### ISSUE TITLE
[Encryption-Idea] use the recovery key to re-encrypt files if user was added to group

### ISSUE THREAD

**Issue by schiessle** [owncloud/core#10010]
I discussed the problem with @cdamken that user often have problems if they add new users to a group because by default the new user will not be able to decrypt the files shared with the group.

There is only one possible solution I could think of:

General thoughts:
- encryption is always a trade-off between security and convenience, you can't have both at 100%

Precondition:
- recovery key needs to be enabled
- all user need to use the recovery key

Solution 1:
- when adding a user to a group the admin could enter the recovery key and trigger a re-encryption with the new user list.

Advantage: the new user will get immediately access to the file
Disadvantage: for large installation this could take a long time.

Solution 2:
- have a script which re-encrypt the files with the recovery key when a new user was added to a group

Advantage: The script could be executed by the admin in the background
Disadvantage: extra manual step for the admin

I think solution 1 is a no-go because we can't expect that the admin needs to wait for a long time after he added a user to a group until all the re-encryption was finished.

Solution could be possible if we really want to go this way. What we need to consider:
- Adds complexity for a solution which only works under certain pre-condition. 
- How often does a ownCloud installation meet this pre-condition that every user uses the recovery key (remeber: this also means less-security)? 
- Already the calculation of the shares which needs to be re-encrypted could be quite expensive, think about re-re-...-shares where at some point the group was involved to whom the user was added. (would be much easier if #9058 is implemented)
- It would still need manual interaction (if we go for the only feasible solution, solution 2)

I tend to stay away from the technical solution and continue with the personal solution: "Hey, I'm new in your working group, please re-share the document with me so that I can work on it." Other encryption systems also doesn't provide any automated solution to add new users. But if it is really important for some users we could think about implementing solution 2 after considering all the advantages and disadvantages.

cc @craigpg @karlitschek @MTRichards

**Comment by MorrisJobke** [comment]
@karlitschek @schiesbn I guess this is out of scope for 8.0 - postpone to 8.1?

**Comment by schiesbn** [comment]
> I guess this is out of scope for 8.0 - postpone to 8.1?

@MorrisJobke From my point of view: yes.
Up to now we don't have a MQ system in ownCloud so it is more a theoretical solution at this point in time.

**Comment by MorrisJobke** [comment]
@craigpg FYI: This is a high prio blue ticket but not solvable in a short time frame. This needs more engineering than just a quick fix which can be easiely deployed.

**Comment by michaelstingl** [comment]
00002415

**Comment by cdamken** [comment]
00002170

**Comment by PVince81** [comment]
@schiesbn does one of the new approaches in 8.2 help fixing this ?

**Comment by schiesbn** [comment]
It is solved if the user decides to use the master key instead of individual keys. But there is still the ideas of doing something like this: https://github.com/owncloud/core/issues/16332#issuecomment-108460634

**Comment by cmonteroluque** [comment]
@schiesbn that dropped to 9.0. Moving this one to track that

**Comment by MorrisJobke** [comment]
All blue cases closed -> remove blue ticket

**Comment by atroxix** [comment]
Our company has several OwnCloud servers set up in separate offices and all of those use LDAP authentication, so our use-case is indeed the one where admin interaction cannot be assumed at all times.

How about handing over the responsibility of re-sharing data to the file owner? Something like:
1. User A shares data to group 1 which has users B, C, D
2. User E is added to group 1
3. User A receives notification (either from some background process (cronjob) or in web UI) that he has data that needs to be reshared with group 1 because user E was added to the group.
  3.1. User A logins to OwnCloud web UI and somewhere among notifications there's link to list of files-folders that need to be re-shared. In that list for every file/folder it could be shown in the right-hand sidebar which users miss the re-encrypted data.
  3.2. User A goes to that list and can select some or all files-folders that need to be re-shared.
4. User E logins to OwnCloud and can use basically the same list/view about the files which have been shared to him, but haven't been encrypted with his certificate.

In that case re-encryption would be visible and not be done behind users' backs. All this activity should be logged too.

**Comment by bboule** [comment]
@cdamken looks like this has moved to 9 are you able to update the user?

**Comment by cdamken** [comment]
I informed to our partner, he is the one who has contact with the customer.

BTW, the new information from this case is here: https://github.com/owncloud/enterprise/issues/482

**Comment by atroxix** [comment]
The above link about enterprise#482 does not work :(

**Comment by MorrisJobke** [comment]
> The above link about enterprise#482 does not work :(

It's internal stuff for employees only, because it could contain confidential data ;)

**Comment by PVince81** [comment]
Moving to 9.2. Might be worth looking into it.

But there was also this parallel discussion: https://github.com/owncloud/core/issues/16332#issuecomment-108459798

**Comment by PVince81** [comment]
Would move to backlog as this is a bigger topic, big in discussion and likely big in implementing the proposed solutions. Current workaround is to use master key instead of the complex encryption scheme.

@butonic @pmaier1

**Comment by PVince81** [comment]
Moving to backlog, needs to be reevaluated and scheduled.

This could take 5-10 md including research and testing.

**Comment by PVince81** [comment]
> I think we should just implement an alternative and simpler system as discussed.

There is a simpler system nowadays: master key encryption
