### ISSUE TITLE
Searching for image and selecting doesn't do anything via the search box

### ISSUE THREAD

**Issue by Crasha** [owncloud/core#10028]
Tried searching for a particular image which I found in the search bar, however upon selecting the image and was thought to be taken to the image, it just sent me to the folder where the image was stored when there are a lot of files in the folder. I presume it should either...

1.) Open the image
or
2.) Only show the image in the list so that we can delete/share/download etc

**Comment by PVince81** [comment]
The scrolling should work now as per https://github.com/owncloud/core/issues/9195
Also I believe that OC 8 will bring a new way of displaying search results, which comes with its own file actions.

Closing hence.
