### ISSUE TITLE
owncloud 7: clicking File -> Apps hangs server

### ISSUE THREAD

**Issue by boxerab** [owncloud/core#10030]
Vanilla install:  ubuntu 14, mysql, owncloud 7

Selecting File -> Apps gives a spinning icon, and spinning never stops.

After this, I cannot log in for about 5 minutes.

**Comment by GitHubGeek** [comment]
Same issue here. Brand new install of oC 7.0.4.2 on Ubuntu 14.04. Running nginx, postgres, uwsgi.

`/owncloud/index.php/settings/apps?installed` took over 60 seconds to load.

I wonder if this is fixed in 8.0?

**Comment by LukasReschke** [comment]
Folks, you are all reporting different issues in one issue tracker. While it might look the same ("ownCloud does not work") the technical reason is indeed very different.

Please open new issues if you encounter any error and use the issue template. THX.
