### ISSUE TITLE
Deleting group with assigned users

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#10057]
I copied this from owncloud/documentation#456 by @KeyboardMidas :

In working in the User page, I noticed that you can delete a group with users still assigned to the group. In doing that, you no longer have the ability to view all members of a group (because it no longer exists) and you can't recreate a group of the same name until all users are removed from the group you deleted. It seems that the group is still in existence [at least residually] and you have to look at each user individually and remove (uncheck) the group.

As a best practice, I have documented that the admin should remove each user from the group BEFORE deleting the group. However, perhaps it would be best to 1) not allow the removal of the group if it contains any users, and/or 2) remove the group assignments from all users when a group is deleted?

I did migrate from the User page and then back into the User page to see if the group assignments would be removed from the users, but the assignment appeared to persist. I did not try logging out and then back in again. If that is a requirement, or if I'm missing something in how the deleted group is propagated on the ownCloud system, please let me know.

---

In my opinion this is an issue of the implementation and not of the documentation.

@blizzz @raghunayyar Please state on this.

@karlitschek @craigpg I also would rate this as a bigger issue, because it can cause severe trouble in the administration of large user bases.

**Comment by Xenopathic** [comment]
Looks like this has been solved. Only slight issue is that the 'undo' 5 second timeout results in the group still existing for a short while, during which a new group with the same name cannot be created. But after the timeout expires, the group is deleted and all users assigned to that group are no longer members of it, and adding a new group with the same name is successful. Don't know when it was fixed, but it was :smile:
