### ISSUE TITLE
LDAP-Connect

### ISSUE THREAD

**Issue by haglo** [owncloud/core#10052]
I use owncloud 7.0, LDAP user and group backend 0.4.3, LDAP-Server openDJ 2.7, with actual mysql and php.
With other programs like phpLDAPAdmin or gerrit i can normaly connect to the LDAP-Server, but i can not connect wirth ownCloud to the LDAP-Server.

The last 100 lines of the logfile are:

{"reqId":"53d9053b0647e","app":"user_ldap","message":"Bind failed: -1: Can't contact LDAP server","level":3,"time":"July 30, 2014 16:46:19","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d9053b0647e","app":"user_ldap","message":"Connection could not be established","level":3,"time":"July 30, 2014 16:46:19","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d9053b0647e","app":"user_ldap","message":"Connection could not be established","level":3,"time":"July 30, 2014 16:46:19","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d9053b0647e","app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"July 30, 2014 16:46:19","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d9053b0647e","app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"July 30, 2014 16:46:19","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d9053b0647e","app":"user_ldap","message":"Connection could not be established","level":3,"time":"July 30, 2014 16:46:19","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d9053b0647e","app":"user_ldap","message":"Connection could not be established","level":3,"time":"July 30, 2014 16:46:19","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d9053b0647e","app":"user_ldap","message":"Could not search, because resource is missing.","level":0,"time":"July 30, 2014 16:46:19","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d9053b64eb9","app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"July 30, 2014 16:46:19","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/testConfiguration.php"}
{"reqId":"53d9053b64eb9","app":"user_ldap","message":"Connection could not be established","level":3,"time":"July 30, 2014 16:46:19","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/testConfiguration.php"}
{"reqId":"53d9053b77cf4","app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"July 30, 2014 16:46:19","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/testConfiguration.php"}
{"reqId":"53d9053b77cf4","app":"user_ldap","message":"Connection could not be established","level":3,"time":"July 30, 2014 16:46:19","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/testConfiguration.php"}
{"reqId":"53d9053b8b88d","app":"user_ldap","message":"Count filter:  (|(objectclass=inetOrgPerson))","level":0,"time":"July 30, 2014 16:46:19","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d9053b8b88d","app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"July 30, 2014 16:46:19","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d9053b8b88d","app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"July 30, 2014 16:46:19","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d9053b8b88d","app":"user_ldap","message":"Connection could not be established","level":3,"time":"July 30, 2014 16:46:19","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d9053b8b88d","app":"user_ldap","message":"Connection could not be established","level":3,"time":"July 30, 2014 16:46:19","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d9053b8b88d","app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"July 30, 2014 16:46:19","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d9053b8b88d","app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"July 30, 2014 16:46:19","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d9053b8b88d","app":"user_ldap","message":"Connection could not be established","level":3,"time":"July 30, 2014 16:46:19","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d9053b8b88d","app":"user_ldap","message":"Connection could not be established","level":3,"time":"July 30, 2014 16:46:19","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d9053b8b88d","app":"user_ldap","message":"Could not search, because resource is missing.","level":0,"time":"July 30, 2014 16:46:19","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d9053ba7d9f","app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"July 30, 2014 16:46:19","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/testConfiguration.php"}
{"reqId":"53d9053ba7d9f","app":"user_ldap","message":"Connection could not be established","level":3,"time":"July 30, 2014 16:46:19","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/testConfiguration.php"}
{"reqId":"53d9054fe58d0","app":"user_ldap","message":"Configuration Error (prefix ): either no password is given for theuser agent or a password is given, but not anLDAP agent.","level":2,"time":"July 30, 2014 16:46:39","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/testConfiguration.php"}
{"reqId":"53d9054fe58d0","app":"user_ldap","message":"Configuration Error (prefix ): either no password is given for theuser agent or a password is given, but not anLDAP agent.","level":2,"time":"July 30, 2014 16:46:39","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/testConfiguration.php"}
{"reqId":"53d9054fe58d0","app":"user_ldap","message":"Configuration Error (prefix ): either no password is given for theuser agent or a password is given, but not anLDAP agent.","level":2,"time":"July 30, 2014 16:46:39","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/testConfiguration.php"}
{"reqId":"53d9054fe58d0","app":"user_ldap","message":"Configuration Error (prefix ): either no password is given for theuser agent or a password is given, but not anLDAP agent.","level":2,"time":"July 30, 2014 16:46:39","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/testConfiguration.php"}
{"reqId":"53d9054fe58d0","app":"user_ldap","message":"Configuration Error (prefix ): either no password is given for theuser agent or a password is given, but not anLDAP agent.","level":2,"time":"July 30, 2014 16:46:39","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/testConfiguration.php"}
{"reqId":"53d9054fe58d0","app":"user_ldap","message":"Configuration Error (prefix ): either no password is given for theuser agent or a password is given, but not anLDAP agent.","level":2,"time":"July 30, 2014 16:46:39","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/testConfiguration.php"}
{"reqId":"53d9054fe58d0","app":"user_ldap","message":"Configuration Error (prefix ): either no password is given for theuser agent or a password is given, but not anLDAP agent.","level":2,"time":"July 30, 2014 16:46:39","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/testConfiguration.php"}
{"reqId":"53d9054fe58d0","app":"user_ldap","message":"Configuration Error (prefix ): either no password is given for theuser agent or a password is given, but not anLDAP agent.","level":2,"time":"July 30, 2014 16:46:39","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/testConfiguration.php"}
{"reqId":"53d9054fe58d0","app":"user_ldap","message":"Configuration Error (prefix ): either no password is given for theuser agent or a password is given, but not anLDAP agent.","level":2,"time":"July 30, 2014 16:46:39","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/testConfiguration.php"}
{"reqId":"53d9054fe58d0","app":"user_ldap","message":"Configuration Error (prefix ): either no password is given for theuser agent or a password is given, but not anLDAP agent.","level":2,"time":"July 30, 2014 16:46:39","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/testConfiguration.php"}
{"reqId":"53d90555a8464","app":"user_ldap","message":"Configuration Error (prefix ): either no password is given for theuser agent or a password is given, but not anLDAP agent.","level":2,"time":"July 30, 2014 16:46:45","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d90555a8464","app":"user_ldap","message":"Configuration Error (prefix ): either no password is given for theuser agent or a password is given, but not anLDAP agent.","level":2,"time":"July 30, 2014 16:46:45","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d90555a8464","app":"user_ldap","message":"Configuration Error (prefix ): either no password is given for theuser agent or a password is given, but not anLDAP agent.","level":2,"time":"July 30, 2014 16:46:45","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d90555a8464","app":"user_ldap","message":"Configuration Error (prefix ): either no password is given for theuser agent or a password is given, but not anLDAP agent.","level":2,"time":"July 30, 2014 16:46:45","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d90555a8464","app":"user_ldap","message":"Configuration Error (prefix ): either no password is given for theuser agent or a password is given, but not anLDAP agent.","level":2,"time":"July 30, 2014 16:46:45","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d90555a8464","app":"user_ldap","message":"Configuration Error (prefix ): either no password is given for theuser agent or a password is given, but not anLDAP agent.","level":2,"time":"July 30, 2014 16:46:45","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d90555a8464","app":"user_ldap","message":"Configuration Error (prefix ): either no password is given for theuser agent or a password is given, but not anLDAP agent.","level":2,"time":"July 30, 2014 16:46:45","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d90555a8464","app":"user_ldap","message":"Configuration Error (prefix ): either no password is given for theuser agent or a password is given, but not anLDAP agent.","level":2,"time":"July 30, 2014 16:46:45","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d90555a8464","app":"user_ldap","message":"Configuration Error (prefix ): either no password is given for theuser agent or a password is given, but not anLDAP agent.","level":2,"time":"July 30, 2014 16:46:45","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d90555a8464","app":"user_ldap","message":"Configuration Error (prefix ): either no password is given for theuser agent or a password is given, but not anLDAP agent.","level":2,"time":"July 30, 2014 16:46:45","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d90555a8464","app":"user_ldap","message":"Configuration Error (prefix ): either no password is given for theuser agent or a password is given, but not anLDAP agent.","level":2,"time":"July 30, 2014 16:46:45","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d90555d43df","app":"PHP","message":"ldap_bind(): Unable to bind to server: Operations error at \/srv\/www\/htdocs\/owncloud\/apps\/user_ldap\/lib\/ldap.php#252","level":0,"time":"July 30, 2014 16:46:45","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d90555d43df","app":"user_ldap","message":"LDAP error Operations error (1) after calling ldap_bind","level":0,"time":"July 30, 2014 16:46:45","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d90555e6f06","app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"July 30, 2014 16:46:45","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/testConfiguration.php"}
{"reqId":"53d90555e6f06","app":"user_ldap","message":"Connection could not be established","level":3,"time":"July 30, 2014 16:46:45","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/testConfiguration.php"}
{"reqId":"53d905d5d4c27","app":"PHP","message":"ldap_bind(): Unable to bind to server: Operations error at \/srv\/www\/htdocs\/owncloud\/apps\/user_ldap\/lib\/ldap.php#252","level":0,"time":"July 30, 2014 16:48:53","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905d5d4c27","app":"user_ldap","message":"LDAP error Operations error (1) after calling ldap_bind","level":0,"time":"July 30, 2014 16:48:53","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905d5e872c","app":"PHP","message":"ldap_bind(): Unable to bind to server: Operations error at \/srv\/www\/htdocs\/owncloud\/apps\/user_ldap\/lib\/ldap.php#252","level":0,"time":"July 30, 2014 16:48:53","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905d5e872c","app":"user_ldap","message":"LDAP error Operations error (1) after calling ldap_bind","level":0,"time":"July 30, 2014 16:48:53","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905d6101d9","app":"user_ldap","message":"Wiz: Final filter (|(objectclass=inetOrgPerson))","level":0,"time":"July 30, 2014 16:48:54","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905d6238b9","app":"user_ldap","message":"Count filter:  (|(objectclass=inetOrgPerson))","level":0,"time":"July 30, 2014 16:48:54","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905d6238b9","app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"July 30, 2014 16:48:54","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905d6238b9","app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"July 30, 2014 16:48:54","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905d6238b9","app":"user_ldap","message":"Connection could not be established","level":3,"time":"July 30, 2014 16:48:54","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905d6238b9","app":"user_ldap","message":"Connection could not be established","level":3,"time":"July 30, 2014 16:48:54","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905d6238b9","app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"July 30, 2014 16:48:54","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905d6238b9","app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"July 30, 2014 16:48:54","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905d6238b9","app":"user_ldap","message":"Connection could not be established","level":3,"time":"July 30, 2014 16:48:54","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905d6238b9","app":"user_ldap","message":"Connection could not be established","level":3,"time":"July 30, 2014 16:48:54","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905d6238b9","app":"user_ldap","message":"Could not search, because resource is missing.","level":0,"time":"July 30, 2014 16:48:54","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905d63798c","app":"user_ldap","message":"Count filter:  (|(objectclass=inetOrgPerson))","level":0,"time":"July 30, 2014 16:48:54","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905d63798c","app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"July 30, 2014 16:48:54","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905d63798c","app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"July 30, 2014 16:48:54","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905d63798c","app":"user_ldap","message":"Connection could not be established","level":3,"time":"July 30, 2014 16:48:54","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905d63798c","app":"user_ldap","message":"Connection could not be established","level":3,"time":"July 30, 2014 16:48:54","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905d63798c","app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"July 30, 2014 16:48:54","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905d63798c","app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"July 30, 2014 16:48:54","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905d63798c","app":"user_ldap","message":"Connection could not be established","level":3,"time":"July 30, 2014 16:48:54","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905d63798c","app":"user_ldap","message":"Connection could not be established","level":3,"time":"July 30, 2014 16:48:54","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905d63798c","app":"user_ldap","message":"Could not search, because resource is missing.","level":0,"time":"July 30, 2014 16:48:54","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905d64aeef","app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"July 30, 2014 16:48:54","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/testConfiguration.php"}
{"reqId":"53d905d64aeef","app":"user_ldap","message":"Connection could not be established","level":3,"time":"July 30, 2014 16:48:54","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/testConfiguration.php"}
{"reqId":"53d905d65d9dc","app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"July 30, 2014 16:48:54","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/testConfiguration.php"}
{"reqId":"53d905d65d9dc","app":"user_ldap","message":"Connection could not be established","level":3,"time":"July 30, 2014 16:48:54","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/testConfiguration.php"}
{"reqId":"53d905d670dc6","app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"July 30, 2014 16:48:54","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/testConfiguration.php"}
{"reqId":"53d905d670dc6","app":"user_ldap","message":"Connection could not be established","level":3,"time":"July 30, 2014 16:48:54","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/testConfiguration.php"}
{"reqId":"53d905d9d6586","app":"PHP","message":"ldap_bind(): Unable to bind to server: Operations error at \/srv\/www\/htdocs\/owncloud\/apps\/user_ldap\/lib\/ldap.php#252","level":0,"time":"July 30, 2014 16:48:57","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905d9d6586","app":"user_ldap","message":"LDAP error Operations error (1) after calling ldap_bind","level":0,"time":"July 30, 2014 16:48:57","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905de149b5","app":"PHP","message":"ldap_bind(): Unable to bind to server: Operations error at \/srv\/www\/htdocs\/owncloud\/apps\/user_ldap\/lib\/ldap.php#252","level":0,"time":"July 30, 2014 16:49:02","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905de149b5","app":"user_ldap","message":"LDAP error Operations error (1) after calling ldap_bind","level":0,"time":"July 30, 2014 16:49:02","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905de29be0","app":"user_ldap","message":"Count filter:  (&(|(objectclass=organizationalUnit)))","level":0,"time":"July 30, 2014 16:49:02","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905de29be0","app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"July 30, 2014 16:49:02","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905de29be0","app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"July 30, 2014 16:49:02","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905de29be0","app":"user_ldap","message":"Connection could not be established","level":3,"time":"July 30, 2014 16:49:02","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905de29be0","app":"user_ldap","message":"Connection could not be established","level":3,"time":"July 30, 2014 16:49:02","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905de29be0","app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"July 30, 2014 16:49:02","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905de29be0","app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"July 30, 2014 16:49:02","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905de29be0","app":"user_ldap","message":"Connection could not be established","level":3,"time":"July 30, 2014 16:49:02","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905de29be0","app":"user_ldap","message":"Connection could not be established","level":3,"time":"July 30, 2014 16:49:02","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905de29be0","app":"user_ldap","message":"Could not search, because resource is missing.","level":0,"time":"July 30, 2014 16:49:02","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905de3dd7c","app":"PHP","message":"ldap_bind(): Unable to bind to server: Operations error at \/srv\/www\/htdocs\/owncloud\/apps\/user_ldap\/lib\/ldap.php#252","level":0,"time":"July 30, 2014 16:49:02","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905de3dd7c","app":"user_ldap","message":"LDAP error Operations error (1) after calling ldap_bind","level":0,"time":"July 30, 2014 16:49:02","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php"}
{"reqId":"53d905de50b22","app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"July 30, 2014 16:49:02","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/testConfiguration.php"}
{"reqId":"53d905de50b22","app":"user_ldap","message":"Connection could not be established","level":3,"time":"July 30, 2014 16:49:02","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/testConfiguration.php"}
{"reqId":"53d905e5e4068","app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"July 30, 2014 16:49:09","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/testConfiguration.php"}
{"reqId":"53d905e5e4068","app":"user_ldap","message":"Connection could not be established","level":3,"time":"July 30, 2014 16:49:09","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/testConfiguration.php"}

**Comment by MorrisJobke** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that the issue is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [latest stable version](http://owncloud.org/install/) and then please use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md). You can also contribute directly by providing a patch – see the [developer manual](http://doc.owncloud.org/server/5.0/developer_manual/). :)

Thank you!
