### ISSUE TITLE
Only for specific groups doesn't work with LDAP user and group backend

### ISSUE THREAD

**Issue by galio** [owncloud/core#10081]
### Steps to reproduce
1. Activate "LDAP user and group backend" and configure it
2. Create Group1 and Group2 in owncloud and affect user to groups
3. In Applications checks "Only for specific groups" for calendar (or other apps) and check group1 

### Expected behaviour
app available for group1 and disable for other

### Actual behaviour
Actually the app is disable for all user

### Server configuration
**Operating system**: Debian 7 wheezy amd64

**Web server:** Apache2

**Database:** mysql

**PHP version:** 5.4.4

**ownCloud version:** ownCloud 7.0.0 (stable) 

**Updated from an older ownCloud or fresh install:** Updated from 6, but tested with fresh install

**List of activated apps:** Activity, Calendar, Contacts, Deleted files, First Run Wizard, Full Text Search, LDAP user and group backend, PDF Viewer, Pictures, Share Files, Text Editor, Updater, Versions

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '524eb3ec49325',
  'passwordsalt' => '****************************',
  'datadirectory' => '/var/www/data',
  'dbtype' => 'mysql',
  'version' => '7.0.0.8',
  'dbname' => 'owncloud',
  'dbhost' => '*****************',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '**************',
  'installed' => true,
  'maxZipInputSize' => 838860800,
  'allowZipDownload' => true,
  'ldapIgnoreNamingRules' => false,
  'loglevel' => '2',
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' => 
  array (
    0 => 'cloud.mri.cnrs.fr',
  ),
);

```

**Are you using external storage, if yes which one:** nfs mount

**Are you using encryption:** no

### Client configuration
**Browser:** Firefox

**Operating system:** Ubuntu 14.04 amd64

#### Web server error log
[Tue Jul 29 15:10:46 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/apps (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/apps/files/
[Tue Jul 29 15:11:05 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/apps (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/apps?installed
[Tue Jul 29 15:11:22 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/apps (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/apps?appid=updater
[Tue Jul 29 15:16:01 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/apps (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/apps/files/
[Tue Jul 29 15:16:16 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/apps (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/apps?installed
[Tue Jul 29 15:16:30 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/apps (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/apps?appid=disablerememberlogin
[Tue Jul 29 15:16:32 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/apps (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/apps?appid=disablerememberlogin
[Tue Jul 29 15:17:38 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/apps (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/apps?appid=disablerememberlogin
[Tue Jul 29 16:17:10 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/apps (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/apps/files/
[Tue Jul 29 16:18:37 2014] [error] [client 10.5.0.116] Negotiation: discovered file(s) matching request: /var/www/settings/users (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/apps/calendar
[Tue Jul 29 16:19:36 2014] [error] [client 10.5.0.116] Negotiation: discovered file(s) matching request: /var/www/settings/users (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/apps/calendar
[Tue Jul 29 16:20:54 2014] [error] [client 10.5.0.116] Negotiation: discovered file(s) matching request: /var/www/settings/ajax/userlist (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/users
[Tue Jul 29 16:20:56 2014] [error] [client 10.5.0.116] Negotiation: discovered file(s) matching request: /var/www/settings/ajax/userlist (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/users
[Tue Jul 29 16:20:58 2014] [error] [client 10.5.0.116] Negotiation: discovered file(s) matching request: /var/www/settings/ajax/userlist (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/users
[Tue Jul 29 16:21:01 2014] [error] [client 10.5.0.116] Negotiation: discovered file(s) matching request: /var/www/settings/ajax/userlist (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/users
[Tue Jul 29 16:21:07 2014] [error] [client 10.5.0.116] Negotiation: discovered file(s) matching request: /var/www/settings/users (None could be negotiated).
[Tue Jul 29 16:21:08 2014] [error] [client 10.5.0.116] Negotiation: discovered file(s) matching request: /var/www/settings/users (None could be negotiated).
[Tue Jul 29 16:21:14 2014] [error] [client 10.5.0.116] Negotiation: discovered file(s) matching request: /var/www/settings/users (None could be negotiated).
[Tue Jul 29 16:21:19 2014] [error] [client 10.5.0.116] Negotiation: discovered file(s) matching request: /var/www/settings/ajax/userlist (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/users
[Tue Jul 29 16:21:20 2014] [error] [client 10.5.0.116] Negotiation: discovered file(s) matching request: /var/www/settings/ajax/userlist (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/users
[Tue Jul 29 16:21:38 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/users (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/apps?installed
[Tue Jul 29 16:21:43 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/ajax/userlist (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/users
[Tue Jul 29 16:21:58 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/ajax/userlist (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/users
[Tue Jul 29 16:22:05 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/ajax/grouplist (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/users
[Tue Jul 29 16:22:06 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/ajax/grouplist (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/users
[Tue Jul 29 16:22:11 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/ajax/userlist (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/users
[Tue Jul 29 16:22:14 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/ajax/userlist (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/users
[Tue Jul 29 16:22:38 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/ajax/userlist (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/users
[Tue Jul 29 16:22:43 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/apps (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/users
[Tue Jul 29 16:25:09 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/apps (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/users
[Tue Jul 29 16:27:53 2014] [error] [client 193.49.132.72] client denied by server configuration: /var/www/data/htaccesstest.txt
[Tue Jul 29 16:28:30 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/apps (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/admin
[Tue Jul 29 16:31:55 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/apps (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/apps?installed
[Tue Jul 29 16:31:58 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/apps (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/apps?installed
[Tue Jul 29 16:34:41 2014] [error] [client 193.49.132.72] client denied by server configuration: /var/www/data/htaccesstest.txt
[Tue Jul 29 16:36:06 2014] [error] [client 193.49.132.72] client denied by server configuration: /var/www/data/htaccesstest.txt
[Tue Jul 29 16:37:10 2014] [error] [client 193.49.132.72] client denied by server configuration: /var/www/data/htaccesstest.txt
[Tue Jul 29 16:38:20 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/apps (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/admin
[Tue Jul 29 16:39:28 2014] [error] [client 10.5.0.131] File does not exist: /var/www/favicon.ico
[Tue Jul 29 16:39:28 2014] [error] [client 10.5.0.131] File does not exist: /var/www/favicon.ico
[Tue Jul 29 16:39:46 2014] [error] [client 193.49.132.72] client denied by server configuration: /var/www/data/htaccesstest.txt
[Tue Jul 29 16:40:13 2014] [error] [client 193.49.132.72] client denied by server configuration: /var/www/data/htaccesstest.txt
[Tue Jul 29 16:40:45 2014] [error] [client 193.49.132.72] client denied by server configuration: /var/www/data/htaccesstest.txt
[Tue Jul 29 16:41:17 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/users (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/admin
[Tue Jul 29 16:41:20 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/ajax/userlist (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/users
[Tue Jul 29 16:41:26 2014] [error] [client 193.49.132.72] client denied by server configuration: /var/www/data/htaccesstest.txt
[Tue Jul 29 16:47:18 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/apps (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/admin
[Tue Jul 29 16:47:33 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/users (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/apps?installed
[Tue Jul 29 16:47:47 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/apps (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/users
[Tue Jul 29 16:47:50 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/users (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/apps/files/
[Tue Jul 29 18:02:25 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/apps (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/users
[Wed Jul 30 02:01:43 2014] [error] [client 54.187.189.195] File does not exist: /var/www/admin
[Wed Jul 30 16:10:48 2014] [error] [client 10.5.0.131] File does not exist: /var/www/favicon.ico
[Wed Jul 30 16:17:39 2014] [notice] caught SIGTERM, shutting down
[Wed Jul 30 16:17:40 2014] [notice] Apache/2.2.22 (Debian) PHP/5.4.4-14+deb7u4 mod_ssl/2.2.22 OpenSSL/1.0.1e configured -- resuming normal operations
[Wed Jul 30 16:18:22 2014] [notice] caught SIGTERM, shutting down
PHP Warning:  PHP Startup: apc.shm_segments setting ignored in MMAP mode in Unknown on line 0
[Wed Jul 30 16:18:23 2014] [notice] Apache/2.2.22 (Debian) PHP/5.4.4-14+deb7u4 mod_ssl/2.2.22 OpenSSL/1.0.1e configured -- resuming normal operations
[Wed Jul 30 16:24:32 2014] [notice] caught SIGTERM, shutting down
PHP Warning:  PHP Startup: apc.shm_segments setting ignored in MMAP mode in Unknown on line 0
[Wed Jul 30 16:24:34 2014] [notice] Apache/2.2.22 (Debian) PHP/5.4.4-14+deb7u4 mod_ssl/2.2.22 OpenSSL/1.0.1e configured -- resuming normal operations
[Wed Jul 30 16:31:53 2014] [notice] caught SIGTERM, shutting down
PHP Warning:  PHP Startup: apc.shm_segments setting ignored in MMAP mode in Unknown on line 0
[Wed Jul 30 16:31:54 2014] [notice] Apache/2.2.22 (Debian) PHP/5.4.4-14+deb7u4 mod_ssl/2.2.22 OpenSSL/1.0.1e configured -- resuming normal operations
[Wed Jul 30 16:35:03 2014] [notice] caught SIGTERM, shutting down
[Wed Jul 30 16:35:04 2014] [notice] Apache/2.2.22 (Debian) PHP/5.4.4-14+deb7u4 mod_ssl/2.2.22 OpenSSL/1.0.1e configured -- resuming normal operations
[Wed Jul 30 16:37:49 2014] [error] [client 10.5.0.131] script '/var/www/apc.php' not found or unable to stat
[Thu Jul 31 01:05:03 2014] [error] [client 217.144.201.243] File does not exist: /var/www/vtigercrm
[Thu Jul 31 10:24:25 2014] [error] [client 10.5.0.131] File does not exist: /var/www/favicon.ico
[Thu Jul 31 10:24:25 2014] [error] [client 10.5.0.131] File does not exist: /var/www/favicon.ico
[Thu Jul 31 10:25:05 2014] [notice] caught SIGTERM, shutting down
[Thu Jul 31 10:25:06 2014] [notice] Apache/2.2.22 (Debian) PHP/5.4.4-14+deb7u4 mod_ssl/2.2.22 OpenSSL/1.0.1e configured -- resuming normal operations
[Thu Jul 31 11:10:24 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/personal (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/apps/files?dir=%2F
[Thu Jul 31 11:17:10 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/apps (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/apps/files/
[Thu Jul 31 11:17:46 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/apps (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/apps/files/
[Thu Jul 31 11:19:55 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/apps (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/apps/files/
[Thu Jul 31 11:20:19 2014] [error] [client 193.49.132.72] client denied by server configuration: /var/www/data/htaccesstest.txt
[Thu Jul 31 11:21:04 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/users (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/admin
[Thu Jul 31 11:21:12 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/ajax/userlist (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/users
[Thu Jul 31 11:21:46 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/apps (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/users
[Thu Jul 31 11:28:10 2014] [error] [client 193.49.132.72] client denied by server configuration: /var/www/data/htaccesstest.txt
[Thu Jul 31 11:35:10 2014] [error] [client 193.49.132.72] client denied by server configuration: /var/www/data/htaccesstest.txt
[Thu Jul 31 11:36:40 2014] [error] [client 193.49.132.72] client denied by server configuration: /var/www/data/htaccesstest.txt
[Thu Jul 31 11:40:25 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/apps (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/admin
[Thu Jul 31 11:42:07 2014] [error] [client 193.49.132.72] client denied by server configuration: /var/www/data/htaccesstest.txt
[Thu Jul 31 12:39:17 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/apps (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/apps/files/
[Thu Jul 31 12:43:07 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/apps (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/apps/files/
[Thu Jul 31 13:51:05 2014] [error] [client 193.49.132.72] client denied by server configuration: /var/www/data/htaccesstest.txt
[Thu Jul 31 13:52:27 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/apps (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/admin
[Thu Jul 31 13:53:28 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/apps (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/apps/files/
[Thu Jul 31 13:53:51 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/apps (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/apps?installed
[Thu Jul 31 14:01:00 2014] [error] [client 193.49.132.72] client denied by server configuration: /var/www/data/htaccesstest.txt
[Thu Jul 31 14:20:02 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/apps (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/apps/files/
[Thu Jul 31 15:03:03 2014] [error] [client 193.49.132.72] client denied by server configuration: /var/www/data/htaccesstest.txt
[Thu Jul 31 15:03:49 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/users (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/admin
[Thu Jul 31 15:03:54 2014] [error] [client 193.49.132.72] client denied by server configuration: /var/www/data/htaccesstest.txt
[Thu Jul 31 15:04:02 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/apps (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/settings/admin
[Thu Jul 31 15:05:50 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/apps (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/apps/files/
[Thu Jul 31 15:06:33 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/apps (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/apps/files/
[Thu Jul 31 15:07:55 2014] [error] [client 10.5.0.131] Negotiation: discovered file(s) matching request: /var/www/settings/apps (None could be negotiated)., referer: https://cloud.mri.cnrs.fr/index.php/apps/files/

#### ownCloud log (data/owncloud.log)

{"app":"user_ldap","message":"Configuration Error (prefix ): login filter does not contain %uid place holder.","level":2,"time":"2014-07-31T13:03:37+00:00"}
{"app":"user_ldap","message":"Configuration Error (prefix ): No LDAP Login Filter given!","level":2,"time":"2014-07-31T13:03:37+00:00"}
{"app":"user_ldap","message":"Configuration Error (prefix ): login filter does not contain %uid place holder.","level":2,"time":"2014-07-31T13:03:37+00:00"}
{"app":"user_ldap","message":"Configuration Error (prefix ): No LDAP Login Filter given!","level":2,"time":"2014-07-31T13:03:37+00:00"}
{"app":"user_ldap","message":"Configuration Error (prefix ): login filter does not contain %uid place holder.","level":2,"time":"2014-07-31T13:03:37+00:00"}
{"app":"user_ldap","message":"Configuration Error (prefix ): No LDAP Login Filter given!","level":2,"time":"2014-07-31T13:03:37+00:00"}
{"app":"user_ldap","message":"Configuration Error (prefix ): login filter does not contain %uid place holder.","level":2,"time":"2014-07-31T13:03:37+00:00"}
{"app":"user_ldap","message":"Configuration Error (prefix ): No LDAP Login Filter given!","level":2,"time":"2014-07-31T13:03:37+00:00"}
{"app":"user_ldap","message":"Configuration Error (prefix ): login filter does not contain %uid place holder.","level":2,"time":"2014-07-31T13:03:37+00:00"}
{"app":"user_ldap","message":"Configuration Error (prefix ): No LDAP Login Filter given!","level":2,"time":"2014-07-31T13:03:37+00:00"}
{"app":"user_ldap","message":"Configuration Error (prefix ): login filter does not contain %uid place holder.","level":2,"time":"2014-07-31T13:03:37+00:00"}
{"app":"user_ldap","message":"Configuration Error (prefix ): No LDAP Login Filter given!","level":2,"time":"2014-07-31T13:03:37+00:00"}
{"app":"user_ldap","message":"Configuration Error (prefix ): login filter does not contain %uid place holder.","level":2,"time":"2014-07-31T13:03:37+00:00"}
{"app":"user_ldap","message":"Configuration Error (prefix ): No LDAP Login Filter given!","level":2,"time":"2014-07-31T13:03:37+00:00"}
{"app":"user_ldap","message":"Configuration Error (prefix ): login filter does not contain %uid place holder.","level":2,"time":"2014-07-31T13:03:37+00:00"}
{"app":"user_ldap","message":"Configuration Error (prefix ): No LDAP Login Filter given!","level":2,"time":"2014-07-31T13:03:37+00:00"}
{"app":"user_ldap","message":"Configuration Error (prefix ): login filter does not contain %uid place holder.","level":2,"time":"2014-07-31T13:03:37+00:00"}
{"app":"user_ldap","message":"Configuration Error (prefix ): No LDAP Login Filter given!","level":2,"time":"2014-07-31T13:03:41+00:00"}
{"app":"user_ldap","message":"Configuration Error (prefix ): login filter does not contain %uid place holder.","level":2,"time":"2014-07-31T13:03:41+00:00"}
{"app":"user_ldap","message":"Configuration Error (prefix ): No LDAP Login Filter given!","level":2,"time":"2014-07-31T13:03:41+00:00"}
{"app":"user_ldap","message":"Configuration Error (prefix ): login filter does not contain %uid place holder.","level":2,"time":"2014-07-31T13:03:41+00:00"}
{"app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"2014-07-31T13:03:41+00:00"}
{"app":"user_ldap","message":"Bind failed: -1: Can't contact LDAP server","level":3,"time":"2014-07-31T13:03:41+00:00"}
{"app":"user_ldap","message":"Bind failed: -1: Can't contact LDAP server","level":3,"time":"2014-07-31T13:03:41+00:00"}
{"app":"user_ldap","message":"Connection could not be established","level":3,"time":"2014-07-31T13:03:41+00:00"}
{"app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"2014-07-31T13:03:41+00:00"}
{"app":"user_ldap","message":"Bind failed: -1: Can't contact LDAP server","level":3,"time":"2014-07-31T13:03:41+00:00"}
{"app":"user_ldap","message":"Connection could not be established","level":3,"time":"2014-07-31T13:03:41+00:00"}
{"app":"PHP","message":"ldap_search(): Partial search results returned: Sizelimit exceeded at \/var\/www\/apps\/user_ldap\/lib\/ldap.php#252","level":3,"time":"2014-07-31T13:03:46+00:00"}
{"app":"PHP","message":"ldap_search(): Partial search results returned: Sizelimit exceeded at \/var\/www\/apps\/user_ldap\/lib\/ldap.php#252","level":3,"time":"2014-07-31T13:03:46+00:00"}
{"app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"2014-07-31T13:03:46+00:00"}
{"app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"2014-07-31T13:03:47+00:00"}
{"app":"PHP","message":"ldap_control_paged_result_response(): Result is: No such object (32) at \/var\/www\/apps\/user_ldap\/lib\/ldap.php#58","level":3,"time":"2014-07-31T13:03:47+00:00"}
{"app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"2014-07-31T13:03:48+00:00"}
{"app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"2014-07-31T13:03:49+00:00"}
{"app":"PHP","message":"ldap_control_paged_result_response(): Result is: No such object (32) at \/var\/www\/apps\/user_ldap\/lib\/ldap.php#58","level":3,"time":"2014-07-31T13:03:49+00:00"}
{"app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"2014-07-31T13:03:55+00:00"}
{"app":"OCP\\Share","message":"Sharing backend OC_Share_Backend_Calendar not registered, OC_Share_Backend_Calendar is already registered for calendar","level":2,"time":"2014-07-31T13:04:18+00:00"}
{"app":"OCP\\Share","message":"Sharing backend OC_Share_Backend_Event not registered, OC_Share_Backend_Event is already registered for event","level":2,"time":"2014-07-31T13:04:18+00:00"}
{"app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"2014-07-31T13:04:42+00:00"}
{"app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"2014-07-31T13:05:17+00:00"}
{"app":"OCP\\Share","message":"Sharing backend OC_Share_Backend_Calendar not registered, OC_Share_Backend_Calendar is already registered for calendar","level":2,"time":"2014-07-31T13:06:05+00:00"}
{"app":"OCP\\Share","message":"Sharing backend OC_Share_Backend_Event not registered, OC_Share_Backend_Event is already registered for event","level":2,"time":"2014-07-31T13:06:05+00:00"}
{"app":"OCP\\Share","message":"Sharing backend OC_Share_Backend_Calendar not registered, OC_Share_Backend_Calendar is already registered for calendar","level":2,"time":"2014-07-31T13:06:13+00:00"}
{"app":"OCP\\Share","message":"Sharing backend OC_Share_Backend_Event not registered, OC_Share_Backend_Event is already registered for event","level":2,"time":"2014-07-31T13:06:13+00:00"}
{"app":"OCP\\Share","message":"Sharing backend OC_Share_Backend_Calendar not registered, OC_Share_Backend_Calendar is already registered for calendar","level":2,"time":"2014-07-31T13:06:48+00:00"}
{"app":"OCP\\Share","message":"Sharing backend OC_Share_Backend_Event not registered, OC_Share_Backend_Event is already registered for event","level":2,"time":"2014-07-31T13:06:48+00:00"}
{"app":"OCP\\Share","message":"Sharing backend OCA\\Contacts\\Share\\Addressbook not registered, OCA\\Contacts\\Share\\Addressbook is already registered for addressbook","level":2,"time":"2014-07-31T13:06:58+00:00"}
{"app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":2,"time":"2014-07-31T13:07:23+00:00"}
{"app":"OCP\\Share","message":"Sharing backend OCA\\Contacts\\Share\\Addressbook not registered, OCA\\Contacts\\Share\\Addressbook is already registered for addressbook","level":2,"time":"2014-07-31T13:08:10+00:00"}

**Comment by blizzz** [comment]
Cannot reproduce with current stable7 (>=7.0.5). @galio @xtruthx  Please reopen if the issue persists for you.

@bitbull06 what you describe is a different problem.
