### ISSUE TITLE
Can't activate apps when using SSL

### ISSUE THREAD

**Issue by damoosenrw** [owncloud/core#10086]
Hello,

I really like owncloud and I just upgraded from 6.0.4 to the current stable release.

Everything works fine except for one issue: When I use ssl with my owncloud instance I am not able to enable any apps.

When accessing my owncloud instance with ssl and I navigate to the apps section, everytime I click on an app on the left (see attached image) the apps page just reloads. So activating / deactivating apps is impossible.  ![apps_section](https://cloud.githubusercontent.com/assets/8087645/3767606/db97de22-18ce-11e4-9404-ca50f65adbff.jpg)

I can't imagine that noone has yet witnessed this problem, but I haven't found an issue which is similar to what I just described.

**Comment by Xenopathic** [comment]
As of https://github.com/owncloud/core/issues/10086#issuecomment-50973344 the issue has been fixed for the OP. If anyone else is still getting the other assorted issues, please open a new issue report.
