### ISSUE TITLE
Upgrading from OC6.04 to OC7 stops at "This ownCloud instance is currently being updated..."

### ISSUE THREAD

**Issue by baldurmen** [owncloud/core#10091]
<h2> Steps to reproduce</h2>
- upgrade from 6.0.4 to 7.0.0 following http://doc.owncloud.org/server/7.0/admin_manual/maintenance/update.html but with apt-get upgrade
- server upgrade procedure launched by accessing the server using a browser connexion.
- "Updating ownCloud to version 7.0.0, this may take a while."
- The same + "Please reload the page"
- "This ownCloud instance is currently being updated, which may take a while...."

<h2>Expected behaviour</h2>
login screen

<h2>Actual behaviour</h2>
screen with "Updating ownCloud to version 7.0.0, this may take a while..."

<h2>Server configuration</h2>

**Operating system:** Debian testing (jessie)

**Web server:** apache 2.4.10-1

**Database:** mysql 5.5.37

**PHP version:** php5 5.6.0RC2

**ownCloud version:** 7.0.0+dfsg-1 (debian testing)

**Updated from an older ownCloud:** 6.0.4+dfsg-1

**List of activated apps:** no 3party apps installed

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'occ8905d32ce',
  'passwordsalt' => 'XXX',
  'trusted_domains' => 
  array (
    0 => 'cloud.sogeecom.org',
  ),
  'datadirectory' => '/data/Owncloud-data/data',
  'dbtype' => 'mysql',
  'version' => '6.0.4.1',
  'appstoreenabled' => false,
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/usr/share/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
  ),
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'XXX',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'forcessl' => true,
  'enable_previews' => false,
  'theme' => '',
  'maintenance' => true,
);

**Are you using external storage, if yes which one:** yes, local

**Are you using encryption:** no

<h2>Client configuration</h2>

**Browser:** firefox

**Operating system:** debian

<h2>Logs</h2>
* Nothing in /var/log/owncloud.log
* Nothing in /var/log/mysql/error.log
* Nothing in /var/log/apache2/error.log

<h2>Comments</h2>
When the update starts, I can see mysql using cpu. A short while after reloading the page, mysql stops and everything returns to idle.

version.php shows this:
    <?php 
    $OC_Version = array(7,0,0,8);
    $OC_VersionString = '7.0.0';
    $OC_Edition = '';
    $OC_Channel = 'stable';
    $OC_Build = '2014-07-22T20:02:34+00:00';

I did the update with a similar Debian server and everything went wel...

**Comment by enoch85** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that the issue is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [latest stable version](http://owncloud.org/install/) and then please use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md). You can also contribute directly by providing a patch – see the [developer manual](http://doc.owncloud.org/server/8.0/developer_manual/). :)

Thank you!

**Comment by StephaneCouturier** [comment]
Hi, FYI I never solved the issue with oc 7.xx but it got fixed with oc 8.
The upgrade to oc 8 went very smoothly.
Thanks a lot for the great work!
