### ISSUE TITLE
Make testing different versions of ownCloud possible on demo.owncloud.org

### ISSUE THREAD

**Issue by stp-ip** [owncloud/core#10129]
Make it possible again to test development versions of ownCloud on demo.owncloud.org.
Could be done after #10128 is integrated.
Work with CI server to get the latest builds. Work with @DeepDiver1975? @MorrisJobke? to get ideas.

Signed Demo Admin

**Comment by jancborchardt** [comment]
This belongs in the owncloud.org repo. Please reopen there if it’s still valid.
