### ISSUE TITLE
LDAP user and password auto-filled with browser saved credentials when they are originally empty

### ISSUE THREAD

**Issue by tps800** [owncloud/core#10137]
Install owncloud, then call your owncloud URL, log in as administrator, go to configuration. Browser will autofill certain fields, mainly those for ldap-user and password. Since owncloud immediately activates these ldap configuration will be broken if you need anonymous logins to the ldap server.
It would be better, instead of automatically submit any changes to have a button submitting them, instead letting any autofil break the configuration until you reset these fields to their correct setting for your configuration.

SEE https://github.com/owncloud/core/issues/10137#issuecomment-51209222

**Comment by LukasReschke** [comment]
This should be fixed now in master from what I can tell.
