### ISSUE TITLE
WebDAV did not work

### ISSUE THREAD

**Issue by juergeneberhardt** [owncloud/core#10132]
### Steps to reproduce
1. I added a network drive on Windows 7 via davs
2. I opened it and copied some files to/from it
3. I tried to edit a .docx file with Word

### Actual behaviour
A login field appears at Word and in most case Word freeze. When it do not freeze and I type in the login information it works. I also can copy files to/from this folder. But there are also some problems with syncing.
 
### Server configuration
**Operating system**: Debian wheezy

**Web server:** Apache 2.2.22

**Database:** mysql Ver 14.14 Distrib 5.5.38, for debian-linux-gnu (x86_64) using readline 6.2

**PHP version:** PHP 5.4.4-14+deb7u12 (cli) (built: Jun 30 2014 13:15:11)

**ownCloud version:** owmCloud 7RC1

**Updated from an older ownCloud or fresh install:**  fresh install

**List of activated apps:** activity, admin_dependencies_chk, bookmarks, calendar, contacts, documents, files, files_encryption, files_pdfviewer, files_sharing, files_trashbin, files_version, gallery, search_licene, rainloop, tasl_enhanced, ocDashboard

**The content of config/config.php:** 

<?php
$CONFIG = array (
  'instanceid' => 'ocad8ef30fd4',
  'passwordsalt' => 'xxxxxxxxxxxxxx',
  'trusted_domains' =>
  array (
    0 => 'www.apernet.de',
    1 => 'owncloud.apernet.de',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.1.0',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_root',
  'dbpassword' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'installed' => true,
  'loglevel' => '0',
  'mail_smtpmode' => 'php',
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/var/www/owncloud/apps',
      'url' => '/apps',
      'writable' => true,
    ),
    1 =>
    array (
      'path' => '/var/www/owncloud/apps2',
      'url' => '/apps2',
      'writable' => true,
    ),
  ),
  'forcessl' => false,
  'theme' => '',
  'maintenance' => false,
  'mail_smtpauthtype' => 'PLAIN',
  'mail_smtpport' => '587',
  'mail_smtpauth' => true,
  'mail_smtpsecure' => 'tls',
  'xframe_restriction' => false,
  'logtimezone' => 'Europe/Berlin',
  'mail_from_address' => 'administrator',
  'mail_domain' => 'apernet.de',

  'default_language' => 'de',
  'allow_user_to_change_display_name' => false,
  'defaultapp' => 'ocDashboard',

  'updatechecker' => true,
  'check_for_working_webdav' => true,
  'check_for_working_htaccess' => true,

 'preview_libreoffice_path' => '/usr/bin/libreoffice',
);

**Are you using external storage, if yes which one:** none

**Are you using encryption:** yes

### Client configuration
**Browser:**  Firefox 31, IE11, Chrome 36

**Operating system:** Windows 7

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)

{"reqId":"53def39b53fc6","app":"webdav","message":"Sabre\\DAV\\Exception\\NotAuthenticated: No basic authentication headers were found","level":0,"time":"2014-08-04T04:44:43+02:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"53def3a14dabd","app":"webdav","message":"Sabre\\DAV\\Exception\\NotAuthenticated: No basic authentication headers were found","level":0,"time":"2014-08-04T04:44:49+02:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"53def5a3bd343","app":"webdav","message":"Sabre\\DAV\\Exception\\NotAuthenticated: No basic authentication headers were found","level":0,"time":"2014-08-04T04:53:23+02:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"53def5ab665b3","app":"webdav","message":"Sabre\\DAV\\Exception\\NotFound: File with name documents\/WINWORD.EXE could not be located","level":0,"time":"2014-08-04T04:53:31+02:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/documents\/WINWORD.EXE"}
{"reqId":"53def5ab86310","app":"webdav","message":"Sabre\\DAV\\Exception\\NotFound: File with name documents\/jre.exe could not be located","level":0,"time":"2014-08-04T04:53:31+02:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/documents\/jre.exe"}
{"reqId":"53def5aba7add","app":"webdav","message":"Sabre\\DAV\\Exception\\NotFound: File with name documents\/jrew.exe could not be located","level":0,"time":"2014-08-04T04:53:31+02:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/documents\/jrew.exe"}
{"reqId":"53def5abf18d8","app":"webdav","message":"Sabre\\DAV\\Exception\\NotFound: File with name documents\/java.exe could not be located","level":0,"time":"2014-08-04T04:53:31+02:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/documents\/java.exe"}
{"reqId":"53def5ac3a0f1","app":"webdav","message":"Sabre\\DAV\\Exception\\NotFound: File with name documents\/javaw.exe could not be located","level":0,"time":"2014-08-04T04:53:32+02:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/documents\/javaw.exe"}
{"reqId":"53def5af49755","app":"webdav","message":"Sabre\\DAV\\Exception\\NotAuthenticated: No basic authentication headers were found","level":0,"time":"2014-08-04T04:53:35+02:00","method":"OPTIONS","url":"\/owncloud\/remote.php\/webdav\/documents\/"}
{"reqId":"53def5b1398e5","app":"webdav","message":"Sabre\\DAV\\Exception\\NotFound: File with name documents\/Language could not be located","level":0,"time":"2014-08-04T04:53:37+02:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/documents\/Language"}
{"reqId":"53def5b18af93","app":"webdav","message":"Sabre\\DAV\\Exception\\NotFound: File with name documents\/.htm could not be located","level":0,"time":"2014-08-04T04:53:37+02:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/documents\/.htm"}
{"reqId":"53def5efd63cb","app":"webdav","message":"Sabre\\DAV\\Exception\\NotAuthenticated: No basic authentication headers were found","level":0,"time":"2014-08-04T04:54:39+02:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"53def61a37e5b","app":"webdav","message":"Sabre\\DAV\\Exception\\NotFound: File with name documents\/.DLL could not be located","level":0,"time":"2014-08-04T04:55:22+02:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/documents\/.DLL"}
{"reqId":"53def61ea3351","app":"webdav","message":"Sabre\\DAV\\Exception\\NotFound: File with name documents\/WINWORD.EXE could not be located","level":0,"time":"2014-08-04T04:55:26+02:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/documents\/WINWORD.EXE"}
{"reqId":"53def61edc4db","app":"webdav","message":"Sabre\\DAV\\Exception\\NotFound: File with name documents\/jre.exe could not be located","level":0,"time":"2014-08-04T04:55:26+02:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/documents\/jre.exe"}
{"reqId":"53def61ef3136","app":"webdav","message":"Sabre\\DAV\\Exception\\NotFound: File with name documents\/jrew.exe could not be located","level":0,"time":"2014-08-04T04:55:26+02:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/documents\/jrew.exe"}
{"reqId":"53def61f37813","app":"webdav","message":"Sabre\\DAV\\Exception\\NotFound: File with name documents\/java.exe could not be located","level":0,"time":"2014-08-04T04:55:27+02:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/documents\/java.exe"}
{"reqId":"53def61f731bf","app":"webdav","message":"Sabre\\DAV\\Exception\\NotFound: File with name documents\/javaw.exe could not be located","level":0,"time":"2014-08-04T04:55:27+02:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/documents\/javaw.exe"}
{"reqId":"53def6202c75d","app":"webdav","message":"Sabre\\DAV\\Exception\\NotAuthenticated: No basic authentication headers were found","level":0,"time":"2014-08-04T04:55:28+02:00","method":"OPTIONS","url":"\/owncloud\/remote.php\/webdav\/documents\/"}
{"reqId":"53def6214f649","app":"webdav","message":"Sabre\\DAV\\Exception\\NotFound: File with name documents\/Language could not be located","level":0,"time":"2014-08-04T04:55:29+02:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/documents\/Language"}

**Comment by enoch85** [comment]
Here is a solution: https://www.en0ch.se/tips-tricks/netdrive/
