### ISSUE TITLE
The shared info isn't kept when a shared file is restored [oC7]

### ISSUE THREAD

**Issue by fernandoruiz** [owncloud/core#10158]
### Expected behaviour:
The file is restored and the shared info keeps.

### Actual behaviour:
The file is restored, but the shared info isn't kept.

### Steps to reproduce:
Shared a file with other user.
Deleted the file from the user owner.
Restored this file.

**Operating system:** Ubuntu 14.04
**Web server:** Apache/2.4.7
**PHP version:** PHP Version 5.5.9-1ubuntu4.3
**ownCloud version:** ownCloud 7.0.0

**Comment by MorrisJobke** [comment]
Implemented by @PVince81 by deleting code https://github.com/owncloud/core/pull/15282 - solved in 8.1 -> closing
