### ISSUE TITLE
Disallow sharing for group should disallowed unsharing as well

### ISSUE THREAD

**Issue by kfricke-hacon** [owncloud/core#10155]
We use the feature to disallow a group to share content in our ownCloud installation. I would assume that this also applies to the ability for the users in that group to not be able to unshare content shared with them. If not the ability to disable the "unshare" action should be an additional global sharing option.

**Comment by butonic** [comment]
Well, the issue just popped up again and a lot of time has passed since this was moved to the backlog. @rullzer how hard would it be to implement "enforced shares" with the refactored sharing code?

**Comment by rullzer** [comment]
Well I think the cleanest approach here would be to just check in the OCS Share API if the user can share at all. And if not return a 401.

Man I wish we had middleware in the OCS API...

**Comment by butonic** [comment]
hm, in OC9 the web ui issues an http DELETE request upon unsharing a folder. How does that land in the ocs api? Just trying to make sure it is a single place where we would have to make the change?

**Comment by rullzer** [comment]
https://github.com/owncloud/core/blob/master/apps/files_sharing/api/share20ocs.php#L192 there... 

However we should catch it in the OCS Share API (for sure). But we should also make sure the webUI is not allowing unsharing

**Comment by butonic** [comment]
@rullzer how much effort do you see for this (as in days)

If we know the guesstimate, @MTRichards do you want this?

If so, @cmonteroluque can you set a milestone?

**Comment by MTRichards** [comment]
@butonic I do want this, but it is a matter of when. 
I would say 9.2 and we can look at sharing cleanup, this, and a few other items around sharing to resolve the overall issues here, provide some granularity, and consistency to all platforms.

**Comment by rullzer** [comment]
@butonic I'd say 0.5 - 1.0 week (including proper UX) and proper test.

**Comment by PVince81** [comment]
@pmaier1 for the conceptual side

**Comment by PVince81** [comment]
Would move to backlog for now as there is not enough time for this

**Comment by PVince81** [comment]
Maybe covered by this app: https://github.com/owncloud/disableunsharing
