### ISSUE TITLE
Cannot sync a .htaccess file -- Internal Server Error

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#10167]
Seen with mirall 1.6.2 against s3.o.c

From the mirall log:
08-05 10:58:57:713 void Mirall::AbstractNetworkJob::setTimeout(qint64) 300000 
08-05 10:58:57:713 !!! Mirall::PUTFileJob created for  QUrl( "https://s3.owncloud.com/owncloud" )  querying "/core/
config/.htaccess" 
08-05 10:58:58:431 void Mirall::AbstractNetworkJob::slotFinished() 299 "Error downloading https://s3.owncloud.com/o
wncloud/remote.php/webdav/core/.htaccess - server replied: Internal Server Error" 
08-05 10:58:58:432 void Mirall::PropagateUploadFileQNAM::slotPutFinished()  QUrl( "https://s3.owncloud.com/owncloud
/remote.php/webdav/core/.htaccess" )  FINISHED WITH STATUS 299 "Error downloading https://s3.owncloud.com/owncloud/
remote.php/webdav/core/.htaccess - server replied: Internal Server Error" QVariant(int, 500) QVariant(QString, "Int
ernal Server Error") 
08-05 10:58:58:433 "<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre_DAV_Exception/s:exception
  <s:message>Could not rename part file to final file/s:message
  <s:sabredav-version>1.7.6/s:sabredav-version
/d:error
" 
08-05 10:58:58:434 void Mirall::SyncEngine::slotJobCompleted(const Mirall::SyncFileItem&) "core/.htaccess" 2 "Error
 downloading https://s3.owncloud.com/owncloud/remote.php/webdav/core/.htaccess - server replied: Internal Server Er
ror (Could not rename part file to final file)" 
![oc_htaccess_error](https://cloud.githubusercontent.com/assets/1108546/3809078/74324c5e-1c7f-11e4-8967-ff389d30bd67.png)

@dragotin what do think?

**Comment by PVince81** [comment]
If we get the file mapper integrated into oc_filecache, file-aliases could be created for such files.
Discussed this recently with @nickvergessen

CC @LukasReschke @DeepDiver1975

**Comment by jnweiger** [comment]
no longer an internal error. Files starting with a . are simply no longer synced. Sigh.

**Comment by RealRancor** [comment]
@jnweiger You can enable to sync hidden files like .htaccess file in the sync client settings. Open the client:

Settings -> General -> Advanced -> Edit Ignored Files

There you can tick the "Sync hidden files" checkbox.
