### ISSUE TITLE
HTTP 1.0 on attempt to download a non-existing file

### ISSUE THREAD

**Issue by uboslinux** [owncloud/core#10189]
I'm accessing:

```
http://owncloud-test/foobar/index.php/apps/files/ajax/download.php?dir=%2F&files=testfile
```

where testfile does not exist. ownCloud correctly returns status 404, but somehow switches back to HTTP 1.0 just for this single request. (This is pasted from HttpFox)

```
HTTP/1.0 404 Not Found 
Date    Tue, 05 Aug 2014 17:02:46 GMT
Server  Apache
X-Powered-By    PHP/5.5.14
Expires Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control   no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma  no-cache
X-XSS-Protection    1; mode=block
x-content-type-options  nosniff
X-Frame-Options Sameorigin
content-security-policy default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *
X-Robots-Tag    none
Connection  close
Content-Type    text/html
```

If the file exists, HTTP 1.1 is used.

**Comment by Xenopathic** [comment]
Wow, that's really strange. I just tested this and got HTTP/1.0 on the 404 page too. The page loaded fine, but the HTTP/1.0 is very odd...

**Comment by PVince81** [comment]
Maybe this is a hard-coded HTML page or something ?

@LukasReschke any idea ?

**Comment by LukasReschke** [comment]
That's hard-coded in https://github.com/owncloud/core/blob/69f14f974b2acd385809b508f22aa5c15e70d801/lib/private/files.php#L113-L119

**Comment by PVince81** [comment]
Is this really an issue ?

**Comment by MorrisJobke** [comment]
Still hardcoded https://github.com/owncloud/core/blob/bb4246c9a8dc40d844ad94492cb40ece5bd35ef6/lib/private/files.php#L164-L170

**Comment by PVince81** [comment]
maybe hard-code it to be 1.1 then ?!
