### ISSUE TITLE
External Only Storage

### ISSUE THREAD

**Issue by chebee7i** [owncloud/core#10198]
This is a followup on #4868. The goal is for all users to *only* store files on external storage.

### Steps to reproduce

Option 1
1. Set up an external storage (such as an Amazon S3 mount) with mount point "Amazon S3".
2. Clear the folder name.
3. Navigate to the Files app and see that the external storage is still in "Amazon S3".

Option 2
1. Set up an external storage (such as an Amazon S3 mount) with mount point "Amazon S3".
2. Set the folder name to "/"
3. The mount does not succeed and we see a red square.

### Expected behaviour
All users should only be able to upload directly to the external file store.

### Actual behaviour
The external file store is not the root storage location, and in scenario two above, doesn't even mount properly. Note, once local storage has been initialized, it's not at all clear how owncloud would resolve a decision to set an external storage as the root. What would happen to the existing files?

### Server configuration
**Operating system**: CentOS 5.10

**Web server**: Apache

**Database**: Mysql

**PHP version**: 5.5

**ownCloud version**: 7.0.1

**Updated from an older ownCloud or fresh install**: Fresh install

**List of activated apps**: Stock + external storage

**The content of config/config.php**: Unmodified.

**Are you using external storage, if yes which one**: Amazon S3

**Are you using encryption**: YES

### Client configuration
**Browser**: Chrome 36

**Operating system**: Ubuntu 12.10

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/issues/13408
