### ISSUE TITLE
Possibility to change the "recovery key password" without knowing the old one

### ISSUE THREAD

**Issue by awinge** [owncloud/core#10190]
I somehow forgot the recovery key password and I wanted to change it (as admin). But it seems impossible to do if I do not know the old password at least in the admin menu. Is this by design or is it a bug?

How can I recover from this? I have all other passwords, so theoretically I could reinstall owncloud, but that is really not what I want. 

I'm running version 7.0.

**Comment by MorrisJobke** [comment]
@schiesbn Do the same steps apply for the new encryption?

**Comment by schiesbn** [comment]
Yes, only the location of the recovery key changed. Both, private- and the public-key, are now stored in ````data/files_encryption/OC_DEFAULT_MODULE````

**Comment by settermjd** [comment]
Will get this done.

**Comment by settermjd** [comment]
owncloud/documentation/pull/2813 has been created to handle this issue. Please add any future comments there.

**Comment by settermjd** [comment]
Closing as the related issue is now closed.
