### ISSUE TITLE
WhisperSystems Flock Card-/CalDAV encryption support

### ISSUE THREAD

**Issue by devurandom** [owncloud/core#10201]
It would be great if ownCloud could support WhisperSystems Flock encrypted Card-/CalDAV. As this seems WebDAV storage related, I am reporting it against ownCloud core instead of the individual apps. I also created a feature request for Flock, so that maybe Flock and ownCloud developers can work together on this.

See-Also: WhisperSystems/Flock#49.

**Comment by untitaker** [comment]
Flock has been discontinued: https://gist.github.com/rhodey/873ae9d527d8d2a38213
