### ISSUE TITLE
Importing a large user base from ldap makes OwnCloud unresponsive

### ISSUE THREAD

**Issue by tps800** [owncloud/core#10207]
### Steps to reproduce
1. Install OwnCloud, Configure OwnCloud, Configure ldap access
2. Browse with a browser of your choice to Users

### Expected behaviour
User list should build up, regardless how many users ldap delivers.

### Actual behaviour
User list starts to build up, getting slower, then stalls. No further progress. Site hangs.
Chromium/Chrome ask for killing the site because of no reaction and no data transferred.
This behaviour starts at about more than 200 Users to import from ldap. A few users is OK, but really many (3000+) isn't. Shrinking the user base by filtering makes the whole thing work again, as long as you do not exceed about 200 Users.

### Server configuration
**Operating system:** Oracle Linux 6.5

**Web server:** Apache 2.2.15

**Database:** PostgreSQL 9.2.9

**PHP version:** PHP 5.5.14

**ownCloud version:** 7.0.1

**Updated from an older ownCloud or fresh install:** Upgrade from 6.5

**List of activated apps:** ?

**The content of config/config.php:** 

```
<?php
$CONFIG = array (
  'instanceid' => 'oc692ddacb52',
  'passwordsalt' => '',
  'trusted_domains' =>
  array (
    0 => '<server>.<local>.<domain>',
  ),
  'datadirectory' => '/data/owncloud/data',
  'dbtype' => 'pgsql',
  'version' => '7.0.1.1',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncld',
  'dbpassword' => '',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => '0',
  'mail_smtpmode' => 'php',
  'mail_smtpname' => 'admin',
  'mail_smtppassword' => '',
);

```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

### Client configuration
**Browser:**
* Windows XP/7/8:
 * Chrome (stable, beta, snapshot)
 * Chromium (stable, continuous)
 * Firefox (stable, nightly)
 * IE (Windows 7/8)
 * Opera (stable)
 * lynx (via cygwin)
 * w3m (via cygwin)

* Linux (Debian, Ubuntu, Fedora, Oracle Linux 6.5/7.0)
 * Chroma (stable, beta, snapshot)
 * Chromium (stable, continuous)
 * Firefox (stable, nightly)
 * Opera (last available)
 * Konqueror
 * lynx
 * w3m

**Comment by blizzz** [comment]
Better/Worse with OC 8? :D

**Comment by blizzz** [comment]
I close it, as there were improvements for 8 and for inactivity. Please reopen if you still have a bad experience.

**Comment by Alex-Hou** [comment]
Got the same Issue on ownCloud 9.0.0 (stable).
I've configured LDAP and have more than 2000 groups.
These groups will be loaded as options of multiselect menus for every row of "User".
