### ISSUE TITLE
[Webdav] When accessing to the external folder “GoogleDrive”, 500 Internal Server Error is received so often

### ISSUE THREAD

**Issue by purigarcia** [owncloud/core#10203]
### Steps to reproduce
1. Enable external storage app
2. Configure GoogleDrive as external storage.
3. GoogleDrive folder is shown
4. Using poster, make a profind of this folder
	URL: http://server/owncloud/remote.php/webdav/GoogleDrive
	user/password
	Select pro find and click in the green button
5. 500 Internal Server Error is received most of the times (but not always)
Image attached above
![screen shot 2014-08-06 at 10 12 13 am](https://cloud.githubusercontent.com/assets/4538201/3824078/5bded0f0-1d42-11e4-9020-c0d4078970a9.png)

### Expected behaviour
	500 Internal Server Error is not received

### Actual behaviour
	500 Internal Server Error is not received

### Client configuration
Operating system: MacOs 10.7.5
Owncloud version: It was tested in beta {"installed":"true","version":"6.0.3.1","versionstring":"6.0.3","edition":"enterprise"}

**Comment by MorrisJobke** [comment]
@icewind1991 Ping

**Comment by PVince81** [comment]
Database is locked is the SQLite issue.
I wonder where the query in the screenshot is called though, probably some code that only updates file sizes.

**Comment by PVince81** [comment]
@purigarcia @rperezb are you still seeing this with 8.1.3 or 8.2 ?

**Comment by MorrisJobke** [comment]
Long time no response: Closing
