### ISSUE TITLE
Enhancement: 7.0.1 Group Admin Should Not Show Create Group Option

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#10228]
When I am in ownCloud and logged in as a group admin, I want to add users. This all works great, and they are part of my group only with the quota I set.

However, I can see on the top left the "+ Group" option. This option leads to an authentication error if I try, which is good, but the option really should not render for a group admin in this page. 

![untitled](https://cloud.githubusercontent.com/assets/1818977/3833609/2917f78e-1da9-11e4-9c28-bbf3eaebadd8.png)

**Comment by PVince81** [comment]
Still observed on master / 9.0 pre-alpha.

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/26380
