### ISSUE TITLE
Server to server sharing is not working properly with single files and documents

### ISSUE THREAD

**Issue by BattleMage** [owncloud/core#10237]
### Steps to reproduce
1. Upload a PDF and an ODT file to your cloud
2. Share both files individually with a public link.
3. Open both public links, use the files service for the ODT file, not the document service.
4. Save the files to your cloud.
5. Open the added files from your files view.

### Expected behaviour
The files should behave like any other shared file. The ODT file should be viewable and editable from the files and the documents app.

### Actual behaviour
* The PDF file is viewable and everything seems to be working for the user, but errors are thrown in the log (see errors below)
*  The ODT file is not usable at all.
 * Selecting *edit* from the files app won't do anything
 * Using the documents app, a preview will be generated, the file is not editable, no filename is shown.

### Server configuration
**Operating system**: Debian GNU/Linux 7.6 (wheezy) (3.2.0-4-amd64)

**Web server:** Apache/2.2.22 (Debian) (2.2.22-13+deb7u3)

**Database:** Mysql 5.5.38-0+wheezy1

**PHP version:** 5.4.4-14+deb7u12

**ownCloud version:** (see ownCloud admin page) 7.0.1 (stable)

**Updated from an older ownCloud or fresh install:** Updated (using the apt repository since owncloud 5)

**List of activated apps:** Activity,Bookmarks,Calendar,Contacts,Deleted files,Documents,Encryption,External Sites,External storage support,First Run Wizard,Notes,ownCloud dependencies info,PDF Viewer,Pictures,Share Files,Text Editor,Versions,Video Viewer,Files move (3rd Party),Mozilla Sync (3rd Party),SQL user backend (3rd Party)

**The content of config/config.php:**
```php
$CONFIG = array (
  'passwordsalt' => '<removed>',
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.1.1',
  'appstoreenabled' => true,
  'writable_appsdir' => false,
  'dbname' => '<removed>',
  'dbhost' => '<removed>',
  'dbtableprefix' => '<removed>',
  'dbuser' => '<removed>',
  'dbpassword' => '<removed>',
  'installed' => true,
  'instanceid' => '<removed>',
  'theme' => '<removed>',
  'maintenance' => false,
  'loglevel' => '1',
  'defaultapp' => 'files',
  'allow_user_to_change_display_name' => true,
  'updatechecker' => true,
  'blacklisted_files' =>
  array (
    0 => '.htaccess',
  ),
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/var/www/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/var/www/owncloud/apps2',
      'url' => '/apps2',
      'writable' => true,
    ),
  ),
  'trusted_domains' =>
  array (
    0 => '<removed>',
  ),
  'forcessl' => true,
);
```
**Are you using external storage, if yes which one:** none per default, external owncloud file is affected by this error

**Are you using encryption:** yes

### Client configuration
**Browser:** Pale Moon 24

**Operating system:** Windows 7

#### Web server error log
**Opening the PDF file** 21 times
```
[Thu Aug 07 10:30:41 2014] [error] [client x.x.x.x] user d036d1db68c53550f87a7a7b5bf688b6 not found: /webdav/
```

**Opening the ODT file** 10 times
```
[Thu Aug 07 10:39:38 2014] [error] [client x.x.x.x] user 46ffe053a05bd101eee53aefc08aca69 not found: /webdav/
```

#### ownCloud log (data/owncloud.log)
**Opening the PDF file** 21 times
```json
{"app":"PHP","message":"Argument 1 passed to OC\\Connector\\Sabre\\ObjectTree::init() must be an instance of Sabre\\DAV\\ICollection, instance of OC_Connector_Sabre_File given, called in \/var\/www\/owncloud\/apps\/files_sharing\/publicwebdav.php on line 68 and defined at \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/objecttree.php#42","level":3,"time":"2014-08-07T08:30:41+00:00"}
```

**Opening the ODT file** 10 times
```json
{"app":"PHP","message":"Argument 1 passed to OC\\Connector\\Sabre\\ObjectTree::init() must be an instance of Sabre\\DAV\\ICollection, instance of OC_Connector_Sabre_File given, called in \/var\/www\/owncloud\/apps\/files_sharing\/publicwebdav.php on line 68 and defined at \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/objecttree.php#42","level":3,"time":"2014-08-07T08:39:36+00:00"}
```

#### Browser log
**Select *edit* from the menu on any ODT file** (this is an issue of the documents app)
```
[10:37:45.742] TypeError: OCA.Files.fileActions.currentFile is null
```
#### Additional Information
Adding the files to the cloud gives the exact same error, just not as often.

**Comment by PVince81** [comment]
Are you still seeing this in 7.0.7, 8.0.5 or 8.1 ?

There have been fixes related to Webdav PUT and single file shares which should hopefully fix this issue too.

**Comment by PVince81** [comment]
Please try again with the latest OC versions, 8.1.5 or 8.2.2.
If you're still having this issue, feel free to reopen.
