### ISSUE TITLE
WebDAV permission attribute wrong

### ISSUE THREAD

**Issue by dragotin** [owncloud/core#10247]
Tested with stable7 on 7540a58ce7e921f1eb8083f58ded6977ade10ad0 :+1: 

* [ ] directories that were shared **by** me do not have the "S" tag.
* [ ] files in directories shared **by** me do not have the "S" tag.
* [x] directories that are shared **with** me do have the "S" tag, but also the "M" tag which they IMO should not have.
* [x] files in directories shared **with** me also have the "M" tag which they IMO should not have.

@DeepDiver1975 please help - thanks.

**Comment by PVince81** [comment]
What's the next step ?

**Comment by PVince81** [comment]
Is this still an issue ? I've seen Webdav permission attributes set before, also the mobile and desktop clients are using them. Does it mean this is fixed or are there any outstanding issues ?

**Comment by guruz** [comment]
@PVince81 I think it's about shared TO me vs shared BY me..

**Comment by DeepDiver1975** [comment]
@dragotin @guruz is this still of an issue? Please reopen if so - THX
