### ISSUE TITLE
[7.0.1] Delete shared folder while uploading

### ISSUE THREAD

**Issue by ser72** [owncloud/core#10254]
**Expected Behavior**
Error stating target folder has been deleted -- Upload cancelled

**Actual Behavior**
Inconsistent.  Tested several times with different results

**Steps**
User A shares a folder with User B
User B uploads several files to the folder
While the upload is going on, User A deletes the folder

Sometimes the error is an Internal Server Error
Sometimes it states target folder has been deleted -- Upload cancelled

Should always say target folder has been deleted

CentOS 
PHP 5.3.3
Postgresql

**Comment by PVince81** [comment]
I guess this is all in the web UI ?

**Comment by PVince81** [comment]
Starting with 8.1, enabling transactional file locking will prevent deleting a folder while a file is being uploaded.
