### ISSUE TITLE
[7.0.1] (Un-)Share a file after another user edited this

### ISSUE THREAD

**Issue by dgohacon** [owncloud/core#10263]
Hi,
I have a strange behavior with shared files after they got edited by other users.
## Reproducing steps
* Me (user1) shared a file with user2.
* user2 is editing this file.
* After this user1 is going to section "All files". In this view there is no icon that this file is shared. Furthermore if I hover over this file there is no icon to "share" this file.
* Only if I go to section "Shared with other" I see that I still have shared this file with user2.

I forgot the important information that the user2 is member of a group that is excluded from sharing. May be it has something to do with this?

**Comment by enoch85** [comment]
@dgohacon Is this still an issue in 8.0.2?

**Comment by PVince81** [comment]
@dgohacon please try again with 7.0.5 or 8.0.2.
If you're still having the issue, please use the issue template to provide more info about your environment: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md (including logs)
