### ISSUE TITLE
[7.0.1] Confusion with share to user name

### ISSUE THREAD

**Issue by ser72** [owncloud/core#10262]
**Expected Behavior**
Username pop up

**Actual Behavior**
Full name pops up

**Steps**
Configure a user as such:

![capture](https://cloud.githubusercontent.com/assets/5174383/3844198/03038d44-1e47-11e4-93e8-da1b4a9f6888.PNG)

Share a file with "logan"
Notice the share dialog pulls up "yogi" and not "logan".

![capture1](https://cloud.githubusercontent.com/assets/5174383/3844204/106e3786-1e47-11e4-99c3-0390470ad383.PNG)

Granted "logan" and "yogi" are the same person, but the end user may not realize this.

CentOS
PHP 5.3.3
Postgresql

**Comment by karlitschek** [comment]
seems to be fixed
