### ISSUE TITLE
owncloud.log full of "Sabre\\DAV\\Exception\\Forbidden"

### ISSUE THREAD

**Issue by chemnic** [owncloud/core#10275]
Hi all

Owncloud server 7.0.1
OS: Ubuntu 12.04 (OpenVZ)
PHP 5.4.31

My owncloud.log file is full of this:

{"app":"webdav","message":"Sabre\\DAV\\Exception\\Forbidden: ","level":4,"time":"2014-08-07T19:19:02+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\Forbidden: ","level":4,"time":"2014-08-07T19:19:03+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\Forbidden: ","level":4,"time":"2014-08-07T19:19:03+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\Forbidden: ","level":4,"time":"2014-08-07T19:19:04+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\Forbidden: ","level":4,"time":"2014-08-07T19:19:04+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\Forbidden: ","level":4,"time":"2014-08-07T19:19:05+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\Forbidden: ","level":4,"time":"2014-08-07T19:19:05+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\Forbidden: ","level":4,"time":"2014-08-07T19:19:06+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\Forbidden: ","level":4,"time":"2014-08-07T19:19:06+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\Forbidden: ","level":4,"time":"2014-08-07T19:19:07+00:00"}

The thing is that everything looks fine. We can upload and download files with no problem. The client is syncing fine, in Windows and Ubuntu.

I have followed some guides about WebDAV configuration, but I dont think that is my problem.

As I said, there is no visible problems with the server or clients, but the error happens 2 times per second approximately. I want to know if there is something wrong with my configuration.

Thanks.

**Comment by enoch85** [comment]
Related #13098
