### ISSUE TITLE
[7.0.1] Download timeout / truncated

### ISSUE THREAD

**Issue by watermark** [owncloud/core#10304]
Downloading large files "complete" well before they are fully downloaded.  Trying multiple times leads to differing amounts that actually get downloaded.  It seems to error between 7:30 and 8:30 minutes, due to the varying time, it doesn't seem to be a timeout either.

This happens on every large file I try to download, so OC is pretty useless for large files.  The download fails when I pause and resume, so I suppose that's not supported either.

**Comment by watermark** [comment]
Different server, different install of owncloud.  This is also an issue in owncloud 8.  I'm still hoping for a solution that allows owncloud to be run in fcgi.

**Comment by lDevas** [comment]
I have the exact same problem in version 8.0.2, Only seen it when a folder is downloaded. Also seen that folder downloads do not show total/progress bar, may it be related?

**Comment by LukasReschke** [comment]
Probably environment related. Please check out https://owncloud.org/support
