### ISSUE TITLE
Fixing authentication to servers without mod_rewrite (Webfaction)

### ISSUE THREAD

**Issue by filipesaraiva** [owncloud/core#10318]
Hello owncloud developers, first thank your for this great software.

Everytime I update my owncloud installation I need to fix the authentication. My provider (Webfaction) doesn't have mod_rewrite enabled in server.

This blog post (http://www.blaicher.com/2012/07/fixing-authentication-of-owncloud-for-webfaction/) teach how fix it and I do it since 6.x series. For now, I am using 7.x and I did it again.

So, is it possible to put that code in owncloud source code repository?

Thank you.

**Comment by filipesaraiva** [comment]
Hi, if necessary I can to try to provide something information, just tell me what is need and how I can to do it.

**Comment by DeepDiver1975** [comment]
> This blog post (http://www.blaicher.com/2012/07/fixing-authentication-of-owncloud-for-webfaction/) teach how fix it and I do it since 6.x series. For now, I am using 7.x and I did it again.

wow - fixed back in 2012 - a pull request to fix this would be great.
@filipesaraiva interested in sending a pull request? THX
