### ISSUE TITLE
When curl is not installed, after accepting a shared folder from another instance, all files seem to have vanished from the cloud

### ISSUE THREAD

**Issue by pierre-alain-b** [owncloud/core#10319]
This bug only happens on a server where php5-curl is not installed. The documentation here (http://doc.owncloud.org/server/7.0/admin_manual/installation/installation_source.html) does not state that php5-curl is compulsory so this is somehow misleading. We could maybe add a graceful behavior when curl is not present or an error message urging the user to add curl.

### Steps to reproduce
0. Your own ownCloud server does not have curl/php5-curl
1. Receive a link with a shared folder from another ownCloud user (e.g. using https://cloud.userA.com)
2. Open the link and use the new feature "Add to your ownCloud"
3. Put your owncloud info in the text box: e.g. cloud.userB.com
4. You are redirected to your own ownCloud instance
5. bang! your cloud seems blank with no file displayed in the list!

### Expected behaviour
Obviously ownCloud should still display all the files in the cloud

### Actual behaviour
No file is displayed. The user may have the feeling that all files have just disappeared and may panick!
The resolution is quite straightforward once we have seen this in the logfile:
[Sun Aug 10 07:12:50 2014] [error] [client x.y.z.a] PHP Fatal error:  Call to undefined function Sabre\\DAV\\curl_init() in /var/www/owncloud/3rdparty/sabre/dav/lib/Sabre/DAV/Client.php on line 465, referer: https://myowncloud.tld/index.php/apps/files?dir=abc

As curl is not available on the server, there is a fatal error and this interrupts the display of all files in the cloud.

### Solution on the server
It is easy to install curl / php5-curl (e.g. with aptitude install php5-curl if Debian) on the server. Then it works and all files are visible again.

### Fix in ownCloud
Wouldn't it be good to:
1. fix the documentation to state that curl is compulsory (sharing data with link should be assumed to be a core feature that anyone may use)
2. add a graceful exception manageement when curl is not present -> no interruption of the code displaying all the files and maybe an error message to notify the absence of curl?

**Comment by DeepDiver1975** [comment]
curl is a hard dependency now - should not longer happen -> close
