### ISSUE TITLE
Unable to add external storage as user

### ISSUE THREAD

**Issue by Larx** [owncloud/core#10327]
I cannot add any external storage as OC user. The permission to do so has been granted in the admin settings.
However, when I try to enter the configuration of an external storage in the user's settings page, only the fields "name" and "type" are available at all. No more configuration can be entered.
Also it is not possible to add the storage manually by creating a data/user/mount.json-file. An external storage added this way does not appear in the "all files" view of OC's file manager. It does appear, however, when clicking on the "external storage" panel of the file manager, but cannot be browsed.
The same external storage works flawlessly when added as admin in the admin config page.

**Comment by vutang50** [comment]
I had the same issue on my installation.  Along with this,  users were not able to add a personal avatar with `asset-pipeline.enabled`.  As soon as I removed the setting, not only were users able to add their own storage but they were able to set their own avatars.
