### ISSUE TITLE
Access local storage, respecting individual user access rights

### ISSUE THREAD

**Issue by Larx** [owncloud/core#10337]
I'd like to propose an enhancement:
Right now, OC can access local storage, but only with access rights of the web server.
If I'd like to keep local user rights, AFAIK I have to make a detour, e.g. setting up an local FTP server and accessing the local files via FTP external storage.
It would be great if OC had a possibility to avoid this detour and access local files with username and password.

**Comment by Xenopathic** [comment]
Unfortunately this is technically infeasible to implement. For the web server to be able to access files with the UID of another system user, it would need to invoke a setuid binary like `su` or `sudo`, pass in the password, then read the file down the stream. This is a really bad way of doing it: see the performance mess with `smbclient` in the SMB backend (thankfully now replaced). A much more performant way of doing this is to have a privileged daemon running that accepts authentication requests over a socket and provides access to the files. This is what FTP, SFTP or SMB are doing.
