### ISSUE TITLE
[oC7.0.1][Server to server sharing] When a file is deleted on the server owner, is not deleted in the other server.

### ISSUE THREAD

**Issue by fernandoruiz** [owncloud/core#10351]
### Expected behaviour:
The file is also deleted in the oC_Instance_B.

### Actual behaviour:
The file is not deleted in the oC_Instance_B and when you try to open the file, the following error appears in the log:
{"reqId":"53e8eacb5913b","app":"index","message":"Sabre\\DAV\\Exception\\NotAuthenticated: Not authenticated","level":4,"time":"2014-08-11T16:09:47+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files_texteditor\/ajax\/loadfile.php?file=MODELO_ISSUE.txt&dir=%2F"}

### Steps to reproduce:
Share a file between servers (from oC_Instance_A to oC_Instance_B)
Delete the file from the oC_Instance_A.

### Note:
This problem is also repeated when we try to delete a file or subfolder that is located within a shared folder between servers.

**Operating system:** Ubuntu 14.04
**Web server:** Apache/2.4.7
**PHP version:** PHP Version 5.5.9-1ubuntu4.3
**ownCloud version:** ownCloud 7.0.1

**Comment by PVince81** [comment]
CC @jnfrmarks

**Comment by PVince81** [comment]
Works in 8.0.
Basically the folder or file gets unmounted on-demand. It means it stays visible in the list until OC tries to access it. At this time it finds out that the file/folder is gone.
