### ISSUE TITLE
 External storage - Can't be able to add another account, but can add DropBox

### ISSUE THREAD

**Issue by milk3dfx** [owncloud/core#10354]
ownCloud 7.0.1
Log shows no errors
While I am trying add another ownCloud account both as user and as admin it show me read square on left. I am using WebDAV address http://cloud.example.com:7777/remote.php/webdav/ (Chrome can open this page) I tried local addresses with same results. Also, It can not add FTP account, but can add DropBox.

**Comment by DeepDiver1975** [comment]
no feedback -> close
