### ISSUE TITLE
Web GUI shows empty 'Shared'-Folder if upgraded from previous version

### ISSUE THREAD

**Issue by tps800** [owncloud/core#10361]
### Steps to reproduce
1. Install OwnCloud, Configure OwnCloud, Configure LDAP access
2. Browse to your OwnCloud URL; Click on "All files"
3.

### Expected behaviour
Showing all files you own

### Actual behaviour
Showing all files you own including the old "Shared" folder. Since this has moved to "Shared with you"-Link on the left navigation bar, the folder is empty, leading to user confusion.

### Server configuration
**Operating system:** Oracle Linux 6.5

**Web server:** Apache 2.2.15

**Database:** PostgreSQL 9.3.5

**PHP version:** PHP 5.5.14

**ownCloud version:** 7.0.1

**Updated from an older ownCloud or fresh install:** Upgrade from 6.5

**List of activated apps:** ?

**The content of config/config.php:** 

```
<?php
$CONFIG = array (
  'instanceid' => 'oc692ddacb52',
  'passwordsalt' => '',
  'trusted_domains' =>
  array (
    0 => '<server>.<local>.<domain>',
  ),
  'datadirectory' => '/data/owncloud/data',
  'dbtype' => 'pgsql',
  'version' => '7.0.1.1',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncld',
  'dbpassword' => '',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => '0',
  'mail_smtpmode' => 'php',
  'mail_smtpname' => 'admin',
  'mail_smtppassword' => '',
);

```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

### Client configuration
**Browser:**
* Windows XP/7/8:
 * Chrome (stable, beta, snapshot)
 * Chromium (stable, continuous)
 * Firefox (stable, nightly)
 * Opera (stable)
 * lynx (from cygwin)
 * w3m (from cygwin)
* Linux (Debian, Ubuntu 12.04/14.04/14.10, Fedora 19/20/21, Oracle Linux 6.5/7.0)
 * Chrome (stable, beta, snapshot)
 * Chromium (stable, continuous)
 * Firefox (stable, nightly)
 * Opera (last available)
 * Konqueror (stable)
 * lynx (stable)
 * w3m (stable)

**Comment by jancborchardt** [comment]
Closed because it’s fixed.
