### ISSUE TITLE
Drag and drop file upload hover overlay

### ISSUE THREAD

**Issue by th3fallen** [owncloud/core#10369]
A thought is it would be very nice to have when a user hovers a file into the browser window that the files app would respond with a overlay with some sort of verbage to the effect of "drop here to upload" 

This way the user knows that the drop action is recognized and available.

Same goes for dragging files into folders there is no UX response that shows the user that it is safe to drop the file into the folder.

cc @PVince81

**Comment by PVince81** [comment]
@vgezer are you still interested in finishing/redoing this ?
