### ISSUE TITLE
[oC7.0.1][Server to server sharing] Sync progress information with very large files

### ISSUE THREAD

**Issue by fernandoruiz** [owncloud/core#10376]
### Expected behaviour:

I think it would be useful for the user to know when a large file is available on the oC_Instance_B.
### Actual behaviour:

No sync progress information is displayed. With large file the response time can be very high.
### Steps to reproduce:

Share a large file (2,5GB) between servers (from user1@oC_Instance_A to user1@oC_Instance_B).
Then from oC_Instance_B, I try to download this file, but the oC_Instance_B does not show any response until the file is not synchronized (with my setup, about 10 minutes).

**Operating system:** Ubuntu 14.04
**Web server:** Apache/2.4.7
**PHP version:** PHP Version 5.5.9-1ubuntu4.3
**ownCloud version:** ownCloud 7.0.1

**Comment by rullzer** [comment]
@danimo another case for the discussion we had in Berlin about downloading directly from the target server.

**Comment by PVince81** [comment]
There is no synchronization between OC instances in the case of federated shares. When downloading, we already stream the file through and not use temporary space any more.
