### ISSUE TITLE
Disk load 90%+ by MariaDB during synchronization of large number of small files

### ISSUE THREAD

**Issue by nazar-pc** [owncloud/core#10384]
OwnCloud 7.0.1, MariaDB 10.0.13, Ubuntu 14.04 x64 inside Docker container.

I've put 10000 files with source codes (Git repository actually) into OwnCloud directory on my local machine (Ubuntu 14.10 x64) to sync, and see VERY poor performance (from one to few files per second on 100 Mb/s Internet channel).

When I go to server - I see 96-98% disk load by MariaDB instance that serves OwnCloud.
When I close desktop client to stop sync process - disk load drops to 0.

I'm wondering what OwnCloud can do with database to cause such load on RAID 1 from 2x240 GiB SATA3 SSD. These SSD are pretty fast, never seen them to be loaded even 50% while I have several containers with different applications on this machine.

Any hints to debug the source of problem? MariaDB with default config.

**Comment by DeepDiver1975** [comment]
We are constantly working on improving sync performance -> closing this issue - THX
