### ISSUE TITLE
Primary Object Store: If you create a folder it goes only to DB, not to Swift

### ISSUE THREAD

**Issue by labkode** [owncloud/core#10391]
With local storage, if you create a folder it goes to DB and to the filesystem.
With object storage it goes only to DB until you have files inside the folder.

**Comment by butonic** [comment]
closing this as works as designed. If you want oc to access swift as a filesystem use files external. ping @icewind1991 to get information on how to mount an external filesystem as a users home. AFAIR it is possible by directly editing the mount.json.
