### ISSUE TITLE
Enable CORS on useful endpoints

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#10415]
Regarding https://github.com/benweet/stackedit/issues/122#issuecomment-52148947 we should create a list of APIs where we should enable CORS to allow third-party devs integrate with ownCloud. Feel free to add more:
- [ ] OCS Share API (no private data)
- [ ] WebDAV
- [ ] CalDAV
- [ ] CardDAV

**Comment by michielbdejong** [comment]
So IIUC, the code for CORS was [added to the middleware last May](https://github.com/owncloud/core/pull/8504), but it was never actually activated on the OCS Share API?

That's what I understand from the discussion above, and also, I did a simple test against the API of the demo instance:

```bash
curl -I https://test:test@demo.owncloud.org/ocs/v1.php/apps/files_sharing/api/v1/shares
````

and got back no CORS headers.

(side note: there were actually some cookie headers on there which should be removed if/when switching to CORS)

**Comment by DeepDiver1975** [comment]
> So IIUC, the code for CORS was added to the middleware last May, but it was never actually activated on the OCS Share API?

ocs share api is not using app framework controllers - we cannot apply the cors middleware - yet

**Comment by PVince81** [comment]
CORS was implemented with domain whitelisting here: https://github.com/owncloud/core/pull/28457
