### ISSUE TITLE
[6.0.4 LDAP Home] No error when Home Directory is missing

### ISSUE THREAD

**Issue by ser72** [owncloud/core#10419]
**Expected Behavior**
Provide a decent error as to what the issue is

**Actual Behavior**
No real error in browser and log doesn't provide details as well

**Steps**
1) Configure LDAP Home directory in LDAP
2) In the Advanced Tab of the LDAP wizard, configure the attribute of the home directory
3) If the home directory mount is gone for some reason, when the user browses to their ownCloud webUI, they get the following:

![capture](https://cloud.githubusercontent.com/assets/5174383/3919242/63017572-23a5-11e4-8de8-6248f0f52f45.PNG)

Better is an error explaining what the issue is -- or to contact the Admin for assistance.

The logs are as follows:
```
Error	PHP	mkdir(): Permission denied at /var/www/owncloud604/lib/private/util.php#82	2014-08-14T11:22:41+00:00
Error	PHP	mkdir(): Permission denied at /var/www/owncloud604/lib/private/util.php#82	2014-08-14T11:22:41+00:00
Error	PHP	mkdir(): Permission denied at /var/www/owncloud604/lib/private/util.php#82	2014-08-14T11:22:40+00:00
```

Which are insufficient to tell the Admin what the issue is.  A log stating something like "Mount no longer exists" would be better so the Admin can remount and the user can be operational again.

**Comment by remixtj** [comment]
What if a user is impacted by this error? How can the admin fix? I created manually files directory which was unavailable for the user and launched a rescan, but i'm looking for a more elegant way to fix.

**Comment by PVince81** [comment]
Does this still happen in 7.0.5 or 8.0.2 ?

@blizzz what do you think ?

**Comment by MorrisJobke** [comment]
I improved a bit the error handling - https://github.com/owncloud/core/pull/21459 should fix this issue.
