### ISSUE TITLE
ownCloud federation - next steps

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#10429]
Having server-to-server sharing with ownCloud7 is already great. But let's look forward. There are a lot of areas where we could improve the way we connect ownClouds to each other.

What I can think of:

- Introduce a concept of "known ownClouds" to connect ownClouds with each other.
- ownCloud which know each other could exchange user lists, etc., this means for file sharing you could pick a user from a known ownCloud directly from the share dialog and the mount could be created automatically
- Also a lot of other apps could benefit from it, think about calendar and contact sharing across ownCloud, maps could share locations between ownClouds which could result in some kind of "federated and privacy respecting foursquare", etc.

Just some ideas I want to write down that they don't get lost. Let's think about it, discuss ideas and see what might be possible for the next ownCloud releases.

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/issues/19566 and https://github.com/owncloud/core/issues/12285
