### ISSUE TITLE
Autologon not working anymore in OC 7 with $remote_user

### ISSUE THREAD

**Issue by lunarok** [owncloud/core#10432]
Steps to reproduce
1.owncloud 7.0.1
2.webserver set to passthrough $remote_user

Expected behaviour
Auto logon, like with owncloud 6 and before

Actual behaviour
With a user already authentified on server (SSO), the owncloud is asking again a login

Server configuration
Debian Wheezy 7.6
Nginx 1.4.4-1~bpo70+1
MariaDB 10.0.13+maria-1~wheezy
Php 5.4.4-14+deb7u12
OWncloud : 'version' => '7.0.1'

List of activated apps:
LDAP connector

Client configuration
Firefox 31
Try also Chrome

Operating system:
Ubuntu 14.04 and others

**Comment by DeepDiver1975** [comment]
ownCloud core out of the box does not support this yet.
