### ISSUE TITLE
No error message when attempting to create a group that already exists

### ISSUE THREAD

**Issue by gig13** [owncloud/core#10446]
**Expected Behavior**
Error message pops up stating that the group already exists

**Actual Behavior**
No error message, you press enter and nothig happens

**Steps**
1. Attempt to duplicate a group in the Users page.

**Server Configuration**
MS IIS
MS SQL Server
Browsers IE 11.0.9600, Firefox 31.0

**Comment by Xenopathic** [comment]
Looks like this has been fixed in #12618, which is in 8.0
