### ISSUE TITLE
owncloud 6 to 7 stuck and failed

### ISSUE THREAD

**Issue by bugsyb** [owncloud/core#10464]
I've faced the very same problem as https://github.com/owncloud/core/issues/10091 (Upgrading from OC6.04 to OC7 stops at "This ownCloud instance is currently being updated..." ) and system got stuck for days. Nothing really did happen.
Once apache got restarted I can't start owncloud as get error:
An exception occurred while executing 'SELECT "configvalue", "appid" FROM "oc_appconfig" WHERE "configkey" = ?' with params ["enabled"]: SQLSTATE[HY000]: General error: 1 no such table: oc_appconfig

./occ upgrade returns empty result.
Files are still in place under _oc-upgrade/tmp folder.

The question is how to finish upgrade procedure without loosing all the settings?
I've created separate bug for this as it might be caused by some other issue and only exposing itself in the very same way.

**Comment by PVince81** [comment]
Maybe this table is already missing for some reason ? Are you able to find it with a MySQL client ?

**Comment by skyynet** [comment]
Thanks for the late reply. I can't tell you anymore as I'm already on oc8.02. As now auto upgrade was possible from 7 to 8 I hope the first oc8 auto update will work.

**Comment by PVince81** [comment]
Ok thanks. So you mean at some point you ran the upgrade and the error disappeared ?

**Comment by skyynet** [comment]
Nope, I just installed 7.x from scratch and copied the data into it manually.
