### ISSUE TITLE
 New issue WebDAV-Filelocking does not work in Multi-User Environment - ReOPENED

### ISSUE THREAD

**Issue by borconi** [owncloud/core#10474]
Hi all.

This is just a reopen of issue (https://github.com/owncloud/core/issues/5267).
The scenario:

User 1 and User 2 shares FILE A.
Both users connect trough WebDAV to the server.
User 1 opens FILE A and starts editing, meanwhile User 2 opens FILE A and starts editing. 

We would expect that user 2 get a warring that file is locked down, but this never happens.

If User 1 is connected from two separate machines trough WebDAV and starts editing FILE A, then on one machine then opens it on the second machine, then he gets a warring that the file is locked for editing. 

Problem: Shared file locks are not propagating between the users who shares them.

I'm not a too bright programmer myself but sometimes I'm quite stubborn so I came up with this solution, please note I know it is not a good and nice solution but till this get fixed properly I'm happy to live with this, we will need to edit 2 files.

File 1) owncloud/lib/private/connector/sabre and replace:

              $query = 'SELECT * FROM `*PREFIX*locks`'
               .' WHERE `userid` = ? AND (`created` + `timeout`) > '.time().' AND (( `uri` = ?)';

with this:

                $query = 'SELECT * FROM `*PREFIX*locks`'
                           .' WHERE `userid` = ? AND `userid` NOT IN (select `share_with` from `*PREFIX*share` where `share_type`=0 and `uid_owner`= ?) AND '
                           .' `userid` NOT IN ( select DISTINCT `uid` from `*PREFIX*group_user` left join `*PREFIX*share` '
                           .' on `*PREFIX*group_user`.`gid`= `*PREFIX*share`.`share_with` WHERE `*PREFIX*share`.`share_type`=1 AND `*PREFIX*share`.`uid_owner`= ?) AND '
                           .'(`created` + `timeout`) > '.time().' AND (( `uri` = ?)';

Also replace this:

                 $params = array(OC_User::getUser(), $uri);

with this:

                 $params = array(OC_User::getUser(), OC_User::getUser(), OC_User::getUser(), $uri);

This patch here will make sure that if the same file is opened by users who share the file a lock warring will be generated. I know for a fact that if the file is re-shared by somebody that person will be able to open it regardless if others are editing it or not, like I said not perfect solution just a quick patch to get it working for a small office.

File 2) /owncloud/3rdparty/sabre/dav/lib/Sabre/DAV/Locks/Plugin.php

Change this:

      protected function httpLock($uri) {
        $lastLock = null;

To this:

    protected function httpLock($uri) {
            $lista = $this->getLocks($uri);
            if ($uri==$lista[0]->uri){throw new DAV\Exception\Locked($lista); }
            $lastLock = null;

Once again I highlight my solution is FAR away from a good and clean solution but it's something to start of with. If somebody can implement a proper fix for any future release will be wonderful.

**Comment by poVoq** [comment]
Any update on this? I would like to use my owncloud server with project gantt as described here:
http://blog.micronarrativ.org/blog/2013/05/08/ganttproject-og-owncloud/

**Comment by PVince81** [comment]
Webdav locking has been removed since 8.1 as it wasn't working properly.
Please follow up here regarding adding it back somehow: https://github.com/owncloud/core/issues/17732

**Comment by PVince81** [comment]
For the question that popped up on IRC regarding the difference between ownCloud locking and Webdav locking. ownCloud locking is automatically used when file operation are used with the ownCloud file APIs (aka node API). Not all apps or code paths are using Webdav so the locking had to be on another level. ownCloud locking does not only lock a file but also the parent folder, for example to prevent moving/renaming the parent folders while a file is being written inside said folders. Such locking also needs to work properly across shares between users.

Also, Webdav's locking works differently. One has to explicitly tell Webdav to lock a file and then release the lock later through separate Webdav operations. I'm not sure whether locking of folders and parent folders would work with that method anyway.
