### ISSUE TITLE
Set File Creation Mask for external mount

### ISSUE THREAD

**Issue by protree** [owncloud/core#10479]
Is it possible to set the file creation mask for external mounts (local folders)? I want these files to be written with group write permissions for sharing.

I believe this is an important feature which shoudn't be hard to integrate.

Currently I am working around this by setting up a local samba share and defining the file creation mask through smbd, which produces a lot of overhead.

**Comment by Xenopathic** [comment]
We cannot guarantee that the destination filesystem supports UNIX-style file modes - SMB shares on a Windows server use complex ACLs for example. Even if we could detect this, the UI would become very inconsistent, making for bad UX. The best thing to do is use default permissions on the remote storage directly, like @PVince81 said, as ownCloud has no effect on that and will respect it.
