### ISSUE TITLE
ownCloud sees size of a multiple-file upload as max single filesize

### ISSUE THREAD

**Issue by finius** [owncloud/core#10489]
When trying to multi-upload a bunch of ten 300MB files into my owncloud i faced a strange behaviour in ownCloud 5.0.13. 
My free ownCloud storage space was about 8,5GB with a max. filesize of 2GB configured when performing the following actions:

As I tried to upload all ten 300MB files to ownCloud using mirall client for WIndows v1.6.1, it only loads up the first file and after this giving the following error:
15:03     Workshop-Daten/Patricia Reum.zip                                ownCloud       Error downloading https://xxxx.xxx-xxx.net/remote.php/webdav/Workshop-Daten/Patricia Reum.zip-chunking-1351279547-23-2 - server replied: Bad request (expected filesize 10485760 got 0)          

The first file had been uploaded, but not the other nine files, however the complete 3GB had been processed/uploaded. No idea where other missing data was left.
After stopping and resuming the mirall client sync, the same issue happend again with the second file.

Then I tried to upload all the 10 files alltogether through the webclient, but the website canceled this try with error "Not enough space available", although about 8GB hab still been left as free space in my OC storage.

So, it seems that ownCloud counts the size of all files together, that are uploaded at a time. When the complete bunch of to be uploaded files exceeds the maximum file size, the operation gets cancelled, even if the single files to be uploaded are a lot smaller (300MB) than the configured max. filesize of 2GB.

**Comment by PVince81** [comment]
Please try with this solution: https://github.com/owncloud/core/issues/24653#issuecomment-220017778
If it doesn't work then your problem was a different one, in this case please reopen.
