### ISSUE TITLE
OC 7.x Web Interface Sharing

### ISSUE THREAD

**Issue by PepeN** [owncloud/core#10497]
OC 7.0.1 and multiple LDAP servers configured:

Click on "Share" and if you type a few letters and wait for the options, then wait for about 30 seconds.

Because the OC makes ldap requests to all servers.

But he (OC) has to look up users in the database (which in turn will be a hundred times faster).

![oc_7-share2](https://cloud.githubusercontent.com/assets/3851532/3953804/969470d6-26ef-11e4-8eab-e5292b97c72d.PNG)
.

Or am I mistaken?

**Comment by blizzz** [comment]
@PepeN is it actually any better with OC 8?
