### ISSUE TITLE
Make useful error messages!

### ISSUE THREAD

**Issue by NiLon** [owncloud/core#10509]
I have cron job set by owncloud and every 15 minutes I get this mail.
> Unexpected error!

Ok, what the frag is that? It doesn't explain the problem at all. It's completely **useless** error. And what does "unexpected" even mean? Are you saying there is errors that are expected?! Add errors that actually explain the problem! I have zero interest to start debugging whole file just to see where if fails each time it does.

**Comment by boltronics** [comment]
Still an issue in 7.0.4.

**Comment by PVince81** [comment]
Is this only about adding a useful message when cron is locked ?

**Comment by hostingnuggets** [comment]
I don't know if this happens when cron is locked but no matter what really happens to cron you should definitely use another more descriptive error message than "Unexpected error!". 

With this error message I am unable to fix the issue as I have no clue where to search for...

**Comment by xataxxx** [comment]
Like I mentioned before, I seem to get these Unexpected error! notifications when desktop client is busy uploading large files while cron starts.

**Comment by DeepDiver1975** [comment]
> Is this only about adding a useful message when cron is locked ?

we can add a meaningful message as soon as we understand the issue - which requires analysis

**Comment by DeepDiver1975** [comment]
I believe this has been fixed with https://github.com/owncloud/core/pull/14400
