### ISSUE TITLE
Webdav not syncing from androind

### ISSUE THREAD

**Issue by Tribalize** [owncloud/core#10503]
### Steps to reproduce
1. Davdroid install on android 4.4.2 S3
2. setup Davdroid to sync to https://owncloudinstall/remote.php/caldav/calendars/me/personal/
    setup Davdroid to sync to https://owncloudinstal/remote.php/carddav/addressbooks/me/contacts/
3. run sync on adnroid
### Expected behaviour
sync contacts and calendar to owncloud
### Actual behavior
nothing syncs to owncloud. owncloud throwing Webdav error
**Web server:** Linux Shared Host

**Database:** MySQL5

**PHP version:** 5.4

**ownCloud version:** ownCloud 7.0.1 (stable)

**Updated from an older ownCloud or fresh install:** Fresh Install

**List of activated apps:**
Files, Activity, Documents, Pictures, Calendar, Contacts, Bookmarks

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'oca047d280f1',
  'passwordsalt' => 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  'trusted_domains' => 
  array (
    0 => 'files.tribalize.com',
    1 => 'www.files.tribalize.com',
  ),
  'datadirectory' => '/homepages/35/d255602532/htdocs/public_html/trib/files/data',
  'dbtype' => 'mysql',
  'version' => '7.0.1.1',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'root',
  'dbpassword' => 'XXXXXXXXXXXXXX',
  'installed' => true,
  'defaultapp' => 'files',
  'theme' => '',
  'maintenance' => false,
  'loglevel' => '0',
);
**Are you using external storage:** No
**Are you using encryption:** No

### Client configuration
**Browser:** Chrome36, FF31
**Operating system:** Windows 7, Android 4.4.2

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Debug	core	OC\Tags::getFavorites, exception: Could not find category "_$!<Favorite>!$_"	2014-08-18T18:30:33+00:00
Debug	core	OC\Tags::loadTags, tags: Array ( )	2014-08-18T18:30:33+00:00
Debug	webdav	Sabre\DAV\Exception\NotAuthenticated: No basic authentication headers were found	2014-08-18T18:28:29+00:00
Debug	webdav	Sabre\DAV\Exception\NotAuthenticated: No basic authentication headers were found	2014-08-18T18:28:29+00:00
Debug	core	OC_Image->fixOrientation() Orientation: -1	2014-08-18T18:24:23+00:00
Debug	core	OC_Image->fixOrientation() No readable file path set.	2014-08-18T18:24:23+00:00
Debug	contacts	Caching contact-thumbnail-local::1::164	2014-08-18T18:23:43+00:00
Debug	contacts	Caching contact-thumbnail-local::1::162	2014-08-18T18:23:43+00:00
Debug	contacts	Caching contact-thumbnail-local::1::161	2014-08-18T18:23:43+00:00
Debug	contacts	Caching contact-thumbnail-local::1::159	2014-08-18T18:23:43+00:00
Debug	contacts	Caching contact-thumbnail-local::1::157	2014-08-18T18:23:43+00:00
Debug	contacts	Caching contact-thumbnail-local::1::156	2014-08-18T18:23:43+00:00
Debug	contacts	Caching contact-thumbnail-local::1::133	2014-08-18T18:23:43+00:00
Debug	webdav	Sabre\DAV\Exception\NotAuthenticated: No basic authentication headers were found	2014-08-18T18:28:29+00:00
```
Have updated DAV/Auth/Backend/AbstractBasic.php as mentioned here https://github.com/fruux/sabre-dav/pull/458

Still throwing same error with every sync. 
Sabre\DAV\Exception\NotAuthenticated: No basic authentication headers were found

**Comment by jancborchardt** [comment]
@Tribalize can you please contact 1and1 support so they fix that problem on their end?

**Comment by Tribalize** [comment]
Since the upgrade to sabre 2 i havent looked into this just yet.
