### ISSUE TITLE
WebDav access under Linux doesn't work after update without changing the configuration

### ISSUE THREAD

**Issue by ckruetze** [owncloud/core#10519]
Up to version 6.0.4 davfs under Linux (tested with Ubuntu 14.04) worked like expected, but after an update to version 7.0.1 new documents can't be created without changing the davfs configuration.

The problem can be solved by changing the ~/.davfs2/davfs2.conf file and set "use_locks" to 0.
See also the forum discussion at: https://forum.owncloud.org/viewtopic.php?f=29&t=22613

In general locking a file while writing to it seems a good idea, so I would really like to be able to do that. Also the change means one additional step to do for every user that wasn't needed under the older versions.

### Steps to reproduce
1. Use version 6.0.4 and have a davfs mount
2. Update to version 7.0.1
3. Try copying a file to the davfs share

### Expected behaviour
It should just work, like in version 6

### Actual behaviour
The copy doesn't work. Ubuntu gives an error message "the system cannot find the file specified"

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Appache

**Database:**
MySQL
**PHP version:**
5.5.9
**ownCloud version:** (see ownCloud admin page)
7.0.1
**Updated from an older ownCloud or fresh install:**
updated from 6.0.4 

**List of activated apps:**
Calendar, Contacs, First Run Wizard, Full Text Search, LDAP user and group backend, PDF Viewer, Pictures, Share Files, Text Editor, Updater, Versions, Video Viewer

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '520a1cfd54290',
  'passwordsalt' => 'xxx',
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.1.1',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'theme' => '',
  'maintenance' => false,
  'forcessl' => true,
  'trusted_domains' => 
  array (
    0 => 'xxx.xxxx.com',
  ),
  'mail_from_address' => 'xx',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'xxx.com',
  'mail_smtphost' => 'xxx.xxx.xxx.xxx',
  'mail_smtpport' => '25',
);

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
### Client configuration
**Browser:**
Firefox, but bug not broweser related
**Operating system:**
Ubuntu 14.04
the line from fstab
https://xxx.xxx.com/remote.php/webdav /home/christian/Cloud davfs noauto,user,rw 0 0

#### Web server error log
```
Can't access them right now. But if they are needed I will get them.
```

#### ownCloud log (data/owncloud.log)
```
A lot of those
Error	PHP	Invalid argument supplied for foreach() at /var/www/owncloud/apps/user_ldap/lib/access.php#201

(but not sure if they are related)
```

**Comment by PVince81** [comment]
Locks have been removed in 8.1

**Comment by PVince81** [comment]
Is this still happening in 8.0.5 or 8.1 ?

**Comment by PVince81** [comment]
Please try again with 8.1.3.

Regarding webdav locks, see https://github.com/owncloud/core/issues/17732
