### ISSUE TITLE
maximum row size error when upgrading to 7.0.1

### ISSUE THREAD

**Issue by mdieterich** [owncloud/core#10529]
Greetings,

I'm trying to upgrade from OC 6.04 to OC 7.0.1.  My installation sits on top of a clustered MySQL instance, so I require that my table engine type is ndbcluster.  Apparently, there are different maximum row sizes available with this engine, so when I try and convert the oc_share_external table, it bombs out with an error:

ERROR 1118 (42000): Row size too large. The maximum row size for the used table type, not counting BLOBs, is 14000. You have to change some columns to TEXT or BLOBs

Looking at the table:

mysql> describe oc_share_external;
+-----------------+---------------+------+-----+---------+----------------+
| Field           | Type          | Null | Key | Default | Extra          |
+-----------------+---------------+------+-----+---------+----------------+
| id              | int(11)       | NO   | PRI | NULL    | auto_increment |
| remote          | varchar(512)  | NO   |     | NULL    |                |
| share_token     | varchar(64)   | NO   |     | NULL    |                |
| password        | varchar(64)   | NO   |     | NULL    |                |
| name            | varchar(64)   | NO   |     | NULL    |                |
| owner           | varchar(64)   | NO   |     | NULL    |                |
| user            | varchar(64)   | NO   | MUL | NULL    |                |
| mountpoint      | varchar(4000) | NO   |     | NULL    |                |
| mountpoint_hash | varchar(32)   | NO   |     | NULL    |                |
+-----------------+---------------+------+-----+---------+----------------+
9 rows in set (0.00 sec)

I see that it's full of varchar types and I'm curious if there is a reason for doing this over just using a text type, especially for something large like mountpoint.  I think this would solve my issue.  In the mean time, I'm also looking into whether or not there is some ndbd setting I can change to increase the maximum row size, but thought you might want to know about this issue... in case anyone else runs across it.

Thanks!

Mark

**Comment by mdieterich** [comment]
Wondering if there is any hope of getting a fix for this or am I perpetually stuck at OC 6.0.4? I see that in OC 7, the occ tool was introduced which would potentially let me migrate over to a different database backend that would not have this limitation, alas I can't get there. Is there any chance the occ tool can be used with an earlier version of the code? Is there a way I can manually convert from say MySQL to Postgres?

**Comment by DeepDiver1975** [comment]
We need up to 4000 chars on the mountpoint because this is the max path length we do support and the mountpoint can technically be any valid path.

Feel free to adopt https://github.com/owncloud/core/blob/stable7/apps/files_sharing/appinfo/database.xml#L64 to get this in your db

**Comment by mdieterich** [comment]
Sorry, my summer got busy and I'm just now getting back to this. Can you point me to a quick primer on how the xml structure you pointed me to is translated into a database schema? Even what toolset is used to do the db updates would be helpful. What I'm struggling with is why a size needs to be defined at all. MySQL suports text type objects, which don't require a maximum size be defined. My understanding is the ndb deals just fine with these, because the underlying table structure results in a pointer and doesn't explode the individual record size.

Thanks!

Mark

**Comment by PVince81** [comment]
Are you still stuck on OC 6 ?

**Comment by PVince81** [comment]
Please reopen if this is still an issue, but note that OC >= 8.2 is already EOL so no fixes will be provided for older versions.

**Comment by PVince81** [comment]
for support/assistance, see http://owncloud.org/support
