### ISSUE TITLE
No reuse of eTag for files when using webDAV and Desktop-Client

### ISSUE THREAD

**Issue by mookuh2k5** [owncloud/core#10538]
### Steps to reproduce
1. Have a user using both WebDAV and the (Windows) Desktop Client
2. Add a file to either the WebDAV share or the synced folder 

Could be reproduced with two different owncloud instances. I also tried different versions of the client, but the problem appeared everytime a new file was added.

### Expected behaviour
No issues

### Actual behaviour
Everytime a new file is uploades an owncloud log entry is created telling that there is "No reuse of eTag for ..." and the server load get very high. 

### Server configuration
**Operating system**: Debian 7.6

**Web server:**  Apache/2.2.22

**Database:** mysql 5.5.83

**PHP version:** 5.4.4

**ownCloud version:** 7.0.1 

**Updated from an older ownCloud or fresh install:** Update from owncloud 6

**List of activated apps:** Default apps

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'trusted_domains' =>
  array (
    0 => 'my.domain.com',
  ),
  'datadirectory' => '/data/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.1.1',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'xxx',
  'installed' => true,
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => '0',
  'enable_previews' => false,
);

```

**Are you using external storage, no

**Are you using encryption:** no

### Client configuration
**Browser:** Firefox

**Operating system:** Windows 7/XP

### Logs

The log basically contains a lot of 'No reuse of eTag for file' messages combined with a 'can not update etags on files'

**Comment by PVince81** [comment]
The entry was moved to DEBUG and is harmless.
