### ISSUE TITLE
Set the sender mail address by user

### ISSUE THREAD

**Issue by offlinehoster** [owncloud/core#10545]
I don't see any options to set the real owncloud user mail address as sender address for shares…

The main 
"mail_from_address" => "owncloud",
is ok for the password recovery option, but receiving a share mail with the full mail address from the sharing user would me more useful.

Is this already a milestone feature or a known "problem/issue" ?

Cheers
Christian

**Comment by MorrisJobke** [comment]
stable7 #15559

**Comment by MorrisJobke** [comment]
stable8 #15558
