### ISSUE TITLE
On Mobile, Notifications block the apps menu

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#10544]
### Steps to reproduce
1. View ownCloud from an admin account, running 7.0.0 on a mobile device

### Expected behaviour
 - Should be able to click on apps menu

### Actual behaviour
 - Notification blocks the view of the apps menu

![screenshot_2014-08-20-12-07-32](https://cloud.githubusercontent.com/assets/660805/3979913/e30ed1d8-285a-11e4-8d35-789fba8da847.png)

**Comment by jancborchardt** [comment]
@MorrisJobke do we have the timeout implemented for the notifications now?

If not, maybe it’s a good idea to just not show the version update notification on mobile.

**Comment by MorrisJobke** [comment]
@jancborchardt It is: OC.Notifications.showTemporary: https://github.com/owncloud/core/blob/92791bb8ba5192c4bf84d8c1756aa5b2463d14a4/core/js/js.js#L800

**Comment by jancborchardt** [comment]
Fix at https://github.com/owncloud/core/pull/15190
