### ISSUE TITLE
Deal with PHP installations limited to 32 bit

### ISSUE THREAD

**Issue by danimo** [owncloud/core#10543]
Right now, many people seem to install ownCloud on their embedded hardware or NAS hardware. That usually only has 32 bit user lands and the PHP version on it only supports 32 bit integers and comes without large file supports.

Complaints about this end up in the mirall bug tracker. In order to reduce support load, it would be good if:

1. the server would issue a warning in the admin panel if a 32 bit PHP version is detected (or large file support exists, see #7138)
2. The WebDAV server should properly refuse files > 4 GB on the WebDAV interface (note: also needs to work with chunking and return a useful error message if possible).

How much effort would that be? Can this be done during the OC7 cycle?

@bantu @DeepDiver1975 @craigpg

**Comment by Xenopathic** [comment]
Warning is displayed after #12781, available in oC 8.0.0
