### ISSUE TITLE
[enhancement] - set shared folders initial view

### ISSUE THREAD

**Issue by githubrsys** [owncloud/core#10555]
[enhancement] - [usability improvement]

It would be useful if you could set the initial view of a shared folder as rule. 
### Usecase

If you share a folder which content is only images it makes sense in the POV of the reciever that the gallery-view is chosen automatically at the time the folder is opened.

This avoids dumb questions from unexpirienced users.
### Hint

Especially in "shared by password folders" on mobile device recievers this makes a lot of sense.

**Comment by jancborchardt** [comment]
Yeah, we had this issue in the gallery some time as well.

When the content of a shared folder is 100% images, use the gallery view by default. cc @owncloud/designers @oparoz.
