### ISSUE TITLE
Can't change user profile picture when there is no more quota available

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#10565]
### Steps to reproduce
1. In browser 1, as the admin user, create a new user
2. In browser 2, log in as the new user, select personal from the user drop down
3. Set the profile picture (no need to log out)
3. Back in browser 1, change the user quota to 0.
4. Back in browser 2, click "Select new from Files" to change the profile picture.

The user is not allowed to select a new photo and gets a broken image.

![p4](https://cloud.githubusercontent.com/assets/8480343/3988956/70c86a8a-28b4-11e4-9353-72bba48c75cb.PNG)

Change  the quota back to a non-zero value and the user in browser 2 can modify their profile picture

### Expected behaviour

The user should be able to change their profile picture.  Even if they aren't able to change it, they should get a better error message  

### Actual behaviour

The user can't change their profile picture and the error message is not helpful.

### Server configuration

**ownCloud version:** (see ownCloud admin page)

ownCloud 7.0.1 (daily) Build:2014-08-20T03:18:51+00:00

**Comment by PVince81** [comment]
Will be obsoleted by moving avatars outside the "files" folder here: https://github.com/owncloud/core/issues/26124

Closing
