### ISSUE TITLE
No notice to user that oC6 does not support file share link download

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#10563]
### Steps to reproduce
1.upload file into 7.0.1
2.highlight file and select share
3.click share link
4.enter email address and click send (I sent it to myself so I could click on the link)
5.Get the email and click the "View It" link
6.In the browser where the file is viewed, enter a url to a non 7 version of oC in the "Add to your ownCloud" text box.  In my case, I entered a URL to oC 6.
7. I am brought to the login screen for the version of ownCloud that I entered but I am not able to save the file.  

I understand that this is because oC 6 doesn't support adding a shared file from a link.  
In this case, it would be nice to give some feedback to the user that the feature is not supported by the version I am trying to save the file to.  
My first thought was that the feature was broken.

### Expected behaviour

The user should be notified that copying a shared file from oC 7 link to any non oC7 version is not supported.

### Actual behaviour

The user logs into oC but the file isn't copied and there is no indication of what's going on or why the file isn't there.

### Server configuration

**ownCloud version:** (see ownCloud admin page)

Both

ownCloud 6.0.4 (daily) Build:2014-08-20T03:23:10+00:00 and
ownCloud 7.0.1 (daily) Build:2014-08-20T03:18:51+00:00

**Comment by MorrisJobke** [comment]
@PVince81 @LukasReschke If I understand this correct: We should add a check for this only if this is accessed by an ownCloud 6? So this is only valid for ownCloud 6 and just needs a fix in the stable6 branch? Is this wanted then I create the fix. cc @karlitschek

**Comment by LukasReschke** [comment]
@MorrisJobke Better approach would be to check the remote status.php file and then make a version comparison. So the fix should be in stable7 and master. We might introduce some backwards incompatible changes in the future (even if undesired) and that should be a more bullet proof approach.

**Comment by MorrisJobke** [comment]
Fix is ready for review in #13108

**Comment by MorrisJobke** [comment]
Will be fixed in 7.0.5 and 8.0.0
