### ISSUE TITLE
Public API to retrieve/manage versions

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#10571]
Just like we have the OCS Share API, it would be nice to also have a OCS Versions API so that external apps can manage versions.

Ideally the versions app itself should use that new API once it's implemented to avoid having multiple endpoints/ajax calls doing the same things.

Operations that come to mind:
1) Retrieve all versions for a given file
2) Revert file to a specific version
3) Retrieve previews for a file version (or call 1) could return the preview URLs)

CC @schiesbn

**Comment by PVince81** [comment]
Could/should probable be done with WebDAV.

Note that such tasks are important to be able to write automated tests

**Comment by PVince81** [comment]
@karlitschek can we schedule this ? Required for automated tests of versions.

**Comment by karlitschek** [comment]
I agree that it would be a very good idea. Time is tight. Let´s see what we can do :-/

**Comment by DeepDiver1975** [comment]
Still voting for webdav - we are talking about files ...

**Comment by PVince81** [comment]
I had a look at http://www.webdav.org/specs/rfc3253.html and I have the feeling that the spec expects the version history to be stable, aka version control. It might not suit the way how ownCloud versions work very well, as we're often discarding old versions.

In any case, the version control spec seems to provide unique URLs for every version, which is a good thing.

As a first step, we should probably look into adding a new WebDAV endpoint for files_versions.

Different proposals:
1) Map the original directory structure under the files_versions endpoint:
   - The versions of http://localhost/owncloud/remote.php/webdav/subdir/somefile.txt would by doing a PROPFIND of the directory http://localhost/owncloud/remote.php/files_versions/subdir/somefile.txt/
   - Every version would appear as a file inside that directory with timestamp of the version: "1234567.txt" (the extension might be needed, to be discussed)
   - Drawback is that the version URL changes if the file is moved. Not too bad a thing though.

or
2) Map by file id:
   - http://localhost/owncloud/remote.php/files_versions/{fileid}/{timestamp}
   - This keeps a stable URL for the file's versions even if the original file is moved or renamed.

In any case:
   - Calling GET http://localhost/owncloud/remote.php/files_versions/{fileid}/{timestamp} downloads the version of the file
   - Calling anything else like PUT, DELETE, MOVE will fail with MethodNotAllowed
   - How to restore a file ? One idea would be to MOVE http://localhost/owncloud/remote.php/files_versions/{fileid}/{timestamp} to the original location of the file http://localhost/owncloud/remote.php/webdav/subdir/somefile.txt

If in the future we choose to also implement the official Webdav versioning verbs, we might be able to do this partially. So calling REPORT http://localhost/owncloud/remote.php/webdav/subdir/somefile.txt could respond with something like this:
```
REPORT /remote.php/webdav/subdir/somefile.txt HTTP/1.1
Host: owncloudhost.com
Content-Type: text/xml; charset="utf-8"
Content-Length: xxxx

<?xml version="1.0" encoding="utf-8" ?>
<D:version-tree xmlns:D="DAV:">
 <D:prop>
   <D:version-name/>
 </D:prop>
```
```
HTTP/1.1 207 Multi-Status
Content-Type: text/xml; charset="utf-8"
Content-Length: xxxx

<?xml version="1.0" encoding="utf-8" ?>
<D:multistatus xmlns:D="DAV:">
 <D:response>
   <D:href>http://owncloudhost.com/remote.php/files_versions/subdir/somefile.txt/1000000</D:href>
   <D:propstat>
     <D:prop>
       <D:version-name>100000</D:version-name>
     </D:prop>
     <D:status>HTTP/1.1 200 OK</D:status>
   </D:propstat>
 </D:response>
 <D:response>
   <D:href>http://owncloudhost.com/remote.php/files_versions/subdir/somefile.txt/2000000</D:href>
   <D:propstat>
     <D:prop>
       <D:version-name>2000000</D:version-name>
     </D:prop>
     <D:status>HTTP/1.1 200 OK</D:status>
   </D:propstat>
 </D:response>
 <D:response>
   <D:href>http://owncloudhost.com/remote.php/files_versions/subdir/somefile.txt/2500000</D:href>
   <D:propstat>
     <D:prop>
       <D:version-name>2500000</D:version-name>
     </D:prop>
     <D:status>HTTP/1.1 200 OK</D:status>
   </D:propstat>
 </D:response>
</D:multistatus>
```

Note: we wouldn't use "create-displayname" or "success-set" as the latter is used when branching, which we don't have. But we could still return proper values for them.

**Comment by PVince81** [comment]
If I understand well, the following associations from the RFC apply to us:
- auto-versioning: any changes to the original file creates a version
- checking out a version: equivalent of restoring a version ?
- checking in: means explicit creation of a version, not applicable in OC due to auto-versioning

But page 14 of the RFC seems to imply that even the core package of the version feature is supposed to provide a way for clients to work on different versions of a resource in parallel, without disturbing each other. This might be what they mean with "check out" and "check in".

This might already be going too far and not be suitable for us.
So implementing an API that only does half of it might not be a good idea, as versioning-capable clients might believe that it works this way when it doesn't.

So we should probably go either with our own invented WebDAV extensions, or more simply providing the versions as a simple file tree as proposed here in https://github.com/owncloud/core/issues/10571#issuecomment-104601521. And each version could simply be retrieved/downloaded with GET. We'd need a special verb for restoring the file to a previous version.
Deletion of older versions could be supported, if we want too (optional).

**Comment by cmonteroluque** [comment]
Note for 9.1: https://github.com/owncloud/client/issues/4556

**Comment by PVince81** [comment]
Moving to 9.2

**Comment by PVince81** [comment]
I think I'd vote for the following spec now that we have more experience with Webdav:

- base URL for version of a specific file looks like http://localhost/owncloud/remote.php/dav/files_versions/$fileid, which itself is a collection
- PROPFIND on "files_versions" forbidden as it would return all possible files
- timestamp for version looks like http://localhost/owncloud/remote.php/dav/files_versions/$fileid/$timestamp: the timestamp is the name of the file node.
- GET http://localhost/owncloud/remote.php/dav/files_versions/$fileid/$timestamp will download the version of the file, with proper file name and mime type
- DELETE http://localhost/owncloud/remote.php/dav/files_versions/$fileid/$timestamp will delete the version
- MOVE http://localhost/owncloud/remote.php/dav/files_versions/$fileid/$timestamp with a destination will restore the version in the given location. This makes it possible to either replace the original file or choose another location. (the web UI would default to only overwriting as before, for simplicity)
-  REPORT with name "versions-list" on http://localhost/owncloud/remote.php/dav/files/$user/folder/filename.txt
    - returns a PROPFIND-like multistatus response with a list of version URLs as hrefs: http://localhost/owncloud/remote.php/dav/files_versions/$fileid/$timestamp
    - if properties were specified in a "DAV:prop" block, these are retrieved as well
    - the only available extra property: "DAV:getlastmodified" which would match the version's timestamp
    - I don't think we want/need other properties because the metadata can be retrieve from the original file, also versions do not have metadata history so they share the same metadata as the original file (tags, favorite, share, etc)

**Comment by PVince81** [comment]
Hmm, I seem to have forgotten the "$user" part of the URL. But anyway, with a $fileid that one isn't needed...

**Comment by PVince81** [comment]
- [ ] blocked by https://github.com/owncloud/core/issues/26195

**Comment by PVince81** [comment]
backlog for now

**Comment by SamuAlfageme** [comment]
Linking this here: https://github.com/owncloud/core/pull/29257

**Comment by PVince81** [comment]
Done with https://github.com/owncloud/core/pull/29257
