### ISSUE TITLE
Viewing shared folder creates a bunch of Undefined Offset errors

### ISSUE THREAD

**Issue by Bugsbane** [owncloud/core#10582]
Every time I go into a folder that I have shared, I get a bunch of the following errors in the log:

Undefined offset: 1 at /path/to/owncloud/lib/private/share/share.php#1389

Its always the same filename and line number. This is on an install that was recently upgraded from 6.0.4 to 7.0.0 and then 7.0.1, with Sqlite3 and Nginx, on Arch, viewed in Firefox. There isn't anything like uwsgi or selinux.

I'm not sure if this is contributing, but it is a folder that was shared before the 6 > 7 upgrade. After the upgrade it didn't seem to be shared, so I shared it again.

**Comment by MorrisJobke** [comment]
@schiesbn ping

**Comment by MorrisJobke** [comment]
@schiesbn Feel free to ask the questions.

**Comment by PVince81** [comment]
@Bugsbane are you still seeing this in 8.0.5 or 8.1 ?

**Comment by PVince81** [comment]
Please try again with 8.1.3 or 8.2RC1 and reopen if you still see this issue in that version.
