### ISSUE TITLE
Impossible rename files inside the folder after creating a sharing loop

### ISSUE THREAD

**Issue by labkode** [owncloud/core#10589]
Scenario based on issue #5491
User A has folder A with file test.txt inside.
User A share folder A with User B
User B share folder A with User C
User C share folder A with User A
User A now see folder A and folder A(2).
We are now User A.
If we rename test.txt file inside folder A the rename is succcesfull. If we rename from folder A(2) the response from th server is empty and the loading icon is in a infinite loop and the file is not renamed.

Try to debug this is a chaos . I think it would be great having some refactorization at some point in the future :)

**Comment by MorrisJobke** [comment]
@schiesbn Ping

**Comment by PVince81** [comment]
I checked this on stable7 (the upcoming 7.0.6) and now the first user doesn't see a folder "A (2)" any more. A lot of grouping logic has been added in OC 7.

Closing.
