### ISSUE TITLE
Deleting file on external mountpoint via SFTP - Deletes recursive files/folders

### ISSUE THREAD

**Issue by Crasha** [owncloud/core#10593]
When deleting a file within an external mount via SFTP, it deletes recursively ALL the files within the folder when it does NOT have permission to delete the main folder. 

E.G, we have a folder called Test when we go into this external mount point. We cannot delete Test since we don't have permission too. However, it will delete all files within the folder, since we have access to anything INSIDE that folder.

Owncloud should not recursively delete anything inside the folder if it cannot delete the folder in the first place.

The biggest concern is that when we go into "Deleted files" and try and restore the folder that Owncloud "thinks" it has deleted, it cannot overwrite the folder that you cannot delete in the first place, thus it deletes EVERYTHING inside that folder from the recycle bin, so all the files are lost permanently.

**Comment by PVince81** [comment]
Still happens on stable7 and master.

**Comment by PVince81** [comment]
@Xenopathic in case you're interested

**Comment by PVince81** [comment]
Still happening in 8.2.0. I had hoped that the recent changes to the trashbin logic would catch that, but it isn't solved.

**Comment by schiesbn** [comment]
> Still happening in 8.2.0. I had hoped that the recent changes to the trashbin logic would catch that, but it isn't solved.

This has nothing to do with the trash bin. The trash bin moves the files to the trash bin which gets deleted by the file system. Most likely the logic to delete the files recursively is implemented somewhere in the ftp external storage implementation. Maybe this gets solved once we switch to @icewind1991 ftp implementation https://github.com/owncloud/core/issues/19941

**Comment by PVince81** [comment]
SFTP, not FTP

**Comment by PVince81** [comment]
Fixed recently: https://github.com/owncloud/core/pull/22518
