### ISSUE TITLE
Always show "File handling" input box

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#10600]
Hi,

currently the "File handling" input box is only shown if Apache is used where the webserver user has write permission to the .htaccess file shipped by OC.

This has often causing confusion in the forums as well as in bugreports like: https://github.com/owncloud/documentation/issues/493

To avoid this maybe it could be useful to always show this "File handling" input box and grey it out including a note why it can't be used at the current environment.

**Comment by jancborchardt** [comment]
Fixed via https://github.com/owncloud/core/pull/14133, thanks to @rullzer! :)
