### ISSUE TITLE
Enable maintenance mode while updating package

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#10602]
### Steps to reproduce
1. Setup ownCloud from package, for example RPM package
2. Continuously access ownCloud, make HTTP request
3. Update the ownCloud package

### Expected result
Maintenance mode should be enabled before the package is extracted
Or if possible, all access to ownCloud should be blocked somehow.

### Actual result
It seems that ownCloud is still accessible, but HTTP calls fail with Internal Server Error due to missing classes, possibly because the code is half-updated.

Note: this is probably more a corner case related to packaging.
Normally I manually set maintenance mode to true before updating the package.

@jnweiger what do you think ?
Not sure how it's done for other packaged web applications.

**Comment by jnweiger** [comment]
@PVince81 The owncloud 8 server packages now set maintenance mode before they start the upgrade.
Does that complete the packaging part of this issue?

**Comment by PVince81** [comment]
I see in the spec that you also stop Apache2 now ?
Thinking of it stopping Apache2 might not be enough due to possibly running cron jobs.

So, disabling maintenance mode is indeed the way to go.
I see in the spec that in %post it will also run `./occ upgrade` which will automatically run the upgrade.

So, that's done.

**Comment by jnweiger** [comment]
There is not much we can do about cron jobs. Killing them is bad.
Enhancement idea:
Is occ able to tell me that a backgorund job is running? If so, we could wait and poll for a few minutes.

**Comment by PVince81** [comment]
Not sure. I remember there were talks about creating a cron lock file ? Was this done ? @icewind1991 @DeepDiver1975 ?
