### ISSUE TITLE
  Cifs external storage : utf-8 problem ?

### ISSUE THREAD

**Issue by Marcatquod** [owncloud/core#10625]
Hello !

I mounted a Synology NAS as external storage (cifs) on my OwnCloud 7.0.1. I get troubles with some files not showing into OC. After some googling + seeking this forum, I can't find something similar.

I ask there before opening a bug to see if anybody else got in trouble with same problem.

What I did :
- removing / re-doing the attachement
- checking the rights (user, login...)
- creating a cron job to force cache sync (occ files:scan --all ...)
...
No way.

Finaly, I think I found the problem in "cache scanner". If a file in the dir currently scanning presents a "non ascii" char (like éàè...), the "$path" varible is corrupted.

The dir contains these files :
01-AO DSE - CG_Conditions_Generales_AVASAD_V1.0 (1e copie).pdf
02-AO DSE - CG_Conditions_Génerales_AVASAD_V1.0 (2e copie).pdf <= é !!
03-AO DSE - CG_Conditions_Génerales_AVASAD_V1.0 (3e copie).pdf <= é !!

When scanner runs, the log shows :
    {"reqId":"53fb3d872d417","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path '2014\/RC\/OC-problem\/03-AO DSE - CG_Conditions_G  01-AO DSE - CG_Conditions_Generales_AVASAD_V1.0 (1e copie).pdf' is not readable !!!","level":0,"time":"2014-08-25 13:43:35","method":"PROPFIND","url":"\/remote.php\/webdav\/QuodAdmin%40NAS\/2014\/RC\/OC-problem\/"}

The "$path" shows incomplete file name "03-AO DSE - CG_Conditions_G" interrupted just before the "é" and continues with the filename of the first file "01-AO DSE - CG_Conditions_Generales_AVASAD_V1.0 (1e copie).pdf".

Actualy, I get many similar messages with "accents" into their name and the files are not showing through OC...

Any idea ? Misconfigured OC ?

Thanks in advance for your help !

My configuration :
- Own server, Debian Wheezy
- OC 7.0.1
- MySQL 5.5.38
- PHP 5.4.4
- APC 3.1.13
- Apache2 2.2.22

My config.php file 
<?php
$CONFIG = array (
  'instanceid' => 'ocb92391edc3',
  'passwordsalt' => 'eae7a8bf6cc4953698368244aa3804',
  'trusted_domains' =>
  array (
    0 => '192.168.30.67',
    1 => 'cloud.quodapps.ch',
    2 => 'timide',
  ),
  'datadirectory' => '/var/spool/owncloud/quod',
  'dbtype' => 'mysql',
  'version' => '7.0.1.1',
  'dbname' => 'quodcloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_oc_admin_quod',
  'dbpassword' => '**hide**',
  'installed' => true,
  'mail_from_address' => 'quodcloud',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'quod.ch',
  'mail_smtpname' => 'masc',
  'mail_smtppassword' => '**hide**',
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/var/www/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/var/www/owncloud/apps2',
      'url' => '/apps2',
      'writable' => true,
    ),
  ),
  'logdateformat' => 'Y-m-d H:i:s',
  'log_rotate_size' => '10485760',
  'loglevel' => '0',
  'appstoreenabled' => false,
  'appcodechecker' => false,
  'updatechecker' => false,
  'enable_previews' => true,
  'theme' => 'quod',
  'preview_libreoffice_path' => '/usr/bin/soffice',
  'forcessl' => true,
);

**Comment by PVince81** [comment]
@icewind1991 what do you think ?

**Comment by Phillinger** [comment]
@Marcatquod thanks for the workarround, great work!

**Comment by DeepDiver1975** [comment]
With owncloud 8.1 we use a different library to connect to smb/cifs shares - this should be fixed - please reopen if issue still persists. THX

**Comment by Phillinger** [comment]
With owncloud 8.1 on Debian Wheezy the error is back. Folders/Files with umlauts are not displayed correctly and can't be opened. Since the configuration of the app has changed, the workarround as mentioned above doesn't work anymore.

Got it fixed for me by changing the following file:
`/var/www/owncloud/apps/files_external/3rdparty/icewind/smb/src/Server.php`

There, i changed the `const LOCALE = 'en_US.UTF-8';` to `const LOCALE = 'de_DE.UTF-8';`

**Comment by Xenopathic** [comment]
cc @icewind1991

**Comment by PVince81** [comment]
Please try 9.1.0beta2. If it doesn't work, try setting the new "encoding compatibility" mode in the external storage's advanced settings (cog icon) and then run "occ files:scan --all" once.

If the problem persists, please open.
