### ISSUE TITLE
What should we do to the already shared items when force expiration is changed?

### ISSUE THREAD

**Issue by vgezer** [owncloud/core#10648]
Currently, when we share a file, set with an expiration date, then force the expiration date to a date before this date, it is not affected. Should we expire all shares exceeding this expiration date or do you think this behaviour is the correct one?

**Comment by Xenopathic** [comment]
RE: setting an expiry date older than today, try again with oC 8.1.1

RE: touching shares when the policy is changed - IMHO this would add unneeded complexity, the admin should make sure the policy is defined before users have access to the system
