### ISSUE TITLE
Feature Request: Wake-On-Lan for external storage

### ISSUE THREAD

**Issue by Larx** [owncloud/core#10655]
I want to include a NAS as external storage into OC. This NAS is not accessed regularly, therefore it could be shut down most of the time. However, it has to wake automatically if it is accessed.

Currently this is not possible. It would be an enhancement if OC could include an option to send a magic WOL paket before accessing external storage. There seem to be PHP code pieces out there which do WOL, so this should be possible in theory.

**Comment by PVince81** [comment]
This is not really the responsibility of core or the external storage system, as the PHP code cannot know about hardware details. Should be implemented as a separate app.

If any hooks are required in core for such app to operate, please open tickets for the hooks in question.
