### ISSUE TITLE
Drag & Drop Support for Navigation Order

### ISSUE THREAD

**Issue by vgezer** [owncloud/core#10654]
Currently we have `'order' => X,` support to sort the app in navigation menu. However, these values should be hardcoded into app.php. It will be nice if we can drag the apps in the menu to change their display order.

See google application menu for example:

![image](https://cloud.githubusercontent.com/assets/231068/4054589/f2bd8b60-2d91-11e4-8403-a2a7769bf858.png)

**Comment by chrisjscott** [comment]
+1

**Comment by sorglos** [comment]
:+1:

**Comment by jancborchardt** [comment]
This has too much potential for breakage and we need to maintain it, as opposed to the very little benefit. On top of it, no one stepped up to do it, so I’m closing it.
