### ISSUE TITLE
Solve timeout problem during initial encryption

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#10657]
We get regularly bug reports from people who activated the encryption at a stage where they already have many (large) files stored on their ownCloud. The initial encryption can take really long in this case and people often run into timeouts.

Possible ways to solve it:

1. Don't allow to enable encryption on a running ownCloud. Instead make it a decision during installation. Either you install your ownCloud with encryption or without. But don't provide a easy way to switch back and forth.

2. If we consider step 1 to radical we could change the way the initial encryption works by moving to ajax calls. We would first fetch a list of all files and then encrypt the files in chunks with several ajax requests. Drawback: Users would need to login over the web interface for the first time after the encryption was enabled.

I already discussed this briefly with @PVince81 any other opinions?

cc @craigpg  @karlitschek @DeepDiver1975 @butonic and of cause anybody else.

**Comment by schiesbn** [comment]
I think this was more a general brain-storming issues.

Concrete steps which tackle all stuff discussed here are:

- I think the command line script is the preferred way to go. The migration we have now should be only for really small installations on shared hosters where the user can't execute command line scripts. But for them I would recommend to enable encryption from the beginning. Shouldn't be hard to migrate a small instance to a new one with encrytion on from the beginning https://github.com/owncloud/core/issues/10956

- Config option for external storage to enable/disable encryption per-storage: https://github.com/owncloud/core/issues/12216

**Comment by carlaschroder** [comment]
so....does this need an oC 8 release note, and what should it say? "don't use the encryption app"  :)

@MTRichards 
@schiesbn 
@MorrisJobke 
@PVince81

**Comment by MorrisJobke** [comment]
> "don't use the encryption app" :)

Yes.

**Comment by MorrisJobke** [comment]
@carlaschroder Just kidding. No idea. @schiesbn can answer this best I guess

**Comment by MTRichards** [comment]
I think a release note on performance when encrypting a large number of files would be a good idea.

**Comment by carlaschroder** [comment]
done.
