### ISSUE TITLE
[oC7.0.2RC1] Expected behaviour when I exclude groups from sharing.

### ISSUE THREAD

**Issue by fernandoruiz** [owncloud/core#10651]
### Steps to reproduce actual behaviour:
Share some files and/or folders from user1 to user2.
From user1 instance I check the option "Exclude groups from sharing" and select the user1 group.
Then disappear filters "Shared with others" and "Shared by link" even though the files and/or folders continue being shared in user2.

I think the behaviour is wrong, but I would like to know the expected behaviour.

**Operating system:** Ubuntu 14.04
**Web server:** Apache/2.4.7
**PHP version:** PHP Version 5.5.9-1ubuntu4.3
**ownCloud version:** ownCloud 7.0.2RC1

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/issues/17346
