### ISSUE TITLE
GoogleDrive Integration - Can't delete files

### ISSUE THREAD

**Issue by zakoon** [owncloud/core#10662]
Deleting of Files in GoogleDrive via OC-Interface fails.
Uploading & downloading seems to work. 

Notes:
A) It might be a permission problem. I tried to follow the OC-Documentation to connect with GD, but the Documentation doesn't fit the current UI of Googles Developer Website, so I might have missed something...

B) It might be a File-Size Problem, the files I want to delete are large, and I noticed that deleted files are shown under "Deleted Files", so OC is downloading the Files I delete from GD?!!! I use GD for files that are to big for my oc, so this behavior makes no sense to me...

### Steps to reproduce
1. Connect OC with GoogleDrive
2. Access the GoogleDrive Folder in the OC Interface
3. Try to delete a file

### Expected behaviour
File should be deleted

### Actual behaviour
Delete-Circle keeps spinng, file is not deleted

### Server configuration
Hosted Webspace
**Database:**
SQLite
**PHP version:**

**ownCloud version:** (see ownCloud admin page)
7.0.1
**Updated from an older ownCloud or fresh install:**
Fresh install

**Are you using external storage, if yes which one:** local/smb/sftp/...
GoogleDrive

**Are you using encryption:** yes/no
no

#### ownCloud log (data/owncloud.log)
Error 	PHP 	Allowed memory size of 134217728 bytes exhausted (tried to allocate 106706885 bytes) at /var/www/web361/html/oc/apps/files_external/3rdparty/google-api-php-client/src/io/Google_CurlIO.php#112 	2014-08-27T09:13:22+00:00

**Comment by PVince81** [comment]
@zakoon an option will be added in the future to disable trashbin for specific external storages: https://github.com/owncloud/core/issues/4389
