### ISSUE TITLE
Setting the email address on the personal page can save too early and a user can't delete a value

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#10665]
### Steps to reproduce
1. Click on Personal link to set/change your email
2. Enter a value
3. Try to edit the value - sometimes the email address gets saved too early
4. Try to delete the value - I was unable to delete the address

![p18](https://cloud.githubusercontent.com/assets/8480343/4058912/b377380c-2ddc-11e4-84a4-199c214f5822.PNG)

![p19](https://cloud.githubusercontent.com/assets/8480343/4058914/ba56552c-2ddc-11e4-9f25-1aa7c2e47821.PNG)

### Expected behaviour

The email address value shouldn't be saved too early and the user should be able to delete the address all together.

### Actual behaviour

The email address value can be saved too early and the user is unable to delete the address all together.

### Server configuration

**ownCloud version:** 

ownCloud Enterprise Edition 7.0.2 (daily) Build:2014-08-27T03:02:53+00:00

**Comment by nickvergessen** [comment]
@jancborchardt can you do this?

**Comment by jancborchardt** [comment]
Just increase the timeout a bit maybe?

**Comment by PVince81** [comment]
Note: deleting the email address works for me in 8.2.0

**Comment by PVince81** [comment]
The delay is currently at 1 second https://github.com/owncloud/core/blob/v8.2.0/settings/js/personal.js#L26. I think it's fine the way it is (not critical)

As the deletion issue is already fixed, closing.
