### ISSUE TITLE
Updating a password using OCS Share API changes the share ID

### ISSUE THREAD

**Issue by Azelphur** [owncloud/core#10671]
If you make an API call using the OCS Share API and set a password on a share, it appears to change the share ID. Not sure if this is intended or not.

Paging @PVince81 as requested.

**Comment by PVince81** [comment]
@DeepDiver1975 moved to 8.1

**Comment by rullzer** [comment]
WIP PR in #14868

**Comment by MorrisJobke** [comment]
Fixed in #14987
