### ISSUE TITLE
OCP\Config::setUserValue returns false if no rows affects OR if exception

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#10672]
### Steps to reproduce
1. Use OCP\Config::setUserValue

### Expected behaviour
Returns false when no rows affected

### Actual behaviour
Returns false ALSO if exception occurred.

OC\Preference::setValue returns a bool, indicating if any rows have been affected: https://github.com/owncloud/core/blob/cb0da1178b0872988582ee5fbf6b5b1cb5ea2527/lib/private/preferences.php#L221

However, the public wrapper of this tries to catch exceptions, and returns false if it catches one: https://github.com/owncloud/core/blob/cb0da1178b0872988582ee5fbf6b5b1cb5ea2527/lib/public/config.php#L145

So if you use the public method, you cannot determine if the call succeeded or not.

**Comment by MorrisJobke** [comment]
This is fixed in the new API https://github.com/owncloud/core/blob/master/lib/public/iconfig.php#L115

This doesn't return any boolean. It just runs fine or throws an exception. If a precondition is specified and nothing is updated it also throws an exception.
