### ISSUE TITLE
Modified time states "seconds" ago for files uploaded ten minutes ago in Web UI

### ISSUE THREAD

**Issue by gig13** [owncloud/core#10677]
**Expected behavior**
Upload files via the sync client and check the modified column and see it change from "seconds ago" to "minutes ago" after time passes and the Web UI page is refreshed.

**Actual behavior**
Even after waiting 10 minutes, the Web Interface still states "seconds" ago.

**Steps to reproduce**
1. Upload several files via the 1.6.2 Windows Sync client
2. Go to the Web Interface and check the modified time.

**Server configuration**
OC 7 daily build
Windows IIS
MS Sql Server

**Desktop configuration**
Windows 1.6.2 sync client
Windows 7 OS

Firefox browser 31.0

**Comment by PVince81** [comment]
@gig13 I guess the issue is still there in 7.0.5 ?

**Comment by gig13** [comment]
@PVince81 
I have not tested with IIS and desktop client 1.6 in a long time. Let's close this one.
