### ISSUE TITLE
"Local" mount icon is displayed as normal folder in files app

### ISSUE THREAD

**Issue by vgezer** [owncloud/core#10712]
In files app, when we have an external mount as type *Local*, it is displayed like this:

![image](https://cloud.githubusercontent.com/assets/231068/4083768/9c384112-2eff-11e4-955d-0460f9c40977.png)

However, in the *External storage* view it is displayed like this which is the normal behaviour:

![image](https://cloud.githubusercontent.com/assets/231068/4083769/a5bddc9c-2eff-11e4-96ce-916fec5d32bd.png)

**Comment by Xenopathic** [comment]
Fixed with #17501
