### ISSUE TITLE
Problems with IE 8+9: writing in the field is gone

### ISSUE THREAD

**Issue by Matthias1983** [owncloud/core#10729]
Hello OC Community,

I have read a lot of posts about problems with Internet Explorer 8 + 9, but I didn't find my topic.

In the "Personal" Area there is the "Password" field, to change the Password. You have to write your old password in the first, and your new password in the second filed. To understand this (because is is not intuitive), there is written in Gray "Current password" and "New password".

But with IE 8 the fields are empty and the User doesn't understand what to do? With IE 11 I have no problem. What is the problem, any idea?

IE is not my favourite browser, but there are a few important persons with have to use IE 8 ...

best regards,

Matthias

PS: With chrome and Firefox OC works perfekt!

**Comment by MorrisJobke** [comment]
Fix is in #15259
