### ISSUE TITLE
Encryption switch for external storages

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#10731]
Discussed this with @Xenopathic today.

Adding the switch shouldn't be too complicated as there is already internal code to disable encryption for specific storages.

The main issue is mostly about where to put it in the already overloaded Admin page UI.

One idea proposed by @Xenopathic was to have a cog icon in every one that shows a dropdown (like the share dropdown) with advanced options like "Disable encryption" and possibly others.

CC @owncloud/designers for the UI topic

**Comment by aaschmid** [comment]
It would also be nice if the external mount encryption could be separated from the users password to be able to use the "remember" feature :-)

**Comment by l3iggs** [comment]
+1 for a per-external-storage encryption switch

**Comment by ZacharyDuBois** [comment]
:( I was hoping to see all these encryption and external mount bugs fixed in 8.0.

**Comment by PVince81** [comment]
@ZacharyDuBois well... time and resources are limited. I was hoping too.

What bugs are you thinking of ?
The encryption bug with WebDAV/ownCloud mounts should be fixed already as per https://github.com/owncloud/core/issues/5952

**Comment by ZacharyDuBois** [comment]
@PVince81 Just in general as it seems that the encryption plugin itself needs a major overhaul since it has so many issues with other plugins.

**Comment by PVince81** [comment]
@icewind1991 are you still working on this ? (if yes please assign to yourself)

**Comment by karlitschek** [comment]
yes. this is actual important

**Comment by icewind1991** [comment]
Should be fixed with #15338

**Comment by PVince81** [comment]
Ah cool, I see the switch.
Will do some testing and raise separate tickets for bugs I find.

**Comment by PVince81** [comment]
So far it seems to work well.
Moving files between encrypted and non-encrypted don't work properly, but this is due to https://github.com/owncloud/core/issues/15619

The option properly disappears when encryption is disabled. Neat :smile:

**Comment by Croydon** [comment]
Desperately needed, thanks!
