### ISSUE TITLE
[OC 7.0.2] Renaming collective-folder for shares doesn't rename folder in "user/gallery/user/" on the server

### ISSUE THREAD

**Issue by deMattin** [owncloud/core#10747]
I collect the files shared by other user (foreign shares) in a special folder.
If I rename this folder, everything works as expected (renaming on server and client sync) but on the server in the folder for the gallery previews the folder remains with previous name.
If you view pictures in browser after that, there is a new folder created on the server in the owncloud data folder "user/gallery/user/" and every preview is newly generated.

I made the test to manual rename the folder in the gallery-folder on the server and the old previews then will be used.

So, i think, there's simply a fuction missing, that renames the gallery folder name if you rename the folder where you collect foreign shares.

### Steps to reproduce
1. create a folder i.e. "old-foldername"
2. move foreign shared files (pictures) or folder with pictures in there
3. view in browser with the picture/gallery app
3. rename the folder "old-foldername" to another name i.e. "new-foldername"
4. view the shares with in the browser with the picture/gallery app
5. on the server the owncloud data folder "user/gallery/user/old-foldername/" remains unchanged and a new folder "user/gallery/user/new-foldername/" will be created and now used for gallery previews
6. All previously generated previews in "user/gallery/user/old-foldername/" won't been used any more and are just waste of space.

### Expected behaviour
If you rename a (collecting) folder for shared files, the folder also has to be renamed in the gallery folder "user/gallery/user/" to reuse the previously generated previews.

### Actual behaviour
If you rename a folder with foreign shares in it:
- "user/gallery/user/old-foldername/" with remains unused
- "user/gallery/user/new-foldername/" is generated and used from now on

### Server configuration
**Operating system**:
Debian 7
**Web server:**
Apache 2
**Database:**
MySQL 5.0
**PHP version:**
 5.4.4
**ownCloud version:** (see ownCloud admin page)
7.0.2 (bug also seen on 7.0.1)
**Updated from an older ownCloud or fresh install:**
updated from 6.0.4 install and after that all official versions 7.0.x (opensuse repo)
**List of activated apps:**
default
+videoviewer
**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => '............',
  'passwordsalt' => '.........',
  'trusted_domains' => 
  array (
    0 => '192.168.192.210',
    1 => 'domain.tld',
  ),
  'datadirectory' => '/media/sf_Owncloud-Data',
  'dbtype' => 'mysql',
  'version' => '7.0.2.1',
  'dbname' => 'ocdb',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '......',
  'dbpassword' => '..................',
  'installed' => true,
  'forcessl' => true,
  "overwritehost" => "domain.tld",
  "overwriteprotocol" => "https",
  "overwritewebroot" => "owncloud",
  'trashbin_retention_obligation' => 180,
  'trashbin_auto_expire' => true,
  'loglevel' => '2',
  "remember_login_cookie_lifetime" => 60*60*24*30,
  'enable_previews' => true,
  'theme' => '',
  'maintenance' => false,
);
**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
(but had activated it before)
### Client configuration
**Browser:**
Google Chrome
**Operating system:**
Windows 7
#### Web server error log
nothing special
#### ownCloud log (data/owncloud.log)
nothing special
#### Browser log
nothing special

**Comment by PVince81** [comment]
or maybe @oparoz has an idea ?

**Comment by PVince81** [comment]
@deMattin are you still seeing this in 8.1.4 or 8.2 ?
Note that 8.2 comes with an improved gallery app. @oparoz

**Comment by PVince81** [comment]
Closing due to lack of feedback.
