### ISSUE TITLE
Videos recorded with iPhone don’t play in the web interface

### ISSUE THREAD

**Issue by autrui** [owncloud/core#10749]
**What I tried:**

Recorded a short *video on my iPhone (H.264, HD,* **.MOV** *)*, uploaded it to my OC (7.0.2) (with iOS OC app), shared the link.

**Result:**
Video won't play in any browser on Win or Mac.

**Comparison:**
Before I switched to OC I had a small web site (SSL, htaccess-protected, html5 video tag) where I would upload such videos from my iPhone while on the road without any PC.

That's how I know that videos recorded on the iPhone should play properly (out of the box = without any browser plugins) in 
- *IE10+*
- *Chrome 25+* 
- *Firefox 21+ (Win)*
- devices running *iOS 6+*.

They *won't* play (out of the box) in *Safari (Mac)* (sandboxing/htaccess problem) or *Firefox (Mac)* (codec problem). 
 
**My request/wish:**
if a small web site can make iPhone recorded videos available in a HTML5 video tag in those browsers mentioned above, OC should be able to do so too.
Request compatibility of OC built-in video viewer with iPhone recorded videos for IE10+, Chrome 25+, FF21+(Win) and iOS6+ (nevermind #8046, that's another story/bug).

Maybe it's as simple as adding a line like "AddType video/mp4 .MOV" to some htaccess file (*which one?*), maybe it's more difficult, I don't know. Thank you.

**Comment by nickvergessen** [comment]
You have to use app for that e.g. https://github.com/owncloud/apps/tree/master/files_videoviewer or https://github.com/owncloud/videos

**Comment by bs** [comment]
This is broken in the videoviewer app.
