### ISSUE TITLE
Failed to base64 decode

### ISSUE THREAD

**Issue by binarykitchen** [owncloud/core#10765]
After the update to 7.0.2 I see tons of these lines in the error log

```
Error 	PHP 	openssl_decrypt(): Failed to base64 decode the input at /var/www/owncloud/apps/files_encryption/lib/crypt.php#250 	2014-08-31T06:52:16+00:00
Error 	PHP 	openssl_decrypt(): Failed to base64 decode the input at /var/www/owncloud/apps/files_encryption/lib/crypt.php#250 	2014-08-31T06:52:16+00:00
Error 	PHP 	openssl_decrypt(): Failed to base64 decode the input at /var/www/owncloud/apps/files_encryption/lib/crypt.php#250 	2014-08-31T06:52:16+00:00 
```

Worrying. And the whole system is suddenly very slow. Any clues?

**Comment by MorrisJobke** [comment]
@schiesbn Do you mind to enhance the log output to provide better information?

**Comment by PVince81** [comment]
@binarykitchen are you still seeing this with 7.0.5 or 8.0.2 ?

Note that there were bugs that were fixed in 7.0.3 related to missing keys, which might or might not produce the messages you were seeing.

**Comment by binarykitchen** [comment]
Seeing these in 7.0.1

**Comment by karlitschek** [comment]
@binarykitchen Can you verify if it still exists in 7.0.5 or 8.0.2 ? 
We fixed some bugs as mentioned above

**Comment by binarykitchen** [comment]
I am unable to upgrade the version, see https://github.com/owncloud/core/issues/15204

**Comment by MorrisJobke** [comment]
@binarykitchen Any news? Did you manage to upgrade?

**Comment by binarykitchen** [comment]
yep all good now
