### ISSUE TITLE
MySQL: autocommit is required

### ISSUE THREAD

**Issue by fgusinde** [owncloud/core#10763]
Hi,

I have a MariaDB running with autocommit=0 (because of another application, so I can't change) and owncloud is not working because we're expecting autocommit is on. I think we should explicitely commit or rollback every transaction.

As a quick workaround I added

 358         $this->executeQuery('SET SESSION AUTOCOMMIT=1;', '');

to 

3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php

Regards, Florian

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 I have no way to test all supported databases to verify this fix, im not sure this is a good one for me.

Missed your comment - sorry - there are two solutions to the issue:
- install all databases locally
- at least test this on MySQL locally and let Jenkins do the rest for you

Anyway - someone else can take over this task

**Comment by DeepDiver1975** [comment]
> Btw I couldn't find any code that uses beginTransaction without commit() or rollback()

quite expected - what are you trying to tell us? :speak_no_evil:
