### ISSUE TITLE
Expire date is not shown when expire date is enforced

### ISSUE THREAD

**Issue by stp-ip** [owncloud/core#10784]
Prerequisite: Expire date is enforced.
Instead of having the ability to edit the date and throw an error instead just show the expire date instead and a message saying it's enforced.

Proposal: Disable editing alltogether.

**Comment by PVince81** [comment]
Already works in 8.2.0 with enforced expiration date, the date appears and there's a message underneath:
![expire-enforce](https://cloud.githubusercontent.com/assets/277525/10758713/64a929c0-7cb3-11e5-943b-c777304c9cc4.png)
