### ISSUE TITLE
Remember changes to sort order

### ISSUE THREAD

**Issue by Bugsbane** [owncloud/core#10788]
This is an enhancement request to improve the sort order of files and folders as per the suggestions of @jancborchardt and @onny in the issue at https://github.com/owncloud/core/issues/164 .

Specifically, this includes:

1. Change from the current default of having file/folder sort order be by name, to being by date, with most recent files listed at the top.

2. Remembering changes to the sort order by the user, so it's remembered when they come back to that folder later.

**Comment by oparoz** [comment]
I agree with @Bugsbane, Add a tick box, just like on Windows to let the user apply the changes globally if he wants to, but don't make that the default behaviour.

**Comment by MartinW2** [comment]
Sorry, i don't agree with the opinion of jancborchardt to close #13484.

1) If the user is not logged in, there is no reliable possibility to store his sort order preference. A main advantage of owncloud is the possibility to share links that do NOT need any login.

2) Especially first-time users or unexperienced users are happy to be presented with a view that already is sorted in reasonable order. Depending on the usecase, an admin can very well decide what is the preferred order. For any kind of collection, where items come in from time to time, it makes sense to have newest items first. I claim this is a main use case of owncloud for private use.

Both (1) and (2) are good reasons to allow the administrator to set a default order, at least to let it be sorted by upload date desc.
So, it's NOT THE SAME as allowing the user to sort himself (which is a nice feature of course, but does not meet the point here).
Please reopen request #13484 or include it in this request. Thank you.

**Comment by Bugsbane** [comment]
I would suggest that if the user is not logged in that yes, we can still remember sort order via a cookie and that showing a decent view to new users can be achieved by carefully chosen defaults rather than having admins of every pod go and manually set defaults for their users. Between reasonable defaults in ownCloud and users being able to change them with a single click via an interface paradigm most are used to from file managers, we have the overwhelming majority of use cases covered.

For the defaults, it seems to me that in *most* (not all, but *most*) cases, users generally want to be seeing their most recently modified files first.

**Comment by MorrisJobke** [comment]
@Bugsbane Full ACK

**Comment by jancborchardt** [comment]
@Bugsbane did I mention that I like you? ;)

@MartinW2 so yeah, basically what @Bugsbane wrote. This is a setting that should not be set by admins.

**Comment by Bugsbane** [comment]
@jancborchardt - Thanks! Gosh, now I feel guilty for repeatedly trying to load the 404 page for owncloud.org/jan-borchardt-is-evil.htm enough that it shows near the top of the site logs yesterday, to confuse the webmaster.

You may think I'm joking. You'd be wrong. I have a strange sense of humor.

Anyway, 90% of what I've learned about user interaction has been from reading your comments on various FOSS projects, so your compliment meaningful to me.

**Comment by jancborchardt** [comment]
@Bugsbane LOL

> Anyway, 90% of what I've learned about user interaction has been from reading your comments on various FOSS projects, so your compliment meaningful to me.

Thanks, right back at you! :)

**Comment by oparoz** [comment]
This feature request has been kind of implemented in Gallery+. The order is not saved when you use the buttons, but you can define defaults for folders and the settings can be inherited.

More information here:
https://github.com/interfasys/galleryplus/blob/master/documentation/Album%20configuration.md

**Comment by jancborchardt** [comment]
@oparoz this is about the files app though, and the sort order defined by the table headers.

**Comment by oparoz** [comment]
Indeed, but I'm just mentioning the way we do it in another app so that participants in this thread can test an alternative way of doing things to see if it would meet their the needs.

**Comment by MartinW2** [comment]
Thanks a lot, @oparoz . As #13484 has been closed, I am happy that someone see the needs of Admins that simply want to make life easier for their occasional or anonymous users by setting optional, reasonable defaults. Of course users should be empowered to dynamically or permanently override sort order as they want - but I don't see why this is in contradiction to admins that (optionally) want to provide their users with a reasonable starting point. It's not the same thing either.
I probably miss the abilities and UI experience of some owncloud power users to know users needs ...
So, thanks again for letting me know via this post.

**Comment by jancborchardt** [comment]
We should fix this for 8.2 – this is very annoying for people who prefer to have their files sorted by modification date as default.

**Comment by cmonteroluque** [comment]
@DeepDiver1975 looking for an assignment

**Comment by jancborchardt** [comment]
Would be a bummer, but I assume this can not be done for 8.2 and hence needs to be moved to 9.0? @DeepDiver1975?

**Comment by PVince81** [comment]
We're past feature freeze, moving to 9.1.

Has there been a consensus yet regarding where to store that setting and its scope ?
- JS variable: cleared on refresh
- cookie / localStorage: only in the current browser
- oc_preferences: kept across sessions for the same user

**Comment by oparoz** [comment]
The last option seems to be the best one and even though it's not part of a public API, it's still something that apps can use.

**Comment by Bugsbane** [comment]
Definitely the lady option. The other two provide an inconsistent experience for the user over time/devices.

**Comment by jancborchardt** [comment]
Yep, definitely the last one. All settings should be user-specific and remembered, not only browser- or session-specific.

**Comment by MartinW2** [comment]
I still would recommend to also allow the admin to set a default, which can
be overridden by the user's settings.
Anyway, i don't think my opinion is considered to be relevant here.
Best regards, Martin




2016-02-22 11:11 GMT+01:00 Jan-Christoph Borchardt <notifications@github.com

**Comment by jancborchardt** [comment]
Since we also talked about the »show recent files« during the 9.1 meetings, I would like to propose this for inclusion for 9.1 @cmonteroluque @MTRichards @PVince81

**Comment by cmonteroluque** [comment]
let's see if it can be done in the bug fixing phase
