### ISSUE TITLE
Confusing UI for pw enforced public link sharing (pw + enter needed to show complete dropdown)

### ISSUE THREAD

**Issue by stp-ip** [owncloud/core#10782]
It's confusing that you need to enter the pw and hit enter before anything else comes available. It is inconsistent with the usual UI in sharing.
With an enforced expiry date for example we don't require that to be entered first, but require it to be set at the end... (or at least you could lay it out like that).

~~To recreate:~~
  * ~~Enforce password protection on public links.~~
  * ~~Try to create a public link.~~

~~Result:~~
  * ~~It fails with an error that password protection would be needed, but doesn't actually let it be set.~~  

~~Expected behaviour:~~
  * ~~Show the password field as usual and add a notice to show that a password is needed.~~

**Comment by Xenopathic** [comment]
Please retry with oC 8.1.1
