### ISSUE TITLE
Add configuration option to exclude directories and files from file system scan

### ISSUE THREAD

**Issue by j-ed** [owncloud/core#10792]
## Expected behavior

It should be possible to exclude directories and files from being added to the cache during a file system scan. In a first step a general configuration option should be added to define excludes, in a second step it might be worse to define excludes based on a file, e.g. '.oc-scan-excludes', which can be stored in a directory which contains directories and files to be excluded.

## Actual behavior

All directories and files are scanned during a file system scan which also include e.g. unix hidden files which are starting with a dot, or Windows profile data, e.g. profile.V2/... (which might contain 10-100k files).

## Steps to reproduce

Check the debug output during a file system scan.

#### Server Configuration

OS: Linux 3.2.54
Web server: Apache2 2.4.10
Database: MySQL 5.1.73
PHP version: 5.4.26
ownCloud version: 7.0.2

#### Client Configuration

Browser: Firefox 31.0
Operating system: Windows 7

**Comment by PVince81** [comment]
Solved with https://github.com/owncloud/core/pull/19235.
This not only excludes from scan but also from being visible in the web UI and Webdav.

Because excluding from scan alone isn't enough anyway as the files would be found later at access time.
