### ISSUE TITLE
[6.0.5] German special character encoding database insert failed

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#10804]
### Steps to reproduce
1. Installed oC 6.0.2
2. Upgraded to oC 6.0.5

### Description
Due to German special character naming of folders and file names in our ownCloud system there could be a severe Bug perhaps since ownCloud version 6.0.2. Server was upgraded to 6.0.5

If a user try to click on an file name with special German characters or a file without a special character in its name but localized in an folder path with special German character a SQL Error rise up (see image). If the file-name with special German character it a text file, an error occurs and it opens normal in text editor. Other file formats e.g. xls, pdf etc. producing described error. Downloading the file is working normal. Perhaps a problem of code page. All major web browser showing this error.

### System specifications
ownCloud 6.0.5
Windows Server 2012
IIS 8
PHP 5.4.24
MySQL 5.5.34

### Database configuration:
SQL: show variables like "collation_database";
Result:
collation_database utf8_general_ci

SQL: SHOW FULL COLUMNS FROM owncloud.oc_file_map;
RESULT:
logic_path varchar(512) utf8_unicode_ci NO select,insert,update,references
logic_path_hash varchar(32) utf8_unicode_ci NO PRI select,insert,update,references
physic_path varchar(512) utf8_unicode_ci NO select,insert,update,references
physic_path_hash varchar(32) utf8_unicode_ci NO UNI select,insert,update,references

So the database is generally in UTF-8 collation.

### Log
```
{"reqId":"54044e70dbfd8","app":"index","message":"Doctrine\\DBAL\\DBALException: An exception occurred while executing 'INSERT INTO `oc_file_map` (`logic_path`, `physic_path`, `logic_path_hash`, `physic_path_hash`)\n\t\t\t\tVALUES (?, ?, ?, ?)':\n\nSQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\xDFnahme...' for column 'logic_path' at row 1","level":4,"time":"01-09-2014 12:46:08","method":"GET","url":null}
```
### Full Log:
S3-ownCloud\Shared\owncloud\support\github-issues\core\10804

**Comment by MorrisJobke** [comment]
> @DeepDiver1975 on phpBB we have a script that needs to be run, when someone upgrades their MySQL version from <= 4.0 to >= 4.1
> Has something like this happened here?

cc @cdamken @michaelstingl

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 on phpBB we have a script that needs to be run, when someone upgrades their MySQL version from <= 4.0 to >= 4.1
> Has something like this happened here?

we have nothing like this

**Comment by nickvergessen** [comment]
I know we don't, the question is where a mysql version update has been performed.

**Comment by DeepDiver1975** [comment]
> I know we don't, the question is where a mysql version update has been performed.

ah - I see - thanks for the clarification

**Comment by MorrisJobke** [comment]
> MySQL 5.5.34

5.5 is the current version. It's very unlikely that there was a upgrade between <=4.0 to 5.5

**Comment by MorrisJobke** [comment]
Where do I get a IIS server from? Or does anybody have one to test this? cc @DeepDiver1975 @jnfrmarks

**Comment by MorrisJobke** [comment]
> Where do I get a IIS server from? Or does anybody have one to test this? cc @DeepDiver1975 @jnfrmarks

Okay. This isn't an issue for @cdamken anymore. - removing blue label
