### ISSUE TITLE
Browser history and files app broken changing the directory in the url inside a view

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#10813]
### Steps to reproduce
1. Activate one of the files view (share or external storage, for example), and click in the view (left panel)
2. You must have a folder inside the view
3. The browser url should be something like: "index.php/apps/files/?dir=%2F&view=sharinglinks"
4. Change the "dir" param to the existing folder (if in the sharinglinks view you have a folder "fileserver", change the url to "index.php/apps/files/?dir=/fileserver&view=sharinglinks")

### Expected behaviour
Either the view changes to the normal one as if the user have clicked in the directory (and he can keep navigating normally), or he browse the contents of the folder in the same view. (Probably first option seems easier and keeps the same behaviour we're having under normal circumstances)

### Actual behaviour
Browser history keeps changing forever between views (as well as the page title) and the files don't get loaded. If you click in another view in this state, the files are loaded, but the browser history and page title keeps changing.

### Server configuration
**Operating system**: Ubuntu 12.04.5 LTS

**Web server:**  Apache/2.2.22

**Database:**  MySQL

**PHP version:**  PHP 5.3.10-1ubuntu3.13

**ownCloud version:**  {"installed":"true","version":"7.0.2.1","versionstring":"7.0.2","edition":""}

### Client configuration
**Browser:**  Firefox 31.0

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/20079
