### ISSUE TITLE
Difficulties to change the view in the files app in small screens

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#10815]
### Steps to reproduce
1. Activate one or more views in the files app (share or external storage)
2. Reduce the window height enough so the "deleted files" entry is overlapped with other entries

### Expected behaviour
All entries are easily clickable

### Actual behaviour
The "Deleted files" entry overlaps one or two entries, making those entries difficult to click

### Server configuration
**ownCloud version:**  {"installed":"true","version":"7.0.2.1","versionstring":"7.0.2","edition":""}

### Client configuration
**Browser:**  Firefox 31.0

![screenshot from 2014-09-02 10 07 50](https://cloud.githubusercontent.com/assets/1477829/4115868/f9c8dedc-327d-11e4-8d84-e9d3976d654c.png)

Note: This could also happen if there are too many entries.

**Comment by jancborchardt** [comment]
Fix at https://github.com/owncloud/core/pull/14970, please review @jvillafanez
