### ISSUE TITLE
LDAP Backend Can't disable certificate check before configuration

### ISSUE THREAD

**Issue by Grimeton** [owncloud/core#10825]
Hello,

when trying to configure the LDAP backend one can't click on the "advanced" tab in the upper right to disable the certificate check for LDAP connections BEFORE configuring the actual connection. It's disabled... 

Only workaround is to set TLS_REQCERT to "allow" in ldap.conf.

Cu

**Comment by blizzz** [comment]
WIP in https://github.com/owncloud/core/compare/fix-10825, moved to 8.1 as this is not a showstopper

**Comment by PVince81** [comment]
@blizzz what's the status ? PR ?

**Comment by blizzz** [comment]
Couldn't finish this one yet.

**Comment by PVince81** [comment]
please reopen if this is still happening in recent versions
