### ISSUE TITLE
Multiple instances per server testing

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#10839]
Owncloud is available in the catalogue of several apps managers designed for the hosting industry and it's great as it contributes to making the app more popular.
However, Owncloud is not a 100% compatible with that configuration where multiple instances are installed on just one server.

I think it would be great if some automated tests could be run on a cluster of instances installed on the same server, just before release.

**Comment by PVince81** [comment]
@oparoz are you still getting issues ?
It looks like only https://github.com/owncloud/documents/pull/353 is still often

**Comment by oparoz** [comment]
Is Smashbox loading several real instances in the same container or using separate containers? If it's the former and there are document tests, then the case described here is covered.

**Comment by MorrisJobke** [comment]
I'm running multiple instance on one server in different subdirectories and all works fine. 

@oparoz I will close this ticket here and would like to ask you to open a new issue if there is a more specific problem and error messages. Thanks

**Comment by oparoz** [comment]
As long as each instance is using its own namespace for caching, settings, etc. it should be fine. Problems arose when configurations from different instances all tried to use the same server resource.

**Comment by MorrisJobke** [comment]
> Problems arose when configurations from different instances all tried to use the same server resource.

Then there is not much we can do. When you configure different owncloud versions to use the same database table it will cause issues.

**Comment by oparoz** [comment]
Of course, but it was more ownCloud missing a namespace for sessions, using /tmp or saving libreoffice configs. This ended up sending the wrong sessions to users or locking the libreoffice config to a specific instance, making it unavailable to other instances, etc.

I think devs are more careful now that these problems have been highlighted, but not every case can be covered as this would require a configuration matrix to test and would take a long time to run.
