### ISSUE TITLE
LDAP/AD: Users primary group is not beeing used

### ISSUE THREAD

**Issue by Finkregh** [owncloud/core#10834]
### Steps to reproduce
Have two users in a LDAP/AD backend, one (user1) with a primary group A, one (user2) with a primary group B and also membership of group A

### Expected behaviour
user1 and user2 should be in the Owncloud-group A

### Actual behaviour
only user2 is member of the Owncloud-group A

### Server configuration
**Operating system**: Linux, Debian v7.6, 64 bit

**Web server:** nginx v1.6.1

**Database:** sqlite

**PHP version:** v5.4.32-1~dotdeb.1

**ownCloud version:** 7.0.2 (git) / a3dcbe5bcee2df9706213deae24b892ae235e363

**Updated from an older ownCloud or fresh install:** updated

**List of activated apps:** Deleted files v0.6.2, LDAP user and group backend v0.4.3, Share Files v0.5.3 (3rdparty at b958a1e609b6bd09dd0fa29943b48eb024a31b75)

**The content of config/config.php:** 

```
<?php
$CONFIG = array (
  'instanceid' => 'x',
  'passwordsalt' => 'x',
  'trusted_domains' =>
  array (
    0 => 'x.de',
    1 => '172.x',
    2 => 'x.de',
  ),
  'datadirectory' => '/var/www/htdocs/x/data',
  'dbtype' => 'sqlite3',
  'version' => '7.0.2.1',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'theme' => '',
  'overwritehost' => 'x.de',
  'overwriteprotocol' => 'https',
  'overwritecondaddr' => '^(172\\.x)$',
  'maintenance' => false,
  'default_language' => 'de',
  'knowledgebaseenabled' => false,
  'mail_domain' => 'x.de',
  'trashbin_retention_obligation' => 1,
  'trashbin_auto_expire' => true,
  'allow_user_to_change_display_name' => false,
  'enable_avatars' => false,
  'enable_previews' => false,
  'xframe_restriction' => true,
  'appstoreenabled' => false,
  'check_for_working_htaccess' => false,
  'log_rotate_size' => '5 MiB',
  'loglevel' => '0',
  'log_query' => '0',
  'share_folder' => '/Shared',
);
```

**LDAP config:**
```
sqlite> select * from oc_appconfig where appid='user_ldap';
user_ldap|installed_version|0.4.3
user_ldap|types|authentication
user_ldap|enabled|yes
user_ldap|ldap_host|y.y.de
user_ldap|ldap_port|389
user_ldap|ldap_backup_host|y.y.de
user_ldap|ldap_backup_port|
user_ldap|ldap_base|DC=y,DC=de
user_ldap|ldap_base_users|DC=y,DC=de
user_ldap|ldap_base_groups|DC=y,DC=de
user_ldap|ldap_dn|CN=admin,OU=y,OU=OE,DC=y,DC=de
user_ldap|ldap_agent_password|y
user_ldap|ldap_tls|0
user_ldap|ldap_nocase|0
user_ldap|ldap_turn_off_cert_check|0
user_ldap|ldap_display_name|displayname
user_ldap|ldap_userfilter_objectclass|organizationalPerson
user_ldap|ldap_userfilter_groups|
user_ldap|ldap_userlist_filter|(&(objectCategory=person)(objectClass=user))
user_ldap|ldap_user_filter_mode|1
user_ldap|ldap_group_filter|(&(|(objectclass=group)))
user_ldap|ldap_group_filter_mode|1
user_ldap|ldap_groupfilter_objectclass|group
user_ldap|ldap_groupfilter_groups|
user_ldap|ldap_group_display_name|cn
user_ldap|ldap_group_member_assoc_attribute|member
user_ldap|ldap_login_filter|(&(&(objectCategory=person)(objectClass=user))(|(sAMAccountName=%uid)))
user_ldap|ldap_login_filter_mode|1
user_ldap|ldap_loginfilter_email|0
user_ldap|ldap_loginfilter_username|0
user_ldap|ldap_loginfilter_attributes|sAMAccountName
user_ldap|ldap_quota_attr|
user_ldap|ldap_quota_def|
user_ldap|ldap_email_attr|
user_ldap|ldap_cache_ttl|600
user_ldap|ldap_override_main_server|0
user_ldap|ldap_configuration_active|1
user_ldap|ldap_attributes_for_user_search|
user_ldap|ldap_attributes_for_group_search|
user_ldap|home_folder_naming_rule|
user_ldap|has_memberof_filter_support|1
user_ldap|ldap_expert_username_attr|sAMAccountName
user_ldap|ldap_expert_uuid_user_attr|
user_ldap|ldap_expert_uuid_group_attr|
user_ldap|last_jpegPhoto_lookup|0
user_ldap|ocsid|166061
user_ldap|ldap_nested_groups|0
user_ldap|ldap_paging_size|500
```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

### Client configuration
**Browser:** Chrome 37

**Operating system:** Windows 8.1 / 64 bit

#### Web server error log
```
2014/09/03 09:36:26 [error] 22220#0: *487 rewrite or internal redirection cycle while internally redirecting to "/index.html", client: 172.x, server: x, request: "GET /y/core/js/jquery-1.10.0.min.map HTTP/1.1", host: "x.de"
```

#### Browser log
```
GET http://x.de/y/core/js/jquery-1.10.0.min.map 500 (Internal Server Error) 
```

Following #7052 : the php-module bcmath is enabled (`php -m|grep bcmath`)

**Comment by blizzz** [comment]
My, is this old. We had several fixes since then. @Finkregh is the issue still valid?

**Comment by Finkregh** [comment]
yep, but i did not run a test with a clean install, just had a look at an up2date installation with old data in it

**Comment by tomcat-sdb** [comment]
I can verify this behavior on a clean installation.  Is there any sort of work around for this?

**Comment by blizzz** [comment]
@tomcat-sdb which version?

**Comment by tomcat-sdb** [comment]
8.1 (downloaded today).

**Comment by tomcat-sdb** [comment]
As a aside note, it's anonymous access (no username / password specified for connection) in the setup GUI if that helps...

**Comment by blizzz** [comment]
@tomcat-sdb  That's supposed to work, actually. Can you set the log to log everything (admin page), then with an LDAP user go to the personal page and provide the log that has been created for that request? Thx!

**Comment by tomcat-sdb** [comment]
Checking the log, I think I found the issue.  It's looking for the attribute: "primarygroupid" to find the user's gid which isn't the correct attribute for our setup.  I don't see a way to specify what attribute to use for the user's gid...

**Comment by tomcat-sdb** [comment]
I'm poking around in the source, and I think line 256 in apps/user_ldap/group_ldap.php may be what I need:

$primaryGroupID = $this->getEntryGroupID($dn, 'primaryGroupID');

change:  'primaryGroupID' to 'gidnumber'

I'll make the quick change and see if it works.  As soon as I can test this, I'll report back.

**Comment by blizzz** [comment]
I was not aware that this can be customized. Well then… if this does not work straight ahead, I'd need to rework primary group stuff anyway *sigh*. Looking forward to your results and thanks for digging into it!

**Comment by tomcat-sdb** [comment]
I don't think is a customized thing so much as different flavors of LDAP having slightly different attribute names, AD being it's own beast at times (grumbles...)  My first go failed, but it might have been due to a careless mistake (attribute is gidNumber, not gidnumber).  My test user is on the phone at the moment, so I need to wait until he's free (as my own ldap account doesn't have the issue).,,

**Comment by tomcat-sdb** [comment]
It's also used on line 283, so changing there as well w/ proper caps...  Still waiting for user to test...

**Comment by tomcat-sdb** [comment]
No luck... so much for a quick fix.  I'll keep working at it and see if I can get ti to behave.

**Comment by tomcat-sdb** [comment]
@blizzz 
I'll hack away at this over the weekend, now it's got me miffed :)  

Quick question for you since I'm not an ldap guru.  Is the primaryGroupID field of the user normally set to the uuid of the group?  If so, then that's probably the problem.  The gidNumber is the numeric groupID, rather than the gorup's ldap uuid.  I'll see if I can't get something in place and have it tested on Monday, since it looks like there's only about three places the attribute is used. 

Thanks for the quick support.  Have a great weekend.

**Comment by blizzz** [comment]
@tomcat-sdb doh, I overread that you are using 389 is LDAP server. Yes, primary group support is here only for AD, at the moment. Because it works different then everywhere else *sigh*. They have some overhead magic that is quite annoying.

IIRC, for 389 and other LDAP flavours you should be good to read gidNumber and look up that group. No further roundtrips.

You can safely ignore cases when requesting attributes.

> Quick question for you since I'm not an ldap guru. Is the primaryGroupID field of the user normally set to the uuid of the group? If so, then that's probably the problem. The gidNumber is the numeric groupID, rather than the gorup's ldap uuid.

No, to  it's objectsid, and there is something in binary stored in between.

Expect that primaryGroupID is specific to AD. Probably it's best to make getUserPrimaryGroup() and subsequent methods work with primaryGroupID and gidNumber, i.e. check for both attributes (possible that also both are existing). At some point you probably need to check what is available and go a shortcut with gidNumber.

>  I'll hack away at this over the weekend, now it's got me miffed :) 

Awesome!! :)

**Comment by PVince81** [comment]
@tomcat-sdb @blizzz any update ?

**Comment by cmonteroluque** [comment]
@tomcat-sdb can you provide an update?

**Comment by blizzz** [comment]
OC 7 gets only security fixes anymore.
We need to verify OC 8, however master should work with https://github.com/owncloud/core/pull/19635 which needs to get backported to 8.1 as well. Although, that was a regression, primary groups should have worked before.

Please reopen if there are still issues (against AD).
