### ISSUE TITLE
HHVM compliance

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#10837]
requires:
- [x] upgrade doctrine/dbal to 2.5 https://github.com/owncloud/core/pull/11689

**Comment by DeepDiver1975** [comment]
moving to 8.1 - still some paths to walk ....

**Comment by LukasReschke** [comment]
http://hhvm.h4cc.de/ might also be handy – saw that mentioned in IRC today.

**Comment by LukasReschke** [comment]
Current state: 
![composer-graph](https://cloud.githubusercontent.com/assets/878997/5939148/995ec234-a701-11e4-995c-45e3ed9b4362.png)

Green = Tested
Yellow = Tested, fails are allowed
Red = Not tested
Grey = Unknown

**Comment by bantu** [comment]
@DeepDiver1975 server-master-linux-hhvm CI broke. https://ci.owncloud.org/job/server-master-linux-hhvm/database=sqlite,label=master/837/console Any idea/hints?

**Comment by LukasReschke** [comment]
Yes... HHVM doesn't like the checkServer ini-checks in util.php

I'd say we should disable these checks on HHVM for now?

**Comment by DeepDiver1975** [comment]
> I'd say we should disable these checks on HHVM for now?

agreed! THX

**Comment by LukasReschke** [comment]
Will do.

**Comment by LukasReschke** [comment]
https://github.com/owncloud/core/pull/14605

**Comment by castarco** [comment]
What can be done to improve Owncloud on HHVM by a new programmer that don't know the codebase?

I'm trying to execute OwnCloud on HHVM in my server, but I'm having many problems and I want to contribute to fix them.

**Comment by Xenopathic** [comment]
@castarco We'd appreciate any bug reports for issues you may have with HHVM, along with full logs and server information (see https://github.com/owncloud/core/blob/master/CONTRIBUTING.md for more details). Not many of us run HHVM setups, and AFAIK we don't test it as part of continuous integration, so HHVM bugs usually go unnoticed. If you could test out the code from master on your setups (on a throwaway database, of course) we'd be very grateful!

**Comment by cortopy** [comment]
What sort of logs would be required? Happy to help although I don't know what's necessary

I've just been trying to set up Owncloud to work with HHVM but I've been unsuccessful. The only page that would show is /owncloud/index.php Any other variation or even a direct link to account gives a 404 file not found message 

The "interesting" part is that the log shows that it's not been possible to connect to SQL database. Changing nginx config back to PHP5 sorts the issue but obviously no HHVM

**Comment by castarco** [comment]
The 404 error is due to a recent bug appeared in the HHVM 3.6 version. In
the 3.5 version is possible to use it (only for basix features).
El dia 23/03/2015 4:32, "cortopy" <notifications@github.com> va escriure:

**Comment by PVince81** [comment]
@DeepDiver1975 @bantu any update ?

**Comment by DeepDiver1975** [comment]
9.0 topic - we are not yet there - in addition I question if this is still a higher priority give the fact that php7 will be released soon

**Comment by Spacefish** [comment]
I would still see HHVM support as a benefit compared to PHP7, the mean CPU load generated by HHVM is ~50% lower than with PHP7. They both deliver great response times, but the CPU load is a lot less with HHVM.

**Comment by DeepDiver1975** [comment]
I'm moving this to the backlog - this really requires some more work power to put into. Anybody is welcome to take care of this. Feel free to get in touch with me anytime.

**Comment by COLABORATI** [comment]
hhvm support is absolutely needed for good speed, would be very important to get this done. thanks!

**Comment by LukasReschke** [comment]
@COLABORATI Contributions welcome. Otherwise your comment won't change anything. :wink:

**Comment by Xenopathic** [comment]
Migrated from #23596:

HHVM seems to not properly handle casting objects to arrays to access object properties, breaking this code: https://github.com/owncloud/core/blob/master/lib/private/security/csp/contentsecuritypolicymanager.php#L60

**Comment by hodyroff** [comment]
With PHP7 we don't need this anymore, or?

**Comment by DeepDiver1975** [comment]
I'm closing this - HHVM is out of scope for us at the moment
