### ISSUE TITLE
notification emails provide internal IP adresses in some links (picture / file) instead of their public domain name 

### ISSUE THREAD

**Issue by finius** [owncloud/core#10838]
We are operating an ownCloud 7.0.1 server with an internal IP adress 10.0.0.30 behind a reverse proxy on which the server is published with an public domain name.

When sharing a file with another user, the email the user gets, always contains the link to the file "logo-mail.gif" which refers to the internal ip adress of the ownCloud server, instead of its public domain name.

Further, when sharing a file, the link to the file itself also contains the internal ip adress of the ownCloud server, when sharing this file by using the autocomplete function (when using registered owncloud users).
 Just when the file is shared by a manually entered email adress, the correct public domain name is used in the link of the notification email. 

### Steps to reproduce
1. configure ownCloud to use SMTP
2. publish and access ownCloud using a reverse proxy (i.e. Microsoft TMG 2010 Firewall)
3. share a link with someone, using a manually entered emailadress in comparision of sharing a link with a user from the ownCloud user list (by using the autocomplete field of registered ownCloud users)

### Expected behaviour
All URLs in the notification mail should contain the external/public domain (cloud.our-company.net) name for all links (logos and the link to the shared itself), based on the given reverse-proxy configuration in the config.php

### Actual behaviour
Just when using a manually entered emailadress when sharing a file with someone, the recieved notification mail contains the public/external URL to the shared file. When sharing a file using the predefined ownCloud user from the autocomplete field, the notification mail contains just a link to the shared file based on the private ownCloud servers IP-adress (in our case 10.0.0.30)
However, the URL to the source referring to the "logo-mail.gif" image contains in any case just the servers private IP-adress, instead of the external/public dns domain name. 

### Server configuration
**Operating system**: Ubuntu 12.04.4  LTS
**Web server: Apache 2 (Ubuntu 12.04.4 LTS)
**Database: MySQL (Ubuntu 12.04.4 LTS)
**PHP version: (Ubuntu 12.04.4 LTS)
**ownCloud version: 7.0.1
**Updated from an older ownCloud or fresh install: 5.0.17 --> 6.0.4 --> 7.0.1
**List of activated apps: Files, Documents
**Are you using external storage, if yes which one:  -
**Are you using encryption: 
http: ownCloud <--> TMG 2010
https: TMG2010 <--> Internet-Client

### Client configuration
**Browser: Internet Explorer 11
**Operating system: Windows 7 Enterprise, x64

**Comment by MorrisJobke** [comment]
@finius I opened a ticket for your new issue: #13206

I will close then, as it is solved
