### ISSUE TITLE
OC 7.0.* Optimierung | CCS > Validate 

### ISSUE THREAD

**Issue by WolfOnTour** [owncloud/core#10852]
Main error is the use of multiple ID's which actually should be used class. '<' Div id = "controls" '>' will happen to '<' div class = "controls" '>' To my knowledge, should each page only once an ID.

<a href="http://www.xup.to/dl,69630409/Clipboard04.jpg/" target="_blank"><img src="http://www1.xup.to/exec/ximg.php?fid=69630409" border="0"></a>

**Comment by Xenopathic** [comment]
Please open issue reports on the relevant apps as necessary.
