### ISSUE TITLE
OC 7.0.* Optimierung | HTML > VALIDATE 

### ISSUE THREAD

**Issue by WolfOnTour** [owncloud/core#10851]
1. The home page (/ownclod/index.php) is not Valid HTML there are about six errors
2. Missing alt tag for example '<' Img class = "float-spinner" src = "/ ownCloud / core / img / loading-dark.gif" / '>' 4.After the application is the "page file" this has around 57 HTML errors

<a href="http://www.xup.to/dl,29872774/Clipboard02.jpg/" target="_blank"><img src="http://www1.xup.to/exec/ximg.php?fid=29872774" border="0"></a>

**Comment by Xenopathic** [comment]
Please open bug reports on the relevant apps.
