### ISSUE TITLE
[LDAP] On the admin configuration panel, lost the focus on the non-active tabs

### ISSUE THREAD

**Issue by rperezb** [owncloud/core#10864]
On the LDAP configuration panel, there are different tabs, on the server one there is a button to "delete". Although you are not on that tab but other one, it could happen that the focus is on the delete button so that if you click enter the delete action is launched.

In order to avoid this, it would be good to loose the focus on any button once you are not on the tab where that button is set so that the action is not launched without your knowledge.

cc / @MTRichards

**Comment by blizzz** [comment]
@fernandoruiz @rperezb sorry, I cannot reproduce the behaviour. My steps were as following:

1. Go to Admin settings, LDAP
2. Go to Login Filter tab (using mouse clicks)
3. Click into Raw Filter Textinput and press Enter.

No delete action was triggered. Neither in current stable7 nor in master.

**Comment by PVince81** [comment]
Wow this is old. I already fixed the focus issue here: https://github.com/owncloud/core/pull/11480

**Comment by blizzz** [comment]
I did not remember this anymore :D thx @PVince81
