### ISSUE TITLE
[Hook] - add new/better hooks about apps' lifecycle - events: enable / disable / update / migrate

### ISSUE THREAD

**Issue by pf18387** [owncloud/core#10879]
I must feed a database table on install and / or to check its content when updating (migrate).

*Could a hook feature do the trick or is there something else?*

**Comment by MorrisJobke** [comment]
@PVince81 Can you create those tickets? Thanks

**Comment by DeepDiver1975** [comment]
Starting with 9.1 we have repair steps which can be defined in info.xml to be executed either before the database migration, after the migration or after the whole upgrade mechanism being executed in a background job.

This should fit the needs of this ticket.

**Comment by bne86** [comment]
I came to the same requirement (need to execute code on app enable). Is there a place where this workaround using info.xml is documented? Can't find it at a first glance in the [docs](https://doc.owncloud.org/server/9.1/developer_manual/app/info.html)
