### ISSUE TITLE
InternalServer Error on desktop client & various error in backend.

### ISSUE THREAD

**Issue by dacoex** [owncloud/core#10872]
We are running 7.0.2

I am using the respective clients on Linux & Windows to synch a directory of text files generated between the server and 2 computers.

On one client I always get the followin errors:
"Error downloading FILENAME.txt - server replied: Internal Server Error"
on other files it says:
"Error downloading FILENAME.txt - An If-Match header was specified, but none of the specified the ETags matched."

What could be the couse for this?

**Comment by MorrisJobke** [comment]
@PVince81 Ping

**Comment by PVince81** [comment]
@guruz @ogoffart does this syncing issue ring any bells ?

@dacoex have you tried upgrading to 7.0.5 or 8.0.2 and see if the issue persists ?
I see you're using encryption and there were several bugs related to it that were fixed since 7.0.2.

**Comment by dacoex** [comment]
>I see you're using encryption and there were several bugs related to it that were fixed since 7.0.2.
We disabled encryption. Now it looks like it's fixed.
I just got quite some conflicts after decryption so I will have to remove those leftovers.
