### ISSUE TITLE
overwriting object via webdav from ios seems to have problems

### ISSUE THREAD

**Issue by thetrial** [owncloud/core#10898]
This seems to be an issue that was introduced with v7. I can’t remember to have seen that with v6.

Given is a user, a synced folder, two syncing mac machines, a third not syncing mac machine with cyberduck to view/manipulate via webdav, and an ios device.

There are (e. g.) docx files in this folder in owncloud (hosted at home, own server, lan, not wan). On the ios device a file abc.docx is written (or let‘s say evolving). abc.docx is in owncloud, too, but in an older version. The ios device (better: the program »pages«) shall upload the new abc.docx. It tries … and fails! After this failure – and this is important and interesting – two things happen: the ios device forgets its whole login credentials (maybe not an owncloud issue, I don’t know yet) and: abc.docx on the owncloud (server) is lost! So it’s not overwritten but deleted.

This should not happen. With v6 there was never a problem in overwriting an existing document. Now, with v7 (7.0.2, too) this happens on and on.

Maybe something with encryption? OC server-side encryption is on. Shall I switch it off? Although encryption would be a nice thing. OC is on a raspbian raspi.

**Comment by MorrisJobke** [comment]
@thetrial Can you provide the requested information? Thanks

**Comment by thetrial** [comment]
Sorry, sorry folks. No, at the moment I have two concurring problems, first: no time and second: the Raspi including OC had recently failed. I just restore the system to a new card. But the first test run showed the same problem. So, when I find time, I’ll try to look for the logs. Maybe you can tell me where I should look exactly for?

Maybe one clue: If something like that happens often or every time (I don’t know at the moment becaus this does happen to several users here, not only me) the file is left there with 0 bytes (in owncloud). But, as mentioned, I don’t know if that happens always or sometimes. As I’ve stated before that files are »gone« (in my first post). I do not exactly remember the setting. But the last weeks I very often (!) had the problem with Syncs claiming »could not blah because e-tag« or something like that. I don’t know if this has to do with that.

Sorry for my chaos ;-)

**Comment by PVince81** [comment]
@thetrial did you manage to rebuild your Rpi ? Are you still seeing the issue with 7.0.5 or 8.0.2 with Cyberduck ?

**Comment by thetrial** [comment]
@PVince81 I’ve just tested all possibilities. And it seems, that everything works fine for now. Tested with iOS 7, Cyberduck 4.5.2 (Mac) and OC 8.0.2. Looks good! Have you changed something with these e-tags, encryption and (sqlite) db?

**Comment by PVince81** [comment]
A lot has been fixed since 7.0.2, especially encryption. Glad to hear it works :smile:
