### ISSUE TITLE
Config.sample.php - SWIFT - How does encryption work?

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#10900]
In Config.sample.php, there is info about SWIFT and how to make it work.

But this part is really confusing:

>WARNING: The current implementation is incompatible with any app that uses direct file IO and circumvents our virtual filesystem. That includes Encryption and Gallery. Gallery will store thumbnails directly in the filesystem and encryption will cause severe overhead because key files need to be fetched in addition to any requested file.

Where are the keys stored? In the object store? Are the incompatible, or is performance terrible?

**Comment by carlaschroder** [comment]
added to release notes.

**Comment by Xenopathic** [comment]
Looks like we've done what we reasonably can do
