### ISSUE TITLE
Cannot select WebDAV / CalDAV inputs on mobile

### ISSUE THREAD

**Issue by mikew** [owncloud/core#10907]
### Steps to reproduce
1. Visit cloud.example.org on your phone
2. Try selecting the WebDAV input

### Expected behaviour
The input should get focused, allowing for the user to copy the contents.

### Actual behaviour
Nothing.

**ownCloud version:** 7.0.2 (git)

---

My guess is the input has the "disabled" attribute set but what you probably want is "$input.on('keypress', function (event) { event.preventDefault(); }"

**Comment by PVince81** [comment]
@mikew do you still intend to have a look at fixing it ? It's fine if you don't, just let us know :smile:

**Comment by mikew** [comment]
Apologies, I did look into the source but unfortunately do not have the time to tackle this.
