### ISSUE TITLE
Better text explaning app update instead of ownCloud update

### ISSUE THREAD

**Issue by LEDfan** [owncloud/core#10909]
Refs ttps://github.com/owncloud/core/pull/9866

When the user tries to update an app (e.g. the Chat app) and there is some code in update.php, the user is prompted with the following screen:
![update-start](https://cloud.githubusercontent.com/assets/2996275/4174644/f6892222-359d-11e4-9ba6-ae1580ee744d.png)
This inform the user ownCloud needs an update, however it's an app which needs to be updated. When clicking the button, the update progress start, and the user is informed the app is updated.

Some users of the Chat app cancelled the update, because they think ownCloud was trying to reupdate ownCloud to 7.0.2. Refs https://github.com/owncloud/chat/issues/132

IMO it should be made clear to the user what is updated (owncloud, app etc).

**Comment by Xenopathic** [comment]
Closing in favour of #14977
