### ISSUE TITLE
Support for search by full name in users page (local backend)

### ISSUE THREAD

**Issue by ser72** [owncloud/core#10905]
**Steps**
1) Create several users in group "test group"
![all users](https://cloud.githubusercontent.com/assets/5174383/4170295/ebe4e666-3530-11e4-8d99-64099cfca874.PNG)

2) Change one user's FULL NAME to a name

![test group](https://cloud.githubusercontent.com/assets/5174383/4170297/eead6fe4-3530-11e4-8a89-527774f59e81.PNG)

3) In the TEST GROUP filter, search for the FULL NAME and notice nothing appears (BROKEN)

![test group search](https://cloud.githubusercontent.com/assets/5174383/4170306/01448a66-3531-11e4-9cb4-8f968005e70b.PNG)

4) Navigate to ALL USERS and notice the user list shows the results of the search in step 3

![all users search](https://cloud.githubusercontent.com/assets/5174383/4170318/1e37de20-3531-11e4-8a7e-8124bf0fd6bd.PNG)

**Comment by PVince81** [comment]
Search on full name doesn't work at all, even when the user is not in a group.

Observed on 8.2RC1

**Comment by DeepDiver1975** [comment]
Given the user backend interfaces it is not possible to search for username AND displayname the same time. Running the search twice is a nightmare from a perf pov.

I vote to mark this as an enhancement or even close.

@PVince81

**Comment by PVince81** [comment]
Yeah, I was also wondering about that. Will rename.
