### ISSUE TITLE
Passwords do not have minimum level of security

### ISSUE THREAD

**Issue by gerald626** [owncloud/core#10901]
### Steps to reproduce
1. Create new user with 1 character password
2. Login with said account
3. Profit???
### Expected behaviour

Admins should be able to set the minimum password security requirements (max/min characters, upper/lower case, special characters, etc...
### Actual behaviour

Passwords of 1 character are allowed.
### Server configuration

**Operating system**:
Linux SERVER 3.13.0-35-generic #62-Ubuntu SMP Fri Aug 15 01:58:42 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Web server:**
Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.3 OpenSSL/1.0.1f

**Database:**
mysql  Ver 14.14 Distrib 5.5.38, for debian-linux-gnu (x86_64) using readline 6.3

**PHP version:**
PHP/5.5.9-1ubuntu4.3

**ownCloud version:** (see ownCloud admin page)
ownCloud 6.0.1+dfsg-1ubuntu1 (Debian) (stable)

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'datadirectory' => '/var/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '6.0.0.16',
  'appstoreenabled' => false,
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/usr/share/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
  ),
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'maxZipInputSize' => 838860800,
  'allowZipDownload' => true,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
Yes
### Client configuration

**Browser:**
Chrome 37.0.2062.103 m
**Operating system:**
Windows 7 64-bit
#### Web server error log

```
Not applicable
```
#### ownCloud log (data/owncloud.log)

```
Not applicable
```
#### Browser log

```
Not applicable
```

**Comment by h-2** [comment]
:+1: this is really necessary!

**Comment by sbelov1** [comment]
@bboule @craigpg We have a large prospect asking for this as a hard requirement. 
@MTRichards do we have this on the roadmap.

PS Opening FT for this in SFDC.

**Comment by MTRichards** [comment]
Which part is missing this - server? Or sharing link?

**Comment by sbelov1** [comment]
@MTRichards Sharing via link. They're using AD for user auth.

**Comment by MTRichards** [comment]
It is in consideration for 8.1. 

What password options do they want for strength? Trying to get to minimum viable product here. Upper, lower, special character, number, min length?

How do they want to set these options?

Or is something simple like min length alone enough?

**Comment by sbelov1** [comment]
@MTRichards checking with the prospect...

**Comment by MTRichards** [comment]
Thanks!  Feature research.

**Comment by CaptionF** [comment]
@MTRichards @bboule 
very large prospect has the same requirement:
as an example, they provided a screen shot of a simple configuration for public link passwords

![link-pwd-policy](https://cloud.githubusercontent.com/assets/10551219/8250065/9e18d740-1670-11e5-9ff6-7383da621645.jpg)

**Comment by DeepDiver1975** [comment]
> as an example, they provided a screen shot of a simple configuration for public link passwords

simple? LOL @jancborchardt will love this "easyness"

**Comment by jancborchardt** [comment]
Yeah, sorry but ridiculous password requirements are the most annoying UX on the internet.

At most this can be done as a separate app which will definitely _not_ be shipped by default.

**Comment by bboule** [comment]
Hey guys it sounds like we have a few large potential users that are asking for this, and it sounds like we are not inclined do do this in the product?  Am I reading this correctly, this would need to be developed as a separate app @craigpg do you see this as a potential consulting engagement.  I guess my point here is the requirement is not going to change just want to figure out how to get there?

**Comment by MTRichards** [comment]
This is on the list for ownCloud 8.2. The screenshot above is simply to outline the options that need to be covered. 

@bboule @CaptionF As discussed on the List.
@cmonteroluque for your reference.
@jancborchardt is there an option that gets us close you would consider "visually appealing"?
Can't have confidential data hanging out there with a password of "l".

**Comment by DeepDiver1975** [comment]
We basically can add a feature in core allowing some kind of callback which allows any other code to verify the password. Some super fancy UI to specify password restriction can be implemented as an isolated app.

**Comment by jancborchardt** [comment]
I mean – the example screenshot above already is quite close to how visually appealing you can make such an interface.

The thing I meant here is that from a high-level standpoint that this should be a separate app for sure, not in core by default. (As Thomas just said seconds above.)

**Comment by MTRichards** [comment]
I like that. Gives us what we need without cluttering the interface unnecessarily.

@DeepDiver1975 What would it take to do what you said there, to create the ability to do this?

**Comment by bboule** [comment]
@sbelov1 @CaptionF does the 8.2 timeframe create an issue?  How does this impact the Opps?

**Comment by sbelov1** [comment]
@bboule It doesn't impact us any longer as we've lost the prospect.

**Comment by CaptionF** [comment]
This is critical to their going live date and with that to deal closing time!
need to be included earlier!
Matthias 
Please excuse typos as this mail was created on smart device

**Comment by h-2** [comment]
Guys, who cares about fine-tuning, just include a slider for **minimum password strength 0-5** and then make up your own rules for the steps. At least there would be some mechanism...

**Comment by bboule** [comment]
@cmonteroluque @MTRichards Please see CaptionF comment perhaps we can discuss alternatives to 8.2 as this seems to be critical? Perhaps we can discuss offline?

**Comment by atroxix** [comment]
Something related to this is implemented in 8.2 Enterprise now (Password Policy)?

**Comment by bboule** [comment]
@cmonteroluque @MTRichards This seems to be in the backlog with no one assigned @CaptionF is this no longer critical?

**Comment by MTRichards** [comment]
For transparency sake, the intent from our side is to point admins to a true authentication mechanism, such as a directory, when enforcing password complexity. Things like strength of the password itself, as well as failed login attempt lockouts and so forth are intended to be provided by a solution that specializes in providing these sorts of services.

**Comment by cmonteroluque** [comment]
Agree with @MTRichards

**Comment by PVince81** [comment]
@rullzer pointed out that this might already be covered by the password policy app ? Or is it missing something ?

**Comment by PVince81** [comment]
Ok, just remembered that the password policy app is only for link share passwords. It doesn't affect user entered passwords.

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/issues/10901 which is a similar topic

**Comment by Pazu** [comment]
@PVince81, isn't _this_ #10901?

**Comment by PVince81** [comment]
Something went wrong with my clipboard and I pasted the wrong number.
Just went through the searches again and couldn't find the other one. I think it was something about generating passwords or so.

Anyway, thanks for pointing out, reopening.

**Comment by robarchibald** [comment]
Dovecot does password policy enforcement through an external API call. There are a lot of benefits to doing it this way including the fact that ownCloud doesn't have to design or implement the myriads of different password policies that every different enterprise could want. If ownCloud were to simply support an API call, there could be a truly SIMPLE configuration UI to point to an API server with a few parameters. Much easier! I vote for something truly "simple" like this. https://wiki2.dovecot.org/Authentication/Policy. 

With this in place the authentication policy service could:
1) Block any attempt to enter in a password that doesn't meet the administrator's defined complexity rules. Administrators could define whatever schemes they want in their API.
2) Block due to a locked account that has exceeded the number of failed password attempts or any other administrator-defined reasons. This can include accounts that are locked for services other than ownCloud.
3) Block an IP address that is brute-force trying multiple accounts

**Comment by karakayasemi** [comment]
We have app for this purpose: https://github.com/owncloud/security, I guess we can close this.
