### ISSUE TITLE
Background Jobs Sometimes Don't check if app is enabled

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#10908]
openSUSE
MySQL
Apache

It seems that if you register an app with the database, and enabled it but didn't configure it - and then disable it, some background jobs still run, even if the app is no longer enabled.

For example, Enable LDAP. Then Disable it, upgrade through the 6.0.x line. It seems that this appears in the background jobs for some reason.

In the log 
> {"reqId":"5409af4e48a03","app":"user_ldap","message":"bgJ
\"updateGroups\" \u2013 groups do not seem to be configured properly, aborting.","level":1,"time":"2014-09-05T12:40:46+00:00","method":"GET","url"
:"\/owncloud\/cron.php"}

How can this be with the app disabled?

Whilenot verified, probably it is the background job which is triggered in core and does not check whether the app is enabled. The kicked off job will need to do it itself. I did not verify it yet, but it seems most likely.

Quick workaround: remove the background job from oc_jobs in the database (col class = ' OCA\user_ldap\lib\Jobs').

@blizzz

**Comment by PVince81** [comment]
@icewind1991 didn't you fix this already ?

**Comment by icewind1991** [comment]
I believe this is fixed yes

**Comment by MorrisJobke** [comment]
I just tested this -> fixed since 7.0 https://github.com/owncloud/core/commit/437094bbfc4230ed4b8b8cc797738ddd4ef7f1aa
