### ISSUE TITLE
Mounted FTP-Server shows files not correctly

### ISSUE THREAD

**Issue by stefan-niedermann** [owncloud/core#10916]
OC 7.0.2
Steps to reproduce:
1. Set up OC
2. Mount a FTP-Server into your OC instance
3. Access the FTP-Server via FTP
4. Create a test.txt-File on your FTP-Server via FTP
5. Reload OC
Current behaviour: OC did not recognize that FTP-Folder-Content changed and still shows me the message "All empty here - load up new files!"
Expected behaviour: After Pressing F5, OC should show me the created test.txt file

Possible cause: Caching?

**Comment by MorrisJobke** [comment]
Duplicate of #11797
