### ISSUE TITLE
Renamed the casing on a folder, after move Owncloud Client Delets Original

### ISSUE THREAD

**Issue by britai** [owncloud/core#10914]
Scenario
Windows 7
OwnCloud client 1.6
Had a folder called "Non-fiction, misc"
Renamed to "Non-fiction, Misc" (capitalized the first letter of Misc)
OwnCloud moved everything to "Non-fiction, Misc"
OwnCloud then deletes "Non-fiction, misc"

Seems to be an issue with the delete not being casing aware when there is a long name or a name with a comma in it. This is a problem.

**Comment by MorrisJobke** [comment]
@britai Did an upgrade to ownCloud 7 fix the issue for you?

@PVince81 Looks like the MySQL collation issue, right?

**Comment by britai** [comment]
@MorrisJobke @PVince81 I can't reproduce the issue now (post 7) with a new folder, however I did with the old folder that I saw this with once post upgrade (non fiction, misc.) Is it possible that the file names got left in the DB in the old format?

I could try moving the folder out of the sync directory, letting it purge on all clients and re-adding it.

**Comment by MorrisJobke** [comment]
@britai 

> Note: when upgrading to OC 7 it will automatically fix this in the database if the collation is not `utf8-bin`

I guess this is fixed then if you upgrade to ownCloud 7. You did the upgrade if I understand your comment correct. Can you verify this? Then I will close this issue as it is fixed.

**Comment by britai** [comment]
@MorrisJobke Yes, I saw that note about fixing it in the database. I'm 99% certain that I reproduced it after upgrading to 7 with the original folder I saw the issue with - I changed the case, it got moved then deleted and I had to restore it from the "bin".

 However I can't reproduce it now, and that doesn't do you much good. I also don't have a snapshot backup of the database from then so I can't help with that.

 I'd say this is safe to close. Thanks for taking the time to respond.

**Comment by MorrisJobke** [comment]
@britai Thanks for the response. No problem :)
