### ISSUE TITLE
Why OwnCloud chooses to cp files when moving to trash?

### ISSUE THREAD

**Issue by ceremcem** [owncloud/core#10915]
Hi,

Is there a good reason for copying files from owncloud/data/{user}/files to owncloud/data/{user}/files_trashbin/files when "delete" button is clicked? Why you don't choose to move instead of copying? Copy takes long long time, mv could move files instantly.

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/issues/12866#issuecomment-72367453

Note that OC 8.0.0 already moves files to trash when possible.
