### ISSUE TITLE
Log shows errors after update from 7.0.1 to 7.0.2

### ISSUE THREAD

**Issue by sthag** [owncloud/core#10923]
### Steps to reproduce
1. Did a fresh install of 7.0.1
2. Created some users and used owncloud, also with client software, for some days.
3. Updated to 7.0.2
4. Error appears with no info.
5. Update nevertheless happened and owncloud reports version 7.0.2

### Expected behaviour
No errors during update expected. Especially because it was a clean install of 7.0.1 before.

### Actual behaviour
These errors happend during the update. They resulted in a error message at the end of the update with no information about what happend or what to do.
```
Error	PHP	Call to undefined method OC\Server::getGroupManager() at /var/www/{removed path}/lib/private/group.php#42	
Error	PHP	Class 'Sabre\DAV\Auth\Backend\AbstractBasic' not found at /var/www/{removed path}/lib/private/connector/sabre/auth.php#24	
Error	PHP	imagecreatefromstring(): Data is not in a recognized format at /var/www/{removed path}/lib/private/image.php#525
```

### Server configuration
**Operating system**: CentOS 5.10

**Web server:** Apache 2.2

**Database:** MYSQL 5.0.95

**PHP version:** 5.3.17

**ownCloud version:** now is 7.0.2, was 7.0.1

**Updated from an older ownCloud or fresh install:** Update

**List of activated apps:** Only the standard ones

**The content of config/config.php:**

```
$CONFIG = array (
  'instanceid' => '{not showing}',
  'passwordsalt' => '{not showing}',
  'trusted_domains' =>
  array (
    0 => 'daten.interaktionsweise.de',
  ),
  'datadirectory' => '/var/www/{not showing}/kiste',
  'dbtype' => 'mysql',
  'version' => '7.0.2.1',
  'dbname' => '{not showing}',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '{not showing}',
  'dbpassword' => '{not showing}',
  'installed' => true,
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
);
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** only https not file encryption

### Client configuration
**Browser:** Chrome 37

**Operating system:** Windows 8.1

I just wanted to let you know about the errors. Owncloud seems to work as expected. Although the update behaviour is still very strange to me.

**Comment by MorrisJobke** [comment]
@sthag The usage of the maintenance mode is crucial and the web upgrade page does it and the ./occ upgrade command also does it.

**Comment by MorrisJobke** [comment]
Feel free to comment if this is still a problem for you with enabled maintenance mode. Thanks.
