### ISSUE TITLE
Sharing "<folder>" failed, because it contains files shared with you!

### ISSUE THREAD

**Issue by butonic** [owncloud/core#10921]
# Motivation

I am trying to provide a (password protected) folder with all the pictures of our latest family addition. There are of course tons of them so we want to filter them and only share the best ones.
# Expected behavior
1. Nina is the owner of the camera, so she uploaded all the Pictures and shared the folder with me.
2. I then shared the most interesting pictures with our "Oberdreyers" account. 
3. As "Oberdreyers" I moved the shared images from the root folder into a "Tim" folder and
4. shared it as a pasword protected link
5. Whoever has the link and password combo can see a selection of our pictures

All shares have been created with reshare and can edit permission. 1. can be omitted,  I only added it for completeness
# Actual behavior

When sharing the folder in 4. the _"Sharing "folder" failed, because it contains files shared with you!"_ message appears.
# Technical details

OC7.0.2 on mysql
Apache2 with PHP-FPM
# More thougts

I updated to oc7 because I had assumed that this kind of filtered sharing would be possible. @DeepDiver1975 and I had this kind of use case with a customer. Now it makes a lot more sense to me: you select the 10 out of 30 files worth sharing and they pop up in a new virtual folder for the receiving user. For them we solved it with a third share type 'collection'.
@schiesbn @icewind1991 With OC7 it might make more sense to create a folder with the same name as the current folder for the receiving user and add the files as individual shares. Then again that kind of grouping does make a lot of sense. Maybe @jancborchardt has a good Idea how that should work in the UI.

**Comment by MorrisJobke** [comment]
@butonic feel free to remove the "needs info" label if @PVince81 steps are the ones you meant
