### ISSUE TITLE
[oC7 mail templates] Error with using Theme

### ISSUE THREAD

**Issue by ser72** [owncloud/core#10942]
**Expected Behavior**
No error appears

**Actual Behavior**
Error appears when selecting Theme

**Steps**
Configure a theme in config.php and copy template files to that location
In the Admin page under MAIL TEMPLATES, select the theme in the pulldown

Error appears:

![capture](https://cloud.githubusercontent.com/assets/5174383/4187626/71777d0c-376b-11e4-8f52-5c471f035303.PNG)

**Comment by MorrisJobke** [comment]
Sounds like a permission issue of the template file that is copied over.

I will close this ticket here. If this is still a problem please reopen it in the template_editor issue tracker. https://github.com/owncloud/templateeditor/issues
