### ISSUE TITLE
Make encryption decision at setup time

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#10956]
As many have noticed, the encryption process is quite complex especially with sharing and groups.
The problem is that you need all users to have their keys generated initially if you want sharing to work for these users.
The current process uses the "encryption migration" where the user's key is generated the first time the user logs in, and only then the user's data gets encrypted.
In a normal OC environment (not LDAP), if the admin creates a user in the users page and types the password themselves, then the key can be generated earlier.

This discussion is mostly about solving the case where encryption is enabled later, not at setup time.

So here is the suggestion:
1) Add a checkbox on the setup page to force admins to decide early about enabling encryption
2) If an admin does want to enable encryption later, it should be done on the CLI. When enabling encryption on the CLI, the user's passwords will be automatically reset to a generated password, because we need a password to generate keys in the first place. The password needs to be communicated to the user, by email or by other means (might not be secure though).

Problems:
- what about the LDAP case where passwords are on the LDAP server ?

@MTRichards @craigpg @karlitschek @schiesbn

**Comment by schiesbn** [comment]
I think the command line script is the preferred way to go. The migration we have now should be only be used for really small installations on shared hosters where the user can't execute command line scripts. But even there I would recommend to backup the files, enable encryption and re-upload them. Shouldn't be a problem for small installations.

**Comment by PVince81** [comment]
This was solved differently with encryption 2.0: encryption can only be enabled once in the admin page.

Close ? Or is there anything else from this ticket we want to implement ?

**Comment by DeepDiver1975** [comment]
> This was solved differently with encryption 2.0: encryption can only be enabled once in the admin page.
> 
> Close ? Or is there anything else from this ticket we want to implement ?

I guess we are good with this. THX
