### ISSUE TITLE
[7.0.1&2] Slow share-"box"

### ISSUE THREAD

**Issue by klewwe** [owncloud/core#10959]
One of our customers have a central share-account with about 60GB data that they in turn share to their users. When trying to share a folder to a user it takes 10-15 seconds for the "share-box" where you type usernames to appear. This only appears for this account and I suspect it's bound to the size of the shares? No problems before 7.0.1 though.

Expected behaviour

Share-box should appear just as quick regardless of how much disk space the account uses.

Actual behaviour

Account with much data is really slow for sharing to new users.

Steps to reproduce

a. Have account with 50+GB data
b. Try to share to user
c. Wait annoyingly long for box to appear

Server configuration:

Operating system: Ubuntu 14.04.1
Web server: Apache 2.4.7 (Ubuntu)
Database: MariaDB 5.5
PHP version: 5.5.9
ownCloud version: 7.0.2

Client configuration:
Web UI

**Comment by PVince81** [comment]
There are plans to move the actual sharing operation to background jobs
@icewind1991 @DeepDiver1975 was there already a ticket for that ?

**Comment by MorrisJobke** [comment]
This will also be fixed together with the new Sharing dialog #3224 (which is planned for 8.2)

**Comment by PVince81** [comment]
@MorrisJobke are you talking about adding a spinner, not solving the slowness issue ?

**Comment by MorrisJobke** [comment]
@PVince81 I was talking about the proper user feedback. Currently simply nothing appears until the request is responed. With the new sharing dialog/sidebar we can add this (as a spinner or something else)

**Comment by PVince81** [comment]
The new sharing dialog will use asynchronous calls instead of synchronous ones, which will make an animated spinner possible. (CC @blizzz)

**Comment by MorrisJobke** [comment]
In 8.2 there is a spinner when opening the share menu. So this is solved.
