### ISSUE TITLE
Fatal Error on Upgrade to (7.0.2-1)

### ISSUE THREAD

**Issue by Aladio** [owncloud/core#10953]
Error Log /var/log/apache2
--------------------------------------
[Mon Sep 08 22:38:11 2014] [error] [client 69.254.138.224] PHP Fatal error:  Access to undeclared static property: OC_Config::$object in /var/www/owncloud/lib/base.php on line 105

Installation under Debian 7
---------------------------------------------------------------------------------------------
 echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/community/Debian_7.0/ /' >> /etc/apt/sources.list.d/owncloud.list
root@iota:~# apt-get update
Hit http://security.debian.org wheezy/updates Release.gpg
Hit http://ftp.us.debian.org wheezy Release.gpg
Hit http://ftp.us.debian.org wheezy-updates Release.gpg
Hit http://security.debian.org wheezy/updates Release
Hit http://ftp.us.debian.org wheezy Release
Hit http://ftp.us.debian.org wheezy-updates Release
Hit http://security.debian.org wheezy/updates/main Sources
Hit http://ftp.us.debian.org wheezy/main Sources
Hit http://ftp.us.debian.org wheezy/main amd64 Packages
Hit http://security.debian.org wheezy/updates/main amd64 Packages
Get:1 http://download.opensuse.org  Release.gpg [189 B]
Hit http://ftp.us.debian.org wheezy/main Translation-en
Hit http://security.debian.org wheezy/updates/main Translation-en
Hit http://ftp.us.debian.org wheezy-updates/main Sources
Hit http://ftp.us.debian.org wheezy-updates/main amd64 Packages/DiffIndex
Get:2 http://download.opensuse.org  Release [1,021 B]
Ign http://download.opensuse.org  Release
Hit http://ftp.us.debian.org wheezy-updates/main Translation-en/DiffIndex
Get:3 http://download.opensuse.org  Packages [676 B]
Ign http://download.opensuse.org  Translation-en_US
Ign http://download.opensuse.org  Translation-en
Fetched 1,886 B in 2s (881 B/s)
Reading package lists... Done
W: GPG error: http://download.opensuse.org  Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 977C43A8BA684223
root@iota:~# apt-get install owncloud
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  javascript-common libjs-jquery libjs-jquery-ui libnet-daemon-perl
  libplrpc-perl libtommath0 php-auth php-auth-sasl php-mail-mime
  php-mail-mimedecode php-net-smtp php-net-socket php5-pspell roundcube-core
  tinymce wwwconfig-common
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  curl dbus fonts-droid ghostscript gsfonts imagemagick-common
  libavahi-client3 libavahi-common-data libavahi-common3 libcups2
  libcupsimage2 libcurl3 libdbus-1-3 libgomp1 libgs9 libgs9-common libice6
  libijs-0.35 libjasper1 libjbig0 libjbig2dec0 liblcms2-2 liblqr-1-0
  libmagickcore5 libmagickwand5 libpaper-utils libpaper1 librtmp0 libsm6
  libssh2-1 libsystemd-login0 libtiff4 libxext6 libxt6 php-xml-parser
  php5-curl php5-imagick php5-pgsql php5-sqlite poppler-data x11-common
Suggested packages:
  dbus-x11 ghostscript-cups ghostscript-x hpijs cups-common libjasper-runtime
  liblcms2-utils libmagickcore5-extra smbclient libav-tools ffmpeg
  libreoffice-writer poppler-utils fonts-japanese-mincho fonts-ipafont-mincho
  fonts-japanese-gothic fonts-ipafont-gothic fonts-arphic-ukai
  fonts-arphic-uming fonts-unfonts-core
Recommended packages:
  php5-apc
The following NEW packages will be installed:
  curl dbus fonts-droid ghostscript gsfonts imagemagick-common
  libavahi-client3 libavahi-common-data libavahi-common3 libcups2
  libcupsimage2 libcurl3 libdbus-1-3 libgomp1 libgs9 libgs9-common libice6
  libijs-0.35 libjasper1 libjbig0 libjbig2dec0 liblcms2-2 liblqr-1-0
  libmagickcore5 libmagickwand5 libpaper-utils libpaper1 librtmp0 libsm6
  libssh2-1 libsystemd-login0 libtiff4 libxext6 libxt6 owncloud php-xml-parser
  php5-curl php5-imagick php5-pgsql php5-sqlite poppler-data x11-common
0 upgraded, 42 newly installed, 0 to remove and 1 not upgraded.
Need to get 52.0 MB of archives.
After this operation, 163 MB of additional disk space will be used.
Do you want to continue [Y/n]? Y
WARNING: The following packages cannot be authenticated!
  owncloud
Install these packages without verification [y/N]? Y
Get:1 http://security.debian.org/ wheezy/updates/main libcups2 amd64 1.5.3-5+deb7u4 [255 kB]
Get:2 http://ftp.us.debian.org/debian/ wheezy/main imagemagick-common all 8:6.7.7.10-5+deb7u3 [128 kB]
Get:3 http://security.debian.org/ wheezy/updates/main libcupsimage2 amd64 1.5.3-5+deb7u4 [138 kB]
Get:4 http://download.opensuse.org/repositories/isv:/ownCloud:/community/Debian_7.0/  owncloud 7.0.2-1 [32.6 MB]
Get:5 http://security.debian.org/ wheezy/updates/main php5-curl amd64 5.4.4-14+deb7u14 [29.2 kB]
Get:6 http://ftp.us.debian.org/debian/ wheezy/main libavahi-common-data amd64 0.6.31-2 [135 kB]
Get:7 http://security.debian.org/ wheezy/updates/main php5-pgsql amd64 5.4.4-14+deb7u14 [61.0 kB]
Get:8 http://security.debian.org/ wheezy/updates/main php5-sqlite amd64 5.4.4-14+deb7u14 [30.3 kB]
Get:9 http://ftp.us.debian.org/debian/ wheezy/main libavahi-common3 amd64 0.6.31-2 [54.6 kB]
Get:10 http://ftp.us.debian.org/debian/ wheezy/main libdbus-1-3 amd64 1.6.8-1+deb7u3 [172 kB]
Get:11 http://ftp.us.debian.org/debian/ wheezy/main libavahi-client3 amd64 0.6.31-2 [59.5 kB]
Get:12 http://ftp.us.debian.org/debian/ wheezy/main libjbig0 amd64 2.0-2+deb7u1 [32.6 kB]
Get:13 http://ftp.us.debian.org/debian/ wheezy/main libtiff4 amd64 3.9.6-11 [202 kB]
Get:14 http://ftp.us.debian.org/debian/ wheezy/main librtmp0 amd64 2.4+20111222.git4e06e21-1 [62.3 kB]
Get:15 http://ftp.us.debian.org/debian/ wheezy/main libssh2-1 amd64 1.4.2-1.1 [133 kB]
Get:16 http://ftp.us.debian.org/debian/ wheezy/main libcurl3 amd64 7.26.0-1+wheezy9 [331 kB]
Get:17 http://ftp.us.debian.org/debian/ wheezy/main libgomp1 amd64 4.7.2-5 [27.5 kB]
Get:18 http://ftp.us.debian.org/debian/ wheezy/main x11-common all 1:7.7+3~deb7u1 [284 kB]
Get:19 http://ftp.us.debian.org/debian/ wheezy/main libice6 amd64 2:1.0.8-2 [63.1 kB]
Get:20 http://ftp.us.debian.org/debian/ wheezy/main libjasper1 amd64 1.900.1-13 [159 kB]
Get:21 http://ftp.us.debian.org/debian/ wheezy/main liblcms2-2 amd64 2.2+git20110628-2.2+deb7u1 [144 kB]
Get:22 http://ftp.us.debian.org/debian/ wheezy/main liblqr-1-0 amd64 0.4.1-2 [29.9 kB]
Get:23 http://ftp.us.debian.org/debian/ wheezy/main libsm6 amd64 2:1.2.1-2 [34.2 kB]
Get:24 http://ftp.us.debian.org/debian/ wheezy/main libxext6 amd64 2:1.3.1-2+deb7u1 [54.8 kB]
Get:25 http://ftp.us.debian.org/debian/ wheezy/main libxt6 amd64 1:1.1.3-1+deb7u1 [212 kB]
Get:26 http://ftp.us.debian.org/debian/ wheezy/main libmagickcore5 amd64 8:6.7.7.10-5+deb7u3 [2,083 kB]
Get:27 http://ftp.us.debian.org/debian/ wheezy/main libmagickwand5 amd64 8:6.7.7.10-5+deb7u3 [462 kB]
Get:28 http://ftp.us.debian.org/debian/ wheezy/main libpaper1 amd64 1.1.24+nmu2 [22.0 kB]
Get:29 http://ftp.us.debian.org/debian/ wheezy/main php-xml-parser all 1.3.4-6 [27.2 kB]
Get:30 http://ftp.us.debian.org/debian/ wheezy/main poppler-data all 0.4.5-10 [1,479 kB]
Get:31 http://ftp.us.debian.org/debian/ wheezy/main libsystemd-login0 amd64 44-11+deb7u4 [29.5 kB]
Get:32 http://ftp.us.debian.org/debian/ wheezy/main curl amd64 7.26.0-1+wheezy9 [270 kB]
Get:33 http://ftp.us.debian.org/debian/ wheezy/main dbus amd64 1.6.8-1+deb7u3 [399 kB]
Get:34 http://ftp.us.debian.org/debian/ wheezy/main fonts-droid all 20111207+git-1 [4,312 kB]
Get:35 http://ftp.us.debian.org/debian/ wheezy/main libijs-0.35 amd64 0.35-8 [20.4 kB]
Get:36 http://ftp.us.debian.org/debian/ wheezy/main libjbig2dec0 amd64 0.11+20120125-1 [51.8 kB]
Get:37 http://ftp.us.debian.org/debian/ wheezy/main libgs9-common all 9.05~dfsg-6.3+deb7u1 [1,980 kB]
Get:38 http://ftp.us.debian.org/debian/ wheezy/main libgs9 amd64 9.05~dfsg-6.3+deb7u1 [1,844 kB]
Get:39 http://ftp.us.debian.org/debian/ wheezy/main gsfonts all 1:8.11+urwcyr1.0.7~pre44-4.2 [3,364 kB]
Get:40 http://ftp.us.debian.org/debian/ wheezy/main ghostscript amd64 9.05~dfsg-6.3+deb7u1 [80.0 kB]
Get:41 http://ftp.us.debian.org/debian/ wheezy/main libpaper-utils amd64 1.1.24+nmu2 [18.3 kB]
Get:42 http://ftp.us.debian.org/debian/ wheezy/main php5-imagick amd64 3.1.0~rc1-1+b2 [134 kB]
Fetched 52.0 MB in 8s (5,810 kB/s)
Extracting templates from packages: 100%
Preconfiguring packages ...
Selecting previously unselected package imagemagick-common.
(Reading database ... 29027 files and directories currently installed.)
Unpacking imagemagick-common (from .../imagemagick-common_8%3a6.7.7.10-5+deb7u3_all.deb) ...
Selecting previously unselected package libavahi-common-data:amd64.
Unpacking libavahi-common-data:amd64 (from .../libavahi-common-data_0.6.31-2_amd64.deb) ...
Selecting previously unselected package libavahi-common3:amd64.
Unpacking libavahi-common3:amd64 (from .../libavahi-common3_0.6.31-2_amd64.deb) ...
Selecting previously unselected package libdbus-1-3:amd64.
Unpacking libdbus-1-3:amd64 (from .../libdbus-1-3_1.6.8-1+deb7u3_amd64.deb) ...
Selecting previously unselected package libavahi-client3:amd64.
Unpacking libavahi-client3:amd64 (from .../libavahi-client3_0.6.31-2_amd64.deb) ...
Selecting previously unselected package libcups2:amd64.
Unpacking libcups2:amd64 (from .../libcups2_1.5.3-5+deb7u4_amd64.deb) ...
Selecting previously unselected package libjbig0:amd64.
Unpacking libjbig0:amd64 (from .../libjbig0_2.0-2+deb7u1_amd64.deb) ...
Selecting previously unselected package libtiff4:amd64.
Unpacking libtiff4:amd64 (from .../libtiff4_3.9.6-11_amd64.deb) ...
Selecting previously unselected package libcupsimage2:amd64.
Unpacking libcupsimage2:amd64 (from .../libcupsimage2_1.5.3-5+deb7u4_amd64.deb) ...
Selecting previously unselected package librtmp0:amd64.
Unpacking librtmp0:amd64 (from .../librtmp0_2.4+20111222.git4e06e21-1_amd64.deb) ...
Selecting previously unselected package libssh2-1:amd64.
Unpacking libssh2-1:amd64 (from .../libssh2-1_1.4.2-1.1_amd64.deb) ...
Selecting previously unselected package libcurl3:amd64.
Unpacking libcurl3:amd64 (from .../libcurl3_7.26.0-1+wheezy9_amd64.deb) ...
Selecting previously unselected package libgomp1:amd64.
Unpacking libgomp1:amd64 (from .../libgomp1_4.7.2-5_amd64.deb) ...
Selecting previously unselected package x11-common.
Unpacking x11-common (from .../x11-common_1%3a7.7+3~deb7u1_all.deb) ...
Selecting previously unselected package libice6:amd64.
Unpacking libice6:amd64 (from .../libice6_2%3a1.0.8-2_amd64.deb) ...
Selecting previously unselected package libjasper1:amd64.
Unpacking libjasper1:amd64 (from .../libjasper1_1.900.1-13_amd64.deb) ...
Selecting previously unselected package liblcms2-2:amd64.
Unpacking liblcms2-2:amd64 (from .../liblcms2-2_2.2+git20110628-2.2+deb7u1_amd64.deb) ...
Selecting previously unselected package liblqr-1-0:amd64.
Unpacking liblqr-1-0:amd64 (from .../liblqr-1-0_0.4.1-2_amd64.deb) ...
Selecting previously unselected package libsm6:amd64.
Unpacking libsm6:amd64 (from .../libsm6_2%3a1.2.1-2_amd64.deb) ...
Selecting previously unselected package libxext6:amd64.
Unpacking libxext6:amd64 (from .../libxext6_2%3a1.3.1-2+deb7u1_amd64.deb) ...
Selecting previously unselected package libxt6:amd64.
Unpacking libxt6:amd64 (from .../libxt6_1%3a1.1.3-1+deb7u1_amd64.deb) ...
Selecting previously unselected package libmagickcore5:amd64.
Unpacking libmagickcore5:amd64 (from .../libmagickcore5_8%3a6.7.7.10-5+deb7u3_amd64.deb) ...
Selecting previously unselected package libmagickwand5:amd64.
Unpacking libmagickwand5:amd64 (from .../libmagickwand5_8%3a6.7.7.10-5+deb7u3_amd64.deb) ...
Selecting previously unselected package libpaper1:amd64.
Unpacking libpaper1:amd64 (from .../libpaper1_1.1.24+nmu2_amd64.deb) ...
Selecting previously unselected package php-xml-parser.
Unpacking php-xml-parser (from .../php-xml-parser_1.3.4-6_all.deb) ...
Selecting previously unselected package php5-curl.
Unpacking php5-curl (from .../php5-curl_5.4.4-14+deb7u14_amd64.deb) ...
Selecting previously unselected package php5-pgsql.
Unpacking php5-pgsql (from .../php5-pgsql_5.4.4-14+deb7u14_amd64.deb) ...
Selecting previously unselected package php5-sqlite.
Unpacking php5-sqlite (from .../php5-sqlite_5.4.4-14+deb7u14_amd64.deb) ...
Selecting previously unselected package poppler-data.
Unpacking poppler-data (from .../poppler-data_0.4.5-10_all.deb) ...
Selecting previously unselected package libsystemd-login0:amd64.
Unpacking libsystemd-login0:amd64 (from .../libsystemd-login0_44-11+deb7u4_amd64.deb) ...
Selecting previously unselected package curl.
Unpacking curl (from .../curl_7.26.0-1+wheezy9_amd64.deb) ...
Selecting previously unselected package dbus.
Unpacking dbus (from .../dbus_1.6.8-1+deb7u3_amd64.deb) ...
Selecting previously unselected package fonts-droid.
Unpacking fonts-droid (from .../fonts-droid_20111207+git-1_all.deb) ...
Selecting previously unselected package libijs-0.35.
Unpacking libijs-0.35 (from .../libijs-0.35_0.35-8_amd64.deb) ...
Selecting previously unselected package libjbig2dec0.
Unpacking libjbig2dec0 (from .../libjbig2dec0_0.11+20120125-1_amd64.deb) ...
Selecting previously unselected package libgs9-common.
Unpacking libgs9-common (from .../libgs9-common_9.05~dfsg-6.3+deb7u1_all.deb) ...
Selecting previously unselected package libgs9.
Unpacking libgs9 (from .../libgs9_9.05~dfsg-6.3+deb7u1_amd64.deb) ...
Selecting previously unselected package gsfonts.
Unpacking gsfonts (from .../gsfonts_1%3a8.11+urwcyr1.0.7~pre44-4.2_all.deb) ...
Selecting previously unselected package ghostscript.
Unpacking ghostscript (from .../ghostscript_9.05~dfsg-6.3+deb7u1_amd64.deb) ...
Selecting previously unselected package libpaper-utils.
Unpacking libpaper-utils (from .../libpaper-utils_1.1.24+nmu2_amd64.deb) ...
Selecting previously unselected package owncloud.
Unpacking owncloud (from .../owncloud_7.0.2-1_all.deb) ...
Selecting previously unselected package php5-imagick.
Unpacking php5-imagick (from .../php5-imagick_3.1.0~rc1-1+b2_amd64.deb) ...
Processing triggers for man-db ...
Processing triggers for libapache2-mod-php5 ...
[ ok ] Reloading web server config: apache2.
Setting up imagemagick-common (8:6.7.7.10-5+deb7u3) ...
Setting up libavahi-common-data:amd64 (0.6.31-2) ...
Setting up libavahi-common3:amd64 (0.6.31-2) ...
Setting up libdbus-1-3:amd64 (1.6.8-1+deb7u3) ...
Setting up libavahi-client3:amd64 (0.6.31-2) ...
Setting up libcups2:amd64 (1.5.3-5+deb7u4) ...
Setting up libjbig0:amd64 (2.0-2+deb7u1) ...
Setting up libtiff4:amd64 (3.9.6-11) ...
Setting up libcupsimage2:amd64 (1.5.3-5+deb7u4) ...
Setting up librtmp0:amd64 (2.4+20111222.git4e06e21-1) ...
Setting up libssh2-1:amd64 (1.4.2-1.1) ...
Setting up libcurl3:amd64 (7.26.0-1+wheezy9) ...
Setting up libgomp1:amd64 (4.7.2-5) ...
Setting up x11-common (1:7.7+3~deb7u1) ...
[ ok ] Setting up X socket directories... /tmp/.X11-unix /tmp/.ICE-unix.
Setting up libice6:amd64 (2:1.0.8-2) ...
Setting up libjasper1:amd64 (1.900.1-13) ...
Setting up liblcms2-2:amd64 (2.2+git20110628-2.2+deb7u1) ...
Setting up liblqr-1-0:amd64 (0.4.1-2) ...
Setting up libsm6:amd64 (2:1.2.1-2) ...
Setting up libxext6:amd64 (2:1.3.1-2+deb7u1) ...
Setting up libxt6:amd64 (1:1.1.3-1+deb7u1) ...
Setting up libmagickcore5:amd64 (8:6.7.7.10-5+deb7u3) ...
Setting up libmagickwand5:amd64 (8:6.7.7.10-5+deb7u3) ...
Setting up libpaper1:amd64 (1.1.24+nmu2) ...

Creating config file /etc/papersize with new version
Setting up php-xml-parser (1.3.4-6) ...
Setting up php5-curl (5.4.4-14+deb7u14) ...

Creating config file /etc/php5/mods-available/curl.ini with new version
Setting up php5-pgsql (5.4.4-14+deb7u14) ...

Creating config file /etc/php5/mods-available/pgsql.ini with new version

Creating config file /etc/php5/mods-available/pdo_pgsql.ini with new version
Setting up php5-sqlite (5.4.4-14+deb7u14) ...

Creating config file /etc/php5/mods-available/sqlite3.ini with new version

Creating config file /etc/php5/mods-available/pdo_sqlite.ini with new version
Setting up poppler-data (0.4.5-10) ...
Setting up libsystemd-login0:amd64 (44-11+deb7u4) ...
Setting up curl (7.26.0-1+wheezy9) ...
Setting up dbus (1.6.8-1+deb7u3) ...
[ ok ] Starting system message bus: dbus.
Setting up fonts-droid (20111207+git-1) ...
Setting up libijs-0.35 (0.35-8) ...
Setting up libjbig2dec0 (0.11+20120125-1) ...
Setting up libgs9-common (9.05~dfsg-6.3+deb7u1) ...
Setting up libgs9 (9.05~dfsg-6.3+deb7u1) ...
Setting up gsfonts (1:8.11+urwcyr1.0.7~pre44-4.2) ...
Setting up ghostscript (9.05~dfsg-6.3+deb7u1) ...
Setting up libpaper-utils (1.1.24+nmu2) ...
Setting up php5-imagick (3.1.0~rc1-1+b2) ...

Creating config file /etc/php5/conf.d/imagick.ini with new version
Processing triggers for libapache2-mod-php5 ...
[ ok ] Reloading web server config: apache2.
Setting up owncloud (7.0.2-1) ...

**Comment by jnweiger** [comment]
See fixes to this:  https://github.com/owncloud/core/issues/12125
please reopen, if this is still an issue.
