### ISSUE TITLE
Upload to OC server with encryption can lead to 0.1% corrupted files.

### ISSUE THREAD

**Issue by VincentvgNn** [owncloud/core#10975]
### Description

Using the OC client and uploading many files to the OC server that uses encryption can lead to encrypted files that are corrupted. When these files are downloaded to another sharing client, the file size and modification date are ok, but a CRC check against the original file shows that they are different. Opening these files is impossible due to the corruption.
Downloading to other clients or via the web interface makes no difference. The corrupted files are exactly equal.
A binary comparison shows that one or more sections of these files are corrupted.

![example corrupted jpg-file](https://cloud.githubusercontent.com/assets/7522929/4211076/019ab302-3881-11e4-8014-7d5fca51d416.png)
(left: original file, right: corrupted file, 2/3 is ok)

### Current issue
Uploading of a 500 MB data set of 3000 files and 300 folders leads to about 0.1% corrupted files when encryption is used.

### Steps to reproduce
1. Use the OC server at a website host with many other users, such that one can be sure of a limited speed and connection interruptions.
2. Let the admin share an empty r/w test folder with 2 or more OC clients (preferably at your own local network for easy comparison).
3. Let all clients be online and copy a 500MB data set with 3000 files and 300 folders into the test folder at client 1
4. Wait 6-8 hours until all data is copied to the other clients.
5. Use a file comparison tool like Beyond Compare to do a CRC check between the original files and the files copied to the other clients.
6. About 0-5 files will have corrupted sections due to the encryption. I repeated this test at least 5 times.

![encrypted files corrupted - selection](https://cloud.githubusercontent.com/assets/7522929/4211140/4ade52a2-3882-11e4-83cb-1bd3b5f4b119.png)
(left: 2 original files, right 2 corrupted files)

### Expected behavior
No data loss or corruption. Same data integrity performance as on a HDD.

### Server configuration
OC server installed at a Dutch webhosting company. 4-5 GB storage.
Control via DirectAdmin and installation using Installatron.
Own (non-shared) IP, ownCloud using https and encryption.

Operating system: Linux Hosting Package
Web server: Apache
Database: MySQL
PHP version: native, 5.5.
ownCloud version: 7.0.2 (stable)
List of activated apps: default apps + encryption
External storage: no
Encryption: yes

### Client configuration
Browser: Google Chrome (or Firefox or IE11)
Operating system: Win XP, Win 7 or Win 8
ownCloud version: 1.6.3

**Comment by guruz** [comment]
@shikasta-net Hi! Can you tell us if you were using encryption or not?
Can you also tell us which Apache version it was on that 3rd of December?

**Comment by shikasta-net** [comment]
I appear to have been using 2.4.7, installed 5th Oct last year when I upgraded to Ubuntu 14.04.

The Apache proxy is configured to redirect all traffic through HTTPS, so it was definitely encrypted but I don't remember what 
settings I used and I've since overhauled the config to take advantage of some changes between Apache 2.2 and 2.4.

Kym

**Comment by guruz** [comment]
@shikasta-net I don't mean HTTPS/SSL encryption, I mean the ```encryption``` app in ownCloud which encrypts your files. Did you enable+use that?

**Comment by shikasta-net** [comment]
No I disabled most apps (including encryption) when I first installed the server.

Kym

**Comment by VincentvgNn** [comment]
On 22-09-2015 I wrote:
_New is that I got 2 corrupted files on the downloading PC's, one on each PC, files that are missing a piece of data at the end. These files got corrupted at the download. In the cloud they are OK._

In a recent test of server 8.0.3 and client 1.8.1, I again found one file that was corrupted at download on one PC. Unfortunately the beginning of the client log was truncated until just after the incident.
The server log shows that the file was downloaded a second time some minutes after it was created at that client for the first time. So for some reason the file was downloaded a second time without writing it correctly to the client's storage folder.
I'l have to wait for a next incident and not forget to have the file logging switched on.

**Comment by PVince81** [comment]
@VincentvgNn are you still seeing the corrupted files with the new sync client 2.0.1 and ownCloud 8.1.3 with the new encryption ?

**Comment by PVince81** [comment]
same question for @shikasta-net :smile:

**Comment by cmonteroluque** [comment]
moving to 8.2.1 unless it is re-prioritized. We will triage it again

**Comment by shikasta-net** [comment]
@PVince81, I haven't seen file corruption in a while (I'm on server 8.1.1) but also haven't used it quite so extensively since it happened.  I shall try some more heavy testing and report back.

**Comment by cmonteroluque** [comment]
closing issue until we get some additional input
