### ISSUE TITLE
Exclude with groups cannot work with groups containing commas

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#10983]
### Steps to reproduce:
1. Create a group called "comma,group"
2. Exclude that group from sharing

### Expected result
Group properly excluded

### Actual result
(not tested but guessing) group name is split into two groups "comma" and "group", so exclusion cannot work.

Note that other places like the "enable app for groups" use JSON to store the groups array.

The "exclude sharing for groups" feature need to be fixed to also use JSON.

CC @schiesbn

**Comment by DeepDiver1975** [comment]
@PVince81 OC8.1?

**Comment by carlaschroder** [comment]
added to 8.0 release note

**Comment by PVince81** [comment]
Now thinking of it, we might not need to keep the code backward compatible because we can auto-fix the configuration in a repair step to make sure it's using the new format.
