### ISSUE TITLE
Encryption don't encrypt the new files

### ISSUE THREAD

**Issue by Thx3r** [owncloud/core#11010]
Hi, i don"t if it's normal. When i enable the encrypter Apps all my files are great encrypted, but when i upload new file from my sync folder there not encrypted on the server side.
Do you have a solution ?
No new key file are present in /data/user/files_encryption/keyfiles for the new upload files.

Regard's

**Comment by PVince81** [comment]
Closing due to lack of information.

If you're still seeing this with 7.0.5 or 8.0.2, feel free to reopen.
Thanks.
