### ISSUE TITLE
PHP: Can't rmdir because directory not empty on deleting user

### ISSUE THREAD

**Issue by Bugsbane** [owncloud/core#11030]
When I delete a user in ownCloud 7.0.2 it appears to work in the GUI, however in the log I see:

Error 	PHP 	rmdir(/path/to/owncloud/data/username): Directory not empty at /path/to/owncloud/lib/private/helper.php#421 	2014-09-11T17:03:52+00:00

...and indeed, the user's folder remains with files in the data folder. I also get the following errors, despite all files being owned by the webserver user:

Error 	PHP 	rmdir(/path/to/owncloud/data/username/cache): Permission denied at /path/to/owncloud/lib/private/helper.php#416 	2014-09-11T17:03:52+00:00
Error 	PHP 	rmdir(/path/to/owncloud/data/username/files): Permission denied at /path/to/owncloud/lib/private/helper.php#416 	2014-09-11T17:03:52+00:00
Error	PHP	unlink(/path/to/owncloud/data/username/files/File name.pptx): Permission denied at /path/to/owncloud/lib/private/helper.php#418

Obviously these logs have been anonymized. The file name in the last one seemed to have an unescaped space in the file name in the log. I'm wondering if this might have something to do with this all.

Setup:
Nginx
PHP 5.5.13
Owncloud 7.0.2
Mysql

**Comment by PVince81** [comment]
@Bugsbane are you still seeing this with 7.0.5 or 8.0.2 ? Did you check SELinux ?

**Comment by PVince81** [comment]
CC @josh4trunks for nginx stuff, in case you have an idea

**Comment by Bugsbane** [comment]
I don't seem to be getting it any more in ownCloud 7.0.4
