### ISSUE TITLE
big files upload don`t work

### ISSUE THREAD

**Issue by Happyfeet01** [owncloud/core#11031]
### Steps to reproduce
1. try to upload an file bigger than ~200 MB
2. php.ini upload and post size at 16 GB

### Expected behaviour
I try to upload an big File (1GB). for few seconds it works but after that the upload process stops without an error at the nginx Log or PHP or Owncloud.log. Files with few MB works still.

### Actual behaviour
i make an Upload and have a look at the Google Chrome Console. It shows me this Error: Failed to load resource: net::ERR_CONNECTION_RESET 

### Server configuration
**Operating system**: CeentOS

**Web server:** Nginx

**Database:** Mysql

**PHP version:** PHP 5.6

**ownCloud version:** : 7.0.2

**Updated from an older ownCloud or fresh install:**

**List of activated apps:**

**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password and passwordsalt)
```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** : No

### Client configuration
**Browser:** Google Chrome 37.0.2062.103

**Operating system:** windows 8.1

#### Web server error log

Insert your webserver log here

#### Browser log

Failed to load resource: net::ERR_CONNECTION_RESET

**Comment by PVince81** [comment]
@Happyfeet01 have you tried with client_max_body_size ?

Closing as it's likely to be an env issue.
If you still have issues, feel free to reopen.
