### ISSUE TITLE
[7.0.2.1] "OC_Apps::shouldUpgrade()"-Error after Update

### ISSUE THREAD

**Issue by EchoSierra** [owncloud/core#11044]
### Steps to reproduce
I'm running OC since Version 5 and I did every Update. Every Update worked. My last version was 7.0.1 which also worked.
Now I tried to update to 7.0.2 (7.0.2.1). After overwriting the files the "your ownCloud is updating" message was shown in browser window. Everything worked as in every update I did in the past.
But after the update process I got only a white window. I took a look in my apache's error log and found the following message:
"PHP Fatal error:  Call to undefined method OC_App::shouldUpgrade() in /path_to_oc/lib/private/util.php on line 1475"

I restored the old Installation from Backup and tried it again -> same problem...

### Expected behaviour
Normally the login page should be shown.

### Actual behaviour
only a white window and an error message in logs.

### Server configuration
**Operating system**:
openSuSE 12.3

**Web server:**
apache2

**Database:**
mysql

**PHP version:**
5.3.17

**ownCloud version:** (see ownCloud admin page)
7.0.2.1

**Updated from an older ownCloud or fresh install:**
updated from 7.0.1

**List of activated apps:**
activity
bookmarks
calendar
contacts
documents
external
files
files_external
files_sharing
files_texteditor
files_trashbin
files_versions
files_videoviewer
firstrunwizard
gallery
templateeditor
updater
user_external
user_ldap

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '{not_shown}',
  'passwordsalt' => '{not_shown}',
  'datadirectory' => '/srv/www/oc_data_copy',
  'dbtype' => 'mysql',
  'version' => '7.0.2.1',
  'dbname' => 'owncloud_7',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '{not_shown}',
  'dbpassword' => '{not_shown}',
  'installed' => true,
  'forcessl' => false,
  'ldapIgnoreNamingRules' => false,
  'loglevel' => '0',
  'theme' => '',
  'maintenance' => false,
  'maxZipInputSize' => 0,
  'allowZipDownload' => true,
  'overwritewebroot' => 'oc_7',
  'trusted_domains' =>
  array (
    0 => '{not_shown}',
  ),
  'mail_smtpmode' => 'php',
  'mail_from_address' => 'owncloud',
  'mail_domain' => '{not_shown}',
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no - not at the moment

**Are you using encryption:** yes/no
no

### Client configuration
**Browser:**
Safari (OS X 10.9)

**Operating system:**
OS X 10.9

#### Web server error log
[Fri Sep 12 13:07:58 2014] [error] [client (...)] PHP Fatal error:  Call to undefined method OC_App::shouldUpgrade() in /srv/www/htdocs/oc_7/lib/private/util.php on line 1475

#### Insert your webserver log here
[12/Sep/2014:13:33:22 +0200] "GET /oc_7/index.php HTTP/1.1" 500 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/7.0.6 Safari/537.78.2"

#### ownCloud log (data/owncloud.log)
{"app":"PHP","message":"Call to undefined method OC_App::shouldUpgrade() at \/srv\/www\/htdocs\/oc_7\/lib\/private\/util.php#1475","level":3,"time":"2014-09-12T11:33:22+00:00"}

**Comment by PVince81** [comment]
The "needUpgrade" issue was fixed here https://github.com/owncloud/core/pull/8974

Also you might want to check your APC cache in case it still happens.

If this still happens for you with 7.0.5 or 8.0.2, feel free to reopen.
Thanks.
