### ISSUE TITLE
Activating deleted files app: Error: Table 'oc_files_trash' already exists

### ISSUE THREAD

**Issue by Bugsbane** [owncloud/core#11047]
When I try to enable the deleted files app, I just get the following Mysql error onscreen:

An exception occurred while executing 'CREATE TABLE oc_files_trash (auto_id INT AUTO_INCREMENT NOT NULL, id VARCHAR(250) DEFAULT '' NOT NULL, user VARCHAR(64) DEFAULT '' NOT NULL, timestamp VARCHAR(12) DEFAULT '' NOT NULL, location VARCHAR(512) DEFAULT '' NOT NULL, type VARCHAR(4) DEFAULT NULL, mime VARCHAR(255) DEFAULT NULL, INDEX id_index (id), INDEX timestamp_index (timestamp), INDEX user_index (user), PRIMARY KEY(auto_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_files_trash' already exists

I don't recall even enabling the trash app before, but I do wonder if this could be a consequence of being an install that was upgraded from Sqlite3 to Mysql by occ (just after upgrading from 6.0.3 to 7.0.0.

Setup:
Owncloud 7.0.2 (also seen on 7.0.1)
Mysql (was Sqlite 3 , but upgraded to Mysql via occ)
PHP 5.5.13
Nginx
Firefox 32

Apps:
Activity
Bookmarks
Calendar
Contacts
Documents
Full text search
PDF viewer
Pictures
Share files
Text editor
Updater
Video viewer
Files move

**Comment by DeepDiver1975** [comment]
> I suggest to enable the '--all' options by default.

@bantu can I ask you to take care of this and submit a PR? THX

**Comment by PVince81** [comment]
@bantu any update ?

**Comment by cmonteroluque** [comment]
@DeepDiver1975 any thoughts on who else

**Comment by DeepDiver1975** [comment]
Backlog for now - lesser issue

**Comment by rickvanderzwet** [comment]
I was facing the same issue when upgraded a few major versions and moving from SQLite to PostgreSQL. In the old SQLite database table `oc_files_trash` existed, yet no references to the installed plugin Trash. The empty database table `oc_files_trash` also existed in the PostgreSQL database. 

Since the table `oc_files_trash` was empty, I issued a drop table on `oc_files_trash` and it allowed me to activate the Trash Plugin.

**Comment by DeepDiver1975** [comment]
I'm closing this - from my understanding we got this solved i the past releases

**Comment by wdehoog** [comment]
Unfortunately it is still happening. While upgrading from 8 to 9 we had exactly this problem and had to manualy remove the tables before the upgrade could finish.
