### ISSUE TITLE
Can't upgrade to owncloud 7.0.2

### ISSUE THREAD

**Issue by Ange7** [owncloud/core#11062]
When i run upgrade : 

I have this error,

An exception occurred while executing 'ALTER TABLE `oc_oc_appconfig_3968dc0facdf5` DROP PRIMARY KEY':

SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'PRIMARY'; check that column/key exists

i use debian wheezy package owncloud

**Comment by MorrisJobke** [comment]
```
'version' => '5.0.28'
```
@Ange7 You tried to upgrad from ownCloud 5 to 7. This is not supported. Please upgrade to ownCloud 6 first.

See this thread:
https://mailman.owncloud.org/pipermail/user/2015-January/001028.html
https://mailman.owncloud.org/pipermail/user/2015-January/001029.html

Please also verify to not use the owncloud package from the debian repo but rather the one from the OBS as this are the official packages provided by us.

Reason is also here: https://mailman.owncloud.org/pipermail/user/2015-January/001031.html

Create a new issue with proper error message, if there is still a problem.
