### ISSUE TITLE
Regression on external storage admin configuration

### ISSUE THREAD

**Issue by Xenopathic** [owncloud/core#11079]
When adding a new external storage, the 'applicable for' box on the right is shorter than any existing storages. It seems that `display: inline;` is added to existing storages, which makes them ignore the width and just use up as much space as possible. Discovered on Firefox 32.0 on Linux.

![screenshot - 150914 - 11 40 35](https://cloud.githubusercontent.com/assets/2016878/4270054/d9c09340-3cc4-11e4-9673-d2bc91220890.png)

**Comment by PVince81** [comment]
Works for me on stable7 (bf1f9df590e45de4bb9a02c3f472ffdbe702bc69) and master (5ce295907fd9469905d561de71d83149a6c0f6c5)

It is likely that this has been fixed as part of other ext storage UI fixed (the ones that adds select2).

@Xenopathic please reopen if you still see this. Thanks.

**Comment by Xenopathic** [comment]
Indeed, it does seem to have gone. Excellent news!
