### ISSUE TITLE
Inconsistent User Count When Searching for a User

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#11087]
Expected behavior:
When I search for a new user using the new user management page, I expect the number counts on the user groups to the left to be consistent. Specifically, I expect the count of matching users based on the search criteria for each group to show up.

What Happens:
I get different behaviors. If I search, I see the Everyone group has the total number of users for the instance in it. The groups themselves have blank count entries.
![untitled](https://cloud.githubusercontent.com/assets/1818977/4271525/14d848b0-3cd9-11e4-8c6a-d15bc6c08130.png)

And
![untitled1](https://cloud.githubusercontent.com/assets/1818977/4271526/1d5cad96-3cd9-11e4-9d99-0ce6cc34d380.png)

Using:
ownCloud Daily build 15 September
openSUSE
SQLite
Firefox latest on Windows 7

@jancborchardt

**Comment by PVince81** [comment]
Still happening in 8.2RC1 (just checked in the hope it might have been fixed already :wink:)

**Comment by PVince81** [comment]
some design input here https://github.com/owncloud/core/issues/8516 (duplicate)

**Comment by cdamken** [comment]
> some design input here #8516 (duplicate)

Close this?

**Comment by hodyroff** [comment]
Yes. Works now.
