### ISSUE TITLE
7 Daily Build: New User Groups Display NaN instead of Group User Count

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#11086]
Testing ownCloud daily build (for Sep 15th) I created a new user in the user management page, and created a new group called users. The user was successfully created and all seemed to work. Except the Group user count displays NaN instead of the correct user count of 1.

![untitled2](https://cloud.githubusercontent.com/assets/1818977/4271473/7284da10-3cd8-11e4-9282-a853f4b98ad0.png)

After a reload, it looks good and gets a user count. It should just not display the NaN.

openSUSE
SQLite
Latest Firefox on Windows 7

Regression of issue:
https://github.com/owncloud/core/issues/9782

**Comment by PVince81** [comment]
Still happening in OC 7.0.4 and stable7 (bf1f9df590e45de4bb9a02c3f472ffdbe702bc69):
1. Create a user "user1" and directly assign a new group "abc" (hit enter to create it)
2. Click the "Create button"

At step 1. the group appears as soon as enter is hit, without any number.
Then at step 2, at creation time, "NaN" appears behind it.

It works fine on master (5ce295907fd9469905d561de71d83149a6c0f6c5)

@karlitschek @DeepDiver1975 this was fixed on master, do we want a backport to OC 7 (if possible) for such a minor issue ?

CC @LukasReschke @MorrisJobke
