### ISSUE TITLE
[Webdav]When trying to rename an external storage folder of Dropbox, a new folder is created

### ISSUE THREAD

**Issue by purigarcia** [owncloud/core#11089]
### Steps to reproduce
1. In the web, mount an external storage as dropbox for an user.
2. Using poster, complement of firefox, try to change the name of the folder.
Notice that it’s an action that should be able to be done. In the web, it’s not possible.

     ◦ URL: http://server/remote.php/webdav/dropbox
     ◦ user/password
     ◦ Select MOVE
	   - Headers
		   * Destination: http://server/remote.php/webdav/dropbox_mod
		   * Overwrite: T
     Click in the green button
3.  A 403 error is received
	Status: 403 Forbidden
4. In the web, refresh the page. There are two folders: dropbox and dropbbox_mod

### Expected behaviour
A 403 error is received and dropbbox_mod is not created.

### Actual behaviour
A 403 error is received and dropbbox_mod is created.

### Server configuration
**ownCloud version: {"installed":"true","version":"7.0.2.1","versionstring":"7.0.2","edition":""}

**Comment by PVince81** [comment]
Tried the following on stable8:
1. Mount dropbox storage as "/db"
2. Use cadaver/webdav to rename "/db" to "/db_renamed"
4. Check the list

Still happens on stable8 and master

**Comment by PVince81** [comment]
Verified, this was fixed in 8.2 through @rullzer's https://github.com/owncloud/core/pull/19609
