### ISSUE TITLE
Encryption recovery UX issues

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#11107]
### Steps to reproduce:
1) Enable encryption
1) Enable recovery key
2) As "user1" enable recovery
3) As admin, go to users page
4) Enter the recovery password on to
5) Enter a new password for "user1"

### Expected result
At step 4) the recovery key password should be verified and there should be a visual clue that it is correct, for example a check mark behind it.
At step 5) when the user's password has been changed whether normally or through recovery, a notification should say so.

### Actual result
At step 4) and step 5) there is no feedback at all. It feels like nothing happened or something is broken.

@owncloud/designers @schiesbn

**Comment by acesabe** [comment]
There is a UX error with accessing the "Admin Recovery Password" field in the "Users" page when viewing on an XGA 1024x768 size screen, it hides behind the "Search" field and can only be accessed by enlarging the browser window beyond the horizontal width of the display.

oc7.0.4+dfsg-2 (Debian) (stable) Chromium 34.0.1847.116 / Firefox 30

Suggest left side navbar dynamically scales, entry fields padding/size shrunk and "Search" field takes lower priority/not set to be on top (for tiny/tablet displays)

**Comment by jancborchardt** [comment]
@acesabe this is an unrelated new issue – can you open a separate issue for this please? Would be good if you can also add a screenshot, then I will look into it.

**Comment by acesabe** [comment]
Done https://github.com/owncloud/core/issues/13084

**Comment by jancborchardt** [comment]
@schiesbn 8.1 or 8.2?

**Comment by cmonteroluque** [comment]
@schiesbn ping

**Comment by schiesbn** [comment]
At step 5 you should get a feedback... I will double-check. Yes, we could check the recovery key password right away and show some hint.  @jancborchardt how should this look like? Do we already have a icon for it or something else?

**Comment by schiesbn** [comment]
At the moment it looks like this if you entered the wrong recovery key password and try to change a users password:

![1](https://cloud.githubusercontent.com/assets/1589737/9784511/d5877278-57ab-11e5-808f-fe424faa0926.png)

**Comment by jancborchardt** [comment]
Looks fine to me. @PVince81 please check since you submitted the issue.

**Comment by MorrisJobke** [comment]
> Looks fine to me. @PVince81 please check since you submitted the issue.

He is on vacation

**Comment by jancborchardt** [comment]
@PVince81 not anymore ;)

**Comment by PVince81** [comment]
Looks fine on master.
