### ISSUE TITLE
Parallel upload of chunks

### ISSUE THREAD

**Issue by ogoffart** [owncloud/core#11106]
The owncloud client 1.6 and 1.7 do parallel upload of files, but the chunks of the same file are uploaded sequencially.

I was experimenting trying to upload the chunks in parallel, but it seems there is race condition in the server.  I am getting error 500 with exception `Could not rename part file assembled from chunks`

I suspect `$chunk_handler->isComplete()`  returns true in lib/private/connector/sabre/file.php if all the chunks have been started, but some of them might not be finished.  (And it is likely that the last chunk ends before the second to last, as it is smaller)

@PVince81

**Comment by DeepDiver1975** [comment]
oc8.1

**Comment by guruz** [comment]
Related: https://github.com/owncloud/client/issues/2724#issuecomment-71015263

**Comment by PVince81** [comment]
From what I heard this has already got better ? What to do with this ticket ?

**Comment by ogoffart** [comment]
The client (1.8) work around the problem by never sending what it thinks is the last chunk in parallel.
But the race condition is still there.

**Comment by PVince81** [comment]
This should be fixed by this PR already: https://github.com/owncloud/core/pull/14113
Did you guys try it out with the disabled workaround ?

**Comment by PVince81** [comment]
(fixed in 8.1)

**Comment by ogoffart** [comment]
Ah, no, i did not try against newer version yet.

**Comment by karlitschek** [comment]
So we can close? Right? @ogoffart Can you confirm

**Comment by DeepDiver1975** [comment]
> So we can close?

yes I'd say - please reopen if issues continue to exist
