### ISSUE TITLE
The LDAP section on the admin page is missing a header

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#11116]
### Steps to reproduce

1. Enable LDAP back end
2. Navigate to the admin page.

### Expected behaviour

The LDAP configuration section on the Admin page has a header similar to all other active apps on the page

### Actual behaviour

The LDAP configuration section on the Admin page does not have a header similar to all other active apps on the page

![p75](https://cloud.githubusercontent.com/assets/8480343/4291488/c99c7d52-3dc4-11e4-886c-15183b6a147d.PNG)

**Operating system**:

Ubuntu 12.04

**Web server:**

 Apache/2.2.22 
 
**Database:**

MySql 

**PHP version:**

PHP 5.3

**ownCloud version:** (see ownCloud admin page)

ownCloud Enterprise Edition 7.0.2 (daily) Build:2014-09-16T03:06:50+00:00

**Updated from an older ownCloud or fresh install:**

fresh install

### Server configuration
**Operating system**:

Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:        12.04
Codename:       precise

**Web server:**

 Apache/2.2.22 
 
**Database:**

MySQL 5.5.36

**PHP version:**

PHP 5.3.10-1ubuntu3.13 with Suhosin-Patch (cli) (built: Jul  7 2014 18:54:55)

**ownCloud version:** (see ownCloud admin page)

ownCloud Enterprise Edition 7.0.2 (daily) Build:2014-09-11T03:05:13+00:00

**Updated from an older ownCloud or fresh install:**

fresh install

**List of activated apps:**

<?xml version="1.0"?>
<ocs>
    <meta>
        <status>ok</status>
        <statuscode>100</statuscode>
        <message/>
    </meta>
    <data>
        <apps>
            <element>files</element>
            <element>activity</element>
            <element>admin_migrate</element>
            <element>enterprise_key</element>
            <element>files_locking</element>
            <element>files_sharing</element>
            <element>files_texteditor</element>
            <element>files_trashbin</element>
            <element>files_versions</element>
            <element>firewall</element>
            <element>firstrunwizard</element>
            <element>provisioning_api</element>
            <element>templateeditor</element>
            <element>user_ldap</element>
        </apps>
    </data>
</ocs>

**The content of config/config.php:**

<?php
$CONFIG = array (
  'appstoreenabled' => false,
  'has_internet_connection' => false,
  'instanceid' => 'oc29bc7c8e1f',
  'passwordsalt' => '',
  'trusted_domains' =>
  array (
    0 => '',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.2.1',
  'dbname' => 'jrm_db',
  'dbhost' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin_jrm',
  'dbpassword' => '',
  'installed' => true,
  'license-key' => 'demo-20141011-6a5199a9d642dfa0-eeabfda7',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...

no

**Are you using encryption:** yes/no

yes

### Client configuration
**Browser:**

Chrome

**Operating system:**

windows

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by PVince81** [comment]
Fixed on master (and probably also 8.0.2 already)
![ldap_header](https://cloud.githubusercontent.com/assets/277525/6880860/d59147c0-d543-11e4-9b7c-24ee4fc5441d.png)
