### ISSUE TITLE
2 google drive external storage not supported

### ISSUE THREAD

**Issue by ferdiga** [owncloud/core#11110]
2 different external storages 
![owncloud google drive different](https://cloud.githubusercontent.com/assets/6248560/4289244/ffba0c5a-3db1-11e4-94eb-7c02f7e77ef5.png)
end up with the same data content
![owncloud google drive identical](https://cloud.githubusercontent.com/assets/6248560/4289246/043e8134-3db2-11e4-84e8-45c31dbc0715.png)
and multiple copies of the same directory
![owncloud google drive multiple entries](https://cloud.githubusercontent.com/assets/6248560/4289248/07101346-3db2-11e4-8581-c36051d5ac3f.png)

**Comment by enoch85** [comment]
@DeepDiver1975 This is a planned feature, right?

**Comment by DeepDiver1975** [comment]
we need to focus on external storages in 8.2

**Comment by PVince81** [comment]
@ferdiga are you still seeing this in 8.1.1 ?
In what OC version were you having issues ?

So far I don't see any reason why 2 google drive storages couldn't coexist. The Google library client doesn't seem to be static and should support multiple parallel connections.

**Comment by cmonteroluque** [comment]
@ferdiga would love to have an update regarding 8.1.1 please. Thank you

**Comment by PVince81** [comment]
@ferdiga can you post your the content of your oc_storages table ?
I wonder if it's using the same storage ids in oc_storages.
But from the code it looks like it's using the client id and token: https://github.com/owncloud/core/blob/v8.1.3/apps/files_external/lib/google.php#L75

**Comment by ferdiga** [comment]
I would prefer to send it to you privately

**Comment by ferdiga** [comment]
Ah sorry, 
in 8.0.3 I do not get this problem any more
