### ISSUE TITLE
If you preview a file that does not have any longer access, the view keeps loading forever

### ISSUE THREAD

**Issue by rperezb** [owncloud/core#11126]
### Steps to reproduce
1. Log in as user1 of FF
2. Create a folder "a" and upload an image
3. Share the the folder "a" with user2
4. Log in as user2 on Chrome
5. From user2, access to folder a
6. From user1, unshare the folder a
7. From user2, select to preview the image

### Expected behaviour
An alert message is shown or it´s redirected automatically to the root folder

### Actual behaviour
It keeps loading forever

### Server configuration
daily.owncloud.com/stable//owncloud

**Database:**
SQLite 

**ownCloud version:** (see ownCloud admin page)
ownCloud 7.0.2 (daily) Build:2014-09-17T03:17:46+00:00 
**Updated from an older ownCloud or fresh install:**
NO
**List of activated apps:**
Files
Activity
Documents
Pictures
Calendar
Contacts

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
NO
### Client configuration
**Browser:**
Chrome,  37.0.2062.120
**Operating system:**
Mac 10.9.4
#### ownCloud log (data/owncloud.log)
```
Error 	PHP 	Call to a member function show() on a non-object at /srv/www/daily/stable7/owncloud/lib/private/preview.php#540 	2014-09-17T09:17:03+00:00
Debug 	webdav 	Sabre\DAV\Exception\NotAuthenticated: No basic authentication headers were found 	2014-09-17T09:17:00+00:00 
```

#### Browser log
```
GET http://daily.owncloud.com/stable7/owncloud/core/js/jquery-1.10.0.min.map 404 (Not Found) daily.owncloud.com/:105
GET http://daily.owncloud.com/stable7/owncloud/index.php/core/preview.png?file=…54-56_0034.JPG&x=1280.4000277519226&y=275.0000059604645&a=true&scalingup=0 500 (Internal Server Error) 
```

**Comment by PVince81** [comment]
Still doesn't return 404, but now it redirects to index.php instead... (on stable8)

@LukasReschke @georgehrke @oparoz

**Comment by oparoz** [comment]
The problem is that the file should immediately disappear from the files list, but it probably only does once the cron job is run. I'm not sure if this can be improved, because that would mean real time tracking of all activity.

When clicking on the missing file, the Gallery apps will try to show the previews and they don't all behave the same way when they encounter an error.
In Gallery+, the user should either get a mime icon or an error message, depending on the version.

**Comment by PVince81** [comment]
The old gallery app is obsolete. Does the new gallery app work as expected ? @oparoz

**Comment by PVince81** [comment]
Closing due to lack of feedback, also this issue is very old (OC 7!)
