### ISSUE TITLE
wrong Quota working with S3 Storage Backend (external)

### ISSUE THREAD

**Issue by c10261** [owncloud/core#11156]
We are using Owncloud 7.0.2. RC and have activated Quotas through LDAP through ownCloudQuota attribute.
Furthermore we use an S3 Storage backend with Ceph.
We encounter the following issues (which seem related to each other):

Issue 1: the files stored in S3 are not accounted in the personal area as "used space"
Issue 2: when you delete a file in the S3 area you suddenly have less! space available, whereas it shoul be more
Issue 3: the LDAP quota is not read correctly (should be 8Gb in our exampl)

See attached pictures:
![bildschirmfoto vom 2014-09-18 15 11 07](https://cloud.githubusercontent.com/assets/8819825/4320319/4fb9e718-3f36-11e4-9f42-f93ea79f0b43.png)
![bildschirmfoto vom 2014-09-18 15 10 13](https://cloud.githubusercontent.com/assets/8819825/4320325/5abaf4d6-3f36-11e4-8b03-8b4383ec9bf6.png)
![bildschirmfoto vom 2014-09-18 15 11 25](https://cloud.githubusercontent.com/assets/8819825/4320329/63f9c6a8-3f36-11e4-8256-ec262be22a6b.png)
![bildschirmfoto vom 2014-09-18 15 11 42](https://cloud.githubusercontent.com/assets/8819825/4320331/678d424a-3f36-11e4-9ce0-c2232cc7104a.png)
![bildschirmfoto vom 2014-09-18 15 09 25](https://cloud.githubusercontent.com/assets/8819825/4320333/6b447cc8-3f36-11e4-82ac-8d453a11d6b9.png)

**Comment by PVince81** [comment]
If you're still seeing this issue with 9.0.5 or 9.1.1, please reopen.

See https://github.com/owncloud/core/issues/11156#issuecomment-56157796 for a switch to make external storage data count in a user's quota.
