### ISSUE TITLE
Stray share keys after deleting user

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#11175]
### Steps to reproduce
1. Enable encryption
2. Create two users "user1" and "user2"
3. As "user1" share a folder "sh" with "user2"
4. Check the share keys in `user1/files_encryption/share-keys` and see that "user2" has one
5. As admin, delete user "user2" (and switch page to confirm deletion)
6. Check the share keys again

### Expected result
Share keys from "user2" must be gone

### Actual result
Share keys are still there.

### Versions
ownCloud 7 stable7 (git 7930440b31ee3c23e24e8efdf31697f6d2ed2918)

@schiesbn

**Comment by PVince81** [comment]
Still happens in stable8.

**Comment by PVince81** [comment]
Problem still exists in 8.1.1RC1.
I guess the encryption app doesn't listen to delete user hooks ? @schiesbn

**Comment by schiesbn** [comment]
It will be gone the next time the file gets manipulated. I think this is enough. The share key doesn't do any harm and it would be quite expensive to search all users files_encryption folder recursively for all share keys from user2.

**Comment by PVince81** [comment]
Okay, fine by me.
