### ISSUE TITLE
Encryption recovery key radio button not easy to click

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#11174]
### Steps
1. Enable encryption
2. As admin go to the admin page
3. Try and enable the recovery key by clicking on the label "Enable"

### Expected result
Clicking on the label should work

### Actual result
Need to click on the radio button.

### Versions
OC 6.0.5, OC 7.0.2

It should just be a matter of adding a "label" tag that maps to the radio button.

Tagging as junior job.

**Comment by jancborchardt** [comment]
Fixed via https://github.com/owncloud/core/pull/11337, thanks to @danbartram
