### ISSUE TITLE
[stable7] Stray share key after unshare from self

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#11177]
### Steps to reproduce
1. Enable encryption
2. Create two users "user1" and "user2"
3. As "user1" share a folder "sh" with "user2"
4. Check the share keys in `user1/files_encryption/share-keys` and see that "user2" has one
5. As "user2" unshare the folder "sh" from self.
6. Check the share keys again

### Expected result
Share keys from "user2" must be gone

### Actual result
Share keys are still there.

### Versions
ownCloud 7 stable7 (git 7930440b31ee3c23e24e8efdf31697f6d2ed2918)

@schiesbn

**Comment by karlitschek** [comment]
@schiesbn ping

**Comment by PVince81** [comment]
Only happens on OC 7, works fine in OC 8, closing as it isn't critical.
