### ISSUE TITLE
[stable7] Ext storage share key not updated after changing applicable users

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#11181]
### Steps to reproduce
1. Enable encryption
2. Enable external storage
3. Create two users "user1" and "user2"
4. Mount a external storage as system mount point (for example "Local") and give access to "user1"
5. Create a non-empty file "test.txt" inside
6. Check the share keys inside of `$datadir/files_encryption/share-keys`, see that there is a key for "user1".
7. Change access of the mount point, remove "user1" and add "user2"
8. Check the keys again

### Expected result
Share keys for "user1" are gone.
Share keys for "user2" exist.

### Actual result
Share keys for "user1" still exist even though the user has no more access.
Share keys for "user2" are missing.

### Versions
ownCloud 7 stable7 (7930440b31ee3c23e24e8efdf31697f6d2ed2918)

I talked with @schiesbn and he said there is no hook to find out whenever a mount point has changed, so it is currently not possible to detect such updates.

**Comment by karlitschek** [comment]
@schiesbn is this still open?

**Comment by PVince81** [comment]
Very likely to still be an issue even with 9.0 because we still don't have hooks for when applicables are changed. But hopefully with the revamped external storage code it should be much easier to add these. Setting to 9.1.

**Comment by schiesbn** [comment]
That's basically the same issue as if users are added to groups... We can't magically encrypt the files for new users. One solution is the master key.
