### ISSUE TITLE
Add method to get user list from mount point

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#11180]
The encryption app is currently dependend on `files_external` in some way:
https://github.com/owncloud/core/blob/master/apps/files_encryption/lib/util.php#L1026

The encryption app actually needs to know what users have access to a given mount point and should not need to know about the external storage app.

The suggestion here is to add a new method `getUsersWithAccess()` to the `Storage` class (or alternatively to `Mount`).

External storage implementations (or `ExternalMount`) should then return a list of users or groups that have access to the point point.
`SharedStorage` (or `SharedMount`) implementation can simply return the already known list of users.

Tagged as technical debt.

@icewind1991 @th3fallen @schiesbn @Xenopathic

**Comment by PVince81** [comment]
@patrickjahns we saw a similar method this week in the search_lucene app

**Comment by patrickjahns** [comment]
Yes - it included though two functionalities:
- usersWithAccess
- groupsWithAccess

it would be good to move this to core and refactor the application to use this method and cleanup the application
