### ISSUE TITLE
Mobile experience very flaky due to snap.js issues

### ISSUE THREAD

**Issue by Raydiation** [owncloud/core#11193]
I've been using the new News app release on my mobile phone the last couple of days and the snap.js experience is very flaky:

* If you scroll down with your finger, the menu shows quite often even if you dont want it. To fix this you need to swipe down from the top left to the bottom right corner to not trigger a left swipe which is kinda weird
* The flying loading icon issue, same as in https://github.com/owncloud/notes/issues/64
* The loading icon and hamburger menu overlap the navigation

All in all I think it would be best to get rid of snap.js (if none of these issues can be fixed in the next couple months) and just use the hamburger button to toggle the right menu, you dont need the menu that often and the hamburger menu is reachable pretty well at all times due to the fixed positioning.

PS: please try out the new News app release, also on your mobile and touch devices :)

@jancborchardt @MorrisJobke @jbtbnl @georgehrke @raghunayyar @PVince81 @th3fallen

**Comment by zerosine** [comment]
I too found this very annoying.  The sensitivity was too high.

I was able to adjust the sensitivity a little bit... open snap.js from it's folder:
../core/vendor/snapjs/dist/latest

Under         var settings = self.settings = {
find             minDragDistance

I changed it's value to 145 and it seems much better.

To disable swiping completely, just change value of touchToDrag to false.

**Comment by Raydiation** [comment]
Btw, it seems much better in 8.1. If anything needs to be fixed at all @zerosine 's fix should be added here https://github.com/owncloud/core/blob/master/core/js/js.js#L1222

**Comment by jancborchardt** [comment]
@zerosine can you open a pull request for core with your sensitivity fix? Sounds great

**Comment by finius** [comment]
on my iOS 8.4 devices I can't see any difference with oc 8.1

**Comment by jancborchardt** [comment]
Pull request to fix this at https://github.com/owncloud/core/pull/17785, applying @zerosine’s suggestion. Please test!
