### ISSUE TITLE
[stable7] Ext storage config does not save when tabbing

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#11216]
### Steps to reproduce:
1. Enable external storage
2. Fill in the configuration for SFTP and make sure to use the TAB key when switching fields (make sure to type quickly enough to not trigger saving early)
3. When reaching the "users" field, do not enter anything, just tab out
4. Wait

### Expected result
Configuration saves

### Actual result
Configuration does not save.
Need to click on a field, change one letter back and forth, then exit the field to trigger saving.

Maybe the blur detection in the select2 field does not work

It seems that if you modify the config then tab out it does work, so it's only initially.

### Versions
ownCloud 7 (stable 7 git 984b6a28ac2961d711139852557da922da0a467b)

@owncloud/designers @Xenopathic

**Comment by karlitschek** [comment]
@PVince81 is this fixed with the latest iteration ?

**Comment by PVince81** [comment]
Not yet, still need to review https://github.com/owncloud/core/issues/14904

**Comment by MorrisJobke** [comment]
@PVince81 but this is only IE9+ -.-

**Comment by Xenopathic** [comment]
@MorrisJobke Discuss that on the PR itself - there might be a way around it :smile:
