### ISSUE TITLE
External storage - Usernames with @-symbol are filtered out

### ISSUE THREAD

**Issue by kosli** [owncloud/core#11231]
When trying to use the External Storage feature in the Admin Panel, with "Local" storage, the list displayed in the "Available for" field, filters out all usernames that have an @-symbol in them. 
owncloud community edition v7.0.2

**Comment by Xenopathic** [comment]
@kosli I'm unable to get a user with an empty display name in the first place. The JS of the user management page prevents saving an empty display name, and even if you override the checks the server rejects the change. I think being able to have an empty full name is restricted.
