### ISSUE TITLE
[ext storage] Rely on numeric_id, store config in DB, improve config format

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#11261]
Code like this is just unreadable and difficult to extend: https://github.com/owncloud/core/blob/master/apps/files_external/lib/config.php#L503

The external storage mount points are stored with multi-dimensional arrays:
```php
$mounts[$mountType][$applicableUsers][$mountPointName][$extraField]
```

This needs a lot of code gymnastics to get to the right information and it also increases the risk of misunderstanding and introducing bugs this way.

I suggest to provide a new class to contain that data, like:
```php
class MountPoint {
    private $type; // personal or system
    private $applicable; // array of users/groups to which the mount point applies
    private $mountPath; // path to the mount point in the user's file system
    private $priority;
    // ...
}
```

Hopefully in OC8...

@icewind1991 @Xenopathic

**Comment by PVince81** [comment]
@icewind1991 do you intend to continue working on this ?
Or should we try to hammer the new config options into the existing config ?

I'm teared between fixing the DB first (which isn't trivial) or implementing the options first (which will be duplicated X times in the crappy mount.json format)

**Comment by PVince81** [comment]
Anyway, there is also UI works that need to be done: fixing the UI side to work with the new storage_id instead of passing everything. I made this ticket for that: https://github.com/owncloud/core/issues/12216

The ticket here would rather be for the backend side / storage format.

**Comment by PVince81** [comment]
This is the ticket for moving mount.json to the DB. As discussed with @DeepDiver1975, moving to 8.2.

From what I heard @Xenopathic will work on it soon, so assigning him.

**Comment by PVince81** [comment]
I hope we can totally get rid of the storage id string in the process as it will solve many issues.

**Comment by PVince81** [comment]
@icewind1991 do you think it's possible in any way to make mounting the storages depend on the numeric id instead of storage string id ? How complex would the change be ?

**Comment by icewind1991** [comment]
I think the main usage of the string id atm is the storage<-> cache mapping, currently a storage calculates it's string id, looks up the numeric id and uses that for cache operations.

We would need to adjust every point a where a mount is created and inject the numeric storage id (non trivial for non-files_external since we dont keep track of numeric storage id's for things like home storages)

**Comment by Xenopathic** [comment]
We should try and get rid of `getId()` on the storage implementation itself, it's awkward to have to construct the storage to get its ID. That leads to easy-to-break code such as https://github.com/owncloud/core/blob/master/apps/files_external/lib/config.php#L971-L980. Especially with session-based credentials, some storages will reject being constructed entirely, so we can never correctly get the ID of such storages.

**Comment by PVince81** [comment]
Moving the the database as a first step (independent from old storage ids, for now): https://github.com/owncloud/core/issues/20354

**Comment by PVince81** [comment]
Also the new oc_mounts table will make it possible to do reverse lookups: https://github.com/owncloud/core/issues/15166

**Comment by PVince81** [comment]
9.0 code has the storages in the database and a mounts table, yay!
This is done.
