### ISSUE TITLE
Option to disable paged (partial) file lists

### ISSUE THREAD

**Issue by tomdeck** [owncloud/core#11272]
I would like to have a configuration option on the files app to disable paged downloading of file lists.

When I navigate to a directory, which contains many files and directories, my instinctive method of navigation would be to use Ctrl+F and search for the file name. There is a good chance this won't work, since the file name in question has not been added to the page yet. Unfortunately, I cannot scroll down in the list using Page Down, either. I tried this in Firefox and SeaMonkey, a friend says Chrome is the same. For better usability, I would like to disable the partial download method.

Browsing around in other bug reports, I found out about the variable pageSize in apps/files/js/filelist.js so I could change its value as a workaround, but this is a dirty fix (which will go away as soon as I upgrade...).

**Comment by MorrisJobke** [comment]
As Ctrl + F now highlights our search field https://github.com/owncloud/core/pull/19212 this is solved
