### ISSUE TITLE
[7.0.2] large files upload correctly, but download truncated to 2GB

### ISSUE THREAD

**Issue by adamehirsch** [owncloud/core#11270]
### Steps to reproduce

1. Upload file to OC 7.0.2 larger than 2.0 GiB
2. Notice that file size is correctly reported in the web interface
3. Attempt to download file via web or webDAV
4. Notice that file download is truncated at 2147483647 bytes, exactly the 32-bit integer limit
5. Enable Apache XSendFiles; no change in behavior

### Expected behaviour

I'd expect OwnCloud to correctly serve the entire file that's sitting on the filesystem. Apache serves the plain file correctly on its own, so I'm looking very skeptically at my 32-bit PHP.

### Actual behaviour

File serves truncated to 2.0GB.

### Server configuration

**Operating system**: 32-bit Ubuntu 12.04.5

**Web server:** Apache 2.2

**Database:** MySQL 5.5.38

**PHP version:** PHP 5.3.10-1ubuntu3.14

**ownCloud version:** 7.0.2

**Updated from an older ownCloud or fresh install:** Updated from 6.x

**List of activated apps:** Only the standard set, no additions

**The content of config/config.php:**

```
<?php
$CONFIG = array (
 'instanceid' => 'oc4d1357acac',
 'passwordsalt' => 'PASSWORDSALT',
 'trusted_domains' =>
 array (
 0 => 'junior.veecharge.com',
 ),
 'datadirectory' => '/var/www/owncloud/data',
 'dbtype' => 'mysql',
 'version' => '7.0.2.1',
 'dbname' => 'owncloud',
 'dbhost' => 'localhost',
 'dbtableprefix' => 'oc_',
 'dbuser' => 'owncloud',
 'dbpassword' => 'NEVERYOUMIND',
 'installed' => true,
 'forcessl' => true,
 'loglevel' => '2',
 'theme' => '',
 'maintenance' => false,
 'mail_smtpmode' => 'php',
 'mail_smtpname' => '',
 'mail_smtppassword' => '',
);
```

**Are you using external storage, if yes which one:** Local

**Are you using encryption:** No

### Client configuration

**Browser:** Chrome, Safari, WebDAVFs

**Operating system:** OSX, Linux

#### Web server error log

No errors logged; this is an access log.

```
[23/Sep/2014:12:05:16 -0400] "GET /owncloud/remote.php/webdav/Releases/RaspPi/SDCardImage1_2.img HTTP/1.1" 200 2158296893 "-" "WebDAVFS/3.0.1 (03018000) Darwin/13.3.0 (x86_64)"
```

#### ownCloud log (data/owncloud.log)
```
No lines matching filename
```

**Comment by bantu** [comment]
adamehirsch reports that the upload works and download also fails with the web interface. So this is not necessarily related to WebDAV content length headers. The PHP version in question is supposed to have Large File Support as per https://gist.github.com/bantu/886ac680b0aef5812f71#file-report-txt-L243.

**Comment by bantu** [comment]
@adamehirsch
Can you confirm that this is still happening using the latest version (7.0.4)?
How was ownCloud Server installed?
How is PHP integrated into Apache? E.g. mod_php or FPM.

**Comment by jayenne01** [comment]
I'm confirming this for 7.0.4. on 32bit Debian GNU/Linux 7.8 (wheezy).
Installation was done through buildservice:
http://download.opensuse.org/repositories/isv:/ownCloud:/community/Debian_7.0/
offered using libapache2-mod-php 5.4.36-0+deb7u3

Filesize is correctly show in the web interface. Starting a download via Browser (firefox on windows) offers a file with 2GB for saving.

**Comment by bantu** [comment]
> offers a file with 2GB for saving

This would indicate an incorrect Content-Length header.

**Comment by jayenne01** [comment]
Could this be related to http://nl.php.net/manual/en/function.filesize.php ?

**Comment by bantu** [comment]
@jayenne01 @adamehirsch Can you please explicitly confirm that you have the php5-curl package installed?

**Comment by adamehirsch** [comment]
Sure can:

> dpkg -l | grep php5-curl
ii  php5-curl                           5.3.10-1ubuntu3.16
 CURL module for php5

On Tue, Mar 17, 2015 at 7:39 PM, Andreas Fischer <notifications@github.com>
wrote:

> @jayenne01 <https://github.com/jayenne01> @adamehirsch
> <https://github.com/adamehirsch> Can you please explicitly confirm that
> you have the php5-curl package installed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/core/issues/11270#issuecomment-82654284>.
>



-- 
Adam Hirsch | Journalist | +1.917.720.5469

**Comment by jayenne01** [comment]
Over here, it is:
ii  php5-curl                            5.4.36-0+deb7u3               i386         CURL module for php5

**Comment by jayenne01** [comment]
Just a note: System was upgraded to 8.0.2 today, no change.

**Comment by jayenne01** [comment]
Upgrading the underlying OS from 32bit ot 64bit resolves the Content-Length-Header limit, but isn't a fix for 32bit-platforms, of course.
If someone needs to go that way, ewan dot cc's tutorial on this matter is a rather dangerous and lengthy approach, but with a few snapshots and small corrective measures I was able to change the architecture to 64bit on debian wheezy. Another tutorial for Ubuntu is available, too.

**Comment by bantu** [comment]
@DeepDiver1975 This turns out to be a problem with the PHP Apache SAPI which casts the Content-Length to a PHP integer. Possibly 
https://github.com/php/php-src/blob/master/sapi/apache2handler/sapi_apache2.c#L131

We are able to correctly determine the filesize via curl, which explains why the webinterface shows the filesize correctly. I have also verfied that this works as intented using Apache + FastCGI + PHP FPM.

I don't think there is anything we can do in ownCloud besides documenting this limitation.

**Comment by bantu** [comment]
When X-Sendfile is enabled and used, single files can be downloaded correctly. This contradicts @adamehirsch.

**Comment by bantu** [comment]
A workaround to this problem might be not sending a Content-Length header at all.

**Comment by bantu** [comment]
@adamehirsch @jayenne01 There is a potential fix at #15229 now. Feel free to check it out.

**Comment by adamehirsch** [comment]
I'm puzzled (but very curious!) if you found a way of enabling this with
XSendfiles; I had not, but would love to see details.

On Thu, Mar 26, 2015 at 10:43 AM, Andreas Fischer <notifications@github.com>
wrote:

> @adamehirsch <https://github.com/adamehirsch> @jayenne01
> <https://github.com/jayenne01> There is a potential fix at #15229
> <https://github.com/owncloud/core/pull/15229> now. Feel free to check it
> out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/core/issues/11270#issuecomment-86580769>.
>



-- 
Adam Hirsch | Journalist | +1.917.720.5469

**Comment by bantu** [comment]
@adamehirsch 
```
SetEnv MOD_X_SENDFILE_ENABLED 1
XSendFile On
```
is all I added to the default Debian Apache configuration.

**Comment by adamehirsch** [comment]
Hrm. I added a whole stanza to no good effect on my setup:

<Directory /var/www/owncloud/>
  AllowOverride All
  Options Indexes FollowSymLinks MultiViews

# for allowing static files to be served directly by the webserver. -AEH

 SetEnv MOD_X_SENDFILE_ENABLED 1
 XSendFile On
 XSendFilePath /tmp/oc-noclean
 XSendFilePath /var/www/owncloud/data
</Directory>


On Thu, Mar 26, 2015 at 11:15 AM, Andreas Fischer <notifications@github.com>
wrote:

> @adamehirsch <https://github.com/adamehirsch>
>
> SetEnv MOD_X_SENDFILE_ENABLED 1
> XSendFile On
>
> is all I added to the default Debian Apache configuration.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/core/issues/11270#issuecomment-86599514>.
>



-- 
Adam Hirsch | Journalist | +1.917.720.5469
