### ISSUE TITLE
Files saved from other apps to Files show up as 0 kB

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#11294]
For example when saving an attachment from the Mail app to Files:

The file is all fine and it can be opened/downloaded correctly. But the »size« column of that file shows »0 kB«. Also after refreshes and several days, so I assume it’s never scanned?

cc @PVince81 @icewind1991 @DeepDiver1975 @zinks-

**Comment by PVince81** [comment]
@jancborchardt is this still happening with 7.0.5 or 8.0.2 ?

**Comment by Xenopathic** [comment]
Tested with 8.0.2 and Mail app master, cannot reproduce. Perhaps it's been fixed?

**Comment by jancborchardt** [comment]
Yup, fixed.
