### ISSUE TITLE
Issues connecting to windows domain share - SMB/CIFS - CentOS 6.5 - Windows 2003 Share - smbclient v3.6.9

### ISSUE THREAD

**Issue by gopher49** [owncloud/core#11309]
I'm deploying Own Cloud.  One of my installs is Ubuntu and one is CentOS.  The Ubuntu's install connects to the same SMB share that my CentOS can't connect to.This being with the same credentials.  I'm not sure to which version of SMB client Ubuntu is running but CentOS is running v3.6.9.  If I run the below command on the CentOS' console I'm able to connect to the share at the CLI but I get the below error.. But.  I'm able to at least list the file via the CLI.  OwnCloud won't connect though.  

session request to 192.168.1.247 failed (Called name not present)

smbclient //192.168.1.247/test -U username -W domain

**Comment by PVince81** [comment]
Are you still having issues with 7.0.5 or 8.0.2 ?

I didn't see any ownCloud version mentionned in your original report

**Comment by gopher49** [comment]
I ended up using the Bitnami image for it uses Ubuntu.  I tried a different versions of the SMB client on CentOS and no luck.  I found it better to simply install the OwnCloud client on my windows file server and share out from there...  I have over 100,000 files I'm sharing out and it works really well.
________________________________

**Comment by PVince81** [comment]
Nice, thanks for your feedback.

**Comment by gopher49** [comment]
I do have a client (newest build) that randomly shows a connection error (icon turns black) and I have to exit it and re-open it..  I'll create a bug report for I think this happens with other users too.. In different environments..

I'll create a separate issue on Github for it.
________________________________

**Comment by PVince81** [comment]
Yes, thanks. If you do, please make sure to use the issue template: https://raw.github.com/owncloud/core/master/issue_template.md :smile:
