### ISSUE TITLE
NTFS access rights on Windows share

### ISSUE THREAD

**Issue by JeWe-HS** [owncloud/core#11301]
Connected the Owncloud server to a Windows share (Server 2008 in a Windows domain). Made the Owncloud server (Ubuntu Linux) a member of the domain. Windows share is configured as "SMB / CIFS with OC-login" in Owncloud. Logged in to Owncloud with Active Directory user (testuser, readonly access to the Windows share) and try to delete a file or a folder. Works. At least it seems to. For other users as testuser the files are still there, but not to be seen for the testuser. I have to modify a file or place a new file in the respective folder to make it visible again for testuser.
In the log, I see the message  "NT_STATUS_ACCESS_DENIED deleting remote file ...." when testuser deletes the file, so basically the system is aware of missing access rights.

### Steps to reproduce
1. Make the Owncloud server a member of the Windows domain
2. Configure external storage (SMB / CIFS with OC-login) and connect to the Windows share
3. Log in to Owncloud with a Windows testuser (readonly access to the Windows share)
4. Delete a file or a folder in the share, it seems be gone
5. Create a file in the respective folder with another user who has write access
6. The "deleted" file is back again, testuser can see it

### Server configuration
**Operating system**: Ubuntu 14.04 LTS server

**Web server:**  Apache 2.4

**Database:** MySQL

**PHP version:** 5.5.9

**ownCloud version:** 7.02

**Updated from an older ownCloud or fresh install:** Updated

**List of activated apps:**
Activity
Calendar
Contacts
Deleted files
Documents
External storage support
First Run Wizard
Full Text Search
LDAP user and group backend
PDF Viewer
Pictures
Share Files
Text Editor
Updater
Versions
Video Viewer

**Comment by blizzz** [comment]
Does the issue still exist? cc @Xenopathic

**Comment by Xenopathic** [comment]
cc @icewind1991 

We have a new SMB implementation though, which might have fixed the issue.

**Comment by DeepDiver1975** [comment]
> We have a new SMB implementation though, which might have fixed the issue.

yes - please upgrade to 8.1 and double check - THX

**Comment by PVince81** [comment]
Please try again with 8.1.3 which contains the improved SMB library.
If the problem still happens, please reopen.
