### ISSUE TITLE
Encryption shows wrong file size for shared folders

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#11314]
### Steps to reproduce

1. Install ownCloud with SQLite and username "admin"
2. Create user "test"
3. Enable files_encryption
4. Login and logout as "admin" and as "test"
5. As user "admin", create a folder "WrongCalculation"
6. As user "admin", upload a few files into the folder "WrongCalculation". I took images.
7. Share the folder with the user "test"
8. Login as "test"
9. See the wrong calculated file size

### Expected behaviour
Folder should be shared with the user "test" and show the same file size.

### Actual behaviour
Folder is shared with the user "test" and shows a much bigger file size. If going into the folder, the correct filesize is shown.

![calculationbug](https://cloud.githubusercontent.com/assets/878997/4420065/8242484e-4574-11e4-9173-df1feebec0b2.png)
![2014-09-26_13-59-34](https://cloud.githubusercontent.com/assets/878997/4420095/cfe13f7e-4574-11e4-97d0-2b579eb9cb6d.png)

### Server configuration
**Operating system**: OS X 10.10

**Web server:** Apache/2.4.9 (Unix) 

**Database:** SQLite

**PHP version:** PHP 5.5.17

**ownCloud version:** master as of e5a111b80e20b188efe782c8245d2379596f893c

**Updated from an older ownCloud or fresh install:** Fresh installation

**List of activated apps:** Default and enabled encryption app

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'ocdd5qf0u2cz',
  'passwordsalt' => 'HAblcFK.Cs0Dg3tZR6hrYxjDw6xfTU',
  'secret' => 'n4A0CLPOkkt2a2mbibtELDhHOmV6pvKsE0cu028MGWEmFX2.',
  'trusted_domains' => 
  array (
    0 => 'localhost',
  ),
  'datadirectory' => '/Users/lreschke/Programming/core/data',
  'overwritewebroot' => '/core',
  'dbtype' => 'sqlite3',
  'version' => '7.8.1.0',
  'installed' => true,
);
```

**Are you using encryption:** Yes

### Client configuration
**Browser:** Chrome 37.0.2062.122

**Operating system:** OS X

### Logs
Nothing relevant found

**Comment by PVince81** [comment]
Still happens on stable8. I suspect that the share mount point is using the encrypted size instead of the unencrypted one.

**Comment by PVince81** [comment]
Tested in 8.1.1RC1, the folder size appears correct.
