### ISSUE TITLE
LDAP: long group name does not show in full on mouse over

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#11329]
### Steps to reproduce
1. Enable LDAP
2. Navigate to the admin page and configure
3. Select a group on the group filter that has a name longer than 31 characters

![p104](https://cloud.githubusercontent.com/assets/8480343/4423343/1aad4556-4594-11e4-82b5-c74bacd19306.PNG)
### Expected behaviour

The group name will show in full when I mouse over the group name on the users page
### Actual behaviour

The group name does not show in full when I mouse over the group name on the users page

![p105](https://cloud.githubusercontent.com/assets/8480343/4423352/2af0ec92-4594-11e4-849d-893949f94edd.PNG)
### Server configuration

**Operating system**:

Ubuntu 14

**Web server:**

 Apache/2.2.22 

**Database:**

MySql 

**PHP version:**

PHP 5.3

**ownCloud version:** (see ownCloud admin page)

ownCloud Enterprise Edition 7.0.2 (daily) Build:2014-09-25T03:06:41+00:00

**Updated from an older ownCloud or fresh install:**

fresh install

**List of activated apps:**

<ocs>
    <meta>
        <status>ok</status>
        <statuscode>100</statuscode>
        <message/>
    </meta>
    <data>
        <apps>
            <element>files</element>
            <element>activity</element>
            <element>enterprise_key</element>
            <element>files_locking</element>
            <element>files_sharing</element>
            <element>files_texteditor</element>
            <element>files_trashbin</element>
            <element>files_versions</element>
            <element>firewall</element>
            <element>provisioning_api</element>
            <element>templateeditor</element>
            <element>user_ldap</element>
        </apps>
    </data>
</ocs>

**Are you using external storage, if yes which one:** local/smb/sftp/...

no

**Are you using encryption:** yes/no

no
### Client configuration

**Browser:**

Chrome and firefox

**Operating system:**

windows
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your webserver log here
```

```

#### Browser log
```

Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...

```
```

**Comment by PVince81** [comment]
to be reopened in [user_ldap app repo](https://github.com/owncloud/user_ldap) if still makes sense

@butonic
