### ISSUE TITLE
LDAP: Groups still being displayed after being de-selected on Group Filter tab

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#11330]
### Steps to reproduce

1. Enable LDAP
2. Navigate to the admin page and configure
3. Select a group on the group filter tab
4. Navigate to users page and validate the group shows up
5. Navigate back to the admin page to the group filter tab and deselect the group

![p106](https://cloud.githubusercontent.com/assets/8480343/4423436/e410193c-4594-11e4-819a-b6eb6769ff6d.PNG)

### Expected behaviour

The group will no longer show up on the users page

### Actual behaviour

The group still shows up 

![p105](https://cloud.githubusercontent.com/assets/8480343/4423444/f0bc6032-4594-11e4-9407-909d139289d1.PNG)

### Server configuration
**Operating system**:

Ubuntu 14

**Web server:**

 Apache/2.2.22 
 
**Database:**

MySql 

**PHP version:**

PHP 5.3

**ownCloud version:** (see ownCloud admin page)

ownCloud Enterprise Edition 7.0.2 (daily) Build:2014-09-25T03:06:41+00:00

**Updated from an older ownCloud or fresh install:**

fresh install

**List of activated apps:**

<ocs>
    <meta>
        <status>ok</status>
        <statuscode>100</statuscode>
        <message/>
    </meta>
    <data>
        <apps>
            <element>files</element>
            <element>activity</element>
            <element>enterprise_key</element>
            <element>files_locking</element>
            <element>files_sharing</element>
            <element>files_texteditor</element>
            <element>files_trashbin</element>
            <element>files_versions</element>
            <element>firewall</element>
            <element>provisioning_api</element>
            <element>templateeditor</element>
            <element>user_ldap</element>
        </apps>
    </data>
</ocs>

**Are you using external storage, if yes which one:** local/smb/sftp/...

no

**Are you using encryption:** yes/no

no

### Client configuration
**Browser:**

Chrome and firefox

**Operating system:**

windows

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)

```
Insert your webserver log here
```
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by blizzz** [comment]
@jnfrmarks this should be fixed in master for 8.1. Can you confirm?

**Comment by karlitschek** [comment]
ping @jnfrmarks

**Comment by jnfrmarks** [comment]
@davitol 

Can you please take a look at this as part of your ldap testing?

**Comment by davitol** [comment]
:+1:  Bug solved

{"installed":true,"maintenance":false,"version":"8.1.0.4","versionstring":"8.1 alpha 3","edition":""}

**Comment by blizzz** [comment]
Thx for testing
