### ISSUE TITLE
Sharing becomes extremely slowly

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#11331]
If encryption is enabled and I share one folder with 4 files it takes about 13 seconds until the file is shared. This wasn't the case for ownCloud 7.2. 

I found out that this commit https://github.com/owncloud/core/commit/850542c5d61cd68f46d028e2bbbe21ed69d37c96 (Refactor Cache\Updater to work outside of the users home ) introduced the bad performance. Is it really possible that just because we write the share-keys and the file-keys now to the file cache the whole share process is ~12 times slower? Can we optimize it? @icewind1991 what do you think? Can you have a look at it? Thanks!

@craigpg @karlitschek  I would consider this a gold ticket. I would neither release 7.0.3 nor OC7EE with such a bad performance.

**Comment by PVince81** [comment]
@icewind1991 any update on this ?
