### ISSUE TITLE
Virtual group 'Everyone'

### ISSUE THREAD

**Issue by m8t** [owncloud/core#11332]
As an administrator I had like to share directories with given groups but also with all users. Maintaining a group 'Everyone' at hand is tedious, it can be useful to have a virtual group.

Sharing a file/directory with a public link may not work in this case, since as an administrator I wish all users to see their available shares.

Bests,
Mike

**Comment by SimonBin** [comment]
Possible solution: 

`==> group_every/group_every.php <==`
```php
<?php
namespace OCA\group_every;

class GROUP_EVERY implements \OCP\GroupInterface {
	const GroupName = "All";

	public function implementsActions($actions) { return false; }
	public function inGroup($uid, $gid) { return ($gid === self::GroupName); }
	public function getUserGroups($uid) { return array(self::GroupName); }
	public function groupExists($gid) { return ($gid === self::GroupName); }

	public function getGroups($search = '', $limit = -1, $offset = 0) {
	       if ($offset <= 0 && (!strlen($search) || false !== stripos(self::GroupName, $search))) return array(self::GroupName);
	       return array();
	}

	public function usersInGroup($gid, $search = '', $limit = -1, $offset = 0) {
	       if ($gid !== self::GroupName) return array();
	       return \OC_User::getUsers($search, $limit, $offset);
	}
}
```
`==> group_every/appinfo/version <==`
```
0.0.1
```
`==> group_every/appinfo/info.xml <==`
```xml
<?xml version="1.0"?>
<info>
	<id>group_every</id>
	<name>every user group backend</name>
	<description>A group for everyone on the server
	</description>
	<licence>AGPL</licence>
	<author>AKSW</author>
	<requiremin>4.93</requiremin>
	<shipped>false</shipped>
	<types>
		<authentication/>
	</types>
</info>
```
`==> group_every/appinfo/app.php <==`
```php
<?php
\OC_Group::useBackend(new OCA\group_every\GROUP_EVERY());

**Comment by RomanKreisel** [comment]
This would really be an appreciated feature! :+1:

**Comment by RomanKreisel** [comment]
For those interested: I modified @SimonBin's solution a little bit.
You can download it from https://github.com/RomanKreisel/group_everyone, afterwards just place its files into ${owncloud_path}/apps/group_everyone

**Comment by DeepDiver1975** [comment]
Looks like this feature request was solved with an app - well done - this is the power an spirit of ownCloud!

**Comment by JochenHWezel** [comment]
The solution of @RomanKreisel can't be activated with OwnCloud 10.0.9, currently, but there is a security warning after copying these files into the app directory:
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- group_everyone-master
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\MissingSignatureException
		- Signature data not found.

Raw output
==========
Array
(
    [group_everyone-master] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\MissingSignatureException
                    [message] => Signature data not found.
                )

        )

)
```

@DeepDiver1975 It would also be great, if this plugin could be listed in owncloud's apps catalogue for simpler installation.

BTW: https://github.com/mihpa/group_everyone already provided an improved version 0.05, but this has got the same issue with the security warning
