### ISSUE TITLE
installation wizard gives misleading error when no database is installed

### ISSUE THREAD

**Issue by karyon** [owncloud/core#11339]
this if
https://github.com/owncloud/core/blob/master/lib/private/setup/mysql.php#L11

may be true for a whole number of reasons, not just if the username/password are invalid. in my case, there was no database installed at all, and the error message was not helpful there.

**Comment by jancborchardt** [comment]
@DeepDiver1975 help please ^

**Comment by MorrisJobke** [comment]
https://github.com/owncloud/core/blob/cea70298f276f25c7f3561c9c7622960f4b610b2/lib/private/setup/mysql.php#L11 <- link to the old version.


This is now handled completely different. Please try with a recent version again and feel free to report here and we will reopen the issue, if it still exists.
