### ISSUE TITLE
[Safari] The rename button is located slightly above the normal case

### ISSUE THREAD

**Issue by lmaestro** [owncloud/core#11348]
### Steps to reproduce
1. Place the mouse over a file or folder

### Actual behaviour
 The rename button is located slightly above the normal case
![screen shot 2014-09-29 at 09 45 21](https://cloud.githubusercontent.com/assets/4689430/4438528/3f868bec-47ad-11e4-862b-709aab898d67.png)

### Server configuration
{"installed":"true","version":"7.0.2.2","versionstring":"7.0.2","edition":""}

### Client configuration
browser:Safari

Operating system: Mac 10.9.3

**Comment by Sugaroverdose** [comment]
Looks crappy, but it positions icon on same place in safari 7, chrome 39 and IE11

    #fileList a.action[data-action="Rename"] {
        padding: 16px 14px 17px !important;
        position: relative;
        top: -16px;
        left: -1px;
        float: right;
    }

**Comment by jancborchardt** [comment]
@Sugaroverdose can you submit a pull request for that? Then we can test and discuss. :) thanks!
