### ISSUE TITLE
[7.0.2] Include formatting help / hints in default email templates

### ISSUE THREAD

**Issue by msrex** [owncloud/core#11345]
The email templates would be much more useful if the contained even a small amount of formatting help and / or hints in the file itself so a user has a starting point when editing, both in the editor in the admin page and in the file itself.

Reproduction: 
1. Look at the files.

Expectation:
See some hints on what to do.

**Comment by DeepDiver1975** [comment]
I assume this is about the template editor - right?
Please reopen in https://github.com/owncloud/templateeditor/issues - THX
