### ISSUE TITLE
LDAP Imported Users Using GUID instead of sAMAccount Name for oC Username

### ISSUE THREAD

**Issue by steadhouse** [owncloud/core#11359]
Environment: Dedicated Virtual Server, XenServer
Server: Ubuntu 14.04
Database: MySQL
Client: Chrome/Firefox
OC-Version: 7.0.2
PHP-Version: 5.3.10-ubuntu

The behavior I'm seeing is that after users are imported, the oC user manager shows that the username and storage location for each user is using their Active Directory GUID, rather than sAMAccountname (as specified in the LDAP configuration tool). This behavior seems to have started around our upgrade to 7.0.2. This is partially cosmetic, but it does mean the file path for the user also uses their GUID.

In my tests, I did find that even though the oC user manager reports that their username is 102924u120934821420193812 (for example), the user can still log in with their Active Directory username (shalstead, in this case). 

If I manually correct the owncloudname field in oc_ldap_user_mapping, the user folder and username appears directly. It appears to just be an issue with the user being loaded in to the database. Also, correcting the field directly would be problematic if the user had already uploaded data.

Thanks! I'd be happy to provide more information or our LDAP configuration (if there's a way to easily pull  it for a post).

Thank you in advance!

Stead Halstead
Eugene, OR

**Comment by blizzz** [comment]
Closed for inactivity. Feel free to reopen with more information.
