### ISSUE TITLE
Rename of a shared folder problem

### ISSUE THREAD

**Issue by JustAlex2014** [owncloud/core#11379]
### Steps to reproduce
0. on PC's (sync mode)
1. user A shares folder 'test' with folder B, containig file 'file.txt'
2. test/file.txt syncs with B's PC
3. user A renames folder 'test' in 'renamed_folder' and 'file.txt' in 'file_renamed.txt'
4. on B's PC the folder and file are not renamed
5. on server there are both folder+file mainteined (test+renamed_folder)
6. user B copy 'file2.txt' to 'test' folder (not renamed on his PC)
7. 'file2.txt' is synced in 'renamed_folder' on A's PC and also on server

### Expected behaviour
If any user renames a shared folder/file, the renaming should happen on all connected PC's and also on server.

### Actual behaviour
On user who makes the renaming, the folder is renamed.
On other users the folder has the same name from before renaming.
On server there are two folders, old name+new name

### Server configuration
9.8.2rc1-RedHat-9.8.2-0.23.rc1.el6_5.1

**Web server:**
Server Version: Apache/2.2.27 (Unix)

**Database:**
MySQL 5.5.37

**PHP version:**
5

**ownCloud version:** 
7.0.2 (stable)

**Updated from an older ownCloud or fresh install:**
Updated

**Comment by MorrisJobke** [comment]
@schiesbn @PVince81 I guess the described actual behaviour is the intended one. Or am I wrong?

**Comment by PVince81** [comment]
Yes, works as intended.
It's the "virtual folder" explanation.
