### ISSUE TITLE
User recovers lost password, encryption keys not updated

### ISSUE THREAD

**Issue by ser72** [owncloud/core#11395]
**Expected Behavior**
Keys to be recovered

**Actual Behavior**
User told to recover key on Personal page -- requires old/LOST password

**Steps**
Enable Encryption
Initialize keys
Set email address for userA
userA logs out
userA forgets password and selects the EMAIL LINK to reset password on the login page
userA changes password from link in email
userA is automatically logged in with the new password but gets an error:

![error1](https://cloud.githubusercontent.com/assets/5174383/4491028/e09b9e7c-4a33-11e4-91a7-ac8a40518269.PNG)

userA tries to open a file -- gets error:

![error2](https://cloud.githubusercontent.com/assets/5174383/4491038/05f5475e-4a34-11e4-8fa2-d071766bc369.PNG)

userA goes to Personal page to reset key and realizes they need their old password to reset the key.  Of course, they forgot their old password -- so this data is lost

**Comment by PVince81** [comment]
@schiesbn what's the next step for this in regards to encryption 2.0 ?

**Comment by PVince81** [comment]
Setting to 9.1 to revive the discussion.

Maybe the existence of the master key makes this requirement less important ?

**Comment by PVince81** [comment]
Moving to 9.2, but I'd rather close as "works as expected with the known limitations of the encryption app"

@dragotin @DeepDiver1975 @felixboehm

**Comment by PVince81** [comment]
@pmaier1 what do you think ?
