### ISSUE TITLE
using a db transaction when scanning (external) files with sqlite causes database locked errors

### ISSUE THREAD

**Issue by butonic** [owncloud/core#11391]
I assume the database transaction used to commit updates of the file scanning process in batches causes an sqlite database to lock for extended periods of time, leading to the `database locked error` when another request comes in. With preview generation, background jobs, hooks, search lucene and maybe sync clients coming along that is very likely to happen. The chance that a lock is in place increases with the latency of file scans, meaning scanning a remote files_external storage, such as amazon s3 is highly likely to produce the db lock.

for reference, a little history:
16 Jan 2013 @icewind1991 adding a transaction to improve scan performance https://github.com/owncloud/core/commit/6871a150bd1309af0ca22e45487043d9640bb356

3 Nov 2013 @jancborchardt the original issue https://github.com/owncloud/core/issues/5680
21 Aug 2014 @PVince81 assuming an open db cursor to be the issue https://github.com/owncloud/core/issues/10566

8 Sep 2014 @icewind1991 making the transaction contain even more updates in master https://github.com/owncloud/core/commit/644755df663e8dc295e92700da208a28c13cbaab

30 Sep 2014 @butonic being able to reproduce the issue https://github.com/owncloud/core/issues/11280#issuecomment-57280837
1 Oct 2014 @jancborchardt confirming he was likely using files_external with sqlite https://github.com/owncloud/core/issues/11280#issuecomment-57536862

With 644755df663e8dc295e92700da208a28c13cbaab has added a flag to the scanner that we could use to do without transactions on sqlite. AFAICT atomicity is not the reason for the transaction. Opinions @DeepDiver1975 @karlitschek @schiesbn @icewind1991

**Comment by dragotin** [comment]
https://github.com/owncloud/core/pull/14329

**Comment by MorrisJobke** [comment]
@PVince81 @icewind1991 Isn't this solved by high level file locking that was enabled in 8.2+?

**Comment by PVince81** [comment]
Such issues haven't been reported since a while, so it might be solved by locking, yes.
Also we did add many closeCursor calls.

**Comment by MorrisJobke** [comment]
Okay let's close this here and maybe reopen if this appears again.
