### ISSUE TITLE
Add MediaFire support to external storage

### ISSUE THREAD

**Issue by franciscoluiz** [owncloud/core#11397]
can the OwnCloud, external storage, support mediafire?

https://www.mediafire.com/developers/

**Comment by davidneudorfer** [comment]
👍

**Comment by DeepDiver1975** [comment]
> Or write this as a separate app.
> The external storage app allows for dynamic backend registration since OC 7, which means any app can provide their own backends.

this is indeed the way to go - I honestly see no reason to keep this ticket open in core.
