### ISSUE TITLE
openstack swift backend issues with GUI

### ISSUE THREAD

**Issue by furlongm** [owncloud/core#11402]
Hi,

We have a number of issues with the openstack swift external storage form in owncloud.

1) The form requires an API key. It says it optional, but if you don't add some value, then the test to see if you can connect to swift storage never runs. Adding a bogus value triggers the check of the settings, but this is not intuitive.
2) The form requires a Region, or else it doesn't work. It should use the default region by default. This is the expected behaviour but it doesn't work.
3) The form requires the the Service Name. This is not something that should be filtered on when getting the endpoint in the catalog. It's not needed. It's also not something most users even see when running "keystone catalog". You need to run "keystone --debug catalog" and decode the json to find the Service Name.

**Comment by PVince81** [comment]
@Xenopathic

**Comment by bradjones1** [comment]
> 2) The form requires a Region, or else it doesn't work. It should use the default region by default. This is the expected behaviour but it doesn't work.

This is indeed confusing. Since that was written it appears the region is now optional in the UI form, but the backend validation will reject the configuration for not having a region set.

https://github.com/owncloud/core/blob/5a058f6c0ef64ff0272fcdb58478f9c6611d6819/apps/files_external/lib/Lib/Storage/Swift.php#L155

**Comment by hodyroff** [comment]
Swift will be deprecated in favor of full S3 support. Which also works with Swift inside Openstack.
