### ISSUE TITLE
Some files are unencrypted

### ISSUE THREAD

**Issue by tflidd** [owncloud/core#11405]
### Steps to reproduce
I don't know.

### Expected behaviour
With the encryption enable I expect all files to be encrypted - if there are some files which are not encrypted, there should be some information for the user.

### Actual behaviour
In the "filecache" table, I found numerous entries for my user with encryption=0. I checked one of these files (a textfile) which was really unencrypted in the filesystem and there was no encryption key. Then I edited the textfile on the owncloud-interface and saved it. With that process the file got encrypted and keys were created.
But the filecache-table entry didn't change (still encryption=0). Even a rescan (./occ files:scan username) didn't help.

This is an updated owncloud installation, therefore I cannot say when this file was uploaded or if it even is a file which was not encrypted during the initial encryption. With the filecache-table not being updated, it is impossible to check each single file (some of them might be encrypted in the meantime). But counting the numbers of files and keys, there are probably some more files to be encrypted.

1) I could initiate a new encryption process by setting the migration status to -1. Would this solve the problem?
2) Is there a way to update the filecache table?
3) For new files encryption is working fine, probably this problem was caused by the initial encryption status or a previous version of OC or OC-client.

### Server configuration
**Operating system**: Linux

**Web server:** Apache 2.4.7
**Database:** MySQL 5.5.38
**PHP version:** 5.5.9
**ownCloud version:** 7.0.2
**Updated from an older ownCloud or fresh install:**
Updated

**List of activated apps:**
3rd party: News, Notes
**The content of config/config.php:**

$CONFIG = array (
  'installed' => true,
  'dbtype' => 'mysql',
  'dbname' => 'xxxx',
  'dbuser' => 'xxxxx',
  'dbpassword' => 'xxxxxxx',
  'dbhost' => 'localhost',
  'dbtableprefix' => '',
  'forcessl' => true,
  'blacklisted_files' =>
  array (
    0 => '.htaccess',
  ),
  'trashbin_retention_obligation' => 30,
  'allow_user_to_change_display_name' => true,
  'updatechecker' => true,
  'has_internet_connection' => true,
  'enablebackup' => false,
  'datadirectory' => '/var/www/owncloud/data',
  'version' => '7.0.2.1',
  'installedat' => '1325006970.14',
  'lastupdatedat' => '1329928732.51',
  'loglevel' => '0',
  'logdateformat' => 'F d, Y H:i:s',
  'instanceid' => 'xxxxxxx',
  'maintenance' => false,
  'theme' => '',
  'trusted_domains' =>
  array (
    0 => 'domain1.example.com',
    1 => 'domain2.example.com',
  ),
  'appcodechecker' => false,
  'appstoreenabled' => false,
  'asset-pipeline.enabled' => false,
  'overwritewebroot'=>'/owncloud',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
Yes

### Logs
Nothing concerning this issue, neither apache nor owncloud.

**Comment by MorrisJobke** [comment]
I will close this ticket, because we moved to a completely rewritten encryption layer.

@tflidd Feel free to report back if this problem still exists on 8.1.1+ and we will reopen the ticket. Thanks
