### ISSUE TITLE
"There were unsaved edits" message should have a time to live

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#11412]
### Steps to reproduce

1. Upload a file
2. Edit the file
3. Abandon the edit by clicking the "x" in the right hand corner

### Expected behaviour

The "There were unsaved edits" message times out after "a reasonable period of time".

### Actual behaviour

The "There were unsaved edits" message remains until another edit happens.

![p145](https://cloud.githubusercontent.com/assets/8480343/4509807/24b2b6f4-4b24-11e4-9549-f07b260b59af.PNG)

### Server configuration
**Operating system**:

Ubuntu 14

**Web server:**

 Apache/2.2.22 
 
**Database:**

MySql 

**PHP version:**

PHP 5.5

**ownCloud version:** (see ownCloud admin page)

ownCloud Enterprise Edition 7 Beta2 (testing)

**Updated from an older ownCloud or fresh install:**

fresh install

**List of activated apps:**

**Are you using external storage, if yes which one:** local/smb/sftp/...

yes, S3

**Are you using encryption:** yes/no

no

### Client configuration
**Browser:**

Chrome and firefox

**Operating system:**

windows

#### ownCloud log (data/owncloud.log)
```

```

**Comment by MorrisJobke** [comment]
More general fix is in here: #9787 and should be the way to go. @DeepDiver1975 Should I use the branch of brantje to fix this issue here or is this out of scope yet?

**Comment by MorrisJobke** [comment]
This is a easy step once #13148 is in

**Comment by MorrisJobke** [comment]
Fix is in https://github.com/owncloud/files_texteditor/pull/53
