### ISSUE TITLE
Users are able to move external storage breaking the link

### ISSUE THREAD

**Issue by floweh** [owncloud/core#11429]
Normal Users are able to move external sorage of type local to one of their folders. This leeds to a broken link to the ext storage.

I was using the media folder of a dokuwiki instance on the same server to link it to owCloud. One of the users moved the folder within a windows client, this broke the ext storage link and the dokuwiki media folder as well.

**Comment by PVince81** [comment]
I tried the following:
1. As admin, enable ext storage
2. Allow "SFTP" mounts for users
3. Login as "user1"
4. Mount an SFTP storage to "/sftp"
5. Create a folder "/sftp/test" and upload files
6. Share "/sftp/test" with link and also with the admin
7. In the web UI, create a folder "sub"
8. Move "/sftp" to "sub/"
9. Open the share link
10. Check the share as admin

The link was not broken in stable8, so possibly fixed already.

If you're still seeing the issue in 8.0.2 or 7.0.5, feel free to reopen.
Thanks.
