### ISSUE TITLE
Can't change default avatar

### ISSUE THREAD

**Issue by juju95** [owncloud/core#11420]
Hi everyone, 

I can't find where is the problem
Each time i want to upload a new avatar, the ajax call return 

data: "notsquare"
status: "error"

The same avatar upload function works perfectly fine in Contacts apps ( have a small bug in it, i can't delete an uploaded avatar but seems an other problem )

Where can be the difference ?

When i upload a new avatar, the default one is removed and replaced with the "missing image" browser icon

Thanks in advance for your help

( using 7.0.2 on Debian Apache + mysql )

**Comment by jancborchardt** [comment]
@Kondou-ger do you have any idea? cc @MorrisJobke as well.

**Comment by Kondou-ger** [comment]
Looks like something is wrong with cropping the image … Probably something server side, because the server doesn't even ask for cropping data via jcrop, but immediately errors out …

@juju95 what if you upload an avatar that's already cropped and has square dimensions?

**Comment by MorrisJobke** [comment]
@juju95 Please reopen if this isn't fixed for you with 8.1
