### ISSUE TITLE
Error connecting external Storage: SabreDAV

### ISSUE THREAD

**Issue by Pencl** [owncloud/core#11436]
External Storage can not be registered throwing the following Error:

curl_setopt_array(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set at /rootdir/3rdparty/sabre/dav/lib/Sabre/DAV/Client.php#466

It appeared trying to Connect a Sabre Dav Server with own cloud 7.0.2

**Comment by oparoz** [comment]
Not sure if OC8 moved to sabredav 2.0, but on OC7, people can use this fix
https://github.com/fruux/sabre-dav/issues/330#issuecomment-49549813

The problem was also affecting owncloud to owncloud sharing.

**Comment by PVince81** [comment]
@evert is the workaround in Sabre 2.1 ? If yes, then it would work in the upcoming OC 8.1

**Comment by evert** [comment]
Well, redirection handling has changed completely in the new client, and it doesn't have that problem anymore. So: yes =)

**Comment by PVince81** [comment]
Closing hence. The upcoming OC 8.1 was upgraded to Sabre 2.1 which contains the fix.
