### ISSUE TITLE
Empty version created when encryption app is enabled

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#11431]
### Steps to reproduce:
1. Enable encryption
2. Using the web UI, create a new empty file "test.txt", leave it empty
3. Setup the sync client, let it download the file
4. Modify "test.txt" locally and add some contents, let it be synced
5. Modify "test.txt" locally again (do not open the versions dropdown yet), let it be synced
6. Now check the versions dropdown in the web UI

### Expected result
Only one version visible in the dropdown.

### Actual result
Two versions in the dropdown, the oldest one appears with a broken preview and cannot be downloaded. It seems it is the zero size file.

### Versions
ownCloud 8 git master (6e991a53ec5bc2b70328ffbb7fd3e43811ccb426)
Sync client 1.6.3
Mariadb 5.5.33

@schiesbn

**Comment by labiculum** [comment]
Thanks for the impressive diagnosis @PVince81. Been following this bug after I noticed that same behaviour myself. Any progress on bringing this to the current version? Safely collaborating on documents is pretty much killed by this bug.

**Comment by PVince81** [comment]
@schiesbn what do you think ?

**Comment by PVince81** [comment]
Still happens on stable8 / 8.0.3RC1

**Comment by PVince81** [comment]
Works properly in 8.2RC1
