### ISSUE TITLE
LDAP Configuration: The user has to click the "Edit raw filter instead" down arrow to get the selected groups populated.

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#11447]
### Steps to reproduce

1. Enable LDAP app
2. Go to admin page and configure LDAP server
3. Click on the Group Filter tab
4. Select a group
5. No groups are shown as found
6. Click the down arrow for the "Edit raw filter instead" option
7. No groups show up
8. Close the "Edit raw filter instead" 
9. Groups show up

### Expected behaviour

The user should not have to click the "Edit raw filter instead" down arrow to get the selected groups populated.

### Actual behaviour

The user has to click the "Edit raw filter instead" down arrow to get the selected groups populated.

![p155](https://cloud.githubusercontent.com/assets/8480343/4534406/1d46bc3e-4da5-11e4-9294-ac3b8656b509.PNG)

![p156](https://cloud.githubusercontent.com/assets/8480343/4534408/1fd2635e-4da5-11e4-82e3-0837b268fba6.PNG)

![p157](https://cloud.githubusercontent.com/assets/8480343/4534409/2178ca36-4da5-11e4-839e-bf3322f3f6df.PNG)

![p158](https://cloud.githubusercontent.com/assets/8480343/4534410/2374c740-4da5-11e4-8262-5c6a7d8dd5a6.PNG)

### Server configuration
**Operating system**:

Ubuntu 14

**Web server:**

 Apache/2.2.22 
 
**Database:**

MySql 

**PHP version:**

PHP 5.5

**ownCloud version:** (see ownCloud admin page)

ownCloud Enterprise Edition 7.0.2 (daily) Build:2014-10-05T03:03:08+00:00

**Updated from an older ownCloud or fresh install:**

fresh install

**List of activated apps:**

Enabled:
 - activity
 - enterprise_key
 - files
 - files_external
 - files_locking
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - firewall
 - provisioning_api
 - templateeditor
 - user_ldap
 - windows_network_drive
Disabled:
 - admin_audit
 - external
 - files_antivirus
 - files_encryption
 - files_ldap_home
 - files_sharing_log
 - firstrunwizard
 - sharepoint
 - user_external
 - user_shibboleth
 - user_webdavauth

**Are you using external storage, if yes which one:** local/smb/sftp/...

no

**Are you using encryption:** yes/no

no

### Client configuration
**Browser:**

Chrome

**Operating system:**

windows

#### ownCloud log (data/owncloud.log)

@craigpg @MTRichards : It would be nice if this could get into oC7 Launch.

**Comment by jancborchardt** [comment]
@blizzz for LDAP

**Comment by MorrisJobke** [comment]
Is fixed with #15492
