### ISSUE TITLE
LDAP drop down content appears as a text box when browser scrolls down

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#11444]
### Steps to reproduce
1. Enable LDAP app
2. Go to admin page and configure LDAP server
3. Click on the "User Filter" tab
4. Click the drop down arrow for "only from those groups"
5. Page down in the browser
### Expected behaviour

The drop down should either close or not be visible
### Actual behaviour

The dropdown content appears as a text box when the browser scrolls down

![p153](https://cloud.githubusercontent.com/assets/8480343/4534199/034c04ee-4da3-11e4-8ce4-59ca628ee692.PNG)
### Server configuration

**Operating system**:

Ubuntu 14

**Web server:**

 Apache/2.2.22 

**Database:**

MySql 

**PHP version:**

PHP 5.5

**ownCloud version:** (see ownCloud admin page)

ownCloud Enterprise Edition 7.0.2 (daily) Build:2014-10-05T03:03:08+00:00

**Updated from an older ownCloud or fresh install:**

fresh install

**List of activated apps:**

Enabled:
- activity
- enterprise_key
- files
- files_external
- files_locking
- files_sharing
- files_texteditor
- files_trashbin
- files_versions
- firewall
- provisioning_api
- templateeditor
- user_ldap
- windows_network_drive
  Disabled:
- admin_audit
- external
- files_antivirus
- files_encryption
- files_ldap_home
- files_sharing_log
- firstrunwizard
- sharepoint
- user_external
- user_shibboleth
- user_webdavauth

**Are you using external storage, if yes which one:** local/smb/sftp/...

no

**Are you using encryption:** yes/no

no
### Client configuration

**Browser:**

Chrome

**Operating system:**

windows

**Comment by PVince81** [comment]
@blizzz

**Comment by blizzz** [comment]
I think it's a bug in the multiselect plugin we use. I'd consider it low severity, though: it sounds to be ugly but happen rather seldom.

**Comment by PVince81** [comment]
@blizzz the plugin was written by us (by @icewind1991 actually), so feel free to fix it if needed

**Comment by blizzz** [comment]
no, it is http://www.erichynds.com/jquery/jquery-ui-multiselect-widget/

**Comment by PVince81** [comment]
@blizzz did the new LDAP wizard fix this ?

**Comment by blizzz** [comment]
No, it's the same plugin.

**Comment by blizzz** [comment]
No, it's the same plugin

**Comment by PVince81** [comment]
moved to grouped UX ticket: https://github.com/owncloud/user_ldap/issues/69
