### ISSUE TITLE
User can't see all selected groups  when configuring LDAP Group filter tab

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#11446]
### Steps to reproduce
1. Enable LDAP app
2. Go to admin page and configure LDAP server
3. Click on the Group Filter tab
4. Select  4 or 5 groups so that the text is greater than the size of the text box
### Expected behaviour

The user can see all groups
### Actual behaviour

The user can't see all groups

![p157](https://cloud.githubusercontent.com/assets/8480343/4534330/759548de-4da4-11e4-9cac-ed6b7255133e.PNG)
### Server configuration

**Operating system**:

Ubuntu 14

**Web server:**

 Apache/2.2.22 

**Database:**

MySql 

**PHP version:**

PHP 5.5

**ownCloud version:** (see ownCloud admin page)

ownCloud Enterprise Edition 7.0.2 (daily) Build:2014-10-05T03:03:08+00:00

**Updated from an older ownCloud or fresh install:**

fresh install

**List of activated apps:**

Enabled:
- activity
- enterprise_key
- files
- files_external
- files_locking
- files_sharing
- files_texteditor
- files_trashbin
- files_versions
- firewall
- provisioning_api
- templateeditor
- user_ldap
- windows_network_drive
  Disabled:
- admin_audit
- external
- files_antivirus
- files_encryption
- files_ldap_home
- files_sharing_log
- firstrunwizard
- sharepoint
- user_external
- user_shibboleth
- user_webdavauth

**Are you using external storage, if yes which one:** local/smb/sftp/...

no

**Are you using encryption:** yes/no

no
### Client configuration

**Browser:**

Chrome

**Operating system:**

windows

**Comment by PVince81** [comment]
moved to grouped UX ticket: https://github.com/owncloud/user_ldap/issues/69
