### ISSUE TITLE
user_external SMB authentication fails when password contains '=' character

### ISSUE THREAD

**Issue by github-pfaff** [owncloud/core#11443]
### Steps to reproduce
1. configure owncloud to use smb user_external authentication
2. create an smb account that has an '=' character in the password
3. attempt owncloud login

### Expected behaviour
login should succeed

### Actual behaviour
login fails

### Server configuration
centos 6.5

**Web server:**
apache from centos 6.5 core repo
httpd-2.2.15-31.el6.centos.x86_64

**Database:**
mysql from centos 6.5 core repo
mysql-server-5.1.73-3.el6_5.x86_64
mysql  Ver 14.14 Distrib 5.1.73, for redhat-linux-gnu (x86_64) using readline 5.1

**PHP version:**
php-5.4.16 from centos 6.5 scl repo
php54-1.1-5.el6.centos.alt.x86_64

**ownCloud version:** (see ownCloud admin page)
owncloud 7.0.2 stable

**Updated from an older ownCloud or fresh install:**
fresh install

**List of activated apps:**
only default apps

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '525e9e0a528ed',
  'passwordsalt' => '',
  'datadirectory' => '/1/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.2.1',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin',
  'dbpassword' => '',
  'installed' => true,
  'forcessl' => true,
  'maxZipInputSize' => 838860800,
  'allowZipDownload' => true,
  'loglevel' => '3',
  'theme' => '',
  'maintenance' => false,
  'user_backends' => 
  array (
    0 => 
    array (
      'class' => 'OC_User_SMB',
      'arguments' => 
      array (
        0 => 'mysmbserver',
      ),
    ),
  ),
  'trusted_domains' => 
  array (
    0 => 'owncloud.mydomain.ca',
  ),
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
smb

**Are you using encryption:** yes/no
no

### Client configuration
**Browser:**
various: firefox, chrome, safari

**Operating system:**
various: linux, macos, windows

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by Xenopathic** [comment]
This is a problem that should be raised in owncloud/apps, not here in core (if this is still an issue, of course). Closing.
