### ISSUE TITLE
Grammar suggestions for LDAP text box titles

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#11445]
### Steps to reproduce

1. Enable LDAP app
2. Go to admin page and configure LDAP server
3. The grammar needs some wordsmithing on the user filter tab and the group filter tab. 

### Suggestions:

"only" gets changed to "Only"
"those" gets changed to "these"

### Server configuration
**Operating system**:

Ubuntu 14

**Web server:**

 Apache/2.2.22 
 
**Database:**

MySql 

**PHP version:**

PHP 5.5

**ownCloud version:** (see ownCloud admin page)

ownCloud Enterprise Edition 7.0.2 (daily) Build:2014-10-05T03:03:08+00:00

**Updated from an older ownCloud or fresh install:**

fresh install

**List of activated apps:**

Enabled:
 - activity
 - enterprise_key
 - files
 - files_external
 - files_locking
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - firewall
 - provisioning_api
 - templateeditor
 - user_ldap
 - windows_network_drive
Disabled:
 - admin_audit
 - external
 - files_antivirus
 - files_encryption
 - files_ldap_home
 - files_sharing_log
 - firstrunwizard
 - sharepoint
 - user_external
 - user_shibboleth
 - user_webdavauth

**Are you using external storage, if yes which one:** local/smb/sftp/...

no

**Are you using encryption:** yes/no

no

### Client configuration
**Browser:**

Chrome

**Operating system:**

windows

**Comment by karlitschek** [comment]
@blizzz please add to the new wizard

**Comment by blizzz** [comment]
Yup, was one of the reqs. Done in https://github.com/owncloud/core/commit/c7771c407868ea8828cb6385ed44457ce9f5171c (feature branch)

**Comment by blizzz** [comment]
Fixed in https://github.com/owncloud/core/pull/15492

**Comment by MorrisJobke** [comment]
The mentioned PR is merged
