### ISSUE TITLE
Error sharing webDAV file  from valid http share when invalid https webDAV share is also created

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#11468]
### Steps to reproduce

1. Enable external storage app
2. Navigate to the admin page and configure two webDAV external storage mounts
3. The first one is over http - all is green
4. The second one is to the same system but over https - all is red
5. Navigate to files
6. Both mounts are visible; click on http
7. Click on a file share a link

### Expected behaviour

A link is created that can be shared

### Actual behaviour

Get a fatal ssl cert error

![p161](https://cloud.githubusercontent.com/assets/8480343/4546873/a7c104a8-4e47-11e4-8802-927d254462e0.PNG)

I did validate that if I delete the https mount that the link gets created

### Server configuration
**Operating system**:

CentOS release 6.5 (Final)

**Web server:**

 Apache/2.2.22 
 
**Database:**

posix 

**PHP version:**

PHP 5.5

**ownCloud version:** (see ownCloud admin page)

ownCloud Enterprise Edition 7 Beta2 (testing)

**Updated from an older ownCloud or fresh install:**

upgrade from beta1 to beta2

**List of activated apps:**

Enabled:
 - activity
 - enterprise_key
 - files
 - files_external
 - files_locking
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - firewall
 - templateeditor
 - user_ldap
Disabled:
 - admin_audit
 - external
 - files_antivirus
 - files_encryption
 - files_ldap_home
 - files_sharing_log
 - firstrunwizard
 - provisioning_api
 - sharepoint
 - user_external
 - user_shibboleth
 - user_webdavauth
 - windows_network_drive

**Are you using external storage, if yes which one:** local/smb/sftp/...

yes, webDAV

**Are you using encryption:** yes/no

no

### Client configuration
**Browser:**

Chrome

**Operating system:**

windows

#### ownCloud log (data/owncloud.log)

There is nothing of interest in the log

**Comment by DeepDiver1975** [comment]
@jnfrmarks may I ask you to reevaluate the current status of this issue? THX

**Comment by jnfrmarks** [comment]
Working as expected in 8.1.  Closing
