### ISSUE TITLE
Can't create webDAV mount using https

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#11463]
### Steps to reproduce

1. Enable external storage app
2. Navigate to the admin page and configure two webDAV external storage mounts
3. The first one is over http - all is green
4. The second one is to the same system but over https - all is red

### Expected behaviour

Both mounts should be green

### Actual behaviour

The https mount is red

![p159](https://cloud.githubusercontent.com/assets/8480343/4544536/16443a30-4e34-11e4-971a-ecb328cdb9d9.PNG)

### Server configuration
**Operating system**:

Ubuntu 12

**Web server:**

 Apache/2.2.22 
 
**Database:**

MySql 

**PHP version:**

PHP 5.3

**ownCloud version:** (see ownCloud admin page)

ownCloud Enterprise Edition 7.0.2 (daily) Build:2014-10-05T03:03:08+00:00

**Updated from an older ownCloud or fresh install:**

fresh install

**List of activated apps:**

Enabled:
 - activity
 - enterprise_key
 - files
 - files_external
 - files_locking
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - firewall
 - firstrunwizard
 - templateeditor
Disabled:
 - admin_audit
 - external
 - files_antivirus
 - files_encryption
 - files_ldap_home
 - files_sharing_log
 - provisioning_api
 - sharepoint
 - user_external
 - user_ldap
 - user_shibboleth
 - user_webdavauth
 - windows_network_drive

**Are you using external storage, if yes which one:** local/smb/sftp/...

no

**Are you using encryption:** yes/no

no

### Client configuration
**Browser:**

Chrome

**Operating system:**

windows

#### ownCloud log (data/owncloud.log)

There is nothing of interest in the log

@MTRichards @craigpg :  gold ticket?

**Comment by PVince81** [comment]
@jnfrmarks ping :smile:

**Comment by PVince81** [comment]
@jnfrmarks were you able to verify this ?

**Comment by PVince81** [comment]
This should work for valid certifcates => close.
