### ISSUE TITLE
"Storage not available" message displayed until browser refresh

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#11467]
### Steps to reproduce

1. Enable external storage app
2. Navigate to the admin page and configure two webDAV external storage mounts
3. The first one is over http - all is green
4. The second one is to the same system but over https - all is red
5. Navigate to files
6. Both mounts are visible; click on https
7. User gets a "storage not available" error but the error message never goes away unless I refresh the browser

### Expected behaviour

Message should timeout or be removed if the user changes pages

### Actual behaviour

The error message is displayed until the browser is refreshed

![p160](https://cloud.githubusercontent.com/assets/8480343/4546851/65e670e0-4e47-11e4-8349-add4baac9078.PNG)

### Server configuration
**Operating system**:

CentOS release 6.5 (Final)

**Web server:**

 Apache/2.2.22 
 
**Database:**

posix 

**PHP version:**

PHP 5.5

**ownCloud version:** (see ownCloud admin page)

ownCloud Enterprise Edition 7 Beta2 (testing)

**Updated from an older ownCloud or fresh install:**

upgrade from beta1 to beta2

**List of activated apps:**

Enabled:
 - activity
 - enterprise_key
 - files
 - files_external
 - files_locking
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - firewall
 - templateeditor
 - user_ldap
Disabled:
 - admin_audit
 - external
 - files_antivirus
 - files_encryption
 - files_ldap_home
 - files_sharing_log
 - firstrunwizard
 - provisioning_api
 - sharepoint
 - user_external
 - user_shibboleth
 - user_webdavauth
 - windows_network_drive

**Are you using external storage, if yes which one:** local/smb/sftp/...

yes, webDAV

**Are you using encryption:** yes/no

no

### Client configuration
**Browser:**

Chrome

**Operating system:**

windows

#### ownCloud log (data/owncloud.log)

There is nothing of interest in the log

**Comment by Xenopathic** [comment]
Timeout for notifications was merged: #13148
