### ISSUE TITLE
File preview is in way too small of a font

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#11469]
### Steps to reproduce

1. Share a text file by link
2. Copy the link and paste it into a browser (I tried both chrome and firefox)

### Expected Behavior

The file preview is readable

### Actual Behavior

The file preview is not readable

![p162](https://cloud.githubusercontent.com/assets/8480343/4547022/0eb13628-4e49-11e4-95bd-ef52402f352f.PNG)

### Server configuration

**ownCloud version:** (see ownCloud admin page)

ownCloud 7.0.2 (daily) Build:2014-10-07T03:17:38+00:00

@MTRichards @craigpg - gold ticket?

**Comment by oparoz** [comment]
Yep, it's ridiculously small... 
`$fontSize = 5; //5px`
https://github.com/owncloud/core/blob/master/lib/private/preview/txt.php#L39

In GD2, the font size should be expressed in points

**Comment by MorrisJobke** [comment]
Let me play around with this a bit, once I have time.

**Comment by georgehrke** [comment]
I guess the question here is we really want a image-based preview of text on the public sharing site.
If you increase the font-size, it get's useless in the filelist, because the preview stops after a few chars.

**Comment by MorrisJobke** [comment]
@georgehrke Why not scale it with the dimension ? ;)

**Comment by oparoz** [comment]
@georgehrke - I agree, if it's not too much trouble, then it would be best to have a text based preview on public shares. Also, the text would reflow nicely.
As for the thumbnails. I'm not sure it makes sense to have a preview. It's not like we can really tell text files apart like we can with office documents.

**Comment by oparoz** [comment]
owncloud/core#15652 implements a text preview of text files which are publicly shared, avoiding the font size problems.

**Comment by MorrisJobke** [comment]
Fixed in #15635
