### ISSUE TITLE
owncloud packages from suse have missing dependencies on centos 7

### ISSUE THREAD

**Issue by rhagu** [owncloud/core#11489]
A centos 7 minimal install fails with these missing dependencies: 

Fehler: Paket: owncloud-7.0.2-12.1.noarch (isv_ownCloud_community)
            Benötigt: php-pear-Net-Curl
Fehler: Paket: owncloud-7.0.2-12.1.noarch (isv_ownCloud_community)
            Benötigt: php-pear-MDB2-Driver-mysqli

to install owncloud using this howto:

http://software.opensuse.org/download/package?project=isv:ownCloud:community&package=owncloud

cd /etc/yum.repos.d/
wget http://download.opensuse.org/repositories/isv:ownCloud:community/CentOS_CentOS-7/isv:ownCloud:community.repo
yum install owncloud

**Comment by jnweiger** [comment]
should be fixed with 7.0.4 -- tested with a CentOS 7 minimal docker image.
