### ISSUE TITLE
Add unit tests / integration tests that run against a LDAP server

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#11488]
Not sure if this is in scope of core or rather automation.

Thing is, the external storage app is able to run tests against different backends (currently all disabled but can be run locally).

It would be good to have such similar tests that can be run against a test LDAP instance.

@blizzz what do you think ?

**Comment by blizzz** [comment]
Available in https://github.com/owncloud/core/tree/master/apps/user_ldap/tests/integration

and larger improvements come within #17464 

Now we need more tests :) but the foundation is here :)
