### ISSUE TITLE
CLI tool to clear/force refresh LDAP sync

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#11483]
Add a new command line operation:
`./occ ldap:forcerefresh`.

This operation would do as follows:
1) Clear the LDAP cache in the /tmp directory
2) Clear lastRun for the last LDAP sync job
3) Automatically re-run the LDAP sync job
4) Delete the last run preferences key (if that one still exists, seems it doesn't)

Would be very useful when debugging but also to troubleshoot some cases where previously wrong settings might have already populated the cache and a refresh is necessary.

@blizzz what do you think ?

**Comment by PVince81** [comment]
@blizzz do we still need this ? I found that lately setting the interval to 60 seconds solved most issues.

**Comment by blizzz** [comment]
then let's close it. I work with a low cache ttl as well, and don't have a need for this feature either.

**Comment by boweeb** [comment]
> I found that lately setting the interval to 60 seconds solved most issues.

What interval?  Where can I find this setting?

**Comment by DevGoslinga** [comment]
You can find the setting here:
https://docs.nextcloud.com/server/11/admin_manual/configuration_user/user_auth_ldap_api.html
ldapCacheTTL set interval in seconds
