### ISSUE TITLE
Corrupt files (wrong md5 checksum) with external storage

### ISSUE THREAD

**Issue by omicloud** [owncloud/core#11497]
We are using the external storage function and sometimes the files we download e.g. via shared links are corrupt. The md5 cehcksums from the original file and the downloaded file do not match.
We first noticed the problem in version 7.0.2. Every download was corrupt there. Then we made a downgrade to 7.0. The problem still exists but it only happens every 5th to 10th download.
The external storage is based on a Windows Server 2012 with Windows filesharing. Mounted in Owncloud with SMB / CIFS.
When we use the local storage of the Owncloud server, all files are fine.
Files are still fine after upload to the storage via web interface, the problem only appers when the files are downloaded.

**Comment by PVince81** [comment]
Did you check if the corruption only happens on SMB ? Does it occur for files outside of it ?

**Comment by PVince81** [comment]
Please try again with 8.1.3, it contains an updated SMB library that might hopefully help.

If you still have data corruption, feel free to reopen.
