### ISSUE TITLE
LDAP Group filter fast clicking keeps old filter / async call issue

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#11504]
### Steps to reproduce
1. Setup a LDAP server
2. Enable LDAP app
3. Go to admin page
4. Fill out the first page
5. Click on "User filter", let it load
6. Click on "Group filter"
7. Very quickly, while the group count is being calculated, open the dropdown "only objects of these classes" and select the matching group (in my case it was "posixGroup")
8. Try to uncheck then recheck "posixGroup"

### Expected result
When "posixGroup" is checked, groups are found

### Actual result
Sometimes the group count is correct and sometimes it's zero.
It seems that if you check or uncheck "posixGroup" while the ajax check is running, it will cause the wrong filter to be saved

### More info
Observed on stable7 (24dbdd2b8edc8a9dc83c5763f7ef6e357329aed3)

One possible solution would be to disable the fields while the ajax calls are running, or cancel the running ajax calls before running the new set of calls.

@blizzz @jnfrmarks

**Comment by blizzz** [comment]
Could confirm it with current 8.

**Comment by blizzz** [comment]
Should be fixed with https://github.com/owncloud/core/pull/15492, the save action is only triggered after closing the select thing, not on clicking.

**Comment by MorrisJobke** [comment]
Reopen this please if this is not fixed with #15492
