### ISSUE TITLE
Mount external storage from files app UI directly

### ISSUE THREAD

**Issue by kaystrobach** [owncloud/core#11517]
Please understand the question from the user point of view

![image](https://cloud.githubusercontent.com/assets/1185776/4591713/ddfff7d8-5070-11e4-8c53-7894b188a282.png)

I know, that i can add storages in the personal profile ... but that's still scary

![image](https://cloud.githubusercontent.com/assets/1185776/4591737/662cc8c0-5071-11e4-8df4-a99f04a5bf66.png)

**Comment by jancborchardt** [comment]
Now we have an anchor for the external storage setting.

We should add a button (like the »New« button in the normal All files view) saying »Add external storage« which leads to the anchor on the Personal settings page.

Who can do that? @PVince81 @LukasReschke please mention a relevant person.

**Comment by jancborchardt** [comment]
@DeepDiver1975 @PVince81 there’s current external storage work going on, isn’t there? Might be good to keep this in mind for that. Basically the whole config UI could be moved directly to the files app so that there is not this strange disconnect.

**Comment by PVince81** [comment]
The external storage code has been improved significantly in 9.0, and so did the API endpoints.
It should now be much easier to make it possible to create mount points from other places like the file list.

Since we're past feature freeze, moving this to 9.1.

**Comment by PVince81** [comment]
and also the "New" menu code was extracted and made portable in 8.2.2, so it should be possible to create a customized one here :smile:

**Comment by PVince81** [comment]
@pmaier1
