### ISSUE TITLE
Share dropdown, checkboxes misaligned in Chrome

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#11515]
Observed on git master 660e9c4012e49240a8e60186e864dde3ec3488fe and also 7.0.2 EE beta2
With Chromium Version 37.0.2062.94 (290621) (64-bit) on openSUSE 13.1

![checkboxshift](https://cloud.githubusercontent.com/assets/277525/4591173/e4dc4d5c-5068-11e4-983e-5f3604a8d8bc.png)

This is a regression from 7.0.2.

@owncloud/designers

**Comment by jancborchardt** [comment]
Fix at https://github.com/owncloud/core/pull/14967

**Comment by MorrisJobke** [comment]
@PVince81 Backport needed?

**Comment by PVince81** [comment]
No, too small and low
