### ISSUE TITLE
Problem(s) with using external storages

### ISSUE THREAD

**Issue by kaystrobach** [owncloud/core#11516]
issue creation suggested via your Twitter channel

external storages connection problems
* if i add dropbox account as external storage with some directories and one file iOS and Android client first connection fails
* in the OSX / Win Desktop client, the sync slows down

ideas:
* as we have cronjobs, the external dir sync maybe done with the job and cached?
* add option to exclude folders

**Comment by PVince81** [comment]
Closing due to lack of feedback. Please try again with 9.0.2 where many Dropbox issues were solved
