### ISSUE TITLE
cannot share folder with groups

### ISSUE THREAD

**Issue by vasyugan** [owncloud/core#11526]
I have mounted a dropbox folder in ownCloud, which causes a number of issues. 

The one I am struggling with right now is, that owncloud won't let me share it with a group. When I start typing in the share dialogue, I only see names of individual users popping up but not the group with whom I intend to share. I have seen the same with non-external folders before, but not as persistently. I have tried clearing the cache, logging out, running the cron job an extra time, but the result remains unchanged.

I would suppose that this message which I found in owncloud.log is related:

{"reqId":"543a55f79258c","app":"PHP","message":"Undefined offset: 24 at \/var\/www\/user_web\/chroot\/htdocs\/org\/www\/oc\/lib\/private\/share\/share.php#1390","level":3,"time":"2014-10-12T10:20:39+00:00","method":"GET","url":"\/oc\/index.php\/core\/ajax\/share.php?fetch=getItemsSharedStatuses&itemType=file"}

**Comment by PVince81** [comment]
@vasyugan are you still seeing this with 8.0.6 or 8.1.1 ?

**Comment by vasyugan** [comment]
@PVince81 I haven't seen this in a while. Appears fixed as far as I am concerned.

**Comment by PVince81** [comment]
Ok thanks for the feedback
