### ISSUE TITLE
[Beta 2] LDAP Wizard: Credentials not updated when entered in wizard

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#11571]
When initially binding ownCloud to the LDAP Server for the very first time, and the wrong credentials were entered by accident, changing the credentials didn't seem to update the credentials. They had to be updated a second time before the bind was allowed. Seems perhaps the credentials were not updated in the back end, even though they were updated in the GUI.

What is Expected:
- Login to ownCloud, go to admin panel (with LDAP app enabled, but not yet configured)
- Enter the wrong credentials for the initial bind
- Enter the base DN
- Update the password
- Bind is successful

What happens:
- When configuring LDAP for the first time, enter a wrong password for LDAP admin
- Enter base DN
- Enter the correct password
-> Connection cannot be established
- Enter the same DN again
- Everything OK

oC 7 EE beta 2
Apache
MySQL
Linux

**Comment by blizzz** [comment]
Should be fixed with https://github.com/owncloud/core/pull/15492, but that's only >= 8.1

**Comment by MorrisJobke** [comment]
It's merged -> close
