### ISSUE TITLE
[beta 2] LDAP app not returning user info to plugin 

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#11577]
I don't have full info here, waiting on logs, but this was reported in our last migration.

The admin has problems with LDAP, and took a lot of time to configure it. The variable that defines the username (displayname) is not the case on the LDAP server, so the correct name is not able to be detected automatically.

Usually displayname is returned by ldap server, and this works on version 6.0.4. But when upgrading to 7.0 beta 2 it broke.

Was able to connect to the server, but the LDAP server did not reply to the ownCloud request.

LDAP in ownCloud expects that the name of the user comes back as a result, and in this case it did not come back from the LDAP server. There seemed to be some sort of problem between ownCloud and the LDAP server and it didn't recognize the username.
The login screen just showed a message, username or password wrong - admin then found out and debugged the problem based on the actual traffic to the LDAP server. 

Admin went into the expert and changed the UID tab in the Expert settings, and then it all worked.
Advanced tab, there are 3 - the first input field in the second section. 

Tried first displayname in that field, and that didn't work, and then put UID there. And login worked, but now the UID is shown for the username instead of the user first name and last name. this has to be changed. 

More (as said above) coming, including logs.

**Comment by DeepDiver1975** [comment]
@MTRichards still a valid issue?
@blizzz mind having a second look?

**Comment by MTRichards** [comment]
Do not think this is still an issue.

**Comment by DeepDiver1975** [comment]
> Do not think this is still an issue.

thx
