### ISSUE TITLE
[beta 2] User lazy load hangs server for LDAP

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#11578]
Don't have all of the logs yet, waiting on them, but wanted to open this ticket anyway.

oC 7 EE beta 2, in the user management panel, with an LDAP configured, if you scroll down, it tries to load more via lazy loading. 
When this happens, the PHP process goes to 100% of the CPU and then the webserver kills the process.
There is a bug somewhere hanging the process.

It does not always happen, sometimes it loaded users, sometimes not.
They have connected
- 80,000 users in a first test
- 400 users in a second test
no difference between tests. 

There would appear to be a bug in the lazy loading of users.

**Comment by blizzz** [comment]
Closed for inactivity.
