### ISSUE TITLE
[beta 2] WebDAV mount fails on first try when mounting from Linuc for LDAP users

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#11574]
When using Dolphin to mount ownCloud for an LDAP user, it is possible to mount ownCloud in Dolphin as a folder - but the first time that the login is attempted, the login fails "Folder does not exist" is the error. If the user tries again, with no changes (or re-entry of the credentials - since dolphin caches the credentials) it works just fine.

How to Reproduce:
- Connect ownCloud to LDAP, login as a user
- Mount owncloud via WebDAV to KDE Linux machine (with Dolphin) does not work, when you enter your credentials for the first time
- if you close Dolphin, open it again and enter the same URL again, you see the correct content of your directory 

Is an issue here because it used to work just fine in ownCloud 6. Since it used to work, the idea is that there is a change in ownCloud for how WebDAV is mounted.

ownCloud 7 EE beta 2
MySQL
KDE Dolphin

**Comment by DeepDiver1975** [comment]
@jnfrmarks can I ask you to verify the status of this issue - THX

**Comment by PVince81** [comment]
@MTRichards @rperezb is this still happening in 8.2RC1 ? Can someone help verify ?

**Comment by PVince81** [comment]
@MTRichards This is old, please try again with 8.2.2 or 9.0 RC1 and reopen if it still happens.
