### ISSUE TITLE
Call to a member function getFileInfo() on a non-object

### ISSUE THREAD

**Issue by hanspansen** [owncloud/core#11584]
### Steps to reproduce
1. After update to 7.0.2.3 (daily 2014-10-14) ownCloud Client did not work (server not available)
2. SOME (!!!) WebDAV clients did not work (e.g. iFiles on iPhone)
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**: Amazon Linux 2013.09

**Web server:** Apache 2.2.26

**Database:** MySQL 5.6.16

**PHP version:** 5.3.28

**ownCloud version:** 7.0.2.3 (daily 2014-10-14)

**Updated from an older ownCloud or fresh install:** Updated from 7.0.2 stable/official

**List of activated apps:** standard

**The content of config/config.php:** standard

**Are you using external storage, if yes which one:** Dropbox, GoogleDrive, WebDAV - preconfigured (but (still) not working) S3

**Are you using encryption:** no

### Client configuration
**Browser:** irrelevant, same effect on all tested browsers and WebDAV clients.

**Operating system:** irrelevant, same effect on all tested browsers and WebDAV clients.

#### Web server error log
[Tue Oct 14 21:11:30 2014] [error] [client 213.209.77.185] PHP Fatal error:  Call to a member function getFileInfo() on a non-object in /var/www/vhosts/owncloud/apps/files/appinfo/remote.php on line 50

#### ownCloud log (data/owncloud.log)
{"app":"PHP","message":"Illegal offset type in isset or empty at \/var\/www\/vhosts\/owncloud\/lib\/private\/app.php#138","level":3,"time":"2014-10-14T20:42:39+00:00"}
{"app":"PHP","message":"Call to a member function getFileInfo() on a non-object at \/var\/www\/vhosts\/owncloud\/apps\/files\/appinfo\/remote.php#49","level":3,"time":"2014-10-14T20:42:48+00:00"}
...
{"app":"PHP","message":"Call to a member function getFileInfo() on a non-object at \/var\/www\/vhosts\/owncloud\/apps\/files\/appinfo\/remote.php#50","level":3,"time":"2014-10-14T21:11:30+00:00"}

**Comment by DeepDiver1975** [comment]
do you guys still observe this issue? thx
