### ISSUE TITLE
First Time Wizard is displayed for user's first login when it shouldn't be

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#11603]
### Steps to reproduce

1. Enable first time wizard for a specific group
2. Log in as a user that is not in the group

### Expected behaviour

The user should not see the first time wizard

### Actual behaviour

The user sees the first time wizard.

### Server configuration
**Operating system**:

Ubuntu 15

**Web server:**

 Apache/2.2.22 
 
**Database:**

MySql 

**PHP version:**

PHP 5.5

**ownCloud version:** (see ownCloud admin page)

ownCloud Enterprise Edition 7 Beta2 (testing)

**Updated from an older ownCloud or fresh install:**

fresh install

**List of activated apps:**

 Enabled:
 - activity
 - enterprise_key
 - external
 - files
 - files_external
 - files_locking
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - firewall
 - provisioning_api
 - sharepoint
 - templateeditor
 - windows_network_drive
Disabled:
 - admin_audit
 - files_antivirus
 - files_encryption
 - files_ldap_home
 - files_sharing_log
 - firstrunwizard
 - user_external
 - user_ldap
 - user_shibboleth
 - user_webdavauth

**Are you using external storage, if yes which one:** local/smb/sftp/...

no

**Are you using encryption:** yes/no

no

### Client configuration
**Browser:**

Chrome

**Operating system:**

windows

#### ownCloud log (data/owncloud.log)

There is nothing of interest in the log

**Comment by nickvergessen** [comment]
Can not reproduce anymore, works as expected here.
