### ISSUE TITLE
Make search field work in apps management page

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#11635]
### Steps to reproduce:
1. On master (0412f830352fe3b00a05de881535666a3530c31b) go to the apps management page.
2. Type "encryption" in the search field

### Expected result
The apps list only shows the encryption app

### Actual result
Nothing happens

@owncloud/designers @DeepDiver1975

**Comment by oparoz** [comment]
>  I'd hide it by default and only show it in apps that register a search provider.

Still missing and confusing for users who expect to be able to get some form of results straight from the search field.

@butonic Any idea when this will land?

**Comment by DeepDiver1975** [comment]
filtering the apps is currently being worked on - https://github.com/owncloud/core/pull/13439 - scheduled for 8.1

**Comment by oparoz** [comment]
@butonic - The search field is still not hidden by default. It's confusing for users to have non-working UI elements.

**Comment by jancborchardt** [comment]
@oparoz can you actually open a new, more general issue? This specific one was solved (Search in apps management) and I’ll close this.
