### ISSUE TITLE
Set E-Mail sender name

### ISSUE THREAD

**Issue by keros** [owncloud/core#11662]
Tested on:
Owncloud 7.0.2 stable

Problem:
Owncloud sends mails in the name of the logged in user, but sets the noreply address (link share).
"`My Testuser <sharing-noreply@owncloud.mydomain.com>`"

Different myilclients (cellphone, mac, ...) only show the name in "from/to/cc/..." so the receiver only sees "My Testuser" (most of the Time "Firstname Lastname").
If the receiver replys to the e-mail ...

Wish:
Add an option in the "config.php" (I don't need a GUI for that) to set the sender name globaly for all users. So that I can set "`Owncloud Noreply <sharing-noreply@owncloud.mydomain.com>`".
Currently I can only set the noreply address.

**Comment by TBrad** [comment]
Was this removed in 8?  I'm running 8.1.3 and this variable has no effect on the emails that are sent from my OC installation:

'mail_from_name' => 'my OC install name',

**Comment by Zyg0te** [comment]
yea, the variable has no effect for me either.

**Comment by mathieufrh** [comment]
This should definitely be an option in the config file. I don't want to hardcode it, I don't think it is the (sirty) way to go.

**Comment by DeepDiver1975** [comment]
This was never implemented - contributions are welcome any time! THX

**Comment by mjrk** [comment]
As some years passed, just to clarify the current situation:

To change the Email Sender Name (from header), I need to create a custom owncloud theme?
