### ISSUE TITLE
Feature Request: allow sharing of multiple files/folders

### ISSUE THREAD

**Issue by plages** [owncloud/core#11663]
Current behaviour:
I can share only one file or folder at a time. If i want to share multiple files/folders, i have to create sharing links seperately and send multiple e-mail messages

Desired behaviour:
When i check multiple files, folders or a combination thereof a share link appears at the top of the page (like it does with "Download") allowing me to share all the selected files and folders at once.
Not necessarily  in one link but possibly several links in one sharing notification e-mail. Or (optionally) one link that creates a .zip download when clicked  containing all the selected files and folders.

**Comment by PVince81** [comment]
aka "bulk sharing"

**Comment by phpweb** [comment]
Is there any improvement about the feature?

**Comment by PVince81** [comment]
Currently not scheduled.

This is a bigger task because it requires support for bulk operations on the API level.
