### ISSUE TITLE
ownCloud server 7.0.2 + encryption + ownCloud client 1.6.3.3721 (all win) = misbehaviour

### ISSUE THREAD

**Issue by velder** [owncloud/core#11660]
If I copy file to local folder (my case: C:\Users\Administrator\ownCloud) client show me that sync is occured and file is sent to server (show process bar in "Settings" and "percent sent" then "sync successful" in tooltip). But file not appeared in server folder (neither in browser nor in webdav).
If I
a) in client sign out then sign in OR
b) exit from client then run it again OR
c) delete file in local folder and copy it again (!!!)
then client again send it to server (show process bar in "Settings" and "percent sent" then "sync successful" in tooltip) and file appeared.

I want file appearance immediately, not after erase/second copy. What I should do?

**Comment by DeepDiver1975** [comment]
@dragotin can you please have a look ? THX

**Comment by PVince81** [comment]
Are you still seeing this with 7.0.5 or 8.0.2 ?
Please note that IIS won't be supported any more in the future as there are many issues on the Windows platform (for PHP servers)

**Comment by dragotin** [comment]
yes, this misbehave of the client is fixed in the recent versions. Seek out for version 1.8.1 coming out next week.
There is a RC1 already which you might wanna test with.
