### ISSUE TITLE
[7.0.3RC1] Encryption: Change password with recovery password while user is logged in

### ISSUE THREAD

**Issue by ser72** [owncloud/core#11668]
**Expected Behavior**
Error stating keys have been modified

**Actual Behavior**
Files page "hangs"

**Steps**
Encryption enabled
Recovery key password in use
User-A has recovery password enabled on personal page
User-A currently logged into ownCloud webUI

Admin user changes password for User-A with Recovery password
User-A then attempts to select a file in his webUI
Nothing happens.
User-A cannot select any files from the WebUI or navigate to any of the menus in the Left side navigation bar.

User-A can press the cloud and get back to the Files Home 

Would expect some sort of error stating password has been changed -- please logout and log back in.

**Logs**

```

{"reqId":"544527da44e0b","app":"admin_audit","message":"Read \"\/logan\/files\/Logan.txt\" by user logan, owner: logan","level":1,"time":"2014-10-20T15:18:50+00:00","method":"GET","url":"\/owncloud703\/index.php\/apps\/files_texteditor\/ajax\/loadfile.php?file=Logan.txt&dir=%2F"}
{"reqId":"544527da44e0b","app":"PHP","message":"json_encode(): Invalid UTF-8 sequence in argument at \/var\/www\/owncloud703\/lib\/private\/log\/owncloud.php#86","level":3,"time":"2014-10-20T15:18:50+00:00","method":"GET","url":"\/owncloud703\/index.php\/apps\/files_texteditor\/ajax\/loadfile.php?file=Logan.txt&dir=%2F"}
{"reqId":"544527da44e0b","app":"index","message":null,"level":4,"time":"2014-10-20T15:18:50+00:00","method":"GET","url":"\/owncloud703\/index.php\/apps\/files_texteditor\/ajax\/loadfile.php?file=Logan.txt&dir=%2F"}
```

**Use Case**
In most cases, the admin will not be changing a password for a user who is currently in the webUI.  However, what happens if the admin accidentally changes the password for the wrong user?  This user will have no indication that their password was changed or why they can't access any files.

**Comment by PVince81** [comment]
Should be possible to kick out user sessions now after changing passwords since we track all sessions in the DB in 9.1.

Just tried it and it doesn't seem to work yet.
