### ISSUE TITLE
Unable to share files with new users/groups

### ISSUE THREAD

**Issue by treynolen** [owncloud/core#11677]
### Steps to reproduce
1.  Have existing, working Owncloud installation
2. After upgrading to 7.0.2, add new user and/or group
3. Try to share with said new user/group.  The user/group does not show up in the sharing dialog
4.  Adding new files and sharing with users/groups existing prior to upgrade works fine.

### Expected behaviour
The user or group should show in the sharing dialog so it can be selected in order to share the files

### Actual behaviour
The new user or group never shows.  Even if you type the entire name of the user or group, you are unable to share with said user/group

### Server configuration
**Operating system**:  Ubuntu 12.04.4

**Web server:**  Apache 2.2.22

**Database:**   MySQL 5.5.22

**PHP version:**  5.3.10

**ownCloud version:**  7.0.2

**Updated from an older ownCloud or fresh install:**  Updated.  This server started out as 5.0, and has had the incremental updates and major updates installed on it.  There has not been a major version skip in the upgrade process.

**List of activated apps:**   Bookmarks, Calendar, Contacts, Deleted Files, Documents, External Storage Support, Owncloud dependencies info, PDF Viewer, Share Files, Text Editor, Versions 

**The content of config/config.php:**
<?php
$CONFIG = array (
  'installed' => true,
  'dbtype' => 'mysql',
  'dbname' => 'myclouddb',
  'dbuser' => 'myclouddbuser',
  'dbpassword' => 'mydbpassword',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'forcessl' => true,
  'blacklisted_files' => 
  array (
    0 => '.htaccess',
  ),
  'overwritehost' => '',
  'overwriteprotocol' => '',
  'overwritewebroot' => '',
  'overwritecondaddr' => '',
  'proxy' => '',
  'proxyuserpwd' => '',
  'theme' => 'sain',
  '3rdpartyroot' => '',
  '3rdpartyurl' => '',
  'defaultapp' => 'files',
  'knowledgebaseenabled' => false,
  'knowledgebaseurl' => 'http://api.apps.owncloud.com/v1',
  'appstoreenabled' => false,
  'appstoreurl' => 'http://api.apps.owncloud.com/v1',
  'mail_smtpmode' => 'sendmail',
  'mail_smtphost' => 'smtp.mydomain.com',
  'mail_smtpport' => 465,
  'mail_smtptimeout' => 10,
  'mail_smtpsecure' => 'ssl',
  'mail_smtpauth' => true,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpname' => 'smtpuser',
  'mail_smtppassword' => 'thepasswordforthat',
  'trashbin_retention_obligation' => 90,
  'allow_user_to_change_display_name' => true,
  'appcodechecker' => '',
  'updatechecker' => true,
  'log_type' => 'owncloud',
  'logfile' => '/var/www/owncloud.log',
  'loglevel' => '3',
  'remember_login_cookie_lifetime' => 1296000,
  'session_lifetime' => 86400,
  'custom_csp_policy' => 'default-src \'self\'; script-src \'self\' \'unsafe-eval\'; style-src \'self\' \'unsafe-inline\'; frame-src *; img-src *; font-src \'self\' data:; media-src *',
  'xframe_restriction' => true,
  'maintenance' => false,
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/apps',
      'url' => '/apps',
      'writable' => true,
    ),
  ),
  'user_backends' => 
  array (
    0 => 
    array (
      'class' => 'OC_User_IMAP',
      'arguments' => 
      array (
        0 => '{imap.gmail.com:993/imap/ssl}INBOX',
      ),
    ),
  ),
  'customclient_desktop' => 'http://www.owncloud.org/sync-clients/',
  'customclient_android' => 'https://play.google.com/store/apps/details?id=com.owncloud.android',
  'customclient_ios' => 'https://itunes.apple.com/us/app/owncloud/id543672169?mt=8',
  'instanceid' => '507afe412774a',
  'version' => '7.0.2.1',
  'trusted_domains' => 
  array (
    0 => 'mycloud.mydomain.com',
  ),
);

**Are you using external storage, if yes which one:** :  WebDAV is enabled, but I don't think it is being actively used

**Are you using encryption:** no

### Client configuration
**Browser:**   We have tried Firefox, Chrome and Safari on the newest versions

**Operating system:**  Apple, Linux, Mac

#### Web server error log
```
Insert your webserver log here
Attempting to share with user named ft.riley2015:
74.252.14.240 - - [20/Oct/2014:13:47:06 -0500] "GET /index.php/core/ajax/share.php?fetch=getItem&itemType=file&itemSource=294754&checkReshare=true&checkShares=true HTTP/1.1" 200 1035 "https://saincloud.saineng.com/index.php/apps/files" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0"
74.252.14.240 - - [20/Oct/2014:13:47:12 -0500] "GET /index.php/core/ajax/share.php?fetch=getShareWith&search=f HTTP/1.1" 200 922 "https://saincloud.saineng.com/index.php/apps/files" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0"
74.252.14.240 - - [20/Oct/2014:13:47:12 -0500] "GET /index.php/core/ajax/share.php?fetch=getShareWith&search=ft. HTTP/1.1" 200 858 "https://saincloud.saineng.com/index.php/apps/files" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0"
74.252.14.240 - - [20/Oct/2014:13:47:15 -0500] "GET /index.php/core/ajax/share.php?fetch=getShareWith&search=ft.riley HTTP/1.1" 200 858 "https://saincloud.saineng.com/index.php/apps/files" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0"
74.252.14.240 - - [20/Oct/2014:13:47:15 -0500] "GET /index.php/core/ajax/share.php?fetch=getShareWith&search=ft.riley2015 HTTP/1.1" 200 858 "https://saincloud.saineng.com/index.php/apps/files" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0"

Nothing shows in error.log

#### ownCloud log (data/owncloud.log)
Nothing is added to the ownCloud log when sharing is attempted.

**Comment by PVince81** [comment]
Did you have any more luck with 7.0.5 or 8.0.2 ?
Several sharing bugs have been fixed since.
