### ISSUE TITLE
[7.0.3RC1] No share key found when deleting empty file with sync client

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#11679]
### Steps to reproduce
1. Enable encryption
2. Setup the sync client
3. `touch x` in the local sync folder
4. Wait for the sync client to upload the empty file
5. `rm x` in the local sync folder.
6. Wait for sync client to delete the file

### Expected result
Silent deletion, no warnings

### Actual result
owncloud.log contains
```
{"reqId":"54457044a7d6c","app":"PHP","message":"Undefined variable: pathOld at \/srv\/www\/htdocs\/owncloud\/apps\/files_encryption\/lib\/helper.php#464","level":3,"time":"2014-10-20T20:27:48+00:00","method":"DELETE","url":"\/remote.php\/webdav\/clientsync\/y"}
{"reqId":"54457044a7d6c","app":"Encryption library","message":"No share key found for user \"vincent\" for file \"\"","level":2,"time":"2014-10-20T20:27:48+00:00","method":"DELETE","url":"\/remote.php\/webdav\/clientsync\/y"}
```

### Versions
owncLoud 7.0.3 RC1
Sync client 1.7.0 beta 3

@schiesbn 

Maybe some of the code path need to ignore the share key seeking when deleting an empty file.
Please note that the files are properly deleted, so this is only a minor issue.

**Comment by DeepDiver1975** [comment]
@PVince81 still a valid issue? THX

**Comment by PVince81** [comment]
Still happening in 7.0.6 RC 1:
```
{"reqId":"556c8dfa43462","app":"Encryption library","message":"No share key found for user \"root\" for file \"x\"","level":2,"time":"2015-06-01T16:53:14+00:00","method":"DELETE","url":"\/owncloud\/remote.php\/webdav\/x"}
```

but as this is a rare case and low severity, I suggest to close. (else this would need a OC 7 specific fix)

**Comment by DeepDiver1975** [comment]
> I suggest to close.

:green_heart:
