### ISSUE TITLE
[7.0.3RC1] Setting share link password deletes expiration date

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#11671]
### Steps to reproduce
1. Create/upload file
2. Click on "Share link"
3. Select an expiration date a few days later
4. Close dropdown by clicking outside
5. Open share dropdown again
6. Tick "Password protect"
7. Enter password and hit enter
8. Close dropdown by clicking outside
9. Open share dropdown again

### Expected result
Expiration date is still there

### Actual result
Expiration date is gone

CC @enoch85 in case this is what you were observing

@schiesbn

**Comment by cmonteroluque** [comment]
@PVince81 is this closed?

**Comment by PVince81** [comment]
This will work properly with the share panel in the sidebar: #18185
