### ISSUE TITLE
[7.0.3RC1] Disable encryption and recover files

### ISSUE THREAD

**Issue by ser72** [owncloud/core#11676]
**Expected Behavior**
Extra buttons not appear

**Actual behavior**
Extra buttons about backing up keys appear

**Steps**
Encryption enabled
User A has files which are encrypted
Admin disables encryption
User A gets message to decode files in Personal page
![capture](https://cloud.githubusercontent.com/assets/5174383/4706266/4c063bba-5883-11e4-9d5d-435ba04aed64.PNG)

User A enters incorrect password.  Gets an error and buttons referencing backup of keys and ability to delete keys:

![capture1](https://cloud.githubusercontent.com/assets/5174383/4706274/595de86c-5883-11e4-8f20-db076454b861.PNG)

Those buttons should Only appear if the password was entered correctly.

Pressing one of the buttons when the password was incorrectly entered gives another error:

![capture2](https://cloud.githubusercontent.com/assets/5174383/4706311/9798a9f0-5883-11e4-8045-6a5db72d7b49.PNG)

Which appears correct but better not to have the buttons appear at all

**Comment by PVince81** [comment]
I saw this in stable8.

If an error happens during decryption, it's probably best to not show the "restore encryption keys" and "delete keys" buttons in that case.

**Comment by PVince81** [comment]
This is obsolete, decryption must now be done on the CLI starting with 8.2.

CC @schiesbn
