### ISSUE TITLE
Errors when uploading to public folder

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#11681]
Also, strange thing is that /var\/www\/owncloud\/apps\/music\/utility\/scanner.php is called on every error...

### Steps to reproduce
1. Create a folder on your oC Instance
2. Share that folder via link, without password or restrictions
3. Make it possible to upload to that folder
4. Ask someone outside your network to upload something, in this case pics and video files
5. The one that uploads gets "server error" all the time (that´s what he said)
6. I get https://gist.github.com/enoch85/3bf635ae8e2449f8e4f8 in my log

### Expected behaviour
No errors

### Actual behaviour
https://gist.github.com/enoch85/3bf635ae8e2449f8e4f8

### Server configuration
Ubuntu Server 12.04

**Database:**
Server version: 5.5.38-0ubuntu0.12.04.1 (Ubuntu)
**PHP version:**
PHP 5.3.10-1ubuntu3.14 with Suhosin-Patch (cli) (built: Sep  4 2014 07:08:49)
**ownCloud version:** (see ownCloud admin page)
7.0.2
**Updated from an older ownCloud or fresh install:**
Updated from stable 5 and then later stable 6
**List of activated apps:**
Activity
Calender 
Contacts
Deleted files
Documents
External Storage Support
First Run Wizard
Full Text Search
Music
PDF Viewer
Pictures
Share Files
Tasks
Text Editor
Updater
Versions
Video Viewer

**The content of config/config.php:**
```
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.2.1',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost.localdomain',
  'dbtableprefix' => 'oc_',
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'maxZipInputSize' => 0,
  'allowZipDownload' => true,
  'session_lifetime' => 1800,
  'check_for_working_webdav' => false,
  'forcessl' => true,
  'updatechecker' => true,
  'loglevel' => '2',
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' =>
  array (
    0 => '',
    1 => '192.168.1.111',
  ),
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'appstoreenabled' => false,
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Dropbox
**Are you using encryption:** yes/no
No
### Client configuration
**Browser:**
Version 37.0.2062.120 m
**Operating system:**
Windows 8.1
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
https://gist.github.com/enoch85/3bf635ae8e2449f8e4f8
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by PVince81** [comment]
Still happening in 7.0.4 ?

**Comment by enoch85** [comment]
@PVince81 Yes, still happening.

**Comment by enoch85** [comment]
```

Error	files	Upload error: 3 - Den uppladdade filen var endast delvis uppladdad	2015-01-23T19:49:16+00:00
Error	PHP	Call to a member function get() on a non-object at /var/www/owncloud/apps/music/utility/scanner.php#85	2015-01-23T19:49:15+00:00
Warning	sharing	No fileinfo available for: /Hej	2015-01-23T19:49:15+00:00
Warning	sharing	No fileinfo available for: /Hej/jim.toms.road.to.nashville.vol.1.special.720p-dhd.r08	2015-01-23T19:49:15+00:00
Error	PHP	Call to a member function get() on a non-object at /var/www/owncloud/apps/music/utility/scanner.php#85	2015-01-23T19:49:11+00:00
Warning	sharing	No fileinfo available for: /Hej	2015-01-23T19:49:11+00:00
Warning	sharing	No fileinfo available for: /Hej/jim.toms.road.to.nashville.vol.1.special.720p-dhd.r07	2015-01-23T19:49:11+00:00
Error	PHP	Call to a member function get() on a non-object at /var/www/owncloud/apps/music/utility/scanner.php#85	2015-01-23T19:49:06+00:00
Warning	sharing	No fileinfo available for: /Hej	2015-01-23T19:49:06+00:00
Warning	sharing	No fileinfo available for: /Hej/jim.toms.road.to.nashville.vol.1.special.720p-dhd.r06	2015-01-23T19:49:06+00:00
Error	PHP	Call to a member function get() on a non-object at /var/www/owncloud/apps/music/utility/scanner.php#85	2015-01-23T19:48:51+00:00
Warning	sharing	No fileinfo available for: /Hej	2015-01-23T19:48:51+00:00
Warning	sharing	No fileinfo available for: /Hej/jim.toms.road.to.nashville.vol.1.special.720p-dhd.r05	2015-01-23T19:48:51+00:00
```

**Comment by enoch85** [comment]
Without Music App activated:

```
Warning	sharing	No fileinfo available for: /Hej	2015-01-23T20:01:15+00:00
Warning	sharing	No fileinfo available for: /Hej/The.Blacklist.S02E08.720p.HDTV.X264-DIMENSION.mkv	2015-01-23T20:01:15+00:00
Warning	sharing	No fileinfo available for: /Hej	2015-01-23T19:58:45+00:00
Warning	sharing	No fileinfo available for: /Hej/the.blacklist.208.720p-dimension.sfv	2015-01-23T19:58:45+00:00
Warning	sharing	No fileinfo available for: /Hej	2015-01-23T19:58:44+00:00
Warning	sharing	No fileinfo available for: /Hej/the.blacklist.208.720p-dimension.rar	2015-01-23T19:58:44+00:00
Warning	sharing	No fileinfo available for: /Hej	2015-01-23T19:58:39+00:00
Warning	sharing	No fileinfo available for: /Hej/the.blacklist.208.720p-dimension.r13	2015-01-23T19:58:39+00:00
Warning	sharing	No fileinfo available for: /Hej	2015-01-23T19:58:34+00:00
Warning	sharing	No fileinfo available for: /Hej/the.blacklist.208.720p-dimension.r12	2015-01-23T19:58:34+00:00
```

No "Internal Server Error" though.

**Comment by PVince81** [comment]
Thanks. Very strange.
Are these files stored on an external storage mount point or just the local home ?

**Comment by enoch85** [comment]
Just local. Removed the External App, remember? :)

2015-01-26 10:58 GMT+01:00 Vincent Petry <notifications@github.com>:

**Comment by PVince81** [comment]
This here is suspicious, but not necessarily related to your issue:
```
Error   PHP Out of memory (allocated 1903165440) (tried to allocate 1879450700 bytes) at /var/www/owncloud/lib/private/preview/txt.php#30   2014-10-24T22:42:32+00:00
```

Do you have a super huge txt file ?

@georgehrke we should maybe prevent creating previews for text files bigger than a given size. Also I don't understand why it would cause such error, the preview code should only read a few lines.

**Comment by enoch85** [comment]
@PVince81 Nope, no big .txt file. Not in that folder anyway. But I have a 2.1 GB logfile in the root of my ownCloud.

**Comment by enoch85** [comment]
@icewind1991 @PVince81 Any update here?

**Comment by PVince81** [comment]
@enoch85 still happening with 7.0.7 or 8.0.5 ?

**Comment by enoch85** [comment]
@pvince81 no, haven't seen it.

**Comment by enoch85** [comment]
On 8.1 that is.
