### ISSUE TITLE
Send password when sharing via e-mail

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#11682]
Instead of having to send the password in a seperate email  we should do it automatically by adding an additional send button that says "_Send with password_" next to the regular "_Send_" button in those cases when you add a password to a link and decides to send the shared link per email.

In the e-mail the user gets it should say something like; 
"The link is password protected. The password is: [Password]"

What do you think @jancborchardt @LukasReschke ?

**Comment by enoch85** [comment]
Ping @jancborchardt @LukasReschke @MTRichards Any milestone for this?

**Comment by rullzer** [comment]
I assume this should also be added in the new sharing modal: #5873

**Comment by cycloon** [comment]
Instead of sending plain text passwords you could send only username and an activation link. That activation link could then behave like the current password reset.

That way you never have to send a password over untrusted connections (read: email) and you even reach a second goal: the user is forced to choose a password on his own.

**Comment by enoch85** [comment]
@cycloon That would be perfect!

**Comment by rullzer** [comment]
@cycloon while that would be possible it does require a significant amount of changes. Since currently we have at most 1 share per link. Which you can share and e-mail with a ton of people. In this scenario you can only share with 1 person by link.

Probably some discussion is required if that is the desired way to go.

**Comment by jancborchardt** [comment]
@rullzer maybe related, from the [design forward of the sharing dialog](https://github.com/owncloud/core/issues/3224):
> future: generate unique link per email address so revocation on a per-person basis is possible

**Comment by Froster** [comment]
Hi

but what is if the User should become the shared e-mail is not a know user in the system? So it should be possible only to activate the option "send password with email". for everyone share via mail.

**Comment by jancborchardt** [comment]
@Froster they will get a personalized share link, as we said above. The password is a different topic – all the links will be separate so if you deactivate a person’s link they can not view it anymore.

**Comment by Froster** [comment]
@jancborchardt  yeah you are right but as you see my request was closed and i was linked here.

- for personal links it should be able for the user to monitore them on a seperated page maybe in an app für the WebUI so the he could overview them to reduce complexity
- even i don't know if the hole System with personal links could be to complex in business proposes if you have mainly normal users

- and i wonder that "Nobody" here think about how to manage this via mobile app this should be the same workflow as in web

I know the hole discuss about Password.This is my request:

share context Menu
•if password is set (or is newly set or changed)
•option checkbox should appear
•variable available in the email template ##email##

**Comment by kylesouza** [comment]
Hello!  sorry for my ignorance, how am I able to see the progress of features such as this one?  Would this be the best place to look?

**Comment by jancborchardt** [comment]
@kylesouza yes. And as you see the issue is in the backlog. That means it’s not scheduled for any release specifically, and there’s currently no work being done on it.

**Comment by kylesouza** [comment]
Okay, thanks!  I'm very new to github and open source and such.





On Sat, Jun 20, 2015 at 4:07 AM -0700, "Jan-Christoph Borchardt" <notifications@github.com> wrote:
@kylesouza yes. And as you see the issue is in the backlog. That means it’s not scheduled for any release specifically, and there’s currently no work being done on it.

---

**Comment by enoch85** [comment]
Ref: #17398

**Comment by RealRancor** [comment]
I think #17398 is unrelated as this is a completely different use-case. When sharing a link password protected it makes no sense to send out a link where a user can set its own password for the share.

**Comment by sysgloo** [comment]
We will wait for the solution of features! thx'

**Comment by michaelstingl** [comment]
@MTRichards Are there any plans to get this in ownCloud?

00004268

**Comment by bboule** [comment]
@MTRichards looks like a feature request @michaelstingl is this in SFDC

**Comment by MTRichards** [comment]
Looking at it, I commented in SFDC that 9.1 is the soonest we can look at an elegant solution to this problem - one that doesn't compromise security too much.

**Comment by bboule** [comment]
@michaelstingl can you communicate this to the customer, I will change this to resolved

**Comment by MTRichards** [comment]
For a little more insight - the core problem here is that we don't store the password in the database, but instead the hash result of the password. So the only time it can be sent is the moment it is typed, which isn't a problem - but needs some core work to make it happen. This is a good thing to do after the sharing rework being done in 9.0 as well, as it will likely impact the code here.

**Comment by enoch85** [comment]
@MTRichards @bboule So this will be in 9.1?

**Comment by MTRichards** [comment]
Possibly. It is in the backlog for evaluation when we get to 9.1 planning, then we will know for certain.

**Comment by BornToBeRoot** [comment]
Send Password would be great. But how about security? 
Maybe send the password in a second mail?

**Comment by enoch85** [comment]
Ref https://github.com/owncloud/core/issues/11682

**Comment by michaelstingl** [comment]
@MTRichards Is the milestone still correct?

**Comment by MTRichards** [comment]
Nope, milestone is not correct. 

And there are problems with sending the password as @BornToBeRoot pointed out. No point in sending the password in the same email. Maybe a second email works, but we also need to remember the system doesn't store the password, it stores the hash of the password - so after the initial setup, if you don't remember the password, we can't send it again the next time you visit the link.

**Comment by MTRichards** [comment]
If you want this feature, feel free to add it to the overall planning list and vote it up!
https://github.com/owncloud/core/issues/24684

**Comment by enoch85** [comment]
Done: https://github.com/owncloud/core/issues/24684#issuecomment-221651987

**Comment by hodyroff** [comment]
Second email is a good start. Password via SMS or any other user defined channel for sending it would be better. Meaning: As a user I would want to decide if such PW goes out by SMS, or maybe per Signal message. Seems like I would first need to select the route and then type the password due to the storing as hash nature.

**Comment by UU0113** [comment]
I totally agrree to this function. Owncloud should give this option to include the password as well. I understand the security risks but this is something Owncloud should note taking care of. The default option is to disable this but a checkbox should allow to include the password (maybe with a hint that emails might be read by someone else). Many companies now using mail gateways and encrypt e-mail with S/MIME or PGP. Don't you?

Long story short: The user may decide how to handle the password, not Owncloud developers view on. 

Just remember, you have to build software that is 'easy' to use for non-technical people. Those people just don't care about your security concerns and suggestions ("oh please use another channel for secuirty like SMS") but want share stuff easily. In a real world people just send another mail with the password and complain to IT dept. for this additional steps dropping their productivity for no benefit...

**Comment by iArjan** [comment]
Still waiting for this function.

**Comment by dnviti** [comment]
Hi we also need this function, please re open this post.
I'd like to choose if send the password along with the link or not.

**Comment by michaelstingl** [comment]
Issue is open and feature is on the product backlog. PR welcome!

**Comment by dnviti** [comment]
Thank you!

**Comment by enoch85** [comment]
This feature was introduced in Nextcloud 12. So for me this is already fixed since I migrated.

**Comment by happicamper** [comment]
Will wait for this feature! Thanks in advance. 🎆

**Comment by PVince81** [comment]
What we can do is add a placeholder for the password but not include it in the default template. So if people really want this security risk they need to edit the template to add the placeholder name into their template.

cc @pmaier1
