### ISSUE TITLE
Folder with very long filename break the sync.

### ISSUE THREAD

**Issue by ogoffart** [owncloud/core#11690]
Spin off https://github.com/owncloud/mirall/issues/2345

### Steps to reproduce

Create a sub folder with a very long name (250 character).
From the web interface or from the sync client.

Example of name: `mmmasdlfjdasfljsflsanfdjsndkfsnfjknaskjfnaskjdfnakjsndfaksdfnjasdnfkjasndfkjsnfdkjnaskjdfnjksdnfjsdfskfdjsndfakjsdnfkjsandfkjansfjknasjkfnaskjfnaksjnfjsfnjksnfkjasnfkjsnfjansfknaskdjfnaskjfnajsdfnkasjfnjaksnfsjkdnfjsanjkfsafpiiiiiiiiiiiiiiiiiiiiixxxx`

### Expected behaviour

Everything should still work, Or there should be an error preventing the creation of the folder.

### Actual behaviour

The sync client cannot sync anything anymore because of this folder.
 And trying to enter that folder from the web interface bring back to the root folder.  Trying to delete the folder do not work.

The sync client is broken because the folder is listed in the PROPFIND of the parent folder, but doing a PROPFIND on the folder itself result in a 404.

**Comment by freddy961** [comment]
Use LongPathTool for long path and and long extension..

**Comment by PVince81** [comment]
Is this still an issue ?
Was the remote server running on Windows Server ? (which is unsupported since 8.1)

**Comment by guruz** [comment]
@PVince81 As per https://github.com/owncloud/client/issues/2345#issuecomment-59935011 i don't think @ogoffart is running a Windows server

**Comment by PVince81** [comment]
@ogoffart can you provide the PHP version and database of that remote server ?

I also cannot reproduce this issue with OC 8.2RC1, php5-5.6.13-1.1.x86_64, mariadb-10.0.20-1.1.x86_64

**Comment by ogoffart** [comment]
I also can no longer reproduce.
