### ISSUE TITLE
Ignore Mac OS X meta-files natively or use wildcards in blacklist_files parameter

### ISSUE THREAD

**Issue by hostingnuggets** [owncloud/core#11705]
Mac OS X meta-files (`.DS_Store` and `._*`) are annoying and correctly ignored by default in the OC desktop client. This is unfortunately not the case when using Mac OS X native WebDAV client. Nevertheless the OC core has a config parameter called blacklisted_files where one can at least blacklist the .DS_Store file. But looking at the code behind this parameter shows that it does not accept wildcards. As such I can't blacklist a wildcard pattern such as `._*`.

Would it be possible to either have a blacklist_files parameter which supports wildcards or to natively ignore Mac OS X meta-files?

**Comment by oureas** [comment]
Is it possible to force the WebGUI to hide all files beginning with a dot?

**Comment by mitar** [comment]
The happens for me when uploading folder with Chrome with drag&dropping in web interface. It uploads also `.DS_Store` files. The worst is, it seems I cannot delete them. I get 403 forbidden error. Despite me uploading it.
