### ISSUE TITLE
How to configure the owncloud database connection with SSL?

### ISSUE THREAD

**Issue by gig13** [owncloud/core#11718]
Is there a way to specify SSL for the ownCloud database connection? Will the php pdo module be used in future releases? The plan is to utilize SSL connections throughout the setup and there is no obvious way to configure the ownCloud Database.

The database that will be used is a percona xtradb cluster.

@MTRichards @craigpg

**Comment by DeepDiver1975** [comment]
moving to oc8.1 for the remaining pieces

**Comment by MorrisJobke** [comment]
This was fixed with #17963

@rperezb Maybe we want this to be added to a test plan or at least a one time test.

**Comment by rperezb** [comment]
@SergioBertolinSG thx
