### ISSUE TITLE
Introduce CI for files_external

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#11717]
@DeepDiver1975 @karlitschek @LukasReschke @icewind1991 
@craigpg @MTRichards 

Whether we keep files_external in core or not it doesn't matter.
Most importantly we need to setup a CI solution for files_external (external storage app).

Let's discuss it here.
Follow up from https://github.com/owncloud/core/issues/8002

**Comment by MorrisJobke** [comment]
I will add additional stuff step by step -> not part of our 8.0 bug fixing season -> move to 8.1

**Comment by MorrisJobke** [comment]
SMB: #13922
SFTP: #14068

**Comment by MorrisJobke** [comment]
FTP: #14076

**Comment by PVince81** [comment]
- [ ] Regular WebDAV raised as: https://github.com/owncloud/core/issues/15897

**Comment by cmonteroluque** [comment]
@DeepDiver1975 ping

**Comment by Xenopathic** [comment]
To be done:

- [ ] Amazon S3 (I hope to make a test tomorrow)
- [ ] Dropbox
- [ ] Google
- [ ] More FTP servers (they all behave differently)
- [ ] Alternative WebDAV server(s) #15897
- [ ] SFTP public key
- [ ] Swift #14077

**Comment by DeepDiver1975** [comment]
9.0

**Comment by PVince81** [comment]
Nice, we did make some progress. I just ticked swift :smile:

**Comment by PVince81** [comment]
SFTP is close to working with two failing tests (PRs included): https://github.com/owncloud/core/issues/11692

Webdav was merged a while ago, could be put into CI as well: https://github.com/owncloud/core/pull/16688

**Comment by PVince81** [comment]
@DeepDiver1975 close this ? We want to move everything to apps anyway so CI should be added there when doing just that.

**Comment by PVince81** [comment]
Closing this. We should focus on moving ext storage backend individually to separate apps and add CI there when possible.
