### ISSUE TITLE
File shared Server to server is read only - should it be?

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#11722]
### Steps to reproduce

1. Upload a file
2. Share it via a link
3. Enter the link in the browser
4. From the link, share with another instance of oC
5. From instance two edit the file

### Expected behaviour

I can change the file content

### Actual behaviour

I cannot change the file content.  The file opens up in the editor but I can't make any changes.  

If this is the way this is supposed to work, is there a way to inform the user the the file is read only?

### Server configuration
**Operating system**:

Ubuntu 14

**Web server:**

apache

**Database:**

MySQL

**PHP version:**

PHP 5.5.9

**ownCloud version:** (see ownCloud admin page)

ownCloud Enterprise Edition 7.0.3 RC1 (daily) Build:2014-10-22T13:14:56+00:00

**Updated from an older ownCloud or fresh install:**

fresh install

**List of activated apps:**

            <element>files</element>
            <element>activity</element>
            <element>admin_audit</element>
            <element>enterprise_key</element>
            <element>files_external</element>
            <element>files_locking</element>
            <element>files_sharing</element>
            <element>files_sharing_log</element>
            <element>files_texteditor</element>
            <element>files_trashbin</element>
            <element>files_versions</element>
            <element>provisioning_api</element>
            <element>sharepoint</element>
            <element>templateeditor</element>
            <element>user_ldap</element>
            <element>windows_network_drive</element>

**Are you using external storage, if yes which one:** local/smb/sftp/...

no

**Are you using encryption:** yes/no

yes, S3 as primary

### Client configuration
**Browser:**

Chrome

**Operating system:**

windows

#### ownCloud log (data/owncloud.log)

```



```

**Comment by PVince81** [comment]
There is a misunderstanding here.

The bug reported by @jnfrmarks is that the file is always read-only.
Currently on master the "allow editing" option only exists for folders, not files.

Renaming "can upload" to "allow editing" for folders was already done on master, but it only applies to folders.

So we need to keep this ticket and fix it as follows:
- [ ] also show "allow editing" checkbox for files

**Comment by cmonteroluque** [comment]
@Xenopathic can I send this your way, as 8.2 cleanup?

**Comment by Xenopathic** [comment]
This seems to have already been fixed at some point
