### ISSUE TITLE
UI freezes when accessing share file that was deleted from the originating server

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#11723]
### Steps to reproduce

1. Upload a file
2. Share it via a link
3. Enter the link in the browser
4. From the link, share with another instance of oC
5. Back on oC1, delete the file
6. From oC2 try to access the file

### Expected behaviour

The file is either accessible or an error is thrown indicating the file isn't available

### Actual behaviour

The UI freezes

### Server configuration
**Operating system**:

Ubuntu 14

**Web server:**

apache

**Database:**

MySQL

**PHP version:**

PHP 5.5.9

**ownCloud version:** (see ownCloud admin page)

ownCloud Enterprise Edition 7.0.3 RC1 (daily) Build:2014-10-22T13:14:56+00:00

**Updated from an older ownCloud or fresh install:**

fresh install

**List of activated apps:**

            <element>files</element>
            <element>activity</element>
            <element>admin_audit</element>
            <element>enterprise_key</element>
            <element>files_external</element>
            <element>files_locking</element>
            <element>files_sharing</element>
            <element>files_sharing_log</element>
            <element>files_texteditor</element>
            <element>files_trashbin</element>
            <element>files_versions</element>
            <element>provisioning_api</element>
            <element>sharepoint</element>
            <element>templateeditor</element>
            <element>user_ldap</element>
            <element>windows_network_drive</element>

**Are you using external storage, if yes which one:** local/smb/sftp/...

no

**Are you using encryption:** yes/no

yes, S3 as primary

### Client configuration
**Browser:**

Chrome

**Operating system:**

windows

#### ownCloud log (data/owncloud.log)

```

{"app":"index","message":"Sabre\\DAV\\Exception\\NotAuthenticated: Not authenticated","level":4,"time":"2014-10-22T20:42:34+00:00"}


```

**Comment by jnfrmarks** [comment]
@PVince81 

To "access the file"  I was editing it.

This no longer freezes the UI, but does throw a server 500 error:

```
{"reqId":"QLS1emv4sMLRBfjPsdSx","remoteAddr":"172.18.0.165","app":"webdav client","message":"curl GET http:\/\/172.18.5.74\/owncloud\/public.php\/webdav\/ returned status code 500","level":3,"time":"2015-06-16T07:28:32+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files_texteditor\/ajax\/loadfile?filename=pre_131.txt&dir=%2F"}

```

This is correct: the file is gone.  Can we throw a "file not found on remote server" error instead of an internal server error?

![p355](https://cloud.githubusercontent.com/assets/8480343/8186908/fee2721e-141a-11e5-9e23-839a63f74c34.PNG)

**Comment by PVince81** [comment]
Yes, we should make that a 404

**Comment by PVince81** [comment]
The problem here is that the code path doesn't go through any of the methods that check availability.
It just calls $view->isUpdatable() which itself calls $davStorage->getPermissions() which receives a 404 from the remote server that is thrown too far and there is no chance to catch it.
