### ISSUE TITLE
Update to 7.0.3 RC1 fails

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#11731]
Distribution: isv:ownCloud:community:testing / openSUSE_13.1 
Pulled in via yast-online-update. When opening the web.interface, I see this error:

Updating ownCloud to version 7.0.3 RC1, this may take a while.

Turned on maintenance mode
An exception occurred while executing 'ALTER TABLE `oc_filecache` CONVERT TO CHARACTER SET utf8 COLLATE utf8_bin;': SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x98\x90 N...' for column 'path' at row 33

The update was unsuccessful.Please report this issue to the ownCloud community.

**Comment by PVince81** [comment]
@jnweiger any news on this issue or obsolete ?

**Comment by jnweiger** [comment]
Not reproducable an more. I'll open new, if this happens again.
