### ISSUE TITLE
Can't display a folder with excesive files in the web browser

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#11743]
### Expected behavior
Open a folder with many files an work with it.

### Actual behavior
Open a folder with many files and error appears:

![70000 files](https://cloud.githubusercontent.com/assets/7264495/4754819/dc435ce6-5ac0-11e4-85ae-4d74c19bd412.png)

### Steps to reproduce 

Testing https://github.com/owncloud/mirall/issues/2090 I became this error

1. Add 70,000 Files in one folder ( :hushed: yes that many)
2. Sync in the server
3. Log in oC over the web interface.
4. Select the folder where the files are located
5. Can continue, even pressing ```Stop script``` or ```Continue```

### Architecture
OwnCloud 6.0.5
Ubuntu server 14.04
Client: Ubuntu 14.04 with oC 1.6.3 and Firefox 33

**Comment by MorrisJobke** [comment]
@DeepDiver1975 @cdamken I don't think that this will be fixed properly in ownCloud 6 ... better upgrade to 7. Or isn't this an option?

**Comment by cdamken** [comment]
Well, then upgrade to oC7
