### ISSUE TITLE
Session_lifetime not working as expected

### ISSUE THREAD

**Issue by ctaperts** [owncloud/core#11745]
'session_lifetime' => '60 * 10',
I tried to disable heartbeat but the server became buggy
### Expected behaviour
Session does not logout after 10 minutes
### Actual behaviour
keeps anyone logged in indefinetly
Xubuntu 14.04-Owncloud 7.0.2.1-MariaDB-PHP 5.5.9-1ubuntu4.4-fresh install

https://github.com/owncloud/core/issues/6877 is the same issue but was closed and did not solve the issue. 

Thanks and sorry to bring it back but i think this feature would bring a larger crowd to use owncloud because of certain security requirements that other platforms implement.

**Comment by MorrisJobke** [comment]
This should be fixed by https://github.com/owncloud/core/pull/21575 with 9.0.0 and 8.2.3
