### ISSUE TITLE
Error uploading 4g file

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#11768]
### Steps to reproduce

1. set owner of .htaccess to the apache user
2. Go to the admin page
3. Validate that the  File Handling Dialog is present and enter max upload size of 20G
4. Validate that it's in .htaccess
5. Upload 4 g file

### Expected behaviour

The file should be uploaded

### Actual behaviour

The upload fails at the very last minute.  There is nothing in the server log file.

![p193](https://cloud.githubusercontent.com/assets/8480343/4774184/ad1cc98a-5baa-11e4-9c3a-e40062c4f885.PNG)
![p192](https://cloud.githubusercontent.com/assets/8480343/4774183/ad1bf460-5baa-11e4-81ea-e03eb56ba80f.PNG)
![p194](https://cloud.githubusercontent.com/assets/8480343/4774185/ad3a57a2-5baa-11e4-9c17-6740d0c60a61.PNG)

### Server configuration
**Operating system**:

Ubuntu 12.04

**Web server:**

 Apache/2.2.22 
 
**Database:**

MySql 

**PHP version:**

PHP 5.3

**ownCloud version:** (see ownCloud admin page)

ownCloud Enterprise Edition 7.0.3 RC1 (daily) Build:2014-10-24T03:03:03+00:00

**Updated from an older ownCloud or fresh install:**

upgrade from beta2

**List of activated apps:**

Enabled:
 - activity
 - enterprise_key
 - files
 - files_encryption
 - files_locking
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - firewall
 - firstrunwizard
 - sharepoint
 - templateeditor
 - windows_network_drive
Disabled:
 - admin_audit
 - external
 - files_antivirus
 - files_external
 - files_ldap_home
 - files_sharing_log
 - provisioning_api
 - user_external
 - user_ldap
 - user_shibboleth
 - user_webdavauth

**Are you using external storage, if yes which one:** local/smb/sftp/...

windows network drive and sharepoint are configured but the file is being copied to the ownCloud root directory

**Are you using encryption:** yes/no

no

### Client configuration
**Browser:**

Chrome

**Operating system:**

windows

**Comment by butonic** [comment]
@DeepDiver1975 close because php 5.3 has reached EOL and Redhat and Suse provide 5.4 packages or their stable distributions?

**Comment by DeepDiver1975** [comment]
@butonic this should work with 5.3 as well

@jnfrmarks does this issue still exists - all I can say: this is most probably a server config issue. Configuring an environment properly with that respect is not trivial.

**Comment by RealRancor** [comment]
> @butonic this should work with 5.3 as well

Not necessarily, there are some reports at the forums that large files with PHP 5.3.x wasn't working and it was fixed by upgrading the PHP version. Even the PHP 5.6.0 changelog is stating "File uploads larger than 2 gigabytes in size are now accepted."

**Comment by blizzz** [comment]
Closing as setup issue then.
