### ISSUE TITLE
Wrong free space reported on webdav mount

### ISSUE THREAD

**Issue by bong0** [owncloud/core#11776]
### Steps to reproduce
0. Have a user with unlimited owncloud qouta
1. mount https://owncloudinstance.example/remote.php/webdav/ with gvfs (1.22.1) or davfs2 (1.5.2)
2. try to write big files (several 50-100 MB) on the mount / try to initiate a deja-dup backup on the share

### Expected behaviour
The backup or copy action should be successful.

### Actual behaviour
df reports:

    https://owncloudinstance.example/remote.php/webdav/ 5.4G  5.4G     0 100% /tmp/test
and gvfs-info -f ...

    attributes:
        filesystem::size: 5720606615
        filesystem::free: 5
        filesystem::type: webdav
        filesystem::used: 5720606610
        gvfs::backend: dav

while the Settings page shows "Du verwendest 5.3 GB der verfügbaren 4.6 TB" - "you use 5.3GB of 4.6T available".

### Server configuration
Regular instance running on a shared host.
There is no linux fs quota set for the running user.

**ownCloud version:** (see ownCloud admin page)
7.0.2 stable

### Client configuration
Gnome 3 and gvfs (1.22.1) and davfs2 (1.5.2) 

**Operating system:**
Arch Linux

### Logs
not available

**Comment by DeepDiver1975** [comment]
> "you use 5.3GB of 4.6T available".

could be an integer overflow in the propfind result? 

refs https://github.com/owncloud/core/issues/16240 :question:

**Comment by MorrisJobke** [comment]
> could be an integer overflow in the propfind result?

I also thought about this. Would be something like 5 * 10^12 while mostly INT_MAX is 9 * 10^18 or 2 * 10^9 is.

Does this still happen?

**Comment by MorrisJobke** [comment]
If this still happen feel free to reopen this. We can't reproduce any problems in the WebDAV response with the recent versions of owncloud anymore.
