### ISSUE TITLE
Uploads grind to a halt when owqnCloud linked to network NAS as external storage.

### ISSUE THREAD

**Issue by dgoadby** [owncloud/core#11774]
I love the feature to link to external storage, I usually link to a QNAP storage box on my network. The box has about 6TB of data on it.

Read access is fine but, when uploading files to the local storage, there is a very long wait (many minutes) and sometimes I have to close the browser and start again. It is worth noting that the files are always up loaded ok. 

I removed my QNAP NAS from external storage and everything works perfectly. I wonder if ownCloud is re-caching the folder contents after the upload? Whatever it is doing the external storage is the problem. 100% repeatable.

The only other effect of using my external NAS storage is a few " General error: 5 database is locked" messages.  Again, no external NAS, no messages.

I am using V7.0.02 with SQLite under SUSE 13.1/Apache

**Comment by PVince81** [comment]
@dgoadby can you post that "database is locked" issue with details ?

**Comment by PVince81** [comment]
Closing due to lack of feedback.
You might have more luck with 8.0.5.
If not, feel free to reopen.
