### ISSUE TITLE
deprecated mysql_connect should be replaced with PDO

### ISSUE THREAD

**Issue by butonic** [owncloud/core#11788]
During install we are using mysql_connect, which has been deprecated with PHP 5.5. We should migrate to PDO for all db connections where possible (at least PDO_OCI is still experimental).

Furthermore, driver options, which are eg. needed to set up an SSL encryted connection to a mysql server should be respected for the initial set up as well as for post install doctrine connections.

- [ ] During installation replace mysql_connect with PDO or maybe even doctrine2 if possible
- [ ] The db availability checks need to be changed https://github.com/owncloud/core/search?q=mysql_connect&type=Code&utf8=%E2%9C%93
- [ ] Pass additional driver options to the connection during installation, as well as post installation

ref https://github.com/owncloud/core/pull/11783
ref https://github.com/owncloud/core/issues/11718

**Comment by DeepDiver1975** [comment]
reschedule for OC8.1

**Comment by nazar-pc** [comment]
Wanted to install 8.1 on server with MySQLi and PDO,  without mysql and failed...

**Comment by DeepDiver1975** [comment]
> Pass additional driver options to the connection during installation, as well as post installation

@butonic you might want to test if this is not properly working for you - THX
