### ISSUE TITLE
Renaming folder during sync causes error

### ISSUE THREAD

**Issue by fabiannagel** [owncloud/core#11784]
While I was uploading several files into a folder using the Windows client, I renamed the folder in the webinterface, causing the client to throw "Path not found: ..." errors. When I changed the name of the folder back to the original, the client was able to continue the sync. Maybe this could be solved by using an alias/hash which isn't affected by a renaming operation?

**Comment by jancborchardt** [comment]
This is a duplicate of https://github.com/owncloud/core/issues/10192, let’s continue there.
