### ISSUE TITLE
SFTP downloads empty files if remote password was changed

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#11785]
### Steps to reproduce
1. Mount an SFTP external storage as "/sftp"
2. Upload a few files
3. See that they can be downloaded
4. SSH to the remote machine and change the password of the SFTP user
5. Navigate to the "/sftp" and download some files

### Expected result
SFTP mount must return 503 Storage unavailable when password is wrong or connection did not work

### Actual result
SFTP mount is still there with the old file list. Downloading files result in empty files (0 bytes).

**Comment by Xenopathic** [comment]
Fix is at #13390

**Comment by PVince81** [comment]
Fixed by https://github.com/owncloud/core/pull/19081
