### ISSUE TITLE
Encryption Modul: encrypt Thumbnails on server as well

### ISSUE THREAD

**Issue by JimLoose** [owncloud/core#11790]
- When i have encryption on, files and especially images should be encrypted here as well.
- If encryption is changed, we could simply delete the cache there.

**Comment by oparoz** [comment]
Not sure why that folder isn't encrypted? It's being access through View.

**Comment by georgehrke** [comment]
ping @schiesbn

**Comment by PVince81** [comment]
Encryption were never encrypted before.

I believe most folders are excluded from encryption, except files, files_versions and files_trashbin

**Comment by georgehrke** [comment]
@schiesbn How hard is it to enable encryption for previews.
Is it just a matter of adding 'thumbnail' to an array of whitelisted folders?

**Comment by PVince81** [comment]
Because it limits itself to files and files_versions, see https://github.com/owncloud/core/blob/master/apps/files_encryption/lib/proxy.php#L52

**Comment by PVince81** [comment]
Whitelisting is likely to not work because there is no location for the encryption key of the "thumbnails" folder.
Ideally the folder structure of the encryption should be changed to be "$user/files_encryption/$folderId/..." where "$folderId" can be "files", "files_versions" or anything else.

**Comment by georgehrke** [comment]
cc @karlitschek @DeepDiver1975 

What's your opinion on encrypting the previews?

**Comment by PVince81** [comment]
I think it would be fine.
My worry is mostly architectural...

**Comment by karlitschek** [comment]
Sounds like something that is possible but would not be very high on the priority list. I suggest that we first fix all the other sev1 and sev2 bug first ;-)

**Comment by DeepDiver1975** [comment]
Let's reevaluate this in 8.2 - with 8.1 we will get a different code organization for encryption - which might help to get this implemented easier

**Comment by oparoz** [comment]
So, what's the word on encrypting thumbnails with the new encryption module? This is a pretty big privacy issue.

**Comment by LukasReschke** [comment]
>  This is a pretty big privacy issue.

This is not part of the threat model and also documented: https://doc.owncloud.org/server/8.1/admin_manual/configuration_files/encryption_configuration.html?highlight=encryption#files-not-encrypted

**Comment by oparoz** [comment]
Just because it's documented doesn't mean that it's OK from my pov. If a users enables encryption, then those files should only be made available "in clear" in the clients.

**Comment by schiesbn** [comment]
With ownCloud 8.0 and smaller this wasn't possible because all keys where relative to data/user/files, so we couldn't store encryption keys for files outside of the "files"-directory.

With ownCloud 8.1 this will change. Now the keys are relative to data/user, so we can encrypt everything. Until now we decided to decrypt the same set of files and not to change the behavior to compared with ownCloud8. But we could easily encrypt the previews, we would just need to return true for "thumbnails" here: https://github.com/owncloud/core/blob/master/apps/encryption/lib/crypto/encryption.php#L338

**Comment by oparoz** [comment]
@schiesbn That's really great news. What was the motivation behind the decision not to encrypt thumbnails in 8.1?

**Comment by schiesbn** [comment]
The basic idea of the encryption re-work was to make it more modular and ready for future requirements, without breaking the old behavior. That's why we decided to encrypt the same set of files.

**Comment by georgehrke** [comment]
Ok, encrypting previews seems easy. :)
Now comes the hard part: decrypting them ;)
Where do we have to hook in, to give other users / public access of previews for shared files?

**Comment by oparoz** [comment]
Even encrypting is a problem since we're currently caching them by accessing the filesystem directly.

**Comment by oparoz** [comment]
Hmmm... Might not be true... `$this->userView->file_put_contents()`  Is that automatically encrypted @schiesbn ?

**Comment by georgehrke** [comment]
>  Is that automatically encrypted 

I think so

**Comment by oparoz** [comment]
So what's the problem with decrypting? Thumbnails are encrypted with the same key used for files, so the proxy should decrypt them on the fly when access is requested, no?

**Comment by schiesbn** [comment]
> Now comes the hard part: decrypting them ;)

It is as easy as encrypting. :smile: 

Just read the file with something like ````$view->file_get_contents('/thumbnails/foo')```` and you will get the decrypted content. You can try it yourself, edit https://github.com/owncloud/core/blob/master/apps/encryption/lib/crypto/encryption.php#L338 to return true for 'thumbnails'. Upload a image, you will see the thumbnail as before but if you look at the thumbnail stored on your filesystem you will see that it is encrypted.

**Comment by schiesbn** [comment]
> So what's the problem with decrypting? Thumbnails are encrypted with the same key used for files, so the proxy should decrypt them on the fly when access is requested, no?

Yes, the storage wrapper decrypts the thumbnails on the fly. But they have they don't use the key from the original file. Every file has it's own key.

**Comment by oparoz** [comment]
What about shared files? Can he thumbnails be copied over from user1/thumbnails to user2/thumbnails and be read by user2?

**Comment by schiesbn** [comment]
> What about shared files? Can he thumbnails be copied over from user1/thumbnails to user2/thumbnails and be read by user2?

Do we do something like this? Afaik also for shared files we create thumbnails for each user.

But it should work if a file gets copied we make sure to also copy the encryption keys.

**Comment by georgehrke** [comment]
> Do we do something like this? Afaik also for shared files we create thumbnails for each user.

We want to change that behavior. It doesn't make sense to store the same preview all over again,

**Comment by schiesbn** [comment]
> We want to change that behavior. It doesn't make sense to store the same preview all over again

What do you want to do exactly? Store the tumbnails only by the owner and always load it from there? This will probably not work if the thumbnails folder is encrypted because the thumbnail will only be encrypted for the owner, so a different user can't decrypt it.

**Comment by georgehrke** [comment]
> Store the tumbnails only by the owner and always load it from there? 

That was my intention.

> This will probably not work if the thumbnails folder is encrypted because the thumbnail will only be encrypted for the owner, so a different user can't decrypt it.

Well, if I am not completely mistaken, shared files itself are also not copied over but accessed directly in the owner's storage. When sharing, there is a dedicated key generated, so that the user, who the file was shared with, can access the file. We should be able to do something similar for the thumbnail itself?!

**Comment by oparoz** [comment]
> Store the tumbnails only by the owner and always load it from there? 

No, letting everybody use the original thumbnail folder probably wouldn't work because of permission issues, but I was thinking that maybe we could copy them over in order to speed up the process, because otherwise, each file has to be sent over so that we can generate a preview.

**Comment by schiesbn** [comment]
> We should be able to do something similar for the thumbnail itself?!

Yes, would be possible. Of course we could also update the keys for the thumbails if a file gets shared the same way we update the keys for the original file. But this would need some extra code specifically for thumbnails and then you can wait until we have the next special folder where we need a similar handling, etc. So I'm not sure if I want to go this way. If we do it we would probably find some more generic way on register some kind of "meta-data folder" for files. So that encryption could grab all the files and update them in a more generic way.

**Comment by georgehrke** [comment]
> permission issues [...] has to be sent over

Are you referring to cross-ownCloud sharing? We should definitely distinguish between sharing within one ownCloud instance and sharing between different ownCloud instances.

**Comment by oparoz** [comment]
@georgehrke - More like user2 wants a preview of a file in user1's cloud, but there is no thumbnail yet. If user2 has read-only access, he wouldn't be able to update the thumbnail folder and if we let user1's cloud do the processing, he might not be very happy about it?

**Comment by georgehrke** [comment]
Ok, copying would definitely make sense when referring to federated clouds, but within the same ownCloud instance, a preview, just like the file itself, should only be stored once.

**Comment by oparoz** [comment]
Makes sense for a file since no matter which rights are given to the user, the minimum required is `read`, but a missing thumbnail has to be created somewhere and that requires write access.
I don't think user1 would be very happy knowing that read-only user2 is able to create thumbnails in his user folder.

**Comment by PVince81** [comment]
@schiesbn any comment in the light of the new encryption ?

**Comment by PVince81** [comment]
Moving enhancement to 9.0 as we're past feature freeze.

CC @MTRichards @cmonteroluque @DeepDiver1975 FYI

**Comment by cmonteroluque** [comment]
@PVince81 agree, thanks

**Comment by loomy** [comment]
hi guys. I was just questioning myself if thumbnails are encrypted too and googled to this ticket.
imho encrypting my pictures is useless as long as the they are still accessible through the thumbnail.
you should at least give a hint on upgrading and show how to disable them. or even give an option.

is 
  'enable_previews' => false,  
enough?

...if you gave that hint and I just didnt read it, blame me

**Comment by AykutCevik** [comment]
Thumbnails are still not encrypted in the latest stable release (9.1.3) of owncloud. This makes encryption for images obsolete since any server host can still access private images of its users without doing any modification on the code. Is any progress made on this issue? Should be handled with a higher severity IMO.

**Comment by kdslkdsaldsal** [comment]
> you should at least give a hint on enabling encryption

Some notes about that is available here:


> This makes encryption for images obsolete since any server host can still access private images of its users without doing any modification on the code. 

The use case of the encryption app is not to protect your local files as widely known and explained here:

> Encryption keys are stored only on the ownCloud server, eliminating exposure of your data to third-party storage providers. The encryption app does not protect your data if your ownCloud server is compromised, and it does not prevent ownCloud administrators from reading user’s files.

https://doc.owncloud.org/server/latest/admin_manual/configuration_files/encryption_configuration.html

**Comment by PVince81** [comment]
@pmaier1

**Comment by kdslkdsaldsal** [comment]
@loomy It is protected with your login password. But everyone with access to your server (e.g. an administrator or an malicious user) can modify the ownCloud source code to:

1. Write out your plaintext password during the time you're logging in
2. Write out the plaintext files during the time you're accessing these

There is no way for ownCloud to protect you from this and there is no way that the Encryption app is protecting local files (e.g. thumbnails as requested here) from users having access to your local server.

**Comment by AykutCevik** [comment]
@kdslkdsaldsal since I'm hosting my own owncloud instance on my root server in a datacenter I would not write down any password to the harddisk. But if the hoster itself extracts my HDD he can view all unencrypted files easily - where he would find all the thumbnails of my owncloud instance.

This is definitely a security issue.

**Comment by kdslkdsaldsal** [comment]
@AykutCevik If you don't trust your hoster then you need to use client-side encryption. There are always possibilities that some one with physical access to your running server is able to get access to everything on your server.
