### ISSUE TITLE
External storage precondition failed after setting back correct password on unavailable storage

### ISSUE THREAD

**Issue by dragotin** [owncloud/core#11798]
I set up two ownClouds based on the setup described here: https://github.com/owncloud/core/issues/11759#issuecomment-60605070

Two things I noticed so far:
1. It seems to me that the communication between the two ownClouds does not maintain a session nor sending basic auth in the first place. That results in _two_ requests for each that has to be done, see access_log snippet:

```
::1 - - [27/Oct/2014:19:43:31 +0100] "PROPFIND /oc6/remote.php/webdav/V/v_0 HTTP/1.1" 401 291 "-" "-"
::1 - kf [27/Oct/2014:19:43:31 +0100] "PROPFIND /oc6/remote.php/webdav/V/v_0 HTTP/1.1" 207 438 "-" "-"
```
1. I modified a file while the mounted path on the server was not available. When I switch back to a working password, the client tries to sync the changed file up, which is correct. However, server answers the PUT with a "precondition failed" error message. Not sure why.
   
   Relevant log snippets, the file v_0 was modified during having the directory offline:

```
10-27 19:38:19:017 0x1de2af8 csync_walker: file: owncloud://localhost/oc/remote.php/webdav/V/v_0 [file_id=00004215ocf4dfb55645 size=204800]
10-27 19:38:19:017 0x1de2af8 _csync_detect_update: Database entry found, compare: 1413135539 <-> 1413135539, etag: 544e8f0e79c53 <-> 544e8f0e79c53, inode: 0 <-> 1323875, size: 204800 <-> 0, perms: RMDNVW <-> RMDNVW
10-27 19:38:19:017 0x1de2af8 _csync_detect_update: file: V/v_0, instruction: INSTRUCTION_NONE <<=
...
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\PreconditionFailed</s:exception>
  <s:message>An If-Match header was specified, but none of the specified the ETags matched.</s:message>
  <s:sabredav-version>1.8.10</s:sabredav-version>
  <s:header>If-Match</s:header>
</d:error>
```

@PVince81 @ogoffart can you doublecheck pls?

**Comment by PVince81** [comment]
Regarding auth, this is the new ticket https://github.com/owncloud/core/issues/12228

**Comment by PVince81** [comment]
Need to retry with 9.0 RC1, likely to still be an issue.

**Comment by PVince81** [comment]
@dragotin is this still happening in 9.0.3 or 9.1.0 RC1 ?

CC @jvillafanez

**Comment by PVince81** [comment]
Could not reproduce the issue with OC 9.0.5.

Possibly because since OC 9.0 the etag is computed based on the storage etag, so no mounting/unmounting etag change is actually happening.
