### ISSUE TITLE
Show error messages in external storage UI

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#11796]
So far, the only indicator whether a connection or setup error exists for external storage is the red dot.

The UI needs to accomodate for proper error messages and the server also needs to return such messages instead of just returning "false".

This would make it much easier to find out what settings were wrong, even if it's just by reading the error messages from the remote server.

CC @Xenopathic @owncloud/designers

**Comment by PVince81** [comment]
@DeepDiver1975 @karlitschek setting to 8.1, need to improve the UX...

**Comment by dronus** [comment]
I think error hiding in the case of many possible faults by the external server, the user entered data or a bug in OwnCloud itself is a  bug on it's own. It is not a feature lacking, but a mistake by the one who decided to not show information already known, but a red box instead. If the UX designer isn't able to get the problems reason, the mistake was made somewhere deeper the chain.

**Comment by PVince81** [comment]
@dronus no, it was not a conscious choice to hide the error message.
Technically, the error message is not given to the client so the client has no way of showing anything.

The code needs to be updated/rewritten in a way that allows for exceptions and error messages to be returned to the client for display.

**Comment by PVince81** [comment]
The error can now be seen by hovering on the red box.
