### ISSUE TITLE
Fix the retrieval of available apps from the app store

### ISSUE THREAD

**Issue by arkascha** [owncloud/core#11809]
To install an app from the owncloud app store I select the "Apps" app from the app menu and wait for the list of apps offered. 
In more than 80% of all my attempts I do NOT see any available 3rd party app. In the few succeeding attempts all apps are shown and can be installed without a problem.

**Comment by arkascha** [comment]
Just checked again, the issue is still not solved. 

Tried a network sniffer without result, since the communication with the app store is ssl encrypted. 

Added a few debugging hooks and a plausible reasons for the issue turned up: 
SimpleXMLElement Object
(
    [meta] => SimpleXMLElement Object
        (
            [status] => failed
            [statuscode] => 200
            [message] => too many API requests in the last 15 minutes from your IP address. please try again later.
        )
)
","level":4,"time":"2015-01-03T11:41:12+00:00"}

OK, that looks pretty much straight forward to me. 
I wonder, why Frank could not reproduce this in his attempts, though. 

So a repeated request of the list of apps leads to silent errors. In my case it is the third repetition of reloading the apps page. 
I suggest that either the limit should be raised, at least for these requests (reloading the apps page in short successions is not THAT surprising...), or the issue (which is obviously known to owncloud, since the app store gives a clear error message) should be visualized to the user! Something like: "sorry, please try again later". Not convenient, but at least the user knows what is going on! 

I for myself got the feeling that it is a strange strategy to first split retrieving the list of available apps into many many requests to an API (why?) and then to limit the number of requests permitted to that API. But I may be wrong there.

**Comment by tobiasKaminsky** [comment]
Or cache the items and only refresh the app infos once an hour.
(I doubt that there are changes so often...)
So, even if the request fails, it will show the cached items, which is better than showing only some apps...

**Comment by arkascha** [comment]
@tobiasKaminsky Indeed! A very obvious and good solution.

**Comment by tobiasKaminsky** [comment]
Maybe @karlitschek cannot reproduce this bug as he has (maybe) an IP address that is whitelisted?
At least this is something I am doing for testing at work...

**Comment by arkascha** [comment]
Sure, could be an explanation. But still there is something odd: 

As written before the behavior was not really deterministic for me: I did not get that effect always once it started, but on every 2nd attempt, roughly. In repeated reloads I sometimes got none, sometimes a few and sometimes all available apps (whatever all is here). And there were not 15 minutes between the attempts, but less than a single minute (the app page takes endless to load...).

I have the impression something has changed, since now I always get no apps except the bundled and installed. That makes sense looking at the error message, but it does not fit the former behavior. I would guess that something has been changed inside the API / the server, maybe even to prevent errors on the server aide. But then, there was no notion about such change in this issue here...

**Comment by karlitschek** [comment]
wow. This was the error message I was looking for. I will fix this. Thanks a lot guys.

**Comment by LukasReschke** [comment]
https://github.com/owncloud/core/pull/13212 works around this if a memcache is installed. (APCu, XCache, Redis, etc…)

**Comment by arkascha** [comment]
I really hesitate to reopen this ticket, but: 
Checked again in OC-8.0.2 and now it appears that there are no third party apps at all offered in owncloud any more. Not at all. None. Only bundled apps are offered and visible for me.

**Comment by RealRancor** [comment]
Are you getting contacts, calendar and search_lucene?

**Comment by arkascha** [comment]
@RealRancor Indeed, those are offered. So maybe only "recommended" apps are offered now? 
I have no idea, frankly. This is all the exact contrary of transparency...

**Comment by RealRancor** [comment]
Those are apps pulled from the appstore, so this works. On my instance i'm also getting the imprint app shown.

**Comment by arkascha** [comment]
imprint is interesting. So it is not even only "recommendeed" apps. 
So it looks like this issue here has NOT been fixed.

**Comment by PVince81** [comment]
Is this still happening with 7.0.7, 8.0.5 or 8.1 ?

**Comment by arkascha** [comment]
Still exactly the same issue in 8.0.5, still exactly the same error message as 8 month ago: 
    {"reqId":"b0d4ef7d56352b1c7fe43923b085eaa3","remoteAddr":"95.91.225.200","app":"core","message":"Invalid OCS content returned for app 166051","level":4,"time":"2015-08-07T20:58:17+00:00"}
    {"reqId":"b0d4ef7d56352b1c7fe43923b085eaa3","remoteAddr":"95.91.225.200","app":"core","message":"Invalid OCS content returned for app 166056","level":4,"time":"2015-08-07T20:58:17+00:00"}
    {"reqId":"b0d4ef7d56352b1c7fe43923b085eaa3","remoteAddr":"95.91.225.200","app":"core","message":"Invalid OCS content returned for app 166047","level":4,"time":"2015-08-07T20:58:17+00:00"}
    {"reqId":"b0d4ef7d56352b1c7fe43923b085eaa3","remoteAddr":"95.91.225.200","app":"core","message":"Invalid OCS content returned for app 166046","level":4,"time":"2015-08-07T20:58:17+00:00"}
    {"reqId":"0cb5cfaba09ccdace3790eba9d72f40d","remoteAddr":"95.91.225.200","app":"core","message":"Invalid OCS content returned for app 166048","level":4,"time":"2015-08-07T20:58:21+00:00"}
    {"reqId":"0cb5cfaba09ccdace3790eba9d72f40d","remoteAddr":"95.91.225.200","app":"core","message":"Invalid OCS content returned for app 166049","level":4,"time":"2015-08-07T20:58:21+00:00"}
    {"reqId":"0cb5cfaba09ccdace3790eba9d72f40d","remoteAddr":"95.91.225.200","app":"core","message":"Invalid OCS content returned for app 166051","level":4,"time":"2015-08-07T20:58:21+00:00"}
    {"reqId":"0cb5cfaba09ccdace3790eba9d72f40d","remoteAddr":"95.91.225.200","app":"core","message":"Invalid OCS content returned for app 166056","level":4,"time":"2015-08-07T20:58:21+00:00"}
    {"reqId":"0cb5cfaba09ccdace3790eba9d72f40d","remoteAddr":"95.91.225.200","app":"core","message":"Invalid OCS content returned for app 166047","level":4,"time":"2015-08-07T20:58:21+00:00"}
    {"reqId":"0cb5cfaba09ccdace3790eba9d72f40d","remoteAddr":"95.91.225.200","app":"core","message":"Invalid OCS content returned for app 166046","level":4,"time":"2015-08-07T20:58:21+00:00"}

**Comment by MorrisJobke** [comment]
This has been improved a lot for 8.2 AFAIK - @LukasReschke worked on this.

**Comment by MorrisJobke** [comment]
Please reopen if you still have issues getting apps installed from the app store with 8.2.x
