### ISSUE TITLE
Implement high level file locking

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#11804]
Currently the files_locking app only works on storage level, which is not enough to guarantee atomicity of operations. This is because we have hooks and proxies and apps are able to perform additional filesystem operations.

A high-level file locking mechanism should be implemented to guarantee atomicity of file operations on a higher level.

For example, this is what happens when renaming an encrypted file:
1) User renames file
2) System calls `$view->rename()`
3) File is renamed on the storage
4) Encryption keys are renamed
5) Version files are renamed

Since files_locking only operates on storage level, only step 3) is locked.

If after step 3) someone renamed the new file to yet another name, they will get a "share key not found" error.

The high-level locking mechanism would work as follows:
1) User renames files
2) System calls `$view->rename()`
3) A lock is set on source and target file names
4) File is renamed on the storage
5) Encryption keys are renamed
6) Versions are renamed
7) Lock is released

Also note that files_locking does not lock folders.

There's also the open question whether parent folders should be locked and whether folder locking is feasible at all.

Here is an example of what kind of race conditions happen due to lack of high-level locking: https://github.com/owncloud/core/issues/11795
(rename a folder while the sync client is uploading files into it)

@craigpg @karlitschek @MTRichards @DeepDiver1975 @icewind1991 @schiesbn @bantu

**Comment by PVince81** [comment]
Some ideas:
- implement file locking on view level using file paths from the user's point of view (with mount points)
- for shared folders, always lock the paths of the owner

- save locks in a DB table or memcache (interchangeable by abstracting the "lock provider")
- lock provider can be instantiated by Storage classes (in case we could even use flock on some 
storages)

- no difference between read/write locks

**Comment by karlitschek** [comment]
related https://github.com/owncloud/core/issues/11734

**Comment by PVince81** [comment]
- [ ] locking provider
   - [ ] acquire lock (shared lock, exclusive lock)
      - [ ] $view->acquireLock() / releaseLock() => calls $storage->acquireLock() ...
      - [ ] $storage->acquireLock() / releaseLock() => calls locking provider
   - [ ] timeout handling
   - [ ] fileid or path based ? (on owner)
   - [ ] memcache (first)
   - [ ] database (second, if needed)
- [ ] plug it into the code (View)
- [ ] return proper locking codes to the client (through exceptions ?)
- [ ] special cases for direct storage access (file PUT)

**Comment by PVince81** [comment]
- [ ] scanner needs to lock too

**Comment by PVince81** [comment]
- [ ] unit test: acquire lock directly, then call $view->operation to ensure that it also acquires the lock

**Comment by PVince81** [comment]
- [ ] raise smashbox ticket with matrix of operations

**Comment by PVince81** [comment]
- [ ] refresh lock for long running operations ? (touch operation)

**Comment by PVince81** [comment]
- [ ] release lock on shutdown handler, if possible

**Comment by PVince81** [comment]
- [ ] config.php switch to "Enable EXPERIMENTAL locking"

**Comment by PVince81** [comment]
- [ ] allow locking outside of "files" (like files_trashbin, thumbnails), but probably not "files_encryption" and "cache"

**Comment by PVince81** [comment]
Assigning @icewind1991 as discussed. Feel free to ping me any time if you want to discuss stuff :smile:

**Comment by karlitschek** [comment]
same here. this has very high priority. let me know if there are any question.

**Comment by DeepDiver1975** [comment]
setting 8.1

**Comment by jnfrmarks** [comment]
@davitol @SergioBertolinSG 

FYI: we need to write a test plan for this.

**Comment by karlitschek** [comment]
@icewind1991 Do you have an ETA?

**Comment by LukasReschke** [comment]
> save locks in a DB table or memcache (interchangeable by abstracting the "lock provider")

Have we considered that data in the memcache can disappear *any* time? – Not all memcache providers are guaranteeing it's availability, what they do is ensuring it's integrity.

In a nutshell: If we put data in a memcache and memcache returns it, we can be sure that it will be the one we put into it. But this data might disappear any time even without having the timeout passed. This is for example how memcached works.

Comment on this would be great – didn't check the implementation and just stumbled upon this while checking all open PRs.

**Comment by LukasReschke** [comment]
Also cc @butonic since he is one of our memcache fans ;-)

**Comment by butonic** [comment]
I am a redis fan because it is a proper let value store, not just a cache that only guarantees that a value is not longer stored than specified by the ttl. Using memcache to store locks is the wrong approach.

**Comment by butonic** [comment]
Redis is an option, though.

**Comment by LukasReschke** [comment]
Mhm. Maybe we need to start differentiating between cache / key-value store. We already do support a switch for local and remote caches. (i.e. a fast local one and a slow remote one)

Ideas?

**Comment by DeepDiver1975** [comment]
> Have we considered that data in the memcache can disappear any time? – Not all memcache providers are guaranteeing it's availability, what they do is ensuring it's integrity.
> 
> In a nutshell: If we put data in a memcache and memcache returns it, we can be sure that it will be the one we put into it. But this data might disappear any time even without having the timeout passed. This is for example how memcached works.
> 
> Comment on this would be great – didn't check the implementation and just stumbled upon this while checking all open PRs.

nice input - @PVince81 @icewind1991 FYI

**Comment by PVince81** [comment]
So should we move the Redis then ? I'm not familiar with any of these technologies.
Or put the locking info in the database as originally discussed ?

**Comment by PVince81** [comment]
Note: moving to any other technology that is not memcache or database means an admin will need to configure additional servers in config.php. From reading the ownCloud docs it seemed that we don't have any Redis usage yet. So this means in some cases an admin will have to configure both Redis and Memcache (for other things). Are we ok with this ?

**Comment by butonic** [comment]
The default implementation should use the database. Redis can completely replace memcached (store sessions as well as cache), so admins will likely choose only one of those key value stores. For locking I think memcached is not an option as locks disappearing because memcached decided to free up some space kind of defeats the purpose of locks...

**Comment by LukasReschke** [comment]
> Note: moving to any other technology that is not memcache or database means an admin will need to configure additional servers in config.php. From reading the ownCloud docs it seemed that we don't have any Redis usage yet. So this means in some cases an admin will have to configure both Redis and Memcache (for other things). Are we ok with this ?

Basically the wording "memcache" is confusing. ownCloud uses "memcache" as term for the cache that ownCloud uses for data, that can be anything and also includes memcached, see https://github.com/owncloud/core/blob/5941e826b8e6005de08fdcb777efb3def5ca8101/config/config.sample.php#L814-L824

Some of this ownCloud "memcaches" are not really suited as key-value store such as Memcached, while others as Redis would be completely fine to use as "memcache" and key-value store. That's the problem we face :see_no_evil:

**Comment by PVince81** [comment]
I just found that we already have Redis settings in config.sample.php, so might be fine to use it.

**Comment by PVince81** [comment]
One challenge with the database approach is that the locking table updates need to be atomic too. If we can use DB transactions we might be fine.

**Comment by bantu** [comment]
Packagist might have some library implementing most of what is required. A very quick search for example finds https://github.com/arvenil/ninja-mutex.

**Comment by icewind1991** [comment]
Redis can already be used atm since we have it as "memcache" implementation.

Since locking will be optional first we dont need a default db backend at first imo.

> https://github.com/arvenil/ninja-mutex

Only provides mutex lock, we want shared/exclusive locks

**Comment by LukasReschke** [comment]
> Since locking will be optional first we dont need a default db backend at first imo.

Needs to get documented then in the config option best – otherwise this opens a can of unexpected bugs :boom:

**Comment by karlitschek** [comment]
The easiest option for now might be the database as @butonic said. redis is a better option but more as an step 2.

**Comment by icewind1991** [comment]
As I said, a redis backend is already implemented and working atm, I'm not sure about implementing a database backend regarding the atomic primitives (inc, dec, cas, add).

**Comment by karlitschek** [comment]
Well the redis mackend might be implemented. But this doesn´t mean that it is available and configured on all installations. For 8.2 this feature should be switch on for all users if it works. So database might be a good first step here. 
What do you think?

**Comment by MTRichards** [comment]
Dumb question: how many folks out there are using Redis, have it in an operating environment and are ready to use it in production?

**Comment by MTRichards** [comment]
From what I can tell, it is highly popular and growing, but by no means universal.

**Comment by DeepDiver1975** [comment]
All our initial assumptions were based on the assumption to go memcache first.
Introducing now the requirement to have a database backend will lead to additional time being required.

If memecache now proves to eb not reliable enough we go back to start.

**Comment by karlitschek** [comment]
o.k. I don´t want to make this more complicated now. Then let´s do the DB based solution later. :-) But we will need it at some point of time.

**Comment by DeepDiver1975** [comment]
> But we will need it at some point of time.

this was already part of the initial design decission

**Comment by LukasReschke** [comment]
> If memecache now proves to eb not reliable enough we go back to start.

Then we need to document properly that i. an distributed environment using memcached is not an option as ownCloud cache and Redis should get used. Otherwise this is not that reliable ;-)

Memcached is simply not a really reliable key-value store. Redis is. - This needs to get explained to our users and also our folks that do deployments :see_no_evil:

**Comment by MTRichards** [comment]
@bboule For deployment scenarios
@carlaschroder for documentation

**Comment by bboule** [comment]
So it sounds like we need to prepare both adjustments in our deployment recommendations for new install and we will also need to gear up for upgrades.  Not a huge issue, but simply something that we will need to be prepared to do. I dont think most people really care which KVS they use (we told them), but we will need to be prepared to force them to make that change (from memcache to redis) and in most cases walk them through it. If having memcache is a risk, we might also look for a way to block an upgrade if we see it (asking the user to contact us) citing this specific issue (to prevent harm) as I am not sure most people will pull off the transition themselves.

**Comment by karlitschek** [comment]
So at the moment this is some testing/beta feature which is disabled by default. Just for selected scenarios/users. If this is successful then we should put this into 8.2 which then will be DB based. so hopefully this is no additional hard requirement

**Comment by DeepDiver1975** [comment]
@jnfrmarks @PVince81 do we have smashbox tests which are failing as of today because of missing locking? If not we shall implement them asap. THX

**Comment by PVince81** [comment]
testConcurrentDirMove might be one, but fails only randomly on some envs.

If we had a way to slow down the server (or dynamically add breakpoints with XDebug :wink:) it could then become easier to reproduce such issues consistently.

**Comment by PVince81** [comment]
There is another fundamental issue that we'll eventually need to think of, related to APIs: so far we ask every app to use the public API, which is the node based files API (OC::$server->getUserFolder()). That API uses the View. So far so good, this means app will benefit from locking too.

The trouble is that now we're changing the trashbin and versions app to use the Storage instead of the Node API. This is because using the node API would lock several times. It starts to feel like in the end the Storage API will need to be made public eventually... which is not really what we wanted.

Originally I thought we could have a method `lockPath()` in the node API that apps can call to tell ownCloud when they start working with a file, and `releasePath($path)`. Every subsequent calls on `lockPath()` within the same PHP request would not double lock the same path, but just do as shared locks do: increment a counter. I think it is still possible to add this a bit later once the groundwork for locking is done (and also discuss whether we want this).

**Comment by PVince81** [comment]
Well this would also mean that apps like trashbin and versions should be able to work with the public node API too in the end (and not use the private View or Storage API)

**Comment by PVince81** [comment]
- [ ] think about all the places where we want to explicitly "lock before a big bunch of operations" and "release lock afterwards". 
    - [ ] file upload: we need to bundle everything from "precondition check" to "final rename" inside a single transaction (currently the precondition check is done early but there is no guarantee that it is still true at the time of the rename)

**Comment by PVince81** [comment]
We can probably discuss the individual cases in separate tickets once the main work is merged.

**Comment by PVince81** [comment]
Note for testers: to enable this feature you need to set "filelocking.enabled" to "true" in config.php and also configure a memcache server. (redis coming later)

**Comment by icewind1991** [comment]
> redis coming later

Redis already works if you configure redis as your memcache backend

**Comment by PVince81** [comment]
Raised https://github.com/owncloud/smashbox/issues/94 about writing a special app that could help recreate the race conditions more consistently.

**Comment by PVince81** [comment]
- [ ] should solve concurrent scanner runs ("Duplicate entry" messages): https://github.com/owncloud/core/issues/16584

**Comment by PVince81** [comment]
- [ ] more user friendly error messages in the web UI when a file is locked

**Comment by PVince81** [comment]
- [ ] also lock properly for system-wide external storage mount points (to be discussed)
This is once again an opportunity to mention my idea of getting rid of "applicable" for external storages but using the "sharing" approach instead (admin mounts ext storage locally, shares with applicable users/groups), to avoid requiring custom code specific to ext storage and simply reuse the sharing one: https://github.com/owncloud/core/issues/11182

**Comment by PVince81** [comment]
- [ ] add LockInfo information in the Sabre Lock response

**Comment by PVince81** [comment]
More issues and test steps documented here: https://github.com/owncloud/core/issues/16664

**Comment by carlaschroder** [comment]
Please review docs https://github.com/owncloud/documentation/pull/1182

**Comment by PVince81** [comment]
@icewind1991 @DeepDiver1975 how about "short waiting time when acquiring before abort" ?
Currently it seems to directly acquire a lock or fail directly.

In the files_locking app we had a usleep().
But anyway, this is more about tweaking locking performance.

**Comment by PVince81** [comment]
raised wait-retry as https://github.com/owncloud/core/issues/17016

**Comment by PVince81** [comment]
Most of this has either been implemented already or raised as separate tickets.

We can either close it or keep it to keep an overview (but then remove the severity tags?)

**Comment by PVince81** [comment]
There are tickets for the remaining issues, tasks => closing
