### ISSUE TITLE
WebDav: Using "allprop" on PROPFIND does not behave as expected

### ISSUE THREAD

**Issue by DecaTec** [owncloud/core#11803]
When using WebDav, the PROPFIND method is used to get a list of WebDav properties (i.e. files and folders saved in ownCloud). When using the so called "allprop" on PROPFIND, ownCloud seems not to include all properties (defined in RFC4918 "HTTP Extensions for Web Distributed Authoring and Versioning (WebDAV)") in the response.

As an example: Let's assume that the "displayname" was changed on a file with a previous PROPPATCH command. Using an allprop-PROPFIND, ownCloud only returns the following properties: oc:id, oc:permissions, d:getetag, d:getlastmodified, d:resourcetype, d:quota-used-bytes, d:quota-available-bytes. According to RFC4918, an allprop-PROPFIND must return all live properties defined in the specification plus dead properties. 
As a side note: d:quota-used-bytes, d:quota-available-bytes are not defined in RFC4918 and should not be part of the namespace xmlns:d="DAV:".

On the other hand: Trying to request a specific named property (in this case "displayname") with PROPFIND, the request content will look like this:

&lt;propfind xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;DAV:&quot;&gt;&lt;prop&gt;&lt;displayname /&gt;&lt;/prop&gt;&lt;/propfind&gt;

In this case, the correct property with it's content is returned.

Is this a bug or is this behavior on allprop-PROPFIND on purpose?

ownCloud version is 7.0.2

**Comment by PVince81** [comment]
Upgrade to sabre 2.0 ticket here: https://github.com/owncloud/core/issues/12876 PR here https://github.com/owncloud/core/pull/14151

**Comment by PVince81** [comment]
Upgrade to Sabre 2.0 has been merged to master.

The hacks that included some "oc:*" properties in "allprops" are now removed.
All OC clients that require such attributes must request them explicitly.

Closing.

(also see https://github.com/owncloud/core/issues/11803#issuecomment-60811308)
