### ISSUE TITLE
owncloud sharing notification emails without shared resource

### ISSUE THREAD

**Issue by kalletabur** [owncloud/core#11808]
Our team has experienced weird notification emails - email subject doesn't have shared resource name and link (named "View it!") is broken

Email:
Email subject: John Doe shared »« with you
Body:
Hey there, 
just letting you know that John Doe shared with you. 
View it! 
Cheers!

Links:
https://serverURL/index.php/apps/files?dir=
and
https://serverURL/index.php/apps/files?dir=%2F&scrollto=

Such emails are not sent everyday but still on regular bases over month already. These emails started to appear after upgrade from 6 to 7.
Maybe related to issue https://github.com/owncloud/core/issues/11757

#### ownCloud log (data/owncloud.log)
```
{"reqId":"542a8145d6f1f","app":"mail","message":"Mail from John Doe (sharing-noreply@serverURL.email.com) to: Jane Doe(j.doe@email.com) subject: John Doe shared \u00bb\u00ab with you","level":0,"time":"2014-09-30T13:09:20+03:00","method":"POST","url":"\/index.php\/core\/ajax\/share.php"}
{"reqId":"542a8145d6f1f","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/share\/mailnotifications.php#90","level":3,"time":"2014-09-30T13:09:20+03:00","method":"POST","url":"\/index.php\/core\/ajax\/share.php"}
```

### Server configuration
Debian 7.6 + nginx + php5-fpm (5.4.4-14) + MySQL + ownCloud 7.0.2-1

**Comment by DeepDiver1975** [comment]
issue has been solved meanwhile - https://github.com/owncloud/core/pull/12030#issuecomment-75752929
