### ISSUE TITLE
Compute and store file checksums on the fly / file integrity

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#11811]
To guarantee file integrity between the server and the sync client, we can compute a checksum based on the file contents. The checksum can be calculated on the fly using a rolling checksum function, for example using `hash_update`: http://php.net/manual/en/function.hash-update.php

The hash can then be used to compare file versions and detect conflicts or broken files, broken transfers, etc...

The only challenge I see so far is for external storage, whenever a file is changed remotely. In this case, if the scanner detects a change the hash could be marked as dirty and be recomputed on the next occasion. The lest efficient method would require the scanner to download the file for the sole purpose of computing the hash, which is slow.

Also, should the hash be used for the etag as well ?

Let's discuss @dragotin @icewind1991 @DeepDiver1975 @karlitschek @craigpg @MTRichards

**Comment by guettli** [comment]
@moscicki  Thank you for your proposal from 22. Nov 2014. I am missing an explanation why this can not be used for ETags. Please be explizt. Cheksums can be used for  integrity and to avoid unneeded duplicate file transfer. Please update the proposal why this is not related to ETags. Thank you.

**Comment by zatricky** [comment]
@guettli - I don't think anybody has explicitly said that it *cannot* be used as the etag or that it cannot be a part of the etag. So far all comments are along the lines of "Should it be used?", "It can be used", and "the bugs giving you concern (that you think this will help fix) should be fixed first".

**Comment by zatricky** [comment]
@guettli - In the proposal, it is merely stating that the proposal has nothing to do with etags - not that checksums cannot be used.

**Comment by dragotin** [comment]
related #12417

**Comment by guruz** [comment]
We discussed about this some more and want the for now simpler solution in https://github.com/owncloud/core/issues/18716

**Comment by dragotin** [comment]
#18716 was closed, however the current implementation lacks the verification of the checksum on the server. So does it make sense to track that requirement here?

**Comment by PVince81** [comment]
Yeah, let's keep this ticket open

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/issues/26655 with more detailed tasks
