### ISSUE TITLE
file name encryption for owncloud

### ISSUE THREAD

**Issue by JimLoose** [owncloud/core#11814]
Beside the lack of thumbnail and gallery encryption (which makes the extension useless)

**the encryption module currently misses "file name encryption" as well**

**Comment by JimLoose** [comment]
is it possible to place a bounty for that?

:+1:

**Comment by RealRancor** [comment]
Yes, see here: https://www.bountysource.com/issues/5576961-file-name-encryption-for-owncloud

**Comment by privacytoolsIO** [comment]
File name encryption would be really nice.

**Comment by idano** [comment]
this feature makes or breaks my use case for owncloud as I'm planning to run this on a remote vps. While it's great that the content is encrypted, the filename still gives away a lot of information for example for financial records etc.

**Comment by RealRancor** [comment]
@idano Please consider in your use case:

> Encryption keys are stored only on the ownCloud server, eliminating exposure of your data to third-party storage providers. The encryption app **does not** protect your data if your ownCloud server is compromised, and it **does not* prevent ownCloud administrators from reading user’s files. This would require client-side encryption, which this app does not provide. If your ownCloud server is not connected to any external storage services then it is better to use other encryption tools, such as file-level or whole-disk encryption.

https://doc.owncloud.org/server/8.2/admin_manual/configuration_files/encryption_configuration.html

**Comment by idano** [comment]
Thanks for clarifying RealRancor.
