### ISSUE TITLE
Chaotic layout and styling of templates

### ISSUE THREAD

**Issue by arkascha** [owncloud/core#11827]
While porting the "imprint" app to OC-7 I once more stumbled about issues with the basic markup structure implemented in the page templates and their styling. 

Apps like "imprint" especially must be able to rely on a certain continuity of the markup between different views, themes and versions. Otherwise a real integration is impossible to code. I do understand that most apps can safely ignore this, since they only provide some content shown inside the content area of the templates. But then again this is absolutely no reason not to take a little care when implementing the templates. 

Two examples: 
* The layout differs in a non-trivial way between the guest and the login template, although they appear practically optical identical. Why the difference?
* The user view template implements a few elements inside the top header bar. Whyever (there really is absolutely no reasons for this), some of these elements are styled using am absolute positioning, some using a relative positioning. Can you imaging the problems such chaos creates for an app trying to inject something into that header bar? I know that this was nothing intended to be supported by the person implementing the template. But again: that does not mean that a more sane layout would not make sense. For the imprint app I overwrote those styling rules to force a better layout. This has absolutely no negative effects on everything, as far as I can see. 

So why the chaotic styling in the first place? Why make things so much more complex than they have to be? Why make the life of 3rd party developers harder without need?

**Comment by DeepDiver1975** [comment]
closing because of inactivty
