### ISSUE TITLE
[7.0.3rc1]Self signed Problem when Server2Server sharing 

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#11822]
I found a big problem testing today, when Self signed certificate are created:

### Problem
Two ownCloud instance running on different machines with https enabled (Self signed certificate)

I can see contents of a shared folder in the browser (even in private browsing mode)

### Steps:

1. Make sure Remote share is enabled (on both)
2. Create public share (tested both possibilities: non authenticated and authenticated) on 1st instance
3. Open it in the browser (I can see contents, download and work on the information)
4. Click add to ownCloud
5. type 2nd instance url: https://second/owncloud and click on the arrow
6. Successfully redirected to second instance
7. Shows confirmation with the message: Do you want to add the remote share
folder from user at first/owncloud ?
8. Click Add remote share
9. Error message: Couldn't add remote share

Do not see any new logs in either owncloud.log

Only log 2 different error messages:
```
"app":"webdav","message":"Sabre\\DAV\\Exception\\Forbidden: Requested uri (\/oc703rc1\/remote.php\/webdav) is out of base uri (\/oc703rc1\/\/remote.php\/webdav\/)","level":4,"time":"2014-10-27T15:03:57+00:00"}

{"reqId":"544e607f26456","app":"PHP","message":"Cannot modify header information - headers already sent at \/var\/www\/html\/oc703rc1\/lib\/private\/json.php#17","level":3,"time":"2014-10-27T15:10:55+00:00","method":"GET","url":"\/oc703rc1\/\/index.php\/apps\/files\/ajax\/newfile.php?dir=%2F&source=https%3A%2F%2Fdamken.ddns.net%2Fpublic.php%3Fservice%3Dfiles%26t%3D8fcba29e76c5ddac2e4a2ee3af19af61%26path%3D%252F%26files%3DHACKDIET.PDF%26download&filename=public.php%3Fservice%3Dfiles%26t%3D8fcba29e76c5ddac2e4a2ee3af19af61%26path%3D%252F%26files%3DHACKDIET.PDF%26download&requesttoken=d0c4241e40780cef116e"}
```
@MTRichards @craigpg @jnfrmarks

**Comment by MorrisJobke** [comment]
@cdamken Please reopen if this is still a issue for you.
