### ISSUE TITLE
Move hamburger menu into header and reduce the amount of menus

### ISSUE THREAD

**Issue by jbtbnl** [owncloud/core#11828]
The current situation is that the hamburger menu is shown on top of `app-content`. This is a non-desirable situation as developers assume, and should be allowed to, make use of app-content to the full extend without worrying about the responsive ownCloud design.

__Proposal 1:__
Let's move the hamburger menu into the header. Something like:

![screenshot from 2014-10-28 21 14 50](https://cloud.githubusercontent.com/assets/639688/4816469/d6f1e708-5edf-11e4-9bf4-03895a0e6983.png)

One might notice that this makes the header look crowded on a mobile device. Why? Well, because there are now three (!) menus embedded in one header bar:
- hamburger menu (app sidebar)
- app switcher menu
- personal settings menu

I hope that my proposal (1) will not be set aside with arguments like "it makes the header too crowded!". The hamburger menu really belongs there, since in-app navigation is the topmost important thing while using an ownCloud app. Therefore:

__Proposal 2:__
Reduce the amount of menus :smile:

**Comment by jancborchardt** [comment]
I’ll close this since none of the suggestions were really better than what we currently have. And actually I think the current design makes a lot of sense (otherwise we wouldn’t have done it like that ;)
