### ISSUE TITLE
Deleted files not going to the trash with unlimited quota

### ISSUE THREAD

**Issue by pscoffoni** [owncloud/core#11838]
Hi,

When the quota for a user is set to unlimited, the deleted files are not keeped. I've got this info message for example
Info 	files_trashbin 	remove "image_083.jpg" (14590B) to meet the limit of trash bin size (50% of available quota) 
If I set the quot to everey thing elese like 100 GB, deleted files are keeped in the trash...

This happend with Owncloud 7.0.2

Sorry for my poor english

Philippe

**Comment by karlitschek** [comment]
closing this because not possible to fix and probably out of scope for owncloud
