### ISSUE TITLE
Page is blocked when using files_external and remote host is down

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#11833]
The files_external application is blocking the loading of the admin and user page if the remote host of a mountpoint is not reachable anymore.

To reproduce this mount a remote WebDAV share and then take the remote server offline. - Opening the pages will then take about 30 seconds.

This is very bad user experience and we should move this to an AJAX check.

**Comment by Xenopathic** [comment]
This problem also occurs when listing a view that contains the downed remote storage. The cache scanner attempts to read files inside the storage, which times out in exactly the same way as the settings pages does.

**Comment by Xenopathic** [comment]
Woop, fixed with #11884!
