### ISSUE TITLE
Cache remote files locally from external storage

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#11839]
For the use case where specific files from external storage are accessed often, one idea is to download and cache that file locally in the ownCloud instance (for example in the "cache" folder). If the file isn't re-read for a given amount of time, it is deleted from the local OC cache folder.

The admin could specify how much cache is allocated per storage and/or user.

Whenever a cached file is modified it is first modified only in the cached version, and then "synced up" after a specific time. (note: conflicts might occur if files are modified outside OC, so not sure whether this is a good idea)

Then the question: how often would a single version of a file be accessed ? Whenever someone uses the sync client, that file is only downloaded once. But if the same file is downloaded by multiple, then there is an extra overhead of having to proxy it every time from the remote storage through OC back to the user.

When accessing files over the UI, the file would be opened/downloaded every time. In this case the local file caching would help as well.

This idea could, in general, improve remote file access speed.

What do you think ?

@icewind1991 @schiesbn @DeepDiver1975 @MTRichards @karlitschek @craigpg

**Comment by PVince81** [comment]
Somewhat related: using csync to sync with external storages: #5225

**Comment by mrubioroy** [comment]
Would this allow to extend local storage space like macOS Sierrra does with iCloud?
https://support.apple.com/en-us/HT206996#storeinicloud
If yes I'd like to encourage you to bring this soon. It'd be great to have an ownCloud solution for ultraportables with limited local storage.
Kudos for your great work anyway!

**Comment by PVince81** [comment]
Sync conflicts are a problem, yes.

The way I see it is that we need to create conflict files for these and have these visible somewhere.
Considering that users usually don't see conflict files in their ownCloud storage since we don't upload them, I think we should first change the behavior to actually upload conflict files: https://github.com/owncloud/client/issues/4557. Then it would be a normal thing for users to see conflict files there, regardless whether they come from a desktop client or an external storage sync.
