### ISSUE TITLE
Redesign/revamp oc_storages to fix various issues

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#11830]
Currently the `oc_storages` has no real unique database id but requires the PHP code to build ids on the fly.

Here is how the `oc_storages` table looks like:
```
MariaDB [owncloud]> select * from oc_storages;
+---------------------------------------+------------+
| id                                    | numeric_id |
+---------------------------------------+------------+
| 77703924cafa1097220e2ff1a8d2b0e7      |          3 |
| home::root                            |          1 |
| local::/srv/www/htdocs/owncloud/data/ |          2 |
+---------------------------------------+------------+
```

First, the `id` column must be computed in PHP based on the following logic:
1) If we're looking for the storage of user "someuser", then the id will be "home::someuser"
2) If we're looking for the entry of a specific external storage, the id is computed based on a custom algorithm which depends on the external storage backend. For example SMB would generate an id like `smb://user@host/rootpath`.

Additionally if the id's length is bigger than 64 characters, then the `md5()` of that id will be used.

The current schema is troublesome, because:
1) Reverse lookups by id are not possible: when the md5() function kicks in, it is not possible to get the user id directly. One needs to iterate over ALL users (imagine LDAP with millions of users) to find out to who this storage belongs.
2) We already have another id called "numeric_id", why not use that instead ?

@icewind1991 @DeepDiver1975 does anyone know why we have these string ids in the first place ?
Why not use the numeric_id ? Every user could have a `oc_preferences` entry mapping them to a given storage. This would prevent strange and bad issues like the legacy storage + data dir moving issue (#10897).

What speaks against discarding the storage `id` string column and working only with the `numeric_id` ?
We cannot rely on the storage `id` column to detect duplicate mount configurations (from external storage).

I suggest to do the following:
1) Get rid of `oc_storages`. If not, at least get rid of the `id` column and use a purely `numeric_id` based access.
2) Every user gets a `storage_id` in their `oc_preferences` table that points to their home storage id. This way there will be no more slippages (legacy storage issues with lost shares, etc...)
3) The external storage mount configuration mount.json will also be extended with a "storage_id" parameter that points to the id of the matching storage. That id is created as soon as the mount point is added.
4) Optional: move mount.json into a table ? Are there may use cases for that file ?
5) Optional: add a column "owner" to the `oc_storages` table which could make resolving file owners from shares easier instead of having to jump through hoops

What do you think ?

**Comment by mmattel** [comment]
As described in the top:

I like the suggestion of @PVince81 to do a oc_storages cleanup and a extension of mount.json
This would be much more consistant and managable than it is right now.
Keep in oc_storages the columns,
...numeric_id is a unique number identifying the storage, a reference number
...id will only keep the type and path, so it is visible where the numeric_id belongs to

And as a extension, all files or folders shared need to get in their table a storage_id in addition.
Or in other words, all tables containing any reference to a file or folder will get a column storage_id added and referenced

**Comment by PVince81** [comment]
@mmattel I agree about the storage_id column/mapping. I thought I had documented this already but can't find it any more.

**Comment by mmattel** [comment]
I can not support you from the coding point of view. My knowledge is limited here.
But it is imho urgently necessary to do these adoptions due to the success of owncloud and its broader acceptance. It is maybe not easy to do, but as later it is done, as more complicated it will become...

**Comment by PVince81** [comment]
Something related: mapping user name to storage https://github.com/owncloud/core/issues/15166

@DeepDiver1975 I'll set this to 8.2

Also CC @MorrisJobke who also went through the storage pains before

**Comment by PVince81** [comment]
Another case of storage id mismatch which leads to loss of shares: https://github.com/owncloud/core/issues/17800 :rage:

**Comment by PVince81** [comment]
This huge task is out of scope now as we're past feature freeze, moving to 9.0

**Comment by PVince81** [comment]
We've made progress, there is now a table "oc_mounts" containing the mount points of every user:
https://github.com/owncloud/core/pull/20768
