### ISSUE TITLE
Add OCS/http APIs to manage external storages

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#11886]
Make it possible to add, edit, remove external storage entries from the command line.

**Comment by SergioBertolinSG** [comment]
This would be very interesting to have for us. @jnfrmarks @jvillafanez @jmaciasportela

**Comment by jvillafanez** [comment]
I would go for a http service similar to what OCS provides (currently in use for the sharing and provisioning API mainly).

Ideally, any action should go through API services. This includes all ajax calls that are being made in the settings page (which should be moved to the OCS service).

To provide an example, if we have an API for external storage (and in fact, any app), all actions performed in the settings page should go through that API. In addition, it's easier to add an occ command that uses that API, and also it's easier that any client (thinking about pyocclient) can use it too. We can guarantee through automated tests that the API performs as it should.

I think this is a wider approach than the original one

**Comment by PVince81** [comment]
CC @jnfrmarks this could be needed for testing.

**Comment by PVince81** [comment]
Let's rename this ticket to propose OCS endpoints for managing external storages.

The OCC ticket is actually here https://github.com/owncloud/core/issues/20368

**Comment by Xenopathic** [comment]
The REST API provided by files_external should satisfy the usecase? It uses JSON, so it's easily scriptable as required

**Comment by LukasReschke** [comment]
`occ`can do such stuff now…
