### ISSUE TITLE
Separate log file

### ISSUE THREAD

**Issue by billybons2006** [owncloud/core#11890]
As I can see, there is one common log file, which can be used for security, trouble search etc in Owncloud 7.0.2.

Is it possible to separate auth.log (generally for fail2ban) from all other logs with standart config settings (without patches which can lead unstable while update etc.)?

Something like this:

'logtimezone' => '<TIMEZONE>',
'logfile' => '/var/log/owncloud.log',
'loglevel' => '2',
'logfile_auth' => '/var/log/owncloud_auth.log',
'log_authfailip' => true

First reason is performance (yes, potentional).
Second one is - security (in common) - one log - one task.
Third one is - stability - imagine, that if there is some error while fail2ban read auth log and this log will be corrupted or..

**Comment by thedd** [comment]
I just noticed:
'log_authfailip' => true
Why does this no longer work?

**Comment by PVince81** [comment]
It would be possible to do so probably by implementing a new logger class.

**Comment by PVince81** [comment]
I think it's already possible now in OC 10.0, isn't it @sharidas ?

**Comment by sharidas** [comment]
Separate log files is possible: for reference we have https://github.com/owncloud/core/blob/master/config/config.sample.php#L634
