### ISSUE TITLE
Do not show "Download" link is folder is empty 

### ISSUE THREAD

**Issue by bnvk** [owncloud/core#11893]
As seen in this screen shot, there is a "download" link in the top right corner. Upon clicking it, a user is able to download an empty directory. This is confusing and unhelpful. You should probably consider hiding it if the directory is empty

![screen shot 2014-10-31 at 5 58 39 pm](https://cloud.githubusercontent.com/assets/48677/4864817/6643f5c2-611f-11e4-82a3-a4d962ed8f21.png)

**Comment by anjanasasindran123** [comment]
@jancborchardt I was just going through the comments, So what could be the actual solution here? Is that enough to deactivate/ hide the button when the folder is empty?

**Comment by jancborchardt** [comment]
@anjanasasindran123 yes, deactivating the button when the folder is empty is the correct solution.

**Comment by jancborchardt** [comment]
Does anyone from our @owncloud/designers want to take care of this? :) Or any new design contributor?

**Comment by jancborchardt** [comment]
Yo @nickvergessen, you’ve been awesome at fixing small stuff like this recently, care to take a stab at this? :)

**Comment by nickvergessen** [comment]
I think this is too risky and too much effort for such a nit pick. Because when you hide the button and the share has upload permissions you need to enable it when a file got uploaded and redisable it when it gets deleted etc...

**Comment by jancborchardt** [comment]
Yeah, that would have to be done of course. But that's just doing it correctly. We do the same thing with the »Nothing in here« message. Essentially the same logic applies to the download button.

**Comment by MorrisJobke** [comment]
Fix ist in #24641

**Comment by noveens** [comment]
@PVince81 ,
In 10.0.0.1, the download button appearing at the drop-down at "all files" page should be removed right?

**Comment by PVince81** [comment]
@noveens no, this is only about the public link page which currently has a permanent "Download" button on the top-right.

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/issues/27259
