### ISSUE TITLE
Firefox OS Sync/Backup App Request

### ISSUE THREAD

**Issue by stephenjudge** [owncloud/core#11897]
This is an enhancement request for some dev out there to please look into creating an app for Firefox OS that can sync or backup files to an ownCloud repo. Initially photos and videos, or even just photos but hopefully later other files. For photos and videos it would be great if the backup happened automatically just after the photo or video was created.

The need for this? Well there is currently only one app in the Firefox Marketplace to perform any kind of backup of photos. It is from Bitcasa but they have now discontinued support for it. So Firefox OS now has no apps for backup. It would really fit in great with the ethos of owning and managing your own data that both the Mozilla Foundation and ownCloud Foundation supports. You may even get some financial and/or coding support from the Mozilla Foundation for this.

I realise Firefox OS may not be very popular in the US or Europe but sales of Firefox OS phones are doing very well in Asia thanks to their $33 phone. It would be great to give them a backup app. Just think how import a backup app is to your own device.

One of the dev's has already mentioned an existing app in development https://github.com/Apophenia/owncloud-photo-upload so maybe this could be built on. You don't need a Firefox OS phone to develop for it, Mozilla has an excellent SDK and Emulator. I am not a developer myself. I just bought a FxOS phone for my mom and I want her photos on it to be safe. I was using Bitcasa until today.

I'm going to look into bountysource and see about starting a bounty there for this and find a way to encourage other FxOS owners to chip in.

**Comment by strugee** [comment]
> Uhm is required a webdav library in js that not exist.

No, this shouldn't be necessary. Since we'd probably just publish a manifest with the existing web app, we have the freedom to use internal APIs for any additional features we'd want to add for Firefox OS.

Unless people were planning to write an entirely separate web app? If so, I don't really see the point of duplicating all the effort that's gone into the existing mobile interface.

**Comment by MorrisJobke** [comment]
As this is an app request I would like to ask you to reopen this in the apps issue tracker: https://github.com/owncloud/apps/issues

Thanks :)

**Comment by stephenjudge** [comment]
@MorrisJobke Can you please mark this issue as "won't fix" so the backers of this issue on Bountysource can get a refund of their bounties as per this FAQ https://github.com/bountysource/core/wiki/Frequently-Asked-Questions#what-happens-if-an-issue-ive-backed-is-closed-without-resolution

The Bountysource issue is here https://www.bountysource.com/issues/5690917-firefox-os-sync-backup-app-request

**Comment by MorrisJobke** [comment]
> @MorrisJobke Can you please mark this issue as "won't fix" so the backers of this issue on

Done
