### ISSUE TITLE
Support separate domains for untrusted user-content

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#11912]
Serving untrusted user-content from the same domain has severe security implications and should be avoided if possible.

An better approach is to serve the user files from another domain, that's the same as Dropbox and Google do with domains such as dropboxusercontent.com.

The goal of this ticket is to evaluate:
1. How we can support separate domains as additional feature
2. What positive implications this has
3. What restrictions this has

**Comment by MorrisJobke** [comment]
Not started yet -> move to 8.1

**Comment by DeepDiver1975** [comment]
@LukasReschke backlog? 9.0?

**Comment by LukasReschke** [comment]
9.0

**Comment by PVince81** [comment]
Backlog for now, would require too many changes. Need to investigate what to change where (tech design).

CC @Peter-Prochaska @pmaier1
