### ISSUE TITLE
Research whether storing directory structure on DB instead FS makes sense

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#11911]
At the moment on a default ownCloud installation the data directory structure is stored in the filesystem and then cached within the DB.

While the current implementation is a straight-forward approach we had a lot of problems with it in the past which even lead to dataloss in some cases. Also we're limited by the filesystem itself which is a huge problem when using ownCloud server on Windows or OS X.
The current code-base contains quite some hacks to properly handle all cases of ugly file-names.

It may be useful to research whether storing the directory structure only within the database would make sense from a performance PoV. The data would then be referenced only with an unique file identifier. (for example 292 would reference to /data/user/files/292)

The goal of this research issue is:

1. Determine what the impact on the performance would be
2. Determine what are the possible gains by this change
3. Determine what are the possible losses by this change
4. Determine how we handle legacy-cases and how migrations are possible

Stable file IDs are also a pre-requisite for other features such as https://github.com/owncloud/core/issues/11732

\cc @PVince81

**Comment by MorrisJobke** [comment]
Isn't this what an object store is good for? I guess we should rather close this here and move the efforts of this in the objectstore implementation. We will always need the FS based layer to access files on an existing filesystem.

cc @karlitschek @DeepDiver1975 for this architectural question

**Comment by karlitschek** [comment]
I think this could be done by a custome filesystem plugin if _really_ needed. But should be a cornercase.
