### ISSUE TITLE
PR #11383 breaks Tags API for Contacts

### ISSUE THREAD

**Issue by jbtbnl** [owncloud/core#11913]
As reported at https://github.com/owncloud/contacts/issues/691 and https://github.com/owncloud/core/commit/7e9baafc5341bda5b8b86700f90d896b43b85185#commitcomment-8400763, the Tags API was recently slightly changed by pull request #11383.

The change makes the Contacts app unable to remove numeric string group names.

cc @ockham

**Comment by PVince81** [comment]
So I guess there is no other alternative than "bloat" the interface with an extra method ?

Side note: I also noticed that many useful methods aren't even exposed on the interface.

**Comment by jbtbnl** [comment]
Yes, an extra method is the most clean solution.

Changing method behaviour based on a variables type is a bad idea in a loosely typed language.

**Comment by DeepDiver1975** [comment]
In case no tag by id is found you can fallback to getTagByName in https://github.com/owncloud/core/pull/11383/files#diff-c01ca4d4cd57b78a07391e67796f145aR659

Not a 100% solution - but an acceptable workaround without breaking apis

**Comment by LukasReschke** [comment]
Given that the old contacts app is dead and this is 1 year old: Close.
