### ISSUE TITLE
Disallow eval in CSP policy

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#11925]
Currently `eval` is allowed with our CSP policy. We should evaluate whether disabling it causes any problems.

**Comment by LukasReschke** [comment]
Would love to get rid of that. – We really need this considering some recent hiccups in some JS code components.

@DeepDiver1975

**Comment by LukasReschke** [comment]
We got bitten by this again: https://github.com/owncloud/gallery/issues/295

We really need this at some point…

**Comment by LukasReschke** [comment]
=> Breaking change that affects third-party apps => Let's move to 9.0

**Comment by PVince81** [comment]
@LukasReschke also the handlebars situation was not solved.

Move to 9.1 ?

**Comment by LukasReschke** [comment]
Yes.

**Comment by PVince81** [comment]
Still can't get rid of eval due to client-side compiling of handlebars templates: https://github.com/owncloud/core/issues/12848

**Comment by PVince81** [comment]
Not possible until we have handlebars templates everywhere -> backlog
