### ISSUE TITLE
Encryption: Adjust UX to default to recovery key

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#11948]
We need an adjustment to the default for encryption such that the recovery key is the default, and the admin has to explicitly disable the recovery key. Otherwise, we get into lost data scenarios - which might be ok, but the default should not be to set that.

Ideally, a UX something like this:
- Admin enables app - but app doesn't encrypt anything yet
- Admin goes to admin panel server side encryption settings
- Admin sees recovery key default enabled
- Admin enters recovery passphrase
- Admin then "turns on" encryption

@jancborchardt what do you think for UX?

**Comment by MTRichards** [comment]
Can we default to this workflow in Encryption 2.0?

Essentially distinguishing between the app being enabled, and being actively encrypting things? 
this is a significant issue in the UX of encryption, and we would like 2 things here:

1) Be able to enable the app and set things up in the admin panel, without actually activating the app. Then be able to click a button and actually activate the app.
2) Be able to have a confirmation that the app is about to be enabled or disabled. For enabled, let the admin know that files will be encrypted in the background when the user first logs in (or set expectations somehow). For disable, let the admin know that the files will be unencrypted and ask yes/no with a popup (are you sure you want to turn this off?).

**Comment by DeepDiver1975** [comment]
@LukasReschke @jancborchardt can we add this as a hint to the 'tips&tricks' section?

**Comment by jancborchardt** [comment]
What exactly would we put there? Simply a link to the docs for encryption?

**Comment by jeremyclarke** [comment]
Hi everyone, just want to say this is a huge problem as far as we (dev team for our org) are concerned. 

An option to enable the user-level recovery option by default shouldn't have any effect on the also-terrible UX problems with admins enabling encryption and adding a recovery key. 

* If the admin recovery key ISN'T set up for any reason (bad UX or admin choice) then the user-profile recovery option is irrelevant, and shouldn't be shown to users at all. The default value doesn't matter in this case, and their choice should be stored but hidden. 
* If the admin recovery key IS set up then the user-profile option can safely be set to enabled OR disabled by default. 

As far as I can tell, this is how it already works: When there's no key set in the admin encryption settings the user profile page has no reference to encryption keys at all. GREAT!

So now all we need is a setting in the admin UI that controls the default behavior:
* Managed mode: Admins can recover by default. Useful for orgs/enterprises where user privacy is not a priority.
* Privacy mode: Users must explicitly consent to admin recovery. Useful for groups/communities using OC in ways that assume the privacy of files in relation to the admin. 

In addition, there should be a `config.php` option to control this to make it solvable with scripting/automation. If the `config.php` option was the only way to change the default (i.e. no UI in the admin options) we'd be satisfied with that too. 

Overall I'd say the app should enable recovery by default when a key is set. It's the most obvious expectation an admin would have and it's too easy for them to set up a recovery key and not realize that it will have no effect whatsoever unless they convince every user to log into the admin and change their personal setting.

Making an option to change the default user setting is the bare minimum needed, and it should be prominent on the admin settings screen if only to make admins aware of how limited the recovery key is when users have it disabled by default.

**Comment by jeremyclarke** [comment]
@jancborchardt WRT the docs there's a LOT of work that should probably be done to have this make more sense. 

This section is very confusing as an administrator. The screenshot is out of date and confusingly labeled, and there's no links to the equivalent page for admins, which would have helped me at least:

**Comment by hodyroff** [comment]
Closing as this was changed for 10.0.x in a different way.

**Comment by PVince81** [comment]
The "different way" meaning we put "Master key" on top and do not recommend user-key any more.
