### ISSUE TITLE
Emit activity when sending a share email

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#11951]
There is a request to add an activity when you shared a link via email: owncloud/activity#168
In order to implement that, a new hook needs to be emitted when the email is sent:
Either in core/ajax/share.php after the call to `sendLinkShareMail()` or inside named function.

@schiesbn any preference?

**Comment by nickvergessen** [comment]
@schiesbn want to add that like the other activities you added for sharing?
So this is independent from the activity app?

**Comment by PVince81** [comment]
Defer to 8.2 ?

**Comment by nickvergessen** [comment]
Yes, PR was already moved

**Comment by cmonteroluque** [comment]
@nickvergessen update?

**Comment by nickvergessen** [comment]
Would need to test again, on the PR vinc said it should work now.
But I'm currently busy with FF

**Comment by cmonteroluque** [comment]
OK, leaving it on 8.2 until we have test results
