### ISSUE TITLE
Whole folder is visable in public and not just the album

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#11969]
### Steps to reproduce
1. Go to the gallery app
2. Share a gallery with password protection (maybe also without) as a link
3. Email that link to a person, or just share the link
4. Log out from your ownCloud account to see how public users see the shared link
5. Open the link
6. Press on the icon in the right upper-corner
   ![namnlos](https://cloud.githubusercontent.com/assets/4511254/4909465/8751823c-6473-11e4-8ab6-a1f6f5738c18.png)
### Expected behavour

The pictures will appear with small thumbnails and some more detailed information like time and date and size. And ONLY the pictures, nothing else.
### Actual behaviour

The whole folder is visable. Security risk!!
![namnlos2](https://cloud.githubusercontent.com/assets/4511254/4909461/7ebaccb4-6473-11e4-935a-50fd8521538a.png)
### Server

ownCloud 7.0.2

---
### Enhancement

Make a filter to only show the pictures in a folder when you share an album. https://github.com/owncloud/gallery/issues/125#issuecomment-61802814

https://github.com/owncloud/gallery/issues/125

**Comment by oparoz** [comment]
@enoch85 - Not coming in OC8
@LukasReschke - I like the approach where a token is restricted to certain mimetypes. It would be easier for all apps.

**Comment by enoch85** [comment]
@oparoz @LukasReschke Milestone 8.3?

**Comment by libasys** [comment]
What's about adding a new column to table oc_share like "share_filter"! And in the share dialog we add new options for folder sharing like "
Filter:
-> include subfolders (checkbox checked/ not checked) (checked by default)
-> all files (checked by default)
if unchecked "all files" we get additional options to granulate for example:
-> only images (checkbox checked/ not checked)
-> only audios (checkbox checked/ not checked)
-> only videos (checkbox checked/ not checked)
and in the new column "share_filter" in the database we add {'httpd/unix-directory','images'}
so you can granulate your shared folder for example

**Comment by PVince81** [comment]
Is this still an issue in 8.2.2 or 9.0 ?

Also if the problem is in the gallery app you should report the bug there.

**Comment by oparoz** [comment]
It still happening, because nothing has changed in the design of the creation of tokens. A folder token gives access to the whole folder, so until that is changed, the problem will remain.

I do find it useful to be able to only show images in Gallery and additional files, as well as various archives on the Files side, but it does require to organise those folders a certain way.
