### ISSUE TITLE
owncloud Update 6.0.3 to 7.0.2 failed

### ISSUE THREAD

**Issue by droidben** [owncloud/core#11971]
Hello everybody

I'm new here and my english isn't the best, please forgive me.

I have owncloud 6.0.3 running on a Windows Server 2012 R2 / IIS 8.5. I barely got it running.

Everytime i try to update owncloud per update-center, it fails (on previous versions too).

Here are some screenshot i took of the errors appering when trying to update per update-center:

![1](https://cloud.githubusercontent.com/assets/9570377/4918704/9ad43946-64f3-11e4-8378-de845284eb15.PNG)

![2](https://cloud.githubusercontent.com/assets/9570377/4918707/a133e070-64f3-11e4-9bd6-b734ea2aa738.PNG)

Can anybody help me here?

**Comment by MorrisJobke** [comment]
@droidben If there is a 500 response, there is definetely something in the logs. Either in the apache logs or in the owncloud.log in your data folder.

**Comment by droidben** [comment]
I looked in the Windows Server Log (since im on IIS). (I cut out all the sync-requests from my workstation at work. Its also not my IP anymore so no security issues):
http://www.mediafire.com/download/71ve6agcipjfmag/u_ex141106.log
If you want to take a look here you go.

**Comment by MorrisJobke** [comment]
@droidben This just lists the URL and the error code. This looks like the access log of the apache. Isn't there an error log for IIS? That log would be of interest.

**Comment by droidben** [comment]
I have an owncloud-log if thats what you mean..?
http://www.mediafire.com/view/t2ezgc9h95iyudt/owncloud.txt

I'm kinda new to the webserver-scene so you might have to tell me what to do and where to look. I'm sorry for that.

**Comment by MorrisJobke** [comment]
@droidben No problem. The problem here is, that I have no experience with IIS. And it's not officially supported in the community edition. I will have a look at the owncloud.log you supplied.

**Comment by MorrisJobke** [comment]
@droidben THe log files contain a lot of errors, but for the timeframe where the HTTP code 500 errors occur nothing special can be found in the owncloud.log.

Maybe @nickvergessen can have a look and maybe experienced similiar errors while setting up ownCloud on Windows.

**Comment by droidben** [comment]
I just want to say that it could have something to do with file- / folder-permissions, since i set this thing up just after the official instructions and then gave permissions until it worked.
