### ISSUE TITLE
Move 3rdparty to composer

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#11973]
Why? Benefits?

- Maintenance of the git submodule is causing some overhead
- vendor javascripts will all be pulled into core repo into core/vendor using bower
- composer (already used in 3rdparty repo) can do the same for php libs 
- remove 3rdparty folder detection code

objections :question:  @karlitschek @craigpg @PVince81 @icewind1991 @schiesbn @butonic @bantu

**Comment by DeepDiver1975** [comment]
Just a second idea did come to my mind:
what about keeping the 3rdparty repo including the submodule as we have it today but move the composer.json into core. This way we can keep the libs isolated but also benefit from composer in core which we require for the autoloader.

**Comment by markuspfeifenberger** [comment]
yes, please move composer to the core and integrate 3rdparty composer.json  as composer package, not as submodule as it is right now.
I tried to install with via composer.json:
```
{
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "owncloud-core",
                "version": "8.0.0",
                "source": {
                    "url": "https://github.com/owncloud/core.git",
                    "type": "git",
                    "reference": "v8.0.0"
                }
            }
        }
    ],
    "require" : {
      "owncloud-core": "8.0.0"
    }
}
```
But the 3rdparty submodule did not work.

**Comment by LukasReschke** [comment]
Closing in favour of https://github.com/owncloud/core/issues/14454
