### ISSUE TITLE
[6.0.5] Shares dissapear

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#11986]
### Expected behavior
The user shares a directory to many people and the share will rest until he deletes it.

### Actual behavior
The share disappeared and the user had to share it again to everybody (two times already).

### Server configuration
**Operating system**:
Red Hat Enterprise Linux Server release 6.5 (Santiago)

**Web server:**
Apache/2.2.15 (Unix)

**Database:**
5.1.73

**PHP version:**
5.3.3

**ownCloud version:** (see ownCloud admin page)
oC 6.0.5 (stable)

**Updated from an older ownCloud or fresh install:**
Updated

**List of activated apps:**
Deleted files
LDAP user and group backend
Share Files
Text Editor
Versions

**The content of config/config.php:**

```
$CONFIG = array (
  'datadirectory' => '/mnt/xxxxxx_data/data',
  'dbtype' => 'mysql',
  'version' => '6.0.5.1',
  'installedat' => '1336391237.9587',
  'lastupdatedat' => '1337968446.9932',
  'dbname' => 'ownCloudDB1',
  'dbhost' => 'xxxxxxxx',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxxxxxx',
  'dbpassword' => '',
  'installed' => true,
  'loglevel' => '4',
  'ldapIgnoreNamingRules' => false,
  'instanceid' => '508fc14d93fa7',
  'maintenance' => false,
  'maxZipInputSize' => 1073741824,
  'allowZipDownload' => true,
  'updatechecker' => false,
  'theme' => 'xxxxx',
  'enable_avatars' => false,
  'forcessl' => true,
  'trashbin_retention_obligation' => 6,
  'trusted_domains' => 
  array (
    0 => 'xxxxxxxx',
    1 => xxxxxxxx',
  ),
  'license-key' => '',
);

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

### Log

S3-ownCloud\Shared\owncloud\support\github-issues\core\11986

00001775

**Comment by cdamken** [comment]
@PVince81  Here is the information:

S3-ownCloud\Shared\owncloud\support\github-issues\core\11986\oC-PB_shares_without_filecache_entries.txt

**Comment by cdamken** [comment]
@PVince81 Any news?

**Comment by PVince81** [comment]
If the OC version is still on OC6 then it's not the known LDAP issue.

You were saying that sharing took too long, which means that maybe not all share entries got created in the first place.

But also you said the shares were created, then worked for a specific time and then suddenly disappeared, is that correct ?

Something to try: after the share was created and is stable (doesn't disappear), try and find it in the `oc_share` table. `select * from oc_share where "file_target" like '%nameofsharedfolder%'` might help locate it. Write down the share ID.
Once the share disappeares, try `select * from oc_share where id=$shareId` (replace $shareId with the id from before). Here see whether the entry has disappear or whether it still exists but maybe orphaned.

Also it would be good if you could find out the real name of the folder from the broken share so we can search for it in the log or database.

**Comment by craigpg** [comment]
@cdamken, can you track down answers to the questions @PVince81 asked above?

**Comment by MorrisJobke** [comment]
@cdamken Is this still an issue? Is the instance still on OC6? Upgrading to OC7/8 will most propably help here, because many fixes regarding stable file ids have landed in those versions.

**Comment by caratsch** [comment]
@MorrisJobke @cdamken there were no tickets regarding this in the last time. Since oC 7 there where no problems regarding this.

**Comment by MorrisJobke** [comment]
@caratsch Thanks for the feedback. I will close this. :)
