### ISSUE TITLE
New from URL doesn't consider filename (from "Content-Disposition" header)

### ISSUE THREAD

**Issue by RandolfCarter** [owncloud/core#1198]
### Expected behaviour
When using the New->From url feature, ownCloud should consider any Content-Disposition headers it gets when retrieving that URL and use the filename given within that header. Only as a fallback (if no such filename header is given), ownCloud should consider taking part of the URL as name.

### Actual behaviour
ownCloud determines the name of the resulting file by taking the last part of the URL (everything after the last /). 

### Steps to reproduce
1. Create a php file, e.g. "dl.php":
```
<?php
header('Content-Disposition: attachment; filename="test.txt"');
header('Content-Type: text/plain');
echo("This is the test text content\n");
```

2. Put that php on some server
3. in owncloudNew->From url choose the URL for the php created in step 1 (i.e. http://example.com/dl.php)
4. After upload has finished, in the file view, you will see a new file called "dl.php"

### Server configuration
Operating system: Ubuntu Server 12.04 LTS 64 bit
Web server: Apache 2.2.22
Database: MySQL Ver 14.14 Distrib 5.5.28
PHP version: 5.3.10
ownCloud version: 4.5.5

### Client configuration
Browser: Firefox 18.0
Operating system: Windows 7

**Comment by MorrisJobke** [comment]
This feature was dropped with #14652
