### ISSUE TITLE
DAV locking doesn't work.

### ISSUE THREAD

**Issue by feinom** [owncloud/core#1199]
We're having some issues with the WebDAV locking implementation in ownCloud.

At first, we contacted Webdrive (the WebDAV client we're using) to see if it was a client bug. This is the response we received:

"""
Your server is not handling LOCK properly. It returns success and says it locked the file, however when webdrive later issues a PROPFIND request asking for the lockdiscovery propery your server is not returning any lock information for the file. I don't know why that is, but it's required to support LOCK and return lock information in the PROPFIND response if it's going to work with the webdrive auto dav lock feature. You can see this behavior without word. Map a drive, then select a file and right click and select properties, then DAV tab and lock the file, you can see the lock token returned by the server. Now close the dialog, and reopen the DAV tab the lock information is gone because PROPFIND didn't return it, it should.
"""

**Comment by LukasReschke** [comment]
@karlitschek We removed DAV locking in 8.1 as far I understand – so can we close this?

**Comment by karlitschek** [comment]
Yes. From my point of view!
