### ISSUE TITLE
Scanner scan() API must default to NOT reset etags

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#11995]
Currently the `scan()` method will reset etags by default, unless a "REUSE_ETAGS" argument is passed.

This is unintuitive and can be the cause of misunderstandings that lead to developers believing that the behavior is the reverse. This happened here: https://github.com/owncloud/core/issues/11932

@schiesbn suggested to change it to have "REUSE_ETAGS" be the default.
If someone wants to force recreation of etag they should pass an extra flag.

@icewind1991

**Comment by MorrisJobke** [comment]
Fixed in #12011
