### ISSUE TITLE
WebDAV extention MPUT for multiple file upload [WIP]

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#12001]
In order to increase sync performance of multiple files we will introduce a new http verb MPUT.

Requirements:
- target folder has to exist
- upload files are restricted to this folder - no sub folder upload

Request:
```http
MPUT  /test/sub-folder-1/sub-folder-2/ HTTP/1.1
   Host: www.foo.bar
   Content-type: text/xml; charset="utf-8"
   Content-Length: xxxx

   <?xml version="1.0" encoding="utf-8" ?>
   <D:mput xmlns:D="http://www.owncloud.org/">
     <D:file>
          <D:name>test1.txt</D:name>
          <D:ctime>2009-06-30T18:00:00+02:00</D:ctime>
          <D:mtime>2009-06-30T18:30:00+02:00</D:mtime>
          <D:etag>aabbccddeeff</D:etag>
          <D:size>1024</D:size>
          <D:data encoding="base64">ABCDEFGH</D:data>
     </D:file>
     <D:file>
          <D:name>test2.jpeg</D:name>
          <D:ctime>2009-06-30T18:00:00+02:00</D:ctime>
          <D:mtime>2009-06-30T18:30:00+02:00</D:mtime>
          <D:etag>aabbccddeeff</D:etag>
          <D:size>4024000</D:size>
          <D:data encoding="base64">ABCDEFGH</D:data>
     </D:file>
   </D:mput>

**Comment by PVince81** [comment]
Should we continue this discussion for 8.1 ?

**Comment by PVince81** [comment]
(or during 8.1 but implement in a later release)

**Comment by DeepDiver1975** [comment]
Discussion during 8.1 for sure

**Comment by jturcotte** [comment]
[Moved from #15264]
Here is a patch for the performance-tests-c++ that uses HTTP multipart to send multiple PUTs in a single HTTP request:
https://gist.github.com/jturcotte/d787bf8c0c6f3f92405d

You can apply it on top of https://github.com/owncloud/administration

If you notice performance improvements worth the extra code complexity, we can then make sure that the client takes advantage of it.

**Comment by jturcotte** [comment]
Unfortunately the Qt network stack currently doesn't support sending multipart requests except when using PUT and POST, so it would be easier client side to go that way instead of MPUT.

Could you guys detect this from a different URI or from the multipart/mixed Content-Type?

**Comment by guruz** [comment]
@jturcotte Let's not go crazy here, POST/PUT is just fine. Everything else brings other issues with load balancers or proxies :-)

**Comment by evert** [comment]
I agree that it will be more robust to define a new contenttype for a POST request, than to introduce a new HTTP method.

**Comment by PVince81** [comment]
@DeepDiver1975 defer to 8.2 ?

**Comment by DeepDiver1975** [comment]
We think we don't need bulk operations - closing this for now.
