### ISSUE TITLE
Thumbnail API should keep file type

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/core#12008]
The Thumbnail API, e.g. /index.php/apps/files/api/v1/thumbnail/253/253/Shared/temp.jpg should obey the file type and return the same filetype as thumbnail:
jpg -> jpg
png -> png
## old version:

Hello,

I have developed the thumbnail generation on android app and we use the new route
/index.php/apps/files/api/v1/thumbnail/253/253/Shared/temp.jpg

Opening this url in the browser lets me download a png file.

If you have a small jpg file: 587x720 with 77,2 kb and get a thumbnail of it I get a png file with:
253x253 with 113,7kB.
So it is bigger than the original file. 
I suggest to use jpg with compression to get a smaller file size:
Originial: 77,2kb
PNG: 113,7kb
jpg of png: 19,5kb
compressed at 80% jpg of png: 16,1kb.

For me there is no visible difference between them, but we would save a lot of traffic.

**Comment by tobiasKaminsky** [comment]
Is there an update? 
As we are getting closer to OC8, and this is the first version that supports thumbnail download for android app, it would be great to have this included, as otherwise we are wasting a lot of bandwidth.
Unfortunately I cannot do this by myself :/

**Comment by tobiasKaminsky** [comment]
*bump*
I am currently developing a feature that loads reduced versions of images to a cache.
With this the bandwith is reduced dramatically on the android app. 
But for this it is necessary to have a jpg reduced version of an original jpg file as otherwise the file size is too high and the benefit is far less or even not existent.

**Comment by oparoz** [comment]
I propose to do this:
* jpg, raw, tiff -> jpg
* everything else -> png

It's not perfect, but would be an acceptable solution.

**Comment by tobiasKaminsky** [comment]
I am fine with this. As long as the preview size is not bigger than the original file :)

**Comment by tobiasKaminsky** [comment]
Any update on this?
It is not good to have the previews on our owncloud app with these large PNGs...

**Comment by tobiasKaminsky** [comment]
@oparoz Can you help me with this? Or can you give me a hint, where to adjust this myself?
As the related PR will be merged in nearer future we need this.

Thank you!

**Comment by oparoz** [comment]
Fun fact, on 8.1+, you're already getting a JPG :D, it just has the wrong extension.
I don't think lowering the quality is a good idea.
4156x3118 JPG | 5.05MB
2048x1536 max preview | 753KB

**Comment by oparoz** [comment]
Since the file is of the correct type, should we close this or is the extension important?

**Comment by tobiasKaminsky** [comment]
There are a few operation systems that rely on the correct extensions, so there should e the correct extension I guess.
