### ISSUE TITLE
Use handlebars templates to render the file list

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#12010]
1) Move from "templates/list.php" to a JS side template for the file list table
2) Inside `filelist.js` in the function `createRow`, use a handlebars template instead of the JS logic to render a row

**Comment by MorrisJobke** [comment]
@PVince81 Afaik this is implemented now, correct?

**Comment by PVince81** [comment]
No, it's not. Still a TODO.

Look at this ugliness: https://github.com/owncloud/core/blob/v8.2.2/apps/files/js/filelist.js#L925 and https://github.com/owncloud/core/blob/v8.2.2/apps/files/js/filelist.js#L972 and https://github.com/owncloud/core/blob/v8.2.2/apps/files/js/filelist.js#L1003

**Comment by MorrisJobke** [comment]
I also just noticed it :(
