### ISSUE TITLE
Create a grammar to define legal file types/names for a given storage type

### ISSUE THREAD

**Issue by danimo** [owncloud/core#12015]
Right now, the client can run into situations where a certain file cannot be uploaded to the server because the backend storage does not support it. Right now this limits the overall usability of the client (e.g. we need to exclude characters illegal on Windows even though it would be legal on Mac OS X and Linux clients). Brainstorming with Frank brought up the idea of a small language that describes what is file name syntax / file content is legal for files and folders in a particular folder (from a users perspective, all backends start with a folder). I agreed to sketch something up, so here it is.

The reason I am bringing this up is that I do not feel confident to merge https://github.com/owncloud/mirall/pull/2288 before we have such a mechanism in place. It would also enable us the get rid of the dreaded black listing that we implemented to overcome such issues.

Here is a (non-exhaustive) list of criterias in which the backend may be limited:

* Might treat certain characters as reserved.
* Might not support the full Unicode range
* Might not allow the creation of subfolders
* Might not allow the upload of files greater than a certain size
* Might not be fully POSIX-compatible (e.g. moves may actually be delete & reupload)
* Might not support certain file types (if only for security reasons)

The idea is to come up with a grammar that the server exposes for all folders as custom WebDAV attributes. It would describe all limitations, so the client can react before it even attempts an upload. Some examples:

```
<oc:filefilter key="reservedChars" value="\|?*<>:"/>
<oc:filefilter key="subDirectories" value="false"/>
<oc:filefilter key="sizeLimit" value="2097152"/> <!-- Files only allowed up to 2 MB in size -->
<oc:filefilter key="disallowedFilePatterns" value="*.exe; *.com;*.scr;*.cpl;*.lnk"/> <!-- Disallow files that would execute on click on Windows -->
```

(This XML syntax is only an example, I'm happy to have `value` as `CDATA` rather than as a property.).

Does that make sense? Is there something I am missing?

/cc @karlitschek @craigpg  @PVince81 

also /cc @DeepDiver1975 and @dragotin because they discussed this matter before.

**Comment by DeepDiver1975** [comment]
follow up is here https://github.com/owncloud/core/issues/13640
