### ISSUE TITLE
Quota Field changes after choosing "Custom"

### ISSUE THREAD

**Issue by kelleybrooks** [owncloud/core#12042]
In creating users on 7.0.3, the quota field turns white if I choose a custom quota.  However, if I change it to an existing dropdown value, the field remains white rather than grey like the other quotas which are using default values.  I also lose the choice of "custom" in the dropdown and instead see the value I entered previously and 0 B.  If I choose 0 B, I'm again able to enter a custom value but would prefer to see "custom".

**Comment by Xenopathic** [comment]
Still an issue, tested on master

**Comment by PVince81** [comment]
Fixed in 9.2 https://github.com/owncloud/core/pull/25253
