### ISSUE TITLE
[External Storage] Typo in error message

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#12040]
In oC 7, when External Storage is enabled but not configured for an account, log in as user.
Click on the file filter "external storage"
You will see The following message:
"You don't have any external storages"

This should read:
"You don't have any external storage configured"

![untitled](https://cloud.githubusercontent.com/assets/1818977/4960986/86ade250-66c9-11e4-87de-67b07ff33221.png)

**Comment by wakeup** [comment]
The text is already changed, closing.
