### ISSUE TITLE
[stable5] OCS Share API returns 500

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#12055]
### Steps
1. Setup stable5 (50e025b148223d4c47837b6e49aea332a6f7d2bf)
2. Create a file "test.txt"
3. Share it with link
4. Run `curl -D - http://root:admin@localhost/owncloud/ocs/v1.php/apps/files_sharing/api/v1/shares`

### Expected result
XML response with the share inside

### Actual result
500 error:
```
HTTP/1.0 500 Internal Server Error
Date: Sat, 08 Nov 2014 18:40:23 GMT
Server: Apache/2.4.10 (Linux/SUSE)
X-Powered-By: PHP/5.6.2
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: Sameorigin
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *
Set-Cookie: oc11qbmm0afb=rhu3501prndo2pjm7kg8mha9hab5dns2on01bo1k12skt5r8bss0; path=/; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Set-Cookie: oc11qbmm0afb=a9cns5ojtth8akibvcb0g8fdhu460q0hig78j1ld2em8dr6fmht0; path=/; HttpOnly
Content-Length: 0
Connection: close
Content-Type: text/html; charset=UTF-8
```

### owncloud.log
```
{"app":"PHP","message":"Call to a member function getRoot() on null at \/srv\/www\/htdocs\/owncloud\/lib\/files\/filesystem.php#327","level":4,"time":"2014-11-08T18:40:23+00:00"}
```

### Versions
ownCloud 5.0.18 (from git)
PHP 5.6.2

I haven't tried with the tarball, but it is likely to have the same problems.

I tried with older versions and are also getting this issue up to v5.0.13, but v5.0.12 returns 401.

Not sure if regression or env issue.
Please note that the same call works fine on stable6 and stable7.

**Comment by LukasReschke** [comment]
Stable5 is EoL after next release => Close from my PoV.
