### ISSUE TITLE
WebDAV (davfs2) doesn't create files

### ISSUE THREAD

**Issue by RobinJ1995** [owncloud/core#12056]
1. Set up _davfs2_ like is described in [this guide](http://doc.owncloud.org/server/6.0/user_manual/files/files.html#mounting-from-command-line)
2. Mount
3. `cd` into folder
4. `touch test`

# Result
```
touch: setting times of ‘sinCloud/test’: No such file or directory
```

Creating a directory *does* work. Creating a file in the directory does not.

Of course this might be a bug in something else (_davfs2_ for example). Accessing my ownCloud files via WebDAV in Dolphin (KDE's file manager) seems to work fine.

# System information
```
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:        14.04
Codename:       trusty
Linux robinj.be 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
KVM hypervisor with VirtIO networking and storage, if that makes any difference.

**Comment by DeepDiver1975** [comment]
closed due to inactivity
