### ISSUE TITLE
Files workflow

### ISSUE THREAD

**Issue by karlitschek** [owncloud/core#12052]
There are usecases where someone want´s to plug a 3rd party system or any workflow into the ownCloud upload/download/share actions.

Examples are:
- Everytime someone uploads a file the virusscanner needs to run and than delete or move the file and send a notification. This partly exists in the current virusscanner app already.

- Everytime a file is uploaded or changed a copy of it has to be put into a 3rd party filestorage for archiving because of legal regulations.

- Everytime someone shares a file with someone or this person gownloads the shared file the file has to be automatically encrypted by a 3rd party tool that ownCloud executes. Alternatively the file has to be digitally signed by this 3rd party tool.

- Everytime a file is uploded into a specific folder a copy is put into a second folder and the files is automatically converted to pdf and password protected by an external cli tool.

- Everytime someone uploads a csv file into a specific folder an external python script is called to do scientific  analysis of the data and puts a report into the same folder later.

The ownCloud core should make it happen that all this actions can be added to ownCloud as apps to plug into the ownCloud file workflow. Some of this external scripts or applications are long running so we can´t do everything synchronously. 
What we need is an extension to the current API/hooks that make it possible to implement this external file workflows.

**Comment by DeepDiver1975** [comment]
@karlitschek if this feature is still on our roadmap - I'd like to push this to OC8.1

**Comment by karlitschek** [comment]
definitely 8.1

**Comment by DeepDiver1975** [comment]
Pushing to 8.2 - still needs discussion ...

**Comment by MorrisJobke** [comment]
@janklostermann this is what we talked about ;)
