### ISSUE TITLE
Cyrillic folder

### ISSUE THREAD

**Issue by dintra7** [owncloud/core#12051]
Hello frend, i'm install owncloud in windows 2008 under apache, and all be fine but have some truble with cyrillic folder no one files copy in this folder or anything else, in administrator panel this error:

Error PHP rename(E:\OwnCloud\data/root/files/---2-.rar,E:\OwnCloud\data/root/files/545e01e447b51/---2-.rar): at C:\web\wampstack-5.4.34-0\apps\owncloud\htdocs\lib\private\files\storage\mappedlocal.php#204 2014-11-08T11:50:25+00:00

Error PHP rename(E:\OwnCloud\data/root/files/---2-.txt,E:\OwnCloud\data/root/files/545dfffe1566b/---2-.txt): at C:\web\wampstack-5.4.34-0\apps\owncloud\htdocs\lib\private\files\storage\mappedlocal.php#204 2014-11-08T11:50:22+00:00

If i try download in cyrillic folder and i have in administrator panel this error:

Error PHP unlink(C:\web\wampstack-5.4.34-0\php\tmp\phpB1FE.tmp): Permission denied at C:\web\wampstack-5.4.34-0\apps\owncloud\htdocs\lib\private\files\view.php#673 2014-11-08T12:10:43+00:00

Error PHP fopen(E:\OwnCloud\data/root/files/545e0843c14e3/---2-.txt): failed to open stream: No such file or directory at C:\web\wampstack-5.4.34-0\apps\owncloud\htdocs\lib\private\files\storage\mappedlocal.php#239 2014-11-08T12:10:43+00:00

plz help
OS Windows 2008 r2
Apache
PHP 5.4.34
MySQL 5.5.40

P.S1 with cyrillic file all alright, they copy and move correctly, this problem just with folder.
P.S2 sorry for my english.

**Comment by XStanleyX** [comment]
Confirm the troubles with Cyrillic on Windows Server installation. (As I can googling with other specify encoding the same problem persist)

If I try to create Cyrillic folder in OwnCloud it's work, but if I create the folder in Windows OwnCloud drop me to previous level. When I leave English symbols only folders works fine. Same problem with filenames too. But when I create txt file in OwnCloud with name like йцукенгшщзхъфывапролджэячс.txt its automatically renamed in -----.txt and I can't to do something with it (remove for example). But if I try to rename it to 1.txt or 123.txt process is hunged before I refresh the page. After that nothing but in Windows was created 2 files 1.txt and 123.txt.

I was trying change encoding in SQL tables, on Server, in php.ini, locale in base.php but unsuccessfully.

Windows Server 2012 R2
PHP 5.6
MySQL 5.6.21
IIS 8.5

PS: Other services on this server like WordPress works with Cyrillic filenames correctly.

Part of log after I try to open Cyrillic folders:

Fatal  files

Exception: {"Message":"An exception occurred while executing 'INSERT INTO `oc_file_map` (`logic_path`, `physic_path`, `logic_path_hash`, `physic_path_hash`)\n\t\t\t\tVALUES (?, ?, ?, ?)' with params [\"\\x44\\x3a\\x5c\\x55\\x73\\x65\\x72\\x66\\x6f\\x6c\\x64\\x65\\x72\\x73\\x5c\\x53\\x74\\x61\\x6e\\x69\\x73\\x6c\\x61\\x76\\x2f\\x44\\x6f\\x63\\x75\\x6d\\x65\\x6e\\x74\\x73\\x2f\\xc0\\xea\\xf2\\x5f\\xc2\\xe0\\xeb\\xe8\\xe3\\xf3\\xf0\\xe0\\x5f\\x38\\x5f\\x31\\x35\\x31\\x32\\x31\\x34\\x2e\\x70\\x64\\x66\", \"\\x44\\x3a\\x5c\\x55\\x73\\x65\\x72\\x66\\x6f\\x6c\\x64\\x65\\x72\\x73\\x5c\\x53\\x74\\x61\\x6e\\x69\\x73\\x6c\\x61\\x76\\x2f\\x44\\x6f\\x63\\x75\\x6d\\x65\\x6e\\x74\\x73\\x2f\\xc0\\xea\\xf2\\x5f\\xc2\\xe0\\xeb\\xe8\\xe3\\xf3\\xf0\\xe0\\x5f\\x38\\x5f\\x31\\x35\\x31\\x32\\x31\\x34\\x2e\\x70\\x64\\x66\", \"fca54d07e0d98409f4f573bfe2d466d2\", \"fca54d07e0d98409f4f573bfe2d466d2\"]:\n\nSQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\xC0\\xEA\\xF2_\\xC2\\xE0...' for column 'logic_path' at row 1","Code":0,"Trace":"#0 D:\\WebSites\\owncloud\\3rdparty\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 D:\\WebSites\\owncloud\\3rdparty\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Statement.php(172): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'INSERT INTO `oc...', Array)\n#2 D:\\WebSites\\owncloud\\lib\\private\\db\\statementwrapper.php(63): Doctrine\\DBAL\\Statement->execute(Array)\n#3 D:\\WebSites\\owncloud\\lib\\private\\db.php(141): OC_DB_StatementWrapper->execute(Array)\n#4 D:\\WebSites\\owncloud\\lib\\private\\files\\mapper.php(193): OC_DB::executeAudited('INSERT INTO `*P...', Array)\n#5 D:\\WebSites\\owncloud\\lib\\private\\files\\mapper.php(40): OC\\Files\\Mapper->insert('D:\\\\Userfolders\\\\...', 'D:\\\\Userfolders\\\\...')\n#6 D:\\WebSites\\owncloud\\lib\\private\\files\\storage\\mappedlocal.php(88): OC\\Files\\Mapper->physicalToLogic('D:\\\\Userfolders\\\\...')\n#7 D:\\WebSites\\owncloud\\lib\\private\\files\\storage\\wrapper\\wrapper.php(69): OC\\Files\\Storage\\MappedLocal->opendir('Documents')\n#8 D:\\WebSites\\owncloud\\lib\\private\\files\\storage\\wrapper\\wrapper.php(69): OC\\Files\\Storage\\Wrapper\\Wrapper->opendir('Documents')\n#9 D:\\WebSites\\owncloud\\lib\\private\\files\\cache\\scanner.php(250): OC\\Files\\Storage\\Wrapper\\Wrapper->opendir('Documents')\n#10 D:\\WebSites\\owncloud\\lib\\private\\files\\cache\\scanner.php(216): OC\\Files\\Cache\\Scanner->scanChildren('Documents', false, 3)\n#11 D:\\WebSites\\owncloud\\lib\\private\\files\\view.php(1018): OC\\Files\\Cache\\Scanner->scan('Documents', false)\n#12 D:\\WebSites\\owncloud\\lib\\private\\files\\filesystem.php(817): OC\\Files\\View->getDirectoryContent('\/\\xD0\\x9B\\xD0\\xBE\\xD0\\xBA\\xD0\\xB0\\xD0\\xBB\\xD1\\x8C\\xD0\\xBD...', '')\n#13 D:\\WebSites\\owncloud\\apps\\files\\lib\\helper.php(176): OC\\Files\\Filesystem::getDirectoryContent('\/\\xD0\\x9B\\xD0\\xBE\\xD0\\xBA\\xD0\\xB0\\xD0\\xBB\\xD1\\x8C\\xD0\\xBD...')\n#14 D:\\WebSites\\owncloud\\apps\\files\\ajax\\list.php(28): OCA\\Files\\Helper::getFiles('\/\\xD0\\x9B\\xD0\\xBE\\xD0\\xBA\\xD0\\xB0\\xD0\\xBB\\xD1\\x8C\\xD0\\xBD...', 'name', false)\n#15 D:\\WebSites\\owncloud\\lib\\private\\route\\route.php(135) : runtime-created function(1): require_once('D:\\\\WebSites\\\\own...')\n#16 [internal function]: __lambda_func(Array)\n#17 D:\\WebSites\\owncloud\\lib\\private\\route\\router.php(250): call_user_func('\\x00lambda_1125', Array)\n#18 D:\\WebSites\\owncloud\\lib\\base.php(763): OC\\Route\\Router->match('\/apps\/files\/aja...')\n#19 D:\\WebSites\\owncloud\\index.php(36): OC::handleRequest()\n#20 {main}","File":"D:\\WebSites\\owncloud\\3rdparty\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php","Line":115}  2015 

Error  PHP 

Cannot modify header information - headers already sent by (output started at D:\WebSites\owncloud\lib\private\eventsource.php:45) at D:\WebSites\owncloud\lib\private\response.php#83

Fatal  index

Exception: {"Message":"An exception occurred while executing 'INSERT INTO `oc_file_map` (`logic_path`, `physic_path`, `logic_path_hash`, `physic_path_hash`)\n\t\t\t\tVALUES (?, ?, ?, ?)' with params [\"\\x44\\x3a\\x5c\\x55\\x73\\x65\\x72\\x66\\x6f\\x6c\\x64\\x65\\x72\\x73\\x5c\\x53\\x74\\x61\\x6e\\x69\\x73\\x6c\\x61\\x76\\x2f\\x44\\x6f\\x77\\x6e\\x6c\\x6f\\x61\\x64\\x2f\\x56\\x69\\x72\\x74\\x75\\x61\\x6c\\x20\\x4d\\x61\\x63\\x68\\x69\\x6e\\x65\\x73\\x2f\\x57\\x69\\x6e\\x64\\x6f\\x77\\x73\\x20\\x56\\x69\\x72\\x74\\x75\\x61\\x6c\\x20\\x50\\x43\\x2f\\xc2\\xe8\\xf0\\xf2\\xf3\\xe0\\xeb\\xfc\\xed\\xfb\\xe5\\x5f\\xec\\xe0\\xf8\\xe8\\xed\\xfb\", \"\\x44\\x3a\\x5c\\x55\\x73\\x65\\x72\\x66\\x6f\\x6c\\x64\\x65\\x72\\x73\\x5c\\x53\\x74\\x61\\x6e\\x69\\x73\\x6c\\x61\\x76\\x2f\\x44\\x6f\\x77\\x6e\\x6c\\x6f\\x61\\x64\\x2f\\x56\\x69\\x72\\x74\\x75\\x61\\x6c\\x20\\x4d\\x61\\x63\\x68\\x69\\x6e\\x65\\x73\\x2f\\x57\\x69\\x6e\\x64\\x6f\\x77\\x73\\x20\\x56\\x69\\x72\\x74\\x75\\x61\\x6c\\x20\\x50\\x43\\x2f\\xc2\\xe8\\xf0\\xf2\\xf3\\xe0\\xeb\\xfc\\xed\\xfb\\xe5\\x5f\\xec\\xe0\\xf8\\xe8\\xed\\xfb\", \"e4fea7306205d3f8dd56024a29481dcb\", \"e4fea7306205d3f8dd56024a29481dcb\"]:\n\nSQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\xC2\\xE8\\xF0\\xF2\\xF3\\xE0...' for column 'logic_path' at row 1","Code":0,"Trace":"#0 D:\\WebSites\\owncloud\\3rdparty\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 D:\\WebSites\\owncloud\\3rdparty\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Statement.php(172): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'INSERT INTO `oc...', Array)\n#2 D:\\WebSites\\owncloud\\lib\\private\\db\\statementwrapper.php(63): Doctrine\\DBAL\\Statement->execute(Array)\n#3 D:\\WebSites\\owncloud\\lib\\private\\db.php(141): OC_DB_StatementWrapper->execute(Array)\n#4 D:\\WebSites\\owncloud\\lib\\private\\files\\mapper.php(193): OC_DB::executeAudited('INSERT INTO `*P...', Array)\n#5 D:\\WebSites\\owncloud\\lib\\private\\files\\mapper.php(40): OC\\Files\\Mapper->insert('D:\\\\Userfolders\\\\...', 'D:\\\\Userfolders\\\\...')\n#6 D:\\WebSites\\owncloud\\lib\\private\\files\\storage\\mappedlocal.php(88): OC\\Files\\Mapper->physicalToLogic('D:\\\\Userfolders\\\\...')\n#7 D:\\WebSites\\owncloud\\lib\\private\\files\\storage\\wrapper\\wrapper.php(69): OC\\Files\\Storage\\MappedLocal->opendir('Download\/Virtua...')\n#8 D:\\WebSites\\owncloud\\lib\\private\\files\\storage\\wrapper\\wrapper.php(69): OC\\Files\\Storage\\Wrapper\\Wrapper->opendir('Download\/Virtua...')\n#9 D:\\WebSites\\owncloud\\lib\\private\\files\\cache\\scanner.php(250): OC\\Files\\Storage\\Wrapper\\Wrapper->opendir('Download\/Virtua...')\n#10 D:\\WebSites\\owncloud\\lib\\private\\files\\cache\\scanner.php(216): OC\\Files\\Cache\\Scanner->scanChildren('Download\/Virtua...', true, 1)\n#11 D:\\WebSites\\owncloud\\lib\\private\\files\\cache\\scanner.php(332): OC\\Files\\Cache\\Scanner->scan('Download\/Virtua...', true, 1)\n#12 D:\\WebSites\\owncloud\\lib\\private\\files\\utils\\scanner.php(108): OC\\Files\\Cache\\Scanner->backgroundScan()\n#13 D:\\WebSites\\owncloud\\apps\\files\\ajax\\scan.php(29): OC\\Files\\Utils\\Scanner->backgroundScan('')\n#14 D:\\WebSites\\owncloud\\lib\\private\\route\\route.php(135) : runtime-created function(1): require_once('D:\\\\WebSites\\\\own...')\n#15 [internal function]: __lambda_func(Array)\n#16 D:\\WebSites\\owncloud\\lib\\private\\route\\router.php(250): call_user_func('\\x00lambda_615', Array)\n#17 D:\\WebSites\\owncloud\\lib\\base.php(763): OC\\Route\\Router->match('\/apps\/files\/aja...')\n#18 D:\\WebSites\\owncloud\\index.php(36): OC::handleRequest()\n#19 {main}","File":"D:\\WebSites\\owncloud\\3rdparty\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php","Line":115}

**Comment by vat78** [comment]
In my case function slugify (in files/mapper.php ) works bad. It converts cyrillic symbols to '-'.
I resolved this by inserting additional function 'translit' and calling it before iconv.

    function translit($st) {
      $lit = array(
          "а" => "a",
          "б" => "b",
          "в" => "v",
          "г" => "g",
          "д" => "d",
          "е" => "e",
          "ё" => "yo",
          "ж" => "g",
          "з" => "z",
          "и" => "i",
          "й" => "y",
          "к" => "k",
          "л" => "l",
          "м" => "m",
          "н" => "n",
          "о" => "o",
          "п" => "p",
          "р" => "r",
          "с" => "s",
          "т" => "t",
          "у" => "u",
          "ф" => "f",
          "х" => "h",
          "ц" => "ts",
          "ч" => "ch",
          "ш" => "sh",
          "щ" => "shch",
          "ъ" => "",
          "ы" => "i",
          "ь" => "",
          "э" => "e",
          "ю" => "yu",
          "я" => "ya",
     
          "А" => "A",
          "Б" => "B",
          "В" => "V",
          "Г" => "G",
          "Д" => "D",
          "Е" => "E",
          "Ё" => "Yo",
          "Ж" => "G",
          "З" => "Z",
          "И" => "I",
          "Й" => "Y",
          "К" => "K",
          "Л" => "L",
          "М" => "M",
          "Н" => "N",
          "О" => "O",
          "П" => "P",
          "Р" => "R",
          "С" => "S",
          "Т" => "T",
          "У" => "U",
          "Ф" => "F",
          "Х" => "H",
          "Ц" => "Ts",
          "Ч" => "Ch",
          "Ш" => "Sh",
          "Щ" => "Shch",
          "Ъ" => "",
          "Ы" => "I",
          "Ь" => "",
          "Э" => "E",
          "Ю" => "Yu",
          "Я" => "Ya",
        );
      return $st = strtr($st, $lit);
    }

**Comment by XStanleyX** [comment]
https://ru.m.wikipedia.org/wiki/Транслит
