### ISSUE TITLE
cron.php: Unexpected error!

### ISSUE THREAD

**Issue by hostingnuggets** [owncloud/core#12066]
I noticed that the cron.php cronjob which I run from the Linux crontab on my ownCloud 7.0.2 installation (PHP 5.4.34, PostgreSQL 9.1.14 and nginx 1.6.2) does not always work correctly. Around 1/3 of the times I get see the following error message in the cron output:

`Unexpected error!`

Here is my crontab entry running under the www-data user:

`*/15  *  *  *  * php -f /var/www/owncloud/cron.php`

Any ideas what could be going wrong here? I don't see anything in the `owncloud.log` file associated to that.

**Comment by DeepDiver1975** [comment]
case closed in 8.1 from my understanding - we changed some cron logic
