### ISSUE TITLE
LDAP wizard user experience

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#12060]
I set up today for the first time ownCloud together with LDAP and I want to share my user experience. 

Note: I don't have set up the LDAP server (I used one already deployed in our environment) and I never have heard/read about how LDAP works.

* propose default ports (prefill 389 and if `ldaps://` is added switch to 636) - switch the port only if it wasn't set by the user to something other than those both
* better error messages: I noticed them in the log, but the wizard often says: "Base-DN couldn't be found" (or something like that) - but it was wrong hostname, port or credentials. That would help a lot - especially newbies to LDAP.
* going back and forth in the tabs doesn't cleans the old state (if you change the base-dn, object-classes weren't reloaded and then result in some confusion on my side, because they were simply not possible for that base-dn ;))
* if the displayname of the user (advanced tab -> directory settings -> first setting) isn't set to a valid attribute a user can't login and isn't shown in the user management - add a warning in the wizard and note this in the "test config step"  - also noted in https://github.com/owncloud/documentation/issues/290

cc @jancborchardt for the UX part

**Comment by Xenopathic** [comment]
Most of this is done, with the exception of error messages being shown in the wizard. cc @blizzz

**Comment by blizzz** [comment]
Should be all fixed in 8.1.
