### ISSUE TITLE
QR-code for client configuration

### ISSUE THREAD

**Issue by tflidd** [owncloud/core#12071]
In Bittorrent-Sync app you can scan a QR-code in order to configure the mobile client. There is no need to type a long address or username on the mobile client. I think it would be a nice feature to create such an QR-Code on the owncloud web-interface that you can scan with your mobile app.

**Comment by Xenopathic** [comment]
This is a great idea for an ownCloud app, @tflidd want to have a go?

**Comment by tflidd** [comment]
I thought it more in a way, that you use the web-interface to make the initial connection to your mobile device. Instead of credentials, the QR code could be used to transmit some server and account information that the client can connect via SSL certificate authentication.

In some interface, you can see the clients connected to your account, and you can of course revoke a certificate in case of loss of a device.

On top of that, it would be nice to configure calendar/contact/backup as well.

**Comment by tflidd** [comment]
A little bit like this: https://www.google.com/patents/US20140108810
(I don't understand why you can patent that)
