### ISSUE TITLE
Check for 3rdparty existance - the proper way

### ISSUE THREAD

**Issue by marcdexet-cnrs** [owncloud/core#12089]
### Steps to reproduce
1. clone core with commit 2023878d537374b47494eb8ce44d3757b3692626
2. install core as usual
3. starts

### Expected behaviour
Screen setup must be displayed

### Actual behaviour
/var/log/error.log says
 ```PHP Fatal error:  Call to a member function getSession() on a non-object in /var/www/html/oc80/lib/private/template.php on line 105```

### Server configuration
**Operating system**:
Ubuntu 14.04
**Web server:**
apache2
**Database:**
mysql
**PHP version:**
5.5.9-1ubuntu4.5
**ownCloud version:** (see ownCloud admin page)
8.0 pre-alpha
**Updated from an older ownCloud or fresh install:**
Fresh
**List of activated apps:**
owncloud setup never starts

**The content of config/config.php:**
empty

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
### Client configuration
**Browser:**
FF
**Operating system:**
ubuntu (the same)
#### Web server error log
```
[Mon Nov 10 22:30:31.694979 2014] [:error] [pid 3050] [client 127.0.0.1:38186] PHP Fatal error:  Call to a member function getSession() on a non-object in /var/www/html/oc80/lib/private/template.php on line 105
```

**Comment by DeepDiver1975** [comment]
fixed with #13809
