### ISSUE TITLE
Improve mobile interface: ability to use all file actions, remove need to hover

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#12081]
Currently there are 2 big problems with the ownCloud interface on mobile / tablet:
* On tablets, you can’t use the file actions at all because they are only shown on hover of the row. iOS catches that intelligently and emulates the hover on first click. Others do not do that.
* On smartphones, you can not use all the file actions since we needed to prioritize what to show because of space constraints. This means you currently can only open, download and share a file but not rename or delete it.

The solution to both of these problems is to put all the actions (except Sharing!) into an extra popover. Sharing needs to stay outside since it’s more important than all the other »management« actions (Rename, Download, Delete, Versions).

For this we should use the popover @Raydiation and I designed with https://github.com/owncloud/core/pull/10644
The three-dots menu should go right to the Share action, on both desktop and mobile sizes. (With the small difference as it is now already that on mobile, share does not have any text.)

@owncloud/designers what do you think? @PVince81 @MorrisJobke what do you think is needed to pull this off?

![](https://raw.githubusercontent.com/owncloud/design/master/Files/Sidebar-mockup-menus.png)

**Comment by jancborchardt** [comment]
Putting the actions in a dropdown would also fix the problem with accidentally clicking the delete icon when trying to use the scrollbar. cc @dragotin

**Comment by stefan-niedermann** [comment]
i agree, this is indeed necessary. but in my personal opinion the rename-action is very important, too. i personally use it much more often than share-action. a download should also be able by touching the filename.

**Comment by jancborchardt** [comment]
Clicking the filename is already bound to open of course – much more common than download. (Download and other actions should of course also be possible in the detail view, but we have https://github.com/owncloud/gallery/issues/18 for that.)

About rename: We have to prioritize somewhat, and as Sharing is the only action which also shows a permanent status (if it’s shared and with whom) that will be the one which is shown outside of the dropdown. Showing more will defeat the purpose of the dropdown and also make everything too crowded as we should not use hover anymore.

**Comment by ShamimIslam** [comment]
Your three dots solution ignores the problem we've had before. These other actions are not lowest class operations. They should not be the last thing on the line. Doing so recreates an existing problem and a new problem:
1. Clicking the three dots instead of the elevator - presumably this solution will be implemented on mobile as well as tablet AND desktop. Please DO NOT PUT ACTIONS other than clicking on the filename at the end of the line. It is the worst possible place and it is becuase we keep forgetting there is an elevator in the desktop view and sometimes even on the mobile view that can be intereacted with. Two interactions that close together are going to be hard to handle as always from a usability/user experience perspective. Let's not recreate teh "accidental delete" problem by creating an "accidental menu" problem.
2. The user will have to move hte mouse pointer or the finger all the way over to the end of the screen for common functions. This should only happen for a state transition such as a download or an open file function - NOT for simply adding operations. 

Therefore, I'm ok with the context menu appraoch but ONLY IF it does not recreate the scenario we have with "Delete".

Thanks.

**Comment by ShamimIslam** [comment]
Last item - personally, if you really want to go the way of the big boys - look at Apple - delete is a modal change of the ENTIRE screen. Why are we not considering this as an option? Yes - they do not have a confirmation (but Android does). But they do recognize how special and dangerous Delete is. How come we do not see it that way? (Yes, Apple has UNDO but they STILL have this modal screen change).

**Comment by jancborchardt** [comment]
@DeepDiver1975 @PVince81 probably no time til 8.1, so I’m putting this in 8.2?

**Comment by jancborchardt** [comment]
To prevent the accidental clicking of the menu when wanting to scroll, we can put it directly next to the "Share" action – right-aligned, but left of the modified date and file size.

**Comment by ShamimIslam** [comment]
Delete is not a primary action.. How long will before menu version of the
secondary actions comes along?

Moving it from the one place will allevaite the scrollbar accidental delete
but then create a new one on clicking too close to the primary action
"share".

I just don't want to go back to where I was fielding all those calls.

**Comment by PVince81** [comment]
@jancborchardt is the mock up still up to date ? Just to confirm.

So three dots for the dropdown menu with all file actions except sharing.
Sharing will later trigger the right sidebar and auto-select the sharing tab.

**Comment by jancborchardt** [comment]
@PVince81 yep, up to date. The change from now is to move the actions Rename, Download, Versions, Delete to the dropdown, right next to the Sharing action. Favoriting and Sharing stays where it is.

**Comment by PVince81** [comment]
@jancborchardt there will likely be a transitional phase for versions. At first we won't have the versions visible in the right sidebar, so should we still move the action to the dropdown or keep it inline ?

**Comment by jancborchardt** [comment]
@PVince81 we should move it to the dropdown already for sure. It might look a bit strange but better than having it still inline, which we definitely want to get rid of.

**Comment by PVince81** [comment]
So the actions dropdown would close after clicking "Versions" and be replaced by the versions dropdown. I'm ok with this.

**Comment by jancborchardt** [comment]
@PVince81 yeah, that’s probably the best interim solution.

**Comment by PVince81** [comment]
@jancborchardt should the default action be visible in the menu too ? And Share ?
For now I'll assume that only the non-inline and non-default actions must appear in the menu.

**Comment by srt10coupe** [comment]
looks very good :)

**Comment by PVince81** [comment]
If you want to really see something, look at the PR: https://github.com/owncloud/core/issues/17709

**Comment by jancborchardt** [comment]
@Pvince81 no, definitely no duplication of actions like open and share. :)

**Comment by jancborchardt** [comment]
Fixed by https://github.com/owncloud/core/pull/17709, thanks @PVince81! :)
