### ISSUE TITLE
Deleted Files: Shows Wrong Time

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#12092]
When I deleted a file, and I look at in the deleted files list, it says it was deleted 5 hours ago. The thing is, I just deleted the file 30 seconds ago.

Reproduction Steps:
Log into ownCloud. Upload a file. Delete it.

Look into the deleted files directory, the time stamp will say "5 hours ago".

Firefox latest on Windows 7
CentOS 6.5 
Apache 
PHP 5.4
ownCloud 7.0.4 (stable)

**Comment by PVince81** [comment]
@MTRichards are you still seeing this ?

**Comment by MTRichards** [comment]
I think it is resolved, it was a time issue on the server.

On March 6, 2015, at 4:59 AM, Vincent Petry <notifications@github.com> wrote:

@MTRichards are you still seeing this ?

**Comment by PVince81** [comment]
Thanks, closing.
