### ISSUE TITLE
Update phpseclib to 0.3.9

### ISSUE THREAD

**Issue by AdamWill** [owncloud/core#12115]
AFAICS OC's only use of phpseclib is for SFTP external storage support. I eyeballed the phpseclib Net_SFTP for changes from 0.3.6 to 0.3.9 and didn't see anything that ought to break it. Upstream recently added a changelog - https://github.com/phpseclib/phpseclib/blob/master/CHANGELOG.md - and nothing leaps out at me there either.

I'm not sure of OC's rules/conventions for submitting PRs that bump 3rdparty deps so I thought I'd just submit an issue instead. Mostly it should just be a case of 'composer update phpseclib/*' in the 3rdparty repo, I guess.

**Comment by th3fallen** [comment]
Other issue with the current version is an incompatibility with users who use phpunit via `composer global require` which is resolved in phpseclib 0.3.9

**Comment by DeepDiver1975** [comment]
master is on 0.3.9 - see [![Dependency Status](https://www.versioneye.com/user/projects/54a548e697427553100000b9/badge.svg?style=flat)](https://www.versioneye.com/user/projects/54a548e697427553100000b9)

**Comment by th3fallen** [comment]
@DeepDiver1975 composer.lock does not show this.... https://github.com/owncloud/3rdparty/blob/master/composer.lock#L1278-L1279

**Comment by bantu** [comment]
@DeepDiver1975 We already established that versioneye lies.

**Comment by bantu** [comment]
@DeepDiver1975 See https://github.com/owncloud/core/issues/9632#issuecomment-72041261

**Comment by th3fallen** [comment]
yeah its definitely at 0.3.6

**Comment by DeepDiver1975** [comment]
oh well - then let's update that on

**Comment by DeepDiver1975** [comment]
I wonder who failed to use composer properly .... most probably myself

**Comment by th3fallen** [comment]
"oh well - then let's update that on"

What are we updating that on....? :smile:

**Comment by bantu** [comment]
@th3fallen I take this.

**Comment by th3fallen** [comment]
Thanks @bantu
