### ISSUE TITLE
ownCloud File Mapper Not Encoding UTF-8 Properly

### ISSUE THREAD

**Issue by LeeThompson** [owncloud/core#12112]
### Preface
I've been wrestling with an issue with ownCloud on a new install, my initial issue and research is also at http://forum.owncloud.org/viewtopic.php?f=29&t=24688

I have been able to isolate exactly what the actual issue and even what ownCloud needs to do to resolve it.    I do plan on working on a fix and submitting it but that may take awhile since I'm new to ownCloud and not familiar with it's codebase.

This may be related to #4513

### Steps to reproduce
* Have owncloud browse to a folder with international characters in a filename via WebUI
* Have owncloud sync with a folder with international characters in a filename

**Sample:**
"é or ç.txt"

### Expected behaviour
It should be able to handle the file or folder.

### Actual behaviour
* WebUI will return an unknown error 
* Insert to file_map will fail with "incorrect string value"
* Sync application will fail.

**Solution?**
Was able to reproduce the issue with a test script/table (mimicking the file_map table)
and was able to fix it by encoding the logic and physic paths with utf8_encode which is
probably not the optimal solution but it did insert the row properly.

**ownCloud's INSERT**
```sql
INSERT INTO `oc_file_map` (`logic_path`, `physic_path`, `logic_path_hash`, `physic_path_hash`) VALUES ('é or ç.txt', 'é or ç.txt', 'TEST', 'TEST');
```

**correct INSERT**
```sql
INSERT INTO `oc_file_map` (`logic_path`, `physic_path`, `logic_path_hash`, `physic_path_hash`) VALUES ('Ã© or Ã§.txt', 'Ã© or Ã§.txt', 'TEST', 'TEST')
```

This can be done with utf8_encode("é or ç.txt") but that's not an optimal solution for many reasons.

### Server configuration
**Operating system**:
Windows Server 2008 R2

**Web server:**
Apache 2.4.10

**Database:**
MariaDB 10.0.14 (MySQL compatible)

**PHP version:**
5.6.2

**ownCloud version:**
7.0.2 (community edition) 

**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
default applications only
deleted files/Versioning are disabled

**config.php**
data/config.php with sensitive information redacted.

```php
$CONFIG = array (
  'instanceid' => 'oc76783e0396',
  'passwordsalt' => REDACTED,
  'datadirectory' => 'E:\\ownCloud',
  'dbtype' => 'mysql',
  'version' => '7.0.2.1',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin',
  'dbpassword' => REDACTED,
  'installed' => true,
  'skeletondirectory' => '',
  'logtimezone' => 'America/Los_Angeles',
  'loglevel' => 2,
  'logfile' => 'C:\\Data\\Logs\\ownCloud\\owncloud.log',
  'log_rotate_size' => 209715200,
  'log_query' => false,
  'maintenance' => false,
  'blacklisted_files' => 
  array (
    0 => '.htaccess',
    1 => '*.lnk',
    2 => '.DS_Store',
    3 => 'thumbs.db',
    4 => 'desktop.ini',
    5 => '*.url',
    6 => '\$RECYCLE.BIN',
    7 => '~\$*',
    8 => 'hiberfil.sys',
    9 => 'pagefile.sys',
  ),
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => REDACTED,
    2 => REDACTED
    3 => REDACTED
    4 => REDACTED
    5 => REDACTED
  ),
  'filesystem_check_changes' => 2,
  'forcessl' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => REDACTED
  'mail_from_address' => 'noreply-owncloud',
  'mail_domain' => REDACTED,
);
```

### External Storage:
local
smb

### Encryption:
no

### Client configuration
not a client issue

### Logs
not a web server issue

#### ownCloud log (data/owncloud.log)
```
{"app":"index","message":"Doctrine\\DBAL\\DBALException: An exception occurred while executing 'INSERT INTO `oc_file_map` (`logic_path`, `physic_path`, `logic_path_hash`, `physic_path_hash`)\n\t\t\t\tVALUES (?, ?, ?, ?)':\n\nSQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\\xE9 or \\xE7...' for column 'logic_path' at row 1","level":4,"time":"2014-11-10T16:43:43-08:00"}
```

**Comment by sdesvergez** [comment]
All seems to be fixed only by the side of MariaDB/MySQL server since type of columns logic_path and physic_path are changed to blob. Then all INSERT queries work as expected.
But, from WebGUI or Sync client the SELECT query does not work and current directory looks empty. Query on blob values should work with internal function CONVERT(column USING UTF8) as `select convert(logic_path using utf8) from oc_file_map limit 0,10`
But I really don't know where it could be used.

**Comment by LeeThompson** [comment]
Just for the heck of it, I tested this stuff under Debian Unix without Windows involved at all.   UTF-8 is still broken.   

I've given up on owncloud.
