### ISSUE TITLE
Print option along with "edit"

### ISSUE THREAD

**Issue by pdrass** [owncloud/core#12121]
Versions:
ownCloud 7.0.2
PHP 5.5.9
mysql Ver 14.14 Distrib 5.5.40, for debian-linux-gnu (x86_64) using readline 6.3

This is a feature request more than a "bug".  I had a client ask me about their ownCloud and if the "edit" logged as an edit when they only wanted to print the document on the web version.  It turns out it doesn't actually edit the file, it simply opens it and it's not logged under the activity plugin.

So, from an end users view edit doesn't mean open or print (even though you can do all that).  I wonder if there could be a drop down where edit exists to:  edit > view > print.

Again, from an end user perspective this makes more sense even though us Geeks assume edit does all those things.

**Comment by Xenopathic** [comment]
Closing due to ambiguity. This sounds like something for the Documents app to handle: see https://github.com/owncloud/documents
