### ISSUE TITLE
Group Admin: Should be able to delete from group, not from system

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#1212]
Today, a group admin can add new users within their group.  That works well.

But, the user can delete ANY user in their group from the system completely.  That should not be.  There should be a configurable option set by the overall admin where the group admin can/cannot delete users from the system when deleting from the group. Also, a group admin should never be able to delete a user from the system that is a member of another group. These use cases should help explain:

Example 1: user 1, user 2 and user 3 are added by the overall admin.  user 1 is the group admin of group 1.  user 2 and 3 are also members of this group.  user 3 is also a member of group 2.  user 1 deletes user 3 from group 1, but user 3 should still be a member of group 2, and the group 1 admin should not be able to delete user 3 from the system, only from their group.  This is regardless of any configurable options mentioned above.

Example 2: user 1, user 2 and user 3 are added by the overall admin, and made members of group 1.  user 1 is the group admin of group 1. The admin does not grant user 1 the right to delete users from the system when deleted from the group. user 1 removes user 2 from the group with a delete.  user 2 is still a member of the system, but is no longer a member of any group.  The overall admin can then delete the user if necessary, or assign other groups.

Example 3: user 1, user 2 and user 3 are added by the overall admin, and members of group 1. user 1 is the admin of group 1. The overall admin GRANTS user 1 the right to delete users from the system when deleted from the group.  user 1 deletes user 2 from group 1, and since he is not a member of any other group, user 2 is deleted from the system.

Example 4: user 1 is the group admin of group 1.  User 1 adds a new user to the system as a member of group 1. At a later time, user 1 can delete the added user from the group and possibly from the system following the configuration switch in Examples 2 and 3.

**Comment by MorrisJobke** [comment]
@LukasReschke I think this won't make it into 8.0 - postpone it to 8.1 - cc @DeepDiver1975

**Comment by Xenopathic** [comment]
Replaced by #3362
