### ISSUE TITLE
Automatic upgrade after package upgrade

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#12125]
Since OC 7 there's a "Update now" button that needs to be clicked manually.

Ideally admins should rather run `./occ upgrade` to make sure to not run into PHP timeouts.

The idea is to provide a mechanism to run an unattended upgrade:
1) In the case of distro packages, automatically run `./occ upgrade` on the instance
2) In the case of tarballs, provide a config.php option to disable the "Update now" button and run the upgrade automatically (but need to look into potential concurrency issues if multiple people open OC at the same time)

CC @jnweiger

**Comment by jnweiger** [comment]
https://build.opensuse.org/package/show/home:jnweiger:branches:isv:ownCloud:community:7.0/owncloud got lost meanwhile. Restored.

**Comment by jnweiger** [comment]
Merged into https://build.opensuse.org/package/show/isv:ownCloud:community:8.0/owncloud

**Comment by jnweiger** [comment]
Implementation is in debian.owncloud-server.preinst debian.owncloud-server.postinst
Confirmed working well for owncloud 7->8 ugrade. Please reopen, if needed for 7.0.x updates.

**Comment by mcnesium** [comment]
Doesnt look like it works over here. OC 8 -> 8.0.1

![eepo3cee](https://cloud.githubusercontent.com/assets/476060/6502023/c081d196-c31f-11e4-9bbb-822131103ac9.png)

**Comment by mcnesium** [comment]
has this been [snafu](https://owncloud.org/blog/owncloud-8-0-1-snafu/)-related?

**Comment by mcnesium** [comment]
It had, obviously. The current method is way better than it used to be for users (if it works[*](https://github.com/owncloud/core/issues/14806). Thank you for changing that!
