### ISSUE TITLE
OC7.0.2 Possible missing indexes in PostgreSQL database.

### ISSUE THREAD

**Issue by PhilJung** [owncloud/core#12132]
PostgreSQL 9.1 database, Apache 2.2.15-30, PHP 5.4.26 all running on Centos 6 servers.

OC configured with encryption enabled. Database contains 100.000 users

Injection performed through JMeter : 
30 concurrent connections doing "get /, log in, wait for the encryption tasks (first connection) to be finished, log out. 

Looks like some tables are heavily sequentialy accessed. Probably some missing indexes or too many full scan requested by the code.

[owncloud@]owncloud=> SELECT relname, seq_scan,idx_scan FROM pg_stat_user_tables;

relname | seq_scan | idx_scan 
------- | ------------- | -----
oc_pictures_images_cache | 1 |         
oc_share_external | 4 | 106518
oc_documents_invite               |        1 |         
oc_documents_revisions         |        2 |        0
oc_filecache                 |     5992 | 26764405
oc_documents_member          |        2 |        0
oc_clndr_repeat              |        2 |        0
oc_vcategory_to_object       |        3 |        0
oc_privatedata               |        2 |        0
oc_preferences               |     2431 |  1065543
oc_jobs                      |   517982 |   419521
oc_contacts_cards_properties |        5 |        0
 oc_clndr_share_calendar      |        1 |       
 oc_contacts_cards            |        3 |        0
 oc_activity_mq               |        8 |        0
 oc_contacts_addressbooks     |        3 |       62
 oc_clndr_share_event         |        1 |         
 oc_group_admin               |        7 |    21636
 oc_documents_session         |        2 |        0
 oc_clndr_calendars           |        2 |        0
 oc_file_map                  |        4 |        0
 oc_files_trash               |        5 |        0
 oc_appconfig                 |  6990912 |      271
 oc_properties                |        3 |      138
 oc_group_user                |   106624 |    65015
 oc_clndr_objects             |        2 |        0
 oc_lucene_status             |        3 |        0
 oc_mimetypes                 |    72546 |        0
 oc_locks                     |        2 |        0
 oc_activity                  |        6 |        0
 oc_share                     |   106611 |  7534583
 oc_users                     |   214263 |    51500
 oc_vcategory                 |        5 |        0
 oc_groups                    |     6981 |   303827
 oc_documents_op              |        3 |        0
 oc_storages                  |    34720 |  5746185
 oc_gallery_sharing           |        2 |       

I have identified at least the following sequential scan:
SELECT "uid", "password" FROM "oc_users" WHERE LOWER("uid") = LOWER($1)
SELECT "uid", "displayname" FROM "oc_users" WHERE LOWER("uid") = LOWER($1)
They can be fixed by 
CREATE INDEX lower_users_uid ON oc_users ((lower(uid)));

**Comment by MorrisJobke** [comment]
Looks good in current 8.2.2:

```
EXPLAIN SELECT `oc_share`.`id`, `item_type`, `item_source`, `item_target`,`oc_share`.`parent`, `share_type`, `share_with`, `uid_owner`,`file_source`, `path`, `file_target`, `oc_share`.`permissions`,`stime`, `expiration`, `token`, `storage`, `mail_send`,`oc_storages`.`id` AS `storage_id`, `oc_filecache`.`parent` as `file_parent` FROM `oc_share` INNER JOIN `oc_filecache` ON `file_source` = `oc_filecache`.`fileid`  AND `file_target` IS NOT NULL INNER JOIN `oc_storages` ON `numeric_id` = `oc_filecache`.`storage`  AND ((`share_type` in ('0', '2') AND `share_with` = 'USERNAME') ) AND `uid_owner` != 'USERNAME' ORDER BY `oc_share`.`id` ASC;
+----+-------------+--------------+--------+--------------------------------------------------------------------------------------+---------+---------+----------------------------------+-------+-------------+
| id | select_type | table        | type   | possible_keys                                                                        | key     | key_len | ref                              | rows  | Extra       |
+----+-------------+--------------+--------+--------------------------------------------------------------------------------------+---------+---------+----------------------------------+-------+-------------+
|  1 | SIMPLE      | oc_share     | index  | file_source_index,oc_share_file_target                                               | PRIMARY | 4       | NULL                             | 33222 | Using where |
|  1 | SIMPLE      | oc_filecache | eq_ref | PRIMARY,fs_storage_path_hash,fs_storage_mimetype,fs_storage_mimepart,fs_storage_size | PRIMARY | 4       | oc_share.file_source        |     1 |             |
|  1 | SIMPLE      | oc_storages  | eq_ref | PRIMARY                                                                              | PRIMARY | 4       | oc_filecache.storage            |     1 |             |
+----+-------------+--------------+--------+--------------------------------------------------------------------------------------+---------+---------+----------------------------------+-------+-------------+
```
