### ISSUE TITLE
Sabre\DAV\Exception\NotAuthenticated: No basic authentication headers were found

### ISSUE THREAD

**Issue by bkerensa** [owncloud/core#12146]
Getting this error constantly filling log on OC 7.0.3 on Ubuntu Linux (I do not even use webdav?)
Debug	webdav	Sabre\DAV\Exception\NotAuthenticated: No basic authentication headers were found

**Comment by bitsandnumbers** [comment]
I have the same issue. My client is on a Mac, but is doesn't seem to be the culprit, as I also get, as in the message above, an error for carddav.

**Comment by PVince81** [comment]
Are you still seeing this with 8.1.3 ?

**Comment by clementhk** [comment]
I started to get his when i upgraded from 8.0 to 8.1.3

**Comment by DeepDiver1975** [comment]
in debug mode we are logging this exception which indicates no issue at all -> closing

**Comment by clementhk** [comment]
We fixed it here by disabling nginx fastcgi_buffering.
So `fastcgi_buffering off;` in site config file.

**Comment by bitsandnumbers** [comment]
@clementhk This workaround didn't work on my side, still get the same message...

**Comment by RealRancor** [comment]
@bitsandnumbers Then lower the loglevel from debug to the standard-loglevel. Should be obvious that a debug mode shouldn't be used on an productive system as Debug is always logging a lot of stuff.

**Comment by bitsandnumbers** [comment]
@RealRancor My bad, didn't remember log level was set to 0. Thanks

**Comment by deviousway** [comment]
Tnx  fastcgi_buffering off; in 
```
location ~ \.php(?:$|/) {
 fastcgi_buffering off;

```
Working for me (Archlinux+Nginx+php-fpm (php7),  tyvm

**Comment by RealRancor** [comment]
@josh4trunks Sorry to ping you directly again but are you aware if there are any drawbacks setting this fastcgi_buffers to off?

**Comment by josh4trunks** [comment]
@RealRancor I'm not familiar with the implications. I personally have never tweaked that.

**Comment by RealRancor** [comment]
@josh4trunks Thanks for the info. I'm also on the defaults of the buffering options and never had any issues like the one described here. Maybe the people in here had too low buffers and configured which was causing that issues.

**Comment by deviousway** [comment]
@josh4trunks @RealRancor 
you can use separate location for auth just use same settings as 'php location' location ~ \.php(?:$|/)
for examle
```
location /remote.php/webdav {
fastcgi_split_path_info ^(.+\.php)(/.+)$;
                        include fastcgi_params;
                        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                        fastcgi_param PATH_INFO $fastcgi_path_info;
                        fastcgi_param HTTPS on;
                        fastcgi_param MOD_X_ACCEL_REDIRECT_ENABLED on;
                        fastcgi_buffering off;
                        fastcgi_pass unix:/var/run/php-fpm/my.deviousway.ru.sock;
}
```

**Comment by RealRancor** [comment]
@deviousway We both don't need that as we both are using the defaults (buffering on) without seeing such issues.

**Comment by deviousway** [comment]
@RealRancor sorry wrong post

**Comment by josh4trunks** [comment]
not sure what this is needed for since I haven't experienced this myself. but if you are going to specify an exact path you can use "location =" so nginx doesn't need to do any regex.

**Comment by clementhk** [comment]
I was also using default buffering and it worked until 8.1.
I'm not so sure if it is related but we have lots of huge files being sync everyday, traffic is maybe 5 TB a day.

**Comment by RealRancor** [comment]
Mhhh, maybe something for:

https://github.com/owncloud/documentation/wiki/Uploading-files-up-to-16GB

if that is related to huge files.

**Comment by clementhk** [comment]
@RealRancor it worked up to 8.0, and stopped working on 8.1, and it works again if I downgrade it, so I don't think that one is related.
