### ISSUE TITLE
Debug	files_sharing	can not update etags on /files/ for user michael. Path does not exists	2014-11-12T20:19:26+00:00

### ISSUE THREAD

**Issue by bkerensa** [owncloud/core#12147]
Getting this error for pretty much all my users spamming my logs pretty heavily on OC 7.0.3 on Linux
Debug	files_sharing	can not update etags on /files/ for user michael. Path does not exists	2014-11-12T20:19:26+00:00

**Comment by PVince81** [comment]
I found this happening too and can reproduce the issue. Closing in favor of https://github.com/owncloud/core/issues/14370

Surprised to see that it already happened back then in 7.0.3

**Comment by PVince81** [comment]
Has the user "michael" ever logged in before ? Can you check if that user has a folder "data/michael/files". If not, you could ask that user to login at least once, it is likely to make the messages disappear.
