### ISSUE TITLE
Error	core	unable to rename, file is not writable : files_versions/MNA .v	2014-11-12T20:19:17+00:00

### ISSUE THREAD

**Issue by bkerensa** [owncloud/core#12148]
Getting this error spamming my admin log pretty frequently on OC 7.0.3 on Linux
Error	core	unable to rename, file is not writable : files_versions/MNA .v	2014-11-12T20:19:17+00:00

**Comment by PVince81** [comment]
Closing as duplicate of https://github.com/owncloud/core/issues/17962 which has more details
