### ISSUE TITLE
Cleanup/improve Javascript namespaces

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#12156]
### Steps to see the mess
1. Run "./buildjsdocs.sh"
2. Browse "build/jsdocs/index.html" (or see here for a snapshot: http://vincentpetry.net/ocjsdocs/)

A few issues:
- [x] snap.js is included in the docs, that should solve itself after we move to bower (@MorrisJobke)
- [x] ExperiencedAdmin is in the global namespace could be moved to OCA.LDAP.ExperiencedAdmin (@blizzz)
- [ ] Many other symbols in the global namespace (mostly in js.js) should be moved to "OC"

Note: the JSDoc template isn't ideal for nested namespaces, this will be looked into separately.

**Comment by blizzz** [comment]
> ExperiencedAdmin is in the global namespace could be moved to OCA.LDAP.ExperiencedAdmin

LDAP Wizard got refactored, i.e. done
