### ISSUE TITLE
7.0.3-1 Webdav issue when External Storage is enabled

### ISSUE THREAD

**Issue by jpeters** [owncloud/core#12167]
I know this is similar to issue #12122, but I am not using encryption. Litmus returns a 500 error at step 2.

### Steps to reproduce
1. Updated owncloud from 7.0.2 to 7.0.3-1
2. Enable External Storage
3. Attempt to access Files or sync from desktop client fails

### Expected behaviour
Files should list all synchronized files and desktop client should be able to connect to owncloud instance.

### Actual behaviour
Files does not list any files for authenticated users. Desktop client is unable to connect. 

### Server configuration
**Operating system**: Ubuntu 14.04.1

**Web server:**
Server version: Apache/2.4.7 (Ubuntu)

**Database:**
mysql-server-5.5     5.5.40-0ubuntu0 amd64

**PHP version:**
php5                 5.5.9+dfsg-1ubu all

**ownCloud version:** (see ownCloud admin page)
7.0.3 (Stable)
owncloud             7.0.3-1         all

**Updated from an older ownCloud or fresh install:**
Updated from 7.0.2

**List of activated apps:**
Activity
Bookmarks
Deleted files
Documents
External Sites
First Run Wizard
Full Text Search
LDAP user and group backend
Mail Template Editor
PDF Viewer
Pictures
Share Files
Text Editor
Updater
Versions
Video Viewer

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => 'ocb06bd369e3',
  'passwordsalt' => 'redacted',
  'trusted_domains' => 
  array (
    0 => 'redacted',
  ),
  'datadirectory' => '/var/OCData',
  'dbtype' => 'mysql',
  'version' => '7.0.3.4',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'redacted',
  'dbpassword' => 'redacted',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'maxZipInputSize' => 838860800,
  'allowZipDownload' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'redacted',
  'mail_smtpsupport' => 25,
  'theme' => '',
  'maintenance' => false,
  'forcessl' => true,
  'mail_from_address' => 'Files',
  'mail_domain' => 'redacted',
  'mail_smtpport' => '25',
  'mail_smtpsecure' => 'tls',
  'mail_smtpname' => 'redacted',
  'mail_smtppassword' => 'redacted',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes, SMB

**Are you using encryption:** yes/no
No

### Client configuration
**Browser:**
Chrome

**Operating system:**
Ubuntu 14.0.4.1

#### Web server error log

[Thu Nov 13 23:01:55.167653 2014] [:error] [pid 16484] [client 172.16.181.2:51054] PHP Fatal error:  Call to a member function getUID() on a non-object in /var/www/owncloud/apps/files_external/lib/config.php on line 124, referer: https://files.innovativeii.com/index.php/apps/files/
[Thu Nov 13 23:01:57.934724 2014] [negotiation:error] [pid 16475] [client 172.16.181.2:51058] AH00687: Negotiation: discovered file(s) matching request: /var/www/owncloud/settings/apps (None could be negotiated)., referer: https://files.innovativeii.com/index.php/apps/files/
[Thu Nov 13 23:01:59.298109 2014] [:error] [pid 16521] [client 99.55.193.106:50734] PHP Fatal error:  Call to a member function getUID() on a non-object in /var/www/owncloud/apps/files_external/lib/config.php on line 124
[Thu Nov 13 23:01:59.436973 2014] [:error] [pid 10981] [client 172.16.181.2:51059] PHP Fatal error:  Call to a member function getUID() on a non-object in /var/www/owncloud/apps/files_external/lib/config.php on line 124

#### ownCloud log (data/owncloud.log)
This is presented multiple times per minute
Call to a member function getUID() on a non-object at /var/www/owncloud/apps/files_external/lib/config.php#124

**Comment by PVince81** [comment]
Did you guys have any more luck with 7.0.4 ?

**Comment by redhell** [comment]
For me it's fixed!

**Comment by strugee** [comment]
Yes, thanks. All is well.

**Comment by jpeters** [comment]
This is resolved for me as well.

**Comment by PVince81** [comment]
Okay thanks guys, glad to hear that it works for you all. :smile: 

Closing.
