### ISSUE TITLE
[7.0.2 + 7.0.3] LDAP User Athentication with different UserGroups and Quotas

### ISSUE THREAD

**Issue by duckdiver** [owncloud/core#12165]
Steps to reproduce:
-------------------------

3x LDAP Group Owncloud groups:

Standard (Default) with 4GB
Advanced 16GB
Premium 50GB

Configured in Owncloud as 3x different Servers with the same Server-IP belonging to different LDAP Groups

As described here: http://doc.owncloud.org/server/7.0/admin_manual/configuration/auth_ldap.html

**

Login as User1 belonging to Standard LDAP group > 4GB

Login as User2 belonging to Advanced LDAP group > 16GB

Login as User3 belonging to Premium LDAP group > 50GB

Each on the same server….

But actually we can see some curious behavior on User QUOTAs ….once they are correct, the next time they got changed??
Do you know any Issues on QUOTAS in Cummunity Edition??

The descripted solution with additional LDAP Quota Field does not work on our system.
Do you have any

---------------------
Expected result:
---------------------
Each User is getting his Volume "quota" depending which LDAP User Group he is member of and quota stays fixed stable

----------------
Actual result:
----------------
the quotas of each user is changing sometimes to Standard LDAP User Group …depending which LDAP group you save latest it will get quota.

**Comment by blizzz** [comment]
Does the issue still exist with current versions?

**Comment by PVince81** [comment]
Closing this old ticket. Please try again with a more recent version like 8.2.6, 9.0.2 or 9.1.0beta2.

If the problem still exists, please report back and reopen.
