### ISSUE TITLE
JS unit tests for external storage frontend

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#12163]
Before doing any clean up or refactoring of the external storage frontend, it's a good idea to first write some unit tests. These will mostly rely on interacting with DOM elements.

This is also an opportunity to properly encapsulate the JS code into a namespace or class, which should require minimal changes for now.

This is the prerequisite before we'll be able to fix the config format later in #11261

**Comment by Xenopathic** [comment]
Related: #11884

**Comment by PVince81** [comment]
Test basics introduced by https://github.com/owncloud/core/pull/11884, closing.
