### ISSUE TITLE
xCache problem

### ISSUE THREAD

**Issue by NesooseN** [owncloud/core#12179]
If you use 2 installations of ownClodu on server with xCache (I use 3.1.0 xCache) second version of ownCloud would use some of settings etc. from first version of vice versa, in short only one can work.

I think problem is that ownCloud store same values with same xCache caching keys and causing problems.

How can this be resolved, what I need to add on second installationof ownCloud to avoid this.

**Comment by DeepDiver1975** [comment]
@LukasReschke cache key issue?

**Comment by DeepDiver1975** [comment]
We see multiple owncloud versions installed in parallel - should no long be of an issue - please reopen in case this is still an issue - THX
