### ISSUE TITLE
Start of owncloud failed (http://localhost/owncloud)

### ISSUE THREAD

**Issue by Mechtilde** [owncloud/core#12185]
after upgrade my Debian wheezy with backports I get this message:

An exception occurred while executing 'ALTER TABLE `oc_oc_appconfig_57a708fd05dbd` DROP PRIMARY KEY': SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'PRIMARY'; check that column/key exists.

actual I have version 7.0.2.

**Comment by DeepDiver1975** [comment]
@Mechtilde are you using mariadb?

**Comment by Mechtilde** [comment]
AS already discussed at IRC this was a problem of the version in Debian Wheezy-Backports 7.0.2. 
I use a MySQL-Server.
I updated to 7.0.4 in Jessie and all thins works

**Comment by LukasReschke** [comment]
So you are using the Debian packages from Debian and not ours? - Right?

**Comment by PVince81** [comment]
Closing due to lack of feedback.
