### ISSUE TITLE
LDAP: Add fallback for Group Filtering when member-of is not available

### ISSUE THREAD

**Issue by rolffokkens** [owncloud/core#12187]
In Directory Settings one can configure memberUid as the "Group Member Assiciation". This feature however does not propagate to the "User Filter" setting. Which is an issue for us, because we're running OpenLDAP conforming to RFC2307 using memberUid. Not all our LDAP users should be allowed to use our owncloud, but currently we have no means to restrict this.

I fix would be more than welcome.

**Comment by DeepDiver1975** [comment]
@blizzz member-of - rings the :bell: to me - isn't that implemented by now? THX

**Comment by blizzz** [comment]
@DeepDiver1975 requested is a fallback method when memberof is not available, so groups can still be selected in user filter. This is still open.

**Comment by DeepDiver1975** [comment]
thx

**Comment by PVince81** [comment]
Please reopen in the [user_ldap app repo](https://github.com/owncloud/user_ldap) if the issue persists with 10.0.4 and the latest version of the user_ldap app from the marketplace.
