### ISSUE TITLE
feature request: occ console encrpytion functionality

### ISSUE THREAD

**Issue by maphy-psd** [owncloud/core#12196]
Hi!

Can you add the (en/de)cryption functionality to the occ console? I run my owncloud on a shared hosting and have a maximal execution script time. When i deactivate the encryption app and i have to decrypt my files, the maximal execution script time is not enough and the script will killed befor all files are decrypt. With the occ console i have no maximal execution script time.

Thanks for listening!

**Comment by MorrisJobke** [comment]
@schiesbn Isn't this possible with the new encryption?

**Comment by schiesbn** [comment]
exists since ownCloud 8.2 https://doc.owncloud.org/server/9.0/admin_manual/configuration_server/occ_command.html?highlight=encryption#encryption-label
