### ISSUE TITLE
AD Primary Group issue

### ISSUE THREAD

**Issue by bboule** [owncloud/core#12190]
I have discovered a problem with the way Primary groups are recognized.  In my example I am going to use the group Domain Users.  In this case, my AD environment all users are a member of Domain Users and this is their Primary group (for 47 of the 48 users).  When I point the OC User Filter to find just these users (Domain Users), it only find 1 user, this happens to be the user who is a member of domain users, but domain users is not this user Primary group.

To confirm, when I go in and start changing users Primary group to something other than Domain Users, the search filter in OC starts to find these users.

Please let me know if we need any logs etc,  In this case the test system is running oc with php 5.5 on Ubuntu 12.02 LTS ownCloud 7.0.3 EE GA

Thanks,

Bob

**Comment by MorrisJobke** [comment]
Backport is in #16456
