### ISSUE TITLE
[7.0.3] ldap configuration impossible (openldap)

### ISSUE THREAD

**Issue by bedzkowp** [owncloud/core#12192]
Hey, I think there is some kind of bug in the latest release.

I can't configure it to work with openldap (user_ldap app) using wizard on the Admin page.
The site hangs on the second, sometimes third page of the wizard (user filter, login filter). It can't verify/save settings and doesn't show number of users found.

In oc logs there is a lot of lines like this:
http://pastebin.com/bvHTk5Le

In ldap logs I can see lines like:
Nov 14 17:08:34 pydio-dev slapd[6406]: conn=5738 op=20 SRCH attr=dn
Nov 14 17:08:34 pydio-dev slapd[6406]: conn=5738 op=20 SEARCH RESULT tag=101 err=4 nentries=500 text=
Nov 14 17:08:34 pydio-dev slapd[6406]: conn=5738 op=21 SRCH base="dc=test,dc=edu,dc=com" scope=2 deref=0 filter="(&(|(objectClass=inetOrgPerson))(mail=*))"

The most important thing is that it loops and even when I close the browser spald uses a lot of cpu:
PID    USER      PR  NI  VIRT    RES  SHR S  %CPU %MEM    TIME+  COMMAND 
6406 openldap  20   0  478m   6484 1396 S  98.6     0.3          66:59.45 slapd

restarting apache helps

There are exactly 1003 users in ldap.

Everyting works fine with the same ldap, apache, etc with owncloud 7.0.2

**Comment by leonweber** [comment]
Hey, are there any news on this? Seems to be broken for me still on 7.0.4. Anything I can do? (Unfortunately, I have no access to the LDAP-logs.)

**Comment by bedzkowp** [comment]
Hello, nope, it's still broken.
Just disable request paging in advanced tab and it should run fine.

**Comment by blizzz** [comment]
This is old. There were a lot of fixes meanwhile in the 7 series as well as 8. I close it, please reopen if the issue still exists in up to date versions.
