### ISSUE TITLE
"Updating ownCloud to version {version}"

### ISSUE THREAD

**Issue by RobinJ1995** [owncloud/core#12204]
Using the Dutch translations, this is what I get while updating ownCloud to version 7.0.3. I'm not talking about the string being in English, but about the `{version}` placeholder.

![snapshot577](https://cloud.githubusercontent.com/assets/3089559/5059301/d525a06e-6d16-11e4-8ae3-aa1a4e838fa0.png)

**Comment by PVince81** [comment]
Hmm... I tried this again and again with different settings:
1) While being logged in with default locale
2) While being logged in with French locale
3) While being logged out with default locale
4) While being logged out with French locale

The version number was always properly displayed.

I do remember seeing it from times to times.

**Comment by PVince81** [comment]
Okay, if I checkout stable7 (4d42485bf5a3d0af69d196a46c2b499112af515c) and upgrade to master (65ee2b1de88e490672067257a6a704a697d71e1e) the message does not appear.

**Comment by PVince81** [comment]
This happens because the file that loads the config strings is not available.
I see that `http://localhost/owncloud/index.php/core/js/oc.js?v=e678535969e5c1b76f3bef518961eaf2` is returning "503 service not available".

Possibly caused by recent changes to base.php.

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/core/pull/13341
It uses another more reliable way to read product name + version.
