### ISSUE TITLE
Fatal Errors after fresh install from master and enabling files_external and music

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#12201]
Ubuntu 14.04, nginx, mysql

Having a clean database and a empty folder, installed owncloud from git/master (10min ago, did it twice to confirm) via sudo ocdev setup base --dir /var/www/xxxx
and set the permissions afterwards to the data directory as usual.
No errors are in owncloud.log or nginx logs
After finalizing the installation, owncloud.log and nginx logs stay empty

BUT when I enabled Music and / or files_external following fatal error are shown in the owncloud.log
```
Fatal	core	Invalid OCS content returned for app music
Fatal	core	Invalid OCS content returned for app files_external
```
Maybe this related (or not), but anyway I document this too:

When adding directly after via files_external a local folder containing pictures, let owncloud finish to scan it and switch to the gallery app, a spinner is shown endless but no pictures. This behaviour is new and was not present in the past.

Doing the same for a folder containing music and switching to the music app, the screen stays empty, not even a spinner is shown. owncloud.log contains 2 errors:
```
Error 	PHP 	js file not found: script:js/md5/md5.min serverroot:/a/b/c/d at /a/b/c/d/lib/private/template/resourcelocator.php#46

Fatal 	index 	Exception: {"Message":"js file not found: script:js\/md5\/md5.min serverroot:\/a\/b\/c\/d","Code":0,"Trace":"#0 \/a\/b\/c/d\/lib\/private\/templatelayout.php(152): OC\\Template\\ResourceLocator->find(Array)\n#1 \/a\/b\/c\/d\/lib\/private\/templatelayout.php(103): OC_TemplateLayout::findJavascriptFiles(Array)\n#2 \/a\/b\/c\/d\/lib\/private\/template.php(118): OC_TemplateLayout->__construct('user', 'music')\n#3 \/a\/b\/c\/d\/lib\/public\/appframework\/http\/templateresponse.php(146): OC_Template->fetchPage()\n#4 \/a\/b\/c\/d\/lib\/private\/appframework\/http\/dispatcher.php(104): OCP\\AppFramework\\Http\\TemplateResponse->render()\n#5 \/a\/b\/c\/oclgd\/lib\/private\/appframework\/app.php(57): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Music\\Controller\\PageController), 'index')\n#6 \/a\/b\/c\/d\/lib\/private\/appframework\/routing\/routeactionhandler.php(44): OC\\AppFramework\\App::main('PageController', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#7 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#8 \/a\/b\/c\/d\/lib\/private\/route\/router.php(250): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#9 \/a\/b\/c\/d\/lib\/base.php(746): OC\\Route\\Router->match('\/apps\/music\/')\n#10 \/a\/b\/c\/d\/index.php(28): OC::handleRequest()\n#11 {main}","File":"\/a\/b\/c\/d\/lib\/private\/template\/resourcelocator.php","Line":46} 
```

**Comment by Xenopathic** [comment]
The exception due to missing JS files has been fixed with #14689, but that is unlikely to fix the underlying problem. If you get any additional information about what happens to cause the app to fail to install, please open a new issue.
