### ISSUE TITLE
enable user backends to show a different page when login failed (e.g. password wrong or needs to change)

### ISSUE THREAD

**Issue by finius** [owncloud/core#12215]
ownCloud seems not to support password changes for AD users!
If a user is forced by AD to change his password (i.e. after a reset caused by IT-helpdesk), he got to find an alternative way to change his password before he will able to log in to ownCloud again.

Further, ownCloud tries to send a password reset mail in the case above - even to Active Directoy imported users, which makes no sense.

**Comment by MorrisJobke** [comment]
I migrated the blue ticket from #16816

---

### Architecture
ownCloud version": "7.0.3.4"
PHP Version": "5.4.34"
Apache 2.2.15 (SLES Expanded Support)
LDAP activated

### Expected behavior: 
LDAP User writes a wrong password and gets a message to contact the administrator.

### Actual behavior:
LDAP USer writes a wrong password and gets a link per Email, and the token is invalid. 

How to turn off this option?

### Steps to reporduce it:
1.- Write a valid user and a wrong password,
2.- ask to reset the password.
3.- The oC Server sends an Email with link but can't reset password (token is not valid).

### Logs

Apache and ownCloud Logs and LDAP configuration in 
S3-ownCloud\Shared\owncloud\support\github-issues\core\16816

@MorrisJobke 

00002757

**Comment by RealRancor** [comment]
Hi,

instead of showing just a message to contact the admin a possibility could be to allow an admin to specify an external URL. This could point to a phpnyldapadmin installation for example where a user can reset its password.

**Comment by bboule** [comment]
Might work for OpenLDAP but not a good option for AD shops... IMHO

**Comment by bboule** [comment]
@MTRichards This seems like something to be considered for future release??

**Comment by MTRichards** [comment]
Need some clarity on the blue part here. 
When a user enters a bad password, they are offered the reset password link by default, even if using LDAP/AD? 
Clearly a "forgotten password" configuration option would be nice so that the "forgotten password" link is either configurable, or can be disabled. 

Is that the ask?

**Comment by blizzz** [comment]
The basic question here is (because of how the user management is designed), if the user was not able to authenticate against the backend, how do you now whether he actually belongs to the LDAP backend? Maybe it's an imap user. Or a local. Or from somewhere else.

**Comment by finius** [comment]
sure, if the users origin can not be determined there is no need for any password reset dialogs, 
But if the username can be verified in some way by any one source (LDAP, AD, IMAP, local -  and regardless of the password given), the "password reset" dialog can be handled the right way.

**Comment by cdamken** [comment]
@MTRichards @blizzz @MorrisJobke @DeepDiver1975 Would it be possible to add at option just to disable the mail option and just a note displayed like: 
##### Password wrong, contact your administrator

**Comment by MTRichards** [comment]
Yes. It is currently tagged for 8.2. The feature is something like this:

As an administrator, I want to be able to disable the "forgot password link" and display a simple message to my end users. 

Acceptance Criteria:
- Config file option enables and disables the "forgot password link"
- Three options exist for the forgotten password link configuration - 1) default as is; 2) disable the link altogether with no password, and 3) a customer URL and message in place of the forgot password link
- Config file option allows the admin to set these options
example setting for option 3)
lost_password_link => custom, 'internal.company.com/ssopasswordreset', 'If you have forgotten your password, please reset it through our corporate sso password reset gateway';

@cdamken does that work?

@LukasReschke any security issue here with setting a URL in the config file?

**Comment by MTRichards** [comment]
Also adding

00003545

**Comment by gig13** [comment]
@gig13

**Comment by cmonteroluque** [comment]
@bboule @MorrisJobke @cdamken I consider this at risk of moving to 9.0. Need a strong push to avoid.
@LukasReschke https://github.com/owncloud/core/issues/12215#issuecomment-126033518 from Matt?

**Comment by cdamken** [comment]
@MTRichards @gig13 @cmonteroluque I'm not pretty sure, but the patch from @schiesbn could be part of this fix:

https://github.com/owncloud/core/pull/18747#issuecomment-136778601

We tested with LDAP. and worked even in 8.1.1

**Comment by blizzz** [comment]
@schiesbn's fix has nothing to do here with. His use case is that LDAP passwords have changed and encryption needs a way to convert keys. In that case the user is already logged in. The changed code belongs all to encryption.

Since Feature Freeze is here I assume we move it to 9.0?

**Comment by LukasReschke** [comment]
> @LukasReschke any security issue here with setting a URL in the config file?

No objections from my side but we need to ensure that not only the URL changes but also the controllers are not accessible anymore :-)

**Comment by cmonteroluque** [comment]
A question, are we expected to provide different behavior when the user is known to exist but has the wrong password vs when the user is not determined to even exist? My understanding is that this is a security vulnerability because it can be used to expose the name of valid users that then can be potentially targeted for a password attack or phishing

**Comment by blizzz** [comment]
@cmonteroluque see @LukasReschke reply here: https://github.com/owncloud/core/issues/12215#issuecomment-63466440

**Comment by cmonteroluque** [comment]
@blizzz Nod. I saw that before. My concern is still there (and one I've seen before in dealing with the response to failed username/password combinations). Happy to get @LukasReschke's response

**Comment by PVince81** [comment]
> No objections from my side but we need to ensure that not only the URL changes but also the controllers are not accessible anymore :-)

@LukasReschke can you clarify the thing with the controllers ? I don't see how it's related if redirecting to a separate custom page.

**Comment by PVince81** [comment]
> @cdamken does that work?

Do we agree on the config option approach from https://github.com/owncloud/core/issues/12215#issuecomment-124564471 ?

**Comment by cmonteroluque** [comment]
@nickvergessen hoping you can tackle it during the 9.0 phase

**Comment by PVince81** [comment]
@carlaschroder do we need explicit documentation for this or is the fact that it's in config.sample.php enough ?

**Comment by MorrisJobke** [comment]
> @carlaschroder do we need explicit documentation for this or is the fact that it's in config.sample.php enough ?

config.sample.php generates to a documentation page ;9

**Comment by MorrisJobke** [comment]
> config.sample.php generates to a documentation page ;)

https://github.com/owncloud/documentation/commit/d56c57c9554a99a6d2520d462b8818692be7e9a1

**Comment by PVince81** [comment]
Yeah I know, but in some cases we might want to "advertise" a feature a bit better like having TOC entries, etc.

**Comment by MorrisJobke** [comment]
> Yeah I know, but in some cases we might want to "advertise" a feature a bit better like having TOC entries, etc.

Sure. This then needs additional documentation ;)

**Comment by carlaschroder** [comment]
@PVince81 @MorrisJobke It would be fabulous if someone could send me some screenshots.

**Comment by PVince81** [comment]
@carlaschroder there are no screenshots to be shown. It's just a new config option in config.php that lets you specify a custom URL that opens whenever a user clicks the "Lost password" link. https://github.com/owncloud/documentation/commit/d56c57c9554a99a6d2520d462b8818692be7e9a1#diff-cc42d41e3199bfcefb0487b5b9e8872aR294

**Comment by carlaschroder** [comment]
Thanks @PVince81

**Comment by carlaschroder** [comment]
> config.sample.php generates to a documentation page ;)

My favorite thing!
