### ISSUE TITLE
Versioning + encryption: former versions are not decrypted when downloaded

### ISSUE THREAD

**Issue by etiess** [owncloud/core#12221]
When I download a former version of a text file from a shared folder, it is downloaded encrypted. I open this new issue after https://github.com/owncloud/core/issues/11761 and @schiesbn advice

### Steps to reproduce
1. UserA creates FolderA. 
2. UserA creates Welcome.txt in Folder A
3. UserA modifies Welcome.txt in order to have a previous version available: everything's fine until here
4. UserA shares FolderA with UserB
5. UserB downloads the previous version of Welcome.txt : the document is encrypted

### Expected behaviour
The document should be downloaded decrypted

### Server configuration
**Operating system**: Ubuntu 14.10
**Web server:** Apache 2.4.10
**Database:** MySQL Ver 14.14 Distrib 5.5.40
**PHP version:** 5.5.12
**ownCloud version:** 7.0.3
**List of activated apps:** Encryption
**Are you using external storage** No
**Are you using encryption:** yes

### Client configuration
**Browser:** FF 31
**Operating system:** Windows 8.1

**Comment by schiesbn** [comment]
@etiess https://github.com/owncloud/core/pull/13182 should fix it, maybe you can give it a try? Thanks!

**Comment by etiess** [comment]
Sorry, I'm not using encryption anymore, so I unfortunately can't test it :(

**Comment by schiesbn** [comment]
ok, anyway thanks for the feedback.
