### ISSUE TITLE
Issue with user quota/storage larger then 100GB

### ISSUE THREAD

**Issue by adammir** [owncloud/core#12231]
### Steps to reproduce
1. Login as a admin
2. Go to users page and add new user User100GB, with storage set to 100GB (or more)
3. Logout from admin
4. Login as User100GB 
5. Go to Personal page

### Expected behavior
In storage usage bar, it should be written "You are using X MB from 100 GB"

### Actual behavior
In storage usage bar, it should be written "You are using X MB from 11 GB"

### Server configuration
**Operating system**:
CentOS release 6.6

**Web server:**
httpd-2.2.15

**Database:**
MySQL: 5.5.40

**PHP version:**
PHP 5.4.30 (cli)

**ownCloud version:**
7.0.2.1

**Updated from an older ownCloud or fresh install:**
Updated from previous version

**List of activated apps:**
Default apps only

**The content of config/config.php:**
default config

**Are you using external storage
No

**Are you using encryption:
No

### Client configuration
**Browser:**
Firefox, Chrome, IE

**Operating system:**
Windows 7 and 8.1

### NOTES
Please note that same wrong values for storage are shown in OC desktop clients and mobile app

**Comment by PVince81** [comment]
Did you guys actually had 100 GB free ?
The formula is `min(actual_free_space_on_disk, quota)`.
So if there is less space on disk than the quota allows, it will show the actual available space.

But I agree that an admin might not want to reveal that information to users.

**Comment by paszczak000** [comment]
Yes it is less, because we are using LVM so we can at any time extend storage.

**Comment by MorrisJobke** [comment]
> Yes it is less, because we are using LVM so we can at any time extend storage.

But as stated above it is the behavior that is intended. So this is not a bug, but correct behavior. To get rid of the low quota increase the disk space.
