### ISSUE TITLE
"Check notifications option" does not work.

### ISSUE THREAD

**Issue by uycarumba** [owncloud/core#12238]
### Steps to reproduce
1.Login as a user or admin
2.settings/personal
3.Section "Notifications"

![image](https://cloud.githubusercontent.com/assets/4967500/5074943/3c776e04-6e5d-11e4-980c-867f9b1ba91c.png)

### Expected behaviour
"check notifications option" does not work.

when I enable the option in my settings.
'asset pipeline.enabled' => true,

the check the option of notification does not work "does not save changes".

But if I disable "asset pipeline.enabled" works correctly.

### Actual behaviour
"check notifications option" does not work.

when I enable the option in my settings.
'asset pipeline.enabled' => true,

the check the option of notification does not work "does not save changes".

But if I disable "asset pipeline.enabled" works correctly.
### Server configuration
**Operating system**:
Ubuntu 14.04.1 LTS

**Web server:**
Apache/2.4.7 (Ubuntu)

**Database:**
MySQL  5.5.40
**PHP version:**
PHP 5.5.9-1
**ownCloud version:** (see ownCloud admin page)
7.0.3.4

**Updated from an older ownCloud or fresh install:**
7.0.2

**List of activated apps:**
Default apps only

**The content of config/config.php:**
 
 'trusted_domains' =>
  array (
    0 => 'xxx.xxx.xxx',
  ),

  'dbname' => 'xxxx',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxxx',
  'default_language' => 'es',
  'maintenance' => false,
  'theme' => 'mytheme',
  'logtimezone' => 'America/Lima',
  'logdateformat' => 'F d, Y H:i:s',
  'asset-pipeline.enabled' => true, (cause of the problem.)
  'overwritewebroot' => '/owncloud',

**Are you using encryption:** yes/no
no

### Client configuration
**Browser:**
- Firefox, Chrome

**Operating system:**
Windows 7
#### Web server error log
No

#### ownCloud log (data/owncloud.log)
No

**Comment by Xenopathic** [comment]
Ah, the old JS-file-not-ending-with-a-semicolon bug. Fixed with #13116
