### ISSUE TITLE
Refactoring \OC_App

### ISSUE THREAD

**Issue by icewind1991** [owncloud/core#12230]
Currently `\OC_App` is a 1200+ line static class that does about a million different things and should be split up in multiple, non-static classes
- [x] "App Manager" to handle disabling/enabling apps and getting enabled apps #12031
- [ ] "App Loader" to handle loading app
- [ ] "App" class/interface with app metadata
- [ ] "Directory manager" to handle locating apps in the various app dirs, finding the correct app dir to install new apps in, etc
- [ ] "Settings manager" for allowing apps to integrate into the settings/admin pages

cc @PVince81 @DeepDiver1975

**Comment by PVince81** [comment]
something that will likely be re-touched when working on the marketplace stuff
