### ISSUE TITLE
Create unit test for files_sharing sharing a directory and files in subdirectory

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#12265]
Currently the [unit tests for the ShareController](https://github.com/owncloud/core/blob/106d0f9c754c91810a798de3628a0361062982ca/apps/files_sharing/tests/controller/sharecontroller.php#L68) are just checking a single file in the topdirectory. This prevented it from catching bugs such as  https://github.com/owncloud/core/pull/12264.

Therefore we should create unit tests for a shared folder and shared files in a subfolder.

@cloutier I created this issue to keep track of this issue. So we don't forget about that. - I assigned you to this issue for now. Let me know if you have any question or need assistance!

**Comment by PVince81** [comment]
Any update @cloutier @LukasReschke 

Is this still relevant @rullzer @schiesbn ?

**Comment by cloutier** [comment]
I am currently working on other projects and I don't have time to work on this, sorry.

**Comment by rullzer** [comment]
@LukasReschke probabaly it makes more sense to have this as intergration tests right? So we actually know stuff doesn't break.

**Comment by PVince81** [comment]
It is likely that we already have this.

@SergioBertolinSG when you got a few minutes please check if we have this then close.

**Comment by SergioBertolinSG** [comment]
Yes it is covered already.
