### ISSUE TITLE
IIS: config.php gets cleared/reset after sometime when upgrading

### ISSUE THREAD

**Issue by ev0lister** [owncloud/core#12263]
Config file gets cleared after some time.

### Steps to reproduce
1. Update from 7.0.2 to 7.0.3

### Expected behaviour
config.php should not be initialized after some time

### Actual behaviour
After upgrade from 7.0.2 to 7.0.3 everything works as usual, but then some time later (not yet known when and why) the config.php gets overwritten by OC.

config.php initialized with the following content:
```php
<?php
$CONFIG = array (
'instanceid' => 'xxxxxxxxx',
);
```
You can replace this one with an backup of the config file and everything works again, however after sometime same issue occurs.

### Server configuration
**Operating system**: Windows 2012 R2

**Web server:** IIS 8

**Database:** MySQL

**PHP version:** PHP 5.5

**ownCloud version:** 7.0.3 (stable) 

**Updated from an older ownCloud or fresh install:** Updated

**List of activated apps:** Only default

**The content of config/config.php:**

```php
<?php
$CONFIG = array (
  'instanceid' => '51bXXXX0ec9',
  'passwordsalt' => 'b93abb4fddd6XXXX12658cab',
  'trusted_domains' => 
  array (
    0 => 'XXX',
    1 => 'XXX',
  ),
  'overwritewebroot' => '/oc',
  'datadirectory' => 'XXXX',
  'dbtype' => 'mysql',
  'version' => '7.0.3.4',
  'dbname' => 'owncloud',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'XXXX',
  'installed' => true,
  'forcessl' => true,
  'mail_from_address' => 'noreply',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'XXXX',
  'loglevel' => '2',
  'theme' => '',
  'maintenance' => false,
);

```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

### Client configuration
**Browser:** Firefox, current version

**Operating system:** Windows 8

#### Web server error log
```
No log
```

#### ownCloud log (data/owncloud.log)
```
No log entries around time of overwriting config.php
```

#### Browser log
```
Not relevant
```

Please note: config.php gets at least touched every minute or so.. seems not to be OK.

**Comment by MatthiasJost** [comment]
Is this bug still open in 7.0.4? (https://owncloud.org/changelog/)

**Comment by LukasReschke** [comment]
7.0.4 might still be affected. We did some changes to ownCloud 8 in regard to config handlig so you might try the beta and report back.
