### ISSUE TITLE
Cleanup I*Config classes

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#12260]
So far we seem to have lots of classes and interfaces just to read the config, some legacy and some new.

We need to clean up this mess.

Here are a few:

- [ ] IConfig
- [x] OC\Preferences
- [ ] IAppConfig
- [x] OC_Config
- [x] OC_AppConfig

@icewind1991 which ones do we want to keep and which ones should go ?

**Comment by MorrisJobke** [comment]
see also stuff like #13736 and #13104

**Comment by MorrisJobke** [comment]
Drop of OC_Preferences: #13869

**Comment by MorrisJobke** [comment]
Drop of \OC\Preferences #13870

**Comment by DeepDiver1975** [comment]
While reviewing #13938 I really wonder if IAppConfig shall die :question: 

It's an isolated and easy to use object.

**Comment by Raydiation** [comment]
Stuff that is only available in IAppConfig:
* Delete all entries for an app
* Delete a key

The rest is code duplication. We might want to add those methods to the IConfig interface and then kill it, that is if those methods are actually used in our code

**Comment by MorrisJobke** [comment]
@Raydiation see #13938 ;)

**Comment by MorrisJobke** [comment]
@DeepDiver1975 We can also handle it all in IAppConfig, but we shouldn't provide two ways of doing this. Either in IConfig **OR** in IAppConfig.

**Comment by MorrisJobke** [comment]
The "or" is an exclusive one ;) Read it as an XOR ;)

**Comment by Raydiation** [comment]
IMHO makes no sense to put the setting of app config values in one class and the deletion of values in another class :)

**Comment by MorrisJobke** [comment]
> IMHO makes no sense to put the setting of app config values in one class and the deletion of values in another class :)

I moved all missing methods over to IConfig and deprecated IAppConfig with #13938 ;) The question here is if we want to do it in this way, or if we want the AppConfig be a separate interface, but then I would remove the methods from IConfig.

**Comment by Raydiation** [comment]
Separate interface makes only sense if we have the exact same signatures. That way we could keep backwards compatibility and let iconfig inherit from iappconfig.

**Comment by MorrisJobke** [comment]
Latest cleanups went into 9.0 -> closing
