### ISSUE TITLE
\OC_Helper::tmpFile can break Imagemagick

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#12282]
### Steps to reproduce
OC generates temp filenames without any extension (i.e. .mp3). It concatenates everything instead.
This test case proves that this will break Imagemagick. 

1. Install Imagemagick in your test env
2. Upload a OTF font
3. Rename the font 23926b6bec09d849d770a606d8403b96otf
4. Use `identify` to let Imagemagick determine what's in the file

Tested with OTF fonts, but could happen with more file types down the line.

### Expected behaviour
Imagemagick should be able to identify the file as an OTF font

### Actual behaviour
Instead
 ```
# identify /tmp/23926b6bec09d849d770a606d8403b96otf
identify: no decode delegate for this image format `' @ error/constitute.c/ReadImage/501.
```
If you rename the file so that extension is kept after the dot.
 ```
# identify /tmp/23926b6bec09d849d770a606d8403b96.otf
/tmp/23926b6bec09d849d770a606d8403b96.otf OTF 800x480 800x480+0+0 16-bit sRGB 96.6KB 0.039u 0:00.039
 ```

### Server configuration
**Operating system**: FreeBSD

**Web server:** Apache

**PHP version:** 5.5 with Imagemagick 6.8 or 6.9

**ownCloud version:** 7.0.3

**Updated from an older ownCloud or fresh install:** Updated

**The content of config/config.php:**

```
  'enabledPreviewProviders' =>
    array(
      'OC\Preview\Image',
      'OC\Preview\MP3',
      'OC\Preview\TXT',
      'OC\Preview\MarkDown',
      'OC\Preview\Movies',
      'OC\Preview\MSOffice2003',
      'OC\Preview\MSOffice2007',
      'OC\Preview\MSOfficeDoc',
      'OC\Preview\OpenDocument',
      'OC\Preview\PDF',
      'OC\Preview\StarOffice',
      'OC\Preview\SVG',
      'OC\Preview\TIFF',
      'OC\Preview\Illustrator',
      'OC\Preview\Postscript',
      'OC\Preview\Photoshop',
      'OC\Preview\SFNT',
    ),
```
**Are you using encryption:** no

**Comment by georgehrke** [comment]
@oparoz Can you still reproduce it on latest master? This should have been fixed with [your commit](https://github.com/owncloud/core/commit/ec7b55f5be67583e4b52c2a8d8c600f476a50e03), as we are now using [toTmpFile() which uses \OC_Helper::tmpFile with extensions](https://github.com/owncloud/core/blob/337c43ce9266106c803e6593e2006fd2b11b4f81/lib/private/files/view.php#L684).

**Comment by oparoz** [comment]
I need to rebase my patch to support fonts to be able to test. It's going to take a few days...

**Comment by oparoz** [comment]
Still a problem.
The tmp file is named `oc_tmp_d20d57d7da3bcb6236f3cd4faacacd32otf`
We need a dot in front the extension

**Comment by oparoz** [comment]
The behaviour can be tested from within OC using this PR https://github.com/owncloud/core/pull/13648
You won't get a preview for OTF fonts unless you fix `\OC_Helper::tmpFile()`

**Comment by oparoz** [comment]
This is also killing any Raw picture conversion as these formats can embed other formats as well for quick previewing

**Comment by oparoz** [comment]
Fix is in https://github.com/owncloud/core/pull/13654

**Comment by MorrisJobke** [comment]
fixein in #14878
