### ISSUE TITLE
Add OCS capability to advertise server to server sharing support

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#12289]
`curl http://root:admin@localhost/owncloud/ocs/v1.php/cloud/capabilities`

We could add "servertoserversharing" there when the server allows for it, what do you think @icewind1991 @schiesbn ?

**Comment by PVince81** [comment]
Tagged as junior job.
There are already a few existing examples in the code for that.

The capability should only be returned whenever remote sharing is enabled on the server.
See the admin section for the matching checkbox, which will lead back to the matching config key setting.

**Comment by PVince81** [comment]
In a similar way: advertise "public link" capability: https://github.com/owncloud/core/issues/13673

**Comment by PVince81** [comment]
I wonder if we should also expose the other settings that enforce the date to be only within a given number of days. This way clients could also enforce it that way.
On the other hand this could be done through validation.

Disclosing too much isn't always a good thing, isn't it @LukasReschke ?

**Comment by rullzer** [comment]
PR #13692 for #13673 can very easily be extended to include this info as well.
However we first need to come up with what we want to expose and also naming scheme so it does not become a mess.

**Comment by rullzer** [comment]
I was just thinking about this issue. Would this only be used by authenticated users? Or do we want a seperate capabilities url/view for unauthenticated users? So that instance A can ask Instance B if server2server sharing is even possible? If so that would require a bit more work in the capabilities section.

**Comment by PVince81** [comment]
So far from what I know we don't want unauthenticated users to find out the config of the server.
But if a share token is available, it might be ok to make the capabilities available.

This can indeed be a problem because in the server to server sharing case, server A doesn't authenticate against server B when asking capabilities.

But in the case of simply API clients, desktop client or mobile clients, they are anyway always authenticated. 

I'd suggest to first focus on the authenticated case.

**Comment by rullzer** [comment]
The authenticated case is easy. However we would need to know where to add it in the capabilities. Is server2server sharing only part of the files part of the capabilities or should it be more general?

I agree that we do not want to expose all the capabilities to the outside world unauthenticated. So we should probably come up with a very limited capabilities endpoint for unauthenticated users. But more on that can come later indeed.

**Comment by PVince81** [comment]
Moving to 8.2

**Comment by cmonteroluque** [comment]
@rullzer do you think you can tackle?

**Comment by rullzer** [comment]
@cmonteroluque so I can add the capability (that is trivial). But that only involves the current user if the server actually supports this. I'll fix this.

But we also need something for inter server communications. To let each other know that this server does or does not support federation.

So I'll prepare a PR for the first part.
But the second parts needs some designing. And a new (unauthenticated, or at least differently authenticated) endpoint.

**Comment by karlitschek** [comment]
Yes. This would be a good thing to have! Thanks @rullzer

**Comment by PVince81** [comment]
@rullzer is this fixed or is there anything that needs to be added ?

**Comment by rullzer** [comment]
@PVince81 yes it is done. But we still need a way to handle the unauthenticated case (i.e. a server checking if another server supports server 2 server sharing.) But that is not the original case of this issue.

Could you raise a ticket for the unauthenticated case (on my phone right now)?

**Comment by PVince81** [comment]
@rullzer raised here https://github.com/owncloud/core/issues/19228
But need to discuss why we'd need that.
