### ISSUE TITLE
Cannot mutliKeyDecrypt empty plain content

### ISSUE THREAD

**Issue by bruzzler** [owncloud/core#12287]
### Steps to reproduce
1. Activate Encryption
2. Upload files to a folder, Share a folder to a group,
3. Add a new user, add this user to the group created before
4. Log in with that user, try opening a file

### Expected behaviour
File should be opened

### Actual behaviour
Error msg:
PDF example:
File could not be opened
PDF.js v0.8.1136 (build: ca612e5)
Nachricht: Unexpected server response (403) while retrieving PDF "http://transfer.hth-service.de/index.php/apps/files/ajax/download.php?files=AirMaid_Kon_2011_07.pdf&dir=%2FEinkauf%2FKondition%2FAirMaid".

By clicking on Download:
Die Datei kann nicht entschlüsselt werden, da die Datei möglicherweise eine geteilte Datei ist. Bitte fragen Sie den Datei-Besitzer, dass er die Datei nochmals mit Ihnen teilt. 
Translation:
The file cannot be encrypted because the file is probably a shared file. Please ask the owner if he will share the file with you again.

### Server configuration
**Operating system**:
Linux depression.ispgateway.de 2.6.32.53-grsec-x86_64 #4 SMP Wed Jun 11 14:57:07 CEST 2014 x86_64 
**Web server:**
Apache
**Database:**
MySQL 5.6.19
**PHP version:**
5.4.16
**ownCloud version:** (see ownCloud admin page)
7.03 (Stable)
**Updated from an older ownCloud or fresh install:**
fresh
**List of activated apps:**
Just encryption additionally
**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'oc042a74e1b3',
  'passwordsalt' => '',
  'trusted_domains' => 
  array (
    0 => 'cloud.hth-service.de',
    1 => 'transfer.hth-service.de',
    2 => 'cloud.hth-service.ist-im-web.de',
	),
  'datadirectory' => '/kunden/XXX/cloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.2.1',
  'dbname' => 'XXX',
  'dbhost' => 'mysql5.hth-service.ist-im-web.de',
  'dbtableprefix' => 'oc_',
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
Yes
### Client configuration
**Browser:**

**Operating system:**
Windows 8.1
#### Web server error log

no log available, hosting

#### ownCloud log (data/owncloud.log)

{"app":"files_encryption","message":"set shareFileKeyFailed (code: 10): Cannot mutliKeyDecrypt empty plain content","level":4,"time":"2014-11-19T07:50:16+00:00"}
{"app":"files_encryption","message":"set shareFileKeyFailed (code: 10): Cannot mutliKeyDecrypt empty plain content","level":4,"time":"2014-11-19T07:50:16+00:00"}
{"app":"files_encryption","message":"set shareFileKeyFailed (code: 10): Cannot mutliKeyDecrypt empty plain content","level":4,"time":"2014-11-19T07:50:16+00:00"}
{"app":"files_encryption","message":"set shareFileKeyFailed (code: 10): Cannot mutliKeyDecrypt empty plain content","level":4,"time":"2014-11-19T07:50:16+00:00"}
{"app":"files_encryption","message":"set shareFileKeyFailed (code: 10): Cannot mutliKeyDecrypt empty plain content","level":4,"time":"2014-11-19T07:50:16+00:00"}
{"app":"files_encryption","message":"set shareFileKeyFailed (code: 10): Cannot mutliKeyDecrypt empty plain content","level":4,"time":"2014-11-19T07:50:16+00:00"}
{"app":"files_encryption","message":"set shareFileKeyFailed (code: 10): Cannot mutliKeyDecrypt empty plain content","level":4,"time":"2014-11-19T07:50:16+00:00"}
{"app":"files_encryption","message":"set shareFileKeyFailed (code: 10): Cannot mutliKeyDecrypt empty plain content","level":4,"time":"2014-11-19T07:50:16+00:00"}
{"app":"files_encryption","message":"set shareFileKeyFailed (code: 10): Cannot mutliKeyDecrypt empty plain content","level":4,"time":"2014-11-19T07:50:16+00:00"}
{"app":"files_encryption","message":"set shareFileKeyFailed (code: 10): Cannot mutliKeyDecrypt empty plain content","level":4,"time":"2014-11-19T07:50:16+00:00"}
{"app":"files_encryption","message":"set shareFileKeyFailed (code: 10): Cannot mutliKeyDecrypt empty plain content","level":4,"time":"2014-11-19T07:50:17+00:00"}
{"app":"files_encryption","message":"set shareFileKeyFailed (code: 10): Cannot mutliKeyDecrypt empty plain content","level":4,"time":"2014-11-19T07:50:17+00:00"}
{"app":"files_encryption","message":"set shareFileKeyFailed (code: 10): Cannot mutliKeyDecrypt empty plain content","level":4,"time":"2014-11-19T07:50:17+00:00"}
{"app":"files_encryption","message":"set shareFileKeyFailed (code: 10): Cannot mutliKeyDecrypt empty plain content","level":4,"time":"2014-11-19T07:50:17+00:00"}
{"app":"files_encryption","message":"set shareFileKeyFailed (code: 10): Cannot mutliKeyDecrypt empty plain content","level":4,"time":"2014-11-19T07:50:17+00:00"}
{"app":"files_encryption","message":"set shareFileKeyFailed (code: 10): Cannot mutliKeyDecrypt empty plain content","level":4,"time":"2014-11-19T07:50:17+00:00"}

#### Browser log
```
Insert your browser log here, this could for example include:

Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery-1.10.0.min.js:1
Synchrone XMLHttpRequests am Haupt-Thread sollte nicht mehr verwendet werden, weil es nachteilige Effekte für das Erlebnis der Endbenutzer hat. Für weitere Hilfe siehe http://xhr.spec.whatwg.org/ jquery-1.10.0.min.js:6
POST http://transfer.hth-service.de/index.php/core/ajax/translations.php [HTTP/1.1 200 OK 276ms]
getPreventDefault() sollte nicht mehr verwendet werden. Verwenden Sie stattdessen defaultPrevented. jquery-1.10.0.min.js:5
GET http://transfer.hth-service.de/index.php/apps/files/ajax/download.php [HTTP/1.1 302 Moved Temporarily 488ms]
GET http://transfer.hth-service.de/apps/files_encryption/files/error.php [HTTP/1.1 403 Die Datei kann nicht entschlÃ¼sselt werden, da die Datei mÃ¶glicherweise eine geteilte Datei ist. Bitte frage den Dateibesitzer, ob er die Datei nochmals mit Dir teilt.

**Comment by DeepDiver1975** [comment]
@schiesbn this should be fixed afaik - right?

**Comment by SerialG** [comment]
Hi, 
Any news on this issue? 
We experience exactly the same problem.

**Comment by PVince81** [comment]
@schiesbn please assist

**Comment by schiesbn** [comment]
That's not a encryption bug. The file was never encrypted for the new user. So it is obvious that we can't decrypt it for the new user, ownCloud will throw a exception and the PDF Viewer app needs to handle it like it is done by the text editor, the files app, etc. As a example see: https://github.com/owncloud/files_texteditor/blob/8748910bf5f44a2687835bf4dd2be9782a8e4ce8/ajax/loadfile.php#L35

This is not only true for encryption. A app should not take it for granted that ownCloud will provide a valid file in all circumstances you should always be prepared to handle exceptions.

**Comment by schiesbn** [comment]
please follow up here: https://github.com/owncloud/files_pdfviewer/issues/70
