### ISSUE TITLE
server2server sharing ng

### ISSUE THREAD

**Issue by karlitschek** [owncloud/core#12285]
Let´s track the new requirements and the progress of the ng server2server sharing here

**Comment by DeepDiver1975** [comment]
from my pov we are done with this  - remaining pieces are to be scheduled for 8.1

moving this to 8.1

**Comment by PVince81** [comment]
- [ ] display shares in "Shared with you" section: https://github.com/owncloud/core/issues/9098
- [ ] overview page of rejected shares: #13495

**Comment by cmonteroluque** [comment]
@karlitschek unsure about proper milestone for this issue

**Comment by karlitschek** [comment]
i would suggest to move this to 9

**Comment by PVince81** [comment]
Moving to 9.2

**Comment by PVince81** [comment]
Moving to backlog for now and added to debt list. @pmaier1
