### ISSUE TITLE
Group admin can't delete files in shared folders

### ISSUE THREAD

**Issue by gmit** [owncloud/core#12292]
I have a small virtual server with oc 7.0.2, debian, apache, mysql.
I've open a group, the group admin shared a directory with the whole group.
Some sub directories contain files that was uploaded by the users of the group,
I want to delete few files / folders and there isn't delete icon next to them, 
The permission of the folders are the same.
I cant see any problem at the data/owncloud.log (attached the last 3 lines)
```
{"app":"search_lucene","message":"failed to extract meta information for \/eran\/files\/mark test: Could not open \"\/var\/www\/owncloud\/data\/eran\/files\/mark test\" (does not exist, or is not a file)","level":2,"time":"2013-09-30T11:48:44+00:00"}
{"app":"search_lucene","message":"failed to extract meta information for \/eran\/files\/\u05de\u05db\u05e8\u05d6 \u05dc\u05d1\u05d5\u05df: Could not open \"\/var\/www\/owncloud\/data\/eran\/files\/\u05de\u05db\u05e8\u05d6 \u05dc\u05d1\u05d5\u05df\" (does not exist, or is not a file)","level":2,"time":"2013-09-30T11:48:45+00:00"}
{"app":"search_lucene","message":"failed to extract meta information for \/eran\/files\/\u05d3\u05d5\u05d3\u05d5: Could not open \"\/var\/www\/owncloud\/data\/eran\/files\/\u05d3\u05d5\u05d3\u05d5\" (does not exist, or is not a file)","level":2,"time":"2013-09-30T11:48:45+00:00"}
```
in the java console there only one error
```
Failed to load resource: net::ERR_CACHE_MISS http://{server}/index.php/apps/files?dir=%2F%D7%9E%D7%91%D7%95%D7%90%D7%95%D7%AA%20%D7%A7%D7%A1%D7%A8%D7%99%D7%94%2F%D7%9E%D7%A2%D7%9C%D7%99%D7%95%D7%AA
```
![1](https://cloud.githubusercontent.com/assets/3193093/5104335/ba3e2a70-6fe9-11e4-9f39-1ce9a1b42f74.png)
![2](https://cloud.githubusercontent.com/assets/3193093/5104338/c0450eca-6fe9-11e4-9961-d3f5039462f5.png)

**Comment by DeepDiver1975** [comment]
no feedback -> close
