### ISSUE TITLE
drag and drop a file into a subfolder not possible / doesn't autoscroll

### ISSUE THREAD

**Issue by dttpy** [owncloud/core#12329]
### Expected behaviour
The file can be moved into the subfolder.

### Actual behaviour
The chosen file can not be moved because the subfolder is not reachable.

### Steps to reproduce
1. create a folder "test" and go into it
2. upload a lot of files (at least 20) and name them alphabetically
3. create a new folder "subfolder" directly
4. sort all files in "test" by name, so that the "subfolder" locates on the top of the file list
5. choose the last file in "test" and try to drag it into "subfolder"

### Server configuration
Operating system: Ubuntu 13.10

Web server: apache 2.4.6 (Ubuntu)

Database: SQLite

PHP version: 5.5.3-1ubuntu2.3

ownCloud version: 7.0.3

Updated from an older ownCloud or fresh install: from 7.0.3rc

List of activated app:standard apps of owncloud 7.0.3 and encryption

The content of config/config.php: (Without the database password and passwordsalt)
$CONFIG = array (
  'instanceid' => 'oc6d9cda6e26',

  'datadirectory' => '/var/ocdata/tingting/owncloud/data',
  'dbtype' => 'sqlite3',
  'version' => '7.0.3.4',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'maxZipInputSize' => 838860800,
  'allowZipDownload' => true,
  'loglevel' => '0',
  'trusted_domains' => 
  array (
    0 => '192.168.1.80',
  ),
);

Are you using external storage, if yes which one: no

### Client configuration
Browser: firefox 33.1.1

Operating system: ubuntu 13.10

#### ownCloud log (data/owncloud.log)

@PVince81

**Comment by PVince81** [comment]
@owncloud/designers I guess we agree that when dragging a file up or down, the list must scroll automatically ?

**Comment by jancborchardt** [comment]
@PVince81 yep.

**Comment by SergioBertolinSG** [comment]
@jancborchardt Is this problem being considered for 8.2? I find it very very annoying.

**Comment by jancborchardt** [comment]
A question for @PVince81 @MorrisJobke as it needs JS to implement this.

**Comment by MorrisJobke** [comment]
> A question for @PVince81 @MorrisJobke as it needs JS to implement this.

Not from my side and @PVince81 is on vacation :(

**Comment by jancborchardt** [comment]
Setting to 9.0 then.

**Comment by MorrisJobke** [comment]
@PVince81 @rullzer I guess we need some traction here :(

**Comment by PVince81** [comment]
Severity ? We're past feature freeze.

**Comment by MorrisJobke** [comment]
> Severity ? We're past feature freeze.

I just got a report from @CaptionF - I can't judge. It's just something that comes up more often in the past. But I'm also fine with a 9.1 fix if it is not super urgent.

**Comment by CaptionF** [comment]
the complaint is foreseeable. preferably  9.0.x, rather then 9.1

**Comment by MorrisJobke** [comment]
> the complaint is foreseeable. preferably 9.0.x, rather then 9.1

Just to keep in mind: It's an enhancement and we are in feature freeze. @MTRichards for scheduling this.

**Comment by MorrisJobke** [comment]
A potential fix is in #22576
