### ISSUE TITLE
User menu doesn’t close on opening Apps menu

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#12326]
1. Open user menu dropdown
2. Click on Apps menu dropdown

Expected: User menu closes again, Apps menu opens

What happens: The user menu stays open, the Apps menu opens as well.

The other way around it works.

cc @owncloud/designers, tagging as junior job though.

**Comment by jancborchardt** [comment]
@tomneedham this is the issue you noted as well! ;)

**Comment by jancborchardt** [comment]
This seems a pretty bad issue from a polish point of view. Depending on the amount of work this takes I would consider this as an 8.1 bugfix (similar to the [sharing menu animation](https://github.com/owncloud/core/issues/15308)), or 8.2.

@owncloud/designers what do you think?

**Comment by MorrisJobke** [comment]
Fix is in #15512

**Comment by jancborchardt** [comment]
@MorrisJobke you’re awesome! Had I realized you’re the right person for this I would have asked you earlier. ;)

**Comment by MorrisJobke** [comment]
> @MorrisJobke you’re awesome! Had I realized you’re the right person for this I would have asked you earlier. ;)

@butonic and @PVince81 showed me the "just do it" style ;)
