### ISSUE TITLE
Listing of users in group(s) fails for integer uid

### ISSUE THREAD

**Issue by a-d** [owncloud/core#12334]
Problem:
You can't list users of a group, when there is one user with an integer uid.

Error:
Accessing "index.php/settings/users" as group admin, for example, raises the following exception:
[Thu Nov 20 12:11:43 2014] [error] [client xxx.xxx.xxx.xxx] PHP Fatal error:  Call to a member function getHome() on a non-object in [...]/owncloud/settings/users.php on line 80

Steps to reproduce:
1. create group "test"
2. create user with id "123" and make it group admin
3. login as user 123
4. list "users" in the action menu

Symptom:
The script in users.php tries to load information about a user with wrong uid. ("0" instead of "123")

Cause:
https://github.com/owncloud/core/blob/master/lib/private/group.php#L285

Fix:
Instead of using "array_merge" to make a union of two user sets, just use the default '+' operator for arrays. "array_merge" removes numeric keys in the array.

\- $displayNames = array_merge($diff, $displayNames);
\+ $displayNames += $diff;

Tested and considered as solution.

**Comment by Xenopathic** [comment]
Looks like this was fixed in #11555. Re-open if I'm wrong!
