### ISSUE TITLE
Provide API endpoints for favorites/metadata/tags on files

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#12337]
#### File list

Goal is to make it possible to receive a list of favorite files and/or ids to be able to display them.
Ideal case would be to have everything go over a OCS API and use it internally as well.

Here are three alternatives about how to retrieve the list of files
1) Extend list.php

Currently the list.php ajax call already returns a list of files.
That list could be made filterable by tag using "?tag=tag1" and also make it return a "tags" attribute as part of the result set:
```json
[{
    "id": "8",
    "name": "test",
    "path": "/path/to/subdir",
    "parentId": "3",
    "date": "November 19, 2014 at 11:16:30 AM GMT+0",
    "etag": "546c7c0ed4527",
    "icon": "/owncloud/core/img/filetypes/folder.svg",
    "mimetype": "httpd/unix-directory",
    "mtime": 1416395790000,
    "permissions": 31,
    "size": "123",
    "tags": ["tag1", "_$!<Favorite>!$_"]
}]
```

This approach would need a db JOIN with the "vcategory" tables when requesting the files list, might be possible.

The tags would be included in the WebDAV response as extended attributes.

Advantage: all the information is already there, reusing existing endpoint (WebDAV + internal)
Disadantage: performance impact is unclear

2) Provide new OCS API endpoints to retrieve the information

- a) Get the list of files by tag: `GET /ocs/v1.php/apps/files/api/v1/tags/{tagname}?path=path/to/subdir&recursive=false`
- b) Get the list of favorite files: `GET /ocs/v1.php/apps/files/api/v1/favoritefiles?path=path/to/subdir&recursive=false`
- c) Get the list of favorite file ids: `GET /ocs/v1.php/apps/files/api/v1/favoritefiles?idonly=true&path=path/to/subdir?recursive=false`

After rendering the file list with "ajax/list.php" the code must also call the "favoritefiles?idonly=true&path=currentpath" endpoint to get the id of all files inside that folder that have the favorite/tag (similar to what OC.Share does at the moment).

Advantages: No JOIN needed, tags API separate from files (if that's an advantage)
Disadvantages: Cross-reference of files+tags need to be done on the JS side (and API consumer). An external API consumer will need to call WebDAV first to get the file ids, then map it with the result of the tags call.

#### Tags list
Additional APIs are required to manage the tags themselves:
a) Get all tags for the current user: `GET /ocs/v1.php/apps/files/api/v1/tags?category=files`
b) Delete a specific tag for the current user: `DELETE /ocs/v1.php/apps/files/api/v1/tags/{tagname}`

#### Assigning tags to files
Two possibilities:
1) REST style with PATCH:

If we want to do it REST style, we should use the PATCH method and patch the files metadata:
`PATCH /ocs/v1.php/apps/files/api/v1/files/path/to/file` and pass a JSON object `{tags: ['newtag1', 'newtag2']}`

Advantage: REST style
Disadvantage: the endpoint itself doesn't exist (addressing files with files) so it would be added solely for this purpose and also would not be possible to change any other file attribute using that method as it would be expected from a PATCH call (so, might be overkill). If we had a full REST API for the files list it might make sense. But we have WebDAV for that.

2) Non-REST:

Same as before but with "POST"
`POST /ocs/v1.php/apps/files/api/v1/files/path/to/file` and pass a JSON object `{tags: ['newtag']}`
or even less REST:
`POST /ocs/v1.php/apps/files/api/v1/settags?path={filePath}&tags=newtag1,newtag2`

3) "Reverse" REST

- Add tag on a given file: POST /ocs/v1.php/apps/files/api/v1/tags/{tagname}?path=file
- Delete tag from a given file: DELETE /ocs/v1.php/apps/files/api/v1/tags/{tagname}?path=file
- Delete all tags from a given file: DELETE /ocs/v1.php/apps/files/api/v1/tags?path=file

4) Webdav attributes

I heard once that it might be possible to set custom attributes over WebDAV and they would land in the `oc_properties` table. Maybe the same API/endpoint could be used for setting tags on files.

Advantages: integrated with WebDAV, no extra strange endpoing as for 1) and 2)
Disadvantages: the files app doesn't use WebDAV so it would need an additional internal endpoint that does exactly the same

**Comment by DeepDiver1975** [comment]
@PVince81 I'd like to close this ticket and continue with new ticket(s) from the remaining parts which will go into the direction of OC8.1/OC8.2. 

What's missing here now?

**Comment by PVince81** [comment]
The favorites/tags of files can be retrieved with PROPFIND and set with PROPPATCH, so I'd say this task is completed.
At some point we'll want to have an API to return the list of all known tags, but that's another feature (and as long as we don't have any UI that lists tags, it might not be needed)

**Comment by lalitesh-infoobjects** [comment]
@PVince81 We tried setting Tag using PROPPATCH

Code: https://bpaste.net/show/6bd75b2d3512

But, on retrieving with PROPFIND we didn't get any tag
Response: https://bpaste.net/show/4cc7d9e7c00a

Please suggest,
How to set the tags using webdav API and retrieve them.

**Comment by PVince81** [comment]
@lalitesh-infoobjects these are not tags but DAV properties. This is not the same thing.

The tags here are about simple tags like "Favorite", "Private", "Important" labels.

The thing in your code is a custom DAV property, but your PROPPATCH syntax looks fine.
Check the `oc_properties` table in the database to see if the DAV property was set.

Also please try again with 8.1, I tested it there a while ago and it should work. Not sure about 8.0.x.

**Comment by lalitesh-infoobjects** [comment]
@PVince81 : Updated to 8.1 rc1
Updated the sabre / guzzle clients
Checked the oc_properties table, we can see the properties created their. But DAV properties are not included in  PROPFIND response.

Response:
https://bpaste.net/show/4a9479bb99a1

**Comment by PVince81** [comment]
Please create a new ticket for this issue. Thanks.
Note that DAV properties need to be requested explicitly in the PROPFIND request. They do not appear by default.
