### ISSUE TITLE
Move files app to use WebDAV instead of custom PHP endpoints

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#12353]
Currently we have at least two endpoints to manage files:
1) WebDAV
2) Private PHP ajax endpoints in the files app

To reduce code duplication and endpoint duplication one idea would be to make the files app use the WebDAV endpoint instead, just like any other external client does (mobile, desktop, etc)

An existing JS library could be used (for example: https://github.com/sara-nl/js-webdav-client) by the files app.

We need to make sure that every custom property (ex: "icon", "isPreviewAvailabe", etc) is available on the WebDAV endpoint to keep the existing functionality working.

There might be other challenges like batch file deletion, where the JS code would need to send multiple "DELETE" calls, one for every selected file, instead of deleting a series of files in one call.

@DeepDiver1975 @icewind1991

**Comment by PVince81** [comment]
The public page can then use the "public.php/webdav" endpoint for public link file operations (https://github.com/owncloud/core/issues/6635)

**Comment by PVince81** [comment]
Note that moving to WebDAV will also have the advantage to automatically use part files internally and solve concurrency issues like https://github.com/owncloud/core/issues/13755

**Comment by PVince81** [comment]
Changing the whole file UI is a big task, so this should rather be done step by step:
- [ ] find/extend/develop JS lib for WebDAV access
- [ ] upload (regular upload for now, no chunking)
- [ ] download
  - [ ] single file
  - [ ] folder download (zip) if possible
- [ ] inject download/upload URLs for apps to use for load/save
- [ ] building the file list with PROPFIND
  - [ ] find attributes needed by the web UI and make them available, if applicable
- [ ] MKCOL
- [ ] DELETE files and folders (+batch delete challenge)
- [ ] rename/move (+batch move challenge)
- [ ] retrieving tags/favorites
- [ ] document/raise challenge: pagination/limit?
- [ ] previews
- [ ] use share info from WebDAV permissions ? (might save some server round trips)

**Comment by PVince81** [comment]
- [ ] read quota/available space value from the list PROPFIND instead of using "getstoragestats.php"

**Comment by PVince81** [comment]
@DeepDiver1975 I'm not sure whether there's time for this in 8.1, but as said above we can split it in smaller pieces.

**Comment by PVince81** [comment]
- [ ] make sure upload still works in IE8 (it might be using a workaround for uploads)

**Comment by PVince81** [comment]
Got some ideas: currently the JS code for the file list is still quite ugly and it would bring some advantages to move the file handling logic to a separate class/API anyway.
Introducing the JS Files API: https://github.com/owncloud/core/issues/13905

It could be written to be based directly off WebDAV and can be injected and used by JS apps too to access files. This way we not only gain the advantage of having the files web UI based on WebDAV, but also any app that needs access/manipulate files from JS.

So the first step would be to first design and write that new JS Files API class, which itself can use/wrap a WebDAV library.

Then the files web UI can be ported progressively to use that JS Files API.

**Comment by PVince81** [comment]
Anoter challenge:
- [ ] downloading multiple files as ZIP. Might need customized WebDAV endpoint

**Comment by PVince81** [comment]
Pretty sure QA will appreciate this, meaning less code paths to test. CC @SergioBertolinSG @jnfrmarks

**Comment by PVince81** [comment]
We shall start with the upload task: https://github.com/owncloud/core/issues/4380 and make it use PUT. This is the part that would solve most problems.

**Comment by PVince81** [comment]
This seems to bring some additional potential: if we have the file/folder's etags in the web UI (we do), we could use the "precondition" headers to make sure the situation is still as before.

**Comment by DeepDiver1975** [comment]
we basically need the etags also for change detection and reload of the file list - as discussed in https://github.com/owncloud/core/pull/14581

**Comment by PVince81** [comment]
In some cases we do not get etags: MKCOL and other operations do not return anything. So either we need to do a subsequent PROPFIND or add them as headers in the response.

**Comment by DeepDiver1975** [comment]
> In some cases we do not get etags: MKCOL and other operations do not return anything. So either we need to do a subsequent PROPFIND or add them as headers in the response.

@dragotin objections? THX

**Comment by PVince81** [comment]
I think @ogoffart said if we would return etags in MKCOL it would save the client a PROPFIND call.

**Comment by ogoffart** [comment]
The client does not really use the etags from the MKCOL. (since the etag is likely to be changed anyway when we add the files to it)

However, the File-ID that is returned is saving a PROPFIND

**Comment by PVince81** [comment]
- [ ] need X-Sendfile for the WebDAV GET endpoint (Sabre): https://github.com/fruux/sabre-dav/issues/120 (so far it was only for the web UI download.php)

**Comment by DeepDiver1975** [comment]
> need X-Sendfile for the WebDAV GET endpoint (Sabre): fruux/sabre-dav#120 (so far it was only for the web UI download.php)

I was thinking about this recently as well - I'd say we simply use X-Sendfile for webdav as soon it is available upstream.

**Comment by PVince81** [comment]
PR here: https://github.com/owncloud/core/pull/16902 with a long TODO list which we might split to different PRs

**Comment by PVince81** [comment]
- [ ] conflict dialog handling: the upload/PUT must be able to detect conflicts and show the conflict dialog

**Comment by PVince81** [comment]
- [ ] test MOVE/COPY in reverse proxy environments, because the "Destination" header is absolute, we need to be sure it points to the correct URL

**Comment by PVince81** [comment]
- [ ] public page should use webdav too

**Comment by icewind1991** [comment]
>  public page should use webdav too

How much code reuse does the public page do atm?

Once we moved files over to dab we can just reuse that code and just change the dav endpoint

**Comment by PVince81** [comment]
I hope changing the DAV endpoint should be enough. I listed it so we don't forget it.

**Comment by PVince81** [comment]
- [ ] should we do a PROPFIND after MKCOL or PUT to make sure we get all the fileinfo ? (headers do not contain everything)

**Comment by PVince81** [comment]
- [ ] move file picker to WebDAV (and remove list.php), beware of the mimetype filter!
- [ ] deprecate/remove x-sendfile ?
- [ ] share properties from sharing ?
- [ ] external storage properties ?
- [ ] getstoragestats: make it use root info ?
- [ ] leverage etag knowledge and use preconditions ?

**Comment by PVince81** [comment]
I just realized that public webdav cannot work because it would require setting the username + share password in the JS code, and I'm not sure we really want that... Ideal would be to have some kind of authorization token returned by the server (bearer?) and pass that in the request headers instead.
It seems public.php/webdav also doesn't care or receive the possible session cookie that is making the web UI work.

**Comment by PVince81** [comment]
Never mind, I found a way to make publicwebdav use the session var "public_link_authenticated" :smile: 
The good news ? Regular file actions in the public page ! (rename and delete already work)

**Comment by PVince81** [comment]
- [ ] raise ticket for later: enable all file actions in public page, show buttons on controls bar

**Comment by PVince81** [comment]
- [ ] debounce operations ? for example when deleting a lot of files, a DELETE call is made for each file (maybe the browser already does that)

**Comment by PVince81** [comment]
- [ ] parse Webdav exception and pass it back instead of just the HTTP status code. Can be useful to distinguish error messages.

**Comment by PVince81** [comment]
- [ ] future: also add convenience methods on OC.Files.Client, even if they still need ajax endpoint ? (ex: downloading multiple files)

**Comment by PVince81** [comment]
Two other regressions that have been missed when testing due to the multiple code paths: https://github.com/owncloud/core/issues/17594 and https://github.com/owncloud/core/issues/18006

**Comment by PVince81** [comment]
Discussed with @DeepDiver1975, moving to 9.0

**Comment by PVince81** [comment]
- [ ] make sure that apps from owncloud/apps and file viewers are also using the webdav endpoint (or ideally the new FilesClient API)

**Comment by MTRichards** [comment]
https://github.com/owncloud/core/issues/5939
https://github.com/DeepDiver1975/dav/issues

**Comment by DeepDiver1975** [comment]
> #5939

@MTRichards I did set the milestone to 9.0 - okay?

**Comment by MTRichards** [comment]
Yep, thank you.

**Comment by PVince81** [comment]
Not fully done, upload is still t obe done.

**Comment by PVince81** [comment]
also downloading as zip, etc. Keeping this ticket open.

**Comment by dragotin** [comment]
yeah!!! :sunny:

**Comment by PVince81** [comment]
but no upload or download as zip yet (not wanting to darken the mood)

**Comment by karlitschek** [comment]
Awesome :-) 
Gret work @PVince81 and everyone!
