### ISSUE TITLE
Uploading large files - again ("request entity too large")

### ISSUE THREAD

**Issue by Dobromir78** [owncloud/core#12351]
I realize there were similar threads but it seems to me I've read all of them, tried to solve the issue but nothing worked out.

At first everything went smoothly - I set up OC, I had no problems uploading files as large as ca. 2 GB (never tried with a larger one). And one day something went wrong and I received a message "request entity too large". Unfortunately, I can't tell whether it was connected with the update 7.0.3. I tried to get back - I even cleared the database, refilled it with the backup data, uploaded the original 7.0.2.1 files and no luck.

My php.ini looks like this:
magic_quotes_gpc = Off
magic_quotes_runtime = Off
magic_quotes_sybase = Off

file_uploads = On
post_max_size = 3064M
upload_max_filesize = 3064M
memory_limit = 3064M

My .htaccess shows identical values, but OC seems to take the values from php.ini. The check via the phpinfo() reflects the values declared in php.ini.

I tried to upload a 800 MB file and I still receive the error message. By the trial and error method I found out the script accepts files up to 512 MB.

I have no admin rights to dig in the Apache settings (hosting via provider).

Anyone any ideas? Please, advise...

**Comment by PVince81** [comment]
@Dobromir78 are you using Apache or nginx ? (because the settings might be different).

**Comment by Dobromir78** [comment]
@PVince81 To be honest - don't know which one, I have a virtual server from my ISP so I can't go deep to the settings.

@RealRancor My ISP is constantly introducing further versions of PHP but users are free to choose which one to apply to their accounts. I haven't changed this setting - as far as I remember it's 5.3.

**Comment by PVince81** [comment]
Please try again with 8.0.6 or 8.1.1.
You will need PHP >= 5.4.

If you're still having trouble with these versions, feel free to reopen.
