### ISSUE TITLE
Owncloud 7 - missing files

### ISSUE THREAD

**Issue by sprbra** [owncloud/core#12357]
Mostly folders on my owncloud have physically more files then is listed on web (Chrome, Firefox, I.E.), i'm had already TRUNCATE the oc_filescache and oc_pictures_images_cache but the issue persists. I'm also tried to verify if in android official owncloud app this issue happens too, and for my unhappy surprise this issue happens too.

**Comment by karlitschek** [comment]
ok. I agree that this should work automatically. 
Closing for now because the issue is resolved for now
