### ISSUE TITLE
directory list not refreshed (dropbox) after davfs2 problem

### ISSUE THREAD

**Issue by sfischme** [owncloud/core#12365]
We use OC 7.0.2. I have dropbox linked to my OC home. Initially I was able to see the files.

I then did some mass renaming of files on a machine with dropbox. The changes got synced to dropbox (confirmed through the web interface on dropbox.com). However, OC hasn't refreshed the file list so far.

Note that I also have OC mounted through davfs2 on a linux box, which then conveniently gives me access to dropbox through davfs. There was some problem writing to the files via davfs, so maybe that's the culprit.

**Comment by DeepDiver1975** [comment]
no feedback -> close
