### ISSUE TITLE
[7.0.3] No HTLM format when seinding an email 

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#12392]
### Expected behavior:

Send emails with HTML format when this events happens: password reset, registration, user activity.
### Actual behavior:

Sent only text format emails when this events happens: password reset, registration, user activity.

@craigpg @markviens @MTRichards

00002153

**Comment by cdamken** [comment]
Is this still an issue?

**Comment by PVince81** [comment]
very likely as I'm not aware of any change there
