### ISSUE TITLE
Hide users name from sharing text field.

### ISSUE THREAD

**Issue by csgit** [owncloud/core#12425]
Hello i have to segnalate a missing option.
I noticed that the users(non admin)have the option in calendar and contacts to choose share from users or groups. This option can expose other names on the server and I don't like that. It also lets users add a shared folder into someone else's account. I feel like this invades the privacy of my clients and was hoping there was a way to disable it.

I know that is possible to turn off the app itself but I like having the ability to share files using a public link. I want to keep the link generation but remove the users and groups sharing.

I found a reply to this on the forum, that is possible simply select 'Allow users to only share with users in their groups' in the admin panel and add a unique group name to each user.

But doing so i have to create a group for every user!

But my idea is to create groups like: "Group Football"(20 persons), "Group Rugby"(10 persons) etc. 
But i don't want they share each other and also dont' like they can see the uesers name (on the sharing namesearch) each other (privacy!)
I was wondering that disablig re-sharing resolve this but no. They can't share, but they can see other users name from sharing option in calendar and contacs.

Is non sense create 10 groups for 10 single persons.

There is an option or need to create an option? 

Thank you hope be usefull.

**Comment by PVince81** [comment]
Also there is the option to "only allow users to share within their own groups". This should be enough to help limit which users can be looked up with autocomplete.
