### ISSUE TITLE
Enabling group checkbox does not disappear when navigating between apps

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#12430]
### Steps to reproduce
1. Enable app with support for enabling for specific groups (I tested with the text editor)
2. Enable for a group (group doesn't matter)
3. Navigate to a different app that doesn't support groups (I tested with file locking)j
4. The text box for the group remains

### Expected behaviour

The group text box would not be present

### Actual behaviour

The group text box is present.

![p220](https://cloud.githubusercontent.com/assets/8480343/5190911/f06bff32-74b7-11e4-874c-ce213f3d431b.PNG)

![p221](https://cloud.githubusercontent.com/assets/8480343/5190913/f2fece78-74b7-11e4-9ca9-66bc41515579.PNG)

### Server configuration

ownCloud Enterprise Edition 7.0.3 (daily) Build:2014-11-25T04:07:01+00:00

### Browser Configuration

I tested with both chrome and firefox

**Comment by MorrisJobke** [comment]
I can't reproduce with the new apps management, as multiple apps are on the same page. The autocomplete doesn't work, but this is another issue.
