### ISSUE TITLE
linux desktop client 1.7.0 wrong credentials

### ISSUE THREAD

**Issue by romaha36** [owncloud/core#12446]
### Steps to reproduce
1. install linux desktop client 1.7.0
2. connect to owncloud server (screen 1) 
3. enter credentials (screen 2)
4. --> error message "wrong credentials"

### Expected behaviour
After step 3, a list of available folders should be shown

### Actual behaviour
error message "wrong credentials" shown and login is impossible

### Server configuration
**Operating system**: ubuntu 14.04.1 server

**Web server:** Apache 2.4.7

**Database:** MySQL

**PHP version:** 5.5.9

**ownCloud version:** (see ownCloud admin page) 7.0.3

**Updated from an older ownCloud or fresh install:** Fresh

**List of activatedActivity
Bookmarks
Calendar
Contacts
Deleted Files
Documents
External Storage Support
First run wizard
Full text search
Mail Template editor
owncloud dependencies info
PDF viewer
Pictures
Share Files
Text editor
Updater
Versions
Video viewer apps:**

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => 'oc36318ef31c',
  'passwordsalt' => '0ff683c1a3312e92651af88c648075',
  'trusted_domains' => 
  array (
    0 => '192.168.1.4',
    1 => 'mydomain.com:81',
    2 => '10.0.0.1',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://192.168.1.4/owncloud',
  'dbtype' => 'mysql',
  'version' => '7.0.3.4',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '@@@',
  'dbpassword' => ' @@@',
  'installed' => true,
);

**Are you using external storage, if yes which one:** local/smb/sftp/... 
GoogleDrive
WebDav (2x)

**Are you using encryption:** no

### Client configuration
**Browser:** firefox 33.0 + Chrome 39.0.2171.65

**Operating system:** Ubuntu 14.04

#### Web server error log
[Wed Nov 26 08:29:20.561102 2014] [mpm_prefork:notice] [pid 22647] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 configured -- resuming normal operations
[Wed Nov 26 08:29:20.561191 2014] [core:notice] [pid 22647] AH00094: Command line: '/usr/sbin/apache2'
[Wed Nov 26 08:34:00.129433 2014] [mpm_prefork:notice] [pid 22647] AH00169: caught SIGTERM, shutting down
[Wed Nov 26 08:34:01.290758 2014] [mpm_prefork:notice] [pid 22757] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 configured -- resuming normal operations
[Wed Nov 26 08:34:01.290850 2014] [core:notice] [pid 22757] AH00094: Command line: '/usr/sbin/apache2'
[Wed Nov 26 08:34:25.683750 2014] [mpm_prefork:notice] [pid 22757] AH00169: caught SIGTERM, shutting down
[Wed Nov 26 08:34:26.883891 2014] [mpm_prefork:notice] [pid 22814] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 configured -- resuming normal operations
[Wed Nov 26 08:34:26.884022 2014] [core:notice] [pid 22814] AH00094: Command line: '/usr/sbin/apache2'
[Wed Nov 26 08:50:25.077744 2014] [mpm_prefork:notice] [pid 22814] AH00171: Graceful restart requested, doing restart
[Wed Nov 26 08:50:25.217570 2014] [mpm_prefork:notice] [pid 22814] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 configured -- resuming normal operations
[Wed Nov 26 08:50:25.217612 2014] [core:notice] [pid 22814] AH00094: Command line: '/usr/sbin/apache2'
[Wed Nov 26 08:51:13.727383 2014] [mpm_prefork:notice] [pid 22814] AH00171: Graceful restart requested, doing restart
[Wed Nov 26 08:51:13.842420 2014] [mpm_prefork:notice] [pid 22814] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 configured -- resuming normal operations
[Wed Nov 26 08:51:13.842458 2014] [core:notice] [pid 22814] AH00094: Command line: '/usr/sbin/apache2'
[Wed Nov 26 08:52:16.245418 2014] [mpm_prefork:notice] [pid 22814] AH00169: caught SIGTERM, shutting down
[Wed Nov 26 08:54:40.630183 2014] [mpm_prefork:notice] [pid 2424] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 configured -- resuming normal operations
[Wed Nov 26 08:54:40.659433 2014] [core:notice] [pid 2424] AH00094: Command line: '/usr/sbin/apache2'
[Wed Nov 26 08:55:14.770950 2014] [mpm_prefork:notice] [pid 2424] AH00169: caught SIGTERM, shutting down
[Wed Nov 26 08:55:15.609042 2014] [mpm_prefork:notice] [pid 2625] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 configured -- resuming normal operations
[Wed Nov 26 08:55:15.609164 2014] [core:notice] [pid 2625] AH00094: Command line: '/usr/sbin/apache2'
[Wed Nov 26 08:56:14.241062 2014] [mpm_prefork:notice] [pid 2625] AH00169: caught SIGTERM, shutting down
[Wed Nov 26 08:56:15.374940 2014] [mpm_prefork:notice] [pid 2691] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 configured -- resuming normal operations
[Wed Nov 26 08:56:15.375060 2014] [core:notice] [pid 2691] AH00094: Command line: '/usr/sbin/apache2'
[Wed Nov 26 09:04:12.138086 2014] [mpm_prefork:notice] [pid 2691] AH00169: caught SIGTERM, shutting down
[Wed Nov 26 09:04:13.304321 2014] [mpm_prefork:notice] [pid 2897] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 configured -- resuming normal operations
[Wed Nov 26 09:04:13.304441 2014] [core:notice] [pid 2897] AH00094: Command line: '/usr/sbin/apache2'
[Wed Nov 26 09:07:11.866035 2014] [mpm_prefork:notice] [pid 2897] AH00169: caught SIGTERM, shutting down
[Wed Nov 26 09:07:13.021127 2014] [mpm_prefork:notice] [pid 2998] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 configured -- resuming normal operations
[Wed Nov 26 09:07:13.021253 2014] [core:notice] [pid 2998] AH00094: Command line: '/usr/sbin/apache2'
[Wed Nov 26 09:12:47.989483 2014] [core:notice] [pid 2998] AH00051: child pid 3005 exit signal Segmentation fault (11), possible coredump in /etc/apache2
[Wed Nov 26 09:12:47.989617 2014] [core:notice] [pid 2998] AH00051: child pid 3012 exit signal Segmentation fault (11), possible coredump in /etc/apache2
[Wed Nov 26 09:12:47.989668 2014] [mpm_prefork:notice] [pid 2998] AH00169: caught SIGTERM, shutting down
[Wed Nov 26 09:12:48.904567 2014] [mpm_prefork:notice] [pid 3264] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 configured -- resuming normal operations
[Wed Nov 26 09:12:48.904691 2014] [core:notice] [pid 3264] AH00094: Command line: '/usr/sbin/apache2'
[Wed Nov 26 09:13:46.600027 2014] [core:notice] [pid 3264] AH00051: child pid 3269 exit signal Segmentation fault (11), possible coredump in /etc/apache2
[Wed Nov 26 09:13:46.600141 2014] [mpm_prefork:notice] [pid 3264] AH00169: caught SIGTERM, shutting down
[Wed Nov 26 09:13:47.471388 2014] [mpm_prefork:notice] [pid 3338] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 configured -- resuming normal operations
[Wed Nov 26 09:13:47.471520 2014] [core:notice] [pid 3338] AH00094: Command line: '/usr/sbin/apache2'
[Wed Nov 26 09:29:03.858370 2014] [core:notice] [pid 3338] AH00051: child pid 3343 exit signal Segmentation fault (11), possible coredump in /etc/apache2
[Wed Nov 26 09:29:03.858443 2014] [core:notice] [pid 3338] AH00051: child pid 3344 exit signal Segmentation fault (11), possible coredump in /etc/apache2
[Wed Nov 26 09:29:03.858551 2014] [mpm_prefork:notice] [pid 3338] AH00169: caught SIGTERM, shutting down
[Wed Nov 26 09:29:04.788216 2014] [mpm_prefork:notice] [pid 3963] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 configured -- resuming normal operations
[Wed Nov 26 09:29:04.789318 2014] [core:notice] [pid 3963] AH00094: Command line: '/usr/sbin/apache2'
[Wed Nov 26 09:30:56.441639 2014] [mpm_prefork:notice] [pid 3963] AH00169: caught SIGTERM, shutting down
[Wed Nov 26 09:30:57.583648 2014] [mpm_prefork:notice] [pid 4072] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 configured -- resuming normal operations
[Wed Nov 26 09:30:57.583805 2014] [core:notice] [pid 4072] AH00094: Command line: '/usr/sbin/apache2'
[Wed Nov 26 09:35:39.774278 2014] [core:notice] [pid 4072] AH00051: child pid 4234 exit signal Segmentation fault (11), possible coredump in /etc/apache2
[Wed Nov 26 09:35:39.774395 2014] [mpm_prefork:notice] [pid 4072] AH00169: caught SIGTERM, shutting down
[Wed Nov 26 09:35:40.699553 2014] [mpm_prefork:notice] [pid 4390] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 configured -- resuming normal operations
[Wed Nov 26 09:35:40.699671 2014] [core:notice] [pid 4390] AH00094: Command line: '/usr/sbin/apache2'
[Wed Nov 26 09:48:09.014294 2014] [core:notice] [pid 4390] AH00051: child pid 4394 exit signal Segmentation fault (11), possible coredump in /etc/apache2
[Wed Nov 26 09:48:09.014396 2014] [mpm_prefork:notice] [pid 4390] AH00169: caught SIGTERM, shutting down
[Wed Nov 26 09:48:09.917010 2014] [mpm_prefork:notice] [pid 4688] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 configured -- resuming normal operations
[Wed Nov 26 09:48:09.917145 2014] [core:notice] [pid 4688] AH00094: Command line: '/usr/sbin/apache2'
[Wed Nov 26 10:39:19.212023 2014] [access_compat:error] [pid 4692] [client 10.0.0.1:35348] AH01797: client denied by server configuration: /var/www/owncloud/data/htaccesstest.txt

#### ownCloud log (data/owncloud.log)
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:27+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:28+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:29+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:30+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:31+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:31+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:32+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:33+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:33+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:34+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:35+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:36+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:38+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:39+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:40+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:41+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:42+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:43+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:44+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:45+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:45+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:46+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:47+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:48+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:49+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:49+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:50+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:51+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:52+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:53+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:54+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:55+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:56+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:56+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:57+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:58+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:59+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:38:59+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:39:00+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:39:01+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:39:02+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:39:03+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:39:04+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:39:04+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:39:05+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:39:06+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:39:07+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:39:08+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:39:09+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:39:09+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:39:10+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:39:11+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:39:12+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:39:13+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-11-26T09:39:13+00:00"}

#### Browser log N/A

extra info:
When trying to connect the 1.7.0 client on a Ubuntu 14.04 (desktop) client, this log is produced:

11-26 09:59:19:265 0x90362c8 !!! Mirall::ValidateDavAuthJob created for QUrl( "http://192.168.1.4/owncloud" ) querying ""
11-26 09:59:34:265 0x90362c8 Mirall::ValidateDavAuthJob(0x96ec480) Timeout
11-26 09:59:34:268 0x90362c8 void Mirall::AbstractNetworkJob::slotFinished() 5 "Operation canceled"

Connection to webinterface AND WebDav via Brower is working perfectly.
I am digging a lot and am now sure that php authentification and Apache settings are correct.

I am convinced that this is related to my rewriting rules in my .htaccess file.

<IfModule mod_fcgid.c>
<IfModule mod_setenvif.c>
<IfModule mod_headers.c>
SetEnvIfNoCase ^Authorization$ "(.+)" XAUTHORIZATION=$1
SetEnvIf Authorization "(.*)" XAUTHORIZATION=$1
RequestHeader set XAuthorization %{XAUTHORIZATION}e env=XAUTHORIZATION
</IfModule>
</IfModule>
</IfModule>
<IfModule mod_php5.c>
php_value upload_max_filesize 513M
php_value post_max_size 513M
php_value memory_limit 512M
php_value mbstring.func_overload 0
<IfModule env_module>
SetEnv htaccessWorking true
</IfModule>
</IfModule>
<IfModule mod_rewrite.c>
RewriteEngine on
RewriteRule .* - [E=REMOTE_USER:%{HTTP:Authorization},L]
# RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]
# RewriteRule .* /lib/private/connector/sabre/server.php [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]
RewriteRule ^\.well-known/host-meta /public.php?service=host-meta [QSA,L]
RewriteRule ^\.well-known/host-meta\.json /public.php?service=host-meta-json [QSA,L]
RewriteRule ^\.well-known/carddav /remote.php/carddav/ [R]
RewriteRule ^\.well-known/caldav /remote.php/caldav/ [R]
RewriteRule ^apps/calendar/caldav\.php remote.php/caldav/ [QSA,L]
RewriteRule ^apps/contacts/carddav\.php remote.php/carddav/ [QSA,L]
RewriteRule ^remote/(.*) remote.php [QSA,L]
</IfModule>
<IfModule mod_mime.c>
AddType image/svg+xml svg svgz
AddEncoding gzip svgz
</IfModule>
<IfModule dir_module>
DirectoryIndex index.php index.html
</IfModule>
AddDefaultCharset utf-8
Options -Indexes
<IfModule pagespeed_module>
ModPagespeed Off
</IfModule>

The thing I cannot understand is if I launch the client in this configuration, It will find my server. On the second screen, I enter my credentials, where I get the "Wrong credentials" error.

IF I activate between screen 1 (server address) and Screen 2 (credentials) the following line in my .htaccess, it will accept these credentials.

# RewriteRule .* /lib/private/connector/sabre/server.php [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]

But, keeping only this above rule active, will (ofcourse) break all other requests, as they are redirected to the wrong place....

Any help would be appreciated!

**Comment by t-h-e** [comment]
same problem here.

Server:
ownCloud 8.1 beta 2 (git) 
Webserver: nginx
Database: MySQL
OS: Raspbian

Client:
ownCloud client: 1.7.0
OS: Linux Mint 17.1

**Comment by DeepDiver1975** [comment]
> ownCloud client: 1.7.0

please upgrade to 1.8.3 - THX

**Comment by t-h-e** [comment]
Sry, my bad. The version in the package manager was already pretty old.

It works fine with the new version (1.8.3). Only, when choosing which folders to sync, no folder names are shown.

Thx, for the fast answer.

**Comment by DeepDiver1975** [comment]
> Thx, for the fast answer.

with pleasure
