### ISSUE TITLE
OC 7.0.2 to 7.0.3 user_ldap group searching does not work

### ISSUE THREAD

**Issue by goodkiller** [owncloud/core#12440]
In 7.0.2 user_ldap module works fine and when you want to share to LDAP user or group then it finds that you need. But in 7.0.3 user_ldap finds only primary group. It's unable to find subgroups or memberOf groups.

Here is some log:
{"reqId":"547596444695d","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => cn=firstname lastname,cn=users,dc=domain,dc=com\n)\n attr Array\n(\n    [0] => uid\n)\n limit 1 offset 0","level":0,"time":"2014-11-26T10:58:44+02:00","method":"GET","url":"\/index.php\/core\/ajax\/share.php?fetch=getShareWith&search=searchstring&itemShares%5B%5D=&itemShares%5B1%5D%5B%5D=MY+COMPANY"}
{"reqId":"547596444695d","app":"user_ldap","message":"Ready for a paged search","level":1,"time":"2014-11-26T10:58:44+02:00","method":"GET","url":"\/index.php\/core\/ajax\/share.php?fetch=getShareWith&search=searchstring&itemShares%5B%5D=&itemShares%5B1%5D%5B%5D=MY+COMPANY"}
{"reqId":"547596444695d","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => cn=firstname lastname,cn=users,dc=domain,dc=com\n)\n attr Array\n(\n    [0] => primaryGroupID\n)\n limit 1 offset 0","level":0,"time":"2014-11-26T10:58:44+02:00","method":"GET","url":"\/index.php\/core\/ajax\/share.php?fetch=getShareWith&search=searchstring&itemShares%5B%5D=&itemShares%5B1%5D%5B%5D=MY+COMPANY"}
{"reqId":"547596444695d","app":"user_ldap","message":"Ready for a paged search","level":1,"time":"2014-11-26T10:58:44+02:00","method":"GET","url":"\/index.php\/core\/ajax\/share.php?fetch=getShareWith&search=searchstring&itemShares%5B%5D=&itemShares%5B1%5D%5B%5D=MY+COMPANY"}
{"reqId":"547596444695d","app":"user_ldap","message":"Requested attribute primarygroupid not found for cn=firstname lastname,cn=users,dc=domain,dc=com","level":0,"time":"2014-11-26T10:58:44+02:00","method":"GET","url":"\/index.php\/core\/ajax\/share.php?fetch=getShareWith&search=searchstring&itemShares%5B%5D=&itemShares%5B1%5D%5B%5D=MY+COMPANY"}
{"reqId":"547596444695d","app":"user_ldap","message":"getGroups getGroups-searchstring-500-","level":0,"time":"2014-11-26T10:58:44+02:00","method":"GET","url":"\/index.php\/core\/ajax\/share.php?fetch=getShareWith&search=searchstring&itemShares%5B%5D=&itemShares%5B1%5D%5B%5D=MY+COMPANY"}
{"reqId":"547596444695d","app":"user_ldap","message":"getGroups(searchstring): read 22 at offset  (limit: 500)","level":0,"time":"2014-11-26T10:58:44+02:00","method":"GET","url":"\/index.php\/core\/ajax\/share.php?fetch=getShareWith&search=searchstring&itemShares%5B%5D=&itemShares%5B1%5D%5B%5D=MY+COMPANY"}
{"reqId":"547596444695d","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => cn=firstname lastname,cn=users,dc=domain,dc=com\n)\n attr Array\n(\n    [0] => uid\n)\n limit 1 offset 0","level":0,"time":"2014-11-26T10:58:44+02:00","method":"GET","url":"\/index.php\/core\/ajax\/share.php?fetch=getShareWith&search=searchstring&itemShares%5B%5D=&itemShares%5B1%5D%5B%5D=MY+COMPANY"}
{"reqId":"547596444695d","app":"user_ldap","message":"Ready for a paged search","level":1,"time":"2014-11-26T10:58:44+02:00","method":"GET","url":"\/index.php\/core\/ajax\/share.php?fetch=getShareWith&search=searchstring&itemShares%5B%5D=&itemShares%5B1%5D%5B%5D=MY+COMPANY"}
{"reqId":"547596444695d","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => cn=firstname lastname,cn=users,dc=domain,dc=com\n)\n attr Array\n(\n    [0] => primaryGroupID\n)\n limit 1 offset 0","level":0,"time":"2014-11-26T10:58:44+02:00","method":"GET","url":"\/index.php\/core\/ajax\/share.php?fetch=getShareWith&search=searchstring&itemShares%5B%5D=&itemShares%5B1%5D%5B%5D=MY+COMPANY"}
{"reqId":"547596444695d","app":"user_ldap","message":"Ready for a paged search","level":1,"time":"2014-11-26T10:58:44+02:00","method":"GET","url":"\/index.php\/core\/ajax\/share.php?fetch=getShareWith&search=searchstring&itemShares%5B%5D=&itemShares%5B1%5D%5B%5D=MY+COMPANY"}
{"reqId":"547596444695d","app":"user_ldap","message":"Requested attribute primarygroupid not found for cn=firstname lastname,cn=users,dc=domain,dc=com","level":0,"time":"2014-11-26T10:58:44+02:00","method":"GET","url":"\/index.php\/core\/ajax\/share.php?fetch=getShareWith&search=searchstring&itemShares%5B%5D=&itemShares%5B1%5D%5B%5D=MY+COMPANY"}

**Comment by blizzz** [comment]
Close for inactivity, if you reencounter the problem and have more info to share, please reopen.
