### ISSUE TITLE
OC 6.X to 7.0.3 Autocomplete not working when typing user/group for sharing

### ISSUE THREAD

**Issue by skeljuve** [owncloud/core#12457]
Hello.
After upgrade to 7.0.3 (stable), stop working autocomplete user/group name in field sharing. At version 6.X all was fine. Also, if I type usernam/group, I can't share/ But some users/groups apeared (may be they are caching?). How it fix?
Thanks.

**Comment by blizzz** [comment]
Since there were no updates i close it as config issue. Please reopen if you still have problems.
