### ISSUE TITLE
getting rid of oc_files_map

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#12461]
we better move the physical path column into the cache table - kind of related to https://github.com/owncloud/core/issues/12460

**Comment by PVince81** [comment]
8.1, 8.2 or backlog ? :smile:

**Comment by nickvergessen** [comment]
8.1 needs a decision on this

**Comment by karlitschek** [comment]
Yes. We should move this into the cache table directly.

**Comment by PVince81** [comment]
What to do with this ? Defer or obsolete ?

**Comment by nickvergessen** [comment]
We will do that once we remove all the other windows hacks
