### ISSUE TITLE
Internal apps should also use the file node-based public API instead of View

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#12471]
Instead of using `\OC\Files\View()` in internal apps like files, sharing, etc, we should make them use the node-based API that can be accessed with `OC::$server->getUserFolder()` (See https://github.com/owncloud/core/blob/master/lib/public/files/folder.php)

It seems the search app is already using that (CC @butonic) and I'm also using it now in the new metadata/tags app.

But first we need to discuss whether we all agree that we want to go that way as we don't want to have lots of different APIs. Then we need to document this better (I only discovered this very recently).

@icewind1991 @DeepDiver1975 @schiesbn @nickvergessen @MorrisJobke

**Comment by oparoz** [comment]
Don't forget that this is currently not possible because `OC::$server->getUserFolder()` doesn't work if the user is using a token,

**Comment by PVince81** [comment]
@icewind1991 any ideas for @oparoz's last comment ?

It might be possible to go through `getRootFolder()`

**Comment by PVince81** [comment]
A few places that could be changed to use the Node API:
- [ ] Sabre plugins
- [ ] Files app UI (but might be using WebDAV instead in #12353 which itself would go through Sabre)
- [ ] Versions ?
- [ ] Trashbin ?
- [ ] Sharing app ?

**Comment by nickvergessen** [comment]
- [ ] Activity app has an issue for it: https://github.com/owncloud/activity/issues/249
