### ISSUE TITLE
Skeleton Enhancement

### ISSUE THREAD

**Issue by CoreSolutions** [owncloud/core#12497]
It would be beneficial if you could assign skeleton folders by group. We have 3 different types of users and all 3 should start with a different set of folders & files.

Thanks for your consideration.

**Comment by butonic** [comment]
You could share the needed files and folders to the groups: individual files as read only works well and will prevent you from duplicating the file over and over by copying it.

**Comment by PVince81** [comment]
9.2 will come with a new hook that is triggered for first time login. This should make it possible to write apps that provide their own skeletons based on whichever rules they want.
