### ISSUE TITLE
Login form should be centered horizontally

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#12494]
Otherwise it looks on large displays as following:

![2014-11-28_13-56-42](https://cloud.githubusercontent.com/assets/878997/5228166/951f1406-7706-11e4-8e52-e72b7d31ded3.png)

**Comment by Volker-E** [comment]
@LukasReschke What should be the advantage of making it horizontal on widescreens?

**Comment by Xenopathic** [comment]
Got confused for a moment there. Do you mean vertical alignment (up-down direction?)

**Comment by oparoz** [comment]
I think it's fine at the top. The mouse cursor will probably come from the top.

**Comment by Xenopathic** [comment]
Likewise - I personally prefer it at the top instead of in the centre of the screen. Makes it look more 'minimalistic' somehow

**Comment by LukasReschke** [comment]
Let's close this then :)
