### ISSUE TITLE
Lazy load JS translation fallback for apps that forgot addTranslation

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#12490]
Some apps might not have added the new required `addTranslations()` PHP function to preload translations.

To avoid breaking these app's translations, the `t()` JS function needs to still use a sync ajax call to load missing translations bundle (like it did before).

CC @Raydiation as discussed

**Comment by MorrisJobke** [comment]
@karlitschek @PVince81 @DeepDiver1975 So this will cause breakage of not updated apps?!? What to do here?

**Comment by PVince81** [comment]
Not a proper breakage but they will only have English as the "translations.php" ajax call will fail.
Workaround could be to bring back a deprecated "translations.php" that still returns sync translations and remove it in a later version (ex: OC 9)

**Comment by DeepDiver1975** [comment]
I guess there is not much we can do -> close ?

**Comment by PVince81** [comment]
@Raydiation came up with an even better fix that removes the need for explicitly calling `addTranslations` here: https://github.com/owncloud/core/pull/13350

**Comment by DeepDiver1975** [comment]
> @Raydiation came up with an even better fix that removes the need for explicitly calling addTranslations here: #13350

@Raydiation 

![awsome](https://cloud.githubusercontent.com/assets/1005065/5742692/6d4f7a6e-9c14-11e4-9be7-81363f2aff11.jpeg)
