### ISSUE TITLE
7.0.3: Decryption finished unexpected: Encryption library: Decryption (symmetric) of content failed

### ISSUE THREAD

**Issue by brozkeff** [owncloud/core#12495]
### Steps to reproduce
1. enable encryption (on some 6.x version of server)
2. use the server with encryption on until upgrade to 7.0.3,have dozens of GB encrypted by a few users
3. decide to disable encryption
4. log in as user with encyrption, go to user settings,enter passord and start decrypting
5. user having a few filers only decrypted OK, user having over 10 GB of files showed (in Czech) "Nebylo možno dešifrovat soubory, zkontroluje prosím owncloud.log nebo kontaktujte svého administrátora" - translation would be "Cannot decrypt files, check owncloud.llog or contact your admin"
6. repeat the process, for the second time it wrote success after about 3 secs

### Expected behaviour
decryption would finish correctly for the first time

### Actual behaviour
decryption of files of user having dozens of GB failed somewhere in the process, seems at the very end, as repeating the decryption was "succesful" (but I did not check all the files manually yet)

### Server configuration
**Operating system**: Debian 7.7 64bit

**Web server:** Apache 2.12.22-13+deb7u3

**Database:** MariaDB 5.5.36+maria-1~wheezy

**PHP version:** 5.4.4-14+deb7u14

**ownCloud version:** (see ownCloud admin page) 7.0.3

**Updated from an older ownCloud or fresh install:** update from 7.0.2 originally 6.x originally 5.x

**List of activated apps:**
Activity
Calendar
Contacts
Deleted files
Documents
External storage support
ownCloud dependencies info
Shared files
Text editor
Updater
Versions
**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'datadirectory' => '/var/www/owncloud/data',
  'overwritewebroot' => '/owncloud',
  'dbtype' => 'mysql',
  'dbname' => 'owncloud',
  'dbuser' => 'owncloud',
  'dbpassword' => 'xxx',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'version' => '7.0.3.4',
  'installed' => true,
  'forcessl' => true,
  'loglevel' => '1',
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' =>
  array (
    0 => 'xxx.net',
  ),
  'openssl' =>
  array (
    'config' => '/etc/ssl/openssl.cnf',
  ),
);

```

**Are you using external storage, if yes which one:** None

**Are you using encryption:** Was using until now, and I disabled Encryption now

### Client configuration
**Browser:** Firefox 33.0

**Operating system:** Linux Mint 17 Cinnamon 

#### Web server error log
no errors

#### ownCloud log (data/owncloud.log)
```
{"app":"encryption library","message":"Decryption finished unexpected: Encryption library: Decryption (symmetric) of content failed","level":3,"time":"2014-11-28T11:53:20+00:00"}
```
(no other records, unfortunately I had debug logging disabled as I used owncloud in production and not for debugging)

**Comment by PVince81** [comment]
In the new encryption in 8.2, a CLI command will be provided to decrypt files. This should make it possible to prevent timeouts.
Closing in favor of https://github.com/owncloud/core/issues/16327
