### ISSUE TITLE
Edit icon on Safari

### ISSUE THREAD

**Issue by oureas** [owncloud/core#12508]
On Safari on OS X 10.9/10.10 the "Edit" icon is not centered vertically. Issue appeared with ownCloud 7 and still there with 7.0.3. On Firefox the issue is the same. On Google Chrome its correct. See screenshot for more information:
 
![screen shot 2014-11-29 at 10 51 22](https://cloud.githubusercontent.com/assets/600317/5234099/c73ec5da-77b5-11e4-965d-cbfbffc6ca3f.png)

**Comment by Sugaroverdose** [comment]
same as #11348

**Comment by MorrisJobke** [comment]
fixed with #13276 

Will be fixed in ownCloud 8
