### ISSUE TITLE
Upgrade Prob

### ISSUE THREAD

**Issue by tbelau666** [owncloud/core#12506]
I was trying an update from 7.0.2 to 7.0.3 in debians jessie. Between installation of these versions I had created some other tables within the owncloud database. The result was a not working database upgrade. The problem in my environment is that listTableNames() or listSequences() in Doctrines SchemaManager are insensitive against the owncloud table prefixes.

I will fix it because I need this fix. But whithout to be any member of any developers community. Whom can I simply send that? Say within next 36 hours...

**Comment by MorrisJobke** [comment]
This will be shipped with ownCloud 8.0
