### ISSUE TITLE
Getting rid of self string concatinated SQL statements

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#12502]
we better use query builder or move into the orm segment
- http://www.doctrine-project.org/api/dbal/2.3/class-Doctrine.DBAL.Query.QueryBuilder.html
- http://www.doctrine-project.org/projects/orm.html

**Comment by DeepDiver1975** [comment]
#13278 shows how querybuilder can be used

**Comment by PVince81** [comment]
The decision so far was to use the QueryBuilder everywhere.

**Comment by DeepDiver1975** [comment]
@pvince81 need for change or are we okay with querybuilder?

**Comment by PVince81** [comment]
Query builder was fine so far, let's keep it. Not sure how many more queries we need to adjust.

**Comment by PVince81** [comment]
We should actually rather use the entity mapper when possible.
If there is no mapper and time is short, usage of the query builder for old code is ok.
