### ISSUE TITLE
Move Photos/Videos into date structured directory

### ISSUE THREAD

**Issue by Crasha** [owncloud/core#12513]
I was thinking it'd be handy since I have a folder with a large amount of files in since my phone gallery syncs with it, to have Date structured folders which are automatically created, and place the files into them automatically. E.G, I have a photo called "IMG_20140924_163839.jpg", it'll be placed in a folder called "Wednesday 24th September" OR "24/09/2014" (UK Timestamped).

Just thought it'd be a lot easier, as well as waiting for the files to show, and it could potentially reduce server load on a folder with a large amount of files, since it'd be trying to create the thumbnails for thousands of files, when it'll only need to create a few or so, depending on how many photos or videos you take in a day in a single folder.

It'll be nice to have all the files structured instead of them all piled into a big folder.

What do you think?

**Comment by Xenopathic** [comment]
This should be implemented as an app - rulesets for moving files around on upload is out of scope for core.
