### ISSUE TITLE
Password salt changed after upgrading

### ISSUE THREAD

**Issue by MALPI** [owncloud/core#12512]
Hi,

I upgraded my owncloud installation vom 6.0.4 to 7.0.2.
I followed the migration guide and kept the data and config folder.
Actually the file config.php was obviously partly overwritten which lead to that the password salt has been overvwritten. Therefore a login to owncloud wasn't possible anymore.

I replaced it with the old salt again, and everything is fine now.

### Steps to reproduce
Didn't try to reproduce it, since my installation is working now

### Expected behaviour
When upgrading from 6.0.4 to 7.0.2 the password salt should stay the same

### Actual behaviour
When upgrading from 6.0.4 to 7.0.2 the password salt is changed, therefore a login with the
old password is not possible anymore

### Server configuration
**Operating system**:  Ubunto 14.04 LTS

**Web server:** Apache2

**Database:** SQLLite

**PHP version:** 5

**ownCloud version:** 7.0.2

**Updated from an older ownCloud or fresh install:** Update from 6.0.4

**List of activated apps:** None

**The content of config/config.php:** Can't check right now. Can update this in the evening

**Are you using external storage, if yes which one:** No

#### Web server error log
N/A
N/Aert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Have to update this later
```

#### Browser log
N/A

**Comment by PVince81** [comment]
It is very likely that you bumped into the issue @LukasReschke mentionned, which is fixed since 7.0.3.
I'll close this ticket now.

If you observe this issue again with 7.0.5, 8.0.2 or later, feel free to reopen.
