### ISSUE TITLE
Unable to share by link on some folders

### ISSUE THREAD

**Issue by elacour** [owncloud/core#12510]
I have some folders shared to me with allow re-sharing. If I try to share it by link, I get a share popup error message with just "Error". In Log files I get:

ownCloud[8023]: PHP Fatal error:  Call to a member function format() on a non-object in /.../owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Types/DateTimeType.php on line 44

Owncloud version 7.0.3 with LDAP authentication, on Debian wheezy.

**Comment by PVince81** [comment]
Are you still seeing this on 7.0.7, 8.0.5 ?

**Comment by nickvergessen** [comment]
Feel free to reopen, if so.
