### ISSUE TITLE
Update ---> 7.0.3 Problem

### ISSUE THREAD

**Issue by yourrs** [owncloud/core#12511]
Hallo,
habe beim Update auf 7.0.3 folgendes Problem:

Kann mir jmd. helfen?

MfG
yourrs
= = = =
Hello,
following problem updating to 7.0.3:

Please help me to solve this.

Kind regards
yourrs
= = = =
Updating ownCloud to version 7.0.3, this may take a while.

Wartungsmodus eingeschaltet
Datenbank-Schemenaktualisierung geprüft
An exception occurred while executing 'CREATE TABLE `oc_owncloud_20140818_183316_contacts_cards_properties_2415ba3473447` (LIKE `owncloud_20140818_183316_contacts_cards_properties`)': SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name 'oc_owncloud_20140818_183316_contacts_cards_properties_2415ba3473447'

The update was unsuccessful.Please report this issue to the ownCloud community.

ownCloud – Web-Services unter Deiner Kontrolle

**Comment by DeepDiver1975** [comment]
> What database backend is being used?

@yourrs can you please provide this information? THX

**Comment by PVince81** [comment]
Please try again with 8.0.6 or 8.1.1.

Feel free to reopen if you're still having issues and use the issue template: https://raw.github.com/owncloud/core/master/issue_template.md to provide more information. Thanks!
