### ISSUE TITLE
IIS + postgresql install issue

### ISSUE THREAD

**Issue by RokSiEu** [owncloud/core#12518]
When trying to install OC on IIS with PostgreSQL I run into problem. 

On installing I get this error:
>An exception occurred while executing 'UPDATE "oc_filecache" SET "mtime" = ?, "storage_mtime"=? WHERE "fileid" = ?': SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: ""

I went through code and found out that issue could be in method "update"
>lib\private\files\cache\cache.php line 271
```
/**
	 * update the metadata in the cache
	 *
	 * @param int $id
	 * @param array $data
	 */
	public function update($id, array $data) {
		if(isset($data['path'])) {
			// normalize path
			$data['path'] = $this->normalize($data['path']);
		}
		if(isset($data['name'])) {
			// normalize path
			$data['name'] = $this->normalize($data['name']);
		}
		list($queryParts, $params) = $this->buildParts($data);
		$params[] = $id;
		$sql = 'UPDATE `*PREFIX*filecache` SET ' . implode(' = ?, ', $queryParts) . '=? WHERE `fileid` = ?';
		\OC_DB::executeAudited($sql, $params);
	}
```

**Comment by acmelhorn** [comment]
Any progress on this issue?

**Comment by DeepDiver1975** [comment]
This has been reported many times and seems to be related to the fact that in some cases there is no mtime available on windows (don't ask me why) - this issue is basically unrelated to postgres - has been reported on mysql as well (afaik on mssql as well).

**Comment by acmelhorn** [comment]
OK, thank you for fast response.
