### ISSUE TITLE
When I log in as a user, I would like to see what groups I am a member of.

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#12529]
When I log in as a user, I would like to see what groups I am a member of.

**Comment by rullzer** [comment]
I made a quick fix https://github.com/rullzer/core/commit/606137cdf30f168a9b512495eb7e100e9b21c535

It currently just lists the groups (no ordering...). Any formatting suggestions? Or just listing them is enough?

**Comment by MorrisJobke** [comment]
@rullzer Can you please open a PR for this? Then we can continue the discussion there. THx

**Comment by rullzer** [comment]
Done: PR #13913
