### ISSUE TITLE
Remove owncloud.log from oc/data when using /mnt/ocdata directory

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#12531]
When using a remote data directory (ie /mnt/ocData/) we should either delete the owncloud.log under owncloud/data or put some type of message indicating where to find the log file.  I keep tailing the owncloud.log under the data directory and thinking that there's no data there.

**Comment by Xenopathic** [comment]
We can't delete the log file, and trying to do something smart is too much overhead. We document that the log file is by default under the data directory, so there's not much else we can do.
