### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by benedettogit** [owncloud/core#12530]
@jancborchardt Having an option to enable or disable share groups and share users in the share box. 
![cloud](https://cloud.githubusercontent.com/assets/4548792/5250743/57d86490-798f-11e4-9df0-1668f2a17761.jpg)
And then in the admin panel options to set what to show, something like Show all, top 10, customise which to show and so on, because some of you guys have 20000 users so it isn't possible to always show them all.

**Comment by Xenopathic** [comment]
@jancborchardt I think this is fixed?

**Comment by jancborchardt** [comment]
Yeah, in the app settings it can be defined which groups an app (such as sharing) is enabled for.
