### ISSUE TITLE
Public link web pages getting significantly slower load times than viewing the content of the same directory when logged in as the account of the sharer

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#12548]
- - - 
@gig13 wrote on 24 Nov 2014:
- - -

**Expected Behavior**
When viewing the content of a directory through a public share, the load time for the content should be similar to the load time as performed by the actual owner of the share as logged in to the OC web interface.

**Actual Behavior**
The load time is significantly increases for the public share. In some cases the load time is 6-7 times faster as the owner of the share.

**Steps to Reproduce**
1. Create a directory for sharing
2. Upload 100 files of 10 MB size
3. Share the directory via a public share.
4. Access the directory via the share link in a different browser not logged into that instance.

**Server Configuration**
OS - CentOS 6.5
Percona DB
OC 6.0.5
Browser: IE11, Firefox 33
No load balancer when performing tests

Relevant DB table info
115000 in oc_filecache
294 in oc_share 

- - - 
@PVince81 wrote on 27 Nov 2014:
- - - 
@gig13 thanks for having used the issue template :smile: 

One difference between the public page and regular page is that the public page needs to resolve the share token, but that should not impact the performance significantly.
The code path is only slightly different. But also from what I remember, there are some security checks to make sure that the token's user is even allowed to read these files with some kind of reverse lookup.

CC @schiesbn @icewind1991 

- - -
@icewind1991  wrote on 27 Nov 2014:
- - - 
Is there the same performance issue when viewing non-public shares?

- - - 
@LukasReschke wrote on 28 Nov 2014:
- - - 
Mhm. I'd guess this is related to the amount of SQL queries (due to lazy loading with JS?)? At least when comparing master to 6 I can see a massive difference:

------

Master:
![screen shot 2014-11-28 at 12 40 41](https://cloud.githubusercontent.com/assets/878997/5227456/ce1a0d5c-76fb-11e4-8823-49a388203ffe.png)
![screen shot 2014-11-28 at 12 50 47](https://cloud.githubusercontent.com/assets/878997/5227540/36f6189c-76fd-11e4-89a4-0f1c5f2289a9.png)

------

Stable6 (the queries are also not that high when viewing as logged-in user):
 
![screen shot 2014-11-28 at 12 40 36](https://cloud.githubusercontent.com/assets/878997/5227457/ce2008ec-76fb-11e4-81b1-dcbca27f0c15.png)

-----

Any chance to get XHProf installed on the system? That would allow to get nice callgraphs which functions took how long etc…

**Comment by MorrisJobke** [comment]
cc'ing the performance gurur @LukasReschke Maybe give the blackfire.io a try ;) I will also set it up here

**Comment by PVince81** [comment]
@gig13 is this still an issue with 8.1.3 ?

**Comment by gig13** [comment]
No, you can close this out.
