### ISSUE TITLE
Some files being constantly synced between server and client (5 minute loop)

### ISSUE THREAD

**Issue by GnaXi** [owncloud/core#12550]
### Steps to reproduce
1. Sync World of Warcraft folder /WTF/Account between owncloud client and server
2. Start the game
3. Exit the game

### Expected behaviour
Files being synced once, if any change was made

### Actual behaviour
Files are constantly being downloaded and uploaded (5 minute loop)
![sync activity](https://cloud.githubusercontent.com/assets/1616448/5264347/4acd02fa-7a3a-11e4-8bd0-fd07aa830f72.png)

### Server configuration
**Operating system**:
Debian 7

**Web server:**
Apache version 2.2.22

**Database:**
MySQL

**PHP version:**
PHP 5.4.35-0+deb7u2

**ownCloud version:** (see ownCloud admin page)
7.0.3

**Updated from an older ownCloud or fresh install:**
7.0.2

**List of activated apps:**
Activity, Bookmarks, Calendar, Contacts, Deleted files, Documents	, First Run Wizard, Full Text Search, Mail Template Editor, PDF Viewer, Pictures, Share Files, Text Editor, Updater, Versions, Video Viewer, Chat

**The content of config/config.php:**

https://note.gnaxi.dk/?3bdbc9c1f3927813#PjxS5ffl5Wgr+mLncwfnm1VZh1kFtt6oHsFMveaRoAs=

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

### Client configuration
**Browser:**
Chrome

**Operating system:**
Windows 8, 64-bit

#### Web server error log
No errors related

#### ownCloud log (data/owncloud.log)
No logs related

#### Browser log
Not browser related

On a sidenote I can include that closing down the ownCloud application on my PC and running it again "solves the issue" until I reproduce it by starting and exiting the game.
Worst part is probably that nothing is showing up in the logs about it.

**Comment by jancborchardt** [comment]
@GnaXi can I ask you to open issues with the desktop client in that repository: https://github.com/owncloud/client/issues

(That’s also the reason why no one answered so far. Sorry about that!)
