### ISSUE TITLE
Server to server sharing / webdav auth inconsistency

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#12585]
### Steps
1. Prepare an instance OC2 but make sure to NOT setup .htaccess properly (which is normally required for certain auth types)
2. Setup OC1 another frontend instance
3. Login in OC2
4. Create a share "linkshare" without password
5. Create another share "linksharepw" with password
6. Mount "linkshare" in OC1 using server to server sharing
7. Mount "linksharepw" in OC1 using server to server sharing
8. Mount OC2 in OC1 using WebDAV ext storage
### Expected result

6, 7, 8 all work.
### Actual result

6, 8 work but not 7
### Versions

OC1 was 7.0.3
OC2 was 7.0.3
### Explanation
- 6 on the command line: `curl -X PROPFIND -D - http://d64aa9eb101889511351975471e31d2f@domain.tld/owncloud/public.php/webdav/`

When only a user name is given, curl will somehow decide to add a header `WWW-Authenticate: Basic realm="ownCloud"` which will trigger another auth logic from SabreDAV which expects a "Authorization" header, which only works when `.htaccess` is configured properly.
- 7 on the command line: `curl -X PROPFIND -D - http://d64aa9eb101889511351975471e31d2f:test@domain.tld/owncloud/public.php/webdav/`

In this case no extra realm header, authentication always works.
- 8 on the command line: `curl -X PROPFIND -D - http://user:password@domain.tld/owncloud/remote.php/webdav/`

Same as 7, the fact that both user and password are there doesn't trigger the realm header.

Now where it gets interesting is that if you have a share that does **not** expect a password, you can do this: `curl -X PROPFIND -D - http://d64aa9eb101889511351975471e31d2f:dummypassword@domain.tld/owncloud/public.php/webdav/`.

Passing a dummy password will not trigger the realm header, but also the target server does not care about the password since it is not expecting one.

So, possible fixes:
1) Pass a dummy password to the Sabre client when no password was set. A bit hacky but would do.
OR
2) Investigate CURL (and SabreClient) and find out how to make it use the correct auth type even when only a user name is given.

@icewind1991 @LukasReschke

**Comment by LukasReschke** [comment]
Ref https://github.com/owncloud/core/issues/13398

**Comment by PVince81** [comment]
Likely obsolete. And if not, it's more tech debt but doesn't hurt.
