### ISSUE TITLE
[User Management] Pre-Defined Filters (in addition to what is already there)

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#12593]
As an admin, I want to have pre-set filters for standard users and groups. These would include:
- External Users – shows all users that are using LDAP / AD / Shibboleth, or some sort of external user authentication
- Internal Users – shows all users that are authenticated only by the internal ownCloud auth mechanisms
- Not Grouped – Shows all users that are not assigned to a group (in the case a group is deleted, or they are not part of a group, this is possible)
- Disabled –  shows all users that have been disabled in the system (This is for all users, not just local users. This should refer to users that are enabled or disabled (as discussed in the LDAP cleanup app, there is a state for “disabled” prior to deletion of a user. Want to use that here too). A user that is disabled in ownCloud should not be able to log in, although they might very well have credentials that work with the LDAP / AD backend.)

**Acceptance Criteria:**
These pre-defined filters would be shown in the left sidebar, and are only shown if there are actually users in it that meet the criteria. Disabled users in a group are always shown at the very bottom of the list and grayed out.

**Remarks by Engineering**:
- Listing external users requires to store them somewhere into the DB when they log-in the first time.
- Disabled users depends upon https://github.com/owncloud/core/issues/12601

**Comment by MorrisJobke** [comment]
@LukasReschke @karlitschek @DeepDiver1975 What to do with this? 8.1?

**Comment by LukasReschke** [comment]
Yes. - Actually the REST backend is supporting filtering for a backend type and shows the type. What is missing are the changes for the GUI.

Regarding that "user in no group" feature - honestly no idea how we can best gather that information without performance loss. - No DB guru here.

**Comment by MorrisJobke** [comment]
GUI changes are a feature -> so we move this to 8.1

**Comment by karlitschek** [comment]
agreed
