### ISSUE TITLE
[master] Dropping PHP 5.3 support

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#12606]
Let's make a checklist here of the many workarounds that were needed for PHP 5.3.

**Comment by MorrisJobke** [comment]
Further effort in this area should be done for 8.1 -> moving this ticket there

**Comment by DeepDiver1975** [comment]
> Further effort in this area should be done for 8.1 -> moving this ticket there

do we still miss anything? - We better close this one or have an explicit list of things to do

**Comment by MorrisJobke** [comment]
Then I vote for the close. I have nothing special in mind. Maybe we find something while working on a feature/bug fix and then we can simply include it there (in the same way as how we proceed with code style stuff)
