### ISSUE TITLE
[User Management] User quota usage

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#12602]
As an admin, I want to be able to easily and quickly see the current quota usage of all of the users on the system.

**Acceptance Criteria:**
This should be integrated in the user management panel. This displays the % of used quota next to the quota drop down for each user in the table. The option is set in the settings panel on the bottom left (the gear). When the option is selected, a new column appears with this info displayed

**Comment by MorrisJobke** [comment]
Postponed to 8.1

**Comment by LukasReschke** [comment]
I'd love to have this @icewind1991 is there a somewhat fast API now so I can take a look at some point at this? :-)

**Comment by icewind1991** [comment]
Not atm, there are plans to add a table with all mount points for users which will allow this to be done fast

**Comment by mbardelmeijer** [comment]
:+1:

**Comment by michaelstingl** [comment]
@MTRichards When can we get this?

00004291

**Comment by MTRichards** [comment]
I will evaluate it in the context of 9.1.

**Comment by MorrisJobke** [comment]
@bboule This is still an unsolved issue -> reopen and removing the blue label.

**Comment by PVince81** [comment]
> Not atm, there are plans to add a table with all mount points for users which will allow this to be done fast

Ref: https://github.com/owncloud/core/issues/15166

**Comment by PVince81** [comment]
Feature didn't make it into 9.1, also wasn't on the plan.
Moving to 9.2.

CC @DeepDiver1975 @dragotin

**Comment by PVince81** [comment]
Closing in favor of older ticket, I'll move the labels there: https://github.com/owncloud/core/issues/1344
