### ISSUE TITLE
error with share dropDown

### ISSUE THREAD

**Issue by dttpy** [owncloud/core#12626]
### Steps to reproduce
1. create a file or folder
2. click "share", and see the share dropDown
3. click one item of sidebars on the left side like "share with you" or "share with others" before giving the user or group name, which is going to get this shared file/folder
4. click "All files" and go back to the file list
5. click "share" again

### Expected behaviour
The share dropDown can still be opened and all the operations of sharing can be done 

### Actual behaviour
share dropDown of all files or folders can not be opened, and it is no more possible to share until refreshing the page or clicking the "cloud"

### Server configuration
Operating system: Ubuntu 13.10

Web server: apache 2.4.6 (Ubuntu)

Database: SQLite

PHP version: 5.5.3-1ubuntu2.3

ownCloud version: 7.0.3 & master

Updated from an older ownCloud or fresh install: owncloud 7.0.3rc

List of activated app:standard apps of owncloud and encryption

The content of config/config.php: (Without the database password and passwordsalt)
$CONFIG = array (
  'instanceid' => 'oc6d9cda6e26',

  'datadirectory' => '/var/ocdata/***/owncloud/data',
  'dbtype' => 'sqlite3',
  'version' => '7.0.3.4',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'maxZipInputSize' => 838860800,
  'allowZipDownload' => true,
  'loglevel' => '0',
  'trusted_domains' => 
  array (
    0 => '192.168.1.80',
  ),
);

Are you using external storage, if yes which one: no

### Client configuration
Browser: firefox 34.0.5, chromium Version 39.0.2171.71

Operating system: ubuntu 13.10

**Comment by PVince81** [comment]
Will be obsoleted by having the share dialog in the sidebar: https://github.com/owncloud/core/issues/17665
