### ISSUE TITLE
asked by browser to save password while creating a new user

### ISSUE THREAD

**Issue by dttpy** [owncloud/core#12628]
***firefox 34.0.5***
### Steps to reproduce
1. log in with admin
2. save the password of admin
3. go to the user management page to create a new user
4. give the user name, password, group(optional)
5. click create

### Expected behaviour
Just a new user is created 

### Actual behaviour
A new user is created and firefox asks, whether to save the password or not.

The same thing is also tested with chromium, but they have different behaviours.

***Chromium Version 39.0.2171.71***
### Steps to reproduce
1. log in with admin
2. save the password of admin
3. go to the user management page to create a new user

### Expected behaviour
the input field of user and password is blank 

### Actual behaviour
As the password is saved by chromium, the input field of user and password is filled with admin and its password. But it is possible to set a new user name, and after typing an alphabet, the password field turns to blank.
If the test is continued, after the step 5, chromium will not ask to save the password.
The interesting thing is: if the password of admin is not saved at the beginning of this test, but chromium has another saved user and password, this user name and password will be showed on the user and pasword input field, as the user management page is loaded.

### Server configuration
Operating system: Ubuntu 13.10

Web server: apache 2.4.6 (Ubuntu)

Database: SQLite

PHP version: 5.5.3-1ubuntu2.3

ownCloud version: 7.0.3 & master

Updated from an older ownCloud or fresh install: owncloud 7.0.3rc

List of activated app:standard apps of owncloud and encryption

The content of config/config.php: (Without the database password and passwordsalt)
$CONFIG = array (
  'instanceid' => 'oc6d9cda6e26',

  'datadirectory' => '/var/ocdata/***/owncloud/data',
  'dbtype' => 'sqlite3',
  'version' => '7.0.3.4',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'maxZipInputSize' => 838860800,
  'allowZipDownload' => true,
  'loglevel' => '0',
  'trusted_domains' => 
  array (
    0 => '192.168.1.80',
  ),
);

Are you using external storage, if yes which one: no

### Client configuration
Browser: firefox 34.0.5 vs. Chromium Version 39.0.2171.71

Operating system: ubuntu 13.10

**Comment by MorrisJobke** [comment]
This seems to be ignored by todays browsers: https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

> Even without a master password, in-browser password management is generally seen as a net gain for security. Since users don't have to remember passwords that the browser stores for them, they are able to choose stronger passwords than they would otherwise.
>
> For this reason, many modern browsers do not support autocomplete="off" for login fields.
> 
> * if a site sets autocomplete="off" for a form, and the form includes username and password input fields, then the browser will still offer to remember this login, and if the user agrees, the browser will autofill those fields the next time the user visits this page.
> * if a site sets autocomplete="off" for username and password input fields, then the browser will still offer to remember this login, and if the user agrees, the browser will autofill those fields the next time the user visits this page.

Not much we can do here -> closing
