### ISSUE TITLE
Config setting to allow folder or file sharing only

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#12634]
@MTRichards @schiesbn

**Comment by PVince81** [comment]
Oh...

That should probably be done on the ShareManager level.

CC @rullzer @schiesbn

**Comment by rullzer** [comment]
This should not be that hard to do on the sharemanager level indeed. I do prefer to tackle it after most of the stuff has been migrated tough.

Assigning to myself so I don't forget.

**Comment by PVince81** [comment]
@DeepDiver1975 don't we have enough config settings already ? :wink:
