### ISSUE TITLE
Progressbar at 100% immediately

### ISSUE THREAD

**Issue by papillon6** [owncloud/core#12630]
### Steps to reproduce
1. Login at http://demo.owncloud.org/
2. Upload a new file

### Expected behaviour
The progressbar on top should visualize the upload-progress (e.g. when uploading a large file) by growing from left to right.

### Actual behaviour
Progress 'jumps' from 0% to 100% immediately. File is uploaded properly though, but it's very confusing when upload lasts several minutes and nothing happens at all...

### Server configuration
See: http://demo.owncloud.org/
Tested with several PHP-Versions 5.3-latest, 5.4-latest, 5.5-latest with different php.ini-configurations.

**Are you using encryption:** no

### Client configuration
**Browser:** Firefox 33.1, Chrome 39.0.2171.71  and InternetExplorer 10

**Operating system:**
Windows 8.1

#### Browser log
Nothing suspicious.

**Comment by nickvergessen** [comment]
Can not reproduce either.
If this still happens, feel free to reopen
