### ISSUE TITLE
Rendering of large group names get garbled when selected

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#12649]
### Steps to reproduce

1. Install 7.0.4 RC2
2. Create a group with at least 26 characters
3. Add a user to the group
4. Select the group

### Expected behaviour

The rendering does not get garbled

### Actual behaviour

The rendering gets garbled.

![p233](https://cloud.githubusercontent.com/assets/8480343/5321581/95f9883c-7c8a-11e4-9856-b4c64e47245b.PNG)

### Server configuration

Ubuntu 14.04
PHP 5.5.9
ownCloud Enterprise Edition 7.0.4 RC2 (testing)

### Browser Configuration

Chrome

**Comment by jancborchardt** [comment]
Fix at https://github.com/owncloud/core/pull/15118, please review.
