### ISSUE TITLE
Add basic syntax checking to LDAP wizard

### ISSUE THREAD

**Issue by craigpg** [owncloud/core#12640]
In cases where the LDAP filters are edited directly and not created via the wizard, it would be helpful to do some basic syntax checking and provide the user with direct feedback that the filter is well-formed.

Minimally, it should simply make sure that the parens are balanced.

However, we should not attempt to validate the filter for correctness since that can be done with "Test Filter".

**Comment by PVince81** [comment]
@butonic reopen in user_ldap repo if there is still interest for this
