### ISSUE TITLE
OC7 - Duplicated folders after rename

### ISSUE THREAD

**Issue by christianrj** [owncloud/core#12659]
### Steps to reproduce
1. Setup two user accounts (user1 and user2). Configure them in two different computers (or same computer with a VM);
2. Share a folder from user1 to user 2 (for example: "TEST"). Wait for the sync to complete;
3. Now, PAUSE the sync in both computers (do not close the clients, just pause the sync);
4. Rename folder TEST to TEST2 for user1 (on computer);
5. Rename folder TEST to TEST3 for user2 (again on computer);
6. Restart sync for user1 then immediately for user2 too;
7. Wait for the sync to complete;
8. You now have TWO folders with the same exact content instead of just one;

* This was tested using Mac Client for user1 and Windows client for user2.

--------------------

### Expected behaviour
The sync must complete and just one folder must remains

### Actual behaviour
A duplicate of the renamed folder is created

### Server configuration
**Operating system**: CentOS 6.6 x64

**Web server:** Apache 2.2.27

**Database:** MySQL 5.5.40

**PHP version:** 5.5.19

**ownCloud version:** 7.0.3

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**

**The content of config/config.php:**

```
  'instanceid' => 'R E M O V E D',
  'passwordsalt' => 'R E M O V E D',
  'trusted_domains' => 
  array (
    0 => 'R E M O V E D',
  ),
  'datadirectory' => '/oc/data',
  'overwrite.cli.url' => 'R E M O V E D',
  'dbtype' => 'mysql',
  'version' => '7.0.3.4',
  'dbname' => 'owncloud7',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'R E M O V E D',
  'dbpassword' => 'R E M O V E D',
  'installed' => true,
  'share_folder' => '/Shared',
```

**Are you using external storage, if yes which one:** local hdd.

**Are you using encryption:** no

### Client configuration
**Browser:** Chrorme 39

**Operating system:** Windows 8.1 PRO x64

#### Web server error log
```
no relevant logs to show
```

#### ownCloud log (data/owncloud.log)
```
{"app":"PHP","message":"Undefined index: mime at \/var\/www\/html\/owncloud\/apps\/files\/ajax\/mimeicon.php#4","level":3,"time":"2014-11-21T12:36:55+00:00"}
{"app":"PHP","message":"Undefined index: mime at \/var\/www\/html\/owncloud\/apps\/files\/ajax\/mimeicon.php#4","level":3,"time":"2014-11-21T12:38:30+00:00"}
{"app":"PHP","message":"Undefined index: mime at \/var\/www\/html\/owncloud\/apps\/files\/ajax\/mimeicon.php#4","level":3,"time":"2014-11-21T12:39:05+00:00"}
```

#### Browser log
```
No relevant logs to show
```

**Comment by PVince81** [comment]
Could be related to: https://github.com/owncloud/core/issues/13391 where the file cache update isn't fast enough.

**Comment by christianrj** [comment]
I think this is maybe related with #12661. Hoping with a fix soon.

**Comment by PVince81** [comment]
This shouldn't happen any more in 8.2 thanks to transactional file locking which prevents such concurrency issues.
