### ISSUE TITLE
Upload-only feature

### ISSUE THREAD

**Issue by vgezer** [owncloud/core#12658]
It has been requested in [forums](http://forum.owncloud.org/viewtopic.php?f=29&t=25067) and I also was thinking a lot about this before.

Some universities allow students to upload their homeworks to Moodle. In that system, students can only upload, but cannot download/see other files. It would be nice to add a sharing option to Folders such that allowed users will only be able to upload, but cannot download/view/modify the existing content to prevent cheating for example :)

**Comment by lasseew** [comment]
I would also like to see this feature soon.
Typical use would also be to let the attendees upload photos at an event/venue.
For this use it is inconvenient to have an app. Whereas a link (and QR-code) makes it rather easy for all to make fast uploads.

**Comment by RealRancor** [comment]
Related: https://github.com/owncloud/core/issues/7747 and https://doc.owncloud.org/server/8.0/admin_manual/enterprise_files_drop/index.html

**Comment by jancborchardt** [comment]
This is actually a duplicae of issue #7747 which @RealRancor mentioned, closing hence. Let’s continue there.
