### ISSUE TITLE
Remote Share (add to your owncloud) stops working after syncing content

### ISSUE THREAD

**Issue by StefanSchaub** [owncloud/core#12662]
Hello there,
I already posted to the forums (http://forum.owncloud.org/viewtopic.php?f=29&t=25064&p=74215#p74215). Did a clean install again and can reproduce it. 
Thanks!

### Steps to reproduce
1. clean install of oC1
2. clean install of oC2
3. public share on oC2 (password protected)
4. logout & access public link via password
5. use "add to your owncloud" to connect with oC1
6. sync data into the public share on oC2

### Expected behaviour
I can view & sync the content of the public share on oC2 in my oC1 account

### Actual behaviour
Works with a few folders & files in oC2. After some minutes I can't access the folder any more. It shows the "loading" icon followed by an "unknown error" after some time.
The windows sync client can't sync the folder any more nore list the directory in the settings.

It feels like oC1 trys a "remote indexing" of the whole directroy content and runs into a timeout.

### Server configuration
**Operating system**:
oC1: Bitname 7.0.2 updated to 7.0.3 (Ubuntu 14.04 x86_64)
oC2: Synology DSM 5.1 Kernel 3.1.40 (synology_cedarview_713+ x86_64)

**Web server:**
oC1: apache 2 Version: 2.4.7-1ubuntu4.1
oC2: Apache/2.2.29

**Database:**
oC1: mysql 5.5
oC2: mariadb 5.5.39-0028

**PHP version:**
oC1: 5.4.32
oC2: 5.5.16

**ownCloud version:** (see ownCloud admin page)
7.0.3

**Updated from an older ownCloud or fresh install:**
oC1: from 7.0.2
oC2: clean install

**List of activated apps:**
both default installation

**The content of config/config.php:**
oC1:
<?php
$CONFIG = array (
  'instanceid' => 'ocfdexxxxxxx',
  'passwordsalt' => 'removed',
  'trusted_domains' =>
  array (
    0 => 'x.y.z',
    1 => '1.2.3.4',
  ),
  'datadirectory' => '/opt/bitnami/apps/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.3.4',
  'dbname' => 'bitnami_owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'bn_owncloud',
  'dbpassword' => 'removed',
  'installed' => true,
  'forcessl' => false,
  'mail_from_address' => 'xxx',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'a.s.d',
  'loglevel' => '1',
  'theme' => '',
  'maintenance' => false,
);

oC2:
<?php
$CONFIG = array (
  'instanceid' => 'oc96fxxxxxxx',
  'passwordsalt' => 'removed',
  'trusted_domains' =>
  array (
    0 => 'a.b.c',
  ),
  'datadirectory' => '/volume1/web/data',
  'overwrite.cli.url' => 'https://a.b.c',
  'dbtype' => 'mysql',
  'version' => '7.0.3.4',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin',
  'dbpassword' => 'removed',
  'installed' => true,
);

**Are you using external storage, if yes which one:**
No - local disks

**Are you using encryption:** yes/no
No

### Client configuration 
tested on some machines
**Browser:**
Chrome / Firefox / IE

**Operating system:**
Win 8 / Server 2003

### Logs

owncloud.log @ Oc2:
{"app":"PHP","message":"Undefined index: permissions at \/volume1\/web\/apps\/files_sharing\/lib\/readonlycache.php#16","level":3,"time":"2014-12-06T16:27:17+00:00"}
is beeing logged every second

all other logs are clean.

**Comment by PVince81** [comment]
@StefanSchaub did it work ? :smile:

**Comment by PVince81** [comment]
Please try again with 8.1.3 and reopen if you still see this issue.
