### ISSUE TITLE
ownCloud unable to rename of delete files and directories with illegal characters

### ISSUE THREAD

**Issue by skjelten** [owncloud/core#12667]
Hi,

ownCloud music app refused to sync properly. After some investigation I found out the reason for this was that some music files had illegal characters in the filename. By browsing the filesystem I could see that bash was displaying the characters with a question mark, e.g.: "Runnin? Blue.ogg". The ownCloud  web interface (Files) only shows the first part of the filename, e.g. "Runnin". I am unable to rename, edit or delete that filename. Same thing when trying to do it on dolphin via webdav.
I tried to rename the folder through bash. That made owncloud automatically find the new file - but the old broken file also persists. There seems to be some trouble for ownCloud to delete the file entry form it's database. My wild guess is that the internal SQL query that ownCloud does to update deleted files is unable to do so due to a bug in the SQL sentence generation.

By renaming all the files (and directories) with illegal characters in them through bash directly on the filesystem I am able to make ownCloud access all my files, but I also now have a number of "virtual files" that have the old short name (such as "Runnin"). ownCloud only gives me an error message if I try to read, rename or delete these files. The exact error message depends on the tool I use, but with:
Web client (Files) I get: Could not rename file. Runnin could not be renamed as it has been deleted
Dolphin via webdav: An unexpected error (404) occurred while attempting to delete the specified file or folder.

I believe this is a serious bug and that ownCloud should always be able handle all filenames - even though with a "strange" character. Note: I have removed the music app and verified that the music app has no impact on this issue.

**Comment by skjelten** [comment]
Just to add a bit more information:

1: Upgrading to owncloud 8.0 did not fix the problem where I am unable to delete existing files with non-ASCII characters.

2: I have set my PHP configuration to UTF-8, but it makes no difference. New files with non-ASCII filenames are neither possible to open nor delete.

3: Running "occ files:scan --all" does not fix the problem

4: When trying to open a file with non-ASCII character I now get the following error message in the log file:
{"reqId":"a491cf05a1234055d8dd938d93aad91c","remoteAddr":"10.0.0.3","app":"PHP","message":"fopen(\/PATH_TO_OWNCLOUD\/files\/Musikk\/U2\/1997 Pop\/broken\/discoth): failed to open stream: No such file or directory at \/var\/www\/ssl\/owncloud\/lib\/private\/files\/storage\/local.php#216","level":3,"time":"2015-02-21T01:04:26+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2FMusikk%2FU2%2F1997%20Pop%2Fbroken&files=discoth"}
(note: I masked the path to my owncloud installation)

5: A work-around seems to be to delete the entire directory where the file with non-ASCII characters is stored. This way the file is finally gone.

**Comment by PVince81** [comment]
Did you check whether your database table collation is set to utf8_bin ?

Are you still seeing this issue with recent versions like 8.0.5 or 8.1 ?

**Comment by PVince81** [comment]
Please double check your database collation.
