### ISSUE TITLE
S3 external storage --- Could not resolve host

### ISSUE THREAD

**Issue by dipeit** [owncloud/core#12666]
I am trying to use swift3 the s3 compatible middleware for swift (because swift v1 auth has for some reason been deprecated and I do nothave keystone). swift3 works fine for other applications but the owncloud module seems to do odd things (the bucket exists)

                    "key": "myuser",
                    "secret": "mysecret",
                    "bucket": "owncloud",
                    "hostname": "server.domain.org",
                    "port": "443",
                    "region": "",
                    "use_ssl": "true",
                    "use_path_style": "true"

I also tried  "use_path_style": "false" but same result 

 {"app":"PHP","message":"Cannot modify header information - headers already sent at \/var\/www\/owncloud\/lib\/private\/response.php#83","level":3,"time":"2014-12-06T07:11:20+00:00"}
 {"app":"files_external","message":"Guzzle\\Http\\Exception\\CurlException: [curl] 6: Could not resolve host: owncloud.server.domain.org [url] https:\/\/owncloud.server.domain.org","level":4,"time":"2014-12-06T07:11:56+00:00"}
 {"app":"files_external","message":"Guzzle\\Http\\Exception\\CurlException: [curl] 3: <url> malformed [url] \/tokens","level":4,"time":"2014-12-06T07:23:13+00:00"}
 {"app":"files_external","message":"Guzzle\\Http\\Exception\\CurlException: [curl] 3: <url> malformed [url] \/tokens","level":4,"time":"2014-12-06T07:23:17+00:00"}

**Comment by Xenopathic** [comment]
@dipeit Are you still seeing this issue?

**Comment by PVince81** [comment]
Any more luck with 8.1.3 ?
