### ISSUE TITLE
OC7 - Deleted folder recreated after rename

### ISSUE THREAD

**Issue by christianrj** [owncloud/core#12661]
### Steps to reproduce
1. Setup two user accounts (user1 and user2). Configure them in two different computers (or same computer with a VM);
2. Share a folder from user1 to user 2 (for example: "TEST"). Wait for the sync to complete;
3. Create a folder inside TEST (for example: "FOLDER1"). Wait for the sync to complete;
4. Now, PAUSE the sync in both computers (do not close the clients, just pause the sync);
5. Rename folder TEST to TEST1 for user1 (on computer);
6. Rename folder TEST to TEST1 for user2 (again on computer);
7. DELETE folder FOLDER1 for user2 (on computer);
8. Restart sync for user2 and wait for the sync to complete;
9. Restart sync for user1 and wait for the sync to complete;
10. Now, folder FOLDER1 (witch was deleted on user2, has been recreated on both computers and in the cloud)

* This was tested using Mac Client for user1 and Windows client for user2.

--------------------

### Expected behaviour
The sync must complete and the deleted folder must not be recreated

### Actual behaviour
The deleted folder is recreated

### Server configuration
**Operating system**: CentOS 6.6 x64

**Web server:** Apache 2.2.27

**Database:** MySQL 5.5.40

**PHP version:** 5.5.19

**ownCloud version:** 7.0.3

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**

**The content of config/config.php:**

```
  'instanceid' => 'R E M O V E D',
  'passwordsalt' => 'R E M O V E D',
  'trusted_domains' => 
  array (
    0 => 'R E M O V E D',
  ),
  'datadirectory' => '/oc/data',
  'overwrite.cli.url' => 'R E M O V E D',
  'dbtype' => 'mysql',
  'version' => '7.0.3.4',
  'dbname' => 'owncloud7',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'R E M O V E D',
  'dbpassword' => 'R E M O V E D',
  'installed' => true,
  'share_folder' => '/Shared',
```

**Are you using external storage, if yes which one:** local hdd.

**Are you using encryption:** no

### Client configuration
**Browser:** Chrorme 39

**Operating system:** Windows 8.1 PRO x64

#### Web server error log
```
no relevant logs to show
```

#### ownCloud log (data/owncloud.log)
```
{"app":"PHP","message":"Undefined index: mime at \/var\/www\/html\/owncloud\/apps\/files\/ajax\/mimeicon.php#4","level":3,"time":"2014-11-21T12:36:55+00:00"}
{"app":"PHP","message":"Undefined index: mime at \/var\/www\/html\/owncloud\/apps\/files\/ajax\/mimeicon.php#4","level":3,"time":"2014-11-21T12:38:30+00:00"}
{"app":"PHP","message":"Undefined index: mime at \/var\/www\/html\/owncloud\/apps\/files\/ajax\/mimeicon.php#4","level":3,"time":"2014-11-21T12:39:05+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\Forbidden: ","level":4,"time":"2014-12-06T15:23:22+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\Forbidden: ","level":4,"time":"2014-12-06T15:25:03+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\Forbidden: ","level":4,"time":"2014-12-06T15:26:00+00:00"}
```

#### Browser log
```
No relevant logs to show
```

**Comment by PVince81** [comment]
Did the problem persist with 7.0.7 or 8.0.5 ?

**Comment by christianrj** [comment]
@PVince81 Yes, although not tested with current version of oC.

**Comment by PVince81** [comment]
This shouldn't happen any more in 8.2 thanks to transactional file locking which prevents such concurrency issues.

8.2 is still in RC1, so you could either try 8.2RC1 or use 8.1.3 instead. In the case of 8.1.3 you need to explicitly enable file locking and have a redis server running, see https://doc.owncloud.org/server/8.1/admin_manual/configuration_files/files_locking_transactional.html

In 8.2 the locking will use the database, which is a bit slower.

**Comment by PVince81** [comment]
Let us know if you still experience such issues despite locking.
Thanks.
