### ISSUE TITLE
Make token based info about a public share available to app developers

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#12676]
When an app receives a token and needs to process shared files in order to offer a public view, it will almost always do the same things to get the original path to the files.
* Get the share based on the token
* Find the original share
* Get the owner of the original share
* Setup the file system for that user
* Get the path to the files

There is an example [here](https://github.com/owncloud/core/blob/988c85d2922a03346389e3656dc71dfee514e645/apps/files_sharing/lib/controllers/sharecontroller.php)

I'm wondering if something like [OCA\Files_Sharing\Helper::setupFromToken](https://github.com/owncloud/core/blob/master/apps/files_sharing/lib/helper.php#L29) could be offered in the OCP namespace or as part of appFramework.
Javascript already has access to part of the info via [/apps/files_sharing/ajax/shareinfo.php](https://github.com/owncloud/core/blob/master/apps/files_sharing/ajax/shareinfo.php)

**Comment by PVince81** [comment]
@rullzer does the new sharing code help here somehow ?

**Comment by rullzer** [comment]
Well the sharemanager has a getShareByToken function. That should do the trick and give you the node your are looking for :)

**Comment by oparoz** [comment]
`getShareByToken` gives the node, but the file system still needs to be set up.
The AppFramework needs to provide everything used by [`ShareController::showShare()`](getShareByToken ) in an array, ready for use

**Comment by rullzer** [comment]
Well that is of course if you want to use the showShare from there. But if you just need to node of the share `getShareByToken` will do that. You don't need to init the fs etc that is all done for you by the Node API.

**Comment by oparoz** [comment]
Apologies, I followed the link in the OP and that was the 2014 version, with all the private methods.... On master, it looks like the shareManager is indeed doing a good job at providing a working node.
Thanks for taking care of that :+1:
