### ISSUE TITLE
swift external storage - authentication error

### ISSUE THREAD

**Issue by dipeit** [owncloud/core#12683]
I am trying to connect  with my rackspace account and am having trouble connecting with owncloud 7.03.

according to the docs (and the html source... as the placeholder is not showing entirely) I need to set these:  

placeholder="Username(required)
placeholder="Bucket (required)"
placeholder="Region (optional for OpenStack Object Storage)"
placeholder="API Key (required for Rackspace Cloud Files)"

but after i entered these and wiggle my mouse and move back and forth it is not saved.

turns out I also need to set the password field because to save it 

the next problem is that it complains about a malformed url 

{"app":"files_external","message":"Guzzle\\Http\\Exception\\CurlException: [curl] 3: <url> malformed [url] \/tokens","level":4,"time":"2014-12-08T04:42:06+00:00"}

well it seems I also need to set the auth URL which should only be required for service type swift but not for cloudfiles.
placeholder="URL of identity endpoint (required for OpenStack Object Storage)"

then after it set the correct URL I am getting unauthorized message:

{"app":"files_external","message":"Client error response\n[status code] 401\n[reason phrase] Unauthorized\n[url] https:\/\/identity.api.rackspacecloud.com\/v2.0\/tokens","level":3,"time":"2014-12-08T04:43:19+00:00"}
 
Several other tools work with Rackspace auth v2, I tried setting tenant to my raclspace account number and/or service name to cloudfiles but no luck.

I feel I have tried every possible config but no luck, has anyone successfully connected to rackspace?

**Comment by gawin** [comment]
+1 Running into the same issues when trying to connect to OpenStack Swift from Cyso (not Rackspace).

{"reqId":"xxxxxxxxxxx","remoteAddr":"xxx.xxx.xxx.xxx","app":"files_external","message":"Client error response\n[status code] 401\n[reason phrase] Unauthorized\n[url] https:\/\/identity.api.openstack.cyso.net:5000\/v2.0\/tokens","level":3,"time":"2015-07-29T16:47:14+00:00"}

Any news on a solution yet?

**Comment by DeepDiver1975** [comment]
Anybody is welcome to debug into issues like this.

**Comment by tjomamokrenko** [comment]
@gawin We probably need separate issue for your problem, but I'll figure out what's wrong with Rackspace.

**Comment by PVince81** [comment]
Any more luck with 8.2.2 ? The swift library was upgraded a long time ago and with a bit of luck it works already ?

**Comment by cmonteroluque** [comment]
closing, no response
