### ISSUE TITLE
Versioning not working with Encryption

### ISSUE THREAD

**Issue by snake2903** [owncloud/core#12685]
I installed ownCloud 7.0.2 on my CentOS 7 server.
First i try to use it without encryption enabled and everything works fine.
After enabling encryption my problems start.

I have aprox. 200 documents, with couple versions of each document.
Those files ar for about month on my cloud. After i try to download some previous version of document, when browser start to download file it says downloadin but then failed.
I tried Firefox, IE, Opera...on all browser the same.

I saw new ownCloud update, 7.0.3 and i updated to latest version.

After update, problem was still here, versioning not working.
By not working, i mean that previous versions is unable to download. On server i can see that there is versoning files.

I tried to reinstall 7.0.2 ownCloud version, but after restoring data, problem was still here.

Then i tried to disable Encryption, decrypt all my files with password, and after that downloading previous file versions started to work.

I tried again enable encryption, and i was unable to download previous file version.

My conclusion is that with Encryption enabled downloading previous file version is not working. :-(

Please investigate that bug becasue encryption is very important to me for ownCloud.

Thank you.

**Comment by schiesbn** [comment]
@snake2903 can you try if this PR solves the problem for you: https://github.com/owncloud/core/pull/13182 ? Thanks!

**Comment by schiesbn** [comment]
I belive this is fixed with: #13182 for OC8, feel free to re-open it if it still fails
