### ISSUE TITLE
No share key found for user XXX

### ISSUE THREAD

**Issue by thbe** [owncloud/core#12692]
After upgrading OC to 7.0.3 I have the problem that files uploaded to an already shared folder are failing with a log message like:

{"app":"Encryption library","message":"No share key found for user \"XXX-XXX-XXX-XXX-XXX\" for file \"xyz\"","lev
el":2,"time":"2014-12-08T10:50:39+00:00"}
{"app":"Encryption library","message":"No share key found for user \"YYY-YYY-YYY-YYY-YYY\" for file \"xyz\"","lev
el":2,"time":"2014-12-08T10:50:39+00:00"}
{"app":"Encryption library","message":"No share key found for user \"pubShare_96374101\" for file \"xyz\"","level":2,"time":"2014-
12-08T10:50:39+00:00"}

The server is Scientific Linux 6.6, PHP is version 5.5 from Software Collections as well as Apache 2.4 also from Software Collections. Encryption is enabled, the OC is installed from ownCloud-Community Repo.

Any ideas?

**Comment by MorrisJobke** [comment]
I will close this ticket, because we moved to a completely rewritten encryption layer.

Feel free to report back if this problem still exists on 8.1.1+ and we will reopen the ticket. Thanks
