### ISSUE TITLE
Can't download files with Android Chrome

### ISSUE THREAD

**Issue by Foxeronie** [owncloud/core#12694]
Hi guys,

I'm trying to download a file from my owncloud instance with Chrome on Android.
The download begins, but the progress bar never starts (see screenshot).
I tried it with other smartphones, but the problem is still the same.
When I use another browser everything works fine (or Desktop Version of Chrome).
let me know If you need additional info's.

Installed:
Ubuntu Server 12.04.5 LTS
ownCloud 7.0.3 (stable)
nginx/1.1.19
PHP 5.3.10-1ubuntu3.15 (fpm-fcgi) (built: Oct 29 2014 12:23:57)
mysqld  Ver 5.5.40

I have a cutting from the nginx error log in debug mode while downloading.
You can find it here: http://pastebin.com/hMsyg53e
I edited my address and the server address.

Best regards,
Patrick

![screenshot_2014-12-07-22-14-41](https://cloud.githubusercontent.com/assets/10115997/5339085/2f69d0b4-7edc-11e4-8351-26e82adbf396.png)

**Comment by dh1jc** [comment]
Same problem here.
Server runs Apache and OC 7, https certificate is valid signed via startssl.
Android version: 4.0.3 (but also affects others... but don't know the versions of friends devices - but none worked)

I shared a link and that works perfect via Desktop Browser or Opera Mobile browser but fails with Android browser.

Noticed following in apache log:
Download via Desktop:
some.server:443 1.2.3.4 - - [01/Jan/2015:16:54:08 +0100] "GET /public.php
?service=files&t=xxxxxx&download HTTP/1.1" 200 2850819
 "-" "Mozilla"
Size is correct.

Download via Android:
some.server:443 1.2.3.4 - - [01/Jan/2015:16:45:25 +0100] "GET /public.php
?service=files&t=xxxxxx&download HTTP/1.1" 200 82735
 "-" "Mozilla/5.0 (Linux; U; Android 4.0.3; en-gb; HTC/EVO_3D/3.28.161.3 Build/I
ML74K) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30"

So the size is different?! wonder why

Thanks,

**Comment by RealRancor** [comment]
@dh1jc 
Have you checked the bugreport to chrome/chromium posted one comment above your's?

**Comment by dh1jc** [comment]
Hi,

yes I did.
  https://github.com/owncloud/core/issues/12931
is about wrongly named files after download.
And about content disposition.

I would be glad if the file is at least downloaded...

-- 
Joschi

**Comment by PVince81** [comment]
Was Chrome fixed eventually ?

**Comment by jsalatiel** [comment]
No. Still have problems with it. just cant download.

**Comment by linucksrox** [comment]
Me too! Using self signed cert, android chrome v 45. Eventually the download notification says unsuccessful, and download manager claims to have failed downloading a file named "" or "unknown file".

**Comment by LukasReschke** [comment]
Closing due to https://github.com/owncloud/core/issues/12931#issuecomment-162449852

**Comment by ngethe** [comment]
What as the fix to this ? I have the same issue

**Comment by linucksrox** [comment]
Chrome in Android prevents downloading files over HTTPS with an unsigned cert (or self signed cert). The workaround is to use a different browser, but a better fix is to use a signed cert which is extremely easy to get using let's encrypt.

**Comment by ngethe** [comment]
@linucksrox Thanks for this
