### ISSUE TITLE
Scrolling down userlist makes page jump to beginning if end of list reached

### ISSUE THREAD

**Issue by tps800** [owncloud/core#12699]
### Steps to reproduce
1. Install ownCloud, create lots of users -- more than one page fit on
2. Scroll down to the bottom of the screen

### Expected behaviour
Seamlessly scroll down to the last line, allowing to select even the last user in the list.

### Actual behaviour
As soon as users are loaded behind the view area jumps to the first user displayed.
Trying to select the last user is nearly impossible, because the view area jumps up to fast to click on this user, opening any editable field (which stops jumping up again).

This seems to be related to loading additional users from the database as soon as you have scrolled down the list to about 2/3. Loading additional users seems to result in a redraw event within the browser leading to jump to top of page or, depending on the browser used someway up the page.
Since I do not see this behaviour with the same browser, but other pages using continuous scrolling, like facebook or google+, I am sure this might be a problem how ownCloud implements continuous scrolling for the user list.

### Server configuration
**Operating system**:
* Oracle Linux Server release 6.6 (Red Hat Enterprise Linux Server release 6.6 (Santiago))

**Web server:** Apache 2.2.15
* httpd-2.2.15-39.0.1.el6.x86_64
* httpd-tools-2.2.15-39.0.1.el6.x86_64

**Database:** PostgreSQL 9.3.5 
* postgresql92-9.2.9-1PGDG.rhel6.x86_64
* postgresql92-contrib-9.2.9-1PGDG.rhel6.x86_64
* postgresql92-libs-9.2.9-1PGDG.rhel6.x86_64
* postgresql92-server-9.2.9-1PGDG.rhel6.x86_64
* postgresql93-9.3.5-1PGDG.rhel6.x86_64
* postgresql93-contrib-9.3.5-1PGDG.rhel6.x86_64
* postgresql93-libs-9.3.5-1PGDG.rhel6.x86_64
* postgresql93-server-9.3.5-1PGDG.rhel6.x86_64

**PHP version:** PHP 5.5.18
* php55w-5.5.18-1.w6.x86_64
* php55w-bcmath-5.5.18-1.w6.x86_64
* php55w-cli-5.5.18-1.w6.x86_64
* php55w-common-5.5.18-1.w6.x86_64
* php55w-dba-5.5.18-1.w6.x86_64
* php55w-enchant-5.5.18-1.w6.x86_64
* php55w-fpm-5.5.18-1.w6.x86_64
* php55w-gd-5.5.18-1.w6.x86_64
* php55w-imap-5.5.18-1.w6.x86_64
* php55w-intl-5.5.18-1.w6.x86_64
* php55w-ldap-5.5.18-1.w6.x86_64
* php55w-mbstring-5.5.18-1.w6.x86_64
* php55w-mcrypt-5.5.18-1.w6.x86_64
* php55w-mysql-5.5.18-1.w6.x86_64
* php55w-opcache-5.5.18-1.w6.x86_64
* php55w-pdo-5.5.18-1.w6.x86_64
* php55w-pear-1.9.4-7.w6.noarch
* php55w-pecl-apcu-4.0.7-1.w6.x86_64
* php55w-pecl-memcache-3.0.8-2.w6.x86_64
* php55w-pgsql-5.5.18-1.w6.x86_64
* php55w-process-5.5.18-1.w6.x86_64
* php55w-pspell-5.5.18-1.w6.x86_64
* php55w-recode-5.5.18-1.w6.x86_64
* php55w-snmp-5.5.18-1.w6.x86_64
* php55w-soap-5.5.18-1.w6.x86_64
* php55w-tidy-5.5.18-1.w6.x86_64
* php55w-xml-5.5.18-1.w6.x86_64
* php55w-xmlrpc-5.5.18-1.w6.x86_64
* php-pear-MDB2-2.5.0-0.9.b5.el6.noarch
* php-pear-MDB2-Driver-mysqli-1.5.0-0.8.b4.el6.noarch
* php-pear-Net-Curl-1.2.5-4.el6.noarch)

**ownCloud version:** (see ownCloud admin page) 
* owncloud-3rdparty-7.0.3-14.1.noarch
* owncloud-7.0.3-14.1.noarch

**Updated from an older ownCloud or fresh install:**
* upgrade

**List of activated apps:**
* Activity
* Deleted Files
* LDAP user and group backend
* ownCloud dependencies info
* PDF Viewer
* Pictures
* Share Files
* Charts
* Files Move
* Imprint
* Password Policy Enforcement

**The content of config/config.php:**
```
<?php
$CONFIG = array (
  'instanceid' => 'oc692ddacb52',
  'passwordsalt' => 'XXX',
  'trusted_domains' =>
  array (
    0 => 'lasair.bfs.de',
    1 => 'dmz01-muc.bfs.de',
  ),
  'datadirectory' => '/data/owncloud/data',
  'dbtype' => 'pgsql',
  'version' => '7.8.1.0',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncld',
  'dbpassword' => 'XXX',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => '0',
  'mail_smtpmode' => 'php',
  'mail_smtpname' => 'admin',
  'mail_smtppassword' => 'XXX',
  'overwritewebroot' => '/owncloud',
  'secret' => 'aQqj0WFAes66HltaOdw1yenkkXUzyi6qzskPOFvB6mfakm4a',
);
```

**Are you using external storage, if yes which one:**
* None

**Are you using encryption:**
* No

### Client configuration
**Browser:**
varies:
* Chromium (dev, stable, release) -> jumps to top of page,
* Chrome (dev, stable, release) -> jumps to top of page,
* Firefox (nightly, alpha, beta, stable) -> jumps upwards in page, but not to top of page,
* Opera (release) -> jumps upwards in page, but not to top of page,
* lynx (release) -> keeps position, but selected field (user) jumps up

**Operating system:**
* Windows 7 64-Bit,
* Ubuntu 14.04.1 LTS

#### Web server error log
```
none
```

#### ownCloud log (data/owncloud.log)
```
none
```

#### Browser log
```
none
```

**Comment by PVince81** [comment]
@tps800 are you still seeing this in 8.0.5 or 8.1 ?

**Comment by PVince81** [comment]
Please try again with 8.1.3 and reopen if the problem persists.
