### ISSUE TITLE
Run owncloud with puppet - make sure no files are deleted

### ISSUE THREAD

**Issue by gig13** [owncloud/core#12707]
We are using owncloud with puppet and this requires knowledge on which files are updated in the owncloud directory. Can someone please provide that list of files/directories?
We have to be sure that ownCloud won't create any new files while running because puppet will delete anything thats different from it's state of the ownCloud directory. I can switch off this mechanism for single files or directories though. 

This is the corresponding puppet resource with being the source directory of ownCloud.
file{ 'owncloud_dir':
path => $owncloud_user_home,
owner => $owncloud_user_name,
ensure => "directory",
purge => true,
force => true,
recurse => true,
source => "puppet:///modules/owncloud-server/owncloud_core",
}

@MorrisJobke

**Comment by MorrisJobke** [comment]
@gig13 Ping

**Comment by gig13** [comment]
@MorrisJobke 
Waiting for a reponse.

**Comment by MorrisJobke** [comment]
@gig13 Can this be closed?

**Comment by gig13** [comment]
@MorrisJobke 
Yes, closing out.
