### ISSUE TITLE
Logging data on admin page is not accurate when the log file is outside the oC install directory

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#12706]
### Steps to reproduce

1. Install owncloud with the data directory outside of the oC directory, like /mnt/ocdata
2. Go to the admin page and view the log file
3. The log file only shows whats in the log file under oc/data so any new logging is not shown

### Expected behaviour

The logging information on the admin page reflects the active log file contents.

### Actual behaviour

The logging information on the admin page does not reflect the active log file contents.

### Server configuration

Ubuntu 14.04
PHP 5.5.9
ownCloud Enterprise Edition 7.0.4 RC2 (testing)

### Browser Configuration

Chrome

**Comment by karlitschek** [comment]
can´t verify. closing
