### ISSUE TITLE
session_regenerate_id(): Session object destruction failed at /usr/share/webapps/owncloud/lib/private/user.php#237

### ISSUE THREAD

**Issue by neitsab** [owncloud/core#12703]
Hi,
I have this error message that fills up my log:

    {PHP} session_regenerate_id(): Session object destruction failed at /usr/share/webapps/owncloud/lib/private/user.php#237

Here is the [corresponding code](https://github.com/owncloud/core/blob/v7.0.3/lib/private/user.php#L226-L243) for my version of OC (7.0.3.4):
```php
	/**
	 * Try to login a user
	 * @param string $loginname The login name of the user to log in
	 * @param string $password The password of the user
	 * @return boolean|null
	 *
	 * Log in a user and regenerate a new session - if the password is ok
	 */
	public static function login($loginname, $password) {
		$loginname = str_replace("\0", '', $loginname);
		$password = str_replace("\0", '', $password);

		session_regenerate_id(true);
		$result = self::getUserSession()->login($loginname, $password);
		if ($result) {
			//we need to pass the user name, which may differ from login name
			OC_Util::setupFS(self::getUserSession()->getUser()->getUID());
		}
		return $result;
	}
```
I didn't change my user/login name nor my password, and it happens whether or not I am logged in (as the default -- administrative -- user, the one I created when I set up OC). I am running it on an up-to-date Arch Linux home server, with latest nginx, PHP (served by uWSGI) and MariaDB (see below for precise versions).

On a side note I also sync my contacts and calendar with my Android phone thanks to DAVDroid. First time the error came up was
```php
{"app":"PHP","message":"session_destroy(): Session object destruction failed at \/usr\/share\/webapps\/owncloud\/lib\/base.php#406","level":3,"time":"2014-11-17T12:16:56+00:00"}
```

I've seen similar error message in logs posted in [previous issues](https://github.com/owncloud/core/search?q=session+object+destruction&type=Issues&utf8=%E2%9C%93), but those were all closed and not specific for this error, that's why I opened up this issue.

Here goes the issue template:

### Steps to reproduce
Nothing specific. Just log in and browse a little bit the interface, e.g. go to the Administration settings and watch the Log, then log out.

### Expected behaviour
No errors :)

### Actual behaviour
Above mentioned error appears

### Server configuration
**Operating system**:
Arch Linux

**Web server:**
nginx 1.6.2

**Database:**
mysql  Ver 15.1 Distrib 10.0.15-MariaDB, for Linux (i686) using readline 5.1

**PHP version:**
PHP 5.6.3 (cli) (built: Nov 13 2014 18:36:30) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies

**uWSGI PHP sessions-related config:**
```ini
; cache configuration
; create a cache with 1000 items named 'mysessions'
cache2 = name=mysessions,items=1000
; set the 'uwsgi' session handler
php-set = session.save_handler=uwsgi
; use the 'mysessions' cache for storing sessions
php-set = session.save_path=mysessions
```
**ownCloud version:** (see ownCloud admin page)
7.0.3.4

**Updated from an older ownCloud or fresh install:**
Fresh install (well, updated from 7.0.1)

**List of activated apps:**
Stock ones: Files Contacts Calendar Documents Activity Images

**The content of config/config.php:**

```php
<?php
$CONFIG = array (
  'instanceid' => 'removed,
  'passwordsalt' => 'removed',
  'trusted_domains' => 
  array (
    0 => 'removed',
  ),
  'datadirectory' => '/home/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.3.4',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_neitsab',
  'dbpassword' => 'removed',
  'installed' => true,
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,

'log_type' => 'syslog',
'logdateformat' => 'c',
'logtimezone' => 'Europe/Paris',
'cron_log' => false,
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Nope

**Are you using encryption:** yes/no
Not in-app, but underlying FS is LUKS-LVM-ext4

### Client configuration
**Browser:**
Not related but FF 34

**Operating system:**
Arch Linux + Android 4.4

#### Web server error log
None

#### ownCloud log (data/owncloud.log)
```
{PHP} session_regenerate_id(): Session object destruction failed at /usr/share/webapps/owncloud/lib/private/user.php#237
```

#### Browser log
None

Thanks for your consideration :)

**Comment by Xenopathic** [comment]
@neitsab Are you still getting this issue?

**Comment by neitsab** [comment]
Actually I was just looking at it, and after upgrading to latest version of OC 8.x this issue has disappeared (but has been replaced by another one, that I shall report promptly). Feel free to close!

**Comment by Xenopathic** [comment]
Awesome! Thanks for the confirmation :smile:
