### ISSUE TITLE
Client won't sync when files are put in a shared folder

### ISSUE THREAD

**Issue by jmary** [owncloud/core#12713]
Situation : 
Create two groups :  group1 and group2
useradmin belong to both groups.
user2 belong to group2.
Folder2 belong to group2 and can be accessed read/write by useradmin.

If user2 places a file into folder2, then folder2 won't be synced on useradmin client.
Sync will happen if useradmin is doing something inside folder2.

That's a nasty bug, adoption blocker indeed.

I noticed this since 7.03, it affects 7.04 also.

Julien

**Comment by PVince81** [comment]
Etag propagation has be reworked in 8.1 for shared storage (https://github.com/owncloud/core/pull/14764), this should work in that version.
