### ISSUE TITLE
user page does not remember the selected check boxes

### ISSUE THREAD

**Issue by tessus** [owncloud/core#12727]
When I select the `Show last login` check box on the user page, the status isn't saved. The next time I go to the user page, I have to select it again. The same is true for `Show storage location`.

The only status that seems to be stored is the `Default quota`.

ownCloud 7.0.3 (I can also fill out the template, but I don't believe this is relevant in this case).

**Comment by PVince81** [comment]
@stephane84 do you have time to look into this ?
I guess it should be a matter of using the same mechanism like "Default quota" to save the setting.

**Comment by jancborchardt** [comment]
Has been reported multiple times, green-ticket as well. @blizzz @schiesbn?

**Comment by rullzer** [comment]
Quick fix in #19354

**Comment by jancborchardt** [comment]
Thanks a lot @rullzer!
