### ISSUE TITLE
Option to download ownCloud log

### ISSUE THREAD

**Issue by karlitschek** [owncloud/core#12731]
On the ownCloud Admin page is a section to see to ownCloud logfile and to configure the loglevel.
In some scenarios it is not possible to access the logfile on the server directly and browsing through the logfile via the webinterface is painful. 
So we should add a "Download Logfile" button.

We should check how big the file is and add a Warning "Logfile is too huge so download might take too long" if it is bigger than 100MB

**Comment by MorrisJobke** [comment]
@radoeka Yes it is: https://github.com/owncloud/core/blob/master/config/config.sample.php#L517

**Comment by MorrisJobke** [comment]
https://github.com/owncloud/core/blob/6a5f12beca175a0b9a951fa844eacfd21a8df3de/config/config.sample.php#L517 <- permanent link
