### ISSUE TITLE
Permissions error on some folders

### ISSUE THREAD

**Issue by cf8geek** [owncloud/core#12730]
Steps to reproduce
1.	Add a file/create a folder, on desktop running ownCloud client
2.	receive error

1.	Go to web browser ip-address/owncloud
2.	Login
3.	navigate to same folder as before
4.	See error along top of webpage, and lack of buttons to add or upload folders.
Expected behaviour
Should either give the error for everything or nothing. Not a seemingly random selection of folders.
Actual behaviour
Receive the error on a seemingly random selection of folder. Permissions are same on everything server-side, as far as I can tell (used chmod and chown to ensure this).

The error varies depending on what I try to do, but it follows the format of: "Not allowed because you don't have permission to X". Full error strings contained here: "http://ftp2.halpanet.org/source/_dev/mirall.git/src/libsync/syncengine.cpp".

Server configuration
Operating system: Ubuntu 14.04 (upgrading to 14.10 now)
Web server: Apache2
Database: MySQL
PHP version: 5.5.9
ownCloud version: 7.0.3 (stable)
 Updated from an older ownCloud or fresh install: updated
List of activated apps: none??
The content of config/config.php:
<?php
$CONFIG = array (
  'instanceid' => 'occa2986066a',
  'passwordsalt' => '[redacted]',
  'trusted_domains' => 
  array (
    0 => '10.40.97.230',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.3.4',
  'installed' => true,
  'maintenance' => false,
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbuser' => 'root',
  'dbpassword' => '[redacted]',
  'theme' => '',
); Are you using external storage, if yes which one: no, it's local.
Are you using encryption: no
Client configuration
Browser: Firefox
Operating system:
Win7x64 w/browser, Mac OS X 10.8.5 w/ ownCloud Desktop Client 1.7.0
Logs
Web server error log – /var/log/apache2/error.log
[Sun Dec 07 06:28:25.547774 2014] [mpm_prefork:notice] [pid 1470] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 configured -- resuming normal operations
[Sun Dec 07 06:28:25.547797 2014] [core:notice] [pid 1470] AH00094: Command line: '/usr/sbin/apache2'
[Sun Dec 07 14:07:17.696482 2014] [mpm_prefork:notice] [pid 1470] AH00169: caught SIGTERM, shutting down
[Sun Dec 07 14:07:18.878751 2014] [mpm_prefork:notice] [pid 41875] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 configured -- resuming normal operations
[Sun Dec 07 14:07:18.879259 2014] [core:notice] [pid 41875] AH00094: Command line: '/usr/sbin/apache2'
[Sun Dec 07 14:33:31.120583 2014] [mpm_prefork:notice] [pid 41875] AH00169: caught SIGTERM, shutting down
[Sun Dec 07 14:33:44.274984 2014] [mpm_prefork:notice] [pid 1462] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 configured -- resuming normal operations
[Sun Dec 07 14:33:44.275233 2014] [core:notice] [pid 1462] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 09 14:34:31.394297 2014] [autoindex:error] [pid 12305] [client 10.40.97.235:63899] AH01276: Cannot serve directory /var/www/owncloud/settings/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index forbidden by Options directive
[Tue Dec 09 14:36:30.163695 2014] [access_compat:error] [pid 12253] [client 10.40.97.235:64018] AH01797: client denied by server configuration: /var/www/owncloud/config
[Tue Dec 09 14:36:33.735661 2014] [:error] [pid 12253] [client 10.40.97.235:64018] script '/var/www/owncloud/config.php' not found or unable to stat
[Tue Dec 09 14:38:07.373018 2014] [autoindex:error] [pid 13116] [client 10.40.97.235:64087] AH01276: Cannot serve directory /var/www/owncloud/settings/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index forbidden by Options directive
[Tue Dec 09 14:38:30.097737 2014] [access_compat:error] [pid 13117] [client 10.40.97.230:54138] AH01797: client denied by server configuration: /var/www/owncloud/data/htaccesstest.txt
ownCloud log (data/owncloud.log) – since beginning of month
{"app":"core","message":"unable to rename, file is not writable : files_versions\/Venues\/Worship-Center\/11.26-27","level":3,"time":"2014-12-02T17:19:41+00:00"}
{"app":"core","message":"unable to rename, file is not writable : files_versions\/Venues\/Worship-Center\/11.26-27","level":3,"time":"2014-12-02T17:19:41+00:00"}
{"app":"core","message":"unable to rename, file is not writable : files_versions\/Venues\/Worship-Center\/11.26-27","level":3,"time":"2014-12-02T17:19:41+00:00"}
{"app":"PHP","message":"unlink(\/var\/www\/owncloud\/data\/production\/files\/Venues\/Worship-Center\/11.26-27\/TG-Bible BLANK.mov): No such file or directory at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#64","level":3,"time":"2014-12-02T17:19:41+00:00"}
{"app":"PHP","message":"unlink(\/var\/www\/owncloud\/data\/production\/files\/Venues\/Worship-Center\/11.26-27\/2014 Thanksgiving\/Slide1.jpg): No such file or directory at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#64","level":3,"time":"2014-12-02T17:19:41+00:00"}
{"app":"PHP","message":"unlink(\/var\/www\/owncloud\/data\/production\/files\/Venues\/Worship-Center\/11.26-27\/TG-Alyssa2 L3rd.mov): No such file or directory at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#64","level":3,"time":"2014-12-02T17:19:41+00:00"}
{"app":"PHP","message":"rmdir(\/var\/www\/owncloud\/data\/production\/files\/Venues\/Worship-Center\/11.26-27\/2014 Thanksgiving): No such file or directory at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#62","level":3,"time":"2014-12-02T17:19:42+00:00"}
{"app":"PHP","message":"rmdir(\/var\/www\/owncloud\/data\/production\/files\/Venues\/Worship-Center\/11.26-27): No such file or directory at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#68","level":3,"time":"2014-12-02T17:19:42+00:00"}
{"app":"PHP","message":"rmdir(\/var\/www\/owncloud\/data\/production\/files\/Venues\/Worship-Center\/11.26-27): No such file or directory at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#68","level":3,"time":"2014-12-02T17:19:42+00:00"}
{"app":"PHP","message":"rmdir(\/var\/www\/owncloud\/data\/production\/files\/Venues\/Worship-Center\/11.26-27): No such file or directory at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#68","level":3,"time":"2014-12-02T17:19:42+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\Forbidden: ","level":4,"time":"2014-12-02T17:19:42+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\Forbidden: ","level":4,"time":"2014-12-02T17:19:42+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\Forbidden: ","level":4,"time":"2014-12-02T17:19:42+00:00"}
{"app":"sharing","message":"No fileinfo available for: \/Venues\/Worship-Center\/11.29-30","level":2,"time":"2014-12-02T17:31:20+00:00"}
{"app":"PHP","message":"filesize(): stat failed for \/var\/www\/owncloud\/data\/production\/files\/Venues\/Worship-Center\/11.29-30 at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#117","level":3,"time":"2014-12-02T17:31:20+00:00"}
{"app":"PHP","message":"copy(\/var\/www\/owncloud\/data\/production\/files\/Venues\/Worship-Center\/11.29-30): failed to open stream: No such file or directory at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#197","level":3,"time":"2014-12-02T17:31:20+00:00"}
{"app":"files_trashbin","message":"Couldn't move \/Venues\/Worship-Center\/11.29-30 to the trash bin","level":3,"time":"2014-12-02T17:31:22+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\Forbidden: ","level":4,"time":"2014-12-02T17:31:23+00:00"}
{"app":"PHP","message":"RecursiveDirectoryIterator::__construct(\/var\/www\/owncloud\/data\/production\/files\/Venues\/Worship-Center\/11.29-30): failed to open dir: No such file or directory at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#44","level":3,"time":"2014-12-02T17:31:23+00:00"}
{"app":"PHP","message":"filemtime(): stat failed for \/var\/www\/owncloud\/data\/production\/files\/Venues\/Worship-Center\/11.29-30\/Bible_1100.mov at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#133","level":3,"time":"2014-12-02T17:31:26+00:00"}
{"app":"PHP","message":"filesize(): stat failed for \/var\/www\/owncloud\/data\/production\/files\/Venues\/Worship-Center\/11.29-30\/Bible_500.mov at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#117","level":3,"time":"2014-12-02T17:31:26+00:00"}
{"app":"PHP","message":"copy(\/var\/www\/owncloud\/data\/production\/files\/Venues\/Worship-Center\/11.29-30\/Bible_500.mov): failed to open stream: No such file or directory at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#197","level":3,"time":"2014-12-02T17:31:26+00:00"}
{"app":"files_trashbin","message":"Couldn't move \/Venues\/Worship-Center\/11.29-30 to the trash bin","level":3,"time":"2014-12-02T17:31:26+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\Forbidden: ","level":4,"time":"2014-12-02T17:31:26+00:00"}
{"app":"PHP","message":"RecursiveDirectoryIterator::__construct(\/var\/www\/owncloud\/data\/production\/files\/Venues\/Worship-Center\/11.29-30): failed to open dir: No such file or directory at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#44","level":3,"time":"2014-12-02T17:31:26+00:00"}
{"app":"PHP","message":"PDO::__construct(): MySQL server has gone away at \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOConnection.php#36","level":3,"time":"2014-12-03T00:49:31+00:00"}
{"app":"PHP","message":"PDO::__construct(): Error while reading greeting packet. PID=35820 at \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOConnection.php#36","level":3,"time":"2014-12-03T00:49:31+00:00"}
{"app":"remote","message":"SQLSTATE[HY000] [2006] MySQL server has gone away","level":4,"time":"2014-12-03T00:49:31+00:00"}
{"app":"remote","message":"SQLSTATE[HY000] [2002] No such file or directory","level":4,"time":"2014-12-03T00:49:32+00:00"}
{"app":"remote","message":"SQLSTATE[HY000] [2002] No such file or directory","level":4,"time":"2014-12-03T00:49:33+00:00"}
{"app":"remote","message":"SQLSTATE[HY000] [2002] No such file or directory","level":4,"time":"2014-12-03T00:49:33+00:00"}
{"app":"remote","message":"SQLSTATE[HY000] [2002] No such file or directory","level":4,"time":"2014-12-03T00:49:34+00:00"}
{"app":"remote","message":"SQLSTATE[HY000] [2002] No such file or directory","level":4,"time":"2014-12-03T00:49:34+00:00"}
{"app":"remote","message":"SQLSTATE[HY000] [2002] No such file or directory","level":4,"time":"2014-12-03T00:49:34+00:00"}
{"app":"PHP","message":"Undefined index: extension at \/var\/www\/owncloud\/apps\/files_versions\/lib\/versions.php#320","level":3,"time":"2014-12-03T15:57:10+00:00"}
{"app":"core","message":"unable to rename, file is not writable : files_versions\/Venues\/Bridge\/2014-12-06_Mission Navajo.v","level":3,"time":"2014-12-03T15:57:10+00:00"}
{"app":"core","message":"Login failed: 'production' (Remote IP: '10.40.97.151', X-Forwarded-For: '')","level":2,"time":"2014-12-04T14:54:36+00:00"}
{"app":"core","message":"Login failed: 'production' (Remote IP: '10.40.97.151', X-Forwarded-For: '')","level":2,"time":"2014-12-04T15:36:17+00:00"}
{"app":"core","message":"Login failed: 'production' (Remote IP: '10.40.97.183', X-Forwarded-For: '')","level":2,"time":"2014-12-06T03:40:33+00:00"}
{"app":"core","message":"Login failed: 'production' (Remote IP: '10.40.97.183', X-Forwarded-For: '')","level":2,"time":"2014-12-06T06:21:43+00:00"}
{"app":"remote","message":"SQLSTATE[HY000] [2002] No such file or directory","level":4,"time":"2014-12-07T20:33:29+00:00"}
{"app":"core","message":"Login failed: 'production' (Remote IP: '10.40.97.148', X-Forwarded-For: '')","level":2,"time":"2014-12-08T14:18:36+00:00"}
{"app":"core","message":"Login failed: 'production' (Remote IP: '10.40.97.148', X-Forwarded-For: '')","level":2,"time":"2014-12-08T20:34:14+00:00"}
{"app":"core","message":"Login failed: 'production' (Remote IP: '10.40.97.147', X-Forwarded-For: '')","level":2,"time":"2014-12-09T14:10:52+00:00"}

Browser log
I believe this is irrelevant, but nonetheless, the JavaScript console log from Firefox:

Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery-1.10.0.min.js:1
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ jquery-1.10.0.min.js:6
window.controllers is deprecated. Do not use it for UA detection. ace.js:1716
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery-1.10.0.min.js:5

**Comment by PVince81** [comment]
@cf8geek did you try `./occ files:scan --all` ? It should refresh the permissions once and you should not need to rerun it.

Closing because the permission issue should be fixed in 7.0.5 and 8.0.3.
Feel free to reopen if the command above didn't solve your problem permanently.

**Comment by cf8geek** [comment]
I don't know for sure if the command is what fixed my problem, or if I manually fixed it somehow. Either way, it's been working fine, as evidenced by my lack of attention to this thread.

Sorry, and thanks!

**Comment by PVince81** [comment]
No worries. Thanks for the feedback.
