### ISSUE TITLE
PROPFIND for quota takes too long

### ISSUE THREAD

**Issue by ckamm** [owncloud/core#12744]
See @stephane84's comment in https://github.com/owncloud/client/issues/2485#issuecomment-66365218

The user queries quota information like this:

    curl https://YOURSERVER/remote.php/webdav/ --user YOURUSER -X PROPFIND -d '<?xml version="1.0" ?><d:propfind xmlns:d="DAV:"><d:prop><d:quota-available-bytes/><d:quota-used-bytes/></d:prop></d:propfind>' -v --trace-time

and gets response times between 10 seconds and 45 seconds depending on server load. The server is Raspberry Pi / Raspbian / Ligghtpd / mysql.

**Comment by PVince81** [comment]
Quota retrieval speed has been improved a bit: https://github.com/owncloud/core/issues/14173

**Comment by PVince81** [comment]
@ckamm do you still see this slowness in 8.1.3 ?

**Comment by ckamm** [comment]
@PVince81 I don't have a way to reproduce, unfortunately.

**Comment by MorrisJobke** [comment]
Please reopen this if this still happens with 8.1.3+
