### ISSUE TITLE
Share event through external API

### ISSUE THREAD

**Issue by cyril94440** [owncloud/core#12757]
Hey,

First of all thank you for your awesome service.

I can't find how you can share an event with friend through the API, could you help me with that ? Or at least where I can find how it is handled through the web interface ?

Thanking you in advance.

**Comment by MorrisJobke** [comment]
@cyril94440 As @RealRancor already answered: If this is a calendar event: ask in the calendar bug tracker or the mailinglist. Otherwise use mailinglist or IRC. @jbtbnl @brantje and @georgehrke the main contributors in calendar ;)

**Comment by georgehrke** [comment]
There is no api for calendar sharing at the moment. This is also not planned anytime soon. If you need this you can use OC_Calendar_Calendar / OC_Calendar_Object to query events and OCP\Share to actually share them
