### ISSUE TITLE
Enforce strict passwords via a configuration

### ISSUE THREAD

**Issue by gig13** [owncloud/core#12764]
We would like to have a configuration for enabling strict passwords. The configuration should be set in the admin page or config file and could possibly include several generic rules like "must contain at least X many characters", "must contain at least one capital letter", etc.

@MTRichards @MorrisJobke

**Comment by gig13** [comment]
@LukasReschke 
Any updates?

**Comment by LukasReschke** [comment]
Let me GitHub that for you.

**Comment by LukasReschke** [comment]
GitHub shows to me after a very hard recherche that this is not an actively worked on feature (no commit + without milestone) and will be done when it's done.

=> No.

**Comment by MTRichards** [comment]
The best answer is if this is necessary, a directory should be used.  It is really good at managing this and already works.  We will likely not add this for a while, we need to stay focused.

**Comment by gig13** [comment]
Just to add a use case here, this would also include passwords set for Share links. Some uses do not want simple passwords for the shares or any other password set withing ownCloud apps.

**Comment by PVince81** [comment]
Ok so if I understand well this is for both regular passwords and public link passwords

**Comment by DeepDiver1975** [comment]
9.0 will ship owncloud/password_policy app for password policies on link sharing password.

@MTRichards close from my pov

**Comment by MTRichards** [comment]
Got an SF ticket?
We are not working on a complex password policy for ownCloud core at this time. For share links, yes. For core ownCloud, they really should use a directory. At this time, I can't consider this. Happy to reconsider it after ownCloud 9, but it is very low priority on my side.

**Comment by gig13** [comment]
SF 2247 and related to SF 3144, asked for by multiple entities.

**Comment by bboule** [comment]
@MTRichards just cleaning up

**Comment by MTRichards** [comment]
Still not planning on providing this. If you want to enforce complex passwords, please use a directory which is designed to do this.

**Comment by bboule** [comment]
@gig13 how was this message received?  can we close this out and keep FR on backlog

**Comment by gig13** [comment]
Close out!
