### ISSUE TITLE
Missing methods from the PreviewManager 

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#12772]
I've trying to collect the methods I would need to use the [PreviewManager](https://github.com/owncloud/core/blob/master/lib/private/previewmanager.php) from an app.
Here is what I'm missing
- setFile()
- setMaxX()
- setMaxY()
- setScalingUp()
- setKeepAspect()
- getPreview()
- isCached()

@georgehrke

**Comment by PVince81** [comment]
@oparoz what's left to do here ?

**Comment by oparoz** [comment]
Everything is still missing. This should be done after the move of Preview to an app, which is planned for 8.2 https://github.com/owncloud/core/issues/13610
