### ISSUE TITLE
Native SVG support for the thumbnail generator

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#12782]
Currently, the UI is using SVG graphics in browsers which support it, but the standard mime icon is used for thumbnails of SVG  files instead of a small SVG preview.

@georgehrke

**Comment by PVince81** [comment]
@oparoz is that still the case ?

**Comment by oparoz** [comment]
Yes, all SVGs show the icon instead of a preview, given the security risks and the work involved in supporting native SVG previews (I did it for Gallery), I'm not sure this is ever going to be taken care of.

**Comment by georgehrke** [comment]
I think loading arbitrary svg files is not safe.

cc @LukasReschke
