### ISSUE TITLE
Don't show passwords / API key in UI for files_external

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#12804]
Hardening that we should consider doing.

**Comment by PVince81** [comment]
Did you mean not returning the token at all to the client or just using a "type=password" field for them ?
The latter seems to work in 8.2.0 (app secret is a password field)

**Comment by Xenopathic** [comment]
What we could do is process the BackendParameter data variables before they get passed to the client, so a type of 'password' would replace the content with some dummy content. But then we'd need a way to intercept the saving so the real password doesn't get overwritten...
