### ISSUE TITLE
Deleting user must delete all their tags

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#12816]
### Steps
1. Create user
2. Create/assign tags for this user (for example using the contacts app or favorites feature https://github.com/owncloud/core/pull/12360)
3. Delete user
4. Check table `oc_vcategory`

### Expected result
User tags are deleted

### Actual result
User tags are still there

### Versions
master 4b57892c4eeeb7bd3c8b1b0465acf032dc84fd19

**Comment by MorrisJobke** [comment]
@PVince81 As a first step you could add a command to cleanup the tags ;) There you can invoke the logic and then decide after the release where and how to register the hooks properly ;)

**Comment by PVince81** [comment]
Raised repair step ticket here: https://github.com/owncloud/core/issues/13334
That would be the bare minimum to avoid too much DB pollution in the long run.

**Comment by MorrisJobke** [comment]
The repair step is now merged

**Comment by blizzz** [comment]
On which conditions will it be lazy-initialized?

**Comment by PVince81** [comment]
The repair step is just a workaround for now.
@nickvergessen suggested to have it run as a background job.

**Comment by PVince81** [comment]
Not a showstopper, moving to 8.1.

@nickvergessen suggested to make it a one-shot background job: as soon as a user is deleted, the bkg job for cleanup is created. This way the user deletion isn't delayed. Same could be done for other cleanup tasks.

**Comment by PVince81** [comment]
Oh, look what I just found: https://github.com/owncloud/core/blob/master/lib/public/itags.php#L34

It looks like tag deletion whenever a user is deleted was already implemented...

**Comment by DeepDiver1975** [comment]
> Oh, look what I just found: https://github.com/owncloud/core/blob/master/lib/public/itags.php#L34
> 
> It looks like tag deletion whenever a user is deleted was already implemented...

but the location is rater sub optimal .... we need that on IRC discussed hook manager ...

**Comment by DeepDiver1975** [comment]
> but the location is rater sub optimal .... we need that on IRC discussed hook manager ...

https://github.com/owncloud/core/issues/13477

**Comment by MorrisJobke** [comment]
> #13477

This was merged to 8.2 https://github.com/owncloud/core/pull/18316

**Comment by PVince81** [comment]
Would be better to extend CleanTags to delete the tags of deleted users instead.

**Comment by nickvergessen** [comment]
I can take care of this.

**Comment by phpweb** [comment]
Version 9.1.4 

I created one user and I logged in as this newly created user and I uploaded an image and I assigned a tag. Later I logged out and logged in as Admin and I deleted this newly created user. Files and folders were deleted. The tag is but still there.

In terminal I called the cron.php

`php -f cron.php`

This did not also delete the tag.

**Comment by PVince81** [comment]
You are likely talking about system tags which have no owners, the admin must delete these manually.

The original ticket was about private tags which were only used by the contacts app.
