### ISSUE TITLE
Many files to be removed in trash stall/prevent normal file deletions

### ISSUE THREAD

**Issue by RandolfCarter** [owncloud/core#12827]
### Steps to reproduce
0. Make sure Deleted files app is enabled
1. Create a folder with many files in it
2. Delete it
3. Wait 30 days

### Expected behaviour
A delete action on a file in the "Files" view should not fail / timeout (no matter how many files there are in trash bin or how old those files are).

### Actual behaviour

When deleting a file (no matter if via client or via web interface), the request times out.
The client shows "Could not read status line: connection timed out" after a few minutes, and when tried via the web GUI, the spinning wheel after pressing the trash button never stops to spin.
On disk in the datadirectory, the file is never deleted.

When deactivating the Deleted files app, files can be deleted just fine.

### Server configuration
**Operating system**: Ubuntu Server 14.04.1 LTS
**Web server:** Apache 2.4.9 (Ubuntu)
**Database:** MariaDB 10.0.14
**PHP version:** 5.5.9
**ownCloud version:** 7.0.4
**Updated from an older ownCloud or fresh install:** Updated through every major version starting from 4.0.x

**List of activated apps:**
Activity
Bookmarks
Calendar
Contacts
Documents
External Sites
External storage support
Mail Template Editor
owncloud Dependencies info
PDF Viewer
Pictures
Share files 
Tasks
Text editor
Updater
Versions
Video Viewer
Mail
Music
News
Notes

**The content of config/config.php:**
Provided on demand if really necessary

**Are you using external storage, if yes which one:** local, but the deleted files were not on external storage

**Are you using encryption:** no

### Client configuration
**Browser:** Firefox 34.05
**Operating system:** Windows 8.1

#### Web server error log
nothing related 

#### ownCloud log (data/owncloud.log)
many many lines like this:
```
{"app":"files_trashbin","message":"remove \"somefile1\" from trash bin because it is older than 30","level":1,"time":"2014-12-13T09:37:03+00:00"}
{"app":"files_trashbin","message":"remove \"somefile1\" from trash bin because it is older than 30","level":1,"time":"2014-12-13T09:37:40+00:00"}
{"app":"files_trashbin","message":"remove \"somefile2\" from trash bin because it is older than 30","level":1,"time":"2014-12-13T09:38:16+00:00"}
{"app":"files_trashbin","message":"remove \"somefile3\" from trash bin because it is older than 30","level":1,"time":"2014-12-13T09:38:58+00:00"}
{"app":"files_trashbin","message":"remove \"somefile3\" from trash bin because it is older than 30","level":1,"time":"2014-12-13T09:39:39+00:00"}
{"app":"files_trashbin","message":"remove \"somefile3\" from trash bin because it is older than 30","level":1,"time":"2014-12-13T09:40:17+00:00"}
{"app":"files_trashbin","message":"remove \"somefile2\" from trash bin because it is older than 30","level":1,"time":"2014-12-13T09:41:00+00:00"}
{"app":"files_trashbin","message":"remove \"somefile1\" from trash bin because it is older than 30","level":1,"time":"2014-12-13T09:41:28+00:00"}
{"app":"files_trashbin","message":"remove \"somefile2\" from trash bin because it is older than 30","level":1,"time":"2014-12-13T09:42:07+00:00"}
{"app":"files_trashbin","message":"remove \"somefile1\" from trash bin because it is older than 30","level":1,"time":"2014-12-13T09:42:44+00:00"}
{"app":"files_trashbin","message":"remove \"somefile2\" from trash bin because it is older than 30","level":1,"time":"2014-12-13T09:43:26+00:00"}
{"app":"files_trashbin","message":"remove \"somefile1\" from trash bin because it is older than 30","level":1,"time":"2014-12-13T09:43:53+00:00"}
{"app":"files_trashbin","message":"remove \"somefile2\" from trash bin because it is older than 30","level":1,"time":"2014-12-13T09:44:27+00:00"}
{"app":"files_trashbin","message":"remove \"somefile3\" from trash bin because it is older than 30","level":1,"time":"2014-12-13T09:45:01+00:00"}
{"app":"files_trashbin","message":"remove \"somefile2\" from trash bin because it is older than 30","level":1,"time":"2014-12-13T09:45:39+00:00"}
{"app":"files_trashbin","message":"remove \"somefile2\" from trash bin because it is older than 30","level":1,"time":"2014-12-13T09:46:10+00:00"}
{"app":"files_trashbin","message":"remove \"somefile2\" from trash bin because it is older than 30","level":1,"time":"2014-12-13T09:46:49+00:00"}
{"app":"files_trashbin","message":"remove \"somefile2\" from trash bin because it is older than 30","level":1,"time":"2014-12-13T09:47:27+00:00"}
{"app":"files_trashbin","message":"remove \"somefile3\" from trash bin because it is older than 30","level":1,"time":"2014-12-13T09:48:12+00:00"}
{"app":"files_trashbin","message":"remove \"somefile3\" from trash bin because it is older than 30","level":1,"time":"2014-12-13T09:48:58+00:00"}
{"app":"files_trashbin","message":"remove \"somefile2\" from trash bin because it is older than 30","level":1,"time":"2014-12-13T09:49:43+00:00"}
{"app":"files_trashbin","message":"remove \"somefile2\" from trash bin because it is older than 30","level":1,"time":"2014-12-13T09:50:28+00:00"}
{"app":"files_trashbin","message":"remove \"somefile2\" from trash bin because it is older than 30","level":1,"time":"2014-12-13T09:51:25+00:00"}
```
Note how all files appear more than once, for the few that I checked in detail, they were mentioned 5-10 times.
Also note how the messages are ~30 seconds apart (what is happening in between I wonder? deleting a file can't take that long even if it's not that powerful of a system running the server - those files are a few hundred bytes to a few KB in size).

#### Browser log
Firebug Console shows multiple lines like
```
nnn files scanned
```
and then in between
```
now scanning /myusername/files_trashbin/...
```
Altogether I have ~ 6800 files with about 873MB currently in the trash bin. Above log output looks like the whole trash bin is rescanned every time before doing the deletion...?

**Comment by PVince81** [comment]
There's a bug in the expire code that will trigger rescans needlessly.
Let's follow up here: https://github.com/owncloud/core/issues/13974#issuecomment-77531761
