### ISSUE TITLE
mail field from ldap not refreshed

### ISSUE THREAD

**Issue by felixboehm** [owncloud/core#12823]
### Steps to reproduce
1. Connect ownCloud to ldap / AD, including mail field
2. Change mail field in ldap / AD for user X
3. logout / login as user X
4. check email of user x (in DB or with another user through 

### Expected behaviour
The mail field of a user should update in ownCloud after changes in ldap.
Email should also be visible for the user in personal settings.

### Actual behaviour
Mail field is not updated even on (re-)login of user.
And you can't see, which email is used in ownCloud.

### Server configuration
**Operating system**: linux, any

**Web server:** apache

**Database:** mysql

**PHP version:** 5.4

**ownCloud version:** 7.0.3

**Updated from an older ownCloud or fresh install:** fresh

**List of activated apps:** 
default plus
- ldap

**Comment by blizzz** [comment]
@felixboehm can this be closed?

**Comment by felixboehm** [comment]
think so

**Comment by noliveira87** [comment]
Sorry for reopening this ticket with my problem. Where can I set my LDAP mail value on owncloud configuration?
