### ISSUE TITLE
Suggestion: renaming some box texts when you do a SMB mount

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#12826]
external_storage_support:

When I used SMB mount, I found some hint texts in the boxes to be filled in are not clear enough.

![image](https://cloud.githubusercontent.com/assets/3321281/5423309/00a6fea4-82b6-11e4-8767-1e43b2b3c23f.png)

The German box text "Teilen" should be kept in original English (Share) as this is a common used term and everyone knows it. I guess that this also is true for other languages, but it is for sure in German.

The box text "Root" should imho be renamed to "Subfolder", as this makes clear what the intention is about.

If my suggestion gets an agreement, I ask that someone does a PR for the code (as I have no clue where to be done) and I will do the PR for the documentation

**Comment by Xenopathic** [comment]
The PR to fix this was merged by hand, so this wasn't closed with it.
