### ISSUE TITLE
Restart of LDAP server causes ALL desktop clients to popup password dialog

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/core#12849]
When we restart our LDAP server, all clients that try to connect to it at that time will pop up the “wrong password, please enter password” dialog

Take a look at the rate drop off sessions on our load balancer:
![screen shot 2014-12-12 at 14 41 04](https://cloud.githubusercontent.com/assets/214010/5433525/ba8967ce-8448-11e4-8ebc-695be6684677.png)

The case of the LDAP server not being available is different than the case of wrong user password. The desktop client SHOULD detect that case, and either ignore the error for one or two sync cycles or pop up a NON MODAL window that states the problem and tries again, then dismissing the window.

@danimo explained in https://github.com/owncloud/client/issues/2615#issuecomment-66976546 :
>Through the WebDAV interface, the client can't tell the difference. The server will report an authentication failure (`401 Unauthorized`), and the client has no idea if LDAP server isn't availabe, or if the password is wrong.

@MorrisJobke What needs to be done on the server side to send correct information to the client?

00002265

**Comment by cdamken** [comment]
@blizzz any news?

**Comment by DeepDiver1975** [comment]
> @blizzz any news?

no - there will be no quick fix or patch - this is an enhancement which requires detailed analysis.
Nothing we can come up with quickly - sorry
