### ISSUE TITLE
occ files:scan --all throws Fatal error, leaking memory

### ISSUE THREAD

**Issue by felixboehm** [owncloud/core#12855]
![bildschirmfoto 2014-12-15 um 15 57 10](https://cloud.githubusercontent.com/assets/1204907/5437790/133666e0-8473-11e4-921f-df2ba8bf3adf.png)

System is downloadable ownCloud Appliance
+ LDAP is enabled and configured with 2 users.
+ External Storage mount enabled with 2 smb mountpoints

**Comment by Xenopathic** [comment]
@felixboehm Could you fill out the issue template? Or, if you are no longer seeing this issue, can we close this?
