### ISSUE TITLE
Deleting big files within webinterface takes long time

### ISSUE THREAD

**Issue by disy-mk** [owncloud/core#12866]
I have OC running on a Server (s1) using nginx; the data directory resides on another server (storage - s2) and is mounted via NFS.
Deleting a big file, e.g. of 2.5GB size, takes quite long; investigating this behavior I realized, that utilization is very high, but no cpu is used (top/htop).
iotop (on s1) shows initial writing activity for the first 20 secs, than nothing; no cpu then as well, but load climbs as high as >8.0, but is <0.1 in idle.

Just checked with a folder containing 2 files, 2.2GB in sum and it tool 6-7 mins to "delete" the file via webinterface (different devices showed the file(s)/folder being still available (webinterface) for that time.

Connection betw. s1&s2 is 100mbit and usually is not fully utilizable. So, it might be possible that the file "gets fetched" before it gets deleted.

What is happening in background there? 

Both (s1&s2) are running in VMs on different phys. hardware. oc vers. btw. is up2date.(7.?)

**Comment by MorrisJobke** [comment]
ref #12274 and #12487

@PVince81 @schiesbn Is this issue covered in one of the above tickets? Or is there a separate "implement trashbin as a move instead of a copy command"?

**Comment by PVince81** [comment]
This isn't fully finished.
The first step of making a move was done with the move of the trashbin to use storage wrapper #13377. Later on, @icewind1991 will provide further changes that should hopefully do the same in case the files are from a shared storage, see #13360 

I suggest to keep this ticket open for now.

**Comment by PVince81** [comment]
On another note, here are some fixes for the trashbin expiration which was also slow: https://github.com/owncloud/core/issues/13974#issuecomment-77531761

**Comment by MorrisJobke** [comment]
Files are now moved to the trash bin: https://github.com/owncloud/core/pull/13377

@PVince81 @schiesbn This looks like it can be closed now, right?

**Comment by DeepDiver1975** [comment]
> @PVince81 @schiesbn This looks like it can be closed now, right?

yes
