### ISSUE TITLE
Notify changes for favorites files

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#12872]
Add new activity option "File or folder that is a favorite has changed".

Not sure how this would work.
Does it mean non-favorited files should not have activity entries any more ?

@karlitschek @nickvergessen

**Comment by Xenopathic** [comment]
If this is still desired, please open a new issue over at owncloud/activity.

**Comment by nickvergessen** [comment]
No, actually activities are not part of the activity app. The activity app is just an empty framework without any context. Also there is already a PR open:
https://github.com/owncloud/core/pull/15196

**Comment by nickvergessen** [comment]
Implemented in 8.1
