### ISSUE TITLE
Update SabreDAV to 2.0

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#12876]
@DeepDiver1975 let's use this ticket to track the steps required to upgrade SabreDAV to 2.0

Here are a few things I spotted already (not sure if related, but will add them here as part of the wanted refactoring):
- [ ] update 3rdparty Sabre
- [ ] move custom properties into a plugin, only return the requested ones

**Comment by dagbdagb** [comment]
I presume this also means that sabre/vobject will see an update. I have a vcf-file which sabre/vobject 3.3.4 claims is perfect. But OC 7.0.4 (which employs an older version of vobject) bombs on it.

**Comment by PVince81** [comment]
Sabre 2's HttpClient makes it possible to manipulate headers (request/response) which we would need to improve DAV client performance, see https://github.com/owncloud/core/issues/12228#issuecomment-73929446

**Comment by DeepDiver1975** [comment]
> Sabre 2's HttpClient makes it possible to manipulate headers (request/response) which we would need to improve DAV client performance, see #12228 (comment)

okay - lets go for it - but we have to do this fast to get major test time on this - THX

**Comment by PVince81** [comment]
How to do this ?

Is it a matter of updating composer.json and running composer in the 3rdparty folder, then committing ?

**Comment by DeepDiver1975** [comment]
> Is it a matter of updating composer.json and running composer in the 3rdparty folder, then committing ?

changes on 3rdparty have to be done in a branch - in addition we require a branch/pr here in core to see unit test execution

**Comment by PVince81** [comment]
I edited "composer.json" and set the sabre/dav version to 2.1.0.

If I do "composer update" it updates too much, so I tried again from scratch with:
`composer update sabre/dav --with-dependencies`

and get this:
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing sabre/event (2.0.1)
    Loading from cache

  - Installing sabre/http (3.0.4)
    Loading from cache

  - Removing sabre/vobject (2.1.3)
  - Installing sabre/vobject (3.3.5)
    Loading from cache

    Skipped installation of bin bin/vobject for package sabre/vobject: name conflicts with an existing file
    Skipped installation of bin bin/generate_vcards for package sabre/vobject: name conflicts with an existing file
  - Removing sabre/dav (1.8.12)
  - Installing sabre/dav (2.1.0)
    Loading from cache

    Skipped installation of bin bin/naturalselection for package sabre/dav: name conflicts with an existing file
Writing lock file
Generating autoload files
```

Should I also manually update the lock file or does composer does it by itself ?

**Comment by PVince81** [comment]
When I did the full `composer update` it didn't have any conflicts, but it also updated symphony and patchwork, which we probably don't want (I'll check @icewind1991's PR for the symphony update https://github.com/owncloud/3rdparty/pull/156)

**Comment by DeepDiver1975** [comment]
> Should I also manually update the lock file or does composer does it by itself ?

composer will update the lock file all by himself - the lock file should be checked in.

I'd say this looks good

**Comment by PVince81** [comment]
Should we ignore this then:
```
Skipped installation of bin bin/vobject for package sabre/vobject: name conflicts with an existing file
```

**Comment by PVince81** [comment]
3rdparty PR is here: https://github.com/owncloud/3rdparty/issues/158

I'll submit one to core later once I get it running (need to make changes in connector/sabre)

**Comment by osos** [comment]
Not sure if you already get this, but latest SabreDav is 2.1.2 (http://sabre.io/blog/2014/sabre-dav-2.1.2-released/)

**Comment by PVince81** [comment]
Hmmmm right... I didn't know. I'll update it to 2.1.2 then.

**Comment by PVince81** [comment]
This would make it possible to make Sabre Client keep cookies instead of re-authing every time when connecting to a remote ownCloud (federation), see https://github.com/owncloud/core/issues/12228

**Comment by PVince81** [comment]
Sabre update PR for core is here: https://github.com/owncloud/core/issues/14151
