### ISSUE TITLE
Remove incognito mode

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#12888]
The incognito mode has been introduced with https://github.com/owncloud/core/pull/6003 apparently for https://github.com/owncloud/core/pull/5976 to fix encryption for public shares.

The mode is implemented using a singleton and complete static in the legacy class `OC_User`. A better solution would be to implement encryption differently instead of relying of some pretty obscure and undocumented functionality. Nobody I asked even understood what this is for, if the function cannot be removed then we should at least migrate it to `IUserSession` and document properly what this function is even for. 

@schiesbn Can you confirm? - If so I'd try to come up with a PR that solves this problem otherwise.

**Comment by oparoz** [comment]
Can we set this to 8.2? We can't have compliant apps with public pages without it.

**Comment by PVince81** [comment]
@LukasReschke any update ?

From what I remember this was a bigger change with risks of breakage, we might want to defer to 9.0. Unfortunately apps would continue to have to rely on this mode for now.

Should we make it public then ?

**Comment by oparoz** [comment]
Well since it doesn't even work on master, maybe it should just be removed.

**Comment by karlitschek** [comment]
What doesn't work? Which sharing behavior is broken?

**Comment by oparoz** [comment]
@karlitschek This is what I did.

1. Share folder
2. Open new tab
3. Paste and go

I get an empty files list

Now if I open a new private window, I get the list.

AFAIK, incognito mode is there to make it possible to open public links while still being logged in.

**Comment by karlitschek** [comment]
Sounds like a bug. @schiesbn What do you think? @oparoz Can you open a new bug report?

**Comment by oparoz** [comment]
OK

**Comment by oparoz** [comment]
https://github.com/owncloud/core/issues/19273
