### ISSUE TITLE
Misleading log message in logfile after setup: touch() unabe to create file owncloud.log

### ISSUE THREAD

**Issue by RandolfCarter** [owncloud/core#12893]
### Steps to reproduce
1. Set up a new owncloud installation
2. Check the owncloud.log

### Expected behaviour
No log entries, or at least none indicating any problem if everything went ok.

### Actual behaviour
Even if everything went perfectly, there is a message stating that the log file could not be written (in the logfile itself) - quite the paradox ;) (see below for message).
Also reported here: https://forum.owncloud.org/viewtopic.php?f=21&t=25393

### Server configuration
**Operating system**: Ubuntu Server 14.04.1 LTS
**Web server:** Apache 2.4.9 (Ubuntu)
**Database:** MariaDB 10.0.14
**PHP version:** 5.5.9
**ownCloud version:** 7.0.3 / 7.0.4
**Updated from an older ownCloud or fresh install:** fresh install

**List of activated apps:**
default apps from community edition

**The content of config/config.php:**
Pristine config.php as written by setup

**Are you using external storage, if yes which one:** none

**Are you using encryption:** no

### Client configuration
(among others):
**Browser:** Firefox 34.05
**Operating system:** Windows 8.1

#### Web server error log
nothing related 

#### ownCloud log (data/owncloud.log)
```
{"app":"PHP","message":"touch(): Unable to create file \/www\/owncloud\/data\/owncloud.log because No such file or directory at \/www\/owncloud\/lib\/private\/log\/owncloud.php#49","level":3,"time":"2014-11-19T18:36:08+00:00"}
```

#### Browser log
nothing relevant

**Comment by frybread** [comment]
Since the error pops up every two seconds, it hides actual errors in the log file that I'd otherwise see.

**Comment by l3iggs** [comment]
I'm seeing this issue. I'm not using an external drive.

**Comment by mobamoba** [comment]
The solution is to create a "data" directory within your Windows owncloud directory. For whatever reason, that directory doesn't exist but it's the directory where Owncloud expects to find the log.

**Comment by RealRancor** [comment]
If someone is taking over to debug this note the recent discussion/comments in https://github.com/owncloud/core/issues/15992

**Comment by extide** [comment]
I am also seeing this issue, it seems to happen when I have any logging settings (like log type or log file) in the config.php -- if I just remove them entirely (so as to use the defaults) it seems to work -- most of the time at least.

**Comment by MorrisJobke** [comment]
This error is gone, but there is now a new one - see https://github.com/owncloud/core/issues/13736

**Comment by MartinMajewski** [comment]
Seeing this issue as well on my Qnap TS453S Pro with MariaDB and owncloud installed from AppCenter repository
