### ISSUE TITLE
"app":"PHP","message":"filesize(): stat failed for

### ISSUE THREAD

**Issue by fbassas** [owncloud/core#12897]
HI,
we have owncloud 7.0.4 on a ubuntu 14.04 LTS
Now that we have serveral users we are getting messages like this on our owncloud.log

{"app":"PHP","message":"filesize(): stat failed for \/var\/www\/owncloud\/data\/b9e1009e-7f3f-102a-8c82-fdcd95ab32a5\/files_trashbin\/files\/prop-base.d1415788018 at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#117","level":3,"time":"2014-12-17T11:00:48+00:00"}
{"app":"PHP","message":"filesize(): stat failed for \/var\/www\/owncloud\/data\/b9e1009e-7f3f-102a-8c82-fdcd95ab32a5\/files_trashbin\/files\/prop-base.d1415788018 at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#117","level":3,"time":"2014-12-17T11:01:19+00:00"}
{"app":"PHP","message":"filesize(): stat failed for \/var\/www\/owncloud\/data\/b9e1009e-7f3f-102a-8c82-fdcd95ab32a5\/files_trashbin\/files\/prop-base.d1415788018 at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#117","level":3,"time":"2014-12-17T11:03:07+00:00"}

Our firs aproach to solve is have been to use occ with the user id :

occ files:scan b9e1009e-7f3f-102a-8c82-fdcd95ab32a5

And it seems it was enough, but after short, messages appeared again.
Can it be a bug? Something related to database integrity?

Thanks for your help

**Comment by pcace** [comment]
Same issue here... Any help?

**Comment by PeterPablo** [comment]
May be is #15726 related?

**Comment by PVince81** [comment]
@fbassas @pcace is this still happening with 8.0.5 or 8.1 ?

The trashbin case looks like it might be the old "rescan too often" issue which has been fixed in more recent versions.

**Comment by fbassas** [comment]
@PVince81 excuse my late response.
We are on 8.1.1 now and the issue is not happening.
Thanks

**Comment by PVince81** [comment]
Thanks for the feedback.

@pcace please update to 8.0.6 or 8.1.3
