### ISSUE TITLE
Rename in Shared with you is too far to the right

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#12927]
* caused by the favorites stars that aren't present in the shared with you listing

cc @jancborchardt @PVince81 

![favorites-fuck-up](https://cloud.githubusercontent.com/assets/245432/5481771/806aefda-8656-11e4-9fc2-56f305bbd3a6.png)

**Comment by DeepDiver1975** [comment]
@jancborchardt PR ready on this one? Thanks a lot!

**Comment by jancborchardt** [comment]
Here you go: https://github.com/owncloud/core/pull/13191
