### ISSUE TITLE
Coordinate n-way sync with multiple clients/users

### ISSUE THREAD

**Issue by danimo** [owncloud/core#1292]
Marked as bug because it causes bugs like owncloud/mirall#188.

Problem outline: syncs are currently only between a given client and the server (2 way). We need to devise a method to coordinate these syncs, or at least lock files currently synced by one client from access by another.

This bug is also tracked as owncloud/mirall#262.

**Comment by Xenopathic** [comment]
File locking fixed this :rocket:
