### ISSUE TITLE
7.0.4 not proposed for update [PHP 5.6 and SSL]

### ISSUE THREAD

**Issue by tamnellop** [owncloud/core#12932]
Hi

I have a 7.0.3 running install.
I wait for the 7.0.4 being proposed by owncloud .. but it does not.

I've looked at the html source code of the update center and i have 

`A new version is available: Array`

More over i've read that the updater call the url below and... it seems that 

`https://apps.owncloud.com/updater.php` return an empty xml ?

```
<?xml version="1.0"?>
<owncloud>
  <version></version>
  <versionstring></versionstring>
  <url></url>
  <web></web>
</owncloud>
````

Could you please help with this issue ?

Thanks

**Comment by carlaschroder** [comment]
@VicDeo -- Does this need to be documented? If I'm reading the PRs correctly it is fixed in code -- thanks!

**Comment by DeepDiver1975** [comment]
fixed with https://github.com/owncloud/updater/pull/65
