### ISSUE TITLE
download issue with android 4.2.1 browser

### ISSUE THREAD

**Issue by arianeboehme** [owncloud/core#12931]
when downloading a file from mobil android 4.2.1 version deault browser not chrom, the files is allways called download.php. Once you rename it it workes.

**Comment by LukasReschke** [comment]
Not sure about that. Doubt it though. – Don't have an Android device anymore – sorry.

**Comment by LukasReschke** [comment]
This is related to https://github.com/owncloud/core/issues/8046#issuecomment-69559434 though

**Comment by PVince81** [comment]
or we could just redirect to the webdav URL for downloads ? :smile: (would be done anyway as part of https://github.com/owncloud/core/issues/12353)

**Comment by MorrisJobke** [comment]
Tested with Safari, Chrome and Chrome on Android -> this is fixed on master (9.0)
