### ISSUE TITLE
[Request] Open Graph Support

### ISSUE THREAD

**Issue by drarko** [owncloud/core#12946]
### Open Graph support for OwnCloud

The Open Graph protocol http://ogp.me/ is a way of providing rich content information for pages when shared on social networks.

This is quite powerful, but at the basic level it provides a way for content creators to control how the share stub looks when shared on networks like Facebook, Google + or Twitter

I think there should be an app or config option to add Open Graph tags in header, especially when a file is sharing through public link (file_sharing app)

I added them manually on my server (in apps/file_sharing/template/public.php), but if there was a Hook, Middleware or something that can be used to inject this headers in this page from other app, I would gladly make an application for this

I hope you can guide me on this

Thanks

**Comment by oparoz** [comment]
Why make it optional? I guess @drarko could simply submit a PR with his changes to the template and all shared files would automatically get it.

**Comment by wotanii** [comment]
This should get the "Junior Job"-Label. 

Am I correct to assume, that this meta-data would get hard-coded into the sharing-page; So there will probably be no need to add something to other pages or to have any options or side-effects?
