### ISSUE TITLE
Setup tests on jenkins/travis to test memcaches (redis, apcu, ...)

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#12950]
Setup this https://github.com/owncloud/core/pull/12748#issuecomment-67575171 for automated tests.

**Comment by PVince81** [comment]
@MorrisJobke can this be closed or is there anything left to be done ?

CC @SergioBertolinSG @jvillafanez

**Comment by MorrisJobke** [comment]
I think they are covered.
