### ISSUE TITLE
Reshare inner folder, recipients not visible by original sharer

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#12964]
### Steps to reproduce
1. Create users "user1", "user2" and "user3"
2. Login as "user1"
3. Create a folder "test"
4. Share "test" with "user2"
5. Login as "user2"
6. Create a subdir "test/sub"
7. Share "test/sub" with "user3"
8. Login as "user1" again
9. Open share dropdown for "test/sub": "user3" is not visible, might be expected
10. Try sharing with "user3"

### Expected result
Not sure ?

### Actual result
Error message that "test/sub" is already shared with "user3" even though it wasn't visible in the UI.
Could be a usability issue.

At step 9 the share to "user3" isn't visible because it was initiated by "user2", not "user1".
I guess this could be solved by making the reshares NOT a chain: https://github.com/owncloud/core/issues/9058

@schiesbn @owncloud/designers

**Comment by jancborchardt** [comment]
Yeah, I think we already had an issue for that somewhere but I can’t find or recall it at the moment. Something about that reshares should also show up in the list for everyone to see since everyone that folder is shared with is essentially part of a group and should be aware of everyone else.

**Comment by PVince81** [comment]
@jancborchardt you probably mean #9058

**Comment by jancborchardt** [comment]
@PVince81 yeah, should we close this in favor of that?

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/issues/9058
