### ISSUE TITLE
[master] User management jumps up when scrolling down

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#12962]
### Steps to reproduce
1. On a fresh OC install, go to the users management page
2. Create 15 users
3. Try and scroll down to the bottom of the list (do not refresh the page)

### Expected result
Can scroll down to the bottom.

### Actual result
As soon as you reach the bottom of the list, a spinner appears (for loading the next page) and then no new entries appear but the page scrolls back to the top.
This makes it impossible to edit users at the bottom of the list.

I had a case on Chromium where the debugger console was opened, scrolling down would trigger the spinner every time. But now when I tried again after refreshing the page it only did it once.
That one time it still jumped up. But after the jump I was able to scroll down again to reach the bottom of the list.

### Versions
OC 8 pre-alpha git master 87e3e2925044831e5fd962207b4a6e9cd29b3f4f

@MorrisJobke @LukasReschke

**Comment by MorrisJobke** [comment]
fix is in #13419

**Comment by MorrisJobke** [comment]
@crylium Can you give this a try? Thanks

**Comment by crylium** [comment]
@MorrisJobke This fixed the spinner issue as it does not appear anymore. 

However, I don't get a full list of my LDAP users returned. I only see 30 users shown.

I found these lines in the users.js file:

`//30 shall be loaded initially, from then on always 10 upon scrolling`
			`UserList.usersToLoad = 30;`

If I scroll down to the bottom of the user list page, nothing happens, no spinner, no new users appear.

**Comment by MorrisJobke** [comment]
@crylium Ah yes. I just fixed this in master. I will have a look at your issue and try to backport the needed fixes.

**Comment by MorrisJobke** [comment]
@crylium Your problem should be fixed with #13422
