### ISSUE TITLE
cannot install httpd in centos:centos7

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#12967]
My package installation test suite fails currently on all centos systems.
It appears, I am running into https://github.com/docker/docker/issues/8966

Error unpacking rpm package httpd-2.4.6-18.el7.centos.x86_64
error: unpacking of archive failed on file /usr/sbin/suexec: cpio: cap_set_file

seen with docker.io version 1.0.1, build 990021a 
and lxc-docker-1.3.2, build 39fa2fa

**Comment by jnweiger** [comment]
isv:ownCloud:devel/libcap-dummy provides a potential workaround.

**Comment by jnweiger** [comment]
fixed with obs-docker-install-2.8 and up.
https://build.opensuse.org/package/show/isv:ownCloud:devel/obs-docker-install
https://raw.githubusercontent.com/owncloud/administration/master/docker/tools/obs-docker-install.py

**Comment by qris** [comment]
If anyone is looking for help with this issue using LXC (not Docker) and ends up here, you can try [chrooting into the container rootfs](https://discuss.linuxcontainers.org/t/cpio-cap-set-file/472/2) to install httpd.
