### ISSUE TITLE
"Create" share permission doesn't let you upload when encryption is enabled

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#12966]
### Steps to reproduce
1. Enable encryption + files_locking (that's how I tested)
2. Create two users "user1" and "user2"
3. As "user1" create a folder "test"
4. Share "test" with "user2" but only give "create" permission
5. As "user2" upload a file "test.txt" in "test"

### Expected result
File properly uploaded as "test/test.txt"

### Actual result
Error message "Could not find uploaded file".
Refresh the page: file is visible but empty!

### Versions
ownCloud 8 pre-alpha git master (87e3e2925044831e5fd962207b4a6e9cd29b3f4f)
I haven't tested in stable7 but I seem to remember that it worked in OC 7.

@icewind1991 @schiesbn

**Comment by PVince81** [comment]
Tested again.

Without encryption:
- works on stable7 (bf1f9df590e45de4bb9a02c3f472ffdbe702bc69)
- works on master (5ce295907fd9469905d561de71d83149a6c0f6c5)

With encryption:
- works on stable7 (bf1f9df590e45de4bb9a02c3f472ffdbe702bc69)
- broken on master (5ce295907fd9469905d561de71d83149a6c0f6c5)

So this is indeed a regression, and is specific to encryption.

**Comment by PVince81** [comment]
CC @schiesbn

**Comment by PVince81** [comment]
Will try and bisect this.

**Comment by PVince81** [comment]
I was wrong.

Actually stable7 is broken too. They both upload a 0 kb file.
Only in master it will show an additional error message but stable7 will proceed without error message.

**Comment by PVince81** [comment]
Just checked, this is also broken in older OC 7 (v7.0.1) and even broken in v6.0.6.

Removing the regression tag.

@karlitschek @DeepDiver1975 seems this was broken for a while (encryption + "create-only" shares), so I guess not that critical.

**Comment by schiesbn** [comment]
I will have a look. Encryption never checks any permissions but rely on the files system layer below. It just encrypt/decrypt anything which passes through the permission check in OC-Filesystem, so this sounds really strange.

**Comment by DeepDiver1975** [comment]
moving to 8.1 - time is up for 8.0

**Comment by PVince81** [comment]
Still happening on 8.0.3RC1.
Unfortunately the permissions fix https://github.com/owncloud/core/pull/13802 didn't help with this specific case.

**Comment by karlitschek** [comment]
@schiesbn This sounds bad. Can you have a look?

**Comment by PVince81** [comment]
@nickvergessen this might be the one that makes test_sharePermissions.py fail with encryption

**Comment by nickvergessen** [comment]
Does not happen anymore on 8.1
