### ISSUE TITLE
[master] Disable encryption app, no notification, cannot decrypt files

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#12977]
### Steps
1. Enable encryption, relogin
2. Upload files
3. Disable encryption
4. Login again
5. Go to personal page to decrypt files

### Expected
Notification + password fields to decrypt files

### Actual
No notification, no password fields to decrypt files

### Versions
OC 8 git master 8164415b45386cb87e05e6e50cf4b8f3128b2e69
Regression from 7.0.4

@schiesbn please have a look

**Comment by PVince81** [comment]
Fixed by https://github.com/owncloud/core/pull/13311

**Comment by schiesbn** [comment]
fix merged
