### ISSUE TITLE
Update Error message

### ISSUE THREAD

**Issue by felusch** [owncloud/core#12989]
Hi,
my installation was corrupted during update, how can I fix it?
here is the message:

An exception occurred while executing ' INSERT INTO "oc_mimetypes" ( "mimetype" ) VALUES ( ? ) ': SQLSTATE[HY000]: General error: 6 database table is locked

THANK YOU FOR YOUR HELP!
regards
Bodo

**Comment by PVince81** [comment]
@felusch have you been able to solve your problem ?
