### ISSUE TITLE
client syncing .lock file spins apache2 out of control

### ISSUE THREAD

**Issue by phunyguy** [owncloud/core#12985]
I am on 7.0.4 on server and 1.7.1 linux client, with postgresql-9.3 backend.  I have keepassx synched across my devices with owncloud, and it has a small .lock file that it uses.  I can tell it to ignore this lock file, but I am worried about larger organizations that adopt owncloud.  You can't tell every single user to have their client ignore a .lock file.  The issue is, on .lock file deletion, the server-side apache2 service spins into a loop, and my RAID10 array lights steady.  I can provide any logs you need to the best of my ability.

**Comment by PVince81** [comment]
Have you had any more issues with 7.0.7 or 8.0.5 ?
Maybe the delay was the trashbin trying to expire old files.

In 8.1 the trashbin expiration now happens in a background job so it shouldn't slow down sync any more.

**Comment by phunyguy** [comment]
To be honest I really have no idea any more.  Been running flawless for
some time.  Seems to be OK now, whatever it was.

**Comment by PVince81** [comment]
Ok thanks for the feedback, I'll close this then.
