### ISSUE TITLE
Chinese-named files cannot be displayed correctly

### ISSUE THREAD

**Issue by huhu2207** [owncloud/core#12993]
Hi all,
I installed the owncloud 7 to my Windows server (Windows Server 2008r2 with IIS+PHP5.5+MySQL). The owncloud server version is 7.0.0 to 7.0.4 and if I upload a Chinese file, the file name cannot be shown correctly. But if I downgrade the server to 6.0.6, everything seems okay. Is it a bug, or I made any mistakes?

Jackson Hu.

**Comment by dongwb** [comment]
owncloud 8 run on the windows(windsows 2008) is also cannot show Chinese file name correctly.If upload such named “***.pdf”,the result is ".pdf".Chinese file name is lost.

**Comment by huhu2207** [comment]
Okay, thanks, I will test it soon.
