### ISSUE TITLE
Can not upload a file - permission denied

### ISSUE THREAD

**Issue by SPQRInc** [owncloud/core#12991]
I'm getting this error in OS X Sync Client.

At the moment I'm getting the following error:

```
15:38 Entwicklung/Bestia/V2/Entwicklung/com_bestia/admin/sql/install.mysql.utf8.sqlDocuments Das Hochladen dieser Datei ist nicht erlaubt, da die Datei auf dem Server schreibgeschützt ist, Wiederherstellung 
```

which is in German:

```
15:38 Entwicklung/Bestia/V2/Entwicklung/com_bestia/admin/sql/install.mysql.utf8.sqlDocuments Uploading of this file is not allowed, because the file is readonly on the server. Restoring. 
```

If I delete this file via Web-Interface, I can upload it without problems.

Why is the client thinking, that this file is readonly? If it would be readonly, I could not delete it via Webinterface...?

The logs I got from the admin-cp of Webclient:
```
Error	hook	error while running hook (OCA\Search_Lucene\Hooks::indexFile): An exception occurred while executing 'INSERT INTO `oc_jobs`(`class`, `argument`, `last_run`) VALUES(?, ?, 0)': SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'argument' at row 1 2014-12-20T14:13:17+00:00
Error	hook	error while running hook (OCA\Search_Lucene\Hooks::indexFile): An exception occurred while executing 'INSERT INTO `oc_jobs`(`class`, `argument`, `last_run`) VALUES(?, ?, 0)': SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'argument' at row 1 2014-12-20T14:12:33+00:00
Error	hook	error while running hook (OCA\Search_Lucene\Hooks::indexFile): An exception occurred while executing 'INSERT INTO `oc_jobs`(`class`, `argument`, `last_run`) VALUES(?, ?, 0)': SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'argument' at row 1 2014-12-20T14:04:53+00:00
Error	hook	error while running hook (OCA\Search_Lucene\Hooks::deleteFile): An exception occurred while executing 'INSERT INTO `oc_jobs`(`class`, `argument`, `last_run`) VALUES(?, ?, 0)': SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'argument' at row 1 2014-12-20T14:04:24+00:00
Error	PHP	Call to undefined function imagepng() at /Library/Server/Web/Data/Sites/cloud.example.com/lib/private/image.php#282	2014-12-20T14:04:10+00:00
Fatal	webdav	Sabre\DAV\Exception\RequestedRangeNotSatisfiable: The start offset (3459) exceeded the size of the entity (3459)	2014-12-20T14:03:51+00:00
Fatal	webdav	Sabre\DAV\Exception\RequestedRangeNotSatisfiable: The start offset (3459) exceeded the size of the entity (3459)	2014-12-20T14:02:08+00:00
Fatal	webdav	Sabre\DAV\Exception\RequestedRangeNotSatisfiable: The start offset (3459) exceeded the size of the entity (3459)	2014-12-20T14:01:04+00:00
Fatal	webdav	Sabre\DAV\Exception\RequestedRangeNotSatisfiable: The start offset (3459) exceeded the size of the entity (3459)	2014-12-20T14:00:02+00:00
Fatal	webdav	Sabre\DAV\Exception\RequestedRangeNotSatisfiable: The start offset (3459) exceeded the size of the entity (3459)	2014-12-20T13:59:05+00:00
Fatal	webdav	Sabre\DAV\Exception\RequestedRangeNotSatisfiable: The start offset (3459) exceeded the size of the entity (3459)	2014-12-20T13:58:08+00:00
Fatal	webdav	Sabre\DAV\Exception\RequestedRangeNotSatisfiable: The start offset (3459) exceeded the size of the entity (3459)	2014-12-20T13:57:09+00:00
Fatal	webdav	Sabre\DAV\Exception\RequestedRangeNotSatisfiable: The start offset (3459) exceeded the size of the entity (3459)	2014-12-20T13:56:08+00:00
``

**Comment by SPQRInc** [comment]
Hi there,

is there anything I can do to help the team to solve this issue? Can I upload some more logs, do the developers need some more information?

I did not get any information yet.

Thanks in advance :-)

**Comment by karlitschek** [comment]
@icewind1991 Do you have any idea?

**Comment by minnesotags** [comment]
I am experiencing the same issue.

**Comment by LukasReschke** [comment]
The error log looks somewhat related to search_lucene:
```
Error   hook    error while running hook (OCA\Search_Lucene\Hooks::indexFile): An exception occurred while executing 'INSERT INTO `oc_jobs`(`class`, `argument`, `last_run`) VALUES(?, ?, 0)': SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'argument' at row 1 2014-12-20T14:13:17+00:00
```

@butonic Any idea?

**Comment by butonic** [comment]
the lucene error should not prevent the file to be uploaded and can be ignored. nevertheless, the error willl be fixed with oc8 or by using search_lucene v0.6 which is in master

**Comment by SPQRInc** [comment]
Hi,
the permissions are correct.

"G-DRIVE mobile with Thunderbolt" is an external Thunderbolt-HDD. There is a directory for the OC-Data.

I don't know if Thunderbolt locks files when accessed from multiple clients. Shouldn't that be a question of the filesystem and not a question of the connection-type?

I do not use the external storage app. Do I have to?

**Comment by SPQRInc** [comment]
Hi there, any new ideas? Something I could do to help solving this issue?

**Comment by PVince81** [comment]
Is it always the same file ? Is the file shared ?

The linked ticket https://github.com/owncloud/core/issues/13193 is only if the share permissions is restricted to "change" (and "create" and "delete" are disallowed). Can you check with what permission the folder/file was shared ?

**Comment by SPQRInc** [comment]
HI @PVince81 
No, it's not always the same file - this error appears on different files. I often get this error on a special directory, because I'm editing a lot of files in there (Coding my Joomla-Component), but it appears in "Downloads"-Directory, "Desktop"-Directory etc., too.

The files are not shared.

The permissions:

Of the folder "datastore", which is the data-directory for OC: drwxrwx---    9 _www           _www    306B 29 Dez 10:37 datastore

**Comment by PVince81** [comment]
Okay, so that rules out the sharing permissions issues.

Can you post the permissions of the broken file and its container ?

**Comment by PVince81** [comment]
Are you able to overwrite the file by uploading its new version using the Web UI instead of the sync client ? (the sync client uses WebDAV which is a different code path, might help to narrow it down)

**Comment by SPQRInc** [comment]
Hi @PVince81 

At the moment all files are synched correctly, because I found a workaround:

I got the file "view.html.php" from 01.12.2014, which I want to edit.
I edit the file and save it.

Now I'm getting the message, that the file could not be uploaded.

Now I find 2 files:

view.html.php - from 01.12.2014
view.htmlconflictXXXXX.php - from today


Now I delete view.html.php on my mac and wait a moment. Now only the file view.htmlconflict.... exists in the directory. Now I rename this file to view.html.php and it works again. Now if I edit this file I do not have any problems to sync them.

This workaround is not a real solution, because I always have to look for conflict-files ;-).

I did not test to upload it via WebUI, but I'll do it the next time the error appears.

**Comment by smatthie** [comment]
@PVince81 @LukasReschke occ doesn't check user (at least it didn't in my case). As this is a separate issue, I commented in #12307.

In my case the upload issue was solved by rebuilding the file_cache with occ (this time running as web user). I haven't noticed the problem again, although I get the occasional hickups which are probably related to lost connections and then sort themselves out at the next sync run.

I suggest, however, that you should not only at the file permissions in the storage file system but also at the permissions column in the file_cache table in the database to see if they are inconsistent. Perhaps this helps to pin down the issue a bit more.

**Comment by SPQRInc** [comment]
Hi @smatthie ,
how can I rebuild the file_cache with occ? Do I have to do that on the terminal? How can I do that?

**Comment by smatthie** [comment]
@SPQRInc yes, occ is s maintenance script that you have to run from the terminal. From the installation directory (www-data is the name of the web user, might be different in your setup): 
> sudo -u www-data php occ files:scan
But if you're not sure, I would wait, as I'm not sure what other side effects it may have. Perhaps you can just look at your database table (using phpmyadmin or similar) and see if the permission column is different for those files that you can't upload.

**Comment by PVince81** [comment]
@SPQRInc can you try running `sudo -uwww ./occ files:scan --all` again ? (replace "www" with your web server user"). I hope this can fix your permissions.

If not, please do a `select * from oc_filecache where path like '%somefolder%'` and replace "somefolder" with the name of the folder which doesn't allow upload (forbidden)

**Comment by tkaufm** [comment]
Hi there, 
 
i had the same trouble with 2 users. One is using one machine with Debian 7, but had the problem some time ago. The other is syncing with 2 Mac-laptops (latest osx), but only got the problem on one laptop. In both cases rescanning the files didn't help, so i try resetting the sync-client (with F5 to force a rediscovering). Permissions and user on the server where ok and the same as of other files that synced correctly. I didn't need to change anything in the db by hand.
I could get the following log from the mac-sync-client:


```

02-05 09:58:54:603 0x7ff089e197f0 socketapi.cpp:325 SocketApi:  Sending message:  "STATUS:SYNC:/Users/user/oc/doc/letters/2013/ucef/recletter.pages/Metadata/Properties.plist"
02-05 09:58:54:613 0x7ff089e197f0 socketapi.cpp:325 SocketApi:  Sending message:  "STATUS:SYNC:/Users/user/oc/doc/letters/2013/ucef/recletter.pages/preview-micro.jpg"
02-05 09:58:54:615 0x7ff089e197f0 socketapi.cpp:325 SocketApi:  Sending message:  "STATUS:SYNC:/Users/user/oc/doc/letters/2013/ucef/recletter.pages/preview.jpg"
02-05 09:58:54:617 0x7ff089e197f0 socketapi.cpp:325 SocketApi:  Sending message:  "STATUS:SYNC:/Users/user/oc/doc/letters/2013/ucef/recletter.pages/Metadata"
02-05 09:58:54:618 0x7ff089e197f0 socketapi.cpp:325 SocketApi:  Sending message:  "STATUS:SYNC:/Users/user/oc/doc/letters/2013/ucef/recletter.pages/preview-web.jpg"
02-05 09:58:54:640 0x7ff089e197f0 socketapi.cpp:325 SocketApi:  Sending message:  "STATUS:SYNC:/Users/user/oc/doc/letters/2013/ucef/recletter.pages/Index.zip"


02-05 09:58:54:725 0x7ff089e197f0 syncengine.cpp:899 checkForPermission: ERROR "doc/letters/2013/ucef/recletter.pages/Data"
02-05 09:58:54:726 0x7ff089e197f0 syncengine.cpp:912 checkForPermission: ERROR "doc/letters/2013/ucef/recletter.pages/Index.zip"
02-05 09:58:54:726 0x7ff089e197f0 syncengine.cpp:899 checkForPermission: ERROR "doc/letters/2013/ucef/recletter.pages/Metadata"
02-05 09:58:54:727 0x7ff089e197f0 syncengine.cpp:912 checkForPermission: ERROR "doc/letters/2013/ucef/recletter.pages/preview-micro.jpg"
02-05 09:58:54:728 0x7ff089e197f0 syncengine.cpp:912 checkForPermission: ERROR "doc/letters/2013/ucef/recletter.pages/preview-web.jpg"
02-05 09:58:54:728 0x7ff089e197f0 syncengine.cpp:912 checkForPermission: ERROR "doc/letters/2013/ucef/recletter.pages/preview.jpg"


02-05 09:58:56:958 0x7ff089e197f0 owncloudpropagator.cpp:93 This error is not blacklisted  0
02-05 09:58:56:958 0x7ff089e197f0 syncengine.cpp:778 void Mirall::SyncEngine::slotJobCompleted(const Mirall::SyncFileItem &) "doc/letters/2013/ucef/recletter.pages/Data" 2 "Not allowed because you don't have permission to add sub-directories in that directory"
02-05 09:58:56:961 0x7ff089e197f0 socketapi.cpp:325 SocketApi:  Sending message:  "STATUS:ERROR:/Users/user/oc/doc/letters/2013/ucef/recletter.pages/Data"
02-05 09:58:56:964 0x7ff089e197f0 owncloudpropagator.cpp:93 This error is not blacklisted  0
02-05 09:58:56:965 0x7ff089e197f0 syncengine.cpp:778 void Mirall::SyncEngine::slotJobCompleted(const Mirall::SyncFileItem &) "doc/letters/2013/ucef/recletter.pages/Index.zip" 2 "Not allowed because you don't have permission to add files in that directory"
02-05 09:58:56:967 0x7ff089e197f0 socketapi.cpp:325 SocketApi:  Sending message:  "STATUS:ERROR:/Users/user/oc/doc/letters/2013/ucef/recletter.pages/Index.zip"
02-05 09:58:56:970 0x7ff089e197f0 owncloudpropagator.cpp:93 This error is not blacklisted  0
02-05 09:58:56:971 0x7ff089e197f0 syncengine.cpp:778 void Mirall::SyncEngine::slotJobCompleted(const Mirall::SyncFileItem &) "doc/letters/2013/ucef/recletter.pages/Metadata" 2 "Not allowed because you don't have permission to add sub-directories in that directory"
02-05 09:58:56:973 0x7ff089e197f0 socketapi.cpp:325 SocketApi:  Sending message:  "STATUS:ERROR:/Users/user/oc/doc/letters/2013/ucef/recletter.pages/Metadata"
02-05 09:58:56:977 0x7ff089e197f0 owncloudpropagator.cpp:93 This error is not blacklisted  0
02-05 09:58:56:978 0x7ff089e197f0 syncengine.cpp:778 void Mirall::SyncEngine::slotJobCompleted(const Mirall::SyncFileItem &) "doc/letters/2013/ucef/recletter.pages/preview-micro.jpg" 2 "Not allowed because you don't have permission to add files in that directory"
02-05 09:58:56:980 0x7ff089e197f0 socketapi.cpp:325 SocketApi:  Sending message:  "STATUS:ERROR:/Users/user/oc/doc/letters/2013/ucef/recletter.pages/preview-micro.jpg"
02-05 09:58:56:982 0x7ff089e197f0 owncloudpropagator.cpp:93 This error is not blacklisted  0
02-05 09:58:56:983 0x7ff089e197f0 syncengine.cpp:778 void Mirall::SyncEngine::slotJobCompleted(const Mirall::SyncFileItem &) "doc/letters/2013/ucef/recletter.pages/preview-web.jpg" 2 "Not allowed because you don't have permission to add files in that directory"
02-05 09:58:56:995 0x7ff089e197f0 socketapi.cpp:325 SocketApi:  Sending message:  "STATUS:ERROR:/Users/user/oc/doc/letters/2013/ucef/recletter.pages/preview-web.jpg"
02-05 09:58:56:998 0x7ff089e197f0 owncloudpropagator.cpp:93 This error is not blacklisted  0
02-05 09:58:56:999 0x7ff089e197f0 syncengine.cpp:778 void Mirall::SyncEngine::slotJobCompleted(const Mirall::SyncFileItem &) "doc/letters/2013/ucef/recletter.pages/preview.jpg" 2 "Not allowed because you don't have permission to add files in that directory"
02-05 09:58:57:002 0x7ff089e197f0 socketapi.cpp:325 SocketApi:  Sending message:  "STATUS:ERROR:/Users/user/oc/doc/letters/2013/ucef/recletter.pages/preview.jpg"
02-05 09:58:57:004 0x7ff089e197f0 owncloudpropagator.cpp:93 This error is not blacklisted  0
```

**Comment by PVince81** [comment]
For the ones from you had permission troubles with shares, you could try the following patch: https://github.com/owncloud/core/pull/13347.patch

**Comment by PVince81** [comment]
(apply on top of OC 7.0.4)

**Comment by blizzz** [comment]
Since https://github.com/owncloud/core/pull/13347 was merged and no further comments on this, I assume this is fixed  → close.

**Comment by ss89** [comment]
i had the same problem in ownCloud 8.1.1 (Ubuntu, Apache 2.4, PHP 5.5.9) with ownCloud Client version 2.0.1 on Mac OS X 10.9.5.
Are there any information i can provide to help fix this?
Renaming the corresponding folder / files, syncing and then renaming them back is a working workaround for me.

**Comment by blizzz** [comment]
@ss89 please open a new issue with the help of the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md).

**Comment by evieceli** [comment]
I'm having similar issues but the other way around.  I don't want the client to upload to the server, hence we made the server read only, no write permissions from the client.  I want the client PCs to mirror what is on the server.  When I delete files from the server, all the client PCs show a sync error with "permission denied" within the error message.  This is very annoying.  OwnCloud should be able to become customized to specific needs.
