### ISSUE TITLE
Problem when moving from the Calendar to Contacts page

### ISSUE THREAD

**Issue by Peweuk** [owncloud/core#13004]
Selecting the 'Contacts' tab results in the page hanging 8 times out of 10 - in bothe Firefox and IE.

### Steps to reproduce
In web browser select the Contacts tab in OC

### Expected behaviour
Should display 2 panels containing Contacts information

### Actual behaviour
About 2 attempts out of 10 the contacts panels both show containing the correct information in both panels.
The rest of the time either some or none of the information is displayed and the loading icon in the panel/s continues to display rotating indefinitely.

### Server configuration
Linux

**Web server:
Apache version 	2.2.26

**Database:
Sqlite and MySQL version 5.1.73-cll
(happens when using either)

**PHP version:
PHP version 5.4.26

**ownCloud version:
7.0.4
7.0.3
7.0.2
Problem occurs in all three

**Updated from an older ownCloud or fresh install:
Fresh installs

**List of activated apps:
Standard apps activated by OC on installation - no other apps activated.

**The content of config/config.php:
<?php
$CONFIG = array (
  'instanceid' => 'oc6b0569e915',
  'passwordsalt' => 'xxxxxxxxx',
  'secret' => '2054d3eb918db325a92a37807b051b0d9e9db09989a6575711b6a26a3b44cead0a0b0a2b7bfba1442344ea7f1f9c5be4',
  'trusted_domains' => 
  array (
    0 => 'calendar.domain.uk',
  ),
  'datadirectory' => '/home/webi8726/public_html/calendar/pewe/data',
  'overwrite.cli.url' => 'http://calendar.domain.uk/pewe',
  'dbtype' => 'sqlite3',
  'version' => '7.0.4.2',
  'installed' => true,
);

**Are you using external storage, if yes which one:
No

**Are you using encryption:
No

### Client configuration
Mozilla Firefox 34.0.5
IE 10.0.3

**Operating system:**

#### ownCloud log (data/owncloud.log)
```
##ownCloud log:
{"app":"PHP","message":"Trying to get property of non-object at \/home\/webi8726\/public_html\/calendar\/pewe\/lib\/private\/updater.php#110","level":3,"time":"2014-12-22T14:27:48+00:00"}
{"app":"PHP","message":"Trying to get property of non-object at \/home\/webi8726\/public_html\/calendar\/pewe\/lib\/private\/updater.php#111","level":3,"time":"2014-12-22T14:27:48+00:00"}
{"app":"PHP","message":"Trying to get property of non-object at \/home\/webi8726\/public_html\/calendar\/pewe\/lib\/private\/updater.php#112","level":3,"time":"2014-12-22T14:27:48+00:00"}
{"app":"PHP","message":"Trying to get property of non-object at \/home\/webi8726\/public_html\/calendar\/pewe\/lib\/private\/updater.php#113","level":3,"time":"2014-12-22T14:27:48+00:00"}


**The javascript console log:
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery-1.10.0.min.js:1
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ jquery-1.10.0.min.js:6
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src http://domain.uk 'unsafe-eval'"). contacts
TypeError: Argument 1 of Window.getComputedStyle is not an object. tiletabs-browser.js:2993
window.controllers is deprecated. Do not use it for UA detection. ace.js:1716
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data jquery-1.10.0.min.js:4
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery-1.10.0.min.js:5
TypeError: $(...).offset(...) is undefined calendar.js:120
TypeError: $(...).offset(...) is undefined calendar.js:120
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery-1.10.0.min.js:1
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ jquery-1.10.0.min.js:6
window.controllers is deprecated. Do not use it for UA detection. ace.js:1716
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data jquery-1.10.0.min.js:4
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery-1.10.0.min.js:5
TypeError: $(...).offset(...) is undefined

**Comment by Peweuk** [comment]
Since my last post I have discovered that the problem related to memory usage.
According to my host the app is consuming too much memory - but strangely only when I load contacts - according to the server log.
This is what the log records each time I try to load contacts:
---------
[Fri Jan 09 04:16:42 2015] [error] [client 92.18.100.130] File does not exist: /home2/webi8726/public_html/calendar/500.shtml, referer: http://domain/pewe/index.php/apps/contacts/

[Fri Jan 09 04:16:42 2015] [error] [client 92.18.100.130] (12)Cannot allocate memory: couldn't create child process: /opt/suphp/sbin/suphp for /home2/webi8726/public_html/calendar/pewe/index.php, referer: http://domain/pewe/index.php/apps/contacts/

[Fri Jan 09 04:16:41 2015] [error] [client 92.18.100.130] File does not exist: /home2/webi8726/public_html/calendar/500.shtml, referer: http://domain/pewe/index.php/apps/contacts/

[Fri Jan 09 04:16:41 2015] [error] [client 92.18.100.130] (12)Cannot allocate memory: couldn't create child process: /opt/suphp/sbin/suphp for /home2/webi8726/public_html/calendar/pewe/index.php, referer: http://domain/pewe/index.php/apps/contacts/

------------
On my host account I am allocated 10124MB of memory, and In my php settings I can set a maximum of 512MB per process, which I would have though was sufficient for OC, but apparently not for some reason.
Can anyone confirm if this usage is correct??

**Comment by PVince81** [comment]
My personal OC server VM only has 512MB RAM overall and seems to work fine with calendar and contacts.
Do you have lots of users, calendar entries or contacts ?
Not sure what could cause such memory overflow.

**Comment by Peweuk** [comment]
This problem occurs with all 3 versions of OC (7.0.2/7.0.3/7.0.4) and there are only 
416 calendar entries
45 Contacts
1 User
I have no other processes running on the server (none that I am aware of and according to my host).

I disabled all apps in OC (except for Calendar and Contacts) and this improved the number of occasions that the contacts section loads fully - down from about 1 in 12 attaemps to 1 in 5/6 - which I think supports the idea that it is a memory issue (I think)

**Comment by Peweuk** [comment]
My host has sent me some further info.
He says that these are the processes running on the server and it is these that are consuming memory to the point where OC cannot load the contact app properly - his comments are also included

-----------------------------------
You are running more things that just Owncloud. The daily process log is showing your processes are being taken up by the following locations:

webi8726 domain.com 8.8 httpd [domain.com] [/pewe/index.php/heartbeat]
webi8726 domain.com 6.0 httpd [domain.com] [/pewe/index.php/heartbeat]
webi8726 domain.com 4.7 httpd [domain.com] [/favicon.ico]
webi8726 domain.com 7.6 httpd [domain.com] [/pewe/settings/img/apps.svg]
webi8726 domain.com 7.1 httpd [domain.com] [/pewe/core/js/placeholder.js?vf2a60693067d8c108a02e76f7dc1]
webi8726 domain.com 7.1 httpd [domain.com] [/pewe/index.php/apps/contacts/ajax/config.js?_142067399268]
webi8726 domain.com 5.7 httpd [domain.com] [/pewe/apps/contacts/img/contacts.svg]
webi8726 domain.com 5.6 httpd [domain.com] [/pewe/index.php/heartbeat]

These process PLUS trying to run owncloud is what's causing you to hit the RAM limits.
---------------------
This is the effect on memory when I load the contacts page.

![vmem1](https://cloud.githubusercontent.com/assets/10102600/5686663/e4bc090e-983c-11e4-907f-b80477ec553f.jpg)

So it does appear to be OC hogging memory ;(

**Comment by PVince81** [comment]
Are you still seeing this in 8.0.6 or 8.1.1 ?

The issue is likely to be in either the calendar or contacts app that might in some cases try to store all entries in memories (not sure, just guessing). Not related to core.

**Comment by PVince81** [comment]
Please try again with 8.1.3.
