### ISSUE TITLE
Files with special character like a slash (/) in filename throw error

### ISSUE THREAD

**Issue by JimLoose** [owncloud/core#13005]
owncloud 7.0.2 + owncloud mac client 1.7.0. (build 1490)

see attached screenshot:

![bild 2014-12-22 um 16 25 11](https://cloud.githubusercontent.com/assets/195000/5526745/44525642-89f7-11e4-8a80-eeb7990e74dc.png)

_\+ sorry the short bugreport!_

**Comment by jospoortvliet** [comment]
So #2885 would fix it - but needs some testing... @JimLoose perhaps you can help with that?

**Comment by zuidwijk** [comment]
I'm experiencing the problem that files with characters like é ë è ó ö å etc are ignored (giving errors while och files:scan).
[scan_errors.txt](https://github.com/owncloud/core/files/747762/scan_errors.txt)

**Comment by PVince81** [comment]
I just tested and syncing file names that contain colons works fine with 10.0.4 and desktop client 2.4.0~rc1, closing.

@zuidwijk your problem is unrelated to the colon/slash issue. Please switch on Mac compatibility for your external storage (cog icon).
