### ISSUE TITLE
Combine OCS API getUser method code into provisioning_api app.

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#13002]
Currently we have two code sections for the same api method, and they are merged:

https://github.com/owncloud/core/blob/master/lib/private/ocs/cloud.php#L63 and
https://github.com/owncloud/core/pull/13000/files#diff-d63ef796ade5860b68adcc00dc5639a6R68.

We should move all of the code into the provisioning_api app to cleanup.

**Comment by DeepDiver1975** [comment]
the responses of both implementation are getting merged together - this change is not critical -> 8.1

**Comment by tomneedham** [comment]
True

**Comment by cmonteroluque** [comment]
low severity but it would be nice to clean up

**Comment by rullzer** [comment]
PR in #19666
