### ISSUE TITLE
Kill all */ajax/*.php routes and move them to testable controllers

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#13007]

**Comment by PVince81** [comment]
- [ ] make OCS routes work with app framework: #12454

**Comment by PVince81** [comment]
On-going effort. Feature freeze now, so moving it to 9.0

**Comment by PVince81** [comment]
@Xenopathic do we still have any ajax/* endpoints in files_external ? If not, please tick the box :smile:

**Comment by Xenopathic** [comment]
We still do :disappointed:

**Comment by PVince81** [comment]
We're slowly getting there... moving to 9.1 for the rest.

**Comment by PVince81** [comment]
Ongoing... moving to 9.2.

But this is probably something that can be done in combination with other work touching these areas.

For example for the versions app, implementing a public API for it: https://github.com/owncloud/core/issues/10571 and same for trashbin https://github.com/owncloud/core/issues/15646

**Comment by PVince81** [comment]
- [ ] files app list.php: still used by the file picker
- [ ] files app getstoragestats: https://github.com/owncloud/core/pull/26070
- [ ] files app download.php: not sure if used

**Comment by PVince81** [comment]
with [Phoenix](https://github.com/owncloud/phoenix) all of these will need to move to public APIs
