### ISSUE TITLE
fresh ownCloud install will silently delete local directory contents

### ISSUE THREAD

**Issue by law** [owncloud/core#13006]
Clients - 1.7.0b1339, on Mac OS X Yosemite (Macbook Air, and Macbook Pro)
Server - originally Ubuntu 12.04 w/ ownCloud 7.0.3-1, reformatted to Ubuntu 14.04 w/ ownCloud 7.0.4-3
     
Putting this to Core, even though it may eventually end up in Client.  Apologies in advance if this is the case.  

Originally, ownCloud was installed on my server with the application itself in /var/www/owncloud and the data directory in /var/storage/owncloud, from the opensuse.org repos.  /var and /var/storage were their own LVM LVs, pointing to separate RAID 1 arrays.  About a week ago, the /var/storage LVM went permanently offline, relating to some LVM issues stemming back six months ago with power outages, etc.  Since it 'only' held the ownCloud data store, and all the data was on various laptops, this was not a major issue.  I resolved to reformat the box rather than pick around LVM trying to resolve UUID issues, and in the interim my owncloud clients were running, they just weren't syncing (expected behavior, since the /var/storage/ LVM was offline and /var/storage/owncloud{/data} etc no longer existed.  The /var/www/owncloud directory, /etc/apache2/sites-enabled/owncloud file, and a dump of the owncloud MySQL database were all backed up to external USB, and the reformat proceeded.   
     
The reformat/reinstall went smoothly.  The opensuse.org repos were used, this time pointing to 14.04 instead of the previous 12.04, mysql db dump restored, and the original /var/www/owncloud/config/config.php copied over to the new install.  Apache started, owncloud found the new /var/storage/owncloud directory, and the clients (running but not syncing this whole week) began syncing automatically.  
     
The first clue something was wrong was when the clients began complaining of a 'case mismatch' between ~/ownCloud/music and ~/ownCloud/Music.  Syncing would pause for a few seconds, then resume.  Checking /var/storage/owncloud/data/law/ I expected to see my files in the process of being uploaded, but instead only saw the documents/ music/ photos/ etc directories of a fresh install.  At that point I killed the owncloud client on my laptops, stopped apache on the server, and went to IRC for assistance.  So far, 36 hours in and $200 in recovery software poorer, no data has been able to be recovered.

**Comment by MorrisJobke** [comment]
The problem here seems to be the reinstall of owncloud with the database dump of the old instance. The DB dump holds the info about files, that are present on the filesystem too. So it thought everything is in place, which wasn't the case because you added a completely clean filesystem. 

I don't think, that we support a way of recovering from that point (partial backed up data). The only way I can imagine is that you loose all your shares and start syncing to a completely fresh installation without the old dump.

Therefore I will close this ticket.

**Comment by law** [comment]
Thanks for taking a look, Morris.  Perhaps this would warrant a 'don't do that' bullet somewhere in the ownCloud administrators guide?  As a user, I would've thought the data would flow from the client to the server, not the opposite.

**Comment by MorrisJobke** [comment]
@carlaschroder Can we add such stuff to the documentation?

Something like "don't restore a owncloud installation (DB dump) if you don't have the content of the data dir too, because the DB claims that there is something in the data dir"
