### ISSUE TITLE
Newsapp "recommended" in fresh install, but can't be installed due to code checker

### ISSUE THREAD

**Issue by menelic** [owncloud/core#13018]
I just installed a fresh Ownccloud instance on a CentOS VPS and was happy to see that one of my favourite apps now comes "recommeded" in the app section. I was also glad to see that teh description provided is the latest one which descibes news as an oc 8 preview that should now be installable on 7.0.4 without code checker issues. However, after clicking enable I got:

App can't be installed because of not allowed code in the App

I assume this to be code checker output.

I know there have been lengthy discussions about the code checker, and I am aware of the apps repo but I m putting this hee because this is also a ux and curatorial issue- why would the only app that has a recommeded label in a fresh install not be installable? New users cannot possibly understand this. 

That said, I obviously think that it should be installable. Thanks @Raydiation for a great app, I hope teh curators of the "recommended" tag will be of help in fixing this in a way that the app can stay recommended because it actially installs.

**Comment by karlitschek** [comment]
Hmmm. I can´t reproduce that. The news app shows up for me as Recommended in 8/git master but not on 7.0.4
@menelic Can you provide some more information here? Have you ever used 8.0 alpha or git?

**Comment by Raydiation** [comment]
Closing this because it is not reproducable and inactive
