### ISSUE TITLE
Hige idle cpu when external storage is added

### ISSUE THREAD

**Issue by prilly** [owncloud/core#13019]
it seems my owncloud install has some problems with hige cpu usage when adding external storage in the gui. i have tried with both cifs, ftp and sftp and all 3 types generates steady hige cpu usage all the time the share is mounted. removing the external storage and cpu usage returns to normal.

debian 7 wheezy
owncloud 7
openfiler as external storage (cifs,ftp and sftp)

**Comment by PVince81** [comment]
The scanner has been moved to a background job (cron) in 9.0, so while it might still use CPU for the actual scanning task, it won't be triggered when a user is inactive in the web browser.
