### ISSUE TITLE
Existing files on one side deleted after sync

### ISSUE THREAD

**Issue by christianrj** [owncloud/core#13024]
### Steps to reproduce
I don't know exactly how to reproduce this bug. The story is this:

We have a windows file server with Owncloud client installed to sync to the cloud. All files on the file server are shared with an owncloud account, that serves as a backup on another machine.

In past week, the owncloud client was disabled on the file server. The other machine was syncing as normal with the cloud.

Yesterday, we started the client on the file server. After the sync, the client deleted some files/folders on the backup machine for no reason. These deleted files are present on the file server AND in the cloud, but NOT on the backup machine.

This is all I know for now.

--------------------

### Expected behaviour
The sync must complete successfully without any strange deletions.

### Actual behaviour
Strange deletions occurred on one side of the sync.

### Server configuration
**Operating system**: CentOS 6.6 x64

**Web server:** Apache 2.2.27

**Database:** MySQL 5.5.40

**PHP version:** 5.5.19

**ownCloud version:** 6.0.6

**Updated from an older ownCloud or fresh install:** 6.0.5

**List of activated apps:** Activity,Deleted files, Share files, Versions, Disable Remember Login

**The content of config/config.php:**

```
   'instanceid' => '',
  'passwordsalt' => '',
  'trusted_domains' => 
  array (
    0 => '',
    1 => '',
    2 => '',
  ),
  'datadirectory' => '/oc/data',
  'dbtype' => 'mysql',
  'version' => '6.0.6.1',
  'dbname' => '',
  'dbhost' => '',
  'dbtableprefix' => '',
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'loglevel' => '1',
  'logdateformat' => 'd-m-Y - H:i:s',
  'logtimezone' => 'America/Sao_Paulo',
  'log_rotate_size' => 5242880,
  'mail_smtpmode' => '',
  'mail_smtphost' => '',
  'mail_smtpauth' => true,
  'mail_smtpname' => '',
  'mail_smtppassword' => '',
  'knowledgebaseenabled' => false,
  'maintenance' => false,
  'forcessl' => false,
  'updatechecker' => false,
  'default_language' => 'pt_BR',
  'theme' => '',
  'appstoreenabled' => false,
  'memcached_servers' => 
  array (
    0 => 
    array (
      0 => '',
      1 => ,
    ),
  ),
  'maxZipInputSize' => 2147483648,
  'allowZipDownload' => true,
```

**Are you using external storage, if yes which one:** local hdd.

**Are you using encryption:** no

### Client configuration
**Browser:** Chrome 39 for OSX
**Operating system:** OSX 10.10.1 Yosemite
**Owncloud Client:** 1.6.4 for OSX

#### Web server error log
```
no relevant or important logs to show
```

#### ownCloud log (data/owncloud.log)
```
http://www.hoffmann.com/downloads/owncloud_log.zip
```

#### ownCloud Client Sync log
```
http://www.hoffmann.com/downloads/owncloud_client_logs.zip
```

#### Browser log
```
no relevant or important logs to show
```

**Comment by PVince81** [comment]
Do you know if these deleted files were touched/moved ?
Has there be any time / timestamp difference between before the file server shutdown and restore ?

So if I understand well, you have 3 machines:
- an ownCloud server OC
- windows file server A, has a sync client running as user "userA" against OC
- backup server B, has a sync client running as user "userB" against OC
On the OC server, a folder (let's call it "allfiles") is shared with "userB" by "userA"
This way when both A and B run, they have the same copy of "allfiles".
Server A was shut down but B continued syncing properly.
When bringing back Server A, the sync client from B suddenly started to delete a bunch of files.
Logically, the deleted files should disappear from OC and client A should also delete these locally. Files should be gone everywhere.

However, in your last paragraph you said that the files are still present on the OC server, A but not on B ?
And B refuses to redownload these files ?

CC @dragotin @guruz

**Comment by dragotin** [comment]
Not specific enough and inactive for very long time. Closing hence.
