### ISSUE TITLE
Also closed junior jobs are shown, by following link at contribute page

### ISSUE THREAD

**Issue by radoeka** [owncloud/core#13020]
At this page http://owncloud.org/contribute/ there is the text: " (Try your hands on a a Junior Job ..."
The Junior Job refers to: https://github.com/owncloud/core/issues?labels=Junior+Job&state=open/
Due to the last slash the closed junior jobs are shown too.  Please have the last "/" removed from the url.

This will reduce the number of pages needed to display open junior jobs from an impressive 13 pages to just 3!

**Comment by nickvergessen** [comment]
Replaced by owncloud/owncloud.org#396
