### ISSUE TITLE
Document preview providers not supported on windows in config/config.sample.php

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#13038]
Hi,

as a follow up of: https://github.com/owncloud/documentation/issues/422

OC is still lacking a lot of infos what is unsupported on windows. This includes the (now disabled) office and movie providers:

https://github.com/owncloud/core/blob/75e8b39826c9278288b8dc02dc19f0ca060080b6/lib/private/preview.php#L784-L785
https://github.com/owncloud/core/blob/75e8b39826c9278288b8dc02dc19f0ca060080b6/lib/private/preview.php#L809-L811

In my opinion this should be at least documented in the config/config.sample.php (OC7 and OC8). 

Personally i don't care about Windows but such infos could save a lot of support work trying to find a solution for a problem which can't be solved when running on Windows.

**Comment by carlaschroder** [comment]
https://github.com/owncloud/core/pull/13365

**Comment by DeepDiver1975** [comment]
refs  #13375

**Comment by carlaschroder** [comment]
I am totally confused. Is this fixed now and we can close this?

**Comment by LukasReschke** [comment]
![49198b66e46c653087e29200320a7e56ce11d5b8e7c320f1e856a046f364745a](https://cloud.githubusercontent.com/assets/878997/5785834/1bbf4958-9ddc-11e4-9de4-5f16840579b3.jpg)

@MorrisJobke's magical script will update the according documentation from the sample config.

**Comment by carlaschroder** [comment]
![grumpycat-good](https://cloud.githubusercontent.com/assets/8388387/5786611/ed9a8c66-9d9c-11e4-86b5-0027df2c7984.jpg)

**Comment by MorrisJobke** [comment]
![x95tsz jpg](https://cloud.githubusercontent.com/assets/245432/5788249/a99b0566-9e2a-11e4-928f-3846593886f2.jpg)
