### ISSUE TITLE
Error in log: OC_Image->fixOrientation() Exif module not enabled.

### ISSUE THREAD

**Issue by radoeka** [owncloud/core#13037]
Obtained the following error in owncloud log:

Debug	core	OC_Image->fixOrientation() Orientation: -1	2014-12-26T13:03:15+00:00
Debug	core	OC_Image->fixOrientation() Exif module not enabled.	2014-12-26T13:03:15+00:00
Debug	core	Generating preview for "/some-song.mp3" with "OC\Preview\MP3"

Looks a module is not present.  I installed php5_exif, assuming that this is the missing module.  
Shouldn´t OC be checking for this module at:
  http://<server>/owncloud/index.php/settings/admin

OC: 7.0.4
Owncloud from openSUSE rpms.
Linux: 3.11

### Steps to reproduce
Unclear, probably uploading an mp3 without image.

### Expected behaviour
The missing php_exif module is displayed at the Admin page, and is shown in red or green depending on whether it is missing or installed.

### Actual behaviour
There is no check for the php_exif module, and its status is not displayed at the admin page.

### Server configuration
**Operating system**: Linux

**Web server:** Apache

**Database:** sqlite3

**PHP version:** 5.4.20

**ownCloud version:** 7.0.4

**Updated from an older ownCloud or fresh install:** Updated

**Comment by PVince81** [comment]
Are you still seeing this issue with OC 8.2.2 ?

**Comment by radoeka** [comment]
I don't see it anymore at 8.2.2
