### ISSUE TITLE
Sharing options do not show up 

### ISSUE THREAD

**Issue by Guyome** [owncloud/core#13032]
I only get the search box when I try to share a content (file, calendar, event).

![error](https://cloud.githubusercontent.com/assets/77540/5557046/cd3235fe-8cef-11e4-8d96-adb413f7490d.png)

In my lighttpd log, I find:

```"GET /index.php/core/ajax/share.php?fetch=getItem&itemType=file&itemSource=1167&checkReshare=true&checkShares=true HTTP/1.1" 200 68 "https://xxxx.xxxxx.net/index.php/apps/files/"```

The url returns the token_expired error when I open it .
``` {"data":{"message":"La session a expir\u00e9. Veuillez recharger la page.","error":"token_expired"},"status":"error"}```

I run a fresh install of the owncloud 7.0.4.2 with user_otp installed.

Is there any  way to work out this ? Thanks in advance.

PHP 5.5.9/ubuntu 14.04/lighttpd 1.4.33 (ssl).

**Comment by PVince81** [comment]
@Guyome are you still seeing this issue on 8.0.5 or 8.1 ?
Note that Sabre has been updated in 8.1.
