### ISSUE TITLE
Web components for apps

### ISSUE THREAD

**Issue by BernhardPosselt** [owncloud/core#13036]
This is just brainstorming.

If you are writing an app there are many UX things that you have to consider and a lot of JavaScript that you need to add to wire up all the navigation logic:
- Add a new entry/folder
  - Default caption
  - Default icon
  - No counter and no menu
  - Body should slide down on click
  - Body should hide on focus lost
  - Autofocus input field
- Navigation list
  - Can have an icon or no icon for entries
- Navigation list folders
  - Default icon
  - Has a button to toggle the open/closed state if it has folders
  - Serves as a target to drop entries
- Navigation list entries
  - Can be dragged to a folder
    Navigation list entries/folders
  - Have titles
  - Can have actions 
    - Actions should be shown as popup on click 
    - Action should hide on focus lost
    - Can have edit action
    - Can have delete action
    - Should show tipsy hints when hovering over icon
  - Can have integer counters (999+ if over 999)
  - Can be deleted (default delete action)
    - Should show the undo entry on delete
    - Should time out and hide the undo entry after x seconds
  - Can be edited
    - Autofocus input field
    - Input should default to entry title
- Settings area:
  - Default button and caption
  - Body should slide down on click
  - Body should hide on focus lost

ATM this is a ton of logic that every app dev has to implement by himself which is not only a lot of work but may also lead to UX inconsistencies across apps or simply be left out because its too much work. Although web components are not widely supported yet we should start thinking about a component API and have a default reference implementation. This can be backported/polyfilled by custom js libraries afterwards (angular, polymer, etc)

@jancborchardt @MorrisJobke @DeepDiver1975 @nickvergessen @georgehrke @LEDfan @jbtbnl

**Comment by jbtbnl** [comment]
I agree with @karlitschek that enforcing a complete framework is not desirable, but web components do not.

I've done some reading on the web components as suggested by @Raydiation and they are basically a neat way of separating elements (consisting of HTML, CSS and JavaScript) and their dependencies into small, maintainable pieces of code. I'm really looking forward to this as a replacement for the jQuery listeners that are literally all over the place.

**Comment by jancborchardt** [comment]
@BernhardPosselt aren’t these components already in what you already added to https://doc.owncloud.org/server/9.0/developer_manual/app/css.html ? If not, could you please add those? :)

**Comment by PVince81** [comment]
@felixheidecke would UI kit be suitable for this purpose ?

**Comment by PVince81** [comment]
PR for introducing UI Kit: https://github.com/owncloud/core/pull/29815

**Comment by felixheidecke** [comment]
components are easily realized with based on vue's component structure. Together with Uikit this makes for nice, reusable components.
