### ISSUE TITLE
oc 7.0.3 / files "not readable" within desktop sync, but ok within web interface

### ISSUE THREAD

**Issue by johan27hack** [owncloud/core#13044]
Hello,

PROBLEM : 

I'm having oc 7.0.3 running perfecly with desktop sync (Pc and mac) without no problem.

But, since a few weeks now, without having do anything special to my server, if I sync a file within a desktop software (pc or mac), it will be not readable within any other desktop sync, but the file will be 100% ok within the web interface !!

Windows 7 Pro 64 with program OC 1.7.0
Mac 10.9.5 with program OC 1.7.0
Windows 8.1 Pro 64 with program OC 1.6.4

I tried also with the last version of program 1.7.1, but nothing else.

I tried anything :
Files will always be ok within the web interface
But still corrupted within any sync program.

I don't know if it's related, but I have this problem since the day I put some datas in the "shared" folder next to "clientsync" folder .
In fact, it was a kind of old folder from my first installation of OC 5.x
But even now I deleted this "shared" problem, I have this problem of some "un readable" files ..

I post it this problem here since nobody can help me inside the OC forum.

Thanks for any help

OC: 7.0.3
Linux nsxxxxx.ovh.net 3.2.13-grsec-xxxx-grs-ipv6-64 #1 SMP Thu Mar 29 09:48:59 UTC 2012 x86_64 GNU/Linux

### Server configuration
Version DEBIAN : 6.0.10
Operating system: Linux
Web server: Apache
Database: MySQL Ver 14.14 Distrib 5.1.73
PHP Version 5.4.36-1~dotdeb.0
ownCloud version: 7.0.3
Updated from an older ownCloud or fresh install: Updated from OC 5 -> OC 6 -> OC7 regularly

**List of activated apps:**
actually, the OC 7 server is set by default, nothing more.

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '5165c50f134c1',
  'passwordsalt' => 'xxxxxxxxxxxxxxxxxx',
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.3.4',
  'installed' => true,
  'forcessl' => true,
  'maintenance' => false,
  'trashbin_retention_obligation' => 60,
  'trashbin_auto_expire' => true,
  'loglevel' => '0',
  'log_rotate_size' => 54857600,
  'theme' => 'theme-jolinuage',
  'trusted_domains' => 
  array (
    0 => 'mon.domaine.fr',
  ),
  'share_folder' => '/Shared',
  'mail_from_address' => 'notification',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'domaine.fr',
  'dbname' => 'dbname',
  'dbhost' => '127.0.0.1',
  'dbuser' => 'xxxxxx',
  'dbpassword' => 'xxxxxxxx',
);

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:**
No

### Client configuration
**Browser:**
Firefox last version
**Operating system:**
Win 7 Pro 64 bits

#### Web server error log
```
Which file(s) do you need ?
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"547467cfbaab1","app":"webdav","message":"Sabre\\DAV\\Exception\\NotAuthenticated: No basic authentication headers were found","level":0,"time":"2014-11-25T11:28:15+00:00","method":"PROPFIND","url":"\/remote.php\/webdav"}
{"reqId":"5474680c1d111","app":"webdav","message":"Sabre\\DAV\\Exception\\NotAuthenticated: No basic authentication headers were found","level":0,"time":"2014-11-25T11:29:16+00:00","method":"PROPFIND","url":"\/remote.php\/webdav"}
{"reqId":"5474680e57d76","app":"OC\\Files\\Cache\\Scanner","message":"!!! No reuse of etag for 'files\/clientsync\/HDD TESTS' !!! \ncache: Array\n(\n    [fileid] => 208482\n    [storage] => local::\/var\/www\/owncloud\/data\/johan\/\n    [path] => files\/clientsync\/HDD TESTS\n    [parent] => 6\n    [name] => HDD TESTS\n    [mimetype] => httpd\/unix-directory\n    [mimepart] => httpd\n    [size] => 0\n    [mtime] => 1416914957\n    [storage_mtime] => 1416914957\n    [encrypted] => \n    [unencrypted_size] => 0\n    [etag] => 5474680d6bb38\n    [permissions] => 31\n)\n \ndata: Array\n(\n    [mimetype] => httpd\/unix-directory\n    [mtime] => 1416914958\n    [size] => -1\n    [etag] => 5474680e57bad\n    [storage_mtime] => 1416914958\n    [permissions] => 31\n    [parent] => 6\n)\n","level":0,"time":"2014-11-25T11:29:18+00:00","method":"PUT","url":"\/remote.php\/webdav\/clientsync\/HDD%20TESTS\/2%20-%20CrystalDiskInfo.lnk"}
{"reqId":"5474680e5b03b","app":"OC\\Files\\Cache\\Scanner","message":"!!! No reuse of etag for 'files\/clientsync\/HDD TESTS' !!! \ncache: Array\n(\n    [fileid] => 208482\n    [storage] => local::\/var\/www\/owncloud\/data\/johan\/\n    [path] => files\/clientsync\/HDD TESTS\n    [parent] => 6\n    [name] => HDD TESTS\n    [mimetype] => httpd\/unix-directory\n    [mimepart] => httpd\n    [size] => 0\n    [mtime] => 1416914957\n    [storage_mtime] => 1416914957\n    [encrypted] => \n    [unencrypted_size] => 0\n    [etag] => 5474680d6bb38\n    [permissions] => 31\n)\n \ndata: Array\n(\n    [mimetype] => httpd\/unix-directory\n    [mtime] => 1416914958\n    [size] => -1\n    [etag] => 5474680e5ae15\n    [storage_mtime] => 1416914958\n    [permissions] => 31\n    [parent] => 6\n)\n","level":0,"time":"2014-11-25T11:29:18+00:00","method":"PUT","url":"\/remote.php\/webdav\/clientsync\/HDD%20TESTS\/3%20-%20CrystalDiskMark.lnk"}
{"reqId":"54746813214d6","app":"OC\\Files\\Cache\\Scanner","message":"!!! No reuse of etag for 'files\/clientsync\/HDD TESTS\/1 - Hard Disk Wipe Tool.lnk' !!! \ncache: Array\n(\n    [fileid] => 208483\n    [storage] => local::\/var\/www\/owncloud\/data\/johan\/\n    [path] => files\/clientsync\/HDD TESTS\/1 - Hard Disk Wipe Tool.lnk\n    [parent] => 208482\n    [name] => 1 - Hard Disk Wipe Tool.lnk\n    [mimetype] => application\/octet-stream\n    [mimepart] => application\n    [size] => 1012\n    [mtime] => 1416914959\n    [storage_mtime] => 1416914959\n    [encrypted] => \n    [unencrypted_size] => 0\n    [etag] => 5474681052f67\n    [permissions] => 27\n)\n \ndata: Array\n(\n    [mimetype] => application\/octet-stream\n    [mtime] => 1415724144\n    [size] => 1012\n    [etag] => 547468132123a\n    [storage_mtime] => 1415724144\n    [permissions] => 27\n    [parent] => 208482\n)\n","level":0,"time":"2014-11-25T11:29:23+00:00","method":"PUT","url":"\/remote.php\/webdav\/clientsync\/HDD%20TESTS\/1%20-%20Hard%20Disk%20Wipe%20Tool.lnk"}
{"reqId":"5474680e57d76","app":"OC\\Files\\Cache\\Scanner","message":"!!! No reuse of etag for 'files\/clientsync\/HDD TESTS\/2 - CrystalDiskInfo.lnk' !!! \ncache: Array\n(\n    [fileid] => 208484\n    [storage] => local::\/var\/www\/owncloud\/data\/johan\/\n    [path] => files\/clientsync\/HDD TESTS\/2 - CrystalDiskInfo.lnk\n    [parent] => 208482\n    [name] => 2 - CrystalDiskInfo.lnk\n    [mimetype] => application\/octet-stream\n    [mimepart] => application\n    [size] => 1190\n    [mtime] => 1416914959\n    [storage_mtime] => 1416914959\n    [encrypted] => \n    [unencrypted_size] => 0\n    [etag] => 5474681114439\n    [permissions] => 27\n)\n \ndata: Array\n(\n    [mimetype] => application\/octet-stream\n    [mtime] => 1415724165\n    [size] => 1190\n    [etag] => 54746813ca4db\n    [storage_mtime] => 1415724165\n    [permissions] => 27\n    [parent] => 208482\n)\n","level":0,"time":"2014-11-25T11:29:23+00:00","method":"PUT","url":"\/remote.php\/webdav\/clientsync\/HDD%20TESTS\/2%20-%20CrystalDiskInfo.lnk"}
{"reqId":"5474680e5b03b","app":"OC\\Files\\Cache\\Scanner","message":"!!! No reuse of etag for 'files\/clientsync\/HDD TESTS\/3 - CrystalDiskMark.lnk' !!! \ncache: Array\n(\n    [fileid] => 208485\n    [storage] => local::\/var\/www\/owncloud\/data\/johan\/\n    [path] => files\/clientsync\/HDD TESTS\/3 - CrystalDiskMark.lnk\n    [parent] => 208482\n    [name] => 3 - CrystalDiskMark.lnk\n    [mimetype] => application\/octet-stream\n    [mimepart] => application\n    [size] => 1794\n    [mtime] => 1416914960\n    [storage_mtime] => 1416914960\n    [encrypted] => \n    [unencrypted_size] => 0\n    [etag] => 54746811599b5\n    [permissions] => 27\n)\n \ndata: Array\n(\n    [mimetype] => application\/octet-stream\n    [mtime] => 1415724192\n    [size] => 1794\n    [etag] => 547468147b41c\n    [storage_mtime] => 1415724192\n    [permissions] => 27\n    [parent] => 208482\n)\n","level":0,"time":"2014-11-25T11:29:24+00:00","method":"PUT","url":"\/remote.php\/webdav\/clientsync\/HDD%20TESTS\/3%20-%20CrystalDiskMark.lnk"}
{"reqId":"54746817255c5","app":"OC\\Files\\Cache\\Scanner","message":"!!! No reuse of etag for 'files\/clientsync\/HDD TESTS\/Auslogics DiskDefrag.lnk' !!! \ncache: Array\n(\n    [fileid] => 208486\n    [storage] => local::\/var\/www\/owncloud\/data\/johan\/\n    [path] => files\/clientsync\/HDD TESTS\/Auslogics DiskDefrag.lnk\n    [parent] => 208482\n    [name] => Auslogics DiskDefrag.lnk\n    [mimetype] => application\/octet-stream\n    [mimepart] => application\n    [size] => 1173\n    [mtime] => 1416914965\n    [storage_mtime] => 1416914965\n    [encrypted] => \n    [unencrypted_size] => 0\n    [etag] => 54746816047a8\n    [permissions] => 27\n)\n \ndata: Array\n(\n    [mimetype] => application\/octet-stream\n    [mtime] => 1415798263\n    [size] => 1173\n    [etag] => 54746817253bf\n    [storage_mtime] => 1415798263\n    [permissions] => 27\n    [parent] => 208482\n)\n","level":0,"time":"2014-11-25T11:29:27+00:00","method":"PUT","url":"\/remote.php\/webdav\/clientsync\/HDD%20TESTS\/Auslogics%20DiskDefrag.lnk"}
{"reqId":"5474685218f42","app":"webdav","message":"Sabre\\DAV\\Exception\\NotAuthenticated: No basic authentication headers were found","level":0,"time":"2014-11-25T11:30:26+00:00","method":"PROPFIND","url":"\/remote.php\/webdav"}
{"reqId":"547468c1711d7","app":"webdav","message":"Sabre\\DAV\\Exception\\NotAuthenticated: No basic authentication headers were found","level":0,"time":"2014-11-25T11:32:17+00:00","method":"PROPFIND","url":"\/remote.php\/webdav"}
{"reqId":"547468c3a88a9","app":"OC\\Files\\Cache\\Scanner","message":"!!! No reuse of etag for 'files_trashbin\/files\/HDD TESTS.d1416915139' !!! \ncache: Array\n(\n    [fileid] => 208487\n    [storage] => local::\/var\/www\/owncloud\/data\/johan\/\n    [path] => files_trashbin\/files\/HDD TESTS.d1416915139\n    [parent] => 172527\n    [name] => HDD TESTS.d1416915139\n    [mimetype] => httpd\/unix-directory\n    [mimepart] => httpd\n    [size] => 0\n    [mtime] => 1416915139\n    [storage_mtime] => 1416915139\n    [encrypted] => \n    [unencrypted_size] => 0\n    [etag] => 547468c304abd\n    [permissions] => 31\n)\n \ndata: Array\n(\n    [mimetype] => httpd\/unix-directory\n    [mtime] => 1416914966\n    [size] => -1\n    [etag] => 547468c3a8602\n    [storage_mtime] => 1416914966\n    [permissions] => 31\n    [parent] => 172527\n)\n","level":0,"time":"2014-11-25T11:32:19+00:00","method":"DELETE","url":"\/remote.php\/webdav\/clientsync\/HDD%20TESTS"}
{"reqId":"547468c3a88a9","app":"OC\\Files\\Cache\\Scanner","message":"!!! No reuse of etag for 'files_trashbin\/files\/HDD TESTS.d1416915139\/1 - Hard Disk Wipe Tool.lnk' !!! \ncache: Array\n(\n    [fileid] => 208488\n    [storage] => local::\/var\/www\/owncloud\/data\/johan\/\n    [path] => files_trashbin\/files\/HDD TESTS.d1416915139\/1 - Hard Disk Wipe Tool.lnk\n    [parent] => 208487\n    [name] => 1 - Hard Disk Wipe Tool.lnk\n    [mimetype] => application\/octet-stream\n    [mimepart] => application\n    [size] => 1012\n    [mtime] => 1416915140\n    [storage_mtime] => 1416915140\n    [encrypted] => \n    [unencrypted_size] => 0\n    [etag] => 547468c45e1ab\n    [permissions] => 27\n)\n \ndata: Array\n(\n    [mimetype] => application\/octet-stream\n    [mtime] => 1415724144\n    [size] => 1012\n    [etag] => 547468c52f82e\n    [storage_mtime] => 1415724144\n    [permissions] => 27\n    [parent] => 208487\n)\n","level":0,"time":"2014-11-25T11:32:21+00:00","method":"DELETE","url":"\/remote.php\/webdav\/clientsync\/HDD%20TESTS"}
{"reqId":"547468c3a88a9","app":"OC\\Files\\Cache\\Scanner","message":"!!! No reuse of etag for 'files_trashbin\/files\/HDD TESTS.d1416915139\/2 - CrystalDiskInfo.lnk' !!! \ncache: Array\n(\n    [fileid] => 208489\n    [storage] => local::\/var\/www\/owncloud\/data\/johan\/\n    [path] => files_trashbin\/files\/HDD TESTS.d1416915139\/2 - CrystalDiskInfo.lnk\n    [parent] => 208487\n    [name] => 2 - CrystalDiskInfo.lnk\n    [mimetype] => application\/octet-stream\n    [mimepart] => application\n    [size] => 1190\n    [mtime] => 1416915141\n    [storage_mtime] => 1416915141\n    [encrypted] => \n    [unencrypted_size] => 0\n    [etag] => 547468c5b8724\n    [permissions] => 27\n)\n \ndata: Array\n(\n    [mimetype] => application\/octet-stream\n    [mtime] => 1415724165\n    [size] => 1190\n    [etag] => 547468c6940da\n    [storage_mtime] => 1415724165\n    [permissions] => 27\n    [parent] => 208487\n)\n","level":0,"time":"2014-11-25T11:32:22+00:00","method":"DELETE","url":"\/remote.php\/webdav\/clientsync\/HDD%20TESTS"}
{"reqId":"547468c3a88a9","app":"OC\\Files\\Cache\\Scanner","message":"!!! No reuse of etag for 'files_trashbin\/files\/HDD TESTS.d1416915139\/3 - CrystalDiskMark.lnk' !!! \ncache: Array\n(\n    [fileid] => 208490\n    [storage] => local::\/var\/www\/owncloud\/data\/johan\/\n    [path] => files_trashbin\/files\/HDD TESTS.d1416915139\/3 - CrystalDiskMark.lnk\n    [parent] => 208487\n    [name] => 3 - CrystalDiskMark.lnk\n    [mimetype] => application\/octet-stream\n    [mimepart] => application\n    [size] => 1794\n    [mtime] => 1416915143\n    [storage_mtime] => 1416915143\n    [encrypted] => \n    [unencrypted_size] => 0\n    [etag] => 547468c738e77\n    [permissions] => 27\n)\n \ndata: Array\n(\n    [mimetype] => application\/octet-stream\n    [mtime] => 1415724192\n    [size] => 1794\n    [etag] => 547468c81a303\n    [storage_mtime] => 1415724192\n    [permissions] => 27\n    [parent] => 208487\n)\n","level":0,"time":"2014-11-25T11:32:24+00:00","method":"DELETE","url":"\/remote.php\/webdav\/clientsync\/HDD%20TESTS"}
{"reqId":"547468c3a88a9","app":"OC\\Files\\Cache\\Scanner","message":"!!! No reuse of etag for 'files_trashbin\/files\/HDD TESTS.d1416915139\/Auslogics DiskDefrag.lnk' !!! \ncache: Array\n(\n    [fileid] => 208491\n    [storage] => local::\/var\/www\/owncloud\/data\/johan\/\n    [path] => files_trashbin\/files\/HDD TESTS.d1416915139\/Auslogics DiskDefrag.lnk\n    [parent] => 208487\n    [name] => Auslogics DiskDefrag.lnk\n    [mimetype] => application\/octet-stream\n    [mimepart] => application\n    [size] => 1173\n    [mtime] => 1416915144\n    [storage_mtime] => 1416915144\n    [encrypted] => \n    [unencrypted_size] => 0\n    [etag] => 547468c8a14e1\n    [permissions] => 27\n)\n \ndata: Array\n(\n    [mimetype] => application\/octet-stream\n    [mtime] => 1415798263\n    [size] => 1173\n    [etag] => 547468c96ca44\n    [storage_mtime] => 1415798263\n    [permissions] => 27\n    [parent] => 208487\n)\n","level":0,"time":"2014-11-25T11:32:25+00:00","method":"DELETE","url":"\/remote.php\/webdav\/clientsync\/HDD%20TESTS"}
{"reqId":"547468db5ff10","app":"search_lucene","message":"file vanished, ignoring","level":0,"time":"2014-11-25T11:32:43+00:00","method":"GET","url":"\/cron.php"}
{"reqId":"547468e9a8066","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'thumbnails\/198354' is not readable !!!","level":0,"time":"2014-11-25T11:32:57+00:00","method":"GET","url":"\/index.php\/apps\/files_trashbin\/ajax\/preview.php?file=%2F%2F128.png.d1416855241&c=1416855241000"}
{"reqId":"547468e9a8066","app":"core","message":"Generating preview for \"\/\/128.png.d1416855241\" with \"OC\\Preview\\Image\"","level":0,"time":"2014-11-25T11:32:57+00:00","method":"GET","url":"\/index.php\/apps\/files_trashbin\/ajax\/preview.php?file=%2F%2F128.png.d1416855241&c=1416855241000"}
{"reqId":"547468e9a8066","app":"core","message":"OC_Image->fixOrientation() Orientation: -1","level":0,"time":"2014-11-25T11:32:57+00:00","method":"GET","url":"\/index.php\/apps\/files_trashbin\/ajax\/preview.php?file=%2F%2F128.png.d1416855241&c=1416855241000"}
{"reqId":"547468eb1d28d","app":"core","message":"OC_Image::loadFromFileHandle(): Trying","level":0,"time":"2014-11-25T11:32:59+00:00","method":"GET","url":"\/index.php\/apps\/files_trashbin\/ajax\/preview.php?file=%2F%2Fcircuit-birmanie.jpg.d1416234109&c=1416234109000"}
{"reqId":"547468eb1d28d","app":"core","message":"OC_Image->fixOrientation() No readable file path set.","level":0,"time":"2014-11-25T11:32:59+00:00","method":"GET","url":"\/index.php\/apps\/files_trashbin\/ajax\/preview.php?file=%2F%2Fcircuit-birmanie.jpg.d1416234109&c=1416234109000"}
{"reqId":"547468eb1d28d","app":"core","message":"OC_Image->fixOrientation() Orientation: -1","level":0,"time":"2014-11-25T11:32:59+00:00","method":"GET","url":"\/index.php\/apps\/files_trashbin\/ajax\/preview.php?file=%2F%2Fcircuit-birmanie.jpg.d1416234109&c=1416234109000"}
{"reqId":"547468ff0065a","app":"core","message":"OC_Image::loadFromFileHandle(): Trying","level":0,"time":"2014-11-25T11:33:18+00:00","method":"GET","url":"\/index.php\/core\/preview.png?file=%2Fclientsync%2FA-ranger%2Fcapriviera.txt&c=54737ed751281&x=36&y=36&forceIcon=0"}
{"reqId":"547468ff0065a","app":"core","message":"OC_Image->fixOrientation() No readable file path set.","level":0,"time":"2014-11-25T11:33:18+00:00","method":"GET","url":"\/index.php\/core\/preview.png?file=%2Fclientsync%2FA-ranger%2Fcapriviera.txt&c=54737ed751281&x=36&y=36&forceIcon=0"}
{"reqId":"547468ff0065a","app":"core","message":"OC_Image->fixOrientation() Orientation: -1","level":0,"time":"2014-11-25T11:33:18+00:00","method":"GET","url":"\/index.php\/core\/preview.png?file=%2Fclientsync%2FA-ranger%2Fcapriviera.txt&c=54737ed751281&x=36&y=36&forceIcon=0"}
{"reqId":"547468ff05de8","app":"core","message":"OC_Image::loadFromFileHandle(): Trying","level":0,"time":"2014-11-25T11:33:19+00:00","method":"GET","url":"\/index.php\/core\/preview.png?file=%2Fclientsync%2FA-ranger%2FBON+DE+COMMANDE+PREMIER+CATERING+001.jpg&c=547234290d71f&x=36&y=36&forceIcon=0"}
{"reqId":"547468ff05de8","app":"core","message":"OC_Image->fixOrientation() No readable file path set.","level":0,"time":"2014-11-25T11:33:19+00:00","method":"GET","url":"\/index.php\/core\/preview.png?file=%2Fclientsync%2FA-ranger%2FBON+DE+COMMANDE+PREMIER+CATERING+001.jpg&c=547234290d71f&x=36&y=36&forceIcon=0"}
{"reqId":"547468ff05de8","app":"core","message":"OC_Image->fixOrientation() Orientation: -1","level":0,"time":"2014-11-25T11:33:19+00:00","method":"GET","url":"\/index.php\/core\/preview.png?file=%2Fclientsync%2FA-ranger%2FBON+DE+COMMANDE+PREMIER+CATERING+001.jpg&c=547234290d71f&x=36&y=36&forceIcon=0"}
{"reqId":"547468ff0ad86","app":"core","message":"OC_Image::loadFromFileHandle(): Trying","level":0,"time":"2014-11-25T11:33:19+00:00","method":"GET","url":"\/index.php\/core\/preview.png?file=%2Fclientsync%2FA-ranger%2FCapture+d%E2%80%99%C3%A9cran+2014-05-01+%C3%A0+20.00.33.png&c=5472343411c0d&x=36&y=36&forceIcon=0"}
{"reqId":"547468ff0ad86","app":"core","message":"OC_Image->fixOrientation() No readable file path set.","level":0,"time":"2014-11-25T11:33:19+00:00","method":"GET","url":"\/index.php\/core\/preview.png?file=%2Fclientsync%2FA-ranger%2FCapture+d%E2%80%99%C3%A9cran+2014-05-01+%C3%A0+20.00.33.png&c=5472343411c0d&x=36&y=36&forceIcon=0"}
```

**Comment by johan27hack** [comment]
Hello all !
Happy New Year !!

Just to know if I have to update to 7.0.4 ? or do you prefer I wait until this issue's solution ?

Greeting!

**Comment by johan27hack** [comment]
Hello !!!
No one can help ?
It's weird ... a bug like this and no one can help ?? :(

**Comment by MorrisJobke** [comment]
@DeepDiver1975 Is the permission somehow saved on the server side? And if yes which one? A simply read, write, access or the full POSIX?

@dragotin @danimo Does the client somehow change permissions? How is a readonly shared folder represented?

@johan27hack I guess this is just the case for some files? Can you have a look at the files attributes (I guess on windows you have to right click and then choose 'Attributes' or something like that - I don't have an english windows here) Can you post a screenshot of the permissions of the file? And maybe also the same for the MacOS files and their permissions.

Keep in mind that it was holiday time and the people maybe enjoyed some free time with their families ;)

**Comment by johan27hack** [comment]
@MorrisJobke Hello, and thanks for your message.
Yes, please feel free to accept my apologizes for my bad behavior, but it was upsetting when no one reply :(
So I will make all the screenshot you asked by this evening .
Thanks again :)

**Comment by dragotin** [comment]
@johan27hack what do you exactly mean with "the file is not readable"?

**Comment by MorrisJobke** [comment]
@dragotin I hope I can see more permission related stuff of the filesystem within the screenshots.

**Comment by MorrisJobke** [comment]
Oh ... I just realized that it is the read permission. I thought about read-only and therefore a missing write permission.

**Comment by johan27hack** [comment]
@MorrisJobke Hello.
Like you asked me yesterday, here are 2 screenshots.
windows-permissions ==> Which is a screenshot of my png files not "readable" on my Windows 7 Pro 64 bits.
But there is something weird with the second screenshot "mac osX 10.9.5- permissions" taken from my Mac OS X 10.9.5.

I put the "windows-permissions.png" file on my oc folder, sync it over my windows desktop software.
Then I sync all the datas within my Mac OS X, and this file was not readable any more !!
Only on my MAC, still fine within my Windows ...

mac osX 10.9.5- permissions.png ==> I tried to load the windows-permissions.png, and display of the informations required.

What do you may need next ?

Greeting :)
![mac osx 10 9 5- permissions](https://cloud.githubusercontent.com/assets/4292160/5659880/e4278384-9719-11e4-8ba6-ce03d2366e65.png)
![windows-permissions](https://cloud.githubusercontent.com/assets/4292160/5659881/e42a41f0-9719-11e4-94d1-4062dae7d934.png)

**Comment by PVince81** [comment]
Ok, with "not readable" @johan27hack meant "the file is corrupted".
So this is not related to permissions.

Are you by any chance using mod_fastcgihandler ?
There were reports recently of a bug in that module causing file corruption: https://github.com/owncloud/core/issues/10984#issuecomment-65544867

**Comment by MorrisJobke** [comment]
@PVince81 Ah ... you read the error message :D :+1:

**Comment by johan27hack** [comment]
Hello @PVince81  and @MorrisJobke : Just to know if you had any news ?
:)
Have a great day ^^

**Comment by PVince81** [comment]
@johan27hack does this happen for text files as well ?
With a text file it might be possible to see how the corruption looks like (missing text blocks, etc)

**Comment by johan27hack** [comment]
@PVince81 Yes, I found some .doc with problems: Word can't read the files and ask me to convert the files to an existing format (word 14, 2007, ....)
To be exact: within the windows sync program: I can read the file, but not possible within my mac.
What datas do you need ?
Have a great day :)

**Comment by PVince81** [comment]
Hmmm I don't see why it would work on Windows but not on Mac. They're both have the same sync client software which both uses WebDAV to download files.

Did you enable additional PHP modules on your server which might try and optimize file download and/or tamper with file contents ?

Another thing to try:
`curl https://yourusername:password@yourdomain.tld/owncloud/remote.php/webdav/path/to/broken/file.doc > file.doc`
This will download the file through WebDAV, then see if "file.doc" is also corrupted when downloaded this way.
Alternatively you could just use a WebDAV client like cadaver to test this.

**Comment by johan27hack** [comment]
Hello @PVince81 : I just tried within OpenSuse 13.2 64 bits.
I have something like : 
 curl https://username:password@mon.domaine.fr/owncloud/remote.php/webdav/clientsync/Projets/template2/template2.0-détails-custom.doc > file.doc
Using Libre Office Writer, I just have the following inside the file.doc : 
---------------------------------------------------------
This application requires JavaScript for correct operation. Please enable JavaScript and reload the page.

File not found
The specified document has not been found on the server.
You can click here to return to Mon Domaine.
Company – Vos données, votre contrôle 
---------------------------------------------------------
The last line is my footer.

I will make a try later with a .doc file using a single name (no accent, or '-' or '.' or any special string).

What's next ?

**Comment by PVince81** [comment]
Next, please do try without special characters. I believe you got a 404 file not found so it just dumped the error page into the file.

**Comment by johan27hack** [comment]
Ok I will do that later on my mac @home. 
Just a question, I have the same problem with image files, but the names are standard: fond1.jpg, fond2.png ... is there any link ?

**Comment by johan27hack** [comment]
Hello,
Yesterday, I create a subfolder "TEST", with severals files.
template23TEST.doc --> not possible to read it within my mac (using Word  for Mac 2011).
slider.txt --> ok no problem.
template-fonctionnement.doc --> not possible
template-fonctionnééement - copie.doc --> not possible.
Each time it's possible, Word ask me to convert the file : 
![capture d ecran 2015-01-16 a 08 03 16](https://cloud.githubusercontent.com/assets/4292160/5772664/47bf9f2a-9d56-11e4-926c-dd56ce6deec6.png)

So what's next ?
:)

**Comment by MorrisJobke** [comment]
Could it be a problem with the underlying filesystem or disc that corrupts the file? Is there some checksum that verified the transfered file content on client side @dragotin ?

**Comment by PVince81** [comment]
There is no checksum (see checksum discussion here: https://github.com/owncloud/core/issues/12417 and here https://github.com/owncloud/core/issues/11811)

The corruption is likely to happen between the data that ownCloud sends back and the client.
We had cases where PHP modules were messing up with the contents.
But I don't understand why it would do that only for Mac.

@johan27hack can you share one of the corrupt DOC files + original DOC files with us so we can compare ? (maybe checking the difference in a hexadecimal editor to identify the kind of corruption).

**Comment by johan27hack** [comment]
Hello, and thanks for your return.
Now I was on my way to create a shared folder for you, using my Windows 7, but impossible to move to another folder the .doc "not readable on my mac".
Here is a screenshot : 
![owncloud-bug](https://cloud.githubusercontent.com/assets/4292160/5774853/e205499c-9d72-11e4-92fc-1611e094be70.png)
What do you think about it ?
The OC sync program just stay stucked when it want to delete the file in order to move it to another folder... I restarted twice my computer but still stucked at this file.
And Windows keep saying, after some minutes "this program doesn't reply" so I have to break it and restarted it !

What do you think if I upgrade the OC server to the last version ?
Or do you prefer I'm keeping this version in order to "resolve" this bug ?

**Comment by PVince81** [comment]
Can you try moving the file from the web UI instead of from the sync client ?

You might want to upgrade to 7.0.4 first in case the bug was somehow fixed already.

**Comment by johan27hack** [comment]
Yes it's working within the web UI.
But here a screenshot of my admin logs (within web UI) !!
![owncloud-bug-admin](https://cloud.githubusercontent.com/assets/4292160/5775071/85af7df4-9d75-11e4-9a31-3927e9e1ab8e.png)

**Comment by PVince81** [comment]
I see it tries to copy "bugzero-fonctionnééement - copie.doc" even though you moved the file.
This means that you actually moved the file into or out of a shared folder (cross-storage move).

But the file is not found ? Can you check if the file exists in the "data" directory of your OC instance ?

But you said the sync clients can properly download this file ? Are you able to download it from the web UI ?

**Comment by johan27hack** [comment]
Hi there,
It was working great using WINDOWS sync client, and not readable in MAC sync client.

Now: on my windows 7 pc:

- using sync client :  
--> folder: "TEST\partage" with : 
------> "template-fonctionnééement - copie.doc" : can't read it any more, Word ask me to convert is to some .doc format.
------> "template-fonctionnement-copie" : can read it  : OK.

- using web access UI :  :  
--> folder: "TEST\partage" with : 
------> "template-fonctionnééement - copie.doc" 
------> "template-fonctionnement-copie" 
I can download and read both of them with Word, without any problem .

:(

**Comment by PVince81** [comment]
Can you rename "template-fonctionnééement - copie.doc" and remove the special chars ?
If it's still broken then it's strange, as if something is messing up with WebDAV file transfer.

Are you able to try downloading these files with a WebDAV client ?

**Comment by johan27hack** [comment]
Hello,
I don't know how, but I'm pretty sure that my mac sync is making the mess ..
I rename the file and : 
--> OK within the web interface
--> Not OK within the mac sync program.

I'm planning to do the following this week end : 
- deleting the mac sync program and re install it.
- upgrade to 7.0.4 the OC server

I will tee you if the problem are still there.

Do I need to to any other actions before or during the upgrade ?

**Comment by PVince81** [comment]
I don't have any more ideas of things to try.

I'm ccing @guruz from the sync client, in case it's a known issue.

**Comment by PVince81** [comment]
@johan27hack are you still seeing this issue with ownCloud 8.0.5 or 8.1 and sync client 1.8.4 ?

**Comment by johan27hack** [comment]
I droped off owncloud a few weeks ago since these issues.

Greeting .
Jo

**Comment by PVince81** [comment]
Thanks for the feedback.
Sorry for the issues.
