### ISSUE TITLE
3rdparty: update php-opencloud

### ISSUE THREAD

**Issue by AdamWill** [owncloud/core#13051]
Upstream is up to 1.12.1, OC is still shipping 1.9.2.

Unfortunately I don't seem to have access to an OpenStack instance with working Swift (no, I'm not doing trystack until I can do it without facebook...) so I can't send a PR as I can't test it actually works, but looking at the changelog, none of the object store related changes between 1.9.2 and 1.12.1 read like they would break BC, so it may well just be a drop-in.

**Comment by PVince81** [comment]
@AdamWill you can try using devstack.
First setup an Ubuntu VM and then download the devstack shell scripts that will bootstrap a SWIFT instance.
http://docs.openstack.org/developer/devstack/guides/single-machine.html

This is how I test SWIFT.

**Comment by PVince81** [comment]
@DeepDiver1975 library update, defer to 9.0 ?

Note that it's now possible to test with a docker instance: https://github.com/owncloud/core/pull/14077

**Comment by DeepDiver1975** [comment]
9.0

**Comment by MorrisJobke** [comment]
This is tracked in https://github.com/owncloud/core/issues/20787 which shows the blocked upgrades of 3rdparty libraries due to conflicts in the supported PHP versions.
