### ISSUE TITLE
Make asset directory location configurable

### ISSUE THREAD

**Issue by AdamWill** [owncloud/core#13053]
While working on the asset compiling stuff today, I noticed it doesn't actually work with the Fedora downstream package. This is because it wants to write the assets to `\OC::$SERVERROOT . '/assets'`, but on Fedora, that's `/usr/share/owncloud/assets`, and it does not have write permissions there - it's a policy on Fedora that web apps are packaged with as many of their files as possible in `/usr/share`, as a security measure. I believe other distros take a similar approach - https://packages.debian.org/sid/all/owncloud/filelist shows the same layout. For testing purposes I just hacked up the `/usr/share/owncloud` permissions and disabled SELinux, but obviously that's not going to be a real solution :)

I'm not *absolutely* sure it's the best solution, but my first idea is to make it possible to configure the asset location. Distros could then move it to a place OC can write to (Fedora has `/var/lib/owncloud` for the purpose, where it puts user data and downloaded apps, for e.g.)

I suppose it could be argued that distributions could just come up with an approach to do the minification during package creation and ship the minified files, but that might wind up being something of an ongoing burden. Plus I guess the Assetic stuff works for apps downloaded after OC is installed? Haven't checked, but it sorta looks like it should.

I'll try and come up with a PR for this soon.

**Comment by DeepDiver1975** [comment]
has been fixed - THX

**Comment by AdamWill** [comment]
Hrm. This is odd. I just went to test this again and for some reason I run into the exception that was added by:

https://github.com/owncloud/core/pull/11593

`$filePath is not under the \\OC::$SERVERROOT`

but that seems to have been put in a while before I proposed this, so when I tested it before, I should've already been testing it against that change...hrm. Let me dig a bit more.
