### ISSUE TITLE
Upload size unit selection should automatically be saved instead of needing to press a »Save« button

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#13064]
There’s one for you @willempienaar if you want to improve that section more in following up https://github.com/owncloud/core/pull/13048 :)

**Comment by willempienaar** [comment]
Sure, I'll get on it.

**Comment by jancborchardt** [comment]
@willempienaar you’re awesome! :) Come to #owncloud-dev on IRC if you need any help.
