### ISSUE TITLE
Sync ignore files due to an unsupported charater

### ISSUE THREAD

**Issue by svecpetr** [owncloud/core#13067]
owncloud disable sync this path / filename 

"Ucetni firma/Daňové přiznání 2013/Snímek obrazovky pořízený 2014-03-30 13:34:56.png"

this is is completly UTF-8 and valid pro Windows, Linux and all UTF-8 compatible system

which character is for you incompatible ???

**Comment by Pierozi** [comment]
Problem is Owncloud Server can be runing under Windows. And for prevent any problem core team have unsupported these character. Bad news are is also unsupported when Server are under Linux.

@svecpetr look at this client issue, djbobke have publish a patch => https://github.com/owncloud/client/issues/854

My opinion is all the clients (web / linux / android...) should include a Server environement check, and then let users settings as he want.

**Comment by PVince81** [comment]
Also related: https://github.com/owncloud/core/issues/12015 (to talk about allowing support of special chars for specific storages)

**Comment by DeepDiver1975** [comment]
server 8.1 and one of the following clients (1.9 ???) will allow more characters to be uploaded -> closing
