### ISSUE TITLE
Web instalation bug LimitRequestBody

### ISSUE THREAD

**Issue by svecpetr** [owncloud/core#13065]
at web instalation setup-owncloud.php instalation didn't check value LimitRequestBody in Apache2 ... 

if is manualy set on Apache2 owncloud upload will failed with nonsense error:

Sabre\DAV\Exception\BadRequest: excepted filesize 1446783 got 491520

Why you nowhere write that LimitRequestBody 0 is required ???

**Comment by MorrisJobke** [comment]
I guess we need to update this one: https://github.com/owncloud/administration/blob/master/web-installer/setup-owncloud.php

And maybe just keep the essential checks for downloading and extracting there. All the other stuff is handled by the installer, that is already in core and there is no need to do it twice.

**Comment by MorrisJobke** [comment]
For the junior job:

* add a check for LimitRequestBody to web-installer
* add the same check to owncloud installer in `core/setup/controller.php`

**Comment by enoch85** [comment]
@ezula Something to start with? :)

**Comment by Chris-The-Tuner** [comment]
If nobody is on this one i can check this issue in the next days and fix it ;)

**Comment by MorrisJobke** [comment]
> If nobody is on this one i can check this issue in the next days and fix it ;)

@Chris-The-Tuner Doesn't seem so. Feel free to open a PR and we would be really happy :) Thanks :)
