### ISSUE TITLE
Shared folder: allow creation of subfolder by button "new"

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/core#13072]
### Steps to reproduce
1. Share a folder with link
2. Log out
3. Open link
4. Try to create folder

I have found https://github.com/owncloud/core/issues/9857#issuecomment-50129894 but this is not known by the user. And even if other browser support this there should be the same button "new" as in the "files" app, as this is know by the user.

### Expected behaviour
Visible button "new", that let me create a new folder.

### Actual behaviour
No folder possible.

### Server configuration
**Operating system**: Linux

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.3

**ownCloud version:** 7.0.2

**Updated from an older ownCloud or fresh install:** update

### Client configuration
**Browser:** Firefox

**Operating system:** Windows, Linux

**Comment by RealRancor** [comment]
Hi,

i think your linked issue/comment is not related. This is only valid if you want to upload a complete folder from your desktop/browser.

**Comment by RealRancor** [comment]
Not sure but this could be a duplicate of https://github.com/owncloud/core/issues/6635

**Comment by tobiasKaminsky** [comment]
Yes it seems so. Although the issue creater is explicitly mentioning photos.
So I am closing this in favour of #6635.

Thank you
