### ISSUE TITLE
Events in shared calendars are not sync on IPhone

### ISSUE THREAD

**Issue by Marco4223** [owncloud/core#13078]
Hi,
I have 3 User (i.e. Peter Paul and Marry) and Peter shared his calendar with Paul and Marry.
Paul and Marry are using IPhones and can create events in their own calendar and in the shared one. But they cannot see the events that made by anyone else in the shared calendar.
For thesting:
Login the Owncloud website as Paul. Create an event (called Test1) in there private calendar and one in the shared calendar of Peter (called Test2).
In the calendar of the webside ->
Test1 visible
Test2 visible
Check on IPhone ->
Test1 visible
Test2 NOT visible

In any constellation I’m not able to sync the events in shared calendar to the IPhones.

Owncloud 7.0.4
Mysql 
Php 5.4.35

Sync-Uri:
https://[my.web.uri]/owncloud/remote.php/caldav/principals/Paul/

Kind regards
Marco

**Comment by RealRancor** [comment]
Hi,

please re-open in the issue tracker of the calendar app:

https://raw.github.com/owncloud/calendar/issues

When creating the new issue it could be also usefull to use the issue template provided here:

https://raw.github.com/owncloud/core/master/issue_template.md

as asked in the "guidelines for contributing" (shown in the box when creating a new issue).
