### ISSUE TITLE
Check doctrine-dbal post-2.5.0 fixes

### ISSUE THREAD

**Issue by AdamWill** [owncloud/core#13071]
FWIW, in doing some preliminary testing of OC 8 for Fedora, I noticed that some of the post-2.5.0 commits on the 2.5 doctrine-dbal branch upstream look pretty significant, e.g.:

https://github.com/doctrine/dbal/commit/8dadeb7ebcfdb1e37e126078260eebee2e401d75
https://github.com/doctrine/dbal/commit/21a2bf6da0e82ae2bd929ae0f45b85eae8aa01b7
https://github.com/doctrine/dbal/commit/aac65338d96ce17cd423c60d4704278877848d16 (and the three subsequent commits)

For my tests instead of building a package of dbal 2.5.0 I built one for the current tip of the 2.5 branch, so far that seems to be working well.

I can't say for absolute certain whether any of these issues affect ownCloud, but it seems like it'd be a good idea for someone with greater familiarity with the database stuff to check?

**Comment by DeepDiver1975** [comment]
> doctrine/dbal@8dadeb7

Not relevant for ownCloud as we don't use foreign keys and renaming indexes is not used (generally speaking)



> doctrine/dbal@21a2bf6

hmmm - might be of interest - requires setup testing on PostgreSQL (especially creation of database) @jnfrmarks 



> doctrine/dbal@aac6533 (and the three subsequent commits)

Needs a second look - cannot judge right away

**Comment by AdamWill** [comment]
I should be able to test initial deployment and upgrade from 7.x with pgsql at least, I'll let you know how that goes.

**Comment by DeepDiver1975** [comment]
8.0.2 ships doctrine 2.5.1 -> closing
