### ISSUE TITLE
Downloading over Chrome on android does not seem to work

### ISSUE THREAD

**Issue by ovidiub13** [owncloud/core#13076]
Scenario:
**This was done using the web interface on Chromium on ArchLinux:**
Created a new folder; Uploaded a picture to the folder; Shared the folder with link.

**On Chrome on Android:**
Opened the shared link; tried to download the picture; tried to download the zip of all files.

**What actually happened:**
I started a download showing a progress with unknown time with a title `<No name>` (approximate translation) and it stays like that for ever. I'll provide a screenshot if necessary.

**What should have happened:**
Normal download should have started.

**Comment by RealRancor** [comment]
Hi,

duplicate of https://github.com/owncloud/core/issues/12694 ?

**Comment by ovidiub13** [comment]
Yes. Sorry for duplication.
