### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by alex42ka** [owncloud/core#13087]
Hi,

since one of the last updates (now it is OC 7.0.4) I get strange error messages in the admin section. It is stated that Web-DAV isn't working properly and that the server doesn't have an internet-connection. But as before the update everything is working fine (sync ...).
And of course my VServer is having an internet connection.

I've installed Owncloud on my Ubuntu 14.04 using the packages provided in the OpenSUSE build service.

What can I do?

**Comment by RealRancor** [comment]
Hi,

have a first look at this FAQ: https://forum.owncloud.org/viewtopic.php?f=17&t=7536

**Comment by alex42ka** [comment]
The Site duescribes a totally different senario from what I'm experiencing. Haven't my comments been clear enough? Do you need more information?

**Comment by RealRancor** [comment]
Hi,

> I get strange error messages in the admin section. It is stated that Web-DAV isn't working properly

which is exactly what is described in this FAQ. You could also fill out the issue template provided here:

https://raw.github.com/owncloud/core/master/issue_template.md

as asked in the "guidelines for contributing" (linked in the box shown when creating a new issue).

**Comment by nickvergessen** [comment]
@alex42ka if the linked FAQ page does not help you, feel free to open a new Issue, using the linked [Issue Template](https://raw.github.com/owncloud/core/master/issue_template.md), so we have all information we need.
