### ISSUE TITLE
Graceful synchronisation stop for oc client

### ISSUE THREAD

**Issue by oliverdo** [owncloud/core#13085]
Hi,

I’m using oc client 1.7.1 in conjunction with oc server 7.0.4 and I'm syncing sometimes quite big file 1-2 GB using this infrastructure. The oc client allows me to stop the synchronization, which stops it immediately. Sometimes I would like the oc client to finish the ongoing synchronization before stopping.

Would it be possible to get such a graceful stop of the synchronization?

Thanks
Oliver

**Comment by RealRancor** [comment]
Hi,

please re-open in the issue tracker of the sync client:

https://github.com/owncloud/client/issues

using the issue template provided here:

https://raw.github.com/owncloud/client/master/issue_template.md
