### ISSUE TITLE
A way to choose which data will be synchronizes to which client.

### ISSUE THREAD

**Issue by oliverdo** [owncloud/core#13086]
Hi,

I’m using oc client 1.7.1 in conjunction with oc server 7.0.4 and I'm syncing a lot of data between multiple clients. The data could be categorized and is sorted in folder for each category. Some of those folders are also shared with other users. The other users and I do not need each folder on each device running an oc client. 
For example the photo and the music folder are about 50 GB, the video folder is about 40 GB and of course they are not needed on any device. So is there a way to configure which data goes to which device and if so, is there a summary there I could look at this configuration?

Any ideas appreciated

Thanks
Oliver

**Comment by RealRancor** [comment]
Hi,

i think this is more something which should be handled at client-side. There you can find a similar request like: https://github.com/owncloud/client/issues/2633
