### ISSUE TITLE
Admin Recovery Password field UX issue in XGA size screen at default zoom

### ISSUE THREAD

**Issue by acesabe** [owncloud/core#13084]
There is a UX error with accessing the "Admin Recovery Password" field in the "Users" page when viewing on an XGA 1024x768 size screen, it hides behind the "Search" field and can only be accessed by enlarging the browser window beyond the horizontal width of the display.

![Image of hidden field at default zoom XGA screen](https://lh4.googleusercontent.com/-fMqKscox-O8/VKcEKfbXlHI/AAAAAAAAGa0/Cshcv8TzYAM/w702-h527-no/Hidden.oc7.png)

Suggest left side navbar dynamically scales, entry fields padding/size shrunk and "Search" field takes lower priority/not set to be on top (for tiny/tablet displays).

Applying zoom to ~75% kind of "solves" the problem, but what the default zoom/font size is on any given system is an unknown variable, but I would think the UI/UX wizards would have this one licked no?

![Image of visible field at 75%](https://lh6.googleusercontent.com/-HicgCEHhyi0/VKcEKvhAHUI/AAAAAAAAGa4/Kb6WUO9wKyc/w702-h527-no/Visible.oc7.png)

_oc7.0.4+dfsg-2 (Debian) (stable) Chromium 34.0.1847.116 / Firefox 30_

**Comment by karlitschek** [comment]
@jancborchardt @blizzz What do you think?

**Comment by jancborchardt** [comment]
@blizzz The recovery password isn’t used that often, is it? We should put it in the bottom left settings area, or only prompt for it when needed. It has no place in the top bar.
