### ISSUE TITLE
Opening the "admin" page shown the "apps" app as active in the navigation menu

### ISSUE THREAD

**Issue by arkascha** [owncloud/core#13090]
in OC-7.0.4, when opening the "admin" page as an administrator I expect to get an admin page. 
The content is fine, but the navigation menu claims that this is the "apps" page I am look at, which clearly is wrong. 
A technical reason might be that there is no "admin" entry in the navigation menu, and one entry has to be active there. But that is not really satisfying. To me the visualization is confusing, though this certainly is not a big thing.

**Comment by radoeka** [comment]
Related to #8160

**Comment by MorrisJobke** [comment]
@jancborchardt Wasn't this by purpose?

**Comment by MorrisJobke** [comment]
The brown labels are for backported fixes (and their issues). The documentation for this is currently written. Sorry for the confusion

**Comment by jancborchardt** [comment]
This is on purpose, the reasoning is explained in https://github.com/owncloud/core/issues/9356#issuecomment-47804471

> That is not the display of the active app, but signifies that you can find »Apps« behind it. You don’t reach »Personal« and »Admin« through the same dropdown as the Apps.
> Maybe we need to revise the menus for ownCloud 8 (and maybe merge user and apps menu into one or something like that) but this is intentional.
