### ISSUE TITLE
log_authfailip not documented in config.sample.php

### ISSUE THREAD

**Issue by radoeka** [owncloud/core#13094]
log_authfailip is not documented in config.sample.php (https://github.com/owncloud/core/blob/master/config/config.sample.php).

In procedures that describe how to enable for example fail2ban [1] a reference is made to the variable log_authfailip, but this variable is not mentioned in config.sample.php  

[1] Owncloud with fail2ban:
 http://www.rojtberg.net/711/secure-owncloud-server/
 https://monotok.org/prevent-brute-force-attacks-against-owncloud/

Shouldn't does variable be documented?

**Comment by RealRancor** [comment]
Hi,

this was removed some time ago: https://github.com/owncloud/core/commit/e7cea79ee7311c41c5f95082cba6e75e0236beac and is always "enabled".

**Comment by radoeka** [comment]
OK.  That's even better :)
