### ISSUE TITLE
Refactoring of Provisioning_API

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#13092]
Non exhaustive list of improvements: 
- [ ] Remove usage of deprecated methods
- [ ] Implement dependancy injection
- [ ] Make use of data providers in test cases

Nice to have (debatable priority)(probably separate refactoring stage):
- [ ] Use HTTP error codes

**Comment by PVince81** [comment]
Tech debt refactor, we're past feature freeze => 9.0

**Comment by DeepDiver1975** [comment]
@rullzer you already did some in this area - finished? close? THX

**Comment by rullzer** [comment]
No it is not fully done yet. But we are getting there.

**Comment by DeepDiver1975** [comment]
> No it is not fully done yet. But we are getting there.

please tick what has been done - thx

**Comment by rullzer** [comment]
the code checker gives us:

```
Analysing /home/roeland/owncloud/test/core/apps/provisioning_api/lib/apps.php
 5 errors
    line   29: OC_App - private class must not be imported with a use statement
    line   48: OC_App - Static method of private class must not be called
    line   57: OC_App - Static method of private class must not be called
    line   60: OC_App - Static method of private class must not be called
    line   82: OC_App - Static method of private class must not be called
Analysing /home/roeland/owncloud/test/core/apps/provisioning_api/lib/users.php
 4 errors
    line   31: OC_Helper - private class must not be imported with a use statement
    line  537: OC_Util - Static method of private class must not be called
    line  538: OC_Util - Static method of private class must not be called
    line  539: OC_Helper - Static method of private class must not be called
```

Which needs to be fixed. But probably require adding some functions to OCP.

Mostly is the the `app` listing/testing of the provisiong API that needs love. User/Group are alsmost fully over on DI, and use only pure unit tests for testing (intergration tests are done via the OCS Intergration tests).

**Comment by PVince81** [comment]
no time for this now... -> backlog
