### ISSUE TITLE
File replacement modal too wide on mobile

### ISSUE THREAD

**Issue by githubrsys** [owncloud/core#13102]
# Summary / actual behaviour

Uploading multiples images with iPhone in files module not possible because the 'confirmation dialogue' for overwriting files cannot be used as expected. There's not enought room for seeing the full dialogue box.
# Way to reproduce
- FE Login with iPhone 4 / 5 / 6 -> Files module -> upload multiple Images 
- Try to Upload 3 or 4 Images
- As of an Issue in iOS there's always an image uploaded as image.jpg but can be automatically renamed in OC if 'dialogue box' is checked and confirmed
- This 'confirmation box' is not accessible on these devices due an CSS issue.
# Expected behaviour
- Ability to confirm the box.
### Labels

[DESIGN] [BUG] [SEV2-HIGH]  -> because it breaks usability in this usecase
### CC's

@owncloud/designers
## Screenshot

![photo-2015-01-03-13-52-30_0328](https://cloud.githubusercontent.com/assets/716689/5613060/b767b0c2-94de-11e4-897e-195eba833027.PNG)

**Comment by githubrsys** [comment]
Screenshot added
![photo-2015-01-03-13-52-30_0328](https://cloud.githubusercontent.com/assets/716689/5611419/aeaf377e-94c6-11e4-9ced-96737bb31833.PNG)

**Comment by MorrisJobke** [comment]
cc @owncloud/designers @butonic

**Comment by DeepDiver1975** [comment]
@jancborchardt can you please have a look? THX

**Comment by DeepDiver1975** [comment]
moving to 9.1 - we first need the files app operating on top of webdav

**Comment by jancborchardt** [comment]
And then @butonic @PVince81 the priority is to have the simple replacement dialog before this one. There was a related issue but I can’t find it atm.

**Comment by butonic** [comment]
@jancborchardt @PVince81 Um implemented in https://github.com/owncloud/core/pull/19417?

**Comment by PVince81** [comment]
Might be possible to simplify the dialog using pure CSS in mobile.css, basically remove the previews and the panels. Or change the layout and make them appear differently.

**Comment by PVince81** [comment]
Moved to general design issues group ticket: https://github.com/owncloud/core/issues/27578
