### ISSUE TITLE
Error log is flooded with "Accessing the server container is deprecated. Use type annotations to inject core services instead!"

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#13106]
"Accessing the server container is deprecated. Use type annotations to inject core services instead!" is flooding the error log even if the warn-level is set to the default "Warnings, errors and fatal issues"

Introduced with https://github.com/owncloud/core/commit/f1951237653ffbbf7fd75f815f401783658cec5e which was merged with https://github.com/owncloud/core/pull/12830

That message should be an info and not a warning. - That's something developers should care about, not  administrators of an ownCloud instance.

@DeepDiver1975 @Raydiation

**Comment by LukasReschke** [comment]
To reproduce this just install the new beta and look at the log file…

**Comment by Raydiation** [comment]
Can you create a fix? The lines are here:
* https://github.com/owncloud/core/blob/master/lib/private/appframework/dependencyinjection/dicontainer.php#L204
* https://github.com/owncloud/core/blob/master/lib/private/appframework/dependencyinjection/dicontainer.php#L225

Either remove them or change it to debug

**Comment by LukasReschke** [comment]
See https://github.com/owncloud/core/pull/13107
