### ISSUE TITLE
Config file is checked multiple times with different checks

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#13104]
From https://github.com/owncloud/documentation/issues/731#issuecomment-68475011:

<hr/>

Oh fun, oh fun.

What happens here is that our awesome code-base has the "is config writable check" in at least three different places and the logic is all different - yay.
1. A check in `lib/private/config.php` whether the file `config/config.php` exists (https://github.com/owncloud/core/blob/c36bac3abdd4b41620bdebbc3391612aac620fb8/lib/private/config.php#L172-L178)
2. A  check in `lib/base.php` whether the file `config/config.php` is writable or the read-only mode is set (https://github.com/owncloud/core/blob/891474b0d6b8cc77a8480cd91f1e48ad3bc3e73b/lib/base.php#L198-L216)
3. A check in `lib/private/util.php` which checks whether the config _directory_ is writable. The even more funny thing here is that this code path is only called for new sessions, thus all existing sessions will work happily but as soon as you start a new one things will explode.(https://github.com/owncloud/core/blob/aec79b0c0ec7a6520a99261ed426d7ac621d2d2e/lib/private/util.php#L509-L516)

For the sake of having an usable documentation I'd say that we adjust the documentation for now and in the future unify these insane checks somehow in core - but that is unrelated… No need to have them at three different places and also no need to be different everywhere. Especially the third check is really some magic voodoo which abuses the session storage totally ;-)

<hr/>

Related to https://github.com/owncloud/core/issues/11843

**Comment by MorrisJobke** [comment]
see also #13736

**Comment by PVince81** [comment]
Did we make any progress here, even small ?
