### ISSUE TITLE
Enable app for group doesn't autocomplete anymore

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#13105]
* try to enable app for specific group only by clicking the checkbox on the app management page for text editor for example
* focus the input
* spinner appears and nothing is displayed even if I typed in the full group name

cc @DeepDiver1975 @jancborchardt

**Comment by jancborchardt** [comment]
Any errors in the console or owncloudlog?

**Comment by MorrisJobke** [comment]
@jancborchardt Nothing. Even the requests are sent. Maybe I will debug this later
