### ISSUE TITLE
Files in files_versions not being deleted when they should

### ISSUE THREAD

**Issue by chemnic** [owncloud/core#13117]
## Steps to reproduce

1. Existing user with unlimited quota and ~50GB of images
2. Reduce all images file size. i. e. Modify all images in some way.
3. data/user/files_verions are filled with 50GB
4. Change user quota to 18GB
5. User now has ~5GB of free space
6. Wait 3 weeks

## Expected behaviour

Owncloud should remove most of those 50GB on user's files_versions directory, as described in http://doc.owncloud.org/server/7.0/user_manual/files/versioncontrol.html

## Actual behaviour

data/user/files_versions keeps filled with those 50GB after 3 weeks. 

## Server configuration

Operating system: Ubuntu 12.04 (Container OpenVZ / Proxmox)

Web server: Apache 2.2.22

Database: MySql 5.5.40

PHP version: 5.4.36

ownCloud version: 7.0.4 (stable)

Installed since version 6

List of activated apps:

- Activity
- Deleted files
- Documents
- First Run Wizard
- Full Text Search
- ownCloud dependecies info
- ODF Viewer
- Pictures
- Share Files
- Text Editor
- Updater
- Versions
- Video Viewer
- Videos

## Config/config.php:

<?php
$CONFIG = array (
  'instanceid' => 'oc7ad26eb688',
  'passwordsalt' => 'nottherealpasswordsalt',
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.4.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'nottherealdbpassword',
  'installed' => true,
  'loglevel' => '3',
  'theme' => '',
  'maintenance' => false,
  'forcessl' => true,
  'overwritewebroot' => '/owncloud',
  'trusted_domains' => 
  array (
    0 => 'nube.example.com',
    1 => 'nube.example.locald',
  ),
  'secret' => 'nottherealsecret',
);

## Apache log:

[Sat Jan 03 12:39:10 2015] [notice] caught SIGTERM, shutting down
[Sat Jan 03 12:39:22 2015] [warn] RSA server certificate CommonName (CN) `localhost.localdomain' does NOT match server name!?
[Sat Jan 03 12:39:23 2015] [warn] RSA server certificate CommonName (CN) `localhost.localdomain' does NOT match server name!?
[Sat Jan 03 12:39:23 2015] [notice] Apache/2.2.22 (Ubuntu) mod_fcgid/2.3.6 PHP/5.4.36-1+deb.sury.org~precise+2 mod_ssl/2.2.22 OpenSSL/1.0.1 configured -- resuming normal operations
[Sat Jan 03 13:02:24 2015] [notice] caught SIGTERM, shutting down
[Sat Jan 03 13:28:55 2015] [warn] RSA server certificate CommonName (CN) `localhost.localdomain' does NOT match server name!?
[Sat Jan 03 13:28:59 2015] [warn] RSA server certificate CommonName (CN) `localhost.localdomain' does NOT match server name!?
[Sat Jan 03 13:28:59 2015] [notice] Apache/2.2.22 (Ubuntu) mod_fcgid/2.3.6 PHP/5.4.36-1+deb.sury.org~precise+2 mod_ssl/2.2.22 OpenSSL/1.0.1 configured -- resuming normal operations
[Sun Jan 04 04:53:01 2015] [notice] Graceful restart requested, doing restart

[Sun Jan 04 04:53:01 2015] [warn] RSA server certificate CommonName (CN) `localhost.localdomain' does NOT match server name!?
[Sun Jan 04 04:53:01 2015] [notice] Apache/2.2.22 (Ubuntu) mod_fcgid/2.3.6 PHP/5.4.36-1+deb.sury.org~precise+2 mod_ssl/2.2.22 OpenSSL/1.0.1 configured -- resuming normal operations

## ownCloud log:

{"app":"PHP","message":"unlink(\/var\/www\/owncloud\/data\/jpcabrales\/files_versions\/Reportes de caja\/Julio 2014\/Reporte de recibos 31-07-14.xls.v1406827184): No such file or directory at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#167","level":3,"time":"2014-12-29T13:34:56+00:00"}
{"app":"PHP","message":"unlink(\/var\/www\/owncloud\/data\/jpcabrales\/files_versions\/Adelantos de salario\/adelantos de salario.xls.v1408038681): No such file or directory at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#167","level":3,"time":"2014-12-29T13:34:56+00:00"}
{"app":"PHP","message":"unlink(\/var\/www\/owncloud\/data\/jpcabrales\/files_versions\/Reportes de caja\/Agosto 2014\/INFORME DE CAJA  15-08-14.xls.v1408111407): No such file or directory at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#167","level":3,"time":"2014-12-29T13:34:56+00:00"}
{"app":"PHP","message":"unlink(\/var\/www\/owncloud\/data\/jpcabrales\/files_versions\/Reportes de caja\/Agosto 2014\/INFORME DE CAJA  20-08-14.xls.v1408577039): No such file or directory at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#167","level":3,"time":"2014-12-29T13:34:56+00:00"}
{"app":"PHP","message":"unlink(\/var\/www\/owncloud\/data\/jpcabrales\/files_versions\/Presupuesto.ods.v1409956081): No such file or directory at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#167","level":3,"time":"2014-12-29T13:34:56+00:00"}
{"app":"PHP","message":"unlink(\/var\/www\/owncloud\/data\/jpcabrales\/files_versions\/RECIBO.ods.v1410211130): No such file or directory at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#167","level":3,"time":"2014-12-29T13:34:56+00:00"}
{"app":"PHP","message":"unlink(\/var\/www\/owncloud\/data\/jpcabrales\/files_versions\/Rendicion de cuentas.xlsx.v1411764561): No such file or directory at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#167","level":3,"time":"2014-12-29T13:34:56+00:00"}
{"app":"PHP","message":"unlink(\/var\/www\/owncloud\/data\/jpcabrales\/files_versions\/casa modelo.skp.v1416349676): No such file or directory at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#167","level":3,"time":"2014-12-29T13:34:57+00:00"}
{"app":"PHP","message":"unlink(\/var\/www\/owncloud\/data\/jpcabrales\/files_versions\/casa modelo.skp.v1418693181): No such file or directory at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#167","level":3,"time":"2014-12-29T13:34:57+00:00"}
{"app":"PHP","message":"Array to string conversion at \/var\/www\/owncloud\/lib\/private\/l10n\/string.php#57","level":3,"time":"2014-12-29T22:16:11+00:00"}
{"app":"PHP","message":"filesize(): stat failed for \/var\/www\/owncloud\/data\/jpcabrales\/files_versions\/elevacion casa bloque.skp.v1419270275 at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#117","level":3,"time":"2014-12-30T21:08:05+00:00"}
{"app":"PHP","message":"Undefined index: mime at \/var\/www\/owncloud\/apps\/files\/ajax\/mimeicon.php#4","level":3,"time":"2014-12-31T03:20:04+00:00"}

**Comment by schiesbn** [comment]
Just a guess at this point in time: Versions only get cleaned up if a new version gets created and then also only for the corresponding file. Also we will always keep the latest version as a minimum. So I wouldn't be surprised if just a lot of files with (many and large) versions wasn't modified during this three weeks.

You could test this by explicitly modify a file with some versions. If you are still above the quota all versions from this file should be deleted beside the latest version. If this works then everything works as expected for now.

Still I see the problem with this approach: Probably we need a hook if the quota was changed and then rearrange the trash and the versions from the user. But this would be quite expensive. This is something we can only do in the background or with a cron job.

**Comment by chemnic** [comment]
I see. So, ownCLoud keeps at least one version even if the files_versions directory is way bigger than the user's free space.

I changed the modification time of some of the images and the older versions are not being deleted. I used the command "touch" in the user's computer. ownCloud client syncs the new modified files and a new version is created in files_versions.

An example of a directory:

root@nube:/var/www/owncloud/data/vfmsamga/files_versions/fotos-proyectos/fotos-proyectos-lohernandez/VENTANAS# ll
total 4440
drwxr-xr-x   2 www-data www-data    4096 Jan  7 11:06 ./
drwxr-xr-x 672 www-data www-data   28672 Jan  7 12:00 ../
-rw-r--r--   1 www-data www-data 2381434 Jul 24 15:32 P1110513.JPG.v1346117998
-rw-r--r--   1 www-data www-data  417836 Oct 10 09:57 P1110513.JPG.v1405714751
-rw-r--r--   1 www-data www-data  418960 Oct 10 14:36 P1110513.JPG.v1412955983
-rw-r--r--   1 www-data www-data  416772 Oct 22 15:14 P1110513.JPG.v1412967246
-rw-r--r--   1 www-data www-data  418339 Oct 22 16:11 P1110513.JPG.v1414011583
-rw-r--r--   1 www-data www-data  418793 Jan  7 11:06 P1110513.JPG.v1414013114


In my understanding, the first and older 5 versions of that file should have been deleted already.

So, ownCloud is keeping more than one version of all this images. What am I doing wrong?

Question: is cron.php responsible for the versions clean up? I have my cron job with system cron:

root@nube:~# crontab -u www-data -l
*/15  *  *  *  * /usr/bin/php -f /var/www/owncloud/cron.php


Thank you.

**Comment by PVince81** [comment]
Here is an explanation for the version expiration logic: http://doc.owncloud.org/server/7.0/user_manual/files/versioncontrol.html?highlight=versions

Maybe at some point we should provide a way to force-clear old versions from the command line ?

**Comment by chemnic** [comment]
So, no problem with my server? Is this a bug?

**Comment by PVince81** [comment]
It is possibly a bug, yes.

Do the file name + path of the image matches the name + path of the versions ?
If the path doesn't match it could be orphaned versions (versions not attached to any file)

**Comment by PVince81** [comment]
To answer your question: no, cron doesn't clean up versions.
As @schiesbn stated here https://github.com/owncloud/core/issues/13117#issuecomment-69013698, the versions will get cleant up the next time that file changes. Only the versions of that specific file will be cleant up, not for other files.

If that didn't happen for you when you did the "touch", then it is likely a bug.

**Comment by chemnic** [comment]
I think they match:

root@nube:~# ls -lh /var/www/owncloud/data/vfmsamga/files/fotos-proyectos/fotos-proyectos-lohernandez/VENTANAS
total 416K
-rw-r--r-- 1 www-data www-data 409K Jan  7 10:34 P1110513.JPG

root@nube:~# ls -lh /var/www/owncloud/data/vfmsamga/files_versions/fotos-proyectos/fotos-proyectos-lohernandez/VENTANAS
total 4.4M
-rw-r--r-- 1 www-data www-data 2.3M Jul 24  2014 P1110513.JPG.v1346117998
-rw-r--r-- 1 www-data www-data 409K Oct 10 09:57 P1110513.JPG.v1405714751
-rw-r--r-- 1 www-data www-data 410K Oct 10 14:36 P1110513.JPG.v1412955983
-rw-r--r-- 1 www-data www-data 408K Oct 22 15:14 P1110513.JPG.v1412967246
-rw-r--r-- 1 www-data www-data 409K Oct 22 16:11 P1110513.JPG.v1414011583
-rw-r--r-- 1 www-data www-data 409K Jan  7 11:06 P1110513.JPG.v1414013114


The file is there in "files" directory, and can be opened by the user as normal. And it has 6 versions in "files_versions" directory. Is that what you mean?

The versions were not deleted when I did the "touch".

I think the bug occurs when the user has unlimited quota initially, the files and versions are created, then we limit the quota, and finally we use "touch". We expect the versions to be deleted, but it won't happen.

**Comment by schiesbn** [comment]
> The versions were not deleted when I did the "touch".

What do you mean with "touch"? Did you modified the file? Because this should also create a new version? Did the "touch" added a new version but didn't removed any of the old one?

Also what looks surprisingly: The newsest version is newer then the original file, comparing this two timestamps:

`ls -lh /var/www/owncloud/data/vfmsamga/files/fotos-proyectos/fotos-proyectos-lohernandez/VENTANAS
total 416K
-rw-r--r-- 1 www-data www-data 409K Jan 7 10:34 P1110513.JPG``


 ls -lh /var/www/owncloud/data/vfmsamga/files_versions/fotos-proyectos/fotos-proyectos-lohernandez/VENTANAS
total 4.4M
[..]
-rw-r--r-- 1 www-data www-data 409K Jan 7 11:06 P1110513.JPG.v1414013114
```

**Comment by chemnic** [comment]
With "touch" I mean I changed the files's modification time. So the files is modified in some way. This "touch" command is being executed in the user's computer, where owncloud-client is installed, not in the server. I also tried ImagesMagic's "mogrify" command to change the size of the images. You can see that the first version is a lot bigger than the rest.

The "touch" command modified the file and owncloud created a new version. I executed the command again just for this file:


root@nube:~# ls -lh /var/www/owncloud/data/vfmsamga/files/fotos-proyectos/fotos-proyectos-lohernandez/VENTANAS
total 416K
-rw-r--r-- 1 www-data www-data 409K Feb  5 09:46 P1110513.JPG


root@nube:~# ls -lh /var/www/owncloud/data/vfmsamga/files_versions/fotos-proyectos/fotos-proyectos-lohernandez/VENTANAS
total 4.8M
-rw-r--r-- 1 www-data www-data 2.3M Jul 24  2014 P1110513.JPG.v1346117998
-rw-r--r-- 1 www-data www-data 409K Oct 10 09:57 P1110513.JPG.v1405714751
-rw-r--r-- 1 www-data www-data 410K Oct 10 14:36 P1110513.JPG.v1412955983
-rw-r--r-- 1 www-data www-data 408K Oct 22 15:14 P1110513.JPG.v1412967246
-rw-r--r-- 1 www-data www-data 409K Oct 22 16:11 P1110513.JPG.v1414011583
-rw-r--r-- 1 www-data www-data 409K Jan  7 11:06 P1110513.JPG.v1414013114
-rw-r--r-- 1 www-data www-data 409K Feb  5 09:46 P1110513.JPG.v1420648498


So there is another version created and the old ones are not being deleted. In this momment that user has 16.4 GB of free space (owncloud quota) and the "files_versions" directory is 58 GB of size.

I think that when owncloud puts a new version of a file in "files_versions" it modifies that version in some way, changing the modification time, and do not preserve the modification time of the original file. Prove of that is that the modification time of the file in "files" and the last version "files_versions" is the same in this precise case (Feb 5 09:46).

In the version file you mention there is a difference of 32 minutes. Maybe owncloud was doing something before writing that version? I don't know, just making some ideas.

**Comment by chemnic** [comment]
Suddenly ownCloud decided to delete what it should have deleted months ago.

I did not make changes to the server. No update. No config. Nothing. I just took a look and 50 GB of files had disappeared. Fortunaly those files were not supposed to be there.

I'm happy that is fixed, but the problem is I don't know what happened. I still think there is a bug somewhere.

**Comment by DeepDiver1975** [comment]
version and trashbin cleanup is based on user action currently - should be move to cron

@icewind1991

**Comment by PVince81** [comment]
Version and trashbin cleanup have been moved to background jobs.
However these jobs are still scheduled based on user action.

**Comment by karlitschek** [comment]
@chemnic Can you confirm that you have configured a cronjob correctly? This should work in 8.1

**Comment by cmonteroluque** [comment]
No comments since May. Closing
