### ISSUE TITLE
Suggestion to add "Version" to the hot links on the admin page

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#13113]
### Steps to reproduce

1. Install both master and enterprise tar balls
2. Navigate to the admin page

### Expected behaviour

There should be a link to click on to get to the version information

### Actual behaviour

There is no link to click on to get to the version information.  

### Server configuration

Ubuntu 14.04
PHP 5.5.9

**Comment by karlitschek** [comment]
@DeepDiver1975 FYI

**Comment by DeepDiver1975** [comment]
While initially working on this with @jancborchardt we decided against this. I don't remember the reason.

**Comment by jancborchardt** [comment]
I don’t really remember deciding on that either. Probably because it’s just one small info and not an important section – hence it should not add to the mass of entries in the sidebar.
