### ISSUE TITLE
Deprication warning in DIContainer is to restrictive for the time being.

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#13118]
https://github.com/owncloud/core/blob/master/lib/private/appframework/dependencyinjection/dicontainer.php#L204

@Raydiation as long as DIContainer itself uses this service the current logging policy is to restrictive from my pov. Let's either remove it for now or downgrade it to debug.

Objections? THX

**Comment by MorrisJobke** [comment]
Fix is in #13125
