### ISSUE TITLE
Collapse app descriptions to be able to more easily browse apps

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#13112]
### Steps to reproduce

1. Install both master and enterprise tar balls
2. Navigate to the apps page to see the new app layout

### Expected behaviour

Ease of use to find all apps enabled, disabled, and recommended

### Actual behaviour

I have to do a lot of scrolling to see what's enabled, disabled, and recommended.  Perhaps having a list of apps that are links to the descriptions would be better?  Then, I can see all apps on the one page and click on the descriptions as needed

The Recommended link displays a blank page.  What should be displayed when I click on this link?

### Server configuration

Ubuntu 14.04
PHP 5.5.9
ownCloud Enterprise Edition 8.0 alpha 1 (daily) Build:2015-01-05T04:12:18+00:00

**Comment by karlitschek** [comment]
@jancborchardt

**Comment by DeepDiver1975** [comment]
> The Recommended link displays a blank page. What should be displayed when I click on this link?

Recommended apps are take from the app store - because of there are apps available yet for OC8 this list will be empty. But in this case you should see other apps categories as well.

**Comment by DeepDiver1975** [comment]
@jnfrmarks can you please post the config files? THX

**Comment by DeepDiver1975** [comment]
> Perhaps having a list of apps that are links to the descriptions would be better? Then, I can see all apps on the one page and click on the descriptions as needed

From my pov we should add a type ahead search/filtering - topic for OC8.1 from my pov.

**Comment by DeepDiver1975** [comment]
@jnfrmarks can I ask you for another favor as you are testing the release packages? From my pov we should have an app icon in the apps page for every app we ship - can I ask you to double check if this is the case? If not - please open issues in the relevant apps repos on github and ask @jancborchardt to add an icon. Many thanks!

**Comment by DeepDiver1975** [comment]
Do we consider this critical for OC8.0? I'd vote for 8.1

@karlitschek

**Comment by karlitschek** [comment]
Hmm. It is an annoyance. I think it depends on how hard it is to fix.

**Comment by DeepDiver1975** [comment]
@jancborchardt tell me what code changes you need from my to make this work :speak_no_evil: THX

**Comment by jancborchardt** [comment]
I’m not sure this counts as a bugfix as this might involve a bunch of JS. Similar to how we do it in the Music app (cc @MorrisJobke) to hide more than 5 tracks for each album initially.

Here’s what we need to do:
* The initial height of each .app-description should be forced to a value where only the first lines are visible. Like this: `height: 44px; overflow: hidden;`
* When clicked, the description should be expanded to show the full description
* We need a small indicator on the bottom that there is more text. I can put an absolutely positioned `…` there.
* Optionally we can have a way to collapse the description again but I don’t think that’s needed, at least for now.

**Comment by jnfrmarks** [comment]
@DeepDiver1975 

I vote to fix this for 8.0.  This is a usability issue (to me) of a new feature we're delivering.

**Comment by PVince81** [comment]
I think it should be possible to quickfix this as @jancborchardt said.
Just keep the current page (no ajax load of descriptions) but add a CSS class "collapsed" that collapses the descriptions by default.
Then when clicking on "..." or whichever button to expand, it would just toggle the "collapsed" class.

I don't think we need complex JS, unless you want to make the collapsing conditional ? Can we go with the simplest solution and collapse everything by default ?

In the future we might want to look into ajax-loading the app descriptions, but out of scope from here.

What do you think ?

**Comment by jancborchardt** [comment]
(Not only clicking on `…` should trigger expanding the description, but clicking on the description itself as well. As I said above.)

**Comment by jnfrmarks** [comment]
@DeepDiver1975 @karlitschek  

Will this be in 8.0?

**Comment by MorrisJobke** [comment]
@jnfrmarks There hasn't been anything implemented yet, so I don't think that this will be available in 8.0

**Comment by PVince81** [comment]
@jancborchardt I was thinking, maybe `text-overflow: ellipsis` could auto-generate the "..." if the layout permits.

**Comment by jnfrmarks** [comment]
Is this a difficult change to make?  I like the look and feel of the new layout - it's just a harder to see what's enabled and what's disabled.

**Comment by MTRichards** [comment]
Concur, this makes a big difference for the admin.

**Comment by jancborchardt** [comment]
cc @ciordache this would be a good issue to get started with for example. :)

**Comment by MorrisJobke** [comment]
As this won't make it into 8.0 I removed my assignment.
