### ISSUE TITLE
.htaccess and directory structure security

### ISSUE THREAD

**Issue by RichardNeill** [owncloud/core#13114]
Looking at the structure of owncloud, it worries me slightly that the private data is in a *subdirectory* of the public data. Although it's protected by .htaccess, it seems that it would be very easy to lose this protection (various potential for human error), and that there are better alternatives.

Currently, the (simplified) structure is:

/var/www/owncloud/ *                        Application root directory AND web root directory, PUBLIC.
/var/www/owncloud/data/                  #Public by default, BUT protected by a .htaccess rule.

http://localhost/owncloud   maps to   /var/www/owncloud

It seems to me that a more logical structure would be:

/var/www/owncloud/                         #Application directory. Private. (Not in the webroot).
/var/www/owncloud/data/                 #Users files. Private.
/var/www/owncloud/config/               #configuration and settings
/var/www/owncloud/include/             #functions and libraries
/var/www/owncloud/htdocs/              #Webroot: only php and image/css files explicitly to be served.

http://localhost/owncloud   maps to   /var/www/owncloud/htdocs

Rationale for changing:

1. This is more secure by default - it is less likely to accidentally break (human error!)

2. .htaccess is inefficient, and recommended against by Apache. It may eventually be deprecated.

3. Almost all Linux distros now use /var/www/ as the web-application folder, and /var/www/html as the default webroot  (it used to be that /var/www/ was the default webroot  on Debian/Ubuntu till 2013), which meant that there was no top-level directory for the local components of web-applications.

4. It's more elegant, imho, to have "secure by default, with certain permissions granted" than "public by default, with certain permissions revoked".

Thanks for your time and consideration.

**Comment by karlitschek** [comment]
the location of the data directory can be changed in the setupnwizard and in the config file.

**Comment by RichardNeill** [comment]
Thanks for your comments. Yes, I know you can change these things. However:

1. The defaults should be better - that's what I'm suggesting
2. data is actually in the right place. It is /var/www/owncloud/index.php  which is not.
3. Diverging from upstream by moving all the files around is a bad idea... it defeats the entire purpose of using a repository for security patches.
