### ISSUE TITLE
Lazy loading of users in share dialog

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#13110]
### Expected behavior
Find a user to share in a big  LDAP user list (when users have the same name).

### Actual behavior
Only 15 users are displayed and no way to find the expected user.

### Steps to reproduce it
I did some tests with my account and I found out that only searching by first name and surname gives me the opportunity to find the right person.

Here are my test results:

· First name & surname: Person found!

· Surname & first name: No people found!

· Surname: Not found, list not complete?

· First name: Not found, list not complete?

· Username: No people found!

I didn't find a possibility to change the search functionality. Is it possible to extend the current search functionality so that all my test scenarios will work?

In: https://github.com/owncloud/core/pull/8232 @blizzz commented on the 22rd of April, that it is possible to use memcached as cache for the LDAP queries. In version 7.0.4 does not work or implemented. If yes, how can I use it? 

 I see only 15 users as maximum!

@schiesbn @MorrisJobke 

00001737

**Comment by MorrisJobke** [comment]
@blizzz Is it possible to tweak the search that you can also search in reverse order (Surname & firstname)?

@cdamken I guess the inclomplete list for search for surname and search for  first name is not related to LDAP, but also a restriction of the other user backends (as the share drop down has a limit of 15)

@jancborchardt @schiesbn @PVince81 Are there ideas how we could handle cases where more search results need to be fetched, because you don't know more than i.e. the first name and want to list everybody?

@DeepDiver1975 You had some special functionality for a more privacy in the share drop down. I couldn't find it anymore. This is maybe a related code path. Can you link it here? Thanks

**Comment by blizzz** [comment]
LDAP should find all users no matter in which order the search names are provided, as long as seperate fields for first name and last name are provided in the search attributes in the LDAP settings. This is since 7.0.4. 

The 15 results restriction is known by the share dialog and at least is in discussion.

**Comment by DeepDiver1975** [comment]
> You had some special functionality for a more privacy in the share drop down. I couldn't find it anymore. This is maybe a related code path. Can you link it here? Thanks

That PR was closed as is was a stupid workaround (as quick solution) - we need to properly support this feature as is to be discussed for one of the upcoming releases. @MTRichards @LukasReschke

**Comment by LukasReschke** [comment]
> we need to properly support this feature as is to be discussed for one of the upcoming releases

Yes - let's please do this properly this time then and use the opportunity to refactor that whole bloody totally untested and probably somewhat buggy [`ajax/share.php`](https://github.com/owncloud/core/blob/6a3f69c2d043203a7650d16200accd0303430e09/core/ajax/share.php)

Needs some more thoughts such as what we actually want to protect against, if that feature should be configurable etc. (for example limiting to minimum character match before auto-completion etc…)

**Comment by cdamken** [comment]
@MTRichards Is this planned or as feature requests?

**Comment by DeepDiver1975** [comment]
So in order to get more users displayed we could move over the drop down to select2 where we have scrolling/lazy loading capabilities.

This touches the sharing dialog/drop down which is kind of pain for quite some long time.

@jancborchardt we shall approach this the next weeks while co-working.

**Comment by PVince81** [comment]
I suggest a rewrite of the sharing dialog as a popup with select2. This would help cleanup the "core/js/share.php" code a bit and would need re-testing / unit tests anyway.

**Comment by DeepDiver1975** [comment]
While at it we can kill that html string concatenation in js and use handlebars.

**Comment by MTRichards** [comment]
Possibly 8.1. @DeepDiver1975 what do you think?

**Comment by DeepDiver1975** [comment]
Everything is possible - we need to plan the next dev cycle these days ....

**Comment by cdamken** [comment]
@MTRichards  @DeepDiver1975 I'll assume then for 8.1. Thanks

**Comment by MTRichards** [comment]
Assuming doesn't necessarily make it so...tagging so I can find it.

**Comment by PVince81** [comment]
Defer to 8.2 ?

Also CC @rullzer for share dialog ideas

**Comment by MTRichards** [comment]
@craigpg need to get this in to 8.1

**Comment by cdamken** [comment]
:+1:

**Comment by rullzer** [comment]
So this is something we want for sure... but I really doubt anyone wants to make this work in the current [`ajax/share.php`](https://github.com/owncloud/core/blob/6a3f69c2d043203a7650d16200accd0303430e09/core/ajax/share.php). And if added to the code it will be a real pain to make sure all the other stuff does not break. Also this needs to be tested in depth to make sure people can still share stuff!

Probably best to add this to the list of stuff for the new sharing modal.

**Comment by MorrisJobke** [comment]
This is fixed with #12401
