### ISSUE TITLE
how to configure preview for Microsoft office file

### ISSUE THREAD

**Issue by zengjice** [owncloud/core#13115]
#### Here is my config.php
![2015-01-05 22 56 06](https://cloud.githubusercontent.com/assets/5196427/5614797/aa60fa18-952f-11e4-9d79-32d9686a8f9f.png)

#### and then i try to upload *.doc, browser show me this and upload fail:
![2015-01-05 23 00 15](https://cloud.githubusercontent.com/assets/5196427/5614829/e400d996-952f-11e4-882d-ca6b60ac4f10.png)

**Comment by karlitschek** [comment]
I suggest that you ask a question like that on the mailing-list or in the forum. 
This issue tracker is for actual bugs only. 
Thanks a lot.
