### ISSUE TITLE
App license information is missing 

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#13120]
### Steps to reproduce

1. Install both master and enterprise tar balls
2. Navigate to the apps page

### Expected behaviour

The license information should be available for each app

### Actual behaviour

The license information is missing for each app

![p234](https://cloud.githubusercontent.com/assets/8480343/5620033/c899f6e0-94f5-11e4-8846-3755ae47ea44.PNG)

### Server configuration

Ubuntu 14.04
PHP 5.5.9
ownCloud Enterprise Edition 8.0 alpha 1 (daily) Build:2015-01-05T04:12:18+00:00

**Comment by karlitschek** [comment]
@DeepDiver1975 @jancborchardt Can you have a look? It seems that the license is missing

**Comment by jancborchardt** [comment]
@DeepDiver1975 we should place it below the description like this:

> License: AGPL

That way it will also be hidden away as an advanced information as soon as we implement the »show more« to show the full description as I wrote in https://github.com/owncloud/core/issues/13112#issuecomment-68771549
