### ISSUE TITLE
( ! ) Fatal error: Call to a member function getSize() on array in /Users/lreschke/Programming/core/lib/private/helper.php on line 908

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#13127]
The following error happens when opening `/index.php/apps/files/ajax/getstoragestats.php?dir=/../`. Please notice that the directory `/../` does obviously not exists.

Better practise would be to check whether the directory actually exists or not.

**Comment by karlitschek** [comment]
@icewind1991
