### ISSUE TITLE
Public API for creating a new database connection

### ISSUE THREAD

**Issue by Raydiation** [owncloud/core#13123]
In order to scale up the News app (and probably other apps too) I need to be able to create a new database connection to a different database host where all News app data is stored to take load off the main server. ATM there is only one database connection instance which is hardcoded in core and I'd have to use private classes.

It would be nice if we could have something like:

```php
namespace OC;

class DatabaseFactory implements OCP\IDatabaseFactory {
    /**
     * @return OCP\IDatabaseConnection
     */
    public function createConnection($type, $host, $user, $pass, $port) {
        // connection kung fu which is currently in server.php
    }

    /**
     * @return OCP\IDb
     */
    public function createDatabaseAccess(OCP\IDatabaseConnection $connection) {
         return new OC\AppFramework\Db\Db($connection);
    }

}
```

so I could do the following in the News app:

```php
$factory = $c->query('OCP\IDatabaseFactory');
$connection = $factory->createConnection('mysql', 'host', 'user', 'pass');
$db = $factory->createDatabaseAccess($connection);
// execute yer db queries
$connection->close();  // this can be moved into an afterController method in a custom middleware
```
PS: The factory is needed to hide the private constructors so we can change them if we want without breaking the public API

@DeepDiver1975 @nickvergessen @PVince81 @MorrisJobke @jbtbnl @fossxplorer

**Comment by DeepDiver1975** [comment]
Well - creating the database connection is only one piece of the story:

- what about database migrations on this database(s)?
- support for NoSQL (which is something we want to target in core as well some point in time)
- use special setups like mysql read/write hosts?

(Last two topics are high level brainstorming - but shows that a fixed parameter set will not help)

**Comment by Raydiation** [comment]
The general idea that went through my mind when talking to @fossxplorer was to create 2 owncloud instances where one is the main instance hosting the normal owncloud installation and the other is the one which is only used to trigger schema migrations. IIRC there is already a separate ownCloud installation for the News app which connects to the same db and is purely used to run the feed updates

**Comment by DeepDiver1975** [comment]
hmm - this seriously sounds like bad kung-fu to me - nothing we should support from an public api pov.

The is still the possibility to run the feed updates on a different server connecting to the same db - wouldn't that make more sense then having two dbs?

**Comment by Raydiation** [comment]
@DeepDiver1975 that's how it is right now. The problem is that the News database gets to big (50gb+) and the update process puts too much load on the database server slowing down file sync etc. So the idea is to create a separate database just for the News app tables to be able to scale it up in an easier fashion.

**Comment by DeepDiver1975** [comment]
hmmm - 50GB of data should not really be on an issue from my pov - with exception to the schema upgrade process which generates duplicate tables. 

@icewind1991 is there a switch/config to disable the table copy mechanism - we know that this is a bad mechanism in case of big data.

**Comment by Raydiation** [comment]
@DeepDiver1975 table migration is not an issue. If you've got a better idea how to scale it up let me know.

**Comment by DeepDiver1975** [comment]
Ah the bottleneck is the update process of the new feeds - hmmm - why is it producing that much load?

**Comment by Raydiation** [comment]
You can speed it up by running parallel requests but the biggest issue is the cleanup where old entries are deleted. It's quite an expensive sql query that I wasnt able to reduce further without adding database specific code like procedures.

**Comment by Raydiation** [comment]
Anyways we need to scale out.

**Comment by DeepDiver1975** [comment]
Generally speaking scaling is a matter of moving to a cluster or  read/write host setup?

**Comment by karlitschek** [comment]
I agree with Thomas. It is highly unusual to handle different db connection on an application layer. Scaling is done on a lower level like in a DB cluster, with a DB load balancer or SQL proxy

**Comment by Raydiation** [comment]
@karlitschek i see, @fossxplorer can you check if this works for you?

**Comment by DeepDiver1975** [comment]
let's close this for now - THX

**Comment by fossxplorer** [comment]
@Raydiation sure i will.
And yes, migration is a big headache as it used over 10 hours last time IIRC due to the simulation stuff it was doing. Would be very useful to be able to switch it off for bigger DBs.

**Comment by LukasReschke** [comment]
@fossxplorer You can switch it off. Check the occ command line tool.

**Comment by fossxplorer** [comment]
@LukasReschke here are the options i can see on stable7. Am i missing something?

$ ./occ
ownCloud version 7.0.4

Usage:
  [options] command [arguments]

Options:
  --help           -h Display this help message.
  --quiet          -q Do not output any message.
  --verbose        -v|vv|vvv Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
  --version        -V Display this application version.
  --ansi              Force ANSI output.
  --no-ansi           Disable ANSI output.
  --no-interaction -n Do not ask any interactive question.

Available commands:
  help                        Displays help for a command
  list                        Lists commands
  status                      show some status information
  upgrade                     run upgrade routines
app
  app:disable                 disable an app
  app:enable                  enable an app
  app:list                    List all available apps
db
  db:convert-type             Convert the ownCloud database to the newly configured one
  db:generate-change-script   generates the change script from the current connected db to db_structure.xml
files
  files:scan                  rescan filesystem
ldap
  ldap:check-user             checks whether a user exists on LDAP.
  ldap:search                 executes a user or group search
  ldap:set-config             modifies an LDAP configuration
  ldap:show-config            shows the LDAP configuration
  ldap:show-remnants          shows which users are not available on LDAP anymore, but have remnants in ownCloud.
  ldap:test-config            tests an LDAP configuration
maintenance
  maintenance:mode            set maintenance mode
  maintenance:repair          repair this installation
  maintenance:singleuser      set single user mode
music
  music:scan                  rescan music
user
  user:delete                 deletes the specified user
  user:lastseen               shows when the user was logged it last time
  user:report                 shows how many users have access
  user:resetpassword          Resets the password of the named user
$

**Comment by LukasReschke** [comment]
http://doc.owncloud.org/server/8.0/admin_manual/configuration/occ_command.html#upgrade-command:

> Before completing the upgrade, ownCloud first runs a simulation by copying all database tables to a temporary directory and then performing the upgrade on them, to ensure that the upgrade will complete correctly. This takes twice as much time, which on large installations can be many hours, so you can omit this step with the --skip-migration-test option:

**Comment by MorrisJobke** [comment]
This is also available on stable7
```
stable7$ ./occ upgrade --help
Usage:
 upgrade [--skip-migration-test] [--dry-run]

Options:
 --skip-migration-test  skips the database schema migration simulation and update directly
 --dry-run              only runs the database schema migration simulation, do not actually update
 --help (-h)            Display this help message.
 --quiet (-q)           Do not output any message.
 --verbose (-v|vv|vvv)  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
 --version (-V)         Display this application version.
 --ansi                 Force ANSI output.
 --no-ansi              Disable ANSI output.
 --no-interaction (-n)  Do not ask any interactive question.
```

**Comment by fossxplorer** [comment]
@LukasReschke @MorrisJobke Thx! For me it wasn't easy to know there was an option to skip the migration test. But at least now i know!
