### ISSUE TITLE
User menu often not available on Android

### ISSUE THREAD

**Issue by carlaschroder** [owncloud/core#13136]
Hello good owncloud peoples! I fear I have discovered an issue in the ownCloud Web interface on Android: the user menu (top right) does not reliably appear. I tested this on an ASUS Memopad 8 and a Samsung Galaxy smartphone. In contrast, the ownCloud dropdown menu (top left) works as it is supposed to.

**Steps to Reproduce**

On my ASUS tablet the user menu (Web GUI) only appears in landscape mode. This is what I see in portrait mode (Dolphin Web browser):

![android-app](https://cloud.githubusercontent.com/assets/8388387/5632732/f19bcc72-9585-11e4-9efb-59390f36ea4d.jpg)

In landscape mode the user menu automatically drops down and remains exposed, and I can't make it go away:

![android-app-2](https://cloud.githubusercontent.com/assets/8388387/5632738/0a4dee30-9586-11e4-89d3-e26daef61cd5.jpg)

Firefox behaves the same way. In Google Chrome the user menu appears and retracts on short press on the username, but only in landscape mode.

The user menu will not appear with any browser on the Samsung Galaxy smartphone.

ASUS Memopad 8, K00L
Android version 4.2.2
kernel version 3.0.36
Google Chrome 39.0.2171.93
Firefox 34.0.1
Dolphin 11.3.4

Samsung Galaxy SCH-S738C
Android 4.04
Kernel 3.0.8
Firefox 27.0
Google Chrome 33.0.1750.132

**Comment by RealRancor** [comment]
Hi,

i think this should be fixed with: https://github.com/owncloud/core/pull/12798

**Comment by carlaschroder** [comment]
ok thanks @RealRancor

**Comment by RealRancor** [comment]
Hi,

@carlaschroder 

but this should only fix:

> The user menu will not appear with any browser on the Samsung Galaxy smartphone.

Don't know about this:

> In landscape mode the user menu automatically drops down and remains exposed, and I can't make it go away
