### ISSUE TITLE
A bug but no solution ? :(

### ISSUE THREAD

**Issue by johan27hack** [owncloud/core#13135]
Good morning,

I'm sorry to post here, but since I found the following issue; a few weeks ago, I don't have any answer neither some little explanation :(
https://github.com/owncloud/core/issues/13044

It's really weird, since if I have this bug, that mean some others people can have it, and, potentially, can leave this project if they feel nobody can help ..

Either, my best wishes for OC 8 and long life to that project :)

Greeting !

**Comment by karlitschek** [comment]
This should be discussed in the original issue. No need to open up a new one. Thanks
