### ISSUE TITLE
Provisioning api uses uniqid()

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#13139]
@tomneedham 

The tests should extend the `\Test\TestCase` class and then use `$this->getUniqueID()`, because uniqid() is not unique on windows

**Comment by MorrisJobke** [comment]
@DeepDiver1975 @nickvergessen Can't we have some linter checks for this to avoid something similiar to slip in?

**Comment by tomneedham** [comment]
Thanks @nickvergessen. Will get on this.

**Comment by DeepDiver1975** [comment]
> Can't we have some linter checks for this to avoid something similiar to slip in?

Stuff like this will heal over time :speak_no_evil:

**Comment by nickvergessen** [comment]
@tomneedham fixed it in #13140
