### ISSUE TITLE
What to display when no search results are present

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#13142]
Currently when there are no search results, I only get the line on the top left:
> No search result in other places

But the nice looking [search icon and the notice](https://github.com/owncloud/core/pull/12653#issuecomment-68863553) does not appear. It should appear though if there are
* no results in this folder
* no results in other places

Additionally, the line below the icon should say:
> No results found for "searchterm"

(A second line is not necessary)

cc @butonic @owncloud/designers

**Comment by karlitschek** [comment]
@butonic can you have a look?

**Comment by MorrisJobke** [comment]
![bildschirmfoto 2015-10-29 um 13 55 23](https://cloud.githubusercontent.com/assets/245432/10818833/c1ae76a6-7e44-11e5-8d01-fdf6e25aeb78.png)

Works -> closing
