### ISSUE TITLE
Initial load shows »No files yet« in the background for a short time

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#13141]
When you open ownCloud Files (or you refresh), behind the spinner the message »No files yet« is shown for a split-second.

This is very disconcerting and wrong information, as the files show up shortly afterwards. It wasn’t the case before as only the spinner showed.

The issue shows since commit 7a812801db6cc2cddf4e176dc893b07c7c486d76 – can you look into it @butonic? :)

**Comment by PVince81** [comment]
Slapping showstopper tag. @karlitschek set it on my duplicate ticket here https://github.com/owncloud/core/issues/13152

As it is a regression, it probably makes sense.

**Comment by butonic** [comment]
on it

**Comment by jancborchardt** [comment]
This still shows up sometimes. Saw it for example on @nickvergessen’s browser, current Firefox.

**Comment by jancborchardt** [comment]
This still shows up sometimes. Saw it for example on @nickvergessen’s browser, current Firefox.

It shows behind the loading spinner. It should never show when the loading spinner is also showing. cc @PVince81 @butonic

**Comment by tomneedham** [comment]
+1 I get this too!

**Comment by PVince81** [comment]
@butonic do you still intend to fix this yourself ? If not, please unassign yourself. Thanks!

**Comment by MorrisJobke** [comment]
AFAIK this was fixed lately in the 8.2 release cycle, but I can't find the ticket anymore (I thought it was fixed by @PVince81)

I will close this then. If you still see this, then reopen please.

**Comment by PVince81** [comment]
Duplicate of https://github.com/owncloud/core/issues/17393
