### ISSUE TITLE
Setting up core master via git gets into infinite loop when accessing it for the first time

### ISSUE THREAD

**Issue by Raydiation** [owncloud/core#13153]
I'm using the newest PHP version 5.6.4 btw.

How to reproduce:

    git clone --recursive https://github.com/owncloud/core.git
    cd core
    php -S localhost:8080

Now access http://localhost:8080 and find yourself stuck in an infinite loop. After killing the server with

    sudo pkill php

and running the server again:
    
    php -S localhost:8080

It works just fine. I think it has something to do with the files that are created when running ownCloud for the first time (maybe some stuff in the data directory?)

@MorrisJobke @DeepDiver1975 @PVince81 @butonic @jbtbnl @wakeup

**Comment by Raydiation** [comment]
I can reproduce this in stable7 btw

**Comment by DeepDiver1975** [comment]
@Raydiation anything in the logs? Can you attach a debugger? THX

**Comment by Raydiation** [comment]
No logs so far

**Comment by Raydiation** [comment]
Narrowed the problem down: It gets into an infinite loop/stuck if data/htaccesstest.txt is not present

**Comment by Raydiation** [comment]
@DeepDiver1975 I'm unable to attach a debugger, PHPStorm has a grayed out debug field. Can you take a look?

**Comment by Raydiation** [comment]
Narrowed it down to this method: if i just return true it works out of the box https://github.com/owncloud/core/blob/master/lib/private/util.php#L1029

**Comment by Raydiation** [comment]
@bartv2 @th3fallen

**Comment by th3fallen** [comment]
Sorry im being pounded right now can't look at this atm i'll take a look when i get some clearance.

**Comment by DeepDiver1975** [comment]
@Raydiation what's the value of $url in here https://github.com/owncloud/core/blob/master/lib/private/util.php#L1055

**Comment by DeepDiver1975** [comment]
I suspect the port is missing in the url

**Comment by Raydiation** [comment]
$url is http://localhost:8080/data/htaccesstest.txt

**Comment by Raydiation** [comment]
Does htaccess even work when you run the php dev server?

**Comment by DeepDiver1975** [comment]
> Does htaccess even work when you run the php dev server?

afaik no - I'll look into this tomorrow

**Comment by DeepDiver1975** [comment]
This happens because the php process is sending the request to himself - which will block ... we shall disable this htaccess check if php dev server is used
