### ISSUE TITLE
Why app "files_encryption" sets "<rememberlogin>false</rememberlogin>"?

### ISSUE THREAD

**Issue by aaschmid** [owncloud/core#13159]
Unfortunately, I couldn't found any documentation about the no longer available "remember" login feature if the "files_encryption" isn't installed. One day I was missing the "remember" checkbox as my mobile client was just logged out every day. After some searching through the source code I found the ```rememberlogin``` variable. As I have just installed the "news" and "encryption" apps, I source both repos and finally found the line 
```xml
<rememberlogin>false</rememberlogin>
```
in ```core/apps/files_encryption/appinfo/info.xml```. 

Now my question is: "Is this intended due to any feature or can I just disable this?" (I have something in mind, that the decryption works by using the password and if this password is not provided, maybe the decryption does not work any longer ...).
If not, I could think about a option within "admin" area or "config.php" to set this behavior ...

Thanks for any answer!
Andreas

**Comment by LukasReschke** [comment]
> Now my question is: "Is this intended due to any feature or can I just disable this?" (I have something in mind, that the decryption works by using the password and if this password is not provided, maybe the decryption does not work any longer ...).

That assumption is correct. The user password is used to decrypt the encryption key. However, with the "remember me" login functionality the user password is not known but only a long random string which is used to authenticate the user.

Thus it is not possible to use encryption with the remember me login functionality. If you want that feature back you need to disable encryption.

@carlaschroder Possible candidate for documentation clarification.

**Comment by aaschmid** [comment]
Ok, thanks for the clarification
