### ISSUE TITLE
Introduce query language to allow tweaking search parameters

### ISSUE THREAD

**Issue by butonic** [owncloud/core#13155]
This is the first step towards limiting search to a certain subdirectory or mimetype. google as well as github allow searching in metadata by using sth like `author:butonic`, `filetype:pdf` or `in:Music`. To allow [more sophisticated search queries](http://www.lucenetutorial.com/lucene-query-syntax.html) we should parse the query string with the [zend search lucene query parser](https://github.com/zf1/zend-search-lucene/blob/master/library/Zend/Search/Lucene/Search/QueryParser.php) and introduce a new searchByQuery method for search providers that takes a search object with the parsed query, page, size and maybe other variables.

**Comment by oparoz** [comment]
Please make sure these support pagination (LIMIT). This is currently a huge problem with the current search commands.

**Comment by PVince81** [comment]
@butonic didn't you re-raise this recently ? duplicate ?
