### ISSUE TITLE
[master] Empty content icon shortly shown during file list load

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13152]
### Steps to reproduce
1. Upload a lot of files
2. Refresh the page

### Expected result
Loading spinner appears **alone**.

### Actual result
Loading spinner appears AND the empty content message with the folder.

### Versions
ownCloud 8 master 5ce295907fd9469905d561de71d83149a6c0f6c5

Minor bug, still setting to OC 8. Hopefully an easy fix.
CC @jancborchardt

**Comment by PVince81** [comment]
Wow, is it that critical to be a showstopper ?

**Comment by nickvergessen** [comment]
@PVince81 duplicate of https://github.com/owncloud/core/issues/13141 ?

**Comment by PVince81** [comment]
Yes, I knew I had seen this before.
Closing.

**Comment by karlitschek** [comment]
Just to clarify. I tagged this as a showstopper to track and keep in mind. This list will change heavily in the next 3 weeks. First it will become longer and later shorter :-)

**Comment by jancborchardt** [comment]
Closing as duplicate of https://github.com/owncloud/core/issues/13141

**Comment by jancborchardt** [comment]
Ah, my tab was outdated! ;)

**Comment by jancborchardt** [comment]
And yeah, I would say this is a showstopper since it’s a regression and can cause you to think your files are gone, even if it’s just for a second.
