### ISSUE TITLE
Make OC_Subadmin non-static

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#13162]
`OC_Subadmin` is static and thus it is an absolute pain to write unit-test for code that includes it. This is kinda bad when it comes to write unit-test where a function may behave differently when the user is an admin or an subadmin.

When touching the `OC_Subadmin` code - for example for https://github.com/owncloud/core/issues/1212 - I *strongly* suggest that we refactor the same code as well. Currently we just cannot test a lot of security relevant code due to that. 

\cc @DeepDiver1975 FYI

**Comment by PVince81** [comment]
It's gone, closing
