### ISSUE TITLE
Animated gifs do not animate

### ISSUE THREAD

**Issue by clarjon1** [owncloud/core#13164]
Hello,

I recently installed OwnCloud 7.0.4 and discovered that animated gifs in the slideshow, gallery, or single file share modes do not animate.
From what I recall, animated gifs did animate in owncloud 6.x.

[Here is a link to an example image, an animated gif of a cat playing with and popping ballons on my install.](https://cloud.xfcab.com/public.php?service=files&t=5c6e6b07bae06e79fefbc874e4a3f70c)

**Comment by MorrisJobke** [comment]
@clarjon1 That's caused by the change to the previews provider for ownCloud 7+

@georgehrke @LukasReschke @jancborchardt Is it reasonable to not preview gifs and simply use the original file within the slideshow?

**Comment by MorrisJobke** [comment]
Keep in mind that it could be a huge file.

**Comment by jancborchardt** [comment]
Well, if we want people to be able to use ownCloud to share GIFs then we better use the original file. And yeah, I think it’s important that we do support this.

**Comment by DeepDiver1975** [comment]
@georgehrke wana take a look? THX

**Comment by DeepDiver1975** [comment]
> Keep in mind that it could be a huge file.

We should put a file size limit to this - ideal depending on the bandwith ....

**Comment by georgehrke** [comment]
so do we want animated thumbs or animation in the slideshow. If it's about the slideshow this issue should move to the gallery

**Comment by DeepDiver1975** [comment]
neither thumbs nor gallery/slideshow - this is about the public file sharing page - see the screenshot - THX

**Comment by georgehrke** [comment]
Ahh sure, yes I can take care.

**Comment by DeepDiver1975** [comment]
> Ahh sure, yes I can take care.

great - thx - I'd move this to the OC8 milestone to get it fixed for OC8 - if time permits

**Comment by georgehrke** [comment]
sure, this is rather a bug fix than a real new feature

**Comment by DeepDiver1975** [comment]
> sure, this is rather a bug fix than a real new feature

indeed :wink:

**Comment by DeepDiver1975** [comment]
> great - thx - I'd move this to the OC8 milestone to get it fixed for OC8 - if time permits

@georgehrke  any chance to get this in? THX

**Comment by georgehrke** [comment]
> @georgehrke any chance to get this in? THX

Saturday

**Comment by georgehrke** [comment]
pr is here: https://github.com/owncloud/core/pull/13432
