### ISSUE TITLE
not able to upload/sync files from ownCloud andriod App v1.6.2

### ISSUE THREAD

**Issue by deepakpatiyal** [owncloud/core#13169]
### Steps to reproduce
1. using andriod app to sync to ownncloud 7.0
2.
3.

### Expected behaviour

When I upload/sync images/files using ownlcoud andriod app it should upload the files to server

### Actual behaviour

When I upload/sync it shows the progess base 1%..10%..50%.. and finally 100% but after it shows error You don't have permission to upload to this folder ,whereas I am able to create new folder at same location

### Server configuration
**Operating system**:

Linux Kernel Version 2.6.32-458.23.2.lve1.2.48.el6.x86_64 

**Web server:**

Apache 2.4.7

**Database:**

MySQL Version 5.5.36-cll-lve 

**PHP version:**

PHP Version 5.3.28 

**ownCloud version:** (see ownCloud admin page)

ownCloud 7.0.4 (stable) 

**Updated from an older ownCloud or fresh install:**

fresh Install

**List of activated apps:**

 Activity
 Calender 
 Contacts
 Deleted files
 Documents
 First Run Wizard
 Full Text Search
 Music
 PDF Viewer
 Pictures
 Share Files

**The content of config/config.php:**

```
$CONFIG = array (
  'instanceid' => 'ocpfr2zqdcbm',
   'passwordsalt' => 'example',
 trusted_domains' => 
  array (
    0 => 'patiyalmail.co.in',
  ),
  'datadirectory' => '/home/example.com/ownclouddata',
  'overwrite.cli.url' => 'http://example.com/owncloud',
  'dbtype' => 'mysql',
  'version' => '7.0.4.2',
  'dbname' => 'xxxxxxxxx',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxxxxxxxx',
  'dbpassword' => 'xxxxxxxxxxx',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpauthtype' => 'LOGIN',
  'loglevel' => '0',
);

```

**Are you using external storage, if yes which one:** 

**Are you using encryption:** yes/no

no

### Client configuration
**Browser:**

owncloud Client 1.6

**Operating system:**

Andriod Smart Phone 4.4.2

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```

Debug webdav Sabre\DAV\Exception\NotFound: File with name ownCloudUserManual (2).pdf could not be located 2015-01-08T04:41:24+00:00 
Debug webdav Sabre\DAV\Exception\NotFound: File with name videos/IMG_20141231_213956.jpg could not be located 2015-01-07T13:57:39+00:00 
Debug webdav Sabre\DAV\Exception\NotFound: File with name photos/note3neo/IMG_20141231_213956.jpg could not be located 2015-01-07T12:03:10+00:00 


```

#### Browser log
```

```

#### Sync Client

ownCloud Andriod App
version 1.6.2

**Comment by MorrisJobke** [comment]
@rperezb Do you know what this could have caused?

**Comment by deepakpatiyal** [comment]
can't figure out but through web browser I am able to upload and download

**Comment by DeepDiver1975** [comment]
Looks more like an android app issue to me ....

**Comment by deepakpatiyal** [comment]
I am able to download files using Android app

**Comment by tobiasKaminsky** [comment]
Is there something in LogCat?

**Comment by deepakpatiyal** [comment]
CatLog show nothing when I start upload or when error is displayed after upload

**Comment by PVince81** [comment]
Are you able to upload files using WebDAV or the desktop sync client ? (to rule out Android issues)
The Android client uses WebDAV, so there's a chance that the problem is with WebDAV.

**Comment by PVince81** [comment]
Close due to inactivity.

If you're still having the issue, please provide the requested information.
Thanks.
