### ISSUE TITLE
filesize(): stat failed

### ISSUE THREAD

**Issue by nazar-pc** [owncloud/core#13171]
### Steps to reproduce
Just normally use owncloud, it will appear by itself at some point

### Expected behaviour
0 warnings log

### Actual behaviour
I have a lot of warnings like this:
> filesize(): stat failed for /var/www/owncloud/data/nazar-pc/files_trashbin/files/pmd_display_field.2.php.d1416559107 at /var/www/owncloud/lib/private/files/storage/local.php#117 

And file doesn't exists, what really exists is `pmd_display_field.2.php.trashinfo.d1416559107` file, and I'm afraid since file was not remove space will be wasted forever.

### Server configuration
**Operating system**: Ubuntu 14.04 with latest updates (Docker container)

**Web server:** Nginx 1.4.6

**Database:** MariaDB 10.0.15

**PHP version:** PHP-FPM 5.5.9

**ownCloud version:** 7.0.4

**Updated from an older ownCloud or fresh install:** most likely updated from 7.x (do not remember exactly)

**List of activated apps:**
> Activity
ATNotes
Calendar
Contacts
Deleted files
Documents
External storage support
First Run Wizard
Full Text Search
Mail Template Editor
ocSafe
ownCloud dependencies info
PDF Viewer
Pictures
Share Files
Tasks
Text Editor
Updater
Versions
Video Viewer
Diagram Editor (3rd Party)
Files Counter (3rd Party)
Files move (3rd Party)
Music (3rd Party)
ocPassman (3rd Party)

**The content of config/config.php:**

```
  'instanceid' => '****',
  'passwordsalt' => '****',
  'trusted_domains' => 
  array (
    0 => '****',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.4.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => '****',
  'dbuser' => '****',
  'dbpassword' => '****',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_from_address' => '****',
  'mail_domain' => '****',
  'mail_smtpauthtype' => 'PLAIN',
  'mail_smtpauth' => true,
  'mail_smtphost' => '****',
  'mail_smtpport' => '587',
  'mail_smtpname' => '*****',
  'mail_smtppassword' => '****',
  'forcessl' => true,
  'loglevel' => '1',
  'blacklisted_files' => 
  array (
  ),
  'theme' => '',
  'maintenance' => false,
  'secret' => '****',
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** Forced HTTPS

**Last server logs:**
```
{"app":"PHP","message":"filesize(): stat failed for \/var\/www\/owncloud\/data\/nazar-pc\/files_trashbin\/files\/920b51f6f50c81ae3bd96fa3a9ef9c27f329fc.d1417510185 at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#117","level":3,"time":"2015-01-08T11:12:41+00:00"}
{"app":"files_trashbin","message":"remove \"920b51f6f50c81ae3bd96fa3a9ef9c27f329fc\" from trash bin because it is older than 30","level":1,"time":"2015-01-08T11:12:41+00:00"}
{"app":"PHP","message":"filesize(): stat failed for \/var\/www\/owncloud\/data\/nazar-pc\/files_trashbin\/files\/920b51f6f50c81ae3bd96fa3a9ef9c27f329fc.d1417510185 at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#117","level":3,"time":"2015-01-08T11:12:43+00:00"}
{"app":"files_trashbin","message":"remove \"920b51f6f50c81ae3bd96fa3a9ef9c27f329fc\" from trash bin because it is older than 30","level":1,"time":"2015-01-08T11:12:43+00:00"}
{"app":"PHP","message":"filesize(): stat failed for \/var\/www\/owncloud\/data\/nazar-pc\/files_trashbin\/files\/920b51f6f50c81ae3bd96fa3a9ef9c27f329fc.d1417510185 at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#117","level":3,"time":"2015-01-08T11:12:47+00:00"}
{"app":"files_trashbin","message":"remove \"920b51f6f50c81ae3bd96fa3a9ef9c27f329fc\" from trash bin because it is older than 30","level":1,"time":"2015-01-08T11:12:47+00:00"}
{"app":"PHP","message":"filesize(): stat failed for \/var\/www\/owncloud\/data\/nazar-pc\/files_trashbin\/files\/920b51f6f50c81ae3bd96fa3a9ef9c27f329fc.d1417510185 at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#117","level":3,"time":"2015-01-08T11:13:42+00:00"}
{"app":"files_trashbin","message":"remove \"920b51f6f50c81ae3bd96fa3a9ef9c27f329fc\" from trash bin because it is older than 30","level":1,"time":"2015-01-08T11:13:42+00:00"}
{"app":"PHP","message":"filesize(): stat failed for \/var\/www\/owncloud\/data\/nazar-pc\/files_trashbin\/files\/920b51f6f50c81ae3bd96fa3a9ef9c27f329fc.d1417510185 at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#117","level":3,"time":"2015-01-08T11:13:42+00:00"}
```

**Comment by MorrisJobke** [comment]
cc @schiesbn

**Comment by enoch85** [comment]
I can confirm this as well.

**Comment by cdamken** [comment]
I think this is solved in 7.0.7 or 7.0.8 AFAIK

**Comment by MorrisJobke** [comment]
@nazar-pc @enoch85 Do you still see this with the latest version of stable7, 8 or 8.1?

**Comment by nazar-pc** [comment]
Do not remember this from 8.0 time, currently on 8.1.3 - no such problems

**Comment by MorrisJobke** [comment]
Please reopen if this still exists

**Comment by kdslkdsaldsal** [comment]
@Railsimulatornet I don't think that it makes any sense to push a more then two year old issue. If you experience similar logs please create a new issue and make sure to fill out the shown issue template with all asked questions / info.
