### ISSUE TITLE
Add interface for accepting self-signed certificates for s2s-shares

### ISSUE THREAD

**Issue by icewind1991** [owncloud/core#13175]
Currently if you want to mount an s2s share with the other server using a self-signed certificate you need to import the certificate beforehand.

Ideally the user would be presented with a warning about the certificate not being valid and the option to trust the certificate while accepting an incomming s2s share

**Comment by PVince81** [comment]
We're past feature freeze => 9.0

**Comment by PVince81** [comment]
@cmonteroluque @MTRichards @karlitschek @DeepDiver1975

**Comment by cmonteroluque** [comment]
@PVince81 @icewind1991 I agree, we should add this after 8.2.0
