### ISSUE TITLE
poor Web performance

### ISSUE THREAD

**Issue by snoocer** [owncloud/core#13178]
Hello,

I have performance issues like described in this thread:
https://forum.owncloud.org/viewtopic.php?f=4&t=2550&start=10#p6968

Data from firebug:
Full load of the index.php takes 9.39 sec.
- XHR takes 4.65
- JS takes 4.31
- CSS takes 1.4

Navigate in the Folder-Structure takes between 200 and 500 ms.

I can not figure out why it takes so long to load the complete page. 462 KB of total 489 KB are read from Cache.

Webserver load average: 0.04
Memory usage: 1272 from 12016MB

At the moment the System is not productive. There are no other Requests!

PHP version: 5.5.9
OC Version 7.0.4.2
OS: Ubuntu Server 14.04

Dont know how to analyse where the long loading times come from.

Thank you in advance!

**Comment by nickvergessen** [comment]
Can you try to disable firebug and use the firefox development tool instead.
Firebug is known to cause troubles in network stuff from time to time

**Comment by snoocer** [comment]
Tried first with Firefox internal "inspect element" --> Network Tab --> same data for example:

complete load: 6.62s
HTML: 0.16s
CSS: 1.56s
JS: 4.54s
XHR: 2.37s
Other: 0.12s

Don't know how to check the Speed with Firefox Web Developer tools....

**Comment by josh4trunks** [comment]
this future documentation focus mostly on backend stuff, but still useful.

https://github.com/owncloud/documentation/pull/479/files

what database are you using, are your files located locally, or external storage?

**Comment by snoocer** [comment]
Database= mysql
I have external storage and local storage.
Storage-Backend is SSD.
apcu extension used for caching
I use cron to perform backgroud jobs

ty for the quick reply's

**Comment by PVince81** [comment]
Are you still seeing performance issues with 7.0.7 or 8.0.5 ?

**Comment by nickvergessen** [comment]
Feel free to reopen, if so.
