### ISSUE TITLE
Remove bogus warning "no reuse of etag!!!"

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13187]
When uploading/overwrite a file through WebDAV, the following warning/debug message often appears in the log:
```
!!! No reuse of etag for 'files/test.txt' !!!
```

From what I remember this message is harmless, we should look into removing it as it can be misleading.

@icewind1991 can you confirm ?

**Comment by karlitschek** [comment]
agreed. This should go away! 
@icewind1991

**Comment by DeepDiver1975** [comment]
Which log level has that message? From a debugging pov it might become interesting again one day. But afiak we did not see any etag related issues in the past month.

@dragotin we introduced this during a hack meeting in Stuttgart year(s) ago

**Comment by MorrisJobke** [comment]
fix is in #13301
