### ISSUE TITLE
[7.0.4] AD Connection kicked

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#13183]
### Expected behaviour
Configure 4 LDAP Server and work with them all

### Actual behaviour
Configure 4 LDAP Server and after each server will be randomly disabled

### Steps to reproduce
1. Configure LDAP 1 .... and is active (Green)
2. Configure LDAP 2 .... and is active (Green)
3. Configure LDAP 3 .... and is active (Green) but LDAP 1 or 2 is already disabled (RED)

### Extra notes

We configured the UserAuthentication for overall 4 AD Domains.

During the configuration of the AD Server we noticed that one AD
Connection worked fine (green field)
but after I configured the next AD Connected the previews Connection is
now dispayed as wrong (red field).

At the end of december I configured the AD connection, afterwards I closed Owncloud Webinterface.
Today I opened the Webinterface again and noticed that 3 of 4 AD Server connections are displayed as failure.

### Server configuration
**Operating system**: Ubuntu

**Web server:**
Apache2

**Database:**
MySQL

**PHP version:**
PHP 5.4

**LDAP:**
Microsoft AD

**ownCloud version:** (see ownCloud admin page)
7.0.4 EE
**Updated from an older ownCloud or fresh install:**
Fresh

@MorrisJobke 

00002349

**Comment by MorrisJobke** [comment]
@cdamken Is this what you described to me in Nuremberg before chrismas and I couldn't reproduce and then you also couldn't reproduce anymore?

**Comment by MorrisJobke** [comment]
@blizzz I guess the problem here lies just in the JS code of the LDAP wizard. Can this be made more robust against context (connection) changes and assistent steps?

**Comment by blizzz** [comment]
@cdamken any news?

**Comment by blizzz** [comment]
@cdamken can we close it?

**Comment by cdamken** [comment]
@blizzz  We can close it, If it happens again (and I get mot information then I reopen it .

Thank you :)
