### ISSUE TITLE
Single quotes not escaped when fetching files from mounted volume

### ISSUE THREAD

**Issue by Uldosphere** [owncloud/core#13189]
I'm having trouble syncing files on my local drive when filenames contains a single quote and are issued from my GoogleDrive mounted volume. 

Windows client crash : 
11:52     Gdrive/Documents/StBruno - Oenologie/2014 - Novembre - Alsace/CREMANT D'ALSACE.pdfownCloud       Error downloading https://cloud.uldosphere.org/remote.php/webdav/Gdrive/Documents/StBruno - Oenologie/2014 - Novembre - Alsace/CREMANT D'ALSACE.pdf - server replied: Internal Server Error

Apache access.log ispretty obvious : 

cloud.uldosphere.org:443 localhost - uld [09/Jan/2015:11:55:19 +0100] "GET /remote.php/webdav/Gdrive/Documents/StBruno%20-%20Oenologie/2014%20-%20Novembre%20-%20Alsace/CREMANT%20D'ALSACE.pdf HTTP/1.1" 500 860 "-" "Mozilla/5.0 (Windows) mirall/1.7.1"

Filename CREMANT%20D'ALSACE.pdf is not escaped on the single quote.

**Comment by MorrisJobke** [comment]
@Uldosphere Can you post the error in owncloud.log or the apache error log. That would help a lot to spot the code where the error occurs

**Comment by MorrisJobke** [comment]
cc @PVince81 You recently had a look at the files_external stuff

**Comment by Uldosphere** [comment]
@MorrisJobke sure, here is owncloud.log on the previous defectuous file : 

{"app":"remote","message":"Error calling GET https:\/\/www.googleapis.com\/drive\/v2\/files?q=title%3D%27CREMANT%20D%27ALSACE.pdf%27%20and%20%270BxrinKTGJnPab0ROVjdJbkVhUlE%27%20in%20parents%20and%20trashed%20%3D%20false: (400) Invalid Value","level":4,"time":"2015-01-09T11:13:44+00:00"}

**Comment by mikmakmuk** [comment]
@MorrisJobke I'm experiencing exactly the same behavior as @Uldosphere. Running owncloud 8.0.2. Any information we can provide to fix this?

**Comment by PVince81** [comment]
@mikmakmuk with GoogleDrive or without another external storage type ?

I suspect this might be specific to Google Drive

**Comment by mikmakmuk** [comment]
@PVince81 with GoogleDrive. It works with ownclouds' own storage. I've tested it with a dummy filename containing a single quote.
Uploading a filename with single quote through ownclouds' webinterface into a GoogleDrive folder fails too.

**Comment by PVince81** [comment]
Ok thanks.

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/core/pull/15215

**Comment by mikmakmuk** [comment]
@PVince81 Thanks for the fix, but this seems to introduce a regression. I've applied your fix on my 8.0.2 installation. Now I can't add files to a directory with a name that contains spaces. Error message on the owncloud web-interface when creating a file: "The target folder has been moved or deleted."

**Comment by PVince81** [comment]
Hmm strange that the unit tests didn't catch it.
Thanks for testing, I'll have a look. Maybe the Google API doesn't like encoded spaces.

**Comment by LukasReschke** [comment]
@mikmakmuk Please test https://github.com/owncloud/core/pull/15336

**Comment by mikmakmuk** [comment]
@LukasReschke tested #15336 on 8.0.2 and works (spaces in directory names and single quotes in file names).
