### ISSUE TITLE
OCP\User::getDisplayName() not returning external users

### ISSUE THREAD

**Issue by brantje** [owncloud/core#13194]
OCP\User::getDisplayName() does not return the Display name for an external user.

I'm using IMAP backend. 
The user display name is stored in oc_users_external, so i think its a little fix.

OS: 
Elementary OS

owncloud git (master)
mysql

Nothing in the log's (both web and owncloud)

I rather not post my config (since my mail server detail are in it) but this is in the oc_users_external (its only one row)
backend: {localhost:993/imap/ssl/novalidate-cert}	
uid: sander@azirly.nl	
displayname: Sander

**Comment by nickvergessen** [comment]
So apparently the call against the database is using an empty backend string.
The problem seems to be in the user manager somewhere? @icewind1991

**Comment by icewind1991** [comment]
Cant reproduce with master, the displayname is properly shown in the ui

**Comment by nickvergessen** [comment]
@icewind1991 seems like it does not work in the activity app (which uses `\OCP\Util::getDisplayName()`)

**Comment by icewind1991** [comment]
Also works for me in the activity app (sharing from IMAP user to local user shows the displayname in the local user's activity)

**Comment by nickvergessen** [comment]
@brantje can you try to find out, where your backend is emptied
