### ISSUE TITLE
Drag-and-Drop upload in master is not working over empty space

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#13199]
With master as of today the drag-and-drop upload is not working over empty space, this is a regression as this worked in ownCloud 7.

![2015-01-09_15-43-29](https://cloud.githubusercontent.com/assets/878997/5681210/b8d460c8-9816-11e4-96d4-31a219ef7850.png)

@jancborchardt FYI

**Comment by DeepDiver1975** [comment]
@PVince81 @icewind1991 can you please have a look? THX

**Comment by PVince81** [comment]
This is likely due to recent changes to CSS where the file list container / drop container isn't taking the whole page.
