### ISSUE TITLE
can not upload changed shared file via syncclient with only change permissions

### ISSUE THREAD

**Issue by dttpy** [owncloud/core#13193]
### Steps to reproduce
1. log in with admin account
2. create a user "user1"
3. create a folder "sharetest"
4. share the folder "sharetest" with user1, but with only "change" permission
5. go into "sharetest" and create a text file "permissiontest.txt"
6. set syncclient account for user1
7. open the local "data" folder for user1
8. go into "sharetest" and open "permissiontest.txt"
9. make some changes of this text file and save it
10. wait for sync of syncclient (ERROR1)
11. rename the text file to "sharetest.txt"
12. wait for sync of syncclient (ERROR2)

### Expected behaviour
The changed file can be uploaded, and "admin" can see the changes of the file.

### Actual behaviour
ERROR1:
The changed file can not be uploaded due to an error:
Error downloading http://192.168.1.80/owncloud704/remote.php/webdav/sharetest/permissiontest.txt - server replied: Internal Server Error (Could not write file contents) 

ERROR2: 
sharetest/sharetest.txt--Not allowed because you don't have permission to add files in that directory          
sharetest/permissiontest.txt--Not allowed to remove, restoring          
sharetest/sharetest.txt--Not allowed because you don't have permission to add files in that directory    
      
User1 can find 2 text files in local sync client data/sharetest folder, permissiontest.txt (the origin one) and sharetest.txt (the changed one), but neither user1 or admin can get all these changes in the web ownCloud

### Server configuration
**Operating system:** Ubuntu 13.10

**Web server:** apache 2.4.6 (Ubuntu)

**Database:** SQLite

**PHP version:** 5.5.3-1ubuntu2.3

**ownCloud version:** 7.0.4 & master

**Updated from an older ownCloud or fresh install:** owncloud 7.0.3

**List of activated apps:** standard apps of owncloud

**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password and passwordsalt)
$CONFIG = array (
  'instanceid' => 'oc6d9cda6e26',

  'datadirectory' => '/var/ocdata/.../owncloud/data',
  'dbtype' => 'sqlite3',
  'version' => '7.0.4.2',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'maxZipInputSize' => 838860800,
  'allowZipDownload' => true,
  'loglevel' => '0',
  'trusted_domains' => 
  array (
    0 => '192.168.1.80',
  ),

);
```

**Are you using external storage, if yes which one:** no
**Are you using encryption:** yes

### Client configuration
**Browser:** firefox 34.0.5

**Operating system:** ubuntu 13.10

#### Web server error log
```

```

#### ownCloud log (data/owncloud.log)
```

```

#### Browser log
```

```

**Comment by dttpy** [comment]
@PVince81

**Comment by SPQRInc** [comment]
Maybe related to this? https://github.com/owncloud/core/issues/12991

**Comment by PVince81** [comment]
The problem is as follows: when uploading the new copy of "permissiontest.txt" it will first create a part file "permissiontest.txt.octransferid123.part".
In fopen() from sharedstorage it will see that the file doesn't exist (the part file) so it will also check `isCreatable` which will return false.

We might want to add an exception there for part files.

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/core/pull/13802

**Comment by DeepDiver1975** [comment]
8.1 or 8.0.1 ?

@PVince81

**Comment by PVince81** [comment]
I'd say 8.1. This was already broken for a very long time and the fix is slightly risky.

**Comment by DeepDiver1975** [comment]
> I'd say 8.1. This was already broken for a very long time and the fix is slightly risky.
> Vincent Petry

THX

**Comment by MorrisJobke** [comment]
@PVince81 Do you have an idea how to solve this? @michaelstingl has this problem too.

**Comment by michaelstingl** [comment]
@MorrisJobke thanks!

00002734
