### ISSUE TITLE
Reshare with link when no update permission was given

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13198]
### Steps to reproduce
1. Create two users "user1" and "user2"
2. As "user1" create a folder "test"
3. Share "test" with "user2" but remove the "update" permission
4. Login as "user2"
5. Share "test" with link
6. Click "Allow editing"

### Expected result
At step 5, the "Allow editing" checkbox must NOT be visible

### Actual result
The "Allow editing" checkbox is visible.
When clicked, a popup error appears that permissions are not allowed.
After closing the popup, if you reopen the dropdown the share is lost.
This could cause trouble if the link share has already been sent to other people.

### Versions
OC 8 git master master a5099b01f93ec81602c8facba04233c7bc65ed47

CC @schiesbn @jnfrmarks

**Comment by rullzer** [comment]
This seems fixed in master

**Comment by rullzer** [comment]
Just checked again. This is fixed on master.
