### ISSUE TITLE
Only one plugin active at a time?

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/core#13197]
I am working on a plugin which sends change notifications via long polling.

I created a route in ```routes.php``` to my poll controller similar to this:

    $this->create('PollController', '/poll')->actionInclude('web_hooks/PollController.php');

```PollController.php``` is obviously contains a blocking function call.

Problem here: As long as one instance of ```PollController.php``` is running, no other plugin can be called. Indeed, owncloud itself (```index.php```) can also not be called.

Is this behaviour by design? Is something wrong with my installation?

Using: Version 7.0.4 with Apache and PHP module (no CGI)

**Comment by DeepDiver1975** [comment]
Most probably other requests are blocked because the session is locked - close the session in the controller - there is an annotation for it meanwhile

**Comment by LukeOwncloud** [comment]
Thanks! That is it!

For the record: I just needed to call

    \OC::$server->getSession()->close();

before doing the waiting.
