### ISSUE TITLE
unable to delete files from trash if there is a lot of files in it

### ISSUE THREAD

**Issue by kiswap** [owncloud/core#13203]
If you have several files in trash (100G+) then it is impossible to delete them permanently because:
apps/files_trashbin/lib/trashbin.php line:~889
$storage->getScanner()->scan('files_trashbin');
forces to rescan path which takes a lot of time. It causes webserver to hang without notifying the user.
commenting out that line results in quick file deletions, but the db operations (delete from filecache) is still very slow, as it deletes every file in separated sql queries.

Is it necessary to always rescan the directory? Is it possible to fasten queries?
I'm not sure, if it's the same with other directories.

**Comment by PVince81** [comment]
@schiesbn what do you think ?

I thought the rescan would be done after deletion, not before.

**Comment by PVince81** [comment]
Closing as duplicate.
See https://github.com/owncloud/core/issues/13974#issuecomment-77531761

You were right, the scanner needlessly rescans the version for every file. There's a fix in the linked ticket.
