### ISSUE TITLE
[6.0.6] Thumbnails of 140MB photo files result in a timeout error of the WebGUI

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#13218]
A user who uploaded a 140MB photo and couldn’t access it from the Web-interface to share or download it because the thumbnail creation failed with a timeout.

I couldn’t find a setting in config.php to limit this behavior like only create thumbnails of files smaller then X size.

we cannot increase the execution time in the php.ini because it’s already 30 seconds; increasing it will only slow down the web interface and annoy other users.

I looked in the documentation but there is no way to adjust the behavior of the thumbnail creation in ownCloud, so I need some kind of fix as such that we can influence the behavior.

For example, a max file size for thumbnails to be created.

@MorrisJobke 

00002256

**Comment by MorrisJobke** [comment]
@georgehrke Is there an easy way to limit the preview generation to a specific timeout and set it as default to not exceed the php session timeout and properly hand back a "no preview" response?

**Comment by DeepDiver1975** [comment]
In case preview generation times out this should not have an impact on the web ui behavior - this has to be analyzed first. @icewind1991 can you please have a look? THX

**Comment by georgehrke** [comment]
> @georgehrke Is there an easy way to limit the preview generation to a specific timeout and set it as default to not exceed the php session timeout and properly hand back a "no preview" response?

Not that I know of (, maybe except for ```proc_open```). That's related to the discussion about the truck of death.

**Comment by MorrisJobke** [comment]
I will try to reproduce this with https://commons.wikimedia.org/wiki/File:Bath_from_alexandra_park.jpg

**Comment by DeepDiver1975** [comment]
THX @MorrisJobke

**Comment by MorrisJobke** [comment]
On master I get a 503, but the page keeps responsive. Only message I could found is in the error log:

```
[Mon Jan 12 11:13:07.566937 2015] [proxy_fcgi:error] [pid 3069:tid 140546412566272] (70007)The timeout specified has expired: [client ::1:56300] AH01075: Error dispatching request to : (polling), referer: http://localhost/master/index.php/apps/files/?dir=%2Fdsf
```

Next step: stable7

**Comment by MorrisJobke** [comment]
stable7 - same behaviour and I don't know why but everything is kind of lacking - tab changing - even changing tabs of my terminal and other applications like thunderbird.(this was also the case in master) Maybe it's caused by the high load on the server side part (as it is on the same machine)

Error in apache error log

```
[Mon Jan 12 11:17:15.648293 2015] [proxy_fcgi:error] [pid 3068:tid 140546420958976] [client ::1:56685] AH01067: Failed to read FastCGI header, referer: http://localhost/master/index.php/apps/files/
[Mon Jan 12 11:17:15.650823 2015] [proxy_fcgi:error] [pid 3068:tid 140546420958976] (104)Connection reset by peer: [client ::1:56685] AH01075: Error dispatching request to : , referer: http://localhost/master/index.php/apps/files/
```

**Comment by MorrisJobke** [comment]
Same on stable6. Everything get's laggy once I hit the upload button.

I experienced the same behaviour in Firefox and Chrome. Once the preview request is send. Everything stalls. I will try with an external server part.

**Comment by MorrisJobke** [comment]
Got it. It's the memory that is consumed a lot. Over 2 GB during the preview generation for that 100 MB image (the spike in the middle at 30 to 25 seconds):

stable6
![bildschirmfoto von 2015-01-12 11 28 09](https://cloud.githubusercontent.com/assets/245432/5701636/655adc30-9a4e-11e4-8d4b-5ebe98ef8671.png)

**Comment by MorrisJobke** [comment]
On stable7 it's a nearly similar graph: (I guess because of the cancelation of the request php-fpm still took the memory of this request but this gets vanished 1 minute later - more than 3 GB where free'd)

![bildschirmfoto von 2015-01-12 12 05 10](https://cloud.githubusercontent.com/assets/245432/5701971/98f67db0-9a53-11e4-94f5-0b1da5f5436c.png)

I would rate for a limitation of the resources here somehow. But I have no good idea, how we could do this.

**Comment by MorrisJobke** [comment]
Surprisingly the preview got's rendered fine (but you need a second request to show it. I guess this is the cause for the long memory consumption. The process finished it's processing and created the preview and put it into the preview cache.

**Comment by MorrisJobke** [comment]
I Noticed that there is a minor lag if I select the image in the dialog box of my browser. This is caused by the preview generation of the dialog window. So there is a way to generate the preview without using nearly every bit of the available memory. 

@georgehrke Can you have a look at reducing the memory usage of the preview generation process?

**Comment by MorrisJobke** [comment]
I just found that the image creation relies on our internal `OC_Image` I try to do this with imagick if it is installed and use just OC_Image as fallback.

**Comment by MorrisJobke** [comment]
I just noticed that it is not easiely migrateable as the preview  system makes highly usage of the OC_Image class. Needs discussion with @georgehrke How we could enhance this, because nowadays the full image gets loaded into memory via methods like `imagecreatefromstring`.

**Comment by georgehrke** [comment]
> @georgehrke Can you have a look at reducing the memory usage of the preview generation process?

Sure.

> I just noticed that it is not easiely migrateable as the preview system makes highly usage of the OC_Image class. Needs discussion with @georgehrke How we could enhance this, because nowadays the full image gets loaded into memory via methods like imagecreatefromstring.

We would probably have to refactor OC_Image to only store the path as long as possible and load the actual image only on demand. For printing we could use standard php functions like imagepng, etc.

**Comment by MorrisJobke** [comment]
Another option would be to just don't generate previews for files bigger than x MB.

**Comment by georgehrke** [comment]
> Another option would be to just don't generate previews for files bigger than x MB.

That's probably the best short-term solution for now, as refactoring OC_Image needs heavy testing.

**Comment by LukasReschke** [comment]
The real and enterprise-ready solution would be a MQ system where previews are generated from another system which is containered and properly segregated.

You simply don't want to run the preview generation of any filetype on the same machine in the same process for multiple reason:

1. Converters are often very prone to security bugs and if a third-party component such as imagemagick has a Security Bug this results often in a very bad result as an attacker could execute arbitrary shell code.
2. With PHP we cannot really limit how long a preview process should run or how much memory it should allocate and then gracefully quit. With an external system we can.

**Comment by DeepDiver1975** [comment]
> Another option would be to just don't generate previews for files bigger than x MB.
> 
> That's probably the best short-term solution for now, as refactoring OC_Image needs heavy testing.

Can we please have a PR to introduce this max image size for preview generation? @georgehrke any time for this? THX

**Comment by DeepDiver1975** [comment]
> I just found that the image creation relies on our internal OC_Image I try to do this with imagick if it is installed and use just OC_Image as fallback.

tech dept please - thx @MorrisJobke

**Comment by georgehrke** [comment]
> @georgehrke any time for this? THX

Saturday

**Comment by georgehrke** [comment]
Do we want a max file size for any file or only for images?

**Comment by DeepDiver1975** [comment]
For sure not on movies ;-)

Basically this depends on the preview implementation .....

**Comment by georgehrke** [comment]
Ok, so let's add a limit to the image backend, that uses OC_Image, for now.
What's a good default limit? 100MB?

**Comment by MorrisJobke** [comment]
not more than 50 MB. The 100 MB picture takes nearly 4 GB of RAM here.

**Comment by georgehrke** [comment]
> not more than 50 MB.

Ok.

> The 100 MB picture takes nearly 4 GB of RAM here.

:frowning: How can that take 4GB of RAM?!

**Comment by MorrisJobke** [comment]
It was a typo. Just 3 GB. See graphs above ;) I guess it will save this as a bitmap internally to convert it from this to any other image file format ;)It was a 100 MB JPG (50,000 × 15,596 pixels) ;)

**Comment by georgehrke** [comment]
here is the pr: https://github.com/owncloud/core/pull/13449, please test

**Comment by oparoz** [comment]
@georgehrke - You may also want to take a look at this:
https://github.com/owncloud/core/blob/master/lib/private/image.php#L470
On a system using Imagick, this is preventing previews from being displayed because it exhausts PHP memory.

**Comment by cdamken** [comment]
>On a system using Imagick, this is preventing previews from being displayed because it exhausts PHP memory.

I suppose that is what happens in my system

**Comment by oparoz** [comment]
Try commenting out that line‎ and refresh a folder to see if
thumbnails get generated


   FROM: Carlos Damken
SENT: Monday, 19 January 2015 21:19
TO: core@noreply.github.com
REPLY TO: owncloud/core
CC: Olivier Paroz
SUBJECT: Re: [core] [6.0.6] Thumbnails of 140MB photo files result in a
timeout error of the WebGUI (#13218)>> On a system using Imagick, this  
is preventing previews from being
