### ISSUE TITLE
star gone after rename a favorite folder

### ISSUE THREAD

**Issue by dttpy** [owncloud/core#13215]
### Steps to reproduce
1. create a folder "test" 
2. tag "test" as favorite
3. rename "test" to "testtest"

### Expected behaviour
folder's name changed and the star icon stayed

### Actual behaviour
folder's name changed and the star icon is gone, but after refreshing the page, the folder is still marked as favorite

### Server configuration
**Operating system:** Ubuntu 13.10

**Web server:** apache 2.4.6 (Ubuntu)

**Database:** SQLite

**PHP version:** 5.5.3-1ubuntu2.3

**ownCloud version:** owncloud 8 git master

**Updated from an older ownCloud or fresh install:** 

**List of activated apps:** standard apps of owncloud

**The content of config/config.php:**

**Are you using external storage, if yes which one:** no
**Are you using encryption:** yes

### Client configuration
**Browser:** firefox 34.0.5

**Operating system:** ubuntu 13.10

**Comment by dttpy** [comment]
@PVince81

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/core/issues/13272
