### ISSUE TITLE
Custom Built Python Webdav https versus http PROPFIND failing.

### ISSUE THREAD

**Issue by heathen711** [owncloud/core#13214]
I am building a custom webdav client for a mobile media storage device. I am building it in Python and I am using a pre-built library for the connection and management. Now the client can connect via http and send/receive perfectly but when trying to connect via https it seems like the server does not accept the authentication because the ssl_requests.log and the ssl_access.log will not show the user as authenticated in the request. So I started digging into the packets (client side) before they are sent and the header does include the basic auth as expected before being wrapped in ssl. But testing on owncloud side (really on the SabreDAV side) has eluded me. Can this be tested to see if it's something with my setup?

Setup:
Mac OS X Mavericks
MAMP Pro
PHP: 5.6.2
MySQL
Apache
Ports 80 & 443

I've included my client log which shows the header for the packet being sent and the response.

HTTP Headers: 

{'Content-Length': '0', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive', 'Accept': '*/*', 'User-Agent': 'python-requests/2.5.1 CPython/2.7.5 Darwin/13.4.0', 'Depth': '1', 'Authorization': 'Basic dGVzdDpib29icw=='}

python webdav-http.py:

[File(name='/remote.php/webdav/iTunes/', size=0, mtime='Thu, 08 Jan 2015 03:56:14 GMT', ctime='', contenttype=''), ... ]

HTTPS Headers:

 {'Content-Length': '0', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive', 'Accept': '*/*', 'User-Agent': 'python-requests/2.5.1 CPython/2.7.5 Darwin/13.4.0', 'Depth': '1', 'Authorization': 'Basic dGVzdDpib29icw=='}

python webdav-https.py:
Traceback (most recent call last):
  File "webdav.py", line 13, in <module>
    print webdav.ls("iTunes")
  File "/Users/god/Downloads/Python WebDav/easywebdav/client.py", line 176, in ls
    response = self._send('PROPFIND', remote_path, (207, 301), headers=headers)
  File "/Users/god/Downloads/Python WebDav/easywebdav/client.py", line 100, in _send
    raise OperationFailed(method, path, expected_code, response.status_code)
easywebdav.client.OperationFailed: Failed to list directory "iTunes".
  Operation     :  PROPFIND iTunes
  Expected code :  207 UNKNOWN, 301 Moved Permanently
  Actual code   :  403 Forbidden

ssl_request.log:
[09/Jan/2015:10:29:24 -0800] 76.95.128.199 TLSv1 DHE-RSA-AES256-SHA "PROPFIND /remote.php/webdav/iTunes HTTP/1.1" 226
[09/Jan/2015:10:32:08 -0800] 76.95.128.199 TLSv1 DHE-RSA-AES256-SHA "PROPFIND /remote.php/webdav/iTunes HTTP/1.1" 226

ssl_access.log: 
76.95.128.199 - - [09/Jan/2015:10:29:24 -0800] "PROPFIND /remote.php/webdav/iTunes HTTP/1.1" 403 226
76.95.128.199 - - [09/Jan/2015:10:32:08 -0800] "PROPFIND /remote.php/webdav/iTunes HTTP/1.1" 403 226

I have looked around and found several posts which pertain to webdav not working at all on apache due to other issues but mine works fine for both http and https via other applications (like cadaver and iOS applications)

The prebuilt class I'm using is here: https://github.com/amnong/easywebdav

webdav-http.py:
import easywebdav
import requests
user='test'
pw='######'
webdav = easywebdav.connect('h711.webhop.me',
                            username=user,
                            password=pw,
                            path="remote.php/webdav",
                            protocol='http', 
                            ##protocol='https',
                            verify_ssl='./h711.webhop.me.pem'
                            )
##Do some stuff:
print webdav.ls("iTunes")

**Comment by PVince81** [comment]
Are you using self-signed SSL certificates ?

**Comment by heathen711** [comment]
Yes but I pass the pem file for it to verify locally.

**Comment by PVince81** [comment]
Have you tried with `curl` and passing the certificate file ?

**Comment by heathen711** [comment]
Done some CURL commands and was able to authenticate it with the PEM file.
curl --cert cert.pem --user test:#### -url https://h711.webhop.me/remote.php/webdav/

H -i
HTTP/1.1 200 OK
Date: Wed, 25 Mar 2015 23:32:15 GMT
Server: Apache
X-Powered-By: PHP/5.6.2
Set-Cookie: occ943c76c1a=7fb36efe992f4166f969954062442cd4; path=/; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Strict-Transport-Security: max-age=31536000
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *; connect-src *
X-Robots-Tag: none
Set-Cookie: occ943c76c1a=6ed2e35d58d62d5fd0aa0ad4b14cfc29; path=/; secure; HttpOnly
Content-Length: 2958
Content-Type: text/html; charset=utf-8

<html>
<head>
  <title>Index for / - SabreDAV </title>
  <style type="text/css">
  body { Font-family: arial}
  h1 { font-size: 150% }
  </style>
        </head>
<body>
  <h1>Index for /</h1>
  	### Redacted for security ###
    <address>Generated by SabreDAV  (c)2007-2015 <a href="http://sabre.io/">http://sabre.io/</a></address>
</body>
</html>

**Comment by PVince81** [comment]
Any update ? This likely to be an environment issue.

Feel free to reopen if you're still having issues with OC 8.0.5.
