### ISSUE TITLE
[master] unit test execution on oracle is failing

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#13220]
https://ci.owncloud.org/job/server-master-linux/database=oci,label=SLAVE/lastCompletedBuild/console

````
00:16:18.836 PHP Fatal error:  Call to a member function clear() on null in /var/jenkins/workspace/server-master-linux/database/oci/label/SLAVE/apps/files_sharing/tests/watcher.php on line 75
00:16:18.836 PHP Stack trace:
00:16:18.836 PHP   1. {main}() /usr/local/bin/phpunit:0
00:16:18.836 PHP   2. PHPUnit_TextUI_Command::main() /usr/local/bin/phpunit:605
00:16:18.836 PHP   3. PHPUnit_TextUI_Command->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:138
00:16:18.836 PHP   4. PHPUnit_TextUI_TestRunner->doRun() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:186
00:16:18.836 PHP   5. PHPUnit_Framework_TestSuite->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/TestRunner.php:423
00:16:18.836 PHP   6. PHPUnit_Framework_TestSuite->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php:751
00:16:18.836 PHP   7. PHPUnit_Framework_TestCase->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php:751
00:16:18.836 PHP   8. PHPUnit_Framework_TestResult->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:711
00:16:18.836 PHP   9. PHP_Invoker->invoke() phar:///usr/local/bin/phpunit/phpunit/Framework/TestResult.php:641
00:16:18.836 PHP  10. call_user_func_array:{phar:///usr/local/bin/phpunit/php-invoker/Invoker.php:93}() phar:///usr/local/bin/phpunit/php-invoker/Invoker.php:93
00:16:18.836 PHP  11. PHPUnit_Framework_TestCase->runBare() phar:///usr/local/bin/phpunit/php-invoker/Invoker.php:93
00:16:18.836 PHP  12. Test_Files_Sharing_Watcher->tearDown() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:802

**Comment by DeepDiver1975** [comment]
@PVince81 can I ask you to apply some bisect magic?

This was the last successful execution: https://ci.owncloud.org/job/server-master-linux/757/
The first failing: https://ci.owncloud.org/job/server-master-linux/758/

THX

**Comment by PVince81** [comment]
Will do tomorrow when I get access to an Oracle machine.

**Comment by PVince81** [comment]
In case the logs expire, here are the commits from both runs:
- git bisect bad 800738f51a1031839711b53d6859b0ce188a8b4c
- git bisect good d2ca9e9c0faa3f6838482c14318a60b6c9e2a800

**Comment by DeepDiver1975** [comment]
$
 git bisect bad
ad8d55c3274e81dd4fd92b41ac5d6ef5c39febf3 is the first bad commit
commit ad8d55c3274e81dd4fd92b41ac5d6ef5c39febf3
Author: tbelau666 <thomas.belau@gmx.de>
Date:   Sun Nov 30 23:17:09 2014 +0100

    Use Doctrines filter by table name
    
    Doctrine's SchemaManager can filter table names by regular expression.
    On this way it picks up only ownClouds's tables in a database.
    
    by tbelau666

:040000 040000 dd2f40bb365d15a02ec7b44fdfb95eba5f44a9cf 5b1eb883ead19c318a03eb2c3c8eab24dd3184d3 M	core
:040000 040000 1f5b1ce3d01ebcac482c59e2cda479df56764c40 b9f021246b1bf9118abcd94dbe623ab84c7fcf15 M	lib
