### ISSUE TITLE
Setup mutation testing on Jenkins

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#13239]
Something like https://github.com/padraic/humbug would be great to have:

> Mutation Testing is, in a nutshell, giving your unit tests a run for their money. It involves injecting small defects into source code and then checking if the unit tests noticed. If they do, then your unit tests have "killed" the mutation. If not, the mutation has escaped detection. As unit tests are intended to prevent regressions, having a real regression pass unnoticed would be a bad thing!
> 
> Whereas Code Coverage can tell you what code your tests are executing, Mutation Testing is intended to help you judge how well your unit tests actually perform and where they could be improved.

@DeepDiver1975 FYI

**Comment by PVince81** [comment]
we'll likely never have time for this, closing
