### ISSUE TITLE
Renaming a folder using the web interface

### ISSUE THREAD

**Issue by boschma1** [owncloud/core#13231]
Hi there

I am running OC 7.0.4 and yesterday I renamed a folder using the web interface. After several minutes I noticed that on my synced clients as well on the web interface all the files in this folder had gone.

After I reverted the folder name to its original name, all the content was there again and even the synced clients showed the folders and files again.

Please advise.

**Comment by LukasReschke** [comment]
Thanks a lot for reporting issues back to us!

We need some more information to properly support you with your issue!

Can I ask you to follow our guidelines for submitting bugs as described here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

Thanks a lot!

**Comment by PVince81** [comment]
Are you using encryption ? Is this a big folder with lots of files ?

**Comment by PVince81** [comment]
Is it a shared folder ? Or a subfolder inside a shared folder ? Is the renaming user the owner or receiver of the share ?

**Comment by DeepDiver1975** [comment]
no feedback -> close
