### ISSUE TITLE
Any reason to expose tmp directory in response value?

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#13234]
When uploading files:
```json
[
    {
        "id": 2122,
        "parentId": "2121",
        "date": "10. Januar 2015 um 10:55:34 MEZ",
        "mtime": 1420883734000,
        "icon": "/core/img/filetypes/file.svg",
        "name": "Thumbs.db",
        "permissions": 27,
        "mimetype": "application/octet-stream",
        "size": 44032,
        "type": "file",
        "etag": "9a0ec1a78aab749baa0da6f702244b70",
        "status": "success",
        "originalname": "/private/var/tmp/php25k3LL",
        "uploadMaxFilesize": 537919488,
        "maxHumanFilesize": "513 MB",
        "directory": "/A/vbc/img"
    }
]
```

Is there any reason that we expose the tmp directory where that file was stored?

@icewind1991

**Comment by DeepDiver1975** [comment]
> Is there any reason that we expose the tmp directory where that file was stored?

seriously - no - please kill it @icewind1991 @VicDeo

**Comment by PVince81** [comment]
@LukasReschke I think "originalname" was maybe used for the overwrite dialog in case of conflicts. But am not 100% sure. If it is, it's not supposed to contain the temp name but probably the real name.

**Comment by PVince81** [comment]
CC @butonic
