### ISSUE TITLE
Problems converting from sqlite to postgres

### ISSUE THREAD

**Issue by hannesa2** [owncloud/core#13233]
my currently config.php (as I understood, before converting it should point to sqlite, am I right ?)

    <?php
    $CONFIG = array (
      ...
      'dbtype'        => 'sqlite3',

but with this command 

    sudo ./occ db:convert-type –-password="mypass" –-all-apps pgsql oc_user localhost owncloud

I run into 
                       
    [RuntimeException]   
    Too many arguments.  
                       
any hints what's wrong ?
Thank you

**Comment by MorrisJobke** [comment]
@hannesa2 The first dash of `--password` isn't a normal dash. It's a longer version. 

Our command is the top one. The fixed command is the lower one:

```
sudo ./occ db:convert-type –-password="mypass" –-all-apps pgsql oc_user localhost owncloud
sudo ./occ db:convert-type --password="mypass"--all-apps pgsql oc_user localhost owncloud
```

**Comment by MorrisJobke** [comment]
As this is just a typo issue, I will close this.
