### ISSUE TITLE
search results -  should include full directory and be sorted 

### ISSUE THREAD

**Issue by ferdiga** [owncloud/core#13240]
hover over the results just shows the parent - which is not sufficient (at least in my case)
example 
the structure is
company name/year/budget

![owncloud search](https://cloud.githubusercontent.com/assets/6248560/5691428/25f359de-98c6-11e4-8010-b6431fa66a4a.jpg)

**Comment by LukasReschke** [comment]
The search has received a major overhaul for ownCloud 8 and will also show the file path. – If you're interested in checking it out you can clone the GIT version of ownCloud and test it.

**Comment by LukasReschke** [comment]
A short preview:

![screen shot 2015-01-10 at 12 47 42](https://cloud.githubusercontent.com/assets/878997/5691448/e64e015c-98c6-11e4-8885-7a0dd5482e25.png)

**Comment by ferdiga** [comment]
the screenshot shows that the list is not sorted (directory for each term found)

**Comment by LukasReschke** [comment]
Fair point – can I ask you to create a new ticket and also give some examples how you want it to be ordered?
