### ISSUE TITLE
Detected an illegal character in input string at ....

### ISSUE THREAD

**Issue by ferdiga** [owncloud/core#13243]
it would be helpful to get the directory/filename to correct the problem

![image](https://cloud.githubusercontent.com/assets/6248560/5691838/a082f754-98da-11e4-82d6-d3f475a7960e.png)

**Comment by RealRancor** [comment]
Hi,

seems this is related to the search_luncene app where you can find the issue tracker here:

https://github.com/owncloud/search_lucene

It could be also useful to fill out the issue template provided here:

https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

as asked in the "guidelines for contributing" (linked in the box when creating a new issue).

**Comment by MorrisJobke** [comment]
cc @butonic Is this maybe an already fixed issue?

**Comment by PVince81** [comment]
Please reopen in https://github.com/owncloud/search_lucene and make sure to at least specify the ownCloud version you are using. Thanks.
