### ISSUE TITLE
OC8 Alpha 1: Upload from the Android App fails with larger files (>5mb)

### ISSUE THREAD

**Issue by derkostka** [owncloud/core#13242]
Steps to reproduce

Upload a file using the Android app
Expected behaviour

File upload shall work
Actual behaviour

File Upload failes when reaching 100%

Operating system: Ubuntu 14.04
Web server: apache2
Database: mySQL
PHP version: PHP 5.5.9-1ubuntu4.5
ownCloud version: Owncloud 8 Alpha 1
Updated from an older ownCloud or fresh install: update from master from 18.12.
Are you using external storage: yes, local file system
Are you using encryption: no

Logs

Log after uploading from Android APP (1.6.2):
{"reqId":"46db30c48b995522ad3102bc917378c6","remoteAddr":"2a02:908:d111:8ec0:e093:1fbc:b290:a710","app":"PHP","message":"Call to a member function getMimetype() on a non-object at \/var\/www\/owncloud\/lib\/private\/files\/node\/node.php#277","level":3,"time":"January 10, 2015 14:34:36"}
{"reqId":"77db6e853270e58f7509d1fa2a810324","remoteAddr":"2a02:908:d111:8ec0:e093:1fbc:b290:a710","app":"files","message":"Upload error: 3 - Die Datei konnte nur teilweise \u00fcbertragen werden","level":3,"time":"January 10, 2015 14:39:27"}
{"reqId":"21bbdc7ede738d3f373485fca7fc6aff","remoteAddr":"2a02:908:d111:8ec0:e093:1fbc:b290:a710","app":"PHP","message":"Call to a member function getMimetype() on a non-object at \/var\/www\/owncloud\/lib\/private\/files\/node\/node.php#277","level":3,"time":"January 10, 2015 14:43:24"}

**Comment by DeepDiver1975** [comment]
@icewind1991 @VicDeo can you please have a look? THX

**Comment by derkostka** [comment]
The Problem is described also in #12766 (getMimeType missing)

**Comment by PVince81** [comment]
The Android app uses WebDAV to upload files, which itself doesn't use the Node API (through SabreDAV the internal $view API is used), so not sure what is causing this to happen ?

@derkostka do you have any third party apps enabled that might try and do something with uploaded files ?

I'm able to upload big files properly through WebDAV on 8.0.0alpha1 and master.

**Comment by PVince81** [comment]
From here https://github.com/owncloud/core/issues/13096 I guess you have the music app enabled ?
@MorrisJobke I suppose the music app checks every uploaded file to see if it's a music file ? (using the Node API)
Might explain this issue above.

**Comment by MorrisJobke** [comment]
Yes. The music app uses the node API

**Comment by icewind1991** [comment]
From #13096 it looks like it's related to the music app trying to scan .part files.

Might be fixed with #13317

**Comment by derkostka** [comment]
@icewind1991  this issue is definitly fixed for me with #13317 . The Upload Status remains 5-10 seconds at 100%, but all uploads finish. :+1:  and thank you

**Comment by DeepDiver1975** [comment]
@derkostka I assume we can close this now? The fix will be available with the next release of OC7 and OC8

**Comment by derkostka** [comment]
Yes ! Done ;) Thank you, you all do awesome things for us users ...
