### ISSUE TITLE
"Paste URL here" placeholder

### ISSUE THREAD

**Issue by wakeup** [owncloud/core#13255]
What do you think adding a placeholder into "From link" input field? Something like:

![image](https://cloud.githubusercontent.com/assets/231068/5695572/77a151f6-99ab-11e4-9ea4-ba6ae4dd5e1a.png)

It is very minor, but nice to see at least a text instead of a blank field IMO.

@jancborchardt

**Comment by jancborchardt** [comment]
A better placeholder for it would be something like `https://…` I think. That’s somehow a standard placeholder for that.

**Comment by jancborchardt** [comment]
cc @owncloud/designers

**Comment by enoch85** [comment]
Agreed on `https://…` :+1:
