### ISSUE TITLE
Search results are not localized

### ISSUE THREAD

**Issue by wakeup** [owncloud/core#13259]
I am unable to find it why, but search.js strings are not parsed for translation. They are not on transifex either.

https://github.com/owncloud/core/blob/master/search/js/search.js#L211

**Comment by karlitschek** [comment]
@butonic

**Comment by DeepDiver1975** [comment]
The script to extract the strings does not touch the search folder. 
What about moving search inside core?
Seems to be a leftover from the very first versions where e.g. files lived in root as well.

**Comment by DeepDiver1975** [comment]
> What about moving search inside core?

@VicDeo can I ask you to submit a PR which gives this a try? THX

**Comment by MorrisJobke** [comment]
@DeepDiver1975 Why not into a separate app?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 Why not into a separate app?

yet another search app? No - THX :speak_no_evil:

**Comment by DeepDiver1975** [comment]
seriously now - these few file contain the basic skeleton of the search mechanism - more part of core then anything else

**Comment by MorrisJobke** [comment]
With the next translation run it (hopefully) will sync the search translations
