### ISSUE TITLE
Issue Reporter application

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#13258]
As I often see a lot of issue reports that are missing nearly every required information to properly debug it I thought maybe a small issue reporter application can help to increase the quality.

This reporter will automatically gather most of the information for the issue template and offer some nice input boxes for all other stuff.

The following information will be automatically determined:
- Server OS
- Webserver
- Database
- PHP version
- ownCloud version
- Activated apps
- Disabled apps
- Config file 
- Client browser
- ownCloud logs (with a notice that users should look through them for potential sensitive entries)

Things the user is asked to enter:
- Issue title
- Expected behaviour
- Actual behaviour
- Reproduction steps
- Installation history
- Whether External storage is used
  - We cannot determine this automagically due to performance reasons
- Web server logs
- Browser logs

Some screenshots for folks that don't want to checkout the branch:
![screen shot 2015-01-11 at 18 42 03](https://cloud.githubusercontent.com/assets/878997/5696106/946bf00a-99c1-11e4-8709-ae35548e0584.png)
![screen shot 2015-01-11 at 18 42 11](https://cloud.githubusercontent.com/assets/878997/5696105/946ad1fc-99c1-11e4-916f-f5dc8edb2907.png)

You can take a look at it here: https://github.com/LukasReschke/issuereporter/pull/1

Please share your thoughts and let me know if this is something that we want. If not, I don't mind, that's why most of the code is also yet a quick and dirty hack since I didn't want to invest ages for something that we don't use then ;-)

Let's summon the usual folks:

@karlitschek @icewind1991 @schiesbn @georgehrke @blizzz @tomneedham @jancborchardt @DeepDiver1975 @PVince81 @jospoortvliet @MorrisJobke - hope I forget nobody that could be interested in sharing some thoughts ;-)

**Comment by LukasReschke** [comment]
The output will be the same issue template as we use today: https://github.com/LukasReschke/issuereporter/blob/7fc5de6c6558b37a80c738e49fa186dd5d87bbef/templates/issue.template.php

**Comment by DeepDiver1975** [comment]
:+1: awesome!

**Comment by wakeup** [comment]
Woww! Great! I loved it.

**Comment by jancborchardt** [comment]
Awesome! It looks really nicely designed already. ;) Was the HTML+CSS easy to do or did you have problems?

**Comment by LukasReschke** [comment]
> Was the HTML+CSS easy to do or did you have problems?

Actually it was pretty easy to do – I just used standard components and with the `ocdev` tool you get the basic boilerplate code for free.

So what we have here is:

1. The standard navigation
2. The standard app layout using `<div class="section">`, `<h2>` and `<em>`
3. A single CSS rule for textarea and input to have 100% width

Was pretty amazing to see with what little effort from my side I get that result. Kudos for that sanity in the CSS :-)

**Comment by karlitschek** [comment]
awesome!!!!!!  :-)

**Comment by MorrisJobke** [comment]
I really like it :) :+1:

**Comment by ferdiga** [comment]
great, thank you for picking up the idea
nevertheless I can not follow your arguments here:
```
Whether External storage is used
We cannot determine this automagically due to performance reasons
```
in the admin screen the external storages are listed, hence these must be easily accessible.

**Comment by LukasReschke** [comment]
We can get system mounts but to my understanding for user mounts we would need to have to parse all mount.json files for the user which would take a lot of time.

@icewind1991 Or can we use some SQL magic to get a list of available mounts and mount types?

**Comment by ferdiga** [comment]
To my understanding admin (it is not a superuser like root) and the person using this account will know nothing about other user mounts

**Comment by PVince81** [comment]
@LukasReschke in the current version you cannot find personal mounts without parsing the mount.json of all users. I'd say leave it for now and raise an issue for later.
In the future the mount config will be moved to the database as per https://github.com/owncloud/core/issues/11261

**Comment by blizzz** [comment]
+345643

**Comment by DeepDiver1975** [comment]
next level - submit button to create issue in github

**Comment by LukasReschke** [comment]
> next level - submit button to create issue in github

I'll investigate how that is possible the easiest way. I know that it is possible to prefill data via GET requests in issue forms but the problem with that is that we can't fill too much data into a GET variable. Via POST it seems not to be possible.

Optimal scenario: User clicks on Generate Report and gets redirected to the GitHub issue creation form with all things pre-filled.

Alternate scenario: I use OAuth and the GitHub API to create that issue for the user, this requires some more magic on our side but should work too – https://developer.github.com/v3/issues/#create-an-issue

Let me get in touch with the GitHub support regarding that matter and then decide what the way to go would be :-)

Currently the output is something like that (URLs are not yet properly highlighted):
![screen shot 2015-01-12 at 13 03 57](https://cloud.githubusercontent.com/assets/878997/5702511/7d208c54-9a5b-11e4-83ed-dff490f46b60.png)

I'll clean-up the code a little bit on my repository later (sometime around this week where I feel like it ;-)), add tests and co, and then I'd propose that we move this to the ownCloud GH organisation in some dedicated repo?

**Comment by MorrisJobke** [comment]
I would liek the prefilled new issue form. As then we have a way to contact that person. Otherwise the issue is created by our account and we have no way to contact the person reporting back.

**Comment by LukasReschke** [comment]
> I would liek the prefilled new issue form. As then we have a way to contact that person. Otherwise the issue is created by our account and we have no way to contact the person reporting back.

Well - the plan was to give the user an OAuth login form for GitHub and then file the issue using his account :-)

**Comment by LukasReschke** [comment]
(Please notice that I didn't take a look yet at their whole API specification, but I guess this should be possible … somehow ;-))

**Comment by LukasReschke** [comment]
Got a reply from the awesome GitHub support:

1. Relying on the GET parameters is not recommended. There is no POST endpoint (yet?)
2. OAuth and an alternative copy-paste option would be the "best way to go"

I think I'll stick with 2 then.

**Comment by tomneedham** [comment]
> next level - submit button to create issue in github

I just hope this doesn't turn into 'free owncloud support' and we get a flood of people who just want help and haven't searched for existing bugs/issues/docs...

**Comment by DeepDiver1975** [comment]
> I just hope this doesn't turn into 'free owncloud support' and we get a flood of people who just want help and haven't searched for existing bugs/issues/docs...

Good point actually - @LukasReschke what about adding a note on top to tell the user to only use this in case of error and link forum and faq for help?

**Comment by ferdiga** [comment]
IMO the problem is that there are issues for every subproject 
* at least for me it is not clear where to search - 4 pages of unsorted !! sub projects
* neither it is clear where to submit the new issue. as a user I can only guess where the problematic code could be.

**Comment by LukasReschke** [comment]
We can add a select box where the user has to select the application which behaves buggy and then redirect / create the issue in the right repository.

**Comment by ferdiga** [comment]
+1

**Comment by jancborchardt** [comment]
Yeah, good call. If we go crazy with the Github API we could even automatically search through the existing issues and display the 5 closest results. Then people could say »yeah, that’s the issue I have«. Some issue trackers (I think) do it like that – for sure a lot of FAQ pages do that.

**Comment by Xenopathic** [comment]
What's the progress on this? Perhaps you could merge the functionality requested in #9152 ?

**Comment by oparoz** [comment]
>  If we go crazy with the Github API we could even automatically search through the existing issues and display the 5 closest results

That.

Also, it would be good to have a log anonymizer for IP, username, etc.

**Comment by enoch85** [comment]
Wow! Nice! My respect to you @LukasReschke

**Comment by enoch85** [comment]
8.2?

**Comment by PVince81** [comment]
If the app code still exists, would need to be revived or rewritten and pushed to a separate repo and published to "marketplace".

Note that currently we already have a configreport app here https://github.com/owncloud/configreport, maybe that one could just be extended to implement the above stuff.

I'll open a ticket there and point here.

**Comment by PVince81** [comment]
ref https://github.com/owncloud/configreport/issues/43
