### ISSUE TITLE
Invalid email: .systems domain

### ISSUE THREAD

**Issue by strahlex** [owncloud/core#13252]
Owncloud seems not to support Email addresses with .systems domain. Why? Syntax checking is fine, but why do you check the top level domain name? Domain names will get even more in the future.

**Comment by karlitschek** [comment]
can you post a full bug report using the issue template please?

**Comment by karlitschek** [comment]
@nickvergessen

**Comment by strahlex** [comment]
@karlitschek Where can I find the template?

**Comment by karlitschek** [comment]
https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by RealRancor** [comment]
Hi,
@strahlex 

are you getting this message in the contacts app? At least the message "invalid email" leads to:

https://github.com/owncloud/contacts/blob/v7.0.4/js/app.js#L505

where this regex could cause this:

https://github.com/owncloud/contacts/blob/v7.0.4/js/app.js#L484

**Comment by strahlex** [comment]
When I enter my email address in the user settings a red field with "invalid email" is displayed. However, when I hit the return button the email address is accepted anyway.

**Comment by RealRancor** [comment]
Hi,

seems not an issue with phpmailer shipped with OC (just place this file into the root of your OC installation):

```
<?php

require '3rdparty/phpmailer/phpmailer/PHPMailerAutoload.php';

var_dump(PHPMailer::validateAddress('test@test.systems'));
?>
```

Result:

```
bool(true)
```

**Comment by strahlex** [comment]
The address actually works. The message is just confusing.

**Comment by nickvergessen** [comment]
I can not reproduce any troubles here on master/alpha1
the field is never marked red, and after the timeout or pressing enter the green "Email saved" appears.

**Comment by RealRancor** [comment]
Is this related to https://github.com/owncloud/core/issues/16720 ?

**Comment by MorrisJobke** [comment]
Works on master and 8.2 - we also switched to swiftmailer in 8.1, which maybe has solved this.

@strahlex If you experience this issue with 8.1+ please report back and I will reopen this ticket. Thanks
