### ISSUE TITLE
OwnCloud Windows and iOS clients report wrong value for the storage space and and it stopped changing

### ISSUE THREAD

**Issue by Biopticon** [owncloud/core#13260]
Hello 
After synching some files and showing the progress properly, the Windows and the iOS clients now report a non-changing value of 78GB for the storage use (See the picture below). 

![capture](https://cloud.githubusercontent.com/assets/6756426/5696346/fd880bd6-999a-11e4-98a6-776e9452be32.JPG)

But, a query run in phpmyAdmin reports 84GB which is similar to the number reported by the command "df -h" (see below).  

![capture2](https://cloud.githubusercontent.com/assets/6756426/5696354/4aa96cac-999b-11e4-97e1-120eb4c60a3d.JPG)

The fact that the storage space report is wrong and not changing although synchronization keeps going could be a bug (I am using v 7.0.4 for the server, and v 1.7.1 for the windows client).

Thanks.

**Comment by LukasReschke** [comment]
Thanks a lot for reporting issues back to us!

We need some more information to properly support you with your issue!

Can I ask you to follow our guidelines for submitting bugs as described here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

Thanks a lot!

**Comment by Biopticon** [comment]
Hello Lukas,

This is as much as I can do:

### Steps to reproduce
The storage usage reported by the desktop client is not changing although more files are synched to the storage.

1.Run owncloud desktop client
2.Check storage used
3.Run a sql query in phpmyadmin to compare reported value

### Expected behaviour
Storage usage value of  the server should increase  as more files are transferred the storage.

### Actual behaviour
This value stopped changing

### Server configuration
OS: Debian (on Rapberry pi)

**Web server:**
apache2 v2.2-22

**Database:**
Mysql v5.5.40

**PHP version:**
php v5.4.35

**ownCloud version:** (see ownCloud admin page)
owncloud v 7.0.4.2

**List of activated apps:**
email
external storage

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'oc080d29a834',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => 'www.myserver.com',
  ),
  'datadirectory' => '/media/OwnCloud/data',
  'overwrite.cli.url' => 'https://www.myserver.com/owncloud',
  'dbtype' => 'mysql',
  'version' => '7.0.4.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_user',
  'dbpassword' => '',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_from_address' => 'owncloud',
  'mail_domain' => 'comcast.net',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'smtp.comcast.net',
  'mail_smtpport' => '587',
  'mail_smtpname' => 'user',
  'mail_smtppassword' => 'xxxxxxx',
  'forcessl' => true,
  'debug' => true,
  'loglevel' => 0,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
/media/OwnCloud (external USB drive)

**Are you using encryption:** yes/no
At the beginning yes. Not now.

### Client configuration
**Browser:**
Mozilla v34.0.5

**Operating system:**
Win 7

### Logs
#### Web server error log
error.log:
...

stat: cannot stat `/media/OwnCloud/data/user/files_trashbin/files/2014-1010-162346--Excel.log.d1415718618': No such file or directory
[Sun Jan 11 20:17:19 2015] [error] [client 192.168.1.1] PHP Fatal error:  Maximum execution time of 3600 seconds exceeded in /var/www/owncloud/lib/private/files/storage/local.php on line 114
[Sun Jan 11 21:12:34 2015] [error] [client 110.77.179.60] File does not exist: /var/www/gigi
[Sun Jan 11 21:12:35 2015] [error] [client 110.77.179.60] File does not exist: /var/www/phpMyAdmin
[Sun Jan 11 21:12:36 2015] [error] [client 110.77.179.60] File does not exist: /var/www/pma
[Sun Jan 11 21:12:37 2015] [error] [client 110.77.179.60] File does not exist: /var/www/myadmin
[Mon Jan 12 00:40:38 2015] [error] [client 58.134.30.5] File does not exist: /var/www/oxox
[Mon Jan 12 00:40:39 2015] [error] [client 58.134.30.5] File does not exist: /var/www/phpMyAdmin
[Mon Jan 12 00:40:39 2015] [error] [client 58.134.30.5] File does not exist: /var/www/pma
[Mon Jan 12 00:40:40 2015] [error] [client 58.134.30.5] File does not exist: /var/www/myadmin

access.log:
...

190.151.14.190 - - [11/Jan/2015:18:21:29 -0500] "POST /cgi-bin/php4?%2D%64+%61%6C%6C%6F%77%5F%75%72%6C%5F%69%6E%63%6C%75%64%65%3D%6F%6E+%2D%64+%73%61%66%65%5F%6D%6F%64%65%3D%6F%66%66+%2D%64+%73%75%68%6F%73%69%6E%2E%73%69%6D%75%6C%61%74%69%6F%6E%3D%6F%6E+%2D%64+%64%69%73%61%62%6C%65%5F%66%75%6E%63%74%69%6F%6E%73%3D%22%22+%2D%64+%6F%70%65%6E%5F%62%61%73%65%64%69%72%3D%6E%6F%6E%65+%2D%64+%61%75%74%6F%5F%70%72%65%70%65%6E%64%5F%66%69%6C%65%3D%70%68%70%3A%2F%2F%69%6E%70%75%74+%2D%64+%63%67%69%2E%66%6F%72%63%65%5F%72%65%64%69%72%65%63%74%3D%30+%2D%64+%63%67%69%2E%72%65%64%69%72%65%63%74%5F%73%74%61%74%75%73%5F%65%6E%76%3D%30+%2D%6E HTTP/1.1" 404 493 "-" "Mozilla/5.0 (iPad; CPU OS 6_0 like Mac OS X) AppleWebKit/536.26(KHTML, like Gecko) Version/6.0 Mobile/10A5355d Safari/8536.25"
186.204.211.116 - - [11/Jan/2015:20:32:15 -0500] "-" 408 0 "-" "-"
110.77.179.60 - - [11/Jan/2015:21:12:34 -0500] "GET /gigi/gig/gi.php HTTP/1.1" 404 496 "-" "-"
110.77.179.60 - - [11/Jan/2015:21:12:35 -0500] "GET /phpMyAdmin/scripts/setup.php HTTP/1.1" 404 509 "-" "-"
110.77.179.60 - - [11/Jan/2015:21:12:36 -0500] "GET /pma/scripts/setup.php HTTP/1.1" 404 502 "-" "-"
110.77.179.60 - - [11/Jan/2015:21:12:37 -0500] "GET /myadmin/scripts/setup.php HTTP/1.1" 404 506 "-" "-"
58.134.30.5 - - [12/Jan/2015:00:40:38 -0500] "GET /oxox/oxo/ox.php HTTP/1.1" 404 496 "-" "-"
58.134.30.5 - - [12/Jan/2015:00:40:39 -0500] "GET /phpMyAdmin/scripts/setup.php HTTP/1.1" 404 509 "-" "-"
58.134.30.5 - - [12/Jan/2015:00:40:39 -0500] "GET /pma/scripts/setup.php HTTP/1.1" 404 502 "-" "-"
58.134.30.5 - - [12/Jan/2015:00:40:40 -0500] "GET /myadmin/scripts/setup.php HTTP/1.1" 404 506 "-" "-"

#### ownCloud log (data/owncloud.log)
...
{"reqId":"54b3789b5c0be","app":"webdav","message":"Sabre\\DAV\\Exception\\ServiceUnavailable: ","level":4,"time":"2015-01-12T07:32:43+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/documents\/Is\/Business%20Documents\/Biopticon%20Web%20Site_files\/image044.wmz"}
{"reqId":"54b3789c4d65f","app":"webdav","message":"Sabre\\DAV\\Exception\\ServiceUnavailable: ","level":4,"time":"2015-01-12T07:32:44+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/documents\/Is\/Business%20Documents\/Biopticon%20Web%20Site_files\/image045.wmz"}
{"reqId":"54b3789d21764","app":"webdav","message":"Sabre\\DAV\\Exception\\ServiceUnavailable: ","level":4,"time":"2015-01-12T07:32:45+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/documents\/Is\/Business%20Documents\/Biopticon%20Web%20Site_files\/image049.gif"}
{"reqId":"54b3789ddfe1d","app":"webdav","message":"Sabre\\DAV\\Exception\\ServiceUnavailable: ","level":4,"time":"2015-01-12T07:32:45+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/documents\/Is\/Business%20Documents\/Biopticon%20Web%20Site_files\/image050.gif"}
{"reqId":"54b3789eaf836","app":"webdav","message":"Sabre\\DAV\\Exception\\ServiceUnavailable: ","level":4,"time":"2015-01-12T07:32:46+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/documents\/Is\/Business%20Documents\/Biopticon%20Web%20Site_files\/image051.wmz"}
{"reqId":"54b3789f858b7","app":"webdav","message":"Sabre\\DAV\\Exception\\ServiceUnavailable: ","level":4,"time":"2015-01-12T07:32:47+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/documents\/Is\/Business%20Documents\/Biopticon%20Web%20Site_files\/oledata.mso"}
{"reqId":"54b378a0335e4","app":"webdav","message":"Sabre\\DAV\\Exception\\ServiceUnavailable: ","level":4,"time":"2015-01-12T07:32:48+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/documents\/Is\/Business%20Documents\/Biopticon%20Web%20Site_files\/imager.zip"}
{"reqId":"54b378a3d5c0c","app":"OC\\Files\\Cache\\Scanner","message":"!!! No reuse of etag for 'files_trashbin\/files\/983db650f7f79bc8e87d9a3ba418aefc.d1421047970' !!! \ncache: Array\n(\n    [fileid] => 94456\n    [storage] => home::user\n    [path] => files_trashbin\/files\/983db650f7f79bc8e87d9a3ba418aefc.d1421047970\n    [parent] => 62938\n    [name] => 983db650f7f79bc8e87d9a3ba418aefc.d1421047970\n    [mimetype] => httpd\/unix-directory\n    [mimepart] => httpd\n    [size] => 0\n    [mtime] => 1421047970\n    [storage_mtime] => 1421047970\n    [encrypted] => \n    [unencrypted_size] => 0\n    [etag] => 54b378a2e824f\n    [permissions] => 31\n)\n \ndata: Array\n(\n    [mimetype] => httpd\/unix-directory\n    [mtime] => 1408039907\n    [size] => -1\n    [etag] => 54b378a3d0654\n    [storage_mtime] => 1408039907\n    [permissions] => 31\n    [parent] => 62938\n)\n","level":0,"time":"2015-01-12T07:32:51+00:00","method":"DELETE","url":"\/owncloud\/remote.php\/webdav\/documents\/Is\/Business%20Documents\/Biopticon%20Documents\/983db650f7f79bc8e87d9a3ba418aefc"}
{"reqId":"54b378a3d5c0c","app":"OC\\Files\\Cache\\Scanner","message":"!!! No reuse of etag for 'files_trashbin\/files\/983db650f7f79bc8e87d9a3ba418aefc.d1421047970\/ Acceptance Letter.jpg' !!! \ncache: Array\n(\n    [fileid] => 94457\n    [storage] => home::user\n    [path] => files_trashbin\/files\/983db650f7f79bc8e87d9a3ba418aefc.d1421047970\/Acceptance Letter.jpg\n    [parent] => 94456\n    [name] =>  Acceptance Letter.jpg\n    [mimetype] => image\/jpeg\n    [mimepart] => image\n    [size] => 9640\n    [mtime] => 1421047972\n    [storage_mtime] => 1421047972\n    [encrypted] => \n    [unencrypted_size] => 0\n    [etag] => 54b378a4646d2\n    [permissions] => 27\n)\n \ndata: Array\n(\n    [mimetype] => image\/jpeg\n    [mtime] => 1404364353\n    [size] => 9640\n    [etag] => 54b378a4ce083\n    [storage_mtime] => 1404364353\n    [permissions] => 27\n    [parent] => 94456\n)\n","level":0,"time":"2015-01-12T07:32:52+00:00","method":"DELETE","url":"\/owncloud\/remote.php\/webdav\/documents\/Is\/Business%20Documents\/Biopticon%20Documents\/983db650f7f79bc8e87d9a3ba418aefc"}
{"reqId":"54b378a3d5c0c","app":"OC\\Files\\Cache\\Scanner","message":"!!! No reuse of etag for 'files_trashbin\/files\/983db650f7f79bc8e87d9a3ba418aefc.d1421047970\/ Application.jpg' !!! \ncache: Array\n(\n    [fileid] => 94458\n    [storage] => home::user\n    [path] => files_trashbin\/files\/983db650f7f79bc8e87d9a3ba418aefc.d1421047970\/Application.jpg\n    [parent] => 94456\n    [name] =>  Application.jpg\n    [mimetype] => image\/jpeg\n    [mimepart] => image\n    [size] => 9648\n    [mtime] => 1421047973\n    [storage_mtime] => 1421047973\n    [encrypted] => \n    [unencrypted_size] => 0\n    [etag] => 54b378a54c484\n    [permissions] => 27\n)\n \ndata: Array\n(\n    [mimetype] => image\/jpeg\n    [mtime] => 1404364354\n    [size] => 9648\n    [etag] => 54b378a5b4459\n    [storage_mtime] => 1404364354\n    [permissions] => 27\n    [parent] => 94456\n)\n","level":0,"time":"2015-01-12T07:32:53+00:00","method":"DELETE","url":"\/owncloud\/remote.php\/webdav\/documents\/Is\/Business%20Documents\/Biopticon%20Documents\/983db650f7f79bc8e87d9a3ba418aefc"}

**Comment by DeepDiver1975** [comment]
83891444069 bytes  = 81925238,3486328 kB = 80005,1155748367 MB = 78,1299956786	GB

**Comment by Biopticon** [comment]
Hello DeepDiver,

You are right! But I still do not understand how it is possible that this number is reached about ten days ago and did not change since then although many files are synched! Is OC reporting the used space ahead of copying the files? Thank you anyhow.
