### ISSUE TITLE
Webinterface: groups hidden behind app settings

### ISSUE THREAD

**Issue by MadEgg** [owncloud/core#13264]
When there are a lot of groups, the last group is invisible because the App-settings panel hides it at the bottom. This is in the User-management panel in OwnCloud 7.0.4.

What I did to work around this is add another bogus group called 'ZZZZZ' that will always end up at the end of the list to push the last item up a bit, but the proper solution would be that the scroll bar only extends up to the app settings panel instead of underneath it.

**Comment by jancborchardt** [comment]
Fix is at https://github.com/owncloud/core/pull/14970, please review @MadEgg :)

**Comment by MadEgg** [comment]
Sorry for not responding sooner. I just got around to checking this issue after an upgrade to OwnCloud 8.0.2, but I'm still experiencing the same problem.

The last group in the group list is still hidden behind the app settings panel. Are the changes in #14970 incorporated in 8.0.2?

**Comment by jancborchardt** [comment]
@MadEgg no, they weren’t backported as of now. So they will only be in 8.1 – however we might backport them so they will be in a future 8.0.* release. Thanks for reminding me. :)
