### ISSUE TITLE
Crontab time on Admin page, inconsistent time zone?

### ISSUE THREAD

**Issue by peterkahl** [owncloud/core#13262]
My crontab is running properly, every 15 minutes.
I am looking at the Admin page, the green indicator and the last timestamp of the crontab execution.
It was showing correct time (HK timezone) yesterday, but today it's showing time in GMT timezone.
WTF?

**Comment by DeepDiver1975** [comment]
> WTF?

https://owncloud.org/community/code-of-conduct/

**Comment by DeepDiver1975** [comment]
> It was showing correct time (HK timezone) yesterday, but today it's showing time in GMT timezone.

Maybe the session lost the timezone information .. needs to be analyzed

**Comment by peterkahl** [comment]
"Wait Till Further" is prohibited conduct?

--
"The two most important days in your life are the day you are born and the day you find out why." - Mark Twain

**Comment by PVince81** [comment]
Any steps to reproduce ?
See https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by peterkahl** [comment]
No longer can reproduce it.

On 2015-08-21 17:05, Vincent Petry wrote:
>
> Any steps to reproduce ?
> See 
> https://raw.githubusercontent.com/owncloud/core/master/issue_template.md
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/owncloud/core/issues/13262#issuecomment-133342434>.
>

-- 
Full Circle Reverse DNS (FCrDNS) aka Forward-confirmed Reverse DNS:
https://en.wikipedia.org/wiki/Forward-confirmed_reverse_DNS

SMTP Protocol:
"...The client initiates its dialog by responding with a HELO command identifying itself in the command's parameter with its FQDN..."
https://en.wikipedia.org/wiki/Simple_Mail_Transfer_Protocol

Fully Qualified Domain Name (FQDN):
https://en.wikipedia.org/wiki/Fully_qualified_domain_name

RFC2821:
https://tools.ietf.org/html/rfc2821

RFC2505, Anti-Spam Recommendations for SMTP MTAs:
https://tools.ietf.org/html/rfc2505

**Comment by PVince81** [comment]
Thanks, maybe it was a temporary glitch on the server timezone.
