### ISSUE TITLE
Web-Based Contributors Agreement??

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#13263]
@karlitschek I just came across https://code.facebook.com/cla

Could that be an option for us as well?

Pro:
- Have the list of contributors (including email for later communication) in some db
- Faster signup process
- No more manual administration by you
- Possibility to change the agreement and ask contributors to sign again

Cons:
- Yet another service to run ...

**Comment by DeepDiver1975** [comment]
> Yet another service to run ...

haha - not really - https://www.clahub.com/

**Comment by DeepDiver1975** [comment]
Test repo up and running - https://github.com/DeepDiver1975/requires-cla

**Comment by DeepDiver1975** [comment]
With this approach we can even apply CLAs to new repos as well - which would really be a great benefit thinking about the current size of core.

(Yes - I know - I'm always cooking up old stories :speak_no_evil: )

**Comment by PVince81** [comment]
@DeepDiver1975 move to 9.0 ?

**Comment by DeepDiver1975** [comment]
Yes - sadly we have to move this :crying_cat_face: 

@cmonteroluque FYI

**Comment by cmonteroluque** [comment]
thanks @DeepDiver1975. Pity

**Comment by DeepDiver1975** [comment]
we have our cla-bot live to check if the author of a pr has signed the contrib agreement.
No further action required for now
