### ISSUE TITLE
Public editable share, drop onto subfolder fails with permission issue

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13267]
### Steps to reproduce:
1. Create a folder "test"
2. Create a subfolder "test/sub"
3. Share "test" with link and allow editing/upload
4. Open link share
5. Drag and drop files from outside the browser onto "sub"
6. Navigate into "sub"
7. Drag and drop files from outside the browser into the file list

### Expected result
Files can be uploaded properly at step 5 and 7.

### Actual result
At step 5, getting "You don’t have permission to upload or create files here" error.
At step 7 the upload in that same folder works.

### Versions
ownCloud 8 git master
ownCloud 7.0.4

**Comment by PVince81** [comment]
Not critical as there's a workaround by going into the folder.
Also not a regression.

@DeepDiver1975 set to 8.1 ?

**Comment by PVince81** [comment]
Looks like the folder permission is set to "1", might need to be overwritten/completed by the public filelist class. Or maybe it's already overwritten but in a wrong way.

**Comment by PeterPablo** [comment]
I see the error message (though with escaped `'`: `You don\u2019t have permission to upload or create files here at`) in my log after updating from 8.0.2 to 8.0.3. (Full report in https://github.com/owncloud/core/issues/8760#issuecomment-98669257)

**Comment by MorrisJobke** [comment]
5. and 7. work fine with current master -> issue is fixed in 9.0
