### ISSUE TITLE
Encryption is broken with public sharing

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#13270]
On current master when installing new:

1. Install ownCloud as user "admin"
2. Enable encryption app
3. Log out
4. Login
5. Create a file "shared.txt"
6. Share that file publicly
7. Access the file
8. Try to download it

Get the following error:
```
[Mon Jan 12 13:58:57.889593 2015] [:error] [pid 44077] [client 192.168.0.17:55522] PHP Fatal error:  Call to a member function getUID() on null in /Users/lreschke/Programming/core/apps/files_encryption/lib/stream.php on line 139, referer: http://192.168.0.17/index.php/s/6eh2VfEbVfPgcGT
```

@schiesbn

**Comment by LukasReschke** [comment]
@jnfrmarks For your information – this is a kinda grave issue – can we add this to our test plan somehow?

**Comment by LukasReschke** [comment]
Regression introduced by https://github.com/owncloud/core/pull/13182 as far I can see

**Comment by karlitschek** [comment]
@schiesbn fyi

**Comment by oparoz** [comment]
When testing a fix, make sure to load a folder on the public side which contains a few pictures. https://github.com/owncloud/core/pull/13288 breaks previews

**Comment by schiesbn** [comment]
@oparoz I can reproduce it... But the encyption app decrypt the file for the preview correctly. Don't know why it doesn't get displayed correctly... Will investigate.

**Comment by oparoz** [comment]
@schiesbn - After a quick loo:
I see that `$this->userView->file_exists($preview)`returns true
https://github.com/owncloud/core/blob/master/lib/private/preview.php#L362
but then
the fopen operation fails `$stream = $this->userView->fopen($cached, 'r');`
https://github.com/owncloud/core/blob/master/lib/private/preview.php#L497

**Comment by jospoortvliet** [comment]
Just out of curiosity while seeing this - is this fixed? It is closed by  @LukasReschke  , but just got showstopper labels added ;-)

**Comment by nickvergessen** [comment]
The label as renamed, nothing more

**Comment by jospoortvliet** [comment]
@nickvergessen ok, thanks so this is clean. Nothing to worry about then :D
