### ISSUE TITLE
[Favorite ] Textfiles can't be edited in the favorites tab

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#13273]
### Steps to reproduce

1. Make a text file favorite
2. Open the favorites tab
3. Click on the file

### Expected behaviour
You are able to edit the textfile.

### Actual behaviour
File starts to download as other kind of file.

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.0.0.1","versionstring":"8.0 alpha 1","edition":""}

**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
none

**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password and passwordsalt)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** no

### Client configuration
**Browser:**
Chrome

**Comment by nickvergessen** [comment]
@PVince81 I guess the other app stuff is not loaded there?

**Comment by PVince81** [comment]
The text editor is not compatible with the sidebar.
It's the same issue as for the sharing overview.
Let's keep this issue here for later testing.
It should work once https://github.com/owncloud/files_texteditor/issues/17 is done

**Comment by DeepDiver1975** [comment]
> It should work once owncloud/files_texteditor#17 is done

closing this one then
