### ISSUE TITLE
star gone after the attempt of rename a favorite folder

### ISSUE THREAD

**Issue by dttpy** [owncloud/core#13283]
### Steps to reproduce
1. create a folder or file "test" 
2. tag "test" as favorite
3. click the "pen" icon to rename, but instead of giving a new name, make no changes
4. refresh the page
5. cancel the favorite of this folder/file
6. do step 3 again

### Expected behaviour
step 3: the star is still activated
step 6: the star is not activated

### Actual behaviour
step 3: the star is gone, although the folder/file can still be found in the favorite list
step 6: the star is yellow again, although the folder/file is no more favorite

TO NOTE: by step 3, if the file/folder name is changed before step 3, this bug will not be happened.

### Server configuration
**Operating system:** Ubuntu 13.10

**Web server:** apache 2.4.6 (Ubuntu)

**Database:** SQLite

**PHP version:** 5.5.3-1ubuntu2.3

**ownCloud version:** owncloud 8 git master

**Updated from an older ownCloud or fresh install:** 

**List of activated apps:** standard apps of owncloud

**The content of config/config.php:**

**Are you using external storage, if yes which one:** no
**Are you using encryption:** yes

### Client configuration
**Browser:** firefox 34.0.5

**Operating system:** ubuntu 13.10

**Comment by dttpy** [comment]
@PVince81

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/core/pull/13289
