### ISSUE TITLE
Make it possible to configure additional parameters over autoconfig.php

### ISSUE THREAD

**Issue by duritong** [owncloud/core#13295]
Hi

to automate installations it should be possible to configure a broad range of configs over autoconfig.php

As discussed here: http://forum.owncloud.org/viewtopic.php?f=26&t=20507

**Comment by LukasReschke** [comment]
I guess this is a duplicate of https://github.com/owncloud/core/issues/8022 - right?

**Comment by duritong** [comment]
Jeez, I was searching for autoconf, but should have searched for autoconfig. Sorry for the noise...
