### ISSUE TITLE
error while vcard contact import.

### ISSUE THREAD

**Issue by athulrajdr** [owncloud/core#13294]
this v card file is exported from google contacts. when i import this file to my owncloud contacts, the status shows  the content of vcf file is,
_________________________________
BEGIN:VCARD
VERSION:3.0
FN:Z New Kni Bz Rp: Wr.no
N:Rp\: Wr.no;Z New Kni Bz;;;
TEL;TYPE=MAIN:+919999999999
END:VCARD
__________________________________
I tried to import this file to my google contacts, and the contact imported successfully. .
The details which i entered to the contact on phone
First name: Z New Kni Bz
Last name: Rp: Wr.no

when this contact comes with a multiple contacts in a single .vcf file. the entire import shows the same status as "Total:0, Success:0, Errors:0",

**Comment by DeepDiver1975** [comment]
please reopen in https://github.com/owncloud/contacts - thx

**Comment by athulrajdr** [comment]
i tried this, also re installed in another directory with new database, sqlite also tried
BEGIN:VCARD
VERSION:3.0
FN:Z New Kni Bz Rp: Wr.no
N:Rp: Wr.no;Z New Kni Bz;;;
TEL;TYPE=MAIN:+919999999999
END:VCARD
__________________________
this made some changes manually to 
BEGIN:VCARD
VERSION:3.0
FN:Z New Kni Bz Rp Wr.no        ---->in this line Rp: to Rp
N:Rp Wr.no;Z New Kni Bz;;;       -----> in this line Rp:\ to Rp
TEL;TYPE=MAIN:+919999999999
END:VCARD
(the comments are not entered in the vcf file)
after this modification this is working with owncloud contact import.

**Comment by athulrajdr** [comment]
i tried to replace the current repository on https://github.com/owncloud/contacts to "apps" directory. but the problem still persists.
i have made some changes on the content
before:
BEGIN:VCARD
VERSION:3.0
FN:Z New Kni Bz Rp: Wr.no
N:Rp\: Wr.no;Z New Kni Bz;;;
TEL;TYPE=MAIN:+919999999999
END:VCARD
_________________________
after changing:
BEGIN:VCARD
VERSION:3.0
FN:Z New Kni Bz Rp Wr.no                ---> Rp: changed to Rp
N:Rp Wr.no;Z New Kni Bz;;;              ------>Rp\: changed to Rp
TEL;TYPE=MAIN:+919999999999
END:VCARD
now with this the import is successfull.
whats wrong with Rp: and Rp\:

**Comment by DeepDiver1975** [comment]
please reopen your issue in https://github.com/owncloud/contacts - thx
