### ISSUE TITLE
sort search results

### ISSUE THREAD

**Issue by ferdiga** [owncloud/core#13292]
Issue based on 
https://github.com/owncloud/core/issues/13240#issuecomment-69559040

IMO 2 possibilities for sorting full text search results
```
1) path+filename
2) word found + path filename (similar to the screen shot)
```
special issue is singular/plural or mistyped but still somewhat similar words

Option to search 
* only in the current and below directory  (in my example https://github.com/owncloud/core/issues/13240#issuecomment-69559040 search only data from the current company)
* global

**Comment by LukasReschke** [comment]
@jancborchardt Your thoughts?

**Comment by ferdiga** [comment]
another option could be substring / full word

**Comment by jancborchardt** [comment]
First should be the results where the search term is in the title, then in the content, then in the path.

**Comment by tmdpny** [comment]
I think folders with the word should be first, then files with the word, then content with the word

**Comment by jancborchardt** [comment]
Closing because the new search sorts the results pretty well.
