### ISSUE TITLE
Favorite file list display issue when clicking on filename

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#13290]
After you click on the filename (to download the file) the cell of the table with the icon, filename and file actions, becomes grey until you click elsewhere:

### Expected
![favorites_-_owncloud_-_2015-01-12_19 18 35](https://cloud.githubusercontent.com/assets/213943/5722638/2b0301fc-9b3e-11e4-9465-3f177ecf179a.png)

### Actual
![favorites_-_owncloud_-_2015-01-12_19 18 36](https://cloud.githubusercontent.com/assets/213943/5708377/aabc3d40-9a90-11e4-919f-9d6896042afe.png)

This does not happen on the normal file list, so I guess it's somehow avoidable?

@PVince81

**Comment by DeepDiver1975** [comment]
@jancborchardt mayb you can help out here as well? THX

**Comment by jancborchardt** [comment]
The real issue here is not the highlighting – it’s that the file is downloaded instead of getting viewed. And I’d say that is kind of a bug which should be solved for ownCloud 8 if we can get that done.

cc @owncloud/designers

**Comment by PVince81** [comment]
The text editor currently doesn't work in non-default view: https://github.com/owncloud/files_texteditor/issues/17

So for now clicking on a text file should download it, as the edit action isn't registered.

But even in that case, the grey highlight should probably disappear.

**Comment by nickvergessen** [comment]
@jancborchardt thanks for changing my ticket to something I did not mean and is a different issue.
When the default action is performed the grey block remains in the favorite list, it does not in any other files list.

**Comment by jancborchardt** [comment]
@nickvergessen hey, no need for sarcasm. :) Sorry for changing it, I assumed this was a general problem, not only with the text editor.

**Comment by PVince81** [comment]
Very strange. Also, the thumbnail disappears.
But then if I click around in the DOM inspector, the highlight disappears and thumbnail is back.

**Comment by Xenopathic** [comment]
@PVince81 Even stranger, once that happens, try switching to another tab and back.

**Comment by PVince81** [comment]
It's the ":focus" style.
There are two issues:
1) The :focus style auto-clears when downloading from "All files". But it stays in other lists from the sidebar.
2) The :focus style's background seems to overlap the thumbnail. Maybe z-index issue.

Looking further.

**Comment by PVince81** [comment]
The reason why it auto-deselects in "All files" is because of the drag and drop handler. That one finds that the click wasn't a drag after all.

There is no drag handler in other lists.

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/core/pull/13397
