### ISSUE TITLE
Feature Request : External Sites

### ISSUE THREAD

**Issue by Maastodonte** [owncloud/core#13308]
Hi guys,

I think that it would be great to be able to set a restriction on group on admin page when adding new external sites.
It would be easier to add this optional input in that particular app than to create a new application for a similar purpose.

Say, I want to add local phpMyAdmin access to all my admins but I don't want my users to even know about it => add new external_site, restrict group on admin and voila!

What do you think about it ?

**Comment by DeepDiver1975** [comment]
Please reopen in https://github.com/owncloud/apps/issues - thx
