### ISSUE TITLE
dbal 2.5.1 has been released - we should consider updating

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#13303]
@VicDeo  can I ask you to prepare a PR which updates 3rdparty repo and core? THX

In case you have questions feel free to ping me

**Comment by PVince81** [comment]
Did you mean 8.1 ? Seems a bit late to update libs, or do they contain critical fixes we need ?

**Comment by DeepDiver1975** [comment]
> Did you mean 8.1

indeed - thx for noticing
