### ISSUE TITLE
Move shared file into shared folder as recipient, moved share info lost

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13307]
### Steps to reproduce
1. Create two users "user1" and "user2"
2. Login as "user1"
3. Create a folder "test"
4. Share "test" with "user2"
5. Login as "user2"
6. Create a folder "sub" and put some files in it
7. Share "sub" with link and copy the link
8. Move "sub" into "test"
9. Check the share info for "sub"
10. Open the copied share link

### Expected result
At step 9 the link share still exists.
At step 10 the link share can be opened.

### Actual result
At step 9 the link share is gone because the fileid changed in the database.
At step 10 the link share can be opened, but the list appears empty (list.php returns 404)
Note that at this point it is impossible to delete that broken share!

### Versions
owncloud 8 git master dc86cbd1e275f01840b304751a02ecbe4043c51e

@SergioBertolinSG @jnfrmarks another one for the sharing test plan

**Comment by PVince81** [comment]
@schiesbn @icewind1991 is there any way to prevent losing/changing the file id in such situations ?

I guess moving a share into an external storage will cause the same issues due to fileid changes.

**Comment by PVince81** [comment]
Raised https://github.com/owncloud/core/issues/13310 to make the file id stable in general.

**Comment by PVince81** [comment]
File id stability https://github.com/owncloud/core/issues/13310 is not fixable in 8.0. Deferring to 8.1 as per the blocking ticket.

**Comment by MorrisJobke** [comment]
Fixed with #15360
