### ISSUE TITLE
Application description has uneeded line breaks

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#13315]
When the description uses some new-lines as in https://github.com/owncloud/core/blob/543fa0d45b23173ed94f4c865fe38855b1602ee4/apps/provisioning_api/appinfo/info.xml#L5-L13 for a cleaner code the description looks very disturbing with those uneeded line breaks (that is on master):

![screen shot 2015-01-13 at 13 34 24](https://cloud.githubusercontent.com/assets/878997/5720750/02afedba-9b29-11e4-9731-ef57971163af.png)

I'm kinda reluctant to change the formatting in `info.xml` as this would make the Git history somewhat cluttersome for edits in the future. Can somebody think of an alternate solution? (maybe searching for `\t` on a new-line?)

**Comment by DeepDiver1975** [comment]
@jancborchardt any idea? THX

**Comment by MorrisJobke** [comment]
Why not simply replace all `\n` with ` `?

**Comment by MorrisJobke** [comment]
Fix is in #13319

**Comment by jancborchardt** [comment]
Removing line breaks altogether is a pretty harsh solution. Does this occur for anything other than the Provisioning API app? If not, then we should just fix it there directly.

**Comment by LukasReschke** [comment]
That's actually relevant for all apps that use a large text blob in the description as you can see at https://github.com/owncloud/core/blob/543fa0d45b23173ed94f4c865fe38855b1602ee4/apps/provisioning_api/appinfo/info.xml#L5-L13
(there are some such as search etc…)

We could fix it also by just destroying the formatting in the info.xml – though this is comfort-- for us ;-)
