### ISSUE TITLE
Update from 7.0.2 to 7.0.4 in update  center fails

### ISSUE THREAD

**Issue by vwalther** [owncloud/core#13329]
Hello, i have bitnami owncloud and its failed to update automaticaly in admin page.
screenshot.
https://www.evernote.com/shard/s245/sh/b75eb408-f4d0-4a90-a812-7b322e119eb6/321b721cf95e541c9221a02abf275e50

Checking your installation...
Downloading package...
Creating backup...

its create backup in 
my data derectory and nothing next!

rights of htdocs
drwxr-xr-x 12 daemon daemon    4096 Jan 13 17:42 htdocs
of updater_backup
drwxr-xr-x 1 daemon daemon     0 Nov 26 01:03 updater_backup

log

{"app":"updater","message":"Backup creation failed. Check permissions.","level":3,"time":"2015-01-12T19:56:28+00:00"}
{"app":"updater","message":"Unable copy \/opt\/bitnami\/apps\/owncloud\/htdocs\/3rdparty\/rackspace\/php-opencloud\/lib\/OpenCloud\/Common\/Exceptions\/HttpError.php to \/home\/s3\/data\/updater_backup\/7.0.2.1-588dba99\/3rdparty\/rackspace\/php-opencloud\/lib\/OpenCloud\/Common\/Exceptions\/HttpError.php","level":3,"time":"2015-01-12T20:25:02+00:00"}
{"app":"PHP","message":"Division by zero at \/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/preview.php#426","level":3,"time":"2015-01-12T23:39:07+00:00"}
{"app":"PHP","message":"copy(\/home\/s3\/data\/updater_backup\/7.0.2.1-075fc243\/3rdparty\/phpmailer\/phpmailer\/examples\/gmail.phps): failed to open stream: No such file or directory at \/opt\/bitnami\/apps\/owncloud\/htdocs\/apps\/updater\/lib\/helper.php#56","level":3,"time":"2015-01-13T14:23:45+00:00"}
{"app":"updater","message":"Backup creation failed. Check permissions.","level":3,"time":"2015-01-13T14:23:46+00:00"}
{"app":"updater","message":"Unable copy \/opt\/bitnami\/apps\/owncloud\/htdocs\/3rdparty\/phpmailer\/phpmailer\/examples\/gmail.phps to \/home\/s3\/data\/updater_backup\/7.0.2.1-075fc243\/3rdparty\/phpmailer\/phpmailer\/examples\/gmail.phps","level":3,"time":"2015-01-13T14:45:32+00:00"}
{"app":"PHP","message":"mkdir(): No such file or directory at \/opt\/bitnami\/apps\/owncloud\/htdocs\/apps\/updater\/lib\/helper.php#69","level":3,"time":"2015-01-13T16:00:28+00:00"}
{"app":"updater","message":"Backup creation failed. Check permissions.","level":3,"time":"2015-01-13T16:00:30+00:00"}

**Comment by RealRancor** [comment]
Hi,

seems to be an issue with the updater app which should be reported in the issue tracker of the app located here: https://github.com/owncloud/updater/issues
