### ISSUE TITLE
[Favorite] Files and folders explored from shared tabs in the side panel can't be favorited.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#13321]
### Steps to reproduce
1. User1 has shared files with User2.
2. User2 enters in the Shared with you tab in the side panel.
### Expected behaviour

You can make files and folders favorite from this tab.
### Actual behaviour

There aren't stars to make them favorite.
### Server configuration

**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.0.0.1","versionstring":"8.0 alpha 1","edition":""}

**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
none

**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password and passwordsalt)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** no
### Client configuration

**Browser:**
Chrome

cc @jancborchardt

**Comment by jancborchardt** [comment]
@Pvince81 is there any specific reason the stars aren’t shown on those views?

**Comment by PVince81** [comment]
Yes, missing data. The sharing API doesn't return the favorite info.

**Comment by PVince81** [comment]
Postpone to 8.1 as discussed with @DeepDiver1975

**Comment by PVince81** [comment]
CC @schiesbn

**Comment by PVince81** [comment]
One suggestion for the far future would be to have a WebDAV endpoint for shares and let API consumer decide whether they want the "oc:favorite" property or not, as it would affect performance to always return it.

**Comment by jancborchardt** [comment]
If we use favorites in the UI, they should be in every view I would say. It’s a pretty basic feature of file management nowadays. But yeah, we do need to balance it with performance.

**Comment by PVince81** [comment]
I agree, let's keep this ticket open to look into that.

**Comment by PVince81** [comment]
Best would be if we could just retrieve these shared file lists through Webdav, just like the tags search does. This way all properties that the web UI needs would always be there and displayable in any view.

**Comment by PVince81** [comment]
Works for me in 10.0.3. As far as I remember this was added recently
