### ISSUE TITLE
Files favorites plugin: star icon changes it's size on click in safari

### ISSUE THREAD

**Issue by Sugaroverdose** [owncloud/core#13322]
Here how it looks like .gif:
![starbutton](https://cloud.githubusercontent.com/assets/10269200/5722542/0d4acb94-9b4e-11e4-935e-a60db2739d4f.gif)

**Comment by karlitschek** [comment]
@jancborchardt

**Comment by Sugaroverdose** [comment]
Maybe it's better not to change src, but switch 'hidden' class between two img?

**Comment by jancborchardt** [comment]
@Sugaroverdose that’s weird … the stars are exactly the same size. Can you maybe debug it? I don’t have OS X / Safari to test unfortunately.

cc @owncloud/designers

**Comment by Sugaroverdose** [comment]
Default size of SVG in Safari is lower than 16px on 16px, and looks like safari doesn't honor css size for img's with dynamically changed src(should it?). 

I've partly fixed this by adding width:100%;height:100%; to img element, that makes icon refresh it's size after unhighlighting file line.

My opinion - it's more about js render technique than markup/styling.

next step - try to add class='hidden' on start of changing icon function and removing it in the end)

**Comment by Sugaroverdose** [comment]
Toggling 'hidden' between two images works as expected: star renders correctly without resizing

**Comment by Sugaroverdose** [comment]
Adding 
```javascript
$actionEl.hide().show(0);
```
to toggleStar function in https://github.com/owncloud/core/blob/master/apps/files/js/tagsplugin.js forces safari to redraw, but but button hides for around a second :(

**Comment by jancborchardt** [comment]
@Sugaroverdose big thank you for the fix! :)
