### ISSUE TITLE
Latest Update of Owncloud Desktop App breaks system.

### ISSUE THREAD

**Issue by texxasrulez** [owncloud/core#13327]
The latest update to owncloud desktop app at the end of 2014 causes (on 2 separate computers) Autocad to lock up whenever a "windows manager" is needed. When opening files, it hangs before file explorer comes up. It also hangs when trying to insert blocks, again, the windows file explorer needs to be opened. Once I uninstalled owncloud app, my Autocad returned to normal. I love your software and have become addicted and dependent on it. Keep up the good work ...

**Comment by Sugaroverdose** [comment]
wrong repo.
https://github.com/owncloud/client
