### ISSUE TITLE
ownCloud 7.0.4 Avatar issue - uploads to user cache but not to user account ... 

### ISSUE THREAD

**Issue by chuckingit** [owncloud/core#13331]
Hi - i recently upgraded to 7.0.4 and everything seems to work except one strange issue with user avatars ... in that when i'm logged in as a new user and scroll down to the Profile picture section and try to "upload new" it bombs ... yes, the status bar shows that a file is being uploaded then stops thus the new photo does not appear ... yet when i logged in to back end of server, indeed i can see the file landed in the /user/cache/avatar_upload file but that file is not being copied over to /user/avatar.jpg ... 

yet if i skip the "upload new" and instead choose "select new from files" that option works fine - in that i can see a list, pick an image, crop it, and voila - new avatar ... 

thus not sure if i found a bug or maybe my install is a bit wonked ..??.. i tried changing permissions on user folders and even if wide open at 777 (for full read, write, execute for all groups, owners, others) - nada - still same result when trying to use the "upload new" option to create an avatar ... hence share accordingly in case this is bug ..??..

cordially, chuck scott

ps - even if i try to change my avatar for an older user who has an existing avatar and try to replace via the "upload new" i get same result - file uploaded to the user/cache/avatar_upload ... but not copied over to /user/avatar.jpg ... 

pss - adding this line to my config file had no success either ->   'enable_avatars' => true,

**Comment by PVince81** [comment]
Still seeing this issue in 7.0.7 or 8.0.5 ?

**Comment by DeepDiver1975** [comment]
Using the file cache to store the images is so wrong - the avatar code is fishy

**Comment by chuckingit** [comment]
@PVince81 - just looping back to you in that i just now re-tested the avatar issue above with current version 8.1 and lo'n behold all seems to work* ... thus Thank You and Team ownCloud for fix :>) ... cordially, chuck scott

*the uploaded jpg landed in the folder /user/cache and the jpg was named -> avatar_upload ... and that file was then copied over to /user/avatar.jpg ... when i deleted user account all files were cleaned up and my only thought for improvement here is that perhaps after the avatar.jpg is created, that the avatar_upload file could have been removed ..??.. not sure if this makes sense to keep the uploaded file on server or not as in my test i uploaded an 8meg jpg which ownCloud allowed me to crop for the avatar ... at that point if ownCloud removed the uploaded file that would help save on disk space ... yet i can also appreciate leaving the file there in the event a user wanted to go back and recrop file ... in my case i don't plan to have that many users so probably not a super big deal if the uploaded file hangs around on server ... but for a team with large user base, i could see how those uploads hanging around could add drag to file system ..??..

**Comment by rullzer** [comment]
As it seems to be solved in newer OC version => close
