### ISSUE TITLE
Public link upload with encryption + files_locking fails

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13337]
### Steps to reproduce
1. Enable encryption
2. Create a folder "test"
3. Share "test" with link and allow editing/upload
4. Upload a file

### Expected result
File uploaded

### Actual result
`Could not obtain lock type 2 on "/srv/www/htdocs/owncloud/data/root/files_encryption/keys/abc/1391249528060.jpg/fileKey`

Maybe the file key is being opened twice in a row ?
Also there's the more broader question whether files_locking should lock on encryption keys: https://github.com/owncloud/apps/issues/1940

This also means that upload will not work either if the folder is mounted as remote share.

### Versions
ownCloud 8 git master (83574053a3a960171a22af1ebb218e8e4cf03fd6) (requires https://github.com/owncloud/core/pull/13288 to be merged first)

@schiesbn can you have a look ?

**Comment by schiesbn** [comment]
that's only happens with file locking, right? Without it the upload works? I will have a look.

**Comment by PVince81** [comment]
Yes, only with the files_locking app.
I suspect that maybe a key file is getting fopen'd twice in a row or something.

**Comment by schiesbn** [comment]
I can't reproduce it on master after the public upload fix was merged ( https://github.com/owncloud/core/commit/9a487f0445d9dfd26690943c5aa570553f7de2fc)

**Comment by schiesbn** [comment]
I could reproduce it. We try to lock the file twice. The first time it works (https://github.com/owncloud/files_locking/blob/master/lib/lockingwrapper.php#L93) and directly after the '$this->storage->file_put_contents($path, $data);' in line 94 we end up in line 93 again. I'm not sure why it happens. Especially with regard to encryption I don't know why it should happen only for public uploads. The path through the encryption proxy/streamwrapper is the same for a public upload and a internal upload.

**Comment by PVince81** [comment]
Hmmmm it almost sounds like the storage was wrapped **twice** by the locking wrapper ?!
Can you check the stack trace at the time where you land on line 93 again ?

**Comment by schiesbn** [comment]
I already tried it. The strange think is that the storage wrapper gets registered in a associated array with "$wrappers[$wrapperName] = $wrapper", so even if we registered it twice the second one should replace the first one because both will have the same name. If I remember correctly, we had similar problems with wrappers registering multiple times in the past and @icewind1991 fixed it with the associated array after we discussed it at one of the developer meetings. @icewind1991 is this correct? Do you have any idea what could be wrong here?

**Comment by PVince81** [comment]
Works properly on 8.1 / master (d2f3710ede1fa72658a4c12264a90a1936faf9ca)
Works properly on 8.0.4RC1 too.
