### ISSUE TITLE
Rename field in "Favorites" is shifted to the right

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#13338]
* mark a file/folder as favorite (star)
* go to the favorite view
* rename the file/folder by clicking on the pencil icon
* looks like:

![rename-favs-in-master](https://cloud.githubusercontent.com/assets/245432/5736848/eea57454-9bda-11e4-8170-468a96fa3c24.png)

version: current master

cc @PVince81 @jancborchardt You played around with that too. Wasn't there a fix for the other views? Maybe this is causing this problem here

**Comment by jancborchardt** [comment]
It seems the DOM is constructed differently than in the normal Files view? There’s extra margin to the left when it shouldn’t be there. The `.has-favorites` CSS rule applies so it adds the 52px left margin necessary to fix it in other views (like the regular list and public share).

**Comment by MorrisJobke** [comment]
And I just found another one (in shared with you):
![rename-failure-shared-with-you](https://cloud.githubusercontent.com/assets/245432/5778129/4e1ac6b8-9d99-11e4-8902-1486fb30265a.png)

**Comment by MorrisJobke** [comment]
ref #12360

**Comment by MorrisJobke** [comment]
ref #12927

**Comment by MorrisJobke** [comment]
I guess https://github.com/owncloud/core/pull/13191/files is the cause
