### ISSUE TITLE
Apps list shows wrong result when switching section during results load

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13336]
### Steps to reproduce
1. Go to the apps management page
2. Wait for the results to load
3. Click on "Not enabled"
4. Before the results appear, quickly click on "Enabled"

### Expected result
Results contain enabled apps

### Actual result
Results contain not enabled apps, which doesn't match the selected section.
I believe this is a race condition: both ajax requests are running and whichever finishes first/last gets its results.
Proper way is to cancel the ajax call whenever the section is changed.

### Versions
ownCloud 8 git master (dc86cbd1e275f01840b304751a02ecbe4043c51e)

@DeepDiver1975 @icewind1991

**Comment by MorrisJobke** [comment]
I also noticed this. I will review the PR.
