### ISSUE TITLE
Allow applications to prevent "remember me" login for specific users

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#13343]
Applications should be possible to prevent the "remember me" login from working for specific users and if that is done a decent notice should get shown to the user so that he gets aware of this.

The current implementation requires us to disable "remember me" if apps such as files_external are enabled which have the "Login with ownCloud credentials" feature.

Ref https://github.com/owncloud/core/pull/13335 and https://github.com/owncloud/windows_network_drive/issues/168

**Comment by LukasReschke** [comment]
@nickvergessen @DeepDiver1975 FYI

**Comment by DeepDiver1975** [comment]
8.2

**Comment by PVince81** [comment]
@DeepDiver1975 @LukasReschke move to 9.0 ?
