### ISSUE TITLE
Inquiry: download managers

### ISSUE THREAD

**Issue by sydcanem** [owncloud/core#13359]
Hey, I'm a new owncloud user. How do you use download managers to handle downloading of files from owncloud? I can't seem to download the resource using the download link provided in the files dashboard.

**Comment by DeepDiver1975** [comment]
Your user base mainly used the desktop client for managing files. If you are looking for a pure download solution you might want to got for any webdav based solution - either a client or mount it to your desktop.

**Comment by LukasReschke** [comment]
=> Use the desktop client.
