### ISSUE TITLE
New requirement for posix extenstion when invoking occ on CentOS

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#13357]
### Steps to reproduce

1. Install master and enterprise tar balls to centos 6 box
2. cd to the installation directory
3. invoke occ using the apache user:

sudo -su apache ./occ

### Expected behaviour

occ should run

### Actual behaviour

A new requirement for the posix extensions is displayed.  This is not the case on ubuntu.  Is this the expected behavior? 

### Server configuration

CentOS 6.6
PHP 5.4.34
ownCloud 8.0 alpha 2 (daily) Build:2015-01-14T04:12:43+00:00

**Comment by Xenopathic** [comment]
Yes - the `occ` command uses the POSIX functions in PHP to run, and without them bad things can happen. There's a PR that introduced it around here somewhere...

**Comment by LukasReschke** [comment]
@carlaschroder Needs documentation – when running linux OCC requires these additions.

@jnweiger FYI – packaging related.

**Comment by jnfrmarks** [comment]
@LukasReschke @Xenopathic 

Do we need to reopen for tracking purposes?

**Comment by LukasReschke** [comment]
Good idea.

**Comment by Xenopathic** [comment]
Or perhaps create an issue in documentation?

**Comment by LukasReschke** [comment]
Packaging issues are tracked here as well – no need to create multiple tickets for that then IMHO :-)

**Comment by Xenopathic** [comment]
Ah, OK :smile:

**Comment by DeepDiver1975** [comment]
We should add this to the docs as well - in here https://github.com/owncloud/documentation/blob/master/admin_manual/installation/source_installation.rst

@carlaschroder the php min requirement should be leveraged as well :speak_no_evil:

**Comment by carlaschroder** [comment]
Hmmm, this raises some questions. I thought that POSIX functions were built into the base PHP for CentOS/RHEL/Fedora. What CentOS package needs to be installed, and is it specific to CentOS 6 only? What about RHEL and Fedora, or other versions?

**Comment by carlaschroder** [comment]
And, if it's a packaging issue does this really need to be documented?

**Comment by jnweiger** [comment]
Regarding packaging:

php-posix is already a indirect dependency of the 7.0x packages on CentOS. I'll make it an explicit dependency for 8.0 -- thanks for the pointer.

testcase: 

docker run -ti owncloud-7.0.4-11.1-centos_6_php54 php -r 'print posix_getuid()."\n";'
0

**Comment by LukasReschke** [comment]
@carlaschroder Yes – we need to document every dependency that needs to be installed. You can very well compile PHP yourself or use some other exotic setup. At least SOMEWHERE we have to have a notice that having the posix extensions installed and activated is required.

Thanks @jnweiger

**Comment by MorrisJobke** [comment]
Documentation: https://github.com/owncloud/documentation/pull/758

**Comment by jnweiger** [comment]
@carlaschroder The general rule about dependencies is this: If you install from RPM packages, dependencies are handled (through the magic that I built into the packages). If you install from TAR or ZIP then you need to study the documentation to learn about dependencies.

And in case my magic fails, the documentaiton is also helpful.

**Comment by DeepDiver1975** [comment]
> Documentation: owncloud/documentation#758

merged

@jnweiger anything left from packaging pov? if not please close this issue - THX

**Comment by jnweiger** [comment]
packaging done.
