### ISSUE TITLE
JSResourceLocator needs to die

### ISSUE THREAD

**Issue by BernhardPosselt** [owncloud/core#13353]
We do some really fancy and slloooooow magic when locating js files added with OC_Util::addScript. The following paths are added for instance:

* js/chosen.js
* news/js/app.js

Then in order to locate the file we loop over all possible directories and figure out if the file exists. Why cant we simply construct a valid path like:

* core/js/chosen.js
* apps/news/js/app.js

inside the addScript method?

@DeepDiver1975 @PVince81 @LukasReschke @MorrisJobke

**Comment by PVince81** [comment]
There can still be multiple configured app folders (apps2, apps3).
I agree that we can limit the search scope to these instead of searching in irrelevant locations (like searching in "core" when it's clearly an app)

**Comment by LukasReschke** [comment]
> There can still be multiple configured app folders (apps2, apps3).

We could cache that in the memcache.

**Comment by Raydiation** [comment]
We should also get rid of the in_array functions in OC_Util since their runtime is O(n) and it could be O(1) by using an array like [$path => true]

**Comment by PVince81** [comment]
That could be fixed separately, or as a quick performance fix for 8.0 :smile:

**Comment by nickvergessen** [comment]
Only allow using `vendor_script()` and `vendor_style()` ?

**Comment by DeepDiver1975** [comment]
> We could cache that in the memcache.

caching is valid AFTER a proper implementation ... let's see what we can do



> Then in order to locate the file we loop over all possible directories and figure out if the file exists. Why cant we simply construct a valid path like:
> 
>     core/js/chosen.js
>     apps/news/js/app.js
> 
> inside the addScript method?

within jsresourcelocator we hold the magic to allow these files to be overloaded in the themes directory - but even this could be moved inside addScript() from my pov
