### ISSUE TITLE
Transfer share ownership to other user

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#13355]
Imagine the following use-case:

1. Club is sharing files for their board members using files_sharing, there is one general share owned by a "system" user.
2. However, one of those board members created a new folder and shared it with the board. Thus this share belongs now to him.
3. The board member has left and all access should get revoked. However, since there are shares belonging to that user deleting the user is not possible (? - Didn't try, but I guess things will explode)

There should be a possibility to move the ownership to a new user or some other sane approach to fix such problems instead of requiring me to fiddle around with the database and the filesystem.

**Comment by PVince81** [comment]
Renamed subject Overwrite => Transfer which sound better and less technical :smile:

**Comment by tflidd** [comment]
It would also be a nice feature to send data to a user (even server-2-server).

**Comment by brunodegoyrans** [comment]
Hello

This is a very important functionnality for companies or projects where several collaborators contribute.

My small company had lost lot of money because one collaborator had left and removed all of its files.
It was with google drive. But there is the same potential issue with owncloud.

In a company or a project, collaborators do not share, but they CONTRIBUTE, they GIVE.
Since a collaborator has given a contribution (new file/folder), the project manager, the company or the admin shall become the owner. He shall be able to manage the permission: who can read, modify, delete this new file.

I would see a button "Give" or "Deliver" near or into the share panel.

Technically, that would not be difficult to implement since this is only a record to update in the oc_share table. But I'am not a developper.

**Comment by DeepDiver1975** [comment]
> Technically, that would not be difficult to implement since this is only a record to update in the oc_share table.

not really because ownership implies that the files physically live in the owners data dir

**Comment by DeepDiver1975** [comment]
what would make more sense with respect to collaborations in bigger groups is is have a concept like group workspace - refs https://github.com/owncloud/core/issues/154

**Comment by brunodegoyrans** [comment]
I like this concept of workspace or project. But after reading ref #154, I'am not sure that it would solve the above issue. i.e. if a collaborator creates a file/folder in this workspace, who is the owner? What if the collaborator delete "his" files/folders?

**Comment by LukasReschke** [comment]
Possible with master now…

**Comment by mczernin** [comment]
i am sorry to reopen this. i also need to do change ownership to another user. what does @LukasReschke  mean with 

> Possible with master now…

**Comment by MTRichards** [comment]
Didn't we deliver this with 9.0 with the occ user_migrate command?

**Comment by nickvergessen** [comment]
Yes, possible with ownCloud 9.0.x

**Comment by LukasReschke** [comment]
That is correct.

**Comment by mczernin** [comment]
How exactly does it work?


Am 4. Mai 2016, 21:24 +0200 schrieb Lukas Reschke<notifications@github.com>:

**Comment by LukasReschke** [comment]
The documentation is your friend 😉 
https://doc.owncloud.org/server/9.0/admin_manual/configuration_files/file_sharing_configuration.html#transferring-files-to-another-user

**Comment by saivert** [comment]
Why is such a feature relegated to the occ command and not available in the web user interface? So one can just click ... next to a file and click "Transfer ownership".

**Comment by PVince81** [comment]
Because anything that is triggered from the web UI will create a PHP request which is likely to run into a timeout. In case of lots of files it is very likely that the PHP request will die due to a timeout and not complete the operation.

**Comment by macz71** [comment]
Hi all,
I believe this should be option available to user from GUI.
There should be task scheduled on server side to do it and GUI action lock to avoid multi scheduling transfer the same files on accidental clicks.
How do you see it?

**Comment by PVince81** [comment]
@macz71 I see this as a separate enhancement ticket, thanks.

Note that it wouldn't work for encryption as it would require storing the user's password for decryption during transfer.
