### ISSUE TITLE
Exif oriented pictures: not all possible values are supported

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/core#13363]
Hello,

as I have included the exif rotated images in android app, I have found out, that not all possible values are supported: 2,4,5,7.
Please see http://www.daveperrett.com/articles/2012/07/28/exif-orientation-handling-is-a-ghetto/

This is the relevant code: As you can see "2" is handled like 1. But it should be mirrored.
https://github.com/owncloud/core/blob/master/lib/private/image.php#L324

**Comment by PVince81** [comment]
@georgehrke @oparoz

**Comment by oparoz** [comment]
If I read the diagram and the method only gets half the cases right because it's missing a flip method.
Should be easy enough to implement

```
case 2: // Super tested
$rotate = 0;
$flip = 1;
break;
...
if ($flip) {
	$res = imageflip($this->resource, IMG_FLIP_HORIZONTAL);
}
if ($rotate) {
...
}
```

What do you think @tobiasKaminsky, would flip + rotate work to fix all those cases?

**Comment by tobiasKaminsky** [comment]
@oparoz Yes. This should work, but it has to be IMG_FLIP_VERTICAL for all cases.
As HORIZONTAL will flip the image on the longer (bottom) side.

**Comment by MorrisJobke** [comment]
I will test this with the examples listed in the blog post: https://github.com/recurser/exif-orientation-examples

**Comment by MorrisJobke** [comment]
Fix is in #13448

**Comment by tobiasKaminsky** [comment]
Great. Thank you all for this quick fix

**Comment by MorrisJobke** [comment]
@tobiasKaminsky No problem. You provided all the needed information and it was then easy to combine them to a nice solution ;) Thanks

**Comment by oparoz** [comment]
Just found out that Imageflip is only available in PHP 5.5 and I think that's breaking things for a few people...
http://php.net/manual/en/function.imageflip.php

**Comment by LukasReschke** [comment]
Ref https://github.com/owncloud/core/commit/a28d3b594b089af837c6a319d7b7b6a8f7155210#commitcomment-9706810

**Comment by MorrisJobke** [comment]
With #14138 they are still supported for PHP 5.5+ ... so I close this for now. Either install a recent PHP version or have unflipped images.
