### ISSUE TITLE
new users don't have permission to open files in swift folder

### ISSUE THREAD

**Issue by Redstoone** [owncloud/core#13376]
owncloud version: 6.0.5
os: ubuntu 12.04
php version: 5.3

I setup external storage on swift. All users can access the "swift" folder.
The issue is, new user cannot read or write files created before their registry. If files were edited later, they could be read then.

The reproduce steps are:
1. put some photos in the "swift" folder
![1](https://cloud.githubusercontent.com/assets/5569028/5756132/5be41298-9ce7-11e4-8282-5ab0351483cc.png)

2. create an new user "tony", and login
![2](https://cloud.githubusercontent.com/assets/5569028/5756134/62d03b54-9ce7-11e4-8b3d-063adbcfd16c.PNG)

3. go to "swift" folder. All files are unreadable. And chrome console complain errors
![3](https://cloud.githubusercontent.com/assets/5569028/5756142/692c18d8-9ce7-11e4-810b-3f03918270cc.PNG)

error code:
GET http://172.16.129.71/apps/files_encryption/files/error.php?p=0&errorCode=3 403 (Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.) 

4. switch to admin user, and rename one photo (Koala.jpg -> dog.jpg)
![4](https://cloud.githubusercontent.com/assets/5569028/5756143/6e0cfff2-9ce7-11e4-9877-efeada2b9d86.PNG)

5. then user "tony" can read it
![5](https://cloud.githubusercontent.com/assets/5569028/5756144/736dd49e-9ce7-11e4-9ae9-206f0fa68428.PNG)

**Comment by kyzy540** [comment]
have the same issue. i guess 'rename' action rescan the user-list and grant permissions

**Comment by PVince81** [comment]
You mentionned "cannot decrypt" ? This means you have encryption enabled.

Are you using SWIFT exclusively from ownCloud ? (not outside of ownCloud)

It sounds like a situation similar to group shares: whenever a new user is created and added inside a group, the share keys for that user cannot be automatically created.
In the case of external storage, the "group" situation is actually the "applicable" field.

@schiesbn

**Comment by Redstoone** [comment]
@PVince81   yes, I have encryption enabled.  How can I solve this?

**Comment by PVince81** [comment]
It is not technically possible to provide share keys for the user that has been newly added to the group because at that time ownCloud doesn't have the user's password (the user's password is needed to be able to decrypt their private key to do anything key-related). As far as I remember.

This is described here: https://github.com/owncloud/core/issues/4986#issuecomment-28471340

CC @schiesbn

**Comment by PVince81** [comment]
I think I got it wrong. It's actually the sharer's key that is required, not the one from the new user.
I'm not sure which key is used for system-wide external storage mounts, can you help clarify @schiesbn ?

The workaround is to unshare the group, in your case remove the group from the external storage, then add it again.

**Comment by Redstoone** [comment]
I have encryption disabled and solved it.
