### ISSUE TITLE
OC 7.0.4.2 group share does not merge usergroups and groups correctly

### ISSUE THREAD

**Issue by goodkiller** [owncloud/core#13378]
Steps to reproduce
Create a different groups and users. Define random groups to random users, also make sure that one user have same groups that you'll have.

For example:
User 1: Group 1, Group 5, Group 8, Group 7
User 2: Group 2, Group 5, Group 3, Group 7

Try to share file or folder to User 2 and find Groups 5 and 7

Expected behaviour
You will find searchable Groups

Actual behaviour
You don't those Groups.

Workarond or fix?
In core/ajax/share.php on line 259 I replaced 
$groups = array_intersect($groups, $usergroups);
to
$groups = array_unique(array_merge($groups, $usergroups));
and it works like a charm.

Server configuration
Ubuntu 14.01.04 LTS
OC 7.0.4.2
PHP 5.5.9
Using OpenLDAP
nginx/1.7.9

**Comment by dttpy** [comment]
Using 
**Operating system:** Ubuntu 13.10
**Web server:** apache 2.4.6 (Ubuntu)
**Database:** SQLite
**PHP version:** 5.5.3-1ubuntu2.3
**ownCloud version:** owncloud 7.0.4,
and can not reproduce this problem

**Comment by PVince81** [comment]
@goodkiller when you say "Try to share file or folder to User 2 and find Groups 5 and 7".
Are you saying:
Open the share dropdown, Type "User 2", select it, then Type "Groups 5", select it. But here the group doesn't appear ?

Can you check the admin page, did you untick the checkbox called "Restrict users to only share with users in their groups" ?

**Comment by goodkiller** [comment]
Hah! I found more deeper issue. This is still same issue as I filed earlier.
https://github.com/owncloud/core/pull/11555/files

The difference is that I am using OpenLDAP and "user key" is defines int32 type not string. 
So for example simple tests shows **results**:

$array1 = array(
	'98760' => 'ONE USER',
	12345 => 'THIRD USER'
);
$array2 = array(
	0 => 'ANOTHER USER'
);

$merge1 = array_merge($array1, $array2);
print_r($merge1);

$merge2 = $array1 + $array2;
print_r($merge2);

**Output is: **
Array
(
    [0] => ONE USER
    [1] => THIRD USER
    [2] => ANOTHER USER
)
Array
(
    [98760] => ONE USER
    [12345] => THIRD USER
    [0] => ANOTHER USER
)

As you can see my solution works both ways. Please consider to fix this in future versions or handle it another way.

**Comment by PVince81** [comment]
@blizzz @schiesbn

**Comment by PVince81** [comment]
Your PR was merged, closing :smile:
