### ISSUE TITLE
High CPU usage on server with calendar

### ISSUE THREAD

**Issue by papezg** [owncloud/core#13373]
Hi!

I'm having this issue with my deployment of owncloud. It's server version 7.0.4. and when I add calendar into Thunderbird client the CPU usage on server immediately spikes to 25% and if I leave it for a minute it goes to 100%.

**Comment by nickvergessen** [comment]
Do you mean the calendar app? https://github.com/owncloud/calendar
If so please open a new issue in https://github.com/owncloud/calendar/issues

**Comment by MorrisJobke** [comment]
@papezg And please also have a look at the owncloud.log in your data folder and append it in the new ticket in the calendar repo ;)

**Comment by papezg** [comment]
Issue is not with calendar app. Problem is that when I add calendar link into Thunderbird client. PHP5-FPM process on server gets totally out of control and uses all available cpu power up to 100%. If I remove calendar link from TB client it stops.

**Comment by MorrisJobke** [comment]
> If I remove calendar link from TB client it stops.

Then it seems to be the calendar app of owncloud, which causes the problem. Please have a look at the owncloud.log in your data directory of owncloud and post it together with your setup (https://github.com/owncloud/core/blob/master/issue_template.md gives you some hints) in the calendar bug tracker: https://github.com/owncloud/calendar/issues
