### ISSUE TITLE
Adding a new subfolder to a shared folder automatically marks that subfolder as being shared on all clients

### ISSUE THREAD

**Issue by jimcglaughlin** [owncloud/core#13371]
We are testing ownCloud 7 Community Edition on Ubuntu with several ownCloud Desktop Windows clients ver 1.7.1.
We added an existing directory to the External Storage area to so the clients can select folders to sync with...for example:
---Top_Level_Share
    -------Shared_Folder_1
    -------Shared_Folder_1
    -------Shared_Folder_3
On each ownCloud Client, we can select 'Choose what to sync' and just select 'Shared_Folder_3' for example and it works fine.  If someone adds a 'Shared_Folder_4' to the 'Top_Level_Share' directory on the server, all of the ownCloud clients will now show that new folder as being sync'ed even though they did not select it.
We will have hundreds of folders under the 'Top_Level_Share' and it will be constantly added to.  The clients will only be needing to sync a few at a time and don't need shared folders automatically being added to their 'sync list' when folders are added to the server.
If you have any comments or suggestion on how to turn this feature off please let me know.  Thank you.

**Comment by Sugaroverdose** [comment]
@jimcglaughlin wrong repo, https://github.com/owncloud/client

**Comment by jimcglaughlin** [comment]
Thanks…I did not know if this was something on the server side or client side…I’ll try the client repo

Jim McGlaughlin
Applications Development Manager
Logical Systems, LLC
(901) 377-5574 (office) | (901) 866-6232 (direct)
