### ISSUE TITLE
Server to server sharing / OC storage upload file limit, needs chunking

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13380]
### Steps to reproduce
1. Setup two ownCloud instances A and B
2. In A setup a max upload limit of 512 MB
3. In B, setup a max upload limit of 64 MB (for testing)
4 .In A, mount a remote share "test" from B (server to server sharing). OR use the ownCloud backend external storage to connect to a folder on B
5. In A over the web UI, upload a ~100 MB file into "/test"

### Expected result
Upload succeeded.

### Actual result
(I haven't tested yet but this is likely to happen:) OC A cannot upload the file to OC B due to max upload limit

### Versions
Could happen on OC 7, master

We need to improve the OC storage code + server to server sharing DAV storage code to upload files to B in chunks, just like the sync client does.

It seems we're also slowly reaching a point where it might be desirable to have a PHP version of pyocclient :wink: (which itself supports chunk upload) and use that phpocclient in the Storage code.

@icewind1991 @schiesbn @DeepDiver1975

**Comment by PVince81** [comment]
CC @MorrisJobke who inquired about this

**Comment by PVince81** [comment]
Raised https://github.com/owncloud/core/issues/13381 to consolidate server to server sharing with the owncloud storage backend to avoid duplicate work, especially if we're adding more advanced features like chunk upload in the future.

**Comment by DeepDiver1975** [comment]
hmm ... max upload is not relevant for DAV as it uses PUT to upload. Only POST does have that upload limitation

**Comment by PVince81** [comment]
Okay, I wasn't aware of that.
Like I said above, it was just an idea.
Will try it out later. I hope you're right :wink:

**Comment by DeepDiver1975** [comment]
> Will try it out later. I hope you're right :wink:

![you-y-u-no-believe-me](https://cloud.githubusercontent.com/assets/1005065/5757232/8fcc76b4-9cb9-11e4-844d-94da57975ac9.jpg)

**Comment by PVince81** [comment]
Just tried it and you were right :smile: 

The limit doesn't kick in, probably because it uses PUT anyway.
Closing.
