### ISSUE TITLE
Consolidate server to server sharing with OC external storage backend

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13381]
Currently there are two ways to mount an external ownCloud folder:
1) Using server to server sharing
2) Using the "ownCloud" external storage backend

These are using different code paths to do similar operations.
The server to server sharing code happens in the `DAV` class: https://github.com/owncloud/core/blob/master/lib/private/files/storage/dav.php
While the ownCloud backend is here: https://github.com/owncloud/core/blob/master/apps/files_external/lib/owncloud.php

The purpose of the ownCloud external storage backend is to take advantage of ownCloud features that might not be available in regular WebDAV mounts like:
- change detection through etags
- disable encryption for remote storage
- chunk upload (yet to be added: https://github.com/owncloud/core/issues/13380)

I think we should make "server to server" sharing based off the "OwnCloud" storage backend, then improve that one so that both mechanisms benefit from it.

@icewind1991 @Xenopathic @schiesbn

**Comment by icewind1991** [comment]
> change detection through etags

That is done "upstream" in the DAV storage backend

The main thing that the oC external storage backend could use would be the improved scanning the s2s backend does (request all metadata in one request)

**Comment by PVince81** [comment]
One trouble is that the "DAV" storage is also used for regular WebDAV storages that might not support it. Which means that we always need to auto-detect whether the remote is an OC server that supports those special features. Not a big issue though.

**Comment by icewind1991** [comment]
The storage requests both the mtime and etag properties when checking if a file has updated, if the etag is available it's used, otherwise the mtime

**Comment by MorrisJobke** [comment]
@PVince81 @DeepDiver1975 @schiesbn @karlitschek Is this still something to think about? Or did we move into another direction? Nowadays you can disable files_external and s2s sharing is still working.

**Comment by PVince81** [comment]
I'm ok with closing this because currently the "ownCloud" backend doesn't do anything special compared to the DAV backend. If at some point we ever add more ownCloud specific stuff to the ownCloud backend, then consolidation will make sense. But that is not the case now.
