### ISSUE TITLE
Wrong units are used to represent sizes.

### ISSUE THREAD

**Issue by ogoffart** [owncloud/core#13386]
The shows uses "1kB" to represent 1024 bytes. 
This is totally wrong.  1kB is 1000 bytes.   1024 bytes is a KB or a KiB

(see https://en.wikipedia.org/wiki/Binary_prefix ,  also TB is wrong)

I would suggest to use the proper SI system with power of 1000 instead of powers of 1024.
The rational is that humans are better with powers of 10 because they use the decimal system. They can better judges if two movies of 750MB and 630 MB fits or not in 1.2GB when powers of 10 are used. 

If you really insist on keeping powers of 1024, then you should use the KiB, MiB, GiB, TiB unit.  (Or at least KB, but not "kB"!!)

**Comment by DeepDiver1975** [comment]
we had this looooong time ago already - right. anyway ...... we have a look in the next dev cycle 8.10 - THX

**Comment by Xenopathic** [comment]
Ping

My personal view is that KiB, MiB, GiB... are the better prefixes to use. Power users will get a warm fuzzy feeling that the correct units are being used, Windows users will enjoy the consistency of file sizes, and most ordinary users will notice the 'i', shrug, and carry on not knowing better. Or at least, that's how I think of it :laughing:

cc @jancborchardt

**Comment by jancborchardt** [comment]
Well, which other popular file managers use KiB, MiB etc? Using odd unit indicators just to please a few nerds (like us) but potentially throw off the majority of users is not really something we should do. ;)

**Comment by Xenopathic** [comment]
@jancborchardt I don't really use file managers anymore, so I can't comment on that, but I know that (G)Parted uses the binary prefixes. And that's fairly popular :smile:

**Comment by jancborchardt** [comment]
I meant popular in the sense of OS X Finder, Windows Explorer, iCloud, Google Drive, Dropbox. ;) And as far as I can see none of them use the KiB/MiB/etc units.

**Comment by jancborchardt** [comment]
It would be fine to use »KB« instead of »kB« though.

**Comment by SergioBertolinSG** [comment]
+1 to KiB, MiB, GiB, TiB notation :shipit: .

**Comment by guruz** [comment]
@MTRichards @cmonteroluque decision needed?

(And yes, I think we should display the same _number_ (no matter which unit) that file managers use so the users confidently see that the size is the same as on desktop)

**Comment by Xenopathic** [comment]
@guruz Different file managers display different numbers, for the same prefix. Windows file manager uses 1024-based numbers, but with MB/GB suffixes, while XFCE Thunar (correctly) uses 1000-based numbers with the MB/GB suffixes. Take your pick :smile:

That's what this issue was about - we currently do the same as Windows, with 1024 divisons rather than 1000 divisions, so we should be using the standardised KiB, MiB, GiB suffixes that denote binary numbers, rather than the decimal KB, MB, GB.

**Comment by jancborchardt** [comment]
> Windows file manager uses 1024-based numbers, but with MB/GB suffixes, while XFCE Thunar (correctly) uses 1000-based numbers with the MB/GB suffixes. Take your pick :smile:

I'd rather pick what one of the most widely used solutions does over some obscure file manager. What does OS X Finder do, for comparison?

**Comment by jancborchardt** [comment]
As far as I know Explorer, Finder, Dropbox and Google Drive use the suffixes everyone knows (KB, MB, GB etc). So as long as that’s the norm, we’ll keep doing that. The base of the numbers is a different topic but we should also keep in line with the most widely used file managers here. Please don’t just cite open source file managers used by a minority of people.

**Comment by SergioBertolinSG** [comment]
Finder uses decimal suffixes correctly (1000 bytes == 1 KB). 
IMHO, a product which main feature is syncing files should have the size clear. Changing to decimal should need a conversion, that's why I suggest an easier change, just adding the middle 'i'.

**Comment by cmonteroluque** [comment]
I have never seen anyone using the *iB notation except from German speakers, and I say this as someone who's worked with both Germans and Americans for a decade now. KB, MB, TB, GB, with the 1024 multiplier is what I've always seen in terms of storage. In my experience,  *iB is a very unused notation in the US (which I know is not the center of the world either).

**Comment by jancborchardt** [comment]
So I’d say: As long as it’s only us folks involved with the project discussing this nerdy stuff, and for now we’re doing it like most other widely used solutions, we should lay this discussion to rest. We can revisit when people actually have a problem with this.

**Comment by michaelstingl** [comment]
@jancborchardt I opened https://github.com/owncloud/client/issues/3457 because there are people having this problem. We need a solution here.

00003498

**Comment by cmonteroluque** [comment]
fine, it stays in the backlog for now

**Comment by ogoffart** [comment]
@jancborchardt this is not only neerdy stuff.  An expensive space probe crashed into Mars because of wrong unit. And that's is just an example amongst many.

**Comment by SergioBertolinSG** [comment]
From a US source:
http://physics.nist.gov/Pubs/SP330/sp330.pdf
```
These SI prefixes refer strictly to powers of 10. They should not be used to indicate powers of 2 (for example, one kilobit represents 1000 bits and not 1024 bits). The IEC has adopted prefixes for binary powers in the international standard IEC 60027-2:2005, third edition, Letter symbols to be used in electrical technology – Part 2: Telecommunications and electronics. The names and symbols for the prefixes corresponding to 210, 220, 230, 240, 250, and 260 are, respectively: kibi, Ki; mebi, Mi; gibi, Gi; tebi, Ti; pebi, Pi; and exbi, Ei. Thus, for example, one kibibyte would be written: 1 KiB = 210 B = 1024 B,
where B denotes a byte. Although these prefixes are not part of the SI, they should be used in the field of information technology to avoid the incorrect usage of the SI prefixes. 
```

**Comment by tflidd** [comment]
After Wikipedia (https://en.wikipedia.org/wiki/Mebibyte) Ubuntu and OS X use the correct (SI) units: 1 kB = 1000 byte. The size of hard disks is also given in base-10 units. Windows labels the wrong unit (MiB as MB).
The size difference between 1 TB and 1 TiB is nearly 10%. So either way, you should use the correct units.

**Comment by cdamken** [comment]
I'm agree with @ogoffart , using the right abbreviations will teach the new generations to use it properly.

Not because everybody does it wrong we have to do it that way.

**Comment by caratsch** [comment]
@cdamken I have a different opinion here: for me the sync client should use the same units of the target system.
Why do you want to confuse dummy users and don't use their abitual units. In theory you are right and I can't tell that you are wrong, but the practice is different.
The whole world is using GB/MB/KB and I don't see the reason that the sync client should use something different.
For you this is really easy to understand and to think different, but all users that have no IT background will only be confused and will open a ticket to me.

**Comment by jancborchardt** [comment]
> I'm agree with @ogoffart , using the right abbreviations will teach the new generations to use it properly.

We’re not here to confuse people (or as you call it »teach«) ;)

As @caratsch says we should use the established units and measurements. I can only fully agree with his statement:

> The whole world is using GB/MB/KB and I don't see the reason that the sync client should use something different.

**Comment by cdamken** [comment]
>We’re not here to confuse people (or as you call it »teach«) ;)

http://blogs.msdn.com/b/oldnewthing/archive/2009/06/11/9725386.aspx

Use Microsoft instead? Or try something right?

http://blogs.msdn.com/b/oldnewthing/archive/2009/06/11/9725386.aspx#9751289

>Shocking news! Microsoft is not following standards.

**Comment by ogoffart** [comment]
In my opinion, the best would be to use the SI units with proper base 1000.

Base 1000 is more intuitive: 
 700MB + 700MB = 14GB,   easy for everybody

 700 MB + 700MB = 13.03 GB , wtf.

**Comment by tflidd** [comment]
> In my opinion, the best would be to use the SI units with proper base 1000.
> 
> Base 1000 is more intuitive:
> 700MB + 700MB = 14GB, easy for everybody

I think that's the best solution (review your calculation, you probably mean 700 MB + 700 MB = 1.4 GB ;-)
That doesn't confuse people with new units, you stay with the standards and follow the tracks of OS X, Ubuntu and others.

Windows users should be used to the fact that their disk and memory size "shrinks" (there are plenty of people complaining about their 1 TB disk having only 931 GB).

**Comment by cdamken** [comment]
![objects-in-mirror](https://cloud.githubusercontent.com/assets/7264495/8827252/f5632124-308b-11e5-8e83-97a4c32e3fce.jpg)

How about putting: Megabyte size is not what you really get :smile:

**Comment by cdamken** [comment]
Sorry :worried:

**Comment by jancborchardt** [comment]
@ogoffart yes, good call. So we need to change the calculation on the server, or does it already happen like that? Also then the client and the mobile apps should follow suit if they do it differently.

**Comment by ogoffart** [comment]
Currently the server uses base 1024 (but still show SI unit)

It's a bit like if I say i'm "5.7m tall"  
I made my computation using feet but I show metters because everybody is using metters.  Of course the difference between a kB and a KB (or KiB) is not as big as the difference between a metter and a feet, but it is still wrong.

**Comment by jancborchardt** [comment]
@ogoffart @DeepDiver1975 so then can you fix it to use the SI units (KB, MB, GB) but use base 1000 if that’s what we decide to do? And then please also do the same on the client.

**Comment by cdamken** [comment]
@ogoffart will be the next client with SI units (KB, MB, GB)?

**Comment by ogoffart** [comment]
@cdamken , @jancborchardt  `KB` is not a SI units.  (`kB` is)

Currently, the git version do not use the SI units. 
I would like it to use the SI unit,  maybe it can be made an option.

**Comment by ogoffart** [comment]
Here is a pull request for the client to switch to SI units:  https://github.com/owncloud/client/pull/3558

**Comment by MorrisJobke** [comment]
Seems to be in 2.0 of the client: https://github.com/owncloud/client/blob/2.0/src/libsync/utility.cpp#L106-L109

**Comment by MorrisJobke** [comment]
@ogoffart Just pointed out that this also affects the server part. -> reopen

**Comment by tessus** [comment]
I also want to mention that all GUI file managers (which are worth anything) can switch the units.

Also, nobody uses the 10-based system in IT. Page sizes (databases, SSD), sector sizes (HD), cluster sizes (RAID), extent size (databases), filesystems (jfs, ext4, xfs, ...) - all of them use the binary unit sizes.

**Comment by tessus** [comment]
also, there are some arguments which are just wrong:

700 MB + 700 MB = 1.4 GB is always 1.4 GB no matter the base. in the discussion above people acted as if this were not the case. 

the comparison with feet and meters is also wrong. a foot has 12 inch. so 5.7 feet is not the same as 5' 7''. changing the unit changes the value, but not the representation.

**Comment by tessus** [comment]
@ogoffart I'm happy to discuss this per phone or per email. or in this thread. but I really think that a 1000 based size unit is wrong for a server SW.

**Comment by tessus** [comment]
@ogoffart the only place where people used to use the 10-based numbers is for media sizes (HD, SSD, DVD, ...)
That's why the confusion came out in the first place. Vendors wanted to make money, so they sold a 250GB hard disk, which was actually only 232GB (now we use 232GiB). Then they told people that 1 GB = 1,000,000,000,000 bytes and then the mess started. Another problem was that in the 70s the decimal suffixes were borrowed for binary values and therefore wrongly used. Only in the 90s, when the HD vendors started to use decimal values, IT had to re-evaluate the use of the units.

I'm just saying that besides HD vendors and a few file managers, the binary system is used (even with the wrong units e.g. KB instead of KiB).

**Comment by ogoffart** [comment]
> 700 MB + 700 MB = 1.4 GB is always 1.4 GB no matter the base

700 MiB + 700MiB = 2 * 734003200 = 1468006400 = 1.367 GiB

> nobody uses the 10-based system in IT.

That's not true.  I have a 8GB of ram memory, that's 8061596 bytes according to `free`  -> base 1000.  (it would be or 7.68 GiB)
I have a 128 GB SSD,  that's 128034627584 bytes according to cfdisk  ->  base 1000  (or it yould be 119 GiB)
An ADSL line that is 50Mbits/s -> base 1000.

Almost everything is in base 1000. There are certain implementation details like page size that are shown in GiB for practical reasons. But everything shown to the user is in base 1000.  

> the comparison with feet and meters is also wrong. a foot has 12 inch. so 5.7 feet is not the same as 5' 7'

That was not my point.

My point was that the server show something with the wrong unit. for example, a file that is 5800 bytes, will be display as `5.7 kB`  which is totally wrong!  Valid display would be one of `5.8 kB` or `5.7KB` or `5.7 KiB`.
But the current way to display it is wrong. Almost as wrong as showing the value un feet and using 'm' as an unit.

**Comment by tessus** [comment]
> 700 MiB + 700MiB = 2 * 734003200 = 1468006400 = 1.367 GiB

Yep, I made a mistake there.

>That's not true. I have a 8GB of ram memory, that's 8061596 bytes according to free -> base 1000. (it would be or 7.68 GiB)

Hmm, my free shows 8176704 bytes. In any case, shouldn't free show 8000000 bytes, if it was base 1000?

>I have a 128 GB SSD, that's 128034627584 bytes according to cfdisk -> base 1000 (or it yould be 119 GiB)

What about fdisk? What about df? e.g. df on AIX shows 512 byte blocks by default. Linux shows 1024 byte blocks.

>An ADSL line that is 50Mbits/s -> base 1000.

Yes, the M and G in LAN speeds are base 1000. But note the bit. Yet again, you do not have a base 10 there. It's base 8, if you want the value in bytes. And most likely you do, because you don't use file sizes in bits, but in bytes.

> for example, a file that is 5800 bytes, will be display as 5.7 kB which is totally wrong! Valid display would be one of 5.8 kB or 5.7KB or 5.7 KiB

I agree with you. The displayed units are often wrong, because the suffixes kilo/mega/giga/tera were borrowed to describe the next 1024 magnitude.
Unless you know the code or it is explained in the help, you can never be sure.
e.g. I still use the terms MB and GB wrongly, because I learned it this way. for me a megabyte will always have 1024 kilobytes. and a kilobyte will always have 1024 bytes.

**Comment by dragotin** [comment]
Fixed in the client with commits https://github.com/owncloud/client/commit/995b42d0fc31bee5882b2f6a704400f4f221c192 and https://github.com/owncloud/client/commit/9004fd6d11326f4a0d851f1ad27ffcab7bcf3f0d

**Comment by ogoffart** [comment]
The server still uses wrong unit and need to be fixed.

kB is defined to be 1000 bytes.  If you want to keep 1024 bytes it needs to be 'KB' (upper case K)  or 'KiB'.  (But IMHO a base 1000 is more logical)

**Comment by michaelstingl** [comment]
@ogoffart please check https://github.com/owncloud/enterprise/issues/798#issuecomment-137460349 and https://github.com/owncloud/enterprise/issues/798#issuecomment-139196110 before you change behavior (again). /cc @dragotin @MTRichards

**Comment by ogoffart** [comment]
@michaelstingl  But even after the last commit, the client display KB and not kB

**Comment by gig13** [comment]
@ogoffart @MTRichards @bboule 
Has this been reverted to the original calculations? When will it be available?

**Comment by bboule** [comment]
@ogoffart @MTRichards @cmonteroluque  Sorry to poke this but the message is a bit confusing here what exactly are we going to do with this?  I see it is in the backlog can we move it to an actual milestone?

**Comment by MTRichards** [comment]
The change was reverted on the desktop client, will be released with the next client release (2.0.2) as far as I know. No changes was ever made on the server side, as per the above.

We just need to put the server to KB, which is a bug. Just needs a bug priority.

**Comment by dragotin** [comment]
confirm @MTRichards assumptions about the client: Revert will come with 2.0.2

**Comment by bboule** [comment]
@michaelstingl are we ok to close this out?

**Comment by MorrisJobke** [comment]
@michaelstingl 2.0.2 was released in October. Please reopen if this is still an issue.

**Comment by ogoffart** [comment]
It is still an issue.  The issue is on the server.  (And when the client fixed the problem people complained that they were not matching the server and it was more important to have it wrong everywhere than having it fixed everywhere)

See the first comment for the detail.  In my opinion this is an imortant issue that should not be hard to fix.

**Comment by bboule** [comment]
@cmonteroluque  @MTRichards we seem to have a bit of a stand off here with this issue?  can we fix or should we simply send this to backlog?

**Comment by MorrisJobke** [comment]
> @cmonteroluque @MTRichards we seem to have a bit of a stand off here with this issue? can we fix or should we simply send this to backlog?

We can fix - the question here is: In which direction should the fix go? 1000 as base and KB, MB, GB as unit? Looks so.

**Comment by tessus** [comment]
On the server 2-based sizes are used (which IMO are still mostly used by IT professionals), so if you have to fix anything, please change the units to show that 2-based values are used.
1000-based values are used by hard drive manufacturers and people who started with IT 5 years ago.

**Comment by ogoffart** [comment]
@tessus, we already have had this discussion. But things are not as simple as you say.  You may prefer 2-base, but i'l pretty sure the majority of the people prefer base 1000. Dropbox uses base 1000 (as shown in the screenshot ealier), google uses base 1000,  check for yourself in this calculator:  https://www.google.com/search?q=1+MB+in+Bytes

**Comment by tessus** [comment]
To clarify my previous statement (b/c I can already hear the backlash): in storage areas, 2-based sizes are mostly used. RAID stripe sizes, cluster sizes, page sizes for SSD chips, table space page sizes (databases), memory allocation for most commercial database products, ...
Transfer speeds have always been measured in 1000-based numbers, although they are also displayed in bits, so you have to convert the numbers as well, if you want them in bytes.

Some client applications started to use 1000-based numbers a while back, but I still can't get used to it and I'm sure I'm not the only one. Also, in the clients I use, I can switch between 2 and 10 based.

**Comment by tessus** [comment]
@ogoffart I do feel very strongly about this topic. please give people a choice. If you have to change the current behavior/size/units, please allow people to choose.

**Comment by tflidd** [comment]
Why wouldn't you want to use metric prefixes with decimal numbers? I don't see where this is useful or where it makes calculations easier. Except you use binary numbers as well, which is actually fun.

Would it make sense to detect the operating system and show the binary-prefix (with wrong label) for Windows users and the metric prefix for others? It's not good to see a different file size on your system and on owncloud.

**Comment by tessus** [comment]
I still think that a client option is the only real and complete solution:

<img width="334" alt="screen shot 2016-01-06 at 12 47 06" src="https://cloud.githubusercontent.com/assets/223439/12149794/aed0fb20-b473-11e5-99c8-59968be55663.png">

Of course, you can also adjust the units (kB, KiB, ...), but I think above pic (especially the explanations in grey) says it all.

**Comment by jancborchardt** [comment]
> Dropbox uses base 1000 (as shown in the screenshot ealier), google uses base 1000

As @ogoffart says … case closed folks.

Please consider what implementing an option for this entails: a setting useful for only a very very small minority, something which keeps attention from the really important settings when you need to crawl through it, and something we need to maintain. I think the devs explained enough why it's not a good idea. And if someone really feels that super strongly about it, maybe they can compile it themselves? (I don't want to seem off-putting here, simply pragmatic – as we are with ownCloud, otherwise we would not be where we are today.)

**Comment by MorrisJobke** [comment]
8.2.2 server:

<img width="337" alt="bildschirmfoto 2016-01-19 um 09 55 59" src="https://cloud.githubusercontent.com/assets/245432/12413961/dd130130-be92-11e5-9e88-3431562ffb78.png">

2.1.0 client:

![bildschirmfoto 2016-01-19 um 09 55 54](https://cloud.githubusercontent.com/assets/245432/12413971/e5d79920-be92-11e5-9eab-a2897523e76a.png)


They are the same. Closing this now.

**Comment by ogoffart** [comment]
@MorrisJobke This issue is not about the client, it's about the server.  It got sided tracked because the client used a different one, but the issue is still there.

The server still use "kB" for 1024 bytes while this is defined as 1024 bytes in every documentation you can find this it wrong.
The client uses "KB" for 1024 bytes

**Comment by atorstling** [comment]
This is still a problem in the detail view on dropbox.com. MiB numbers reported as "MB". Reopen?

**Comment by michaelstingl** [comment]
dropbox.com ? What needs to be fixed in ownCloud or in ownCloud clients?

**Comment by atorstling** [comment]
@michaelstingl Oops, my bad.
