### ISSUE TITLE
LDAP (ActiveDirectory) - Update via sync issue

### ISSUE THREAD

**Issue by theonlydoo** [owncloud/core#13392]
Hi there, I noticed an issue with AD sync, here is a simple description :

### Steps to reproduce
1. Peer your owncloud to an active Directory
2. Sync your first users only with ```(&(|(objectclass=organizationalPerson))(|(memberof=CN=Share,OU=ZZZZ,OU=Resources,DC=xxxx,DC=yyy)))``` for user filter and ```(objectclass=organizationalPerson)``` as login filter
3. Login a test1 user
4. Edit your login filter to ```(&(&(|(objectclass=organizationalPerson))(|(memberof=CN=Share,OU=ZZZ,OU=Resources,DC=xxx,DC=yyy)))(|(samaccountname=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))(|(cn=%uid)(displayName=%uid)(distinguishedName=%uid)(mail=%uid)(name=%uid))))```
5. Login with a user test2 

### Expected behaviour
Have mail email addresses synced for both user1 and user2

### Actual behaviour
```bash
# mysql -e 'select * from owncloud.oc_preferences\G'|egrep -i "@|userid"|sort -u -k2
     userid: user2
configvalue: user2@xxx.yyy
     userid: user1
```
So user1 doesn't have any "email attribute" in ```configvalue``` field

### Server configuration
**Operating system**: Debian 7
**NGINX** :
```
nginx version: nginx/1.2.1
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-log-path=/var/log/nginx/access.log --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --lock-path=/var/lock/nginx.lock --pid-path=/var/run/nginx.pid --with-pcre-jit --with-debug --with-http_addition_module --with-http_dav_module --with-http_geoip_module --with-http_gzip_static_module --with-http_image_filter_module --with-http_realip_module --with-http_stub_status_module --with-http_ssl_module --with-http_sub_module --with-http_xslt_module --with-ipv6 --with-sha1=/usr/include/openssl --with-md5=/usr/include/openssl --with-mail --with-mail_ssl_module --add-module=/tmp/buildd/nginx-1.2.1/debian/modules/nginx-auth-pam --add-module=/tmp/buildd/nginx-1.2.1/debian/modules/nginx-echo --add-module=/tmp/buildd/nginx-1.2.1/debian/modules/nginx-upstream-fair --add-module=/tmp/buildd/nginx-1.2.1/debian/modules/nginx-dav-ext-module
```
**PHP5-FPM** :http://sebsauvage.net/paste/?6ceae4dcc381e17b#sywyQj7OhK8lRe+QXGeGW9o0SKjMBGnRAOYz24x2KTI=
**MariaDB** : 10.0

**ownCloud server** : https://download.owncloud.org/community/owncloud-latest.tar.bz2
** Fresh install** (2 weeks ago)

**Apps enabled** : LDAP, Activity, Deleted Files, Encryption, PDFViewer, Share Files, Updater, Versions
**Config.php** :
```php
<?php
$CONFIG = array (
  'instanceid' => 'oc93b9675303',
  'passwordsalt' => 'n0',
  'secret' => 'hum',
  'trusted_domains' => 
  array (
    0 => 'xxx-owncloud.intra',
    1 => 'share.xxx.com',
  ),
  'datadirectory' => '/var/www/owncloud/owncloud/data',
  'overwrite.cli.url' => 'https://xxx-owncloud.intra',
  'dbtype' => 'mysql',
  'version' => '7.0.4.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'yyy',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'forcessl' => true,
  'mail_from_address' => 'webmaster',
  'mail_smtpmode' => 'sendmail',
  'mail_domain' => 'xxx.com',
);
```
**Are you using external storage, if yes which one:** None

**Are you using encryption:** Yes

### Client configuration
**Browser:** Firefox latest

**Operating system:** Fedora 20
### Logs
Nothing, really :(

### Tests done on my own 
See the first part of the issue, i can post more if needed

### Error diagnose 

ownCloud doesn't sync new attributes for already synced account 

### Closing words
If you need to have more details, I'll give you more !

**Comment by karlitschek** [comment]
@blizzz

**Comment by blizzz** [comment]
@theonlydoo some details like email addresses will be read only every 24h hours. You may retry you login with user1 again and see whether it was set.

Most likely with 8.1 we will read email address more regularly whenever a user is retrieved from LDAP.

**Comment by theonlydoo** [comment]
Hello @blizzz , it seems that the user that we are speaking of has still no email linked to his account. He doesn't have the possibility to add it via the "user" menu, I think that it's due to the fact that  it's an LDAP user and not a "classic" one.

**Comment by theonlydoo** [comment]
Hey, after another 24Hrs I finally had my emails synced ! Thx @blizzz  for the information
