### ISSUE TITLE
Some apps have uninstall button

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#13405]
### Steps to reproduce

1. Install master and enterprise tar balls 
2. go to the apps page
3. scroll not enabled list of apps
4. only antivirus and elasticsearch apps have uninstall buttons

### Expected behaviour

I'm not sure - I would expect all apps to have the button or no apps to have the button

### Actual behaviour

Two apps have an uninstall button

![p236](https://cloud.githubusercontent.com/assets/8480343/5765207/c96f9b88-9cc5-11e4-9c73-d11562c777db.PNG)

### Server configuration

CentOS 6.6
PHP 5.4.34
ownCloud 8.0 alpha 2 (daily) Build:2015-01-14T04:12:43+00:00

**Comment by MorrisJobke** [comment]
Internal apps can't be uninstalled (this was the wanted behaviour in earlier versions). I guess we can drop that behaviour nowadays.

@DeepDiver1975 @karlitschek Opinions?

**Comment by DeepDiver1975** [comment]
uninstall is intended for apps which have been downloaded from the appstore and got disabled - this is triggered by a tag in info.xml - should be enough to update the info.xml files

**Comment by DeepDiver1975** [comment]
the uninstall behaviour itself is valid

**Comment by jnfrmarks** [comment]
@MorrisJobke @DeepDiver1975 

While the behavior is valid, these two apps should not have the button.  Is that correct?

**Comment by MorrisJobke** [comment]
@jnfrmarks Yes. Let me look up the missing element.

**Comment by MorrisJobke** [comment]
https://github.com/owncloud/files_antivirus/pull/10

**Comment by MorrisJobke** [comment]
The PRs should solve the issue

**Comment by DeepDiver1975** [comment]
PRs merged
