### ISSUE TITLE
Disable local storage / use external storage only

### ISSUE THREAD

**Issue by sammcj** [owncloud/core#13408]
It'd be great if you could disable internal storage or at least re-map it to use external SMB storage.

This would mean you could keep your owncloud server as a web server and use your standard SMB file storage for all files, one less place to backup and one less file server running a web app.

**Comment by DeepDiver1975** [comment]
you can mount a smb share to your web servers and use this share then as your data dir

**Comment by sammcj** [comment]
That's not a very nice solution when you have an organisation of 100~ people that already have auto-mapping home drives etc... already.

**Comment by mmattel** [comment]
I guess I understand what is meant.

There is a already existing storage environment, lets say it is a AD with users and shares and the users have their homedir defined in a SMB share as part of the AD.
When using oC as another frontend to the shares / home for the users, you get now a additional "home", a oC home, in parallel to the already existing home from the AD.

What @sammcj is requesting is (pls correct me if I am wrong), if the current oC user home, which is under the /data directory, can be be managed like the other storages (and therefore be disabled). From my interpretation, oC must have a users home where the user can store data, but it is worth thinkging that this home could be "externalized" with already existing methods of oC. The interresting thing is, that at least for SMB we already have a good basis. This is LDAP for the credentials and $user for the subdirectory for the users home.

**Comment by preexo** [comment]
+1 for this feature request! separating the storage and the front end on two different machines should be normal practice and therefore it would be nice if the local storage could be completely disabled.

**Comment by PVince81** [comment]
In theory this is already possible on the technical level. You need to find a way to trick ownCloud (hack) to mount system-wide external storages to an empty mount point, or basically "/$user/files/" instead of the usual mount point like "/$user/files/subdir".

**Comment by PVince81** [comment]
So here the idea is to allow the web UI to accept "/" as a valid mount point value.

Careful testing needs to be done to make sure this doesn't break other things.
Also needs to be documented.

**Comment by butonic** [comment]
actually the web ui allows it ... the server side prevents `/`. This limitation can be removed with:
```diff
diff --git a/apps/files_external/controller/storagescontroller.php b/apps/files_external/controller/storagescontroller.php
index b26e85c..8b2d418 100644
--- a/apps/files_external/controller/storagescontroller.php
+++ b/apps/files_external/controller/storagescontroller.php
@@ -144,7 +144,7 @@ abstract class StoragesController extends Controller {
         */
        protected function validate(StorageConfig $storage) {
                $mountPoint = $storage->getMountPoint();
-               if ($mountPoint === '' || $mountPoint === '/') {
+               if ($mountPoint === '') {
                        return new DataResponse(
                                array(
                                        'message' => (string)$this->l10n->t('Invalid mount point')
```

bear in mind that this is likely to cause problems. Let us know if you try!

**Comment by PVince81** [comment]
Another approach that could allow this: https://github.com/owncloud/core/issues/29502.

With that approach one could specify a specific external storage entry as the home for a user.

**Comment by spaceone** [comment]
I need this, too.

**Comment by didierm** [comment]
Reopen, please.

**Comment by prilly-dev** [comment]
i need this also
