### ISSUE TITLE
Renaming a folder deletes its content

### ISSUE THREAD

**Issue by loxK** [owncloud/core#13409]
Hello,

I wasn't happy with the default folder name for automatic android photos uploads. So, I renamed it using the Owncloud's WebUI and then every client (Ubuntu, Android, WebUI) do show an empty folder.

I had a look to the database and the table oc_filecache, all files are there and the 'parent' is correctly pointing to the renamed folder. 
Also the files do exist in the user's folder on the server, in the renamed directory ...

Server: Ubuntu 14.04
Owncloud V7.0.4.1, installed via the OpenSuse apt repository

**Comment by MorrisJobke** [comment]
Looks like #13391 

How big is that folder (GBs and file count)?

**Comment by DeepDiver1975** [comment]
no feedback -> close
