### ISSUE TITLE
[Windows] Renaming, moving or deleting files isn't possible.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#13410]
### Steps to reproduce

1. Try to rename a file.
2. Try to delete a file
3. Try to move a file to another folder.

### Expected behaviour
File is renamed, deleted or moved correctly.

### Actual behaviour

1. Renaming a file shows an alert saying it can't be renamed and duplicates it (new name and old one).
2. Files can't be deleted.
3. Moving a file to a folder shows an alert "FileX couldn't be moved", an it is duplicated, one inside the folder and one in its previous location.

### Server configuration
**Operating system**:
Windows Server 2008 R2 Enterprise

**Web server:**
IIS

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.0.0.2","versionstring":"8.0 alpha 2","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
none

**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password and passwordsalt)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** no

### Client configuration
**Browser:**
Chrome

***Logs***

```
Error	PHP	Undefined index: /C:/owncloud_data/admin_win2/files/owncloudusermanual.pdf at C:\owncloud\apps\files_locking\lib\lockingwrapper.php#140	2015-01-16T07:18:20+00:00
Error	PHP	rename(C:\owncloud_data/admin_win2/files/owncloudusermanual.pdf,C:\owncloud_data/admin_win2/files/documents/owncloudusermanual.pdf): The process cannot access the file because it is being used by another process. (code: 32) at C:\owncloud\lib\private\files\storage\mappedlocal.php#218	2015-01-16T07:18:20+00:00
Error	PHP	rmdir(C:\owncloud_data/admin_win2/files/documents/owncloudusermanual.pdf): Invalid argument at C:\owncloud\lib\private\files\storage\mappedlocal.php#289	2015-01-16T07:18:20+00:00
Error	PHP	Invalid argument supplied for foreach() at C:\owncloud\lib\private\files\storage\mappedlocal.php#275
```

cc @jnfrmarks

**Comment by MorrisJobke** [comment]
cc @nickvergessen

**Comment by nickvergessen** [comment]
I can not reproduce that in a simple case where just one file is moved.
But there are quite some other cases where it can happen.

**Comment by xpresservers** [comment]
I am also facing same problem. Same behavior on Windows Server 2012 R2 Std Edition with IIS. Fresh installation of v 8.0.3

**Comment by nickvergessen** [comment]
Please disable the files_locking app

**Comment by enoch85** [comment]
@nickvergessen Isn't a better fix to fix the actual problem? :)

**Comment by jospoortvliet** [comment]
@enoch85 and what other bugfix or feature would you drop from 8.1 to have time to fix this problem for a platform we no longer support? It is always a matter of time and priorities... And, very egoistically, I prefer Joas to spend his time on things which make ownCloud 8.1 better ;-)

**Comment by enoch85** [comment]
Didn't mean it in a bad way. And no I'd rather keep everything in 8.1 than
make this a priority right now.
Den 28 maj 2015 12:01 em skrev "Jos Poortvliet" <notifications@github.com>:

**Comment by nickvergessen** [comment]
> @nickvergessen Isn't a better fix to fix the actual problem? :)

It is fixed for the next release, but that is the actual "workaround" which has the same result.
https://github.com/owncloud/files_locking/pull/11
https://github.com/owncloud/files_locking/pull/10
