### ISSUE TITLE
JS API / container for apps to embed viewers/editors

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13414]
Currently every file viewer / file editor app is registering a FileAction and then doing whatever they want to try and embed themselves into the current view.
Also, back button support, URL and breadcrumb need to be managed by the app itself.

A new API / container need to be developed in the files app that allows apps to register viewer/editor handlers. The API will automatically support this:
1) getViewerContainer() will return the container that the viewer must use to embed itself
2) event APIs to communicate between the viewer and the files app (open event, close event, etc)
3) back button handling
4) URL handling:
- modify URL to point to the file upon file opening
- if the URL was opened directly in the browser, automatically open the matching editor
  5) this must also work in public preview mode (files_sharing public link)

@DeepDiver1975 @tomneedham @LukasReschke

**Comment by michaelstingl** [comment]
00002190

**Comment by SergioBertolinSG** [comment]
The problem with going back using the browser remains in 8.0.0.4, I think users will find it really annoying.
Entering a folder, previewing a pdf or a text file and going back distorts web UI.

**Comment by PVince81** [comment]
I can try and look into this for 8.1

**Comment by PVince81** [comment]
One important part is that the viewer implementations should not compute download URLs by themselves. They need to use the ones given by the API/container because the viewer cannot predict in which view it is. This would also make it possible to view files in the trashbin.

The container could also inject an instance of JS Files API (https://github.com/owncloud/core/issues/13905) so the viewer/app can access any file operation if needed (including download/upload)

**Comment by tomneedham** [comment]
@PVince81 Yes. Hard part is handling the additional stuff that the text editor needs.

**Comment by PVince81** [comment]
I thought about it. If I remember well the additional part is about checking if the file was changed on the server ? Basically some kind of conflict detection ?
This should be doable over WebDAV too, just like the sync client does.
If the viewer knows the etag of the file before saving, it could call `api.saveFile(data, {etag: oldEtag});` and the WebDAV call might fail with "409 conflict" if the file was changed.

**Comment by tomneedham** [comment]
Essentially yes. The only other bit is some fixes on the encoding, but this might be handled by core now, considering this was written for OC3: https://github.com/owncloud/files_texteditor/blob/master/ajax/savefile.php#L47

**Comment by PVince81** [comment]
I see. Either it could be done in pure JS (if that is even possible), or the text editor would still have to use its own endpoint, but that one needs to be made flexible to be able to load files from the trashbin as well.

**Comment by jancborchardt** [comment]
Would be good indeed!

**Comment by jancborchardt** [comment]
Would be good indeed. Then we can consistently place the viewers, fade the background, display file actions etc.

**Comment by PVince81** [comment]
Enhancement/refactor/API change, but we're past feature freeze -> 8.2

**Comment by oparoz** [comment]
Yes, please! :)

**Comment by PVince81** [comment]
- Idea: viewers or app could register JS URL routes to make it work with the history API (back/forward button) instead of the anchor hackery

**Comment by oparoz** [comment]
I guess this is now for 9.0 @PVince81 ?

**Comment by PVince81** [comment]
Yes.
@cmonteroluque defer ?

**Comment by PVince81** [comment]
@michaelstingl see https://github.com/owncloud/files_texteditor/issues/50, is that an acceptable workaround ?

**Comment by michaelstingl** [comment]
@PVince81 Planned for 9.0 oder 8.2 as milestone in https://github.com/owncloud/files_texteditor/pull/78 says?

**Comment by PVince81** [comment]
That PR is already merged for 8.2, so the issue should hopefully be gone in that version. (I haven't tried it myself)

**Comment by cmonteroluque** [comment]
@rperezb can we get a test?

**Comment by cmonteroluque** [comment]
@owncloud/qa-team need a test please so we can determine status

**Comment by cmonteroluque** [comment]
@rperezb @SergioBertolinSG @davitol ping

**Comment by SergioBertolinSG** [comment]
Breadcrumbs problem remains https://github.com/owncloud/core/issues/13794#issuecomment-144464066. Most problems of files_texteditor are not even possible with the new version.

**Comment by PVince81** [comment]
The question here is mostly whether the blue ticket part was fixed.

This ticket here needs to stay open to track the implementation of a proper viewer/editor API in core, in which apps can plug in.

**Comment by michaelstingl** [comment]
@PVince81 The blue ticket part is described here: https://github.com/owncloud/files_texteditor/issues/50#issuecomment-66123127

**Comment by DeepDiver1975** [comment]
> @PVince81 The blue ticket part is described here: owncloud/files_texteditor#50 (comment)

This is fixed - just tested with 8.2. 

@PVince81 what about this enhancement ticket - I guess we move it to 9.0 ???

**Comment by PVince81** [comment]
Yes, move to 9.0 or backlog

**Comment by DeepDiver1975** [comment]
> Yes, move to 9.0 or backlog

@cmonteroluque

**Comment by PVince81** [comment]
@michaelstingl can you confirm that the blue ticket part is fixed ? Last time I checked the back button was properly closing the text editor, so it should work.

We should defer this ticket here to 9.0 or backlog and also remove the blue ticket tag as its part was fixed.

**Comment by cmonteroluque** [comment]
holding off for @michaelstingl's answer

**Comment by michaelstingl** [comment]
@PVince81 @cmonteroluque I can confirm: Closing text editor with browser back button keeps user in the current directory. This solves this problem described here: https://github.com/owncloud/files_texteditor/issues/50#issuecomment-66123127 Thanks!

**Comment by PVince81** [comment]
Moving to backlog for now, no time for this

**Comment by PVince81** [comment]
By extension, also to provide a diff view, see https://github.com/owncloud/core/issues/4056

**Comment by PVince81** [comment]
this will be reconsidered with Phoenix https://github.com/owncloud/phoenix/issues/215
