### ISSUE TITLE
LDAP - user in multiple groups not working

### ISSUE THREAD

**Issue by PeteSSS** [owncloud/core#13426]
### Steps to reproduce
Users are member of multiple groups

### Expected behaviour
In user backend the groups per member should be ticked for all valid groups

### Actual behaviour
If a user is member of multiple groups the backend lists random memberships: valid groups but not all. There are side effects in different apps (e.g. calendar via caldav not synchronizing for shared calendars)

### Causes
I have located the bug in file group_ldap.php 
```php
	private function getGroupsByMember($dn, &$seen = null) {
...
		$groups = $this->access->fetchListOfGroups($filter,
			array($this->access->connection->ldapGroupDisplayName, 'dn'));

}
```

function fetchListOfGroups in lib/access.php expects as 3rd parameter a $limit (set to null by default)

### Workaround (Bugfix?)
I have set that parameter to 500 and the user list and the group memberships are populated as expected.

```php
		$groups = $this->access->fetchListOfGroups($filter,
			array($this->access->connection->ldapGroupDisplayName, 'dn'), 500);
```

There might be more $limit parameters not set to valid values or left as null.

**Comment by karlitschek** [comment]
@blizzz

**Comment by blizzz** [comment]
@PeteSSS does this fix it for you? https://github.com/owncloud/core/pull/13280

**Comment by PeteSSS** [comment]
No. I had already applied that fix. It seems for me that the $limit parameter has values set in former calls.

**Comment by PeteSSS** [comment]
Not to forget:
We have ~200 owncloud user and they have confirmed: calendars now synchronizing as they should do.

**Comment by flattermann** [comment]
@PeteSSS 
Thanks, the workaround works fine!
My users are now able to access their shared calendars again...

**Comment by flattermann** [comment]
BTW: I also tried the patch from #13280, but that did not solve the problem for me.

**Comment by fnerdwq** [comment]
@PeteSSS: Thanks to your fix, my problem solved as well - only one group membership was shown for a given user (actually the reverse listing *users in group* is correct anyway).

**Comment by blizzz** [comment]
Does https://github.com/owncloud/core/pull/14707 fix your issue?

**Comment by PeteSSS** [comment]
Doesn't fix it.
Why is it so difficult to solve this problem?

**Comment by blizzz** [comment]
The limit parameter is optional. Passing 500 indiciates that there is an issue when it is initiated with 0. That you get "random" groups, is somewhat bogus though.

To make sure: when tested it, the results where not taken from cache (by default LDAP results are cached for 10 minutes).

**Comment by PeteSSS** [comment]
No, I have used a fresh installation of owncloud 7.

**Comment by PeteSSS** [comment]
I have to apologize: The fix solves the problem. I had inserted the new code at the wrong place.
Thank you, blizzz.

**Comment by blizzz** [comment]
@PeteSSS Glad it works! Thank you for testing!

**Comment by lchigami** [comment]
This bug still persists in OwnCloud 9.0
Why was this ticket closed?
Every time I update my Owncloud through apt, I have to manually patch the code with the workaround...

**Comment by blizzz** [comment]
@lchigami what exactly do you patch? #14707 was merged. You might want to open a new issue.

**Comment by sirbeagle** [comment]
We ran across this bug in ownCloud v9.0.2 as well - users coming from Active Directory via LDAP were only a member of a single group. Implementing the fix from @lchigami seemed to do the trick - users now belong to multiple groups. We made the change to the `getGroupsByMember` function at line 570 in the file `/apps/user_ldap/group_ldap.php`.

**Comment by sirbeagle** [comment]
@blizzz We upgraded to 9.1 beta 2 and still have the same issue - we only see our LDAP users as a member of a single group each. We made the same change listed at the top of the issue and the group mapping then worked properly. For reference we changed line 576 in `/apps/user_ldap/lib/Group_LDAP.php` and added in an extra parameter of `500` and all seems to be good.

**Comment by worim** [comment]
Problem still exists. Set up a new ownCloud 9.0.2 and still needed to add the 500 to line 570. Please reopen and fix.
