### ISSUE TITLE
No dynamic (javascript) translations with firefox v.35

### ISSUE THREAD

**Issue by avoine** [owncloud/core#13428]
When navigating Owncloud 7.0.4.2 with firefox v.35 where is no dynamic (javascript) translation and
with those errors in the javascript console:

    Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery-1.10.0.min.js:1

    Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ jquery-1.10.0.min.js:6

    Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://nuage.auf.org 'unsafe-eval'"). files

    window.controllers is deprecated. Do not use it for UA detection. ace.js:1716

    Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.

**Comment by LukasReschke** [comment]
Please use the issue template https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#submitting-issues

**Comment by LukasReschke** [comment]
Checked the referenced https://nuage.auf.org/ – there is some custom app that uses inline JS => not a ownCloud problem => get in touch with the app author to fix this.
