### ISSUE TITLE
Upgrade process and NDB mysql cluster

### ISSUE THREAD

**Issue by mrktt** [owncloud/core#13437]
The upgrade process creates a temp table for each db table (oc_oc_filecache_xyzrandom for oc_filecache), inserts all the rows from the original table into the new one, drops the old one and renames the new one to oc_filecache.

This is a no brainer in standard mysql installation. However it's a problem with NDB cluster installation.
INSERT statements of large group of rows (oc_filecache can scale up easily to hundred thousands of rows if one adds external storages like big SMB shares) are a pity in NDB cluster, as the memory requirements scale to huge amounts of RAM.

I manage owncloud using a 2 node NDB cluster (with 2 apache each mounting gluster fs for local storage) and even with 16GB of RAM i can't complete a migration from say 7.0.2 to 7.0.4 without some kind of manual intervention with 1.2 million rows. 

1) Is really necessary the recreation of the table even if no changes to the schema are beeing made? (I'm not so sure of this, but it has happened at every step from 7.0 to 7.0.4 so it seems a bit strange that the schema has changed every single time)

2) some kind of oc_filecache cleaning mechanism should be allowed, I know there are other Issues open on this, take this as a +1. I've like 200k rows from a remote storage that no one is mounting now that is clearly useless stuff, no share pointing to it etc.

3) If the recreation of tables is mandatory can the INSERT statement be tweaked to do the the job like in 100k rows step?

It's a bummer to be forced to reserve huge amount of ram only for the updates when during the normal use the cluster is fine with like 1/10 of the RAM.
thx

**Comment by LukasReschke** [comment]
>  1) Is really necessary the recreation of the table even if no changes to the schema are beeing made? (I'm not so sure of this, but it has happened at every step from 7.0 to 7.0.4 so it seems a bit strange that the schema has changed every single time)

You're probably referring to the schema migration test. Please take a look at the occ tool – you can skip those migrations there: 

```
➜  core git:(master) ✗ ./occ upgrade --help
Usage:
 upgrade [--skip-migration-test] [--dry-run]

Options:
 --skip-migration-test  skips the database schema migration simulation and update directly
 --dry-run              only runs the database schema migration simulation, do not actually update
 --help (-h)            Display this help message.
 --quiet (-q)           Do not output any message.
 --verbose (-v|vv|vvv)  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug.
 --version (-V)         Display this application version.
 --ansi                 Force ANSI output.
 --no-ansi              Disable ANSI output.
 --no-interaction (-n)  Do not ask any interactive question.
```

> 2) some kind of oc_filecache cleaning mechanism should be allowed, I know there are other Issues open on this, take this as a +1. I've like 200k rows from a remote storage that no one is mounting now that is clearly useless stuff, no share pointing to it etc.
> 3) If the recreation of tables is mandatory can the INSERT statement be tweaked to do the the job like in 100k rows step?

Well… Then please reference the original issue instead of creating a new one. Also I think such discussions would be better suited on either the user or the developer mailing list.
