### ISSUE TITLE
Can't open pictures with shared link

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#13430]
...or the browser hangs.

### Steps to reproduce

Go to the links on https://www.en0ch.se/about-me/ (Västerås, Edefors, Trelleborg, and Stockholm.

### Expected behaviour

No error

### Actual behaviour

The piture takes forever to load, or the browser hangs with a "wait" or "close" site.

### Server configuration

Ubuntu Server 12.04

**Database:**
Server version: 5.5.38-0ubuntu0.12.04.1 (Ubuntu)
PHP version:
PHP 5.3.10-1ubuntu3.15 with Suhosin-Patch (cli) (built: Oct 29 2014 12:19:04)

**ownCloud version: (see ownCloud admin page)**
7.0.4
*Updated from an older ownCloud or fresh install:*
Updated from stable 5 and then later stable 6

**List of activated apps:**
Activity
Calender 
Contacts
Deleted files
Documents
First Run Wizard
Full Text Search
Music
PDF Viewer
Pictures
Share Files
Tasks
Text Editor
Updater
Versions
Video Viewer
ownCloud SMS

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'oc106ccbdf7c',
  'passwordsalt' => 'example',
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.4.2',
  'dbname' => 'owncloud',
  'dbhost' => 'example.se',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_enoch',
  'dbpassword' => 'example',
  'installed' => true,
  'maxZipInputSize' => 0,
  'allowZipDownload' => true,
  'session_lifetime' => 1800,
  'forcessl' => true,
  'updatechecker' => true,
  'loglevel' => '2',
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' =>
  array (
    0 => 'example.se',
    1 => 'www.example.se',
  ),
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'mail_smtpmode' => 'php',
  'mail_smtpname' => 'enoch',
  'mail_smtppassword' => 'EXAMPLE',
  'secret' => 'EXAMPLE$
);

```

**Are you using external storage, if yes which one: local/smb/sftp/...**
No
**Are you using encryption: yes/no**
No

### Client configuration

**Browser:**
Version 39.0.2171.99 m
**Operating system:**
Windows 8.1
**Sync Client**
1.7.1 stable

### Logs

**Web server error log**

```
Insert your webserver log here
```

**ownCloud log (data/owncloud.log)**

```
no errors
```

**Browser log**

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by enoch85** [comment]
CC @PVince81

**Comment by DeepDiver1975** [comment]
Hmm - all the links just work fine here for me

**Comment by RealRancor** [comment]
Same here, just have tested all four links/images and works as expected.

```
Browser:
Version 39.0.2171.99
```

Probably Chrome? Have just tested with Chromium 9.0.2171.71-2 from Debian and also works as expected.

**Comment by enoch85** [comment]
Hmm.. Yes, works on IE. Sorry, didn't test.

Chrome :-1:

**Comment by RealRancor** [comment]
Mhhh, i have used Chromium and it worked. Could be still usefull to know the difference between a non-working:

Chrome 39.0.2171.99

vs a working

Chromium 39.0.2171.71-2
