### ISSUE TITLE
Users disk usage

### ISSUE THREAD

**Issue by hoerup** [owncloud/core#1344]
When viewing the user list (settings/users.php) it would be nice to see each users current disk consumption / usage preferably both as a MB/GB number and as a percentage of quota (if set)

**Comment by jospoortvliet** [comment]
I don't think this ever made it in, it isn't in 8.2 at least... Am I wrong @blizzz ?

**Comment by madmas** [comment]
@jospoortvliet I see it the same way, but it's also not checked in the checklist section "Additional Features" in #7151 (which has not been updated for a while now)

**Comment by blizzz** [comment]
No, it's not in and there are no plans to get it into 9.0 either.

**Comment by jospoortvliet** [comment]
Ok so this should be kept open.

**Comment by RealRancor** [comment]
What about https://apps.owncloud.com/content/show.php/Storage+Usage+%2B+Activity+Charts?content=166746 for now?

**Comment by PVince81** [comment]
Removing junior job tag, this is tricky and I remember @icewind1991 saying that the APIs aren't quite ready to make this work efficiently.

**Comment by PVince81** [comment]
This slightly twisted Mysql query can return the used space for all users:
```
MariaDB [owncloud]> select m.user_id, fc.size from oc_mounts m, oc_filecache fc, oc_storages s where m.mount_point=concat('/', m.user_id, '/') and s.numeric_id=m.storage_id and fc.storage=m.storage_id and fc.name='files';
+---------+---------+
| user_id | size    |
+---------+---------+
| admin   |     163 |
| user1   | 4774179 |
| user2   | 1571107 |
+---------+---------+
3 rows in set (0.00 sec)
```

I still wish there was a way to directly retrieve home storages and user ids from oc_storages...

**Comment by PVince81** [comment]
(which obviously wouldn't work for custom storage/cache implementations if someone decided to not use oc_filecache)

**Comment by lustyffh** [comment]
are there any plans to include this functionality in the upcoming versions?

**Comment by PVince81** [comment]
Not for 9.2.

But if anyone volunteers to work on it and submit a PR, we can include it.
The way I see it, the minimum required work is as follows:
- add an optional field in the users page to display the disk usage
- the field must be disable-able using the settings on the bottom left
- if the setting is disabled, the SQL query must not run as it can be expensive
- if the setting is enabled, querying the user list would run the query from https://github.com/owncloud/core/issues/1344#issuecomment-245526902 and include its result for each returned user

**Comment by PVince81** [comment]
- [ ] requires API: https://github.com/owncloud/core/issues/26829

**Comment by PVince81** [comment]
Looks like the provisioning API already returns the usage quota.
However the web UI uses a different API. It should be possible to reuse whatever the provisioning API is using to get the usage and display it in the users page.

**Comment by PVince81** [comment]
Acceptance criteria from the closed duplicate ticket:

As an admin, I want to be able to easily and quickly see the current quota usage of all of the users on the system.

**Acceptance Criteria:**
This should be integrated in the user management panel. This displays the % of used quota next to the quota drop down for each user in the table. The option is set in the settings panel on the bottom left (the gear). When the option is selected, a new column appears with this info displayed

**Comment by PVince81** [comment]
The query has a small mistake. It must be "fc.path", not "fc.name".

Here:
```sql
select m.user_id, fc.size from oc_mounts m, oc_filecache fc, oc_storages s where m.mount_point=concat('/', m.user_id, '/') and s.numeric_id=m.storage_id and fc.storage=m.storage_id and fc.path='files';
```

**Comment by JackSlateur** [comment]
And with sorted human-size:
```
select m.user_id, concat(convert(fc.size / 1024 / 1024, integer), 'MB') as size from oc_mounts m, oc_filecache fc, oc_storages s where m.mount_point=concat('/', m.user_id, '/') and s.numeric_id=m.storage_id and fc.storage=m.storage_id and fc.path='files' order by fc.size desc;
```

**Comment by geekonthepc** [comment]
Hi, is there any chance of this being followed up as it would be very useful to be able to see user quota usage?

**Comment by PVince81** [comment]
@pmaier1

**Comment by matfiz** [comment]
@ownclouders if community proposes PR with this, would it be accepted, or there is some (personal info?) reason why it should not be added?

**Comment by pmaier1** [comment]
> if community proposes PR with this, would it be accepted, or there is some (personal info?) reason why it should not be added?

Yes, you're more than welcome to go for a PR, absolutely. The solution needs to work performant in installations with several thousands of users. That's the main pain point, I guess.
If you want to contribute, you're welcome join our public chat on talk.owncloud.com to get in touch.

**Comment by micbar** [comment]
Was implemented in the metrics app as an enterprise feature.
