### ISSUE TITLE
Searching in folder with many files freezes/crashes browser tab

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#13442]
On current master with Chrome on OS X when searching in the root folder with about 100k files called `foo` with a numerical suffix when searching for "test" the browser tab gets unresponsive and in my case it even got completely white (thankfully Chrome runs all tabs sandboxed so not my whole browser crashed):

![screen shot 2015-01-18 at 18 01 53](https://cloud.githubusercontent.com/assets/878997/5793222/282eee94-9f3c-11e4-9bfc-42bc3441c0c5.png)

**Comment by LukasReschke** [comment]
That is caused by the search JS scripts which is allocating memory without end and requiring 100% CPU.

![screen shot 2015-01-18 at 18 04 22](https://cloud.githubusercontent.com/assets/878997/5793227/752ec138-9f3c-11e4-86fd-81d7c3c4705c.png)

@butonic FYI

**Comment by PVince81** [comment]
Needs search + pagination: https://github.com/owncloud/core/issues/25373
