### ISSUE TITLE
Error when creating files with lang different/special characters, umlauts on windows

### ISSUE THREAD

**Issue by crewer** [owncloud/core#13444]
Hello,
I'm facing same issue with special characters or umlauts in the latest version OC regarding this #94 
I searched whole github regarding this type of issue and no help at all. Please help me.

I use IIS7.5 on Windows 2008 R2 Enterprise x64 with Czech locale
 Latest owncloud 7.0.4
 php-5.6.4-nts-Win32-VC11-x64
 mysql-5.6.22-winx64

I need to use characters like this ěščřžýáíéťňĚŠČŘŽÝÁÍÉŇŤ and so on but still getting errors :-(

I have searched and read lots of discussions but everything without working solution. It seems to be quite old bug.
 Did you made any progress with it? OC is great solution, but it is useless for me without Czech language filename support.

I can see your demo version supports everything I tested, what is the reason? Linux machine? Is there a solution for Windows as well?

I will appreciate your help.

Thank you!

**Comment by LukasReschke** [comment]
> I can see your demo version supports everything I tested, what is the reason? Linux machine? 

Yes

**Comment by LukasReschke** [comment]
@DeepDiver1975 @nickvergessen Filemapper fun
