### ISSUE TITLE
Incorrect "From" field in the "Share Link" notification (Email link to person) 

### ISSUE THREAD

**Issue by mpeltier** [owncloud/core#13468]
### Steps to reproduce 
1. Log in as ("X Y" \<x.y@domain.org\>) 
2. Create a share link 
3. Write z@domain2.org in "Email link to person" and click to send 
 
### Expected behaviour 
A mail from "X Y" \<x.y@domain.org\> should be sent to <z@domain2.org> in order to inform the remote user that the share has been created. 
 
### Actual behaviour 
A mail from "X Y" \<noreply@domain.org\> is sent to <z@domain2.org>, where noreply=mail_from_address and domain.org=mail_domain in config.php. So users can be confused and try to reply to the mail as they see "X Y" as sender. 
 
It seems that the code is present in the constructor of MailNotifications (lib/private/share/mailnotifications.php) but that the constructor is never called with $sender arg != null? 
 
### Server configuration 
Centos 7 
7.0.3 (updated from 7.0.2) 
 
**The content of config/config.php:** 
 
$CONFIG = array ( 
  'instanceid' => 'ocd2fcdac93c', 
  'passwordsalt' => 'x', 
  'datadirectory' => '/var/www/html/owncloud/data', 
  'dbuser' => 'oc_mpeltier', 
  'dbpassword' => 'x, 
  'installed' => true, 
  'trusted_domains' =>  
  array ( 
    0 => 'cloud.domain.org, 
  ), 
  'dbtype' => 'mysql', 
  'version' => '7.0.2.1', 
  'dbname' => 'owncloud', 
  'dbhost' => 'localhost', 
  'dbtableprefix' => 'oc_', 
  'asset-pipeline.enabled' => false, 
  'default_language' => 'en', 
  'proxy' => 'proxy.domain.org:8080', 
  'proxyuserpwd' => 'user:pass, 
  'mail_smtpmode' => 'smtp', 
  'mail_from_address' => 'noreply', 
  'mail_domain' => 'domain.org', 
  'mail_smtphost' => 'mail.domain.org', 
  'mail_smtpport' => '25', 
  'preview_libreoffice_path' => '/usr/bin/libreoffice', 
  'trashbin_retention_obligation' => 180, 
  'theme' => 'mytheme', 
  'customclient_desktop' => 'http://owncloud.org/sync-clients/', 
  'customclient_android' => 'https://play.google.com/store/apps/details?id=com.owncloud.android', 
  'customclient_ios' => 'https://itunes.apple.com/us/app/owncloud/id543672169?mt=8', 
  'log_type' => 'owncloud', 
  'logfile' => '/var/www/html/owncloud/data/log/owncloud.log', 
  'loglevel' => '0', 
);

**Comment by MorrisJobke** [comment]
@michaelstingl Looks similar to your issue. Let me check that

**Comment by centredecalcul** [comment]
Same bug with Owncloud 8.0.2

**Comment by DeepDiver1975** [comment]
From my understanding this is fixed since 8.1 -> closing

**Comment by MorrisJobke** [comment]
Yes, fixed by #15541 and backported to 7.0.6 and 8.0.3
