### ISSUE TITLE
"Blog size" should be "Block size"

### ISSUE THREAD

**Issue by bantu** [owncloud/core#13460]
https://github.com/owncloud/core/blob/64ee942e7dde5225fa2e9e44bd2b488300650205/apps/files_encryption/lib/stream.php#L263
https://github.com/owncloud/core/blob/26861a98c59c39901b9127831b7edf0c0a3eff40/apps/files_encryption/exception/encryptionexception.php#L43

@schiesbn

**Comment by MorrisJobke** [comment]
fix is in #13471
