### ISSUE TITLE
\OC_Util::isValidFileName has to be manually called for file actions

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#13462]
Some files such as `newfolder.php` or `newfile.php` contain the following code snippet:

```php
if(!OCP\Util::isValidFileName($foldername)) {
	$result['data'] = array('message' => (string)$l10n->t("Invalid name, '\\', '/', '<', '>', ':', '\"', '|', '?' and '*' are not allowed."));
	OCP\JSON::error($result);
	exit();
}
```

I seriously wonder why this check is opt-in and not automatically enforced as are other checks in `\OC\Files\View::basicOperation`

@icewind1991 FYI

**Comment by DeepDiver1975** [comment]
within 8.1 we shall implement an isValidFileName/isValidPath to the storage interface. Valid file and path names are storage specific. there is already a tech dept on this afaik ...

**Comment by PVince81** [comment]
We could add a method "isValidFileName()" and "isValidPath()" on the storage implementation. Then every storage is free to implement its own depending on the storage type. (CC @icewind1991)

But what @LukasReschke meant is that the check should be systematic.
If we move newfile.php and newfolder.php to app framework controllers, this check could be done in a middleware.

**Comment by PVince81** [comment]
Ref: https://github.com/owncloud/core/issues/13640

**Comment by DeepDiver1975** [comment]
somewhat related to #13640 and #14629

**Comment by PVince81** [comment]
Is this still an issue ? I remember there was some validation code put in core, might be enough to cover this ticket ?

**Comment by DeepDiver1975** [comment]
As far as I rememeber the final cleanup is missing -> 8.2

**Comment by PVince81** [comment]
@DeepDiver1975 final cleanup still missing ?

**Comment by cmonteroluque** [comment]
@DeepDiver1975 @PVince81 what's the cleanup?

**Comment by cmonteroluque** [comment]
This bug will fall off 8.2 if not resolved by 6 Oct
