### ISSUE TITLE
we are now in 2015 - in some places 2014 is still displayed - e.g. first run wizard

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#13469]

**Comment by MorrisJobke** [comment]
I couldn't find any date in the ownCloud interface (public share, personal settings, admin settings, first run wizard,...) What do you mean?

![firstrunwizard](https://cloud.githubusercontent.com/assets/245432/5802432/6fcf74da-9ff5-11e4-8b1b-8b9a53cf77d9.png)

The dates of the apps in the apps management?

**Comment by DeepDiver1975** [comment]
![bildschirmfoto von 2015-01-19 16 10 25](https://cloud.githubusercontent.com/assets/1005065/5802458/b96664f0-9ff5-11e4-8f13-a8ec0be66b72.png)

**Comment by MorrisJobke** [comment]
Cloned just now.
![english-first-run-wizard](https://cloud.githubusercontent.com/assets/245432/5802513/04e8b9d2-9ff6-11e4-8f44-7e1b1350f419.png)

**Comment by nickvergessen** [comment]
@MorrisJobke https://github.com/owncloud/firstrunwizard/blob/master/templates/wizard.php#L66
