### ISSUE TITLE
[User Management] Textboxes aren't long enough

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#13464]
### Steps to reproduce

Having an admin account:
1. Go to users
2. Activate send email address to new users
### Expected behaviour

All textboxes are long enough.
### Actual behaviour

Text is sliced because textboxes are short.
### Server configuration

**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.0.0.1","versionstring":"8.0 beta 1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
none

**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password and passwordsalt)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** no
### Client configuration

**Browser:**
Chrome

![screen shot 2015-01-16 at 11 05 40](https://cloud.githubusercontent.com/assets/9048796/5801255/4b821710-9fe9-11e4-9e6d-b4de84cdfd64.png)

**Comment by DeepDiver1975** [comment]
@jancborchardt

**Comment by DeepDiver1975** [comment]
not critical -> 8.1

**Comment by jancborchardt** [comment]
Hm … that is our standard textbox size, and changing it will likely break layouts elsewhere. Since it’s a language-specific problem there will likely always be problems. It doesn’t impair the understanding, so I would keep it as it is.

In the future we could have some intelligent text sizing which makes the text a bit smaller to fit in the input field.

**Comment by Volker-E** [comment]
@jancborchardt Well, if I understand your comment correct, the integration of CSS property unit size values like the whole `v*` family has possibly strong advantages, like direct adaptability to available screen space, but brings less control and more responsibilities for designers.

You have to make sure, that elements get min-width and there's to my knowledge currently no fallback when it comes to internationalization of UI elements, comparing very long words of e.g. German or Turkish to English and squeezing them into little real estate.
Elements should IMHO always have the possibility to expand at least slighty, may the reason be i18n or just text zooming.

**Comment by jancborchardt** [comment]
8.2 because any textbox changes here would likely break layouts.
