### ISSUE TITLE
The Files Web GUI should support archive unpacking

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#13465]
As a user I want to be able to drop archives (zips, rars, 7zip, etc) on my Files interface and have the interface automatically detect that I'm uploading an archive and offer to unpack it for me.
The Files app actions menu should also offer to unpack archives for me, should I decide to unpack those at a later time.

#### Requirements:
- [ ] Add archive type detection to the web uploader
- [ ] Add modal window to ask the user what he wants to do
- [ ] Implement calls to the corresponding unarchiver
- [ ] Add unpacking file action to the menu

**Comment by DeepDiver1975** [comment]
not a core feature from my pov - but can be added as an app

**Comment by oparoz** [comment]
I assumed system calls would be required in order to support most archivers and I don't like apps which require more privilege than core, but it turns out [PHP supports quite a few different formats out of the box](http://php.net/manual/en/refs.compression.php), so maybe this should be an app instead.

**Comment by PVince81** [comment]
Could be done maybe as part of the archive app ? https://github.com/owncloud/apps/tree/master/files_archive

**Comment by Xenopathic** [comment]
Agree with @PVince81 - the archive app is the natural place to implement this
