### ISSUE TITLE
Hook manager

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#13477]
We need a hook manager in the server container which allows registration of hook listeners with delayed loading of the explicit listener.

Something like in the activity manager:https://github.com/owncloud/core/blob/master/lib/public/activity/imanager.php#L58

**Comment by PVince81** [comment]
and then move the hooks that are registered in base.php to their relevant places: https://github.com/owncloud/core/blob/master/lib/base.php#L676

**Comment by PVince81** [comment]
If "preview", "avatar" and "tags" were some kind of module (subapp ?) they could register the hook in their init code.

**Comment by PVince81** [comment]
module aka plugin a bit like I did in JS for the tags: https://github.com/owncloud/core/blob/master/apps/files/js/tagsplugin.js#L179

**Comment by DeepDiver1975** [comment]
actually fixed by https://github.com/owncloud/core/pull/18316
