### ISSUE TITLE
Get rid of oc.js

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#13476]
`oc.js` leaks too much information to third-party sites (i.e. if somebody includes oc.js they get information such as whether the user is administrator or not etc…). 

We should migrate it to some other approach. (either requesting a JSON blob and caching that in the browser or add the variables to the template)

Long-term goal though…

**Comment by LukasReschke** [comment]
(that file was actually just created because of our CSP that forbids inline JS)

**Comment by aheusingfeld** [comment]
What's the status of this? After running `apt-get upgrade` on my Ubuntu 14.04 LTS which installed owncloud_8.1.0-4, the web UI is unusable and in the webconsole there is the error message "https://mydomain.de/cloud/index.php/core/js/oc.js HTTP404". Indeed there is no `oc.js` in `/var/www/owncloud/core/js`!

**Comment by RealRancor** [comment]
@aheusingfeld oc.js is an "on the fly" created .js script as you can see here:

https://demo.owncloud.org/index.php/core/js/oc.js

**Comment by aheusingfeld** [comment]
Thanks for the quick response. Do you have any idea why it's not being generated anymore?

**Comment by RealRancor** [comment]
Please continue in your other issue as this issue here is about to remove this auto-generated oc.js completely which is currently not related to your issue.

**Comment by PVince81** [comment]
Loading a JSON file won't be possible until **every** app is ported to be able to be loaded asynchronously on the JS side. Unfortunately most apps still assume that everything they need (including the config and "js.js" with the OC namespace) is available at the time they are loaded.

We need to rethink the way how apps are designed and loaded.

If we had something like requirejs, it would be possible to make apps depend on the config loader to read the config which would make sure that it's loaded first.

See https://github.com/owncloud/core/issues/17169
