### ISSUE TITLE
Files/Folders are removed from cache when attempting to delete them without permissions over WebDAV

### ISSUE THREAD

**Issue by EviLzLiKeNeO** [owncloud/core#13488]
ownCloud version info:

$OC_Version = array(7,8,1,0);
$OC_VersionString = '8.0 pre alpha';
$OC_Edition = '';
$OC_Channel = 'daily';
$OC_Build = '2014-12-02T04:14:34+00:00';

Scenario:
A folder with the sticky bit set containing files and folders owned by another user.

1.) Connect to the site using any WebDAV client (tested Cyberduck, MS WebDAV mapped drive, and PDF Expert on iOS).
2.) Navigate to the folder with the sticky bit set and locate a file owned by another user.
3.) Attempt to delete the file.

Behavior:
1.) The file remains on the server and some WebDAV clients report an error (Cyberduck was the only one that did in my testing... MS WebDAV and PDF Expert did not).
2.) When refreshing the folder in the WebDAV client, the file is no longer visible.
3.) After making a change to the folder with the sticky bit set (e.g. upload a file or edit an existing file you have permission for) to force the ownCloud cache to reload.
4.) Refresh the WebDAV client and the missing file is visible again.

Expected Behavior:
1.) The file should have never been removed from the cache since SabreDAV does indeed report an error in the logs and the file is not actually deleted.

Related Config Entry Settings:
  'version' => '7.8.1.0',
  'filesystem_check_changes' => 2,
  'filesystem_cache_readonly' => false,

SabreDAV Error Entry:
{"reqId":"d2d5c196a25850038b86acfb5445cf20","remoteAddr":"192.168.201.1","app":"webdav","message":"Exception: {\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Tree.php(102): OC_Connector_Sabre_File->delete()\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(691): Sabre\\\\DAV\\\\Tree->delete('FolderWithStickyBitSet\\...')\\n#2 [internal function]: Sabre\\\\DAV\\\\Server->httpDelete('FolderWithStickyBitSet\\...')\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(474): call_user_func(Array, 'FolderWithStickyBitSet\\...')\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('DELETE', 'FolderWithStickyBitSet\\...')\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/remote.php(62): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#7 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":192}","level":4,"time":"2015-01-19T21:02:40+00:00"}

**Comment by karlitschek** [comment]
@icewind1991 @schiesbn What do you think?

**Comment by EviLzLiKeNeO** [comment]
I just realized that it actually reports the file as deleted in the activity application as well.  If that helps you diagnose the issue at all.
