### ISSUE TITLE
ownCloud login impossible after upgrade of cURL library - stream_wrapper_register(): Protocol smb:// is already defined

### ISSUE THREAD

**Issue by j-ed** [owncloud/core#13485]
## Actual behavior

Without any specific announcement, but after a web server restart,  I realized that I wasn't able to login to ownCloud anymore. After entering my login credentials the following error message was shown on the screen: `Failed to register protocol`.

I found the following, more detailed, error message In the log file:
```
{"reqId":"54bd07d9f3e3f","app":"PHP","message":"stream_wrapper_register(): Protocol smb:\/\/ is already defined. at \/var\/www\/htdocs\/owncloud\/apps\/files_external\/3rdparty\/smb4php\/smb.php#515","level":0,"time":"2015-01-19 14:34:18+01:00","method":"OPTIONS","url":"\/owncloud\/remote.php\/caldav\/calendars\/juergen\/"}
```

I checked the server configuration with `phpinfo()` and found out that "**smb**" was listed under the registered protocols and especially that "libcurl" also listed smb as its supported protocols.
That pointed me into the right direction because I had updated the libcurl library from v7.38.0 to **cURL v7.40.0** (released on January 8th 2015) only a couple of days ago. After downgrading the library to v7.38.0, the smb protocol wasn't listed as *registered protocol* anymore and ownCloud worked as expected again.

It seems that the developers of cURL have not only applied bug fixes but also added initials SMB support
(`smb: Added initial support for the SMB/CIFS protocol`). A side effect of this change is, that ownCloud refuses to work and denies every connection.

Here you will find the change the relevant change note of the cURL v7.40.0 release:
http://curl.haxx.se/changes.html

Due to the fact that more and more users will most likely install the new library in the future, ownCloud should double-check if a desired protocol is already registered before it tries to register it on its own using the `stream_wrapper_register()` function.

#### Server Configuration

OS: Linux 3.2.54
Web server: Apache2 2.4.10
Database: MySQL 5.1.73
PHP version: 5.4.35
ownCloud version: 7.0.4

#### Client Configuration

Browser: Firefox 35.0
Operating system: Windows 7

**Comment by LukasReschke** [comment]
@DeepDiver1975 @icewind1991 That looks pretty serious for me.

**Comment by j-ed** [comment]
Has no-one else reported this problem until now?

**Comment by jfqd** [comment]
Same issue here. After updating curl to v7.40.0 I got the same error message.

**Comment by Xenopathic** [comment]
In 8.x this won't be a problem anymore, due to @icewind1991's new library that doesn't register a stream wrapper. In oC 7 this problem will continue (and likely get worse as servers and shared hosting update cURL versions)

**Comment by PVince81** [comment]
Is this still happening with 8.0.6, 8.1.4 ?

**Comment by j-ed** [comment]
@PVince81 I've not seen that error anymore, after I had upgraded my server to 8.1.3.

**Comment by acroyear** [comment]
What is the workaround for shared hosts? This just started happening to me today.
