### ISSUE TITLE
Something leads to a single contact being multiplied over and over

### ISSUE THREAD

**Issue by sixtyfive** [owncloud/core#13489]
There's one contact in my addressbook which exists a couple of hundred times. I'm clicking the tickbox of every instance of it now. My hope is that by deleting them all in ownCloud as well as the one version of it that exists in Thunderbird, the one in EDS and the one in Android, this spooky behaviour will come to an end.

Syncing, in 2015, still seems to be an issue the world cannot solve, so perhaps Elon Musk's fears of advanced AIs killing all of humanity can be laid to rest for now. 

What I don't get, though, is that there's plenty of "duplicate finder" applications for contacts that work quite well. Since all these contacts are exactly the same in all seven of their fields, perhaps there's some sort of "possible duplicate sanity check" could be implemented before any sync partner is allowed to upload a contact into ownCloud?

**Comment by karlitschek** [comment]
sounds like a problem in the contacts app. Can you open this in the contacts repository please?

**Comment by sixtyfive** [comment]
Sorry, didn't spot "contacts" when browsing through the repo list. Re-opened under https://github.com/owncloud/contacts/issues/783 now.
