### ISSUE TITLE
OwnCloud App on iPhone 5 iOS 8.1.2 problem

### ISSUE THREAD

**Issue by splash94** [owncloud/core#13481]
Hi, I bought the owncloud app on App store to connect through my personal cloud.. When I insert the server it's all ok and the connection is established (my server is not ssl enabled so it is http://...).
Then I insert my user and my pass but the app says "Is not possible to connect to the server now". My friend with Android app can connect with the same credentials..
Can anybody help me?
Thanks
Francesco

**Comment by LukasReschke** [comment]
Can you please reopen this at the iOS bugtracker at https://github.com/owncloud/ios? 

Thanks!

**Comment by splash94** [comment]
Ok sorry! :)
