### ISSUE TITLE
Parameter for default sort order (in file list and image gallery), incl. sort by date 

### ISSUE THREAD

**Issue by MartinW2** [owncloud/core#13484]
It should be possible to change the default sort order of files according to administration parameters.
Options should not only include to sort by file name, but especially by upload date descending.
Many installations would prefer to have their newest uploads on top, so that visitors of shared folders see the most recent stuff on top.
A first step in this direction is depicted here - however it's just a hack and lacking detailed owncloud knowhow: https://forum.owncloud.org/viewtopic.php?f=29&t=25816

**Comment by phtheref** [comment]
Plz, this is option we really needed!!

**Comment by DeepDiver1975** [comment]
@jancborchardt

**Comment by jancborchardt** [comment]
The sort order should simply be remembered to what the user last chose. This is not something an admin should decide globally. The issue for that is https://github.com/owncloud/core/issues/10788 – let’s continue there. :)

**Comment by MartinW2** [comment]
Sorry, i don't agree with the opinion of jancborchardt.

1) If the user is not logged in, there is no reliable possibility to store his sort order preference. A main advantage of owncloud is the possibility to share links that do NOT need any login.

2) Especially first-time users or unexperienced users are happy to be presented with a view that already is sorted in reasonable order. Depending on the usecase, an admin can very well decide what is the preferred order. For any kind of collection, where items come in from time to time, it makes sense to have newest items first. I claim this is a main use case of owncloud for private use.

Both (1) and (2) are good reasons to allow the administrator to set a default order, at least to let it be sorted by upload date desc.
So, it's NOT THE SAME as allowing the user to sort himself (which is a nice feature of course, but does not meet the point here).
Please reopen this request.
