### ISSUE TITLE
The Preview class needs better protection against breakage

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#13493]
When an encryption key gets lost per example, the preview generator will break and the script will stop executing, potentially breaking whole apps like Gallery.
#### Steps to reproduce
- Install master, turn on encryption, add image files
- Optional: Install a Gallery app
- Go to data/<user>/files_encryption/keys/<file_to_test>
- Rename fileKey
- Delete all thumbnails (data/<user>/thumbnails)
- Reload the gallery or files app

In the files App, there will be a missing thumbnail. In the gallery app, processing will have stopped after having encountered that problem.

This can by avoided by catching Exceptions in `getPreview()` and perhaps sending back either a broken image icon or the mime icon

**Comment by oparoz** [comment]
@georgehrke, your thoughts?

**Comment by DeepDiver1975** [comment]
@oparoz do you have error messages/exception in the log? THX

**Comment by oparoz** [comment]
Here you go @DeepDiver1975
```
{"reqId":"54bd481853ddb","app":"index","message":"Exception: Encryption key not found for \"\/fondation\/files\/RH_GRAVURES\/006 \u00a9 Fondation Hainard.jpg\" during attempted read via stream","level":4,"time":"2015-01-19T18:08:24+00:00","method":"GET","url":"\/index.php\/apps\/galleryplus\/thumbnails?images=&scale=1&square=1&token=&requesttoken=9247b26bf4ceab0e9abe"}
```

**Comment by DeepDiver1975** [comment]
THX @oparoz - there should be at least proper handling of such an exception in the preview controller to return proper http status codes - if there only would be a preview controller ....

@georgehrke please open a tech dept issue for 8.1 - use appframework for preview system - THX

**Comment by PVince81** [comment]
Any update ?

**Comment by oparoz** [comment]
Well, nothing has changed in Preview and nothing will change until 9.0, but I don't know yet if this specific use case has been fixed.

**Comment by DeepDiver1975** [comment]
May I suggest to move this issue to the dav backend?

There is a totally stupid thumbnail resource as of today - https://github.com/DeepDiver1975/dav/tree/master/lib/thumbnail

We might want to extend this (or add a second resource) to allow proper preview generation for any use case in ownCloud

**Comment by DeepDiver1975** [comment]
https://github.com/DeepDiver1975/dav/issues/10

**Comment by oparoz** [comment]
I guess the plan is for the DAV endpoint to throw an error in case anything happens (exception, fatal error, etc.), so that would take care of the issue, without having to fix Preview. It only works though if nobody calls Preview directly any more, but there is still IPreview in OCP.

**Comment by DeepDiver1975** [comment]
Ipreview can throw exceptions as well - as long as its properly documented.

**Comment by DeepDiver1975** [comment]
@karlitschek @cmonteroluque 9.0 from my POV by now

**Comment by karlitschek** [comment]
agreed

**Comment by DeepDiver1975** [comment]
THX

**Comment by PVince81** [comment]
Any update ? Or move to 9.1 ?

**Comment by oparoz** [comment]
AFAIK, preview is still an ajax endpoint and the preview system is still not using the AppFramework ,so best to move this to 9.1.
