### ISSUE TITLE
Don't show share action in public share view

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#13492]
Steps to reproduce:

1. share folder from server1 to server2
2. user on server2 shares the folder as public link
3. open the public link

The folder listing will look like this:

![snapshot1](https://cloud.githubusercontent.com/assets/1589737/5809894/5a7e14b2-a03e-11e4-81a7-85e3ea2a2927.png)

The share action shouldn't be there because it is useless for the public link view and it exposes a both a user-id and  a owncloud server address.

**Comment by PVince81** [comment]
Was this share created using the new API ?
Does it also happen for regular public shares ?

**Comment by schiesbn** [comment]
@PVince81 it was created with the new server2server sharing. I didn't try it with regular public link shares yet. Would be awesome if you could have a look at it, if you have time for it. I assume that it can be fixed at the JS side. Thanks a lot!

**Comment by PVince81** [comment]
Busy with more critical bugs atm, unassigning in case someone else is free to take it.

**Comment by PVince81** [comment]
Ok, got a bit of time now to have a look.

**Comment by PVince81** [comment]
@schiesbn the public file list is never populated for me (regardless whether I'm logged in or not), see https://github.com/owncloud/core/issues/13207

**Comment by PVince81** [comment]
Ok, it requires https://github.com/owncloud/core/pull/13490 to be able to see the list.

**Comment by PVince81** [comment]
The share action only appears if logged in as a user, not in non-logged in.

Fix is on the way.

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/core/issues/13679 but blocked by the other PR
