### ISSUE TITLE
Overview page of pending+rejected shares

### ISSUE THREAD

**Issue by schiessle** [owncloud/core#13495]
If a user unshares a file from themself there is no way to bring the share back. We should have a sidebar entry "rejected shares" (or similar) which lists all shares a user unshared from themself until the owner unshares the file. This enabled the user to bring back a share if they unshared the file by accident. Currently there is no way to bring back a share after the user unshared it from themself.

**Comment by PVince81** [comment]
Good idea!

@owncloud/designers

**Comment by MorrisJobke** [comment]
What about listing incoming shares in such an overview page in the sidebar too. see https://github.com/owncloud/core/issues/4435#issuecomment-73251295

**Comment by schiesbn** [comment]
> What about listing incoming shares in such an overview page in the sidebar too

That's exactly my plans :smile: 

It is also listed there as "nice to have": https://github.com/owncloud/core/issues/12285#issuecomment-63823361

**Comment by MorrisJobke** [comment]
Awesome :)

**Comment by jancborchardt** [comment]
We should have a situational »Pending shares« sidebar entry which will list both incoming and rejected shares – if there are any.
Incoming should be at the top, and rejected ones sorted at the bottom and greyed out.

For incoming shares you can accept or reject them, and for rejected shares you can re-accept (undo rejection) or permanently delete. (Otherwise you’re stuck with a »pending shares« section for longer than you want.)

**Comment by PVince81** [comment]
Sounds good

**Comment by MorrisJobke** [comment]
* [ ] Multiple incoming shares UX is broken #13690

**Comment by MorrisJobke** [comment]
from @cdamken 00002646

**Comment by MorrisJobke** [comment]
@MTRichards This was a requested feature from @cdamken

**Comment by PVince81** [comment]
Past feature freeze -> 8.2

**Comment by jancborchardt** [comment]
Past this feature freeze too –> 9.0

**Comment by rullzer** [comment]
@PVince81 @cmonteroluque still no work on this has been done. So no 9.0...

**Comment by PVince81** [comment]
Moving to 9.1 then. @cmonteroluque 

This would go along very well with the other proposed feature of having users accept local shares too: https://github.com/owncloud/core/issues/19153

**Comment by rullzer** [comment]
@PVince81 fully agree.
@MTRichards FYI

**Comment by MTRichards** [comment]
Concur. Will take a look in the context of 9.1.

**Comment by PVince81** [comment]
This page would also allow to re-accept shares that were rejected / unshared from self by group members, as requested here https://github.com/owncloud/core/issues/19159

**Comment by cmonteroluque** [comment]
nod

**Comment by PVince81** [comment]
We're past feature freeze, moving to 9.2

**Comment by dragotin** [comment]
Wouldn't that mean an API that returns a list of the shares, with a state that tells if it is accepted or not? Remember that we want to use the same APIs over all clients, also the web client. The desktop client currently gives the user the chance to accept or decline a share through the notification API (very handy...) but once accepted or declined, it can not display a list again.

**Comment by jsteremberg** [comment]
is there a way to prevent the user to delete a folder shared with him? Thank you

**Comment by jancborchardt** [comment]
@jsteremberg yep, just uncheck the »can edit« permission, then they can not edit or delete anything. :)

**Comment by jsteremberg** [comment]
@jancborchardt I did, but even though the real files are not being deleted, the user can still delete the folder that was shared with him from his "view". Can I disable the option to delete or even make the folder disappear from their view, completely?

**Comment by jancborchardt** [comment]
@jsteremberg not at this point, no.

**Comment by brozkeff** [comment]
Database hack (workaround) how to revert group-wise shared folders that a certain use (member of the group) unshared for him/herself (Thanks to PVince81):

- to show you the „opted-out“ shares, enter SQL command:
select * from oc_share where permissions=0 and share_type=2

- if you delete the undesired entry, the share will be visible again for the user from the „share_with“ column

**Comment by Aka4Code** [comment]
Here is solution based on @brozkeff last post, simple trigger in MySQL db, that prevents delete of shared folder:

```sql
CREATE TRIGGER `_UndoUserShareDelete` BEFORE INSERT ON `oc_share`
 FOR EACH ROW BEGIN
	IF (NEW.permissions=0 and NEW.share_type=2) THEN 
		signal sqlstate '45000';
	END IF;
END;
```

When this trigger exist then users will not have ability to delete shared folders.

**Comment by molul** [comment]
I'd love a "Prevent from deleting" option for shared files and folders.

Current behaviour is not really really bad, but it would be really nice being able to avoid removing some really important files and folders. It's not that uncommon that one wants to make sure that certain users can't delete a folder.

**Comment by WhistleMaster** [comment]
@Aka4Code, would it be also possible to have a similar trigger but to prevent user from renaming a shared folder ?

**Comment by abolinhas** [comment]
@Aka4Code your trigger work like a charm

**Comment by PVince81** [comment]
@pmaier1 backlog ?

Note that some of the API work was already done here https://github.com/owncloud/core/pull/24439

**Comment by mapeze** [comment]
This trigger worked for me to avoid share rename and/or deletion:

`CREATE TRIGGER `_UndoUserShareDeleteOrRename` BEFORE INSERT ON `oc_share`
 FOR EACH ROW BEGIN
    IF (NEW.share_type=2) THEN 
        signal sqlstate '45000';
    END IF;
END;`

If the share has been already renamed before to create this trigger, the user can continue renaming it.

**Comment by kernelpanic01** [comment]
@mapeze When trying to create the trigger I get the following error:
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'END IF' at line 1

I Have Mysql 5.6 on Debian 8.

**Comment by mapeze** [comment]
I corrected the code format. Try now.

**Comment by kernelpanic01** [comment]
@mapeze 
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| owncloud           |
+--------------------+
2 rows in set (0.00 sec)

mysql> use owncloud
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> CREATE TRIGGER `_UndoUserShareDeleteOrRename` BEFORE INSERT ON `oc_share`
    ->     FOR EACH ROW BEGIN
    ->     IF (NEW.share_type=2) THEN
    ->     signal sqlstate '45000';
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 4
mysql>     END IF;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'END IF' at line 1
mysql>     END;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'END' at line 1
mysql> CREATE TRIGGER `_UndoUserShareDeleteOrRename` BEFORE INSERT ON 'oc_share' FOR EACH ROW BEGIN IF (NEW.share_type=2) THEN signal sqlstate '45000';
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''oc_share' FOR EACH ROW BEGIN IF (NEW.share_type=2) THEN signal sqlstate '45000'' at line 1
mysql>
mysql>
mysql> CREATE TRIGGER `_UndoUserShareDeleteOrRename` BEFORE INSERT ON `oc_share` FOR EACH ROW BEGIN IF (NEW.share_type=2) THEN signal sqlstate '45000';
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

**Comment by kernelpanic01** [comment]
@mapeze mysql> SELECT @@version;
+-----------------+
| @@version       |
+-----------------+
| 5.5.53-0+deb8u1 |
+-----------------+
1 row in set (0.00 sec)

mysql>

**Comment by mapeze** [comment]
You need first to change delimiter to for example // and then execute this code. More info here http://stackoverflow.com/questions/1346637/what-does-delimiter-do-in-a-trigger
After delimiter change to //, paste the code, hit enter, type // and hit enter.

**Comment by ApolloLV** [comment]
How has a high-severity issue like this one no Assignee after 2 years?

**Comment by mixMugz** [comment]
Any news?

**Comment by PVince81** [comment]
Estimate: 3-5 md

**Comment by kernelpanic01** [comment]
Hi. 
I want to prevent a user that I share a folder from being able to rename the folder. I do not give you any permission and yet you can rename it

**Comment by phil-davis** [comment]
@kernelpanic01 the receiver of the share cannot rename the share, they are just renaming their local "view" of the share.
1) That sort of renaming needs to be possible in general, e.g. if userA shares folder "stuff" with userB, but userB already has their own folder "stuff" then "the system" has to do something to provide userB with the share, as well as keep userB's own "stuff" folder. Given that that has to be possible, then userB also needs to be able to rename some folder shared with them as "stuff" so that they can make their own local folder"stuff".
2) On the webUI and API it is possible to control these things, but once userB syncs down to some local client e.g. their Windows laptop) then they can rename the folder that was shared with them - the client needs to be able to then do something. There is a general issue with trying to prevent users from renaming things - they will rename anyway on client systems where ownCloud does not have control, and so life is easier if ownCloud minimizes how much it tries to fight that.

**Comment by PVince81** [comment]
- accept/reject/unshare from self for user shares
- for group shares only accept/reject: when rejected, it stays in the list

**Comment by PVince81** [comment]
@felixheidecke can you provide a design with mock up ?

Let us know if you have questions.

We need to think about what columns to display, etc.

**Comment by PVince81** [comment]
@felixheidecke also a few old relevant questions about UX interaction: https://github.com/owncloud/core/pull/24439#issuecomment-217873494

**Comment by felixheidecke** [comment]
This was successfully added to my backlog 👍

**Comment by pmaier1** [comment]
> This was successfully added to my backlog

Backlog? We want to take on this topic in the next iterations of core so we need an idea and design proposal.

**Comment by felixheidecke** [comment]
My personal Backlog :-) So it's on the list of things to do.

**Comment by felixheidecke** [comment]
My idea is to enrich the existing _shared by me_, _shared with me_ sections with this information.
It's just a sketch. Icons and colors are TBD.

![rejected-pending-shares](https://user-images.githubusercontent.com/12717530/33483189-eccc7bf0-d69c-11e7-813a-158bdfc422d5.gif)

**Comment by felixheidecke** [comment]
@pmaier1 is this still of interest?

**Comment by pmaier1** [comment]
> @pmaier1 is this still of interest?

Yes, definitely. This is a prerequisite for plans we have for the next server release.

**Comment by PVince81** [comment]
@felixheidecke and I like your idea of reusing "Shared with you", looks promising.

**Comment by PVince81** [comment]
Summary of discussion with @pmaier1 @felixheidecke:

- implement a mock up and do some usability testing
- for mock up, use https://github.com/owncloud/core/issues/13495#issuecomment-348484906 as base
- only for "Shared with you" section, no change in "Shared with others" for now
- accept/reject action must be inside the row, need to find different approaches
- we agreed to not have accept/reject action in sidebar
- add column header for the state, sort by state by default: pending shares first, accepted shares next, and at the end rejected shares

**Comment by PVince81** [comment]
I'm not sure about the special icons though, they'd only apply for folder shares, not file shares. I'd do away with the icons for now and only keep the state text. Maybe we could change the row background color ?

**Comment by PVince81** [comment]
@felixheidecke I think we don't need this for "Shared with others". Or if we want to display something, we could change the text behind "Shared" to say something like "2 pending, 3 accepted".

I still wonder whether the sharer should really know anything about whether shares were accepted or rejected. If yes, then we might also need to add an indicator for each user in the share panel. And for group shares in the share panel, also display something like "2 accepted, 3 pending" or so.

**Comment by PVince81** [comment]
Also consider that so far a user could never know how many members a group has. Adding numbers would make it possible to reveal this new information to users. Not sure if we could do that.

For now I'd suggest to go with a simpler change and only adjust the "Shared with you", considering that without this part we cannot continue implementing the feature as it will have a UX hole.
The "Shared with others" is more of a nice to have for later.

**Comment by felixheidecke** [comment]
True … I build this on the assumption it was the other way around.

> only for "Shared with you" section, no change in "Shared with others" for now

What a couple of holidays can make me forget things :-|

**Comment by PVince81** [comment]
> forget things

this is why we strive to write everything down in a timely fashion, so no one needs to remember everything and be context-switch safe

**Comment by felixheidecke** [comment]
Well … it was written down … on 20 Dec 2017 :-|

**Comment by PVince81** [comment]
WIP here https://github.com/owncloud/core/pull/30106

**Comment by PVince81** [comment]
Implemented in https://github.com/owncloud/core/pull/30106, backport pending

**Comment by PVince81** [comment]
@jvillafanez please close once the backport https://github.com/owncloud/core/pull/31613 is merged
