### ISSUE TITLE
[User management] Invalid email address keeps in textfield and no alert is shown

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#13503]
### Steps to reproduce

Using an administrator account: 

1. Go to the users view.
2. Activate the checkbox about showing users email addresses.
3. Write anything in the email fields (don't stroke return key).
4. Click out of the textfield.

### Expected behaviour
An alert is shown warning that email address isn't valid and textfield is deleted.

### Actual behaviour
Wrong email address keeps in the textfield, it isn't erased and alert is not shown.

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.0.0.1","versionstring":"8.0 alpha 1","edition":""}

**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
none

**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password and passwordsalt)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** no

### Client configuration
**Browser:**
Chrome, Firefox

![screen shot 2015-01-20 at 12 31 15](https://cloud.githubusercontent.com/assets/9048796/5816425/5a663b78-a0a0-11e4-8b12-a0f5b14aa8ed.png)

**Comment by SergioBertolinSG** [comment]
This merge #13519 has worsen this issue, now many invalid email addreses are accepted and stored in database.
cc @jnfrmarks

**Comment by Sugaroverdose** [comment]
@SergioBertolinSG PR #13519 doesn't changes anything from perspective of this issue. 
This issue was mentioned there only just because discussion context has switched to same problems.
Clearing fileds - not a good way to handle typos.

**Comment by MorrisJobke** [comment]
@SergioBertolinSG The PR doesn't put invalid emails into the database. It is just wrongly shown. But this is another issue of just a temporary wrong info presented. I will have a look at this once I worked on the more critical stuff that is out there.

**Comment by SergioBertolinSG** [comment]
I have to disagree, take a look to the oc_preferences table:
+--------+----------+-----------+------------------------+
| userid | appid    | configkey | configvalue            |
+--------+----------+-----------+------------------------+
| Mendo  | settings | email     | dtoledo@owncloud.com   |
| david  | settings | email     | aaaa@bbb               |
| maria  | core     | timezone  | America/New_York       |
| maria  | login    | lastLogin | 1421942704             |
| maria  | settings | email     | sdasdasdas@dominio.com |
| pipi   | settings | email     | aaaa@bbb               |
| tole   | core     | timezone  | Europe/Berlin          |
| tole   | login    | lastLogin | 1421947096             |
+--------+----------+-----------+------------------------+

**Comment by MorrisJobke** [comment]
Okay. I didn't noticed that. I will have a look.

**Comment by MorrisJobke** [comment]
@DeepDiver1975 I will maybe propose a fix for that and would like it in 8.0 because it seems there is a regression, but I first will test this.

**Comment by Sugaroverdose** [comment]
@MorrisJobke looks like phpmailer always uses 'pcre/pcre8' validation, which not so strict and doesn't requires to have dot in email address. Forcing 'php' validation fixes server-side validation:
lib/private/mail.php line 133:
```php
return PHPMailer::ValidateAddress($emailAddress, 'php');
```

**Comment by MorrisJobke** [comment]
These are all valid email addresses https://en.wikipedia.org/wiki/Email_address#Domain_part (see linked RFC there - there are multiple in the text and also valid email addresses listed)
