### ISSUE TITLE
Amazon S3 external folders not being registered when parent entries are missing

### ISSUE THREAD

**Issue by alappo** [owncloud/core#13507]
### Steps to reproduce
1. Create external storage link to S3 bucket
2. Upload files directly into S3, a couple of directories deep, so that Owncloud has no idea of these 'nested' files
3. Run the files:scan tool on the command line
4. Notice that the immediate sub directories of the bucket are picked up by the scan (they appear in the output), but this does not recursively pass through these folders, searching for more folders within the directory
### Expected behaviour

I understand that amazon has no concept of folders as such, but Owncloud should notice (considering it sends a request to S3 at this point) that there could be folders here, and search within these folders for more folders. It will pick up immediate files, but doesn't register any folders.
### Actual behaviour

The scan tool notices the bucket root folder, and ends the check there, as the file_exists method call (later on in the process), which calls out to filetype($path) fails the check. The bug appears to be down to the use of the following code in apps/files_external/lib/amazons3.php:

``` php
if ($this->getConnection()->doesObjectExist($this->bucket, $path.'/')) {
    return 'dir';
}
```

It looks to me like it will never return true here. From looking at the doesObjectExist method in the AWS SDK, this only works with full object paths, and not a 'directory' key, regardless of whether a slash is added to the end.

Something along the lines of:

``` php
$objectList = $this->getConnection()->listObjects(array('Bucket' => $this->bucket, "Prefix" => $path, "MaxKeys" => 1));
if (!empty($objectList["Contents"])) {
    return 'dir';
}
```

which checks the path for objects, results in the expected behaviour.
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache2

**Database:**
MySql

**PHP version:**
5.6.4

**ownCloud version:** (see ownCloud admin page)
7.0.4 (stable)

**Updated from an older ownCloud or fresh install:**
Fresh Install

**List of activated apps:**
Files, Activity, Documents, Pictures, Calendar, Contacts

**The content of config/config.php:**

``` php
<?php
$CONFIG = array (
  'instanceid' => 'oc3ba9149512',
  'passwordsalt' => '##############################',
  'secret' => '##############################',
  'trusted_domains' =>
      array (
        0 => '[IP ADDRESS]',
      ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://[IP ADDRESS]',
  'dbtype' => 'mysql',
  'version' => '7.0.4.2',
  'dbname' => 'DB_NAME',
  'dbhost' => 'DB_HOST',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'DB_PASSWORD',
  'installed' => true,
  'loglevel' => '0',
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Amazon S3

**Are you using encryption:** yes/no
No
### Client configuration

**Browser:**
Firefox 35.0

**Operating system:**
Windows 7 Professional
#### ownCloud log (data/owncloud.log)

```
Debug   OC\Files\Cache\Scanner  !!! Path '[PATH TO FOLDER WITHIN ACCESSIBLE FOLDER]' is not readable !!!    2015-01-20T11:47:52+00:00 
```

**Comment by PVince81** [comment]
Thanks for the detailed report.

This is a known issue: https://github.com/owncloud/core/issues/11652 (contains a workaround)
And the general issue: https://github.com/owncloud/core/issues/11797

Closing as duplicate.

**Comment by PVince81** [comment]
Okay, I realize that you're running the scan tool already and provided some analysis, sorry.

So it works on the first level but not second level.

**Comment by PVince81** [comment]
@butonic

**Comment by alappo** [comment]
That's correct. It will get files from the sub directory, as they will get the 'file' string returned from the filetype method call. But from what I can see, folders will never get 'dir' when scanning or navigating the folders, as the doesObjectExist method will only work with complete paths i.e. a file.

**Comment by PVince81** [comment]
@DeepDiver1975 something to look into for 8.1
Even though update detection is still inaccurate, we should at least make sure that the workaround (files:scan) works.

**Comment by PVince81** [comment]
@alappo if you have an idea how to fix it, you're welcome to submit ideas and/or a pull request :smile:

**Comment by alappo** [comment]
@PVince81 Of course, but I just wanted to test the waters first and make sure I wasn't missing something :)

**Comment by DeepDiver1975** [comment]
> something to look into for 8.1

indeed - THX ofr triaging

**Comment by helmutschneider** [comment]
Confirmed working on master. S3 structure:
```
[dir]  hello/
[dir]  hello/again/
[file] hello/again/foo.txt
```

Relevant part of scan output:
```
Scanning file   /admin/files/S3/
Scanning folder /admin/files/S3/
Scanning file   /admin/files/S3/hello
Scanning folder /admin/files/S3/hello
Scanning file   /admin/files/S3/hello/hello
Scanning file   /admin/files/S3/hello/again
Scanning folder /admin/files/S3/hello/again
Scanning file   /admin/files/S3/hello/again/again
Scanning file   /admin/files/S3/hello/again/foo.txt
```

**Comment by alappo** [comment]
Thanks for trying that @helmutschneider , I agree it works as you mentioned.

After further investigation I've now got a better idea of why this was an issue for me, so I suppose it depends on how much of an edge case you feel this is in terms a code change being required.

If the files and directories are created in sequence on S3 (as they most likely will be most of the time, e.g. create folder 1, then create folder 2, then upload the file), then run the scan, it will work perfectly as above.

However the problem for me was that the files were uploaded to S3 using the PUT command. This creates the full key to the file on S3, but no keys for the 'sub-directories' which owncloud would pick up on a scan.

 (PUT request) /hello/again/file.txt

When owncloud scans / there is no key explicitly named /hello/ so it will think there is nothing here.

That being said, I wouldn't say this is a bug in Owncloud as such, and more of an implementation issue on my part and down to the way S3 handles file keys, but it would be beneficial if Owncloud was able to pick up on this S3 behaviour.

I'm hoping to look into this at some point and create a pull request, but thought I'd update the issue with my findings :smile:

**Comment by helmutschneider** [comment]
Yes - S3 is weird like that. The GUI interprets / as directory separators but does not create the actual directory objects themselves. Implementing this in OC is kind of tricky since you would need to pattern-match files containing front slashes, extract the non-existent directories and push them into the directory structure. An option would be to only implement it in the scan mechanism and not the actual OC-filesystem... Feel free to look into it :)

**Comment by PVince81** [comment]
Ref: https://github.com/owncloud/core/issues/11797 (getting updates sorted out)

**Comment by PVince81** [comment]
I'd rather consider this an enhancement: make ownCloud able to auto-create parent folders when there are no entries for them in S3. This might require implementing a S3 specific file scanner that works linearly instead of recursively.

As we're past feature freeze, moving to 9.0

**Comment by DeepDiver1975** [comment]
Secondary s3 storage integration just got move over to https://github.com/owncloud/files_external_s3.

Unfortunately GitHub does not allow to move issues. Please reopen the issue at https://github.com/owncloud/files_external_s3/issues
