### ISSUE TITLE
[User Management] Info in textbox Username is deleted when email address is wrong.

### ISSUE THREAD

**Issue by davitol** [owncloud/core#13500]
### Steps to reproduce

1. Go to users
2. Activate send to email address to new users.
3. Write down user/password and a wrong email.
4. Click create new user.

### Expected behaviour
Username  should keep the info due to it was right.

### Actual behaviour

Username textbox is empty after trying to create a new user with a wrong email address.

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.0.0.1","versionstring":"8.0 alpha 1","edition":""}

**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
none

**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password and passwordsalt)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** no
![captura de pantalla 2015-01-20 a las 11 15 32](https://cloud.githubusercontent.com/assets/10596560/5815669/e24856ce-a097-11e4-831d-250be8996be6.png)

### Client configuration
**Browser:**
Chrome, Firefox

![Uploading Captura de pantalla 2015-01-20 a las 11.15.32.png . . .]()

**Comment by rperezb** [comment]
It would be great to have the same behavior than the one when you leave empty the mail field, the error message is shown and the info (id and password) is not deleted.
