### ISSUE TITLE
Previews with aspect ratio need to be properly cached

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#13516]
#### Current situation
Currently, the code in the Preview class contains this in the isCachedBigger() method:
```
// in order to not loose quality we better generate aspect preserving previews from the original file
if ($this->keepAspect) {
	return false;
}
```
and even if this is commented out, the class will never return a cached copy of a preview if the client is asking for a smaller preview which keeps the aspect ratio as the code further down doesn't look for it.

### Why is this a problem?
Let's say you're storing a 25MB TIFF and want to see it full screen via the Gallery app.
The app asks for a 1233x1487 preview and 30 seconds later the cache stores it as 1233-1487-with-aspect.png.
Now resize your screen slightly and ask for a full screen preview again.
You'll have to wait the full 30 seconds again to get a 932-1487-with-aspect.png preview

Multiply this scenario by the number of window configurations which are going to be used to watch a large screen preview and that thumbnail folder is going to get filled with a lot of similar previews and a lot of CPU cycles is going to get wasted.

### Next steps
* [ ] What's the problem with resizing a cached "with-aspect" preview?

If the problem doesn't exist any more
* [ ] Update the cache checking methods

cc @georgehrke @DeepDiver1975

**Comment by georgehrke** [comment]
cc'ing @icewind1991 as he introduced the '-with-aspect' name-scheme for gallery

**Comment by oparoz** [comment]
And is there documentation somewhere regarding some of the design decisions which has been made regarding resizing and caching? For instance, on a few occasions, only `width < maxX` is checked. Is that because previews are expected to be square within OC core?

**Comment by oparoz** [comment]
OK, 2 reasons this is failing are:
* The dimensions of the preview may not match maxX and maxY. So we have a 700x350 preview stored as 1233x1487-with-aspect
* maxX and maxY are based on the window size, so with today's variety of screen dimensions, this leads to many different aspect ratios and comparing them will often fail

**Comment by oparoz** [comment]
I had a look at the process
* This affects both with and without aspect previews
* There are 2 solutions to the window resizing problem:
	* Have size categories, pick the previews from there and let the browser resize previews it gets. That's what the Gallery is doing for thumbnails
	* Force one or two maximum size previews which are used for all resizing requests

**Comment by oparoz** [comment]
I'm marking this as a duplicate of https://github.com/owncloud/core/issues/12465 since solving that problem will make this one less relevant.
The potential fix is in https://github.com/owncloud/core/pull/13582

Having size categories can be another issue and PR.
