### ISSUE TITLE
Encryption password recovery broken

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#13522]
Seems like password recovery is broken in oc7.0.4 maybe also master.

Should happen with LDAP and with the ownCloud user management:

Steps with LDAP:
- user lost password and admin set a new login password in LDAP
- admin tries to revover the users files in the ownCloud user management with the recovery password
-> admin gets error that he can't change the user password

Without LDAP:
- no error message but files not recovered

I will try to reproduce it.

cc @MorrisJobke @cdamken @michaelstingl

**Comment by schiesbn** [comment]
I had a first look at the code.

The pre-hook should be execute no matter if the back-end supports password change or not, see https://github.com/owncloud/core/blob/stable7/lib/private/user/user.php#L171

In the next step we should start here the recovery process in case we can't change the login password. https://github.com/owncloud/core/blob/stable7/apps/files_encryption/hooks/hooks.php#L188

If the login password can be changed we will wait for the post-hook to recover the files to make sure that the password was changed successfully. https://github.com/owncloud/core/blob/stable7/apps/files_encryption/hooks/hooks.php#L188

Hooks are registered here: https://github.com/owncloud/core/blob/stable7/apps/files_encryption/lib/helper.php#L53

That's just from the code point of view, I will try it later to see if something goes wrong while executing this code path

**Comment by michaelstingl** [comment]
@schiesbn Thanks!

00002318
00002409
00002426

**Comment by schiesbn** [comment]
Now I tried it with 7.0.4 but unfortunately couldn't reproduce it. Without LDAP everything works without any error message and with LDAP I get this message at the end "Back-end doesn't support password change, but the user's encryption key was successfully updated." which I think is OK, it describes exactly what happens.

**Comment by MorrisJobke** [comment]
let me check that again.

**Comment by MorrisJobke** [comment]
I tried on master with LDAP and it works with the same message as @schiesbn already noticed.

**Comment by MorrisJobke** [comment]
On master with plain user management it also works and there is no error message.

**Comment by digitali-eu** [comment]
This issue can be closed - i'm very sorry, I wasn't aware of the fact that the recovery option has to be enabled for every individual user too.
