### ISSUE TITLE
Upload > 2G with PHP 5.6

### ISSUE THREAD

**Issue by Akhenaton** [owncloud/core#13529]
The recent PHP 5.6 release comes with important new features : 

Constant scalar expressions.
Variadic functions and argument unpacking using the ... operator.
Exponentiation using the ** operator.
Function and constant importing with the use keyword.
phpdbg as an interactive integrated debugger SAPI.
php://input is now reusable, and $HTTP_RAW_POST_DATA is deprecated.
GMP objects now support operator overloading.
**File uploads larger than 2 gigabytes in size are now accepted.**

See here : http://php.net/releases/5_6_0.php

But i can't set the max file size in my admin panel... Still saying (Max. possible :2 GB)
(my system is upgraded to PHP 5.6.4)

**Comment by Akhenaton** [comment]
Hi karlitschek,
Is there a trick to be able to bypass the 2GB limit in the 7.0.4 ownCloud for now ? :-)

**Comment by karlitschek** [comment]
There a few tricks mentioned in the documentation yes.

**Comment by Akhenaton** [comment]
O.K. Thanks ! Will see the docs....
Regards,

**Comment by RealRancor** [comment]
See also: http://forum.owncloud.org/viewtopic.php?f=17&t=7733

> But i can't set the max file size in my admin panel...

Especially the part "Setting the maximum upload size in the Webinterface"

> Is there a trick to be able to bypass the 2GB limit in the 7.0.4 ownCloud for now ? :-)

Thats not a limit of ownCloud itself but of PHP on 32bit and windows systems (32bit and 64bit).

**Comment by PVince81** [comment]
Closing due to lack of feedback.

If you're still having this upload with 8.1.3 or 8.2.0, feel free to reopen.
