### ISSUE TITLE
Add icons for video viewer and external user support

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#13524]
Both the video viewer and the external user support apps are missing icons.  They should be added for 8.0

**Comment by PVince81** [comment]
@owncloud/designers

**Comment by jancborchardt** [comment]
Where are the repositories of these apps? I couldn’t find them. If you let me know where they are, I can add the icons.

**Comment by jancborchardt** [comment]
cc @DeepDiver1975

**Comment by MorrisJobke** [comment]
@jancborchardt https://github.com/owncloud/videos <- I guess that is the video app

**Comment by MorrisJobke** [comment]
https://github.com/owncloud/apps/tree/master/user_external <- user external

**Comment by jancborchardt** [comment]
No, that has an icon.

**Comment by MorrisJobke** [comment]
@jancborchardt But it has the wrong name `video.svg` instead of `app.svg` ;)

**Comment by DeepDiver1975** [comment]
> But it has the wrong name video.svg instead of app.svg ;)

videos.svg would be valid as well

**Comment by jancborchardt** [comment]
So … I can’t reproduce nor fix it without knowing where the repos are. Does anyone know where the repositories are?

**Comment by jancborchardt** [comment]
@karlitschek you also reported this but I could not find the video viewer repository anywhere. Can you point me to it?

**Comment by karlitschek** [comment]
it´s here: https://github.com/owncloud/apps

**Comment by jancborchardt** [comment]
Fix at https://github.com/owncloud/apps/pull/2022

**Comment by MorrisJobke** [comment]
@karlitschek Should we backport these icons to stable8?

**Comment by karlitschek** [comment]
please backport

**Comment by MorrisJobke** [comment]
will be in 8.0.1
