### ISSUE TITLE
Auto-umount / ignore / blacklist broken storages

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13531]
With server to server sharing and other external storages, it can happen that a storage becomes unavailable for various reason. (ex: no route to host, host is down, etc).

Instead of trying to connect there and wait until timeout, OC should blacklist broken storages for a given time and try again later instead of trying for every PHP request.

Because trying every time can slow down significantly when accessing the folder where the mount point is in.

@icewind1991 @Xenopathic

**Comment by Xenopathic** [comment]
I've already got some ideas on how to do this. I'll have a look at an implementation tomorrow.
