### ISSUE TITLE
File cannot be reshared with a user if the user hasn't acknowledged the original request

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#13534]
### Steps to reproduce

1. Install master on two boxes
2. log in as a user on box 2, navigate to the personal page and stay on that page
3. on box one, share a file with a user on box 2
4. on box one, unshare the file
5. on box one, share the same file again with the user on box 2

### Expected behaviour

Box one can still share with user on box two

### Actual behaviour

Box one cannot share the file.
This is because the original share accept has not been acknowledged

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration

ownCloud 8.0 beta 1 (daily) Build:2015-01-20T04:14:11+00:00

**Comment by PVince81** [comment]
@schiesbn

**Comment by jnfrmarks** [comment]
This seems resolved in 8.1; closing
