### ISSUE TITLE
Use PUT for an update of an entity - files tags API

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#13536]
https://github.com/owncloud/core/blob/84bb4cc2e9013eb3db8d7114a0e6eb132a723adf/apps/files/appinfo/routes.php#L23

cc @PVince81 @DeepDiver1975

**Comment by PVince81** [comment]
PROPPATCH is the future

**Comment by PVince81** [comment]
also we're not putting a file (which is what the url points to) but changing a file's attribute. So POST for change, not PUT.

**Comment by DeepDiver1975** [comment]
@PVince81 as we are talking about a RESTful api - POST is for creating a new entity and PUT is for updating an entity - unlike WebDAV where POST is not used at all and PUT for create and update

**Comment by DeepDiver1975** [comment]
anyway - this is topic of discussion on how to continue with our API melting pot ....

**Comment by PVince81** [comment]
Would PUT require the whole entity to be re-sent by convention ? We don't want to resend the file here to just change attributes. I remember asking @Raydiation and he advised for POST in this situation, probably because of that "resend file" element.

Anyway, a discussion for later.

**Comment by Raydiation** [comment]
PUT requires to resend everything. Either go for POST or PATCH

**Comment by DeepDiver1975** [comment]
Indeed partial updates are implemented using PATCH - questionable is then is these meta data of files might be modelled as it's own resource where a PUT can update the all meta data.

But - yeah - I finally understand the reasoning behind using POST here -> case closed - THX
