### ISSUE TITLE
Cache remote users so they show up in user selection when sharing

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#13532]
When sharing a file with a remote user, I have to type in user@http://<remotesystem>/owncloud.  

If I make a mistake, I have to type that all in again.

If I want to share a second, third, forth file, I have to type that all in again.

It would be really great if there was a way to cache the users somehow so that they can be selected from a drop down list.

![p242](https://cloud.githubusercontent.com/assets/8480343/5825777/f8799d3a-a0bb-11e4-98e7-641af180e3a4.PNG)

**Comment by PVince81** [comment]
@nickvergessen looks like you were right, see sharing format :wink: 
Ref #13678

**Comment by PVince81** [comment]
Defer to 9.0 ? Not sure if this was on the plan

@nickvergessen @cmonteroluque @MTRichards

**Comment by MTRichards** [comment]
9.0 is fine from my perspective, as it is not a blue ticket.

**Comment by PVince81** [comment]
I think there was also a talk about automatically adding the users to the address book or some internal list, it would also fit with this ticket @schiesbn

**Comment by karlitschek** [comment]
Yes. Something for 9.0

**Comment by cmonteroluque** [comment]
nod

**Comment by PVince81** [comment]
@schiesbn will this be obsoleted by federation autocomplete ?

**Comment by LukasReschke** [comment]
Yes

**Comment by nickvergessen** [comment]
Not really, but the actual bug was fixed with https://github.com/owncloud/core/pull/22452
