### ISSUE TITLE
Feature request: Add personal text on sharing emails

### ISSUE THREAD

**Issue by novij** [owncloud/core#13549]
Is it possible to add a text box on link sharing for a personal comment which is added in the mail to the recipient?

**Comment by DeepDiver1975** [comment]
we had this request already in the past - @jancborchardt what was our approach here? THX

**Comment by DeepDiver1975** [comment]
most probably duplicate ....

**Comment by jancborchardt** [comment]
Duplicate of https://github.com/owncloud/core/issues/9940, let’s continue there.
