### ISSUE TITLE
Install wizard - no predefined database/user possible (postgresql)

### ISSUE THREAD

**Issue by Jas2Ma** [owncloud/core#13541]
I am referring to http://doc.owncloud.org/server/7.0/admin_manual/installation/installation_wizard.html.

I tried to use Docker postgres image as db for owncloud. But since owncloud Installation Wizzard does create it's own db user, this is not possible without adjusting pg_hba.conf.
The error massage Installation Wizzard is giving back is very poor (wronge login credentials).

This is what I think is happening: Owncloud is using the given credentials to create new user + db, then trying to log in as new user. This is forbidden by pg_hba.conf, so I get the error message, that my credentials are wrong (which they are not, new user and db are created, but new user is not allowed to login from different ip than localhost) and being told to give the right ones (still on Installation Wizzard start page).

In Owncloud 6.0 it was allowed to create an db and give the Installation Wizzard the right credentials, so it would use them instead of creating them on it's own.

In Owncloud 7 this is no longer possible - so I would have to adjust pg_hba.conf to new OC user to run Installation Wizzard.

**Comment by DeepDiver1975** [comment]
@rperezb can we have some qa power on this please? something for the testplan from my pov

**Comment by rperezb** [comment]
@SergioBertolinSG can you please check this one, thx

**Comment by SergioBertolinSG** [comment]
I think I am not getting the problem. 

When setting up oc first you should set up database, it is documented here https://doc.owncloud.org/server/7.0/admin_manual/configuration/database_configuration.html#postgresql-database

So I think you should change the dockerfile or use some environment variables to making it able for being used.

**Comment by Jas2Ma** [comment]
@SergioBertolinSG Well, all this happened to me some time ago and I am now using mariadb, so I am not affected by this problem anymore.

But the point was: I have valid credentials for the database owncloud can use and is using. But instead using them all over, in the configuration of the new owncloud server instance, it is using them (credentials c1, which do work), to create an other set of credentials (c2) which are not working, because they are only working for localhost, without further configuration in pg_hba.conf.

Does this explanation clarify the (from my point of view) user unfriendly behaviour?

**Comment by Jas2Ma** [comment]
@SergioBertolinSG And one can not simply turn the credentials back to c1 in owncloud config file, because owncloud created database "owncloud" with permissions of c2, so one has to change the permissions of database "owncloud" to c1, too.
