### ISSUE TITLE
Do not log auth error in publicwebdav for initial auth call

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13545]
### Steps to reproduce:
1. Mount a remote share from server to server sharing
2. As the receiving user, open the files app
3. Open the chrome console, copy the `getstoragestats.php` with curl
4. Close all ownCloud related windows (to avoid background calls)
5. Run the curl command
6. Observe the target server log

### Expected result
No error in log

### Actual result
Log is full with:
```
ic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Plugin.php(108): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#1 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod('PROPFIND', '')\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(433): call_user_func_array(Array, Array)\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(455): Sabre\\\\DAV\\\\Server->broadcastEvent('beforeMethod', Array)\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('PROPFIND', '')\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_sharing\\\/publicwebdav.php(78): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/public.php(48): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#7 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":73}","level":0,"time":"2015-01-21T12:16:08+00:00","method":"PROPFIND","url":"\/owncloud\/public.php\/webdav\/"}
```

When debugging I noticed that when doing a single Sabre Client call, curl (the one used by Sabre) would first do a non-authenticated call to "publicwebdav.php" which triggers the message and returns 401. After that, curl would send a second request with the auth info.

According to @LukasReschke this is the expected protocol.

So if this is expected, we need to find a way to prevent that error to be logged during the first "handshake" request to avoid polluting the logs and making people believe that something is wrong.

**Comment by PVince81** [comment]
CC @icewind1991

**Comment by LukasReschke** [comment]
> According to @LukasReschke this is the expected protocol.

My assumption here is that curl is trying to get the nonce in case the server uses digest access authentication.
