### ISSUE TITLE
Upgrading from 7.0.4 to 8.0.1 results missing/broken apps

### ISSUE THREAD

**Issue by myymi** [owncloud/core#13543]
Here's how to reproduce:
1) backed up my installation's directory (mv owncloud owncloud_bak), 
2) untarred beta 8.0.1, 
3) chowned new installation to web server's rights (chown httpd:httpd owncloud), 
4) copied original conf file and 3rd party apps to the new installation (cp owncloud_bak/config/config.php owncloud/config/config.php)
5) started the instance's webpage and let the upgrade run, no errors.
6) checked for the previously activated/installed apps, 3rd party apps are missing in the web console's Apps section, none of the apps on the "Recommended" section can be activated, resulting  "application does not offer any info.xml file" error. Most of the others result in "this app contains disallowed code"

Expected behaviour:
Listed apps activate without errors, 3rd party apps in apps/ folder show up in apps list.

system:
Fedora release 19 (Schrödinger’s Cat), kernel 3.14.27-100.fc19.x86_64
Server version: Apache/2.4.10 (Fedora)
PHP 5.5.20
mysql  Ver 15.1 Distrib 5.5.39-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by DeepDiver1975** [comment]
> checked for the previously activated/installed apps, 3rd party apps are missing in the web console's Apps section, none of the apps on the "Recommended" section can be activated,

The app store does not yet hold that much apps which have been enabled for OC8 - this will happen within the next days/weeks from my understanding.



> resulting "application does not offer any info.xml file" error.

This is popping up because of we have some placeholders for apps which will be uploaded the next days/weeks



> Most of the others result in "this app contains disallowed code"

Many apps still are not compliant according to our coding guidelines and therefore are by now rejected to be installed.

**Comment by DeepDiver1975** [comment]
@karlitschek FYI - regarding appstore - THX

@jnfrmarks feedback on some upgrade testing - FYI

**Comment by PVince81** [comment]
It was reported on the mailing list that this is still happening in 8.0 beta2: https://mailman.owncloud.org/pipermail/testpilots/2015-January/000260.html

**Comment by JSoko** [comment]
Had the same issue here with beta1 and beta2 under Ubuntu.

Fixed that issue as follows:

Before upgrading I deactivated not only the 3rd-party apps but also the calendar and the contacts app in OC 7.04

I did the upgrade with these steps:
1.
rename the old /var/www/owncloud folder to /oc704
2.
move the beta 2 to /var/www/owncloud
3.
moved the calender and contact folder from the github
https://github.com/owncloud/calendar/releases
into the apps folder
4.
sudo chown -R www-data:www-data /var/www/owncloud
5.
sudo /etc/init.d/apache2 restart && /etc/init.d/mysql restart
6.
Started the Owncloud Update in the browser
7.
activated calendar and contacts under apps/not activated

Now caldav and carddav are working like they should...
:-))

Now I copied the beta 2 releases from calender onde contact into the apps folder before starting the update fixes the issue

**Comment by DeepDiver1975** [comment]
@myymi @JSoko beta versions of previously shipped apps have been uploaded to the appstore. Can I ask you to retest the installation of e.g. calendar and contacts? THX a lot

**Comment by JSoko** [comment]
Hello can't install calendar 8 or contacts 8
Error	core	Die Applikation kann auf Grund von unerlaubten Code nicht installiert werden	2015-01-28T16:41:35+00:00
Error	core	App "calendar" is using a not allowed call "OC_App::". Installation refused.

Could this have something to do with the codechecker?:
https://github.com/owncloud/core/issues/11065

**Comment by karlitschek** [comment]
Not sure which version you are using. There is not 8.0.1 beta
Do you mean 8.0.0 beta 1 or 2?
The mentioned error is fixed in the meantime and will be released in the next beta. You can also check the nightly build if you want.
Thanks a lot for reporting.

**Comment by JSoko** [comment]
Helo Frank,

the threadopener wrote about 8.01 beta.

I've had this Issue with 8.0 alpha 1, alpha 2, beta 1 and beta2
Actually I tested with beta 2.

As I wrote yesterday calendar and contacts are working witth the app from github
https://github.com/owncloud/calendar/releases

Ciao,
Joachim

**Comment by karlitschek** [comment]
Great. Good to hear :-)

**Comment by DeepDiver1975** [comment]
> Could this have something to do with the codechecker?:
> #11065

to clarify the app code checker is disabled in oc8 since yesterday (https://github.com/owncloud/core/pull/13701) and even beta 2 does not contain the necessary changes. 

For testing the appcodechecker can be disabled in the config by setting 'appcodechecker' to false.

After this change apps should be installable from the appstore.

Sorry for not being precise enough about my request to retest this issue - THX

**Comment by myymi** [comment]
Hi!

Sure, here are the results:

Documents 8.0 fails still with error   inode/x-empty type archives are 
not supported

Others activate nicely after adding 'appcodechecker' => false, to the 
config.php, but give me non-funcional apps on the menu, showing some 
elements, but scramble everything up. Also, some elements keep on 
loading endlessly.
Screenshot of the Contacts (sry, my installation is in Estonian, but You 
should get the point)
https://owncloud.sudo.ee/index.php/s/rMEidt2l4M2b3JL
Strangely, one 3rd party app I have been using, Notes 0.9 by Bernhard 
Posselt, Jan-Christoph Borchardt(https://github.com/owncloud/notes/)
runs really nice, no problems whatsoever.

This screenshot is taken on and shared from the very same system, 
everything else apart from most of the apps is running great! Upgrading 
has been breeze, nice job!



28/01/15 18:20, Thomas Müller kirjutas:

**Comment by karlitschek** [comment]
Can you try again? There was a filesize problem on the server side.

**Comment by myymi** [comment]
Should I try to re-enable apps? Because re-enabling leads to error " 
directory already exists", although I have the apps disabled.
28/01/15 22:48, Frank Karlitschek kirjutas:

**Comment by arusa** [comment]
I just upgraded owncloud with the updater app and now I only get an empty page when I access my installation with my webbrowser.

The logs are showing:

PHP Fatal error:  Class OCA\\Contacts\\Share\\Addressbook contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCP\\Share_Backend::isShareTypeAllowed) in /var/www/owncloud/apps/contacts/lib/share/addressbook.php on line 130

I will try to upgrade the Addressbook App now using the github version, but this should be done by the Updater App - or at least it should warn me...

**Comment by russianryebread** [comment]
I am getting the error as well after using the `occ update` command.  Just upgraded on Ubuntu 14.04 from OC 7.0.4 to OC 8.0.2:


```
[Mon Apr 06 22:42:41.919244 2015] [:error] [pid 1761] [client x.x.x.x:19494] PHP Fatal error:  Class OCA\\Contacts\\Share\\Addressbook contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCP\\Share_Backend::isShareTypeAllowed) in /var/www/owncloud/apps/contacts/lib/share/addressbook.php on line 130, referer: https://example.net/index.php
[Mon Apr 06 22:42:41.924350 2015] [:error] [pid 1761] [client 71.87.6.5:19494] {"reqId":"c8df22ebc2f9b3769dfc44bc870aa4de","remoteAddr":"x.x.x.x","app":"PHP","message":"Class OCA\\\\Contacts\\\\Share\\\\Addressbook contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCP\\\\Share_Backend::isShareTypeAllowed) at \\/var\\/www\\/owncloud\\/apps\\/contacts\\/lib\\/share\\/addressbook.php#130","level":3,"time":"2015-04-07T03:42:41+00:00","method":"GET","url":"\\/index.php\\/apps\\/files\\/"}, referer: https://example.net/index.php
```

**Comment by maces** [comment]
Same Problem here. Folowing @arusa s advice, I did the following: 
- disabling 'contacts' and 'calendar' in the DB table 'oc_appconfig'
- moving the directorys 'contacts' and 'calendar's from '/apps' to some temporarily location.
- downloading the stable8 branches of these apps from github
- uploading them
- enable them via webinterface

After doing the same with the tasks app I have been redirected to the web updater again and did the update to 8.0.2 (again?). After that my owncloud instance appears to be working again.

**Comment by djtm** [comment]
I'm still getting the disallowed code even for all owncloud apps such as calendar, I had to disable the config setting to check the code to make it work: 
`` //  'appcodechecker' => true, ``
