### ISSUE TITLE
  [User Management] Modified template for new email user is not sent. 

### ISSUE THREAD

**Issue by davitol** [owncloud/core#13547]
### Steps to reproduce

1. Go to administration
2. Edit "new email address user" template and save it
3. Go to users
2. Activate send to email address to new users.
3. Write down user/password and email.
4. Click create new user.

### Expected behaviour
An email should be received by the user according to the edited template

### Actual behaviour

The email received contains the text of the predetermined template

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.0.0.1","versionstring":"8.0 alpha 1","edition":""}

**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
none

**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password and passwordsalt)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** no

### Client configuration
**Browser:**
Firefox

![captura de pantalla 2015-01-21 a las 13 42 11](https://cloud.githubusercontent.com/assets/10596560/5836286/b07d6486-a173-11e4-84a2-981f45043d30.png)

**Comment by DeepDiver1975** [comment]
template editor related ? @butonic 
user management related? @LukasReschke @MorrisJobke 

THX

**Comment by LukasReschke** [comment]
Was the HTML template also edited?

**Comment by davitol** [comment]
Was the HTML template also edited? @LukasReschke

**Comment by LukasReschke** [comment]
There is a file that contains the HTML template and one the plain-text version. From your screenshot it looks like you edited only the one containing the plain-text version.

Mail programs will display whatever works for them, so if HTML is supported they display that. If it doesn't they display the plain-text version.

**Comment by davitol** [comment]
Thank you for the info and the reply.

**Comment by MorrisJobke** [comment]
@davitol So this is not a issue? Can this be closed?
