### ISSUE TITLE
Full editable calendars in user group even though calendars are marked as not shareable and not editable (only in Version 7.0.4)

### ISSUE THREAD

**Issue by JeTim** [owncloud/core#13544]
Describtion: First I have generate 2 users A, B which join the user group xy. A and B have next to their default calender (in german: "Persönlich") a second calender, user A, calender A and user B, calender B. These both calenders are shared with the group xy whith the options "not shareable" and "not editable". Until here it works fine. If I log in as A or B I can see calendar of the other groub member but cannot edit it. But if I generate a third user C in the group xy the group permissions becomes crazy, if I log in now as A,B or C I can edit, delete, create appointments in calendars at least of one of the other  group members!!
In a second installation of owncloud (Version 7.0.2) I performed the test with 5 users in one group and it worked fine. The users of the group can see the calendars of the other members but do not have full access.
For both owncloud installations I use the same admin settings. Could it be a bug in 7.0.4 ?

![2 users](https://cloud.githubusercontent.com/assets/10629443/5835950/d4f7aace-a16e-11e4-8c46-a11dfc6047e1.JPG)
![3 users](https://cloud.githubusercontent.com/assets/10629443/5835948/d4e675c4-a16e-11e4-9f02-5c123f1480b2.JPG)
![users](https://cloud.githubusercontent.com/assets/10629443/5835949/d4e800e2-a16e-11e4-8ef7-3c38105e937e.JPG)

**Comment by MorrisJobke** [comment]
@JeTim Thanks for the report. Can I ask you to reopen this in the calendar bug tracker https://github.com/owncloud/calendar/issues Thanks.

**Comment by JeTim** [comment]
Thanks, I will do so!

**Comment by cedric-dufour** [comment]
It's not only the Calendar that is affected.

Same issues with files!

Looking at what happens in the database when sharing an object (table oc_share):
1. When "Share" is clicked (GUI), the parent (group) and children (users) objects are created, by default with edit permissions (DB).
2. When edit permissions are unchecked (GUI) from the group, only the parent (group) object is updated (DB); all children (users) objects remain with the original (edit) permissions.

Same happens with calendar (GUI <-> DB).

I think this is a very critical security issue!
