### ISSUE TITLE
Warning in user management before password change by admin

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#13542]
* add a warning before the admin changes the password of a user in the user management if recovery is disabled because it implies data loss if the user doesn't know the old password

cc @michaelstingl

**Comment by MorrisJobke** [comment]
encryption needs to be enabled ;)

**Comment by michaelstingl** [comment]
@MorrisJobke thanks!

00002318

**Comment by DeepDiver1975** [comment]
data loss -> showstopper

**Comment by nickvergessen** [comment]
Well a warning doesn't really help here?
One would assume, an admin only changes the password when requested.
And if not, the user should still have the old password.

**Comment by MorrisJobke** [comment]
And here it is: #13542
