### ISSUE TITLE
Delete file on non-local storage does not properly delete file

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13557]
### Steps to reproduce
1. Mount a remote share through server to server sharing
2. Run cadaver for the receiving user
3. `cd remoteshare`
4. `put test.txt` (upload a file)
5. `rm test.txt`
6. `ls`

### Expected result
File is deleted

### Actual result
Even though the deletion call succeeded, the file is still there.

### Versions
OC 8 master ff5715779c56ceacc870307bf25f4e769ff22a1a

I'll have a look.

**Comment by PVince81** [comment]
Works properly with external storage mounts, so the problem is only for server to server shares.

**Comment by PVince81** [comment]
Nope, wrong. The file is never deleted from external storage, but the web UI / WebDAV says it's gone because it's removed from cache.

Issue is in trashbin wrapper.

**Comment by PVince81** [comment]
Also affects local shares.
Even though the file looks like it's gone, it still exists in the data dir of the owner.

It seems that the trashbin wrapper should forward the unlink() call to the underlying storage after doing move2trash.

**Comment by DeepDiver1975** [comment]
> It seems that the trashbin wrapper should forward the unlink() call to the underlying storage after doing move2trash.

should not be necessary with the cross storage move pr - right?

**Comment by PVince81** [comment]
The cross storage move PR would still need to do a stream copy + final delete for remote shares or external storage. So that PR would not fix it completely.

Fix is here: https://github.com/owncloud/core/pull/13561

**Comment by PVince81** [comment]
@DeepDiver1975 see here https://github.com/owncloud/core/pull/13561#issuecomment-70858493 where I referenced it

**Comment by PVince81** [comment]
For reference: trashbin wrapper PR that introduced the issue: https://github.com/owncloud/core/pull/13377
