### ISSUE TITLE
The "Download logfile" button overlays the log file text being displayed

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#13558]
### Steps to reproduce

1. Install master 
2. Navigate to the admin page 
3. Scroll down to the "log" section

### Expected behaviour

The "Download logfile" button is properly places

### Actual behaviour

The "Download logfile" button overlays the log file text being displayed

(Should the text be "Download Log File"?)

![p243](https://cloud.githubusercontent.com/assets/8480343/5838390/28b3e2be-a155-11e4-8f55-0c35f89bdb8f.PNG)

### Browser

Chrome
Firefox

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration

ownCloud Enterprise Edition 8.0 beta 1 (daily) Build:2015-01-21T04:13:37+00:00

**Comment by DeepDiver1975** [comment]
@jancborchardt @georgehrke please have a look - THX

**Comment by MorrisJobke** [comment]
@DeepDiver1975 I'm already on it ;)

**Comment by MorrisJobke** [comment]
fix is in #13559
