### ISSUE TITLE
WinClient and status.php

### ISSUE THREAD

**Issue by Mumba85** [owncloud/core#13567]
Hi,
i just installed owncloud on my BananaPi, and it works fine via browser (with https).
I used the repository to install owncloud, apache,phpmyadmin and my data is on a external storage (USB harddisk).

However, when i try to use the windows client i get the following error:
Failed to connect to ownCloud at https://..../status.php:
Error downloading https://.../status.php - server replied: Service Unavailable

I have googled this but there was no solution which would work for.
I hope you can help me, because i dont even know where to start.

Thanks alot,
Markus

**Comment by MorrisJobke** [comment]
@Mumba85 Please open https://.../status.php in you browser. It should look like this:

```
{"installed":true,"maintenance":false,"version":"8.0.0.3","versionstring":"8.0 beta 1","edition":""}
```

Please also provide the content of owncloud.log (based in your data directory) and maybe relevant entries of your apache error log (usually somewher in `/var/log/apache/...`)

**Comment by MorrisJobke** [comment]
The best would be if you could fill out https://github.com/owncloud/core/blob/master/issue_template.md ;)

**Comment by Mumba85** [comment]
Ok Thanks i will do this:
Server - Version: all newly installed
owncloud: 7.0.4, fresh installed

status.php gives this:
{"installed":"true","version":"7.0.4.2","versionstring":"7.0.4","edition":""}

owncloud.log:
{"app":"PHP","message":"fopen(\/var\/www\/owncloud\/config\/config.php): failed to open stream:
No such file or directory at \/var\/www\/owncloud\/lib\/private\/config.php#141","level":3,"time":
"2015-01-21T14:58:07+00:00"}

apache2 error.log:
[Wed Jan 21 15:56:26 2015] [error] [client 192.168.0.101] File does not exist: /var/www/phpmyadmin
[Wed Jan 21 15:56:28 2015] [error] [client 192.168.0.101] File does not exist: /var/www/phpmyadmin
[Wed Jan 21 15:56:29 2015] [error] [client 192.168.0.101] File does not exist: /var/www/phpmyadmin
[Wed Jan 21 15:56:29 2015] [error] [client 192.168.0.101] File does not exist: /var/www/phpmyadmin
[Wed Jan 21 15:56:29 2015] [error] [client 192.168.0.101] File does not exist: /var/www/phpmyadmin
[Wed Jan 21 15:56:29 2015] [error] [client 192.168.0.101] File does not exist: /var/www/phpmyadmin
[Wed Jan 21 15:56:42 2015] [error] [client 192.168.0.101] File does not exist: /var/www/phpmyadmin
[Wed Jan 21 15:57:54 2015] [error] [client 192.168.0.101] File does not exist: /var/www/phpmyadmin
[Wed Jan 21 15:58:07 2015] [error] [client 192.168.0.104] client denied by server configuration: /var/www/owncloud$
[Wed Jan 21 15:58:08 2015] [error] [client 192.168.0.104] client denied by server configuration: /var/www/owncloud$
[Wed Jan 21 15:58:21 2015] [error] [client 192.168.0.104] client denied by server configuration: /var/www/owncloud$
[Wed Jan 21 15:58:22 2015] [error] [client 192.168.0.104] client denied by server configuration: /var/www/owncloud$
[Wed Jan 21 15:58:33 2015] [error] [client 192.168.0.101] File does not exist: /var/www/phpmyadmin
[Wed Jan 21 15:58:48 2015] [error] [client 192.168.0.101] File does not exist: /var/www/phpmyadmin
[Wed Jan 21 15:59:16 2015] [error] [client 192.168.0.101] File does not exist: /var/www/admin
[Wed Jan 21 16:02:21 2015] [notice] caught SIGTERM, shutting down
[Wed Jan 21 16:02:23 2015] [warn] RSA server certificate CommonName (CN) `markusnoip.ddns.net' does NOT match serv$
[Wed Jan 21 16:02:24 2015] [warn] RSA server certificate CommonName (CN) `markusnoip.ddns.net' does NOT match serv$
[Wed Jan 21 16:02:24 2015] [notice] Apache/2.2.22 (Debian) PHP/5.4.36-0+deb7u3 mod_ssl/2.2.22 OpenSSL/1.0.1e confi$
[Wed Jan 21 16:04:40 2015] [error] [client 192.168.0.104] client denied by server configuration: /var/www/owncloud$
[Wed Jan 21 16:04:41 2015] [error] [client 192.168.0.104] client denied by server configuration: /var/www/owncloud$
[Wed Jan 21 16:06:08 2015] [error] [client 192.168.0.104] client denied by server configuration: /var/www/owncloud$
[Wed Jan 21 16:06:09 2015] [error] [client 192.168.0.104] client denied by server configuration: /var/www/owncloud$
[Wed Jan 21 16:07:09 2015] [error] [client 192.168.0.104] client denied by server configuration: /var/www/owncloud$
[Wed Jan 21 16:07:15 2015] [error] [client 192.168.0.104] client denied by server configuration: /var/www/owncloud$
[Wed Jan 21 16:09:18 2015] [error] [client 192.168.0.104] client denied by server configuration: /var/www/owncloud$
[Wed Jan 21 16:09:19 2015] [error] [client 192.168.0.104] client denied by server configuration: /var/www/owncloud$
[Wed Jan 21 16:11:54 2015] [error] [client 192.168.0.104] client denied by server configuration: /var/www/owncloud$
[Wed Jan 21 16:17:12 2015] [error] [client 192.168.0.104] client denied by server configuration: /var/www/owncloud$
[Wed Jan 21 16:17:47 2015] [error] [client 192.168.0.104] client denied by server configuration: /var/www/owncloud$
[Wed Jan 21 16:25:01 2015] [error] [client 192.168.0.101] File does not exist: /var/www/owncloud/owncloud
[Wed Jan 21 16:25:01 2015] [error] [client 192.168.0.101] File does not exist: /var/www/owncloud/owncloud
[Wed Jan 21 17:29:12 2015] [error] [client 192.168.0.101] File does not exist: /var/www/favicon.ico
[Wed Jan 21 17:34:22 2015] [error] [client 192.168.0.101] Invalid method in request \x80=\x01\x03\x01
[Wed Jan 21 17:43:20 2015] [error] [client 192.168.0.104] client denied by server configuration: /var/www/owncloud$

config.php;
<?php
$CONFIG = array (
  'instanceid' => 'oc741e5075f0',
  'passwordsalt' => '*********',
  'secret' => '*********',
  'trusted_domains' =>
  array (
    0 => 'markusbpi',
  ),
  'datadirectory' => '/media/bpidisk/owncloud',
  'overwrite.cli.url' => 'http://markusbpi/owncloud',
  'dbtype' => 'mysql',
  'version' => '7.0.4.2',
  'dbname' => 'owncloud7',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_root',
  'dbpassword' => '******',
  'installed' => true,
);


extneral storage: mounted harddisk, no encryption


I hope this helps :)

**Comment by Mumba85** [comment]
i just realized sth strange, when i use
https://markusbpi/owncloud/status.php
it works, but
https://192.168.0.4/owncloud/status.php
doesnt work?!

**Comment by Mumba85** [comment]
when i use the hostname to run the status.php i get the message above, but when i use the internal IP address of the bananapi, i get a message that should change the right to 0770 because other users have access to the data folder too

**Comment by RealRancor** [comment]
Hi,

i think this could be related to: https://github.com/owncloud/documentation/issues/731

**Comment by Mumba85** [comment]
you mean ishould set
chown www-data:www-data /var/www/owncloud/config/   ?

that doesnt work

**Comment by Mumba85** [comment]
wenn ich apcche starte kommt immer:
Reloading web server config: apache2apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.0.104 for ServerName

**Comment by MorrisJobke** [comment]
This is related to the data folder
```
chown www-data:www-data /var/www/owncloud/data/ 
chmod 770 /var/www/owncloud/data/ 
```
Can you try this? Thanks

**Comment by Mumba85** [comment]
I tried, but it didnt change anything. I still get the same Error :(

**Comment by MorrisJobke** [comment]
Can you do a `ls -la` in the owncloud folder? (where the status.php and index.php is located)

**Comment by Mumba85** [comment]
drwxr-xr-x  13 root     root      4096 Jan 21 17:03 ./
drwxr-xr-x   3 root     root      4096 Jan 21 15:34 ../
drwxr-xr-x  27 root     root      4096 Jan 21 15:34 3rdparty/
drwxr-xr-x  26 www-data www-data  4096 Jan 21 15:34 apps/
drwxr-xr-x   2 www-data www-data  4096 Jan 21 15:58 config/
-rw-r--r--   1 root     root      1283 Dec  8 19:32 console.php
drwxr-xr-x  16 root     root      4096 Jan 21 15:34 core/
-rw-r--r--   1 root     root      3929 Dec  8 19:34 cron.php
drwxrwx---   2 www-data www-data  4096 Jan 21 17:45 data/
-rw-r--r--   1 root     root     23751 Dec  8 19:32 db_structure.xml
-rw-r--r--   1 root     root      1292 Jan 21 15:37 .htaccess
-rw-r--r--   1 root     root       179 Dec  8 19:32 index.html
-rw-r--r--   1 root     root      1281 Dec  8 19:34 index.php
-rw-r--r--   1 root     root      2595 Dec  8 19:32 indie.json
drwxr-xr-x 123 root     root      4096 Jan 21 15:34 l10n/
drwxr-xr-x   6 root     root      4096 Jan 21 15:34 lib/
-rw-r--r--   1 root     root       279 Dec  8 19:34 occ
drwxr-xr-x   2 root     root      4096 Jan 21 15:34 ocs/
-rw-r--r--   1 root     root      1753 Dec  8 19:34 public.php
-rw-r--r--   1 root     root      1735 Dec  8 19:34 remote.php
-rw-r--r--   1 root     root        26 Jan 21 12:47 robots.txt
drwxr-xr-x   6 root     root      4096 Jan 21 15:33 search/
drwxr-xr-x  11 root     root      4096 Jan 21 15:34 settings/
-rw-r--r--   1 root     root      1406 Dec  8 19:34 status.php
drwxr-xr-x   2 root     root      4096 Jan 21 15:34 themes/
-rw-r--r--   1 root     root       149 Dec  8 19:35 version.php

**Comment by MorrisJobke** [comment]
All the logs look fine. Also this listing look fine, but you still get this warning: "i get a message that should change the right to 0770 because other users have access to the data folder too"? What do you see if you go to http://markusbpi/owncloud/ ? You should have the login page there.Am I wrong?

**Comment by Mumba85** [comment]
hmm that is strange......now this message comes too. so before i got a login page when i opened
http://markusbpi/owncloud/, and the error message came only when i used the ip: 192.168.0.104/owncloud/
Now i cant even log in to owncloud anymore ^^.

Anyway i checked the folder (it is the path to my external harddisk: /media/bpidisk) and its right, everyone hast access: drwxrwxrwx 1 root root 4096 Jan 21 17:43 owncloud/

I tried to change it, but it doesnt work. I tried:
chmod 0770 owncloud/
and i tired to set the right using mc, there is no error msg, but thr rights are not changed either

**Comment by MorrisJobke** [comment]
@Mumba85 I won't be rude, but this bug tracker doesn't seem to be the right place for a setup problem. I'm also out of ideas for this. Can I ask you to ask your question in the forums?  http://forum.owncloud.org/ Because this bug tracker should just contain actual problems in the code base and not problems of the setup. Thanks
