### ISSUE TITLE
Some LDAP User without email

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/core#13560]
We integrated LDAP in ownCloud. We created in our LDAP Environment a special security group to automatically add users in our ownCloud. For most users everything works like a charm. But in some cases the user is added to ownCloud, his email address however isn't. This is especially annoying, because these users can't change their email address on their Personal Page. How can prevent this from happening again and how do we fix the users with no email address?

### Steps to reproduce

1. In Active Directory add Security Group "Owncloud" to user
2. Owncloud finds user
3. User has no Email Address for notifications, can't add Email Email Address (see attached picture)
![image002](https://cloud.githubusercontent.com/assets/214010/5976666/bedb6900-a890-11e4-8e88-0c606d4b06a2.jpg)
4. Happens not to everybody

### Expected behaviour

The user should have his assigned Email address from the AD in owncloud

### Actual behaviour

Some users don't have his assigned Email address from the AD in owncloud

### Server configuration

**Operating system**:

CentOS

**Web server:**

Apache/2.2.15 (Unix)

**Database:**

mysql Ver 14.14 Distrib 5.5.40, for Linux (x86_64)

**PHP version:**

5.4.34 (cli)

**ownCloud version:** (see ownCloud admin page)

ownCloud 7.0.3 (stable)

**Updated from an older ownCloud or fresh install:**

Fresh Install

**List of activated apps:**

Activity
Deleted files
Enterprise License Key
External storage support
FileLocking
File Shared access logging app
LDAP user and group backend
Log audit info
Mail Template Editor
Provisioning API
Share Files
Text Editor
Versions
Windows Network Drive

**The content of config/config.php:**

```
<?php
$CONFIG = array (
'appstoreenabled' => false,
'has_internet_connection' => false,
'supportedDatabases' => 
array (
0 => 'mysql',
1 => 'pgsql',
2 => 'oci',
3 => 'mssql',
),
'skeletondirectory' => '/mnt/Common/',
'check_for_working_htaccess' => false,
'instanceid' => '1234567890',
'passwordsalt' => '',
'trusted_domains' => 
array (
0 => '192.168.100.26',
1 => 'owncloud.mydomain.com',
2 => '123.456.789.1',
),
'datadirectory' => '/mnt/ocdata',
'overwrite.cli.url' => 'http://192.168.100.146/owncloud',
'dbtype' => 'mysql',
'version' => '7.0.3.3',
'dbname' => 'ocdata',
'dbhost' => 'localhost',
'dbtableprefix' => '',
'dbuser' => 'ocadmin',
'dbpassword' => '',
'installed' => true,
'mail_smtpmode' => 'smtp',
'mail_smtphost' => '192.168.100.10',
'mail_smtpport' => '25',
'ldapIgnoreNamingRules' => false,
'forcessl' => true,
'loglevel' => '1',
'theme' => 'mytheme',
'mail_from_address' => 'owncloud.mymail',
'mail_domain' => 'mydomain.com',
'default_language' => 'en',
);
```

**Are you using external storage, if yes which one:**

Windows Network Drive

**Are you using encryption:**

No

### Client configuration

**Browser:**

Firefox, Chrome, Internet Explorer

**Operating system:**
Win7 PRO SP1

#### Web server error log

```
{"app":"PHP","message":"touch(): Unable to create file \/var\/www\/html\/owncloud\/data\/owncloud.log because No such file or directory at \/var\/www\/html\/owncloud\/lib\/private\/log\/owncloud.php#49","level":3,"time":"2014-11-21T09:42:32+00:00"}
```

@MorrisJobke 

00002373

**Comment by karlitschek** [comment]
@blizzz

**Comment by MorrisJobke** [comment]
Would be nice to have examples for this. Otherwise this is a issue for the :crystal_ball: ;)

A working user and a not working user as example would be nice.

**Comment by MorrisJobke** [comment]
Infos that would help:

* `./occ ldap:show-config`

**Comment by MorrisJobke** [comment]
Get the username (see user management - left most column - quite cryptic hash) of a user that has a email address set in LDAP but not in ownCloud. Then execute this:

```
SELECT * FROM oc_preferences WHERE configkey = 'email' AND userid = '12345-abcdef-12345-abcdef';
```

**Comment by blizzz** [comment]
additional to Morris last post, please also fetch lastFeatureRefresh as configkey. Full SQL:

```sql
SELECT * FROM oc_preferences WHERE (configkey = 'email' OR configkey = 'lastFeatureRefresh') AND userid = '12345-abcdef-12345-abcdef';
```

**Comment by michaelstingl** [comment]
@MorrisJobke @blizzz Thanks! I requested this information.

**Comment by michaelstingl** [comment]
@MorrisJobke **see ./occ ldap:show-config on s3:**
S3-ownCloud/Shared/owncloud/support/github-issues/core/13560

**working user and a not working user as example:**
- **Working User:** CE87B949-0AB5-4838-B653-ED5C7BB7B728
- **NOT Working User:** 437202EE-5692-4B35-A073-074145198AFF

Waiting for SQL response…

**Comment by cdamken** [comment]
@michaelstingl 
> can't add Email Email Address (see attached picture)

Where is the picture?

**Comment by michaelstingl** [comment]
@cdamken I added the image to the initial comment: https://github.com/owncloud/core/issues/13560#issue-55032608

**Comment by michaelstingl** [comment]
Still waiting for SQL response…

**Comment by michaelstingl** [comment]
@MorrisJobke here comes the SQL:

**Working User:**

```
mysql> SELECT * FROM preferences WHERE (configkey = 'email' OR configkey = 'lastFeatureRefresh') AND userid = 'CE87B949-0AB5-4838-B653-ED5C7BB7B728';
+--------------------------------------+-----------+--------------------+-------------------------+
| userid | appid | configkey | configvalue |
+--------------------------------------+-----------+--------------------+-------------------------+
| CE87B949-0AB5-4838-B653-ED5C7BB7B728 | settings | email | K.******@domain.com |
| CE87B949-0AB5-4838-B653-ED5C7BB7B728 | user_ldap | lastFeatureRefresh | 1422539292 |
+--------------------------------------+-----------+--------------------+-------------------------+
```

**Formerly NOT working user:**

```
mysql> SELECT * FROM preferences WHERE (configkey = 'email' OR configkey = 'lastFeatureRefresh') AND userid = '437202EE-5692-4B35-A073-074145198AFF';
+--------------------------------------+-----------+--------------------+---------------------------+
| userid | appid | configkey | configvalue |
+--------------------------------------+-----------+--------------------+---------------------------+
| 437202EE-5692-4B35-A073-074145198AFF | settings | email | R.*******@domain.com |
| 437202EE-5692-4B35-A073-074145198AFF | user_ldap | lastFeatureRefresh | 1422626070 |
+--------------------------------------+-----------+--------------------+---------------------------+
```

@bboule 's tip to add mail under ADMIN->Advanced->Special Attributes->Email Field did the trick.

I don't know how it did it, because I did the same thing before I opened a ticket with you but now it seems to be working. [Perhaps I should have waited a little bit longer :) ]

**Comment by MorrisJobke** [comment]
@michaelstingl Okay :) Then this is fixed :) Thanks

**Comment by MorrisJobke** [comment]
@cdamken You had a similar problem. Can you try following:

> @bboule 's tip to add mail under ADMIN->Advanced->Special Attributes->Email Field did the trick.

And wait a bit (longest time to fetch everything is 24 hours).

Does this solve your problem?

**Comment by cdamken** [comment]
@MorrisJobke  
> @bboule 's tip to add mail under ADMIN->Advanced->Special Attributes->Email Field did the trick.

The attribute is correct 

> Does this solve your problem?

No, I still wait for the MySQL output

**Comment by MorrisJobke** [comment]
@cdamken Do you have another ticket for this? Or was this just something you've asked in IRC/Skype?

**Comment by cdamken** [comment]
I just created the ticket with the whole information :smile:
