### ISSUE TITLE
Local and remote users with the same name show up as the same user when sharing files

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#13571]
### Steps to reproduce

1. Install owncloud on two systems
2. on system one, create user c1 and remote share an item with a user q1 on system 2 
3. on system two, create a user c1 and locally share with q1
4. The shared view shows "c1" in both cases

### Expected behaviour

The remote "c1" and the local "c1" would be differentiated in the shared icon

### Actual behaviour

The remote "c1" and the local "c1" are not differentiated in the shared icon

![p248](https://cloud.githubusercontent.com/assets/8480343/5842289/98cdedd0-a171-11e4-84a5-029125e7fe0c.PNG)

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration

ownCloud Enterprise Edition 8.0 beta 1 (daily) Build:2015-01-21T04:13:37+00:00

**Comment by karlitschek** [comment]
Not sure this is a bug. @jancborchardt @schiesbn What are your opinions?

**Comment by LukasReschke** [comment]
I agree with @jnfrmarks that we need some kind of differentiation here to prevent Social Engineering like attempts.

**Comment by nickvergessen** [comment]
when you hover over the name it shows the remote domain, maybe we should just bring that into the normal UI aswell

**Comment by DeepDiver1975** [comment]
@jancborchardt we need your input on this - THX

**Comment by DeepDiver1975** [comment]
anyway - not really critical from my pov -> 8.1
