### ISSUE TITLE
 Intermittently, remote shares don't show up until the page is refreshed

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#13570]
### Steps to reproduce

1. Install owncloud on two systems
2. on system one, remote share an item with a user on system 2 
3. on system two, log in and accept the share
4. Intermittently, the share doesn't show up until the page is refreshed

### Expected behaviour

The share should show up without a refresh

### Actual behaviour

The page needs to be refreshed.

I haven't yet figured out the magic to make this happen consistently but I see it often in my testing.  Once I figure out the exact steps, I'll update this (unless of course it gets resolved before then ;) )  This might be a timing or initialization issue because once I refresh the page additional remote shares are immediately seen once accepted.

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration

ownCloud Enterprise Edition 8.0 beta 1 (daily) Build:2015-01-21T04:13:37+00:00

**Comment by karlitschek** [comment]
@schiesbn

**Comment by DeepDiver1975** [comment]
> Intermittently, the share doesn't show up until the page is refreshed

@jnfrmarks do you see any errors in the browser error console? <- always worth having an eye on it while testing :speak_no_evil:

**Comment by nickvergessen** [comment]
Can not reproduce this one.
The file list always refreshes for me (not a full page refresh, only the files list)

**Comment by nickvergessen** [comment]
Settings to 8.1 since the "workaround" (page refresh) is quite obvious and will be tried by most users

**Comment by PVince81** [comment]
Works for me every time with folder shares. Maybe we should add a spinner of some sort.

However, for file shares the page never refreshes. The "external.php" ajax call returns an empty body, so the calling JS code doesn't recognize it as successs and doesn't auto-refresh the page.

**Comment by PVince81** [comment]
Hmmmmm.... and now I got it working once with a single file.
It is indeed intermittent. Even in this case "external.php" returned nothing.

**Comment by PVince81** [comment]
Well of course! See https://github.com/owncloud/core/blob/master/apps/files_sharing/js/external.js#L134

The "accept" POST is done in parallel with `FileList.reload()`. Which means that if the "accept" call isn't finished yet, the list will be re-rendered too early.

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/core/pull/13691

I suggest to move this to 8.0. Intermittent failures make it look like the feature is broken.
