### ISSUE TITLE
Update deletes /cgi

### ISSUE THREAD

**Issue by kaffeeringe** [owncloud/core#13575]
Hi all!

I just used the automatic updater for the update from 7.0.2 to 7.0.4 and it failed because the updater deleted the /cgi folder that I need in my all-inkl.com webspace to run higher PHP versions. After restoring it, the update went on fine …

Thank you for all the cool work! Owncloud rules!

**Comment by LukasReschke** [comment]
Thanks for the feedback. We handle issues for the updater under https://github.com/owncloud/updater – can I ask you to open the issue there again?

Thanks!

**Comment by kaffeeringe** [comment]
:+1:
