### ISSUE TITLE
Share name not set when adding folder to shared directory

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#13572]
### Steps to reproduce

1. Install owncloud
2. User 1 shares a directory with user 2
3. Log in as user 2 and validate name in share icon
4. As User 1, add a file to the directory
5. As User 2, validate name in share icon
6. As user 1, validate name in share icon

### Expected behaviour

File should have share icon in user 1's view

### Actual behaviour

File does not have share icon in user 1's view

![p250](https://cloud.githubusercontent.com/assets/8480343/5842504/5345e9be-a173-11e4-9cee-980de932a415.PNG)

![p249](https://cloud.githubusercontent.com/assets/8480343/5842505/53468eaa-a173-11e4-99c7-d89be8ac1425.PNG)

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration

ownCloud Enterprise Edition 8.0 beta 1 (daily) Build:2015-01-21T04:13:37+00:00

**Comment by karlitschek** [comment]
@schiesbn

**Comment by jnfrmarks** [comment]
This is still in 8.1 though not critical for the release.

**Comment by PVince81** [comment]
I believe this is by design. We do not show the sticky share icon for the share owner for every subfolder entries. @jancborchardt can you confirm ?

**Comment by jancborchardt** [comment]
Yeah, because this would clutter it up too much. The correct fix is to put the share icon in the breadcrumb if a parent folder was shared. See https://github.com/owncloud/core/issues/4333 (»Not possible to share current folder«)
