### ISSUE TITLE
[OC7.0.4] Webdav error 500 when MKCOL existing_dir

### ISSUE THREAD

**Issue by PhilJung** [owncloud/core#13583]
OC7.0.4, Apache 2.2, PHP 5.4

MKCOL http://10.0.0.0/remote.php/webdav/Nouveau%20dossier/
Return code : 201
Return message : Created
do it again
MKCOL http://10.0.0.0/remote.php/webdav/Nouveau%20dossier/
Return code : 500
Return message : Internal Server Error

In web server error.log:
[Thu Jan 22 09:16:56 2015] [error] [client 10.0.0.0] {"app":"webdav","message":"Sabre\\\\DAV\\\\Exception\\\\MethodNotAllowed: The resource you tried to create already exists","level":4,"time":"2015-01-22 09:16:56"}

RFC2518 states it should be 405:
405 (Method Not Allowed) - MKCOL can only be executed on a deleted/non-existent resource.

**Comment by PVince81** [comment]
Works fine, tested in 7.0.7 and 8.1.0.
