### ISSUE TITLE
Inconsistent reference names for the encryption app

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#13580]
### Steps to reproduce

1. Install owncloud
2. Enable encryption, which has a new name for 8.0: Server-side Encryption
2. Navigate to the admin page - encryption is still referred to with the old name
3. Navigate to the personal page - encryption is still referred to with the old name

### Expected behaviour

The naming should be consistent throughout the UI

### Actual behaviour

The UI has a little old and a little new mixed in.

![p255](https://cloud.githubusercontent.com/assets/8480343/5846506/1af587e4-a192-11e4-93ac-ef49571151d2.PNG)

![p254](https://cloud.githubusercontent.com/assets/8480343/5846508/1d0b7638-a192-11e4-9406-98d2c2704de0.PNG)

![p256](https://cloud.githubusercontent.com/assets/8480343/5846524/3ab2f99a-a192-11e4-93a0-bb92b7cba7f8.PNG)

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration

ownCloud Enterprise Edition 8.0 beta 1 (daily) Build:2015-01-21T04:13:37+00:00

**Comment by karlitschek** [comment]
@schiesbn
