### ISSUE TITLE
Remove "add to owncloud" and use OCS/invite approach only

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13584]
In OC 8 there are now two workflows for server to server sharing.
This means more code paths to maintain and test.

This ticket is to discuss whether we should remove the "Add to ownCloud" feature from public links and only keep the new "invite user to mount a share" that was added in OC 8.

This means that:
1) People cannot mount random public links any more. Users who chose the "public link" approach is mostly for quick anonymous sharing.
2) If a user wants to allow mounting, that user must use the "invite" feature instead.
3) The "invite" feature gives more granular control over who can keep the share mounted (vs public link which allowed anyone. Revoking individually is not possible)
4) What happens to existing public link mounts ? (migration case)

What do you think ?

@owncloud/designers @karlitschek @schiesbn @icewind1991 @DeepDiver1975 @jnfrmarks

**Comment by MorrisJobke** [comment]
I really like the public link one. Can't we combine both? And convert the old public link one to an invite based? Otherwise it's just a removal of a feature because we are not able to write good code and that is the wrong way to go.

**Comment by PVince81** [comment]
Yes, consolidating the anonymous sharing with the invite feature might be the way to go.

It's not really about "good code". It is about more code paths to maintain/test.
If we can consolidate, then the code path will be much closer to the invite one instead of being quite different (mostly thinking about the JS stuff though)

**Comment by karlitschek** [comment]
Hmm. I see usecases for both ways

**Comment by jnfrmarks** [comment]
@MTRichards 

Is this a matter of refactoring the code underneath to handle both cases?  I don't think we should remove the public link case.

**Comment by karlitschek** [comment]
O.K. Let´s say they more clear. :-) We have to keep both usecases.

**Comment by PVince81** [comment]
Thanks for the feedback.

The only part that can somehow be consolidated is probably that "ajax/external.php" that imports an external share. But not sure. Let's keep this ticket to see if something can be done code-wise.

@schiesbn told me that the backend side should be the same for both so there shouldn't be too many duplicate testing required between both modes.

**Comment by PVince81** [comment]
"should be the same" => "is the same in the current version"

**Comment by PVince81** [comment]
> O.K. Let´s say they more clear. :-) We have to keep both usecases.

In hindsight I don't think there is much duplicate code paths that can be reused anyway => closing
