### ISSUE TITLE
[User Management] User is not created if it was first created and deleted

### ISSUE THREAD

**Issue by davitol** [owncloud/core#13589]
### Steps to reproduce

1. Go to users
2. Activate send to email address to new users.
3. Write down user/password
4. Click create new user.
5. Delete the new user just created
6. Create again a user with the same info as the previous one

### Expected behaviour
User should be created and mail sent.

### Actual behaviour

User does not appear in the list but the email is sent. If the browser is refreshed after the deletion, it works ok.

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.0.0.1","versionstring":"8.0 alpha 1","edition":""}

**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
none

**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password and passwordsalt)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** no

### Client configuration
**Browser:**
Chrome, Firefox

**Comment by DeepDiver1975** [comment]
@davitol can I ask you to switch the language to English when screen shotting? My Spanish is not that great :speak_no_evil:

**Comment by davitol** [comment]
@DeepDiver1975 Sure!! Next screenshots will be in english. :+1:

**Comment by karlitschek** [comment]
Can you retest please?

**Comment by jnfrmarks** [comment]
@davitol  Please retest.

**Comment by davitol** [comment]
:-1:   Bug not solved

{"installed":true,"maintenance":false,"version":"8.1.0.4","versionstring":"8.1 alpha 3","edition":""}

**Comment by DeepDiver1975** [comment]
we already moved all user management related topics to 8.2 - moving this as well

**Comment by jnfrmarks** [comment]
@davitol 

Do you refresh the page after deleting the user?  Right now, in order for the last deleted user to be official gone, you need to either refresh the admin page or navigate away.

**Comment by davitol** [comment]
@jnfrmarks Refreshing the screen the behaviour is OK, but settings as send email to a new user or show email adress are not kept as it is said in #12727

**Comment by PVince81** [comment]
Still happening on master (8.2 beta)

**Comment by cmonteroluque** [comment]
@PVince81 I think this needs to move forward, maybe 8.2.1

**Comment by PVince81** [comment]
This is because the deferred action from the "undo" notification isn't sent in the correct order.

**Comment by PVince81** [comment]
Ouch, we still didn't have time to introduce a proper undo handler, this is going to get fiddly...

**Comment by PVince81** [comment]
Fiddly fix is here https://github.com/owncloud/core/pull/19627
