### ISSUE TITLE
Cannot see "share" icon in Calendar on Safari

### ISSUE THREAD

**Issue by reckart** [owncloud/core#13588]
At http://demo.owncloud.org/index.php/apps/calendar I cannot see the "share" button when I open the page in Safari 7.1.2. It is in the HTML code, but not visible.

Opening the same page in Firefox 35.0, the share button is visible.

Browser set to language "German" in both cases.

**Comment by LukasReschke** [comment]
Sorry - please reopen at owncloud/calendar

**Comment by reckart** [comment]
Got told on IRC to open here. Reopened at https://github.com/owncloud/calendar/issues/679
