### ISSUE TITLE
Your web server is not yet properly setup to allow files synchronization because the WebDAV interface seems to be broken.

### ISSUE THREAD

**Issue by Owned67** [owncloud/core#13596]
Owncloud 7.0.4.2

I have see installation guides...

I have added 'check_for_working_webdav' => false, to ../owncloud/config/config.php

restart nginx et php5-fpm and always same...

and how to fix:
Votre dossier de données et vos fichiers sont probablement accessibles depuis internet. Le fichier .htaccess ne fonctionne pas. Nous vous recommandons vivement de configurer votre serveur web de façon à ce que ce dossier de données ne soit plus accessible, ou bien de le déplacer à l'extérieur de la racine du serveur web. 

I don't use htaccess with nginx....

Cheers

**Comment by PVince81** [comment]
The French error message doesn't match the subject of the issue. It has nothing to do with WebDAV.

.htaccess on Apache is used to prevent accessing the "data" folder from outside.
Can you check if opening "http://yourhost/owncloud/data/owncloud.log" works ?
If yes, then you need to double check your config (see http://doc.owncloud.org/server/7.0/admin_manual/installation/nginx_configuration.html)

Else it's a false positive, and a bug.

**Comment by Owned67** [comment]
owncloud.log (yes i have access):
{"app":"PHP","message":"fopen(\/home\/serveur\/www\/owncloud\/config\/config.php): failed to open stream: No such file or directory at \/home\/serveur\/www\/owncloud\/lib\/private\/config.php#141","level":3,"time":"2015-01-22T11:50:01+00:00"}
{"app":"PHP","message":"Comments starting with '#' are deprecated in Unknown on line 1 at Unknown#0","level":3,"time":"2015-01-22T13:31:16+00:00"}
{"app":"PHP","message":"Comments starting with '#' are deprecated in Unknown on line 1 at Unknown#0","level":3,"time":"2015-01-22T13:31:20+00:00"}
{"app":"PHP","message":"Comments starting with '#' are deprecated in Unknown on line 1 at Unknown#0","level":3,"time":"2015-01-22T13:31:48+00:00"}
{"app":"PHP","message":"Comments starting with '#' are deprecated in Unknown on line 1 at Unknown#0","level":3,"time":"2015-01-22T13:32:11+00:00"}
{"reqId":"54c0fdd1f3186","app":"PHP","message":"Comments starting with '#' are deprecated in Unknown on line 1 at Unknown#0","level":3,"time":"2015-01-22T13:40:33+00:00","method":"POST","url":"\/owncloud\/index.php\/core\/ajax\/translations.php"}
{"app":"PHP","message":"Comments starting with '#' are deprecated in Unknown on line 1 at Unknown#0","level":3,"time":"2015-01-22T13:42:33+00:00"}
{"app":"PHP","message":"Comments starting with '#' are deprecated in Unknown on line 1 at Unknown#0","level":3,"time":"2015-01-22T13:45:35+00:00"}
{"app":"PHP","message":"Comments starting with '#' are deprecated in Unknown on line 1 at Unknown#0","level":3,"time":"2015-01-22T13:46:09+00:00"}
{"app":"PHP","message":"Comments starting with '#' are deprecated in Unknown on line 1 at Unknown#0","level":3,"time":"2015-01-22T13:46:15+00:00"}
{"app":"PHP","message":"Comments starting with '#' are deprecated in Unknown on line 1 at Unknown#0","level":3,"time":"2015-01-22T13:47:10+00:00"}
{"app":"PHP","message":"Comments starting with '#' are deprecated in Unknown on line 1 at Unknown#0","level":3,"time":"2015-01-22T13:47:12+00:00"}
{"app":"PHP","message":"Comments starting with '#' are deprecated in Unknown on line 1 at Unknown#0","level":3,"time":"2015-01-22T13:47:15+00:00"}
{"app":"PHP","message":"Comments starting with '#' are deprecated in Unknown on line 1 at Unknown#0","level":3,"time":"2015-01-22T13:49:14+00:00"}
{"app":"PHP","message":"Comments starting with '#' are deprecated in Unknown on line 1 at Unknown#0","level":3,"time":"2015-01-22T13:51:07+00:00"}
{"app":"PHP","message":"Comments starting with '#' are deprecated in Unknown on line 1 at Unknown#0","level":3,"time":"2015-01-22T13:51:08+00:00"}
{"app":"PHP","message":"Comments starting with '#' are deprecated in Unknown on line 1 at Unknown#0","level":3,"time":"2015-01-22T13:51:11+00:00"}
{"app":"PHP","message":"ZipArchive::extractTo(): Invalid or unitialized Zip object at \/home\/serveur\/www\/owncloud\/lib\/private\/archive\/zip.php#135","level":3,"time":"2015-01-22T13:59:42+00:00"}
{"app":"core","message":"L'application ne fournit pas de fichier info.xml","level":3,"time":"2015-01-22T13:59:42+00:00"}
{"app":"PHP","message":"ZipArchive::extractTo(): Invalid or unitialized Zip object at \/home\/serveur\/www\/owncloud\/lib\/private\/archive\/zip.php#135","level":3,"time":"2015-01-22T13:59:59+00:00"}
{"app":"core","message":"L'application ne fournit pas de fichier info.xml","level":3,"time":"2015-01-22T13:59:59+00:00"}
{"app":"PHP","message":"Comments starting with '#' are deprecated in Unknown on line 1 at Unknown#0","level":3,"time":"2015-01-22T14:03:01+00:00"}
{"app":"PHP","message":"ZipArchive::extractTo(): Invalid or unitialized Zip object at \/home\/serveur\/www\/owncloud\/lib\/private\/archive\/zip.php#135","level":3,"time":"2015-01-22T14:03:21+00:00"}
{"app":"core","message":"L'application ne fournit pas de fichier info.xml","level":3,"time":"2015-01-22T14:03:21+00:00"}


nginx access log:
MYIP - - [22/Jan/2015:09:06:47 -0500] "PROPFIND /owncloud/remote.php/webdav HTTP/1.1" 404 31 "https://MYDOMAIN.NET/owncloud/index.php/settings/admin" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
MYIP - - [22/Jan/2015:09:06:48 -0500] "GET /owncloud/index.php/settings/ajax/checksetup HTTP/1.1" 200 66 "https://MYDOMAIN.NET/owncloud/index.php/settings/admin" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
MYIP - - [22/Jan/2015:09:08:45 -0500] "GET /owncloud/remote.php/webdav HTTP/1.1" 404 31 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
IP_VPS - - [22/Jan/2015:09:10:51 -0500] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 404 5 "-" "curl/7.26.0"
MYIP - - [22/Jan/2015:09:12:52 -0500] "GET /owncloud/ HTTP/1.1" 302 5 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
MYIP - - [22/Jan/2015:09:12:53 -0500] "GET /owncloud/index.php/apps/files/ HTTP/1.1" 200 4632 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
MYIP - - [22/Jan/2015:09:12:55 -0500] "GET /owncloud/index.php/core/js/oc.js?v=b9eec2bfd124482af1b5b48481c286c8 HTTP/1.1" 200 1556 "https://MYDOMAIN.NET/owncloud/index.php/apps/files/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
MYIP - - [22/Jan/2015:09:12:55 -0500] "GET /owncloud/core/img/actions/history.svg HTTP/1.1" 200 788 "https://MYDOMAIN.NET/owncloud/index.php/apps/files/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
MYIP - - [22/Jan/2015:09:12:55 -0500] "GET /owncloud/core/img/actions/download.svg HTTP/1.1" 200 320 "https://MYDOMAIN.NET/owncloud/index.php/apps/files/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
MYIP - - [22/Jan/2015:09:12:55 -0500] "GET /owncloud/core/img/actions/delete.svg HTTP/1.1" 200 478 "https://MYDOMAIN.NET/owncloud/index.php/apps/files/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
MYIP - - [22/Jan/2015:09:12:55 -0500] "POST /owncloud/index.php/core/ajax/translations.php HTTP/1.1" 200 16993 "https://MYDOMAIN.NET/owncloud/index.php/apps/files/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
MYIP - - [22/Jan/2015:09:12:56 -0500] "POST /owncloud/index.php/core/ajax/translations.php HTTP/1.1" 200 7682 "https://MYDOMAIN.NET/owncloud/index.php/apps/files/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
MYIP - - [22/Jan/2015:09:12:57 -0500] "POST /owncloud/index.php/core/ajax/translations.php HTTP/1.1" 200 476 "https://MYDOMAIN.NET/owncloud/index.php/apps/files/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
MYIP - - [22/Jan/2015:09:12:57 -0500] "GET /owncloud/core/img/actions/settings.svg HTTP/1.1" 200 1769 "https://MYDOMAIN.NET/owncloud/core/css/apps.css?v=b9eec2bfd124482af1b5b48481c286c8" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
MYIP - - [22/Jan/2015:09:12:58 -0500] "GET /owncloud/cron.php HTTP/1.1" 200 31 "https://MYDOMAIN.NET/owncloud/index.php/apps/files/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
MYIP - - [22/Jan/2015:09:12:58 -0500] "POST /owncloud/index.php/core/ajax/translations.php HTTP/1.1" 200 421 "https://MYDOMAIN.NET/owncloud/index.php/apps/files/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
MYIP - - [22/Jan/2015:09:12:59 -0500] "POST /owncloud/index.php/core/ajax/translations.php HTTP/1.1" 200 17032 "https://MYDOMAIN.NET/owncloud/index.php/apps/files/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
MYIP - - [22/Jan/2015:09:12:59 -0500] "POST /owncloud/index.php/apps/documents/ajax/mimes.php HTTP/1.1" 200 42 "https://MYDOMAIN.NET/owncloud/index.php/apps/files/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
MYIP - - [22/Jan/2015:09:13:00 -0500] "POST /owncloud/index.php/core/ajax/translations.php HTTP/1.1" 200 4640 "https://MYDOMAIN.NET/owncloud/index.php/apps/files/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
MYIP - - [22/Jan/2015:09:13:03 -0500] "GET /owncloud/core/img/places/home.svg HTTP/1.1" 200 521 "https://MYDOMAIN.NET/owncloud/index.php/apps/files/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
MYIP - - [22/Jan/2015:09:13:03 -0500] "GET /owncloud/core/img/actions/upload.svg HTTP/1.1" 200 337 "https://MYDOMAIN.NET/owncloud/core/css/icons.css?v=b9eec2bfd124482af1b5b48481c286c8" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
MYIP - - [22/Jan/2015:09:13:03 -0500] "GET /owncloud/core/img/actions/menu.svg HTTP/1.1" 200 511 "https://MYDOMAIN.NET/owncloud/core/css/icons.css?v=b9eec2bfd124482af1b5b48481c286c8" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
MYIP - - [22/Jan/2015:09:13:03 -0500] "GET /owncloud/index.php/apps/files/ajax/scan.php?force=false&dir=&requesttoken=94a63b7402464f9cc30c HTTP/1.1" 200 95 "https://MYDOMAIN.NET/owncloud/index.php/apps/files/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
MYIP - - [22/Jan/2015:09:13:04 -0500] "GET /owncloud/index.php/apps/files/ajax/list.php?dir=%2F&sort=name&sortdirection=asc HTTP/1.1" 200 353 "https://MYDOMAIN.NET/owncloud/index.php/apps/files/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
MYIP - - [22/Jan/2015:09:13:04 -0500] "GET /owncloud/index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/1.1" 200 153 "https://MYDOMAIN.NET/owncloud/index.php/apps/files/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
MYIP - - [22/Jan/2015:09:13:05 -0500] "GET /owncloud/core/img/actions/rename.svg HTTP/1.1" 200 536 "https://MYDOMAIN.NET/owncloud/index.php/apps/files/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
MYIP - - [22/Jan/2015:09:13:05 -0500] "GET /owncloud/core/img/actions/share.svg HTTP/1.1" 200 1003 "https://MYDOMAIN.NET/owncloud/index.php/apps/files/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
MYIP - - [22/Jan/2015:09:13:05 -0500] "GET /owncloud/core/img/actions/triangle-s.svg HTTP/1.1" 200 437 "https://MYDOMAIN.NET/owncloud/core/css/icons.css?v=b9eec2bfd124482af1b5b48481c286c8" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
MYIP - - [22/Jan/2015:09:13:05 -0500] "GET /owncloud/core/img/actions/triangle-n.svg HTTP/1.1" 200 439 "https://MYDOMAIN.NET/owncloud/core/css/icons.css?v=b9eec2bfd124482af1b5b48481c286c8" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
MYIP - - [22/Jan/2015:09:13:05 -0500] "GET /owncloud/index.php/core/ajax/share.php?fetch=getItemsSharedStatuses&itemType=file HTTP/1.1" 200 41 "https://MYDOMAIN.NET/owncloud/index.php/apps/files/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
127.0.0.1 - - [22/Jan/2015:09:13:06 -0500] "GET /owncloud/data/htaccesstest.txt HTTP/1.0" 200 11 "-" "-"
MYIP - - [22/Jan/2015:09:13:06 -0500] "GET /owncloud/index.php/core/preview.png?file=%2F%2Fwelcome.txt&c=54c0fb9c42bf2&x=36&y=36&forceIcon=0 HTTP/1.1" 200 344 "https://MYDOMAIN.NET/owncloud/index.php/apps/files/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
MYIP - - [22/Jan/2015:09:13:06 -0500] "GET /owncloud/index.php/settings/admin HTTP/1.1" 200 6428 "https://MYDOMAIN.NET/owncloud/index.php/apps/files/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
MYIP - - [22/Jan/2015:09:13:10 -0500] "GET /owncloud/index.php/core/js/oc.js?v=b9eec2bfd124482af1b5b48481c286c8 HTTP/1.1" 200 1556 "https://MYDOMAIN.NET/owncloud/index.php/settings/admin" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
MYIP - - [22/Jan/2015:09:13:17 -0500] "POST /owncloud/index.php/core/ajax/translations.php HTTP/1.1" 200 16993 "https://MYDOMAIN.NET/owncloud/index.php/settings/admin" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
MYIP - - [22/Jan/2015:09:13:36 -0500] "POST /owncloud/index.php/core/ajax/translations.php HTTP/1.1" 200 17032 "https://MYDOMAIN.NET/owncloud/index.php/settings/admin" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
MYIP - - [22/Jan/2015:09:13:36 -0500] "GET /owncloud/cron.php HTTP/1.1" 200 31 "https://MYDOMAIN.NET/owncloud/index.php/settings/admin" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
MYIP - - [22/Jan/2015:09:13:37 -0500] "PROPFIND /owncloud/remote.php/webdav HTTP/1.1" 404 31 "https://MYDOMAIN.NET/owncloud/index.php/settings/admin" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
MYIP - - [22/Jan/2015:09:13:37 -0500] "GET /owncloud/index.php/settings/ajax/checksetup HTTP/1.1" 200 66 "https://MYDOMAIN.NET/owncloud/index.php/settings/admin" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"

nginx configuration is clean... :+1: upstream php-handler {
        server 127.0.0.1:9000;
}

server {
        server_name     MYDOMAIN.NET;
        listen          80;
        server_tokens off;
        return 301 https://$server_name$request_uri;
}

server {
          server_tokens off;
          listen 443 ssl;
          server_name MYDOMAIN.NET;

          ssl_certificate /etc/ssl/certs/owncloud.crt;
          ssl_certificate_key /etc/ssl/private/owncloud.key;
          access_log      /var/log/nginx/access_owncloud.log;
          error_log       /var/log/nginx/error_owncloud.log;
          root /home/serveur/www;
          index index.php;
          # set max upload size
          client_max_body_size 10G;
          fastcgi_buffers 64 4K;

          rewrite ^/caldav(.*)$ /remote.php/caldav$1 redirect;
          rewrite ^/carddav(.*)$ /remote.php/carddav$1 redirect;
          rewrite ^/webdav(.*)$ /remote.php/webdav$1 redirect;

          error_page 403 /core/templates/403.php;
          error_page 404 /core/templates/404.php;

  location = /robots.txt {
    allow all;
    log_not_found off;
    access_log off;
    }

  location ~ ^/(?:\.htaccess|data|config|db_structure\.xml|README){
    deny all;
    }

  location / {
   # The following 2 rules are only needed with webfinger
   rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
   rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json last;

   rewrite ^/.well-known/carddav /remote.php/carddav/ redirect;
   rewrite ^/.well-known/caldav /remote.php/caldav/ redirect;

   rewrite ^(/core/doc/[^\/]+/)$ $1/index.html;
   
   
   try_files $uri $uri/ /index.php;
   }

   location ~ ^(.+?\.php)(/.*)?$ {
           try_files $1 = 404;
           fastcgi_split_path_info ^(.+\.php)(/.+)$;
           include fastcgi_params;
           fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
           #fastcgi_param SCRIPT_FILENAME $document_root$1;
           #fastcgi_param PATH_INFO $2;
           fastcgi_param PATH_INFO $fastcgi_path_info;
           fastcgi_param HTTPS on;
           fastcgi_pass php-handler;

   }

   # Optional: set long EXPIRES header on static assets
   location ~* \.(?:jpg|jpeg|gif|bmp|ico|png|css|js|swf)$ {
       expires 30d;
       # Optional: Don't log access to assets
         access_log off;
   }

}

**Comment by PVince81** [comment]
Hmm okay that's not good, please check your Nginx config. There might be some clauses that will block access to the "data" directory (or simply not allow it). Please check the doc I linked and compare with your settings.

**Comment by Owned67** [comment]
Thanks! Solved
