### ISSUE TITLE
Votre dossier de données et vos fichiers sont probablement accessibles depuis internet. Le fichier .htaccess ne fonctionne pas. Nous vous recommandons vivement de configurer votre serveur web de façon à ce que ce dossier de données ne soit plus accessible, ou bien de le déplacer à l'extérieur de la racine du serveur web. 

### ISSUE THREAD

**Issue by Owned67** [owncloud/core#13597]
Hello,

i post a new issue...
Votre dossier de données et vos fichiers sont probablement accessibles depuis internet. Le fichier .htaccess ne fonctionne pas. Nous vous recommandons vivement de configurer votre serveur web de façon à ce que ce dossier de données ne soit plus accessible, ou bien de le déplacer à l'extérieur de la racine du serveur web. 

Cheers

**Comment by MorrisJobke** [comment]
@PVince81 Maybe there is something useful in this text and you can decrypt it ;)

**Comment by PVince81** [comment]
This is the usual ".htaccess" error message but in French.

**Comment by Owned67** [comment]
I use nginx... i can fix? how? or it's false bug?

**Comment by PVince81** [comment]
Isn't it the same issue as https://github.com/owncloud/core/issues/13596#issuecomment-71030291 ?

**Comment by Owned67** [comment]
I decided to create a new outcome, the WebDav problem is corrected but not this one.

**Comment by PVince81** [comment]
Ah ok. I was confused because the other ticket had the same error message.

If you're still able to access owncloud.log through http://yourserver/owncloud/data/owncloud.log, then you need to triple check your nginx config like before.

**Comment by Owned67** [comment]
Nginx config is fixed.

{"app":"PHP","message":"ZipArchive::extractTo(): Invalid or unitialized Zip object at \/home\/serveur\/www\/owncloud\/lib\/private\/archive\/zip.php#135","level":3,"time":"2015-01-22T13:59:42+00:00"}
{"app":"core","message":"L'application ne fournit pas de fichier info.xml","level":3,"time":"2015-01-22T13:59:42+00:00"}
{"app":"PHP","message":"ZipArchive::extractTo(): Invalid or unitialized Zip object at \/home\/serveur\/www\/owncloud\/lib\/private\/archive\/zip.php#135","level":3,"time":"2015-01-22T13:59:59+00:00"}
{"app":"core","message":"L'application ne fournit pas de fichier info.xml","level":3,"time":"2015-01-22T13:59:59+00:00"}
{"app":"PHP","message":"Comments starting with '#' are deprecated in Unknown on line 1 at Unknown#0","level":3,"time":"2015-01-22T14:03:01+00:00"}
{"app":"PHP","message":"ZipArchive::extractTo(): Invalid or unitialized Zip object at \/home\/serveur\/www\/owncloud\/lib\/private\/archive\/zip.php#135","level":3,"time":"2015-01-22T14:03:21+00:00"}
{"app":"core","message":"L'application ne fournit pas de fichier info.xml","level":3,"time":"2015-01-22T14:03:21+00:00"}
{"app":"PHP","message":"ZipArchive::extractTo(): Invalid or unitialized Zip object at \/home\/serveur\/www\/owncloud\/lib\/private\/archive\/zip.php#135","level":3,"time":"2015-01-22T14:20:10+00:00"}
{"app":"core","message":"L'application ne fournit pas de fichier info.xml","level":3,"time":"2015-01-22T14:20:10+00:00"}

**Comment by PVince81** [comment]
But you can still access it, so something must be wrong.

Can you post your config and maybe someone can help check it ? CC @josh4trunks

**Comment by Owned67** [comment]
upstream php-handler {
        server 127.0.0.1:9000;
}

server {
        listen          80;
	server_name     MYDOMAIN.NET;
	#server_tokens off;
	return 301 https://$server_name$request_uri;
}

server {
	  #server_tokens off;
	  listen 443 ssl;
	  server_name MYDOMAIN.NET;

	  ssl_certificate /etc/ssl/certs/owncloud.crt;
	  ssl_certificate_key /etc/ssl/private/owncloud.key;
          access_log      /var/log/nginx/access_owncloud.log;
	  error_log       /var/log/nginx/error_owncloud.log;
	  root /home/serveur/www;
	  index index.php;
	  # set max upload size
	  client_max_body_size 10G;
	  fastcgi_buffers 64 4K;

	  rewrite ^/caldav(.*)$ /remote.php/caldav$1 redirect;
	  rewrite ^/carddav(.*)$ /remote.php/carddav$1 redirect;
	  rewrite ^/webdav(.*)$ /remote.php/webdav$1 redirect;

	  error_page 403 /core/templates/403.php;
	  error_page 404 /core/templates/404.php;

  location = /robots.txt {
    allow all;
    log_not_found off;
    access_log off;
    }

  location ~ ^/(?:\.htaccess|data|config|db_structure\.xml|README){
    deny all;
  }

  location / {
   # The following 2 rules are only needed with webfinger
   rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
   rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json last;

   rewrite ^/.well-known/carddav /remote.php/carddav/ redirect;
   rewrite ^/.well-known/caldav /remote.php/caldav/ redirect;

   rewrite ^(/core/doc/[^\/]+/)$ $1/index.html;

   try_files $uri $uri/ /index.php;
   }

#   location ~ \.php(?:$|/) {
#   fastcgi_split_path_info ^(.+\.php)(/.+)$;
#   include fastcgi_params;
#   fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
#   fastcgi_param PATH_INFO $fastcgi_path_info;
#   fastcgi_param HTTPS on;
#   fastcgi_pass php-handler;
#   }


#   location ~ ^(.+?\.php)(/.*)?$ {
   location ~ \.php(?:$|/) {
           #try_files $1 = 404;
	   fastcgi_split_path_info ^(.+\.php)(/.+)$;
	   include fastcgi_params;
	   fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	   fastcgi_param PATH_INFO $fastcgi_path_info;
           fastcgi_param HTTPS on;
	   fastcgi_pass php-handler;

   }

   # Optional: set long EXPIRES header on static assets
   location ~* \.(?:jpg|jpeg|gif|bmp|ico|png|css|js|swf)$ {
       expires 30d;
       # Optional: Don't log access to assets
         access_log off;
   }

}

**Comment by josh4trunks** [comment]
when you post your config, please try to get it all in code blocks, i think 3*` before and after work best.

not sure why but you seem to have 2 or 3 different php location blocks, just keep the first one.

**Comment by Owned67** [comment]
Yes sorry.

What? It's ginx config from your site...

**Comment by josh4trunks** [comment]
thanks, looks better. what exactly is the issue here?
/data is accessible, or what?

**Comment by Owned67** [comment]
issue: 
Votre dossier de données et vos fichiers sont probablement accessibles depuis internet. Le fichier .htaccess ne fonctionne pas. Nous vous recommandons vivement de configurer votre serveur web de façon à ce que ce dossier de données ne soit plus accessible, ou bien de le déplacer à l'extérieur de la racine du serveur web. 


https://dadada.changeip.net/owncloud/data/
No input file specified.

https://dadada.changeip.net/owncloud/data/owncloud.log => work

**Comment by josh4trunks** [comment]
based on my quick review your config like like it should block /data. did you reload/restart nginx?

**Comment by Owned67** [comment]
yes, multiples times....

**Comment by josh4trunks** [comment]
also looks like you are missing a space here, before the curly bracket
```location ~ ^/(?:\.htaccess|data|config|db_structure\.xml|README){```

**Comment by Owned67** [comment]
This just your guide:
http://doc.owncloud.org/server/7.0/admin_manual/installation/nginx_configuration.html

I need replace by:
  location ~ ^/(?:\.htaccess|data|config|db_structure\.xml|README) {

??

**Comment by josh4trunks** [comment]
yes.. add the space, but use what I posted, yours is missing some "\"
the posted config is missing the space which should be fixed.

**Comment by Owned67** [comment]
No... error persist...

**Comment by josh4trunks** [comment]
k, guess the mystory will never be solved.
