### ISSUE TITLE
Preview providers should take maxX and maxY into consideration

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#13607]
#### Problem

The interface includes maX and maxY for a reason and yet, none of the providers use it.

A 5000x5000, 140MB TIFF is currently being converted to a 5000x5000 50MB PNG.
Fortunately, it will soon be possible to avoid multiple roundtrips to ImageMagick (via https://github.com/owncloud/core/pull/13674) , but each resizing request of that 50MB PNG is still going to take some time (and waste memory) and that will only partially be fixed once https://github.com/owncloud/core/issues/8196 is implemented.

#### Solution
Make sure preview providers take maxX and maxY into consideration when generating previews. With https://github.com/owncloud/core/pull/13674 in place, each provider should only be called once.

I'm going to fix Bitmap, but the other providers should be fixed as well.

- [x] Bitmap
- [x] Image
- [x] Txt
- [x] MP3
- [x] SVG
- [x] Movie

**Comment by oparoz** [comment]
Job done for all files using the bitmap preview class: https://github.com/owncloud/core/pull/13635

**Comment by oparoz** [comment]
Re-opening, as the Image provider is not taking the max dimensions into consideration

**Comment by oparoz** [comment]
Fix is in https://github.com/owncloud/core/issues/16382

**Comment by PVince81** [comment]
You tagged this as regression, so this worked before ?

**Comment by oparoz** [comment]
Yes, before the max preview, each provider would be queried for each request and thus provide a preview matching the asked dimension. Since they're now only use to generate the max preview, we need to make sure those previews keep the aspect ratio of the original image.

**Comment by DeepDiver1975** [comment]
@oparoz we can close this now that #16382  is merged? THX

**Comment by oparoz** [comment]
Yes, the API should now return the expected previews.

**Comment by DeepDiver1975** [comment]
> Yes, the API should now return the expected previews.

awesome - thanks @oparoz for your contribution - very much welcome!
