### ISSUE TITLE
LDAP getUsers is not returning all users if limit and offset are not specified

### ISSUE THREAD

**Issue by blizzz** [owncloud/core#13602]
### Steps to reproduce
1. Run the script
   
   ``` php
   <?php
   
   require_once 'lib/base.php';
   \OC_App::loadApp('user_ldap');
   $um = \OC::$server->getUserManager();
   $users = $um->search('');
   print(count($users) . ' users' . PHP_EOL);
   ```
### Expected behaviour

The number of all total users should appear
### Actual behaviour

From LDAP only as many users are retrieved as page limit is configured for the LDAP server.

**Please note:** It is a terribly bad idea to run `\OC::$server->getUserManager()->search('');` without specifying limit and offset, especially for anything user interface related. Image 1 million users being fetched from a service on a distant machine. In few certain edge cases it is valid (e.g. background files scan command).

(The problem does not exist with counting LDAP objects as done in user:report)

**Comment by DeepDiver1975** [comment]
as a result we shall review all locations where search is used and move over to a more iterative approach where we process users in chunks.

We could add a method to the user manager which takes a closure like this:

```php
\OC::$server->getUserManager()->foreach(function($user) {
    $user->delete();
});

**Comment by DeepDiver1975** [comment]
8.1 topic for me

**Comment by blizzz** [comment]
Nice idea the closure is.

**Comment by DeepDiver1975** [comment]
or we return a custom implementation of ArrayAccess for search which will lazy load users as any array function iterates over the array

**Comment by DeepDiver1975** [comment]
Using an iterator might make more sense to me.

@bantu interested in coming up with a PR to address this?

From my understanding we should add a new method to the user manager:

```php

namespace OC\User;

class UserIterator implements Iterator{
}

namespace OCP;

interface IUserManager {
    /**
     * @param string $pattern
     * @return \Iterator
     */
    public function getIterator($pattern = '');

**Comment by DeepDiver1975** [comment]
The implementation of that user iterator will loop backends and users inside.

namespace OC\User;

class UserIterator implements Iterator{
    pubic function __construct(UserManager $mgmr, $pattern = '') {}
}

**Comment by PVince81** [comment]
@blizzz any update ?

**Comment by PVince81** [comment]
@butonic to be reopened in user_ldap if there is interest in fixing this and if the issue still exists.
