### ISSUE TITLE
[User Management] Upper search textbox does not work for users

### ISSUE THREAD

**Issue by davitol** [owncloud/core#13606]
### Steps to reproduce

1. Go to users
2. Activate send to email address to new users.
3. Write down an existing user name in upper search textbox

### Expected behaviour
Users that match with the text should be shown

### Actual behaviour

"No search result in other places" 

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.0.0.3","versionstring":"8.0 beta 1","edition":""}
**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
none

**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password and passwordsalt)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** no

### Client configuration
**Browser:**
Firefox

![search](https://cloud.githubusercontent.com/assets/10596560/5858551/52a10e12-a254-11e4-8398-f9b5d63c09b6.png)

**Comment by DeepDiver1975** [comment]
it was never expected to search fro users using the search box up there.

But honestly that text on the screen looks really strange - @jancborchardt 

8.1

**Comment by jancborchardt** [comment]
@butnic can we hijack the search box on that page to make it do what the cirrent user search box does? (And then delete the search box on zhe users page)

**Comment by jancborchardt** [comment]
Superseded by the plan in https://github.com/owncloud/core/issues/14973 – it’s not a bug because there’s an extra search bar. But we should get rid of that extra one and use the existing top search bar.
