### ISSUE TITLE
Groups <-> users share permissions issue

### ISSUE THREAD

**Issue by cedric-dufour** [owncloud/core#13619]
(coming from https://github.com/owncloud/calendar/issues/619)

### Steps to reproduce
1. configure OC for LDAP groups and users
2. user sharer S shares a file (or calendar) with group G and removes edit permissions from share

### Expected behaviour
Users (Ug) from group G should not be able to edit file (or calendar) anylonger

### Actual behaviour
Users (Ug) from group G are *still* able to edit file (or calendar).
This is a serious security issue for large-scale deployments (e.g. academics)

### Server configuration
**Operating system**: Debian/Wheezy (64-bit)
**Web server:** Apache 2.2.22 (stock Debian/Wheezy)
**Database:** MySQL 5.5.40 (stock Debian/Wheezy)
**PHP version:** PHP 5.4.36 (stock Debian/Wheezy)
**ownCloud version:** 7.0.4-3 (Debian/Wheezy package from OC official repository)
**Updated from an older ownCloud or fresh install:** updated after each update since 7.0.3
**List of activated apps:** does not apply (I think)
**The content of config/config.php:** does not apply (I think)
**Are you using external storage, if yes which one:** none
**Are you using encryption:** no

### Client configuration
**Browser:** Firefox 31.4.0 (stock Debian/Jessie)
**Operating system:** Debian/Jessie (64-bit)

### Logs
do not apply (I think)

### Additional information

OC is still under evaluation and only a very few objects exist in the database; it makes debugging easy.

Looking at table oc_share:

1. When sharer S creates a new share entry [GUI], corresponding entries are immediately created for both group G (share_type=1) and users Ug (share_type=2), along *default* permissions (editable) [DB]

2. When sharer S removee (uncheck) edit permissions [GUI], only group G permissions (share_type=1) are updated (non-editable); users Ug permissions (share_type=2) are left *unchanged* (editable) [DB]

3. Deleting share_type=2 entries from table oc_share makes shared file (or calendar) disappear from users Ug views

NOTE:
a. sharer S is the only non-LDAP user (OC admin, in facts)
b. all groups and users are LDAP-based
c. resharing has been disabled at Admin level; behavior appears identical if it is enabled (that would need double-checking)
d. there is *no* name conflict between object shared by S and objects in users Ug realms
e. the fact that users permissions (share_type=2) are created for group-shared objects is very scary, given the large quantity of users (>100) in some groups (scalability?)

Thanks and best

**Comment by JeTim** [comment]
Hi Cedric, I found the same problem. Do you have a idea, when this problem will be solved.
I am just a enthusiastic user of OC, and want to implement it in our department at university. It seems that OC 7.0.2 do not have this problem. It is advisable to use 7.0.2 until the problem is solved.
You are right is a realy scary problem!

**Comment by blizzz** [comment]
cc @schiesbn i think this was discussed over in calendar and affects files as well, but not limited to ldap users.

**Comment by cedric-dufour** [comment]
Updated to OC 8.0.0-9 (Debian package).
Group permissions seem fixed, both for Calendar App and files.
Permissions get created in oc_share table initially with edit right (permissions=15), both for the group (share_type=1) and its users (share_type=2).
When permissions are restricted, both group and users permissions are modified/lowered (permissions=1). Users can not edit the shared resource anylonger.
When granting permission again, only group permission is modified/raised (back to permissions=15); users can still modify the shared resource, though, even if their permissions remains unchanged (permissions=1).
Let's now hope share_type=2 will not blow oc_share table away when OC is opened to our students.

**Comment by PVince81** [comment]
@cedric-dufour if I understand well it worked properly ?
If you still see an issue after trying 8.0.5 or newer, feel free to reopen.
