### ISSUE TITLE
can not upload file

### ISSUE THREAD

**Issue by taich001** [owncloud/core#13618]
I have a linux executeable file (e.g. /bin/dbus-deamon) and I can not upload it to owncloud. Response from my owncloud server is "Could not get result from server".

Does anybody know the reason?

Thanks
Thomas

**Comment by RealRancor** [comment]
Hi,

please fill out the issue template provided here:

https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

as asked in the guidelines for contributing (linked in the box when creating a new issue).

Without more informations about your environment its nearly impossible to know whats wrong here.
