### ISSUE TITLE
Display yellow warning bar when a favorite is missing from the favorite list

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#13624]
When a external storage is disconnected (e.g. network issue), the favorites are not displayed. This was made in #13479 as a quick solution. It's better to hide one then to have an exception which blocks the complete favorite list.
However, better UX would be to either still list the file and display a warning on the row, or at least put a warning at the top of the page, that some files are not listed due to xXwhateverXx

@PVince81 agreed on this https://github.com/owncloud/core/pull/13479#discussion_r23170361

**Comment by jancborchardt** [comment]
Best would be to just add a row at the bottom of the list saying »Some favorites could not be shown since external storage `Name` is not connected.« Of course only show that line when there actually were favorites of that external storage.
