### ISSUE TITLE
Add Share API calls to automatically mount remote shares

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13627]
Use cases:
- a user wants to accept a server to server share over the Android app
- trigger a server to server share invite over the Android app
- automated tests that automatically setup two servers and automatically mounts server to server shares

@schiesbn some of them might already be possible, but I remember you said some still need to be covered.

The Share API should be extended to support these cases:
- share file/folder with external user (might work with shareType = 4?)
- mount "link" share
- mount/accept "remote" share

CC @jnfrmarks will be of interest for automated tests

**Comment by rullzer** [comment]
Of course this would hold true for any client.
I would very much like to see the proposed API extensions. When this is implanted I suggest to allow specifying the mount point directly. I.E. if I add a link share via the API that I can direct say place it in folder X.
