### ISSUE TITLE
Versions lost when moving file to or out of external storage root

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13634]
### Steps to reproduce
1. Create a file "versions.txt"
2. Edit and save the file multiple times to create versions
3. Open the "Versions" dropdown and see that versions exist
4. Mount a SFTP external storage to "/sftp"
5. Move "/versions.txt" to "/sftp"
6. Open the "Versions" dropdown again

### Expected result
Versions kept

### Actual result
Versions lost. Moving the file back to "/" doesn't bring them back either.

Note: if "versions.txt" is created and edited on "/sftp", the versions works. But then moving it to "/" will lose the versions too.

### Versions
Broken on: ownCloud 8 post beta1 git master (f8b1fde2c06575de79035f6690bda8a24c9802e9)
Works correctly on stable7 (80560e70b7133739f87cf6a03acb55169fb2462f)

@schiesbn @icewind1991

**Comment by PVince81** [comment]
Here is the file tree before moving "versions.txt" into "/sftp":
```
% find -iname \*versions\* 
./root/files_versions
./root/files_versions/versions.txt.v1422028532
./root/files_versions/versions.txt.v1422028507
./root/files/versions.txt
```

File cache:
```
MariaDB [owncloud]> select fileid,path,size,mtime from oc_filecache where path like '%version%';
+--------+-----------------------------------------+------+------------+
| fileid | path                                    | size | mtime      |
+--------+-----------------------------------------+------+------------+
|     12 | files_versions                          |   82 | 1422028539 |
|     32 | files_versions/sftp                     |    0 | 1422028313 |
|     69 | files/versions.txt                      |    6 | 1422028537 |
|     73 | files_versions/versions.txt.v1422028507 |   69 | 1422028534 |
|     74 | files_versions/versions.txt.v1422028532 |   13 | 1422028539 |
+--------+-----------------------------------------+------+------------+
```

Now after moving the file into "/sftp", they seem to land into the trashbin ?!
```
./root/files_trashbin/versions
./root/files_trashbin/versions/versions.txt.v1422028507.d1422028609
./root/files_trashbin/versions/versions.txt.v1422028532.d1422028609
./root/files_trashbin/files/versions.txt.d1422028609
./root/files_versions
```

```
MariaDB [owncloud]> select fileid,path,size,mtime from oc_filecache where path like '%version%';
+--------+-------------------------+------+------------+
| fileid | path                    | size | mtime      |
+--------+-------------------------+------+------------+
|     12 | files_versions          |    0 | 1422028609 |
|     32 | files_versions/sftp     |    0 | 1422028313 |
|     83 | files_trashbin/versions |    0 | 1422028609 |
|     85 | versions.txt            |    6 | 1422028609 |
+--------+-------------------------+------+------------+
```

It could have something to do with the "unlink()" from the cross-storage rename, which triggers the versions hook, making it believe that it's a deletion.

Note: I also observed this issue on the trashbin storage wrapper fix branch: https://github.com/owncloud/core/pull/13561
I believe that in this case the versions hooks would also be triggered.

But it doesn't explain why it worked in stable7, which also resorts to such hooks.

**Comment by PVince81** [comment]
I had another try with https://github.com/owncloud/core/pull/13561 and the test result is the same: the versions are moved into the trashbin.

**Comment by PVince81** [comment]
This issue was also introduced by cd4c7fd which is the trashbin storage wrapper...
The commit before that works fine.

**Comment by PVince81** [comment]
For reference: trashbin wrapper PR that introduced the issue: https://github.com/owncloud/core/pull/13377

**Comment by PVince81** [comment]
Fixed by https://github.com/owncloud/core/issues/13561

**Comment by SergioBertolinSG** [comment]
Tested in 8.0.3, half of the versions are lost when moving versions.txt into the SFTP mounted folder.

**Comment by PVince81** [comment]
@SergioBertolinSG half ? Then it is not a bug, it's the "version thinning" algorithm that got activated somehow and auto-expired versions after moving.

**Comment by DeepDiver1975** [comment]
moving to 8.2 - we need to have a closer look at sftp anyhow - nothing which can be quick fixed afaik

**Comment by PVince81** [comment]
@SergioBertolinSG this should work already.

You can first trigger the version thinning algorithm by moving the folder into a regular subfolder (not SFTP), then move it out again. Then check the number of versions: it should be thinned out already.
And then move it into the SFTP folder and see that it's still the same amount.

**Comment by PVince81** [comment]
@SergioBertolinSG can you try again with 8.2 ?

**Comment by cmonteroluque** [comment]
@owncloud/qa-team please check

**Comment by SergioBertolinSG** [comment]
Working fine on 8.2.
