### ISSUE TITLE
"Uploading" section in sidebar

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13631]
Scenario:
1. Go to folder A: upload files
2. During upload, go to folder B: upload files/folders
3. During upload, go to folder C: upload files/folders

This scenario already works well as the upload is still running in the background and puts files in the proper folders.

It would be nice to have a section "Uploading..." in the sidebar with a spinner where one can view the list of files that are being uploaded (with a cancel button).
This means that if there's a big file in the middle that takes too long, that file could be individually cancelled.

This view could replace the progress bar in the controls bar.

The sidebar entry could look like this:
- "Uploading... (file 1/135)"
- could have a background/progress bar on the item

What do you think ? @owncloud/designers

**Comment by PVince81** [comment]
To clarify: activating the section in the sidebar would show a flat list of the files being uploaded, with a spinner to the ones currently uploading (not sure if we already have parallel upload, it might still be one by one). The ones that are done uploading will either disappear from the list or become clickable (clicking on it could jump to the corresponding location in "All files") :smile:

**Comment by jbtbnl** [comment]
I like this idea :+1:

**Comment by jancborchardt** [comment]
Yeah, a temporary sidebar entry for that would be good indeed! Then uploads don’t feel blocking anymore and people could navigate through their files while an upload takes place. (Given that this is possible.)

**Comment by PVince81** [comment]
Navigating during upload is already possible as long as the user doesn't leave the files app, try it out :wink:

**Comment by jancborchardt** [comment]
I know – I was referring to that it doesn’t _feel_ like it’s possible at the moment. ;) So a change like this would be good. :)

**Comment by PVince81** [comment]
Haha, true. I agree that it doesn't feel like it is possible :smile:

**Comment by jancborchardt** [comment]
Closing in favor of #18589 »Combine new+upload and move to sidebar« where we specced more and also have a mockup.
