### ISSUE TITLE
'ldapUserCleanupInterval' is not enabled by default in config.php

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#13639]
### Steps to reproduce

1. Install owncloud
2. Enable LDAP
3. Click on admin page
4. Configure LDAP server
5. Check config.php to see if 'ldapUserCleanupInterval' is enabled (I'm not sure when it should get enabled)

### Expected behaviour

According to issue #12643 'ldapUserCleanupInterval' should be enabled be default in config.php

### Actual behaviour

'ldapUserCleanupInterval'  is not enabled in config.php

### Browser

Chrome

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration

ownCloud Enterprise Edition 8.0 beta 1 (daily) Build:2015-01-23T04:12:45+00:00

**Comment by karlitschek** [comment]
@blizzz

**Comment by blizzz** [comment]
@jnfrmarks  If it is not present (as in this case), the default behaviour kicks in (=> 51min). See also config.sample.php.

**Comment by DeepDiver1975** [comment]
@jnfrmarks case closed? THX
