### ISSUE TITLE
Sharing is broken when a user is in more than 1000 groups with SQLite

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#13630]
See my remarks at https://github.com/owncloud/core/pull/13463/files#r23421042

**Comment by PVince81** [comment]
Come on, stop trying and break stuff :wink: 

Thanks for the report so we don't forget.

**Comment by LukasReschke** [comment]
;D

**Comment by DeepDiver1975** [comment]
not only sqlite related - oracle has a limit of 1000 as well

**Comment by cmonteroluque** [comment]
moving to 9.0, would need customer input to accelerate

**Comment by nickvergessen** [comment]
sqlite is CE only, so no customer input ;)

**Comment by PVince81** [comment]
the answer: use MySQL or PostgreSQL for big numbers of files/users/groups
