### ISSUE TITLE
Minor CSS issue in "New" menu

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13632]
### Steps:
1. In the files app, click "New" and leave the menu open
![newmenu1](https://cloud.githubusercontent.com/assets/277525/5877192/2c227f30-a31e-11e4-9727-ea824b5a6157.png)

2. Hover on "New":
![newmenu2](https://cloud.githubusercontent.com/assets/277525/5877200/39878332-a31e-11e4-9f55-42890e22bd91.png)

3. Hover back and forth between "New" and the upload button.

### Expected result
Menu items stay black

### Actual result
Text of menu items becomes grey. They seem to inherit the hover style from the button.

@owncloud/designers

**Comment by PVince81** [comment]
Hmmm, also happens on stable7 and 7.0.4

**Comment by Sugaroverdose** [comment]
Maybe it's better to make button same as highlighted when dropdown opened? Look's like it doesn't have specific styles for 'active' state except 0 border-radius for bottom angles.

**Comment by Sugaroverdose** [comment]
What about to make new file menu looks like this:
![2015-01-25 7 33 41 am](https://cloud.githubusercontent.com/assets/10269200/5890269/a1fa21d0-a464-11e4-9021-cb00107ee00d.png)

**Comment by MorrisJobke** [comment]
@Sugaroverdose I would really like this :) :+1:

**Comment by MorrisJobke** [comment]
Fix is in #13655
