### ISSUE TITLE
A mime type can be linked to many file formats

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#13647]
### The situation
- Preview uses [Imagick::queryFormats](http://php.net/manual/en/imagick.queryformats.php) to determine if a specific file format is supported by the system

```
$imagickProviders = array(
    'SVG'   => 'OC\Preview\SVG',
    'TIFF'  => 'OC\Preview\TIFF',
    'PDF'   => 'OC\Preview\PDF',
    'AI''       => 'OC\Preview\Illustrator',
    'PSD'   => 'OC\Preview\Photoshop',
    'EPS'   => 'OC\Preview\Postscript',
);

foreach ($imagickProviders as $queryFormat => $provider) {
    if (count($checkImagick->queryFormats($queryFormat)) === 1) {
        self::registerProvider($provider);
    }
}
```

The key is the name of a format supported by ImageMagick
- Only one format is linked to a preview provider class. It's an arbitrary decision
- A preview class can only be activated once or it will be loaded several times in the $registeredProviders` array.
### The problem

We can't always know which formats the admin is going to enable in ImageMagick to support a certain family of files.
#### An example with Font files

The check in Preview
`TTF'   => 'OC\Preview\Font`

Some formats supported by ImageMagick
- TTF
- OTF

Extension enabled
- OTF

The system will determine that font preview has to be disabled.
### Solutions

One solution would be to add all the formats as keys and for `registerProvider` to check if a class is already registered before adding it to the array.

**Comment by oparoz** [comment]
I'll give you a better example. Those are the RAW formats supported by ImageMagick
* arw
* cr2
* dcr
* dng
* erf
* iiq
* kdc
* k25
* nef
* mef
* orf
* rw2
* pef
* raf
* srf
* sr2
* xrf

You can't just pick one

**Comment by oparoz** [comment]
cc @georgehrke

**Comment by oparoz** [comment]
Updated the OP to better describe the problem

**Comment by PVince81** [comment]
Moving to 8.2 (enhancement)

**Comment by PVince81** [comment]
Moving to 9.0 as we're past feature freeze
