### ISSUE TITLE
Broken breadcrumbs if backslahes are used in the URL

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#13643]
![broken-breadcrumbs](https://cloud.githubusercontent.com/assets/245432/5884006/17226728-a358-11e4-8bd7-9a884878c9d3.png)

The correct folder is shown, but the breadcrumbs aren't available for URLs that contain backslashes instead of slashes.

**Comment by LukasReschke** [comment]
Good call. Was annoyed by this as well by some Windows users on S3 ;-)
