### ISSUE TITLE
Storage based path validation

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#13640]
-    the server is the only authority to apply any kind of rules
-    duplicating any kind of rule processing will duplicate development effort and processing effort in production
-    upload processing has to be adopted to apply rules BEFORE the data transmission to allow early abort (e.g. invalid file name, invalid file ext, not enough space ..)

Should be handled in different issues:
-    upload processing also can be aborted DURING data transmission - e.g. virus signature detected
-    upload processing also can be aborted AFTER data transmission - e.g. ???

**Comment by DeepDiver1975** [comment]
refs https://github.com/owncloud/core/issues/12015#issuecomment-62686429

**Comment by PVince81** [comment]
How about using the file mapper (once merged into oc_filecache) to rename the problematic files to an acceptable name ? Unless that itself is already too much hassle.

**Comment by DeepDiver1975** [comment]
That might be a solution for some cases - but honestly the file mapper is still not working really great.
(no offence @nickvergessen - issue are in the initial design - which was my fault :wink: )

Furthermore I question if this is a solution for all cases.

I'm even thinking about a hooking to the path validation regarding the used database. E.g. don't allow 4-byte UTF-8 chars on mysql.

**Comment by DeepDiver1975** [comment]
> We need to find a way to enhance the webdac xml response - I will have a look at this

We have the possibility to add additional xml elements to the response.
To achieve this we need to define your own sabre dav exceptions and implement the serialize method - like this: https://github.com/fruux/sabre-dav/blob/master/lib/DAV/Exception/Locked.php#L57

I suggest to add two nodes as requested by @danimo:

```xml
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:o="http://owncloud.org/ns">
  <s:sabredav-version>2.0.3</s:sabredav-version>
  <s:exception>OCP\DAV\Exception\InvalidPath</s:exception>
  <s:message>The file extension 'exe' is not allowed.</s:message>
  <o:retry>false</o:retry>
  <o:reason>The file extension 'exe' is not allowed.</o:reason>
</d:error>

**Comment by DeepDiver1975** [comment]
@danimo @dragotin we have to come up with a proper http status code for this scenario

**Comment by LukasReschke** [comment]
Code is merged in current master.

**Comment by DeepDiver1975** [comment]
> Code is merged in current master.

THX

We need follow up issues with this - every storage implementation has to handle the path verification according to it's specs.

**Comment by PVince81** [comment]
Move to 8.2 ?

**Comment by DeepDiver1975** [comment]
> Move to 8.2 ?

yes - we should create one for each storage implementation

**Comment by PVince81** [comment]
@DeepDiver1975 move to 9.0 ?

**Comment by brevilo** [comment]
Oh no. Please keep in mind that this one is prerequisite for https://github.com/owncloud/client/issues/3406 if I'm not mistaken. OwnCloud is unusable for many Linux/Mac users like me who expect their sync folder contents be synced, regardless of Windows' file name constraints. Thanks.

**Comment by nickvergessen** [comment]
@brevilo that is not related to this story here on the server repository

**Comment by brevilo** [comment]
Ok, in that case just ignore my comment :+1:

**Comment by DeepDiver1975** [comment]
> yes - we should create one for each storage implementation

I'll open individual issues
