### ISSUE TITLE
Paged search for LDAP backend seems broken

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#13644]
This is an issue I noticed once and need to verify again.
![broken-ldap-paged](https://cloud.githubusercontent.com/assets/245432/5884040/7d28ff6e-a358-11e4-9ff3-7e830912a175.png)

The first request has an offset of 5 and a limit of 10 and it just returns 5 elements. The next requests had an offset of 8 and a limit of 10 and returned 2. It seems that limit is not the count but the position. I need to debug this. Or maybe @blizzz knows the cause.

**Comment by karlitschek** [comment]
@blizzz

**Comment by blizzz** [comment]
Wow, how do you get to this point at all? I mean, if you fetch 10 from the beginning and there are only 4 or 5 retrieved, why/how do you start fetching more result?

**Comment by blizzz** [comment]
And how and why is it followd by an offset of 8!?

**Comment by MorrisJobke** [comment]
I didn't know. I will check again later

**Comment by MorrisJobke** [comment]
@blizzz It's still valid. No more users are loaded. Now I get as the second request: offset 21 and limit 10 -> 0 results

If I manipulate the request to offset 8 and limit 10 I get 2 results.

@blizzz Can you have a look at this?

@karlitschek @DeepDiver1975 I will rate this as showblocker until @blizzz has proven the opposite.

**Comment by blizzz** [comment]
Yes, i will have a look. @jnfrmarks and I have also seen strange behaviour late on Friday that might be connected.

**Comment by karlitschek** [comment]
@jnfrmarks Can you help here?

**Comment by jnfrmarks** [comment]
@blizzz @MorrisJobke 

I'm not sure what needs to be tested here.  What was the original issue and what are the steps to reproduce it?  Is there any risk to other areas of LDAP that need to be tested due to this fix?

**Comment by blizzz** [comment]
@jnfrmarks I just opened a PR for this: #13897
