### ISSUE TITLE
Remove jQuery tipsy in favor of Bootstrap tooltips

### ISSUE THREAD

**Issue by Raydiation** [owncloud/core#13646]
jQuery tipsy is unmaintained ([last commit 2012](https://github.com/jaz303/tipsy/commits/master)), does not work with up to date jQuery which forces us to ship jquery-migrate and has several bugs that are not present in the [Bootstrape equivalent](http://getbootstrap.com/javascript/#tooltips)

Migrating should not be hard, most of the time it will only amount to replacing

    $('#element').tipsy()

with

    $('#element').tooltip()

@PVince81 @jancborchardt @LukasReschke @DeepDiver1975 @MorrisJobke

**Comment by MorrisJobke** [comment]
I will have a look at this for 8.1

**Comment by MorrisJobke** [comment]
ref #12877

**Comment by Raydiation** [comment]
Yep :) it was the first thing that did not work after removing jquery-migrate :)

**Comment by DeepDiver1975** [comment]
fine with me - please add a tipsy() function for backwards compatibility

**Comment by Xenopathic** [comment]
There is a Tipsy fork that is maintained (https://github.com/CloCkWeRX/tipsy), and seems to fix all the problems with compatibility and the bugs mentioned. It might still be best to migrate to Bootstrap though.

**Comment by LukasReschke** [comment]
Mhm. Would prefer some widely used library instead of something unofficial with less than 30 stars on GH.

**Comment by Raydiation** [comment]
@Xenopathic we could try to use the fork as a shortterm solution, as in to get rid of jquery migrate if we do not have to make adjustments

**Comment by jancborchardt** [comment]
Yeah, sounds best to remove to the Bootstrap tooltip library. Good call @Raydiation

**Comment by Henni** [comment]
@MorrisJobke are you working on this? If not I will take a look at this.

**Comment by MorrisJobke** [comment]
@Henni Feel free to do so :)
