### ISSUE TITLE
Access restriction to data and config folder

### ISSUE THREAD

**Issue by mapaongh** [owncloud/core#13657]
Problem: 

The data and the config folder are protected via an .htaccess file. The change from Apache 2.2 to 2.4 causes a refactoring of authorization process. To capture this a new template for .htaccess was delivered with ownclud.

### Expected behaviour
If I try to get access via the browser

www.myowncloud.com/data/owncloud.db

I would expect two things:

In the browser: "Forbidden"
In the LogFile: ... [authz_core .... client denied by server configuration: ... data/owncloud.db

### Actual behaviour

In the browser: "Forbidden"
In the LogFile: ... [access_compat .... client denied by server configuration: ... data/owncloud.db

This means that not the "Require all denied" is used but the "Deny from all". This can be seen in the module (mod_access_compat) capturing htaccess statement. 

In case mod_access_compat is not loaded I think it can lead to a security problem.

### Server configuration
Apache 2.4
Owncloud 7.0.4

## Solution:

I investigated a bit and found out that within the IfModule Statement the .c is missing. It should be written:
```
<ifModule mod_authz_core.c>
Require all denied
</ifModule>
```

instead of 

```
<ifModule mod_authz_core>
Require all denied
</ifModule>
```

Can you agree?

**Comment by LukasReschke** [comment]
Agreed. Though we have a check in place that checks whether the data folder is reachable publicly so if the shipped `.htaccess` does not work a warning is shown to the admin so that he is aware of that fact.

Should get changed anyways. Assigning to myself.

**Comment by nickvergessen** [comment]
the `.htaccess` in root has some similar issues:
```
<IfModule dir_module>
...
<IfModule pagespeed_module>
```
