### ISSUE TITLE
Supporting the Raw image format (digital negatives)

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#13650]
The RAW image format is popular among photographers and what better than a cloud to store all these shots online to preview and share them?
The problem is that there isn't a standard like for PNG or JPEG. Most are based on TIFF, but use different headers.

Here is the list of formats supported by ImageMagick:
* Sony Alpha RAW .arw
* Canon RAW 2 .cr2
* Digital Camera Raw .dcr
* Digital Negative .dng
* EPSON RAW .erf
* Intelligent Image Quality RAW .iiq
* Kodak DC40/DC50 RAW .kdc
* Kodak DC25 RAW .k25
* Nikon RAW .nef
* Mamiya RAW .mef
* Olympus RAW .orf
* Panasonic RAW .rw2
* PENTAX RAW .pef
* Fujifilm RAW .raf
* Sony RAW File .srf .sr2
* SIGMA RAW .xrf

I've implemented support for CR2 and DNG, but I'm calling for experts to voice their opinion on whether we should support all extensions or not.

**Comment by oparoz** [comment]
cc @georgehrke @jancborchardt

**Comment by RealRancor** [comment]
Some refs for existing requests: https://github.com/owncloud/apps/issues/1113, https://github.com/owncloud/apps/issues/439

**Comment by oparoz** [comment]
Thanks @RealRancor :)

PR available here: https://github.com/owncloud/core/pull/13652

**Comment by PVince81** [comment]
Linking your new PR here: https://github.com/owncloud/core/pull/14878

Moving to 8.2

**Comment by oparoz** [comment]
Providers are no longer accepted in core. This may be available in the future as a patch or an app.
