### ISSUE TITLE
OC 7.0.4 android default browser logout at web interface not working.

### ISSUE THREAD

**Issue by SISolutions** [owncloud/core#13656]
Fresh Installation OC 7.0.4 at a mint 17 xfce 32bit.
Web server apache
MariaDB/MySQL

Loging in from android (from ver 4 and up as i have tested) default browser to OC 7.0.4 web interface there is no option to logout. The right corner button not working.You click and nothing happens.

**Comment by RealRancor** [comment]
Hi,

try the fix in: https://github.com/owncloud/core/pull/12798 which should give you the dropdown menu in the right corner back.

**Comment by RealRancor** [comment]
@SISolutions 
Ping. Have you tried the mentioned/linked fix?

**Comment by SISolutions** [comment]
Hello,

yes it solved my problem.

will you or i will mark it at github like soved ?

Thank you.

John Pagourtzis | SISolutions
jp@sisolutions.gr
http://sisolutions.gr

**Comment by RealRancor** [comment]
Hi,

i don't have any permissions but you could close it yourself.

**Comment by SISolutions** [comment]
Οκ thanks.

John Pagourtzis

**Comment by DeepDiver1975** [comment]
fixed with 7.0.5 then - THX
