### ISSUE TITLE
Using php_sapi_name() does not detect CLI reliably

### ISSUE THREAD

**Issue by jakobsack** [owncloud/core#13651]
Hi,

using ```php_sapi_name() == 'cli'``` does not detect the usage of the CLI reliably.
If you call ```$ php -f cron.php``` and /usr/bin/php is a symlink to *php-cgi* the SAPI will be "cgi-fcgi". One webhoster with this problem is 1&1.

This bug could be related to #7715 and #11551

Possible solutions:

1. Find additional ways to detect the usage of the CLI
  - pro: Our users do not have to care about the setup
  - con: Does the new solution hit every corner case?

2. Use the full path to the "real" php executable in cron job.
  - pro: nothing left to do for owncloud coders
  - con: it could be hard for unexperienced users to determine the real path

3. Create a workaround using environment variables
  - pro: very easy to code
  - con: users have to hit the error, find the solution (using environment variables) and apply it

Personally, I do favor solution 1. Doing a quick research shows that ```$_SERVER[HTTP*]``` and ```$_SERVER[REMOTE*]``` are visible when using apache+modphp but not when calling php or php-cgi from command line.

Please test if this assumption is true for other setups (lighttpd, nginx, apache+cgi). You can use the following code:

```php
<?php
echo php_sapi_name();
echo "\n";
var_dump( $_SERVER );
```

jakob

**Comment by jakobsack** [comment]
If there is enough positive feedback I'll create a patch on monday.

**Comment by MorrisJobke** [comment]
Is there no `php-cli` installed on those hosts?

**Comment by jakobsack** [comment]
I don't know, it's not me having this problem. I'll ask the one who contacted me

**Comment by jakobsack** [comment]
php-cli worked. I'll integrate this in the documentation.
