### ISSUE TITLE
findBinaryPath can't immediately find new binary locations

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#13658]
https://github.com/owncloud/core/pull/13192 introduced a nice speed up, but it needs to be updated to make sure that any change in binary and binary location is picked up.

#### Example scenario
* User enables movie previews
* Helper can't find the binaries and stores null values in memcache
* User installs ffmpeg
* Helper never bothers to look and always returns null values
* User won't be able to see his videos until the memcache key expires and may think something is wrong

```
public static function findBinaryPath($program) {
	$memcache = \OC::$server->getMemCacheFactory()->create('findBinaryPath');
	if ($memcache->hasKey($program)) {
		return $memcache->get($program);
	}
```

Only tested on master, with encryption enabled

**Comment by Xenopathic** [comment]
What about clearing all caches with a special button in the admin settings? It would also clear non-memcache caches, like generated assets, so it would be very useful in a variety of circumstances. I know that Drupal does this, and I expect other web applications to do the same. Then all that is needed is a note in the documentation that any changes to software on the server may require a cache clear to take effect.

**Comment by oparoz** [comment]
@Xenopathic - Exactly what I was thinking. Otherwise we lose the advantage of caching the path in the first place.

**Comment by Xenopathic** [comment]
I'll write something up tomorrow. @DeepDiver1975 I guess this qualifies as an oC 8 issue, given that the offending code is already in master?

**Comment by nickvergessen** [comment]
Well since the problem resolves itself in 1 hour, I guess documentation + fix in 8.0.1/8.1 should be enough

**Comment by Xenopathic** [comment]
So, what's the conclusion on this? The only way I can see this working properly is through a 'Clear caches' button in the admin settings, since ownCloud cannot detect external changes.

**Comment by oparoz** [comment]
I ran into the issue a few times and it's frustrating because you have to wait or patch the code. If a button is too time consuming to create, then maybe there can be an occ command?

**Comment by Xenopathic** [comment]
@oparoz We already have an implementation in a PR: #18475

**Comment by nickvergessen** [comment]
@Xenopathic as said multiple times that is not going to happen...

**Comment by oparoz** [comment]
So @nickvergessen , you're just going to tell admins to sit around for an hour?

**Comment by nickvergessen** [comment]
As per Frank in the PR: https://github.com/owncloud/core/pull/18475#issuecomment-139375751
> Maybe a combination of shorter TTL or an automatic cache cleanup when a restart is detected.

**Comment by oparoz** [comment]
Shorter TTL is a bad compromise. It defeats the purpose of storing the information in the cache.

And I don't understand what a restart means in this context? Apache restart? If yes, then it's a good solution.

**Comment by karlitschek** [comment]
I think a TTL of , for example, 3min is a good compromise. An admin might take that time to install a new tool anyway and the performance impact is minimal. A cache clear button is not better. People will click this randomly and an admin has to know that this button needs be be clicked too.
I think a short TTL provides the best automatic solution

**Comment by DeepDiver1975** [comment]
lets think about this in the scope of 9.0 again ... we have more important things to do

**Comment by PVince81** [comment]
How to move forward with this regression ?

> Apache restart? If yes, then it's a good solution.

If an Apache restart is acceptable, then is there anything left to be done here ? @oparoz @Xenopathic

**Comment by oparoz** [comment]
> If an Apache restart is acceptable, then is there anything left to be done here ? 

Everything is left to be done since a restart by itself doesn't do anything. It needs to be detected by ownCloud which will then wipe these specific keys.

**Comment by Xenopathic** [comment]
Since we don't want to introduce a 'Clear caches' button, I think the only solution will be to change the TTL to a smaller value, e.g. 5 minutes

**Comment by PVince81** [comment]
@Xenopathic any update ? So the TTL is the right approach then ?

**Comment by Xenopathic** [comment]
@PVince81 Probably. I'm still in favour of an explicit button that clears *all* caches that ownCloud has generated, be that memcache, assets etc. *just in case*, though.
