### ISSUE TITLE
Admin Console showing "accessing via HTTP" error when using HTTPS (w/ reverse proxy terminating SSL)

### ISSUE THREAD

**Issue by pastudan** [owncloud/core#13659]
### Steps to reproduce
1. Set up a reverse proxy (nginx or similar)
2. Terminate SSL
3. Forward plaintext requests to owncloud server

### Expected behaviour
No error

### Actual behaviour
Receive error in Admin Console: "You are accessing ownCloud via HTTP. We strongly suggest you configure your server to require using HTTPS instead."

### Server configuration
Initial HTTPS request comes in via nginx, is decrypted, and is passed along to the owncloud VM (apache) in plaintext.

**Operating system**:
Ubuntu 14.04

**Web server:**
nginx (ssl) -> apache

**Database:**
n/a

**PHP version:**
n/a

**ownCloud version:** (see ownCloud admin page)
7.0.4 stable

**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
none

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
yes

**Comment by DeepDiver1975** [comment]
@LukasReschke thx

**Comment by LukasReschke** [comment]
That is the expected behaviour, you have several possibilities to address this:

1. Configure your reverse proxy properly to support `X-Forwarded-Proto`
2. Set `overwriteprotocol` in `config/config.php` to https

Nothing we can do on our site => Configuration error

**Comment by LukasReschke** [comment]
Also documented at http://doc.owncloud.org/server/7.0/admin_manual/configuration/reverse_proxy_configuration.html

**Comment by pastudan** [comment]
OK, sorry. I tried searching pretty extensively and asking in IRC but
somehow missed that. Thanks for the help!
