### ISSUE TITLE
Cannot download encrypted file version after moving to external storage

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13668]
### Steps to reproduce
1. Enable encryption, external storage and files locking app
2. Log out then log in again
3. Mount a SFTP external storage to "/sftp"
4. Create a text file in the home root: "test.txt"
5. Edit the text file several times to create versions
6. Check the versions dropdown to have at least 3 versions
7. Check that an older version can be downloaded
8. Now move "test.txt" to "/sftp"
9. Check the versions dropdown
10. Download a version

### Expected result
Versions can be downloaded, preview looks alright.

### Actual result
Version file is still encrypted after download. The text preview thumbnail shows an encrypted content.
I haven't tried without the locking app, but suspect that it might happen without it too.

### Versions
Happens on OC 8 master (f8b1fde2c06575de79035f6690bda8a24c9802e9)
and on OC 7 stable7 (80560e70b7133739f87cf6a03acb55169fb2462f)

### Logs
Log (with the files_locking entries removed as it is too long)
```
{"reqId":"54c642d56a206","app":"PHP","message":"ob_end_clean(): failed to delete buffer. No buffer to delete at \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/view.php#269","level":0,"time":"2015-01-26T13:36:21+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files_versions\/download.php?file=%2Fsftp%2Fv2.txt&revision=1422279013"}
```

@schiesbn

**Comment by davitol** [comment]
:+1: fixed
