### ISSUE TITLE
Get rid of `octemplate.js`

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#13661]
We really need to get rid of `octemplate.js` which is some custom templating system only used by contacts but lives in core.

There are better and maintained template systems…

**Comment by DeepDiver1975** [comment]
octemplate.js is used in oc-dialogs and tags.js

**Comment by MorrisJobke** [comment]
As @ChristophWurst is cleaning up JS stuff recently - maybe he wants to look into this too ;)

**Comment by DeepDiver1975** [comment]
> only used by contacts but lives in core.

:skull: with :fire: :tada:

**Comment by PVince81** [comment]
need to move the existing html templates to handlebars and load those instead

**Comment by PVince81** [comment]
backlog for now.

@felixheidecke might provide some new dialogs at some point so we could rewire the OC.dialogs function to those for a seamless experience, and once we have this we can kill the old templates.
