### ISSUE TITLE
Files with a + sign in the name are not synchronized by Windows Client.

### ISSUE THREAD

**Issue by scs-tech** [owncloud/core#13665]
This appears to be the same error as reported (and closed) with bug #4568
Problem does not appear to be fixed (or has come back).

Steps to Reproduce:
1) Create a file "file+name.txt" on windows client
2) Create a file "file-name.txt" on windows client
3) Copy both files to the synced folder.

Expected behavior:
Both files should sync to OC

Actual behavior:
'File-name.txt' will sync fine, 'file+name.txt' will not sync.
Error in client activity log is:
Error Downloading Https://my.domain.com/remote.php/webdav/file+name.txt - server replied: Not Found

Environment:
 Fresh install
 Server: Windows 2012 R2, IIS 8.5, OwnCloud 7.0.4, PHP 5.6.0, MySQL 

 Client: Windows 2012 R2, OwnCloud Client 1.7.1 (build 4382)

**Comment by nickvergessen** [comment]
Moved to the client tracker:
https://github.com/owncloud/client/issues/2747

**Comment by danimo** [comment]
Why? This works with Linux, so it's a bug in the Windows normalization layer or in the deployment // cc @DeepDiver1975

**Comment by LukasReschke** [comment]
This looks like a platform specific bug on the Windows file mapper. As you might know with ownCloud 8.1 we will not support the MS Windows Platform as a server anymore officially as nobody maintained it really, see https://owncloud.org/blog/owncloud-server-8-1-will-not-support-windows-as-server-platform-natively/

Sorry for the inconvenience that this caused and thanks a lot for your bug report. You would be best of by migrating your instance to a Linux server.
