### ISSUE TITLE
*.odt-viewer shows old versions, editor shows current ones

### ISSUE THREAD

**Issue by splashote** [owncloud/core#13662]
Hi,

we're using the current Owncloud version and experienced problems regarding shared *odt-files.

The viewer shows old versions of the files while the editor worked alright.

Is this a known issue? Any suggestions how to fix this?

Thanks!

**Comment by nickvergessen** [comment]
Please use the issue template:
https://raw.githubusercontent.com/owncloud/core/master/issue_template.md
