### ISSUE TITLE
Guessing "Enter remote user syntax" for S2S share is bad UX

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#13678]
When you use the "Add to my owncloud" field to mount a public share into another instance, it accepts almost any URL:
```
http://localhost/ownCloud/Master/index.php
http://localhost/ownCloud/Master/
http://localhost/ownCloud/Master
localhost/ownCloud/Master/index.php
localhost/ownCloud/Master/
localhost/ownCloud/Master
etc.
```

However, when trying to add a remote share via the share dropdown, you have to:
1. Guess that `<username>@<instance>` is the remote syntax
2. that `<instance>` MUST be the last of the list above.

We need a hint about the first thing in the UI and should fix the remote guessing to strip away `http://` and `/index.php(.*)` so all of those URLs listed above work

@jancborchardt for the UI hint
@schiesbn for s2s
@jnfrmarks for testing full URL insertions

**Comment by PVince81** [comment]
CC @owncloud/designers

**Comment by LukasReschke** [comment]
Just as a side note that is REALLY annoying… – I had to fight with that today and noticed it does not work with trailing slash……

**Comment by PVince81** [comment]
It should after https://github.com/owncloud/core/issues/13677, at least with the format "user@host/owncloud/"

**Comment by LukasReschke** [comment]
admin@localhost/core**/** fails admin@localhost/core works

**Comment by schiesbn** [comment]
"http://" already gets stripped away. I think this is mainly a documentation issue to tell people that they can address remote ownClouds like email addresses "user@domain", I don't see a reasons to support every kind of URLs and start guessing the right one by stripping "random" parts of the URL.

**Comment by DeepDiver1975** [comment]
link pr for master not yet merged - possible backport with 8.0.2

**Comment by MorrisJobke** [comment]
@nickvergessen Reopened, because this is planned for 8.0.3 - please open a backport PR

**Comment by MorrisJobke** [comment]
merged
