### ISSUE TITLE
Versions lost when moving file into shared folder as recipient

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13671]
### Steps to reproduce
1. Create two users "user1" and "user2".
2. As "user2" share a folder "test" with "user1"
3. Login as "user1"
4. Create a file "versions.txt"
5. Edit and save the file multiple times to create versions
6. Check the versions dropdown for versions
7. Move the file "versions.txt" into "test"
8. Check the versions dropdown for "test/versions.txt"

### Expected result
Versions preserved

### Actual result
Versions not preserved. The version files are still in the home of "user1"

### Versions
Happens in 7.0.4, stable7 (80560e70b7133739f87cf6a03acb55169fb2462f) and master (f8b1fde2c06575de79035f6690bda8a24c9802e9)

Note: not related to the trashbin wrapper change since it happened before.

@schiesbn

**Comment by PVince81** [comment]
@DeepDiver1975 @karlitschek please evaluate severity. I'll set to 8.1 for now but we might want to have this earlier.

**Comment by karlitschek** [comment]
8.1 is fine

**Comment by PVince81** [comment]
Closing as duplicate of https://github.com/owncloud/core/issues/13307
