### ISSUE TITLE
Add OCS capability to advertise whether a server allows public links

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13673]
`curl http://root:admin@localhost/owncloud/ocs/v1.php/cloud/capabilities`

Add a new attribute that tells whether public sharing is enabled.

@guruz @icewind1991 @schiesbn

**Comment by PVince81** [comment]
CC @rperezb @dragotin as this info can be interesting for the mobile and desktop clients

There's a PR from @rullzer here: https://github.com/owncloud/core/issues/13692

**Comment by rperezb** [comment]
Thanks @PVince81, indeed it is.

**Comment by MTRichards** [comment]
If/when we get a fix, can we get a backport to 8.0 and 7.0.5 please? This is key for the mobile and desktop - as well as the info on whether a password is required for public links.

**Comment by rullzer** [comment]
@MTRichards I did not test it (yet) but I think my PR can be trivially backported to 7.0.5.
As for 8.0 it works against the current master.

**Comment by MTRichards** [comment]
Awesome sauce. Does it also advertise if a public link requires a password?

**Comment by rullzer** [comment]
Yes, and if we allow public uploads. The rest can be added as well (default expire date etc).
However there was some discussion where it had to be placed in the capabilitie

**Comment by davivel** [comment]
Sorry, Matt, we messed this a bit before. From the client POV would be great to have this backported, but is not really necessary for the problem we talked about.

The key point is in my comment in https://github.com/owncloud/client/issues/2774#issuecomment-72872210 .

Thanks.

**Comment by dragotin** [comment]
I think the capabilities API should provide the followiing information, based on @rullzer s pull request:

1. Public link sharing enabled yes/no (already in the patch)
2. Password required (already in the patch)
3. Default expiration date yes/no, if set, the duration in days
4. Expiration date enforced yes/no
5. Mail sending for public link shares yes/no
6. Mail sending for user/group sharing yes/no
7. Restrict sharing to own group yes/no
8. Allow sharing to groups yes/no

No. 7. and 8. could also be handled by a server API that returns the list of users/groups that the client is allowed to share to.

We will currently not need the public upload information.

**Comment by rullzer** [comment]
@dragotin I'll add 3-6 when I have some time (hopefully tonight but otherwise during the weekend)

As for 7 and 8 I agree they are probably mostly usefull in a seperate API since a client can't do anything with that info. But I have a PR #13587 for that well.

Still leaves the issue where to place it in the capabilities? Is the files section good or should it be more global?

**Comment by MTRichards** [comment]
Ok - so this is for ownCloud 8.0.1 right?

NOT 8.1? Tag says 8.1.
Too many tickets on this problem, and 1.8 is waiting on this.

**Comment by LukasReschke** [comment]
> Too many tickets on this problem, and 1.8 is waiting on this.

Well… maybe this should have then be better communicated before relying in the client on some API that does not yet exist… – I thought we agreed on only backporting critical bugfixes once…

**Comment by MTRichards** [comment]
This happens sometimes. :/

The important thing is we have a bug/feature (is that a fug?) and it is relatively important to fix.

Core issues:
- Client: https://github.com/owncloud/client/issues/2774
- Mobile: https://github.com/owncloud/ios/issues/283

**Comment by PVince81** [comment]
Next time I will be careful to not advertise ideas that late before the release.

**Comment by karlitschek** [comment]
@MTRichards @craigpg We have to discuss and merge something like that way earlier in the cycle. aka FeatureFreeze

**Comment by MTRichards** [comment]
Ok.
Still, 8.0.1? 
:smile:

**Comment by DeepDiver1975** [comment]
> Still, 8.0.1?

To be honest and precise: if we agree on walking this path - I'm not yet fully convinced. Just started to think about this and talk to people.

Please understand that ANY change to ANY-thing which is API-like has big impact on our maintenance effort. The best API to support and maintain is the one we never need/use/implement (e.g. no need to have capabilities for thumbnails)

**Comment by MTRichards** [comment]
I think I should also be clear...
I don't mean we need this API to solve this, maybe we do something different - https://github.com/owncloud/client/commit/4849c31addc1d1c6b9a45a5487c22511d5cac83c .  
Bottom line is we just need some fix.

I don't want to proscribe an answer, and this particular issue is a technical proscription, I just work with priorities and requirements.

**Comment by karlitschek** [comment]
@DeepDiver1975 do you think we can come up with a pull request for an API like that?
We can discuss tomorrow if you want.

**Comment by rullzer** [comment]
@DeepDiver1975 well I'm fine with any other implementation really. Could also be a new function in the share API. However this approach looked cleaner to me.

**Comment by rullzer** [comment]
This is fixed with #13964. So closing.
The info is now exposed. The info might be extended in the future. But that should go in a different issue.
