### ISSUE TITLE
Share versions in server to server sharing scenario

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13672]
Whenever "user1" mounts a remote share from "user2", they should both get access to the list of versions.

Note: this might require adding new APIs for versions to make it possible to remotely:
- get the list of versions to display them in the dropdown
- download a specific version
- revert to a specific version

Also operations like moving a local file into the share should also preserve / copy the versions to the owner's ownCloud (since versions are always stored at the owner's place)

@owncloud/designers @schiesbn @icewind1991

**Comment by DeepDiver1975** [comment]
We should definitly elaborate webdav for this - either by introducing a new resource or by implementing version capabilities as specified in https://www.ietf.org/rfc/rfc3253.txt

**Comment by PVince81** [comment]
Will require proper APIs: https://github.com/owncloud/core/issues/10571

**Comment by PVince81** [comment]
Will be possible with storage specific versions: https://github.com/owncloud/core/issues/12274
