### ISSUE TITLE
Error 404 when trying to download a file from external 'local' storage

### ISSUE THREAD

**Issue by gagou9** [owncloud/core#13670]
Hello,

### Steps to reproduce
0. nginx is configured to enable downloads resume
1. Add a local storage
2. Add the owncloud php user to the group that owns the storage
3. Add the nginx (in my case) user to the group that owns the storage
4. Make sure the groups permissions let owncloud and nginx access the files

### Expected behaviour
Files should be downloadable from OC interface

### Actual behaviour
404 error.

### Server configuration
**Operating system:** Debian/Linux Wheezy

**Web server:** nginx 1.6.2

**Database:** mariaDB 10.0.15

**PHP version:** 5.4.36

**ownCloud version:** 7.0.4

**Updated from an older ownCloud or fresh install:** Upgraded, but using the "delete everything exept [some files and folders]" method

**List of activated apps:** Activity, Calendar, Contacts, Deleted files, Documents, External storage support, First Run Wizard, Full Text Search, Mail Template Editor, PDF Viewer, Pictures, Share Files, Text Editor, Updater, Versions, Video Viewer

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '522f03799df90',
  'passwordsalt' => 'lolsalt',
  'datadirectory' => '/home/owncloud/www/data',
  'dbtype' => 'mysql',
  'version' => '7.0.4.2',
  'installed' => true,
  'loglevel' => '2',
  'logtimezone' => 'Europe/Paris',
  'logfile' => '/home/owncloud/logs/owncloud.log',
  'log_authfailip' => true,
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' => 
  array (
    0 => 'URL Changed',
  ),
  'mail_smtpmode' => 'smtp',
  'forcessl' => true,
  'mail_smtpsecure' => 'tls',
  'mail_from_address' => 'me',
  'mail_domain' => 'mydomain.tld',
  'mail_smtpauth' => true,
  'mail_smtphost' => 'mail.mydomain.tld',
  'mail_smtpport' => '25',
  'mail_smtpname' => 'me',
  'mail_smtppassword' => 'mypassword',
  'mail_smtpauthtype' => 'LOGIN',
  'dbname' => 'owncloud_db',
  'dbhost' => '127.0.0.1',
  'dbuser' => 'owncloud_user',
  'dbpassword' => 'lolpassword',
  'secret' => 'thisWasMyFreakingSecret',
);
```

**Are you using external storage, if yes which one:** local, and FTP but that works

**Are you using encryption:** The app ? no.     HTTPS? yes

### Client configuration
**Browser:** firefox last stable, chromium last stable

**Operating system:** archlinux

#### Web server error log
```
2015/01/26 14:06:32 [error] 17575#0: *1959 open() "/home/owncloud/www/data/gagou9/files/Transmission-Files/downloads/debian-7.6.0-kfreebsd-i386-xfce-CD-1.iso" failed (2: No such file or directory), client: xxx.yyy.zzz.aaa, server: mydomain.tld, request: "GET /index.php/apps/files/ajax/download.php?dir=%2FTransmission-Files%2Fdownloads&files=debian-7.6.0-kfreebsd-i386-xfce-CD-1.iso HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm/owncloud.sock", host: "mydomain.tld"
```

#### ownCloud log (data/owncloud.log)
```
{"app":"PHP","message":"iconv(): Detected an illegal character in input string at \/home\/owncloud\/www\/apps\/search_lucene\/3rdparty\/Zend\/Search\/Lucene\/Analysis\/Analyzer\/Common\/TextNum.php#58","level":3,"time":"2015-01-19T01:45:04+01:00"}
{"app":"PHP","message":"iconv(): Detected an illegal character in input string at \/home\/owncloud\/www\/apps\/search_lucene\/3rdparty\/Zend\/Search\/Lucene\/Analysis\/Analyzer\/Common\/TextNum.php#58","level":3,"time":"2015-01-22T01:45:03+01:00"}
{"app":"PHP","message":"iconv(): Detected an illegal character in input string at \/home\/owncloud\/www\/apps\/search_lucene\/3rdparty\/Zend\/Search\/Lucene\/Analysis\/Analyzer\/Common\/TextNum.php#58","level":3,"time":"2015-01-23T17:00:04+01:00"}
{"app":"PHP","message":"iconv(): Detected an illegal character in input string at \/home\/owncloud\/www\/apps\/search_lucene\/3rdparty\/Zend\/Search\/Lucene\/Analysis\/Analyzer\/Common\/TextNum.php#58","level":3,"time":"2015-01-23T17:00:06+01:00"}
{"app":"PHP","message":"iconv(): Detected an illegal character in input string at \/home\/owncloud\/www\/apps\/search_lucene\/3rdparty\/Zend\/Search\/Lucene\/Analysis\/Analyzer\/Common\/TextNum.php#58","level":3,"time":"2015-01-24T21:30:02+01:00"}
{"app":"PHP","message":"Array to string conversion at \/home\/owncloud\/www\/lib\/private\/l10n\/string.php#57","level":3,"time":"2015-01-26T14:33:08+01:00"}

```

Maybe the problem is on my side, but I couldn't find anything. The problem might be due to the downloads resume thing, but I don't really think so as it works everywhere else!

Thanks a lot!

**Comment by PVince81** [comment]
It is very likely to be an issue on your side. Are you using the "X-Sendfile" approach ? If yes you'll need to add additional entries for those external storages.
Can you post your nginx config ?

@josh4trunks might be able to help :smile:

**Comment by josh4trunks** [comment]
yes, please follow the documentation for your local storage mountpoint.
http://doc.owncloud.org/server/7.0/admin_manual/configuration/xsendfile.html#id4

If it's still not working post you nginx config and I can take a look.

**Comment by gagou9** [comment]
Pouah i'm very sorry I didn't see that small part about Local mount points when I enabled X-sendfile ...

It works now, thanks a lot!

**Comment by josh4trunks** [comment]
great, glad it's working
