### ISSUE TITLE
Search results only found in .pdf and .odt files 

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#13685]
### Steps to reproduce

1. Install owncloud
2. Upload a .txt file that contains the word owncloud (or, create one locally)
3. Upload a pdf file that contains the word owncloud
4. upload a doc/docx file that contains the word owncloud
5. upload an xlsx file that contains the word owncloud
6. upload an odt file that contains the work owncloud
7. enter owncloud in the search box

### Expected behaviour

Expect results to contain all files

### Actual behaviour

Results contain only odt and pdf files

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration

ownCloud Enterprise Edition 8.0 beta 2 (testing)

**Comment by LukasReschke** [comment]
search_lucene is enabled?

**Comment by LukasReschke** [comment]
Also issue might better suit to https://github.com/owncloud/search_lucene/

**Comment by PVince81** [comment]
@butonic

**Comment by DeepDiver1975** [comment]
@butonic please have a look if time permits - if not please ping me - THX

**Comment by PVince81** [comment]
Works for me on core master (4d90fd933f47c71b4b9ff333b223f06822bc5340) and search_lucene master (0ab731440d8b53302d55d938dccfdc332560fe85), I saw it indexing the XLS file with a breakpoint.

Did you put some files on an external storage ? Just asking because I saw the indexer code only working with local files.

**Comment by PVince81** [comment]
To clarify, I also saw the XLSX file appearing in the result list.

**Comment by DeepDiver1975** [comment]
@PVince81 afaik - we are talking about search_elastic here ...

**Comment by PVince81** [comment]
Then the bug should be raised in the corresponding repository

**Comment by jnfrmarks** [comment]
I'll re-test and move/update this issue accordingly.

**Comment by nickvergessen** [comment]
Reported in https://github.com/owncloud/search_lucene/issues/55 since it's not a core issue (core has no content search)

**Comment by jnfrmarks** [comment]
See https://github.com/owncloud/core/issues/13687#issuecomment-72069043
