### ISSUE TITLE
s2s single file share doesn't update for recipient through syncing when changed by owner

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13688]
### Steps to reproduce
1. Setup two users "user1" and "user2"
2. Login as "user1"
3. Create a non-empty text file "test.txt"
4. Share "test.txt" with "user2@localhost/owncloud" (or whichever server address/path)
5. Login as "user2" to accept the share
6. Setup sync client for "user2" and let it download the file
7. Login as "user1" and edit "test.txt" in the web UI and save it.
8. Wait for sync

### Expected result
Sync client of "user2" finds and downloads the changes

### Actual result
Changes not downloaded. Possibly an etag propagation issue on the server side.

### Versions
ownCloud 8 git master (bd888748bd9d0d9e9268447501fe35abf121083b)

@icewind1991

**Comment by PVince81** [comment]
@karlitschek @DeepDiver1975 please schedule accordingly

**Comment by PVince81** [comment]
Note: this happens only for single file shares.
For folder shares (through s2s), the contents is synced properly.

**Comment by DeepDiver1975** [comment]
> Note: this happens only for single file shares.

let's retest this once https://github.com/owncloud/core/pull/13682 is ready

**Comment by PVince81** [comment]
Retested on master (d2f3710ede1fa72658a4c12264a90a1936faf9ca) and it works now: the change is detected and the file is redownloaded by the sync client.
