### ISSUE TITLE
Can no longer run autotest.sh on my local system (master)

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#13681]
I can no longer run autotest.sh on master, I get this error message:

```
$ ./autotest.sh sqlite
Using database oc_autotest
Setup environment for sqlite testing ...
INDEX
END INDEX
Testing with sqlite ...
No coverage
PHP Fatal error:  Uncaught exception 'Exception' with message 'Not installed' in /home/schiesbn/public_html/owncloud/master/lib/base.php:223
Stack trace:
#0 /home/schiesbn/public_html/owncloud/master/lib/base.php(546): OC::checkInstalled()
#1 /home/schiesbn/public_html/owncloud/master/lib/base.php(1002): OC::init()
#2 /home/schiesbn/public_html/owncloud/master/tests/bootstrap.php(11): require_once('/home/schiesbn/...')
#3 /usr/share/php/PHPUnit/Util/Fileloader.php(93): include_once('/home/schiesbn/...')
#4 /usr/share/php/PHPUnit/Util/Fileloader.php(77): PHPUnit_Util_Fileloader::load('/home/schiesbn/...')
#5 /usr/share/php/PHPUnit/TextUI/Command.php(817): PHPUnit_Util_Fileloader::checkAndLoad('/home/schiesbn/...')
#6 /usr/share/php/PHPUnit/TextUI/Command.php(651):  PHPUnit_TextUI_Command->handleBootstrap('/home/schiesbn/...')
#7 /usr/share/php/PHPUnit/TextUI/Command.php(148): PHPUnit_TextUI_Command->handleArguments(Array)
#8 /usr/share/php/PHPUnit/TextUI/Command.php(138): PHPUnit_TextUI_Command->run(Array, true)
#9 /usr/bin/phpu in /home/schiesbn/public_html/owncloud/master/lib/base.php on line 223
```

Git bisect told me that the problem was introduced by commit bb80cf4ecab3a92541bf9c2fccaa204b6ea914f9 from this PR https://github.com/owncloud/core/pull/13593

@LukasReschke Does autotest.sh still works for you? Can you have a look at it? Thanks!

**Comment by LukasReschke** [comment]
Configure your PHP properly ;-)

**Comment by LukasReschke** [comment]
From that PR:

```php
+				'error' => 'PHP is configured to populate raw post data. Since PHP 5.6 this will lead to PHP throwing notices for perfectly valid code.',
+				'hint' => 'To fix this issue set <code>always_populate_raw_post_data</code> to <code>-1</code> in your php.ini'
```

**Comment by LukasReschke** [comment]
(when accessing oC via web the value is set via user.ini or .htaccess or that error is shown to the admin as well)

**Comment by schiesbn** [comment]
Works!

**Comment by AW-UC** [comment]
had the same problem. @LukasReschke a warning about this when running tests would be great. is this already on the agenda?

**Comment by DeepDiver1975** [comment]
issue on master branch as well????

https://ci.owncloud.org/job/server-master-linux/database=oci,label=SLAVE/

@LukasReschke THX

**Comment by LukasReschke** [comment]
No. A completely unrelated issue and I don't really care about Oracle much personally ;-)

**Comment by LukasReschke** [comment]
As in: I don't have any oracle test system and this change was in since like 2 weeks and we adjusted the 5.6 test systems. This is a configuration regression then on the CI system.

Ref https://github.com/owncloud/core/pull/13777

**Comment by LukasReschke** [comment]
Anyways, while I have some doubt that this is the issue here the point by @AW-UC makes sense. I added a dirty hack to our autotest which will detect such scenarios: https://github.com/owncloud/core/pull/14410
