### ISSUE TITLE
Feature Request: Send email notification if file is downloaded

### ISSUE THREAD

**Issue by novij** [owncloud/core#13683]
We often send a share link to our customers and would like to know if the file is downloaded. It would be nice to have a checkbox for a email notification to the file owner.

**Comment by RealRancor** [comment]
Very likely a duplicate of those: https://github.com/owncloud/core/issues/8765, https://github.com/owncloud/core/issues/7812

**Comment by DeepDiver1975** [comment]
> Very likely a duplicate of those: #8765, #7812
> Thomas Müller

indeed - THX @RealRancor
