### ISSUE TITLE
Bug with project website (documentation)

### ISSUE THREAD

**Issue by DaemonLion** [owncloud/core#13680]
Hi!
I'm trying to visit: https://doc.owncloud.org/server/7.0/go.php?to=admin-ldap
but there is a problem with your ssl certificate:

doc.owncloud.org uses an invalid security certificate. The certificate is only valid for the following names: www.owncloud.org, owncloud.org, download.owncloud.org, forum.owncloud.org

Don't know why but firefox forcefully rewrites url to https, maybe there was working https earlier and now it's broken

**Comment by LukasReschke** [comment]
We had some hiccup with the Apache configuration.

Please visit https://owncloud.org again and then try to visit http://doc.owncloud.org – if that not work then clearing your cache should help.

@MorrisJobke What have you done ;-)

**Comment by MorrisJobke** [comment]
> @MorrisJobke What have you done ;-)

Not I ;) It was  @danimo who added the all subdomains option ;)
