### ISSUE TITLE
Files in sub-folders maching search results not  clickable

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#13686]
### Steps to reproduce

1. Install owncloud
2. Upload an odt or pdf file that has owncloud in it
3. Create a subfolder
4. Upload a bunch of odt or pdf files that have owncloud in them
5. Search from the root for owncloud

### Expected behaviour

All files displayed in the search results to be clickable

### Actual behaviour

Only files found in the root are clickable

![p267](https://cloud.githubusercontent.com/assets/8480343/5906401/4b07c510-a565-11e4-804f-7f5d32a5e23c.PNG)

Ubuntu 14.04
PHP 5.5.9

### Server configuration

ownCloud Enterprise Edition 8.0 beta 2 (testing)

**Comment by PVince81** [comment]
@butonic

**Comment by DeepDiver1975** [comment]
@butonic please have a look if time permits - if not please ping me - THX

**Comment by PVince81** [comment]
I suspect the files might be missing the "data-path" attribute, needed in such flat lists.
I'll have a look.

**Comment by PVince81** [comment]
Works for me on core master (4d90fd933f47c71b4b9ff333b223f06822bc5340) and search_lucene master (4d90fd933f47c71b4b9ff333b223f06822bc5340)

When clicking on an entry in the "XX search results in other places" the files app is reloaded with the corresponding file in the URL.
The only issue I see is that it appends "file=owncloud1.odt" instead of "scrollto=owncloud1.odt" (which I can fix quickly if needed)

**Comment by PVince81** [comment]
@jnfrmarks on what part of the file row did you try clicking ? Is there anything appearing in the Javascript console ? (maybe a side-effect caused by other apps)

**Comment by DeepDiver1975** [comment]
@jnfrmarks as discussed on irc - we need to know the used/enabled search app - THX

**Comment by jnfrmarks** [comment]
Retesting and will update with requested info.

**Comment by nickvergessen** [comment]
Moved to https://github.com/owncloud/search_lucene/issues/56

**Comment by jnfrmarks** [comment]
See https://github.com/owncloud/core/issues/13687#issuecomment-72069043
