### ISSUE TITLE
Upgrade from 7.0.4 to 8.0.0 fails with invalid .htaccess version error

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#13693]
### Steps to reproduce

1. Install owncloud 7.0.4 into root directory "owncloud-704"
2. configure ldap, upload some files to have some data, create share link
3. mv owncloud-704 to owncloud-704.orig
4. make new  owncloud-704 directory
5. copy over data and config directories from owncloud-704.orig
6. access oC from GUI - get .htaccess version error
7. copy over .htaccess from owncloud-704.orig
8. Still get error

### Expected behaviour

Upgrade should complete without error

### Actual behaviour

Upgrade fails with a .htaccess version mismatch error

![p269](https://cloud.githubusercontent.com/assets/8480343/5908767/64ce80fc-a578-11e4-99d2-88ada851dfe6.PNG)

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration

ownCloud Enterprise Edition 8.0 beta 2 (testing)

**Comment by LukasReschke** [comment]
That is expected. Please update properly ;-)

**Comment by LukasReschke** [comment]
You did most likely not update the `.htaccess` file that was delivered with the new ownCloud release. You need to replace the old one with that one.

**Comment by jnfrmarks** [comment]
confirmed User error.  Thanks Lukas!

**Comment by LukasReschke** [comment]
I think we could make the error message more descriptive though… – Let me change that.

**Comment by LukasReschke** [comment]
https://github.com/owncloud/core/pull/13694

**Comment by EgbertJan** [comment]
Sorry. I do a webbased upgrade and now my cloud is broken. WHICH .htaccess WHERE???? Old version WHERE????

TNX Egbert Jan NL

**Comment by AdamWill** [comment]
This stuff is kind of broken anyway, it's making a lot of assumptions about how you want your webserver configuration to be done.

Fedora's packaged ownCloud does not use a `.htaccess` file as we can do the same configuration much more securely outside the publicly-served paths, in `/etc/httpd/conf.d`. It is generally considered Good Practice to do such configuration outside the actual content paths if at all possible; `.htaccess` files are an unfortunate necessity for people with limited administrative control over their deployment (shared host or whatever), they are not best practice. OC shouldn't really expect one to exist and throw a tantrum if it doesn't.

**Comment by EgbertJan** [comment]
Well spoken. And fully agree. I had some troubles also during the upgrade.

Egbert Jan, NL

Adam Williamson schreef op 22-2-2015 om 1:27:

**Comment by LukasReschke** [comment]
> OC shouldn't really expect one to exist and throw a tantrum if it doesn't.

Well, fact is that most people use them anyways and ship older .htaccess versions because they forgot to update them because they are hidden files. 

If you don't like them just disable them in the Apache config and ship the default anyways ;-)
