### ISSUE TITLE
Problems with accessibility: labels

### ISSUE THREAD

**Issue by davitol** [owncloud/core#13708]
### Steps to reproduce

1. Go to users screen

### Expected behaviour
Labels to grant the accessibility should exist

### Actual behaviour

There are many labels left as we can see in the screenshot attached using WAVE Web Accessibility Evaluation Toolbar

![captura de pantalla 2015-01-27 a las 13 26 24](https://cloud.githubusercontent.com/assets/10596560/5919030/c599e8ec-a62f-11e4-82e2-15e16e0d2de4.png)

**Comment by PVince81** [comment]
@jancborchardt

**Comment by PVince81** [comment]
Was there any work done for accessiblity on the users list ? I thought there was only for the files app.

**Comment by jancborchardt** [comment]
Yeah, was only files so far, and some settings parts. Will look into fixing some of this here.

**Comment by DeepDiver1975** [comment]
> Yeah, was only files so far, and some settings parts. Will look into fixing some of this here.

okay - out of scope for 8.0 then from my pov - let's move this off to 8.1 - THX

**Comment by PVince81** [comment]
@davitol if something is a problem, please tag it as "Bug", not "Enhancement". The "Enhancement" tag is for new features or nice improvements

**Comment by Volker-E** [comment]
@jancborchardt I could look into that as well, I've got several ideas. 
One of the bigger problems for all users is, that the space of the dropdowns isn't sufficient in i18n terms, see f.e. the group dropdown, where "Gruppe hinzufügen" in German is too long for the construction of table layout.

**Comment by Volker-E** [comment]
(Somehow) Connected to #13464

**Comment by jancborchardt** [comment]
@Volker-E what do you think about the approach as commented in #13464:

> In the future we could have some intelligent text sizing which makes the text a bit smaller to fit in the input field.

iOS for example does it like that. If text doesn’t fit the width, we could size it down a few sizes until it fits. That way most things would work. (Of course we’ll have a minimum of how small we’ll make the text.)

**Comment by Volker-E** [comment]
Seems like my last comment didn't get through: 
@jancborchardt I think that 'intelligent' text sizing based on `v*` unit sizes  can help in certain cases, right now browser support isn't great and it disables the ability to zoom in current implementations (which wouldn't be affecting ownCloud due to `maximum-scale=1`).
Two more things to take into account with inputs are longer strings then a text inputs size and text-only zooming.

**Comment by jancborchardt** [comment]
Afaik this has been fixed.

**Comment by davitol** [comment]
@jancborchardt alternative text is not provided for images that are the only thing within a link.
e.g. New button and share button

**Comment by jancborchardt** [comment]
@davitol different issue, but will look into that. Thanks!

**Comment by jancborchardt** [comment]
@davitol can you open a separate issue for reference though?

**Comment by jancborchardt** [comment]
@davitol fix for the New button at https://github.com/owncloud/core/pull/19085 – the Share thing needs more work since it should only be shown when not shared yet.
