### ISSUE TITLE
Prevent file scanner concurrency

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13703]
Sometimes it can happen that a scanner process is triggered twice at the same time through different requests, and they both scan the same file entries.

This can cause "Duplicate entry" issues and other unpredictable results.

We should look into a way to prevent two scanner instances to run into each other.

@icewind1991 @DeepDiver1975 @MorrisJobke

**Comment by DeepDiver1975** [comment]
duplicate entries are to be solved by having proper unique keys

errors with accidentally duplicate insert is to be handled by using INSERT WHERE NOT EXISTS

**Comment by karlitschek** [comment]
@icewind1991 can we do something here?

**Comment by DeepDiver1975** [comment]
Our high level file locking will help .... stay tuned.  ;-)

**Comment by PVince81** [comment]
Closing as duplicate of https://github.com/owncloud/core/issues/16584
It is more recent but contains steps to reproduce.
