### ISSUE TITLE
[provisioning_api] POSTing a request to make a user a subadmin of the same group fails

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#13709]
### Steps to reproduce

1. Enable Provising API application
2. Add some users, groups, and subadmins to some of the groups.
3. Using POSTMAN chrome plugin, invoke a request to POST a request to make a user a subadmin of a group
4. Invoke the request a second time

### Expected behaviour

The user gets a message indicating that the user is already a subadmin

### Actual behaviour

The user sees a white screen and there's an error in the server log 

![p85](https://cloud.githubusercontent.com/assets/8480343/4324546/9dd527bc-3f5b-11e4-8740-c7a7e8dad9e6.PNG)

![p86](https://cloud.githubusercontent.com/assets/8480343/4324547/a0b5d684-3f5b-11e4-91ab-2902457cdc93.PNG)

### Server configuration
**Operating system**:

Ubuntu 12.04

**Web server:**

 Apache/2.2.22 
 
**Database:**

MySql 

**PHP version:**

PHP 5.3

**ownCloud version:** (see ownCloud admin page)

ownCloud Enterprise Edition 7.0.2 Beta 1 (testing)

**Updated from an older ownCloud or fresh install:**

fresh install
#### ownCloud log (data/owncloud.log)

```
{"app":"PHP","message":"An exception occurred while exe cuting 'INSERT INTO `oc_group_admin` (`gid`,`uid`) VALU ES(?,?)':\n\nSQLSTATE[23000]: Integrity constraint viol ation: 1062 Duplicate entry 'sales-qa_admin' for key 'P RIMARY' at \/var\/www\/owncloud\/3rdparty\/doctrine\/db al\/lib\/Doctrine\/DBAL\/DBALException.php#47","level": 3,"time":"2014-09-18T17:43:58+00:00"}

```

**Comment by DeepDiver1975** [comment]
details on how to fix this: https://github.com/owncloud/enterprise/issues/322#issuecomment-56154360

**Comment by LukasReschke** [comment]
Moved the details to the public repo as well for @rullzer:
<hr/>
> "There is a missing check if a user is already a subadmin of a group in https://github.com/owncloud/enterprise/blob/master/provisioning_api/lib/users.php#L266. This is how it works in core: https://github.com/owncloud/core/blob/master/settings/ajax/togglesubadmins.php#L10.
> 
> Not sure if we should fix this in the SubAdmin class itself or only add the check to the provisioning api."

<hr/>

> To me it makes sense to fix this in the subadmin class and throw an exception, but that's gonna break stuff. Guess we add the check to the provis api?

<hr/>

> i think we have to add it to the provisioning api for now.

**Comment by rullzer** [comment]
Fix in #15564 .
However, I would suggest to also address the other raised points (but in a PR for 8.2). The subadmin class should throw an exception. Since that is the actual place it needs to be fixed.

**Comment by rullzer** [comment]
Technical dept issue created at #15573 to really fix the subadmin class.
However this issue here is fixed, so closing.

**Comment by SergioBertolinSG** [comment]
Tested on stable8, it returns <statuscode>100</statuscode> the two times. Good.
