### ISSUE TITLE
Remove shipped tag from all aps which are no longer shipped

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#13706]
- [x] calendar https://github.com/owncloud/calendar/pull/688
- [x] contacts https://github.com/owncloud/contacts/pull/793
- [x] bookmarks https://github.com/owncloud/bookmarks/pull/124
- [x] documents https://github.com/owncloud/documents/pull/441
- [x] admin_dependencies_chk - will not be uploaded

@LukasReschke are you aware of others? THX

**Comment by LukasReschke** [comment]
- [ ] admin_dependencies_chk
- [ ] documents

**Comment by DeepDiver1975** [comment]
> admin_dependencies_chk

is dead - will not be uploaded to the appstore from my understanding

**Comment by nickvergessen** [comment]
Added PRs for the other 4 apps (see first post)

**Comment by nickvergessen** [comment]
Closing since all have been merged

**Comment by DeepDiver1975** [comment]
awesome guys - THX!

**Comment by DeepDiver1975** [comment]
@karlitschek did we miss any app? THX

**Comment by karlitschek** [comment]
yes. search_lucene is missing too, The rest is fine. Thanks a lot!

**Comment by nickvergessen** [comment]
If we don't ship search_lucene the tickets from jennifer can be moved to 8.0.1/8.1 ? @DeepDiver1975

**Comment by DeepDiver1975** [comment]
> If we don't ship search_lucene the tickets from jennifer can be moved to 8.0.1/8.1 ?

If they are search_lucene specific - yes - but this needs to be clarified first.
furthermore we need to test search without any search app being installed :speak_no_evil:
