### ISSUE TITLE
Incomplete ext storage config breaks file list

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13715]
### Steps to reproduce
1. Enable external storage
2. Create a GDrive mount point, but enter "a" for client id and key
3. Click "Grant access", it will fail
4. Go back: the config must have a red square
5. Open file list

### Expected result
File list can be displayed, without the bogus mount.

### Actual result
File list is empty, server errors

### Versions
stable7 works correctly.
Observed on master.

Need to catch exceptions in the Storage's constructor.

CC @Xenopathic @icewind1991 @MorrisJobke 

Followup from https://github.com/owncloud/core/pull/13707#issuecomment-71661680

**Comment by PVince81** [comment]
It looks like stable7 the bogus mounts are added, but the exception is caught here on "createStorage": https://github.com/owncloud/core/blob/stable7/lib/private/files/mount/mount.php#L95

Let's find out where it happens on master and catch the exception there too.

**Comment by PVince81** [comment]
Okay, it turns out that the mechanism is the same.

The difference is that now there's the trashbin storage wrapper (which wasn't there before) which fails because it tries to wrap a `null` storage. Note that this could have happened with any other storage wrapper.

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/core/pull/13717

**Comment by MorrisJobke** [comment]
Fixed in #13717
