### ISSUE TITLE
Language question - Transifex

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#13713]
Hopefully my question is not stupid...

Why is it necessary to have on Transifex for owncloud the translation languages:
German
  and
German (Germany)

IMHO, I do not know any differences. Couldn´t that be reduced to one, eg German?

**Comment by karlitschek** [comment]
One of it uses "Sie" and the other "Du"
This is also a great question for the mailinglist. 
Please use the bugtracker only for bugs. Thanks :-)
