### ISSUE TITLE
How to ensure external CIF/SMB shares are securely authenticated?

### ISSUE THREAD

**Issue by gig13** [owncloud/core#13719]
When using CIF/SMB shares are authentication details sent from ownCloud encrypted and secure? Does this use the LDAP configuration settings, for example if ldaps is setup, it uses ldaps? 
Does the server need to be secured using SSL certs and https?

@MorrisJobke

**Comment by MorrisJobke** [comment]
cc @LukasReschke

**Comment by LukasReschke** [comment]
Reply is at https://github.com/owncloud/windows_network_drive/issues/175#issuecomment-71863982 – I have honestly no idea to what LDAP stuff you are referring to.

**Comment by DeepDiver1975** [comment]
We mount SMB shares using user id and password - both information is transmitted to the server via whatever the protocol defines/requests.

The link to ldap might be explainable as in: do we request e.g. a kerberos ticket(or how ever this is called in context of ldpa/ad) to authenticate against smb - no we don't.

Case closed from my pov - @gig13 or do you need more information on this? THX

**Comment by gig13** [comment]
Yes, closing.
