### ISSUE TITLE
Encripted server makes mobile logged accounts unusable

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#13727]
### Previous requirements

Have a OC 8.0 server unencrypted.
Have a user account with several files, pictures and documents.
Have the mobile client installed.
Have the user logged in the mobile client.

### Steps to reproduce
1. Enable encryption on server.
2. Log out and log in with an administrator account in the server using web UI.
3. From mobile client (who was previously logged in using a regular user account) try to browse your files, pictures, documents.

### Expected behaviour
You are still able to browse your files from  mobile clients.

### Actual behaviour
Files are blocked and you can't open it without any advice.

Note: While doing the same steps using a OC 7 server, mobile clients can browse their files without problems.

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.0.0.1","versionstring":"8.0 beta 1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
none

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes

### Client configuration
**Mobile:**
iOS client

**Comment by schiesbn** [comment]
like on the web interface and the desktop client you also need to re-login with your mobile client.

**Comment by LukasReschke** [comment]
Why not writing a key to the session when login happened with enabled encryption and if encryption is enabled then check for that key using a hook or some kind of magic?

**Comment by SergioBertolinSG** [comment]
@schiesbn Yes logging out and logging in allows the mobile client to show the files again, but this is a regression problem because OC 7 server allowed client to browse files without problems.

**Comment by DeepDiver1975** [comment]
scheduling this for 8.1 - the described scenario is not that critical from my pov

**Comment by PVince81** [comment]
@SergioBertolinSG I don't think this is a regression, this is the way it always worked. Unless the older versions of the mobile client would re-login every time for every request.

**Comment by DeepDiver1975** [comment]
We would need some mechanism to invalidate a user session see https://github.com/owncloud/security-tracker/issues/31

**Comment by PVince81** [comment]
@SergioBertolinSG is this really a regression ? I had the feeling that it's the way it's always worked before.

**Comment by PVince81** [comment]
> because OC 7 server allowed client to browse files without problems. 

@SergioBertolinSG are you sure ? Were you able to download the files ?

From what I remember, there might have been a time where the encryption app did not try to prevent users to download encrypted files, and this was added later. Maybe browsing the files worked but downloading didn't ?

**Comment by SergioBertolinSG** [comment]
With encryption 2.0 (8.1) this issue won't happen again.
Just tested with 8.2.1rc1 with iOS client, no problems.
