### ISSUE TITLE
Text label of shared folders isn't long enough to show domain.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#13722]
### Steps to reproduce

Using an administrator account: 

1. User1 in Server1 shares a folder with User2 in Server2 User2@IP_Server2/OWNCLOUD_FOLDER .
2. Show files of User2 in Server2.

### Expected behaviour
Location of shared folder shows domain/ip.

### Actual behaviour
Text label is too short and only User1_name+"@..." is shown.
You have to hover the pointer over the text label to show a tooltip with fullname.

![screen shot 2015-01-28 at 09 54 16](https://cloud.githubusercontent.com/assets/9048796/5934968/27e1ff48-a6d6-11e4-8d31-6dff6b0d3db8.png)

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.0.0.1","versionstring":"8.0 beta 1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
none

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** no

### Client configuration
**Browser:**
Chrome,Firefox

**Comment by LukasReschke** [comment]
That is actually how we implemented it. @nickvergessen @jancborchardt Thoughts?

**Comment by LukasReschke** [comment]
Actually the current implementation allows users to ensure that it is an actual remote share as they can check the tipsy hover. So even if a local user would be called

**Comment by jancborchardt** [comment]
This is intended. Showing the full domain happens on hover. If we show it always then there would be way too much going on in the UI. From the UX, external shares shouldn’t be much different anyways.
