### ISSUE TITLE
Add user Share textbox disappears after a wrong try

### ISSUE THREAD

**Issue by davitol** [owncloud/core#13726]
### Steps to reproduce

1. Go to files
2. Click share
3. Share file to a user of another server (USERNAME@domain.tld/owncloud )

### Expected behaviour
Adding user to sharing textbox should not be cleaned after a wrong line is sent.

### Actual behaviour

Adding user to sharing textbox dissapears after a wrong user written

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.0.0.4","versionstring":"8.0 beta 2","edition":""}

**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
none

**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password and passwordsalt)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** no

### Client configuration
**Browser:**
Firefox

![captura de pantalla 2015-01-28 a las 10 55 50](https://cloud.githubusercontent.com/assets/10596560/5935711/10fe4b58-a6de-11e4-8823-4d27ed0826a9.png)

**Comment by DeepDiver1975** [comment]
@jancborchardt for UX - THX

**Comment by DeepDiver1975** [comment]
8.1 as well - not critical

**Comment by jancborchardt** [comment]
This is a JS issue, not a design issue it seems. The popup should not cause the textbox to disappear.

**Comment by PVince81** [comment]
@davitol does it do that in 8.2 too ?

**Comment by davitol** [comment]
@PVince81 Due to the new design the textbox is visible after writing down a wrong user, but the info written is deleted; feel free to decide what it should be the right behaviour

**Comment by PVince81** [comment]
Low ticket for an older version => closing.

If this still occurs in the sidebar version, please reopen.
