### ISSUE TITLE
Handling large file uploads - PHP max execution time etc.

### ISSUE THREAD

**Issue by geez0x1** [owncloud/core#13721]
I recently bumped the upload limit of my ownCloud server to 8GB files. With this I encountered problems. Setting the upload limit to 8GB correctly updated the upload_max_filesize and post_max_size values in ownCloud's main htaccess, but this was not sufficient. I encountered two other problems:

**Inability to move the temporary file to its destination due to PHP execution timeout**
Files would be uploaded to my PHP temp folder (default on Debian: /tmp/), but since /tmp/ is on a raid 1 with three 5400rpm disks and the files are moved to a raid 5 on the same three disks, this takes a while for very large files. The script doing the moving times out:
`[Sun Jan 25 21:16:10 2015] [error] [client 1.2.3.4] PHP Fatal error:  Maximum execution time of 60 seconds exceeded in Unknown on line 0, referer: https://site/owncloud/index.php/apps/files/?dir=%2Fsomefolder`
and the upload fails. I fixed this by adding 
`php_value max_input_time 3600`
`php_value max_execution_time 3600`
to ownCloud's main htaccess file. I traced down the issue using these reports, among a few others: https://github.com/owncloud/core/issues/1270, http://forum.owncloud.org/viewtopic.php?f=26&t=21134

**Insufficient space in /tmp/**
Since my PHP temp folder resides in /, which is small due to it being a non-GUI server, there was insufficient space to upload these very large files. I fixed this by modifying `/etc/php5/apache2/php.ini`:
`upload_tmp_dir = /home/large_tmp/`
This is specific to my server but it might not occur/be known to everyone that PHP writes files to /tmp/ first. In other words, this should be at least noted.

**Fixes**
These issues are not documented on this page:
http://doc.owncloud.org/server/7.0/admin_manual/configuration/big_file_upload_configuration.html
A good step would be to at least document this issue there. A possible other solution would be to increase the PHP execution time accordingly when the max file upload is changed. Or, perhaps, the script that moves the files can be moved outside of the main upload request. The problem has been fixed for me for now but I've read multiple people asking about it and the solution is not documented in the official documentation.

**Comment by DeepDiver1975** [comment]
@carlaschroder can you please adopt the documentation accordingly?

Two thinks are to be mentioned:
- temp space has to be big enough to hold multiple parallel uploads from multiple users - e.g. max upload size is 10GB and the average users uploading the same time is 100: temp space has to hold at least 10x100 GB
- php execution times might have to be adjusted - as described above

Thanks a lot!

**Comment by DeepDiver1975** [comment]
How can this be fixed in ownCloud from a general POV:
- we use our chunked upload mechanism as the desktop client does - see #https://github.com/owncloud/core/issues/4380

**Comment by carlaschroder** [comment]
https://github.com/owncloud/documentation/pull/792
Feel free to make your own tweaks; I'm gone feb 3-13 and am out of time for anything but oC 8 release work.

**Comment by swapnilkun** [comment]
Hi

**Comment by swapnilkun** [comment]
i am upload a video file 150mb it's work but time consuming so how to reduce the time file uploading

**Comment by swapnilkun** [comment]
Please help Me
