### ISSUE TITLE
"federated cloud" share users are anonymous in activity feed due to current session restrictions

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#13739]
## Steps to reproduce
1. Share a Folder as public link (with write permissions) in instance A with `UserA` (uid: `UserA`, display: `A from InstanceA`)
2. Open public link and add to instance B as `UserB` (uid: `UserB`, display: `B from InstanceB`) with "Add to owncloud" field
3. Add a File `test.txt` to the folder as `UserB`
4. Check activity feed for `UserA`
### Expected

One of:
- `UserB` created test.txt
- `UserB@InstanceB` created test.txt
- `B from InstanceB` created test.txt
### Actual

`***empty string***` created test.txt
(Added a workaroung so it uses "remote user" instead of empty string for now, see https://github.com/owncloud/activity/pull/220 )
### Findings

The activity app uses the following code to get the uid when creating the activities:

``` php
            $user = $server->getUserSession()->getUser();
            return ($user) ? $user->getUID() : '';
```

Is it somehow possible to get any info from the session or somewhere else, that the current user is a remote user `UserXYZ` with a displayname `XYZ on InstanceABC` on `InstanceABC`, so we don't display "remote user" only, but can help to identify the user.

Since this also happens to intentional remote shares (uid@instance in the share dropdown), it would be nice to know, which user you want to remove from the sharing list ;)

// cc @schiesbn @icewind1991 for writing the feature

**Comment by schiesbn** [comment]
if no user is logged it should be save that the operation was performed from a external user, either from a server-to-server share or from a public link share which allows upload.

**Comment by schiesbn** [comment]
At the moment the user authenticate itself with the share token we can find his username and remote server by looking up the share table. But I think the upload activity gets triggered by the write hook. If we would find a way to propagate the information from the sharing code to the activity app we could display the correct remote user, in case of server-to-server sharing.

**Comment by progmem64** [comment]
I know this comment is pretty useless, but this issue is the most annoying thing about oc. If you shared a ressource with multiple clouds, you just need to know who did what. The message "remote user" did something is just useless and sometimes frustrating. Since this issue is open since 2015 and moves from milestone to milestone, i hope that i can push it a little with my comment.
