### ISSUE TITLE
About behavior of NFS Connectivity 

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#13734]
What I want ask is I need more specific information how oC server and/or sync client behaves in the situation when the NFS lost connection.

Currently, I don’t have any hard proof that indicates there was back-end connectivity issue in any log.

I need some information how OC server should behave in such situation helps us much to diagnose back-end connectivity.  

As a reference https://github.com/owncloud/mirall/issues/1425

@MorrisJobke @DeepDiver1975 

00001901

**Comment by DeepDiver1975** [comment]
I assume we are talking about the data directly being mounted to a NFS server - right?

We have a hidden magic file called .ocdata exactly for this purpose.
In case the mount is lost - no .ocdata file exists and ownCloud can detect the data folder not being present.

This will result in a controlled exception scenario - should be a 503 http response.

**Comment by MorrisJobke** [comment]
Maybe some web UI indication (like in WND) would be nice. Isn't there already a ticket to migratet this into the files_external app?

**Comment by DeepDiver1975** [comment]
with the data dir not being available there is no reason to show anything - a user will have no files, no encryption keys, no thumbnails - basically nothing.

missing data dir is a critical failure which is handled in a controlled manner - 503 http status and an error page in the browser

**Comment by MorrisJobke** [comment]
Ah....the data dir is missing. Okay. I just thought about a subfolder of the data dir.

**Comment by DeepDiver1975** [comment]
> I just thought about a subfolder of the data dir.

this is not supported from my understanding

**Comment by cdamken** [comment]
what is in the case the that the folder is mounted on the server and used as data folder? and has intermittent disconnections?

**Comment by nickvergessen** [comment]
Propable the same as setting it to an non existing drive...?

**Comment by DeepDiver1975** [comment]
> what is in the case the that the folder is mounted on the server and used as data folder? and has intermittent disconnections?

well - the folder is either there nor not at the point in time when the request is being processed.

**Comment by DeepDiver1975** [comment]
@cdamken case closed?

**Comment by cdamken** [comment]
@DeepDiver1975 yes
