### ISSUE TITLE
Run `updateDataDirectory` after update

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#13731]
Ref https://github.com/owncloud/core/pull/13730#issuecomment-71821620

**Comment by DeepDiver1975** [comment]
can be implemented as repair job - should be done already for 8.0 ????

**Comment by LukasReschke** [comment]
Well, if we're going with "Critical fixes" only then I believe that this is not critical enough and I have a lot of other things to do instead of that at the moment ;-)

But if somebody volunteers to do that: Sure ;-)

**Comment by LukasReschke** [comment]
(i.e. 8.0.1 – I guess this would be the 8.0-next milestone then? *confused*)

**Comment by DeepDiver1975** [comment]
8.0-next will pop up soon ....
