### ISSUE TITLE
How can oC prevent the lost of information or get a warning when the NFS lost connection

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#13735]
Seeing https://github.com/owncloud/core/issues/13734  I want to know If you can make a QA to test when the NFS lost connection, which is the behavior from oC?

@jnweiger 

00001901

**Comment by DeepDiver1975** [comment]
as described here: https://github.com/owncloud/core/issues/13734#issuecomment-71832425

as for the test: no need to mount NFS - just kill .ocdata in the data dir and observer the behavior.

**Comment by cdamken** [comment]
@DeepDiver1975 thanks :+1:

**Comment by DeepDiver1975** [comment]
so - what shall we do with this ticket here? Anything else left to do? @cdamken

**Comment by PVince81** [comment]
Looks like @cdamken was asking for the creation of an automated test to check for such cases.

@jnfrmarks

**Comment by MorrisJobke** [comment]
@jnfrmarks Can you create a test that covers this?

**Comment by jnfrmarks** [comment]
@MorrisJobke 

Please move the issue to the smashbox repo - that's where we're tracking test requests.  Thanks!

**Comment by MorrisJobke** [comment]
https://github.com/owncloud/smashbox/issues/60
