### ISSUE TITLE
[packaging] Getting 403 with openSUSE package for 8.0.0~beta2

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13732]
### Steps to reproduce:
1. I had 7.0.4 installed from OBS RPM on my server
2. Upgrade to owncloud-8.0.0~beta2 (used `zypper update`)
3. Run `./occ upgrade` as wwwrun user

### Expected result
ownCloud runs after upgrade

### Actual result
Apache gives 403

### Versions
OC 8.0.0~beta2 from OBS RPM (community testing repo)

I suspect that the Apache config might not be correct / complete.

owncloud.conf seems to have been changed to this:
```
Alias /owncloud "/usr/share/owncloud/"
<Directory "/usr/share/owncloud">
  AllowOverride All
</Directory>
```

I see that `/srv/www/htdocs/owncloud` is now a symlink to `/usr/share/owncloud`.
And the data was migrated to `/var/lib/owncloud/data`  which also has a symlink as `/srv/www/htdocs/owncloud/data`.

I suspect that Apache might not be allowed to access the parent dir `/usr/share`.

@jnweiger can you confirm ?

**Comment by jnweiger** [comment]
Suggested workaround: we'll offer FHS compliance only as a separate experimental package named 'owncloud-fhs'. The normal 'owncloud' package will revert to the traditional file system layout.

That should resolve the showstopper.

**Comment by karlitschek** [comment]
@jnfrmarks Thanks a lot. Good idea.

**Comment by jnfrmarks** [comment]
>@jnfrmarks Thanks a lot. Good idea.


Was this meant for @jnweiger ?

**Comment by jnweiger** [comment]
jn+TabCompletion

guess so :-)

**Comment by jnweiger** [comment]
@PVince81 please retest with 8.0.0 RC1 packages.

**Comment by PVince81** [comment]
I'm still on the train. Will test them on my server this evening or tomorrow.
Thanks.

**Comment by PVince81** [comment]
Note, the RC1 package worked but I had to force it with `--oldpackage`. Next time please use lower case "rc1" in the name.

Can we do this for the tarballs too in the future @karlitschek ? (never use any upper case letters in package/tarball names and everything will be fine)

**Comment by DeepDiver1975** [comment]
@PVince81 did you retest upgrading recently? Maybe retry with rc2? THX

**Comment by PVince81** [comment]
I already upgraded to "RC1" capitalized. There are no packages for "rc2" now in the testing repo it seems. @jnweiger ?

**Comment by DeepDiver1975** [comment]
@PVince81 close? as upgrate now works???

**Comment by PVince81** [comment]
Package upgrade works, yes.
Next time PLEASE use lower case `rc1`.
Thanks.

**Comment by jnweiger** [comment]
Thanks for testing.

The changelogs show that all 7.0.x used uppercase RC ...

**Comment by PVince81** [comment]
Yes, and we met the same issue there. Need to upgrade with `zypper install --oldpackage ...`
