### ISSUE TITLE
Support U2F

### ISSUE THREAD

**Issue by bkerensa** [owncloud/core#13748]
Would be great to see OwnCloud be a leader in support U2F authentication

**Comment by karlitschek** [comment]
Do you volunteer to work on that?

**Comment by bkerensa** [comment]
I volunteer for no such things I am busy upstream building the browser that loads your app :P

**Comment by DeepDiver1975** [comment]
Falls into the area of two factor auth. From my understanding we first have to bring core into share for the basic ground work. Explicit implementations can follow afterwards in apps. @lukasreschke thx

**Comment by LukasReschke** [comment]
Correct – https://github.com/owncloud/core/issues/12102

**Comment by MorrisJobke** [comment]
Should we close this in favour of #12102 or should this be kept open to track this specific protocol?
