### ISSUE TITLE
setupchecks.js: Message: WebDAV interface seems to be broken

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#13744]
Ubuntu 14.04, MySQL, PHP 5.5, nginx, Browser W7/Opera 24, fresh install of git/master

@PVince81 @LukasReschke 

Old story about the config check message in the admin page: 
'Your web server is not yet properly setup to allow files synchronization because the WebDAV interface seems to be broken.'

I questioned myself why I get this message and did browser debugging.
The result is shown in the screensot below. The query response is a 404 (not found).
The address is https://subdomain.domain/remote.php/webdav
My certificate could make a difference, because when you run
curl either with -v (error due to the certificate) or -k (success, because the certificate is not validated)

During beeing logged on, if I do the query manually from the browser, I get a empty page.

core/js/setupchecks.js
![image](https://cloud.githubusercontent.com/assets/3321281/5942624/fb990cf4-a718-11e4-81fd-59ef6ffff34e.png)

**Comment by LukasReschke** [comment]
Kinda hard to debug this without test account / domain – would it be possible to get me access to that instance? You can find my mail address in my profile.

**Comment by mmattel** [comment]
Done, eMail sent.

**Comment by mmattel** [comment]
There is no bug, it was al local setup problem I was able to sort out with the help of @LukasReschke, sorry for any inconvinience caused. I close this issue.
