### ISSUE TITLE
Improve CSS on server error page 

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#13747]
### Steps to reproduce

1. Install and configure 7.0.4 and owncloud 8.0.0
2. Bring down the DB box
3. Try to access 7.0.4 - get valid error message
4. Try to access 8.0.0 - get Internal Server Error message

### Expected behaviour

The user should get the same message (can't reach DB) in both cases

### Actual behaviour

User gets Internal Server Message in 8.0.0

Screen shot from 7.0.4:

![p270](https://cloud.githubusercontent.com/assets/8480343/5944323/0f1727cc-a6f4-11e4-9b0a-65cc35b041dc.PNG)

Screen shot from 8.0.0:

![p271](https://cloud.githubusercontent.com/assets/8480343/5944315/05510780-a6f4-11e4-8b72-efd4d43f8e89.PNG)

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration

ownCloud Enterprise Edition 8.0 beta 2 (testing)

**Comment by LukasReschke** [comment]
Actually the Internal Server Error is the expected behaviour as we didn't want to leak information why is something down which can contain the IP of the remote host etc…

Though the CSS should work as well, but that is a different issue ;-)

**Comment by LukasReschke** [comment]
Internal Server Error == A page for all errors. Admin can see details in the owncloud.log or enable DEBUG mode in which case he will see a proper error description and stacktrace.

**Comment by LukasReschke** [comment]
The Server Error page has been introduced with 8.0 – thus not available on 7

**Comment by jnfrmarks** [comment]
Makes sense.  

I'll change the title to: improve css on internal server error message

**Comment by LukasReschke** [comment]
No CSS is added since the query to appconfig fails. Great dependency fun :/
```php
Array
(
    [reqId] => 353a4dad23db45d6643808a592840c53
    [remoteAddr] => ::1
    [app] => index
    [message] => Exception: {"Message":"An exception occurred while executing 'SELECT \"configvalue\", \"appid\" FROM \"oc_appconfig\" WHERE \"configkey\" = ?' with params [\"enabled\"]:\n\nSQLSTATE[HY000]: General error: 1 no such table: oc_appconfig","Code":0,"Trace":"#0 \/Users\/lreschke\/Programming\/core\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/Users\/lreschke\/Programming\/core\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(838): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOSqlite\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'SELECT \"configv...', Array)\n#2 \/Users\/lreschke\/Programming\/core\/lib\/private\/db\/connection.php(111): Doctrine\\DBAL\\Connection->executeQuery('SELECT \"configv...', Array, Array, NULL)\n#3 \/Users\/lreschke\/Programming\/core\/lib\/private\/appconfig.php(259): OC\\DB\\Connection->executeQuery('SELECT `configv...', Array)\n#4 \/Users\/lreschke\/Programming\/core\/lib\/private\/app.php(219): OC\\AppConfig->getValues(false, 'enabled')\n#5 \/Users\/lreschke\/Programming\/core\/lib\/private\/app.php(71): OC_App::getEnabledApps()\n#6 \/Users\/lreschke\/Programming\/core\/lib\/base.php(539): OC_App::loadApps(Array)\n#7 \/Users\/lreschke\/Programming\/core\/lib\/base.php(1007): OC::init()\n#8 \/Users\/lreschke\/Programming\/core\/index.php(26): require_once('\/Users\/lreschke...')\n#9 {main}","File":"\/Users\/lreschke\/Programming\/core\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractSQLiteDriver.php","Line":57}
    [level] => 4
    [time] => 2015-01-28T18:56:44+00:00
)
```

**Comment by DeepDiver1975** [comment]
@jancborchardt can you easily apply some magic to make this happen? THX

**Comment by jancborchardt** [comment]
Shouldn’t it simply use the same error page template? Or is that not possible?

**Comment by MorrisJobke** [comment]
@DeepDiver1975 @jancborchardt It is that error page, but somehow the CSS isn't loaded. Maybe an not updated htaccess again?!? 

cc @LukasReschke @jnfrmarks

**Comment by MorrisJobke** [comment]
Reproduced locally ... I will have a look at it

**Comment by LukasReschke** [comment]
No. This is dependency fun, see https://github.com/owncloud/core/issues/13747#issuecomment-71893343

**Comment by LukasReschke** [comment]
Generally spoken: The exception is thrown before the CSS is added.

I doubt that this can be fixed that easily since it is base.php fun – and it shouldn't happen that often, when  it is a general PHP error caused by some app the CSS is already added etc…

Not sure if we really should make that 8.0 – though @MorrisJobke may prove me wrong and find an easy fix ;)

**Comment by MorrisJobke** [comment]
I already have a fix locally :P

**Comment by MorrisJobke** [comment]
And it's an one liner :P

**Comment by MorrisJobke** [comment]
sorry ... actually a three liner but one line is a comment ;)
