### ISSUE TITLE
chown php error on install

### ISSUE THREAD

**Issue by puggan** [owncloud/core#13749]
Got his (as json) in my apache log when trying to install (button after filling in database auth)

    Array
    (
        [app] => PHP
        [message] => chmod(): No such file or directory at \/usr\/share\/webapps\/owncloud\/7.0.4\/htdocs\/lib\/private\/log\/owncloud.php#88
        [level] => 3
        [time] => 2015-01-28T20:39:53+00:00
    )

according to
http://doc.owncloud.org/server/7.0/admin_manual/installation/installation_source.html
3 folders need to be own by apache:

    ls -ld /usr/share/webapps/owncloud/7.0.4/htdocs/apps/ /usr/share/webapps/owncloud/7.0.4/htdocs/config/ /usr/share/webapps/owncloud/7.0.4/htdocs/data/
    drwxr-xr-x 26 apache apache  776 Jan 28 12:53 /usr/share/webapps/owncloud/7.0.4/htdocs/apps/
    drwxr-xr-x  2 apache apache  152 Jan 28 21:41 /usr/share/webapps/owncloud/7.0.4/htdocs/config/
    drwxr-xr-x  2 apache apache 4096 Jan 28 21:49 /usr/share/webapps/owncloud/7.0.4/htdocs/data/

Row 88 tries to write/chown to log file, and /usr/share/webapps/owncloud/7.0.4/htdocs/data/owncloud.log exists, and are also owned by apache.

installation is done by emerge (gentoo package manager) using owncloud-7.0.4.ebuild

**Comment by RealRancor** [comment]
Related to https://github.com/owncloud/core/issues/13736 ?

**Comment by DeepDiver1975** [comment]
> Related to #13736 ?

no - afaik

**Comment by DeepDiver1975** [comment]
the call to chmod is failing in case the file does not yet exist - https://github.com/owncloud/core/blob/master/lib/private/log/owncloud.php#L85

but because of @ it should not really be causing an error to be written.

**Comment by puggan** [comment]
the failer of the installation proberly is something else, this was the last (or 2nd las) error message before it crached, i later found in another log-file, that apache had a segmentation error.

**Comment by Xenopathic** [comment]
Please retry with oC 8.1.1, and re-open if you are seeing the same issues.
