### ISSUE TITLE
Use part files for web UI upload

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13755]
### Steps to reproduce
1. Prepare a bag full with luck
2. Enable encryption
3. Setup the sync client
4. Upload a lot of small files with the Web UI
5. While the Web UI is still uploading, the sync client will at some point start downloading

### Expected result
No encryption error in log

### Actual result
If you're (un-)luck, it might happen that the sync client sees a file while it is still being uploaded/encrypted, which results in the following:
```
{"reqId":"f88e81b5c643f29cba06d504d97b69b1","remoteAddr":"192.168.1.2","app":"remote","message":"Encryption key not found for \"\/root\/files\/sub10\/zegar.gif\" during attempted read via stream","level":4,"time":"2014-11-28T08:57:35+00:00"}
```

One solution for this would be to make files that are uploaded through the Web UI also become a part file at first, until all file operations, proxies, etc are finished (for encryption). Then at the end, rename the file to the final file.

### Versions
OC 8 git master, possibly happening in any version

In general I think we should start using part files for everything related to upload.

@schiesbn @DeepDiver1975 @icewind1991

**Comment by PVince81** [comment]
I forgot to mention that the sync client will show an error when downloading that incomplete file. The next sync run will redownload it and all is fine in the end.

**Comment by DeepDiver1975** [comment]
> In general I think we should start using part files for everything related to upload.

as soon as we migrate over to webdav in the browser this will be solved

**Comment by PVince81** [comment]
Closing as duplicate then: https://github.com/owncloud/core/issues/12353
