### ISSUE TITLE
Only variables should be passed by reference

### ISSUE THREAD

**Issue by puggan** [owncloud/core#13751]
when trying to install i get:

	Array
	(
		[app] => PHP
		[message] => Only variables should be passed by reference at \/usr\/share\/webapps\/owncloud\/7.0.4\/htdocs\/lib\/private\/template.php#287
		[level] => 3
		[time] => 2015-01-28T20:39:53+00:00
	)

where row 287 is the getHint() row in

      } else {
         $hint = '';
         if ($exception instanceof \OC\HintException) {
            $hint = OC_Util::sanitizeHTML($exception->getHint());
         }
      }

sending the result of a function to a function that takes a reference

    public static function sanitizeHTML( &$value )

in /usr/share/webapps/owncloud/7.0.4/htdocs/lib/private/util.php:975

same as #13296 ?

**Comment by puggan** [comment]
sanitizeHTML is currently at 
https://github.com/owncloud/core/blob/30a5758a95f612d00f9aed934819f16c67aceefc/lib/private/util.php#L1021

the getHint() row:
https://github.com/owncloud/core/blob/9ab62ad5b787d44238c842f633fc950918aaa796/lib/private/template.php#L287

removed in:
https://github.com/owncloud/core/blob/6d3757f8648cb94b2ba04c6a5bfbc9dd1493103b/lib/private/template.php

**Comment by MorrisJobke** [comment]
@puggan Can I ask you to fill out the issue template: https://github.com/owncloud/core/blob/master/issue_template.md Especially the architecture of your server and the steps to reproduce. Thanks

**Comment by DeepDiver1975** [comment]
> @puggan Can I ask you to fill out the issue template: https://github.com/owncloud/core/blob/master/issue_template.md Especially the architecture of your server and the steps to reproduce. Thanks

@MorrisJobke  I think this is not necessary here - it's quite obvious that there is an issue in the code

**Comment by puggan** [comment]
the failer of the installation proberly is something else, this was the last (or 2nd las) error message before it crached, i later found in another log-file, that apache had a segmentation error.

**Comment by puggan** [comment]
Server configuration
Operating system: Gentoo (Linux chi.puggan.se 3.10.17-gentoo #2 SMP Sun Mar 2 22:34:28 CET 2014 x86_64 AMD FX(tm)-8350 Eight-Core Processor AuthenticAMD GNU/Linux)
Web server: www-servers/apache-2.2.27-r4
Database: dev-db/mysql-5.6.22
PHP version: dev-lang/php-5.5.21
ownCloud version: www-apps/owncloud-7.0.4
Updated from an older ownCloud or fresh install: fresh

**Comment by DeepDiver1975** [comment]
@nickvergessen can I ask you for a PR on this as well? THX

**Comment by nickvergessen** [comment]
done

**Comment by ravermeister** [comment]
##### Still open in OC 8.02?
is it resolved in OC 8.0.2 stable? 
because I get this error in OC 8.0.2 below is the log:
` "reqId":"c7f3af3c89960cee767c8202d64a8c3c"`
`"remoteAddr":"",`
`"app":"PHP",`
`"message":"Only variables should be passed by reference at \/path\/to\/owncloud\/lib\/private\/cache\/fileglobalgc.php#50", `

**Comment by MorrisJobke** [comment]
@ravermeister this is a different issue. Can you open a separate issue with your error. Thanks.

**Comment by MorrisJobke** [comment]
@ravermeister It will be fixed in 8.0.3 #14698
