### ISSUE TITLE
Moving files from a remote shared folder in an encrypted server to a not encrypted server using webdav fails.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#13758]
### Steps to reproduce

Having two servers server1 and server2, server1 is encrypted and server2 isn't.

1. Share a folder with files from server1 to server2.
2. Using webdav interface of server2 try to move a file from remote shared folder located in server1 to a local folder of server2. 

### Expected behaviour
File is moved correctly.

### Actual behaviour
Move fails and it returns:
503 Service Unavailable

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.0.0.4","versionstring":"8.0 beta 2","edition":""}

**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
Encryption in server1.

**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password and passwordsalt)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes in server1

### Client configuration
**Browser:**
Chrome

**Comment by schiesbn** [comment]
I can reproduce it... Will have a look at it

**Comment by schiesbn** [comment]
@SergioBertolinSG The pull request above should fix the issue, can you give it a try? Thanks!

**Comment by SergioBertolinSG** [comment]
Tested on the branch fix_move_del_of_remote_shares, working fine, not '503 service unavailable' found  but succeded.
