### ISSUE TITLE
Weird thing with Dropbox

### ISSUE THREAD

**Issue by iliyasbasir** [owncloud/core#13769]
### Expected behaviour

I add a dropbox account in my owncloud account to be able to have access to these files directly.
So everything works fine, the installation has been easy but I I saw that my client delete the folder then everyfile and few minutes later restart to download every files..
Don't understand why.
Nothing has changed from my side.
So I send you the log file from yesterday filtered to you to be able to see what's is going on with the server.

### Actual behaviour

Clienet should not delete the folder and restart download

### Steps to reproduce

1) add a dropbox account in my owncloud account to be able to have access to these files directly. 
2) Install was fine
3)

## Server configuration

Operating system:

Web server:

 Database:

PHP version:

ownCloud version:

Storage backend:

### Client configuration

Client version:

Operating system:

OS language:

Installation path of client:

### Logs 

Logs can be found at s3 under github-issue/core/13769

### Link
https://github.com/owncloud/client/issues/2737

**Comment by DeepDiver1975** [comment]
@iliyasbasir please enter all information as requested by the issue template - THX

**Comment by MorrisJobke** [comment]
@iliyasbasir If we don't get more information I can just add the same as over there: https://github.com/owncloud/client/issues/2737#issuecomment-71618636

**Comment by MorrisJobke** [comment]
The issue template is linked while creating an issue or here https://github.com/owncloud/core/blob/master/issue_template.md

**Comment by iliyasbasir** [comment]
@MorrisJobke i'll try get to you asap...

**Comment by iliyasbasir** [comment]
@MorrisJobke :
 I love filed out form which you placed, Customer do not like disclosed any information, after phone conversation with me and Allen he only provide us architecture layout which I’m placing 
 He is using appliance (centos 6, apache,  mysql  and ownCloud 7.0.3)
Somehow he had impression that if he provide me log all information should be in the log

**Comment by iliyasbasir** [comment]
@MorrisJobke : Can you please have some one look this issue. thx

**Comment by MorrisJobke** [comment]
@iliyasbasir 

The first line in the logs says:

```
{"reqId":"54941a0d04b20","app":"remote","message":"SQLSTATE[HY000] [1040] Too many connections","level":4,"time":"2014-12-19T12:29:01+00:00","method":"GET","url":"\/status.php"}
```

He needs to increase the connection limit of the database. Once this is fixed all the other problems should be gone. If not -> new ticket or reopen

**Comment by iliyasbasir** [comment]
@MorrisJobke : why  closed issue i'm waiting for customer confirmed change ..make sure it's work for customer I'll close after customer verify

**Comment by iliyasbasir** [comment]
@MorrisJobke @butonic @DeepDiver1975 @LukasReschke 

Customer max connection at 700, was at 500 ..No luck..Any help would be appreciated..

**Comment by PVince81** [comment]
I believe the redownload issue was observed already by @enoch85 in a different ticket.

**Comment by LukasReschke** [comment]
From the so secret error log which was not posted here:

```json
{"reqId":"54934981224c0","app":"core","message":"Exception while scanning file \"files_trashbin\/files\/FILENAME": An exception occurred while executing 'UPDATE `filecache` SET `mimepart` = ?, `mimetype` = ?, `mtime` = ?, `size` = ?, `etag` = ?, `storage_mtime` = ?, `permissions` = ?, `parent`=? WHERE `fileid` = ?':\n\nSQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction","level":0,"time":"2014-12-19T12:29:02+00:00","method":"DELETE","url":"\/remote.php\/webdav\FILENAME"}
```

Please post those logs always… Just remove all sensitive information… Having all developers searching them on S3 is not really productive at all and prevents the community to search for similar issues.

And as stated at https://github.com/owncloud/core/issues/13769#issuecomment-72047331: Please provide all information… I have no idea what DB they are running etc. This makes a huge difference!

**Comment by LukasReschke** [comment]
From https://github.com/owncloud/core/issues/13769#issuecomment-72096741 it looks like MySQL. Can you add those informations to the first post? Thanks.

**Comment by PVince81** [comment]
Maybe two processes concurrently scanning the trashbin (there is code to rescan it) and running into a deadlock ? Maybe an unclosed cursor.

**Comment by iliyasbasir** [comment]
@PVince81 @LukasReschke 
He did sent me some more log today..it's big log file so I placed at  s3 under github-issue/core/13769  > 02_10_log

**Comment by bboule** [comment]
@iliyasbasir We should also reproduce this as well, lets have a look at the logs you uploaded, but lets also ask the user for more information if he is unable or unwilling to provide the data we need to reproduce this we will close the case and send him a note letting him know we can re-open when he provides the needed information.

**Comment by iliyasbasir** [comment]
Cannot reproduced issue…informed customer

Thank you
-Iliyas

**Comment by MorrisJobke** [comment]
@iliyasbasir Please reopen if you know more
