### ISSUE TITLE
Remote shared folders from windows servers accessed from linux servers behaves too slow

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#13766]
### Steps to reproduce

Having server_linux in a linux machine and server_win in a windows one.

1. Share a folder from server_win to server_linux.

2. (Choose one)
       2.1. Upload many files from server_linux to the shared folder using webdav.
       2.2. Delete many files from server_linux to the shared folder using webdav.
       2.3. Move a local folder of server_linux inside the shared folder using webdav.

### Expected behaviour
It works good, not 503 service unavailable errors, no timeouts.

### Actual behaviour
Some 503 errors when uploading files, very slow in other cases.

Note: Same configuration but sharing a folder from server_linux to server_win accessing from server_win goes smoothly.

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.0.0.4","versionstring":"8.0 beta 2","edition":""}

**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
none

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** no

### Client configuration
WebDav interface

**Comment by PVince81** [comment]
Is there anything in owncloud.log of both servers regarding the reason for the 503 ?

**Comment by DeepDiver1975** [comment]
@karlitschek we do want to ship s2s for windows? Before walking this path I'd prefer to get the basic foundation fixed. Anyway - out of scope for 8.0 -> moving to 8.1

**Comment by DeepDiver1975** [comment]
> moving to 8.1

backlog I mean

**Comment by PVince81** [comment]
Windows server not supported any more, close ?
