### ISSUE TITLE
ownCloud fails to activate apps inside a folder name that contains a dash ("-")

### ISSUE THREAD

**Issue by arkascha** [owncloud/core#1376]
Current stable (OC-4.5.6) fails to active an app that is extracted into a folder that is named with a dash ("-") in the name. This often happens when apps are installed manually, since then the naming of the folder is up to the installing user. Often names like <appname>-<version> are chosen. Such naming scheme clearly makes sense from a technical point of view and is perfectly sane on a sytem level. Also ownCloud sees the app and offers it for activation. However during that activation an sql statement fails which is mean to to write the apps preferences: 

> Fatal error: Uncaught exception 'PDOException' with message
> 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'appid'
> cannot be null' in /var/www/bcloud/lib/db.php:731

The reason for column 'appid' being filled with an empty value simply is that ownCloud considers the folder name the app has been installed into as naeme of the app. This is strange in my eyes. Also it completely fails when the folders are named as described above. The name is treated as a mathematical expression by php which tries to build the difference of two invalid numerical values. This attempt results in a value FALSE, so an empty value as appid. 

I see three issues that should all be corrected inside OC-core: 
1.) Not the apps folder name should be taken as the apps name. I do know that this approach simplifies app handling. However it also leads to problems like the one described here. Those are issues that could be avoided with a different approach. 
2.) The result of the decision which name to use for an app should be validated. Maybe by testing the name (appid) against a regular expression. 
3.) The error generated is not helpful. Neither is it displayed to the user (the user just gets a generic "failed" error message, if at all), nor does it contain any meaningful information which might help to solve the problem. 

Since ownCloud allows to manually install apps the process of handling such apps should be robust enough. To prevent performance issues during normal operation it might make sense to limit checks of those names to handling during the installation/activation of apps.

**Comment by pf18387** [comment]
1) Computers do not make any difference between an hyphen and a minus character inside a string - except when the string is evaluated. So, avoid the '-' in IDs.
Fortunately, there is a "sanitizer" https://github.com/owncloud/core/blob/master/lib/private/app.php#L51
```php
public static function cleanAppId($app) {
	return str_replace(array('\0', '/', '\\', '..'), '', $app);
}
```

2) Another constraint might be implemented there: the length of an appId MUST be less or equal to 32. See, at least, the SQL tables `oc_appconfig`, and `oc_preferences`, where columns `appid` are defined as varchar(32). *In my opinion, the lack of this constraint could explain some other issues*.

3) According to VicDeo https://github.com/owncloud/core/issues/1376#issuecomment-13280641
> App files *should* be under 'appid' directory by design

To be very clear, for the moment the App files MUST be stored to an "appid" folder.
This constraint is well defined, at least inside remote.php: Given a `$service`, start to retrieve its corresponding `$file`path from the database, then extract the first directory from this filepath… will return the `$app` id. https://github.com/owncloud/core/blob/master/remote.php#L24
```php
$file = \OC::$server->getAppConfig()->getValue('core', 'remote_' . $service);
…
$parts=explode('/', $file, 2);
$app=$parts[0];
```
*In my opinion, the violation of this rather unknown constraint could explain some further issues*.

4) Last, to be honest, this issue should not been labeled as "Enhancement" ; this is only bug. The former *adds* new features, the latter *removes* unwanted features. Believe me: I'm a bug maker.

**Comment by Xenopathic** [comment]
Please retry with oC 8.1.1, and re-open if not resolved
