### ISSUE TITLE
Warning in log when uploading files into a shared folder with sync client

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13761]
### Steps to reproduce
1. Enable encryption
2. Create two users "user1" and "user2"
3. Login as "user2" and share a folder "sha" with "user1"
4. Setup the sync client for "user1"
5. Copy a folder full with files into the local "sha" folder
6. Wait for sync and observe sync.log

### Expected result
Successfull sync, nothing in log

### Actual result
Successfull sync, but log full of this:
```
{"reqId":"f8535cedd9c7d867d9f5028110859e68","remoteAddr":"192.168.1.2","app":"PHP","message":"Undefined index: storage_mtime at \/var\/ocdata\/vincent\/owncloud\/lib\/private\/files\/cache\/watcher.php#67","level":3,"time":"2014-11-28T10:08:20+00:00"}
{"reqId":"f8535cedd9c7d867d9f5028110859e68","remoteAddr":"192.168.1.2","app":"PHP","message":"filemtime(): stat failed for \/var\/ocdata\/vincent\/owncloud\/data\/user1\/files\/sha\/penguins-s\/zmeczony.gif at \/var\/ocdata\/vincent\/owncloud\/lib\/private\/files\/storage\/local.php#138","level":3,"time":"2014-11-28T10:08:20+00:00"}
{"reqId":"5080fe6dc942e821b0dfdfbee4fe76a0","remoteAddr":"192.168.1.2","app":"PHP","message":"Undefined index: storage_mtime at \/var\/ocdata\/vincent\/owncloud\/lib\/private\/files\/cache\/watcher.php#67","level":3,"time":"2014-11-28T10:08:21+00:00"}
{"reqId":"5080fe6dc942e821b0dfdfbee4fe76a0","remoteAddr":"192.168.1.2","app":"PHP","message":"filemtime(): stat failed for \/var\/ocdata\/vincent\/owncloud\/data\/user1\/files\/sha\/penguins-s\/zniesmaczony.gif at \/var\/ocdata\/vincent\/owncloud\/lib\/private\/files\/storage\/local.php#138","level":3,"time":"2014-11-28T10:08:21+00:00"}
{"reqId":"726dd0914f240e49cb6ba6682743a43a","remoteAddr":"192.168.1.2","app":"PHP","message":"Undefined index: storage_mtime at \/var\/ocdata\/vincent\/owncloud\/lib\/private\/files\/cache\/watcher.php#67","level":3,"time":"2014-11-28T10:08:21+00:00"}
{"reqId":"726dd0914f240e49cb6ba6682743a43a","remoteAddr":"192.168.1.2","app":"PHP","message":"filemtime(): stat failed for \/var\/ocdata\/vincent\/owncloud\/data\/user1\/files\/sha\/penguins-s\/zly.gif at \/var\/ocdata\/vincent\/owncloud\/lib\/private\/files\/storage\/local.php#138","level":3,"time":"2014-11-28T10:08:21+00:00"}
```

### Versions
ownCloud 8 git master + this patch https://github.com/owncloud/core/issues/12429
Database is SQLite
Encryption enabled
Sync client 1.7.1

I'll check whether this also happens in MySQL and without encryption.

CC @icewind1991

**Comment by PVince81** [comment]
Also happens with MySQL + encryption.
It doesn't happen when encryption is disabled.

**Comment by PVince81** [comment]
CC @schiesbn 

Not critical, but pollutes the log.
What do you think @DeepDiver1975 ?

**Comment by DeepDiver1975** [comment]
@icewind1991 already fixed some similar case these days - you remember?

**Comment by DeepDiver1975** [comment]
> Not critical, but pollutes the log.

polluting logs is not nice ... 8.0.1

**Comment by MatteoMora** [comment]
I also have the same problem, MySQL with encryption enabled.

    {"reqId":"2afc25130aa493da27bd5a0bcfe4ae2d","remoteAddr":"221.224.127.118","app":"PHP","message":"Undefined index: storage_mtime at \/var\/www\/owncloud\/lib\/private\/files\/cache\/watcher.php#67","level":3,"time":"Tue Apr 21 08:55:51 2015"}
    {"reqId":"2afc25130aa493da27bd5a0bcfe4ae2d","remoteAddr":"221.224.127.118","app":"PHP","message":"filemtime(): stat failed for \/var\/www\/owncloud\/data\/s.pisoni\/files\/Global Procurement Team\/India 2015-04-17\/IMG_20150417_104957_HDR.jpg at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#138","level":3,"time":"Tue Apr 21 08:55:51 2015"}
    {"reqId":"2674044f03a88644bdaa8a518498ceef","remoteAddr":"221.224.127.118","app":"PHP","message":"Undefined index: storage_mtime at \/var\/www\/owncloud\/lib\/private\/files\/cache\/watcher.php#67","level":3,"time":"Tue Apr 21 08:55:53 2015"}
    {"reqId":"2674044f03a88644bdaa8a518498ceef","remoteAddr":"221.224.127.118","app":"PHP","message":"filemtime(): stat failed for \/var\/www\/owncloud\/data\/l.reposi\/files\/PRICE LIST\/PRICE LIST CHINA\/Price list and packing China updated on 2015-4-21.xls at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#138","level":3,"time":"Tue Apr 21 08:55:53 2015"}

**Comment by PVince81** [comment]
I haven't seen this since a while, let's try again with 8.0.3RC3

**Comment by PVince81** [comment]
Still happening with 8.0.3RC3

**Comment by DeepDiver1975** [comment]
@nickvergessen mind taking a look - THX

**Comment by PVince81** [comment]
This is the stack that leads to this:
```
0  OC\Files\Cache\Watcher->checkUpdate() /srv/www/htdocs/owncloud/lib/private/files/cache/watcher.php:68
1  OC\Files\Cache\Shared_Watcher->checkUpdate() /srv/www/htdocs/owncloud/apps/files_sharing/lib/watcher.php:37
2  OC\Files\View->getFileInfo() /srv/www/htdocs/owncloud/lib/private/files/view.php:978
3  OC\Files\Filesystem::getFileInfo() /srv/www/htdocs/owncloud/lib/private/files/filesystem.php:793
4  OCA\Files_Versions\Storage::getUidAndFilename() /srv/www/htdocs/owncloud/apps/files_versions/lib/storage.php:48
5  OCA\Files_Versions\Storage::store() /srv/www/htdocs/owncloud/apps/files_versions/lib/storage.php:108
6  OCA\Files_Versions\Hooks::write_hook() /srv/www/htdocs/owncloud/apps/files_versions/lib/hooks.php:37
7  call_user_func:{/srv/www/htdocs/owncloud/lib/private/hook.php:78}() /srv/www/htdocs/owncloud/lib/private/hook.php:78
8  OC_Hook::emit() /srv/www/htdocs/owncloud/lib/private/hook.php:78
9  OC\Files\View->emit_file_hooks_pre() /srv/www/htdocs/owncloud/lib/private/files/view.php:374
10 OC\Files\View->rename() /srv/www/htdocs/owncloud/lib/private/files/view.php:482
11 OC_Connector_Sabre_File->put() /srv/www/htdocs/owncloud/lib/private/connector/sabre/file.php:137
12 OC_Connector_Sabre_Directory->createFile() /srv/www/htdocs/owncloud/lib/private/connector/sabre/directory.php:84
13 Sabre\DAV\Server->createFile() /srv/www/htdocs/owncloud/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php:1647
14 Sabre\DAV\Server->httpPut() /srv/www/htdocs/owncloud/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php:900
15 call_user_func:{/srv/www/htdocs/owncloud/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php:474}() /srv/www/htdocs/owncloud/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php:474
16 Sabre\DAV\Server->invokeMethod() /srv/www/htdocs/owncloud/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php:474
17 Sabre\DAV\Server->exec() /srv/www/htdocs/owncloud/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php:214
18 require_once()  /srv/www/htdocs/owncloud/apps/files/appinfo/remote.php:61
19 {main}          /srv/www/htdocs/owncloud/remote.php:54
```

**Comment by PVince81** [comment]
It looks like the cache entry for the file isn't there yet, but encryption is trying to call `getUidAndFilename()` on it to find out who has access.

Not sure if this is hiding a bug or expected.

Removing the warning should be trivial but I'd like @icewind1991 or @schiesbn to have a quick look to confirm that this is expected.

**Comment by PVince81** [comment]
This only happens for newly created files.

This is the cache entry that gets passed to `checkUpdate()` in the trace above:
```
$data                            = (array[8]);
  $data['permissions']           = (int) '0';
  $data['parent']                = (string[2]) '38';
  $data['mimetype']              = (string[24]) 'application/octet-stream';
  $data['encrypted']             = (bool) '1';
  $data['unencrypted_size']      = (int) '4';
  $data['displayname_owner']     = (string[5]) 'user2';
  $data['path']                  = (string[14]) 'Food/test5.txt';
  $data['uid_owner']             = (string[5]) 'user2';
```

It has neither id, nor mtime nor storage_mtime. Possibly created on the fly as this is a new fly.

**Comment by MatteoMora** [comment]
Still open?

**Comment by PVince81** [comment]
Thing is, it is easy to make the warning disappear by adding an extra `if isset` block.
My concern is that it might hide a programming error that needs to be looked into.

**Comment by fossxplorer** [comment]
I see this as well using current stable8.1 without encryption.

**Comment by PVince81** [comment]
Hss anyone seen this in recent versions like 9.0.2 ?

**Comment by PVince81** [comment]
Not reproducible in 9.1.0beta2.
