### ISSUE TITLE
Consolidate database API

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13779]
So far I've seen several different ways of making database calls:

1) Using `OC_DB`
2) Using `OCP\DB`
3) Using the entity mapper from the app framework

Then there is `execute()` and `executeAudited()`.
Some are using our "statement wrapper" and others aren't.

We need to clean up this mess and make **one** single way for doing database queries.
Or at least two: the regular DB queries and one with the entity mapper would be acceptable.

In the short/middle term it should be possible to already replace many of the calls with `OCP\DB`.

Then my next problem is that they work with the statement wrapper which itself wraps too much and doesn't allow for `closeCursor()` to be called.

- [ ] add "close()" to statement wrapper
- [ ] OR get rid of the statement wrapper completely
- [ ] replace `OC_DB` usage with `OCP\DB` (this will also prevent people to use `executeAudited` which is private

@DeepDiver1975 @bantu @icewind1991 @LukasReschke @schiesbn 

Note that I'm a bit struggling with this for the task to add `closeCursor` everywhere: https://github.com/owncloud/core/issues/10566

**Comment by DeepDiver1975** [comment]
:+1: for this cleanup

**Comment by LukasReschke** [comment]
Fully agreed as well. – Makes it also a pita to search for SQL queries in the code since there are multiple possible constructs etc…

**Comment by PVince81** [comment]
We agreed to settle with the query builder, closing in favor of https://github.com/owncloud/core/issues/12502
