### ISSUE TITLE
Move files + update cache one by one instead of bulk update

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13775]
When moving a huge folder, the following happens:
1) Every file is moved one by one to the target folders (sometimes even copied in cross-storage situations)
2) The cache is updated at the very end, for all files

If a PHP timeout occurs and/or the process is killed, the discrepancy between cache and filesystem is very big.

We should rather move the files one by one, and for each moved file, update the cache directly.
This way at if there is a crash, the database would still be in sync with the last change. The unmoved files would still be in their old location with their matching cache entries. The most damage that would happen is a single broken file.

@icewind1991 @MorrisJobke @DeepDiver1975 what do you think ?

But on a local FS I'd still expect the FS `rename()` to be atomic, so the benefit would mostly be on non-local storages. But even for local storages, the huge final DB update for all the entries might be huge and take time.

**Comment by PVince81** [comment]
@icewind1991 can you please comment on this ? It might be the solution for https://github.com/owncloud/core/issues/13391

**Comment by icewind1991** [comment]
For cross storage moves this seems good

**Comment by PVince81** [comment]
@icewind1991 I think the problem here https://github.com/owncloud/core/issues/13391 was about local moves. It's just the cache that takes too much time to update at the end, or there is a time window where the disk content and cache are completely different. We need to shrink that time window as much as possible (unless we can come up with a better solution, some kind of locking?)

**Comment by icewind1991** [comment]
#13948 for the cache issue

**Comment by PVince81** [comment]
Problem was fixed through transactional file locking.
