### ISSUE TITLE
[stable7] oracle unit test failing

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#13788]
https://github.com/owncloud/core/pull/13752
https://github.com/owncloud/core/pull/13772

**Comment by DeepDiver1975** [comment]
@PVince81 this is broken since 234f33e01e630f763f34c51114d25986bae02b42

Looks like the oracle implementation behaves different when it comes down to closing the cursor

````
{"app":"PHP","message":"Undefined variable: htaccessWorking at \/home\/deepdiver\/Development\/ownCloud\/stable7\/core\/setup\/controller.php#156","level":3,"time":"2015-01-30T13:55:14+00:00"}
{"app":"PHP","message":"oci_bind_by_name(): 311 is not a valid oci8 statement resource at \/home\/deepdiver\/Development\/ownCloud\/stable7\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/OCI8\/OCI8Statement.php#125","level":3,"time":"2015-01-30T13:55:17+00:00"}
{"app":"PHP","message":"oci_bind_by_name(): 311 is not a valid oci8 statement resource at \/home\/deepdiver\/Development\/ownCloud\/stable7\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/OCI8\/OCI8Statement.php#125","level":3,"time":"2015-01-30T13:55:17+00:00"}

**Comment by nickvergessen** [comment]
Title says stable7, but milestone is 8.0
Does this affect both, or just one of them?

**Comment by DeepDiver1975** [comment]
> Title says stable7, but milestone is 8.0
> Does this affect both, or just one of them?

I'm currently reevaluating master on this ....

**Comment by DeepDiver1975** [comment]
doctrine version change between 7 and 8 - this could be one reason why this is only failing on stable7 so far

**Comment by MorrisJobke** [comment]
@DeepDiver1975 But once OCI isn't tested in the PR-analyzer this wouldn't have been noticed earlier too:(

**Comment by DeepDiver1975** [comment]
no issue on master - stable7 related only

**Comment by DeepDiver1975** [comment]
@PVince81 I vote for revert of 234f33e in stable7

**Comment by MorrisJobke** [comment]
@DeepDiver1975 Could this be fixed by the update of doctrine, that is currently open as a PR?

**Comment by MorrisJobke** [comment]
ref #13798

**Comment by nickvergessen** [comment]
@MorrisJobke wrong link?

**Comment by nickvergessen** [comment]
Made a patch for the revert

**Comment by MorrisJobke** [comment]
@nickvergessen No this is the update of the sabre dav component in stable7. Is it the mentioned difference between stable7 and master that caused this breakage?

**Comment by nickvergessen** [comment]
@MorrisJobke the difference in doctrine, not in sabre-dav
these are two different independent dependencies

**Comment by MorrisJobke** [comment]
@nickvergessen I know ... sorry my fault

**Comment by DeepDiver1975** [comment]
close as #13803 is merged now
