### ISSUE TITLE
Public share site leaks information about mounts being used

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#13789]
It displayes the icon for external storage folders.
However, this information should not be given to public.
Instead the normal folder icon should be used.

![bildschirmfoto vom 2015-01-30 11 13 47](https://cloud.githubusercontent.com/assets/213943/5974160/472ca49c-a871-11e4-8c7a-08c9b995a8f1.png)

cc @PVince81

**Comment by rullzer** [comment]
It took some digging trough the code but I just created PR #14341 which should fix this.
