### ISSUE TITLE
Importing a VCF that was exported from the same OC instance does not work

### ISSUE THREAD

**Issue by wbergner** [owncloud/core#13783]
Having exported my contacts from my OC installation, I wanted to re-import them a few days later, which did not succeed. There was no update in between. I am using the most recent version 7.0.4. No error is shown after the import, only:
Total:0; Success:0; Errors:0

I figured out that once I removed all lines starting with "NOTE:", the import worked, even with automatic format detection. However, for roughly 100 contacts, it took quite some time, about 1 minute or so.

Please also have a look at http://forum.owncloud.org/viewtopic.php?f=29&t=25719

**Comment by MorrisJobke** [comment]
As this is a calendar issue, I would like to ask you to open this in the calendar bug tracker: https://github.com/owncloud/calendar/issues Thanks

**Comment by RealRancor** [comment]
@wbergner 
When re-opening in the calendar tracker it's also recommended to use the issue template provided here:

https://raw.github.com/owncloud/core/master/issue_template.md

as asked in the "guidelines for contributing" (linked in the box shown when creating a new issue).
