### ISSUE TITLE
Fix SSL setup - SSLLabs-Rating is only F because of insecure SSL2 support

### ISSUE THREAD

**Issue by braegel** [owncloud/core#13785]
https://www.ssllabs.com/ssltest/analyze.html?d=apps.owncloud.com

**Comment by LukasReschke** [comment]
@karlitschek

**Comment by RealRancor** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=owncloud.org

could also get some improvements.

**Comment by DeepDiver1975** [comment]
From my understanding this is why I'm not able to install any app from the appstore. I'm running Debian Testing. 

@karlitschek this is rater critical from my pov as this would leave many installation broken with respect to installing apps from the appstore.

**Comment by LukasReschke** [comment]
This is a unrelated issue. – The SSL configuration itself has nothing to do with the certificate chain.

**Comment by karlitschek** [comment]
agreed. i will look into that.

**Comment by Sugaroverdose** [comment]
Apache config: 
```
SSLCipherSuite ECDH+AESGCM256:DH+AESGCM256:ECDH+AES256:DH+AES256:DH+AES256:EECDH+AES128:DH+AES128:RSA+AESGCM256:RSA+AES256:RSA+AESGCM128:RSA+AES128:RSA+3DES:!aNULL:!MD5:!DSS
SSLProtocol All -SSLv2 -SSLv3
```
*cipher supports almost all browsers except IE6(if dh>1024 java6 also become unsupported), but secure.
here's my results https://www.ssllabs.com/ssltest/analyze.html?d=f.hq.pe (i've dropped 'RSA+3DES' cipher in my case, just because i don't need to support IE8)

**Comment by RealRancor** [comment]
https://bettercrypto.org/ also provides an awesome overview for a SSL config of various services.

**Comment by khlem** [comment]
Hello,

Apache2 SSL.CONF in mods-available

SSLHonorCipherOrder on
SSLCipherSuite AES256+EECDH:AES256+EDH:HIGH:!aNULL:!MD5:!EDH:!RC4

SSLProtocol -All +TLSv1 +TLSv1.1 +TLSv1.2

Restart apache2 and try : https://www.ssllabs.com/ssltest/analyze.html?d=apps.owncloud.com

The score is A- or A+ depends of your certificate.

Regards,

Clément.

**Comment by Sugaroverdose** [comment]
At this moment freebsd servers can't connect to apps.owncloud.org because of curl 7.40 which have dropped sslv3(and you should, because of poodle) and this is only way to connect to apps.owncloud.org (tlsv1 broken, looks like same cert defined in multiple virtual hosts) can it be fixed asap?

**Comment by LukasReschke** [comment]
@Sugaroverdose It's https://apps.owncloud.com/

**Comment by Sugaroverdose** [comment]
@LukasReschke sorry for typo, written comment after several hours of troubleshooting :)

**Comment by karlitschek** [comment]
should be fixed now

**Comment by RealRancor** [comment]
@karlitschek 
Enabling TLS 1.1 and TLS 1.2 (if the installed openssl version is supporting them) and disabling TLS compression could be still also a good idea:

https://www.ssllabs.com/ssltest/analyze.html?d=apps.owncloud.com
https://www.ssllabs.com/ssltest/analyze.html?d=owncloud.org

**Comment by Sugaroverdose** [comment]
@karlitschek :+1:
