### ISSUE TITLE
webdav performance slow, ubuntu server and client

### ISSUE THREAD

**Issue by gentooza** [owncloud/core#13795]
Hi owncloud team!

I've configured an owncloud server from offficial respoitories within an ubuntu server 14.04
I've follow the official administration installation guide, installing also the php-xcache complement.

My net is a local net at home by a switch.

The problem is when uploading files to the server, it's completely unusable, with transference rates of only 16kb/s
Whe downloading is terrible also, begining quick (5Mb/s) but finishing at (900Kb/s)

Also, Before, I had prepared the server in a little weaker server (Pentium 4) with debian/kfreebsd with same result.

What could be the problem?
I'm ready to show hardware/software information about my system

Thank you very much!
Joa

**Comment by karlitschek** [comment]
There are some performance tip. I suggest to ask this question on the forum to get more help. Thanks

**Comment by gentooza** [comment]
Well,
- I've already tested owncloud in two different systems
- I've already tested webdav mounting in two different clients
- I've followed the official documentation, twice
- I've already applied optimization tools like php-xcache
- I think that 16kbs/sec should not be treated as an optimization issue, it's a fail
- I have followed the Arch linux instructions, and the apache 2.2 optimization guide, and also the owncloud enterprise optimization doc.

As I see, you have a Free Software enthusiastic here spending his time testing the community software, so you can either close and ask users to be professional hackers beyond the official owncloud package and docs. Or open, understanding there is some fail/bug in code or documentation and try together to solve it
Also, it seems to be something general
https://bugs.launchpad.net/ubuntu/+source/davfs2/+bug/185986
http://forum.owncloud.org/viewtopic.php?p=47063
https://github.com/owncloud/core/issues/7072

thanks, and happy hacking

**Comment by gentooza** [comment]
OK!

a week after, I personally also close this already buried (by project admins) issue.
I continue with the same problem with no hope of having feedback from the developers.

I'm migrating now my server and my efforts to a more community friendly project as seafile.
http://seafile.com/en/home/

Thanks, and happy hacking

**Comment by apple601601601** [comment]
The same problem with me. Owncloud works ok with the synchronizer software with full speed(in LAN).
However when I use webdav, no matter from a webdav client software or windows default webdav Client, it's extremely slow and totally unuseable.

**Comment by mwaeckerlin** [comment]
WebDAV in OwnCloud is definitively a pain in the ass, even in a LAN.
