### ISSUE TITLE
Fatal error: Call to a member function getSession() on a non-object

### ISSUE THREAD

**Issue by jkroepke** [owncloud/core#13808]
### Steps to reproduce
1. Download owncloud
2. Open URL on Browser
3.

### Expected behaviour
Show the owncloud Installer

### Actual behaviour
Fatal error:  Call to a member function getSession() on a non-object in .\owncloud\lib\private\template.php on line 53

### Server configuration
**Operating system**: Windows 7 x64

**Web server:** Apache 2.4.7

**Database:** MySQL 5.6.15

**PHP version:** 5.6.4

**ownCloud version:** 8 RC1

**Updated from an older ownCloud or fresh install:** No

**List of activated apps:** N/A (Default)

**The content of config/config.php:** No config available.

```
No config available.
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

### Client configuration
**Browser:**
Chrome
**Operating system:**
Windows 7 x64
#### Web server error log
```
[Sat Jan 31 14:19:26.059290 2015] [:error] [pid 7460:tid 764] [client 127.0.0.1:51893] PHP Fatal error:  Call to a member function getSession() on a non-object in .\\owncloud\\lib\\private\\template.php on line 53, referer: http://127.0.0.1/projects/
```

#### ownCloud log (data/owncloud.log)
```
N/A
```

### Additional Infos:

I added a own debug_print_backtrace before line 56
````
#0  OC_Template->__construct(, error, error, ) called at [.\owncloud\lib\private\template.php:206]
#1  OC_Template::printErrorPage(Composer autoloader not found, unable to continue.) called at [.\owncloud\lib\base.php:481]
#2  OC::init() called at [.\owncloud\lib\base.php:1007]
#3  require_once(.\owncloud\lib\base.php) called at [.\owncloud\index.php:26]


Fatal error:  Call to a member function getSession() on a non-object in .\owncloud\lib\private\template.php on line 53
````

Btw, Now I know, the composer is missing.

**Comment by MorrisJobke** [comment]
@jkroepke Thanks for the report. Where did you get ownCloud from? Github archives of a tag aren't supported. Possible ways to get this are the official tar balls or a git clone.

**Comment by MorrisJobke** [comment]
How to reproduce:

* fresh master
* `rm 3rdparty/autoload.php`

Should we support this case? Would propably need additional rearrangements in base.php :(

**Comment by MorrisJobke** [comment]
@jkroepke Can you test this: https://github.com/owncloud/core/pull/13809

**Comment by jkroepke** [comment]
Hi,

I used the releases from this github repo .

Anyway it fixed. Now the error message is displayed as expected.

As an improvment, i would like to say instead.

```Composer autoloader not found, unable to continue.```

somethink like

```Composer autoloader not found, unable to continue. 3rdparty files are correct?```

But this is maybe an another case.

Thank you.
