### ISSUE TITLE
Password reset doesn't comply with Content Security Policy

### ISSUE THREAD

**Issue by Comarco** [owncloud/core#13800]
I have this error in my browser console:

`Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://example.com 'unsafe-eval'").`

I don't really know if it is related but owncloud version 7.0.4 on my server gives you an error when you fail the login, instead of beautifull inline JS that should send an email to the user, it shows a white page with big characters saying : 

`LOGGG SELECT user_login,user_pass FROM users WHERE user_login = "johndoe" AND user_status = 0`

I did not find much on google aboout thsi error, but it looks like this is a way the browser is protecting against XSS... 

> This ban includes not only scripts embedded directly in script tags, but also inline event handlers and javascript: URLs. You’ll need to move the content of script tags into an external file, and replace javascript: URLs and <a ... onclick="[JAVASCRIPT]"> with appropriate addEventListener calls. For example, you might rewrite the following from:

http://www.html5rocks.com/en/tutorials/security/content-security-policy/#inline-code-considered-harmful

note, my email settings are tested correctly in the admin interface.

**Comment by LukasReschke** [comment]
1. Please use the issue template
2. Google shows that this is most likely related to this plugin https://apps.owncloud.com/content/show.php/CloudPress?content=154756

**Comment by Comarco** [comment]
Hi, 

1. I don't use the cloudpress plugin.
2. I did not see any isue template. It is already the second time I report this, once it was not on the right issue (which I understand), now I need to use a issue template which is not obvious.

Isn't there an issue with Content Security Policy ?

**Comment by LukasReschke** [comment]
From the link on the yellow notification when creating an issue: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by Comarco** [comment]
ok, sorry for not doing my contributing job correctly. I thought it would be usefull. If it is not, I have spend enough time on this for now. Do whatever you want with this, it is just a little research I made before publishing this one. May be I'm completely wrong and everyhthing is super fine ;)
