### ISSUE TITLE
Maybe folder name causing "400 bad request" error, preventing sync on Win8/8.1/10

### ISSUE THREAD

**Issue by joshi07** [owncloud/core#13806]
i had a folder named "NP++" and until i renamed it, i had a csync failed error, 400 bad request so i wasnt able to sync.

i found this :
"csync_ftw: opendir failed for ownclouds://xxx.xx/ownCloud/remote.php/webdav/zzz_Privat"

in the logs and decided to rename the the subfolder "NP++" to "NP"  and well now it works!

Seems like Opendir method cant handle the "++" in the name. but only on Win 8/8.1 and 10.

on WIn7 i synced the folder to the web so this seems fine!

**Comment by joshi07** [comment]
as i tried to reproduce the error, it happened again, but renaming the folder a 2. time wasn't doing any good, so im stuck with no sync again :-(

**Comment by RealRancor** [comment]
Hi,

please use the issue template provided here:

https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

as asked in the "guidelines for contributing" (linked in the yellow box when creating a new issue).

**Comment by MorrisJobke** [comment]
@danimo @dragotin Did you ever tested with Windows 8/10? Looks like maybe something bad happened there. If you have a test instance, can you try to sync a folder named "NP++"?

**Comment by joshi07** [comment]
### Steps to reproduce
Install owncloud on Win8 or Win10

try to sync with an already filled (by win 7  OC client, android OC client) webspace lying at OVH shared hosting.


### Expected behaviour
Sync with OC server

### Actual behaviour
This is in the logs of the client.

01-31 11:17:31:849 0xb91198c oc_module: Call the csync callback for ownCloud
01-31 11:17:31:881 0xb91198c oc_module: Neon error code was 1
01-31 11:17:31:881 0xb91198c oc_module: WRN: propfind named failed with 1, request error: 400 Bad Request
01-31 11:17:31:882 0xb91198c oc_module: fill_recursive_propfind_cache /remote.php/webdav Server maybe did not give us an 'infinity' depth result
01-31 11:17:31:882 0xb91198c oc_module: get_listdir_context_from_recursive_cache No cache
01-31 11:17:32:953 0xb91198c oc_module: Simple propfind result code 207.
01-31 11:17:32:954 0xb91198c oc_module: opendir returning handle 0a207c60 (count=4)
01-31 11:17:32:954 0xb91198c csync_walker: directory: ownclouds://xxx.xx/remote.php/webdav/slider [file_id=00000005ocdd92866b32]
01-31 11:17:32:954 0xb91198c _csync_detect_update: file: slider, instruction: INSTRUCTION_NEW <<=
01-31 11:17:32:954 0xb91198c oc_module: opendir method called on ownclouds://xxx.xx/remote.php/webdav/slider
01-31 11:17:32:987 0xb91198c oc_module: Neon error code was 1
01-31 11:17:32:987 0xb91198c oc_module: Neon error code was 1
01-31 11:17:32:987 0xb91198c oc_module: WRN: propfind named failed with 1, request error: 400 Bad Request
01-31 11:17:32:988 0xb91198c oc_module: Errno set to 22
01-31 11:17:32:988 0xb91198c csync_ftw: opendir failed for ownclouds://xxx.xx/remote.php/webdav/slider - errno 22
01-31 11:17:32:988 0xb91198c csync_statedb_close: sqlite3_close=0
01-31 11:17:33:020 0x5759d90 syncengine.cpp:518  #### ERROR during  csync_update :  "CSync hat einen schwerwiegender Parameterfehler festgestellt. 400 Bad Request"
01-31 11:17:33:024 0x5759d90 syncengine.cpp:824 CSync run took  1969
01-31 11:17:33:030 0x5759d90 folder.cpp:836 -> SyncEngine finished with ERROR, warn count is 0
no sync, it shows a red cross in the task bar, the interface says csync has a fatal error, 400 bad request.

### Server configuration
OVH Shared Hosting 2014

SQLite

PHP Version 5.4.37

ownCloud 7.0.4 (stable) 

Freshly installed ca 2 weeks ago

**List of activated apps:**
no more than originally activated.

**The content of config/config.php:**
<?php
$CONFIG = array (
'trusted_domains' => 
  array (
    0 => 'XXX.XX',
    1 => 'XXXXX.XX',
  ),
  'datadirectory' => '/home/madelppsql/www/ownCloud/data',
  'overwrite.cli.url' => 'xxx.xxx',
  'dbtype' => 'sqlite3',
  'version' => '7.0.4.2',
  'installed' => true,
  'loglevel' => '0',
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
);


**Are you using external storage, if yes which one:** local/smb/sftp/...
no external storage

**Are you using encryption:** yes/no
i dont know, i guess not!

### Client configuration
Chromium, Iron, FF, IE

**Operating system:**
Windows 8/8.1/10 triple boot Computer

### Logs
#### Web server error log
shared hosting, no log....

#### ownCloud log (data/owncloud.log)
This is the only line when the sync fails

{"reqId":"54ccb268bb559","app":"webdav","message":"Sabre\\DAV\\Exception\\NotAuthenticated: No basic authentication headers were found","level":0,"time":"2015-01-31T10:46:00+00:00","method":"PROPFIND","url":"\/remote.php\/webdav"}


#### Browser log
since its no browser problem, no log!

**Comment by MorrisJobke** [comment]
Maybe related: #13398, #12146

@joshi07 Did you mount another public share to that folder or any subfolder? Either by getting a public link share and then clicking in the top right to "add to my owncloud" or by getting it directly from another owncloud instance: https://github.com/owncloud/owncloud.org/blob/ownCloudEight/assets/img/screenshots/server/eight/FederatedShare2.png
https://github.com/owncloud/owncloud.org/blob/ownCloudEight/assets/img/screenshots/server/eight/FederatedShare3.png

(those are ownCloud 8 screenshots and I'm not sure if they are already available in ownCloud 7, but it could be)

**Comment by MorrisJobke** [comment]
@LukasReschke Didn't you fixed some "Not authenticated" problems recently?

**Comment by joshi07** [comment]
@MorrisJobke i just shared the folder via link with a workmate which is why i cant reinstall OC server right now, which i would do if he didnt need that files for buissness.

but if its the share ( and the sync was already failing before i shared that folder.) why is the android and windows 7 client working fine ?  And even  the CarrotDAV is working from my windows 8 or 10.

**Comment by MorrisJobke** [comment]
@joshi07 So it just fails for the Windows 8/10 client? Can you lookup the apache access log? So we see which request come in and which one causes the 400?

**Comment by joshi07** [comment]
its a shared hosting by OVH i do not know how to take the apache access log from there since i have no SSH  for it :( sorry

**Comment by MorrisJobke** [comment]
@joshi07 Is the access log just from the time where just the Windows 8/10 client tried to connect?

**Comment by joshi07** [comment]
@MorrisJobke yes!

**Comment by MorrisJobke** [comment]
```
82.83.171.99 xxx.xx - [31/Jan/2015:12:40:46 +0100] "PROPFIND /remote.php/webdav HTTP/1.1" 401 292 "-" "Mozilla/5.0 (Windows) csyncoC/0.91.5 neon/0.30.1" 82.83.171.99 xxx.xx - [31/Jan/2015:12:40:46 +0100] "PROPFIND /remote.php/webdav HTTP/1.1" 207 2159 "-" "Mozilla/5.0 (Windows) csyncoC/0.91.5 neon/0.30.1"
```

Weird ... two propfinds to the same resource with different response o.O

@dragotin @danimo Is this normal behaviour or maybe caused by this issue? Usually the folder is part of the URL in a PROPFIND, isn't it? So this is a PROPFIND to the root folder?

**Comment by MorrisJobke** [comment]
I just tried it and it looks good :(

```
$ curl -u mjob:mjob -X PROPFIND http://localhost/master/remote.php/webdav
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   650    0   650    0     0   5228      0 --:--:-- --:--:-- --:--:--  5241
```

```xml
<?xml version="1.0" encoding="utf-8"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns">
  <d:response>
    <d:href>/master/remote.php/webdav/</d:href>
    <d:propstat>
      <d:prop>
        <oc:id>00000003ocgzoerbcimi</oc:id>
        <oc:permissions>RDNVCK</oc:permissions>
        <oc:size>0</oc:size>
        <d:getetag>"54ccd070b3835"</d:getetag>
        <d:getlastmodified>Sat, 31 Jan 2015 12:54:08 GMT</d:getlastmodified>
        <d:resourcetype>
          <d:collection/>
        </d:resourcetype>
        <d:quota-used-bytes>0</d:quota-used-bytes>
        <d:quota-available-bytes>9250074624</d:quota-available-bytes>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
</d:multistatus>
```

Currently I have no idea, why the first PROPFIND fails and the second not (and why there are two propfinds at the exact same time at all)

Maybe wait for the others ;)

**Comment by joshi07** [comment]
if i can provide any more information or even a Teamviewer session since were both germans, i would be happy to help.

Greetings

**Comment by MorrisJobke** [comment]
@joshi07 Thanks. But I guess we need to wait for monday and then have a look at this together with other devs.

**Comment by joshi07** [comment]
@MorrisJobke  i hope this is not my fault :o config error or such. ... but thanks anyway :)

**Comment by dragotin** [comment]
The two PROPFINDs are fine, the 401 comes in reply to a non authenticated PROPFIND, and the client than trries again with credentials which results in 201. 

You say it works with the win7 client, but not with the client on win8 or 10. What file systems are used on that systems? And, do we know which operating system runs on the server?

**Comment by MorrisJobke** [comment]
They just provide some infos about their product: http://cluster015.ovh.net/infos/ is the config for https://www.ovh.de/hosting/hosting-basic.xml 

@dragotin What do you want to know exactly?

@joshi07 Do you have any additional info?

**Comment by LukasReschke** [comment]
> @LukasReschke Didn't you fixed some "Not authenticated" problems recently?

Nothing that I could think of that could related to this.

**Comment by joshi07** [comment]
@MorrisJobke you got the informations right.

About the server... i do not have more informations than you do, since its a standard product and i have no acces to the hardware or operating system. 
But i am on cluster 11 so my link is http://cluster011.ovh.net/infos/

@dragotin since the Win 7 Client is my PC at work, i will see which filesystem is there.
here at home i am using NTFS which, i think, is the same at my workplace, but im not 100% sure.

I will try a Virtual mashine with W7 to see if my home network is the issue or the operating system.
Maybe its an issue with my home router? (fritzbox) on the other hand, android is working fine.

Both my Windows 8 and 10 systems are also freshly installed. Not even 1 week old.

**Comment by joshi07** [comment]
without doing anything, it started syncing today morning, is still going. i have no idea why ?! O,o

**Comment by MorrisJobke** [comment]
@joshi07 Can you try to log the stuff the client is doing: http://doc.owncloud.org/desktop/1.7/troubleshooting.html#saving-files-directly Maybe this helps.

**Comment by MorrisJobke** [comment]
@joshi07 Any news on this?

**Comment by MorrisJobke** [comment]
There wasn't any complain about this anymore. I will close this due to inactivity.
