### ISSUE TITLE
Missing shares after upgrade to OC6.0.6

### ISSUE THREAD

**Issue by iliyasbasir** [owncloud/core#13805]
### Expected behavior

Customer upgraded from ownCloud 6.0.5 to 6.0.6 after upgrade customer ; 

Under  specific account ,  create a directory A and share it with group one group (group :X). None of the members in group X  see this directory.
Same directory share it with members in other group (group:Y), they see directory A under their Shared directory.
Customer testing at 6.0.2  behaviors normal 

### Actual behavior

Both Group would able to view directory

### Steps to reproduce

1) In my personal system I'm unable re-produced issue.

 During Go-to meeting we have customer take following step:
    1) Add one test file add to specific group share with other group
         -log in to the first group as user view file fine
        - log in to second group as user can not view file 
    2) Have customer run oc_Share table
         - oc_share table look good we can view newly add test file on both group
    3) we have customer verify  LADP setting on DB
         - All ldap seeting look good both group define correctly
   4) During 6.0.5 to 6.0.6 upgrade group/user get carried over good
   5) Have customer run ./occ files:scan --all 
        - Noticed error on log full log at S3 but bellow is error 
    
              " PHP Fatal error:  Maximum function nesting level of '100' reached, aborting! in        /var/www/html/owncloud/3rdparty/symfony/console/Symfony/Component/Console/Formatter/OutputFormatterStyleStack.php on line 99"

###### Database: mysqld  Ver 5.5.30-log for solaris11 on i386 (Source distribution) (percona on an openindiana box)

openldap-2.4.23-34.el6_5.1.x86_64 is installed on our ldap server (RHEL 6.5)
PHP version:php55-5.5.10-1.el6.x86_64

###### Storage backend: NFS mount from a DDN "nfs gateway". http://www.ddn.com/products/object-storage-web-object-scaler-wos/

Client configuration

Client version:

###### OS language: LANG=en_US.UTF-8

Installation path of client:

### Logs & other config detail 

Logs can be found at s3 under github-issues/core/13805
@MorrisJobke @bboule

**Comment by LukasReschke** [comment]
@MorrisJobke Have fun

**Comment by MorrisJobke** [comment]
@iliyasbasir I couldn't find the logs. What groups are this? From a backend (LDAP groups for example) or are that owncloud native groups created in the user management? Is there anything special to that groups? (weird characters in the name or a `,` in the name)

**Comment by iliyasbasir** [comment]
@MorrisJobke : my bad i'm  still type down and accidentally click on submit button...i will send all detail soon...

**Comment by MorrisJobke** [comment]
@iliyasbasir Simply update your initial post ;)

**Comment by LukasReschke** [comment]
> " PHP Fatal error: Maximum function nesting level of '100' reached, aborting! in /var/www/html/owncloud/3rdparty/symfony/console/Symfony/Component/Console/Formatter/OutputFormatterStyleStack.php on line 99"

Wait… you're using XDebug in a production environment?!?

**Comment by MorrisJobke** [comment]
> Have customer run ./occ files:scan --all

Yes. This will destroy all shares. No way to recover them once this is done.

**Comment by iliyasbasir** [comment]
@MorrisJobke This been suggest by Carlos D to run ./occ files:scan --all

**Comment by iliyasbasir** [comment]
@MorrisJobke This been  run to troubleshot issue ...this share issue was there before.

**Comment by iliyasbasir** [comment]
@MorrisJobke : Can you please have some one look this issue. thx

**Comment by DeepDiver1975** [comment]
@blizzz did we backport all this uid magic to stable6 as well?

**Comment by iliyasbasir** [comment]
@MorrisJobke : Customer is waiting for response ..any help would be appreciated

**Comment by blizzz** [comment]
not sure which uid magic you mean. For OC 7 we were just splitting up general uuid override to user and group specific ones, but that is it. don't remember anything else in this regard.

**Comment by DeepDiver1975** [comment]
> not sure which uid magic you mean.

I'm referring to the ldap uid issues we are experiancing on upgrade 7.0.3 to 7.0.4

**Comment by blizzz** [comment]
fairly unlikely

**Comment by enoch85** [comment]
Regarding missing shares: #14084

**Comment by bboule** [comment]
@iliyasbasir  wondering if we can spend some time trying to reproduce this, it would help in that we could see if a jump from 6.0.6 to an RC of 7.0.5 solves the issue in a test environment... You say the share appears in the share table how about the group in the ldap_group_mappings table post upgrade is the group still in that table?  Is there a chance the user was removed from the group (checking the user table).  Just some things we might be able to do... lets work Monday to reproduce this!!

**Comment by iliyasbasir** [comment]
Hopefully 7.0.5 will resolved issue.

Thank you
-Iliyas
