### ISSUE TITLE
[7.04] LDAP quota not updated

### ISSUE THREAD

**Issue by paveman** [owncloud/core#13801]
Hi,
we encountered a problem with the quota been read from Active Directory.
It will not be updated once it will be set to a new value such as 42 GB.
The old quota will persist for the user.
Clearing the cache will not resolve the problem.
Do you have any clue?

Debian Wheezy
Apache2 2.2
PHP 5.4
Owncloud 7.04 Enterprise
AD on Windows Server 2k8 R2

regards
 Peter

**Comment by karlitschek** [comment]
Please post a full bug report using our issue template.
https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

Thanks

**Comment by karlitschek** [comment]
@blizzz

**Comment by paveman** [comment]
### Steps to reproduce
1. Set custom attribute for quota in Active Directory (ownCloudQuota)
2. Fill it with a value like '42 G'
3. Set the attribute created in the OC backend.
4. Login and logout a user the quota has been setted.
5. Change the attribute value in AD to another.
6. Login with the user from step 4.

### Expected behaviour
quota should have the value from previous step 5.

### Actual behaviour
quota will remain with the value from previous step 2.

### Server configuration
**Operating system**:
Debian Wheezy 7.8

**Web server:**
Apache2 2.2.22-13+deb7u4

**Database:**
MySQL 5.5.41-0+wheezy1

**PHP version:**
PHP 5.4.36-0+deb7u3

**ownCloud version:**
ownCloud Enterprise Edition 7.0.4 (stable)

**Updated from an older ownCloud or fresh install:**
Update from OC6 Enterprise

**List of activated apps:**
Deleted files
First Run Wizard
LDAP user and group backend
Shared files
Text Editor
Versions

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '***',
  'passwordsalt' => '***',
  'datadirectory' => '/var/www/owncloud-enterprise/data',
  'dbtype' => 'mysql',
  'version' => '7.0.4.2',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'theme' => 'custom',
  'maintenance' => false,
  'log_type' => 'syslog',
  'logfile' => '',
  'loglevel' => '3',
  'trusted_domains' =>
  array (
    0 => 'myoc.tld',
    1 => 'mycloud.tld',
  ),
  'forcessl' => true,
  'default_language' => 'de_DE',
  'appstoreenabled' => false,
  'has_internet_connection' => false,
  'supportedDatabases' =>
  array (
    0 => 'mysql',
    1 => 'pgsql',
    2 => 'oci',
    3 => 'mssql',
  ),
  'secret' => '***',
  'share_folder' => '/Shared',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbuser' => 'owncloud',
  'dbpassword' => '***',
);

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
external NFS share

**Are you using encryption:** yes/no
no

### Client configuration
**Browser:**
Iceweasel
Firfox
Chromium
Opera

**Operating system:**
Debian Wheezy
Ubuntu Trusty

**Comment by blizzz** [comment]
It will  be updated once every 24h on a per user-base. Starting OC 8.1 we will refresh it more regularly. 

If it does not update in 24 hours, please reopen.

**Comment by issamo12** [comment]
I was looking for this comment for so long, thank you, i'm looking forward OC 8.1 now
