### ISSUE TITLE
Recommand: Turn on SPDY support in nginx example.

### ISSUE THREAD

**Issue by jinchizhong** [owncloud/core#13812]
Hi friend.
I notice here: In ownCloud [`Manual Installation`](http://doc.owncloud.org/server/6.0/admin_manual/installation/installation_source.html)
There is not turn SPDY on.
I strongly recommend turn it on, it can speed up a lot.(50%, even more)

It's very easy to turn it on.
Just change `listen 443 ssl;` to `listen 443 ssl spdy;`

**Comment by MorrisJobke** [comment]
I wil move this to the documentation repo. Thanks for the report.

**Comment by MorrisJobke** [comment]
https://github.com/owncloud/documentation/pull/806
