### ISSUE TITLE
Distinguish between CronJobs and BackgroundJobs/AsyncJobs

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#13816]
## Background
As of today we push both types of jobs to the jobqueue (\OCP\BackgroundJob\IJobList).

With the current implementation it kind of works for both scenarios because every time cron.php is executed all cron jobs which are added during execution of every app.php will be added to the queue as well as jobs which got inserted during previous execution paths.

## Problem

As soon as we will move on with this topic with respect to use real message queuing system this mechanism will no longer work because the job execution will either be dedicated worker process (which will not reload app.php files - while it could be during the transition phase) or explicit jobs are pushed into the application using push queues (see Iron.io push queues).

## Solution

Because it is anyhow pointless to add jobs during app's initialization (in terms of why add a job for a request to deliver e.g. the setting page) a dedicated entrypoint seems to be best for cron jobs.
This could be a cron.php living in the appinfo folder or entries in the info.xml - to be discussed.

CronJobs will be executed using the existing cron mechanisms (system cron, web cron or ajax) and in case no job queue system is available/configured this can be used as fallback.

Async jobs will be added via the existing interface \OCP\BackgroundJob\IJobList including some necessary extensions to allow job queuing. From an implementation pov we can get some inspiration from https://github.com/laravel/framework/tree/4.2/src/Illuminate/Queue - especially the implementation of http://laravel.com/docs/4.2/queues#push-queues is relevant to enable ownCloud installations to use message queuing even if there is no such system available in smaller installations.

**Comment by DeepDiver1975** [comment]
@MTRichards do we have any understanding on the market regarding message queuing systems used in the target enterprises? THX

**Comment by DeepDiver1975** [comment]
Interesting implementation detail: serialization of closures - this would give us more power when moving jobs to the jobs queue - https://github.com/laravel/framework/blob/4.2/src/Illuminate/Queue/Queue.php#L69

```php
\OC::$server->getJobQueue()->push(function() use ($fileName, $previewManager) {
    $previewManager->generatePreview($fileName);
);

**Comment by MTRichards** [comment]
If we are talking about embedding something internally, I am not sure it really matters what the enterprise is using. That said, there are a few vendors - IBM, VMware, Tibco, Progress (Iona) and many more have a form of Advanced Message Queue software.

For open source MQ systems, the biggest Market Share with a large active community seems to be Rabbit MQ.(Acquired by SpringSource)
Others include Open AMQ, Apache Qpid, Red Hat Enterprise MRG.and a few more.

It is worth mentioning the protocol at work if looking for a queue system across hosts (such as distributed ownClouds):
The Advanced Message Queuing Protocol (AMQP) is an emerging standard for message-oriented middleware (MOM). MOM supports high quality-of-service, asynchronous program-to-program communication between two or more components of an application, or between two or more applications. AMQP specifies the wire protocol, so messages can be exchanged among software components supplied by different vendors without the need for gateways or adapters.

**Comment by MTRichards** [comment]
Net of the above: there is no one vendor, though AMQP seems to be the important protocol.

**Comment by DeepDiver1975** [comment]
> If we are talking about embedding something internally, I am not sure it really matters what the enterprise is using.

It does from my perspective - it's just like with databases. Usually enterprises have a defined tech stacj for their systems. E.g. they already have Oracle DBMS up and running and do not want to maintain a mysql cluster. Same goes for Message Queuing Systems.



> The Advanced Message Queuing Protocol (AMQP) is an emerging standard for message-oriented middleware (MOM).

This is indeed the path to follow - thx for the input.

**Comment by DeepDiver1975** [comment]
Regarding AMQP support we want to look into https://github.com/ForumHouseTeam/laravel-amqp

**Comment by DeepDiver1975** [comment]
Requirement:
- [ ] jobs need an attribute to tell the execution system whether file content needs to be accessed - in case of encryption the job can not be executed outside the user context

**Comment by DeepDiver1975** [comment]
Having #14300 merged this ticket mainly seems to be resolved.



> Because it is anyhow pointless to add jobs during app's initialization (in terms of why add a job for a request to deliver e.g. the setting page) a dedicated entrypoint seems to be best for cron jobs.
> This could be a cron.php living in the appinfo folder or entries in the info.xml - to be discussed.
> 
> CronJobs will be executed using the existing cron mechanisms (system cron, web cron or ajax) and in case no job queue system is available/configured this can be used as fallback.

^ this has to be addressed to some extent - from an API pov we shall cleanly make a difference here.

**Comment by PVince81** [comment]
Anything left to do for 8.1 ?

**Comment by DeepDiver1975** [comment]
> Anything left to do for 8.1 ?

no - we will continue to enhance this in 8.2

**Comment by DeepDiver1975** [comment]
basically we can close this one and move #15460 to 8.2

**Comment by PVince81** [comment]
Done
