### ISSUE TITLE
Pre_login hook cannot prevent a login during hook execution even though it should be possible

### ISSUE THREAD

**Issue by ShamimIslam** [owncloud/core#13814]
There is a class of users that are never allowed to login, but have accounts. These users are those that have been terminated by HR but they have created content and files that are now owned by the company. They are the disabled users.

Pre-Login cannot set $uid to nothing. Emit does not return a value so it needs to have the value passed by reference. Should be able to prevent these users from resetting passwords as well, but that is not honored in the current hooks for pre_setPassword.

Correction should be to pass $uid by reference (&$uid instead of $uid)

```
            $uid = $backend->getCurrentUserId();
            $run = true;
            OC_Hook::emit( "OC_User", "pre_login", array( "run" => &$run, "uid" => $uid ));

            if($uid) {
                    self::setUserId($uid);
                    self::setDisplayName($uid);
                    self::getUserSession()->setLoginName($uid);

                    OC_Hook::emit( "OC_User", "post_login", array( "uid" => $uid, 'password'=>'' ));
                    return true;
            }
```

**Comment by PVince81** [comment]
@LukasReschke is there a better API to kill a user's session ?

**Comment by PVince81** [comment]
Or maybe we need an option "disable user" in the users page, which would be cleaner.

**Comment by LukasReschke** [comment]
That would be https://github.com/owncloud/core/issues/12601 then.

**Comment by ShamimIslam** [comment]
I've created an app that does this. But it requires a change in the
checkPassword function. Because the "pre_login" does not execute every time
nor does it allow me to intercept the call.

**Comment by shahank** [comment]
@ShamimIslam : i am facing same issue. can you please help me on that.
My case : when user going to login in to own cloud system.  i want to call pre-login hook and base on that i am calling API for CRM to check whether user is exist or not in CRM. if User exist in CRM it allows user to enter in own cloud system. if user not exist in CRM it will create new user in own cloud system.

can you please guide for the same.

Any body can help me on that. It will be great help, as i am new to own cloud.
Please response on this.

Thanks in Advance.

**Comment by karakayasemi** [comment]
As explained in https://github.com/owncloud/core/issues/16908, `$run` is deprecated. An app can prevent login in `preLogin` event by throwing an Exception like Brute Force Protection app does. For these reasons, I'm closing this issue.
