### ISSUE TITLE
Add basic html compatible fallback interface

### ISSUE THREAD

**Issue by treaki** [owncloud/core#13815]
I tried today to use ownlcoud with an mobile device (pda) which wasn't the most recent model... I was able to download the file i needed but not without much problems.

From using other web services (like web mail (example try gmail without javascript) i am used to have an fallback webinterface that is working also without css/javascript capable devices. I think that is a good praxis. I would be glad if you could add one feature for an interface that with an grate usability without having css and javascript.

Here i send you some screenshots created from the minimalistic, but very fast and reliable (i like it), browser links2. The view looks much like that ive got on my mobile device (pda):

![screenshot from 2015-02-01 22 25 31](https://cloud.githubusercontent.com/assets/1477872/5995107/1edad782-aa8a-11e4-8fc3-8c250b57ddd2.png)
![screenshot from 2015-02-01 22 25 37](https://cloud.githubusercontent.com/assets/1477872/5995108/20119654-aa8a-11e4-89ca-b8def87b644a.png)
![screenshot from 2015-02-01 22 25 45](https://cloud.githubusercontent.com/assets/1477872/5995109/2241fd74-aa8a-11e4-9e5a-1ea3bba6d499.png)

You can see that there are statements inapplicable to the current situation. Its looks like if that textes are normally hidden by css. You should add ad least some warning for users without css/javascript that will prevent misjudgment that could result out of this messages. Also i would suggest doing it like gmail dose, show while the javascript/css things are loarding (static content) a link to an basic html version of the owncloud interface. So that users who atnt using css/javascript at all will see that link first and will be able to switch to the basic html version.

for me its dosnt look like there is much to do to implement a basic html mode because downloading in general are still working. its just need 
- copy all  related files to another directory like .../basic/
- remove all css/javascript stuff and make it look good on all browsers
- add an feature to load not everyting of that list, seperate it in pages (like on not javascript aware web MUAs (web mail clients))
- add an basic file upload form (with the old api not with that javascript based new one) like <input type="file" ...> and something that manages basic upload on the backend site.
- improve that file selection and action stuff so that any action can be done with an file without javascript
- A search an complete file searches complete on the serverside and display the resoults as a new list.

i would appreciate if you could implement this

**Comment by MorrisJobke** [comment]
There should be an warning about missing JS: https://github.com/owncloud/core/blob/master/core/templates/layout.base.php#L27

And in our current state we really need it. The effort to do this doesn't sound much, but it actually is a huge work load, because we don't do the work twice (in frontend and backend). Feel free to work on something like that.

**Comment by treaki** [comment]
i am a little skilled in php programming, can i help?

**Comment by PVince81** [comment]
I'm not sure this is really in scope for adding in core, which would be yet another user interface to maintain.
However something to consider is making it possible for this to be implemented as an app.

It should already be possible to develop JS-less frontends for Webdav and deploy these in a separate namespace and connect them to ownCloud. Is there any JS-less frontend for Webdav out there ?

**Comment by DeepDiver1975** [comment]
Seriously - js less Web apps are dead. Sorry
