### ISSUE TITLE
OwnCloud Chunking Issue

### ISSUE THREAD

**Issue by LukeHamer** [owncloud/core#13818]
Hi Guys

We have an issue with one of the accounts which is setup through our OwnCloud server that is running version 7.0.4 (This server is Linux), the problem is a number of large files are unable to sync due to something known as chunking which we thought it possibly could have been a bug in version 6 which is why we attempted to upgrade he account.

The user has the latest version of the desktop client and the files that are failing to sync have a size of around 30-150MB  these files are in the following formats .Mov , .TIF , .ZIP and .PDF

This is the error we have from the webdav:
Fatal	webdav	Sabre\DAV\Exception\BadRequest: expected filesize 20971520 got 0	2015-01-30T14:44:33+00:00

Any assistance on what we can apply would be greatly appreciated :)

**Comment by MorrisJobke** [comment]
@LukeHamer Can you please fill out https://github.com/owncloud/core/blob/master/issue_template.md (especially the section about used apps)

**Comment by LukeHamer** [comment]
Steps to reproduce
1. Download the Latest version of the OwnCloud client 1.7.1
2. Set up the account with the provided details 
3. Select the folder containing various information as well as items such as .MOV files and .TIF files

Expected behaviour

The OwnCloud client should sync a copy up to our OwnCloud 7 server.

Actual behaviour

The files are unable to upload due to a chunking error and it skips out a large number of files.

Server configuration

Operating system: CentOS release 6.4 (Final)

Web server: Apache

Database: mysql

PHP version: PHP 5.5.20 (cli) (Built: Dec 20 2014 15:46:42)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies

ownCloud version: 7.0.4

Updated from an older ownCloud or fresh install: Fresh Install

List of activated apps: WebDav

The content of config/config.php:

<?php
$CONFIG = array (
  'instanceid' => 'oce5722f62ae',
  'passwordsalt' => '87ec51253916b3fb73e1903bf85857',
  'secret' => '645b8f71635a5762abf9bf6b36c23d29eef44aeda1c17239517d61abe1d3e8adec69a65ef1f509732de14ee49df7eed2',
  'trusted_domains' =>
  array (
    0 => '185.35.56.124',
    1 => 'owncloud.myfilesonline.co.uk',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'overwrite.cli.url' => 'http://185.35.56.124/owncloud',
  'dbtype' => 'mysql',
  'version' => '7.0.4.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'XXXXXXX',
  'dbpassword' => ‘XXXXXXXX',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'forcessl' => true,
  'loglevel' => '0',
);

Are you using encryption: no

Client configuration

Browser: Internet Explorer

Operating system: Windows 7 Service Pack 1

Logs

Web server error log
Fatal	webdav	Sabre\DAV\Exception\BadRequest: expected filesize 20971520 got 0	2015-01-30T14:44:33+00:00
ownCloud log (data/owncloud.log)

**Comment by LukeHamer** [comment]
Is there anything else you need info on?

**Comment by PVince81** [comment]
@LukeHamer yes, a slow connection speed increases the time it takes to upload the file. If that time is too big, there is a risk that PHP runs into a timeout situation, in which case it might abandon the transfer.

The error you saw about the expected filesize usually happens in such situations.

You could try increasing the PHP timeout value on the server.

**Comment by PVince81** [comment]
@LukeHamer are you still having this issue with OC 8.1.3 with the sync client 2.0.1 ? If yes, did you try increasing the timeout value ?
