### ISSUE TITLE
webDav locking is not working

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#13828]
### Expected behavior
A file opened over webdav should be locked

### Actual behavior
A file opended over webdav has no lock

### Steps to reproduce:

1. Mount a webdav directory in two different computers.
2. Share a file in both (if they are different users) 
3. open with the 2 computers the file

@MorrisJobke 

00002459

**Comment by DeepDiver1975** [comment]
refs https://github.com/owncloud/core/pull/5342
refs https://github.com/owncloud/core/issues/5267

known to be broken for a long time - currently this is a wont-fix

**Comment by DeepDiver1975** [comment]
Just to summarize the reasoning why this is long time broken and no further time will be invested:
Our sync algorithm will break apart as soon as file are going to be locked - as a result locking is basically not allowed. Therefore we don't support locking.

**Comment by jancborchardt** [comment]
Closing cause it’s won’t fix.

**Comment by derkostka** [comment]
Just a side Note: OSX is picky about WebDav LOCK. It expects locking to be working and otherwise only mounts the share as read-only (finder implementation).
Do you have a work around for that ?
