### ISSUE TITLE
Can not sent Calendar events by email

### ISSUE THREAD

**Issue by christianlx** [owncloud/core#13826]
Hi Owncloud devs,
I've a stranged behaviour whith sharing calendar events and mail notification.
When i share an event to another user and "send email", notification is sent to me, but not to my contact.
I found an old post where someone had the problem on 6.x version. I'm using a 7.0.4.

Is it a bug or configuration mistake ?

**Comment by DeepDiver1975** [comment]
> sharing calendar events

Please reopen this issue in https://github.com/owncloud/calendar - THX
