### ISSUE TITLE
Missing Secure Attribute SSL Cookie Information Disclosure Vulnerability

### ISSUE THREAD

**Issue by grisutheguru** [owncloud/core#13821]
Ahoi!

I did a security scan on my owncloud server and found the following:
High (CVSS: 6.4)
NVT: Missing Secure Attribute SSL Cookie Information Disclosure Vulnerability
The cookies:
Set-Cookie: ocd26375a548=96p2mc1ijg7afv979nf3ukg9f5; path=/; HttpOnly
are missing the secure attribute.

OID of test routine: 1.3.6.1.4.1.25623.1.0.902661

References
Other:
  URL:http://www.ietf.org/rfc/rfc2965.txt
  URL:https://www.owasp.org/index.phpTesting_for_cookies_attributes_(OWASP-SM-002)

Is there a parameter to set to fix this or does that have to be fixed by the developers?

**Comment by LukasReschke** [comment]
Please post your config as described in the issue reporting guidelines. If PHP is configured properly and enforce SSL is set this should just work fine.

**Comment by grisutheguru** [comment]
Sorry for the incomplete post.
I cannot find the reporting guidelines. Any link?
What I know about my config:
Debian 7, actual patch level.
Apache2, only one site on SSL.
owncloud installed via apt-get install, followed the wizard for config.

That's it.

How to retrieve a complete config?

Thanks for the help

**Comment by LukasReschke** [comment]
See https://github.com/owncloud/core/blob/master/CONTRIBUTING.md and https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by grisutheguru** [comment]
OK, thnx, here we go:

### Server configuration
**Operating system**: 
Debian 7

**Web server:**
Apache2.2.22 (Debian)

**Database:**
 sqlite_2.8.17-7

**PHP version:**
PHP 5.4.36-0+deb7u3 (cli) (built: Jan  9 2015 08:07:06)
**ownCloud version:** (see ownCloud admin page)
7.0.4 (stable)
**Updated from an older ownCloud or fresh install:**
fresh
**List of activated apps:**
Dateien, Aktivität, Dokumente, Bilder Kalender, Kontakte
**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'xxxxxxxxxx',
  'passwordsalt' => 'xxxxxxxxxxxxxxxxxxxxxx',
  'secret' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'trusted_domains' => 
  array (
    0 => 'my.guru.at',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://my.guru.at/owncloud',
  'dbtype' => 'sqlite3',
  'version' => '7.0.4.2',
  'installed' => true,
  'mail_from_address' => 'grisu',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'guru.at',
  'forcessl' => true,
);

```
Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
yes
### Client configuration
**Browser:**
Safari 8.0.3
**Operating system:**
Mac OSX 10.10.2


Hope that helps

**Comment by LukasReschke** [comment]
Please take a look at your cookies once you have logged-in. The according secure flag should then be set.

**Comment by LukasReschke** [comment]
Alternatively try https://github.com/owncloud/core/pull/13827, please note however that this is actually not a security bug as the cookie does at this time contain no sensitive information.

**Comment by grisutheguru** [comment]
ahhhh, OK, my fault, should analyze the details of a finding before posting.

Learned something today.
;-)

Will do the scan again with credentials, then coming back with the result.

Thank you.
Thumbs up for the quick solution-

**Comment by LukasReschke** [comment]
That said, please report all potential security bugs to security@owncloud.com instead of posting to our public bug tracker. Thanks.

**Comment by LukasReschke** [comment]
Will be fixed in 8.2 due to https://github.com/owncloud/core/pull/13827#issuecomment-134898745

**Comment by ltning** [comment]
This is also an issue in 10.0.1. 'overwriteprotocol' => 'https' is set in config.php. Nginx is the front-end, using php-fpm. Server only listening on TLS port 443.

**Comment by mschiessl** [comment]
still in there ! just let a scan run over my installation. 

`Vulnerability Detection Result
The cookies:

Set-Cookie: ocjgxz8kyelk=***replaced***; path=/; HttpOnly 

are missing the "secure" attribute.`
