### ISSUE TITLE
LDAP connections

### ISSUE THREAD

**Issue by ak-uk** [owncloud/core#13833]
I have 2 owncloud servers. One on CentOS 7 and one on CentOS 6. I found that there are non owncloud related problems with CentOS 7 and our SAN, so I built a CentOS 6 server. 
server setup:
php 5.6
php-fpm
nginx with ssl
maria db
On the CentOS 7 server I got the LDAP app working but this fails on CentOS 6. As per attached screenshots. 
C6:
![centos6](https://cloud.githubusercontent.com/assets/8711214/6003458/e0ecffbc-aaf3-11e4-99c8-82e3e5c64986.png)

C7:
![centos7](https://cloud.githubusercontent.com/assets/8711214/6003462/e4a9c3ba-aaf3-11e4-8ed0-ad00a4e870ae.png)

I've checked the configs and both are identical. 

The only errors that I'm seeing in owncloud.log are:

{"app":"PHP","message":"ldap_search(): Partial search results returned: Sizelimit exceeded at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#252","level":3,"time":"2015-02-02T14:14:58+00:00"}
{"app":"PHP","message":"ldap_search(): Partial search results returned: Sizelimit exceeded at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#252","level":3,"time":"2015-02-02T14:14:59+00:00"}
{"app":"PHP","message":"Array to string conversion at \/var\/www\/html\/owncloud\/lib\/private\/l10n\/string.php#57","level":3,"time":"2015-02-02T15:31:16+00:00"}

edit:

owncloud version 7.0.4

**Comment by MorrisJobke** [comment]
cc @blizzz 

@ak-uk Can you specify the PHP version on CentOS 6 and on CentOS 7?

**Comment by ak-uk** [comment]
Both using 5.6 from the remi repo
thanks

**Comment by blizzz** [comment]
So, what exactly does happen? On the CentOS 6 machine the wizard keeps spinning? Any network-related differences between both machines?

**Comment by ak-uk** [comment]
Yes, keeps spinning, often the domain controller will eventually lock out everything else trying to perform authentication until samba, slapd and sssd are restarted. 
Only networking differences are that centos 6 machine is dhcp.

**Comment by ak-uk** [comment]
@blizzz 
Thanks. Looking at the output of ./occ ldap:show-config on both pointed me in the right direction. 
Once I ran update oc_appconfig set configvalue = 0 where configkey = 'ldap_tls'; in the CentOS 6 DB, things started working immediately.

**Comment by blizzz** [comment]
Perfect, welcome!
