### ISSUE TITLE
ownCloud does not have a hook to alter the login process

### ISSUE THREAD

**Issue by ShamimIslam** [owncloud/core#13844]
Although ownCloud does have hooks that fire before a login executes, this hook does not fire uniformly on all logins. Pre-login in the lib/private/user.php does not always execute - specifically when MySQL is running.

**Comment by PVince81** [comment]
@MorrisJobke that's not technical debt but enhancement.

Technical debt is for duplicate code or stuff that needs refactoring. Or quickfixes that were put in because there was no time for a proper fix.

**Comment by PVince81** [comment]
Okay, I re-read the ticket. A hook that doesn't fire uniformly sounds more like a bug.

**Comment by MorrisJobke** [comment]
@PVince81 Oh ... sorry. I misread this. :(

**Comment by ShamimIslam** [comment]
So what is the pre-login hook for if it cannot intercept the login process
and alter it? I'm not sure I follow then. Isn't it supposed to be a
pre-emptive event handler that can cancel the event?

**Comment by PVince81** [comment]
@icewind1991 @schiesbn any idea ?

**Comment by icewind1991** [comment]
From what I can tell from the code and some quick debuging the pre login hook should always fire

**Comment by ShamimIslam** [comment]
Ok. So how do I cause the login to fail in the hook? Or can I not do so?

On February 4, 2015 8:34:25 AM EST, Robin Appelman <notifications@github.com> wrote:
>From what I can tell from the code and some quick debuging the pre
>login hook should always fire
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/owncloud/core/issues/13844#issuecomment-72854597

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
