### ISSUE TITLE
Migrate to official Dropbox PHP Core SDK

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#13841]
We need to migrate from the current unofficial and unmaintained Dropbox SDK we use at the moment to the official one: https://www.dropbox.com/developers/core/sdks/php

Test plan:
- [ ] use big files and slow networks - refs https://github.com/owncloud/core/issues/7821

**Comment by PVince81** [comment]
Makes sense. I hope it can also help to make update detection more easily and magically improve performance :wink:

**Comment by DeepDiver1975** [comment]
I'd really be happy to take the opportunity to also extract dropbox to it's own app.
In an ideal world moving it to a new repo and distribute the app via the appstore.

**Comment by LukasReschke** [comment]
@icewind1991  Maybe something for combination with the FlySystem thing we introduce at some Point of Time? (https://github.com/owncloud/core/pull/14551)

**Comment by DeepDiver1975** [comment]
I dont see this happening .....

**Comment by PVince81** [comment]
The flysystem base work has made it into code.

With a bit of luck, writing an adapter for Flysystem's Dropbox might be minimal.
See how it's done for FTP: https://github.com/icewind1991/files_external_ftp

**Comment by PVince81** [comment]
and make sure the library doesn't store the whole file in memory...

Moving to 9.1

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/issues/25969
