### ISSUE TITLE
ownCloud pre_login hook is not uniform

### ISSUE THREAD

**Issue by ShamimIslam** [owncloud/core#13845]
Some instances of the hook are labeled "preLogin". Unsure which is the correct one.

**Comment by PVince81** [comment]
CC @Xenopathic did you observe this too ?

**Comment by Xenopathic** [comment]
The hook fired by `OC_Hook` (or `\OCP\Util::connectHook()`) is `pre_login`. This gets fired when the `preLogin` event is emitted by the UserManager object, but to listen for that you can't use `OC_Hook`, but rather `->listen()` on the UserManager object itself.

So you have an option: Hooks Mk2 by listening directly on the UserManager with `preLogin`, or Hooks Legacy with `OCP\Util::connectHook()` with `pre_login`.
