### ISSUE TITLE
ownCloud does not have a pre-check-password hook

### ISSUE THREAD

**Issue by ShamimIslam** [owncloud/core#13846]
This hook should allow the interception of the password entered and allow force failing of this password based on user id.

**Comment by PVince81** [comment]
I think there is a prelogin hook already but it might not be possible to force-fail.

**Comment by ShamimIslam** [comment]
The catch is "pre-event" hooks by design are supposed to indicate whether
the process should continue or stop. This is a standard mechanism for
intercepting the call and determining if conditions are correct for
proceeding. This exists in ALL systems EXCEPT ownCloud. ownCloud is the
ONLY system I know which does not allow the pre-login hook to PREVENT
continuation. As such, ownCloud is designed to notify other systems of what
is going on in this instance instead of properly allowing them to
intervene. This dates back to the 1980s and the first even-based models of
programming and stems directly from the predicate calculus. A program
should leave the current system in a valid state - this means checking
pre-conditions, executing and then evaluating post-conditions. The
pre-confition failues prevent execution, the post-condition checks rollback
failed attempts.

The question is not whether pre-login exists. The question is why does
pre-login operate on a notify-basis and not a validate-pre-condition-basis?
And why are we not requesting that the pre-login and all pre-condition
events provide the actual failure mode validation as is the norm.

Thanks.

**Comment by PVince81** [comment]
Good points. It seems these were design decisions from the beginnings of OC...

What I would suggest here is to simply introduce new hooks that fulfil the requirement you described, using the Symfony event dispatcher (which is what we want to use in the future for hooks instead of the old static classes)

**Comment by PVince81** [comment]
Example of symfony-style event dispatcher for the "first login" hook: https://github.com/owncloud/core/pull/26206/files
A similar approach should be used for the new "pre-login" and "post-login" hook, but with interception of the result.

**Comment by ShamimIslam** [comment]
I think I understood what was indicated by the introduction of new hooks.
But I think we are overburdening the hooks and leaving ourselves for a
scenario where a hook will get missed. Is there a way to define an event
and then ALWAYS be able to provide a callback for the pre-condition
validation and then a callback for the post-condition callback, and have a
parameter be pushed into the both callbacks that can be used to request
closure/event details at the time the event took place? Once that's done,
the actual event mechanism can be a single call to react to an event which
will do the same processing each time:

Any return of false from precondition or postcondition prevents further
execution.

for($handleNext=$event->firstHandler();$handleNext;$handleNext=$handleNext
&& $event->nextHandler())
{
    // Precondition validation
    if($event->curHandler->hasPrecondition)
        $handleNext=$event->curHandler->preCondition($event->curEvent());
    // Execution
    if($handleNext)
        $event->curHandler->handleEvent($event->curEvent());
    // Postcondition validation
    if($handleNext && $event->curHandler->hasPostcondition)
        $handleNext=$event->curHandler->postCondition($event->curEvent())
}

Or something along those lines. Obviously I'm oversimplifying but I'm
saying that we should have standardized code executing the event handlers
in this mode.

**Comment by PVince81** [comment]
> a scenario where a hook will get missed

This shouldn't happen if implemented correctly inside the login code.

If not a hook then maybe it should rather be some kind of "authentication handler" class that can be registered somewhere. And then for each of those handlers it would call pre and post condition.
A bit like how the two factor provider plugin code is doing core. This reminds me that the two factor code also prevents login and displays a challenge page instead. Only after the challenge is resolved will it login fully.

**Comment by ShamimIslam** [comment]
I'm simply asking if it's worth/possible doing this for all events. I'm not asking for just logins. Event handling should operate a state machine that follows the predicate calculus. 

Otherwise we have different implementations of how events are handled.

On October 17, 2016 5:12:14 AM EDT, Vincent Petry <notifications@github.com> wrote:
>> a scenario where a hook will get missed
>
>This shouldn't happen if implemented correctly inside the login code.
>
>If not a hook then maybe it should rather be some kind of
>"authentication handler" class that can be registered somewhere. And
>then for each of those handlers it would call pre and post condition.
>A bit like how the two factor provider plugin code is doing core. This
>reminds me that the two factor code also prevents login and displays a
>challenge page instead. Only after the challenge is resolved will it
>login fully.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/owncloud/core/issues/13846#issuecomment-254154295

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
