### ISSUE TITLE
Update required, again, after reboot, but server is already updated to latest version.

### ISSUE THREAD

**Issue by buzzra** [owncloud/core#13856]
Hello all,

This has been posted in the Owncloud forums, but we can't seem to find out what is going on. I am also concerned how this will affect the upgrade to Owncloud 8.0 when it comes out.

I have been running Owncloud 7.0.4 for a while now. It works great. 2 nights ago the server was re-booted, and now anyone going to the https://myserver.com/owncloud url sees the "start update" button to update to Owncloud 7.0.4.

2 questions:
a) How do I stop the server from wanting to update to the version it is already running?
b) Why is the "start update" button available to ANYONE that goes to the server URL? 

Thanks for the help,

buzz

Environment: Linux Mint 13 Maya
Server: Apache2
Database: Mysql
Client: Web client
OC-Version: 7.0.4
PHP-Version: 5.4.37-1+deb.sury.org~precise+1 (from phpinfo.php page)

**Comment by DeepDiver1975** [comment]
> How do I stop the server from wanting to update to the version it is already running?

how did you install ownCloud? 



> Why is the "start update" button available to ANYONE that goes to the server URL?

Just because :speak_no_evil:

**Comment by RealRancor** [comment]
Hi,

just a wild guess: Your server was reseted to a state previous state where an older OC version was installed?

**Comment by PVince81** [comment]
@DeepDiver1975 we could add a config.php option to disallow updating in the web UI to avoid having anyone click on it

**Comment by RealRancor** [comment]
@buzzra 
Some more questions:

1. What happens if you click on "start update"? (Anything in your data/owncloud.log)
2. Have you recently installed/updated an app?

**Comment by buzzra** [comment]
@RealRancor,
I have not clicked the button yet. I was trying to figure out why this happened and so how to prevent it. I also didn't want to screw anything up, if possible. Currently, the owncloud.log has a bunch of "updste required, skipping cron" messages.

I have recently installed the news app and it was working fine. I also installed and removed an old version of the OPDS catalog app and then installed the latest version. Maybe that screwed something up? 

@DeepDiver1975 to amend my earlier comments, You asked about version.php and I told you about status.php. When I try version.php from the browser, I get nothing. when I look in the file it shows:
<?php
$OC_Version = array(7,0,4,2);
$OC_VersionString = '7.0.4';
$OC_Edition = '';
$OC_Channel = 'stable';
$OC_Build = '2014-12-08T18:35:45+00:00';

Thanks again for the help.

**Comment by buzzra** [comment]
@RealRancor ,
O.K. I clicked the button. the only message I got in the log (logging set to 0) was:

{"reqId":"xxxxxxxxxx","app":"core","message":"starting upgrade from 7.0.4.2 to 7.0.4.2","level":0,"time":"2015-02-03T16:39:42-06:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=xxxxxxxxxxxxxxxxxx"}

The web site went in to maintenance mode, and when I refreshed after a few minutes, I got the logon. Everything seems to be working just fine.   The version is still 7.0.4.2. 

Let me know if anyone wants to test anything else or look at anything else. 

Thanks for the help,

buzz

**Comment by RealRancor** [comment]
Hi,

have you also updated the app? Because you're getting the same message if you have just updated an app: https://github.com/owncloud/core/issues/10909

**Comment by DeepDiver1975** [comment]
> Everything seems to be working just fine. The version is still 7.0.4.2.



> have you also updated the app?

Indeed upgrades can be triggered by some apps as well.

I guess we can close this - server is successfully migrated.

**Comment by buzzra** [comment]
The news app shows an update available, but it only works with OC8, so I can't do it until I upgrade. Maybe that's what caused it. Seems like it might be a problem, if so. 

Also, did we want to do anything about the "start update" button being available to ANY/ALL visitors to the OC URL?

buzz
