### ISSUE TITLE
Encryption and Share issue

### ISSUE THREAD

**Issue by tele81** [owncloud/core#13851]
Hello Community , I have the latest OC version running on my mini server.
I have about 350 users for a university group.

After I made ​​the last update , there is a problem with the encryption and the parts of the folder.

For encryption :

Invalid private key for encryption app comes with most users who are logged on a bit longer . You can not access the data in the shared folder groups because they are defective or encrypted .

Share to :

I have a self-registration thus incorporated the user can give yourself up , I must only add to the group. Always When I add a new user I have to cancel parts of the folder and re- order to get back parts of the new user access . And there's the problem now , he remains in these actions depend but shows after hours and a new login procedure at which the folder is shared.

These messages standing for example . in the LOG :

Error Encryption library private key for user " bavaria blue" is not valid ! Maybe the userPassword what changed from outside if so please change it back to gain access

OC \ Files \ Cache \ scanner !!! Path ' thumbnails / 94 ' is not readable !!!

Can you give me support?

greeting

Hallo Community, ich habe die aktuelle OC Version auf meinem Mini Server laufen.
Ich habe ca. 350 User für eine Uni Gruppe.

Nachdem ich das letzte Update gemacht habe, gibt es ein Problem mit der Verschlüsslung und den Teilen der Ordner.

Zur Verschlüsslung:

Ungültiger privater Schlüssel für die Verschlüsselung-App kommt bei den meisten Usern die schon etwas länger angemeldet sind. Sie können nicht auf die Daten zugreifen im geteilten Gruppen Ordner da diese defekt oder Verschlüsselt sind.

Zum Teilen:

Ich habe eine Selbstregistrierung eingebaut somit können sich die User selbst Registrieren ich muss Sie dann nur zur jeweiligen Gruppe hinzufügen. Immer Wenn ich einen neuen User hinzufüge muss ich das Teilen des Ordners aufheben und wieder neu Teilen damit die neuen User Zugriff bekommen. Und da ist jetzt das Problem er bleibt bei diesen Aktionen hängen aber zeigt nach Stunden und neuem Einloggen an das der Ordner geteilt ist.

Diese Meldungen Stehen zb. im LOG:

Error	Encryption library	Private key for user "bavariablue" is not valid! Maybe the user password was changed from outside if so please change it back to gain access

OC\Files\Cache\Scanner	!!! Path 'thumbnails/94' is not readable !!!

Könnt Ihr mir Support geben?

Gruß

**Comment by MorrisJobke** [comment]
cc @schiesbn

**Comment by RealRancor** [comment]
Hi,
@tele81 
i think you could help debugging this problem by providing more informations about your environment by filling out the issue template:

https://raw.github.com/owncloud/core/master/issue_template.md

as asked in the "guidelines for contributing" (Linked in the yellow box when creating a new issue).

**Comment by PVince81** [comment]
Closing due to lack of feedback.

@tele81 without knowing your ownCloud version it will difficult to help you.
You might need to make sure that your automatic registration process properly triggers user hooks and login hooks at login time to make sure the keys are generated.

Please try with 8.0.5 or the upcoming 8.1.1.
