### ISSUE TITLE
Recommended LDAP/AD settings when initially configureing (doc)

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#13858]
Wanted to document the need for a recommendation around initial setup of AD/LDAP.

In common ownCloud use, users sometimes change names. This means that a Jane Doe could become a Jane Wu. This means the email address would change, the user name and the display name in LDAP or AD.

This is why we highly recommend that admins leverage an attribute that will not change when binding and setting up the initial LDAP/AD, such as UUID. Username (for login) and display name can also be different attributes from UUID, but it is important that admins don't select a unique user identification attribute that will change, or ownCloud will think it is a new user and *poof* user date appears lost. In fact, it is not lost - just in a different folder on the server.

@bboule any comments welcome here!
@jnfrmarks more FYI than anything

@carlaschroder would love to augment the LDAP/AD docs with this little explanation (if it is not already there).

**Comment by karlitschek** [comment]
@blizzz FYI

**Comment by Xenopathic** [comment]
To complete this, could the user list page show the username of the user instead of the UUID in such cases? Seeing a list of

    0123456789-abcde-wxyz
    992msik1xkj-sk221-fvn3
    ...

Doesn't make for easy administration, which is why some AD admins choose to change the attribute to the username (which, as you say, may change)

**Comment by DeepDiver1975** [comment]
@MTRichards should be in docs for 8.0? We are kind of running out of time - right? Shall we schedule this for 8.0.1? As soon as the docs will be there changes are going to be pushed to the doc server - there is not need to wait for the final 8.0.1 release.

Shouldn't we track this in the documentation repo? (Just wondering :speak_no_evil: )

**Comment by cdamken** [comment]
@Xenopathic  you have to add an atribute in Advanced tab: User Display Name Field and put samaccountname or what your LDAP needs

**Comment by MTRichards** [comment]
@Blizz I thought this was how the latest plugin worked - UUID separate from display name and user name?

@DeepDiver1975 Tagged as documentation, but also not 100% sure if this is current behavior.

**Comment by Xenopathic** [comment]
@cdamken I know, I was referring to the fact that given that sAMAccountName can change, but UUIDs are really ugly, there is no way to have nice usernames in the user list with persistent user data :smile:

**Comment by blizzz** [comment]
@MTRichards: the user @Blizz is not related to us.

Otherwise, the description is mostly accurate. Only I want to  elaborate on:

> This is why we highly recommend that admins leverage an attribute that will not change when binding and setting up the initial LDAP/AD, such as UUID.

There is no standard attribute name that refers to the UUID of an LDAP entry. I.e. it is not called "UUID", but "entryuuid" on OpenLDAP, "guid" on AD, etc. . Currently we know 5 attribute names are they are detected automatically. This is the default behaviour, i.e. does not require extra configuration by the admin. Only if the admin wants to override this behaviour, he can choose something else. And then you are totally right.

**Comment by blizzz** [comment]
> I thought this was how the latest plugin worked - UUID separate from display name and user name?

Correct. And everything can be customized.

**Comment by blizzz** [comment]
@MTRichards can this be closed or … ?

**Comment by MTRichards** [comment]
I think so, since we have the work you are doing now which should address any remaining item here...
