### ISSUE TITLE
Throw exception in initMountPoints if user manager returned null

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13862]
If for some reason the user manager did not find the expected user here https://github.com/owncloud/core/blob/stable7/lib/private/files/filesystem.php#L332 the logic will still go in the else block and create a bogus "local::" home entry.

This code needs to be made more robust: add a check whether `$user` is non-null and non-empty and if `$userObject` is null, which means that the user manager did not find the user, just throw an exception. This will avoid unwanted side-effects.
See https://github.com/owncloud/core/issues/12801#issuecomment-72667623 where this was found

CC @icewind1991 @blizzz

**Comment by PVince81** [comment]
PR is here: https://github.com/owncloud/core/pull/14044

This is not technically a bugfix, only something to make the code more robust in case of unknown bugs triggering that code path.

@DeepDiver1975 moving to 8.1

**Comment by PVince81** [comment]
(the part that was known to trigger that code path was fixed already in stable7 + stable8: https://github.com/owncloud/core/issues/12801)

**Comment by MorrisJobke** [comment]
Fix is in #15332

**Comment by PVince81** [comment]
Closing as the PRs have been merged.
