### ISSUE TITLE
Infinite creation of folders in web interface

### ISSUE THREAD

**Issue by Krypton25** [owncloud/core#13860]
Ok so I've installed Owncloud 7.0.4 on my windows desktop server using WAMP to bypass my incompetence with IIS and MySQL :). I'm using an 
Apache 2.4.9 server with 
PHP 5.5.12 and 
MySQL 5.6.17

My data folder is not located in the WWW root, but on another drive. When I first got there, I went into the folder called "admin" which is my OC username. In there, I created a subdirectory called "Musique" (note the "que" at the end - it might be important later) and another subdirectory called "Photos"

When I went on the web interface using https://localhost/owncloud and entered my login info, my personal folder contained 4069 files and folders, including:

"Musique"
"Photos" (capital P)
"owncloud_usermanual.pdf" (or something like that)
and 4066 different folders called "photos"

Now where did these come from!? They do not sync on either of my OC clients, but I can't get rid of them. Whenever I try to delete it, OC web interface just "tries" but never finishes deleting.
My workaround to use my "Photos" folder was to rename it "Images" to avoid case-sensitivity conflicts.

I don't know if there's a way to reproduce this bug elsewhere than here on my OC with my files.. Has anyone ever seen that and is there a simple fix to remove these 4066 folders?

Thanks

**Comment by PVince81** [comment]
Very likely.

@nickvergessen which one was the main ticket for this issue ?

**Comment by Krypton25** [comment]
I searched on this website for similar issue, but being new here, I didn't manage to find the "exact same issue" anywhere. I'm just looking for a way to:

1 - delete the 4066 folders that I can't seem to get rid of (and they only appear in web interface)
2 - prevent it from happening again - my guess is to completely disable case-sensitivity if that's possible

Thanks for your help :)

**Comment by PVince81** [comment]
Yeah, I also didn't manage to find it. I remember some other guy having the same issue.
It was also due to problems with path handling in Windows and possibly related to unicode chars too.

**Comment by Krypton25** [comment]
#13625 
is that it?
does not seem to be solved though...

**Comment by PVince81** [comment]
Yes, that's the one. Closing as duplicate.

Sorry that it's not fixed yet, from what I heard it is quite tricky. Please follow up in that other ticket.
Thanks.
