### ISSUE TITLE
Rename file in s2s sharing with encryption enabled

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13864]
### Steps to reproduce
1. Setup a OC instance B with stable7 (361b70e4d7a80e1aea930a4a9439394c3e30af18)
2. Enable encryption
3. Create a folder "folder" and share it with link, allow upload
4. Setup a OC instance A with master (9e222ec841946d773514f790fcc567c634d27038)
5. On A: Open share link and mount it as remote share
6. Create a subdir "folder/testroot" and "folder/testroot/sub"
7. Connect to A with a WebDAV client
8. Upload a small text file in "folder/testroot/test.txt"
9. With WebDAV, move "folder/testroot/test.txt" into "folder/testroot/sub/renamed.txt"
10. Download that file "renamed.txt" in the web UI of A

### Expected result
File downloaded properly

### Actual result
File size is the same as original file, but the contents is an HTML error page truncated to the original file size:
```
<!DOCTYPE html>
<!--[if lt IE 7]><html class="ng-csp ie ie6 lte9 lte8 lte7" data-placeholder-focus="false"><![endif]-->
<!--[if IE 7]><html class="ng-csp ie ie7 lt
```

Not sure yet whether it is related to stable7 and/or server to server sharing and/or encryption.

I will continue to investigate.

(discovered while running the pyocclient test suite inside a remote share folder)

@schiesbn @DeepDiver1975 @karlitschek @icewind1991 @jnfrmarks

**Comment by PVince81** [comment]
Confirmed, reproduced again on a different machine with the same steps.

Also I saw this in the back-end instance (stable7):
```
{"reqId":"54d1ff43e6dd3","app":"remote","message":"Encryption key not found for \"\/root\/files\/folder\/testroot\/sub\/renamed.txt\" during attempted read via stream","level":4,"time":"2015-02-04T11:15:15+00:00","method":"GET","url":"\/owncloud2\/public.php\/webdav\/testroot\/sub\/renamed.txt"}
```

The share key hasn't been moved into "sub":
```
data/root/files_encryption/share-keys/folder/testroot/test.txt.root.shareKey
data/root/files_encryption/share-keys/folder/testroot/test.txt.pubShare_0143dfb5.shareKey
```

Possibly a stable7 bug. Will continue to investigate.

**Comment by PVince81** [comment]
I tried connecting to the stable7 directly with cadaver and moving a file from "testroot" to "testroot/sub" and the keys were moved properly.

That's strange, because when done over the s2s share the keys aren't moved, even though it is also supposed to be a WebDAV MOVE operation.

**Comment by PVince81** [comment]
Very strange, when the MOVE was done over s2s sharing instead of cadaver, stable7 cannot find the owner name. This line https://github.com/owncloud/core/blob/stable7/apps/files_encryption/hooks/hooks.php#L441 returns null for the owner when done over s2s and "root" when done with cadaver.

**Comment by PVince81** [comment]
I debugged into resolvePath() and it sounds strangely similar to https://github.com/owncloud/core/pull/13881
Trying with that patch applied on stable7 now.

**Comment by PVince81** [comment]
Okay, I think I'm getting closer.

The difference between cadaver and s2s is that cadaver is **authenticated** as a specific user but s2s is using `publicwebdav.php` which is not authenticated.

That seems to mess up finding share key owners because the owner is null at this point.

**Comment by PVince81** [comment]
The steps can be reduced to the following:
1. Setup an OC instance
2. Enable encryption
3. Create a folder "folder" and subfolder "folder/sub"
4. Share "folder" with public link and allow upload
5. Connect cadaver to "http://localhost/owncloud2/public.php/webdav/" and login using the token from the link share, leave password empty
6. Upload a file and call it "test.txt"
7. `mv test.txt sub/test.txt`
8. Check the share key files on the server: see that they are still in "folder", not in "sub"

**Comment by PVince81** [comment]
The problem also exists in 8.0.

@schiesbn can you advise how to fix it ?
The problem is that there is no current user when using publicwebdav and yet the encryption code tries to work with an owner here: https://github.com/owncloud/core/blob/stable7/apps/files_encryption/hooks/hooks.php#L441

**Comment by PVince81** [comment]
Discussed this with @schiesbn last week and this is a "cannot fix for 8.0.1" because the current architecture doesn't give access to the owner at this stage.

Since refactoring of encryption is planned for 8.1 (as part of encryption 2.0), this hopefully will be possible.

@schiesbn can you re-confirm that there is no possible quick fix here ?

**Comment by karlitschek** [comment]
@schiesbn Is is possible to have a quick fix here?

**Comment by jnfrmarks** [comment]
@SergioBertolinSG 

Can you please add this test case to the test plan?

**Comment by PVince81** [comment]
I retested this connected to an encrypted 8.1/master (3ebc8f0564395fbb519fc4275e0f6f883df708b7) and renaming/moving didn't cause any trouble any more.

However on stable7/8 the problem still exists due to the old architecture with its unfortunate limitations.

Closing as fixed, backport not possible.
