### ISSUE TITLE
Different edit behavior when a file is shared via the server UI or via cURL

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#13867]
### Steps to reproduce

1. Install owncloud 
2. create user1 and user2
3. as user1 in the server UI create a .txt file, edit it to put in some content, and share with user2 with only share permissions (no edit permission)
4. as user2 edit the file - the file opens in an editor window but the user can't make changes.

5. Install owncloud client 
6. Create a local .txt file, edit it to put in some content, and sync the file to the server

/usr/bin/owncloudcmd  --trust /jrm/smashbox/results/test_shareFile/sharer/ owncloud://<un>:<pw>@x.x.x.x/owncloud/remote.php/webdav/

7. run a curl command to share the file with user 2, again with only share permissions

curl -u <un>:<pw> --data "path=somefile.txt&shareType=0&shareWith=user2&permissions=16" http://<un>:<pw>@x.x.x.x/owncloud/ocs/v1.php/apps/files_sharing/api/v1/shares

8. Back at the ui as user2, access the file shared via curl.  In this case, the file is not edited but instead is downloaded.

What is the correct behavior?  Are both ok?

### Expected behaviour

Consistent behavior regardless of how the file is shared.

### Actual behaviour

Different behavior between a curl share and a share via the server ui

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration

ownCloud Enterprise Edition 8.0 beta 2 (daily) Build:2015-01-30T04:20:37+00:00 24fc1c751ac1521ef02540bbf6d4d8fefc393b39

### Client Configuration

owncloudcmd version 1.7.1

**Comment by LukasReschke** [comment]
This is related to https://github.com/owncloud/core/issues/11707 - scheduled for 8.1. Can you confirm that I did not misunderstood that issue?

We need to switch to a secure by default policy here. Edit should be an additional option, but not be the default.

**Comment by jnfrmarks** [comment]
For the file shared via the server UI:

user2 can't make any changes to the file; the file is just opened in the texteditor window instead of being downloaded.

For the file shared via the cURL command,

The file is only downloaded for user 2 instead of being opened in the texteditor window.

**Comment by PVince81** [comment]
@jnfrmarks can you make sure that you clicked on the text file inside the "All files" view, not any other view ? (because clicking a text file will not open the editor in the "Shared with you" entry)

**Comment by jnfrmarks** [comment]
@PVince81 

I was in the all files view.

**Comment by PVince81** [comment]
Can you double check ? Because normally the editor should ALWAYS open in that view, unless the text editor app is not enabled or the mime type is not detected properly.

Can you evaluate the "tr" in the DOM and see if "data-mime" contains "text/plain" or something else ?

**Comment by jnfrmarks** [comment]
From server UI, user 1 shares with user 2, permissions = share only

From server UI, user 2 logs in and clicks on the file, the text editor opens.  This is from the "All Files" view

From client, user 1 shares with user 2, permissions = share only

From server UI, user 2 logs in and clicks on the file, the file downloads.  This is from the "All Files" view

I'm not sure which DOM you're looking for. If I view source user2's file page, there is no data-mime element.

**Comment by PVince81** [comment]
Right click on the row of the file, then click "Inspect element". Then find the "tr" element matching that file. You should see a few "data-XXX" attributes. One of them is "data-mime".

If you still say it's missing then it means the server didn't return any mime type for some reason

**Comment by jnfrmarks** [comment]
From abc.txt (this file opens in the editor)

![p288](https://cloud.githubusercontent.com/assets/8480343/6047156/d4fea0ce-ac75-11e4-9ac0-3ea825ed1653.PNG)

From TEST_FILE_MODIFIED_USER_SHARE.txt (this file downloads)

![p287](https://cloud.githubusercontent.com/assets/8480343/6047158/d8421cb6-ac75-11e4-8ffe-4b9a87665f69.PNG)

**Comment by jnfrmarks** [comment]
Hmm, the permissions are different but abc.txt should only have share permissions:


![p289](https://cloud.githubusercontent.com/assets/8480343/6047204/2ccadd04-ac76-11e4-851e-9c5a04de94eb.PNG)

**Comment by jnfrmarks** [comment]
ok; I have confirmed that when the client sets the permissions to "19" instead of "18" that the behavior is the same (the file is opened in the texteditor window).

(There has to be some internal mucking around with the permissions value that shows up in the DOM vs what gets set via the sharing API)

Sooo, the question NOW is: what is the correct permission setting to use in the sharing api when setting the permission to SHARE?  

In the first case, I was using OCS_PERMISSION_SHARE = 16 

When I changed OCS_PERMISSION_SHARE to 17 I got the same UI behavior.

**Comment by PVince81** [comment]
Ok, I think if you forget to set OCS_PERMISSION_READ (which is 1) then the file will not be readable, so the text editor will not open it because it expects the permissions to have the "read" bit.

So basically when composing permissions you should always do `OCS_PERMISISON_READ | OCS_PERMISSION_SHARE`.

But I agree that it doesn't make sense to let the API set useless permissions...

**Comment by jnfrmarks** [comment]
Thanks!  I'll update my test.  It looks like OCS_PERMISSION_READ
