### ISSUE TITLE
[feature request] Short URLs for sharing (tiny urls)

### ISSUE THREAD

**Issue by giovanisp** [owncloud/core#13863]
Just an idea... instead of creating long links like www.example.com/public.php?service=files&t=6c7d88d64d44f2d7680cbcf3abf96473, why do not provide friendly (and tiny) URLs like
www.example.com/b76J09c  or let the user chose a custom like www.example.com/myCustomSharedDoc  ?

There are some FLOSS URL Shorteners around (http://yourls.org/, http://sourceforge.net/projects/polrshortener/ ... ). Not sure if licenses are compatible, for maybe some code can be reused?

**Comment by karlitschek** [comment]
this requires tools like mod_rewrite so we can´t directly ship this with owncloud. But I´m sure this can be configured in apache to have the proper redirects.

**Comment by RealRancor** [comment]
Hi,

also have a look at https://apps.owncloud.com/content/show.php/Shorty?content=150401

**Comment by DeepDiver1975** [comment]
With oc8 the url will already be shorter as in previous versions.

**Comment by giovanisp** [comment]
Thank you!

@DeepDiver1975 cool! Short urls are very useful, specially at work, some executives complain about sending long URLs to customers...

@karlitschek couldn't this part be implemented within an .htaccess using
```html
<IfModule mod_rewrite.c>
RewriteEngine on
...
...
</IfModule>
```
? I think Wordpress works this way when you configure permalinks.

@RealRancor thanks, I'll try that in the meantime.

**Comment by DeepDiver1975** [comment]
Generated links for shared files in OC8 look like this:

http://localhost/index.php/s/RWA7lrh90kdhWwM

**Comment by giovanisp** [comment]
Thanks, you might find these interesting if in the future you have plans to get rid of the "index.php" in the URL (could be an option like it is in wordpress):
* http://codex.wordpress.org/Using_Permalinks#Choosing_your_permalink_structure
* http://vip.wordpress.com/documentation/change-your-pretty-permalinks-or-add-custom-rewrite-rules/

**Comment by RealRancor** [comment]
Have a look at the issue search, there is an existing issue
