### ISSUE TITLE
Move a Shared Folder with WebDAV deletes the content

### ISSUE THREAD

**Issue by flixx** [owncloud/core#13871]
Hello,
I have v8.0RC1 installed.
When User A shares a Folder "Foo" for User B (with all permissions), User B will see "Foo" in WebDAVs root. If User B moves "Foo" with WebDAV into another private Folder, User A will not see the contents of "Foo" anymore (WebDAV and WebInterface). In the WebInterface, User A still sees the share-icon for "Foo". However User B will not show up in the share details.

I am not sure if this is a known bug, intended behavior or already fixed. I could not test the "file move" app, because the current version will not run on v8.0RC1.
 
For completeness: User B can rename the Folder "Foo" to "Bar" with WebDAV. User A will still see the Folder as "Foo" including the content.

Cheers.

**Comment by flixx** [comment]
I did some more testing with deleting "Foo". It works fine via the WebInterface but not with WebDAV.

I guess when moving folders with WebDAV, my OS (Ubuntu) will first copy the folder to the new location, then deleting first the content of the old folder and then the old folder itself. So it's not Ownclouds fault, just strange WebDAV behavior.

**Comment by DeepDiver1975** [comment]
Which webdav client are you using?
Generally speaking: there is a move operation within the webdav protocol.

**Comment by flixx** [comment]
I'm using the integrated tools of nautilus 3.10.1 on Ubuntu 14.04.
Found this one: https://bugs.launchpad.net/ubuntu/+source/gvfs/+bug/1297773

**Comment by DeepDiver1975** [comment]
@icewind1991 if time permits - please have a look - THX

**Comment by icewind1991** [comment]
@flixx can you try manually doing a dav move with cadaver

1. `cadaver http://example.com/owncloud/remote.php/webdav`
2. login as the share recipient
3. `mv Foo PrivateFolder/Foo`

**Comment by DeepDiver1975** [comment]
moved to 8.0.1 for further analysis

**Comment by PVince81** [comment]
@flixx you could also have a look at the web server's access log and see whether your WebDAV client is indeed doing a COPY instead of MOVE (the method name should show in the log)

**Comment by enoch85** [comment]
ping @flixx

**Comment by DeepDiver1975** [comment]
closed due to inactivity - THX

**Comment by PVince81** [comment]
Likely to be related to https://github.com/owncloud/core/issues/13391
