### ISSUE TITLE
Dropbox problem / internal error 1060, 500 internal error

### ISSUE THREAD

**Issue by gdumanoir** [owncloud/core#13874]
### Steps to reproduce
1. Add a Dropbox external storage
2. Do some tidying, moving file and directory inside the dropbox share using the linux owncloud sync client.

### Expected behaviour
No error, syncs correctly

### Actual behaviour
The client is unable to execute the changes it seems, and starts to get errors : internal error 1060, 500 internal error.
Each time it scans the dropbox directory, it ends up with this error and stops the scan.

### Server configuration
**Operating system**: Linux Debian

**Web server:** Apache

**Database:** mysql

**PHP version:** PHP Version 5.4.23-1~dotdeb.1

**ownCloud version:** ownCloud 7.0.4

**Updated from an older ownCloud or fresh install:** fresh install

**List of activated apps:** external storage

**The content of config/config.php:**
$CONFIG = array (
  'instanceid' = abc,
  'passwordsalt' => abc,
  'secret' => abc,
  'trusted_domains' => 
  array (
    0 => 'cloudgdm.ouvaton.org',
  ),
  'datadirectory' => '/var/www/vhosts/cloudgdm.ouvaton.org/httpdocs/data',
  'overwrite.cli.url' => 'http://cloudgdm.ouvaton.org',
  'dbtype' => 'mysql',
  'version' => '7.0.4.2',
  'dbname' => '00429_gdm',
  'dbhost' => abc,
  'dbtableprefix' => 'oc_',
  'dbuser' => '00429_gdm',
  'dbpassword' => abc,
  'installed' => true,
  'forcessl' => true,
  'loglevel' => '0',
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => abc,
  'mail_domain' => abc,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtpsecure' => 'tls',
  'mail_smtphost' => abc,
  'mail_smtpport' => '587',
  'mail_smtpname' => abc,
  'mail_smtppassword' => abc,

**Are you using external storage, if yes which one:** local/smb/sftp/...
yes, dropbox and google drive

**Are you using encryption:** no

### Client configuration
**Browser:** Firefox

**Operating system:** Windows 7, Linux Ubuntu

#### Web server error log
No access to logs

#### ownCloud log (data/owncloud.log)

Debug OC\Files\Cache\Scanner !!! No reuse of etag for '' !!! cache: Array ( [fileid] => 7 [storage] => dropbox::0ef0t2zo64sum0jzb0qr1zjybgd7tbz/ [path] => [parent] => -1 [name] => [mimetype] => httpd/unix-directory [mimepart] => httpd [size] => -1 [mtime] => 1422810150 [storage_mtime] => 1422810150 [encrypted] => [unencrypted_size] => 0 [etag] => 54ce5c26e03de [permissions] => 31 ) data: Array ( [mimetype] => httpd/unix-directory [mtime] => 1422810188 [size] => -1 [etag] => 54ce5c4cebea4 [storage_mtime] => 1422810188 [permissions] => 31 )

What seems weird to me is the fact no file name is filled : No reuse of etag for ''

##### Comments :
I have another dropbox share configured, and it is working well.

Also, when I check the dropbox share on the dropbox interface, the changes done with owncloud were correctly done.

I tried several things :

-    erase content of oc_filecache table : no improvement
-   configure a new dropbox application : no improvement
-   erase completely the content of the dropbox share (using the dropbox website) : then the sync worked correctly. I then started to add my files again using owncloud, the problem reappeared.... Each file uploaded though the sync client had a 500 error, even if the file arrived correctly on the dropbox share...

When I try to click on the dropbox share using owncloud web interface, after a few second I get the root of owncloud...

Thanks

**Comment by DeepDiver1975** [comment]
The Dropbox integration needs some love ... will happen in 8.1 if time permits. THX

**Comment by PVince81** [comment]
@gdumanoir are you still having issues with 8.0.5 ? There were a few small fixes related to Dropbox.

**Comment by cmonteroluque** [comment]
@gdumanoir can you confirm?

**Comment by gdumanoir** [comment]
Hi, sorry for my late answer, I had some difficulties to upgrade. I am now in 8.1.1.
I still have the same problem....
Thanks....

**Comment by PVince81** [comment]
Is there still nothing in the logs with 8.1.1 or 8.1.3 ?
Usually 500 internal server errors always have exceptions or errors in owncloud.log.

**Comment by PVince81** [comment]
There was an issue when moving files, see https://github.com/owncloud/core/issues/11628 and a possible fix https://github.com/owncloud/core/pull/19869

**Comment by cmonteroluque** [comment]
Moving to 9.0

**Comment by PVince81** [comment]
Should be fixed with 9.0 through https://github.com/owncloud/core/pull/19869

@gdumanoir feel free to reopen if you still have this issue in 9.0beta1
