### ISSUE TITLE
External storages not visible in personal settings

### ISSUE THREAD

**Issue by pierrejochem** [owncloud/core#13873]
_I installed the OC 8.0 RC1 and got the problem that the external storages configuration is not display under my personal settings._

**Enable User External Storage is switched on and all providers are selected**

I can only see: **ArrayArrayArrayArrayArray** at the place where it should be normally

**Comment by MorrisJobke** [comment]
@pierrejochem Was this a fresh install or an upgrade? Is there anything in the owncloud.log or the webservers log?

Can you fill out the architecture details in https://github.com/owncloud/core/blob/master/issue_template.md

Thanks

**Comment by pierrejochem** [comment]
It is a fresh installation with the sources from here:

http://download.owncloud.org/community/testing/owncloud-8.0.0RC1.tar.bz2

And the here is the part from the owncloud.log (Apache error log has nothing related to the problem)

{"reqId":"9d09811e1e373a2a8e56103de909b595","remoteAddr":"127.0.0.1","app":"PHP","message":"Array to string conversion at \/var\/www\/owncloud\/lib\/private\/template\/functions.php#23","level":3,"time":"2015-02-04T09:10:17+00:00"}
{"reqId":"9d09811e1e373a2a8e56103de909b595","remoteAddr":"127.0.0.1","app":"PHP","message":"Array to string conversion at \/var\/www\/owncloud\/lib\/private\/template\/functions.php#23","level":3,"time":"2015-02-04T09:10:17+00:00"}
{"reqId":"9d09811e1e373a2a8e56103de909b595","remoteAddr":"127.0.0.1","app":"PHP","message":"Array to string conversion at \/var\/www\/owncloud\/lib\/private\/template\/functions.php#23","level":3,"time":"2015-02-04T09:10:17+00:00"}
{"reqId":"9d09811e1e373a2a8e56103de909b595","remoteAddr":"127.0.0.1","app":"PHP","message":"Array to string conversion at \/var\/www\/owncloud\/lib\/private\/template\/functions.php#23","level":3,"time":"2015-02-04T09:10:17+00:00"}
{"reqId":"9d09811e1e373a2a8e56103de909b595","remoteAddr":"127.0.0.1","app":"PHP","message":"Array to string conversion at \/var\/www\/owncloud\/lib\/private\/template\/functions.php#23","level":3,"time":"2015-02-04T09:10:17+00:00"}

**Comment by DeepDiver1975** [comment]
@pierrejochem can I ask you for a screenshot? Which language are you using?

**Comment by icewind1991** [comment]
Also can you post the mount.json (`owncloud/data/$user/mount.json`) for the user (ofc. editing out private info where needed)

**Comment by pierrejochem** [comment]
### Steps to reproduce
1. Enable files_external
2. Activate the setting in admin settings and enable all storages
3. Go to personal and you won't see the storage configuration part

### Expected behaviour
Show storages like in the admin settings page

### Actual behaviour
ArrayArrayArrayArrayArray

### Server configuration
**Operating system**: Ubuntu 14.04 LTS

**Web server:** Apache/2.4.7

**Database:** Mysql 5.5.41

**PHP version:** PHP 5.5.9

**ownCloud version:** ownCloud 8.0 RC 1 (testing)

**Updated from an older ownCloud or fresh install:** no

**List of activated apps:** 

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => 'xxxxxx',
  'passwordsalt' => 'xxxxxx',
  'secret' => 'xxxxx',
  'trusted_domains' => 
  array (
    0 => 'localhost',
  ),
  'proxy' => 'x.x.x.x:3128',
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'https://localhost/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.0.5',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin',
  'dbpassword' => 'xxxxx',
  'installed' => true,
  'theme' => 'sysmex',
);

**Are you using external storage, if yes which one:** not available

**Are you using encryption:** no

### Client configuration
**Browser:** Firefox 35.0.1

**Operating system:** Ubuntu 14.04

**Comment by pierrejochem** [comment]
@DeepDiver1975  English

**Comment by pierrejochem** [comment]
@icewind1991 I can not add a mount so the file is empty and not created

**Comment by pierrejochem** [comment]
![screenshot from 2015-02-04 14 47 01](https://cloud.githubusercontent.com/assets/9192953/6041574/efd224f4-ac7d-11e4-908f-03f5a2ec3357.png)

**Comment by pierrejochem** [comment]
Guy's I found the problem. I created an own theme and this produced this behaviour. After setting it to the default I can see it correctly. Sorry :-(

**Comment by MorrisJobke** [comment]
@pierrejochem No problem :) Thanks anyway :)
