### ISSUE TITLE
Can not add files to root of the mount in a 2 level share situation

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#13878]
### Steps to reproduce
1. Server1:
    1. Create folder `root/` and share public with permissions
    2. Add a folder `root/server1/` and two files `root/server1-1.txt` and `root/server1/server1-2.txt`
    3. Visit public link and "Add to owncloud" on Server2

2. Server2
    1. Accept share from Server1, share mount public with permissions
    2. Add a folder `root/server2/` and two files `root/server2-1.txt` and `root/server1/server2-2.txt`
    3. Visit public link from Server2 and "Add to owncloud" on Server3

3. Server3
    1. Accept share from Server2
    2. Add a folder and multiple files:
        + `root/server1/server3-2.txt` :white_check_mark: (fixed on stable7 with #13796, master #13490)
        + `root/server2/server3-3.txt` :white_check_mark:  (fixed on stable7 with #13796, master #13490)
        + `root/server3-1.txt` :x:
        + `root/server3/` :x:

### Affected versions
* master/stable8
* stable7

### Possible solution
from @schiesbn https://github.com/owncloud/core/pull/13796#issuecomment-72705705
> I think I found the problem. I did all de debugging on master, because it fails their too. 
>
> We share a folder from server1 to server2 to server3. Now server3 wants to write a file to the folder. Since the folder is the root of the mount point on server2 the isCreatable()-check will lead us to this place https://github.com/owncloud/core/blob/master/lib/private/files/view.php#L90
At this point 'path' will be something like "/user/files/mountpoint" and "fakeRoot" will be "/user/files/mountpoint/" so strpos() will be false and we will return null which again will return false for the isCreatable()-check.
>
>My simple solution, I edited https://github.com/owncloud/core/blob/master/lib/private/files/view.php#L90 and adding following if-statement:
>
```
if (rtrim($path,'/') === rtrim($this->fakeRoot, '/')) {
    return '/';
}
```
>
> It works, all tests still pass. But I don't really feel comfortable... @icewind1991 what do you think?
>
> BTW: This is only 90% of the solution because for some reasons I'm able to create the first file successfully on server3 but if I try to create a second one I get a "storage error" and after that the mount point is gone. But still I think that the problem I outlined above is one of the important issues on the way to a solution.

### Verified the "possible solution"
- [x] master by @schiesbn 
- [x] stable7 by @nickvergessen

**Comment by nickvergessen** [comment]
Reopening for stable7 backport

**Comment by MorrisJobke** [comment]
@nickvergessen Why reopening? We have the backport-request label. I have a look at it regularly and ping if the answer is pending ;)

**Comment by MorrisJobke** [comment]
Backport granted https://github.com/owncloud/core/pull/13888#issuecomment-72862298
