### ISSUE TITLE
Inconsistent behaviour in \OC\Files\View regarding paths.

### ISSUE THREAD

**Issue by schiessle** [owncloud/core#13887]
The problem was discovered here https://github.com/owncloud/core/pull/13796#issuecomment-72705705 and handled by a easy fix for a particular problem here https://github.com/owncloud/core/pull/13881. But the overall problem still exists:

The fakeRoot in OC\Files\View has a trailing slash for external mount points or share mount points. Otherwise it doesn't have a trailing slash. Also depending on how the View is initialized fakeRoot can have a trailing slash or not. This leads to problems like described and fixed in the issues linked above. Additional it will fail if the path comes with two leading slashes like mentioned here https://github.com/owncloud/core/pull/13881#issuecomment-72843267. Another inconsistency is that depending on the trailing slash of the fakeRoot the result of getRelativePath() will start with a leading slash or not.

This all is highly inconsistent and it is really hard to say which behaviour is the correct one.
We should always operate on normalized paths starting with one slash, without any double-slashes and without a trailing slash. Also the result should always be a normalized path.

cc @icewind1991

**Comment by PVince81** [comment]
I think in general we'd like to move away from the "View" class and use the Node API instead.
But I'm not sure whether that one is usable "from the inside" of core.

**Comment by DeepDiver1975** [comment]
@icewind1991 please comment - THX

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/issues/16478
