### ISSUE TITLE
Strange permission for folder/file created in a shared folder

### ISSUE THREAD

**Issue by Watchwolf** [owncloud/core#13886]
Hello,

Maybe this is not a bug .. I do not know.

**Steps to reproduce**

Actions are made with the WEB interface

* User A share a folder to User B with all permission except Share and delete
* User B create a file or folder in the shared folder
* User A can't share or delete the file/folder created by user B

**Expected behaviour**

The file/folder created by user B is in the account of user A, user A should have all rights on it. In the database permissions is 7.

If the shared permission are all (with Share and Delete ) user A can share and delete the file/folder created by user B. In the database permissions is 31.

**Configuration**

Server ownCloud 7.0.4
Are you using external storage, if yes which one: no
Are you using encryption:no

**Comment by MorrisJobke** [comment]
I just tested - works on master.

I will test stable7.

**Comment by MorrisJobke** [comment]
I have no problems with stable7.

@schiesbn @PVince81 Were there any changes to sharing in the past?

**Comment by Watchwolf** [comment]
Maybe this is because I use an old install (olds user, many upgrades ...) 

I will make some tests with clean install.

**Comment by MorrisJobke** [comment]
@Watchwolf Can you provide the server configuration section from https://github.com/owncloud/core/blob/master/issue_template.md ?

**Comment by Watchwolf** [comment]
Server configuration

**Operating system:** Debian

**Web server:** Apache

**Database**: MySQL

**PHP version**: PHP 5.4.36-0+deb7u1

**ownCloud version**: 7.0.4

**Updated from an older ownCloud or fresh install**: updated, I do not know the original version, the install has more than 1 year

**List of activated apps**: only "Acitivité" (Activity in english ?)

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => '5130bb9e2795c',
  'passwordsalt' => '',
  'datadirectory' => '/srv/media_owncloud/actecil',
  'dbtype' => 'mysql',
  'version' => '7.0.4.2',
  'dbname' => 'actecil_owncloud',
  'dbhost' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'localhost',
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' => 
  array (
    0 => 'files.actecil.fr',
  ),
  'share_folder' => '/Shared',
  'mail_smtpname' => '',
  'mail_smtppassword' => '',
  'forcessl' => false,
  'secret' => '',
  'ldapIgnoreNamingRules' => false,
);


**Are you using external storage:** no

**Are you using encryption:** no

**Comment by Watchwolf** [comment]
I have the problem with 2 new users and new folders.

I will test with a fresh install when I will have time. 

Maybe you can tell me some ideas where to look in the source code to see if I can find something.

**Comment by PVince81** [comment]
Can you try with this patch ? https://github.com/owncloud/core/pull/13347

It fixes an issue with permissions in shared folders.

**Comment by Watchwolf** [comment]
The patch #13347 fix the problem.

Thank you !
