### ISSUE TITLE
Files External: Available For not showing after refresh

### ISSUE THREAD

**Issue by tg-ciphron** [owncloud/core#13883]
Hello,
by adding a new storage under file external, i am able also to add an LDAP-User. This User is defined under "available for". After refreshing the Admin-page, following incident occurs : the field "available for" is blank/empty. Therefore the folder is shared und reacheable for the user. This issue needs to be fixed, due to the fact that our client requested for that. we are currently using owncloud 7. i would be really greatful, if you provide a solution to this issue. thanks in advance!

**Comment by DeepDiver1975** [comment]
scheduling for 8.1 for analysis

**Comment by DeepDiver1975** [comment]
@tg-ciphron I assume you have asset-pipeline enabled in your conifg - right? 
There is an issue with respect to js concatenation is OC7 - #14631

**Comment by PVince81** [comment]
Related to https://github.com/owncloud/core/issues/13781 and https://github.com/owncloud/core/issues/16582 ?

**Comment by blizzz** [comment]
Users should work with recent stable7. @tg-ciphron can you confirm?
