### ISSUE TITLE
Permissions will be overwritten by parent directory

### ISSUE THREAD

**Issue by raiffeisennet** [owncloud/core#13891]
# Expected behaviour
When entering in a subdirectory with write permissions and the parent has no write permissions i should be able to create a file
# Actual behaviour
When i enter in a a subdirectory with write permissions and the parent has no write permissions i can't create files in the subdirectory. When i enter directly to the subdirectory i have the write permissions.
# Server Configuration
php -v PHP 5.4.36-0+deb7u3 (cli) (built: Jan  9 2015 08:07:06) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
mysql 5.1
OC Server 7.0.4
# Steps to reproduce:
1) Create group A
2) Create group B
3) Create folder "test"
4) Create folder "subtest"
5) Give group B write permissions to "subtest"
6) Give group A write permissions to "test"
7) Give groub B read permissions to "test"
8) Assign with group admin user the group B to "testuser"
9) With "testuser" go to file app and enter via "test" folder into "subtest" folder
10) there will be no write permissions
11) With "testuser" go to file app and enter directly ito folder "subtest"
12) now you have write permission

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by DeepDiver1975** [comment]
scheduling for 8.1 for analysis

**Comment by PVince81** [comment]
@raiffeisennet when you say "give group permissions" are you referring to ownCloud shares or filesystem permissions ? Are these system groups or ownCloud groups ?

CC @schiesbn

**Comment by raiffeisennet** [comment]
I'am refering to ownCloud shares and ownCloud groups.

**Comment by PVince81** [comment]
Ah yes, this is the known "receive the folder twice, once as subdir and once as direct share, with different permissions" issue. I'll close this ticket in favor of https://github.com/owncloud/core/issues/14428 where the design discussion is.
