### ISSUE TITLE
owncloud-3rdparty dependency isn't satisfied

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#13901]
### Steps to reproduce
Install owncloud package in Ubuntu

sudo sh -c "echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/xUbuntu_14.10/ /' >> /etc/apt/sources.list.d/owncloud.list"
sudo apt-get update
sudo apt-get install owncloud

### Expected behaviour
owncloud-3rdparty is installed as a dependency while installing owncloud.

### Actual behaviour
owncloud-3rdparty isn't installed so owncloud can't run and you have to install it manually.

**Comment by LukasReschke** [comment]
@jnweiger

**Comment by DeepDiver1975** [comment]
Should be fixed by now

```irc
[17:59:37] <Juergen> sergio: please retry with RC1-3 when the rebuild is done.

**Comment by DeepDiver1975** [comment]
fixed on obs: https://build.opensuse.org/package/rdiff/isv:ownCloud:community:8.0/owncloud?linkrev=base&rev=63

**Comment by SergioBertolinSG** [comment]
Tested using RC1-3 version, fixed for me too.

**Comment by DeepDiver1975** [comment]
> Tested using RC1-3 version, fixed for me too.

thx
