### ISSUE TITLE
Provide JS Files API classes to access and manipulate files

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13905]
Currently apps and file viewers need to resort to their own URL generation schemes and have no direct way of doing file operations like "retrieving the file list" (ex: gallery), "downloading a file", etc.

Instead of having every app or file viewers invent their own way of accessing files, a JS Files API should be developed to provide file operations like:
- list files in a folder
- search files
- download file (when opening a file for vieweing)
- upload file (when saving a file after modifying it)
- creating folders
- deleting files
- ...

Ideally this API should be implemented base directly WebDAV (see #12353).

Once this API is available, the following will be possible:
- the files app web UI **itself** should be based off the JS Files API (#12353)
- other apps or sidebar views can provide their own instance of JS Files API (for example the trashbin can provide a file list of deleted files and let file viewers open such files for viewing)
- the JS Files API could be used outside of ownCloud by third party apps (with CORS)

@DeepDiver1975 @icewind1991 @schiesbn @MorrisJobke @Raydiation what do you think ?

**Comment by PVince81** [comment]
The JS Files API could also be written in a way similar to pyocclient: https://github.com/PVince81/pyocclient
But the question is whether it should also provide other APIs like sharing or such, I'd say no for now.

**Comment by DeepDiver1975** [comment]
> the JS Files API could be used outside of ownCloud by third party apps (with CORS)

so this files api for javascript is then more a kind of "ownCloud Files SDK for JavaScript" - right?

**Comment by PVince81** [comment]
I would say so, yes. A JS SDK designed to run in the browser (not Node JS).

It would be based on WebDAV and contain the workarounds required to upload files in IE 8 or browsers that might not support FormData/FileReader/etc.

The interesting part is that it abstracts away the file access logic and also can be implemented by the trashbin to provide a view to access trashbin files through the same methods.

I still need to think it through to make sure it:
1) covers the use cases we want when running it inside of ownCloud
2) not make it too specific so we could at some point extract it as a separate library (like pyocclient) for external apps

**Comment by rullzer** [comment]
I can only say this is very welcome!
Similar stuff should be done for sharing, but one step at a time :)

**Comment by oparoz** [comment]
+1. Every app is currently using their own controller to do this

**Comment by PVince81** [comment]
In OC 9.0 there is now `OC.Files.getClient()`.

However it doesn't support uploading yet, might be tricky though.

**Comment by oparoz** [comment]
I've tested it in Gallery for the move operation and it worked as expected, looking forward to `upload` :)

**Comment by PVince81** [comment]
Upload is very tricky because it requires a hidden "input type=file" field to exist. Also one needs to trigger the file selection dialog by setting the focus on the field to make the browser trigger the dialog.
Not sure how to fit something like this in a simple API like `client.upload()`.

Maybe you have some ideas ? :smile: 

Note that this PR https://github.com/owncloud/core/pull/21237 brings webdav PUT upload but would need further refactoring to allow cramming the logic into this API.

**Comment by PVince81** [comment]
Well, thinking of it, the API might still look simple:

```javascript
    client.triggerUploadDialog(targetFolder, options).then(function(data) {
        // do stuff after the upload, data contains the uploaded files metadata
    });
```

The call would have to generate the input field and direclty trigger it to make the dialog appear. Then it would perform the upload into the given `targetFolder` and eventually calls the callback.

**Comment by PVince81** [comment]
apps could actually use this library: https://github.com/noveens/js-owncloud-client
