### ISSUE TITLE
.htaccess file comes inside a folder

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#13902]
### Steps to reproduce
Install owncloud package in Ubuntu >14.XX:

sudo sh -c "echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/xUbuntu_14.10/ /' >> /etc/apt/sources.list.d/owncloud.list"
sudo apt-get update
sudo apt-get install owncloud

### Expected behaviour
owncloud/.htaccess is a file not a folder.

### Actual behaviour
owncloud/.htaccess is a folder with the .htaccess file inside, you have to manually move that file out to avoid problems.

**Comment by karlitschek** [comment]
@jnweiger Wow. What is the problem here?

**Comment by DeepDiver1975** [comment]
this looks wrong: https://build.opensuse.org/package/view_file/isv:ownCloud:community:8.0/owncloud/debian.owncloud-config-apache.install?expand=1

**Comment by DeepDiver1975** [comment]
instead of

````
.htaccess /var/www/owncloud/.htaccess
````

we better use

````
.htaccess /var/www/owncloud/
````

**Comment by jnweiger** [comment]
Fixed in commit 64. on isv:ownCloud:community:8.0

Aarg. Install files again. Sometimes I need to specify a filename, sometimes a directory. Simple logic, but sometimes I get it wrong.

**Comment by SergioBertolinSG** [comment]
Working fine in RC2-1.
