### ISSUE TITLE
Enhance sqlite warning in admin section and during setup

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#13906]
Admin page:
![bildschirmfoto von 2015-02-04 20 41 30](https://cloud.githubusercontent.com/assets/1005065/6048089/3d2b5a4c-acae-11e4-95cc-55af9456c760.png)

Setup page:
![bildschirmfoto von 2015-02-04 20 48 28](https://cloud.githubusercontent.com/assets/1005065/6048239/330549aa-acaf-11e4-8b64-bdf0e4e6157f.png)

@karlitschek please review the proposed text - THX

**Comment by karlitschek** [comment]
I don´t think we want to discharge sqlite for desktop clients at all. I would say something like. "more than 3 clients in parallel"

**Comment by RealRancor** [comment]
Until the sync client is not limiting its parallel connections only one sync client can also cause a "database locked" message as often reported in the bugtracker.
