### ISSUE TITLE
flock() expects parameter 1 to be resource

### ISSUE THREAD

**Issue by Free16t** [owncloud/core#13912]
Impossible to have the login page (and to make owncloud working)

# Steps to reproduce

Don't really know

# Expected behaviour 
No error and the login page

# Actual behaviour

I change from Apache to Nginx and I upgrade to the 8.0.0.5 (RC).
When I go to xxx/owncloud, I have a blank page and those errors in the nginx-errors.log : 

`[error] 74886#0: *6 FastCGI sent in stderr: "PHP message: PHP Warning:  flock() expects parameter 1 to be resource, boolean given in /home/www/owncloud/lib/private/config.php on line 178
PHP message: PHP Fatal error:  Call to a member function getValue() on a non-object in /home/wwwowncloud/lib/private/legacy/config.php on line 46" while reading response header from upstream, client: XXXXXXXXX, server: XXXXXXXXX, request: "GET /owncloud/status.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "XXXXXXX" `

Here is my configuration 
><?php
$CONFIG = array (
  'instanceid' => 'XXXXXX',
  'passwordsalt' => 'XXXXXX',
  'secret' => 'XXXXXX',
  'trusted_domains' =>
  array (
    0 => 'XXXXXXX',
  ),
  'datadirectory' => '/home/www/owncloud/data',
  'overwritewebroot' => '/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.0.5',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_XXXX',
  'dbpassword' => '',
  'installed' => true,
  'loglevel' => '3',
  'maintenance' => false,
  'theme' => '',
>);

And my Nginx config (the .conf is in the vhosts folder as Owncloud is at the point <ip>/owncloud. I have a fully operationnal wordpress at <ip>.

>upstream php-handler {
  server 127.0.0.1:9000;
  #server unix:/var/run/php5-fpm.sock;
  }

  >root /home/www/owncloud/;
  client_max_body_size 10G;
  fastcgi_buffers 64 4K;

  >rewrite ^/caldav(.*)$ /remote.php/caldav$1 redirect;
  rewrite ^/carddav(.*)$ /remote.php/carddav$1 redirect;
  rewrite ^/webdav(.*)$ /remote.php/webdav$1 redirect;

  >index index.php;
  error_page 403 /core/templates/403.php;
  error_page 404 /core/templates/404.php;

  >location = /robots.txt {
    allow all;
    log_not_found off;
    access_log off;
    }

  >location ~ ^/(?:\.htaccess|data|config|db_structure\.xml|README){
    deny all;
    }

  >location / {
   # The following 2 rules are only needed with webfinger
   rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
   rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json last;

   >rewrite ^/.well-known/carddav /remote.php/carddav/ redirect;
   rewrite ^/.well-known/caldav /remote.php/caldav/ redirect;
   rewrite ^(/core/doc/[^\/]+/)$ $1/index.html;

>   try_files $uri $uri/ /index.php;
   }

  > location ~ \.php(?:$|/) {
   fastcgi_split_path_info ^(.+\.php)(/.+)$;
   include fastcgi_params;
   fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
   fastcgi_param PATH_INFO $fastcgi_path_info;
   fastcgi_param HTTPS on;
   }

>   # Optional: set long EXPIRES header on static assets
   location ~* \.(?:jpg|jpeg|gif|bmp|ico|png|css|js|swf)$ {
       expires 30d;
       # Optional: Don't log access to assets
         access_log off;
>   }

>  }
>

## Server configuration
**Operating system**: FreeBSD 10.1
**Database**: Mysql
**PHP**: 5.5.19
**Owncloud version**: 8.0.0.5 RC (updated but not by the updater)
**Are you using external storage, if yes which one**: No
**Are you using encryption**: Before I was using but I faced issues with the encryption so I stop it

**Comment by PeterPablo** [comment]
I just tried to manually upgrade to OwnCloud 8 with the release tar from the official homepage according to the [upgrade manual](http://doc.owncloud.org/server/8.0/admin_manual/maintenance/upgrade.html) and am getting the same error.
```
[Mon Feb 09 14:14:41 2015] [error] [client IP] PHP Warning:  flock() expects parameter 1 to be resource, boolean given in /var/www/owncloud/lib/private/config.php on line 178
[Mon Feb 09 14:14:41 2015] [error] [client IP] PHP Fatal error:  Call to a member function getValue() on a non-object in /var/www/owncloud/lib/private/legacy/config.php on line 46
```

`ls -la` yields:
```
root@HOST:/var/www/owncloud_8_not_working/config# la
insgesamt 36K
-rw-r----- 1 www-data www-data 748 Feb  9 14:32 config.php
-rw-r--r-- 1 www-data www-data 28K Feb  7 03:31 config.sample.php
-rw-r--r-- 1 www-data www-data 225 Feb  7 03:31 .htaccess
```

The same config works fine with owncloud 7 (I just returned). It seems the config file can not be accessed. The partition ist mounted as `ext4` with the options `defaults,noatime` (in case that matters).

I am running Raspian `Linux rpi 3.18.6+ #753 PREEMPT Sun Feb 8 14:47:22 GMT 2015 armv6l GNU/Linux` with
```v
Server version: Apache/2.2.22 (Debian)
Server built:   Jan 10 2015 15:51:04
```
and `mysql  Ver 14.14 Distrib 5.5.41, for debian-linux-gnu (armv7l) using readline 6.2`.

If I delete the `config.php` then I get an installation prompt where I could enter new root credentials and database settings.

I tested in both Chromium and Firefox.

No encryption, data directory is on an external storage.

`config.php` (working in 7, but not in 8)
```
<?php
$CONFIG = array (
  'instanceid' => 'id',
  'passwordsalt' => 'salt',
  'datadirectory' => '/media/mountpoint/owncloud_data',
  'dbtype' => 'mysql',
  'version' => '7.0.4.2',
  'installed' => true,
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' =>
  array (
    0 => 'domain1',
    1 => 'domain2',
  ),
  'mail_smtpmode' => 'php',
  'mail_from_address' => 'user',
  'mail_domain' => 'tld.com',
  'secret' => 'secret',
  'dbname' => 'db',
  'dbhost' => 'localhost',
  'dbuser' => 'user',
  'dbpassword' => 'pw',
);

```

**Comment by DeepDiver1975** [comment]
> I change from Apache to Nginx and I upgrade to the 8.0.0.5 (RC).

Which user is configured to run nginx? Is it www-run as well?

Looks like the nginx user has no right to access the config file.

**Comment by PeterPablo** [comment]
@DeepDiver1975, in my case it is `apache` and runs as `www-data` (except the root process, as described [here](http://serverfault.com/a/310883/126310)):
```
user@FQDN:~$ ps auxf | grep apache
user       7767  0.0  0.4   4148  1820 pts/0    S+   15:13   0:00              \_ grep --color=auto apache
root      7391  0.0  4.7 110300 21136 ?        Ss   14:33   0:01 /usr/sbin/apache2 -k start
www-data  7663  0.0  1.8 110524  8196 ?        S    15:09   0:00  \_ /usr/sbin/apache2 -k start
www-data  7673  0.6  5.6 116572 25364 ?        S    15:10   0:01  \_ /usr/sbin/apache2 -k start
www-data  7674  0.0  1.8 110524  8196 ?        S    15:10   0:00  \_ /usr/sbin/apache2 -k start
```
My configuration did not change recently and the only thing I tried is a manual upgrade to OC8 stable from OC7 stable.

**Comment by DeepDiver1975** [comment]
> If I delete the config.php then I get an installation prompt where I could enter new root credentials and database settings.

@PeterPablo how do permissions look like after generation? THX

**Comment by PeterPablo** [comment]
When I delete the config.php, the newly generated one looks like this:
`-rw-r-----  1 www-data www-data   61 Feb  9 15:28 config.php`
(the same)

Manually deleting a key from the mysql database (#13980) at least makes a "your instance is currently being upgraded" appear, but unfortunately the system is idle and doesn't proceed (checked by htop and iotop).
I am uncertain which issue is dominating in my case. Hopefully I don't clutter/mix the two issues.

**Comment by PeterPablo** [comment]
I gave it another try, this time directly on the console with `$ sudo -u www-data php occ upgrade`.
It worked without issue.

**Comment by Free16t** [comment]
Well it does work for me to but know I have this error on the `nginx-errors.log`
>80946#0: *3 "/home/www/owncloud/index.php/apps/files/index.html" is not found (20: Not a directory), >client: XXX, server: XX, request: "GET /owncloud/index.php/apps/files/ HTTP/1.1"

My user for nginx is www

**Comment by Free16t** [comment]
I find a solution to my issue but now I have this error message:
`{"reqId":"cbfa35eb36736b8c6d53e4668fe72cf3","remoteAddr":"XXX","app":"index","message":"Exception: {\"Message\":\"The requested uri(\\\/owncloud\\\/index.php\\\/apps\\\/files\\\/) cannot be processed by the script '\\\/home\\\/www\\\/owncloud\\\/index.php')\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/www\\\/owncloud\\\/lib\\\/base.php(763): OC_Request::getRawPathInfo()\\n#1 \\\/home\\\/www\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#2 {main}\",\"File\":\"\\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/request.php\",\"Line\":297}","level":4,"time":"2015-02-21T16:15:07+00:00"}
`
Do you have a solution?

Sincerely

**Comment by Constey** [comment]
I had the same issue - it was related to wrong file owner permissions.
Try a chown www-data:www-data owncloud -R to resolve this issue.
(Replace www-data with your Webserver User)

**Comment by karlitschek** [comment]
very likely a permission problem. closing

**Comment by PeterPablo** [comment]
This happened to me again while manually updating to 8.0.3. The problematic command is `cp owncloud_bak/config/config.php owncloud/config/` that I executed as `root`, since this makes the duplicated `config.php` to be owned by root.
Upon visiting the OwnCloud instance with a browser, you are only presented with a white page and with the following error in the log:
`PHP Warning:  flock() expects parameter 1 to be resource, boolean given in /var/www/owncloud/lib/private/config.php on line 178`

May be it is worth to invest a little bit in this user error, catch the `flock` exception and throw a proper error (instead of a blank page)?

**Comment by ebanders** [comment]
+1 (Reopen issue to include proper error message in logs)
