### ISSUE TITLE
External Storage with special charackters

### ISSUE THREAD

**Issue by JT1301** [owncloud/core#13916]
Hello,

I currently try to connect a hard drive via smb to the owncloud.
It works so far but I have a problem with special characters like Ä,Ü,Ö...

For example, the structure on the hard drive is something like this:
-Corporate Documents
--Formulare
--Präsentation
--Vorlagen
-Design
...
...
When I look at the structure over ownCloud, I see the following:
-Corporate Documents
--Formulare
-Design
...
...

I tried to rescan the Filesystem via "php console.php files:scan --all" and then I saw that there are Problems with the Ä.
Here the line from the scan:
"Scanning /***********/files/SMB1/Corporate documents/Pr Vorlagen"

Is there a solution for this? (Apart from avoiding special charackters in folder names...)

OS Debian Wheezy
Owncloud 7.0.4 (in previous versions it was the same error)
Database: MySQL 7.0.4.2
PHP: 5.4.36-0

Do you need more Information?

Thank you in advance for help
Regards,
JT

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by Xenopathic** [comment]
I just did a quick test, files with special characters come through OK in an SMB mount. I couldn't test creation of files in the oC interface though.

**Comment by abelgomez** [comment]
I stumbled upon the same problem in a fresh installation of OC 7.0.4 also in a new installation of Debian Wheezy.
In my case, regenerating the system locales (`dpkg-reconfigure locales`) solved the problem. I also set the default system locale to en_US.UTF-8.

**Comment by JT1301** [comment]
Abelgomez this has fixed the problem with the view.
Now I have the problem that the data is synchronized with the client, but even though the user has write permission, he can't edit or create anything.

Error 	PHP 	NT_STATUS_ACCESS_DENIED making remote directory params(-d 0 '//172.26.110.13/corporate_documents$' -c 'mkdir "\Test"') at /var/www/owncloud/apps/files_external/3rdparty/smb4php/smb.php#201 	2015-02-06T10:42:16+00:00 

The share comes from a Windows Server 2008 R2. The config of the external storage in Owncloud (GUI) is:
SMB / CIFS  -> 172.26.110.13 -> domain/user -> password -> /corporate_documents$ -> /

The User has full access to the Windows Share (NTFS and Share permission).

Do you have a solution for this too?

**Comment by Xenopathic** [comment]
An NT_STATUS_ACCESS_DENIED means that your server configuration is incorrect. Please ensure your user has write access to the share and the real folder on the server.

As far as the original issue with UTF-8 characters is concerned, can this be closed?

**Comment by JT1301** [comment]
My mistake ... Two Different share name can of course also have different permissions.

Thank you, the problem is solved.
