### ISSUE TITLE
[Debian] Apache can't restart after installing owncloud-config-apache package 

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#13914]
### Steps to reproduce
Install owncloud package in Debian 6:

echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/Debian_6.0/ /' >> /etc/apt/sources.list.d/owncloud.list 
apt-get update
apt-get install owncloud

while installing I can see this output:
```
Setting up owncloud-server (8.0.0~RC1-3) ...
Setting up owncloud-config-apache (8.0.0~RC1-3) ...
Action 'configtest' failed.
The Apache error log may have more information.
Your Apache 2 configuration is broken, so we're not restarting it for you.
Setting up owncloud-3rdparty (8.0.0~RC1-3) ...
```

Trying to restart apache2 manually:
```
apache2: Syntax error on line 227 of /etc/apache2/apache2.conf: Could not open configuration file /etc/apache2/conf.d/owncloud.conf: No such file or directory
Action 'configtest' failed.
```

### Expected behaviour
Apache can restart after installing owncloud-config-apache.

### Actual behaviour
Apache isn't able to restart.

**Comment by MorrisJobke** [comment]
cc @jnweiger

**Comment by SergioBertolinSG** [comment]
Problem happens also in a Debian 7 environment (with php 5.4).

**Comment by MorrisJobke** [comment]
@DeepDiver1975 @karlitschek I added the showstopper label here

**Comment by jnweiger** [comment]
most parts of debian.control had no effect. Reason stil unclear.
moving owncloud.conf before dh_install should fix this.
Committed revision 71. project:isv:ownCloud:community:8.0

**Comment by jnweiger** [comment]
fixed.
<pre>
# ls -la /etc/apache2/conf-*               
/etc/apache2/conf-available:
total 32
-rw-r--r-- 1 root root  133 Feb  6 21:11 owncloud.conf

/etc/apache2/conf-enabled:
total 8
lrwxrwxrwx 1 root root   31 Feb  7 00:10 owncloud.conf -> ../conf-available/owncloud.conf

# service apache2 start 
 * Starting web server apache2
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.1.144. Set the 'ServerName' directive globally to suppress this message
 * 

</pre>

**Comment by SergioBertolinSG** [comment]
Tested with published indications in debian 7.
```echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/community/Debian_7.0/ /' >> /etc/apt/sources.list.d/owncloud.list 
apt-get update
apt-get install owncloud
```
Working fine. Apache restarts.

**Comment by SergioBertolinSG** [comment]
Tested with version 8.0.0-1, no problems with apache restart.
Using this repository 
```
http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/Debian_7.0/
```
not website download repo (Still has 7 version).
