### ISSUE TITLE
LDAP app - raw user filter doesn't restrict who can authenticate

### ISSUE THREAD

**Issue by unamedplayer** [owncloud/core#13929]
When setting up a raw user filter to limit to 1 user for example:
(cn=John Doe)

clicking the "Test Filter" button pulls a count of 1 user, going to the "Users" panel shows the right user.

But any user in the directory can still log in. When they do so, a folder is created for them in data but they still don't show up in the user list.

Reproducible in OwnCloud 7, just test in owncloud-8.0.0RC2.

Please let me know if I can do anything to help resolve the issue.

Screenshots:
LDAP config:
![screen shot 2015-02-05 at 12 28 01](https://cloud.githubusercontent.com/assets/5199967/6065493/d3a18aca-ad33-11e4-832a-e09cc1bb0dd3.png)
User list:
![screen shot 2015-02-05 at 12 28 18](https://cloud.githubusercontent.com/assets/5199967/6065495/d3a89b94-ad33-11e4-8bd9-5c1cc713e858.png)
But wait, rando guy can still log in :):
![screen shot 2015-02-05 at 12 29 01](https://cloud.githubusercontent.com/assets/5199967/6065494/d3a2919a-ad33-11e4-9248-8f3b597cb339.png)

Adding console.php's thoughts if this can be helpful:
![screen shot 2015-02-05 at 12 56 56](https://cloud.githubusercontent.com/assets/5199967/6065869/9c7aa5ce-ad36-11e4-8f78-6b592d1f07c0.png)

**Comment by RealRancor** [comment]
Hi,

could be possible that this is currently more a documentation issue: https://github.com/owncloud/documentation/issues/774

You need to configure the "Login filter" to limit the access, not the "User filter".

**Comment by MorrisJobke** [comment]
cc @blizzz

**Comment by blizzz** [comment]
Access is restricted by the Login filter, not the User filter. This is for listing.

**Comment by unamedplayer** [comment]
Thank you for pointing this out, I just confirmed it.

The verbiage of the "User Filter" tab is supper confusing: "Limit ownCloud access to users meeting these criteria: " that to me implies that users not meeting the criteria don't get access :)

Same with the verbiage of the "Login Filter" tab: "Users login with this attribute", does not mention access restriction at all.

I end up with a fairly repetitive set of filters:
   user: (|(cn=unamedplayer))
   login: (&(sAMAccountName=%uid)(cn=unamedplayer))

Which works really well, thank you for explaining how these filters operate. My humble suggestion is to change to verbiage to prevent further tickets :)

take care.

**Comment by RealRancor** [comment]
@unamedplayer 
Consider re-open this issue or create a new one with this suggestion:

>My humble suggestion is to change to verbiage to prevent further issues opened in GitHub :)

**Comment by MorrisJobke** [comment]
> create a new one with this suggestion:

Voila: #13936
