### ISSUE TITLE
Better wording in LDAP wizard

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#13936]
The verbiage of the "User Filter" tab is supper confusing: "Limit ownCloud access to users meeting these criteria: " that to me implies that users not meeting the criteria don't get access :)

Same with the verbiage of the "Login Filter" tab: "Users login with this attribute", does not mention access restriction at all.

From https://github.com/owncloud/core/issues/13929#issuecomment-73157481

cc @blizzz @unamedplayer

**Comment by blizzz** [comment]
Pull requests welcome :)

**Comment by michaelhofer** [comment]
Still looking for pull requests? I'd like to contribute to this project and this seems like an very easy start =)

**Comment by MorrisJobke** [comment]
@michaelhofer Sure :) Feel free to open one. Simply mention me there. Feel free to join our #owncloud-dev channel on IRC: https://doc.owncloud.org/server/8.1/developer_manual/commun/index.html

**Comment by blizzz** [comment]
Regarding this specific issue, there are already changes in a feature branch which will go to master and 8.1. But in general, Pull Requests are welcome, you could follow the ["Junior  Job"](https://github.com/owncloud/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22Junior+Job%22) tag to find thinks to tackle as a start.

**Comment by blizzz** [comment]
Well, partly fixed in https://github.com/owncloud/core/pull/15492

**Comment by PVince81** [comment]
@blizzz any update ?

**Comment by blizzz** [comment]
Um, no, too late for 8.2 as enhancement anyway.

**Comment by PVince81** [comment]
@davicente I suggest to start with this one to get in touch with LDAP stuff

**Comment by davicente** [comment]
@PVince81 
I don't know if changing the wording in the wizard php file, because it would break all the translations, or just change the english l10n translation, which I suppose it would be undo when the translation files are created again

**Comment by PVince81** [comment]
@davicente as discussed on IRC: you can change text in PHP or JS files. Once it's merged on master, the translation bot will pick the changes up and sync with transifex, where people will retranslate the texts. Later on, the translation bot will sync the translations back into the l10n/* files (don't touch these).

As long as the commits go to master eventually, there is nothing to worry about :smile:
