### ISSUE TITLE
Ability to reconfigure SFTP external storage instead of delete and reconfigure

### ISSUE THREAD

**Issue by gig13** [owncloud/core#13947]
**Expected Behavior**
Setup an SFTP external storage mount and be able to modify the path without having to reconfigure due to setting up an incorrect path.

**Actual Behavior**
After setting up an SFTP external storage mount when typing in the folder name, URL, username and password,  the server connects and added the "/" as the root folder and EVERYTHING on the cluster was suddenly in the connected external storage. I did not have time to set the correct sub folder path.
I was then unable to modify it and needed to remove it and then reconfigure.

**Steps to Reproduce**
Add an SFTP external storage mount by typing in the folder name, URL, username and password.
Then try and modify the path to a subfolder (for example:  "/home/mydirectory/myOCsync")

**Server Configuration**
OC7.0.4
Red Hat EL 6.5
MySQL Database
SFTP External Storage

**Comment by gig13** [comment]
@MTRichards @MorrisJobke

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by MTRichards** [comment]
I would categorize this as a nice to have UX improvement across the board, for all secondary storage, not just FTP.

**Comment by gig13** [comment]
Agreed -- for all secondary storage

**Comment by PVince81** [comment]
Yes... ideally the configuration should NOT auto-save unless fully configured.
If we could have a popup to configure the external storages (especially if we start adding more options), it would be possible to display all fields in a more vertical manner but also make it possible for the user to click "OK" to save instead of having auto-save.

@owncloud/designers

**Comment by PVince81** [comment]
CC @Xenopathic

**Comment by Xenopathic** [comment]
This particular issue has been solved, either with a bug fix along the way or with #11884 which enabled proper storage config updating. The sub issue with not autosaving a storage (requiring an explicit save) is separate, and if it is still considered a notable issue, please open a new issue for it.
