### ISSUE TITLE
Web UI has problems with starting special characters in filenames.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#13946]
### Steps to reproduce

1. Upload a file with a filename starting by a special character (ñ, ö...)

### Expected behaviour
File is uploaded and web UI shows the full filename.

### Actual behaviour
File is uploaded, but web UI removes the first special character, if you upload a file named 'ñtestfile', web ui shows 'testfile' and it conflicts with files named like that and you can't remove the file.

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.0.0.6","versionstring":"8.0 RC 2","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
Default in enterprise edition

**Logs**
Nothing was write in the owncloud.log during this process.

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** no

### Client configuration
Chrome, Firefox.

**Comment by MorrisJobke** [comment]
I have no problems here with Firefox on Linux:

 * `ña.bmp`
 * `a.bmp`
 * `äöüunicodehell.bmp`

**Comment by MorrisJobke** [comment]
Oh. Maybe it's the MySQL. Let me check that

**Comment by MorrisJobke** [comment]
The mysql charset stuff should be fixed with oc8. Are there any errors in the owncloud.log?

**Comment by MorrisJobke** [comment]
@SergioBertolinSG ^

**Comment by MorrisJobke** [comment]
Ah. I tried with mariadb. Let me test mysql too.

**Comment by SergioBertolinSG** [comment]
No, I deleted owncloud.log before the test and nothing new was written.

**Comment by MorrisJobke** [comment]
I can't even reproduce with mysql 5.6.23.

**Comment by DeepDiver1975** [comment]
Maybe the locale en_US-utf8 is not installed? 
Php module intl missing?

**Comment by mmattel** [comment]
do you have a setting in your corresponding php.ini
`default_charset = "utf-8"`

**Comment by SergioBertolinSG** [comment]
Php module intl is enabled.
default_charset in php.ini is empty.
Only happens with starting characters, not in the middle of the filename.

**Comment by DeepDiver1975** [comment]
Is that locale installed?

**Comment by SergioBertolinSG** [comment]
Yes. 
In daily/master this is working.

**Comment by SergioBertolinSG** [comment]
I am using enterprise version.

**Comment by guruz** [comment]
@lmaestro mentioned that she had https://github.com/owncloud/client/issues/2794 with a nightly build of the server. But when she re-created the folder fromthe webinterface it worked.. so it is fixed now with a newer server nightly?
Does that ring a bell for anyone here?

**Comment by PVince81** [comment]
I'm not away of any recent changes regarding special characters / locale

**Comment by jnfrmarks** [comment]
@SergioBertolinSG 

Any info on this one?

**Comment by SergioBertolinSG** [comment]
Tested in  8.1 alpha 3 enterprise edition. Working fine now.
