### ISSUE TITLE
[8.0] Activate button is present for already activated apps

### ISSUE THREAD

**Issue by etiess** [owncloud/core#13945]
### Steps to reproduce
1. Activate Calendar 8.0 0.6.4 for example
2. Go into "Recommended" app section

### Expected behaviour
The button should be grey and show "Deactivate" like in the "Activated" section of the app menu

### Actual behaviour
The "Activate" button is there for the Calendar app. If you click on it, the following message is shown: "The folder already exists".
This is true for the other apps too.

### Server configuration
Ubuntu 14.10
3.16.0-30-generic
Server version: Apache/2.4.10 (Ubuntu)
PHP 5.5.12-2ubuntu4.1 (cli) (built: Oct 29 2014 11:59:49)
with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies
mysql  Ver 14.14 Distrib 5.5.41, for debian-linux-gnu (x86_64) using readline 6.3

**ownCloud version:** 8.0 RC2

**Updated from an older ownCloud or fresh install:** Fresh Install

**List of activated apps:** default ones + Contacts, Document, Calendar

**Are you using external storage, if yes which one:** local/smb/sftp/... NO

**Are you using encryption:** no

**Comment by MorrisJobke** [comment]
cc @DeepDiver1975 Looks like a regression in the app management

**Comment by MorrisJobke** [comment]
Could this be caused by wrong OCSIDs?

**Comment by DeepDiver1975** [comment]
Upgrade or fresh install of owncloud?

If update: was calendar already present before? 

Thx

**Comment by etiess** [comment]
Fresh install

**Comment by etiess** [comment]
Just installed 8.0 as a fresh install: the issue is still present.

**Comment by jancborchardt** [comment]
@DeepDiver1975 this seems to be a duplicate of https://github.com/owncloud/core/issues/14004 (or the other way around)?

Either way @etiess please test if https://github.com/owncloud/core/pull/14009 fixes this for you.

**Comment by etiess** [comment]
@DeepDiver1975 Do you want I test another version?

**Comment by PVince81** [comment]
CC @dttpy

**Comment by PVince81** [comment]
@etiess would be good if you could retest with the PR, yes. Then we can close this ticket :smile:

**Comment by DeepDiver1975** [comment]
The ocsids in calendarn contacts and probably all other apps need to be reviewed and fixed.

But basically the fix is there: https://github.com/owncloud/core/pull/14009 and this issue can be closed from my pov

**Comment by DeepDiver1975** [comment]
From my understanding this is not really that critical and does not justify a backport to 8.0.1

**Comment by etiess** [comment]
@PVince81 I wanted to test it, so I did as usual. But when I want to connect to OC the first time, I get this message: "Le paramètre PHP "output_buffering" n'est pas "'off'"."   (The parameter PHP "output_buffering" is not "off".
My standard OC installation on the same server still works properly.
I downloaded the file from Github, the master branch.
Does it come from my server?

**Comment by PVince81** [comment]
Hmmm, never copy and replace files directly.

Normally you would download the patch from https://github.com/owncloud/core/pull/14009.patch but from what I see that patch doesn't apply on top of 8.0.0.
So we're out of luck as there is no backport patch for this.

**Comment by etiess** [comment]
I just installed 8.0.2 and it's fixed. I close the issue.
