### ISSUE TITLE
Dropping a folder into the files list does not display the warning anymore

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#13940]
You only see a little yellow line, but the text itself is missing:
![files_-_owncloud_-_2015-02-06_10 54 34](https://cloud.githubusercontent.com/assets/213943/6077384/9750555e-adee-11e4-98dd-64f255db2b8d.png)

@MorrisJobke as discussed

**Comment by MorrisJobke** [comment]
This was also broken in 7.0.0

**Comment by MorrisJobke** [comment]
I will debug

**Comment by MorrisJobke** [comment]
Same for stable6 o.O

**Comment by MorrisJobke** [comment]
Fix is in #13941

**Comment by DeepDiver1975** [comment]
no regression - no showstopper -> 8.0.1

**Comment by DeepDiver1975** [comment]
@nickvergessen which browser? AFAIK there is already a pr open which tries to fix this

**Comment by nickvergessen** [comment]
Firefox 35.0.1,
as per PR its a problem with the browser version, not with the oC version.
Still quite annoying

**Comment by MorrisJobke** [comment]
ref #10105
