### ISSUE TITLE
OC 8 RC2: Log flooded with php messages: readdir() expects parameter 1 to be resource, boolean

### ISSUE THREAD

**Issue by AW-UC** [owncloud/core#13953]
I installed OC 8 RC2 and deactivated all apps. As soon as I browse to my OC login page (don't even have to login) my owncloud.log is flooded with:
`{"reqId":"a795aba02ba3565855ce2967d2a5493d","remoteAddr":"xx.xxx.xxx.xx","app":"PHP","message":"readdir() expects parameter 1 to be resource, boolean given at \/mnt\/web2\/c1\/92\/xxxxxx\/htdocs\/owncloud\/lib\/private\/tempmanager.php#135","level":3,"time":"2015-02-06T16:14:57+00:00"}`
The log grows to several MBs within minutes! The remoteAddr is the IP address of my pc (I blanked it in the quote). I can login, but OC reactes slowly and sometimes I receive an internal server error.
tempmanager.php:135 is `while (($file = readdir($dh)) !== false) {`
A quick look at the code, suggests that `$file` might be undefined or we need an `==` instead of `=`.

PHP Version = 5.5.21
MYSQL = 5.0.96

**Comment by DeepDiver1975** [comment]
@icewind1991 looks like there is a check for null missing - please submit pr to fix this - THX

**Comment by LukasReschke** [comment]
Confirmed again on IRC:

```irc
14:16:11 <mbiebl_> been testing oc 8.0 RC1
14:16:39 <mbiebl_> seems my owncloud.log is over 220 GB
14:16:53 <mbiebl_> looks a bit excessive to me :-)
14:17:31 <AnybodyElse> mbiebl_: File a bug please and we can take a look at this – shouldn’t happen if you have the system properly configured
14:18:13 <mbiebl_> AnybodyElse: I see a lot of "readdir() expects parameter 1 to be resource, boolean given at /www/htdocs/w00d7ed1/mynebula.net/owncloud/lib/private/tempmanager.php#135 "
14:18:18 <mbiebl_> does that ring a bell?
14:18:55 <AnybodyElse> looks like https://github.com/owncloud/core/issues/13953
```

**Comment by karlitschek** [comment]
@icewind1991 This is very annoying. Can you have a look?

**Comment by AW-UC** [comment]
To get rid of this annoyance, you can try this hotfix:
tempmanager.php#135: `if (!empty($dh)) {while (($file = readdir($dh)) !== false) {`
tempmanager.php#143: `}}`
This will silent those message. Now you will be able to find a few messages like this:
`opendir(/mnt/shared/tmp): failed to open dir: Permission denied at /xxxxx/owncloud/lib/private/tempmanager.php#134`
So, this is a permission problem. Which isn't fixable on shared hosting. Maybe #13031 will help here?
@icewind1991 it would be nice to replace the "failed to open dir" message with a warning, that one should properly configure one's tempdir.

**Comment by DeepDiver1975** [comment]
will be fixed with 8.0.1 and 8.1 - THX

**Comment by joernhees** [comment]
ugh, just ran into this as well after the log filled my whole free space... when is 8.0.1 planned to be released?

**Comment by AW-UC** [comment]
8.0.1 RC1 is already out: http://download.owncloud.org/community/testing/owncloud-8.0.1RC1.tar.bz2. To stay up to date about releases, follow the announcemnts here: https://forum.owncloud.org/viewforum.php?f=9. Of course you could also apply https://github.com/owncloud/core/commit/45e3cbefc9e069d5c904ed8961504551a51ce735 to your install, if you don't want to install the RC.

**Comment by joernhees** [comment]
yupp, already running 8.0.1 RC1 but now it's full with 
```
Error 	PHP 	opendir(/tmp): failed to open dir: Permission denied at /xxx/owncloud/lib/private/tempmanager.php#134 
```
as you reported... so i guess RC1 didn't fix it?

**Comment by AW-UC** [comment]
No, that might either be fixed with #13031 (and a properly configured temp dir) or with an additional check for permissions. Those errors shouldn't be as numerous than those other messages. So IMHO only, it is OK to wait for #13031.

**Comment by joernhees** [comment]
ah, i thought that was meant to be in 8.0.1 already. thanks for the reply

**Comment by cbhp** [comment]
This programming error generated a 1.3 Terabyte big owncloud.log on my disk with millions of lines for the readdir() issue, because the while loop ran infinite.

version:
$OC_Version = array(8,0,0,7);
$OC_VersionString = '8.0';
$OC_Channel = 'stable';
$OC_Build = '2015-02-07T02:34:55+00:00 df2808eec840c033b952e001ee8a063a93fae417';

**Comment by AW-UC** [comment]
@cbhp Please post that log, so it can be used for debugging ;-)

**Comment by abdennour** [comment]
The same issue of @cbhp  . In fact, when i stop ```php-fpm``` service , the log file size stop increasing . 
Thus ,this is something related to ```php-fpm``` . 

Any idea ?
