### ISSUE TITLE
Cross user backend sharing encryption key migration fails on update

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13950]
### Steps to reproduce:
1. Setup OC 7.0.4 with LDAP and with "root" as the local admin user
2. Enable encryption
3. Login as LDAP user "ldapuser1" to init encryption keys
4. As "root", share a folder "test" with a ldap user "ldapuser1"
5. Upgrade to OC 8.0.0~RC2
6. Run `./occ encryption:migrate` to migrate the LDAP keys
7. Login as "ldapuser1" and try downloading the files from the folder "test"

### Expected result
Files can be downloaded. Share keys properly migrated

### Actual result
Files cannot be downloaded.
It looks like only the keys from the user "root" have been migrated, not the ones from the LDAP users.

After talking to @schiesbn it seems it could be the same issue with app update order like https://github.com/owncloud/core/pull/13865 where the LDAP app isn't loaded (or loaded too late) during an update, so the migration code (the part that runs during update) doesn't find the LDAP users.

A quickfix would be to remove the "userExists()" check that is done during key migration to make sure all keys are simply copied.

I guess this issue only happens when sharing between users from different backends.
I'll retest this when sharing between LDAP users and see whether it happens too.

@schiesbn @karlitschek @DeepDiver1975 @blizzz

**Comment by PVince81** [comment]
To try:
- [ ] test when sharing between LDAP users: expected to work
- [ ] test with @blizzz's fix for app loading order during update https://github.com/owncloud/core/pull/13865 (which isn't ready for production yet)

**Comment by PVince81** [comment]
CC @jnfrmarks

**Comment by PVince81** [comment]
- [ ] test with @schiesbn's fix: https://github.com/owncloud/core/pull/13952

**Comment by PVince81** [comment]
I can confirm that files shared between two LDAP users are properly migrated by the script (given that https://github.com/owncloud/core/issues/13951 doesn't kick in).

The error case is only when sharing cross-backend.

Next step: test the fixes

**Comment by PVince81** [comment]
I can confirm that @blizzz's  script with loading order works: https://github.com/owncloud/core/pull/13865 (but is not ready for production)
It also makes the migration script obsolete, the users seemed to be migrated properly (but might be useful if people ran into timeout when upgrading in the web UI)

Next step: test @schiesbn's quickfix (which is more suited as a quick fix)

**Comment by karlitschek** [comment]
@jnfrmarks Can you help testing this? This is critical

**Comment by PVince81** [comment]
@schiesbn's patch worked for me: https://github.com/owncloud/core/pull/13952
With that one, I still need to run "sudo -uwww ./occ encryption:migrate-keys" which is fine short term.

**Comment by schiesbn** [comment]
> With that one, I still need to run "sudo -uwww ./occ encryption:migrate-keys" which is fine short term.

sure,nothing changes with respect to the occ script.

**Comment by jnfrmarks** [comment]
testing underway

**Comment by MorrisJobke** [comment]
Fixed with #13952
