### ISSUE TITLE
encryption:migrate only migrates first 10 LDAP users

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13951]
### Steps to reproduce
1. Setup OC 7.0.4 with LDAP (with more than 10 users)
2. Enable encryption
3. Upgrade to OC 8.0.0~RC2
4. Run `./occ encryption:migrate`

### Expected result
Keys for all users migrated, the output must show as many users as there are in LDAP.

### Actual result
Only first 10 users from LDAP are shown.
I didn't verify the keys (as one would need to init all these users), but it is likely that it only processed the first 10 users.

### Versions
OC 8.0.0~RC2

This would affect any setup where LDAP + encryption is used.

@DeepDiver1975 @schiesbn @karlitschek @blizzz 

CC @jnfrmarks

**Comment by PVince81** [comment]
How about using this approach: https://github.com/owncloud/core/blob/master/lib/private/repair/repairlegacystorages.php#L185

**Comment by PVince81** [comment]
@schiesbn just told me there's another location where getUsers() is used

**Comment by schiesbn** [comment]
Here https://github.com/owncloud/core/blob/master/apps/files_encryption/lib/migration.php#L45 we also use getUsers(). That's the migration path if the migration gets triggered over the web ui. We probably need a similar fix here.

**Comment by blizzz** [comment]
@schiesbn thx for the hint, will fix

**Comment by blizzz** [comment]
have fun with https://github.com/owncloud/core/pull/13954
