### ISSUE TITLE
Can't import new Calendar after a Calender has been created

### ISSUE THREAD

**Issue by RoMaTiX99** [owncloud/core#13966]
I am not able to import a calendar after I've created a seperate calendar :(.

**Comment by RealRancor** [comment]
Hi,

please re-open in: https://github.com/owncloud/calendar/issues using the issue template provided here:

https://raw.github.com/owncloud/core/master/issue_template.md

**Comment by MorrisJobke** [comment]
@RoMaTiX99 ICS files can be imported to the calender by uploading them into the files app and then click in the files app on that calendar file. If this doesn't work for you please open an issue in the calendar app inssue tracker (see above). Thanks.
