### ISSUE TITLE
Converting From SQLite to MySQL, MariaDB, or PostgreSQL: please create an unpriviledged DB user and use it

### ISSUE THREAD

**Issue by LudovicRousseau** [owncloud/core#13965]
### Steps to reproduce
1. make a default installation (so using SQLite)
2. convert the data from SQLite to PostgreSQL using the procedure at http://doc.owncloud.org/server/7.0/admin_manual/maintenance/convert_db.html
### Expected behaviour

The migration script should (as done by the install wizzard):
- create a new DB user for OwnCloud
- create a new database and give all access to this database to the newly created user
- offer the possibility to skip the 2 steps above and ask the DB Admin to do them by itself (for DB Admin that know what they do).
### Actual behaviour

I need to enter a DB admin login and password to create the database. OK fine. My problem is that the same login/password is stored in clear in `owncloud/config/config.php`. From a security point of view this is not acceptable.

I had to create a new DB user, give it access to the already created "oc_*" tables and update `owncloud/config/config.php`. That was not an easy task for me as I do not speak SQL fluently :-)
### Server configuration

OwnCloud version 7.0.4

**Comment by RealRancor** [comment]
Hi,

just keep in mind that this will bring a lot of complexity for such a single task:

For example not every user (and so the occ tool) has the possibility to create new users or databases.

**Comment by LudovicRousseau** [comment]
The complexity to create a new DB user and a new database is *already* present in the wizard setup tool. Maybe it is possible to share code.

Regarding the access rights, in both cases (setup wizzard and conversion tool) you have to give a DB admin login and password.

**Comment by RealRancor** [comment]
> Regarding the access rights, in both cases (setup wizzard and conversion tool) you have to give a DB admin login and password.

Are you sure that you need to use the db admin? There is no single note that you need to use this one in the executed code:

https://github.com/owncloud/core/blob/v7.0.4/core/command/db/converttype.php

Have you tried to use an existing user with an existing database?

**Comment by LudovicRousseau** [comment]
No, I have not tried with an existing user and database. I just followed the documentation :-)

From http://doc.owncloud.org/server/7.0/admin_manual/maintenance/convert_db.html :

Conversion Options
* ``username`` A database **admin** user.
* ``--password="mysql_user_password"`` The database **admin** password, if there is one.

Maybe the problem is just that the documentation is wrong (or not clear) and you don't need to give the login of a DB Admin but just the login of the database owner.

I propose to document two missing steps (to do as a DB Admin):
* creation of a new DB user ``CREATE USER owncloud_user;``
* creation of a new database owner by the user ``CREATE DATABASE owncloud_db WITH OWNER owncloud_user;``

**Comment by MorrisJobke** [comment]
@DeepDiver1975 Who developed the migrate tool?
