### ISSUE TITLE
Extreme CPU load and slow operation with OwnCloud external storage

### ISSUE THREAD

**Issue by dronus** [owncloud/core#13962]
ownCloud 7.0.4

If I mount an external OwnCloud storage into my OwnCloud folder, listing directories inside the mount in the web frontend takes a long time (eg. 30s for a directory containing 30 files) and the server CPU is heavily loaded, mostly by the external storage instance, lesser by the mounting instance of OwnCloud.

# What did I do
Mount as external storage another OwnCloud instance on the same server using https in some folder
The mounted tree consist of some hundred files, not more than about 40 per directory. 
Access one of the mounted directories in the web front end. Both instances running ownCloud 7.0.4 .

# What do I expect
Fluent operation, as only about 30 files of max. some MB each are in the directory.

# What happens
Listing the directory takes about 30 seconds, while putting full CPU load on the server, mostly by the external storage instance of OwnCloud

This does not only occur on the first try, but happens on every access of the same directory too.

**Comment by dronus** [comment]
The same happens, when an OwnCloud desktop client is restarted accessing the mounting instance. The client stays in the 'synchronized' state forever, while waiting for server answers that are pending for minutes on full CPU load. It takes minutes until syncing starts, maybe more then one directory has to be listed before.

**Comment by dronus** [comment]
Hmm. I would entitle this as enhancement if it happens on extreme intstallations with terabytes of data, but for my use case with an sub-average amount of data, this is already a show stopper and definetely a bug. 
I guess the effect needs other circumstances and it does NOT appear on all occasions, otherwise simple testing wouldn't have passed.
External mounts of OwnCloud instances are useless if that happens. Maybe some people only have 1mb in two files shared, even that would be slow in the case of this bug. So this is not low performance, but broken functionality.

**Comment by PVince81** [comment]
Currently OC is doing way too many requests to the target server, which could explain the CPU load.
See https://github.com/owncloud/core/issues/13882

**Comment by awnz** [comment]
I'm affected by this two (OC to OC external storage link) and would be interested to know if anyone has any workarounds while we wait for this to be fixed.

Currently considering hacking a script together that kills the sync client, swaps two sync client config folders around, and restarts it to be able to sync to two OC servers from affected users' desktop PCs.

**Comment by PVince81** [comment]
Is this still happening in 8.1.4 or 8.2 ?

**Comment by awnz** [comment]
I've got around this permanently for me by using the v2 client's multiple accounts feature.

**Comment by dronus** [comment]
Well, the feature we where waiting for years now finally eased my pain by removing the need for the external files feature. However this issue itself is still there. And there are several other use cases for external files.

**Comment by PVince81** [comment]
closing in favor of https://github.com/owncloud/core/issues/7910
