### ISSUE TITLE
Storage stat cache as storage wrapper

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13971]
Many file operations are done on upload/download (like file_exists, getMimeType(), etc).
These should be buffered instead of letting them hit the real storage several times within a single PHP request.

One idea for this would be to implement a stat cache as a storage wrapper.
The stat cache can be put directly on top of the external storage one by doing the wrapping directly in the external storage app. This would ensure that the wrapping order is correct.

We could also make it optional by adding a flag "useStatCache" in the storage backend options, because some backends already have their own stat caches.

I will have a go at implementing this.

@icewind1991 what do you think ?

**Comment by Xenopathic** [comment]
:+1: Storage wrapper seems like the best way to go about this.

**Comment by PVince81** [comment]
Hmm I just realized that this will not help as much as I want it to.

For use cases where the storage is called from outside, then every call will go through the wrapper.

But there are cases where the Storage instance calls itself (ex: is_file(), is_dir(), etc like the swift one does: https://github.com/owncloud/core/blob/master/apps/files_external/lib/swift.php#L128). In such cases, the call would not go through the wrapper and not be cached... :frowning:

**Comment by PVince81** [comment]
Not a good idea, see my previous comment.
Closing
