### ISSUE TITLE
Opensuse packages isn't updated.

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#13972]
http://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_14.10/

http://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_14.04/

http://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_12.04/

CC @jnweiger 

**EDIT**

setup-owncloud.php also contains owncloud 7. :(

*changed CC*

**Comment by PVince81** [comment]
@jnweiger

**Comment by jnweiger** [comment]
The package link there still says 'Links to isv:ownCloud:community:7.0 / owncloud'

**Comment by jnweiger** [comment]
Fixed. Committed revision 10.  isv:ownCloud:community/owncloud

**Comment by enoch85** [comment]
**setup-owncloud.php** is still downloading ownCloud 7.0.4.

**Comment by PVince81** [comment]
@enoch85 setup-owncloud.php is something else, not related to packaging.

I believe @karlitschek hasn't updated the "owncloud-latest" archive, might be intentional. (might be done later, not sure)

**Comment by PVince81** [comment]
@enoch85 someone made an explicit ticket for this here: https://github.com/owncloud/core/issues/14042
