### ISSUE TITLE
OC 8.0: File sorting case sensitive

### ISSUE THREAD

**Issue by AW-UC** [owncloud/core#13982]
Not sure whether this is the intended behaviour. My files are sorted by name like this:
A-Z
a-z
However, the "common" (most apps/OS) pattern is: aA-zZ.
Can we have an option for case insensitive sorting?

**Comment by PVince81** [comment]
Please install php5-intl

**Comment by PVince81** [comment]
You might also want to check whether your locale en_US.UTF-8 is installed/configured properly.

Feel free to reopen if it still happens after that, and use the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by PeterPablo** [comment]
I confirm thatinstsalling`php5-intl` solves the described problem.

**Comment by AW-UC** [comment]
@PVince81 I'm on shared hosting so installing php5-intl is not an option. Any ideas for a workaround? It used to work fine on previous versions of OC. How about using [natcasesort](http://php.net/manual/en/function.natcasesort.php)?

**Comment by PVince81** [comment]
You could add a fallback here: https://github.com/owncloud/core/blob/master/lib/private/naturalsort.php#L59

Note that without php5-intl there will be inconsistency in sorting between the JS side (client side sort) and server side (there were already some in the past)

**Comment by PVince81** [comment]
Actually you might want to change the default collator (or provide yet another collator for when php5-intl isn't installed): https://github.com/owncloud/core/blob/master/lib/private/naturalsort_defaultcollator.php#L14

You could try putting `natcasesort` if that's a solution that works in your env.

**Comment by AW-UC** [comment]
@PVince81 What about generally using `strcasecmp()` in NaturalSort_DefaultCollator? Like this;

    class NaturalSort_DefaultCollator {
      public function compare($a, $b) {
        if (strcasecmp($a, $b) == 0) {
          return 0;
        }
        return (strcasecmp($a, $b) < 0) ? -1 : 1;
      }
    }
Works great for me.

**Comment by PVince81** [comment]
@AW-UC do you mind sending a PR for this change ?

I'm reopening the ticket for visibility.

**Comment by AW-UC** [comment]
@PVince81 yeah, no problem. We can evan go with `strnatcasecmp()`. Doesn't make a difference for me, but I think it's safer.
