### ISSUE TITLE
Blank Page after Upgrade from 7 to 8

### ISSUE THREAD

**Issue by oureas** [owncloud/core#13986]
### Steps to reproduce
1. Open ownCloud per WebGUI in a browser (i.e Safari, Firefox)

### Expected behaviour
Browser should show Login page.

### Actual behaviour
There is a blank page. No error site or similar.

### Server configuration
**Operating system**: Ubuntu 14.04 LTS

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 5.5

**ownCloud version:** 8.0

**Updated from an older ownCloud or fresh install:** Upgrade from 7.0.4

**List of activated apps:**
 - activity
 - bookmarks
 - calendar
 - contacts
 - documents
 - files
 - files_pdfviewer
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - files_videoviewer
 - gallery
 - search_lucene
 - templateeditor
 - updater

**The content of config/config.php:**
``<?php
$CONFIG = array (
  'instanceid' => 'id',
  'passwordsalt' => 'salt',
  'secret' => 'secret',
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => 'example.com',
    2 => '192.168.3.9',
  ),
  'datadirectory' => '/var/www/html/data',
  'dbtype' => 'mysql',
  'version' => '8.0.0.7',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'default_language' => 'de',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin',
  'dbpassword' => 'password',
  'installed' => true,
  'forcessl' => true,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'notification',
  'mail_domain' => 'example.com',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'mail.anver.ch',
  'mail_smtpport' => '25',
  'mail_smtpname' => 'mail@example.com',
  'mail_smtppassword' => 'password',
  'trashbin_retention_obligation' => 30,
  'trashbin_auto_expire' => true,
  'theme' => 'theme',
  'maintenance' => false,
);``

**Are you using external storage, if yes which one:** NFS

**Are you using encryption:** No

### Client configuration
**Browser:** Safari

**Operating system:** OS X 10.10, 

#### Web server error log
`[Mon Feb 09 04:35:57.658298 2015] [:error] [pid 2039] [client 212.51.147.121:5955] PHP Fatal error:  Class 'OC_Connector_Sabre_Principal' not found in /var/www/html/apps/contacts/appinfo/remote.php on line 39
[Mon Feb 09 04:36:01.626331 2015] [:error] [pid 2229] [client 212.51.147.121:38863] PHP Fatal error:  Class 'OC_Connector_Sabre_Principal' not found in /var/www/html/apps/contacts/appinfo/remote.php on line 39
[Mon Feb 09 06:34:16.642919 2015] [core:notice] [pid 2035] AH00052: child pid 2204 exit signal Segmentation fault (11)
[Mon Feb 09 06:34:16.643051 2015] [core:notice] [pid 2035] AH00052: child pid 2223 exit signal Segmentation fault (11)
[Mon Feb 09 06:34:16.643300 2015] [core:notice] [pid 2035] AH00052: child pid 2225 exit signal Segmentation fault (11)
[Mon Feb 09 06:34:16.647688 2015] [mpm_prefork:notice] [pid 2035] AH00169: caught SIGTERM, shutting down
[Mon Feb 09 06:34:38.277106 2015] [mpm_prefork:notice] [pid 1853] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 OpenSSL/1.0.1f configured -- resuming normal operations
[Mon Feb 09 06:34:38.277615 2015] [core:notice] [pid 1853] AH00094: Command line: '/usr/sbin/apache2'
[Mon Feb 09 06:53:35.130207 2015] [mpm_prefork:notice] [pid 1853] AH00169: caught SIGTERM, shutting down
[Mon Feb 09 06:53:36.175133 2015] [mpm_prefork:notice] [pid 2588] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 OpenSSL/1.0.1f configured -- resuming normal operations
[Mon Feb 09 06:53:36.175198 2015] [core:notice] [pid 2588] AH00094: Command line: '/usr/sbin/apache2'
[Mon Feb 09 06:54:16.846868 2015] [mpm_prefork:notice] [pid 2588] AH00169: caught SIGTERM, shutting down
[Mon Feb 09 06:54:17.872977 2015] [mpm_prefork:notice] [pid 2643] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 OpenSSL/1.0.1f configured -- resuming normal operations
[Mon Feb 09 06:54:17.873040 2015] [core:notice] [pid 2643] AH00094: Command line: '/usr/sbin/apache2'
[Mon Feb 09 07:09:41.855576 2015] [mpm_prefork:notice] [pid 2643] AH00169: caught SIGTERM, shutting down
[Mon Feb 09 07:09:42.893730 2015] [mpm_prefork:notice] [pid 2820] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 OpenSSL/1.0.1f configured -- resuming normal operations
[Mon Feb 09 07:09:42.893797 2015] [core:notice] [pid 2820] AH00094: Command line: '/usr/sbin/apache2'
[Mon Feb 09 07:11:18.152962 2015] [mpm_prefork:notice] [pid 2820] AH00169: caught SIGTERM, shutting down
[Mon Feb 09 16:11:19.194859 2015] [mpm_prefork:notice] [pid 2902] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 OpenSSL/1.0.1f configured -- resuming normal operations
[Mon Feb 09 16:11:19.194921 2015] [core:notice] [pid 2902] AH00094: Command line: '/usr/sbin/apache2'
[Mon Feb 09 16:13:56.374063 2015] [mpm_prefork:notice] [pid 2902] AH00169: caught SIGTERM, shutting down
[Mon Feb 09 16:13:57.411974 2015] [mpm_prefork:notice] [pid 2958] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 OpenSSL/1.0.1f configured -- resuming normal operations
[Mon Feb 09 16:13:57.412044 2015] [core:notice] [pid 2958] AH00094: Command line: '/usr/sbin/apache2'
[Mon Feb 09 16:14:17.664557 2015] [mpm_prefork:notice] [pid 2958] AH00169: caught SIGTERM, shutting down
[Mon Feb 09 16:14:18.696399 2015] [mpm_prefork:notice] [pid 3012] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 OpenSSL/1.0.1f configured -- resuming normal operations
[Mon Feb 09 16:14:18.696461 2015] [core:notice] [pid 3012] AH00094: Command line: '/usr/sbin/apache2'
[Mon Feb 09 16:14:44.165138 2015] [mpm_prefork:notice] [pid 3012] AH00169: caught SIGTERM, shutting down
[Mon Feb 09 16:14:45.208373 2015] [mpm_prefork:notice] [pid 3076] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 OpenSSL/1.0.1f configured -- resuming normal operations
[Mon Feb 09 16:14:45.208433 2015] [core:notice] [pid 3076] AH00094: Command line: '/usr/sbin/apache2'`

**Comment by hidden72** [comment]
Seeing similar from 7.0.4 upgrade to 8.0.

**Comment by LukasReschke** [comment]
You need to update the calendar and contacts application as well. Remove everything in the application folder for that and then reinstall them afterwards. See our upgrading guide: http://doc.owncloud.org/server/8.0/admin_manual/maintenance/upgrade.html

**Comment by DeepDiver1975** [comment]
> Class 'OC_Connector_Sabre_Principal' not found

this class no longer exists in OC8 - please update the contacts app

**Comment by hidden72** [comment]
from /var/www/owncloud/apps, I removed all of the files & subdirectories.  After that I re-extracted the owncloud-8 tarfile and things came up for me.

**Comment by jelle-e** [comment]
So, just to check entire process.
0) Disable 3rd party apps in admin interface
1) Backup database
2) Remove (after backup) entire owncloud folder.
3) Extract owncloud8 to (main) owncloud folder
4) Copy original config.php to owncloud/config/.
5) Bring owncloud up 
6) Through webinterface upgrade/update database
7) Copy over 3rd party apps you want to use and activate them

Is this right or am I missing something?

**Comment by oureas** [comment]
I deleted the apps folder and copied the files from the OC 8 tarfile and now it works. I just overwritten the files. The issue can be closed. Thanks to everyone!

**Comment by arthuragone** [comment]
Still get a blank page

**Comment by Phunny** [comment]
same over here, upgrade screwed the DAV story up, removed the database the installation completely, removed any files in the data directory and installed 8.0 from scratch 
worked .. but calendar was strange running into error, some groups are there but not appeared in the sharing popup's
reinstalled again .. working but empty page .. removed all install again .. worked and i created user and group , restarted apache .. white page .. i'm nearly giving up :(
logfile doesnt say anything which give any hint

**Comment by maxbader** [comment]
Hi.

I had the same problem, 
I upgraded to version  8.0.4 and I got an empty blank weight page.
    sudo -u www-data php occ app:disable calendar
    sudo -u www-data php occ app:disable contacts
But you have to step first into your owncloud folder.

Greetings
Markus
