### ISSUE TITLE
Weird ldap configID required for the ldap:test-config occ command (OC 7.0.5)

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#13981]
### Steps to reproduce
1. Add 2 configurations in the ldap admin page
2. Execute the ldap:test-config command line app

### Expected behaviour
ConfigIDs required to execute the command should be easily accessible

### Actual behaviour
The configIDs doesn't seem intuitive:

- Executing `./occ ldap:test-config 1` (which should be an intuitive ID to get the first or second configurations) gives an "Invalid ConfigID" error

- Executing `./occ ldap:test-config ''` runs fine, but doesn't seems an intuitive ID. I'm not sure whether this will check all the configurations, or just the first one

- Executing `./occ ldap:test-config s01` I think it checks the second configuration, but from an user's point of view it should stand for the first configuration. Plus, the configID doesn't seem to appear anywhere (not in the wizard, nor any any other command line option)

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache

**Database:** sqlite3

**PHP version:** 5.5

**ownCloud version:** 7.0.5 RC1 (testing) 

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by karlitschek** [comment]
@blizzz

**Comment by blizzz** [comment]
./occ ldap:show-config reveals the configuration id. The very first one is an empty string, the following in a pattern x##.

**Comment by titansmc** [comment]
Hi,
Probable I am doing something weird, but I cannot see the configID here.

# sudo -u wwwrun ./occ ldap:show-config 
+------------------------------+---------------------------------------------------------------+
| Configuration                |                                                               |
+------------------------------+---------------------------------------------------------------+
| hasMemberOfFilterSupport     |                                                               |
| hasPagedResultSupport        |                                                               |
| homeFolderNamingRule         |                                                               |
| lastJpegPhotoLookup          | 0                                                             |
| ldapAgentName                |                                                               |
| ldapAgentPassword            | ***                                                           |
| ldapAttributesForGroupSearch |                                                               |
| ldapAttributesForUserSearch  | displayName                                                   |
| ldapBackupHost               |                                                               |
| ldapBackupPort               |                                                               |
| ldapBase                     | ou=bsc-cns,dc=es                                              |
| ldapBaseGroups               | ou=bsc-cns,dc=es                                              |
| ldapBaseUsers                | ou=bsc-cns,dc=es                                              |
| ldapCacheTTL                 | 600                                                           |
| ldapConfigurationActive      | 1                                                             |
| ldapEmailAttribute           | mail                                                          |debug2: channel 0: window 999083 sent adjust 49493

| ldapExperiencedAdmin         | 0                                                             |
| ldapExpertUUIDGroupAttr      |                                                               |
| ldapExpertUUIDUserAttr       |                                                               |
| ldapExpertUsernameAttr       |                                                               |
| ldapGroupDisplayName         | cn                                                            |
| ldapGroupFilter              | (&(|(objectclass=posixGroup)(objectclass=sambaGroupMapping))) |
| ldapGroupFilterGroups        |                                                               |
| ldapGroupFilterMode          | 1                                                             |
| ldapGroupFilterObjectclass   |                                                               |
| ldapGroupMemberAssocAttr     | memberUid                                                     |
| ldapHost                     | ldap.bsc.es                                                   |
| ldapIgnoreNamingRules        |                                                               |
| ldapLoginFilter              | (&(|(objectclass=inetOrgPerson))(uid=%uid))                   |
| ldapLoginFilterAttributes    |                                                               |
| ldapLoginFilterEmail         | 0                                                             |
| ldapLoginFilterMode          | 1                                                             |
| ldapLoginFilterUsername      | 1                                                             |
| ldapNestedGroups             | 0                                                             |
| ldapNoCase                   | 0                                                             |
| ldapOverrideMainServer       | 0                                                             |
| ldapPagingSize               | 500                                                           |
| ldapPort                     | 389                                                           |
| ldapQuotaAttribute           |                                                               |
| ldapQuotaDefault             |                                                               |
| ldapTLS                      | 0                                                             |
| ldapUserDisplayName          | displayname                                                   |
| ldapUserFilter               | (|(objectclass=inetOrgPerson))                                |
| ldapUserFilterGroups         |                                                               |
| ldapUserFilterMode           | 1                                                             |
| ldapUserFilterObjectclass    |                                                               |
| ldapUuidGroupAttribute       | auto                                                          |
| ldapUuidUserAttribute        | auto                                                          |
| turnOffCertCheck             | 0                                                             |
+------------------------------+---------------------------------------------------------------+

Thank you.

**Comment by jvillafanez** [comment]
@titansmc just read the last comment :wink: 

The very first LDAP configuration has an empty string as the configID. `./occ ldap:show-config ''` (single quotes) should show the configuration.

If you need to set any configuration value, you can do `./occ ldap:set-config '' key value`
