### ISSUE TITLE
7.0.04 to 8.0.0 not working: legacy storage repair issue

### ISSUE THREAD

**Issue by alexweirig** [owncloud/core#13980]
Hello,

updating 7.0.4 to 8.0.0 fails with the following message:

Updating ownCloud to version 8.0, this may take a while.

Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Could not automatically fix legacy storage "local::/Volumes/OWNCLOUD_DA/ocdata//admin/" => "home::admin" because they both have data.
The update was unsuccessful. Please report this issue to the ownCloud community

What does this mean? How can I fix this?
When I connect to the web interface in 7.0.4 with the admin account, there is no data in that accout.

**Comment by karlitschek** [comment]
@PVince81 What do you think?

**Comment by crysknife** [comment]
I've faced the same issue by upgrading my instance from 7.0.4 -> 8.0.0

**Comment by PeterPablo** [comment]
Could issue #13912 be related (failing upgrade process)?

**Comment by PVince81** [comment]
This is the legacy storage situation: at some point you renamed/moved the data folder but the hard-coded value in the database was still on the old one.

Did you recently change the data directory or was it a long time ago ?

If it was a long time ago, you probably want to manually delete the bogus "local::$olddatadir/$user" entry and keep only "home::$user"

**Comment by PVince81** [comment]
@karlitschek this is the reason why I thought it's maybe not a good idea to "block" updates when a legacy storage cannot be repaired: see #13513

**Comment by karlitschek** [comment]
@PVince81 Yes. I remember.

**Comment by crysknife** [comment]
I did changed the data directory quite some time ago ... even before upgrading to 7.x

**Comment by PeterPablo** [comment]
The same holds true for me. I did not modify any values manually in the database.

**Comment by crysknife** [comment]
As suggested, deleting the bogus tries fixed the issue.

**Comment by PVince81** [comment]
You guys all updated from OC 5.0.12 at some point which add the old "local::$datadir/$user" storage entries. The error message is because in OC 8 it tries to convert these to the new format "home::$user" but cannot do so because for some reason that entry already exists.

Normally when meeting both entries, ownCloud would use the "local::$datadir/$user" one by default (as per https://github.com/owncloud/core/blob/master/lib/private/files/filesystem.php#L369)

Since you guys did not change the datadir recently, the way to fix it is as follows:
Find all users who have both "local::$datadir/$user" and "home::$user" then delete the bogus "home::$user" entries before doing the upgrade. The upgrade will convert the old ones to the new ones.

**Comment by alexweirig** [comment]
Hi Vincent,

there is a contradiction in you instructions, so I just want to make absolutely sure:

are we supposed to delete the local:: or the home:: entries in the database?

I can confirm that I didn't change the data directory either. I've been updating our current OC installation ever since v4.

Here is my version history:
4.0.4
4.0.5
4.0.6
4.0.7
4.0.8
4.5.0
4.5.1
4.5.2
4.5.32
4.5.42
4.5.52
4.5.62
4.5.72
4.5.82
5.0.00
5.0.02
5.0.03
5.0.04
5.0.05
5.0.06
5.0.07
5.0.08
5.0.09
5.0.10
5.0.11
5.0.12
5.0.13
6.0.00
6.0.00a
6.0.01
6.0.02
6.0.03
6.0.04
7.0.00
7.0.01
7.0.02
7.0.03
7.0.04

**Comment by PeterPablo** [comment]
I just deleted the single entry `('local::/var/www/owncloud/data/', 2);` in the table `oc_storages` (there is now only a single entry `('local::/media/backup/owncloud_data/', 3),` with the new data location). Now OwnCloud started the update process. I will edit as soon as this is finished. Wanted to give a timely update, since other people are facing the same issue right now.

**Comment by PVince81** [comment]
@alexweirig hmmm, can you check all `local::` entries ? `select * from oc_storages where id like 'local::%'`
They should all have your current data dir.
Did you at some point move the data dir away then move it back immediately afterwards and maybe forgot ? The DB entries might help figuring this out.

**Comment by alexweirig** [comment]
I have 192 entries in local:: and 142 in home::
42 are both in local:: and home::
thus 150 unique local:: and 100 unique home::

Can I go and delete the home:: for those that have a local:: and leave all the others in place?

**Comment by PVince81** [comment]
@alexweirig yes. Do this before the upgrade. The upgrade process should then automatically convert all of them to "home::"

**Comment by alexweirig** [comment]
Since my account is one of those that has both local:: and home:: I compared the database (oc_filecache) and the web interface and it seems that home:: is more up to date than local:: so I guess it would be wiser to remove the local:: for the users that have both entries rather than removing the home::?

**Comment by PVince81** [comment]
It actually depends whether the "local::" entry contains the exact same datadir as in config.php or not.
In case it wasn't the same, then "home::" would contain the more recent data.

**Comment by alexweirig** [comment]
In config.php I have the following setting:
'datadirectory' => '/Volumes/OWNCLOUD_DA/ocdata',

in the database I see (for my account):
local::/Volumes/OWNCLOUD_DA/ocdata//alexweirig/

Except for the 2 strange // between ocdata and my userid the directory is the same, yet home:: is more recent...

**Comment by PVince81** [comment]
Hmmm... it almost looks like the $datadir for storages had a trailing slash, which probably caused the mismatch (and the creation of the "home::" entries)

**Comment by alexweirig** [comment]
OK I see, that could then explain the fact that home:: is more recent that local::

I've checked with 2 other users and we found the same situation.

I'll go ahead and remove the local:: but before that I run a backup of the database and a backup of the ocdata folder ... just in case :-)

**Comment by alexweirig** [comment]
After removing the local:: entries the migration worked like a charm.

Thanks a lot for your support

**Comment by PVince81** [comment]
Unfortunately this is something that the update script cannot detect/decide automatically and has to be done manually based on the setup. :frowning:

**Comment by alexweirig** [comment]
sure, that makes perfect sense.

I also understand that this is a situation that is hard to explain in an error message.

**Comment by PVince81** [comment]
If we see common patterns popping up like yours (the double slash), we might be able to automate it somehow. Hopefully.

**Comment by unlinker** [comment]
I had the same problem, and deleting the `local::` entries did the trick (I had no double slashes in the database though).

**Comment by Gummikavalier** [comment]
Same problem and same fix here. Update history from version oc4.5. Owncloud data directory was moved somewhere before oc5.

**Comment by RandolfCarter** [comment]
> If we see common patterns popping up like yours (the double slash), 

I have the same message during upgrade; I did change the data directory (back in I think 4.5 or 5.0 times); and yes, I also noticed a double slash (at the time when the upgrade fails with above message), for each user I have two entries, like this:
```
local::/media/exthd/owncloud/data//username/
local::/media/exthd/owncloud/data/username/
```
the one with double slash seems to be more recent (at least "news" (the app I suppose) only exists there - or is that not supposed to have a storage?)

**Comment by luto** [comment]
I've got the same problem.

```
Turned on maintenance mode
Checked database schema update
Updated database
Could not automatically fix legacy storage "local::/var/www/oc/data/xy/" => "home::xy" because they both have data.
Turned off maintenance mode
Update failed
```

Relevant storages:

```
               id                | numeric_id 
---------------------------------+------------
 home::xy                        |          8
 local::/var/www/oc/data/xy/     |        355
```

Files of `home::xy`:
```
owncloud=# SELECT fileid, storage, path FROM oc_filecache WHERE storage = 8;
 fileid | storage |                 path                 
--------+---------+--------------------------------------
    328 |       8 | 
    331 |       8 | files/documents
    338 |       8 | files/documents/example.odt
    335 |       8 | files/photos/san francisco.jpg
    336 |       8 | files/photos/paris.jpg
    337 |       8 | files/photos/squirrel.jpg
    332 |       8 | files/photos
    330 |       8 | files/ownCloudUserManual.pdf
    329 |       8 | files
(11 rows)
```

Files of `local::/var/www/oc/data/xy/`:
```
owncloud=# SELECT fileid, storage, path FROM oc_filecache WHERE storage = 355;
 fileid | storage |     path     
--------+---------+--------------
  11999 |     355 | 
  12000 |     355 | cache
  12001 |     355 | files
  12002 |     355 | files/Shared
(4 rows)
```

**Comment by PVince81** [comment]
@luto what's your "datadir" value ? Does it have a trailing slash ?

**Comment by luto** [comment]
No it doesn't: `/var/www/oc/data`

**Comment by PVince81** [comment]
If you didn't change your "datadir" recently then it is likely that the old "local::" storage is old, so you can delete that entry manually from oc_storages.

**Comment by PVince81** [comment]
This PR will change the behavior and instead of blocking the upgrade it will only show a warning: https://github.com/owncloud/core/pull/13513

**Comment by MorrisJobke** [comment]
@PVince81 This can then be closed? The backport is merged and will be shipped with 8.0.3

**Comment by PVince81** [comment]
Okay.

**Comment by abbgrade** [comment]
Hello,

i got the same error message and a changed the data directory as well some time ago.
In the database table oc_storages were a few entries with the old path (the data root and 3 home dirs).
I deleted these entries and ran the upgrade, which worked. Since that the index.php returns a blank page, whereas the clients and webdav still works.

Is there anybody with an idea for a solution?

**Comment by PVince81** [comment]
@abbgrade please post your owncloud.log from when the white screen appears.

**Comment by abbgrade** [comment]
{"reqId":"28349c2653d69f9df8806c21a335d0ab","remoteAddr":"10.101.1.215","app":"index","message":"Exception: {\"Message\":\"js file not found: script:miniColors\\\/l10n\\\/de serverroot:\\\/var\\\/www\\\/owncloud\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/templatelayout.php(156): OC\\\\Template\\\\ResourceLocator->find(Array)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/templatelayout.php(107): OC_TemplateLayout::findJavascriptFiles(Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template.php(118): OC_TemplateLayout->__construct('guest', '')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template\\\/base.php(103): OC_Template->fetchPage()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template.php(197): OC\\\\Template\\\\Base->printPage()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/util.php(826): OC_Template::printGuestPage('', 'login', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(870): OC_Util::displayLoginPage(Array, Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(825): OC::handleLogin()\\n#8 \\\/var\\\/www\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template\\\/resourcelocator.php\",\"Line\":46}","level":4,"time":"2015-03-23T19:39:24+00:00"}
	{"reqId":"28349c2653d69f9df8806c21a335d0ab","remoteAddr":"10.101.1.215","app":"PHP","message":"js file not found: script:miniColors\/l10n\/de serverroot:\/var\/www\/owncloud at \/var\/www\/owncloud\/lib\/private\/template\/resourcelocator.php#46","level":3,"time":"2015-03-23T19:39:24+00:00"}

**Comment by PVince81** [comment]
minicolors ? I grepped the apps and it might be used by the calendar app. Depending on how you did the upgrade, you might want to delete it to finish the upgrade. Then reinstall it from the apps page (this is needed anyway, not sure why the app wouldn't auto-disable during the upgrade)

**Comment by viper1vip** [comment]
How to manually delete the bogus "local::$olddatadir/$user" entry ? I mean where can I find this entry? I mean somewhere on server where is located the OC or in the mysql database?

**Comment by MorrisJobke** [comment]
@viper1vip They are in the oc_storages table and automatically cleaned up with 8.0

**Comment by viper1vip** [comment]
I do not have oc_storages table. I just checked in phpmyadmin and there is no any tables.

So why I received this communication during upgrade OC:
Could not automatically fix legacy storage "local::/home/admin/domains/XXXXXX.pl/public_html/site/owncloud/data/user/" => "home::user" because they both have data.

What should I do in this case?

**Comment by MorrisJobke** [comment]
cc @PVince81

**Comment by PVince81** [comment]
@viper1vip maybe you used another prefix or are looking at the wrong database.
If you don't see any tables in phpmyadmin, maybe you're using SQLite instead of MySQL ?
Then you need to open "data/owncloud.db" with a SQLite client.

**Comment by viper1vip** [comment]
Hi my config file looks like that:
<?php
$CONFIG = array (
  'instanceid' => 'ocbf6504805b',
  'passwordsalt' => 'XXXXX',
  'datadirectory' => '/home/admin/domains/XXXXX.pl/public_html/site/owncloud/data',
  'dbtype' => 'sqlite3',
  'version' => '7.0.4.2',
  'dbname' => 'XXXXX',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'admin_XXXXX',
  'dbpassword' => 'XXXXX',
  'installed' => true,
  'loglevel' => '0',
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' => 
  array (
    0 => 'www.XXXXX.pl',
  ),
  'secret' => 'XXXXX',
);


Also in the data/ directory I have XXXXX.db file. But this file (table) is not present in phpmyadmin. Also all OC is configured with MySQL. I think that during updata of OC the database was delate? Is it possible?

**Comment by PVince81** [comment]
Your config says "sqlite3" which means you're using SQLite, not MySQL.
As far as I know phpmyadmin only works with MySQL. You might need another client.

**Comment by viper1vip** [comment]
So the server is mysql but the server can using module sqlite to php.
So I supposed to have a table in phpmysql - as I understand. But I do not have it :(

I open "data/owncloud.db" with a SQLite client - I see tables and I see table oc_storages.
What should I do now?

I see the columns:
              "Id"                                                    "Numeric_Id":
"home::user",                                                         "1"
"075d4076e5dcab713582709db34b667d",           "2"
"17170f52934d7405f147de1f7ec80014",              "3"
"home::user2",                                                       "4"

**Comment by PVince81** [comment]
Hmm, one of "2" or "3" is the one that could not be repaired.
Try running this script:
```php
<?php

print(md5('local::/home/admin/domains/XXXXXX.pl/public_html/site/owncloud/data/user/'));
```

and replace the path. It should give you a value as output, which will match either "075d4076e5dcab713582709db34b667d" or "17170f52934d7405f147de1f7ec80014".

Then you need to delete either the "home::" entry or the "local::" entry (the one matching the md5) depending on how old the files are.

Did you change the "datadir" in config.php recently ? Did you change it before/after upgrading ?

**Comment by viper1vip** [comment]
Could you explain where to run the script? I mean where to insert the php code?

I did not change anything in config.php

**Comment by PVince81** [comment]
You can run this script from anywhere. It's just for you to convert the long "local::" string to the md5 storage format. When a storage id has more than 64 characters, it will be converted to md5

**Comment by viper1vip** [comment]
Can I ask you for runing this script:
print(md5('local::/home/admin/domains/serwerek.waw.pl/public_html/site/owncloud/data/tenigra/'));

**Comment by viper1vip** [comment]
I recommend http://www.tools4noobs.com/online_php_functions/md5/ for md5 :)

So my 'local::/home/admin/domains/XXXXXX.pl/public_html/site/owncloud/data/user/' matching to 075d4076e5dcab713582709db34b667d so I delate this entries (075d4076e5dcab713582709db34b667d) and the instalation finished.

But now I try to login but when I open login page I have white site  without any login box...

**Comment by abbgrade** [comment]
@PVince81 thanks

After *occ app:disable calendar* the login worked. But then the previous problem appears with the following log entry:

	{"reqId":"55436515f56ab46361561966d20efeaf","remoteAddr":"10.101.1.215","app":"PHP","message":"Class OCA\\Contacts\\Share\\Addressbook contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCP\\Share_Backend::isShareTypeAllowed) at \/var\/www\/owncloud\/apps\/contacts\/lib\/share\/addressbook.php#130","level":3,"time":"2015-03-25T17:15:14+00:00"}

Then i disabled the adressbook via *./occ app:disable contacts*. Now the webapp works without these (unused) apps.

**Comment by viper1vip** [comment]
I just update that also I had to add additional code in .htaccess file because I did not have sychronization between computers.

<Limit GET POST>
order allow,deny
allow from all
</Limit>
<Limit PUT DELETE>
order allow,deny
allow from all
</Limit>

**Comment by tmahring** [comment]
Hi
I'm getting the same error upgrading to 8.0.3 on debian.
However, I checked the database and oc_storage contains NO entries in the form of local::$olddatadir/$user, all entries are in the home:$user form.

All my users (besides admin) are stored in an ldap database, could this be the reason ?

**Comment by PVince81** [comment]
@tmahring can you post the exact error message and owncloud.log entries ?

**Comment by tmahring** [comment]
here is the exact error message:
Could not automatically fix legacy storage "local::/var/www/owncloud/data/c09b7381-4d9011e4-b17192f0-f4f98cac/" => "home::c09b7381-4d9011e4-b17192f0-f4f98cac" because they both have data.

no new messages appear in owncloud.log when i try to run the update, is there maybe a way to set it to more verbose logging ?

**Comment by PVince81** [comment]
There is no way to get more verbose logging.
So you do confirm that your "oc_storages" table contains no entry with "local::/var/www/owncloud/data/c09b7381-4d9011e4-b17192f0-f4f98cac/" nor one with "home::c09b7381-4d9011e4-b17192f0-f4f98cac" ? The error message implies that both entries exist.
Do you have any kind of database caching enabled ?

And re-running the upgrade also didn't help I guess ?

**Comment by tmahring** [comment]
i DO have this entry: "home::c09b7381-4d9011e4-b17192f0-f4f98cac", but not the one with local::... 
Do I need to delete this entry ? I thought the problem was when both entries where in the database, maybe i misunderstood.

**Comment by PVince81** [comment]
No, you're right, it is when both entries are in the database.
Now if you cannot find an entry "local::/var/www/owncloud/data/c09b7381-4d9011e4-b17192f0-f4f98cac/" it is because that id is too long (more than 64 chars), so it will use the md5 of it instead.
Let's convert it: md5("local::/var/www/owncloud/data/c09b7381-4d9011e4-b17192f0-f4f98cac") => "ca535304ac81cab9019419ddf0b060a2".

Try searching for a storage id "ca535304ac81cab9019419ddf0b060a2". That would be the duplicate entry.

At this point you need to check the matching "oc_filecache" entries and decide whether you want to keep either the "local::" one (the md5) or the "home::" one.

**Comment by tmahring** [comment]
Ok, I didn't find ca535304ac81cab9019419ddf0b060a2 but when I run the md5 command on my system it outputs fd0d3df08ccdf869498aae57ff90e028 which i found in oc_storages.
as storage id 17.

so in order to fix it i would now:
1. run an update query to change storage id 17 to 12 in the oc_filecache table (12 is the storage id of the home::... entry)
2. delete fd0d3df08ccdf869498aae57ff90e028 (storage id 17) from oc_storages
3. rerun the upgrade

Is that correct ?

**Comment by PVince81** [comment]
Not exactly. Did you change the "datadir" in config.php recently ? Did you add or remove the trailing slash in that value ? This is usually what causes duplicate entries to appear.

Did you check whether your actual most recent files and shares are in the "home::" entry or in the fd0d3df08ccdf869498aae57ff90e028 entry ? You should only need to delete the one you don't want to use, then re-run the upgrade. It will automatically adjust the id to the new format.

**Comment by tmahring** [comment]
I'm pretty sure I never changed the datadir in config.php (or made any other changes to it).
Could it be that it got changed during an update by the debian package manager ?

I checked oc_filecache and the fd0d3df08ccdf869498aae57ff90e028 storage only contains a few files in files_trashbin, so that should be save to remove.
Should I change the entries in oc_filecache associated with fd0d3df08ccdf869498aae57ff90e028 ? (delete them, change the storage_id...) or just leave them ?

**Comment by PVince81** [comment]
Only delete the entry fd0d3df08ccdf869498aae57ff90e028 in oc_storages and also the matching orphaned oc_filecache entries. Then re-run the upgrade.

**Comment by tmahring** [comment]
Worked like a charm. Thank you very much for your help !
