### ISSUE TITLE
Warning for Bookmarks app in owncloud.log

### ISSUE THREAD

**Issue by StopTrain** [owncloud/core#13996]
"app":"PHP","message":"Undefined index: req_tag at \/srv\/www\/htdocs\/owncloud\/apps\/bookmarks\/templates\/main.php#40","level":3,"time":"2015-02-09T17:40:10+00:00"}

Not that it is a show stopper, but reporting here for the new ownCloud 8.0 release just in case.

**Comment by LukasReschke** [comment]
Can you reopen this at https://github.com/owncloud/bookmarks? – Thanks!

**Comment by StopTrain** [comment]
I certainly can!
