### ISSUE TITLE
[oc6->oc7] DB upgrade failed for a single user 

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#13998]
### Steps to reproduce
1. in ownCloud 6 create a folder and share it with another internal user all users are managed in external LDAP
2. upgrade to ownCloud 7

### Expected behavior
all data should be accessible after upgrade

### Actual behavior
The user does not see the folders that have been shared anymore.
running "occ files:scan" make the files accessible again, but all sharing information are lost.

Note: I have done different reproduction scenarios with public shared folders, public uploads and time-limited shares.
The internal share seems to be the way for the easiest and most reliable reproduction. The problem was occurring 2 times when using the same set of demo-data.

### Server configuration
**Operating system**: UCS 3.2-4

**Web server:** Apache 2.2.16-6.79

**Database:** MySQL

**PHP version:** 5.4.4-14

**ownCloud version:** 7.0.4

**Updated from an older ownCloud or fresh install:**
upgraded from 6.0.6

**List of activated apps:**
- activity
- enterprise_key
- files
- files_sharing
- files_texteditor
- files_trashbin
- files_versions
- firstrunwizard
- user_ldap

**The content of config/config.php:**
```
$CONFIG = array (
'instanceid' => 'xxxxxxxx',
'passwordsalt' => 'removed',
'trusted_domains' =>
array (
0 => 'xxxxxxxxxxx',
1 => '192.168.133.11',
),
'datadirectory' => '/var/lib/owncloud',
'dbtype' => 'mysql',
'version' => '7.0.4.2',
'dbname' => 'owncloud',
'dbhost' => 'localhost',
'dbtableprefix' => 'oc_',
'dbuser' => 'oc_owncloudadmin',
'dbpassword' => 'removed',
'installed' => true,
'license-key' => 'xxxxxxxxxxx',
'ldapIgnoreNamingRules' => false,
'loglevel' => '0',
'appstoreenabled' => false,
'has_internet_connection' => false,
'supportedDatabases' =>
array (
0 => 'mysql',
1 => 'pgsql',
2 => 'oci',
3 => 'mssql',
),
'maintenance' => false,
'secret' => 'removed',
'share_folder' => '/Shared',
'overwritewebroot' => '/owncloud',
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

### Client configuration
**Browser:**
FF and Chromium

**Operating system:**
Linux Mint 17.1

#### Web server error log
nothing related to ownCloud

#### ownCloud log (data/owncloud.log)
```
{"reqId":"54cf6e54a8338","app":"user_ldap","message":"No DN found for
on
m.test3single.it25.de","level":0,"time":"2015-02-02T12:32:20+00:00","method":"GET","url":"\/owncloud\/index.php\/core\/js\/oc.js?v=5a99a2a3eb17097c5fd4b4edf41aaef2"}
{"reqId":"54cf6e5c06935","app":"user_ldap","message":"initializing paged
search for Filter objectClass=* base Array\n(\n [0] =>
uid=test11,cn=users,dc=it25,dc=de\n)\n attr Array\n(\n [0] =>
uid\n)\n limit 1 offset
0","level":0,"time":"2015-02-02T12:32:28+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/list.php?dir=%2F&sort=name&sortdirection=asc"}
{"reqId":"54cf6e5c06935","app":"user_ldap","message":"Ready for a paged
search","level":1,"time":"2015-02-02T12:32:28+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/list.php?dir=%2F&sort=name&sortdirection=asc"}
```

#### Browser log
not applicable

@MorrisJobke 
00002421

**Comment by PVince81** [comment]
Very likely to be the same as: https://github.com/owncloud/core/issues/12801

Any user who were recipients of shares would see their files/shares lost and a bogus "local::" entry created for them. To confirm if this is the same issue, check `oc_storages` and see if there is a new bogus `local::` entry that was created for the affected users.

**Comment by LukasReschke** [comment]
@cdamken Please comment on above statement. THX.

**Comment by DeepDiver1975** [comment]
no feedback -> close

**Comment by cdamken** [comment]
Just a new comment: the behavior does not happens when upgrade from 6.0.7 to 7.0.5, well then its probably fixed.
