### ISSUE TITLE
Not presented with ownCloud 8 update

### ISSUE THREAD

**Issue by josh4trunks** [owncloud/core#13997]
I mistakenly emptied my huge log file thinking I could trigger another update check. Anyone know how I can trigger another update check so I can see what's gong on in my log? Thanks

Currently on version 7.0.4 this is what I get.
![screenshot from 2015-02-09 09 42 52](https://cloud.githubusercontent.com/assets/1018807/6111803/5317c06c-b040-11e4-865d-18e7116571c0.png)

**Comment by abelgomez** [comment]
Moving from ownCloud 7 to ownCloud 8 is not an "update", it's an "upgrade".

The updater app only handles updates for minor versions (http://doc.owncloud.org/server/8.0/admin_manual/maintenance/update.html). Upgrading to a new major release should be done according to the instructions of http://doc.owncloud.org/server/8.0/admin_manual/maintenance/upgrade.html.

**Comment by josh4trunks** [comment]
Thanks I knew I was missing something!

**Comment by karlitschek** [comment]
The upgrade to 8 will be available via the updater app in the next 1-2 days.
Thanks for the patience.

**Comment by josh4trunks** [comment]
@karlitschek 
Hmm.. @abelgomez and the docs indicate I can't perform an upgrade OC7.0.4 > OC8 using the updater app. Do the docs need updating or is there just a misunderstanding?

**Comment by abelgomez** [comment]
I must point out that my reply was based exclusively on what I read on the docs, and not on my experience with ownCloud ;)

**Comment by karlitschek** [comment]
hmm. maybe the docs are wrong. We always offer upgrade vie the updater app. But 1-2 days after the release.

**Comment by josh4trunks** [comment]
Ok sounds like the docs need updating regarding this matter. I'll personally wait for the upgrade to be available through the updater app, confirm it works, then open a bug in owncloud/documentation.

**Comment by josh4trunks** [comment]
I'm still not presented with the update even though the updater app said it just checked? Should I start checking my log or has the OC8 update still yet to be pushed out?
Thanks,

**Comment by karlitschek** [comment]
we will push the update via the updater later. At the moment it looks like we might wait for 8.0.1 because of bugs that need to be fixed first.
