### ISSUE TITLE
After upgrade 7.0.4->8.0 on Ubuntu 14.10: "js file not found: script:js\/chosen\/chosen.jquery.min serverroot:\/var\/www\/owncloud at \/var\/www\/owncloud\/lib\/private\/template\/resourcelocator.php#46"

### ISSUE THREAD

**Issue by pmalek** [owncloud/core#13999]
After upgrading from 7.0.4 to 8.0 (and handling some other package issues :) ) I have encountered this in `/var/www/owncloud/data/owncloud.log` ( I am using oc with `nginx`):

```
{"reqId":"dad96f8819f59df62d0e8e249b42114f","remoteAddr":"xxx.xxx.xxx.xxx","app":"index","message":"Exception: {\"Message\":\"js file not found: script:js\\\/chosen\\\/chosen.jquery.min serverroot:\\\/var\\\/www\\\/owncloud\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/templatelayout.php(155): OC\\\\Template\\\\ResourceLocator->find(Array)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/templatelayout.php(106): OC_TemplateLayout::findJavascriptFiles(Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template.php(118): OC_TemplateLayout->__construct('guest', '')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template\\\/base.php(103): OC_Template->fetchPage()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template.php(197): OC\\\\Template\\\\Base->printPage()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/util.php(827): OC_Template::printGuestPage('', 'login', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(866): OC_Util::displayLoginPage(Array, Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(821): OC::handleLogin()\\n#8 \\\/var\\\/www\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template\\\/resourcelocator.php\",\"Line\":46}","level":4,"time":"2015-02-09T18:17:17+00:00"}                                                                                  
{"reqId":"dad96f8819f59df62d0e8e249b42114f","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"js file not found: script:js\/chosen\/chosen.jquery.min serverroot:\/var\/www\/owncloud at \/var\/www\/owncloud\/lib\/private\/template\/resourcelocator.php#46","level":3,"time":"2015-02-09T18:17:17+00:00"}
```

My oc versions:

```
dpkg -l | grep owncloud 
ii  owncloud                            8.0.0-2                             all          ownCloud Server - Private file sync and share server
ii  owncloud-3rdparty                   8.0.0-2                             amd64        The ownCloud app owncloud-3rdparty
ii  owncloud-app-activity               8.0.0-2                             amd64        The ownCloud app owncloud-app-activity
ii  owncloud-app-external               8.0.0-2                             amd64        The ownCloud app owncloud-app-external
ii  owncloud-app-files                  8.0.0-2                             amd64        The ownCloud app owncloud-app-files
ii  owncloud-app-files-encryption       8.0.0-2                             amd64        The ownCloud app owncloud-app-files-encryption
ii  owncloud-app-files-external         8.0.0-2                             amd64        The ownCloud app owncloud-app-files-external
ii  owncloud-app-files-locking          8.0.0-2                             amd64        The ownCloud app owncloud-app-files-locking
ii  owncloud-app-files-pdfviewer        8.0.0-2                             amd64        The ownCloud app owncloud-app-files-pdfviewer
ii  owncloud-app-files-sharing          8.0.0-2                             amd64        The ownCloud app owncloud-app-files-sharing
ii  owncloud-app-files-texteditor       8.0.0-2                             amd64        The ownCloud app owncloud-app-files-texteditor
ii  owncloud-app-files-trashbin         8.0.0-2                             amd64        The ownCloud app owncloud-app-files-trashbin
ii  owncloud-app-files-versions         8.0.0-2                             amd64        The ownCloud app owncloud-app-files-versions
ii  owncloud-app-files-videoviewer      8.0.0-2                             amd64        The ownCloud app owncloud-app-files-videoviewer
ii  owncloud-app-firstrunwizard         8.0.0-2                             amd64        The ownCloud app owncloud-app-firstrunwizard
ii  owncloud-app-gallery                8.0.0-2                             amd64        The ownCloud app owncloud-app-gallery
ii  owncloud-app-provisioning-api       8.0.0-2                             amd64        The ownCloud app owncloud-app-provisioning-api
ii  owncloud-app-templateeditor         8.0.0-2                             amd64        The ownCloud app owncloud-app-templateeditor
ii  owncloud-app-updater                8.0.0-2                             amd64        The ownCloud app owncloud-app-updater
ii  owncloud-app-user-external          8.0.0-2                             amd64        The ownCloud app owncloud-app-user-external
ii  owncloud-app-user-ldap              8.0.0-2                             amd64        The ownCloud app owncloud-app-user-ldap
ii  owncloud-app-user-webdavauth        8.0.0-2                             amd64        The ownCloud app owncloud-app-user-webdavauth
ii  owncloud-config-apache              8.0.0-2                             amd64        The ownCloud app owncloud-config-apache
ii  owncloud-server                     8.0.0-2                             amd64        The owncloud-server package
```

**Comment by RealRancor** [comment]
Hi,

have you disabled all 3rdparty apps as noted in the upgrade instructions?

**Comment by pmalek** [comment]
I didn't have any AFAIR

**Comment by MiCRoPhoBIC** [comment]
I have exactly the same issue, but on Debian. Upgrading 7.0.4->8.0, I also had to do some magic (force overwrite apache.conf) with the packages, but I'm stuck at the same error. I have one 3dparty package and forgot to disable it. How can I do it now manually (without the interface)?

**Comment by pmalek** [comment]
Ok I got :)  You have to launch `occ` to list your apps and locate the 3rd party app, e.g. 

```
sudo -u www-data php occ app:list 
```

My 3rd party app was `files_mv`. Then you can disable it by:

```
sudo -u www-data php occ app:disable files_mv 
```

Then after restart of web server and (it you have it enabled) disabling maintenance mode you should have it running :)

```
sudo -u www-data php occ maintenance:mode --off
```

(note: all those commands are ran from `/var/www/owncloud/` so that `occ` is in the current dir - I do not know how to run those commands/modules/etc. in php from other dirs)

**Comment by MiCRoPhoBIC** [comment]
Lol two different solutions in a seconds ;-)

**Comment by eggithub** [comment]
Hi,

Same kind of issue. Updated from 7.0.4 to 8.0. Login screen of ownCloud not showing up after update. Also did forget to disable 3rd-party apps before update but did afterwards with occ, without succes.

owncloud.log:

{"reqId":"ba1a264ad65e9625026f7dcdbfea57a8","remoteAddr":"xxx.xxx.xxx.xxx","app":"index","message":"Exception: {\"Message\":\"js file not found: script:miniColors\\\/l10n\\\/en serverroot:\\\/var\\\/www\\\/owncloud\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/templatelayout.php(155): OC\\\\Template\\\\ResourceLocator->find(Array)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/templatelayout.php(106): OC_TemplateLayout::findJavascriptFiles(Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template.php(118): OC_TemplateLayout->__construct('guest', '')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template\\\/base.php(103): OC_Template->fetchPage()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template.php(197): OC\\\\Template\\\\Base->printPage()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/util.php(827): OC_Template::printGuestPage('', 'login', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(866): OC_Util::displayLoginPage(Array, Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(821): OC::handleLogin()\\n#8 \\\/var\\\/www\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template\\\/resourcelocator.php\",\"Line\":46}","level":4,"time":"2015-02-09T19:21:41+01:00","method":"GET","url":"\/owncloud\/"}
{"reqId":"ba1a264ad65e9625026f7dcdbfea57a8","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"js file not found: script:miniColors\/l10n\/en serverroot:\/var\/www\/owncloud at \/var\/www\/owncloud\/lib\/private\/template\/resourcelocator.php#46","level":3,"time":"2015-02-09T19:21:41+01:00","method":"GET","url":"\/owncloud\/"}

System:
Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u1 x86_64 GNU/Linux
PHP 5.4.36-0+deb7u3 (cli) (built: Jan  9 2015 08:07:06)
Server version: Apache/2.2.22 (Debian)

sudo -u www-data php occ app:list
Enabled:
 - activity
 - admin_dependencies_chk
 - appframework
 - bookmarks
 - calendar
 - contacts
 - documents
 - external
 - files
 - files_external
 - files_pdfviewer
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - files_videoviewer
 - gallery
 - updater
Disabled:
 - files_encryption
 - files_locking
 - files_mv
 - firstrunwizard
 - journal
 - news
 - notes
 - provisioning_api
 - search_lucene
 - tal
 - tasks
 - templateeditor
 - user_external
 - user_ldap
 - user_webdavauth

Also have have a dropbox account mounted in owncloud

Also did a maintenance:repair action without succes.

**Comment by eggithub** [comment]
Why is this closed? :-) Still having this issue.

tried a maintenance disable and restart webserver but no luck.

greetz

**Comment by pmalek** [comment]
Did you try my full solution with disabling 3rd party apps ?

**Comment by eggithub** [comment]
Yep, or could you check my list above. maybe I missed out on one.

**Comment by RealRancor** [comment]
@eggithub 
Have you done a full upgrade with deleting all files except /config/* and /data* ?

**Comment by eggithub** [comment]
D'OH! I guess I forgot to do that, instead dealt with it as an "within main version" update. Is it safe to delete all other files and do a "cp -r owncloud" again? I feel so dumb :-)

**Comment by eggithub** [comment]
@RealRancor 

Thanx, for now I deleted all but config and data  dirs, and re-copied the owncloud dir from the install file. This seems to work for now.

cheerz!

**Comment by RealRancor** [comment]
Hi,

it is "not saver" but a "must have":

http://doc.owncloud.org/server/8.0/admin_manual/maintenance/upgrade.html

**Comment by cweiske** [comment]
For me it was calendar that caused the error.

**Comment by psych0d0g** [comment]
same for me, lastest upgrade from 7.0.3 to 8.0.2 calendar AND contacts broke owncloud...

**Comment by wenzul** [comment]
same for me. to solve it I disabled calendar with

```
sudo -u www-data /var/www/owncloud/occ app:disable calendar
```

**Comment by Distopico** [comment]
The same error with calendar and contacts apps

**Comment by RealRancor** [comment]
@Distopico Exactly as described above where you can find possible workarounds.
