### ISSUE TITLE
Upgrade from 7.04 to 8.0rc2 failes

### ISSUE THREAD

**Issue by Tribalize** [owncloud/core#13990]
tried to test locally the upgrade from 7.04 to 8.0 rc2 fails with error Fatal error: Class 'Pimple\Container' not found in C:\xampp\htdocs\owncloud\lib\private\appframework\utility\simplecontainer.php on line 32

Also tried to test locally fresh install of 8.0rc2 and it fails with error Fatal error: Call to a member function getSession() on null in C:\xampp\htdocs\owncloud8\lib\private\template.php on line 53

### Steps to reproduce
1. running copy of 7.04
2. overwrite with 8.0rc2  files

### Expected behaviour
Expected to see upgrade screen at login page

### Actual behaviour
see error no page at all

### Server configuration
**Operating system**:
xampp 5.6.3 for local testing
**Web server:**

**Database:**
mysql
**PHP version:**
PHP Version 5.6.3

**ownCloud version:** (see ownCloud admin page)
7.04
**Updated from an older ownCloud or fresh install:**
fresh install
**List of activated apps:**
Activity
Calendar
Contacts
Deleted files
Documents
First Run Wizard
Full Text Search
Mail Template Editor
PDF Viewer
Pictures
Share Files
Text Editor
Updater
Versions
Video Viewer
**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password, passwordsalt and secret)
<?php
$CONFIG = array (
  'instanceid' => 'oc91364f1974',
  'passwordsalt' => 'dec07e17ba1dc58928aa0decdf3728',
  'trusted_domains' => 
  array (
    0 => 'localhost',
  ),
  'datadirectory' => 'C:\\xampp\\htdocs\\owncloud\\data',
  'overwrite.cli.url' => 'http://localhost/owncloud',
  'dbtype' => 'mysql',
  'version' => '7.0.4.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin',
  'dbpassword' => '163ad96ff028e189cd3349bdd1b0fc',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'secret' => '4c523c8095633e1c7c5fac52f63cdf474a91ee3f5df5590145a37c5ea552a9d27d230a8a0f6f94716b087d1dfec61a5b',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
### Client configuration
**Browser:**
chrome, FF, IE
**Operating system:**
windows 7 64
### Logs
#### Web server error log
apache error log
[Mon Feb 09 10:05:04.410030 2015] [ssl:warn] [pid 5504:tid 256] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Feb 09 10:05:04.500030 2015] [core:warn] [pid 5504:tid 256] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Mon Feb 09 10:05:04.670030 2015] [ssl:warn] [pid 5504:tid 256] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Feb 09 10:05:09.083037 2015] [mpm_winnt:notice] [pid 5504:tid 256] AH00455: Apache/2.4.10 (Win32) OpenSSL/1.0.1i PHP/5.6.3 configured -- resuming normal operations
[Mon Feb 09 10:05:09.083037 2015] [mpm_winnt:notice] [pid 5504:tid 256] AH00456: Apache Lounge VC11 Server built: Jul 17 2014 11:50:08
[Mon Feb 09 10:05:09.083037 2015] [core:notice] [pid 5504:tid 256] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Mon Feb 09 10:05:09.103037 2015] [mpm_winnt:notice] [pid 5504:tid 256] AH00418: Parent: Created child process 5396
[Mon Feb 09 10:05:09.623037 2015] [ssl:warn] [pid 5396:tid 268] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Feb 09 10:05:09.823038 2015] [ssl:warn] [pid 5396:tid 268] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Feb 09 10:05:09.853038 2015] [mpm_winnt:notice] [pid 5396:tid 268] AH00354: Child: Starting 150 worker threads.

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
log is old doesnt show anything new

{"app":"PHP","message":"touch(): Unable to create file C:\/xampp\/htdocs\/owncloud\/data\/owncloud.log because No such file or directory at C:\\xampp\\htdocs\\owncloud\\lib\\private\\log\\owncloud.php#49","level":3,"time":"2014-12-05T16:23:03+00:00"}
{"app":"PHP","message":"filemtime(): stat failed for C:\\xampp\\htdocs\\owncloud\\data\/admin\/5481dc0f4fd76 at C:\\xampp\\htdocs\\owncloud\\lib\\private\\files\\storage\\mappedlocal.php#155","level":3,"time":"2014-12-05T16:23:43+00:00"}
{"app":"PHP","message":"filemtime(): stat failed for C:\\xampp\\htdocs\\owncloud\\data\/admin\/5481dc0f4fd76 at C:\\xampp\\htdocs\\owncloud\\lib\\private\\files\\storage\\mappedlocal.php#155","level":3,"time":"2014-12-05T16:23:43+00:00"}
{"app":"core","message":"Unable to parse OCS content for app 166038","level":4,"time":"2015-02-09T15:38:17+00:00"}
{"app":"core","message":"Unable to parse OCS content for app 166043","level":4,"time":"2015-02-09T15:38:18+00:00"}
{"app":"core","message":"Unable to parse OCS content for app 166044","level":4,"time":"2015-02-09T15:38:18+00:00"}
{"app":"core","message":"Unable to parse OCS content for app 166045","level":4,"time":"2015-02-09T15:38:18+00:00"}
{"app":"core","message":"Unable to parse OCS content for app 166049","level":4,"time":"2015-02-09T15:38:19+00:00"}
{"app":"core","message":"Unable to parse OCS content for app 166050","level":4,"time":"2015-02-09T15:38:19+00:00"}
{"app":"core","message":"Unable to parse OCS content for app 166051","level":4,"time":"2015-02-09T15:38:20+00:00"}
{"app":"core","message":"Unable to parse OCS content for app 166052","level":4,"time":"2015-02-09T15:38:20+00:00"}
{"app":"core","message":"Unable to parse OCS content for app 166053","level":4,"time":"2015-02-09T15:38:21+00:00"}
{"app":"core","message":"Unable to parse OCS content for app 166054","level":4,"time":"2015-02-09T15:38:21+00:00"}
{"app":"core","message":"Unable to parse OCS content for app 166055","level":4,"time":"2015-02-09T15:38:21+00:00"}
{"app":"core","message":"Unable to parse OCS content for app 166056","level":4,"time":"2015-02-09T15:38:22+00:00"}
{"app":"core","message":"Unable to parse OCS content for app 166057","level":4,"time":"2015-02-09T15:38:22+00:00"}
{"app":"core","message":"Unable to parse OCS content for app 166059","level":4,"time":"2015-02-09T15:38:23+00:00"}
{"app":"core","message":"Unable to parse OCS content for app 166038","level":4,"time":"2015-02-09T15:38:24+00:00"}
{"app":"core","message":"Unable to parse OCS content for app 166043","level":4,"time":"2015-02-09T15:38:24+00:00"}
{"app":"core","message":"Unable to parse OCS content for app 166044","level":4,"time":"2015-02-09T15:38:25+00:00"}
{"app":"core","message":"Unable to parse OCS content for app 166045","level":4,"time":"2015-02-09T15:38:25+00:00"}
{"app":"core","message":"Unable to parse OCS content for app 166049","level":4,"time":"2015-02-09T15:38:26+00:00"}
{"app":"core","message":"Unable to parse OCS content for app 166050","level":4,"time":"2015-02-09T15:38:26+00:00"}
{"app":"core","message":"Unable to parse OCS content for app 166051","level":4,"time":"2015-02-09T15:38:26+00:00"}
{"app":"core","message":"Unable to parse OCS content for app 166052","level":4,"time":"2015-02-09T15:38:27+00:00"}
{"app":"core","message":"Unable to parse OCS content for app 166053","level":4,"time":"2015-02-09T15:38:27+00:00"}
{"app":"core","message":"Unable to parse OCS content for app 166054","level":4,"time":"2015-02-09T15:38:28+00:00"}
{"app":"core","message":"Unable to parse OCS content for app 166055","level":4,"time":"2015-02-09T15:38:28+00:00"}
{"app":"core","message":"Unable to parse OCS content for app 166056","level":4,"time":"2015-02-09T15:38:28+00:00"}
{"app":"core","message":"Unable to parse OCS content for app 166057","level":4,"time":"2015-02-09T15:38:29+00:00"}
{"app":"core","message":"Unable to parse OCS content for app 166059","level":4,"time":"2015-02-09T15:38:29+00:00"}

**Comment by LukasReschke** [comment]
Did you upgrade as described in our documentation? http://doc.owncloud.org/server/8.0/admin_manual/maintenance/upgrade.html

Did you remove all applications before etc?

**Comment by Tribalize** [comment]
Yes the upgrade was done according to upgrade manual. apache was stopped, no 3rd party apps, apache restarted.

The fresh install of 8.0 rc2 was done the same as a 7.0 install.

**Comment by LukasReschke** [comment]
No 3rdparty apps or no apps at all as pointed out in the upgrade app? i.e. is there still an /apps/ which contains /calendar/ and /contacts/ and so on? – If so delete everything in it and just upload the new release over it.

**Comment by Tribalize** [comment]
Just deleted all under apps. turned off apache. config maintenance' => true. restarted apache. still throwing same error for the upgrade. Anything else I can try?

**Comment by DeepDiver1975** [comment]
> Also tried to test locally fresh install of 8.0rc2 and it fails with error Fatal error: Call to a member function getSession() on null in C:\xampp\htdocs\owncloud8\lib\private\template.php on line 53

this is fixed with #13809

**Comment by DeepDiver1975** [comment]
@Tribalize these errors do show up in case the 3rdparty folder/repo is not available/updated. Please double check your setup - THX

**Comment by DeepDiver1975** [comment]
any - updating to the final release might be a good idea as well :wink:

**Comment by Tribalize** [comment]
have done the upgrade from 7.04 to 8.0.0.7. and a fresh install of 8.0.0.7. which is the version you get when downloading from the main page.

first the upgrade. When setting 'maintenance' => true, before trying to upgrade. The upgrade will not begin and states on the main page that an update is is progress. Changing this back to false, The upgrade goes fine. 
the fresh install went fine also.

mind you these are test setups on local server. 
But on both instances if you go to apps , recommended the page is blank. the other links work fine. 
This is just FYI. Thanks for the hard work.

**Comment by PVince81** [comment]
Sorry, Windows env won't be supported any more starting with 8.1: https://owncloud.org/blog/owncloud-server-8-1-will-not-support-windows-as-server-platform-natively/

You might want to try again in a Linux VM with a more recent version like 8.0.6 or 8.1.1.
