### ISSUE TITLE
appcodechecker running regardless of config file

### ISSUE THREAD

**Issue by clarjon1** [owncloud/core#14001]
Hello,

The appcode checker snippet of code is running regardless of whether the config.php has it set to true OR false.

This is preventing me from installing apps from the app installer.

I have set it to both true and false in the config ( It had been false during an upgrade from OC7), and both prevent the app installation. I can make a workaround at the moment by editing lib/private/installer.php and changing "grep" on line 561 to another word, like "grap" for example, to disable the check. However, this is not a longterm solution.

http://i.imgur.com/qUHLr3v.png shows the app installer behaviour with   'appcodechecker' => 'true',  in the config file.
http://privatepaste.com/bd98442668  is example code of how i disabled the bug, allowing for app installation to happen again.

Please let me know if you need further information from me.

**Comment by karlitschek** [comment]
@DeepDiver1975

**Comment by DeepDiver1975** [comment]
@clarjon1 
Can I ask you for a dump of ALL config files?
do you have any kind of php ops code cache in place? (apc(u), xcache ...)

THX

**Comment by clarjon1** [comment]
config/config.php:
```` php
<?php
$CONFIG = array (
  'instanceid' => '[REMOVED]',
  'passwordsalt' => '[REMOVED]',
  'secret' => '[REMOVED]',
  'trusted_domains' => 
  array (
    0 => 'cloud.xfcab.com',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://cloud.xfcab.com/',
  'dbtype' => 'mysql',
  'version' => '8.0.0.7',
  'installed' => true,
  'forcessl' => true,
  'maintenance' => false,
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbuser' => '[REMOVED]',
  'dbpassword' => '[REMOVED]',
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'info',
  'mail_domain' => 'xfcab.com',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'smtp.gmail.com',
  'mail_smtpport' => '587',
  'mail_smtpname' => '[REMOVED]',
  'mail_smtppassword' => '[REMOVED]',
  'mail_smtpsecure' => 'tls',
  'mail_smtpauthtype' => 'PLAIN',
  'appcodechecker' => 'false',
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\Image',
    1 => 'OC\\Preview\\MP3',
    2 => 'OC\\Preview\\TXT',
    3 => 'OC\\Preview\\MarkDown',
    4 => 'OC\\Preview\\Epub',
    5 => 'OC\\Preview\\PDF',
  ),
  'theme' => '',
);
````

I am not using any caching on this server.  Please let me know if there are other config files, this is the only one I have worked with thus far with ownCloud.

**Comment by DeepDiver1975** [comment]
> 'appcodechecker' => 'false',

please try with

'appcodechecker' => false

an alternative you can simple remove this line

**Comment by clarjon1** [comment]
Removing the line fixed the problem. Thank you.
