### ISSUE TITLE
Personal Setting not catching the customize CSS

### ISSUE THREAD

**Issue by godambrosio** [owncloud/core#14002]
I have set one customized theme in my instance of owncloud.
All is working good but when I go to Personal Settings, the header is catched from core directory and not from my customized folder into Theme.

**Comment by DeepDiver1975** [comment]
@godambrosio Thanks a lot for reporting issues back to us!

We need some more information to properly support you with your issue!

Can I ask you to follow our guidelines for submitting bugs as described here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

Thanks a lot!

**Comment by godambrosio** [comment]
### Steps to reproduce
1.Go to "Personal" option within the left-top corner menu
2. Do an insepct element (option of the browser) in the Header
3. You can se that CSS file who is giving the style to the header
(header.css) is in core and not in themes/customTheme

### Expected behaviour
The CSS file (header.css) is catched from themes/customTheme and not
from core directory

### Actual behaviour
The header.css is catched from the core directory

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS
**Web server:**
Apache 2.4.7
**Database:**
MySql 14.14
**PHP version:**
Php 5.5.9
**ownCloud version:** (see ownCloud admin page)
8.0
**Updated from an older ownCloud or fresh install:**
Yes updated from 7.4
**List of activated apps:**
Files,Document, Activity
**The content of config/config.php:**
  $CONFIG = array (
  'instanceid' => 'oc2219ae15c9',
  'passwordsalt' => '',
  'trusted_domains' =>
  array (
    0 => 'localhost',
  ),
  'datadirectory' => '/var/www/html/sgat/data',
  'dbtype' => 'mysql',
  'version' => '8.0.0.7',
  'dbname' => 'owncloudDesarrollo',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_gustavo',
  'dbpassword' => '',
  'installed' => true,
  'theme' => 'Edesa',
  'loglevel' => '0',
  'appcodechecker' => false,
  'maintenance' => false,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'gdambrosio',
  'mail_domain' => 'edesa.com.ar',
  'mail_smtphost' => '',
  'mail_smtpport' => '',
  'mail_smtpdebug' => true,
  'mail_smtpname' => 'lucas',
  'mail_smtppassword' => '',
  'secret' => '',
  'overwrite.cli.url' => 'http://localhost/sgat',
Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
no
### Client configuration
**Browser:**
Firefox 35.0.1
**Operating system:**
Ubuntu 14.01 LTS
### Logs
#### Web server error log
```
Insert your webserver log here
```
Not relevant because is not logges as an error
#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

Not relevant because this event is not logged


2015-02-09 17:48 GMT-03:00 Thomas Müller <notifications@github.com>:

> @godambrosio <https://github.com/godambrosio> Thanks a lot for reporting
> issues back to us!
>
> We need some more information to properly support you with your issue!
>
> Can I ask you to follow our guidelines for submitting bugs as described
> here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md
>
> Thanks a lot!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/core/issues/14002#issuecomment-73586956>.
>

**Comment by DeepDiver1975** [comment]
@jancborchardt can I ask you to have a look please? THX

**Comment by godambrosio** [comment]
Sorry I'm very ashamed, it's a typing error for my part when I created the
custom CSS, very sorry.
Anyway thanks for your time

2015-02-10 12:31 GMT-03:00 Thomas Müller <notifications@github.com>:

**Comment by jancborchardt** [comment]
@godambrosio no worries! Happy it works now. :)
