### ISSUE TITLE
App installer does not reflect installed apps.

### ISSUE THREAD

**Issue by clarjon1** [owncloud/core#14004]
Hello,

In my Owncloud 8 instance, I have discovered that after a page refresh, the app installation interface does not "remember" which apps are installed, allowing me to attempt to install an already installed app, and failing to do so.

In the below example, I have installed Contacts and Calendar 8.0 via the installation interface, then tested them, then came back to the admin page to check for further apps to install, and I found that I was being prompted to install the packages again. When I clicked the "Enable" button, it sat there for about 20-30 seconds, before providing an error, "App Directory Already Exists".

http://i.imgur.com/26y2ytV.png   Here is a screenshot of this, with the owncloud menu opened to show that the apps are indeed already installed, as well as the error message mentioned above.

http://i.imgur.com/9vGeEF0.png  And here is a screenshot of the apps installed in the "Enabled" section of the app interface, to show that they are indeed installed.

**Comment by DeepDiver1975** [comment]
That's kind of ... stupid - agreed - we shall fix this for 8.0.1
