### ISSUE TITLE
OwnCloud on Ubuntu ARM

### ISSUE THREAD

**Issue by sideeffffect** [owncloud/core#14000]
Ubuntu package on OBS have architecture set as `x86_64`, but it should be `all`.
Currently it impossible to install them on ARM computer, although OwnCloud works on ARM too

https://build.opensuse.org/package/repositories/isv:ownCloud:community/owncloud

https://build.opensuse.org/package/binaries/isv:ownCloud:community/owncloud?repository=xUbuntu_14.04

**Comment by karlitschek** [comment]
@jnweiger

**Comment by jnweiger** [comment]
Archutecture: all 
is already scheduled for next rebuild. 8.0.0-3 will have that in an hour or so.
Waiting for mirrors to push 8.0.0-2

**Comment by sideeffffect** [comment]
oh that's very good news. thank you!

**Comment by logomancer** [comment]
This problem also existed on my i686 Ubuntu machine. Glad it's getting fixed.

**Comment by sideeffffect** [comment]
but why is it separated into various architectures anyway? isn't it all just PHP and thus `all`?

**Comment by DeepDiver1975** [comment]
architecture all has been added - see

https://build.opensuse.org/package/view_file/isv:ownCloud:community:8.0/owncloud/debian.changelog?expand=1

````
owncloud (8.0.0-3) stable; urgency=low

  * Architecture: any is actually amd64+i686, switching to 
    Architecture: all

 -- Jürgen Weigert <jw@owncloud.com>  Mon, 09 Feb 2015 20:04:58 +0100

**Comment by jnweiger** [comment]
fixed. 8.0.0-5 is the latest build.
