### ISSUE TITLE
no data folder during installation

### ISSUE THREAD

**Issue by Valsimot** [owncloud/core#14014]
I'm on Ubuntu 1404, with marginal knowhow about Linux and new to Owncloud. I followed https://owncloud.org/install/ and dl the .tar.bz2, checked the md5 hash, extracted and copied it to /var/www/ and opened http://localhost/owncloud

I created the DB following this http://doc.owncloud.org/server/8.0/admin_manual/configuration/database_configuration.html

The wizard wouldn't open though, the php file had no write access. I used the script at
http://doc.owncloud.org/server/8.0/admin_manual/installation/installation_wizard.html
to set the rights as neccessary, but I got an error: chown data, chown data/.htaccess and chmod data/.htaccess: file or folder not found
user frikinz IRC was helpful, I created the data folder manually as well as the .htaccess fil, ran the script as sudo again and it worked. 
Shouldn't the data folder be part of the package?

**Comment by MorrisJobke** [comment]
cc @jnweiger

**Comment by hedii** [comment]
I have the same issue, no data folder when installing manually on ubuntu 14.04 LTS

**Comment by PVince81** [comment]
Should be solved in recent tarballs.

If you're still having this issue with recent tarballs, like 8.2.2, feel free to reopen.
