### ISSUE TITLE
Cannot login after upgrading to OC 8.0

### ISSUE THREAD

**Issue by mikew** [owncloud/core#14013]
My upgrade method was pretty clean:

```bash
su owncloud
cd ~/
mv owncloud owncloud~
tar jxf owncloud-8.0.0.tar.bz2
cp owncloud~/config/config.php owncloud/config/
cd owncloud/
./occ upgrade
```

Upgrade script didn't complain about anything, however when I try to log in the button never becomes enabled, and there's plenty of 404s in the console:

![screen shot 2015-02-09 at 6 22 11 pm](https://cloud.githubusercontent.com/assets/4729/6117148/04b09b6c-b089-11e4-8af3-4cd0e63a2300.png)

Also after upgrading, trying to run `./occ app:list` would complain about Redis, which is odd, because there was no mention of Redis anywhere and it wasn't ever an issue with OC 7.0.

Here is the output of `./occ app:list`:

```
Enabled:
 - files
 - files_external
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - files_videoviewer
 - firstrunwizard
 - updater
 - user_ldap
Disabled:
 - activity
 - external
 - files_encryption
 - files_locking
 - files_pdfviewer
 - gallery
 - provisioning_api
 - templateeditor
 - user_external
 - user_webdavauth
```

**Comment by mikew** [comment]
It's not like the files are missing either:

```bash
owncloud@owncloud:~/owncloud$ ls -lh core/vendor/jquery/jquery.min.js core/vendor/jquery/jquery-migrate.min.js
-rw-r--r-- 1 owncloud owncloud 7.0K Feb  7 02:31 core/vendor/jquery/jquery-migrate.min.js
-rw-r--r-- 1 owncloud owncloud  91K Feb  7 02:31 core/vendor/jquery/jquery.min.js
owncloud@owncloud:~/owncloud$
```

**Comment by karlitschek** [comment]
@schiesbn @DeepDiver1975 any idea?

**Comment by DeepDiver1975** [comment]
What's in the web server logs? Thx

**Comment by mikew** [comment]
Sorry for the delay

[Here is the nginx log](https://gist.github.com/mikew/999950aed2d0af7008b4#file-00-error_log-log)

For good measure, I've also copied the [nginx server conf](https://gist.github.com/mikew/999950aed2d0af7008b4#file-owncloud-nginx-conf) and the [php5-fpm ini](https://gist.github.com/mikew/999950aed2d0af7008b4#file-owncloud-php5-fpm-ini)

I should mention that owncloud runs on one machine and nginx runs on another, but this works fine for OC 7 (in fact just reverting to my `owncloud~` backup folder worked)

**Comment by mikew** [comment]
> owncloud runs on one machine and nginx runs on another

and that's the ticket. the machine that hosts nginx also has a copy of owncloud that needed to be updated to serve the static files. my bad.
