### ISSUE TITLE
Upgrading to v8 on Debian 7 results in error.

### ISSUE THREAD

**Issue by thetechstewart** [owncloud/core#14010]
I'm running into some issues upgrading on Debian 7.  The owncloud-config-apache package doesn't seem to want to install.  I get the following from dpkg if I try to manually install it.

Unpacking owncloud-config-apache (from owncloud-config-apache_8.0.0-1_amd64.deb) ...
dpkg: error processing owncloud-config-apache_8.0.0-1_amd64.deb (--install):
 trying to overwrite '/etc/apache2/conf-available/owncloud.conf', which is also in package owncloud 8.0.0-1
Errors were encountered while processing:
 owncloud-config-apache_8.0.0-1_amd64.deb

I've checked permissions on the conf-available dir and it's writeable by root, I also moved the old file out of the way to try and resolve this issue with no changes.  Running sudo apt-get -o Dpkg::Options::="--force-overwrite" -f install fixed the issue in the end, but the install process has some hiccups on Debian 7.

**Comment by DeepDiver1975** [comment]
> owncloud-config-apache_8.0.0-1_amd64.deb

this is afaik not the latest version of the package ....

**Comment by DeepDiver1975** [comment]
we are at -4 meanwhile - see https://build.opensuse.org/package/view_file/isv:ownCloud:community:8.0/owncloud/debian.changelog?expand=1

**Comment by DeepDiver1975** [comment]
Please install 8.0.0-4 once available on PBS - feel free to reopen in case the error persists - THX
