### ISSUE TITLE
ownCloud PDF Viewer in Favorites

### ISSUE THREAD

**Issue by igraf** [owncloud/core#14024]
ownCloud 8 Final

Hi
I have problems with pdf view in favorites. when open a pdf, the folder structure is displayed. Failure detected in several browsers.

Examples
https://drive.google.com/file/d/0B_JBqvP4UUXkSTJPSjBnRnBYRG8/view?usp=sharing
https://drive.google.com/file/d/0B_JBqvP4UUXkV0NaRWJ1VU5SbGs/view?usp=sharing

best regards

**Comment by DeepDiver1975** [comment]
Please reopen in https://github.com/owncloud/files_pdfviewer

Thanks a lot.
