### ISSUE TITLE
No error message is thrown after setting a random key with the occ ldap:set-config command

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#14027]
### Steps to reproduce
1. Create a valid ldap configuration with the ldap wizard (for example)
2. From the command line, try to set a non-existent config key in the ldap configuration (`./occ ldap:set-config '' randomkey randomvalue` or something similar). The config key must be valid.
### Expected behaviour

An error message is thrown (adding the new key doesn't make sense)
### Actual behaviour

Nothing happens. No error is thrown but the key isn't added
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** sqlite3

**PHP version:** 5.5.9

**ownCloud version:** ownCloud 7.0.5 RC1 (testing) 

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by PVince81** [comment]
Please reopen in the [user_ldap app repo](https://github.com/owncloud/user_ldap) if the issue persists with 10.0.4 and the latest version of the user_ldap app from the marketplace.
