### ISSUE TITLE
After upgrading from 7.0.4 to 8.0.0 empty page for owncloud web interface

### ISSUE THREAD

**Issue by tps800** [owncloud/core#14020]
Since we had this upgrading from 6.0.6 to 7.0.0 I'd assume a regression :-(

**Comment by nroach44** [comment]
I just had this an I deleted everything except config/ and data/ and recopied the new version and it works.

**Comment by karlitschek** [comment]
This is actually the documented way to upgrade. @tps800 Can you confirm that it works if you do that?

**Comment by tps800** [comment]
This is really a problem here. Using packages to upgrade upgrades I assume not having to read update instructions I am assuming all going magically without user intervention.
After installing the packages the only chance is to click the presented button to upgrade on your own cloud instance website. You do not have access to disable 3rd-party apps. You do not even have the possibility to keep the version -- you'll have to click "Upgrade". No other chance.

**Comment by tps800** [comment]
I did not need to remove all files. Only two 3rd-Party apps where to remove: files_tree and files_mv. Both do not work any more with OC 8. Hopefully these get ported, as they ease moving files around with the web interface.
