### ISSUE TITLE
OC update CentOS6 7->8 fails during missing dependency's. 

### ISSUE THREAD

**Issue by tuxmaster** [owncloud/core#14025]
Hello,
when using the OC repo for CentOS6 then yum update fails with:
esolving Dependencies
--> Running transaction check
---> Package owncloud.noarch 0:7.0.4-17.1 will be obsoleted
---> Package owncloud-3rdparty.noarch 0:7.0.4-17.1 will be updated
---> Package owncloud-3rdparty.noarch 0:8.0.0-19.1 will be obsoleting
---> Package owncloud-app-activity.noarch 0:8.0.0-19.1 will be obsoleting
--> Processing Dependency: owncloud-server-core = 8.0.0 for package: owncloud-app-activity-8.0.0-19.1.noarch
---> Package owncloud-app-external.noarch 0:8.0.0-19.1 will be obsoleting
---> Package owncloud-app-files.noarch 0:8.0.0-19.1 will be obsoleting
---> Package owncloud-app-files_encryption.noarch 0:8.0.0-19.1 will be obsoleting
---> Package owncloud-app-files_external.noarch 0:8.0.0-19.1 will be obsoleting
---> Package owncloud-app-files_locking.noarch 0:8.0.0-19.1 will be obsoleting
---> Package owncloud-app-files_pdfviewer.noarch 0:8.0.0-19.1 will be obsoleting
---> Package owncloud-app-files_sharing.noarch 0:8.0.0-19.1 will be obsoleting
---> Package owncloud-app-files_texteditor.noarch 0:8.0.0-19.1 will be obsoleting
---> Package owncloud-app-files_trashbin.noarch 0:8.0.0-19.1 will be obsoleting
---> Package owncloud-app-files_versions.noarch 0:8.0.0-19.1 will be obsoleting
---> Package owncloud-app-files_videoviewer.noarch 0:8.0.0-19.1 will be obsoleting
---> Package owncloud-app-firstrunwizard.noarch 0:8.0.0-19.1 will be obsoleting
---> Package owncloud-app-gallery.noarch 0:8.0.0-19.1 will be obsoleting
---> Package owncloud-app-provisioning_api.noarch 0:8.0.0-19.1 will be obsoleting
---> Package owncloud-app-templateeditor.noarch 0:8.0.0-19.1 will be obsoleting
---> Package owncloud-app-updater.noarch 0:8.0.0-19.1 will be obsoleting
---> Package owncloud-app-user_external.noarch 0:8.0.0-19.1 will be obsoleting
---> Package owncloud-app-user_ldap.noarch 0:8.0.0-19.1 will be obsoleting
--> Processing Dependency: php-ldap for package: owncloud-app-user_ldap-8.0.0-19.1.noarch
---> Package owncloud-app-user_webdavauth.noarch 0:8.0.0-19.1 will be obsoleting
---> Package owncloud-config-apache.noarch 0:8.0.0-19.1 will be obsoleting
--> Running transaction check
---> Package owncloud-server.noarch 0:8.0.0-19.1 will be installed
--> Processing Dependency: php >= 5.4.0 for package: owncloud-server-8.0.0-19.1.noarch
---> Package php-ldap.x86_64 0:5.3.3-40.el6_6 will be installed
--> Finished Dependency Resolution
Error: Package: owncloud-server-8.0.0-19.1.noarch (isv_ownCloud_community)
           Requires: php >= 5.4.0
           Installed: php-5.3.3-40.el6_6.x86_64 (@updates)
               php = 5.3.3-40.el6_6
           Available: php-5.3.3-38.el6.x86_64 (base)
               php = 5.3.3-38.el6
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by RealRancor** [comment]
OC8 needs PHP 5.4.x as stated in:

https://owncloud.org/blog/what-is-coming-in-owncloud-server-8-0-for-system-administrators/
http://doc.owncloud.org/server/8.0/admin_manual/release_notes.html

See here how to install PHP 5.4: https://github.com/owncloud/core/issues/13917#issuecomment-73424407

**Comment by paavon** [comment]
I noticed same problem at morning.  CentOS6 including php 5.4 as "php54" package from The Software Collections repository.
