### ISSUE TITLE
files app should throw 401 on unauth thumbnail and tag requests

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#14029]
While playing around with thumbnail support for the client I noticed that if I am not authorized and request a thumbnail via /index.php/apps/files/api/v1/thumbnail/2/3/welcome.txt the server does not respond with a 401.

Instead I get an error:

<br />
<b>Fatal error</b>:  Call to a member function getUId() on a non-object in <b>lib/private/tagmanager.php</b> on line <b>79</b><br />

Which is understandable since I did not authenticate.

**Comment by LukasReschke** [comment]
@PVince81
