### ISSUE TITLE
Segmentation fault in the users page with user_ldap app and a wrong configuration

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#14035]
Related to #14030 as it depends on setting a wrong configuration like that

### Steps to reproduce
1. Set a wrong configuration the same way it's done in #14030 (checked with a wrong port)
2. Make sure the only active configuration for ldap is this one (you can use `./occ ldap:set-config '' ldapConfigurationActive 1`, for the wrong configuration, and with a value of 0 for the rest)
3. Go to the users page

### Expected behaviour
Either the page shows an error, or shows only available users and groups ignoring the ldap users

### Actual behaviour
There is a segmentation fault and apache crashes

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** sqlite3

**PHP version:** 5.5.9

**ownCloud version:** ownCloud 7.0.5 RC1 (testing) 

**Updated from an older ownCloud or fresh install:** fresh install

#### Web server error log
```
[Tue Feb 10 10:39:59.602289 2015] [access_compat:error] [pid 5763] [client 10.40.30.21:37530] AH01797: client denied by server configuration: /home/jvillafanez/src/owncloud/owncloud1/data/htaccesstest.txt
[Tue Feb 10 10:46:46.605311 2015] [core:notice] [pid 1410] AH00051: child pid 5756 exit signal Segmentation fault (11), possible coredump in /etc/apache2
[Tue Feb 10 10:46:47.606619 2015] [core:notice] [pid 1410] AH00051: child pid 5677 exit signal Segmentation fault (11), possible coredump in /etc/apache2
[Tue Feb 10 10:46:49.609100 2015] [core:notice] [pid 1410] AH00051: child pid 5758 exit signal Segmentation fault (11), possible coredump in /etc/apache2
```

#### ownCloud log (data/owncloud.log)
```
{"app":"PHP","message":"ldap_connect() expects parameter 2 to be long, string given at \/home\/jvillafanez\/src\/owncloud\/owncloud1\/apps\/user_ldap\/lib\/ldap.php#252","level":3,"time":"2015-02-10T09:46:49+00:00"}
{"app":"PHP","message":"ldap_set_option(): supplied argument is not a valid ldap link resource at \/home\/jvillafanez\/src\/owncloud\/owncloud1\/apps\/user_ldap\/lib\/ldap.php#252","level":3,"time":"2015-02-10T09:46:49+00:00"}
{"app":"PHP","message":"ldap_connect() expects parameter 2 to be long, string given at \/home\/jvillafanez\/src\/owncloud\/owncloud1\/apps\/user_ldap\/lib\/ldap.php#252","level":3,"time":"2015-02-10T09:46:49+00:00"}
{"app":"PHP","message":"ldap_set_option(): supplied argument is not a valid ldap link resource at \/home\/jvillafanez\/src\/owncloud\/owncloud1\/apps\/user_ldap\/lib\/ldap.php#252","level":3,"time":"2015-02-10T09:46:49+00:00"}
{"app":"PHP","message":"ldap_connect() expects parameter 2 to be long, string given at \/home\/jvillafanez\/src\/owncloud\/owncloud1\/apps\/user_ldap\/lib\/ldap.php#252","level":3,"time":"2015-02-10T09:46:49+00:00"}
{"app":"PHP","message":"ldap_set_option(): supplied argument is not a valid ldap link resource at \/home\/jvillafanez\/src\/owncloud\/owncloud1\/apps\/user_ldap\/lib\/ldap.php#252","level":3,"time":"2015-02-10T09:46:49+00:00"}
```

**Comment by MorrisJobke** [comment]
cc @blizzz

**Comment by blizzz** [comment]
@jvillafanez the connection should not be active at all, if a clear misconfiguration (as reported) is given. Did you manually enable it?

**Comment by blizzz** [comment]
And via CLI, because otherwise the Wizard should not display the other tabs.

**Comment by jvillafanez** [comment]
I've enabled it via CLI.

I'll try to reach the same state from the wizard.

**Comment by jvillafanez** [comment]
Checked with IE8: it's possible to input and save letter instead numbers in the ldap port field from the ldap wizard.
I've also checked that IE11 doesn't seem to have this problem, because the field resets and the value isn't stored

Based on http://caniuse.com/#feat=input-number , probably IE9 will present the same problem but not IE10, however this hasn't been tested

**Comment by blizzz** [comment]
@jvillafanez OK, that may be, nevertheless the configuration should not be enabled automatically, because it cannot connect.

**Comment by blizzz** [comment]
A broken LDAP config (e.g. "foo" as port instead of a correct number) now leads to a ServerNotAvailableException. @jvillafanez would you confirm with current master?
