### ISSUE TITLE
ldap:test-config crashes with invalid values

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#14034]
Related to #14030 as it depends on setting a wrong configuration like that
### Steps to reproduce
1. Set a wrong configuration the same way it's done in #14030 (checked with a wrong port)
2. Run `./occ ldap:test-config ''` (the configID must be the wrong one)
### Expected behaviour

An error message is shown, complaining about an invalid configuration, or similar
### Actual behaviour

Nothing happens
### Server configuration

**Operating system**: 14.04

**Web server:** apache 2.4.7

**Database:** sqlite3

**PHP version:** 5.5.9

**ownCloud version:** ownCloud 7.0.5 RC1 (testing) 

**Updated from an older ownCloud or fresh install:** fresh install
#### ownCloud log (data/owncloud.log)

```
{"app":"PHP","message":"ldap_connect() expects parameter 2 to be long, string given at \/home\/jvillafanez\/src\/owncloud\/owncloud1\/apps\/user_ldap\/lib\/ldap.php#252","level":3,"time":"2015-02-10T09:46:49+00:00"}
{"app":"PHP","message":"ldap_set_option(): supplied argument is not a valid ldap link resource at \/home\/jvillafanez\/src\/owncloud\/owncloud1\/apps\/user_ldap\/lib\/ldap.php#252","level":3,"time":"2015-02-10T09:46:49+00:00"}
{"app":"PHP","message":"ldap_connect() expects parameter 2 to be long, string given at \/home\/jvillafanez\/src\/owncloud\/owncloud1\/apps\/user_ldap\/lib\/ldap.php#252","level":3,"time":"2015-02-10T09:46:49+00:00"}
{"app":"PHP","message":"ldap_set_option(): supplied argument is not a valid ldap link resource at \/home\/jvillafanez\/src\/owncloud\/owncloud1\/apps\/user_ldap\/lib\/ldap.php#252","level":3,"time":"2015-02-10T09:46:49+00:00"}
{"app":"PHP","message":"ldap_connect() expects parameter 2 to be long, string given at \/home\/jvillafanez\/src\/owncloud\/owncloud1\/apps\/user_ldap\/lib\/ldap.php#252","level":3,"time":"2015-02-10T09:46:49+00:00"}
{"app":"PHP","message":"ldap_set_option(): supplied argument is not a valid ldap link resource at \/home\/jvillafanez\/src\/owncloud\/owncloud1\/apps\/user_ldap\/lib\/ldap.php#252","level":3,"time":"2015-02-10T09:46:49+00:00"}
```

**Comment by MorrisJobke** [comment]
cc @blizzz

**Comment by karlitschek** [comment]
@blizzz any idea?

**Comment by blizzz** [comment]
This is usually only possible when doing the configuration on command line using occ. Valid, but rather unlikely to happen, while a fix might be not just few lines.

**Comment by jvillafanez** [comment]
I don't know if we officially support IE8 and IE9, but those browsers doesn't enforce a number in the port field of the LDAP wizard (the input type "number" doesn't seem to be supported)

**Comment by karlitschek** [comment]
we support them

**Comment by blizzz** [comment]
I expect it to be reasonable sense to insert 389 into port instead of threehundredeightynine. It's also documented accordingly. And standard ports are detected, too. 

→ I agree that this is not ideal behaviour and can be improved, but continue to see it as a corner case. Which means I deal with it as low priority, unless i am being shown that this his significant implications.

**Comment by PVince81** [comment]
Please reopen in the [user_ldap app repo](https://github.com/owncloud/user_ldap) if the issue persists with 10.0.4 and the latest version of the user_ldap app from the marketplace.
