### ISSUE TITLE
No validation is done in order to set a string-like value in an integer field with occ ldap:set-config

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#14030]
### Steps to reproduce
1. Create a valid ldap configuration (from the ldap wizard, for example)
2. Change an integer value to a string (for example the "ldapPort" -> `./occ ldap:set-config '' ldapPort randomPort`
3. Check the configuration -> `./occ ldap:show-config ''`
### Expected behaviour

The value isn't changed because it isn't valid
### Actual behaviour

The value is set with the string
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** sqlite3

**PHP version:** 5.5.9

**ownCloud version:** ownCloud 7.0.5 RC1 (testing) 

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by PVince81** [comment]
Please reopen in the [user_ldap app repo](https://github.com/owncloud/user_ldap) if the issue persists with 10.0.4 and the latest version of the user_ldap app from the marketplace.
