### ISSUE TITLE
Thumbnail generator should not return 200 when there is no thumbnail

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#14031]
When a thumbnail is requested for a file type we do not have a provider for it should not return status code 200 with an empty body. 

A 404/204 would make more sense IMO. Since there was no actual thumbnail generated 200 seems weird.

**Comment by PVince81** [comment]
@georgehrke @oparoz @LukasReschke

**Comment by oparoz** [comment]
I suggested 415
https://github.com/owncloud/core/pull/12546#issuecomment-68596719

**Comment by rullzer** [comment]
> I suggested 415, but I now realise that it only applies to the requesting content-type, not the response...

Well with a little "reading between the line" the RFC could be interperted for this case:

> 10.4.16 415 Unsupported Media Type
>
> The server is refusing to service the request because the entity of the request is in a format not  supported by the requested resource for the requested method. 

415 seems like a good fit.

**Comment by PVince81** [comment]
Isn't it already returning 404 now ?

**Comment by rullzer** [comment]
Ah yes. This is changed.
By default it will return the mimeicon. But if you pass it forceIcon=0 then it will return a 404.
