### ISSUE TITLE
accessing /index.php/apps/contacts/addressbook/local/1/export

### ISSUE THREAD

**Issue by abrumloop** [owncloud/core#14045]
### Steps to reproduce
1. curl -u <user>:<pw>  https://<url>/owncloud/index.php/apps/contacts/addressbook/local/1/export > adressbook.vcf

### Expected behaviour
This command should download the adressbook
### Actual behaviour
Everything i get is a login error:
{"message":"Current user is not logged in"}

The same command does the job with owncloud 7. With firefox / chrome downloading still works.

### Server configuration

**Web server:**
apache
**Database:**
sql
**PHP version:**
5.5
**ownCloud version:** (see ownCloud admin page)
8
**Updated from an older ownCloud or fresh install:**
fresh
**List of activated apps:**
contacts, calendar, share, activities, deleted files, file locking, first run wizard, mail template editor, pdf-viewer, pictures, text, Provisioning API, updater, versions, video viewer 
**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password, passwordsalt and secret)
<?php
$CONFIG = array (
'instanceid' => 'oczxzjxdmzrh',
'passwordsalt' => '',
'secret' => '',
'trusted_domains' =>
array (
0 => '',
),
'datadirectory' => '/mnt/webr/c3/66/54458666/htdocs/owncloud/data',
'overwrite.cli.url' => 'https:///owncloud',
'dbtype' => 'mysql',
'version' => '8.0.0.7',
'dbname' => 'DB2016509',
'dbhost' => 'rdbms.strato.de',
'dbtableprefix' => 'oc_',
'dbuser' => 'U2016509',
'dbpassword' => '',
'installed' => true,
'loglevel' => 1,
'forcessl' => true,
'forceSSLforSubdomains' => true,
'mail_from_address' => 'oc',
'mail_smtpmode' => 'php',
'mail_domain' => '',
);
**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
### Client configuration
**Browser:**

**Operating system:**

#### ownCloud log (data/owncloud.log)
no entry

**Comment by DeepDiver1975** [comment]
please open this issue in https://github.com/owncloud/contacts - THX
