### ISSUE TITLE
shared hosting installer gives ownCloud 7.0.4 and not 8

### ISSUE THREAD

**Issue by ndeblauw** [owncloud/core#14042]
I'm not sure whether this is intentionally or not, but I'm just observing it.

**Comment by RealRancor** [comment]
Seems https://download.owncloud.org/download/community/owncloud-latest.zip which is downloaded by the installer is not updated yet.

**Comment by DeepDiver1975** [comment]
@karlitschek can you please update the link? THX

**Comment by karlitschek** [comment]
We usually do this a bit after the public announcement. I just updated it. can you try again please?

**Comment by ndeblauw** [comment]
it is 8.0 now (I just installed and checked it)

**Comment by DeepDiver1975** [comment]
> We usually do this a bit after the public announcement. I just updated it.

THX @karlitschek
