### ISSUE TITLE
New Lines are ignored on Windows

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#14046]
On Windows when creating a text-file in the browser and then open it locally in Notepad, new lines are ignored.

### Steps to reproduce
Tested on Windows 7 with IE 11 on ownCloud Server 6 with client 1.7.1  and ownCloud Server 7  with ownCloud client 1.7.1 :
1. go to the browser and create a text-file.
2. edit the newly created text-file and write on multiple lines. ie.
		"hi
		there
		how
		are
		you"
3. wait to sync on your windows computer
4. open the text-file in notepad.exe

### Expected Result:
		"hi
		there
		how
		are
		you"

### Actual Result:
		"hitherehowareyou"

The newlines are completely ignored. This is a problem all Windows user have.

@MorrisJobke 

00002575

**Comment by DeepDiver1975** [comment]
> On Windows when creating a text-file in the browser and then open it locally in Notepad, new lines are ignored.

we are talking about our text editor as part of owncloud?

https://github.com/owncloud/files_texteditor please in this case - THX

**Comment by MorrisJobke** [comment]
https://github.com/owncloud/files_texteditor/issues/60
