### ISSUE TITLE
s2s ldap invitation with user name, not ldap id

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#14043]
### Steps to reproduce
1. Setup two ownCloud instances A and B with LDAP
2. Make sure to have a user "user1" on A and a user "user2" on B
3. Login on A as user "user1"
4. Create a folder "test"
5. Share "test" with "user2@B" (replace B with the address of ownCloud B)

### Expected result
Invitation sent.

### Actual result
Error message that the user "user2" could not be found.
But if I use the long LDAP id: "5108dd16-4561-1034-82b2-4bf38ed03200@B" then it works.

This is a usability issue, because we cannot expect regular users to know/remember the target user's LDAP IDs.

### Versions
ownCloud 8.0.0

@blizzz @schiesbn @icewind1991

**Comment by blizzz** [comment]
"Could not be found" or "User does not exist"? What's the complete error message?

**Comment by PVince81** [comment]
Let me resetup LDAP to find out

**Comment by blizzz** [comment]
In general, it does not seem to be trivial to solve. Usernames are unique, but are not really known to users (and may be unpractical to memorize). Basically they know the display name. This however is not unique.

**Comment by blizzz** [comment]
Login name: does not need to be unique either. And we don't have any methods to check them.

**Comment by PVince81** [comment]
![sharing_ldap_error](https://cloud.githubusercontent.com/assets/277525/6127188/8def36f0-b128-11e4-8dea-7da178b84418.png)

**Comment by PVince81** [comment]
![sharing_ldap_error1](https://cloud.githubusercontent.com/assets/277525/6127197/a6eb9e64-b128-11e4-8888-99d58f872625.png)

**Comment by blizzz** [comment]
I think we die here: https://github.com/owncloud/core/blob/master/apps/files_sharing/api/server2server.php#L53

**Comment by blizzz** [comment]
Better would be a lookup (like on the sharing dialog) on the remote server

**Comment by blizzz** [comment]
I cannot come up with a proper solution. We cannot do searches, because they are to fuzzy and might end up with sharing to the wrong user.

For now I say, let us display a share token (USERID@OC) to the personal page that people can pass on.

**Comment by blizzz** [comment]
Possible solution as discussed with @schiesbn on IRC:

 * we move away from usernames (they are not known to users, plus don't need to be leaked) and use "tokens" instead, basically an extra name.
 * those upgrading from 8.0.0 will have set their username as token to establish backwards compatibility. 
 * default tokens will be username as well. 
 * a token can be chosen freely otherwise, but must be unique and is mapped internally to the username
 * it will be presented on the Personal page
 * it will not appear to be different than now for the end user

**Comment by PVince81** [comment]
CC @owncloud/designers

**Comment by schiesbn** [comment]
I think we can implement this relatively easy. I will take care of it.

**Comment by DeepDiver1975** [comment]
I honestly don't see this being fixed for 8.0.1 based on the current implementation ... simply to risky as it introduced a new table - we shall not do this in patch releases

**Comment by karlitschek** [comment]
yes. 8.1

**Comment by DeepDiver1975** [comment]
@blizzz can we chat about this issue with respect to ldap - this smells all very fishy :speak_no_evil:

**Comment by SergioBertolinSG** [comment]
Still present in 8.1.1beta1.

LDAP ids are very confusing, you don't know which user owns a file at a first sight.
Same when receiving a new federated sharing.
