### ISSUE TITLE
Fix files_external UI to work with the new storage_id

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#14058]
Currently the files_external UI is unmaintainable, because it uses a combination of all settings (tuple) as if it was a unique id. This is very unreliable and can cause possible breakage.

Since OC 8.0 there is a new "storage_id" value stored in mount.json.

The external storage config code must be adapted to use this storage_id when updating the config instead of the huge tuple.

This will make room for adding more options.

CC @icewind1991

**Comment by PVince81** [comment]
I'd like to migrate the code from addMountPoint/removeMountPoint to app framework controllers instead. We can keep the config reading code (for mount.json) in that ugly static class for now (until we get the new DB based one  https://github.com/owncloud/core/issues/11261)

**Comment by PVince81** [comment]
CC @Xenopathic

**Comment by PVince81** [comment]
The new storage_id isn't reliable... see: https://github.com/owncloud/core/pull/11884#issuecomment-73883825

**Comment by Xenopathic** [comment]
This was implemented as part of #11884 - awesome!
