### ISSUE TITLE
Mounting ownCloud inside another ownCloud unable to upload files

### ISSUE THREAD

**Issue by bboule** [owncloud/core#14055]
Steps to reproduce

Create a folder on ownCloud 1  login to ownCloud 2 and mount this folder using the external storage app.

Attempt to upload a file from ownCloud 2 to this newly mounted folder (mounted from ownCloud 1)

Expected behavior

You should be able to upload to this folder without issue

Actual behavior

When you upload a file it hits the server, is scan via anti virus but you then get a message that says the target folder has been moved or deleted 

Server configuration

Operating system: Centos 6.5

Web server: Apache/2.2.22 (centos)

Database:MySql

PHP version: PHP 5.5.20

ownCloud version: 7.0.4

Fresh OC Install

Logs

From ownCloud 2

Debug	sharepoint	get_global_mounts	2015-02-10T07:04:54+00:00
Warning	sharing	No fileinfo available for: /ownCloud/dwsup.pdf	2015-02-10T07:04:45+00:00
Error	webdav client	Resource not found.	2015-02-10T07:04:44+00:00
Error	webdav client	Resource not found.	2015-02-10T07:04:39+00:00
Debug	OC\Files\Cache\Scanner	!!! Path 'dwsup.pdf' is not readable !!!	2015-02-10T07:04:39+00:00
Error	webdav client	curl GET http://172.18.5.38/owncloud/remote.php/webdav/Law Firm 2/dwsup.pdf returned status code 204	2015-02-10T07:04:38+00:00
Error	webdav client	Resource not found.	2015-02-10T07:04:37+00:00
Debug	OC\Files\Cache\Scanner	!!! Path 'dwsup.pdf' is not readable !!!	2015-02-10T07:04:37+00:00
Error	webdav client	Resource not found.	2015-02-10T07:04:36+00:00
Info	admin_audit	Write "/admin/files/ownCloud/dwsup.pdf" by user admin, owner: admin	2015-02-10T07:04:35+00:00
Error	webdav client	Resource not found.	2015-02-10T07:04:35+00:00
Info	admin_audit	Write "/admin/files/ownCloud/dwsup.pdf" by user admin, owner: admin	2015-02-10T07:04:35+00:00
Info	admin_audit	Create "/admin/files/ownCloud/dwsup.pdf" by user admin, owner: admin	2015-02-10T07:04:35+00:00
Debug	sharepoint	Get applicable mount points	2015-02-10T14:11:53+00:00
Debug	files_antivirus	Result CLEAN!	2015-02-10T14:11:53+00:00
Debug	files_antivirus	Response :: stream: OK	2015-02-10T14:11:53+00:00
Debug	files_antivirus	Exec scan: files/Random Files/TestFile3096.txt	2015-02-10T14:11:53+00:00
Debug	files_antivirus	Result CLEAN!	2015-02-10T14:11:53+00:00
Debug	files_antivirus	Response :: stream: OK	2015-02-10T14:11:53+00:00
Debug	files_antivirus	Exec scan: files/Random Files/TestFile6916.txt	2015-02-10T14:11:52+00:00
Debug	files_antivirus	Result CLEAN!	2015-02-10T14:11:52+00:00
Debug	files_antivirus	Response :: stream: OK	2015-02-10T14:11:52+00:00
Debug	files_antivirus	Exec scan: files/Random Files/TestFile7698.txt	2015-02-10T14:11:52+00:00

**Comment by DeepDiver1975** [comment]
> ownCloud version: 7.0.4

go for 7.0.5 - we did fix some issues in the area of s2s

**Comment by bboule** [comment]
OK cool I will test in 7.0.5 and close on successful test!!  Thanks for your help!!

**Comment by PVince81** [comment]
@bboule any update ?

Could also be an issue with the antivirus app...

**Comment by PVince81** [comment]
CC @VicDeo

**Comment by PVince81** [comment]
@bboule did it work better with 7.0.6 or 8.0.6 ?

**Comment by PVince81** [comment]
okay actually it's not about federated sharing but external storage

**Comment by PVince81** [comment]
@bboule any update ?

**Comment by PVince81** [comment]
Closing due to lack of feedback.
