### ISSUE TITLE
owncloud 8 :: centos6 :: webpage stuck at "currently being updated"

### ISSUE THREAD

**Issue by adriansev** [owncloud/core#14050]
### Steps to reproduce
1. yum update to owncloud 8

### Expected behaviour
after update the web page should return to normal login page

### Actual behaviour
the webpage is stuck at 
"This ownCloud instance is currently being updated, which may take a while."
update page.

### Server configuration
**Operating system**:
CentOS 6 

**Web server:**
httpd-2.2.15-39.el6.centos.x86_64

**Database:**
sqlite3

**PHP version:**
php-5.6.0-1.el6.remi.1.x86_64

**ownCloud version:** (see ownCloud admin page)
owncloud-server-8.0.0-19.1.noarch

**Updated from an older ownCloud or fresh install:**
updated from previous installation with yum update

**List of activated apps:**

**The content of config/config.php:**
define('DEBUG', true);

$CONFIG = array (
  'instanceid' => 'replaced',
  'passwordsalt' => 'replaced',
  'datadirectory' => '/export/owncloud_data',
  'overwritewebroot' => '/owncloud',
  'dbtype' => 'sqlite',
  'version' => '7.0.4.2',
  'installed' => true,
  'maxZipInputSize' => 104857600,
  'allowZipDownload' => false,
  'loglevel' => '0',
  'forcessl' => true,
  'theme' => '',
  'maintenance' => true,
  'mail_domain' => 'issaf.spacescience.ro',
  'trusted_domains' =>
  array (
    0 => 'issaf.spacescience.ro',
  ),
  'mail_from_address' => 'owncloud',
  'mail_smtpmode' => 'php',
  'secret' => 'replaced',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

### Client configuration
**Browser:** 
firefox-35.0-3.fc20.x86_64
google-chrome-stable-40.0.2214.111-1.x86_64

**Operating system:**
Fedora 20 x86_64

#### Web server error log
ssl access
217.156.104.90 - - [10/Feb/2015:15:41:16 +0200] "GET /owncloud/status.php HTTP/1.1" 200 92

ssl request
[10/Feb/2015:15:41:16 +0200] 217.156.104.90 TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256 "GET /owncloud/status.php HTTP/1.1" 92

#### ownCloud log (data/owncloud.log)
{"reqId":"070a55624cb9e90b30a90f342a3b39d1","remoteAddr":"217.156.104.90","app":"PHP","message":"Module 'mysqlnd' already loaded at Unknown#0","level":3,"time":"2015-02-10T13:29:10+00:00","method":"GET","url":"\/owncloud\/status.php"}
{"reqId":"7f8bc0440343abafb0be4a31b4fee98c","remoteAddr":"217.156.104.90","app":"PHP","message":"Module 'mysqlnd' already loaded at Unknown#0","level":3,"time":"2015-02-10T13:29:34+00:00","method":"GET","url":"\/owncloud\/index.php\/core\/js\/oc.js?v=f99456086f190e43269fc80ffd1a2724"}
{"reqId":"f2fb471e2762e2a6d1867896db72465b","remoteAddr":"","app":"PHP","message":"Module 'mysqlnd' already loaded at Unknown#0","level":3,"time":"2015-02-10T13:30:02+00:00","method":"--","url":"--"}
{"reqId":"40dec34d23ca66d781880bc76f6ea2cf","remoteAddr":"217.156.104.90","app":"PHP","message":"Module 'mysqlnd' already loaded at Unknown#0","level":3,"time":"2015-02-10T13:30:55+00:00","method":"GET","url":"\/owncloud\/status.php"}

**Comment by RealRancor** [comment]
Hi,

you can try to set:

```
'maintenance' => true,
```

to:

```
'maintenance' => false,
```

to see if your installation is available again.

```
{"reqId":"070a55624cb9e90b30a90f342a3b39d1","remoteAddr":"217.156.104.90","app":"PHP","message":"Module 'mysqlnd' already loaded at Unknown#0","level":3,"time":"2015-02-10T13:29:10+00:00","method":"GET","url":"\/owncloud\/status.php"}
```

This just shows that you're loading this mysqlnd module twice in your PHP configuration. This needs to be fixed in your PHP config file.

**Comment by Croydon** [comment]
I have basically the same problem on Ubuntu 14.04. I have started the upgrade progress once more, and it finished, but the config.php didn't get updated. It keeps in maintance mode, and the old version number. Should I just modify it manually?

**Comment by PVince81** [comment]
Are you still having issues with 8.0.5 ?

One reason why the maintenance mode might not be set back is due to errors during the update, sometimes apps that couldn't update properly. The log might contain some clues.

**Comment by adriansev** [comment]
I am at 8.1.0-18.1 and the upgrade was without problems.
