### ISSUE TITLE
SQL error when upgrading from oc7 to oc8

### ISSUE THREAD

**Issue by ccharlot** [owncloud/core#14053]
### Steps to reproduce
1. upgrade oc from the command line (sudo -u www-data php /var/www/owncloud/occ upgrade)

### Expected behaviour 
Upgrade should comlpete

### Actual behaviour
I get this error message : 
An exception occurred while executing 'UPDATE "oc_filecache" SET "mtime" = ?, "etag" = ?, "storage_mtime" = ?, "parent"=? WHERE "fileid" = ?' with params [1423576133, "c627e22394863e7c6798ac5abc0b0502", 1423576133, null, "59108"]:

SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: oc_filecache.parent
 

### Server configuration
**Operating system**: Ubuntu 14.04
**Web server:** Apache 2.4.7
**Database:** MYSQL 5.5.41-0ubuntu0.14.04.1-log
**PHP version:**  PHP 5.5.15-1+deb.sury.org~precise+1
**ownCloud version: 8.0.0-5
**Updated from an older ownCloud or fresh install:  7.0.4 .2 
**List of activated apps: don't remember
**The content of config/config.php:**
'instanceid' => '51e5bf75776d5',
  'passwordsalt' => 'removed',
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'sqlite3',
  'version' => '7.0.4.2',
  'installed' => true,
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => '2',
  'trusted_domains' => 
  array (
    0 => 'c.fuc.fr',
    1 => 'oc.fuc.fr',
  ),
  'mail_from_address' => 'ccharlot',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'fuc.fr',
  'secret' => (removed)',

**Are you using external storage, if yes which one:** no
**Are you using encryption:** yes

### Client configuration
N/A

#### Web server error log
No revelant message

Insert your webserver log here
N/A

#### ownCloud log (data/owncloud.log)
No new message during upgrade process.

**Comment by ccharlot** [comment]
I think I have more infos on this problem : 

The SQL error message looks like there is a problem with a "parent" file name missing somewhere.

Looking at the owncloud log file, there are messages about user1.private.key, user2.private.key, ... missing  .. and when looking it the directory, I find user1.privateKey ..

Surely both are related ?

I'll keep investigating this way.. :)

**Comment by DeepDiver1975** [comment]
@icewind1991 parent is NULL - any idea? THX

**Comment by ccharlot** [comment]
I followed the info about private keys in the owncloud logfile and found some informations in issue #14012 .

Applying the solution at the end of the comments by @jknockaert did solve the problems found in the log files... but not the initial subject if this issue, I still have the SQL error message :(

**Comment by tessus** [comment]
@DeepDiver1975 I saw that this bug is scheduled for 8.1-next.

I was about to upgrade my oc7 to oc8, but I'm afraid I will run into the same problem. Is there a solution to this or do I have to wait for 8.1 to be able to upgrade?

**Comment by tessus** [comment]
@DeepDiver1975 any update on this? what is your take on this issue? what shall I do, if I want to upgrade?

I was about to upgrade my oc7 to oc8, but I'm afraid I will run into the same problem. Is there a solution to this or do I have to wait for 8.1 to be able to upgrade?

**Comment by karlitschek** [comment]
@jnfrmarks Can you try to reproduce?

**Comment by PVince81** [comment]
It is still not clear how to reproduce this issue.

@ccharlot did you still see that error message when updating to recent versions like 8.1.3 ?
Do you have any files or folders which names end with ".part" in your database ?
`select * from oc_filecache where path like '%.part'`

If yes, you can try and delete the as they will can cause trouble.

**Comment by ccharlot** [comment]
Hi,

Sorry I forgot this issue... I managed to upgrade to one of the recent version so for me this issue is closed.
