### ISSUE TITLE
Recomended apps show enable for already enabled apps

### ISSUE THREAD

**Issue by drsbaitso** [owncloud/core#14054]
In reccomended apps, it shows two apps (calendar and contacts) that I already have enabled with the Enable button.  Either these apps shouldn't show up in recomended if they're enabled, or have the 'disable' button if they are already enabled.

**Comment by karlitschek** [comment]
@DeepDiver1975

**Comment by RealRancor** [comment]
Hi,

could be possible that this was already fixed: https://github.com/owncloud/core/issues/14033

**Comment by clarjon1** [comment]
I reported this yesterday,  #14004

**Comment by MorrisJobke** [comment]
duplicate of #14004
