### ISSUE TITLE
Update OC from 7.0.4.2 to 8.0 RC2 took a lot of time because of encryption key reorganisation

### ISSUE THREAD

**Issue by DrHauss** [owncloud/core#14060]
Updating OC from 7.0.4.2 to 8.0 RC2 took a lot of time in large deployments. 

"occ upgrade" hangs at the following point:

Turned on maintenance mode
Checked database schema update
Updated database

Doing an strace shows that there is a reorganisation of the encryption keyfiles with 8RC2 which took a lot of time because ~10GB of stored files and user and group sharing. 

In my personal meaning the output of occ upgrade should give more information about the actual status. There are no information about the keyfile update/reorganisation. Also option -vvv for more debug/verbose output doesn't give more status about the update.

Following improvements shoud be implemented:
 1. OC 8 update notes + release notes should inform about possible required update time 
 2. occ upgrade should give a detailed status about the upgrade procedure (e.g. reorganisation keys of user XXXX) so that the user get the information about what is actual beeing done by the updater.

**Comment by karlitschek** [comment]
@schiesbn

**Comment by Skatox** [comment]
Same problem in here but with 3GB of data. I though that the script was locked or something.

**Comment by VictorPhilipp** [comment]
Please implement some kind of "This process will take very long. Press Enter to continue or Ctrl+C to abort..." and some progress indicator the next time. Then, we get at least some kind of hint that it would be wise to run it inside a screen session...

**Comment by Krishath** [comment]
+1 (still upgrading)

**Comment by sylwe** [comment]
For me i'm geting error like that:

An exception occurred while executing 'UPDATE `oc_filecache` SET `path` = ?, `path_hash` = ?, `name` = ?, `parent` =? WHERE `fileid` = ?' with params ["files_encryption\/public_keys\/pubShare_6b01177f.publicKey", "d8b21e1933e37f19665619d765634fc0", "pubShare_6b01177f.publicKey", "166292", 177982]:
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4-d8b21e1933e37f19665619d765634fc0' for key 'fs_storage_path_hash'

**Comment by DrHauss** [comment]
@silwe: I think that is another issue where you should open a new issue to analyze this special topic. 

In general regarding this topic:

For me it took about 8 hours to upgrade the encryption files (~38500 keyfiles incl. shared keys)

Is there in general no other way to reorganize this faster or better :-)

**Comment by sylwe** [comment]
I have to do that on github, right now I'm waiting for answer on the owncloud forum. Thanks for reply.

**Comment by VictorPhilipp** [comment]
Wow, upgrade done (after 3 whole days [sic]) for ~15GB of encryption-enabled data (especially having lots of small files seems to contribute to the long delay). How could one ever, ever think of upgrading a production server with more than 2 users?
I have seen in the strace output that you are iterating over all files (probably doing hashing or encrypting) and performing some SQL queries. Maybe,
1. you could parallelize this process such that 2 or more files are processed simultaneously and/or
2. the database work is done concurrently (so that the next file can be processed while the queries from the previous file are being processed).

Dreaming of "./occ upgrade --num-cpus=#"...

**Comment by DrHauss** [comment]
same issue as #14012

**Comment by jimlei** [comment]
Looking forward to this, just initiated an upgrade 1 hour ago and started browsing when the upgrader "hanged". Since I have 3TB of encrypted data (millions of files) this is probably going to take a while...

**Comment by DeepDiver1975** [comment]
8.1 and 8.0.3 will fix this issues -> close

**Comment by anolting** [comment]
Hello DeepDiver1975,

i'm just upgrading from 7.0.4 to 8.0.3 and experience the issue like before. I have encrypted folders and files of around 15 GB in size and 6 users. The updater seems to hang while it hopefully does it's job.

So for me it's not fixed in 8.0.3.

Regards
Alex

**Comment by michaelstingl** [comment]
@MorrisJobke Could you investigate @anolting 's problem? Do you need more information? /cc @DeepDiver1975 

00003344

**Comment by anolting** [comment]
Hello Michael,

just for update the ticket. After around 10 hours (can't exactly say at which time specific as I didn't watched all the time the command line) the script finished the upgrade. As I can see there where no errors while updating the installation and it looks like that the server is running fine.

If you need some logs or something else please point me to right direction.
Regards
Alex

**Comment by DeepDiver1975** [comment]
Time is relative - we did improve the execution time - but at the end it will run for some amount of time.

I'm pretty aware of the fact that we miss some kind of progress communication to the user.

**Comment by anolting** [comment]
Ok, then I may misinterpreted the thread ;) So I'm fine if close the case again.
