### ISSUE TITLE
The external storage icon is not displayed at the "All files" view, when the external storage is local

### ISSUE THREAD

**Issue by swas** [owncloud/core#14062]
Using the ownCloud admin user, when I add a External Storage local mount through the GUI (or Configuration File), the external storage icon (folder-external.svg) ![Image of Yaktocat](https://demo.owncloud.org/core/img/filetypes/folder-external.svg)  is not displayed at the "All files" view, (the folder.svg icon is showed instead) but at the "external storage" view, the icon is displayed.

With other types of external storage mounts (like SMB/CIFS) this is not happening.

I think that the icon should be displayed in all views regardless of the type of external storage

### Server configuration

I appreciated this error since version 7.0.2

I don't know if OC 8 continues with this issue

**Comment by swas** [comment]
I appreciated this error since version 7.0.2

I don't know if OC 8 continues with this issue

**Comment by Xenopathic** [comment]
Have a look at #10712 :smile:
