### ISSUE TITLE
App Install with Proxy don't work

### ISSUE THREAD

**Issue by hlop** [owncloud/core#14066]
Change, to fix it, in owncloud/lib/private/installer.php from:

copy($data['href'], $path);

to:

file_put_contents($path, \OC_Util::getUrlContent($data['href']));

**Comment by karlitschek** [comment]
@icewind1991 @DeepDiver1975 what do you think?

**Comment by DeepDiver1975** [comment]
Absolutely reasonable - @hlop feel free to submit a pull request in case you are interested in contributing - THX

**Comment by DeepDiver1975** [comment]
fixed with #14086
