### ISSUE TITLE
Set correct preview_office_cl_parameters in config.sample.php

### ISSUE THREAD

**Issue by ghost** [owncloud/core#14069]
Hi,

seems the preview_office_cl_parameters in the config.sample.php:

https://github.com/owncloud/core/blob/v8.0.0/config/config.sample.php#L640-L645

is currently out-of-sync with the one used in office.php:

https://github.com/owncloud/core/blob/v8.0.0/lib/private/preview/office.php#L26

If a user is using the preview_office_cl_parameters from config.sample.php (as seen yesterday in IRC) the preview generation for .doc and .docx is broken if the .config folder is not writeable by the webservers user (See: https://github.com/owncloud/documents/issues/291#issuecomment-48382155).

**Comment by RealRancor** [comment]
Not quite sure if this is also valid for stable7

**Comment by RealRancor** [comment]
Is the syntax:

```
'preview_office_cl_parameters' =>
	' -env:UserInstallation=file://' . escapeshellarg($tmpDir . '/owncloud-' . \OC_Util::getInstanceId().'/') '.
	'--headless --nologo --nofirststartwizard --invisible --norestore '.
	'--convert-to pdf --outdir ';
```

correct? I could prepare a PR if someone can confirm this.

**Comment by settermjd** [comment]
Is this still relevant @PVince81 @MorrisJobke?

**Comment by MorrisJobke** [comment]
> Is this still relevant @PVince81 @MorrisJobke?

I don't know, what the status is here.

Disclaimer: I also moved to https://github.com/nextcloud.

**Comment by settermjd** [comment]
Closing as the, seeming, implementing PR is closed.
