### ISSUE TITLE
"re-share" an unshare folder

### ISSUE THREAD

**Issue by iwurzer** [owncloud/core#14075]
Hello,

if someone shares a folder with you, you can see it in your web-client. Instead of an "Delete" Button you already implemented the "Unshare" Button. 

Feature Request A:
Disable the possibility to "Unshare" a folder/file (per Admin or ShareOwner)

Feature Request B:
Show the folder/file entry in the "shared with me" Section and/or in the "Recyle Bin" (maybe special backgroudn color or something else) and a "re-share" Button; If you click on the button, your "unshared" folder will be shown again...

Thanks and best regards,
Ingo

**Comment by karlitschek** [comment]
@schiesbn

**Comment by MTRichards** [comment]
@jancborchardt best bet to put this in the recycle bin?

**Comment by jancborchardt** [comment]
@iwurzer please open 2 different issues if you have 2 different feature requests. Thanks! :)

Request A: Well, we would need to introduce yet another setting for that. I think it’s the first time we had this request. @MTRichards 

Request B: Restoring a deleted folder/file which was shared with you from the deleted files should also restore the sharing relationship, automatically. cc @schiesbn

**Comment by MTRichards** [comment]
I should have said, I meant for option B to put it in the recycle bin.

But yes, two issues would help keep them separate

**Comment by schiesbn** [comment]
Feature request B was already discussed here with the idea of a "pending shares" entry on the side bar which contain both, not yet accepted shared and unshared shares. https://github.com/owncloud/core/issues/13495

Not sure about Feature request A, I don't like the idea that I I can't unshare files shared with me. I should be always in control of my files folder.

**Comment by jancborchardt** [comment]
Agree with @schiesbn on both points. Things have either already discussed or need their own issue. Closing this mix.
