### ISSUE TITLE
[OC8] [NGINX] - Sendfile should send URI instead of absolute path

### ISSUE THREAD

**Issue by josh4trunks** [owncloud/core#14082]
Please revert https://github.com/owncloud/core/pull/13060
Explained https://github.com/owncloud/core/pull/13060#issuecomment-73815564

**Comment by MorrisJobke** [comment]
cc @LukasReschke

**Comment by josh4trunks** [comment]
This is addressed by https://github.com/owncloud/core/pull/14125#issuecomment-75731085

**Comment by josh4trunks** [comment]
this was fixed by https://github.com/owncloud/core/pull/14125
