### ISSUE TITLE
Can't change the email if the username is also an email

### ISSUE THREAD

**Issue by MightyCreak** [owncloud/core#14083]
### Steps to reproduce
1. Create a new user with an email address as username
2. Go to Users (in the top-right corner)
3. Enter the same email as the username, but in the email field

Rk: changing the email work if you change it directly from the user account.

### Expected behaviour
The email is saved

### Actual behaviour
The email is not saved (need to refresh Users to see it)

### Server configuration
**Operating system**: Debian 7.5 (GNU/Linux)

**Web server:** Nginx 1.2

**Database:** MySQL 5.5

**PHP version:** PHP 5.4

**ownCloud version:** 8.0 (stable)

**Updated from an older ownCloud or fresh install:** updated from 7.0.2

**List of activated apps:** Default apps, Music 0.3.4

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'trusted_domains =>
  array (
    0 => 'xxx',
    1 => 'xxx',
  ),
  'datadirectory' => 'xxx',
  'dbtype' => 'mysql',
  'version' => '8.0.0.7',
  'dbname' => 'xxx',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword => 'xxx',
  'installed' => true,
  'loglevel' => '0',
  'theme' => '',
  'maintenance' => false,
  'mail_from_address' => 'xxx',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'xxx',
  'secret' => 'xxx',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'xxx',
  'mail_smtpport' => 'xxx',
  'mail_smtpname' => 'xxx',
  'mail_smtppassword' => 'xxx',
  'forcessl' => false,
);
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

### Client configuration
**Browser:** Firefox 35

**Operating system:** GNU/Linux (Manjaro), Windows 7

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by PVince81** [comment]
Works for me on 9.1.1, possibly a very old issue.
