### ISSUE TITLE
Updating to 8.0: Could not automatically fix legacy storage

### ISSUE THREAD

**Issue by derherrc** [owncloud/core#14088]
...while updating ownCloud server to version 8 this error was shown to me:

Could not automatically fix legacy storage "local::/home/xxxxxxx/owncloud-data/admin/" => "home::admin" because they both have data.
The update was unsuccessful. Please report this issue to the ownCloud community.

**Comment by PVince81** [comment]
Please check https://github.com/owncloud/core/issues/13980
It has some ideas on how to manually fix your duplicate storages.

Make sure to check whether the "datadir" setting in config.php matches the "local::" storage entries.
