### ISSUE TITLE
Cannot enable contacts and calendar after upgrade to 8.0

### ISSUE THREAD

**Issue by Killer1337** [owncloud/core#14099]
The contacts and calendar apps are gone after I upgraded manually from 7.04 to 8.0 by following the steps in the Owncloud Documentation.

I copied my old config.php from 7.04 to and deactivated maintanance mode. After the next call of the owncloud webpage, the upgrade process ran through just fine.

But when I try to activate any app in the apps section of the admin account it won't work.
I get `Archive vom Typ werden nicht unterstützt` (sorry, my install is german, it means something like `Archive of this Type is not supported`)

In the log section of my admin acount the output is:

    Error 	core 	Archive vom Typ werden nicht unterstützt 	2015-02-11T08:49:24+00:00
    Error 	PHP 	mime_content_type(): Can only process string or stream arguments at /media/www_owncloud/lib/private/files/type/detection.php#103 	2015-02-11T08:49:24+00:00
    Error 	PHP 	copy(): Filename cannot be empty at /media/da151e00-ebb1-4f57-ae22-7cbf0f7a9e8d/www_owncloud/lib/private/installer.php#244 	2015-02-11T08:49:24+00:00
    Warning	no app in context	Can not create a temporary file in directory /media/data. Check it exists and has correct permissions	2015-02-11T08:49:24+00:00[/code]

I checked the permissions for `www_owncloud` and also for my owncloud data dir (`/media/owncloud_data`). 

But I don't know why the warning message states `/media/data`. This directory doesn't exist.

In the upgrade process, the only change made to the config.php seems to be the version number. My config looks like this now:

    <?php
    $CONFIG = array (
      'maintenance' => false,
      'instanceid' => 'xxx',
      'passwordsalt' => 'xxxx',
      'trusted_domains' =>
      array (
        0 => '192.168.178.1',
        1 => 'xxx.yyy.com',
      ),
      'datadirectory' => '/media/owncloud_data',
      'dbtype' => 'mysql',
      'version' => '8.0.0.7',
      'dbname' => 'owncloud',
      'dbhost' => 'localhost',
      'dbtableprefix' => 'oc_',
      'dbuser' => 'owncloud',
      'dbpassword' => 'xxx',
      'installed' => true,
      'forcessl' => true,
      'mail_smtpmode' => 'smtp',
      'mail_from_address' => 'xxx',
      'mail_domain' => 'xxx',
      'mail_smtpsecure' => 'tls',
      'mail_smtpauthtype' => 'LOGIN',
      'mail_smtpauth' => true,
      'mail_smtphost' => 'xxx.yyy.com',
      'mail_smtpport' => '587',
      'mail_smtpname' => 'xxx',
      'mail_smtppassword' => 'xxx',
      'appcodechecker' => false,
      'appstoreenabled' => true,
      'appstoreurl' => 'https://api.owncloud.com/v1',
      'apps_paths' => array(
              array(
                      'path'=> '/media/www_owncloud/apps',
                      'url' => '/apps',
                      'writable' => true,
              ),
      ),

      'loglevel' => '2',
      'theme' => '',
      'secret' => 'xxx',
    );`

Do I need to add anything in order to make calendar and contacts work again? 

I already manually added the appstore stuff:

      'appstoreenabled' => true,
      'appstoreurl' => 'https://api.owncloud.com/v1',
      'apps_paths' => array(
              array(
                      'path'=> '/media/www_owncloud/apps',
                      'url' => '/apps',
                      'writable' => true,
              ),
      ),

but this didn't solve the problem.

**Comment by rakekniven** [comment]
More users have the same problem. See forum thread https://forum.owncloud.org/viewtopic.php?f=31&t=26314&start=10

**Comment by DeepDiver1975** [comment]
> Error core Archive vom Typ werden nicht unterstützt 2015-02-11T08:49:24+00:00

looks like the archive cannot be unzipped ...

**Comment by DeepDiver1975** [comment]
we require zip support in php:

```
$ php --info | grep zip

**Comment by Killer1337** [comment]
This is the output:

    # php --info | grep zip

    Registered PHP Streams => https, ftps, compress.zlib, compress.bzip2, php, file, glob, data, http, ftp, zip, phar
    Registered Stream Filters => zlib.*, bzip2.*, convert.iconv.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk
    Stream Wrapper support => compress.bzip2://
    Stream Filter support => bzip2.decompress, bzip2.compress
    gzip compression => enabled
    bzip2 compression => enabled
    zip
    Libzip version => 0.10.1

**Comment by Killer1337** [comment]
Ok, I resolved the issue! In my php.ini I changed the default line

`upload_tmp_dir = /media/data`

to a directory that actually exists and that my nginx user has access to. Guess that makes sense ;)

Is this directory used by the zip module and was not needed before 8.0?

**Comment by VicDeo** [comment]
@Killer1337 most likely it is used as a temporary dir while downloading a package
`upload_tmp_dir` value is the first candidate for that:
https://github.com/owncloud/core/blob/master/lib/base.php#L992

**Comment by Killer1337** [comment]
Thanks for clearifying!
