### ISSUE TITLE
Add various additional dependencies to core and apps

### ISSUE THREAD

**Issue by ghost** [owncloud/core#14092]
Hi,

within the PR https://github.com/owncloud/apps/pull/1905 i've done some work and collected all dependencies from the documentation at http://doc.owncloud.org/server/8.0/admin_manual/installation/source_installation.html#prerequisites

It might be useful that a more experienced user/dev have a look at this and add the missing dependencies to either the https://github.com/owncloud/core/blob/v8.0.0/lib/private/util.php#L570-L595 for core stuff or the new dependency of core apps.

Additional it could be useful to check for disabled PHP functions like "shell_exec", "exec", "escapeshellcmd" and "escapeshellarg" which are often on the "disabled_function" list of PHP.

**Comment by RealRancor** [comment]
Some examples:

core:
- php-curl (or curl_init and curl_exec functions)
- php-fileinfo
- php-intl (or Class Collator)
- php-imagick (or Class Imagick)
- shell_exec, exec, escapeshellcmd and escapeshellarg, disk_free_space
- ffmpeg or iconv binary
- ini_set and set_time_limit
- grep binary

files_encryption:
- php-mcrypt (or function mcrypt_cbc)

files_external:
- php-ftp (or function ftp_alloc)
- php-gmp (or function gmp_abs)

user_external:
- php-imap (or function imap_8bit)

**Comment by karlitschek** [comment]
Very good idea. ownCloud should detect missing dependencies and warn correctly.
@VicDeo Can you help with that?

**Comment by DeepDiver1975** [comment]
> Very good idea. ownCloud should detect missing dependencies and warn correctly.

this is already on my list for app management improvments

**Comment by RealRancor** [comment]
Just had another look at the dependency list i've posted above. Some of them like "php-imap" or "php-ftp" are no direct hard dependencies which makes the app completely unusable. They are more soft dependencies or recommendations.

**Comment by RealRancor** [comment]
Moved the discussion about the user_external app dependencies from https://github.com/owncloud/documentation/issues/1149 here:

> well - this is now the big question:
>
>- hard dependency on all?
>- soft dependency on all? (which is not implemented in core and kind of pointless as one could still install and use an app even if soft dependencies are missing)
> - split the app into 3 individual apps (what about the base class then)

**Comment by szepeviktor** [comment]
After a bit of struggle I've found that allow_url_fopen was off for security reasons but External Storage backends needed it.

Please consider checking it with ini_get().

**Comment by PVince81** [comment]
Already possible, not sure since which version. info.xml can specify lib + version dependencies.

@DeepDiver1975 if you have more info, please add.

Closing
