### ISSUE TITLE
search parameter explanation of the occ ldap:search command is misleading

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#14093]
According to the help of the command, the search parameter is a search string. I expect to use as parameter something like `"(sn=sm*)"` or `"(&(objectCategory=person)(objectClass=user)(!cn=andy))"` but this is not working.

Since the search uses a set predefined fields (configurable from the wizard) with a fallback to displayName, it would be better to clarify this in the help

**Comment by PVince81** [comment]
Please reopen in user_ldap repo if still relevant and important
