### ISSUE TITLE
Sharing folders with users of 1 character isn't an option.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#14095]
### Steps to reproduce

Having a user of 1 character 'n' for example and other user called user2.

1. Using user2 try to share a folder with n.

### Expected behaviour
You can share folders with n.

### Actual behaviour
You need to type two characters to show the list of users for sharing.

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.0.0.6","versionstring":"8.0 RC 2","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
none

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** no

### Client configuration
Chrome.

**Comment by PVince81** [comment]
It is very likely that this was done on purpose to avoid a huge load on servers that have too many users.

@blizzz

**Comment by SergioBertolinSG** [comment]
@PVince81 the problem is that users with 1 char can be created but other users can't share folders with them.
So from my point of view: 
Option 1: Forbid the creation of users <2 chars. (May lead to upgrade problems if that kind of users existed before)
Option 2: Allow to stroke return and share, without waiting to the list of users (Now hitting return doesn't work either).
Option 3: Show list with first character (Hugh load).

**Comment by PVince81** [comment]
@owncloud/designers @MTRichards @LukasReschke

**Comment by blizzz** [comment]
Yes, that's on purpose. We could make it flexible i.e. configurable in the admin settings.

**Comment by jancborchardt** [comment]
I was under the impression that it was only the as-you-type suggestions which need at least 2 characters to work. Of course if you just put in one character and there is a user with that exact name, sharing should work.

**Comment by jancborchardt** [comment]
What is there to make configurable? If someone puts in »n« in the share input, presses enter, and ownCloud notes there is a user called »n« – just share it.

**Comment by PVince81** [comment]
If display names are chinese characters it might become problematic.
Chinese names usually contain mostly three characters, for example 李小龙, so typing a single one 李 (usually the family name) might be common practice.
A similar issue was raised for the file search https://github.com/owncloud/core/issues/9916

**Comment by PVince81** [comment]
CC @dttpy @kkyang

**Comment by vgezer** [comment]
@PVince81 Chinese characters are multibyte characters. So if you check the size of the string, this might help. Just as a side note...

You can test it here: https://mothereff.in/byte-counter

**Comment by cmonteroluque** [comment]
This bug will fall off 8.2 if not resolved by 6 Oct

**Comment by PVince81** [comment]
See @jancborchardt's comment here https://github.com/owncloud/core/issues/12431#issuecomment-85123883

**Comment by PVince81** [comment]
If backends support it and don't explode with too many results, we could change the minimum to 1...

@blizzz @rullzer @schiesbn ?

**Comment by rullzer** [comment]
I think we can safely do this as we limit the number of result in the shareeAPI anyway...
I'll take care of this.

**Comment by blizzz** [comment]
> If backends support it and don't explode with too many results, we could change the minimum to 1...

Tricky. Could start time taking LDAP request on big directories. OTOH, since we limit the result set, it's probably not that bad (as long as sharing is not limited to group memberships, this is expensive). Important is that there is a long enough delay until the search is actually triggered.
