### ISSUE TITLE
Connecting Owncloud with OpenLdap

### ISSUE THREAD

**Issue by NewComer15** [owncloud/core#14096]
Hello guys,
i added a ldap connection.
This connection should import all users and groups of a schoolserver.
But at this time the connection is not importing all users.
The groups are all importet but the connections between the groups and users are buggy.
Sometimes the users are in the groups and sometimes in no group?!

![Here u can see how it looks](https://cloud.githubusercontent.com/assets/10957051/6145602/d6ec544e-b1e3-11e4-80d8-c17b16c97bf1.png)

**Comment by karlitschek** [comment]
@blizzz any idea?

**Comment by blizzz** [comment]
@NewComer15 can you please complete this bug report using the template: https://raw.github.com/owncloud/core/master/issue_template.md

Additionally to what is stated there, the LDAP configuration would be useful. You can get it from command line by running ```./occ ldap:show-config``` as your web user.

**Comment by NewComer15** [comment]
@blizzz @karlitschek 
This problem is fixxed i had the wrong group filter.

And i downloaded oc 8 now.

But i have a problem, at the ldap plugin i see only  337 Users. The schoolserver have around 1000 users.
At the oc log 


### Steps to reproduce
1. What u mean with point=

### Expected behaviour
I should see all 1000 Users in the LDAP Plugin and at the Userview of OC 8

### Actual behaviour
at the ldap plugin i see only  337 Users. The schoolserver have around 1000 users.
At the Userview is see the users at the group list but they are not imported.
(Look at the screen bellow)
![Userview](https://cloud.githubusercontent.com/assets/10957051/6163270/0c28404e-b290-11e4-93bf-c5e0598b17c6.png)

At the oc look i see that there is a error -> Sizelimit

Debug	user_ldap	getGroups(): read 102 at offset (limit: 1500)	2015-02-12T08:16:28+00:00
Debug	user_ldap	getGroups getGroups--1500-	2015-02-12T08:16:28+00:00
Debug	user_ldap	Requested attribute primarygroupid not found for uid=bf1ho14baum,ou=users,dc=userbase,dc=universe	2015-02-12T08:13:14+00:00
Debug	user_ldap	Ready for a paged search	2015-02-12T08:13:14+00:00
Debug	user_ldap	initializing paged search for Filter objectClass=* base Array ( [0] => uid=bf1ho14baum,ou=users,dc=userbase,dc=universe ) attr Array ( [0] => primaryGroupID ) limit 1500 offset 0	2015-02-12T08:13:14+00:00
Debug	user_ldap	Requested attribute primarygroupid not found for uid=bsegs14christmann,ou=users,dc=userbase,dc=universe	2015-02-12T08:13:14+00:00
Debug	user_ldap	Ready for a paged search	2015-02-12T08:13:14+00:00
Debug	user_ldap	initializing paged search for Filter objectClass=* base Array ( [0] => uid=bsegs14christmann,ou=users,dc=userbase,dc=universe ) attr Array ( [0] => primaryGroupID ) limit 1500 offset 0	2015-02-12T08:13:14+00:00
Debug	user_ldap	Requested attribute primarygroupid not found for uid=hbfso14bstrasheim,ou=users,dc=userbase,dc=universe	2015-02-12T08:13:14+00:00
Debug	user_ldap	Ready for a paged search	2015-02-12T08:13:14+00:00
Debug	user_ldap	initializing paged search for Filter objectClass=* base Array ( [0] => uid=hbfso14bstrasheim,ou=users,dc=userbase,dc=universe ) attr Array ( [0] => primaryGroupID ) limit 1500 offset 0	2015-02-12T08:13:14+00:00
Debug	user_ldap	Requested attribute primarygroupid not found for uid=dbos14weber,ou=users,dc=userbase,dc=universe	2015-02-12T08:13:14+00:00
Debug	user_ldap	Ready for a paged search

I edited the size limit to 1500 as u can see but nothing happens.

### Server configuration

**Operating system**:
Ubuntu 14 Serverversion

**Web server:**
Apache2

**Database:**
Mysql

**PHP version:**
5.6

**ownCloud version:** (see ownCloud admin page)
8

**Updated from an older ownCloud or fresh install:**
Fresh install

**List of activated apps:**
Added is only see ldap plugin

**The content of config/config.php:**
![cnfig](https://cloud.githubusercontent.com/assets/10957051/6163328/e116d22a-b290-11e4-8cf4-1f52b94821a4.png)


**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

### Client configuration
Firefox/Chromium

**Operating system:**
Ubuntu 14.04. Grafikinterface
### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
The log is too long so, only the last lines

http://pastebin.com/5013eMCn

#### Browser log
```
Insert your browser log here, this could for example include:
It is not a borwser porblem..

**Comment by NewComer15** [comment]
Why u closed this

**Comment by blizzz** [comment]
@NewComer15 

In "Steps to reproduce" write please step by step to how you end up with the issue.

The log you pasted to pastebin seems to be outdated. The entries there are older than you posted here directly.

The sizelimit is not your problem. However, ensure that the newly set 1500 is smaller then the (soft) limit of your OpenLDAP olcSizeLimit configuration.

I suspect that the configured display name attribute does not exist on every of your user accounts. Please revise the according setting in the Advanced tab.

**Comment by NewComer15** [comment]
@blizzz 


Till now i only edited at the ldap plugin the paging chunksize too 1500

This is the acutally log (Idk why the time of my vm switched again -.-)


Debug	user_ldap	Requested attribute primarygroupid not found for uid=hbfit14gonzalez,ou=users,dc=userbase,dc=universe	2015-02-12T10:34:54+00:00
Debug	user_ldap	Ready for a paged search	2015-02-12T10:34:54+00:00
Debug	user_ldap	initializing paged search for Filter objectClass=* base Array ( [0] => uid=hbfit14gonzalez,ou=users,dc=userbase,dc=universe ) attr Array ( [0] => primaryGroupID ) limit 1500 offset 0	2015-02-12T10:34:54+00:00
Debug	user_ldap	Requested attribute primarygroupid not found for uid=hbfit14okur,ou=users,dc=userbase,dc=universe	2015-02-12T10:34:54+00:00
Debug	user_ldap	Ready for a paged search	2015-02-12T10:34:54+00:00
Debug	user_ldap	initializing paged search for Filter objectClass=* base Array ( [0] => uid=hbfit14okur,ou=users,dc=userbase,dc=universe ) attr Array ( [0] => primaryGroupID ) limit 1500 offset 0	2015-02-12T10:34:54+00:00
Debug	user_ldap	Requested attribute primarygroupid not found for uid=hbfit14matheis,ou=users,dc=userbase,dc=universe	2015-02-12T10:34:54+00:00
Debug	user_ldap	Ready for a paged search	2015-02-12T10:34:54+00:00
Debug	user_ldap	initializing paged search for Filter objectClass=* base Array ( [0] => uid=hbfit14matheis,ou=users,dc=userbase,dc=universe ) attr Array ( [0] => primaryGroupID ) limit 1500 offset 0	2015-02-12T10:34:54+00:00
Debug	user_ldap	Requested attribute primarygroupid not found for uid=bsit13feindel,ou=users,dc=userbase,dc=universe	2015-02-12T10:34:54+00:00
Debug	user_ldap	Ready for a paged search	2015-02-12T10:34:54+00:00
Debug	user_ldap	initializing paged search for Filter objectClass=* base Array ( [0] => uid=bsit13feindel,ou=users,dc=userbase,dc=universe ) attr Array ( [0] => primaryGroupID ) limit 1500 offset 0	2015-02-12T10:34:54+00:00
Debug	user_ldap	Requested attribute primarygroupid not found for uid=hbfit14schlechte,ou=users,dc=userbase,dc=universe	2015-02-12T10:34:54+00:00
Debug	user_ldap	Ready for a paged search	2015-02-12T10:34:54+00:00
Debug	user_ldap	initializing paged search for Filter objectClass=* base Array ( [0] => uid=hbfit14schlechte,ou=users,dc=userbase,dc=universe ) attr Array ( [0] => primaryGroupID ) limit 1500 offset 0	2015-02-12T10:34:54+00:00
Debug	user_ldap	Requested attribute primarygroupid not found for uid=hbfit14hirsch,ou=users,dc=userbase,dc=universe	2015-02-12T10:34:54+00:00
Debug	user_ldap	Ready for a paged search	2015-02-12T10:34:54+00:00
Debug	user_ldap	initializing paged search for Filter objectClass=* base Array ( [0] => uid=hbfit14hirsch,ou=users,dc=userbase,dc=universe ) attr Array ( [0] => primaryGroupID ) limit 1500 offset 0	2015-02-12T10:34:54+00:00
Debug	user_ldap	Requested attribute primarygroupid not found for uid=hbfit14bannasch,ou=users,dc=userbase,dc=universe	2015-02-12T10:34:54+00:00
Debug	user_ldap	Ready for a paged search	2015-02-12T10:34:54+00:00
Debug	user_ldap	initializing paged search for Filter objectClass=* base Array ( [0] => uid=hbfit14bannasch,ou=users,dc=userbase,dc=universe ) attr Array ( [0] => primaryGroupID ) limit 1500 offset 0	2015-02-12T10:34:54+00:00


->The sizelimit is not your problem. However, ensure that the newly set 1500 is smaller then the (soft) limit of your OpenLDAP olcSizeLimit configuration.
Is this olcSizeLimit on the school server or at my vm where my owncloud is installed?



What should i chooose 
![cnfig](https://cloud.githubusercontent.com/assets/10957051/6165899/dd23a5ce-b2ab-11e4-8a44-bd3e41cbc047.png)

**Comment by blizzz** [comment]
>> ->The sizelimit is not your problem. However, ensure that the newly set 1500 is smaller then the (soft) limit of your OpenLDAP olcSizeLimit configuration.

> Is this olcSizeLimit on the school server or at my vm where my owncloud is installed?

As written, this is an OpenLDAP server configuration.

> What should i chooose 

Well, this is something you should know, or your LDAP administrator :) You can try with "cn" or "uid". 

> Additionally to what is stated there, the LDAP configuration would be useful. You can get it from command line by running ./occ ldap:show-config as your web user.

This still might be useful. More info on occ: http://doc.owncloud.org/server/8.0/admin_manual/configuration/occ_command.html

Your log says everything is fine. It's just a configuration issue.

**Comment by NewComer15** [comment]
But i have installed openldap on my vm too. i thought i would need it for the connection to the schooolserver..
so i most say the schoolserveradmin to set the olcsiezlimt.

oke i will try it at the evening and write u then


what do u need of the occ ?

cya

**Comment by blizzz** [comment]
Please read my comments carefully. The olcsiezlimt does not need to be changed, but your set up sizelimit must not exceed this. In doubt, leave it at 500, that's fine. occ command is stated above.

**Comment by NewComer15** [comment]
Here u can see the ldap config: http://pastebin.com/415Br2tg

But tbh i dont understand the problem with the size..

Should i change the 1500 to 500 again or what should i do :/

@blizzz

**Comment by blizzz** [comment]
@NewComer15 yes, put it back to 500. Use "cn"  as user display name.

You should also rework your User and Login Filter (learn about LDAP Filters, read ownCloud LDAP doc). If questions arise use the [User Mailing List](https://mailman.owncloud.org/mailman/listinfo/user) or the [Forum](http://forum.owncloud.org/) as a proper place for questions and help.
