### ISSUE TITLE
offset parameter of the occ ldap:search command doesn't work with the group option

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#14098]
### Steps to reproduce
1. Set a valid ldap configuration with several groups. Make sure you have enough groups
2. Run `./occ ldap:search --group --limit=3 ''`. This should show the first 3 groups.
3. Run `./occ ldap:search --group --offset=3 --limit=3 ''`

### Expected behaviour
The command should show the next 3 groups

### Actual behaviour
Nothing happens

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** sqlite3

**PHP version:** 5.5.9

**ownCloud version:** ownCloud 7.0.5 RC1 (testing) 

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by blizzz** [comment]
confirmed

**Comment by jvillafanez** [comment]
checked for stable7 :+1:
