### ISSUE TITLE
After Update to 8: Syncing via CardDAV- or CalDAV-Link doesn't work anymore

### ISSUE THREAD

**Issue by Phillinger** [owncloud/core#14104]
Running owncloud on Debian 7.0. Updating owncloud 7 to 8 via repository http://download.opensuse.org/repositories/isv:ownCloud:community/Debian_7.0/ ran flawlessly.

Syncing contacts and calendar via CardDAV- or CalDAV-Link doesn't work anymore.

Owncloud runs under 'https://mydomain.org/owncloud'.

In the access.log of the apache2 the request shows up as follows:
 "PROPFIND /owncloud/remote.php/carddav/addressbooks/20...2/kontakte/ HTTP/1.1" 207 410 "-" "CardDAV-Sync (Android) (like iOS/5.0.1 (9A405) dataaccessd/1.0) gzip"
which seems correct (disguised ID in URL).

But in error.log in shows up as follows:
script '/var/www/mydomain.org/groupdav.php' not found or unable to stat
script '/var/www/mydomain.org/remote.php' not found or unable to stat

So the folder "owncloud" isn't present anymore in the calling URL. To my understanding, it should call the script under '/var/www/mydomain.org/owncloud/groupdav.php'.

Even deactivating Contacts- and Calendar-App and activating Contacts 8.0 and Calendar 8.0 app didn't fix it.

**Comment by PVince81** [comment]
Did you add any custom rewrite rules or are using old style URLs ?

AFAIK you should use the URL "https://mydomain.org/owncloud/remote.php/caldav" and "https://mydomain.org/owncloud/remote.php/carddav" from your clients.

**Comment by Phillinger** [comment]
I have an rewrite rule in my VirtualHost-section to redirect anything from http to https:

<code>RedirectMatch ^/(.*)$ https://mydomain.org/$1</code>

This worked very well with owncloud 7 all the time.

I found another configuration, added by owncloud-setup in /etc/apache2/conf.d/owncloud.conf:

<code>Alias /owncloud "/var/www/owncloud/"</code>
<code>\<Directory "/var/www/owncloud"></code>
<code>    Options +FollowSymLinks</code>
<code>    AllowOverride All</code>
<code>\</Directory></code>


This seems correct to me.


What do you mean with old style URLs?

**Comment by markgraf** [comment]
Same issue here. Though I have my owncloud rewritten to https://owncloud.fragkram.de/ forcing https as indicated in the apache documentation:

	RewriteEngine On
	# This will enable the Rewrite capabilities
	RewriteCond %{HTTPS} !=on
	# This checks to make sure the connection is not already HTTPS
	RewriteRule /?(.*) https://%{SERVER_NAME}/$1 [R,L]
	# This rule will redirect users from their original location, to the same location but using HTTPS.
	# i.e.  http://www.example.com/foo/ to https://www.example.com/foo/
	# The leading slash is made optional so that this will work either in httpd.conf
	# or .htaccess context

**Comment by Phillinger** [comment]
This one can be closed. See solution in #14275.
