### ISSUE TITLE
previews broken for non-supported file types

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#14106]
Affected: owncloud 7, ownCloud 8 and master

I tried this with the versions drop-down but it affects all previews we create.
The versions drop down shows previews for all supported files. But if you open the version dop-down for a file for which we can't create a preview, e.g. a odt file, the preview will be broken.

![snapshot1](https://cloud.githubusercontent.com/assets/1589737/6147451/febd36be-b1f7-11e4-8eeb-15c62da43d80.png)

I think the preview lib should always return a useful image and fall-back to the mime-icon if it can't create a preview from the file content.

@georgehrke what do you think? Can you have a look at it?

**Comment by georgehrke** [comment]
> I think the preview lib should always return a useful image and fall-back to the mime-icon if it can't create a preview from the file content.

I guess this will be fixed with @oparoz 's pr: https://github.com/owncloud/core/pull/12546

concerning versions: can you please respond to https://github.com/owncloud/core/issues/10559

**Comment by schiesbn** [comment]
@georgehrke great, sounds like the PR will fix the issue!

**Comment by schiesbn** [comment]
will be fixed with https://github.com/owncloud/core/pull/12546

**Comment by PVince81** [comment]
https://github.com/owncloud/core/pull/12546 seems to have issues, so unlikely to be finished for 8.1.

Defer to 8.2 ?

**Comment by PVince81** [comment]
issues as in "API-breaking issues" and might need a full rethink.

**Comment by oparoz** [comment]
No, no, no, it's the mobile clients who have issues and don't check what they're receiving ;). This could one day play tricks on them, but I'm going to be nice and modify the PR in order to please every one.

**Comment by georgehrke** [comment]
@oparoz Do you want to add the empty space around the actual preview?

**Comment by oparoz** [comment]
Around the mime icon, yes, as a stop-gap measure. The only clients which will get them are the mobile clients.
