### ISSUE TITLE
occ ldap:check-user reports that the user doesn't exists with disabled configuration, even forcing

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#14103]
### Steps to reproduce
1. Create a valid ldap configuration.
2. Run `./occ ldap:check-user <userId>` and verify that the user exists in LDAP (success message should be shown)
3. Disable all configurations and rerun the same command in step 2. (expect an error message since there are disabled configurations)
4. Rerun same command than the step 2 with the "--force" option `./occ ldap:check-user --force <userId>`

### Expected behaviour
It should show a success message since the user is still there, even though the configuration is disabled

### Actual behaviour
It's no longer detected as present. In addition, if the configuration is enabled again, the user will still be detected as deleted, but the user is still present in the ldap directory

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** sqlite3

**PHP version:** 5.5.9

**ownCloud version:** ownCloud 7.0.5 RC1 (testing) 

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by jvillafanez** [comment]
OC 8.0.0 has the same behaviour.

**Comment by karlitschek** [comment]
@blizzz Can you have a look?

**Comment by blizzz** [comment]
No, if the LDAP server is disabled, ownCloud will *not* connect to them. The check-user command will not try to check the user if a disabled LDAP configuration is found. If you use --force, then all active one's will be checked. Thus, it works as intended. 

What i see is that the switch is not documented. cc @carlaschroder

**Comment by carlaschroder** [comment]
https://github.com/owncloud/documentation/commit/7e4c48c0caddb6e1fef8d72935e5737713dafd7f

**Comment by blizzz** [comment]
@carlaschroder the optional  --force flag is missing there. 

Without it the check will only be done, if there are no disabled LDAP configurations, because we cannot be share to falsely mark a user as deleted, because the LDAP is not available. The admin can specify --force to let the check run against the enabled servers, given that he knows the the user he is checking is definitely not belongs to any of the disabled LDAP configs.

**Comment by jnfrmarks** [comment]
@jvillafanez @blizzz @carlaschroder 

Can this be closed?

**Comment by carlaschroder** [comment]
Now it can be closed. ``--force`` flag added to 8.x docs:
https://github.com/owncloud/documentation/commit/93a19c655ee32cb33d7103d90294c0e11379ca17
https://github.com/owncloud/documentation/commit/6c5e8014f66b7ee2abec70afacb49b7d69f967fb

**Comment by jvillafanez** [comment]
:+1:
