### ISSUE TITLE
apache should run without mod_dav

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#14109]
Currently we have e.g. on CentOS6_php54 the following modules loaded per default:
&lt;?php phpinfo(); ?&gt;

Loaded Modules 	core prefork http_core mod_so mod_auth_basic mod_auth_digest mod_authn_file mod_authn_alias mod_authn_anon mod_authn_dbm mod_authn_default mod_authz_host mod_authz_user mod_authz_owner mod_authz_groupfile mod_authz_dbm mod_authz_default util_ldap mod_authnz_ldap mod_include mod_log_config mod_logio mod_env mod_ext_filter mod_mime_magic mod_expires mod_deflate mod_headers mod_usertrack mod_setenvif mod_mime mod_dav mod_status mod_autoindex mod_info mod_dav_fs mod_vhost_alias mod_negotiation mod_dir mod_actions mod_speling mod_userdir mod_alias mod_substitute mod_rewrite mod_proxy mod_proxy_balancer mod_proxy_ftp mod_proxy_http mod_proxy_ajp mod_proxy_connect mod_cache mod_suexec mod_disk_cache mod_cgi mod_version mod_php5

The mod_dav module is there. If we run with 'Dav on'  enabled, owncloudcmd fails like this:

<pre>
02/11 15:27:32.837777, 9] oc_module:  fetch_resource_list_recursive Starting recursive propfind owncloud://monkey:88/owncloud/remote.php/webdav /owncloud/remote.php/webdav
[02/11 15:27:32.879841, 9] oc_module:  Neon error code was 1
[02/11 15:27:32.879886, 9] oc_module:  WRN: propfind named failed with 1, request error: 400 Bad Request
[02/11 15:27:32.879920, 9] oc_module:  fill_recursive_propfind_cache /owncloud/remote.php/webdav Server maybe did not give us an 'infinity' depth result
[02/11 15:27:32.879932, 9] oc_module:  get_listdir_context_from_recursive_cache No cache
[02/11 15:27:32.890488, 9] oc_module:  Neon error code was 1
[02/11 15:27:32.890543, 9] oc_module:  Neon error code was 1
[02/11 15:27:32.890566, 9] oc_module:  WRN: propfind named failed with 1, request error: 400 Bad Request
[02/11 15:27:32.890599, 9] oc_module:  Errno set to 22
[02/11 15:27:32.890619, 4] csync_ftw:  opendir failed for owncloud://monkey:88/owncloud/remote.php/webdav - errno 22
[02/11 15:27:32.890787, 6] csync_statedb_close:  sqlite3_close=0
 #### ERROR during  csync_update :  "CSync fatal parameter error. 400 Bad Request" 
</pre>

Better enforce 'Dav off' in /etc/httpd/conf.d/owncloud.conf

    Alias /owncloud "/var/www/html/owncloud/"
    <Directory "/var/www/html/owncloud">
        Options +FollowSymLinks
        AllowOverride All
        <IfModule mod_dav.c>
            Dav off
        </IfModule>
    </Directory>

**Comment by jnweiger** [comment]
@cdamken @dragotin  this is different from your dav issue, right?

**Comment by cdamken** [comment]
@jnweiger  http://doc.owncloud.com/server/7.0EE/admin_manual/installation/installation_source.html

**Comment by jnweiger** [comment]
http://doc.owncloud.com/server/8.0EE/admin_manual/installation/source_installation.html

**Comment by jnweiger** [comment]
Potential fix submitted to isv:ownCloud:community:testing/owncloud
Does not yet build.

**Comment by DeepDiver1975** [comment]
Can this be set in htaccess as well?

**Comment by jnweiger** [comment]
@deepdivee1975 I dont think so. The docs only mention httpd.conf and I got 'not allowed here' errors when I tried it in my htaccess. It must be inside a Location container.

**Comment by DeepDiver1975** [comment]
we shall add this to the docs as well @carlaschroder

**Comment by enoch85** [comment]
@jnweiger Will this happen with the 8.0.3 package?

**Comment by carlaschroder** [comment]
The admin manual already says to not use mod_dav with ownCloud, and shows an example for disabling it for ownCloud only. I'm not sure what you want here.

**Comment by jnweiger** [comment]
Since 8.0.3 we have 
<pre>
    <IfModule mod_dav.c>
      Dav off
    </IfModule>
</pre>

in our owncloud.conf -- this should fix the issue.
