### ISSUE TITLE
Node API horrible slow with files_locking

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#14107]
Filing here since not sure if this is an issue in core or the files_locking application, but it's a PRETTY annoying bug anyways…

The following test script creates 100 test files. Without enabled files_locking application the reading of the files requires roughly 400ms, with enabled application it takes more than 5.5 seconds! See https://blackfire.io/profiles/compare/31c8f164-4086-426f-924e-41210fd6197a/graph for a comparison view.

```php
<?php


require_once('./lib/base.php');

$randomFolderName = \OC::$server->getSecureRandom()->getLowStrengthGenerator()->generate(
	5, \OCP\Security\ISecureRandom::CHAR_LOWER
);

\OC_User::createUser($randomFolderName, 'admin');

for ($i = 1; $i <= 100; $i++) {
	mkdir('./data/'.$randomFolderName);
	mkdir('./data/'.$randomFolderName.'/files/');
	mkdir('./data/'.$randomFolderName.'/files/'.$randomFolderName);
	file_put_contents('./data/'.$randomFolderName.'/files/'.$randomFolderName.'/'.$i.'.txt', 'asdf');
}


$time1 = microtime(true);

$view = new \OC\Files\View('/'.$randomFolderName.'/files/');
$files = $view->getDirectoryContent($randomFolderName);

$rootFolder = \OC::$server->getUserFolder($randomFolderName);
$files = $rootFolder->get($randomFolderName)->getDirectoryListing();
foreach($files as $file) {
	if($file->getType() === 'file' && $file->getMimeType() === 'text/plain') {
		$file->getContent();
	}
}

$time2 = microtime(true);
echo "script execution time: ".($time2-$time1);
```
This is a valid use-case and already performed by applications such as the widely used notes app. Reading some small text files should certainly not take that long.

I'm pretty sure we have huge other performance problems as well due to the files_locking application.
 
cc @DeepDiver1975 That's the bug that I referred to in IRC.
cc @icewind1991 Could you take a look at this? THX!

**Comment by oparoz** [comment]
Media apps are affected as they need to read hundreds of files quickly and sometimes write at the same time.

**Comment by LukasReschke** [comment]
Yep… Funny break things like https://forum.owncloud.org/viewtopic.php?f=31&t=26790… Totally awesome…

**Comment by oparoz** [comment]
Looking at the error log posted, I'm wondering if that might be because thumbnails are not in a standard location. That could be a separate bug, once I can investigate. Maybe the File Locking app is expecting an encrypted file if the cloud is encrypted, but thumbnails are not.

**Comment by icewind1991** [comment]
Fixed with https://github.com/owncloud/files_locking/pull/13
