### ISSUE TITLE
Updateer.php patch creates WSOD after completing the process

### ISSUE THREAD

**Issue by bboule** [owncloud/core#14101]
Having an issue with a user upgrading from 6.0.6 to 7.0.4 losing files and shares post upgrade.  We have recreated the situation in a non-production environment.  I have taken the following steps to attempt to fix the situation:

1.  Apply the following https://github.com/owncloud/core/pull/13865
2.  Apply the following https://github.com/owncloud/core/pull/13759.patch
3.  ) delete bogus "local::" entries from oc_storages (make sure to be in maintenance mode the whole time of course)  
4. edit oc_appconfig and reduce the version of files_sharing  so on the table roll the version of this app back from 0.5.3 to 0.3.5
5. Run Upgrade again

The result of this is that all files and shares appear to come back the way they should, however, when I attempt to login as one of the LDAP users I am able to get to the login screen post login when it attempt to load the files app I get a white screen.  I have reverted back to the original updater.php (rolling back the file applied in step one) and I am then able to login again and can see all files!!

Here is a snippet from the logs when attempting to login:

{"app":"PHP","message":"Missing argument 2 for OC\\Updater::__construct(), called in \/var\/www\/owncloud\/lib\/private\/legacy\/updater.php on line 11 and defined at \/var\/www\/owncloud\/lib\/private\/updater.php#46","level":3,"time":"2015-02-10T21:56:52+00:00"}
{"app":"PHP","message":"Undefined variable: httpHelper at \/var\/www\/owncloud\/lib\/private\/updater.php#47","level":3,"time":"2015-02-10T21:56:52+00:00"}
{"app":"PHP","message":"Undefined variable: config at \/var\/www\/owncloud\/lib\/private\/updater.php#49","level":3,"time":"2015-02-10T21:56:52+00:00"}
{"app":"PHP","message":"Call to a member function getValue() on a non-object at \/var\/www\/owncloud\/lib\/private\/updater.php#84","level":3,"time":"2015-02-10T21:56:52+00:00"}
{"app":"PHP","message":"PHP Startup: Unable to load dynamic library '\/usr\/lib\/php5\/20090626\/mysqlnd.so' - \/usr\/lib\/php5\/20090626\/mysqlnd.so: cannot open shared object file: No such file or directory at Unknown#0","level":3,"time":"2015-02-10T21:57:00+00:00"}
{"app":"PHP","message":"Missing argument 1 for OC\\Updater::__construct(), called in \/var\/www\/owncloud\/lib\/private\/legacy\/updater.php on line 11 and defined at \/var\/www\/owncloud\/lib\/private\/updater.php#46","level":3,"time":"2015-02-10T21:57:00+00:00"}
{"app":"PHP","message":"Missing argument 2 for OC\\Updater::__construct(), called in \/var\/www\/owncloud\/lib\/private\/legacy\/updater.php on line 11 and defined at \/var\/www\/owncloud\/lib\/private\/updater.php#46","level":3,"time":"2015-02-10T21:57:00+00:00"}
{"app":"PHP","message":"Undefined variable: httpHelper at \/var\/www\/owncloud\/lib\/private\/updater.php#47","level":3,"time":"2015-02-10T21:57:00+00:00"}
{"app":"PHP","message":"Undefined variable: config at \/var\/www\/owncloud\/lib\/private\/updater.php#49","level":3,"time":"2015-02-10T21:57:00+00:00"}
{"app":"PHP","message":"Call to a member function getValue() on a non-object at \/var\/www\/owncloud\/lib\/private\/updater.php#84","level":3,"time":"2015-02-10T21:57:00+00:00"}
{"app":"PHP","message":"PHP Startup: Unable to load dynamic library '\/usr\/lib\/php5\/20090626\/mysqlnd.so' - \/usr\/lib\/php5\/20090626\/mysqlnd.so: cannot open shared object file: No such file or directory at Unknown#0","level":3,"time":"2015-02-10T21:57:31+00:00"}
{"app":"PHP","message":"Missing argument 1 for OC\\Updater::__construct(), called in \/var\/www\/owncloud\/lib\/private\/legacy\/updater.php on line 11 and defined at \/var\/www\/owncloud\/lib\/private\/updater.php#46","level":3,"time":"2015-02-10T21:57:31+00:00"}
{"app":"PHP","message":"Missing argument 2 for OC\\Updater::__construct(), called in \/var\/www\/owncloud\/lib\/private\/legacy\/updater.php on line 11 and defined at \/var\/www\/owncloud\/lib\/private\/updater.php#46","level":3,"time":"2015-02-10T21:57:31+00:00"}
{"app":"PHP","message":"Undefined variable: httpHelper at \/var\/www\/owncloud\/lib\/private\/updater.php#47","level":3,"time":"2015-02-10T21:57:31+00:00"}
{"app":"PHP","message":"Undefined variable: config at \/var\/www\/owncloud\/lib\/private\/updater.php#49","level":3,"time":"2015-02-10T21:57:31+00:00"}
{"app":"PHP","message":"Call to a member function getValue() on a non-object at \/var\/www\/owncloud\/lib\/private\/updater.php#84","level":3,"time":"2015-02-10T21:57:31+00:00"}
{"app":"PHP","message":"PHP Startup: Unable to load dynamic library '\/usr\/lib\/php5\/20090626\/mysqlnd.so' - \/usr\/lib\/php5\/20090626\/mysqlnd.so: cannot open shared object file: No such file or directory at Unknown#0","level":3,"time":"2015-02-10T21:57:45+00:00"}
{"app":"PHP","message":"Missing argument 1 for OC\\Updater::__construct(), called in \/var\/www\/owncloud\/lib\/private\/legacy\/updater.php on line 11 and defined at \/var\/www\/owncloud\/lib\/private\/updater.php#46","level":3,"time":"2015-02-10T21:57:45+00:00"}
{"app":"PHP","message":"Missing argument 2 for OC\\Updater::__construct(), called in \/var\/www\/owncloud\/lib\/private\/legacy\/updater.php on line 11 and defined at \/var\/www\/owncloud\/lib\/private\/updater.php#46","level":3,"time":"2015-02-10T21:57:45+00:00"}
{"app":"PHP","message":"Undefined variable: httpHelper at \/var\/www\/owncloud\/lib\/private\/updater.php#47","level":3,"time":"2015-02-10T21:57:45+00:00"}
{"app":"PHP","message":"Undefined variable: config at \/var\/www\/owncloud\/lib\/private\/updater.php#49","level":3,"time":"2015-02-10T21:57:45+00:00"}
{"app":"PHP","message":"Call to a member function getValue() on a non-object at \/var\/www\/owncloud\/lib\/private\/updater.php#84","level":3,"time":"2015-02-10T21:57:45+00:00"}
{"app":"PHP","message":"PHP Startup: Unable to load dynamic library '\/usr\/lib\/php5\/20090626\/mysqlnd.so' - \/usr\/lib\/php5\/20090626\/mysqlnd.so: cannot open shared object file: No such file or directory at Unknown#0","level":3,"time":"2015-02-10T21:59:15+00:00"}
{"app":"PHP","message":"Missing argument 1 for OC\\Updater::__construct(), called in \/var\/www\/owncloud\/lib\/private\/legacy\/updater.php on line 11 and defined at \/var\/www\/owncloud\/lib\/private\/updater.php#46","level":3,"time":"2015-02-10T22:00:54+00:00"}
{"app":"PHP","message":"Missing argument 2 for OC\\Updater::__construct(), called in \/var\/www\/owncloud\/lib\/private\/legacy\/updater.php on line 11 and defined at \/var\/www\/owncloud\/lib\/private\/updater.php#46","level":3,"time":"2015-02-10T22:00:54+00:00"}
{"app":"PHP","message":"Undefined variable: httpHelper at \/var\/www\/owncloud\/lib\/private\/updater.php#47","level":3,"time":"2015-02-10T22:00:54+00:00"}
{"app":"PHP","message":"Undefined variable: config at \/var\/www\/owncloud\/lib\/private\/updater.php#49","level":3,"time":"2015-02-10T22:00:54+00:00"}
{"app":"PHP","message":"Call to a member function getValue() on a non-object at \/var\/www\/owncloud\/lib\/private\/updater.php#84","level":3,"time":"2015-02-10T22:00:54+00:00"}
{"app":"PHP","message":"PHP Startup: Unable to load dynamic library '\/usr\/lib\/php5\/20090626\/mysqlnd.so' - \/usr\/lib\/php5\/20090626\/mysqlnd.so: cannot open shared object file: No such file or directory at Unknown#0","level":3,"time":"2015-02-10T22:01:31+00:00"}
{"app":"PHP","message":"Missing argument 1 for OC\\Updater::__construct(), called in \/var\/www\/owncloud\/lib\/private\/legacy\/updater.php on line 11 and defined at \/var\/www\/owncloud\/lib\/private\/updater.php#46","level":3,"time":"2015-02-10T22:01:31+00:00"}
{"app":"PHP","message":"Missing argument 2 for OC\\Updater::__construct(), called in \/var\/www\/owncloud\/lib\/private\/legacy\/updater.php on line 11 and defined at \/var\/www\/owncloud\/lib\/private\/updater.php#46","level":3,"time":"2015-02-10T22:01:31+00:00"}
{"app":"PHP","message":"Undefined variable: httpHelper at \/var\/www\/owncloud\/lib\/private\/updater.php#47","level":3,"time":"2015-02-10T22:01:31+00:00"}
{"app":"PHP","message":"Undefined variable: config at \/var\/www\/owncloud\/lib\/private\/updater.php#49","level":3,"time":"2015-02-10T22:01:31+00:00"}
{"app":"PHP","message":"Call to a member function getValue() on a non-object at \/var\/www\/owncloud\/lib\/private\/updater.php#84","level":3,"time":"2015-02-10T22:01:31+00:00"}
{"app":"PHP","message":"PHP Startup: Unable to load dynamic library '\/usr\/lib\/php5\/20090626\/mysqlnd.so' - \/usr\/lib\/php5\/20090626\/mysqlnd.so: cannot open shared object file: No such file or directory at Unknown#0","level":3,"time":"2015-02-10T22:01:35+00:00"}
{"app":"PHP","message":"Missing argument 1 for OC\\Updater::__construct(), called in \/var\/www\/owncloud\/lib\/private\/legacy\/updater.php on line 11 and defined at \/var\/www\/owncloud\/lib\/private\/updater.php#46","level":3,"time":"2015-02-10T22:01:35+00:00"}
{"app":"PHP","message":"Missing argument 2 for OC\\Updater::__construct(), called in \/var\/www\/owncloud\/lib\/private\/legacy\/updater.php on line 11 and defined at \/var\/www\/owncloud\/lib\/private\/updater.php#46","level":3,"time":"2015-02-10T22:01:35+00:00"}
{"app":"PHP","message":"Undefined variable: httpHelper at \/var\/www\/owncloud\/lib\/private\/updater.php#47","level":3,"time":"2015-02-10T22:01:35+00:00"}
{"app":"PHP","message":"Undefined variable: config at \/var\/www\/owncloud\/lib\/private\/updater.php#49","level":3,"time":"2015-02-10T22:01:35+00:00"}
{"app":"PHP","message":"Call to a member function getValue() on a non-object at \/var\/www\/owncloud\/lib\/private\/updater.php#84","level":3,"time":"2015-02-10T22:01:35+00:00"}
{"app":"PHP","message":"Missing argument 1 for OC\\Updater::__construct(), called in \/var\/www\/owncloud\/lib\/private\/legacy\/updater.php on line 11 and defined at \/var\/www\/owncloud\/lib\/private\/updater.php#46","level":3,"time":"2015-02-10T22:01:46+00:00"}
{"app":"PHP","message":"Missing argument 2 for OC\\Updater::__construct(), called in \/var\/www\/owncloud\/lib\/private\/legacy\/updater.php on line 11 and defined at \/var\/www\/owncloud\/lib\/private\/updater.php#46","level":3,"time":"2015-02-10T22:01:46+00:00"}
{"app":"PHP","message":"Undefined variable: httpHelper at \/var\/www\/owncloud\/lib\/private\/updater.php#47","level":3,"time":"2015-02-10T22:01:46+00:00"}
{"app":"PHP","message":"Undefined variable: config at \/var\/www\/owncloud\/lib\/private\/updater.php#49","level":3,"time":"2015-02-10T22:01:46+00:00"}
{"app":"PHP","message":"Call to a member function getValue() on a non-object at \/var\/www\/owncloud\/lib\/private\/updater.php#84","level":3,"time":"2015-02-10T22:01:46+00:00"}
{"app":"PHP","message":"PHP Startup: Unable to load dynamic library '\/usr\/lib\/php5\/20090626\/mysqlnd.so' - \/usr\/lib\/php5\/20090626\/mysqlnd.so: cannot open shared object file: No such file or directory at Unknown#0","level":3,"time":"2015-02-10T22:01:55+00:00"}
{"app":"PHP","message":"Missing argument 1 for OC\\Updater::__construct(), called in \/var\/www\/owncloud\/lib\/private\/legacy\/updater.php on line 11 and defined at \/var\/www\/owncloud\/lib\/private\/updater.php#46","level":3,"time":"2015-02-10T22:01:55+00:00"}
{"app":"PHP","message":"Missing argument 2 for OC\\Updater::__construct(), called in \/var\/www\/owncloud\/lib\/private\/legacy\/updater.php on line 11 and defined at \/var\/www\/owncloud\/lib\/private\/updater.php#46","level":3,"time":"2015-02-10T22:01:55+00:00"}
{"app":"PHP","message":"Undefined variable: httpHelper at \/var\/www\/owncloud\/lib\/private\/updater.php#47","level":3,"time":"2015-02-10T22:01:55+00:00"}
{"app":"PHP","message":"Undefined variable: config at \/var\/www\/owncloud\/lib\/private\/updater.php#49","level":3,"time":"2015-02-10T22:01:55+00:00"}
{"app":"PHP","message":"Call to a member function getValue() on a non-object at \/var\/www\/owncloud\/lib\/private\/updater.php#84","level":3,"time":"2015-02-10T22:01:55+00:00"}
{"app":"PHP","message":"PHP Startup: Unable to load dynamic library '\/usr\/lib\/php5\/20090626\/mysqlnd.so' - \/usr\/lib\/php5\/20090626\/mysqlnd.so: cannot open shared object file: No such file or directory at Unknown#0","level":3,"time":"2015-02-10T22:02:09+00:00"}
{"app":"PHP","message":"Missing argument 1 for OC\\Updater::__construct(), called in \/var\/www\/owncloud\/lib\/private\/legacy\/updater.php on line 11 and defined at \/var\/www\/owncloud\/lib\/private\/updater.php#46","level":3,"time":"2015-02-10T22:02:09+00:00"}
{"app":"PHP","message":"Missing argument 2 for OC\\Updater::__construct(), called in \/var\/www\/owncloud\/lib\/private\/legacy\/updater.php on line 11 and defined at \/var\/www\/owncloud\/lib\/private\/updater.php#46","level":3,"time":"2015-02-10T22:02:09+00:00"}
{"app":"PHP","message":"Undefined variable: httpHelper at \/var\/www\/owncloud\/lib\/private\/updater.php#47","level":3,"time":"2015-02-10T22:02:09+00:00"}
{"app":"PHP","message":"Undefined variable: config at \/var\/www\/owncloud\/lib\/private\/updater.php#49","level":3,"time":"2015-02-10T22:02:09+00:00"}
{"app":"PHP","message":"Call to a member function getValue() on a non-object at \/var\/www\/owncloud\/lib\/private\/updater.php#84","level":3,"time":"2015-02-10T22:02:09+00:00"}
{"app":"PHP","message":"Missing argument 1 for OC\\Updater::__construct(), called in \/var\/www\/owncloud\/lib\/private\/legacy\/updater.php on line 11 and defined at \/var\/www\/owncloud\/lib\/private\/updater.php#46","level":3,"time":"2015-02-10T22:04:11+00:00"}
{"app":"PHP","message":"Missing argument 2 for OC\\Updater::__construct(), called in \/var\/www\/owncloud\/lib\/private\/legacy\/updater.php on line 11 and defined at \/var\/www\/owncloud\/lib\/private\/updater.php#46","level":3,"time":"2015-02-10T22:04:11+00:00"}
{"app":"PHP","message":"Undefined variable: httpHelper at \/var\/www\/owncloud\/lib\/private\/updater.php#47","level":3,"time":"2015-02-10T22:04:11+00:00"}
{"app":"PHP","message":"Undefined variable: config at \/var\/www\/owncloud\/lib\/private\/updater.php#49","level":3,"time":"2015-02-10T22:04:11+00:00"}
{"app":"PHP","message":"Call to a member function getValue() on a non-object at \/var\/www\/owncloud\/lib\/private\/updater.php#84","level":3,"time":"2015-02-10T22:04:11+00:00"}
{"app":"PHP","message":"Missing argument 1 for OC\\Updater::__construct(), called in \/var\/www\/owncloud\/lib\/private\/legacy\/updater.php on line 11 and defined at \/var\/www\/owncloud\/lib\/private\/updater.php#46","level":3,"time":"2015-02-10T22:04:30+00:00"}
{"app":"PHP","message":"Missing argument 2 for OC\\Updater::__construct(), called in \/var\/www\/owncloud\/lib\/private\/legacy\/updater.php on line 11 and defined at \/var\/www\/owncloud\/lib\/private\/updater.php#46","level":3,"time":"2015-02-10T22:04:30+00:00"}
{"app":"PHP","message":"Undefined variable: httpHelper at \/var\/www\/owncloud\/lib\/private\/updater.php#47","level":3,"time":"2015-02-10T22:04:30+00:00"}
{"app":"PHP","message":"Undefined variable: config at \/var\/www\/owncloud\/lib\/private\/updater.php#49","level":3,"time":"2015-02-10T22:04:30+00:00"}
{"app":"PHP","message":"Call to a member function getValue() on a non-object at \/var\/www\/owncloud\/lib\/private\/updater.php#84","level":3,"time":"2015-02-10T22:04:30+00:00"}
{"app":"PHP","message":"Missing argument 1 for OC\\Updater::__construct(), called in \/var\/www\/owncloud\/lib\/private\/legacy\/updater.php on line 11 and defined at \/var\/www\/owncloud\/lib\/private\/updater.php#46","level":3,"time":"2015-02-10T22:04:42+00:00"}
{"app":"PHP","message":"Missing argument 2 for OC\\Updater::__construct(), called in \/var\/www\/owncloud\/lib\/private\/legacy\/updater.php on line 11 and defined at \/var\/www\/owncloud\/lib\/private\/updater.php#46","level":3,"time":"2015-02-10T22:04:42+00:00"}
{"app":"PHP","message":"Undefined variable: httpHelper at \/var\/www\/owncloud\/lib\/private\/updater.php#47","level":3,"time":"2015-02-10T22:04:42+00:00"}
{"app":"PHP","message":"Undefined variable: config at \/var\/www\/owncloud\/lib\/private\/updater.php#49","level":3,"time":"2015-02-10T22:04:42+00:00"}
{"app":"PHP","message":"Call to a member function getValue() on a non-object at \/var\/www\/owncloud\/lib\/private\/updater.php#84","level":3,"time":"2015-02-10T22:04:42+00:00"}
{"app":"PHP","message":"Missing argument 1 for OC\\Updater::__construct(), called in \/var\/www\/owncloud\/lib\/private\/legacy\/updater.php on line 11 and defined at \/var\/www\/owncloud\/lib\/private\/updater.php#46","level":3,"time":"2015-02-10T22:04:45+00:00"}
{"app":"PHP","message":"Missing argument 2 for OC\\Updater::__construct(), called in \/var\/www\/owncloud\/lib\/private\/legacy\/updater.php on line 11 and defined at \/var\/www\/owncloud\/lib\/private\/updater.php#46","level":3,"time":"2015-02-10T22:04:45+00:00"}
{"app":"PHP","message":"Undefined variable: httpHelper at \/var\/www\/owncloud\/lib\/private\/updater.php#47","level":3,"time":"2015-02-10T22:04:45+00:00"}
{"app":"PHP","message":"Undefined variable: config at \/var\/www\/owncloud\/lib\/private\/updater.php#49","level":3,"time":"2015-02-10T22:04:45+00:00"}
{"app":"PHP","message":"Call to a member function getValue() on a non-object at \/var\/www\/owncloud\/lib\/private\/updater.php#84","level":3,"time":"2015-02-10T22:04:45+00:00"}
{"app":"PHP","message":"Missing argument 1 for OC\\Updater::__construct(), called in \/var\/www\/owncloud\/lib\/private\/legacy\/updater.php on line 11 and defined at \/var\/www\/owncloud\/lib\/private\/updater.php#46","level":3,"time":"2015-02-11T11:54:59+00:00"}
{"app":"PHP","message":"Missing argument 2 for OC\\Updater::__construct(), called in \/var\/www\/owncloud\/lib\/private\/legacy\/updater.php on line 11 and defined at \/var\/www\/owncloud\/lib\/private\/updater.php#46","level":3,"time":"2015-02-11T11:54:59+00:00"}
{"app":"PHP","message":"Undefined variable: httpHelper at \/var\/www\/owncloud\/lib\/private\/updater.php#47","level":3,"time":"2015-02-11T11:54:59+00:00"}
{"app":"PHP","message":"Undefined variable: config at \/var\/www\/owncloud\/lib\/private\/updater.php#49","level":3,"time":"2015-02-11T11:54:59+00:00"}
{"app":"PHP","message":"Call to a member function getValue() on a non-object at \/var\/www\/owncloud\/lib\/private\/updater.php#84","level":3,"time":"2015-02-11T11:54:59+00:00"}
{"app":"PHP","message":"PHP Startup: Unable to load dynamic library '\/usr\/lib\/php5\/20090626\/mysqlnd.so' - \/usr\/lib\/php5\/20090626\/mysqlnd.so: cannot open shared object file: No such file or directory at Unknown#0","level":3,"time":"2015-02-11T11:56:26+00:00"}
{"app":"PHP","message":"PHP Startup: Unable to load dynamic library '\/usr\/lib\/php5\/20090626\/mysqlnd.so' - \/usr\/lib\/php5\/20090626\/mysqlnd.so: cannot open shared object file: No such file or directory at Unknown#0","level":3,"time":"2015-02-11T11:56:26+00:00"}
{"app":"PHP","message":"PHP Startup: Unable to load dynamic library '\/usr\/lib\/php5\/20090626\/mysqlnd.so' - \/usr\/lib\/php5\/20090626\/mysqlnd.so: cannot open shared object file: No such file or directory at Unknown#0","level":3,"time":"2015-02-11T11:58:32+00:00"}
{"app":"PHP","message":"Missing argument 1 for OC\\Updater::__construct(), called in \/var\/www\/owncloud\/lib\/private\/legacy\/updater.php on line 11 and defined at \/var\/www\/owncloud\/lib\/private\/updater.php#46","level":3,"time":"2015-02-11T12:03:22+00:00"}
{"app":"PHP","message":"Missing argument 2 for OC\\Updater::__construct(), called in \/var\/www\/owncloud\/lib\/private\/legacy\/updater.php on line 11 and defined at \/var\/www\/owncloud\/lib\/private\/updater.php#46","level":3,"time":"2015-02-11T12:03:22+00:00"}
{"app":"PHP","message":"Undefined variable: httpHelper at \/var\/www\/owncloud\/lib\/private\/updater.php#47","level":3,"time":"2015-02-11T12:03:22+00:00"}
{"app":"PHP","message":"Undefined variable: config at \/var\/www\/owncloud\/lib\/private\/updater.php#49","level":3,"time":"2015-02-11T12:03:22+00:00"}
{"app":"PHP","message":"Call to a member function getValue() on a non-object at \/var\/www\/owncloud\/lib\/private\/updater.php#84","level":3,"time":"2015-02-11T12:03:22+00:00"}
{"app":"PHP","message":"Missing argument 1 for OC\\Updater::__construct(), called in \/var\/www\/owncloud\/lib\/private\/legacy\/updater.php on line 11 and defined at \/var\/www\/owncloud\/lib\/private\/updater.php#46","level":3,"time":"2015-02-11T12:04:16+00:00"}
{"app":"PHP","message":"Missing argument 2 for OC\\Updater::__construct(), called in \/var\/www\/owncloud\/lib\/private\/legacy\/updater.php on line 11 and defined at \/var\/www\/owncloud\/lib\/private\/updater.php#46","level":3,"time":"2015-02-11T12:04:16+00:00"}
{"app":"PHP","message":"Undefined variable: httpHelper at \/var\/www\/owncloud\/lib\/private\/updater.php#47","level":3,"time":"2015-02-11T12:04:16+00:00"}
{"app":"PHP","message":"Undefined variable: config at \/var\/www\/owncloud\/lib\/private\/updater.php#49","level":3,"time":"2015-02-11T12:04:16+00:00"}
{"app":"PHP","message":"Call to a member function getValue() on a non-object at \/var\/www\/owncloud\/lib\/private\/updater.php#84","level":3,"time":"2015-02-11T12:04:16+00:00"}

**Comment by PVince81** [comment]
@bboule how did you apply the patch ?

Strangely the error message is for "\/var\/www\/owncloud\/lib\/private\/legacy\/updater.php" but none of the patches are related to this file.

**Comment by bboule** [comment]
For this one I simply downloaded the file added the .bak extension to the original and placed the file and changed permissions on the file to match the rest.  So the file I changed was /lib/privaye/updater.php  What is odd is after I do the upgrade again and it fixes everything  when I revert to the original updater.php I can login with out any issues!!

**Comment by DeepDiver1975** [comment]
> Apply the following #13865

is a patch against master (will be 8.1) - issues are to be expected

please use https://github.com/owncloud/core/pull/14040 for stable7

**Comment by DeepDiver1975** [comment]
in case you are facing issues - please comment on #14040 - closing this issue - THX
