### ISSUE TITLE
[LDAP wizard] login filter tab might use invalid attributes and report the configuration as "OK"

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#14116]
### Steps to reproduce
1. In the "User filter" tab, "select only those object classes => person"

### Expected behaviour
The selectable attributes should be the ones that the schema defines. For the "person" case (check http://www.zytrax.com/books/ldap/ape/#person) the uid, email and displayName aren't defined, so they shouldn't be shown.

### Actual behaviour
All attributes are selectable.

### Notes
- I find risky to filter objects using missing attributes (as exposed). It might be usual that the people found is of the "inetOrgPerson" object class, but I personally wouldn't make that assumption.
- What happens if, for example, we try to filter by uid and we find a "person" (not "inetOrgPerson") object? The behaviour might be server-dependent, so it would be better if we avoid the issue.
- The same behaviour happens if the user chooses "organizationalPerson" instead of "person" in the "User filter" tab

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** sqlite3

**PHP version:** 5.5.9

**ownCloud version:** ownCloud 7.0.5 RC1 (testing)

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by karlitschek** [comment]
@blizzz

**Comment by blizzz** [comment]
The list of attributes is fetched from the server and represent those that are available. It is not intended to see restrict them to the chosen objectclass. Quite the opposite, you can just use an attribute=value pair as filter.

**Comment by blizzz** [comment]
> What happens if, for example, we try to filter by uid and we find a "person" (not "inetOrgPerson") object? The behaviour might be server-dependent, so it would be better if we avoid the issue.

An LDAP entry might (and this is rather rule than exception) several objectclasses. The limitation of the object class  does not mean that all other possible or not considered anymore. Instead the LDAP server looks at all LDAP objects that have the person objectClass AND the uid attribute (which is provided from another schema that also links to the LDAP object).

**Comment by blizzz** [comment]
Furthermore we cannot guess around on custom schemas and I honestly don't see a point in it.

**Comment by jvillafanez** [comment]
@blizzz Check http://stackoverflow.com/a/5258902
It might be worthy to give it a shot

**Comment by blizzz** [comment]
@jvillafanez 

> This will return all the objectclasses and attributetypes as string. You dont have an option of querying list of attribute of a given objectclass. You can ONLY get the ldif output of all stored objetclass and attribute.

So? That's where we are.
