### ISSUE TITLE
"app":"PHP","message":"imagesetpixel() expects parameter 1 to be resource

### ISSUE THREAD

**Issue by dmclaren** [owncloud/core#14112]
Hello,

I am getting this error millions of times in the owncloud.log until the disk is full. I upgraded to version 8 this morning and the issue continues, here is a sample of the log.

{"app":"PHP","message":"imagesetpixel() expects parameter 1 to be resource, boolean given at \/var\/www\/owncloud\/lib\/private\/image.php#726","level":3,"time":"2015-02-11T14:41:54+00:00"}
{"app":"PHP","message":"imagesetpixel() expects parameter 1 to be resource, boolean given at \/var\/www\/owncloud\/lib\/private\/image.php#726","level":3,"time":"2015-02-11T14:41:54+00:00"}
{"app":"PHP","message":"imagesetpixel() expects parameter 1 to be resource, boolean given at \/var\/www\/owncloud\/lib\/private\/image.php#726","level":3,"time":"2015-02-11T14:41:54+00:00"}
{"app":"PHP","message":"imagesetpixel() expects parameter 1 to be resource, boolean given at \/var\/www\/owncloud\/lib\/private\/image.php#726","level":3,"time":"2015-02-11T14:41:54+00:00"}
{"app":"PHP","message":"imagesetpixel() expects parameter 1 to be resource, boolean given at \/var\/www\/owncloud\/lib\/private\/image.php#726","level":3,"time":"2015-02-11T14:41:54+00:00"}
{"app":"PHP","message":"imagesetpixel() expects parameter 1 to be resource, boolean given at \/var\/www\/owncloud\/lib\/private\/image.php#726","level":3,"time":"2015-02-11T14:41:54+00:00"}

Is there a work around for this issue? I have seen other issues reported before.

Thanks.

**Comment by karlitschek** [comment]
@georgehrke any idea?

**Comment by georgehrke** [comment]
please use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md) as described in our [contributing guidelines](https://github.com/owncloud/core/blob/master/CONTRIBUTING.md)

**Comment by georgehrke** [comment]
@karlitschek Could be preview related, could also be gallery/avatar related.

**Comment by dmclaren** [comment]
I'll start gathering the rest of the info.

Thanks.

**Comment by georgehrke** [comment]
@dmclaren Do you still see the error logs if you [disable previews](http://doc.owncloud.org/server/8.0/admin_manual/configuration/previews_configuration.html#disabling-previews)?

**Comment by dmclaren** [comment]
Checking, it could be related to that, I just noticed they have a folder with thousands of images.

**Comment by DeepDiver1975** [comment]
> /www\/owncloud\/lib\/private\/image.php#726

hmmm - there is something messed up with your installation

https://github.com/owncloud/core/blob/stable8/lib/private/image.php#L726 holds no call to imagesetpixel

**Comment by dmclaren** [comment]
@georgehrke I just disabled previews, @DeepDiver1975 I guess something went wrong when I did the upgrade, although the admin panel shows I'm running version 8 and the upgrade process didn't fail.

Thanks for the quick replies!

**Comment by georgehrke** [comment]
> @georgehrke I just disabled previews

And did ownCloud stop logging this certain error message?

**Comment by georgehrke** [comment]
ping @dmclaren

**Comment by PVince81** [comment]
Closing due to lack of feedback.

@dmclaren if you're still seeing this with OC 8.0.5, feel free to reopen.
