### ISSUE TITLE
Admins can't edit mails of users if `allow_user_to_change_display_name` is set to false

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#14127]
Had a little chat with @enoch85 and he couldn't change the mail of users even as admin. Turned out that he had `allow_user_to_change_display_name` set to false and from the code logic admins can't change the users email then.

We either need to allow it for admins or hide those settings in the UI.

**Comment by LukasReschke** [comment]
@MorrisJobke FYI

**Comment by LukasReschke** [comment]
Or the error should make the reason more clear

**Comment by enoch85** [comment]
No error in owncloud.log either. Not even in debug mode.

**Comment by enoch85** [comment]
The logged in users can't change their email either, they are prompted with the same error "can't change email".

**Comment by snake2903** [comment]
I also have allow_user_to_change_display_name set to false and can't change e-mail address as admin. After seting to true, i can change email address as admin.

**Comment by MorrisJobke** [comment]
-.- This is because usually the "can change" permission is fetched from the backend (because there are read-only backends out there). It seems that this setting overwrites this functionality.

**Comment by DeepDiver1975** [comment]
not really critical -> 8.1

**Comment by karlitschek** [comment]
@georgehrke In the mood for a nice junior job? :-)

**Comment by PVince81** [comment]
fix is here https://github.com/owncloud/core/issues/19053

**Comment by MorrisJobke** [comment]
@DeepDiver1975 requested to postpone this to 9.0 https://github.com/owncloud/core/pull/19053#discussion_r40074520

**Comment by cmonteroluque** [comment]
ok

**Comment by colomailbe** [comment]
'allow_user_to_change_display_name' => true,
Still block user and admin to change email (and is therefore useless).

This setting is essential and was postponed since a very long time, was hoping some changes with new milestone, but no chance. Is there still any plan to fix it? Any timeline? Thanks!

**Comment by PVince81** [comment]
We now have two conflicting PRs:
- from @georgehrke https://github.com/owncloud/core/pull/19053
- from @nickvergessen https://github.com/owncloud/core/pull/22610

Both require API changes which is bad after feature freeze...

**Comment by cmonteroluque** [comment]
https://github.com/owncloud/core/pull/22669 minimal fix merged. Moving rest to 9.1

**Comment by PVince81** [comment]
Okay, so the two PRs got closed.

What approach should we use for this then ? Does the minimal fix cover enough of the requirements ?
What's the next step for the rest ?

**Comment by DeepDiver1975** [comment]
the current behavior works as designed -> 9.2 will bring the user account table and any property can the be changed -> close
