### ISSUE TITLE
Error in Log on Cron execution: Undefined index: REQUEST_URI at .../apps/calendar/appinfo/app.php#41 

### ISSUE THREAD

**Issue by Panoptis** [owncloud/core#14122]
Every time Cron runs this Error is logged:
Error 	PHP 	Undefined index: REQUEST_URI at /var/www/virtual/.../apps/calendar/appinfo/app.php#41 

Calendar app seems to work fine though.
OC 8.0 (stable) 
PHP 5.6.5 on CentOS

**Comment by RealRancor** [comment]
Could be related to: https://github.com/owncloud/core/issues/11551

**Comment by DeepDiver1975** [comment]
should be opened in https://github.com/owncloud/calendar - THX
