### ISSUE TITLE
External Storage config options unavaiable when using asset-pipeline.enabled

### ISSUE THREAD

**Issue by fossxplorer** [owncloud/core#14134]
Using stable7, after selecting an external storage type, the config options are not displayed!
When i set 'asset-pipeline.enabled' => false, it works as intended.
Console shows:

```
Uncaught TypeError: undefined is not a function  ad7293bd07935ab658745d598cd67fbb.js:24032 
And line 24032 starts with:
(function (factory) {
    'use strict';
    if (typeof define === 'function' && define.amd) {
        // Register as an anonymous AMD module:
        define([
            'jquery',
            'jquery.ui.widget'
        ], factory);
    } else {
        // Browser globals:
        factory(window.jQuery);
    }
```

@DeepDiver1975

**Comment by fossxplorer** [comment]
Could looke like a namespace issue and the following fixes the issue https://github.com/fossxplorer/3rdparty/commit/37b32f2d5742c7308062b281ed69f02dcea043d2.
If this is a proper solution the problem, i'll open a PR.

**Comment by fossxplorer** [comment]
Fixed here https://github.com/MorrisJobke/strengthify/blob/master/jquery.strengthify.js#L134.

**Comment by MorrisJobke** [comment]
This was fixed in https://github.com/owncloud/core/pull/13126 for ownCloud 8.0.

@karlitschek @DeepDiver1975 Together with asset pipelining this cause trouble. Should I create a backport PR for stable7 for the fixes that took place in the strengthify code?

**Comment by MorrisJobke** [comment]
Another possible ay to go would be to backport #13116

**Comment by MorrisJobke** [comment]
@karlitschek @DeepDiver1975 Ping

**Comment by Xenopathic** [comment]
There's a good chance a different JavaScript library will miss out a final semicolon, which is where #13116 comes in useful.

**Comment by MorrisJobke** [comment]
I created a backport PR in #14631

**Comment by MorrisJobke** [comment]
@fossxplorer I can't fully reproduce your issue. Can you please list the enabled apps that cause this problem? And can I ask you to test against #14631

**Comment by MorrisJobke** [comment]
stable7 simply doesn't support asset pipeline for now .... as the PR doesn't fix everything and even more stuff needs to be backported, that will introduce problems with a high propability: I will close this. It's fixed in stable8+
