### ISSUE TITLE
Allow to define OpenStack Swift storage as root path for a user

### ISSUE THREAD

**Issue by ro78** [owncloud/core#14136]
Hi all,

Today, in ownCloud, I can setup an OpenStack Swift storage, and access it from a folder inside my root path (home directory of the user).

I want to be able to set the home directory of a user directly inside an OpenStack Swift storage, so he will not be able to store anything on the server hosting ownCloud, and he will not have to click on a folder to start seeing his file or upload new files to the OpenStack Swift storage.

Best regards,
Romain

**Comment by LukasReschke** [comment]
https://github.com/owncloud/core/blob/780024e25217db167761dc723c5100a5f144a768/config/config.sample.php#L873-L912

**Comment by ro78** [comment]
Thanks.
Is there a way to define 1 container by user ?

**Comment by LukasReschke** [comment]
@butonic

**Comment by butonic** [comment]
not yet.

**Comment by LukasReschke** [comment]
Reopen or do we already have an issue for that?
