### ISSUE TITLE
ownCloud 8's OC_Image is incompatible with 5.4

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#14130]
This breaks quite some stuff: https://github.com/owncloud/core/commit/a28d3b594b089af837c6a319d7b7b6a8f7155210#commitcomment-9706810

**Comment by karlitschek** [comment]
This is bad. And needs to be fixed as soon as possible. @MorrisJobke

**Comment by MorrisJobke** [comment]
I will simply not flip the image in PHP 5.4. Is this okay?

**Comment by MorrisJobke** [comment]
Fix is in #14138

**Comment by oparoz** [comment]
A quick Google search revealed a couple of functions which can emulate the behaviour for PHP < 5.5. Wouldn't that be a better option?
