### ISSUE TITLE
Unexpected error: 0 error after successfull upgrade to 8.0

### ISSUE THREAD

**Issue by redhell** [owncloud/core#14139]
Good morning,

i successfully upgraded to OC8 but in the admin menu more or less randomly an issue raises at configureation check "Unexpected error: 0 error"  and "Fehler beim Überprüfen der Servereinrichtung
Bitte prüfe die Installationsanleitungen." 
I changed nothing in the config and so far everythings runs fine. Sometimes OC tells me there is no error and everything is fine but a refresh later the "problem" is back.
Additionally no error etc. is logged.

I upgraded with the skip-migration-test flag because i'm using MariaDB 10. On my test installation i had no issues without the flag.

Server:
Ubuntu 14.04
PHP 5.6.5. w/OpCache & APCu
Nginx frontend and Apache as Backend
MariaDB 10.0

**Comment by LukasReschke** [comment]
Thanks a lot for reporting issues back to us!

We need some more information to properly support you with your issue!

Can I ask you to follow our guidelines for submitting bugs as described here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

Thanks a lot!

**Comment by redhell** [comment]
OC version: 8
Updated: yes
List of activated apps:
- Calendar
- Contacts
- Encryption
- Shorty
- Tasks
- Gallery 
- Documents
Config:
```
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'datadirectory' => '',
  'dbtype' => 'mysql',
  'version' => '8.0.0.7',
  'dbname' => '',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'forcessl' => true,
  'loglevel' => 1,
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' => 
  array (
    0 => '',
  ),
  'logtimezone' => 'Europe/Berlin',
  'log_authfailip' => true,
  'mail_from_address' => 'cloud',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => '',
  'cipher' => 'AES-256-CFB',
  'user_backends' => 
  array (
    0 => 
    array (
      'class' => 'OC_User_IMAP',
      'arguments' => 
      array (
        0 => '{:993/imap/ssl/secure/readonly}}',
      ),
    ),
  ),
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => true,
  'mail_smtpsecure' => 'tls',
  'mail_smtpport' => '25',
  'mail_smtphost' => '',
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'mail_smtpname' => '',
  'mail_smtppassword' => '',
  'secret' => 'secret',
  'hashingCost' => 10,
);
```
Encryption: yes

**Comment by DeepDiver1975** [comment]
Does this error still persist? Anything in the logs?

**Comment by redhell** [comment]
Negative. It's gone now.

**Comment by DeepDiver1975** [comment]
> Negative. It's gone now.

thx
