### ISSUE TITLE
Previews not working when an apostrophe is present in name.

### ISSUE THREAD

**Issue by ka0tik0** [owncloud/core#14149]
Previews not working when an apostrophe is present in name.

**Comment by karlitschek** [comment]
@georgehrke

**Comment by LukasReschke** [comment]
More details can be found at https://github.com/owncloud/core/issues/14180

**Comment by georgehrke** [comment]
Strange, was definitely working in ownCloud 7. Will check asap

**Comment by oparoz** [comment]
I'm wondering if this is not because of the use of regular expressions to determine if a preview can be generated

**Comment by georgehrke** [comment]
fix is here: https://github.com/owncloud/core/pull/14419
