### ISSUE TITLE
File uploaded from client gets the wrong mime type

### ISSUE THREAD

**Issue by remixtj** [owncloud/core#14148]
### Steps to reproduce
1. Set the mime type for the mmap extension in mimetypes.list.php
2. Copy a .mmap file in the client directory and wait for syncronization
3. Make this query to check assigned mime type:
```
select name,oc_mimetypes.mimetype as mime from oc_filecache inner join oc_mimetypes on oc_mimetypes.id=oc_filecache.mimetype where name LIKE "%.mmap"

```

### Expected behaviour
A file with extension .mmap uploaded gets the mime type that is set in lib/private/mimetypes.list.php:

```
'mmap' => array('application/vnd.mindjet.mindmanager', null),

```

### Actual behaviour
The file is classified as application/zip if uploaded with the client. Using web interface, mime type is correct. 

Application/zip is chosen because the file in fact a zip file containing xml. Wrong mime type gives problem when opening the file from web interface.

### Server configuration
**Operating system**: Red Hat Enterprise Linux 6.5

**Web server:** Apache/2.2.15

**Database:** mysql  Ver 14.14 Distrib 5.1.71, for redhat-linux-gnu (x86_64) using readline 5.1

**PHP version:** PHP 5.4.16 (cli) (built: Feb  4 2014 08:10:51) 

**ownCloud version:** 7.0.3.4

**Updated from an older ownCloud or fresh install:**

**List of activated apps:**
Enabled:
 - activity
 - admin_dependencies_chk
 - appVNCsafe
 - contacts
 - documents
 - files
 - files_external
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - files_videoviewer
 - firstrunwizard
 - gallery
 - search_lucene
 - templateeditor
 - user_ldap

**The content of config/config.php:**

```<?php
$CONFIG = array (
  'instanceid' => 'istanceid',
  'passwordsalt' => 'salt',
  'trusted_domains' => 
  array (
    0 => 'domain1',
    1 => 'domain2',
    2 => 'domain2',
  ),
  'datadirectory' => '/opt/owncloud/data',
  'overwrite.cli.url' => 'http://domain1',
  'dbtype' => 'mysql',
  'version' => '7.0.3.4',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'password',
  'installed' => true,
  'appstoreenabled' => false,
  'updatechecker' => false,
  'has_internet_connection' => false,
  'loglevel' => '0',
  'log_query' => false,
  'objectstore' => 
  array (
    'class' => 'OC\\Files\\ObjectStore\\Swift',
    'arguments' => 
    array (
      'username' => 'owncloud',
      'password' => 'password_swift_owncloud',
      'container' => 'dati_owncloud',
      'autocreate' => true,
      'region' => 'regionOne',
      'url' => 'http://keystoneserver:5000/v2.0/',
      'tenantName' => 'owncloud',
      'serviceName' => 'swift',
    ),
  ),
  'ldapIgnoreNamingRules' => false,
  'forcessl' => true,
  'skeletondirectory' => '/opt/owncloud/ic_skeleton/',
  'customclient_desktop' => 'https://domain3/client/',
  'customclient_android' => 'https://domain3/client/client_android.apk',
  'customclient_ios' => 'https://itunes.apple.com/us/app/owncloud/id543672169?mt=8',
  'singleuser' => false,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'owncloud',
  'mail_domain' => 'domain',
  'mail_smtphost' => 'mailserver',
  'mail_smtpport' => '25',
  'maintenance' => false,
);

```

**Are you using external storage, if yes which one:** swift as main storage.

**Are you using encryption:** no

### Client configuration
**Browser:** Several (IE 10, Firefox 32/35, Chrome)

**Operating system:** Several (Windows 7, Several linux distributions)

**Comment by karlitschek** [comment]
@icewind1991 @PVince81

**Comment by PVince81** [comment]
Weird. OC 7 doesn't detect the mime type based on file type but on extension so this shouldn't happen.

Can you confirm that the local file is indeed a zip file, not a folder ? (on Mac there were "magic folders" that look like files in the file manager but are actually folders, that's why I'm asking)

**Comment by remixtj** [comment]
yes, it is.

```
remixtj@remixtj:test_mmap$ file experiment.mmap 
experiment.mmap: Zip archive data, at least v2.0 to extract
```

You can get the file from here for testing: http://www.remixtj.net/experiment.mmap

**Comment by remixtj** [comment]
Can i have some ideas on how to check for the code that assigns the mimetype to objects uploaded via webdav? I would like to solve this issue  before going in production...

**Comment by PVince81** [comment]
Not 100% but it might be here: https://github.com/owncloud/core/blob/master/lib/private/files/cache/scanner.php#L90

For regular storage it would go here: https://github.com/owncloud/core/blob/master/lib/private/files/storage/common.php#L194 and use the "detect based on file extension approach".

But in the case of a SWIFT server, this class extends the Common class: https://github.com/owncloud/core/blob/master/apps/files_external/lib/swift.php#L355 which doesn't seem to use that approach.

You could put breakpoints there and/or use logging to see where it goes.

**Comment by remixtj** [comment]
Thanks @PVince81 i made another test and some checks and using regular storage the problem does not exists (the right mime is used).

The problem is connected to using the SWIFT Backend.

**Comment by PVince81** [comment]
I'm not sure why the Swift storage doesn't rely on our detection... maybe @butonic thought that we could save some logic and use the mime type stored in SWIFT instead of recomputing it ?

@remixtj you can try removing the method "getMimeType" from the Swift class to make it use the one from Common. That might solve your problem.

**Comment by PVince81** [comment]
I checked the git history and it seems the logic has always be to get the mime type from Swift. Maybe it was a misunderstanding since the beginning.

**Comment by remixtj** [comment]
Commented getMimeType from swift class but nothing changed. Checking other code

**Comment by remixtj** [comment]
I put some trigger_error, file_put_contents and other codes for identifying which mime type detection function is called. Cannot identify which one is used...

**Comment by risacher** [comment]
I've struggled with similar issues.  I would love to better understand how the mimetype is determined for the WebDAV interface.  Both .html and .svg files are served out from the WebDAV interface as 'text/plain', which is not what I expect.

**Comment by remixtj** [comment]
@risacher this issue is clearly related to the usage of Swift as backend storage. As far as i can understand the problem you're experiencing is different

**Comment by PVince81** [comment]
Please try again with OC v9.0.1.
Mime type should now be inferred based on extension, for all external storage types.
