### ISSUE TITLE
Hide password strength after password change

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#14142]
* go to the personal page
* type in the old password and a new one (password strength appears)
* hit enter or the "Change password" button

### expected

strength meter hides

### actual

strength meter is still visible

**Comment by jancborchardt** [comment]
@Kondou-ger cause he worked on the strength meter.

**Comment by jancborchardt** [comment]
@Kondou-ger can you look into this? :)

**Comment by Kondou-ger** [comment]
Looks like @MorrisJobke's strengthify library has no way to hide the strengthify wrapper.

He should add a hide-call to it, so when the input is cleaned by changing the password a
`$('#pass2).strenghtify.hide()` (or so) call can be done, too.

**Comment by jancborchardt** [comment]
@MorrisJobke you said you wanna hack on stuff, right? ;) Go

**Comment by MorrisJobke** [comment]
@Kondou-ger I'm open for PRs :) Would be nice if you implement something.

**Comment by jancborchardt** [comment]
@Kondou-ger @MorrisJobke any news here? Would be cool to fix this for 8.1

**Comment by jancborchardt** [comment]
> @Kondou-ger @MorrisJobke any news here? Would be cool to fix this for 8.2

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/19625 (one liner)
