### ISSUE TITLE
Usernames and federated cloud sharing

### ISSUE THREAD

**Issue by Helios07** [owncloud/core#14154]
Dear ownCloud developers.

First I want to thank you for the federated cloud sharing feature formely known as server2server sharing. Since it is crucial for our project I was very happy to see that it is further developed in ownCloud 8.
The reason why I write this ticket is that there might be an aspect that you did not consider. As far as I understand it, you enter an @ behind the username you want to share with and enter the server name (which in my case only worked when I put an https:// in front of the servername, what confused me a bit).  
The thing is that it is possible to use emailadresses as usernames (or usernames that contain an @ in general) so you would have to type two @ signs when using federated cloud sharing. In this case you have to ensure that ownlcoud only parses the username behind the last an not the first @, what does not seem to be the case.
But instead of just fixing this, my proposal is that you introduce a separate box in the sharing dialogue for the server name. It could be pre-filled with your own servername and you only would have to change it when you want to share with someone from another server.

Regards
Holger

**Comment by LukasReschke** [comment]
@jancborchardt @schiesbn

**Comment by schiesbn** [comment]
@Helios07 Great to hear that you like the new concept of cloud federation. You couldn't chose a better time for your suggestion. :smile:  I worked at exact this feature last week and it should be available in ownCloud 8.1 https://github.com/owncloud/core/pull/14218

**Comment by Helios07** [comment]
@schiesbn Thank you for your reply. I read #14218, but at least one of my points was not mentioned. At the moment in owncloud 8 you cannot use the federated cloud sharing feature with users that have an @ in their usernames. Or is this fixed in 8.1?

**Comment by felixboehm** [comment]
@schiesbn Are usernames with an @ (e.g. email) working?
How can I test this?

**Comment by nickvergessen** [comment]
I think splitting the input in the UI sounds like a good option.

@jancborchardt can you poke @owncloud/designers

**Comment by jancborchardt** [comment]
cc @owncloud/designers 

Yeah, I also discussed this with @schiesbn @DeepDiver1975 and we came to the conclusion that this is something to be discussed in Nürnberg for 8.2. Splitting the inputs could be done, but on what basis? For shares on the same ownCloud, it’s not needed.

**Comment by nickvergessen** [comment]
@jancborchardt from my understanding the suggestion is to split the input fields, so in one field you put the username (uid, user-ldap email, ...) and in the second field you put the URL of the instance.

**Comment by Helios07** [comment]
That's exactly what I meant.
There would be another advantage that I did not mention. Imagine you want to share with a user called "abc@gmail.com". When you enter this user in the share field as it is implemented in 8.0, the owncloud would ask google if it is an owncloud. I think this is not wanted.

**Comment by jancborchardt** [comment]
@Helios07 first off, ownCloud should check if the username put in is a name on the same ownCloud. So that will not happen if it’s really a username.

@nickvergessen ok, so then we could add a dropdown to the input field saying »Share with user on other ownCloud« (better shorter) which will then display an input field for the URL.

**Comment by jancborchardt** [comment]
@nickvergessen that would also solve https://github.com/owncloud/core/issues/13678, right?

**Comment by nickvergessen** [comment]
At least it would make it easier, since the cleaning can then be done on the URL only, without having potential problems with more `@` signs in the username.

The problem with the current approach is also:
if you have a user `test@owncloud.com`, you can not remote share anything to `test` on the `owncloud.com` instance. Well, you can, if you know that you can add the `http(s)://` prefix, to force remote share to trigger. But I guess the easier, the better.

**Comment by Helios07** [comment]
Hi, are there any news regarding this ticket? Is there already a decision, if this will be implemented?

**Comment by jancborchardt** [comment]
We have a clarification in the sharing dialog now which lets you know to use the syntax `username@example.com/owncloud`. That should work, right?

If it doesn’t work to put `user@email.com@example.com/owncloud` then that’s a technical issue to be fixed.

**Comment by Helios07** [comment]
Ok, thank you. I will give it a test.

**Comment by Helios07** [comment]
I have tested federated cloud sharing again in 8.1. It is still not possible to share with someone having an @ in his username. I created a separate ticket for this.

**Comment by felixboehm** [comment]
Remote share code looks good, but the sharing dialog ui doesn't "fetch" and match entries with 2 '@':
https://github.com/owncloud/core/blob/master/core/ajax/share.php#L356

Changing this line to:
```
if (substr_count((string)$_GET['search'], '@') >= 1) {
```

let's me successfully remote share with users having emails as usernames.

Anything dangerous I don't see?

**Comment by schiesbn** [comment]
> Any side effects I don't see?

No, I think this the right change. Do you want to create a PR for it?
