### ISSUE TITLE
Class 'OCA\\Files_Sharing\\API\\Server2Server' not found

### ISSUE THREAD

**Issue by guyguy333** [owncloud/core#14152]
### Steps to reproduce
1. Install ownCloud 8 on CentOS 7
2. Configure MySQL
3. Open homepage

### Expected behaviour
ownCloud homepage

### Actual behaviour
PHP Error : 
> PHP Fatal error:  Class 'OCA\\Files_Sharing\\API\\Server2Server' not found in /home/****/webapps/owncloud/ocs/routes.php on line 86

### Server configuration
**Operating system:** CentOS 7

**Web server:** Apache/2.4.6

**Database:** 5.5.41-MariaDB

**PHP version:** PHP 5.4.16

**ownCloud version:** 8.0.0.7

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:** none

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'oc******qg',
  'passwordsalt' => 'jzJU******PSeubOQ',
  'secret' => 'HX******qjgH',
  'trusted_domains' =>
  array (
    0 => 'cloud.******.com',
  ),
  'datadirectory' => '/home/******/owncloud/data',
  'overwrite.cli.url' => 'http://cloud.******.com',
  'dbtype' => 'mysql',
  'version' => '8.0.0.7',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '******',
  'installed' => true,
);

```

**Are you using external storage, if yes which one:** none

**Are you using encryption:** no

### Client configuration
**Browser:** Safari

**Operating system:** OS X Yosemite

#### Web server error log
```
[Wed Feb 11 22:18:32.458784 2015] [:error] [pid 17093] [client ****] PHP Fatal error:  Class 'OCA\\Files_Sharing\\API\\Server2Server' not found in /home/****/webapps/owncloud/ocs/routes.php on line 86
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"27417bfe759*****ee4094","remoteAddr":"****","app":"PHP","message":"Class 'OCA\\Files_Sharing\\API\\Server2Server' not found at \/home\/****\/webapps\/owncloud\/ocs\/routes.php#86","level":3,"time":"2015-02-11T21:18:32+00:00"}
```
```

**Comment by LukasReschke** [comment]
How did you install ownCloud?

cc @jnweiger  This pretty sure looks like a packaging bug to me.

**Comment by jnweiger** [comment]
@LukasReschke the CentOS7 package intalls into /var/www/html/owncloud not into home/****/webapps/owncloud  -> Not a packaging issue.

@guyguy333 please check your file permissions. You probably need to give more read/write access to the apache user.

**Comment by guyguy333** [comment]
I confirm, it was a file permissions problem.

Thank you

**Comment by JT089** [comment]
We´ve got the same Problem. Because of "least privilege thinking", we´d like to make only the minimum subset of files/directory writable to apache. Till now it was owncloud/apps owncloud-www/config owncloud/tmp /owncloud/data

@guyguy333 What file permissions did you change?

**Comment by pierreozoux** [comment]
I'm hitting the same issue right now :)

@guyguy333 What file permissions did you change?

FYI, I followed [this](http://doc.owncloud.org/server/8.0/admin_manual/installation/installation_wizard.html#setting-strong-directory-permissions) to setup file permission. Maybe, it would be good to update if needed.

**Comment by JT089** [comment]
Hey @LukasReschke,

think this issue has to be reopened. Tryed to give my www-run-user control over ALL owncloud-files, but still the same issue.

**Comment by LukasReschke** [comment]
If you have similiar issues which cannot be resolved by changing the file permissions this is a different bug and needs a new report using the issue template.

**Comment by pierreozoux** [comment]
@LukasReschke can you give us more clue about file permission? Then I can try and tell you if it is related to permission or not.

Thanks!

**Comment by JT089** [comment]
@LukasReschke: I agree to @pierreozoux - noone ever pointed out, what files permissions were changed. We both followed the "manual installation" documentation and changed the permissions accordingly

**Comment by LukasReschke** [comment]
The script works quite fine here. Please post exact steps what you did.

I performed:

1. `sudo su`
2. `wget https://download.owncloud.org/community/owncloud-8.0.0.tar.bz2`
3. `tar -xvf owncloud-8.0.0.tar.bz2`
4. `chown -R www-data:www-data owncloud/`
5. `vim setup.sh` and added the scripts content
6. `bash setup.sh`

**Comment by VincentSC** [comment]
Just fixed it here. I had a configuration-mistake: the location of the app-directory was wrong. OC7 just fell back to the default, whereas OC8 did not. My suggestion for 8.0.3: give an error when there is a config-error like an nonexisting directory.
