### ISSUE TITLE
Path length(261) exceeds max path 

### ISSUE THREAD

**Issue by genobit** [owncloud/core#14155]
Hello,

I have an Issue with upgrading Owncloud 7.0.4 to 8.0.0.

I backed up my complete Owncloud Folder + my Owncloud Database and copied the new Owncloud folder into mine (except the config folder and .htaccess).

After a few minutes of updating it shows me this error:
Path length(261) exceeds max path length(260): gvwe1/files_encryption/keyfiles//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

gvwe1 is one of our users.

My Server Setup:
Intel Xeon E5-2620 v2 @ 2.10GHz
10 GB RAM
Windows Server 2012 R2 Standard 64 bit

Edit: MySQL 5.6.16.0 is installed

**Comment by PVince81** [comment]
@nickvergessen

**Comment by genobit** [comment]
I switched to ubuntu server now, thanks for the help anyways.
