### ISSUE TITLE
occ upgrade fail "Maximum execution time of 3600 seconds exceeded"

### ISSUE THREAD

**Issue by MLWALK3R** [owncloud/core#14156]
Applied this patch nlegoff/dbal@7f89a78317808a4cdf271bb5e4740c06d230c2d8 to fix this issue #14003 but still doesn't upgrade and Owncloud is stuck in maintenance mode even when you set it to false in the config.

```bash
 sudo -u www-data php /var/www/owncloud/occ upgrade
Turned on maintenance mode
Checked database schema update
Updated database
PHP Fatal error:  Maximum execution time of 3600 seconds exceeded in /var/www/owncloud/lib/private/fileproxy.php on line 118
```

**Comment by karlitschek** [comment]
@DeepDiver1975 @bantu FYI

**Comment by MLWALK3R** [comment]
Any idea when this will be fixed?

**Comment by karlitschek** [comment]
will be fixed in the next patch release

**Comment by MLWALK3R** [comment]
I'm trying that new commit and its not looking good IMO.

**Comment by DeepDiver1975** [comment]
> its not looking good

NOT or NOW? Hoping for now :speak_no_evil:

**Comment by MLWALK3R** [comment]
I've been on this for about 3 hours

```bash
# sudo -u www-data php /var/www/owncloud/occ upgrade -VVV
Turned on maintenance mode
Checked database schema update
Updated database
```

**Comment by DeepDiver1975** [comment]
> I've been on this for about 3 hours

hmm - not really nice to take that long - but at least the execution timeout seems to be gone .... THX for the feedback

**Comment by MLWALK3R** [comment]
Any idea what's causing it to take so long?

**Comment by MLWALK3R** [comment]
is it right for it to continue to create these files?

```bash
drwxr-xr-x   5 www-data www-data  4096 Feb 10 22:12 encryption_migration_backup_2015-02-10_21-11-26/
drwxr-xr-x   5 www-data www-data  4096 Feb 11 13:51 encryption_migration_backup_2015-02-11_12-50-32/
drwxr-xr-x   5 www-data www-data  4096 Feb 11 19:41 encryption_migration_backup_2015-02-11_18-40-34/
drwxr-xr-x   5 www-data www-data  4096 Feb 16 14:32 encryption_migration_backup_2015-02-16_13-30-37/
drwxr-xr-x   5 www-data www-data  4096 Feb 16 14:50 encryption_migration_backup_2015-02-16_13-49-16/
drwxr-xr-x   5 www-data www-data  4096 Feb 16 14:56 encryption_migration_backup_2015-02-16_13-55-27/
```

**Comment by DeepDiver1975** [comment]
> Any idea what's causing it to take so long?

it's the encryption key migration - known to waste time ...

**Comment by DeepDiver1975** [comment]
> is it right for it to continue to create these files?

hmm - when did you start the console command to upgrade?

**Comment by MLWALK3R** [comment]
Around 14:00. Is there a way to disable the encryption?  (I would reinstall the whole thing if I didn't have 40GB of raw images on there)

**Comment by MLWALK3R** [comment]
Left the upgrade running overnight and it worked. xD

**Comment by DeepDiver1975** [comment]
@MLWALK3R good to know it finally worked out for you.

How long did it run at the end?
How many users do you have?

THX

**Comment by MLWALK3R** [comment]
@DeepDiver1975 

IDK how long it was I restarted the hole progress last night then just when bed and woke up to it completed.
1 User account ( about 50GB of Raw images)

**Comment by DeepDiver1975** [comment]
> 1 User account ( about 50GB of Raw images)

WOW - that should not take that long ... hmmmm ... we need to have a closer look.

Which apps are enabled? THX

**Comment by DeepDiver1975** [comment]
@MLWALK3R we better start off a new ticket to get this sorted out - can I ask you to file a new ticket?

Please use the issue template so that we get all required information about your environment - THX
