### ISSUE TITLE
Big file upload not working

### ISSUE THREAD

**Issue by shoeper** [owncloud/core#14166]
### Expected behaviour
Uploading files up to 16GB should work

### Actual behaviour
Uploading ~9GB big file fails (2.2GB do work)

### Server configuration
**Operating system:** Debian (Wheezy) 3.2.65-1+deb7u1 x86_64

**Web server:** Nginx 1.2.1

**Database:** 5.5.41-0+wheezy1

**PHP version:** PHP 5.4.36-0+deb7u3

**ownCloud version:** ownCloud 8.0 (stable)

**Updated from an older ownCloud or fresh install:** no

I've followed steps from http://doc.owncloud.org/server/8.0/admin_manual/configuration/big_file_upload_configuration.html

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 8.1

#### nginx access log
```
root@home:/# cat /var/log/nginx/access.log | grep Chrome | grep POST | grep upload.php
192.168.178.82 - - [12/Feb/2015:17:06:12 +0100] "POST /index.php/apps/files/ajax/upload.php HTTP/1.1" 200 226 "https://owncloud.hoeper.me/index.php/apps/files/?dir=%2FBackup" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36"
192.168.178.82 - - [12/Feb/2015:17:22:54 +0100] "POST /index.php/apps/files/ajax/upload.php HTTP/1.1" 400 0 "https://owncloud.hoeper.me/index.php/apps/files/?dir=%2FBackup" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36"
192.168.178.82 - - [12/Feb/2015:17:34:18 +0100] "POST /index.php/apps/files/ajax/upload.php HTTP/1.1" 200 226 "https://owncloud.hoeper.me/index.php/apps/files/?dir=%2FBackup" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36"
192.168.178.82 - - [12/Feb/2015:17:58:51 +0100] "POST /index.php/apps/files/ajax/upload.php HTTP/1.1" 200 450 "https://owncloud.hoeper.me/index.php/apps/files/?dir=%2FBackup" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36"
```

#### ownCloud log (data/owncloud.log)
```
Upload error: 3 - Die Datei konnte nur teilweise übertragen werden 2015-02-12T16:47:26+00:00 
```

Is my php version too old?

**Comment by PVince81** [comment]
Does a file of 4 or 5 GB work ? (to rule out the > 2.2 GB limit)

**Comment by shoeper** [comment]
A 4GB (4294967296Byte) file throws the same error.

**Comment by RealRancor** [comment]
Not quite sure if this is related but just quoting from the PHP 5.6.0 changelog:

>Uploads equal or greater than 2GB in size are now accepted.

http://php.net/ChangeLog-5.php#5.6.0

**Comment by shoeper** [comment]
Hmm, 3,8GB upload works fine ...

**Comment by shoeper** [comment]
ok, as also being written here http://cweiske.de/tagebuch/php-large-file-uploads.htm (german) this seems to be a php issue as @RealRancor said. Files bigger than 4 GB should work in php 5.6 (I'll give it a try).
It's just confusing why they talk about more than 2 GiB when 4 GiB minus some bytes files do already work in php 5.4.

Will give some feedback later on if it works with php 5.6 and how one installs it on wheezy.

**Comment by MorrisJobke** [comment]
@RealRancor Is this something we should put into the documentation? cc @carlaschroder

**Comment by carlaschroder** [comment]
Given the issues with different filesystems, PHP versions, and Windows, I'm thinking this would be a great Wikl document. I'll poke the powers-that-be into enabling one.

**Comment by carlaschroder** [comment]
In owncloud/documentation

**Comment by carlaschroder** [comment]
My apologies, I lost track of this! I copied it to the documentation Wiki. It's also on my list to review the admin manual. Thank you @shoeper

**Comment by carlaschroder** [comment]
https://github.com/owncloud/documentation/wiki/Uploading-files-up-to-16GB
