### ISSUE TITLE
Changing the user / group raw filter in the LDAP wizard doesn't update the user / group count

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#14161]
### Steps to reproduce
1. Start setting a new ldap configuration
2. In the user filter tab, set a valid raw filter which can pick up some users (tested with `(|(&(objectclass=inetOrgPerson)(sn=a*)))`

### Expected behaviour
The user count should be updated (in this case, it should show 18 users)

### Actual behaviour
The user count doesn't get updated (it shows 0 users). The list of users shows correctly in the users page

### Notes
This also happens with the group filter

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** sqlite3

**PHP version:** 5.5.9

**ownCloud version:** ownCloud 7.0.5 RC1 (testing) 

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by karlitschek** [comment]
@blizzz

**Comment by jvillafanez** [comment]
It's not reproducible in OC 8.0 (stable)

**Comment by felipediasssss** [comment]
I have the same problem in 7.0.4. After update from 7.0.3 the users disappear. Also when making a search in ./occ ldap:search, there is no user. Using the same filter with ldapsearch is ok.

**Comment by blizzz** [comment]
@jvillafanez do you confirm @felipediasssss observations?

**Comment by jvillafanez** [comment]
@blizzz I can't confirm it.

I've started with 7.0.3 and a user filter similar to the above (just changing sn=a* to sn=b*) without setting groups and the users page shows the filtered users fine. Just the user count in the wizard is the one wrong.
After upgrading to 7.0.4 without touching the configuration, it shows the same set of users in the users page (and the same issue with the user count in the wizard). Anyway, the users are still there.

Notice that my issue is just with the user count in the LDAP wizard, but the users are shown fine in the users page

**Comment by blizzz** [comment]
@felipediasssss can you please open a bug report of your own (after revising your config)?

**Comment by blizzz** [comment]
@jvillafanez although the spinner appears, the counting method is not triggered for some reason. Works with experienced mode (with the checkbox check on first tab), but there counting is triggered manually.

**Comment by blizzz** [comment]
Okay, it seems master is not affected, because it got https://github.com/owncloud/core/pull/11837. Which got permission to to be backported… Alas it is a big changeset and tough to get back to stable7. At least my attempts so far did not went far, failed with the first commits. 

I will try to get a dedicated fix for this issue. Might be even trivial, as far as i could make out the bad spot, let's see.

**Comment by DeepDiver1975** [comment]
@blizzz what is the status with this? close? 7.0.6? or maybe already fixed for 7.0.5? THX

**Comment by blizzz** [comment]
sorry, 7.0.6.

**Comment by cmonteroluque** [comment]
LDAP Wizard issues to be addressed by upgrading to 8
