### ISSUE TITLE
RandomLib - "open_basedir restriction in effect" errors

### ISSUE THREAD

**Issue by Jolk** [owncloud/core#14165]
### Steps to reproduce
1. install Owncloud 8 on shared webhosting account with open_basedir restrictions
2. use it
3. check logs

### Expected behaviour
no error messages

### Actual behaviour / Logged Error
log gets filled with following error:

file_exists(): open_basedir restriction in effect. File(/dev/urandom) is not within the allowed path(s): (xxxxxxxxxxxxxxxx) at /var/xxxx/owncloud/3rdparty/ircmaxell/random-lib/lib/RandomLib/Source/URandom.php#57

### Server configuration
**Database:** mySQL
**PHP version:** 5.5.20
**ownCloud version:** 8.0
**Updated from an older ownCloud or fresh install:** updated

**Comment by Jolk** [comment]
### Possible Fix: Update RandomLib?
see https://github.com/ircmaxell/RandomLib/commit/ddacd6d1269c51cf130e5fdb858b3e222da65d95

**Comment by LukasReschke** [comment]
v1.1.0 was released 28 days ago and fixes this and other bugs. I'll sync with upstream. (though it is not really the best practise to have `/dev/urandom` inaccessible ;-))
