### ISSUE TITLE
Use Sabre's PartialUpdate plugin for chunking

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#14162]
I noticed that SabreDAV has some interfaces and plugins to handle partial uploads:
https://github.com/owncloud/3rdparty/tree/master/sabre/dav/lib/Sabre/DAV/PartialUpdate

Maybe at some point we could port our chunking stuff there.

It seems to imply that instead of doing a PUT, one does a PATCH request to upload pieces of files.

Something to research at some point :smile:

Also interesting seems to be "IMultiGet" in the new Sabre 2 version.

@DeepDiver1975 @icewind1991

**Comment by PVince81** [comment]
and I see there's also something called "WebDAVSync". Not sure if that works with files.

Things to look into for better Sabre integration:
- [ ] partial update: https://github.com/owncloud/3rdparty/tree/master/sabre/dav/lib/Sabre/DAV/PartialUpdate
- [ ] IMultiGet
- [ ] WebDAV sync

**Comment by DeepDiver1975** [comment]
We had a look at webdav sync quite some back.
It basically works in change sets - would require a total different architecture. 
Furthermore I have no idea if this works with our external storage approach.

**Comment by PVince81** [comment]
Maybe similar to what @icewind1991 proposed here: https://github.com/owncloud/core/issues/4936

**Comment by PVince81** [comment]
Or IPatchSupport: https://github.com/owncloud/core/issues/16524

**Comment by DavidAnderson684** [comment]
+1 for supporting PartialUpdate; or at least just the "append" method documented here - http://sabre.io/dav/http-patch/ - that looks fairly simple.

**Comment by PVince81** [comment]
we went for another custom protocol, closing for now

**Comment by DavidAnderson684** [comment]
@PVince81 is the protocol documented anywhere? I tried Googling, but did not find the answer.

**Comment by PVince81** [comment]
the spec is here https://dragotin.wordpress.com/2015/06/22/owncloud-chunking-ng/ but I see it's not accurate as the endpoint is "remote.php/dav/uploads" not "remote.php/uploads".

hasn't been streamlined into the docs yet: https://github.com/owncloud/documentation/issues/2864
