### ISSUE TITLE
With PHP 5.5.21, reported version is < 5.4 when accesing  /owncloud ....

### ISSUE THREAD

**Issue by SevenSeasWinds** [owncloud/core#14163]
I had installed ownCloud 8 in my Centos 6.6 with PHP 5.5 and mySQL 5.5 and apache 2.2 

When I try to access my domain , it gives an exception related to the version : 

. * */ // Show warning if a PHP version below 5.4.0 is used, this has to happen here // because base.php will already use 5.4 syntax. if (version_compare(PHP_VERSION, '5.4.0') === -1) { echo 'This version of ownCloud requires at least PHP 5.4.0
'; echo 'You are currently running ' . PHP_VERSION . '. Please update your PHP version.'; return; } try { require_once 'lib/base.php'; OC::handleRequest(); } catch(\OC\ServiceUnavailableException $ex) { \OCP\Util::logException('index', $ex); //show the user a detailed error page OC_Response::setStatus(OC_Response::STATUS_SERVICE_UNAVAILABLE); OC_Template::printExceptionErrorPage($ex); } catch (\OC\HintException $ex) { OC_Response::setStatus(OC_Response::STATUS_SERVICE_UNAVAILABLE); OC_Template::printErrorPage($ex->getMessage(), $ex->getHint()); } catch (Exception $ex) { \OCP\Util::logException('index', $ex); //show the user a detailed error page OC_Response::setStatus(OC_Response::STATUS_INTERNAL_SERVER_ERROR); OC_Template::printExceptionErrorPage($ex); }

Apache error log :
---------------------
[Thu Feb 12 12:43:51 2015] [error] [client 200.123.162.45] File does not exist: /home/1.vnct3008.avnam.net/public_html/owncloud
[Thu Feb 12 12:43:51 2015] [error] [client 200.123.162.45] File does not exist: /home/1.vnct3008.avnam.net/public_html/owncloud
[Thu Feb 12 13:09:06 2015] [error] [client 128.199.207.123] File does not exist: /var/www/html/owncloud/index.php/apps/files_sharing/ajax/publicpreview.php

Apache access log :+1: 
200.123.162.45 - - [12/Feb/2015:13:27:03 -0300] "GET /owncloud/status.php HTTP/1.1" 200 861 "-" "Mozilla/5.0 (Windows) mirall/1.7.1"
200.123.162.45 - - [12/Feb/2015:13:27:36 -0300] "GET /owncloud/status.php HTTP/1.1" 200 861 "-" "Mozilla/5.0 (Windows) mirall/1.7.1"
200.123.162.45 - - [12/Feb/2015:13:28:08 -0300] "GET /owncloud/status.php HTTP/1.1" 200 861 "-" "Mozilla/5.0 (Windows) mirall/1.7.1"
200.123.162.45 - - [12/Feb/2015:13:28:40 -0300] "GET /owncloud/status.php HTTP/1.1" 200 861 "-" "Mozilla/5.0 (Windows) mirall/1.7.1"
128.199.207.123 - - [12/Feb/2015:13:28:56 -0300] "GET /owncloud/ HTTP/1.1" 304 - "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36 OPR/27.0.1689.69"
200.123.162.45 - - [12/Feb/2015:13:29:12 -0300] "GET /owncloud/status.php HTTP/1.1" 200 861 "-" "Mozilla/5.0 (Windows) mirall/1.7.1"
200.123.162.45 - - [12/Feb/2015:13:29:44 -0300] "GET /owncloud/status.php HTTP/1.1" 200 861 "-" "Mozilla/5.0 (Windows) mirall/1.7.1"
200.123.162.45 - - [12/Feb/2015:13:30:16 -0300] "GET /owncloud/status.php HTTP/1.1" 200 861 "-" "Mozilla/5.0 (Windows) mirall/1.7.1"
200.123.162.45 - - [12/Feb/2015:13:30:48 -0300] "GET /owncloud/status.php HTTP/1.1" 200 861 "-" "Mozilla/5.0 (Windows) mirall/1.7.1"
128.199.207.123 - - [12/Feb/2015:13:31:15 -0300] "GET /owncloud/ HTTP/1.1" 304 - "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36 OPR/27.0.1689.69"
200.123.162.45 - - [12/Feb/2015:13:31:20 -0300] "GET /owncloud/status.php HTTP/1.1" 200 861 "-" "Mozilla/5.0 (Windows) mirall/1.7.1"
200.123.162.45 - - [12/Feb/2015:13:31:52 -0300] "GET /owncloud/status.php HTTP/1.1" 200 861 "-" "Mozilla/5.0 (Windows) mirall/1.7.1"
200.123.162.45 - - [12/Feb/2015:13:32:24 -0300] "GET /owncloud/status.php HTTP/1.1" 200 861 "-" "Mozilla/5.0 (Windows) mirall/1.7.1"
200.123.162.45 - - [12/Feb/2015:13:32:56 -0300] "GET /owncloud/status.php HTTP/1.1" 200 861 "-" "Mozilla/5.0 (Windows) mirall/1.7.1"
200.123.162.45 - - [12/Feb/2015:13:33:28 -0300] "GET /owncloud/status.php HTTP/1.1" 200 861 "-" "Mozilla/5.0 (Windows) mirall/1.7.1"
200.123.162.45 - - [12/Feb/2015:13:34:00 -0300] "GET /owncloud/status.php HTTP/1.1" 200 861 "-" "Mozilla/5.0 (Windows) mirall/1.7.1"
200.123.162.45 - - [12/Feb/2015:13:34:32 -0300] "GET /owncloud/status.php HTTP/1.1" 200 861 "-" "Mozilla/5.0 (Windows) mirall/1.7.1"
200.123.162.45 - - [12/Feb/2015:13:35:04 -0300] "GET /owncloud/status.php HTTP/1.1" 200 861 "-" "Mozilla/5.0 (Windows) mirall/1.7.1"
200.123.162.45 - - [12/Feb/2015:13:35:36 -0300] "GET /owncloud/status.php HTTP/1.1" 200 861 "-" "Mozilla/5.0 (Windows) mirall/1.7.1"
200.123.162.45 - - [12/Feb/2015:13:36:08 -0300] "GET /owncloud/status.php HTTP/1.1" 200 861 "-" "Mozilla/5.0 (Windows) mirall/1.7.1"

**Comment by LukasReschke** [comment]
This looks more like you configured your Webserver incorrectly and it does not serve PHP at all.

That said:
> Thanks a lot for reporting issues back to us!
> 
> We need some more information to properly support you with your issue!
>
> Can I ask you to follow our guidelines for submitting bugs as described here: > https://github.com/owncloud/core/blob/master/CONTRIBUTING.md
>
> Thanks a lot!

**Comment by RealRancor** [comment]
Not quite sure if this is related but just quoting from the PHP 5.6.0 changelog:

> Uploads equal or greater than 2GB in size are now accepted.

http://php.net/ChangeLog-5.php#5.6.0

**Comment by LukasReschke** [comment]
@RealRancor Wrong issue? :smile:

**Comment by SevenSeasWinds** [comment]
I will try to remove php55 and let you know if it works... It seems I broke tha Apache when upgraded to 5.5 from 5.3 , instead of adding a new instance of php.




-----Original Message-----

**Comment by RealRancor** [comment]
@LukasReschke 
Yes, definitely the wrong issue. :)

**Comment by intdel** [comment]
I am having the same issue. Upgraded via aptitude upgrade and now I get following error:

. * */ // Show warning if a PHP version below 5.4.0 is used, this has to happen here // because base.php will already use 5.4 syntax. if (version_compare(PHP_VERSION, '5.4.0') === -1) { echo 'This version of ownCloud requires at least PHP 5.4.0
'; echo 'You are currently running ' . PHP_VERSION . '. Please update your PHP version.'; return; } try { require_once 'lib/base.php'; OC::handleRequest(); } catch(\OC\ServiceUnavailableException $ex) { \OCP\Util::logException('index', $ex); //show the user a detailed error page OC_Response::setStatus(OC_Response::STATUS_SERVICE_UNAVAILABLE); OC_Template::printExceptionErrorPage($ex); } catch (\OC\HintException $ex) { OC_Response::setStatus(OC_Response::STATUS_SERVICE_UNAVAILABLE); OC_Template::printErrorPage($ex->getMessage(), $ex->getHint()); } catch (Exception $ex) { \OCP\Util::logException('index', $ex); //show the user a detailed error page OC_Response::setStatus(OC_Response::STATUS_INTERNAL_SERVER_ERROR); OC_Template::printExceptionErrorPage($ex); }

**Comment by intdel** [comment]
An apt-get install php5 libapache2-mod-php5 fixed it.

**Comment by RealRancor** [comment]
Yes, PHP is needed for ownCloud. This is also described in:

http://doc.owncloud.org/server/8.0/admin_manual/installation/source_installation.html#example-installation-on-ubuntu-14-04-lts-server

**Comment by intdel** [comment]
@RealRancor  of course it is needed. It was working just fine before the 8.0 upgrade. I guess the upgrade process removed the php module.

**Comment by LukasReschke** [comment]
@jnweiger Packaging fun?

**Comment by RealRancor** [comment]
@intdel 
Ah, sorry. Missed that this happened during an upgrade.

Maybe have a look at your /var/log/apt/* logfiles to see why those packages where removed.

**Comment by SevenSeasWinds** [comment]
The solution is to add these entries in http.conf =

AddType application/x-httpd-php .php .htm .html
AddType application/x-httpd-php-source  .phps
AddType application/x-httpd-php5 .php .htm .html
  
  Always happening after an upgrade.

-----Original Message-----

**Comment by RealRancor** [comment]
@SevenSeasWinds 
Yes, this is a configuration issue in your webservers config where you don't have configured it correctly for PHP.
