### ISSUE TITLE
Cannot WebDAV upload file into shared folder as recipient with enc enabled

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#14169]
### Steps to reproduce
1. Enable encryption (note: I haven't tried without it yet)
1. Log out and log in again as admin ("root")
1. Create a user "user1"
1. Login as "user1"
1. Create folder "folder"
1. Share "folder" with "root"
1. With a WebDAV client (cadaver), login as "root"
1. PUT a file into "folder"

### Expected result
Upload works.

### Actual result
```
{"reqId":"JhB52rcUn5cVvkFUgjdg","remoteAddr":"127.0.0.1","app":"PHP","message":"filemtime(): stat failed for \/srv\/www\/htdocs\/owncloud\/data\/user1\/files\/folder\/test.txt at \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/storage\/local.php#138","level":0,"time":"2015-02-12T17:41:16+00:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/folder\/test.txt"}
{"reqId":"JhB52rcUn5cVvkFUgjdg","remoteAddr":"127.0.0.1","app":"PHP","message":"filesize(): stat failed for \/srv\/www\/htdocs\/owncloud\/data\/user1\/files\/folder\/test.txt at \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/storage\/local.php#121","level":0,"time":"2015-02-12T17:41:16+00:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/folder\/test.txt"}
{"reqId":"JhB52rcUn5cVvkFUgjdg","remoteAddr":"127.0.0.1","app":"remote","message":"An exception occurred while executing 'INSERT INTO `oc_filecache` (`mimepart`, `mimetype`, `mtime`, `size`, `etag`, `storage_mtime`, `permissions`, `path_hash`, `path`, `parent`, `name`, `storage`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"8\", \"8\", false, false, \"54dce5bc58456\", false, 0, \"8b56397656221e042b8dc40fe87f9e5a\", \"files\\\/folder\\\/test.txt\", \"28\", \"test.txt\", \"3\"]:\n\nSQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column 'mtime' at row 1","level":4,"time":"2015-02-12T17:41:16+00:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/folder\/test.txt"}
```

### Versions
ownCloud 8.1 pre-alpha git master (8e8acad550e45dfd7b17efca2fcb41582cd09e36)

@schiesbn @icewind1991 I suspect it might be related to the "reuse file id" PR.

Going to bisect this now.

Edit: added missing "share" step

**Comment by PVince81** [comment]
Only happens for newly created files (overwriting existing works)

This is the bad commit: 9df18ffe75589ecf45bf6802dae1024ce3f03785, part of https://github.com/owncloud/core/pull/10993

@icewind1991 please have a look. Thanks

**Comment by PVince81** [comment]
Please also add a unit test to protect against such regressions.

**Comment by icewind1991** [comment]
cant reproduce this...

Also I cant see any way that commit causes such a problem...

**Comment by PVince81** [comment]
This was with mariadb-10.0.14-2.3.x86_64 in case that makes a difference.
Did you follow the exact same steps ?

**Comment by PVince81** [comment]
Still happening on master (732541448136d41b97a7fc77f6efb23d6d893f3f)

I'll try with another DB to rule out mariadb.

**Comment by PVince81** [comment]
Ah, it works with sqlite!

**Comment by PVince81** [comment]
Cannot reproduce on master (a672e9d5563998205923b3b388208bb4b8242048) with the new encryption. Closing.
