### ISSUE TITLE
Weird user count in the users page with filtered LDAP users

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#14164]
### Steps to reproduce
1. Start setting a new configuration
2. In the user filter tab, set a valid raw filter which can pick up some users (tested with `(|(&(objectclass=inetOrgPerson)(sn=a*)))`
3. In the group tab set a valid filter. The filtered groups should have some members (tested with `(&(|(objectclass=groupOfNames)))`)
4. Go to the users page

### Expected behaviour
The user counts of the groups should take into account the users that are filtered. 

### Actual behaviour
- The "Everyone" group shows the user list fine (in our case, only users whose surname starts with "a" shows up), but the user count is wrong.
- Other groups doesn't seems to respect the user filter, so it shows a non-filtered list of users. The user count is also wrong as it shows as if there is no filter

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** sqlite3

**PHP version:** 5.5.9

**ownCloud version:** ownCloud 7.0.5 RC1 (testing) 

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by jvillafanez** [comment]
I'm not sure if this could be a cache issue because now the "Everyone" group shows the right number, although the other groups not. If this is the case, it could be a good idea the clear the cache if the filters change.

**Comment by jvillafanez** [comment]
Still reproducible in 8.1 alpha 1

**Comment by blizzz** [comment]
We decided not to show counts on Users page for performance reason when LDAP is enabled. Thus, this got invalid.
