### ISSUE TITLE
If WebDav is activated i can not create a new user

### ISSUE THREAD

**Issue by Nemofly** [owncloud/core#14177]
If I enable Webdavauth i can not create an new owncloud user.
if i disable it, i can create a user.

Anyone know why?

**Comment by LukasReschke** [comment]
Yes. Read the documentation - that helps ;-)

**Comment by LukasReschke** [comment]
![screen shot 2015-02-12 at 21 40 57](https://cloud.githubusercontent.com/assets/878997/6176521/da996baa-b2ff-11e4-9ca1-d37f1a318ffe.png)

**Comment by Nemofly** [comment]
i do not use LDAP Backend  and it is not activated. So i can read! but i do not know the Problem...
![unbenannt](https://cloud.githubusercontent.com/assets/10982849/6177353/3a53c544-b306-11e4-98eb-7808f7ffc3a5.PNG)

**Comment by LukasReschke** [comment]
Why did you enable the "WebDAV User Backend"?

**Comment by LukasReschke** [comment]
What do you think is it good for?

**Comment by Nemofly** [comment]
i want you sync pictures from ios and ipad

**Comment by LukasReschke** [comment]
Then go back to https://github.com/owncloud/core/issues/14177#issuecomment-74148523 and read the whole marked part. Also the one after the first dot ;-)

**Comment by shoeper** [comment]
That does not need the "WebDAV User Backend".
The "WebDAV User Backend" is used to authenticate users using another WebDAV server with existing users. The benefit would be that you don't have to manage all users twice. That's also the reason why you cannot create new users when you enable the "WebDAV User Backend".

Syncing files with iOS works out of the box. So you should not enable this plugin.
