### ISSUE TITLE
Change-Date of a folder in the webinterface shows wrong time

### ISSUE THREAD

**Issue by zocker22** [owncloud/core#14172]
I discovered that in the webview of owncloud the "latest modified" timestamp ist not as I epect it to be. Maybe I am wrong, than please correct me.

Steps to reproduce the error:
1) Create a folder (a) with a client and let it sync with owncloud
2) Create a NEW file (b1) (with current timestamp as modfied date) and save it into that folder
3) let it sync with owncloud - when viewing the parent folder of (a) in ownclouds webview it shows the timestamp of file (b1) as latest modified date - so far so good.
4) Move a old file (b2) (PDF, or what ever) with an very olde modified timestamp into the folder (a)
5) Let it sync with owncloud - when viewing the parent folder of (a) in ownclouds webview it says that the latest modified date is the one of file (b2). Which means very, very old.

I would epect owncloud to display the most up to date timestamp of file (b1) or the time when I moved the old file (b1) into the folder (a). 
This means I have moved an old file into my folder and suddendly the latest modified date jumps back a view years :-)

**Comment by karlitschek** [comment]
Hmmm. Interesting bug. @icewind1991

**Comment by PVince81** [comment]
Possibly closed by mistake. The PR is still open.
Reopening.
