### ISSUE TITLE
Bump password_compat

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#14181]
Let's wait until RandomLib has been bumped.

**Comment by DeepDiver1975** [comment]
Just like all the other dependencies - @nickvergessen some spare time? THX

**Comment by DeepDiver1975** [comment]
@LukasReschke is there an open pr? please link - THX

**Comment by LukasReschke** [comment]
If there would be I would have linked :see_no_evil:

**Comment by PVince81** [comment]
Defering lib update to 9.0
