### ISSUE TITLE
Scrolling stops loading users in the users page after changing the group view

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#14189]
### Steps to reproduce
1. Create 90 users and assign 50 users to a group (group A), and 40 to another (group B). You can assign them to the groups at the same time that they're being created
2. Make sure you can scroll to see all the users
3. Go to the group A, with 50 users. You should be able to scroll to see all the 50 users
4. Go to the "Everyone" group. You should be able to scroll to see all the users.

### Expected behaviour
In each view, you should be able to see all the users belonging to that group

### Actual behaviour
The view only shows the first 30 users of the group, and the scrolling can't load more users

### Notes
Checked with local users in OC 7.0.4 (git) and with LDAP users in 7.0.5 (testing). Reproducible in both cases

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** sqlite3

**PHP version:** 5.5.9

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by DeepDiver1975** [comment]
> Checked with local users in OC 7.0.4 (git) and with LDAP users in 7.0.5 (testing). Reproducible in both cases

please double check master branch as well - THX

**Comment by jvillafanez** [comment]
I cannot reproduce it in OC 8.0 (stable) with LDAP users. I'll check in master

**Comment by DeepDiver1975** [comment]
well - OC8 got a lot of improvements to be capable to work around the limited capabilities of previous versions. I fear the change set will be too big to fix this

**Comment by MorrisJobke** [comment]
cc @blizzz @LukasReschke We should maybe have a look at this in the 7.0.6 cycle ... maybe we can backport some little fixes

**Comment by cmonteroluque** [comment]
not planning to fix in 7
