### ISSUE TITLE
OC 8.0: versions/restore issues

### ISSUE THREAD

**Issue by zebtom** [owncloud/core#14183]
When restoring an older version of a file (click on 'Versions' and then 'Restore') the web UI is not refreshed in OC8. The file is actually restored, but the main window is not refreshed, which is a bit confusing. In OC 7.0.x, the web UI is refreshed after a file is restored.

Also, in OC8 file preview in the 'Versions' menu doesn't work (at least for .txt, .php, .c, ... files).

Both issues confirmed on demo.owncloud.org

**Comment by karlitschek** [comment]
@schiesbn Can you have a look?

**Comment by PVince81** [comment]
Duplicate of https://github.com/owncloud/core/issues/14559
Already resolved, works in 8.0.6 or 8.1.1.
