### ISSUE TITLE
Owncloud 8 crashes Apache on brand new fresh install Ubuntu 14.04 [Workaround]

### ISSUE THREAD

**Issue by BoBeR182** [owncloud/core#14188]
Hey everyone,

I was experiencing the same issue on a new installation, and after some digging around I have successfully concluded that the issue was the cache that was being used.

FYI im on ubuntu 14.04 server.

after running apt-cache depends owncloud i get the following list

Depends: owncloud-server
Depends: owncloud-config-apache
Depends: owncloud-3rdparty
Depends: owncloud-app-activity
Depends: owncloud-app-files
Depends: owncloud-app-files-encryption
Depends: owncloud-app-files-pdfviewer
Depends: owncloud-app-files-trashbin
Depends: owncloud-app-firstrunwizard
Depends: owncloud-app-templateeditor
Depends: owncloud-app-user-ldap
Depends: owncloud-app-external
Depends: owncloud-app-files-external
Depends: owncloud-app-files-sharing
Depends: owncloud-app-files-versions
Depends: owncloud-app-gallery
Depends: owncloud-app-updater
Depends: owncloud-app-user-webdavauth
Depends: owncloud-app-files-locking
Depends: owncloud-app-files-texteditor
Depends: owncloud-app-files-videoviewer
Depends: owncloud-app-provisioning-api
Depends: owncloud-app-user-external
|Suggests: clamav
Suggests: clamav-daemon
Suggests: smbclient
Suggests: libreoffice-writer
Recommends: mysql-server
Recommends: curl
curl:i386
|Recommends: exim4
Recommends: <mail-transport-agent>
citadel-mta
courier-mta
esmtp-run
exim4-daemon-light
lsb-invalid-mta
masqmail
msmtp-mta
nullmailer
opensmtpd
qmail-run
sendmail-bin
ssmtp
xmail
dma:i386
dma
exim4-daemon-heavy
postfix
|Recommends: php5-apcu
Recommends: <php5-apc>
Conflicts: <owncloud-fhs>
Conflicts: <owncloud-fhs:i386>

As you can see that php5-apc conflicts with the owncloud fhs so php5-apcu is installed instead. This was confirmed by running apt-cache policy on both php5-apc and php5-apcu.

Seeing as that is a recommended package I proceeded to purge it from the system. Owncloud functionality was not effected at all. My OC has been up for over 12 hours now.

Wanted to share this with you all as I hope it will help alot of you as it helped me.

**Comment by simonnzg** [comment]
Aha. I've noticed OC8 was giving Apache trouble and was looking on here for answers. My task was complicated by having migrated from SQLite to MySQL at the same time as I upgraded, so wasn't sure if that was part of the problem, but removing php5-apcu seems to have done the trick here, too.

**Comment by arm2arm** [comment]
You cannot use 2 caching modules at the same time. Select between apcu it is newer.

**Comment by DeepDiver1975** [comment]
@jnweiger please have a look - THX

**Comment by simonnzg** [comment]
It depends if php5-apc is Requires anywhere else on the particular computer installation. Best to remove the conflicting Recommended. Not ideal, but avoids too much hell.

**Comment by jnweiger** [comment]
On Ubuntu-14.04, the situation with apc is tricky.
When I ask for apc, I automatically get apcu. This is what happens to me:

    # apt-get install php-apc
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    The following extra packages will be installed:
      lsof php5-apcu php5-common php5-json psmisc
    Suggested packages:
      php5-gd php5-user-cache
    The following NEW packages will be installed:
      lsof php-apc php5-apcu php5-common php5-json psmisc


@BoBeR182 I don't follow your description with the conflicts. The package owncloud-fhs is not installed at all. It has no influence on the dependency resolution. Also, it does not conflict with any *apc* or *apcu* packages.

I'll fix one error in the Recomends: line. It asks for either php5-apcu or php5-apc -- A package 'php5-apc' does not exist in debian universe. It should say php-apc, without a '5'. 

I'll also make it a Suggests: instead. Unless we have a strong reason to advocate for a caching system, I see this negative experience as a valid reason to not Recommend any.

**Comment by enoch85** [comment]
following

**Comment by enoch85** [comment]
Now, this is a workaround:

**1.** Create a bash script
```
#!/bin/bash
sudo -i & 
sudo apache2 restart
```
**2.** Setup a cronjob
`crontab -e`

**3.** Make the script run every 3 hour (that´s about when the server crashes
```
00 */3 * * * your_script.sh
```
**4.** Delete the crontab when this is fixed(!)

**Comment by simonnzg** [comment]
I made a very similar script, but it simply hupped apache every couple of
hours.

**Comment by enoch85** [comment]
Closing this, here is the final fix: https://github.com/owncloud/core/issues/14175#issuecomment-74573088

Please track this issue here: #14175
