### ISSUE TITLE
Creating a user inside a group view in the users page doesn't add it to the group or fliter him out

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#14186]
### Steps to reproduce
1. Create a new user and add it to a new group
2. Click in the new group (in the sidebar) to filter the users
3. Add a new user and don't add him to the group

### Expected behaviour
The user is automatically added to the group and shows in the filtered list, or the user isn't automatically added to the group but it isn't shown in the group (the user is always created and assigned to the groups selected by the user)

### Actual behaviour
The user is created and shows up in the filtered list even though the user doesn't belong to the group

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** sqlite3

**PHP version:** 5.5.9

**ownCloud version:** ownCloud 7.0.5 RC1 (testing)

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by jvillafanez** [comment]
Reproducible with OC 8.0 (stable)

**Comment by PVince81** [comment]
This was fixed on master already recently with https://github.com/owncloud/core/pull/15258, closing.
