### ISSUE TITLE
Can't activate any apps in owncloud 8

### ISSUE THREAD

**Issue by mholschbach** [owncloud/core#14192]
When i try to activate any apps, only the message "Die Applikation enthält keine info,xml Datei" (App does not provide an info.xml file) is shown. I tried to activate Contacts 8.0, Calendar 8.0, Search Lucene 8.0, Bookmarks 8.0, Documents 8.0, ...

I suppose it's an php error within the downloadApp function implemented in lib/private/installer.php. The "copy($data['href'], $path);" doesn't follow the http to https redirect, because the downloaded file looks like this "zless ../tmp/oc_tmp_92fb120b99dd518f087e1aa86c9b161e.zip":
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://apps.owncloud.com/CONTENT/content-files/168707-calendar.zip">here</a>.</p>
</body></html>

My php Version is 5.4.37-1+deb.sury.org~lucid+1 and the php-cli is able to follow the redirect:    
<?php copy("http://apps.owncloud.com/CONTENT/content-files/168707-calendar.zip","168707-calendar.zip"); ?> downloads a zip file

1) Any idea why the copy funtion won't follow the redirect if executed within owncloud?

2) Why does owncloud try to download from http in the first place? If all the software and app packages are available by https, it's a bad choice to still rely on http.

**Comment by DeepDiver1975** [comment]
for me copy is following the redirect ... but using https is for sure reasonable

**Comment by DeepDiver1975** [comment]
@mholschbach you might want to give this change a try - https://github.com/owncloud/core/pull/14086 - THX

**Comment by DeepDiver1975** [comment]
> 2) Why does owncloud try to download from http in the first place? If all the software and app packages are available by https, it's a bad choice to still rely on http.

@karlitschek I just debugged this situation - looks like the final download url is returned from the appstore via an OCS call - is there any possibility to change this? THX

**Comment by mholschbach** [comment]
I replaced the copy line with the proposed change from #14086:
file_put_contents($path, \OC::$server->getHTTPHelper()->getUrlContent($data['href']));

Now i can successfully enable the apps. Thank you for your quick response.

And i would we very happy, if you modify the download of additional software packages to always use https.

**Comment by karlitschek** [comment]
@DeepDiver1975 Yes. This needs to be fixed. Not ultra urgent in my opinion but I will look into it.

**Comment by DeepDiver1975** [comment]
> I replaced the copy line with the proposed change from #14086:
> file_put_contents($path, \OC::$server->getHTTPHelper()->getUrlContent($data['href']));
> 
> Now i can successfully enable apps. Thank you for your quick response.
> 
> And i would be very happy, if you modify the download of additional software packages to always use https.

fixed for 8.0.1 with https://github.com/owncloud/core/pull/14198

**Comment by Metal-Frog** [comment]
Unfortunately I've still got the problem.
Version 8.0.07

**Comment by DeepDiver1975** [comment]
@Metal-Frog did you apply the patch #14086 ???

**Comment by Metal-Frog** [comment]
Yep, I've changed line 244.
And it doesn't work when I'm not behind a proxy either!

**Comment by DeepDiver1975** [comment]
@Metal-Frog maybe a different issue - please open a new issue here - THX

**Comment by joefalce** [comment]
changed line 244 I'm not behind a proxy same problem  version   owncloud-8.0.0 php 5.6.5
L'applicazione non fornisce un file info.xml --> App does not provide an info.xml file
even installing other packages like contacts

**Comment by nerdoc** [comment]
Same roblem here with 8.0.4 (freshly upgraded from 7.0.2). Calendar worked. I now even extracted the contacts zip file into /apps/, and then tried to activate it, but it is not found.

**Comment by nerdoc** [comment]
Funny. After clicking on "Deinstallieren", unzipping it again into the /apps/ dir, and activating it, everything works now.
