### ISSUE TITLE
Force .htaccess to select php v5.5 instead of server default

### ISSUE THREAD

**Issue by Rezonansowy** [owncloud/core#14205]
This version of php is required for OC 8. It is good to include the following line in .htaccess:
```
AddHandler php5.5-fastcgi php
```

**Comment by LukasReschke** [comment]
I believe this is something that should be handled on the server config, having this in our `.htaccess` looks out of scope.

**Comment by Rezonansowy** [comment]
This change has sense. Otherwise you have do this anyway. Including this in  .htaccess out of the box just simplify this process.

**Comment by DeepDiver1975** [comment]
> Including this in .htaccess out of the box just simplify this process.

well it will for sure break other installations and therfore I second @LukasReschke on his decission

**Comment by Rezonansowy** [comment]
@DeepDiver1975 What installations you mean? It won't break anything if it's only inside the OC folder.

**Comment by DeepDiver1975** [comment]
> What installations you mean?

installation which have no php5.5-fastcgi or installations which don't want to use 5.5 but 5.6

**Comment by Rezonansowy** [comment]
Is it possible to specify a minimum php version in htaccess?
