### ISSUE TITLE
Update error to master, key length issue with oc_file_map table 

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#14204]
Upgrading to 51f8d240c1c7a2c5fe4ab89854aeae02a33406b4

Very likely to be related to https://github.com/owncloud/core/pull/14171

Happens with:
mariadb-10.0.14-2.3.x86_64

![file_map_index](https://cloud.githubusercontent.com/assets/277525/6188469/a11dad90-b391-11e4-92eb-0c38f4ad6fbe.png)

@nickvergessen @LukasReschke

**Comment by PVince81** [comment]
Note: the table "oc_filemap" is completely empty.

**Comment by nickvergessen** [comment]
Works here: `MySQL Server version: 5.5.41-0ubuntu0.14.04.1 - (Ubuntu)`

But I can imagine something to be a problem here:
Column: `physic_path	varchar(512)`
Index: `file_map_physic_path	physic_path (255)`

But we can revert it, until we found another solution. (jenkins seems to fail aswell all of a sudden, maybe that's related)

**Comment by nickvergessen** [comment]
Seems like something automatically sets the key length, although none is specified
