### ISSUE TITLE
[LDAP wizard] login filter should enforce the usage of the user filter

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#14202]
Ideally the login filter should pick a subset of the users filtered by the user filter. This is done fine following the steps with the wizard, but the user can choose to save a different raw filter.

1. In the wizard, go to the user filter tab and use (for example) the filter: `(|(&(objectclass=inetOrgPerson)(sn=a*)))`
2. Go to the login filter and click in the "edit raw filter"
3. The raw filter shown uses the correct user filter (with the uid option added)
4. You can edit the filter to use another one: (&(|(&(objectclass=inetOrgPerson)(sn=b*)))(uid=%uid))

In this scenario, the admin can see all users whose surname starts with an "a", but none of then will be able to access. Plus all users whose surname starts with "b" can login, but they're not shown in the users page

**Comment by karlitschek** [comment]
@blizzz

**Comment by blizzz** [comment]
This is intended behaviour. For instance you can create some system users that will not show up in the lists or share dialogues, but are able to to operate. Of course it works vice versa which makes less sense, but then again it's an admin decision…
