### ISSUE TITLE
Consider requiring authentication to perform database upgrades

### ISSUE THREAD

**Issue by strugee** [owncloud/core#14219]
Currently, AFAICT, when the ownCloud installation is upgraded, ownCloud will show the "ownCloud will be upgraded" screen to _anyone_ who loads the page. This is unfortunate because, as the page mentions, you should back up all your stuff before performing database upgrades, and if any user visits the page before the admin, they won't have the capability to do this and will probably just click through.

The solution would be to have the upgrade page require authentication with admin credentials before proceeding. I'm not sure how complicated this is, given that the app is in a semi-inconsistent state, but I figured I'd file an issue anyway.

Note that this scenario is more likely than you think - a lot of people will install ownCloud from a package manager (e.g. APT with the OBS repo) and then turn on automatic upgrades.

**Comment by shoeper** [comment]
Are database upgrades handled by the updater plugin? The updater plugin can be restricted to only allow admin access.

**Comment by Xenopathic** [comment]
Perhaps the best solution would be to have maintenance mode activated when an update is required and this feature is enabled, so that the admin must use `./occ` (or some sort of authenticated web interface) to perform the upgrade?

**Comment by karlitschek** [comment]
there is nothing that can be done in owncloud because we can't authenticate a user before the upgrade. best practices are to do it with the command line tool as described.

**Comment by shoeper** [comment]
Command line tool is not available on all shared hosting systems.
The admin password hash could get stored in the config. That would give us the possibility to authenticate the admin before upgrading the system/database.

**Comment by Xenopathic** [comment]
@karlitschek How about some way to disable the ability to perform an upgrade in the web interface? See my previous comment on a potential implementation.

**Comment by shoeper** [comment]
@Xenopathic Command line tool is not available on all shared hosting systems.

**Comment by r-daneel** [comment]
Actually, I also would at least allow for a parameter in the config file that prevents showing the db update page upon upgrade (maybe a maintenance page). The default could be the current  bahaviour.

**Comment by Xenopathic** [comment]
@shoeper I know that won't help in some shared hosting systems, but there are many cases where it would be very useful. Given that we don't/can't do authentication during an upgrade, I suspect it will be impossible to support this feature in environments where CLI access is forbidden.

**Comment by Xenopathic** [comment]
I opened a ticket to continue this idea: #14229

**Comment by shoeper** [comment]
I still don't know why authentication is an issue. Just save login data of the admin account(s) in the config and it won't be any problem to authenticate the admin for upgrading oc.
