### ISSUE TITLE
UTF-8 charset message does not disappear, even if UTF-8 is set.

### ISSUE THREAD

**Issue by MeCias** [owncloud/core#14216]
Hi guys,

I am running owncloud 8 on a hosted space, so I had to ask the provider to do the necessary changes to the php.ini. What they did. The php.info shows as follows:

![untitled](https://cloud.githubusercontent.com/assets/4476171/6191535/7c633470-b3aa-11e4-936b-123358f84cd0.jpg)

But in the admin area I still find this:

![utf-8_error](https://cloud.githubusercontent.com/assets/4476171/6191542/9792062c-b3aa-11e4-983e-ae36068f9f95.jpg)

Is there anything else I can change?

The four log entry's that are recurring over and over again are:

 {"reqId":"ca9580c7d18ecabaf23ebcb578953acb","remoteAddr":"222.222.222.222","app":"PHP","message":"Use of undefined constant CURLOPT_PROTOCOLS - assumed 'CURLOPT_PROTOCOLS' at \/home\/www\/web\/html\/cloud\/lib\/private\/httphelper.php#71","level":3,"time":"2015-02-13T12:07:02+00:00"}
{"reqId":"ca9580c7d18ecabaf23ebcb578953acb","remoteAddr":"222.222.222.222","app":"PHP","message":"Use of undefined constant CURLPROTO_HTTP - assumed 'CURLPROTO_HTTP' at \/home\/www\/web\/html\/cloud\/lib\/private\/httphelper.php#71","level":3,"time":"2015-02-13T12:07:02+00:00"}
{"reqId":"ca9580c7d18ecabaf23ebcb578953acb","remoteAddr":"222.222.222.222","app":"PHP","message":"Use of undefined constant CURLPROTO_HTTPS - assumed 'CURLPROTO_HTTPS' at \/home\/www\/web\/html\/cloud\/lib\/private\/httphelper.php#71","level":3,"time":"2015-02-13T12:07:02+00:00"}
{"reqId":"ca9580c7d18ecabaf23ebcb578953acb","remoteAddr":"222.222.222.222","app":"PHP","message":"curl_setopt() expects parameter 2 to be long, string given at \/home\/www\/web\/html\/cloud\/lib\/private\/httphelper.php#71","level":3,"time":"2015-02-13T12:07:02+00:00"}

I have no clue if that is related?

**Comment by RealRancor** [comment]
Hi,

not sure but this mentioned apache setting could be related:

https://stackoverflow.com/questions/9351694/setting-php-default-encoding-to-utf-8/9351983#9351983

**Comment by MorrisJobke** [comment]
For reference: It just checks the PHP setting: https://github.com/owncloud/core/blob/d665b7a4b1def34799fc386333f42497cb3aaeca/lib/private/util.php#L1432

**Comment by MeCias** [comment]
Hi,

Ok I figured it out.

I changed (uppercase UTF)

	return strtoupper(ini_get('default_charset')) === 'UTF-8';

to (lowercase utf)

	return strtoupper(ini_get('default_charset')) === 'utf-8';

and now the warning disappears.

**Comment by DeepDiver1975** [comment]
this is fixed with 8.1 - see https://github.com/owncloud/core/pull/14097

**Comment by RealRancor** [comment]
@DeepDiver1975 
Is it not useful to backport such a trivial change to 8.0.1 instead of waiting 3-4 months for the release of OC 8.1?

**Comment by karlitschek** [comment]
@deepdiver1975 can we backport this please?

**Comment by VincentvgNn** [comment]
Today, March 18th 2015, I installed server 8.0.2. and encountered this issue.
In this way I cannot release and promote OC as a reliable product.
When will 8.1 be ready?

**Comment by jormathog** [comment]
I too just install a virgin setup of owncloud 8.0.2 and am getting the same error:
# grep UTF /etc/php5/apache2/php.ini
default_charset = "UTF-8"
;mbstring.internal_encoding = UTF-8
;mbstring.http_input = UTF-8
# grep UTF /etc/php5/cli/php.ini
default_charset = "UTF-8"
;mbstring.internal_encoding = UTF-8
;mbstring.http_input = UTF-8

Will this cause problems going forward or do I need to wait until 8.1 comes out?

**Comment by RealRancor** [comment]
Its already fixed in OC 8.0.2:

https://github.com/owncloud/core/pull/14388

**Comment by jormathog** [comment]
If this issue is closed or resolved then why am I getting the error message still.  I have tried UTF-8 and utf-8 and the error message persists.  What else should I be looking at?

**Comment by VincentvgNn** [comment]
@karlitschek 
I have 2 instances of OC independently running at a webhost.
Server 7.0.4 no problem, server 8.0.2 just the problem as initially described here.

I have PHP v5.5.21 default_charset: no value
Did OC7 set a character set and does OC8 not do that?

Please reopen this issue.

**Comment by RealRancor** [comment]
Use a phpinfo to see the actual value of this.

**Comment by VincentvgNn** [comment]
@RealRancor 
I retrieved that setting ( PHP v5.5.21 default_charset: no value) by running phpinfo on Feb. 13th 2015.
I assume that my hosting company did not change that setting.
Again, it's a problem introduced at OC 8.
.

**Comment by RealRancor** [comment]
Yes, and you have no value which explains why you're getting this message. The message even says what to do.

Your problem currently has nothing to do with this initial issue reported here. The check is workingbas expected on your environment.

**Comment by VincentvgNn** [comment]
@RealRancor 
Thanks for your quick response.
Why do I not have this problem at OC 7? Was a check on the default_charset introduced in OC8?
Or did OC7 set a  default_charset and OC8 not?
For changing these settings I need to approach 2 webhosting companies.

**Comment by jormathog** [comment]
@RealRancor Thank you for your suggestion about creating a phpinfo page.  I was able to track down the problem and fix it.

**Comment by RealRancor** [comment]
@VincentvgNn 
I have no idea.

**Comment by VincentvgNn** [comment]
@RealRancor 
I solved it in the .htaccess file by putting the line ```php_value default_charset UTF-8``` just after the line ```AddDefaultCharset utf-8``` (as discussed at: https://forum.owncloud.org/viewtopic.php?f=31&t=26289&sid=05827e7c4d515e32f7b8fe62ec6022c4&start=10 and https://forum.owncloud.org/viewtopic.php?f=31&t=27138 )

How to get this solution in the installer packages?

**Comment by RealRancor** [comment]
Create a new issue as this is not related to this issue.
