### ISSUE TITLE
[OC 8 Upgrade] Unable to activate 3rd party apps

### ISSUE THREAD

**Issue by Tom-Schmidt** [owncloud/core#14226]
### Steps to reproduce
1. Upgrage to 8.0
2. Try to enable any recommended 3rd party app

### Expected behaviour
Enabled 3rd party app

### Actual behaviour
"App does not provide an info.xml file" - App won't be enabled.

### Server configuration
**Operating system**: Ubuntu 14.10

**Web server:** nginx

**Database:** MySQL

**PHP version:** 5.5.9

**ownCloud version:** 8.0

**Updated from an older ownCloud or fresh install:** Upgrade

**List of activated apps:**
Activity, Calendar, Contacts, Deleted Files, First Run Wizard, Mail Template Editor, PDF Viewer, Pictures, Share Files, Text Editor, Updater, Versions

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'oc8ab27a8968',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' =>
  array (
    0 => mydomain.com',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'https://mydomain.com',
  'dbtype' => 'mysql',
  'version' => '8.0.0.7',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'ocuser',
  'dbpassword' => '',
  'installed' => true,
  'forcessl' => true,
  'mail_from_address' => 'user',
  'mail_smtpmode' => 'php',
  'mail_domain' => '@provider.com',
  'maintenance' => false,
  'theme' => '',
);

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

### Client configuration
**Browser:** Firefox 35

**Operating system:** Windows 8.1

#### Web server error log
No relevant error log entries

#### ownCloud log (data/owncloud.log)
{"reqId":"a21c8fcc2fda26943a425ef26f9d1f85","remoteAddr":"88.153.xxx.xxx","app":"PHP","message":"ZipArchive::extractTo(): Invalid or unitialized Zip object at \/var\/www\/owncloud\/lib\/private\/archive\/zip.php#135","level":3,"time":"2015-02-14T17:01:51+00:00"}
{"reqId":"a21c8fcc2fda26943a425ef26f9d1f85","remoteAddr":"88.153.xxx.xxx","app":"core","message":"App does not provide an info.xml file","level":3,"time":"2015-02-14T17:01:51+00:00"}

#### Browser log
--

The third party apps calendar and contacts could be installed by wget to the app folder and enabling them.
They're still listed in Recommended apps as disabled. 

I did notice similar issue reports but none seemed to completely match my case.

**Comment by karlitschek** [comment]
which 3rdparty app do you try to enable? and how did you download and unpack it? 
the problem might be in the 3rdparty app and not in owncloud

**Comment by Tom-Schmidt** [comment]
I tried to enable all that are listed in the recommended section: Contacts 8, Calendar 8, Search Lucene 8, Bookmarks 8 and Documents 8. All with the same error message.

I used wget and the links https://apps.owncloud.com/CONTENT/content-files/168708-contacts.zip and https://apps.owncloud.com/CONTENT/content-files/168707-calendar.zip. Unzipped both in the app folder and enabled them with a press of a button in the oc not enabled apps section.

**Comment by Tom-Schmidt** [comment]
Trying once more via oc recommended apps to enable the Search Lucene 8 and afterwards other apps resulted in shortly displaying "enabled" for the Search Lucene app and the following log.
Search Lucene is now disabled again without my interference.

{"reqId":"2d120cdc8a41b83893fb6d4803938214","remoteAddr":"88.153.xxx.xxx","app":"core","message":"Unable to parse OCS content for app 166043","level":4,"time":"2015-02-14T21:10:02+00:00"}
{"reqId":"2d120cdc8a41b83893fb6d4803938214","remoteAddr":"88.153.xxx.xxx","app":"PHP","message":"get_headers(): php_network_getaddresses: getaddrinfo failed: Name or service not known at \/var\/www\/owncloud\/lib\/private\/httphelper.php#149","level":3,"time":"2015-02-14T21:10:22+00:00"}
{"reqId":"2d120cdc8a41b83893fb6d4803938214","remoteAddr":"88.153.xxx.xxx","app":"PHP","message":"get_headers(https:\/\/api.owncloud.com\/v1\/content\/data\/166054): failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known at \/var\/www\/owncloud\/lib\/private\/httphelper.php#149","level":3,"time":"2015-02-14T21:10:22+00:00"}
{"reqId":"2d120cdc8a41b83893fb6d4803938214","remoteAddr":"88.153.xxx.xxx","app":"PHP","message":"get_headers(): php_network_getaddresses: getaddrinfo failed: Name or service not known at \/var\/www\/owncloud\/lib\/private\/httphelper.php#149","level":3,"time":"2015-02-14T21:10:38+00:00"}
{"reqId":"2d120cdc8a41b83893fb6d4803938214","remoteAddr":"88.153.xxx.xxx","app":"PHP","message":"get_headers(https:\/\/api.owncloud.com\/v1\/content\/data\/166050): failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known at \/var\/www\/owncloud\/lib\/private\/httphelper.php#149","level":3,"time":"2015-02-14T21:10:38+00:00"}
{"reqId":"d5a909dfafb28b5337fa52cec95a9221","remoteAddr":"88.153.xxx.xxx","app":"core","message":"Unable to parse OCS content for app 166055","level":4,"time":"2015-02-14T21:10:47+00:00"}
{"reqId":"d5a909dfafb28b5337fa52cec95a9221","remoteAddr":"88.153.xxx.xxx","app":"PHP","message":"get_headers(): php_network_getaddresses: getaddrinfo failed: Name or service not known at \/var\/www\/owncloud\/lib\/private\/httphelper.php#149","level":3,"time":"2015-02-14T21:10:57+00:00"}
{"reqId":"d5a909dfafb28b5337fa52cec95a9221","remoteAddr":"88.153.xxx.xxx","app":"PHP","message":"get_headers(https:\/\/api.owncloud.com\/v1\/content\/data\/166054): failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known at \/var\/www\/owncloud\/lib\/private\/httphelper.php#149","level":3,"time":"2015-02-14T21:10:57+00:00"}
{"reqId":"aa26dc51119f6e262b422ee3fd7d7aaf","remoteAddr":"88.153.xxx.xxx","app":"core","message":"Unable to parse OCS content","level":4,"time":"2015-02-14T21:11:06+00:00"}
{"reqId":"2d120cdc8a41b83893fb6d4803938214","remoteAddr":"88.153.xxx.xxx","app":"core","message":"Unable to parse OCS content for app 166051","level":4,"time":"2015-02-14T21:11:10+00:00"}
{"reqId":"720d8ab15826a29453625c2b7b474026","remoteAddr":"88.153.xxx.xxx","app":"PHP","message":"ZipArchive::extractTo(): Invalid or unitialized Zip object at \/var\/www\/owncloud\/lib\/private\/archive\/zip.php#135","level":3,"time":"2015-02-14T21:14:51+00:00"}
{"reqId":"720d8ab15826a29453625c2b7b474026","remoteAddr":"88.153.xxx.xxx","app":"core","message":"App does not provide an info.xml file","level":3,"time":"2015-02-14T21:14:51+00:00"}
{"reqId":"5dc628b4addde2548ae5051f6a6a0f85","remoteAddr":"88.153.xxx.xxx","app":"PHP","message":"ZipArchive::extractTo(): Invalid or unitialized Zip object at \/var\/www\/owncloud\/lib\/private\/archive\/zip.php#135","level":3,"time":"2015-02-14T21:14:59+00:00"}
{"reqId":"5dc628b4addde2548ae5051f6a6a0f85","remoteAddr":"88.153.xxx.xxx","app":"core","message":"App does not provide an info.xml file","level":3,"time":"2015-02-14T21:14:59+00:00"}
{"reqId":"6dc68a056667ef122b391e9f74f34ae5","remoteAddr":"88.153.xxx.xxx","app":"PHP","message":"ZipArchive::extractTo(): Invalid or unitialized Zip object at \/var\/www\/owncloud\/lib\/private\/archive\/zip.php#135","level":3,"time":"2015-02-14T21:15:56+00:00"}
{"reqId":"6dc68a056667ef122b391e9f74f34ae5","remoteAddr":"88.153.xxx.xxx","app":"core","message":"App does not provide an info.xml file","level":3,"time":"2015-02-14T21:15:56+00:00"}
{"reqId":"2b792b95766fefbb9c6d102749577bc1","remoteAddr":"88.153.xxx.xxx","app":"PHP","message":"ZipArchive::extractTo(): Invalid or unitialized Zip object at \/var\/www\/owncloud\/lib\/private\/archive\/zip.php#135","level":3,"time":"2015-02-14T21:16:00+00:00"}
{"reqId":"2b792b95766fefbb9c6d102749577bc1","remoteAddr":"88.153.xxx.xxx","app":"core","message":"App does not provide an info.xml file","level":3,"time":"2015-02-14T21:16:00+00:00"}

**Comment by VicDeo** [comment]
@Tom-Schmidt 
1. What does 'Connectivity Checks' section say  at the admin page?
2. What is a value for `upload_tmp_dir` in php.ini? Is this path writable?
3. Is PHP zip extension enabled according to your phpinfo?

**Comment by Tom-Schmidt** [comment]
1. Connectivity Checks section not shown.
2. upload_tmp_dir is commented out. (= system default = /tmp is writable)
3. ZIP is enabled.

**Comment by Tom-Schmidt** [comment]
Any other suggestions?

**Comment by VicDeo** [comment]
@Tom-Schmidt does 'New->From link' function  work in Files app?

**Comment by VicDeo** [comment]
according to your logs it's not possible to connect to apps.owncloud.com.

**Comment by Tom-Schmidt** [comment]
@VicDeo This function seems to work correctly. The apps still don't install.

**Comment by jasonsturges** [comment]
Experiencing this identical issue with ownCloud v8.0.0.7 - apps cannot be enabled:

> ![image](https://cloud.githubusercontent.com/assets/1213591/6398364/b28006b8-bdb0-11e4-9f25-44a44ca5b01c.png)

Error log states:

```
[{
    "reqId": "b49d89a9d7f4f482a081eed4c0b863e0",
    "remoteAddr": "192.223.7.254",
    "app": "core",
    "message": "App does not provide an info.xml file",
    "level": 3,
    "time": "2015-02-26T17:53:12+00:00"
}, {
    "reqId": "b49d89a9d7f4f482a081eed4c0b863e0",
    "remoteAddr": "192.223.7.254",
    "app": "PHP",
    "message": "ZipArchive::extractTo(): Invalid or unitialized Zip object at \/data\/www\/owncloud\/lib\/private\/archive\/zip.php#135",
    "level": 3,
    "time": "2015-02-26T17:53:12+00:00"
}, {
    "reqId": "05388d6253104d28850570075343a0ed",
    "remoteAddr": "192.223.7.254",
    "app": "core",
    "message": "App does not provide an info.xml file",
    "level": 3,
    "time": "2015-02-26T17:52:59+00:00"
}, {
    "reqId": "05388d6253104d28850570075343a0ed",
    "remoteAddr": "192.223.7.254",
    "app": "PHP",
    "message": "ZipArchive::extractTo(): Invalid or unitialized Zip object at \/data\/www\/owncloud\/lib\/private\/archive\/zip.php#135",
    "level": 3,
    "time": "2015-02-26T17:52:59+00:00"
}]
```

This occurred using the following install configured with Ubuntu 14.04, Nginx, MySQL:
- https://download.owncloud.org/community/owncloud-8.0.0.tar.bz2

Yesterday I'd performed an install via the preferred methodology of package management as in:

```
sudo sh -c "echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_14.04/ /' >> /etc/apt/sources.list.d/owncloud.list"
sudo apt-get update
sudo apt-get install owncloud
```

That installation was able to enable apps.

**Comment by jasonsturges** [comment]
Checking my dependencies, it appears I was missing: php-pear, php-xml-parser, and php-curl.

Now able to enable apps, installing missing dependencies resolved my issue:

    sudo apt-get install php-pear php-xml-parser php5-curl

**Comment by oliwel** [comment]
@jasonsturges THX, life/timesafer - same error, gone after adding the required packages
@karlitschek suggestion - add those modules to the prereq check

**Comment by karlitschek** [comment]
@oliwel I agree. We should check for that during setup.

**Comment by Tom-Schmidt** [comment]
@jasonsturges Perfect, that solved it indeed. Thank you for your contribution.
