### ISSUE TITLE
not able to verify gpg signature on owncloud 8.0.0

### ISSUE THREAD

**Issue by andriesinfoserv** [owncloud/core#14221]
###steps to reproduce
follow install instructions here:
http://doc.owncloud.org/server/8.0/admin_manual/installation/source_installation.html
get to last step of the gpg sig verification section:
"gpg owncloud-x.y.z.tar.bz2"

### Expected behaviour
Owncloud download is verified

### Actual behaviour
gpg: no valid OpenPGP data found.
gpg: processing message failed: Unknown system error

### Server configuration
up to date arch linux
kernel: 3.18.6.201502062100-1-grsec
gnupg 2.1.2-1

thanks

**Comment by RealRancor** [comment]
Hi,

``
gpg --verify owncloud-8.0.0.tar.bz2.asc owncloud-8.0.0.tar.bz2
``

works here better. Seems more like an documentation issue here which should be reported to:

https://github.com/owncloud/documentation/issues

**Comment by andriesinfoserv** [comment]
thanks. that works here too. i'll report it at the location you specified.
