### ISSUE TITLE
Ability to disable the upgrade page, forcing use of occ

### ISSUE THREAD

**Issue by RobinMcCorkell** [owncloud/core#14229]
An admin may want to make a DB backup before performing an upgrade, after installing a new version. However, if a user gets to the upgrade page first, they can trigger an upgrade, which may fail, with no chance for the admin to make a backup first.

A solution to this would be to have a non-default option to disable the web upgrade process, forcing the use of `./occ`. If the DB hasn't been upgraded and a newer version is installed, a maintenance page should be displayed.

Obviously this won't be of any benefit in shared hosting environments where CLI access is not provided, but in many cases it will be.

cc @strugee @r-daneel @karlitschek @LukasReschke

**Comment by LukasReschke** [comment]
Mhm… I think it would make more sense to prevent against this on a webserver layer using IP blocks or VPNs etc…

**Comment by strugee** [comment]
> Mhm… I think it would make more sense to prevent against this on a webserver layer using IP blocks or VPNs etc…

How would you suggest automatically determining what mode ownCloud is in (waiting for DB upgrade or in a consistent state) and then acting on that mode at the webserver level?

**Comment by enoch85** [comment]
Another way could be to enter admin password before the upgrade starts.

**Comment by karlitschek** [comment]
this doesn't work. owncloud is disfunctional before the upgrade is performed. we can't do any complex operations like access the usernanagement before everything is upgraded. 
i think this problem can be avoided by a proper upgrade process. if you have a bigger installation then just stop your web-server, replace owncloud, uograde with occ and start the webserver again. smaller installation should be fine with the current web based upgrade routine

**Comment by shoeper** [comment]
Owncloud doesn't need to have complex usermanagement for this. Just store admin hash in the config. That would only require hashing and comparing of the hashes.

**Comment by Xenopathic** [comment]
@shoeper *Which* admin hash? And what about when LDAP is used? Or you delete an admin user? It becomes a huge mess that we don't want to support. Please keep this ticket about the ability to disable upgrades through the web interface - no mention of authentication. If you want to continue to discuss that go to the other ticket.

**Comment by shoeper** [comment]
That one of the first user being created on setup. Alternatively add an option to the admin settings to set the "admin" password. LDAP wouldn't be any problem btw. owncloud could just save  it's own copy of username + password.
But okay that may be too much work for to little gain.

**Comment by strugee** [comment]
> That one of the first user being created on setup. Alternatively add
> an option to the admin settings to set the "admin" password. LDAP
> wouldn't be any problem btw. owncloud could just save  it's own copy
> of username + password.
> But okay that may be too much work for to little gain.

This discussion doesn't belong here. Move it to the other issue.

**Comment by PVince81** [comment]
I think having a config option to disallow web UI update is a good idea (I thought I already raised an issue for this before, but didn't). In general it is recommended to always do the update on the CLI to avoid running into PHP timeouts during the upgrade.

**Comment by r-daneel** [comment]
Exploring here:
If the 'update' button always redirects to a known url, Apache could intercept this and ask for it's own authentication (kind of htaccess in the apache config files) so no changes on the page, but the access to the actual update page is barred for non-admin users.
On next update, I'll try to test this out.

**Comment by r-daneel** [comment]
Hi,
With the 8.0.2 update I got the chance to test out filtering of the update url.
It actually works: In apache2, setting up a Location section to /owncloud/core/ajax/update.php can password protect the update. I tried this for a test:
<Location /owncloud/core/ajax/update.php >
	AuthType Basic
	AuthName "update requires admin access"
	AuthUserFile /path/to/password/db
	Require user admin 
</Location>

So yes, it would be nice to have something at the front page, but this at least blocks access.

**Comment by sergiocallegari** [comment]
IMHO, this should not be "ability" it should be the default, until the web UI upgrade can be restricted only to users having a permssion to run it.  It is not acceptable that anyone on the internet can trigger the upgrade outside the admin control.

**Comment by PVince81** [comment]
Discussion to make it a default here: https://github.com/owncloud/core/issues/17091

**Comment by PVince81** [comment]
possibly duplicate...
