### ISSUE TITLE
Feature Request: Using group for creating address books and calendars

### ISSUE THREAD

**Issue by johanfleury** [owncloud/core#14224]
Hi.

I think it would be nice if we had the possibility to create address books and calendars for a group rather than create them in an account and then share them with the group.

We could more easily share a calendar with a group.

I think of something like Gitlab's groups that can be used as projects namespace.

**Comment by RealRancor** [comment]
Hi,

as those are related to the calendar and contacts app its better to request this on the issue trackers of those apps:

https://github.com/owncloud/contacts/issues
https://github.com/owncloud/calendar/issues
