### ISSUE TITLE
mac client installer reports issue any stops

### ISSUE THREAD

**Issue by sebastiennoir** [owncloud/core#14227]
I have tried to install the mac client (version 1.7.1 and 1.8.0) on my mac (OX X 10.10.2). Installer stops near the end.
Console reports : 

        14.02.15 22:07:52.839 Installer[49922]: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.

I have enough disk space, and enough RAM.

**Comment by LukasReschke** [comment]
Can you please reopen this at https://github.com/owncloud/client? Thanks!

**Comment by sebastiennoir** [comment]
@LukasReschke  I don't think I have the right to do so...
How should I do that?

**Comment by RealRancor** [comment]
@sebastiennoir 
Just create a new issue at this linked issue tracker and make sure that you are also using the issue template here: https://raw.github.com/owncloud/client/master/issue_template.md

**Comment by sebastiennoir** [comment]
Done. For reference : https://github.com/owncloud/client/issues/2843
