### ISSUE TITLE
Scripts download as HTML page

### ISSUE THREAD

**Issue by Timvdv** [owncloud/core#14239]
Hello awesome people,

I've got a problem, not sure if this is a misconfiguration on my side or an Owncloud bug.

At first my Owncloud setup is probably a bit different then the normal Owncloud user. I'm running Owncloud on my Synology NAS, I'm using their DDNS service to forward my local Owncloud setup to the web (http://timvdv.synology.me/owncloud). Then I have my own domain: tvdv.me. I use this domain (actually a subdomain) http://c.tvdv.me to redirect to the Synology website *(important: I keep the c.tvdv.me URL while showing the timvdv.synology.me domain)*.

When I try to download a script file (also happens with ZIP files) on c.tvdv.me I get the error:

```
Not Found

The requested URL /php-fpm-handler.fcgi/public.php was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.
```

It's supposed to download file.js but instead it's download file.js.html containing that error.
For some reason images work just fine.

Downloading the files:
1. local setup (**works**)
2. http://timvdv.synology.me/owncloud (**works**)
3. c.tvdv.me (**fails**)

Here is an example so you can see for yourself:
- http://timvdv.synology.me/owncloud/public.php?service=files&t=c1a043dc228714e1f84254f3a69198a4 **(works)**
- http://c.tvdv.me/public.php?service=files&t=c1a043dc228714e1f84254f3a69198a4 **(fails)**

I wonder if you guys have any idea why this is happening. Thanks a lot for your help!
*(if this is a bug tell me and I'll fill out the bug form)*

**Comment by LukasReschke** [comment]
This is a misconfiguration on your side. Please reopen that question on forum.owncloud.org  – thx.
