### ISSUE TITLE
Shared restored files are marked as shared before browser cache being cleaned

### ISSUE THREAD

**Issue by vbouchet31** [owncloud/core#14230]
Hi,

### Steps to reproduce
1. Share a file with another user.
2. Delete this file.
3. Visit the bin and restore the file.
4. Visit the folder containing the restored file.

### Expected behavior
The restored file is not marked as shared anymore and is actually not shared.
OR
Share settings are restored.

### Current behavior
When visiting the folder containing the restored file, the file is marked as shared. Clicking on the "Shared" button opens the option to share but no user is listed. After clearing browser cache and refreshing the page (fn + F5 on OSX), the file is not marked as shared anymore.

### Server configuration
Linux raspberrypi 3.18.7-v7+
PHP 5.4.36-0+deb7u3
OC 8.0.0

### Client configuration
Firefox 35
OSX Yosemite (10.10.2)

**Comment by karlitschek** [comment]
@schiesbn any idea?

**Comment by PVince81** [comment]
This is because the share ids are cached in "OC.Share.*". Switching back to "All files" doesn't reload the share infos, so it is using outdated info. (not 100% sure though, I'd expect the fileid to change after restore)

**Comment by vbouchet31** [comment]
Maybe it should delete all cached info regarding the file when it's being deleted?

**Comment by nickvergessen** [comment]
@PVince81 with the "fileID must be stable" approach, this should be right and working correctly again, right?

**Comment by PVince81** [comment]
Not necessarily. We'd better clear the cached share ids when switching between views in the sidebar.

**Comment by PVince81** [comment]
Since 8.1 the share information is preserved for deleted files. So when you restore the file the share information will still be available.
