### ISSUE TITLE
Loading apps in secondary apps_path stalls (calendar, contacts)

### ISSUE THREAD

**Issue by eigengrau** [owncloud/core#14236]
After installing calendar and contacts for Owncloud 8, I noticed that these apps were showing no icons, and activating the links would lead to a garbled page (e.g., for calendar, I could see the list of my calendars, but the main calendar pane was missing, with the spinner running indefinitely).

I have a secondary apps path set in my config, and the apps were installed there. I noticed the apps load correctly when I symlink calendar and contacts from the secondary apps location into Owncloud’s primary apps path.

This is what’s set in the config.

```
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/usr/share/webapps/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/var/lib/owncloud/apps',
      'url' => '/localapps',
      'writable' => true,
    ),
  ),
```

At first I suspected an open_basedir issue, but /var/lib/owncloud is accessible from PHP.

No errors were generated in the logs when accessing the apps (except `simplexml_load_file(): I/O warning : failed to load external entity`, which I also get with the workaround).

**Comment by karlitschek** [comment]
Can you post a full bug report using this template please?
https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

How have you installed this apps?

**Comment by Dreadeath** [comment]
I have the same issue. I`m using nginx and found out that though apps installed to secondary apps folder, some files are looked in wrong place and it looks like second absolute path is ignored in some cases. 

For example, we have two folders - apps and apps2, and two paths - /one/path/apps and /second/apps2. So, according to ngnix`s logs, icons of installed apps (and so as some other files I suppose) are looked in /one/path/apps2 (not in /second/apps2).

As workaround I created symlink /one/path/apps2 to /second/apps2.

**Comment by oparoz** [comment]
@Dreadeath @eigengrau - Could you open your browser debugger and check which calls fail? You should be getting 404s for specific URLs

**Comment by Dreadeath** [comment]
For example
`https://xxx.xx/apps2/files_mv/js/move.js?v=longlongstring` gives 404
In nginx logs it is represented as
`open() "/usr/share/webapps/owncloud/apps2/files_mv/css/mv.css?v=longlongstring" failed (2: No such file or directory), client: xxxx, server: xxx.xxx, request: "GET /apps2/files_mv/css/mv.css HTTP/1.1"`

**Comment by oparoz** [comment]
OK, that's a problem with the files_mv app. It would be great if you could report the problem in its repository and indicate what the correct path should look like. It would help with the debugging.
On Gallery+, we were using an OC method which would not automatically build the proper path until someone told me that an html fragment would not load. The files_mv developer may be using the same one.

**Comment by Dreadeath** [comment]
That was an example, every app in apps2 folder has these symptoms. js, css, png are looked in wrong place.

**Comment by DeepDiver1975** [comment]
what ever you define in the url parameter has to be a valid url which is served by the web server.

In the case above https://github.com/owncloud/core/issues/14236#issue-57737317

      'path' => '/usr/share/webapps/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/var/lib/owncloud/apps',
      'url' => '/localapps',


http://localhost/apps shall be resolved to /usr/share/webapps/owncloud/apps
http://localhost/localapps shall be resolved to /var/lib/owncloud/apps

**Comment by Dreadeath** [comment]
Define "valid". Paths are valid, since PHP scripts are found, only static assets are "lost". My guess for now it is related to nginx misconfiguration, related to root directive or something like that. Maybe not :)

**Comment by DeepDiver1975** [comment]
Valid in the sense that assets are served.
Php scripts are unrelated - routing is done via 'apps' url part. 

So: proper web server config is the solution.

**Comment by PVince81** [comment]
@eigengrau see solution proposed here https://github.com/owncloud/core/issues/14236#issuecomment-94592044
