### ISSUE TITLE
Enabling documents app fails

### ISSUE THREAD

**Issue by jpschewe** [owncloud/core#14233]
Owncloud 8.0 upgraded from 7.0. Postgresql database. Using Debian repository.

An exception occurred while executing 'CREATE TABLE "oc_documents_session" ("es_id" VARCHAR(64) NOT NULL, "genesis_url" VARCHAR(512) DEFAULT NULL, "genesis_hash" VARCHAR(128) NOT NULL, "file_id" VARCHAR(512) DEFAULT NULL, "owner" VARCHAR(64) NOT NULL, PRIMARY KEY("es_id"))': SQLSTATE[42P07]: Duplicate table: 7 ERROR: relation "oc_documents_session" already exists

**Comment by RealRancor** [comment]
Hi,

the documents app issue tracker is located here:

https://github.com/owncloud/documents/issues

Please re-open there.

**Comment by karlitschek** [comment]
@VicDeo Can you have a look please?

**Comment by VicDeo** [comment]
@jpschewe Please post output for `SELECT * FROM oc_appconfig where appid='documents';`

**Comment by LukasReschke** [comment]
Closing due to missing informations.
