### ISSUE TITLE
upgrade to 8 issue

### ISSUE THREAD

**Issue by Tommylans** [owncloud/core#14242]
An exception occurred while executing 'CREATE TABLE oc_ownc_appconfig_aoutkwvgu5266 (`appid` VARCHAR(32) DEFAULT '' NOT NULL, `configkey` VARCHAR(64) DEFAULT '' NOT NULL, `configvalue` LONGTEXT DEFAULT NULL, INDEX oc_fmbu95hqob9jz (`configkey`), INDEX oc_461g3hki5aomj (`appid`), PRIMARY KEY(`appid`, `configkey`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_ownc_appconfig_aoutkwvgu5266' already exists

**Comment by DeepDiver1975** [comment]
@icewind1991 table names which are generated for migration testing are supposed to be unique - what went wrong?

@LukasReschke the temp table names are generates using random lib - any issues know to get duplicates?

@Tommylans as a quick fix/work around: drop all tables which have similar looking table postfixes and rerun the migration.

**Comment by LukasReschke** [comment]
Well. A random library can always give you duplicated. Randomness does not mean uniqueness :)

Though I doubt that that happened here. Chances would be the same than winning in lotto. Though it would male sense to check this in the update wizard.

**Comment by Tommylans** [comment]
you can try https://randomnlgames.nl/cloud

**Comment by Tommylans** [comment]
what is the name of the table?

**Comment by PVince81** [comment]
See, his server name contains the word "random". Could this crash the known universe and cause random collisions ? :wink:

**Comment by PVince81** [comment]
@Tommylans I think he meant drop all tables that start with `oc_ownc_appconfig*` EXCEPT the real `oc_own_appconfig` table. (assuming that your database prefix is "oc_ownc")

**Comment by Tommylans** [comment]
problem found the plugin files_encryption don't working
