### ISSUE TITLE
Upgrade 7.0.4 to OC 8

### ISSUE THREAD

**Issue by FrankMaute** [owncloud/core#14246]
Hello,

made a dist-upgrade on Debian 7 to version:
$OC_Version = array(8,0,0,7);
$OC_VersionString = '8.0';
$OC_Channel = 'stable';
$OC_Build = '2015-02-07T02:34:55+00:00 df2808eec840c033b952e001ee8a063a93fae417';

Most Apps are not working. Admin page does not show up:

{"reqId":"607e7c01a62eb03cec2f34a6b3553fe8","remoteAddr":"x.x.x.x","app":"index","message":"Exception: {\"Message\":\"js file not found: script:js\\\/chosen\\\/chosen.jquery.min serverroot:\\\/var\\\/www\\\/owncloud\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/templatelayout.php(155): OC\\\\Template\\\\ResourceLocator->find(Array)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/templatelayout.php(106): OC_TemplateLayout::findJavascriptFiles(Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template.php(118): OC_TemplateLayout->__construct('user', 'settings')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template\\\/base.php(103): OC_Template->fetchPage()\\n#4 \\\/var\\\/www\\\/owncloud\\\/settings\\\/admin.php(127): OC\\\\Template\\\\Base->printPage()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 [internal function]: __lambda_func(Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('\\\\x00lambda_1558', Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(763): OC\\\\Route\\\\Router->match('\\\/settings\\\/admin')\\n#9 \\\/var\\\/www\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template\\\/resourcelocator.php\",\"Line\":46}","level":4,"time":"2015-02-16T09:35:05+00:00"}
{"reqId":"607e7c01a62eb03cec2f34a6b3553fe8","remoteAddr":"x.x.x.x","app":"PHP","message":"js file not found: script:js\/chosen\/chosen.jquery.min serverroot:\/var\/www\/owncloud at \/var\/www\/owncloud\/lib\/private\/template\/resourcelocator.php#46","level":3,"time":"2015-02-16T09:35:05+00:00"}

Any help is appreciated. 

Thanking you in advance,
Frank.

**Comment by LukasReschke** [comment]
Looks pretty much like you did not update the shipped application such as calendar and contacts. Please remove those from the apps folder and download the new versions from apps.owncloud.com as described in the upgrading documentation.

**Comment by DeepDiver1975** [comment]
@FrankMaute this is caused by an incompatibility of callendar and/or contacts - please disable these two apps and update them via the appstore - THX
