### ISSUE TITLE
modify and add translations to core without transifex

### ISSUE THREAD

**Issue by luto** [owncloud/core#14249]
Is it currently possible to add or modify strings in OC8 without the use of transifex? If so, how?
I'm unable to find the `.po` files provided in OC7, which were used to generate the `.php` translation files and so on.

**Comment by DeepDiver1975** [comment]
The .po files are just used during an intermediate step - there is no need to add them to git.

With OC8 we now use json and js files where translations are stored.

Please elaborate why you are interested in adding/changing translation string in core - THX

**Comment by luto** [comment]
So, for example I'd like to change the de_AT translation of `January` to `Jänner` (currently: `Januar`), which is used in Austria. To test my change, I'd like it to be reflected in the `.json`, `.js` and `.php` files. Which file do I need to edit and how do I update those 3 to achieve this? Do I need to make the change manually in all 3 of them?

**Comment by DeepDiver1975** [comment]
well - best would be to join transifex and fix the issue in there - we have mechanisms to backport translations from the master branch to the stable8 branch.

If you want to fix this locally only you have to manually change the js and json files - php files are no longer available and required.

**Comment by luto** [comment]
Thank you for the information. All clear now. :)

**Comment by ostasevych** [comment]
DeepDiver, is it possible to backport translations manually? Or which are other mechanisms to sync my oc instance with the transifex?

**Comment by DeepDiver1975** [comment]
> DeepDiver, is it possible to backport translations manually?

We have scripts to do this - @nickvergessen @MorrisJobke where are the scripts located? THX

**Comment by nickvergessen** [comment]
You mean this? https://github.com/vgezer/oc_l10n_patch_applier
It's sometimes nasty to use, but all info should basically be in the readme.

**Comment by DeepDiver1975** [comment]
> You mean this? https://github.com/vgezer/oc_l10n_patch_applier

yes
