### ISSUE TITLE
Upgrade 7.0.4.2 -> 8.0.0.7: Unknown database type varchar requested

### ISSUE THREAD

**Issue by JanWelker** [owncloud/core#14247]
Update failed with the following message:

Unknown database type varchar requested, Doctrine\DBAL\Platforms\SqlitePlatform may not support it.

Please find the relevant log entries below:

{"reqId":"70a092144084d5e3a9db39e857b444aa","remoteAddr":"131.152.98.222","app":"core","message":"starting upgrade from 7.0.4.2 to 8.0.0.7","level":0,"time":"2015-02-16T09:50:24+00:00","method":"GET","url":"\/cloud\/core\/ajax\/update.php?requesttoken=99b5c91d1c1ba25c0ed9"}
{"reqId":"70a092144084d5e3a9db39e857b444aa","remoteAddr":"131.152.98.222","app":"core","message":"Simulated database structure update failed (exception 'OC\\DB\\MigrationException' with message 'Unknown database type varchar  requested, Doctrine\\DBAL\\Platforms\\SqlitePlatform may not support it.' in \/var\/www\/owncloud\/lib\/private\/db\/sqlitemigrator.php:39\nStack trace:\n#0 \/var\/www\/owncloud\/lib\/private\/db\/mdb2schemamanager.php(113): OC\\DB\\SQLiteMigrator->checkMigrate(Object(Doctrine\\DBAL\\Schema\\Schema))\n#1 \/var\/www\/owncloud\/lib\/private\/db.php(252): OC\\DB\\MDB2SchemaManager->simulateUpdateDbFromStructure('\/var\/www\/ownclo...')\n#2 \/var\/www\/owncloud\/lib\/private\/updater.php(241): OC_DB::simulateUpdateDbFromStructure('\/var\/www\/ownclo...')\n#3 \/var\/www\/owncloud\/lib\/private\/updater.php(210): OC\\Updater->checkCoreUpgrade()\n#4 \/var\/www\/owncloud\/lib\/private\/updater.php(149): OC\\Updater->doUpgrade('8.0.0.7', '7.0.4.2')\n#5 \/var\/www\/owncloud\/core\/ajax\/update.php(49): OC\\Updater->upgrade()\n#6 {main})","level":4,"time":"2015-02-16T09:50:24+00:00","method":"GET","url":"\/cloud\/core\/ajax\/update.php?requesttoken=99b5c91d1c1ba25c0ed9"}

**Comment by DeepDiver1975** [comment]
@JanWelker can I ask you for a schema dump of your db?

**Comment by JanWelker** [comment]
Thanks for your quick reply. Please find the requested information below.

sqlite> .schema
CREATE TABLE ` oc_roundcube `(` id `INTEGER PRIMARY KEY AUTOINCREMENT, ` oc_user `varchar (4096) NOT NULL DEFAULT '', ` mail_user `varchar (4096) NOT NULL DEFAULT '', `mail_password` varchar (4096) NOT NULL DEFAULT' ');
CREATE TABLE oc_appconfig (appid VARCHAR(32) DEFAULT '' NOT NULL, configkey VARCHAR(64) DEFAULT '' NOT NULL, configvalue CLOB DEFAULT NULL, PRIMARY KEY(appid, configkey));
CREATE TABLE oc_clndr_calendars ("id" INTEGER NOT NULL, userid VARCHAR(255) DEFAULT NULL, displayname VARCHAR(100) DEFAULT NULL, uri VARCHAR(255) DEFAULT NULL, active INTEGER DEFAULT 1 NOT NULL, calendarcolor VARCHAR(10) DEFAULT NULL, timezone CLOB DEFAULT NULL, components VARCHAR(100) DEFAULT NULL, "ctag" INTEGER DEFAULT 0 NOT NULL, "calendarorder" INTEGER DEFAULT 0 NOT NULL, PRIMARY KEY("id"));
CREATE TABLE oc_clndr_objects ("id" INTEGER NOT NULL, startdate DATETIME DEFAULT '1970-01-01 00:00:00', enddate DATETIME DEFAULT '1970-01-01 00:00:00', repeating INTEGER DEFAULT NULL, summary VARCHAR(255) DEFAULT NULL, calendardata CLOB DEFAULT NULL, uri VARCHAR(255) DEFAULT NULL, lastmodified INTEGER DEFAULT NULL, "calendarid" INTEGER DEFAULT 0 NOT NULL, "objecttype" VARCHAR(40) DEFAULT '' NOT NULL, PRIMARY KEY("id"));
CREATE TABLE oc_clndr_repeat ("id" INTEGER NOT NULL, startdate DATETIME DEFAULT '1970-01-01 00:00:00', enddate DATETIME DEFAULT '1970-01-01 00:00:00', "eventid" INTEGER DEFAULT 0 NOT NULL, "calid" INTEGER DEFAULT 0 NOT NULL, PRIMARY KEY("id"));
CREATE TABLE oc_clndr_share_calendar (active INTEGER DEFAULT 1 NOT NULL, "owner" VARCHAR(255) NOT NULL, "share" VARCHAR(255) NOT NULL, "sharetype" VARCHAR(6) NOT NULL, "calendarid" INTEGER DEFAULT '0' NOT NULL, "permissions" INTEGER NOT NULL);
CREATE TABLE oc_clndr_share_event ("owner" VARCHAR(255) NOT NULL, "share" VARCHAR(255) NOT NULL, "sharetype" VARCHAR(6) NOT NULL, "eventid" INTEGER DEFAULT '0' NOT NULL, "permissions" INTEGER NOT NULL);
CREATE TABLE oc_contacts_addressbooks ("id" INTEGER NOT NULL, displayname VARCHAR(255) DEFAULT NULL, uri VARCHAR(200) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, active INTEGER DEFAULT 1 NOT NULL, userid VARCHAR(255) DEFAULT '' NOT NULL, "ctag" INTEGER DEFAULT 1 NOT NULL, PRIMARY KEY("id"));
CREATE TABLE oc_contacts_cards ("id" INTEGER NOT NULL, fullname VARCHAR(255) DEFAULT NULL, carddata CLOB DEFAULT NULL, uri VARCHAR(200) DEFAULT NULL, "addressbookid" INTEGER DEFAULT 0 NOT NULL, "lastmodified" INTEGER DEFAULT 0, PRIMARY KEY("id"));
CREATE TABLE oc_contacts_cards_properties ("id" INTEGER NOT NULL, name VARCHAR(64) DEFAULT NULL, value VARCHAR(255) DEFAULT NULL, preferred INTEGER DEFAULT 1 NOT NULL, userid VARCHAR(255) DEFAULT '' NOT NULL, "contactid" INTEGER DEFAULT 0 NOT NULL, PRIMARY KEY("id"));
CREATE TABLE oc_documents_invite (es_id VARCHAR(64) NOT NULL, "uid" VARCHAR(64) DEFAULT NULL, "status" INTEGER DEFAULT '0', "sent_on" INTEGER DEFAULT 0);
CREATE TABLE oc_documents_member ("member_id" INTEGER NOT NULL, es_id VARCHAR(64) NOT NULL, token VARCHAR(32) DEFAULT NULL, "uid" VARCHAR(64) DEFAULT NULL, "color" VARCHAR(32) DEFAULT NULL, "last_activity" INTEGER DEFAULT NULL, "status" INTEGER DEFAULT '1' NOT NULL, "is_guest" INTEGER DEFAULT '0' NOT NULL, PRIMARY KEY("member_id"));
CREATE TABLE oc_documents_op ("seq" INTEGER NOT NULL, es_id VARCHAR(64) NOT NULL, opspec CLOB DEFAULT NULL, "member" INTEGER DEFAULT 1 NOT NULL, PRIMARY KEY("seq"));
CREATE TABLE oc_documents_revisions (es_id VARCHAR(64) NOT NULL, save_hash VARCHAR(128) NOT NULL, "file_id" VARCHAR(512) DEFAULT NULL, "seq_head" INTEGER NOT NULL, "member_id" INTEGER NOT NULL);
CREATE TABLE oc_documents_session (es_id VARCHAR(64) NOT NULL, genesis_hash VARCHAR(128) NOT NULL, owner VARCHAR(64) NOT NULL, "genesis_url" VARCHAR(512) DEFAULT NULL, "file_id" VARCHAR(512) DEFAULT NULL, PRIMARY KEY(es_id));
CREATE TABLE oc_file_map ("logic_path" VARCHAR(512) DEFAULT '' NOT NULL, "logic_path_hash" VARCHAR(32) DEFAULT '' NOT NULL, "physic_path" VARCHAR(512) DEFAULT '' NOT NULL, "physic_path_hash" VARCHAR(32) DEFAULT '' NOT NULL, PRIMARY KEY("logic_path_hash"));
CREATE TABLE oc_filecache (fileid INTEGER NOT NULL, storage INTEGER DEFAULT 0 NOT NULL, parent INTEGER DEFAULT 0 NOT NULL, name VARCHAR(250) DEFAULT NULL, mimetype INTEGER DEFAULT 0 NOT NULL, mimepart INTEGER DEFAULT 0 NOT NULL, mtime INTEGER DEFAULT 0 NOT NULL, encrypted INTEGER DEFAULT 0 NOT NULL, path_hash VARCHAR(32) DEFAULT '' NOT NULL, etag VARCHAR(40) DEFAULT NULL, storage_mtime INTEGER DEFAULT 0 NOT NULL, path VARCHAR(4000) DEFAULT NULL, permissions INTEGER DEFAULT 0, "size" INTEGER DEFAULT '0' NOT NULL, "unencrypted_size" INTEGER DEFAULT '0' NOT NULL, PRIMARY KEY(fileid));
CREATE TABLE oc_files_trash (id VARCHAR(250) DEFAULT '' NOT NULL, user VARCHAR(64) DEFAULT '' NOT NULL, timestamp VARCHAR(12) DEFAULT '' NOT NULL, location VARCHAR(512) DEFAULT '' NOT NULL, "type" VARCHAR(4) DEFAULT NULL, "mime" VARCHAR(255) DEFAULT NULL, "auto_id" INTEGER NOT NULL, PRIMARY KEY("auto_id"));
CREATE TABLE oc_gallery_sharing (gallery_id INTEGER DEFAULT 0 NOT NULL, token VARCHAR(64) NOT NULL, "recursive" INTEGER NOT NULL);
CREATE TABLE oc_group_admin ("gid" VARCHAR(64) DEFAULT '' NOT NULL, "uid" VARCHAR(64) DEFAULT '' NOT NULL, PRIMARY KEY("gid", "uid"));
CREATE TABLE oc_group_user ("gid" VARCHAR(64) DEFAULT '' NOT NULL, "uid" VARCHAR(64) DEFAULT '' NOT NULL, PRIMARY KEY("gid", "uid"));
CREATE TABLE oc_groups ("gid" VARCHAR(64) DEFAULT '' NOT NULL, PRIMARY KEY("gid"));
CREATE TABLE oc_jobs ("id" INTEGER NOT NULL, class VARCHAR(255) DEFAULT '' NOT NULL, argument VARCHAR(256) DEFAULT '' NOT NULL, last_run INTEGER DEFAULT 0, PRIMARY KEY("id"));
CREATE TABLE oc_locks ("id" INTEGER NOT NULL, userid VARCHAR(64) DEFAULT NULL, owner VARCHAR(100) DEFAULT NULL, token VARCHAR(100) DEFAULT NULL, uri CLOB DEFAULT NULL, "created" INTEGER DEFAULT NULL, "scope" INTEGER DEFAULT NULL, "depth" INTEGER DEFAULT NULL, "timeout" INTEGER DEFAULT NULL, PRIMARY KEY("id"));
CREATE TABLE "oc_lucene_status" ("fileid" INTEGER DEFAULT 0 NOT NULL, "status" VARCHAR(1));
CREATE TABLE "oc_media_albums" ("album_id" INTEGER PRIMARY KEY AUTOINCREMENT, "album_name" VARCHAR(200) DEFAULT ' ' NOT NULL, "album_artist" INTEGER DEFAULT 0 NOT NULL, "album_art" VARCHAR(200));
CREATE TABLE "oc_media_artists" ("artist_id" INTEGER PRIMARY KEY AUTOINCREMENT, "artist_name" VARCHAR(200) DEFAULT ' ' NOT NULL);
CREATE TABLE "oc_media_sessions" ("session_id" INTEGER PRIMARY KEY AUTOINCREMENT, "token" VARCHAR(64) DEFAULT ' ' NOT NULL, "user_id" VARCHAR(64) DEFAULT ' ' NOT NULL, "start" DATETIME DEFAULT '1970-01-01 00:00:00' NOT NULL);
CREATE TABLE "oc_media_songs" ("song_id" INTEGER PRIMARY KEY AUTOINCREMENT, "song_name" VARCHAR(200) DEFAULT ' ' NOT NULL, "song_artist" INTEGER DEFAULT 0 NOT NULL, "song_album" INTEGER DEFAULT 0 NOT NULL, "song_path" VARCHAR(200) DEFAULT ' ' NOT NULL, "song_user" VARCHAR(64) DEFAULT '0' NOT NULL, "song_length" INTEGER DEFAULT 0 NOT NULL, "song_track" INTEGER DEFAULT 0 NOT NULL, "song_size" INTEGER DEFAULT 0 NOT NULL, "song_playcount" INTEGER DEFAULT 0 NOT NULL, "song_lastplayed" INTEGER DEFAULT 0 NOT NULL);
CREATE TABLE "oc_media_users" ("user_id" VARCHAR(64) DEFAULT '0' NOT NULL, "user_password_sha256" VARCHAR(64) DEFAULT ' ' NOT NULL);
CREATE TABLE oc_mimetypes ("id" INTEGER NOT NULL, "mimetype" VARCHAR(255) DEFAULT '' NOT NULL, PRIMARY KEY("id"));
CREATE TABLE oc_permissions (fileid INTEGER DEFAULT 0 NOT NULL, permissions INTEGER DEFAULT 0 NOT NULL, "user" VARCHAR(64) DEFAULT NULL);
CREATE TABLE oc_pictures_images_cache ("uid_owner" VARCHAR(64) NOT NULL, "path" VARCHAR(256) NOT NULL, "width" INTEGER NOT NULL, "height" INTEGER NOT NULL);
CREATE TABLE oc_preferences (configvalue CLOB DEFAULT NULL, "userid" VARCHAR(64) DEFAULT '' NOT NULL, "appid" VARCHAR(32) DEFAULT '' NOT NULL, "configkey" VARCHAR(64) DEFAULT '' NOT NULL, PRIMARY KEY("userid", "appid", "configkey"));
CREATE TABLE oc_privatedata ("keyid" INTEGER NOT NULL, app VARCHAR(255) DEFAULT '' NOT NULL, "key" VARCHAR(255) DEFAULT '' NOT NULL, value VARCHAR(255) DEFAULT '' NOT NULL, user VARCHAR(64) DEFAULT '' NOT NULL, PRIMARY KEY("keyid"));
CREATE TABLE oc_properties ("userid" VARCHAR(64) DEFAULT '' NOT NULL, "propertypath" VARCHAR(255) DEFAULT '' NOT NULL, "propertyname" VARCHAR(255) DEFAULT '' NOT NULL, "propertyvalue" VARCHAR(255) DEFAULT '' NOT NULL, "id" INTEGER NOT NULL, PRIMARY KEY("id"));
CREATE TABLE "oc_queuedtasks" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "app" VARCHAR(255) DEFAULT ' ' NOT NULL, "klass" VARCHAR(255) DEFAULT ' ' NOT NULL, "method" VARCHAR(255) DEFAULT ' ' NOT NULL, "parameters" VARCHAR(255) DEFAULT ' ' NOT NULL);
CREATE TABLE oc_share (id INTEGER NOT NULL, share_with VARCHAR(255) DEFAULT NULL, item_source VARCHAR(255) DEFAULT NULL, item_target VARCHAR(255) DEFAULT NULL, file_target VARCHAR(512) DEFAULT NULL, expiration DATETIME DEFAULT NULL, token VARCHAR(32) DEFAULT NULL, item_type VARCHAR(64) DEFAULT '' NOT NULL, parent INTEGER DEFAULT NULL, file_source INTEGER DEFAULT NULL, uid_owner VARCHAR(64) DEFAULT '' NOT NULL, "share_type" INTEGER DEFAULT '0' NOT NULL, "permissions" INTEGER DEFAULT '0' NOT NULL, "stime" INTEGER DEFAULT '0' NOT NULL, "accepted" INTEGER DEFAULT '0' NOT NULL, "mail_send" INTEGER DEFAULT '0' NOT NULL, PRIMARY KEY(id));
CREATE TABLE "oc_share_external" ("id" INTEGER NOT NULL, "remote" VARCHAR(512) NOT NULL, "share_token" VARCHAR(64) NOT NULL, "password" VARCHAR(64) NOT NULL, "name" VARCHAR(64) NOT NULL, "owner" VARCHAR(64) NOT NULL, "user" VARCHAR(64) NOT NULL, "mountpoint" VARCHAR(4000) NOT NULL, "mountpoint_hash" VARCHAR(32) NOT NULL, PRIMARY KEY("id"));
CREATE TABLE oc_storages ("numeric_id" INTEGER NOT NULL, id VARCHAR(64) DEFAULT NULL, PRIMARY KEY("numeric_id"));
CREATE TABLE oc_users (displayname VARCHAR(64) DEFAULT NULL, "uid" VARCHAR(64) DEFAULT '' NOT NULL, "password" VARCHAR(255) DEFAULT '' NOT NULL, PRIMARY KEY("uid"));
CREATE TABLE oc_vcategory ("id" INTEGER NOT NULL, uid VARCHAR(64) DEFAULT '' NOT NULL, type VARCHAR(64) DEFAULT '' NOT NULL, category VARCHAR(255) DEFAULT '' NOT NULL, PRIMARY KEY("id"));
CREATE TABLE oc_vcategory_to_object (type VARCHAR(64) DEFAULT '' NOT NULL, "objid" INTEGER DEFAULT 0 NOT NULL, "categoryid" INTEGER DEFAULT 0 NOT NULL, PRIMARY KEY("categoryid", "objid", type));
CREATE INDEX album_artist_index ON "oc_media_albums" (album_artist ASC);
CREATE INDEX album_name_index ON "oc_media_albums" (album_name ASC);
CREATE INDEX appconfig_appid_key ON oc_appconfig ("appid");
CREATE INDEX appconfig_config_key_index ON oc_appconfig (configkey);
CREATE UNIQUE INDEX artist_name ON "oc_media_artists" (artist_name ASC);
CREATE INDEX c_addressbook_userid_index ON oc_contacts_addressbooks (userid);
CREATE INDEX c_addressbookid_index ON oc_contacts_cards (addressbookid);
CREATE INDEX category_index ON oc_vcategory (category);
CREATE INDEX cp_contactid_index ON oc_contacts_cards_properties (contactid);
CREATE INDEX cp_name_index ON oc_contacts_cards_properties (name);
CREATE INDEX cp_value_index ON oc_contacts_cards_properties (value);
CREATE UNIQUE INDEX documents_op_eis_idx ON oc_documents_op (es_id, seq);
CREATE UNIQUE INDEX documents_rev_eis_idx ON oc_documents_revisions (es_id, seq_head);
CREATE UNIQUE INDEX file_map_pp_index ON "oc_file_map" (physic_path_hash);
CREATE INDEX file_source_index ON oc_share (file_source);
CREATE INDEX fs_parent_name_hash ON oc_filecache (parent, name);
CREATE INDEX fs_storage_mimepart ON oc_filecache (storage, mimepart);
CREATE INDEX fs_storage_mimetype ON oc_filecache (storage, mimetype);
CREATE UNIQUE INDEX fs_storage_path_hash ON oc_filecache (storage, path_hash);
CREATE INDEX fs_storage_size ON oc_filecache (storage, size, fileid);
CREATE INDEX group_admin_uid ON "oc_group_admin" (uid);
CREATE INDEX id_index ON oc_files_trash (id);
CREATE INDEX id_user_index ON "oc_permissions" ("fileid", "user");
CREATE INDEX item_share_type_index ON oc_share (item_type, share_type);
CREATE INDEX job_class_index ON oc_jobs (class);
CREATE UNIQUE INDEX mimetype_id_index ON "oc_mimetypes" (mimetype);
CREATE INDEX property_index ON "oc_properties" (userid);
CREATE UNIQUE INDEX sh_external_mp ON "oc_share_external" ("user", "mountpoint_hash");
CREATE INDEX sh_external_user ON "oc_share_external" ("user");
CREATE INDEX song_album_index ON "oc_media_songs" (song_album ASC);
CREATE INDEX song_artist_index ON "oc_media_songs" (song_artist ASC);
CREATE INDEX song_name_index ON "oc_media_songs" (song_name ASC);
CREATE INDEX status_index ON "oc_lucene_status" (status ASC);
CREATE UNIQUE INDEX storages_id_index ON "oc_storages" (id);
CREATE INDEX timestamp_index ON oc_files_trash (timestamp);
CREATE INDEX token_index ON oc_share (token);
CREATE INDEX type_index ON oc_vcategory (type);
CREATE INDEX uid_index ON oc_vcategory (uid);
CREATE INDEX user_index ON oc_files_trash (user);
CREATE INDEX vcategory_objectd_index ON oc_vcategory_to_object (objid, type);

**Comment by PVince81** [comment]
@DeepDiver1975 could it be the roundcube table ?

It seems varchar is also used in core tables, which are known to update properly.
So, likely to be related to third party apps.

@JanWelker besides roundcube, do you have any other 3rdparty apps installed ?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 could it be the roundcube table ?

looks like - I wonder if this is related to the casing of the type varchar vs VARCHAR

**Comment by DeepDiver1975** [comment]
> looks like - I wonder if this is related to the casing of the type varchar vs VARCHAR

@VicDeo can I ask you to dig into this? I guess doctrine is not comparing the types case in-sensitive. THX

**Comment by JanWelker** [comment]
@DeepDiver1975 only roundcube if I am not mistaken. Is there a way to view or remove apps from the filesystem? I do not have access to the admin interface because of the problem.

**Comment by VicDeo** [comment]
@DeepDiver1975 on it

**Comment by VicDeo** [comment]
@JanWelker can you add
```		$args->getConnection()->getDatabasePlatform()->registerDoctrineTypeMapping('varchar', 'string');
```
after this line https://github.com/owncloud/core/blob/stable8/lib/private/db/sqlitesessioninit.php#L44 
and retry?

**Comment by VicDeo** [comment]
hmmm. it's even more interesting.
@JanWelker Can you recall OC version of good old times you installed roundcube?

this is what I have while installing it on OC7.0.4:

>CREATE TABLE "oc_roundcube" ("id" INTEGER NOT NULL, "oc_user" CLOB DEFAULT '' NOT NULL, "mail_user" CLOB DEFAULT '' NOT NULL, "mail_password" CLOB DEFAULT '' NOT NULL, PRIMARY KEY("id"));

when I create the table manually using your query Doctrine claims there no mapping for type `varchar ` (note the trailing space)

**Comment by VicDeo** [comment]
Looks like this is known issue for an old roundcube  releases:
https://github.com/owncloud/core/issues/6416#issuecomment-34695075

**Comment by DeepDiver1975** [comment]
> $platform->registerDoctrineTypeMapping('varchar ', 'string');

we should at least fix this from my pov - THX

**Comment by VicDeo** [comment]
@DeepDiver1975 ok, fix pushed

@JanWelker would you like to help in testing https://github.com/owncloud/core/pull/14308 ?

**Comment by JanWelker** [comment]
@VicDeo I tested #14308 and it worked like a charm. Thanks a lot.
I unfortunately do not know what version I initially installed since I ended up not using it.
