### ISSUE TITLE
[LDAP Wizard] Valid configuration is reported as invalid

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#14244]
### Steps to reproduce
1. Go to the LDAP wizard and create a valid configuration
2. From this valid configuration, change the server url to a non-existing one. This should report an invalid configuration
3. Change the url back to the previous one.

### Expected behaviour
The wizard should report a valid configuration as it's done in the step 1

### Actual behaviour
The wizard reports an invalid configuration. Changing the tab to the user filter (and probably any other) reports the configuration fine.
Also the ldap:test-config shows the correct information

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** sqlite3

**PHP version:** 5.5.9

**ownCloud version:** 8.0 (stable)

**Updated from an older ownCloud or fresh install:** updated from OC 7.0.5

**Comment by jvillafanez** [comment]
Looks like it's working as expected in OC 7.0.5

**Comment by PVince81** [comment]
I remember seeing a similar problem if I mistyped the server password then came back to change it. It wouldn't change back from red to green. But I don't remember if it was in OC 6 or OC 7.

CC @blizzz

**Comment by blizzz** [comment]
I guess I know what it may cause it. Will fix it along with 8.1 improvements.

**Comment by blizzz** [comment]
Fixed in https://github.com/owncloud/core/pull/15492

**Comment by MorrisJobke** [comment]
The PR is merged
