### ISSUE TITLE
ownCloud 7 doesn't show update to version 8 (one week after the release)

### ISSUE THREAD

**Issue by JimLoose** [owncloud/core#14241]
It's almost a week since ownCloud 8 has been released.

Unfortunately my version ownCloud 7.0.4 doesn't show any update in it's update center:

![image](https://cloud.githubusercontent.com/assets/195000/6205584/bccc8b0e-b573-11e4-8b90-8869c5c5a2b5.png)

Whats wrong here again?
(and how to update it anyway?)

**Comment by JimLoose** [comment]
https://apps.owncloud.com/updater.php?version=7x0x2x1x1411115531.08x1414765265xstable

^^  come on, after a week??

**Comment by RealRancor** [comment]
Already reported here: https://github.com/owncloud/updater/issues/74

**Comment by karlitschek** [comment]
We have a few bad bugs in 8.0.0 So maybe we will delay the updater availability for some time before 8.0.1 is out. Sorry for the inconvenience.
