### ISSUE TITLE
occ ldap:search with groups and limit = 0 doesn't return any result

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#14248]
### Steps to reproduce
1. Run `./occ ldap:search --group ''`. This should return some results (up to the default limit)
2. Run `./occ ldap:search --group --limit=0 ''`
### Expected behaviour

This should return all available groups (at least the same groups that are shown in step 1, if not more)
### Actual behaviour

Nothing happens
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** sqlite3

**PHP version:** 5.5.9

**ownCloud version:** OC 7.0.5 (testing)

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by jvillafanez** [comment]
This also happens in OC 8.0.0 updated from OC 7.0.5

**Comment by jvillafanez** [comment]
Still happening in 8.1 alpha 1

**Comment by PVince81** [comment]
Still exists on 9.1.0 beta2
