### ISSUE TITLE
occ ldap:check-user valid user reported as no-longer existent

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#14250]
Possibly related to https://github.com/owncloud/core/issues/14103

### Steps to reproduce
1. Create a valid configuration
2. Run `./occ ldap:check-user <userId>` and verify that the user exists in LDAP (success message should be shown)
3. Disable all configurations and rerun the same command in step 2. (expect an error message since there are disabled configurations)
4. Rerun same command than the step 2 with the "--force" option `./occ ldap:check-user --force <userId>`. Currently the following message shows:

    ```
    The user does not exists on LDAP anymore.
    Clean up the user's remnants by: ./occ user:delete <userID>
    ```

5. Enable the configuration again
6. Run `./occ ldap:check-user <userId>`

### Expected behaviour
The user is available

### Actual behaviour
The user is detected as deleted

```
The user does not exists on LDAP anymore.
Clean up the user's remnants by: ./occ user:delete <userId>
```

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** sqlite3

**PHP version:** 5.5.9

**ownCloud version:** OC 7.0.5 and 8.0.0
**Updated from an older ownCloud or fresh install:** OC 7.0.5 fresh install and updated to 8.0.0 (both versions have the same behaviour)

**Comment by jvillafanez** [comment]
This is still happening in OC 8.1 alpha 1

**Comment by blizzz** [comment]
same as https://github.com/owncloud/core/issues/14489
