### ISSUE TITLE
feature request : Occ need new commands

### ISSUE THREAD

**Issue by cedrilou** [owncloud/core#14252]
Hi, we need two new commands for occ.

-"user:new" for create new user
-"update" for update the version automatically . Same as the update center but in command line.
With this "update" command , it is necessary to have an option to keep the configuration (theme in particular)

Thank you for the quality of your work ;)
Cédric

**Comment by karlitschek** [comment]
user creation should be possible via the provisioning api with a curl request

**Comment by RealRancor** [comment]
> -"update" for update the version automatically . Same as the update center but in command line.
With this "update" command , it is necessary to have an option to keep the configuration (theme in particular)

As ownCloud itself is not providing the update feature itself but within the updater app this could be also part of the updater app: https://github.com/owncloud/updater/issues

**Comment by RealRancor** [comment]
Issue could be closed. The add user command was added in https://github.com/owncloud/core/pull/14794 and the update command was requested in the updater repo.

**Comment by Xenopathic** [comment]
@RealRancor: indeed, this can now be closed :smile:
