### ISSUE TITLE
ldap_control_paged_result_response(): Result is: No such object (32) 

### ISSUE THREAD

**Issue by ckruetze** [owncloud/core#14260]
The error message seems the same as the one in #13151 however as I don't have any speed issues I've opened a new issue.
I get lots of error messages indicating a missing object.
The system is a fresh install of ownCloud 8.0 (stable) on a fresh installed Ubuntu 14.04.
The error message or a very similar one also showed up in ownCloud 7 on an old system.

I'm using LDAP to authenticate users against an samba AD.

```
Error   PHP     ldap_control_paged_result_response(): Result is: No such object (32) at /var/www/owncloud/apps/user_ldap/lib/ldap.php#58    2015-02-16T16:10:16+00:00
Error   PHP     ldap_control_paged_result_response(): Result is: No such object (32) at /var/www/owncloud/apps/user_ldap/lib/ldap.php#58    2015-02-16T16:09:32+00:00
Error   PHP     ldap_control_paged_result_response(): Result is: No such object (32) at /var/www/owncloud/apps/user_ldap/lib/ldap.php#58    2015-02-16T16:05:41+00:00
Error   PHP ldap_control_paged_result_response(): Result is: No such object (32) at /var/www/owncloud/apps/user_ldap/lib/ldap.php#58    2015-02-16T15:59:09+00:00
Error   PHP ldap_control_paged_result_response(): Result is: No such object (32) at /var/www/owncloud/apps/user_ldap/lib/ldap.php#58    2015-02-16T15:59:04+00:00
Error   PHP ldap_control_paged_result_response(): Result is: No such object (32) at /var/www/owncloud/apps/user_ldap/lib/ldap.php#58    2015-02-16T15:58:07+00:00
Error   PHP ldap_control_paged_result_response(): Result is: No such object (32) at /var/www/owncloud/apps/user_ldap/lib/ldap.php#58    2015-02-16T15:57:32+00:00
Error   PHP ldap_control_paged_result_response(): Result is: No such object (32) at /var/www/owncloud/apps/user_ldap/lib/ldap.php#58    2015-02-16T15:57:16+00:00
Error   PHP ldap_control_paged_result_response(): Result is: No such object (32) at /var/www/owncloud/apps/user_ldap/lib/ldap.php#58    2015-02-16T15:53:43+00:00
Error   PHP ldap_control_paged_result_response(): Result is: No such object (32) at /var/www/owncloud/apps/user_ldap/lib/ldap.php#58    2015-02-16T15:53:32+00:00
Error   PHP ldap_control_paged_result_response(): Result is: No such object (32) at /var/www/owncloud/apps/user_ldap/lib/ldap.php#58    2015-02-16T15:51:26+00:00
```

I have tried the script suggested by @blizzz in #13151 an the result is my server (samba) supports Paged Results.
I also tried the ./occ ldap:search suggestion and it returns quickly

```
real 0m0.181s
user 0m0.111s
sys  0m0.048s
```

It doesn't seem to be slow but we don't have that many users (about 50). And everything I would like to do and the user want to do in ownCloud works, so without that error message I wouldn't even know that something is broken.

The only thing that I seem to not be able to get working is the LDAP Group Filter. But as the system works I might not be understanding what the group filter is supposed to do.
The "only those object classes" field works fine but "only from those groups" is always greyed out. I've also tried a manual filter of "(&(|(objectclass=group)(objectclass=top)))" and various others but I always get 0 groups found.
Could this be related? Is the object that doesn't exist supposed to hold group information?

**Comment by LukasReschke** [comment]
@blizzz

**Comment by blizzz** [comment]
32 cannot really be thrown by ldap_control_paged_result_response, it rather seems it slips through from a previous operation. Although we check for errors…

> The "only those object classes" field works fine but "only from those groups" is always greyed out.

In the groups tab? It seems like no group was found. Do your groups follow a custom objectclass (not a standard respectively widely-used one?)

It would be good if you could narrow down to when the error is written to the log. E.g. any action, or just when sharing a file, or just on logins, or… ?

**Comment by blizzz** [comment]
@Xenopathic you use samba4 as well, right, do you see the same?

**Comment by Xenopathic** [comment]
I haven't seen any problems with Samba4 and user_ldap, it all just works as intended. I can test things if needs be though.

**Comment by ckruetze** [comment]
>> The "only those object classes" field works fine but "only from those groups" is always greyed out.
>
>In the groups tab? It seems like no group was found. Do your groups follow a custom objectclass (not a standard respectively widely-used one?)

Not that I know of, actually we don't use many groups at all. But shouldn't the drop down list the usual build in Groups like "Domain Users"?


>It would be good if you could narrow down to when the error is written to the log. E.g. any action, or just when sharing a file, or just on logins, or… ?

There is too much going on for me to find out if it happens on logins or whenever.
I don't think it happens on sharing as nobody creates any shares regularly.

I'm happy to modify the php file to include an extra debug statement just before line 58 in ldap.php.
If you could come up with something that logs either the statement or at least the username causing this error that would be great. Sadly I don't know enough about ownCloud to come up with something myself.

**Comment by ckruetze** [comment]
I've looked at the raw log file that shows the remote address, (would be nice to also show that in the web interface).

Now I'm actually more confused then before.
The error happens for all users as far as I can see from the remoteAddr part of the log file.
But for my IP it happened yesterday around 2pm and then this morning around 10am.
I'm 100% sure that I did log in between those times and that I changed and created files between those times.

This morning my IP produced the error at:
```
2015-02-19T10:09:21+00:00
2015-02-19T10:09:22+00:00
2015-02-19T10:09:22+00:00
2015-02-19T10:09:22+00:00
2015-02-19T10:09:22+00:00
2015-02-19T10:09:22+00:00
2015-02-19T10:09:22+00:00
2015-02-19T10:09:22+00:00
2015-02-19T10:09:22+00:00
2015-02-19T10:09:22+00:00
2015-02-19T10:09:22+00:00
2015-02-19T10:09:22+00:00
2015-02-19T10:09:22+00:00
2015-02-19T10:09:22+00:00
2015-02-19T10:09:22+00:00
2015-02-19T10:09:22+00:00
2015-02-19T10:09:22+00:00
2015-02-19T10:09:22+00:00
2015-02-19T10:09:22+00:00
```

Another PC that got turned on this morning and uses the same WebDav connection (different user name and password) only produced two entries in the log file.

Just thinking out loud but there is one difference between my account and the account that only produced two entries. I have access to 16 shares and the other user has 6 shares. But still those numbers don't add up to the number of errors in the log...

**Comment by blizzz** [comment]
May you show us your LDAP config? run  ```./occ ldap:show-config``` as web user on command line.

**Comment by ckruetze** [comment]
@blizzz  sure, no problem. I would have uploaded it, but I couldn't figure out how to upload a text document, so here it is inline.
I've changed the username, and domain name.
```
+------------------------------+------------------------------------------------------------------------------------------+
|[32m Configuration                [39m|[32m                                                                                          [39m|
+------------------------------+------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport     | 0                                                                                        |
| hasPagedResultSupport        |                                                                                          |
| homeFolderNamingRule         |                                                                                          |
| lastJpegPhotoLookup          | 0                                                                                        |
| ldapAgentName                | xxxx@mydomain.com                                                                        |
| ldapAgentPassword            | xxx                                                                                      |
| ldapAttributesForGroupSearch | samaccountname                                                                           |
| ldapAttributesForUserSearch  |                                                                                          |
| ldapBackupHost               |                                                                                          |
| ldapBackupPort               | 389                                                                                      |
| ldapBase                     | cn=Users,dc=mydomain,dc=com                                                              |
| ldapBaseGroups               | ou=Users,dc=mydomain,dc=com                                                              |
| ldapBaseUsers                | dc=mydomain,dc=com                                                                       |
| ldapCacheTTL                 | 600                                                                                      |
| ldapConfigurationActive      | 1                                                                                        |
| ldapEmailAttribute           | mail                                                                                     |
| ldapExperiencedAdmin         | 1                                                                                        |
| ldapExpertUUIDGroupAttr      |                                                                                          |
| ldapExpertUUIDUserAttr       |                                                                                          |
| ldapExpertUsernameAttr       | sAMAccountName                                                                           |
| ldapGroupDisplayName         | cn                                                                                       |
| ldapGroupFilter              | (&(|(objectclass=group)(objectclass=top)))                                               |
| ldapGroupFilterGroups        |                                                                                          |
| ldapGroupFilterMode          | 1                                                                                        |
| ldapGroupFilterObjectclass   | group                                                                                    |
| ldapGroupMemberAssocAttr     | member                                                                                   |
| ldapHost                     | mysambaserver.mydomain.com                                                               |
| ldapIgnoreNamingRules        |                                                                                          |
| ldapLoginFilter              | (&(|(objectclass=person)(objectclass=user))(samaccountname=%uid))                        |
| ldapLoginFilterAttributes    |                                                                                          |
| ldapLoginFilterEmail         | 0                                                                                        |
| ldapLoginFilterMode          | 1                                                                                        |
| ldapLoginFilterUsername      | 1                                                                                        |
| ldapNestedGroups             | 0                                                                                        |
| ldapNoCase                   | 1                                                                                        |
| ldapOverrideMainServer       | 0                                                                                        |
| ldapPagingSize               | 500                                                                                      |
| ldapPort                     | 389                                                                                      |
| ldapQuotaAttribute           |                                                                                          |
| ldapQuotaDefault             |                                                                                          |
| ldapTLS                      | 0                                                                                        |
| ldapUserDisplayName          | displayname                                                                              |
| ldapUserFilter               | (&(objectClass=user)(memberOf=cn=cloudusers,ou=serviceaccounts,dc=mydomain,dc=com))      |
| ldapUserFilterGroups         |                                                                                          |
| ldapUserFilterMode           | 1                                                                                        |
| ldapUserFilterObjectclass    | user                                                                                     |
| ldapUuidGroupAttribute       | auto                                                                                     |
| ldapUuidUserAttribute        | auto                                                                                     |
| turnOffCertCheck             | 0                                                                                        |
+------------------------------+------------------------------------------------------------------------------------------+
```

**Comment by Xenopathic** [comment]
Ah, I just got this error using OpenLDAP. It only happened once though, just after setting up an LDAP configuration for the first time. Not sure if it's related?

**Comment by fritz-fritz** [comment]
I get this error as well. I am trying to use owncloud authenticating against zimbra's builtin openldap.

This error is new though. It finds 0 groups (i have no groups and no group filter in place). However, I also cannot get owncloud to find any users. The filters I use work properly when using ldap_search from the command line...

**Comment by nilo72** [comment]
I got this error as well. My ActiveDirectory-Admin drives crazy when his AD-Servers ran to 100% CPU in that kind of situations. But I found a workaround which might work for others. Setting the value of 'Paging chunksize' in the LDAP-Config-Dialog higher than the number of users solves the problem for me and the AD-Admin :-).

**Comment by bitbull06** [comment]
`ldap_control_paged_result_response(): Result is: No such object (32) at /var/www/html/owncloud/apps/user_ldap/lib/ldap.php#63` points in the same direction of the main issue i guess

**Comment by ckruetze** [comment]
Just to confirm this is still an issue in ownCloud 9.0.1
Chinging the Paging chunksize option as suggested by @nilo72 didn't help. We have it set to 500 but we have under 50 users.

The error changed a little as in now it is
`ldap_control_paged_result_response(): Result is: No such object (32) at /var/www/owncloud/apps/user_ldap/lib/ldap.php#70`
But other then the 70 at the end the rest is the same, today I already got several hundred of those errors.

**Comment by clvsle** [comment]
I can also confirm with @ckruetze that the problem still exists and in 9.0.2.  I had moved up my paging chunksize to 500 with only 18? users - and i'm still getting a bunch of these errors.  Could anyone offer us some feedback?

Thanks!

**Comment by ynott** [comment]
I got the same errors at my ownCloud.

```{"reqId":"sieeE0DZ5NUgmyzAjseb","remoteAddr":"","app":"PHP","message":"ldap_control_paged_result_response(): No server controls in result at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#70","level":3,"time":"2016-10-31 14:58:27","method":"--","url":"--","user":"--"}
{"reqId":"sieeE0DZ5NUgmyzAjseb","remoteAddr":"","app":"PHP","message":"ldap_control_paged_result_response(): No server controls in result at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#70","level":3,"time":"2016-10-31 14:58:28","method":"--","url":"--","user":"--"}
{"reqId":"sieeE0DZ5NUgmyzAjseb","remoteAddr":"","app":"PHP","message":"ldap_control_paged_result_response(): No server controls in result at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#70","level":3,"time":"2016-10-31 14:58:28","method":"--","url":"--","user":"--"}
{"reqId":"sieeE0DZ5NUgmyzAjseb","remoteAddr":"","app":"PHP","message":"ldap_control_paged_result_response(): No server controls in result at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#70","level":3,"time":"2016-10-31 14:58:28","method":"--","url":"--","user":"--"}
{"reqId":"sieeE0DZ5NUgmyzAjseb","remoteAddr":"","app":"PHP","message":"ldap_control_paged_result_response(): No server controls in result at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#70","level":3,"time":"2016-10-31 14:58:28","method":"--","url":"--","user":"--"}
{"reqId":"sieeE0DZ5NUgmyzAjseb","remoteAddr":"","app":"PHP","message":"ldap_control_paged_result_response(): No server controls in result at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#70","level":3,"time":"2016-10-31 14:58:29","method":"--","url":"--","user":"--"}
```

```
# sudo -u nginx ./occ status
  - installed: true
  - version: 9.0.4.1
  - versionstring: 9.0.4
  - edition
```

I also changed paging size.
```
| ldapPagingSize                | 1500                                         |
```

Dose anyone have a knowledge for us?
OR workarounds.

**Comment by bitbull06** [comment]
issue solved for me by configuring the following in 'advanced' tab of LDAP options:
- activating nested groups
- eliminating non-existing OUs for users
- setting paging chunk size to 0
afterwards, the error doesn't show up in logging anymore

**Comment by PVince81** [comment]
Please reopen in the [user_ldap app repo](https://github.com/owncloud/user_ldap) if the issue persists with 10.0.4 and the latest version of the user_ldap app from the marketplace.

**Comment by Dr4K4n** [comment]
I just had this error message when i tried `occ files:scan --all`
Turned out it was a configuration error. owncloud could not find my groups because a wrong group base DN was provided. Maybe this info helps someone coming here from google.
