### ISSUE TITLE
[master] 412/csrf check missing 

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#14264]
GET http://localhost:8888/index.php/apps/files_sharing/api/externalShares 412 (Precondition failed)jquery.min.js?v=91f8e4b41173d465d8e6d24fc21f3ba7:6 x.ajaxTransport.sendjquery.min.js?v=91f8e4b41173d465d8e6d24fc21f3ba7:6 x.extend.ajaxjquery.min.js?v=91f8e4b41173d465d8e6d24fc21f3ba7:6 x.each.x.(anonymous function)external.js?v=91f8e4b41173d465d8e6d24fc21f3ba7:123 OCA.Sharing.ExternalShareDialogPlugin.processSharesToConfirmexternal.js?v=91f8e4b41173d465d8e6d24fc21f3ba7:74 OCA.Sharing.ExternalShareDialogPlugin.attachjs.js?v=91f8e4b41173d465d8e6d24fc21f3ba7:559 OC.Plugins.attachapp.js?v=91f8e4b41173d465d8e6d24fc21f3ba7:83 OCA.Files.App.initializeapp.js?v=91f8e4b41173d465d8e6d24fc21f3ba7:224 (anonymous function)underscore.js?v=91f8e4b41173d465d8e6d24fc21f3ba7:666 (anonymous function)

**Comment by DeepDiver1975** [comment]
@LukasReschke any clue? THX

**Comment by DeepDiver1975** [comment]
same for favorities

````
http://localhost:8888/index.php/apps/files/api/v1/tags/_$!%3CFavorite%3E!$_/files 412 (Precondition failed)

**Comment by LukasReschke** [comment]
Is it really the CSRF check or https://github.com/owncloud/core/blob/e8f90133e0b964a51590422668fca32e6d87d362/lib/private/appframework/middleware/security/securitymiddleware.php#L130? 

Works fine here… - Also a screenshot of your request would be nice (does it include the CSRF token? – if so equals it to the one echoed in the HTML template?)

**Comment by LukasReschke** [comment]
Also: Are you still logged-in or is this an old browser tab?

**Comment by DeepDiver1975** [comment]
the response holds

{"message":"CSRF check failed"}

**Comment by LukasReschke** [comment]
Could be everything, I need at least to see the request and which token is stored in the session. Even easier to debug would be if you could add some debug statements at https://github.com/owncloud/core/blob/f82b710e383882c09a77c23c6cd312d6ed5b7f42/lib/private/appframework/http/request.php#L393-L422 to see where it exactly fails and what `$this->items['requesttoken']` does equal to.

I tried a lot of things but it works all the time locally here…

**Comment by DeepDiver1975** [comment]
I'll debug this tomorrow .....

**Comment by LukasReschke** [comment]
THX

**Comment by PVince81** [comment]
Have the same issue with a new install.
Also couldn't login with WebDAV.

Will try and gather more info.

**Comment by PVince81** [comment]
Bisected, the breaking commit is this one: 87db136508f6599568eedf8f7696c6ebea4f56c1 from https://github.com/owncloud/core/pull/13879
Very strange.

**Comment by PVince81** [comment]
I double checked by resetting OC before and on this commit and also clearing the cache.
On the commit, tagging shows the CSRF error. Before that commit it works.

While the commit doesn't seem to contain any related stuff, it still seems to be that one commit. Strange stuff.

**Comment by DeepDiver1975** [comment]
well with this commit the load order of objects within the server container changed .. might be related

We can try to NOT inject \OC::$server->getLogger() ...
