### ISSUE TITLE
Updates between multiple major versions are unsupported.

### ISSUE THREAD

**Issue by ginsa** [owncloud/core#14265]
After manual upgrade on OMV server:
Updating ownCloud to version 8.0, this may take a while.
Turned on maintenance mode
Updates between multiple major versions are unsupported.
The update was unsuccessful. Please report this issue to the ownCloud community.

**Comment by LukasReschke** [comment]
From which previous version did you update to ownCloud 8? You can only update from 6 to 7 to 8 but not directly from 7 to 8.

**Comment by ginsa** [comment]
I updated from 7 to 8. I didn't know it wasn't possible.

**Comment by LukasReschke** [comment]
From 7 to 8 should work. But then please edit your original issue to use the issue template. Thanks. See https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by Poulpatine** [comment]
Hi,

you should check in your config/config.php for a 'version' variable. Personnaly, I had a 5.0.18 version which I suppose had never been updated despite the multiple upgrades (I was in 7.0.4 version).

Change this line to 7.0.1 (for an instance) and upgrade will be ok.

**Comment by ginsa** [comment]
Thank you very much, I'll try to do that.

**Comment by MorrisJobke** [comment]
@ginsa Please reopen if this issue still exists for you. Thanks

**Comment by elalimellamoysoyelamo** [comment]
Hi, i'm facing the same problem!, but instead of having a 6 or 5 version mine is 4.90.11 and as a dumb i clicked the upgrade button without thinking, can anyone have a an advice for me.
thanks a lot.
