### ISSUE TITLE
8.0 upgrade error: An exception occurred while executing 'INSERT INTO `oc_oc_filecache_ym36cxf92kb0n` SELECT * FROM `oc_filecache`': SQLSTATE[HY000]: General error: 1114 The table 'oc_oc_filecache_ym36cxf92kb0n' is full

### ISSUE THREAD

**Issue by plars3n** [owncloud/core#14272]
An exception occurred while executing 'INSERT INTO `oc_oc_filecache_ym36cxf92kb0n` SELECT * FROM `oc_filecache`': SQLSTATE[HY000]: General error: 1114 The table 'oc_oc_filecache_ym36cxf92kb0n' is full

**Comment by karlitschek** [comment]
This sounds like a problem with your database server. Please check that you have enough disk space for example.

**Comment by plars3n** [comment]
I just checked disk space and found I had none. I deleted a few big files, re-ran the install. Voila! Everything works!

Thanks!
