### ISSUE TITLE
Cannot update News app after upgrade to OC8

### ISSUE THREAD

**Issue by buzzra** [owncloud/core#14271]
I opened this in the News app repo a few days ago, but was told to open it in Core. Issue 730 in News.

I tried to update the News using the "update to 5.2.2" button in the ownCloud web client. It came back done with no errors, but still showed the older version. when I logged out and back in, the app showed 4.3.0 and the "update to 5.2.2" button was still present.

Thanks
buzz

**Comment by RealRancor** [comment]
Direct ref to your issue at the news issue tracker: https://github.com/owncloud/news/issues/730

I think it could be also useful if you're updating your post with the issue template (see yellow box when creating a new issue) to provide more infos about your environment.

**Comment by buzzra** [comment]
Thanks, I did not know how to direct ref an issue in another repo.

### Steps to reproduce
1.click update button for news app on apps page in web client
2.wait until update stops
3.note version does not change
4.log out and log back in
5.note update button is back and version did not change

### Expected behaviour
news app should update to newest version and show correct version with no update button in apps page

### Actual behaviour
appears to update but does not

### Server configuration
**Operating system**:
Linux Mint 13 Maya
**Web server:**
Apache2
**Database:**
Mysql
**PHP version:**
5.4.37-1+deb.sury.org~precise+1 (from phpinfo.php page)
**ownCloud version:** (see ownCloud admin page)
ownCloud 8.0
**Updated from an older ownCloud or fresh install:**
updated from 7.0.4
**List of activated apps:**
 activity
 bookmarks
 external
 files
 files_epubviewer
 files_external
 files_opds
 files_pdfviewer
 files_sharing
 files_texteditor
 files_trashbin
 files_versions
 files_videoviewer
 firstrunwizard
 gallery
 news
 templateeditor
 updater
**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'occ5a70f5eb8',
  'passwordsalt' =>
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.0.0.7',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' =>
  'installed' => true,
  'maxZipInputSize' => 0,
  'allowZipDownload' => true,
  'loglevel' => '2',
  'logtimezone' => 'America/Chicago',
  'log_rotate_size' => 104857600,
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' =>
  array (
    0 => 'kashmir.vanelli.net',
    1 => 'kashmir.vanelli.net',
    2 => '192.168.1.253',
  ),
  'mail_from_address' => 'kashmir',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'vanelli.net',
  'mail_smtphost' => 'zoso.vanelli.net',
  'mail_smtpport' => '25',
  'secret' => 
  'appcodechecker' => false,
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\Image',
    1 => 'OC\\Preview\\MP3',
    2 => 'OC\\Preview\\TXT',
    3 => 'OC\\Preview\\MarkDown',
    4 => 'OC\\Preview\\Epub',
    5 => 'OC\\Preview\\PDF',
    6 => 'OC\\Preview\\OpenDocument',
    7 => 'OC\\Preview\\StarOffice',
    8 => 'OC\\Preview\\MSOfficeDoc',
    9 => 'OC\\Preview\\MSOffice2003',
    10 => 'OC\\Preview\\MSOffice2007',
  ),
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
SMb, SFTP, Google drive, webdav
**Are you using encryption:** yes/no
no
### Client configuration
**Browser:**
Chrome Version 40.0.2214.111 m
**Operating system:**
Windows 7 ultimate x64
### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by RealRancor** [comment]
Hi,

to be able to post the owncloud.log just clean/empty it and then hit the update button for the news app again. Then you should only have the important/relevant log entries for this problem in the owncloud.log

**Comment by buzzra** [comment]
@RealRancor Thanks. I have edited my template comment above with the contents of the owncloud.log file after the procedure you suggested. Sorry for not thinking that through. I should have figured that one out myself.

**Comment by buzzra** [comment]
@RealRancor Is there still more info needed for this?

**Comment by buzzra** [comment]
@LukasReschke 
I see this still says more info needed. Please let me What additional info to provide.

Thanks!

buzz

**Comment by DeepDiver1975** [comment]
I honestly vote for a won't-fix - work for me and a hell of other installations.

Furtermore I see no relevant error message which could lead to an explanation.
