### ISSUE TITLE
Authentication cookie rejected with OC8 (login fails)

### ISSUE THREAD

**Issue by ogasser** [owncloud/core#14276]
### Steps to reproduce
1. Have ownCloud open in a tab
2. Close browser
3. Open browser, tab is reopened automatically
4. Enter login data and click on "Log in"
5. User is **not** logged in, redirected to login page again
6. Entry in `owncloud.log` appears (see below)

### Expected behaviour
Log in should succeed.

### Actual behaviour
Log in does not succeed, maybe related to #854. CC @LukasReschke because you were involved there.
You need to remove the complete path including the `index.php` and change it to `/` and then the log in works.

### Server configuration
**Operating system**: Ubuntu 14.04.1 LTS

**Web server:** nginx 1.4.6

**Database:** PostgreSQL 9.3

**PHP version:** 5.5.9

**ownCloud version:** 8.0.0.7

### ownCloud log (data/owncloud.log)
```
{"reqId":"[removed]","remoteAddr":"[removed]","app":"core","message":"Authentication cookie rejected for user [removed]","level":2,"time":"2015-02-16T22:26:40+00:00","method":"POST","url":"\/index.php?redirect_url=%2Findex.php%2Fapps%2Ffiles%2F"}
```

**Comment by LukasReschke** [comment]
Let me take a look at that later… At some point we need to refactor the whole login logic.

**Comment by PVince81** [comment]
@LukasReschke is this still valid ?

**Comment by PVince81** [comment]
@ogasser are you still seeing this in 8.1.3 or 8.2RC1 ?

**Comment by ogasser** [comment]
It seems to be fixed now. Thanks :+1:
