### ISSUE TITLE
Undefined offset: 3 at \/Users\/lreschke\/Programming\/core\/apps\/files\/controller\/apicontroller.php#105"

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#14277]
On current master when going to the Favourites sidebar:

> {"reqId":"36b9928bf99ddbdbe5e7b8a4a5fdd065","remoteAddr":"::1","app":"PHP","message":"Undefined offset: 3 at \/Users\/lreschke\/Programming\/core\/apps\/files\/controller\/apicontroller.php#105","level":3,"time":"2015-02-16T23:04:37+00:00"}

@PVince81

**Comment by PVince81** [comment]
Strange, I haven't seen this error before. Need to check if it happens on stable8 too.

**Comment by PVince81** [comment]
I wonder if you have broken/bad entries in your DB that would make `$parts[3]` not exist.
I've seen this happen before but couldn't reproduce it.
Basically, you should only be able to tag files under "$user/files". But if somehow some bug managed to tag a file outside of that (ex: in trashbin).

If you still have that setup, can you do the following:
`select * from oc_vcategory`. Pick the id of the one with "favorites" in it.
`select * from oc_filecache fc, oc_vcategory_to_object t where t.categoryid=$THECATEGORYID and t.objid=fc.fileid;` (replace $THECATEGORYID with the one from the favorite tag)

**Comment by LukasReschke** [comment]
Steps to reproduce:

1. Setup a new ownCloud master instance
2. Star the file "welcome.txt"
3. Go to "Favorites"
4. Experience the error message ;-)

DB:
```sql
sqlite> select * from oc_vcategory;
id|uid|type|category
1|admin|files|_$!<Favorite>!$_
```

```sql
sqlite> select * from oc_filecache fc, oc_vcategory_to_object t where t.categoryid=1 and t.objid=fc.fileid;
fileid|storage|path|path_hash|parent|name|mimetype|mimepart|size|mtime|storage_mtime|encrypted|unencrypted_size|etag|permissions|objid|categoryid|type
4|1|files/welcome.txt|c49a144e772727f51b75705170e88a43|3|welcome.txt|4|3|163|1424130986|1424130986|0|0|0cf0d17aca263970f182d8775e72e138|27|4|1|files
```

**Comment by PVince81** [comment]
Huh... that seems to be correct. Unless the format of the path has changed.
If I remember well the reason why it has three parts is because it splits "$user/files/thirdpart" into "$user", "files" and "thirdpart" and picks "thirdpart" alone.

I'll see if I can reproduce it and debug inside.

Do you see the file shown correctly in the favorites list ?

**Comment by LukasReschke** [comment]
> Do you see the file shown correctly in the favorites list ?

Yes.

**Comment by PVince81** [comment]
Okay got it... there is a leading slash in the path: "/user/files/thirdpart" becomes "", "user", "files" and "thirdpart" ...

Let me find out whether this was introduced recently.

**Comment by LukasReschke** [comment]
:see_no_evil:

**Comment by PVince81** [comment]
Seems I always missed it...

If the favorite file is in the root, then `$parts[3]` is not defined, but the path is still correct ("/")
If the file is in a subdir, then `$parts[3]` is defined.

So basically this magically still worked properly.

Let's use your PR that fixes the warning then.
