### ISSUE TITLE
Activity [downloaded] seems to be triggered more than once

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#14270]
### Steps to reproduce

1. Make a public share
2. Download it

### Expected behavior

In the activity view it should be entered as 1 (one) single output.

### Actual behavior

It seems like the output is triggered more than once.

From activity mail:

```
* Der öffentliche geteilte Ordner ownCloud files/Owncloud (delad)/ownCloud pre-installed [Stable 8] [SSL] [Ubuntu Server 14.04] wurde heruntergeladen - I går 15:26:58
* Der öffentliche geteilte Ordner ownCloud files/Owncloud (delad)/ownCloud pre-installed [Stable 8] [SSL] [Ubuntu Server 14.04] wurde heruntergeladen - I går 15:27:17
* Der öffentliche geteilte Ordner ownCloud files/Owncloud (delad)/ownCloud pre-installed [Stable 8] [SSL] [Ubuntu Server 14.04] wurde heruntergeladen - I går 15:27:18
* Der öffentliche geteilte Ordner ownCloud files/Owncloud (delad)/ownCloud pre-installed [Stable 8] [SSL] [Ubuntu Server 14.04] wurde heruntergeladen - I går 15:27:18
* Der öffentliche geteilte Ordner ownCloud files/Owncloud (delad)/ownCloud pre-installed [Stable 8] [SSL] [Ubuntu Server 14.04] wurde heruntergeladen - I går 15:27:18
* Der öffentliche geteilte Ordner ownCloud files/Owncloud (delad)/ownCloud pre-installed [Stable 8] [SSL] [Ubuntu Server 14.04] wurde heruntergeladen - I går 15:27:19
* Der öffentliche geteilte Ordner ownCloud files/Owncloud (delad)/ownCloud pre-installed [Stable 8] [SSL] [Ubuntu Server 14.04] wurde heruntergeladen - I går 15:27:19
```

From the Web UI:

![image](https://cloud.githubusercontent.com/assets/4511254/6218957/1edd6100-b624-11e4-92b9-70b55198e28e.png)

### Server configuration

Ubuntu Server 12.04

**Database:**
Server version: 5.5.41-0ubuntu0.12.04.1 - (Ubuntu)
PHP version:
PHP 5.5.9-1ubuntu4.5 (cli) (built: Oct 29 2014 11:59:10)

**ownCloud version: (see ownCloud admin page)**
8.0
*Updated from an older ownCloud or fresh install:*
5, 6, 7.

**List of activated apps:**
Activity
Calender 
Contacts
Deleted files
Documents
First Run Wizard
Full Text Search
PDF Viewer
Pictures
Share Files
Text Editor
Updater
Versions
Video Viewer

**Are you using external storage, if yes which one: local/smb/sftp/...**
No
**Are you using encryption: yes/no**
No

### Client configuration

**Browser:**
Version 39.0.2171.71 m
**Operating system:**
Windows 8.1
**Sync Client**
1.7.1 stable

### Logs

**Web server error log**

```
Insert your webserver log here
```

**ownCloud log (data/owncloud.log)**

```
No logs
```

**Browser log**

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by enoch85** [comment]
CC @schiesbn

**Comment by nickvergessen** [comment]
Relevant commit 393deb596182deec076cf1d9941eae4ba51f34d4
I assume the controller is triggered for the folder and each file in it. Can you count, whether the number of entries is the same as the number of files + folders in the share?

**Comment by enoch85** [comment]
@nickvergessen There is only one zip file and one .txt in that folder, nothing more. https://en0ch.se/index.php/s/jaBcGYB0BkjaVY7 

Also, in that case it should reference to which file is getting downloaded.

**Comment by nickvergessen** [comment]
Seems to always list the folder instead of the directly downloaded file. Will try to have a look

**Comment by enoch85** [comment]
@nickvergessen Problem seems to persist in 8.0.2

![activity](https://cloud.githubusercontent.com/assets/4511254/7057564/3b8f5186-de57-11e4-99b8-1a03f44d6288.png)

**Comment by nickvergessen** [comment]
Yeah we didnt backport it

**Comment by enoch85** [comment]
Could you please? @karlitschek

**Comment by nickvergessen** [comment]
opened a PR #15502
