### ISSUE TITLE
WebDav and storage limit files unusable

### ISSUE THREAD

**Issue by ckruetze** [owncloud/core#14284]
When a user has exceeded the storage limit it shouldn't be possible for the user to copy files.

System: ownCloud 8 running on Ubuntu 14.04
Client: Ubuntu client with a mounted webDav share for the ownCloud folder

How to reproduce:
The user in question has to exceed the storage limit eg. using 1.5 of 1GB storage.
Now move some files around [Ctrl] + X and then [Ctrl] + V or use the mouse.
The file is deleted at the old location and a new file is created with the correct filename but with 0 Bytes in file size.

I think if the storage size is exceeded it shouldn't be possible to create new files.
Alternatively if WebDav can't handle that it might even be more secure to set the filesystem for that user to read-only for any connections other then the web interface where the user would get a proper warning.

The main idea here is to protect the user files at all cost. suggesting to the user that the file has been moved and even showing it in the new folder but losing all data in the background isn't really a good user experience.

**Comment by DeepDiver1975** [comment]
This is really critical as we shall not kill user data.

**Comment by karlitschek** [comment]
yes. agreed @PVince81

**Comment by PVince81** [comment]
also CC @icewind1991 

I'm not sure whether adding a "check free space" before the copy will help, because concurrency could change the free space just after the check...

Similar to https://github.com/owncloud/core/issues/7626 with encryption.

**Comment by PVince81** [comment]
Ideally the `streamCopy` operation should be able to react on "full disk" space and then cancel the operation. What do you think @icewind1991 ?

**Comment by PVince81** [comment]
Might also affect "move between storages" as long as we have that between shared storage and local storage, because that can also cause a "file copy then delete" operation.

**Comment by PVince81** [comment]
Confirmed on master by moving a big file from a shared folder into the local storage (where local storage is full).

**Comment by PVince81** [comment]
For some reason "streamCopy" returns 1 ("success") even when fwrite didn't succeed.
Digging deeper...

**Comment by PVince81** [comment]
We need to check whether `fwrite()` has indeed written the correct number of bytes, if not it's an error.
https://github.com/owncloud/core/blob/master/lib/private/helper.php#L580

Currently it seems that the code expects "false" to be returned on error, which is not exact. An error is only when invalid arguments are passed, not when not all bytes could be written. Here is more info about this pitfall: http://php.net/manual/de/function.fwrite.php#96951

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/core/pull/14430

**Comment by PVince81** [comment]
A better fix here: https://github.com/owncloud/core/pull/14503
