### ISSUE TITLE
OC8 link sharing retro-compatibility

### ISSUE THREAD

**Issue by ziirish** [owncloud/core#14281]
Hi,

After upgrading from 7.0.4 to 8, my old public links are not working anymore.

Here is the server return:

```
GET /public.php?service=files&t=<sharing_token> HTTP/1.1
host: example.org

HTTP/1.1 304 Found
Server: nginx
Date: Tue, 17 Feb 2015 09:42:57 GMT
Connection: keep-alive
X-Powered-By: PHP/5.4.37-1~dotdeb.1
Set-Cookie: xxxxxxxxxxxxxx=g4rsn0nc4m23on773fc77ai2s7; path=/; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Strict-Transport-Security: max-age=0
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: Sameorigin
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *; connect-src *
X-Robots-Tag: none
Location: /index.php/s/<sharing_token>
```

That is not a cache/browser issue as this output comes from `openssl s_client`.
I don't understand the "304 Found" here but I guess it is causing troubles.

Can anyone reproduce this behavior?

Thanks

**Comment by DeepDiver1975** [comment]
> Location: /index.php/s/<sharing_token>

The browser is supposed to be redirected to the given location - I wonder where 304 is coming from

@LukasReschke THX

**Comment by LukasReschke** [comment]
Very strange. We use `\OC_Response::redirect` which explicitly sets a 307 statuscode. Though I have to say I have no idea about how NGINX works and behaves and guess this might as well be a configuration problem.

@ziirish Can you please provide your NGINX config.

Oh mighty NGINX Guru @josh4trunks, may I ask you if you have any idea what could cause this and whether this works on your NGIXN instance? :smile:

**Comment by ziirish** [comment]
Thanks for investigating on this.

Here is the log of my nginx server:

```
x.x.x.x - - [17/Feb/2015:11:05:02 +0000] "GET /public.php?service=files&t=<sharing_token> HTTP/1.0" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:35.0) Gecko/20100101 Firefox/35.0 Iceweasel/35.0.1"
```

And here is an extract of my nginx configuration (I think it comes from the documentation):

```
    location ~ ^/(data|config|\.ht|db_structure\.xml|README) {
        deny all;
    }

    location / {
        # The following 2 rules are only needed with webfinger
        rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
        rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json last;

        rewrite ^/.well-known/carddav /remote.php/carddav/ redirect;
        rewrite ^/.well-known/caldav /remote.php/caldav/ redirect;

        rewrite ^(/core/doc/[^\/]+/)$ $1/index.html;

        try_files $uri $uri/ index.php;
    }

    location ~ ^(.+?\.php)(/.*)?$ {
        try_files $1 = 404;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$1;
        fastcgi_param PATH_INFO $2;
        fastcgi_param HTTPS on;
        fastcgi_read_timeout 600s;
#       fastcgi_param MOD_X_ACCEL_REDIRECT_ENABLED on;
        fastcgi_pass owncloud;
    }

    # Optional: set long EXPIRES header on static assets
    location ~* ^.+\.(jpg|jpeg|gif|bmp|ico|png|css|js|swf)$ {
        expires 30d;
        # Optional: Don't log access to assets
        access_log off;
    }
```

**Comment by josh4trunks** [comment]
please  replace your try_files line with ```try_files $uri $uri/ /index.php;```

the following aren't crucial but could be improved..
* replace your php location line with the one from the OC7-8 docs
* add the fastcgi_split_pathinfo line from the OC7-8 docs
* replace your script filename and pathinfo lines with the ones from the OC7-8 docs

**Comment by ziirish** [comment]
After applying your suggestions I still have the "304 Found" return code.

**Comment by ziirish** [comment]
Ok, I get it.

The thing is my owncloud instance is behind a reverse-proxy.
As we can see in the log I provided, the protocol used by the reverse-proxy is `HTTP/1.0`.

Your redirect routine only handles the `HTTP/1.1` protocol.

```
 62             case self::STATUS_TEMPORARY_REDIRECT:
 63                 if ($protocol == 'HTTP/1.1') {
 64                     $status = $status . ' Temporary Redirect';
 65                     break;
 66                 } else {
 67                     $status = self::STATUS_FOUND;
 68                     // fallthrough
 69                 }
```

I'll try forcing my RP to use the `HTTP/1.1` protocol.

**Comment by LukasReschke** [comment]
@DeepDiver1975 No idea what would the best approach. Please decide if we want to dig into an alternate solution for HTTP/1.0 or if we consider this a WONT FIX and just document this behaviour…?

**Comment by ziirish** [comment]
I guess there is a reason you try the protocol version used, so I think just adding a note in the documentation should be enough.

**Comment by karlitschek** [comment]
Hmm. I´m not sure it is acceptable for users to lose they sharing links.

**Comment by ziirish** [comment]
I don't think "basic" users should encounter this issue which is caused by a "complex" architecture.

So I guess admins of such an architecture could/should be able to perform the appropriate modifications.

On my nginx RP I had to add the following setting: `proxy_http_version 1.1;`.

My configuration now looks like:

```
    location / { 
        # you need to change this to "https", if you set "ssl" directive to "on"
        proxy_set_header   X-FORWARDED_PROTO https;
        proxy_set_header   Host              $http_host;
        proxy_set_header   X-Forwarded-For   $remote_addr;

        proxy_read_timeout 300;

        proxy_pass http://oc;
        proxy_http_version 1.1;
        proxy_connect_timeout 2;
        proxy_next_upstream     error timeout invalid_header http_500;
    }
```

I think you could add this note in the "upgrade" documentation or something.

**Comment by osamak** [comment]
I have the same issue, and my proxy also uses HTTP 1.0, but in my case, I cannot change the protocol since I'm using a shared Apache/nginx instances.  Is there anyway to workaround this?

**Comment by osamak** [comment]
Is it still appropriate to label this bug report with _needs info_?

**Comment by DeepDiver1975** [comment]
@LukasReschke do I get this right? We try to send 307/Temporary Redirect which simply does not exist in http/1.0? Should we got for 302 - which was the temporary redirect in http/1.0

see http://benramsey.com/blog/2008/07/http-status-redirection/

**Comment by ziirish** [comment]
I don't remember exaclty, but I think the HTTP code 307 is not the only problem. I think there is some kind of test against the HTTP protocol version too.

I'll try to take a look at it.

**Comment by osamak** [comment]
This bug is still a major upgrading blocker.

**Comment by osamak** [comment]
Are there any workarounds suggested for this bug?

**Comment by julakali** [comment]
Thanks for the nginx-workaround. I'm using nginx as reverse proxy, too and encountered this issue.
How about at least printing out a page with the new link for http/1.0? This is much better than just doing nothing and providing users with a blank page.
The error could also be logged, so admins are aware WHY users are not automatically redirected.

**Comment by Gomez** [comment]
I can confirm that 
```
proxy_http_version 1.1;
```
fixes the problem on my nginx reverse proxy. But as suggest this should be fixed in oC Code.

**Comment by PVince81** [comment]
@rperezb sounds like something you reported recently too ?

**Comment by rperezb** [comment]
It could be, I ask the user to report it on github...however,  it hasn't happened :(

His problem was  that the url: https://server/public.php/s/Tgzidip14A3dauL was not working, this is the one generated from the iOS app, however, if he changed manually to  https://server/index.php/s/Tgzidip14A3dauL

**Comment by LukasReschke** [comment]
> His problem was that the url: https://server/public.php/s/Tgzidip14A3dauL was not working, this is the one generated from the iOS app, however, if he changed manually to https://server/index.php/s/Tgzidip14A3dauL

The old public.php route is only registered if you update from an older ownCloud version. Please take a look at https://github.com/owncloud/client/blob/07ddf18b3b1e15ddc754c90fad2d0239e021a9d3/src/gui/sharedialog.cpp#L359-L372 to see how the desktop client does it. That said, with 8.2 the server returns the actual URL.

**Comment by rperezb** [comment]
thanks @LukasReschke, yes, it´s included on the mobile roadmap (Android and iOS) update the sharelink methods to that

**Comment by MorrisJobke** [comment]
As there is a work around for this special setup available (https://github.com/owncloud/core/issues/14281#issuecomment-121617952) I think it would be too much to add more special code paths that are hard to test and should be fixed in another layer of the architecture (proxy setup).

I will close this ticket here. Feel free to reopen if the presented solution doesn't fit.
