### ISSUE TITLE
EventSource fallback will not work with IE versions that support CSP

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#14286]
With [TP Microsoft is considering supporting the Content-Security-Policy](http://caniuse.com/#feat=contentsecuritypolicy), however it will most likely [still not support EventSource's](http://caniuse.com/#feat=eventsource). Our fallback relies on Inline JavaScript and everything in regard to EventSource (Updating / Files handling / Gallery / etc…) will fail horribly once MS ships TP…

We need to adjust the CSP (maybe https://github.com/owncloud/core/pull/13989 can help here) or somehow differently fix this behaviour…

**Comment by LukasReschke** [comment]
cc @icewind1991 fyi

**Comment by LukasReschke** [comment]
Also see https://status.modern.ie/contentsecuritypolicy

**Comment by oparoz** [comment]
The EventSource fallback just doesn't work period.

1. Install oC8
2. Click on the "Pictures" app
3. Stare at the spinning wheel forever
4. Look at the debugger. All the data is there, just never sent to where it's supposed to

I'm saying this in hope that the oC team will consider replacing OC_EventSource with a maintained polyfill and perhaps raise an issue there regarding upcoming changes in IE.

**Comment by LukasReschke** [comment]
@jnfrmarks Has this been tested?

**Comment by karlitschek** [comment]
@jnfrmarks Can you test?

**Comment by jnfrmarks** [comment]
@davitol 

Can you please give this a try?

**Comment by oparoz** [comment]
I've tested Pictures with Azure RemoteApp and it crashes the browser.
