### ISSUE TITLE
htaccess not updated if ugrading from occ

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#14280]
https://github.com/owncloud/core/blob/master/lib/private/updater.php#L191

**Comment by LukasReschke** [comment]
IMHO that whole IF block makes no sense at all. This will also fail hard in case somebody uses Apache in combination with mod_security (and hides their server headers) etc…

Why not remove that whole if block? It wouldn't hurt at all to have those `.htaccess`'s also under NGINX / Windows updated.

**Comment by DeepDiver1975** [comment]
> Why not remove that whole if block? It wouldn't hurt at all to have those .htaccess's also under NGINX / Windows updated.

way to go .. thx
