### ISSUE TITLE
[Feature request] Public upload without the possibility of overwriting existing files 

### ISSUE THREAD

**Issue by fossxplorer** [owncloud/core#14292]
Currently, when a folder is used for public upload and one uploads a file with existing name, an option is given to keep the original or overwrite it. Sometimes the intention is to allow for public upload, but not to edit or replace anything that's already there. 

Thanks.

**Comment by PVince81** [comment]
This would be covered by an "upload-only" feature where people don't see the contents of the folder and no overwriting would happen anyway.

**Comment by PVince81** [comment]
upload-only is available since OC 10
