### ISSUE TITLE
Empty files creating  time to time in DATA folder after oC upgrade 7.0.4

### ISSUE THREAD

**Issue by iliyasbasir** [owncloud/core#14294]
#### Expected behavior
Empty file should not be created on data folder.
#### Actual behavior
After upgrading form 6.0.5 to 7.0.4 customer noticed files in data “directory” appear from time to time with the object guid value of users. These directories are typically empty or have an empty files directory inside them. When Customer looked up these guids found out that it's represented user. As well noticed a proper directory named for their VPN attribute that contains their data, confirming there is no data in these directories,

We had screen share with customer and noticed directory also noticed that some file name is  encrypted password of users which listed on  oc_users table in Password* column.

This issue not impacting user share. 
####  Step to reproduce
I cannot reproduced this issue
#### Server configuration
Operating system: centos 6.6
Web server: Apache 2.2.15
Database:
PHP version:5.5.20
ownCloud version:7.0.4
Storage backend:
Client configuration
Client version:
Operating system:
OS language:
Installation path of client:

**Comment by DeepDiver1975** [comment]
enabled apps?
server os?

Please supply all information as requested in the issue template - THX

**Comment by RealRancor** [comment]
Hi,

isn't this something which is fixed in OC 7.0.5 according to the preliminary changelog:

>Fix creation of ghost directories in certain situations
https://owncloud.org/releases/Changelog

Ref: https://github.com/owncloud/core/pull/13927

**Comment by iliyasbasir** [comment]
Hopefully...7.0.5 release will resolved issue

Thank you
-Iliyas
