### ISSUE TITLE
Public upload and existing files

### ISSUE THREAD

**Issue by fossxplorer** [owncloud/core#14291]
When choosing to overwrite with the existing with the new file, i get a "internal server error" message from oC's notification area.
Web server log related to the replacement of an existing file:
FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function get() on a non-object in /var/www/apps/music/utility/scanner.php on line 85" while reading response header from upstream, client: xx.xxx.xx.xx., server: example.com, request: "POST /index.php/apps/files/ajax/upload.php HTTP/1.0", upstream: "fastcgi://unix:/var/run/php-fpm/example.com.sock:", host: "example.com", referrer: "https://example.com/public.php?service=files&t=aadda235f2a44a4ed8731a9be0a5e88b"

This seems not to happen on another oC instance without Music app.

@PVince81 @MorrisJobke

**Comment by PVince81** [comment]
Having public upload for upload only without edit, that's a feature request.

I'll keep this ticket for the bug instead. I remember this used to work before.

**Comment by LukasReschke** [comment]
@PVince81 `/var/www/apps/music/utility/scanner.php` looks like more a bug in @MorrisJobke's code? :see_no_evil:

**Comment by MorrisJobke** [comment]
@fossxplorer which version of the music app? 0.3.5?

**Comment by fossxplorer** [comment]
0.2 @MorrisJobke

**Comment by MorrisJobke** [comment]
@fossxplorer I just tested some hours ago music master with core master and stable7. So it should work.

**Comment by PVince81** [comment]
Any news ?

**Comment by fossxplorer** [comment]
@PVince81 i will update the instance to 7.0.5 this weekend and report back :)

**Comment by PVince81** [comment]
@fossxplorer if it didn't work with 8.0.6 or 8.1.1, please reopen :wink:
