### ISSUE TITLE
Setting base URI for WebDAV

### ISSUE THREAD

**Issue by HontoNoRoger** [owncloud/core#14299]
In order to fix certain problems with Office and WebDAV (see #14157) I had to use several rewrite rules in Apache to avoid the typical WebDAV problem `Requested uri (…) is out of base uri`.
These rewrite rules brought another problem with renaming / moving files through Windows (see #5942).
So to actually use my rewrite rules without problems when renaming / moving files, I had to add another rule with another Apache mod.

```apache
RequestHeader edit Destination /remote/(.*)$ /remote.php/webdav/$1
```

While this approach works for specific problems, it's not a general solution.
Isn't there an easy way to change the base URI the integrated WebDAV server uses, like overwriting it in the `config.php`?
I would appreciate a simple way of using other base URIs to mount the WebDAV drive without changing the internal functions. Thanks!

**Comment by PVince81** [comment]
The code that sets the base URI is here, you might be able to hack it by replacing that line:
https://github.com/owncloud/core/blob/master/apps/files/appinfo/remote.php#L35

Also for server to server sharing:
https://github.com/owncloud/core/blob/master/apps/files_sharing/publicwebdav.php#L29

Maybe a new setting "overwritebaseuri" could be provided and set there ?

**Comment by HontoNoRoger** [comment]
@PVince81 A setting like `overwritebaseuri` would be awesome. I guess it's not even so hard to implement, since you already pointed out where the basepath could be manipulated.

**Comment by Xenopathic** [comment]
`overwrite*` is used for reverse proxy configuration, not rewriting URIs. That is down to the web server - ownCloud cannot do much about it.
