### ISSUE TITLE
Add a check for webserver configs (request limiting) to avoid sync/upload problems

### ISSUE THREAD

**Issue by ghost** [owncloud/core#14307]
Hi,

there is a Apache config option called "LimitRequestBody" (https://httpd.apache.org/docs/2.4/en/mod/core.html#limitrequestbody) which can be set to either 0 for unlimited or a max. of 2GB.

The default for this is unlimited (0) but some howtos / tutorials are recommending to limit this because of "security" reasons. This can cause various issues like: https://github.com/owncloud/core/issues/1270 , https://github.com/owncloud/core/issues/13065 , https://github.com/owncloud/core/issues/9832

I don't know if it is possible to check this value from within PHP but if this is possible it is really recommended to add a check for this into ownCloud to avoid such problems in the future.

**Comment by RealRancor** [comment]
Btw. i don't know if there are other similar options for Nginx, PHP-FPM, (f)cgi and similar other used components which should be also checked.

**Comment by ckruetze** [comment]
Hi,
I don't think there is a good way to access the Apache configuration from within PHP.

You could try mod_info I think it includes the LimitRequestBody.

Alternatively you could read the apache config file directly as in open the text file and read it.
Problem would be to locate the correct file to read and to get the necesary permissions to actually read it. The cleaner solution would be mod_info but that's one more module to load.

If you do end up using mod_info it would be nice to get the output somewhere in the admin part of the ownCloud webinterface.

**Comment by RealRancor** [comment]
Collection of some webserver configs which are known to break the file upload:

Apache
LimitRequestBody (https://httpd.apache.org/docs/2.4/en/mod/core.html#limitrequestbody)
SSLRenegBufferSize (https://httpd.apache.org/docs/trunk/mod/mod_ssl.html#sslrenegbuffersize)

NginX
client_max_body_size (http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size)

Apache with mod_fcgid
FcgidMaxRequestLen (https://httpd.apache.org/mod_fcgid/mod/mod_fcgid.html#fcgidmaxrequestlen)

IIS
maxAllowedContentLength (http://www.iis.net/configreference/system.webserver/security/requestfiltering/requestlimits#005)

Source of this is our FAQ at the forums: http://forum.owncloud.org/viewtopic.php?f=17&t=7733

**Comment by MorrisJobke** [comment]
@LukasReschke Something for our setup check?
