### ISSUE TITLE
App access to certain groups fails

### ISSUE THREAD

**Issue by nolash** [owncloud/core#14305]
Using 7.0.2

When I limit access to one or more groups, the app disappears for all users, regardless of groups they belong to.

If i enable for a group I myself belong to, the app appears in the dropdown list, but if I click it I reach a blank screen. If I refresh the page, it's gone again.

**Comment by LukasReschke** [comment]
Which apps?

Can you also fill out the issue template? Thanks! https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by DeepDiver1975** [comment]
no feedback -> close
