### ISSUE TITLE
run occ upgrade as apache user

### ISSUE THREAD

**Issue by conrel** [owncloud/core#14301]
I'm running OC on an OpenVZ CentOS system and got another update now. Feared to death because of all my encrypted data (and the last update process which tokk 2hours) I made a backup etc and what I find a bit misterious since OC8 is, that I have to run ./occ upgrade explicitly as the apache user and not as root. I now tried "runuser" and "su" but I always get an error saying "the user is not available" (since it is set to /sbin/nologin in etc/passwd). My "workaround" so far is to use the crond but that is really ugly of cause. Especially because I don't get any output of the process... Does anyone know how I can solve this?

best regards
conrel

**Comment by RealRancor** [comment]
Hi,

i think thats more a question which should be asked at the forums or the users mailinglist. This issue tracker is used for bugs in ownCloud itself and this one is very likely not a bug in OC.

Ref. for the reason why you need to run as webserver user: https://github.com/owncloud/documentation/issues/815
