### ISSUE TITLE
Identifier "OCP\INavigationManager" is not defined.

### ISSUE THREAD

**Issue by nocard** [owncloud/core#14317]
I shall report this issue to the community - updatescript said...

(update 7.04 to 8.00, Ubuntu-Server 12.04)

### Steps to reproduce
1. Update per setup-owncloud.php
2. update per commandline php
3. 

### Expected behaviour

updgrade

### Actual behaviour

error

### Server configuration
**Operating system**:
Ubuntu Linux 12.04.5
Linux 2.6.32-042stab093.4 auf x86_64
**Web server:**

lighttpd 1.7

**Database:**

mysql (5.5.41-0ubuntu0.12.04.1)

**PHP version:**

PHP Version	5.5.20-1+deb.sury.org~precise+1

**ownCloud version:** (see ownCloud admin page)

7.0.4 -> 8.0.0

**Updated from an older ownCloud or fresh install:**

fresh per setup-owncloud.php

**List of activated apps:**

	chat	enabled	yes
	mail	enabled	yes
	maps	enabled	yes
	news	enabled	yes
	files	enabled	yes
	music	enabled	yes
	notes	enabled	yes
	tasks	enabled	no
	shorty	enabled	yes
	gallery	enabled	yes
	imprint	enabled	yes
	updater	enabled	yes
	calendar	enabled	yes
	contacts	enabled	yes
	bookmarks	enabled	yes
	documents	enabled	yes
	roundcube	enabled	yes
	user_ldap	enabled	no
	ocDashboard	enabled	yes
	files_sharing	enabled	yes
	files_external	enabled	yes
	files_trashbin	enabled	yes
	files_versions	enabled	yes
	shorty_tracking	enabled	yes 

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'oc06900bc0d6',
  'passwordsalt' => '53924ddc5281d20b8facecd0d631aa',
  'trusted_domains' => 
  array (
    0 => 'infologie.de',
    1 => 'infologie.de',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.4.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpname' => '',
  'mail_smtppassword' => '',
  'forcessl' => true,
  'mail_smtpauthtype' => 'PLAIN',
  'mail_smtpauth' => true,
  'mail_smtpsecure' => 'tls',
  'mail_smtphost' => 'posteo.de',
  'mail_smtpport' => '587',
  'ldapIgnoreNamingRules' => false,
  'theme' => '',
  'maintenance' => false,
  'overwritewebroot' => '/owncloud',
  'secret' => '',
);

```

**Are you using external storage, if yes which one:** 

local/smb/sftp/dropbox

**Are you using encryption:** 
no

### Client configuration

Browser Information

Refered From: http://www.whatsmyip.org/
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.89 Vivaldi/1.0.94.2 Safari/537.36
Screen Resolution: 1600 x 900 (pixels)
Browser Dimensions: 1602 x 784 (pixels)
Cookie Status: Enabled
Cookies (Only Cookies Visible to WhatsMyIP.org): none
Browser Plugins: 
Chrome PDF Viewer (pdf.dll)
QuickTime Plug-in 7.7.6 (npqtplugin.dll)
QuickTime Plug-in 7.7.6 (npqtplugin2.dll)
QuickTime Plug-in 7.7.6 (npqtplugin3.dll)
QuickTime Plug-in 7.7.6 (npqtplugin4.dll)
QuickTime Plug-in 7.7.6 (npqtplugin5.dll)
Microsoft Office 2013 (NPSPWRAP.DLL)
AmazonMP3DownloaderPlugin (npAmazonMP3DownloaderPlugin1017325.dll)
Google Earth Plugin (npgeplugin.dll)
Google Update (npGoogleUpdate3.dll)
Java Deployment Toolkit 8.0.310.13 (npDeployJava1.dll)
Java(TM) Platform SE 8 U31 (npjp2.dll)
Microsoft Office 2013 (npmeetingjoinpluginoc.dll)
Nokia Suite Enabler Plugin (npNokiaSuiteEnabler.dll)
Skype Web Plugin (npSkypeWebPlugin.dll)
VLC Web Plugin (npvlc.dll)
iTunes Application Detector (npitunes.dll)
Flatcast Viewer Plugin 5.3.0.784 (NpFv530.dll)
Shockwave Flash (NPSWF32_16_0_0_305.dll)
Windows Activation Technologies (npWatWeb.dll)

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
{"app":"PHP","message":"Call to undefined method OC\\Server::getSystemConfig() at \/var\/www\/owncloud\/status.php#28","level":3,"time":"2015-02-18T09:11:26+00:00"}
{"app":"PHP","message":"Undefined variable: OC_Edition at \/var\/www\/owncloud\/lib\/private\/util.php#316","level":3,"time":"2015-02-18T09:11:58+00:00"}
{"app":"PHP","message":"Call to undefined method OC\\Server::getSystemConfig() at \/var\/www\/owncloud\/status.php#28","level":3,"time":"2015-02-18T09:11:58+00:00"}
{"app":"PHP","message":"Undefined variable: OC_Edition at \/var\/www\/owncloud\/lib\/private\/util.php#316","level":3,"time":"2015-02-18T09:12:30+00:00"}
{"app":"PHP","message":"Call to undefined method OC\\Server::getSystemConfig() at \/var\/www\/owncloud\/status.php#28","level":3,"time":"2015-02-18T09:12:30+00:00"}
{"app":"PHP","message":"Undefined variable: OC_Edition at \/var\/www\/owncloud\/lib\/private\/util.php#316","level":3,"time":"2015-02-18T09:12:32+00:00"}
{"app":"PHP","message":"Undefined variable: OC_Edition at \/var\/www\/owncloud\/lib\/private\/util.php#316","level":3,"time":"2015-02-18T09:13:02+00:00"}
{"app":"PHP","message":"Call to undefined method OC\\Server::getSystemConfig() at \/var\/www\/owncloud\/status.php#28","level":3,"time":"2015-02-18T09:13:02+00:00"}
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
I shall report this issue to the community - updatescript said...

(update 7.04 to 8.00, Ubuntu-Server 12.04)

### Steps to reproduce
1. Update per setup-owncloud.php
2. update per commandline php
3. 

### Expected behaviour

updgrade

### Actual behaviour

error

### Server configuration
**Operating system**:
Ubuntu Linux 12.04.5
Linux 2.6.32-042stab093.4 auf x86_64
**Web server:**

lighttpd 1.7

**Database:**

mysql (5.5.41-0ubuntu0.12.04.1)

**PHP version:**

PHP Version	5.5.20-1+deb.sury.org~precise+1

**ownCloud version:** (see ownCloud admin page)

7.0.4 -> 8.0.0

**Updated from an older ownCloud or fresh install:**

fresh per setup-owncloud.php

**List of activated apps:**

	chat	enabled	yes
	mail	enabled	yes
	maps	enabled	yes
	news	enabled	yes
	files	enabled	yes
	music	enabled	yes
	notes	enabled	yes
	tasks	enabled	no
	shorty	enabled	yes
	gallery	enabled	yes
	imprint	enabled	yes
	updater	enabled	yes
	calendar	enabled	yes
	contacts	enabled	yes
	bookmarks	enabled	yes
	documents	enabled	yes
	roundcube	enabled	yes
	user_ldap	enabled	no
	ocDashboard	enabled	yes
	files_sharing	enabled	yes
	files_external	enabled	yes
	files_trashbin	enabled	yes
	files_versions	enabled	yes
	shorty_tracking	enabled	yes 

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'oc06900bc0d6',
  'passwordsalt' => '53924ddc5281d20b8facecd0d631aa',
  'trusted_domains' => 
  array (
    0 => 'infologie.de',
    1 => 'infologie.de',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.4.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpname' => '',
  'mail_smtppassword' => '',
  'forcessl' => true,
  'mail_smtpauthtype' => 'PLAIN',
  'mail_smtpauth' => true,
  'mail_smtpsecure' => 'tls',
  'mail_smtphost' => 'posteo.de',
  'mail_smtpport' => '587',
  'ldapIgnoreNamingRules' => false,
  'theme' => '',
  'maintenance' => false,
  'overwritewebroot' => '/owncloud',
  'secret' => '',
);

```

**Are you using external storage, if yes which one:** 

local/smb/sftp/dropbox

**Are you using encryption:** 
no

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
{"app":"PHP","message":"Call to undefined method OC\\Server::getSystemConfig() at \/var\/www\/owncloud\/status.php#28","level":3,"time":"2015-02-18T09:11:26+00:00"}
{"app":"PHP","message":"Undefined variable: OC_Edition at \/var\/www\/owncloud\/lib\/private\/util.php#316","level":3,"time":"2015-02-18T09:11:58+00:00"}
{"app":"PHP","message":"Call to undefined method OC\\Server::getSystemConfig() at \/var\/www\/owncloud\/status.php#28","level":3,"time":"2015-02-18T09:11:58+00:00"}
{"app":"PHP","message":"Undefined variable: OC_Edition at \/var\/www\/owncloud\/lib\/private\/util.php#316","level":3,"time":"2015-02-18T09:12:30+00:00"}
{"app":"PHP","message":"Call to undefined method OC\\Server::getSystemConfig() at \/var\/www\/owncloud\/status.php#28","level":3,"time":"2015-02-18T09:12:30+00:00"}
{"app":"PHP","message":"Undefined variable: OC_Edition at \/var\/www\/owncloud\/lib\/private\/util.php#316","level":3,"time":"2015-02-18T09:12:32+00:00"}
{"app":"PHP","message":"Undefined variable: OC_Edition at \/var\/www\/owncloud\/lib\/private\/util.php#316","level":3,"time":"2015-02-18T09:13:02+00:00"}
{"app":"PHP","message":"Call to undefined method OC\\Server::getSystemConfig() at \/var\/www\/owncloud\/status.php#28","level":3,"time":"2015-02-18T09:13:02+00:00"}
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by RealRancor** [comment]
Hi,

please use the issue template provided here:

https://raw.github.com/owncloud/core/master/issue_template.md

as asked in the "guidelines for contributing" (shown in the yellow box when creating a new issue).

Currently this issue contains too few informations about your problem.

**Comment by nocard** [comment]
A lot of questions for a litle problem....

**Comment by RealRancor** [comment]
Hi,

> Update per setup-owncloud.php

this is an installer and not an updater. Please do the manual upgrade as described here:

http://doc.owncloud.org/server/8.0/admin_manual/maintenance/upgrade.html

and especially note the deletion of all files and folders except /config/ and /data/

**Comment by LukasReschke** [comment]
https://github.com/owncloud/administration/pull/11 would fix that
