### ISSUE TITLE
OC search getHandler called with undefined variable

### ISSUE THREAD

**Issue by raimund-schluessler** [owncloud/core#14310]
In https://github.com/owncloud/core/blob/master/core/search/js/search.js#L340 ```getHandler(item.type)($row, result, event)``` is called with the undefined variable ```result``` instead of the correct one ```item```. This prevents using the search result in the handler function.

Will create a PR soon.

@butonic @MorrisJobke

**Comment by DeepDiver1975** [comment]
will be fixed in 8.1

**Comment by DeepDiver1975** [comment]
relevant for 8.0.1?

@karlitschek

**Comment by karlitschek** [comment]
yes please backport

**Comment by MorrisJobke** [comment]
I will create the backport PR

**Comment by MorrisJobke** [comment]
#14382

**Comment by butonic** [comment]
@raimund-schluessler thx for fixing this. If you are interested in search related topics I can add you to @owncloud/search.

**Comment by raimund-schluessler** [comment]
@butonic No problem, noticed it while implementing the global search for the tasks app https://github.com/owncloud/tasks/issues/120.
You could add me to @owncloud/search and maybe also have a look at https://github.com/owncloud/core/pull/13969 ;)
