### ISSUE TITLE
Add script to convert PHP format translations to JS/JSON format

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#14319]
Some app devs aren't using transifex so they aren't using the translation script that auto-generates JS/JSON.

We should provide a script that converts the translations one time.

Not sure if that should be a PHP script in core or part of ocdev.

@Raydiation @DeepDiver1975 what do you think ?

**Comment by DeepDiver1975** [comment]
```sh
$ ./occ l10n:createjs chat

**Comment by arnovr** [comment]
Confirmed, worked like a charm
