### ISSUE TITLE
Unable to start server from master or stable8

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#14318]
### Steps to reproduce

1. Install owncloud server 
2. Start server using autoconfig.php

When starting server directly via the browser, I get a white screen so I'm assuming the issue is the same regardless of how the server is being started.

### Expected behaviour

Server starts successfully

### Actual behaviour

Server startup fails with:

```

PHP Fatal error:  Class 'OC_Request' not found in /var/www/html/owncloud/apps/firewall/lib/rules.php on line 87
PHP Stack trace:
PHP   1. {main}() /var/www/html/owncloud/occ:0
PHP   2. require_once() /var/www/html/owncloud/occ:11
PHP   3. OC_App::loadApps() /var/www/html/owncloud/console.php:47
PHP   4. OC_App::loadApp() /var/www/html/owncloud/lib/private/app.php:76
PHP   5. OC_App::requireAppFile() /var/www/html/owncloud/lib/private/app.php:97
PHP   6. require_once() /var/www/html/owncloud/lib/private/app.php:116
PHP   7. OCA\Firewall\AppInfo\Application->boot() /var/www/html/owncloud/apps/firewall/appinfo/app.php:27
PHP   8. OCA\Firewall\AppInfo\Application->startFirewall() /var/www/html/owncloud/apps/firewall/appinfo/application.php:61
PHP   9. OCA\Firewall\Rules->__construct() /var/www/html/owncloud/apps/firewall/appinfo/application.php:92
PHP  10. OCA\Firewall\Rules->getCriteria() /var/www/html/owncloud/apps/firewall/lib/rules.php:69
Error during standup of ownCloud server
Fatal error occured when invoking occ

```

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration

Installing using:

http://download.owncloud.org/community/owncloud-daily-master.tar.bz2
http://download.owncloud.com/internal/owncloud-daily-enterprise-master.tar.bz2

I also tried

http://download.owncloud.org/community/owncloud-daily-master.tar.bz2
http://download.owncloud.com/internal/owncloud-daily-enterprise-stable8.tar.bz2

and get the same error

**Comment by DeepDiver1975** [comment]
issue in the fire wall app
