### ISSUE TITLE
impossible browse apps/files: garbled

### ISSUE THREAD

**Issue by yeupou** [owncloud/core#14328]
Since a few versions (current: debian 7.0.4+dfsg-2), it's impossible for me to use apps/files. First I thought it was a temporary issue but it's stays over upgrades

That's with firefox/iceweasel. You can see the first line is not readable and the rest is confusing (folder image repeated):
![capture d ecran2](https://cloud.githubusercontent.com/assets/1160681/6247443/f273b798-b774-11e4-8a43-1f3f9f176b31.png)

Still with firefox/iceweasel. That's what happen when there is actually one line. Unusable. Note also the message about a file I'd be trying to upload, while I'm not uploading anything.
![capture d ecran3](https://cloud.githubusercontent.com/assets/1160681/6247457/16eef128-b775-11e4-97df-4cd09689334a.png)

That's with Konqueror.  Here, the list of files is way under, you need to scroll down. It's slightly better since ou can actually use the download and share links but you still get the folder image repeated
![capture d ecran4](https://cloud.githubusercontent.com/assets/1160681/6247476/43329f8c-b775-11e4-923e-8308e362f4dc.png)

Still with Konqueror. Only one file, with a dark colored image it really looks bad.
![capture d ecran5](https://cloud.githubusercontent.com/assets/1160681/6247496/723760c4-b775-11e4-87c2-15ff0a6be616.png)

What did I miss?

**Comment by LukasReschke** [comment]
> What did I miss?

20 Cent on you did not update properly. Please update the  `.htaccess` file as well or update to 8.0.0 which will show you a big warning if you do it wrong.

**Comment by RealRancor** [comment]
And if you're on NginX make sure that you're using the NginX config provided here:

http://doc.owncloud.org/server/7.0/admin_manual/installation/nginx_configuration.html

**Comment by yeupou** [comment]
Ok, that fixed it.

For the record, it failed after a regular debian upgrade with no warning about anything whatsoever and no change at all in the conffiles.

**Comment by RealRancor** [comment]
Hi,

as you're running the package from Debian (7.0.4+dfsg-2) which is not maintained by ownCloud you could report this problem to the debian bugtracker.

**Comment by yeupou** [comment]
Problem is this package only provides apache conf, not nginx. Hence the no warning at all. I do hope in the future there wont be too many changes that requires to actually changes the server setup.
Anyway, thanks for the help.

**Comment by RealRancor** [comment]
Mhhh, maybe you can request that a note about checking the NginX config is added to the documentation:

https://github.com/owncloud/documentation/issues
