### ISSUE TITLE
Installation from a different domain to localhost shows untrusted domain page instead of installation page

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#14321]
### Steps to reproduce

Having prepared a fresh owncloud from tarball:

1. Access to owncloud from a domain different to localhost.

### Expected behaviour
Owncloud installation page.

![screen shot 2015-02-18 at 10 34 31](https://cloud.githubusercontent.com/assets/9048796/6244942/c4780c10-b759-11e4-8b45-8386833c36be.png)

### Actual behaviour
Untrusted domain page happens.

![screen shot 2015-02-18 at 10 28 23](https://cloud.githubusercontent.com/assets/9048796/6244929/9d3db5c8-b759-11e4-8675-9c34b07cc3f5.png)

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
"version":"8.0.0.9,"versionstring":"8.0","edition":"Community"

**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
none

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** no

### Client configuration
Chrome, Firefox.

**Comment by SergioBertolinSG** [comment]
Note that previously this could be done without problems, and a new owncloud could be configured from an external ip.

**Comment by RealRancor** [comment]
Hi,

are you sure that you don't have an already configured config/config.php with the trusted_domains setting pointed to localhost?

**Comment by SergioBertolinSG** [comment]
No, it is a totally fresh installation in a new folder.

**Comment by LukasReschke** [comment]
Also mine.

**Comment by SergioBertolinSG** [comment]
Fixed in #14324
