### ISSUE TITLE
Large File (>2 GB) Upload & Sync both fail on full 64 bit System

### ISSUE THREAD

**Issue by usrbin123** [owncloud/core#14322]
System: Owncloud 7.0.2. on a Hetzner Managed Server MX90 running Debian (completely 64bit).
No mods on the Owncloud itself, just a few apps.

When uploading files larger than 2GB (with WebDav) or synchronizing them with the Desktop Client (Mac OS X v 1.7.1 build 1655) I get those errors:

WebDAV: Error Code -8084 on OS X 10.10.
Desktop Client: no error code, states correct upload.
And the PHP Log file gives NO error at all.

When using the desktop client, the website shows the files with (in this case) 4.3 GB as it should be, but when I copy the files or download it again, the file is corrupted and never reaches the "full size".
Using WebDAV for Download, the OS X Finder says "error -36", a download is not even possible.

I expected a 32/64 bit problem, but the system simply is not a 32 bit system - and no windows / IIS as well.

Client Log says:
17:45 Local File Changed during Sync
19:03 Operation Timed Out
19:23 Uploaded

The file is shown both in WebDAV/Web Frontend/Local Sync-Folder with the correct size, but downloading it on another client always fails.

I am not sure if this is a Client problem or a core problem, but as there seem to be errors with WebDAV as well, I posted it here.

I am not 100% sure, if my internet-connection was 100% stable (upload of 4.3 GB takes some more minutes) , but it shouldn't be a problem for the client to resume sync after the disconnection.

If you need any more logs, let me know. Thanks for your help!

**Comment by RealRancor** [comment]
Hi,

not sure but this changelog entry of PHP 5.6.0 could be related to your problem:

> Uploads equal or greater than 2GB in size are now accepted.
http://php.net/ChangeLog-5.php#5.6.0

Also have a look at this links for some more infos:
http://forum.owncloud.org/viewtopic.php?f=17&t=7733
http://doc.owncloud.org/server/7.0/admin_manual/configuration/big_file_upload_configuration.html

> System: Owncloud 7.0.2
Also consider to upgrade to the latest OC7 stable 7.0.4

**Comment by usrbin123** [comment]
Hi @RealRancor 

> Uploads equal or greater than 2GB in size are now accepted.
> http://php.net/ChangeLog-5.php#5.6.0

My hoster (www.hetzner.de) does not provide PHP 5.6.0 but I will try asking them. Never though, they've set the vmsize from 500MB to 1GB but the error is still there.

> Also have a look at this links for some more infos:
> http://forum.owncloud.org/viewtopic.php?f=17&t=7733
> http://doc.owncloud.org/server/7.0/admin_manual/configuration/big_file_upload_configuration.html

I followed all the steps already, and can confirm, that the PHP configuration seems to be correct, or at least as the forum link describes.

> System: Owncloud 7.0.2
> Also consider to upgrade to the latest OC7 stable 7.0.4

I will do so tomorrow morning, as Owncloud is not upgrading automatically and I have traffic on the system right now.

For better handling, I filled out the form.
Could it be a problem with the server's infrastructure / CPU power / memory instead of a client or core issue ?

### Steps to reproduce
1. Install Desktop Client, Sync with ownCloud
2. Copy 4.6 GB .mov-Videofile into local ownCloud directory
3. Client syncs

### Expected behaviour
The file should be uploaded correctly. It should be available through Website, WebDAV, and Desktop Sync Client.

### Actual behaviour
The file is uploaded to the server, no error is shown. 
Using WebDAV, FTP or the Website the file is shown with its original size of 4.6 GB in the folder, where it has been synced to.

When downloading the file with **Chrome**, **Firefox** or **Safari** (no other tested), the download stops at various file sizes. Just tested and it stopped at 2.43 GB and 2.34 GB.

Using **WebDAV** the file is shown with 4.6 GB as well. A download / copy though is not possible. 
*(german)*
```Der Vorgang konnte nicht abgeschlossen werden, da ein unbekannter Fehler aufgetreten ist (Fehler -8084).```
*english translation (probably inaccurate):*
```The operation could not be completed because an unknown error occurred. (Error -8084).```

Using **FTP**, the file is shown with 4.6 GB as well. A download though does not start, Cyberduck (on Mac OS X) won’t start the transfer.

### Server configuration
**Operating system**: Linux # 1 SMP Debian 3.2.65-1+deb7u1

**Machine Type:** x86_64

**vmsize:** 1GB

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.5.21
**PHP Integer Size:** 64 bits

**php_value upload_max_filesize:** 16G
**php_value post_max_size:** 16G

**ownCloud version:** 7.0.2 (stable)
**Desktop Client Version:** 1.7.1 (built 1655)

**Updated from an older ownCloud or fresh install:** Fresh Install

**List of activated apps:** 
- Files Move 0.7.2
- Dashboard 1.3.1
- Superlog 0.6.0

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'trusted_domains' => 
  array (
    0 => ‚DOMAIN.com‘,
    1 => 'www.DOMAIN.com',
  ),
  'datadirectory' => '/usr/www/users/dquolw/cloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.2.1',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_domain' => ‚DOMAIN.com',
  'mail_from_address' => 'cloud',
  'mail_smtpsecure' => 'tls',
  'mail_smtpauth' => true,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => ‚HOST‘,
  'mail_smtpport' => '587',
  'mail_smtppassword' => '',
  'mail_smtpname' => 'cloud@DOMAIN.com',
  'forcessl' => true,
  'loglevel' => '0',
);

```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

### Client configuration
**Browser:**
Google Chrome Version 41.0.2272.63 beta (64-bit)

**Operating system:**
Mac OS X 10.10.2

### Logs
#### Web server error log
```
No entries
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"54e64a83cd4f2","app":"OC\\Files\\Cache\\Scanner","message":"!!! No reuse of etag for 'files\/PATH\/FILENAME.mov' !!! \ncache: Array\n(\n    [fileid] => 225782\n    [storage] => home::USERNAME\n    [path] => files\/PATH\/FILENAME.mov\n    [parent] => 225780\n    [name] => FILENAME.mov\n    [mimetype] => video\/quicktime\n    [mimepart] => video\n    [size] => 4569357622\n    [mtime] => 1424378491\n    [storage_mtime] => 1424378491\n    [encrypted] => \n    [unencrypted_size] => 0\n    [etag] => 54e64a83ccb57\n    [permissions] => 27\n)\n \ndata: Array\n(\n    [mimetype] => video\/quicktime\n    [mtime] => 1423566854\n    [size] => 4569357622\n    [etag] => 54e64a83cd0fb\n    [storage_mtime] => 1423566854\n    [permissions] => 27\n    [parent] => 225780\n)\n","level":0,"time":"2015-02-19T20:41:39+00:00","method":"PUT","url":"\/cloud\/remote.php\/webdav\/PATH\/FILENAME.mov-chunking-3908286163-218-217"}
{"reqId":"54e64a941fe37","app":"webdav","message":"Sabre\\DAV\\Exception\\NotAuthenticated: No basic authentication headers were found","level":0,"time":"2015-02-19T20:41:56+00:00","method":"PROPFIND","url":"\/cloud\/remote.php\/webdav\/"}
{"reqId":"54e64d5321ca1","app":"webdav","message":"Sabre\\DAV\\Exception\\NotAuthenticated: No basic authentication headers were found","level":0,"time":"2015-02-19T20:53:39+00:00","method":"PROPFIND","url":"\/cloud\/remote.php\/webdav\/"}
```

#### Client log
```
21:41     PATH/FILENAME.mov	ownCloud 	Uploaded    4,3 GB    
20:21     PATH/FILENAME.mov	ownCloud 	A local file has been changed during sync.        
20:21     PATH/FILENAME.mov	ownCloud 	A local file has been changed during sync.         
20:21     PATH/FILENAME.mov	ownCloud 	A local file has been changed during sync.       
20:21     PATH/FILENAME.mov	ownCloud 	A local file has been changed during sync.      
```

#### PHP Error log
```
No entries   
```

**Comment by usrbin123** [comment]
I am thinking, it may be not a problem with sync or upload, but with the download ?
#8575 sounds pretty much like my problem, except for that **WebDAV**, **FTP** and **Browser** are affected.

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by usrbin123** [comment]
Found this issue as well on OC 8 - #14100 
@PVince81 - did you get into this problem ?
@RealRancor - could the output_buffering be the problem here as well ?

**Comment by elessard84** [comment]
(sorry if my english is not so good)
I have the  same isssue exept with a diferente configuration.
I host my own server
OC 8.0
php 5.6.6 (tried 5.5 too same issue) x64
IIS 7.5 (on windows 7 x64)
But I have a wierd looking message in my log:
Error 	PHP 	file_put_contents(): content truncated from 2367291392 to 2147483647 bytes at C:\inetpub\wwwroot\3rdparty\sabre\dav\lib\Sabre\HTTP\Response.php#164 	2015-03-06T04:52:12+00:00 
But my error log can maybe help solve your problem. It point to Response.php Something in there should use 64 bit operation but use 32 bit....

**Comment by RealRancor** [comment]
@elessard84 
It is known that PHP on Windows doesn't support files larger then 2GB. See the last box on the left on:

http://windows.php.net/download#php-5.6

**Comment by elessard84** [comment]
@RealRancor 
Thanks!!! I can stop searching now and get some sleep. I can't believe I seached 3 days and didn't see that.

**Comment by RealRancor** [comment]
@elessard84 Ist now also documented in https://doc.owncloud.org/server/8.0/admin_manual/configuration_files/big_file_upload_configuration.html

But you still should be able to use the sync client to upload such large files at it will upload the large file in smaller chunks.

**Comment by elessard84** [comment]
@RealRancor 
Owncloud don't seen to upload large file that way; I have the same size limitation with the sync client. The fact taht the client use the same port as the web interface let me think that even the the sync with the client is PHP driven on the server side. I think I will just wait for PHP for windows with large file support and for now rely on ftp for larger file. That not an elegant solution but that work.... 

Thank you again for your help :)

**Comment by shoeper** [comment]
It is statet like that in the link from RealRancor.

> The x64 builds of PHP for Windows should be considered experimental, and do not yet provide 64-bit integer or large file support. - http://windows.php.net/download#php-5.6

I think large file support is not limited to uploads.

**Comment by usrbin123** [comment]
@shoeper 
This only applies to @elessard84 's Problem, as I am running a 64-bit Linux.

**Comment by shoeper** [comment]
Could be a php5.5 error. Did you try 5.6?
Have you set max input time and other timeouts to appropriate values?

**Comment by shoeper** [comment]
http://php.net/manual/de/migration56.new-features.php -> large file uploads

**Comment by usrbin123** [comment]
Yes, I have set the .htaccess to the following:

php_value upload_max_filesize 16G
php_value post_max_size 16G
php_value memory_limit 1G
php_value mbstring.func_overload 0
php_value max_input_time 3600
php_value max_execution_time 3600

Ain't this enough ?

Regarding the new PHP 5.6 Features: This would mean, that OC has never been able to handle files larger than 2 GB before PHP 5.6 came out, right ? But this doesn't make any sense...

**Comment by shoeper** [comment]
And what are your webserver timeouts?

Why wouldn't that make sense?
The client bypasses this by using chunks anyway.

**Comment by RealRancor** [comment]
@usrbin123 
There could be also more limitations on webserver level not only PHP. Have a look at:

https://doc.owncloud.org/server/8.0/admin_manual/configuration_files/big_file_upload_configuration.html#configuring-your-webserver

**Comment by bantu** [comment]
@PVince81 "large file uploads" refers to POSTing files larger than 2 GiB. See http://cweiske.de/tagebuch/php-large-file-uploads.htm.

**Comment by usrbin123** [comment]
@shoeper Any method of uploading fails, also with chunking/the client, FTP and WebDAV. 
And if this was a PHP fault (before 5.6), there should be much more users having the problem. That why I said, it doesn't make sense.

I am checking with the support again for more limitations on webserver's side.

**Comment by bantu** [comment]
@usrbin123 #11270 is different as it is 32-bit.

**Comment by bantu** [comment]
@usrbin123 Can you download a large file onto your VM and share that publicly with me. E.g. a debian DVD image?

**Comment by bantu** [comment]
Let's get the download issue addressed first. It might be the same as your upload issue.

**Comment by shoeper** [comment]
Btw. did you have a look via ssh if the file is there and has the right checksum?

**Comment by usrbin123** [comment]
@shoeper thanks for this hint. Didn't come to my mind before to check it.
Both md5-checksums are the same, so file is not corrupted on the server. Seems like the upload is fine, at least with the client (when chunks are used).
@bantu - Shall I post the public link here ? Or PM you ?

**Comment by bantu** [comment]
@usrbin123 As you like.

**Comment by usrbin123** [comment]
PM is disabled .. did not know that.

File: debian-7.8.0-amd64-DVD-2.iso
Download: http://bit.ly/1Hn97z9
MD5: 4172cb3f8d3dfd8bf0f09834719b75ee 
(check http://cdimage.debian.org/debian-cd/7.8.0/amd64/iso-dvd/MD5SUMS)

MD5 is correct - again. Download fails at 2.14 GB (at first try).

**Comment by bantu** [comment]
@usrbin123 Did you measure the time it takes until you run into problems? Possibly an hour and you're running into `max_execution_time 3600` ?

**Comment by bantu** [comment]
HTTP download works for me as per the following:
```
wget -S https://polytope-artists.com/cloud/public.php?service=files\&t=e15580933f517312240f16aa40b77cd8\&download -O - | md5sum -b--2015-03-09 15:32:03--  https://polytope-artists.com/cloud/public.php?service=files&t=e15580933f517312240f16aa40b77cd8&download
Resolving polytope-artists.com (polytope-artists.com)... 78.46.139.231
Connecting to polytope-artists.com (polytope-artists.com)|78.46.139.231|:443... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 200 OK
  Date: Mon, 09 Mar 2015 15:32:07 GMT
  Server: Apache
  Strict-Transport-Security: max-age=31536000
  X-XSS-Protection: 1; mode=block
  X-Content-Type-Options: nosniff
  X-Frame-Options: Sameorigin
  Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *
  X-Robots-Tag: none
  Content-Disposition: attachment; filename*=UTF-8''debian-7.8.0-amd64-DVD-2.iso; filename="debian-7.8.0-amd64-DVD-2.iso"
  Content-Transfer-Encoding: binary
  Pragma: public
  Expires: 0
  Cache-Control: must-revalidate, post-check=0, pre-check=0
  Set-Cookie: oc15c91e6dc6=631a931e13187aecdf31c2db2711b945; path=/cloud; HttpOnly
  Content-Length: 4700016640
  Keep-Alive: timeout=15, max=100
  Connection: Keep-Alive
  Content-Type: application/octet-stream
Length: 4700016640 (4.4G) [application/octet-stream]
Saving to: ‘STDOUT’

100%[==========================================================================================================>] 4,700,016,640 40.9MB/s   in 90s    

2015-03-09 15:33:33 (49.9 MB/s) - written to stdout [4700016640/4700016640]

4172cb3f8d3dfd8bf0f09834719b75ee *-
```

I ran this a few times. Note, this is all Hetzner-internal traffic.

**Comment by bantu** [comment]
2.14 GiB/hour = (2.14×8×1024^3)÷(3600×1000^2) MBit/s = 5.11 Mbit/s

**Comment by bantu** [comment]
For the record: The FTP protocol might have its own share of large file problems. The SFTP and rsync protocols are much more reliable.

**Comment by usrbin123** [comment]
@bantu I have an approximate downstream of 45.000 kbit/s. The 4.7 GB file should be downloaded in 20 Minutes. Shall I run another download as a test ?  Do you expect the timeout to cause the error ?

I used Chrome, Firefox and Safari on Mac OS X as well as Firefox and Chrome on Windows to reproduce the error. Using the web interface should work be default.

By the way: It is getting a little difficult for me to understand what's going on, as I am not a pro and am not very good with Terminal / Console.

**Comment by bantu** [comment]
@usrbin123 Does it take longer than an hour or not until it fails for you?

**Comment by usrbin123** [comment]
@bantu This morning it failed after approx. 10 minutes. I handed in a support enquiry to Hetzner this morning and I just got feedback.

*German*
```Wir haben nun einige zusätzliche Tests durchgeführt und sind dabei einmal in einen Timeout des Webservers gelaufen - wir haben die relevanten Webserver Timeouts nun deutlich erhöht, ein Download Ihrer ISO-Datei war damit möglich.
Bitte prüfen Sie, ob damit das Problem behoben wurde.```

*English*
```We have now carried out some additional tests and ran in a webserver timeout once - we have increased the relevant web server timeouts considerably, so that a download of your ISO file was possible.```

Now the download was succesfull at first try. I will let my colleague download the "real" files asap and check if the error still exists. Thanks for all your help so far. 

For the record: This seems to be a problem with Webserver Timeouts.

**Comment by bantu** [comment]
@usrbin123 All right, I am closing this as such.
