### ISSUE TITLE
rejected HELO with syntactically invalid argument(s): ~^wildcard

### ISSUE THREAD

**Issue by yeupou** [owncloud/core#14327]
Hello,

I'm using owncloud as shipped by debian (7.0.4+dfsg-2) along with exim and nginx.

The nginx server name is configured by a wildcard as allowed by http://nginx.org/en/docs/http/server_names.html
When I'm setting owncloud to use smtp to send mail, it get rejected by exim. In the logs shows up
```
2015-02-18 13:25:30 rejected HELO from localhost [127.0.0.1]: syntactically invalid argument(s): ~^wildcard
```

I found no info in the docs ( http://doc.owncloud.org/server/7.0/admin_manual/configuration/configuration_mail.html ) about changing this helo. 

I guess owncloud should not use server name but the domain (which must be checked somewhere, at least due to trusted_domains setting) as helo since server name can be wildcards that won't be accepted by smtp.

**Comment by DeepDiver1975** [comment]
@nickvergessen can you please have a look at the smtp mailer code what is used in the helo command? THX

**Comment by nickvergessen** [comment]
when Helo is not set explicit on PHPMailer, it falls back to
```php
    protected function serverHostname()
    {
        $result = 'localhost.localdomain';
        if (!empty($this->Hostname)) {
            $result = $this->Hostname;
        } elseif (isset($_SERVER) and array_key_exists('SERVER_NAME', $_SERVER) and !empty($_SERVER['SERVER_NAME'])) {
            $result = $_SERVER['SERVER_NAME'];
        } elseif (function_exists('gethostname') && gethostname() !== false) {
            $result = gethostname();
        } elseif (php_uname('n') !== false) {
            $result = php_uname('n');
        }
        return $result;
    }
```

And we don't set it explicit.

**Comment by DeepDiver1975** [comment]
just another config we need to expose?

@LukasReschke will this be necessary with swift as well?

**Comment by LukasReschke** [comment]
SwiftMailer uses the https://github.com/swiftmailer/swiftmailer/blob/29623072927aa83f371dfa645644ec7a26600e95/lib/classes/Swift/Transport/EsmtpTransport.php#L278 for the EHLO which relies on https://github.com/swiftmailer/swiftmailer/blob/31fcc427630c92e1f74e8a0e5439fc1e868b6765/lib/classes/Swift/Transport/AbstractSmtpTransport.php#L49-L67

Thus per default it uses `127.0.0.1` as domain name in the HELO command, if we don't like that we can also add `setLocalDomain` and pass the domain configured for CLI usage in there.

**Comment by yeupou** [comment]
Hello,

For the record, what's the solution you picked?

**Comment by nickvergessen** [comment]
We replaced the old custom code with swift mailer which uses sensible defaults.
