### ISSUE TITLE
Can't activate any app in owncloud 8

### ISSUE THREAD

**Issue by Metal-Frog** [owncloud/core#14336]
Version 8.0.0.7
PHP-Version 5.6
Patch #14086 applied

Due to provider restrictions I had to comment the line
Options -Indexes
in the .htaccess file.

Any further ideas?

Best regards, Tom

**Comment by nickvergessen** [comment]
:crystal_ball: has no idea.
If you fill out the [issue tempalte](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) we might have enough data to help you.

**Comment by Metal-Frog** [comment]
### Steps to reproduce
1. install owncloud
2. try to activate an app
3.

### Expected behaviour
app remains deactivated

### Actual behaviour
app should be activated

### Server configuration
**Operating system**:
Linux

**Web server:**
Apache

**Database:**
MySQL 5.5

**PHP version:**
5.6.3

**ownCloud version:** (see ownCloud admin page)
8.0.0.7

**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
none

**The content of config/config.php:**
$CONFIG = array (
  'instanceid' => 'oc2flsdy6bi5',
  'passwordsalt' => 'xxxxxxxxxxxx',
  'secret' => 'xxxxxxxxxxxx',
  'trusted_domains' => 
  array (
    0 => 'hva6x.w4yserver.at',
  ),
  'datadirectory' => '/home/.sites/149/site2393825/web/_owncloud/data',
  'overwrite.cli.url' => 'http://hva6x.w4yserver.at/_owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.0.7',
  'installed' => true,
  'dbname' => '2393825db2',
  'dbhost' => 'mysqlsvr42.world4you.com',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'sql2393825',
  'dbpassword' => 'xxxxxxxxxxxx',
  'mail_from_address' => 'webmaster',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'it-ferdinand.de',
  Insert your config.php content here

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

### Client configuration
**Browser:**
IE, Chrome, FireFox

**Operating system:**
Win7 & Win8

### Logs
#### Web server error log
[Tue Feb 17 14:14:53 2015] [error] [client 81.19.145.238] client denied by server configuration: /home/.sites/149/site2393825/web/_owncloud/data/htaccesstest.txt
[Tue Feb 17 14:15:20 2015] [crit] [client 81.19.145.238] (13)Permission denied: /home/.sites/149/site2393825/web/_owncloud/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable

#### ownCloud log (data/owncloud.log)
{"reqId":"fc6c8c4d50a7f73654626b03ab9e62cf","remoteAddr":"194.138.39.61","app":"PHP","message":"file_exists(): open_basedir restriction in effect. File(\/dev\/urandom) is not within the allowed path(s): (\/home\/.sites\/149\/site2393825\/web:\/home\/.sites\/149\/site2393825\/tmp:\/usr\/share\/pear) at \/home\/.sites\/149\/site2393825\/web\/_owncloud\/3rdparty\/ircmaxell\/random-lib\/lib\/RandomLib\/Source\/URandom.php#57","level":3,"time":"2015-02-17T13:14:12+00:00"}

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by andriesinfoserv** [comment]
@Metal-Frog: it may be a good idea to resolve the issues listed in the apache and owncloud logs and see if that fixes your issue. in the web server log, first your htaccess file denied the client then (presumaably after it was modified as you indicate above) apache reports it was unable to read the htaccess file due to permissions. that will "break" stuff.  Also, you may want to list your Linux distribution and version(if applicable) in the future as "Linux" is just the kernel and depending on the issue the distribution info could be valuable.

**Comment by Metal-Frog** [comment]
I'm not sure that I can do anything on that. The owncloud installation is hosted at the provider "world4you". So I can't tell anything aboud the OS.
htaccess files are allowed, but no "option" directions in it.
Besides that the htaccess file in the data directory is successfully reated by owncloud with the following content:
```
# Generated by ownCloud on 2015-02-17 16:26:49
# line below if for Apache 2.4
<ifModule mod_authz_core.c>
Require all denied
</ifModule>

# line below if for Apache 2.2
<ifModule !mod_authz_core.c>
deny from all
</ifModule>

# section for Apache 2.2 and 2.4
IndexIgnore *
```
So could there really be a "breaking" problem?

**Comment by andriesinfoserv** [comment]
the .htaccess for the data directory is probably not relevent for your apps enable issue. I had the same problem as you with apps not enabling, applied the patch and it still didn't work. after fixing more issues with my config, i tried it later and it magically worked. this is why i recommended you try to clean everything up, b/c i was in the same boat. did you add "/dev/urandom" to the open_basedir line in /etc/php/php.ini? I haven't looked at the source, but maybe app install function needs this to work. you may have to ask your host about php.ini. when i used shared hosting they would let you have your own php.ini for any domains and that one would be used.

**Comment by Metal-Frog** [comment]
Is there a way to activate an app manually?

**Comment by DeepDiver1975** [comment]
> Is there a way to activate an app manually?

1. download the zip/tar.gz archives from the appstore 
2. extract them into your apps folder
3. on the apps page the app is listed in 'Not Enabled'
4. click enable :wink:

**Comment by DeepDiver1975** [comment]
We need to enhance appstore feedback/error handling - note to @deepdiver1975

**Comment by Metal-Frog** [comment]
I need to bypass this.
You do know this whole thread is about the problem that activating in the appstore doesn't work :) ?

**Comment by DaDirnbocher** [comment]
@Metal-Frog have a look here: http://wiki.goneo.de/owncloud_install_apps

I think world4you doesn't allow allow_url_fopen.

**Comment by Metal-Frog** [comment]
@DaDirnbocher That's it. Thanks alot. Especially for the tutorial for manual installation!!!

**Comment by tubia** [comment]
I'm experiencing the same behaviour. After enabling an app from the appstore, refreshing the page results in the same app to be still disabled.

**Comment by Tiger862000** [comment]
Hey guys, I am experiencing the same issue. What info needs to be provided in order to solve it?

**Comment by nickvergessen** [comment]
Closing this, if it happens again with 8.0.4+ or 8.1.0+ please create a new issue.
