### ISSUE TITLE
Update gets stuck on update screen

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#14334]
Trying to update to the latest git master, my instance gets stuck in the update screen:

> This ownCloud instance is currently being updated, which may take a while.
etc.

The owncloud.log says this:

```
{"reqId":"+JPFuB+QeiWPgR2xG\/Xv","remoteAddr":"127.0.0.1","app":"memcache","message":"no low latency cache available","level":0,"time":"2015-02-18T13:35:26+00:00","method":"GET","url":"\/owncloud\/"}
{"reqId":"oSZGpavL0X+XS9l\/SEDj","remoteAddr":"127.0.0.1","app":"memcache","message":"no low latency cache available","level":0,"time":"2015-02-18T13:35:26+00:00","method":"GET","url":"\/owncloud\/index.php\/core\/js\/oc.js?v=ab0eb82b58fbf9fbc14191cd0cf575a1"}
{"reqId":"tjYWUn6k4pvDXaQC8Gvq","remoteAddr":"127.0.0.1","app":"memcache","message":"no low latency cache available","level":0,"time":"2015-02-18T13:35:47+00:00","method":"GET","url":"\/owncloud\/status.php"}
```

**Comment by LukasReschke** [comment]
owncloud.log entries are unrelated and will go away with https://github.com/owncloud/core/pull/14330

**Comment by jancborchardt** [comment]
Ok – so what could be the error? Apache error.log or JS log doesn’t say anything either.

**Comment by LukasReschke** [comment]
Could be anything… Where did it stop on the update screen?

**Comment by jancborchardt** [comment]
After clicking the update button, on the page saying this:

```
This ownCloud instance is currently being updated, which may take a while.

This page will refresh itself when the ownCloud instance is available again.

Contact your system administrator if this message persists or appeared unexpectedly.

Thank you for your patience.

```

**Comment by DeepDiver1975** [comment]
> After clicking the update button, on the page saying this:

change maintenance in config.php back to false and retry

**Comment by jancborchardt** [comment]
The message in the update dialog was:
```
Updating ownCloud to version 8.0, this may take a while.

Possible CSRF attack. Connection will be closed.
Please reload the page.
```

After that the message posted in the comment before this appears.

**Comment by LukasReschke** [comment]
Let me see whether I can somehow reproduce this *sigh*

**Comment by jancborchardt** [comment]
And this just busted my newly setup ownCloud dev instance as well …

Removing config.php works, but it seems to come back at will.

**Comment by pelicanmedia** [comment]
Wow this is still an issue ?? https://github.com/owncloud/core/issues/14184

I have fixed by changing `'maintenance' => true,`  to: `'maintenance' => false,` in `config.php` then restarting my webserver (in my case httpd)

**Comment by DeepDiver1975** [comment]
@jancborchardt this issue should no longer apply - please verify and close - THX

**Comment by jancborchardt** [comment]
Yep, haven’t had the issue again. Thanks!
