### ISSUE TITLE
Add test credentials box with WebDAV Authentication configuration

### ISSUE THREAD

**Issue by johanehnberg** [owncloud/core#14333]
As a feature request, next to the WebDAV Authentication address, test credentials that are not saved could be used with a test button to check the function of the address given.

**Comment by MorrisJobke** [comment]
Webdav auth was merged with user_external - https://github.com/owncloud/apps/commit/3076d18aeb1a6871926bac9c2226ab229b5b997e

If the issue still exists please reopen this in the apps bug tracker https://github.com/owncloud/apps/issues

Thanks
