### ISSUE TITLE
IMAP Backend - massiv logins

### ISSUE THREAD

**Issue by chises** [owncloud/core#14339]
I use version OC 8.0.0.7 & 7.0.4.2. 
In both version i use user backend imap.
config:
'user_backends' =>
  array (
    0 =>
    array (
      'class' => 'OC_User_IMAP',
      'arguments' =>
      array (
        0 => '{mailserver:993/imap/ssl/novalidate-cert}INBOX',
      ),
    ),
  ),

I can login successfull and everything is fine. But since 1st sucessfull login my imap server is queried every 5 secounds. Other successfull imap accounts will be send these logins, too.
If i use 10 imap logins every account will query the imap server every 2 secounds.

Nothing is logged in owncloud.log, even with loglevel debug.

Here the mailserver logfile:
/var/log/mail.log
Feb 18 15:35:32 vsrv01 dovecot: imap-login: Login: user=<test@test.de>, method=PLAIN, rip=<IP>, lip=<IP>, mpid=30257, TLS, session=<3fNJu10P6gBOLwmu>
Feb 18 15:35:32 vsrv01 dovecot: imap(test@test.de): Disconnected: Logged out in=15 out=409
Feb 18 15:35:33 vsrv01 dovecot: imap-login: Login: user=<test@test.de>, method=PLAIN, rip=<IP>, lip=<IP>, mpid=30259, TLS, session=<741au10P7ABOLwmu>
Feb 18 15:35:33 vsrv01 dovecot: imap(test@test.de): Disconnected: Logged out in=15 out=409
Feb 18 15:35:33 vsrv01 dovecot: imap-login: Login: user=<test@test.de>, method=PLAIN, rip=<IP>, lip=<IP>, mpid=30261, TLS, session=<LrZbu10P7QBOLwmu>
Feb 18 15:35:33 vsrv01 dovecot: imap(test@test.de): Disconnected: Logged out in=15 out=409
Feb 18 15:35:33 vsrv01 dovecot: imap-login: Login: user=<test@test.de>, method=PLAIN, rip=<IP>, lip=<IP>, mpid=30263, TLS, session=<Pntdu10P7gBOLwmu>
Feb 18 15:35:33 vsrv01 dovecot: imap(test@test.de): Disconnected: Logged out in=15 out=409
Feb 18 15:35:33 vsrv01 dovecot: imap-login: Login: user=<test@test.de>, method=PLAIN, rip=<IP>, lip=<IP>, mpid=30265, TLS, session=<lqReu10P7wBOLwmu>
Feb 18 15:35:33 vsrv01 dovecot: imap(test@test.de): Disconnected: Logged out in=15 out=409
Feb 18 15:35:37 vsrv01 dovecot: imap-login: Login: user=<test@test.de>, method=PLAIN, rip=<IP>, lip=<IP>, mpid=30268, TLS, session=<YqCYu10P8QBOLwmu>
Feb 18 15:35:37 vsrv01 dovecot: imap(test@test.de): Disconnected: Logged out in=15 out=409
Feb 18 15:35:38 vsrv01 dovecot: imap-login: Login: user=<test@test.de>, method=PLAIN, rip=<IP>, lip=<IP>, mpid=30270, TLS, session=<Z2Ctu10P8wBOLwmu>
Feb 18 15:35:38 vsrv01 dovecot: imap(test@test.de): Disconnected: Logged out in=15 out=409

**Comment by DeepDiver1975** [comment]
please reopen this issue in here - https://github.com/owncloud/apps

user_external is maintained in the apps repo - THX
