### ISSUE TITLE
Improve WebDAV Authentication text box

### ISSUE THREAD

**Issue by johanehnberg** [owncloud/core#14331]
The placeholder text of the field, which is now https://example.com/webdav, could be https://owncloud.example.com/remote.php/webdav to promote how to use it with owncloud.

Furthermore, the text box is too small to actually show the full placeholder by default, for me it ends at example.com/. I had to check the page source to see the path.

**Comment by MorrisJobke** [comment]
Webdav auth was merged with user_external - https://github.com/owncloud/apps/commit/3076d18aeb1a6871926bac9c2226ab229b5b997e

If the issue still exists please reopen this in the apps bug tracker https://github.com/owncloud/apps/issues

Thanks
