### ISSUE TITLE
Wrong 'datadirectory' after upgrade to OC 8

### ISSUE THREAD

**Issue by hrzn** [owncloud/core#14337]
After upgrading to OC 8.0.0 (using apt-get dist-upgrade and the web dialog box), all the files have disappeared. They left place to the default "Documents", "Photos" and "ownCloudUserManual.pdf".

However, the files are still stored on the filesystem in /home/owncloud/data/$user/files/, for each $user.

The upgrade seems to have completed successfully:
`www-data$ php console.php upgrade`
`ownCloud is already latest version`

The problem seems to come from the fact that the upgrade to OC 8 set 'datadirectory' to 
'/var/www/owncloud/data' in config.php, whereas the correct configuration in my case is '/home/owncloud/data'.

Setting 'datadirectory' back to the correct path restores the files (and causes the clients to re-download all files again).

* Config: Debian Wheezy, PHP 5.4.36, Apache 2.2.22, MySQL 5.5.41
* The last logs in owncloud.log are older than the update

**Comment by LukasReschke** [comment]
@jnweiger Can this be packaging related?

**Comment by jnweiger** [comment]
@hrzn did you install tar/zip package, or did you install our deb package? (I double checked: all of them only ship a config.sample.php and do not directly overwrite your config.php file.)

The setting  'datadirectory' = '/var/www/owncloud/data' is in the config.sample.php
We need to review how the new sample config merges into the existing config.php -- initialization and/or upgrade code? 

If Debian packaging breaks that code somehow, please let me know.

**Comment by LukasReschke** [comment]
> We need to review how the new sample config merges into the existing config.php -- initialization and/or upgrade code?

Sample config should not get merged at all.

**Comment by hrzn** [comment]
I always used only Debian packages, no tar/zip package. I don't know whether the upgrade caused this line in config.php to change (as I didn't check this line just before the upgrade). However, the upgrade for sure made the files disappear, and changing this line back to 'datadirectory' => '/home/owncloud/data' (along with a "console.php files:scan --all") made them reappear.

**Comment by jnweiger** [comment]
Thanks for confirming the packages.
I don't see code in the packaging logic that would impact your config.php -- may still be packaging related, but I'd say 'unlikely' now.

**Comment by LukasReschke** [comment]
Okay… This could then be a core issue… I just have no idea *HOW* this could happen.

Thanks @jnweiger.

**Comment by PVince81** [comment]
Did only the data directory get reset or other settings too like the instance id and password salt ?
If the latter, it could be the known concurrency issue when reading/writing config.php.

**Comment by hrzn** [comment]
I didn't check the config file before the update so I cannot tell for sure, but I think that only the 'datadirectory' variable was affected. Also I didn't notice any other symptom of other modifications (like credential problems).

**Comment by PVince81** [comment]
Are we sure this isn't a case of upgrading from the Debian repo packages to the OBS repo packages ?
@jnweiger did we ever store the data directory in "/home/owncloud" for Debian ?

**Comment by PVince81** [comment]
> Are we sure this isn't a case of upgrading from the Debian repo packages to the OBS repo packages ?
@hrzn ^

**Comment by blizzz** [comment]
Closing, because of missing info. Possible incompatible package conflict.
