### ISSUE TITLE
installing owncloud using composer

### ISSUE THREAD

**Issue by markuspfeifenberger** [owncloud/core#14343]
We wanted to install the owncloud core using a composer.json file. The composer install works fine, we didn't get the 3rdparty submodules to work. Would it not be a good idea to handle the 3rdparty with composer and not as submodule?

Here is the our composer.json file:
```
{
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "owncloud-core",
                "version": "8.0.0",
                "source": {
                    "url": "https://github.com/owncloud/core.git",
                    "type": "git",
                    "reference": "v8.0.0"
                }
            }
        }
    ],
    "require" : {
      "owncloud-core": "8.0.0"
    }
}
```

**Comment by LukasReschke** [comment]
Let's discuss this stuff at https://github.com/owncloud/core/issues/11973
