### ISSUE TITLE
Changing the Title and footer bar option in admin panel

### ISSUE THREAD

**Issue by biobeo** [owncloud/core#14353]
Every time a new version of owncloud came out, I have to modify the whole script's title and footer bar, 

It would be a lot more easier if I can change the whole thing from the admin panel like WordPress

**Comment by RealRancor** [comment]
Hi,

thats already possible with a new theme using the "defaults.php". Have a look at the forums and search for the keyword "footer" or "title" to find some examples.

**Comment by biobeo** [comment]
So I have to create a new theme for that? why should I create a new theme If I want to use the default theme and want to change the title easily !!

**Comment by LukasReschke** [comment]
Because that's it how it is ;-)

**Comment by LukasReschke** [comment]
(you don't have to create a complete theme - the defaults file is enough)

**Comment by biobeo** [comment]
It's better to have a place holder for title as mentioned here:
https://github.com/owncloud/files_texteditor/issues/49#issuecomment-66595995
