### ISSUE TITLE
Share by link (Link url changes when a folder moved)

### ISSUE THREAD

**Issue by biobeo** [owncloud/core#14354]
I upload movies in my owncloud server and add that with a movie poster in my site by sharing the file with share by link url, But sometimes accidentally when a folder drags on another folder, the folder moves into that folder and all the links which I created stop working. Isn't there anyway to fix or disable it?

**Comment by PVince81** [comment]
Please use the issue template to provide more information about your setup (ex: what ownCloud version you use): https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

Also, what folder are you dragging the shared file in ? Is it a regular folder or another shared folder ?

**Comment by DeepDiver1975** [comment]
no feedback -> close
