### ISSUE TITLE
 Error fetching URL when redirect behind link 

### ISSUE THREAD

**Issue by bong0** [owncloud/core#14358]
The Procedure of adding a file via `New => From link` fails when the content behind the link is a redirect.
I suspect there is also something wrong with handling urls like the one resolved here:
    http://zdf.vo.llnwd.net/e1/s/none/zdf/15/02/150213_hsh_hsh_2256k_p14v11.mp4?rs=1024&ri=10000&ip=174.129.218.229&h=6faa64d87aee182aa303584f570d0d1d
which should be valid but also fails when being added via `New=>From Link`

Example Link: http://nrodl.zdf.de/none/zdf/15/02/150213_hsh_hsh_2256k_p14v11.mp4

Wget for example handles this correctly:

     wget -O/dev/null http://nrodl.zdf.de/none/zdf/15/02/150213_hsh_hsh_2256k_p14v11.mp4
    --2015-02-19 02:16:56--  http://nrodl.zdf.de/none/zdf/15/02/150213_hsh_hsh_2256k_p14v11.mp4
    Resolving nrodl.zdf.de (nrodl.zdf.de)... 217.115.140.11, 178.63.118.91
    Connecting to nrodl.zdf.de (nrodl.zdf.de)|217.115.140.11|:80... connected.
    HTTP request sent, awaiting response... 302 Moved Temporarily
    Location: http://zdf.vo.llnwd.net/e1/s/none/zdf/15/02/150213_hsh_hsh_2256k_p14v11.mp4\?rs\=1024\&ri\=10000\&ip\=REDACTED\&h\=8381dec06e6a75238f3492d2cd17e1f4 [following]
    --2015-02-19 02:16:56--  http://zdf.vo.llnwd.net/e1/s/none/zdf/15/02/150213_hsh_hsh_2256k_p14v11.mp4\?rs\=1024\&ri\=10000\&ip\=REDACTED\&h\=8381dec06e6a75238f3492d2cd17e1f4
    Resolving zdf.vo.llnwd.net (zdf.vo.llnwd.net)... 87.248.221.253, 87.248.221.254
    Connecting to zdf.vo.llnwd.net (zdf.vo.llnwd.net)|87.248.221.253|:80... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 583283164 (556M) [video/mp4]
    Saving to: ‘/dev/null’
    
    /dev/null                 1%[                                 ]   7.35M  5.25MB/s             

Version: ownCloud 7.0.4 (stable)

**Comment by DeepDiver1975** [comment]
the feature new->from link has been removed in 8.1

**Comment by bong0** [comment]
@DeepDiver1975 is there any replacement?

**Comment by DeepDiver1975** [comment]
afaik there are apps in the appstore which have even more features
