### ISSUE TITLE
Update to version 8.0 fails

### ISSUE THREAD

**Issue by kutsurak** [owncloud/core#14369]
Hello all

while trying to update to version 8.0 I get the following error

An exception occurred while executing 'INSERT INTO oc_share_external (id, "remote", "share_token", "password", "name", "owner", "user", "mountpoint", "mountpoint_hash") SELECT id, remote, share_token, password, name, owner, user, mountpoint, mountpoint_hash FROM __temp__oc_share_external':

SQLSTATE[23000]: Integrity constraint violation: 19 oc_share_external.remote_id may not be NULL

I'm running a debian Wheezy (7.8) with Apache/2.2.22 (Debian)

Any ideas?

Thanks in advance,
Panos.

**Comment by RealRancor** [comment]
Hi,

thats probably a duplicate https://github.com/owncloud/core/issues/13970 and at least two or three other (already closed duplicates).

**Comment by kutsurak** [comment]
Thanks, a lot! I'll close this issue in order to aboid confusion.
