### ISSUE TITLE
Owncloud 8 package for ubuntu 12.04 fails to install because php version < 5.4

### ISSUE THREAD

**Issue by robho** [owncloud/core#14363]
I'm not sure where to report this problem. If this is the wrong place, please tell me where to go.

### Steps to reproduce
1. Install ubuntu 12.04
2. Add repository http://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_12.04/
3. Install owncloud (sudo apt-get install owncloud)

### Expected behaviour
Owncloud installs successfully

### Actual behaviour
Install fails:
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 owncloud-server : Depends: php5 (>= 5.4.0) but 5.3.10-1ubuntu3.16 is to be installed
E: Unable to correct problems, you have held broken packages.
```

### Server configuration
**Operating system**:
Ubuntu 12.04

**Web server:**
Apache 2.2.22

**Database:**
mysql 5.5.41

**PHP version:**
php 5.3.10

**ownCloud version:** (see ownCloud admin page)
owncloud-server_8.0.0-5_all.de

**Comment by DeepDiver1975** [comment]
yes - we require php 5.4 with oc8 - sorry.

**Comment by robho** [comment]
Thanks for the response. I'm closing this issue then.

(Maybe it should be considered to stay with owncloud 7 in the ubuntu 12.04 repo or the 12.04 repo should be dropped?)

**Comment by RealRancor** [comment]
@robho: You still can install PHP 5.4 from launchpad repositories:

https://launchpad.net/~ondrej/+archive/ubuntu/php5-oldstable

so there is no reason to drop the OC8 for Ubuntu 12.04

If you don't want to install PHP 5.4 you can stay with OC7 using the repos here:

http://download.opensuse.org/repositories/isv:/ownCloud:/community:/7.0/xUbuntu_12.04/

**Comment by RealRancor** [comment]
Also a ref to include the links to the older repos: https://github.com/owncloud/owncloud.org/issues/330

**Comment by Ark74** [comment]
After upgrading php (5.3 -> 5.4) and oc (7->8) then went to maintenance mode and never got back from it, resulting on a blank page.

apache2 showed 500 error, but no luck finding the issue, if manually change 
config/config.php back to
'maintenance' => true,

i could see the page asking for time to upgrade, if it goes back to false, then it will never got back.
(same structure that robho)

**Comment by RealRancor** [comment]
@Ark74
I think thats not really related to this issue. Make sure that you have followed the manual upgrade instructions at doc.owncloud.org and if you still have problems create a new issue using the issue template.

**Comment by McPeterBlinckers** [comment]
Sorry for my english.. but i don't understand why owncloud don't check php version _BEFORE_ install new version ?!! by default when owncloud say me upgrade version i launch it ... now my server in product is broken :(
I thinck owncloud must check if upgrade is available in product and that before inwtall it :\

**Comment by RealRancor** [comment]
@McPeterBlinckers 
How did you upgrade (there are several ways of doing so) and where do you want to have such a check?

1. If manual/via the package manager report a new issue here: https://github.com/owncloud/core/issues
2. If via the updater app report a new issue here: https://github.com/owncloud/updater/issues

**Comment by McPeterBlinckers** [comment]
@RealRancor 
I upgrade via updater app. I thinks when update apps download new version it can check if all is available before final install and stop install with : "you're php version is not available for OC8". finaly i can fix it by install php5.4 via ppa... Just for information ppa php5.4 on ubuntu 12.04 broke php5-xcache. Solution : desinstall and reinstall it.

### Server configuration
**Operating system**: Ubuntu Server 12.04.5 LTS

**Web server:** Apache 2.2.22

**Database:** MySql 5.5.41

**PHP version:** Php 5.4.38

**ownCloud version:** ownCloud 8.0.2 (stable) 

**Updated from an older ownCloud or fresh install:** from OC 7.0.4.2

**Comment by Ark74** [comment]
@RealRancor 
You were right, the problem was other third party app that was not manually disable when i made the upgrade.

Thanks, all is working now.
