### ISSUE TITLE
Announcement to all users

### ISSUE THREAD

**Issue by biobeo** [owncloud/core#14365]
What if I would like to close or update to a new fresh version of my owncloud server, I would like to post an announcement to all users that the server will be updated within one week, They should download all the important files they have uploaded.

We need an announcement bar at the top of page where all users can see important messages from admin like the popup application. (The popup application not works on every sites we need this feature as default.)

**Comment by Sugaroverdose** [comment]
It's more app request :)
https://apps.owncloud.com/content/show.php/popup?content=165669

**Comment by DeepDiver1975** [comment]
looks like there is already an app for this purpose - @nickvergessen FYI as you wanted to work on something like this as well.

**Comment by biobeo** [comment]
The app not works on version 8 as I told it, also It's not running on the version 7.0.2 which is in my case.

**Comment by DeepDiver1975** [comment]
> The app not works on version 8 as I told it, also It's not running on the version 7.0.2 which is in my case.

I see - I missed that part - sorry

**Comment by Xenopathic** [comment]
This can be implemented as an app, oC 7 no longer recieves feature updates

**Comment by nickvergessen** [comment]
I finished my app yesterday. It requires ownCloud 8.2 thou, but other then that, it is exactly what you are looking for: https://github.com/nickv-oc/announcementcenter

**Comment by karlitschek** [comment]
very cool!!! :-) @jospoortvliet Something for the next developer report :-)
