### ISSUE TITLE
disable cancel sharing folder

### ISSUE THREAD

**Issue by gal79** [owncloud/core#14364]
Hi all,
sorry for my english
Server 8
I create two users A and B.
User A create a folder, share this folder for user B and give some rights..
But after, user B have the ability to cancel sharing - click icon recycle bin and folder hiding.
Can user A to disable cancel sharing for B? Thanks

**Comment by LukasReschke** [comment]
This is not possible.

**Comment by gal79** [comment]
LukasReschke, thank you for the reply.
Its a pity( I think that it is a big minus
And I think that Administrators group must have full permissions for all objects of cloud automatically; to assign any permissions for objects (allow/deny) - it will follow the order through the web interface.
-
Also, is missing possibility to choose other color for folder and file icons (5-10 variants or open palette).
This are my wishes)
2programmers: thanks very much for the owncloud!
