### ISSUE TITLE
less intrusive noscript-warning on download page

### ISSUE THREAD

**Issue by unhammer** [owncloud/core#14361]
When I send someone who uses noscript a download link, they shouldn't have to click "inspect element" and delete the warning-element before being able to download. 

Perhaps the warning could be a bar at the top of the screen (like stackoverflow has)?

**Comment by DeepDiver1975** [comment]
@jancborchardt please have a look - THX

**Comment by jancborchardt** [comment]
We could actually remove the script warning on the single-file download page, cause no JS is needed there, is it? @MorrisJobke @PVince81

**Comment by PVince81** [comment]
Is this still happening ? There is now a read-only input text field rendered on the server-side, so it should be possible to copy the URL from there.

Please reopen if the problem still exists in 9.1.1
