### ISSUE TITLE
Temporal files are left in the temporal directory for SMB external storage

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#14374]
### Steps to reproduce
1. Activate external storage and connect to a SMB / CIFS storage
2. Upload a big file (tested with a 510MB text file, max upload 512MB)
3. Let the upload finish correctly

### Expected behaviour
Temporal files are cleaned up. There should be no traces of the uploaded file there

### Actual behaviour
Files such as "smb.down.E1eEbM" are left in the temporal directory with the same filesize as the uploaded files.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** checked with 6.0.7 RC1 and 7.0.5 RC1

**Updated from an older ownCloud or fresh install:** fresh install

### Notes
I've checked with other storages (not all) and it seems this is the only one that present this behaviour. Other storages seems to delete the temporal files well

**Comment by karlitschek** [comment]
@icewind1991 Can you have a look?

**Comment by MorrisJobke** [comment]
@icewind1991 Wasn't there some work done with the tempDirManager lastly?

**Comment by PVince81** [comment]
@jvillafanez are you still seeing this issue with 8.0.5 ?

A temp dir manager was introduced but I don't remember in which OC version. @icewind1991

**Comment by MorrisJobke** [comment]
@PVince81 #11709 ... getTempManager() was added in 8.0.0

**Comment by jvillafanez** [comment]
8.0.5 and 7.0.7 seem to work fine with 500MB files :+1:
