### ISSUE TITLE
Drag and drop doesn't work on dropbox external storage folders.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#14375]
### Steps to reproduce

Having a dropbox mount point using external storage app activated with several files and folders inside.
1. Enter the dropbox folder.
2. Try to drag and drop a file into a folder.
### Expected behaviour

File is moved to the folder.
### Actual behaviour

Drag and drop isn't allowed in this folder.
### Server configuration

**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.0.0.6","versionstring":"8.0 RC 2","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
none

**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password and passwordsalt)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
yes, Dropbox

**Are you using encryption:** yes
### Client configuration

**Browser:**
Chrome, Firefox.

**Comment by karlitschek** [comment]
@PVince81

**Comment by PVince81** [comment]
"as in the rest of the owncloud UI", what do you mean with that ?
I assume you tried dragging files into a non-Dropbox folder and it worked ?

**Comment by SergioBertolinSG** [comment]
Edited. I meant that in every other type of folders you can drag and drop, but in dropbox folders you can't.

**Comment by PVince81** [comment]
Cool, thanks for the clarification.

**Comment by PVince81** [comment]
Works for me on master, dragging a file from konqueror into chromium (drop upload), or from the parent folder into the "dropbox" folder.

**Comment by PVince81** [comment]
please retry with new Dropbox app as the API calls are different there
