### ISSUE TITLE
ownCloud should check for mbstring.func_overload

### ISSUE THREAD

**Issue by Raydiation** [owncloud/core#14372]
Linking issue https://github.com/owncloud/news/issues/732

mbstring.func_overload basically tells PHP to use mb functions instead of the default ones, e.g.: stlren is turned into mb_strlen

This can cause all sorts of shenanigans, like broken pages (https://github.com/owncloud/core/blob/master/lib/private/appframework/app.php#L116) etc.

We should therefore warn on admins on the admin and setup page if they've enabled this setting

@DeepDiver1975 @MorrisJobke @LukasReschke @PVince81

**Comment by Raydiation** [comment]
#shit-php-does

**Comment by Raydiation** [comment]
@RealRancor why is news in the modules array? This thing applies globally

**Comment by MorrisJobke** [comment]
@realRancor: Please add them there: https://github.com/owncloud/core/blob/7a9d428d6f6146d44883e2c5bab04db702792ce4/lib/private/util.php#L575

**Comment by RealRancor** [comment]
Sorry, i won't start doing core development.

The checks in the linked app are easy for me to add and test on my stable7 productive system and the settings.php is also linked in a forums thread.

If this should be added to core someone else needs to do it.

**Comment by RealRancor** [comment]
@MorrisJobke 
Btw. its now the third ini setting which should be checked in the util.php:
new: mbstring.func_overload, output_buffering
existing: default_charset

so its probably better that an more experienced dev is adding an general test for ini settings in the util.php

**Comment by LukasReschke** [comment]
Yes – fair point – will add an helper here as well. Thanks @RealRancor.
