### ISSUE TITLE
[user_ldap] [feature request] set displayName as a sum of attributes

### ISSUE THREAD

**Issue by kralizeck** [owncloud/core#14385]
Be able to set "User Dispaly Name Field" in LDAP->Advanced->Directory Settings, as a sum or combination of multibple attributes, like "User search attributes" fiel.

p.e.
givenName
sn

Resulting a displayName = "givenName sn"

**Comment by MorrisJobke** [comment]
cc @blizzz

**Comment by blizzz** [comment]
Actually a thing I plan to do, hopefully for 8.1. Although it would not be a list, but you could specify a format. Just chaining values won't be sufficient.

**Comment by blizzz** [comment]
No real news, but this is effectively a dup of https://github.com/owncloud/core/issues/3597, because when i finally come around to implement it, it will have the possibility to define custom display name patterns. Please follow there.
