### ISSUE TITLE
Temporary files created by ownCloud are not removed after they are no longer required

### ISSUE THREAD

**Issue by j-ed** [owncloud/core#14387]
## Expected behavior
If ownCloud creates temporary directories to fulfill its tasks, these directories should be removed after they are no longer required.

## Actual behavior
Temporary directories which have been created by ownCloud are not removed after they are no longer required.
```
# ls -ald /tmp/owncloud-*
drwxr-xr-x 2 wwwrun nogroup 4096 Feb 19 19:14 /tmp/owncloud-oc7wua239hr6
drwxr-xr-x 2 wwwrun nogroup 4096 Feb 14 18:28 /tmp/owncloud-ocdqm97byaxm
drwxr-xr-x 2 wwwrun nogroup 4096 Feb 13 09:13 /tmp/owncloud-ocojmxio97cp
drwxr-xr-x 2 wwwrun nogroup 4096 Feb 13 09:28 /tmp/owncloud-ocwqinrim3m8
```
I did some research and found out that the function `getCacheDir()`, which is defined in */var/www/htdocs/owncloud/lib/private/cache/fileglobal.php*, seems to be responsible for these abandoned directories. Several function in the same file are using this function to fulfill their tasks but although they are making sure that temporary created files are deleted, the temporary directories which contained these files, are not removed afterwards.

#### Server Configuration
OS: Linux 3.2.54
Web server: Apache2 2.4.10
Database: MySQL 5.1.73
PHP version: 5.4.35
ownCloud version: 8.0

#### Client Configuration
Browser: Firefox 35.0.1
Operating system: Windows 7

**Comment by LukasReschke** [comment]
@icewind1991 FYI

**Comment by oparoz** [comment]
FYI, these folders are used to store LibreOffice configs per example. There may be other uses.

**Comment by icewind1991** [comment]
These folders are not "no longer required" since the same folder will be used next time something is stored in the global file cache, only one folder per owncloud instance is created

**Comment by GuriSoft** [comment]
In my domain, after installing OwnCloud, I have 2 directories:

tmp-owncloud1458573370
owncloud

I've deleted the tmp-owncloud1458573370 folder...

So far, everything is working fine, have tested on the web, mac desktop app, Iphone app, ipad app and also an android tablet app. 

Cheers...!

***
