### ISSUE TITLE
ownCloud 8 LDAP/AD groups and share not fully operational

### ISSUE THREAD

**Issue by labkode** [owncloud/core#14384]
My stack is:
- Owncloud 8
- MySQL 5.5
- Ubuntu 14.10
- LDAP/AD user and group backend.

If somebody shares a folder with a group I belong to , I can see this share but in the moment I leave the group and after waiting for the LDAP cache to refresh I am still able to see the share.

I know that you update the share table when a user is added to a group, but why not remove on leaving? or at least changing permissions to 0 like an unshare ?

This scenario can lead to a security hole where the user could see files that he don't have access.

Best regards

**Comment by karlitschek** [comment]
@blizzz any idea?

**Comment by blizzz** [comment]
@labkode group memberships are refreshed every one hour by background job. For LDAP groups we do not know when a user is added or removed, but we need to discover/update memberships regularly. I assume you refer to LDAP groups, not local ones?

**Comment by labkode** [comment]
@blizzz I am referencing LDAP groups only, which as far as I know are updated depending on the Cache Time to Live parameter in Advanced Tab in LDAP settings.

The test case is the following.

We have two users: A and B.
We have a group called MYGROUP. 
Both A and B  belong to MYGROUP.
A shares folder MYFOLDER  with group MYGROUP
B can see the share because is in MYGROUP
....
B leaves MYGROUP
LDAP cache refreshed
B still can access the shared folder MYFOLDER, and should not.


Cheers

**Comment by blizzz** [comment]
@labkode as said, group memberships (by group, not by user) are refreshed every hour by background job (given it's configured properly).

**Comment by labkode** [comment]
@blizzz Thanks. How can I check if the background job is configured correctly ? I have a fresh installation.
Best regards

**Comment by blizzz** [comment]
@labkode Please see https://doc.owncloud.org/server/8.0/admin_manual/configuration/background_jobs_configuration.html

**Comment by labkode** [comment]
@blizzz After ran the cron job to update the groups the problem still persists and the user can see the shared folder.

**Comment by blizzz** [comment]
@labkode there is a table called oc_ldap_group_members. Could you check whether the members of the  group in  questions are up to date, or are there users missing  or too many?

**Comment by labkode** [comment]
I checked that table and there are other groups mapped to some users, but for my group there is no entry at all. 
Another thing I find interesting is that I have around 40 000 groups and around 20 000 users and in the table oc_ldap_group_members there are only 2000 rows. Is this a limit ?

**Comment by blizzz** [comment]
@labkode it might be a LDAP server defined restriction.

**Comment by PVince81** [comment]
@blizzz any update ?

**Comment by blizzz** [comment]
* [ ] TODO: check whether background job handles massive amount of groups properly

However, I don't think it's the issue here. File sharing does not rely on the hooks anymore, but the group memberships are fetched dynamically. This should be the case in OC 8 at least. That also means, the Cache TTL would be in effect for group memberships indeed. We had some fixes with group memberships, but usually in connection with primary groups in the time span since the report, and usually there were not too many members. 

@labkode could you tell us whether the issue still persists and in which exact version?

**Comment by labkode** [comment]
@blizzz  I cannot tested because we drop the OC LDAP group management and we implemented our own to update the memberships on the fly based on EOS, so we don't have the group membership table anymore.

To check if the issue is still persistent this scenario should tell you:

```
The test case is the following.

We have two users: A and B.
We have a group called MYGROUP. 
Both A and B belong to MYGROUP.
A shares folder MYFOLDER with group MYGROUP
B can see the share because is in MYGROUP
....
B leaves MYGROUP
LDAP cache refreshed
B still can access the shared folder MYFOLDER, and should not.
```

**Comment by PVince81** [comment]
See https://github.com/owncloud/core/issues/19541 for the issue where the share API still returns the old share entry.

There is another issue here: whenever the LDAP cache refreshes itself, it should trigger the hooks that cleans up the share entries. In a non-LDAP situation I saw that removing a user from a group would automatically clear their outdated shares. If the LDAP situation doesn't do it it means the hooks aren't triggered properly. @blizzz

**Comment by blizzz** [comment]
@cmonteroluque um…we don't have a severity here?

**Comment by PVince81** [comment]
https://github.com/owncloud/core/issues/19541 was fixed, so the symptoms described in https://github.com/owncloud/core/issues/14384#issuecomment-143354710 should not appear any more.

So now this ticket is only about checking if the add/delete hooks are triggered properly when new groups are synced from LDAP.

**Comment by cmonteroluque** [comment]
https://github.com/owncloud/core/issues/14384#issuecomment-146007441 True. There are a couple of issues that we want fixed on top of the list of sev1 and sev2's.

**Comment by blizzz** [comment]
* master (8.2) is not affected, because sharing works different: directly to groups instead of users. It does not rely on hooks.
* 8.1: did not reassure, iirc it works as in master.
* 8.0.x is affected. Running the cronjob did resolve the issue. The hooks is thrown correctly (although there are issues #17355, but removeFromGroups is correct). Important: that cron job needed to be run before sharing to a group and removing a users from it. So all the group memberships are populated (oc_ldap_group_members DB table). Such hooks are only thrown by the background job.

@labkode does it help you?

**Comment by labkode** [comment]
@blizzz  we are not suffering it and it is fixed in the latest branchs, I think it is OK to close this issue.
