### ISSUE TITLE
OC 7 or 8 package for Debian/Ubuntu (OC 7 not existing, OC 8 not working < 14.04)

### ISSUE THREAD

**Issue by dirkbrent** [owncloud/core#14393]
I'm running Ubuntu 12.04 and I'd like to continue using ownCloud. Unfortunately OC 8 requires PHP 5.4 which does not exist in the Ubuntu repos. A PHP backport is also out of the question because I have a lot of PHP-based 3rd party software running, and I'm reasonably certain that a few things might break if I upgrade to PHP 5.4+. 

The [openSUSE repository](https://software.opensuse.org/download/package?project=isv:ownCloud:community&package=owncloud) only includes OC 8 and has removed OC 7. 

(a) Where do I find the Debian-resources to build the package myself (`debian/`)?
(b) What exactly depends on PHP 5.4? Can it be deactivated?
(c) Any other ideas to either make OC 8 work on 12.04 or keep using OC 7 on Debian?

Thanks!!

**Comment by LukasReschke** [comment]
http://download.opensuse.org/repositories/isv:/ownCloud:/community:/7.0/

**Comment by dirkbrent** [comment]
:+1: Sorry I missed that...

**Comment by RealRancor** [comment]
Ref for a request to add this to the owncloud.org page: https://github.com/owncloud/owncloud.org/issues/330

**Comment by RealRancor** [comment]
An additional note to this:

> What exactly depends on PHP 5.4? Can it be deactivated?

ownCloud completely depends on PHP 5.4 as stated in:

http://doc.owncloud.org/server/8.0/admin_manual/release_notes.html
