### ISSUE TITLE
sql error while update from 7.0.4 to 8.0.0

### ISSUE THREAD

**Issue by michl85** [owncloud/core#14398]
Update from 7.0.4 to 8.0.0 aborts always with the following error message during "Database update":

SQLSTATE[HY000]: General error: 1 cannot commit transaction - SQL statements in progress

**Comment by LukasReschke** [comment]
Thanks a lot for reporting issues back to us!

We need some more information to properly support you with your issue!

Can I ask you to follow our guidelines for submitting bugs as described here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by michl85** [comment]
Sorry, of course!

### Steps to reproduce
1. Upgrade as described in the administrators manual until
"With the next page request the update procedures will run."

### Expected behaviour
After page request update procedure starts and upgrade should 
run through successfully.

### Actual behaviour
After page request update procedure starts and the following error
message appears on step "Update database" ("Datenbank aktualisiert"):

SQLSTATE[HY000]: General error: 1 cannot commit transaction - SQL statements in progress

### Server configuration
**Operating system**: Linux 2.6.18-xxxxx x86_64 (Webhoster with no terminal access)

**Web server:** Apache

**Database:** MySQL 5.5.32-cll-lve

**PHP version:** 5.2.13

**ownCloud version:** 7.0.4 (now maybe something inbetween)

**Updated from an older ownCloud or fresh install:** Update process from 7.0.4
to 8.0.0

**List of activated apps:** Non not already activated in the standard configuration as far as I can remember

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => 'oc0288b2b454',
  'passwordsalt' => 'xxxx',
  'trusted_domains' => 
  array (
    0 => 'mcloudm.xxxxx.de',
  ),
  'datadirectory' => '/home/www/webxxxxx/html/mcloudm/mcloudm/data',
  'dbtype' => 'sqlite3',
  'version' => '7.0.4.2',
  'installed' => true,
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
  'secret' => 'xxxxxxx',
);


**Are you using external storage, if yes which one:** none

**Are you using encryption:** no, just SSL

### Client configuration
**Browser:** Firefox 35.0

**Operating system:** Gentoo Linux

### Logs
#### Web server error log

No error messages from webhoster concerning the upgrade proccess

#### ownCloud log (data/owncloud.log)

No error messages concerning the upgrade proccess. Last on is a "Login failed:" before
the upgrade

#### Browser log

Don't think that the problem is there.


Hope this helps. If you need further information please let me know!

Thank you very much in advance!

**Comment by Tribalize** [comment]
PHP 5.3 Support Dropped
PHP 5.3 is not supported in ownCloud 8, and PHP 5.4 or better is required.

Maybe the issue.

**Comment by LukasReschke** [comment]
> PHP version: 5.2.13

Are you sure that you mean 5.2.13? :scream:

**Comment by michl85** [comment]
That's what the info.php of my hosting account says. But a email correspondence with my hosting provider some time ago says 5.5. How can I test this?

**Comment by LukasReschke** [comment]
Create a file called `test.php` with the following content:

```php
<?php
phpinfo();
```

And upload it where your ownCloud is located, access it then via your web browser and tell us what it says ;-)
(if you don't mind us seeing your URL and some details you can also link it here)

**Comment by michl85** [comment]
It's really 5.5.0

If the URL helps you finding the problem I will link. Do you still need it?

**Comment by datorexpert** [comment]
I get the same error when upgrading to Owncloud v8 from v7 on a QNAP SS-839 (x86) with PHP v5.5.19.
Any solution?
I have a phpinfo.html file if you want it?

**Comment by michl85** [comment]
When there is no way forward to v8 is there maybe a save way back to 7.0.4 without having a backup of the config and data folder beside the ones of the in-between state?
Thanks in advance!

**Comment by michl85** [comment]
For those how are interested in and have no real backup: "Downgrade" to 7.0.4 is easily possible by copying config and data dir back into the old 7.0.4 file structure. Here it works again.

**Comment by manaaaaa** [comment]
i Had the same Problem.

I fixed it myway : 

i installed it directly with this instructions :
http://wiki.qnap.com/wiki/Category:OwnCloud

**Comment by PVince81** [comment]
Is this still happening with 8.0.5 ?

**Comment by datorexpert** [comment]
No!

2015-08-03 17:35 GMT+02:00 Vincent Petry <notifications@github.com>:

> Is this still happening with 8.0.5 ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/core/issues/14398#issuecomment-127279846>.
>



-- 
Best Regards,
/Thomas Andersson
Senior Storage Specialist

M: +46 725 22 23 45
E: senior.storage.specialist@gmail.com

**Comment by michl85** [comment]
Here it's still happening with 8.0.5 and 8.1.0.

**Comment by nihe** [comment]
I also have the same issue. i cannot update to 8.1.3 from 7.0.4. 
I read the system requirements for 8.1.x and see that apache 2.4 is required...
check  the version running on my qnap 
/usr/local/apache/bin/apache -v show me this. 

Server version: Apache/2.2.29 (Unix)

@michl85  
can you verify the version of apache?

can anyone else verify it the apache version 2.2 is working or not?

**Comment by michl85** [comment]
@nihe 
Sorry I cannot find the version of Apache. I'm using a webhoster and the version information about Apache is missing everywhere I looked.
In the meanwhile I fixed the issue by converting the database from SQLite to MySQL. So it's maybe a pure SQLite issue?

**Comment by PVince81** [comment]
@nihe you need to first upgrade to 8.0.x, and then to 8.1. Future versions will show a warning when attempting to skip major versions. (since the OC 8 series, the second digit counts as major version)

**Comment by PVince81** [comment]
Please reopen if you're still having update issues to 8.1.5 or 8.2.2.
Make sure to not skip major versions.
