### ISSUE TITLE
Renaming folders is not reflected in shared name

### ISSUE THREAD

**Issue by canepan** [owncloud/core#14397]
I'm using OwnCloud 7.0.4 with MySQL backend
When I do the follwoign steps:
* create a folder (i.e. "nicola is cool")
* share the folder with a user group
* rename the folder (i.e. "nicolaiscool")
* users in the group see it as the original name ("nicola is cool")
I think also the share name should be updated to reflect the new name

**Comment by jancborchardt** [comment]
This is intended behavior so that people can move and rename shares to their liking / to fit their folder structure or naming. As far as I know this is also how Dropbox does it – feel free to double-check.

cc @owncloud/designers @DeepDiver1975 for reference.
