### ISSUE TITLE
Updating owncloud with indian timezone GMT+5:30 fails

### ISSUE THREAD

**Issue by bit** [owncloud/core#14391]
DateTimeZone::__construct(): Unknown or bad timezone (Etc/GMT-5.5) at owncloud/lib/private/datetimezone.php#52

Etc/GMT-5.5 does not exist as timezone, one has to use Asia/Kolkata instead.

**Comment by bit** [comment]
This will also be an issue for other timezones where the offset is not a full hour (http://www.timeanddate.com/time/time-zones-interesting.html)

'-04:30': 'America/Caracas',
'-03:30': 'Canada/Newfoundland',
'+03:30': 'Asia/Tehran',
'+04:30': 'Asia/Kabul',
'+05:30': 'Asia/Kolkata',
'+05:45': 'Asia/Kathmandu',
'+09:30': 'Australia/Darwin',

**Comment by RealRancor** [comment]
Ref for a similar report: https://github.com/owncloud/core/issues/14176

So it is not necessarily related to the half hour timezone.

**Comment by bit** [comment]
php does not know GMT-5.5 as timezone name so
 new \DateTimeZone('Etc/GMT-' . $offsetHours);
with offsetHours = 5.5 in
https://github.com/owncloud/core/blob/master/lib/private/datetimezone.php#L52
fails. The other bug is also about timezones but not related from what I see.

**Comment by nickvergessen** [comment]
In deed, http://php.net/manual/en/timezones.others.php
Will close this as it is a duplicate

**Comment by nickvergessen** [comment]
@bit can you please post the full log entry of the error you got.
Just to be sure its the same issue as the one we think is a duplicate

**Comment by bit** [comment]
@nickvergessen dont have the logs anymore. But I get the same error creating a simple php file with 
<?php
print_r(DateTimeZone('Etc/GMT-5.5'));

and it was the call in 
https://github.com/owncloud/core/blob/master/lib/private/datetimezone.php#L60

**Comment by nickvergessen** [comment]
the question is where this wrong value comes from
Can you try to reproduce the error please?

**Comment by bit** [comment]
The fix for #14429 (https://github.com/owncloud/core/commit/a08e77b6fdd404902315b18c5b72d1919c315620) will also fix this issue.

**Comment by MorrisJobke** [comment]
Will be in 8.0.3 and 8.1
