### ISSUE TITLE
OC\Files\Node\Node doesn't check it has a valid FileInfo object before working on it

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#14390]
### Problem
A method creates a new OC\Files\Node\Node, using a broken path
A method then calls OC\Files\Node\Node->getFileInfo()
```
public function getFileInfo() {
	if (!$this->fileInfo) {
		$this->fileInfo = $this->view->getFileInfo($this->path);
	}
	return $this->fileInfo;
}
```
which calls OC\Files\View->getFileInfo using the broken path
```
public function getFileInfo($path, $includeMountPoints = true) {
...
		$data = array();
		if (!Filesystem::isValidPath($path)) {
			return $data;
		}
...
```
which returns an empty array as a FileInfo object.

Now the Node object is going to call many different methods on an array and that will fail and break anything sitting on top of it.

Some examples of these methods
```
public function isMounted() {
	return $this->getFileInfo()->isMounted();
}
public function isShared() {
	return $this->getFileInfo()->isShared();
}
public function getMimeType() {
	return $this->getFileInfo()->getMimetype();
}
public function getMimePart() {
	return $this->getFileInfo()->getMimePart();
}
public function getType() {
	return $this->getFileInfo()->getType();
}
public function isEncrypted() {
	return $this->getFileInfo()->isEncrypted();
}
public function getMountPoint() {
	return $this->getFileInfo()->getMountPoint();
}
```

### Fix it in Node
* Check that we actually have a FileInfo object
* Throw an exception letting others know that things went sour

**Comment by PVince81** [comment]
@icewind1991

**Comment by DeepDiver1975** [comment]
let's close this once fixed on stable8

**Comment by oparoz** [comment]
@DeepDiver1975 - And only if the PR actually fixes the problem. User has provided feedback that it did not: https://github.com/owncloud/core/pull/14437#issuecomment-75838164

**Comment by DeepDiver1975** [comment]
@oparoz indeed - but I still question that the patch was properly applied - the fix by itself is valid to fix the bug :speak_no_evil:

**Comment by oparoz** [comment]
@DeepDiver1975 - Let's wait for the user to get back to me, but this check does not catch all bad values of $fileinfo.
https://github.com/owncloud/core/blob/master/lib/private/files/node/node.php#L60
```
if (!$this->fileInfo) {
```
Maybe something like this would be better suited
```
if (!$fileInfo instanceof FileInfo) {
```

**Comment by DeepDiver1975** [comment]
@icewind1991 ^^^ THX

**Comment by icewind1991** [comment]
@oparoz we already do an instanceof a few lines down

**Comment by oparoz** [comment]
@icewind1991 - Indeed, but let's say $fileInfo is already defined elsewhere, which is not totally unexpected since Node can be sub-classed.
In this case, the check made lower down might not be reached.
Seems a bit far-fetched, I know, but if that user is really encountering that error, then it means that it can happen somehow.

**Comment by nickvergessen** [comment]
Stable8 branch has been merged aswell
