### ISSUE TITLE
ERROR while upgrading: varchar() too long

### ISSUE THREAD

**Issue by gladiac** [owncloud/core#14395]
Hi,

if you try to upgrade owncloud you get the error:

```An exception occurred while executing 'ALTER TABLE cld_foldersize ENGINE=InnoDB;': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes```

VARCHAR is stronger limited due to UTF8. Lookint at the table the path is VARCHAR(512). Some distros apply a patch to allow bigger, some don't or remove it again. So sometimes it works and sometimes not ...

https://stackoverflow.com/questions/6172798/mysql-varchar255-utf8-is-too-long-for-key-but-max-length-is-1000-bytes
http://bugs.mysql.com/bug.php?id=4541

**Comment by LukasReschke** [comment]
@DeepDiver1975 @bantu Thougths?

**Comment by DeepDiver1975** [comment]
@gladiac foldersize is not a table used in core - can you please let us know which apps you have installed? Maybe you can grep for foldersize in all database.xml files in your installation? THX

**Comment by gladiac** [comment]
I don't find it in any database.xml, so I've deleted the table. However the same applies for fscache  which has a long varchar for path and name!

**Comment by DeepDiver1975** [comment]
fscache is an old table from pre-oc5 - can be dropped as well

**Comment by DeepDiver1975** [comment]
maybe we sould add a repair job to remove these old tables
- [ ] foldersize
- [ ] fscache

**Comment by PVince81** [comment]
This repair step was already added: https://github.com/owncloud/core/pull/14638
