### ISSUE TITLE
Upgrade from 7.0.4 always fails

### ISSUE THREAD

**Issue by gladiac** [owncloud/core#14394]
I'm not able to upgrade from 7.0.4 to the latest version 8.0. The error I get is:

```An exception occurred while executing 'CREATE TABLE oc_cld_appconfig_9mvxep97vtbun (`appid` VARCHAR(32) DEFAULT '' NOT NULL, `configkey` VARCHAR(64) DEFAULT '' NOT NULL, `configvalue` LONGTEXT DEFAULT NULL, INDEX oc_x45gjuy5niy0x (`configkey`), INDEX oc_8ywbcxflgfp1p (`appid`), PRIMARY KEY(`appid`, `configkey`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_cld_appconfig_9mvxep97vtbun' already exists```

Apache 2.5 PHP 5.6.1

**Comment by gladiac** [comment]
Strange, now the error is a different one ...

**Comment by gladiac** [comment]
No, the error still occurs. It is strange since the table has a random value in the name ...

**Comment by DeepDiver1975** [comment]
@icewind1991 we had this error already last week afaik - would be good to get this analyzed - THX

@gladiac feel free to drop tables with that random postfix before retrying - THX

**Comment by gladiac** [comment]
I don't have any table with the random postfix. But I keep getting this error so help would be appreciated to fix that.  You can also find me in the IRC channel ...

**Comment by gladiac** [comment]
I it possible it tries to create the able with the same name twice?

**Comment by nazar-pc** [comment]
Same here, upgrade from 7.0.4 to 8.0 on Ubuntu

**Comment by nazar-pc** [comment]
No, different one SQL error:
```
An exception occurred while executing 'ALTER TABLE oc_oc_appconfig_greprkijxns9u RENAME INDEX appconfig_config_key_index TO oc_lfpvizqp0i0f3': SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'INDEX appconfig_config_key_index TO oc_lfpvizqp0i0f3' at line 1
```

**Comment by nazar-pc** [comment]
Reported as #14448

**Comment by karlitschek** [comment]
close a duplicate
