### ISSUE TITLE
"Enable" in app manager should say "Download" when downloading from remote server

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#14405]

**Comment by jancborchardt** [comment]
Not sure if yet another label for the button (after we already have »Enable« and »Install« …) is a good idea. Maybe just add a tooltip note to the button? Or is this even needed at all?

**Comment by LukasReschke** [comment]
From a security PoV it is required yes - we're doing something completely different than what the button says which got quite some people complaining to me :see_no_evil:

A tool-tip would be a valid alternative – yes. Seems easier.

**Comment by jancborchardt** [comment]
Cool, then let’s do it as a tooltip.

**Comment by karlitschek** [comment]
@jancborchardt So do we have the tooltip? ;-)

**Comment by jancborchardt** [comment]
Hehe – as this requires PHP code to decide if the tooltip should be shown or not, I assumed @LukasReschke would do it. ;)
