### ISSUE TITLE
php version 

### ISSUE THREAD

**Issue by Wildpit** [owncloud/core#14407]
Owncloud.org says System administrators should take note that PHP 5.4 is now required for ownCloud Server 8.0.

But the PHP Function password_hash() (used in hasher.php) ist avalible at PHP >= 5.5.0
PHP 5.4 breaks all passwords in the database

is the note on ouncloud.org or this function a error ?

Wildpit

**Comment by LukasReschke** [comment]
Did you test this?

We ship a PHP-only drop-in replacement.

**Comment by LukasReschke** [comment]
https://github.com/owncloud/3rdparty/tree/stable8/ircmaxell/password-compat

**Comment by LukasReschke** [comment]
Works fine here on 5.4.37, also we have complete test coverage on this and if this didn't work we should have noticed this before.

As this is used for authentication purposes as well others should have reported this as well…

If you can't login anymore then there is a different problem lying around somwhere… In this case please fill out the issue template.

**Comment by Wildpit** [comment]
Yes, with SQlite and MYSql
New Install and Upgrade.
all rehashed passwords in DB is set to 1|
an after many hours of searching i fund "$this->currentVersion . '|' . password_hash("
and $currentVersion ist Static set to 1
 i have the 1| passwords replaced with passwords hashed in sha1, but on new login the passwords sets back to 1| and no login possible without reset the sha1 hash in database

Wildpit

**Comment by LukasReschke** [comment]
>  In this case please fill out the issue template.

**Comment by LukasReschke** [comment]
https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by LukasReschke** [comment]
So you had SHA1 password before there then?

**Comment by Wildpit** [comment]
My server runs on php 5.4.16

**Comment by LukasReschke** [comment]
Again: Please fill out the issue template. I can't help you otherwise.

**Comment by LukasReschke** [comment]
See https://github.com/owncloud/core/blob/master/CONTRIBUTING.md for a link

**Comment by Wildpit** [comment]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Passwords in Database correct hashed

### Actual behaviour
passwords in databse is set to 1| on rehash

### Server configuration
**Operating system**:
OenSuse 11.2
**Web server:**
Apache2 2.4.4
**Database:**
MYsql 5.1.49
**PHP version:**
PHP 5.4.16
**ownCloud version:** (see ownCloud admin page)
8.0.0 Stable
**Updated from an older ownCloud or fresh install:**
current fresh install, on upgrade the same problem

**List of activated apps:**
Calendar,Contacts
**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => '',
  ),
  'datadirectory' => '/owncloud/data',
  'overwrite.cli.url' => ',
  'dbtype' => 'mysql',
  'version' => '8.0.0.7',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => 0,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
### Client configuration
**Browser:**
Firefox , Konqueror
**Operating system:**
Gentoo
### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)

{"reqId":"4ca35a2b42b2d42b4bb48ddc98d44893","remoteAddr":"85.176.194.145","app":"core","message":"Login failed: 'Oliver' (Remote IP: '85.176.194.145', X-Forwarded-For: '')","level":2,"time":"2015-02-20T16:36:49+00:00"}
{"reqId":"4ca35a2b42b2d42b4bb48ddc98d44893","remoteAddr":"85.176.194.145","app":"PHP","message":"touch(): Unable to create file \/srv\/www\/vhost\/bu-trans.de\/owncloud\/oc-80\/owncloud\/data\/owncloud.log because No such file or directory at \/srv\/www\/vhost\/bu-trans.de\/owncloud\/oc-80\/owncloud\/lib\/private\/log\/owncloud.php#48","level":3,"time":"2015-02-20T16:36:53+00:00"}
{"reqId":"d75f02b1011ff4b348bc3cef678fb7fc","remoteAddr":"85.176.194.145","app":"core","message":"Login failed: 'Oliver' (Remote IP: '85.176.194.145', X-Forwarded-For: '')","level":2,"time":"2015-02-20T16:37:03+00:00"}

#### Browser log
```
Browser Logging disabled

oc_users table on sqlite databse after fesh install and setup, noting more

sqlite3 data/owncloud.db
SQLite version 3.6.16
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> select * from oc_users;
Oliver||1|
sqlite>

**Comment by LukasReschke** [comment]
If you enter `a94a8fe5ccb19ba61c4c0873d391e987982fbbd3` (test) as hash for the user does it then work when logging in? (just to determine that this is no logic fail)

**Comment by LukasReschke** [comment]
Also notice that OpenSuse 11.2 is unsupported by the vendor and will not receive any fixes anymore (not even security fixes)

Please try updating to another distribution or a newer OpenSuse version. It might very well be the case that the PHP version shipped by OpenSuse here is buggy.

**Comment by Wildpit** [comment]
befor login :
SQLite version 3.6.16
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> update oc_users set password = 'a94a8fe5ccb19ba61c4c0873d391e987982fbbd3' where uid = 'Oliver';
sqlite> select * from oc_users;
Oliver||a94a8fe5ccb19ba61c4c0873d391e987982fbbd3
after login :
sqlite> select * from oc_users
   ...> ;
Oliver||1|
sqlite> 
i know opensuse 11.2 is an old version, but it is a little difficult with updates on a system witch is 24/7, the next possible free days is next chrismas days or 1.  May 
And Owncloud 7.0.4 works perfectly

**Comment by LukasReschke** [comment]
I really cannot reproduce this on any other decent distribution such as Ubuntu 14.x or Debian 7…

**Comment by LukasReschke** [comment]
@Wildpit Can you do me the favour and try if you can reproduce this problem with your database on Ubuntu 14.x or a Debian 7 (or some supported CentOS etc…)

If yes I will look into it and might require some examples hashes. However, until now it looks like this only affects you on OpenSuse 11.2 which we would consider as won't fix since unsupported by the vendor. If that is the case this means that you would only be able to use ownCloud 8 once you updated your distribution.

**Comment by Wildpit** [comment]
i have take a look in the hasher.php in owncloud 7.0.4
owncloud 7.0.4 uses the same function
now im confused, a little

**Comment by LukasReschke** [comment]
That's because the hasher is not used for 7.0 for user passwords but only for generic hashes (in core AFAIK none). With 8.0 we switched to said hasher.

**Comment by LukasReschke** [comment]
See https://github.com/owncloud/core/commit/c4d7483a0a7d1ea75bf06d0a4e726e2b150be81f which is only included in ownCloud 8+

**Comment by LukasReschke** [comment]
You might also want to try the following in `index.php`:

1. Comment out `OC::handleRequest();`
2. Add below the commented line `	var_dump(\OC::$server->getHasher()->hash('My Test'));`
3. Access the instance

What is the ouput? Also what do your *webserver* logs say? (for example `/var/log/apache/error_log`) - The issue template is missing that above.

**Comment by Wildpit** [comment]
var_dump returns string(2) "1|"  in browser on logout

the apache log says noting about this

the last logentry from owncloud is 
 [Fri Feb 20 17:36:48.471472 2015] [:error] [pid 30517] [client 85.176.194.145:59246] creating sqlite db, referer: https://oc.bu-trans.de/oc-80/owncloud/index.php

this is from fresh install befor chmod to webserver user.

**Comment by LukasReschke** [comment]
3rdparty folder contains ircmaxell/password-compat?

**Comment by Wildpit** [comment]
yes it contains  ircmaxell/password-compat

**Comment by LukasReschke** [comment]
Ok - then not really much I can do for you if you are not able to reproduce this on a newer system. Sorry, can't afford to spend too much time in something that I and other users can't reproduce.

That said, if you can reproduce this on any other newer distribution let me know which and I can take a look.

**Comment by Wildpit** [comment]
ok, thank you for help
