### ISSUE TITLE
[7.0.4] Sync large file to SFTP external storage file not complete

### ISSUE THREAD

**Issue by gig13** [owncloud/core#14406]
Reference https://github.com/owncloud/core/issues/11432

The log for this is at https://s3.owncloud.com/owncloud/index.php/apps/files?dir=%2FShared%2Fowncloud%2Fsupport%2Fgithub-issues%2Fcore%2F11432

**Expected Behavior**
Upload a large file (11 GB) file into the SFTP external storage without issues.

**Actual Behavior**
When uploading a large file into the SFTP, there are error messages saying failure, then it said sync is finished, but only 1.5GB was transferred and the destination files were incomplete.

**Steps to reproduce**
Upload a large file (4 to 11 GB) into an SFTP external storage mount and wait for error message.

**Server Config**
OC7.0.4
MySql DB
Apache
CentOS 6.5

**Comment by LukasReschke** [comment]
@bantu FYI

**Comment by bantu** [comment]
@gig13 
Which version/architecture of CentOS is that? x86?
Is this 64bit or 32bit PHP?
What is the SFTP server software? OpenSSH? Which version?

**Comment by bantu** [comment]
According to the logs this also involves ownCloud Client version 1.7.0 on Windows x86.

**Comment by bantu** [comment]
For the record: filesize(CentOS-7.0-1406-x86_64-DVD.iso) = 4148166656 < 4 GiB = 4294967296

**Comment by bantu** [comment]
Only client logs are provided. Is there anything in the server log?

**Comment by gig13** [comment]
@bantu
- 2.6.32-504.1.3.el6.centos.plus.x86_64 #1 SMP Tue Nov 11 23:01:20 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

64 bit php 5.6.4
rpm -qa|grep php
php-mysqlnd-5.6.4-2.el6.remi.x86_64
php-pdo-5.6.4-2.el6.remi.x86_64
php-process-5.6.4-2.el6.remi.x86_64
php-pecl-zip-1.12.4-2.el6.remi.5.6.x86_64
php-cli-5.6.4-2.el6.remi.x86_64
php-mbstring-5.6.4-2.el6.remi.x86_64
php-pecl-jsonc-1.3.6-1.el6.remi.5.6.1.x86_64
php-5.6.4-2.el6.remi.x86_64
php-xml-5.6.4-2.el6.remi.x86_64
php-common-5.6.4-2.el6.remi.x86_64
php-gd-5.6.4-2.el6.remi.x86_64
php-pear-1.9.5-3.el6.remi.noarch
php-ldap-5.6.4-2.el6.remi.x86_64

Open SSH
rpm -qa|grep ssh
openssh-server-5.3p1-84.1.el6.x86_64
rssh-2.3.3-2.el6.x86_64
fuse-sshfs-2.4-1.el6.x86_64
libssh2-1.4.2-1.el6.x86_64
openssh-clients-5.3p1-84.1.el6.x86_64
pdsh-rcmd-ssh-2.26-1.el6.x86_64
openssh-5.3p1-84.1.el6.x86_64

**Comment by bantu** [comment]
@gig13 Thanks. So the SFTP Server is also running CentOS 6.5 ?

**Comment by gig13** [comment]
@bantu
The external SFTP runs RHEL 6 with kernel 2.6.32-358.23.2.el6.x86_64

**Comment by bantu** [comment]
@gig13 What software is the SFTP Server using?

**Comment by bantu** [comment]
So the scenario here is something like this:
```
    Windows ownCloud Client 1.7.0 (x86)
<-> Apache mod_php5 (PHP 5.6.4) on CentOS 6.5 x86_64
<-> Unknown SFTP server software on RHEL 6 x86_64
```

**Comment by gig13** [comment]
@bantu 
The RHEL SFTP server is 
rpm -qa|grep ssh
openssh-server-5.3p1-84.1.el6.x86_64
rssh-2.3.3-2.el6.x86_64
fuse-sshfs-2.4-1.el6.x86_64
libssh2-1.4.2-1.el6.x86_64
openssh-clients-5.3p1-84.1.el6.x86_64
pdsh-rcmd-ssh-2.26-1.el6.x86_64
openssh-5.3p1-84.1.el6.x86_64

**Comment by gig13** [comment]
@bantu
In addition to file size limit, users have been observing that if the folder of an SFTP external storage consists of many files, some of the files will not show up and ownCloud client even deletes files!!!

**Comment by bantu** [comment]
@danimo FYI ^

**Comment by davleema** [comment]
I am seeing similar behavior in OC 7 and 8. When uploading large files (> 1 GB) to external SFTP storage, the resulting files appear on the external storage, but with a wrong filesize. For example, a file from 1.7 GB results in a file on the server that is only 780MB. Almost seems as if OC is doing some realtime compression or what? 
When I upload that very same file using CIFS external storage, the resulting filesize is correct.
Both OC server and external sftp server are 64-bit Linux, with plenty of free diskspace, and both ssh deamons are plain OpenSSH 6.7

**Comment by Ypnose** [comment]
Same "bug" here with OC 7.0.4. Tried to upload several times many big files on an external SFTP and the result is always the same: faulty files (size is 780,4MB).

**Comment by bantu** [comment]
@davleema @Ypnose How are you uploading ownCloud? ownCloud Client as in https://github.com/owncloud/core/issues/14406#issuecomment-75554582 ?

**Comment by davleema** [comment]
No , uploading in webinterface, using Firefox.

On March 18, 2015 1:48:32 AM CET, Andreas Fischer <notifications@github.com> wrote:
>@davleema @Ypnose How are you uploading ownCloud? ownCloud Client as in
>https://github.com/owncloud/core/issues/14406#issuecomment-75554582 ?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/owncloud/core/issues/14406#issuecomment-82658687

--

**Comment by Ypnose** [comment]
@bantu As @davleema told it, I was using the Web UI. Today, I successfully uploaded "huge" files using <code>scp</code> and <code>sftp</code>.

**Comment by PVince81** [comment]
Is this still happening on 8.1.3 or 8.2.0 ?

**Comment by gig13** [comment]
It was still happening as of 8.0.5

**Comment by bboule** [comment]
@gig13 is this still an open issue?  have we been able to test with 8.1 or 8.2?

**Comment by gig13** [comment]
Need to test with 8.1 or 8.2

**Comment by PVince81** [comment]
@gig13 Any update ? Can we close this ?
