### ISSUE TITLE
Check for output_buffering != 0/off to avoid upload problems with large files

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#14412]
output_buffering (http://php.net/manual/en/outcontrol.configuration.php#ini.output-buffering) should be 0 or Off according to:

http://doc.owncloud.org/server/8.0/admin_manual/configuration/big_file_upload_configuration.html#configuring-php

Could be useful to add a check for this to master/stable8/stable7 together with the mbstring.func_overload: https://github.com/owncloud/core/issues/14372

**Comment by LukasReschke** [comment]
I'll add an helper to check such things as stated at https://github.com/owncloud/core/issues/14372#issuecomment-75366789 - thanks @RealRancor!

**Comment by RealRancor** [comment]
PR was merged so closing.

Thanks for the fix. :+1:
