### ISSUE TITLE
Copy in the Clipboard (webdav-path's)

### ISSUE THREAD

**Issue by blackcrack** [owncloud/core#14415]
Hi,

if i on my tabled or , more heavy on my Handy, have i am en serious problem for selecting the text from the webdav-link for copy in the the clipboard , this mus work more easy, maby with an button, by side of the "Webdavlink" [copy to clibboard] into the Contacts and into the Calender., this webdav link's  i mean. Where you can klick by mouse, copy to clipboard, in Firefox, it is impossible with the fad fingers .. also with the (galaxy 10.1 Tablet and Galaxy 3S mini) Samsung Pen it is also impossible.
for this is maybe not bad an to have an Button for use the links into carddav & caldav or other applications for Android or other Pad's/Handy's

best regards
Blacky

**Comment by LukasReschke** [comment]
> Where you can klick by mouse, copy to clipboard

Not possible without Flash at the moment => Nothing we should do until somehow supported by more browsers natively.

**Comment by PVince81** [comment]
@blackcrack I am wondering: why do you need copying the WebDAV link from the files app on mobile ?
That link isn't valid for caldav/carddav anyway.

Or do you first copy the link "http://somehost/owncloud/remote.php/webdav" then manually replace "webdav" with "carddav" ?

**Comment by blackcrack** [comment]
something :  http://community.sitepoint.com/t/copy-url-to-clipboard-script/1290/2
http://vectortoons.com/product/clipboard-with-check-mark-next-to-it-black-and-white-computer-icon/
http://www.blackysgate.net/files/upload/owncloud/oc-clipboard.png
like so maybe an easy icon for make it possible to copy in the clipboard on any systems via javascript, the most browsers should support this .. like i think, but I can also  better teach let me ;)

best regards
Blacky

**Comment by PVince81** [comment]
A copy button was added for link shares using some library. This code could be reused to add a button for the Webdav link as well.

cc @DeepDiver1975
