### ISSUE TITLE
Enhanced group permission management in admin panel

### ISSUE THREAD

**Issue by biobeo** [owncloud/core#14411]
Remember facebook without privacy?

OwnCloud Dev Team really needs to develop this feature cause it's very very important.

What If I do not want to give permission to a group to create a folder in a shared folder or just in the home page (files in apps tab)

The feature should be like this:

Allow (this group) to create a folder in home page: Yes/No (this can just hide the "New" button)

Allow (this group) to create a file in home page: Yes/No

Allow (this group) to create a folder in this folder (list of folders) : Yes/No

Allow (this group) to upload a file in this folder (list of folders) : Yes/No

Allow (this group) to upload a file in home page: Yes/No

Allow (this group) to upload a file in main storage: Yes/No

Allow (this group) to upload a file in this external storage (list of external storage): Yes/No

*Allow (this group / this user) to delete any uploaded files: Yes/No

** Folders and Files can be created by Admins only: Yes/No

I hope OwnCloud Dev Team understands my problem and we will get this feature in OwnCloud 8.1

**Comment by LukasReschke** [comment]
Please refrain from using statements like "very very Important" in the title. An objective title makes handling this much easier.

That said, I added this as enhancement request, however if nobody starts doing this this is just yet another ticket here ;-)

**Comment by biobeo** [comment]
Thanks for the response. I hope you will code and implement this feature in 8.1, If you are not planning to doing this right now, I request you, please do this. It would be a great tool to manage OwnCloud a lot more easier! @LukasReschke

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/issues/4579
