### ISSUE TITLE
OC Share via email to multiple email ids returns error.

### ISSUE THREAD

**Issue by supportreq** [owncloud/core#14421]
### Steps to reproduce
1. Share a File
2. Select Share Link
3.Under Email link to a person enter two email ids separated with a comma or a semi-colon

### Expected behaviour
Email should be sent to both the users.

### Actual behaviour
Error is generated : Couldn't send mail to following users: abc@abc.com, pqr@abc.com

**Comment by schiesbn** [comment]
Currently it is only possible to enter one email address but I agree that it would be a nice improvement to allow to enter multiple addresses.

**Comment by LukasReschke** [comment]
Duplicate of https://github.com/owncloud/core/issues/1632
