### ISSUE TITLE
Debian Wheezy Upgrade issue for "owncloud-app-user-external"

### ISSUE THREAD

**Issue by DerZeitspringer** [owncloud/core#14420]
I'm running Debian Wheezy (Stable). Since last night, there's an upgrade available via APT and the OpenSuSE-Repository: owncloud-app-user-external

But, local and remote version numbers are the same ((8.0.0-5 => 8.0.0-5)), so the update is shown again and again. It seems that Apt assumes this to be a valid update because of another attribute beside version number.

```
The following packages will be upgraded:
   owncloud-app-user-external (8.0.0-5 => 8.0.0-5)
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/6,282 B of archives.
After this operation, 0 B of additional disk space will be used.
```

Best regards,
Martin

**Comment by karlitschek** [comment]
@jnweiger Can you have a look?

**Comment by jnweiger** [comment]
I've incremented the release number from 5 to 6 and pushed a small fix for ubuntu14.04 that I had ready. Normally apt just does nothing, when the build-release is identical, -- that is what I had expected. An endless-loop is not intended. Sorry for this.  

You should see 8.0.0-6 in two or three hours on the opensuse mirrors. Please let me know if the update then succeeds.

**Comment by DerZeitspringer** [comment]
Hi @jnweiger 

An overall upgrade from 8.0.0-5 to 8.0.0-6 has been published by the Apt-Repo and was installed successfully on my machine. No "loop" anymore.

Thanks for that very quick solution! :)

Best regards,
Martin

**Comment by jnweiger** [comment]
Thanks for the confirmation.
