### ISSUE TITLE
Creating new external storages broken on master

### ISSUE THREAD

**Issue by Xenopathic** [owncloud/core#14438]
After the merge of #14199, creating new external storages results in a broken `mount.json`, with `"options": "Array"` instead of an actual array containing the mount options.

No obvious log error messages

cc @LukasReschke @icewind1991

**Comment by LukasReschke** [comment]
https://github.com/owncloud/core/pull/14199/files#diff-d77412fc38a7962174493dfd1a2ecd6eR17should then probably be `(array)` instead of `(string)` - can you test that and open a PR if it works? Thanks! :smile:

**Comment by LukasReschke** [comment]
Refering to `+$options = (string)$_POST['classOptions'];`

**Comment by Xenopathic** [comment]
Yep, that's the issue
