### ISSUE TITLE
Core Javascript method to retrieve the media type icon is missing

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#14431]
There is currently no way for an app to easily get the path to the media type icon without having to talk to the server.

### Apps affected by the problem
* Search 
* Versions https://github.com/owncloud/core/issues/14106
* Media apps
* Any app which decides to be pro-active when it encounters a preview failure

### Current ways to do things
* Implement a way to retrieve either the full list or just one media type icon from within each app
* Send media type icon data whenever a preview request fails
* Copy the getMimeIcon `Files` method which may break in the future since the endpoint is within another app
* Ugly hacks which don't work #14432

### Possible solutions
* Always load the list of **supported** media types in the public OCP Javascript library and add a method to easily retrieve the icon based on the type
* Move the `File`method to the public space, including it's PHP backend. It has a caching mechanism which minimises the amount of REST requests required, but it will still be more than in the first solution.

@DeepDiver1975 - This could be one step closer to reaching that goal https://github.com/owncloud/core/pull/12546#issuecomment-73496473

**Comment by oparoz** [comment]
In Gallery+/Media, I've decided to start the app by loading an associative array `['type' => 'path/to/icon.png'] and it works quite well, but there are only a few entries in there since we don't support the full range of files which are supported by the system.

**Comment by MorrisJobke** [comment]
@oparoz Have a look at #16724 because it's merged now :)

**Comment by oparoz** [comment]
@MorrisJobke I will test as soon as I have 8.2 setup. Really great job by @rullzer :)

**Comment by PVince81** [comment]
@oparoz I guess you already have 8.2 setup by now ? :wink:

**Comment by oparoz** [comment]
I have actually implemented in Gallery already and it's available in Gallery+ V14 ;)
