### ISSUE TITLE
OC8: Undefined offset: settings.php#22

### ISSUE THREAD

**Issue by rinchen** [owncloud/core#14445]
### Steps to reproduce
 * Login to the admin panel

### Expected behaviour
 * no errors

### Actual behaviour
 * Log errors (see below)

### Server configuration
**Operating system**:
 * Ubuntu 14.04.2 LTS

**Web server:**
 * apache2 2.4.7-1ubuntu4.1

**Database:**
 * mysql 5.5.41-0ubuntu0.14.04.1

**PHP version:**
 * PHP5  5.5.9+dfsg-1ubuntu4.6

**ownCloud version:** (see ownCloud admin page)
 * 8.0.0-6

**Updated from an older ownCloud or fresh install:**
 * Updated via repo

#### ownCloud log (data/owncloud.log)
```
{"reqId":"e11b5ac2e9a0cfee9ee54f9cd2bb3dc3","remoteAddr":"67.190.60.73","app":"PHP","message":"Undefined offset: 2 at \/var\/www\/owncloud\/apps\/external\/templates\/settings.php#22","level":3,"time":"February 23, 2015 12:19:33"}
{"reqId":"e11b5ac2e9a0cfee9ee54f9cd2bb3dc3","remoteAddr":"67.190.60.73","app":"PHP","message":"Undefined offset: 2 at \/var\/www\/owncloud\/apps\/external\/templates\/settings.php#22","level":3,"time":"February 23, 2015 12:19:33"}
{"reqId":"e11b5ac2e9a0cfee9ee54f9cd2bb3dc3","remoteAddr":"67.190.60.73","app":"PHP","message":"Undefined offset: 2 at \/var\/www\/owncloud\/apps\/external\/templates\/settings.php#22","level":3,"time":"February 23, 2015 12:19:33"}
{"reqId":"e11b5ac2e9a0cfee9ee54f9cd2bb3dc3","remoteAddr":"67.190.60.73","app":"PHP","message":"Undefined offset: 2 at \/var\/www\/owncloud\/apps\/external\/templates\/settings.php#22","level":3,"time":"February 23, 2015 12:19:33"}```

**Comment by rinchen** [comment]
This issue first surfaced after the upgrade from OC7 to OC8.

**Comment by rinchen** [comment]
For clarity, this is the "External Sites" settings template.

**Comment by rinchen** [comment]
it's amazing how filing a bug report can help you self-diagnose. :-)   I thought this was in the core apps but instead it's in an add-on app.

**Comment by rinchen** [comment]
@karlitschek can you help me file this bug against the appropriate place please?  Installed version is 1.2

**Comment by karlitschek** [comment]
the external app is in the apps repository. please open the issue there: https://github.com/owncloud/apps/issues
