### ISSUE TITLE
SQL syntax error while upgrading from 7.0.4 to 8.0

### ISSUE THREAD

**Issue by nazar-pc** [owncloud/core#14448]
> An exception occurred while executing 'ALTER TABLE oc_oc_appconfig_greprkijxns9u RENAME INDEX appconfig_config_key_index TO oc_lfpvizqp0i0f3': SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'INDEX appconfig_config_key_index TO oc_lfpvizqp0i0f3' at line 1

I have MariaDB, and MariaDB 10-, MySQL 5.6 and Percona Server 5.6- all do not support `RENAME INDEX` at all!
ownCloud should generate `DROP INDEX` + `CREATE INDEX` instead.

**Comment by nazar-pc** [comment]
OK, upgrade to MariaDB 10.1 Alpha doesn't help.
This should be fixed ASAP, otherwise people stuck on upgrade.

**Comment by trampi** [comment]
Duplicate of
https://github.com/owncloud/core/issues/14003

**Comment by trampi** [comment]
@nazar-pc you could follow this guide, it worked for me on mariadb 10: https://github.com/owncloud/core/issues/14003#issuecomment-73589526

**Comment by nazar-pc** [comment]
@trampi, now I get in log file:
> {"reqId":"18bce06065411b88638400365e39f31b","remoteAddr":"172.17.42.1","app":"index","message":"Exception: {\"Message\":\"js file not found: script:js\\\/chosen\\\/chosen.jquery.min serverroot:\\\/var\\\/www\\\/owncloud\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/templatelayout.php(155): OC\\\\Template\\\\ResourceLocator->find(Array)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/templatelayout.php(106): OC_TemplateLayout::findJavascriptFiles(Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template.php(118): OC_TemplateLayout->__construct('guest', '')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template\\\/base.php(103): OC_Template->fetchPage()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template.php(197): OC\\\\Template\\\\Base->printPage()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/util.php(827): OC_Template::printGuestPage('', 'login', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(866): OC_Util::displayLoginPage(Array, Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\
/lib\\\/base.php(821): OC::handleLogin()\\n#8 \\\/var\\\/www\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template\\\/resourcelocator.php\",\"Line\":46}","level":4,"time":"2015-02-24T10:10:17+00:00"}
{"reqId":"18bce06065411b88638400365e39f31b","remoteAddr":"172.17.42.1","app":"PHP","message":"js file not found: script:js\/chosen\/chosen.jquery.min serverroot:\/var\/www\/owncloud at \/var\/www\/owncloud\/lib\/private\/template\/resourcelocator.php#46","level":3,"time":"2015-02-24T10:10:17+00:00"}


Blank page with 500 status code

**Comment by DeepDiver1975** [comment]
@nazar-pc please disable calendar and/or contacts - these apps need to be upgraded before being enabled again.

**Comment by nazar-pc** [comment]
@DeepDiver1975, thanks, I found that files_mv caused problems, thanks!
