### ISSUE TITLE
Membership of multiple groups - multiple same shares

### ISSUE THREAD

**Issue by j4mb4l4j4** [owncloud/core#14447]
Like in my post: https://forum.owncloud.org/viewtopic.php?f=29&t=26672&p=80453#p80453
, I have the following issue/bug ?

When I have the user "marketing" and the is in the group marketing, I can share my "documents" Folder to marketing. But when I put user marketing also in the group "sales" and I share "documents" to sales, I have the problem , that the user "marketing" has to shares with the name "documents" and document(02) or document(01)"

Before 7 there was the shared folder, but regarding to https://owncloud.org/blog/owncloud-7-sneak-peek-more-sharing/ there is no such folder anymore.

Can I share one folder to multiple groups by with avoiding this problem ?

Is there like a best practice how to share folder to multiple groups, without having multiple shares for the user who are in more groups who get the share ?

How did you solved this problem ?

**Comment by karlitschek** [comment]
Not sure I understand. File name collision could happen before 7 and can happen after 7 too. The behavior that we automatically add a (1) is exactly the same. Unfortunately there is nothing that can be done to prevent this.
