### ISSUE TITLE
Download Counter

### ISSUE THREAD

**Issue by biobeo** [owncloud/core#14446]
Please add a download counter that how many times the file has been downloaded in public.php

**Comment by MegaV0lt** [comment]
Agree, that would be a nice feature.

**Comment by JimLoose** [comment]
:-1: 
sound more like a plugin request not a default feature! :-)

**Comment by GreatEmerald** [comment]
To me it sounds like it should be a default feature. For one, it's a pretty standard feature on may file hosting services; for another, it's pretty trivial functionality, and using third party plugins for that is not really optimal when it comes to both maintainability and security. The apps that did provide such a feature would usually not allow seeing the statistic at a glance, and now all of them are deprecated altogether as far as I can see.

**Comment by rienesl** [comment]
Currently I'm searching for exact that solution. I'm sharing files and I don't know, if they have been downloaded already. OK, if you share one single file to a single person, this should be no problem, you can simply ask. But if you got several files with several people, it becomes a bit complicated...

**Comment by MTRichards** [comment]
How would you want this to appear in the default files view? 
We may not actually know if a download has been successful, just that the bytes have left the server - we don't know if they arrived at the client or if the file was assembled, and there are two code paths - webdav (clients and mobile apps) and web. 
What count do you want here? Do you count your own downloads, or only shared downloads? What about shares you do not own but are shared with you?

**Comment by GreatEmerald** [comment]
My thinking was that if the file is shared via link, it would tell you how many times the link was accessed. I think that's a pretty straight-forward way of counting it.

**Comment by rienesl** [comment]
I would totally agree to the solution GreatEmerald suggested: By the way, I guess, this is like all the counters in the web work - they are not counting a download successful or not, they simply count how often a link was accessed

**Comment by MTRichards** [comment]
I think that is a good way to count - access is ok for me, and a close proxy for downloads. What about where it might appear? This can start to clutter things with not so useful bits of information, so maybe an addition to the share link view, as an option the admin can set?

**Comment by MTRichards** [comment]
Trying for 9.0. Will see if it stays in.

**Comment by MTRichards** [comment]
Also note, this should display in the activity feed for the file - and since activity feed for the file is not on a per file basis, that could meet this need.

**Comment by MTRichards** [comment]
Ok, this is likely not going to make 9.0, unless we have additional folks to help. I know this is small, but it is not on the list. I assigned it to 9.1 for consideration.

**Comment by MTRichards** [comment]
@bboule @butonic your call on importance and if it can be done outside for 9.0.

**Comment by bleed2002** [comment]
Thanks for accepting this subject! From a sales point of view this is actually an important feature and often one of the first questions asked by prospective customers is something like: "And where can I see how often/when/by whom a file was downloaded..". A lot of users (including myself) would be very happy if this would make it into owncloud core soon!

**Comment by PVince81** [comment]
A counter could be implemented as an app once a hook is in place. Note that counting downloads has many shortcomings because opening a file for preview could count as download too.

Go to https://github.com/owncloud/core/issues/13158 for further discussion about the hook and download detection mechanism.
