### ISSUE TITLE
Initial setup broken with Doctrine DBAL 2.5.1 (future issue)

### ISSUE THREAD

**Issue by AdamWill** [owncloud/core#14444]
OC still uses DBAL 2.5.1, but for Fedora packaging purposes I've been testing 8.0.0 with DBAL 2.5.1. It breaks on initial setup (at least with sqlite database it does, I haven't tried with the other types yet).

ownCloud reports "Error while trying to create admin user: An index with name 'keyid_index' was already defined on table 'oc_privatedata'."

this is an `indexAlreadyExists()` exception from DBAL. I isolated the change in DBAL that causes this:

https://github.com/doctrine/dbal/commit/32ab659628b9abe2c6f66b6c2dc6239027148d6d

partially reverting that change fixes the problem. Upstream documents this as a 'minor BC break' at https://github.com/doctrine/dbal/blob/v2.5.1/UPGRADE.md .

**Comment by LukasReschke** [comment]
Please try https://github.com/owncloud/core/pull/14119

**Comment by AdamWill** [comment]
oh, I missed that - thanks.
