### ISSUE TITLE
[Share api] The path of a renamed shared folder also shared by link is not correct

### ISSUE THREAD

**Issue by purigarcia** [owncloud/core#14450]
### Steps to reproduce
1. In the web, login as user1
2. Share a folder “a” with user2
3. In the web, login as user2
4. Rename “a” as “a modified”
5. Select to share by link
6. In the share api, the path return is not correct so in the movile device this file is not shown as shared by link.
It’s possible to cheek using Poster (firefox complement)
	- Url: server/ocs/v1.php/apps/files_sharing/api/v1/shares
	- user2/password2
 	- Click on GET
	This is the path that is returned
	<path>/a modified/a</path>

### Expected behavior
In the share api, the path given should be <path>/a modified</path>

### Actual behavior
In the share api, the path given is <path>/a modified/a</path>

### Client configuration
Operating system: MacOs 10.7.5
Web server: Firefox, Chrome
Owncloud version: {"installed":"true","version":"7.0.5.0","versionstring":"7.0.5 RC1","edition":"enterprise"}

**Comment by DeepDiver1975** [comment]
@nickvergessen mind taking a quick look? THX

**Comment by DeepDiver1975** [comment]
@purigarcia is the same behavior observable with 6.0.x, 7.0.4 and 8.0.0?

**Comment by rullzer** [comment]
I just checked and this does not happen on master.

**Comment by PVince81** [comment]
@purigarcia are you still seeing this in 7.0.7, 8.0.5 ?

**Comment by purigarcia** [comment]
@davitol could you check it? Thanks

**Comment by davitol** [comment]
:+1: Tested un 7.0.7 and 8.0.5 using curl and it works, tested with a mobile app too, worked as expected :) .
