### ISSUE TITLE
Could not delete files via web - owncloud8

### ISSUE THREAD

**Issue by tompizmor** [owncloud/core#14453]
Hello, It is not possible to delete files via web interface on windows server. It seems an error with the mappedlocal.php script and the path routes. This issue has already been posted at:
https://forum.owncloud.org/viewtopic.php?f=31&t=26421

A user have found a workaround using the mappedlocal.php script from previous version.
Thanks!

**Comment by DeepDiver1975** [comment]
@nickvergessen duplicate? THX

**Comment by nickvergessen** [comment]
Will check later when I create the ticket collection

**Comment by oresch** [comment]
I got the same issue: fresh installation ($OC_Version = array(8,0,0,7);) on a Centos 7 machine. 
The main subfolder can be deleted (dustbin icon is shown), but files and folders inside cannot.
I changed the "mappedlocal.php" as mentioned in the posting above without success.

Info filesystem (zfs): -rwxrwxr-x.  1 apache apache <filenam>

Maybe this can help?

**Comment by nickvergessen** [comment]
if it happens for you on CentOS please create another issue, because that uses totally different code then windows.

**Comment by nickvergessen** [comment]
See #14513 - Closing as duplicate
