### ISSUE TITLE
[dev-productivity] Get rid of 3rdparty submodule

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#14454]
We are again in the situation where updating multiple 3rdparty libs causes major headaches just because of the merge order.

## Problem
Because we have to synchronize two pull requests on two repos the merge order is critical.
As soon as one pr in 3rdparty is merged all 3rdparty prs have to be updated/rebased and all related prs in core have to be rebased.

This is simply tooo time consuming and too fault tolerant.

## Proposal

- Move 3rdparty folder inside core
- Keep all libs within core
- Use composer to update and to generate the autoloader
- Add comments to README on how to properly upgrade
- Add comments to README regarding contribution agreement and legal impact

@karlitschek @LukasReschke @PVince81 @icewind1991 @nickvergessen Comments please

**Comment by nickvergessen** [comment]
:+1:

**Comment by LukasReschke** [comment]
Agreed - keeping the libs somewhere (as I understand we would keep them in the core repo now) is anyways still something we should do from a security PoV as composer does not yet understand package signing and such fun.

:+1: from my side.

**Comment by PVince81** [comment]
Can we have a "bootstrap.sh" script or something that will automatically pull composer.phar and run composer + bower ? My worry is mostly about the barrier of entry for newcomers.

**Comment by DeepDiver1975** [comment]
with the approach discussed here - composer and bower are only needed once a dependency has to be updated - all libs will be within git

**Comment by PVince81** [comment]
Ok, makes sense then.

**Comment by icewind1991** [comment]
:+1: 3rdparty PRs are a pain atm

**Comment by karlitschek** [comment]
needs to be discussed and the legal implications needs to be checked. please hold your horses guys

**Comment by DeepDiver1975** [comment]
> needs to be discussed and the legal implications needs to be checked. please hold your horses guys

sure - but if we have a pain - we need to talk about it - THX

**Comment by th3fallen** [comment]
this would be FANTASTIC although i am opposed to storing all the composer deps in the git repo (its completely unnecessary imho) but this would none the less be a great first step.

**Comment by oparoz** [comment]
I agree with @th3fallen. Provide composer.json so that people who wish to introduce new libraries in their PR can easily do so, but let bots and devs update their environment via a script, as @PVince81 has suggested.

Having to sync PRs is a pain. I wasn't able to test one of mine simply because I have no idea how we're supposed to manage those.

**Comment by th3fallen** [comment]
may be a topic for @cmonteroluque Too.

**Comment by PVince81** [comment]
Moving this big topic to 9.0 as we're past feature freeze

**Comment by DeepDiver1975** [comment]
I guess there will be not much movement in this area -> close
