### ISSUE TITLE
Share owner avatar position

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#14457]
@owncloud/designers @rullzer shouldn't the avatar rather be left or was it decided to have it right on purpose ? Or a bug ?

![share_owner_avatar](https://cloud.githubusercontent.com/assets/277525/6348419/bd8032e6-bc1f-11e4-8ec7-3d7c146bb47f.png)

**Comment by PVince81** [comment]
Also there's an empty space when sharing with groups, is it ok ?

**Comment by rullzer** [comment]
@PVince81 mmm on the right makes more sense indeed. I'm not sure why I did not put it there in the first place.

Aaah yes the spacing... It indeed looks weird now... It is there so they align better if you have it shared with a user. Should also be fixable. I'll have a look later.

**Comment by jancborchardt** [comment]
@rullzer no, the avatar should always be on the left of the name. Here the placeholder of »root« is placed wrongly.

And yeah, we should show a group-icon after all for groups. Then it will look less strangely indented when you only shared with a group.

**Comment by rullzer** [comment]
Ah sorry typo. I meant on the left.

**Comment by rullzer** [comment]
I have a branch where the avatar is to the left (trivial fix).
I still need to look into the avatars for groups and remote users... since there are a lot of edge cases. 

I'll keep you up to date..

**Comment by jancborchardt** [comment]
@rullzer great stuff, thank you! :)

**Comment by PVince81** [comment]
We might need an icon/avatar as well for server to server shares (aka ownCloud federation):
There's currently an empty space there as well. (AFAIK we currently cannot download avatars from a remote server)

**Comment by jancborchardt** [comment]
Would be awesome if we can then. :) At least for people whom you already shared with in the past.

**Comment by PVince81** [comment]
Probably not in this ticket. I raised this one for that: https://github.com/owncloud/core/issues/14564

**Comment by jancborchardt** [comment]
Great stuff, thanks!

**Comment by nickvergessen** [comment]
Could put it directly infront of the user/group name, just like the activity app does?

![bildschirmfoto vom 2015-03-02 17 15 00](https://cloud.githubusercontent.com/assets/213943/6444771/f44b6dc4-c0ff-11e4-85d5-8c819f5cff32.png)
