### ISSUE TITLE
Support for read-only config dir

### ISSUE THREAD

**Issue by Equidamoid** [owncloud/core#14455]
This request comes from #14451.

OwnCloud requires /config dir to be writeable by webserver. This can be a potential security issue. It would be nice to have all the setup read-only.

**Comment by LukasReschke** [comment]
Related https://github.com/owncloud/core/issues/11843

**Comment by orzel** [comment]
Moreover, you get absolutely no error message when it's so. The PHP backtrace in log is all but helpful about finding that the original problem is that config.php (or the config/ directory) is not writable.

**Comment by LukasReschke** [comment]
Please test https://github.com/owncloud/core/pull/21060
