### ISSUE TITLE
[UX/Performance] Use direct download link for federated cloud sharing

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#14452]
Desktop client 1.8 is capable of direct download.

In case a requested file is shared via cloud federation the direct download link shall contain the remote url.

This has to be tested with respect to credential transmission.

@dragotin FYI

**Comment by DeepDiver1975** [comment]
something we can take care of for 8.2 form my understanding

**Comment by PVince81** [comment]
I guess it's related to the "oc:downloadURL" property ?

**Comment by DeepDiver1975** [comment]
yes

**Comment by PVince81** [comment]
This enhancement makes sense. However: good luck when the share is done through 2-3 servers :wink:

**Comment by DeepDiver1975** [comment]
even this should be possible - it's all webdav and the direct download url is available - but still has to be tested

**Comment by PVince81** [comment]
Yeah, in that case it means the OC instances need to cache the download URLs from the other OCs after querying them. This is assuming that the downloadURL is not predictable.
If we assume that the format of the download URL is always the same / consistent, then we can do that.

**Comment by PVince81** [comment]
With flat reshares the problem would be less complicated and in case the download link is broken, the desktop client should fall back to regular download in case the link is not accessible due to firewall restrictions.

**Comment by PVince81** [comment]
The download URL shall be a Webdav URL to avoid going through the usual web UI download hooks which would trigger activities.
