### ISSUE TITLE
[7.0.3] Apache hangs while creating a over the Web-interface

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#14464]
We have problem with application "Text Editor" hangs when we try to save the new file with text on the page. 

I have to restart Apache!!

### Steps to reproduce
1. Create file - is ok
2. Write some text - is ok
3. Save - hangs

### System Configuration:
"ownCloud version": "7.0.3.4",
"ownCloud version string": "7.0.3",
"webserver version": "Apache\/2.2.15 (SLES Expanded Support)",
"PHP Version": "5.4.34",
"MySQL": "5.1.73",

### Installed Apps
"Activity" true
"Antivirus App for files" true
"Deleted files" true
"Encryption" true
"Enterprise License Key" true
"Export/import" true
"Export/import for users" true
"File Firewall" true
"File Locking" true
"File Shared access logging app" true
"First Run Wizard" true
"LDAP user and group backend" true
"Log audit info" true
"Mail Template Editor" true
"ownCloud dependencies info" true
"PDF Viewer" true
"Pictures" true
"Provisioning API" true
"Share Files" true
"Text Editor" true
"Versions" true
"External Sites" false
"External storage support" false
"External user support" false
"LDAP Home Connector" false
"SharePoint" false
"Shibboleth user backend" false
"WebDAV user backend" false
"Windows Network Drive" false

### Logs
create file
```
{"app":"admin_audit","message":"Create \"\/USER_NAME\/files\/test.txt\" by user USER_NAME, owner: USER_NAME","level":1,"time":"February 23, 2015 13:20:49"}
{"app":"admin_audit","message":"Write \"\/USER_NAME\/files\/test.txt\" by user USER_NAME, owner: USER_NAME","level":1,"time":"February 23, 2015 13:20:49"}
{"app":"admin_audit","message":"Read \"\/USER_NAME\/files\/test.txt\" by user USER_NAME, owner: USER_NAME","level":1,"time":"February 23, 2015 13:20:51"}
{"app":"admin_audit","message":"Read \"\/USER_NAME\/files\/test.txt\" by user USER_NAME, owner: USER_NAME","level":1,"time":"February 23, 2015 13:20:53"}
{"app":"admin_audit","message":"Write \"\/USER_NAME\/files\/test.txt\" by user USER_NAME, owner: USER_NAME","level":1,"time":"February 23, 2015 13:21:07"}
```

deleted file
```
{"app":"admin_audit","message":"Read \"\/USER_NAME\/files\/test.txt\" by user USER_NAME, owner: USER_NAME","level":1,"time":"February 23, 2015 13:23:56"}
{"app":"admin_audit","message":"Delete \"\/USER_NAME\/files\/test.txt\" by user USER_NAME, owner: USER_NAME","level":1,"time":"February 23, 2015 13:25:07"}
{"app":"PHP","message":"unlink(\/USER_NAME\/files_encryption\/share-keys\/test.txt.recovery_2978e250.shareKey): No such file or directory at \/var\/www\/html\/owncloud-enterprise\/apps\/files_trashbin\/lib\/trashbin.php#305","level":3,"time":"February 23, 2015 13:25:07"}
```
Apache Error Log
```
[Mon Feb 23 13:23:38 2015] [notice] caught SIGTERM, shutting down
[Mon Feb 23 13:23:38 2015] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Mon Feb 23 13:23:39 2015] [warn] Init: Session Cache is not configured [hint: SSLSessionCache]
[Mon Feb 23 13:23:39 2015] [notice] Digest: generating secret for digest authentication ...
[Mon Feb 23 13:23:39 2015] [notice] Digest: done
[Mon Feb 23 13:23:39 2015] [notice] Apache/2.2.15 (Unix) DAV/2 mod_ssl/2.2.15 OpenSSL/1.0.1e-fips PHP/5.4.34 configured -- resuming normal operations
```
@MorrisJobke 

00002636

**Comment by DeepDiver1975** [comment]
Anything in the browser logs?

**Comment by DeepDiver1975** [comment]
Screenshot of network tab might be interesting as well

**Comment by DeepDiver1975** [comment]
@cdamken is this reproducible?

**Comment by cdamken** [comment]
@DeepDiver1975 I couldn't reproduce in my environment :crying_cat_face: 

I'll asked for the other blogs. I will post them soon. Thanks.

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 I couldn't reproduce in my environment :crying_cat_face:

not reproducible -> pechi-pechi :speak_no_evil:

**Comment by DeepDiver1975** [comment]
> I'll asked for the other blogs. I will post them soon. Thanks.

blogs? :wink:

**Comment by hodyroff** [comment]
From the customer:
"Steps that was taken
Turn off "Encryption0.6.1."
Decrypt the files, 
Removal keys
Turn on Encryption app problem persists.   
We must recovery system OC. 
Application "Encryption0.6.1." not work ok. This is really a big problem.
"
Same (not working with encryption combined) is reported for the pdfviewer app.

Is there a compatibility issue with these webapps and encryption?

**Comment by michaelstingl** [comment]
@DeepDiver1975 @hodyroff detailed steps:

Steps was taken

1. create new database
2. create new configuration Owncloud 
3. disable selinux
4. disable firewall
3. Turn on Encryption 0.6.1.
4. hangs on first logon and user encryption
5. system crash on saving the file txt
6. again turn off Encryption 0.6.1. 
7. possible save a txt file
8. Turn on Encryption system crash on saving the file txt
9. Al previously worked correctly!!!
10. I can't implement the system

I don't install pdf_viewer just clean system OC 7.03

@MorrisJobke can you reproduce this?

Please also check the following files (S3-ownCloud/Shared/owncloud/support/github-issues/core/14464):
- Consol Firefox.txt
- Debugger Firefox.txt
- Log ownCloud.txt

**Comment by cdamken** [comment]
@hodyroff 

>Same (not working with encryption combined) is reported for the pdfviewer app.

That is because the package from oC7.0.3. This is something different

**Comment by cdamken** [comment]
Upgrade to 7.0.5 fixed the problem. Thanks guys
