### ISSUE TITLE
OC 8 + HTTP Basic Auth + File upload =  "Token expired, please reload page" Re-Appeared!!

### ISSUE THREAD

**Issue by t0mcat1337** [owncloud/core#14469]
Hi everybody,

just updated to the last stable OC 8 and this Bug from OC 6.x / OC7.0.x reappeared:

1.) After logging in with Apache's Basic Auth the user is correctly logged in to OC
2.) Uploading a file fails, the progress bar completely gets filled but then this message appears:
"Token expired, please reload page"
and the file isn't there.

Exactly the same behaviour was described in 

https://github.com/owncloud/core/issues/4574
and
https://github.com/owncloud/core/pull/7852

In OC6/7.0x the solution from https://github.com/owncloud/core/issues/4574 always worked. But as the code structure has heavily changed I coultn't find the correct file / line to try, if this still would work.

Any hints?

Thx in advance!

**Comment by LukasReschke** [comment]
Where do you authenticate against? Which endpoint? If you take a look at the source to you see something like `data-requesttoken` and does it has a value?

**Comment by t0mcat1337** [comment]
Just at this moment I found the line:

lib/base.php:

if (!self::checkUpgrade(false)
                        && !$systemConfig->getValue('maintenance', false)
                        && !\OCP\Util::needUpgrade()) {
                        // For logged-in users: Load everything
                        if(OC_User::isLoggedIn()) { <------------------ ??
                                OC_App::loadApps();
                        } else {
                                // For guests: Load only authentication, filesystem and logging
                                OC_App::loadApps(array('authentication'));
                                OC_App::loadApps(array('filesystem', 'logging'));
                                if (!OC_User::isLoggedIn()) { <------------------------------ HERE-------------------
                                        \OC_User::tryBasicAuthLogin();
                                } <----------------------HERE ----------------------------------
                        }
                }

When inserting the "HERE" lines, file uploading works... when deleting them again (as is in origin) the error appears.... 
But I don't really understand why this works as "OC_User::isLoggedIn" is already checked in the former outer if.... (the Line wirh "??")

Anyway... with this little hack, everything works again...

**Comment by t0mcat1337** [comment]
@LukasReschke : Just now saw your answer... The HTTP Basic Auth is against LDAP, the same one, which is configured in OC8

**Comment by t0mcat1337** [comment]
Yes, there is a "data-requesttoken" in the "<head...>" element and it has a value... doesn't matter, if the lines are inserted to lib/base.php or not...

**Comment by LukasReschke** [comment]
Against which endpoint are you authenticating? – How does the login request look like?

**Comment by t0mcat1337** [comment]
what do u mean with "endpoint"?

**Comment by LukasReschke** [comment]
How do you login? What are the exact steps that you follow to authenticate?

**Comment by t0mcat1337** [comment]
1.) Enter the URL
2.) The HTTP Basic Auth window appears (as the Apache is configured to use HTTP Basic Auth for this URL)
3.) Enter my credentials as needed to authenticate against the LDAP Backend
4.) OC8 opens with the correct user

**Comment by LukasReschke** [comment]
@blizzz When looking at the custom patch in https://github.com/owncloud/core/issues/14469#issuecomment-75786846 it looks to me like LDAP is not yet initialized in that state and thus it does not work? - Would it make sense to initialize the `authentication` apps before somewhere?

**Comment by t0mcat1337** [comment]
Found this out:
WITHOUT my changes in lib/base.php:
1.) Open OC8 -> requesttoken is, lets say "AAAAAAA"
2.) Change Directory by clicking on it -> requesttoken changes to, lets say "BBBBBBBB"

WITH my changes:
1.) Open OC8 -> requesttoken is, lets say "AAAAAAA"
2.) Change Directory by clicking on it -> requesttoken remains "AAAAAAA"

So it seems, WITHOUT my changes, the requesttoken is renewed at each and every request even it is in the same session. This explains, why the upload fails, as the AJAX request for the upload includes the first token (to stay with the first example: "AAAAAA", checked that in Firebug), whereas the new token "BBBBBB" is the valid one...

**Comment by blizzz** [comment]
@LukasReschke OC_User::isLoggedIn() does not interact with  user backends, only with the user session (which checks $_SESSION).

**Comment by LukasReschke** [comment]
Sure. But it does also a query to `\OC_User::userExists` – let me try to get some LDAP setup again and verify this.

**Comment by blizzz** [comment]
@LukasReschke oh, i have seen that spot. This explains why it works. Then yes, we'd need to load auth-apps earlier.

**Comment by LukasReschke** [comment]
In earlier versions we loaded the apps already there: https://github.com/owncloud/core/blob/87345f80ea6063ce0e09539621457c4ba1998fb4/lib/private/user.php#L328 *sigh*

**Comment by LukasReschke** [comment]
Let me put it somewhere on top of base.php – I doubt that there are cases where it is uneeded?

**Comment by blizzz** [comment]
Public (guest) pages?

**Comment by LukasReschke** [comment]
I think even then it makes sense to load them in case user list has to get loaded somehow?

**Comment by blizzz** [comment]
I doubt… But  you never know. We'd be on the safe side.

**Comment by t0mcat1337** [comment]
Did a quick test with @LukasReschke 's comment about this: https://github.com/owncloud/core/blob/87345f80ea6063ce0e09539621457c4ba1998fb4/lib/private/user.php#L328

I added these "HERE" lines to lib/private/user.php:

        public static function isLoggedIn() {
                if (\OC::$server->getSession()->get('user_id') !== null && self::$incognitoMode === false) {
                        OC_App::loadApps(array('authentication')); <--------------------------- HERE
                        self::setupBackends(); <------------------------- HERE
                        return self::userExists(\OC::$server->getSession()->get('user_id'));
                }

                return false;
        }

 as it obviously was in the earlier version.

Then I reverted my change to "lib/base.php" so it is the original one now

Witht that file uploading works, too

**Comment by blizzz** [comment]
Thanks for veryfying @t0mcat1337

**Comment by LukasReschke** [comment]
I created a somewhat cleaner patch in https://github.com/owncloud/core/pull/14471 - @t0mcat1337 could you test this and report back whether it works on the PR as well?

**Comment by t0mcat1337** [comment]
And what was to expect... the requesttoken remains the same in all requests, too...

**Comment by t0mcat1337** [comment]
@LukasReschke : As I have to leave work now I can test the patch during the next few hours... anyway thx a lot for this REALLY quick assistance ;)

**Comment by LukasReschke** [comment]
Sure. Thanks for testing and reporting issues back and your investigation (especially that you tried some patches yourself, that is far more than the usual bug reporter does). Helped a lot to understand the issue :smile: 

If you stumble upon any other bug please don't hesitate to file an issue. (though this is authentication related and more urgent than some little tiny nitpick :))

**Comment by LukasReschke** [comment]
Patch will be include within 8.0.1 - thanks for reporting issues back.
