### ISSUE TITLE
[Documentation] LDAP documentation doesn't say LDAP will be accessed read-only

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#14466]
@carlaschroder I've checked with @blizzz that LDAP will be accessed "read-only" from ownCloud. This means that some operations over the users such as delete them won't be possible (which makes sense).

I've been browsing the documentation (mainly for 7.0) and I haven't seen anything mentioning this. Could you add it?

Thanks!

**Comment by RealRancor** [comment]
Hi,

the issue tracker for the documentation is located here:

https://github.com/owncloud/documentation/issues

**Comment by DeepDiver1975** [comment]
thx @RealRancor 

@jvillafanez please open issues in the documents repo
