### ISSUE TITLE
onedrive support for external storage

### ISSUE THREAD

**Issue by karlitschek** [owncloud/core#14478]
Microsoft published theri new API for onedrive. So we could support it in external storage at one point of time.
http://onedrive.github.io/index.htm

**Comment by enoch85** [comment]
Yes please!

**Comment by DeepDiver1975** [comment]
This will be lesser fun to implement/install - each app requires installation and authentication is done via OAuth. 

Will almost work the same way as out Google and DropBox integration.

Well .. if anybody is interested ... as an isolated app - why not

**Comment by DavidDohmen** [comment]
Yes Please! So many people have an Office 365 subscription including a free onedrive terabyte...

**Comment by gig13** [comment]
@MTRichards @bboule

**Comment by ncl2fth** [comment]
Would love to see this feature to incorporate 1TB cloud into my owncloud.

**Comment by ovidiub13** [comment]
+1

**Comment by fstackdev** [comment]
+1

**Comment by DeepDiver1975** [comment]
Feature request is open - it might come one day or not. Issue locked to prevent further distraction due to +1

THX

**Comment by bboule** [comment]
@MTRichards this is a feature request for consideration

**Comment by MTRichards** [comment]
Needs a SF ticket please, so it doesn't get lost.

**Comment by bboule** [comment]
@gig13 can you open in SF?

**Comment by gig13** [comment]
@MTRichards @bboule    I reopened SF 00003068

**Comment by gig13** [comment]
@bboule To close SF since this is not moving...

**Comment by cdamken** [comment]
@pmaier1 FYI
