### ISSUE TITLE
http request which are received from non-browser clients the http header accept-header has to be evaluated

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#14470]
Especially for request by the desktop and mobile client the language to be used for e.g. error messages has to be taken from the http request header Accept-Language.

**Comment by PVince81** [comment]
Fixed by your commit ? (I somehow cannot find the matching PR)

**Comment by DeepDiver1975** [comment]
fixed by https://github.com/owncloud/core/pull/14346
