### ISSUE TITLE
Difficult to run unit tests for files_external

### ISSUE THREAD

**Issue by Xenopathic** [owncloud/core#14486]
We have `autotest-external.sh`, which is great for running the backend unit tests against docker containers, but there is no way to easily run the standard files_external unit tests in `apps/files_external/tests/*.php`. These tests don't need any backends to work. The @PVince81 sanctioned way of doing it is to enable files_external in `tests/enable_all.php`, but this seems messy to be doing every time one wants to run those unit tests.

Perhaps we should be running those unit tests as part of CI anyway? As stated before, they don't need any working backends, but just test the common parts of files_external.

cc @DeepDiver1975 @MorrisJobke @PVince81 @icewind1991

**Comment by MorrisJobke** [comment]
They are run with autotest-external.sh before the docker container based tests are executed.

**Comment by MorrisJobke** [comment]
Just noticed, that I commented them out before, but then missed to remove the comment. I will supply a fix.

**Comment by MorrisJobke** [comment]
#14535
