### ISSUE TITLE
LDAP user ownCloud data is deleted even though the user still exists in the LDAP server

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#14489]
### Steps to reproduce
1. Create a valid LDAP configuration
2. With one of the LDAP user, upload some files to his account
3. Delete the LDAP configuration
4. From the CLI, check that the user isn't available `./occ ldap:check-user --force <user-id>`
5. Create the same LDAP configuration as the step 1. This should connect to the same LDAP server with the same filters.
6. Try to delete the user from the CLI with the `./occ user:delete <user-id>` command
### Expected behaviour

The user is still available in the LDAP server, so if under normal circumstances it isn't possible to delete the user data in ownCloud, it shouldn't be possible in this case.
### Actual behaviour

The user data in ownCloud is deleted
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 7.0.5

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by karlitschek** [comment]
@blizzz What do you think?

**Comment by blizzz** [comment]
Known. Re-evaluating users that have been found as deleted is not implemented yet (as discussed) and was not given priority.

**Comment by blizzz** [comment]
Might be fixed with https://github.com/owncloud/core/pull/20192, but you'd need to run the ./occ ``ldap:check-user --force <user-id>`` check again, before attempting to delete. After all, the admin might want to reset an existing user. So far flagging him as deleted is the workaround for it.  @jvillafanez could you retry?

**Comment by jvillafanez** [comment]
Checked in stable9 ownCloud 9.0.2 (daily) Build:2016-05-11T03:02:54+00:00 a3bdcfbb90494b7fefa7c8c39c092a8aef9bfce1 : looks good. The only minor thing is the misleading error message when trying to delete the user:

```
The specified user could not be deleted. Please check the logs.
```

It's true the user shouldn't be deleted because the user still exists, but there is no info in the logs regarding this.

Otherwise 👍

**Comment by blizzz** [comment]
@jvillafanez thanks :) So, just some additional log output is necessary.

**Comment by PVince81** [comment]
Likely obsoleted by user:sync behavior, closing.

Please reopen in user_ldap repo if issue still valid.
