### ISSUE TITLE
occ user:delete command for LDAP requires a valid configuration

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#14487]
### Steps to reproduce
1. Create a valid LDAP configuration with several LDAP users
2. Enter to ownCloud with one of the LDAP users and upload some files
3. Logout and go back to the admin user to delete the LDAP configuration
4. Check that the user isn't available any longer `./occ ldap:check-user --force <user-id>`
5. Try to delete the user with the user:delete command

### Expected behaviour
The ownCloud data for the user is deleted

### Actual behaviour
Cannot delete the user data in ownCloud

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 7.0.5

**Updated from an older ownCloud or fresh install:** fresh install

### Notes
Looks like a valid LDAP configuration is needed to delete the user data

**Comment by karlitschek** [comment]
@blizzz

**Comment by DeepDiver1975** [comment]
I'd say this works as designed - if there is no valid ldap config we have no idea if that user is/was an ldap user. Deleting any *random* user directory with by accident matches is rather critical.

I vote for "Won't fix"
