### ISSUE TITLE
Nginx config does not work

### ISSUE THREAD

**Issue by dreh23** [owncloud/core#14482]
I had the exact same problem in owncloud 8.0.0-6 described in Bug [
#9143](https://github.com/owncloud/core/issues/9143) Switching the caching block with the php block solved this. This should be documented somewhere.

**Comment by RealRancor** [comment]
Hi,

it is indirectly documented in NginX config here:

https://doc.owncloud.org/server/8.0/admin_manual/installation/nginx_configuration.html
