### ISSUE TITLE
Propose to reinstall third party apps after an upgrade

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#14485]
As per https://github.com/owncloud/core/pull/14282 third party apps will be disabled.
Also some people who use the tarballs follow the instructions that ask to delete everything but "config" and "data", which means that third party apps will be deleted too.

Here is a proposal to make it easier to reinstall those missing apps after an upgrade.

Whenever the code of apps is deleted, the database still contains the apps' entries in "oc_appconfig".
After a successful update, the admin can be prompted (for example on the "Apps" page) to reinstall these apps with a link/notification "reinstall apps". The list will be read from the database and the apps will be re-downloaded or re-enabled (in the case of disabled third party apps).

One possible issue is that some older deleted apps might still have entries in "oc_appconfig", so this probably need a way to distinguish apps that were deleted/disabled due to an upgrade from old apps.

@DeepDiver1975

**Comment by PVince81** [comment]
@owncloud/designers

**Comment by RealRancor** [comment]
Hi,

correct me if i'm wrong but this will also install incompatible apps as those don't have a max version?

**Comment by karlitschek** [comment]
Hmm. I agree with @RealRancor Not sure. Maybe this reintroduces the same problem again when incompatible apps are automatically enabled again after upgrade.

**Comment by PVince81** [comment]
Hmmm.. right... incompatible as "app says it works for OC > 8" but in fact it doesn't.
It would almost need to "carefully" automatically enable the app, and if it crashes, disable again, which is not technically possible.

I hope one day we find a way to "scaffold" apps in a way that we can make them fail controllably.

**Comment by RealRancor** [comment]
> Hmmm.. right... incompatible as "app says it works for OC > 8" but in fact it doesn't.

Yes, thats what i thought.

If all apps are providing the correct min and max version it shouldn't be a problem but i don't know how realistic this is.

**Comment by DeepDiver1975** [comment]
> If all apps are providing the correct min and max version it shouldn't be a problem but i don't know how realistic this is.

we could auto-max-version an app after installation to the current server major release

**Comment by PVince81** [comment]
Or make "requiremax" a required field. Maybe some devs will put a value like "99" in there but reasonable devs should put the tested version.

But this also means excluding unmaintained apps that **might** still work in the newer version but are untested.

**Comment by jancborchardt** [comment]
This is difficult to do automatically. Before a release we need to coordinate with app developers to let them know to test with the new ownCloud version, check to make their apps compatible, and update the version compatibility in the app store.

**Comment by PVince81** [comment]
obsoleted by market app logic: third party apps stay enabled
