### ISSUE TITLE
Too much scrolling might be needed to access an already-shown user in the user page

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#14480]
This may depend on how the list of users are return by the user backend. It has been checked with the LDAP user backend, but might happen with other backends.
### Steps to reproduce
1. Add more than 100 users
2. When you enter in the users page, the first 50 users are loaded
3. Try to modify the user 50
### Expected behaviour

You can scroll to the bottom and modify the last user. No need to load more users because the user is already there.
### Actual behaviour

You scroll to the bottom, then the interface loads more users. If the users are inserted at the end you can modify the user you want after that, but if the users are inserted at the start, you need to keep scrolling. You might need to get the whole user list to modify the user you want, although the user was in the first bunch.
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 7.0.5
### Notes

It might be a better idea to add a button at the end to load more users and make the user to confirm that he wants to load more users. Another option could be to force the interface to add the new users at the end of the list regardless of the order the list is returned.

**Comment by karlitschek** [comment]
@blizzz

**Comment by blizzz** [comment]
@jancborchardt what do you think? LDAP does not return results in a sorted fashion, unfortunately.

**Comment by jancborchardt** [comment]
@blizzz ugh, this is a tough one then. What do you sort them by after you received them?

To resolve this issue we would probably need to keep the results unsorted after having received them (that is, always only adding 50 new elements at the bottom). But will the first 50 always be the same ones? This is confusing as people don’t know what it’s sorted by, cause it’s not.

**Comment by blizzz** [comment]
The client JS insert sorts them. OTOH I don't think it is a huge issue, you can search for the user after all.

**Comment by crysman** [comment]
We have more than 100 users and it is a real pain to scroll down multiple times all the way to somebody beginning with Z - it takes quite a moment and it is very unconvenient.

We need "show all" button

**Comment by butonic** [comment]
Fixed with the account table.
