### ISSUE TITLE
Cannot add a share from OC 7.0.4 in OC 7.0.5

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#14493]
### Steps to reproduce
1. Create a folder with some files in it inside a OC 7.0.4 server
2. Share the folder by link (checked with the default share params - no password, no expiration)
3. Go to the share link in another browser and try to add the link to your ownCloud (your OC version is 7.0.5)
4. Follow the process and add the share in the popup that shows up in your OC 7.0.5

### Expected behaviour
The shared folder is added correctly

### Actual behaviour
The remote share isn't added

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 7.0.4 and 7.0.5

**Updated from an older ownCloud or fresh install:** fresh install

### Notes
Also checked with 7.0.5 to 7.0.4, with 7.0.5 to 7.0.5; in both cases the share is added

**Comment by karlitschek** [comment]
@schiesbn Can you have a look? Sounds like a regression

**Comment by DeepDiver1975** [comment]
7.0.4 is know to be broken with that respect - that's why 7.0.5 will be shipped

**Comment by DeepDiver1975** [comment]
the fix for 7.0.5 - https://github.com/owncloud/core/pull/13796

**Comment by DeepDiver1975** [comment]
vote for close

**Comment by jnfrmarks** [comment]
@DeepDiver1975 

Should this work 7.0.3 -> 7.0.5?
