### ISSUE TITLE
Can't delete some files with weird accented chars

### ISSUE THREAD

**Issue by mhow2** [owncloud/core#14492]
Hi,

Actually running OC v6.0.6 ( was running 5.0.10 and 5.0.18 and had the same issue )
I can't get this particular file deleted, opened or renamed.

The filename contain an accented char on the letter 'e'. However it seems not a real 'é', it is something else :

In OC Web UI I get:
![selection_014](https://cloud.githubusercontent.com/assets/9987241/6369819/0043f462-bcea-11e4-9f0d-4ae8460a380c.png)

If I read the output of a 'ls -l' where the file sits, I get this 

![selection_013](https://cloud.githubusercontent.com/assets/9987241/6369794/c7feed28-bce9-11e4-9e71-3c08f142057e.png)

If I copy/paste that part from the terminal I get :  Dépliant

The file is real in OC data folder from the filesystem, I can open it.

How do I cleanly recover from this issue ?

**Comment by LukasReschke** [comment]
Thanks a lot for reporting issues back to us!

We need some more information to properly support you with your issue!

Can I ask you to follow our guidelines for submitting bugs as described here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by mhow2** [comment]
Hi, sorry for the missing info.


**Operating system**:
Debian 7
**Web server:**
Apache
**Database:**
MySQL
**PHP version:**
5.4.36

**ownCloud version:** 
6.0.6

**Updated from an older ownCloud or fresh install:**
Updated from

**List of activated apps:**
N/A

### Client configuration
**Browser:**
Firefox or Chrome

**Operating system:**
Ubuntu

### Logs
#### Web server error log

```
Error 	PHP 	fopen(..../APP-DATA/OwnCloud/ow2box/....../Devis N°1112-009056 Dépliant xxxxx.pdf): failed to open stream: No such file or directory at /usr/local/ow2apps/owncloud-current/lib/private/files/storage/local.php#188 	2015-02-25T11:19:16+00:00 
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"54edb6262b4fe","app":"PHP","message":"fopen(\/fs\/path\/APP-DATA\/OwnCloud\/....\/Devis N\u00b01112-009056 D\u00e9pliant xxxxxx.pdf): failed to open stream: No such file or directory at \/usr\/local\/ow2apps\/owncloud-current\/lib\/private\/files\/storage\/local.php#188","level":3,"time":"2015-02-25T11:46:46+00:00","method":"GET","url":"\/index.php\/apps\/files\/ajax\/download.php?files=Devis%20N%C2%B01112-009056%20De%CC%81pliant%203%20volets%20-%20xxxx.pdf&dir=%2FShared'.....Devis"}

```

**Comment by DeepDiver1975** [comment]
- [ ] php module intl installed?
- [ ] locale en_US.UTF-8 installed?

**Comment by mhow2** [comment]
package php5-intl is installed
locale en_US.UTF-8 is installed

**Comment by DeepDiver1975** [comment]
Hmmm - I honestly think this is an environment issue.
I just tested this on demo.owncloud.org(which is OC8) and this works - but on another test instance with OC6 this was working as well.

**Comment by karlitschek** [comment]
@mhow2 Can you try to test on a different machine/OS ?
I´m closing this until we got more information what exactly is the special difference in the environment.
