### ISSUE TITLE
[7.0.4] External Storages do not reflect updates with cron job/cron.php

### ISSUE THREAD

**Issue by gig13** [owncloud/core#14507]
**Expected Behavior**
When setting up the backgound jobs to use cron and call cron.php, the External storage will update changes made directly on the external storage with the ownCloud server and desktop client.

**Actual Behavior**
No updating is occurring for SMB/CIFS. This may also be occurring with other external storage.

**Steps to Reproduce**
Setup an SMB external storage
Update the files directly on the SMB (outside ownCloud)
Check the ownCloud desktop client folder for synced or updated changes. No changes are reflected.

**Server configurations**
RHEL 7
MySql 
OC 7.0.4

@MorrisJobke @bboule

**Comment by RealRancor** [comment]
Ref to a ML posting describing a possible workaround:

http://owncloud.10557.n7.nabble.com/Exclusive-access-to-custom-mounts-tp12705p12706.html

**Comment by gig13** [comment]
@RealRancor 
Some use cases this is fine, like if the file scan is for a specific user. When there are multiple users and lots of files/data, it is not realistic.

**Comment by RealRancor** [comment]
@gig13 
Sure. It just was a short pointer to a possible solution and als a pointer that it seems to be a known problem.

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by karlitschek** [comment]
@icewind1991 What is the status here?

**Comment by DeepDiver1975** [comment]
From my understanding there is some etag propagation missing - setting milestone 8.1 to get attentions

**Comment by icewind1991** [comment]
etag propagation isn't the problem, background scanning is, and not a problem that's easy solvable

**Comment by craigpg** [comment]
Changing to "resolves-blue-ticket" because I don't think there's additional troubleshooting necessary.

**Comment by gig13** [comment]
@craigpg 
Do you need additional information for troubleshooting? Has there been any progress?

**Comment by PVince81** [comment]
Update detection is still an general issue and cannot be done accurately: https://github.com/owncloud/core/issues/11797

Needs more research.

**Comment by karlitschek** [comment]
@icewind1991 Any change for a quickfix?

**Comment by PVince81** [comment]
The quickfix is to have a cron job that runs `./occ files:scan --all` (or for a specific user)
Also related ticket about update detection on ext storage: https://github.com/owncloud/core/issues/5036

How about having a command `./occ files:scan --storage-id smb::xxxxx` that takes the storage id instead of user name ? Would at least prevent having to scan the whole home.

**Comment by DeepDiver1975** [comment]
> How about having a command ./occ files:scan --storage-id smb::xxxxx that takes the storage id instead of user name ? Would at least prevent having to scan the whole home.

@gig13 @craigpg would that be something which would solve your issues? THX

**Comment by gig13** [comment]
@DeepDiver1975 @craigpg 
I will follow up with the customer.

**Comment by gig13** [comment]
@DeepDiver1975 
Feedback from the customer:

"That would be good. We could control refresh using cron and it’d work for all external storage types. We use owncloudcmd now running from a script that creates a pid file so it won’t run if it’s already running. That way we can have cron run the script every minute but if there’s a long sync run it won’t try and run a second instance. We could do the same kind of thing with this occ command. Have it run on a schedule in cron inside a script so that there’s only one refresh happening on any one external storage location at a time. An example of such a script should probably go into the documentation.

So long as the one scan could update for all users who are accessing that external storage that’d be fine."

**Comment by DeepDiver1975** [comment]
@PVince81 @icewind1991  there we have this one problem again: how to get from the storage id to the storage?

**Comment by PVince81** [comment]
If you have the storage id, you can get the "numeric_id" and map it to the filecache.
This direction is not the problematic one.

**Comment by PVince81** [comment]
I  just discovered that we already have a `--path` option to files:scan:

`./occ files:scan --path /$user/files/somemountpoint`.

So if the mount point is used by multiple users, the cron scan could be setup to run for only one of them.

@icewind1991 can you confirm that this willfor mounted filesystems ?

**Comment by icewind1991** [comment]
It should, it gets the user id from the path and sets up the filesystem from that

**Comment by PVince81** [comment]
Excellent. Then we might not need any additions for this workaround.

**Comment by cmonteroluque** [comment]
@jnfrmarks please test this so we can determine whether to close

**Comment by jnfrmarks** [comment]
@gig13 @cmonteroluque 

I tested with amazon s3 , server 8.1, and client 1.8.2

Test was:

1. create external storage
2. upload file to S3 outside of oC
3. sync using owncloudcmd

File uploaded in step 2 showed up in step 3.

If this is not the right test case, can someone please put the test steps in this issue?

**Comment by MorrisJobke** [comment]
@gig13 Please verify that this is solved.

**Comment by matzex** [comment]
This issue is also for me important because at the moment the external storage implementation is not usable for Dropbox. Files and Folders are not updated, etc.
What is the correct command to do a resync of Dropbox as an external Storage?
`./occ files:scan --path /$user/files/somemountpoint`
This is not working because there is no mountpoint for Dropbox if you use the external storage support from owncloud. Any suggestions?

**Comment by PVince81** [comment]
There should always be a mount point for any external storage, please double check.
If dropbox is visible for "user1" under the "/dropboxdir" mount point, then the command for that user would be:
`./occ files:scan --path /user1/files/dropboxdir`

**Comment by matzex** [comment]
If is use the --all option i see this path and it goes through every subfolder and scans every file in there:
`Scanning file   /matthias/files/oc/Dropbox/
Scanning folder /matthias/files/oc/Dropbox/`
Then i tried to use this path with the following command:
`./occ files:scan --path /matthias/files/oc/Dropbox`
But it does not scan the Dropbox folder and does nothing. Also in the folder in the file system there is no entry related to dropbox under this path:
`$ownCloud/data/matthias/files/oc/`

**Comment by PVince81** [comment]
Yes, the external storage mounts points are mounted virtually on the ownCloud filesystem, so they are not visible under "data".

Not sure why it is not scanning it, possibly a bug with the `--path` option :frowning: 

When doing `--all` does it find the updates there ?

**Comment by matzex** [comment]
Yes, for testing this again i uploaded a file to the external storage provider (Dropbox) and directly afterwards i started the syncing with `--all` and the new file appears in the list of the scanned files.
Also the syncing process with the `--all` Option shows a lot of lines of synced folders and files, with the `--path` option (path to the Dropbox folder) only 1 line is shown as status and the process terminates directly:
`$ ./occ files:scan --path /matthias/files/oc/Dropbox`
`Scanning file   /matthias/files/oc/Dropbox`
Also if i try to sync a superior folder with the following command it does not recognize the Dropbox folder. It looks like external storages are ignored for the `files:scan` command if it uses the path option.
`$ ./occ files:scan --path /matthias/files/oc`

Should i open a seperate bug report for this? I don't know if it only affects Dropbox or also other external storages.

**Comment by PVince81** [comment]
Yes, please make a separate ticket. Thanks.

**Comment by MorrisJobke** [comment]
@gig13 Please verify that this is solved.

**Comment by rperezb** [comment]
@jvillafanez can you please check this one?

**Comment by jvillafanez** [comment]
Checked the `./occ files:scan --path /user1/files/dropboxdir` workaround for 8.2 pre alpha and 8.1.1. Earlier versions won't have that option (check https://github.com/owncloud/core/issues/17067)

**Comment by gig13** [comment]
@bboule @cburnard 
FYI 
 `./occ files:scan --path /user1/files/dropboxdir` workaround for 8.2 pre alpha and 8.1.1. Earlier versions won't have that option (check https://github.com/owncloud/core/issues/17067)
