### ISSUE TITLE
Sharing API broken on master: shareUpdate fails

### ISSUE THREAD

**Issue by dragotin** [owncloud/core#14506]
Posting an update to an existing share through the share API in current master (7e7e0c51fb97312c69ee0cf03e9241f1bf08294e) does not update, but returns with an error message *"Wrong or no update parameter given"*, see ```apps/files_sharing/api/local.php```. It smells like parsing the PUT parameters fails.

The good news is that it works on stable8 and stable7 branch, I tested with update password.

**Comment by LukasReschke** [comment]
A curl request would have made this much easier to debug :see_no_evil: 

Let me look into this…

**Comment by DeepDiver1975** [comment]
@dragotin as far as I can tell this is fixed now in master - THX
