### ISSUE TITLE
WebDAV COPY creates empty folder when copying non-existing file

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#14501]
### Steps
1. Start cadaver
2. Type "cp nonexistingfile test.txt" (test.txt should not exist either)

### Expected
404

### Actual
An empty folder "test.txt" is created

**Comment by davivel** [comment]
@PVince81 , just to check it. Any chance this is backported? Not a big deal, but in Android we are adding the copy functionality and need to take a decision about what to do with this case.
