### ISSUE TITLE
cannot sync png file (attached)

### ISSUE THREAD

**Issue by JimLoose** [owncloud/core#14512]
OwnCloud Mac Client 1.7.1 build 1655
ownCloud 7.0.4 (stable)

It's unfortunately the second time: https://github.com/owncloud/core/issues/13005 - owncloud suddenly stops syncing my files! :-1: 
(because of missing e-tag??? whuuaat?)

![bug](https://cloud.githubusercontent.com/assets/195000/6378797/e44206b6-bd2d-11e4-82af-b864642c89ec.png)

the file, owncloud doesn't like to sync:
![icon-128](https://cloud.githubusercontent.com/assets/195000/6378812/f2a6b1ca-bd2d-11e4-8c09-e680ec287c10.png)

**Comment by LukasReschke** [comment]
Thanks a lot for reporting issues back to us!

We need some more information to properly support you with your issue!

Can I ask you to follow our guidelines for submitting bugs as described here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by JimLoose** [comment]
@LukasReschke before an hour of work collecting all that information...

- i retried it several times = doesn't work
- i renamed the file = works
- i renamed it to the old filename = suddenly works

anyway, why an etag check here?

**Comment by PVince81** [comment]
Forget the "etag" message, it's the equivalent of "an unknown error occurred on the server" which doesn't tell much.

Can you provide the matching server logs, from the owncloud.log file ?

I'd also like you to fill the issue template: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md because it contains important information like "what ownCloud version", "are you using encryption", etc, which are likely to influence/cause this issue.

Thanks.

**Comment by PVince81** [comment]
Ah I see, 7.0.4. Also: was it a shared file ? Shared by you or are you the recipient ?

**Comment by Joluwe** [comment]
Yep, i shared the file to another user:

		{"reqId":"54d8f139b4c99","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'files\/Share Ha+Fe\/Files\/Universal Booking Client.latest\/images\/icon-128.png' is not readable !!!","level":0,"time":"2015-02-09T17:41:13+00:00","method":"PUT","url":"\/remote.php\/webdav\/Share%20Ha+Fe\/Files\/Universal%20Booking%20Client.latest\/images\/icon-128.png"}
		{"reqId":"54d8f139b4c99","app":"core","message":"No preview providers exist","level":3,"time":"2015-02-09T17:41:18+00:00","method":"PUT","url":"\/remote.php\/webdav\/Share%20Ha+Fe\/Files\/Universal%20Booking%20Client.latest\/images\/icon-128.png"}
		{"reqId":"54d8f139b4c99","app":"hook","message":"error while running hook (OC\\Preview::post_write): No preview providers","level":3,"time":"2015-02-09T17:41:18+00:00","method":"PUT","url":"\/remote.php\/webdav\/Share%20Ha+Fe\/Files\/Universal%20Booking%20Client.latest\/images\/icon-128.png"}
		{"reqId":"54d8f139b4c99","app":"OC\\Files\\Cache\\Scanner","message":"!!! No reuse of etag for 'files\/Share Ha+Fe\/Files\/Universal Booking Client.latest\/images\/icon-128.png' !!! \ncache: Array\n(\n    [fileid] => 2208\n    [storage] => home::JimLoose\n    [path] => files\/Share Ha+Fe\/Files\/Universal Booking Client.latest\/images\/icon-128.png\n    [parent] => 2147\n    [name] => icon-128.png\n    [mimetype] => image\/png\n    [mimepart] => image\n    [size] => 10348\n    [mtime] => 1423503665\n    [storage_mtime] => 1423503665\n    [encrypted] => 1\n    [unencrypted_size] => 1597\n    [etag] => 54d8f13b64496\n    [permissions] => 27\n)\n \ndata: Array\n(\n    [mimetype] => image\/png\n    [mtime] => 1423499260\n    [size] => 10348\n    [etag] => 54d8f13e8bba6\n    [storage_mtime] => 1423499260\n    [permissions] => 27\n    [parent] => 2147\n)\n","level":0,"time":"2015-02-09T17:41:18+00:00","method":"PUT","url":"\/remote.php\/webdav\/Share%20Ha+Fe\/Files\/Universal%20Booking%20Client.latest\/images\/icon-128.png"}

**Comment by JimLoose** [comment]
Yep, i shared the file to another user:

		{"reqId":"54d8f139b4c99","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'files\/Share Ha+Fe\/Files\/Universal Booking Client.latest\/images\/icon-128.png' is not readable !!!","level":0,"time":"2015-02-09T17:41:13+00:00","method":"PUT","url":"\/remote.php\/webdav\/Share%20Ha+Fe\/Files\/Universal%20Booking%20Client.latest\/images\/icon-128.png"}
		{"reqId":"54d8f139b4c99","app":"core","message":"No preview providers exist","level":3,"time":"2015-02-09T17:41:18+00:00","method":"PUT","url":"\/remote.php\/webdav\/Share%20Ha+Fe\/Files\/Universal%20Booking%20Client.latest\/images\/icon-128.png"}
		{"reqId":"54d8f139b4c99","app":"hook","message":"error while running hook (OC\\Preview::post_write): No preview providers","level":3,"time":"2015-02-09T17:41:18+00:00","method":"PUT","url":"\/remote.php\/webdav\/Share%20Ha+Fe\/Files\/Universal%20Booking%20Client.latest\/images\/icon-128.png"}
		{"reqId":"54d8f139b4c99","app":"OC\\Files\\Cache\\Scanner","message":"!!! No reuse of etag for 'files\/Share Ha+Fe\/Files\/Universal Booking Client.latest\/images\/icon-128.png' !!! \ncache: Array\n(\n    [fileid] => 2208\n    [storage] => home::JimLoose\n    [path] => files\/Share Ha+Fe\/Files\/Universal Booking Client.latest\/images\/icon-128.png\n    [parent] => 2147\n    [name] => icon-128.png\n    [mimetype] => image\/png\n    [mimepart] => image\n    [size] => 10348\n    [mtime] => 1423503665\n    [storage_mtime] => 1423503665\n    [encrypted] => 1\n    [unencrypted_size] => 1597\n    [etag] => 54d8f13b64496\n    [permissions] => 27\n)\n \ndata: Array\n(\n    [mimetype] => image\/png\n    [mtime] => 1423499260\n    [size] => 10348\n    [etag] => 54d8f13e8bba6\n    [storage_mtime] => 1423499260\n    [permissions] => 27\n    [parent] => 2147\n)\n","level":0,"time":"2015-02-09T17:41:18+00:00","method":"PUT","url":"\/remote.php\/webdav\/Share%20Ha+Fe\/Files\/Universal%20Booking%20Client.latest\/images\/icon-128.png"}

Concerning: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md it makes sense to provide a debug-php file which collects the requested information automatically in a logfile for your review. Otherwise we always have the same problem in every issue here :/

**Comment by PVince81** [comment]
Yeah, @LukasReschke is working on a tool to do that.

If there's another issue with your setup, feel free to copy/paste it here.

Did you spot any other errors in the log ?
Apart from the "missing preview provider" I don't see any problem. Also I don't think a missing preview provider would break upload (but who knows, CC @LukasReschke @georgehrke).

**Comment by JimLoose** [comment]
concerning:

> - i retried it "several times" = doesn't work
> - i renamed the file = works
> - i renamed it to the old filename = suddenly works
> 
> anyway, why an etag check here?

i do not have a way to reproduce that issue :(
→ won't fix
