### ISSUE TITLE
Exception: {"Message":"","Code":0,"Trace":"#0 [internal function]: OC_Connector_Sabre_QuotaPlugin

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#14516]
An unwanted error from owncloud.log again. 

### Steps to reproduce

Think it has something to do with sharing folder, but I´m not sure.

### Expected behavior

No errors

### Actual behavior

```
Exception: {"Message":"","Code":0,"Trace":"#0 [internal function]: OC_Connector_Sabre_QuotaPlugin->checkQuota('Bilder\/2015\/VER...', Resource id #107, Object(OC_Connector_Sabre_Directory))\n#1 \/var\/www\/html\/example.se\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(433): call_user_func_array(Array, Array)\n#2 \/var\/www\/html\/example.se.se\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(1645): Sabre\\DAV\\Server->broadcastEvent('beforeCreateFil...', Array)\n#3 \/var\/www\/html\/example.se\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(900): Sabre\\DAV\\Server->createFile('Bilder\/2015\/VER...', Resource id #107, NULL)\n#4 [internal function]: Sabre\\DAV\\Server->httpPut('Bilder\/2015\/VER...')\n#5 \/var\/www\/html\/example.se\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(474): call_user_func(Array, 'Bilder\/2015\/VER...')\n#6 \/var\/www\/html\/example.se\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(214): Sabre\\DAV\\Server->invokeMethod('PUT', 'Bilder\/2015\/VER...')\n#7 \/var\/www\/html\/example.se\/owncloud\/apps\/files\/appinfo\/remote.php(61): Sabre\\DAV\\Server->exec()\n#8 \/var\/www\/html\/example.se\/owncloud\/remote.php(54): require_once('\/var\/www\/html\/f...')\n#9 {main}","File":"\/var\/www\/html\/example.se\/owncloud\/lib\/private\/connector\/sabre\/quotaplugin.php","Line":79}	
```

### Server configuration

Ubuntu Server 14.04

**Database:**
Server version: 5.5.41-0ubuntu0.14.04.1 - (Ubuntu)
PHP version:
PHP 5.5.9-1ubuntu4.5 (cli) (built: Oct 29 2014 11:59:10)

**ownCloud version: (see ownCloud admin page)**
8.0
*Updated from an older ownCloud or fresh install:*
Fresh install on a new system

**List of activated apps:**
Activity
Calender 
Contacts
Deleted files
Documents
First Run Wizard
Full Text Search
PDF Viewer
Pictures
Share Files
Text Editor
Updater
Versions
Video Viewer

**Are you using external storage, if yes which one: local/smb/sftp/...**
No
**Are you using encryption: yes/no**
No

### Client configuration

**Browser:**
Version 39.0.2171.71 m
**Operating system:**
Windows 8.1
**Sync Client**
1.7.1 stable

### Logs

**Web server error log**

```
Insert your webserver log here
```

**ownCloud log (data/owncloud.log)**

```
As mentioned above
```

**Browser log**

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by LukasReschke** [comment]
Unserialized:
```
Array
(
    [Message] => 
    [Code] => 0
    [Trace] => #0 [internal function]: OC_Connector_Sabre_QuotaPlugin->checkQuota('Bilder/2015/VER...', Resource id #107, Object(OC_Connector_Sabre_Directory))
#1 /var/www/html/example.se/owncloud/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php(433): call_user_func_array(Array, Array)
#2 /var/www/html/example.se.se/owncloud/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php(1645): Sabre\DAV\Server->broadcastEvent('beforeCreateFil...', Array)
#3 /var/www/html/example.se/owncloud/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php(900): Sabre\DAV\Server->createFile('Bilder/2015/VER...', Resource id #107, NULL)
#4 [internal function]: Sabre\DAV\Server->httpPut('Bilder/2015/VER...')
#5 /var/www/html/example.se/owncloud/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php(474): call_user_func(Array, 'Bilder/2015/VER...')
#6 /var/www/html/example.se/owncloud/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php(214): Sabre\DAV\Server->invokeMethod('PUT', 'Bilder/2015/VER...')
#7 /var/www/html/example.se/owncloud/apps/files/appinfo/remote.php(61): Sabre\DAV\Server->exec()
#8 /var/www/html/example.se/owncloud/remote.php(54): require_once('/var/www/html/f...')
#9 {main}
    [File] => /var/www/html/example.se/owncloud/lib/private/connector/sabre/quotaplugin.php
    [Line] => 79
)
```

**Comment by enoch85** [comment]
@LukasReschke Thanks!

**Comment by LukasReschke** [comment]
Though I'm not sure WHAT kind of error this is…

@PVince81 Can you help me here? – I don't get WHAT this error is saying. It's a stack-trace yes, but for WHAT?!?

**Comment by PVince81** [comment]
Possibly an exception that did not specify any error message...

**Comment by PVince81** [comment]
Mystery solved: https://github.com/owncloud/core/blob/v8.0.0/lib/private/connector/sabre/quotaplugin.php#L79

**Comment by LukasReschke** [comment]
… /me didn't look at the v8.0.0 tag …

… now punch me in my face … :facepunch:

**Comment by PVince81** [comment]
@enoch85 would you agree that "insufficient storage" errors are still logged, if they have a proper message ?

**Comment by PVince81** [comment]
note: this is triggered by someone uploading a file when there isn't enough space left.

**Comment by enoch85** [comment]
@PVince81 If they have a proper message, yes. But I also want to say that I have 1 TB free space left.

**Comment by PVince81** [comment]
Did you set a quota ?

**Comment by enoch85** [comment]
@PVince81 Yes, there is the main issue here. But please, make the error message more proper.

**Comment by enoch85** [comment]
Something like: `User quota exeeded for [user]`

**Comment by nickvergessen** [comment]
Does this affect master? i mean we only have different class names there, but the original issue should still be a problem, right @PVince81 ?

**Comment by PVince81** [comment]
Yes, still a problem.

**Comment by DeepDiver1975** [comment]
So basically the exception logging plugin has to properly fill the message.

**Comment by crysman** [comment]
I am experiencing the same/similar issue - the log full of messages like this:

`Exception: {"Message":"","Code":0,"Trace":"#0 [internal function]: OC_Connector_Sabre_QuotaPlugin->checkQuota('Letn\\xC3\\xAD t\\xC3\\xA1bor\/C...', Resource id #128, Object(OC_Connector_Sabre_Directory))\n#1 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(433): call_user_func_array(Array, Array)\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(1645): Sabre\\DAV\\Server->broadcastEvent('beforeCreateFil...', Array)\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(900): Sabre\\DAV\\Server->createFile('Letn\\xC3\\xAD t\\xC3\\xA1bor\/C...', Resource id #128, NULL)\n#4 [internal function]: Sabre\\DAV\\Server->httpPut('Letn\\xC3\\xAD t\\xC3\\xA1bor\/C...')\n#5 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(474): call_user_func(Array, 'Letn\\xC3\\xAD t\\xC3\\xA1bor\/C...')\n#6 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(214): Sabre\\DAV\\Server->invokeMethod('PUT', 'Letn\\xC3\\xAD t\\xC3\\xA1bor\/C...')\n#7 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(61): Sabre\\DAV\\Server->exec()\n#8 \/var\/www\/owncloud\/remote.php(54): require_once('\/var\/www\/ownclo...')\n#9 {main}","File":"\/var\/www\/owncloud\/lib\/private\/connector\/sabre\/quotaplugin.php","Line":79}`

How shall I understand this, please? :/
