### ISSUE TITLE
Changelog for new Owncloud 5/6/7 releases?

### ISSUE THREAD

**Issue by oniled** [owncloud/core#14517]
Hi everyone,

It's been a couple days since new Owncloud updates for versions 5,6,7 were listed here:

https://github.com/owncloud/core/releases

Is there a changelog for each?  Are these considered production or test versions since I didn't see any announcement for their release?

**Comment by LukasReschke** [comment]
@karlitschek

**Comment by karlitschek** [comment]
We will announce this as soon as they are ready and fully tested. Sorry for the delay.

**Comment by RealRancor** [comment]
@oniled 
A preview is available here: https://owncloud.org/releases/Changelog
