### ISSUE TITLE
Admin page needs return to top

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#14519]
Admin page needs a link that goes back to the top. We have all the links to the sections on the left (LOVE IT!!! SUPER!!!) but we don't link back to the top of the page.

**Comment by DeepDiver1975** [comment]
@jancborchardt one for us :wink:

**Comment by jancborchardt** [comment]
We do though. »Security & Setup warnings« is the entry which is at the very top, and that’s linked in the sidebar.

Or what do you mean @MTRichards? Please clarify.

**Comment by MTRichards** [comment]
I think just a back tothe  top link at the top on the left top. How would you know that security and setup is the top of the menu? Clear we did not, so just a quick explicit item that provides this would be good.

**Comment by jancborchardt** [comment]
Not sure if this is really a problem. In the past we did not have an entry for »Security & Setup warnings«, so the problem probably stems from that.

**Comment by jancborchardt** [comment]
@MTRichards you probably mean the »Personal« page instead of Admin, right? Because that one indeed doesn’t have a link for the top section and we need to add that.

**Comment by MTRichards** [comment]
As discussed, lets see if we can make the left nav bar titles more the same as the headers for the top of the admin page. And, of course, personal page too... :)

**Comment by jancborchardt** [comment]
Combining all the errors into a »Security & setup warnings« section. At https://github.com/owncloud/core/pull/15112
