### ISSUE TITLE
Uploading a file after enabling encryption without loging out results in a 0 bytes upload

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#14521]
### Steps to reproduce
1. Enable the files_encryption app
2. Go to the files view without login out. You'll see a warning telling you to log out
3. Try to upload a file. You'll see a notification that it's not possible to upload a file because the encryption keys are not set
4. Log out and login again

### Expected behaviour
According to the notification, you shouldn't have any new file (specially the one that we tried to upload in the step 3)

### Actual behaviour
The file uploaded in step 3 appears with 0 bytes

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** stable8

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by karlitschek** [comment]
@schiesbn This doesn´t sound good

**Comment by DeepDiver1975** [comment]
> You'll see a warning telling you to log out

hmm - capability to read is a requirement in the first world :speak_no_evil: 

True not optimal - but not really critical because generally speaking encryption is enabled once right after installation.

**Comment by jvillafanez** [comment]
This can also happen if there are several users using the web interface and one of them enables the encryption. The rest of users will have the same issue until they log out, and I guess the notification is a bit cryptic for them because they won't know that the encryption has been enabled

**Comment by nickvergessen** [comment]
We could close all sessions when enabling encryption, so they all are forced to relog in?
Same for disabling it?

**Comment by PVince81** [comment]
Are you still seeing this in 8.0.5 ? 8.1 might behave differently, I expect you to get 403 there.

**Comment by PVince81** [comment]
@schiesbn is this still valid for encryption 2.0 ?

**Comment by PVince81** [comment]
Closing due to lack of feedback. Please reopen if this is still happening in 8.2.6 or 9.0.3.
