### ISSUE TITLE
Display first apps with an update pending

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#14525]
From @awikatchikaen - https://github.com/owncloud/apps/issues/2019:

The new display of apps in the admin menu is great, but like in the 'play store', it would be useful to have the apps to update in the first result.

Or have a special category

**Comment by MorrisJobke** [comment]
I labelled this as junior job because it is a good possibility to get in touch with the core code and shouldn't be that hard, because the information is already available.

**Comment by RealRancor** [comment]
@MorrisJobke Seems @awikatchikaen had already created it here: https://github.com/owncloud/core/issues/14520

**Comment by MorrisJobke** [comment]
@RealRancor Thanks for spotting
