### ISSUE TITLE
Upload does not complete

### ISSUE THREAD

**Issue by trigonova** [owncloud/core#14523]
Steps to reproduce
1.Try upload a file >200MB

Expected behaviour

File should upload correctly

Actual behaviour

The upload bar runs till the end and stays there, nothing more happens. The file is not uploaded.

Server configuration

Operating system: Windows Server 2008 R2

Web server: IIS 7.5

Database: mysql

PHP version: 5.6

ownCloud version: 7.0.4

Updated from an older ownCloud or fresh install: from 7.0.2

**Comment by nickvergessen** [comment]
Disable the "files locking" app

**Comment by nickvergessen** [comment]
Duplicate of #14513

**Comment by trigonova** [comment]
i dont use any "files locking" app..what should that be?

**Comment by nickvergessen** [comment]
It's an app that is shipped with the default package and also enabled by default.
Visit `index.php/settings/apps` > `Enabled` and search for it

**Comment by trigonova** [comment]
I definitely don't have this app, never heard of it:
![apps](https://cloud.githubusercontent.com/assets/7849016/6479607/6316728c-c248-11e4-8e3e-7cda44bb1133.jpg)
![apps2](https://cloud.githubusercontent.com/assets/7849016/6479610/689c7ca6-c248-11e4-897a-8f26d85e8652.jpg)
