### ISSUE TITLE
Sidebar in files application is reusing IDs leading to problems with jQuery functions

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#14536]
The `#filestable` DIV is used multiple times in the files view, this causes problems with stuff like [`setViewerMode`](https://github.com/owncloud/core/blob/a320edaca5f90a713ad5e394555bcbddce2cb319/apps/files/js/filelist.js#L1256)  which operates on a DIV.

An ID can only be used once, from my PoV it would be the sensiblest solution to replace this with a class instead. However, we would then have to change this usage in all apps as well :see_no_evil: 

This causes bugs such as https://github.com/owncloud/files_pdfviewer/issues/38

@PVince81 Any idea for a quick win to solve this problem?

**Comment by PVince81** [comment]
Back then (OC6) I didn't dare getting rid of that id because I wasn't sure if apps were using it, but I agree that an id should be unique. I don't like this general pattern where people seem to use ids everywhere (ex: sharing dropdown). Ideal is only using class names.

If the PDF viewer is still accessing the list by id it should change and use the class name instead or a different selector.

**Comment by PVince81** [comment]
Ah, got it. To fix it change https://github.com/owncloud/core/blob/a320edaca5f90a713ad5e394555bcbddce2cb319/apps/files/js/filelist.js#L1256 and make it use `this.$fileList` instead, which already points to the correct DOM element.

**Comment by jancborchardt** [comment]
Yeah, ID’s should only be used for elements which really appear only once – like the header bar, or the #app-navigation, etc. Not things which are likely to appear multiple times. cc @owncloud/designers

**Comment by LukasReschke** [comment]
> Ah, got it. To fix it change https://github.com/owncloud/core/blob/a320edaca5f90a713ad5e394555bcbddce2cb319/apps/files/js/filelist.js#L1256 and make it use this.$fileList instead, which already points to the correct DOM element.

Good call… verifying and preparing PR. Thanks!! :rocket:

**Comment by LukasReschke** [comment]
> Ah, got it. To fix it change https://github.com/owncloud/core/blob/a320edaca5f90a713ad5e394555bcbddce2cb319/apps/files/js/filelist.js#L1256 and make it use this.$fileList instead, which already points to the correct DOM element.

Mhm… Doesn't seem to work properly in all cases :cry:

**Comment by LukasReschke** [comment]
(still changes the wrong filelist then)

**Comment by PVince81** [comment]
Ok, maybe try additionally to change this line https://github.com/owncloud/core/blob/a320edaca5f90a713ad5e394555bcbddce2cb319/apps/files/js/filelist.js#L186

Change "#filelist" with "tbody"

**Comment by LukasReschke** [comment]
:see_no_evil:

**Comment by PVince81** [comment]
Has this even worked before ? I had the feeling it already worked fine in the past.

**Comment by LukasReschke** [comment]
Mhm? – What before? Previously we didn't use the new FileList API thingy and so Previews did not work in Favourites.

Now they work in favourites and I call `setViewerMode` which however will in this case only set the first #filestable to hidden and the favourites one is the second or so :-/

… let me try if your suggestion works :smile: …

**Comment by DeepDiver1975** [comment]
8.0.2? @LukasReschke

**Comment by LukasReschke** [comment]
Had some chit-chat with @PVince81. This seems not *that* easily fixable as we thought. Let's move this to 8.0.2 for now from my PoV – that bug only affects the PDF Viewer with favourited files. There is worse IMHO.

**Comment by PVince81** [comment]
@LukasReschke can you point me to the PDF viewer code that calls "setViewerMode()" ?
Is that code calling the method on the correct FileList object, the one that was passed/injected from the file action callback ?

**Comment by LukasReschke** [comment]
https://github.com/owncloud/files_pdfviewer/blob/master/js/previewplugin.js#L33 - pretty sure it is not using the callback 🙈

**Comment by PVince81** [comment]
Yeah, that's the problem.

The PDF viewer should save/store whichever instance of fileList was injected instead of using the global instance. The global instance is always the one from "All files", for backward compatilibity.

**Comment by LukasReschke** [comment]
Then let's try that :see_no_evil: (though we shouldn't reuse IDs anyways)

**Comment by LukasReschke** [comment]
https://github.com/owncloud/files_pdfviewer/pull/42

**Comment by LukasReschke** [comment]
Causes other problems then: https://github.com/owncloud/files_pdfviewer/pull/42#issuecomment-76682540

**Comment by PVince81** [comment]
Hmm, your code looks good now. I'll need to debug this.

**Comment by DeepDiver1975** [comment]
nothing for 8.0.3 -> 8.2 to reevaluate the situation

**Comment by PVince81** [comment]
tech debt => 9.0

**Comment by PVince81** [comment]
Low issue / tech debt => backlog
