### ISSUE TITLE
PUT Routes arguments are not properly parsed

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#14541]
It seems that the AppFramework has a bug.

When I tried to update the e-mail address on a fresh install on the personal page I got errors that I supplied an "Invalid mail address".

After a bit of debugging it seems that $mailAddress on https://github.com/owncloud/core/blob/master/settings/controller/userscontroller.php#L443 is just not set! And thus the address does not validate.

The other routes seem to work fine. But this is the only PUT request.

When tested on the stable8 branch everything works as expected.

**Comment by LukasReschke** [comment]
Mhm… That works fine here… Let's catch up in IRC.

**Comment by rullzer** [comment]
So a step by step:

1. Clean new install (sqlite)
2. Go to perosnal page
3. Try to edit e-mail
4. Fail :(


The js stuff just reports back:
````{"status":"error","data":{"message":"Invalid mail address"}}````


Nothing in the owncloud log
And also my nginx logs are clean

**Comment by DeepDiver1975** [comment]
@rullzer which oc version are you using? THX

**Comment by rullzer** [comment]
@DeepDiver1975 ah I should have included that... master

**Comment by DeepDiver1975** [comment]
hmm - works here - which browser?

**Comment by rullzer** [comment]
Firefox.
But I also tested it in Chromium and with curl. All fail with the same response.

**Comment by rullzer** [comment]
O and running Gentoo Linux on my server

**Comment by DeepDiver1975** [comment]
do me the favor and paste the curl command  - one never knows .... :speak_no_evil:

**Comment by rullzer** [comment]
curl 'https://xxxxxxxxx/index.php/settings/users/roeland/mailAddress' -X PUT -H 'Host: cloud3.famdouma.nl' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:35.0) Gecko/20100101 Firefox/35.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H 'requesttoken: hIcboSDbwGrEenayW678xD6Z3dJU5t' -H 'OCS-APIREQUEST: true' -H 'X-Requested-With: XMLHttpRequest' -H 'Referer: https://cloud3.famdouma.nl/index.php/settings/personal' -H 'Cookie: ocaz881q2ia0=08gsnpiiumv1eil2bm2ajlejh6' --data 'mailAddress=foo%40bar.coz'

**Comment by DeepDiver1975** [comment]
> And also my nginx logs are clean

nginx setup issue?

**Comment by rullzer** [comment]
> nginx setup issue?

Could be. But if I checkout the stable8 branch everything works fine again.

**Comment by DeepDiver1975** [comment]
hmmmm - which auth backend are you using?

**Comment by DeepDiver1975** [comment]
@Julian1998 you had issues with setting your email address as well - right? 
Which oc version?

**Comment by rullzer** [comment]
> hmmmm - which auth backend are you using?

Default sqlite3 database backend.

**Comment by rullzer** [comment]
So it is not only the appframework. If I try to update a share with a put request ti also fails on master. But succeeds on stable8.

I'll see if I can debug some more

**Comment by DeepDiver1975** [comment]
hmmm ... @dragotin you faced some PUT issues as well - right? #14506 ?

**Comment by rullzer** [comment]
I made a simple test case where I try to update the persmission on a share (which is a PUT request). And ran git bisect.

This tells me the first "bad" commit is 87db136508f6599568eedf8f7696c6ebea4f56c1

But I can't really find anything in there that might explain the sudden fail.

**Comment by dragotin** [comment]
@DeepDiver1975 yes, #14506

**Comment by DeepDiver1975** [comment]
> This tells me the first "bad" commit is 87db136

@rullzer you are awesome! Let me have a look at that commit!

**Comment by DeepDiver1975** [comment]
hmm - that commit was reverted some time later

**Comment by rullzer** [comment]
@DeepDiver1975 @LukasReschke are you two by any change on php-5.6?

I noticed that if I add print statements in all the places where php:://input is used there is a bit of difference between stable8 and master. I'll try to explain below.

Files modified:
        modified:   lib/private/api.php
        modified:   lib/private/appframework/http/request.php
        modified:   lib/private/ocs.php

basically I added a print statement:    <FILE> file_get_contents("php://input") \n

On stable8 on a curl to OCS I get:
> lib/private/api.php: permissions=1

On master I get:

> lib/private/appframework/http/request.php: permissions=1
> lib/private/appframework/http/request.php: 
> lib/private/appframework/http/request.php: 
> lib/private/appframework/http/request.php: 
> lib/private/appframework/http/request.php: 
> lib/private/appframework/http/request.php: 
> lib/private/appframework/http/request.php: 
> lib/private/appframework/http/request.php: 
> lib/private/appframework/http/request.php: 
> lib/private/appframework/http/request.php: 
> lib/private/appframework/http/request.php: 
> lib/private/appframework/http/request.php: 
> lib/private/appframework/http/request.php: 
> lib/private/api.php: 
> lib/private/appframework/http/request.php: 
> lib/private/appframework/http/request.php: 
> lib/private/appframework/http/request.php: 
> lib/private/appframework/http/request.php: 
> lib/private/appframework/http/request.php: 
> lib/private/appframework/http/request.php: 
> lib/private/appframework/http/request.php: 
> lib/private/appframework/http/request.php: 

Which shows that we do a lot more in the appframework now. Including reading the stream. Which on php 5.6 is not a problem but on php 5.5 is: http://php.net/manual/en/wrappers.php.php

````......Prior to PHP 5.6, a stream opened with php://input could only be read once;......````

**Comment by DeepDiver1975** [comment]
I'm on php 5.6.5

**Comment by LukasReschke** [comment]
Dito.

**Comment by DeepDiver1975** [comment]
> On master I get:
> 
>     lib/private/appframework/http/request.php: permissions=1
>     lib/private/appframework/http/request.php:
>     lib/private/appframework/http/request.php:
>     lib/private/appframework/http/request.php:
>     lib/private/appframework/http/request.php:
>     lib/private/appframework/http/request.php:
>     lib/private/appframework/http/request.php:
>     lib/private/appframework/http/request.php:
>     lib/private/appframework/http/request.php:
>     lib/private/appframework/http/request.php:
>     lib/private/appframework/http/request.php:
>     lib/private/appframework/http/request.php:
>     lib/private/appframework/http/request.php:
>     lib/private/api.php:
>     lib/private/appframework/http/request.php:
>     lib/private/appframework/http/request.php:
>     lib/private/appframework/http/request.php:
>     lib/private/appframework/http/request.php:
>     lib/private/appframework/http/request.php:
>     lib/private/appframework/http/request.php:
>     lib/private/appframework/http/request.php:
>     lib/private/appframework/http/request.php:

@dragotin your php version? - THX

**Comment by rullzer** [comment]
So most likely a php < 5.6 issue. I'll compile 5.6 and see if the problem goes away

**Comment by DeepDiver1975** [comment]
> On master I get:
> 
>     lib/private/appframework/http/request.php: permissions=1
>     lib/private/appframework/http/request.php:
>     lib/private/appframework/http/request.php:
>     lib/private/appframework/http/request.php:
>     lib/private/appframework/http/request.php:
>     lib/private/appframework/http/request.php:
>     lib/private/appframework/http/request.php:
>     lib/private/appframework/http/request.php:
>     lib/private/appframework/http/request.php:
>     lib/private/appframework/http/request.php:
>     lib/private/appframework/http/request.php:
>     lib/private/appframework/http/request.php:
>     lib/private/appframework/http/request.php:
>     lib/private/api.php:
>     lib/private/appframework/http/request.php:
>     lib/private/appframework/http/request.php:
>     lib/private/appframework/http/request.php:
>     lib/private/appframework/http/request.php:
>     lib/private/appframework/http/request.php:
>     lib/private/appframework/http/request.php:
>     lib/private/appframework/http/request.php:
>     lib/private/appframework/http/request.php:

so - we better use IRequest in ocs/api.php as well? :speak_no_evil:

**Comment by LukasReschke** [comment]
But IRequest is only on master – so it should work on 8.0? – In this case let's move this to 8.1-next?

**Comment by LukasReschke** [comment]
That said @DeepDiver1975's proposal sounds like the easiest :+1:

**Comment by DeepDiver1975** [comment]
8.1 - yes - but better sooner then later :wink:

**Comment by DeepDiver1975** [comment]
I really wonder why ctor of request is called that often ...

**Comment by LukasReschke** [comment]
Well… I can tell you that… It's because of our crappy unit tests.

**Comment by LukasReschke** [comment]
https://github.com/owncloud/core/blob/7fe07e93fe4706962d2957d252b009513459d15e/lib/private/server.php#L294

**Comment by LukasReschke** [comment]
Which means we would need to cache this again etc… – The problem is that some of our unit tests use `$_GET = foo` and other black magic… We would need to migrate those usages to the IRequest then as well…

**Comment by LukasReschke** [comment]
Especially this was needed for that bloody WebDAV server "unit test" which we apparently couldn't remove the time I added this, but now it's gone and this task should be easier :see_no_evil:

**Comment by LukasReschke** [comment]
See https://github.com/owncloud/core/pull/14056#issuecomment-73945860

**Comment by DeepDiver1975** [comment]
> https://github.com/owncloud/core/blob/7fe07e93fe4706962d2957d252b009513459d15e/lib/private/server.php#L294

well here the request instance has to be cached as member in the server

**Comment by DeepDiver1975** [comment]
furthermore there is a request instanciated in base.php initPaths() - which means php://input is read there and bye bye

**Comment by LukasReschke** [comment]
Let me take care of this – gotta love PHP ;-)

**Comment by DeepDiver1975** [comment]
THX @LukasReschke

**Comment by rullzer** [comment]
Everything works as expected with php-5.6.

I still do not know why my git bisect gave that commit.

**Comment by DeepDiver1975** [comment]
> I still do not know why my git bisect gave that commit.

that commit broke a hell of thing - start to bisect one commit after that - if you like
