### ISSUE TITLE
Force error if READ permission not given in OCS Share API

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#14548]
Following up on https://github.com/owncloud/core/issues/13867

The OCS Share API must validate the passed permissions.

If no "READ" permission was given (for example when passing 0 or 16 (SHARE)), it must return 400 Bad Request.

@schiesbn @rullzer

**Comment by PVince81** [comment]
I'm tagging this as bug because if you forget to pass "READ", the server will behave weirdly.

**Comment by rullzer** [comment]
That should not be to hard. I'll have a look later.

**Comment by rullzer** [comment]
Above PR should fix this

**Comment by MorrisJobke** [comment]
fixed with #14570
