### ISSUE TITLE
Let admin use share API to manage shares from all users

### ISSUE THREAD

**Issue by gig13** [owncloud/core#14545]
When using the Sharing API is would be very useful to obtain all of the files/folders that have been shared with a specific user. This could be used for audit purposes, reconciliation, and other tasks.

I only see methods to Get All Shares or Get Shares From a Specific File or Folder. I am using the Get all api and then to get share id for a particular user. The problem is the return results could be huge.

@MTRichards

**Comment by MTRichards** [comment]
Seems a reasonable request.  Who worked on this? 
@DeepDiver1975 Any ideas?
Even a SQL Query workaround would be ok to solve this short term...

**Comment by gig13** [comment]
@MTRichards 
Any update on a workaround sql query?

**Comment by LukasReschke** [comment]
What about the following?
```
SELECT * from oc_share where share_with="UserID";
```

**Comment by LukasReschke** [comment]
If you want to loop through all file names in the share as well one would need to create a little script that iterates through the file cache.

**Comment by PVince81** [comment]
There is already a call used by the web UI: "http://localhost/owncloud/ocs/v1.php/apps/files_sharing/api/v1/shares?format=json&shared_with_me=true" but I think it only applies to the currently logged in user.

The requirement here is to be able to do so as an admin for any user.
