### ISSUE TITLE
Nothing happens when users use the search field in most apps

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#14544]
As mentioned [here](https://github.com/owncloud/core/issues/11635#issuecomment-59767816), [here](https://github.com/owncloud/gallery/issues/156) and [here](https://github.com/interfasys/galleryplus/issues/37), the search field **is broken** for most apps because the mechanism has changed in oC8 and **there is no fallback in place**.

The fallback could be for the field to work like in previous versions, giving users access to a dropdown or a more drastic change could be implemented by removing the field if the app hasn't registered with the search engine.

To me, this is a regression, but I'll let the people in charge be judge of that.
@butonic @jancborchardt @DeepDiver1975

**Comment by karlitschek** [comment]
@butonic What do you think?

**Comment by karlitschek** [comment]
@jancborchardt Isn´t this the bug that we discussed friday?

**Comment by DeepDiver1975** [comment]
We should introduce some fallback at least - I'm also a bit "mad" about the fact that in case I want to use the search box as a pure client side filter mechanism that there is still a request sent to the server to perform a search.

**Comment by DeepDiver1975** [comment]
@jancborchardt maybe find the time to fix this these days ....

**Comment by jancborchardt** [comment]
@DeepDiver1975 yeah, probably it’s best for us to collaborate on it when coworking.

The important thing we need to decide is what to do for an app / view which does not support search – which will be most apps actually.

If we want the search to have a purpose then we need to make it search the Files. In that case we need something similar to the previous search dropdown. But a bit wider, and nicely styled.

**Comment by jancborchardt** [comment]
@DeepDiver1975 this we also need to work on tomorrow when coworking.

**Comment by DeepDiver1975** [comment]
This is a tough one .... 

- [ ] how to detect that the current app is handling search results by itself?
- [ ] how should the fallback look like?

**Comment by nickvergessen** [comment]
> how to detect that the current app is handling search results by itself?

I fixed this part in my previous attempt: https://github.com/owncloud/core/pull/16480/files

**Comment by oparoz** [comment]
Having given it some thoughts, I think we should respect the context. If we're in an app, the search field should work for data which the app can work with and that's the app's responsibility to implement that.
I'm for introducing a way to disable the search field if the app hasn't registered to use it, so that each app doesn't have to create their own search field.

Having the old dropdown would prolly confuse users as they would be redirected to the Files app when selecting a file or folder.

**Comment by jancborchardt** [comment]
Good call by @DeepDiver1975 to just hide it when the app doesn’t support search. Please review https://github.com/owncloud/core/pull/16810
