### ISSUE TITLE
Password tipsy

### ISSUE THREAD

**Issue by Julian1998** [owncloud/core#14543]
The tipsy for password strength is not moved while scrolling

Steps to reproduce:
1. change your password into a random password
2. scroll down

![unbenannt](https://cloud.githubusercontent.com/assets/2546997/6393671/67c95cb6-bdcc-11e4-843b-3716cdb9e2f6.PNG)

**Comment by DeepDiver1975** [comment]
@Julian1998 which version is this? git master branch? THX

**Comment by Julian1998** [comment]
yeah I´m usig git master :)

**Comment by PVince81** [comment]
That's likely to be an issue everywhere, the tipsy isn't appended into the scroll container but is absolute and floating.

One idea would be to kill all tipsies when a scroll event is detected.

**Comment by nickvergessen** [comment]
Confirmed on the activity stream, the solution from @PVince81 sounds like a plan

**Comment by DeepDiver1975** [comment]
PR welcome - any volunteer?

**Comment by DeepDiver1975** [comment]
closing this as duplicate of https://github.com/owncloud/core/issues/14094
