### ISSUE TITLE
Different behaviour between web and webDAV interfaces after disabling encryption

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#14549]
### Steps to reproduce
1. Enable encryption
2. Log out and log in to generate the encryption keys
3. Upload several files
4. Check that you can download the files normally from the web and webDAV interfaces
5. Disable encryption
6. Go to the files app. You should see a notification saying that your files are still encrypted and you should go to the personal settings page.
7. Try to upload and download files from both interfaces

### Expected behaviour
Both interfaces (web and webDAV) behave the same, probably blocking uploads and downloads.

### Actual behaviour
- From the webDAV interface isn't possible to upload neither download any file (encrypted or not)

- From the web interface, you can upload files and download them without being encrypted. Previously encrypted files can be downloaded encrypted.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** stable8

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by karlitschek** [comment]
@schiesbn @th3fallen What do you think?

**Comment by DeepDiver1975** [comment]
> From the webDAV interface isn't possible to upload neither download any file (encrypted or not)

at least this is done on purpose - we don't want to mess around with synced files.

basically the same checks need to be applied to the web ui as well-

Just another reason to move the web ui over to use webdav as well

@PVince81

**Comment by DeepDiver1975** [comment]
let' schedule the file app webdav migration for 8.2 - long overdue

**Comment by PVince81** [comment]
Here: https://github.com/owncloud/core/issues/12353

**Comment by DeepDiver1975** [comment]
well - this will be solved with #12353 -> close
