### ISSUE TITLE
7.0.5 UI has copyright of 2014

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#14556]
Copyright date in UI for 7.0.5 is 2014.  Should it be 2015?

The same issue probably exists in 5.0.19 and 6.0.7, though I have not validated it just yet

**Comment by jnfrmarks** [comment]
@karlitschek @DeepDiver1975 

What's the chance of this being resolved by next Tuesday?

**Comment by LukasReschke** [comment]
If you refer to that one in EE this needs to get fixed in the theme there as well. So we would need to:

1. For CE fix in core
2. For themes fix in the theme in `theme/defaults.php`

**Comment by LukasReschke** [comment]
Created some pull requests… Have you referenced on all of them. Please test.

**Comment by LukasReschke** [comment]
Should be fixed now. Please verify.

**Comment by DeepDiver1975** [comment]
@jnfrmarks ^

**Comment by jnfrmarks** [comment]
Looks good.
