### ISSUE TITLE
Can I override how space usage is calculated?

### ISSUE THREAD

**Issue by jerrac** [owncloud/core#14553]
Current behavior is this: "For example, if you upload files to another user’s share, those files count against your quota." From https://doc.owncloud.org/server/8.0/user_manual/files/quota.html

My issue is that I need to create manual accounts for a department that has a larger quota than normal ldap users. That way, when ldap users upload to a folder shared by the department account, their quota doesn't get used up. According to the docs linked above, that's exactly the oposite of how it works.

So, is there a way I could tell OwnCloud that, for this department account, files uploaded to a share by other users actually count towards the department account quota, and not the uploader's quota?

In detail:

departmentA creates ShareAlpha, and shares it with userB.
userB uploads a 5GB file to ShareAlpha.
departmentA's space usage then goes up by 5GB. userB's space usage does not go up at all.

**Comment by LukasReschke** [comment]
This is at the moment not possible.

**Comment by jerrac** [comment]
Is there anything in the app api that would let me do this?

**Comment by PVince81** [comment]
You might be able to use a storage wrapper and override the `free_space` method.
Here is an example how to create a storage wrapper: https://github.com/owncloud/files_locking/blob/master/lib/lockingwrapper.php

You need to register it in your app this way: https://github.com/owncloud/files_locking/blob/master/appinfo/app.php#L3 https://github.com/owncloud/files_locking/blob/master/lib/lockingwrapper.php#L198

CC @icewind1991

**Comment by jerrac** [comment]
@PVince81 Thanks for the advice. Unfortunately customizing our OwnCloud implementation like I wanted to was pushed to the back burner here at work. As you can tell by how long it took me to reply... Anyway, I'll revisit this issue if I ever have time to work on it.
