### ISSUE TITLE
SSL Error and Failed Mount with unsigned SSL certs

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#14557]
Working with ownCloud 8.0.1 pre-release, set up a server to server share with a link. When the recipient clicked on the link, they get to the web page with the shared files. All good at this point.

Then the user logged into their ownCloud to add the link as a server to server share. They accepted the share. 

At this point, the use of a self-signed certificate on the initiating server caused the link to not add the server to server share, with a little yellow message at the top about an untrusted certificate.

Given the number of self-signed certificates out there, we need a message that either allows an accept, or not of a self signed certificate, rather than a complete failure to add.

**Comment by LukasReschke** [comment]
From my understanding this is not possible with the core PHP functions. This would give us a hard-dependency on cURL. Which I personally would find reasonable.

cURL is even available on most shared hosting environments and would allow us to get rid of some hacks. – I don't think it would be good to add even more fallbacks and detections and offer fewer features, this will just introduce more technical debt for the sake of supporting some really strange environments :see_no_evil: 

@karlitschek @DeepDiver1975 Feedback required. THX.

**Comment by LukasReschke** [comment]
Mhm… As far I can find in our code some parts already require cURL anyways: https://github.com/owncloud/core/blob/df3c73de728c1b74156fd4d7d8d17fab230cfbb4/apps/files_sharing/lib/external/storage.php#L227-L268

**Comment by RealRancor** [comment]
The docs describes the usage of self-signed certs since a few hours:

https://doc.owncloud.org/server/8.0/admin_manual/configuration/server_to_server_configuration.html#using-self-signed-certificates

Maybe this should also be described in the user manual?

**Comment by LukasReschke** [comment]
The problem is that this is still far away from any user expectation. While you and I are both very technical aware persons most of our users aren't and we need to have as much guidance as possible. That's only something that a wizard can do :)

**Comment by RealRancor** [comment]
Sure, you're absolutely right. It's also not very realistic that all users are reading the manuals so more guidance is probably better.

**Comment by DeepDiver1975** [comment]
This is a know issue - https://github.com/owncloud/core/issues/13175

Let's see if we can come up with a solution for 8.1

**Comment by DeepDiver1975** [comment]
I'd prefer to continue the discussion in https://github.com/owncloud/core/issues/13175
