### ISSUE TITLE
OwnCloud 8: Problem with LDAP Authentication 

### ISSUE THREAD

**Issue by marcosak85** [owncloud/core#14552]
Hello,
my LDAP login is not working.
Wizard say that configuration is correct and domain user are shown correctly in Users tab.
When try to login, it fail and I found this messages in log:

----------------------------------------------------------------------------------------------------------------------

{"reqId":"f963d378e7dfa5101732fd4f8f64b09c","remoteAddr":"192.168.1.246","app":"user_ldap","message":"No group filter is specified, LDAP group feature will not be used.","level":1,"time":"2015-02-26T18:04:16+00:00","method":"POST","url":"\/"}
{"reqId":"f963d378e7dfa5101732fd4f8f64b09c","remoteAddr":"192.168.1.246","app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":0,"time":"2015-02-26T18:04:16+00:00","method":"POST","url":"\/"}
{"reqId":"f963d378e7dfa5101732fd4f8f64b09c","remoteAddr":"192.168.1.246","app":"core","message":"Login failed: 'ownclouduser' (Remote IP: '192.168.1.246', X-Forwarded-For: '')","level":2,"time":"2015-02-26T18:04:21+00:00","method":"POST","url":"\/"}
{"reqId":"7ffbecf153eaad53d5c7a6cbd5f49a8c","remoteAddr":"192.168.1.246","app":"user_ldap","message":"No group filter is specified, LDAP group feature will not be used.","level":1,"time":"2015-02-26T18:04:21+00:00","method":"GET","url":"\/index.php\/core\/js\/oc.js?v=b02c867e67f96e4ed5f55b10f0032d82"}
{"reqId":"e00bdeb4398b8b45a78e56743a9c9deb","remoteAddr":"192.168.1.246","app":"user_ldap","message":"No group filter is specified, LDAP group feature will not be used.","level":1,"time":"2015-02-26T18:04:22+00:00","method":"GET","url":"\/cron.php"}

----------------------------------------------------------------------------------------------------------------------

I've copied settings from OwnCloud 7 that is still working fine.
Is anything change in this version?

**Comment by LukasReschke** [comment]
Thanks a lot for reporting issues back to us!

We need some more information to properly support you with your issue!

Can I ask you to follow our guidelines for submitting bugs as described here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by sentaidigital** [comment]
You may be suffering from #14048 or #14104.  Both are fixed with #14275.

**Comment by DeepDiver1975** [comment]
> You may be suffering from #14048 or #14104. Both are fixed with #14275.

close as duplicate
