### ISSUE TITLE
Updating Owncloud from 7.0.2 to 8.0.0 fails

### ISSUE THREAD

**Issue by master7811** [owncloud/core#14554]
Updating owncloud to version 8 coming from version 7.0.2 fails:

An exception occurred while executing 'ALTER TABLE oc_oc_appconfig_p0rmv62qsv9ss RENAME INDEX appconfig_config_key_index TO oc_qr2royozp3grh': SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'INDEX appconfig_config_key_index TO oc_qr2royozp3grh' at line 1

**Comment by karlitschek** [comment]
Can you post as full bug report using this template please?
https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by DeepDiver1975** [comment]
This is the know MariaDB issue which we will fix with 8.0.1

**Comment by DeepDiver1975** [comment]
@master7811 - you need to upgrade doctrine/dbal in 3rdparty - see https://github.com/owncloud/core/issues/14003#issuecomment-73598450

**Comment by RealRancor** [comment]
@master7811 
Not related to this problem but its also recommended to go to the latest stable 7.x (currently 7.0.4) before doing an upgrade to the next major version (see upgrade documentation).
