### ISSUE TITLE
Version number on upgrade is not being substituted

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#14555]
### Steps to reproduce

1. Install owncloud 6.0.7 using the tarball
2. Upgrade to 7.0.5 using the tarball
3. Finish the upgrade in the UI

### Expected behaviour

The version numbers are correct in the UI

### Actual behaviour

The version number being upgraded to is not substituted

![p293](https://cloud.githubusercontent.com/assets/8480343/6399503/d766d3e8-bdc0-11e4-91bf-9fdbe61da59b.PNG)

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

**Comment by jnfrmarks** [comment]
@karlitschek @DeepDiver1975 

What's the chance of this getting in by next Tuesday for us to test on Wednesday?

**Comment by LukasReschke** [comment]
Known issue … Let me search if I find them or if they are already fixed somewhere :eyes:

**Comment by LukasReschke** [comment]
Looks like https://github.com/owncloud/core/issues/12204 which has been fixed with https://github.com/owncloud/core/pull/13341, however that patch is only in starting with v8.0.0 as can be seen at https://github.com/owncloud/core/commit/99304be4ef4c34e60c1b2f2d1589a9678a893181

**Comment by jnfrmarks** [comment]
ok - validated that it works as expected with 8.0.  

@karlitschek @DeepDiver1975 

Do we want to backport for 7.0.5 or leave this be?

**Comment by karlitschek** [comment]
Not critical but if someone needs a break from the more difficult work and wants to do something more relaxing than please backport this :-)

**Comment by DeepDiver1975** [comment]
@nickvergessen backport pr please - THX

**Comment by DeepDiver1975** [comment]
scheduled for 7.0.6 - 7.0.5 is closed from my perspective

**Comment by MorrisJobke** [comment]
Backport is merged: #14637
