### ISSUE TITLE
Files corrupted after messing with the encryption app

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#14562]
### Steps to reproduce
1. Enable the encryption app
2. Log out and log in to initialize the encryption keys and encrypt the files
3. Upload several files
4. Disable the encryption app
5. Go to the personal page to decrypt your files (enter the correct password)
6. Make sure you don't restores neither delete the keys (don't click the respective buttons)
7. Enable the encryption app again
8. Log out and log in again to generate new keys
9. Disable the encryption app another time.
10. Go to the personal page.
11. Click in the "restore keys" button without decrypting the files. _The call seems to get stuck_
12. Go to the file view to download a file

### Expected behaviour
The file is downloaded correctly

### Actual behaviour
A corrupted files is downloaded, probably a badly decrypted file

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** stable8

**Updated from an older ownCloud or fresh install:** fresh install

### Notes
Probably step 11 shouldn't be possible as it might be the main reason of this issue as you might be restoring the wrong keys.
Also, the corrupted files are limited to this account. Other account files seems to be fine. New uploaded files in this account can be downloaded normally.

**Comment by karlitschek** [comment]
Interesting bug @schiesbn

**Comment by PVince81** [comment]
@schiebn obsolete ?

**Comment by PVince81** [comment]
@schiesbn obsolete ?

@jvillafanez still happening in 8.1.3 or 8.2rc1 ?

**Comment by jvillafanez** [comment]
I think it's obsolete because the UI is different, as well as the app, unless we want to solve it in the old encryption app

The problem was with the "restore key" option that isn't longer available in the encryption 2.0.

@owncloud/qa Has a similar scenario been taken into account, with the recovery key password option?

**Comment by rperezb** [comment]
@SergioBertolinSG does it make you ring any bell? thx

**Comment by PVince81** [comment]
@schiesbn @jvillafanez @SergioBertolinSG should we close this then ?

**Comment by schiesbn** [comment]
Of course if you restore old keys and overwrite exiting new keys the files will be broken. But this is nothing we can decide on code level. If the admin decides to restore keys we need to expect that he knows what he is doing.

@jvillafanez @SergioBertolinSG feel free to re-open it if you think this is still a issue
