### ISSUE TITLE
Update UI: stop automatic redirect in case there are warnings

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#14569]
Whenever warnings are displayed in the update UI after an update, the user/admin does not have a chance to see it or copy it.

The behavior should be changed as follows: if warnings were displayed, disable automatic redirect.

The warnings I was thinking about were things like:
- some third party apps were disabled
- some legacy storages could not be repaired automatically

@DeepDiver1975 @owncloud/designers

**Comment by DeepDiver1975** [comment]
true story - thx

**Comment by jancborchardt** [comment]
Great point indeed. Then instead of automatically redirecting, we need to display a button: »Return to ownCloud« (of course only if the errors weren’t breaking).

Basically that can be a simple reload, if that would do it – but we need a button cause we can’t expect people to know they need to refresh.

**Comment by MorrisJobke** [comment]
> Then instead of automatically redirecting, we need to display a button: »Return to ownCloud« (of course only if the errors weren’t breaking).

This would just lead again to the upgrade page. Or am I wrong?

**Comment by PVince81** [comment]
There are two situations:
1) When there are errors, it already shows in red the exception and "Please reload the page". After reload, the update button is there again.

2) When there are warnings, it currently redirects directly to ownCloud because it was not fatal. Here we want to have a button "Return to ownCloud" that will do the redirect on click, not automatically.

**Comment by MorrisJobke** [comment]
> 2) When there are warnings, it currently redirects directly to ownCloud because it was not fatal. Here we want to have a button "Return to ownCloud" that will do the redirect on click, not automatically.

Ah okay ... Got it

**Comment by jancborchardt** [comment]
> 1) When there are errors, it already shows in red the exception and "Please reload the page". After reload, the update button is there again.

Don’t we want a button here directly as well? Something like »Retry update«? Instead of needing to first reload the page and then clicking »Update« again?

**Comment by PVince81** [comment]
Yeah, that makes sense. Could be done as part of this fix.

**Comment by te-online** [comment]
@PVince81 Short question: What do you mean with update UI? The UI of the updater app?

**Comment by PVince81** [comment]
No... whatever I say on Github I never ever refer to the updater UI :wink: 

I was referring to this page:
![update_ui](https://cloud.githubusercontent.com/assets/277525/6504192/e0227d92-c334-11e4-8f29-9f8c10f9a9cd.png)

This page is not part of the updater app but part of core. (completely independent from updater app)

**Comment by te-online** [comment]
Thanks and sorry, now I see what you mean! :wink:

To be precise concerning the link between the core update process and the updater app: I think, this UI appears when you click »Proceed« in the updater app UI after it copied the files. 

And I agree, there shouldn't be a redirect if messages appear :+1:

Btw: The naming is confusing, isn't it? An administrator has to click *update* twice: One click for backuping, downloading and unziping (in the updater app UI) and one click on »Start update« (on the screen above). I don't know how to solve this. Maybe the caption could be changed to »Proceed update« or something... (Well, okay, you might call this a minor inconsistency, I know :grin:).

**Comment by carlaschroder** [comment]
@PVince81 , that's a meaningless distinction to the poor harried ownCloud admin, and also doc writer, because to us the UI is the app. If it's not the app then what is it doing there, and where is the danged Updater app? Sorry, I know the devs work hard and are doing amazing work, but this is a confusing situation, and it doesn't help to tell people "Oh, that's not the Updater app! It just tells you when there are updates and then performs the updates when you click on it!"

**Comment by carlaschroder** [comment]
Sorry, I'm not trying to be difficult, I'm just trying to figure this out because I'm getting conflicting explanations.

**Comment by te-online** [comment]
@carlaschroder I can totally understand your point of view. Problem is that you can't speak of *the* ownCloud admin. Some admin might be used to download all the stuff manually – not even thinking of using the updater app. Another admin might run ownCloud with very limited knowledge and is dependent on the app to work as expected. That's a tricky situation, but it that can't be avoided without stating that e.g. using the updater app is kind of »default« way and every other way is only for »pro-admins«.

While this is still a bit confusing and floating, I think, we can tell users that there are different ways to *prepare* an update/upgrade (manually, app, command line, whatever), but actually only two ways for *applying* the update/upgrade: clicking »start« on the website or using the command line to do this.

**Comment by oparoz** [comment]
And make sure the redirect takes the user back to /. Currently it traps users in endless redirects when the app they were using before the upgrade has been disabled.

**Comment by jancborchardt** [comment]
Was this fixed meanwhile? @DeepDiver1975 @MorrisJobke @PVince81 what’s the call?

**Comment by MorrisJobke** [comment]
> Was this fixed meanwhile?

No.

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/17436

**Comment by PVince81** [comment]
Fixed through https://github.com/owncloud/core/pull/17436
