### ISSUE TITLE
Show remote user's avatar for server to server shares

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#14564]
Share a folder with a remote user, for example "remoteuser@remotehost.com/owncloud".

Now that there are avatars in the share dropdown, it would be nice to be able to show avatars from remote users.

For this, we need to add a OCS Share API to allow retrieving remote user avatars

I'd say this API should only work once the share was accepted, for security purposes (CC @LukasReschke)

The remote avatars could be cached locally too in case some are used often.

@owncloud/designers @rullzer

**Comment by rullzer** [comment]
So I have been thinking about this.

1. We can just send the share token along. So the url would be something like... avatar/remote/{user}/{size}/{token}. Now this would require passing the share token around.
2. We can send the requesting user. So the url then becomes something like: avatar/remote/{user}/{size}/{remoteUser}.

I think option 2 is better.
However both would reqruire an extention to the OCP Share Class, or direct calls to the OC Share class. Since we need to obtain the list of remote shares for {user} and then find the share with {token} or a share with {remoteUser}. The share might have to be accepted but a check for that should not be to hard, and of course only required in case of a call from the sharer..

This seems like a good first step. Caching can then be added later. I'll see if i can come up with a PR somewhere this week.

**Comment by rullzer** [comment]
On a (somewhat) unrelated note: it seems like converting the avatar stuff to the AppFramework is non trivial because of the imagejpeg call in $image->show().

I'll look into this since it would be nice to do that right away.

**Comment by rullzer** [comment]
Initial PR at #14856

**Comment by jancborchardt** [comment]
@rullzer @MorrisJobke can this be closed now that https://github.com/owncloud/core/pull/14856 has been merged?

**Comment by DeepDiver1975** [comment]
> @rullzer @MorrisJobke can this be closed now that #14856 has been merged?

it was wrong to merge the pr - will revert - issue goes to 9.0

**Comment by rullzer** [comment]
We should rethink this now that we can sync federated address books.
But is not going to be 9.0.. @PVince81 @cmonteroluque

**Comment by MorrisJobke** [comment]
> But is not going to be 9.0.. @PVince81 @cmonteroluque

Updating milestone

**Comment by cmonteroluque** [comment]
@MorrisJobke agreed

**Comment by AndyScherzinger** [comment]
Can we commit on 9.1 in some way since we, android app, want to integrate this :)
https://github.com/owncloud/android-library/issues/107

**Comment by rullzer** [comment]
@MTRichards FYI

**Comment by rullzer** [comment]
Also related to https://github.com/owncloud/core/issues/22414

**Comment by MTRichards** [comment]
Will take it into account when planning - short answer is maybe! It is all a matter of priorities...

**Comment by guruz** [comment]
Desktop is also looking forward to it for activity list, share dialog and maybe even account toolbar in settings dialog.

**Comment by AndyScherzinger** [comment]
@rullzer any news on avatars? :)

**Comment by rullzer** [comment]
not yet. We have to rethink how we handle avatars. Since they are now stored in the systems address book. So we could fetch them there. But then again we want to cache them resized as well and all. But that will take time...

**Comment by AndyScherzinger** [comment]
Thanks for the update! On the Android side we would and do a caching of the avatars too :)

**Comment by rullzer** [comment]
I see no way this makes it into 9.1. CC: @PVince81

**Comment by PVince81** [comment]
Yeah, we're past feature freeze and this needs some new APIs.
Moving to 9.2

**Comment by daorte** [comment]
Hi, 
About the ubication of the OCS API and how the calls are made in the android library, i ask some questions on owncloud/android-library#132 and owncloud/android-library#107 but apparently it is related to server side and how the services are exposed

**Comment by PVince81** [comment]
@DeepDiver1975 is the DAV resource available publicly or needs auth ? https://github.com/owncloud/core/pull/26872

If no auth then it would be possible to use it for federated shares.
If auth, then it needs to somehow use the fed shares tokens to access a specific avatar for the sharer or all share participants.

**Comment by PVince81** [comment]
moving to backlog, but would be good to schedule this at some point @pmaier1 

@DeepDiver1975 any estimate on difficulty ? if we can reuse the new avatar retrieval endpoint from 10.0 ?
