### ISSUE TITLE
There's a delay when marking a slow remote storage as a favorite

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#14560]
### Steps to reproduce
1. Install owncloud 
2. configure S3 storage - my storage connection is slow
3. upload a file
4. mark the folder as a favorite
5. Click on the favorites page
### Expected behaviour

The folder shows up in the favorite page
### Actual behaviour

There's a delay before folder shows up.  Same with if I uncheck the folder as a favorite.  
### Server Host info:

CentOS release 6.6 (Final)
PHP 5.4.36
### Server configuration

ownCloud Enterprise Edition 8.0 (daily) Build:2015-02-26T05:30:39+00:00 bc1418156339d4e61fe81bd1474f91555432ca00

**Comment by PVince81** [comment]
I guess that some code might try and get the file info of that file and that triggers the update check for the remote file/folder.

**Comment by PVince81** [comment]
closing, too low severity
