### ISSUE TITLE
Sharing a file with a link using a password doesn't aware you of its limit.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#14578]
### Steps to reproduce

1. Share a file using a link with a password.

Use this as password:
```
111111111111111111111111111111111111111111111111111111111111111111111111222222
```

2. Open the link in another browser.
    Put 
```
111111111111111111111111111111111111111111111111111111111111111111111111
```
 as password.

### Expected behaviour
An alert is opened telling you that only first 72 chars are being used.

### Actual behaviour
You can put passwords >72 chars without alert and later access the file with the first 72 chars.

**Comment by PVince81** [comment]
@rullzer if you're looking for another challenge :wink: 

The share dropdown might be missing validation for the password field.
Not sure if the OCS Share API itself validates either.

**Comment by PVince81** [comment]
Also CC @schiesbn

**Comment by LukasReschke** [comment]
This is a bcrypt limitation, however we can't assume the maximum length since you can't guarantee the underlying used hash mechanism.

IMHO accepted behaviour for me when documented.

**Comment by LukasReschke** [comment]
Also valid for user passwords etc…

**Comment by nickvergessen** [comment]
So just display and verify the max password length in all the places?

**Comment by rullzer** [comment]
That would get horribly messy if you have to support multiple hashing algorithms with different input lengths

**Comment by nickvergessen** [comment]
Well only one is used at a time, so we just add something like validateLength() and getMaxLength(), to validate and display the max length in the UI.

**Comment by LukasReschke** [comment]
@carlaschroder Can you document that ownCloud uses the bcrypt algorithm and thus for security and performance reasons (namely: Denial of Service as CPU power increases exponentially) only verifies the first 72 character of passwords? (in nearly all contexts such as sharing etc…)

**Comment by carlaschroder** [comment]
@LukasReschke Sure, though the likelihood of anyone ever getting bitten by this seems small.

**Comment by carlaschroder** [comment]
https://github.com/owncloud/documentation/issues/1113
