### ISSUE TITLE
ldap user mapping broken

### ISSUE THREAD

**Issue by hengels7** [owncloud/core#14576]
### Steps to reproduce
configure ldap user mapping for an ads:
login filter is (&(objectClass=person)(cn=%uid))
internal username is uid
uuid-attribute for user is cn
case insensitivity is activated

I tried to clear the mappings several times, even removed all accounts by applying an erroneous user filter and waiting for the trigger to remove all users.

### Expected behaviour
usernames should be the same as the cns

### Actual behaviour
usernames look like _1203, _2972, ... as if all cns were "" and thus and all names were colliding ..

example: a user with the unique cn=achieng.den1234 gets the correct displayName, is member of the correct group, but is assigned the username _5402 .. 

### Server configuration
ubuntu server 14.10

**Web server:**
apache

**Database:**
mysql

**PHP version:**
5.5.12

**ownCloud version:** (see ownCloud admin page)
8.0

**Updated from an older ownCloud or fresh install:**
fresh install

**List of activated apps:**
ldap user and group backend

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'ocltz554x9ts',
  'passwordsalt' => 'l8IOjdt1zyrQHCEynVSgfUrBb9zOP.',
  'secret' => 'CWMbK./nH5KnQXyhX8uFAqOYK5k6vizTE82F8R4AV3Hn9Wny',
  'trusted_domains' => 
  array (
    0 => '192.168.0.87',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://192.168.0.87/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.0.7',
  'dbname' => 'cloudy',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_cloudy',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
ldap user and group backend with an ads

#### LDAP configuration (delete this part if not used)

| user_ldap | cleanUpJobOffset                  | 50                                         |
| user_ldap | enabled                           | yes                                        |
| user_ldap | has_memberof_filter_support       | 1                                          |
| user_ldap | home_folder_naming_rule           | attr:cn                                    |
| user_ldap | installed_version                 | 0.5.0                                      |
| user_ldap | last_jpegPhoto_lookup             | 0                                          |
| user_ldap | ldap_agent_password               | somepassword                               |
| user_ldap | ldap_attributes_for_group_search  |                                            |
| user_ldap | ldap_attributes_for_user_search   | displayName
cn                             |
| user_ldap | ldap_backup_host                  |                                            |
| user_ldap | ldap_backup_port                  |                                            |
| user_ldap | ldap_base                         | dc=schule,dc=local                         |
| user_ldap | ldap_base_groups                  | dc=schule,dc=local                         |
| user_ldap | ldap_base_users                   | dc=schule,dc=local                         |
| user_ldap | ldap_cache_ttl                    | 600                                        |
| user_ldap | ldap_configuration_active         | 1                                          |
| user_ldap | ldap_display_name                 | displayname                                |
| user_ldap | ldap_dn                           | cn=ldapuser,ou=Benutzer,dc=schule,dc=local |
| user_ldap | ldap_email_attr                   | mail                                       |
| user_ldap | ldap_experienced_admin            | 0                                          |
| user_ldap | ldap_expert_username_attr         | uid                                        |
| user_ldap | ldap_expert_uuid_group_attr       | cn                                         |
| user_ldap | ldap_expert_uuid_user_attr        | cn                                         |
| user_ldap | ldap_group_display_name           | cn                                         |
| user_ldap | ldap_group_filter                 | objectClass=group                          |
| user_ldap | ldap_group_filter_mode            | 1                                          |
| user_ldap | ldap_group_member_assoc_attribute | member                                     |
| user_ldap | ldap_groupfilter_groups           | Benutzer                                   |
| user_ldap | ldap_groupfilter_objectclass      | group                                      |
| user_ldap | ldap_host                         | someserver                               |
| user_ldap | ldap_login_filter                 | (&(objectClass=person)(cn=%uid))           |
| user_ldap | ldap_login_filter_mode            | 1                                          |
| user_ldap | ldap_loginfilter_attributes       | cn                                         |
| user_ldap | ldap_loginfilter_email            | 0                                          |
| user_ldap | ldap_loginfilter_username         | 0                                          |
| user_ldap | ldap_nested_groups                | 1                                          |
| user_ldap | ldap_nocase                       | 1                                          |
| user_ldap | ldap_override_main_server         | 0                                          |
| user_ldap | ldap_paging_size                  | 500                                        |
| user_ldap | ldap_port                         | 389                                        |
| user_ldap | ldap_quota_attr                   |                                            |
| user_ldap | ldap_quota_def                    |                                            |
| user_ldap | ldap_tls                          | 0                                          |
| user_ldap | ldap_turn_off_cert_check          | 0                                          |
| user_ldap | ldap_user_filter_mode             | 1                                          |
| user_ldap | ldap_userfilter_groups            | Benutzer                                   |
| user_ldap | ldap_userfilter_objectclass       | person                                     |
| user_ldap | ldap_userlist_filter              | objectClass=person                         |
| user_ldap | ocsid                             | 166061                                     |
| user_ldap | types                             | authentication                             |

#### ownCloud log (data/owncloud.log)
lots of ..

{"reqId":"d24eeb667c37db55531a043f9b80a12b","remoteAddr":"192.168.0.233","app":"core","message":"DB Error: \"An exception occurred while executing 'INSERT INTO `oc_ldap_user_mapping` (`ldap_dn`,`owncloud_name`,`directory_uuid`) SELECT ?,?,? FROM `oc_ldap_user_mapping` WHERE `ldap_dn` = ? AND `owncloud_name` = ? AND `directory_uuid` = ? HAVING COUNT(*) = 0' with params [\"cn=m.28,ou=uef-relax,ou=berufskolleg,ou=schueler,ou=benutzer,dc=schule,dc=local\", \"_2806\", \"M.28\", \"cn=m.28,ou=uef-relax,ou=berufskolleg,ou=schueler,ou=benutzer,dc=schule,dc=local\", \"_2806\", \"M.28\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '_2806' for key 'PRIMARY'\"<br \/>Offending command was: INSERT INTO `*PREFIX*ldap_user_mapping` (`ldap_dn`,`owncloud_name`,`directory_uuid`) SELECT ?,?,? FROM `*PREFIX*ldap_user_mapping` WHERE `ldap_dn` = ? AND `owncloud_name` = ? AND `directory_uuid` = ? HAVING COUNT(*) = 0<br \/>","level":4,"time":"2015-02-27T07:35:54+00:00"}
{"reqId":"d24eeb667c37db55531a043f9b80a12b","remoteAddr":"192.168.0.233","app":"core","message":"DB Error: \"An exception occurred while executing 'INSERT INTO `oc_ldap_user_mapping` (`ldap_dn`,`owncloud_name`,`directory_uuid`) SELECT ?,?,? FROM `oc_ldap_user_mapping` WHERE `ldap_dn` = ? AND `owncloud_name` = ? AND `directory_uuid` = ? HAVING COUNT(*) = 0' with params [\"cn=schuehle.nik8040,ou=2bfp22_b,ou=bfs,ou=schueler,ou=benutzer,dc=schule,dc=local\", \"_1244\", \"schuehle.nik8040\", \"cn=schuehle.nik8040,ou=2bfp22_b,ou=bfs,ou=schueler,ou=benutzer,dc=schule,dc=local\", \"_1244\", \"schuehle.nik8040\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '_1244' for key 'PRIMARY'\"<br \/>Offending command was: INSERT INTO `*PREFIX*ldap_user_mapping` (`ldap_dn`,`owncloud_name`,`directory_uuid`) SELECT ?,?,? FROM `*PREFIX*ldap_user_mapping` WHERE `ldap_dn` = ? AND `owncloud_name` = ? AND `directory_uuid` = ? HAVING COUNT(*) = 0<br \/>","level":4,"time":"2015-02-27T07:35:56+00:00"}

.. but I think, this is not related, because yesterday the same problem occured and I didn't see these messages.

**Comment by karlitschek** [comment]
@blizzz Can you have a look?

**Comment by blizzz** [comment]
AD does not have 'uid' attribute. Use 'cn' as well as internsl usernane attribute.

**Comment by hengels7** [comment]
sorry .. I thought this was meant to be the owncloud internal attribute name .. I didn't understand the documentation here .. now it's working fine

thanks,

holger

**Comment by blizzz** [comment]
@hengels7  glad it works for you now. ownCloud will have  an internal name it refers the user to. This will be created based upon the "owncloud internal attribute name" settings, which defaults to the corresponding UUID in LDAP/AD.
