### ISSUE TITLE
Wrong Link to Dev Manual on Apps Page 8.0

### ISSUE THREAD

**Issue by carlaschroder** [owncloud/core#14589]
Not sure where to change this-- the 'Add Your App' link on the Apps page in 8.0 is https://owncloud.org/dev, which redirects to the 7.0 manual at https://doc.owncloud.org/server/7.0/developer_manual/app/index.html. Surely it should go to the 8.0 version?

**Comment by LukasReschke** [comment]
@tomneedham THX.

**Comment by tomneedham** [comment]
Fixed. It's in the .htaccess on oc.org. We should update the link in core to use go.php maybe?

**Comment by carlaschroder** [comment]
Thank you! :D
