### ISSUE TITLE
Some artifacts are missing after upgrading from 7 to 8

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#14598]
### Steps to reproduce

1. Install owncloud 7.0.5
2. Upgrade to 8.0.1
3. Navigate to the Apps page
4. Click on the down arrow for the installed apps 
5. Click on the files page

### Expected behaviour

The apps page has all the same links as in a straight 8.0.1 installation, the skeleton files and directories are present, and the Photos app shows up in the dropdown list.

### Actual behaviour

The apps page is missing links, the skeleton directories are missing, and the Photos app is missing from the dropdown list.

8.0.1 fresh install:

![p296](https://cloud.githubusercontent.com/assets/8480343/6421764/f03c3ed2-be9f-11e4-8643-4e77441d6c6a.PNG)

![p298](https://cloud.githubusercontent.com/assets/8480343/6421773/05d07074-bea0-11e4-93b8-955795864198.PNG)

![p300](https://cloud.githubusercontent.com/assets/8480343/6421787/36ea3064-bea0-11e4-92ad-7ce866d4927d.PNG)

8.0.1 after upgrade:

![p297](https://cloud.githubusercontent.com/assets/8480343/6421769/fe460cce-be9f-11e4-9d1b-ba84591a09ff.PNG)

![p299](https://cloud.githubusercontent.com/assets/8480343/6421775/09c49ae8-bea0-11e4-9e99-58f2354732e3.PNG)

![p301](https://cloud.githubusercontent.com/assets/8480343/6421792/3c07a090-bea0-11e4-892b-05e6a3db5ba2.PNG)

### Server Host info:

CentOS release 6.6 (Final)
PHP 5.4.36

### Server configuration

ownCloud Enterprise Edition 8.0 (daily) Build:2015-02-27T04:33:31+00:00 5faf9f819212eb0d2321fe324831b941a215819e

**Comment by jnfrmarks** [comment]
The skeleton files are present when new users gets created so that is not an issue.

**Comment by karlitschek** [comment]
yes. Expected behavior
