### ISSUE TITLE
Upgrade fails to 8.0.0 from 7.0.4.2 on postgres

### ISSUE THREAD

**Issue by mitzip** [owncloud/core#14595]
<pre>An exception occurred while executing 'ALTER TABLE oc_oc_share_external_ugbfwn5zoee01 ADD "remote_id" INT NOT NULL':
                                                                                                                                                               
SQLSTATE[23502]: Not null violation: 7 ERROR:  column "remote_id" contains null values</pre>

I had one external share that wasn't important so I just deleted it via the psql CLI. Upgrade then  proceeded successfully.

**Comment by LukasReschke** [comment]
Should be fixed with the upcoming 8.0.1, see https://github.com/owncloud/core/pull/14533

**Comment by LukasReschke** [comment]
If you by any chance still have the data it would be interesting to see if that worked for you :smile:

**Comment by mitzip** [comment]
You'd like to see the record I deleted?
