### ISSUE TITLE
WebDAV interface seems to be broken when using Firefox 36.0

### ISSUE THREAD

**Issue by j-ed** [owncloud/core#14590]
## Expected behavior
ownCloud should work with all available web browsers, like e.g. Firefox 36.0.

## Actual behavior
After upgrading Firefox to v36.0 ownCloud doesn't show mounted WebDAV shares anymore (directory empty) [**picture 1**] and the error `Your web server is not yet properly setup to allow files synchronization because the WebDAV interface seems to be broken."` is shown in the Admin menu [**picture 3**]. Additionally no contacts are shown anymore (spinning wheels) [**picture 2**]
I first thought that the whole server configuration is broken but I don't have any problems if I use Firefox v35.0.1 or Internet Explorer v11.0.9600.17633 to access ownCloud. No error messages are shown in the Admin menu either.

picture 1: 
![20150227_oc8_ff360_files](https://cloud.githubusercontent.com/assets/2572764/6417972/a1b718ba-beb1-11e4-8949-038c73e3c714.jpg)

picture 2:
![20150227_oc8_ff360_contacts](https://cloud.githubusercontent.com/assets/2572764/6417983/af5cefc6-beb1-11e4-8f7f-31a6a582b766.jpg)

picture 3:
![20150227_oc8_ff360_admin](https://cloud.githubusercontent.com/assets/2572764/6417987/ba3acddc-beb1-11e4-9147-2dcc97d516f0.jpg)

## Steps to reproduce problem
1. use Firefox Browser 36.0 to access ownCloud

#### Server Configuration
OS: Linux 3.2.54
Web server: Apache2 2.4.10
Database: MySQL 5.1.73
PHP version: 5.4.38
ownCloud version: 8.0.0

#### Client Configuration
Browser: Firefox 36.0 (not working!)
Browser: Firefox 35.0.1 / IE 11.0.9600.17633 (no problems)
Operating system: Windows 7

**Comment by PVince81** [comment]
With WebDAV shares are you talking about server to server shares aka ownCloud federation ?

**Comment by j-ed** [comment]
I've added WebDAV shares from a NAS server but I think there must be a general WebDAV recognition problem because of the error message in the Admin menu.

**Comment by j-ed** [comment]
I've just tested the direct WebDAV access by entering the following URL in the FF 36.0 address field and it works like a sharm: `https://my-server.local.lan/owncloud/remote.php/webdav/`
All directories and files, which should usually by shown by the Files app, are displayed.

**Comment by RealRancor** [comment]
@j-ed 
Your second post doesn't really show that much as this is a simple GET request done by FF. The WebDAV check is doing a PROPFIND request which is very likely not working.

Have a look at your data/owncloud.log or maybe also at this FAQ thread: https://forum.owncloud.org/viewtopic.php?f=17&t=7536

**Comment by LukasReschke** [comment]
> Your second post doesn't really show that much as this is a simple GET request done by FF. The WebDAV check is doing a PROPFIND request which is very likely not working.

Indeed. Which is also an argument why with ownCloud 8.1 we will not show anymore directory listings on a GET :)

**Comment by j-ed** [comment]
I've already read the tips from @RealRancor but they only make sense from my point of view if there is a general server issue, but seems not the case. I can definitely access the ownCloud server from the same PC using IE 11 and FF 35.x and all files and functions can be used without a problem except if I use FF 36.x. Could you agree to this analysis?

Therefore I would assume that the problem should be related to a component or script code which is handled differently in FF 36.0 than in the other browsers. I've already checked the owncloud.log and the Apache2 web server logs without finding any error message.

**Comment by RealRancor** [comment]
Hi,

nice observation / write-up.

If its an FF 36 only problem have you considered to report this to the mozilla bugtracker or maybe ask also in a Mozilla community what was changed between FF 35 and 36 which is causing that seen behavior?

**Comment by j-ed** [comment]
The problem is, that I've only observed problems with ownCloud and no other website until now. Additionally I'm not a programmer at all so that I do not really understand what I should ask for. Usually you need to provide at least a minimum of information to the developers so that they could get hold of a problem. Only telling them "it works with FF 35.x, but not with FF 36.x" might not be enough.
Due to the fact that the problem popped-up in ownCloud I though someone
a) could reproduce it and
b) has an idea what causes the problem or how the problem could be narrowed down.

**Comment by RealRancor** [comment]
Ah, sorry. Thought you have some knowledge to report this.

**Comment by RealRancor** [comment]
Mhhh, just have updated to FF 36 on Debian Wheezy and don't see this issue at my OC 7.0.4 installation or on https://demo.owncloud.org/index.php/settings/admin (OC 8.0.0)

**Comment by j-ed** [comment]
I've now compared a backup of my original ownCloud configuration file with the new one which is part of the ownCloud package and which I used as a template for the new installation. I found out that `custom_csp_policy` parameter has been added by default. After deleting this parameter I'm able to access my ownCloud server again with FF 36.
I ran some more tests and found out that the original parameter entry from the `config.sample.php` looks like this:
```
'custom_csp_policy' =>
    "default-src 'self'; script-src 'self' 'unsafe-eval'; ".
    "style-src 'self' 'unsafe-inline'; frame-src *; img-src *; ".
    "font-src 'self' data:; media-src *; connect-src *",
```
Some internal ownCloud processes are forcing a rewrite of this parameter to:
```
'custom_csp_policy' => 'default-src \'self\'; script-src \'self\' \'unsafe-eval\'; style-src \'self\' \'unsafe-inline\'; frame-src *; img-src *; font-src \'self\' data:; media-src \\*; connect-src \\*',
```
I don't know what is wrong with it and why it had worked with FF 35 but not with FF 36, nevertheless after I've removed the entry everything is working fine again.

**Comment by j-ed** [comment]
Any further information required?

**Comment by PVince81** [comment]
@j-ed is this still happening with 8.0.5 and newer Firefox versions ?

**Comment by j-ed** [comment]
I've tested it with 8.0.5 and FF 39.0 and everything seems to work fine now.

**Comment by PVince81** [comment]
Thanks, closing
