### ISSUE TITLE
Storage full msg for a shared folder is kept for others

### ISSUE THREAD

**Issue by luizluca** [owncloud/core#14597]
Hello,

User A have a shared folder F with User B. When User A quota is over, user B receives this msg when entering the folder F:

"Your storage is full, files can not be updated or synced anymore!"

This is not really correct as it is not user's storage that is full but user A quota that is over.

However, if I go back to root folder, the msg is kept visible.

If I upload any files for the foldef F (which will fail) and go back to my root folder, when I try to upload a file, I get this msg:

"Not enough free space, you are uploading 44 kB but only NaN undefined is left"

But the file is uploaded.

**Comment by PVince81** [comment]
Maybe need to add a timeout to that message, or explicitly discard it when the folder is changed.

**Comment by nickvergessen** [comment]
The later sounds better to me

**Comment by PatelParas** [comment]
I will fix it.....

**Comment by PVince81** [comment]
Message will be obsoleted once we move to sending a user notification.

Unless someone wants to send a PR with a quick fix for this, won't fix.
