### ISSUE TITLE
Execute unit tests with installed files_locking app

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#14592]
@jnfrmarks found multiple bugs related to files_locking  and I'm pretty sure we would have catched them as well if CI would execute the unit tests with that enabled app?

cc @DeepDiver1975 Inputs?

**Comment by PVince81** [comment]
@DeepDiver1975 are we now running unit tests with files_locking enabled ? (the old one)

**Comment by LukasReschke** [comment]
Irrelevant for the future.
