### ISSUE TITLE
Add "login as user" feature

### ISSUE THREAD

**Issue by luizluca** [owncloud/core#14599]
Hello,

It would be interesting for an admin to login into another user's account without a password.
I guess encrypted files would be kept unreadable but for all others, this would be great.

As admin users normally already have filesystem access to owncloud server, this would not be a
a big security concern.

**Comment by DeepDiver1975** [comment]
This will fail in main situations
- in case encryption is enabled as we require the user password to get access to the keys
- in case external mounted filesystems require the user password
- in some authentication scenarios as well - e.g. ldap, shibboleth ...

**Comment by JimLoose** [comment]
-1

sounds more like a plugin request not a default feature!

**Comment by blizzz** [comment]
There is an app for this: https://github.com/owncloud/impersonate/
