### ISSUE TITLE
Failed to parse time string on trying to import root certificate

### ISSUE THREAD

**Issue by joejoe2010** [owncloud/core#14594]
Hi guys,
I tried to import a root certificate over the admin panel but this didn't work.
Checking the log I saw the following issue.
DateTime::__construct(): Failed to parse time string (@) at position 0 (@): Unexpected character at owncloud/lib/private/security/certificate.php#42

I use version 8.0 stable with server encryption enabled. I'm using an external storage drive over webDAV.

Any ideas?

**Comment by karlitschek** [comment]
@schiesbn @LukasReschke

**Comment by LukasReschke** [comment]
Can you by any chance share the root certificate with us? – Otherwise this only is a lot of guessing ;)

**Comment by nickvergessen** [comment]
Also please use the issue template:
https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by joejoe2010** [comment]
thank you guys for your replies.
What is the normal file ending of a root certificate? Perhaps I uploaded a certificate that is not intended to be a root certificate.
