### ISSUE TITLE
Toogle show/hidden system files, temporary, .DS_Store,.... in the web client...

### ISSUE THREAD

**Issue by aqxavier** [owncloud/core#14602]
I'm looking for some option to perform this task, but can not find ..
I think it would be extremely importance can hide these file types to prevent the listing becoming dirty.

Regards,
Alexandre

**Comment by nickvergessen** [comment]
You can also change your client to ignore those files, so they are not synced at all.

**Comment by LukasReschke** [comment]
Looks like a duplicate of https://github.com/owncloud/core/issues/2589 to me

**Comment by aqxavier** [comment]
The modification to clients (Mac / Pc) and mobiles. I had accompanied the discussion.
I'm referring to web clients ....
Did not find any solution to the case.
