### ISSUE TITLE
Provide CONTRIBUTING.md for all repositories

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#14609]
Hi,

recently i have seen that many repositories like:

https://github.com/owncloud/calendar/
https://github.com/owncloud/contacts/
https://github.com/owncloud/documents/
https://github.com/owncloud/updater/

and so on doesn't provide a CONTRIBUTING.md linking to the issue template. Often the file gets no attention by the issue reporter but i think at least it should be there in all repositories.

**Comment by rakekniven** [comment]
:+1:

**Comment by Xenopathic** [comment]
@RealRancor Could you send PRs to those repositories containing a copy of the CONTRIBUTING.md we have here at core? That'll be the easiest way to fix this issue (which shouldn't really be in the core issue tracker anyway...)

**Comment by RealRancor** [comment]
I think a 1to1 copy of CONTRIBUTING.md from core is a little bit overkill as those copies needs to be also maintained on each repos. Maybe just a short note for the issue template and a link to the core CONTRIBUTING.md?

The reported issue here in core is just to avoid tons of duplicate reports in each own repository as most of the app devs are also reading here.

**Comment by RealRancor** [comment]
Btw. it also makes more sense if some one with direct commit permissions are just uploading this file to each repos.

For me cloning each repos and creating a PR for each means a lot of effort.

**Comment by RealRancor** [comment]
Good example for all other repositories could be: https://github.com/owncloud/calendar/pull/839

**Comment by RealRancor** [comment]
Some PRs created above

**Comment by Xenopathic** [comment]
Nice. Time to close this I think :smile:

**Comment by RealRancor** [comment]
Did a PR marathon, happy merging :see_no_evil:
