### ISSUE TITLE
oc8 tar results in oc4.0.4 installation

### ISSUE THREAD

**Issue by mrmee** [owncloud/core#14612]
i installed from a owncloud-8.0.0.tar.bz2 file to a raspberry pi. but the installed oc shows version 4.0.4.

md5 of the tar-file is: d2c1366be0756c24e1f5cfc02f80269f

do i have a corrupted installation and should do a whole fresh raspbian-setup or can i "just" upgrade to a hopefully working oc8 and keep my data-base?

**Comment by LukasReschke** [comment]
That is strange. The md5 sum seems to match. How did your `version.php` look like?

**Comment by mrmee** [comment]
version.php:
<?php 
$OC_Version = array(8,0,0,7);
$OC_VersionString = '8.0';
$OC_Channel = 'stable';
$OC_Build = '2015-02-07T02:34:55+00:00 df2808eec840c033b952e001ee8a063a93fae417$

but status.php:
{"installed":"true","version":"4.0.4","versionstring":"4.0.4","edition":""}

**Comment by LukasReschke** [comment]
And config/config.php?

**Comment by mrmee** [comment]
there is no config/config.php at all. :-o 

just the config.sample.php

**Comment by LukasReschke** [comment]
Can you please fill out the issue template as described at https://github.com/owncloud/core/blob/master/CONTRIBUTING.md? – Thx.

**Comment by mrmee** [comment]
sorry for the lack of info. i hope now i have it all together:

### Expected behaviour
Installed from a owncloud.8.0.0.tar.bz2
md5: d2c1366be0756c24e1f5cfc02f80269f

Installation should be OC 8.0


### Actual behaviour

version.php shows:
$OC_Version = array(8,0,0,7);
$OC_VersionString = '8.0';
$OC_Channel = 'stable';

but status.php shows:
{"installed":"true","version":"4.0.4","versionstring":"4.0.4","edition":""}

Results: 
- linux desktop-client says: "server too old"

- iOS client 3.3.3 works fine
- webdav/carddav/caldav works fine



### Server configuration
**Operating system*Linux Raspbian*:
Raspbian GNU/Linux 7

**Web server:**
Apache/2.2.22 (Debian)


**Database:**
mysql  Ver 14.14 Distrib 5.5.41, for debian-linux-gnu (armv7l) using readline 6.2


**PHP version:**
PHP Version 5.4.36-0+deb7u3


**ownCloud version:** (see ownCloud admin page)
see "actual behavior"

**Updated from an older ownCloud or fresh install:**
fresh install

had oc7 running before but deleted to do an all-clean new install.

**List of activated apps:**
- Archive support
- Calendar
- Contacts
- Media
- ODF Viewer
- PDF Viewer
- Pictures
- Share Files
- Text Editor
- User Account Migration
- Versions
- owncloud Instance Migration


**The content of config/config.php:**
There is no config.php in config/
just config.sample.php 


**Are you using external storage, if yes which one:** local/smb/sftp/...
1TB HD mounted at /media/ocdata


**Are you using encryption:** yes/no
no


**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### Web server error log

#file upload-errors excluded
#this occurs several times
[Sun Feb 22 10:46:09 2015] [error] [client myip] File does not exist: /usr/share/owncloud/data/htaccesstest.txt
...
[Sat Feb 28 16:43:18 2015] [error] [client myip] script '/usr/share/owncloud/version.php' not found or unable to stat
[Sat Feb 28 16:43:20 2015] [error] [client myip] File does not exist: /var/www/core, referer: http://myip/owncloud/core/css/styles.css


#### ownCloud log (data/owncloud.log)

{"app":"core","message":"unable to find package 'MDB2_Driver_sqlite3' file 'MDB2\/Driver\/sqlite3.php'","level":4,"time":1424555921}
{"app":"core","message":"MDB2 Error: not found","level":4,"time":1424555921}
{"app":"core","message":"unable to find package 'MDB2_Driver_sqlite3' file 'MDB2\/Driver\/sqlite3.php'","level":4,"time":1424555927}
{"app":"core","message":"MDB2 Error: not found","level":4,"time":1424555927}

**Comment by LukasReschke** [comment]
> [Sat Feb 28 16:43:18 2015] [error] [client myip] script '/usr/share/owncloud/version.php' not found or unable to stat

This looks like you installed ownCloud using your package manager? – Please double check this. In this case this is a bug in the distributions packages and nothing we can change. We already provide packages for a lot of distributions using OBS as can be seen at owncloud.org/install

**Comment by DeepDiver1975** [comment]
setup issue -> close - THX
