### ISSUE TITLE
debian packaged 7.0.4+dfsg-2 tries to play videos with flashmediaelement.swf that is missing

### ISSUE THREAD

**Issue by yeupou** [owncloud/core#14617]
Hello,

owncloud debian packaged version 7.0.4+dfsg-2 tries to play videos with flashmediaelement.swf that is missing.

When trying to play a mp4 video while browsing files, nothing happens.

In the logs, I get:
2015/03/01 13:46:29 [error] 15194#0: *1 open() "/usr/share/owncloud/apps/files_videoviewer/js/flashmediaelement.swf" failed (2: No such file or directory), client: 78.249.90.43, server: ~^cloud, request: "GET /apps/files_videoviewer/js/flashmediaelement.swf HTTP/1.1", host: "cloud2.XXXX.org", referrer: "https://cloud2.XXXX.org/index.php/apps/files/?dir=%2FXXXXX"

#  dpkg --listfiles owncloud | grep flashmedia
returns nothing.

This file is anyway not in https://packages.debian.org/sid/all/owncloud/filelist

I did not change anything in the configuration related to video playback.

I've seen there was some security issue in the past related to this file (owncloud 5.0.5 changelog). Is it possible that this file has been removed for security reasons? I found no mention of this in the
README.Debian.

Should be flashmediaelement.swf shipped with owncloud? Or is it that something else  should be used and, for some reason to be determined, owncloud does not try to use this something else? 

For the record, the files_videoviewer directory contains:
# find /usr/share/owncloud/apps/files_videoviewer
/usr/share/owncloud/apps/files_videoviewer
/usr/share/owncloud/apps/files_videoviewer/img
/usr/share/owncloud/apps/files_videoviewer/img/close.png
/usr/share/owncloud/apps/files_videoviewer/appinfo
/usr/share/owncloud/apps/files_videoviewer/appinfo/version
/usr/share/owncloud/apps/files_videoviewer/appinfo/app.php
/usr/share/owncloud/apps/files_videoviewer/appinfo/info.xml
/usr/share/owncloud/apps/files_videoviewer/js
/usr/share/owncloud/apps/files_videoviewer/js/mediaelement-and-player.js
/usr/share/owncloud/apps/files_videoviewer/js/mediaelement-and-player.min.js
/usr/share/owncloud/apps/files_videoviewer/js/viewer.js
/usr/share/owncloud/apps/files_videoviewer/js/mep-extra.js
/usr/share/owncloud/apps/files_videoviewer/css
/usr/share/owncloud/apps/files_videoviewer/css/controls.svg
/usr/share/owncloud/apps/files_videoviewer/css/bigplay.png
/usr/share/owncloud/apps/files_videoviewer/css/background.png
/usr/share/owncloud/apps/files_videoviewer/css/style.css
/usr/share/owncloud/apps/files_videoviewer/css/loading.gif
/usr/share/owncloud/apps/files_videoviewer/css/mediaelementplayer.css
/usr/share/owncloud/apps/files_videoviewer/css/bigplay.svg
/usr/share/owncloud/apps/files_videoviewer/css/controls.png

Regards,

PS: I reported the issue against the debian package also, since it's not unlikely it's a packaging issue https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=779491

**Comment by karlitschek** [comment]
@jnweiger Hmmm. I see the file in the tar file. Something wrong in the package?

**Comment by jnweiger** [comment]
@yeupou Do you know where that 7.0.4 package came from?

**Comment by DeepDiver1975** [comment]
this is an issue within the debian packages - flashmediaelement.swf is removed because of missing sources - not out business

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=779491#28
