### ISSUE TITLE
Checksum app installations

### ISSUE THREAD

**Issue by BernhardPosselt** [owncloud/core#14616]
Very often I'm getting bug reports that go like this:

* Updated news app and it stopped working
* Complains about missing class X

This has always been due to missing files that were not updated correctly or were not present at all.

We need to get some mechanism in place that checks if all files that should be there are actually there and available in a form that is checksummed.

Whab about shipping a file like **checksums.txt** that contains all the files that should be there and the md5 checksums?
```
file | md5sum
appinfo/info.xml 34adfa123123123
```

**Comment by Raydiation** [comment]
@DeepDiver1975 @LukasReschke @PVince81 @nickvergessen @jbtbnl @georgehrke @LEDfan @butonic

**Comment by LukasReschke** [comment]
Good idea as long as we verify this only on update / installation to prevent a performance bottle-necks. Also needs to get disabled by users for development purposes and ocdev should be able to create those checksums on it's own. Furthermore has to be optional for backwards compatibility.

**Comment by Raydiation** [comment]
Yep should happen on update/installation.

If a checksum.txt is missing the check should not be performed, but maybe we should warn the user (what if there are no files at all after package extraction?)

**Comment by LEDfan** [comment]
I absolutely agree wit this! I'm experience the same issues with missing files in the Chat app. Note that there is a Grunt task (https://github.com/felthy/grunt-cachebuster) which can generate cheksum lists in both json as PHP format:
````
<?php
/**
 * GENERATED FILE, DO NOT EDIT. This file is simply a collection of generated hashes for static assets in
 * the project. It is generated by grunt, see Gruntfile.js for details.
 */
return array(
    'md5' => array(
        'js/main.js' => 'ae65552d65cd19ab4f1996c77915ed42',
        'js/vendor/modernizr-2.6.2.min.js' => 'b8009fa783ea3de3802efcd29d7473d5',
        'img/bg/about.jpg' => '7e402c1d64f0b00b4ade850f9017556a',
        'crossdomain.xml' => '625e6c239ea0b5504ce0641b74ec2a3b',
    )
)
````
I don't think this can easily be integrated in ocdev? @Raydiation

**Comment by LEDfan** [comment]
IMO a portable format should be used. Like JSON or PHP. So each developer can use it's own builder for this.

**Comment by Raydiation** [comment]
Oh great :)

Yeah JSON should be the preferred format possibly and it makes sense to do this with grunt since this file should always be up to date for people downloading master release versions, so a watch task would be awesome.

Regardless of the tool that we use to generate it, we should settle on the cachebuster JSON file format.

**Comment by LEDfan** [comment]
For reference Grunftile.js and output of the Chat app with cachebuster https://gist.github.com/LEDfan/d09a940102f06d974231

**Comment by Raydiation** [comment]
Ok, fix should be very easy, see https://github.com/owncloud/core/blob/master/lib/private/installer.php#L288

You just have to check if app_id/checksum.json exists, then go over all the files listed in there and check if the file exists and if it matches the checksum. If it does not exist or fails the checksum check, throw an exception.

If no app_id/checksum.json exists, error log to the owncloud log that the app does not provide a checksum file and that it could either miss the file/be corrupt or not ship any.

Should be maybe 10-25 lines of code, I'll be afk for today. @LEDfan can you try to create a reference implementation and create a pull request?

**Comment by Raydiation** [comment]
BTW: In order for this feature to reduce and not increase bug reports the error message should mention the files that are:
* Not there (file_exists)
* Can not be read (is_readable)
* Do not match the checksums

The installer.php only handles the appstore btw (I think). We should also find out how to hook into the app update/install method because some people are deploying the apps manually, as in uploading all files manually over ftp into the app_id folder.

**Comment by LEDfan** [comment]
I'll start working on this :)

**Comment by LEDfan** [comment]
@Raydiation I created a first implementation in #14618 which is already working!

**Comment by BernhardPosselt** [comment]
Closing this since signing applications takes care of this
