### ISSUE TITLE
Small changes within file were not synched properly

### ISSUE THREAD

**Issue by mapaongh** [owncloud/core#14626]
### Steps to reproduce
The folder which should be synchronized via owncloud lies on a NTFS partition.
The system is dualboot (Windows 7 / Ubuntu)
Files on it can be added, changed and removed using Windows or Linux.

1. Create File, e.g. Test.txt with Linux or Windows
2. Wait til it is uploaded to owncloud
3. Change one letter inside the file and save it again using Linux.

### Expected behaviour
The change would be recognized and file uploaded again.

### Actual behaviour
The change is sometimes not noticed. I know sometimes is not very specific, but it happens to me in the last 6 months for about 20 times. Especially with MS Office Files

### Server configuration
Owncloud 8
Ubuntu Server
no encryption

### Client configuration
Owncloud Client 1.7.1

### Question:
Can the reason be that Linux mounts NTFS?

**Comment by karlitschek** [comment]
difficult to debug. If this happens again please check if the mtime actually changed. Sorry but we need some way to reproduce that.
We can reopen this once we have more information.

**Comment by RealRancor** [comment]
@mapaongh 
Is this for the sync client? If yes the correct issue tracker would be https://github.com/owncloud/client/issues
