### ISSUE TITLE
Should "object store support" be listed as an app?

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#14624]
### Steps to reproduce

1. Install owncloud 
2. Go to the apps panel, click on "Not enabled"
3. Scroll to the bottom and find "object store support"

### Expected behaviour

The "object store support" app should not be listed

### Actual behaviour

The app is listed.

If it should be listed, two things:

1) It does not have an icon and 2) it's not in the correct alphabetical location

### Server Host info:

CentOS release 6.6 (Final)
PHP 5.4.36

### Server configuration

ownCloud Enterprise Edition 8.0.1 (stable)

**Comment by karlitschek** [comment]
This should be opened in the objectstore repo.
It is indeed a bit strange that the objectstore app doesn´t register itself to show up in the apps list.
But this is how it is designed at the moment.
@butonic Any input here?

**Comment by DeepDiver1975** [comment]
> @butonic Any input here?

not needed - this issue was fixed last week
