### ISSUE TITLE
Probleme update owncloud

### ISSUE THREAD

**Issue by ftrainor** [owncloud/core#14622]
I've updated owncloud-7.0.2 to owncloud-8 and then : 
An exception occurred while executing 'CREATE TABLE oc_own6_appconfig_u7yvcpuhaa29s (`appid` VARCHAR(32) DEFAULT '' NOT NULL, `configkey` VARCHAR(64) DEFAULT '' NOT NULL, `configvalue` LONGTEXT DEFAULT NULL, INDEX oc_fziglr67euso4 (`configkey`), INDEX oc_gu3w83dedc0qa (`appid`), PRIMARY KEY(`appid`, `configkey`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_own6_appconfig_u7yvcpuhaa29s' already exists

Now i have no more synchronisation and cant get acces to my web site.

**Comment by karlitschek** [comment]
Can you post a full bug report using the issue template please?
https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by DeepDiver1975** [comment]
duplicate - #14006
