### ISSUE TITLE
Log message of federated share missing who the share is with

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#14623]
### Steps to reproduce

1. Install owncloud on two systems for federated sharing
2. Make sure files_sharing_log app is enabled
3. Upload a file on system one and share with a user on system two

### Expected behaviour

Expect the logging for federated sharing to contain the share name

### Actual behaviour

The logging message does not contain the user name.

Message from a local share and link share:

```
{"reqId":"873c135e3aab2328f45896b12e3b99a7","remoteAddr":"x.x.x.x","app":"sharing_log","message":"User u1 shared \"\/pre_127.txt\" with a public link, token=QcL5aw9h2XHvgxV, permissions: READ","level":1,"time":"2015-03-01T15:59:31+00:00","method":"POST","url":"\/owncloud\/index.php\/core\/ajax\/share.php"}
{"reqId":"e088bb403e11e6c0939b7c7a72e2319d","remoteAddr":"x.x.x.x","app":"sharing_log","message":"User u1 shared \"\/pre_128.txt\" with the user u2, permissions: READ UPDATE SHARE","level":1,"time":"2015-03-01T16:00:48+00:00","method":"POST","url":"\/owncloud\/index.php\/core\/ajax\/share.php"}
```

Message when doing a remote share:

```
{"reqId":"438e24d8e14b4d20aaf3df9849b87421","remoteAddr":"x.x.x.x","app":"sharing_log","message":"User u1 shared \"\/pre_135.txt\" with , permissions: READ UPDATE CREATE","level":1,"time":"2015-03-01T16:01:27+00:00","method":"POST","url":"\/owncloud\/index.php\/core\/ajax\/share.php"}
```

### Server Host info:

CentOS release 6.6 (Final)
PHP 5.4.36

### Server configuration

ownCloud Enterprise Edition 8.0.1 (stable)

**Comment by karlitschek** [comment]
Yes. Would be good to add this. @schiesbn What do you think?

**Comment by DeepDiver1975** [comment]
> Make sure files_sharing_log app is enabled

is an enterprise app -> closing therefore
