### ISSUE TITLE
sanitize invalid filenames (e.g. if filename contains >260 characters or invalid characters) into valid cross-platform filename if other app attempts to

### ISSUE THREAD

**Issue by ericfont** [owncloud/core#14629]
### Steps to reproduce
The notes app uses the first line of a note as the filename.  However, if this first line is an invalid filename, then the note won't sync because files with invalid filenames won't sync with desktops:
1. open notes app in webbrowser
2. make new note or open old note
3. input any of the following in the first line:
    * more than 260 characters
    * an invalid character (, :, ?, *, ”, >, <, |)
    * a tab
    * anything else that would produce an invalid filename

alternatively in android:
1. open android notes app "MyOwnNotes"
2. make new note
3. leave the beginning of the first line as the default datetime(YYYY-MM-DD HH:MM:SS) 
4. put nothing or anything else after default or on newlines
5. save successfully (but due to colon in first line, the file won't sync with desktops)

### Expected behavior
owncloud core should sanitize invalid filenames into valid cross-platform filenames so all files will sync on all devices (win, mac, linux, android, iOS, etc.) regardless of whether a specific app submits an invalid filename to core.

### Actual behavior
The note file will not be transferred or synced to desktop.  My Windows and Linux desktop client complains in Sync Activity that "File contains invalid characters that can not be synced cross platform." for most invalid filenames (and specifically for a tab, windows client complains "The filename, directory name, or volume label syntax is incorrect"). New notes with invalid filenames don't show up in desktop folder, while old notes that are updated with a different first line producing invalid filename aren't updated.  Copying & pasting a block of text containing invalid filename into first line in browser's note app will not sync any file at all, while typing text only saves the latest valid filename.

I tried re-rasing this issue to owncloud notes app and suggested that the responsibility should be on the notes app to provide valid filename, but developer Raydiation insists: "Filename sanitation is handled in core, reopen there": https://github.com/owncloud/notes/issues/86#issuecomment-76611524

I can't find any specific issues to filename sanitation in core, so I'm opening here.  (Some component should be responsible for sanitation.  If it isn't the note app responsibility, then core should be.)

(Update: I have been testing this with lots of different combinations, and now am discovering that older valid notes with valid filenames are now lost to both browser, android, and desktop.  What was previously a perfectly valid note seems to get overwritten with no text and will be renamed "New note (number)" when I click on the valid note.  I suspect this is because at this point I have corrupted so many files that filesystem is confused, but I can't provide exact steps to replicate at this point...will need to try on a clean configuration.)

### Server configuration
**Operating system**:
arch linux (latest rolling release)

**Web server:**
 Apache/2.4.12 (Unix) OpenSSL/1.0.2 PHP/

**Database:**
mysql  Ver 15.1 Distrib 10.0.16-MariaDB, for Linux (x86_64) using readline 5.1

**PHP version:**
5.6.6

**ownCloud version:** (see ownCloud admin page)
ownCloud 8.0 (stable)

**Updated from an older ownCloud or fresh install:**
updated from a fresh late 7.* install

**List of activated apps:**
activity, bookmarks, calendar, contacts, deleted files, documents, fun first wizard, full text search, mail template editor, news, notes, pdf view, pictures, shared files, subphonics, tasks, text editor, updater, versions, video viewer, ownCloud SMS

**The content of config/config.php:**
```
<?php
$CONFIG = array (
  'instanceid' => 'ocf4786ae702',
  'passwordsalt' => ***********************************************
  'secret' => *****************************************
  'trusted_domains' =>
  array (
    0 => '192.168.0.23',
    1 => 'efjz.in',
    2 => '192.168.0.19',
  ),
  'datadirectory' => '/usr/share/webapps/owncloud/data',
  'overwrite.cli.url' => 'http://192.168.0.23',
  'dbtype' => 'mysql',
  'version' => '8.0.0.7',
  'dbname' => 'ownCloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_e',
  'dbpassword' => **********************************************
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'ericfontainejazz.com',
  'mail_from_address' => 'owncloud',
  'forcessl' => true,
  'loglevel' => '0',
  'theme' => '',
  'maintenance' => false,
  'mail_smtpsecure' => 'ssl',
  'mail_smtpauthtype' => 'PLAIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'server203.webhostingpad.com',
  'mail_smtpport' => '465',
  'mail_smtpname' => 'owncloud@ericfontainejazz.com',
  'mail_smtppassword' => **********************
);
```

**Are you using external storage, if yes which one:**
no

**Are you using encryption:**
no

**Are you using an external user-backend, if yes which one:**
no

### Client configuration
**Browser:**
chrome nightly windows

**Operating system:**
windows 10 open alpha

#### Web server error log
nothing out of ordinary..but I can't parse all my logs...here is snippit from tail of apache /var/log/httpd/access_log when trying to make a note in browser by repeatedly typing letter 'a' over 260 times in first line (logs confirm it saves the initial a.txt correctly with just one a, but owncloud.log indicates doesn't save updates with more a's):
```
24.99.152.204 - - [01/Mar/2015:22:23:06 -0500] "PUT /index.php/apps/notes/notes/709 HTTP/1.1" 500 10799
24.99.152.204 - e [01/Mar/2015:22:23:09 -0500] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 508
24.99.152.204 - - [01/Mar/2015:22:23:09 -0500] "GET /index.php/apps/notes/notes/696 HTTP/1.1" 200 102
24.99.152.204 - e [01/Mar/2015:22:23:17 -0500] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 4746
24.99.152.204 - - [01/Mar/2015:22:23:17 -0500] "PROPFIND /remote.php/webdav HTTP/1.1" 401 242
24.99.152.204 - e [01/Mar/2015:22:23:17 -0500] "PROPFIND /remote.php/webdav HTTP/1.1" 207 7374
24.99.152.204 - e [01/Mar/2015:22:23:17 -0500] "PROPFIND /remote.php/webdav/Notes HTTP/1.1" 207 6735
24.99.152.204 - e [01/Mar/2015:22:23:18 -0500] "GET /remote.php/webdav/Notes/a.txt HTTP/1.1" 200 1
24.99.152.204 - e [01/Mar/2015:22:23:20 -0500] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 508
24.99.152.204 - e [01/Mar/2015:22:23:39 -0500] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 508
24.99.152.204 - e [01/Mar/2015:22:23:48 -0500] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 4746
...
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"f1fe79806d7114f89f910f7260f88549","remoteAddr":"24.99.152.204","app":"index","message":"Exception: {\"Message\":\"\\\/e\\\/files\\\/Notes\\\/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabb.txt\",\"Code\":0,\"Trace\":\"#0 \\\/owncloud\\\/lib\\\/private\\\/files\\\/node\\\/file.php(132): OC\\\\Files\\\\Node\\\\Root->get('\\\/e\\\/files\\\/Notes\\\/...')\\n#1 \\\/owncloud\\\/apps\\\/notes\\\/service\\\/notesservice.php(122): OC\\\\Files\\\\Node\\\\File->move('\\\/e\\\/files\\\/Notes\\\/...')\\n#2 \\\/owncloud\\\/apps\\\/notes\\\/controller\\\/notescontroller.php(99): OCA\\\\Notes\\\\Service\\\\NotesService->update(709, 'aaaaaaaaaaaaaaa...', 'e')\\n#3 \\\/owncloud\\\/apps\\\/notes\\\/controller\\\/errors.php(31): OCA\\\\Notes\\\\Controller\\\\NotesController->OCA\\\\Notes\\\\Controller\\\\{closure}()\\n#4 \\\/owncloud\\\/apps\\\/notes\\\/controller\\\/notescontroller.php(100): OCA\\\\Notes\\\\Controller\\\\NotesController->respond(Object(Closure))\\n#5 [internal function]: OCA\\\\Notes\\\\Controller\\\\NotesController->update(709, 'aaaaaaaaaaaaaaa...')\\n#6 \\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(158): call_user_func_array(Array, Array)\\n#7 \\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(86): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Notes\\\\Controller\\\\NotesController), 'update')\\n#8 \\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(97): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Notes\\\\Controller\\\\NotesController), 'update')\\n#9 \\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(44): OC\\\\AppFramework\\\\App::main('NotesController', 'update', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#10 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#11 \\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#12 \\\/owncloud\\\/lib\\\/base.php(763): OC\\\\Route\\\\Router->match('\\\/apps\\\/notes\\\/not...')\\n#13 \\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/owncloud\\\/lib\\\/private\\\/files\\\/node\\\/root.php\",\"Line\":167}","level":4,"time":"2015-03-02T03:23:07+00:00","method":"PUT","url":"\/index.php\/apps\/notes\/notes\/709"}
```

#### Browser log
N/A...browser is not at issue.

**Comment by DeepDiver1975** [comment]
looks like the public file note api doesn't perform file name verification as this is done via webdav and the files app. Will look into this within the scope of #13640

**Comment by DeepDiver1975** [comment]
#14776 will now check for 255 characters max length (http://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits) and throw an exception.

The notes app has to properly handle this - pr will follow.

**Comment by DeepDiver1975** [comment]
PR in notes - https://github.com/owncloud/notes/pull/96

**Comment by DeepDiver1975** [comment]
#14776 was merged now - remaining tasks are up to the notes app - owncloud/notes#96
