### ISSUE TITLE
Smtp broken on PHP 5.6/OC8

### ISSUE THREAD

**Issue by dcrdev** [owncloud/core#14628]
Smtp appears to be broken with PHP 5.6 - works fine on a comparable set up with PHP 5.5.x. Just getting this error: "A problem occurred while sending the email. Please revise your settings." Along with this log entry: "SMTP connect() failed."

So nothing really to indicate what's broken.

**Comment by karlitschek** [comment]
hmm. likely a problem with your setup. Can you have a look into your apache/php log or your syslog or mail log?

**Comment by RealRancor** [comment]
@dcrdev 
Could be also useful to fill out the issue template linked in the guidelines for contributing (shown in the yellow box when creating a new issue) to provide mandatory infos about your environment.

Additional troubleshooting steps are also available here:

https://doc.owncloud.org/server/8.0/admin_manual/configuration_server/email_configuration.html#troubleshooting

**Comment by DeepDiver1975** [comment]
Maybe related to this? https://github.com/PHPMailer/PHPMailer/issues/359

@LukasReschke could that be the issue I was facing while testing the swift mailer pr?

**Comment by LukasReschke** [comment]
That could be one of these issues - yes. With my SwiftMailer PR a more explaining error message should be shown in the test wizard: https://github.com/owncloud/core/pull/12085

**Comment by dcrdev** [comment]
I'd seen that mentioned on the php website - I've got my root CA bundle referenced directly in my php configuration to make sure. I'm pretty sure it's something else as I can open a socket connection to ssl destinations in php i.e. through fopen.

Worth mentioning also that I've got a roundcube webmail client installation set up on the same server and it can connect to the same smtp host.

**Comment by DeepDiver1975** [comment]
> Worth mentioning also that I've got a roundcube webmail client installation set up on the same server and it can connect to the same smtp host.

roundcure uses another library for smtp and might enabled some settings to make if work - we need to analyse this situation - but it's kind of pointless for the time being as we want to move to swift mailer instead of phpmailer

**Comment by DeepDiver1975** [comment]
closing this because mainly a setup issue - in addition this is a won't fix as we are moving away from PHPMailer
