### ISSUE TITLE
ownCloud resets customized storage quota back to default value

### ISSUE THREAD

**Issue by finius** [owncloud/core#14621]
We use LDAP sync to fill our ownClous user list. By default each users quota is set to 20gb. When we create a larger storage quota for certain users, the new size is shown immediately on the ownloud client. But after a while (it may be 24h), whitout changing anything on the server side, the quota is reset to systems default on server and client side. Even in the user list on the admin website the default value is set back to 20gb. The only thing we could determine is, that in every case the user was meanwhile syncing (uploading) data with the local owncloud windows client.

**Comment by karlitschek** [comment]
@blizzz any idea how this can happen?

**Comment by blizzz** [comment]
Do you mix LDAP controlled quota and ownCloud controlled quota on the Users page? You xannot, you need to decide for one.

Do you use LDAP controlled quota solely? Then what is your configuration and where do you change values?

**Comment by finius** [comment]
@blizzz 
I guess your hint about mixed use of LDAP specified quotas and ownCloud specified quotas was helpful. Indeed there was defined a quota inside the advanced settings of the LDAP wizard while the special quotas for certain users had been defined in the user list. I now cleared the LDAP quota entry. We'll keep watching the quota behaviour within the next days to see if anything resets again.
@karlitschek  
It may be worth to give a hint in the user interface when changing quotas in the user list while a global LDAP quota is preset. We haven't realised this dependency when configuring our storage.

**Comment by blizzz** [comment]
Sorry it is not clear how it operates. I opened a ticket on documentation to  clarify this: https://github.com/owncloud/documentation/issues/903
