### ISSUE TITLE
maintenance message is misleading

### ISSUE THREAD

**Issue by karlitschek** [owncloud/core#14627]
If the ownCloud maintenance mode is switched on the webpage says: "This ownCloud is currently upgraded...." The admin might think that an upgrade is happening at the moment. But it is not.
We should change this to something more neutral like: "This ownCloud is currently in maintenance mode, ...."

**Comment by RealRancor** [comment]
Yes, that has lead to some confusion in the past. Maybe also add an additional note how the maintenance mode xan be disabled.

**Comment by DeepDiver1975** [comment]
@nickvergessen can I ask you to submit a pr? THX
