### ISSUE TITLE
Bump jQuery to 1.11.2 or 2.x

### ISSUE THREAD

**Issue by bkerensa** [owncloud/core#14634]
Can we bump jQuery in Owncloud to 1.11.2 or even better 2.x? The current version used by OwnCloud is not the latest stable and uses deprecated. Notably though 2.x would not work with IE 6/7/8 but maybe thats a good thing as it pushes the web forward? Eitherway though a bump to 1.11.2 would be great in the next maintenance release.

Might aswell also bump any other external libraries to their latest stable.

**Comment by LukasReschke** [comment]
>  Notably though 2.x would not work with IE 6/7/8 but maybe thats a good thing as it pushes the web forward? 

We still have to support IE 8 for now.

cc @MTRichards @DeepDiver1975 @karlitschek

**Comment by bkerensa** [comment]
Well then at least bumping to 1.11.2 which supports everything would be good because the jQuery being used now throws errors in both Firefox and Chrome's DevTools over deprecated js

**Comment by karlitschek** [comment]
Yes. IE8 is unfortunately still on the supported list :-(

**Comment by DeepDiver1975** [comment]
we should add a javascript dependency batch and see which libs require an update.

is there aversion exe fro javascript?

**Comment by MorrisJobke** [comment]
https://www.versioneye.com/user/projects/54f4a2384f3108959a000a16

![dependencies](https://cloud.githubusercontent.com/assets/245432/6446706/21e0be94-c10d-11e4-98de-11b1234737a5.png)

**Comment by MorrisJobke** [comment]
@DeepDiver1975 Also a `bower ls` list this dependency tree ;)

**Comment by MorrisJobke** [comment]
This will drop jquery-migrate too - see #12877

This is required too: #13646

**Comment by MorrisJobke** [comment]
@DeepDiver1975 I will bump this to 8.2 too, because you put #12877 into 8.2 and this is mandatory for this ticket.

**Comment by PVince81** [comment]
IE8 support timeline: #15567

**Comment by PVince81** [comment]
IE8 still has to be supported unfortunately and we're past feature freeze => 9.0

**Comment by phsc** [comment]
IE8 support will be dropped for Owncloud 9.0. So it should be possible to upgrade to jQuery 2.x.
See https://github.com/owncloud/core/issues/15567#issuecomment-166754301

**Comment by PVince81** [comment]
Nice! Upgrading jquery will require some careful regression testing of all the web UI incase of API changes.

**Comment by PVince81** [comment]
IE8-IE10 support will be dropped in 9.1, so might be a good opportunity to make this upgrade.
