### ISSUE TITLE
Lost share-keys for some (but not all) files

### ISSUE THREAD

**Issue by Olen** [owncloud/core#14647]
### Steps to reproduce
1. Enable files_encryption
2. Mount OC-filesystem via webdav
3. After a while, some "shareKey"s will disappear

### Expected behaviour
Tell us what should happen

The files should obviously never be lost-

### Actual behaviour
Tell us what happens instead

The files are not there anymore.

I have a backup of the entire data-directory from November, the files are there:

../data-backup/olen/files_encryption/keyfiles/www/db_functions.php.key
../data-backup/olen/files_encryption/share-keys/www/db_functions.php.olen.shareKey
../data-backup/olen/files_encryption/share-keys/www/db_functions.php.recovery_e70ae258.shareKey

Now, all I have is:

../data/olen/files_encryption/keyfiles/www/db_functions.php.key

So the two shareKeys are gone.

The file in question "db_functions.php" is used and included in several of my web-projects, and these have been working fine until some time in february.
Suddenly, they all stopped working, and any access to the file db_functions.php via webdav will only give an IO-error, and in the Web UI, I get the error message that "Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you."

Unfortunatly, the keys from the backup do not seem to work on the current version of db_functions.php.  They do work if i copy over the old version of this file from the backup, but that one is missing a lot of the latest development.

I know I should do more regular backups, but the core issue here is that one can not trust the encryption module, as keys seem to disappear out of the blue.

### Server configuration
**Operating system**:
Linux (Fedora 20)

**Web server:**
Nginx

**Database:**
pgsql

**PHP version:**
5.2.21

**ownCloud version:** (see ownCloud admin page)
This used to be 7.something.  
Unfortunatly it is now upgraded to 8, which has made the problem worse, as the keyfiles are now converted to the new format.

**Updated from an older ownCloud or fresh install:**
Updated

**List of activated apps:**
 - files
 - files_encryption
 - files_pdfviewer
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_videoviewer
 - firstrunwizard
 - updater

**The content of config/config.php:**
$CONFIG = array (
 ...
  'datadirectory' => '/home/users/owncloud/data',
  'dbtype' => 'pgsql',
  'version' => '8.0.0.7',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'loglevel' => '0',
  'blacklisted_files' => 
  array (
  ),
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' => 
  array (
    0 => 'cloud.olen.net',
  ),
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
 ...
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
Yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Webdav/Chrome/Firefox

**Operating system:**
N/A

### Logs

As I don't know exactly when this happened, the logs make no sense.

**Comment by Olen** [comment]
And btw.
This has happend with several other files as well.  The db_functions.php is only an example.
But _most_ files are ok.

 find ../data/olen/files_encryption/keyfiles | wc -l
10934
find ../data/olen/files_encryption/share-keys/ | wc -l
21398

If there should be two shareKeys for each fileKey, there should have been 21868 shareKeys, so probably about 250 of 11000 files are missing their shareKeys. I have not counted this precisely.

Any help in further debugging or investigation or how to recover is highly appreciated.

**Comment by karlitschek** [comment]
Hmm. This doesn´t sound good. @schiesbn What do you think?

**Comment by PVince81** [comment]
Are you able to find out which "7.x.x" version you had ?
There were bugs in the past related to encryption and share key pattern matching: https://github.com/owncloud/core/issues/11127

Basically if you had two files "abc.txt" and "abc 2.txt" and moved one of them into a subdir with WebDAV, it would move the share keys of BOTH files instead of just one.
Can you check whether the share keys were moved (or stayed) in another directory ? (maybe in your backup)

**Comment by PVince81** [comment]
That bug was found in 7.0.2 and fixed in 7.0.3 (I believe), so if your old instance was 7.0.2 or previous, it is likely that it happened to you. Did you have another file called "db_functions_backup.php" or something maybe ?

**Comment by Olen** [comment]
Seems like it was 7.0.2 that was installed (from RPM).
I can't seem to find any other files with the same name as the ones that are missing the shareKeys, but it could be that the files have been renamed on different computers with different clients, so it could be some stale file-handles or -names hanging around of course.

But is there anything I can do to be able to either recreate the shareKeys, or decrypt the files in other ways?
Brute forcing the shareKeys is probably not an option?

I can easily scan the file system to see which files I have a fileKey but no shareKey for.

**Comment by Olen** [comment]
After checking the whole "/data" tree, there seem to be about 40 files with missing share-keys.
Most of them are temp-files of different sorts, so they are not important.  And probably they might have colliding names with other files.

However, about 10 of the files are slightly more important, and I would really like to get them back...

**Comment by PVince81** [comment]
This is unfortunately not something that can be repaired automatically due to the too big potential for false positives.

Please try and see whether you can find any share key for those files. Search for the name of those 10 files inside the whole "data" folder. If you find any share key lying around, try moving it to the correct folder where the file is now.
If the share key you found is the recovery key, then you should be able to recover the contents too but I don't exactly remember how. Let me know if you find some and I can try and find this info.

**Comment by PVince81** [comment]
@Olen did you manage to restore your encrypted files by moving the share keys ?

**Comment by PVince81** [comment]
Closing due to lack of feedback.
You should be able to restore encrypted files by moving the correct file keys and share keys to the proper location.
