### ISSUE TITLE
Cleanup routine might run into race-condition

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#14648]
I had a short discussion with @cdamken about an issue which is similar to https://github.com/owncloud/core/issues/13171 and https://github.com/owncloud/core/issues/12897

For example:
```json
{"app":"PHP","message":"filesize(): stat failed for \/mnt\/USER\/files_versions\/FOO\/T070\/FILENAME.txt.v1410672949 at \/var\/www\/html\/owncloud\/lib\/private\/files\/storage\/local.php#105","level":3,"time":"2015-02-11T08:18:33+00:00"}
```

In my opinion these issues are caused by a race-condition from multiple requests:

1. First requests starts clean-up
2. Second request starts clean-up as well
3. Second clean-up explodes as it does not find the files anymore and tries to delete them

If we move it to the cron like suggested in https://github.com/owncloud/core/issues/8109, these types of issues should be gone. Has also to be done for files_versions.

@DeepDiver1975 @icewind1991 Thoughts?

**Comment by cdamken** [comment]
In the last ten days owncloud.log growth with 17'408 of this error messages

@MorrisJobke We need a fix here too

00002584

**Comment by DeepDiver1975** [comment]
will be fixed with 8.1 - see https://github.com/owncloud/core/pull/14644

**Comment by DeepDiver1975** [comment]
@cdamken as I know you might want to ask: backport will not really be possible due to the big changset

**Comment by LukasReschke** [comment]
> will be fixed with 8.1 - see #14644

Seems like we need the same thing for versioning as well?

**Comment by PVince81** [comment]
We could also add a `@` before filesize to avoid logging warnings. But also make sure that there's code to handle the case where filesize is not set, some kind of defensive programming to make sure stuff is still there before doing any further operation.

**Comment by LukasReschke** [comment]
> We could also add a @ before filesize to avoid logging warnings.

Yeah but a `@` in the local filesystem storage? – That seems like a major hack :see_no_evil:

**Comment by PVince81** [comment]
Yes it is :wink:

**Comment by DeepDiver1975** [comment]
> Seems like we need the same thing for versioning as well?

should arrive these days as well

**Comment by DeepDiver1975** [comment]
here we go - https://github.com/owncloud/core/pull/15129

**Comment by MorrisJobke** [comment]
Merged :)
