### ISSUE TITLE
[7.0.4 --> 8] After Upgrade, Encryption Private Keys not found for LDAP users

### ISSUE THREAD

**Issue by oniled** [owncloud/core#14655]
### Steps to reproduce
1. Upgraded Owncloud from 7.0.4 to 8.0
2. Logged in as a LDAP/Active Directory User
3. Received notice that "Encryption App is enabled but your keys are not initialized, please log-out and log-in again"
4. Tried Logging off and logging back on, errors continued

### Expected behaviour
Error should go away after log off and log on.

### Actual behaviour
Error continues to show after each logon.  If I check the owncloud.log, it says the private key is missing when I clearly see it in  /data/%user%/files-encryption

### Server configuration
**Operating system**: Server 2012 R2 Standard

**Web server:** IIS8

**Database:** MYSQL

**PHP version:** 5.6.2

**ownCloud version:** 8.0

**Updated from an older ownCloud or fresh install:** 6.0.2 --> 6.0.3 --> 6.0.5 --> 6.0.6 --> 7.0.4 --> 8.0

**List of activated apps:** activity, deleted files, encryption, full text search, LDAP user and group backend, Mail Template editor, PDF viewer, share files, text editor, versions

**The content of config/config.php:**

```
<?php
$CONFIG = array (
'instanceid' => 'oc0cec0e0306',
'passwordsalt' => 'supersecretsquirrel',
'trusted_domains' => 
array (
0 => 'filextest.foundation.sdsu.edu',
),
'datadirectory' => 'C:\inetpub\wwwroot\data',
'dbtype' => 'mysql',
'version' => '8.0.0.7',
'dbname' => 'oc',
'dbhost' => '127.0.0.1',
'dbtableprefix' => 'oc_',
'dbuser' => 'supersecretsquirrel',
'dbpassword' => 'supersecretsquirrel',
'installed' => true,
'ldapIgnoreNamingRules' => false,
'forcessl' => true,
'logtimezone' => 'America/Los_Angeles',
'theme' => 'filex', 
'enable_previews' => false,
'enable_avatars' => false,
'allow_user_to_change_display_name' => false,
'mail_smtpmode' => 'smtp',
'mail_smtphost' => 'smtp.foundation.sdsu.edu',
'mail_smtpport' => '25',
'mail_smtptimeout' => '10',
'maintenance' => false,
'loglevel' => '0',
'secret' => 'supersecretsquirrel',
'share_folder' => '/Shared',
);
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory

#### LDAP configuration (delete this part if not used)

```
user_ldap	cleanUpJobOffset	150
user_ldap	enabled	yes
user_ldap	has_memberof_filter_support	1
user_ldap	home_folder_naming_rule	
user_ldap	installed_version	0.5.0
user_ldap	last_jpegPhoto_lookup	0
user_ldap	ldap_agent_password	x
user_ldap	ldap_attributes_for_group_search	
user_ldap	ldap_attributes_for_user_search	
user_ldap	ldap_backup_host	
user_ldap	ldap_backup_port	
user_ldap	ldap_base	dc=x,dc=y,dc=z
user_ldap	ldap_base_groups	dc=x,dc=y,dc=z
user_ldap	ldap_base_users	ou=accounts,dc=x,dc=y,dc=z
 
user_ldap	ldap_cache_ttl	600
user_ldap	ldap_configuration_active	1
user_ldap	ldap_display_name	displayname
user_ldap	ldap_dn	ownCloud
user_ldap	ldap_email_attr	mail
user_ldap	ldap_experienced_admin	0
user_ldap	ldap_expert_username_attr	
user_ldap	ldap_expert_uuid_group_attr	
user_ldap	ldap_expert_uuid_user_attr	
user_ldap	ldap_group_display_name	cn
user_ldap	ldap_group_filter	(|(cn=Domain Users))
user_ldap	ldap_group_filter_mode	1
user_ldap	ldap_group_member_assoc_attribute	uniqueMember
user_ldap	ldap_groupfilter_groups	Domain Users
user_ldap	ldap_groupfilter_objectclass	
user_ldap	ldap_host	130.191.66.161
user_ldap	ldap_login_filter	(&(&(|(objectclass=user)))(|(samaccountname=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))))
user_ldap	ldap_login_filter_mode	1
user_ldap	ldap_loginfilter_attributes	
user_ldap	ldap_loginfilter_email	1
user_ldap	ldap_loginfilter_username	1
user_ldap	ldap_nested_groups	0
user_ldap	ldap_nocase	0
user_ldap	ldap_override_main_server	0
user_ldap	ldap_paging_size	500
user_ldap	ldap_port	3268
user_ldap	ldap_quota_attr	
user_ldap	ldap_quota_def	
user_ldap	ldap_tls	0
user_ldap	ldap_turn_off_cert_check	0
user_ldap	ldap_user_filter_mode	0
user_ldap	ldap_userfilter_groups	
user_ldap	ldap_userfilter_objectclass	user
user_ldap	ldap_userlist_filter	(&(|(objectclass=user)))
user_ldap	ocsid	166061
user_ldap	types	authentication
```

### Client configuration
**Browser:** Chrome/Firefox/IE10

**Operating system:** Windows 7 SP1 x64

#### Web server error log
```
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"8465cbb1f3ef7c043dcaf18872fd8e3d","remoteAddr":"130.191.67.149","app":"Encryption library","message":"User account \"27E30FD0-1336-4A7E-9E68-90488494C826\" is not ready for encryption; configuration started","level":0,"time":"2015-03-02T14:20:05-08:00","method":"POST","url":"\/filex\/index.php"}
{"reqId":"8465cbb1f3ef7c043dcaf18872fd8e3d","remoteAddr":"130.191.67.149","app":"Encryption library","message":"public key exists but private key is missing for \"27E30FD0-1336-4A7E-9E68-90488494C826\"","level":4,"time":"2015-03-02T14:20:05-08:00","method":"POST","url":"\/filex\/index.php"}
```
![image](https://cloud.githubusercontent.com/assets/8421682/6452327/cf4cc98e-c0e9-11e4-8dbc-a313a4e5245f.png)

**Comment by PVince81** [comment]
You have LDAP so might need to run `./occ encryption:migrate-keys`

**Comment by oniled** [comment]
Think that is working...but so far I've come across 2 users that threw this error:

```
[OCP\Files\InvalidPathException]
Path length(261) exceeds max path length(260): 210F3118-103B-4CDC-8BE7-26DC
EF04F27C/files_trashbin/keyfiles/Julie Johnson.d1424839086/////////////////
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
////////
```

I found I could delete the offending key file and the file for that user to get past the first exception but should I have to do this for all exceptions?

**Comment by PVince81** [comment]
Ouch, you're running on Windows :frowning: 
You're likely to meet such issues with paths.

@nickvergessen any advice?

**Comment by LukasReschke** [comment]
Setting to backlog as not really an officially recommended platform anymore.

**Comment by nickvergessen** [comment]
Please have a look at the other issues that mention `/////////////////////`

Closing as duplicate

**Comment by oniled** [comment]
Good to know.  In that case...

1) Is there a migration path to migrate data and users from Windows to Linux?  Almost feel safer just starting with a new instance of Owncloud though.
2) I tried doing some searches for "/////////////"but couldn't find anything.  Also tried searching for "InvalidPathException" "max path length 260" but all I found was another open ticket from 19 days ago?

https://github.com/owncloud/core/issues/14155

Thanks for the clarity and help guys but might need your help pointing me in the next step.

**Comment by LukasReschke** [comment]
> 1) Is there a migration path to migrate data and users from Windows to Linux? Almost feel safer just starting with a new instance of Owncloud though.

You'd be way better of if you re-setup the instance. Sorry.

**Comment by Elethiomel** [comment]
I'm having the exact same issue on a Linux box (Debian Wheezy) with 8.0.1RC1

I'm getting "Encryption App is enabled  but your keys are not initialised, please log-out and log-in again." 

This is an old account and it worked perfectly today before the upgrade. 

In the log I'm getting "public key exists but private key is missing for  \"72766112-d9cc-102f-8f72-f9b2ae36fa74\"

The file  /srv/owncloud/cfowler/files_encryption/72766112-d9cc-102f-8f72-f9b2ae36fa74.private.key exists though.

Note that the users files are in /srv/owncloud/cfowler whereas owncloud seems to want to refer to the user via uuid. There seems to be a disparity here

I ran /occ encryption:migrate-keys and it completes in a seconds or two, scrolling out 2614 uuids (The number of users in LDAP).  THat doesn't fix anything, however I do end up with an encryption_migration_backup_<date> folder

**Comment by PVince81** [comment]
Had a chat with @Elethiomel on IRC and it seems that some LDAP users didn't have their keys migrated.
There also seems to be a discrepancy between the LDAP userid and uuid. The storage table contains "home::uuid" but the folder on disk is using the userid.
Not sure how this could happen.

But it could explain why the migration code didn't find the keys.

**Comment by PVince81** [comment]
CC @blizzz can a home folder be in userid format but the storage entry have uuid ?

**Comment by PVince81** [comment]
We observed some cases where oc_storages was "home::some_uuid" but on disk it was the home folder with "some_user_id". But the encryption migration code seemed to want the "some_uuid" instead. Since it didn't find it, the home migration failed.

**Comment by blizzz** [comment]
> CC @blizzz can a home folder be in userid format but the storage entry have uuid ?

Yes. The default is the same, but you can configure it to be different.

**Comment by nickvergessen** [comment]
This is a windows server issue ticket. Please use a new one for your LDAP discussion :P
