### ISSUE TITLE
S3 External Storage - allow use of subfolder as the "root" of the mount

### ISSUE THREAD

**Issue by TravellingGuy** [owncloud/core#14657]
When setting up an Amazon S3 external storage point, it would be great if we could specify a folder (or subfolder) in the S3 bucket to use for the mount point.

Right now, entering something like "mybucket/folder1" in the "Bucket" field fails (red square shows for that external storage point) and the external storage doesn't get mounted.

**Comment by DeepDiver1975** [comment]
Secondary s3 storage integration just got move over to https://github.com/owncloud/files_external_s3.

Unfortunately GitHub does not allow to move issues. Please reopen the issue at https://github.com/owncloud/files_external_s3/issues
