### ISSUE TITLE
Invalid VObject. Document ended prematurely. 

### ISSUE THREAD

**Issue by jpfeifer** [owncloud/core#14659]
Hi. I installed a fresh copy of owncloud 8 with a mysql backend. Then I imported my calendar entries from owncloud 7 using the  ics format. Unfortunately now I can't synchronize some calendars on Android because of this error:

{"reqId":"de2303c4561ee1a2407eafa2c7a7c664","remoteAddr":"95.112.248.59","app":"vobject","message":"Invalid VObject. Document ended prematurely.","level":3,"time":"2015-03-02T23:50:22+00:00","method":"GET","url":"\/oc\/index.php\/apps\/calendar\/ajax\/events.php?calendar_id=2&start=1424646000&end=1428271200"}

Please help cause this is a blocker for me.

**Comment by karlitschek** [comment]
can you open this in the calendar repository please?
We also need a full bug report using the issue template. thanks
https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by jpfeifer** [comment]
Sure, sorry for the inconvience. Follow up issue here:

https://github.com/owncloud/calendar/issues/743
