### ISSUE TITLE
Provide app version in occ app:list

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#14661]
Hi,

the issue template at https://raw.githubusercontent.com/owncloud/core/master/issue_template.md is asking for a list of installed apps. For this the occ app:list is often used.

As more apps like calendar and contacts where moved to the appstore and are now updated independently from the OC release it might be useful to add the version of the app into the occ app:list command line client.

**Comment by nickvergessen** [comment]
One idea could be to include the version, when `--versions` is added to the command, the other idea would be to always show them.
But that's easy to change:

```
nickv@nickv-lt-mint ~/ownCloud/Master $ ./occ app:list --versions
Enabled:
 - activity (1.2.1)
 - files (1.1.9)
 - files_external (0.2.3)
 - files_sharing (0.6.1)
 - files_trashbin (0.6.2)
 - files_versions (1.0.5)
 - gallery (0.6.0)
Disabled:
 - calendar
 - contacts (0.3.0.18)
 - files_encryption
