### ISSUE TITLE
Stray share entries in DB after deleting parent folder

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#14664]
### Steps to reproduce
1. Create a folder "test"
2. Create/upload a file "test/file.txt"
3. Share "test/file.txt" with link
4. Delete "test"
5. Check "oc_shares"

### Expected result
The share entry is gone.

### Actual result
The share entry still exists.
Also, the link share can still be opened and shows a page with an empty file or folder!

### Versions
ownCloud 6 (stable6)
ownCloud 7 (stable7)
ownCloud 8 (stable8)
master

@schiesbn I vaguely remember that there were technical issues (maybe performance) if we want to properly delete all shares

**Comment by PVince81** [comment]
Workaround would be to run this https://github.com/owncloud/core/issues/12323 after a deletion (or on a regular basis).

But the other bug is that the link share doesn't give 404 directly.

**Comment by wshadow** [comment]
Another case for Foreign keys? #13143

**Comment by PVince81** [comment]
Yeah...

CC @DeepDiver1975

**Comment by PVince81** [comment]
Setting to 8.1 to keep this in mind...

**Comment by PVince81** [comment]
@jnfrmarks another test case. Can probably be verified by checking that the created link share does not exist any more after deleting the parent folder. (currently if you query it with the OCS Share API you'll see that it still exist)

**Comment by PVince81** [comment]
It looks like shares set directly on the deleted item (file/folder) is deleted here: https://github.com/owncloud/core/blob/master/apps/files_sharing/lib/updater.php#L89

Maybe that code needs to be extended to also do the same for all children.
That's the place where I miss something like "SELECT fileid FROM children" ...

**Comment by PVince81** [comment]
I guess a 8.1 scoped solution would be to trigger a background job to delete all orphaned shares (not only the currently deleted one).
The query itself can be expensive in case of many orphaned entries with SQLite since we cannot use DELETE + LEFT JOIN (like MySQL allows), so better put it in a background job.

**Comment by PVince81** [comment]
Duplicate of https://github.com/owncloud/core/issues/6985
