### ISSUE TITLE
App callbacks

### ISSUE THREAD

**Issue by BernhardPosselt** [owncloud/core#14666]
Sometimes you need to execute code after an app was initialized (appinfo/app.php included) or after an app is active, for instance adding additional JavaScript or CSS to an app. The biggest motivation for me is the REQUEST_URI not found error when running cron, basically its unreliable to check the URL if an app has been started since sometimes there might not even be an URL. IIRC @butonic suggested something similar, I can't find the issue however.

My proposal is to do the following:

``` php
OC::$server->getAppManager()->onAppInit($callback, $appId);
OC::$server->getAppManager()->onAppLaunch($callback, $appId);

// adding JS for the files app
// files_sharing/appinfo/app.php
OC::$server->getAppManager()->onAppLaunch(function () {
    OCP\Util::addScript('files_sharing', 'script');
}, 'files');
```

The $appId parameter is optional. If it is not set, it will be executed for every app. 

@MorrisJobke @DeepDiver1975 @jbtbnl @LEDfan @georgehrke @oparoz @icewind1991 @butonic

**Comment by Raydiation** [comment]
@LukasReschke

**Comment by Raydiation** [comment]
As for the implementation: The onAppInit will be run here: https://github.com/owncloud/core/blob/master/lib/private/app.php#L101

The onAppLaunch will be run here https://github.com/owncloud/core/blob/master/lib/private/appframework/app.php#L84

Which basically means that only app framework apps will support onAppLaunch out of the box. There is no good way to determine this for legacy apps, so apps like the files app will need something like **OC::$server->getAppManager->notifyAppLaunched('files');** in its index.php/ajax files

**Comment by Raydiation** [comment]
@PVince81

**Comment by DeepDiver1975** [comment]
Nice - I like that! Thanks!

This will also help to reduce the amount of code being executed during startup.

**Comment by DeepDiver1975** [comment]
Should we also add a parameter to the callback indicating the request type like

- web
- console / command
- cron
- webdav / api

**Comment by Raydiation** [comment]
web/api: should work with onAppLoaded

command/console/cron: onLoaded is not needed because no app is active

onAppInit will work for all the types that youve mentioned and could receive the type. Is there something   reusable to get the type of the request?

**Comment by DeepDiver1975** [comment]
I see the following use case:
- in case the request is an api or webdav request - there is no need to work on css and js
- only in case the request type is cron I might want to add my cron tasks

**Comment by DeepDiver1975** [comment]
but - yes - one could query the request type somehow.

**Comment by Raydiation** [comment]
Yep, lets keep it simple for now. Adding scripts should be unproblematic if no template is being rendered

**Comment by DeepDiver1975** [comment]
There is one problem : the load order

One could only listen to an app init event if that app is loaded afterwards.

We might want to collect all apps which got activated and fire the event afterwards.

furthermore: it's this all about event dispatching? We might want to think about using symfony's event dispatcher for this purpose?

**Comment by butonic** [comment]
the PR is here: https://github.com/owncloud/core/pull/12613

**Comment by Raydiation** [comment]
Ok, that's something different :)

**Comment by Raydiation** [comment]
@DeepDiver1975 good idea, how do we want to build it in? I'd just use the type and dont wrap anything around it or do we need to create a separate EventDispatcher class in lib/private which extends the dispatcher and implements a public interface?

**Comment by nickvergessen** [comment]
Would be nice to have this. Currently files_texteditor, files_version, gallery and other apps load their scripts and styles in app.php making pages that are independent from teh files lsit (settings, activity, ...) unnecessary slow.

**Comment by DeepDiver1975** [comment]
> good idea, how do we want to build it in?

hmmm - generally speaking I'd love to keep external interfaces/classes out of our public api.
Reasoning - just in case we are ever forced to update symfony's eventdispatcher (because it's a dependency to many other components we (will) use) this might break our api.

On the other hand - will symfony's event dispatch ever change that radical?

Well - creating a tiny wrapper will no damage that much ... hopefully :speak_no_evil: 

But - most important we have to thank about the load order issue as described above - https://github.com/owncloud/core/issues/14666#issuecomment-76940014

**Comment by PVince81** [comment]
Quick solution: https://github.com/owncloud/core/pull/18290

**Comment by PVince81** [comment]
Well that one only for the files app.

**Comment by DeepDiver1975** [comment]
I am still all in for symfony event dispatcher.
For this case as well as replacment for hooks and our emitters.

**Comment by Raydiation** [comment]
:+1: for symfony

**Comment by oparoz** [comment]
SED would be nice for AppFramework users :) :+1:

**Comment by nickvergessen** [comment]
I'm in as well, the question is, who implements it :speak_no_evil:

**Comment by PVince81** [comment]
In @Raydiation's example in the first post https://github.com/owncloud/core/issues/14666#issue-59627039 I don't see how this would guarantee that an app runs after the "files" app. There is no reference of the "files" app in the code.

Should it be `onAppLaunch('files', callback)` intead ?

I don't know much about symphony so I'd appreciate it if someone who knows it could implement it.

**Comment by PVince81** [comment]
8.2 makes the symphony event dispatcher public, which opens new possibilities, see https://github.com/owncloud/core/pull/18316

The activity app for example already uses an event triggered by the files app to load files-specific JS code. https://github.com/owncloud/activity/blob/master/lib/fileshooksstatic.php#L43

Should we close this ticket or is there anything else to add ?
Moving to 9.0 in the meantime.

**Comment by oparoz** [comment]
The only thing left would be to add some documentation and mnodify ocdev. All apps should listen fro now on instead of dump their scripts on poor Files.

**Comment by DeepDiver1975** [comment]
> Should we close this ticket or is there anything else to add ?

I'd say close - the event dispatch allows to broadcast data/events which has to be sufficient

**Comment by MorrisJobke** [comment]
> The activity app for example already uses an event triggered by the files app to load files-specific JS code. https://github.com/owncloud/activity/blob/master/lib/fileshooksstatic.php#L43
> 
> Should we close this ticket or is there anything else to add ?

@PVince81 @nickvergessen Can one of you add the documentation?
