### ISSUE TITLE
Check for mbstring.func_overload in lib/private/util.php fails if php-mbstring extension is not installed

### ISSUE THREAD

**Issue by Raydiation** [owncloud/core#14670]
Just ran into this on the latest fedora, was very hard to debug. We need to check if the mbstring module exists before checking for the func_overload setting

@LukasReschke @DeepDiver1975 @MorrisJobke @PVince81

**Comment by karlitschek** [comment]
Yes. Who can help to add this check?

**Comment by LukasReschke** [comment]
All mine.

**Comment by LukasReschke** [comment]
Patch proposal is at https://github.com/owncloud/core/pull/16048
