### ISSUE TITLE
Internal Server Error after attempting to do "occ files:scan"

### ISSUE THREAD

**Issue by tmason101** [owncloud/core#14681]
Hello,
After upgrading to latest ownCloud version (8.0.0 or 8.0.1) the files for various users no longer appears. All passwords worked normally and the ownCloud instance otherwise responded normally.

In attempting to resolve the issue by running "occ files:scan --all" the ownCloud instance now responds with an "Internal Server Issue".

The server logs report the following:

	{"reqId":"VPa8kse8zJwAAxPulDwAAAAB","remoteAddr":"[[[MY IP]]]","app":"PHP","message":"Declaration of OC\\Files\\ObjectStore\\NoopScanner::scanFile() should be compatible with OC\\Files\\Cache\\Scanner::scanFile($file, $reuseExisting = 0, $parentId = -1, $cacheData = NULL) at [[[WEBROOT]]]\/owncloud\/lib\/private\/files\/objectstore\/noopscanner.php#74","level":3,"time":"March 04, 2015 03:04:34","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
	{"reqId":"VPa8kse8zJwAAxPulDwAAAAB","remoteAddr":"[[[MY IP]]]","app":"PHP","message":"Declaration of OC\\Files\\ObjectStore\\NoopScanner::scanChildren() should be compatible with OC\\Files\\Cache\\Scanner::scanChildren($path, $recursive = self::SCAN_RECURSIVE, $reuse = -1, $folderData = NULL) at [[[WEBROOT]]]\/owncloud\/lib\/private\/files\/objectstore\/noopscanner.php#74","level":3,"time":"March 04, 2015 03:04:34","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
	{"reqId":"VPa8sce8zJwAAxQyljkAAAGC","remoteAddr":"[[[MY IP]]]","app":"PHP","message":"Declaration of OC\\Files\\ObjectStore\\NoopScanner::scanFile() should be compatible with OC\\Files\\Cache\\Scanner::scanFile($file, $reuseExisting = 0, $parentId = -1, $cacheData = NULL) at [[[WEBROOT]]]\/owncloud\/lib\/private\/files\/objectstore\/noopscanner.php#74","level":3,"time":"March 04, 2015 03:05:05","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
	{"reqId":"VPa8sce8zJwAAxQyljkAAAGC","remoteAddr":"[[[MY IP]]]","app":"PHP","message":"Declaration of OC\\Files\\ObjectStore\\NoopScanner::scanChildren() should be compatible with OC\\Files\\Cache\\Scanner::scanChildren($path, $recursive = self::SCAN_RECURSIVE, $reuse = -1, $folderData = NULL) at [[[WEBROOT]]]\/owncloud\/lib\/private\/files\/objectstore\/noopscanner.php#74","level":3,"time":"March 04, 2015 03:05:05","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"} 

What can I do to get rid of the message and restore the files?

All data still resides in the data folder for the respective users.

Thank you.

**Comment by nickvergessen** [comment]
You would need to do the following modifications:
https://github.com/owncloud/core/pull/14682/files

**Comment by tmason101** [comment]
Thank you for the fast reply! This does solve the error message.

However, I still don't see any files in the ownCloud system even though the data directory certainly contains files for all of the defined users. The directory structure is exactly the same as it was from the previously working instance.

Is there a way to force ownCloud to read the data outside of using occ files:scan --all?

The command reports no errors but the system is never populated with the files that clearly exists.

**Comment by DeepDiver1975** [comment]
let's keep this open until this is fixed in stable8 branch

**Comment by tmason101** [comment]
What about the files not appearing issue; do I open a separate issue for that?

**Comment by nickvergessen** [comment]
Yes, create a new issue please

**Comment by DeepDiver1975** [comment]
closing this - backport has been merged: https://github.com/owncloud/core/pull/14686
