### ISSUE TITLE
Problem with the email field (OC 8.0.0.7)

### ISSUE THREAD

**Issue by lambdax1** [owncloud/core#14683]
Hi,
I use Owncloud 8.0.0.7 with the ldap plugin.
But i have a problem with the email field. I set the Special attribute "Email Field" to mail. (does not work)
I also set  the "User Home Folder Naming Rule" to mail  (and that works...) 
![special attrib owncloud](https://cloud.githubusercontent.com/assets/6041858/6481503/439caaf0-c25e-11e4-997f-054eca97b494.png)

any idea?
Thank!

P.S: Sorry for my "bad" english.

Michaël

**Comment by DeepDiver1975** [comment]
@blizzz can I ask you to have a look at this? THX

**Comment by blizzz** [comment]
@lambdax1 can you elaborate on what exactly does not work?

**Comment by lambdax1** [comment]
Sry, but it works now. After +/-  24 h.
