### ISSUE TITLE
Files not appearing even after running ./occ files:scan --all

### ISSUE THREAD

**Issue by tmason101** [owncloud/core#14684]
Hello,

I have two (2) ownCloud instances; own which represents the latest version of ownCloud (8.1 alpha) and one which represents my Used-to-be-stable install after I reverted to a backup of the upgrade that failed.

In BOTH cases, I cannot see any of the users data even though the data folders for both instances contains the users files/folders.

I can log in perfectly as any of the users with their old passwords/see their settings/etc. but no files show up for anyone.

I verified that the permissions on the folder is the same as they were before, the config.php file has the location of the data folder set up correctly, and that I restored the database 100% as it was before (especially for the 7.0.4 instance that used to be working).

I get no error messages when I run ./occ files:scan --all

What gives?

Is there a way I can load the files manually in with database entries? I can write a script but I need to know if that is worth the effort and if that is the right direction to go.

Thank you for your time.

**Comment by karlitschek** [comment]
@icewind1991 Do you have any insights here?

**Comment by PVince81** [comment]
@tmason101 can you have a look at the `oc_storages` and see if there are duplicate entries ?
You might see entries with the format "local::$datadir/$userid" and "home::$userid". For every user there should be only ONE of such entries, not BOTH.
Please post your findings.

Did you change the "datadir" in config.php option for the upgrade ? (did you upgrade from OC 5 at some point ?)

**Comment by caineone** [comment]
Hi PVince81,
what happens if you have a user with both: local and home entry in the oc_storages table? I'm honestly not really sure what this table manages.
Thanks in advance.

**Comment by PVince81** [comment]
These entries are linked with oc_filecache and contain the indexed files.
If your files are not showing it is likely that the index is the wrong one... somehow.

If you have both then it depends on the "datadir" value in the config.php

The logic is as follows:
1) First it searches oc_storages to see if there is an entry with the format "local::$datadir/$user". If yes, it uses that.
2) If not, it searches oc_storages for an entry with the format "home::$user".
3) If none is found, it automatically creates a new "home::$user" entry with brand new file cache

The "local::" entries were the old format. They're bad because they have the data dir hard-coded.

So now if recently you changed the datadir value in the config, then it might happen that OC didn't find "local::$datadir/$user" any more because $datadir changed, so it would automatically create a new one (as per 3)) which is empty by default.

**Comment by caineone** [comment]
Thank you very much for the explanation. This helps me to understand. So I can delete the old entry with the static link and it will use the "home-link" instead automatically.
Maybe this is another problem and off topic. How is it handled when a user get access to a share via group? I have two users which have no directly (to the username) assigned share. Only via group. And one user can see all shares the other not. Is there another table for that sharing information than the "oc_shares" table?

**Comment by PVince81** [comment]
Please do not manually delete the old entry, unless you are sure that it doesn't contain your missing files. You need to find which one of "local::" or "home::" is containing the missing files, then delete the other one.

The share information for local shares is only in the "oc_shares" table. Note that the shares are linked with the files through "file_source" which is the fileid inside the "oc_filecache" table.
If there is a storage mismatch problem and the file is in the wrong storage, then it is possible that it won't be visible. You might want to fix the storage issue first.

**Comment by caineone** [comment]
Hi PVince81, is it possible to contact you via PN?

**Comment by PVince81** [comment]
You can find my on IRC in the owncloud-devel channel.

**Comment by PVince81** [comment]
Are you still having issues with 8.1.0 ?

**Comment by caineone** [comment]
I still haven’t installed the newest version. But we started a service contract with owncloud and we will install the newest version on a new linux server within the next weeks.

Best regards,
Marko

Von: Vincent Petry
Antworten an: owncloud/core
Datum: Montag, 3. August 2015 15:45
An: owncloud/core
Cc: Marko Beyer
Betreff: Re: [core] Files not appearing even after running ./occ files:scan --all (#14684)


Are you still having issues with 8.1.0 ?

**Comment by PVince81** [comment]
how about you @tmason101, still having issues with 8.1 ?

**Comment by MelonSmasher** [comment]
I am also experiencing a the same issue. I am currently running `8.1.1`. 

I have each users `files` directory shared as their Home drive is active directory over SMB. Any file modifications that take place on that end of the storage do not show up in the web interface.

I have `'filesystem_check_changes''` set to `3` in my config.php. I have also tried running:

```shell
sudo -u www-data php occ files:scan --all
```

Even this did not force any changes to ownclouds cache.

**Comment by PVince81** [comment]
Should work in 8.1.3, please follow up here https://github.com/owncloud/core/issues/13456#issuecomment-142247261
