### ISSUE TITLE
Upgrade Status Report

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#14680]
When upgrading ownCloud, the overall process is a bit of an unknown.

If you kick off the upgrade, for example, we don't tell a user in any way what apps will be disabled, which will be enabled, and which won't work. After the upgrade, we don't point out (if you missed the upgrade screen showing you) what actually happened, and what will or won't work.

The request is for this:
As an admin, I want to be able to see a pre-upgrade and post-upgrade report of my upgrade so I know what apps worked, what will be disabled because they are 3rd party, and which won't be upgraded because there is no newer code available so that I have my expectations set and managed through the upgrade.

The reports should be visible for the last few patch release and major version upgrades, and should look something like this:

Version:              7.0.4            >            8.0.1
Core Server    active > active | update planned
Installed Supported Apps:
Sharing          active > active | update planned
File Firewall    active > active | update planned
SharePoint     active > active | update planned
...(etc)
Installed Unsupported Apps:
Contacts         active > active | update planned
Files Move     active > de-activated | update not planned. App will not work after upgrade as no ownCloud 8.0.1 compliant code can be found in the app store
..(etc)

then, during the update, the update planned would move to update successful (or not).
this report would have a date associated with it and be available and visible from an "update report" mechanism in the admin panel.

**Comment by MTRichards** [comment]
@karlitschek @jancborchardt @jnfrmarks 
Something to consider as a starting point for this feature.

**Comment by jancborchardt** [comment]
cc @DeepDiver1975 @VicDeo @te-online regarding the updater.

**Comment by DeepDiver1975** [comment]
@jancborchardt unrelated to the updater app - more related to the core parts of upgrade execution

**Comment by te-online** [comment]
I like the idea of making upgrading more transparent. :+1: As versions of owncloud come and go, one main task of admins will always be to upgrade to a newer version. And this task should cause as little headache as possible.
Maybe we could take some advantage from looking at the process of how operating systems or other webbased systems are doing upgrades and managing dependencies and compatibility-issues.

@DeepDiver1975 Are »the core parts of upgrade execution« located *in* core? So a core team could create a *backend* for this (given that there is room for it)?

@jancborchardt Parallel, the task of the updater app might be to create a usable interface for this function?

**Comment by PVince81** [comment]
Partly related: https://github.com/owncloud/core/issues/14569 to not automatically redirect whenever there were errors.

**Comment by PVince81** [comment]
In 8.2 we'll have this: https://github.com/owncloud/core/pull/17434.

We still need to add a section for third party apps that would be disabled.

**Comment by PVince81** [comment]
@DeepDiver1975 didn't we add this already in the very verbose update progress output ?
