### ISSUE TITLE
[stable7] Select all + delete misses delete action in trashbin

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#14687]
### Steps
1. Delete a bunch of files
2. Go to trashbin
3. Select all with the checkbox
4. In the selection overlay, click "Delete"

### Expected result
"Delete" link is there and working.

### Actual result
"Delete" link is missing

### Versions
ownCloud 7.0.5 final

@karlitschek @DeepDiver1975 @jnfrmarks @schiesbn 

Going to investigate this.

**Comment by PVince81** [comment]
Bisected, this is the breaking commit: 3720ba931802fb75f84eb928d0a742dee8a28327 from @icewind1991 

I thought we fixed this already, maybe missing a backport.

**Comment by PVince81** [comment]
Confirmed. That regression existed on OC 8 and was fixed later: https://github.com/owncloud/core/issues/12675

We need to backport that fix https://github.com/owncloud/core/pull/12696 to OC 7.
Will prepare a PR.

**Comment by PVince81** [comment]
PR here, please review promptly: https://github.com/owncloud/core/issues/14688

**Comment by nickvergessen** [comment]
Fix has been merged
