### ISSUE TITLE
[RFC] remove support for `*dbprefix*` support and `dbtableprefix` config variable

### ISSUE THREAD

**Issue by martin-rueegg** [owncloud/core#14695]
regarding the discussion in https://github.com/owncloud/core/pull/6332#issuecomment-43861623 and https://github.com/owncloud/core/pull/14658#issuecomment-77222770 (and probably others) there is a question if support of the given multi-oc-instance-in-one-db feature should be dropped.

**argument to keep:**
- multiple oc instances could be hosted in one database
- or the database could be shared with any other application that uses the `oc_` prefix

**arguments to drop are:**
- no real world usage (no one actually uses it)
- functionality is broken (eg. indexes do not currently support this feature [see #14658] while required by certain dbms's)
- on the long run, it will sure make code easier
- stability could be improved through simplifying the code

**a scenario to go for dropping support could be:**
- a grace period should be defined during which users are notified to change the `dbtableprefix` to `oc_` (or dropping it, with the same result)
- during the grace period a config value `dbtableprefixmigrate` could be introduced. when set, upon the next upgrade the prefix would be changed to `oc_` by renaming the tables and dropping both `dbtableprefix` and `dbtableprefixmigrate` variables.
- after the grace period, an exception should be thrown, if `dbtableprefix` is set. the migration can still be done automatically but becomes mandatory. except for the upgrade code, the code will be cleaned of replacement features and using static `oc_` value instead.
- additionally after the grace period an exception should be thrown if a) an app installed is using `*dbprefix*` in table names (it should automatically be disabled to not block the entire oc instance) or any such is attempted to be installed (which thus should fail).
- documentation needs to be updated accordingly.

**Comment by MorrisJobke** [comment]
cc @icewind1991 @DeepDiver1975 @PVince81 @LukasReschke @bantu @Raydiation

**Comment by MorrisJobke** [comment]
I like this idea. It would also reduce the workload for app developers.

**Comment by Raydiation** [comment]
I'm actually not sure if I like it or not. Fixing the indices should be easy

**Comment by martin-rueegg** [comment]
@Raydiation, you're right, fixing the indices is quite easy. in fact, the code is already provided (#14658 [open] and #14660 [merged]).
the question is more of general nature due to @DeepDiver1975's https://github.com/owncloud/core/pull/14658#issuecomment-77154805. so maybe other issues related to that topic could be linked to this issue, so we would have an overview.
it would be interesting thouh, if @Raydiation could point out, what are the pros and cons. what are your considerations? 
if you have specific arguments, note them here and i will add them to the initial comment.

**Comment by Raydiation** [comment]
I think one of the cons is that the user can sometimes be restricted to one database and the tables might already exist from a different software, it doesn't particularly have to be another owncloud installation. 

Also we will break apps yet again. I think if the fix is that easy we should just fix it and not break backwards compatibility

**Comment by DeepDiver1975** [comment]
I had a quick look (well - by accident basically) - and there is no need to name an index. DBAL will auto generate the name (and/or leave it to the db). 
This might allow us to fix this issue rather easily.

**Comment by remixtj** [comment]
I'm interest in preserving this feature. In my company we are starting to sell several oc instances and we're sharing the same postgresql db with several other applications. Each package of applications have it's own schema and all owncloud instances are packaged on a single package and so will use the same schema. In case of drop of this feature i'll have to ask db administrators to configure a different schema for each owncloud instance, requiring additional work for each instance.
