### ISSUE TITLE
underscore_, dash- problem in uploaded files/folders

### ISSUE THREAD

**Issue by atiderko** [owncloud/core#14697]
I use owncloud 8.0 on Windows 7x64 with:
- apache 2.4
- php 5.6.5
- mysql 5.6

The problem arises when I work with the web browser and on the file server using file browser.

If I use webbrowser to create folder `aaa_abb` the ownlcoud creates one `aaa-bbb` on my disk. After this I put a file using my file browser on my server. To update the database I run 
`php console.php files:scan USER`:

And this is is that the script do:
files/aaa_bbb
files/aaa_bbb/
files/aaa_bbb/
files/aaa_bbb//
files/aaa_bbb//
files/aaa_bbb///
files/aaa_bbb///
files/aaa_bbb////
files/aaa_bbb////
files/aaa_bbb/////
files/aaa_bbb/////
files/aaa_bbb//////
files/aaa_bbb//////
files/aaa_bbb///////
files/aaa_bbb///////
files/aaa_bbb////////
files/aaa_bbb////////
files/aaa_bbb/////////
files/aaa_bbb/////////
files/aaa_bbb//////////
files/aaa_bbb//////////

I have to cancel the script execution :-/

This is one of the problems. The other is, that all underscores of uploaded files are replaced by dashes on the disk (all my photos ;-(). But if I copy the file using file browser and update with `console.php`-script the file have still underscores. It is very confusing! Is there an important reason, why owncloud rename the files/folders?

**Comment by nickvergessen** [comment]
You should not use the data directory on a windows server and browse the files. The file names are cleaned, because on linux you can have some file names which are not allowed, and e.g. you can upload `Hello` and `hello` which are two different files on linux, but the same on windows.

Also when you don't directly modify/upload files in the data dir, you should avoid calling the `console files:scan`

**Comment by atiderko** [comment]
What a pity! Thanks for the answer!
And on linux the file names are not cleaned? And I can use the data dir to include hundreds of GBs of my  photos and videos without upload it through owncloud interface?

**Comment by nickvergessen** [comment]
Yes I think that should work on linux, although I never actually tested it. But I know for sure it does not work on windows.

**Comment by atiderko** [comment]
thank you!
Perhaps I will give it a try, on virtual machine first ;-)

**Comment by MorrisJobke** [comment]
@DeepDiver1975 Wasn't the support for windows dropped with 8.0?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 Wasn't the support for windows dropped with 8.0?

see the milestone names 'backlog' - just because of that :wink:
