### ISSUE TITLE
Email notifications for files shared by myself

### ISSUE THREAD

**Issue by shoeper** [owncloud/core#14709]
**Actual behaviour**: I get email notification for files I've shared via link. I did not select "inform about activities done by myself" (Über Ihre eigenen Aktivitäten via E-Mail benachrichtigen).

**Expected behaviour**: Because I did not select "inform about activities done by myself" I don't get any notifications for files I've shared.

**Steps to reproduce**:
1. Enable notifications for sharing files or folders
2. Share a file link via Android app (did not test with browser)
3. You get an email that you've shared the file

*I'm using ownCloud 8.0 (stable) on a shared hosting with php 5.5 (fcgi) + apache and emails are send via   smtp.*

**Comment by LukasReschke** [comment]
Can you please reopen at https://github.com/owncloud/activity? – THX!
