### ISSUE TITLE
Errors after upgrade to 8

### ISSUE THREAD

**Issue by highacid** [owncloud/core#14714]
Error	PHP	Array to string conversion at /home/uhlhosting/public_html/work/lib/private/l10n/string.php#75	2015-03-05T15:20:26+00:00
Error	PHP	Undefined index: item_type at /home/uhlhosting/public_html/work/lib/private/share/share.php#1179	2015-03-05T15:16:02+00:00
Error	PHP	Undefined index: item_type at /home/uhlhosting/public_html/work/lib/private/share/share.php#1179	2015-03-05T15:16:02+00:00
Error	PHP	Undefined index: item_source at /home/uhlhosting/public_html/work/lib/private/share/share.php#1173	2015-03-05T15:16:02+00:00
Error	PHP	Undefined index: item_type at /home/uhlhosting/public_html/work/lib/private/share/share.php#1172	2015-03-05T15:16:02+00:00
Error	PHP	Array to string conversion at /home/uhlhosting/public_html/work/lib/private/l10n/string.php#75	2015-02-23T11:11:53+00:00
Error	PHP	Array to string conversion at /home/uhlhosting/public_html/work/lib/private/l10n/string.php#75	2015-02-21T04:02:31+00:00
Error	PHP	Array to string conversion at /home/uhlhosting/public_html/work/lib/private/l10n/string.php#57	2015-02-19T08:58:36+00:00
Error	PHP	Call to a member function getSize() on a non-object at /home/uhlhosting/public_html/work/lib/private/helper.php#981	2014-12-04T20:35:41+00:00

**Comment by DeepDiver1975** [comment]
@highacid did you follow the upgrade instructions and remove everything with exception of the config and data folder?

**Comment by highacid** [comment]
this upgrade was done automatic by installatron plugin.

**Comment by DeepDiver1975** [comment]
@highacid mind giving a try to install 8.0.2? THX

**Comment by PVince81** [comment]
Please try again with 8.0.6 or 8.1.1.

If you're still having issues, please reopen and provide more information using the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md
Thanks.
