### ISSUE TITLE
Maximum upload file size resets itself

### ISSUE THREAD

**Issue by shoeper** [owncloud/core#14710]
**Actual behaviour**: I set a maximum upload file size via oc admin panel (and click on save), but it resets itself.

**Expected behaviour**: Oc should keep my value and show it to all user wanting to upload files.

**Steps to reproduce**:
1. Set upload filesize in admin panel & save
2. reload page
3. upload file size has not been saved and is not shown to users (so no admin panel bug)

**Why do I want to set my own value?**
My shared hosting has a hard limit at 128MB so when ownCloud does everything to make me able to upload 513MB that does not work because of the hardlimit.

*I'm using ownCloud 8.0 (stable) on a shared hosting with php 5.5 (fcgi) + apache*

**Comment by karlitschek** [comment]
@blizzz any idea?

**Comment by blizzz** [comment]
Works for me.
Is .htaccess writable and allowed by your web server configuration?

**Comment by PVince81** [comment]
Very likely that the .htaccess has been overwritten.

Do you upgrade using RPM/DEB packages ?

**Comment by shoeper** [comment]
It is writable
before:
```
<IfModule mod_php5.c>
php_value upload_max_filesize 513M
php_value post_max_size 513M
php_value memory_limit 512M
php_value mbstring.func_overload 0
php_value always_populate_raw_post_data -1
<IfModule mod_env.c>
  SetEnv htaccessWorking true
</IfModule>
</IfModule>
```

after change:
```
<IfModule mod_php5.c>
php_value upload_max_filesize 128M
php_value post_max_size 128M
php_value memory_limit 512M
php_value mbstring.func_overload 0
php_value always_populate_raw_post_data -1
<IfModule mod_env.c>
  SetEnv htaccessWorking true
</IfModule>
</IfModule>
```

But browser still says limit = 513m (Did test with chrome and firefox)

**Comment by deMattin** [comment]
Hm, I've read this issue and wonder, why I don't have this setting in my owncloud admin panel.
I have to set php values manually.
I'm using Suse repo and have OC 8.0.1 installed.
Sorry for this off topic question, but how should this setting look like and has anybody an idea, why this isn't shown?

**Comment by MorrisJobke** [comment]
@deMattin The setting is just visible if the webserver is able to write to the .htaccess. If this is not the case, the setting is just hidden.

**Comment by deMattin** [comment]
Many thanks for this information.
I switched rights of .htaccess to group: www-data (has been root) and gave it read/write and the setting is there and works.

I used direct install with OC 5/6 and switched to suse repo with 7 and now 8 and could remember I had such setting ages ago. But I thought, the feature, to set this in admin panel has been removed.
In documentation there is also no indication of this setting so I haven't looked for it.

I don't know, which other settings screens I perhaps don't see because of "wrong" or not optimal default configuration.

Over all I think, it's not a good idea to completely hide not setable **core** features if some conditions aren't given.
It would be much better to give a hint instead like: "This setting is not available because of missing rights to write to ".htaccess".

**Comment by MorrisJobke** [comment]
> All in all I think, it's not a good idea to completely hide not setable core features if some conditions aren't given.
> It would be much better to give a hint instead like: "This setting is not available because of missing rights to write to ".htaccess" or something like this.

cc @jancborchardt

**Comment by DeepDiver1975** [comment]
8.1 will display the information even if htaccess is readonly.

**Comment by shoeper** [comment]
To come back to the issue.
How does oc examine the max file upload size shown on hover of the upload button and in the admin panel.
Because the htaccess value is actually getting changed. But not shown.

**Comment by shoeper** [comment]
Ok it is done here: https://github.com/owncloud/core/blob/13b0b7dfaf6553411928677420d8d21fa352bb3e/apps/files/admin.php and read by ini_get. Looks fine but does not work for some reason.

**Comment by deMattin** [comment]
On topic I wrote: It works for me ...
My idea to this would be, that the hoster force overwrites such settings or you have another .htaccess, which overwrites this value.

**Comment by shoeper** [comment]
But not to 512MiB.
Hardlimit is 128MiB.
But okay seems to be due to shared hosting - just don't get why.

Btw afaik till php 5.5 max post size must be as least as big as max upload size. This case is not handled via oc. Oc just asks for max upload size. (But tjis isn't the problem in my case.

**Comment by RealRancor** [comment]
@deMattin 
>All in all I think, it's not a good idea to completely hide not setable core features if some conditions aren't given.
It would be much better to give a hint instead like: "This setting is not available because of missing rights to write to ".htaccess" or something like this.

Have requested this quite some time here: https://github.com/owncloud/core/issues/10600

**Comment by RealRancor** [comment]
@shoeper 
As your hoster is on fcgi have a look at the .user.ini which also contains the upload limits. From a short look it seems the file handling box is only writing to .htaccess. But as fcgi is not using the this and only the .user.ini this could explain your noticed behaviour.

**Comment by shoeper** [comment]
If owncloud does not write to the user.ini then it can't be the reason because it did not change it and hard upload limit is 128MB. I've listet my htaccess values above - I just don't understand why oc says upload limit 513M when there's 128MB limit in htaccess and 128MB hard limit

**Comment by RealRancor** [comment]
Yes, you didn't changed it so it is still set to 513 MB and not to the size you have put into the box. That could explain this behaviour.

The file size itself is calculated here: https://github.com/owncloud/core/blob/v8.0.0/apps/files/admin.php#L28-L30

So the minimum of both settings is your max upload size. You could use a phpinfo file to check which limits are currently set for your environment.

**Comment by shoeper** [comment]
Did you look at my htaccess above? Don't think so.


Am 9. März 2015 01:21:19 schrieb RealRancor <notifications@github.com>:

**Comment by RealRancor** [comment]
htaccess files are not used in fcgi

**Comment by shoeper** [comment]
Ok I'm sorry. 

That explains a lot. I've never created a user.ini but one is there with ownclouds limits.

So as you've written in #14748 if owncloud ships a user.ini it should also write to it on change of settings in admin panel. Maybe owncloud should also check hardlimits on chaning values.
I'm just not sure on how ownCloud could handle hard limits (the webserver could e.g. also have limits on upload max file size, I've tried bigger files than 128MB but they don't work) - not sure if it is possible.

**Comment by RealRancor** [comment]
Hi,

yes the problem with such webserver limits like described in https://doc.owncloud.org/server/8.0/admin_manual/configuration_files/big_file_upload_configuration.html#apache is that ownCloud/PHP can't or write them.

**Comment by shoeper** [comment]
Yeah I understood that, unfortunately there also seems to be no way to determine those limits.
But that's a point where we can live with. Almost every hoster states somewhere which those limits are.
