### ISSUE TITLE
can't upgrade 8

### ISSUE THREAD

**Issue by michaelCrusem** [owncloud/core#14715]
An index with name 'keyid_index' was already defined on table 'oc_privatedata'

**Comment by DeepDiver1975** [comment]
@michaelCrusem Thanks a lot for reporting issues back to us!

We need some more information to properly support you with your issue!

Can I ask you to follow our guidelines for submitting bugs as described here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

Thanks a lot!
