### ISSUE TITLE
Implementing privacy security for user files

### ISSUE THREAD

**Issue by skironDotNet** [owncloud/core#14717]
Currently anybody who has an access to FTP can browse any user files.
Is there a way to encrypt files on the fly or otherwise protect so even admin could not access them, well access maybe could but not open them?

I can only imagine that this would performance and resource hit, encrypt each file with user password hash (not with user password, the hash of password) then if user request password reset, all files would have to be decrypted with old hash, random password generated as is and re-ecrypted using new password hash. then when user sets new password, do the job again for all files.

Browsing also, but at least decription to be faster.

Personally I don't believe anybody will implement such, but who knows we could experiment

**Comment by PVince81** [comment]
Please use the "server side encryption" app. It already encrypts files and the encryption key is encrypted using the user's password.

**Comment by skironDotNet** [comment]
how about ownCloud web client?

**Comment by PVince81** [comment]
Some info about the encryption app: https://doc.owncloud.org/server/7.0/admin_manual/configuration/encryption_configuration.html and https://doc.owncloud.org/server/7.0/user_manual/files/encryption.html

Basically the files are always encrypted on the server through the PHP code, regardless how you access them.

If you use the web UI and upload a file, it will be encrypted on the server.
When you download it with the web UI, the server will decrypt it and send it back for download.
Inside the "data" folder the files are always encrypted.

**Comment by skironDotNet** [comment]
Thank you! this is exactly what I needed. I just didn't know it exists, links were very helpful.

One question, why each files has such big header, I've been doing AES-256 encription and this part is not really part of encrypted data

HBEGIN:cipher:AES-256-CFB:HEND---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by PVince81** [comment]
This is a customer header for OC to store metadata like encryption cypher.
