### ISSUE TITLE
Sharing folder to group ro & subfolder to user rw adds folder twice

### ISSUE THREAD

**Issue by butonic** [owncloud/core#14724]
### Steps to reproduce
1. Create a user *test* in group *testgroup*
2. share `/testfolder` ro with *testgroup*
3. share `/testfolder/subfolder` rw with *test*

### Expected behaviour
*test* receives `/testfolder` with ro permissions and `/testfolder/subfolder` with rw permissions

### Actual behaviour
*test* receives `/testfolder` with ro permissions and a second `/testfolder (2)` with rw permissions with the content of `/testfolder/subfolder`

### Acceptable, but unintuitive solution
*test* receives `/testfolder` with ro permissions and `/subfolder` with rw permissions
behavior needs to be documented

### Related
https://github.com/owncloud/core/issues/4579

**Comment by DeepDiver1975** [comment]
This is by design from my pov - two shares -> two folders on the receiver

**Comment by DeepDiver1975** [comment]
Two shares will result in two folders on the receiver side - anything else will add too much kung-fu.

I'd expect to get testfolder and subfolder as two separate folders.

**Comment by PVince81** [comment]
I agree with @DeepDiver1975. This is by design.

**Comment by PVince81** [comment]
CC @schiesbn

**Comment by butonic** [comment]
Then there is a bug that mixes up folder names and creates a `/testfolder (2)` instead of `/subfolder`. Also broken in OC7.0.4

**Comment by DeepDiver1975** [comment]
> Then there is a bug that mixes up folder names and creates a /testfolder (2) instead of /subfolder.

indeed - agreed

**Comment by PVince81** [comment]
So, duplicate of https://github.com/owncloud/core/issues/13213 ?

**Comment by butonic** [comment]
indeed. closing as duplicate.
