### ISSUE TITLE
Uploaded ODT or PDF files, when downloaded are corrupt if I use HHVM

### ISSUE THREAD

**Issue by castarco** [owncloud/core#14723]
Related with #10837 .

Assuming I'm running OwnCloud on HHVM, when I upload ODT or PDF files, then I obtain corrupt files if I try to download them.

If I do the same with .txt files I don't experience the same problem...

The fatals, errors & warnings log:
http://pastebin.com/9u2SVg8R

you can use http://jsonlint.com/ to beautify it.

EDIT:

I'm using OwnCloud 8.0.9 , on Ubuntu 14.04 , with HHVM 3.5. I'm also using SSL (and forcing it).

I've tried with the files encryption app and without it, the problem is related with the files encryption app. The uploaded file weights 125K, the downloaded file weights 19K. If I download multiple times the same file, the downloaded files are different, they have the same size, but different byte sequences.

**Comment by DeepDiver1975** [comment]
> I've tried with the files encryption app and without it, the problem is related with the files encryption app.

Encryption is know to not *yet* work with HHVM - THX

**Comment by DeepDiver1975** [comment]
We will not fix encryption for OC8 on hhvm - let's see what 8.1 brings to ...
