### ISSUE TITLE
Let us create new thumbnails without having to create a new object

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#14739]
### Situation
It doesn't seem to be possible currently to generate more than one thumbnail per object. Once we get a valid preview, `$object->getPreview()` will always return the same preview and we have to create a new object to get a thumbnail of a different size.

### Proposal
It would be nice if we could simply do a `setMaxX()` to set the preview to null, followed by a `getPreview()` to generate a new one.

### Use case
* A cron could want to generate thumbnails of 3 different sizes
* A media app could need a 2nd preview if what it gets doesn't meet its requirements

@georgehrke

**Comment by georgehrke** [comment]
I like the idea!

**Comment by DeepDiver1975** [comment]
@nickvergessen handled in #14857 ???

**Comment by nickvergessen** [comment]
No, I just changed how the registration of the preview providers is done, not how the preview object that is returned works
