### ISSUE TITLE
PHP CLI cron job receiving SIGKILL due to OOM

### ISSUE THREAD

**Issue by dutchgecko** [owncloud/core#14745]
Since upgrading to owncloud 8 my cron jobs would mysteriously stop running, leaving behind a cron.lock file and preventing the cron job from running in the future. Today I ran the cron job manually from the command line with `php -f cron.php` and returned later to find the job had been aborted by a SIGKILL (leaving behind a cron.lock file as usual).

### Steps to reproduce
1. `php -f cron.php`

### Expected behaviour
Cron job completes

### Actual behaviour
Cron job is aborted by a SIGKILL

### Server configuration
**Operating system**:
`Linux alchemist 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u2 x86_64 GNU/Linux`

**Web server:**
`nginx version: nginx/1.2.1`

**Database:**
`Server version: 10.0.17-MariaDB-1~wheezy-log mariadb.org binary distribution`

**PHP version:**
PHP 5.4.36-0+deb7u3 (cli)
PHP 5.4.36-0+deb7u3 (fpm-fcgi)

**ownCloud version:** (see ownCloud admin page)
ownCloud 8.0.1 (stable)

**Updated from an older ownCloud or fresh install:**
Upgraded from 6 through 8

**List of activated apps:**
- Activity
- Calendar
- Contacts
- Deleted files
- External storage support
- First run wizard
- Markdown editor
- Mozilla sync
- News
- PDF Viewer
- Pictures
- Share files
- Text editor
- Updater
- Versions
- Video viewer

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'datadirectory' => '/media/raid/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.1.1',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'xxx',
  'installed' => true,
  'maxZipInputSize' => 2147483648,
  'allowZipDownload' => true,
  'overwritewebroot' => '/cloud',
  'loglevel' => '2',
  'theme' => '',
  'maintenance' => false,
  'forcessl' => true,
  'trusted_domains' =>
  array (
    0 => 'thuis.parseq.co.uk',
  ),
  'secret' => 'xxx',
  'overwrite.cli.url' => 'https://thuis.parseq.co.uk/cloud',
);

```

**Are you using external storage, if yes which one:** 
- local

**Are you using encryption:** 
- no

**Are you using an external user-backend, if yes which one:** 
- no

#### Web server error log
nothing suspicious

#### ownCloud log (data/owncloud.log)
```
tail owncloud.log
{"reqId":"a14e68e3a2773cea1824e5e4ff909c3e","remoteAddr":"82.161.237.125","app":"news","message":"Configuration value \"simplePieCacheDuration\" does not exist. Ignored value.","level":2,"time":"2015-03-07T17:29:55+00:00"}
{"reqId":"806f79cd46bf00f4a0acf60877f63798","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/var\/www\/owncloud\/apps\/calendar\/appinfo\/app.php#41","level":3,"time":"2015-03-07T17:30:04+00:00"}
{"reqId":"37010b32157f836bb9a08fc76a604ac2","remoteAddr":"82.161.237.125","app":"news","message":"Configuration value \"simplePieCacheDuration\" does not exist. Ignored value.","level":2,"time":"2015-03-07T17:32:46+00:00"}
{"reqId":"3e709f523aa9458bd2a0bd7375aa2586","remoteAddr":"82.161.237.125","app":"news","message":"Configuration value \"simplePieCacheDuration\" does not exist. Ignored value.","level":2,"time":"2015-03-07T17:32:47+00:00"}
{"reqId":"5a388e3ad0c2bc7829115a9a59277f58","remoteAddr":"82.161.237.125","app":"news","message":"Configuration value \"simplePieCacheDuration\" does not exist. Ignored value.","level":2,"time":"2015-03-07T17:32:48+00:00"}
{"reqId":"381bb70780439aba43d721ca89f836ea","remoteAddr":"82.161.237.125","app":"news","message":"Configuration value \"simplePieCacheDuration\" does not exist. Ignored value.","level":2,"time":"2015-03-07T17:32:48+00:00"}
{"reqId":"e0399888ae8d0818fe6c3b63117392d0","remoteAddr":"82.161.237.125","app":"news","message":"Configuration value \"simplePieCacheDuration\" does not exist. Ignored value.","level":2,"time":"2015-03-07T17:32:48+00:00"}
{"reqId":"d869546ecaa94c7a8960b4c41cec4955","remoteAddr":"82.161.237.125","app":"news","message":"Configuration value \"simplePieCacheDuration\" does not exist. Ignored value.","level":2,"time":"2015-03-07T17:32:49+00:00"}
{"reqId":"0799a6d58da1b8b2e8e48126d8ebe063","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/var\/www\/owncloud\/apps\/calendar\/appinfo\/app.php#41","level":3,"time":"2015-03-07T17:45:04+00:00"}
{"reqId":"c1fb61a69115c7de385fbc88ce8afd1f","remoteAddr":"82.161.237.125","app":"news","message":"Configuration value \"simplePieCacheDuration\" does not exist. Ignored value.","level":2,"time":"2015-03-07T17:46:12+00:00"}
```

edit: cron.log contents (last 3 lines)
```
PHP Notice: A feed could not be found at xxx. A feed with an invalid mime type may fall victim to this error, or SimplePie was unable to auto-discover it.. Use force_feed() if you are certain this URL is a real feed. in /var/www/owncloud/apps/news/3rdparty/simplepie/library/SimplePie.php on line 1520
Killed
Killed
```

edit2: further investigation has revealed that the process was killed by the kernel due to low memory. I've read that this can happen if full text search is enabled, however it isn't on my machine. Any ideas on what is consuming so much memory during cron update?

```
free -m
             total       used       free     shared    buffers     cached
Mem:          3900       3742        157          0         13       2011
-/+ buffers/cache:       1718       2181
Swap:         1898        947        950
```

```
sudo tail -n 2 kern.log
Mar  7 18:08:07 alchemist kernel: [494086.141504] Out of memory: Kill process 28132 (php) score 551 or sacrifice child
Mar  7 18:08:07 alchemist kernel: [494086.141669] Killed process 28132 (php) total-vm:3524692kB, anon-rss:2543012kB, file-rss:180kB
```

**Comment by RealRancor** [comment]
Hi,

that could be caused by the news app which is also providing an alternative update script:

https://github.com/owncloud/news#performance-notices

**Comment by dutchgecko** [comment]
I installed the custom script and disabled News updates for the cron job. The cron job now finishes in about 2 seconds. Why is the news app chewing through approximately 2GB of memory during the cron update?

**Comment by RealRancor** [comment]
Hi,

some basic infos are available here: https://github.com/owncloud/news/blob/master/bin/updater/README.rst

Everything else is probably something should clarify with the devs of the News app.
