### ISSUE TITLE
Use DNS SRV-RRs to detect Federated cloud

### ISSUE THREAD

**Issue by c4539** [owncloud/core#14746]
Would be great to look up for an SRV record in DNS while searching for a foreign user.

I. e.: I like to share a file/folder with user@example.com, but his/her owncloud is running on cloud.example.com. At the moment, I have to share with user@cloud.example.com, but if OC is looking for a SRV record that redirects service "owncloud" on example.com to cloud.example.com, I can share with user@example.com.
This would be very helpfull in some cases.

**Comment by Xenopathic** [comment]
A possible implementation would be like the well known DNS SRV records for CalDAV or CardDAV: http://sabre.io/dav/service-discovery/. `_owncloud._tcp.domain.tld`, for example. Or while we are at it, well known HTTP redirects (again, like CalDAV or CardDAV), so `https://domain.tld/.well-known/owncloud`

**Comment by PVince81** [comment]
I believe @schiesbn mentionned something similar to me recently.

**Comment by plinss** [comment]
Note that you also want to support a secure version of the service, i.e.: `_ownclouds._tcp.domain.tld`

**Comment by boydhako** [comment]
Using SRV records is client side routine. So, all the clients would have to be updated to look for SRV records to populate the appropriate fields when adding a server. Using SRV records should be used to ease configuration if the instance is operating on a non-standard port. Querying for users should be done via some sort of JSON API with optional mutual trusts between the two systems. CalDAV and CardDav could be in an SRV record as an "extension" of a WebDAV SRV record. Check the URL below on how to add CalDAV as an SRV record. 

https://tools.ietf.org/html/rfc6764
