### ISSUE TITLE
Call to undefined method Redis::connect() 

### ISSUE THREAD

**Issue by stephenreda** [owncloud/core#14744]
### Steps to reproduce
1. Install latest version using owncloud-setup.php
2. Setup login + configure storage (either sqlite or mysql)

### Expected behaviour
Owncloud should work

### Actual behaviour
Nothing is loaded. Blank page. The logs report that a call to the method Redis::connect() is undefined
 
### Server configuration
**Operating system**:
ubuntu version ? (shared hosting)
**Web server:**
apache 2.4
**Database:**
MySQL 5.1.73 
**PHP version:**
php 5.5
**ownCloud version:** (see ownCloud admin page)
Latest version through webinstaller (owncloud not showb)
**List of activated apps:**
None

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '#####',
  'passwordsalt' => '#####',
  'secret' => '#####',
  'trusted_domains' => 
  array (
    0 => '#####.be',
  ),
  'datadirectory' => '#####/www/oc/data',
  'overwrite.cli.url' => 'https://#####.be/oc',
  'dbtype' => 'mysql',
  'version' => '8.0.0.7',
  'dbname' => '#####',
  'dbhost' => '#####',
  'dbtableprefix' => 'oc_',
  'dbuser' => '#####',
  'dbpassword' => '#####',
  'installed' => true,
);
```
### Client configuration
**Browser:**
Chromium/40.0.2214.111
**Operating system:**
Linux x86_64
#### Web server error log
```
No access
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"#####","remoteAddr":"#####","app":"PHP","message":"touch(): Unable to create file \/#####\/www\/oc\/data\/owncloud.log because No such file or directory at \/#####\/www\/oc\/lib\/private\/log\/owncloud.php#48","level":3,"time":"2015-03-07T15:45:17+00:00"}
{"reqId":"#####","remoteAddr":"#####","app":"PHP","message":"Call to undefined method Redis::connect() at \/#####\/www\/oc\/lib\/private\/memcache\/redis.php#39","level":3,"time":"2015-03-07T15:46:02+00:00"}
```

#### Browser log
```
Remote Address:[############]:443
Request URL:https://########.be/oc/
Request Method:GET
Status Code:500 Internal Server Error
```

**Comment by RealRancor** [comment]
Hi,

seems this default behaviour to use redis will be changed in 8.1: https://github.com/owncloud/core/issues/14742

In the mean time you could install php-xcache or php-acp(u) to solve this.

**Comment by stephenreda** [comment]
Thanx @RealRancor , but this is a hosted webserver so I fear I will have to be a bit patient :(

**Comment by Xenopathic** [comment]
Actually, this is a more serious issue. Redis would only be chosen if `isAvailable()` returns true, which checks if the extension is loaded. Then the memcache itself is created, constructing a Redis object then calling `connect()` on it. Here, the extension is loaded, and the Redis object gets constructed successfully, but there is no `connect()` method, which indicates to me that the API might have changed.

**Comment by RealRancor** [comment]
Ah, sure. That makes sense.

**Comment by stephenreda** [comment]
okay thx guys @Xenopathic @RealRancor 
Any idea on the timeline, expected release date of 8.1?

**Comment by RealRancor** [comment]
This is probably something which even should be fixed in OC 8.0.x.

But the release schedules for upcoming versions are described here:

https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule

**Comment by 5YHgB** [comment]
please fix

**Comment by PVince81** [comment]
@icewind1991 @Xenopathic wasn't this fixed recently ?

**Comment by Xenopathic** [comment]
@PVince81 This is no longer an issue with 8.1, since the admin must explicitly set the memcache backend to use.

**Comment by PVince81** [comment]
Please try again with 8.1.3 or 8.2RC1.
If the problem persists, feel free to reopen.
