### ISSUE TITLE
upgrading owncloud is a nightmare

### ISSUE THREAD

**Issue by bahsoft** [owncloud/core#14749]
I had installed Server 7.0.2 on Windows XAMPP 1.8.2 + Bitnami ownCloud Module.
Beside the "conflict file creation while only one side was changed" problem it worked.
Then I moved one folder in explorer within the sync folder structure.
The ownCloud 1.7.1 client log said something like "moving folder..." FINE!
But then I wondered, that my .py files (edited some hours ago) are GONE and only 3 .txt files are there. 
FUCK! IT!

I could recover the files from the ownCloud Server folder.
In the owncloud webpage this subfolder was 2x visible in the new location and 0 in the old location.
I deleted the 2 folder in the webpage and in the file system.
Then I wanted to recreate it and copied the old files into it.
It did not sync anymore. :-( :-1: 

Then I tried to update the server to 8.0 because... maybe... it's better?
I uninstalled the old bitnami app and installed the new one.
I couldn't find the "app-password". In the setup dialogs I entered the old password for the web user but later the client was not able to connect.
The server was installed fine, only the port 80 vhost config file was wrong, because on port 80 is another webserver running.
I commented the lines in the conf-file.
The apache was running and I logged in to ownCloud-website and it was empty, no files.

Thats OK I thought, lets start the client so it can upload the files again.
But the client could not log in and I could not just edit the password in the config files...
In the client, I clicked on something like "edit account"...
server address is right...
I entered the right user name and password... login works...
"sync everything from server" WHAT? DAMN NO, I WANT TO UPLOAD TO THE FUCKING SERVER! HOW?

WELL TO MAKE IT SHORT: IN THE OWNCLOUD CLIENT I'M ABLE TO CONFIGURE M_U_L_T_I_P_L_E SYNC FOLDERS
BUT WHY THE FUCKING HELL I'M NOT ABLE TO UPDATE THE FUCKING USER ACCOUNT WITHOUT DESTROYING ALL FUCKING SYNC FOLDERS?

I then deleted the 3 sync folders and created them new. Imagine if someone has like 15 folders!
Guess what? The ownCloud server was unable to upload the files because of error (clientlog)
"Could not rename part file to final file". 
In the server folder there are my files with 0 bytes + an "part" file with content. WHY THE FUCK?
AND THEN IT WAS MAGICALLY ABLE TO DOWNLOAD THE FUCKING 0 BYTE FILES AND 
O_V_E_R_W_R_I_T_E MY LOCAL GOOD FILES.
FUCK!! FUCK!! FUCK!! FUCK!! FUCK!! FUCK!! FUCK!! FUCK!! FUCK!! FUCK!! FuuUUuuUuuUUUCK!! 

Conclusion:
UPGRADING OWNCLOUD IS A NIGHTMARE!
FUCK! IT!

(all swear words are only provided to express the importance and severity of this problem and my feelings about this)
:-(

**Comment by LukasReschke** [comment]
I did only skim your issue but from your report this seems like a client bug? – Can you please:

1. Reopen this at https://github.com/owncloud/client if this affects the client
2. Use the issue template (see https://github.com/owncloud/core/blob/master/CONTRIBUTING.md and https://github.com/owncloud/client/blob/master/CONTRIBUTING.md)

We cannot really help you without these information and we need it in a standardized format so that developers can easily debug, find and cross-reference this issue. Thanks.

**Comment by DeepDiver1975** [comment]
@bahsoft while I understand your frustration I have to ask you to be polite - https://owncloud.org/community/code-of-conduct/

**Comment by DeepDiver1975** [comment]
> I had installed Server 7.0.2 on Windows XAMPP 1.8.2 + Bitnami ownCloud Module.

don't use Windows please - Linux server is the way to go.
