### ISSUE TITLE
Implicit usage of redis server

### ISSUE THREAD

**Issue by peku33** [owncloud/core#14742]
Hi.

I spent a few hours trying to make my owncloud installtion work.

After 'Setup Wizard' I was redirected to index.php and received Internal Server Error.
My error_log is set properly, but nothing was written to it.

After some time I decided to run console.php from cli. I got:

    An unhandled exception has been thrown:
    exception 'RedisException' with message 'Redis server went away' in /home/*/public_html/lib/private/memcache/redis.php:68
    Stack trace:

I don't want owncloud to use redis without my knowledge, it has never asked me for permisson and/or data.
This error appeared beacuse my redis server is listening on local unix socket, not default '127.0.0.1'.

Please disable redis by default, let users decide whether they want (and how) to allow owncloud to use redis.

**Comment by RealRancor** [comment]
Hi,

seems the description here could explain this behaviour:

https://github.com/owncloud/core/blob/v8.0.0/config/config.sample.php#L790

**Comment by Xenopathic** [comment]
This behaviour is changing in 8.1: https://github.com/owncloud/core/wiki/ownCloud-8.1-Features#deployment

**Comment by 5YHgB** [comment]
please fix

**Comment by seidelh** [comment]
is already fixed in 8.0.4 -- needs manual editing config.php add add these content:
'host' => '/home/'.$_SERVER['USER'].'/.redissock', // can also be an other unix domain socket: '/tmp/redis.sock'
'port' => 0,
'timeout' => 0.0
be sure it's inside your leading array( and trailing ); ... be also sure por is 0 on a unix socket ... and be sure u know and replace where is your redissocket in the unix system
Have fun =)

**Comment by RealRancor** [comment]
Hi,

this is possible since older versions:

https://github.com/owncloud/core/blob/v8.0.0/config/config.sample.php#L793

The issue here is about the problem that oC is using redis without a configuration and without the knowledge of the admin.

**Comment by HLFH** [comment]
Redis Server Went Away issue solved on OC 8.2 on my side. https://github.com/owncloud/contacts/issues/1082#issuecomment-151638547
