### ISSUE TITLE
Webinstallation does not check dependency php-curl

### ISSUE THREAD

**Issue by sedrubal** [owncloud/core#14761]
### Steps to reproduce
1. Don't enable / install `php5-curl`(on `Ubuntu`: `sudo apt-get remove php5-curl` or something like this)
2. Use the [webinstaller](https://owncloud.org/install/#instructions-web) (setup-owncloud.php)
3. Click through the installation instructions

### Expected behaviour
The installer should realize, that php-curl isn't installed or enabled.

### Actual behaviour
The installation breaks; it does not install owncloud and there are many php warnings, but the installer exits with `success` message.

### Server configuration
**Operating system**: 

`Ubuntu 14.04`

**Web server:** 

`Apache 2.4.7-1ubuntu4.1`

**Database:** 

`MySQL`

**PHP version:** 

`PHP 5.5.9-1ubuntu4.6 (cli) (built: Feb 13 2015 19:17:11)`

**ownCloud version:** (see ownCloud admin page) 

*I think this will be owncloud 8 if it is installed ;)*

**Updated from an older ownCloud or fresh install:** 

*fresh install*

**List of activated apps:**

*only standard apps*

**The content of config/config.php:**

```
```

**Are you using external storage, if yes which one:** 

`-`

**Are you using encryption:**

`no`

**Are you using an external user-backend, if yes which one:** 

`no`

### Client configuration
**Browser:** 

`firefox 36`

**Operating system:**

`Ubuntu 14.04`

#### Web server error log
```
[Mon Mar 09 15:12:28.617922 2015] [:error] [pid 22796] [client 127.0.0.1:59160] PHP Fatal error:  Call to undefined function curl_init() in /var/www/owncloud/setup-owncloud.php on line 189, referer: http://localhost/setup-owncloud.php?step=1
[Mon Mar 09 15:12:28.617956 2015] [:error] [pid 22796] [client 127.0.0.1:59160] PHP Stack trace:, referer: http://localhost/setup-owncloud.php?step=1
[Mon Mar 09 15:12:28.617965 2015] [:error] [pid 22796] [client 127.0.0.1:59160] PHP   1. {main}() /var/www/owncloud/setup-owncloud.php:0, referer: http://localhost/setup-owncloud.php?step=1
[Mon Mar 09 15:12:28.617972 2015] [:error] [pid 22796] [client 127.0.0.1:59160] PHP   2. oc_setup::showinstall() /var/www/owncloud/setup-owncloud.php:348, referer: http://localhost/setup-owncloud.php?step=1
[Mon Mar 09 15:12:28.617978 2015] [:error] [pid 22796] [client 127.0.0.1:59160] PHP   3. oc_setup::install() /var/www/owncloud/setup-owncloud.php:313, referer: http://localhost/setup-owncloud.php?step=1
[Mon Mar 09 15:12:28.617983 2015] [:error] [pid 22796] [client 127.0.0.1:59160] PHP   4. oc_setup::getfile() /var/www/owncloud/setup-owncloud.php:145, referer: http://localhost/setup-owncloud.php?step=1
[Mon Mar 09 15:14:14.007241 2015] [:error] [pid 22797] [client 127.0.0.1:59174] PHP Fatal error:  Call to undefined function curl_init() in /var/www/owncloud/index.php on line 3
[Mon Mar 09 15:14:14.007273 2015] [:error] [pid 22797] [client 127.0.0.1:59174] PHP Stack trace:
[Mon Mar 09 15:14:14.007288 2015] [:error] [pid 22797] [client 127.0.0.1:59174] PHP   1. {main}() /var/www/owncloud/index.php:0
```

#### ownCloud log (data/owncloud.log)
```
```

**Comment by DeepDiver1975** [comment]
@LukasReschke :speak_no_evil:

**Comment by LukasReschke** [comment]
I knew that having files with my name in the copyright header is a bad idea … ;-)

**Comment by LukasReschke** [comment]
Patch is at https://github.com/owncloud/administration/pull/33

**Comment by sedrubal** [comment]
:+1: I like this one click installer `*.*`

**Comment by LukasReschke** [comment]
Let's keep this open until the patch is live :)

**Comment by karlitschek** [comment]
done

**Comment by LukasReschke** [comment]
Thanks :smiley:
