### ISSUE TITLE
Home folder variations to investigate / use getHome() instead of root view

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#14770]
Recently I heard that the LDAP admin settings make it possible to specify the format of the name of the home folder.

However there are many places in the code that assume that the home folder is always in the format "$datadir/$userId". This is mostly when a root view is used, then it concatenated the user name instead of using `getHome()`.

We need to check whether these parts are compatible. I suspect this is likely to break...

@icewind1991 @MorrisJobke @schiesbn @blizzz

**Comment by blizzz** [comment]
In setupFS the user folder as returned by getHome by the corresponding backend is mounted as $datadir/$userId so that subsequent views etc. to $datadir/$userId resolve just fine.

**Comment by blizzz** [comment]
Also, getHome() is never expected to be called from anywhere else than setupFS. (I have gotten it wrong back then when this stuff was introduced and also thought this way. There were ways to circumvent/directly access files, which broke.)

**Comment by PVince81** [comment]
So if I understand well, this means that if someone creates a root view and forgets to do setupFS for a given user, then the home will not be mounted properly.

So let's say setupFS('uuid') would mount the uuid folder onto "$datadir/userid". If someone uses a root view but forgets to call setupFS('uuid'), then the view will be looking for a real folder "$datadir/userid" instead of the mounted one.
This sounds very similar to what I observed with  @Elethiomel  on IRC yesterday.

While looking at the encryption migration code, I noticed that setupFS() only worked for the first user, because subsequent calls would have `$fsExists` already true. Will raise separately.

**Comment by blizzz** [comment]
setupFS should be called as early as possible of course, and I am not aware of any issues… which does not mean that there are none or were re-introduced.

> While looking at the encryption migration code, I noticed that setupFS() only worked for the first user, because subsequent calls would have $fsExists already true. Will raise separately.

In that case we indeed need to tearDownFS() it before setting it up for another user. It resets the fsSetup marker.

**Comment by PVince81** [comment]
Raised ticket for missing tearDownFS() here: https://github.com/owncloud/core/issues/14775

**Comment by blizzz** [comment]
tearDown is implemented, we can close. Reopen, if not.
