### ISSUE TITLE
File uploads in an encrypted environment are terminated shortly before upload completion.

### ISSUE THREAD

**Issue by hellmachine2000** [owncloud/core#14777]
### Steps to reproduce
1. Upload file (1,2gb .mp4 file)
2. Upload progression bar starts, process is fine
3. Shortly before upload completion upload is terminated with an internal server error 

### Expected behaviour
Completed upload, encrypted file

### Actual behaviour
After Page reload the .mp4 file is listed, but with size "0kB". When connecting via FTP the file size of the mp4 is right, but the downloaded mp4 can't be played. The cache directory is full of chucks with the name of the file. Without encryption the upload works fine.

### Server configuration
**Operating system**: Linux 3.0, shared Hosting by 1und1

**Web server:** Apache
**Database:** SQlite
**PHP version:** 5.5.20
**ownCloud version:** 8.0

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:** Encryption, Activity, Calendar, Contacts, First Run, PDF, Pictures, Share, Text Editor

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => '',
  ),
  'datadirectory' => '',
  'overwrite.cli.url' => '',
  'dbtype' => 'sqlite3',
  'version' => '8.0.0.7',
  'installed' => true,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
);

**Are you using external storage:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Safari, Firefox

**Operating system:** OS X 10.10

#### ownCloud log (data/owncloud.log)
[{"reqId":"fbb0132541375224125a16ff4a28a225","remoteAddr":"IPADRESS","app":"core","message":"Invalid OCS content returned for app files_encryption","level":4,"time":"2015-03-09T11:50:34+00:00"},{"reqId":"81d9926c6e29f56e7f090de0c29e4a61","remoteAddr":"IPADRESS","app":"PHP","message":"touch(): Unable to create file MYPATH/owncloud.log because No such file or directory at MYPATH\/owncloud\/lib\/private\/log\/owncloud.php#48","level":3,"time":"2015-03-09T11:47:37+00:00"}]

**Comment by karlitschek** [comment]
Is this the only entry in the owncloud.log?

**Comment by hellmachine2000** [comment]
I updated the log info. MYPATH replaced the original paths.

**Comment by hellmachine2000** [comment]
This problem also happened in 7.x. I hoped a fresh install with 8.x would finally fix this :-)

**Comment by hellmachine2000** [comment]
Another finding: It works fine with files below 1GB, bigger files will not work.

**Comment by RealRancor** [comment]
@hellmachine2000
Any chances that you can get access to your webserver / PHP error log? An internal error should be definitely logged somewhere additional to the posted logs.

**Comment by hellmachine2000** [comment]
right now i have no idea how to get the php logs :-(

**Comment by RealRancor** [comment]
@hellmachine2000 
Using your favorite search engine should lead you to this informations. A starting point could be: https://forum.owncloud.org/viewtopic.php?f=17&t=7330

**Comment by hellmachine2000** [comment]
@RealRancor 
yep, searched already, but my hosting provider only let me alter the following php settings:
register_globals, allow_url_fopen, display_errors, disable_functions, safe_mode, memory_limit, post_max_size, upload_max_filesize, max_execution_time, zlib.output_compression, magic_quotes_gpc, session.auto_start, max_input_vars, max_input_time

http://hilfe-center.1und1.de/skript--und-programmiersprachen-c82634/php-c82686/bedienung-c82739/welche-php-einstellungen-kann-ich-aendern-a791899.html

**Comment by RealRancor** [comment]
@hellmachine2000 
Unfortunately its probably not really possible to guess whats wrong here without the related log entry to the "internal server error". Maybe you could contact the support of 1und1 to get them?

Two alternatives as you're running sqlite:

1. As you're probably don't have access to a command line: Do a fresh installation with a MySQL database
2. Wait until OC 8.0.3 is released which could fix some problems with sqlite and encryption according to https://github.com/owncloud/core/issues/12725#issuecomment-78052430

**Comment by PVince81** [comment]
Please try again with 8.0.5 and reopen if you are still having issues. Thanks.
