### ISSUE TITLE
LDAP uuid and name mappings problem in migration to 8.0.1RC1. Failed (and very slow) migration

### ISSUE THREAD

**Issue by Elethiomel** [owncloud/core#14774]
This bug was previously mentioned at https://github.com/owncloud/core/issues/14655#issuecomment-77943305 but I was told to open a new issue by @nickvergessen 

Migrating from 7.0.4 to 8.0/8.0.1RC1 failed on Debian Wheezy. I upgraded with debs from supplied repository and then used the recommended 8.0.1RC1

After the migration oc_storages contained a mix of home::uuid and home::userid but on disk it was all $datadir/username

occ encryption:migrate failed (completed in seconds with no warnings). Encryption keys were in all the wrong places

After doing some debugging work with @PVince81 I found that manually creating the symlink  uuid->username by looking up the ldap mappings table allowed the migration to proceed.

Another problem now is that the migration is taking forever. It's been running for over 12 hours and only about 20 users (10%) have been migrated. Why is re-encryption necessary? The occ migration process is only taking up 20% single CPU and 10% RAM. MySQL is busy with about 10% on 2 CPUs 3% RAM

Any ideas on how to speed it up? This is an 8 core machine with 8GB of RAM

**Comment by PVince81** [comment]
Ah! you raised it here. I raised another ticket that might or might not be related to what you saw yesterday: https://github.com/owncloud/core/issues/14775

To encryption migration speed has been fixed in the upcoming 8.0.2.

**Comment by PVince81** [comment]
Sorry, wrong. It will be in 8.0.3.
The speed issue is fixed here: https://github.com/owncloud/core/pull/14669

**Comment by PVince81** [comment]
I guess your original bug might be reproducible by going to the LDAP settings and changing the format of the home folder, and then doing the upgrade from OC 7 to OC 8.

**Comment by blizzz** [comment]
I assume it is fixed as the mentioned PR was merged and no further update was posted.
