### ISSUE TITLE
Encryption migration setupFS doesn't work properly

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#14775]
### Steps
1. Setup LDAP on OC 7.0.4
2. Enable encryption
3. Login with some users, upload files
4. Upgrade code to 8.0.0
5. Put breakpoint on setupFS() here: https://github.com/owncloud/core/blob/master/apps/files_encryption/lib/migration.php#L87
6. Run the upgrade and step into setupFS()

### Expected result
Filesystem is setup properly for every user

### Actual result
Filesystem is only setup for the first user, because in https://github.com/owncloud/core/blob/master/lib/private/util.php#L67 we have `$fsSetup` which is always true.

The migration code is missing a `tearDown()` call to make sure we reset that.

Also that code uses a root view and from my understanding from here https://github.com/owncloud/core/issues/14770#issuecomment-77954925 is that regardless of the user home format, it is always mounted onto "$datadir/$user". However in this specific case, since setupFS is not doing anything, it will never properly mount the user's home. This might work for regular users but could fail with LDAP as it did with @Elethiomel.

@schiesbn @icewind1991

**Comment by PVince81** [comment]
@blizzz can you tell me the steps to make the LDAP uuid different to the userid ? Goal is to have "home::uuid" that is mounted onto "$datadir/$userid". That could help reproduce @Elethiomel's encryption migration issues with LDAP in regard to this bug ticket.

**Comment by blizzz** [comment]
@PVince81 configure User Home Folder Naming Rule (https://doc.owncloud.org/server/8.0/admin_manual/configuration/user_auth_ldap.html#special-attributes). Use uid or cn against OpenLDAP.

**Comment by DeepDiver1975** [comment]
> The migration code is missing a tearDown() call to make sure we reset that.

```php
		\OC_Util::tearDownFS();
