### ISSUE TITLE
Downloading a shared file cause "failed to delete buffer"

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#14786]
1. Share the welcome.txt via link
2. Go to that link
3. click the download button below the preview

{"reqId":"rjPZxZRzBSaJuKBNJsa\/","remoteAddr":"127.0.0.1","app":"PHP","message":"ob_end_clean(): failed to delete buffer. No buffer to delete at \/home\/mjob\/Projekte\/owncloud\/master\/lib\/private\/files\/view.php#317","level":0,"time":"2015-03-11T08:31:10+00:00","method":"GET","url":"\/master\/index.php\/s\/PMDmuh1azIaUJBg\/download"}

cc @icewind1991

**Comment by oparoz** [comment]
Are you sure it's not because you've cancelled the download?

**Comment by MorrisJobke** [comment]
Let me retry :)

**Comment by MorrisJobke** [comment]
I can't reproduce anymore :(

Maybe just a problem, because unit tests run before that.

**Comment by oparoz** [comment]
I've definitely seen this message in the logs on 8.0, but I assumed it was generated when I cancelled a test download.
Maybe it's not reproducible on 8.0.2 :)
