### ISSUE TITLE
Owncloud Calendar Feature Request

### ISSUE THREAD

**Issue by waleedkh** [owncloud/core#14784]
Hi there,

Would it be possible to integrate the "private appointment" feature in Outlook so that it syncs to Owncloud and across all devices. 
This is a very useful feature when sharing calendars as at times users would prefer to keep certain appointments private 
Thanks

**Comment by nickvergessen** [comment]
ownCloud itself has no calendar and will never get one. There is however a calendar app which might help you: https://github.com/owncloud/calendar
