### ISSUE TITLE
File API for copying/moving files/folders

### ISSUE THREAD

**Issue by eotryx** [owncloud/core#14781]
Hello,

as I started to redevelop my app (files_mv) for OC8 with the app framework, I now stumbled over the files-api which I don't get to work.
The full code can be found here: https://github.com/eotryx/oc_files_mv/tree/b300015ad96ca9a5fa9ef6ac9eeae0dc19b82e5e

The API-Documentation states, that the folder object has a move and copy instruction (http://api.owncloud.org/classes/OCP.Files.Folder.html#move).

The code below is what I made of the API description and doesn't work.
The files app(ajax/move.php) uses the filesystem(\OC\Files\Filesystem) api and seems to work fine with it. After doing the same, it works for me well, too.

So my question, what is the right way within the OC core/libs to move and copy files/directories, and why does this approach not work? And which of the two(or more unknown APIs) probably continues to live in OC9?

-----------------------------
// extracted from controller/movecontroller.php#index-function within the foreach loop, reduced to the move-method
-----------------------------
```php
$to = $dest.$file; // string(16) "/weg/welcome.txt"
$fromPath = $srcDir.$file; // string(12) "/welcome.txt"
$from = $this->storage->get($fromPath); // $this->storage = $ServerContainer->getUserFolder($UserId);
        // $from is a folder object
$from->move($to); // here it crashes
```
-----------------------------
Results in the following output:

```html
<h2><strong>Technical details</strong></h2>
    <ul>
        <li>Remote Address: 127.0.0.1</li>
        <li>Request ID: lKVEgjk8A2V+eyFIWL4a</li>
                    <li>Code: 0</li>
            <li>Message: </li>
            <li>File: /var/www/oc/ocdev/core/lib/private/files/node/file.php</li>
            <li>Line: 139</li>
            </ul>

            <br />
        <h2><strong>Trace</strong></h2>
        <pre>#0 /var/www/oc/ocdev/core/apps/files_mv/controller/movecontroller.php(74): OC\Files\Node\File-&gt;move(&#039;/weg/welcome.tx...&#039;)
#1 [internal function]: OCA\Files_Mv\Controller\MoveController-&gt;index(&#039;/&#039;, &#039;welcome.txt&#039;, &#039;/weg&#039;, false)
#2 /var/www/oc/ocdev/core/lib/private/appframework/http/dispatcher.php(158): call_user_func_array(Array, Array)
#3 /var/www/oc/ocdev/core/lib/private/appframework/http/dispatcher.php(86): OC\AppFramework\Http\Dispatcher-&gt;executeController(Object(OCA\Files_Mv\Controller\MoveController), &#039;index&#039;)
#4 /var/www/oc/ocdev/core/lib/private/appframework/app.php(97): OC\AppFramework\Http\Dispatcher-&gt;dispatch(Object(OCA\Files_Mv\Controller\MoveController), &#039;index&#039;)
#5 /var/www/oc/ocdev/core/lib/private/appframework/routing/routeactionhandler.php(44): OC\AppFramework\App::main(&#039;MoveController&#039;, &#039;index&#039;, Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#6 [internal function]: OC\AppFramework\routing\RouteActionHandler-&gt;__invoke(Array)
#7 /var/www/oc/ocdev/core/lib/private/route/router.php(251): call_user_func(Object(OC\AppFramework\routing\RouteActionHandler), Array)
#8 /var/www/oc/ocdev/core/lib/base.php(796): OC\Route\Router-&gt;match(&#039;/apps/files_mv/...&#039;)
#9 /var/www/oc/ocdev/core/index.php(36): OC::handleRequest()
#10 {main}</pre>
```
-----------------------------

**Comment by PVince81** [comment]
@icewind1991 some bug in the node API ?

**Comment by icewind1991** [comment]
With the move and copy operation you need to pass absolute path.

Try `$from->move($storage->getFullPath($to))`

**Comment by eotryx** [comment]
Okay, thanks. That works.
