### ISSUE TITLE
Reduce complexity in share dropdown - remove fold up

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#14787]
Remove the permission fold up, because it only has one single entry "Change" (Ändern) and it is already the same as the outer "Can edit" (kann bearbeiten).

![share-dropdown](https://cloud.githubusercontent.com/assets/245432/6592735/d1f1bdd6-c7d1-11e4-94c6-451512d0a969.png)

opinions @owncloud/designers

**Comment by MorrisJobke** [comment]
Got it. This is just the case for files. For folders there are more options.

But I think that we can savely remove this fold up for files. Maybe something we should address  together with #5873

**Comment by MorrisJobke** [comment]
cc @rullzer

**Comment by PVince81** [comment]
At this stage I wouldn't bother, better focus on the new share dialog instead.

**Comment by enoch85** [comment]
Looks good to me.

**Comment by DeepDiver1975** [comment]
> At this stage I wouldn't bother, better focus on the new share dialog instead.

indeed -> close?

**Comment by jancborchardt** [comment]
Ok, so then we’ll work on the new sharing dialog in Nürnberg I suppose?

**Comment by MorrisJobke** [comment]
@jancborchardt Sure :) Can you add it to the list?
