### ISSUE TITLE
Cannot redeclare class OC\\Security\\SecureRandom on updating from 8.0 to 8.0.2

### ISSUE THREAD

**Issue by alekseyvm** [owncloud/core#14797]
While try to update via Update Center I got this error

```[Wed Mar 11 16:11:07 2015] [warn] [client 192.168.1.101] mod_fcgid: stderr: PHP Fatal error:  Cannot redeclare class OC\\Security\\SecureRandom in /home/files/public_html/lib/private/security/securerandom.php on line 24, referer: https://files.domain.local/index.php/apps/updater/update.php```

**Comment by LukasReschke** [comment]
Duplicate of https://github.com/owncloud/updater/issues/86. Please use the issue template as well. Thanks.
