### ISSUE TITLE
sharing-dialog, newline after the check-box

### ISSUE THREAD

**Issue by rolandbu** [owncloud/core#14796]
Hi
The newline after the check-box looks wired. I think the better solution is the newline in front of the check-box.

![owncloud8 0 0-9_03112015_01](https://cloud.githubusercontent.com/assets/5870127/6596163/d21bb2ba-c7f1-11e4-983f-376ca8bf4384.png)
![owncloud8 0 0-9_03112015_02](https://cloud.githubusercontent.com/assets/5870127/6596162/d21947aa-c7f1-11e4-8858-fc6b2f79b159.jpg)

**Comment by karlitschek** [comment]
@owncloud/designers

**Comment by MorrisJobke** [comment]
I think this will be addressed with the new share dialog: #5873

**Comment by jancborchardt** [comment]
@rolandbu which version of ownCloud do you use? It looks like 7 or 6, because the »notify by email« function was removed in 8, which fixes this issue.

**Comment by rolandbu** [comment]
@jancborchardt  No, it is 8.0.0-9 Debian community version from the  http://download.opensuse.org/repositories/isv:ownCloud:community/Debian_7.0/ repository.

**Comment by jancborchardt** [comment]
I’m confused. We removed that function, didn’t we @nickvergessen?

**Comment by nickvergessen** [comment]
@jancborchardt no, I didn't do anything to remove it and have it displayed in master aswell

**Comment by DeepDiver1975** [comment]
@jancborchardt you have to enable this in the admin settings

![bildschirmfoto von 2015-03-17 13 12 41](https://cloud.githubusercontent.com/assets/1005065/6687041/5b313ac0-cca7-11e4-83ff-66d008c578a6.png)

**Comment by jancborchardt** [comment]
But it’s not a default, right? I’d really say it’s finally time to remove it since the Activity/notification settings solve this. It’s not something for the sharer to decide.

**Comment by DeepDiver1975** [comment]
> I’d really say it’s finally time to remove it since the Activity/notification settings solve this. It’s not something for the sharer to decide.

well - there are differences: 
- different mail templates are used (interesting in terms of theming)
- the timing is different - in the activity app an email is sent in time frames (e.g. hourly) where as on the share dialog it's immediate
- furthermore the mail in activity app is combined with multiple other events

**Comment by karlitschek** [comment]
yes. i´m not sure we can/should remove this. users like this feature

**Comment by MorrisJobke** [comment]
> the timing is different - in the activity app an email is sent in time frames (e.g. hourly) where as on the share dialog it's immediate

We could introduce the "send once the event occurs"? cc @nickvergessen

**Comment by MorrisJobke** [comment]
But I would like to keep that feature. Because then it's easy to send a link by mail without firing up you mail app and copy and paste some links.

**Comment by jancborchardt** [comment]
But then it should be a button. A checkbox for this makes no sense.

**Comment by MorrisJobke** [comment]
> But then it should be a button. A checkbox for this makes no sense.

? It's an input field for the email address with a button "Send"

**Comment by jancborchardt** [comment]
@MorrisJobke I was talking about the »notify by email« checkbox which shows up next to each user in the share dialog. Of course I _don’t_ want to remove the »send link by email« feature.

**Comment by MorrisJobke** [comment]
> Of course I don’t want to remove the »send link by email« feature.

-.- Sorry I totally mixed this up. My fault :(

**Comment by MorrisJobke** [comment]
Yes. This setting is kind of useless here. Each user should decide this for itself. Not the sharer.

**Comment by jancborchardt** [comment]
So – @karlitschek since you said »users like this feature« I’m pretty sure you also meant the »Send share link via email« feature. But we were talking about the »notify by email« checkbox, which isn’t even there by default.

Can we remove that? As Morris said, the sharer shouldn’t decide that, as it’s handled by the notifications. It’s basically a legacy piece we added back when we didn’t have email notifications. cc @nickvergessen

**Comment by nickvergessen** [comment]
Well if we only had some usage stats for the activity app. But I assume it is okay to say "we remove this feature from the core. If you want it, use the activity app"

**Comment by jancborchardt** [comment]
I mean – the feature is not enabled by default anyway.

Maybe it’s time to think about putting the notifications mechanism in core instead? It’s a really core feature of file management/sharing, while a view on activity seems quite different. It’s actually a bit confusing that they belong together.

**Comment by jancborchardt** [comment]
Fix at https://github.com/owncloud/core/pull/15114
