### ISSUE TITLE
After a reboot users can't see their files

### ISSUE THREAD

**Issue by ohnotnow** [owncloud/core#14793]
I've got an install of owncloud 8 from the rpm repo running on CentOS 7 (owncloud update centre says it's up-to-date). The server seemed to be running fine, had been rebooted numerous times - then yesterday I had to shut it down again and when it came back up users could log in, but all they could see was the default documents/photos folders.

The data is all still there on disk and from a quick scan of the mysql tables things look ok there too (ie, no sign of strange/duplicate paths or anything). If the users upload new files those show up ok in the right place. Storage paths seem ok both in the web interface and the new uploaded files are going into the right user folders. The group information shows up ok in the Users list too.

Most users are coming in via LDAP, but there are local accounts too - all have the same problem. There's nothing leaping out at me in the logs either (there were initially a few out-of-memory crashes but had cleared up after allocating more memory via .htaccess).

Are there any pointer to places I could look? I'm wary of re-scanning the files before seeing if there's something else I can try...

Oh - and for reference, it's CentOS 7, php-5.4.16, apache httpd-2.4.6-19.

**Comment by LukasReschke** [comment]
Thanks a lot for reporting issues back to us!

We need some more information to properly support you with your issue!

Can I ask you to follow our guidelines for submitting bugs as described here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by ohnotnow** [comment]
I'll try as best as I can below :-)

### Steps to reproduce
I wish I knew...

### Expected behaviour
Users should be able to see their files.

### Actual behaviour
Users cannot see their existing files but can see new ones.

### Server configuration
**Operating system**: 
CentOS 7 x86_64

**Web server:** 
Apache 2.4.6

**Database:** 
MariaDB 5.5

**PHP version:** 
5.4.16

**ownCloud version:** (see ownCloud admin page)
ownCloud 8.0 (stable) 

**Updated from an older ownCloud or fresh install:**
Fresh install

**List of activated apps:**
Default + LDAP user and group backend 0.5.0

**The content of config/config.php:**
  'instanceid' => 'xxxxxx',
  'passwordsalt' => 'xxxxxxx',
  'secret' => 'xxxxxx',
  array (
    0 => 'xxxxxx.xxx',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'overwrite.cli.url' => 'http://xxxxxx.xxx/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.0.7',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxxxxxx',
  'dbpassword' => 'xxxxxxxx',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'mail_from_address' => 'xxxxxxx',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'xxxxx.xxx',
  'loglevel' => 3,

**Are you using external storage, if yes which one:**
No

**Are you using encryption:**
No

**Are you using an external user-backend, if yes which one:** 
Yes - LDAP

#### LDAP configuration
| user_ldap | s01home_folder_naming_rule           | attr:uid                                    |
| user_ldap | s01last_jpegPhoto_lookup             | 0                                           |
| user_ldap | s01ldap_agent_password               |                                             |
| user_ldap | s01ldap_attributes_for_group_search  |                                             |
| user_ldap | s01ldap_attributes_for_user_search   |                                             |
| user_ldap | s01ldap_backup_host                  |                                             |
| user_ldap | s01ldap_backup_port                  |                                             |
| user_ldap | s01ldap_base                         | o=Xxx                                       |
| user_ldap | s01ldap_base_groups                  | o=Xxx                                       |
| user_ldap | s01ldap_base_users                   | o=Xxx                                       |
| user_ldap | s01ldap_cache_ttl                    | 600                                         |
| user_ldap | s01ldap_configuration_active         | 1                                           |
| user_ldap | s01ldap_display_name                 | cn                                          |
| user_ldap | s01ldap_dn                           |                                             |
| user_ldap | s01ldap_email_attr                   | mail                                        |
| user_ldap | s01ldap_experienced_admin            | 0                                           |
| user_ldap | s01ldap_expert_username_attr         |                                             |
| user_ldap | s01ldap_expert_uuid_group_attr       |                                             |
| user_ldap | s01ldap_expert_uuid_user_attr        |                                             |
| user_ldap | s01ldap_group_display_name           | cn                                          |
| user_ldap | s01ldap_group_filter                 |                                             |
| user_ldap | s01ldap_group_filter_mode            | 0                                           |
| user_ldap | s01ldap_group_member_assoc_attribute | uniqueMember                                |
| user_ldap | s01ldap_groupfilter_groups           |                                             |
| user_ldap | s01ldap_groupfilter_objectclass      |                                             |
| user_ldap | s01ldap_host                         | ldaps://xxxxxx.xxx                          |
| user_ldap | s01ldap_login_filter                 | (&(|(objectclass=inetOrgPerson))(uid=%uid)) |
| user_ldap | s01ldap_login_filter_mode            | 0                                           |
| user_ldap | s01ldap_loginfilter_attributes       |                                             |
| user_ldap | s01ldap_loginfilter_email            | 0                                           |
| user_ldap | s01ldap_loginfilter_username         | 1                                           |
| user_ldap | s01ldap_nested_groups                | 0                                           |
| user_ldap | s01ldap_nocase                       | 0                                           |
| user_ldap | s01ldap_override_main_server         | 0                                           |
| user_ldap | s01ldap_paging_size                  | 500                                         |
| user_ldap | s01ldap_port                         | 636                                         |
| user_ldap | s01ldap_quota_attr                   |                                             |
| user_ldap | s01ldap_quota_def                    |                                             |
| user_ldap | s01ldap_tls                          | 0                                           |
| user_ldap | s01ldap_turn_off_cert_check          | 0                                           |
| user_ldap | s01ldap_user_filter_mode             | 0                                           |
| user_ldap | s01ldap_userfilter_groups            |                                             |
| user_ldap | s01ldap_userfilter_objectclass       | inetOrgPerson                               |
| user_ldap | s01ldap_userlist_filter              | (|(objectclass=inetOrgPerson))              |
| user_ldap | types                                | authentication 

### Client configuration
**Browser:** Any affected
**Operating system:** All affected

### Logs
#### Web server error log
[Tue Mar 10 10:23:13.966160 2015] [:error] [pid 7832] [client xxx.xxx.6.43:50780] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20979712 bytes) in /var/www/html/owncloud/lib/private/files/storage/local.php on line 161
[Tue Mar 10 17:15:51.463339 2015] [:error] [pid 7321] [client xxx.xxx.176.23:64861] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20979712 bytes) in /var/www/html/owncloud/lib/private/files/storage/local.php on line 161
[Tue Mar 10 17:26:00.727745 2015] [authz_core:error] [pid 8670] [client xxx.xxx.177.10:38794] AH01630: client denied by server configuration: /var/www/html/owncloud/data/htaccesstest.txt
[Tue Mar 10 17:54:41.214500 2015] [:error] [pid 10561] [client xxx.xxx.176.23:49774] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20979712 bytes) in /var/www/html/owncloud/lib/private/files/storage/local.php on line 161
[Tue Mar 10 20:25:52.495030 2015] [:error] [pid 14038] [client xxx.xxx.176.23:50066] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20979712 bytes) in /var/www/html/owncloud/lib/private/files/storage/local.php on line 161
[Wed Mar 11 09:16:41.468445 2015] [authz_core:error] [pid 44003] [client xxx.xxx.177.10:40605] AH01630: client denied by server configuration: /var/www/html/owncloud/data/htaccesstest.txt
[Wed Mar 11 10:53:31.696347 2015] [authz_core:error] [pid 46316] [client xxx.xxx.177.10:40868] AH01630: client denied by server configuration: /var/www/html/owncloud/data/htaccesstest.txt


#### ownCloud log
(Recent-ish parts anyway)
{"reqId":"2d7f55eb6725efc495b78b7e35087814","remoteAddr":"xxx.xxx.6.43","app":"webdav","message":"Exception: {\"Message\":\"No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(123): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(103): OC_Connector_Sabre_Auth->auth(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Plugin.php(108): OC_Connector_Sabre_Auth->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod('PROPFIND', '')\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(433): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(455): Sabre\\\\DAV\\\\Server->broadcastEvent('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('PROPFIND', '')\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(61): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(54): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":73}","level":0,"time":"2015-03-11T10:54:01+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav"}
{"reqId":"20f75587f834b4444c481fdd7ed04ed5","remoteAddr":"xxx.xxx.176.157","app":"user_ldap","message":"No group filter is specified, LDAP group feature will not be used.","level":1,"time":"2015-03-11T10:54:01+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"a7a5c08039fe2d605cfd864447cf01c4","remoteAddr":"xxx.xxx.176.231","app":"user_ldap","message":"No group filter is specified, LDAP group feature will not be used.","level":1,"time":"2015-03-11T10:54:01+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"63946012ffa4f3ec4096ffc236dba4da","remoteAddr":"xxx.xxx.6.43","app":"user_ldap","message":"No group filter is specified, LDAP group feature will not be used.","level":1,"time":"2015-03-11T10:54:01+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav"}
{"reqId":"e83ad712ce683da5fd1a4f0a3477a3b0","remoteAddr":"xxx.xxx.176.42","app":"user_ldap","message":"No group filter is specified, LDAP group feature will not be used.","level":1,"time":"2015-03-11T10:54:04+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/admin\/log\/entries?offset=63&count=10"}
{"reqId":"6b2f27161ceadcf298295bd2652e918d","remoteAddr":"xxx.xxx.176.248","app":"webdav","message":"Exception: {\"Message\":\"No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(123): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(103): OC_Connector_Sabre_Auth->auth(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Plugin.php(108): OC_Connector_Sabre_Auth->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod('PROPFIND', '')\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(433): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(455): Sabre\\\\DAV\\\\Server->broadcastEvent('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('PROPFIND', '')\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(61): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(54): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":73}","level":0,"time":"2015-03-11T10:54:05+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav"}
{"reqId":"7f0c57f69f1d40563cfb2a0554d8132f","remoteAddr":"xxx.xxx.125.165","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => cn=xxxx,ou=staff,o=xxxx\n)\n attr Array\n(\n    [0] => \n)\n limit 500 offset 0","level":0,"time":"2015-03-11T10:54:10+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"7f0c57f69f1d40563cfb2a0554d8132f","remoteAddr":"xxx.xxx.125.165","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2015-03-11T10:54:10+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"7f0c57f69f1d40563cfb2a0554d8132f","remoteAddr":"xxx.xxx.125.165","app":"user_ldap","message":"readAttribute: cn=xxxx,ou=staff,o=xxxx found","level":0,"time":"2015-03-11T10:54:10+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"7f0c57f69f1d40563cfb2a0554d8132f","remoteAddr":"xxx.xxx.125.165","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => cn=xxxx,ou=staff,o=xxxx\n)\n attr Array\n(\n    [0] => uid\n)\n limit 500 offset 0","level":0,"time":"2015-03-11T10:54:10+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"7f0c57f69f1d40563cfb2a0554d8132f","remoteAddr":"xxx.xxx.125.165","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2015-03-11T10:54:10+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"db71f1b25cb2aec6a4d6f250ac5dc9c7","remoteAddr":"xxx.xxx.176.42","app":"user_ldap","message":"No group filter is specified, LDAP group feature will not be used.","level":1,"time":"2015-03-11T10:54:28+00:00","method":"POST","url":"\/owncloud\/index.php\/settings\/admin\/log\/level"}

### Browser Log
(Ignoring successful GET's)
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery-migrate.min.js:3:0
window.controllers is deprecated. Do not use it for UA detection. ace.js:1716:0
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://xxxxx.xxk 'unsafe-eval'").

**Comment by ohnotnow** [comment]
Just to add to the owncloud log - going back a little further (we were powering kit off due to electrical work) I can see a lot of :

{"reqId":"4540b9be59ac6f38a119aae832325836","remoteAddr":"xxx.xxx.176.186","app"
:"user_ldap","message":"No LDAP Connection to server ldaps:\/\/xxxxxx.xxx
","level":2,"time":"2015-03-10T10:40:53+00:00"}

Which was possibly due to the nearest DNS server being off for a few minutes.  Possibly the ldap mappings have got lost?

**Comment by PVince81** [comment]
@blizzz

**Comment by ohnotnow** [comment]
A further update... I've tried running 'occ files:scan xxxx' for an LDAP user who could log in ok (although not see their files) and it comes back saying 'Unknown user xxxx'. user:report lists no ldap users either.  But in the sql table oc_ldap_user_mapping there is an entry for them. I also tried files:scan with the owncloud_name from the table (just in case that's how owncloud refereces them) and got another unknown user.

**Comment by PVince81** [comment]
If you're not seeing files maybe something is wrong in oc_storages, can you have a look ?
The entries should either look like "local::$datadir/$userid/" or "home::$userid" (only one of these must exist, not both at the same time). $userid could also be the LDAP uuid.
Some people reported a mismatch between folder name and what's in oc_storages, but I'm not sure if that would cause files to not be displayed.

**Comment by PVince81** [comment]
You can also check if "oc_filecache" for those users contain any files or is empty. That "oc_filecache.storage" maps to "oc_storages.numeric_id".

**Comment by ohnotnow** [comment]
The oc_storages tables looks fine (only one entry for each user and seem mapped to the right userid). In oc_filecache there are some files listed for the user I was looking at - some in files_trashbin and the newly created ones - but the old data that's still in 'files/' on disk isn't showing up.

I've just walked through the LDAP wizard again and now the user:report shows up LDAP users and user:lastseen works again. So at least I can possibly run the files:scan again if that is the only way back...

**Comment by ohnotnow** [comment]
A little more digging. At about the time the "No LDAP Connection to server ldaps" errors shown above started appearing, a folder in data/ was created that matches the owncloud_name in oc_ldap_user_mappings (with the default folders/files) rather than the LDAP uid which is used in the settings for | user_ldap | s01home_folder_naming_rule | attr:uid . So looks like something 'went funny' around the ldap uid/mappings when DNS went down.

When the server (and DNS) came back up they are definitely getting their original/correct /data/uid folder though as that's where new files are showing up.  

Possibly when the new folder was created it flushed the oc_filecache entries for the old stuff?

**Comment by blizzz** [comment]
> A little more digging. At about the time the "No LDAP Connection to server ldaps" errors shown above started appearing, a folder in data/ was created that matches the owncloud_name in oc_ldap_user_mappings (with the default folders/files) rather than the LDAP uid which is used in the settings for | user_ldap | s01home_folder_naming_rule | attr:uid . So looks like something 'went funny' around the ldap uid/mappings when DNS went down.

Possible happening: user existence was cached while LDAP/DNS was offline. An attempt to use the files for the user was made, but while user was confirmed to be existant, his real folder name could not be retrieved.

**Comment by ohnotnow** [comment]
I'm probably going to have to try running files:scan for the user(s) soon - they've been quite patient with me so far, but getting a little more urgent.  If there's anything else I can dig out for you in the near-term let me know though.  I've got a snapshot of the data & database that I can dig at if needed afterwards.

**Comment by blizzz** [comment]
For now it's interesting whether the files appear again after running the file scan. As both local and LDAP users are affected it's likely that there is something wrong there. If it works, you could compare the filecache tables on the states before the upgrade, afterwards with the faulty behaviour and when it worked.

Later, you could try to setup a test setup and redo the upgrade, to try to reproduce the issue and possibly apply debug patches or even fixes.

**Comment by ohnotnow** [comment]
Ok - files:scan brought all the data back into view for the users, but has lost all of the sharing options on the folders (that's maybe expected behaviour?).

I think for now we'll disable LDAP and go with local accounts.  The corporate ldap server can be a bit temperamental so I don't want to be back here again any time soon ;-)

**Comment by DeepDiver1975** [comment]
> Possible happening: user existence was cached while LDAP/DNS was offline.

just another reason to keep user from ALL auth backends in the central database :speak_no_evil:

**Comment by ohnotnow** [comment]
Oh - as I have now found out, the local user accounts *didn't* seem to be affected - only the LDAP ones.  It turns out that all of the local accounts were storing their files in a shared group folder created by an LDAP user (which had disappeared), so that's why they couldn't see "their" files.

But anyway - a corner case still to be caught somewhere for LDAP auth/mapping.

**Comment by blizzz** [comment]
> Oh - as I have now found out, the local user accounts didn't seem to be affected - only the LDAP ones. It turns out that all of the local accounts were storing their files in a shared group folder created by an LDAP user (which had disappeared), so that's why they couldn't see "their" files.

That explains it.

>>  Possible happening: user existence was cached while LDAP/DNS was offline.

> just another reason to keep user from ALL auth backends in the central database :speak_no_evil:

@DeepDiver1975 this will have such a long :rat:-tail. Needs to be discussed and drafted carefully. I agree on necessity.

**Comment by blizzz** [comment]
Meanwhile, exceptions are thrown when LDAP is required, but not accessible or get lost.
