### ISSUE TITLE
Creating "test (1)" exception folders for users needs performance improvement

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#14795]
I added 1k users to a group (#14794) and then shared a folder with the group, stupid me...
It now creates 1k Views and checks whether the folder exists, etc.

The request for the share finished now after 10 minutes :snail: 
This should happen asyncronous or be quicker light-weighter in general somehow if possible :/

**Comment by MorrisJobke** [comment]
`\OCP\...\IBus`

**Comment by LukasReschke** [comment]
> \OCP\...\IBus

I'm wondering if moving everything to a cronjob that is executed only in 15 minute intervalls is the best solution. Usually when such an action is not performed directly users are *really* confused :)

**Comment by nickvergessen** [comment]
Yeah, certainly not. But we need a way to improve here :/

**Comment by icewind1991** [comment]
please test with https://github.com/owncloud/core/pull/13899 and https://github.com/owncloud/core/pull/13896

**Comment by DeepDiver1975** [comment]
@nickvergessen can you test the prs above? THX

**Comment by nickvergessen** [comment]
Group with 100 user benchmark:

Branch | Time | Blackfire | Compare (master)
------ | ---- | --------- | ----------------
master | 1.35 | [Blackfire](https://blackfire.io/slots/8dcea534-05aa-415d-9bda-58e98669671e/graph) | -
PR #13896 | 1.36 | [Blackfire](https://blackfire.io/slots/e0549b65-1161-46d8-80ba-f1e9d3c618ce/graph) | [Compare](https://blackfire.io/slots/compare/8dcea534-05aa-415d-9bda-58e98669671e...e0549b65-1161-46d8-80ba-f1e9d3c618ce/graph?callname=main%28%29&selected=&settings[dimension]=wt&settings[callerDepth]=2&settings[calleeDepth]=&settings[minNodeCost]=5&settings[minCallCost]=0.01)
PR #13899 | 0.908 | [Blackfire](https://blackfire.io/slots/ce726c88-859e-44a2-9249-f330bfb82e9c/graph) | [Compare](https://blackfire.io/slots/compare/8dcea534-05aa-415d-9bda-58e98669671e...ce726c88-859e-44a2-9249-f330bfb82e9c/graph?callname=main%28%29&selected=&settings[dimension]=wt&settings[callerDepth]=2&settings[calleeDepth]=&settings[minNodeCost]=5&settings[minCallCost]=0.01)
Both | 0.871 | [Blackfire](https://blackfire.io/slots/9bc97afe-d829-4eb9-bc6e-8205270790cc/graph) | [Compare](https://blackfire.io/slots/compare/8dcea534-05aa-415d-9bda-58e98669671e...9bc97afe-d829-4eb9-bc6e-8205270790cc/graph?callname=main%28%29&selected=&settings[dimension]=wt&settings[callerDepth]=2&settings[calleeDepth]=&settings[minNodeCost]=5&settings[minCallCost]=0.01)

For reference when sharing with a already shared group, the request is about ~0.4sec.
Removing that makes it a 0.9 to 0.45 improvement, so about 50% faster

**Comment by PVince81** [comment]
Related https://github.com/owncloud/core/pull/19944

**Comment by schiesbn** [comment]
@nickvergessen can you try again with oC8.2? This shouldn't be a problem anymore because now we verify the mount point once it is mounted for the first time

**Comment by nickvergessen** [comment]
We still do that:
https://github.com/owncloud/core/blob/8f09d5b/lib/private/share/share.php#L2140-L2144
```php
				// group share which doesn't exists until now, check if we need a unique target for this user
				$itemTarget = Helper::generateTarget($itemType, $itemSource, self::SHARE_TYPE_USER, $user,
					$uidOwner, $suggestedItemTarget, $parent);
```

And yes, the request to share a folder with a group of 3k users still times out for me with 20secs execution limit

**Comment by nickvergessen** [comment]
But the actual problem seems to be the hooks now:
```json
{"message":"before","level":3,"time":"2015-10-28T09:31:25+00:00"}
{"message":"beforePut","level":3,"time":"2015-10-28T09:31:30+00:00"}
{"message":"beforeHook","level":3,"time":"2015-10-28T09:31:47+00:00"}
~30secs in hooks
{"message":"afterHook","level":3,"time":"2015-10-28T09:32:11+00:00"}
{"message":"afterPut","level":3,"time":"2015-10-28T09:32:11+00:00"}
{"message":"after","level":3,"time":"2015-10-28T09:32:11+00:00"}
```

https://github.com/owncloud/core/blob/8f09d5b/apps/files_sharing/lib/updater.php#L83-L87
```php
			} elseif ($shareType === \OCP\Share::SHARE_TYPE_GROUP) {
				foreach (\OC_Group::usersInGroup($shareWith) as $user) {
					self::correctUsersFolder($user, $params['fileTarget']);
				}
			}
```
This still set's up the view of each user :/

**Comment by schiesbn** [comment]
I was 100% sure that I added a item type check and skipped this step for files... Let me look at this in more detail.

@rullzer we should definitely don't do this during the share operation, because this is a real performance killer. Just as a note, so that we don't forget this for 9.0

**Comment by PVince81** [comment]
Ideally it would be good to have a system that works not only for shares but also external storages, because overlap can happen there too: https://github.com/owncloud/core/issues/11794

**Comment by nickvergessen** [comment]
That's now not done on sharing anymore but when the user mount it, so we can close this
