### ISSUE TITLE
Page blank after upgrade from 7.0.4.2 to 8.0.2.0 with core apps (contacts and calendar)

### ISSUE THREAD

**Issue by andunix** [owncloud/core#14804]
I upgraded my owncloud today from 7.0.4.2 to 8.0.2.0 and had also the blank page issue. It worked again after disabling contacts and calendar. I'm opeing the issue as all the issues I found refer to third party apps and are closed in 8.0.1 or 8.0.2. I'm using no third party apps and the two failed apps are internal ones.
Will these two apps work again with the next release (8.0.3 or 8.1) or do I have to fix them somehow?
Kind regards,
Andreas

**Comment by psych0d0g** [comment]
Same for me!

**Comment by MorrisJobke** [comment]
Remove the folders calendar and contacts from your apps directory and the go to the apps management and click install for those apps. Then the new version will get downloaded.

**Comment by RealRancor** [comment]
Hi,

you need to follow the upgrade manuals at doc.owncloud.org and remove the old /apps/contacts and /apps/calendar folder.

**Comment by dave8128** [comment]
I can confirm removing the folders and reinstalling corrects the issue.
These are available under the "Recommended" tab in Apps.
Contacts 8.0 and Calendar 8.0

Thanks.

**Comment by andunix** [comment]
@MorrisJobke: Thanks, removing and reinstalling fixed it.

**Comment by TenserD** [comment]
@MorrisJobke +1
thx a lot this fixed it

**Comment by chimerarv** [comment]
No joke, I been searching everywhere and this finally did the trick. THANKS
