### ISSUE TITLE
Provide a way to create preview provider within an app

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#14803]
See https://github.com/owncloud/core/pull/13648#issuecomment-78271913
- [x] Preview provider registration in manager #14857
- [ ] Implement inter-app dependency management
- [ ] Move providers outside of core

**Comment by oparoz** [comment]
The first steps would be to have:
* app inter-dependency checks
* app invocation API

Unless this creates a special app category which only works with the Preview app

Providers return OC_Image objects which will need to be pushed to apps requesting the preview

**Comment by DeepDiver1975** [comment]
refs #14857

**Comment by PVince81** [comment]
Moving to 8.2 as we're past feature freeze

**Comment by PVince81** [comment]
Moving to 9.0
