### ISSUE TITLE
Upgrading 8.0.1 to 8.0.2

### ISSUE THREAD

**Issue by mcnesium** [owncloud/core#14806]
Having issues with upgrade OC server from 8.0.1 to 8.0.2:

Via update center:

it stops saying "server errror: look in the webserver logfile for errors" but there are no update related error messages in `/var/log/nginx/error.log`

Via command line:

    mcnesium@fluse:/var/www/owncloud$ sudo -u www-data php occ upgrade
    [sudo] password for mcnesium:
    {"reqId":"f51f27fccd587e4dd6a59b866ef5cf3b","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/var\/www\/owncloud\/apps\/calendar\/appinfo\/app.php#41","level":3,"time":"2015-03-11T15:22:29+00:00","method":"--","url":"--"}
    ownCloud is already latest version
    {"reqId":"f51f27fccd587e4dd6a59b866ef5cf3b","remoteAddr":"","app":"PHP","message":"chmod(): Operation not permitted at \/var\/www\/owncloud\/lib\/private\/log\/owncloud.php#85","level":3,"time":"2015-03-11T15:22:30+00:00","method":"--","url":"--"}

The owncloud directory at `/var/www/owncloud` as well as the data directory at `/mnt/crypt/owncloud` have `drwxrwx---   www-data www-data` permissions and ownership.

Still running on 8.0.1 with the [yellow bar](https://doc.owncloud.org/server/8.0/admin_manual/_images/updater-1.png) on top.

**Update:** actually I did find a line in the log:

    2015/03/11 16:37:08 [error] 2580#0: *45305 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 5.28.69.71, server: xxxx, request: "GET /owncloud/index.php/apps/updater/ajax/backup.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock", host: "xxxx", referrer: "https://xxxx/owncloud/index.php/apps/updater/update.php"

**Comment by RealRancor** [comment]
Hi,

seems the updater is running into a timeout? If yes you might want to re-open in https://github.com/owncloud/updater/issues using the issue template provided here: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md
