### ISSUE TITLE
OCS Share API for share creation is missing expiration date

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#14808]
Currently to create a link share with expiration date, one needs to first create public share without it, and then update it with the expiration date.

See that the API https://doc.owncloud.org/server/7.0/developer_manual/core/ocs-share-api.html#create-a-new-share doesn't contain a "expireDate" field (also missing in the source code).

Only update has it: https://doc.owncloud.org/server/7.0/developer_manual/core/ocs-share-api.html#update-share

On a side note: I also wonder if "publicUpload" should be incorporated into the permissions instead...

**Comment by PVince81** [comment]
@schiesbn is there a reason (maybe technical limitation) why "expireDate" was omitted ?

**Comment by rullzer** [comment]
@PVince81 the public upload is internally already handled as a permission update.

Probably would make sense to move away from that indeed as to minimize the special handling of public links.

**Comment by rullzer** [comment]
Seems that it should not be to hard to add the argument to the create new share command.

I have it working now. But we need some more sanity checking in share.php. I'll have a look later this week.

**Comment by rullzer** [comment]
Ok after digging into this adding it to the OCS endpoint should not be that hard. There even in an expirationDate agument for shareItem. But it is pretty untested (non of the calls in test/lib/share/share.php actually use it)

So lets keep this on the list for sharing 2.0 but for now I do not really feel comfortable adding it if the backend code is somewhat untested...

**Comment by PVince81** [comment]
backlog then

**Comment by PVince81** [comment]
Closed by https://github.com/owncloud/core/issues/18651
