### ISSUE TITLE
Add CapabilitiesManager to allow (easier) migration to the AppFramework

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#14805]
As pointed out (at least) in #12454 and #13964. The currently we cannot properly handle getCapabiilities if and app is converted to the AppFramework.

I had a discussion with @PVince81 about this on IRC. And we came up with the following.

- A capabilities manager is introduced. 
- Apps can register a function in the capabilities manager. 
- The getCapabilities endpoint then simply accesses the CapabilitiesManager and calls all the registered functions of the apps.

Any comments/suggestions etc?

CC: @PVince81 @LukasReschke @Raydiation @DeepDiver1975 @schiesbn @butonic

**Comment by Raydiation** [comment]
Sounds good

**Comment by rullzer** [comment]
Fixed by #15093
