### ISSUE TITLE
Error during Update from 7.0.4 to 8.0.2: Could not automatically fix legacy storage

### ISSUE THREAD

**Issue by icetear** [owncloud/core#14800]
Could not automatically fix legacy storage "local::/mnt/storage/Backup/owncloud/data/mgaida/" => "home::mgaida" because they both have data.

**Comment by LukasReschke** [comment]
@PVince81

**Comment by LukasReschke** [comment]
Do we have some documentation also in regard to EE?

**Comment by icetear** [comment]
sorry for the hasty report. It seems this problem is handled here: https://github.com/owncloud/core/issues/13980

**Comment by RealRancor** [comment]
@icetear 
If you think its the same isse feel free to close this one. :-)
