### ISSUE TITLE
error messages in webserver log

### ISSUE THREAD

**Issue by mcnesium** [owncloud/core#14807]
My webserver log at `/var/log/nginx/error.log` is full of those messages:

    2015/03/11 17:06:53 [error] 2581#0: *46493 FastCGI sent in stderr: "PHP message: {"reqId":"f2f260af9444d27fa097237c4c10e570","remoteAddr":"5.28.69.71","app":"webdav","message":"Exception: {\"Message\":\"No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(126): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(106): OC_Connector_Sabre_Auth->auth(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Plugin.php(108): OC_Connector_Sabre_Auth->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod('PROPFIND', 'mcobst\\\/music')\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(433): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/" while reading response header from upstream, client: 5.28.69.71, server: xxxx, request: "PROPFIND /owncloud/remote.php/webdav/mcobst/music HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "xxxx"

There is one line for every sync of any folder I have set up to be synced in my notebook client. What is this about?

**Comment by karlitschek** [comment]
@icewind1991 what do you think?

**Comment by DeepDiver1975** [comment]
The client does  connect unauthenticated - but afaik not for every folder.

I will look into this.

**Comment by DeepDiver1975** [comment]
```json
{
"reqId":"f2f260af9444d27fa097237c4c10e570",
"remoteAddr":"5.28.69.71",
"app":"webdav",
"message":"Exception: {\"Message\":\"No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(126): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(106): OC_Connector_Sabre_Auth->auth(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Plugin.php(108): OC_Connector_Sabre_Auth->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod('PROPFIND', 'mcobst\\\/music')\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(433): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/" while reading response header from upstream, client: 5.28.69.71, server: xxxx, 
request: "PROPFIND /owncloud/remote.php/webdav/mcobst/music HTTP/1.1", 
upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", 
host: "xxxx"

**Comment by DeepDiver1975** [comment]
@mcnesium which client version are you running? THX

**Comment by mcnesium** [comment]
It's 1.6.4 build 1195 (waiting for 1.8 [desperately](https://github.com/owncloud/client/issues/2479#issuecomment-66272778))

**Comment by dragotin** [comment]
@mcnesium pls try with 1.8.0 beta2, its available from owncloud.org download page section "testing"

**Comment by mcnesium** [comment]
ran this with 1.8 release as well as [this nightly](http://download.owncloud.com/desktop/daily/ownCloud-1.8.0.2204-nightly20150325.pkg) and there are stillt he same messages:

    2015/03/25 09:32:55 [error] 2602#0: *56031 FastCGI sent in stderr: "PHP message: {"reqId":"93dc17739394e0d73f4a4c092ef69e53","remoteAddr":"158.181.82.151","app":"calendar","message":"OC_Share_Backend_Event::formatItems, Missing event: Brunch","level":0,"time":"2015-03-25T08:32:55+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/calendar\/ajax\/events.php?calendar_id=shared_events&start=1427065200&end=1427666400&_=1427228569935"}" while reading response header from upstream, client: 158.181.82.151, server: xxxx, request: "GET /owncloud/index.php/apps/calendar/ajax/events.php?calendar_id=shared_events&start=1427065200&end=1427666400&_=1427228569935 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "xxxx", referrer: "https://xxxx/owncloud/index.php/apps/calendar/"

**Comment by karlitschek** [comment]
@LukasReschke so isn´t this as it is supposed to work? First request is unauthenticated?

**Comment by LukasReschke** [comment]
The ownCloud client should actually behave properly here, anyways properly behaving DAV clients should have this error reported once and not really more often. (see also https://github.com/owncloud/core/issues/14510#issuecomment-95379103)

That said, I am confused that the error in https://github.com/owncloud/core/issues/14807#issuecomment-85952050 seems completely unrelated. @mcnesium Could you double check? Thanks a lot!

**Comment by PVince81** [comment]
Please try again with 8.0.6 or 8.1.1 and sync client 1.8.4.

If you're still having these problems, feel free to reopen.

**Comment by mcnesium** [comment]
No more log messages, thank you :)
