### ISSUE TITLE
Issue Tracker Cleanup

### ISSUE THREAD

**Issue by JimLoose** [owncloud/core#14818]
I hope Owncloud is more for security instead of for tons of features!

On the first page of the issue tracker i stumbled over several issues which are more like:
"feature requests for plugins" (not the default system)

e.g.
https://github.com/owncloud/core/issues/14446
https://github.com/owncloud/core/issues/14599

Does it make sense to ban such issues here and move them to another place?

+ sorry ban topics like this one as well!

Please close this! :-)

**Comment by karlitschek** [comment]
It is fine to have feature request. Nothing wrong with that as long as they are tagged correctly so that the developer can still find the bugs. :-)
