### ISSUE TITLE
cron.lock isn't deleted when data directory isn't in $SERVERROOT

### ISSUE THREAD

**Issue by drgreco** [owncloud/core#14812]
I've been having issues with cron.lock not being deleted. Once I created a symlink from owncloud/data to the actual data directory, the cron.lock was properly deleted.

If it matters, I run cron.php from the www-data crontab

**Comment by RealRancor** [comment]
Hi,

recently there was a fix included to avoid not deleted cron.lock files: https://github.com/owncloud/core/issues/3221

Not quite sure if this is related.

**Comment by drgreco** [comment]
This was an issue from 7.x through at least 8.0.0 (don't remember if I fixed it before or after the upgrade to 8.0.2). 

But yea, if the locking method has changed for the next version, then hopefully this issue will be resolved.

**Comment by DeepDiver1975** [comment]
@drgreco let us know if the problem continues to exist once you are on oc8 -> closing this for now as won't fix

**Comment by RealRancor** [comment]
Just to avoid confusion: Its not in OC8.0.x yet and needs to be backported first: https://github.com/owncloud/core/pull/14400#issuecomment-77171743

**Comment by DeepDiver1975** [comment]
> Just to avoid confusion: Its not in OC8.0.x yet and needs to be backported first: #14400 (comment)

sure - thx for the pointer @RealRancor - I was talking about 8.1
