### ISSUE TITLE
occ upgrade to version 8 fails with mariadb

### ISSUE THREAD

**Issue by Blindfreddy** [owncloud/core#14810]
Upgraded owncloud backend to version 8.0.0.7.  Running occ upgrade fails with following message

sudo -u www-data ./occ upgrade
Turned on maintenance mode
An exception occurred while executing 'ALTER TABLE oc_oc_appconfig_od0cqzqaec3u0 RENAME INDEX appconfig_config_key_index TO oc_vmv4gtsaq3y21':

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'INDEX appconfig_config_key_index TO oc_vmv4gtsaq3y21' at line 1
Turned off maintenance mode
Update failed

The SQL statement is obviously jibberish, neither the table nor the index exists.  Table oc_appconfig exists, and it has an index appconfig_config_key_index:
MariaDB [owncloud]> show indexes from oc_appconfig;
+--------------+------------+----------------------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| Table        | Non_unique | Key_name                   | Seq_in_index | Column_name | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment |
+--------------+------------+----------------------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| oc_appconfig |          0 | PRIMARY                    |            1 | appid       | A         |          41 |     NULL | NULL   |      | BTREE      |         |               |
| oc_appconfig |          0 | PRIMARY                    |            2 | configkey   | A         |          83 |     NULL | NULL   |      | BTREE      |         |               |
| oc_appconfig |          1 | appconfig_config_key_index |            1 | configkey   | A         |          83 |     NULL | NULL   |      | BTREE      |         |               |
| oc_appconfig |          1 | appconfig_appid_key        |            1 | appid       | A         |          41 |     NULL | NULL   |      | BTREE      |         |               |
+--------------+------------+----------------------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
4 rows in set (0.01 sec)

**Comment by RealRancor** [comment]
Hi,

this is a known issue with OC 8.0.0 https://github.com/owncloud/core/issues/14003 and was fixed with the today released 8.0.2: https://owncloud.org/changelog/

**Comment by Blindfreddy** [comment]
Thanks, and forgive me for not noticing that this is a duplicate.  I appended --skip-migration-test  and it updated successfully on 8.0.0.7

sudo -u www-data ./occ upgrade --skip-migration-test
Turned on maintenance mode
Updated database
Turned off maintenance mode
Update successful

**Comment by RealRancor** [comment]
@Blindfreddy 
I would have recommended to directly upgrade to OC 8.0.2 instead of skipping the migration test.
