### ISSUE TITLE
Support for prioritised synchronisation (Suggestion)

### ISSUE THREAD

**Issue by JakeCowton** [owncloud/core#14821]
I use owncloud to backup some large files from my main desktop, however, when I am doing this, I am also doing work which needs to be synchronised to my other computers.

It would be good if there was a way I could set a specific folder to have sync priority over others which will interrupt other syncing if new changes are detected.

**Comment by MorrisJobke** [comment]
Can I ask you to open this in the sync client issue tracker https://github.com/owncloud/client/issues

Thanks :)
