### ISSUE TITLE
Couldn't install any app

### ISSUE THREAD

**Issue by jsisaev1** [owncloud/core#14820]
Couldn't install any app at fresh installed system.

It says: App does not provide an info.xml file

**Comment by jsisaev1** [comment]
I've Centos 6.6, php 5.6. mod_gzip enabled.

**Comment by DeepDiver1975** [comment]
Most probably tar and/or zip archive support is missing.  We need to enhance the error messages and the checks in missing components.

**Comment by DeepDiver1975** [comment]
@jsisaev1 
which apps did you try?
Can I ask you to run php --info and paste the output? THX

**Comment by DeepDiver1975** [comment]
Anything in the logs? Like "Error while opening archive"

**Comment by oparoz** [comment]
Possibly a duplicate of  https://github.com/owncloud/core/issues/14708

**Comment by LukasReschke** [comment]
Happened to me as well - reason was a missing curl extension for PHP. Can you please try to install the PHP cURL extension?

**Comment by LukasReschke** [comment]
(That said  – I'd welcome a hard-dependency on that)

**Comment by LukasReschke** [comment]
Okay – checked the source code – we require it anyways for functions such as S2S which will otherwise fail hard then – creating a PR.

**Comment by DeepDiver1975** [comment]
> Happened to me as well - reason was a missing curl extension for PHP.

So the fallback implementation in the httphelper doesn't really work - right? Brilliant!

**Comment by LukasReschke** [comment]
> So the fallback implementation in the httphelper doesn't really work - right? Brilliant!

At least not on my machine – yes.

**Comment by flotho** [comment]
Hy #14840 solved the problem for me

**Comment by MorrisJobke** [comment]
@LukasReschke @DeepDiver1975 Closing this for the same reasons as in https://github.com/owncloud/core/issues/14840#issuecomment-87620565 ?

**Comment by DeepDiver1975** [comment]
thx @MorrisJobke
