### ISSUE TITLE
Encryption doesn't work when recreate a user after disabling encryption

### ISSUE THREAD

**Issue by sirio81** [owncloud/core#14823]
ownCloud 7.0.4 (stable) on debian wheezy 64 bit.

How to reproduce:
- enable encryption
- create the user 'test' and login with that user 2 time to encrypt its files
- disable encryption
- now you can login with the user and decrypt file in its profiles but that stped doesn't matter
- remove the acount 'test'
- recreate the user 'test'
- enable the encryption
- log in with user 'test' 2 or more times

In the user profile you'll always see
Encryption App is enabled but your keys are not initialized, please log-out and log-in again

In owncloud.log you'll find
{"app":"Encryption library","message":"public key exists but private key is missing for \"test\"","level":4,"time":"2015-03-12T09:04:27+00:00"}

**Comment by MorrisJobke** [comment]
cc @schiesbn

**Comment by PVince81** [comment]
I guess that when you deleted the user, it didn't automatically remove the "migration state" in the "oc_preferences" table.
What should happen in my opinion:
- if a user is deleted, all preferences of that user must be deleted, which includes the migration flag
- if a user's files are successfully decrypted, remove the migration flag from the DB

**Comment by nickvergessen** [comment]
> if a user is deleted, all preferences of that user must be deleted, which includes the migration flag

That does in fact happen https://github.com/owncloud/core/blob/34a1c2288ab698c355e8bcab432204859f1270a4/lib/private/user/user.php#L186-L187

**Comment by PVince81** [comment]
The migration flag will disappear starting with 8.1 as encryption works differently.

**Comment by PVince81** [comment]
Please upgrade to 8.1.3 or later
