### ISSUE TITLE
[oc update 8.0.2] Loading gif showing forever in update view

### ISSUE THREAD

**Issue by SamEliotFisher** [owncloud/core#14822]
When installing an update (from 8.0.0 to 8.0.2) and experiencing an error the loading-small.gif is displayed forever below the "3. Replace" section even though the update process terminated.

Also, should this really be a .gif animation? Suggesting a replacement with a more modern looking css or js loading symbol. (http://cssload.net/ and http://tobiasahlin.com/spinkit/ etc.)

**Comment by MorrisJobke** [comment]
cc @owncloud/designers

**Comment by DeepDiver1975** [comment]
@SamEliotFisher can I ask you for a screenshot? THX

**Comment by SamEliotFisher** [comment]
@DeepDiver1975 
![oc_screen1](https://cloud.githubusercontent.com/assets/11375752/6615845/ecaa4144-c8a7-11e4-848b-4af708edc2ac.png)

**Comment by MorrisJobke** [comment]
Please reopen this in the updater app, because this is not part of the owncloud core https://github.com/owncloud/updater/
