### ISSUE TITLE
update 8.0.0 ->8.0.2 fails, Simulated database structure update failed

### ISSUE THREAD

**Issue by thastad** [owncloud/core#14831]
### Steps to reproduce
1. Update from 8.0.0 -> 8.0.2 via updater

### Expected behavior
a successful update

### Actual behavior
Updater fails with the following log
An exception occurred while executing 'DROP INDEX appconfig_config_key_index ON oc_oc_appconfig_1swfqlk2wdmto': SQLSTATE[42000]: Syntax error or access violation: 1142 INDEX command denied to user 'cloud'@'localhost' for table 'oc_oc_appconfig_1swfqlk2wdmto'

The mysql user should have all permissions in order.
+--------------------------------------------------------------------------------------------------------------+
| Grants for cloud@localhost                                                                                   |
+--------------------------------------------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO 'cloud'@'localhost' IDENTIFIED BY PASSWORD 'xxx' |
| GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP ON `owncloud`.* TO 'cloud'@'localhost'                    |
+--------------------------------------------------------------------------------------------------------------+

### Server configuration
**Operating system**:
Debian GNU/Linux 7.8
**Web server:**
Apache/2.2.22 (Debian)
**Database:**
mysql
**PHP version:**
PHP 5.4.36-0+deb7u3

**ownCloud version:** (see ownCloud admin page)
8.0.0
**Updated from an older ownCloud or fresh install:**
Fresh
**The content of config/config.php:**

```
  'instanceid' => 'ocstnlo52y27',
   'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.0.0.7',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'cloud',
  'installed' => true,
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
```

### Client configuration
**Browser:**
Firefox 36.0.1
**Operating system:**
windows 8.1

#### ownCloud log (data/owncloud.log)
```
{"reqId":"e55ffb73461dd60ff04419b4e61c9200","remoteAddr":"2a02:fe0:x:x:x:x:x","app":"core","message":"Simulated database structure update failed (exception 'OC\\DB\\MigrationException' with message 'An exception occurred while executing 'DROP INDEX appconfig_config_key_index ON oc_oc_appconfig_1swfqlk2wdmto':\n\nSQLSTATE[42000]: Syntax error or access violation: 1142 INDEX command denied to user 'cloud'@'localhost' for table 'oc_oc_appconfig_1swfqlk2wdmto'' in \/var\/www\/owncloud\/lib\/private\/db\/migrator.php:133\nStack trace:\n#0 \/var\/www\/owncloud\/lib\/private\/db\/migrator.php(91): OC\\DB\\Migrator->checkTableMigrate(Object(Doctrine\\DBAL\\Schema\\Table))\n#1 \/var\/www\/owncloud\/lib\/private\/db\/mdb2schemamanager.php(113): OC\\DB\\Migrator->checkMigrate(Object(Doctrine\\DBAL\\Schema\\Schema))\n#2 \/var\/www\/owncloud\/lib\/private\/db.php(252): OC\\DB\\MDB2SchemaManager->simulateUpdateDbFromStructure('\/var\/www\/ownclo...')\n#3 \/var\/www\/owncloud\/lib\/private\/updater.php(238): OC_DB::simulateUpdateDbFromStructure('\/var\/www\/ownclo...')\n#4 \/var\/www\/owncloud\/lib\/private\/updater.php(211): OC\\Updater->checkCoreUpgrade()\n#5 \/var\/www\/owncloud\/lib\/private\/updater.php(150): OC\\Updater->doUpgrade('8.0.2.0', '8.0.0.7')\n#6 \/var\/www\/owncloud\/core\/ajax\/update.php(50): OC\\Updater->upgrade()\n#7 {main})","level":4,"time":"2015-03-12T13:59:10+00:00"}

```

**Comment by DeepDiver1975** [comment]
looks like you miss the the grant on index - http://dev.mysql.com/doc/refman/5.1/en/privileges-provided.html#priv_index

**Comment by MorrisJobke** [comment]
Please retry after adding this permission. If this is still an issue, reopen this ticket

**Comment by KaputteLeuchte** [comment]
Hi, I get the same error on upgrading vom 8.0.0.7 to 8.1.1. If i look at the database permissions I get the following result:

GRANT USAGE ON *.* TO ...

So I should have all rights, or am I wrong? Could there be another configuration on the database side?
