### ISSUE TITLE
Problem with update from 7.0.2 to 8.0.2

### ISSUE THREAD

**Issue by prepu** [owncloud/core#14832]
Hi, I have tried to update the Owncloud server in a Windows Server 2008 from 7.0.2 to 8.0.2 and I got this message:

Unable to move C:\xampp\htdocs\owncloud2\data to C:\xampp\htdocs\owncloud2\data

Why do I have this problem?

**Comment by MorrisJobke** [comment]
cc @DeepDiver1975 @bantu

**Comment by RealRancor** [comment]
@MorrisJobke Based on your question in https://github.com/owncloud/apps/issues/2030:

> Windows Server is not supported in ownCloud 8

from: https://doc.owncloud.org/server/8.0/admin_manual/release_notes.html

**Comment by prepu** [comment]
It is very strange @MorrisJobke because I have installed a clean 8.0.2 version in the same Windows Server 2008 and it is working properly.
I don't know why in the manual says that it doesn't work.
My problem is that the automatic update shows that error.

**Comment by bantu** [comment]
@MorrisJobke I think you probably rather want @nickvergessen
