### ISSUE TITLE
SMB storage backend must not contact server in constructor

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#14837]
### Steps
1. Edit "tests/enable_all.php" and add the "files_external" app
2. Run `./autotest.sh sqlite apps/files_external/tests/mountconfig.php`

### Expected result
Config tests pass

### Actual result
Even though only the constructor of the `\OC\Files\SMB` class is called, it still tries to make a connection:
```
.FF..Can't contact server smbhost. Error NT_STATUS_UNSUCCESSFUL
FCan't contact server smbhost. Error NT_STATUS_UNSUCCESSFUL
(...snip...)
FCan't contact server somehost. Error NT_STATUS_UNSUCCESSFUL
FF
```

### Versions
ownCloud 8.1 git master

After debugging I found that the SMB library from @icewind1991 tries to load the timezone from the server.

@icewind1991 can you fix it to do this lazily ?
External storage classes **must not** attempt any connection from the constructor, because it will cause other (future) problems like when deleting storages, see https://github.com/owncloud/core/pull/11694

**Comment by PVince81** [comment]
It was actually on this branch: https://github.com/owncloud/core/pull/11884

It looks like on master someone removed the name "SMB" to make it work.

Still, would be good to fix this eventually.

**Comment by DeepDiver1975** [comment]
@PVince81 
@Xenopathic recently replaced the smb storage with Test_Mount_Config_Dummy_Storage
https://github.com/owncloud/core/blob/master/apps/files_external/tests/mountconfig.php#L24

To make the unit tests pass properly - just FYI - lazy ctor is still desired
