### ISSUE TITLE
Share dialog shows the same user multiple times

### ISSUE THREAD

**Issue by gig13** [owncloud/core#14835]
**Expected behavior**
When searching for a user in the Share dialog, the list shows unique users.

**Actual behavior**
When searching for a user in the Share dialog, the list shows each user multiple times.

**Steps to reproduce**
Obtaining additional information, but this is related to the upgrade from reference https://github.com/owncloud/core/issues/13957 

**Server configuration**

Operating system: Ubuntu 12.04.5 LTS

Web server: 2.2.22-1ubuntu1.7

Database: MySQL 5.5.41-0ubuntu0.12.04.1

PHP version: 5.3.10-1ubuntu3.15

ownCloud version: 7.0.4 (stable)

Storage backend: Local storage ext4 filesystem - VMware raw disk mapped LUN on SAN

Client configuration:

Client version: Varied - web interface and all sync clients affected

Operating system: Windows, Linux, Mac, Android, iPad

OS language: Varied but mostly English

Installation path of client: default

@blizzz

**Comment by gig13** [comment]
Screenshot available on https://s3.owncloud.com/owncloud/index.php/apps/files/?dir=%2FShared%2Fowncloud%2Fsupport%2Fgithub-issues%2Fcore%2F14835

**Comment by gig13** [comment]
Correction,  It isn't when you enter the name, just when you view who the folder is shared with.

Screenshot and some database information in https://s3.owncloud.com/owncloud/index.php/apps/files/?dir=%2FShared%2Fowncloud%2Fsupport%2Fgithub-issues%2Fcore%2F14835

Related to #https://github.com/owncloud/core/issues/13957

**Comment by DeepDiver1975** [comment]
@gig13 which users are duplicate?

**Comment by gig13** [comment]
@DeepDiver1975 
Look at the screenshot, It lists the file is shared in "APSC 480 with TREVOR LEWIS (TL33)" -- that users is listed 3 times in the same line.

Then it shows "Shared in APSC 480 2014-15 with JAKE ARMSTRONG (8JEA3)" -- he is listed 3 times in the same line.

1. Why are there 2 lines of the Share
2. Why is each user listed 3 times?

**Comment by gig13** [comment]
@DeepDiver1975 @PVince81 
Any thoughts?

**Comment by PVince81** [comment]
also @schiesbn 

@gig13 did you check whether they have the duplicate oc_storage entries situation ? (local::$datadir/$user additionally to home::$user) Many sharing issues are related to that.

But I must say that this situation is a bit new.

It kind of reminds me of another issue where it would display the users from a group instead of the group name but cannot find the ticket any more.

**Comment by PVince81** [comment]
Ah, here it is: https://github.com/owncloud/core/issues/12106

@gig13 was the file/folder shared with that user multiple times, like through multiple groups ? If yes, then it could be the same issue.

**Comment by gig13** [comment]
@PVince81 
There was no group sharing whatsoever. Everything was from one user to another (or many other). I will check if the user shared this multiple times -- very possible since they did the upgrade and may have had the initial share, and then after the patch was applied, shared again?

**Comment by PVince81** [comment]
If there is only one owner and multiple recipients (and no reshares), then this situation shouldn't happen. But who knows... you could check in oc_share whether that user is the recipient multiple times (`select * from oc_share where share_with='theusername'`)

**Comment by gig13** [comment]
@PVince81 
They were only shared once.

**Comment by PVince81** [comment]
Still happening with 7.0.7 or 8.0.5 ?

**Comment by gig13** [comment]
@PVince81 -- This has been closed from some time on my side. To re-open if needed.

**Comment by bedzkowp** [comment]
I can confirm this in 8.0.7 stable.

The situation is as follows:
    /FolderA                - shared with user1
    /FolderA/FolderB  - shared with 21 other users

Share dialog for FolderB shows "Shared in FolderA with user1, user1, ..., user1" - user1 is shown 21 times.

There are no duplicated entries in oc_storages for affected users.
There is no group sharing involved of any kind.
Only one entry in oc_share for this share.

Steps to reproduce:

1. Create folder - FolderA
2. Share FolderA with User1
3. Inside FolderA create FolderB
4. Share FolderB with user2, user3, user4 (or more)
5. Open share dialog for FolderB again.
6. Result: Share dialog for FolderB shows "Shared in FolderA with user1, user1, user1" - number of times user1 is displayed depends on how may times FolderB was shared with other users.


Tested on Firefox, Chromium, Opera, different versions, different OS - no difference.
