### ISSUE TITLE
[LDAP] High count of LDAP binds on LDAP server

### ISSUE THREAD

**Issue by jcfischer** [owncloud/core#14834]
We are investigating LDAP performance on our setup with around 7500 users.

Monitoring the LDAP server, we see around 280 binds per second - almost double of the number of requests our servers are handling at the moment. Investigating the code, we found this line:

https://github.com/owncloud/core/blob/master/apps/user_ldap/lib/access.php#L1128

If I understand this correctly, the app clones the single connection, tries to bind to the LDAP server to see if the password is valid and then immediately binds the main connection again. 

Is this really necessary?

**Comment by blizzz** [comment]
The last bind is most (likely not) necessary, we have an instance where this (and some single LDAP requests) were saved and it works well.

**Comment by jcfischer** [comment]
Ok - I will try to remove it on our servers, and see if we can get a performance improvement going

**Comment by DeepDiver1975** [comment]
@jcfischer I assume the requests are mainly driven by the connected desktop clients?

Any idea which versions of the desktop client are in place?

@blizzz @dragotin this might be related to the php session being closed on webdav requests - we had a similar case a few weeks back ....

**Comment by jcfischer** [comment]
@DeepDiver1975 - yes - web clients are none of our worries. We have a mix of 1.6 and 1.7 clients

I will now disable it on one of the servers for the desktop clients and see what disaster unfolds

**Comment by DeepDiver1975** [comment]
@jcfischer which server version are you running?

**Comment by jcfischer** [comment]
@DeepDiver1975  currently 6.0.6 - upgrade to 7.0.5 in Test and planned for 28.3

**Comment by DeepDiver1975** [comment]
@jcfischer you might want to try to comment this line https://github.com/owncloud/core/blob/stable7/lib/private/connector/sabre/auth.php#L81

**Comment by jcfischer** [comment]
@DeepDiver1975 - I have this

```
                // close the session - right after authentication there is not need to write to the session any more
                session_write_close();
```

so you are saying that I should keep the session open for the webdav accesses?

**Comment by DeepDiver1975** [comment]
> I have this

yes - I posted the wrong link - sorry - https://github.com/owncloud/core/blob/stable6/lib/private/connector/sabre/auth.php#L79

**Comment by DeepDiver1975** [comment]
> so you are saying that I should keep the session open for the webdav accesses?

Yes - this is a wild guess - this did help at a different installation as well. Let's just give it a try :wink:

**Comment by jcfischer** [comment]
ok - I have one server (out of 8 changed) - I probably should look at debug log to see if anything bad happens. But would I see anything?

**Comment by DeepDiver1975** [comment]
> But would I see anything?

I'd expect the LDAP connects to drop

**Comment by jcfischer** [comment]
@DeepDiver1975 same overall amount of bind() operations on the LDAP server. Weird... will investigate some more

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 same overall amount of bind() operations on the LDAP server. Weird... will investigate some more

hmm ... well - it was worth trying.

**Comment by jcfischer** [comment]
I have enabled New Relic monitoring again on the sync servers. Seems like the LDAP server is not the culprit at all (usual suspects come to mind - mainly the many DB operations). Still the double bind() would shave of a millisecond or so from a  request

**Comment by DeepDiver1975** [comment]
> Seems like the LDAP server is not the culprit at all (usual suspects come to mind - mainly the many DB operations).

not really a new finding on an OC6 installation - we did learn a few thing in the past months :speak_no_evil:

**Comment by karlitschek** [comment]
@blizzz @butonic @felixboehm Do we have new information about this?

**Comment by blizzz** [comment]
> If I understand this correctly, the app clones the single connection, tries to bind to the LDAP server to see if the password is valid and then immediately binds the main connection again. 

The extra bind was removed in 8.2.3 and 9.0.
