### ISSUE TITLE
Conversion errors on 8.0.2

### ISSUE THREAD

**Issue by agherzan** [owncloud/core#14841]
### Steps to reproduce
1. nothing specially

### Expected behaviour
No errors

### Actual behaviour
Errors in log

### Server configuration
Fedora21

**Web server:**
apache

**Database:**
mysql

**PHP version:**

**ownCloud version:** (see ownCloud admin page)
8.0.2

**Updated from an older ownCloud or fresh install:**
7.0.X

**List of activated apps:**
nothing/defaults

**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
run: sqlite3 data/owncloud.db
then execute:  select * from oc_appconfig where appid='user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
chrome

**Operating system:**
win/fedora21

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"888a99dc0877f6ca1cdb3853a0844b38","remoteAddr":"130.226.142.243","app":"PHP","message":"Array to string conversion at \/var\/www\/html\/owncloud\/lib\/private\/l10n\/string.php#75","level":3,"time":"2015-03-12T17:23:58+00:00"}
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by RealRancor** [comment]
Might be a dup of: https://github.com/owncloud/core/issues/14714

**Comment by Georg-Git** [comment]
Or a dup of https://github.com/owncloud/updater/issues/109
;-)

OC 8.0.4: Error in Log when opening update center:
"Array to string conversion at ... /lib\/private\/l10n\/string.php#75"

**Comment by jospoortvliet** [comment]
In either case, there are some tips in the forums as well:
https://forum.owncloud.org/viewtopic.php?f=14&t=25789

@agherzan could you try and see if 8.0.5 / 8.1 or any of the tips in the forums fix it?
