### ISSUE TITLE
cron.php must not run in maintenance mode is enabled

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#14843]
### Steps
1. Setup OC with either ajax cron or CLI cron
2. Switch on maintenance mode
3. `update oc_jobs set last_run=0`
4. Run `php cron.php` or `curl http://userid:password/owncloud/cron.php`
5. Check "oc_jobs" table

### Expected result
Cron does NOT run, timestamps left as is

### Actual result
Cron runs through the background jobs and updates the "last_run" field.

This can have nasty consequences especially when doing manual database repairs, there is a risk that the background file watcher kicks in and does some scanning.

### Versions
Observed in OC 6.0.5, likely to exist in OC 7 and OC 8 too

@DeepDiver1975 @karlitschek @MorrisJobke @icewind1991

**Comment by PVince81** [comment]
I also noticed that CLI tools like "./occ files:scan --all" work in maintenance mode, but that should be fine since an admin might want to manually rescan in maintenance mode. However some admins might have setup their own cron jobs to rerun the scanner as a workaround for FS issues (ex: external storage update detection).

**Comment by karlitschek** [comment]
wow,. This can be very bad.

**Comment by DeepDiver1975** [comment]
I'll take care of that ...

**Comment by MorrisJobke** [comment]
> wow,. This can be very bad.

It did very bad :(

**Comment by MorrisJobke** [comment]
Is this file also used for the webcron? Otherwise we need to check for other possible places that could trigger this

**Comment by jvillafanez** [comment]
Checked for stable7 :+1:
