### ISSUE TITLE
Drop class OC_User_HTTP - webdav auth provides the same thing

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#14847]
- [x] https://github.com/owncloud/core/blob/master/lib/private/user/http.php (https://github.com/owncloud/core/pull/14867)

While at it:
- [ ] https://github.com/owncloud/core/blob/master/lib/private/user/dummy.php is for test purpose only -> move to tests/lib
- [x] https://github.com/owncloud/core/blob/master/lib/private/user/example.php is not really needed from my understanding - if at all this shall go into the dev docs (https://github.com/owncloud/core/pull/14880)

**Comment by MorrisJobke** [comment]
@LukasReschke Can you have a look at the other stuff in here? Thanks

**Comment by LukasReschke** [comment]
Well. No idea about our user backends (dummy.php) and from my PoV we would just drop that example file completely :see_no_evil:

**Comment by MorrisJobke** [comment]
Can you create the PR for the drop? It's not necessary, because we already have a Interface to work with

**Comment by LukasReschke** [comment]
![frabz-sir-yes-sir-3d0bcd](https://cloud.githubusercontent.com/assets/878997/6641048/a5fed5e4-c99b-11e4-9e5c-b40bd8a4f635.jpg)

**Comment by LukasReschke** [comment]
https://github.com/owncloud/core/pull/14880

**Comment by MorrisJobke** [comment]
@LukasReschke You made my day :)

**Comment by LukasReschke** [comment]
SIR… THANKS SIR!!!

**Comment by PVince81** [comment]
@LukasReschke the PR https://github.com/owncloud/core/pull/14880 was merged, is there anything left to do ?

**Comment by LukasReschke** [comment]
The dummy backend is still there. - Kill / defer / ignore?

**Comment by cmonteroluque** [comment]
Is it quick? I'd rather we clean it up and close it properly

**Comment by DeepDiver1975** [comment]
> The dummy backend is still there. - Kill / defer / ignore?

:heavy_check_mark: kill

**Comment by LukasReschke** [comment]
:gun: in progress :gun:

**Comment by LukasReschke** [comment]
=> https://github.com/owncloud/core/pull/19233
