### ISSUE TITLE
some bugs

### ISSUE THREAD

**Issue by JasonMe** [owncloud/core#14854]
when invoke app/files/ajax/upload.php  the nginx server will crash down.

**Comment by DeepDiver1975** [comment]
Closing due to insufficient report.

**Comment by RealRancor** [comment]
@JasonMe Just as a reference/hint:

When creating an issue please use the issue template provided here:

https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

as asked in the "guidelines for contributing" (linked in the yellow box when creating a new issue).

Currently your report doesn't contain even the basic infos which ownCloud version you're running.
