### ISSUE TITLE
8.0.2 packages missing in Debian repo

### ISSUE THREAD

**Issue by jbiddy** [owncloud/core#14850]
## Steps to reproduce

1. Have a working 8.0.0-9/8.0.1-1 install on Debian Wheezy
2. [Set up the package manager](http://software.opensuse.org/download/package?project=isv:ownCloud:community&package=owncloud) to point to the Debian Wheezy ownCloud OBS repo
3. Run the upgrade through the package manager (apt-get update, apt-get upgrade)

## Expected Behavior
apt-get should prompt you y/n to install new owncloud packages

## Actual Behavior
apt-get returns "packages already up to date."

## Server Configuration
Debian Wheezy fully updated

web server: apache 2.2.22

database: MariaDB 5.5.42

PHP version: 5.4.36

ownCloud version: 8.0.0-9/8.0.1-1

**Comment by blizzz** [comment]
from OBS repo

cc @jnweiger

**Comment by jnweiger** [comment]
No linux packages for 8.0.2 are released by now. QA approval pending.

**Comment by jbiddy** [comment]
Oh darnet, thanks @blizzz that was the most important part and I forgot it! Fail for first issue report :(

**Comment by deMattin** [comment]
jnweiger commented:
>No linux packages for 8.0.2 are released by now. QA approval pending.

It seems to be a good idea to check reliability of the package update very well.

jbiddy commented:
>Oh darnet, thanks @blizzz that was the most important part and I forgot it! Fail for first issue report :(

I don't think, it's a fail because now we have an answer why there's no repo update... :wink:

**Comment by jnweiger** [comment]
The original plan was to announce Linux packages next week. 
Sorry that tar-ball releases were announced earlier.

**Comment by blizzz** [comment]
@jbiddy no worries, i think @jnweiger would have guessed it either way. Next time ;)

**Comment by jbiddy** [comment]
That is so okay! I am not in a hurry. I've just been getting the update is available message when I go into the WebUI. After ignoring it for a day I finally logged into the server via ssh and tried to do an update. 

Anyway, thanks for letting us know what the situation is so quickly. We appreciate it :)

**Comment by shoeper** [comment]
The webui should then probably query another api to determine if there is a new version.

**Comment by jnweiger** [comment]
Then the webui would also need to know the difference between a tar-ball installation and a deb/rpm installation. 

Anyway, your package manager should tell you when there is an update available.

**Comment by deMattin** [comment]
I think it's usefull to get the information even though you update from repo.
For both installation variants you might have reasons to wait with the update and so the message should appear but hide itself after some seconds to not disturb usage of this account.

**Comment by shoeper** [comment]
@jnweiger the package manager is not the problem. The problem is the message in the web ui.

Furthermore upgrading via package manager is the recommended way but updates come out a week later.

Especially because this was in the announcement email.
> The releases contain a lot of important and security fixes and improvements for ownCloud 8.
> Update is strongly recommended!

It does not make sense to announce security fixes on the one hand and updating repositorys a week later on the other hand.

**Comment by RealRancor** [comment]
If you're using your package manager just disable the update check:

https://github.com/owncloud/core/blob/v8.0.2/config/config.sample.php#L428-L432

as you're getting the update via the package manager. That was something Debian had done with their own packages.

**Comment by deMattin** [comment]
But then we get no infos and checks any more.
As I mentioned above, the information is or ca can be also relevant for user of repositories.
Only a message timeout (per session) should be implemented.

**Comment by RealRancor** [comment]
@deMattin 
It you think this should be implemented then i think you should create a new issue / feature request for this. Thats nothing what should be discussed in an issue about missing packages in a repo. :-)

**Comment by karlitschek** [comment]
Well I think the best option is to provide the packages again at the same time as the tar/zip releases. We have to make this happen again.

**Comment by Akhenaton** [comment]
Yes ! Because actually if you go on the ownCloud.org download page it advertise version 8.0.2 but if you click on "Packages (for auto updates)" you'll get a 8.0.0.9 version.
https://owncloud.org/install/

**Comment by enoch85** [comment]
> Well I think the best option is to provide the packages again at the same time as the tar/zip releases. We have to make this happen again.

Agree with you @karlitschek

**Comment by enoch85** [comment]
Any update here? 8.0.2 has been official for like one week now. @jnweiger

**Comment by boltronics** [comment]
I just had to disable the update warning notification. It was getting really annoying. Still feeling nervous about not having security patches applied. Security issues should not be announced by a project if patched packages are not yet available!

**Comment by jackyes** [comment]
"No linux packages for 8.0.2 are released by now. QA approval pending."

@jnweige does it take more than 5 days? it's the first time i use the auto update package...is  it  normal that it takes so long?

**Comment by deMattin** [comment]
In the past the suse repository updates often have been faster than the official announcements!

**Comment by jackyes** [comment]
Yes! working is better....better late than never

**Comment by jnweiger** [comment]
Sorry for the long delay here. Today I saw that the test results are all good. I hope for a go-ahead today or tomorrow.

@deMattin I fully agree: 'fast and working' is the goal next time!

**Comment by cortopy** [comment]
I'm experiencing all these issues in Ubuntu too. I've opened a bug issue about the messaging system and the inaccuracy in the docs

https://github.com/owncloud/core/issues/14990

Apart from that, looking forward to the update. Thanks @jnweiger !!

**Comment by jnweiger** [comment]
Linux packages for 8.0.2 are public now!

https://software.opensuse.org/download.html?project=isv:ownCloud:community:8.0&package=owncloud
http://download.opensuse.org/repositories/isv:ownCloud:community:8.0
https://build.opensuse.org/package/show/isv:ownCloud:community:8.0/owncloud

(Timing to be improved next time...)

**Comment by etiess** [comment]
@jnweiger what about for Ubuntu? Is http://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_14.10/ not valid anymore?

**Comment by etiess** [comment]
OK, now it works :)

**Comment by jnweiger** [comment]
@etiess the build service was slow with publishing.... thanks for double-checking!

**Comment by enoch85** [comment]
`apt-get update`
`apt-get upgrade`

Doesen't work on Ubuntu 14.04. Did I miss something here?

**Comment by boltronics** [comment]
Thanks @jnweiger for fixing this. Downloading the update now (for Debian).

**Comment by JB1985** [comment]
.htaccess file has the wrong version. Please upload the correct version. Maybe you forgot to replace it after updating?

Who have the new .htaccess? I dont have overwrite it :(

**Comment by RealRancor** [comment]
> Who have the new .htaccess?

Github :)

https://github.com/owncloud/core/blob/v8.0.2/.htaccess

**Comment by JB1985** [comment]
Ok, I have download it from the sources.

**Comment by RealRancor** [comment]
@JB1985 Btw. if the .htaccess file wasn't overwritten during the package update from 8.0.0 to 8.0.2 consider to create a new issue for this.

**Comment by daryltucker** [comment]
I just want to mention, after having upgraded through various means and having installed owncloud through various means, that it is **extermely frustrating** to move to the *recommended method* (ie: System Package Manager), and attempt to update via the *recommended method* (ie: System Package Manager), for ownCloud to refuse connections until a release which is not yet available through my package manager is installed on my system. phew!

Please think about providing checks for various channels, as well as continuing to provide web access before an upgrade (ie: Do not alert about an update that is available on another channel (git/source) that is not yet available on your current channel).

I am also experiencing issues with API access, but I can't imagine ownCloud would refuse API connections if it is out of date... or would it?

I appreciate all that you guys are doing and I hope this comes across as constructive.


Debian 8

**Comment by jnweiger** [comment]
@daryltucker An equivalent of occ upgrade is triggered, when a user visits the web page after the upgrade was installed. The first user to do so is presented with a dialog that should look like this:

<pre>
ownCloud will be updated to version 8.1 beta 2.
Please make sure that the database, the config folder and the data folder have been backed up before proceeding.
[Start update]
To avoid timeouts with larger installations, you can instead run the following command from your installation directory:

./occ upgrade
</pre>

That should get the update going. As an alternative to clicking [Start update], The following shell command should work on ubuntu to perform the update (without adding a shell to www-data):

    sudo -u www-data php /var/www/owncloud/occ upgrade

**Comment by daryltucker** [comment]
Thanks for the clarification and tips, @jnweiger
