### ISSUE TITLE
Add to your owncloud button / function

### ISSUE THREAD

**Issue by pierrejochem** [owncloud/core#14858]
Hi Guy's,

I get this error, when I try to add a file from another cloud:

**Error	files_external	[CURL] Error while making request: Failed to connect to x.x.com port 443: Connection timed out (error code: 7)**

In my config.php is a proxy defined, but I think it is not in use for the curl request.

Can anybody confirm this please or tell me why this is not working.

Thank you in advance

Cheers,

Pierre

**Comment by LukasReschke** [comment]
Probably the proxy is missing there. When does that happen did you say? – I don't quite understand "when I try to add a file from another cloud". There are multiple ways to achieve something like that :)

**Comment by pierrejochem** [comment]
A customer has shared a file with password protection. In that page you have a button on top left side of the page "Add to your owncloud". If I try this I get the error in the owncloud.log and surely nothing is included (downloaded) into our cloud.

**Comment by DeepDiver1975** [comment]
> In my config.php is a proxy defined, but I think it is not in use for the curl request.

@LukasReschke are we sure this actually works? :speak_no_evil:

**Comment by LukasReschke** [comment]
> @LukasReschke are we sure this actually works? :speak_no_evil:

Absolutely not. That's another reason for https://github.com/owncloud/core/pull/14913 where I'm just implementing that.

Currently for example `HTTPHelper::post` does not really consider this – yes – I know we need to fix that also in 8.x and Co. but first things first ;-)

**Comment by PVince81** [comment]
Any update ? I see the linked ticket was closed/merged ?

**Comment by LukasReschke** [comment]
Should be fixed - yes.

**Comment by LukasReschke** [comment]
(in 8.1)

**Comment by pierrejochem** [comment]
Perfect. Thank you and you make a good Job!
