### ISSUE TITLE
Owncloud 7 and 8 shared document editing not working by shared LDAP users

### ISSUE THREAD

**Issue by neazoi** [owncloud/core#14863]
Hello, I have installed Owncloud7 and enabled the LDAP. Users login ok and can share and edit documents at the same time. My data directory is inside the owncloud installation. In the LDAP settings:
User Home Folder Naming Rule is set to uid
Everything works fine with this settings.

However, when I set the User Home Folder Naming Rule to "homeDirectory" (the attribute of my ldap), things are messed up. Let me explain this:
The "homeDirectory" attribute returns the home directory of the LDAP user which is something like /users/m/v/username. If the User Home Folder Naming Rule is set to "homeDirectory", then owncloud creates a folder for each user with the right directory structure, for example /users/m/v/username.
But, when this happens, the documents app is not working correctly. If a user creates a document and shares it with a second user, then the second user cannot edit this document not at the same time, neither when the document owner has closed the file editor.

To test the issue, I have installed ownclowd 8 as well and noticed the same behaviour in owncloud 8.
Also to test the issue, I have made a new clean installation and I have set in the installation wizard, the data directory to be outside the owncloud instance. The same problem happens again.
It seems that is the data directory is outside the owncloud instance, the problem with the documents editing appears.

I am running 
mysql  Ver 15.1 Distrib 5.5.41-MariaDB, for Linux (x86_64) using readline 5.1
And linux fedora
Linux 3.10.0-123.20.1.el7.x86_64 #1 SMP Thu Jan 29 18:05:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by RealRancor** [comment]
Hi,

not absolutely sure but this could be an issue in the documents app itself. So you could re-open in: https://github.com/owncloud/documents/issues

**Comment by neazoi** [comment]
Thank you, I will do so

**Comment by RealRancor** [comment]
Ref to your reported issue in the documents app tracker: https://github.com/owncloud/documents/issues/463

**Comment by PVince81** [comment]
@blizzz

@VicDeo does the documents app use setupFS properly ?

**Comment by blizzz** [comment]
I think it is an issue with Documents. I left a [comment](https://github.com/owncloud/documents/issues/463#issuecomment-85089109) in the corresponding issue and will close this one here therefore. Please follow up at https://github.com/owncloud/documents/issues/463
