### ISSUE TITLE
Update notification links

### ISSUE THREAD

**Issue by mcnesium** [owncloud/core#14866]
![notification bar](https://doc.owncloud.org/server/8.0/admin_manual/_images/updater-1.png)

The notification bar currently links to the [upgrade](https://doc.owncloud.org/server/8.0/admin_manual/maintenance/upgrade.html) instead of the  [update](https://doc.owncloud.org/server/8.0/admin_manual/maintenance/update.html) manual while a minor update.

Also it would be nice if it would link to the updater app in the first part and only in the second part to the manual [here](https://github.com/mcnesium/owncloud-core/blob/master/core/templates/layout.user.php#L39)

**Comment by LukasReschke** [comment]
That URL is served from the apps.owncloud.com server as far I can tell from https://github.com/owncloud/core/blob/c546f0bf46a51dc297be15aa1acbca5ed9a84de9/lib/private/updater.php#L122

cc @karlitschek

**Comment by RealRancor** [comment]
@LukasReschke 
Yupp, seems so: https://apps.owncloud.com/updater.php?version=6x0x2x0x1399658401.0121x1405698422xstablexx2014-06-24T15:11:49+00:00

**Comment by LukasReschke** [comment]
@karlitschek Can we switch to SSL URLs there as well? THX.

**Comment by karlitschek** [comment]
Sure. I think https://api.owncloud.com/... should work fine

**Comment by LukasReschke** [comment]
@karlitschek I meant the ` <url>http://download.owncloud.org/community/owncloud-8.0.2.zip</url>` in https://apps.owncloud.com/updater.php?version=6x0x2x0x1399658401.0121x1405698422xstablexx2014-06-24T15:11:49+00:00 ;)

**Comment by karlitschek** [comment]
ahh. got it. I will do this.

**Comment by Xenopathic** [comment]
@karlitschek This is still an issue, can we fix?

**Comment by PVince81** [comment]
should be fixed now, the update notification app has been rewritten.

If this issue still exists in 9.0.x or 9.1.x, please reopen.
