### ISSUE TITLE
Extend ./occ upgrade description to clarify this won't automatically download and update the latest version

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#14864]
Hi,

some people think that the "./occ upgrade" command will download and install the latest OC update:

https://github.com/owncloud/updater/issues/94
https://forum.owncloud.org/viewtopic.php?f=31&t=27011
(And IIRC also some other questions in either the mailinglist or IRC)

Maybe the text should be extended that this is not the case?

**Comment by PVince81** [comment]
Do you mind submitting a PR ? If needed I can point to you to where the code is.

**Comment by RealRancor** [comment]
If you provide a meaningful text. No clue at the moment how to describe this in some short words.
