### ISSUE TITLE
readdir() expects parameter 1 to be resource, boolean given at

### ISSUE THREAD

**Issue by mbiebl** [owncloud/core#14876]
Version: 7.0.5

Since the latest point update from 7.0.4 to 7.0.5,  my owncloud.log has been spammed with messages like this:

{"app":"PHP","message":"readdir() expects parameter 1 to be resource, boolean given at \/www\/owncloud\/lib\/private\/tempmanager.php#135","level":3,"time":"2015-03-12T15:50:40+00:00"}

Apparently, this has also caused a high system load, so my service provider flagged the file as a virus and removed it.

05:30:43 owncloud_overload.UNOFFICIAL gefunden in /www/owncloud/lib/private/tempmanager.php (chown: XXXXX.XXXXXX | last change: 2015-03-12 15:37:12.803493670 +0100 | last mod.: 2015-03-05 22:28:55.000000000 +0100 | chmod: 644) umbenannt in: /www//owncloud/lib/private/VIRUS_owncloud_overload.UNOFFICIAL_tempmanager.php (chmod: 200)

I made the update yesterday, the owncloud.log file has grown to 35GB of size in that time.

**Comment by RealRancor** [comment]
Hi,

seems like a duplicate of: https://github.com/owncloud/core/issues/14153 where you can find some pointers.

**Comment by mbiebl** [comment]
Why did this slip into a new release when the problem was already known and fixed?

**Comment by RealRancor** [comment]
Thats probably something you should ask in the linked issue. :-)

**Comment by mbiebl** [comment]
Well, this affects the stable7 branch

**Comment by RealRancor** [comment]
Arghhhs, missed that. The reports where from OC8. :-/

**Comment by RealRancor** [comment]
Seems the fix was just backported to stable8 but not to stable7: https://github.com/owncloud/core/pull/13977

**Comment by mbiebl** [comment]
This bug is caused by merging owncloud/temp-handling-stable7

**Comment by mbiebl** [comment]
@RealRancor could the severity of this issue please be bumped? That's a rather nasty one and should be fixed as soon as possible.

**Comment by RealRancor** [comment]
@mbiebl 
See that i have no "Collaborator" nor an "Owner" flag on the right side of my name as the others in here: https://github.com/owncloud/core/pull/13977

**Comment by mbiebl** [comment]
ah, ok. I'm not too familiar with github

**Comment by karlitschek** [comment]
@DeepDiver1975 @icewind1991 What is the status with this? Thanks

**Comment by MorrisJobke** [comment]
fixed with #14902

**Comment by LisaYF** [comment]
not usefull
