### ISSUE TITLE
Unable to upload files larger that 4 GB...

### ISSUE THREAD

**Issue by actyler555** [owncloud/core#14882]
It appears I am experiencing the same issue as described in this post:
https://github.com/owncloud/client/issues/2047

Unfortunately I wasn't able to get a clear answer on what the fix was from reading the conversation. This particular build of ownClould started at 7.0.2 was upgraded to 7.0.5, and then again to 8.0.2.. the issue was present in all versions. Basically as I am uploading I watch the "temp" file from an SSH session, once it gets to 4 GB, a new file is created which counts up to 4 GB (Sometimes 3.9GB) then the browser displays "internal Server error". Any suggestions? I have been over and over the online help with modifying the .htaccess file and php.ini files.

My server:
 Ubuntu Linux 14.04
 Apache2
 MySQL

Tests with Windows 8/7 and Firefox
I also tested with IE10 and didn't even get a progress meter....  Didn't get as far as the upload going to 4 GB.
Large files seem to upload fine via the Windows client, so this is specific to uploading via the web interface and browser.

**Comment by RealRancor** [comment]
Hi,

did you had a look at:

https://doc.owncloud.org/server/8.0/admin_manual/configuration_files/big_file_upload_configuration.html
https://forum.owncloud.org/viewtopic.php?f=17&t=7733

Those could give you some pointers what could be wrong here.

**Comment by DeepDiver1975** [comment]
> I also tested with IE10 and didn't even get a progress meter....

blame M$ for not supporting the required interfaces .... :speak_no_evil:

**Comment by PVince81** [comment]
@actyler555 any more luck with the hints from https://github.com/owncloud/core/issues/14882#issuecomment-79115568 and 8.1.3 ?

**Comment by actyler555** [comment]
Hi there.  I haven't looked into this much since facing the original problem unfortunately.  I did recently upgrade to the most recent build of Owncloud..  I'll give it another shot and let you know.

**Comment by PVince81** [comment]
Did it eventually work ?

If it didn't with ownCloud 8.2.2, feel free to reopen.
