### ISSUE TITLE
Upgrade breaks owncloud 

### ISSUE THREAD

**Issue by benhartwich** [owncloud/core#14885]
Hi,

as already discussed here - the upgrade from 7.0.4 to 8.0.2 breaks owncloud. Error messages: 
 Class OCA\Contacts\Share\Addressbook contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCP\Share_Backend::isShareTypeAllowed) in /var/kunden/data/owncloud/apps/contacts/lib/share/addressbook.php on line 130"

Is this problem solved? How can I fix this? Have I to reinstall owncloud?

**Comment by RealRancor** [comment]
Hi,

please use the search of github to find similar issues: https://github.com/owncloud/core/issues/14852, https://github.com/owncloud/core/issues/14677 where you can find a solution here: https://github.com/owncloud/core/issues/14852#issuecomment-78707046

**Comment by karlitschek** [comment]
@benhartwich How have you updated ownCloud? Manually with the zip files, via rpms, or via the updater?

**Comment by benhartwich** [comment]
Via the Updater.

Am 15.03.2015 um 16:59 schrieb Frank Karlitschek:

**Comment by karlitschek** [comment]
@VicDeo Doesn´t the updater delete/remove the apps? Like Contacts in this case?

**Comment by RealRancor** [comment]
@benhartwich 
Did you got this to work with the suggestions above?

If the calendar and contacts apps are the problematic ones then this should be fixed with https://github.com/owncloud/core/pull/14862

**Comment by benhartwich** [comment]
Yes, the deactivation worked for accessing the web interface again. I´ve uploaded the new version of these apps and enabled it, but it seems that the version 8 is not recognized.

**Comment by VicDeo** [comment]
@karlitschek no, the flow is changed in OC7.  
It's up to core now to decide what apps are compatible.

**Comment by karlitschek** [comment]
@VicDeo Hmm. Not sure this is the best behavior for 7 and 8.0
What do you think @PVince81 ?

**Comment by PVince81** [comment]
For the manual update we said that apps need to be deleted by the admin, so the updater app should probably use the same technique for that and delete these apps.

But I am wondering why an upgrade over the updater would have an exception in calendar/contacts. As far as I understood the updater app just deletes the source code, then extracts the new one, then redirects to the "update" page. Then when the user clicks "Update", third party apps will get disabled.

Does it actually fail earlier than that ?

**Comment by RealRancor** [comment]
@PVince81 
The steps the updater is doing is described in its readme:
https://github.com/owncloud/updater/blob/master/README.md

From what i have read it moves all apps back which could explain this.

**Comment by VicDeo** [comment]
@PVince81  As I said it doesn't touch apps at all. Except the shipped apps that are replaced with updated versions from the downloaded package.

**Comment by DeepDiver1975** [comment]
upgrade procedure starting 8.1 will disable all non-shipped apps - refs https://github.com/owncloud/core/pull/14862
