### ISSUE TITLE
opendir(/tmp): failed to open dir: Permission denied at /.../lib/private/tempmanager.php#134 

### ISSUE THREAD

**Issue by mbiebl** [owncloud/core#14886]
Version: 8.0.2 and 7.0.5

With Version 8.0.2 and 7.0.5 my log is full of those messages:
opendir(/tmp): failed to open dir: Permission denied at /.../lib/private/tempmanager.php#134 

/tmp has the following permissions:
drwxrwxrwt  4 root         root     4096 Mär 13 18:14 tmp

Those look fine.

This owncloud instance is hosted by all-inkl, might this be a php configuration issue?

**Comment by DeepDiver1975** [comment]
Most probably a hosting specific issue.  Afaik they don't allow directory listing on tmp

**Comment by DeepDiver1975** [comment]
@icewind1991 any idea?

**Comment by RealRancor** [comment]
Could an configured open_basedir also causing this?

**Comment by mbiebl** [comment]
@RealRancor In case this question was directed to me, how can I find out and provide you the necessary information?

**Comment by RealRancor** [comment]
You could check your php config with a phpinfo file uploaded to your webspace.

**Comment by mbiebl** [comment]
Directive	| Local Value	| Master Value
open_basedir | /www/htdocs/<uid>/:/tmp:/usr/bin:/www/htdocs/<uid>:/bin:/usr/local/bin:/usr/share/php:/dev/urandom | no value

**Comment by RealRancor** [comment]
Ok, that should be fine then from what i see.

**Comment by DeepDiver1975** [comment]
@mbiebl can you get in touch with the hoster to get this sorted out - :crystal_ball: failed to reveal anything - THX

**Comment by mbiebl** [comment]
@DeepDiver1975: this is the reply
"Der Server-/tmp ist für Sie nicht erreichbar. Sie können sich höchstens einen eigenen Ordner tmp im FTP anlegen und auf diesen verweisen."

Is there a way, to configure an alternate tmp directory?

**Comment by RealRancor** [comment]
@mbiebl 
There is a php.ini setting for this. Check the php manual for something like php tmp dir, php upload dir or similar. This can be also set by a .htaccess for user.ini file.

**Comment by mbiebl** [comment]
@RealRancor I didn't find a .htaccess config setting which was working

**Comment by mbiebl** [comment]
@RealRancor did try to talk to the all-inkl support team, telling them, that letting sys_get_temp_dir() return /tmp is probably not a good idea, when tmp is not fully functional. I also asked them, how I could reconfigure the sys_temp_dir variable to point to something else. The response was a bit smug, imho, shifting the blame to OC:

"In den systemweiten /tmp Ordner können Sie schreiben und Ihre Dateien lesen. Eine Auflistung des Inhaltes des Verzeichnisses /tmp ist aber nicht möglich.

Die Anpassung des /tmp-Pfades sollte erfahrungsgemäß in jedem guten PHP-Skipt per Konfigurationsdatei möglich sein."

**Comment by RealRancor** [comment]
@mbiebl 
Have a look at http://php.net/manual/en/ini.core.php#ini.upload-tmp-dir and try to set this via .htaccess/user.ini to a folder they don't block for reading the content.

**Comment by mbiebl** [comment]
Well, afaics, the code use sys_get_temp_dir(), which means I'd have to set sys_temp_dir. This is a 
PHP_INI_SYSTEM variable [1], so I' can change it from .htaccess. (I do use PHP 5.5)


[1] http://de2.php.net/manual/en/ini.list.php

**Comment by RealRancor** [comment]
@mbiebl 
OC is using the upload-tmp-dir (when set) as temporary dir:

https://github.com/owncloud/core/blob/v8.0.2/lib/base.php#L990-L1009

**Comment by mbiebl** [comment]
Same issue basically, upload_tmp_dir is a PHP_INI_SYSTEM variable, so I can't change it via .htaccess. And I don't have access to the apache config or php.ini

**Comment by DeepDiver1975** [comment]
Looks like we need a way to disable this cleanup routine where we cannot list temp contents.

**Comment by RealRancor** [comment]
Ah, got it. Also havn't noticed that there is already a PR to allowing a custom tmp directory in the config.php: https://github.com/owncloud/core/pull/13031

You could either wait until this PR is merged or modify https://github.com/owncloud/core/blob/v8.0.2/lib/base.php#L996 to your needs and include the custom temp dir.

**Comment by DeepDiver1975** [comment]
> Ah, got it. Also havn't noticed that there is already a PR to allowing a custom tmp directory in the config.php: #13031

thats a solution as well - thx for the reminder

**Comment by mbiebl** [comment]
Thanks for the pointer @DeepDiver1975 . Seeing that I wasn't successful with getting this issue fixed on the hosters side, I appreciate it if I can override that in OC. Looking forward to 8.1.

**Comment by mbiebl** [comment]
Actually, thank you both, @DeepDiver1975 and @RealRancor

**Comment by webwude** [comment]
Same issue here (even with the same provider - all-inkl.com

Looking forward to 8.1 as well :)

**Comment by PVince81** [comment]
Adjusting milestone to matching PR https://github.com/owncloud/core/pull/13031

**Comment by poldixd** [comment]
thanks. i have the same issue with all-inkl.com

**Comment by Bullnados** [comment]
Im also by all-inkl and have the same opendir(/tmp) error.
Im runing OC with mod_php (Apache Module) and PHP 5.5
First i created a tmp-dir in my OC-Folder
/owncloud/tmp
In the .htaccess i added following code:

<IfModule mod_env.c>
  SetEnv htaccessWorking true
	SetEnv TEMP /www/htdocs/xxx/owncloud/tmp
	SetEnv TMP /www/htdocs/xxx/krakadu/owncloud/tmp
	SetEnv TMPDIR /www/htdocs/xxx/owncloud/tmp

Since that the error is gone.

**Comment by poldixd** [comment]
Yes, it works. Thanks!

But if there is an update for owncloud, the .htaccess will be overwritten in the next release.

**Comment by Bullnados** [comment]
Yes, but when you installed Owncloud you must be an explorer and discoverer or you have a problem^^

**Comment by pictibe** [comment]
@Bullnados i have the same all-inkl problem but it won't work for me. I'm new user on owncloud and i copy your code to the head of .htaccess and create the /tmp dir with w-user and 755. 

Can you help me please :(

**Comment by Bullnados** [comment]
Perhaps try that

#php_value session.save_path /www/xxx/owncloud/tmp
<IfModule mod_env.c>
  SetEnv htaccessWorking true
	SetEnv TEMP /www/xxx/owncloudtmp
	SetEnv TMP /www/xxx/owncloud/tmp
	SetEnv TMPDIR /www/xxx/owncloud/tmp
</IfModule>

**Comment by Bullnados** [comment]
I alos found that.
http://de.contaowiki.org/Probleme_beim_Zugriff_auf_/tmp_mit_sys_get_temp_dir%28%29,_tmpfile%28%29_oder_tempnam%28%29

**Comment by pictibe** [comment]
Won't work or did i make a mistake? 

 
![bildschirmfoto 2015-06-05 um 14 37 03](https://cloud.githubusercontent.com/assets/12760325/8006173/87bbd748-0b91-11e5-8418-54ecc87983c5.png)

**Comment by Bullnados** [comment]
Try it to copy it in

<IfModule mod_env.c>
SetEnv htaccessWorking true
SetEnv TEMP /www/xxx/owncloudtmp
SetEnv TMP /www/xxx/owncloud/tmp
SetEnv TMPDIR /www/xxx/owncloud/tmp
</IfModule>

perhaps that block still exists in the .htaccess.

This Line u didnt need:
#php_value session.save_path /www/xxx/owncloud/tmp
 #=comment in php. Sorry for that

**Comment by pictibe** [comment]
I find the block. Log show me error again :( 
Can i give you a ftp access?

**Comment by Bullnados** [comment]
If u want i can try it. But i fear i cant help u but lets try :)

**Comment by pictibe** [comment]
Is it possible to send you a private mail or message?

**Comment by Bullnados** [comment]
Ok
alexander.scholz(at)fau.de

**Comment by RealRancor** [comment]
Maybe start a thread at the forums? Such a discussion is probably also better placed there.

**Comment by Bullnados** [comment]
If u tell me how xD im new to git

**Comment by Bullnados** [comment]
I think u have to set /tmp folder to php-user. Today i get the error again

**Comment by Xandersoft** [comment]
on Version 8.02, ..., 8.04 didn´t work the rules
...
  SetEnv TEMP /www/htdocs/<all-inkl-account>/pathtocloud/tmp
  SetEnv TMP /www/htdocs/<all-inkl-account>/pathtocloud/tmp
  SetEnv TMPDIR /www/htdocs/<all-inkl-account>/pathtocloud/tmp
</IfModule>
other solutions?

**Comment by mevolu** [comment]
I had the same Problem like the others. I'm at all-inkl, too. Here is what I found out (using phpinfo):
At all-inkl you could choose to use php as a apache-module or as cgi (for ex. if you need other php versions). In both versions the variables "upload_tmp_dir", TMP, TEMP, TMPDIR are not set.
If you add the "SetEnv TMP", TEMP, TMPDIR lines to the .htaccess file, they only set the correct variables if you use the apache-module. If you use php-cgi the new following variables get created:
"REDIRECT_TEMP", "REDIRECT_TMP", "REDIRECT_TMPDIR".

So I just added (because I use php-cgi) the following lines in lib/base.php:
after:
```
	function get_temp_dir() {
		if ($temp = ini_get('upload_tmp_dir')) return $temp;
		if ($temp = getenv('TMP')) return $temp;
		if ($temp = getenv('TEMP')) return $temp;
		if ($temp = getenv('TMPDIR')) return $temp;
```
added:
```
		if ($temp = getenv('REDIRECT_TMP')) return $temp;
		if ($temp = getenv('REDIRECT_TEMP')) return $temp;
		if ($temp = getenv('REDIRECT_TMPDIR')) return $temp;
```
my .htaccess:
```
<IfModule mod_env.c>
  SetEnv htaccessWorking true
  SetEnv TEMP /www/htdocs/xxx/owncloud/tmp
  SetEnv TMP /www/htdocs/xxx/owncloud/tmp
  SetEnv TMPDIR /www/htdocs/xxx/owncloud/tmp
</IfModule>
...
```

This seems to get rid of the problem.

**Comment by Bullnados** [comment]
How long the error doesnt come back? I ask cause it seems, that the error appeares periiodicly one time a day. 
So if u are free for 2 or more days it would be rly nice :+1:

**Comment by mevolu** [comment]
I got the error every time the cron.php got called (by browser or per cronjob). Now every time I call cron.php (by browser or per cronjob) there is no more the error message in my log.

**Comment by Bullnados** [comment]
Perfect than we have a workaround for CGI and Modul :+1:

**Comment by farson2003** [comment]
I am also using allinkl.com, with similar problem. 
I believe this here should be continued to the owncloud forum.
Could someone please comment there what the impact and solution might be:
See my last post here: https://forum.owncloud.org/viewtopic.php?f=32&t=29447&p=92462#p92462

Thank you.

**Comment by RealRancor** [comment]
@farson2003 Solution was already posted here: https://github.com/owncloud/core/issues/14886#issuecomment-120727077 and in other comments.

**Comment by farson2003** [comment]
@RealRancor @DeepDiver1975 
What happens if we just ignore that error message. Would that have any negative (long term) impact on the OC installation and use?
Thank you

**Comment by farson2003** [comment]
@mevolu 
I am using owncloud with allinkl.com shared hosting. OC8.1.  running on PHP Version 5.6(als CGI/FPM).

In htaccess after
<IfModule mod_env.c>
  SetEnv htaccessWorking true

I added:
  SetEnv TEMP /www/htdocs/xxx/owncloud/tmp
  SetEnv TMP /www/htdocs/xxx/owncloud/tmp
  SetEnv TMPDIR /www/htdocs/xxx/owncloud/tmp



In the lib/base.php I then tried to find function get_temp_dir() {  but I cannot find that line.

Could someone please give simple instructions in this Owncloud forum post:  https://forum.owncloud.org/viewtopic.php?f=32&t=29447&p=92462#p92462

Thank you

**Comment by Bullnados** [comment]
At the Moment i havent FTP access. But here in git there is get_temp_dir in lib/base.PHP.

**Comment by Allibabba** [comment]
I'm struggling with the same problem. My hoster is STRATO and their CS told me not to grant access to the tmp-directory required by OC. The above mentioned workaround doesn't work for my installation. I still have '...tmp...permission denied...' entries in my logfile (approx. 1 per day).

Which effect does this error really have? Which functionality is affected?

Cheers,
Ralf

**Comment by marschal** [comment]
I'm also hosting at STRATO and having this problem. The best solution I camed across is to change my hoster, what I'll definitely do. 

But during the period you can cancel your conctract **what you can try** is the following: 
- In the `base.php` simply return after these lines your tmp directory like this:

    	function get_temp_dir() {
		if ($temp = ini_get('upload_tmp_dir')) return $temp;
		if ($temp = getenv('TMP')) return $temp;
		if ($temp = getenv('TEMP')) return $temp;
		if ($temp = getenv('TMPDIR')) return $temp;
                return "/home/xxx/www/xxx/htdocs/owncloud/tmp";  // <-- RETURN YOUR TMP HERE

For sure this is **not a solution**!
Way more this is a **very dirty workaround** and I assume it won't survive an update of OC. But it is straight forward and it definitely does what it should: It's returning your local tmp directory.

**Comment by dbieling** [comment]
Still now, I had this problem on the latest OwnCloud Version 9.0.1 and 9.1.0 on All-Inkl. 
opendir(/tmp): failed to open dir: Permission denied at /.../lib/private/tempmanager.php#187

Because the solutions, mentioned here, seems not not work for the current OC-Version, i thought it would be god, to mention the solution, my hoster gave me:

1. Step:
Adding to config/config.php the following line:
'tempdirectory' => '/www/htdocs/yourpathtoyourcloud/tmp/',

2. Step: 
Create a Directory with the name tmp into your owncloud 'root'-directory.
