### ISSUE TITLE
Do not create navigation entries unless required

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#14881]
### Worst Case, aka Current State
Currently apps register their navigation entry with an array in app.php e.g. Activity:
```php
$app = new Application();
$c = $app->getContainer();

$navigationEntry = array(
	'id' => $c->getAppName(),
	'order' => 1,
	'name' => $c->query('ActivityL10N')->t('Activity'),
	'href' => \OC::$server->getURLGenerator()->linkToRoute('activity.Activities.showList'),
	'icon' => \OC::$server->getURLGenerator()->imagePath('activity', 'activity.svg'),
);
\OC::$server->getNavigationManager()->add($navigationEntry);
```

This creates a lot of overhead, although not required:

1. The `Application` of the activity app is created and instanciated
2. The `$app->getContainer()` ....
3. The `$c->query('ActivityL10N')` ....
4. The `\OC::$server->getURLGenerator()` ....

This makes requests that do not need the navigation quite bloated.

I got two ideas to prevent this easily:

---

### 1. Use Closures

Add a `addClosure()` method and register all navigation per closure, so the stuff is only created when required, on `getAll()` of the NavigationManager run the closures and add them:

    ```php
    	public function getAll() {
    		foreach ($this->closureEntries as $c) {
    			$this->add($c());
    		}
    		$this->closureEntries = array();
    		return $this->entries;
    	}
    ```

App Code:
```php
\OC::$server->getNavigationManager()->addClosure(function () use ($c) {
	$app = new Application();
	$c = $app->getContainer();
	$urlGenerator = $c->getServer()->getURLGenerator();

	return [
		'id' => $c->getAppName(),
		'order' => 1,
		'name' => $c->query('ActivityL10N')->t('Activity'),
		'href' => $urlGenerator->linkToRoute('activity.Activities.showList'),
		'icon' => $urlGenerator->imagePath('activity', 'activity.svg'),
	];
});
```
#### Advantage:
+ Code is not executed unless really required
+ Quick (and dirty)

#### Disadvantage:
- We create tones of closures
- Return value of the closure is not specific and needs to be verified?
- Apps need to be updated to help improve the performance

---

### 2. Use a method in the appframework
Add a `registerNavigation()` method to the `\OCP\AppFramework\App` class, and call that for all enabled apps in the `NavigationManager::getAll()` method.

#### Advantage:
+ Code is not executed unless really required
+ Properly structured and making use of the Application class

#### Disadvantage:
- We need a way to create a list of all `\OCP\AppFramework\App` objects, so we can run the `registerNavigation()` method on them (but I think we create all those classes already anyway, and just don't keep them in the appmanager or whereever)
- Apps need to be updated to help improve the performance

---

Both ways are way finer and less ressource wasting then the current implementation.

Opinions? @LukasReschke @Raydiation @DeepDiver1975

**Comment by Raydiation** [comment]
IMHO navigations should be registered in your info.xml since we're duplicating tons of logic that is already present in the info.xml file.

We need:
* id (available in info.xml, not changing ever)
* name (available in the info.xml)
* icon: not going to change ever, can be hard coded or even default to img/icon.svg or img/icon.png by convention which is probably the best solution
* url: could default to the route for appid.page.index
* order: bad solution for a non problem. We should get rid of that and use an internal mechanism to order this, either by alphabeth like the android app drawer does it, installdate or a hardcoded ordering @jancborchardt 

Stuff like the name would sometimes be nice to be translated, but so is the description which inside the info.xml. IMHO we need to enable translation for the info.xml file anyways.

So I'm going to propose the following tag to register the navigation for your app:

```xml
<navigation />
```

The above markup is similar to the following explicit markup
```xml
<navigation>
  <id>calendar</id>
  <name translate="true">Calendar</>
  <route>calendar.page.index</route>
  <icon app="calendar">app.svg</icon>
</navigation>
```

There can be multiple navigation tags. If we need custom behavior you can still use the current API.

Your problem can then be handled entirely internally, the app author has to change virtually nothing and we can optimize things behind the scenes.

**Comment by nickvergessen** [comment]
Well there is this app (bookmarks?) which lets you add links to it. I don't really want to see it writing the info.xml file -.-

But yes, apart from that the info.xml solution sounds like a plan aswell

**Comment by Raydiation** [comment]
@nickvergessen I think the bookmark app does not register additional navigation entries.  But apps that do this can ofc keep using the current API. Apart from that the performance impact in general should be negligible, unless you have some benchmarks that proof that this is a problem.

**Comment by karlitschek** [comment]
There are usecases where we want to hide/show and add navigation entries programmatically. So I think a hard coded definition in info.xml doesn´t work.

**Comment by Raydiation** [comment]
@karlitschek yep, thats totally fine, you can still use the API. But most apps dont need to hide it and can benefit from optimizations behind the scenes

**Comment by karlitschek** [comment]
The drawback with this solution is that we then have two ways to do the same thing which needs to be maintained, tested understood by the developers and longterm supported. Not sure if this is worth the benefit.

**Comment by Raydiation** [comment]
So does the initially proposed solution unless you want to break backwards compatibility ofc. But we should first focus on a real world benchmark to check if this is actually a performance problem. There are probably things that matter more.

**Comment by karlitschek** [comment]
@Raydiation I agree. Somehow I doubt that this calls have a real world performance impact. I think there are WAY bigger things to improve. Hint: Just do some php profiling and SQL logging while doing different webdav calls.

**Comment by nickvergessen** [comment]
Hint I was profiling the ajax calls from activity, and 80% of the time spend is "load apps", because of adding css/js, registering navigation, registering background jobs (1sql on each call, instead of doing it once after install), etc.
But okay was just an idea to reduce app.php which is called for each app on each page although they dont do anything...

**Comment by karlitschek** [comment]
@nickvergessen Ahh ok. :-)  I´m not super sure if this ajax call are the most critical parts of ownCloud. :-)
I think we should focus on webdav performance. (which might actually be impacted by activity because we store one event every time)

**Comment by Raydiation** [comment]
@nickvergessen do you have some data? About what you consider loading apps. Because basically this could all be done with a single Sql statement regardless of how many apps you've got installed that gets app meta info and only executes the things that are really needed. Stuff that could be stored in the db are:
* jobs
* css
* js
* background jobs
* hooks
* navigation
* admin pages

**Comment by nickvergessen** [comment]
> I think we should focus on webdav performance. 

We load all the stuff there aswell and that is exactly the stuff that causes us to be slow. There is no need to execute all that code from many apps, unless we really need that. Yes there might be bigger breaks then navigation, css/js, jobs, ... but they are the most obvious once and should be easy to fix

**Comment by DeepDiver1975** [comment]
> But okay was just an idea to reduce app.php which is called for each app on each page although they dont do anything...

Well - this is the basic reasoning behind having all these register methods on the manager classes using closures - any object will be lazy initialized when needed.

see https://github.com/owncloud/core/blob/master/lib/public/contacts/imanager.php#L144

**Comment by DeepDiver1975** [comment]
> We load all the stuff there aswell and that is exactly the stuff that causes us to be slow.

On webdav we 'only' load apps of type filesystem - but we still for sure execute code which is never needed in the scope of webdav - e.g. js and css

**Comment by DeepDiver1975** [comment]
> e.g. js and css

this is handled in https://github.com/owncloud/core/issues/14666

**Comment by nickvergessen** [comment]
> Well - this is the basic reasoning behind having all these register methods on the manager classes using closures - any object will be lazy initialized when needed.
>
> see https://github.com/owncloud/core/blob/master/lib/public/contacts/imanager.php#L144

I know, that's why I wanted to do that for navigation aswell, but the "straight forward" discussion escalated a bit :see_no_evil:

**Comment by DeepDiver1975** [comment]
> 1. Use Closures

I'm all in for this approach - THX

**Comment by Raydiation** [comment]
As discussed on IRC: :+1: to get this in, adding an additional way to do this using configuration in the info.xml can be added later on.
