### ISSUE TITLE
Please, add unminified version of zxcvbn

### ISSUE THREAD

**Issue by DavidPrevot** [owncloud/core#14888]
Almost two years ago, after zxcvbn got [added to 3rdparty](https://github.com/owncloud/3rdparty/commit/10dc2a63931a740143a82eb1d9dd289c71a01c66), the unminified version was [added too](https://github.com/owncloud/3rdparty/commit/c6eef895c08e43eacb6c08a2b9818353da784cc9).

It would be nice to ship an unminified version (provide source code), and even use it rather than the minified one (it will be minified anyway in assets). Currently, reviewing the zxcvbn code is tough…

**Comment by DeepDiver1975** [comment]
That lib now lives here - still minified: https://github.com/owncloud/core/tree/master/core/vendor/zxcvbn

summoning bower master: @MorrisJobke

**Comment by MorrisJobke** [comment]
zxcvbn is written in coffeescript and got compiled and minified. This is the way they distribute. Should we generate the unminified version ourself? But then bower is useless, because we need to build it (setup the coffeescript compiler)

**Comment by DeepDiver1975** [comment]
@DavidPrevot so basically we would require to add all the coffeescript files to respect open source principles. Somewhat crazy from our perspective. Any idea on how to solve this? THX

**Comment by DavidPrevot** [comment]
Hi,

> @DavidPrevot so basically we would require to add all the coffeescript
> files to respect open source principles.

That sounds saner indeed, but at least providing (or using instead) the
unminified version would be an improvement: the code executed to check
passwords should be at least reviewable (I know it�s big, but hiding it
under minification sounds more like a potential security issue than a DFSG
nitpicking one).

Regards

David

**Comment by DeepDiver1975** [comment]
@DavidPrevot sorry for getting back on this topic that late - I think adding the coffeescript files is not really the way to walk for us from an packaging perspective (as in generating a tar ball people can throw into a web server to fire up ownCloud).

From my understanding you anyhow need to strip off all our js and php libs with the intention to use debian packages. This applies to zxcvbn as well - right?

**Comment by DeepDiver1975** [comment]
moving to backlog - I honestly don't see any proper solutions
