### ISSUE TITLE
OS X 10.10.2

### ISSUE THREAD

**Issue by AustriaXL** [owncloud/core#14895]
Hello,
since the last update, Safari is blank when I try to open owncloud in the browser via the menubar icon.
Therefore I have no access to my settings............
http://i.imgur.com/mhhFDci.jpeg
Regards,
Thomas

**Comment by RealRancor** [comment]
Hi,

please fill out the issue template provided here:

https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

as requested in the "guidelines for contributing" (linked in the yellow box when creating a new issue).

Especially the note about log entries (owncloud.log) are important which could show the reasons of this white page (very likely an internal server error).

**Comment by AustriaXL** [comment]
I will deinstall own cloud from my devices instead filling forms....
