### ISSUE TITLE
Delete icon (trash can) not shown in IE v11 and chrome v41

### ISSUE THREAD

**Issue by LarsHanses** [owncloud/core#14890]
Steps to reproduce

login user
move mouse over delete area

Tell us what should happen
trash can should be shown

Actual behaviour

Tell us what happens instead
just "Delete"-balloon is shown without trash can

Server configuration

Operating system:
Windows 7 x64

Web server:
IIS 7.5 (mime-types for svg and svgz already added)

Database:
MySql

PHP version:
5.5.5

ownCloud version: (see ownCloud admin page)
8.0.0 (stable) amd 8.0.2 (stable)

Updated from an older ownCloud or fresh install:
Fresh install

List of activated apps:
Default, calendar, contacts, tasks, rainloop, bookmarks

Are you using external storage, if yes which one: local/smb/sftp/...
None

Are you using encryption: yes

Client configuration

Browser:
Chrome 43
Internet Explorer 11

Operating system:
Windows 7 x64

![image](https://cloud.githubusercontent.com/assets/11421668/6648181/0623483e-c9d7-11e4-8d0e-329f0db0b159.png)

**Comment by karlitschek** [comment]
@jancborchardt any idea?

**Comment by rullzer** [comment]
This seems to be related to #14891

**Comment by jancborchardt** [comment]
@LarsHanses heya! Can you try with a completely vanilla installation? That is: no apps installed and encryption disabled?

Another point: »IIS 7.5« – do we support that @DeepDiver1975 @karlitschek? Not sure what the status is these days.

**Comment by LarsHanses** [comment]
@rullzer: No I tested the shared Icon with a Windows 8.1 and IE 11.0 Client. Share Icon is displayed. But delete Icon is still not displayed.

**Comment by LarsHanses** [comment]
@jancborchardt Is it enough to deactivate all applications and disable encryption? If I have to setup a fresh vanilla Installation, it is not as easy, because I have already a lot of data stored within the System.

**Comment by jancborchardt** [comment]
But you can just set up a vanilla installation side-by-side? And use SQLite so the existing database doesn't get polluted.
