### ISSUE TITLE
share icon not shown, if file is not already shared

### ISSUE THREAD

**Issue by LarsHanses** [owncloud/core#14891]
Steps to reproduce

login user
move mouse over share area

Tell us what should happen
share icon should be shown

Actual behaviour

Tell us what happens instead
just square with broser "default" image is shown (see attached screenshot)
Note: shared icon is shown (see attached screenshot)

Server configuration

Operating system:
Windows 7 x64

Web server:
IIS 7.5 (mime-types for svg and svgz already added)

Database:
MySql

PHP version:
5.5.5

ownCloud version: (see ownCloud admin page)
8.0.0 (stable) amd 8.0.2 (stable)

Updated from an older ownCloud or fresh install:
Fresh install

List of activated apps:
Default, calendar, contacts, tasks, rainloop, bookmarks

Are you using external storage, if yes which one: local/smb/sftp/...
None

Are you using encryption: yes

Client configuration

Browser:
Chrome 43
Internet Explorer 11

Operating system:
Windows 7 x64

![image](https://cloud.githubusercontent.com/assets/11421668/6648265/2b535968-c9d8-11e4-86f2-8df3e9549dca.png)

**Comment by rullzer** [comment]
Could you check the image location? (right click and then there should be something like copy image location).

Also if you go directly to the image location is it shown?

**Comment by jancborchardt** [comment]
Same as for https://github.com/owncloud/core/issues/14890:

@LarsHanses Can you try with a completely vanilla installation? That is: no apps installed and encryption disabled?

Another point: »IIS 7.5« – do we support that @DeepDiver1975 @karlitschek? Not sure what the status is these days.

**Comment by LarsHanses** [comment]
Tested with a further Client OS: Windows 8.1, Browser: IE 11.0. It works well.
