### ISSUE TITLE
Owncloud on lighttpd

### ISSUE THREAD

**Issue by andreyoit** [owncloud/core#14897]
Hi, i've tried to install owncloud 8.0 on localhost first, in wamp server have some issues with windows permissions, so i've tried to install in my openwrt board, using lighttpd and php5 environment,

the problem is that when i load the index.php file i got these error:

Notice: date_default_timezone_set(): Timezone ID 'UTC' is invalid in /mnt/sda1/www/lib/base.php on line 497

Fatal error: Call to undefined function RandomLib\Source\hash() in /mnt/sda1/www/3rdparty/ircmaxell/random-lib/lib/RandomLib/Source/MicroTime.php on line 72

Fatal error: Call to undefined function hash() in /mnt/sda1/www/lib/private/request.php on line 52

I've tried to delete all file and re upload again 3 times.

i've tried to set timezone to Europe/Rome as my openwrt settings, also set openwrt to UTC default, nothing change, i think is not related.

can help me? thanks a lot, and congratulation for the great software!

**Comment by RealRancor** [comment]
Hi,

which PHP Version is your openwrt running? To me it seems the mandatory hash() is missing which should be shipped in PHP by default:

http://php.net/manual/en/hash.requirements.php

Could be possible that openwrt has disabled this.

**Comment by andreyoit** [comment]
I'm using PHP 5.5.6, in php.ini file is set UTC default timezone, hash is set '--enable-hash=shared'

**Comment by RealRancor** [comment]
--enable-hash=shared is building the hash function as a module so it could be possible that it is disabled. Please check that a phpinfo file uploaded to your webroot contains a "hash support" field with an "enabled" option and also a "date.timezone" field with an Europe/Rome option.

**Comment by andreyoit** [comment]
date/time support 	enabled
"Olson" Timezone Database Version 	0.system
Timezone Database 	internal
Default timezone 	UTC 

I can't find hash support in my phpinfo()

**Comment by RealRancor** [comment]
Then this explains why you're getting this error and you need to find a way to enable this module. Please use either the forum, the user mailinglist or your favorite search engine.

**Comment by andreyoit** [comment]
that work, i needed to install php5-mod-hash, php5-mod-pdo, php5-mod-json that was missing from my system.

now i get 

Fatal error: Call to undefined function OC\Session\session_name() in /mnt/sda1/www/lib/private/session/internal.php on line 20

and even the UTC error again

**Comment by andreyoit** [comment]
Ok, my mistake, i've installed php5-mod-session and now i see the installation page asking me to install some additional modules.

i think is all, now i will try to install these modules and if i get some other errors i will ask for.

thanks a lot!

**Comment by andreyoit** [comment]
The setting of the localization en_US.UTF-8/fr_FR.UTF-8/es_ES.UTF-8/de_DE.UTF-8/ru_RU.UTF-8/pt_BR.UTF-8/it_IT.UTF-8/ja_JP.UTF-8/zh_CN.UTF-8 failed

Install one of the following locations on your system and restart the web server.

**Comment by RealRancor** [comment]
Please note this is an issue tracker for ownCloud where bugs should be reported. The UTC as well as the last posted messages are configuration problems where you should follow my advice here:

https://github.com/owncloud/core/issues/14897#issuecomment-80742726

**Comment by DeepDiver1975** [comment]
> Please use either the forum, the user mailinglist or your favorite search engine.
