### ISSUE TITLE
MySQL over SSL

### ISSUE THREAD

**Issue by NicolasKAROLAK** [owncloud/core#14892]
Hello,

I'm trying to configure owncloud with a remote DB server and I it's not possible to make it working with MySQL/MariaDB over SSL. It's not implemented in ownCloud.

I don't know if there is a simple way to implement it, since it requires to import certificates, etc. May be through an 'advanced' dropdown panel at the installation page ?

Otherwise if you don't think it is wotrh (or a good idea to implement this, it should be specified in the documentation that ownCloud shloud be configured only with local DB server otherwise the remote connection cannot be secure and is not recommended.

Bests regards, and thanks for your awesome work !

**Comment by DeepDiver1975** [comment]
You can specify driver options in the config - see https://github.com/owncloud/core/blob/master/config/config.sample.php#L144

But this will only work after the database has been generated WITHOUT connecting via SSL, because the setup code does not yet respect driver option from the database.

**Comment by DeepDiver1975** [comment]
refs https://github.com/owncloud/core/issues/11788

**Comment by NicolasKAROLAK** [comment]
Oh great ! I will try. Thanks.

**Comment by enoch85** [comment]
Please close this issue if it works out for you @NicolasKAROLAK
