### ISSUE TITLE
500 interal server errors for each PUT and DELETE command

### ISSUE THREAD

**Issue by CptLeeChuck** [owncloud/core#14894]
I have internal server errors with my owncloud installation for each PUT or DELETE request WebDAV (sabre/dav) receives. See my apache access.log excerpt:

    192.168.2.11 - - [14/Mar/2015:08:39:44 +0100] "PROPFIND /remote.php/webdav HTTP/1.1" 207 5272
    192.168.2.11 - - [14/Mar/2015:08:39:44 +0100] "DELETE /remote.php/webdav/Documents/MyDocument.rtf HTTP/1.1" 500 529
    192.168.2.11 - - [14/Mar/2015:08:39:45 +0100] "DELETE /remote.php/webdav/Documents/AnotherDoc.doc HTTP/1.1" 500 529
    192.168.2.11 - - [14/Mar/2015:08:39:45 +0100] "PUT /remote.php/webdav/Documents/TEST1.TXT HTTP/1.1" 500 529
    192.168.2.11 - - [14/Mar/2015:08:39:45 +0100] "PUT /remote.php/webdav/Documents/TEST2.TXT HTTP/1.1" 500 529
    192.168.2.11 - - [14/Mar/2015:08:40:12 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 502
    192.168.2.11 - - [14/Mar/2015:08:40:23 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1270

At the same time I can find this in apaches error.log:

    [Sat Mar 14 08:39:45.350992 2015] [fcgid:warn] [pid 16840:tid 880] (OS 109)Die Pipe wurde beendet.  : [client 192.168.2.11:53446] mod_fcgid: get overlap result error
    [Sat Mar 14 08:39:45.350992 2015] [core:error] [pid 16840:tid 880] [client 192.168.2.11:53446] End of script output before headers: remote.php
    [Sat Mar 14 08:39:45.803398 2015] [fcgid:warn] [pid 16840:tid 880] (OS 109)Die Pipe wurde beendet.  : [client 192.168.2.11:53447] mod_fcgid: get overlap result error
    [Sat Mar 14 08:39:45.803398 2015] [core:error] [pid 16840:tid 880] [client 192.168.2.11:53447] End of script output before headers: remote.php

Also same time owncloud.log has some more details:

    {"reqId":"45d62f7c8057519037a1480b67a1c2de","remoteAddr":"192.168.2.11","app":"user_ldap","message":"No group filter is specified, LDAP group feature will not be used.","level":1,"time":"2015-03-14T07:39:46+00:00","method":"PUT","url":"\/remote.php\/webdav\/Documents\/TEST2.TXT"}
    {"reqId":"45d62f7c8057519037a1480b67a1c2de","remoteAddr":"192.168.2.11","app":"lock","message":"INFO: Write lock requested for F:\/Apache\/owncloud\/Apache24\/htdocs\/data\/testuser\/files\/documents\/test2.txt.octransferid18718.part","level":0,"time":"2015-03-14T07:39:46+00:00","method":"PUT","url":"\/remote.php\/webdav\/Documents\/TEST2.TXT"}
    {"reqId":"45d62f7c8057519037a1480b67a1c2de","remoteAddr":"192.168.2.11","app":"lock","message":"PASS: Write lock succeeded on F:\/Apache\/owncloud\/Apache24\/htdocs\/data\/testuser\/files\/documents\/test2.txt.octransferid18718.part","level":0,"time":"2015-03-14T07:39:46+00:00","method":"PUT","url":"\/remote.php\/webdav\/Documents\/TEST2.TXT"}
    {"reqId":"45d62f7c8057519037a1480b67a1c2de","remoteAddr":"192.168.2.11","app":"lock","message":"INFO: Incrementing lock type 2 count for F:\/Apache\/owncloud\/Apache24\/htdocs\/data\/testuser\/files\/documents\/test2.txt.octransferid18718.part","level":0,"time":"2015-03-14T07:39:46+00:00","method":"PUT","url":"\/remote.php\/webdav\/Documents\/TEST2.TXT"}
    {"reqId":"45d62f7c8057519037a1480b67a1c2de","remoteAddr":"192.168.2.11","app":"lock","message":"INFO: Read lock requested for F:\/Apache\/owncloud\/Apache24\/htdocs\/data\/testuser\/files\/documents\/test2.txt.octransferid18718.part","level":0,"time":"2015-03-14T07:39:47+00:00","method":"PUT","url":"\/remote.php\/webdav\/Documents\/TEST2.TXT"}
    {"reqId":"45d62f7c8057519037a1480b67a1c2de","remoteAddr":"192.168.2.11","app":"lock","message":"PASS: Acquired read lock for F:\/Apache\/owncloud\/Apache24\/htdocs\/data\/testuser\/files\/documents\/test2.txt.octransferid18718.part","level":0,"time":"2015-03-14T07:39:47+00:00","method":"PUT","url":"\/remote.php\/webdav\/Documents\/TEST2.TXT"}
    {"reqId":"45d62f7c8057519037a1480b67a1c2de","remoteAddr":"192.168.2.11","app":"lock","message":"INFO: Incrementing lock type 1 count for F:\/Apache\/owncloud\/Apache24\/htdocs\/data\/testuser\/files\/documents\/test2.txt.octransferid18718.part","level":0,"time":"2015-03-14T07:39:47+00:00","method":"PUT","url":"\/remote.php\/webdav\/Documents\/TEST2.TXT"}
    {"reqId":"45d62f7c8057519037a1480b67a1c2de","remoteAddr":"192.168.2.11","app":"lock","message":"INFO: Write lock requested for F:\/Apache\/owncloud\/Apache24\/htdocs\/data\/testuser\/files\/documents\/test2.txt","level":0,"time":"2015-03-14T07:39:47+00:00","method":"PUT","url":"\/remote.php\/webdav\/Documents\/TEST2.TXT"}
    {"reqId":"45d62f7c8057519037a1480b67a1c2de","remoteAddr":"192.168.2.11","app":"lock","message":"PASS: Write lock succeeded on F:\/Apache\/owncloud\/Apache24\/htdocs\/data\/testuser\/files\/documents\/test2.txt","level":0,"time":"2015-03-14T07:39:47+00:00","method":"PUT","url":"\/remote.php\/webdav\/Documents\/TEST2.TXT"}
    {"reqId":"45d62f7c8057519037a1480b67a1c2de","remoteAddr":"192.168.2.11","app":"lock","message":"INFO: Incrementing lock type 2 count for F:\/Apache\/owncloud\/Apache24\/htdocs\/data\/testuser\/files\/documents\/test2.txt","level":0,"time":"2015-03-14T07:39:47+00:00","method":"PUT","url":"\/remote.php\/webdav\/Documents\/TEST2.TXT"}
    {"reqId":"45d62f7c8057519037a1480b67a1c2de","remoteAddr":"192.168.2.11","app":"PHP","message":"unlink(F:\\Apache\\owncloud\\Apache24\\htdocs\\data\/testuser\/files\/documents\/test2.txt): Permission denied at F:\\Apache\\owncloud\\Apache24\\htdocs\\lib\\private\\files\\storage\\mappedlocal.php#270","level":3,"time":"2015-03-14T07:39:47+00:00","method":"PUT","url":"\/remote.php\/webdav\/Documents\/TEST2.TXT"}
    {"reqId":"d8898b5d419ba2468cf5021413104369","remoteAddr":"192.168.2.11","app":"lock","message":"INFO: Read lock requested for F:\/Apache\/owncloud\/Apache24\/htdocs\/data\/testuser\/files\/documents\/test2.txt","level":0,"time":"2015-03-14T07:40:28+00:00","method":"GET","url":"\/remote.php\/webdav\/Documents\/TEST2.TXT"}
    {"reqId":"d8898b5d419ba2468cf5021413104369","remoteAddr":"192.168.2.11","app":"lock","message":"PASS: Acquired read lock for F:\/Apache\/owncloud\/Apache24\/htdocs\/data\/testuser\/files\/documents\/test2.txt","level":0,"time":"2015-03-14T07:40:28+00:00","method":"GET","url":"\/remote.php\/webdav\/Documents\/TEST2.TXT"}
    {"reqId":"d8898b5d419ba2468cf5021413104369","remoteAddr":"192.168.2.11","app":"lock","message":"INFO: Incrementing lock type 1 count for F:\/Apache\/owncloud\/Apache24\/htdocs\/data\/testuser\/files\/documents\/test2.txt","level":0,"time":"2015-03-14T07:40:28+00:00","method":"GET","url":"\/remote.php\/webdav\/Documents\/TEST2.TXT"}

Based on owncloud.log it looks like it is a "access denied" problem (at least for the unlink message, which I do not understand by the way, as in this case I just added a document), however, the related apache user has full permissions, and I monitored the progress with Sysinternals Process-Monitor, it has not one Access Denied error, just Success, and not found. See screenshot:

![proccess-monitor](https://cloud.githubusercontent.com/assets/11474337/6651735/9535b3c4-ca52-11e4-9bc1-8989a6601c6b.png)

To ensure it's no a permission issue, I tried also to run Apache as local Administrator, which has the same 500 errors. Doing this on command line I noticed PHP crashs for each 500 in the log file:
![php-crash](https://cloud.githubusercontent.com/assets/11474337/6651741/1232abca-ca53-11e4-8b45-70bdcc930a0e.PNG)

If I try to access manually the .../owncloud/remote.php/webdav/ folder it's also ending up in 500 errors if I try to add or delete a file.
However in both cases 0 byte files are created with the correct name, but no data comes into the files.

My setup is: Windows 2k8 R2 with Owncloud 8.0.0.7, Apache 2.4.12 (fresh clean installation with default http.conf) and PHP 5.6.5 via FastCGI with more or less default php.ini.

I'm really lost how I could get this solved out, has anyone a tip what I could try next?

Help is much appreciated.

LC

**Comment by RealRancor** [comment]
Hi,

not quite sure if this is related but where are the ""app":"lock"" messages are coming from? Is this a custom app? Have you tried to disable it?

**Comment by CptLeeChuck** [comment]
Wow I already invested 2 evening in troubleshooting without success.
Based on your hint I disabled the App "File Locking" which is enabled by default.
No more 500 with PUT / DELETE. Thanks so much

**Comment by RealRancor** [comment]
Hi,

sure that this is enabled by default? The "File locking" app has its bugtracker located here:

https://github.com/owncloud/files_locking/issues

You could report this there using the issue template provided here:

https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by CptLeeChuck** [comment]
Hi,

just reinstalled OwnCloud from scratch for productive use. And yes "File locking" is enabled by default.

**Comment by RealRancor** [comment]
Ah, good to know. Wasn't aware that this is enabled by default.

Then i think you really should report an issue like described above.
