### ISSUE TITLE
"Duplicate headers received from server" error

### ISSUE THREAD

**Issue by SpaceIntruder** [owncloud/core#14909]
### Steps to reproduce
1. Upload a mp3 File via Client/Frontend
2. Download mp3 File via Webfrontend

### Expected behaviour
get the download of the mp3 File

### Actual behaviour
Chrome: Click on the file and get Duplicate headers received from server
Firefox: Click on the file and get a Error: Corrupt content
Internet Explorer: download starts and seems to never stop. The test file is about 3 Mb.
Download contains every file of the folder. In my example about 9 hrs music.

### Server configuration
**Operating system**: Ubuntu 14.04 x64

**Web server:** nginx 1.4.6

**Database:** MySQL 5.5.41

**PHP version:** PHP 5.5.9-1ubuntu4.6

**ownCloud version:** 8.0.2 (stable)

**Updated from an older ownCloud or fresh install:** upgraded from owncloud 7

**List of activated apps:** Activity, Deleted files, First Run Wizard, Full Text Search, PDF Viewer, Pictures, Share Files, Text Editor, Updater, Versions, Video Viewer

**The content of config/config.php:**
$CONFIG = array (
  'trusted_domains' => 
  array (
    0 => 'xyz',
  ),
  'memcached_servers' => 
  array (
    0 => 
    array (
      0 => 'localhost',
      1 => 11211,
    ),
  ),
  'datadirectory' => '/var/www/cloud/data',
  'overwrite.cli.url' => 'xyz',
  'dbtype' => 'mysql',
  'version' => '8.0.2.0',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'installed' => true,
  'forcessl' => true,
  'loglevel' => '1',
  'default_language' => 'de_DE',
  'mail_smtpdebug' => true,
  'mail_smtpmode' => 'sendmail',
  'mail_smtphost' => 'localhost',
  'mail_smtpport' => '25',
  'mail_smtptimeout' => 20,
  'mail_from' => 'owncloud',
  'theme' => '',
  'maintenance' => false,
  'logtimezone' => 'Europe/Berlin',
  'log_type' => 'owncloud',
  'log_authfailip' => true,
  'mail_from_address' => 'cloud',
  'forceSSLforSubdomains' => true,
);

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 36.0.1 / Chrome 40 / IE 11

**Operating system:** Windows 8.1

no relevant log entries :(

***Some hints i found:***
if i commenting out the setContentDispositionHeader body of [core/lib/private/response.php](https://github.com/owncloud/core/blob/f1d74e8803efc2d642dd37751eff928ec42b8ec6/lib/private/response.php), i can download the files in FF and Chrome but the download seems to never stop like the behaviour in IE 11. (see above)

Google finds this: https://forum.owncloud.org/viewtopic.php?f=31&t=26680

**Comment by karlitschek** [comment]
@DeepDiver1975 any idea?

**Comment by andriesinfoserv** [comment]
for me at least this is an nginx config issue, disabling "fastcgi_param MOD_X_ACCEL_REDIRECT_ENABLED on;" in /etc/nginx/nginx.conf fixed the problem immediately.

**Comment by SpaceIntruder** [comment]
@andriesinfoserv this solved my issue :)

**Comment by andriesinfoserv** [comment]
well now I think i originally had it like this:
https://doc.owncloud.org/server/8.0/admin_manual/configuration_files/serving_static_files_configuration.html?highlight=xsendfile
 and i want to say it was working with 7 or 8.0 but can't be sure. just tested with the data+internal location block and it still doesn't work when enabled. so i'm guessing it must be a bug but at least this way there's an easy workaround.

**Comment by karlitschek** [comment]
@carlaschroder Is this a documentation issue? Something that we can clarify?

**Comment by LukasReschke** [comment]
This is a known issue, nginx XSendFile support as implemented by ownCloud in version 8 is simply broken.

There is a change request at https://github.com/owncloud/core/pull/15287 (original https://github.com/owncloud/core/pull/14125)  and some documentation discussion at https://github.com/owncloud/documentation/issues/1082
