### ISSUE TITLE
Still not able to enable any apps in 8.0.2

### ISSUE THREAD

**Issue by andre-dierker** [owncloud/core#14906]
Hey,

after upgrade from 7.0.4 to 8.0.2 I'm still not able to enable any apps.
![selection_004](https://cloud.githubusercontent.com/assets/6938843/6658135/4699c3c2-cb60-11e4-8a8a-de71d8695818.png)

see too:
https://github.com/owncloud/core/issues/14185

**Comment by karlitschek** [comment]
hmm. this is the same issue as you reported already, right? Or do i miss something?
Closing as duplicate.
