### ISSUE TITLE
FastCGI error (connectionfactory.php)

### ISSUE THREAD

**Issue by illusive-c** [owncloud/core#14901]
Platform: Rpi 2 
OS:Raspian(Wheezy)
Web Server: Nginx with PhP5, PhP-5-FPM
OwnCloud Version: 8.0.2- Default addons
Database: MYSQL(used to be sqlite. Migrated using occ)

Probem: Nginx log file is filled with this message:

2015/03/15 19:15:18 [error] 2419#0: *2996 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'Doctrine\DBAL\Event\Listeners\MysqlSessionInit' not found in /var/www/owncloud/lib/private/db/connectionfactory.php on line 90" while reading response header from upstream, client: 85.xx.xx.215, server: xxxxxxxx, request: "GET /owncloud/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "xxxxxxxx", referrer: "xxxxxxx"

This is what I get in owncloud web interface:
![image](https://cloud.githubusercontent.com/assets/11490199/6657171/97e6404e-cb4b-11e4-91be-697e37f32bbf.png)

I manually checked connectionfactoy.php file. It's there and permissions are right.I can connect MYSQL database with client. 

Web interface of owncloud works for a few days after reboot. Then it becomes unreachable. Nginex keeps working(there are other sites hosted under www, they work) but  when I try /owncloud there is only a white page. /status.php also unreachable.

**Comment by Xenopathic** [comment]
Please check if you have anything in `3rdparty`, in particular `3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Event/Listeners/MysqlSessionInit.php`.

**Comment by illusive-c** [comment]
https://dl.dropboxusercontent.com/u/24552419/MysqlSessionInit.php

**Comment by illusive-c** [comment]
I installed OC 8.0 with Sqlite. Then updated(automated update) to 8.0.2 and migrated to MYSQL. Btw, I might have found the root of the problem. 

From what I've gathered, MYSQL server goes to "sleep state" when left inactive for a period of time. When I log into OC, it tries to connect to MYSQL and since it takes some time for Mysql to fully "wake up" I'm seeing those errors in the log. That might also explain why it takes 10-15 seconds to show the login page when I first go to my OC servers web page but it goes faster after the initial connection.  I'm also having a new kind of error. Here it is:

![image](https://cloud.githubusercontent.com/assets/11490199/6662108/fbad1e6c-cbbf-11e4-94a7-40b3f50edd14.png)

**Comment by Spacefish** [comment]
Please take a gold look at the availible memory on your Server with free -m . MySQL might get swapped out to the disk and take to long to restore!

**Comment by illusive-c** [comment]
![image](https://cloud.githubusercontent.com/assets/11490199/6671918/5e087e34-cc11-11e4-9f35-58d33c4f2f13.png)

Indeed it appears that I have no free ram, but I always thought this was just the way Debian handles  ram. Since even with a fresh install my ram is pretty much always full...

Is there a way to force OS to never swap MYSQL? Did some googling, couldn't find anything specific to Raspian.

**Comment by Xenopathic** [comment]
@illusive-c Are you still experiencing this problem?

**Comment by illusive-c** [comment]
@Xenopathic  Nope. Updated to 8.0.2 and been using it hassle free for the last month. Thanks and cheers.

**Comment by Xenopathic** [comment]
@illusive-c Your problem was definitely something to do with missing 3rdparty files. Glad to see you got it working though!
