### ISSUE TITLE
sabre-dav-2.1.3

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#14915]
http://sabre.io/blog/2015/sabre-dav-2.1.3-released/

**Comment by PVince81** [comment]
Aha!

**Comment by PVince81** [comment]
3rdparty: https://github.com/owncloud/3rdparty/pull/168

**Comment by PVince81** [comment]
PR: https://github.com/owncloud/core/pull/14949

**Comment by DeepDiver1975** [comment]
> PR: #14949

merged -> close

**Comment by osos** [comment]
http://sabre.io/blog/2015/sabre-dav-2.1.4-released/

And

http://sabre.io/blog/2015/sabredav-3-release/

**Comment by PVince81** [comment]
@osos please make a new ticket.

We're already past feature freeze, so the next sabre update can be done in 8.2
