### ISSUE TITLE
External Files - DropBox - Updated file, modified date not updated

### ISSUE THREAD

**Issue by lyallp** [owncloud/core#14910]
## Steps to reproduce

* Have Dropbox setup as external storage
* Have a file loaded previously, visible
* Upload a new copy of the same file, overwriting
* After successful upload, modified date/time does not change, have to go back to Files and drill back into External Storage

## Expected behaviour

After update, the modified date/time should update, as it does with 'internal' storage, ie, 'seconds ago'

## Actual behaviour

The updated date/time remains unchanged, from the originally uploaded copy of the file
Server configuration

Operating system: Linux (Shared Hosting) x86_64

Web server: Apache 2.2.29

Database: MySQL 5.5.42-cli

PHP version: 5.4.36

ownCloud version: ownCloud 8.0.2 (stable)

Updated from an older ownCloud or fresh install: Updated from 8.0.0

## List of activated apps:

    activity
    bookmarks
    calendar
    contacts
    documents
    external
    files
    files_external
    files_locking
    files_pdfviewer
    files_sharing
    files_texteditor
    files_trashbin
    files_versions
    files_videoviewer
    firstrunwizard
    gallery
    mozilla_sync
    tasks
    templateeditor
    updater

## The content of config/config.php:
<?php
$CONFIG = array (
'installed' => true,
'dbtype' => 'mysql',
'dbname' => 'secret',
'dbuser' => 'secret',
'dbpassword' => 'secret',
'dbhost' => 'localhost',
'dbtableprefix' => 'oc_',
'forcessl' => true,
'theme' => '',
'3rdpartyroot' => '',
'3rdpartyurl' => '',
'blacklisted_files' =>
array (
0 => '.htaccess',
),
'default_language' => 'en',
'overwritehost' => '',
'overwriteprotocol' => '',
'overwritewebroot' => '',
'overwritecondaddr' => '',
'proxy' => '',
'proxyuserpwd' => '',
'defaultapp' => 'calendar',
'knowledgebaseenabled' => true,
'knowledgebaseurl' => 'http://api.apps.owncloud.com/v1',
'appstoreenabled' => false,
'appstoreurl' => 'http://api.apps.owncloud.com/v1',
'apps_paths' =>
array (
0 =>
array (
'path' => '/home/secret/public_html/cloud/apps',
'url' => '/apps',
'writable' => false,
),
),
'mail_smtpdebug' => false,
'mail_smtpmode' => 'php',
'mail_smtphost' => '127.0.0.1',
'mail_smtpport' => '25',
'mail_smtptimeout' => 10,
'mail_smtpauthtype' => 'LOGIN',
'appcodechecker' => '',
'log_type' => 'owncloud',
'logfile' => '/home/secret/owncloud/logs/owncloud.log',
'loglevel' => '2',
'logdateformat' => 'Y-m-d H:i:s',
'logtimezone' => 'Australia/Adelaide',
'log_rotate_size' => '31457280',
'passwordsalt' => 'acc481916f0bd3a46d5257dea0fa2a',
'trashbin_retention_obligation' => 180,
'allow_user_to_change_display_name' => true,
'xframe_restriction' => true,
'custom_csp_policy' => 'default-src \'self\'; script-src \'self\' \'unsafe-eval\'; style-src \'self\' \'unsafe-inline\'; frame-src *; img-src *; font-src \'self\' data:; media-src *',
'customclient_desktop' => '',
'customclient_android' => '',
'customclient_ios' => '',
'remember_login_cookie_lifetime' => 1296000,
'updatechecker' => false,
'writable_appsdir' => true,
'datadirectory' => '/home/secret/owncloud/data',
'version' => '8.0.2.0',
'maxZipInputSize' => '838860800',
'allowZipDownload' => true,
'instanceid' => '514824ae2237a',
'maintenance' => false,
'mail_from_address' => 'OwnCloud-NoReply',
'mail_domain' => 'secret.com',
'trusted_domains' =>
array (
),
'secret' => 'secret',
'forceSSLforSubdomains' => true,
);

Are you using external storage, if yes which one: Via the external storage app, DropBox

Are you using encryption: no

Are you using an external user-backend, if yes which one:No
Client configuration

Mozilla/5.0 (X11; Linux x86_64; rv:36.0) Gecko/20100101 Firefox/36.0

Operating system:
Linux lyalls-pc 3.18.7-gentoo #1 SMP Sun Feb 22 10:29:18 CST 2015 x86_64 Intel(R) Core(TM)2 Quad CPU Q9400 @ 2.66GHz GenuineIntel GNU/Linux
# Logs

**Comment by PVince81** [comment]
@lyallp can you clarify "Upload a new copy" ? Are you uploading that copy through ownCloud or directly to Dropbox (with the Dropbox client) ?

**Comment by lyallp** [comment]
Both original and 'new' copy of the file were uploaded using the OwnCloud UI.
No interaction with via DropBox except through OwnCloud.
I suggest uploading a file, then completely exiting OwnCloud and then re-upload a short time later, just to ensure no 'carry over' between transactions. 
I noticed it with a couple of days separation.

**Comment by PVince81** [comment]
Also observed in 8.1.1.

I see that the file list row gets updated, but it still has the old mtime. When I refresh the browser it seems to rescan the storage and properly re-read the mtime.

The response from "upload.php" also contains the old timestamp.

This is the file cache entry before overwriting:
```
MariaDB [owncloud]> select * from oc_filecache where path like '%test1.txt%';
+--------+---------+-----------+----------------------------------+--------+-----------+----------+----------+------+------------+---------------+-----------+------------------+---------------+-------------+
| fileid | storage | path      | path_hash                        | parent | name      | mimetype | mimepart | size | mtime      | storage_mtime | encrypted | unencrypted_size | etag          | permissions |
+--------+---------+-----------+----------------------------------+--------+-----------+----------+----------+------+------------+---------------+-----------+------------------+---------------+-------------+
|     58 |       5 | test1.txt | b3d5cf638ed2f6a94d6b3c628f946196 |     23 | test1.txt |        4 |        3 |  111 | 1440177506 |    1440177506 |         0 |                0 | 55d75d63ccd0f |          27 |
+--------+---------+-----------+----------------------------------+--------+-----------+----------+----------+------+------------+---------------+-----------+------------------+---------------+-------------+
1 row in set (0.01 sec)
```

After overwrite:
```
MariaDB [owncloud]> select * from oc_filecache where path like '%test1.txt%';
+--------+---------+----------------------------------------------+----------------------------------+--------+-----------------------+----------+----------+------+------------+---------------+-----------+------------------+----------------------------------+-------------+
| fileid | storage | path                                         | path_hash                        | parent | name                  | mimetype | mimepart | size | mtime      | storage_mtime | encrypted | unencrypted_size | etag                             | permissions |
+--------+---------+----------------------------------------------+----------------------------------+--------+-----------------------+----------+----------+------+------------+---------------+-----------+------------------+----------------------------------+-------------+
|     58 |       5 | test1.txt                                    | b3d5cf638ed2f6a94d6b3c628f946196 |     23 | test1.txt             |        4 |        3 |  111 | 1440177506 |    1440177506 |         0 |                0 | 55d75d63ccd0f                    |          27 |
|     63 |       1 | files_versions/dropbox/test1.txt.v1440177506 | 169b00f0c9e744049cbee74656b45341 |     38 | test1.txt.v1440177506 |       19 |        7 |  111 | 1440177589 |    1440177589 |         0 |                0 | 0cc8588818f3e95103f531454f80eb98 |          27 |
+--------+---------+----------------------------------------------+----------------------------------+--------+-----------------------+----------+----------+------+------------+---------------+-----------+------------------+----------------------------------+-------------+
2 rows in set (0.00 sec)
```

Strangely the mtime didn't change at all. (CC @icewind1991)

When doing the same on a local storage, it works.

Needs further research.

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/19831

The local metadata array wasn't cleared after upload.
