### ISSUE TITLE
Change Password in IE9: no entry sets password to "new password"

### ISSUE THREAD

**Issue by Norahy** [owncloud/core#14912]
Info: Tried it with Internet Explorer 9, Firefox and Chrome, only seems to happen in IE.

If you want to change the password on the "personal" site, you can leave the input field for the new password emtpy. If you do so, your password is set to "New password" (or whatever "new password" is in any other language).

As well it would be great to have to confirm the new pw by typing it two times to ensure you have no typo in it?

**Comment by PVince81** [comment]
I think this was discussion before but cannot find the old ticket.

@owncloud/designers

**Comment by MorrisJobke** [comment]
-.- I fixed this for other inputs (the search in the user management)

@jancborchardt Isn't there a proper alternative for those placeholders?

@karlitschek Any rought ETA about end of support for IE8? And when will IE9 end?

**Comment by MorrisJobke** [comment]
> As well it would be great to have to confirm the new pw by typing it two times to ensure you have no typo in it?

That's why we have the "eye icon". Click on it to verify. We discussed this a lot (regarding the move to two inputs) and the we decided for this way.

**Comment by MorrisJobke** [comment]
I will provide a fix later today

**Comment by MorrisJobke** [comment]
Fix is in #14918

**Comment by Norahy** [comment]
Great, thank you very much.
I noticed that the same problem occurs on the login screen if the password field is left emtpy.

**Comment by jancborchardt** [comment]
@Norahy did https://github.com/owncloud/core/pull/14918 fix the issue for you then? Did you test?

**Comment by Norahy** [comment]
Jap, test was successful!

**Comment by MorrisJobke** [comment]
> I noticed that the same problem occurs on the login screen if the password field is left emtpy.

I would like to not add more such hacks. The login field isn't a problem here, because an empty password isn't valid either. And I would rate the usage of "Password" as password as "bad password that never should be used - deal with it" ;)

**Comment by Norahy** [comment]
Alright, got it ;) Thanks!

**Comment by Norahy** [comment]
Hey guys,

I'm really sorry to say that. There is also a problem when sharing a link, if password enforcement is activated. If you click on the checkbox "share link", the password field appears. But in IE9, you are NOT forced to enter a password. After one second you can directly send a mail and set an expiration date. If you then uncheck the checkbox and directly check it again, the password field is filled with "*******". Then you are forced to enter a password.

I know, it's an old version of IE9, but it is still used in the company and the update to a newer version will take a while.

**Comment by MorrisJobke** [comment]
@Norahy I added it to the PR so we don't lose it.
