### ISSUE TITLE
OC 8.0.2 - User count gives wrong number / adds up all group members

### ISSUE THREAD

**Issue by usrbin123** [owncloud/core#14921]
### Steps to reproduce
1. Have multiple user groups and users, which are in more than one group.
2. Log in into ownCloud with non-admin-account, enter user panel

### Expected behaviour
OwnCloud should count all users in the tab "Everyone" correctly, for example with 20, if there are 20 users in the owncloud installation.
The user count in the group tabs should be correct as well.

### Actual behaviour
Owncloud adds up the user counts from every group to the "Everyone" tab, if logged in as normal user with "group manager" rights. If logged in as admin, everything is fine.

I have 20 users in the cloud, and they are organized in approx. 2 groups ("Office" and equivalent "Departement", e.g. "Accountin", "Production" etc.) per user. The "Everyone" tab counts 37 users, which is exactly the count of all group members added up.

### Server configuration
**Operating system:** Linux # 1 SMP Debian 3.2.65-1+deb7u1
**Machine Type:** x86_64
**Web server:** Apache
**Database:** MySQL
**PHP version:** 5.5.21 **PHP Integer Size:** 64 bits
**OwnCloud version:** 8.0.2 (stable)
**Updated from an older ownCloud or fresh install:** Updated from 7.0.2
**List of activated apps:**
- Files Move 0.7.3a

**Comment by karlitschek** [comment]
@MorrisJobke @LukasReschke @blizzz

**Comment by karlitschek** [comment]
@MorrisJobke Didn´t we fixed this lately?

**Comment by MorrisJobke** [comment]
> @MorrisJobke Didn´t we fixed this lately?

I think so: #13740 <- was fixed in 8.1

@usrbin123 Please retest with 8.1 and reopen if this issue still exists. Thanks
