### ISSUE TITLE
Assets not updating reliable if you get app updates from git

### ISSUE THREAD

**Issue by deMattin** [owncloud/core#14937]
If you use [asset-pipeline] (https://github.com/owncloud/documentation/blob/master/admin_manual/configuration_server/js_css_asset_management_configuration.rst) and also get parts of owncloud code (apps) from git, there is the problem, that the assets don't update reliable.
Actually the check for updating the assets only relies on filename with relative path and app version.
But if you get updates with git, there the app version often is not updated with any new update or commit.

So the hash check routine should also regard the filedate (filectime) of the css / js files.

It's in https://github.com/owncloud/core/blob/master/lib/private/templatelayout.php I think.

Could someone please implement this and make a pull request?

**Comment by LukasReschke** [comment]
Not sure if this is something that we want to support officially? – Doing a check on the file time seems like a rather I/O expensive action for me?

**Comment by deMattin** [comment]
Could it then be a possible solution to integrate this (complete) check in the cron job instead?
In this case it would be possible to transfer all of the asset check routines there and no hash check is needed to be perfomed on owncloud call in browser session.

**Comment by oparoz** [comment]
Maybe git apps could be added to an array of apps to be checked so that the cron job does not waste time on non-git apps?

**Comment by DeepDiver1975** [comment]
From my pov it's not the responsibility of core to detect this situation.  App devs have to properly release their apps. In each version change if an app the asset cache will be cleared.

**Comment by oparoz** [comment]
Then that means that users should be discouraged to install any apps from Github if they've enabled pipelining, because that will break their installation. Can probably be solved with some documentation on the page describing how to install it.

**Comment by deMattin** [comment]
I do not agree with DeepDiver. Handling with assets and (its) cache should definitly be the job of the core and it shouldn't rely only on one parameter (app version) that is under control of the app developer.
As it is now, using assets and git together can be a source of weird bugs - although if you document this in some readmes.

But maybe there's another way.
Does the core recognize a git pull of an app somerwhere somehow?
In this case it would be possible to **always** clear the assets for this app if there was a git pull whether there was a change on css or js files or not.

**Comment by LukasReschke** [comment]
Well – if an application changes CSS or JS elements it has to bump the version – and this also applies to Git versions.

If developers don't do that then the Git version is likely not meant to be deployed in a live environment. Case closed from my PoV :see_no_evil:

**Comment by nickvergessen** [comment]
The app author just needs to increase the version in the `appinfo/version` file when changing an asset.

With the increment the old assets are purged. So users can keep using github apps... that should be "fair" enough for everyone and without adding tones of load to the already slow asset loading.

The only other thing I could imagine is a console command for purging the asset cache.

**Comment by oparoz** [comment]
In reality, the version change is going to be forgotten sometimes or too much of a burden and on top of that it triggers an ownCloud update every time, so I agree, that git should be used for development, without pipelining.

I do also miss an occ command to clear that folder though.

**Comment by oparoz** [comment]
https://github.com/owncloud/documentation/pull/957

**Comment by deMattin** [comment]
You are all right:
- Developer **should** encrease version number.
- Cloudadmin **should** have to remember they setted up assets and **should** know the dependencies
- git **should** be used only for development

But whats reality?
- gits are rolling releases and developer don't raise number on every commit (I think, noone does this)
- Cloudadmin **use** git on their productive server and possibly forget or don't know the dependency with assets. They rely on working cache management.
- git apps are and have to be used for apps not only for testing because you don't have another way to get some apps working

So you have to always remember on issue side and if there's a "bug report", that there might be an asset cache, that has not been updated.

For me it's not a problem now, because I know it:
After a git pull I have a look at the 2 asset names of the app in page source and delete them on the server as a default workflow.

But there are too many things someone **"should"** do, that the actual solution ignoring git pulls is a good solution.

**Comment by PVince81** [comment]
Crazy idea, what about using the git hash ? :wink:

**Comment by nickvergessen** [comment]
So in a live enviroment you want to check for all apps, whether .git exists and then track down to the git commit hash, instead of telling app authors to behave correctly, or just have a way to update it correctly?

**Comment by deMattin** [comment]
Yes - a solution not to tell someone something he has to regard amoung countless other things he also has to remember will shurely be a much better solution than hoping, that the developer does behave correctly (whatever this means)!
But certainly "the solution" should not slow down things much.
So it should be found a sort of "trigger" on git pull and so there would not be the afford to create a time consuming hash or check very often.

**Comment by oparoz** [comment]
@nickvergessen - What's the difference between checking info.xml and the git hash? If the script is checking a file anyway, it might as well be the right one, no?

**Comment by DeepDiver1975** [comment]
> Crazy idea, what about using the git hash ? :wink:

so we add git client as core dependency?

**Comment by DeepDiver1975** [comment]
> I do also miss an occ command to clear that folder though.

There is already a repairstep in place - https://github.com/owncloud/core/blob/master/lib/repair/assetcache.php

Running 

```sh
./occ maintenance:repair
```

will do the job

**Comment by DeepDiver1975** [comment]
Using apps from git has more issue than asset caching:
- [ ] apc caching
- [ ] possibly broken database migrations (thinking about an unreleased app dev stage)
- [ ] missing components due to composer install not executed
- [ ] missing components due to bower not invoked
- [ ] missing components due to make * not invoked
- [ ] missing components due to grunt ...
- [ ] missing components due to *whateverdevstep* not executed

**Comment by DeepDiver1975** [comment]
in other words: one better know what to do if using apps from git

**Comment by nickvergessen** [comment]
+ having executable files like travis.yml, tests/ etc. which are potentially dangerous

**Comment by deMattin** [comment]
Perfect solution to close here: :/
Is this ownCloud a piece of software only for developers, experts and anybody knowing anything or a web app for the masses to be mostly installed on small servers and at home or in office?

If you ignore common practice (using git) and common "commiting" (no version update) with words like "you should know, what you do", then you certainly miss your audience.

And to say, that there are other situations, where apps or app developer can break something, is also no argument on this issue or helpful at all.

Useful suggestions are ignored and qashed down with phrases.
I'm a bit disappointed.

**Comment by nickvergessen** [comment]
You can add a [git hook](http://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) for `post-receive` (see bottom of the page) to do the necessary action (`./occ maintenance:repair`) after you git pulled something.

I can't really see the need to slow down stuff even more, just because people try to run dev stuff with performance improvement options.

**Comment by oparoz** [comment]
Nice tip :)

**Comment by deMattin** [comment]
If it only were some "performance improvement options" you would be right.
But sometimes it's the only way to get something to work (e.g. gallery app in 8.0).
Do you have to stay on BUGS until a new official release fixes it a month or more later?

Shorter updates like recently announced are the right step. But issues, that crash functionality you often only get with git or manual patches.

And there is no need to slow something down - maybe there's also the potential to speed it up compared to actual asset cache checks.
**If core checks and hashes an app version file for assets on every call of an app, this is too often already now!**

To clarify: I haven't discussed here for my personal demand! I have no problem to solve this **for me**. I see here a "problem" and dependency, "normal" ownCloud operator might miss or don't see.

But I give up - you are the boss ...

Btw.: Clearing **all** asset cache is a bit too much, I think.
The asset is only generated on first call of the page in browser, so this slows all pages down on first call and I have to call all sides once to generate all assets not to confuse the other users of my cloud with a not responsible page.

**Comment by nickvergessen** [comment]
by "performance improvement options" I was talking about the asset pipelining
