### ISSUE TITLE
OC 8.0.0 Favorites not working properly with php-fpm 5.5.22 on CentOS 6 w/apache 2.4.6

### ISSUE THREAD

**Issue by milprog** [owncloud/core#14930]
### Steps to reproduce
1. use mod_php 5.4.38 and apache 2.2.15 to create a favorite -> works OK
2. Switch server to php-fpm using apache 2.4.6 and php-fpm 5.5.22 from scl and remi repos
3. Create a favorite using php-fpm again

### Expected behaviour
favorite is being created, highlighted on shares page and then appears on favorite page when switching to it

### Actual behaviour
favorite marker (star) appears correctly on shares page, but favorite does not appear on favorite page

#### ownCloud log (data/owncloud.log)
Fatal   index 	Exception: {"Message":"The requested uri(\/index.php\/apps\/files\/api\/v1\/tags\/_$!%3CFavorite%3E!$_\/files) cannot be processed by the script '\/index.php\/apps\/files\/api\/v1\/tags\/_$!\<Favorite\>!$_\/files')","Code":0,"Trace":"#0 \/var\/www\/html\/owncloud\/lib\/base.php(763): OC_Request::getRawPathInfo()\n#1 \/var\/www\/html\/owncloud\/index.php(36): OC::handleRequest()\n#2 {main}","File":"\/var\/www\/html\/owncloud\/lib\/private\/request.php","Line":297} 

#### THOUGHTS
 angle brackets for the "_$!\<Favorite\>!$_" tag are urlencoded in first part of the message, but shown as brackets in second part. But according to issue #7719 the urlencoding should no more be problematic using php-fpm (resolved since 5.5.18 and we use 5.5.22 here). We use exactly the same installation with mod_php, the issue only happens with php-fpm.

Also issue #11779 does not apply, webdav (and everything else AFAIK) works as expected - either with "SetEnvIf Authorization" line before or after the ProxyPassMatch line.

### Server configuration
CentOS 6.6 with httpd2.4.6 from scl and php55-php-fpm 5.5.22-1 from remi repo; repo-based Owncloud install using yum
PostgreSQL 9.4 database on different server
owncloud version 8.0 (stable) taken from http://download.opensuse.org/repositories/isv:/ownCloud:/community/CentOS_CentOS-6/

apache configuration:

    SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
    ProxyPassMatch ^/(.*\.php(/.*)?)$ fcgi://127.0.0.1:9000/var/www/html/owncloud/$1
    DirectoryIndex index.php
    <Directory /var/www/html/owncloud\>
     AllowOverride All
    </Directory\>

System originally installed as owncloud 7, then updated using yum.

Activated Apps: Activity, Deleted Files, First Run Wizard, Mail Template Editor, PDF Viewer, Share Files, Text Editor, Versions

config.php:
 $CONFIG = array (
  'instanceid' => 'xxxxxx',
  'passwordsalt' => 'xxxx',
  'default_language' => 'de_DE',
  'trusted_domains' =>
  array (
    0 => 'www.xxxxxx.ch',
    1 => '192.168.79.21',
    2 => 'cloud.xxxxxxx.ch',
  ),
  'proxy' => '192.168.79.3:3128',
  'datadirectory' => '/var/www/html/owncloud/data',
  'dbtype' => 'pgsql',
  'version' => '8.0.0.7',
  'dbname' => 'owncloud',
  'dbhost' => 'pgsql.hfthun.lan',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'xxxx',
  'installed' => true,
  'logtimezone' => 'Europe/Zurich',
  'mail_from_address' => 'cloud',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'xxxxxx.ch',
  'forcessl' => true,
  'theme' => 'xxxxx',
  'maintenance' => false,
  'log_type' => 'owncloud',
  'log_authfailip' => true,
  'secret' => 'xxx',
  'loglevel' => 1,
 );

 accessed with https:// only, hence 'forcessl' => true

**Comment by PVince81** [comment]
Hmmm, need to double check the code to make sure it's url encoded everywhere.

If it's problematic, we might want to switch to using an extra attribute instead of the internal "funny" tag name.

**Comment by DeepDiver1975** [comment]
@LukasReschke :cough: urlencode :cough:

**Comment by gig13** [comment]
@MorrisJobke 
Do you have this same setup? Do you see this issue?

**Comment by MorrisJobke** [comment]
@gig13 I never experienced such problems. Both my dev and my prod machines uses php-fpm and all works fine there.

**Comment by MorrisJobke** [comment]
> favorite marker (star) appears correctly on shares page

What does "shares page" means? In the view "shared by you" or "shared with you" there is now favorite icon.

**Comment by milprog** [comment]
sorry, i mean the "all files" tab. Left to each folder, a grey star appears on mouseover that turns to yellow when clicked, but the favorite does not "move" to the favorites folder.

**Comment by milprog** [comment]
@MorrisJobke : can you post your apache virtualhost settings? Here are mine - i know this is perhaps more complicated than it should be :

     <VirtualHost *:443>
     <IfModule proxy_module>
      ProxyPassMatch ^/(.*\.php(/.*)?)$ fcgi://127.0.0.1:9000/var/www/html/owncloud/$1
      SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
     </IfModule>

     DirectoryIndex index.php
     SSLEngine on
     SSLCertificateFile /etc/pki/tls/certs/cloud.xxxx.xx.crt
     SSLCACertificateFile /etc/pki/tls/certs/cloud.xxxx.xx.chained.crt
     SSLCertificateKeyFile /etc/pki/tls/certs/cloud.xxxx.xx.key
     SSLUseStapling on
    
     SSLProtocol -all +TLSv1 +TLSv1.2 -SSLv3 -SSLv2
     SSLHonorCipherOrder On
    
     SSLCipherSuite (...)
     ServerAdmin noc@xxxx.xx
     DocumentRoot /var/www/html/owncloud
     ServerName cloud.xxxx.xx
     ServerAlias www.cloud.xxxx.xx
     CustomLog /var/log/httpd/cloud.xxxx.xx/access_log combined
     ErrorLog /var/log/httpd/cloud.xxxx.xx/error_log
    <Directory /var/www/html/owncloud>
    <IfModule mod_fcgid.c> 
    <IfModule mod_setenvif.c>
    <IfModule mod_headers.c>
     SetEnvIfNoCase ^Authorization$ "(.+)" XAUTHORIZATION=$1
     RequestHeader set XAuthorization %{XAUTHORIZATION}e env=XAUTHORIZATION
    </IfModule>
    </IfModule>
    </IfModule>
    <IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteRule .* - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
    RewriteRule ^\.well-known/host-meta /public.php?service=host-meta [QSA,L]
    RewriteRule ^\.well-known/host-meta\.json /public.php?service=host-meta-json [QSA,L]
    RewriteRule ^\.well-known/carddav /remote.php/carddav/ [R]
    RewriteRule ^\.well-known/caldav /remote.php/caldav/ [R]
    RewriteRule ^apps/calendar/caldav\.php remote.php/caldav/ [QSA,L]
    RewriteRule ^apps/contacts/carddav\.php remote.php/carddav/ [QSA,L]
    RewriteRule ^remote/(.*) remote.php [QSA,L]
    RewriteRule ^(build|tests|config|lib|3rdparty|templates)/.* - [R=404,L]
    RewriteRule ^(\.|autotest|occ|issue|indie|db_|console).* - [R=404,L]
    </IfModule>
    <IfModule mod_mime.c>
    AddType image/svg+xml svg svgz
    AddEncoding gzip svgz
    </IfModule>
    <IfModule mod_dir.c>
    DirectoryIndex index.php index.html
    </IfModule>
    AddDefaultCharset utf-8
    Options -Indexes
    <IfModule pagespeed_module>
          ModPagespeed Off
    </IfModule>
    <IfModule mod_headers.c>
    <FilesMatch "\.(css|js)$">
     Header set Cache-Control "max-age=7200, public"
    </FilesMatch>
    </IfModule>
     AllowOverride All
    </Directory>
    <Directory /var/www/html/owncloud/data>
     <ifModule mod_authz_core>
      Require all denied
     </ifModule>
     IndexIgnore *
    </Directory>
    </VirtualHost>

**Comment by gig13** [comment]
@milprog 

Some more debug information in this mail. We are able to reproduce it
with PHP-FPM with the follow apache config:
It seems like things go wrong because this way of using PHP-FPM is
missing some global $_SERVER variables.

SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
ProxyPassMatch ^/(.*\.php(/.*)?)$ fcgi://[::1]:9000/mnt/disk/owncloud/$1

If we change the apache config / PHP-FPM config to the following, it all
works fine:
```
DocumentRoot "/mnt/disk/owncloud"
AcceptPathInfo On

# We create an obfuscated ScriptAlias to a specific dir
# (doesn't really matter which directory as long as it exists)
ScriptAlias /randomstring=/ "/var/run/php-fpm/php56//"

# Declare an Action, name php54-fastcgi that points to php-cgi binary
# within the obfuscated path. This will evaluate to /var/run/php-fpm/php54//php-cgi
# The php-cgi doesn't need to actually be in that directory
Action php56-fastcgi /randomstring=/php-cgi

# Make sure Apache allows us to execute CGI files in that directory
<Directory/var/run/php-fpm/php56//>
Options +ExecCGI
</Directory>

# Make sure Apache allows us to access the made-up path to the php-cgi binary
<Location/randomstring=/php-cgi/>
Require all granted
</Location>

# This is the actual magic:
# Direct all calls for the php-cgi binary to an external FastCGI server.
# The server is defined by a socket which fastcgi_module will connect to.
# Therefore it doesn't really matter where you tell apache where php-cgi is
# as long as it eventually maps to the right socket
FastCGIExternalServer /var/run/php-fpm/php56//php-cgi -socket /var/run/php56-fpm.sock -idle-timeout 61 -pass-header Authorization

DirectoryIndex /index.php

<Directory/mnt/disk/owncloud>
AddHandler php56-fastcgi .php
AllowOverride All
Require all granted
</Directory>
```

The different ways of setting up php-fpm is causing the environment to
handle settings/variables different. I hope this gives you enough
information to make owncloud compatible with both ways of using php-fpm.
The broken setup is the "new" and advised way to setup everything by
apache 2.4, so more customers will run into this problem in the future.

**Comment by bboule** [comment]
@butonic  could you assist @gig13 with this? or is this fixed and can be closed out?

**Comment by milprog** [comment]
this problem still persists with OC 8.1.4-12.1 and  php-fpm 5.6.16-1 on centos-6 (installed from rpm). We still use the same default php-fpm config since everything else works flawlessly.
Adding clear_env = no to the php-fpm config file (here:  /opt/remi/php56/root/etc/php-fpm.d/www.conf ) did not help either.

**Comment by cmonteroluque** [comment]
@bboule would like an update

**Comment by milprog** [comment]
We have had the same issue with oc 8.2. Meanwhile, we have deinstalled apache and installed hiawatha 10.0.3 from ulyaoth repo. Still using the same php-fpm. One thing missing with hiawatha (i.e. its ssl library) is ocsp stapling, and there is no dynamic .htaccess file. But otherwise now everything appears to work properly.

**Comment by MorrisJobke** [comment]
> @butonic could you assist @gig13 with this? or is this fixed and can be closed out?

@gig13 Please reopen this if this is still an issue.
