### ISSUE TITLE
windows 8 with OC8 performance

### ISSUE THREAD

**Issue by joaocamara** [owncloud/core#14939]
I am facing a strong performance issue on windows 8 with OC 8, PHP 5.6 and mysql. It takes up to 5 min to open OC webbrowser than more 5 min to move to calendar .... Is there anyone can help me ?

**Comment by karlitschek** [comment]
there must be something wrong with your setup. is the network fully working? does nslookup localhost work? i recomment to ask this question in the owncloud forum. thanks

**Comment by joaocamara** [comment]
Network is ok
nslookup is ok
I sent a question to owncloud fórum.
thanks
