### ISSUE TITLE
fileglobalgc warning

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#14932]
On stable8, repeateadly (when refreshing a s2s folder as recipient)
```
{"reqId":"8506c8202f1e9ba6a95615452b0e5743","remoteAddr":"127.0.0.1","app":"PHP","message":"unlink() expects parameter 2 to be resource, integer given at \/srv\/www\/htdocs\/owncloud\/lib\/private\/cache\/fileglobalgc.php#51","level":0,"time":"2015-03-16T15:45:58+00:00","method":"GET","url":"\/owncloud\/cron.php"}
```

I compared the code of "fileglobalgc" with master and it's the same, so likely to happen there as well.

I haven't been able to reproduce it, and from reading the code I'm not sure what would return an integer instead of an array.

@icewind1991 any idea ?

**Comment by Xenopathic** [comment]
`array_walk` callback documentation:

> Typically, callback takes on two parameters. The array parameter's value being the first, and the key/index second. 

Looks like we need to wrap `unlink()` in a closure:

```
function($file, $wafflewaffle) {
unlink($file);
}
```

**Comment by chuckingit** [comment]
Hi - i too found some error messages related to fileglobalgc.php after i upgraded from 8.0.0 to 8.0.2 ... initially i posted my issue here -> https://github.com/owncloud/owncloud.org/issues/467#event-257288504 -> but that apparently was wrong place thus reposting here in case my issue is related to the array_walk callback issue mentioned above ..??.. 

background = i updated earlier today from 8.0.0 to 8.0.2 and am getting some php warnings and error messages in log thus not sure if simple or serious and share as fyi ...

the log shows entries like this ->

Only variables should be passed by reference at
/home/my_sever_path_to_owncloud/lib/private/cache/fileglobalgc.php#50 ...

and like this ->
{"reqId":"c869d1c0be34f1658f0de874c6c95735","remoteAddr":"50.187.100.103","app":"PHP","message":"Only variables should be passed by reference at \/home\/my_sever_path_to_owncloud\/lib\/private\/cache\/fileglobalgc.php#50","level":3,"time":"2015-03-17T14:15:38-04:00","method":"GET","url":"\/cron.php"}

cordially, chuck scott
