### ISSUE TITLE
[Suggestion] Log and Activity: when editing or deleting users, add this activity to the log and activity

### ISSUE THREAD

**Issue by Wikinaut** [owncloud/core#14943]
I suggest that user account manipulations by the admin are logged and also shown as "Activity" in the activity pane.

**Comment by jancborchardt** [comment]
@nickvergessen any updates here?

**Comment by nickvergessen** [comment]
admit_audit does the logging
As for activities I don't see much use in creating more admin-only activities...

**Comment by jancborchardt** [comment]
So – do we want this or close? @karlitschek?
