### ISSUE TITLE
Asset pipelining fails with apps directory not under $SERVERROOT

### ISSUE THREAD

**Issue by AdamWill** [owncloud/core#14940]
If you have an apps directory which is not under $SERVERROOT - which has been a perfectly valid OC configuration for years - trying to use asset pipelining will result in OC throwing an exception and entirely failing to work.

The exception thrown is `$filePath is not under the \OC::$SERVERROOT`, found at https://github.com/owncloud/core/blob/master/lib/private/templatelayout.php#L232 (as I write this). I have confirmed that this is what's going on by making the exception actually include the *value* of $filePath, and when I do that, this is the exception I get:

`"\/var\/lib\/owncloud\/apps\/calendar is not under the \\OC::$SERVERROOT"`

That code assumes that all pipeline-able assets will be under $SERVERROOT, but that is not at all a safe assumption, as OC allows for the server admin to configure additional application directories, and allows for these application directories to be outside the server root.

It needs to either cope with assets that are not located inside $SERVERROOT, or except such assets from pipelining.

**Comment by AdamWill** [comment]
https://github.com/owncloud/core/pull/14941 is a PR for this, just my first cut at a fix, may not be correct.

**Comment by MorrisJobke** [comment]
#14941  is merged

**Comment by MorrisJobke** [comment]
@DeepDiver1975 Backport?

**Comment by MorrisJobke** [comment]
I moved the backport-request label to the PR
