### ISSUE TITLE
[Users] Not possible to use the character " ´ " on the full name

### ISSUE THREAD

**Issue by rperezb** [owncloud/core#14955]
### Steps to reproduce
1. Login on ownCloud as admin user
2. Go to users view
3. Create a new user, something as user / user
4. Refresh
5. Modify the full name to : úser
6. Refresh

### Expected behaviour
The full name is kept

### Actual behaviour
The user name is changed to the previous one, in this case, user

### Server configuration
{"installed":"true","version":"7.0.5.2","versionstring":"7.0.5","edition":"enterprise"}

**Operating system**:  Ubuntu

**Web server:** apache

**Database:** mysql

**PHP version:** 5.5.9

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
<?php
$CONFIG = array (
  'appstoreenabled' => false,
  'has_internet_connection' => false,
  'supportedDatabases' =>
  array (
    0 => 'mysql',
    1 => 'pgsql',
    2 => 'oci',
    3 => 'mssql',
  ),
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' =>
  array (
    0 => '',
  ),
  'datadirectory' => '/opt/owncloud/data',
  'overwrite.cli.url' => '',
  'dbtype' => 'mysql',
  'version' => '7.0.5.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => '',
  'dbuser' => 'oc_admin',
  'dbpassword' => '',
  'installed' => true,
  'license-key' => '',
);
``` 
**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** FF and Chrome

**Operating system:** MAC

### Logs
I have not seen any logs related to this

**Comment by LukasReschke** [comment]
Works just fine here. [PHP5-intl](http://php.net/manual/en/book.intl.php) installed?

**Comment by rperezb** [comment]
New step added to reproduced it, thx to @LukasReschke 
### Steps to reproduce
1. Login on ownCloud as admin user
2. Go to users view
3. Create a new user, something as user / user
4. Refresh
5. Modify the full name to : úser
6.- Click with the mouse anywhere
6. Refresh

The key point is that if you click on the enter (instead of with the mouse) the chages are kept

**Comment by blizzz** [comment]
Verified also on stable8, but anything you enter and click away will not be saved, although it looks like it is. Only pressing enter triggers the save. Whether ` is included or not does not matter. It also does not pass on any errors.

Same behaviour with passwords and email addresses. Clearing values (does not make sense for display names, but might for email addresses) does not work, one character need to be entered.

The code base is the same from stable7 to master.

One thing to consider: there is no other possibility to cancel the action (ESC key does not work) and that should be possible. If done by clicking away, the value is not reset however, i.e. also faulty. What is the desired behaviour? Canceling by clicking away, by pressing ESC or both?

@jancborchardt your input is welcome :)

**Comment by DeepDiver1975** [comment]
@blizzz can I ask you to verify if this is working in 8.1? THX

**Comment by blizzz** [comment]
All the same, fix in progress.

**Comment by blizzz** [comment]
Fix in progress but I stumbled across a misbehaviour with Firefox. Whether is is because of jQuery or a browser issue I do not now yet. However I could isolate it from our code and have a demo in a [JS Fiddle](https://jsfiddle.net/xb16r06L/10/). Happens with every jQuery version starting 1.10.1 (did not test earlier ones).

**Comment by blizzz** [comment]
Should be fixed by https://github.com/owncloud/core/pull/17154, please test.

**Comment by MorrisJobke** [comment]
@cmonteroluque @DeepDiver1975 As the fix was proposed for 8.1.1 I will move this to 7.0.8. Also see https://github.com/owncloud/core/pull/17154#issuecomment-115131227

**Comment by cmonteroluque** [comment]
@rperezb please test as per @blizzz above

**Comment by DeepDiver1975** [comment]
out of scope for 7.0.8 - PR is even not yet merged into master

**Comment by cmonteroluque** [comment]
@rperezb confirm that this is resolved?

**Comment by rperezb** [comment]
tested, the changes on the full name are not changed if you confirm them with the "enter".
However, if you confirm them clicking anywhere on the screen are kept.

(@davitol checked it too :monkey_face: https://github.com/owncloud/core/pull/17154#issuecomment-131096395 )

**Comment by DeepDiver1975** [comment]
not fixed -> 7.0.10

**Comment by MorrisJobke** [comment]
@DeepDiver1975 @cmonteroluque Is there a reason to have this in the 7.0.x milestones and move it all the time? We should maybe put it into 8.2 or 9.0 ... I don't see a solution for this in the very near future that is backportable down to stable7 :see_no_evil:

**Comment by cmonteroluque** [comment]
@MorrisJobke Moving it to the backlog. I think this may come back to haunt us but we also need to start using the backlog as the repository of all issues (and not just move forward milestones by default).

**Comment by PVince81** [comment]
Works correctly in 9.1.0beta2.

The special char is saved and also the save is done when hitting enter or blurring the field (clicking outside)
