### ISSUE TITLE
update 8.0.2 was unsuccessful.

### ISSUE THREAD

**Issue by sash85** [owncloud/core#14960]
An exception occurred while executing 'SELECT `fileid` FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ?' with params ["2", "47565767f9fdadf0ef839c373807c795"]: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

**Comment by PVince81** [comment]
Likely to be an environment issue. Not sure when, but sometimes it happens that the MySQL server shuts down.

Please use the issue template to provide info about your environment: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by karlitschek** [comment]
This message means that your mysql server is no longer working. maybe crashed. This is very likely not an owncloud bug.

**Comment by sash85** [comment]
Thank you. :-)
