### ISSUE TITLE
Cleanup Conditional IE html classes / no longer support IE6 & 7 explicitely

### ISSUE THREAD

**Issue by Volker-E** [owncloud/core#14978]
It's time to update the conditional html element classes for targeting IE 6 & IE 7 and just set one for IE8 and below and one for IE9.<br />
Turning in `/core/templates/layout.base.php` from 

    <!DOCTYPE html>
    
    
    
    
    
    <html class="ng-csp" data-placeholder-focus="false" lang="<?php p($_['language']); ?>" >

to 

    <!DOCTYPE html>
    
    
    <html class="ng-csp" data-placeholder-focus="false" lang="<?php p($_['language']); ?>" >
`.ie6`, `.ie7` are not in use at all in core, `.ie` is in use at one place (https://github.com/owncloud/core/blob/64138b0af50dacab4ec8da20406c0131d8dee423/core/css/fixes.css)<br>
The use of `ie` is also a bit counter-intuitive, because it doesn't affect all Internet Explorer versions and at the one place in use at core it's targeting just IE6 and 7. So I would suggest to get rid of that 
too and simply change/kick out that one rule.

HTML5 Boilerplate doesn't use Conditional Classes any more at all. I wouldn't go that far, IE8 has still a marketshare.

See also https://webforscher.wordpress.com/2010/05/20/ie-6-slowing-down-ie-8/ and http://www.paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/

**Comment by DeepDiver1975** [comment]
@jancborchardt THX
