### ISSUE TITLE
Re-share not visible to original owner

### ISSUE THREAD

**Issue by watermark** [owncloud/core#14971]
__Summary:__
User1 shares "folder1" with User2, such that User2 has the ability to re-share that folder.  If User2 re-shares "folder1", User1 is not informed and has no ability to see who it has been re-shared with, or even that it has been re-shared.

This same scenario applies to "share by link".  If two users share the exact same folder, each user will get a unique link.  There may be an argument to keep it this way.

This same scenario applies to external storage.  If User1 and User2 both have share ability of the same external storage folder, User1 cannot see what other users have access to these files.  If User1 shares a folder in the external storage, User2 has no ability to see that.

__Google Drive:__
Google Drive has this functionality.  They handle it by:
* By default, all people with the "edit" permission can change who the folder is shared with.  They can even remove people that the owner shared the folder with.
* The "owner" of the folder can never be removed from the share list
* The "owner" can change the share settings of the folder such that only they can alter the share permissions.
* All people that have the ability to re-share the folder can also see who else it's shared with.  
* People that have access to the folder, but cannot re-share it, cannot see who else the folder is shared with.  They can only see who has shared the folder with them.

__Proposal:__
* Currently, in the shares database, the shares are owned by the user that created the share (uid_owner).  Change this to have the owner be the original owner of that folder.  The share itself will not save any distinction of who actually shared the folder.  The activity log will still record who did the sharing.
* If that user can re-share the folder, they can also change *who* that folder is shared with.  They can add new people as well as remove anyone that it's currently shared with.

On Google Drive, you cannot set who has re-share ability on a user-by-user basis.  OC would be more flexible because of the "can share" checkbox on a per user/group basis.

**Comment by karlitschek** [comment]
@MTRichards @schiesbn what do you think?

**Comment by MTRichards** [comment]
This is related to https://github.com/owncloud/core/issues/9058
I would go with that, and essentially collapse resharing into adding the "reshared" users to the original share list.

**Comment by watermark** [comment]
@MTRichards yep, that ticket sounds great to me
