### ISSUE TITLE
Wrong translation in share-email

### ISSUE THREAD

**Issue by padjon** [owncloud/core#14974]
if you share a folder via email, you get the following text in german:

Hallo,

wir möchten dich nur wissen lassen, dass XXX YYY mit dir geteilt hat.
Ansehen!

Die Freigabe wird am 24. März 2015 ablaufen.

Hallo!
=====

The mail ends with "Hallo!" - i think its because of the wrong translation of "cheers".

**Comment by RealRancor** [comment]
Hi,

translations are handled at https://www.transifex.com/projects/p/owncloud/ where you could submit a correction.
