### ISSUE TITLE
meta charset declaration should be in the first 1024 byte

### ISSUE THREAD

**Issue by Volker-E** [owncloud/core#14979]
The `meta charset` declaration [should be in the first 1024 bytes of the webpage](http://www.w3.org/International/questions/qa-html-encoding-declarations.en). 

Currently it resides below the `<title>` tag, which could in rare cases of overextended titles lead to have put the meta declaration outside of this limit. Therefore I suggest putting the meta charset declaration at top of title tag. I don't know if there are built in limitations to title content length.

Also, in another story on the same line of code, I'd suggest using the short declaration as it doesn't make any difference regarding browser support.

**Comment by jancborchardt** [comment]
Fixed by https://github.com/owncloud/core/pull/14981
