### ISSUE TITLE
Update of an app looks like an update of the ownCloud version - bad UX

### ISSUE THREAD

**Issue by git-marijus** [owncloud/core#14977]
enable files_sharing app from admin panel makes oc want to update again. had to disable it in the db to be able to log in again.

**Comment by LukasReschke** [comment]
Thanks a lot for reporting issues back to us!

We need some more information to properly support you with your issue!

Can I ask you to follow our guidelines for submitting bugs as described here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by git-marijus** [comment]
### Steps to reproduce
1. update to oc 8.0.2
2. enable files_sharing
3. logout 

### Expected behaviour
login visible

### Actual behaviour
oc wants to update again... only allows login after disabling files_sharing in db

### Server configuration
**Operating system**:
linux

**Web server:**
nginx

**Database:**
mysql

**PHP version:**
5.6
**ownCloud version:** (see ownCloud admin page)
8.0.2
**Updated from an older ownCloud or fresh install:**
from 8.0.1
**List of activated apps:**
calendar contact pictures

**The content of config/config.php:**

Insert your config.php content here
(Without the database password, passwordsalt and secret)

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

**Comment by MorrisJobke** [comment]
> oc wants to update again... only allows login after disabling files_sharing in db

This is the update of the files_sharing app. Just proceed with this "update" and then you will be able to login as normal with the enabled files_sharing app.

@jancborchardt @PVince81 @LukasReschke This is a bad UX because for a app update the same screen is shown: "Update your owncloud to version 8.0.2" but it will just do an update of an app to a new version. Is there a way to have a proper text there for those app updates?

**Comment by PVince81** [comment]
Yes, this is something that still needs to be done.

The code needs to find out whether the update requirement was triggered by core or by apps, then adjust the message in the template accordingly.

**Comment by MorrisJobke** [comment]
I renamed the title to match this.

**Comment by git-marijus** [comment]
point is it does nothing after clicking start update...
it just says:
>Updating ownCloud to version 8.0.2, this may take a while.
Please reload the page.

on page reload it shows the update screen again. this loop only breaks if i disable files_sharing in db

**Comment by MorrisJobke** [comment]
That's weird. I just noticed that then the apps and their versions are listed.

**Comment by PVince81** [comment]
@git-marijus did you try clearing your cache and cookies ? (in case it's the CSRF bug)

**Comment by git-marijus** [comment]
clearing cache and cookies does not help.

**Comment by git-marijus** [comment]
can someone reproduce or is this something which explicitely went worng during my update?
if so, where can i look to fix it?

**Comment by PVince81** [comment]
It's only on your side so far.

Maybe check the files_sharing version  in oc_appconfig and compare it with the one in "apps/files_sharing/version". Tell us what version is in the database.

There is some code in the files_sharing app that would run upgrade routines for specific versions.
Maybe some of it fails.

Did you find anything in owncloud.log from the time when running the upgrade of files_sharing ?

**Comment by PVince81** [comment]
another question: how did you upgrade ? Did you use git (as per your nickname :smile:) or did you manually delete the code and replace it with the newer version ?

**Comment by git-marijus** [comment]
i updated manually but i'll consider changing to git :)
files_sharing version in db 0.6.0
files_sharing version on fs 0.6.1
changing the version manually to 0.6.1 in db resolved the problem
thanks for the hint...

btw. files_locking(!) is missing the version file

**Comment by git-marijus** [comment]
fixed for me... can't say why the version did not get updated...

**Comment by MorrisJobke** [comment]
> btw. files_locking(!) is missing the version file

The version is also in the info.xml. But I don't know when which information is used. @PVince81 do you know more?

**Comment by PVince81** [comment]
Yeah, sometimes the version is in info.xml instead of a version file.

@git-marijus better stick with regular updates :smile: 
I see that the files_sharing app was supposed to add a new column when upgrading to 0.6.0: https://github.com/owncloud/core/blob/stable8/apps/files_sharing/appinfo/update.php#L8

Can you check if oc_share_external has a "1" in the "accepted" columns ?
I suspect that something has gone wrong on your setup (and owncloud.log might contain hints)

**Comment by MorrisJobke** [comment]
> @PVince81 do you know more?

https://github.com/owncloud/core/blob/087117d87d97643dec0eb871597160e6ea4f00d8/lib/private/app.php#L582

So if no version file is present the info.xml one is used

**Comment by git-marijus** [comment]
oc_share_external is empty here :(
i did all upgrades from, not sure, maybe 3.something with no issues...

**Comment by DeepDiver1975** [comment]
@PVince81 @MorrisJobke regarding the bad ux - I'd suggest to open a new dedicated issue - objections? THX

**Comment by oparoz** [comment]
@PVince81 @MorrisJobke @DeepDiver1975 - Issue about the UX is here: https://github.com/owncloud/core/issues/16272

**Comment by PVince81** [comment]
@git-marijus did you set "log_query" in your config.php ? It was reported before that it could cause an update loop for some reason

**Comment by PVince81** [comment]
The UX of app updates was improved in 8.2.2, closing.
