### ISSUE TITLE
Make search box work in user management

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#14973]
We currently have an extra search bar in the users management. Instead, the search box in the header should be made to work with that. Just like in the apps management.

cc @butonic @raghunayyar @icewind1991 :)

**Comment by RealRancor** [comment]
Ref: https://github.com/owncloud/core/issues/13606

**Comment by jancborchardt** [comment]
@icewind1991 if you’re up for some fun ;)
cc @blizzz as well

**Comment by jancborchardt** [comment]
@nickvergessen @DeepDiver1975 @blizzz would be good to do this to have search look properly in the user management. Especially after we disabled search for apps where not available https://github.com/owncloud/core/pull/16810

**Comment by jancborchardt** [comment]
Fixed by https://github.com/owncloud/core/pull/18083
