### ISSUE TITLE
404 on 'download' buttons, but only for individual file

### ISSUE THREAD

**Issue by orzel** [owncloud/core#14976]
I've updated from 7.0.2 to 8.0.0 and few days later i also moved the datadir. I'm not sure if the problem occured between those two events as it's only one link that fails, everything else work. I've updated to 8.0.2 since then in the hope of having this bug fixed (but nope).

What's sure, with my current setup (new datadir/ and using 8.0.2).
* i can do almost almost everything i could before, creating/uploading documents/directories, creating share links for anonymous view (this proves that most of the time owncloud knows where to find/put data in the new location).
* the bug is about the 'download' button you get when hovering a filename. It is NOT about clicking on the file name ( -> online view of image or pdf).
* it happens both on the anonymous view you get with the share links and with my own view when authentified.
* if i select several files and use the top "download", it works : i get a zip with all wanted files within. That shows (imho) that permissions are OK and confirms that somehow owncloud knows where to find the files.

The bug was NOT happening with my previous setup (7.0.2 and datadir in another non-default location).

When i click on the download button, i got a 404, but not the usual owncloud 404 page with the blue background. I got a message, dependant on the browser. Google Chrome for exemple only display a very simple "This webpage is not available".

On my web logs, there's this kind of entries:
2015/03/17 20:50:17 [error] 13837#0: *2605 open() "/usr/olocal/web-apps/owncloud/usr/olocal/owncloud/data/orzel/files/Temporaire/testbugdownload/django-logo-negative-square-150.png" failed (2: No such file or directory), client: ::ffff:10.11.3.3, request: "GET /index.php/s/4sjsZ0eZjInj5nI/download?path=%2F&files=django-logo-negative-square-150.png HTTP/1.1", upstream: "fastcgi://unix:/var/sockets/php-fpm.socket"

This is very weird, as the path is actually the concatenation of 
/usr/olocal/web-apps/owncloud : the app dir with the owncloud php files
/usr/olocal/owncloud/data/ : the datadir configured in config/config.php

I really don't understand why this happens, and most importantly why this happens only with individual download buttons, not other buttons.

There's this video where the author mentions the fact that using another location ending with "owncloud/data" is confusing owncloud:
https://youtu.be/Uf--rx3TjTs?t=1m50s
So i tried using somethint very different for 'datadir' : /usr/olocal/aojewfaewf/iauhwueih/
But this doesn't solve the problem. The behaviour is exactly the same : almost everything works but individual download links.

There's a last point worth mentionning : the new location is on another partition  (/usr/olocal/owncloud), which was not the case before. I doubt it really matters, but i try to provide everything that could help solve this bug.

**Comment by LukasReschke** [comment]
Can you fill out the issue template? THX!

https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by orzel** [comment]
### Server configuration

Gentoo ~amd64 up-to-date, nginx-1.7.8, mariadb-10.0.15, php-fpm 5.5.22, owncloud 7.0.2, 8.0.0 and 8.0.2.

**List of activated apps:**
No more activated apps than default.

**The content of config/config.php:**

(edited:)
<?php
$CONFIG = array (
  'instanceid' => 'XXXXXXXXXXXX',
  'passwordsalt' => 'xxxxx',
  'trusted_domains' => 
  array (
    0 => 'owncloud.xxxx',
  ),
  'datadirectory' => '/usr/olocal/owncloud/data/',
  'dbtype' => 'mysql',
  'version' => '8.0.2.0',
  'dbname' => 'owncloud',
  'dbhost' => 'xxxxxx',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxxxxxx',
  'dbpassword' => 'xxxxxxxxxxx',
  'installed' => true,
  'maxZipInputSize' => 0,
  'allowZipDownload' => true,
  'log_authfailip' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'xxxxxxxxxxxxx',
  'mail_domain' => 'xxxx',
  'custom_csp_policy' => 'default-src \'self\'; script-src \'self\' http://stats.xxxxx \'unsafe-inline\' \'unsafe-eval\'; style-src \'self\' \'unsafe-inline\'; frame-src *; img-src *; font-src \'self\' data:; media-src *',
  'maintenance' => false,
  'theme' => '',
  'mail_from_address' => 'xxxx',
  'secret' => 'xxxxx',
  'loglevel' => 0,
);

no external storage, no encryption, no external user backend.

### Client configuration
**Browser:**
tried chromium and firefox from linux, but it doesn't matter here. all my users (mostly windows) have the problem.

### Logs
#### Web server error log
see report

#### ownCloud log (data/owncloud.log)
Nothing worth noting (only "Generating preview", "fixOrientation", thumbnails, and such).


#### Browser log
???

**Comment by DeepDiver1975** [comment]
Could that be an issue with the nginx configuration? Can we see the nginx config? THX

**Comment by orzel** [comment]
@DeepDiver1975 
Very good point ! I've narrowed the problem some more. You mentionning nginx made me think that i forgot to mention i'm using the neat xsendfile stuff. And indeed the bug appearing with download but NOT with zip-creation was a good indicator toward this.

I had followed this:
https://doc.owncloud.org/server/7.0/admin_manual/configuration/xsendfile.html

I'm using xsendfile stuff on other websites on the same server, and it works well. It was working with owncloud 7.0.2 as well, i remember testing this. here's my current xsendfile configuration part in nginx:

    location ^~ /data {
        internal;
        alias /usr/olocal/owncloud/data/;
    }

The path is right (this is where my actual data is).

Now the important point is that if i comment this whole block and the corresponding "fastcgi_param MOD_X_ACCEL_REDIRECT_ENABLED on;", the bug is no more. So this is definitely a bug with xsendfile.

Now, after checking my config file and the documentation, i cannot see anything wrong with my config. This and the fact that it used to work with the previous owncloud (7.0.2) kinda point toward a bug introduced in owncloud 8, don't you think ?
With this previous setting i was using another non-standard datadir path (/usr/olocal/web-data/owncloud). And again ... xsendfile was working.

**Comment by LukasReschke** [comment]
XSendFile is broken on NGINX and ownCloud 8: https://github.com/owncloud/core/pull/14125

If you want the best result (i.e. that what we developer use) stick with Apache or find somebody to review that :see_no_evil:

**Comment by orzel** [comment]
Ok, i've subscribed to this other ticket as well.
I've used and administered apache for very long, but I now consider it an old weird remains of very old age. There's no way me going back to those ugly config files and complex systems.
So i'll keep disabling xsendfile until this is fixed :-/

**Comment by DeepDiver1975** [comment]
I guess we can close this one - broken xsendfile on nginx is already handled in #14125

**Comment by DeepDiver1975** [comment]
Please reopen in case I did miss anything - THX
