### ISSUE TITLE
Self-closing tags ending slash doesn't have purpose and should therefore be removed

### ISSUE THREAD

**Issue by Volker-E** [owncloud/core#14982]
In the `<head>` element of the different template/layout* files are single tag elements with both, no ending slash and ending slashes.

Citing from https://stackoverflow.com/questions/3558119/are-self-closing-tags-valid-in-html5 :
> In HTML5, `<foo />` means `<foo>`, the start tag. It is not a "self-closing tag". Instead, certain elements are designated as having no end tag, for example `<br>`. These are collectively called void elements. *The slash is just syntactic sugar for people who are addicted to XML*. Using the slash in a non-void element tag is invalid, but browsers parse it as the start tag anyway, leading to a mismatch in end tags.

<small>Accentuation by issue author</small>

So for example 

    <link rel="stylesheet" href="<?php print_unescaped($cssfile); ?>" type="text/css" media="screen" />

should become

    <link rel="stylesheet" href="<?php print_unescaped($cssfile); ?>" type="text/css" media="screen">

**Comment by Raydiation** [comment]
@Volker-E feel free to submit a PR

**Comment by jancborchardt** [comment]
Fixed by https://github.com/owncloud/core/pull/14981
