### ISSUE TITLE
[OC8] File creation from app fail silently if default quota is set to 0

### ISSUE THREAD

**Issue by jmaciasportela** [owncloud/core#14988]
This failure has been detected with ownbrander app. This app create some files from templates and store it on the user data folder.

### Steps to reproduce
1. Set default quota to 0
2. Assing default quota to a test user
3. Set up ownbrander, and generate new branding 

### Expected behaviour
View a notification, with an error because of quota limits, or view a log with an exception when file_put_contents return false.

### Actual behaviour
Silent failure. Files are not created from templates. 

### Server configuration
**Operating system:**  openSuse
**Web server:** Apache
**Database:** MySQL
**ownCloud version:** 7.0.5

When ownbrander try to create files, file_put_contents from lib/private/files/storage/wrapper/quota.php return false, because method free_space from the same file, return 0.

    public function file_put_contents($path, $data) {
       
        $free = $this->free_space('');   
        if ($free < 0 or strlen($data) < $free) {
            return $this->storage->file_put_contents($path, $data);
        } else {
            return false;
        }
    }
If this method return false, should be propagated correctly or use exceptions instead booleans.

**Comment by DeepDiver1975** [comment]
@icewind1991

**Comment by DeepDiver1975** [comment]
I'd consider this as 'works-as-designed' - our implementation follows the php file functions - see http://php.net/manual/en/function.file-put-contents.php#refsect1-function.file-put-contents-returnvalues

In case of error we shall return false - it's within the responsibility of the caller to handle a return value of false
