### ISSUE TITLE
Remove unnecessary `type` attributes from link stylesheet and script tags

### ISSUE THREAD

**Issue by Volker-E** [owncloud/core#14984]
In HTML5 `type="text/javascript"` and `type="text/css"` are optional/useless for the default assumed types.
See http://dev.w3.org/html5/spec-preview/Overview.html#the-link-element and http://stackoverflow.com/a/14323399/1696030
Remove the redundant attributes!

**Comment by jancborchardt** [comment]
Fixed by https://github.com/owncloud/core/pull/14981
