### ISSUE TITLE
can not share calendars after update to 8.0

### ISSUE THREAD

**Issue by fbassas** [owncloud/core#14991]
Running on ubuntu 14.04
Upgrade made using "apt-get upgrade owncloud"
Disabled "shorty" app cause not supported by OC 8.0
Firs I had problems to access existing calendars until I applied #14275 fix
apache 2.4.7
php 5.5.9

Problem description: 
-I create a calendar with user us1 and share it among group gr1
-I copy share link, which is:https://aaaaaaaaaaaa.aaaa.aa/owncloud/remote.php/caldav/calendars/d0df6336-67f0-102b-9dfb-ed8d470aa0af/calendarisb
-with user us2, which belongs to group gr1, I use thunderbird with  lightning 3.3 an try to add the calendar using the share link. us2 type his owncloud username info but calendar is not added like he have not permission.
-No special log appear on owncloud.log
-On access.log I get:"PROPFIND /owncloud/remote.php/caldav/calendars/d0df6336-67f0-102b-9dfb-ed8d470aa0af/calendarisb/ HTTP/1.1" 404 5233 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Thunderbird/31.5.0 Lightning/3.3.2"

It's the same error that it appeared before applying #14275 fix when trying to access a personal calendar.
Any ideas?
Thanks for your help.

**Comment by LukasReschke** [comment]
Please reopen at https://github.com/owncloud/calendar
