### ISSUE TITLE
Update from 7.0.4 to 8.0.2 takes forever

### ISSUE THREAD

**Issue by jonlapointe** [owncloud/core#14996]
Hi,

I tried to update three days ago from OC7.0.4 to OC8.0.2 via the openSuse method on a Debian 7 server.

On the home page I have the "This ownCloud instance is currently being updated, which may take a while." message. The "While" is now three days. Is it normal ? I have around 60Gb of encrypted data. 

In the config file, it still shows version 7.0.4

I tried to turn off maintenance mode, changed nothing. When I try to restart apache, it tells me there are open files.

Anybody has a clue on what to do ? 
Thanks a lot

**Comment by RealRancor** [comment]
Hi,

it is known that the upgrade with encrypted data takes a long time. That should be fixed in 8.0.3.

You can also try to set the maintenance option in your config.php to false as described in the upgrade manual.

**Comment by jonlapointe** [comment]
Maintenance option is set to false in the config. It doesn't change a thing.

**Comment by RealRancor** [comment]
Are you really sure? Picked the wrong config.php? The initial posted message is only shown if maintenance is set to true.

**Comment by DeepDiver1975** [comment]
@jonlapointe try to upgrade using the console client - maybe this helps

**Comment by jonlapointe** [comment]
Just checked back the config.php file in var/www/owncloud/config and maintenance is set to false.
There is a change though, version is set to 8.0.0.x ! I guess it's in progress as it wasn't set to 8 earlier.

**Comment by DeepDiver1975** [comment]
@jonlapointe I assume you have enryption enabled - there is one migration step which is rather time consuming - and therefore using the console is recommended.

**Comment by jonlapointe** [comment]
@DeepDiver1975 Indeed, I have encryption enabled. 
As the upgrade is already taking place, would it be a problem if I relaunch it from the console ??

**Comment by DeepDiver1975** [comment]
> As the upgrade is already taking place, would it be a problem if I relaunch it from the console ??

you can execute the key migration explicitly:

```sh
$ ./occ help encryption:migrate-keys
Usage:
 encryption:migrate-keys [user_id1] ... [user_idN]

Arguments:
 user_id               will migrate keys of the given user(s)

Options:
 --help (-h)           Display this help message
 --quiet (-q)          Do not output any message
 --verbose (-v|vv|vvv) Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
 --version (-V)        Display this application version
 --ansi                Force ANSI output
 --no-ansi             Disable ANSI output
 --no-interaction (-n) Do not ask any interactive question

**Comment by jonlapointe** [comment]
Doesn't seem to help unfortunately. 
I still have the same message. I'll go through the log later today and see if I see something wierd.

**Comment by RealRancor** [comment]
Try to disable this maintenance mode from command line.

**Comment by jonlapointe** [comment]
Hi,
I read some doc and people saying that PHP5.5 might be necessary. So I did an update of that + a reset of apache and everything is back in order.

Thanks to all for the help.

**Comment by karlitschek** [comment]
ok. closing for now
