### ISSUE TITLE
share folder with groups doesnt work

### ISSUE THREAD

**Issue by caineone** [owncloud/core#15004]
### Steps to reproduce
1. User and group Management via OpenLDAP, LDAP integration is working silent
1. There are "User1" and "User2" which are members of "Group A" and "User3"
2. "User1" is sharing a folder "Folder Z" with "Group A"
3. Later "User3" will be added to group "Group A"

### Expected behaviour
"User2" should have access to "Folder Z" via group access rights 
Same for later for added "User3"

### Actual behaviour
At first time "User2" has access. But the access rights bounces between have access and dont see the shared folder.
"User3" also didnt see the shared folder all the time. 

### Additional experiences and verified behavior

If I add a Group to a share, there will be created a line in the "oc_share" table for the group with permission and all the needed attributes. And additionally there will be created a line for every user of the group with parent_id = ID of the group share.
After some time the lines for some users got lost. For example all seperate share entries for "User1" got lost, but "User1" can still see about 1/3 to 1/2 of all the shared folders. Sometimes all shares are visible on the web-front-end and the local client and then after 1 hour half of the shares got lost again.
In between the table "oc_ldap_group_members" is complete and the group still contains the correct users. 
So the only thing, that changes over time and maybe is the cause of the bouncing access rights is the cron.php which will be executed every 15 minutes and (I think) update the user and group info from LDAP.

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** APACHE 2.4.7

**Database:** MYSQL 5.5.41

**PHP version:** PHP 5.5.9

**ownCloud version:** 7.0.4

**Updated from an older ownCloud or fresh install:** Updated from older versions

**List of activated apps:**
Deleted Files
Full Text Search
LDAP USer and group backend
Mail Template Editor
PDF Viewer
Pictures
Share Files
Text Editor
Updater
Versions

**The content of config/config.php:**
<?php
$CONFIG = array (
  'passwordsalt' => '<removed_for_privacy_reason>',
  'datadirectory' => '/mnt/owndata',
  'overwritewebroot' => '/owncloud',
  'dbtype' => 'mysql',
  'version' => '7.0.4.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '<removed_for_privacy_reason>',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'forcessl' => true,
  'instanceid' => '5049b5a316752',
  'maintenance' => false,
  'singleuser' => false,
  'theme' => '',
  'trusted_domains' => 
  array (
    0 => '<removed_for_privacy_reason>',
  ),
  'mail_smtpmode' => 'php',
  'mail_from_address' => 'administration',
  'mail_domain' => '<removed_for_privacy_reason>',
  'mail_smtphost' => 'localhost',
  'mail_smtpport' => '25',
  'secret' => '<removed_for_privacy_reason>',
  'loglevel' => '3',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...

no

**Are you using encryption:** yes/no

no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
user_ldap,"bgjUpdateGroupsLastRun","1397208478"
user_ldap,"enabled","yes"
user_ldap,"has_memberof_filter_support","1"
user_ldap,"home_folder_naming_rule",
user_ldap,"installed_version","0.4.4"
user_ldap,"last_jpegPhoto_lookup","0"
user_ldap,"ldap_agent_password",""
user_ldap,"ldap_attributes_for_group_search",
user_ldap,"ldap_attributes_for_user_search",
user_ldap,"ldap_backup_host",
user_ldap,"ldap_backup_port","389"
user_ldap,"ldap_base","dc=xxx,dc=com"
user_ldap,"ldap_base_groups","cn=owncloud,ou=groups,dc=xxx,dc=com"
user_ldap,"ldap_base_users","ou=users,dc=xxx,dc=com"
user_ldap,"ldap_cache_ttl","600"
user_ldap,"ldap_configuration_active","1"
user_ldap,"ldap_display_name","displayname"
user_ldap,"ldap_dn","cn=ldapread,dc=xxx,dc=com"
user_ldap,"ldap_email_attr","mail"
user_ldap,"ldap_experienced_admin","0"
user_ldap,"ldap_expert_username_attr","uid"
user_ldap,"ldap_expert_uuid_attr",
user_ldap,"ldap_expert_uuid_group_attr",
user_ldap,"ldap_expert_uuid_user_attr",
user_ldap,"ldap_group_display_name","cn"
user_ldap,"ldap_group_filter","(&(objectclass=groupOfNames)(!(cn=owncloud)))"
user_ldap,"ldap_group_filter_mode","1"
user_ldap,"ldap_group_member_assoc_attribute","member"
user_ldap,"ldap_groupfilter_groups",
user_ldap,"ldap_groupfilter_objectclass","top"
user_ldap,"ldap_host","x.x.x.x"
user_ldap,"ldap_login_filter","(&(&(|(objectclass=inetOrgPerson))(|(memberof=cn=owncloud,ou=groups,dc=xxx,dc=com)))(uid=%uid))"
user_ldap,"ldap_login_filter_mode","1"
user_ldap,"ldap_loginfilter_attributes",
user_ldap,"ldap_loginfilter_email","0"
user_ldap,"ldap_loginfilter_username","1"
user_ldap,"ldap_nested_groups","0"
user_ldap,"ldap_nocase","0"
user_ldap,"ldap_override_main_server","0"
user_ldap,"ldap_paging_size","500"
user_ldap,"ldap_port","389"
user_ldap,"ldap_quota_attr",
user_ldap,"ldap_quota_def",
user_ldap,"ldap_tls",
user_ldap,"ldap_turn_off_cert_check","0"
user_ldap,"ldap_user_filter_mode","1"
user_ldap,"ldap_userfilter_groups","owncloud"
user_ldap,"ldap_userfilter_objectclass","inetOrgPerson"
user_ldap,"ldap_userlist_filter","(&(|(objectclass=inetOrgPerson))(|(memberof=cn=owncloud,ou=groups,dc=xxx,dc=com)))"
user_ldap,"ldap_uuid_attribute","entryuuid"
user_ldap,"ldap_uuid_group_attribute","entryuuid"
user_ldap,"ldap_uuid_user_attribute","entryuuid"
user_ldap,"ocsid","166061"
user_ldap,"types","authentication"

### Client configuration
**Browser:**
FireFox, IE, Safari, Chrome

**Operating system:**
Windows 7 Pro, MAC OS 10.10 Yosemite

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by MorrisJobke** [comment]
cc @blizzz @schiesbn

**Comment by blizzz** [comment]
Is Group A a local or an LDAP group?

If an LDAP group, then ownCloud is not notified of changed group memberships. Therefore there is a background job that runs every hour and updates the memberships. If changes are detected, hooks will be fired and sharing should update the shares as well.

**Comment by caineone** [comment]
Yes, I manage users and groups in LDAP only. This hourly job you mentioned is triggered by the cron.php ?

**Comment by blizzz** [comment]
Depending on what you configured in the admin panel. By default it is triggered by ajax, but having it set to cron.php as well as setup a cron job :) is the recommended setting.

**Comment by caineone** [comment]
Ok. This was only for my understanding. Yes there is a cronjob, who execute the cron.php every 15 minutes. I also saw that the cronjob execute all commands from the table "oc_jobs". 
Without reading the whole source code of OC i cannot see, where the error is by only reading the database tables. 
Is it a fact that there is no need to have a seperate entry for every user of a share in "oc_share" table?Is it enough, that the group has an entry in that table and the user is member of the group?

**Comment by blizzz** [comment]
Could you check the contents of the database table ldap_group_members?

The other questions are for @schiesbn

**Comment by caineone** [comment]
Yes. I did it all the time, the shares got lost from the user account. And all the time the user was member of the group.

**Comment by caineone** [comment]
Is there someone in the forum, who can answer the quesions? : 
Is it enough, that the group has an entry in that table and the user is member of the group?

**Comment by cmonteroluque** [comment]
@blizzz @schiesbn can you guys answer so we can resolve this?

**Comment by blizzz** [comment]
> Is it enough, that the group has an entry in that table and the user is member of the group? 

I believe so. @schiesbn 

> So the only thing, that changes over time and maybe is the cause of the bouncing access rights is the cron.php which will be executed every 15 minutes and (I think) update the user and group info from LDAP.

@caineone what do you mean with bouncing access rights? The cron should be run as web user as well. If file cache is being used, this might lead to odd behaviour when the cache files are written and attempted to be accessed by different users.

> In between the table "oc_ldap_group_members" is complete and the group still contains the correct users. 

@caineone  Have you ever seen the table be wrong when shares are not seen as they should?

**Comment by cmonteroluque** [comment]
This bug will fall off 8.2 if not resolved by 6 Oct

**Comment by schiesbn** [comment]
> Is there someone in the forum, who can answer the quesions? :
> Is it enough, that the group has an entry in that table and the user is member of the group? 

Sorry for the late reply. Yes, that's absolutely OK. By default there is only one entry for the group share. We will only create a db entry for the specific user if he renames the group share, unshare it from himself, etc.
