### ISSUE TITLE
Owncloud 8.02 enable app error: App does not provide an info.xml file

### ISSUE THREAD

**Issue by wildhare3d** [owncloud/core#15007]
centos 7 fresh install of owncloud 8.02 when I try to enable an app I get the following error:
App does not provide an info.xml file

owncloud.log output

"reqId":"6371f421cb87a55297925d39fe0a1c90","remoteAddr":"127.0.0.1....","app":"PHP","message":"ZipArchive::extractTo(): Invalid or unitialized Zip object at \/var\/www\/html\/owncloud\/lib\/private\/archive\/zip.php#135","level":3,"time":"2015-03-17T16:05:28+00:00"}
{"reqId":"6371f421cb87a55297925d39fe0a1c90","remoteAddr":"127.0.0.1....","app":"core","message":"App does not provide an info.xml file","level":3,"time":"2015-03-17T16:05:28+00:00"}

I have read the forums and tried a few things but no luck so far.

FYI - I have installed the same version 8.02 as an upgrade on a virtual environment without any issues enabling apps. This install is not virtual.

**Comment by RealRancor** [comment]
Very likely a dup of: https://github.com/owncloud/core/issues/14963

**Comment by karlitschek** [comment]
yes. probably a duplicate.

**Comment by Philippe34** [comment]
I found the solution of this problem.
 I had installed owncloud 8.0.3 with centOS 7 RPM and when I wanted activate calendar with apps > recommanded, I had the wildhare3d error.
In fact, you must absolutly install this application with the rpm. But Suse does not provide this.
So you have to download the source of the application. For instance : owncloud-apps-calendar-8.0-1.1.src.rpm
Then do: # rpm -Uvh owncloud-apps-calendar-8.0-1.1.src.rpm
# cd /root/rpmbuild/SPECS
and edit your spec file
Name:           owncloud-apps-calendar
%define         owncloud_name 168707-calendar
%define         real_name calendar
#%define         install_dir /srv/www/htdocs/owncloud <<-- TO COMMENT
%define         install_dir /var/www/html/owncloud  <<-- TO ADD
Version:        8.0
Release:        1.1
License:        AGPL-1.0
Summary:        Calendar App for Owncloud
Url:            https://apps.owncloud.com/content/show.php/Calendar+8.0?content=168707
Group:          Productivity/Networking/Web/Utilities
Source:         %{owncloud_name}.zip
BuildRequires:  unzip
#Requires:       owncloud >= 8.0 <<-- TO COMMENT
Requires:       owncloud-server >= 8.0 <<-- TO ADD
BuildRoot:      %{_tmppath}/%{name}-%{version}-build
BuildArch:      noarch

%description
Calendar app for Owncloud. Without it, you would not have a calendar for your
users.

%prep
%setup -q -n %{real_name}

%build
#
%install
mkdir -p %{buildroot}%{install_dir}/apps/%{real_name}
cp -r * %{buildroot}%{install_dir}/apps/%{real_name}/

%files
#%defattr(0640,root,www,0750)
%defattr(0640,apache,apache,0750) <-- TO ADD
#%dir %{install_dir} <<-- TO COMMENT
#%dir %{install_dir}/apps <<-- TO COMMENT
%dir %{install_dir}/apps/%{real_name}
%{install_dir}/apps/%{real_name}/*

%changelog
* Tue Feb 10 2015 lars@linux-schulserver.de
- initial version 8.0

Then build your rpm:
# yum install rpm-build
#rpmbuild -ba owncloud-apps-calendar.spec

then verify you have your rpm:
# ls /root/rpmbuild/RPMS/noarch
owncloud-apps-calendar-8.0-1.1.noarch.rpm

if OK, install this rpm:
# rpm -Uvh owncloud-apps-calendar-8.0-1.1.noarch.rpm

Then, go to your app, desactivated NOT recommanded
and activate it.

Enjoy

**Comment by Philippe34** [comment]
here screenshot:

![capture](https://cloud.githubusercontent.com/assets/12435553/7621526/ce313104-f9c7-11e4-9f17-f8fcb7d8fd9c.PNG)
![capture2](https://cloud.githubusercontent.com/assets/12435553/7621528/d6387b0a-f9c7-11e4-887e-ff3250fc4ba1.PNG)
