### ISSUE TITLE
Accessibility - Implement ARIA landmarks/roles where distinct in layout files

### ISSUE THREAD

**Issue by Volker-E** [owncloud/core#15011]
Citing from the article further down: 
> Adding ARIA landmarks to your existing site, or to a site you are developing, provides useful global navigation features and aids understanding of content structure for users. Over time the necessity of explicitly assigning landmarks will lessen as browsers build in ARIA landmark roles to newer HTML element semantics. There is widespread support for ARIA landmarks in browsers and screen readers.

Read further: http://www.paciellogroup.com/blog/2013/02/using-wai-aria-landmarks-2013/ and http://www.w3.org/TR/wai-aria/roles

**Comment by Volker-E** [comment]
Reflated to #12068

**Comment by DeepDiver1975** [comment]
@jancborchardt

**Comment by jancborchardt** [comment]
Fix at https://github.com/owncloud/core/pull/15012

**Comment by jancborchardt** [comment]
@Volker-E filing issues and fixing them yourself, I like it
![](http://i1.kym-cdn.com/entries/icons/original/000/012/982/post-19715-Brent-Rambo-gif-thumbs-up-imgu-L3yP.gif)

**Comment by Volker-E** [comment]
:+1:
