### ISSUE TITLE
Swift Object Storage doesn't work with Encryption App on 8.0.2

### ISSUE THREAD

**Issue by rvrangel** [owncloud/core#15017]
### Steps to reproduce
1. Install owncloud 8.0.2
2. Store files in a Swift Object Storage
3. Enable encryption

### Expected behaviour
File should be stored correctly with its key.

### Actual behaviour
It seems the files are uploaded, but when owncloud tries to create a temporary fileKey, it fails. I don't understand how owncloud does it, but I believe when the encryption app is disabled, the file is saves directly to the **data** dir, but when using swift it has to create a temporary file and update it afterwards.

In this case, it tries to **touch** the file **/tmp/oc_tmp_a6b01e156c7a13a8ee28a6c9f68dbcdf.txt/fileKey**, but the folder **/tmp/oc_tmp_a6b01e156c7a13a8ee28a6c9f68dbcdf.txt/** does not exist and it fails. I believe creating the folder before should solve this issue.

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** lighttpd

**Database:** SQLite

**PHP version:** 5.5.9

**ownCloud version:** 8.0.2

**Updated from an older ownCloud or fresh install:** fresh install

**List of activated apps:** files_encryption

**The content of config/config.php:** 

```
<?php
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' => 
  array (
    0 => 'xxx',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'https://xxx',
  'dbtype' => 'sqlite3',
  'version' => '8.0.2.0',
  'installed' => true,
  'forcessl' => true,
  
  'objectstore' => array(
    'class' => 'OC\\Files\\ObjectStore\\Swift',
    'arguments' => array(
      'username' => 'xxx',
      'password' => 'xxx',
      'container' => 'xxx',
      'autocreate' => false,
      'region' => 'xxx',
      'url' => 'xxx',
      'tenantName' => 'xxx',
      'serviceName' => 'swift',
    ),
  ),
);

```

**Are you using external storage, if yes which one:** swift

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 36.0

**Operating system:** Linux

#### Web server error log
```
2015-03-18 21:05:26: (mod_fastcgi.c.2673) FastCGI-stderr: PHP Warning:  fflush(): 186 is not a valid stream resource in /var/www/owncloud/apps/files_encryption/lib/stream.php on line 540
2015-03-18 21:05:26: (mod_fastcgi.c.2673) FastCGI-stderr: PHP Warning:  fclose(): 186 is not a valid stream resource in /var/www/owncloud/apps/files_encryption/lib/stream.php on line 657
2015-03-18 21:05:26: (mod_fastcgi.c.2673) FastCGI-stderr: PHP Fatal error:  Access to undeclared static property: OC_Log::$enabled in /var/www/owncloud/lib/private/legacy/log.php on line 47

```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"d84b5dd97fb8f9f87d8447aeb0a76774","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"touch(): Unable to create file \/tmp\/oc_tmp_a6b01e156c7a13a8ee28a6c9f68dbcdf.txt\/fileKey because No such file or directory at \/var\/www\/owncloud\/lib\/private\/tempmanager.php#62","level":3,"time":"2015-03-18T21:05:25+00:00"}
{"reqId":"d84b5dd97fb8f9f87d8447aeb0a76774","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"fopen(\/tmp\/oc_tmp_a6b01e156c7a13a8ee28a6c9f68dbcdf.txt\/fileKey): failed to open stream: No such file or directory at \/var\/www\/owncloud\/lib\/private\/files\/stream\/close.php#23","level":3,"time":"2015-03-18T21:05:25+00:00"}
{"reqId":"d84b5dd97fb8f9f87d8447aeb0a76774","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"fopen(close:\/\/\/tmp\/oc_tmp_a6b01e156c7a13a8ee28a6c9f68dbcdf.txt\/fileKey): failed to open stream: &quot;OC\\Files\\Stream\\Close::stream_open&quot; call failed at \/var\/www\/owncloud\/lib\/private\/files\/objectstore\/objectstorestorage.php#280","level":3,"time":"2015-03-18T21:05:25+00:00"}
{"reqId":"d84b5dd97fb8f9f87d8447aeb0a76774","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"fwrite() expects parameter 1 to be resource, boolean given at \/var\/www\/owncloud\/lib\/private\/files\/storage\/common.php#155","level":3,"time":"2015-03-18T21:05:25+00:00"}
{"reqId":"d84b5dd97fb8f9f87d8447aeb0a76774","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"fclose() expects parameter 1 to be resource, boolean given at \/var\/www\/owncloud\/lib\/private\/files\/storage\/common.php#156","level":3,"time":"2015-03-18T21:05:25+00:00"}
{"reqId":"7ec022f6340f6369c8380640ab849645","remoteAddr":"xxx.xxx.xxx.xxx","app":"index","message":"Exception: {\"Message\":\"Encryption key not found for \\\"\\\/rvrangel\\\/files\\\/test.txt\\\" during attempted read via stream\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\Files_Encryption\\\\Stream->stream_read(8192)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/preview\\\/txt.php(30): stream_get_contents(Resource id #189, 3000)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/preview.php(520): OC\\\\Preview\\\\TXT->getThumbnail('\\\/test.txt', 36, 36, true, Object(OC\\\\Files\\\\View))\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/preview.php(565): OC\\\\Preview->getPreview()\\n#4 \\\/var\\\/www\\\/owncloud\\\/core\\\/ajax\\\/preview.php(44): OC\\\\Preview->showPreview()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 [internal function]: __lambda_func(Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('?lambda_167', Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(767): OC\\\\Route\\\\Router->match('\\\/core\\\/preview.p...')\\n#9 \\\/var\\\/www\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/files_encryption\\\/lib\\\/stream.php\",\"Line\":281}","level":4,"time":"2015-03-18T21:05:26+00:00"}

```

**Comment by MorrisJobke** [comment]
cc @schiesbn @icewind1991

**Comment by DeepDiver1975** [comment]
@butonic

**Comment by PVince81** [comment]
@icewind1991 did your recent fixes cover this too ?

**Comment by butonic** [comment]
The current encryption is considered incompatible with objectstore and has been since it was added: https://doc.owncloud.org/server/9.0/admin_manual/enterprise_external_storage/s3_swift_as_primary_object_store_configuration.html#implications

Technically it was working at least in oc7.0, but:

1. the keys are also stored in the objectstore, which partly defeats the purpose of using encryption with objectstore. 
2. Since the keys need to be decrypted with the users password (OC8.2 allows implementing other mechanisms) every file content change needs an additional HTTP trip to the objectstore, which slows things down to a totally sluggish user experience.

I think we should track the encryption compatibility as an enhancement. Probably in this issue.

Also keep in mind that the decision to store the keys in the objectstore was made because, at the time, it was crucial that no data was stored on local disk (which is a moot point I agree, but we still need to be able to have it working this way when tackling this in the future).

**Comment by DeepDiver1975** [comment]
With 8.2 it is possible to choose a different key storage location - maybe this helps

**Comment by schiesbn** [comment]
Closed... see @butonic and @DeepDiver1975 explanation

**Comment by butonic** [comment]
Well ... nobody seems to have tested if it actually works ... so ... leave open as FR?
