### ISSUE TITLE
External Storage App: SMB CIFS / Using OC Login 

### ISSUE THREAD

**Issue by sbelov1** [owncloud/core#15014]
Description: We're setting up two exactly identical CIFS shares: one being under 'SMB CIFS' and the other under 'SMB CIFS / Using OC Login'. The one under 'SMB CIFS' is working while the other one - doesn't.

![image](https://cloud.githubusercontent.com/assets/8365936/6719334/3169a30a-cd90-11e4-9068-693ba4e238e9.png)

Environment: The issue was reproduced on CentOS 6.6 and Open Suse, samba client is installed, php 5.4.34, MySQL, apache.

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by Xenopathic** [comment]
SMB with OC login doesn't perform a proper check when configured in the admin panel - it can't, as it doesn't have any credentials to check with. Please check if you can log in with a valid user and get SMB1 mounted properly.

**Comment by MorrisJobke** [comment]
> SMB with OC login doesn't perform a proper check when configured in the admin panel - it can't, as it doesn't have any credentials to check with. Please check if you can log in with a valid user and get SMB1 mounted properly.

Shouldn't then even the red square be omitted or just tested what is possible (can the server be reached and a handshake be made)

**Comment by Xenopathic** [comment]
@MorrisJobke Before the new SMB backend it did exactly that - just tested for a valid server connection. I think it might have broken...

**Comment by sbelov1** [comment]
@MorrisJobke @Xenopathic Thanks for checking on this guys. Yes. It appears to be working but having a red square shown is a little misleading.

**Comment by DeepDiver1975** [comment]
@sbelov1 which OC version is this? THX

**Comment by sbelov1** [comment]
@DeepDiver1975 I was able to reproduce it on OpenSuse 13.1 and CentOS 6.6.

**Comment by DeepDiver1975** [comment]
> @sbelov1 which OC version is this? THX

OC as in ownCloud - not OS as in Operating System :speak_no_evil:

**Comment by sbelov1** [comment]
oh, sorry. Was too preoccupied with something else there for a second :) This was tested on Community 8.0.2 and Enterprise 8.0.1.

**Comment by DeepDiver1975** [comment]
> This was tested on Community 8.0.2 and Enterprise 8.0.1.

thx - so we are talking about the old smb implementation ....

**Comment by sbelov1** [comment]
@DeepDiver1975 I believe @bboule  was also experiencing on EE 7.0.4 if I'm not mistaking.

**Comment by DeepDiver1975** [comment]
@Xenopathic can I ask you to double check the behavior on master, stable8 and stable7? Thanks a lot!

**Comment by Xenopathic** [comment]
It was @LukasReschke's changes in #12523 that broke this, since the original code assumed *some* credentials to be available when testing in the admin section (they weren't actually used, but the class cannot be constructed without them). I have a fix for it though.
