### ISSUE TITLE
can't login after upgrade oc-8.0

### ISSUE THREAD

**Issue by ordinaryegi** [owncloud/core#15019]
Hi
a couple days ago i already updated my owncloud, and had fix blank page also disabled 3rd party, but we got trouble with login page, we can't login any user even admin, i try reset with occ but unfortunately it's still same, please tell me how to fix it

my owncloud running on
HP Proliant ML10
Nginx web server
PHP-FPM

regards

**Comment by RealRancor** [comment]
"can't login" ?

Whats happening when you try to login? Try to describe you problem as the issue currently is missing needed infos like this.

**Comment by ordinaryegi** [comment]
2015-03-19 2:13 GMT-04:00 RealRancor <notifications@github.com>:

> "can't login" ?
>
> Whats happening when you try to login? Try to describe you problem as the
> issue currently is missing needed infos like this.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/core/issues/15019#issuecomment-83356016>.
>

after upgrade version into 8, it's direct me into login page, unfornately
after enter username and password always go back to login page, and the i
decided to doing fresh install and still can't access my files

-- 
ubuntu user # 30968

**Comment by RealRancor** [comment]
Hi,

very likely a problem with your session dir and its permissions.

Have a look at your owncloud.log as pointed out in my previous post or search for:

login loop

at the forums.

**Comment by ordinaryegi** [comment]
2015-03-19 3:46 GMT-04:00 RealRancor <notifications@github.com>:

> Hi,
>
> very likely a problem with your session dir and its permissions.
>
> Have a look at your owncloud.log as pointed out in my previous post or
> search for:
>
> login loop
>
> at the forums.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/core/issues/15019#issuecomment-83397899>.
>

yeah, i found permission problem

Permission denied (13) at
\/var\/www\/html\/owncloud\/lib\/private\/session\/internal.php

should i change to 777 or 755?

-- 
ubuntu user # 30968

**Comment by RealRancor** [comment]
@LukasReschke 
Isn't there a way to detect such incorrectly set permissions during the login?

Have seen a lot of such reported "login loops" at the forums.

**Comment by ordinaryegi** [comment]
this is my owncloud configuration
OS
CentOS 6.6 x86_64
Web Server
Nginx formerly using apache
PHP Version
PHP 5.4.38 
Owncloud version
8
upgrade and then fresh install
 Config.php

<?php  
      2 $CONFIG = array (
      3   'instanceid' => 'oceqlwdq6y7y',  
      4   'passwordsalt' => '**********************',  
      5   'secret' => '****************************',
      6   'trusted_domains' =>  
      7   array (  
      8     0 => 'data.berkahbersama.co.id',
      9   ),  
     10   'datadirectory' => '/var/www/html/owncloud/data',  
     11   'overwrite.cli.url' => 'https://data.berkahbersama.co.id',
     12   'dbtype' => 'mysql',  
     13   'version' => '8.0.2.0',  
     14   'dbname' => 'datacenter',
     15   'dbhost' => 'localhost',  
     16   'dbtableprefix' => 'oc_',  
     17   'dbuser' => 'oc_berkahadmin',
     18   'dbpassword' => '*********',  
     19   'installed' => true,  
     20 );
Client Browser
Firefox 36 Fedora

Logs
Web Server log
2015/03/17 16:13:06 [crit] 4973#0: *66 open() "/var/www/html/owncloud/" failed (13: Permission denied), client: 36.78.16.248, server: data.berkahbersama.co.        id, request: "GET / HTTP/1.1", host: "data.berkahbersama.co.id"
      2 2015/03/17 16:13:06 [crit] 4973#0: *66 open() "/var/www/html/owncloud/" failed (13: Permission denied), client: 36.78.16.248, server: data.berkahbersama.co.        id, request: "GET / HTTP/1.1", host: "data.berkahbersama.co.id"
      3 2015/03/17 16:13:06 [crit] 4973#0: *66 open() "/var/www/html/owncloud/core/templates/404.php" failed (13: Permission denied), client: 36.78.16.248, server:         data.berkahbersama.co.id, request: "GET / HTTP/1.1", host: "data.berkahbersama.co.id"
      4 2015/03/17 16:13:13 [crit] 4973#0: *68 open() "/var/www/html/owncloud/owncloud/status.php" failed (13: Permission denied), client: 36.78.16.248, server: dat        a.berkahbersama.co.id, request: "GET /owncloud/status.php HTTP/1.1", host: "data.berkahbersama.co.id"
      5 2015/03/17 16:13:13 [crit] 4973#0: *68 open() "/var/www/html/owncloud/core/templates/404.php" failed (13: Permission denied), client: 36.78.16.248, server:         data.berkahbersama.co.id, request: "GET /owncloud/status.php HTTP/1.1", host: "data.berkahbersama.co.id"
      6 2015/03/17 16:13:13 [crit] 4973#0: *68 open() "/var/www/html/owncloud/owncloud/owncloud/status.php" failed (13: Permission denied), client: 36.78.16.248, se        rver: data.berkahbersama.co.id, request: "GET /owncloud/owncloud/status.php HTTP/1.1", host: "data.berkahbersama.co.id"
      7 2015/03/17 16:13:13 [crit] 4973#0: *68 open() "/var/www/html/owncloud/core/templates/404.php" failed (13: Permission denied), client: 36.78.16.248, server:         data.berkahbersama.co.id, request: "GET /owncloud/owncloud/status.php HTTP/1.1", host: "data.berkahbersama.co.id"
      8 2015/03/17 16:13:22 [crit] 4995#0: *1 open() "/var/www/html/owncloud/" failed (13: Permission denied), client: 36.78.16.248, server: data.berkahbersama.co.i        d, request: "GET / HTTP/1.1", host: "data.berkahbersama.co.id"
      9 2015/03/17 16:13:22 [crit] 4995#0: *1 open() "/var/www/html/owncloud/" failed (13: Permission denied), client: 36.78.16.248, server: data.berkahbersama.co.i        d, request: "GET / HTTP/1.1", host: "data.berkahbersama.co.id"
     10 2015/03/17 16:13:22 [crit] 4995#0: *1 open() "/var/www/html/owncloud/core/templates/404.php" failed (13: Permission denied), client: 36.78.16.248, server: d        ata.berkahbersama.co.id, request: "GET / HTTP/1.1", host: "data.berkahbersama.co.id"
     11 2015/03/17 16:13:44 [crit] 4995#0: *2 open() "/var/www/html/owncloud/owncloud" failed (13: Permission denied), client: 36.78.16.248, server: data.berkahbers        ama.co.id, request: "GET /owncloud HTTP/1.1", host: "data.berkahbersama.co.id"
     12 2015/03/17 16:13:44 [crit] 4995#0: *2 open() "/var/www/html/owncloud/owncloud" failed (13: Permission denied), client: 36.78.16.248, server: data.berkahbers        ama.co.id, request: "GET /owncloud HTTP/1.1", host: "data.berkahbersama.co.id"
     13 2015/03/17 16:13:44 [crit] 4995#0: *2 open() "/var/www/html/owncloud/core/templates/404.php" failed (13: Permission denied), client: 36.78.16.248, server: d        ata.berkahbersama.co.id, request: "GET /owncloud HTTP/1.1", host: "data.berkahbersama.co.id"
     14 2015/03/17 16:13:45 [crit] 4995#0: *3 open() "/var/www/html/owncloud/owncloud/status.php" failed (13: Permission denied), client: 36.78.16.248, server: data        .berkahbersama.co.id, request: "GET /owncloud/status.php HTTP/1.1", host: "data.berkahbersama.co.id"
     15 2015/03/17 16:13:45 [crit] 4995#0: *3 open() "/var/www/html/owncloud/core/templates/404.php" failed (13: Permission denied), client: 36.78.16.248, server: d        ata.berkahbersama.co.id, request: "GET /owncloud/status.php HTTP/1.1", host: "data.berkahbersama.co.id"
     16 2015/03/17 16:13:46 [crit] 4995#0: *3 open() "/var/www/html/owncloud/owncloud/owncloud/status.php" failed (13: Permission denied), client: 36.78.16.248, ser        ver: data.berkahbersama.co.id, request: "GET /owncloud/owncloud/status.php HTTP/1.1", host: "data.berkahbersama.co.id"
     17 2015/03/17 16:13:46 [crit] 4995#0: *3 open() "/var/www/html/owncloud/core/templates/404.php" failed (13: Permission denied), client: 36.78.16.248, server: d        ata.berkahbersama.co.id, request: "GET /owncloud/owncloud/status.php HTTP/1.1", host: "data.berkahbersama.co.id"
     18 2015/03/17 16:13:53 [crit] 4995#0: *4 open() "/var/www/html/owncloud/owncloud/status.php" failed (13: Permission denied), client: 36.78.16.248, server: data        .berkahbersama.co.id, request: "GET /owncloud/status.php HTTP/1.1", host: "data.berkahbersama.co.id"
     19 2015/03/17 16:13:53 [crit] 4995#0: *4 open() "/var/www/html/owncloud/core/templates/404.php" failed (13: Permission denied), client: 36.78.16.248, server: d        ata.berkahbersama.co.id, request: "GET /owncloud/status.php HTTP/1.1", host: "data.berkahbersama.co.id"
Owncloud.log
{"reqId":"ab81766fc9b732a14000eec4482231ab","remoteAddr":"112.215.64.171","app":"PHP","message":"chmod(): No such file or directory at \/var\/www\/html\/own        cloud\/lib\/private\/log\/owncloud.php#85","level":3,"time":"2015-03-19T07:18:22+00:00"}
      2 {"reqId":"ab81766fc9b732a14000eec4482231ab","remoteAddr":"112.215.64.171","app":"PHP","message":"session_write_close(): open(\/var\/lib\/php\/session\/sess_        cckqbea5mngcfta4p8m7kndor2, O_RDWR) failed: Permission denied (13) at \/var\/www\/html\/owncloud\/lib\/private\/session\/internal.php#77","level":3,"time":"        2015-03-19T07:18:22+00:00"}  
      3 {"reqId":"ab81766fc9b732a14000eec4482231ab","remoteAddr":"112.215.64.171","app":"PHP","message":"session_write_close(): Failed to write session data (files)        . Please verify that the current setting of session.save_path is correct (\/var\/lib\/php\/session) at \/var\/www\/html\/owncloud\/lib\/private\/session\/in        ternal.php#77","level":3,"time":"2015-03-19T07:18:22+00:00"}
      4 {"reqId":"ead7f0e54a110a970ae5d762b83367fd","remoteAddr":"112.215.64.171","app":"PHP","message":"session_start(): open(\/var\/lib\/php\/session\/sess_e2444a        rnkbjpcoao17k3qg8576, O_RDWR) failed: Permission denied (13) at \/var\/www\/html\/owncloud\/lib\/private\/session\/internal.php#21","level":3,"time":"2015-0        3-19T07:18:27+00:00"}

**Comment by RealRancor** [comment]
Its not a problem of your OC config. You just need to set the correct permissions on your filesystem.

**Comment by ordinaryegi** [comment]
chmod the directory?

**Comment by ordinaryegi** [comment]
bump

**Comment by RealRancor** [comment]
That are linux basics. Instead of bumping please read into how permissions are working on linux and how to correctly set them.

**Comment by ordinaryegi** [comment]
sorry, i've already change permission and ownership, but it's still same result

**Comment by karlitschek** [comment]
Hmm. It is very likely that owncloud can´t write into the session/tmp directory because of permission problems. This is most likely not an owncloud bug. I suggest that you ask at the owncloud forum for configuration tipps. closing this.
