### ISSUE TITLE
Merge `<header><div id="header">` and similar markup fragments

### ISSUE THREAD

**Issue by Volker-E** [owncloud/core#15015]
The `<header><div id="header">` workaround was targeting at IE6 (IE7?) due to it's inability to render HTML5 semantic elements correctly resulting in FOUC sometimes, even when you're integrating solutions to that like https://github.com/aFarkas/html5shiv too late in script execution on page.

Nowadays those nested elements (`<header><div id="header">`) should be merged into `<header id="header">`.
Is ownCloud caring about polyfill rendering of HTML5 elements in IE <= 8?

In the 73(!) included JS files I couldn't find html5shiv equivalent on first sight.

**Comment by jancborchardt** [comment]
Ok, I thought that workaround was also for newer versions of other browsers. But we did it a long time ago so it might really only be for IE < 8.

Thing is – the lowest we need to support right now is IE8, and that might end soon as well. (Do you have more info @MorrisJobke?) If IE8 needs the workaround, I would prefer to just keep that as long as we still need to support it instead of adding the shiv.

**Comment by Volker-E** [comment]
Well, IE8 needs either that nested markup currently in use or a shim like html5shiv. :\

**Comment by Volker-E** [comment]
In my projects I normally address it like this in `<header>` below the stylesheet links

**Comment by MorrisJobke** [comment]
We still support IE8. I have no idea, when we will drop this.

**Comment by Volker-E** [comment]
If you're willing and want to help me with the inclusion of the JS file at the right place, I'd be making a pull request on the different affected PHP files.

**Comment by MorrisJobke** [comment]
I would like to keep the simple HTML markup. It just feels wrong to include yet another JS snippet to just detect this. It works now. We can simply drop it once we drop IE8 support.

**Comment by Volker-E** [comment]
My argument would be you've got right now 78(!) JS files in a normal request and that one would just target IE8 and bring cleaner markup to all other (the majority of) browsers. But I go for whatever is decided as long as you are aware about the problem.

**Comment by jancborchardt** [comment]
@Volker-E I’d agree with @MorrisJobke here. We can keep this issue open as planned and make the change when we drop IE8 support.
