### ISSUE TITLE
Log out everywhere

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#15020]
Wordpress has a function were you can logout from every instance you're logged in to except the one that you are on right now. Is it possible to do the same with ownCloud?

Or maybe no need because of the heartbeat settings and such?

Just a thought.

@LukasReschke maybe?

**Comment by DeepDiver1975** [comment]
@LukasReschke

**Comment by enoch85** [comment]
This is somewhat done in 9.0.1. The only thing missing is a button "Log out everywhere".

**Comment by enoch85** [comment]
@DeepDiver1975 Changing milestone on this?

**Comment by enoch85** [comment]
@jancborchardt What do you think of a button just below "Sessions", or maybe at the bottom to the right, below the delete button?

**Comment by enoch85** [comment]
Ref: #24913
