### ISSUE TITLE
Get rid of unnecessary HTML comment

### ISSUE THREAD

**Issue by Volker-E** [owncloud/core#15023]
For filesize's sake I'd suggest to get rid of HTML comments and instead implement it as PHP comments, f.e in layout.user.php:

**Comment by DeepDiver1975** [comment]
@Volker-E pull request in the queue for this one as well? :speak_no_evil: :wink: 

Thanks a lot for your enhancements!

**Comment by Volker-E** [comment]
@DeepDiver1975 Done!
