### ISSUE TITLE
Usability: .deb-package update should update database automatically

### ISSUE THREAD

**Issue by htgoebel** [owncloud/core#15029]
### Steps to reproduce
1. Install owncloud 8.0.0.7 using deb-packages
2. Upgrade to 8.0.2: `apt-get update ; apt-get upgrade`
2. Point your browser to your installation

### Expected behaviour
I still should get the normal login-screen.
Updating the setup should have been done automatically when upgrading the deb-package.

### Actual behaviour
The main page of owncloud is showing the "Update now" note (see picture).
![Uploading owncloud.png . . .]()

### Server configuration
**Operating system**: n/a
**Web server:** n/a
**Database:** n/a
**PHP version:** n/a
**ownCloud version:** 8.0.0.7
**Updated from an older ownCloud or fresh install:** fresh
**List of activated apps:** n/a
**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'forcessl' => true,
  'logdateformat' => 'Y-m-d H:i:s.u',
  'loglevel' => 2,
  'mail_domain' => '...',
  'mail_from_address' => '...',
  'mail_smtpmode' => 'sendmail',
  'remember_login_cookie_lifetime' => '1296000',
  'session_keepalive' => true,
  'session_lifetime' => '86400',
  'trashbin_auto_expire' => true,
  'trashbin_retention_obligation' => 30,
  'instanceid' => '...',
  'passwordsalt' => '...',
  'secret' => '...',
  'trusted_domains' => 
  array (
    0 => '...',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'https://...',
  'dbtype' => 'sqlite3',
  'version' => '8.0.0.7',
  'installed' => true,
  'theme' => '',
);
```

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** n/a
**Operating system:** all

### Logs
n/a

**Comment by MorrisJobke** [comment]
Sometimes the upgrade needs manual interaction. Therefore we decided to not run the upgrade command from within the package. This is also documented: https://doc.owncloud.org/server/8.0/admin_manual/maintenance/upgrade.html#upgrading-with-your-linux-package-manager
