### ISSUE TITLE
OCS API Allows deleting of expiration date when enfroced

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#15021]
On current master (but I suspect at stable as well) the OCS API allows you to remove the expiration date when this is set to be enforced.

I stumble upon this when fixing something in the client.

## Steps
1. Set enforce expiration date in config
2. Share a link by url
3. use the OCS API to delete the expiration date
4. call succeeds and expiration date is unset

I did not yet test if the share does not get removed anyway, by the con jobs since it can check for creation date.

But this is still bad behavior from the OCS API and the removing of an expiration date should fail! Since now I have no way of knowing that the share needs an expiration date. 

I'll have a look later. But reporting so I do not forget. Should be a simple fix in the OCS API.

CC: @schiesbn

**Comment by rullzer** [comment]
PR at #15025

**Comment by DeepDiver1975** [comment]
> PR at #15025

merged -> close
