### ISSUE TITLE
Remove obsolete and invalid IE5-7 filter properties from CSS 

### ISSUE THREAD

**Issue by Volker-E** [owncloud/core#15027]
The `filter` CSS properties are invalid and just useful for IE5-7 and should be removed. From core/css/styles.css:

    -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=30)";
    filter: alpha(opacity=30);
    opacity: .3;

See also: http://www.quirksmode.org/css/opacity.html

**Comment by MorrisJobke** [comment]
Works. Thanks for noticing this :)

**Comment by MorrisJobke** [comment]
#15012
