### ISSUE TITLE
Share link hangs

### ISSUE THREAD

**Issue by jdelvecchio** [owncloud/core#15022]
When I try to share a file, the process hangs for ever.

Steps to reproduce

1. choose a file
2. click share
3. click "Share Link"

Server configuration

Operating system: Ubuntu 14.04

Web server: APACHE 2.4.7

Database: MYSQL 5.5.41

PHP version: PHP 5.5.9

ownCloud version: 7.0.3.4

Lines in the log 

{"app":"PHP","message":"Call to a member function getUID() on a non-object at \/usr\/share\/owncloud\/apps\/files_external\/lib\/config.php#124","level":3,"time":"2015-03-19T08:57:21+00:00"}

**Comment by MorrisJobke** [comment]
There was a fix added for this in 7.0.4. Please update your instance and this will be gone.

ref https://github.com/owncloud/core/pull/12290
