### ISSUE TITLE
Disabling the app trash or version does not cleanup trash or version files

### ISSUE THREAD

**Issue by ernesttk** [owncloud/core#15034]
See also my comment about the situation at the bottom of the issue 
### Steps to reproduce
1.  Use default setting which has trash and versioning enabled. Add, modify and delete some files client side for a while to startup trash and versioning. Now, server side, in the "data/username/" directory the client files can be seen in there respective directories files/, files_trashbin/ and files_versions/.
2.  Login to the web interface as admin and disable either or both the trash and the versioning. 
3.  modify and delete some files client side. 
4.  Old files from before disabling are still present in files_trashbin/ and or files_versions/ 
### Expected behavior

There should have been a automatic cleanup initiated by the action to disable the app (with or without warning for dummies). 
### Actual behavior

Files are left in place.
Only after I added trashbin_retention_obligation => 0 to config.php and re-enabled trashbin were the files in <user>files_tashbin/ deleted. I haven't figured out yet how to delete safely the versions
### Server configuration

**Operating system**: 
debian 

**Web server:**
Apache 2.2.22-13+deb7u4

**Database:**
mysql 5.5.41-0+wheezy1

**PHP version:**
5.4.38-0+deb7u1

**ownCloud version:** (see ownCloud admin page)
8.0.2-5

**Updated from an older ownCloud or fresh install:**
updated from 8.0.0

**List of activated apps:**
All apps which are enabled by default. Those concerning this issue are:
Deleted Files 0.6.2
Versions 1.0.5

**The content of config/config.php:**

```
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://euscloud.eus.klm.nl/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.2.0',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_root',
  'dbpassword' => '',
  'installed' => true,
  'forcessl' => true,
  'loglevel' => 2,
  'theme' => '',
  'maintenance' => false,
  'trashbin_retention_obligation' => 0,
```

note: trashbin_retention_obligation was added to finally delete the trashbin. But this only works with "Deleted Files" enabled. There may be something similar for app Versions, but I haven't discovered it.

**Are you using external storage, if yes which one:** local/smb/sftp/...
none

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
not yet
#### LDAP configuration (delete this part if not used)

not used
### Client configuration

**Browser:**
firefox

**Operating system:**
Windows 7
### Logs

None of the systems show any errors, so no logs are included.

**Situation around this issue**
I use owncloud as a (near) instantaneous synchronization of my development environment between two workstation (and have a quick backup too). This means that files changes a lot. Versions are not needed because I also use subversion and neither is the trash needed as it would contain masses of compiler generated temporary files/. And actually this was the case and is the reason I disabled both.
I haven't actually checked, but I suspect ownCloud's app API does not provide something like a pre-disable call which could be used to resolve this. If what I suspect is correct then this issue report should be seen as a enhancement. 
I realize this issue could be by design, this is for you to judge.

**Comment by PVince81** [comment]
There is a pre-disable hook, see https://github.com/owncloud/core/blob/master/apps/files_encryption/lib/helper.php#L84

But clearing all files at this stage could take a long time so might be better to put this logic in a one-shot background job instead.

**Comment by ovidiub13** [comment]
You can clear the trash by going to the trash (while the app is enabled) select all and delete them.

I haven't found any way of deleting the versions. Is there such a way? I wouldn't just delete them from the filesystem (via ssh).

Since I don't have a storage set for my user, it takes up a huge amount of storage:
```
$ du -h -s ./OwnCloud/ovidiu/*
116K    ./OwnCloud/ovidiu/avatar.png
1,7G    ./OwnCloud/ovidiu/cache
174G    ./OwnCloud/ovidiu/files
8,0K    ./OwnCloud/ovidiu/files_trashbin
134G    ./OwnCloud/ovidiu/files_versions
498M    ./OwnCloud/ovidiu/thumbnails```

**Comment by ovidiub13** [comment]
Also, I've tried limiting the user storage to just above my current usage, to attempt to trigger the version app clean-up. And then I checked in the `files_versions` directory and found that the most storage it taken by a external storage, that is available for a group. So it does not belong to a user.

How can I limit that?

**Comment by ovidiub13** [comment]
I've disabled and re-enabled the version app. Waited for a while. And now I see the `file_versions` directory has been cleaned. So something happened.

```
$ du -h -s /media/500GB/OwnCloud/ovidiu/*
116K    /media/500GB/OwnCloud/ovidiu/avatar.png
15G     /media/500GB/OwnCloud/ovidiu/cache
177G    /media/500GB/OwnCloud/ovidiu/files
8,0K    /media/500GB/OwnCloud/ovidiu/files_trashbin
13M     /media/500GB/OwnCloud/ovidiu/files_versions
498M    /media/500GB/OwnCloud/ovidiu/thumbnails
```

I've disabled the versioning app now. I don't plan to re-enable it again.

**Comment by PVince81** [comment]
when the app is enabled and before disabling, use the following commands:
- `occ versions:cleanup`
- `occ trashbin:cleanup`

then disable the apps

**Comment by mihail-minkov** [comment]
@PVince81 you literally helped me release about 830 GB on my server 👍 👍 👍

**Comment by jcoliv82** [comment]
Hello,
I'm facing a similar problem.
I'm running OwnCloud 9.1.3 on a Ubuntu 14.04.3 LTS server. I don't have the occ command to run. How can I install it?

Thanks a lot!

**Comment by DeepDiver1975** [comment]
The occ command is part of the Server release. Nothing additional has to be installed.

**Comment by DeepDiver1975** [comment]
I'm closing this. The solution is documented above.
