### ISSUE TITLE
.htaccess is not updated from 8.0 to 8.0.2

### ISSUE THREAD

**Issue by bjoerns1983** [owncloud/core#15039]
Hi there,
i wondered why owncloud showed me the wrong version number (and the update message didn't disappear) after my upgrade from 8.0 to 8.0.2 via the Open Suse Build Servers on debian.

Apt-get showed me that the correct package 8.0.2-5 was installed, but it seems that the .htaccess files was not touched. It still has the same date from the day i installe OC 8.0.

**Comment by karlitschek** [comment]
@jnweiger any idea?

**Comment by deMattin** [comment]
I updated just now with suse repository on debian 7 and I got the message to decide, if I want to use the old .htaccess, use the new .htaccess of packet maintainer, check differences, ...
All as it should be.

**Comment by phuvries** [comment]
As deMattin I updated just an hour ago and got the cited question about .htaccess.
Unfortunately I chose "N" and now ownCloud refuses to update to the last version.
Does anybody have a suggestion how to install the right version of .htaccess after this failure?

**Comment by sebfox** [comment]
in debian packaging : /var/www/owncloud# cp .htaccess .htaccess.old; cp .htaccess.dpkg-dist .htaccess
will solve your issue.
( .htaccess.dpkg-dist is on the installation directory)

**Comment by phuvries** [comment]
@sebfox 
You solved my problem, thanks!

**Comment by enoch85** [comment]
The 8.0.2-5 packages are released and with that upgrade the .htaccess is included. At least in Ubuntu 14.04.

**Comment by bjoerns1983** [comment]
I didn't got any dialog like deMattin describe it when i updated some hours ago.
Nevermind i manually downloaded the correct .htaccess from github for 8.0.2 and placed it in my owncloud folder.

Unfortunately the problem stays the same. Admin Panel tells me that i am still on 8.0 and i still  yellow upgrade reminder.

Btw. i am using nginx on Debian 7. I dont think that nginx uses the .htaccess or am i wrong?

**Comment by RealRancor** [comment]
@bjoerns1983 
The yellow upgrade reminder is not related to this problem.

**Comment by DeepDiver1975** [comment]
@jnweiger

**Comment by zakisaad** [comment]
also have this issue, i was asked during install if i wanted to update my .htaccess files but i didnt; i have replaced it with the newer version with:

cp .htaccess .htaccess.old; cp .htaccess.dpkg-dist .htaccess

and i still have owncloud telling my .htaccess is the wrong version

**Comment by enoch85** [comment]
If you answser "yes",  the package manager will save the old .htaccess as .htaccess.dpkg - so no worries.

**Comment by jnweiger** [comment]
.htaccess is flagged as a config file. That is the reason why it is treated special. 
Config files are preserved by the installer to not override any human changes...

I understand that this .htaccess is written / overwritten by owncloud core - that probably confuses the installer?

**Comment by karlitschek** [comment]
@jnweiger Is there a reason that this is flagged as config file? maybe it is better to consider it a normal part of the application for owncloud?

**Comment by gpirtle** [comment]
cd /var/www/owncloud
sudo cp .htaccess .htaccess.old
sudo nano .htaccess
First line is #8.0.0 - edit to #8.0.2
Ctrl-X, Yes to save
Attempt upgrade again

**Comment by jnweiger** [comment]
Example procedure to later update the .htaccess file:

    apt-get download owncloud-config-apache
    ar x owncloud-config-apache
    tar xvf data.tar.xz
    cp var/www/owncloud/.htaccess /var/www/owncloud/

**Comment by jnweiger** [comment]
fix pushed to isv:ownCloud:community:8.0 -- check out owncloud-8.0.2-6
