### ISSUE TITLE
Disallow old clients form connecting to the server

### ISSUE THREAD

**Issue by stonerl** [owncloud/core#15032]
Would it be possible to implement a configure-option to deny access for old client versions? For example to set a minimum version for the clients that are allowed to connect. I came up with this idea because some users are very lazy with updating their desktop clients and this would give administrators a tool to "force" their users to upgrade.

**Comment by DeepDiver1975** [comment]
For sure something which makes sense.

@dragotin @MTRichards @karlitschek opionions

**Comment by dragotin** [comment]
Well, yes, however, these users should get an update notification.

Of course we can not change the clients that are out already, so I guess the server would have to check the UserAgent that is coming in to decide.

**Comment by DeepDiver1975** [comment]
> so I guess the server would have to check the UserAgent that is coming in to decide.

exactly - check the user agent and the version and in case the version is too low we throw back an exception/http error code.

Same goes for the mobile clients as well.

**Comment by MTRichards** [comment]
Certainly a good idea. We could just block it at the file firewall all the time, and make a simple option for that. BUT, we need the client to know that this happened, so some form of error return code that is recognized is needed (error xxx: outdated client.) which then (if configured) points to how to update. Mobile: point to app stores or URL in ownBrander. Desktop: point to oC update or url from ownBrander.

Something like that would work ok.

Tagging.

**Comment by DeepDiver1975** [comment]
> We could just block it at the file firewall all the time, and make a simple option for that.

Well - we need a solution for the community edition as well. Some point in time we might want to restrict access of old clients by default as we know they eat kitten, bears, dinosaurs ....

**Comment by rullzer** [comment]
Probably 403 of the HTTP status codes makes the most sense.
Then with some custom returned data to notify the client of the exact error. (Client to old/Currently no client syncing allowed/......)

I assume this is mainly for the webdav endpoint. Altough I could imagine this is useful for other endpoints. If we know that old clients have incompatible behaviour (if for example the OCS API changes).

8.1 is probably a bit early but getting this into 8.2 would be a good idea. Ideally this function should already be there (and in the client) for some time before we have to use it ;) So a lot of people are using a compatible client already.

**Comment by stonerl** [comment]
Just one question. Since there has been much more discussion in this pull-request #15683, can I close this issue here?

**Comment by dragotin** [comment]
@stonerl please before closing, maybe you can test that with the latest client (1.8.3) and report back if the client comes up with a useful message to the user. If not, we need to keep that open to implement that IMHO.

**Comment by DeepDiver1975** [comment]
Yes - this can be closed. With 8.1 we can block old clients.
