### ISSUE TITLE
how does the web interface of owncloud work?

### ISSUE THREAD

**Issue by marie8** [owncloud/core#15036]
owncloud uses sabre (a webdav server) to let users view and manipulate remote data in their native OS using webdav clients  .In the web interface of owncloud , the files are manipulated with webdav too ?? OR it  just use fopen fclose .... and the database (since the paths of files are stored) ? 
thank you

**Comment by RealRancor** [comment]
Hi,

please note this is the issue tracker to report issues or features requests for OC.

Questions like this should go to the forums or the mailinglist.

**Comment by marie8** [comment]
ok , I'm sorry , but I can't delete this .

**Comment by RealRancor** [comment]
Just leave it closed. :)
