### ISSUE TITLE
shebang used in shell scripts only works on Linux

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#15037]
You can't use `/bin/bash` as the shebang as it will surely fail on some systems.

A safer call is `/usr/bin/env bash`

Wrong in at least 16 scripts
https://github.com/owncloud/core/search?utf8=%E2%9C%93&q=bin%2Fbash

**Comment by karlitschek** [comment]
Can you give an example on which OS /bin/bash doesn´t work?

**Comment by oparoz** [comment]
All the OS families which put "non-OS" files in `/usr/local`. The *BSD family being one of them.

**Comment by DeepDiver1975** [comment]
@oparoz THX - pull request to fix this is welcome :speak_no_evil:

**Comment by Xenopathic** [comment]
What happens if `env` is in a different place?

**Comment by oparoz** [comment]
As the article mentions it's not a 100% foolproof solution, but do you have examples of env being in other locations?

**Comment by Xenopathic** [comment]
@oparoz Well, I don't have any examples of bash being in a different place, so no :laughing:

**Comment by DeepDiver1975** [comment]
moving to backlog - pr welcome at any time

**Comment by PVince81** [comment]
Moving to 9.0
