### ISSUE TITLE
Uninstalling owncloud leaves owncloud.conf symbolic link in /etc/apache2, which disables entire httpd server

### ISSUE THREAD

**Issue by cpbl** [owncloud/core#15038]
I installed owncloud service on an Ubuntu 14.04 box.
I later uninstalled it.
Then I noticed that the entire web server was down.

The error is:

* The apache2 configtest failed.
Output of config test was:
apache2: Syntax error on line 224 of /etc/apache2/apache2.conf: Could not open configuration file /etc/apache2/conf-enabled/owncloud.conf: No such file or directory
Action 'configtest' failed.
The Apache error log may have more information.

I found:

>  ls conf-enabled/
charset.conf@  localized-error-pages.conf@  other-vhosts-access-log.conf@  owncloud.conf@  security.conf@  serve-cgi-bin.conf@
> ls conf-available/
charset.conf  localized-error-pages.conf  other-vhosts-access-log.conf  security.conf  serve-cgi-bin.conf

ie, the symbolic link was not deleted on uninstall.

**Comment by karlitschek** [comment]
@jnweiger What do you think?

**Comment by DeepDiver1975** [comment]
> I installed owncloud service on an Ubuntu 14.04 box.

@cpbl what is your installation repo? Please add the exact package version - THX

**Comment by cpbl** [comment]
/var/log/apt/history says:

Commandline: apt-get remove owncloud-server
Remove: owncloud-app-files-external:amd64 (8.0.2-4), owncloud-app-files-locking:amd64 (8.0.2-4), owncloud:amd64 (8.0.2-4), owncloud-3rdparty:amd64 (8.0.2-4), owncloud-app-user-external:amd64 (8.0.2-4), owncloud-app-files-trashbin:amd64 (8.0.2-4), owncloud-app-files-sharing:amd64 (8.0.2-4), owncloud-app-firstrunwizard:amd64 (8.0.2-4), owncloud-server:amd64 (8.0.2-4), owncloud-app-files-pdfviewer:amd64 (8.0.2-4), owncloud-app-activity:amd64 (8.0.2-4), owncloud-app-files-texteditor:amd64 (8.0.2-4), owncloud-app-provisioning-api:amd64 (8.0.2-4), owncloud-app-updater:amd64 (8.0.2-4), owncloud-app-user-webdavauth:amd64 (8.0.2-4), owncloud-app-templateeditor:amd64 (8.0.2-4), owncloud-app-files-versions:amd64 (8.0.2-4), owncloud-app-files-encryption:amd64 (8.0.2-4), owncloud-app-files:amd64 (8.0.2-4), owncloud-app-gallery:amd64 (8.0.2-4), owncloud-config-apache:amd64 (8.0.2-4), owncloud-app-external:amd64 (8.0.2-4), owncloud-app-files-videoviewer:amd64 (8.0.2-4), owncloud-app-user-ldap:amd64 (8.0.2-4)

**Comment by RealRancor** [comment]
If you're only using apt-get remove then i think its normal that config files stay in place. Use:

apt-get remove --purge

instead.

**Comment by cpbl** [comment]
Shouldn't "remove" either leave the file in conf-available, then, or delete both it AND its symbolic link in conf-enabled?

**Comment by DeepDiver1975** [comment]
@jnweiger

**Comment by jnweiger** [comment]
Fixed in rebuild 8.0.2-7 of owncloud, pushed to isv:ownCloud:community:8.0
