### ISSUE TITLE
Add "Recent Files" to the sidebar of the files app.

### ISSUE THREAD

**Issue by icewind1991** [owncloud/core#15049]
Showing a list of the most receently changed files.

This differs from simply sorting the file list by mtime by not having files hidden in a folde structure but instead showing a flat list sorted by mtime (maybe show newly created folders if we have a way to distinguish recently created foldes from folders that have recently edited files)

cc @PVince81 @jancborchardt

**Comment by PVince81** [comment]
Does it mean we'd need to have a method "searchRecent($limit)" on the node/view/cache, similar to "searchByMime" ?

**Comment by DeepDiver1975** [comment]
scheduling for backlog

**Comment by jancborchardt** [comment]
Yup, great idea. Should be the third entry, after All and Favorites.

**Comment by jancborchardt** [comment]
This is a very good enhancement for visibility of files and I’d say we should consider this for 9.1. @MTRichards

**Comment by karlitschek** [comment]
good point. i agree. Funny I heard this from someone else just 2 days ago.

**Comment by MTRichards** [comment]
Really like this. I assume we sort based on mtime, and pick a metric that means something (e.g. 1 day or something). Then we also have to have a limit on the number of files shown...20 or something. Depends on the UX. Will consider for 9.1.

**Comment by PVince81** [comment]
@pmaier1

**Comment by raoulteeuwen** [comment]
Ended up here while google-ing whether this is already implemented in OwnCloud. Bit surprised it isn't? When working with a lot of files, one often at some point in time works with the same files, so having easy access to those saves time traversing through the folder hierarchies...
