### ISSUE TITLE
can't create external storage (ftp)

### ISSUE THREAD

**Issue by wildhare3d** [owncloud/core#15040]
oc 8.0 and oc 8.02 centos7 

When I try to create FTP storage account I get this error:

Error	PHP	stat(): stat failed for ftp://xxx:xxx@ftp.xxx.net/ at /var/www/html/owncloud/apps/files_external/lib/streamwrapper.php#104	
Error	PHP	stat(): connect() failed: Permission denied at /var/www/html/owncloud/apps/files_external/lib/streamwrapper.php#104

External storage works on centos7 oc8.02 (virtual server) I tested. the above serer is not virtual..

**Comment by karlitschek** [comment]
There are php configuration setting to disable ftp:// urls. Some php "security" patches can also affect this. Or SELinux or AppArmor.
Can you please verify this?

**Comment by wildhare3d** [comment]
in php.ini:  allow_url_include = On it was Off and restarted apache. 
allow_url_include = On  

still gettting error:
Error	PHP	stat(): stat failed for ftp://xxx:xxx@ftp.xxx.net/ at /var/www/html/owncloud/apps/files_external/lib/streamwrapper.php#104	2015-03-19T12:32:50+00:00
Error	PHP	stat(): connect() failed: Permission denied at /var/www/html/owncloud/apps/files_external/lib/streamwrapper.php#104	2015-03-19T12:32:50+00:00
Error	PHP	stat(): stat failed for ftp://xxx:xxx@ftp.triple8.net/ at /var/www/html/owncloud/apps/files_external/lib/streamwrapper.php#104	2015-03-19T12:32:47+00:00
Error	PHP	file_exists(): connect() failed: Permission denied at /var/www/html/owncloud/apps/files_external/lib/streamwrapper.php#51

**Comment by wildhare3d** [comment]
Disabling selinux fixed the issue. I can now add FTP external storage!!

 Strangely enough on two other virtual servers (oc 8.02 one windows and the other also centos7)  selinux is enabled and "external storage" FTP works?
