### ISSUE TITLE
Core updater not making update notifications

### ISSUE THREAD

**Issue by carlaschroder** [owncloud/core#15041]
Hey all, I've been sorting out the differences between the Updater app and the core updater. (Reviews of docs pages welcome, links below) In my own testing, when I disable the Updater app I do not get  update notifications. When the Updater app is enabled I see the little yellow banner.
![updater-1](https://cloud.githubusercontent.com/assets/8388387/6734231/2ac1b400-ce14-11e4-9e6c-197a8e584453.png)

When the Updater app is disabled, there are no notifications. I have tried two scenarios:
1. Installing and updating from package repos, both oBS and the enterprise repo. My Linux package manager does automatic update notifications, so that tells me when there are new ownCloud updates. But I have not seen the update alert in ownCloud.
1. Manual installation & manual updates of ownCloud. Again, with the Updater app disabled I do not see update notifications.

Is this how it supposed to behave?

Upgrading ownCloud with the Updater App
https://doc.owncloud.org/server/8.0/admin_manual/maintenance/update.html
Upgrading Your ownCloud Server
https://doc.owncloud.org/server/8.0/admin_manual/maintenance/upgrade.html

**Comment by PVince81** [comment]
@VicDeo might know

**Comment by VicDeo** [comment]
@carlaschroder 
All I know is that  
1. This bubble  lives in the core class  https://github.com/owncloud/core/blob/master/lib/private/templatelayout.php#L46
2. Updater app doesn't manage this bubble. 
3. Both Updater and bubble respect `updatechecker`  config parameter state https://github.com/owncloud/core/blob/master/config/config.sample.php#L433

**Comment by VicDeo** [comment]
@carlaschroder what is OC version you tested this against btw?

**Comment by carlaschroder** [comment]
@VicDeo, most recent test is Linux Mint 17 using the xUbuntu 14.04 oBS repo, owncloud 8. Current installed version is 8.0.2-4, new version is 8.0.2-5 . This is what I see in my Mint update notifier:

![mint-update](https://cloud.githubusercontent.com/assets/8388387/6741081/29ce256e-ce42-11e4-819d-5c89a9956290.png)

My other test platforms are in a bit of a mess so that's all I have at the moment. I'm going to try a few things & see what happens. At any rate I am glad to have the confirmation that the bubble is supposed to appear.

**Comment by VicDeo** [comment]
@carlaschroder @DeepDiver1975 
I don't think this is a bug since  8.0.2-4 and 8.0.2-5  are package manager versions.  4 and 5 are build numbers here. I guess these packages have the same OC 8.0.2 code inside.

If someone has 8.0.2 installed it is the most recent version. 
apps.owncloud.org works independently from any package manager and for sure is not capable to track Debian|Suse|whatever repo changes 
And I haven't seen that we announce 8.0.2 release twice :)

**Comment by VicDeo** [comment]
@carlaschroder

>I guess these packages have the same OC 8.0.2 code inside.

This seems to be right,  8.0.2-5 fixes packaging-specific issue https://github.com/owncloud/enterprise/issues/573  Nothing to update if package manager is not used.

**Comment by carlaschroder** [comment]
Thanks @VicDeo, I appreciate the help. That's great information for the manual page. I understand how it works now and what to look for in testing, so I am closing this.
