### ISSUE TITLE
Share Links not working after upgrading from 7.0.4  to 8.0.2

### ISSUE THREAD

**Issue by offlinehoster** [owncloud/core#15045]
I can see the right names inside the oc_share, but the share link urls are not right. Downloading a 2KB file takes a lot of time and the downloaded file is big...1GB or more.

And i don't see on the webpanel that a file is shared by me...

**Comment by enoch85** [comment]
@offlinehoster Thanks for reporting! Please update your issue report with this: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by offlinehoster** [comment]
### Steps to reproduce
1. Running 7.0.4 ownCloud (with older data, beginning by ownCloud version 5
2. Update to 8.0.2 

### Expected behaviour
The update should work ;)

### Actual behaviour
The update is telling me that there is an old existing date local:: home:: and the db migration or whatever can't continue.

### Server configuration
**Operating system**:
Debian 7 64bit

**Web server:**
Nginx with php5-fpm

**Database:**
 mysql-server-5.5  5.5.41-0+wheezy1

**PHP version:**
php5                             5.4.38-0+deb7u1 

**ownCloud version:** (see ownCloud admin page)
current 7.0.4
after update should be 8.0.2

**Updated from an older ownCloud or fresh install:**
updated from 7.0.4 to current

**List of activated apps:**
no 3rd party or other plugin (we're using ldap)

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'oc65abe4a7e8',
  'passwordsalt' => 'oiefhoweifhwoiefhowihfwoifhb',
  'datadirectory' => '/var/www/owncloud/data',
  'version' => '7.0.4.2',
  'dbtype' => 'mysql',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'efewfwefwef_wefwefwef_wefwfwef_wfwefwef',
  'installed' => true,
  'forcessl' => true,
  'ldapIgnoreNamingRules' => false,
  'theme' => '',
  'maintenance' => false,
  'log_type' => 'owncloud',
  'logfile' => '/var/www/owncloud/data/owncloud.log',
  'loglevel' => '0',
  'logdateformat' => 'F d, Y H:i:s',
  'logtimezone' => 'Europe/Berlin',
  'log_query' => false,
  'trusted_domains' =>
  array (
    0 => 'owncloud.domain.tld',
  ),
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'owncloud-noreply',
  'mail_domain' => 'domain.tld',
  'mail_smtpsecure' => 'tls',
  'mail_smtphost' => '127.0.0.1',
  'secret' => '768965b2ab4f2ewefwefiwefowiefhwoihfwofhowifhoweifhwoifhowfhweoifhweoifhweofhweofihc852c76f',
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no external storages

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP

#### LDAP configuration (delete this part if not used)

```

```

### Client configuration
**Browser:**
Firefox 36.0.1

**Operating system:**
linux 3.16.0-31-generic

### Logs
#### Web server error log
```
just a simple 200 inside the log
```

#### ownCloud log (data/owncloud.log)
```
nothing special, only the information that the update from 7.0.4 to 8.0.2 is running
```

**Comment by offlinehoster** [comment]
Is there an option to backup all the user data with settings and import them to a brandnew ownCloud installation?

**Comment by DeepDiver1975** [comment]
> The update is telling me that there is an old existing date local:: home:: and the db migration or whatever can't continue.

@PVince81 can you help here? THX

**Comment by karlitschek** [comment]
@PVince81 ping

**Comment by PVince81** [comment]
@offlinehoster did you rename/move the data directory during or after the update ?
If you had hard-coded paths in the database (legacy stuff from very old OC versions), then these have not been recognized.

See: https://github.com/owncloud/core/issues/13980#issuecomment-73511661

**Comment by PVince81** [comment]
Closing due to lack of info.
Please follow the discussion in https://github.com/owncloud/core/issues/13980#issuecomment-73511661 which might help you make a decision on how to fix the warning.
