### ISSUE TITLE
ownCloud 8.0.2 shows no content anymore, file rescan fails

### ISSUE THREAD

**Issue by resound88** [owncloud/core#15059]
Hi together,
after using the function "share with another owncloud" for a file, owncloud doesn't anymore show the contents of the site "all files", it's completely blank.
If I try to rescan with console.php, it appears the following error message:

PHP Fatal error:  Call to undefined function OCA\Files_Sharing\External\curl_init() in [...]/owncloud/apps/files_sharing/lib/external/storage.php on line 219

The system is running Debian 6.

I tried to delete the uploaded files in the file_cache table at DB layer and on the file system, but without any success.
What can I do?

Thanks in advance.
Best regards

**Comment by RealRancor** [comment]
Hi,

you're missing the php5-curl package which will be a hard dependency in the next OC version:

https://github.com/owncloud/core/pull/14839

**Comment by DeepDiver1975** [comment]
> you're missing the php5-curl package which will be a hard dependency in the next OC version:

yes -> case closed

**Comment by resound88** [comment]
@RealRancor Thanks, that solved the problem, but the deleted file still appears in the search results. How can I rebuild the index?

**Comment by RealRancor** [comment]
@resound88 Sorry, no idea.
