### ISSUE TITLE
Upgrade message does not disappear after upgrade from 8.0 to 8.0.2

### ISSUE THREAD

**Issue by bjoerns1983** [owncloud/core#15051]
Hi there i am having a strange Problem.

I updated from 8.0 to 8.0.2 via the Open Suse Build Service, the package was definately installed but the version of OC in the Admin panel still tells me it is 8.0 (stable) and also the upgrade message has not disappeared.

I am using Owncloud on a Debian 7 Server with nginx and php5-fpm (Version 5.4.36).

Does anybody has an idea. Could it be that i first have to install 8.0.1 and than go to 8.0.2?

**Comment by DeepDiver1975** [comment]
@VicDeo I assume caching of the update information is causing this.

**Comment by bjoerns1983** [comment]
Anything i can do here to change this by myself? Any caches i can flush or something like that?

**Comment by VicDeo** [comment]
@bjoerns1983 it should flush itself in 30 minutes

**Comment by bjoerns1983** [comment]
Nope not happening since 3 days.

**Comment by VicDeo** [comment]
@bjoerns1983 ah, you update via repo. Please post exact package version that is installed currently on your system. 

>Could it be that i first have to install 8.0.1 and than go to 8.0.2?

definitely no

**Comment by VicDeo** [comment]
cc @jnweiger

**Comment by VicDeo** [comment]
@bjoerns1983 Did you install it initially via package manager btw?

**Comment by bjoerns1983** [comment]
Yes the initial install with 7.0.2-1 was done with the package manager just like all the updates and the upgrade to 8.0.

When available i updated to 8.0.2-4 and then to 8.0.2-5, but the massage never vanished.

**Comment by VicDeo** [comment]
@bjoerns1983  hm... can you check whether `root` in your nginx config is the same with path where 8.0.2-5 packages were installed?

**Comment by bjoerns1983** [comment]
If i call dpkg -L owncloud i only get:
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/owncloud
/usr/share/doc/owncloud/changelog.Debian.gz
/usr/share/doc/owncloud/README.gz
/usr/share/doc/owncloud/AUTHORS
/usr/share/doc/owncloud/README.packaging.gz
/usr/share/doc/owncloud/COPYING-AGPL.gz

Seems nothing is installed to /var/www/owncloud, or is there another command i can use to find out if owncloud 8.0.2-5 is correctly installed?

**Comment by blee880** [comment]
Hi, I had this .htaccess not updated with the new version. I edited the first line of .htaccess from 8.0.0 to 8.0.2 this solved the whole situation.

**Comment by bjoerns1983** [comment]
Do you use Apache?

**Comment by blee880** [comment]
I'm runs on Apache2.

**Comment by karlitschek** [comment]
can you post the content of version.php in the owncloud root folder?

**Comment by blee880** [comment]
Hi, here is the content of version.php:

<?php 
$OC_Version = array(8,0,2,0);
$OC_VersionString = '8.0.2';
$OC_Channel = 'stable';
$OC_Build = '2015-03-09T13:29:12+00:00 8db687a1cddd13c2a6fb6b16038d20275bd31e17';

**Comment by bjoerns1983** [comment]
Here is the content of my version.php. Btw. i installed the latest owncloud 8.0.2-6 yesterday:

<?php 
$OC_Version = array(8,0,0,7);
$OC_VersionString = '8.0';
$OC_Channel = 'stable';
$OC_Build = '2015-02-07T02:34:55+00:00 df2808eec840c033b952e001ee8a063a93fae417';

**Comment by karlitschek** [comment]
@bjoerns1983 strange. this is not the file that is part of 8.0.2

**Comment by bjoerns1983** [comment]
Yes thats what i also think. I just looked at the at my bash history. At 16.03 i made a backup of my owncloud and updated from 7.0.4 directly to 8.0.0 via apt-get. I have not done it manually. The package available at this time must have been 8.0.
I am on a standard debian 7 with the OSBS Repos activated. Could it be that i have to use something else than apt-get update and after that apt-get install owncloud?

**Comment by bjoerns1983** [comment]
Finally sucess. I had to manually update owncloud-server Packahe (apt-get install owncloud-server).
Now i am on 8.0.2, but i dont think thats the way it should be.

Normally an apt-get install owncloud should be sufficient.

**Comment by bjoerns1983** [comment]
Next problem, searching the dpkg status file reveals that apart from owncloud and owncloud-server, all the other packages stayed (owncloud-3rdparty etc) at 8.0.0-9. I solved this problem by doing a apt-get upgrade.

But thats all a bit strange.

**Comment by karlitschek** [comment]
Can you please test again with 8.0.3? Please reopen if it still exists
