### ISSUE TITLE
Ghost section in the apps page when app store is disabled

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15056]
### Steps
1. Set "appstoreenabled" to false in config.php
2. Open the apps page
3. Click below "Not enabled"

![ghostsection](https://cloud.githubusercontent.com/assets/277525/6749406/37659406-cef0-11e4-9927-b3e51b00d887.png)

Observed on master

**Comment by karlitschek** [comment]
@DeepDiver1975
