### ISSUE TITLE
Unable to upload files using DavCopy

### ISSUE THREAD

**Issue by ziotibia81** [owncloud/core#15061]
Is not possible upload files using DavCopy (http://www.bluedoglimited.com/Downloads/SitePages/DavCopy.aspx)

Test was made using owncloud 8.0.2 on Ubuntu 14.04 (apache2+mysql).

Davcopy report error:

Remote server error: (401)  Unauthorized.

Same user, pass and url work perfectly using WinSCP

Here logs:

==> /var/log/owncloud.log <==
{"reqId":"e9b1813ffa172762d6fee2d1baf46b11","remoteAddr":"192.168.1.36","app":"webdav","message":"Exception: {\"Message\":\"No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(126): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(106): OC_Connector_Sabre_Auth->auth(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Plugin.php(108): OC_Connector_Sabre_Auth->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod('PROPFIND', '')\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(433): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(455): Sabre\\\\DAV\\\\Server->broadcastEvent('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('PROPFIND', '')\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(61): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(54): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":73}","level":0,"time":"2015-03-20T12:13:46+01:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}

==> /var/log/apache2/access.log <==
192.168.1.36 - - [20/Mar/2015:12:13:45 +0100] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 401 1043 "-" "DavCopy/1.4"

**Comment by DeepDiver1975** [comment]
@ziotibia81 can you connect to your owncloud installation with tools like cadaver? If yes this is most probably an issue with DavCopy

**Comment by ziotibia81** [comment]
I used webdav on winscp to connect to owncloud without probelms.
I will do more tests.

**Comment by ziotibia81** [comment]
DavCopy was made to work with MS Sharepoint. Maybe that Sharepoint webdav implementation has something little different form standard webdav.

I made a sniffing session.
Davcopy Send:
PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1
User-Agent: DavCopy/1.4
Depth: 0
Translate: F
Host: 192.168.117.11
Connection: Keep-Alive

Server Reply:
HTTP/1.1 401 Unauthorized
[....]

Davcopy exit with error 401.

Sniffing session using WinSCP.
WinSCP send:

OPTIONS /owncloud/remote.php/webdav/ HTTP/1.1
User-Agent: WinSCP/5.7 neon/0.30.1
Keep-Alive: 
Connection: TE, Keep-Alive
TE: trailers
Host: 192.168.117.11

Server Reply:
HTTP/1.1 401 Unauthorized
[....]

And now WinSCP retry OPTIONS query with Basic Auth.

Maybe that DavCopy expect a 403 repley intead of a 401 as described on http://tools.ietf.org/html/rfc4918#section-9.1.2

**Comment by DeepDiver1975** [comment]
To me this seems to be an issue with the client DavCopy - please get in touch with the devs. THX
