### ISSUE TITLE
Old files aren't removed from search index

### ISSUE THREAD

**Issue by resound88** [owncloud/core#15066]
Hi together,

accidentally I noticed, that old files aren't immediately removed from the search index, after they get deleted.
A run of the cronjob doesn't change anything.

I'm not sure if this is a known limitation or a bug.

I can reproduce it on Debian 6.

Best regards

**Comment by DeepDiver1975** [comment]
I assume you are using the app search_lucene - please reopen this issue in https://github.com/owncloud/search_lucene - THX
