### ISSUE TITLE
Problem with connect owncloud to a S3 Storage

### ISSUE THREAD

**Issue by alebeta90** [owncloud/core#15067]
Hello i have the next output from owncloud log when im trying to connect to my storage service.

Exception: {"Message":"[curl] 7: Failed to connect to x.x.x.x : Permission denied [url] http:\/\/bucketname.subdomain.company.com:9021","Code":0,"Trace":"#0 \/var\/www\/html\/owncloud\/apps\/files_external\/3rdparty\/aws-sdk-php\/Guzzle\/Service\/Client.php(136): Aws\\Common\\Client\\AbstractClient->send(Object(Guzzle\\Http\\Message\\Request))\n#1 \/var\/www\/html\/owncloud\/apps\/files_external\/3rdparty\/aws-sdk-php\/Guzzle\/Service\/Command\/AbstractCommand.php(153): Guzzle\\Service\\Client->execute(Object(Aws\\S3\\Command\\S3Command))\n#2 \/var\/www\/html\/owncloud\/apps\/files_external\/3rdparty\/aws-sdk-php\/Aws\/S3\/S3Client.php(665): Guzzle\\Service\\Command\\AbstractCommand->execute()\n#3 \/var\/www\/html\/owncloud\/apps\/files_external\/3rdparty\/aws-sdk-php\/Aws\/S3\/S3Client.php(396): Aws\\S3\\S3Client->checkExistenceWithCommand(Object(Aws\\S3\\Command\\S3Command), true)\n#4 \/var\/www\/html\/owncloud\/apps\/files_external\/lib\/amazons3.php(584): Aws\\S3\\S3Client->doesBucketExist('veeambucket')\n#5 \/var\/www\/html\/owncloud\/apps\/files_external\/lib\/amazons3.php(260): OC\\Files\\Storage\\AmazonS3->getConnection()\n#6 \/var\/www\/html\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(69): OC\\Files\\Storage\\AmazonS3->opendir('')\n#7 \/var\/www\/html\/owncloud\/lib\/private\/files\/cache\/scanner.php(250): OC\\Files\\Storage\\Wrapper\\Wrapper->opendir('')\n#8 \/var\/www\/html\/owncloud\/lib\/private\/files\/cache\/scanner.php(216): OC\\Files\\Cache\\Scanner->scanChildren('', true, 1)\n#9 \/var\/www\/html\/owncloud\/lib\/private\/files\/cache\/scanner.php(332): OC\\Files\\Cache\\Scanner->scan('', true, 1)\n#10 \/var\/www\/html\/owncloud\/lib\/private\/files\/utils\/scanner.php(108): OC\\Files\\Cache\\Scanner->backgroundScan()\n#11 \/var\/www\/html\/owncloud\/apps\/files\/ajax\/scan.php(29): OC\\Files\\Utils\\Scanner->backgroundScan('')\n#12 \/var\/www\/html\/owncloud\/lib\/private\/route\/route.php(135) : runtime-created function(1): require_once('\/var\/www\/html\/o...')\n#13 [internal function]: __lambda_func(Array)\n#14 \/var\/www\/html\/owncloud\/lib\/private\/route\/router.php(250): call_user_func('?lambda_11', Array)\n#15 \/var\/www\/html\/owncloud\/lib\/base.php(767): OC\\Route\\Router->match('\/apps\/files\/aja...')\n#16 \/var\/www\/html\/owncloud\/index.php(36): OC::handleRequest()\n#17 {main}","File":"\/var\/www\/html\/owncloud\/apps\/files_external\/3rdparty\/aws-sdk-php\/Aws\/Common\/Client\/AbstractClient.php","Line":264} 

I don't know why owncloud is trying to connect through apache, because this permison denied error is from apache.

All the best!
Thnks

**Comment by DeepDiver1975** [comment]
Looks like a configuration issue to me - missing or wrong credentials on the external storage configuration.

**Comment by alebeta90** [comment]
@DeepDiver1975 i can connect with other app like dragondisk with the same credentials and the same port. for this reason for me is so extrange this situation.

**Comment by PVince81** [comment]
Is this still happening with 8.0.5 or 8.1 ?

**Comment by PVince81** [comment]
If you still see this issue, please reopen and use the issue template https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by alebeta90** [comment]
@PVince81 Hello! Yes the problem was solved! thanks for all the support.!

All the best.!
Alejandro B.
