### ISSUE TITLE
Web interface does not show all the files present. WebDAV shows more directory contents

### ISSUE THREAD

**Issue by bong0** [owncloud/core#15070]
On the left of the screenshot you see the browser view of the directory. The right side shows the view in nautilus on gnome, the mounted WebDAV. A _lot_ of files are not accessible via the webinterface for no obvious reason

![screenshot from 2015-03-20 14 56 51](https://cloud.githubusercontent.com/assets/179111/6752887/239fa52a-cf12-11e4-9dc8-c8982709ebd0.png)

As the Listing suggest "1 folder and 50 files	" there should be 50 files...

Version 7.0.4

**Comment by DeepDiver1975** [comment]
the web view implements scrolling - might this be the issue?

**Comment by bong0** [comment]
@DeepDiver1975 But it doesn't even fill the screen oO

**Comment by DeepDiver1975** [comment]
Looks like you have a rather big screen and not all space is used. 

@PVince81

**Comment by Xenopathic** [comment]
Hmm, this looks like a HiDPI issue to me. A common problem with webapps that load a fixed amount, expecting there to be enough content for a scrollbar :laughing:

**Comment by bong0** [comment]
*facepalm*

**Comment by PVince81** [comment]
Please upgrade to 7.0.5. This has been fixed there through https://github.com/owncloud/core/pull/11524

Feel free to reopen if you still observe this issue in 7.0.5. Thanks.

**Comment by bong0** [comment]
@PVince81 Thank you very much! I'll poke the admin about that!
