### ISSUE TITLE
Error running cron.php

### ISSUE THREAD

**Issue by bboule** [owncloud/core#15087]
Server OS:  CentOS 6.5
Database MySQL
OC Version 8.0.2
PHP version 5.5.20

When attempting to run cron.php (manually or via crontab) I get the following error:

PHP Fatal error:  Class 'OCA\Files_Antivirus\OCA\Files_Antivirus\Cron\Task' not found in /var/www/html/owncloud/apps/files_antivirus/lib/backgroundscanner.php on line 112
Unexpected error!

I am using ClamAV over the network for this server (it is not installed locally).

**Comment by enoch85** [comment]
Is the Antivirus app activated?

**Comment by karlitschek** [comment]
@vicdeo

**Comment by VicDeo** [comment]
@bboule Please test https://github.com/owncloud/files_antivirus/pull/35
