### ISSUE TITLE
Follow-up of: Better message if session.save_path is not writeable during login

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#15089]
Hi,

the "login loop" in https://github.com/owncloud/core/issues/15053 got fixed by the PR https://github.com/owncloud/core/pull/15062.

But from my understanding instead of "looping back" to the login page the error page is only containing parts of the errors like:

```
{"reqId":"04f9da825b2ed619ade3427f2b0926d3","remoteAddr":"112.215.64.171","app":"PHP","message":"session_write_close(): open(\/var\/lib\/php\/session\/sess _82arf9b2jqc9k5gs065tohh586, O_RDWR) failed: Permission denied (13) at \/var\/www\/html\/owncloud\/lib\/private\/session\/internal.php#77","level":3,"time" :"2015-03-19T08:46:24+00:00"}
{"reqId":"04f9da825b2ed619ade3427f2b0926d3","remoteAddr":"112.215.64.171","app":"PHP","message":"session_write_close(): Failed to write session data (files ). Please verify that the current setting of session.save_path is correct (\/var\/lib\/php\/session) at \/var\/www\/html\/owncloud\/lib\/private\/session\/ internal.php#77","level":3,"time":"2015-03-19T08:46:24+00:00"}
```

Maybe it could be useful to show a more generic message instead because of:

1. From my experiences most users still can't interpret this error messages
2. No internal path on the filesystem are leaked

**Comment by DeepDiver1975** [comment]
The exception details are only displayed in debug mode. Any further error details are in the logs.

From my understanding this is sufficient for an admin to take further action to fix this. 

Or do I miss anything?

**Comment by RealRancor** [comment]
> The exception details are only displayed in debug mode. Any further error details are in the logs.

Ah, sorry. I wasn't aware of this.

> From my understanding this is sufficient for an admin to take further action to fix this. 

From my experience on the forums or IRC a lot of users are not able to interpret that error message, even if i think it should be clear. We even have a FAQ thread at the forums explaining this:

https://forum.owncloud.org/viewtopic.php?f=17&t=23315

but questions on how to interpret that error are still asked quite often.

**Comment by DeepDiver1975** [comment]
Hmmm ... this is nothing personal but - how hard is it to use a search engine passing in the error?

We are not the first project using php and solutions out there exist - I see no reason to add much more.

THX

**Comment by DeepDiver1975** [comment]
.... am I too deep into the technical side ...

**Comment by RealRancor** [comment]
Hi,

i fully understand your point and absolutely agree with you. But just join the forums and you will see that many people can't manage to use a search engine :)

**Comment by DeepDiver1975** [comment]
@RealRancor well ... one of the requirements these days for users is the capability to read ... and use search engines. I honestly see much more important tasks with the team. Closing therefore.

**Comment by RealRancor** [comment]
@DeepDiver1975 
I'm absolutely fine with closing this and also agree with you.

>one of the requirements these days for users is the capability to read ... and use search engines.

Join the forum for some hours and see thats not reality. :-/
