### ISSUE TITLE
Watcher policy doesn't seem to work with SFTP

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15081]
### Steps to reproduce
1. Setup SFTP external storage and mount it to "/sftp"
2. Set watcher policy to 1 (it's the default)
3. Navigate into "/sftp" in the web UI
4. Create a file "test.txt" in "/sftp" outside of OC (directly on the SFTP folder)
5. Refresh the web UI
6. Delete an already existing file that was in "/sftp" before mounting (directly on SFTP folder)
7. Refresh the web UI

### Expected result
At step 5 the new file "test.txt" should appear in the web UI.
At step 7 the file that was deleted must disappear from the web UI.

### Actual result
The web UI shows the old state from step 3.

### Versions
master (e44ab2dcfed7a613af145174ee93668c931adf56)

I debugged a bit in the code and even though I saw the watcher being initialized properly, it never seemed to try and check for updates / rescan.

@icewind1991 can you have a look ? Or am I misunderstanding the default watch policy ?
I seem to remember that this used to work before.

**Comment by DeepDiver1975** [comment]
setting 8.1 - we want to have the policy as mount option - should really work

@icewind1991 please have a look - THX

**Comment by icewind1991** [comment]
This seems more like a bug in the sftp change detection than with the watcher policy, do the sftp unit tests run successfully for you?

**Comment by PVince81** [comment]
Hmmm, they are failing against a local SFTP account:
```
1) Test\Files\Storage\SFTP::testDirectories with data set #0 ('folder')
Failed asserting that true is false.

/srv/www/htdocs/owncloud/tests/lib/files/storage/storage.php:92

2) Test\Files\Storage\SFTP::testDirectories with data set #1 (' folder')
Failed asserting that true is false.

/srv/www/htdocs/owncloud/tests/lib/files/storage/storage.php:92

3) Test\Files\Storage\SFTP::testDirectories with data set #2 ('folder ')
Failed asserting that true is false.

/srv/www/htdocs/owncloud/tests/lib/files/storage/storage.php:92

4) Test\Files\Storage\SFTP::testDirectories with data set #3 ('folder with space')
Failed asserting that true is false.

/srv/www/htdocs/owncloud/tests/lib/files/storage/storage.php:92

5) Test\Files\Storage\SFTP::testDirectories with data set #4 ('spéciäl földer')
Failed asserting that true is false.

/srv/www/htdocs/owncloud/tests/lib/files/storage/storage.php:92

6) Test\Files\Storage\SFTP::testHashInFileName
Failed asserting that false matches expected 'data'.

/srv/www/htdocs/owncloud/tests/lib/files/storage/storage.php:395

7) Test\Files\Storage\SFTP::testRenameOverWriteDirectory
rename must return true on success
Failed asserting that false is true.

/srv/www/htdocs/owncloud/tests/lib/files/storage/storage.php:460
```

Same for the SFTP docker test.

Have you tried if the watcher works with SMB ? (I'll try that later)

**Comment by PVince81** [comment]
I tried with SMB and before I set the policy explicitly, it seemed to work fine at first.
After setting the policy to "Never" (0), it stopped detecting updates, which is correct.
But then when setting it to either "Always" (2) or back to 1, further changes to the SMB storage (like creating new files) weren't detected.

**Comment by PVince81** [comment]
This is the config after I set it back:
```
{
    "user": {
        "all": {
            "\/$user\/files\/smb": {
                "id": 1,
                "class": "\\OC\\Files\\Storage\\SMB",
                "options": {
                    "host": "localhost",
                    "user": "vincent",
                    "password": "",
                    "share": "shared",
                    "root": "octest",
                    "password_encrypted": "REMOVED"
                },
                "priority": 100,
                "mountOptions": {
                    "previews": true,
                    "filesystem_check_changes": 1
                },
                "storage_id": "4"
            }
        }
    }
}
```

**Comment by PVince81** [comment]
Looks like the "filesystem_check_changes" is returned as string instead of int.

**Comment by PVince81** [comment]
It's a bug in the mount options parsing code: https://github.com/owncloud/core/pull/14925#issuecomment-86625511
Closing
