### ISSUE TITLE
Jenkins timezone tests fail

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#15094]
https://ci.owncloud.org/job/server-master-linux/database=sqlite,label=SLAVE/1400/testReport/%28root%29/Test_Util__testFormatDateWithTZFromSession/testFormatDateWithTZFromSession_with_data_set__3/

```
Test_Util::testFormatDateWithTZFromSession with data set #3 (3.5, 'October 13, 2012 at 3:23:25 P...T+3:30')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'October 13, 2012 at 3:23:25 PM GMT+3:30'
+'October 13, 2012 at 11:53:25 AM GMT+0'

/var/jenkins/workspace/server-master-linux/database/sqlite/label/SLAVE/tests/lib/util.php:80

**Comment by rullzer** [comment]
git bisect tells us that it is commit: 276d67808013927c8777ffd92a2cbe09285f449f <-- however that just seems to be the commit where @nickvergessen introduced the checks.

But it is strange they fail all of a sudden. Since that commit is from a month ago.

**Comment by DeepDiver1975** [comment]
wild guess the system's timezones got updated and there is no timezone anymore which matches GMT+3.5

**Comment by rullzer** [comment]
so the only country using +3.5 is Iran. Which switched to daylight saving time sun march 22 at 00:00 (+3.5, so 20:30 GMT).

However that means that currently there is no +3.5 timezone but a +4.5.

Seems the unit tests needs to be adapted.

**Comment by DeepDiver1975** [comment]
nice catch - daylight is causing this.
