### ISSUE TITLE
Centos 6.x Repository missing files for 8.0.2

### ISSUE THREAD

**Issue by globaljunk** [owncloud/core#15096]
The public repo for CentOs 6 is missing the files;
owncloud-3rdparty-8.0.2-13.1.noarch.rpm:
owncloud-app-files_external-8.0.2-13.1.noarch.rpm

Even though they are listed online at:
http://download.opensuse.org/repositories/isv:/ownCloud:/community/CentOS_CentOS-6/noarch/

Trying to perform an upgrade using the repo I keep getting 404 errors on these two files.

**Comment by karlitschek** [comment]
@jnweiger any idea?

**Comment by brycekottke** [comment]
I to am getting this error after adding the isv community repo and doing a yum install owncloud.

#OS: 
Centos 6.6 Final

#Error:
Is this ok [y/N]: y
Downloading Packages:
http://download.opensuse.org/repositories/isv%3A/ownCloud%3A/community/CentOS_CentOS-6/noarch/owncloud-3rdparty-8.0.2-13.1.noarch.rpm: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.
http://download.opensuse.org/repositories/isv%3A/ownCloud%3A/community/CentOS_CentOS-6/noarch/owncloud-app-files_external-8.0.2-13.1.noarch.rpm: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.

Error Downloading Packages:
  owncloud-app-files_external-8.0.2-13.1.noarch: failure: noarch/owncloud-app-files_external-8.0.2-13.1.noarch.rpm from isv_ownCloud_community: [Errno 256] No more mirrors to try.
  owncloud-3rdparty-8.0.2-13.1.noarch: failure: noarch/owncloud-3rdparty-8.0.2-13.1.noarch.rpm from isv_ownCloud_community: [Errno 256] No more mirrors to try.

Any Ideas?

**Comment by razyr** [comment]
Also getting 404 errors on upgrading 8.0.0 to 8.0.2 on two different CentOS 7.0 servers using the isv_ownCloud_community repo.

`Error downloading packages:
  owncloud-app-files-8.0.2-13.1.noarch: [Errno 256] No more mirrors to try.
  owncloud-app-files_videoviewer-8.0.2-13.1.noarch: [Errno 256] No more mirrors to try.
  owncloud-app-files_encryption-8.0.2-13.1.noarch: [Errno 256] No more mirrors to try.
  owncloud-app-user_ldap-8.0.2-13.1.noarch: [Errno 256] No more mirrors to try.
  owncloud-app-updater-8.0.2-13.1.noarch: [Errno 256] No more mirrors to try.`

**Comment by andreasbaumann** [comment]
Experiencing this one too. Sounds like a Open Build Service Mirrorbrain bug.

**Comment by karlitschek** [comment]
@jnweiger can you have a look please?

**Comment by razyr** [comment]
Problem seems to be resolved for my CentOS 7 servers.  Successfully updated both systems to OC 8.0.2 via yum update.

**Comment by jnweiger** [comment]
The packages are on the master download server of the open build service.

I agree with @andreasbaumann that this looks like an issue with the mirror infrastructure.
Testing the URLs that produces errors for @brycekottke , they work fine for me. 

If there is anybody who can pinpoint *which* mirror is broken, please let us know.

**Comment by brycekottke** [comment]
Strange, I am now only receiving this error on the following package when trying to install this morning:

Error Downloading Packages:
  owncloud-app-user_ldap-8.0.2-13.1.noarch: failure: noarch/owncloud-app-user_ldap-8.0.2-13.1.noarch.rpm from isv_ownCloud_community: [Errno 256] No more mirrors to try.

Steps Taken to Resolve:

$ yum clean metadata
$ yum clean all

Also have modified my /etc/resolv.conf and added Google's public DNS servers (8.8.8.8 and 8.8.4.4) in case of a DNS caching issue, but still getting error on ldap rpm. the 3rdparty and appfiles_external rpm's downloaded successful now though.

**Comment by globaljunk** [comment]
jnweiger, I found that tux.rainside.sk is failing, although I was able to resolve some mirrors now and was able to update via yum.
  
http://tux.rainside.sk/opensuse/repositories/isv:/ownCloud:/community/CentOS_CentOS-6/noarch/owncloud-3rdparty-8.0.2-13.1.noarch.rpm


Thanks for looking into this.

**Comment by andreasbaumann** [comment]
My advice would be: use the OBS only for building the packages, not for hosting them in a download
area.

**Comment by andreasbaumann** [comment]
As the failing package is noarch and RHEL6 and Centos6 should really be the same, I managed
to update with the following procedure:

yum update (let it fail in owncloud-app-files).

Then download manually the RHEL6 file:

wget http://download.opensuse.org/repositories/isv:/ownCloud:/community/RedHat_RHEL-6/noarch/owncloud-app-files-8.0.2-13.1.noarch.rpm

yum localinstall owncloud-app-files-8.0.2-13.1.noarch.rpm

**Comment by jnweiger** [comment]
duplicte of https://github.com/owncloud/core/issues/13991

**Comment by jnweiger** [comment]
Fixed! The issue was found in the scanner that feeds the opensuse mirrorbrain.
Please try again and reopen if you still have issues.

**Comment by sokratisg** [comment]
Excuse me for opening this up again, but I think there still may be a problem with the repos.

Just tried to install OC 8.0.2 on CentOS 6.6 and still 404 error on an rpm package:
...
http://download.opensuse.org/repositories/isv%3A/ownCloud%3A/community/CentOS_CentOS-6/noarch/owncloud-server-8.0.2-16.1.noarch.rpm: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.
...
Error Downloading Packages:
  owncloud-server-8.0.2-16.1.noarch: failure: noarch/owncloud-server-8.0.2-16.1.noarch.rpm from isv_ownCloud_community: [Errno 256] No more mirrors to try.

**Comment by DeepDiver1975** [comment]
For me the link resolves to http://suse.lagis.at/repositories/isv:/ownCloud:/community/CentOS_CentOS-6/noarch/ - where the package is missing. Just another case of mirror out of sync. Not much we can do - but maybe out friends at suse can? @jnweiger

**Comment by jnweiger** [comment]
Notified the helpful souls at suse. 
A mirror missing a package is okayish. But no more mirrors to try is a real issue.
Most of the suse people are travelling (including myself) please ping me again if it does not improve by Sunday.

**Comment by sokratisg** [comment]
@jnweiger it seems that problem still hasn't been resolved. Can you please have a look at it?
Unfortunately it is a blocking issue for new OC installations and I think it should affect everyone redirected to this repo.

**Comment by sokratisg** [comment]
everything looks super now! thank you
