### ISSUE TITLE
Working on file and saving results in failed synchronization and file deleted from Google Drive with windows sync client

### ISSUE THREAD

**Issue by zapotah** [owncloud/core#15092]
Working in the Google Drive folder on a workstation, editing a file and saving it results in the file being deleted on Google Drive and creating a conflict in the sync client directory.

Server log indicates "Error calling PATCH https://www.googleapis.com/drive/v2/files/REDACTED?setModifiedDate=true: (404) File not found: REDACTED"

Using Windows owncloud sync client version 1.8.0, Windows 8.1, Owncloud server 8.0.2 on httpd 2.4 and php 5.4 on CentOS 7. No other issues have manifested on the system.

The issue manifests with a fresh install.

**Comment by DeepDiver1975** [comment]
scheduling for 8.2 where we want to touch all external file systems.

**Comment by PVince81** [comment]
Please try again with 8.2.2 or 8.1.5.
There were some fixes for GDrive.

If the problem persists with these versions, feel free to reopen.
