### ISSUE TITLE
PHP warning about reference

### ISSUE THREAD

**Issue by tuxmaster** [owncloud/core#15090]
In the log file the message:
{PHP} Only variables should be passed by reference at /var/www/html/owncloud/lib/private/cache/fileglobalgc.php#50
occurs very often.

**Comment by RealRancor** [comment]
Very likely a dup: https://github.com/owncloud/core/issues/14696 , https://github.com/owncloud/core/issues/15010

**Comment by tuxmaster** [comment]
Yes it is the same.
Using the search function about "PHP" don't result anything .
So I think that was the reson for the dup.

**Comment by RealRancor** [comment]
Hi,

yes that can happen when using such shorter keywords. To find possible duplicates try to use keywords like "fileglobalgc" to get better matches.
