### ISSUE TITLE
Blank screen after update from 7.0.4 to 8.0.2 php5-hash not available

### ISSUE THREAD

**Issue by hagenbuch** [owncloud/core#15102]
Someone mentioned already that if you get I blank screen "after" the update, you'd have to install "php5-hash".

Now how are we supposed to do that?

"apt-get install php5-hash" yields no results, as well as "a2enmod php5-hash".

I have a standard Debian 7.0 installation out of the box.

**Comment by RealRancor** [comment]
Hi,

as written in your forum thread you probably have a completely different problem here. php5-hash seems to be only needed for FreeBSD and similar, not for Debian as this is not available there.

Please follow the complete first post of the forums thread here: https://forum.owncloud.org/viewtopic.php?f=31&t=26310.

A wild guess:

Disable the calendar and contacts app and your instance is running again.

**Comment by hagenbuch** [comment]
Many thanks - yes I did not disable the 3rd party apps. Allow me some humble remarks:

I'm a casual admin that does not "sleep" next to owncloud. So when I see there is an automatic updater that even warns me about folders like /stats/ that have been created by AWstats I think everything will be cared for. That's why I started it. 

1. Why is the updater not able to deactivate them while it had been able to install them all?

Du you know the principle of the least surprise?

2. If I should read several manuals and hints in a form somewhere, make a forum account AND a github account before updating, then please, dear developers, do NOT provide an updater. A complete reinstall will be quicker for me.

3. It's great that there is an "occ" command to deactivate the 3rd party apps, but you have to name them one by one. Now, as I have no access whatsoever, how can I get of a list of 3rd party apps? Or can I say "*"?

Thanks -

**Comment by RealRancor** [comment]
Hi,

the main problem here is that 3rdparty apps are already deactivated. But currently calendar and contacts, which are now also seen as 3rdparty (or better say non-core) apps are not and this is very likely your current problem.

Those two apps are also deactivated in one of the next OC versions to avoid this: https://github.com/owncloud/core/pull/14862 , https://github.com/owncloud/core/issues/14852

**Comment by DeepDiver1975** [comment]
I guess we can close this then - THX @RealRancor for your support

**Comment by RealRancor** [comment]
@DeepDiver1975 
My post above is just a guess / hint that the calendar or contacts app could cause this. I don't know if this is the real problem here, better wait until @hagenbuch is confirming that one of those apps are causing this before closing the issue.

**Comment by hagenbuch** [comment]
I can confirm that deactivating calendar and contacts re-enabled my owncloud. The rest of the apps work, except "Music" - which also show a blank screnn. When I return to the previous URL, the rest runs fine..

Thanks for your answers..

**Comment by RealRancor** [comment]
@hagenbuch 
Thanks for the confirmation. The "music" is working here with on OC8 but there are some reports like https://github.com/owncloud/music/issues/355 and https://github.com/owncloud/music/issues/345.
