### ISSUE TITLE
Don't use fetchAll() - uses potentially too much memory

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#15105]
https://github.com/owncloud/core/issues/8116#issuecomment-84940356

**Comment by rullzer** [comment]
Related files:

````
apps/files_trashbin/lib/trashbin.php
apps/user_ldap/lib/mapping/abstractmapping.php
apps/user_ldap/lib/jobs.php
apps/user_ldap/lib/helper.php
apps/files_sharing/lib/external/manager.php
apps/files_sharing/lib/helper.php
apps/files_sharing/tests/migrationtest.php
apps/files_sharing/tests/server2server.php
apps/files_sharing/tests/sharedmount.php
apps/files_sharing/api/local.php
cover/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php.xml
cover/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php.xml
cover/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php.xml
lib/repair/collation.php
lib/private/files/cache/cache.php
lib/private/share/share.php
lib/private/db/statementwrapper.php
tests/lib/db.php

**Comment by delbydev** [comment]
Searching Mr G to find a resolve for this when running a console.php files:scan for a large directory structure

PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 80 bytes) in /usr/local/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 128


Traced this Issue via google searches and linking to other (now closed) GH issues.


Running OC 8.2.2 on FreeBSD 9.3 with nginx and php version 5.5
Rescanning files using the console.php for a directory structure containing circa 230K files 
(software installation shared folder for OS X)
I could maybe slim it down to 184K files but that might mean our OC installation would start to look disjointed.

Is this perhaps a case of throw more resource at the MariaDB or should I be looking somewhere else such as this main issue?

**Comment by rullzer** [comment]
@delbydev 128MB for php is a bit on the low side if you want to scan 230K files.

**Comment by PVince81** [comment]
@DeepDiver1975 junior job ?

**Comment by imujjwal96** [comment]
Will replacing each and every fetchAll with fetch in a loop suffice?
