### ISSUE TITLE
Adapt l10n.pl to also parse translations in handlebars templates

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15106]
This ticket https://github.com/owncloud/core/pull/14925/files#diff-c428169f7899b3a581d46ca00ce88080R18 will add a new helper for translations in handlebars templates.

These should also be parsed properly by the l10n.pl script (at least once that PR is merged)

@DeepDiver1975

**Comment by DeepDiver1975** [comment]
hmm - I doubt that gettext has any idea about handlebars ..... can we either inject the translation strings in php or js?

**Comment by PVince81** [comment]
Are you saying that parsing `$l->l10n('')` and `t()` is a feature of gettext ?

We might be able to inject the text using template variables, but that somewhat defies the purpose of having a template in the first place.

**Comment by PVince81** [comment]
might also need something similar for vuejs/pug templates then...

cc @felixheidecke

**Comment by DeepDiver1975** [comment]
afaik not - market app is vue.js based and translations strings are extracted from the final generated js code.

**Comment by felixheidecke** [comment]
indeed no changes needed for vue.
