### ISSUE TITLE
Shared folders and anonymous uploads

### ISSUE THREAD

**Issue by musaa32** [owncloud/core#15101]
### Steps to reproduce
1. Create a folder 
2. Insert a file into the new folder
3. Share it with **user** e.g. JohnDoe (give him all rights)
4. Log-In with user JohnDoe and upload a new file into the shared folder
### Expected behaviour

The problem here is that the user who shared the folder can't see the uploaders name, if JohnDoe adds a new file, the other user sees only the new file. In my oppinion, the user should also see the username like JohnDoe sees it.

![johndoe](https://cloud.githubusercontent.com/assets/6105361/6777583/40aefedc-d14b-11e4-828e-81dc8a70ca4b.png)
### Actual behaviour

The user to the folder belongs only sees the new file without username
![folder owner](https://cloud.githubusercontent.com/assets/6105361/6777594/52c6447c-d14b-11e4-8534-95ec7c2798a0.png)
### Server configuration

fedora 21

**Web server:**
nginx 1.7

**Database:**
MariaDB 10.10.15

**PHP version:**
 5.6.6
**ownCloud version:** (see ownCloud admin page)
8.0.2(stable)

**Updated from an older ownCloud or fresh install:**
fresh install

**List of activated apps:**
standard apps

**The content of config/config.php:**
standard config.

**Comment by PVince81** [comment]
This is not a bug but a feature request.

Currently ownCloud doesn't have the information of who uploaded what, because the owner of the file is automatically whoever own the share, not the uploader.

The closest you'd have is to look at the activity app, which will show you who uploaded the file when.

**Comment by ABSAhmad** [comment]
Was this ever added?
Everyone's confused over here because of this.

**Comment by PVince81** [comment]
No, because ownCloud does not track who uploads which files.
The files automatically belong to whoever the storage owner is.

For user shares, the activity app has a log of which user did what but for anonymous upload there is no way to know who the user is so it appears as "public user"
