### ISSUE TITLE
Separate admin settings sections for Sharing & Federated sharing

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#15109]
Currently there are two separate sections in the admin section: Sharing and Federated Cloud Sharing. The inability for us to force sort the settings makes this worse, since they end up in completely different places. This is confusing.

Instead, Federated Cloud Sharing with its measly 2 checkboxes should be a sub-point of Sharing.

@schiesbn

**Comment by DeepDiver1975** [comment]
fixed in oc10
