### ISSUE TITLE
Question: What should do the function getSharesFromFolder in API local.php OCS

### ISSUE THREAD

**Issue by libasys** [owncloud/core#15100]
Hello, i am working on a app that gives me an overview of all sharees within a cloud from a user,
but if i would like to use the function getSharesFromFolder, than it returns nothing. Do i have understand the function false or should this list all files within this shared folder?

normal call owncloud_base_url/ocs/v1.php/apps/files_sharing/api/v1/shares?path=path&subfiles=true

but here nothing happens i have to modify this function like
added 2 new urlparams in the function getAllShares
Now i can list a folder with the specific rights of an share (user,group, bylink)
```
if(isset($_GET['share_with'])){	
				$params['shareWith'] =$_GET['share_with'];
			}
			if(isset($_GET['share_type'])){	
				$params['shareType'] =$_GET['share_type'];
			}
```

```

/**
		/**
	 * get share from all files in a given folder (non-recursive)
	 * @param array $params contains 'path' to the folder
	 * @return \OC_OCS_Result
	 */
	private static function getSharesFromFolder($params) {
		$path = $params['path'];
		$shareWith =$params['shareWith'];
		$shareType= $params['shareType'];
		
		
		$view = new \OC\Files\View('/'.\OCP\User::getUser().'/files');

		if(!$view->is_dir($path)) {
			return new \OC_OCS_Result(null, 400, "not a directory");
		}
		
		$content = $view->getDirectoryContent($path);

		$result = array();
		foreach ($content as $file) {
			// workaround because folders are named 'dir' in this context
			$itemType = $file['type'] === 'file' ? 'file' : 'folder';
			
			$shares = \OCP\Share::getItemShared($itemType, $file['fileid'],\OCP\Share::FORMAT_NONE,null,true);
			
			if($shares) {
					foreach($shares as $share){
						$sShareItemWith=$share['share_with'];
						//Password protected
						if($share['share_type'] == 3 && $share['share_with'] !=''){
							$sShareItemWith='';
						}
						
						if($sShareItemWith == $shareWith && $share['share_type'] == $shareType){	
							$shareFile[]=array(
								'id' => $file['fileid'],
								'item_type' => $itemType,
								'file_target' => $file['name'],
								'share_type' => (int) $share['share_type'],
								'share_with' => $share['share_with'],
								'share_with_displayname' =>$share['share_with_displayname'],
								'permissions' => $share['permissions'],
								'uid_owner' => $share['displayname_owner'],
								'token' => $share['token'],
								'parent' => $params['itemSource'],
								'stime' => $share['stime'],
								'file_source' => $file['fileid'],
								'item_source' => $file['fileid'],
								'expiration' => $share['expiration']
							);
						
						$receivedFrom =  \OCP\Share::getItemSharedWithBySource($itemType, $file['fileid'],\OCP\Share::FORMAT_NONE,null,true);
						
							if ($receivedFrom) {
								$shareFile[]['received_from'] = $receivedFrom['uid_owner'];
								$shareFile[]['received_from_displayname'] = \OCP\User::getDisplayName($receivedFrom['uid_owner']);
							}
							
							break;
					 }
				}
					
			}
		}

		return new \OC_OCS_Result($shareFile);
	}
```

is this behaviour now ok or do i thinking the false way?
Thanks!

**Comment by PVince81** [comment]
@schiesbn

**Comment by PVince81** [comment]
and maybe @rullzer

**Comment by rullzer** [comment]
@libasys I do not really understand what you try to do.

Assume the following folder stucture

    foo/
      bar/
      baz.txt
If I now share all of them by link.

Now If I do

    .../ocs/v1.php/apps/files_sharing/api/v1/shares?path=foo
It shows 1 share (foo)

Now if I do:

    .../ocs/v1.php/apps/files_sharing/api/v1/shares?path=foo&subfile=true
It shows 2 shares (bar and baz.txt)

Is that now what you expected?

**Comment by libasys** [comment]
ok i done a test on the demo of owncloud:
folder structure
/test
/test/sub
test/file.txt
test/file1.txt
test.file2.txt
I share the folder test by Link and by user Foo
Now the call:
```
/ocs/v1.php/apps/files_sharing/api/v1/shares?path=test&subfile=true&format=json
```
Listing in json Format and it returns information about the mainfolder but not for the subfiles:
```
{"ocs":{"meta":{"status":"ok","statuscode":100,"message":null},"data":[{"id":31468,"item_type":"folder","item_source":"131","parent":null,"share_type":3,"share_with":null,"file_source":131,"file_target":"\/test","path":"test","permissions":1,"stime":1427183775,"expiration":null,"token":"mGeUah1e6h0hH4o","storage":1142,"mail_send":"0","uid_owner":"test","share_with_displayname":null,"displayname_owner":"test"},{"id":31469,"item_type":"folder","item_source":"131","parent":null,"share_type":0,"share_with":"foo","file_source":131,"file_target":"\/test","path":"test","permissions":31,"stime":1427183779,"expiration":null,"token":null,"storage":1142,"mail_send":"0","uid_owner":"test","share_with_displayname":"foo","displayname_owner":"test"}]}}
```
and for my understanding  it should display the directory content of the folder like:
/test
/test/sub
test/file.txt
test/file1.txt
test.file2.txt

but that's not happend

with the changes above in my app first call:
```
/ocs/v1.php/apps/files_sharing/api/v1/shares
```
![shares](https://cloud.githubusercontent.com/assets/2439975/6797714/9fd798e6-d205-11e4-8774-5bdb75b83687.jpg)

And now if i click on the the link by object id i do the call
```
/ocs/v1.php/apps/files_sharing/api/v1/shares?path=GPS&subfile=true&format=json
```
![shares-subfiles](https://cloud.githubusercontent.com/assets/2439975/6797723/bdb33cda-d205-11e4-9eb4-84bd0a1229f7.jpg)

And that should be the right behaviour or not?

**Comment by rullzer** [comment]
No, the OCS Share API only returns information about shares. For directory listing you should use the webdav endpoint.

**Comment by libasys** [comment]
But in your first comment, you get the same result as me, by call &subfiles=true, you only shared the main folder but in your call &subfiles=true you get the sub folder and the file? and what is now the different? the function getSharesFromFolder makes a call to get the directory content, and the description of the function says: "get share from all files in a given folder (non-recursive)"!

**Comment by rullzer** [comment]
@libasys no I shared all files. If I add more files that are not shared I will not see them.

The explanation exactly says what is does.  

    "get share from all files in a given folder (non-recursive)"

So for a given folder we get all the shares in the toplevel of that folder.

So all the other files are ignored. Which is good API behaviour since the results could be huge.

**Comment by libasys** [comment]
Ahh ok now i am understanding, the api shows only additional sharees of a folder content, sharees shared with other user than the shared user of the folder!

**Comment by rullzer** [comment]
Yes, it is only for shares.
To obtain a directory listing use webdav.

I'll close this issue now.
