### ISSUE TITLE
Remote share mount point cannot be reshared with local users

### ISSUE THREAD

**Issue by ymolinet** [owncloud/core#15116]
I'm just installed two OC8.0.2 and I use a public shared folder to sync data between each OC.
In the "master" OC, I have created the folder, shared it by a public share, and set permission for the local users.
In the "slave" OC, I have "connected" the remote shared folder and set permission for the local users with the admin account.

When an user of the slave OC log in the web gui of the slave OC, he can access to the remote share folder and work with it. But this public folder is not visible by webdav and OC client (Windows).

https://forum.owncloud.org/viewtopic.php?uid=25511&f=31&t=27290&start=0

**Comment by PVince81** [comment]
Can you provide more detailed info/steps ? How did you "connect" the slave OC ? Did you use the publicwebdav endpoint ? It might help if you could express it with steps (click this, enter this, do this, etc)

**Comment by ymolinet** [comment]
1. I create a folder with admin account on my "Master OC"
2. I share it with public link, allow modify
3. I add to specific permission for "Master OC" users
4. I call the public link in my browser, and use "Add to my owncloud" to Add in the "slave OC", enter the "Slave OC" url.
5. I login with the admin account of my "Slave OC". I see my shared folder in the WebUI.
6. I add some permission to this for local "Slave Users".
7. I logout the admin account from the webui
8. I login in the webui with a local "Slave" account, I see the shared folder, I can work with.
9. I try to configure my owncloud client (Windows) but the shared folder is not visible.
10. I try to access by webdav (Windows) but the shared folder is not visible.

**Comment by ymolinet** [comment]
for webdav, I call http://myowncloudurl/remote.php/webdav and provide local user credential.

**Comment by PVince81** [comment]
Ah I see, you're using server to server sharing aka federation. Good.

What do you mean with "I add to specific permission" at step 3 ? Do you mean you also share the folder with local user, then specify access permissions ("can edit", "can share") ?

**Comment by ymolinet** [comment]
yes. I add permission to allow other user to write and use this folder

**Comment by ymolinet** [comment]
The shared folder, on the master, is used by other user without any problems. The issue occur only on the slave (step 6 and other)

**Comment by PVince81** [comment]
I tried the following steps with both 8.0.2:
1. On ownCloud A, create two users "user1" and "user2"
2. Add "user1" and "user2" into a group "group1"
3. Create a folder "fold"
4. Share "fold" with public link and allow editing
5. Share "fold" with "group1"
6. Open the public link
7. Click "Add to ownCloud"
8. Enter the URL of ownCloud B and login as admin@ownCloudB
9. On ownCloud B, create two users "buser1" and "buser2", add them to group "bgroup1"
10. Share "fold" with "bgroup1"
11. Still on ownCloud B, login as "buser1"
12. Hmm, "buser1" doesn't see the folder
13. Login as admin on ownCloud B
14. Create another user "buser3"
15. Share "fold" with "buser3"
16. Login as "buser3"
17. Still nothing in the web UI

It looks like you've got another variation where somehow the last user was able to see the folder in the web UI but not through WebDAV.

**Comment by PVince81** [comment]
Might be another variation of https://github.com/owncloud/core/issues/15202

I'll check if some PRs fix that

**Comment by PVince81** [comment]
Hmmm no, no luck.

I think this bug can be summarized as "Remote share mount point cannot be reshared with local users". I'll update the title.

**Comment by MTRichards** [comment]
@carlaschroder Can you document this limitation in release notes?
Thanks.

**Comment by carlaschroder** [comment]
https://github.com/owncloud/documentation/commit/3ca0f517ffb880a265ff07aaf33b98db9f588830

**Comment by PVince81** [comment]
There was a fix recently on master regarding resharing, but it did not fix this. Still happening on e1923bac07305fadb136f80ca098cd9f7e454f22

I suspect that maybe the mount points of the resharer aren't initialized, so it's like the folder would not exist so it cannot appear for the recipient.

Needs further research.

**Comment by PVince81** [comment]
Yes, that's a mountpoint issue.
"root" is the user receiving the remote share "s2s" then reshared it with "user1" (through group)

```
$evalResult                      = (array[4]);
  $evalResult->/                 = (object|OC\Files\Mount\MountPoint[8])+;
  $evalResult->/user1/           = (object|OC\Files\Mount\MountPoint[8])+;
  $evalResult->/root/            = (object|OC\Files\Mount\MountPoint[8])+;
  $evalResult->/user1/files/s2s/ = (object|OCA\Files_Sharing\SharedMount[9])+;
```

Here we can see that the mount point "/root/files/s2s" is missing.

**Comment by cdamken** [comment]
@MorrisJobke 

00003129

**Comment by PVince81** [comment]
Ok, the problem is as follows:
1) The External\Manager for external mounts is triggered by the "setup" hook. "setupFS()" is called for the current user, so that user would have their remote shared mounted. This works when logging in as "root"

2) When logging in as "user1", there is code that will also gather the mount points of "root" (since "user1" is receiving a local share from "root"). However that piece of code uses "initMountPoints()" instead of "setupFS()". So the "setup" hook is not triggered for "root", which in turn misses the code that would gather external mounts for that user.

Two possible solutions so far:
- move the hook triggering to "initMountPoints()", but that could have other side effects.
or
- use "setupFS()" instead of "initMountPoints()" when mounting mount points of another user when gathering shares (not the logged in one).

Both solutions are dangerous and risk causing side effects.

This will need more time to investigate a proper solution, so I think 8.2 is a fitting target.

**Comment by PVince81** [comment]
@icewind1991 see previous comment

**Comment by icewind1991** [comment]
3\. Move external mount managing to a mountprovider

**Comment by cdamken** [comment]
@PVince81 @icewind1991 Any news?

**Comment by PVince81** [comment]
This is scheduled to 8.2

**Comment by PVince81** [comment]
> 3. Move external mount managing to a mountprovider

@icewind1991 didn't you do that already ?

**Comment by PVince81** [comment]
@icewind1991 what about the mount provider ?

**Comment by icewind1991** [comment]
No, only internal shares have been moved over atm

**Comment by icewind1991** [comment]
Fix is here: #19589

**Comment by MorrisJobke** [comment]
> 00003129

@cdamken Fixed in 8.2 ;)

**Comment by cdamken** [comment]
> @cdamken Fixed in 8.2 ;)

Thanks @MorrisJobke

**Comment by morphiumdeus** [comment]
I'm having the same problem with OC 9.0.
Can you confirm it has been fixed?

**Comment by PVince81** [comment]
@morphiumdeus can you provide reproduction steps and setup info ? https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

You can compare your steps with https://github.com/owncloud/core/issues/15116#issuecomment-85071033
