### ISSUE TITLE
How to deinstall an app?

### ISSUE THREAD

**Issue by hagenbuch** [owncloud/core#15117]
Hello,

apparently my "music" app might have a problem with owncloud 8. 

I have downloaded the *-music.zip file. Now I am looking for a way how to install it. What I expect would be an upload link in the "Apps" section or a hint where I should put these files.

Also: How do I uninstall an app? I see only buttons to activate / deactivate them.

Thanks!

**Comment by karlitschek** [comment]
deactivate is the correct way to deinstall an app.
Is this not working?

**Comment by jancborchardt** [comment]
@hagenbuch also, you need to put the new »music« folder into the `apps` subfolder of the owncloud folder.

**Comment by jancborchardt** [comment]
@hagenbuch and please report any problems with the Music app to https://github.com/owncloud/music/issues cc @MorrisJobke

**Comment by hagenbuch** [comment]
Thanks - music app is not visible any more after I deactivated it. I can't even activate it.
