### ISSUE TITLE
File & Folder locking 

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#15122]
## Solution Approach

- add columns to filecache table identifying the lock state (lock user or lock client or lock session id, lock timeout)
- operations lock folders and files before performing operations
- access to folders and files which are locked results in exception and http status code 415/Locked
- lock status is exposed via webdav properties 
- lock status is visible in the web browser
- web dav clients CANNOT actively loc files/folders

**Comment by DeepDiver1975** [comment]
@karlitschek as just discussed

**Comment by DeepDiver1975** [comment]
Alternative approach which might help in searching the file hierarchy is to have an isolated lock table.

@PVince81 we have been talking about this right.

**Comment by PVince81** [comment]
We already had a ticket: https://github.com/owncloud/core/issues/11804

**Comment by PVince81** [comment]
An isolated lock table is maybe better, but if we map it by file id we might get in trouble in some situations...

**Comment by DeepDiver1975** [comment]
> An isolated lock table is maybe better, but if we map it by file id we might get in trouble in some situations...

FK time ...

**Comment by DeepDiver1975** [comment]
let's close this on and continue in #11804

**Comment by PVince81** [comment]
With trouble I was mostly thinking of unstable file ids: #13310
