### ISSUE TITLE
Google drive error: The OAuth 2.0 access token has expired, and a refresh token is not available

### ISSUE THREAD

**Issue by zubanst** [owncloud/core#15128]
Owncloud 8.0.2 fresh install on https. File locking enabled, server side encryption enabled, external drive support enabled. After adding Google drive external storage, in a first time, everything is fine, then after the token expiry, drive becomes unaccessible with the following error:

Fatal files_external Exception: {"Message":"The OAuth 2.0 access token has expired, and a refresh token is not available. Refresh tokens are not returned for responses that were auto-approved.","Code":0,"Trace":"#0 \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/google-api-php-client\/src\/Google\/Service\/Resource.php(176): Google_Auth_OAuth2->sign(Object(Google_Http_Request))\n#1 \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/google-api-php-client\/src\/Google\/Service\/Drive.php(1283): Google_Service_Resource->call('get', Array, 'Google_Service_...')\n#2 \/var\/www\/owncloud\/apps\/files_external\/lib\/google.php(510): Google_Service_Drive_About_Resource->get()\n#3 \/var\/www\/owncloud\/apps\/files_external\/lib\/google.php(547): OC\Files\Storage\Google->free_space('')\n#4 \/var\/www\/owncloud\/apps\/files_external\/lib\/config.php(457): OC\Files\Storage\Google->test(false)\n#5 \/var\/www\/owncloud\/apps\/files_external\/lib\/config.php(539): OC_Mount_Config::getBackendStatus('\\OC\\Files\\Stora...', Array, false)\n#6 \/var\/www\/owncloud\/apps\/files_external\/ajax\/addMountPoint.php(25): OC_Mount_Config::addMountPoint('GoogleDrive', '\\OC\\Files\\Stora...', Array, 'user', 'all', false)\n#7 \/var\/www\/owncloud\/lib\/private\/route\/route.php(135) : runtime-created function(1): require_once('\/var\/www\/ownclo...')\n#8 [internal function]: __lambda_func(Array)\n#9 \/var\/www\/owncloud\/lib\/private\/route\/router.php(250): call_user_func('\x00lambda_9649', Array)\n#10 \/var\/www\/owncloud\/lib\/base.php(767): OC\Route\Router->match('\/apps\/files_ext...')\n#11 \/var\/www\/owncloud\/index.php(36): OC::handleRequest()\n#12 {main}","File":"\/var\/www\/owncloud\/apps\/files_external\/3rdparty\/google-api-php-client\/src\/Google\/Auth\/OAuth2.php","Line":240}

Removing external storage and then re-adding it will provide again acces to the external drive, until the next token expiry. This is a regression compared to OC 7.0.4 where there is no such issue.
Additional information:
web server apache, config file
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'trusted_domains' => 
  array (
    0 => 'www.pennyitsupport.eu',
  ),
  'datadirectory' => '/var/data',
  'dbtype' => 'mysql',
  'version' => '8.0.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'root',
  'dbpassword' => '',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_from_address' => '',
  'mail_domain' => 'pennyitsupport.eu',
  'mail_smtpauth' => 1,
  'mail_smtpname' => '',
  'mail_smtppassword' => '',
  'mail_smtpport' => '587',
  'mail_smtphost' => 'mail.pennyitsupport.eu',
  'loglevel' => '3',
  'mail_smtpauthtype' => 'LOGIN',
  'forcessl' => false,
  'theme' => '',
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'maintenance' => true,
  'secret' =>',
);

**Comment by Undeadhunter** [comment]
I have the same issue, is there anything that I can provide to give a better view into the issue?

**Comment by DeepDiver1975** [comment]
duplicate #15768
