### ISSUE TITLE
File in trash still appears as shared for recipient

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15139]
### Steps to reproduce
1. Create two users "user1" and "user2"
2. Login as "user1"
3. Create a folder "folder" and subfolder "folder/test"
4. Share "folder/test" with "user2"
5. Delete "folder"
6. Check trashbin: folder is present
7. Check "Shared with others" in the files app
8. Login as "user2"
9. Check if "test" is present

### Expected result
Folder "test" not visible for "user2" any more.
Folder "test" not visible in "Shared with others" section.

### Actual result
Folder "test" is still visible for "user2" until "user1" deletes it from trash.
Folder "test" still visible in "Shared with others" section.

Since the introduction of "moving files to trash" and the trashbin storage wrapper, they now keep their file ids. This is nice because it would make it possible to keep shares associated to trashed files, but the share API must be adapted to not return such entries.

Note that if "folder" was shared directly, the share would be cleant up properly. The reason why it doesn't in this specific case is because of https://github.com/owncloud/core/issues/14664

Discussed with @schiesbn and he said we could do the following:
- [ ] prevent the share API from touching shares linked with trash files
- [ ] remove the clearing of shares on direct delete to make it possible to keep shares associated with trash files

### Versions
The bug happens in 8.0.2 (since the introduction of the trashbin storage wrapper)

**Comment by PVince81** [comment]
We'll probably want a backportable solution for 8.0.3

**Comment by karlitschek** [comment]
yes. please backport

**Comment by PVince81** [comment]
Note: this bug existed on master and stable8.

@cdamken I tried OC 7 and I can confirm that this specific bug does **not** exist on stable7 because the fileid wasn't preserved at deletion time in that version.

**Comment by cdamken** [comment]
@PVince81 Thanks
