### ISSUE TITLE
Use 24h format instead of 12h format in WebUI

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#15132]
### Expected behavior

That time shows in 24h format

### Actual behavior

Time shows in 12 format

![owncloud time](https://cloud.githubusercontent.com/assets/4511254/6789694/85d746fc-d1a2-11e4-949f-2d298e763d29.png)

Ubuntu Server 14.04

**Database:**
Server version: 5.5.41-0ubuntu0.14.04.1 - (Ubuntu)
PHP version:
PHP 5.5.9-1ubuntu4.5 (cli) (built: Oct 29 2014 11:59:10)

**ownCloud version: (see ownCloud admin page)**
8.0.2

**List of activated apps:**
Activity
Calender 
Contacts
Deleted files
Documents
First Run Wizard
Full Text Search
PDF Viewer
Pictures
Share Files
Text Editor
Updater
Versions
Video Viewer

**Are you using external storage, if yes which one: local/smb/sftp/...**
No
**Are you using encryption: yes/no**
No

### Client configuration

**Browser:**
Version 39.0.2171.71 m
**Operating system:**
Windows 8.1 and XP and Vista
**Sync Client**
1.8 stable

**Comment by PVince81** [comment]
Right, I don't like it either.

You can try playing with the format here: https://github.com/owncloud/core/blob/master/core/js/js.js#L1341 and submit a PR if you like

**Comment by enoch85** [comment]
@PVince81 Isn't it just to change `"MMMM D, YYYY h:mm"` to `"MMMM D, YYYY hh:mm"`

**Comment by enoch85** [comment]
No, it wasn't that easy...

**Comment by PVince81** [comment]
Maybe check the documentation of the momentJS library

**Comment by rullzer** [comment]
http://momentjs.com/docs/#/parsing/string-format/ <-- should be `"MMMM D, YYYY H:mm"` (capital H) according to the docs.

**Comment by enoch85** [comment]
https://github.com/owncloud/core/commit/8279dde97a8f93b74eb733d243d6a5bb41aa15e3

Sorry, made the change directly in master. Should I revert it and make a PR instead?

**Comment by enoch85** [comment]
I tested and it works as expected.

**Comment by enoch85** [comment]
@PVince81

**Comment by enoch85** [comment]
Closing as the bug is fixed anyway.

**Comment by PVince81** [comment]
I have reverted the change, sorry.
Please resend as a PR so we can discuss and test it, according to the process :smile:

**Comment by PVince81** [comment]
revert commit is ce5d2ab7dbe9e4ca67c12ba1f5506619b639ddb7

**Comment by enoch85** [comment]
Fix is here: https://github.com/owncloud/core/pull/15143
