### ISSUE TITLE
App does not provide an info.xml file error after upgrade from owncloud 7.0.4 to 8.0.2

### ISSUE THREAD

**Issue by ruxandy** [owncloud/core#15130]
I've updated owncloud 7.0.4 to 8.0.2 (renamed existing folder, extracted 8.0.2 archive, copied config.php from old instance).
After upgrading, everything seems to work fine, except the fact that I can't enable the Contacts/Calendar apps. I receive the infamous "App does not provide an info.xml file" error.

This is the logged error in the owncloud.log file:
 ```{"reqId":"2ca9c25e758a0842f4f1a344a6312750","remoteAddr":"xx.xx.xx.xx","app":"PHP","message":"ZipArchive::extractTo(): Invalid or uninitialized Zip object at \/var\/www\/html\/owncloud\/lib\/private\/archive\/zip.php#135","level":3,"time":"2015-03-23T17:25:07+00:00"}```
```{"reqId":"2ca9c25e758a0842f4f1a344a6312750","remoteAddr":"xx.xx.xx.xx","app":"core","message":"App does not provide an info.xml file","level":3,"time":"2015-03-23T17:25:07+00:00"}```

I've seen that a lot of people encountered this problem, I tried everything that was recommended, but nothing seems to work.

**SERVER SPECS:**

OS: Fedora 20

SQL version: MariaDB 5.5.41

Installed PHP version/extensions:
php-cli-5.5.22-1.fc20.x86_64
php-imap-5.5.22-1.fc20.x86_64
php-pecl-zip-1.12.4-1.fc20.x86_64
php-pecl-jsonc-1.3.6-1.fc20.x86_64
php-xml-5.5.22-1.fc20.x86_64
php-common-5.5.22-1.fc20.x86_64
php-mysqlnd-5.5.22-1.fc20.x86_64
php-intl-5.5.22-1.fc20.x86_64
php-pear-MDB2-2.5.0-0.10.b5.fc20.noarch
php-pear-1.9.5-6.fc20.noarch
php-5.5.22-1.fc20.x86_64
php-mbstring-5.5.22-1.fc20.x86_64
php-process-5.5.22-1.fc20.x86_64
php-pear-MDB2-Driver-mysqli-1.5.0-0.9.b4.fc20.noarch
php-pear-Net-Curl-1.2.5-11.fc20.noarch
php-gd-5.5.22-1.fc20.x86_64
php-pclzip-2.8.2-1.fc20.noarch
php-pdo-5.5.22-1.fc20.x86_64
php-mcrypt-5.5.22-1.fc20.x86_64

**Comment by RealRancor** [comment]
Hi,

there should be at least one or two still opened issues for this problem available here.

Have you checked if they are matching your problem before creating a new issue?

**Comment by ruxandy** [comment]
It's the same apparent error, but I'm afraid that this problem is caused by different, unrelated issues.
None of the solutions provided in the other threads work in my case.
As far as I can tell, I have all the required php extensions and the upgrade process went smoothly with no errors
It's the same apparent error, but I'm afraid that this problem is caused by different, unrelated issues.
None of the solutions provided in the other threads work in my case.
As far as I can tell, I have all the required php extensions and the upgrade process went smoothly with no errors

**Comment by RealRancor** [comment]
@ruxandy 
Its not only the required php extensions. Have you had a look at https://github.com/owncloud/core/issues/14840, especially at https://github.com/owncloud/core/issues/14840#issuecomment-85247056 ?

**Comment by ruxandy** [comment]
Ah damn, I must have missed that.  Thanks for the heads up.
Unfortunatelly I already reverted back to 7.0.4 :(

**Comment by i42n** [comment]
+1
back to 7 for now.

**Comment by ruxandy** [comment]
I had another go with the upgrade, this time from 7.0.5 to 8.0.3
And, again, I encountered the same error: "App does not provide an info.xml file"
Adding the following line in lib/private/httphelper.php solved the issue and I was able to install both Contacts and Calendar:
>    curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
