### ISSUE TITLE
Session has been closed - Sabre\Dav\Exception\ReportNotSupported

### ISSUE THREAD

**Issue by t3chguy** [owncloud/core#15135]
I am trying to add EAS Support to my OwnCloud instance, through z-push-contrib. Every now and then the z-push-contrib log shows a 403 error on CardDAV/CalDAV to the OwnCloud server. The corresponding error in the owncloud log is shown below. Any ideas? Thanks in advance. 

```
{"app":"carddav","message":"Sabre\\DAV\\Exception\\ReportNotSupported: ","level":4,"time":"2015-03-24T06:03:15+00:00"}
```
and just before a mass of those messages is a:
```
{"app":"PHP","message":"Session has been closed - no further changes to the session as allowed at \/var\/www\/owncloud\/lib\/private\/session\/memory.php#80","level":3,"time":"2015-03-24T05:59:38+00:00"}
```

**Comment by DeepDiver1975** [comment]
Please get in touch with the z-push developer. Thx
