### ISSUE TITLE
Error during uodate the owncloud from 7 to 8 version

### ISSUE THREAD

**Issue by viper1vip** [owncloud/core#15131]
I have big problem. I started updata the owncloud using autoapdata in the program menu. After the backup has done I saw the communication:
SQLSTATE[HY000]: General error: 5 cannot rollback transaction - SQL statements in progress

What is wrong? How can I fix it now?

**Comment by enoch85** [comment]
@viper1vip Please use the issue template. https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by RealRancor** [comment]
@enoch85 
Could be also a duplicate of https://github.com/owncloud/core/issues/14911 and/or https://github.com/owncloud/core/issues/14398

**Comment by VicDeo** [comment]
Closing as duplicate of https://github.com/owncloud/core/issues/14911
Please post details according to https://raw.githubusercontent.com/owncloud/core/master/issue_template.md there. 
Thanks
