### ISSUE TITLE
Activate / deactivate apps => Error: Class 'APCIterator' not found

### ISSUE THREAD

**Issue by Waterkant** [owncloud/core#15146]
I've never had problems with APC running Owncloud < 8.0.2. I'm using a shared web host, which seems to have APC and opcache disabled by default. OC documentation says it's optional.

 Now I cannot activate / deactivate apps without errors.

Do I have to enable APC due to new requirements or is this a bug?

### Steps to reproduce
1. Install Owncloud 8.0.2
2. Try to enable apps like "Calendar 8.0" or try to deactive an app

### Expected behaviour
App should be activated / deactivated without errors

### Actual behaviour
Red message about errors during activation

### Server configuration

**Shared web host**

**Operating system**: Debian
**Web server:** Apache
**Database:** sqlite3
**PHP version:**  5.5.20
    
**APC Settings - phpinfo()**

    Configuration
    apc
    APC support 	Emulated

    apcu
    APCu Support	Disabled
    Version 	4.0.7
    APCu Debugging 	Disabled
    MMAP Support 	Enabled
    MMAP File Mask 	no value
    Serialization Support 	Disabled
    Revision 	$Revision: 328290 $
    Build Date 	Jan 7 2015 14:37:44

    Directive	Local Value	Master Value
    apc.coredump_unmap	Off	Off
    apc.enable_cli	Off	Off
    apc.enabled	Off	Off
    apc.entries_hint	4096	4096
    apc.gc_ttl	3600	3600
    apc.mmap_file_mask	no value	no value
    apc.preload_path	no value	no value
    apc.rfc1867	Off	Off
    apc.rfc1867_freq	0	0
    apc.rfc1867_name	APC_UPLOAD_PROGRESS	APC_UPLOAD_PROGRESS
    apc.rfc1867_prefix	upload_	upload_
    apc.rfc1867_ttl	3600	3600
    apc.serializer	php	php
    apc.shm_segments	1	1
    apc.shm_size	32M	32M
    apc.slam_defense	On	On
    apc.smart	0	0
    apc.ttl	7200	7200
    apc.use_request_time	On	On
    apc.writable	/tmp	/tmp

**ownCloud version:** 8.0.2 (fresh installation)
**List of activated apps:** default
**The content of config/config.php:** default

#### ownCloud log (data/owncloud.log)

Error Message:
{"reqId":"b53944f704de54aa47175d58db149a69","remoteAddr":"XX.XX.XXX.XXX","app":"PHP","message":"Class 'APCIterator' not found at \/var\/www\/webXXX\/html\/owncloud\/lib\/private\/memcache\/apc.php#35","level":3,"time":"2015-03-24T09:47:35+00:00","method":"POST","url":"\/index.php\/settings\/ajax\/enableapp.php"}

**Comment by DeepDiver1975** [comment]
> apc.enabled Off Off

sine apc is not enabled - this should really not happen ...

**Comment by DeepDiver1975** [comment]
@bantu some get_ini kung-fu? Maybe you find the time to take a look - THX

**Comment by bantu** [comment]
@Waterkant Please try whether #15194 fixes this issue for you.

**Comment by DeepDiver1975** [comment]
THX @bantu

**Comment by Waterkant** [comment]
@bantu Great, now it's working without errors. Thanks!
