### ISSUE TITLE
New file/folder: Modal and technical error message when file already exists

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#15147]
1. Create a new text file
2. Try to create a new text file with the same name
3. EXPECTED: Get an inline notification that this file already exists

Instead, two different scenarios:
* If you reloaded the page before step 2, you get a modal saying `The name New text file.txt is already used in the folder /. Please choose a different name.` This is annoying and rips you out of the flow. Worst of all, these modals stack up!
* If you do it directly after you added the new text file, you get an inline notification (tooltip) and red border around the input field _for as long as you hold enter_ saying: `TypeError: FileList.checkName is not a function` this is too technical, and visible for too short.

**What should happen instead:**
On pressing enter, show the inline notification (tooltip) and the red border (similar to the second scenario above) but saying »A file with that name already exists« and it should stay until the name in the box is changed.
(Same for folders btw.)

@icewind1991 maybe?

**Comment by PVince81** [comment]
There seem to be two different issues.
The first one involve some kind of race condition with refreshing: this is probably an existing/old issue.

The other one, which I observe on master, is that the tooltip doesn't stay after entering the name of an existing file, and the message inside looks like a JS error. This is a regression.

I'll have a look at fixing the latter.

**Comment by PVince81** [comment]
Regression introduced by @LukasReschke through https://github.com/owncloud/core/pull/14652

I'll take care of it.

**Comment by PVince81** [comment]
Funny thing, it looks like the method `FileList.checkName()` hasn't existed for a long time. So the error was hidden in the shadows and woke up after that PR.

**Comment by PVince81** [comment]
It looks like the validation happened earlier, and prevented the user to hit enter in case of error, so "FileList.checkName()" was never called. Now that the early validation is gone for some reason, that happens.

I'll do the following:
1) Bring back the early validation
2) Code archeology to find out what checkName() was supposed to do and remove accordingly

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/core/pull/15893
