### ISSUE TITLE
Apple Browser Safari - Problems

### ISSUE THREAD

**Issue by aqxavier** [owncloud/core#15148]
I have some customers using Mac OS 10.9.5 and 10.10.2 and they are experiencing problems in accessing the owncloud the Web interface.
One of these problems is the delay higher than in other web browsers to open and access the pages. Not so with Chrome and Firefox.
Another problem identified is that any video (.mp4, .mov, .m4v) using the native video player of owncloud, the video is not played.
It caught the screen as if waiting for the download or stream video to the player but not nothing happens.

All this only occurs with OS X and Apple Safari systems. The problem in my case it is that most of my clients use this platform.

I am running 8.0.2 with Ownlcloud Nginx 1.6.2 Server and MySql as database on a Linux Server Debian 7.7

**Comment by karlitschek** [comment]
we need more detailed information. inpersonally use safari on os x just fine. so thisnus maybe a configuration or setup problem. the supported video types of owncloud depend on the supported codecs of the browser. i suggest to discuss this in the forum.
