### ISSUE TITLE
Sync client gives too many "unknown errors" with upload bandwith "limit automatically"

### ISSUE THREAD

**Issue by cortopy** [owncloud/core#15159]
I've spent a good couple of hours exploring why my sync client just decided to not sync files this morning. I'm uploading a large number of files at the moment and the sync was just giving me "unknown error" for about 99% per cent of files so the sync would largely fail.

Then, I realised I changed the settings to limit upload bandwidth to "automatic". I changed it back to "no limit" and sync was working fine again.

**Comment by RealRancor** [comment]
Hi,

@cortopy 
The issue tracker of the sync client is located here:

https://github.com/owncloud/client/issues

Please re-open there using the issue template provided here:

https://raw.github.com/owncloud/client/master/issue_template.md

**Comment by cortopy** [comment]
Thanks! I wasn't aware there was different trackers
