### ISSUE TITLE
Multiselect with shift does not work when the second click is on the checkbox again

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#15157]
1. Select a file (click the checkbox)
2. hold shift to perform a multiselect
3. while holding shift, click the checkbox of another file lower down or further up

Expected: Both files and all files inbetween are selected.

What actually happens: Only the two files where you clicked the checkbox are selected.
If the click on the second file is _anywhere else_ but the checkbox, it actually works. Should work when clicking on the checkbox as well though.

@icewind1991 @schiesbn cc @hodyroff

**Comment by PVince81** [comment]
Looks like the checkbox event handler is missing shift/ctrl key handling: https://github.com/owncloud/core/blob/master/apps/files/js/filelist.js#L383

This is the code that does it properly for a click outside the checkbox: https://github.com/owncloud/core/blob/master/apps/files/js/filelist.js#L326

Maybe both needs to be consolidated in some way.

One idea would be to detect shift or control for the checkbox. If they are pressed, then simply call the other event handler instead. Else fallback to the current code.

**Comment by oparoz** [comment]
1. Click on a file at the bottom
2. selec-all+deselect-all 
3. Tap on the row of a file at the top to bring out the details 
4. Press shift
5. Tap on the row of a file in between the files selected in 1 and 3

**Comment by simonschaufi** [comment]
I would love to see this feature in the next release!

**Comment by PVince81** [comment]
Closing in favor of general files app keyboard issue ticket: https://github.com/owncloud/core/issues/27580
