### ISSUE TITLE
sharing does not find ldap username but finds full name

### ISSUE THREAD

**Issue by groniu** [owncloud/core#15154]
Steps to reproduce

go to  folder or file  via browser in "File" menu
click on "share" 
type the username of the ldap owncloud user  in the field
no suggestion
try full name  of the same ldap owncloud user -> success

sugestion for local user works with username

Server configuration

Operating system: ubuntu 14.10 64bit

**Web server:  nginx/1.6.2 (Ubuntu)

**Database: postgresql 9.4

**PHP version: 5.5.12-2ubuntu4.3

**ownCloud version:8.0.2

**Updated from an older ownCloud or fresh install: fresh install

**Are you using external storage, if yes which one: no

**Are you using encryption: yes

**Are you using an external user-backend, if yes which one:** LDAP/AD samba4

**Client configuration: chrome/firefox/safari 

**Operating system: windows/mac os x/linux

**Comment by blizzz** [comment]
See User Search Attributes https://doc.owncloud.org/server/8.0/admin_manual/configuration_user/user_auth_ldap.html#directory-settings
