### ISSUE TITLE
Delete file as recipient to trash, restore it, versions lost

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15152]
### Steps
1. Create two users "user1" and "user2"
2. As "user1", share a folder "sub" with "user2"
3. Login as "user2"
4. Create a text file "sub/test.txt"
5. Edit "sub/test.txt" several times to generate versions
6. Delete "sub/test.txt"
7. Restore "test.txt" from trash
8. Open the versions dropdown

### Expected result
Versions kept upon restore

### Actual result
Versions lost after restore.
Note that if the file was deleted by the owner (user1) instead, versions will be kept.

### Versions
Observed in OC 7.0.5, OC 8.0.2 and master

@schiesbn

**Comment by DeepDiver1975** [comment]
@PVince81 @schiesbn what's the call on this one? I fear fixing this will result in bigger changes.

8.2 ????

**Comment by PVince81** [comment]
I guess it depends whether the logic is already there (but inactive/buggy)  or needs to be implemented because it's missing. Any idea @schiesbn ?

**Comment by PVince81** [comment]
I'll have a look to find out.

**Comment by PVince81** [comment]
Tested on master.

Before deletion:
```
  % find . -iname \*test\*
./user1/files_versions/sub/test.txt.v1433254934
./user1/files_versions/sub/test.txt.v1433254933
./user1/files/sub/test.txt
```

After deletion:
```
% find . -iname \*test\*
./user1/files_trashbin/files/test.txt.d1433254969
./user2/files_trashbin/files/test.txt.d1433254969
```

It looks like the versions are completely deleted, even for user1.

The correct behavior I think would be to have both users have a copy not only of the file but also of all versions.

**Comment by PVince81** [comment]
A quick debug session shows that it is a bug.

In the code that retains versions we try and get the owner with getOwner.

When deleting as owner, getOwner() will be called on the home storage, so always returns the current user.
For a shared file, getOwner() will try and resolve the original file. However, at this point the file has already been moved to trash so it doesn't exist any more, so nothing is found: versions are skipped.

We might need to reverse the order: first resolve the owner+path before the actual deletion, then pass them to `retainVersions()`.

**Comment by PVince81** [comment]
Okay, seems to work. Will submit a PR later.

**Comment by PVince81** [comment]
PR here: https://github.com/owncloud/core/pull/16691
