### ISSUE TITLE
File disappears from search results after having been edited

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#15167]
ownCloud 8.0.2
Firefox 36

### Steps to reproduce
* Place several text files named ztest.txt in different folders, so that you have more than one search result
* Go to a folder which contains one of the files fill the folder with lots of dummy files with names starting any letter but z. I think 30 should be enough, but it might depend on your window's height.
* Type the first 3 letters of the filename in the search field
* Click on the file to edit it
* Save the file
* Close the file

### Expected results
I'm back to the search results, seeing my file as the top result

### Actual results
The row containing my file is nowhere to be seen. Below it, the summary says there is one file matching the query and below that there is the list of files belonging to other folders.

Looking at the html, I think the hidden list view might only contain the 30 or so first files and my search results are not part of that list

**Comment by karlitschek** [comment]
@butonic any idea?

**Comment by oparoz** [comment]
Maybe @icewind1991 knows how to fix this?

**Comment by PVince81** [comment]
@oparoz still seeing this in 8.1.3 or 8.2rc1 ?

**Comment by oparoz** [comment]
All good on 8.2. Probably fixed by your navigation fix.

**Comment by oparoz** [comment]
Yep, still there on 8.1.3 as the fix probably wasn't backported.

**Comment by PVince81** [comment]
Probably not critical enough to justify a backport ?
First would be to try and identify what piece of code actually fixed it (inverted bisect)

**Comment by enoch85** [comment]
Any news here?

**Comment by PVince81** [comment]
Since it's fixed in 8.2, closing.
Not critical enough for a 8.1 backport.
