### ISSUE TITLE
Resizing the window makes search results vanish

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#15163]
ownCloud 8.0.2 and master
Firefox 36

### Steps to reproduce
* Type a few letters in the search field
* Watch the main area get filled with search results
* Resize window

### Expected results
The search results should be re-arranged to take the new size of the window into consideration

### Actual results
The search results disappear

**Comment by jancborchardt** [comment]
Ohlala @nickvergessen @butonic

**Comment by nickvergessen** [comment]
8.0.2 means its not from our current master fixes :)

**Comment by oparoz** [comment]
Just tested on master, same problem ;)

**Comment by PVince81** [comment]
@oparoz is this still happening in 9.0beta ?

**Comment by PVince81** [comment]
Should be fixed through https://github.com/owncloud/core/pull/24682
