### ISSUE TITLE
Moving files: missing feedback

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#15173]
When moving files, you don’t get any feedback where the files are moved. It would be good to show a notification up top like:
`Filename moved to foldername`

cc @PVince81 @schiesbn

**Comment by jancborchardt** [comment]
cc @msrex since we talked about this.

**Comment by enoch85** [comment]
@ezula Something to start with? :)

**Comment by jancborchardt** [comment]
@ezula would be cool – any junior job really, preferably design ones. ;)
