### ISSUE TITLE
Show disabled icon for delete action if there is no permission

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#15172]
* have a file where you don't have a permission for delete

## expected behaviour

show that the delete action isn't available because of the missing permission

## actual behaviour

delete action is simply not there

cc @jancborchardt 

as discussed with @msrex

**Comment by jancborchardt** [comment]
The delete icon should show, but on hover it should not get more opaque, and the tooltip should say »You don’t have delete permissions«

@schiesbn can you make the delete icon show up? Then I’ll handle the styling.

**Comment by jancborchardt** [comment]
@schiesbn @MorrisJobke can one of you make the delete icon show up, and give it a class like »no-permission«?

**Comment by MorrisJobke** [comment]
@jancborchardt I fixed it while I was at it - #15835
