### ISSUE TITLE
owncloud dosnt sync git repository

### ISSUE THREAD

**Issue by treaki** [owncloud/core#15175]
hi, to backup some git repositorys i did a clone --bare into the ownCloud folder. But it isnt syncing and there is no message about the status where it should be...

![screenshot from 2015-03-24 22 21 00](https://cloud.githubusercontent.com/assets/1477872/6813372/1feec094-d275-11e4-9942-1d5353796df5.png)

please help me out on this.

thanks

**Comment by karlitschek** [comment]
can you open this in the client repository please? thanks a lot
