### ISSUE TITLE
Unable to share files with another LDAP user

### ISSUE THREAD

**Issue by plastilincheg** [owncloud/core#15178]
### Steps to reproduce
1. Fresh install OC 8.0.2 on Ubuntu 14.04
2. Set up LDAP to AD on Windows Server 2008 R2
3. Try to share file from one LDAP user to another LDAP user

### Expected behaviour
The system should provide standard file access some other users

### Actual behaviour
Sharing already working only for user admin. System not see LDAP users for sharing files

### Server configuration
**Operating system**:

Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty

**Web server:**

Server version: Apache/2.4.7 (Ubuntu)
Server built:   Mar 10 2015 13:05:59

**Database:**

mysql  Ver 14.14 Distrib 5.5.41, for debian-linux-gnu (x86_64) using readline 6.3

**PHP version:**

PHP 5.5.9-1ubuntu4.7 (cli) (built: Mar 16 2015 20:47:39)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

**ownCloud version:** (see ownCloud admin page)

ownCloud 8.0.2 (stable)

**Updated from an older ownCloud or fresh install:**

Fresh install

**List of activated apps:**

Activity 1.2.0
Deleted files 0.6.2
Documents 0.9.0
File Locking
First Run Wizard 1.1
Full Text Search 0.6.0
LDAP user and group backend 0.5.0
Mail Template Editor 0.1
PDF Viewer 0.7
Pictures 0.6.0
Provisioning API 0.2
Share Files 0.6.1
Text Editor 0.4
Versions 1.0.5
Video Viewer 0.1.3

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => 'ocbjvo06qxyl',
  'passwordsalt' => '************************************************',
  'secret' => '**********************************************************',
  'trusted_domains' =>
  array (
    0 => '***.***.*.*',
    1 => '***.***.*.***',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://***.***.*.*/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.2.0',
  'installed' => true,
  'mail_from_address' => '******',
  'mail_smtpmode' => 'php',
  'mail_domain' => *************',
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'ldapIgnoreNamingRules' => false,
  'maintenance' => false,
  'dbname' => 'owncloud',
  'dbuser' => 'owncloud',
  'dbpassword' => '********',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'loglevel' => 4,
  'default_language' => 'ru',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...

local

**Are you using encryption:** yes/no

no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

ActiveDirectory

#### LDAP configuration (delete this part if not used)

| user_ldap | cleanUpJobOffset                  | 0                                                                                                                        |
| user_ldap | enabled                           | yes                                                                                                                      |
| user_ldap | has_memberof_filter_support       | 1                                                                                                                        |
| user_ldap | home_folder_naming_rule           | attr:sAMAccountName                                                                                                      |
| user_ldap | installed_version                 | 0.5.0                                                                                                                    |
| user_ldap | last_jpegPhoto_lookup             | 0                                                                                                                        |
| user_ldap | ldap_agent_password               | ***********                                                                                                             |
| user_ldap | ldap_attributes_for_group_search  |                                                                                                                          |
| user_ldap | ldap_attributes_for_user_search   |                                                                                                                          |
| user_ldap | ldap_backup_host                  |                                                                                                                          |
| user_ldap | ldap_backup_port                  |                                                                                                                          |
| user_ldap | ldap_base                         | DC=***********,DC=lan                                                                                                        |
| user_ldap | ldap_base_groups                  | DC=***********,DC=lan                                                                                                        |
| user_ldap | ldap_base_users                   | DC=***********,DC=lan                                                                                                        |
| user_ldap | ldap_cache_ttl                    | 600                                                                                                                      |
| user_ldap | ldap_configuration_active         | 1                                                                                                                        |
| user_ldap | ldap_display_name                 | displayname                                                                                                              |
| user_ldap | ldap_dn                           | CN=Администратор,CN=Users,DC=***********,DC=lan                                                                              |
| user_ldap | ldap_email_attr                   | mail                                                                                                                     |
| user_ldap | ldap_experienced_admin            | 0                                                                                                                        |
| user_ldap | ldap_expert_username_attr         | sAMAccountName                                                                                                           |
| user_ldap | ldap_expert_uuid_group_attr       |                                                                                                                          |
| user_ldap | ldap_expert_uuid_user_attr        |                                                                                                                          |
| user_ldap | ldap_group_display_name           | cn                                                                                                                       |
| user_ldap | ldap_group_filter                 |                                                                                                                          |
| user_ldap | ldap_group_filter_mode            | 1                                                                                                                        |
| user_ldap | ldap_group_member_assoc_attribute | member                                                                                                                   |
| user_ldap | ldap_groupfilter_groups           |                                                                                                                          |
| user_ldap | ldap_groupfilter_objectclass      |                                                                                                                          |
| user_ldap | ldap_host                         | ***.***.*.*                                                                                                              |
| user_ldap | ldap_login_filter                 | (&(&(&(objectclass=user)(objectcategory=person))(!(userAccountControl:1.2.840.113556.1.4.803:=2)))(samaccountname=%uid)) |
| user_ldap | ldap_login_filter_mode            | 0                                                                                                                        |
| user_ldap | ldap_loginfilter_attributes       |                                                                                                                          |
| user_ldap | ldap_loginfilter_email            | 0                                                                                                                        |
| user_ldap | ldap_loginfilter_username         | 1                                                                                                                        |
| user_ldap | ldap_nested_groups                | 0                                                                                                                        |
| user_ldap | ldap_nocase                       | 1                                                                                                                        |
| user_ldap | ldap_override_main_server         | 0                                                                                                                        |
| user_ldap | ldap_paging_size                  | 500                                                                                                                      |
| user_ldap | ldap_port                         | 389                                                                                                                      |
| user_ldap | ldap_quota_attr                   |                                                                                                                          |
| user_ldap | ldap_quota_def                    |                                                                                                                          |
| user_ldap | ldap_tls                          | 0                                                                                                                        |
| user_ldap | ldap_turn_off_cert_check          | 0                                                                                                                        |
| user_ldap | ldap_user_filter_mode             | 1                                                                                                                        |
| user_ldap | ldap_userfilter_groups            |                                                                                                                          |
| user_ldap | ldap_userfilter_objectclass       |                                                                                                                          |
| user_ldap | ldap_userlist_filter              | (&(&(objectclass=user)(objectcategory=person))(!(userAccountControl:1.2.840.113556.1.4.803:=2)))                         |
| user_ldap | types                             | authentication                                                                                                           |

### Client configuration

Mozilla Firefox 36.0.4

**Operating system:**

Windows Server 2008 R2

***.***.*.* - - [24/Mar/2015:23:49:30 +0200] "GET /owncloud/index.php/apps/files/ajax/list.php?dir=%2F&sort=name&sortdirection=asc HTTP/1.1" 200 1950 "http://***.***.*.* /owncloud/index.php/apps/files?dir=%2F" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0"

#### ownCloud log (data/owncloud.log)

/var\/www\/owncloud\/lib\/private\/cache\/fileglobalgc.php#50","level":3,"time":"2015-03-24T21:28:00+00:00"}
{"reqId":"36c60de6fdb8cbd0f744468a35c7b2e8","remoteAddr":"***.***.*.*","app":"PHP","message":"unlink() expects parameter 2 to be resource, integer given at \/var\/www\/owncloud\/lib\/private\/cache\/fileglobalgc.php#50","level":3,"time":"2015-03-24T21:28:00+00:00"}
{"reqId":"36c60de6fdb8cbd0f744468a35c7b2e8","remoteAddr":"***.***.*.*","app":"PHP","message":"unlink() expects parameter 2 to be resource, integer given at \/var\/www\/owncloud\/lib\/private\/cache\/fileglobalgc.php#50","level":3,"time":"2015-03-24T21:28:00+00:00"}

#### Browser log

Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery-migrate.min.js:3:0
window.controllers является устаревшим. Не используйте его для определения UA. ace.js:1716:0
Метод getPreventDefault() является устаревшим. Для его замены используйте метод defaultPrevented. jquery.min.js:5:0
Синхронный XMLHttpRequest в основной нити является устаревшим из-за его пагубного влияния на работу конечного пользователя. Для получения дополнительной помощи обратитесь к http://xhr.spec.whatwg.org/

**Comment by blizzz** [comment]
привет! Most likely a configuration issue. As admin, do you see LDAP users on the Users page?

**Comment by blizzz** [comment]
… if not, you want to change the user display name attribute to samaccountname or cn.

**Comment by plastilincheg** [comment]
@blizzz I See users normally. See screenshot. Users imported from Active Directory
![owncloud](https://cloud.githubusercontent.com/assets/9542165/6815428/4b3b39ea-d292-11e4-8b92-afb1a71c72a3.PNG)

**Comment by blizzz** [comment]
That's fine then. Just to get sure, in the search dialogue you typed in couple letters, correct? And actually those that would match with the start of a displayname?

**Comment by plastilincheg** [comment]
@blizzz Yes. I try type first letters of username, but names not vieweing

**Comment by blizzz** [comment]
displayname not username/samaccountname. To search in both fields, add displayname and samaccountname into the User Search Attributes text area in the Advanced Tab in the LDAP settings.

**Comment by plastilincheg** [comment]
@blizzz Thank you. After i added attribute samaccountname in User Search Attributes text area in the Advanced Tab in the LDAP settings searching and sharing working.

**Comment by blizzz** [comment]
Yes, if you want to search in there as well. Often admins like to add sn and givenname, too, to search in first and family names.
