### ISSUE TITLE
Display of web interface on large screens

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#15177]
We need to think about what to do with the web interface on very large screens, like 4k ones.

This is an example for how the log in view looks like on large screens: https://github.com/owncloud/core/issues/12494

Another issue is the display of the file list on wide displays, as the date/size info as well as the actions for deletion/sharing etc are very far off to the right, far from the filename.

We could think about limiting the width at some point there. Or do we scale the whole interface up?

@owncloud/designers what do you think?

**Comment by oparoz** [comment]
Regarding the width of the Files app, I've been using large screens for a long time and I think it's a non issue as you will almost never let the browser fill the entire screen. Most sites will have lots of dead space or be unusable at full width. It's much more comfortable to have one window in portrait mode filling half the screen.
