### ISSUE TITLE
Moving files: ability to undo

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#15174]
Next to the notification of where the files were moved (see https://github.com/owncloud/core/issues/15173), it should be possible to undo the move if it was made accidentally.

cc @DeepDiver1975 @PVince81 @schiesbn

**Comment by jancborchardt** [comment]
This relates to undo for deletion: https://github.com/owncloud/core/pull/15002

**Comment by PVince81** [comment]
Duplicate of https://github.com/owncloud/core/issues/7058
