### ISSUE TITLE
Confirm function for text fields

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#15176]
Lots of text fields in ownCloud don’t have any immediately obvious way of what needs to be done next.

Some examples are:
- New -> text file / folder (you need to press enter)
- Password field in the share dialog and in the user management
- Sharing dialog user input field
- …

For each of these fields, we should have a small arrow button as a confirm mechanism on the right inside the field. Similar to the password reset mechanism (or Add to ownCloud text field in sharing) right now. It should _not_ be a separate button, but integrated in the input field.

cc @owncloud/designers

**Comment by Raydiation** [comment]
:+1: Got bitten by this, apparently to edit a user in the user overview you have to press enter and not unfocus the input.

**Comment by jancborchardt** [comment]
Already in place in a lot of fields, moving rest to 9.0

**Comment by PVince81** [comment]
We're past feature freeze, moving to 9.1. (this doesn't sound like something that can be fixed quickly)

**Comment by PVince81** [comment]
@pmaier1 FYI, I remember seeing a comment from you about this
