### ISSUE TITLE
New milestones for all new issues.

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#15188]
To keep track of all issues and follow up in a better way than today and not "forget" them, my suggestion is to automatically add a milestone called "New Issues" to all new issues. Later we change it to a more appropriate milestone, i.e 8.2, backlog and so on.

Also, what happened to the bot that tells you to use the issue template if not present with an issue template? 

CC @DeepDiver1975

**Comment by enoch85** [comment]
Is this a bad suggestion?

**Comment by karlitschek** [comment]
I´m not sure. We have to look at all the issues and fix them sooner or later. Doesn´t matter it they are "new" or not.

**Comment by enoch85** [comment]
Old issues are often outdated and fixed in new versions anyway. I'm thinking of the public reaction to people visiting Github and sees that ownCloud has 1500 issues or more, that's not a good thing. 

Too keep that number as low as possible is way better than just letting it be. It's also eaiser to keep track of issues if they all have milestones.

**Comment by enoch85** [comment]
...Or if a bot closes all issues older than 6 months with a text that @jancborchardt uses when issues has been open for a long time.

**Comment by Xenopathic** [comment]
@enoch85 We already have a bot, it's called a bored developer :stuck_out_tongue_closed_eyes:

**Comment by enoch85** [comment]
@Xenopathic Haha! And how does that work?

**Comment by Xenopathic** [comment]
@enoch85 Well, dev gets fed up of waiting for Jenkins, or wants to improve the Pulse, or has a headache that day, and so goes through old issues and ~~ruthlessly~~ intelligently closes them.

Problem with a bot is that it will indiscriminantly close *all* issues older than a certain age, regardless of if the issue is placed in backlog or something and simply no-one has got round to fixing it yet.

**Comment by enoch85** [comment]
Ok, I get your point. Anyway @jospoortvliet introduced a bot that adds a "Needs Info" label on al new issues without an issue template, and asked the contributor to add that. 

That was a really great improvement, but I have not seen it in core. 

Closing this anyway as it seems like a bad suggestion.

**Comment by jospoortvliet** [comment]
@enoch85 you probably @ mentioned the wrong person ;-)

I wouldn't know where to begin doing such bot thingies :d 

Meanwhile, what I would like is a view on pull requests that have been open for a long time. Luckily we can have that with github:
https://github.com/pulls?utf8=%E2%9C%93&q=user%3Aowncloud+sort%3Acreated-asc+is%3Apublic+is%3Aopen+is%3Apr+

Of course, you can view that for issues, too:
https://github.com/pulls?utf8=%E2%9C%93&q=user%3Aowncloud+sort%3Acreated-asc+is%3Apublic+is%3Aopen

**Comment by jancborchardt** [comment]
There’s also a way to show issues with no milestone: https://github.com/owncloud/core/issues?q=is%3Aopen+is%3Aissue+no%3Amilestone

So we don’t really need a »no milestone« milestone. ;)

**Comment by jospoortvliet** [comment]
What isn't github magical ;-)
