### ISSUE TITLE
App does not provide an info.xml file

### ISSUE THREAD

**Issue by liquidat** [owncloud/core#15184]
Since an upgrade to Owncloud 8 (currently 8.0.2) I am not able to activate any app - like Documents or Bookmarks. Whenever I click the enable button in the Owncloud webinterface I get the mentioned error message.

I double checked that in my OC 8.0.2 the patch of #14086 is actually applied. Yet, the problem still persists.

Currently I have no idea how to debug the problem, or what the cause is. If I think about what is currently special on my system, I would say the https redirect:

    # Redirect everything to https
    RewriteEngine on
    RewriteCond %{SERVER_PORT} 80
    RewriteRule ^(.*) https://%{HTTP_HOST}%{REQUEST_URI}

Here some version data:

    $ rpm -qa owncloud-server
    owncloud-server-8.0.2-15.1.noarch
    $ cat /etc/centos-release 
    CentOS release 6.6 (Final)
    $ rpm -q php
    php-5.4.39-1.el6.remi.x86_64

**Comment by karlitschek** [comment]
@DeepDiver1975

**Comment by RealRancor** [comment]
@liquidat 
There are a lot of more reported issues/fixes than the one you have linked above. Have you checked all possible duplicates and especially: https://github.com/owncloud/core/issues/14840#issuecomment-85247056

**Comment by VicDeo** [comment]
@liquidat webser error.log and owncloud.log excerpts taken after the attempt to enable the app should shed some light.

**Comment by pavnet** [comment]
I have same problem on fresh install 

ownCloud 8.0.2 (stable)
Apache/2.4.6 (CentOS 7) 
PHP/5.4.16

**Comment by davidtacheny** [comment]
I have the exact same issue on a clean install:  CentOS 7, Nginx, redirect to https self signed certificates , PHP 5.4.16.

**Comment by liquidat** [comment]
@RealRancor I did check some reports, but indeed not enough. Thanks for pointing out #14840 ! The fix in https://github.com/owncloud/core/issues/14840#issuecomment-78648121 indeed fixed my problems.

**Comment by davidtacheny** [comment]
Yes, this works for me, Clean install on CentOS 7:  Adding curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false); in https://github.com/owncloud/core/blob/master/lib/private/httphelper.php#L73 solved it for me.

**Comment by jorin-vogel** [comment]
Also had this issue (on [Uberspace](https://uberspace.de/)). The fix worked. Thanks!
Is there any other way to fix this instead of changing the code?

**Comment by RealRancor** [comment]
@jorin-vogel 
OC 8.1 will ship a workaround for such systems missing the intermediate cert:

https://github.com/owncloud/core/wiki/ownCloud-8.1-Features

**Comment by jorin-vogel** [comment]
@RealRancor thanks for the quick feedback :wink:

**Comment by BerndderHeld** [comment]
@jorin-vogel or anyone else: i am having the same Problem with owncloud (fresh Install 8.0.4) on uberspace. But my httphelper is difrent then the one on Github. Can show me what Version i have to use with the addition of the fix?

my httphelper.php

```
/**
         * Returns the response headers of a HTTP URL without following redirects
         * @param string $location Needs to be a HTTPS or HTTP URL
         * @return array
         */
        public function getHeaders($location) {
                stream_context_set_default($this->getDefaultContextArray());
                return get_headers($location, 1);
        }
```

the one on GitHub:

```
/**
	 * Returns the response headers of a HTTP URL without following redirects
	 * @param string $location Needs to be a HTTPS or HTTP URL
	 * @return array
	 * @deprecated Use \OCP\Http\Client\IClientService
	 */
	public function getHeaders($location) {
		$client = $this->clientService->newClient();
		$response = $client->get($location);
		return $response->getHeaders();
	}
```

the fix:
```
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
```

**Comment by RealRancor** [comment]
Hi,

you can put this in here:

https://github.com/owncloud/core/blob/v8.0.4/lib/private/httphelper.php#L70

PLEASE NOTE: This allows Man-in-the-middle attacks against your connection to the appstore.

As an alternative you could have a look at:

https://forum.owncloud.org/viewtopic.php?f=31&t=26310&p=88393#p85771

or wait until OC 8.1 is released which ships a workaround for systems like yours which are not providing the needed intermediate certificate for the appstore connection.

**Comment by BerndderHeld** [comment]
Sorry for asking again. PHP is not really my language. Can you post the working version function above? And it only breaks the crypto to the Appstore, not the whole SSL structure, right?

**Comment by RealRancor** [comment]
Hi,

> Can you post the working version function above?

just add the:

```
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
```

somewhere in between the calls at https://github.com/owncloud/core/blob/v8.0.4/lib/private/httphelper.php#L67-L70

> And it only breaks the crypto to the Appstore, not the whole SSL structure, right?

It makes all functions where ownCloud is using this http calls to the appstore (and maybe also to other places) vulnerable against this Man-in-the-middle attacks.

**Comment by BerndderHeld** [comment]
Thanks. Now it works and i removed the line again directly after installing the Apps.
