### ISSUE TITLE
  Expire document shared by link after download

### ISSUE THREAD

**Issue by svoop** [owncloud/core#15199]
This is a feature suggestion when sharing a document as link:

![d7dc0822-d263-11e4-909a-ed450494daaa](https://cloud.githubusercontent.com/assets/7255/6830183/8300eb00-d318-11e4-9040-4b6160b8ac53.png)

How about one more checkbox:

* [x] Expire immediately after download

When used together with a date triggered expiration, the link would not work any longer than absolutely necessary.

What do you think?

**Comment by enoch85** [comment]
@jancborchardt

**Comment by jancborchardt** [comment]
I’m really hesitant about adding yet another option for edge-cases here. Unshare after a specific date covers a lot of use-cases. But how do you measure »download«? After the page has been opened? After the »Download« button has been clicked? What about accidentally closing the tab, only opening it on mobile, etc etc.?
But most importantly: Why after the first download? What if the wrong person first opens it? If you only send it to one person, why is it necessary to expire it after the first download anyway?

There are too many variables here which make it unclear on what to base the decision. This is something that someone could write a separate ownCloud app for, but we probably won’t implement it in core.

**Comment by jancborchardt** [comment]
I’m really hesitant about adding yet another option for edge-cases here. Unshare after a specific date covers a lot of use-cases. But how do you measure »download«? After the page has been opened? After the »Download« button has been clicked? What about accidentally closing the tab, only opening it on mobile, etc etc.?
But most importantly: Why after the first download? What if the wrong person first opens it? If you only send it to one person, why is it necessary to expire it after the first download anyway?

There are too many variables here which make it unclear on what to base the decision. This is something that someone could write a separate ownCloud app for, but we probably won’t implement it in core.

cc @owncloud/designers
