### ISSUE TITLE
Icelandic translation change suggested

### ISSUE THREAD

**Issue by thorsig** [owncloud/core#15197]
(I know of the contribution guidelines, but this is short, concise and does not warrant a full-blown report - and contains the solution as well!).

Bug: The "Log in" (Skrá inn) has "&lt;strong&gt;" tags associated with it in the Icelandic translation of the core system (8.0.2) and previous, causing the tags to be displayed in the log-in button on the front page.

I suggest that in core/l18n/is.js, line 87 is changed from
    "Log in" : "&lt;strong&gt;Skrá inn&lt;/strong&gt;"
to
    "Log in" : "Skrá inn"

And similarly line 85 in is.json (exactly the same change).

**Comment by LukasReschke** [comment]
Translations are maintained using Transifex, can you submit this to https://www.transifex.com/projects/p/owncloud/? 

Thanks!
