### ISSUE TITLE
A single shared S2S folder makes a Propfind 50ms slower and that is locally!

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#15198]
@icewind1991 As discussed https://blackfire.io/profiles/de8c7abd-6ad8-449f-9560-e49cea282b35/graph THX

**Comment by PVince81** [comment]
You could try again with https://github.com/owncloud/core/pull/14120

**Comment by PVince81** [comment]
Also related: https://github.com/owncloud/core/issues/13882

**Comment by MorrisJobke** [comment]
@LukasReschke Can you retry? The mentioned PR is merged

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/issues/13882#issuecomment-73927046 (it has a checklist of improvements to be done)
