### ISSUE TITLE
Editing Contacts does not show the same details as creating a new one

### ISSUE THREAD

**Issue by blainy** [owncloud/core#15207]
Since update from 8.0 to 8.0.2 i am no longer able to edit Contacts.
Before the update was done, i could enter details in seperate Fields for Firstname and Lastname for example.
After the update i only have one field called name, when i click on a contact.
On creating a new contact i have also a field called Organisation. I dont get this field displayed when i try to edit an existing contact.

**Comment by karlitschek** [comment]
Can you reopen this in the contacts repository please?
