### ISSUE TITLE
Reshare of file is not downloaded if the file is on a federated server

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#15202]
### Steps to reproduce

1. Make a folder on Server A
2. Share that folder as link
3. Add that folder to Server B 
4. Upload a file from Server B in Server A's folder
5. Reshare that file from Server B as a link
6. Try to download that file, shared from Server B (Server A is the owner)

### Expected behavior

The file from Server A should be downloaded with Server B's shared link

### Actual behavior

I can open the link, but the download stalls, and nothing happens.

### Server configuration on both servers

Ubuntu Server 14.04

**Database:**
Server version: 5.5.41-0ubuntu0.14.04.1 - (Ubuntu)
**PHP version:**
PHP 5.5.9-1ubuntu4.5 (cli) (built: Oct 29 2014 11:59:10)

**ownCloud version:** (see ownCloud admin page)
8.0.2

**List of activated apps:**
Activity
Calender 
Contacts
Deleted files
Documents
First Run Wizard
Full Text Search
PDF Viewer
Pictures
Share Files
Text Editor
Updater
Versions
Video Viewer

**Are you using external storage, if yes which one: local/smb/sftp/...**
No
**Are you using encryption: yes/no**
No

### Client configuration

**Browser:**
Chrome 
**Operating system:**
Windows 8.1
**Sync Client**
1.8 stable
**Mobile app*
Android 1.7.0

### Logs

**Web server error log**

```
Insert your webserver log here
```

**ownCloud log (data/owncloud.log)**

```
Error	PHP	Method OC_L10N_String::__toString() must return a string value at /var/www/owncloud/lib/private/util.php#1025	2015-03-25T20:32:30+00:00
Error	PHP	vsprintf(): Too few arguments at /var/www/owncloud/lib/private/l10n/string.php#75	2015-03-25T20:32:30+00:00

```

**Browser log**

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by MorrisJobke** [comment]
cc @icewind1991 @schiesbn @PVince81

**Comment by nickvergessen** [comment]
Etag propagation error

**Comment by MorrisJobke** [comment]
Fix is in #14764

**Comment by PVince81** [comment]
It's not necessarily 100% the same.
The PR in https://github.com/owncloud/core/pull/14764 is for local shares, not remote shares.

**Comment by PVince81** [comment]
I think it's not an etag propagation error. Rereading the report tells that the download itself doesn't work. It's not about sync client detecting changes, but direct download.

**Comment by PVince81** [comment]
@enoch85 I'll assume that the first link share in your steps has "allow editing" set, else the recipient wouldn't be able to upload there.

**Comment by PVince81** [comment]
These are my steps:
1. Login as "root" on ownCloud A
2. Create a folder "fold"
3. Share "fold" with link and allow editing
4. Log out
5. Open the link
6. Click "Add to ownCloud" and enter the URL to ownCloud B
7. Login as "root" in ownCloud B
8. Accept the incoming share
9. Upload a picture "test.jpg" into "fold"
10. Share "test.jpg" with link
11. Log out
12. Open the last link
13. Click "Download" and view the image

Works for me

**Comment by PVince81** [comment]
@enoch85 doesn't downloading the file from ownCloud B works with the regular web UI (not the share link) ?

Note: I used v8.0.2 for both test instances

**Comment by PVince81** [comment]
@enoch85 maybe you got the steps wrong ? There's another similar case but where the sharing chain is done differently, and I'm able to reproduce that one: https://github.com/owncloud/core/issues/15758

The issue is also a broken download link.

**Comment by enoch85** [comment]
@PVince81 Hmm, I´m not able to reproduce it either now when I tried again. 

I get this errors though:
```
Error	webdav client	curl GET https://cloud.example.se/public.php/webdav/Hansson/test/IMG_20141212_121744.jpg returned status code 201	2015-04-23T10:53:57+00:00
Error	webdav client	curl GET https://cloud.example.se/public.php/webdav/Hansson/hej.txt returned status code 204	2015-04-23T10:47:15+00:00
Error	webdav client	curl GET https://cloud.example.se/public.php/webdav/Hansson/hej.txt returned status code 201	2015-04-23T10:46:58+00:00
```

**Comment by PVince81** [comment]
Hmm status code 201 is "Created" and 204 is "No content". These Statuses should never be returned by a GET operation.

**Comment by PVince81** [comment]
Closing as not reproducible.
