### ISSUE TITLE
OwnCloud Debian packages: Update kills apache

### ISSUE THREAD

**Issue by RalfJung** [owncloud/core#15200]
I just upgraded the OwnCloud packages. The following errors appeared during installation:
```
Setting up owncloud-config-apache (8.0.2-7) ...
Conf owncloud already enabled
 * Reloading web server apache2                                                                                                                                          * 
apache2_invoke rewrite: already enabled
 * Restarting web server apache2                                                                                                                                        (98)Address already in use: AH00072: make_sock: could not bind to address [::]:80
(98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
AH00015: Unable to open logs
Action 'start' failed.
The Apache error log may have more information.
                                                                                                                                                                 [fail]
 * The apache2 instance did not start within 20 seconds. Please read the log files to discover problems
invoke-rc.d: initscript apache2, action "restart" failed.
apache2_invoke owncloud: already enabled
 * Reloading web server apache2                                                                                                                                          * 
 * Apache2 is not running
invoke-rc.d: initscript apache2, action "reload" failed.
```

After this, apache does not work until a restart.

**Comment by enoch85** [comment]
@jnweiger

**Comment by thetazerlaser** [comment]
I'm getting the same problem on Ubuntu 14.04

**Comment by Kawohl** [comment]
I don't see this  as a bug. Restarting Apache after an upgrade should be done in any case manually.

type : service apache start.

**Comment by RalfJung** [comment]
Wait, you are saying the entire server (that is, all the potentially dozens of sites it hosts) being down for several minutes during the ownCloud updates is "not a bug"? Really, a "service apache2 reload" should be good enough for site configuration changes. A restart would be acceptable. But messing up the restarts in a way that the server is down for several minutes, that's certainly *not* acceptable.

**Comment by Kawohl** [comment]
Thinking about it automation would be good. If @jw could point me to the installation script i'll give it a  shot

**Comment by Kawohl** [comment]
@RalfJung Thanks for pointing that out!

**Comment by jnweiger** [comment]
There certainly is an issue. Messages like "Action 'start' failed." should not appear.

@RalfJung Do you still see that happening with newer updates? 

@RalfJung I understand you have an issue with apache stop + start, and would prefer a restart or reload instead.
We do stop + start in the packaging code to be in sync with the documented manual upgrade procedure, which also includes these steps.
 https://doc.owncloud.org/server/8.2/admin_manual/maintenance/upgrade.html#manual-upgrade-procedure

Personally, I believe it is not needed. Having owncloud in maintenance mode during the upgrade should be sufficient to secure consistency of the procedure. A simple apache-reload in the post-install scripts should be fine.

**Comment by jnweiger** [comment]
@Kawohl
 for DEB, we do one simple apache2 reload after the upgrade.
https://build.opensuse.org/package/view_file/isv:ownCloud:community:8.2:testing/owncloud/debian.owncloud-config-apache.postinst?expand=1

For RPM, we do stop + start as coded around lines 503ff and 558ff of
https://build.opensuse.org/package/view_file/isv:ownCloud:community:8.2:testing/owncloud/owncloud.spec?expand=1

I cannot see a reason why RPM based systems do stop+start - a simple reload should do fine too.

**Comment by RalfJung** [comment]
It's been a while since there was a major ownCloud update, the last few minor ones went fine as far as I recall.

**Comment by Kawohl** [comment]
I'll test.

**Comment by Kawohl** [comment]
Updating from 8.1.3 to 8.2rc1 on ubuntu 14.04  works without crashing apache.

These for lines are a little confusing at the end:

invoke-rc.d: policy-rc.d denied execution of restart.
apache2_invoke owncloud: already enabled
invoke-rc.d: policy-rc.d denied execution of reload.
Setting up owncloud (8.2~RC1-3.1) ...

I'll test more versions, and rpm based stuff.

**Comment by jnweiger** [comment]
I saw similar denied execution messages when running inside docker. That may not be a valid test then.

**Comment by Kawohl** [comment]
ah o.k. i'll retest  in full virtual machine again

**Comment by Kawohl** [comment]
Tested and passed!

**Comment by RalfJung** [comment]
I just had this problem again. I opened a new issue, because I could not re-open this one. See #20491.

**Comment by jnweiger** [comment]
The original error is
98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:80

this looks like you have a competing webserver that grabs port 80, while apache is reloading.

**Comment by RalfJung** [comment]
I am pretty sure I do not. The machine is fairly fresh (OS has been installed ~3 months ago), and never saw a webserver besides apache. I never have that issue when I manually reload and restart apache. It is something that ownCloud does in its pre- and/or post-install script that causes the trouble.

**Comment by RalfJung** [comment]
Indeed the postinst script will often trigger *three* reloads, it seems... first it does, in the beginning

```
  a2enconf owncloud || true
  service apache2 reload || true
```

Soon thereafter, it does
```
		apache2_invoke enmod rewrite
```
followed by
```
			apache2_invoke enconf $CONF || exit $?
```

In particular, the $CONF file is enabled twice. `apache2_invoke` ends with:
```
apache2_reload $rcd_action
```
an in the case of enabling a module, `$rcd_action` is restart. So, you are firing "reload" "restart" "reload" to apache, almost at the same time. I agree that this ending up in flames is a bug in apache (which I'll try to reproduce outside of owncloud), but nevertheless, it's also pretty redundant by ownCloud to do this, and kind of asking for trouble (in the form of race conditions).

**Comment by jnweiger** [comment]
I see the redundant calls, but the conditionals are unclear to me. I like to have the 'try always the dummy way' first, and then followed by the more arcane calls that we learned from debian upstream.
I call this arcane, as I cannot follow the logic in if helper-is there, then something, else if status is .... then something else. 

Having helper scripts and having a certain status should be orthogonal. ...

I am not going to change logic here. Too dangerous to break something. I'll instead
add some 'sleep 5' calls. This should help you to confirm if it is indeed race conditions on apache's side.

**Comment by RalfJung** [comment]
Okay. The issue is not 100% reproducible here either, but I will certainly keep you posted when I ever see it again.
