### ISSUE TITLE
isv_ownCloud_community | CentOS 6 | 404 Error: owncloud-app-files_videoviewer-8.0.2-16.1.noarch.rpm

### ISSUE THREAD

**Issue by FlyinFistOfJuda** [owncloud/core#15205]
Hello,

following rpm is missing on the repository:

Downloading Packages:
http://download.opensuse.org/repositories/isv%3A/ownCloud%3A/community/CentOS_CentOS-6/noarch/owncloud-app-files_videoviewer-8.0.2-16.1.noarch.rpm: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.

Error Downloading Packages:
  owncloud-app-files_videoviewer-8.0.2-16.1.noarch: failure: noarch/owncloud-app-files_videoviewer-8.0.2-16.1.noarch.rpm from isv_ownCloud_community: [Errno 256] No more mirrors to try.

**Comment by jnweiger** [comment]
We have issues with the openSUSE Mirror infrastructure. Some mirrors are not updated properly.
See also https://github.com/owncloud/core/issues/15096
I am pinging the friendly admins at SUSE.

**Comment by jnweiger** [comment]
Workaround: Please use https://software.opensuse.org/download.html?project=isv%3AownCloud%3Acommunity%3A8.0&package=owncloud
instead.

**Comment by FlyinFistOfJuda** [comment]
hm, the workaround is ok for a fresh install and will give you -6.1 if i get it right, but i'm already on -15.1. I worked around it by blacklisting the videoviewer for now by adding <code>exclude=owncloud-app-files_videoviewer</code> to the repository file.

**Comment by FlyinFistOfJuda** [comment]
sorry, closed it by commenting it. my bad.

**Comment by FlyinFistOfJuda** [comment]
owncloud-app-files_videoviewer.noarch 0:8.0.2-16.1 is now available in the repo. Thanks.
