### ISSUE TITLE
Update Ubuntu deb 

### ISSUE THREAD

**Issue by binarykitchen** [owncloud/core#15204]
```
sudo sh -c "echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_14.10/ /' >> /etc/apt/sources.list.d/owncloud.list"
sudo apt-get update
sudo apt-get install owncloud
```

still installs the older 7.0.1 version. Could you update the deb file for Ubuntu to your latest version 8.0.2? Thanks

**Comment by enoch85** [comment]
@jnweiger

**Comment by RealRancor** [comment]
@binarykitchen 
http://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_14.10/all/

has OC 8.0.2. There probably are some apt-pinnings configured on your system to favorite OC 7.0.1. Maybe have a look at:

apt-get policy owncloud

**Comment by enoch85** [comment]
You could also try, 

'sudo apt-get aptitude full-upgrade'

**Comment by binarykitchen** [comment]
```
$ apt-cache policy owncloud
owncloud:
  Installed: 7.0.1-0
  Candidate: 7.0.1-0
  Version table:
 *** 7.0.1-0 0
        100 /var/lib/dpkg/status
     6.0.1+dfsg-1ubuntu1.2 0
        500 http://archive.ubuntu.com/ubuntu/ trusty-updates/universe amd64 Packages
     6.0.1+dfsg-1ubuntu1 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
```

Can anybody bump owncloud on Ubuntu's general repo?

**Comment by binarykitchen** [comment]
@enoch85 nah, that will result in an error

```
$ sudo apt-get aptitude full-upgrade
E: Invalid operation aptitude
```

**Comment by enoch85** [comment]
@binarykitchen 
```
Last login: Thu Mar 26 13:43:26 2015 from 192.168.1.115
enoch@enoch:~$ sudo aptitude full-upgrade
[sudo] password for enoch:
No packages will be installed, upgraded, or removed.
0 packages upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B of archives. After unpacking 0 B will be used.
```

**Comment by binarykitchen** [comment]
Ah. Still, no change. `sudo aptitude full-upgrade` still didn't make a difference.

So, can anybody bump owncloud on Ubuntu's general repo? See my comment above.

**Comment by RealRancor** [comment]
@binarykitchen Fix your apt list instead so that the new package will get installed.

**Comment by binarykitchen** [comment]
Ah, adding `sudo sh -c "echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_14.10/ /' >> /etc/apt/sources.list.d/owncloud.list"` and doing a `sudo apt-get dist-upgrade` was the solution.

**Comment by RealRancor** [comment]
Mhhh, so your first add of the repos in your initial report pribably just was unsuccessful.

**Comment by binarykitchen** [comment]
Yes.

And now I am stick with the updater. I am seeing 504 Gateway Time-outs all the time.

**Comment by RealRancor** [comment]
Feel free to close this issue as your initial problem is solved. To workaround time-outs while upgrading have a look at the docs:

https://doc.owncloud.org/server/8.0/admin_manual/maintenance/upgrade.html#upgrading-with-your-linux-package-manager

**Comment by binarykitchen** [comment]
Yeah. Doing this:

```
$ sudo -u www-data php occ upgrade
[sudo] password for michael.heuberger: 
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
```

But there it got stuck for over four minutes and there is no feedback ...

**Comment by RealRancor** [comment]
Just let it run, especially when you're using encryption.

If you're seeing some problems here either create a new issue or maybe also ask at the forums.

**Comment by binarykitchen** [comment]
Yeah, I let it run but it should show a progress bar or give at least some feedback ...

**Comment by RealRancor** [comment]
Just close this issue and create a new feature request as this issue about update issues has the best chances that it won't be noticed. ;-)

**Comment by binarykitchen** [comment]
Alright, thanks for your great support and patience so far!
