### ISSUE TITLE
Access parent folder path in web-interface (feature request)

### ISSUE THREAD

**Issue by sm8ps** [owncloud/core#15220]
When navigating down in a folder hierarchy, the full path (1, cf. picture) eventually gets too wide for the screen size and is replaced by '...' at its left. I repeatedly encounter situations where I would like to move to the omitted parent folder but double-clicking the dots does nothing although it does show the name of the parent folder in a tool tip (2, cf. picture) .

I would like to suggest that double-clicking these dots does open the parent folder.

This certainly is not a major improvement but one I believe being useful for everybody using the web interface. And I suppose it should not impose much work if one knows how to do such things (which I don't, unfortunately). Thanks for this great piece of software!

![lsg - dateien - owncloud - mozilla firefox_026](https://cloud.githubusercontent.com/assets/3989424/6847912/3839f10e-d3ca-11e4-8ed9-6d02b56e5698.png)

**Comment by Xenopathic** [comment]
@sm8ps Does clicking on the Home button (looks like a house) do what you expect?

**Comment by sm8ps** [comment]
Thanks for your reaction, @Xenopathic! Indeed, the home button does what one would expect it to do.
Though that is not really what I am looking for. In a long folder hierarchy, I would like to be able to select the omitted parent folder instead of jumping straight back to the root. That would allow "climbing" back up in the folder hierarchy the same way "../" does in Linux. The way it stands now, one is stuck with current part of the path with the only way out to the root folder.
I have changed my first post with the feature request, hoping to make my point more clear.

**Comment by Xenopathic** [comment]
@sm8ps I'm not too sure what you want to do? When the breadcrumb (the directory path) becomes too long, we compress the left-most directories into the ... to save space. What do you expect to happen if multiple directories are compressed into the ... ? Which one gets opened? If you want to access the parent directory, you can click on the next directory up on the chain, and if you want to get to the very beginning, you have the home button.

**Comment by sm8ps** [comment]
Let me try with an example! Say, I move down the following path:
HOME > SubDirectoryA > SubDirectoryB > SubDirectoryC > SubDirectoryD > SubDirectoryE
For reasons of space, the path is reduced to the following after some point:
HOME > ... > SubDirectoryC > SubDirectoryD > SubDirectoryE
Clicking either one of the sub-directories shows their content which is as expected, as is clicking on the HOME symbol. Hovering the mouse pointer of the breadcrumb shows "SubDirectoryB" in a tooltip but there is no way of accessing this "current parent folder".

My request is to open the "current parent folder" SubDirectoryB when clicking on the breadcrumb. Does that make better sense now?

**Comment by Xenopathic** [comment]
Ah, I understand. What version of oC are you running?

**Comment by sm8ps** [comment]
It is 7.0.4 (stable) on Ubuntu 12.04. (Should have mentioned right away, sorry!)

**Comment by Xenopathic** [comment]
@sm8ps Looks like this was fixed in #10902, which is part of oC 8.0. So good news in that it is already fixed, but bad news in that you need to upgrade to see it :smile:

**Comment by sm8ps** [comment]
@Xenopathic Thanks for the good news as well as for your time spent with this request!
I will not upgrade the whole system anytime soon but am really looking forward to a pleasant surprise when the time shall come. After all, it seems like mind-reading is truly happening here. :)
Congrats to everybody involved!
