### ISSUE TITLE
Sync server2server shares

### ISSUE THREAD

**Issue by taieb92** [owncloud/core#15223]
<h3>Steps to reproduce</h3>

1. Share folder from a server A
2. Add the folder's link to a server B
3. Disable networking

<h3>Expected behavior</h3>

The folder is synced with the owncloud server, and the datas still available after the connection is down

<h3>Actual behavior</h3>

The folder is synced with the client but not accessible from the server when the connection is down

**Comment by MorrisJobke** [comment]
It's not how the federated cloud sharing works. Currently it only mounts the external content. THerefore I marked this as a enhancement

**Comment by tflidd** [comment]
Double of this one: https://github.com/owncloud/core/issues/1190 ?

**Comment by taieb92** [comment]
I found a little trick it may help, I ceated a symbolic link of the synchronized folder from owncloud desktop folder to the owncloud server data folder, so this is what happens when a file is modified in the first server:

1. a file is modified from a server A
2. the server B receive the update
3. the oc desktop app sync the file
4. the symbolic link is updated obviously and you can access to it even if the connection is down

it's not the really efficient but it works

**Comment by rullzer** [comment]
@taieb92 this is not what we want for federated sharing. Server A should have control over the files stored there. Meaning that if user A (on server A) decides one of his files is no longer shared. It should be no longer shared.

**Comment by tflidd** [comment]
But there is an interest for some users, if the internet connection between the two servers is limited (one instance in a data center, second at home). And it is one of the topics that received some money on bountysource: https://www.bountysource.com/issues/905996-owncloud-server-synchronisation-mirrored-redundant-serving

One could think of an option that server B asks server A for authorization (could be as well interesting for a LAN-sync feature: https://github.com/owncloud/client/issues/230).

**Comment by rullzer** [comment]
Sure, but like you pointed out that is #1190.
What is described here is the expected behaviour in the current setting.

Closing this.

**Comment by vtolkm** [comment]
So this is dead then, no dev interested? Would it not be possible to implement the desktop client in a similar fashion as server sync app?

Meantime this may assist those with the need to sync between various clouds https://multcloud.com
