### ISSUE TITLE
CalDav/CardDav Authentication failed

### ISSUE THREAD

**Issue by greg0r** [owncloud/core#15248]
### Steps to reproduce
1. upgrade 7.04 via updater app to 8.02
2. find out that you got to have php 5.4 at least
3. upgrade apache and php via ppa:ondrej/apache2 and ppa:ondrej/php5
4. replace php/fastcgi with php/fpm
5. everything works but no authentication via CalDav/CardDav

### Expected behaviour
Owncloud Client on MacOS, Linux as well as CalDavSync/CardDavSync on Android should accept my username/password like WebInterface. 

### Actual behaviour
Connections through CalDav/CardDav don't accept my credentials.

### Server configuration
**Operating system**: Ubuntu 12.04

**Web server:** apache2.4 / php-fpm5.5

**Database:** mysql
 
**PHP version:** 5.5

**ownCloud version:** 8.02

**Updated from an older ownCloud or fresh install:**7.04

**List of activated apps:**Activity, Calendar, Contacts, Deleted Files, Documents, First Run, Full Textsearch, PDF Viewer, Share Files, Text Editor, Updater, Versions

**The content of config/config.php:**
```
<?php
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'datadirectory' => '/var/www/share/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.0.2.0',
  'dbname' => 'share_oc',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'share',
  'dbpassword' => 'xxx',
  'installed' => true,
  'forcessl' => true,
  'log_type' => 'syslog',
  'loglevel' => '1',
  'log_authfailip' => true,
  'maintenance' => false,
  'theme' => '',
  'trusted_domains' =>
  array (
    0 => 'meine.domain.de',
    1 => 'meine.domain.de',
  ),
  'mail_smtpmode' => 'php',
  'mail_smtpname' => 'john',
  'mail_smtppassword' => 'doe',
  'mail_from_address' => 'owncloud',
  'mail_domain' => 'domain.de',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => true,
  'secret' => 'xxx',
);
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Owncloud Client:**1.5, 1.8

**Operating system:**Ubuntu 14.04

#### Web server error log
```
empty
```

#### Web server access log
```
1.2.3.4 - - [26/Mar/2015:22:01:25 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 401 7032 "-" "Mozilla/5.0 (Linux) mirall/1.8.0"
```

#### ownCloud log (data/owncloud.log)
```
empty
```

#### Owncloud Client log
```
03-26 22:01:25:221 0x1a446f0 Connect to url:  "https://meine.domain.de" 
03-26 22:01:25:221 0x1a446f0 "/home/john/.local/share/data//ownCloud//cookies.db" 
03-26 22:01:25:222 0x1a446f0 Setup-Log:  "Verbindungsversuch mit ownCloud unter https://meine.domain.de…" 
03-26 22:01:25:222 0x1a446f0 !!! OCC::PropfindJob created for  QUrl( "https://meine.domain.de" )  querying "/" 
03-26 22:01:25:435 0x1a446f0 Stop request: Authentication failed for  "https://meine.domain.de/remote.php/webdav/" 
03-26 22:01:25:435 0x1a446f0 void OCC::AbstractNetworkJob::slotFinished() 5 "Operation abgebrochen" 
03-26 22:01:25:439 0x1a446f0 Quota request *not* successful, http result code is 0 "" 
03-26 22:01:25:453 0x1a446f0 QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
```

**Comment by RealRancor** [comment]
Hi,

are you able to open https://meine.domain.de/remote.php/webdav/ in your browsers and login there?

**Comment by greg0r** [comment]
Hi RealRancor,
I am not able to login via this URL in my Browser. Once I open this Link, I am asked to enter username/password and it keeps asking. This is the xml I get as error message.
```
<d:error>
  <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
  <s:message>No basic authentication headers were found</s:message>
</d:error>
```

**Comment by greg0r** [comment]
Hi RealRancor,
I am not able to login via this URL in my Browser. Once I open this Link, I am asked to enter username/password and it keeps asking. This is the xml I get as error message.
```
<d:error>
  <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
  <s:message>No basic authentication headers were found</s:message>
</d:error>
```

**Comment by greg0r** [comment]
Is this issue propably connected with this entry in my apache vhost config?
´´´
ProxyPassMatch ^/(.*\.php(/.*)?)$ fcgi://127.0.0.1:9001/var/www/share/owncloud/$1
´´´

**Comment by enoch85** [comment]
@greg0r 
> Once I open this Link, I am asked to enter username/password and it keeps asking.

Enter the usename and password for your user on ownCloud

**Comment by RealRancor** [comment]
"owncloud is not compatible with PHP in Fast-CGI Mode." from https://github.com/owncloud/core/issues/776

Try the workarounds from there.

**Comment by vgiralt** [comment]
ownCloud works nicely under Apache 2.4 with php-fpm with mod_proxy_fcgi once you sit and think how Apache and ownCloud work!

ownCloud is fully under PHP control, as everything is mostly run either by index.php or remote.php entry points. Then, all of ownCloud is run by the **php-fpm process** not by Apache, so:

1. Anything you put in .htaccess is absolutely moot, as it is never read. See, for example, this [Server Fault link](http://serverfault.com/questions/490667/apache-2-4-with-php-fpm-htaccess-redirection#491503).
2. Apache **never** sees the real filesystem location of ownCloud, it is proxied to the FCGI bye URL regular expression. (See @greg0r comment above)
3. Per 2, <Directory> sections related to ownCloud are *never* evaluated.
4. ***<Location>*** for ownCloud URL local part apply **all** rules, except, of course, those related to mod_php (there is no mod_php), they have to be configured either in .user.ini or in the relevant php-fpm pool configuration (better approach, no per request evaluation).

Hope this helps other fighting ownCloud non-web client authentication.

**Comment by RealRancor** [comment]
@greg0r Could you test https://github.com/owncloud/core/pull/18194 ? Thanks

**Comment by wehe64** [comment]
same here with ownCloud 8.2.7 (stable): I can do a normal login into the web client the but linux desktop client (Version 2.2.3) is rejected ('access not allowed by server'), when I try to log in at /remote.php/webdav/ in my browser (FF) I get: 'This is the WebDAV interface. It can only be accessed by WebDAV clients such as the ownCloud desktop sync client'. No log entrie though. I've tried both FastCGI and FPM (which is a variant of FastCGI) on a Centos box with Plesk - the mod_php is not available there.

**Comment by RealRancor** [comment]
@wehe64 Yes, you need to fix your webserver config to correctly pass the authentication headers to the PHP process. See https://github.com/owncloud/core/pull/18194 for some pointers.

**Comment by wehe64** [comment]
yes, that did the job:
"SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1" in my vhost_ssl.conf on Plesk!
thank you very much, RR!
