### ISSUE TITLE
Default shared folder not used when adding user to group

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15243]
### Steps to reproduce
1. Set "share_folder" to "/Shared" in config.php
1. Create two users "user1" and "user2"
1. Add "user2" to group "group1"
1. Login as "user1"
1. Create a folder "test"
1. Share "test" with "group1"
1. Login as "user2"
1. See that the folder was put in "/Shared/test"
1. Now create a new user "user3" and add to group "group1"
1. Login as "user3"

### Expected result
For "user3" the received share appears as "/Shared/test"

### Actual result
For "user3" the received share appears in the root as "/test"

### Versions
Observed in stable7 and master (likely to be on stable8 too)

@schiesbn @MorrisJobke

**Comment by PVince81** [comment]
Fixed by https://github.com/owncloud/core/pull/15244

**Comment by SergioBertolinSG** [comment]
Tested on stable7, working fine.
