### ISSUE TITLE
Add quota and display to the default creation of users in the provisioning API

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#15242]
While creating users using the provisioning API would be nice to have the option of choosing a quota by default and the display name. Now we don't have that choice and we have to edit the user.

According to documentation:

```
users / adduser
Create a new user on the ownCloud server. Authentication is done by sending a basic HTTP authentication header.

Syntax: ocs/v1.php/cloud/users

HTTP method: POST
POST argument: userid - string, the required username for the new user
POST argument: password - string, the required password for the new user
Status codes:

100 - successful
101 - invalid input data
102 - username already exists
103 - unknown error occurred whilst adding the user
Example
POST http://admin:secret@example.com/ocs/v1.php/cloud/users -d userid="Frank" -d password="frankspassword"
Creates the user Frank with password frankspassword
```

**Comment by PVince81** [comment]
Moving this enhancement to 9.0

@MTRichards @cmonteroluque

**Comment by PVince81** [comment]
CC @tomneedham

**Comment by PVince81** [comment]
@SergioBertolinSG wasn't this added recently by @michag86 ? Or am I mixing this up with something else ?

**Comment by michag86** [comment]
I've only added support for setting the group memberships while adding the user. This is required, if a group admin wants to create a user.

**Comment by PVince81** [comment]
Thanks for the info. Then let's leave this ticket open.

**Comment by michag86** [comment]
Hmmm... and this is not documented yet...  :hushed:
