### ISSUE TITLE
Encryption fails for pipe bar character in file names

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#15241]
Scenario: Enabling encryption on a previously unencrypted ownCloud.

There was one file with the title: `Something something | something | …`, so pipe bars in the titles. That led to not being able to log in to the ownCloud, and this unintelligible error in the log which didn’t really tell me which file it was about:
```
{"reqId":"VMNWy5khJMqjyTU4v5pJ","remoteAddr":"127.0.0.1",
"app":"Encryption library"
"message":"Initial encryption failed! Error: File name contains at least one invalid character",
"level":4,"time":"2015-03-26T19:52:35+00:00"}
{"reqId":"VMNWy5khJMqjyTU4v5pJ","remoteAddr":"127.0.0.1",
"app":"Encryption library",
"message":"Initial encryption failed!",
"level":4,"time":"2015-03-26T19:52:35+00:00"}
```

cc @schiesbn @DeepDiver1975

**Comment by PVince81** [comment]
Is this still happening in recent versions ?
You didn't specify what version you had the issue with.

**Comment by jancborchardt** [comment]
The version was with current master at that time (March 26). Haven’t given encryption a go recently.
