### ISSUE TITLE
group & members permission mismatch

### ISSUE THREAD

**Issue by mhaggel** [owncloud/core#15253]
Hi,
I need some help: Either I have a problem understanding how the permissions of a share work or there is a bug in the code (owncloud 8.0.2).

situation: User A shares a folder X with a group M. All the group members (the users) have initially the same permissions ('15' by looking into the DB). 
By revoking the 'delete' one from the group then the group & members get permissions '7'. (so far so good)
Giving back the removed one the group has again the '15', however the individuals (users) got stuck with the '7'. 
Eventually if i continue play around with the group permissions i will end up having a share with group permission 15 and individual group members with 1!! 
Since i am relatively new to ownCloud, i would like to ask whether this is an expected behavior or not. 

One more clue is that i am getting users & groups from ldap.

Many thanks in advance.
M.

**Comment by PVince81** [comment]
Hmm, likely to be a bug. I'd expect that giving back the permissions would also update the permissions for the group members.
From what I remember, group members may in some cases get their own entries in the "oc_share" table (additionally to the group entry), and maybe the permissions aren't updated properly there.

**Comment by PVince81** [comment]
Still reproducible on 8.1.3 and 8.2RC1.

For some reason removing permissions work and updates the sub-shares from the group share. But adding back the permissions doesn't.

Is this by design or a bug @schiesbn @rullzer ?

**Comment by rullzer** [comment]
> Is this by design or a bug

That is kind of grey area ;)

> For some reason removing permissions work and updates the sub-shares from the group share. But adding back the permissions doesn't.

Time to fire up XDebug.. I'll see what I can dig up

**Comment by rullzer** [comment]
So yeah we simply do not check for the added permissions case: https://github.com/owncloud/core/blob/master/lib/private/share/share.php#L1105-L1106

This is weird since all children should be updated as well. Or well the children of the same share.. e.g. the user moved the mountpoint so there is an extra entry in the shares table.

Lets write a ~~unit~~ test for this. And then see if we can fix it without breaking all of sharing.
