### ISSUE TITLE
Handle batched WebDAV PUT requests

### ISSUE THREAD

**Issue by jturcotte** [owncloud/core#15264]
Here is a patch for the performance-tests-c++ that uses HTTP multipart to send multiple PUTs in a single HTTP request:
https://gist.github.com/jturcotte/d787bf8c0c6f3f92405d

You can apply it on top of https://github.com/owncloud/administration

If you notice performance improvements worth the extra code complexity, we can then make sure that the client takes advantage of it.

**Comment by jturcotte** [comment]
cc @DeepDiver1975 @dragotin

**Comment by PVince81** [comment]
This was discussed here: https://github.com/owncloud/core/issues/12001

**Comment by jturcotte** [comment]
Ok, I looked for it but didn't fine any, let me re-copy my comment there.
