### ISSUE TITLE
Do not show table headers in »SSL root certificates« section when there are none

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#15263]
Currently the SSL root certificates section looks quite strange with the stray table headers:
![capture du 2015-03-27 09 53 36](https://cloud.githubusercontent.com/assets/925062/6864859/29d8564e-d467-11e4-88f4-00c2dc4934f3.png)

Let’s hide the headers while there are no certificates present. Of course they should show up again as soon as a certificate is loaded. (I tried some basic PHP check but of course that will not bring up the headers again …)

cc @icewind1991 @schiesbn maybe.

**Comment by jancborchardt** [comment]
Fixed via https://github.com/owncloud/core/pull/15345

**Comment by rullzer** [comment]
PR #15544 merged
