### ISSUE TITLE
external storage: WebDAV method works but ownCloud not

### ISSUE THREAD

**Issue by der-domi** [owncloud/core#15262]
I'm using ownCloud 8.0.2. I can connect from one ownCloud server to another one with the WebDAV method by using the address
   https://www.example.com/oc/remote.php/webdav

But it doesn't work with the ownCloud method by using the address
   https://www.example.com/oc/
Error message: Forbidden

Take a look to https://forum.owncloud.org/viewtopic.php?f=31&t=27359

**Comment by PVince81** [comment]
Don't use the "WebDAV" external storage for ownCloud, it will not work properly (due to part files handling).

Please use the "ownCloud" external storage backend, you just need to put the target OC URL like "https://www.exaxmple.com/oc" and the credentials, it should work.

**Comment by PVince81** [comment]
If it still doesn't work, please post your settings and owncloud.log

**Comment by PVince81** [comment]
Ok sorry, I misread. You said it works with WebDAV but not the OC method.
Hmmm, strange.

**Comment by der-domi** [comment]
That's it! The correct URL is "https://www.exaxmple.com/oc" (without the last slash). It would be helpfully if the correct URL of the ownCloud method will be named somewhere in the documentation.
Maybe the software itself can handle the last slash :-)

Thanks for help!

**Comment by PVince81** [comment]
If the bug is only about the last slash, let's keep this open to fix it.
I'd expect the external storage module to be able to automatically strip it if needed...

**Comment by PVince81** [comment]
CC @Xenopathic

**Comment by der-domi** [comment]
Sorry :-)

**Comment by Xenopathic** [comment]
Fixed in #14475, but hasn't been backported. Perhaps we should?
