### ISSUE TITLE
files_external app suppresses remember log in?

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#15277]
For the encryption app I know that »remember me« is not shown. But it seems that the files_external app also does it (see the `<rememberlogin>` in the info.xml).

@LukasReschke what’s the reason here / is this needed? Just asking. :)

**Comment by Xenopathic** [comment]
We sometimes need the password for SMB_OC to mount the share. It's the only storage using it at the moment, but conceivably more could use it in the future.

**Comment by DeepDiver1975** [comment]
Some backends rely on the password being stored in the session and there fore we require login.

**Comment by jancborchardt** [comment]
Ok, thanks for the clarification. Then at least we have this on record somewhere.
