### ISSUE TITLE
Cryptic error message not helping at all to solve the issue at hand

### ISSUE THREAD

**Issue by arkascha** [owncloud/core#15272]
I was just thrown an error message into my face by an installation of OC-8.0.2. The message is impossible to understand for non developers. And the "No such file or directory" leads to wrong conclusions too, I'd say. See attached screenshot....

![screenshot-oc8-crash](https://cloud.githubusercontent.com/assets/2156237/6867873/68d0590e-d486-11e4-9bc0-7219a35e76ad.png)

Turned out after a minute that the issue simply was that OC is configured to use mysql and the mysql server was down. 

I think it would make sense to detect such obvious causes and offer an error message that actually helps.

**Comment by VicDeo** [comment]
Since 10.4 it is more user-friendly due to https://github.com/owncloud/core/pull/36413 
<img width="581" alt="Screenshot_20200407_152138" src="https://user-images.githubusercontent.com/991300/78668613-a20ea700-78e3-11ea-861e-fd48b262f40c.png">
:smile:

**Comment by DeepDiver1975** [comment]
> Turned out after a minute that the issue simply was that OC is configured to use mysql and the mysql server was down.
> 
> I think it would make sense to detect such obvious causes and offer an error message that actually helps.

it actually is already pretty obvious if one has a tech understanding - we can close this from my pov.

**Comment by DeepDiver1975** [comment]
> Since 10.4 it is more user-friendly due to #36413
> <img alt="Screenshot_20200407_152138" width="581" src="https://user-images.githubusercontent.com/991300/78668613-a20ea700-78e3-11ea-861e-fd48b262f40c.png">
> smile

this is something to discuss in a new issue
