### ISSUE TITLE
How to unshare folders/files from expired users after upgrading from OC5 to OC7?

### ISSUE THREAD

**Issue by gig13** [owncloud/core#15283]
In ownCloud5 there were expiration of shares available for the users. When upgrading to ownCloud7, this feature is missing, and we wanted to know how to expire/remove these "shares" for all of the user shares that are on the existing system.

There are thousands of users, so this is not something that each user can do individually as a part of operations. How can we do this in a quick and efficient manner?

@MTRichards @bboule

**Comment by karlitschek** [comment]
@PVince81 @schiesbn

**Comment by MorrisJobke** [comment]
There is an option to expire public link shares. I wonder that back in ownCloud 5 also normal user-to-user shares were expired. I thought the checkbox in the webinterface was just separated more and the expiry date was also send for new shares if the user has set that to a date.

cc @jancborchardt I thought you were also involved into the process of dividing this functionality. But I doubt, that there was a global option. I couldn't find one in the web interface (admin settings)

**Comment by butonic** [comment]
@gig13 Do I understand correctly that this is a one time action for the migration? then we could create a simple SQL query to remove all user / group shares with an expiration date, if that is what is wanted. What db is used?

**Comment by gig13** [comment]
@butonic @bboule 
We will need to discuss if it is one time for migration or custom add on to enable older functionality.

**Comment by MorrisJobke** [comment]
Ref #Can't contact LDAP server code -1

**Comment by MorrisJobke** [comment]
Ref #15459

**Comment by bboule** [comment]
@gig13 looks like this is done and checked on for 9 do you need a backport or are we good?

**Comment by gig13** [comment]
@bboule 
I do not have a reference for this case, no further comments

**Comment by MorrisJobke** [comment]
> I do not have a reference for this case, no further comments

So closing this?
