### ISSUE TITLE
'oci' missing in owncloud/lib/private/setup.php

### ISSUE THREAD

**Issue by gnuppek** [owncloud/core#15280]
According to the owncloud documentation Oracle database is supported as database backend. In owncloud/lib/private/setup.php Oracle database is provided as member of $availableDatabases, but is missing in line 91 of said file, so the installation wizard does not provide Oracle database as an option.

Can be fixed as follows:

```--- setup.php   2015-03-09 14:27:15.000000000 +0100
@@ -88,7 +88,7 @@
                        )
                );
                $configuredDatabases = $this->config->getSystemValue('supportedDatabases',
-                       array('sqlite', 'mysql', 'pgsql'));
+                       array('sqlite', 'mysql', 'pgsql', 'oci'));
                if(!is_array($configuredDatabases)) {
                        throw new Exception('Supported databases are not properly configured.');
                }
```

**Comment by DeepDiver1975** [comment]
oci is to be enabled in the config - see https://github.com/owncloud/core/blob/master/config/config.sample.php#L94

**Comment by gnuppek** [comment]
I just tried that. Nope, you have to fix the code according to my proposal first.

**Comment by DeepDiver1975** [comment]
create a separate config file - e.g. db.config.php with this content:

```php
<?php
$CONFIG = array(
    'supportedDatabases' => array(
        'sqlite',
        'mysql',
        'pgsql',
        'oci'
    ),
);

**Comment by LukasReschke** [comment]
Please notice that anything over basic file sync and share (such as apps as calendar or contacts) will probably not work on Oracle and are untested – thus the comment that this is officially only supported in the Enterprise Edition.

**Comment by gnuppek** [comment]
@LukasReschke Since Calendar and Contacts are supported in the EE, I thought it might work in the Community Edition too. I just didn't expect two separate apps for each of Calendar and Contacts with codebases that different. Too much effort to maintain. Maybe I'm wrong. The other explanation might be: It doesn't work for EE either and nobody ever noticed...

**Comment by LukasReschke** [comment]
> @LukasReschke Since Calendar and Contacts are supported in the EE, I thought it might work in the Community Edition too.

They ar enot.

**Comment by LukasReschke** [comment]
https://owncloud.com/lp/owncloud-server-or-enterprise-edition/
