### ISSUE TITLE
Issue with Windows Network Drive Plugin

### ISSUE THREAD

**Issue by wingZero21** [owncloud/core#15296]
Hi,

We have installed Owncloud via the repositories supplied, however when looking at the admin config currently its giving the below error.

Is there any further information as to why this may be occuring as far as we can see both libsmbclient and php5-libsmbclient are installed and enabled for php.

There does not seem to be that much helpful about this in the owncloud logs either.

Details:
Error:
```
Windows network drive application cannot locate the libsmbclientor php-libsmbclient libraries. Please ensure these libraries are properly installed and accessible by PHP
```
rpm -qa | grep libsmb
php5-libsmbclient-0.5.0-25.1.x86_64
libsmbclient-3.6.9-151.el6.x86_64

**Comment by DeepDiver1975** [comment]
did you reboot the webserver after installing these packages?

Please supply all necessary information as explained in https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by wingZero21** [comment]
Hi,

I have managed to resolve this by compiling the requirement php5-libsmbclient from source. (https://github.com/eduardok/libsmbclient-php)

It looks like the RPM that is getting provided seems to not work for us and our version of php 5.5. With the version of php 5.5 that was recommended by owncloud support I had recompile with the maintainer-zts option below.

With owncloud recommended php 5.5

```
./configure --with-php-config=/usr/bin/zts-php-config --enable-debug --enable-maintainer-zts
```

With our php 5.5
```
./configure
```

**Comment by DeepDiver1975** [comment]
@wingZero21 where did you get the package php5-libsmbclient-0.5.0-25.1.x86_64 from? THX

**Comment by DeepDiver1975** [comment]
@jnweiger is this our package? THX

**Comment by wingZero21** [comment]
Hi,

Yeah its the RPM that was provided from the Owncloud Enterprise repo.

**Comment by DeepDiver1975** [comment]
@wingZero21 I'm closing this issue therefore - please get in touch with ownCloud support - THX
