### ISSUE TITLE
require_once(): Failed opening required '/appinfo/remote.php

### ISSUE THREAD

**Issue by heartsaver** [owncloud/core#15299]
### Steps to reproduce
1. install a app

### Server configuration
**Operating system**:
Ubuntu 14.04.2 LTS

**Web server:**
Apache/2.4.12 (Ubuntu)
Server built:   Feb  4 2015 14:22:06

**Database:**
MySQL 5.5.41-0ubuntu0.14.04.1 - (Ubuntu)

**PHP version:**
PHP 5.6.7-1+deb.sury.org~trusty+1 (cli) (built: Mar 24 2015 11:21:10)

**ownCloud version:** (see ownCloud admin page)
8.0.2

**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
Activity 1.2.0; Bookmarks 0.4; Calendar 0.6.4; Contacts 0.3.0.18; Deleted files 0.6.2; Documents 0.9.0;File Locking; First Run Wizard 1.1; Full Text Search 0.6.0; Mail Template Editor 0.1; PDF Viewer 0.7; Pictures 0.6.0; Provisioning API 0.2; Share Files 0.6.1; Text Editor 0.4; Updater 0.4; 
Versions 1.0.5; Video Viewer 0.1.3

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => 'url_to_owncloud',
    1 => 'url_to_owncloud',
  ),
  'datadirectory' => 'data',
  'overwrite.cli.url' => 'url_to_owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.2.0',
  'dbname' => '',
  'dbhost' => 'localhost',
  'dbtableprefix' => '',
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'loglevel' => 2,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'mail_smtpmode' => '',
  'mail_smtpsecure' => '',
  'mail_smtpauthtype' => '',
  'mail_smtpauth' => ,
  'mail_smtphost' => '',
  'mail_smtpport' => '',
  'mail_from_address' => 'owncloud',
  'mail_smtpname' => '',
  'mail_smtppassword' => '',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
SSL

### Client configuration
**Browser:**
Chrome 41

**Operating system:**
Windows 8

#### Web server error log
Nothing from owncloud

Insert your webserver log here
Nothing from owncloud

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
Error	PHP	Undefined index: REQUEST_URI at /var/www/html/apps/calendar/appinfo/app.php#41	2015-03-29T18:45:01+00:00
Error	PHP	require_once(): Failed opening required '/appinfo/remote.php' (include_path='/var/www/html/3rdparty/phpseclib/phpseclib/phpseclib:/var/www/html/3rdparty/pear/pear_exception:/var/www/html/3rdparty/pear/archive_tar:/var/www/html/lib/private:/var/www/html/config:/var/www/html/3rdparty:/var/www/html/apps:/var/www/html/lib:.:/usr/share/php:/usr/share/pear:/var/www/html') at /var/www/html/remote.php#54	2015-03-29T18:35:12+00:00
Error	PHP	require_once(/appinfo/remote.php): failed to open stream: No such file or directory at /var/www/html/remote.php#54	2015-03-29T18:35:12+00:00
Error	PHP	require_once(): Failed opening required '/appinfo/remote.php' (include_path='/var/www/html/3rdparty/phpseclib/phpseclib/phpseclib:/var/www/html/3rdparty/pear/pear_exception:/var/www/html/3rdparty/pear/archive_tar:/var/www/html/lib/private:/var/www/html/config:/var/www/html/3rdparty:/var/www/html/apps:/var/www/html/lib:.:/usr/share/php:/usr/share/pear:/var/www/html') at /var/www/html/remote.php#54	2015-03-29T18:20:10+00:00
Error	PHP	require_once(/appinfo/remote.php): failed to open stream: No such file or directory at /var/www/html/remote.php#54	2015-03-29T18:20:10+00:00
Error	PHP	require_once(): Failed opening required '/appinfo/remote.php' (include_path='/var/www/html/3rdparty/phpseclib/phpseclib/phpseclib:/var/www/html/3rdparty/pear/pear_exception:/var/www/html/3rdparty/pear/archive_tar:/var/www/html/lib/private:/var/www/html/config:/var/www/html/3rdparty:/var/www/html/apps:/var/www/html/lib:.:/usr/share/php:/usr/share/pear:/var/www/html') at /var/www/html/remote.php#54	2015-03-29T18:20:09+00:00
Error	PHP	require_once(/appinfo/remote.php): failed to open stream: No such file or directory at /var/www/html/remote.php#54	2015-03-29T18:20:09+00:00
Error	PHP	require_once(): Failed opening required '/appinfo/remote.php' (include_path='/var/www/html/3rdparty/phpseclib/phpseclib/phpseclib:/var/www/html/3rdparty/pear/pear_exception:/var/www/html/3rdparty/pear/archive_tar:/var/www/html/lib/private:/var/www/html/config:/var/www/html/3rdparty:/var/www/html/apps:/var/www/html/lib:.:/usr/share/php:/usr/share/pear:/var/www/html') at /var/www/html/remote.php#54	2015-03-29T18:20:09+00:00
Error	PHP	require_once(/appinfo/remote.php): failed to open stream: No such file or directory at /var/www/html/remote.php#54	2015-03-29T18:20:09+00:00
Error	PHP	require_once(): Failed opening required '/appinfo/remote.php' (include_path='/var/www/html/3rdparty/phpseclib/phpseclib/phpseclib:/var/www/html/3rdparty/pear/pear_exception:/var/www/html/3rdparty/pear/archive_tar:/var/www/html/lib/private:/var/www/html/config:/var/www/html/3rdparty:/var/www/html/apps:/var/www/html/lib:.:/usr/share/php:/usr/share/pear:/var/www/html') at /var/www/html/remote.php#54	2015-03-29T18:20:08+00:00
Error	PHP	require_once(/appinfo/remote.php): failed to open stream: No such file or directory at /var/www/html/remote.php#54	2015-03-29T18:20:08+00:00
Error	PHP	require_once(): Failed opening required '/appinfo/remote.php' (include_path='/var/www/html/3rdparty/phpseclib/phpseclib/phpseclib:/var/www/html/3rdparty/pear/pear_exception:/var/www/html/3rdparty/pear/archive_tar:/var/www/html/lib/private:/var/www/html/config:/var/www/html/3rdparty:/var/www/html/apps:/var/www/html/lib:.:/usr/share/php:/usr/share/pear:/var/www/html') at /var/www/html/remote.php#54	2015-03-29T18:20:07+00:00
Error	PHP	require_once(/appinfo/remote.php): failed to open stream: No such file or directory at /var/www/html/remote.php#54	2015-03-29T18:20:07+00:00
Error	PHP	unlink(/var/www/html/themes/default/core/lostpassword/templates/email.php): No such file or directory at /var/www/html/apps/templateeditor/lib/mailtemplate.php#107

#### Browser log
Nothing from owncloud

**Comment by heartsaver** [comment]
Don't have an issue at owncloud anymore, but my cron.php don't work anymore...

cron.php

<?php
/**
 * ownCloud
 *
 * @author Jakob Sack
 * @copyright 2012 Jakob Sack owncloud@jakobsack.de
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU AFFERO GENERAL PUBLIC LICENSE for more details.
 *
 * You should have received a copy of the GNU Affero General Public
 * License along with this library.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

// Unfortunately we need this class for shutdown function
class TemporaryCronClass {
	public static $sent = false;
	public static $lockfile = "";
	public static $keeplock = false;
}

// We use this function to handle (unexpected) shutdowns
function handleUnexpectedShutdown() {
	// Delete lockfile
	if (!TemporaryCronClass::$keeplock && file_exists(TemporaryCronClass::$lockfile)) {
		unlink(TemporaryCronClass::$lockfile);
	}

	// Say goodbye if the app did not shutdown properly
	if (!TemporaryCronClass::$sent) {
		if (OC::$CLI) {
			echo 'Unexpected error!' . PHP_EOL;
		} else {
			OC_JSON::error(array('data' => array('message' => 'Unexpected error!')));
		}
	}
}

try {

	require_once 'lib/base.php';

	if (\OCP\Util::needUpgrade()) {
		\OCP\Util::writeLog('cron', 'Update required, skipping cron', \OCP\Util::DEBUG);
		exit();
	}

	// load all apps to get all api routes properly setup
	OC_App::loadApps();

	\OC::$server->getSession()->close();

	// initialize a dummy memory session
	\OC::$server->setSession(new \OC\Session\Memory(''));

	$logger = \OC_Log::$object;

	// Don't do anything if ownCloud has not been installed
	if (!OC_Config::getValue('installed', false)) {
		exit(0);
	}

	// Handle unexpected errors
	register_shutdown_function('handleUnexpectedShutdown');

	\OC::$server->getTempManager()->cleanOld();

	// Exit if background jobs are disabled!
	$appmode = OC_BackgroundJob::getExecutionType();
	if ($appmode == 'none') {
		TemporaryCronClass::$sent = true;
		if (OC::$CLI) {
			echo 'Background Jobs are disabled!' . PHP_EOL;
		} else {
			OC_JSON::error(array('data' => array('message' => 'Background jobs disabled!')));
		}
		exit(1);
	}

	if (OC::$CLI) {
		// Create lock file first
		TemporaryCronClass::$lockfile = OC_Config::getValue("datadirectory", OC::$SERVERROOT . '/data') . '/cron.lock';

		// We call ownCloud from the CLI (aka cron)
		if ($appmode != 'cron') {
			// Use cron in future!
			OC_BackgroundJob::setExecutionType('cron');
		}

		// check if backgroundjobs is still running
		if (file_exists(TemporaryCronClass::$lockfile)) {
			TemporaryCronClass::$keeplock = true;
			TemporaryCronClass::$sent = true;
			echo "Another instance of cron.php is still running!" . PHP_EOL;
			exit(1);
		}

		// Create a lock file
		touch(TemporaryCronClass::$lockfile);

		// Work
		$jobList = \OC::$server->getJobList();
		$jobs = $jobList->getAll();
		foreach ($jobs as $job) {
			$job->execute($jobList, $logger);
		}
	} else {
		// We call cron.php from some website
		if ($appmode == 'cron') {
			// Cron is cron :-P
			OC_JSON::error(array('data' => array('message' => 'Backgroundjobs are using system cron!')));
		} else {
			// Work and success :-)
			$jobList = \OC::$server->getJobList();
			$job = $jobList->getNext();
			if ($job != null) {
				$job->execute($jobList, $logger);
				$jobList->setLastJob($job);
			}
			OC_JSON::success();
		}
	}

	// done!
	TemporaryCronClass::$sent = true;
	// Log the successful cron execution
	if (\OC::$server->getConfig()->getSystemValue('cron_log', true)) {
		\OC::$server->getAppConfig()->setValue('core', 'lastcron', time());
	}
	exit();

} catch (Exception $ex) {
	\OCP\Util::writeLog('cron', $ex->getMessage(), \OCP\Util::FATAL);
}

php Error

PHP Warning:  flock() expects parameter 1 to be resource, boolean given in /var/www/html/lib/private/config.php on line 178
PHP Fatal error:  Call to a member function getValue() on null in /var/www/html/lib/private/legacy/config.php on line 46

**Comment by RealRancor** [comment]
```
`PHP Warning: flock() expects parameter 1 to be resource, boolean given in /var/www/html/lib/private/config.php on line 178
PHP Fatal error: Call to a member function getValue() on null in /var/www/html/lib/private/legacy/config.php on line 46
```

That shows you're having some permission problems: https://github.com/owncloud/core/issues/13912

**Comment by DeepDiver1975** [comment]
> That shows you're having some permission problems: #13912

yes - closing
