### ISSUE TITLE
Verbosity of the occ command is broken

### ISSUE THREAD

**Issue by binarykitchen** [owncloud/core#15290]
If I run it with the `v` flag or not results into the same output:

```
$ sudo -u www-data php occ upgrade -vv
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
...
```

and

```
$ sudo -u www-data php occ upgrade
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
...
```

**Comment by DeepDiver1975** [comment]
Basically we are aware of that - we will take care within 8.2 - thx

**Comment by binarykitchen** [comment]
Okay. But I am migrating from 7.0.1 to 8.0.2 and `occ` is not working at all. Without verbosity I do not know where and why it fails. 

Isn't there a log or anything else that could tell me why `occ` is failing??

**Comment by binarykitchen** [comment]
PS: It's pretty serious and cannot wait until v8.2 is out

**Comment by DeepDiver1975** [comment]
> Okay. But I am migrating from 7.0.1 to 8.0.2 and occ is not working at all. Without verbosity I do not know where and why it fails.

Why do you think occ is broken? I assume you have encryption enabled - there is a migrations step in place which moving around encryption keys - this operation can *unfortunately* take pretty long.

This is fixed with 8.0.3

**Comment by DeepDiver1975** [comment]
> PS: It's pretty serious and cannot wait until v8.2 is out

occ running almost forever - true - fixed in 8.0.3.
occ not being that verbose - hmmm - well .... :wink:

**Comment by binarykitchen** [comment]
When is v8.0.3 out and can be installed via `apt-get`?

Yes, I have encryption here. Long running processes MUST feedback the progress back to the user. That's something `occ` should do. Show an percent indicator or something like that.

Otherwise I end up guessing something is broken and I hit CTRL-C in the middle.

**Comment by binarykitchen** [comment]
@DeepDiver1975 `occ` has been running for more than two days and still no progress has been made :(

```
$ sudo -u www-data php occ upgrade -vvv
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
```

STUCK HERE after 48 hours ... what should I do?

**Comment by DeepDiver1975** [comment]
8.0.3 will be out in the next two weeks.

**Comment by binarykitchen** [comment]
Hmmm, I cannot wait that long. What should I do now? Any chance I can cherry-pick the bugfix now?

**Comment by DeepDiver1975** [comment]
@binarykitchen this is the patch: https://github.com/owncloud/core/pull/14669

**Comment by binarykitchen** [comment]
Thanks @DeepDiver1975 but how do I deploy this patch when I installed owncloud via apt-get instead of git?

**Comment by DeepDiver1975** [comment]
> Thanks @DeepDiver1975 but how do I deploy this patch when I installed owncloud via apt-get instead of git?

In this case before break your installation I highly suggest you wait for the new package.
I'm not going to teach patching here - and afterwards I'm guilty for breaking your system.
No - sorry - this is not going to happen.

**Comment by binarykitchen** [comment]
Smart response @DeepDiver1975 

Alright, while waiting for two weeks, how can I bring back the owncloud server alive then? It's v8.0.2 but not migrated yet. I need access to my calendar which is quite urgent.

**Comment by binarykitchen** [comment]
Or do you think you could release v8.0.3 now as an urgent bugfix and postpone the rest to v8.0.4?

Das Release-Management sollte ja flexibel sein ;)

**Comment by DeepDiver1975** [comment]
> Or do you think you could release v8.0.3 now as an urgent bugfix and postpone the rest to v8.0.4?

official release take their time - we shall no overreact.

**Comment by binarykitchen** [comment]
@DeepDiver1975 how's going? any news?

**Comment by binarykitchen** [comment]
ping?

**Comment by Xenopathic** [comment]
The thing is, `occ` doesn't have *broken* verbosity, it just doesn't print anything at higher verbosities at all. It will still log to owncloud.log AFAIK, so you might find some useful information in there. Even if we do start printing more information to the console at higher verbosities, it might not be the information you need to fix your issue!

**Comment by binarykitchen** [comment]
Ah, I had two log files, one was never used and I fixed the location of the log file in the config. Now I restarted the migration and finally some output telling me what's wrong:

```
$ cat owncloud.log 
{"reqId":"adfa90fdea8e035025ab16bc2b659b1a","remoteAddr":"","app":"PHP","message":"copy(\/var\/www\/owncloud\/data\/owncloud_private_key): failed to open stream: No such file or directory at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#211","level":3,"time":"2015-04-20T11:05:52+00:00"}
{"reqId":"adfa90fdea8e035025ab16bc2b659b1a","remoteAddr":"","app":"PHP","message":"copy(\/var\/www\/owncloud\/data\/public-keys): failed to open stream: No such file or directory at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#211","level":3,"time":"2015-04-20T11:05:53+00:00"}
{"reqId":"adfa90fdea8e035025ab16bc2b659b1a","remoteAddr":"","app":"PHP","message":"opendir(\/var\/www\/owncloud\/data\/public-keys): failed to open dir: No such file or directory at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#78","level":3,"time":"2015-04-20T11:06:00+00:00"}
{"reqId":"adfa90fdea8e035025ab16bc2b659b1a","remoteAddr":"","app":"PHP","message":"opendir(\/var\/www\/owncloud\/data\/files_encryption\/keyfiles): failed to open dir: No such file or directory at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#78","level":3,"time":"2015-04-20T11:06:00+00:00"}
{"reqId":"adfa90fdea8e035025ab16bc2b659b1a","remoteAddr":"","app":"PHP","message":"opendir(\/var\/www\/owncloud\/data\/owncloud_private_key): failed to open dir: No such file or directory at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#78","level":3,"time":"2015-04-20T11:06:00+00:00"}
{"reqId":"adfa90fdea8e035025ab16bc2b659b1a","remoteAddr":"","app":"core","message":"unable to rename, file does not exists : files_encryption\/michael.heuberger.private.key","level":3,"time":"2015-04-20T11:33:49+00:00"}
```

Hmmm, it says some files are missing. What should I do?

**Comment by binarykitchen** [comment]
turns out that the `occ` command did mess around with my keys while migrating from v7 to v8 and got aborted in the middle.

i found some backup folders and copied back the missing keys. giving the `occ` command another try now.

can you ensure that the `occ` command is purely transaction-oriented? so that, when aborted, everything is reverted to the original state?

**Comment by PVince81** [comment]
> can you ensure that the occ command is purely transaction-oriented? so that, when aborted, everything is reverted to the original state?

No, this is technically impossible because it requires the whole platform and third party apps that hook into the platform to be transaction-oriented. If an app makes changes to files (and encryption is one) they'd need to also support a `revert` API to be able to revert stuff back, if even possible.
