### ISSUE TITLE
Shared lLink not working in linux terminal

### ISSUE THREAD

**Issue by MegaV0lt** [owncloud/core#15292]
When i share a loink in Desktopclient i can not get teh file in linux. When i enter 

wget https://...

There comes an errormessage that the cert is nut trustet...

Screenshot shows share dialog (SheevaPlug = my local oc-server) and linux terminal via ssh

![Image errormesg](http://i.imgur.com/XRVyBuR.png)

Also the variant with /download is not working

OC is Debain 8.0.2-5
Edit: Self Signed SSL -Cert

**Comment by PVince81** [comment]
Please add `--no-check-certificate` to your wget command.
It's not an OC bug.
