### ISSUE TITLE
Animation for right sidebar doesn’t work

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#15308]
I also added the same animations we use for the Apps and User menus to also fire for the Sharing and Versions dropdowns. For some reason they only work for the _closing_ animation of the Share dropdown.

Can you help here @PVince81 @MorrisJobke @owncloud/designers? The relevant line is at https://github.com/owncloud/core/blob/master/core/js/share.js#L593 – the function is added there.

`$('#dropdown').slideDown(OC.menuSpeed);` – that works at least for the Apps and Users menu.

**Comment by jancborchardt** [comment]
*cough* soo … @MorrisJobke … you need something new to work on after fixing https://github.com/owncloud/core/issues/12326? ;)

**Comment by PVince81** [comment]
8.2 says goodbye dropdowns

**Comment by jancborchardt** [comment]
Well, the sidebar should have a quick animation too. ;)

**Comment by PVince81** [comment]
@jancborchardt a quick animation where ? when closing the sidebar ?

**Comment by jancborchardt** [comment]
Both for opening and closing.

**Comment by cmonteroluque** [comment]
This bug will fall off 8.2 if not resolved by 6 Oct

**Comment by PVince81** [comment]
moved to general design / UX / styling issues group ticket: https://github.com/owncloud/core/issues/27578
