### ISSUE TITLE
Enhancement: unread notification badges

### ISSUE THREAD

**Issue by zkvvoob** [owncloud/core#15309]
Hello,

I don't know whether this is the appropriate venue for this, so please excuse me if I'm posting in the wrong place.

Has anyone considered the possibility to add unread notification badges on top of OwnCloud's apps' icons? Take me, for instance: I'm actively using the News app, RainLoop, ocSMS and Tasks. Wouldn't it be great if one could see at a glance that there are unread emails and 25 new item in one's news feed?

What do you think? Is it doable?

**Comment by nickvergessen** [comment]
@jancborchardt

**Comment by jancborchardt** [comment]
Yeah, that would be doable and sensible design-wise at least. Is this data exposed already or how would we display it in the navigation cc @DeepDiver1975?

**Comment by jancborchardt** [comment]
cc @owncloud/designers what do you think? I’m undecided yet between a badge with an actual counter and a simple badge without counter to not be too detailed.

**Comment by zkvvoob** [comment]
Hello,

What do you mean by "a simple badge without counter" - what would this
badge be used for?

2015-04-09 9:55 Гринуич+03:00, Jan-Christoph Borchardt
<notifications@github.com>:

**Comment by nickvergessen** [comment]
> Is this data exposed already or how would we display it in the navigation

We are talking about new stuff, so no, there is no data already somewhere. Once we have the option, app developers can start to expose data to display it there.

**Comment by jancborchardt** [comment]
As talked about with @ChristophWurst, it should be a simple red dot for new notifications since last check. A number is not necessary because the exact number makes little difference. People will not remember if the number changed from the one that was there before – it’s more important if there was a change since last checked.

**Comment by jancborchardt** [comment]
We now have a Notifications app: https://github.com/owncloud/notifications

A mechanism for per-app unread badges would need to be addressed separately.

**Comment by stefan-niedermann** [comment]
@zkvvoob what do you think about my suggestion? https://github.com/owncloud/activity/issues/10 scroll down for mock-up ;)

**Comment by jancborchardt** [comment]
@stefan-niedermann did you look at the notifications app? ;)

**Comment by stefan-niedermann** [comment]
not available on the apps store, even after enableing "experimental apps" - am i missing something?

**Comment by zkvvoob** [comment]
@stefan-niedermann The mockup looks quite lovely. I'm going to give the app itself a test run right away.

Are you planning on changing the icon of the drawer when there are unread notifications?

**Comment by stefan-niedermann** [comment]
@zkvvoob just to prevent any misunderstanding:
- i am not the developer of owncloud/notifications - i didn't even knew it.
- the mockup is just a mockup^^ i did not develop anything and currently have not the time for it. also my suggestion (owncloud/activity#10) was closed yesterday without any reason.

so i will have a look to the owncloud/notifications app in the near future and see if this is, what i wanted.

**Comment by nickvergessen** [comment]
> the mockup is just a mockup^^ i did not develop anything and currently have not the time for it. also my suggestion (owncloud/activity#10) was closed yesterday without any reason.

The reason is, that such stuff is handled in the notifications app now. :wink:

**Comment by stefan-niedermann** [comment]
sounds good, but again:

> not available on the apps store, even after enableing "experimental apps" - am i missing something?

where can i find this app? do i have to install it manually?

@zkvvoob sorry for bloating your issue :-/

**Comment by nickvergessen** [comment]
It will be shipped with 8.2 because it depends on changes that are in ownCloud 8.2 only. Should be there on the daily builds already, other then that wait for the alpha or beta

**Comment by PVince81** [comment]
Notifications app was shipped a long time ago. Apps need to use its APIs to publish their unread notifications there.
