### ISSUE TITLE
"External API" documentation outdated

### ISSUE THREAD

**Issue by mss** [owncloud/core#15317]
I hope this is the correct place to report a documentation issue.

While looking for a public API to access ownCloud from a 3rd party app, I reached the page https://doc.owncloud.org/server/8.0/developer_manual/core/externalapi.html

There you can find the sentence

> ownCloud version 5.0 will follow the OCS v1.7 specification (draft).

Since this is the documentation for version 8.0, it is clearly outdated. I think it should just be replaced with

> ownCloud implements the OCS v1.7 specification (draft).

But I can't be sure since I don't know since I'm still at the start of my research for an API :-)

**Comment by RealRancor** [comment]
Hi,

unfortunately this is the wrong place. The issue tracker of the documentation is located here:

https://github.com/owncloud/documentation/issues/
