### ISSUE TITLE
Problem with the email adresse registering using the Roundcube plugin

### ISSUE THREAD

**Issue by Supafish** [owncloud/core#15316]
Hello,

I noticed a bug with the Roundcube plugin. In my password there is a "!" and i can't register it in the Personnal page. If I want to access the plugin I have to go to the real roundcube interface, login, then go to the plugin page.

This is all the information I can give you, feel free to ask any questions.

**Comment by LukasReschke** [comment]
Please report this to the roundcube plugin developer. It's a third-party plugin.
