### ISSUE TITLE
Anmeldung owncloud

### ISSUE THREAD

**Issue by adm-doan** [owncloud/core#15311]
Guten Tag

Meldet man sich an ownclod mit einem falschen Passwort an, so kann u.U. keine Mail ausgelöst werden.
Meldung:
E-Mail zum Zurücksetzen des Passworts kann nicht versendet werden..."
Vermutlich genau dann, wenn bei der Eingabe des Benutzernamens Grossbuchstaben verwendet werden also Anna.Doerr statt anna.doerr.

Freundliche Grüsse
Anna Dörr

**Comment by RealRancor** [comment]
Hi,

please try to write in English and also use the issue template provided here:

https://raw.github.com/owncloud/core/master/issue_template.md

as asked in the "guidelines for contributing" (linked in the yellow box when creating a new issue).

**Comment by karlitschek** [comment]
Please ask your question in the owncloud forum. thank you.
