### ISSUE TITLE
$user variable not working when using SMB/CIFS with OC login in OC 8.0.2

### ISSUE THREAD

**Issue by reneglauser** [owncloud/core#15313]
Hi, I trie to use SMB/CIFS mount with OC login. It works, but I can not access the user-directory directly with variable $user as described in documentation. My share is called "users$" and the subdirectory is named with the users login-name. In the logs I always get the following message:

Debug	OC\Files\Cache\Scanner	!!! Path '' is not accessible or present !!!

best Regards
René

**Comment by Xenopathic** [comment]
Just to confirm, you want to access `//server.domain/users$/<username>`? And you set the share to `users$` and the root to `$user`?

Could you also fill out the issue template, it'd really help us fix your problem: https://github.com/owncloud/core/blob/master/issue_template.md

In addition, have you tried with the standard SMB/CIFS storage type?

**Comment by mmattel** [comment]
Maybe to consider:
http://support.microsoft.com/en-us/kb/90929

When sharing folders or drives with Windows, if a dollar sign ($) character is added to the end of a share name, the share name does not appear in a browsed list of available shares on the server. 
If you know the full name of the hidden share, you can obtain access to it normally by typing its name with a $ at the end.
This functionality is also supported in LAN Manager.
For example, if drive C: is shared as ROOT$ on the machine SERVER, then ROOT$ does not appear when SERVER is browsed by a workstation. However, if a user enters \\SERVER\ROOT$ as the path in the Connect Network Drive dialog box, the user can connect to the hidden server.

Therefore a test without having the root (remote subdirectory) set to $user would be helpful to see if there is a problem with the sharename having a $ sign at the end or not.

**Comment by reneglauser** [comment]
Thanks for your feedback. I tried it again by creating a new share without $ sign. OC-login is working with user-account, but again, when I try to use the variable $user for the shares subdirectory, it dows not work. When I leave the field subdirectory empty I can connect to the directory by clicking on its linkt...that works. It also works, when I replace the variable $user by the real usernam "xyz", but that is not what I want.... I realy think, that the content of variable $user is wrong or maybe there is no $user variable ?

**Comment by Xenopathic** [comment]
Tested with SFTP, and it works, so I don't think the replacement of `$user` is an issue here. I haven't been able to test with SMB due to a broken setup...

**Comment by Xenopathic** [comment]
Scratch that - I got SMB working. And it works fine with `$user` in the subfolder path. This was tested on master

**Comment by chrisys** [comment]
Just as an addition to @reneglauser 's comment - I too am experiencing the exact issue as described. I need to use $user in the subfolder path but it does not seem to be working. The other scenarios exactly as described work for me but when using the $user variable they do not.

**Comment by reneglauser** [comment]
I think now to know why it does not work on my side. My internal user ids of my ldap-users in owncloud are different then the users login name. But my subfolders I would like to access are the same as the users login name. So I think I should have the possibility to change the content of $user variable that it corresponds to my users login name....is this possible?

**Comment by Xenopathic** [comment]
AH, that explains it. It reminds me of the very similar issue I ran into when creating SMB_OC in the first place: https://github.com/owncloud/core/blob/master/apps/files_external/lib/smb_oc.php#L50

**Comment by mmattel** [comment]
@Xenopathic 
We could think of a additional functionality like:

- if subdirectory parameter has set $user
- if a checkmark in the mount option (to be created) is set
- then try to create the subdirectory on access, if it does not exist, if base share is writable
Then you never have an access problem and it is it is immediate recogizable which user-id/name ect triggers it.

What do you think?

**Comment by Xenopathic** [comment]
@mmattel You mean like your enhancement report over at #12836 ? :laughing:

**Comment by mmattel** [comment]
Yes :smile:

**Comment by reneglauser** [comment]
for me it would be great, if the content of $user could be set individually with an ldap-field

**Comment by PVince81** [comment]
@jvillafanez

**Comment by jvillafanez** [comment]
`$user` variable is supported in newer versions (at least from 9.0). Try 9.0.5 or 9.1.1 and reopen if the issue is still present in your environment.
