### ISSUE TITLE
  Problem of remove folder

### ISSUE THREAD

**Issue by littlejo** [owncloud/core#15315]
### Steps to reproduce
1. create a folder
2. click on remove folder

### Expected behaviour
folder should be in a trash

### Actual behaviour
folder is still here

### Server configuration
**Operating system**: CentOS 7
**Web server:** Apache
**Database:** MySQL
**PHP version:** 5.4
**ownCloud version:** 8.0.2
**Updated from an older ownCloud or fresh install:** 8.0.0
**List of activated apps:** LDAP
**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'oc4v2ps1ccs5',
  'trusted_domains' =>
  array (
    0 => 'cloud.ensta.fr',
    1 => 'nuage.ensta.fr',
  ),
  'datadirectory' => '/var/data',
  'overwrite.cli.url' => 'https://cloud.ensta.fr/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.2.0',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_ligier',
  'installed' => true,
  'forcessl' => true,
  'ldapIgnoreNamingRules' => false,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => 0,
);

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** LDAP

#### ownCloud log (data/owncloud.log)

    {"reqId":"02dde82340af345ee1c48f30d8e18835","remoteAddr":"147.250.91.193","app":"PHP","message":"rename(): The first argument to copy() function cannot be a directory at \/var\/www\/html\/lib\/private\/files\/storage\/local.php#204","level":3,"time":"2015-03-30T12:10:17+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/delete.php"}
    {"reqId":"02dde82340af345ee1c48f30d8e18835","remoteAddr":"147.250.91.193","app":"PHP","message":"rename(\/var\/data\/8d5dc32e-ea68-102f-9930-8ffa7bb38356\/files\/test-forum,\/var\/data\/8d5dc32e-ea68-102f-9930-8ffa7bb38356\/files_trashbin\/files\/test-forum.d1427717417): No such file or directory at \/var\/www\/html\/lib\/private\/files\/storage\/local.php#204","level":3,"time":"2015-03-30T12:10:17+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/delete.php"}
    {"reqId":"02dde82340af345ee1c48f30d8e18835","remoteAddr":"147.250.91.193","app":"PHP","message":"Undefined index: \/var\/data\/8d5dc32e-ea68-102f-9930-8ffa7bb38356\/files\/test-forum at \/var\/www\/html\/apps\/files_locking\/lib\/lockingwrapper.php#140","level":3,"time":"2015-03-30T12:10:17+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/delete.php"}

**Comment by littlejo** [comment]
The related topic is : https://forum.owncloud.org/viewtopic.php?f=31&t=27445

**Comment by littlejo** [comment]
the patch : https://cloud.ensta.fr/index.php/s/2QZBHwDRvg5iWOp

**Comment by LukasReschke** [comment]
@littlejo Could you submit this as pull request? THX!

**Comment by DeepDiver1975** [comment]
@icewind1991 can you please grab this patch and add proper unit tests please - THX

**Comment by nickvergessen** [comment]
We might run out of disc space when the folder is big and we try to duplicate it?
