### ISSUE TITLE
user can't change login password

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#15328]
Tested with current master. 

Changing the user password in the personal settings fails. There is no error message and everything seems to work fine but the password wasn't changed.

Steps to reproduce
1. go to personal settings
2. change password by enter old and the new password
3. logout and try to login with the new password -> fails
4. login with the old password still works

**Comment by Xenopathic** [comment]
Breaking commit is 55e1226dfee2778d92e7dbaf9e907f20a80c073b, introduced in #14918

cc @MorrisJobke @PVince81 @jancborchardt
