### ISSUE TITLE
Failed to update

### ISSUE THREAD

**Issue by highacid** [owncloud/core#15323]
Currently running 8.0.2 but I am unable to bypass this upgrade. And on installatron is not visible any new update. What can I do? This runs in Centos 6.2

An exception occurred while executing 'CREATE TABLE oc_ownc_appconfig_onqvlmrkfntpq (`appid` VARCHAR(32) DEFAULT '' NOT NULL, `configkey` VARCHAR(64) DEFAULT '' NOT NULL, `configvalue` LONGTEXT DEFAULT NULL, INDEX oc_a2vls4sy53zwo (`configkey`), INDEX oc_s847k3e1ik5px (`appid`), PRIMARY KEY(`appid`, `configkey`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_ownc_appconfig_onqvlmrkfntpq' already exists

**Comment by DeepDiver1975** [comment]
Which db and version?

**Comment by RealRancor** [comment]
Very likely a dups: https://github.com/owncloud/core/issues/14916 and/or https://github.com/owncloud/core/issues/14242

**Comment by highacid** [comment]
Well I run Mysql 5.6 and this should be 8.0.2 somehow it wants to make this update, and it crashed.
