### ISSUE TITLE
Add a word to icon in bottom of sidebar

### ISSUE THREAD

**Issue by bnvk** [owncloud/core#15322]
![screen shot 2015-03-31 at 12 11 50 am](https://cloud.githubusercontent.com/assets/48677/6908806/75b1e608-d740-11e4-839c-dc1ac9a00b2e.png)

So, this icon was so tucked away + minimalist that I didn't even notice it until I was reading through documentation and it showed a screenshot. Granted, one reason is I am on a rather larger screen, but still. I would advocate one of the following possibilities:

- [Icon] Settings
- [Icon] Contact Settings

**Comment by karlitschek** [comment]
@jancborchardt

**Comment by bnvk** [comment]
@karlitschek thanks. I don't why I forgot to tag @jancborchardt that spicy dude!

**Comment by ddxor** [comment]
Submitted a PR to address this issue

**Comment by MorrisJobke** [comment]
PR: #15387

**Comment by jancborchardt** [comment]
I'm not sure showing icon _and_ text is a good solution here. It would be the only item in the sidebar with both, giving more importance to the entry than it deserves. Maybe text only is a good call.

However, @bnvk it seems you had a very specific issue in this case. It was in the Contacts app, and you wanted to find how to sync your contacts, right?

**Comment by bnvk** [comment]
@jancborchardt nah, it wasn't specific to contacts, I honestly just didn't notice the gear icon at all in any of the apps for a while as I was exploring how to add, import, configure my virutally empty ownCloud instance.

But re: `"the only item in the sidebar with both"` maybe in Files or Calendar, but the Contacts app has "+" icons:

![screen shot 2015-04-03 at 6 32 33 pm](https://cloud.githubusercontent.com/assets/48677/6985224/4cf216fe-da31-11e4-9ddd-4f103e89caef.png)

Or has this been changed in Version 8? Apologies if it has!

**Comment by jancborchardt** [comment]
A follow up is at https://github.com/owncloud/core/pull/15488 – showing both text and icons for all sidebar entries in the Files app. I also picked up your commit @ddxor, please review. :)

**Comment by MorrisJobke** [comment]
fixed in #15488

**Comment by jancborchardt** [comment]
@bnvk thank you for the suggestion homie! Can’t wait to see your first code contributions. ;)
