### ISSUE TITLE
Generating URLs for AJAX calls

### ISSUE THREAD

**Issue by fpiraneo** [owncloud/core#15334]
In the old 6 and 7 the following function fits the need:

var dataPath = OC.filePath('appname', 'ajax', 'savePrefs.php');

Now, as stated on the doc the following should be used (https://doc.owncloud.org/server/8.0/developer_manual/app/js.html):

var authorUrl = OC.generateUrl('/apps/myapp/authors/1');

Unfortunately the script crashes and I cannot realize what's wrong; a better example should help; a backward compatibility should be the best.

What changed on the new time of OC8's? Can someone clarify?

**Comment by karlitschek** [comment]
Hi. This is a great question. I suggest to ask this on the devel mailinglist.
Thanks a lot.

**Comment by DeepDiver1975** [comment]
> Unfortunately the script crashes and I cannot realize what's wrong; a better example should help; a backward compatibility should be the best.

You can still use the old mechanism - so backwards compatibility is given

var dataPath = OC.filePath('appname', 'ajax', 'savePrefs.php');

**Comment by fpiraneo** [comment]
If this was the case I won't opened an issue here! :-)
Unfortunately with the old mechanism the script crashes and instead of the JSON data I get an HTML page, maybe from the owncloud core because with xdebug I checked that my ajax/savePrefs.php is not called at all.
So, again my question: What's changed from the 6 & 7 to the 8?
Or: With Firefox I'm not able to see the complete answer string on JavaScript debugger; is there a workaround to see the complete AJAX answer string or maybe on other browser we don't have the issue?

**Comment by LukasReschke** [comment]
> Unfortunately with the old mechanism the script crashes and instead of the JSON data I get an HTML page, maybe from the owncloud core because with xdebug I checked that my ajax/savePrefs.php is not called at all.

Then this is a complete different error. Please try always to be as precise as possible when reporting an error.

Please take a look at the changelog: https://doc.owncloud.org/server/8.0/developer_manual/app/changelog.html

> Applications not using the AppFramework need now to register their routes as well in appinfo/routes.php. See https://mailman.owncloud.org/pipermail/devel/2014-August/000565.html

**Comment by fpiraneo** [comment]
All the informations I have are here; if not in here I don't have more precise informations; 

"Applications not using the AppFramework need now to register their routes as well in appinfo/routes.php."

I think that this is a major change (and frankly speaking I don't understand why change something that works) and it should be reported on main documentation.

**Comment by LukasReschke** [comment]
Well – the change is in the **main documentation for developers** and was announced in August last year on the developer mailinglist. Sometimes changes needs to be done for multiple reasons (that one was for enhanced security).

There will always be small changes that need to be done and this one takes about 20 seconds to perform especially as the original PR includes a script to generate the required file.

Regarding the original issue: From the issue description one might think that the URL Generation does not work, in fact however, the URL is properly generated but the route just does not exists as it is not registered.

**Comment by fpiraneo** [comment]
| Sometimes changes needs to be done for multiple reasons (that one was for enhanced security).

"Increase the WOPR security or mess up instead?" (Cit. War Games)
