### ISSUE TITLE
iphone login without app does not work

### ISSUE THREAD

**Issue by credel** [owncloud/core#15330]
### Steps to reproduce
open owncloud login page

### Actual behaviour
in Safari on iphone the login button is "grey" (see attachd photos) 
i can not click on login and return on the keyboards does not work too.
if i use Opera on my iphone it is working.

### Server configuration
it is not working on demo.owncloud.org and on my private server (Ubuntu 14.04.1 / Owncloud 8.0.2 -> base installation without modifications)

### Client configuration
Safari
iOS 8.2

img_2261 is safari login page with grey login button.
img_2262 is opera with usual login button
img_2263 is after the login with opera

![img_2261](https://cloud.githubusercontent.com/assets/7223602/6918135/287e0b30-d7ab-11e4-9702-fc4535b8690e.PNG)
![img_2262](https://cloud.githubusercontent.com/assets/7223602/6918133/27d78896-d7ab-11e4-9f5d-f71d5d95c6a1.PNG)
![img_2263](https://cloud.githubusercontent.com/assets/7223602/6918134/2862b222-d7ab-11e4-9730-90b19d0d78e3.PNG)

**Comment by karlitschek** [comment]
@jancborchardt any idea?

**Comment by jancborchardt** [comment]
No, no clue. Can any other iPhone users reproduce? @karlitschek @LukasReschke 

@credel does this happen with other instances as well or only the demo?

**Comment by credel** [comment]
hi, have tested it with the demo and on my server (fresh installed ubuntu without any modifications) 
both have the same problem...

**Comment by LukasReschke** [comment]
Can test tomorrow on my instance… iPhone charger is broken so I need a new one… Kudos for Apple for not using Micro USB…

**Comment by tflidd** [comment]
I can login with safari (iOS 8.2) on demo.owncloud.org. Wifi and cellular, both without proxy.

**Comment by credel** [comment]
found the issue! you have to enable cookies in safari, then it is working!
