### ISSUE TITLE
Multimedia category in apps management is always empty

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#15347]
Using master, PHP 5.5

### Steps to reproduce
* Create or modify an app so that it belongs to the Multimedia category. Like this: https://github.com/interfasys/galleryplus/blob/master/appinfo/info.xml#L15
* Unpack the app in the apps folder
* Go to apps management
* Got to the "Multimedia" category

### Expected result
The app should show up 

### Actual result 
The category is empty. The app shows up in the "Not enabled" category.

**Comment by RealRancor** [comment]
Hi,

i think the categories are provided by the API if apps.owncloud.com and not by the app itself. As soon as the app is provided by the appstore it should appear in the correct category.

**Comment by DeepDiver1975** [comment]
We need a clear distinction between apps from the store and local apps.

As of today this seems to be too confusing. 

@jancborchardt

**Comment by oparoz** [comment]
@RealRancor - Unfortunately, that only works for official apps, so it doesn't really help since most apps are only available through manual installation.

@DeepDiver1975 While I agree that it's good to be able to identify official apps (there is another ticket talking about trust levels), I think the app manager should use info.xml to classify apps. There is no point in having them all in the "not enabled" category.

**Comment by RealRancor** [comment]
@oparoz 
It should also work for "non-official" 3rdparty apps IF they are approved in the appstore. If the approval of new app is working as expected you shouldn't even have to install the apps manually.

But sure, an additional entry in the info.xml is probably the best choice here.

**Comment by oparoz** [comment]
@RealRancor - What do you mean approved? The app manager is a ghost town compared to what's available on the appstore.
Multimedia: Empty
PIM: 2 official apps
Productivity: 2 official apps
Game: Empty
Tool: 1 unofficial app
Other: 1 official app

90% of these apps came with the distribution, so that means we're only getting 1-2 apps made by 3rd parties.

info.xml already has everything needed. The app manager just needs to use it.

**Comment by RealRancor** [comment]
@oparoz

See this recent discussion at the ML:

http://owncloud.10557.n7.nabble.com/Visibility-of-apps-published-in-the-quot-app-store-quot-td14842.html

**Comment by oparoz** [comment]
Thanks. I'm glad this is going to be sorted for 8.1.
And hopefully the app manager will be able to parse the info.xml in 8.2

**Comment by jancborchardt** [comment]
@DeepDiver1975 
> We need a clear distinction between apps from the store and local apps.
> As of today this seems to be too confusing. 

Separating between store and local apps would be confusing. Apps which are local (downloaded via zip or git) should have a category as well – it should probably be in the info.xml.

**Comment by oparoz** [comment]
This has now been fixed in the apps store.
