### ISSUE TITLE
Help! Upgrade from 6.? to 8.0.2 on Debian 7 via apt didn't work

### ISSUE THREAD

**Issue by angico** [owncloud/core#15341]
Hi!

After installation, launching the site in upgrade mode it says:

"Updates between multiple major versions are unsupported.
The update was unsuccessful. Please report this issue to the ownCloud community."

Now, I just can't access my owncloud. Any hints?

TIA!!!

**Comment by karlitschek** [comment]
You have to go to owncloud 7 first. The latest owncloud 7 package should also be in the repository.

**Comment by RealRancor** [comment]
Its not exactly the same link but here we go:

https://software.opensuse.org/download/package?project=isv:ownCloud:community:7.0&package=owncloud

**Comment by RealRancor** [comment]
Btw. ref for a request to also add those "older" repository links to the owncloud.org page: https://github.com/owncloud/owncloud.org/issues/468
