### ISSUE TITLE
upgrade from 8.0.0 to 8.0.2 saw some peculiar action

### ISSUE THREAD

**Issue by wdiechmann** [owncloud/core#15350]
with 16 clients, 3 of which are Windows Server services, the rest being Windows and Mac clients, we upgraded owncloud from 8.0.0 to 8.0.2 using yum on a CentOS system with the data store being a symbolic linked folder into a NFS mounted 18TB Synology NAS - which bared the upgrade and forced us to umount the data store before finalizing the upgrade, and once performed, we reboot'ed 

once restartet the server had created a new data store and the mount failed which had us rename the new data store, recreate the symbolic link to the NFS mounted data store and change the permissions and ownership -- only to discover that in the time frame from reboot to data store rename, the server had issued commands to all clients to sync the standard documents share (which on the server now was empty) 

recreating the data store obviously is the default action to take on the owncloud servers behalf but how could we stop the server from issuing delete commands with a pristine data store?

could a missing data store on a 'production' server perhaps indicate some error and put the server in a special 'no actions taken' mode until cleared by service personel?

with mostly family 'hit' by this we did not suffer substantial damage but other systems might be on the look out!

**Comment by RealRancor** [comment]
Mhhh, strange. Normally ownCloud should detect a missing datadirectory https://github.com/owncloud/core/pull/7732 and shouldn't take any actions if the .ocdata file is missing.

**Comment by DeepDiver1975** [comment]
> Mhhh, strange. Normally ownCloud should detect a missing datadirectory #7732 and shouldn't take any actions if the .ocdata file is missing.

indeed

@wdiechmann data was symlinked to the NFS mount - right? Loosing symlink and mount during upgrade might still cause issues as we had the logic to generate the .ocdata during upgrade - we might need to harden the .ocdata check during upgrade.

@jnfrmarks interesting upgrade scenario we should consider to add to our regression test suite - THX

**Comment by wdiechmann** [comment]
well - we observed otherwise :/

at the time of upgrade

/var/www/html/owncloud/data was symbolically linked to

/etc/fstab
10.0.0.186:/volume1/ckup_data	/mnt/ckup_data_mnt	nfs	wsize=8192,atime,exec,dev,rsize=8192,_netdev	0	0

as seen with ls -la
lrwxrwxrwx  1 apache apache    23 31 mar 13:14 data -> /mnt/ckup_data_mnt/data

nobody:nobody owns all files in the data store as per

/etc/idmapd.conf
Nobody-User = nobody
Nobody-Group = nobody

and this is how it has all panned out according to the terminal session stdout log:

**Comment by PVince81** [comment]
some hardening done here: https://github.com/owncloud/core/pull/28432
