### ISSUE TITLE
space full in client but quota set to unlimited...

### ISSUE THREAD

**Issue by piettt** [owncloud/core#15355]
Hello,

this is not the first time I have this bug.

After the update to 8.0.2 we have a problem with the quota. I don't remember how to fix it.

If I put the quota to unlimited (or more than 50GB) I have a maximum of 36GB :

![2015-04-01_10h06_00](https://cloud.githubusercontent.com/assets/7397394/6938357/18c06892-d863-11e4-9458-69bc3cc3442f.jpg)

If I put the quota to 40GB, I have a maximum of 31GB, and the space is full :

![2015-04-01_10h11_36](https://cloud.githubusercontent.com/assets/7397394/6938358/1a20f40e-d863-11e4-8acb-3bb6d62f9824.jpg)

We have the client version 1.7.1, and we install the update 1.8.0 but still have this bug.

If someone have a idea to fix this bug...

Regard

**Comment by piettt** [comment]
### Server configuration
**Operating system**:
Debian 7.
**Web server:**
Linux server-debian-oc 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u2 x86_64 GNU/Linux
7.8
Debian GNU/Linux 7 \n \l
**Database:**

**PHP version:**
5.5.23-1
**ownCloud version:** (see ownCloud admin page)
8.0.2
**List of activated apps:**
Default
**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

**Operating system:**
Windows 7 64bits (or Mac OS 10.8)
### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)

too big : more than 

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...

**Comment by piettt** [comment]
Ok, apparently the problem was the ownCloud log (data/owncloud.log)

more than 364GB....

**Comment by tflidd** [comment]
Probably a good idea to set the 'log_rotate_size' option in your config.php
