### ISSUE TITLE
Make settings/js/personal.js unit testable

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#15352]
Currently the personal settings page is almost impossible to unit test. It would be great to rewrite this so we get more code coverage. And can actually verify if still keeps working ;)

I can imagine this has to be done in various pr's.

PR's blocked by this.
- #15345 

CC: @PVince81

**Comment by PVince81** [comment]
That kind of thing needs to be tagged as "technical debt", not "enhancement" :smile: 

I agree with you. Eventually we should make all JS code unit-testable with proper wrapping/encapsulation.
