### ISSUE TITLE
Sharing a file add multiple "(2)" to the file name

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#15361]
If I share a file or folder multiple "(2)" gets added to the file for the recipient, even if there is no name conflict. If the recipient logout and login ownCloud adds again some "(2)" so that the filename gets longer and longer.

I experienced this behaviour with current master.

cc @PVince81 @icewind1991 afaik you made some changes to the way the shares gets mounted and conflicts get resolved. Can you have a look? Thanks!

**Comment by schiesbn** [comment]
I will debug it... seems to happen only on one of my branches based on master

**Comment by schiesbn** [comment]
It only happens here https://github.com/owncloud/core/pull/14472 if encryption is enabled because setupFS() get's called multiple times. But within the OC\Filesystem code for example if the encryption does a ````$view->file_exists($encryptionKey);````

As a short work arround I did this https://github.com/owncloud/core/commit/65150e050536c339bc434638e4fd1ddb7493ff84 so that I can continue to work on the encryption. @icewind1991 would be great if you could have a look at it. Thanks!

**Comment by PVince81** [comment]
@schiesbn are you still seeing this ?

**Comment by schiesbn** [comment]
This seems to be fixed with the latest changes to the way we mount the shares.
