### ISSUE TITLE
Undelete not working with Swift as primary backend storage

### ISSUE THREAD

**Issue by shanecentre** [owncloud/core#15379]
When files are deleted though sync client, web interface or mobile app the file is immediately removed from the swift back-end storage without fallowing the undelete rules in 8.0.2.  Undelete works as expected in using local storage.

**Comment by karlitschek** [comment]
yes. this is a known limitation of the current implementation.

**Comment by RealRancor** [comment]
Hi,

not absolutely sure but i think this is already discussed here: https://github.com/owncloud/core/issues/10328
