### ISSUE TITLE
Error Enabled Apps per groups

### ISSUE THREAD

**Issue by DemisBand** [owncloud/core#15377]
### Steps to reproduce

1. Enable Apps with "Enable only for specific groups "
2. Add several groups

### Expected behaviour

The apps are only enabled for these groups

### Actual behaviour

When there are multiple configured groups (local or LDAP), apps do not appear. 

### Server configuration

Debian 7.5
Apache2
MySQL
5.4.39
Owncloud 8.0.2
Fresh install
User-backend : LDAP/ActiveDirectory

**Comment by karlitschek** [comment]
@jnfrmarks Can you help reproducing this ?

**Comment by nickvergessen** [comment]
I'm on it, fixed this on master last week... but its not a straight forward backport

**Comment by MorrisJobke** [comment]
Fix was merged #15378
