### ISSUE TITLE
Fatal error messag log entry when enabling files_external

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#15375]
Ubuntu 14.04 nginx 1.7.11 MySQL
oC from git master updated today

When I enable files_external, I get a error message logged:

Fatal	core	Invalid OCS content returned for app files_external

**Comment by karlitschek** [comment]
Can you post a full bug report using the issue template please?

**Comment by mmattel** [comment]
### Steps to reproduce
1. Install oC from git
2. Enable files_external

### Expected behaviour
No error

### Actual behaviour
oC Error Log: Fatal core Invalid OCS content returned for app files_external

### Server configuration
**Operating system**:
Ubuntu 14.04
**Web server:**
nginx 1.7.11
**Database:**
MySQL 5.5.41
**PHP version:**
PPH 5.5.9, php-apcu version: 4.0.6-1

**ownCloud version:** (see ownCloud admin page)
ownCloud 8.1 pre alpha (git) (updated today from git)

**Updated from an older ownCloud or fresh install:**
no, fresh install from some days ago

**List of activated apps:**
Standard (Files, Activity, Gallery) + Files_External

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'xxxx',
  'passwordsalt' => 'xxxxx',
  'secret' => 'xxxx',
  'trusted_domains' =>
  array (
    0 => 'yyyy',
  ),
  'datadirectory' => '/var/www/xxxx/data',
  'overwrite.cli.url' => 'yyyy',
  'dbtype' => 'mysql',
  'version' => '8.1.0.1',
  'dbname' => 'xxxxx',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxxxx',
  'dbpassword' => 'xxxxx',
  'logtimezone' => 'Europe/Vienna',
  'installed' => true,
  'loglevel' => 0,
  'memcache.local' => '\OC\Memcache\APCu',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
SMB
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
W7/Opera
**Operating system:**
Ubuntu 14.04
### Logs
#### ownCloud log (data/owncloud.log)
```
Fatal	core	Invalid OCS content returned for app files_external
```

**Comment by DeepDiver1975** [comment]
The app installer is reaching out to the appstore to check for updates - as there are non the content is empty. This error message should not be fatal

**Comment by mmattel** [comment]
@DeepDiver1975 
This is true and should be imho Info.
In addition, the message content it self is confusing, and does not fit to your explanation why it is triggered.

**Comment by DeepDiver1975** [comment]
> In addition, the message content it self is confusing, and does not fit to your explanation why it is triggered.

for sure

**Comment by mmattel** [comment]
Just a reminder where to find the corresponding code segment:
https://github.com/owncloud/core/blob/a8b756154a533a2618f03c54aca56af957da12ae/lib/private/ocsclient.php#L207

**Comment by PVince81** [comment]
Solved by https://github.com/owncloud/core/pull/15411
