### ISSUE TITLE
SQL Error. Update 7.0.4 to 8.0.2

### ISSUE THREAD

**Issue by highcurrent** [owncloud/core#15374]
Hi,
when I try to update my OC I get following message:

An exception occurred while executing ' UPDATE `oc_filecache` SET `mimetype` = ( SELECT `id` FROM `oc_mimetypes` WHERE `mimetype` = ? ) WHERE `name` LIKE ? ' with params ["application\/vnd.openxmlformats-officedocument.wordprocessingml.document", "%.docx"]: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction

Can you help me?

**Comment by LukasReschke** [comment]
Thanks a lot for reporting issues back to us!

We need some more information to properly support you with your issue!

Can I ask you to follow our guidelines for submitting bugs as described here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

Furthermore when you are using MySQL please run `SHOW ENGINE INNODB STATUS` and report the returned values.

**Comment by highcurrent** [comment]
So I hope you can help me better:

### Steps to reproduce
1. Now I can't. I get a blank page
2.
3.

### Expected behaviour
Back to login page

### Actual behaviour
If I call my website it appers a blank white page

### Server configuration
**Operating system**: It is a Webspace. (Linux dd35336 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64)

**Web server:** Apache 2

**Database:** MySQL 5.6.23

**PHP version:** 5.4.38

**ownCloud version:** between 7.0.4 and 8.0.2

**Updated from an older ownCloud or fresh install:** update from 7.0.4

**List of activated apps:** All standard apps

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'oc3c188c0989',
  'passwordsalt' => '******',
  'trusted_domains' => 
  array (
    0 => 'space.*****.de',
  ),
  'datadirectory' => '/www/htdocs/w00df2a9/space/data',
  'dbtype' => 'mysql',
  'version' => '8.0.2.0',
  'dbname' => 'd01',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'd01',
  'dbpassword' => '******',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'secret' => '********',
);


**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no



### Client configuration
**Browser:**Firefox

**Operating system:**Linux Ubuntu

### Logs
#### Web server error log

it's a webspace, so no log is aviable

#### ownCloud log (data/owncloud.log)

it is very very long :-)

the most often message is following:

{"reqId":"428a73289b33d992374f90882f7c4554","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"Class OCA\\Contacts\\Share\\Addressbook contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCP\\Share_Backend::isShareTypeAllowed) at \/www\/htdocs\/w00df2a9\/space\/apps\/contacts\/lib\/share\/addressbook.php#130","level":3,"time":"2015-04-02T11:46:39+00:00"}

that message is about 5000000000 times.

The last one is:

{"reqId":"da85601e6baa0f7130034058d1e729c2","remoteAddr":"129.187.54.2","app":"PHP","message":"Class 'OC_Connector_Sabre_Principal' not found at \/www\/htdocs\/w00df2a9\/space\/apps\/calendar\/appinfo\/remote.php#23","level":3,"time":"2015-04-02T11:48:42+00:00"}

and where the SQL Error is:

{"app":"hook","message":"error while running hook (OCA\\Files_Trashbin\\Hooks::remove_hook): An exception occurred while executing 'INSERT INTO `oc_filecache` (`mimepart`, `mimetype`, `mtime`, `size`, `etag`, `storage_mtime`, `permissions`, `parent`, `path_hash`, `path`, `name`, `storage`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)':\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-988e6a0a3fbb7b6db15a1109cef37a13' for key 'fs_storage_path_hash'","level":3,"time":"2015-04-02T11:07:00+00:00"}


I can't run "SHOW ENGINE INNODB STATUS" because I have not the privileges for this operation (said my server)

**Comment by PVince81** [comment]
Did you have any more luck with 8.0.5 or 8.1 ?

**Comment by PVince81** [comment]
The "database is locked" issues have been mitigated in recent versions, please try again with 8.0.6 or 8.1.1.

Feel free to reopen if you're still having trouble updating.
