### ISSUE TITLE
trashbin size ignores quota rules

### ISSUE THREAD

**Issue by kaplandani** [owncloud/core#15371]
server version is 7.0.3 on CENTOS 7.0
php version is 5.6

the user's quota is 10G. most his files are access with a share from another user. 
the user's files_trashbin  folder is 732 GB !!!

I am not sure what happened there....

**Comment by LukasReschke** [comment]
@schiesbn Any idea?

**Comment by PVince81** [comment]
@kaplandani can you run the following: `select * from oc_filecache where (path like 'files' or path like 'files_trashbin')` and find the entries for the user in question ? (you can map it to oc_storages with storage=numeric_id). Have a look at the "size" column.

To work properly, the "files" entry and "files_trashbin" entries must both have the correct size in the database. If they don't, you can try running `./occ files:scan --all` as web server user to try and fix them

**Comment by PVince81** [comment]
@kaplandani any update ? Are you still seeing this happening with 8.1.3 ?

**Comment by PVince81** [comment]
more possible clues here in this duplicate https://github.com/owncloud/core/issues/16920

**Comment by PVince81** [comment]
This should work properly now in 8.1 or 8.2 with the retention feature.

If you still see this issue in 8.1.5 or 8.2.2, feel free to reopen.
