### ISSUE TITLE
Storage::file_put_content return wrong in PHPDoc - implementations have to be checked as well

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#15382]
see https://scrutinizer-ci.com/g/owncloud/core/inspections/6cf4248d-d123-438d-a243-6521856b1e86/issues/files/lib/private/files/storage/wrapper/encryption.php?status=new&orderField=issueCount&order=desc#inspectioncomment-699654580

@icewind1991

**Comment by PVince81** [comment]
I see that file_put_contents returns an int instead of bool: https://github.com/owncloud/core/blob/master/lib/private/files/storage/wrapper/encryption.php#L202

Also I'm not sure if it's correct to return false if "fwrite" returned 0 because it can still be considered a success.

**Comment by PVince81** [comment]
Closing as this is old. If scrutinizer is still not happy, let's do a "fix all scrutinizer errors" pass one of these days...
