### ISSUE TITLE
Move mimetypes.list.php to a text file in /config

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#15384]
It can take between 1 to 6+ months for a user to have access to a new media type, simply because `core` has to be hacked for that.

I propose we move the list to a simple text or php file in the config folder so that users can upgrade the list as they see fit.
The cron job can keep the cache updated and simple media type migrations could be performed on the fly.

Is there some big invisible hurdle to doing it this way?

**Comment by Xenopathic** [comment]
:+1: Mimetype/file extension associations are data, not code, so shouldn't be stored in the code.

**Comment by flamenco108** [comment]
I appologize for interruption, but I have fount closed issue, where were request to recognize filetypes by mime, not extension. Here I see the reasonable request to make easier to configure filetypes. 

This is also my pain: I would like to edit **txt2tags** files by ownCloud text editor, but textfile with **.t2t** extension is not recognized as a text file (I'm not talking about code coloring).

How to change the ownCloud to make it possible to edit text files with other extensions?

**Comment by Xenopathic** [comment]
@flamenco108 At the moment, your only option is to edit mimetypes.list.php with your desired changes, then keep that file up to date every time you update your ownCloud installation. If/when the feature here gets implemented, you will have a file in /config to edit instead, which should preserve your changes across updates.

**Comment by DeepDiver1975** [comment]
We might want to use this as resource - http://www.webmaster-toolkit.com/mime-types.shtml

**Comment by oparoz** [comment]
I've had a look and it's missing quite a few ones we're already using, but I guess it could be merged with what we have.

**Comment by rullzer** [comment]
Let me have a look at this after the big mimetypealias.json merge :)

**Comment by rullzer** [comment]
See #17481

**Comment by rullzer** [comment]
Fixed in #17481
