### ISSUE TITLE
Update from 8.0.1 to 8.0.2 crashed (missing files?)

### ISSUE THREAD

**Issue by felikz3** [owncloud/core#15388]
I've updated my owncloud 8 to the latest version today with the online update tool. At some point the updater page said that I should manually reload the page in my browser.
I did that and I got a HTTP Error Code 500 (Internal Server Error). Waited for a couple of minutes and reloaded the page multiple times, no change, always 500. Therefore, after 10 minutes I killed the php process. Then, the Owncloud page was up again, but it showed me that an update was in progress (so owncloud was in the maintenance mode).
I already got some help from the forum (https://forum.owncloud.org/viewtopic.php?f=31&t=27522&p=84022#p84022), but they referred me to here.

The latest status is, that after the above I manually disabled maintenance in config.php and restarted the upgrade with ```occ upgrade```
The output after 2.5h was:
```
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
```

But after these 2.5h nothing happened (at some point the occ upgrade process just returned without any further output and there was also no CPU usage anymore).
Last entry in owncloud.log
```
{"reqId":"6c5805b4fd7b890a05b8a958c7b48f24","remoteAddr":"","app":"PHP","message":"opendir(\/var\/www\/virtual\/NAME\/html\/owncloud\/data\/NAME\/files_trashbin\/share-keys\/values-zh.d1425843087): failed to open dir: No such file or directory at \/var\/www\/virtual\/NAME\/html\/owncloud\/lib\/private\/files\/storage\/local.php#78","level":3,"time":"2015-04-02T21:20:28+00:00"}
```

Last entry in error.log (from Apache)
```
[Thu Apr 02 18:52:23 2015] [warn] [client 204.123.28.70] mod_fcgid: stderr: PHP Fatal error:  Class 'Patchwork\\Utf8\\Bootup' not found in /var/www/virtual/NAME/html/owncloud/lib/private/util.php on line 1060
```

Encryption app is enabled. Looks like the size of the data folder has increased significantly, I guess the size before was around 3 GB and now it is 7.36 GB.

**Comment by felikz3** [comment]
Update: I ran the occ upgrade once more and after a few hours I got this:
```
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 4194304 bytes) in /var/www/virtual/felkotik/html/owncloud/lib/private/files/filesystem.php on line 779
```

What can I do about it?

**Comment by LukasReschke** [comment]
Please upgrade following the documentation which says you have to remove all applications before and then reinstall it. You likely have apps installed that are not compatible yet or ab ilder version.

For example the contacts and calendar app should be installed from the AppStore now.

**Comment by RealRancor** [comment]
@LukasReschke 
Seems the OP was already at OC8 when reading the topic title so the apps shouldn't be the problem here?

**Comment by PVince81** [comment]
OP used the updater app. Not sure if the updater app had a glitch and didn't properly replace all the source files.

Please note that "./occ upgrade" only updates the database, not the OC source code.

I'd recommend to manually replace the source code now instead of relying on the updater app, see https://doc.owncloud.org/server/8.0/admin_manual/maintenance/upgrade.html#manual-upgrade-procedure

Please try that with 8.0.6 or 8.1.1.

If you're still having trouble, feel free to reopen.
