### ISSUE TITLE
Exlude particular directories from beeing viewed, accessed and scanned 

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#15385]
I came across this when I did some debugging on SMB, but this is not limited to.

My external storage is capable of snapshots. These snapshots are present in each directory and have as entrypoint a particular directory name. I can enable the view on this directory from the storage point of view, then when you browse with your desktop and enter the snapshot directory name, you can walk into. If I disable this view, I can enter the snapshot directory name, but it behaves like a non existing folder.

As this is a good thing to recover files without tape access, enabeling the view has its benefits.

The bad thing with the current behaviour of owncloud is, if you have a TB volume shared, snapshot directory access enabled and let´s say 10 snapshots you rotate, you scan 11TB (1 + 10)...
And each rescan does then the same
And each mount point does the same.

The idea is now, that there is a possibility in owncloud to exlude the view, access and scan of these directories. Maybe a config.php parameter array with names to exclude.

In my case, the folder names to exclude would be ``~snapshot`` and ``.snapshot``
(The first character is access protocol dependent, ~ = SMB, . = NFS)

Please consider, that these kind of storages are more likely to be found in enterprise environments, but then snapshots are liked and heavily used ...

**Comment by Aesculapius** [comment]
Yes, being able to exclude folders from being scanned also fits my usecase, where incremental backups using hardlinks would result in terabytes of storage to be scanned. Also see https://github.com/owncloud/core/issues/7234

**Comment by DeepDiver1975** [comment]
Please have a look at config.sample.php - there is a option to blacklist files/folders.

Please give it a try if this works out for you.

**Comment by mmattel** [comment]
Good hint.

The config.php parameter: ``blacklisted_files`` is for files only, but not for directories
https://github.com/owncloud/core/blob/master/config/config.sample.php
https://github.com/owncloud/core/blob/4082436419d5325157553131b93343d5b7439b90/lib/private/files/filesystem.php#L569

But there is another function just below: 
https://github.com/owncloud/core/blob/4082436419d5325157553131b93343d5b7439b90/lib/private/files/filesystem.php#L583

	/**
	 * check if the directory should be ignored when scanning
	 * NOTE: the special directories . and .. would cause never ending recursion
	 * @param String $dir
	 * @return boolean
	 */
	static public function isIgnoredDir($dir) {
		if ($dir === '.' || $dir === '..') {
			return true;
		}
		return false;
	}

This would do what we expect, at least from the scanning point of view, maybe also from viewing. Just needs to be expanded to a config.php parameter maybe ``blacklisted_directories``

**Comment by PVince81** [comment]
@mmattel since your PR was merged I guess this can be closed ? Or is something missing ?

**Comment by mmattel** [comment]
Closing because of merging #19235
