### ISSUE TITLE
Unable to connect to ftps server using External Storage App

### ISSUE THREAD

**Issue by gig13** [owncloud/core#15392]
**Expected Behavior**
Setup the External Storage to access an ftps server with appropriate credentials and connect without issue.

**Actual Behavior**
The connection fails when attempting to connect. A connection can be made through FileZilla tool without issue using the correct port and credentials.

**Server Configuration**
OC8.0.2
CentOS 6.6
Apache 2.4 server
php 5.5 (details on s3 link)

Log file also on s3 link
https://s3.owncloud.com/owncloud/index.php/apps/files?dir=%2FShared%2Fowncloud%2Fsupport%2Fgithub-issues%2Fcore%2F15392

**Comment by gig13** [comment]
I also failed the connection from an Ubuntu server with OC802 and php 5.5.9.

**Comment by Xenopathic** [comment]
@gig13 Could you post the log file here for the benefit of those who don't have access to S3 (like myself :smile:)?

**Comment by gig13** [comment]
@Xenopathic 
I had to scrub some info, here is a snippet.

```
{"reqId":"182b9bc0e25f4fead2b4c6e2a2037cd9","remoteAddr":"1.2.3.4","app":"webdav","message":"Exception: {\"Message\":\"File with name avast premium full.exe could not be located\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/local\\\/apache\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/tagsplugin.php(197): OC\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('avast premium f...')\\n#1 [internal function]: OC\\\\Connector\\\\Sabre\\\\TagsPlugin->beforeGetPropertiesForPath('avast premium f...', Array, 0)\\n#2 \\\/usr\\\/local\\\/apache\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(433): call_user_func_array(Array, Array)\\n#3 \\\/usr\\\/local\\\/apache\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/server.php(152): Sabre\\\\DAV\\\\Server->broadcastEvent('beforeGetProper...', Array)\\n#4 \\\/usr\\\/local\\\/apache\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/server.php(104): OC_Connector_Sabre_Server->getPropertiesForPath('avast premium f...', Array, 0)\\n#5 [internal function]: OC_Connector_Sabre_Server->httpPropfind('avast premium f...')\\n#6 \\\/usr\\\/local\\\/apache\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(474): call_user_func(Array, 'avast premium f...')\\n#7 \\\/usr\\\/local\\\/apache\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('PROPFIND', 'avast premium f...')\\n#8 \\\/usr\\\/local\\\/apache\\\/htdocs\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(61): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/usr\\\/local\\\/apache\\\/htdocs\\\/owncloud\\\/remote.php(54): require_once('\\\/usr\\\/local\\\/apac...')\\n#10 {main}\",\"File\":\"\\\/usr\\\/local\\\/apache\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/objecttree.php\",\"Line\":100}","level":0,"time":"2015-04-03T17:54:24+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/avast%20premium%20full.exe"}
{"reqId":"5ece3c6e6224e5accde2515c7b8da6d1","remoteAddr":"1.2.3.4","app":"webdav","message":"Exception: {\"Message\":\"File with name setup.zip.exe could not be located\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/local\\\/apache\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/tagsplugin.php(197): OC\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('setup.zip.exe')\\n#1 [internal function]: OC\\\\Connector\\\\Sabre\\\\TagsPlugin->beforeGetPropertiesForPath('setup.zip.exe', Array, 0)\\n#2 \\\/usr\\\/local\\\/apache\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(433): call_user_func_array(Array, Array)\\n#3 \\\/usr\\\/local\\\/apache\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/server.php(152): Sabre\\\\DAV\\\\Server->broadcastEvent('beforeGetProper...', Array)\\n#4 \\\/usr\\\/local\\\/apache\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/server.php(104): OC_Connector_Sabre_Server->getPropertiesForPath('setup.zip.exe', Array, 0)\\n#5 [internal function]: OC_Connector_Sabre_Server->httpPropfind('setup.zip.exe')\\n#6 \\\/usr\\\/local\\\/apache\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(474): call_user_func(Array, 'setup.zip.exe')\\n#7 \\\/usr\\\/local\\\/apache\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('PROPFIND', 'setup.zip.exe')\\n#8 \\\/usr\\\/local\\\/apache\\\/htdocs\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(61): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/usr\\\/local\\\/apache\\\/htdocs\\\/owncloud\\\/remote.php(54): require_once('\\\/usr\\\/local\\\/apac...')\\n#10 {main}\",\"File\":\"\\\/usr\\\/local\\\/apache\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/objecttree.php\",\"Line\":100}","level":0,"time":"2015-04-03T17:54:25+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/setup.zip.exe"}
{"reqId":"4aadf0f8c764c38a1a5d7ca95954a33f","remoteAddr":"1.2.3.4","app":"webdav","message":"Exception: {\"Message\":\"File with name setup.zip.exe could not be located\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/local\\\/apache\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/tagsplugin.php(197): OC\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('setup.zip.exe')\\n#1 [internal function]: OC\\\\Connector\\\\Sabre\\\\TagsPlugin->beforeGetPropertiesForPath('setup.zip.exe', Array, 0)\\n#2 \\\/usr\\\/local\\\/apache\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(433): call_user_func_array(Array, Array)\\n#3 \\\/usr\\\/local\\\/apache\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/server.php(152): Sabre\\\\DAV\\\\Server->broadcastEvent('beforeGetProper...', Array)\\n#4 \\\/usr\\\/local\\\/apache\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/server.php(104): OC_Connector_Sabre_Server->getPropertiesForPath('setup.zip.exe', Array, 0)\\n#5 [internal function]: OC_Connector_Sabre_Server->httpPropfind('setup.zip.exe')\\n#6 \\\/usr\\\/local\\\/apache\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(474): call_user_func(Array, 'setup.zip.exe')\\n#7 \\\/usr\\\/local\\\/apache\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('PROPFIND', 'setup.zip.exe')\\n#8 \\\/usr\\\/local\\\/apache\\\/htdocs\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(61): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/usr\\\/local\\\/apache\\\/htdocs\\\/owncloud\\\/remote.php(54): require_once('\\\/usr\\\/local\\\/apac...')\\n#10 {main}\",\"File\":\"\\\/usr\\\/local\\\/apache\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/objecttree.php\",\"Line\":100}","level":0,"time":"2015-04-03T17:54:25+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/setup.zip.exe"}
{"reqId":"2a337d5da04325617802733a57a8646a","remoteAddr":"111.111.111.111","app":"PHP","message":"stat(): stat failed for ftps:\/\/xxx:xxx@sslblah:990\/FHVUpload\/ at \/usr\/local\/apache\/htdocs\/owncloud\/apps\/files_external\/lib\/streamwrapper.php#104","level":3,"time":"2015-04-03T17:54:48+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files_external\/ajax\/addMountPoint.php"}


```

**Comment by Xenopathic** [comment]
Does your FTP server use an 'official' SSL certificate or a self-signed one?

**Comment by RealRancor** [comment]
SElinux enabled? https://github.com/owncloud/documentation/pull/969 , https://github.com/owncloud/core/issues/15040#issuecomment-83752716

**Comment by gig13** [comment]
@RealRancor 
Disabled

**Comment by gig13** [comment]
@Xenopathic 
self-signed

**Comment by gig13** [comment]
When using FileZilla, the first time I connect, I am prompted for the certificate from the server. I accept, and then do not have it prompted again when using FileZilla.

**Comment by RealRancor** [comment]
Ah, then try to import the self-signed cert as described here:

https://doc.owncloud.org/server/8.0/admin_manual/configuration_files/external_storage_configuration_gui.html#using-self-signed-certificates

**Comment by gig13** [comment]
@RealRancor @schiesbn 
How do I obtain the certificate for importing into the ownCloud personal page? When I used Firefox to connect, it redirected to WinSCP and I get the pop up to store the certificate, but i can't find it on my local system or in the Windows certmgr.

The sftp site I am trying to connect to is setup by another vendor, so do I need to ask them for something explicitly?

**Comment by gig13** [comment]
The owncloud log has timeout messages and stat failed for ftps

```
{"reqId":"be681fe7354f5b5e285ed1fced490ec7","remoteAddr":"123.123.123.123","app":"PHP","message":"stat(): connect() failed: Connection timed out at \/var\/www\/html\/oc802\/apps\/files_external\/lib\/streamwrapper.php#104","level":3,"time":"2015-04-09T17:44:22+00:00","method":"POST","url":"\/oc802\/index.php\/apps\/files_external\/ajax\/addMountPoint.php"}
{"reqId":"be681fe7354f5b5e285ed1fced490ec7","remoteAddr":"123.123.123.123","app":"PHP","message":"stat(): stat failed for ftps:\/\/xxx:xxx@serveraddress\/ at \/var\/www\/html\/oc802\/apps\/files_external\/lib\/streamwrapper.php#104","level":3,"time":"2015-04-09T17:44:22+00:00","method":"POST","url":"\/oc802\/index.php\/apps\/files_external\/ajax\/addMountPoint.php"}
{"reqId":"e6339afa7dd8909ac49915ba6917be68","remoteAddr":"123.123.123.123","app":"PHP","message":"stat(): connect() failed: Connection timed out at \/var\/www\/html\/oc802\/apps\/files_external\/lib\/streamwrapper.php#104","level":3,"time":"2015-04-09T17:45:23+00:00","method":"POST","url":"\/oc802\/index.php\/apps\/files_external\/ajax\/addMountPoint.php"}
{"reqId":"e6339afa7dd8909ac49915ba6917be68","remoteAddr":"123.123.123.123","app":"PHP","message":"stat(): stat failed for ftps:\/\/xxx:xxx@serveraddress\/ at \/var\/www\/html\/oc802\/apps\/files_external\/lib\/streamwrapper.php#104","level":3,"time":"2015-04-09T17:45:23+00:00","method":"POST","url":"\/oc802\/index.php\/apps\/files_external\/ajax\/addMountPoint.php"}
{"reqId":"4b0b73f0c72e61ccba595980cc8a80e9","remoteAddr":"123.123.123.123","app":"PHP","message":"stat(): connect() failed: Connection timed out at \/var\/www\/html\/oc802\/apps\/files_external\/lib\/streamwrapper.php#104","level":3,"time":"2015-04-09T17:48:11+00:00","method":"POST","url":"\/oc802\/index.php\/apps\/files_external\/ajax\/addMountPoint.php"}
{"reqId":"4b0b73f0c72e61ccba595980cc8a80e9","remoteAddr":"123.123.123.123","app":"PHP","message":"stat(): stat failed for ftps:\/\/xxx:xxx@serveraddress\/ at \/var\/www\/html\/oc802\/apps\/files_external\/lib\/streamwrapper.php#104","level":3,"time":"2015-04-09T17:48:11+00:00","method":"POST","url":"\/oc802\/index.php\/apps\/files_external\/ajax\/addMountPoint.php"}
{"reqId":"631231c8ef97f460e7293aca96ccece6","remoteAddr":"123.123.123.123","app":"PHP","message":"stat(): stat failed for ftps:\/\/xxx:xxx@serveraddress:990\/ at \/var\/www\/html\/oc802\/apps\/files_external\/lib\/streamwrapper.php#104","level":3,"time":"2015-04-09T17:49:11+00:00","method":"POST","url":"\/oc802\/index.php\/apps\/files_external\/ajax\/addMountPoint.php"}
{"reqId":"0bdf26e427f6cf62c188d19da7f8fe27","remoteAddr":"123.123.123.123","app":"PHP","message":"stat(): stat failed for ftps:\/\/xxx:xxx@serveraddress:990\/ at \/var\/www\/html\/oc802\/apps\/files_external\/lib\/streamwrapper.php#104","level":3,"time":"2015-04-09T17:51:16+00:00","method":"POST","url":"\/oc802\/index.php\/apps\/files_external\/ajax\/addMountPoint.php"}
```

**Comment by gig13** [comment]
The apache access.log doesn't have much information.

```
123.123.123.123 - - [09/Apr/2015:13:42:27 -0400] "GET /oc802/core/js/setupchecks.js?v=b8a034cb93272ce15995bd3d8baa45cc HTTP/1.1" 200 1663 "https://172.18.5.106/oc802/index.php/settings/admin" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
123.123.123.123 - - [09/Apr/2015:13:42:27 -0400] "GET /oc802/core/js/multiselect.js?v=b8a034cb93272ce15995bd3d8baa45cc HTTP/1.1" 200 3604 "https://172.18.5.106/oc802/index.php/settings/admin" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
123.123.123.123 - - [09/Apr/2015:13:42:27 -0400] "GET /oc802/index.php/core/js/oc.js?v=b8a034cb93272ce15995bd3d8baa45cc HTTP/1.1" 200 3114 "https://172.18.5.106/oc802/index.php/settings/admin" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
123.123.123.123 - - [09/Apr/2015:13:42:28 -0400] "GET /oc802/apps/firewall/vendor/font-awesome/fonts/fontawesome-webfont.eot? HTTP/1.1" 304 261 "https://172.18.5.106/oc802/index.php/settings/admin" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
123.123.123.123 - - [09/Apr/2015:13:42:28 -0400] "GET /oc802/index.php/avatar/foo/128?requesttoken=jn.JeJYf5F9ZxFKpOsbHQI/PzbU2O7 HTTP/1.1" 200 938 "https://172.18.5.106/oc802/index.php/settings/admin" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
123.123.123.123 - - [09/Apr/2015:13:42:28 -0400] "GET /oc802/index.php/apps/firewall/ajax/getUIData HTTP/1.1" 200 858 "https://172.18.5.106/oc802/index.php/settings/admin" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
123.123.123.123 - - [09/Apr/2015:13:42:28 -0400] "GET /oc802/cron.php HTTP/1.1" 200 906 "https://172.18.5.106/oc802/index.php/settings/admin" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
123.123.123.123 - - [09/Apr/2015:13:42:28 -0400] "PROPFIND /oc802/remote.php/webdav HTTP/1.1" 207 5162 "https://172.18.5.106/oc802/index.php/settings/admin" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
123.123.123.123 - - [09/Apr/2015:13:42:28 -0400] "GET /oc802/index.php/settings/ajax/checksetup HTTP/1.1" 200 970 "https://172.18.5.106/oc802/index.php/settings/admin" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
::1 - - [09/Apr/2015:13:42:37 -0400] "OPTIONS * HTTP/1.0" 200 125 "-" "Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.7 OpenSSL/1.0.1f (internal dummy connection)"
123.123.123.123 - - [09/Apr/2015:13:43:21 -0400] "GET /oc802/core/img/loading-small.gif HTTP/1.1" 304 454 "https://172.18.5.106/oc802/index.php/settings/admin" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
123.123.123.123 - - [09/Apr/2015:13:43:21 -0400] "POST /oc802/index.php/apps/files_external/ajax/addMountPoint.php HTTP/1.1" 200 1115 "https://172.18.5.106/oc802/index.php/settings/admin" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
123.123.123.123 - - [09/Apr/2015:13:43:23 -0400] "POST /oc802/index.php/apps/files_external/ajax/addMountPoint.php HTTP/1.1" 200 922 "https://172.18.5.106/oc802/index.php/settings/admin" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
123.123.123.123 - - [09/Apr/2015:13:44:02 -0400] "GET /oc802/index.php/settings/admin/log/entries?offset=3&count=10 HTTP/1.1" 200 1403 "https://172.18.5.106/oc802/index.php/settings/admin" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
123.123.123.123 - - [09/Apr/2015:13:47:11 -0400] "POST /oc802/index.php/apps/files_external/ajax/addMountPoint.php HTTP/1.1" 200 2205 "https://172.18.5.106/oc802/index.php/settings/admin" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
123.123.123.123 - - [09/Apr/2015:13:47:18 -0400] "POST /oc802/index.php/apps/files_external/ajax/addMountPoint.php HTTP/1.1" 200 1115 "https://172.18.5.106/oc802/index.php/settings/admin" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
123.123.123.123 - - [09/Apr/2015:13:50:14 -0400] "POST /oc802/index.php/apps/files_external/ajax/addMountPoint.php HTTP/1.1" 200 1115 "https://172.18.5.106/oc802/index.php/settings/admin" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
123.123.123.123 - - [09/Apr/2015:13:54:28 -0400] "POST /oc802/index.php/heartbeat HTTP/1.1" 200 2072 "https://172.18.5.106/oc802/index.php/settings/admin" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"

```

**Comment by gig13** [comment]
@RealRancor @schiesbn @bboule 
I was able to connect to the ftp server from the ownCloud server via a curl command and transfer a file without issue.

The command I used is as follows:
```
curl -3 -v --cacert /root/rootCA.pem --disable-epsv --ftp-skip-pasv-ip --ftp-ssl --insecure -T "/root/TESTFILE.txt" ftps://user:password@ftpserver:990
```

What are the next steps? The ftps connection outside ownCloud works fine, now how do we get the External Storage connected? Is it possibly related to the bundled certificate?

**Comment by butonic** [comment]
looking at the code I dont see a place where we load the certificate for use with tho stat call / ftps::/ streamwrapper. I don't think you can use self signed certificates that have been uploaded by a user.

Might be possible to import them in the system. @icewind1991 @PVince81 can you confirm?

**Comment by butonic** [comment]
also see: http://stackoverflow.com/questions/21854012/is-it-possible-to-work-with-ftps-under-php-using-stream-context - possible but we are not doing it

**Comment by LukasReschke** [comment]
I explained this already twice last week in the internal IRC…

**Comment by butonic** [comment]
I wasn't there and still had to investigate today, so what exactly did you explain? how to import certificates? That's not my problem, and I am well capable of using openssl to download a certificate ;) From my understanding:
1. importing the certificate in oc is useless because the streamwrappers won't be using it.
2. you would have to add the certificate chain to the trusted system certificates, which is not an option for shared hosters, such as GoDaddy. etc ...

Now what part of your explanation that I missed can add to this?

**Comment by LukasReschke** [comment]
That was it pretty much and I was more annoyed that this gets asked over and over again. Not that you answered it @butonic :-) – But if I reply to such things 3 times in 2 weeks it gets somewhat *meh* and doesn't motivate me to respond to anything in IRC anymore.

I doubt that it is a SSL issue, PHP before 5.6 does not really verify SSL certificates in a lot of places. I suspect something like the FTP passive mode to play a role here. – It would help to get an exact testsystem using the same FTP settings in the lab running otherwise this is major guessing, and also the FTP wrapper we use is not really meant to be verbose or adjustable :-(

**Comment by butonic** [comment]
We just use the stock ftps:// streamwrapper and don't set up the context anywhere:
```php
<?php
$ctx = stream_context_create(['ssl' => [
    'verify_peer' => true,
    'cafile' => 'd:/sandbox/mycerts.pem',
    'CN_match' => 'ftp-12345678.mywebhoster.com'
]]);
```

so ... actually this seems possible, but we need to set up the context everywhere ... basically that means extending https://github.com/owncloud/core/blob/master/apps/files_external/lib/ftp.php with all methods from https://github.com/owncloud/core/blob/a8b756154a533a2618f03c54aca56af957da12ae/apps/files_external/lib/streamwrapper.php and set up the context prior to doing eg. a stat call ...

**Comment by LukasReschke** [comment]
Please notice that this will lead to usability problems as well. Even if this is a SSL problem we do not have a system-wide certificate store and thus while it might work for a single user that sets it up a shared mountpoint will most likely fail: https://github.com/owncloud/core/issues/15518

**Comment by craigpg** [comment]
@butonic, assigning this to you per your conversation with @bboule.

**Comment by butonic** [comment]
@icewind1991 I saw https://github.com/owncloud/core/pull/14551 where you replace the current ftp(s) implementation with code from flyspace. Do they have a straight forward way of supplying self signed certificates for FTPS (not SFTP)? I only saw ssl related parameters in their SFTPAdapter. I'd like to push forward with flyspace I you can point me to a place where to start. Currently, it seems I have to extend the FTPAdapter.

**Comment by butonic** [comment]
Trying to find a good solution it seems we cannot just set up the stream context with our own certificates in all cases. [stat()](http://php.net/manual/de/function.stat.php) for example does not have a context parameter. We would have to implement our own ftps stream wrapper to support self signed certificates. The flysystem ftps implementation introduced with #14551 uses [ftp_ssl_connect()](http://php.net/manual/de/function.ftp-ssl-connect.php) instead of the stock [ftps:// wrapper](http://php.net/manual/de/wrappers.ftp.php). My google fu did not reveal how to allow self signed certificates with that.

In our DAV implementation we use cURL which also supports FTPS. So, to me it seems taking our DAV class as an example we should be able to derive a FTP(S) storage that internally uses curl to allow self signed certificates.

If anyone knows how to make ftp_ssl_connect accept self signed certificates (without tampering with the underlying os) I will gladly reinvest in that direction. AFAICT it is not possible.

Sidenote: I was under the wrong impression that using cURL would force us to use temporary files, but as it turns out we can [combine CURLOPT_FILE with a custom php stream wrapper](http://stackoverflow.com/a/1342760) which would allow us to stream content directly to the browser.

**Comment by butonic** [comment]
@MorrisJobke it seems https://github.com/owncloud/core/pull/14551 is the way to go, now that the full certificate chain is in place. can you have a look at that pr?

**Comment by DeepDiver1975** [comment]
Hold your horses.  #14551 is scheduled for 8.2 - we are deep in 8.1 development. 

Please no distraction of the server team devs. Thx

**Comment by craigpg** [comment]
At the moment, this is a deployment blocker.

@butonic, can you explain a bit further why we need to move to flysystem (#14551) now that we've cleared up the intermediate certificate issue?

@cmonteroluque, may need to accelerate #14551 if it's our only viable technical solution.

**Comment by butonic** [comment]
PHP has two ways of speaking to an ftp(s) server. The older, explicit function calls (used by flysystem) and the younger streamwrappers (currently used by oc). I cannot make the stat call successfully connect to their ftps server. Not even in a minimal code snippet. I can try with the explicit methods tomorrow, or we just get 14551 reviewed and test with that branch.

Streamwrappers won't work. If flysystem does not work either, using the curl bindings does (tested, similar code can be found in the dav external filesystem).

**Comment by craigpg** [comment]
It turns out that #14551 won't help us with this particular ftp server.  The server only works with _implicit_ FTPS, a deprecated protocol, that flysystem does not support.

owncloud/consulting#8

**Comment by butonic** [comment]
For reference: when the ftp server does not support MLST/MLSD (indicated by MLST in the FEAT response) we would have to parse the more or less human readable LIST response. See [FileZilla src](https://github.com/michaellukashov/Far-NetBox/blob/master/src/filezilla/FtpListResult.cpp#L43) for examples. One word: insane. A regex catching some but by far not all of them it [stackoverflow](http://stackoverflow.com/a/2176738).

**Comment by gig13** [comment]
@craigpg @butonic @bboule 
Any ETA on a solution?

**Comment by DeepDiver1975** [comment]
> One word: insane. A regex catching some but by far not all of them at stackoverflow.

Such crazy :hankey: will never be accepted as part of the regular project/product.
Any implementation like this is a total maintenance nightmare - engineering will never take over this.

**Comment by DeepDiver1975** [comment]
> @craigpg @butonic @bboule
> Any ETA on a solution?

Non from engineering

**Comment by DeepDiver1975** [comment]
This aint no task for 8.1

**Comment by craigpg** [comment]
@DeepDiver1975, I'm thinking we can close this.  Consulting is taking this on: owncloud/consulting#8.

**Comment by gig13** [comment]
Agreed, this can be closed out since it is being handled in the consulting repo.
