### ISSUE TITLE
Cleaning up `autocapitalize="off"` in files

### ISSUE THREAD

**Issue by Volker-E** [owncloud/core#15399]
`autocapitalize="off"` is [deprecated since iOS 5.0](https://developer.apple.com/library/safari/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/Attributes.html). 
Moreover it is inherited from the enclosing `form` tag, so the current `autocomplete="none"` should be set just once at the parent `form`

Currently in core it occurs 20 times in 6 files.

**Comment by DeepDiver1975** [comment]
@jancborchardt

**Comment by jancborchardt** [comment]
@Volker-E and it’s not used by Android anymore either? What is used nowadays to prevent the mobile keyboards autocapitalizing usernames?

**Comment by Volker-E** [comment]
That has always been just an iOS proprietary attribute and not being interpreted anywhere else. As stated above "`autocomplete="none" should be set just once at the parent form`". I can make a PR for this, I just wanted to make sure that my last changes on my branch get merged first. (Curr. have problems with two branches side-by-side).

**Comment by Xenopathic** [comment]
`autocomplete` =/= `autocapitalize`

**Comment by Volker-E** [comment]
@Xenopathic Sorry, just referring to the documentation and mistyped in my comment above, I meant `autocapitalize="none"`. That should go in the parent `form` element and it works for iOS >= 5.0

**Comment by Xenopathic** [comment]
@jancborchardt Fix or defer?

**Comment by jancborchardt** [comment]
@Volker-E what do you say? :)

**Comment by PVince81** [comment]
PRs welcome

**Comment by jnweiger** [comment]
##retested on a running instance of 10.6.0-rc1
`find /var/www/owncloud -type f | xargs grep -i autocapitalize`

```
./apps/customgroups/js/templates/list.handlebars.js:13
./apps/guests/templates/form.password.php:35,42
./apps/files_texteditor/js/vendor/ace/src-noconflict/ace.js:1931
./core/vendor/select2/select2.min.js:22
./core/vendor/select2/select2.js:2150
./core/vendor/select2/select2.js:2782
./updater/src/Resources/views/partials/login.php:22
```

**Comment by micbar** [comment]
@jnweiger try
`find /var/www/owncloud -type f | xargs grep -i autocapitalize=off`

`autocapitalize=off` was transformed into `autocapitalize=none`

should not find anything

**Comment by jnweiger** [comment]
I agree. Expected none. But found 7.

Fixed string `autocapitalize=off` fails to find spelling variants. We have `'off'`, `"off"`, `\"off\"`, `...", "off");` etc. 
Open eyes needed. :-)
