### ISSUE TITLE
Can't create or upload files

### ISSUE THREAD

**Issue by angico** [owncloud/core#15409]
Hi!

I've upgraded my server to version 8.0.2 and now realized I just can't upload or create files in my owncloud.

I've already changed access modes on the entire data directory tree so that the web server user has the right privileges on them, but the issue persists.

Moreover, owncloud client on my computer just stopped sync'ing, as it also can't create or upload files to the server.

Any hints on how to solve this?

Thank you very much!

**Comment by Xenopathic** [comment]
Could you please fill out the issue template (https://github.com/owncloud/core/blob/master/issue_template.md)? Thanks!

**Comment by angico** [comment]
Hey, I have just finished running `occ files:scan` on my server and it seems it solved the problem. The message about having no permissions to create or upload files has just disappeared, and I could delete some folders and create other one via web interface with no problem.

I'm sorry for bothering you with my silly questions.

Many thanks!
