### ISSUE TITLE
Missing delete permission on external share when parent is read-only

### ISSUE THREAD

**Issue by oliwel** [owncloud/core#15405]
### Steps to reproduce
1. Create /srv/private/ with read permissions for oc
2. Create folder /srv/private/shareme with write permissions for oc
3. Add /srv/private as external storage
4. Try to share "shareme" with another OC user
### Expected behaviour

Share options should include the "delete" permission, delete should apply to subfolders (deleting the parent share should not ne supported anyway) 
### Actual behaviour

Share options are "create" and "change" only
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
mysql

**PHP version:**
5.5.9-1ubuntu4.7

**ownCloud version:** 
8.0.2

**Updated from an older ownCloud or fresh install:**
Fresh install of 8.0.0, inline update

**List of activated apps:**

**The content of config/config.php:**
$CONFIG = array (
  'trusted_domains' => 
  array (
    0 => 'owncloud.xxxx.xxx',
  ),
  'datadirectory' => '/srv/owncloud',
  'overwrite.cli.url' => 'https://owncloud.xxxxx.xxx',
  'dbtype' => 'mysql',
  'version' => '8.0.2.0',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'forcessl' => true,
  'loglevel' => 0,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
local 

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by PVince81** [comment]
@rullzer @icewind1991 likely still an issue in OC 9

**Comment by PVince81** [comment]
Works for me in 9.1.3, delete permissions are there for the recipient and I could delete the subfolder.
