### ISSUE TITLE
Style and some images are lost in Internet Explorer 8

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#15413]
### Observed behaviour:
 
1.
![screen shot 2015-04-06 at 08 58 51](https://cloud.githubusercontent.com/assets/9048796/7001604/2c1982ce-dc3d-11e4-9522-3339b9fee8b8.png)

2.
![screen shot 2015-04-06 at 08 59 46](https://cloud.githubusercontent.com/assets/9048796/7001608/3d65d6b8-dc3d-11e4-9744-6bcea7c71e70.png)

3.
![screen shot 2015-04-06 at 09 00 32](https://cloud.githubusercontent.com/assets/9048796/7001615/55f649f6-dc3d-11e4-9e91-997a1aab490f.png)

### Expected behaviour:

1.
![screen shot 2015-04-06 at 08 58 39](https://cloud.githubusercontent.com/assets/9048796/7001605/30ea0828-dc3d-11e4-81a6-21de7cd9d030.png)

2.
![screen shot 2015-04-06 at 08 59 38](https://cloud.githubusercontent.com/assets/9048796/7001610/45f5b848-dc3d-11e4-8501-ed086f0fd96a.png)

3.
![screen shot 2015-04-06 at 09 00 20](https://cloud.githubusercontent.com/assets/9048796/7001616/5ff0b252-dc3d-11e4-8b1a-e6cb31693ba7.png)

Server configuration

Operating system:
Ubuntu 14.04

Web server:
Apache

Database:
MySQL

PHP version:
5.5.9

ownCloud version: (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.1","versionstring":"8.1 pre alpha","edition":"Enterprise"}

Updated from an older ownCloud or fresh install:
fresh

List of activated apps:
Files drop

The content of config/config.php:

Are you using external storage, if yes which one: local/smb/sftp/...
No

Are you using encryption:
Yes

Are you using an external user-backend, if yes which one: LDAP/ActiveDirectory/Webdav/...
No

### Client configuration

Browser:
Internet Explorer 8.0.7601

Operating System:
Windows Server 2008 R2 enterprise

**Comment by karlitschek** [comment]
The EE theme is not yet ported to 8.1
@jancborchardt

**Comment by karlitschek** [comment]
@jancborchardt Can you look into the EE theme soon please?

**Comment by jancborchardt** [comment]
Yes, I will!

**Comment by jancborchardt** [comment]
So I wanted to work on it last week already but enabling the theme did not work no matter what I tried (see https://github.com/owncloud/enterprise/pull/404), no one could help me either. I did:
* put the theme in the themes folder
* add the name of the theme in the config.php
* add `$OC_Edition='enterprise';` to version.php

How many more hoops do I need to jump through?

**Comment by SergioBertolinSG** [comment]
I am seeing the same ugly interface (internet explorer 8):

![screen shot 2015-05-20 at 17 41 30](https://cloud.githubusercontent.com/assets/9048796/7729934/aa4985b6-ff17-11e4-9f98-fb73b991eb2e.png)

**Comment by SergioBertolinSG** [comment]
Perhaps this PR solves it? https://github.com/owncloud/core/pull/16417

**Comment by MorrisJobke** [comment]
> Perhaps this PR solves it? #16417

No. This PR only fixed the login page.

**Comment by jancborchardt** [comment]
@SergioBertolinSG can you please right-click the dropdown, inspect the CSS in the browser and tell me what overwrites [this line](https://github.com/owncloud/enterprise/pull/639/files#diff-5b0e0c44dcd5ac6cf63506fea258b190R184)? (background:white)

**Comment by SergioBertolinSG** [comment]
I see this:
in background rgb(255,255,255); BORDER-TOP: rgb(204,204,204) 1px solid

**Comment by jancborchardt** [comment]
@SergioBertolinSG that’s what it’s supposed to say – I was asking what _overwrites_ that line. Can you take a screenshot of it with the inspector open? I don’t get why the background gets overridden.

**Comment by SergioBertolinSG** [comment]
This is what i see.

![screen shot 2015-05-22 at 12 05 53](https://cloud.githubusercontent.com/assets/9048796/7768402/fd00c080-007a-11e5-9c30-77b7ebd151f1.png)

**Comment by MorrisJobke** [comment]
Sorry ... I mixed this up. It's with master. and I think my change broke this. The install screen isn't scrollable.

@jancborchardt Can you please have a look at this? I'm totally fine with revert the change. Also the menu is black for me in IE8. Please also check for stable7 and stable8.

**Comment by DeepDiver1975** [comment]
> @jancborchardt Can you please have a look at this? I'm totally fine with revert the change. Also the menu is black for me in IE8. Please also check for stable7 and stable8.

@MorrisJobke Jan is off this week - any chance you take care of this? THX

**Comment by MorrisJobke** [comment]
Fixes are now all in PRs for all branches

master: #16703
stable8: #16705
stable7: #16707
