### ISSUE TITLE
Weird behaviour for logged in users in maintenance mode

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#15418]
### Steps to reproduce
1. Log in with an user
2. From the OC command line, set the maintenance mode (`sudo -u www-data ./occ maintenance:mode --on`)
3. Do some ajax stuff with the logged in user (for example, in the files view, try to get the contents of a folder)

### Expected behaviour
You are kicked to the maintenance screen

### Actual behaviour
You stay in the page getting errors. For example, if you try to get the contents of the folder, you stay in the current folder instead of changing it; if you want to know the file shared with you, you'll see that there are no files shared with you even though it's wrong.

This behaviour stays until the user loads another page, then the user is redirected to the maintenance screen

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.4

**ownCloud version:** 8.0.3RC1

**Updated from an older ownCloud or fresh install:** fresh install

**Browser:** firefox

**Comment by nickvergessen** [comment]
pretty much the same problem like when LDAP and others are not there.
We need a wrapper in the get(), post(), ... methods in js to catch these cases and redirect.

**Comment by nickvergessen** [comment]
cc @MorrisJobke can you find the ldap exception issue for a cross link quickly?

**Comment by MorrisJobke** [comment]
@nickvergessen #15332 or #15357 ?

**Comment by nickvergessen** [comment]
The later one is what I was looking for

**Comment by PVince81** [comment]
This one is tricky. Every app needs to fix their ajax calls to be able to react properly on 503 http codes and automatically show a proper error message or redirect accordingly.

**Comment by jvillafanez** [comment]
Checked also with single-user mode: same behaviour with normal users

**Comment by PVince81** [comment]
in recent versions, a notification will appear that an error occurred and the page will reload, which will redirect to the login page (or maintenance page followed up by login page when it comes back)
