### ISSUE TITLE
Drag and drop of a folder with special characters fails to upload.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#15415]
### Steps to reproduce
Having a OC server with an account and logged in using chrome browser:
1. Upload a folder with special characters in the name using drag and drop.

### Observed behaviour:
Unknown error message appears, nothing is uploaded.

### Expected behaviour:
1. Folder is uploaded and structure is kept.
(Just in chrome by the moment because other browsers doesn't have this functionality yet)

### Server configuration

Operating system:
Ubuntu 14.04

Web server:
Apache

Database:
MySQL

PHP version:
5.5.9

ownCloud version: (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.1","versionstring":"8.1 pre alpha","edition":"Enterprise"}

Updated from an older ownCloud or fresh install:
fresh

List of activated apps:
Files drop

The content of config/config.php:

Are you using external storage, if yes which one: local/smb/sftp/...
No

Are you using encryption:
No

Are you using an external user-backend, if yes which one: LDAP/ActiveDirectory/Webdav/...
No

### Client configuration

Browser:
Chrome 41.0.2272.104 (64-bit)

Operating System:
Mac OS X

**Comment by nickvergessen** [comment]
Works here with Chrome on Unix with german Umlauts `öäüß`.

Can you post the name you where trying to use?

**Comment by SergioBertolinSG** [comment]
German characters fails for me, just uploaded a folder called björn.

Some headers from chrome:

```
Remote Address:10.40.40.130:80
Request URL:http://10.40.40.130/enterprise_803RC1/index.php/apps/files/ajax/upload.php
Request Method:POST
Status Code:200 OK
Response Headers
view source
Cache-Control:no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Connection:Keep-Alive
Content-Encoding:gzip
Content-Length:193
Content-Security-Policy:default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *; connect-src *
Content-Type:text/plain; charset=utf-8
Date:Tue, 07 Apr 2015 10:02:24 GMT
Expires:Thu, 19 Nov 1981 08:52:00 GMT
Keep-Alive:timeout=5, max=100
Pragma:no-cache
Server:Apache/2.4.7 (Ubuntu)
Vary:Accept-Encoding
X-Content-Type-Options:nosniff
X-Frame-Options:Sameorigin
X-Powered-By:PHP/5.5.9-1ubuntu4.5
X-Robots-Tag:none
X-XSS-Protection:1; mode=block
Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate
Accept-Language:es-ES,es;q=0.8,en;q=0.6
Connection:keep-alive
Content-Disposition:attachment; filename="EncodingError"
Content-Length:365
Content-Type:multipart/form-data; boundary=----WebKitFormBoundary3Lv8J78EMd91lXal
Cookie:ocrmd0c3lf4z=7jcdvmgangd49lvjap32jcbre5
Host:10.40.40.130
OCS-APIREQUEST:true
Origin:http://10.40.40.130
Referer:http://10.40.40.130/enterprise_803RC1/index.php/apps/files
requesttoken:mH7IU.KVXH4ikvaH/TyON/J1KFzzFA
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36
X-Requested-With:XMLHttpRequest
Request Payload
Name
Path
upload.php
/enterprise_803RC1/index.php/apps/files/ajax
getstoragestats.php?dir=%2F
/enterprise_803RC1/index.php/apps/files/ajax
upload.php
/enterprise_803RC1/index.php/apps/files/ajax
getstoragestats.php?dir=%2F
/enterprise_803RC1/index.php/apps/files/ajax
upload.php
/enterprise_803RC1/index.php/apps/files/ajax
getstoragestats.php?dir=%2F
/enterprise_803RC1/index.php/apps/files/ajax
upload.php
/enterprise_803RC1/index.php/apps/files/ajax
getstoragestats.php?dir=%2F
/enterprise_803RC1/index.php/apps/files/ajax
getstoragestats.php?dir=%2F
/enterprise_803RC1/index.php/apps/files/ajax
upload.php
/enterprise_803RC1/index.php/apps/files/ajax
upload.php
/enterprise_803RC1/index.php/apps/files/ajax
16 requests ❘ 14.6 KB transferred
.
.
```

**Comment by LukasReschke** [comment]
Can confirm. "äaa" does not work in Chrome on 10.10

**Comment by PVince81** [comment]
Ok so Chrome 41 on Mac OS ? Could it be a Mac OS thing ?

**Comment by karlitschek** [comment]
FIX IT @PVince81 @LukasReschke

**Comment by LukasReschke** [comment]
Pending between
![resized_lazy-college-senior-meme-generator-it-will-probably-fix-itself-95a6dd](https://cloud.githubusercontent.com/assets/878997/7501680/32022e96-f436-11e4-9e36-a953731498b0.jpg)

and 

![54498936](https://cloud.githubusercontent.com/assets/878997/7501692/440f6bbc-f436-11e4-88a1-44b4702c4cb9.jpg)

**Comment by SergioBertolinSG** [comment]
Tested in 8.1 beta 2 in chrome, firefox and opera. Not working in any of them.

**Comment by SergioBertolinSG** [comment]
I've just realized uploading of folders with drag and drop is still not allowed in not-chrome browsers.
Is it possible to allow the upload of folders in the uploading dialog? Now only drag and drop in chrome allows this.

**Comment by LukasReschke** [comment]
> I've just realized uploading of folders with drag and drop is still not allowed in not-chrome browsers.
Is it possible to allow the upload of folders in the uploading dialog? Now only drag and drop in chrome allows this.

Can you file a new bug about this? THX. – Let's keep that one focused on the special char thing,

**Comment by PVince81** [comment]
He filed it here: https://github.com/owncloud/core/issues/16235
Will comment there.

**Comment by DeepDiver1975** [comment]
I guess this is an encoding issue on Mac - the is some UTF8 fun called NFD and NFC. Sounds related to me.

**Comment by DeepDiver1975** [comment]
We need someone woth a Mac to debug this. @georgehrke some spare time left on your side? THX

**Comment by georgehrke** [comment]
yes, can check later today

**Comment by georgehrke** [comment]
Uploading a folder named "äæñöø" works for me with Chromium 45.
I'm indeed able to reproduce it with older versions of Chromium (test version 38).

So what do we want to do here?
Pollute js code with OS X specific code or advice users to update?

**Comment by DeepDiver1975** [comment]
Thx. In this case it's a won't fix for me. Thx

**Comment by SergioBertolinSG** [comment]
Tested with chrome 43 in mac, working fine.
