### ISSUE TITLE
Log full of "message":"Accessing the API class is deprecated! Use the appropriate services instead!"

### ISSUE THREAD

**Issue by pierre-alain-b** [owncloud/core#15412]
Hello all,

Since I updated from oC 7.0.4 to oC 8.0.2, I see tons of duplicates of the following message piling up in the owncloud.log:
<code>
{"reqId":"b9a02f2acae3f0cdec3189bc4f34edde","remoteAddr":"a.b.c.d","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-04-06T06:27:08+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/"}
</code>

Otherwise, oC is working just fine. I don't know where the message could come from: is this from the core, from an app? Should I try to disable one app after the other to detect which one is generating the message? I don't know very well where to start the investigation... I've searched around and seen the message reported in a couple of messages but it was never reported as the actual issue (as in my case, the message is apparently not related to a failed feature) and never any explanation or fix was suggested.

I appreciate your advice. I will report any finding here of course!

## Server configuration
Operating system: Linux (Debian stable)
Web server: Apache/2.2.22
Database: Mysql 5.5.41
PHP version: PHP 5.4.39-0+deb7u2
ownCloud version: 8.0.2
Updated from an older ownCloud or fresh install: updated from 7.0.4
Are you using external storage, if yes which one: local/smb/sftp/... : No
Are you using an external user-backend, if yes which one: LDAP/ActiveDirectory/Webdav/... No

**Comment by Xenopathic** [comment]
What apps have you got enabled?

**Comment by pierre-alain-b** [comment]
Activity 1.2.0
Calendar 0.6.4
Contacts 0.3.0.18
Deleted files 0.6.2
Documents 0.9.0
External Sites 1.2
First Run Wizard 1.1
Gallery+ 2.0.7
Music 0.3.5
PDF Viewer 0.7
Share files 0.6.1
Text Editor 0.4
Updater 0.4
Versions 1.0.5
Video Viewer 0.1.3

All pretty standard except Music & Gallery+. I observed the message in the logs before installing Gallery+. But maybe Music?

Let me know your thoughts!

**Comment by RealRancor** [comment]
Hi,

yes. Music could cause this: https://github.com/owncloud/music/issues/345

**Comment by Xenopathic** [comment]
We shouldn't really ever spam messages to the log, especially if the message is one about deprecated APIs. Suggest we implement some kind of throttling, say to only print such messages every minute or so instead of on every request? In addition, that message isn't very useful - an app at least would help tremendously. cc @LukasReschke @DeepDiver1975 @MorrisJobke

**Comment by RealRancor** [comment]
Isn't it so that the message are only shown if the loglevel is on DEBUG ("level":0) which shouldn't be used in a productive environment anyway?

**Comment by pierre-alain-b** [comment]
- I confirm that disabling Music makes the crazy logging stop.
- I confirm that this is only displayed in loglevel 0 ; sorry I forgot loglevel 0 was debug.

So the root cause is now identified. According to owncloud/music#345, the point should be addressed by the main developer of the plugin message in the near future.

Thanks to all for your help and comments.
