### ISSUE TITLE
Uninstalling an app is "successful" even though FS permissions doesn't allow it

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#15414]
### Steps to reproduce
1. Install a 3rdparty app that can be uninstalled
2. Check the app permission in the apps directory, and verify that the apache user cannot delete the app folder (checked with www-data as apache user; the app folder belongs to my personal user)
3. Try to uninstall the app from the apps page
### Expected behaviour

An error is thrown warning that the app hasn't been deleted
### Actual behaviour

The app is deleted in the web interface. Reloading the page shows the app again
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.4

**ownCloud version:** checked with OC 8.0.3RC1 and 8.1 pre-alpha

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by jvillafanez** [comment]
I've also checked with the correct permissions (changing the files owner to www-data) and the app still remains in the FS and reappears in the web interface

**Comment by karlitschek** [comment]
Technically this can´t happen because a newly downloaded and installed app has always the right permissions. The only way to get this error is to manually put an app into the apps folder with the wrong permissions. 
Would still be good to improve the error message.

**Comment by oparoz** [comment]
Just ran into this. The logs clearly show the error, so that should be shown to the admin so that he can take action.

**Comment by PVince81** [comment]
Some of the install/uninstall code has changed. If issue persists with 10.0.4, please reopen.
