### ISSUE TITLE
ownCloud Demo not reachable with Firefox 37

### ISSUE THREAD

**Issue by Volker-E** [owncloud/core#15410]
[ownCloud Demo](https://demo.owncloud.org/) isn't reachable any more with Firefox 37. Seems due to HSTS policy changes.

**Comment by RealRancor** [comment]
Mhhh, works here with Firefox 37.0.1 on Linux (Debian) without a problem.

**Comment by Xenopathic** [comment]
Likewise - I can access it just fine, both with Firefox 36 and 37 (I updated right now). The HSTS policy won't have any effect on being able to access the site, it just restricts the validity of the SSL cert. If your browser doesn't accept the cert, the HSTS policy prevents you adding an exception. You might want to see if your certificate authority database is up to date.

**Comment by apg1980** [comment]
you have to uncheck certificate ocsp server check, than it works again.

**Comment by Volker-E** [comment]
Thanks for the inputs, works after 12 hours and restart. @apg1980 Where would that option be? Like described here: https://support.mozilla.org/de/questions/994264

**Comment by apg1980** [comment]
settings->cert area
