### ISSUE TITLE
config.php 'allow_user_to_change_display_name' also prevent email change

### ISSUE THREAD

**Issue by colomailbe** [owncloud/core#15438]
Hi there,

Just found another bug, if you set this parameter to 'false' in config.php 'allow_user_to_change_display_name', it will also prevent (both Admin and user) to change or set their email address.

This is quite annoying as email is very useful (and forbiding name change too ;-)

NB. tested on 8.0.2

Best regards,
Colo

**Comment by nickvergessen** [comment]
https://github.com/owncloud/core/blob/master/settings/templates/personal.php#L119-L124

```php
if($_['passwordChangeSupported']) {
?>
<form id="lostpassword" class="section">
	<h2>
		<label for="email"><?php p($l->t('Email'));?></label>
	</h2>
```

it's linked to password change, although I think it's wrong as well

**Comment by nickvergessen** [comment]
Fun fact, the php end checks the display name permission:
```php
		// this is the only permission a backend provides and is also used
		// for the permission of setting a email address
		if(!$user->canChangeDisplayName()){
			return new DataResponse(
				array(
					'status' => 'error',
					'data' => array(
						'message' => (string)$this->l10n->t('Unable to change mail address')
					)
				),
				Http::STATUS_FORBIDDEN
			);
		}

**Comment by colomailbe** [comment]
probably some mix up in the function to call...
Thanks for your update!

**Comment by michag86** [comment]
Duplicate #14127
