### ISSUE TITLE
IE8 and 9: Password enforcement still not working correctly

### ISSUE THREAD

**Issue by Norahy** [owncloud/core#15440]
#14918 fixed the problem that the placeholder is directly set as password; the user didn't even had a chance to enter anything.

Now the following error still occurs:
Set the focus on the password input field; do not enter anything. Leave the password field (e.g. click into the "share with user or group" input field)
-> The placeholder is set as password, the "share link" dropdown is shown. The password field is empty. Again, set the focus to the pw-input and leave it again -> placeholder "*******" is shown. Do the step again -> input field is empty again.

Somehow the password value is still set to the value of the placeholder if no user input is given.

**Comment by ryantbrown** [comment]
Solution: stop using IE8 / 9

**Comment by davitol** [comment]
As IE8 support is dropped in 9.0 I will close this issue.
