### ISSUE TITLE
Mount external storage with OC user credentials

### ISSUE THREAD

**Issue by Larx** [owncloud/core#15451]
As #10337 was closed, I'd like to propose another enhancement: Add external storage using OC credentials to log in. 

This is already available for SMB mounts, however it would be great to have this for other external storage methods, too. E.g. when using a lightweight local FTP server to include local files with correct user rights this would be an enhancement.

**Comment by PVince81** [comment]
CC @Xenopathic

**Comment by Xenopathic** [comment]
I'll assign myself for the time being... hopefully I'll get some time to work on a proper solution.

**Comment by Xenopathic** [comment]
Done!
