### ISSUE TITLE
 Provisioning API: still working with maintenance mode on

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#15456]
### Steps to reproduce

Turn on the maintenance mode from the command-line
Add an user using the provisioning API: `curl -u user:password -X POST http://server:port/ocs/v1.php/cloud/users -d userid=foo -d password=11111`

### Expected behaviour

An error is thrown due to the maintenance mode
### Actual behaviour

The user is added
### Server configuration

Operating system: ubuntu 14.04

Web server: apache 2.4.7

Database: mysql

PHP version: 5.5.4

ownCloud version: 8.0.3RC1 EE

Updated from an older ownCloud or fresh install: fresh install

**Comment by MorrisJobke** [comment]
Related to #15436

**Comment by nickvergessen** [comment]
applies to all ocs calls?

**Comment by jvillafanez** [comment]
I've checked with some of the calls from the provisioning API: add and get users, and enable and disable apps. All those works even though the maintenance mode is active.

**Comment by jvillafanez** [comment]
I've also checked with the files_external with the same behaviour, so this issue probably applies to all ocs calls

**Comment by MorrisJobke** [comment]
@DeepDiver1975 @PVince81 I would say this can lead to similiar problems like we had with the cron.php and the maintenance mode.

**Comment by MorrisJobke** [comment]
Ref #14843

**Comment by PVince81** [comment]
Argh, this means that v1.php doesn't check for maintenance mode either ?
But it requires "base.php" which should do it... or does it ?

**Comment by MorrisJobke** [comment]
> But it requires "base.php" which should do it... or does it ?

Doesn't seem so, because cron.php also uses base.php ;)

**Comment by PVince81** [comment]
and suddenly a hero jumps in :wink:
