### ISSUE TITLE
Upgrade 8.0.2.0 fails: Could not automatically fix legacy storage 

### ISSUE THREAD

**Issue by Chassetheater** [owncloud/core#15454]
I receive an error when upgrading from 7.0.4 to 8.0.2.0:

Could not automatically fix legacy storage "local::/data/B3C17EF6-2B15-4D85-9560-A9786696EE84/" => "home::B3C17EF6-2B15-4D85-9560-A9786696EE84" because they both have data

How to fix this?

Thnx Remco

**Comment by nickvergessen** [comment]
See https://github.com/owncloud/core/issues/13980#issuecomment-73511661 + following comments
