### ISSUE TITLE
Almost full warning message is not removed after deletions.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#15452]
### Steps to reproduce

Having a OC server installed and several users.
1. Put a low quota to a user. (4MB for example).
2. Upload a couple of files about 1.6 MB and several files to reach ~97% full storage.
3. Delete one of the 1.6MB files. 

### Expected behaviour
After point 2 a warning message about almost full storage appears.
After point 3 it dissapears.

### Actual behaviour
Message is still there, even moving to other elements. Refreshing of the page is needed.

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.0.3.0","versionstring":"8.0.3 RC1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise version.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** 
no

### Client configuration

**browser**
Chrome 41

**Operating system**
Mac OS X

**Comment by SergioBertolinSG** [comment]
Perhaps related with #5475 ?

**Comment by PVince81** [comment]
I'd expect the next call to "getstoragestats.php" (which happens often) would make it disappear.

**Comment by PVince81** [comment]
Trivial fix here https://github.com/owncloud/core/pull/19747
