### ISSUE TITLE
Remove obsolete "oc:///" stream wrapper

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15461]
I found some unit tests related to that stream wrapper.
AFAIK this is now unused/obsolete ?

We should deprecate this officially.

@DeepDiver1975 @icewind1991

**Comment by DeepDiver1975** [comment]
@icewind1991

**Comment by PVince81** [comment]
From what I see this seemed to be some kind of shortcut to the view.

Basically one could do `fopen('oc:///someuser/files/path/to/file.dat')` to open a file from an app.
This would be the equivalent of `$rootView->fopen()`.

In general I wouldn't recommend using such weird way to access files. Ideal is to use the Node API instead.

**Comment by PVince81** [comment]
PR that kills it: https://github.com/owncloud/core/pull/26381
