### ISSUE TITLE
Provide a mechanism to register cron jobs outside or app.php

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15460]
Currently apps need to register their cron jobs inside of app.php.
The problem with this is that adding the jobs there will cause a "insert if not exists" every time the app is loaded, even if the PHP request is not cron.php.

We should provide a mechanism for apps to register cron jobs outside of app.php.
One suggestion would be to add a method "registerCronJobs($jobManager)" in the Application class and expect apps to override that method to register their jobs there.

That method would then only be called by cron.php when really needed.

@nickvergessen as discussed

**Comment by PVince81** [comment]
See part of the discussion here: https://github.com/owncloud/core/pull/14676/files#r27889424

**Comment by DeepDiver1975** [comment]
refs https://github.com/owncloud/core/issues/13816#issuecomment-78176535

**Comment by PVince81** [comment]
or https://github.com/owncloud/core/issues/18804

**Comment by nickvergessen** [comment]
or use install.php and update.php

That should be enough for the moment, close?

**Comment by PVince81** [comment]
Makes sense
