### ISSUE TITLE
Showing original path for files in trash

### ISSUE THREAD

**Issue by remixtj** [owncloud/core#15467]
When a file is put in the trashbin there is no way to know where originally it was. If user restores the file is moved back to the original path, but user doesn't know what is.

Additionally if there are several files with the same name in the trash, there's no possibility find which is the correct one a user wants to restore.

An idea could be to show a tooltip bubble when user goes over the restore button. Something like what happens when you go over the filename on the activity app.

**Comment by nickvergessen** [comment]
Works at least on master
![path-in-trashbin](https://cloud.githubusercontent.com/assets/213943/7045539/4e24b8e8-ddff-11e4-8962-b229c49eb492.png)

**Comment by remixtj** [comment]
on 7.0.5 is not available and also on demo.owncloud.org (running 8.0.2) is not working. Maybe is very recent change

**Comment by nickvergessen** [comment]
Also works on my stable8 branch, so it looks like it will come with 8.0.3
