### ISSUE TITLE
Provisioning api app uses wrong app type

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#15462]
```xml
	<types>
		<!-- this is used to disable the feature of enabling an app for specific groups only because this would break this app -->
		<filesystem/>
	</types>
```

App type filesystem should not be used here, just to avoid the "enable for group" feature. If that is needed a new type should be added. But using type filesystem will cause the app to be loaded in various scenarios, where it is not needed, e.g. webdav

**Comment by DeepDiver1975** [comment]
I'm happy to accept a PR anytime to fix this.
