### ISSUE TITLE
When updating

### ISSUE THREAD

**Issue by highacid** [owncloud/core#15477]
First it was telling me that is some CSR attack and it started this.
This ownCloud instance is currently being updated, which may take a while.
This page will refresh itself when the ownCloud instance is available again.
Contact your system administrator if this message persists or appeared unexpectedly.
Thank you for your patience.

Now this is what I have for some time, and in past weeks or so I was not able login at all into my admin side.

**Comment by nickvergessen** [comment]
If you are sure no other admin is updating your instance atm, run the following in the console of your installation:
`./occ maintenance:mode --off`

**Comment by RealRancor** [comment]
This is also described here:

https://doc.owncloud.org/server/8.0/admin_manual/maintenance/upgrade.html#troubleshooting

**Comment by MorrisJobke** [comment]
please reopen if the above tips doesn't solve the problem for you

**Comment by highacid** [comment]
I get -bash: ./occ: Permission denied funny cause I am root... and the user under the running account does not have a shell.

**Comment by highacid** [comment]
root@panel [/home/uhlhosting/public_html/work]# ./occ maintenance:mode --off
Console has to be executed with the same user as the web server is operated
Current user: root
Web server user: uhlhosting

**Comment by highacid** [comment]
How do you reopen same issue anyhow? :dart:

**Comment by MorrisJobke** [comment]
@highacid https://doc.owncloud.org/server/8.0/admin_manual/configuration_server/occ_command.html#using-the-occ-command

You need to run the command as the web server user

For Ubuntu for example this is:

```
sudo -u www-data php occ
```

To see the user (in the above example the user is `www-data`) do a `ls` on the config file: `ls -l config/config.php`:

```
-rw-r----- 1 mjob users 485  8. Apr 17:57 config/config.php
```

In my case the user is `mjob`.
