### ISSUE TITLE
Updates between multiple major versions are unsupported. Owncloud

### ISSUE THREAD

**Issue by xav13r** [owncloud/core#15479]
hi, i had a 6.0 owncloud version on ubuntu 12.04 server LTE i updated through an option inside the administration panel but after downlading th upgrade package it sais Updates between multiple major versions are unsupported.

**Comment by MorrisJobke** [comment]
@xav13r Do you upgrade via package manager? It is then possible (if you didn't updated your packages for a long time) that you simply skipped the 7.0 series.

1. Please use the dedicated 7.0 series repo: https://software.opensuse.org/download/package?project=isv:ownCloud:community:7.0&package=owncloud
2. Then do a downgrade of the owncloud package to 7.0.5
3. Run the migration and log in to your ownCloud
4. switch to the stable repo without a dedicated version: https://software.opensuse.org/download/package?project=isv:ownCloud:community&package=owncloud
5. upgrade to 8.0.2

**Comment by xav13r** [comment]
thank you so much ill try it now and let you know.
