### ISSUE TITLE
Admin cannot change email address if allow_user_to_change_display_name is set to false

### ISSUE THREAD

**Issue by michag86** [owncloud/core#15474]
Like written in the subject, it is not possible to change the email address of an user as admin, if the config value of allow_user_to_change_display_name is set to false.

https://github.com/owncloud/core/blob/a8b756154a533a2618f03c54aca56af957da12ae/settings/controller/userscontroller.php starting in line 495:
```
		if(!$user->canChangeDisplayName()){
			return new DataResponse(
				array(
					'status' => 'error',
					'data' => array(
						'message' => (string)$this->l10n->t('Unable to change mail address')
					)
				),
				Http::STATUS_FORBIDDEN
			);
		}
```

Environment
* ownCloud 8.0.2
* user backend: internal (sql)
* PHP 5.4.39
* Apache 2.4.6
* CentOS 7.1

**Comment by nickvergessen** [comment]
Duplicate https://github.com/owncloud/core/issues/15438
