### ISSUE TITLE
Cron.php runs in single-user mode

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#15498]
### Steps to reproduce
Following similar steps as https://github.com/owncloud/core/issues/14843
1. Set single-user mode in the server
2. `update oc_jobs set last_run=0`
3. Run `php cron.php`
4. Check "oc_jobs" table

### Expected behaviour
Cron doesn't run, timestamps in the "oc_jobs" table don't change

### Actual behaviour
Cron runs

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.4

**ownCloud version:** 8.0.3RC1

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by PVince81** [comment]
Thanks.

@DeepDiver1975 @icewind1991

**Comment by PVince81** [comment]
As discussed on IRC, I also agree that cron should not run in single-user mode (aka admin-only mode) because it is similar to maintenance mode. The purpose of that mode is to do maintenance work, so cron should not run.

**Comment by PVince81** [comment]
@karlitschek

**Comment by karlitschek** [comment]
Thanks for the fix @icewind1991

**Comment by MorrisJobke** [comment]
@karlitschek This was scheduled for 8.0.4 -> I have marked #15510 as backport request
