### ISSUE TITLE
"Everyone" list is empty after visiting a group list

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#15494]
### Steps to reproduce

1. Go to Users section
2. Go to group "Admin"
3. Go back to "Everyone

### Expected

All users are displayed

### Actual

The list is blank, only a hard refresh brings back the list.

**Comment by nickvergessen** [comment]
Does not affect stable8, so can wait a bit

**Comment by LukasReschke** [comment]
Can confirm.

**Comment by PVince81** [comment]
Not sure if showstopper if there is a simply workaround (refreshing the page).
This can be adressed in the bugfix phase.

**Comment by LukasReschke** [comment]
> Not sure if showstopper if there is a simply workaround (refreshing the page).
> This can be adressed in the bugfix phase.

Well this is very bad UX and we should fix it before 8.1 => Showstopper for 8.1 which can also be fixed in the bugfix phase ;-)

**Comment by MorrisJobke** [comment]
fixed with #15555
