### ISSUE TITLE
Manual upgrade 

### ISSUE THREAD

**Issue by highacid** [owncloud/core#15493]
uhlhosting@uhlhosting.ch [~/public_html/work]# ./occ upgrade
Turned on maintenance mode
An exception occurred while executing 'CREATE TABLE oc_ownc_appconfig_zulyvbqj53x7y (`appid` VARCHAR(32) DEFAULT '' NOT NULL, `configkey` VARCHAR(64) DEFAULT '' NOT NULL, `configvalue` LONGTEXT DEFAULT NULL, INDEX oc_y0nv4jio0lc41 (`configkey`), INDEX oc_bqel04knfmks0 (`appid`), PRIMARY KEY(`appid`, `configkey`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB':

SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_ownc_appconfig_zulyvbqj53x7y' already exists
Turned off maintenance mode
Update failed
uhlhosting@uhlhosting.ch [~/public_html/work]# ./occ maintenance:mode --off
Maintenance mode disabled
uhlhosting@uhlhosting.ch [~/public_html/work]#

**Comment by highacid** [comment]
Updating ownCloud to version 8.0.2, this may take a while.

Turned on maintenance mode
An exception occurred while executing 'CREATE TABLE oc_ownc_appconfig_5t3iy7k60h1gc (`appid` VARCHAR(32) DEFAULT '' NOT NULL, `configkey` VARCHAR(64) DEFAULT '' NOT NULL, `configvalue` LONGTEXT DEFAULT NULL, INDEX oc_tacw6ioltlejy (`configkey`), INDEX oc_0103ja8ftg4b7 (`appid`), PRIMARY KEY(`appid`, `configkey`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_ownc_appconfig_5t3iy7k60h1gc' already exists
The update was unsuccessful. Please report this issue to the ownCloud community.

**Comment by nickvergessen** [comment]
Duplicates #14916
