### ISSUE TITLE
WebDAV interface accessible to normal users with single-user mode active

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#15495]
### Steps to reproduce
1. Enable single-user mode through command-line `sudo -u www-data ./occ maintenance:singleuser --on`
2. Access to webdav interface with a normal user `curl -u foo:11111 -X PUT --data-binary @Pictures/8.jpg http://10.40.30.21:8180/remote.php/webdav/9.jpg`

### Expected behaviour
Admin users should be able to access, but normal users shouldn't (same behaviour that the web interface has)

### Actual behaviour
All users can access to the webdav interface. Normal users can upload files through the webdav interface.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.4

**ownCloud version:** 8.0.3RC1

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by karlitschek** [comment]
good catch

**Comment by PVince81** [comment]
Fixed by https://github.com/owncloud/core/issues/15510
