### ISSUE TITLE
Share information not updated if LDAP user is added to LDAP group

### ISSUE THREAD

**Issue by lnxbil** [owncloud/core#15504]
### Steps to reproduce

1. Add an user to a group with already shared folders
2. observe that the new folder is not shared to the new group member

This does sometimes work and sometimes it does not. If I create a new folder and share it to the same group after adding the user to their group, it works as expected, yet it does not work for already shared folders.

### Expected behaviour
The folder should be shared to all group members.

### Actual behaviour
The folder does not appear to be shared (not visible).

### Server configuration
**Operating system**:
Debian Wheezy
**Web server:**
Apache 2.2.22
**Database:**
PostgreSQL 9.1.5
**PHP version:**
5.4.36
**ownCloud version:** (see ownCloud admin page)
7.0.5
**Updated from an older ownCloud or fresh install:**
updated from 5 to 6 to 7 (debian packages)
**List of activated apps:**
activity, external sites, full text search, ldap backend, mail tempalte editor, pdf viewer, pictures, share files, text editor
**The content of config/config.php:**
```
<?php
$CONFIG = array (
  'datadirectory' => '/var/www/owncloud/data',
  'version' => '7.0.5.2',
  'installed' => true,
  'maintenance' => false,
  'dbtype' => 'pgsql',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'forcessl' => false,
  'updatechecker' => false,
  'default_language' => 'de_DE',
  'appstoreenabled' => true,
  'enable_previews' => false,
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/owncloud/myapps',
      'url' => '/myapps',
      'writable' => true,
    ),
  ),
  'ldapIgnoreNamingRules' => false,
  'share_folder' => '/Shared',
  'trusted_domains' => 
  array (
    0 => 'blabla',
  ),
  'knowledgebaseenabled' => false,
  'loglevel' => 1,
  'logtimezone' => 'Europe/Berlin',
  'log_authfailip' => true,
  'log_rotate_size' => 104857600,
  'enable_avatars' => false,
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP
#### LDAP configuration (delete this part if not used)

```
/var/www/owncloud $ php -f occ ldap:show-config
+------------------------------+---------------------------------------------------------------------------+
| Configuration                |                                                                           |
+------------------------------+---------------------------------------------------------------------------+
| hasMemberOfFilterSupport     |                                                                           |
| hasPagedResultSupport        |                                                                           |
| homeFolderNamingRule         |                                                                           |
| lastJpegPhotoLookup          | 0                                                                         |
| ldapAgentName                |                                                                           |
| ldapAgentPassword            | ***                                                                       |
| ldapAttributesForGroupSearch |                                                                           |
| ldapAttributesForUserSearch  |                                                                           |
| ldapBackupHost               |                                                                           |
| ldapBackupPort               |                                                                           |
| ldapBase                     | xxxx,dc=de                                               |
| ldapBaseGroups               | xxxx,dc=de                                                |
| ldapBaseUsers                | xxxx,dc=de                                                |
| ldapCacheTTL                 | 600                                                                       |
| ldapConfigurationActive      | 1                                                                         |
| ldapEmailAttribute           | mail                                                                      |
| ldapExperiencedAdmin         | 0                                                                         |
| ldapExpertUUIDGroupAttr      |                                                                           |
| ldapExpertUUIDUserAttr       |                                                                           |
| ldapExpertUsernameAttr       |                                                                           |
| ldapGroupDisplayName         | cn                                                                        |
| ldapGroupFilter              | objectClass=posixGroup                                                    |
| ldapGroupFilterGroups        |                                                                           |
| ldapGroupFilterMode          | 1                                                                         |
| ldapGroupFilterObjectclass   |                                                                           |
| ldapGroupMemberAssocAttr     | memberUid                                                                 |
| ldapHost                     | localhost                                                                 |
| ldapIgnoreNamingRules        |                                                                           |
| ldapLoginFilter              | (&(objectclass=*)(|(|(mailPrimaryAddress=%uid)(mail=%uid))(|(uid=%uid)))) |
| ldapLoginFilterAttributes    |                                                                           |
| ldapLoginFilterEmail         | 1                                                                         |
| ldapLoginFilterMode          | 1                                                                         |
| ldapLoginFilterUsername      | 1                                                                         |
| ldapNestedGroups             | 0                                                                         |
| ldapNoCase                   | 0                                                                         |
| ldapOverrideMainServer       | 0                                                                         |
| ldapPagingSize               | 500                                                                       |
| ldapPort                     | 389                                                                       |
| ldapQuotaAttribute           | roomNumber                                                                |
| ldapQuotaDefault             | 256 MB                                                                    |
| ldapTLS                      | 0                                                                         |
| ldapUserDisplayName          | uid                                                                       |
| ldapUserFilter               | (objectclass=*)                                                           |
| ldapUserFilterGroups         |                                                                           |
| ldapUserFilterMode           | 1                                                                         |
| ldapUserFilterObjectclass    |                                                                           |
| ldapUuidGroupAttribute       | auto                                                                      |
| ldapUuidUserAttribute        | auto                                                                      |
| turnOffCertCheck             | 0                                                                         |
+------------------------------+---------------------------------------------------------------------------+
```

### Additional Notes

If I unshare and reshare the folder to the group it yields to correct behaviour, yet this is not applicable if you have a lot of groups and a lot of users.

**Comment by lnxbil** [comment]
As requested in IRC @PVince81 @blizzz

**Comment by PVince81** [comment]
also @schiesbn as it's related to shares

**Comment by blizzz** [comment]
There is a background job running every hour who updates group memberships and throws hooks so that group shares will be upgraded as well. We don't know about group memberships changes in LDAP until we check and compare.

**Comment by lnxbil** [comment]
I manually started the cron-job after updating the LDAP group memberships (and it also runs automatically every 15 minutes) or are you not referring to the cron job?

The change of the group was done earlier this week, so the job you're talking about should be run at least once. I also had a look at the ```occ``` but there is no update membership or something similar.

**Comment by blizzz** [comment]
Yes, i am referring thereto.

In the database, is ldap_group_members filled properly?

**Comment by lnxbil** [comment]
I don't know if it's properly, but I see it in the GUI and the SQL also states that it's working:

```sql
select count(*) from oc_ldap_group_members where owncloudname = 'XXXXX' and owncloudusers like '%XXXX%';
1
```

so the user is in the group - yet I it's clear because if I create a new share for that group, the share is properly displayed for the user. I fixed the problem for the specific user by hand: sharing the already shared folder with the specific user in addition to the group, yet this only fixes it for one user.

**Comment by lnxbil** [comment]
I tried to search for a similar issue before issuing my problem and I have overlooked #15004 which is actually very similar to my problem.

**Comment by blizzz** [comment]
I will try to reproduce it, but won't have time before next week.

**Comment by blizzz** [comment]
I did following test today with stable7:

1. Have an LDAP group
2. as local admin, share a folder with full permissions and add two files
3. as a group member log in. the folder is available, uploading a file works.
4. add a new member to this group
5. verify on Users page that the new member is part of the group
6. log in as new member -> the shared folder is available. Even without the background job run.

I.e. could not reproduce. But you state is sometimes work and sometimes does not … any observations or suggestions?

**Comment by lnxbil** [comment]
I retested it and it still does not work:
1) Add a user to an existing LDAP group (externally added not in OC) which already has shared stuff 
2) Checking group membership in OC looks fine, user is member of group
3) Login user and there is nothing present besides an empty 'Shared'-Folder.

Maybe this is also related to the remapped Shared-Folder? There were some problems with this in the past, yet maybe some related bug. If I look at all the shares with respect to LDAP users, I can still see some shares with and some without the 'Shared'-Prefix (Postgresql syntax):

```
SELECT s.id,
        CASE
            WHEN s.token IS NULL THEN 'Benutzerfreigabe'::text
            ELSE 'Linkfreigabe'::text
        END ||
        CASE
            WHEN "substring"(s.share_with::text, 1, 2) = '$2'::text THEN ' mit Passwort'::text
            WHEN s.share_with IS NOT NULL THEN ''::text
            ELSE ' ohne Passwort'::text
        END AS "Typ", COALESCE(owncloud_ldap_strip_username(ol.ldap_dn::text), s.uid_owner::text) AS "source user", COALESCE(owncloud_ldap_strip_username(ul.ldap_dn::text), s.share_with::text) AS "destination user", s.file_target, s.expiration, s.token
   FROM oc_share s
   LEFT JOIN oc_ldap_user_mapping ol ON s.uid_owner::text = ol.owncloud_name::text
   LEFT JOIN oc_ldap_user_mapping ul ON s.share_with::text = ul.owncloud_name::text
  ORDER BY char_length(s.token::text), char_length(s.share_with::text) DESC, s.uid_owner, s.share_with, s.file_target;
```

I can also see that for some users, there exist entries for explicit sharing by username and share, others are only shared via group. This is strange because I rechecked the shares and they are only shared to groups, not individuals. Maybe this is some "old-style-sharing" from a previous OC version?

Even if this bug/is is due to bad behaviour based on bad data in the database, how do I fix this without reinstalling and resharing everything?

**Comment by PVince81** [comment]
If we assume that the upgrade went properly, at update time the shares will all receive the "/Shared" prefix in files_target. However users are then free to move the received shared folders out of this one, which would then change the files_target path and remove the prefix. So it is not necessarily an issue.

Can you try and find the share entries matching the specific share you were using in your tests ? Does this one look broken ?

**Comment by jvillafanez** [comment]
I have a similar issue:

1. Have an LDAP group
2. as *LDAP user* from a different group, share a file with another LDAP group
3. as a group member log in. the file is visible
4. add a new member to this group
5. verify on Users page that the new member is part of the group
6. log in as new member -> the shared folder is available. Even without the background job run.

Step 6 is the one that fails. It seems to work only if it's a local user.

To be a bit more clearer, "admin" (local) and a LDAP user share a file (different each other) to a LDAP group. Both files are visible for any member of the LDAP group. When a new member is added to the group, only the file shared by "admin" is shown to the new member.

**Comment by jvillafanez** [comment]
Checked with 8.0.3 and 8.0.5, both versions have the same behaviour

**Comment by gwes** [comment]
I can confirm having what appears to be the same issue.

Existing directory shared with existing ldap group
new user added to ldap group via domain
user appears in the correct group in domain and in owncloud web interface
logging on as the user and no shared directories/files are available

I'm not 100% sure that removing and re-sharing works
(I can't take any shares away from people right now)

I'm not 100% sure if it is intermittent or always happens.
(but I will do some more testing later today)

Running OC 8.0.2 on Ubuntu 14.04.2, can get additional info if it's required.

**Comment by lnxbil** [comment]
Over the last month, we had non-deterministic behavior:

Adding 4 users in a batch, 3 work, one does not (not automatically shared).

**Comment by PVince81** [comment]
maybe because there is a delay until ownCloud refreshes its user info ?

**Comment by PVince81** [comment]
Is this still happening in 8.2.8, 9.0.5 or 9.1.1 ?

**Comment by jvillafanez** [comment]
Maybe @owncloud/qa can verify if this is still an issue for those versions before moving the issue (if it still applies).

**Comment by PVince81** [comment]
please try with 9.1.2RC1 and if it doesn't add the user after a while, you could try the new `occ ldap:update-group group_name` command which will immediately update the group memberships from LDAP instead of having to wait for TTL expiration.
