### ISSUE TITLE
Empty content notice does not show for shared links

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#15508]
What is expected:
![capture du 2015-04-09 13 34 06](https://cloud.githubusercontent.com/assets/925062/7065910/3032b2ea-debd-11e4-9070-91b4800f83ac.png)
How it actually looks:
![capture du 2015-04-09 13 32 23](https://cloud.githubusercontent.com/assets/925062/7065911/30346838-debd-11e4-9abd-e5ee63acd284.png)

The emptycontent element is there, it just stays hidden. When the folder is empty it should be shown though because otherwise it’s confusing as to why there’s no content.
As an addition, when you have upload rights in that folder, the additional `<p>` in the notice could say `You can upload into this folder`

cc @owncloud/designers @PVince81 @schiesbn do you know why the notice is not shown?

**Comment by PVince81** [comment]
Is it gone again ? :frowning: regression

**Comment by MorrisJobke** [comment]
Doesn't work in stable7, stable8 and master

**Comment by MorrisJobke** [comment]
I read through the code and simply have no idea how what gets loaded and which code parts are used from the sharing and which are from the files app. :(

**Comment by jancborchardt** [comment]
Yeah, I found that confusing as well. It seems that for file lists code from core is used. Because when you inspect it, the emptycontent message is the one from files, not from the sharing filelist template.

**Comment by PVince81** [comment]
You probably need to add a new override here: https://github.com/owncloud/core/blob/master/apps/files_sharing/js/public.js#L121 that overrides this method: https://github.com/owncloud/core/blob/master/apps/files/js/filelist.js#L1623

This is still trashy code. Ideally we should move the public file list code to a separate class PublicFileList that properly extends the FileList class.

**Comment by PVince81** [comment]
I just tried it and the empty content does show when upload is allowed, but not when upload is denied.

**Comment by PVince81** [comment]
The same problem applies if you share a folder (regular share) with another user and remove "can edit". The empty folders will not show any message.

We could show the regular "No files here" message but hide the upload subtext.

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/core/pull/15769

**Comment by jancborchardt** [comment]
Fixed with https://github.com/owncloud/core/pull/15769, thank you @PVince81
