### ISSUE TITLE
A normal user can share files through the share API with single-user mode active

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#15505]
### Steps to reproduce
1. Set single-user mode in the server
2. Share a file using the share API and a normal user `curl -u foo2:11111 -X POST http://server/ocs/v1.php/apps/files_sharing/api/v1/shares -d path=ownCloudUserManual.pdf -d shareType=3`

### Expected behaviour
An error is thrown because single-user mode is active and the user isn't admin

### Actual behaviour
The share is created

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.4

**ownCloud version:** 8.0.3RC1

**Updated from an older ownCloud or fresh install:** fresh install

### Notes
This also could applies to any OCS call. The provisioning API probably works as intended because is only for admins, so a normal user won't be able to use it with or without the single-user mode.

**Comment by nickvergessen** [comment]
This again affects all OCS api calls

**Comment by PVince81** [comment]
Fixed by https://github.com/owncloud/core/issues/15510
