### ISSUE TITLE
admin site should contain controls for console.php

### ISSUE THREAD

**Issue by finius** [owncloud/core#15513]
To avoid breaks in media for an administrator while performing administrative tasks (f.ex. using console.php to rescan user directories), a GUI control for those common tasks should be placed in the administrator frontend of the owncloud website.

**Comment by nickvergessen** [comment]
Rescanning user directories should not be a daily task, but is a last way to try to fix stuff.
However @DeepDiver1975 is working on an app to allow running such stuff from the front end, so won't fix in core, but "there is an app for it"

**Comment by finius** [comment]
okay - thank's for this hint!
