### ISSUE TITLE
GUI frontend for detection of user directories that became an LDAP-orphan

### ISSUE THREAD

**Issue by finius** [owncloud/core#15515]
While ownCloud is able to use LDAP to give users access to the system, it creates user directories the same way it does for local created ownCloud users. 
Unfortunately ownCloud seems not to (be able to) take notice, when users have been deleted in LDAP, so the data directory gets bigger and bigger because the mount of occupied storage for orphaned user directories is never cleaned up. I would appreciate a function or an overview in the user panel, to get an overview of all the users (together with an option to delete those directories) that have no longer any correspondending counterpart (SIDs/UPN/etc) on the AD/LDAP side.

**Comment by Froster** [comment]
Same

**Comment by finius** [comment]
If "same" means solution-by-app, I'm not quite sure if maintanance of data directories and the database itself shouldn't be a sovereign task of ownCloud core itself

**Comment by DeepDiver1975** [comment]
There is console command which takes care of this.

**Comment by MorrisJobke** [comment]
The command is documented in https://doc.owncloud.org/server/8.0/admin_manual/configuration_user/user_auth_ldap_cleanup.html and available for 7.0.5 and 8.0.0 and upwards.

**Comment by MorrisJobke** [comment]
@finius Please reopen if this command doesn't fit your needs.

**Comment by Froster** [comment]
@MorrisJobke  if i tested right i only could get in ldap deleted users but i Need also a view for

- disabled users
- users who only get revoked there access while deleted out of the ldap Group which grants Access to OC

cause not all users will directly deleted or disabled in a bigger Company :(

Is there a Chance to get this filters function's on Shell?

**Comment by MorrisJobke** [comment]
@blizzz Can you have a look. I'm not fully aware what is already in there.

**Comment by blizzz** [comment]
This is not implemented and would also extend by far the "deleted LDAP users" feature.

#### Disabled Users ####

Speaking out of memory and without much rechecking, disabled users is not a standardized LDAP feature but a proprietary method. Nevertheless it's certainly possible to get a report therefore, but then somebody needs to do this. Typically, for AD you would take the user list filter and add a condition to check the userAccountControl. 

#### Revoked Access ####

I am not sure I understand it quite right. So you want to see users, who once have been part of a specific group, but are not anymore? 

I don't think ownCloud is the right place for this, but rather the directory management layer/application. 

OTOH you could assume that all mapped users at least once have been part of the group in question. You could fetch the group members and compare the mapped users against this list and output the difference. Sound feasible.

**Comment by Froster** [comment]
Disabled Users

Dont know i think there is a ldap value in AD?

Revoked Access

In our LDAP (AD) configuration we have an User Filter. Collecting serveral hundred users.
A User must be "memberof=" a Group but that shouldn't be the deal.

It should be this way:

OC reads all users with Access and compares them to local entrys.

Missmatch = is not any more allowed to Access.

**Comment by finius** [comment]
@Froster: sounds reasonable

**Comment by blizzz** [comment]
For revoked access a described by @Froster please follow https://github.com/owncloud/core/issues/15656 it contains a proposed PR.
