### ISSUE TITLE
Add system-wide certificate storage

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#15518]
We really need in addition to the user-wide certificate storage also a system-wide one… Let's see how and if we can make this happen properly. Then we need to re-evaluate if all external storages implement it properly. 

@icewind1991 FYI

**Comment by mwellnitz** [comment]
maybe it's possible to integrate client-crtificates also? That would increase the security level heaviely.

**Comment by LukasReschke** [comment]
> maybe it's possible to integrate client-crtificates also? That would increase the security level heaviely.

Completely unrelated topic.

**Comment by LukasReschke** [comment]
For client certificate support see https://github.com/owncloud/client/issues/69. – It will come, but not right now ;-)

**Comment by PVince81** [comment]
@LukasReschke move to 9.0 ?

**Comment by LukasReschke** [comment]
@icewind1991 We fixed this, right?

**Comment by icewind1991** [comment]
Yes
