### ISSUE TITLE
OC.History - don't fire reload if URL hasn't changed any value

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#15520]
If for example via a click on a `<a href='#'>' the URL is changed, but the actual pointer of the URL is still the same no reload of the files app should happen.

Noticed together with @pvince81

See https://github.com/owncloud/core/pull/15512#issuecomment-91241159 for a real world example

**Comment by oparoz** [comment]
It's OC.Util.History now.

**Comment by PVince81** [comment]
@noveens here is the location where the file app listens to the browser back button event: https://github.com/owncloud/core/blob/master/apps/files/js/app.js#L177

**Comment by noveens** [comment]
@PVince81 ,
I'll have a look.

**Comment by noveens** [comment]
@PVince81 ,
Is this issue still relevant?
A refresh is called if and only if someone clicks a back button or does something with the browser stack.

**Comment by PVince81** [comment]
@noveens yes please.

**Comment by PVince81** [comment]
You need to add a check to see whether the path from the pop state stack is the same like the current list. If it is, don't trigger a file list refresh.
