### ISSUE TITLE
Handle HTTP connection errors in files_external as StorageNotAvailable

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#15524]
Follow up from https://github.com/owncloud/core/pull/15521#issuecomment-91370650

If I shut down the apache it's a:

`Sabre\HTTP\ClientException` with code `7` and message `Failed to connect to 192.168.0.17 port 80: Connection refused`. We should handle this as well.

If I shut down the whole PC it's:

`Sabre\HTTP\ClientException` with code `7` and message `Failed to connect to 192.168.0.17 port 80: No route to host`.

Can we include these two as well? Because I think they are also valid "storage not available", because of network/server/process outage.

**Comment by MorrisJobke** [comment]
Okay ... doesn't was that easy to fix. :(

@PVince81 Can you have a look at this tomorrow? It's easy to reproduce :)

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/core/pull/15530
