### ISSUE TITLE
Need the ability to use external storage (S3 in my case) and restrict users from seeing each others files.

### ISSUE THREAD

**Issue by crewshin** [owncloud/core#15523]
Anyone considering adding a feature to allow users to have jailed/private directories when using external storage on S3? I'd LOVE to be able to use ownCloud for my company instead of an sftp server but this is a deal breaker for me. I just need a way to allow customers to transfer files to us privately and not store the files on the system drive basically. Customer A should not be able to see Customer B's files :)

**Comment by MorrisJobke** [comment]
This is available if you use the S3 storage backend as primary storage. This is an enterprise feature.

cc @DeepDiver1975 Is this correct?

**Comment by crewshin** [comment]
Ah I see. Thanks guys!
