### ISSUE TITLE
Loading indicator in share drop down overlaps border

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#15522]
introduced with #15235

![bildschirmfoto von 2015-04-09 19-14-29](https://cloud.githubusercontent.com/assets/245432/7072466/f896ffa0-deec-11e4-8467-ce64ed4d004e.png)

cc @jancborchardt

**Comment by jancborchardt** [comment]
Ah, it should be inside the input field on the right. Self-assigning.

**Comment by jancborchardt** [comment]
Fix at https://github.com/owncloud/core/pull/15528 :)
