### ISSUE TITLE
No Login if Database full

### ISSUE THREAD

**Issue by zanglerecke** [owncloud/core#15525]
I just encounterd some trouble to login, but no error or something. 

-> Problem was, my Disk was full (another Process wrote its log to the end of space, NOT OC)

BUT, it looked like that my Password is not correct, as i put it in,
so it may be possible to give a tiny pice of information to the User, like (There is a Problem with the Installation, your administrator will check for it)

**Comment by nickvergessen** [comment]
well I guess we can not write the session file if the disc is full.
Not a lot we can do about.

**Comment by DeepDiver1975** [comment]
> Not a lot we can do about.

indeed

**Comment by zanglerecke** [comment]
true ;(

but .... i also have no idea
