### ISSUE TITLE
Filtering for mimetypes in filepicker dialog does not work

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#15526]
So what I did was:

```js
OC.dialogs.filepicker(
	t('files_drop', 'Choose the folder to store files uploaded with File Drop'),
    OCA.Files_Drop.savePath,
    false,
    'httpd/unix-directory',
    true
);
```

Which fires a request to `/index.php/apps/files/ajax/list.php?dir=&mimetypes=%5B%22httpd%2Funix-directory%22%5D`, so the JS part is completely fine, but let's take a look at the endpoint: https://github.com/owncloud/core/blob/43b503641c9f3cc705f4a5c318c4122d00f8940a/apps/files/ajax/list.php

There is simply no filter at all for the mimetype, the whole parameter is unused :see_no_evil:

This is caused by the fact that in previous ownCloud versions, such as ownCloud 6, `rawlist.php` was called which indeed had a mimetype filter: https://github.com/owncloud/core/blob/231bc00a501f1ab9cea67b4d9fa6a87f1a1a7c30/apps/files/ajax/rawlist.php#L12-L17

From my PoV this is a regression introduced with https://github.com/owncloud/core/pull/6968's https://github.com/owncloud/core/commit/0be9de5df558232e12e2f582af5d08e1f488ba90, so ~~since Oct. 28 2013~~ Apr 4, 2014 broken and nobody really cared :see_no_evil:

<hr/>
X-Post from https://github.com/owncloud/files_drop/issues/40#issuecomment-91480081

**Comment by libasys** [comment]
https://github.com/owncloud/core/issues/11563

**Comment by DeepDiver1975** [comment]
Thanks @libasys - can you submit your changes as pull request please? THX
