### ISSUE TITLE
request - see users Quota Consumption in user panel

### ISSUE THREAD

**Issue by Froster** [owncloud/core#15529]
Hi,

it should be able to see the consumption from every user in the user Panel to Monitor if a user get's a full space.

kindly

**Comment by nickvergessen** [comment]
Yeah mean in the admin overview?

**Comment by Froster** [comment]
Maybe depends on ..

if the info could get from the db and the user Panel could be sorted or so in the user Panel would also be an Option.

but if the user Panel would be slower or couldn't be sorted it should be better to have an own list fort it.

**Comment by RealRancor** [comment]
Hi,

i think this functionality is already provided by some 3rdparty apps:

https://apps.owncloud.com/content/show.php/Storage+Charts+2?content=165528
https://apps.owncloud.com/content/show.php/Storage+Usage+%2B+Activity+Charts?content=166746

**Comment by LukasReschke** [comment]
Dupe https://github.com/owncloud/core/issues/12998

**Comment by Froster** [comment]
@LukasReschke Steps 5 in #12998 ?

**Comment by LukasReschke** [comment]
Yes. The whole category of "User quota usage (#12602)", especially step 5. This will happen soonest with ownCloud 8.2 but depending on other factors can also happen later ;-)
