### ISSUE TITLE
Optimize load times of images & icons

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#15531]
It would be good to reduce the number of HTTP requests necessary to load the icons. Currently every icon is its own file.

We could and should optimize that by putting the SVG and PNG icons into a sprite. We can use http://iconizr.com for that.

cc @owncloud/designers

**Comment by libasys** [comment]
Better way: https://github.com/owncloud/core/issues/1146#issuecomment-99739453

**Comment by MorrisJobke** [comment]
I really like the idea of the icons within a font. Then we automatically fix our problem with changing the color of the menu to a light one, without fixing all the icons out there again.

**Comment by MorrisJobke** [comment]
Thanks @libasys for the pointer :)

**Comment by libasys** [comment]
yes that's the idea, and we have the unicode of a icon to work with displaying icons on a placeholder input, textarea fields!

**Comment by jancborchardt** [comment]
Before considering a big change such as moving to an icon font just for the reason of being able to change the color, see https://css-tricks.com/icon-fonts-vs-svg/

(We can change the color just as easily with SVG – the _only_ problem is that we can not do that for the PNG fallback for IE8.)

**Comment by MorrisJobke** [comment]
> (We can change the color just as easily with SVG – the only problem is that we can not do that for the PNG fallback for IE8.)

Didn't we want to drop IE8 support soon?

**Comment by PVince81** [comment]
Icons in a font can be really painful in some cases from my experience a few years ago (alignment with text, etc), and also complicated to add into font files (unless there are better tools nowadays)

But I'd rather avoid it and go with a sprite sheet instead.

**Comment by libasys** [comment]
@PVince81 this tool is easy to use to add svg to font:
http://fontello.com/
on css you have fallback like:
```
@font-face {
  font-family: 'fontello';
  src: url('../font/fontello.eot?62379790');
  src: url('../font/fontello.eot?62379790#iefix') format('embedded-opentype'),
       url('../font/fontello.woff?62379790') format('woff'),
       url('../font/fontello.ttf?62379790') format('truetype'),
       url('../font/fontello.svg?62379790#fontello') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

**Comment by DeepDiver1975** [comment]
> @PVince81 this tool is easy to use to add svg to font:
> http://fontello.com/

the question is what happens that day when http://fontello.com/ doesn't exist any more?

Yes - that are open source - but still this would add another dependency with respect to the dev toolkit.

In addition: just imaging what needs to be don if we want to change one icon: we need to fully regenerate the font and upload this one to github. For sure more steps then simply replacing the svg.

**Comment by karlitschek** [comment]
@morrisjobke ie8 is still supported. just check how many people still use it out there :-/

**Comment by MorrisJobke** [comment]
> @morrisjobke ie8 is still supported. just check how many people still use it out there :-/

for reference #15567 ... at one point in time we need to drop it. The only system it is able to run on is already over a full year in the end of life cycle. ;) I Give this decision to @MTRichards and hopefully we can drop it in 8.3 or 8.4 :see_no_evil:

**Comment by Henni** [comment]
Do we actually want to create an icon sprite?
I think using icon sprites would break some functionality like icons in the navigation.
This would need some (maybe dirty) workaround.

Additionally the (hopefully soon) adoption of HTTP/2 should reduce the impact of image sprites.

**Comment by jancborchardt** [comment]
@Henni can you explain why it would break that? You mean because the background image is on the left and everything right of the icon would show? I think that's what background-size is for, although that is not available in IE I believe. So yeah, good question.

**Comment by Henni** [comment]
@jancborchardt are you actually able to crop with background-size? I thought that only scaling is possible.

I'm just not sure whether image sprites may become a bad practice as soon as we have the capabilities of HTTP/2. I definitely see the current performance improvements by sprites but I don't think that this is worth the extra workarounds when you want to use the icons in different settings.

For example the star icon could be used in the navigation and in another place as a button to mark a task. In the navigation it would be used as a background-image from the sprite while for a button it should be embedded in the html as an image tag for accessibility. This may lead to two separate requests for the same image therefore canceling the effect of the image sprite.

**Comment by PVince81** [comment]
Now that support for old IE versions was dropped, it might be possible to use sprite sheets more efficiently with CSS that crops + scale.

Might make it more difficult to theme though, as theme developers would need to take the original sprite sheet and insert their own icons into it.

**Comment by PVince81** [comment]
On the other hand now we only have SVGs and no PNG fallbacks, and SVGs don't work on sprite sheets AFAIK. Closing.
