### ISSUE TITLE
Synchronized shared parent folder

### ISSUE THREAD

**Issue by procsik** [owncloud/core#15547]
Hello!
I think the problem will go into version 1.8.

User "A" to share a folder the user "B" without the right to delete. User "B" removes the attached files in a directory - the files are restored (synchronized) - good. But if the user deletes the parent folder, it will not be restored, and in addition stop sharing the user "A".

I think it is better to shared folders also synchronized after "accidentally" deleted, as well as files. And immediately disable file sharing could only user "A". Thank U!

**Comment by karlitschek** [comment]
please reopen this in the client repository. Thanks
