### ISSUE TITLE
Upgrade oc 7.x -> 8.0.2 eror

### ISSUE THREAD

**Issue by heavymanto** [owncloud/core#15540]
Hi, in updating procedure hi have this error, can i do?

thx

![screenshot 543](https://cloud.githubusercontent.com/assets/6449169/7090254/0ad03b40-dfa2-11e4-885d-aa7d1abd5d75.png)

**Comment by nickvergessen** [comment]
See https://github.com/owncloud/core/issues/13980#issuecomment-73511661 + following comments
