### ISSUE TITLE
Icon of Desktop Client / Gray Border

### ISSUE THREAD

**Issue by danielkraffner** [owncloud/core#15557]
The "Green-Tick-Icon" of the Desktop-Client seems to have a grayish border around it. (1.8.0 build 4893)

See Screenshot:

![image](https://cloud.githubusercontent.com/assets/5311744/7107403/dc8b1b1e-e164-11e4-9c30-c135842b08cf.png)

Nothing Critical, just grinds my gears everytime I see it :)

**Comment by MorrisJobke** [comment]
@danielkraffner Please reopen in the client bug tracker https://github.com/owncloud/client/issues

This is the server component of ownCloud. Thanks :)

**Comment by karlitschek** [comment]
@jancborchardt

**Comment by danielkraffner** [comment]
Reopened in Client Issues: https://github.com/owncloud/client/issues/3105
