### ISSUE TITLE
Desktop client can't sync large files - Internal Server Error

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#15550]
#### Expected behaviour

Big files should be able to upload without getting Internal Server Errror.

#### Actual behavior

I have to upload them to WebUI to get it working. The Client stops syncing the file due to some chunking error. Please see log for more info.

#### Steps to reproduce

1. Upload file to a folder that sync with ownCloud.
2. See what happens

#### PHP.ini
```
; Maximum amount of memory a script may consume (128MB)
; http://php.net/memory-limit
memory_limit = 512M
```

#### Logs

**Sync log**
```
2015-04-11 22:46Wordpress VMDK/Wordpress_www.en0ch.se.rar                       ownCloud       Objektet kunde inte synkas på grund av tidigare fel: Error downloading https://en0ch.se/remote.php/webdav/Wordpress VMDK/Wordpress_www.en0ch.se.rar-chunking-1690968986-177-100 - server replied: Internal Server Error          
2015-04-11 22:37DirektUppladdning/Bilder övrigt/make money.png                  ownCloud       Uppladdad      29 KiB    
2015-04-11 21:03Wordpress VMDK/Wordpress_www.en0ch.se.rar                       ownCloud       Error downloading https://en0ch.se/remote.php/webdav/Wordpress VMDK/Wordpress_www.en0ch.se.rar-chunking-1690968986-177-176 - server replied: Internal Server Error884 MiB   
2015-04-11 20:55Wordpress VMDK/Wordpress_www.en0ch.se                           ownCloud       Raderad                  
2015-04-11 20:54Wordpress VMDK/Wordpress_www.en0ch.se/Wordpress_www.en0ch.se-flat.vmdkownCloud       Den lokala filen togs bort under synkronisering.20 GiB    
2015-04-11 20:45Wordpress VMDK/Wordpress_www.en0ch.se/Wordpress_www.en0ch.se.vmxfownCloud       Uppladdad      277 B     
2015-04-11 20:45Wordpress 
``` 
**owncloud.log**
```
Error	PHP	Allowed memory size of 536870912 bytes exhausted (tried to allocate 5251072 bytes) at /var/www/owncloud/lib/private/files/storage/local.php#161	2015-04-11T20:38:47+00:00
Error	PHP	Allowed memory size of 536870912 bytes exhausted (tried to allocate 5251072 bytes) at /var/www/owncloud/lib/private/files/storage/local.php#161
Error	PHP	Allowed memory size of 536870912 bytes exhausted (tried to allocate 5251072 bytes) at /var/www/owncloud/lib/private/files/storage/local.php#161	2015-04-11T19:03:08+00:00
Error	PHP	Undefined index: /var/www/owncloud/data/[user]/files/Ny mapp at /var/www/owncloud/apps/files_locking/lib/lockingwrapper.php#140	2015-04-11T18:41:19+00:00
```
**error.log**
```
[Sat Apr 11 19:24:19.010517 2015] [mpm_prefork:notice] [pid 1538] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.7 OpenSSL/1.0.1f configured -- resuming normal operations
[Sat Apr 11 19:24:19.010557 2015] [core:notice] [pid 1538] AH00094: Command line: '/usr/sbin/apache2'
[Sat Apr 11 21:03:08.552415 2015] [:error] [pid 2717] [client 192.168.1.1:58472] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 5251072 bytes) in /var/www/owncloud/lib/private/files/storage/local.php on line 161
[Sat Apr 11 21:04:22.706001 2015] [:error] [pid 2713] [client 192.168.1.1:58776] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 5251072 bytes) in /var/www/owncloud/lib/private/files/storage/local.php on line 161
[Sat Apr 11 22:38:47.880196 2015] [:error] [pid 3065] [client 192.168.1.1:59223] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 5251072 bytes) in /var/www/owncloud/lib/private/files/storage/local.php on line 161
[Sat Apr 11 23:26:37.329515 2015] [access_compat:error] [pid 3964] [client 127.0.0.1:52203] AH01797: client denied by server configuration: /var/www/owncloud/data/htaccesstest.txt
```

### Server configuration on both servers

Ubuntu Server 14.04

**Database:**
Server version: 5.5.41-0ubuntu0.14.04.1 - (Ubuntu)
**PHP version:**
PHP 5.5.9-1ubuntu4.5 (cli) (built: Oct 29 2014 11:59:10)

**ownCloud version:** (see ownCloud admin page)
8.0.2
**Are you using encryption: yes/no**
No

### Client configuration

**Browser:**
Chrome 
**Operating system:**
Windows 8.1
**Sync Client**
1.8 stable
**Mobile app*
Android 1.7.1

**Comment by enoch85** [comment]
Opened it here before: https://github.com/owncloud/client/issues/3101

**Comment by RealRancor** [comment]
Hi,

seems you're hitting the memory limit of your configured 512 MB:

> Allowed memory size of 536870912

536870912 / 1024 / 1024 = 512 MB.

https://doc.owncloud.org/server/8.0/admin_manual/configuration_files/big_file_upload_configuration.html

says something about memory related errors when output_buffering is not set to 0. Have you checked this?

**Comment by VincentvgNn** [comment]
Hi,
I use server 8.0.2 and client 1.8.0.4938-nightly20150411 on Win 8.1.
Using the file ownCloud-1.8.0.4938-nightly20150411-setup.exe (38 MB) as a test file, I see during upload the same "......Error downloading..........Internal server" error reported in the "Sync Activity". Pushing "Retry Sync" is needed to restart the syncing. After some patience I get the file synced between the 2 clients that are working in a directory that has been shared to these 2 clients by the admin.
My server is installed at a webhost where the PHP memory_limit is set to 256 MB.

**Comment by RealRancor** [comment]
@VincentvgNn 
As you havn't posted any related logfiles its not even sure if your problem is even related to this issue.

**Comment by enoch85** [comment]
@RealRancor Yes,I followed that guide when I configured my `upload_max` and the other values. Only solution as I see it is to increase `max_upload` as well to 16GB, but that's a bad workaround.

I mean this should be enough: https://www.en0ch.se/owncloud_/increase-max-file-size/

Have I missed something here?

**Comment by emilnikkhah** [comment]
I have the same problem syncing 16GB file from desktop. How much mem should I allocate to PHP.
I have set max_upload 20GB in both Owncloud and php.

Error	PHP	Allowed memory size of 536870912 bytes exhausted (tried to allocate 5251072 bytes) at /var/www/owncloud/lib/private/files/storage/local.php#161	2015-04-14T13:42:57+00:00
Error	PHP	Undefined index: /var/www/owncloud/data/fremantle/files/Documents at /var/www/owncloud/apps/files_locking/lib/lockingwrapper.php#140	2015-04-14T11:55:42+00:00
Error	PHP	Undefined index: /var/www/owncloud/data/fremantle/files/Photos at /var/www/owncloud/apps/files_locking/lib/lockingwrapper.php#140	2015-04-14T11:55:40+00:00

**Comment by VincentvgNn** [comment]
@RealRancor @enoch85 
I wouldn't be surprised that in OC similar phenomena have a different root cause.
I get this similar looking issue when my connection to the webhost get's (temporarily?) throttled down to less than about 100 KB/s. I have seen upload speeds between 10 KB/s to over 1 MB/s. On top of that the connection with the server will be interrupted about every 5 minutes.
Chuncks of 5 MB are getting in the clients cache on the server. There are often much more chunks than there would be needed. Unsuccessful chunks are not always cleaned up. For these tests I delete them each time manually.

I did a test with 3 the same 38 MB files with a different name:
```
- file 2: ownCloud-1.8.0.4938-nightly20150411-setup-2.exe
- file 3: ownCloud-1.8.0.4938-nightly20150411-setup-3.exe
- file 4: ownCloud-1.8.0.4938-nightly20150411-setup-4.exe
```

1. After some retries I got file 2 uploaded successfully. There were no remaining chunks in the servers cache.
2. For file 3 I limited the upload speed at the client to 100 KB/s. From that test a lot of chunks, all with the index "0" remained in the cache. After a while I stopped the speed throttling at the client and after  some retries and start/stops I could get that file uploaded as well.
3. 
For file 4 I did not use the local speed throttling. 
Nevertheless I could not get that file uploaded. Chunks with the index 0-4 remained in the cache.
The system could not continue after chunk 4.

Here is the client sync log:
```
14-4-2015 14:49:19Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-4.exe "folder name" The item is not synced because of previous errors: Error downloading https://www."domainname"/owncloud/remote.php/webdav/Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-4.exe-chunking-3931681040-8-4 - server replied: Internal Server Error          
14-4-2015 14:48:05Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-4.exe "folder name" Error downloading https://www."domainname"/owncloud/remote.php/webdav/Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-4.exe-chunking-3931681040-8-4 - server replied: Internal Server Error37 MiB    
14-4-2015 14:47:01Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-4.exe "folder name" Error downloading https://www."domainname"/owncloud/remote.php/webdav/Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-4.exe-chunking-3931681040-8-4 - server replied: Internal Server Error37 MiB    
14-4-2015 14:45:33Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-4.exe "folder name" Error downloading https://www."domainname"/owncloud/remote.php/webdav/Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-4.exe-chunking-3931681040-8-4 - server replied: Internal Server Error37 MiB    
14-4-2015 14:44:24Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-4.exe "folder name" Error downloading https://www."domainname"/owncloud/remote.php/webdav/Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-4.exe-chunking-3931681040-8-4 - server replied: Internal Server Error37 MiB    
14-4-2015 14:41:41Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-4.exe "folder name" Error downloading https://www."domainname"/owncloud/remote.php/webdav/Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-4.exe-chunking-3931681040-8-3 - server replied: Internal Server Error37 MiB    
14-4-2015 14:40:35Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-4.exe "folder name" Error downloading https://www."domainname"/owncloud/remote.php/webdav/Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-4.exe-chunking-3931681040-8-3 - server replied: Internal Server Error37 MiB    
14-4-2015 14:39:28Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-4.exe "folder name" Error downloading https://www."domainname"/owncloud/remote.php/webdav/Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-4.exe-chunking-3931681040-8-3 - server replied: Internal Server Error37 MiB    
14-4-2015 14:38:37Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-4.exe "folder name" Error downloading https://www."domainname"/owncloud/remote.php/webdav/Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-4.exe-chunking-3931681040-8-3 - server replied: Internal Server Error37 MiB    
14-4-2015 14:36:19Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-4.exe "folder name" Error downloading https://www."domainname"/owncloud/remote.php/webdav/Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-4.exe-chunking-3931681040-8-1 - server replied: Internal Server Error37 MiB    
14-4-2015 14:35:28Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-4.exe "folder name" Error downloading https://www."domainname"/owncloud/remote.php/webdav/Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-4.exe-chunking-3931681040-8-1 - server replied: Internal Server Error37 MiB    
14-4-2015 14:34:16Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-4.exe "folder name" Error downloading https://www."domainname"/owncloud/remote.php/webdav/Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-4.exe-chunking-3931681040-8-1 - server replied: Internal Server Error37 MiB    
14-4-2015 14:32:25Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-4.exe "folder name" Error downloading https://www."domainname"/owncloud/remote.php/webdav/Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-4.exe-chunking-3931689746-8-0 - server replied: Internal Server Error37 MiB    
14-4-2015 14:24:42Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-3.exe "folder name" Uploaded       37 MiB    
14-4-2015 14:18:56Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-3.exe "folder name" Error downloading https://www."domainname"/owncloud/remote.php/webdav/Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-3.exe-chunking-3931682208-8-0 - server replied: Internal Server Error37 MiB    
14-4-2015 14:15:43Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-3.exe "folder name" Error downloading https://www."domainname"/owncloud/remote.php/webdav/Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-3.exe-chunking-3931681604-8-0 - server replied: Internal Server Error37 MiB    
14-4-2015 14:14:00Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-3.exe "folder name" Error downloading https://www."domainname"/owncloud/remote.php/webdav/Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-3.exe-chunking-3931678057-8-0 - server replied: Internal Server Error37 MiB    
14-4-2015 14:12:45Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-3.exe "folder name" Error downloading https://www."domainname"/owncloud/remote.php/webdav/Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-3.exe-chunking-3931674796-8-0 - server replied: Internal Server Error37 MiB    
14-4-2015 14:09:54Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-3.exe "folder name" Error downloading https://www."domainname"/owncloud/remote.php/webdav/Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-3.exe-chunking-3931686201-8-0 - server replied: Internal Server Error37 MiB    
14-4-2015 14:08:04Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-3.exe "folder name" Error downloading https://www."domainname"/owncloud/remote.php/webdav/Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-3.exe-chunking-3931686646-8-0 - server replied: Internal Server Error37 MiB    
14-4-2015 13:59:16Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-2.exe "folder name" Uploaded       37 MiB    
14-4-2015 13:57:33Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-2.exe "folder name" Error downloading https://www."domainname"/owncloud/remote.php/webdav/Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-2.exe-chunking-3931674030-8-6 - server replied: Internal Server Error37 MiB    
14-4-2015 13:54:34Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-2.exe "folder name" Error downloading https://www."domainname"/owncloud/remote.php/webdav/Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-2.exe-chunking-3931674030-8-2 - server replied: Internal Server Error37 MiB    
14-4-2015 13:53:27Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-2.exe "folder name" Error downloading https://www."domainname"/owncloud/remote.php/webdav/Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-2.exe-chunking-3931674030-8-2 - server replied: Internal Server Error37 MiB    
14-4-2015 13:51:58Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-2.exe "folder name" Error downloading https://www."domainname"/owncloud/remote.php/webdav/Test Fat32 + sharing/ownCloud-1.8.0.4938-nightly20150411-setup-2.exe-chunking-3931674030-8-2 - server replied: Internal Server Error37 MiB    
```

The resulting chunks are:
![owncloud server cache with bad chunks](https://cloud.githubusercontent.com/assets/7522929/7138422/9e7bd072-e2c0-11e4-9b3a-f0b66fc0c04e.jpg)

**Comment by shanecentre** [comment]
I've seen the same issue

Ubuntu 14.04, (VM with 16GB RAM and 4vCPU) ownCloud 8.0.2, Active Directory for auth, Openstack swift (Juno) mounted to the file system using S3QL for storage.

Files @1G or over cause the following memory exhaustion error. The files completely uploads in chunks to the cache folder of the account and as some point when it is being resembled the error occurs.  Files I've tested under 1G all seem to work without issue.

From apache error log:
PHP Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 5251072 bytes) in /var/www/owncloud/lib/private/files/storage/local.php on line 161

From owncloud log:
{"reqId":"0da0475d3efdc540812c7f1c91b1b229","remoteAddr":"10.21.1.253","app":"PHP","message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 5251072 bytes) at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#161","level":3,"time":"2015-04-14T18:09:07+00:00"}

My php.ini settings are as follows:
max_execution_time = 3600
max_input_time = 3600
memory_limit = 2048M
post_max_size = 2048M
upload_max_filesize = 2048M
max_file_uploads = 20
default_charset = UTF-8

**Comment by jorgedferreira** [comment]
No update for this? I'm having to reboot my server because of owncloud from time to time. THIS SUCKS!
I have other services in that VPS (8GB ram tbw) and i cant be having to reboot it.
No extreme syncing is going on, for the past few days about 30 small < then 1mb files have been added and still i needed to restart bind and got no shared memory available error.

Please, please, please, any new for this? some fix? I want to use the software but like this i can't.

Thanks in advance

**Comment by AlektroNik** [comment]
Resolved
1. Close and stop completely ownCloud
2. Go to the root of the synchronized folder. For example, D:\ownCloud.
3. For Win7 - <Alt> -> Tools -> Folder Options -> View -> Show hidden files, folders and drives
4. Remove all files starting with a dot ". *". For example, .csync_journal.db and .owncloudsync.log.
5. Run ownCloud

**Comment by jorgedferreira** [comment]
Hi, thanks for your comment, but does that relate to the server issues or only the client one?

**Comment by AlektroNik** [comment]
Hi, only the client one.

**Comment by enoch85** [comment]
Seems to have the same problem on server side. Trying to upload an 8GB file results in "Internal Server Error" as a yellow notice, and no errors in log with loglevel 3. 

I have 16GB as max_upload and followed this guide: https://doc.owncloud.org/server/7.0/admin_manual/configuration/big_file_upload_configuration.html

**Comment by RealRancor** [comment]
Have you checked other logfiles like the one of PHP or your webserver? An internal server error should be definitely logged.

**Comment by csware** [comment]
I'm also experiencing this issue and this issue can cause severe data loss (as I experienced today)!

First files are not uploaded correctly (a lot of big files are truncated; for some files just a few 100 MB are missing, for others the file in OC is 8 MB, but the original file is 2.7 GB).

Second: Someone moves files around locally. Then the correct large files get deleted locally and the new (truncated) files get downloaded to all clients (also for the client on which the not-truncated files were located).

**Comment by kenjiru** [comment]
I have the same issue with files larger than 1GB.

**Comment by guruz** [comment]
@csware @kenjiru Which server versions?

@kenjiru for upload?

**Comment by csware** [comment]
I was using the latest release at the time (IIRC 8.0.x)

**Comment by enoch85** [comment]
2015-09-08 22:08:07Interstellar.2014.1080p.BluRay.x264-DAA.mkv                     S:\Client                     Continue blacklisting: Error downloading https://en0ch.se/remote.php/webdav/Interstellar.2014.1080p.BluRay.x264-DAA.mkv-chunking-3221492446-2911-2910 - server replied: Locked (Target file  is locked by another process.)15 GB     
2015-09-08 22:06:56Interstellar.2014.1080p.BluRay.x264-DAA.mkv                     S:\Client                     Error downloading https://en0ch.se/remote.php/webdav/Interstellar.2014.1080p.BluRay.x264-DAA.mkv-chunking-3221492446-2911-2910 - server replied: Locked (Target file  is locked by another process.)15 GB     
2015-09-08 22:05:02Interstellar.2014.1080p.BluRay.x264-DAA.mkv                     S:\Client                     Anslutningen avbröts på grund av timeout15 GB     
2015-09-08 21:22:46Interstellar.2014.1080p.BluRay.x264-DAA.mkv                     S:\Client                     Det går inte att komma åt filen eftersom den
används av en annan process.15 GB

**Comment by enoch85** [comment]
Just an update: Uploaded a 9 GB file (16 GB max upload) in ownCloud GUI (8.1.1) with this error in owncloud.log:

```
Error	files	Upload error: 7 - Failed to save to disk
```

Upload via Client 2.0.1 also produce some errors:

```
2015-09-08 22:08:07Interstellar.2014.1080p.BluRay.x264-DAA.mkv S:\Client Continue blacklisting: Error downloading https://en0ch.se/remote.php/webdav/Interstellar.2014.1080p.BluRay.x264-DAA.mkv-chunking-3221492446-2911-2910 - server replied: Locked (Target file is locked by another process.)15 GB

2015-09-08 22:06:56Interstellar.2014.1080p.BluRay.x264-DAA.mkv S:\Client Error downloading https://en0ch.se/remote.php/webdav/Interstellar.2014.1080p.BluRay.x264-DAA.mkv-chunking-3221492446-2911-2910 - server replied: Locked (Target file is locked by another process.)15 GB

2015-09-08 22:05:02Interstellar.2014.1080p.BluRay.x264-DAA.mkv S:\Client Connection aborted due to timeout15 GB
```

**Comment by PVince81** [comment]
@enoch85 maybe a rogue background scan ?
Try setting "filesystem_check_changes" to 0 in config.php.
Another thing to try: disable the "files_locking" app.

**Comment by PVince81** [comment]
but ideal is upgrading to 8.1.3 and enable transactional file locking (https://doc.owncloud.org/server/8.1/admin_manual/configuration_files/files_locking_transactional.html) or 8.2rc1 where it's enabled by default.

(it's another, better kind of locking)

**Comment by enoch85** [comment]
I'll try with 8.2 stable when it comes out.

I really hope that it's a locking issue.

Best Regards
Daniel Hansson

www.en0ch.se

Sent from OnePlus Two, sorry for typos.

**Comment by enoch85** [comment]
Tested  on a newly installed server (8.1.3) with one 12 GB file and one 9 GB file. Uploaded through client `Version 2.0.2-nightly20151008 (build 5525)`, 9 GB file = no issues. 12 GB file = client responded "Connection aborted due to timeout" (directly translated from Swedish), but were uploaded anyway when I looked in the server GUI.

I then deleted all the files and tried to upload the 12 GB file from the server GUI = Not uploaded. 

I used the settings in this guide: https://www.en0ch.se/increase-max-file-size/

Will do further tests in 8.2. 

cc @PVince81 @guruz

**Comment by RealRancor** [comment]
@enoch85 Maybe also have a look at https://github.com/owncloud/documentation/wiki/Uploading-files-up-to-16GB

**Comment by guruz** [comment]
FYI, this is what we from the client side think needs to be done to reliable support big file uploads for arbitrary storage backends: https://github.com/owncloud/core/issues/12097
FYI @ogoffart @dragotin

**Comment by enoch85** [comment]
@RealRancor Regarding the PHP stuff, it's exactly what I wrote in my guide as well. Other than that, he runs Nginx and I run Apache. Thanks for the advice anyway.

**Comment by RealRancor** [comment]
@enoch85 I haven't compared both tutorials. Just was an additional reference for you

**Comment by pierrejochem** [comment]
Webserver: Apache?
What is the content of .htaccess?

**Comment by enoch85** [comment]
It seems to be solved with Server 8.2 and Client 2.0.2 + I added a upload_tmp dir. Seems like my regular tmp got full when I uploaded big files. 

I'll close this now, feel free to reopen.

**Comment by fritzmg** [comment]
I am trying to upload a large file (~8GiB) - but ownCloud seems to require a huge amount of memory:
```
{"reqId":"…","remoteAddr":"…","app":"PHP","message":"Allowed memory size of 1073741824 bytes exhausted (tried to allocate 5251072 bytes) at …/lib/private/files/storage/local.php#179","level":3,"time":"2016-01-30T19:49:57+00:00"}
```
It's a root server, so I can easily set the memory limit higher - but is it really necessary to have such a large memory limit when you need to transfer large files to/from the ownCloud?

**Comment by PVince81** [comment]
@fritzmg it shouldn't, unless you are uploading to some buggy external storages.
There were also reports that some php5-fpm configs might result in the web server or PHP storing the file into memory before passing it to ownCloud.

**Comment by fritzmg** [comment]
It's not an external storage and ownCloud runs as an Apache Module (PHP 5.4.39). 

(I couldn't get ownCloud on my server with (Fast)CGI to upload any kind of large file, no matter what I tried.)

**Comment by PVince81** [comment]
@fritzmg I can't help you further. All I can tell you is that OC doesn't store files in memory so it might be a side-effect of your env config, or third party apps.
You might have more luck asking in the forums, see http://owncloud.org/support

**Comment by pierrejochem** [comment]
Apache Settings okay? PHP Settings Okay? 32 or 64 Bit Version of PHP?

**Comment by fritzmg** [comment]
> Apache Settings okay? PHP Settings Okay? 32 or 64 Bit Version of PHP?

As per @PVince81 suggestion, I created a thread on the ownCloud forum: https://forum.owncloud.org/viewtopic.php?f=36&t=32818
I have listed all the settings there. They are all set to the recommended values as defined in [this article](https://doc.owncloud.org/server/8.0/admin_manual/configuration_files/big_file_upload_configuration.html).

However, as I mentioned in that thread, that article also states:

> Please see the manual of your webserver for how to configure those values correctly:

without exactly telling what values these settings should be set to. In both cases (_LimitRequestBody_ and _SSLRenegBufferSize_) the values are at their respective defaults as described in the Apache documentation.

The 64-Bit version of PHP is in use for the ownCloud installation (confirmed by `echo PHP_INT_SIZE;` for example).

**Comment by RealRancor** [comment]
> without exactly telling what values these settings should be set to

A documentation of a web application can't and shouldn't give exact values of such webservers options. Some environments might need higher, other lower values. If unsure raise it to the highest possible value and then lower it until it breaks again.

**Comment by fritzmg** [comment]
> Some environments might need higher, other lower values.

Well, what does it depend on then?

_LimitRequestBody_ is already set to _0 (= unlimited)_ - I'll try setting _SSLRenegBufferSize_ to something much higher.

**Comment by RealRancor** [comment]
Both settings are not causing a Allowed memory size of 1073741824 bytes exhausted message, only stuff like "connection closed/operation cancelled" and similar.

**Comment by fritzmg** [comment]
> Both settings shouldn't causing a Allowed memory size of 1073741824 bytes exhausted message, only stuff like "connection closed/operation cancelled" and similar.

That's what I though as well. As far as I can see, the server, plus the PHP environment is properly configured - yet the error still occurs.

Looking at [lib/private/files/storage/local.php#L179](https://github.com/owncloud/core/blob/v8.2.2/lib/private/files/storage/local.php#L179) ownCloud retrieves data via
```php
file_get_contents(…);
```
According to the [documentation](http://php.net/manual/en/function.file-get-contents.php)

> it will use memory mapping techniques if supported by your OS to enhance performance,  

but I am not sure this really means that `file_get_contents` loads the file out-of-core. Most stackoverflow results for memory issues with `file_get_contents` seem to suggest, that it does _not_ load the file out-of-core and thus you should refrain from using it to load large files. But I haven't found anything definitive yet.

**Comment by fritzmg** [comment]
Looking at [php/php-src/blob/PHP-5.4.39/ext/standard/file.c#L514](https://github.com/php/php-src/blob/PHP-5.4.39/ext/standard/file.c#L514) I don't see any evidence, that files are loaded out-of-core this way - so if `OC\Files\Storage\Local::file_get_contents` retrieves a file larger than the `memory_limit`, it will run out of memory. I am assuming thouhg, that this function usually does get to load large files like that?

**Comment by bcutter** [comment]
I recently see a lot of those errors in owncloud.log:

```
Allowed memory size of 536870912 bytes exhausted (tried to allocate 3215851560 bytes) at /var/www/owncloud/lib/autoloader.php#183
```
I don´t know when or why it starts, especially file sync works fine. But everything else on the system (Raspberry Pi 2) stops working like Webmin or SSH.

Why does Owncloud want to allocate about 3 GB (!!!) of memory (where only 1 GB physically exists, no swap partition) for a 524 KB file??? I did NOT try to sync a large file.

**Comment by guruz** [comment]
@bcutter Which version? I remember this had been fixed in newer versions. If not please create a new issue. :)

**Comment by bcutter** [comment]
v9.0.2.2 - so pretty up 2 date

(because Update button not working... but that's another issue)
