### ISSUE TITLE
nodeExists always returns true for files coming from shared folder from federated clouds

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#15551]
### Env
Master or oC8, PHP 5.5
2 oC instances on the same server

### Steps to reproduce
* Share **read-only** folder on oC1 **which is running oC 8.0**
* Attach share folder to oC2
* Launch a script on oC2 which tests the presence of a specific file **which doesn't exist** on oC1

Log the result like this
```
$this->logger->debug("Folder: {path}", ['path' => $folder->getPath()]);
$this->logger->debug("nodeExists : {test}", ['test' => $folder->nodeExists('CallMeSartre')]);
```

### Expected result
```
Folder: \/demo1\/files\/Shared from oC1
nodeExists : false
```

### Actual result
```
Folder: \/demo1\/files\/Shared from oC1
nodeExists : true
```

The same test works perfectly well on local folders.

### Logs
This is from the sharing server on oC8.0

```
"Undefined index: permissions at \/apps\/files_sharing\/lib\/readonlycache.php#16"
"Undefined index: storage_mtime at \/lib\/private\/files\/cache\/watcher.php#67"
"Undefined index: permissions at \/apps\/files_sharing\/lib\/readonlycache.php#16"
"Undefined index: fileid at \/lib\/private\/files\/cache\/cache.php#378"
"Undefined index: mimetype at \/lib\/private\/files\/cache\/cache.php#379"
"Undefined index: mimetype at \/lib\/private\/files\/cache\/watcher.php#73"
"Undefined index: permissions at \/apps\/files_sharing\/lib\/readonlycache.php#16"
"Undefined index: permissions at \/apps\/files_sharing\/lib\/readonlycache.php#16"
"Undefined index: mimetype at \/lib\/private\/files\/fileinfo.php#106"
"Undefined index: fileid at \/lib\/private\/files\/fileinfo.php#99"
"Undefined index: mimetype at \/lib\/private\/files\/fileinfo.php#106"
"Undefined index: etag at \/lib\/private\/files\/fileinfo.php#127"
```

**Comment by oparoz** [comment]
I'm guessing @icewind1991 should know what's going on.

**Comment by PVince81** [comment]
For files ?

I vaguely remember that during a past debugging session I saw there's an `if` someone that checks if `$path === ''`, always return true to say that it exists. Which is valid for most storages except for remote shares.

**Comment by oparoz** [comment]
Yes, it's when checking for the existence of a file in a folder.

**Comment by oparoz** [comment]
Added some logs from the sharing server, which is on 8.0. It seems the cache is not returning anything for some of the files in that folder. Could be some encoding problem then.

**Comment by oparoz** [comment]
The webDAV endpoint does not answer properly to a PROPFIND request. It should raise an exception when it doesn't find the file and it does not.

**Comment by oparoz** [comment]
Found the problem.
This line corrupts the answer received from the cache:
https://github.com/owncloud/core/blob/master/apps/files_sharing/lib/readonlycache.php#L31
