### ISSUE TITLE
Could not automatically fix legacy storagae

### ISSUE THREAD

**Issue by jcallerykbi** [owncloud/core#15553]
Here is what owncloud said:
Updating ownCloud to version 8.0.2, this may take a while.

Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Updated "files_pdfviewer" to 0.7
Updated "user_ldap" to 0.5.0
Updated "activity" to 1.2.0
Updated "files_sharing" to 0.6.1
Updated "gallery" to 0.6.0
Could not automatically fix legacy storage "local::/var/www/owncloud/data/rshumate/" => "home::rshumate" because they both have data.
The update was unsuccessful. Please report this issue to the ownCloud community.

Please let me know what other information you want/need

**Comment by RealRancor** [comment]
Duplicate.

See https://github.com/owncloud/core/issues/13980#issuecomment-73511661 +following comments
