### ISSUE TITLE
Feature request: App Versions: Option to delete older versions

### ISSUE THREAD

**Issue by m-abs** [owncloud/core#15554]
I'd like an option for the files_version-app to delete old versions of the file.
Currently after 30 days one copy per week is kept, I'd like an option to make that zero, maybe after 60 days.

I've older versions of files that hasn't been changed in over a year. 
I can't imagine that I'll ever need to use these old versions, so I'd prefer that they were deleted.

**Comment by RealRancor** [comment]
Related: https://github.com/owncloud/core/issues/13232

**Comment by PVince81** [comment]
Since 8.2 there is a CLI tool to delete old versions and empty trashbins: https://github.com/owncloud/core/issues/9652

**Comment by PVince81** [comment]
Please have a look at the new settings in config.php to set a time limit: https://github.com/owncloud/core/blob/v8.2.2/config/config.sample.php#L439

It makes it possible to automatically delete versions older than X days.
