### ISSUE TITLE
conflicts dialog not usable on phones (mobile)

### ISSUE THREAD

**Issue by burkemw3** [owncloud/core#15552]
### Steps to reproduce
1. Go to an owncloud folder on an iPhone
2. Select 2 photos from the Camera Roll to upload together
3. Upload

### Expected behaviour

Conflict dialog should appear and be usable

### Actual behaviour

Conflict dialog appears, but it isn't usable. Much of the dialog is off the screen. Zooming does not work. Scrolling does not work. Turning the viewport to landscape or portrait shows a little bit more of the dialog in some ways, but never exposes the 'Cancel' and 'Continue' buttons.

### Server configuration
Witnessed on v7.0.1 (stable) and 8.0.2 (stable), the latter on [demo.owncloud.org](https://demo.owncloud.org).

### Client configuration

iOS v 7.1 Native Safari

(I think I also saw it on a Galaxy S3 on FireFox v 34.0.1)

### Additional information

This is particularly irritating when trying to upload multiple photos from iOS's Camera Roll. All of the photos have the same name (image) and are all detected as conflicts. There's no way to actually resolve the conflicts from the phone, though.

I did my best to look through past issues (searching for things like conflicts, dialogs, mobile, iPhone, and android), but I didn't find anything about this. #4766 is possibly the introduction of the current dialog. The lack of zooming on mobile (#15024) also inhibits function here.

### Screenshots

![horizontal](https://cloud.githubusercontent.com/assets/665792/7104270/c6036a7c-e0a1-11e4-95e4-9c64f389fe8c.jpg)
![vertical](https://cloud.githubusercontent.com/assets/665792/7104308/fcaa505c-e0a3-11e4-915c-739f50e5bea6.jpg)

**Comment by MorrisJobke** [comment]
@owncloud/designers Anybody who wants to look into this? Maybe @jancborchardt ?

**Comment by jancborchardt** [comment]
This is a bigger one … definitely only for 8.2 cc @butonic

**Comment by xMartin** [comment]
Just experienced this issue myself. Thanks for the report.

It would be such a great feature to just be able to send people a link to easily upload pictures from a mobile phone. Unfortunately just not possible currently.

**Comment by PVince81** [comment]
Duplicate of https://github.com/owncloud/core/issues/13102
