### ISSUE TITLE
Windows Client continuously discovering

### ISSUE THREAD

**Issue by roymcclure** [owncloud/core#15561]
I'm using the windows client version 1.8.0 (build 4893). Server is 8.0.2 stable running on lubuntu. After it's walked through the whole discovery process, it will succesfully sync all files (except one*) and then start again a few seconds later - even when I have set remotePollInterval=1000000 in the [general] tab of c:\users\roymcclure\appdata\local\owncloud\owncloud.cfg - thus consuming a big chunk of the cpu time.

* That file it always fails to sync throws an error message in the activity tab of the client: "Not able to upload this file because it is read-only on the server, restoring: Restoration failed: Error downloading .../not/especially/long/path/to/file/file.xml - server replied: Requested Range not satisfiable." I have  checked the permissions for that file in the server and they are just the same as all the others that are being synced correctly, read-write for the owner (www-data), read for the rest.

**Comment by MorrisJobke** [comment]
@roymcclure Please reopen this in the client issue tracker: https://github.com/owncloud/client/issues

This is the server component of ownCloud. Thanks :)

**Comment by roymcclure** [comment]
No problem
