### ISSUE TITLE
Internet Explorer support timeline

### ISSUE THREAD

**Issue by BernhardPosselt** [owncloud/core#15567]
At some point we need to think about deprecating older IE versions since the maintenance cost is too high. 

I think its possible to drop IE8 soon. I'd also advocate to drop IE9 support with it. 

8 is the classic company browser on XP, 10 is the newest possible version on 7 which is what most companies will likely migrate to. I think the issue is therefore more about what company Windows version we want to support and Vista is a very unpopular choice for that.

Some marketshare stats as of 13th of April:

| Area  | IE8%  | IE9%  | IE10% |
|---|---|---|---|
| [Europe](http://gs.statcounter.com/#browser_version_partially_combined-eu-monthly-201502-201502-bar)  | 1.89 | 1.69 | 1.26 | 
| [North America](http://gs.statcounter.com/#browser_version_partially_combined-na-monthly-201502-201502-bar)  | 5.29 | 3.24 | 2.65 |  
| [Global](http://gs.statcounter.com/#browser_version_partially_combined-ww-monthly-201502-201502-bar)  | 3.77 | 2.39 | 1.9 |   

@MorrisJobke @LukasReschke @PVince81 @DeepDiver1975 @nickvergessen @jancborchardt

**Comment by LukasReschke** [comment]
cc @MTRichards

**Comment by oparoz** [comment]
I think the focus should be on making oC work with IE11 first, before looking at anything else. "Pictures", which is the only app which ships with 8.0 doesn't work at all on IE.

**Comment by Raydiation** [comment]
@oparoz that's a different issue ;)

**Comment by oparoz** [comment]
Well, there are 2 aspects. IE support was dropped with the release of 8.0. So, there should be an effort to make it work again and at the same time, workaround code for IE8/9 should be removed.

**Comment by Raydiation** [comment]
I think you mistook dropping Windows IIS support for removing IE support. IE is still supported afaik

**Comment by LukasReschke** [comment]
Yes. We still officially support IE until 8… Well, "support"… it's not really that there are a lot of people actually testing it :see_no_evil:

**Comment by oparoz** [comment]
That's what I mean. People think it is still supported because nothing was said about dropping it, but in reality, oC contains components which don't run on it.

**Comment by Raydiation** [comment]
@oparoz different issue, thats a bug report for the pictures app

**Comment by oparoz** [comment]
@Raydiation - Nope, it's not the only app/component using EventSource and OC.EventSource is part of core. There might also be other polyfills in core as well.
But from my pov, even if it was isolated to that one app. It's part of the distribution. You can't claim IE compatibility and ship something which doesn't work on it. Might be fine for the community edition, but that's nonsense for a supported enterprise distribution. What could be done is split that app in 2 and only include the slideshow component which works fine on the Files side to get large previews of pictures, but that's for another ticket.

**Comment by Raydiation** [comment]
This thread has nothing to do with coding and more with issue management and all the loops that devs have to jump through to get CSS and JS code in: this is about making it possible to immediately close IE8 and 9 related rendering issues and being able to use newer CSS features like calc() when submitting PRs

Bugs related to IE compatibility are an entirely different problem and therefore need to be handled like every other bug. In your case open a ticket for eventsource related to IE which will be accepted because officially IE 10/11 is supported, so file a bug.

As for the JS API side: The JS api has no guarantee to be stable, only 1 function and the csrf token is officially documented, roll your own implementation that fixes this issue if you want to.

**Comment by oparoz** [comment]
> This thread has nothing to do with coding and more with issue management 

You're right, first define the policy, then perform an assessment, then fix according to the policy. The current non-written policy regarding IE is that it's not supported, despite what it says on the tin. Bugs are not fixed consistently. Releases are not tested on IE. Most apps don't support it.
Hopefully this ticket will provide a way forward for full compatibility and not just a way to decommission very old code.

From my pov, you should support IE11 only and perhaps IE10 if your support contracts tell you to.

> Bugs related to IE compatibility are an entirely different problem and therefore need to be handled like every other bug

In the current context, I'm not sure people see a point in reporting IE bugs, so yes, a new direction is needed, with some clear actions and not just words.
QA should have a clear mandate to test everything on all supported browsers and if you decide to ship something which is broken, it has to be indicated in the release statement.

> As for the JS API side

js.js is pretty well documented and without requireJS support, oC quickly becomes bloated when every app is adding its own libraries, but that's for another discussion.

**Comment by oparoz** [comment]
Supporting IE8 is killing the user experience for 95+% of users
https://github.com/owncloud/core/issues/14828

**Comment by Raydiation** [comment]
Some updated stats based on only the month May

| Area  | IE8%  | IE9%  | IE10% |
|---|---|---|---|
| [Europe](http://gs.statcounter.com/?PHPSESSID=525sl35652lc1ef2futkqm32l6#browser_version_partially_combined-eu-monthly-201505-201505-bar)  | 1.69 (-0.20%) | 1.55 (-0.14%) | 1.15 (-0.90%) | 
| [North America](http://gs.statcounter.com/?PHPSESSID=525sl35652lc1ef2futkqm32l6#browser_version_partially_combined-na-monthly-201505-201505-bar)  | 3.45 (-1.84%) | 2.9 (-0.34%) | 2.6 (-0.05%) |  
| [Global](http://gs.statcounter.com/?PHPSESSID=525sl35652lc1ef2futkqm32l6#browser_version_partially_combined-ww-monthly-201505-201505-bar)  | 3.21 (-0.56%) | 2.21 (-0.18%) | 1.89 (-0.01%) |

**Comment by Raydiation** [comment]
BTW just read that 11 is also available on 7 so we could actually drop 10 too ^^

**Comment by LukasReschke** [comment]
> BTW just read that 11 is also available on 7 so we could actually drop 10 too ^^

Dream on, sorry folks. As long as there are users that pay money which decide to use IE 8 (and there are a hell of them because some companies don't feel the need to update their ancient software) we simply cannot drop support in core. At least not for the basic functionalities such as file access etc… :-(

**Comment by Raydiation** [comment]
The question is ofc how many there are and when xp support is going to be dropped. Since the company does not publish these numbers one could only guess

**Comment by karlitschek** [comment]
just fyi. XP and IE8 marketshare is tracked by a lot of organizations. Just google it.

**Comment by DeepDiver1975** [comment]
@Raydiation we hate to support IE - it's no fun - nothing to argue about. But we need to continue to support it. It's simply a fact for the time being. We shall re-evaluate this on every major release.

So for 8.1 we keep IE8 - for 8.2 we will decide as soon as we start the dev cycle.

**Comment by oparoz** [comment]
Must be the same companies responsible for all the data breaches we keep hearing about...

**Comment by MorrisJobke** [comment]
Starting January 2016 Microsoft will drop support for IE8 completely and only support IE9 (Vista) and IE11 (7, 8.1) https://support.microsoft.com/en-us/gp/microsoft-internet-explorer

As 8.2 will be released in mid October and will not be in the production release channel before december with 8.2.2 (as a rough estimate). This is worth to think about.

The reason for this is, that @PVince81 currently has problems with porting it's WebDAV files app to a working state in IE8: https://github.com/owncloud/core/pull/16902#issuecomment-121139312

**Comment by DeepDiver1975** [comment]
Because this is mainly affecting the business side of ownCloud: @MTRichards please consider this with respect to the product road map - THX

**Comment by PVince81** [comment]
If people want to use ownCloud as a secure solution, they should also make sure to use secure browsers, which IE8 is not. Just saying.

**Comment by karlitschek** [comment]
Wow. This is cool. Would be great to drop 8. The question is of course of people stop using IE8 too. We have the problem with XP too. It is out of support but people still use it.

XP Marketshare: 12%
http://www.netmarketshare.com/operating-system-market-share.aspx?qprid=10&qpcustomd=0

IE8 Marketshare: 13.5%
https://www.netmarketshare.com/browser-market-share.aspx?qprid=2&qpcustomd=0

**Comment by karlitschek** [comment]
@MTRichards What do you think?

**Comment by MorrisJobke** [comment]
> XP Marketshare: 12%
> http://www.netmarketshare.com/operating-system-market-share.aspx?qprid=10&qpcustomd=0
> 
> IE8 Marketshare: 13.5%
> https://www.netmarketshare.com/browser-market-share.aspx?qprid=2&qpcustomd=0

Weird: 

http://gs.statcounter.com/#all-browser_version-ww-monthly-201506-201506-bar
IE8 Marketshare: <2% 

http://gs.statcounter.com/#all-os-ww-monthly-201506-201506-bar
Windows XP: 6%

**Comment by oparoz** [comment]
> IE8 Marketshare: 13.5%

That's because you've picked an analytics tool which heavily favours IE. ;)

At the end of the day, what counts is what your paying customers are telling you they're using, BUT, I still think it warrants having a special branch with all kind of workarounds for enterprise customers instead of polluting the main branch with shims, switches, etc. 
Keeping that debt in core makes it harder for contributors to submit their front-end code. Most would prefer working with HTML5 exclusively.

**Comment by karlitschek** [comment]
Well I just googled for it. :-) Do you have a better link?
Not sure it makes sense to maintain two different apps. Sounds like more work and a source for confusion. But something to discuss.

**Comment by karlitschek** [comment]
And now I saw the links from @MorrisJobke too :-)

**Comment by MorrisJobke** [comment]
> And now I saw the links from @MorrisJobke too :-)

;)

**Comment by oparoz** [comment]
@karlitschek - I like this page: https://en.wikipedia.org/wiki/Usage_share_of_web_browsers . It gives you a few sources and some insight on the methodologies used.

Regarding the separate branch, only a few experts should work on that. Special PHPDoc and JSDoc could be used in the main branch when compatibility is known to be broken and patches could be built at the same time on the IE8 branch.

At the end of the day, it's going to be the same amount of work, except that all the workarounds are kept away from the main branch and can die as soon as support is dropped instead of making the debt larger at every release.

**Comment by MTRichards** [comment]
Problem with dropping ie8 is that it remains a standard in many enterprises where legacy apps cost money to migrate, so they leave them on a required platform. So, while I would like to drop IE8, we can't at this time.

**Comment by oparoz** [comment]
I agree, but using IE8 to browse content sitting outside of the enterprise perimeter is usually too dangerous, even with proxies and firewalls, so some enterprises keep IE8 in the start menu for legacy apps, but also offer another browser.
It might be worth asking your clients if their tech support does offer a more modern browser which could be installed on their employees' hardware.

**Comment by MTRichards** [comment]
Good point - and for some, you are correct. But, there are still legacy folks for whom the only official browser is IE8, even though everyone is on Firefox or Chrome...

**Comment by Raydiation** [comment]
@MTRichards so what's the plan? What if your legacy customers will still be on IE8 in 2020? This sounds like we can never drop IE8 support. 

How many existing customers still use this stuff? Can we ask them how long they plan to stay on XP and if it would be possible for them to install Firefox or Chrome Enterprise Editions? Maybe also add incentives like higher costs if you require IE8 support like Microsoft does. How is IE8 support different from Windows Server and MSSql support which was dropped?

**Comment by tflidd** [comment]
I've seen company and university networks where you had to use IE for legacy apps. But they  encourage users to use IE only for that and FF for all other activities. One company (with a proxy server) even blocked IE completely for internet access.
I think the problem will be when you suddenly drop the support. With the last IE compatible release, I would put a warning on the admin and user page, that it is strongly recommended to use a secure browser. If you want to be very nice, you could put some kind of emergency interface to access their data on the first non-compatible version.
If you keep everything running on WinXP/IE8 why should users/companies ever update their systems (never change a running system)?

**Comment by Raydiation** [comment]
I think I've got something that will help to kill XP support :)

https://technet.microsoft.com/en-us/library/security/MS15-078

XP is also affected according to http://www.ghacks.net/2015/07/21/emergency-patch-for-windows-vulnerability-ms15-078-released-kb3079904/ 

TL;DR if anyone in your company surfs to a page that features fonts in the content or ads, the machine will be taken over. There is no patch for XP, making it actually impossible for people to safely surf the web on any browser.

@MTRichards Can we use that as a leverage to help our customers to migrate off XP?

Another thing that comes to my mind: If we drop IE<11 support in 8.2 e.g. we would still support it during the entire 8.1 maintenance period. As for 8.1 that means that we will support IE8 until april 2017.

Could we maybe agree on that mid 2017 is a long enough support time frame for XP?

**Comment by MTRichards** [comment]
>Could we maybe agree on that mid 2017 is a long enough support time frame for XP?

I think we can say that. But if we drop it in 8.2, that really means we start to drop it in Oct with 8.2. Sadly, we don't get much influence over corporate encironments, but we will do what we can here.

**Comment by DeepDiver1975** [comment]
@MTRichards is this an explicit: YES - DROP IE8 FOR 8.2?

**Comment by MTRichards** [comment]
No. Definitely not.

**Comment by MTRichards** [comment]
I will investigate dropping it with our customers, but not yet.

**Comment by oparoz** [comment]
@MTRichards - Why should enterprise customers still using IE8 get the new features of ownCloud 8.2?
8.1 is supported for 18 months, plenty of time for them to migrate to more modern technologies if they want to get 8.2, 8.3 or 9.x.

Making some of the new features compatible with IE8 is wasting a lot of resources which cuold be better spent serving 90% of users out there.

**Comment by MTRichards** [comment]
>Why should enterprise customers still using IE8 get the new features of ownCloud 8.2?

I know it is a pain, I know it takes time away from other efforts, and I know most folks don't user IE at all, let alone IE8. Regardless, we have obligations that we have to meet for support. I hope we can drop it soon, I really do, I would rather spend more time doing something else with the effort. We are almost there...

**Comment by oparoz** [comment]
OK. Hopefully, you're in the process of tuning your support contracts to make it possible to keep customers on an older release if they don't meet the requirements of the latest version :)

**Comment by MTRichards** [comment]
Yeah - to be completely transparent there are 2 more I need to talk to and set expectations.

**Comment by oparoz** [comment]
\o/

**Comment by kylesouza** [comment]
I'm still pretty new to Github, so hopefully I'm alerting you all to this in the right place - if not let me know, please.

While doing some IE specific testing I noticed a script error when loading search results and longer lists of folder contents.  I believe I've tracked this down to use of the jQuery "closest" method, specifically as used in the apps.js file (owncloud/core/js/apps.js); it does not appear that .closest() is supported in any version of Internet Explorer.  I am testing replacing .closest() with .parent().

Have you guys run into this before?

**Comment by Raydiation** [comment]
Wrong issue and it's already fixed, please update ;)

**Comment by jancborchardt** [comment]
Fun fact: Office 365, Microsoft’s cloud platform, doesn’t support IE8: https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/GETTINGSTARTED.md#supported-browsers

And will also aggressively start deprecating IE9: https://support.office.com/en-US/article/Office-365-system-requirements-719254c0-2671-4648-9c84-c6a3d4f3be45

**Comment by DeepDiver1975** [comment]
let's reelaborate on this within 9.0 scope - thx

**Comment by MorrisJobke** [comment]
As we are now in the scope of ownCloud 9.0:

@karlitschek @MTRichards What is the state of this? ;)

**Comment by MTRichards** [comment]
checking... I always say that, and always check - but I am leaning to dropping it, but still don't have feedback on everyone. For now, lets plan to remove it but please confirm with me before we take action that is irreversible...

**Comment by MorrisJobke** [comment]
> checking... I always say that, and always check - but I am leaning to dropping it, but still don't have feedback on everyone. For now, lets plan to remove it but please confirm with me before we take action that is irreversible...

Let's repeat the game :) What is the status? Did you collect all the feedback yet?

**Comment by rullzer** [comment]
Also relevant: https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support

**Comment by MTRichards** [comment]
Jan 21 seems like a good time to up the minimum to IE 11.

**Comment by LukasReschke** [comment]
> Jan 21 seems like a good time to up the minimum to IE 11.

Just to get a proper statement on this one: Seems like a good time or will we do it? This would affect ownCloud 9.0 where we already are investing significant time (also on-going!) on IE 8 compatibility and if we would not have to support IE 8 this would make @PVince81 much happier and a lot of needed efforts gone.

**Comment by MTRichards** [comment]
I will be super clear then.  We can discontinue IE 8 support with oc 9.0 launch. My discussions with customers and gcx have proven this is ok. So no need for ie 8 support in oC 9.0. IE 9 and 10 and 11 for 9.0. We will drop 9 and 10 for 9.1.

-- 
Matt Richards
VP Products & Markets 
ownCloud, inc.

**Comment by LukasReschke** [comment]
Thank you, @MTRichards. Let's close this then :smile:

**Comment by Henni** [comment]
Great to hear this!
What is the consequence of this decision?
Will we actively remove fallbacks like for SVGs to clean up the code or should we keep them for now?

**Comment by MorrisJobke** [comment]
> Will we actively remove fallbacks like for SVGs to clean up the code or should we keep them for now?

I think the SVG fallback can be removed.

**Comment by rullzer** [comment]
As suggested by @PVince81 we need to be carefull that the IE8 stuff is not also supporting IE9. Probabaly easiest to do the big cleanup for 9.1 when we can remove a lot more.

**Comment by PVince81** [comment]
@jospoortvliet @carlaschroder FYI, see https://github.com/owncloud/core/issues/15567#issuecomment-166754301

**Comment by jancborchardt** [comment]
Also FYI @owncloud/designers @oparoz :)

As mentioned, let’s wait for the 9.1 cycle though to remove all the fallbacks. But we can stop right now to add any more workarounds to current master. :)

**Comment by carlaschroder** [comment]
\o/

**Comment by RealRancor** [comment]
In addition to https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support two more links:

http://thenextweb.com/microsoft/2016/01/05/web-developers-rejoice-internet-explorer-8-9-and-10-die-on-tuesday/
https://support.microsoft.com/en-us/kb/3123303?sd=rss&spid=14019

MS will also ship a "The new "End of Life" upgrade notification for Internet Explorer" to make people aware of this.
