### ISSUE TITLE
Core has dependency on OpenSSL

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#15574]
For example https://github.com/owncloud/core/blob/a88e013f722a2bf30100074760509613c76ca807/lib/private/security/certificate.php#L54, other usages likely as well.

Two options:
1. We make OpenSSL a hard-dependency, should be not that big of a deal
2. We go through all OpenSSL usages and verify/replace them

This whole dependency stuff is a nightmare on it's own :see_no_evil: 

cc @karlitschek @DeepDiver1975

**Comment by DeepDiver1975** [comment]
from my understanding openssl is also required if we try to access an https link - e.g. appstore

**Comment by LukasReschke** [comment]
> from my understanding openssl is also required if we try to access an https link - e.g. appstore

I think for that it is actually sufficient to have cURL with OpenSSL support compiled. That said we have a ton of third-party libraries that expect that OpenSSL is installed and they might do some pretty … interesting … stuff if it isn't there ;-)

I'd vote for an hard-dependency. – OpenSSL is pretty much installed even on the crappiest web hosters available out there. But then only for 8.1 and for the older releases… well… let's just ignore it :see_no_evil:

**Comment by karlitschek** [comment]
Yes. Stuff like appstore should be covered by curl.
It would be good to have an overview over all the 3rdparty libraries that expect openssl and our own features that rely on that. Then we can evaluate. 
Less dependencies is always good.

**Comment by PVince81** [comment]
> OpenSSL is pretty much installed even on the crappiest web hosters available out there
