### ISSUE TITLE
After first use can't login anymore

### ISSUE THREAD

**Issue by hektor157** [owncloud/core#15576]
Ahoy,
yesterday i've installed ownCloud through cPanel, and everything just worked fine, but today i've tried to login through admin account and i can't get inside.
I've tried to remove cache, also browsing in incognito mode and still nothing. What should i do? =/
Best regards,
hektor157

**Comment by karlitschek** [comment]
Hm. I´m sorry to hear that. I recommend that you ask this question in the owncloud forum at forum.owncloud.org
Thanks a lot.
