### ISSUE TITLE
problem updating webpage after fileupload

### ISSUE THREAD

**Issue by emitac** [owncloud/core#15571]
### Steps to reproduce
1.Login to Owncloud
2.Upload a file
3.The site does not actualize - at all PCs and all Browsers

### Expected behaviour
The site should actualize

### Actual behaviour
The site stands as shown in tne Picture for ever

### Server configuration
**Operating system**: CentOS 6.6

**Web server: Apache 2.2.15

**Database: MySql 5.1.73

**PHP version: 5.5.23

**ownCloud version: 8.0.2

**Updated from an older ownCloud or fresh install: fresh install

**List of activated apps: none

**The content of config/config.php:

```
<?php
$CONFIG = array (
 'instanceid' => ocxlkfxu9cbs',
 'passwordsalt' => 'thepassword',
 'secret' => 'thesecret',
 'trusted_domains' =>
 array (
 0 => 'scloud.rheingold-salon.de',
 ),
 'datadirectory' => '/srv/owncloud/',
 'overwrite.cli.url' => 'https://scloud.rheingold-salon.de/owncloud',
 'dbtype' => 'mysql',
 'version' => '8.0.2.0'
 'dbname' => 'owncloud',
 'dbhost' => 'localhost'
 'dbtableprefix' => 'oc_',
 'dbuser' => 'ownclouduser',
 'dbpasswort' => 'thepasswort',  -- (the original password exists of upper and lower letters, special characters and numbers)
 'installed' => true,
 'forcessl' => true,
 'forceSSLforSubdomains' => true,
 'mail_from_address' => 'postmaster',
 'mail_smtpmode' => 'php',
 'mail_domain' => 'rheingold-salon.de';
);
```

**Are you using external storage, if yes which one: no

**Are you using encryption: no

**Are you using an external user-backend, if yes which one: no

```
run: sqlite3 data/owncloud.db
then execute:  select * from oc_appconfig where appid='user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser: IE 11, Mozilla Firefox 36

**Operating system: Windows 7 64bit

#### Web server error log
```
see file "Web server error log.jpg"
```

#### ownCloud log (data/owncloud.log)
```
see file "owncloud log.jpg"
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

![owncloud log](https://cloud.githubusercontent.com/assets/11923253/7114159/331fa168-e1db-11e4-9d2f-a17d24020434.jpg)
![web server error log](https://cloud.githubusercontent.com/assets/11923253/7114160/331ff032-e1db-11e4-8e15-72677a16f771.jpg)

**Comment by PVince81** [comment]
@emitac anything in the JS console ?

Are these big files ? I see messages in your log that say the file couldn't be fully uploaded.
Maybe something in your setup is mangling the HTTP requests, please double check your config.

Has this ever worked before on this env and broke recently, or never worked in the first place ?

**Comment by emitac** [comment]
Hello,

it happens with every files, starting from Kilobytes up to Gigabytes.
The files are fully uploaded. Only Files biger than 3.5GB can not uploaded.
It does not matter what I have written in config.php and php.ini.
When the upload finished, the website does not aktualize, as shown in the foto. This stays for ever.
First when I hit F5 the site is actualized with the question to leave the site before.
This had never worked.

I hope that is clear what happened, please be patient for my english!


Mit freundlichem Gruß

EMITaC – IT Consulting
Erik Mühlfarth
Feltenstr. 88
D-50827 Köln
Tel.: +49 221 94969704
Mob: +49 163 6996386
Fax: +49 221 94969707
Ust. ID: DE813459937

Von: Vincent Petry [mailto:notifications@github.com]
Gesendet: Dienstag, 14. April 2015 13:17
An: owncloud/core
Cc: EMITaC - IT Consulting (Erik Mühlfarth)
Betreff: Re: [core] problem updating webpage after fileupload (#15571)


@emitac<https://github.com/emitac> anything in the JS console ?

Are these big files ? I see messages in your log that say the file couldn't be fully uploaded.
Maybe something in your setup is mangling the HTTP requests, please double check your config.

Has this ever worked before on this env and broke recently, or never worked in the first place ?

**Comment by emitac** [comment]
Hello,

I checked the .htaccess, config.php, httpd.conf and php.ini
I did not found any that could be responsible for that behavior with the F5 and leave site Message.
If You can give me an emailadress i sent you the files, so maybe You see more than me.
Do You have any other ideas what could be the problem?

Thanks in advance
Yours, Erik
