### ISSUE TITLE
[Enc 2] desktop client syncs encrypted file.

### ISSUE THREAD

**Issue by th3fallen** [owncloud/core#15582]
## Steps
configure desktop client
Sync files

## Expected result

files sync and are usable from ownCloud folder
## Actual result

files in ownCloud folder are encrypted

## Versions
current master

**Comment by DeepDiver1975** [comment]
new instance or migrated from oc7?

**Comment by DeepDiver1975** [comment]
There is an explicit check to throw back an exception to the client in case an encrypted file cannot be decrypted.

**Comment by th3fallen** [comment]
sorry, migrated from oc7 but shouldnt matter files have been migrated and work fine in web ui

**Comment by DeepDiver1975** [comment]
BÄÄH!

**Comment by th3fallen** [comment]
glad i started looking at desktop client firewall blocks....

**Comment by PVince81** [comment]
@th3fallen are you still seeing this on master ?

**Comment by th3fallen** [comment]
nope were clear now @PVince81
