### ISSUE TITLE
S3 unlimited space

### ISSUE THREAD

**Issue by emilnikkhah** [owncloud/core#15587]
HI 
I have installed ownCloud 8.0.2, added 2 users with two buckets, User X can se bucket XX and user Y can se bucket YY.  Unlimited space.
Now I uploaded 6G to user X. In personal it shows You have used 0 B of the available 10.1 GB.
Same thing shows on user Y. 
When I delete files, it is still You have used 0 B of the available 10.1 GB in both users, also in admin.
I suppose it is not looking in to S3 storage but in to the servers storage( the server it is running on?)

**Comment by emilnikkhah** [comment]
If I am at the wrong place, please let me know.

**Comment by RealRancor** [comment]
Hi,

external storages are currently not counted for qouta by default:

https://github.com/owncloud/core/blob/v8.0.2/config/config.sample.php#L828

**Comment by emilnikkhah** [comment]
Thanks 
I still dont get it why when i try to Upload 16G with desktop app. It just stuck.
Also the cache from /data/user/cache is not deleted.
Emil

**Comment by Xenopathic** [comment]
@RealRancor I don't think this is an external storage, I think this is using the S3 storage backend for user files, available in the Enterprise edition.

@emilnikkhah I noticed you closed the issue - if you are still getting problems, please reopen!

**Comment by RealRancor** [comment]
@Xenopathic Ah, ok. One reason why the people should fill out the issue template. :)

**Comment by emilnikkhah** [comment]
Sorry, I am not used to reporting. next time i will do better. But from what i understand Owncloud don´t work well with uploading big files to S3, I get different error every time. Thank your for your time.

**Comment by emilnikkhah** [comment]
To be clear:) nothing can upload 16G to S3, i have been trying Cyberduck, Transmit, Forklift.)
