### ISSUE TITLE
[enc2] New encryption much slower to download files

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15580]
### Steps
1. Setup OC 8.0.3RC1 (or stable8)
1. Enable encryption
1. Create two users "user1" and "user2"
1. Login as "user1"
1. Create a folder "test"
1. Upload a big file "data1.dat" (mine was 121MB big)
1. Share "test" with "user2"
1. Download the file with curl as "user2": `curl http://user2:test@localhost/owncloud/remote.php/webdav/test/data1.dat -o temp.dat`. Took 2s "Time spent"
1. Upgrade to master (I used the migration branch https://github.com/owncloud/core/pull/15445)
1. Go to the admin page and enable encryption
1. Click "Start migration"
1. Enable "ownCloud default encryption module" app
1. Rerun the curl command: took 16 seconds "Time spent"

### Expected result
No significant performance impact

### Actual result
Performance loss of about 800%

I'll try running it into blackfire before and after

### Versions
Migrating stable8 to this branch https://github.com/owncloud/core/pull/15445 (for the migration)

**Comment by PVince81** [comment]
@schiesbn @th3fallen @icewind1991 @DeepDiver1975

**Comment by karlitschek** [comment]
hmm. not good at all

**Comment by PVince81** [comment]
I tried to profile it with blackfire and here is the result:
- before: https://blackfire.io/profiles/50c31839-b57d-4369-a5cd-d87ee578bbe6/graph
- after: https://blackfire.io/profiles/22e78407-16f9-45ed-b8dd-7104b078dd2d/graph

When doing the measurement with curl, I noticed that it now aborts at 2s:
```
  % blackfire -slot=11 curl http://user2:test@localhost/owncloud/remote.php/webdav/test/data1.dat -o temp_before.dat
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 69  161M   69  112M    0     0  49.0M      0  0:00:03  0:00:02  0:00:01 49.0Mcurl: (18) transfer closed with 42737308 bytes remaining to read
Error while running command: exit status 18

```

I think the reason why it takes 15 additional seconds is only because curl waits for the missing bytes, then gives up. So the actual download still only takes 2 seconds.

The real problem is that Content-Length doesn't match, possibly due to https://github.com/owncloud/core/pull/15445#issuecomment-92363297

**Comment by PVince81** [comment]
I also observed this in Chrome: I see the download counter advancing then stopping for a while, then it gives up (timeout) and delivers the file.

**Comment by DeepDiver1975** [comment]
> The real problem is that Content-Length doesn't match, possibly due to #15445 (comment)

This is related to the filesize issue which is still open ...

**Comment by PVince81** [comment]
Got another case with this specific file: https://owncloud.vincentpetry.net/index.php/s/n8iRzw7ROCb6Fv7
Download it from my server and then upload it on OC master.
Then download in Chromium or copy the download.php link by right clicking on the file name in the web UI.

Downloading this file with curl with download.php gives me this:
```
  % curl -D - 'http://root:admin@vvortex.lan/owncloud/index.php/apps/files/ajax/download.php?dir=%2FFotos&files=dsc05535.jpg' -o test.jpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0HTTP/1.1 200 OK
Date: Mon, 20 Apr 2015 14:18:00 GMT
Server: Apache/2.4.12 (Linux/SUSE)
X-Powered-By: PHP/5.6.7
Set-Cookie: ocs3nh3668n3=c4j6at09tk8gt8af9g0c40o9s8488up3pvf93r7ui54vf8ncorl0; path=/owncloud; HttpOnly
Expires: 0
Cache-Control: must-revalidate, post-check=0, pre-check=0
Pragma: public
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *; connect-src *
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: Sameorigin
X-Robots-Tag: none
Set-Cookie: ocs3nh3668n3=q71j2bt3agge7pvar61891377aqcekoih5ri1jemt5d1qtndjej0; path=/owncloud; HttpOnly
Content-Disposition: attachment; filename*=UTF-8''dsc05535.jpg; filename="dsc05535.jpg"
Content-Transfer-Encoding: binary
Content-Length: 780180
Content-Type: image/jpeg

 99  761k   99  760k    0     0  51172      0  0:00:15  0:00:15 --:--:--     0curl: (18) transfer closed with 1940 bytes remaining to read
```
The resulting file is corrupt because it is missing a few bytes.

The Content-Length does match the original file size.

**Comment by PVince81** [comment]
Note: it doesn't even need to be a shared file.

**Comment by PVince81** [comment]
Also downloading the file over curl delivers the correct content. So it's not an upload problem.

**Comment by PVince81** [comment]
CC @jknockaert here as well in case you got an idea.
In the other ticket you mention writing problem. Here it seems to be more of a reading problem.
But not sure why it would happen with download.php but not with WebDAV.

**Comment by jknockaert** [comment]
@PVince81 This looks like a filesize problem. Something broken in this area is being fixed in #15636 (but not yet merged). After that it would be good to check if the encryption stream wrapper gets the right unencrypted and encrypted size passed upon stream_open. The encrypted size should include the encryption header. The write issue that I mentioned in https://github.com/owncloud/core/issues/15631#issuecomment-94424421 can potentially lead to corruption but should not slow down read/writes (if the result is still correct).

**Comment by PVince81** [comment]
One difference I observed between WebDAV (which works) and download.php:
- in the case of WebDAV, it uses file_put_contents in the SAPI from Sabre. Basically Sabre calls `file_put_contents()` on the PHP output and puts the stream resource. So the copy loop is done by PHP.
- in the case of download.php, it goes into the View and we have our own loop there: https://github.com/owncloud/core/blob/master/lib/private/files/view.php#L353

**Comment by PVince81** [comment]
Thanks for the info. I'll have a check with the debugger to see if the stream is getting the wrong filesize, that could confirm it.

**Comment by PVince81** [comment]
With WebDAV:
```
  $this->size                    = (int) '1051504';
  $this->position                = (int) '0';
  $this->unencryptedSize         = (int) '780180';
  $this->unencryptedBlockSize    = (int) '6126';
```

with download.php:
```
  $this->size                    = (int) '1051504';
  $this->position                = (int) '0';
  $this->unencryptedSize         = (int) '780180';
  $this->unencryptedBlockSize    = (int) '6126';
```

780180 bytes is the correct file size of the original file.

Both seem to call stream_read with a count of 8192.

**Comment by jknockaert** [comment]
That looks pretty similar.

**Comment by PVince81** [comment]
Yes. I also tried evaluating the whole class and it looks that it's the same for both.
The difference might be how stream_read is called, combined with calls to feof.

I tried logging $count at the beginning of the loop, and this is what I get: https://s3.owncloud.com/owncloud/index.php/s/jDc1gdO9CWgceQQ

Starting with the 6th iteration the remaining value isn't the same any more (6192 instead of 2066).
I'll see if I can find out more.

**Comment by jknockaert** [comment]
And the result (i.e. the downloaded file) is still the same for both?

**Comment by PVince81** [comment]
No, the file from download.php is missing a few bytes.

Sorry, I had a copy-paste fail when creating those files. I have updated them now.
The diff now shows that the $count sizes were identical until the end of the file:
```
--- encdebug-webdav.log 2015-04-20 16:59:47.740339159 +0200
+++ encdebug-download.log   2015-04-20 16:57:50.248206279 +0200
@@ -220,7 +220,3 @@
 8192
 6364
 238
-8192
-2304
-8192
-4370
```

**Comment by PVince81** [comment]
Okay I created a local file that has 8193 bytes and uploaded it.
Downloading that file with download.php is missing the last byte. (curl is fine)
I have uploaded it here too: https://s3.owncloud.com/owncloud/index.php/apps/files/?dir=%2Fattachments%2Fgithub%2F15580

**Comment by jknockaert** [comment]
OK, so you wrote a file, then you did download.php which results in a missing byte, and next webdav with the correct file, right? Could you check if the order of things matter? Specifically: does the missing byte only happen upon the first download (with download.php) after upload? E.g. if you repeat download.php upon the same saved file, does this always result in the same missing byte?

**Comment by PVince81** [comment]
Yes, WebDAV always gives the correct file and download.php always gives a file with a missing byte.

I tried stepping over the "while" loop a few times and observed that with WebDAV it loops much longer, even after $this->position=8192 it goes futher to $this->position=16283, 24576 and only then it goes out. Note that it's PHP's internal code (from file_put_contents) which controls the calls.

In the case of download.php it only goes up to $this->position=8192 and then `readfile()` calls feof() and jumps out, failing to read the last block.

**Comment by PVince81** [comment]
So basically, with WebDAV: stream_read is called 3 times (6 iterations in the while) and with download.php it is called 1 time (2 iterations in the while)

**Comment by jknockaert** [comment]
Hmm. No idea right now what's happening. I'll have another look at it later today.

**Comment by PVince81** [comment]
As you like, I think I'm onto something:

With WebDAV:
```
{"reqId":"TONCiX\/fi5gOeYiuGsE+","remoteAddr":"127.0.0.1","app":"encryptiondebug","message":"count=8192","level":0,"time":"2015-04-20T15:14:14+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/8193.dat"}
{"reqId":"TONCiX\/fi5gOeYiuGsE+","remoteAddr":"127.0.0.1","app":"encryptiondebug","message":"count=2066","level":0,"time":"2015-04-20T15:14:14+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/8193.dat"}
{"reqId":"TONCiX\/fi5gOeYiuGsE+","remoteAddr":"127.0.0.1","app":"encryptiondebug","message":"returned length: 8192","level":0,"time":"2015-04-20T15:14:14+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/8193.dat"}
{"reqId":"TONCiX\/fi5gOeYiuGsE+","remoteAddr":"127.0.0.1","app":"encryptiondebug","message":"icewind stream wrapper: feof($this->source)=1","level":0,"time":"2015-04-20T15:14:14+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/8193.dat"}
{"reqId":"TONCiX\/fi5gOeYiuGsE+","remoteAddr":"127.0.0.1","app":"encryptiondebug","message":"count=8192","level":0,"time":"2015-04-20T15:14:14+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/8193.dat"}
{"reqId":"TONCiX\/fi5gOeYiuGsE+","remoteAddr":"127.0.0.1","app":"encryptiondebug","message":"count=4132","level":0,"time":"2015-04-20T15:14:14+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/8193.dat"}
{"reqId":"TONCiX\/fi5gOeYiuGsE+","remoteAddr":"127.0.0.1","app":"encryptiondebug","message":"returned length: 1","level":0,"time":"2015-04-20T15:14:14+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/8193.dat"}
{"reqId":"TONCiX\/fi5gOeYiuGsE+","remoteAddr":"127.0.0.1","app":"encryptiondebug","message":"icewind stream wrapper: feof($this->source)=1","level":0,"time":"2015-04-20T15:14:14+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/8193.dat"}
{"reqId":"TONCiX\/fi5gOeYiuGsE+","remoteAddr":"127.0.0.1","app":"encryptiondebug","message":"count=8192","level":0,"time":"2015-04-20T15:14:14+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/8193.dat"}
{"reqId":"TONCiX\/fi5gOeYiuGsE+","remoteAddr":"127.0.0.1","app":"encryptiondebug","message":"count=6198","level":0,"time":"2015-04-20T15:14:14+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/8193.dat"}
{"reqId":"TONCiX\/fi5gOeYiuGsE+","remoteAddr":"127.0.0.1","app":"encryptiondebug","message":"count=72","level":0,"time":"2015-04-20T15:14:14+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/8193.dat"}
{"reqId":"TONCiX\/fi5gOeYiuGsE+","remoteAddr":"127.0.0.1","app":"encryptiondebug","message":"returned length: 0","level":0,"time":"2015-04-20T15:14:14+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/8193.dat"}
{"reqId":"TONCiX\/fi5gOeYiuGsE+","remoteAddr":"127.0.0.1","app":"encryptiondebug","message":"icewind stream wrapper: feof($this->source)=1","level":0,"time":"2015-04-20T15:14:14+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/8193.dat"}
```

here with WebDAV even though feof returns 1, the internal PHP code continues to loop.

But in download.php case, we have our own loop that correctly relies on feof to stop:
```
{"reqId":"TONCiX\/fi5gOeYiuGsE+","remoteAddr":"127.0.0.1","app":"encryptiondebug","message":"count=8192","level":0,"time":"2015-04-20T15:14:14+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/8193.dat"}
{"reqId":"TONCiX\/fi5gOeYiuGsE+","remoteAddr":"127.0.0.1","app":"encryptiondebug","message":"count=2066","level":0,"time":"2015-04-20T15:14:14+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/8193.dat"}
{"reqId":"TONCiX\/fi5gOeYiuGsE+","remoteAddr":"127.0.0.1","app":"encryptiondebug","message":"returned length: 8192","level":0,"time":"2015-04-20T15:14:14+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/8193.dat"}
{"reqId":"TONCiX\/fi5gOeYiuGsE+","remoteAddr":"127.0.0.1","app":"encryptiondebug","message":"icewind stream wrapper: feof($this->source)=1","level":0,"time":"2015-04-20T15:14:14+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/8193.dat"}
{"reqId":"TONCiX\/fi5gOeYiuGsE+","remoteAddr":"127.0.0.1","app":"encryptiondebug","message":"count=8192","level":0,"time":"2015-04-20T15:14:14+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/8193.dat"}
{"reqId":"TONCiX\/fi5gOeYiuGsE+","remoteAddr":"127.0.0.1","app":"encryptiondebug","message":"count=4132","level":0,"time":"2015-04-20T15:14:14+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/8193.dat"}
{"reqId":"TONCiX\/fi5gOeYiuGsE+","remoteAddr":"127.0.0.1","app":"encryptiondebug","message":"returned length: 1","level":0,"time":"2015-04-20T15:14:14+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/8193.dat"}
{"reqId":"TONCiX\/fi5gOeYiuGsE+","remoteAddr":"127.0.0.1","app":"encryptiondebug","message":"icewind stream wrapper: feof($this->source)=1","level":0,"time":"2015-04-20T15:14:14+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/8193.dat"}
{"reqId":"TONCiX\/fi5gOeYiuGsE+","remoteAddr":"127.0.0.1","app":"encryptiondebug","message":"count=8192","level":0,"time":"2015-04-20T15:14:14+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/8193.dat"}
{"reqId":"TONCiX\/fi5gOeYiuGsE+","remoteAddr":"127.0.0.1","app":"encryptiondebug","message":"count=6198","level":0,"time":"2015-04-20T15:14:14+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/8193.dat"}
{"reqId":"TONCiX\/fi5gOeYiuGsE+","remoteAddr":"127.0.0.1","app":"encryptiondebug","message":"count=72","level":0,"time":"2015-04-20T15:14:14+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/8193.dat"}
{"reqId":"TONCiX\/fi5gOeYiuGsE+","remoteAddr":"127.0.0.1","app":"encryptiondebug","message":"returned length: 0","level":0,"time":"2015-04-20T15:14:14+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/8193.dat"}
{"reqId":"TONCiX\/fi5gOeYiuGsE+","remoteAddr":"127.0.0.1","app":"encryptiondebug","message":"icewind stream wrapper: feof($this->source)=1","level":0,"time":"2015-04-20T15:14:14+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/8193.dat"}
```

It is either a bug in @icewind1991's stream wrapper that might not return the correct feof value, or it's a bug in the encryption stream's feof that returns true too early.

**Comment by PVince81** [comment]
Sorry, I pasted the same twice. Fixed now in previous comment.

I'll try and dig into feof now.

**Comment by PVince81** [comment]
I suspect that the loop is reading the last block in advance, but the stream wrapper's feof function is called on the real file, which already reached the end, even though we haven't processed the last block. If that's the case we need to override stream_feof and properly compute its result.

**Comment by PVince81** [comment]
Fixing feof works, PR here: https://github.com/owncloud/core/pull/15757
