### ISSUE TITLE
File marked as shared but remote user cancelled the share

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#15589]
### Steps to reproduce
1. Upload a file (server A) and share it with a remote user in other server (Click in the share, and use something like "user@http://server/owncloud" to send the link - "user" must exists in the remote ownCloud server)
2. In the other server (server B), login as the user. A popup should appear, telling you that a file has been shared with you.
3. Cancel the sharing

### Expected behaviour
File shared inside server A isn't marked as shared (the remote user has cancelled it, so the file isn't shared)

### Actual behaviour
File is marked as shared

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.4

**ownCloud version:** OC 8.0.3RC1

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by nickvergessen** [comment]
reopening for 8.0.4 fix

**Comment by MorrisJobke** [comment]
Backport also merged -> close
