### ISSUE TITLE
Users page layout issue

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15583]
On master (660aa7ff1e7bcb61d5dcb103014da39b8a257899)

It looks like the login name column is missing:
![login_username_missing](https://cloud.githubusercontent.com/assets/277525/7118255/3a939fd0-e1fe-11e4-9676-82d82bab8234.png)

@rullzer @MorrisJobke @LukasReschke

**Comment by MorrisJobke** [comment]
Bisected: 	b6efee8079ac67da5e72c281c3a9cacf047d7fd8

I will look into this

**Comment by nickvergessen** [comment]
`<th class="name" scope="row"></th>` can not be found by `$tr.find('td.name').text(user.name);`

Please while fixing add a test for this.

**Comment by MorrisJobke** [comment]
Fix is in #15585
