### ISSUE TITLE
OC_EventSource does not support multiple streams on IE8

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#15599]
This is to make it clearer that the fallback implemented in OC_EventSource does not work, instead of just mentioning it in [another ticket](https://github.com/owncloud/core/issues/14286).

Afaict, EventSource is used in OC.update and Pictures (Gallery+ has switched to a different library).

The best thing to do from my pov is to switch to a 3rd party polyfill since that would be one less thing to maintain.

**Comment by PVince81** [comment]
Hmm, but OC_EventSource is also used by the upgrade system when clicking "Start update" and I remember that it worked in the past with IE8.

So, possibly a regression.

**Comment by oparoz** [comment]
I don't have access to IE8, but what could happen is that it works fine when one EventSource call is made at a time, but fails when there is more than one, like in the Pictures app.

**Comment by PVince81** [comment]
You can easily get an IE8 VM here: https://www.modern.ie/en-us/virtualization-tools#downloads

**Comment by oparoz** [comment]
Ah, thanks :)

**Comment by oparoz** [comment]
Updated the title since it can be made to work with IE9-11 using black magic.
IE8 is still a no go though when using multiple streams, like in Pictures.

**Comment by davitol** [comment]
As IE8 support is dropped in 9.0 I will close this issue.
