### ISSUE TITLE
Move one share into another as recipient, reshare recipient cannot access it

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15591]
### Steps
1. Create three users "user1", "user2" and "user3"
2. Login as "user1"
3. Create a folder "test" and share it with "user2"
4. Login as "user2"
5. Create a folder "test2" and share it with "user3"
6. Now move "test2" into "test"
7. Login as "user3"
8. Enter "test2" folder

### Expected result
"test2" must be visible to "user3" and can be entered.

### Actual result
"test2" doesn't appear in the file list for "user3"

### Versions
ownCloud master (ffa115b51725c4774b49c2419f88cb91d726386b)

### Log
Nothing in the log

### DB dump
```
MariaDB [owncloud]> select * from oc_share;
+----+------------+------------+-----------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-------+-----------+
| id | share_type | share_with | uid_owner | parent | item_type | item_source | item_target | file_source | file_target | permissions | stime      | accepted | expiration | token | mail_send |
+----+------------+------------+-----------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-------+-----------+
|  1 |          0 | user2      | user1     |   NULL | folder    | 15          | /15         |          15 | /test       |          31 | 1429001599 |        0 | NULL       | NULL  |         0 |
|  2 |          0 | user3      | user2     |   NULL | folder    | 23          | /23         |          23 | /test2      |          31 | 1429001631 |        0 | NULL       | NULL  |         0 |
+----+------------+------------+-----------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-------+-----------+
```

In the case of a subfolder reshare, the reshare should have its "parent" column pointing at the main one. This is missing here. I suspect that when moving a share into another there is no logic to reparent the share ?

@schiesbn @icewind1991

**Comment by PVince81** [comment]
Note: this situation was never possible in the past because the unstable file ids used to lost the share

**Comment by PVince81** [comment]
Still happening in 8.2RC1

**Comment by rullzer** [comment]
This was a simplified version of https://github.com/owncloud/core/issues/20769

And is thus also fixed by https://github.com/owncloud/core/pull/20989

Just tested and works on master :) => Closing

**Comment by brozkeff** [comment]
I tested the Steps on owncloud 8.2.2~RC1-24.1 on Ubuntu 14.04 server.

Results:

"test2" DOES appear in the file list for "user3" correctly. User3 does NOT see whole folder "test" but only the subfolder including some text file.

The only error I see is that the UI for user2 shows in the "Shared with others" list, as if whole folder "test" was "shared with user3", in details of user2 on the right is "Shared in test with user3" with the ability to tweak permissions for whole folder "test" and not just the subfolder "test2".

```text
select * from oc_share where file_target like '%test%'

id	share_type	share_with	uid_owner	parent	item_type	item_source	item_target	file_source	file_target	permissions	stime	accepted	
955	0	user2	user1	NULL	folder	181917	/181917	181917	/test	31	1450710306	0	NULL	NULL	0
956	0	user3	user2	955	folder	181918	/181918	181918	/test2	31	1450710367	0	NULL	NULL	0
```
