### ISSUE TITLE
Weird mtime behaviour in a cascade federated share

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#15594]
### Steps to reproduce
1. Upload a file in server A (checked with an image file in the root folder)
2. Send the share to a server B (click in the share button and use something like "user1@http://serverb/owncloud")
3. From the server B, send the shared file to server C (same as step 2)
4. Check the file is visible in server C with a determined mtime
5. After some time (5 minutes is enough) reload the page in server C to verify the mtime
6. Reload the page again

### Expected behaviour
Mtime of the file in server C should be same than the original file (in server A)

### Actual behaviour
Mtime in server C shows "a few seconds ago" even though the file hasn't been modified in server A

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.4

**ownCloud version:** OC 8.0.3RC1 in all the servers

**Updated from an older ownCloud or fresh install:** fresh install in all the servers

### Notes
- Checked with a folder instead of a file, and it doesn't present this behaviour.
- Mtime of the file in server B changes too, but then seems to recover after loading the file in server B
- Preview might be the cause. Reloading several times the page in server C without allowing to finish getting the preview shows an acceptable timestamp, but if the preview get downloaded, the timestamp resets.

**Comment by PVince81** [comment]
Can you retest with plain data files, ex: "data1.dat" to make sure no preview gets created.
If it still happens, then it is not related to previews.

Not sure why the mtime would change several times on the receiver side. It is supposed to reuse the cache info delivered by the origin, which includes mtime information.
CC @icewind1991

**Comment by PVince81** [comment]
I guess the mtime change might also have a related etag change, which would cause sync clients to redownload the files. To be confirmed.

**Comment by jvillafanez** [comment]
I've checked a similar setup with another image file, but instead sending the share to the user using password-protected shared links: The file in server C doesn't get the correct mtime after being modified in server A, looks like the file is stuck with the old version, but it downloads the right file. File in server B looks good except for the preview.

From my point of view, both methods should have the same behaviour, but it's very different.

Checking with a plain file now.

**Comment by jvillafanez** [comment]
With a "fake.dat" file, the behaviour seems the same as my last comment.

**Comment by PVince81** [comment]
Ok thanks for the info, so probably unrelated to previews.

**Comment by PVince81** [comment]
could be related to https://github.com/owncloud/core/issues/19737

**Comment by PVince81** [comment]
Is this still happening in 9.0 ? (etag propagation has changed)

**Comment by cmonteroluque** [comment]
@rperezb @jvillafanez please check

**Comment by cmonteroluque** [comment]
@rperezb @jvillafanez ping

**Comment by jvillafanez** [comment]
Checked against daily master (ownCloud 9.0.0 beta 2 (daily) Build:2016-02-26T04:41:33+00:00 cb41b1a86397579d55e0ce96e67b80a83037d1d2) in the 3 servers: it's working.

There are quite a bunch of possiblities here with the server versions, so I'm not sure if we should prioritize any special configuration.
