### ISSUE TITLE
apps_paths configuration should not modify the url

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#15604]
In a restful design, a URL should be a resource.
On ownCloud, apps can be found in /apps

`apps_paths` allows admins to modify the url where to find some apps and that goes against the convention and breaks things (https://github.com/owncloud/core/issues/14236)

```
'apps_paths' => array(
	array(
		'path'=> '/var/www/owncloud/apps',
		'url' => '/apps',
		'writable' => false,
	),
	array(
		'path'=> '/var/www/owncloud/myapps',
		'url' => '/3rdparty-apps',
		'writable' => true,
	),
),
```

The URL parameter should be dropped and writable is up for removal discussion since ownCloud can figure out by itself if a directory is writable

**Comment by oparoz** [comment]
@Raydiation - Feel free to enhance this ticket

**Comment by DeepDiver1975** [comment]
This doesn't work.  The url id used to load assets being served statico by the web server.

Routes remain unchanged and always start with /app/

**Comment by Raydiation** [comment]
The News app also suffered from one of these issues: Debian used to ship a default config which placed all appstore apps under the url root /apps-3rdparty e.g. /apps-3rdparty/news. This not only broke the webinterface but also all API URLs for mobile clients.

While this issue may be nicely solvable for the webinterface, it isnt for the mobile clients (or you'd have to enter the entire! api url whereas only the base owncloud url should suffice)

**Comment by oparoz** [comment]
@DeepDiver1975 A 3rd party app loading one of its template while the user is in the Files app will not find it in /apps, the specific folder will have to be given. That's just one case I'm aware of.

**Comment by DeepDiver1975** [comment]
> This not only broke the webinterface but also all API URLs for mobile clients.

How is the API URL generated? How does it look like? For me any route is starting with apps and I have all apps installed in the folder apps2.

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 A 3rd party app loading one of its template while the user is in the Files app will not find it in /apps, the specific folder will have to be given. That's just one case I'm aware of.

explicit example please - and I can have a look - thx

**Comment by Raydiation** [comment]
@DeepDiver1975 the problem is the additional url parameter, which you are able to set in the config.php That way you can overwrite the route generation in an unforseen way.

**Comment by DeepDiver1975** [comment]
> the problem is the additional url parameter, which you are able to set in the config.php

This parameter is not taken into consideration when generating routes

**Comment by Raydiation** [comment]
Has this been changed at some point? Does that mean that the url parameter is ignored and the documentation in config.php is wrong?

**Comment by DeepDiver1975** [comment]
> Has this been changed at some point?

no - has been this for a long time - the only affecting change in this area was when we skipped js and css delivery via php and allow static delivery by the web server.



> Does that mean that the url parameter is ignored and the documentation in config.php is wrong?

No - this parameter is used to generate urls for assets (images, css, js)

**Comment by oparoz** [comment]
@DeepDiver1975 
`OC.generateUrl('apps/myapp/templates/fragment.html')`
That will generate a full URL using index.php and can't be called from the Files app.
we used to be able to call OC.filePath() and it would build the proper URL for us, but that doesn't exist any more.
If this is horribly, wrong, then it's the developer's fault, of course.
For other examples, look at https://github.com/owncloud/core/issues/14236
Those users can only load the apps if they use symlinks.

**Comment by DeepDiver1975** [comment]
@oparoz I see the confusion here now - this indeed needs more documentation.

OC.generateUrl - is to be used to generate routes - there is no need to take 'url' into consideration here.

OC.filePath() - afaik is used for static files and respects 'url' - one shall have a look ...

**Comment by Raydiation** [comment]
We should probably start to think about a minimal clientside public api which is documented well and includes:

* Routing
 * OCP.Router.linkToRoute(): returns an absolute url for a route
 * OCP.Router.linkToFile(): returns an absolute url for a file (do we want to split this up?)
 * OCP.Router.getBaseUrl(): returns the owncloud base url for concatenation, e,g, like /test/owncloud/
* L10N
 * OCP.L10N.t()
* CSRF tokens:
 * OCP.Security.getCSRFToken()

Another solution: Django solves this issue by using a collecstatic shell command, as in: on a production machine and after app installation you run the command to copy the static content over to the default static directory. When running the development server, django just serves the files for you by using a slower Python based implementation

**Comment by oparoz** [comment]
@DeepDiver1975 - Well, the problem is that OC.filePath() is depreciated, and the documentation explicitly mentions replacing that method with OC.generateUrl(), so yes, there seems to be a big documentation problem.
https://github.com/owncloud/core/blob/master/core/js/js.js#L160

OC.generateUrl needs to evolve or the depreciated label removed from OC.filePath()
(And after that change, everything needs to move to OCP)
