### ISSUE TITLE
SSL root certificates should be automatically converted on upload

### ISSUE THREAD

**Issue by gig13** [owncloud/core#15608]
**Expected Behavior**
When uploading a SSL root certificate in one of the various formats in the Personal page, the file conversion should automatically be done so ownCloud can use it.

**Actual Behavior**
When uploading the .cer file, No error message is logged or displayed, just a red colored bar appears where the root certificate information should display.

**Steps to reproduce**
Upload a root certificate not in the format ownCloud is expecting in the Personal Page under the SSL root certificate section.

**Server configuration**
OC8.0.2
CentOs6.6/Ubuntu 14
MySQL
Apache

**Comment by LukasReschke** [comment]
For clarification purposes: With .cer a DER encoded binary certificate file is meant, currently we can only handle ASCII encoded PEM files.

**Comment by LukasReschke** [comment]
(work-around as discussed meanwhile if someone stumbles upon this as well: `openssl x509 -in rootCA.cer -inform der -outform pem -out rootCA.pem`)

**Comment by gig13** [comment]
@MTRichards

**Comment by DeepDiver1975** [comment]
I'd really like to go the documentation path here and let admins know how to convert the certs properly.

The effort to add more supported certs shall not be underestimated - testing as well.

From my understanding it's quite common to convert certs - thinking about the jave keystore e.g.

**Comment by LukasReschke** [comment]
That would be valid as well. Though we really should show a waning instead of simply failing.

**Comment by DeepDiver1975** [comment]
Yes - proper error handling is required - in any case

**Comment by LukasReschke** [comment]
Will add error-handling and move the static ajax files into controllers to prepare https://github.com/owncloud/core/issues/15518 for the future.

**Comment by LukasReschke** [comment]
And there we go: https://github.com/owncloud/core/pull/15637
