### ISSUE TITLE
[s2s] Files lose permissions when scanner retriggered through publicwebdav.php

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15600]
The goal is to trigger the scanner through publicwebdav.php, because publicwebdav.php is enabling the ReadOnlyWrapper that will modify the permissions when reading from the cache.
Some code paths will read the cache, change values, then put the values again, which will have the wrong permissions when a ReadOnlyWrapper was enabled.

### Steps to reproduce
1. Mount SFTP external storage to "/sftp"
2. Create a folder "/sftp/sharethis"
3. Share "sharethis" with link, keep it read-only
4. Log out
5. Open the link and add it to ownCloud
6. Navigate into "sharethis", see that it's empty.
7. Now go directly to the SFTP folder and put some files into "sharethis".
8. Refresh the web UI to show the contents of "sharethis". You should see the new files appear thanks to the owner's scanner doing its work. (make sure you refreshed as the **recipient**, not the owner)
9. Login as the owner
10. Check the folder "/sftp/sharethis" and try to delete files

### Expected result
The owner's view of "sharethis" must have the correct permissions, and be able to delete files

### Actual result
The scanner was triggered by publicwebdav.php where ReadOnlyWrapper was applied, so the permissions that were used for the new files are wrong (read-only): 17 instead of 27

### Versions
Observed on master (ffa115b51725c4774b49c2419f88cb91d726386b)
Likely to happen on OC 8 too

@icewind1991

**Comment by icewind1991** [comment]
Can you try adding 
```php
public function getScanner($path = '', $storage = null) {
	return parent::getScanner($path, $this->storage);
}
```
to readonlywrapper.php

I've trouble reproducing

**Comment by PVince81** [comment]
I forgot to mention that I mounted SFTP as a personal storage, not global.
To create new files in the SFTP folder, I simply used the "touch" command.
Make sure to NOT update the owner's page after creating the new files, only do the page refresh on the recipient's page (the one that calls publicwebdav.php).

I'll try adding these lines

**Comment by PVince81** [comment]
I had to try several times, adding new folders, new files. That would retrigger the scanner.
Then I see in the DB data the permissions become 17.

After adding these lines and adding files to the sftp subdir, the scanner replaced the 27 with 17, which means that it works.

I guess it should be possible to reproduce this through a unit test.
Should I take care of it and the PR ?

**Comment by PVince81** [comment]
I'll prepare the PR

**Comment by PVince81** [comment]
In the steps I forgot to mention that the web UI must be refreshed as recipient, not as owner.

**Comment by PVince81** [comment]
@icewind1991 I tried it again, it doesn't work as expected.

Whenever I change a file directly on SFTP, it now depends which window I refresh first.
If I refresh the recipient's window first (to trigger the scanner), the files are still read-only for both owner and receiver.
If I refresh the owner's window first (to trigger the scanner), the files are read-wrte for **both** owner and receiver. Or at least they appear so in the web UI.

Looks like the fix will have to be more complex.

**Comment by PVince81** [comment]
Your new approach for the read-only wrapper here https://github.com/owncloud/core/pull/15814 fixes the problem :smile:

**Comment by PVince81** [comment]
Fixed through https://github.com/owncloud/core/issues/15814
