### ISSUE TITLE
Files get corrupted when downloading from owncloud (public link)

### ISSUE THREAD

**Issue by tilllt** [owncloud/core#15603]
System: 
debian wheezy / Linux one 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u2 x86_64 GNU/Linux
PHP 5.5.23-1~dotdeb.2 (cli) (built: Mar 26 2015 02:24:24)
nginx version: nginx/1.6.3
Owncloud 7.0.5

Problem: 
I have a 2.58GB file i prepared for a client to download. I zipped the content into one archive on my Mac. Then i put it on an SMB Volume on my debian server. Owncloud has access to that directory as a local External Storage.

After the client downloaded the file from a public link i sent him via OC, he complained that he couldnt unzip the file since it was corrupted. I started looking into it more systematically and apparently there is a problem.

These are the MD5 hashes:

The original zip file on my mac:
60877b5b1fa036bcaa63a2b1c7b9a73c

As calculated from the debian box for the file copied to the SMB folder:
60877b5b1fa036bcaa63a2b1c7b9a73c

A direct download of the file from nginx
60877b5b1fa036bcaa63a2b1c7b9a73c

And the file after being downloaded from the owncloud link i sent to the client:
904d5b2594b9e64ed6a63addc89559f8

Obviously this could also be a general PHP problem, in any case it is a showstopper for the majority of users that use Owncloud for file exchange purposes.

**Comment by tilllt** [comment]
could be that there is a connection between file size and corruption. tried to recreate the problem with a 1G random content file (openssl rand -out sample.txt -base64 $(( 2**30 * 3/4 )), using the same process i described above and the md5 hashes are correct, also for the file downloaded from the public link.

**Comment by PVince81** [comment]
First let's try and see whether it's related to the SMB external storage: can you try the same operation on the local non-SMB storage ?

When I see 2 GB it often sounds like the 32-bits limit, but I see you have a 64 bits machine.

**Comment by tilllt** [comment]
maybe i was not clear: the directory is not added within Owncloud as a SMB volume. OC sees the local directory, only the transfer from my mac to the debian machine was through a SMB mount to the same dir. i only mentioned this since i thought that maybe the transfer over SMB corrupted the file, which is not the case, since the MD5 hashes on he Debian box and on my mac are identical.

**Comment by derkostka** [comment]
short Info: 
  checked with OC 8.0.3RC1:
  - a share mounted via smb within own cloud (not by linux itself)
  - zipped a file (32mb) on a mac, copied to the share using smb
  - login to oc, share the file via link
  --> md5 is the same, have downloaded the fie on the same mac and also on an android phone

**Comment by tilllt** [comment]
I am not an expert on this but i would assume that transferring a 2.5gb file makes a big difference to transferring a 32mb file.

**Comment by derkostka** [comment]
Right, did you compare the exact file sizes for the 2 GB file ?

For me, the download breaks early (at 1024 MB) because my /tmp folder is full. This is because i did mount the smb share within owncloud, and then, downloads are cached in /tmp ... Maybe this is related with external files somehow ? If not, please mute me *g*

**Comment by tilllt** [comment]
I got 100+ GB free for /tmp so thats probably not the problem in my case.

**Comment by PVince81** [comment]
@tilllt I'm still a bit confused about your setup, can you describe the mount ?

Did you mount a SMB folder directly inside of "/data/$user/files/somedir" on the Linux filesystem, and uploaded files directly there ?

Is the file from the public link served from that mount ?

**Comment by tilllt** [comment]
Ok, i regret mentioning the term SMB at all, since my OC installation does not access the folder containing the file in question via SMB. For Owncloud, there is a local folder on the filesystem. 

For completeness sake, i mentioned that this folder is ALSO an smb share (but not for OC, only for the SAMBA Daemon) - which i used to transport the file from a local mac to the debian server. Hashes on the Mac and on the server were identical, so the mistake is NOT connected to SMB at all.

I could rephrase the problem: When owncloud is serving a 2.58gb file that i send out via a public link, it arrived on the downloaders computer as a corrupted zip. i could recreate that problem by downloading the file through this link, and it was corrupted for me as well. downloading that file just over nginx did not cause the corruption. so it must be either an owncloud OR a php problem.

**Comment by PVince81** [comment]
Okay, understood.

I don't have much idea what this could be.
Did you configure X-Sendfile (or the nginx equivalent) to directly server files ?

I see you have nginx, @josh4trunks have you heard of such issues before ?

**Comment by tilllt** [comment]
No, i did not configure X-Sendfile or the equivalent for Nginx. I just followed the installation instructions, as mentioned here: https://doc.owncloud.org/server/7.0/admin_manual/installation/nginx_configuration.html

**Comment by tilllt** [comment]
The only mention of the configuration of this for nginx is for OC6, here https://doc.owncloud.org/server/6.0/admin_manual/configuration/xsendfile.html

Additionally the nginx config given there as an example, does exactly what is mentioned in the "Pitfalls" document for nginx as a big No-No, defining "root" for multiple locations, which doesnt make it really trustworthy as a guide. http://wiki.nginx.org/Pitfalls

**Comment by josh4trunks** [comment]
@tilllt x-sendfile is covered here
https://doc.owncloud.org/server/8.0/admin_manual/configuration_files/serving_static_files_configuration.html#nginx-x-accel-redirect

note, these docs work with 8.0.3+
the current docs do not violate the nginx pitfalls. though 'method 2' has root defined in a location block it doesn't actually violate it by having root only defined in locations and not im the 'server' block.

**Comment by josh4trunks** [comment]
since @tilllts didn't configure x-sendfile it is obviously unrelated. but, setting it up actually might solve the issue in this case because owncloud/php won't be processing the file.

Im guessing it's a PHP memory limit.

**Comment by tilllt** [comment]
php.ini: memory_limit = 128M

**Comment by PVince81** [comment]
Hmm, I also have 128M on my server and it works fine. (but with Apache2)

**Comment by PVince81** [comment]
This is likely a config issue and not a bug in ownCloud.
Please check http://owncloud.org/support
