### ISSUE TITLE
Enforce expiration date not working correctly if password is enforced

### ISSUE THREAD

**Issue by Norahy** [owncloud/core#15611]
Hi guys,

the enforcement of an expiration date for a link seems to not work correctly if password protection is enforced. I get this behaviour in version 8.0.2, with the following sharing settings:

![image](https://cloud.githubusercontent.com/assets/11943267/7137239/4692c648-e2b8-11e4-977b-4621292015c4.png)

The result is this:
![image](https://cloud.githubusercontent.com/assets/11943267/7137288/9812fb1e-e2b8-11e4-86ca-5d6a87a049aa.png)

Password is enforced, but not the expiration date. Only the message that the link will expire appears. If you send the link per mail, there also is no information about the expiration.

if you disable the password enforcement, the following appears:
![image](https://cloud.githubusercontent.com/assets/11943267/7137317/fcee6aaa-e2b8-11e4-87b6-285a90341d54.png)
The expiration date enforcement works like it should do.

Could you please try to reproduce it?

**Comment by PVince81** [comment]
@rullzer

**Comment by rullzer** [comment]
I think I found the issue. A different code path is taken when the password is enforced. Fix is not that hard. But also here I want to add unit tests to make sure we do not break it later. Hopefully I have time to make a PR tomorrow.

**Comment by rullzer** [comment]
PR in #15738

**Comment by karlitschek** [comment]
Can we get this in?  @DeepDiver1975

**Comment by davitol** [comment]
:+1:
