### ISSUE TITLE
Problems installing Owncloud 8 on Ubuntu 14.04

### ISSUE THREAD

**Issue by edfield** [owncloud/core#15615]
I cannot get OwnCloud to install on Ubuntu 14.04. 

```
#apt-get install owncloud
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
owncloud : Depends: owncloud-server-core
Depends: owncloud-config-apache but it is not going to be installed
Recommends: mysql-server
E: Unable to correct problems, you have held broken packages.
```

```
#lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 14.04.2 LTS
Release: 14.04
Codename: trusty

#mysql -h localhost -V
mysql Ver 14.14 Distrib 5.5.41, for debian-linux-gnu (i686) using readline 6.3

#apachectl -V
Server version: Apache/2.4.7 (Ubuntu)
Server built: Mar 10 2015 13:05:59

#php -v
PHP 5.5.9-1ubuntu4.7 (cli) (built: Mar 16 2015 20:48:03)

#cat owncloud.list
deb http://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_14.04/ /
```

**Comment by nickvergessen** [comment]
@jnweiger packaging issue?

**Comment by edfield** [comment]
Not sure what is going on. The installer recommends mysql-server but doesn't say anything else about it. Current mysql version is 5.5.41 and it is working fine. Manually trying to install mysql-server package results.

#apt-get install mysql-server
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mysql-server : Depends: mysql-server-5.5 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.




Not sure if trying to install owncloud packages individually will have any affect, but I will try whatever you would like to get more information if needed.

**Comment by jnweiger** [comment]
@edfield I'd like to see more diagnostics here. The ...'but it is not going to be installed' message does not say why.
Do you already have some mysql or owncloud packages in your system?
Please show the output of 

    dpkg -l  | egrep 'mysql|owncloud'

Maybe these bring your system in a cleaner state:

    sudo apt-get autoremove
    sudo apt-get autoclean

**Comment by ufechner7** [comment]
Someone closed my issue:
https://github.com/owncloud/core/issues/15689

But I think this is not the same issue. I have problems installing on Ubuntu 12.04, AND I have a different error message.

**Comment by jnweiger** [comment]
@ufechner7 's issue is different: He wants to install owncloud-client.

**Comment by edfield** [comment]
dpkg -l  | egrep 'mysql|owncloud'
ii  libdbd-mysql-perl                    4.025-1                              i386         Perl5 database interface to the MySQL database
ii  libmysqlclient16                     5.1.62-0ubuntu0.11.10.1              i386         MySQL database client library
ii  libmysqlclient18:i386                5.5.41-0ubuntu0.14.04.1              i386         MySQL database client library
ii  mysql-client-5.5                     5.5.41-0ubuntu0.14.04.1              i386         MySQL database client binaries
ii  mysql-client-core-5.5                5.5.41-0ubuntu0.14.04.1              i386         MySQL database core client binaries
ii  mysql-common                         5.5.41-0ubuntu0.14.04.1              all          MySQL database common files, e.g. /etc/mysql/my.cnf
rc  mysql-server-5.1                     5.1.62-0ubuntu0.11.10.1              i386         MySQL database server binaries and system database setup
ii  mysql-server-5.5                     5.5.41-0ubuntu0.14.04.1              i386         MySQL database server binaries and system database setup
ii  mysql-server-core-5.5                5.5.41-0ubuntu0.14.04.1              i386         MySQL database server binaries
ii  php5-mysql                           5.5.9+dfsg-1ubuntu4.7                i386         MySQL module for php5

apt-get autoremove
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be REMOVED:
  linux-headers-3.13.0-39 linux-headers-3.13.0-39-generic
  linux-headers-3.13.0-40 linux-headers-3.13.0-40-generic
  linux-image-3.13.0-39-generic linux-image-3.13.0-40-generic
  linux-image-extra-3.13.0-39-generic linux-image-extra-3.13.0-40-generic
0 upgraded, 0 newly installed, 8 to remove and 0 not upgraded.
After this operation, 445 MB disk space will be freed.
Do you want to continue? [Y/n] n
Abort.

apt-get autoclean
Reading package lists... Done
Building dependency tree
Reading state information... Done

**Comment by edfield** [comment]
Installed new mysql packages that came out for Ubuntu. The reference to mysql-server no longer comes up, but owncloud still fails install. 

# apt-get install owncloud                             
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 owncloud : Depends: owncloud-server-core
            Depends: owncloud-config-apache but it is not going to be installed
E: Unable to correct problems, you have held broken packages.


# dpkg -l | egrep 'mysql|owncloud'
ii  libdbd-mysql-perl                    4.025-1                              i386         Perl5 database interface to the MySQL database
ii  libmysqlclient16                     5.1.62-0ubuntu0.11.10.1              i386         MySQL database client library
ii  libmysqlclient18:i386                5.5.43-0ubuntu0.12.04.1              i386         MySQL database client library
ii  mysql-client-5.5                     5.5.43-0ubuntu0.12.04.1              i386         MySQL database client binaries
ii  mysql-client-core-5.5                5.5.43-0ubuntu0.12.04.1              i386         MySQL database core client binaries
ii  mysql-common                         5.5.43-0ubuntu0.12.04.1              all          MySQL database common files, e.g. /etc/mysql/my.cnf
rc  mysql-server-5.1                     5.1.62-0ubuntu0.11.10.1              i386         MySQL database server binaries and system database setup
ii  mysql-server-5.5                     5.5.43-0ubuntu0.12.04.1              i386         MySQL database server binaries and system database setup
ii  mysql-server-core-5.5                5.5.43-0ubuntu0.12.04.1              i386         MySQL database server binaries
ii  php5-mysql                           5.5.9+dfsg-1ubuntu4.7                i386         MySQL module for php5

**Comment by jnweiger** [comment]
mysql-server 5.1 is flagged 'rc' on your system. This means, that there are config files around, that would be overwritten by installing mysql-server 5.5

The clean way to continue is apt-get purge mysql-server
Autoremove / autoclean do not catch this, unfortunatly. 
I wonder what the config file is. To be safe, make a backup copy of /etc/mysql 
Then try apt-get purge mysql-server; apt-get install -f

**Comment by edfield** [comment]
apt-get purge mysql-server; apt-get install -f
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package 'mysql-server' is not installed, so not removed
The following packages were automatically installed and are no longer required:
  linux-headers-3.13.0-39 linux-headers-3.13.0-39-generic
  linux-headers-3.13.0-40 linux-headers-3.13.0-40-generic
  linux-image-3.13.0-39-generic linux-image-3.13.0-40-generic
  linux-image-extra-3.13.0-39-generic linux-image-extra-3.13.0-40-generic
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-headers-3.13.0-39 linux-headers-3.13.0-39-generic
  linux-headers-3.13.0-40 linux-headers-3.13.0-40-generic
  linux-image-3.13.0-39-generic linux-image-3.13.0-40-generic
  linux-image-extra-3.13.0-39-generic linux-image-extra-3.13.0-40-generic
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

mysql-server is installed and working with other things, so I did this to see if it had any affect.

apt-get install mysql-server
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-headers-3.13.0-39 linux-headers-3.13.0-39-generic
  linux-headers-3.13.0-40 linux-headers-3.13.0-40-generic
  linux-image-3.13.0-39-generic linux-image-3.13.0-40-generic
  linux-image-extra-3.13.0-39-generic linux-image-extra-3.13.0-40-generic
Use 'apt-get autoremove' to remove them.
The following NEW packages will be installed:
  mysql-server
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 11.2 kB of archives.
After this operation, 117 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main mysql-server all 5.5.43-0ubuntu0.12.04.1 [11.2 kB]
Fetched 11.2 kB in 0s (22.6 kB/s)
Selecting previously unselected package mysql-server.
(Reading database ... 246880 files and directories currently installed.)
Preparing to unpack .../mysql-server_5.5.43-0ubuntu0.12.04.1_all.deb ...
Unpacking mysql-server (5.5.43-0ubuntu0.12.04.1) ...
Setting up mysql-server (5.5.43-0ubuntu0.12.04.1) ...

versions installed 

dpkg -l | egrep 'mysql|owncloud'
ii  libdbd-mysql-perl                    4.025-1                              i386         Perl5 database interface to the MySQL database
ii  libmysqlclient16                     5.1.62-0ubuntu0.11.10.1              i386         MySQL database client library
ii  libmysqlclient18:i386                5.5.43-0ubuntu0.12.04.1              i386         MySQL database client library
ii  mysql-client-5.5                     5.5.43-0ubuntu0.12.04.1              i386         MySQL database client binaries
ii  mysql-client-core-5.5                5.5.43-0ubuntu0.12.04.1              i386         MySQL database core client binaries
ii  mysql-common                         5.5.43-0ubuntu0.12.04.1              all          MySQL database common files, e.g. /etc/mysql/my.cnf
ii  mysql-server                         5.5.43-0ubuntu0.12.04.1              all          MySQL database server (metapackage depending on the latest version)
rc  mysql-server-5.1                     5.1.62-0ubuntu0.11.10.1              i386         MySQL database server binaries and system database setup
ii  mysql-server-5.5                     5.5.43-0ubuntu0.12.04.1              i386         MySQL database server binaries and system database setup
ii  mysql-server-core-5.5                5.5.43-0ubuntu0.12.04.1              i386         MySQL database server binaries
ii  php5-mysql                           5.5.9+dfsg-1ubuntu4.7                i386         MySQL module for php5


try to install owncloud again


apt-get install owncloud
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 owncloud : Depends: owncloud-server (= 8.0.3-2) but it is not going to be installed
            Depends: owncloud-config-apache (= 8.0.3-2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.


The system has eGroupware installed. I don't think it modified mysql-server configs, but it does modify apache config.

**Comment by jnweiger** [comment]
Old  mysql-server-5.1 is still there in state rc. It is strange that purge said 
    Package 'mysql-server' is not installed, so not removed

Still I don't see the reason for the "but it is not going to be installed'' message.

**Comment by edfield** [comment]
Can the packages owncloud depends on be installed individually before attempting to install owncloud. If so, installing them might shed more light on the problem.

**Comment by jnweiger** [comment]
@edfield your situation is still that you get 'is not going to be installed' for the packages owncloud-server and owncloud-config-apache, right?

Try: 

   apt-get install owncloud-config-apache
   apt-get install owncloud-server

I am quite at loss here. Just poking in the dark. Sorry.

**Comment by edfield** [comment]
Here are the results, no joy, but it might shed some light on what is happening.

root@little-john:/home/ed# apt-get install owncloud-config-apache
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 owncloud-config-apache : Depends: owncloud-server (= 8.0.4-0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.


install owncloud-server
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 owncloud-server : Depends: php5-pgsql but it is not going to be installed
                   Depends: php5-intl but it is not going to be installed
                   Depends: php5-curl but it is not going to be installed
E: Unable to correct problems, you have held broken packages.


 apt-get install php5-pgsql
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php5-pgsql : Depends: phpapi-20090626+lfs
              Depends: php5-common (= 5.3.10-1ubuntu3.18) but 5.5.9+dfsg-1ubuntu4.7 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by PVince81** [comment]
Is this still an issue with the 8.0.6 or 8.1.1 packages ?

**Comment by edfield** [comment]
Finally gave up on trying to fix the problem in Ubuntu and did a clean Debian install. Owncloud installed without a hitch. The system had gone thru several version upgrades in Ubuntu and something must have gotten screwed up along the way. Instead of trying to continue hunting a ghost it was more time efficient to start over and have something that worked. Thanks for the help anyway.

**Comment by Xenopathic** [comment]
I hate `apt`, it is so easy to get into a dependency hell :disappointed: Glad that you have ownCloud working though @edfield
