### ISSUE TITLE
Theming should be done by implementing an Interface 

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#15614]
Currently you have to check all methods from https://github.com/owncloud/core/blob/master/lib/private/defaults.php but it would be better to have an interface for this to implement simply all the methods 

Ref documentation issue owncloud/documentation#1060

**Comment by MorrisJobke** [comment]
Also related to the demo theme: #4031

**Comment by jancborchardt** [comment]
I agree – why do I have to have all the `public function getSyncClientUrl()` and such in there? It should just be a json file with the variables and the relevant values.

**Comment by PVince81** [comment]
Moving to 9.0 as we're past feature freeze

**Comment by PVince81** [comment]
CC @PhilippSchaffrath if that still makes sense

**Comment by PhilippSchaffrath** [comment]
Using an interface for that would force you to implement all methods. Currently you can only define the ones you actually want to use, all methods you don't define will use a default.

Although i dislike the `defaults.php` approach, providing an interface is no solution.

I'll have a closer look at this and will try to provide a more user friendly solution.

**Comment by PVince81** [comment]
backlog. an estimate would be nice

**Comment by va1entin** [comment]
Nextcloud has a very simple Theming app that allows you to edit the basic stuff that most want to change. Having this in Owncloud would already be a huge advancement compared to the current approach
https://docs.nextcloud.com/server/12/admin_manual/configuration_server/theming.html

**Comment by micbar** [comment]
ownCloud.online has now a basic theming app.
