### ISSUE TITLE
Folder size not sorted by size

### ISSUE THREAD

**Issue by geek65535** [owncloud/core#15618]
The desktop client has an option "choose what to sync," which presents the user with a tree of folders and their sizes. The folders can be sorted by size by clicking the column header. But the client sorts by ASCII value, rather than by size. For instance, it will sort 3.1GiB before 37KiB.

See attached screenshot for an example.
![screenshot_2015-04-14_10-27-43](https://cloud.githubusercontent.com/assets/1102057/7140612/d9451fb2-e291-11e4-8474-67800e75ad8c.png)

**Comment by nickvergessen** [comment]
Reported it to the client repository: https://github.com/owncloud/client/issues/3112
