### ISSUE TITLE
Feature request: Share direct-download links

### ISSUE THREAD

**Issue by StrangeNoises** [owncloud/core#15622]
This almost seems a bit too simple compared to what a lot of people do with their ownclouds; this is a request from someone (me) who really only uses it at a fairly trivial level in a fashion similar to basic DropBox:

I would like to be able to obtain a shared public link to a file in my owncloud, that can then be used to *directly* download that file, with its original filename and mime content type. For eg: directly grabbing with wget/curl, for pasting into a chatroom, or a forum, and have inline viewing work. Similarly to just paste into the URL bar of a browser that is *not* logged in and to directly see or download the file.

Called something like "Share direct link". You get a link something like this:

    https://owncloud.domain.me/owncloud/index.php/s/BLAHbl4hBLAH/my-file.png

So, the path up until the filename is as it is now, the generated link which can be later revoked in the normal way; but it just has appended on the end of it the original filename of the file. Someone, given that link, can then just fetch it and immediately get the file itself, typed as image/png in this case.

At the moment when I want to do this, I have to separately upload the file into my public_html in my webspace (on the same server) but that's *far* less convenient, especially if the "Share direct link" option was available in the finder and not just in the website.

Apologies if this functionality does already exist. If it does, it's not at all obvious (I have looked, several times) and this is therefore a bug report about UX and usability. ;-)

If you go to the download *page* the normal link gives you, the download *link* on there will download a file of the right *type* but called `download`, which isn't terribly useful. Even if that `/download` suffix was instead the original name of the file that would pretty much do what I want, though I'd like Finder integration to directly obtain that link without going to the website.

Even if it was `/download.png` - ie: it takes only the extension from that of the original file without exposing the rest of the filename, that would be enough. eg: for pasting to places which will only take image URLs with the right extension.

**Comment by karlitschek** [comment]
this is already possible. The direct download link can be seen on the public sharing page. Just create a public link, open the page and copy the direct link from this page.

**Comment by donkikos** [comment]
@karlitschek the problem is when you try to download the file by it's direct link e.g. with wget you get file named "download", but not the real file name.

**Comment by DeepDiver1975** [comment]
this is done this way because of security reasons.

**Comment by donkikos** [comment]
Ok I can use --content-disposition key for wget. But in that case I get file name repeated twice in downloaded file.
