### ISSUE TITLE
Unexpected LDAP errors in server log file

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#15621]
### Steps to reproduce

1. Install 8.0.3 enterprise edition
2. Enable the LDAP app and configure it
3. run smashbox test_uploadFiles.py test in a loop using local users and share_sets = 3

### Expected behaviour

There should be no errors in the server log file

### Actual behaviour

I see errors related to LDAP:

```
{"reqId":"96981d7175c576360c5b2a0f8d505619","remoteAddr":"172.18.5.75","app":"PHP","messa
ge":"unlink(\/tmp\/owncloud-ochewo9lqdny\/LDAP-user_ldap-s01-d94e891c5073ba522188dcd74950
51fe): No such file or directory at \/var\/www\/html\/owncloud\/lib\/private\/cache\/file
global.php#58","level":3,"time":"2015-04-14T16:08:49+00:00"}
```

### Server configuration

Ubuntu 14.04
PHP 5.5.9
ownCloud Enterprise Edition 8.0.3 RC1 (testing) and 15577.patch

**Comment by karlitschek** [comment]
@blizzz any idea how this can happen?

**Comment by DeepDiver1975** [comment]
this was already discussed here: https://github.com/owncloud/core/pull/15577#issuecomment-92695064

Basically our global file cache is not save for parallel access - because only LDAP is using it I vote for killing the class and fallback to existing mechanisms like apc memcached etc - basically as already done

**Comment by DeepDiver1975** [comment]
More critical then deleting a cache entry which no longer exists is the fact that a key potentially can be written by two concurrent processes and result in data corruption - needs some analysis.

**Comment by blizzz** [comment]
> Basically our global file cache is not save for parallel access - because only LDAP is using it I vote for killing the class and fallback to existing mechanisms like apc memcached etc - basically as already done

The global file cache is already used as a fallback if a memory based cache is not available. IIRC this will need to be configured explicitely next release → we can drop the file cache with big recommendation to properly set up a membased cache.
