### ISSUE TITLE
dummy encryption module showing up in 8.0.3

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#15624]
### Steps to reproduce

1. Install 8.0.3 complete tarball
2. Go to apps -> not enabled

### Expected behaviour

Should not see dummy encryption module

### Actual behaviour

See dummy encryption module

![p309](https://cloud.githubusercontent.com/assets/8480343/7147455/1298e064-e2c9-11e4-800d-b6931fbc1c3e.PNG)

### Server configuration

Ubuntu 14.04
PHP 5.5.9
ownCloud Enterprise Edition 8.0.3 RC1 (testing)

**Comment by jnfrmarks** [comment]
I double checked that I installed 8.0.3:

![p310](https://cloud.githubusercontent.com/assets/8480343/7147562/cbcd4714-e2c9-11e4-945b-7681d3b686e6.PNG)

**Comment by jnfrmarks** [comment]
@SergioBertolinSG 

Can you double check this?  It's really weird ...

Thanks!

**Comment by karlitschek** [comment]
This is really strange. If I download this file and look into the apps folder I don´t see any dummy app.
http://download.owncloud.com/internal/8.0.3RC1/owncloud-enterprise-complete-8.0.3RC1.zip

It is present in the current enterprise master build of course. The name is encryption_dummy
http://download.owncloud.com/internal/owncloud-daily-enterprise-complete-master.tar.bz2

Not sure I understand.

**Comment by nickvergessen** [comment]
Downloaded the first package from frank above and checked stable8
I don't see the dummy app here

**Comment by SergioBertolinSG** [comment]
I have installed 8.0.3rc1 from tarball and I don't see that app enabled nor disabled.

Perhaps it was uncompressed in a path with a previous installation which had that dummy app?

**Comment by DeepDiver1975** [comment]
Jennifer: is the app somewhere in the apps folders of that installation? 

Was there previously an 8.1 installation on that system?

**Comment by jnfrmarks** [comment]
I will double check this when I get into the office.  I was installing both versions yesterday.  I'll close this for now and reopen if there is still an issue.

**Comment by jnfrmarks** [comment]
To follow up, I have confirmed that there was an error in my install script.  I was mixing up daily and stable8.
