### ISSUE TITLE
available size doesn't increase after partition resize

### ISSUE THREAD

**Issue by rbcouture** [owncloud/core#15620]
Using VMWare, I created a new VM, (300Gb allocated)
Installed Ubuntu Server LTS14.04 (x64)
Installed owncloud from packages successfully
Connected the first (admin -> unlimited quota) user to a test pc and successfully synchronized 75Gb (so more than 100Gb is still free)

I decided to increase the partition size now to test it before hitting the 300Gb wall:
In vmware: shutdown the vm, increase disk size to 500Gb
Booted from GParted Live cd, I had to deactivate the partition.
Increase the partition to 500Gb.
Reboot in Ubuntu-Owncloud
sudo pvdisplay show PV size of 500Gb
Accessing the webpage, login using the first (admin) user. 
Go to personal, still shows:
You have used 75 GB of the available 300 GB

but shouldn't it be:
You have used 75 GB of the available 500 GB
?

**Comment by RealRancor** [comment]
Hi,

what is the output of:

df -h

entered in the console of your VM? I bet its still saying 300GB for the / (root) partition.

**Comment by rbcouture** [comment]
you are right

**Comment by RealRancor** [comment]
Hi,

feel free to close this issue as it is clearly not an ownCloud bug. Maybe ask in a linux specific forums how to resize a partition correctly or use your favorite search engine to find some tutorials.

**Comment by Xenopathic** [comment]
Sounds like you are using LVM. You need to resize the VM disk, then the LVM partition (you've done up to this point), then the actual filesystem underneath. Until the system reports a larger disk size (with `df`) ownCloud can't use it :smile:

**Comment by rbcouture** [comment]
You are right,

For anyone else on the web stumbling upon this:
After extending the partition with GParted, I opened the console in GParted and ran lvextend -L+200G then resize2fs

this link helped me:
http://ubuntuforums.org/showthread.php?t=1537569
