### ISSUE TITLE
[OC8.0.2.] "Only variables should be passed by reference at /lib/private/cache/fileglobalgc.php#50"

### ISSUE THREAD

**Issue by Wikinaut** [owncloud/core#15627]
Log files entries à la 

"Only variables should be passed by reference at /lib/private/cache/fileglobalgc.php#50"

indicate a problem in the current code.

* oc server 8.0.2
* php 5.5.15

**Comment by RealRancor** [comment]
Seems to be already fixed in OC 8.0.3: https://github.com/owncloud/core/issues/15010#issuecomment-83210123
