### ISSUE TITLE
Public API to work with trashbin

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15646]
OCS or WebDAV, whichever is better suited.

Need to be able to:
1) List files in trashbin
2) Delete files permanently
3) Restore files

**Comment by PVince81** [comment]
@karlitschek can we schedule this ? Required for automated tests of versions.
If we had the tests it would have detected regressions like this one https://github.com/owncloud/core/issues/15009#issuecomment-100936118

**Comment by karlitschek** [comment]
I agree that it would be a very good idea. Time is tight. Let´s see what we can do :-/

**Comment by DeepDiver1975** [comment]
Still voting for webdav - we are talking about files ...

**Comment by PVince81** [comment]
True, this requires discussing the right API format first.
I just don't want this task to get lost, so setting to backlog for now.

**Comment by PVince81** [comment]
While we could design an API for the current trashbin access, it might not be future proof if we decide to move forward to the "per storage trashbin" concept: https://github.com/owncloud/core/issues/12274#issuecomment-246617302
If we do, the endpoint in question might require additional path sections to specify the storage from which to read the trashbin.

**Comment by PVince81** [comment]
If we stay with the current trashbin, I'd suggest the following format:

- base endpoint: https://host/owncloud/remote.php/dav/files_trashbin/$user/
- trashed files listed by file id: https://host/owncloud/remote.php/dav/files_trashbin/$user/$fileId
- a PROPFIND on the file id element will return the file name as "oc:name" property. This is needed because there might be multiple files with the same name but with different deletion timestamp
- new property "oc:deleted_time" for the deletion timestamp
- deleted folders also appear with "$fileId", so a subfile would look like: https://host/owncloud/remote.php/dav/files_trashbin/$user/$folderFileId/$subFileId

@DeepDiver1975 @davivel @nasli @dragotin @guruz

**Comment by PVince81** [comment]
- another optional property: "oc:original-path" that returns the path to which the file would be restored

**Comment by PVince81** [comment]
- PROPFIND **could** maybe also return more metadata like tags/shares if it makes sense
- restore a file by calling MOVE https://host/owncloud/remote.php/dav/files_trashbin/$user/$fileId and specifying the value from "oc:original-path" as "Destination" header. Need conflict handling with the proper headers and handling of 409 response in case the file exists (like regular MOVE)
- delete a file/folder from trash by calling DELETE https://host/owncloud/remote.php/dav/files_trashbin/$user/$fileId
- empty the whole trashbin by calling DELETE https://host/owncloud/remote.php/dav/files_trashbin/$user/ ?

**Comment by PVince81** [comment]
Now thinking of it, if we did design a trashbin that is storage specific, I'd suggest that we rewrite the whole trashbin app as a separate app with a different name, in which case the endpoint name would also change.

**Comment by PVince81** [comment]
- [ ] blocked by https://github.com/owncloud/core/issues/26195

**Comment by PVince81** [comment]
- whenever a file is deleted from the regular Webdav endpoint with DELETE, an additional header "Content-Location" could be returned with the location of the trashed file on the "files_trashbin" endpoint. (the header only appears if trashbin app is enabled)

**Comment by WanpengShao** [comment]
@PVince81 @karlitschek   Excuse me, sir. I am using libcurl(C++) library to visit owncloud. Now I can put files into trashbin by libcurl, but there it no way to restore/completely delete files in trash bin, I read the help document in official website, and searched a lot by google. But I still found no information about these. So have you finished the public API work with trashbin? thank you.

**Comment by PVince81** [comment]
@WanpengShao there is no public API for trashbin yet

**Comment by WanpengShao** [comment]
@PVince81  Thanks for replying me. So what should I do to restore/completely delete files in trashBin ? Is there any trick way to do this?I get a help from https://stackoverflow.com/questions/46211099/how-to-delete-file-in-trash-in-owncloud, but it is difficult for me to get the token and execute other actions in C++.

**Comment by WanpengShao** [comment]
@PVince81 Thanks for replying me.
So what should I do to restore/completely delete files in trashBin ? Is there any trick way to do this?I get a help from https://stackoverflow.com/questions/46211099/how-to-delete-file-in-trash-in-owncloud, but it is difficult for me to get the token and execute other actions in C++.
And I still have a questions:
I want to do the break point upload, but when I stop the upload, and click continue to upload. The uploaded file are over written. I felt depressed when I try a lot of times. Is there any way to do break point upload?

**Comment by karlitschek** [comment]
@WanpengShao Thanks for mentioning me. But I'm no longer involved in owncloud. But we can discuss this for Nextcloud here https://github.com/nextcloud/server/issues if you want.

**Comment by DeepDiver1975** [comment]
@WanpengShao we will soon release a public api to access file versions. Next on the schedule is a public api for trashbin.

As of now there is no way to interact with the trashbin from out side owncloud.

**Comment by PVince81** [comment]
@WanpengShao for development questions, please ask on https://central.owncloud.org/c/development and ping me there. You could use the private APIs for now...

**Comment by PVince81** [comment]
estimate: 4d including API acceptance tests

**Comment by DeepDiver1975** [comment]
this is implemented and we are done
