### ISSUE TITLE
Get a white screen trying to access files via webdav in the browser

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#15648]
### Steps to reproduce

1. Install 8.1
2. Navigate to files page
3. Expand setting on lower left
4. Grab URL for WebDAV
5. Enter URL in another browser

### Expected behaviour

Expect to get access to files

### Actual behaviour

Get a white screen

There is nothing in the server log.

### Server configuration

Ubuntu 14.04
PHP 5.5.9
ownCloud Enterprise Edition 8.1 pre alpha (daily) Build:2015-04-15T03:08:27+00:00 e33e5b425aae5013407083d94d3b03401ade5795

**Comment by PVince81** [comment]
AFAIK the browser plugin was removed, so it is not possible to view the file list from WebDAV any more in the web browser. You should however be able to download files if you use the URL pointing at the file.

CC @LukasReschke

**Comment by PVince81** [comment]
Not sure if the white screen is fixable, because the browser does a GET on that URL and we probably don't want to return an HTML error page as it might mess up the sync client ?

**Comment by LukasReschke** [comment]
Well, actually the white page is the expected behaviour. That said, technically it should be possible to show a page with a message but not sure if it is worth to add more hacks for it :)

**Comment by LukasReschke** [comment]
(WebDAV defines a GET on collections as invalid and thus we don't show anything at all – the browser plugin did also not match our security expectations and thus it was removed for 8.1)

**Comment by karlitschek** [comment]
yes. This is the expected behavior.

**Comment by RealRancor** [comment]
Btw. this is also documented here: https://github.com/owncloud/core/wiki/ownCloud-8.1-Features

**Comment by jnfrmarks** [comment]
I understand that we've made a change but we have to somehow let the customer know what the change is and that the url will not work anymore - or not put the url in the webdav field at all.  A white screen is not a good user experience.  I'm reopening for us to address the user experience.

**Comment by karlitschek** [comment]
@LukasReschke Is there a way to show an error message in the browser?

**Comment by LukasReschke** [comment]
> @LukasReschke Is there a way to show an error message in the browser?

With black magic and so on everything is possible. At least if it is plain-text and does not require fancy templating, which means the ownCloud design won't be there but a white page with a text ;-) - But a simple "This is the WebDAV backend and can only be used by WebDAV clients and not be displayed in the browser." is something we can do without *too* much magic. – Text okay?

**Comment by karlitschek** [comment]
@LukasReschke Yes. This would be great! Thanks :-)

**Comment by LukasReschke** [comment]
Sure. Let me do this tomorrow… Busy trying to investigate with https://github.com/owncloud/enterprise/issues/445 with a few other folks :-(

**Comment by jnfrmarks** [comment]
I vote for removing this from the UI completely.

![p314](https://cloud.githubusercontent.com/assets/8480343/7166704/72ec1076-e37d-11e4-9d2a-58857ba8dc3d.PNG)

**Comment by karlitschek** [comment]
Well. this is the url to mount it. :-)

**Comment by PVince81** [comment]
or add a hint that this is a URL only for WebDAV clients

**Comment by RealRancor** [comment]
As this was closed: Is there a new issue to track that a note is added to the remote.php ?

**Comment by jnfrmarks** [comment]
No

**Comment by RealRancor** [comment]
Ref: https://github.com/owncloud/core/issues/16359

Without such a note i can already see tons of bugreports and forum posts :see_no_evil:

**Comment by MorrisJobke** [comment]
Fixed in #16364
