### ISSUE TITLE
Mouse over should display whole text 

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#15643]
### Steps to reproduce

1. Install 8.0.3 complete
2. Navigate throughout the UI

### Expected behaviour

Text that is wider than field width is fully displayed when mouse-d over

### Actual behaviour

Text that is wider than field width is not fully displayed when mouse-d over

 
![p313](https://cloud.githubusercontent.com/assets/8480343/7160839/90616990-e359-11e4-9296-f3031701c146.PNG)

### Server configuration

Ubuntu 14.04
PHP 5.5.9
ownCloud Enterprise Edition 8.0.3 RC1 (testing)

**Comment by karlitschek** [comment]
@jancborchardt

**Comment by PVince81** [comment]
@owncloud/designers

**Comment by jancborchardt** [comment]
In this case I would say it should only say »Windows Network Drive«. Titles in the sidebar should be kept concise.
