### ISSUE TITLE
Clicking on the theming link gets a 404

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#15649]
### Steps to reproduce

1. Install 8.1
2. Navigate to admin page
3. Click on Tip and Tricks
4. Click on Theming

### Expected behaviour

Expect to get re directed to theming documentation

### Actual behaviour

Get a 404

http://doc.owncloud.com/server/8.0/developer_manual/core/theming.html

### Server configuration

Ubuntu 14.04
PHP 5.5.9
ownCloud Enterprise Edition 8.1 pre alpha (daily) Build:2015-04-15T03:08:27+00:00 e33e5b425aae5013407083d94d3b03401ade5795

**Comment by PVince81** [comment]
Without the EE theme the link seems to work.

There doesn't seem to be any developer manual on doc.owncloud.com.

@carlaschroder any idea ?

**Comment by carlaschroder** [comment]
Because the dev manuals are not on doc.owncloud.com. I can't think of a reason to not have them there, so give me a few and I'll fix that.

**Comment by carlaschroder** [comment]
ok then, links should work for developer manuals on 8.0 and 8.1
