### ISSUE TITLE
Work directly on storage in chunk upload mode

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15647]
Follow up from: https://github.com/owncloud/core/pull/12006

This needs to be done for the chunking mode too.

@icewind1991 as discussed here https://github.com/owncloud/core/pull/12006/files#r28233056

@DeepDiver1975 8.1 or 8.2 ?

**Comment by karlitschek** [comment]
How Intrusive would this be?

**Comment by PVince81** [comment]
As intrusive as the original fix for non-chunking mode: https://github.com/owncloud/core/issues/12006

**Comment by PVince81** [comment]
assuming that the part file assembling is the one that goes directly to the storage instead of using the view. It shouldn't be too different to the other one. It's just that the code is partly duplicated in other places.

**Comment by PVince81** [comment]
Looks like we might need this for the files locking to work, to avoid double locking.

**Comment by PVince81** [comment]
@icewind1991 didn't you have a PR for this already ? Or maybe I mixed it up with something else.

**Comment by icewind1991** [comment]
https://github.com/owncloud/core/pull/17811 does chunk assembly direct on the storage

**Comment by PVince81** [comment]
Right, that was the one. I was confused because it combined the lock fix as well.

Closing.
