### ISSUE TITLE
Remote user's avatar not updated in share dialog after avatar is modified

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#15657]
### Steps to reproduce

1. Install 8.1
2. Upload a file
3. Share with a local user and with a remote user
4. Change the local user and remote user avatars
5. Refresh the share dialog

### Expected behaviour

Avatars reflect new avatars

### Actual behaviour

Just the local user's avatar is refreshed; the remote user remains the same.

### Server configuration

Ubuntu 14.04
PHP 5.5.9
ownCloud Enterprise Edition 8.1 pre alpha (daily) Build:2015-04-15T03:08:27+00:00 e33e5b425aae5013407083d94d3b03401ade5795

**Comment by nickvergessen** [comment]
I assume we cache the avatar, since it's an external image, to not poll the other server unnecessarily

**Comment by rullzer** [comment]
We do not retrieve remote avatars yet. As there are some security things to consider. So for now we just use the generated avatar for remote shares.

But we are working on it :).

**Comment by nickvergessen** [comment]
@rullzer there is a ticket for this, so we can close this one as duplicate/superseded ?

**Comment by rullzer** [comment]
Yes there is #14564
