### ISSUE TITLE
Reapply search when switching sections in apps page

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15651]
### Steps
1. Go to apps page
1. Type in a search term, for example "storage"
1. Switch to "Not enabled" section

### Expected
Search/filter must still be applied to the newly selected section

### Actual
Search field still contains the value, but no search is applied. I need to type something in the field to retrigger it.

@owncloud/designers

**Comment by jancborchardt** [comment]
Totally agree. Any search should be reset when switching the section and the search field should be emptied.

cc @butonic @icewind1991

**Comment by jancborchardt** [comment]
Even better would be to search across categories in the first place: https://github.com/owncloud/core/issues/16003
