### ISSUE TITLE
oc8 seems to drag ubuntu server down on high client sync loads

### ISSUE THREAD

**Issue by finius** [owncloud/core#15659]
I'm sorry to give such an unspecific misbehavior, but I'm hardly able to reproduce this behaviour nor to explain what the exact reason for this is. Let me give some facts on the situation to give an impression of what's going on:
- oc8 runs virtualized on a single ubuntu 14.04 LTS server with 4 cores on a new Dell PowerEdge R730xd, 4GB on a 20GB hdd with about 50% free space left. storage of the data dir is mounted into linux from a Windows network share. CPU and RAM are operating in the lowest 10% of their given server ressources.
- oc8 is performing fine when operating in regular daily business (normal sync loads - about 2-3GB a day by 50 users)
- performance problems always seems to occurs when users are (initially) uploading/downloading huge amounts of personal data (>10GB), in a stronly nested folder hierarchy, at a time using the owncloud sync client for Windows (even in version 1.8).
- The sync client gets disconnected from the server after a while with a "socket operation timeout" error. When trying to login to the owncloud server, you might get a blackscreen (hang) OR you're facing network HTTP problems concerning the apace/oc8, although the performance key indicators (RAM, SWAP, HDD, CPU) seem to be within normal ranges.
- system parameters are unsuspicious at any time (much free RAM, much free SWAP, etc) - except HTTP response times on the apache port of oc8 which exceed 1500ms in case of the fault which is described here.

Summarized you can say, that owncloud seems to stop operating in the server side when huge sync loads are proceeded on the sync client over a longer period of time (some hours) - even if the server system itself seems to continue operating normal. Just a quick reboot puts the server back to normal operation - until a critcal amout of sync load had been processed again.

**Comment by karlitschek** [comment]
This is a system configuration issue.
The recommendation is to configure the MxcClients setting in apache to an value that doesn´t use too much system ressources. For example if MaxClients are reach then the system should still enough free memory and don´t swap.
I recommend to ask more questions in the ownCloud forum.
