### ISSUE TITLE
Keep current section in hash/URL in apps page

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15650]
### Steps:
1. Go to the apps page
2. Select a section, for example "Recommended"
3. Refresh the browser page

### Expected
Still in "Recommended" section

### Actual
Back to the "Enabled" section

Optionally the search term could also be kept in the URL so that the search stays. That might become more relevant in the future when there are more apps.

@owncloud/designers

**Comment by jancborchardt** [comment]
Yes, agreed.
