### ISSUE TITLE
OC 8.0.3 filesize() stat failed trying to add any external storage

### ISSUE THREAD

**Issue by derkostka** [owncloud/core#15658]
### Steps to reproduce

* Try to mount a SMB or local share within the Owncloud settings
* The green light will indicate, the share is okay (destination found, credentials match)
* Change to files, the share has not been stored

### Expected behaviour

The share shall be stored and accessible

### Actual behaviour

The share is not stored

#### Server configuration

Operating system: Ubuntu 14.04
Web server: apache2
Database: mySQL
PHP version: PHP 5.5.9-1ubuntu4.5
ownCloud version: Owncloud 8.0.3-RC1
Updated from an older ownCloud or fresh install: update to 8.0.3-rc1 manually from 8.0.2 (ubuntu .debs)
Are you using external storage: yes, local file system and oc-smb mounts
Are you using encryption: no

Logs

```
"app":"PHP","message":"filesize(): stat failed for \/media\/shared\/ at
\/var\/www\/owncloud\/lib\/private\/largefilehelper.php#179"
```

**Comment by PVince81** [comment]
@derkostka can you tell us more about the SMB server you are connecting to ? Is it a Linux or Windows machine ?

**Comment by PVince81** [comment]
When you say "any" external storage, does it mean you also get it with SFTP ?

**Comment by DeepDiver1975** [comment]
32 bit issue? @bantu

**Comment by bantu** [comment]
@derkostka Please make sure you have the curl PHP extension installed and enabled.

**Comment by derkostka** [comment]
Sorry for the delay ..
The SMB share i tried to connect to is a linux server (my netgear router).
I tried mounting  this via a local folder (router->mounted in linux->mounted by owncloud) and a smb mount directly from router->owncloud. curl-php is installed.
However, meanwhile i updated to 8.1-alpha1 and the problem is gone. 
Can´t you reproduce this ?
I am about to setup a "test-cloud basd on 8.0.3-rc1" and will report back asap

**Comment by derkostka** [comment]
Sorry guys, a have setup a second oc 8.0.3-rc1, no problems no error messages ... shall we close this one ? i can´t reproduce unfortunately :-1:

**Comment by bantu** [comment]
Yes, please. No problem.

**Comment by jeffhoffman13** [comment]
Hmmm  upgrade from 8.0.2 to 8.0.3 external storage assignments get a green light however if I go to files and click on the folder nada.  Go back in admin and check external storage I set up it's gone..

**Comment by jeffhoffman13** [comment]
More info:
Fatal	core	Invalid OCS content returned for app user_external	2015-05-07T19:20:12+00:00
Fatal	core	Invalid OCS content returned for app external	2015-05-07T19:20:05+00:00

**Comment by bantu** [comment]
@jeffhoffman13 Not sure how what you describe is relevant to this ticket. Please see whether there is a ticket for your issue and create a new one if necessary.
