### ISSUE TITLE
[enc2] API / OCC to enable encryption + select encryption module

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15667]
To be able to automate setup for automated tests and also deployments, it is necessary to provide an API and/or CLI command to make it possible to enable the encryption module.

In the past, enabling encryption was only about enabling the "files_encryption" app.
Since 8.1 and encryption 2.0, enabling the "encryption" app is not enough. Admins need to go to the admin page and tick "enable encryption". An API/CLI command need to be provided to do this programmatically.

@schiesbn @th3fallen @DeepDiver1975 

CC @jnfrmarks

**Comment by DeepDiver1975** [comment]
A bunch of cli commands will be necessary:

encryption:enable
encryption:disable
encryption:list-modules
encryption:set-default-module

**Comment by nickvergessen** [comment]
Could also be possible to do that with config:add/set etc, but I guess having encryption:* additional doesn't hurt and saves to remember the name of the config

**Comment by jnfrmarks** [comment]
Is this a usability issue for customers?  Do we want to try to get this in for 8.1?

**Comment by DeepDiver1975** [comment]
> Is this a usability issue for customers? Do we want to try to get this in for 8.1?

Hmm .... I have not really any idea - but we need this ourselves for test automation - so at least enable and disable can be in the scope of 8.1

**Comment by nickvergessen** [comment]
I will have a look at this then
