### ISSUE TITLE
Feature request: Output necessary debug data from backend

### ISSUE THREAD

**Issue by BinaryCoder87** [owncloud/core#15661]
Whenever you need to send a bug report or ask for support (in the forum), you need to specify specific data like server, database etc. It would be nice if you could just press a button at the backend, to generate those data. In best case you have several reports to generates, which helps you and your supporters to find the problem fast and easy.

**Comment by Xenopathic** [comment]
We have a work-in-progress implementation of this, thanks to @LukasReschke : track the progress over at #13258
