### ISSUE TITLE
Error 64, 80; 138, 140

### ISSUE THREAD

**Issue by BinaryCoder87** [owncloud/core#15662]
I got four recurring error messages in my log:

```
Error   PHP   filemtime(): stat failed for /store/ownclouddata//***/files/***/***/Promostuff/Visitenkarte.tiff at /var/www/owncloud/lib/private/files/storage/local.php#138   2015-04-14T14:58:15+00:00
Error   PHP   Undefined index: storage_mtime at /var/www/owncloud/lib/private/files/cache/watcher.php#67   2015-04-14T14:58:15+00:00
Fatal   files_encryption   set shareFileKeyFailed (code: 80): Cannot mutliKeyDecrypt empty plain content   2015-04-13T20:21:48+00:00
Error   PHP   Undefined index: /store/ownclouddata/***/files_encryption/keys/transfer/*****_DAB/***.JPG at /var/www/owncloud/apps/files_locking/lib/lockingwrapper.php#140   2015-04-13T14:43:51+00:00
```

Environment VM on a VServer
Server Apache / Ubuntu server 14.04.2 LTS
Database mysql  Ver 14.14
Client Chrome
Versions of OwnCloud and PHP OC 8.0.2 PHP 5.5.9
Fresh install

``` php
<?php
$CONFIG = array (
  'instanceid' => 'ocy1tiu4p5c2',
  'passwordsalt' => '***',
  'secret' => '***',
  'trusted_domains' => 
  array (
    0 => '***',
  ),
  'datadirectory' => '/store/ownclouddata/',
  'overwrite.cli.url' => 'https://***/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.2.0',
  'installed' => true,
  'forcessl' => true,
  'maintenance' => false,
  'dbname' => '***',
  'dbhost' => 'localhost',
  'dbuser' => '**',
  'theme' => '',
  'loglevel' => 1,
);
```

encryption yes
external storage no
external interface no

**Comment by karlitschek** [comment]
@icewind1991 can you have a look?

**Comment by PVince81** [comment]
@BinaryCoder87 any specific steps to trigger the error ?

@schiesbn for the missing key error

**Comment by BinaryCoder87** [comment]
Friend of mine told me, that every time he tries to share something, he got troubles with the webinterface.

**Comment by PVince81** [comment]
troubles as in... error messages ?

Maybe try to unshare the file then reshare again, if there are other recipients.
Maybe the recipient's encryption keys are broken somehow.
Is he able to share with other people ? Is it specific to one recipient ?

**Comment by PVince81** [comment]
Closing due to lack of feedback
