### ISSUE TITLE
Cron.php update fails when server-side encryption is enabled

### ISSUE THREAD

**Issue by efelon** [owncloud/core#15664]
Owncloud 8.0.2
News 5.2.8
Server-side Encryption 0.7.1

Symptom was, that news were not updated after enabling encryption app. Cron.php itself returns with: {"status":"success"}

Log entry with encryption enabled:
{"reqId":"116981ce9c21dcd8e43eed629c4fcb94","remoteAddr":"x.x.x.x","app":"no app in context","message":"Error while running background job: Could not determine user","level":3,"time":"2015-04-16T07:01:16+00:00","method":"GET","url":"\/ocnew\/cron.php"}

Had already a chat with "Raydiation" about this.

**Comment by DeepDiver1975** [comment]
Is the search app enabled? Try disabling it - anyhow pointless with encryption enabled ...

**Comment by efelon** [comment]
I just had a look in the admins app menu and didn't see an app related or named with search in enabled or not enabled.

**Comment by psych0d0g** [comment]
i have exactly the same problem
Owncloud: 8.0.3
News 5.2.8
Server-side Encryption 0.7.1

**Comment by DeepDiver1975** [comment]
@schiesbn can you please have a look how encryption can impact this? thx

**Comment by schiesbn** [comment]
I will have a look at it

**Comment by schiesbn** [comment]
btw, the readme from the news app state that they don't support server side encryption: https://github.com/owncloud/news/blob/master/README.md

Don't know why and doesn't really make sense to me. Anyhow, I will check if I can reproduce it and if it is something we can/should fix on our side.

**Comment by schiesbn** [comment]
The PR above should fix it... @efelon @psych0d0g maybe you can give it a try and report back if it solves the issue for you? Thanks!

**Comment by DeepDiver1975** [comment]
fixed in #17001
