### ISSUE TITLE
Encryption app is enabled by default in 8.0.3RC2

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#15665]
### Steps to reproduce
Install 8.0.3RC2 version from tarball.

### Expected behaviour
Disabled by default.

### Actual behaviour
Enabled by default.

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.0.3.1","versionstring":"8.0.3 RC2","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
Default in enterprise version

**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password and passwordsalt)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** 
yes, but i didn't want to

### Client configuration
**Browser:**
Chrome

**Comment by DeepDiver1975** [comment]
@nickvergessen can I ask you to verify/analyze this? THX

**Comment by SergioBertolinSG** [comment]
No need to, my mistake, I used an existing database. With a different one it is disabled but default.
