### ISSUE TITLE
Improve apps management with compatibility labels

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#15676]
App dependencies and app trust levels will be part of 8.1, but users would benefit from additional labels which would indicate whether or not an app is compatible with the device they're going to use the GUI with.
Filtering the app store using labels would clearly indicate to users which apps should work and they would probably feel more inclined to fill bug reports if something is off.
### Browsers

Browser compatibility labels would be really useful, since there are a few well known apps which don't run on IE per example, despite the fact that oC claims IE compatibility and that man hours are allocated to fixing bugs related to IE8.

A policy should be defined, stating that
- Official apps are required to run on all 3 major desktop browsers
- Approved apps are only required to indicate on which browsers they run

Not enforcing such policy means that the user experience will slowly degrade over months.
### Mobile

A mobile compatibility label would indicate whether the app can be used as is on mobile.

**Comment by jancborchardt** [comment]
I like parts of this, but parts are also too much. Let’s see:

> Official apps are required to run on all 3 major browsers

Which major browsers do you mean? Safari for iOS mobile, Chrome for Android mobile, Chrome for Desktop, and Firefox for Desktop?
This seems a bit like over-management at this point. We’re at a too early stage in the appstore to restrict it like this and make it difficult for app developers. Sure it would be great if every app would work flawlessly on mobile and on Internet Explorer – but volunteers often simply don’t have time for that.

The app not working on Firefox or Chrome would be a K.O. criteria of course, but it not working on IE8 is honestly not something we should really reprimand.

Now with the mobile label I agree to some extent. It’s similar for the Firefox Marketplace. It could be a positive label, as in an app gets it when it works on mobile as well.

cc @LukasReschke @karlitschek

**Comment by oparoz** [comment]
I meant the 3 major desktop browsers (FF, Chrome, IE), since there are mobile apps available and since we can introduce the mobile label for people who can't use the apps.

The reason to include IE in the official apps QA criteria is because the core team is spending time to maintain IE8 workarounds, so it has to be because official apps support it, otherwise resources are best allocated elsewhere.
From my pov, the core team should only focus on IE11 and make sure all official apps support it by introducing quality criteria for app statuses.

**Comment by PVince81** [comment]
@DeepDiver1975 please take note for the marketplace if interesting, closing here
