### ISSUE TITLE
output_buffering = 4096 is not detetced to be invalid

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#15671]
@LukasReschke

**Comment by LukasReschke** [comment]
I removed, `php_value output_buffering off` from the `.htaccess` and set it to 4096 in my php.ini, after clearing the cookies (session stores the results), I get the error screen as expected.

Are you sure it is set to 4096? Can you verify using a phpinfo in the same directory?

**Comment by LukasReschke** [comment]
Just FTR: I am on master.

**Comment by DeepDiver1975** [comment]
I'm using occ and in php.ini I have 

```
output_buffering = 4096

**Comment by LukasReschke** [comment]
`output_buffering` does not affect the CLI, see http://php.net/manual/en/outcontrol.configuration.php:

> *output_buffering boolean/integer*
 > You can enable output buffering for all files by setting this directive to 'On'. If you wish to limit the size of the buffer to a certain size - you can use a maximum number of bytes instead of 'On', as a value for this directive (e.g., output_buffering=4096). **As of PHP 4.3.5, this directive is always Off in PHP-CLI.**

**Comment by DeepDiver1975** [comment]
> output_buffering does not affect the CLI, see http://php.net/manual/en/outcontrol.configuration.php:

so occ check is kind of pointless

**Comment by LukasReschke** [comment]
> so occ check is kind of pointless

Depends on what we want to do with it. In most linux distributions the CLI does anyways use another php.ini file than the web server. If it is a check to ensure that the PHP settings are correct for the webserver: Yes. Will probably not help.

**Comment by DeepDiver1975** [comment]
@dragotin @jnweiger looks like we can revert the check command - pointless

**Comment by dragotin** [comment]
@DeepDiver1975 well, no! Remember we wanted to replay the checks that you do on the admin page to detect php modules available or not.

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 well, no! Remember we wanted to replay the checks that you do on the admin page to detect php modules available or not.

But the results will be different as this case shows.

**Comment by DeepDiver1975** [comment]
Background: there are two php.ini - one for cli one for the web server - the output will not be reliable

**Comment by dragotin** [comment]
can you make the CLI thing load the same as the web server? We should be able in packages.

**Comment by dragotin** [comment]
ie. start the cli script by a shell script that, before it starts the php interpreter, checks the usual locations of php.ini and than starts the php interpreter with the correct ini file? Maybe...

**Comment by DeepDiver1975** [comment]
this is all :hankey:

**Comment by LukasReschke** [comment]
To sum up: We would have to add a parser for php.ini files and actually *parse* the content :see_no_evil:

**Comment by dragotin** [comment]
@DeepDiver1975 no, it's doable:
```
[kf:~/owncloud.com/buildmirall] $ php --help
Usage: php [options] [-f] <file> [--] [args...]
...
  -c <path>|<file> Look for php.ini file in this directory
  -n               No php.ini file will be used
  -d foo[=bar]     Define INI entry foo with value 'bar'
...
```
There are even shell scripts out in the wild that detect the distro  its running on, so you know for sure where the correct ini is.

**Comment by LukasReschke** [comment]
http://php.net/manual/en/function.parse-ini-file.php - oh you huge hack :see_no_evil:

**Comment by LukasReschke** [comment]
@dragotin That won't help. PHP overwrites some settings when it runs in CLI mode despite what it says in php.ini.

**Comment by LukasReschke** [comment]
(not for all but for stuff like `output_buffering`… :( )

**Comment by LukasReschke** [comment]
(or we just don't care about some stuff that it ignores :see_no_evil:)

**Comment by LukasReschke** [comment]
> ie. start the cli script by a shell script that, before it starts the php interpreter, checks the usual locations of php.ini and than starts the php interpreter with the correct ini file? Maybe...

As discussed with @dragotin this should be a feasible solution and requires some magic in the packaging scripts. – Won't detect 100% of the stuff such as `output_buffering` but for that we have our `.htaccess` which hardcodes some changed settings, so should be good enough :tm:

**Comment by DeepDiver1975** [comment]
> As discussed with @dragotin this should be a feasible solution and requires some magic in the packaging scripts. – Won't detect 100% of the stuff such as output_buffering but for that we have our .htaccess which hardcodes some changed settings, so should be good enough :tm:

whatever - I guess we can close this ticket

**Comment by jnweiger** [comment]
Idea:
Enhance status.php so that it can run all the checks.
Then let occ check just do a curl http://localhost/owncloud/status.php?check=json or equivalend.

**Comment by MorrisJobke** [comment]
> Then let occ check do a curl http://localhost/owncloud/status.php?check=json or equivalent.

seriously? :-1:

**Comment by DeepDiver1975** [comment]
> whatever - I guess we can close this ticket

closing
