### ISSUE TITLE
Ext storage config must not validate before backend selection

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15687]
### Steps to reproduce
1. Enable ext storage app
2. Allow mounting SFTP storages
3. Login as another user
4. Type in "sftp" as mount point (do not select any backend)
5. Click outside
### Expected result

Nothing happens
### Actual result

Spinner appears, then red square
### Versions

ownCloud git master (aef6ecdbf1fbe748acb64bcf8d1abdf14ea51e97)

@Xenopathic I thought you fixed that last time ?

**Comment by Xenopathic** [comment]
Hmm, I thought I had. Perhaps I only fixed the problem when tabbing out of a row (that was the timer thing). There must be an `if` statement not being hit or something.

**Comment by PVince81** [comment]
I saw this one again lately on master (8.2rc1) with personal storages

**Comment by PVince81** [comment]
And saw this recently on master / 9.0 too. Setting to 9.1

**Comment by PVince81** [comment]
Use save button instead: https://github.com/owncloud/core/issues/22479
