### ISSUE TITLE
[enc2] Cannot upload to external storage

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15688]
### Steps
1. Enable encryption + default enc module
2. Mount either a global SFTP storage or local one (personal)
3. Upload a file

### Expected
File uploaded

### Actual
Error notification appears: path needs to be relative to the system wide data folder and point to a user specific file
Nothing in the log.

### Version
ownCloud master (aef6ecdbf1fbe748acb64bcf8d1abdf14ea51e97)

@schiesbn @th3fallen please have a look

**Comment by schiesbn** [comment]
can't reproduce it, works here wit current master

**Comment by PVince81** [comment]
Did you use SFTP for it ?

Note that this is setup from scratch, not done any migration.

**Comment by schiesbn** [comment]
indeed, it only happens on sftp... tested with ftp before. I will debug it.

**Comment by schiesbn** [comment]
fixed in master
