### ISSUE TITLE
  Problems reading files after OC 7.0.4 -> 8.0.2

### ISSUE THREAD

**Issue by jimlei** [owncloud/core#15684]
### Steps to reproduce
1. install OC 7.0.4 and enable encryption
2. upload files
3. upgrade to OC 8.0.2

### Expected behaviour
OC works as expected

### Actual behaviour
OC can't read files

### Server configuration
**Operating system**: Debian 7

**Web server: ** Apache/2.2.22

**Database:** MySQL 5.5.38

**PHP version:** 5.4.4

**ownCloud version:** 8.0.2

**Updated from an older ownCloud or fresh install:** updated from working 7.0.4

**List of activated apps:** calendar, contacts, documents, files, files_encryption, files_pdfviewer, files_sharing, files_texteditor, files_trashbin, files_versions, files_videoviewer, firstrunwizard, gallery, updater

**The content of config/config.php:**
```php
<?php
$CONFIG = array (
  'instanceid' => 'oc59305178e7',
  'passwordsalt' => '',
  'trusted_domains' => 
  array (
    0 => 'cloud.jimleirvik.no',
  ),
  'datadirectory' => '/mnt/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.0.2.0',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '',
  'installed' => true,
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
  'secret' => '',
);
```

**Are you using external storage, if yes which one:** cifs/smb

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome/Firefox

**Operating system:**

#### Web server error log
```
deleted it but current usage logs nothing
```

#### ownCloud log (data/owncloud.log)
```
...
{"reqId":"23e4350ec1ff2086b11f4ef5b5c373c9","remoteAddr":"77.110.204.166","app":"PHP","message":"json_encode(): Invalid UTF-8 sequence in argument at \/srv\/www\/owncloud\/lib\/public\/util.php#99","level":3,"time":"2015-04-17T07:04:30+00:00"}
{"reqId":"23e4350ec1ff2086b11f4ef5b5c373c9","remoteAddr":"77.110.204.166","app":"index","message":"Exception: {\"Message\":null,\"Code\":110,\"Trace\":\"#0 \\\/srv\\\/www\\\/owncloud\\\/apps\\\/files_encryption\\\/lib\\\/stream.php(355): OCA\\\\Files_Encryption\\\\Crypt::multiKeyDecrypt('f{g????6????$??...', '7??2?*??W\\\/???S?...', '-----BEGIN PRIV...')\\n#1 \\\/srv\\\/www\\\/owncloud\\\/apps\\\/files_encryption\\\/lib\\\/stream.php(278): OCA\\\\Files_Encryption\\\\Stream->getKey()\\n#2 [internal function]: OCA\\\\Files_Encryption\\\\Stream->stream_read(8192)\\n#3 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(283): fread(Resource id #436, 8192)\\n#4 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(606): OC\\\\Files\\\\View->readfile('\\\/\\\/HelloWorld-de...')\\n#5 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/private\\\/files.php(155): OC\\\\Files\\\\Filesystem::readfile('\\\/\\\/HelloWorld-de...')\\n#6 \\\/srv\\\/www\\\/owncloud\\\/apps\\\/files\\\/ajax\\\/download.php(37): OC_Files::get('\\\/', Array, false)\\n#7 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/srv\\\/www\\\/ownclo...')\\n#8 [internal function]: __lambda_func(Array)\\n#9 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('?lambda_253', Array)\\n#10 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/base.php(767): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/aja...')\\n#11 \\\/srv\\\/www\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/srv\\\/www\\\/owncloud\\\/apps\\\/files_encryption\\\/lib\\\/crypt.php\",\"Line\":444}","level":4,"time":"2015-04-17T07:04:30+00:00"}
{"reqId":"c7eb94be127ba14cb4e95361c26040b4","remoteAddr":"77.110.204.166","app":"PHP","message":"json_encode(): Invalid UTF-8 sequence in argument at \/srv\/www\/owncloud\/lib\/public\/util.php#99","level":3,"time":"2015-04-17T07:05:40+00:00"}
{"reqId":"c7eb94be127ba14cb4e95361c26040b4","remoteAddr":"77.110.204.166","app":"index","message":"Exception: {\"Message\":null,\"Code\":110,\"Trace\":\"#0 \\\/srv\\\/www\\\/owncloud\\\/apps\\\/files_encryption\\\/lib\\\/stream.php(355): OCA\\\\Files_Encryption\\\\Crypt::multiKeyDecrypt('f{g????6????$??...', '7??2?*??W\\\/???S?...', '-----BEGIN PRIV...')\\n#1 \\\/srv\\\/www\\\/owncloud\\\/apps\\\/files_encryption\\\/lib\\\/stream.php(278): OCA\\\\Files_Encryption\\\\Stream->getKey()\\n#2 [internal function]: OCA\\\\Files_Encryption\\\\Stream->stream_read(8192)\\n#3 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(283): fread(Resource id #436, 8192)\\n#4 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(606): OC\\\\Files\\\\View->readfile('\\\/\\\/HelloWorld-de...')\\n#5 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/private\\\/files.php(155): OC\\\\Files\\\\Filesystem::readfile('\\\/\\\/HelloWorld-de...')\\n#6 \\\/srv\\\/www\\\/owncloud\\\/apps\\\/files\\\/ajax\\\/download.php(37): OC_Files::get('\\\/', Array, false)\\n#7 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/srv\\\/www\\\/ownclo...')\\n#8 [internal function]: __lambda_func(Array)\\n#9 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('?lambda_3', Array)\\n#10 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/base.php(767): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/aja...')\\n#11 \\\/srv\\\/www\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/srv\\\/www\\\/owncloud\\\/apps\\\/files_encryption\\\/lib\\\/crypt.php\",\"Line\":444}","level":4,"time":"2015-04-17T07:05:40+00:00"}
```

#### Browser log
```
GET https://cloud.jimleirvik.no/index.php/apps/files/ajax/download.php?dir=/&files=HelloWorld-debug.apk

500 INTERNAL SERVER ERROR
empty response

Cache-Control: must-revalidate, post-check=0, pre-check=0
Connection: close
Content-Disposition: attachment; filename*=UTF-8''HelloWorld-debug.apk; filename="HelloWorld-debug.apk"
Content-Length: 2775063
Content-Type: application/vnd.android.package-archive
Date: Fri, 17 Apr 2015 07:05:40 GMT
Expires: 0
Pragma: public
Server: Apache/2.2.22 (Debian)
Strict-Transport-Security: max-age=31536000
X-Frame-Options: Sameorigin
X-Powered-By: PHP/5.4.4-14+deb7u14
X-Robots-Tag: none
X-XSS-Protection: 1; mode=block
content-security-policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *; connect-src *
content-transfer-encoding: binary
x-content-type-options: nosniff
```

**Comment by DeepDiver1975** [comment]
@schiesbn some old encryption issue? THX

**Comment by jimlei** [comment]
@DeepDiver1975 Thanks for the quick tagging of the issue.

I'd appreciate if someone could point me in the direction of how to resolve this. Sadly I had too much data to back it all up, so now I have a bunch of encrypted data that I'm unable to access. Hopefully all isn't lost yet :)

**Comment by PVince81** [comment]
Can you check if the encryption keys exist for the files you are trying to access ? Then compare the keys location with the files that do work. Maybe something went wrong during migration of the keys to the new location.

You should be able to restore the keys from the backup folder.

Did you happen to run into a timeout during the update ? (did you do it on the cli with ./occ upgrade or on the web UI ?)

**Comment by jimlei** [comment]
I had a web ui time out and then ran it in cli.

![screenshot from 2015-05-19 13 31 17](https://cloud.githubusercontent.com/assets/4523053/7701858/76afda4e-fe2b-11e4-9d1e-ea53456c41f4.png)

steam.png works, test.odt doesn't

**Comment by PVince81** [comment]
If you had a timeout then it means that only part of the files were migrated.
@schiesbn does the cli migration tool would resume migration or does a flag need to be set ?

**Comment by PVince81** [comment]
Please try running `./occ encryption:migrate-keys`. It should hopefully migrate the remaining keys.

**Comment by cmonteroluque** [comment]
@jimlei any luck with @PVince81's suggestion?

**Comment by jimlei** [comment]
@cmonteroluque @PVince81 Thought I had commented, oh well. I ran the command using the owncloud user and it ran through all the users (listed them green, big data users took forever). still in the same situation as before though.

**Comment by schiesbn** [comment]
Looking at the screenshot here https://github.com/owncloud/core/issues/15684#issuecomment-103452090  all keys seems to be at the right location.

Are those files located at the external storage? Was the external storage mounted in the users personal settings or as system wide mounts in the admin settings?

**Comment by schiesbn** [comment]
Just saw that the files on the screenshot are located at the root of your files folder. So they are probably stored on the local storage and not on the external storage, right?

**Comment by schiesbn** [comment]
It is also confusing that the error message from the exception in your lock is 'null'. The exception comes from here: https://github.com/owncloud/core/blob/v8.0.2/apps/files_encryption/lib/crypt.php#L444 where we add a message to the exception, especially the output of 'openssl_error_string()' would be really useful in this case. Can you double-check that this line looks the same on your server?

**Comment by jimlei** [comment]
@schiesbn /mnt/owncloud/data is external storage, mounted there with nfs.

**Comment by schiesbn** [comment]
@jimlei thanks... ok, but from the ownCloud point of view it is a 'local' storage, so the key paths should be OK.

**Comment by jimlei** [comment]
@schiesbn true, here's the file in question

```
root@debcloud:/srv/www/owncloud# sed -n '440,450p' apps/files_encryption/lib/crypt.php 

			return $plainContent;

		} else {
			throw new Exception\MultiKeyDecryptException('multiKeyDecrypt with share-key' . $shareKey . 'failed: ' . openssl_error_string(),
					Exception\MultiKeyDecryptException::OPENSSL_OPEN_FAILED);
		}

	}
```

**Comment by schiesbn** [comment]
@jimlei can you try to add this line right before the "throw new...":

````
\OCP\Util::writeLog('Encryption library', 'multiKeyDecrypt with share-key' . $shareKey . 'failed: ' . openssl_error_string(), \OCP\Util::ERROR);
````

Then try to open the broken file again and post the output from your owncloud.log here. Thanks!

**Comment by schiesbn** [comment]
By the way, what I just saw while looking at your initial bug report. Did the broken file already existed before the upgrade to 0C8 or was it uploaded after the upgrade? Is there any pattern, like old files work and new uploads doesn't, the other way around or is it random?

**Comment by jimlei** [comment]
````
{"reqId":"c0be482fa70410e6674d0d9f7212aa1a","remoteAddr":"192.168.1.1","app":"PHP","message":"json_encode(): Invalid UTF-8 sequence in argument at \/srv\/www\/owncloud\/lib\/private\/log\/owncloud.php#83","level":3,"time":"2015-05-29T18:15:30+00:00"}
{"reqId":"c0be482fa70410e6674d0d9f7212aa1a","remoteAddr":"192.168.1.1","app":"Encryption library","message":null,"level":3,"time":"2015-05-29T18:15:30+00:00"}
{"reqId":"c0be482fa70410e6674d0d9f7212aa1a","remoteAddr":"192.168.1.1","app":"PHP","message":"json_encode(): Invalid UTF-8 sequence in argument at \/srv\/www\/owncloud\/lib\/public\/util.php#99","level":3,"time":"2015-05-29T18:15:30+00:00"}
{"reqId":"c0be482fa70410e6674d0d9f7212aa1a","remoteAddr":"192.168.1.1","app":"index","message":"Exception: {\"Message\":null,\"Code\":110,\"Trace\":\"#0 \\\/srv\\\/www\\\/owncloud\\\/apps\\\/files_encryption\\\/lib\\\/stream.php(355): OCA\\\\Files_Encryption\\\\Crypt::multiKeyDecrypt('T??Y?YyD???y\\\\3#...', '2??9B?#1e???7G?...', '-----BEGIN PRIV...')\\n#1 \\\/srv\\\/www\\\/owncloud\\\/apps\\\/files_encryption\\\/lib\\\/stream.php(278): OCA\\\\Files_Encryption\\\\Stream->getKey()\\n#2 [internal function]: OCA\\\\Files_Encryption\\\\Stream->stream_read(8192)\\n#3 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(283): fread(Resource id #436, 8192)\\n#4 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(606): OC\\\\Files\\\\View->readfile('\\\/\\\/Test.odt')\\n#5 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/private\\\/files.php(155): OC\\\\Files\\\\Filesystem::readfile('\\\/\\\/Test.odt')\\n#6 \\\/srv\\\/www\\\/owncloud\\\/apps\\\/files\\\/ajax\\\/download.php(37): OC_Files::get('\\\/', Array, false)\\n#7 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/srv\\\/www\\\/ownclo...')\\n#8 [internal function]: __lambda_func(Array)\\n#9 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('?lambda_3', Array)\\n#10 \\\/srv\\\/www\\\/owncloud\\\/lib\\\/base.php(767): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/aja...')\\n#11 \\\/srv\\\/www\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/srv\\\/www\\\/owncloud\\\/apps\\\/files_encryption\\\/lib\\\/crypt.php\",\"Line\":445}","level":4,"time":"2015-05-29T18:15:30+00:00"}
````

All new files seem to work

Old files does _not_ work

**Comment by jimlei** [comment]
Hm. I had a test account with some dummy files in them. Same story, old files did not work, new files did.

I then did a password change, and got a "invalid key file, update your password in your personal settings".

I then entered the old password + the new password to reset the key, which was successful.

This account can now access old files.

Should this be safe to do on other accounts (one has 300 GB of data)?

**Comment by schiesbn** [comment]
Wow, that's strange. Resetting the password by providing the old and the new one means that ownCloud just decrypt your private key with the old password and then encrypt it again with the new one. If it works afterwards it means that all keys where OK, right from the beginning and you could also decrypt your private key because otherwise it wouldn't be possible to reset the password and you would have get the ""invalid key file, update your password in your personal settings". warning already before.

I would try it on the other accounts but before you do it make a backup of the users private and public keys. The public keys are stored in ````data/files_encryption/public_keys```` for all users and the private keys are stored for each user individuell in ````data/<user>/files_encryption/<user>.privateKey````

**Comment by jimlei** [comment]
@schiesbn have no idea why that worked. perhaps I was mistaken (though I tried several files without being able to read them before resetting.

Resetting my main accounts password does not give me the "invalid key file" message, and I'm now allowed to "update it", like I was with the other account.
