### ISSUE TITLE
Set theme on Admin page

### ISSUE THREAD

**Issue by fcturner** [owncloud/core#15697]
I work a lot with theming as I think it's the ultimate way for making edits to the ownCloud instance files.

But whenever an update comes forth, ownCloud disables the theme during the update. Afterwards, it's not being restored, causing me to SSH-ing to my config.php and typing the theme name by hand. So maybe these two things aren't a bad idea:
- A fix to this issue so the theme get restored after an update
- An option on the admin page to set a theme, based on all directories found in owncloud/themes. 

The latter is a big wish, since it would allow testing with different (versions of) themes within the same owncloud instance.

**Comment by DeepDiver1975** [comment]
> A fix to this issue so the theme get restored after an update

The theme is not enabled for a good reason - themes can cause breakage of an installation after upgrade. Therefore re-enabling the theme is a manual step.

**Comment by DeepDiver1975** [comment]
> An option on the admin page to set a theme, based on all directories found in owncloud/themes.

This will not work - thinking about a clustered setup: the change will be written only to one confg.php.
Furthermore - we are experiencing a lot of issues just because ownCloud is writting to config.php by itself - we need to reduce such calls.

**Comment by DeepDiver1975** [comment]
@fcturner your requests are not wrong - just to explain the current situation - I see no point in fixing this short term -> backlog

**Comment by fcturner** [comment]
I see... Thanks for replying and clarifying!

**Comment by fcturner** [comment]
Just wanted to let people know that I created an app to accomplish the second suggestion:
https://github.com/fcturner/theme_switcher

Available on the App Store too. Supports all versions of ownCloud server 8 (since I didn't test OC7 and OC9 isn't out yet :smile:)

**Comment by DeepDiver1975** [comment]
I guess this can be closed now

**Comment by fcturner** [comment]
Well, now you rely on an app developer instead of maintaining this yourself (as ownCloud core team). So what if I decide to stop updating my app after OC8?

I agree this can be close for now, but I think you should really mention this feature in a meeting and take a decision if this should be maintained by the ownCloud core. Especially since it ships with an example theme! 

I think ownCloud is a \*really\* great product used by thousands and thousands of companies around the globe, as you obviously know (might be nice to add a download counter on the main download page :smile:). Although I think it should be much easier to change the look and feel of it by a GUI (which is a lot of work), you should really stimulate using themes, for example by implementing my app.

Just to drop the idea :thought_balloon:

**Comment by fcturner** [comment]
This won't be read anymore. Nice.

**Comment by jancborchardt** [comment]
@fcturner to reply in this issue rather than the other one where you referenced this:

> Well, now you rely on an app developer instead of maintaining this yourself (as ownCloud core team).

Exactly – we can not do everything ourselves. :) It’s awesome that folks like you step up to the plate and develop apps which are useful for people.
There are not as many core developers as you think, and it’s difficult to maintain what we have already and then on top develop new great stuff.

Hope that explains why this is closed. You developed an app which takes care of the use-case, hence we don’t really need it in core until a majority of people really ask for it. But the thing is that enabling a theme is an almost-only-one-time action and only something an admin will do. Hence it’s not really anything for core.

**Comment by fcturner** [comment]
I must admit that I indeed thought there was a core developers army :smile: 

This helped a lot, thank you.
