### ISSUE TITLE
Apps has empty category lists

### ISSUE THREAD

**Issue by pascalBokBok** [owncloud/core#15709]
the apps page  should not show empty categories such as Game and multimedia.

**Comment by jancborchardt** [comment]
Well, actually I would say this is more of a bug which we should polish for 8.1. Don’t you think @karlitschek @LukasReschke? Otherwise it looks pretty stupid and people will think our appstore is very empty.

(@pascalBokBok good suggestion!)

**Comment by LukasReschke** [comment]
Well… The appstore *is* pretty empty with regard to the [games category](https://apps.owncloud.com/index.php?xcontentmode=923) or no apps have been been configured to be compatible such as for the Multimedia category. Adjusting this would just be yet another request to every category when loading the appstore and making it even slower as far I can tell. I'd like to avoid this if not absolutely necessary at the moment.

What would help here is if the appstore could return all informations at once such as we only have to request a big blob and don't have to send a request for everything on it's own. Other ideas are at https://github.com/owncloud/core/issues/15851#issuecomment-95937246 to make it a faster experience.

**Comment by pascalBokBok** [comment]
@LukasReschke Sounds like a pretty crazy API you are working against.
Otherwise - you can always scrape it from the front-page of apps.owncloud.com with 1 request - it has the app quantity in the title attributes of the category menu ;-)

**Comment by pascalBokBok** [comment]
BTW. I'm running 8.0 and for me the game and multimedia categories are entirely empty but the "Apps"-store loads in ~10seconds

**Comment by oparoz** [comment]
Approved apps are now showing in the app store, so we can close this.
There is one caveat, apps which target multiple versions of ownCloud cannot be updated at this point.

**Comment by pascalBokBok** [comment]
Sounds good. A few details would be nice though.
From which Owncloud version?
Approved by whom?

**Comment by jancborchardt** [comment]
@pascalBokBok by the review team, which everyone is very welcome to join. Come to our IRC channel **#owncloud-app-review**
Also, the empty category lists are tracked at https://github.com/owncloud/appstore-issues/issues/26
