### ISSUE TITLE
Fix illogical storage location method names

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#15703]
The storage ID definitions [found here](https://github.com/owncloud/core/wiki/Storage-IDs) help developers figure out what those IDs mean.

The problem is that when we're trying to use what's at our disposal to identify where a folder is located, it doesn't work as expected.
#### Expectation
- Only returns true for folders hosted in the data folder
- Returns true for storage with the ID "local::"
- Returns true for shares belonging to the same instance
### Actual behaviour
- Always returns false for folders hosted in the data folder on 8.1 https://github.com/owncloud/core/issues/15548
- Returns false for local shares on 8.0+
#### Expectation

Returns references to storage which is mounted
### Actual behaviour

https://github.com/owncloud/core/blob/master/lib/private/files/fileinfo.php#L255

An ID starting with "local::" should not be considered mounted, but, from the definitions, _"If you use the files_external you could also mount local folder into your ownCloud. In this case also a local:: storage is created."_
Which means we're not getting those mounted folders.

On top of that, an external share is not considered mounted, which is confusing.
## What can be done

I can understand that a method is needed to know whether we have a direct access to files and folder, so that we can pick the right tools to manipulate them, but calling it isLocal is confusing. We already have isEncrypted(), but maybe we need to introduce a method called isProxied() or hasDirectAccess()?

We also need another method which can help us figure out where the node is located and whether or not it's collected via the network or not.
- An external share is much slower than a local one, but both are identified as "shared"
- A mounted SMB folder can be quite fast, but one which requires to make HTTP requests probably won't be, so why ID them all as "local::"

Apps which need to collect specific files in order to present them to the user in a different GUI (Documents, Gallery, etc.) need to know whether the files can be fetched quickly or not because fetching files which take several seconds or even minutes each to retrieve is simply killing the user experience.

**Comment by PVince81** [comment]
@DeepDiver1975 so we want to rename isLocal() to a new name in 8.1 and change the public API ? Basically deprecate isLocal() and add a new method "canAccessFileDirectly()" and deprecate the old one ?

**Comment by oparoz** [comment]
I think isLocal() should stay true to its definition or you're breaking the API. That's what has almost happened with 8.1

The PHPDoc says:
```

	/**
	 * Returns whether the storage is local, which means that files
	 * are stored on the local filesystem instead of remotely.
	 * Calling getLocalFile() for local storages should always
	 * return the local files, whereas for non-local storages
	 * it might return a temporary file.
	 *
	 * @return bool true if the files are stored locally, false otherwise
	 * @since 7.0.0
	 */
```
