### ISSUE TITLE
Cleanup storage of incoming external share

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#15701]
- getting a remote share (either via share dropdown and user@remote or via public link page and "Add to my owncloud")
- unshare this folder
### Expected behaviour
- Database entries are cleaned up (storage and filecache)
### Actual behaviour
- Storage and filecache is still filled
### How to test this

Following queries list the tables joined together (for MySQL)

Map `shared::` storage to external share:

``` sql
SELECT * FROM oc_storages s LEFT JOIN oc_share_external e ON s.id = CONCAT('shared::', MD5(CONCAT(e.share_token, '@', e.remote))) WHERE s.id LIKE 'shared::%';
```

List only not existing external share storages:

``` sql
SELECT * FROM oc_storages s LEFT JOIN oc_share_external e ON s.id = CONCAT('shared::', MD5(CONCAT(e.share_token, '@', e.remote))) WHERE s.id LIKE 'shared::%' AND e.id IS NULL;
```

**Comment by MorrisJobke** [comment]
cc @schiesbn @icewind1991

**Comment by MorrisJobke** [comment]
Be prepared same behaviour if external server doesn't have the folder anymore - maybe keep it for this case.

cc @butonic

**Comment by PVince81** [comment]
The question is whether to do this on the fly as soon as the share is auto-removed or in a background job.

**Comment by butonic** [comment]
Careful, we need to be fault tolerant with remote shares because ... "the tubes might just be blocked". Whan user A an site X shared a folder to usen B at site Y there are four scenarios:

1. user A unshares the folder
2. user B doas not accept the share
3. user B deletas the share
4. site Y might not be reachable for an unknown period of time

2 & 3 are basically the same, which leaves us with three cases that we *should* treat differently:

1. site X tells site Y it deleted the share
2&3. site Y tells site X it deleted the share 
4. no communication possible

This has different consequences:

1. can be as easy as answering with 403 or 404 when site Y tries to scan site X, no active message necessary
2&3. either site Y makes an http call to site X or we show a "last seen" date in the "shared by you" list so that a user can delete obsolete shares
4. well we can only show the "last seen" date here as well.

Thinking about this it might make sense to show a "last working" date for case 1. That allows user B to contact user A and reactivate the share ... maybe a firewall got in between. Or if A no longer likes B, he can decide to delete the share.

@jancborchardt do I make sense?

**Comment by jancborchardt** [comment]
Yeah, we definitely have to account for the »connection problems« case.

**Comment by PVince81** [comment]
@butonic we already have this code in place. We are already able to distinguish between "temporary unavailable" (StorageNotAvailableException) and "share is definitely gone" (StorageInvalidException). The "share is definitely gone" situation is detected when connecting to "shareinfo.php" which will return a WebDAV 404 or 403 (not a regular HTML 404 or 403).

In the case of "share is definitely gone", there is code to auto-unmount it. But that code doesn't delete the oc_storages entry. See here: https://github.com/owncloud/core/blob/master/apps/files_sharing/lib/external/storage.php#L186

**Comment by PVince81** [comment]
CC @icewind1991

**Comment by PVince81** [comment]
I think it should be easier to delete this entry at the time where we explicitly remove the mount point, here: https://github.com/owncloud/core/blob/v8.1.1/apps/files_sharing/lib/external/storage.php#L189
Because that is the moment where we know exactly what storage it is we are removing.

Basically need to extend that `removeShare` method to also clear the "oc_storages" and "oc_filecache" for that entry.

**Comment by PVince81** [comment]
I just noticed that @MorrisJobke already had some queries to reverse-resolve the storage ids to external shares. This means that the background job approach is also possible.

**Comment by MorrisJobke** [comment]
Blue coming from #23931

**Comment by PVince81** [comment]
In some cases it can even happen that people have reshared the incoming fed share mount point. If we provide a bkg job to delete the orphaned "shared::" entries, it would also delete the oc_filecache entries that match it. And then, the later existing job that clears orhpaned oc_share entries with orphaned file_source (pointing to fileid), it would also remove those.

Sounds like a plan.

**Comment by PVince81** [comment]
PR for clearing oc_storages directly at deletion time: https://github.com/owncloud/core/pull/26490

**Comment by PVince81** [comment]
And now another blocker: LDAP.
When users are deleted from LDAP they become "zombies" or "remnants" and need to be deleted with `occ user:delete`. However when doing so, it is not possible to call `initMountPoints()` for such users to cleanup their homes or access mounts points, getting this:
```
{"reqId":"PNmySHv8Gvs9viLgax2x","remoteAddr":"","app":"no app in context","message":"Exception: {\"Exception\":\"OC\\\\User\\\\NoUserException\",\"Message\":\"c3dd75d8-2feb-1036-8aa3-0f5fbaaee22f is not a valid user anymore\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/User\\\/User.php(260): OCA\\\\User_LDAP\\\\User_LDAP->getHome('c3dd75d8-2feb-1...')\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Mount\\\/LocalHomeMountProvider.php(41): OC\\\\User\\\\User->getHome()\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Config\\\/MountProviderCollection.php(97): OC\\\\Files\\\\Mount\\\\LocalHomeMountProvider->getHomeMountForUser(Object(OC\\\\User\\\\User), Object(OC\\\\Files\\\\Storage\\\\StorageFactory))\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php(432): OC\\\\Files\\\\Config\\\\MountProviderCollection->getHomeMountForUser(Object(OC\\\\User\\\\User))\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/Hooks.php(35): OC\\\\Files\\\\Filesystem::initMountPoints('c3dd75d8-2feb-1...')\\n#5 [internal function]: OCA\\\\Files_Sharing\\\\Hooks::deleteUser(Array)\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/hook.php(105): call_user_func(Array, Array)\\n#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Server.php(251): OC_Hook::emit('OC_User', 'pre_deleteUser', Array)\\n#8 [internal function]: OC\\\\Server->OC\\\\{closure}(Object(OC\\\\User\\\\User))\\n#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Hooks\\\/EmitterTrait.php(98): call_user_func_array(Object(Closure), Array)\\n#10 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Hooks\\\/PublicEmitter.php(32): OC\\\\Hooks\\\\BasicEmitter->emit('\\\\\\\\OC\\\\\\\\User', 'preDelete', Array)\\n#11 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/User\\\/User.php(198): OC\\\\Hooks\\\\PublicEmitter->emit('\\\\\\\\OC\\\\\\\\User', 'preDelete', Array)\\n#12 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/core\\\/Command\\\/User\\\/Delete.php(63): OC\\\\User\\\\User->delete()\\n#13 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/symfony\\\/console\\\/Command\\\/Command.php(256): OC\\\\Core\\\\Command\\\\User\\\\Delete->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#14 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/symfony\\\/console\\\/Application.php(818): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#15 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/symfony\\\/console\\\/Application.php(186): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\User\\\\Delete), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#16 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/symfony\\\/console\\\/Application.php(117): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#17 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Console\\\/Application.php(158): Symfony\\\\Component\\\\Console\\\\Application->run(NULL, NULL)\\n#18 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/console.php(99): OC\\\\Console\\\\Application->run()\\n#19 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/occ(11): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#20 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps3\\\/user_ldap\\\/lib\\\/User_LDAP.php\",\"Line\":331}","level":3,"time":"2016-10-26T18:00:23+00:00","method":"--","url":"--","user":"--"}
```

**Comment by PVince81** [comment]
@butonic backport required for this new command ?

**Comment by butonic** [comment]
backport to 9.0.x requested.

**Comment by PVince81** [comment]
Ok thanks. Please review my test adjustments in the PR and I'll backport.

**Comment by PVince81** [comment]
The command https://github.com/owncloud/core/pull/26379 has been added in 9.0.8 and 9.1.4.

Is that solution sufficient or do we want to spend more time on https://github.com/owncloud/core/pull/26490 which is blocked due to a chicken-egg problem regarding deleted users ?

**Comment by PVince81** [comment]
I'm closing this now, if more work is needed, please reopen.

Here is a documentation ticket: https://github.com/owncloud/documentation/issues/2843
