### ISSUE TITLE
Call to undefined method Sabre\HTTP\Request::setUrl()

### ISSUE THREAD

**Issue by BlackLotus** [owncloud/core#15712]
Got a little owncloud setup with lighttpd + fastcgi on my gentoo server.
I get owncloud from git and when I try to run the latest commits I get
> 2015-04-17 21:45:46: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Fatal error:  Call to undefined method Sabre\HTTP\Request::setUrl() in /var/www/owncloud/htdocs/apps/files/appinfo/remote.php on line 41
The only similar problems I found googling were packaging errors in debian.
Do I have to install a special package for sabre?It seems to be an OC specific thing.

**Comment by DeepDiver1975** [comment]
How did you install owncloud? From git? Some distro packages?

**Comment by PVince81** [comment]
Please use the issue template: https://raw.github.com/owncloud/core/master/issue_template.md

**Comment by DeepDiver1975** [comment]
Either packaging error, missing git submodule or server miss configuration. 

Please reopen if neither of the mentioned. Thx

**Comment by BlackLotus** [comment]
Sorry for that.You were right I didn't update the submodules.
I just pulled it from git and didn't think about that when updating.
Thanks
