### ISSUE TITLE
SQLSTATE[HY000]: General error: 1 cannot commit transaction - SQL statements in progress

### ISSUE THREAD

**Issue by manaaaaa** [owncloud/core#15711]
Hello ,

i tried to upgrade owncloud from 7.02 to 8.02 .
But then i get the error Message:
SQLSTATE[HY000]: General error: 1 cannot commit transaction - SQL statements in progress

What should i do ?

-greetings

**Comment by karlitschek** [comment]
Can you post a full bug report using this template please?
https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by RealRancor** [comment]
Very likely a dup of: https://github.com/owncloud/core/issues/14911 and https://github.com/owncloud/core/issues/14398

**Comment by manaaaaa** [comment]
I fixed it myway : 

i installed it directly with this instructions :
http://wiki.qnap.com/wiki/Category:OwnCloud

Thanks for help.
