### ISSUE TITLE
8.1 trusted_domain new feature 

### ISSUE THREAD

**Issue by ZVonFeng** [owncloud/core#15719]
Hi, I understand without trusted_domain it has a lot more security issues. 
But what if I want to access my owncloud from a cafe or restaurant, or just somewhere else when i need it, is that still possible to do it?

**Comment by RealRancor** [comment]
Hi,

please read the documentation about the trusted_domains setting:

https://doc.owncloud.org/server/8.0/admin_manual/installation/installation_wizard.html?highlight=trusted#trusted-domains

Btw. please use either the forums or the mailinglist for asking such questions.

**Comment by Xenopathic** [comment]
`trusted_domains` affects the domains you connect *to* ownCloud with, not the domain you connect *from*. It is to prevent man-in-the-middle attacks. As long as you connect to your instance with the domain name in `trusted_domains`, you won't have any issues.

**Comment by RealRancor** [comment]
Exactly as described in the linked docs above :)
