### ISSUE TITLE
Deleting all SSL root certificates breaks curl requests

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#15710]
### Env
Master, PHP 5.5

### Steps to reproduce

As a non-admin user

1. Install a root certificate
2. Delete the certificate
3. Try to connect to a remote share

### Expected behaviour
Files should be able to connect to all the remote folders

### Actual behaviour
Instead, this is what is shown in the browser logs
`"Sabre\DAV\Exception: [CURL] Error while making request: error setting certificate verify locations:  CAfile: /www/data/demo1/files_external/rootcerts.crt  CApath: none (error code: 77)"`

That `rootcerts.crt` file weighs 0 bytes. Deleting it solves the problem.
Not sure if it's a regression or if it's always been like this.

**Comment by nickvergessen** [comment]
@LukasReschke

**Comment by LukasReschke** [comment]
Probably a "somewhat" regression. Stable releases actually don't do SSL really properly wrt to this storage etc.

Will fix this for 8.1

**Comment by karlitschek** [comment]
@LukasReschke What is the status here? 8.1 is here very soon :-)

**Comment by LukasReschke** [comment]
On current master:

1. Go to personal settings
2. Upload root certificates
3. Remove the root certificates
4. `data/admin/files_external/rootcerts.crt` is still valid

@oparoz May I ask you to recheck this and if this still fails for you give me some guidance on what we did different? :smile:

**Comment by oparoz** [comment]
@LukasReschke - I'll give it another go later, but when you say that `data/admin/files_external/rootcerts.crt` is still valid, what does it contain?

**Comment by LukasReschke** [comment]
> @LukasReschke - I'll give it another go later, but when you say that data/admin/files_external/rootcerts.crt is still valid, what does it contain?

The content from ca-bundle.crt in the config folder.

**Comment by oparoz** [comment]
Ah, yeah, but that's a recently introduced feature if I'm not mistaken, so that should work now.
I'll keep you posted.

**Comment by oparoz** [comment]
OK, I can't even install the certificate and will file a separate bug first...

**Comment by oparoz** [comment]
@LukasReschke - https://github.com/owncloud/core/issues/16288

**Comment by oparoz** [comment]
As an admin, rootcerts.crt is now populated with the bundle, so there is hope :)

**Comment by oparoz** [comment]
With https://github.com/owncloud/core/pull/16289, I was able to install and remove certs as a user and the `rootcerts.crt` is never empty, so this was fixed when the bundle was introduced. Thank you!

**Comment by LukasReschke** [comment]
Great. Thanks for confirmation :dancer: 

Though this is still completely broken in any other version than master but that is nothing we can backport. :see_no_evil:

**Comment by oparoz** [comment]
Yeah, it's a shame because that means people will have to wait for all their contacts to upgrade to 8.1 before being able to securely share files, but that should only take a few months.
