### ISSUE TITLE
HTTP2 support

### ISSUE THREAD

**Issue by fduraibi** [owncloud/core#15715]
Is there any plan on supporting http2?

Since I believe it will help increase the performance specially when syncing many small files over SSL.

**Comment by RealRancor** [comment]
Maybe i'm wrong but OC don't need to support this as this is the transport protocol used by your webserver. So your webserver needs support for it, not ownCloud.

**Comment by karlitschek** [comment]
yes. the owncloud server supports http2 automatically if the webserver does. possible that we have to implement this in the owncloud client. please open the ticket there.
