### ISSUE TITLE
CentOS 7 installation fails, files missing from repo

### ISSUE THREAD

**Issue by CrazyDymond88** [owncloud/core#15730]
Hello, I'm pretty new to linux so please be gentle.  From what I can tell yum is misreading some of the locations of the files in the repo needed for install.  :/ seems to translate to %3A

Downloading packages:
owncloud-app-files_encryption- FAILED
http://download.opensuse.org/repositories/isv%3A/ownCloud%3A/community/CentOS_CentOS-7/noarch/owncloud-app-files_encryption-8.0.2-16.1.noarch.rpm: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
owncloud-app-files_sharing-8.0 FAILED
http://download.opensuse.org/repositories/isv%3A/ownCloud%3A/community/CentOS_CentOS-7/noarch/owncloud-app-files_sharing-8.0.2-16.1.noarch.rpm: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
owncloud-app-files_trashbin-8. FAILED
http://download.opensuse.org/repositories/isv%3A/ownCloud%3A/community/CentOS_CentOS-7/noarch/owncloud-app-files_trashbin-8.0.2-16.1.noarch.rpm: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
owncloud-app-files_videoviewer FAILED
http://download.opensuse.org/repositories/isv%3A/ownCloud%3A/community/CentOS_CentOS-7/noarch/owncloud-app-files_videoviewer-8.0.2-16.1.noarch.rpm: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
owncloud-app-gallery-8.0.2-16. FAILED
http://download.opensuse.org/repositories/isv%3A/ownCloud%3A/community/CentOS_CentOS-7/noarch/owncloud-app-gallery-8.0.2-16.1.noarch.rpm: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
owncloud-app-user_external-8.0 FAILED
http://download.opensuse.org/repositories/isv%3A/ownCloud%3A/community/CentOS_CentOS-7/noarch/owncloud-app-user_external-8.0.2-16.1.noarch.rpm: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.

Error downloading packages:
  owncloud-app-files_trashbin-8.0.2-16.1.noarch: [Errno 256] No more mirrors to try.
  owncloud-app-user_external-8.0.2-16.1.noarch: [Errno 256] No more mirrors to try.
  owncloud-app-files_encryption-8.0.2-16.1.noarch: [Errno 256] No more mirrors to try.
  owncloud-app-files_videoviewer-8.0.2-16.1.noarch: [Errno 256] No more mirrors to try.
  owncloud-app-files_sharing-8.0.2-16.1.noarch: [Errno 256] No more mirrors to try.
  owncloud-app-gallery-8.0.2-16.1.noarch: [Errno 256] No more mirrors to try.

Even when I try to correct this I get a 404 not found:

[root@CentOwnCloud tmp]# wget http://download.opensuse.org/repositories/isv:/ownCloud:/community/CentOS_CentOS-7/noarch/owncloud-app-files_encryption-8.0.2-16.1.noarch.rpm
--2015-04-18 11:05:10--  http://download.opensuse.org/repositories/isv:/ownCloud:/community/CentOS_CentOS-7/noarch/owncloud-app-files_encryption-8.0.2-16.1.noarch.rpm
Resolving download.opensuse.org (download.opensuse.org)... 195.135.221.134, 2001:67c:2178:8::13
Connecting to download.opensuse.org (download.opensuse.org)|195.135.221.134|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://mirror.umd.edu/opensuse/repositories/isv:/ownCloud:/community/CentOS_CentOS-7/noarch/owncloud-app-files_encryption-8.0.2-16.1.noarch.rpm [following]
--2015-04-18 11:05:10--  http://mirror.umd.edu/opensuse/repositories/isv:/ownCloud:/community/CentOS_CentOS-7/noarch/owncloud-app-files_encryption-8.0.2-16.1.noarch.rpm
Resolving mirror.umd.edu (mirror.umd.edu)... 129.2.73.2
Connecting to mirror.umd.edu (mirror.umd.edu)|129.2.73.2|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-04-18 11:05:10 ERROR 404: Not Found.

**Comment by karlitschek** [comment]
@jnweiger Can you have a look please?

**Comment by DeepDiver1975** [comment]
This is most probably a mirror sync issue at our friend at OBS.

@CrazyDymond88 please retry after some time.
