### ISSUE TITLE
Encryption key not found for ____ filename during attempted read via stream

### ISSUE THREAD

**Issue by kaplandani** [owncloud/core#15743]
I get this messages again and again.
The sync client keeps trying to do something, and fails.

The file is in the main account folder, and it looks like the share account can't read it.
 Server is 8.0.2 on Centos 7.
Client is 1.8.0 build from apr 11.

I have about 10 files like that all on the same folder. 
I am not sure there is a simple way to reproduce as there are another 10GB of shared files that works ok.

**Comment by DeepDiver1975** [comment]
@schiesbn @th3fallen can I ask you to take a look? THX

**Comment by kaplandani** [comment]
Sure.

**Comment by cmonteroluque** [comment]
@schiesbn @th3fallen any update?

**Comment by schiesbn** [comment]
Can you check if the keys for this file exists. They should be located in ````data/user/files_encryption/keys/<path_to_file>/<filename>/```` This folder should at least contain two files: ````fileKey```` and ````<user>.shareKey````

Did you already used ownCloud 7 with encryption and migrated to ownCloud 8? Did the migration finished without any errors? During migration we moved the keys to a new location which can cause some troubles in the sense of timeouts for large installations or if a external user management such as LDAP is in use.

**Comment by schiesbn** [comment]
Moved milestone because at this stage it is not clear if it is a bug and how it could be fixed. Let's wait for more feedback and then decide what to do (most likely after 8.0.4).

**Comment by cmonteroluque** [comment]
@kaplandani is there any more feedback, did you try a new migration to oC8 to see if it resolved it?
