### ISSUE TITLE
[enc2] no route for updatePrivateKeyPassword

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#15745]
no route defined in https://github.com/owncloud/core/blob/master/apps/encryption/appinfo/routes.php#L26 for https://github.com/owncloud/core/blob/master/apps/encryption/js/settings-personal.js#L12

@schiesbn @th3fallen

**Comment by th3fallen** [comment]
@schiesbn Am i missing something or is there not a method to update private key password? Unless it meaning the recovery password?

**Comment by DeepDiver1975** [comment]
from my understanding route and method are missing

**Comment by th3fallen** [comment]
fan...{blank}ing.... tastic....

k.

**Comment by DeepDiver1975** [comment]
summoning @schiesbn ....

**Comment by DeepDiver1975** [comment]
LOL - @th3fallen please review https://github.com/owncloud/core/pull/15677

**Comment by th3fallen** [comment]
Ah that makes more sense i was about to start writing the method, will test now. @DeepDiver1975
