### ISSUE TITLE
Exception namespaces

### ISSUE THREAD

**Issue by Xenopathic** [owncloud/core#15749]
We currently have exceptions scattered all over the place, in lib/private, lib/public, in subdirs of those folders etc. This makes it difficult to find an exception that fits the need you have, and also means you have to decide whether to put it in the OCP or OC namespace.

On the one hand, exceptions shouldn't be private. They need to be caught by apps, so by definition they should be public.

On the other hand, OCP is cluttered as it is, before we even start moving all the exceptions there. This might be a moot point with the correct directory structure though.

I propose a new namespace, OCE, where exceptions live. It shares the trait of OCP, in that there must be no breaking changes, but gathers all exceptions in a single place to avoid cluttering OCP. It also makes it a single place that all exceptions can be found - no more searching through the hierarchy to find one that fits your usecase.

Thoughts? @PVince81 @icewind1991 @LukasReschke @DeepDiver1975 @MorrisJobke

**Comment by DeepDiver1975** [comment]
> On the one hand, exceptions shouldn't be private. They need to be caught by apps, so by definition they should be public.

hmmm ... I cannot really agree on this. There is also a difference between public and private exceptions.

Exception which are expected to be thrown by public api calls MUST live in the public namespace.

Where as: if there are any exceptions implementation specific and do not hit the surface of the public api - these shall remain in private as well.

**Comment by MorrisJobke** [comment]
> They need to be caught by apps, so by definition they should be public.

If it is really just an internal thing you want to throw some steps up and catch there, then it shouldn't be public.

**Comment by Xenopathic** [comment]
The problem is, what happens if an exception is supposed to be thrown and caught in private code, but doesn't? Perhaps by accident, or perhaps a `catch()` is removed at a later date.

**Comment by rullzer** [comment]
There are ways to check that. Sure they require a lot of analysis. But it is doable. Keeping all the exception in a public namespace would get messy really quickly.

Having said that. A more organized way (2 namespaces maybe?) to organize our exceptions would not be a bad idea.

**Comment by MorrisJobke** [comment]
> Having said that. A more organized way (2 namespaces maybe?) to organize our exceptions would not be a bad idea.

* `\OC\Exception`
* `\OCP\Exception`

?

**Comment by rullzer** [comment]
Sure those sounds sensible enough ;)

**Comment by DeepDiver1975** [comment]
> The problem is, what happens if an exception is supposed to be thrown and caught in private code, but doesn't? Perhaps by accident, or perhaps a catch() is removed at a later date.

Not that of a problem from my understanding - worst case the unexpected exception will be cought top level in e.g. index.php as a general PHP Exception.

**Comment by DeepDiver1975** [comment]
> Having said that. A more organized way (2 namespaces maybe?) to organize our exceptions would not be a bad idea.

well - having 200 exception in one namespace doesn't really make things easier.
I prefer to have exceptions living in the namespace they belong to.

e.g. all our webdav related exception live in one place: https://github.com/owncloud/core/tree/master/lib/private/connector/sabre/exception

Moving them to a more global place has no value - it might even cause some damage because they are of no relevance in other areas.

**Comment by nickvergessen** [comment]
> Moving them to a more global place has no value - it might even cause some damage because they are of no relevance in other areas.

I agree here, it's just like with all the interfaces we have in `OCP\I*` instead of having them organized in a somewhat clear way (folders per topic like they are in `lib/private/`: group, user, ...)

**Comment by DeepDiver1975** [comment]
> I agree here, it's just like with all the interfaces we have in OCP\I* instead of having them organized in a somewhat clear way (folders per topic like they are in lib/private/: group, user, ...)

yes - this is the lesson we did learn ....

**Comment by nickvergessen** [comment]
So let's use `OCP\<topic>\*Exception`, closing?

**Comment by MorrisJobke** [comment]
> So let's use OCP\<topic>\*Exception, closing?

:+1:

@Xenopathic Feel free to close

**Comment by Xenopathic** [comment]
Hmm, OK.
