### ISSUE TITLE
Apps don't pass occ app:check-code

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#15751]
### Steps to reproduce

1. Install 8.1 enterprise
2. invoke occ app:check-code on all apps

### Expected behaviour

All apps pass the check

### Actual behaviour

The following apps fail the check:

Encryption
External
files_external
files_sharing
files_trashbin
files_versions
files
provisioning_api
user_external
user_ldap
user_webdav

### Server configuration

Ubuntu 14.04
PHP 5.5.9
ownCloud Enterprise Edition 8.1 alpha 1 (daily) Build:2015-04-16T03:08:13+00:00 f50798a674bf223e1c8015b9a27287b2ac6c9f1a

**Comment by MorrisJobke** [comment]
> The following apps fail the check:

you meant:

> All apps don't pass.

;)

**Comment by Xenopathic** [comment]
We already have an issue to track this :smile: Closing in favour of #4774
