### ISSUE TITLE
Public page sessions don't work properly in all browsers

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#15755]
### Env
Master, PHP-FPM 5.5, Apache 2.4, memcache in config.php

### Steps to reproduce
1. Share a file
2. From the public page, which is authorised via a token, make a Jquery ajax requests to the public WebDAV endpoint, using the token as authorization, in the URL
```
var url = parent.location.protocol + '//' + token + '@' + location.host + OC.linkTo('', 'public.php/webdav');
$.ajax({
	url: url
});
```

### Expected behaviour
Firefox should get the file
Chrome should get the file

### Actual behaviour
Firefox gets the file
Chrome gets the file, but JQuery reports a 401 error and thus raises an exception

If you remove the token from the URL:
Chrome gets the file
Firefox shows a HTTP authorisation window, asking for the username and password

### Open questions
* I don't know which is the proper behaviour. Is the token required since we're already in a session and only talking to a different route?
* Is this purely a JQuery issue?

**Comment by PVince81** [comment]
The share token is always required.

The only session that is used in the public page is whenever the share needs a password. After entering the password, a session cookie is used to keep the session.

**Comment by oparoz** [comment]
How come Chrome is able to retrieve the content without using a token then?
Take my PR https://github.com/owncloud/core/pull/15652
Comment out the authorisation part and load the shared file in a private tab in Chrome. You still get the content.
