### ISSUE TITLE
Session cache crashes when browser sends invalid authorisation headers

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#15754]
### Env
Master, PHP 5.5, memcache in config.php

### Steps to reproduce
1. Share a file
2. From the public page, which is authorised via a token, make a Jquery ajax requests to the public WebDAV endpoint, using the token as authorization
```
var url = parent.location.protocol + '//' + location.host + OC.linkTo('', 'public.php/webdav');
$.ajax({
	url: url,
	headers: {
		Authorization: 'Basic ' + token + ':'
	}
});
```

### Expected behaviour
The browser should get the file

### Actual behaviour
The browser receives an error page and oC crashes

It's possible to avoid the crash by adding the token to the URL instead, but then you run into other [session issues](https://github.com/owncloud/core/issues/15755)

**EDIT: Things work fine if the authorisation is properly base64 encoded.**
So, this issue is purely about parameter validation

### Logs
```
Exception: {
"Message":"session_start(): Cannot send session cache limiter - headers already sent (output started at www/lib/base.php:944)",
"Code":0,
"Trace":"#0 [internal function]: OC\Session\Internal->trapError(2, 'session_start()...', '/www...', 38, Array)\\n#1 www/lib/private/session/internal.php(38): session_start()\\n#2 www/lib/base.php(454): OC\Session\Internal->__construct('ocinstanceId')\\n#3 www/lib/base.php(589): OC::initSession()\\n#4 www/lib/base.php(1117): OC::init()\\n#5 www/public.php(30): require_once('/www...')\\n#6 {main}",
"File":"www/lib/private/session/internal.php",
"Line":104
}
```

**Comment by oparoz** [comment]
It turns out I forgot to encode the authorisation parameters, but still, oC should not crash. I've left the original mistake in the OP (token is not encoded).

@DeepDiver1975 - This might not be urgent, unless @LukasReschke thinks not validating headers and crashing instead could represent a security risk.

**Comment by PVince81** [comment]
@oparoz still happens with 8.2 ?

**Comment by cmonteroluque** [comment]
This bug will fall off 8.2 if not resolved by 6 Oct

**Comment by PVince81** [comment]
@ChristophWurst is that something you observed recently or different ?

**Comment by ChristophWurst** [comment]
@PVince81 nope

**Comment by PVince81** [comment]
Please reopen if the problem persists with 9.0.5 or 9.1.1
