### ISSUE TITLE
Improve progressbar and allow renaming file while uploading

### ISSUE THREAD

**Issue by halflife3lost** [owncloud/core#15759]
Needed:
1. The name of the uploaded file in line with the progress bar.
Uncomfortable when multiple files to upload.
On the other file storage, the name of the file loaded on the server is displayed at startup.
2. Show interest uploaded to the server. For each file. An example of the format of 99.9%. Because the progress bar reaches the end and worth it.

**Comment by halflife3lost** [comment]
Learn more.

You can add a web interface:
0. Show filename file uploads.
1. Display the full size of the file uploaded to the server.
2. The current size of the file uploaded to the server.
3. The current speed file upload.

Example:
  [10,5 Mb / 125,8 Mb - 8,3%] ararararararar.zip

![owncloud_new_web_gui](https://cloud.githubusercontent.com/assets/12036389/7254723/81ca8c4c-e84d-11e4-8b70-b19eedfbe987.jpg)

**Comment by jancborchardt** [comment]
Well, the files being uploaded should directly appear in the list with a spinner, so we don’t need to add that info on top there. The percentage is also not really interesting since that’s what the bar already represents.
