### ISSUE TITLE
Need tighter ldap property validation

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#15765]
### Steps to reproduce
1. Install 8.1 enterprise
2. Enable LDAP app
3. Navigate to admin page
4. Add new LDAP server
5. Enter data either directly via UI or via occ
### Expected behaviour

Data is checked for incorrect format or data types
### Actual behaviour

Data entered is not verified when the data is entered:

For instance, I can enter this command:

sudo -u www-data php occ ldap:set-config s04 ldapHostfffff 172.18.5.147aesfzXcC

and not get any feedback (good or bad) that there is an issue with the field being set (ldapHostfffff) or the value it is being set to 172.18.5.147aesfzXcC

On the UI, I can enter x.x.x.x as a host name and save this value. 
### Server configuration

Ubuntu 14.04
PHP 5.5.9
ownCloud Enterprise Edition 8.1 alpha 1 (daily) Build:2015-04-16T03:08:13+00:00 f50798a674bf223e1c8015b9a27287b2ac6c9f1a

**Comment by karlitschek** [comment]
@blizzz

**Comment by PVince81** [comment]
Please reopen in user_ldap app repo if still relevant @butonic @jvillafanez
