### ISSUE TITLE
Make it easy to reuse app containers in other apps

### ISSUE THREAD

**Issue by Raydiation** [owncloud/core#15763]
Sometimes you want to reuse classes from another app. If you do so, you also need to reuse the container because the author could suddenly decide to create a custom factory for a class. So in order to be able to react to that you cant simply resolve that class from your own container.

I've written a small app that allows you to serve your news app feeds as rss, it also reuses the news app container: https://github.com/Raydiation/feedcentral/blob/master/appinfo/application.php#L28

The current way to do this that we need to resolve all deps that we want to use manually, e.g.

```php
$container->registerService('NewsContainer', function($c) {
    $app = new News();
    return $app->getContainer();
});
$container->registerService('OCA\News\Service\ItemService', function($c) {
    return $c->query('NewsContainer')->query('OCA\News\Service\ItemService');
});
```

What if we could just do the following:
```php
$container->registerAppContainer((new OCA\News\Application)->getContainer(), 'News');
```

And now all classes that start with **OCA\\News** will automatically be resolved from that app container.

Here's a small patch to make it clearer how it would work:

```diff
diff --git a/lib/private/appframework/utility/simplecontainer.php b/lib/private/appframework/utility/simplecontainer.php
index c7dff6f..790ab52 100644
--- a/lib/private/appframework/utility/simplecontainer.php
+++ b/lib/private/appframework/utility/simplecontainer.php
@@ -34,6 +34,7 @@ use \OCP\AppFramework\QueryException;
  */
 class SimpleContainer extends \Pimple\Container implements \OCP\IContainer {
 
+       private $appContainers = [];
 
        /**
         * @param \ReflectionClass $class the class to instantiate
@@ -94,7 +95,17 @@ class SimpleContainer extends \Pimple\Container implements \OCP\IContainer {
                if ($this->offsetExists($name)) {
                        return $this->offsetGet($name);
                } else {
-                       $object = $this->resolve($name);
+                       $paths = implode('\\', $name, 3); // only the first two are important
+                       $appNamespace = $paths[1];
+
+                       if (count($paths) >= 2 &&
+                               isset($this->appContainers[$appNamespace])
+                               strpos($paths[0], 'OCA') === 0 &&) {
+                               $object = $this->appContainers[$appNamespace]->query($name);
+                       } else {
+                               $object = $this->resolve($name);
+                       }
+
                        $this->registerService($name, function () use ($object) {
                                return $object;
                        });
@@ -111,6 +122,21 @@ class SimpleContainer extends \Pimple\Container implements \OCP\IContainer {
        }
 
        /**
+        * Allows you to register a separate container for a namespace. This makes
+        * it possible to reuse a container of a different app and access all its
+        * classes
+        *
+        * @param SimpleContainer $container the container that should be registered
+        * for the namespace
+        * @param string $appNamespace the app namespace that should resolve to a
+        * different container, e.g. to register the container for OCA\News\Class
+        * the string would be News
+        */
+       public function registerAppContainer(SimpleContainer $container, $appNamespace) {
+               $this->appContainers[$appNamespace] = $container;
+       }
+
+       /**
         * The given closure is call the first time the given service is queried.
         * The closure has to return the instance for the given service.
```

@oparoz @DeepDiver1975 @MorrisJobke @LukasReschke @PVince81

**Comment by oparoz** [comment]
I think it 's an elegant solution to the problems we're going to start facing when the first inter-dependant apps are going to be introduced.

**Comment by DeepDiver1975** [comment]
> when the first inter-dependant apps are going to be introduced.

As per the design criteria of ownCloud there shall be NO dependency between app.

Just have a look at the nightmare we have as of today in the area of calendar, contacts and task which "only" share a 3rdparty library.

This is nothing we want in core - sorry.

**Comment by oparoz** [comment]
@DeepDiver1975 - How are you going to move preview providers to apps if the Preview app can't load them? It really depends on how you look at apps. They can be treated as libraries which aren't included in core.

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 - How are you going to move preview providers to apps if the Preview app can't load them? It really depends on how you look at apps. They can be treated as libraries which aren't included in core.

This what we have the public api in core for. 
As for this explicit scenario:
- an preview generating app will register the preview provider to the preview manager in it's app.php
- as soon as an preview is to be generated the registered provider living in the app will be called

We already have working mechanism like this in the contacts manager or in the activity manager.

**Comment by oparoz** [comment]
OK, but that's limited to very specific use cases then since the manager needs to live in core whereas with inter-app dependencies, the manager can live in another app. On top of that it's the app's responsibility to manage these dependencies, just like they already do using composer or bower, so I don't really see the problem with the AppFramework making it easy to load classes from other apps.

**Comment by DeepDiver1975** [comment]
> , so I don't really see the problem with the AppFramework making it easy to load classes from other apps.

Just have a look at the nightmare we have as of today in the area of calendar, contacts and task which "only" share a 3rdparty library.

**Comment by oparoz** [comment]
I'm not familiar with the issues these apps are having apart from some DAV incompatibilities. Which library are they sharing? If it's indeed SabreDAV, they I'd stay it's very different than sharing a class to parse or log data per example.
But again, it's a problem with these apps and the way they've decided to share a library. App developers can decide whether or not to use a library from the app store and if they grow apart, they can usually "simply" include the class(es) of the version which worked for them, with their app.

I guess the fallback is to create composer components which can be loaded by apps.

**Comment by MorrisJobke** [comment]
> I guess the fallback is to create composer components which can be loaded by apps.

And then each app itself is again self contained. I would say this is the way to go.

**Comment by oparoz** [comment]
> Just have a look at the nightmare we have as of today in the area of calendar, contacts and task which "only" share a 3rdparty library.

@DeepDiver1975 - I've read about the mail app recently and it needs contacts and would be more useful if it can talk to the calendar and tasks apps. How are you going to manage these dependencies?

Add something like the Horde Activesync lib for efficient push. Do you really want to install it in every single app or would you rather have one AS app which communicates with the other ones?
