### ISSUE TITLE
LDAP users can't be checked via OCC if there are mis-configured ldap servers along with correctly configured ldap servers

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#15767]
### Steps to reproduce

1. Install 8.1 enterprise
2. Enable LDAP app
3. Navigate to admin page
4. Configure a new LDAP server
5. Create some empty LDAP server configurations
6. From occ get a user report (occ user:report) --> see ldap user count
7. From occ, check ldap user (occ ldap:check-user <un>)

### Expected behaviour

User information returned from ldap:check-user

### Actual behaviour

The occ command returns an error:

```

ubuntu-14-lts: sudo -u www-data php occ user:report
+------------------+---+
| User Report      |   |
+------------------+---+
| Database         | 2 |
| LDAP             | 4 |
|                  |   |
| total users      | 6 |
|                  |   |
| user directories | 3 |
+------------------+---+

ubuntu-14-lts: sudo -u www-data php occ ldap:check-user abagail_kuhic
Cannot check user existence, because disabled LDAP configurations are present.

```

Delete all misconfigured LDAPs and rerun occ command:

```

ubuntu-14-lts: sudo -u www-data php occ ldap:check-user abagail_kuhic
The user is still available on LDAP.


```

### Server configuration

Ubuntu 14.04
PHP 5.5.9
ownCloud Enterprise Edition 8.1 alpha 1 (daily) Build:2015-04-16T03:08:13+00:00 f50798a674bf223e1c8015b9a27287b2ac6c9f1a

**Comment by karlitschek** [comment]
@blizzz

**Comment by blizzz** [comment]
see the --force switch for check-user

**Comment by jnfrmarks** [comment]
@blizzz 

ubuntu-14-lts: sudo -u www-data php occ ldap:check-user --force abagail_kuhic
The given user is not a recognized LDAP user.

--force did not find the user either.


![p322](https://cloud.githubusercontent.com/assets/8480343/7255072/0081af18-e815-11e4-8a33-4b62de875a32.PNG)

**Comment by jnfrmarks** [comment]
hmm, I have gotten this command to work.  Now to figure out what was different ...  I will close this for now and reopen if/when I figure out what causes the failure.

**Comment by blizzz** [comment]
> hmm, I have gotten this command to work.  Now to figure out what was
> different ...  I will close this for now and reopen if/when I figure out
> what causes the failure.

random shot: cache? :)

**Comment by jnfrmarks** [comment]
hmm could be - I did run files:cleanup before rerunning.
