### ISSUE TITLE
TypeError: OC.Encryption.displayEncryptionWarning is not a function

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#15760]
Printed to the console with encryption enabled and when your private key needs to be re-passworded:
```
TypeError: OC.Encryption.displayEncryptionWarning is not a function
```

You can see that before Step5 of https://github.com/owncloud/core/pull/15677

**Comment by nickvergessen** [comment]
Maybe @MorrisJobke or when @PVince81 needs some context switch

**Comment by DeepDiver1975** [comment]
fixed with this???? https://github.com/owncloud/core/pull/15713

**Comment by nickvergessen** [comment]
Yes, I added it to the PR description
