### ISSUE TITLE
LDAP host text box outline missing when configuring LDAP

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#15764]
### Steps to reproduce

1. Install 8.1 enterprise
2. Enable LDAP app
3. Navigate to admin page
4. Add new LDAP server

### Expected behaviour

There is a Host text box

### Actual behaviour

The host text box is missing.  If you put your cursor where the text box should be, you can still enter dat

![p319](https://cloud.githubusercontent.com/assets/8480343/7239507/749d6f2e-e778-11e4-8f0f-e9336c26d8cf.PNG)

### Server configuration

Ubuntu 14.04
PHP 5.5.9
ownCloud Enterprise Edition 8.1 alpha 1 (daily) Build:2015-04-16T03:08:13+00:00 f50798a674bf223e1c8015b9a27287b2ac6c9f1a

**Comment by karlitschek** [comment]
@blizzz

**Comment by blizzz** [comment]
Never seen this. Which browser? Also in the screen shot the host field is visible.

**Comment by jnfrmarks** [comment]
chrome.  The outline of the box is what's missing.

**Comment by blizzz** [comment]
Ah, the outline.  Okay, that I see. That's different than  missing text box ;) Fix on the way.

**Comment by blizzz** [comment]
Fixed with https://github.com/owncloud/core/pull/15770, please test.
