### ISSUE TITLE
What's the correct way to use ./occ --password-from-env user:resetpassword

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#15762]
### Steps to reproduce

1. Install 8.1 enterprise
2. invoke occ user:resetpassword:

sudo -u www-data ./occ --password-from-env user:resetpassword <uid>

### Expected behaviour

Not sure; the option is not documented.  I'm trying to reset the user's password

### Actual behaviour

I can't change the users password using the --password-from-env option:

```

ubuntu-14-lts: sudo -u www-data ./occ user:resetpassword --password-from-env jrm
--password-from-env given, but OC_PASS is empty!
ubuntu-14-lts: echo $OC_PASS
jrm


```

How does this work?

### Server configuration

Ubuntu 14.04
PHP 5.5.9
ownCloud Enterprise Edition 8.1 alpha 1 (daily) Build:2015-04-16T03:08:13+00:00 f50798a674bf223e1c8015b9a27287b2ac6c9f1a

**Comment by Xenopathic** [comment]
Firstly, you need to `export` the variable for any subprocesses to see it. Not sure if you've already done this. Just run `export OC_PASS` and any subprocesses will be able to see it...

...except for `sudo`. `sudo` purposefully drops all environment variables and starts with a fresh environment. If you anticipate needing this regularly, and don't want to `sudo -i` all the time, follow the instructions over [here](http://stackoverflow.com/questions/8633461/how-to-keep-environment-variables-when-using-sudo)

This seems to be a documentation bug however - we should note that `sudo` (by default) drops environment variables. cc @carlaschroder

**Comment by carlaschroder** [comment]
What is this --password-from-env option? Never seen it before, and it does not exist on my system.

Resetting a user's password is done this way:

    sudo -u www-data php occ user:resetpassword [username]

I prefer 'php occ to './occ' because in a default oC installation the occ script is not executable.

**Comment by jnfrmarks** [comment]
@carlaschroder 

If you enter the command without a UID value, you get the usage syntax and that is where I saw the --password-from-env option.

@Xenopathic 

That makes sense; closing for now and will reopen if it's not a user error.

**Comment by carlaschroder** [comment]
sudo drops environment variables as a security measure. There should not be any sudo usage that requires messing with environment variables without a really good reason-- what is the purpose of --password-from-env, and why us it rather than running the plain user:resetpassword command?

**Comment by jnfrmarks** [comment]
In my case, I want to be able to use the env var so that  I can script adding users without requiring input from users.

**Comment by jnfrmarks** [comment]
This works:

export OC_PASS=newPW
su -s /bin/sh www-data -c "php /var/www/html/owncloud/occ user:resetpassword --password-from-env uid"

**Comment by carlaschroder** [comment]
export OC_PASS=   is exposed in the BASH history.

I thought the User Provisioning API was for managing mass quantities of users?

**Comment by jnfrmarks** [comment]
Good catch.

@LukasReschke @DeepDiver1975

**Comment by carlaschroder** [comment]
I'm happy to document this, I just don't get it. The original PR also seems confused. https://github.com/owncloud/core/pull/15404

**Comment by LukasReschke** [comment]
See https://github.com/owncloud/core/pull/15404, so generally speaking the old approach and the new one are okay for me though this one makes it harder to shoot yourself in your knee too much. – A regular call with `--password` would be in the bash history (for the user) as well as the process list (for all users)

So the `export` approach looks valid to me. Though it has indeed a confusing usage.

**Comment by jnfrmarks** [comment]
I missed that this is new with 8.1, which explains why it isn't documented.

**Comment by carlaschroder** [comment]
I'm still looking for a use case. If it's for scripting adding multiple users, it is missing a way to import a user list and a mechanism for forcing users to change their password on their first login. If it's just for adding one user a time using `occ`, it's still missing password change enforcement. So the admin either has to change the OC_PASS= variable for every user they're adding, or use the same password for multiple users. I'm not trying to be a pain; this just seems to introduce a new set of problems.

**Comment by carlaschroder** [comment]
And testing the obvious-- I don't see it in the process list. IMO this needs some more thought.

**Comment by Xenopathic** [comment]
It can be very useful to script things using Bash scripts, such as resetting a password for a particular user (user comes to the admin and wants a reset password, for example). I know for certain The Linux Schools Project (which I am part of) uses Bash scripts extensively. The ability to use a password that isn't on the command line is very useful, either by passing it in on stdin or passing it through as an environment variable (the approach here).

Hopefully that was enough of a use case for you :smile:

**Comment by carlaschroder** [comment]
Sorry Xenopathic, I'm still befuzzled. I'm not seeing a clear use case.

User wants password reset. oC already has three ways to do this: automated reset from the login screen, admin resets it from the Web GUI, admin resets it with occ user:resetpassword

Or, admin wants to add users. What improvement does this offer over existing user management tools? The `occ` command does not appear in the process list, but it does get recorded in BASH history of the sudo user, and so does `echo`. So it adds an extra step for...why?

If we're going to offer a scripted option, then we need to offer a complete example script.

**Comment by Xenopathic** [comment]
@carlaschroder Here is an example from Karoshi Server: https://github.com/the-linux-schools-project/karoshi-server/blob/master/serversetup/web_controls/scripts/exec/pdc/reset_password#L123-L127. It uses the CLI tool from Samba to change user passwords, and it isn't too dissimilar to how occ works. This code runs in production, and is powered by a web management interface. Admittedly, ownCloud already has a web interface for this, but imagine a full domain with multiple passwords on multiple authentication services - one web management interface to control them all (written in Bash).

**Comment by nickvergessen** [comment]
As already mentioned in the PR, I don't see how the export OC_PASS is more secure then --password, it's just harder to use when you want to add mulitple users with different passwords.

ref https://github.com/owncloud/core/pull/15404/files#r27768552

**Comment by MorrisJobke** [comment]
> As already mentioned in the PR, I don't see how the export OC_PASS is more secure then --password, it's just harder to use when you want to add mulitple users with different passwords.

The --password would be listed in the running processes. The export not (export is a shell command and not a executable). So each user on the same host can sniff the passwords by checking the currently running executables. That's the reason for this. Otherwise you need an interactive type in of the password, which is not an easy scriptable way of doing this.

And the other ways of changing a password aren't scriptable by the admin.

**Comment by carlaschroder** [comment]
@jnfrmarks @MorrisJobke 
I am testing this on ownCloud 8.1 alpha 2, and it does not create a new user, it only changes passwords for existing users. To make it work I had to run as real root:

```
$ su
# export OC_PASS=newPASS
# su -s /bin/sh www-data -c "php /var/www/html/owncloud/occ user:resetpassword --password-from-env fred"
```
When fred is not an existing user it throws an error message:
```
There is no user called fred
```
When fred already exists, it is happy:

```
Successfully reset password for fred
```

**Comment by carlaschroder** [comment]
And, obviously, `user:resetpassword` implies re-setting an existing password :)

**Comment by carlaschroder** [comment]
And I couldn't do anything until I set UTF-8 as the default in PHP. Ever notice how PHP is annoying like all of the time?

**Comment by jnfrmarks** [comment]
@carlaschroder 

Sounds like we're good here.  Can we close this one?

**Comment by carlaschroder** [comment]
Ah, a brand-new user:add option. I heart surprises.

**Comment by carlaschroder** [comment]
no @jnfrmarks, I want to keep it open until I am finished uncovering all the surprises.

**Comment by carlaschroder** [comment]
eh, let's close it. I have a doc issue open. Thanks everyone!
