### ISSUE TITLE
Adding LDAP server reuses last number in the list

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#15766]
### Steps to reproduce

1. Install 8.1 enterprise
2. Enable LDAP app
3. Navigate to admin page
4. Add a bunch of new LDAP servers (I added 5)
5. Delete some of the middle ones (deleting one will do)
6. Add a new LDAP server

### Expected behaviour

New LDAP server should get the next numerical value available

### Actual behaviour

The next LDAP server created reuses the last number:

![p321](https://cloud.githubusercontent.com/assets/8480343/7239946/8f67a0a6-e77b-11e4-9270-343e30bb5c79.PNG)

### Server configuration

Ubuntu 14.04
PHP 5.5.9
ownCloud Enterprise Edition 8.1 alpha 1 (daily) Build:2015-04-16T03:08:13+00:00 f50798a674bf223e1c8015b9a27287b2ac6c9f1a

**Comment by karlitschek** [comment]
@blizzz

**Comment by blizzz** [comment]
Confirmed. The important part is the delete action. This is also reproducible on older versions.

**Comment by blizzz** [comment]
Fixed with https://github.com/owncloud/core/pull/15773
