### ISSUE TITLE
'Modified' span does not hide when selecting files or folders

### ISSUE THREAD

**Issue by fcturner** [owncloud/core#15779]
When you select a file or folder on the webserver, the Modified span of the files table head does not hide, making the underlying text 'Delete' barely readable/usable.

Steps to reproduce:
- Just visit https://demo.owncloud.org (8.0.2)
- Select a file or folder
- Try to delete your selection

My own ownCloud is Dutch. May be language dependant.

![select](https://cloud.githubusercontent.com/assets/7526559/7252433/42574342-e835-11e4-8f5b-c3bef415b617.png)

**Comment by karlitschek** [comment]
@jancborchardt

**Comment by jancborchardt** [comment]
Thanks for catching that! Fix at https://github.com/owncloud/core/pull/15782, please review @fcturner :)

**Comment by fcturner** [comment]
Works like a charm, thanks :smiley:
