### ISSUE TITLE
"Shared with you and the group {group} by {owner}" displayed for owner

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#15771]
### Steps to reproduce

1. Create a folder
2. Create a file inside the folder
3. Share the folder with a group you are in and remove all permissions
4. Open the share dialog of the file

### Expected

The file can be shared normally

### Actual

`Shared with you and the group {group} by {owner}` is displayed at the top of the share dropdown.
Also the file can not be shared because "resharing is not allowed"

### Fix
```js
		if (data !== false &amp;&amp; data.reshare !== false &amp;&amp; data.reshare.uid_owner !== undefined) {
			if (data.reshare.share_type == OC.Share.SHARE_TYPE_GROUP) {
				html += '&lt;span class="reshare">'+t('core', 'Shared with you and the group {group} by {owner}', {group: data.reshare.share_with, owner: data.reshare.displayname_owner})+'&lt;/span>';
			} else {
				html += '&lt;span class="reshare">'+t('core', 'Shared with you by {owner}', {owner: data.reshare.displayname_owner})+'&lt;/span>';
			}
			html += '&lt;br />';
			// reduce possible permissions to what the original share allowed
			possiblePermissions = possiblePermissions &amp; data.reshare.permissions;
		}
```
the block is missing a check whether `data.reshare.uid_owner` is the current owner

**Comment by PVince81** [comment]
PR for the permissions issue: https://github.com/owncloud/core/pull/15772

**Comment by PVince81** [comment]
Tested, works :+1:
