### ISSUE TITLE
Public Link Session not destroyed when browser closes.

### ISSUE THREAD

**Issue by iamkhris** [owncloud/core#15785]
When a password protected public link is shared out, the user is not required to enter the password again when they close out their browser, and then reopen the link.  They are automatically taken right back into the ownCloud share.  This is a security concern.

**Comment by karlitschek** [comment]
Yes is cached in the session. I don´t agree that is is a security issue because this is the same browser. Can be prevented by using a private browsing windows.

**Comment by iamkhris** [comment]
I respectfully disagree that with your assertion that it's not a security issue, it is. Forcing someone to use a private browsing window, or to clear their browser cookies in order to prevent the link from opening again without using the password is absolutely a security, as well as a usability issue.  Anytime information is shared via ownCloud that can be accessed by someone without having to enter the password is a serious issue.

While it might seem easy to you to resort to a private window or to clear your cookies, not everyone can be bothered, or care to perform those extra steps.

--
Christopher Phillips


On Apr 21, 2015, at 3:34 PM, Frank Karlitschek <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes is cached in the session. I don?t agree that is is a security issue because this is the same browser. Can be prevented by using a private browsing windows.

-

**Comment by LukasReschke** [comment]
This is an hardening issue and not an immediate security threat for our threat modell. That said, this behaviour will be changed with 8.2

Duplicate of https://github.com/owncloud/core/issues/11581
