### ISSUE TITLE
enable_previews => false does not cancel preview hooks

### ISSUE THREAD

**Issue by labkode** [owncloud/core#15784]
With the config option `enable_previews=>false`, the hooks for the previews are still called.
An extra check should we putted here https://github.com/owncloud/core/blob/1ee2ee84327a23ebf089f5b719f871168d6d007d/lib/base.php#L763, I'll create a pull request.

**Comment by nickvergessen** [comment]
This might be somewhat intended. Otherwise if someone disables previews then changes a file and reenables them, they will still display the old image, because it did not get removed, so no new file is being created.

**Comment by DeepDiver1975** [comment]
> This might be somewhat intended. Otherwise if someone disables previews then changes a file and reenables them, they will still display the old image, because it did not get removed, so no new file is being created.

so triggering delete seems valid in this case. but generally speaking I see no reason to fire the hooks

**Comment by oparoz** [comment]
Or the preview cache could get deleted when `enable_previews` is set to false. I'm with the OP in thinking that those hooks should not run on systems with that setting set to disabled.

**Comment by nickvergessen** [comment]
> Or the preview cache could get deleted when `enable_previews` is set to false

You have a good location for that? :P But yeah, maybe it's fine and then just document to manually delete the data/*/thumbnails/ folders when en-/disabling previews?

**Comment by oparoz** [comment]
I would just use the cron and on 8.2, the new queue system should be able to manage all that. No?
Documentation is certainly key, but since this will be disabled in a config file which may not contain any comments, a junior admin may simply disable it without knowing what the consequences might be. As you've mentioned, apps will still use the old images.
