### ISSUE TITLE
WebDAV PUT on file share fails with 500

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15786]
### Steps to reproduce
1. Create two users "root" (the admin) and "user1"
2. Login as "root"
3. Create a file "sharedfile.txt"
4. Share "sharedfile.txt" with "user1" and make sure "can edit" is set
5. Login as "user1" with cadaver or a WebDAV client
6. Do as WebDAV PUT of a text file to overwrite test.txt

or 

1. Run smashbox `lib/oc-tests/test_shareFile.py`

### Expected result
File can be overwritten properly

### Actual result
File cannot be overwritten, 500 Internal server error.
```
{"reqId":"2QjjduRR8kJF8TBWyPFN","remoteAddr":"127.0.0.1","app":"PHP","message":"rename(\/srv\/www\/htdocs\/owncloud\/data\/user1\/files\/sharedfile.txt.ocTransferId1983394316.part,\/srv\/www\/htdocs\/owncloud\/data\/user1\/): Not a directory at \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/storage\/local.php#244","level":3,"time":"2015-04-21T16:10:08+00:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/sharedfile.txt"}
{"reqId":"2QjjduRR8kJF8TBWyPFN","remoteAddr":"127.0.0.1","app":"webdav","message":"\\OC\\Files\\Filesystem::rename() failed","level":3,"time":"2015-04-21T16:10:08+00:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/sharedfile.txt"}
{"reqId":"2QjjduRR8kJF8TBWyPFN","remoteAddr":"127.0.0.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 500 Could not rename part file to final file\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1087): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #230)\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(501): Sabre\\\\DAV\\\\Server->updateFile('sharedfile.txt', Resource id #230, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(80): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/remote.php(84): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#8 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":170}","level":4,"time":"2015-04-21T16:10:08+00:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/sharedfile.txt"}
```

Also in the database I noticed that the "unlink()" of the part file causes them to be trashed:
```
| home::user1 |    875 | files_trashbin/files/sharedfile.txt.ocTransferId1983394316.part.d1429632608 | 112b5cefead68467d14d74af57943441 |        4 |
| home::user1 |    874 | files_trashbin/files/sharedfile.txt.ocTransferId389730646.part.d1429632588  | 33599c3fee38a23d1e2652dc61f5661a |        4 |
```

### Versions
Happens on ownCloud git master (9dc12d40d846d54e024812c2c23c402073f8dd03)
Regression introduced by https://github.com/owncloud/core/pull/12006 from @icewind1991

**Comment by PVince81** [comment]
@icewind1991 if you already have an idea please fix it. Else let me know and I can have a look myself.

**Comment by PVince81** [comment]
Can also be reproduced by running the smashbox test "test_shareFile.py"

**Comment by PVince81** [comment]
Seems the reason for the "unlink to trashbin" is because we unlink using the $view instead of the $storage.

**Comment by PVince81** [comment]
Hmm no, not enough. The trash wrapper must ignore part files. I guess that will be a separate fix.

**Comment by PVince81** [comment]
Here is the PR for the trashbin behavior with part files: https://github.com/owncloud/core/pull/15787

Now let's have a look why the upload actually fails.

**Comment by PVince81** [comment]
@icewind1991 the final rename tries to rename the part file to an empty string, which is probably the name of the mountpoint file.
We should probably do the final rename on the view instead of the storage, but that might affect the hooks (we might need to remove them). What do you think ?

**Comment by PVince81** [comment]
or, now thinking of it, since this is the shared storage, we might need to add some logic in case it's a file share, in which case the empty string might be an acceptable value for `$path2`

**Comment by PVince81** [comment]
but this might mess up some storage wrappers :frowning:

**Comment by PVince81** [comment]
also it looks like we don't reach the shared storage, at least not at rename time:
```
0  OC\Files\Storage\Local->rename() /srv/www/htdocs/owncloud/lib/private/files/storage/local.php:210
1  OCA\Files_Trashbin\Storage->rename() /srv/www/htdocs/owncloud/apps/files_trashbin/lib/storage.php:72
2  OC\Files\Storage\Wrapper\Encryption->rename() /srv/www/htdocs/owncloud/lib/private/files/storage/wrapper/encryption.php:211
3  OC\Connector\Sabre\File->put() /srv/www/htdocs/owncloud/lib/private/connector/sabre/file.php:165
4  Sabre\DAV\Server->updateFile() /srv/www/htdocs/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php:1087
5  Sabre\DAV\CorePlugin->httpPut() /srv/www/htdocs/owncloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php:501
6  call_user_func_array:{/srv/www/htdocs/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php:105}() /srv/www/htdocs/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php:105
7  Sabre\Event\EventEmitter->emit() /srv/www/htdocs/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php:105
8  Sabre\DAV\Server->invokeMethod() /srv/www/htdocs/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php:469
9  Sabre\DAV\Server->exec() /srv/www/htdocs/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php:254
10 require_once()  /srv/www/htdocs/owncloud/apps/files/appinfo/remote.php:80
11 {main}          /srv/www/htdocs/owncloud/remote.php:84
```

I don't think we want to add special handling for shared storage directly in the sabre connector file class. So probably the view approach is still better.

**Comment by nickvergessen** [comment]
https://github.com/owncloud/core/pull/12006/files#diff-2e4a54e72d495abc750a9bc445da15a0R115 is causing the error, it returns an empty path to `$internalPath` for me

**Comment by PVince81** [comment]
Yes, because the shared storage root entry has the path "". And since the shared file is itself a shared storage, its path is an empty string too... (the matching cache entry as well)

**Comment by nickvergessen** [comment]
Ah, so this should be a cross storage move/copy, but isn't dealt like one

**Comment by PVince81** [comment]
Hmmyeah, kind of. The regression is there because we used to work with the View but a PR has been put in to work directly with storages to improve performance.

**Comment by nickvergessen** [comment]
> also it looks like we don't reach the shared storage, at least not at rename time:

yeah, because we throw away the storage right here: https://github.com/owncloud/core/commit/6a5950275993394df22b208f1126efae9e35e42b#diff-2e4a54e72d495abc750a9bc445da15a0R115

**Comment by nickvergessen** [comment]
@icewind1991 ping?
