### ISSUE TITLE
[7.0.5] Translation in the mail share notification does not work.

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#15783]
The translation of the emails in oC 6.0.6 did work.

I'm now changing this in oC 7.0.5, but I fail on the subject.

In English the subject looks like this: "Carlos shared »foto.png« with you"

I now want it to have in German like this: "Carlos hat »tcpdump« mit Ihnen geteilt"

In Swiss German and in German (unpersöhnlich) I get not very good subjects: "Carlos teilte »foto.png« mit Dir" & "Carlos teilt »foto.png« mit Ihnen"

In the language files (de_CH.php and de.php) I have it translated like this: ""%s shared »%s« with you" => "%s hat »%s« mit Ihnen geteilt","

This translation is not working. I searched in the original translation files under core/l10n, but there I'm not able to find this line, also I don't find this translation line containing "teilt" or "Dir" in my own translation files (these are copies of the original with only three new lines).

Do you know why this is not working in oC 7 and how can I translate it correctly? Is this a new bug?

@MorrisJobke 

00002985

**Comment by DeepDiver1975** [comment]
@nickvergessen mind having a look? THX

**Comment by nickvergessen** [comment]
@cdamken it's in `lib/l10n/de.php`:
```php
"%s shared »%s« with you" => "%s teilte »%s« mit Dir",
```

Changing that also worked for me. Please let me know if you accidently modified the wrong file

**Comment by cdamken** [comment]
@nickvergessen in oC6 the modification was in  ```/core/l10n/de_CH.php```

It's different in every version?

**Comment by caratsch** [comment]
@nickvergessen I did the modifications in de.php, de_DE.php and de_CH.php and it worked there (oC 6). Now in oC 7 I do the same modifications, but it's not working for me. The subject is always the 'default' one. I also don't find these lines in the original php-files (the default translation).

**Comment by DeepDiver1975** [comment]
> I did the modifications in de.php, de_DE.php and de_CH.php

in core/l10n or in lib/l10n ??

As pointed out by @nickvergessen the translation is in here https://github.com/owncloud/core/blob/stable7/lib/l10n/de.php#L56

**Comment by caratsch** [comment]
@DeepDiver1975 I did the modifications in core/l10. Doing them in lib/l10n works for the subject.
Thank you very much for your help!

**Comment by cdamken** [comment]
## Thanks guys!
