### ISSUE TITLE
Some apps are missing l10n directories

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#15793]
### Steps to reproduce

1. Install 8.1 enterprise
2. Check for an l10n directory for each app

### Expected behaviour

All apps have an l10n directory

### Actual behaviour

The following apps do not have an l10n dir:

encyrption_dummy (maybe this doesn't need one) 
files_locking
files_pdfviewer
files_videoviewer 
provisioning_api 
user_external 

### Server configuration

Ubuntu 14.04
PHP 5.5.9
ownCloud Enterprise Edition 8.1 alpha 1 (daily) Build:2015-04-16T03:08:13+00:00 f50798a674bf223e1c8015b9a27287b2ac6c9f1a

**Comment by karlitschek** [comment]
yes. I think this apps don´t have any userinterface that needs translation. Can you confirm @DeepDiver1975 @jancborchardt  ?

**Comment by jancborchardt** [comment]
Yeah, them having no l10n directories is not an issue. It would be an issue if there would be untranslated words.
