### ISSUE TITLE
Rrunning occ upgrade on an up to date install returns with 3 and not 0

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#15795]
### Steps to reproduce

1. Install 8.1 enterprise
2. Run the following occ command:

sudo -u www-data php occ upgrade

### Expected behaviour

The command should return with a 0

### Actual behaviour

The command returns with a 3

```

ubuntu-14-lts: sudo -u www-data php occ upgrade
ownCloud is already latest version
ubuntu-14-lts:echo $?
3

```

Why do we return an error here?  

### Server configuration

Ubuntu 14.04
PHP 5.5.9
ownCloud Enterprise Edition 8.1 alpha 1 (daily) Build:2015-04-16T03:08:13+00:00 f50798a674bf223e1c8015b9a27287b2ac6c9f1a

**Comment by karlitschek** [comment]
@DeepDiver1975 do you know who did this feature?

**Comment by DeepDiver1975** [comment]
The upgrade command defines its own exit codes - https://github.com/owncloud/core/blob/master/core/command/upgrade.php#L40
