### ISSUE TITLE
An exception occurred while executing 'SELECT ...

### ISSUE THREAD

**Issue by binarykitchen** [owncloud/core#15792]
The following explains all:

```
$ sudo -u www-data php occ upgrade -vvv
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
An exception occurred while executing 'SELECT `fileid` FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ?' with params ["3", "31f27b64666e7f81955ada2ff001204b"]:

SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
Turned off maintenance mode
Update failed
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91
Stack trace:
#0 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(Array)
#1 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(830): Doctrine\DBAL\Driver\PDOStatement->execute(Array)
#2 /var/www/owncloud/lib/private/db/connection.php(111): Doctrine\DBAL\Connection->executeQuery('SELECT `configv...', Array, Array, NULL)
#3 /var/www/owncloud/lib/private/appconfig.php(259): OC\DB\Connection->executeQuery('SELECT `configv...', Array)
#4 /var/www/owncloud/lib/private/app.php(219): OC\AppConfig->getValues(false, 'enabled')
#5 /var/www/owncloud/lib/private/app.php(71): OC_App::getEnabledApps()
#6 /var/www/owncloud/lib/private/util.php(75): OC_App::loadApps(Array)
#7 /var/www/owncloud/lib/private/files/mount/manager.php(53): OC_Util::set in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 115
```

**Comment by karlitschek** [comment]
"Server has gone away" means that you mysql daemon has crashed or was stopped manually. This is most likely not an ownCloud error. 
Please check if mysqld is still running and check why it was stopped.

**Comment by binarykitchen** [comment]
Maybe. But I found this in the mysql error log:

```
150422  7:08:39 InnoDB: 5.5.43 started; log sequence number 2996122705
ERROR: 1064  You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ALTER TABLE user ADD column Show_view_priv enum('N','Y') CHARACTER SET utf8 NOT ' at line 1
150422  7:08:39 [ERROR] Aborting

150422  7:08:39  InnoDB: Starting shutdown...
150422  7:08:41  InnoDB: Shutdown completed; log sequence number 2996122705
```

**Comment by binarykitchen** [comment]
Will I have to do manual DB adjustments before I try the aboce `occ` command over again?

**Comment by RealRancor** [comment]
Hi,

both tables "users" and "plugins" are not tables of ownCloud so there is probably nothing to do here from OC side.

The message "mysql server is gone away" and a possible solution is described here:

https://doc.owncloud.org/server/8.0/admin_manual/issues/index.html#common-problems-error-messages

**Comment by binarykitchen** [comment]
Okay, I have increased `wait_timeout` and `max_allowed_packet` and will give `occ` another try.

But really, do you have somewhere a recommendation what MySQL config to use? What are the optimal parameters for these two config variables? Shouldn't owncloud make recommendations for these?

**Comment by RealRancor** [comment]
Hi,

don't think that it is possible to give recommendations here as this heavily depends on your environment.

**Comment by binarykitchen** [comment]
@RealRancor yeah, sure, respect that. But for example on Ubuntu 14.10, owncloud with tons of photos, music files, documents and so on ... what would the recommended MySQL config look like?

**Comment by RealRancor** [comment]
There still can't be a recommended config for this.

**Comment by binarykitchen** [comment]
was soll ich da sagen? ... if you care about that cool product "owncloud" you guys are producing with hard effort and love as well i guess, then there is sure a heart to make sure users - that's admins and developers like me included - get on well with owncloud.

all i am saying, it would be nice do have an optimal mysql settings documented somewhere for each major distribution/environment. just giving good feedback and hope to be heard here. because owncloud is really ... i was going to say, muy bueno, but no, it's beyond that: i rely a lot on it. all of my digitalized stuff is on that cloud, from calendar, tasks, pics, documents and much more. i realized, without the cloud, things become more complicated. because all my different machines, phones and other devices aren't synced anymore. just trying to explain my situation ...

**Comment by RealRancor** [comment]
Hi,

i don't produce anything as i'm just a user as you are. :wink: 

But you just can't expect a "killer" MySQL config which runs perfect on every single system out there and performances as best as possible. This just doesn't exist and needs to be created for your specific system.

In general you can get some basic infos for MySQL tuning here:

https://doc.owncloud.org/server/8.0/admin_manual/configuration_server/performance_tuning.html#database-best-practice

but everything else is in the hand of the admin (there are even jobs like Database administrator/DBA outh there).

**Comment by RealRancor** [comment]
Btw. just an info to the two settings ```wait_timeout``` and ```max_allowed_packet```:

Both defaults for those values can be found here:

https://dev.mysql.com/doc/refman/5.6/en/server-system-variables.html#sysvar_max_allowed_packet
https://dev.mysql.com/doc/refman/5.6/en/server-system-variables.html#sysvar_wait_timeout

Try to raise those step by step until you don't get the message anymore. There is also a discussion ongoing here: https://github.com/owncloud/core/issues/15407 to workaround too low configured limits.
