### ISSUE TITLE
default_charset error in 8.1 and Master - isPhpCharSetUtf8 is missing in /lib/private/util.php

### ISSUE THREAD

**Issue by derkostka** [owncloud/core#15791]
Steps to reproduce

Between 8.0.3-rc3 and 8.1.0-alpha1 the operation isPhpCharSetUtf8 (and maybe even some     others) got lost.

As a result, the error "default_charset" is not UTF-8 appears again and again.

See: (search for isPhpCharSetUtf8)
https://github.com/owncloud/core/blob/master/lib/private/util.php
vs.
https://github.com/owncloud/core/blob/v8.0.3RC3/lib/private/util.php

Expected behaviour

No errors, cron shall run also
Actual behaviour
Error in admin preferences and cron does not work. aside everything else is okay
Server configuration

Operating system: Ubuntu 14.04
Web server: apache2
Database: mySQL
PHP version: PHP 5.5.9-1ubuntu4.5
ownCloud version: Owncloud 8.1.0-Alpha1 and also Master

Are you using external storage: yes, local file system and oc-smb mounts
Are you using encryption: no

**Comment by karlitschek** [comment]
@LukasReschke what do you think? What is the 8.1 way to handle this?

**Comment by LukasReschke** [comment]
> As a result, the error "default_charset" is not UTF-8 appears again and again.

Where do you see this error? In 8.1 we should actually enforce UTF-8 as per https://github.com/owncloud/core/blob/9dc12d40d846d54e024812c2c23c402073f8dd03/lib/private/util.php#L676

**Comment by derkostka** [comment]
I´ve got this error in the occ as well as in cron.php and in the admin preferences. after manually copying the operation from 8.0.3 into 8.1 this error is gone. i´ve checked by php config, it definitly is UTF-8. please compare both files.

**Comment by LukasReschke** [comment]
What is the exact error message? – Are you sure you actually copied everything correct? The error message in the admin settings has been removed as of https://github.com/owncloud/core/commit/06cf93e6ee19ea5c710b029fd403af3c90529074

Alternatively a screenshot, without more information this is only pure guessing. Best is usually to fill out the issue template (https://github.com/owncloud/core/blob/master/CONTRIBUTING.md)

**Comment by derkostka** [comment]
Well ..  now after my manual changes cron completed. Now,  the message is gone and does not return.

So the intention is to only throw this error once, when installing or upgrading to at least 8.1 right ?

php is configurfed properly:
![screen-capture](https://cloud.githubusercontent.com/assets/8389316/7261859/4547d964-e875-11e4-86ba-4a03526b876f.png)

**Comment by LukasReschke** [comment]
`isPhpCharSetUtf8` is unrelated to this error message, it does only read the value and does not set something etc. and again:

> What is the exact error message?

Can you quote the error message please?

> So the intention is to only throw this error once, when installing or upgrading to at least 8.1 right ?

These errors should appear and prevent usage of the ownCloud instance unless they are addressed. However, the results are cached in the session and thus we might need to verify if the cache is invalidated when we update the instance.

cron on it's own is yet another topic.

**Comment by derkostka** [comment]
The error message was like that (im german, i did not take a screenshot): PHP setting "default_charset" is not set to "'UTF-8'".

i tried to update another clean instance of 8.0.3 to 8.1 and it works perfectly. Sorry i can´t rerproduce this.

Any idea how i could check for the actual php setting within owncloud ? Otherwise this ticket can be closed , again ...

**Comment by derkostka** [comment]
i cannot reproduce this one either. Please close !
