### ISSUE TITLE
Blank screen while using "old" share link public.php

### ISSUE THREAD

**Issue by sitcool** [owncloud/core#15790]
Hello,

using my iOS own-cloud app i can send "share links" to friends easily . The app is using the "old" link with public.php.
When I open this public.php link I only see a blank screen. 
Nothing in the error logs. If I record the SQL-request it stops at 
[code]{"reqId":"6e5424df1154e95d16b1d0d694bf858c","remoteAddr":"XXX.XXX:XXX.XXX","app":"core","message":"DB prepare : SELECT `id` FROM `oc_jobs` WHERE `class` = ? AND `argument` = ?","level":0,"time":"2015-04-20T19:24:30+00:00","method":"GET","url":"\/public.php?service=files&t=jEgytGnufXicemY"}[/code]

What can I do to fix this?
"Share links" with index.php work find.

Thanks
Georg

**Comment by LukasReschke** [comment]
Please post the complete link (without domain if you don't want to) as well as some more information such as which version you use, etc. – see https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by sitcool** [comment]
The link is https://own.pelda.de/public.php?service=files&t=XAN9zq5qxNsWrvS

I'm using OC 8.0.2 (new installation didn't help)
The app version is 3.4.1
It's the same for IE as FF as Safari...

**Comment by LukasReschke** [comment]
Was this a 7.x install before? Please execute the following query on your database and report the result set back: `SELECT * from oc_appconfig where appid="core";`

**Comment by sitcool** [comment]
Yes, it was 7.x before. But to fix the problem I finaly tried a new installation. Also new DB. But still the same Problem. 
Thanks for your help!!

core,"global_cache_gc_lastrun","1429647591"
core,"installedat","1429645075.7484"
core,"lastcron","1429647606"
core,"lastupdateResult","{""version"":{},""versionstring"":{},""url"":{},""web"":{}}"
core,"lastupdatedat","1429647595"
core,"public_files","files_sharing/public.php"
core,"public_gallery","gallery/public.php"
core,"public_webdav","files_sharing/publicwebdav.php"
core,"remote_files","files/appinfo/remote.php"
core,"remote_webdav","files/appinfo/remote.php"
core,"shareapi_allow_links","no"
core,"shareapi_allow_resharing","no"

**Comment by LukasReschke** [comment]
> core,"public_files","files_sharing/public.php"

That actually looks good. When accessing `https://own.pelda.de/public.php?service=files` I see some errors, can you take a look at your ownCloud log in `data` and also the PHP log (usually in the apache error log) and report back if there is by chance something related to this?

**Comment by sitcool** [comment]
{"reqId":"4e8d5a8e877b7728afab2eaeaa4c2c2a","remoteAddr":"188.108.93.194","app":"remote","message":"Parameter \"token\" for route \"files_sharing.sharecontroller.showShare\" must match \"[^\/]++\" (\"\" given) to generate a corresponding URL.","level":4,"time":"2015-04-21T20:52:48+00:00"}

**Comment by LukasReschke** [comment]
Can you please try to apply the changes from https://github.com/owncloud/core/pull/14509 and report back if it still works? If not: Does the error look different now?

**Comment by sitcool** [comment]
I'm not sure where to find the php error log on my (hosted) server:-/

**Comment by sitcool** [comment]
Yes, it still "works" but blank screen again.
public.php looks now like this:
<?php

// This file is just used to redirect the legacy sharing URLs (< ownCloud 8) to the new ones

$urlGenerator = new \OC\URLGenerator(\OC::$server->getConfig());
$token = isset($_GET['t']) ? $_GET['t'] : '';
$route = isset($_GET['download']) ? 'files_sharing.sharecontroller.downloadShare' : 'files_sharing.sharecontroller.showShare';

if($token !== '') {
	OC_Response::redirect($urlGenerator->linkToRoute($route, array('token' => $token)));
} else {
	header('HTTP/1.0 404 Not Found');
	$tmpl = new OCP\Template('', '404', 'guest');
	print_unescaped($tmpl->fetchPage());
}

**Comment by sitcool** [comment]
Any idea how to fix the problem?

**Comment by MorrisJobke** [comment]
@sitcool I now get the correct HTTP 404 with an empty token and a weird HTTP 304 for the token you provided. @LukasReschke Shouldn't then there be a redirect?

**Comment by PVince81** [comment]
Is this still happening with 8.0.5 ?

**Comment by sitcool** [comment]
Problem solved:-)
