### ISSUE TITLE
occ ldap:search with a limit = 0 only shows the first 5 users in the LDAP server

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#15796]
### Steps to reproduce
1. Setup a LDAP with several users and connect it to OC (checked with openLDAP)
2. Use `./occ ldap:search --limit=0 ''`
### Expected behaviour

All users in the LDAP server are shown.
### Actual behaviour

Only the first 5 users are shown
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.4

**ownCloud version:** 8.1 alpha 1

**Updated from an older ownCloud or fresh install:** fresh install
### Notes

This doesn't happens in OC 8.0.3RC1

**Comment by jvillafanez** [comment]
@blizzz

**Comment by blizzz** [comment]
5 is an odd number. what if you set the limit to 12, will you get 12 or 5?

**Comment by jvillafanez** [comment]
the limit seems to work fine for the rest of cases

**Comment by jvillafanez** [comment]
Still happening in 8.1 alpha 2

I have several configurations, two of them active. With one active, it only shows 20 users even though there are more than 1000; with two active it shows 65 users (it should be around 1047)

**Comment by jvillafanez** [comment]
@blizzz I think the problem is that the "paging chunksize" is being enforced in the results. The configuration that shows 20 users have that chunksize in its configuration. I've also checked with a large server (about 1000 users or so) and it only shows 500 results (same value as its paging chunksize)

**Comment by PVince81** [comment]
Works for me on 9.1.0 beta2. Please reopen if it still occurs for you.

**Comment by PVince81** [comment]
Okay, I only had a simple config, no chunksize stuff. So not sure.
Reopening.

**Comment by jvillafanez** [comment]
Setting the chunksize to 20 will still show all the users if the limit parameter is 0 ->
* stable9.1 Works
* stable9.0 Works
* stable8.2 **Fails**  (shows only 20 users)

**Comment by PVince81** [comment]
Please reopen in the [user_ldap app repo] https://github.com/owncloud/user_ldap if the problem persists in 10.0.4 with the latest user_ldap app from the marketplace.

Seems it used to be an old 8.2 issue ?
