### ISSUE TITLE
account deletion

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#158]
People should have the possibility to delete their own account through the personal settings.
The question is how usernames and still present data should be handled.
- moved into another directory deleted-users or so, so that it’s inaccessible for people who register the same name afterwards, but could still be restored by an admin, but automatically deleted after some time?
- completely deleted on the spot?

**Comment by hodyroff** [comment]
This should not be a feature in the core. Maybe in its own app so it can be added by the people who want it. Too many scenarios where this is unwanted.
