### ISSUE TITLE
OwnCloud Setup NAS

### ISSUE THREAD

**Issue by LukeHamer** [owncloud/core#15803]
Hi Guys

We have version 6 and 7 of OwnCloud on our system but we would like to setup a sync to a NAS device similar to the client, does anyone have any recommendations to which NAS we could use this is compatible with this.

Cheers 
Luke

**Comment by RealRancor** [comment]
Hi,

this is an issue tracker to report bugs or feature requests for ownCloud. Such questions related how and where to run ownCloud should be asked at the forums or the users mailinglist.
