### ISSUE TITLE
Apps menu loading spinner does not show up anymore for just installed apps

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#15806]
1. Go to the apps management
2. Install a new app
3. Open the apps menu and click that app

Expected:
A spinner shows over the app just like it does when you click other apps.

What actually happens:
The app icon only vanishes but no spinner shows.

cc @PVince81 @MorrisJobke @owncloud/designers this worked before but somewhere along the way it must’ve broke.

**Comment by MorrisJobke** [comment]
I just tried and it never worked with the newly added icon. I will nevertheless have a look.

**Comment by jancborchardt** [comment]
Really …? I’m pretty sure @PVince81 and I specifically fixed it when working on the apps dropdown back for ownCloud 7. Anyway, thank you!

**Comment by MorrisJobke** [comment]
Fix is in #15846
