### ISSUE TITLE
php fatal error trying to delete a LDAP user

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#15804]
### Steps to reproduce
1. Setup a LDAP server and configure it in OC
2. Login in OC with any of the LDAP users. This will create the user data folder in OC (you can upload some files)
3. Disconnect the LDAP server (or set the configuration inactive in the LDAP wizard)
4. Run `./occ user:delete <userID>` (you can check the userID in the data folder)

### Expected behaviour
The user data is deleted from OC

### Actual behaviour
A php fatal error is shown

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.4

**ownCloud version:** OC 8.1 alpha 1

**Updated from an older ownCloud or fresh install:** fresh install

#### console output
```
PHP Fatal error:  Call to a member function delete() on a non-object in /home/jvillafanez/src/owncloud/owncloud2/core/command/user/delete.php on line 54

Fatal error: Call to a member function delete() on a non-object in /home/jvillafanez/src/owncloud/owncloud2/core/command/user/delete.php on line 54
```

### Notes
The same error is thrown trying to delete a wrong user (the user is missing)

After checking that the user is missing and added to the "remnants list" (using ldap:check-user), the user data can be deleted correctly

**Comment by karlitschek** [comment]
@blizzz

**Comment by DeepDiver1975** [comment]
is_null check is missing - can happen with any backend - not ldap related
https://github.com/owncloud/core/blob/master/core/command/user/delete.php#L54

@nickvergessen @MorrisJobke PR please - THX

**Comment by DeepDiver1975** [comment]
> PR please - THX

with unit tests :speak_no_evil:

**Comment by nickvergessen** [comment]
Hmm, We can catch the case and just say `The user does not exist`, however, it may exist, it's just the UserBackend server is currently not available.

Should we try to detect that case and then print an additional message?

**Comment by DeepDiver1975** [comment]
> Hmm, We can catch the case and just say The user does not exist,

enough from my understanding for now
