### ISSUE TITLE
Share menu of items in the bottom of the list is not visible

### ISSUE THREAD

**Issue by donniezazen** [owncloud/core#15801]
When sharing a item in the bottom of the list the share menu opens itself below it which is not accessible. Please see the screenshot.

![snapshot47](https://cloud.githubusercontent.com/assets/841656/7272850/b7686108-e90b-11e4-9a8b-020112c081a1.png)

**Comment by jancborchardt** [comment]
Thank you for the design issue report! :) Fix is at https://github.com/owncloud/core/pull/15805, please review.
