### ISSUE TITLE
cleanFolder does a PROPFIND on every file in S2S case

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15802]
I noticed on 7.0.5 that whenever you mount a remote share, the update detection will not only call shareinfo.php but also call cleanFolder(), which will itself call file_exists() on every file inside the folder, which itself calls PROPFIND on the remote files.

Originally this was intended to detect whether files inside the remote share folder were deleted.
We should already have that information through the ajax/shareinfo.php call, so we can probably do a diff between the local cache and remote cache to find out which entries to remove without the need of doing extra remote PROPFINDs (which can be slow in S2S situations)

@icewind1991 as discussed

**Comment by PVince81** [comment]
Setting to 8.1 in case there is time left, else 8.2. (it doesn't break functionality, just makes S2S slow)

CC @DeepDiver1975

**Comment by PVince81** [comment]
Slightly related: https://github.com/owncloud/core/issues/15904 would be an alternative approach (switching to PROPFIND with an update detection logic similar to the sync client instead of shareinfo.php)

**Comment by PVince81** [comment]
Related: https://github.com/owncloud/core/issues/24421

Still happening in 9.1.0beta2 and it seems the stat cache misses in this case. This is when browsing the parent folder in which the received fed share is in.

@icewind1991 I hope we can get rid of `cleanFolders` altogether, or at least let specific storage backends tell that they don't need it like fed shares. Fed shares don't need it because they rely on etags for update detection.

**Comment by icewind1991** [comment]
> or at least let specific storage backends tell that they don't need it like fed shares

https://github.com/owncloud/core/pull/25103
