### ISSUE TITLE
Cannot login with a "person" objectClass with LDAP

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#15816]
### Steps to reproduce
1. Consider the following LDAP entry:
   `
   # 007_person, people, owncloudqa2.com
   dn: cn=007,ou=people,dc=owncloudqa2,dc=com
   objectClass: person
   cn: 007
   sn: person
   userPassword:: e1NTSEF9YWppZkFtckxIeExvcm0yOUdoWHBmYzdkU3Zpa2VzS2Q=
   `
2. In the LDAP wizard, set the user filter to `(|(objectclass=person))`
3. In the LDAP wizard, set the login filter with username, email and "sn" attribute". The login filter should be something like: `(&(|(objectclass=person))(|(uid=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))(|(sn=%uid))))`
4. Try to login with the user in step 1 (username = person / password = secret)
### Expected behaviour

According with the setup in the LDAP wizard, you should be able to login
### Actual behaviour

You can't login
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.4

**ownCloud version:** OC 8.1 alpha 1

**Updated from an older ownCloud or fresh install:** fresh install
#### ownCloud log (data/owncloud.log)

```
{"reqId":"wpaYEepUPIZw+GWl019v","remoteAddr":"10.40.30.21","app":"user_ldap","message":"LDAP Login: Could not get user object for DN cn=007,ou=people,dc=owncloudqa2,dc=com. Maybe the LDAP entry has no set display name attribute?","level":2,"time":"2015-04-22T16:09:56+00:00"}
{"reqId":"wpaYEepUPIZw+GWl019v","remoteAddr":"10.40.30.21","app":"core","message":"Login failed: 'person' (Remote IP: '10.40.30.21)","level":2,"time":"2015-04-22T16:09:56+00:00"}
```
### Notes

Trying to add the display name attribute in the LDAP entry fails:

```
ldap_add: Object class violation (65)
    additional info: attribute 'displayName' not allowed
```

This might also happen with organizationalPerson object class.

**Comment by jvillafanez** [comment]
@blizzz

**Comment by blizzz** [comment]
@jvillafanez the attribute displayname belongs to the scheme inetOrgPerson. If the the user does not have inetOrgPerson as objectclass, attempting to add displayname will always fail. In that case you either make it an inetOrgPerson, too, or you change the displayname attribute in the LDAP settings to something different, for instance "cn".

**Comment by jvillafanez** [comment]
@blizzz From an UX perspective, I would remove the options to set the person or organizationalPerson from the select, and stick only with the inetOrgPerson.

A standard admin would go for a quick setup without touching the advanced section neither the expert section. If the admin sets the person objectClass he'll likely have similar issues, and he'll need some extra configuration.

From the 2 solutions you've given, if I need to change the LDAP entry to use an inetOrgPerson, then the option in the wizard to choose the person is useless; changing the displayname attribute in the LDAP settings needs extra configuration easily avoidable using an inetOrgPerson, which can have additional implications.

Sticking only with the inteOrgPerson objectClass makes a simpler configuration for the admin, and less error prone. If the admin still wants to use the person objectClass, he can edit the filter anyway.

**Comment by blizzz** [comment]
> @blizzz From an UX perspective, I would remove the options to set the person or organizationalPerson from the select, and stick only with the inetOrgPerson.

inetOrgPerson is not necessarily available, but we might actually pick it, if available and returning users. @bboule @MTRichards do you think this would be useful?

> A standard admin would go for a quick setup without touching the advanced section neither the expert section. If the admin sets the person objectClass he'll likely have similar issues, and he'll need some extra configuration.

The displayname is supposed to be detected (either displayname, otherwise cn), but it does not take into account possibly chosen objectclasses. This is to be improved.

**Comment by PVince81** [comment]
Please reopen in the [user_ldap app repo] https://github.com/owncloud/user_ldap if the problem persists in 10.0.4 with the latest user_ldap app from the marketplace.
