### ISSUE TITLE
Long group names should be displayed when moused-over

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#15819]
### Steps to reproduce

1. Install 8.1 enterprise
2. Navigate to the admin page
3. Create a group with a really long name
4. Put the admin user in the group
5. Mouse over the admin's groups

### Expected behaviour

The full group name should be displayed on mouse-over

### Actual behaviour

The user only sees the truncated name with elipses:

![p326](https://cloud.githubusercontent.com/assets/8480343/7284288/8bd80012-e90a-11e4-9121-7b28e555524b.PNG)

### Server configuration

Ubuntu 14.04
PHP 5.5.9
ownCloud Enterprise Edition 8.1 alpha 1 (daily) Build:2015-04-16T03:08:13+00:00 f50798a674bf223e1c8015b9a27287b2ac6c9f1a

**Comment by DeepDiver1975** [comment]
@jancborchardt can you help out here? THX

**Comment by jancborchardt** [comment]
Fixed at https://github.com/owncloud/core/pull/15947 – @jnfrmarks in the future you can also just @-mention me with @jancborchardt so I directly see the issue. :)

**Comment by nickvergessen** [comment]
![group dropdown](https://cloud.githubusercontent.com/assets/213943/7450668/dcfba53e-f247-11e4-9440-e5df2b94da7f.png)

Should we put an ellipse character at the end, it "looks broken" atm

**Comment by MorrisJobke** [comment]
> Should we put an ellipse character at the end, it "looks broken" atm

Yes :+1:

**Comment by MorrisJobke** [comment]
I changed the label rule (`ul.multiselectoptions > li input[type="checkbox"] + label`) but it doesn't look good, because the overflow causes a line break somehow. @jancborchardt Can you have a look
```css
/* snip */
padding: 5px 5px 5px 27px;
box-sizing: border-box;
text-overflow: ellipsis;
overflow: hidden;
margin: 0 -27px;
```

**Comment by jancborchardt** [comment]
@MorrisJobke `white-space: nowrap;` ;)

**Comment by MorrisJobke** [comment]
> @MorrisJobke white-space: nowrap; ;)

It isn't really a line break ... the checkbox is somehow shifted to the bottom:

![bildschirmfoto von 2015-05-04 13-28-58](https://cloud.githubusercontent.com/assets/245432/7452779/531b476e-f262-11e4-8be0-a8d975ec9313.png)
![bildschirmfoto von 2015-05-04 13-29-06](https://cloud.githubusercontent.com/assets/245432/7452780/54d41e6e-f262-11e4-9438-ccf2d0f9077f.png)
![bildschirmfoto von 2015-05-04 13-29-09](https://cloud.githubusercontent.com/assets/245432/7452781/56e14de4-f262-11e4-9dd0-0ee26c99ed03.png)

**Comment by jancborchardt** [comment]
Ah right, I had the same thing when I dabbled around with it. Honestly the ellipsis is not something for 8.1

**Comment by MorrisJobke** [comment]
@jancborchardt okay ... I will open a  ticket.

**Comment by MorrisJobke** [comment]
Ref #16041

**Comment by jancborchardt** [comment]
Thank you!
