### ISSUE TITLE
Multi-tenancy support

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#15810]
Multi-tenancy support would be great for web hosting companies.
* Single global configuration file for items such as previews
* multiple domain names per account
* Mounting /home/user/cloud as the home directory
* Each domain owner is a sub-admin
* Federated clouds coming from the same instance would be much faster
* etc

**Comment by DeepDiver1975** [comment]
From my understanding there are mechanisms to do this as of today - @Gomez might give some insights in the setup of https://portknox.net/de

**Comment by oparoz** [comment]
One things that seem to be missing to do this right is for an admin to be able pick a theme based on the domain.
Another is to be able to assign a mount configuration at user creation time, but I guess instructions could be given so that the admin can mount his user space himslef.

**Comment by Gomez** [comment]
Nearly all portknox.net clouds are separated/dedicated installation. I use common linux tools to do this. The config is autogenerated and can be updated on all clouds. Works good, but always room for improvement/new ways.
Happy to show more insights if some1 is interested. 

@oparoz You looked at the autoconfig.php? Should be possible to extend it to add theme/domain/mount logik.

**Comment by oparoz** [comment]
@Gomez - Thanks for the feedback. There are indeed some tools out there which help with the setup and management of several oC instances, but I find it highly inefficient when several of these instances end up on the same hardware.

I couldn't find autoconfig.php in master, but if it's similar to the testing script I guess that can be modified, but the goal of this ticket is to get oC to support that sort of configuration.
There needs to be at least a domain identifier somewhere so that users and a mount point can be linked to that domain.

**Comment by hodyroff** [comment]
https://owncloud.com/blog-multi-tenancy-owncloud/
This will not be available for ownCloud for ages, happy to discuss in the comments to the above, if I missed a point.

**Comment by shyamal890** [comment]
This is a much needed feature. Completely agree with @oparoz

**Comment by hodyroff** [comment]
@shyamal890 Any specific comments on the related blog post above? Or would you be looking for a scalable setup in this regards? Leveraging Docker/Ansible and other DevOps tools going forward seems to be the best approach.
