### ISSUE TITLE
Varying width for group dropdown and mouse overs on longer names

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#15820]
### Steps to reproduce

1. Install 8.1 enterprise
2. Navigate to the admin page
3. Create a group with a really long name
4. Select the group drop down for a user

### Expected behaviour

The full group name should show up on mouse over or the box should be large enough

### Actual behaviour

The width of the drop down depends on the selected group and anything larger than the selected group is chopped off  I like the varying width - maybe what we need to do is fix the mouse over?

![p325](https://cloud.githubusercontent.com/assets/8480343/7284382/166394d0-e90b-11e4-8e31-0681f1fa5ca4.PNG)

![p326](https://cloud.githubusercontent.com/assets/8480343/7284389/2103403e-e90b-11e4-89de-43ce25b89739.PNG)

### Server configuration

Ubuntu 14.04
PHP 5.5.9
ownCloud Enterprise Edition 8.1 alpha 1 (daily) Build:2015-04-16T03:08:13+00:00 f50798a674bf223e1c8015b9a27287b2ac6c9f1a

**Comment by nickvergessen** [comment]
Related #15819

**Comment by DeepDiver1975** [comment]
@jancborchardt can you help out here? THX

**Comment by jancborchardt** [comment]
Fix at https://github.com/owncloud/core/pull/15947
