### ISSUE TITLE
Groups are disappearing and reappearing from the UI 

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#15821]
### Steps to reproduce

1. Install 8.1 
2. enable encryption
3. Navigate to the admin page
4. Create a group with a really long name
5. Select the group drop down for a user
6. Muck around with the dropdown, adding and removing users from the groups
7. The group mysteriously disappears
8. Add another group
9. Refresh the page
10. The group mysteriously reappears

### Expected behaviour

The groups should not be appearing and disappearing

### Actual behaviour

The groups are appearing and disappearing

I have no idea on what caused this - filing this bug for now incase someone can see something. I see this error in the sever log file but I don't know if it happened when I was adding the groups or not:

![p327](https://cloud.githubusercontent.com/assets/8480343/7284399/3fde42a6-e90b-11e4-8d10-6edfff1c187b.PNG)

![p328](https://cloud.githubusercontent.com/assets/8480343/7284403/488167b2-e90b-11e4-818d-0d28b8d64ca4.PNG)

```

{"reqId":"Fhn9ntY6nnATqZ+V0Rvv","remoteAddr":"192.168.1.219","app":"index","message":"Exception: {\"Exception\":\"OC\\\\Encryption\\\\Exceptions\\\\ModuleAlreadyExistsException\",\"Message\":\"Id \\\"OC_DEFAULT_MODULE\\\" already used by encryption module \\\"ownCloud Default Encryption\\\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/encryption\\\/appinfo\\\/application.php(104): OC\\\\Encryption\\\\Manager->registerEncryptionModule('OC_DEFAULT_MODU...', 'ownCloud Defaul...', Object(Closure))\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/encryption\\\/appinfo\\\/app.php(30): OCA\\\\Encryption\\\\AppInfo\\\\Application->registerEncryptionModule()\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/app.php(388): require('\\\/var\\\/www\\\/html\\\/o...')\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/settings\\\/ajax\\\/navigationdetect.php(30): OC_App::getAppNavigationEntries('encryption')\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(153) : runtime-created function(1): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#5 [internal function]: __lambda_func(Array)\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(272): call_user_func('?lambda_95', Array)\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(853): OC\\\\Route\\\\Router->match('\\\/settings\\\/ajax\\\/...')\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/encryption\\\/manager.php\",\"Line\":100}","level":4,"time":"2015-04-22T19:42:07+00:00"}
{"reqId":"kDmmsZEgSjEMtcupFgEt","remoteAddr":"","app":"PHP","message":"Argument 3 passed to OC\\Encryption\\Manager::registerEncryptionModule() must be callable, object given, called in \/var\/www\/html\/owncloud\/apps\/encryption_dummy\/appinfo\/app.php on line 5 and defined at \/var\/www\/html\/owncloud\/lib\/private\/encryption\/manager.php#97","level":3,"time":"2015-04-22T19:43:32+00:00"}


```

### Server configuration

Ubuntu 14.04
PHP 5.5.9
ownCloud Enterprise Edition 8.1 alpha 1 (daily) Build:2015-04-16T03:08:13+00:00 f50798a674bf223e1c8015b9a27287b2ac6c9f1a

**Comment by karlitschek** [comment]
@jnfrmarks Can you retest?

**Comment by PVince81** [comment]
Did you create groups during your mucking around ?
I could imagine that some code paths do not properly update the dropdowns and might miss newly created groups.

Note that if you create a new group in the dropdown in the top bar, but did not create a user, it will not actually create a group.
Also creating a group without assigning it to a real user might not actually create the group either.

**Comment by jnfrmarks** [comment]
I'm closing this as I can't reproduce it.

**Comment by PVince81** [comment]
you forgot to close, closing.
