### ISSUE TITLE
[enc2] Recovery key doesn't seem to work

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15825]
### Steps to reproduce
1. Setup OC from scratch
2. Enable encryption and the default enc module
3. Log out then log in again as admin
4. Enable recovery key by setting a recovery password in the admin page
5. Create a user "user1" with password "test"
6. Login as "user1" and upload some files
7. Enable recovery key in the personal page
8. Login as admin
9. Go to the users page
10. Enter the recovery password
11. Change the password of "user1" to "xxx" (imagine the user had forgotten the password)
12. Login as "user1" with the password "xxx"
13. Access files

### Expected result
"user1" still has access to files.

### Actual result
After login, "user1" sees a notification about invalid private keys, asks the user to enter their password in the personal page. However, "user1" has forgotten the old password and cannot do that.

### Version
ownCloud 8.1 alpha2

@schiesbn @th3fallen @DeepDiver1975

**Comment by DeepDiver1975** [comment]
@th3fallen can you please take care of this? THX

**Comment by schiesbn** [comment]
@th3fallen sorry, just saw now that Thomas mentioned you. Hope you didn't already start working on it... My proposed fix is here: https://github.com/owncloud/core/pull/15911

**Comment by SergioBertolinSG** [comment]
I see a problem here, after following the steps the files accessed by user1 are encrypted after downloading them or using files_texteditor

**Comment by schiesbn** [comment]
I can't reproduce it... @PVince81 how about you?

**Comment by PVince81** [comment]
@SergioBertolinSG the UX of recovery has some problems, so it's easy to get confused and miss something. Did you use the exact steps as provided in my first comment ? You need to enable recovery both in the admin page and also for the user.

Then when you enter the user's new password, you need to hit enter. You won't get any visual feedback (the bad UX issue), but it should have done its work.

**Comment by PVince81** [comment]
@schiesbn to answer your question, I already tested it in your PR: https://github.com/owncloud/core/pull/15911#issuecomment-97023418

Now if @SergioBertolinSG still says it's broken on master, maybe some other change that was on master broke it.

**Comment by PVince81** [comment]
Just to be sure I tried again on master (002d74f95ab8d06e969fdd2c3ceeca4e766f3251) and it works for me too. user1 can properly download the file after changing the password.

**Comment by SergioBertolinSG** [comment]
OK, tested again. Exact steps works fine. 
I added a couple more in my test:
14. Login as admin.
15. In admin page change recovery password.
16. Go to users page. Enter new recovery password, hit enter.
17. Change user1 password to xxx2.
18. Login with user1 with password xxx2.
19. Try to access files.


and after this steps files can't be decrypted for user1.

**Comment by schiesbn** [comment]
Thanks for the updated tests steps... I will try this later today. Generally speaking this shouldn't make a difference because the key should stay the same, it is only encrypted with a different password.

**Comment by schiesbn** [comment]
I could reproduce and already know what's going wrong... Will prepare a pull request
