### ISSUE TITLE
[enc2] No error message for wrong recovery password in users page

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15822]
### Steps
1. Enable encryption + default module
2. As "root" (the admin) add a recovery password "recovery" in the admin page
3. Create a user "user1" with the password "test"
4. Login as "user1" 
5. Upload a file
6. Login as "root"
7. Go to the users page
8. Enter the wrong recovery password "wrong"
9. Change "user1"'s password

### Expected result
Error message that recovery password is wrong (or that password could not be changed)

### Actual result
No UI feedback. Ajax call returns 200 OK.

### Versions
ownCloud git master (f8f354b351a349898bbb5cdf2d9bee1c798c0f73)

@schiesbn @th3fallen @DeepDiver1975

**Comment by PVince81** [comment]
Note: I forgot to enable recovery for "user1". But even if I enable it, no message is shown.

On stable8: if "user1" has recovery enabled, the wrong recovery password will produce a message.
However if the user doesn't have recovery enabled, the password is ignored even when wrong, no message is shown (bad UX still).

For now let's focus on the regression case: when recovery password is wrong, an error notification must be shown as it was the case in stable8.

**Comment by DeepDiver1975** [comment]
@jancborchardt you might want to review the UX here and give directions - THX

**Comment by PVince81** [comment]
Well, so far the UX for the recovery path was sub-par. I already raised some tickets to address it: https://github.com/owncloud/core/issues/11107

**Comment by jancborchardt** [comment]
Yup, show a yellow error notification here.

**Comment by DeepDiver1975** [comment]
@th3fallen can you please take care of this? THX
