### ISSUE TITLE
[enc2] Missing tooltip that tells that a user doesn't have recovery enabled

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15823]
### Steps
1. Enable encryption + default module
2. As "root" (the admin) add a recovery password "recovery" in the admin page
3. Create a user "user1" with the password "test"
4. Login as "user1" 
5. Upload a file
6. Login as "root"
7. Go to the admin page
8. Enter the correct recovery password "recovery"
9. Click on "user1"'s password field and wait for the tooltip to appear

### Expected result
Like on stable8, show a tooltip that tells that this user has no recovery key configured and changing the password will cause data loss.
![enc-user-recovery-missing](https://cloud.githubusercontent.com/assets/277525/7294422/881155c0-e9ad-11e4-8014-ac1c82b4f3eb.png)

### Actual result
Missing tooltip.

Note: as an addition, if the admin does change the password it would be good to show that message again in the orange notification "Password changed, but data loss because no recovery key for user ..."

### Versions
ownCloud 8.1 alpha2

@schiesbn @th3fallen @DeepDiver1975

**Comment by DeepDiver1975** [comment]
@th3fallen can you please taken care of this? THX

**Comment by schiesbn** [comment]
fix merged
