### ISSUE TITLE
How can i set quota to the user while creating user using api?

### ISSUE THREAD

**Issue by vikasnagare** [owncloud/core#15824]
Hi want to set max quota for the user. I'm creating user using provisioning api.

**Comment by nickvergessen** [comment]
This is not possible atm

**Comment by PVince81** [comment]
You can set the quota in a subsequent editUser call after after having created the user, see https://doc.owncloud.org/server/8.1/admin_manual/configuration_user/user_provisioning_api.html#users-edituser
