### ISSUE TITLE
Conflicting configuration warnings on admin page

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#15832]
### Steps to reproduce

1. Install 8.1 
2. Do not set a cacheing model
3. Go to admin page

### Expected behaviour

The only message about cacheing should be that it's not configured

### Actual behaviour

I see messages about the APCu version and that cacheing is not configured.  I'm thinking that we shouldn't be checking the version if it's not configured.

![p329](https://cloud.githubusercontent.com/assets/8480343/7296700/ff8f7be0-e98f-11e4-867a-a2b7fdb8c626.PNG)

### Server configuration

Ubuntu 14.04
PHP 5.5.9
ownCloud Enterprise Edition 8.1 alpha 2 (testing)

**Comment by RealRancor** [comment]
Hi,

isn't it so that APCu was disabled because of the old version and then the second message appears because there is no other memory cache configured?

**Comment by jnfrmarks** [comment]
I was thinking: why are we checking the APCu version if it's not even configured?

**Comment by DeepDiver1975** [comment]
Well - the list of warnings might cause confusion - but technically speaking they are correct.

1. APCu was detected with a wrong version -> warning is reported and not used
2. Because no other memcache was detected -> warning because performance will not be optimal

**Comment by jnfrmarks** [comment]
I agree that they are technically correct.  I am just questioning if we should be displaying 1 if no memcache is configured.  If we're ok with this, then we can close this issue.

**Comment by DeepDiver1975** [comment]
well removing either of these messages can result in confusion as well.

But this is more a UX/tech writer topic @jancborchardt @carlaschroder THX

**Comment by jancborchardt** [comment]
It seems like yeah, if no memory cache is configured, then we don’t need the APCu message.

**Comment by DeepDiver1975** [comment]
well and then you turn APCu on -> what shall happen?

APCu is broken and you have still no mem cache

**Comment by jnfrmarks** [comment]
Then I should get a message saying that APCu is the wrong version.

My issue is we're checking something that isn't yet configured and providing an error to the user on that.  We should only be checking it if it's configured.

For instance, when I configured the memcache to XCache, I do not get the APCu error (as expected).  If you're saying that we should check it regardless of if memcache is configured in config.php then I would have expected the same warning when XCache was configured.

**Comment by jancborchardt** [comment]
Yup, as @jnfrmarks said. Ideally the APCu warning should also mention that it’s for caching.

**Comment by DeepDiver1975** [comment]
> Ideally the APCu warning should also mention that it’s for caching.

well - let's add a documentation link to it just like we did with the "no mem cache" warning

**Comment by carlaschroder** [comment]
OPCache replaces APC in PHP 5.5, and is included so you don't have to install it separately. http://php.net/manual/en/opcache.installation.php I think this may be more than a documentation issue.

**Comment by RealRancor** [comment]
Not exactly as also written here: https://github.com/owncloud/documentation/issues/1056#issuecomment-95478319

>APC is opcode cache and data store
>APCu is only data store
>OPcache is only opcode cache

**Comment by carlaschroder** [comment]
See how y'all like this one https://github.com/owncloud/documentation/pull/1099

**Comment by jnfrmarks** [comment]
Doc looks ok to me.  

Can we close this one? @carlaschroder @jancborchardt @DeepDiver1975
