### ISSUE TITLE
Error validating LDAP login attributes tab

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#15836]
### Steps to reproduce

1. Install 8.1 
2. Configure LDAP
3. On Login Attrributes tab, click verify settings

### Expected behaviour

The settings are verified and there are no errors

### Actual behaviour

The settings are not verified and there is an reror "Please provide a login anme to test against".
I don't see how to provide the login name - there is no text box for that and the Test Loginname button is greyed out.

![p330](https://cloud.githubusercontent.com/assets/8480343/7299007/4b496e54-e9a1-11e4-9c49-90778a7e1da9.PNG)

### Server configuration

Ubuntu 14.04
PHP 5.5.9
ownCloud Enterprise Edition 8.1 alpha 2 (testing)

**Comment by DeepDiver1975** [comment]
@blizzz THX

**Comment by blizzz** [comment]
@jnfrmarks on the lower left, next to the button

**Comment by blizzz** [comment]
>  Test Loginname button

it's a text field, not a button.

**Comment by jnfrmarks** [comment]
Ah! that works - how about if we grey out the verify settings button until someone enters a username in the loginname field?

**Comment by blizzz** [comment]
yup, sounds good

**Comment by PVince81** [comment]
@blizzz any update ?

**Comment by blizzz** [comment]
Fix in https://github.com/owncloud/core/pull/19342
