### ISSUE TITLE
LDAP Group Issues

### ISSUE THREAD

**Issue by sbelov1** [owncloud/core#15842]
Environment. 
Latest vmWare virtual appliance: OpenSUSE, Apache, MySQL
Description. Upon binding with an LDAP server, we select the group under User Filer tab. Group shows 3200 users as oppose to 17 (Issue 1). There's no sAmAccountName attribute available to select from a Login Filter (Issue 2), even though an attribute is there as all the user names properly render on the Users page for us. The User page shows only 2 users under Everyone where as the correct amount is shown under the group we selected - which is 17 (Issue 3). 

![users2](https://cloud.githubusercontent.com/assets/8365936/7302931/e3545330-e9ba-11e4-937c-f59440860ee5.JPG)

As a result of the above three issues,  the user can only login using their email, not the sAmAccountName. 
@blizzz I'll email you the logs once I get them. But there seem to be a Page Limit issue error which was consistent in the log.

**Comment by sbelov1** [comment]
Here's two sets of errors we're getting. Logs have been emailed.

"app":"PHP","message":"ldap_start_tls(): Unable to start TLS: Connect error at 

\/srv\/www\/htdocs\/owncloud\/apps\/user_ldap\/lib\/ldap.php#252","level":3,"time":"2015-04-22T19:21:49+00:00"},

"app":"user_ldap","message":"Configuration Error (prefix ): No LDAP Login Filter 
given!","level":2,"time":"2015-04-22T15:48:48+00:00"}]

**Comment by blizzz** [comment]
Please use the [template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md), also specify which LDAP server is in use.

**Comment by blizzz** [comment]
> @blizzz I'll email you the logs once I get them

Please make them generally available, ideally publicly, but if this is not possible then on s3.

**Comment by sbelov1** [comment]
@blizzz we should keep customer logs confidential. As you suggested, I've uploaded them in S3 under 15842 folder. They're running oC 8.0.2 and I'm getting the exact versions for MySQL/MariaDB and the  os.

**Comment by sbelov1** [comment]
Here it is. @blizzz please let me know if anything else is needed.
eval-appliance-oc8ee-vmdk-2015-8-6:~ # php -v
PHP 5.4.20 (cli)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies
    with Zend Guard Loader v3.3, Copyright (c) 1998-2013, by Zend Technologies
 
eval-appliance-oc8ee-vmdk-2015-8-6:~ # mysql -u root -p
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 2705
Server version: 5.5.33-MariaDB openSUSE package
 
Copyright (c) 2000, 2013, Oracle, Monty Program Ab and others.
 
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
 
MariaDB [(none)]> exit
Bye
 
eval-appliance-oc8ee-vmdk-2015-8-6:~ # cat /etc/os-release
NAME=openSUSE
VERSION="13.1 (Bottle)"
VERSION_ID="13.1"
PRETTY_NAME="openSUSE 13.1 (Bottle) (x86_64)"
ID=opensuse
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:opensuse:13.1"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://opensuse.org/"
ID_LIKE="suse"
eval-appliance-oc8ee-vmdk-2015-8-6:~ #

**Comment by blizzz** [comment]
@sbelov1 thank you. Any details about the LDAP server they use?

**Comment by sbelov1** [comment]
@blizzz what do we need exactly just a version? Its AD LDAP not an OpenLDAP.

**Comment by sbelov1** [comment]
@blizzz any updates?

**Comment by sbelov1** [comment]
@blizzz they're LDAP on win 2008. Pleas let me know if anything else is needed.

**Comment by PVince81** [comment]
@blizzz any update ?

**Comment by blizzz** [comment]
Well, LDAP configuration was missing. I think that was just configuration issues. If "LDAP Username" is clicked in the login filter, than samaccountname will be used against AD. 

> "app":"PHP","message":"ldap_start_tls(): Unable to start TLS: Connect error at 

Might indicate either SSL setup issues are or false-positively detected TLS availablity. That can be turned of using occ. 

I'd close it as config issue.

@bboule please reopen if you think it is necessary.
