### ISSUE TITLE
Missing local copies

### ISSUE THREAD

**Issue by alexpyattaev** [owncloud/core#15843]
With no reason whatsoever, owncloud client 1.8.0 on Suse linux decided it is a good idea to delete a directory, together with its contents. The only thing that I did is saved one of the files in the directory, causing an upload sync. This is how the log looked like:          
>4/23/15 7:45 innocent file 3           documents      Deleted                  
>4/23/15 7:45 PM innocent file 2                        documents      Deleted                  
>4/23/15 7:45 PM innocent file 1                      documents      Deleted                  
>4/23/15 7:45 PM.directory                                                      documents      Deleted                  
>4/23/15 7:39 PMuniver/antennas/paper/main.lyx                                  documents      Uploaded       12 KiB    
>4/23/15 7:38 PMuniver/antennas/paper/#main.lyx#                                documents      Uploaded       12 KiB    
>4/23/15 7:28 PMuniver/antennas/paper/#main.lyx#                                documents      Uploaded       11 KiB    
>4/23/15 7:23 PMuniver/antennas/paper/#main.lyx#                                documents      Uploaded       11 KiB    
As if nothing is happening!  By pure miracle I noticed that something fishy is happening and prevented the upload of changes to the server. 
There were no errors reported. Given how shitty my connection is right now, my first suspicion is race conditions somewhere in the sync code. Sadly, I can not provide much more info than that, but if bad links/terminated and timeouted sockets could be a problem they definitely are here in China thanks to the great firewall. 
This bug is not new at all, similar things have been noticed since 2012, please look at the race conditions/unhandled socket exceptions, maybe that is the key.

**Comment by karlitschek** [comment]
Sorry for the trouble.
Can you please open this in the client repository bug tracker?
@dragotin FYI
