### ISSUE TITLE
[enc2] Copy file into shared dir as recipient produces broken copy

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15840]
### Steps
1. Enable encryption + default encryption module
2. Create two users "user1" and "user2"
3. As "user1" share a folder "sub" with "user2"
4. Login as "user2" with cadaver
5. WebDAV PUT a file test.txt
6. WebDAV COPY test.txt into "sub/copy.txt"
7. In the Web UI login as "user2"
8. Open "sub/copy.txt"

### Expected result
Copy can be opened

### Actual result
Broken copy.

### Versions
ownCloud 8.1 git master (a672e9d5563998205923b3b388208bb4b8242048)

@schiesbn @th3fallen

**Comment by schiesbn** [comment]
I think this will be fixed with: https://github.com/owncloud/core/pull/15628 Can you give it a try? Thanks!

**Comment by PVince81** [comment]
Indeed, the PR https://github.com/owncloud/core/pull/15628 fixes this issue

**Comment by schiesbn** [comment]
fix merged
