### ISSUE TITLE
Feature Request:  Confirm deletion of user in Web Interface

### ISSUE THREAD

**Issue by jason-vivid** [owncloud/core#15849]
We had a user accidentally deleted recently while another user was intentionally being deleted.

There doesn't appear to be an undo and there was no request to confirm.  

Request this be added as a feature.

**Comment by RealRancor** [comment]
Hi,

this was rejected some time ago for the reasons posted here: https://github.com/owncloud/core/issues/14945#issuecomment-82387715

If you got no undo possibility then you might have found a bug which you should post in a separate issue while using the issue template like requested in the "guidelines for contributing" (linked in the yellow box when creating a new ussue)

**Comment by enoch85** [comment]
Also, all the files end up in trashbin. I think the standard is for 30 days before it gts deleted totally.

**Comment by MorrisJobke** [comment]
> Also, all the files end up in trashbin. I think the standard is for 30 days before it gets deleted totally.

This was about users and not about files ;)

**Comment by nickvergessen** [comment]
Closing as duplicate

**Comment by MorrisJobke** [comment]
@jason-vivid If the undo message doesn't come up this is definetely a bug and should be reported. Please use the issue template to report this. https://github.com/owncloud/core/blob/master/issue_template.md
