### ISSUE TITLE
Renaming Directory by Fixing Case Results in Non Working Directory

### ISSUE THREAD

**Issue by vseven** [owncloud/core#15841]
If you rename a directory by only changing the case of a letter the directory stops being usable for uploads.  IE rename  DOcuments to Documents and you no longer can upload into it, says directory doesn't exist which it actually does but has a -0 added to it in the file system.

### Steps to reproduce
1.  Create a directory and use the wrong case for a letter  (Doctors and phDs).  Folder on disk gets created such as "doctors-and-phds"
2.  Edit the directory name with the correct case   (Doctors and PHDs).  Folder on disk gets renamed to "doctors-and-phds-0"
3.  Database still points to original.  Uploads fail.  If you manually rename the folder and remove the -0 you can upload into it.  Deleting the directory and recreating it does not fix the issue.  Renaming to something completely different then back to the fixed case seems to work.

### Expected behaviour
Tell us what should happen
Directory name in storage shouldn't be renamed with the added -0 at the end.

### Actual behaviour
Tell us what happens instead
It gets a -0 added to the end

### Server configuration
**Operating system**:  Server 2012 R2
**Web server:**  IIS 8.5
**Database:**  mySQL
**PHP version:**  5.6
**ownCloud version:** (see ownCloud admin page)  7.0.5.2
**Updated from an older ownCloud or fresh install:**  fresh install
**List of activated apps:**  External Sites, LDAP, PDF Viewer, Share Files, Updater
**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'ocb0989e1ffb',
  'passwordsalt' => '*****',
  'secret' => '******',
  'trusted_domains' => 
  array (
    0 => 'Internal URL',
  ),
  'datadirectory' => 'C:\\OwnCloudData',
  'overwrite.cli.url' => 'http://Internal URL',
  'dbtype' => 'mysql',
  'version' => '7.0.5.2',
  'dbname' => 'ownclouddb',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_ocadmin',
  'dbpassword' => '**********',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'maxZipInputSize' => 500000000,
  'allowZipDownload' => false,
  'knowledgebaseenabled' => false,
  'allow_user_to_change_display_name' => false,
  'defaultapp' => 'files',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...  No

**Are you using encryption:** yes/no   No

### Client configuration
**Browser:**  Firefox, Chrome, and IE

**Operating system:**  Windows 7 SP1

#### ownCloud log (data/owncloud.log)
blank (empty)

**Comment by LukasReschke** [comment]
> Operating system: Server 2012 R2

This looks like a platform specific bug on the Windows file mapper. As you might know with ownCloud 8.1 we will not support the MS Windows Platform as a server anymore officially as nobody maintained it really, see https://owncloud.org/blog/owncloud-server-8-1-will-not-support-windows-as-server-platform-natively/

Sorry for the inconvenience that this caused and thanks a lot for your detailled bug report. You would be best of by migrating your instance to a Linux server.

**Comment by vseven** [comment]
Although I want to agree with you that it is a "windows" issue this bug affects both 6.* and 7.* versions of ownCloud but does not seem to affect other cloud type software.  For example I have Pydio running on the same server and if I try the same thing I will get a error message saying that files are case insensitive.  I can then rename the folder to "Doctors temp" and then back to "Doctors and PHDs" and the source does correctly update.  With ownCloud it does not, it stays stuck at "doctors-and-phDs-0" with the extra dash 0 at the end.  That's really whats messing things up is the addition of the space 0.

You can leave this closed as I understand not supporting this software under windows is a business decision you guys decided to make.  But attempting to correct the case of a folder should not make the folder unusable in ownCloud while in other software it still works.  That, to me,doesn't make it a windows problem.

**Comment by LukasReschke** [comment]
> But attempting to correct the case of a folder should not make the folder unusable in ownCloud while in other software it still works. That, to me,doesn't make it a windows problem.

It is because we use a custom file mapper on Windows which is buggy and thus results in this bug. Unless somebody volunteers to fix the file mapper stuff will be buggy ;-)

**Comment by LukasReschke** [comment]
(as in: We are not actively fixing bugs in code paths that only affects Windows Server)
