### ISSUE TITLE
Object classes in the user tab of the LDAP wizard get deselected

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#15859]
### Steps to reproduce
1. In assisted mode (in the user tab) select an object class
2. Click in "edit LDAP Query" to edit the filter manually (no need to edit the filter)
3. Click again in the "edit LDAP Query"
4. Select another object class keeping the object class in step 1 selected too

### Expected behaviour
The LDAP filter is updated with both object classes and both classes are selected in the multiselect

### Actual behaviour
The LDAP filter is updated but the multiselect remove all the selections. The filter will also be updated with the multiselect data later (after clicking in the LDAP filter?).

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 alpha 1

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by jvillafanez** [comment]
@blizzz

**Comment by jvillafanez** [comment]
Looks like this is also happening with the "other attributes" in the "login attributes" tab in the LDAP wizard

**Comment by jvillafanez** [comment]
object classes in the group tab is also affected

**Comment by blizzz** [comment]
@jvillafanez still happening?

**Comment by blizzz** [comment]
Cannot reproduce anymore, closing as fixed.
