### ISSUE TITLE
Cache issues testing connection in the LDAP wizard

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#15857]
### Steps to reproduce
1. With a disconnected LDAP server, setup a configuration in the server tab of the LDAP wizard targeting the disconnected LDAP server (all the configuration should be
2. Once the configuration is set, click in the "test base DN" button: a notification saying that there is no connection to the LDAP server should popup
3. Start the LDAP server
4. Click again in the "test base DN" button

### Expected behaviour
Success message should appear because the server is up and running now (and is properly configured to connect to the LDAP server)

### Actual behaviour
Error message is shown as if there isn't connection to the LDAP server

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** 8.1 alpha 1

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by jvillafanez** [comment]
@blizzz

**Comment by blizzz** [comment]
There is no caching involved in testing, as it's treated as a "on-the-fly" configuration. It would cause real trouble during configuration, too. Maybe you're LDAP server was not ready yet when you clicked, or you really have had an issue in your configuration?

**Comment by blizzz** [comment]
Closed for inactivity.
