### ISSUE TITLE
File and folder location is wrong at shared external folders

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#15858]
Originally reported at https://github.com/owncloud/activity/issues/284 by @tibmanus

> ### Steps to reproduce
1. Admin user mounts a local folder as an external storage. (Folder name: Localhhh)
2. Admin user creates a folder inside this folder (Folder name: external), then shares it with 'testuser'.
3. Testuser creates a file in this folder (Name: file1).
4. Testuser checks the Activity app: "You created file1"
>
> ### Expected behaviour
Tooltip and link shows the correct location for testuser: external/
>
> ### Actual behaviour
Tooltip and link for testuser goes to this location:   externalcalhhh/external
>
> ### Server configuration
**Operating system**:
Ubuntu 14.04
>
> **Web server:**
Apache2
>
> **Database:**
SQLite
>
> **ownCloud version:** (see ownCloud admin page)
8.02
>
> **Updated from an older ownCloud or fresh install:**
Happens both at fresh and updated version.
>
> **Are you using external storage, if yes which one:**
local
>
> **Are you using encryption:** 
no
>
> **Are you using an external user-backend, if yes which one:** 
no

[lib/private/share/share.php#L282-L288](https://github.com/owncloud/core/blob/1911472b88898868969bfbefa16e0e2e3168c146/lib/private/share/share.php#L282-L288)
```php
					while ($row = $result->fetchRow()) {
						foreach ($fileTargets[$row['fileid']] as $uid => $shareData) {
							$sharedPath = $shareData['file_target'];
							$sharedPath .= substr($path, strlen($row['path']) -5);
							$sharePaths[$uid] = $sharedPath;
						}
					}
```
This code generates broken paths. Instead of `$path` starting with `files/` it starts with the mount point name, so stripping should be until the next slash instead of hardcoded 5 characters?

**Comment by nickvergessen** [comment]
// cc @schiesbn @rullzer

**Comment by PVince81** [comment]
Is this OC 8.0 only ? Anything that can be backported from 8.1 ?

**Comment by nickvergessen** [comment]
No, I somehow was in the wrong milestone-setting-mind from other projects.

Affects both 8.1 and 8.0

**Comment by SergioBertolinSG** [comment]
Tested in last 8.1 version (2015-06-19). I can reproduce it.

**Comment by schiesbn** [comment]
> This code generates broken paths. Instead of $path starting with files/ it starts with the mount point name, so stripping should be until the next slash instead of hardcoded 5 characters?

Not sure if we want to strip away the mount point (btw. a mount point doesn't need to be in the root folder). I think what we want is the complete path relative to the files folder, right?

**Comment by nickvergessen** [comment]
What I want is the full path of the sharee, not the sharer. So yes we need to strip away the mount point name

**Comment by PVince81** [comment]
@schiesbn @nickvergessen @rullzer possibly still an issue in 8.2 beta ?

**Comment by nickvergessen** [comment]
Yes, still a verify annoying issue

changed the line numbers to match the new code position:
https://github.com/owncloud/core/blob/1911472b88898868969bfbefa16e0e2e3168c146/lib/private/share/share.php#L282-L288

**Comment by cmonteroluque** [comment]
This bug will fall off 8.2 if not resolved by 6 Oct

**Comment by schiesbn** [comment]
> What I want is the full path of the sharee, not the sharer. So yes we need to strip away the mount point name

I'm still not sure what's the right behavior here. If you want the full path we don't have to trip away the mount point but first get the complete path relative to /files and then strip away files/. Stripping away the mount point doesn't give you the full path but the relative path to the mount point.

**Comment by nickvergessen** [comment]
@icewind1991

**Comment by icewind1991** [comment]
Atm there is no need to do this without taking a horrible performance panalty, there are plans to add a table which would allow this (mount point for users table)
