### ISSUE TITLE
[stable8] Cannot PROPPATCH getlastmodified, getting 403

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15850]
On stable8 (and potentially older versions), doing a PROPPATCH on getlastmodified returns 403.
Not sure why.

On master it will properly set the property.

From what I understand the sync client does such PROPPATCH in case a PUT didn't accept the mtime. (@guruz @ogoffart)

#### Steps:
1. Use the following PROPPATCH file:
```

<?xml version="1.0"?>
<d:propertyupdate xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">
  <d:set>
    <d:prop>
        <d:getlastmodified>Mon, 19 Jan 2015 19:50:20 GMT</d:getlastmodified>
    </d:prop>
  </d:set>
</d:propertyupdate>
```
2. `curl -X PROPPATCH -H "Content-Type: text/xml" --data-binary "@proppatchx.txt" http://root:admin@localhost/owncloud/remote.php/webdav/welcome.txt`

### Expected
200 OK in XML response

### Actual
403 OK in XML response

### Versions
Observed on v8.0.2 (master is fine with the new Sabre).

**Comment by ogoffart** [comment]
> From what I understand the sync client does such PROPPATCH in case a PUT didn't accept the mtime.

Yes that's correct,   but PUT always accept the mtime with recent server.
The newest version of the client does not even do it anymore and if PUT does not support PROPPATCH, the mtime will be wrong.

**Comment by PVince81** [comment]
Yes, I also couldn't think of cases where the mtime would not be accepted.

Anyway, I think still it is legitimate to allow PROPPATCH on getlastmodified, so we might want to see why it doesn't work on OC 8.0

**Comment by ziotibia81** [comment]
I confirm this issue on 8.0.3

**Comment by ziotibia81** [comment]
There are a way to make it work on 8.0.4?

**Comment by PVince81** [comment]
I didn't have to look into this sorry... fully booked with upcoming 8.1 release.

If you feel adventurous you can try debugging the OC code, the location should be here https://github.com/owncloud/core/blob/stable8/lib/private/connector/sabre/node.php#L162

**Comment by ziotibia81** [comment]
Solved.... The problem is here:
https://github.com/owncloud/3rdparty/blob/stable8/sabre/dav/lib/Sabre/DAV/Server.php#L104

Removing this line matime is chaged. Listing file in DAV I can see correct mtime. In web view I still view time of upload.

**Comment by PVince81** [comment]
You need to make sure that it does not write the lastmodified property in the "oc_properties" table. I believe that was the reason for the protected properties.

If this works correctly, do you mind sending the change as a pull request ?

**Comment by ziotibia81** [comment]
I think that reason because this property is protected is RFC4918, where getlastmodified is readonly. Many Webdav servers breaks this rule and permit to use getlastmodified to set mtime, so it looks like to be a standard feature.

It seems to me we understand that L162 of node.php manage {DAV:}lastmodified to change mtime. 
In this case also node.php need to be fixed.

**Comment by ziotibia81** [comment]
I sent two PR:

https://github.com/owncloud/core/pull/17051
https://github.com/owncloud/3rdparty/pull/177

**Comment by ziotibia81** [comment]
@PVince81 Could you manage commit https://github.com/ziotibia81/3rdparty/commit/94efe7bad5e1081b24520ef7d22e98a752923c0d ? I'm not very skilled and I'm making too much hassle in GitHub.....

**Comment by MorrisJobke** [comment]
Solution is an upgrade to 8.1 see https://github.com/owncloud/core/pull/17051#issuecomment-113580990

**Comment by PVince81** [comment]
Looks like there was a misunderstanding. You need to proppatch "{DAV:}lastmodified" and not "{DAV:}getlastmodified". This will work in OC <= 8.0.

Since 8.1 you need to proppatch "getlastmodified", which is wrong, raised here: https://github.com/owncloud/core/issues/19737
