### ISSUE TITLE
Version expire bkg job cannot run on shared folders

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15852]
### Steps to reproduce
1. Create a user "user1"
2. Create a folder "folder"
3. Share "folder" with "user1"
4. Login as "user1"
5. Create a file "test.txt" in the root
6. Move "test.txt" into "folder"
7. Run cron on the CLI several times

### Expected result
No warnings

### Actual result
```
{"reqId":"mgRniCJD9\/Umu5ZsEL3y","remoteAddr":"","app":"files_sharing","message":"File source not found for: test.txt","level":0,"time":"2015-04-24T09:02:09+00:00","method":"--","url":"--"}
{"reqId":"mgRniCJD9\/Umu5ZsEL3y","remoteAddr":"","app":"files","message":" Backends provided no user object for ","level":3,"time":"2015-04-24T09:02:09+00:00","method":"--","url":"--"}
{"reqId":"mgRniCJD9\/Umu5ZsEL3y","remoteAddr":"","app":"no app in context","message":"Error while running background job: ","level":3,"time":"2015-04-24T09:02:09+00:00","method":"--","url":"--"}
```

### Versions
ownCloud 8.1 git master (33d197db29bcaded7b22c0d81e4e2f92004e9398)

**Comment by PVince81** [comment]
It's the versions expire command trying to expire on the old path:
```
0  OC_Share_Backend_File::getSource() /srv/www/htdocs/owncloud/apps/files_sharing/lib/share/file.php:228
1  OC\Files\Storage\Shared->getFile() /srv/www/htdocs/owncloud/apps/files_sharing/lib/sharedstorage.php:80
2  OC\Files\Storage\Shared->getOwner() /srv/www/htdocs/owncloud/apps/files_sharing/lib/sharedstorage.php:554
3  OC\Files\Storage\Wrapper\Wrapper->getOwner() /srv/www/htdocs/owncloud/lib/private/files/storage/wrapper/wrapper.php:414
4  OC\Files\View->basicOperation() /srv/www/htdocs/owncloud/lib/private/files/view.php:934
5  OC\Files\View->getOwner() /srv/www/htdocs/owncloud/lib/private/files/view.php:1389
6  OC\Files\Filesystem::getOwner() /srv/www/htdocs/owncloud/lib/private/files/filesystem.php:872
7  OCA\Files_Versions\Storage::getUidAndFilename() /srv/www/htdocs/owncloud/apps/files_versions/lib/storage.php:71
8  OCA\Files_Versions\Storage::expire() /srv/www/htdocs/owncloud/apps/files_versions/lib/storage.php:511
9  OCA\Files_Versions\Command\Expire->handle() /srv/www/htdocs/owncloud/apps/files_versions/command/expire.php:55
10 OC\Command\CommandJob->run() /srv/www/htdocs/owncloud/lib/private/command/commandjob.php:34
11 OC\BackgroundJob\Job->execute() /srv/www/htdocs/owncloud/lib/private/backgroundjob/job.php:51
12 OC\BackgroundJob\QueuedJob->execute() /srv/www/htdocs/owncloud/lib/private/backgroundjob/queuedjob.php:41
13 {main}          /srv/www/htdocs/owncloud/cron.php:130
```

Maybe before expiring the background job needs to check whether the file still exists where it is.

In the case where two files were swapped, there's a risk of running the background job on the wrong file... This might be a general issue with background jobs related to files @icewind1991 @DeepDiver1975 @schiesbn

**Comment by PVince81** [comment]
It looks like the version expiring job gets scheduled when moving the file, but maybe gets scheduled on the old path instead of the new one.

**Comment by PVince81** [comment]
Just debugged and it seems that it's worse than I thought.
Actually the expire job is properly configured to expire the new path, but as the path is in a shared folder (as recipient), it doesn't resolve properly to the final file.

I'll investigate further.

**Comment by PVince81** [comment]
Raised the "file name mix up" concern as separate ticket for discussion: https://github.com/owncloud/core/issues/15853

**Comment by PVince81** [comment]
Back to the problem: the background job cannot resolve the shares because there is no logged in user... so getOwner() and Share::getItems() will fail... Need to find a way to inject the current user because we certainly don't want to create a dummy session for that user...

**Comment by PVince81** [comment]
Had a chat with @LukasReschke and setting the user into IUserSession in the background job is a no go because there's a high risk of messing up the session in the ajax cron case. Even if we'd clean up by re-setting the correct user back, if an exception / error happens in the middle... then the wrong session would be used...

Let's have a look if the user can be injected/passed around... smells like major refactoring ahead...

**Comment by PVince81** [comment]
Looks like IUserSession has no user even in ajax cron mode, which is good because it would allow user mix ups otherwise.

**Comment by PVince81** [comment]
I had a look at the stack from https://github.com/owncloud/core/issues/15852#issuecomment-95860981, and the trickiest part would be to pass the user through the Storage class.

One idea would be to always pass the current user (the one from setupFS) through MountPoint/Storage $arguments and store it. Might be a risky fix to put in 8.1.

**Comment by PVince81** [comment]
We might be lucky, it looks like for the SharedStorage specifically we already inject the $user but don't use it. I'll prepare a PR.

**Comment by icewind1991** [comment]
> We might be lucky, it looks like for the SharedStorage specifically we already inject the $user but don't use it. I'll prepare a PR.

In the etag propagation PR the injected $user is used in some more places

**Comment by PVince81** [comment]
Cool...

I thought my PR was almost ready but it seems I bumped accross other parts of the code that depend on the currently logged in user... investigating...

**Comment by PVince81** [comment]
Okay... I'm finding more unrelated stuff, raised here https://github.com/owncloud/core/issues/15867

**Comment by PVince81** [comment]
PR is here: https://github.com/owncloud/core/pull/15868

**Comment by PVince81** [comment]
I retested this on master following up https://github.com/owncloud/core/pull/16337 that now expire files using the owner instead of recipient. The issue has disappeared and expiration is properly done with the owner user.

I will close this issue then.

However, let's keep the PR because it will make it possible to properly pass the user when expiring versions, which is better than relying on the currently logged in user.
