### ISSUE TITLE
Inject the current user instead of reading out of IUserSession

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15854]
There are many places in the code where the current user is read out of IUserSession or \OCP\User::getUser(). This is dangerous because it assumes that the currently logged in user is also the one we are working on.

In the case of background jobs (versions expire, etc), there is no user in the session, but we still need to apply changes for a given user.  (see https://github.com/owncloud/core/issues/15852)

This is why we need to always inject the $user instead of getting the one from the session.

CC @LukasReschke

**Comment by nickvergessen** [comment]
Well that should be nothing to discuss really, that is exactly what DI is for and what makes it easier then static code. If you fix one method, but can't fix it everywhere in one go, just inject it in the most outer method and call this one with `User::getUser()`, the next one will remove an additional depth, etc.

**Comment by PVince81** [comment]
Agreed, closing
