### ISSUE TITLE
Does openLDAP support "memberof"?

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#15864]
Having an openLDAP server with the default configuration, and configured with the wizard, in the "users" tab the "only from these groups" select is disabled. Due to this, we won't be able to test some cases properly with openLDAP.

How can we handle this? Any configuration we could use to make this active?

@blizzz @jnfrmarks

**Comment by blizzz** [comment]
That's written in the OpenLDAP Adminstration manual: http://www.openldap.org/doc/admin24/overlays.html

And here a simple example on ubuntu 12.04: http://www.schenkels.nl/2013/03/how-to-setup-openldap-with-memberof-overlay-ubuntu-12-04/

**Comment by jnfrmarks** [comment]
@jvillafanez @blizzz 

Can we close this?

**Comment by jvillafanez** [comment]
Sure!
