### ISSUE TITLE
Group selection broken in the LDAP wizard, group tab

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#15866]
### Steps to reproduce
1. Setup an LDAP server with more than 40 groups
2. Go to the groups tab in the LDAP wizard. You should see two list of groups below the "only from these groups" (the right one might be empty)
3. Select one of them and click in the ">" button

### Expected behaviour
The group is properly moved to the list

### Actual behaviour
A new item is added in the list per each character in the group name. The screenshot shows the state after moving the groups a bit from one list to another

![screenshot from 2015-04-24 15 14 15](https://cloud.githubusercontent.com/assets/1477829/7319277/9f327990-ea94-11e4-8a09-4e7f1d82655e.png)

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** 8.1 alpha 1

**Updated from an older ownCloud or fresh install:** fresh install

### Notes
To be checked if this also happens in the user tab

**Comment by jvillafanez** [comment]
@blizzz

**Comment by blizzz** [comment]
yup, will take care

**Comment by davitol** [comment]
:+1:  Fixed
