### ISSUE TITLE
expired shared links don't update UI

### ISSUE THREAD

**Issue by tlhonmey** [owncloud/core#15871]
If you share a folder via a link, and then share files inside that folder individually via links with expiration dates, the shared icons for the individual files do not update when the link expires (id est:  they continue to show the files as shared via link.)  Clicking the share icon shows that the share parameters are blank, however and subsequent refreshes of the page will then show the file with its correct shared status.

This appears to also be the case if you have not shared the parent folder via a link.  The difference is that if the parent folder is not shared, clicking the "Shared By Link" filter can be used to mass-update the expired files.  If a parent folder is shared via a link, however, the "Shared By Link" filter appears to have no effect.

I don't have time to test this as thoroughly as I would normally like before filing a bug report, but I don't want it to get forgotten.  If it doesn't repro easily let me know and I'll throw it on my stack of spare-time projects to figure out precisely what's going on.

**Comment by PVince81** [comment]
The reason for this is because the expiration is done on-demand, which means the expiration logic only runs the next time the file is accessed or the share info is requested directly like when you open the dropdown.

I do agree that it might be confusing for a user's point of view.

One possible fix would be to provide a cron job / background job that runs once a day and iterates over all the shares and then auto-expires them. And this would be additionally to the on-demand expire.

@schiesbn @rullzer @butonic what do you think ?

**Comment by PVince81** [comment]
Another idea would be to auto-expire whenever we do a SELECT on the shares, for example when displaying the icons in the web UI. But that approach could make the UI / WebDAV slower. So I think the background job approach might be nicer.

**Comment by nickvergessen** [comment]
Or we also expire the share when the dropdown is opened, so it "refreshes" the information?

**Comment by PVince81** [comment]
There is a JS-side cache that contains all the shares, that cache could be updated, yes.
But the basic UX issue is probably that the user still thinks the file is shared before opening the dropdown.

**Comment by tlhonmey** [comment]
That was my primary concern, at least.  It's hard to go through and clean out files that are no longer shared if you can't see that they're being shared.

**Comment by PVince81** [comment]
Let's have a look at this for 8.2

**Comment by jancborchardt** [comment]
It should definitely expire them not only as soon as the file is interacted with. A background job sounds like a good solution indeed.

**Comment by rullzer** [comment]
Moving to 9.0

**Comment by rullzer** [comment]
PR started in #19636
