### ISSUE TITLE
When occ had an error, move back the files

### ISSUE THREAD

**Issue by binarykitchen** [owncloud/core#15877]
Each time when the `occ` command errored, it would be nice to move back all the files it has moved. This should be a pure transaction with a rollback mechanism.

For example I have to restore `./data/public-keys/` and `./data/owncloud_private_key/` everytime.

**Comment by PVince81** [comment]
@schiesbn @th3fallen @DeepDiver1975 

@binarykitchen you probably mean something like a command to restore backup keys

**Comment by binarykitchen** [comment]
absolutely @PVince81 and the whole occ thing must be transaction-oriented. a backup procedure always should come with restore functionality.

**Comment by th3fallen** [comment]
i agree completely with the transaction based backup, but how its done now is the entire encryption folder with all keys is moved to files_encryption_backup_{date} which should make things easier

**Comment by PVince81** [comment]
This is an old migration routine and I doubt we'll want to invest more time into this obsolete code.
