### ISSUE TITLE
Allowed memory size of ... bytes exhausted

### ISSUE THREAD

**Issue by binarykitchen** [owncloud/core#15876]
I ran the `occ` command three days ago and let it run without interruptions for a huge migration of 30 GB of encrypted data from v7 to v8. Then I got this error:

```
$ sudo -u www-data php occ upgrade -vvv
[sudo] password for xxx: 
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
PHP Fatal error:  Allowed memory size of 100663296 bytes exhausted (tried to allocate 250 bytes) in /var/www/owncloud/lib/private/files/filesystem.php on line 779
```

In the log file I spotted this:

```
{"reqId":"aae5165b23e49d301be174230b0fbd92","remoteAddr":"","app":"core","message":"unable to rename, file does not exists : files_encryption\/xxx.private.key","level":3,"time":"2015-04-26T16:42:18+00:00"}
```

But I had the private key in that directory before I started the `occ` process. Confused.

**Comment by binarykitchen** [comment]
By the way, `files_encryption\/xxx.private.key` does exist in my filesystem but a couple of things are not clear:
- The full path is missing
- Was it a permission issue?
- Why does the log not print where exactly in the code the error has been thrown?

**Comment by RealRancor** [comment]
Hi,

you have a memory limit for the php-cli of 96MB which is far too low. Try to increase it to something like 512MB.

Ref. https://github.com/owncloud/core/issues/12855

**Comment by binarykitchen** [comment]
@RealRancor okay, i will raise the limit and try again with the `occ` command. But what about the other issue with the private key? Should I raise a separate ticket for that?

**Comment by RealRancor** [comment]
I think the message is caused because the upgrade is migrating / rewriting the encryption keys during this process.

**Comment by binarykitchen** [comment]
Okay, see how it goes this time.

**Comment by MorrisJobke** [comment]
> you have a memory limit for the php-cli of 96MB which is far too low. Try to increase it to something like 512MB.

@DeepDiver1975 @LukasReschke Does it make sense to check for a memory limit of at least 512 MB for a CLI run? Otherwise these issues will pop up over time again.

**Comment by LukasReschke** [comment]
> @DeepDiver1975 @LukasReschke Does it make sense to check for a memory limit of at least 512 MB for a CLI run? Otherwise these issues will pop up over time again.

Can't judge on this. Sorry. – Personal feeling: Yes. If we can enforce that: Not sure ;-)

**Comment by MorrisJobke** [comment]
> Can't judge on this. Sorry. – Personal feeling: Yes. If we can enforce that: Not sure ;-)

Maybe just add a notice and make it then a warning you can skip. Nothing to enforce, but to warn the user before any corruption happens.

**Comment by binarykitchen** [comment]
Exactly, a check and a warning afterwards would have been extremely useful! Believe me, I already have wasted hours for this.

**Comment by karlitschek** [comment]
hmmm. wh does it need so much memory? maybe we have to make sure that it doesn't leak memiry before we require a higher memeory limit

**Comment by RealRancor** [comment]
Is 96MB that much memory for migrating 30GB of encrypted data?

**Comment by karlitschek** [comment]
honstly yes. should be enough the migrate the keys

**Comment by binarykitchen** [comment]
correction, i have 40 GB encrypted data. and yes, i suspect a memory leak too.

the `occ` command at high verbosity should print memory usage every 15 min or so, this as an observation. plus i think PHP is able to add a memory hook saying i.E. when usage has reached 95%, print a memory dump. like that you can see the bad variables which are never unset.

**Comment by binarykitchen** [comment]
i ran the `occ` command again three days ago and today the ssh connection got aborted. grrrr...

rolling back all the files manually and trying again, but this time with a tmux session. you have no idea how painful this is. trying for weeks to migrate :(

**Comment by binarykitchen** [comment]
ah, finally have migrated everything, this after one month of hassles ...

but really, there should be more warnings and the rollback mechanism is missing.
