### ISSUE TITLE
Owncloud does not remember my trusted domain

### ISSUE THREAD

**Issue by coryulrich** [owncloud/core#15873]
Hello all, I'm trying to use owncloud with my domain name. I've got the forwarding working perfectly, except every time I try to reach my owncloud by name it asks me to add the trusted domain and I do. I checked the config.php and it has added www.mydomain.com several times. I can't get owncloud to realize it's already added my domain as trusted. For good measure I changed the permissions to 755 to guarantee it was able to read to the file, even if it could obviously write to it. 

I installed it in a freenas jail, but that's probably irrelevant for the most part.

**Comment by LukasReschke** [comment]
Thanks a lot for reporting issues back to us!

We need some more information to properly support you with your issue.

Can I ask you to follow our guidelines for submitting bugs as described here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by PVince81** [comment]
Closing due to lack of feedback. See previous comment.
