### ISSUE TITLE
Web uploader chokes on apostrophes

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#15874]
### Env
FreeBSD - PHP-FPM 5.5 - Apache

### Steps to reproduce
1. Name a JPG "l'émotion.jpg"
2. Drop it on the web interface

### Expected behaviour
The file gets uploaded and a nice thumbnail shows up in the list of files

### Actual behaviour
Kaboom - Bad request - Error 400

If you remove the apostrophe, it will upload just fine

The problem probably comes from
`Content-Disposition: form-data; name="files[]"; filename="l'Ã©motion.jpg"`

### Logs
Nothing

**Comment by PVince81** [comment]
Works for me. Uploading this file through web UI works and downloading it from there again works too.

Could be specific to your environment ?

I have this:
apache2-2.4.12-2.1.x86_64
php5-5.6.7-1.1.x86_64
mariadb-10.0.14-2.3.x86_64

and use mod_php.

**Comment by PVince81** [comment]
forgot to mention that I tested this on master 802f818c2770b8b52d050e8fbc7562295f995445

**Comment by nickvergessen** [comment]
@oparoz can you make sure you have php-intl installed?

**Comment by oparoz** [comment]
I've updated the OP, but I've tested with another application on the same server and it also refused the file, so it must have something to do with my PHP setup.

php-intl is installed as a PECL extension.

**Comment by oparoz** [comment]
Happens to lots of users on Wordpress as well
https://core.trac.wordpress.org/ticket/22694

**Comment by oparoz** [comment]
It's mod_security complaining about a problem with the POST data. I should have checked that first...
`Multipart request body failed strict validation: PE 0, BQ 0, BW 0, DB 0, DA 0, HF 0, LF 0, SM 0, IQ 1, IP 0, IH 0, FL 0`

Apostrophes are used in scripts and modsec thinks it's an attack.
