### ISSUE TITLE
Allow apps to register Sabre plugins

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15879]
We should look into allowing apps to register their own Sabre plugins.
This would make it possible for apps to provide additional properties.

@DeepDiver1975 if I remember well you were against this approach ?

If the use case is only about additional properties, then maybe we could use another API/approach to let apps register their properties/listeners in an ownCloud way (not Sabre plugin) and then have a special Sabre plugin to connect them to remote.php.

CC @icewind1991

**Comment by PVince81** [comment]
@DeepDiver1975 obsolete ?

**Comment by DeepDiver1975** [comment]
I think so - we are going to have one dav entrypoint starting from 9.0 on

**Comment by DeepDiver1975** [comment]
I would not allow wild injection of plugins since this could break sync of files, calendars and address books
