### ISSUE TITLE
Error upgrading from 7.0.4 to 8.0.2

### ISSUE THREAD

**Issue by SierraBMWCCA** [owncloud/core#15872]
![image](https://cloud.githubusercontent.com/assets/12112048/7333061/37117084-eb2d-11e4-8f91-5031db09f0db.png)

Please Help...
In trying to upgrade I received the following error:
An exception occurred while executing 'CREATE TABLE oc_ownc_appconfig_yevmylckttaim (`appid` VARCHAR(32) DEFAULT '' NOT NULL, `configkey` VARCHAR(64) DEFAULT '' NOT NULL, `configvalue` LONGTEXT DEFAULT NULL, INDEX oc_k3avh7elcltrq (`configkey`), INDEX oc_5ymhx0yjojfwb (`appid`), PRIMARY KEY(`appid`, `configkey`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_ownc_appconfig_yevmylckttaim' already exists

And stated
"The update was unsuccessful. Please report this issue to the ownCloud community."

Now my installation is stuck on this screen:
![image](https://cloud.githubusercontent.com/assets/12112048/7333076/ea8e21e8-eb2d-11e4-95cf-c54ee99cd465.png)

I will try to restore from my backup and wait for your advice

Thanks

**Comment by RealRancor** [comment]
Very likely a dup of:  https://github.com/owncloud/core/issues/14916 and/or https://github.com/owncloud/core/issues/14242

**Comment by SierraBMWCCA** [comment]
Thanks, I had tried to search the error and found nothing. I'll take a look at these.

**Comment by SierraBMWCCA** [comment]
I read them but didn't seem to solve my problem. 

Carol 🏁

**Comment by RealRancor** [comment]
https://github.com/owncloud/core/issues/14916 is still open so you can subscribe to it to see if there is a solution provided there.
