### ISSUE TITLE
Debian 8.0 Repository

### ISSUE THREAD

**Issue by lordfolken** [owncloud/core#15889]
Hi, 

Slowly Debian 8.0 comes into view. Would it be possible to instruct the build server to generate Packages for Debian 8.0?

**Comment by LukasReschke** [comment]
cc @jnweiger

**Comment by DeepDiver1975** [comment]
This will be possible after release of Debian 8. OBS will prepare Debian 8 images after that. Not much we can do for now.

In addition Debian 8 will contain Debian 8.0 afaik.

**Comment by LukasReschke** [comment]
> This will be possible after release of Debian 8. OBS will prepare Debian 8 images after that. Not much we can do for now.

Shouldn't that be possible already? – At least what I understood from @jospoortvliet on https://twitter.com/jospoortvliet/status/591585222828883968

**Comment by DeepDiver1975** [comment]
> Shouldn't that be possible already?

ah - nice - I missed that part

**Comment by DeepDiver1975** [comment]
@jnweiger GOGOGO

**Comment by jnweiger** [comment]
This is how it looked in OBS until today:

xUbuntu_15.04 succeeds nicely.
Debian_8.0 bailed out with an error: have choice for sysv-rc | file-rc needed by initscripts: openrc sysv-rc

I've crafted a workaround. Now it builds here:
https://build.opensuse.org/package/show/isv:ownCloud:community:8.0/owncloud

**Comment by DeepDiver1975** [comment]
case closed then from my understanding - THX @jnweiger

**Comment by jnweiger** [comment]
@DeepDiver1975 has faith in first time builds :-)

**Comment by jnweiger** [comment]
Workaround discussed with Adrian. Fixed at SUSE now.
