### ISSUE TITLE
Can't use function return value in write context

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#15885]
```
PHP Fatal error:  Can't use function return value in write context in ./settings/admin.php on line 127
Fatal error: Can't use function return value in write context in ./settings/admin.php on line 127
Errors parsing ./settings/admin.php
```

![empty-getenv-path](https://cloud.githubusercontent.com/assets/213943/7347479/5a5b38be-ece9-11e4-8979-0b148e27feb0.png)

Caused by https://github.com/owncloud/core/pull/15617

Slapping @Xenopathic and @DeepDiver1975 as reviewers.

Will fix in a bit

**Comment by LukasReschke** [comment]
We should really add the PHPStorm Incompatibility scanner before the release, see https://github.com/owncloud/core/issues/15463#issuecomment-90890905 – should get added to some kind of release checklist.

cc @DeepDiver1975 @karlitschek

**Comment by nickvergessen** [comment]
I found this by defining a wrong path on the activity app, which runs
```bash
sh -c "if [ '$CODECHECK' = '1' ]; then find . -name \*.php -exec php -l \"{}\" \;; fi"
```
