### ISSUE TITLE
login failed LDAP user owncloud 8.0.2.0 LDAp user not authenticated

### ISSUE THREAD

**Issue by kumarsanjeet101** [owncloud/core#15898]
{"reqId":"44a20f33cb3eb11447b6ba2b1e1caaea","remoteAddr":"172.16.10.57","app":"core","message":"Login failed: 'sanjeetk' (Remote IP: '172.16.10.57', X-Forwarded-For: '')","level":2,"time":"2015-04-27T16:40:08+00:00"}
{"reqId":"bab790a35282f748da35455fcd200374","remoteAddr":"172.16.10.57","app":"PHP","message":"Only variables should be passed by reference at \/var\/www\/html\/domaincloud\/lib\/private\/cache\/fileglobalgc.php#50","level":3,"time":"2015-04-27T16:40:08+00:00"}
{"reqId":"bab790a35282f748da35455fcd200374","remoteAddr":"172.16.10.57","app":"PHP","message":"unlink() expects parameter 2 to be resource, integer given at \/var\/www\/html\/domaincloud\/lib\/private\/cache\/fileglobalgc.php#50","level":3,"time":"2015-04-27T16:40:08+00:00"}

how can i resolve the issue please send me the solution.

**Comment by kumarsanjeet101** [comment]
LDAP://pdc.domain.com  port ###
CN=domainclouduser,CN=Users,DC=domain,DC=com
pwd:#########
DC=domain,DC=com

userfilter
(&(|(objectclass=user))(|(memberof=CN=domainCloud,CN=Users,DC=domain,DC=com)))

loginfilter
(&(&(|(objectclass=user))(|(memberof=CN=domainCloud,CN=Users,DC=domain,DC=com)))(|(samaccountname=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))(|(displayName=%uid))))

groupfilter
.....(blank)

directory settings
User Display Name Field : displayname
Base User Tree : DC=domain,DC=com
Group Display Name Field : cn
Base Group Tree : DC=domain,DC=com
Group-Member association : uniquemember

**Comment by LukasReschke** [comment]
Thanks a lot for reporting issues back to us!

We need some more information to properly support you with your issue!

Can I ask you to follow our guidelines for submitting bugs as described here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by kumarsanjeet101** [comment]
@LukasReschke 

no any commit found and code changes from your end can u describe brefilly in details. thanku before please describe the problem and solutions.

**Comment by LukasReschke** [comment]
Can you elaborate please? – I have troubles trying to understand your actual issue. Without the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) we miss important information to debug this and help you.

**Comment by kumarsanjeet101** [comment]
@LukasReschke 
i have installed successfully and admin user logged in succesfully into the application. and i was configure with 1000 user of ldap but no anyone user logged in into application message forgot your password reset it! but username and password is correct. 
In owncloud.log file 
Login failed: 'aman' (Remote IP: '172.16.10.57', X-Forwarded-For: '')","level":2,"time":"2015-04-27T16:40:08+00:00"}

**Comment by LukasReschke** [comment]
@blizzz

**Comment by kumarsanjeet101** [comment]
@blizzz 
@LukasReschke 
 the below mention is my basic configuration settings and list of everyone user list all LDAP user. admin user succesfully login into application but LDAP user not login with error message forgot passord reset it!.
So, please solve the issue version 8.0.2.0 and 
$users = $this->access->fetchListOfUsers($filter, $attrs); users array blank.
LDAP://pdc.domain.com port ###
CN=domainclouduser,CN=Users,DC=domain,DC=com
pwd:#########
DC=domain,DC=com

userfilter
(&(|(objectclass=user))(|(memberof=CN=domainCloud,CN=Users,DC=domain,DC=com)))

loginfilter
(&(&(|(objectclass=user))(|(memberof=CN=domainCloud,CN=Users,DC=domain,DC=com)))(|(samaccountname=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))(|(displayName=%uid))))

groupfilter
.....(blank)

directory settings
User Display Name Field : displayname
Base User Tree : DC=domain,DC=com
Group Display Name Field : cn
Base Group Tree : DC=domain,DC=com
Group-Member association : uniquemember

**Comment by blizzz** [comment]
Do your users have a displayname set on AD site? Otherwise, change display name attribute in the advanced settings to cn.

**Comment by kumarsanjeet101** [comment]
User Display Name Field : cn
Base User Tree : DC=chetu,DC=com
User Search Attributes : 
Group Display Name Field : cn
Base Group Tree : DC=chetu,DC=com
Group Search Attributes
Group-Member association : uniqqueMember
Nested Groups
Paging chunksize

i will use these settings but can't get solution can you help me on this user listed on everyone tab and list all users.

**Comment by kumarsanjeet101** [comment]
@blizzz 
@LukasReschke 

User Display Name Field : cn
Base User Tree : DC=chetu,DC=com
User Search Attributes : 
Group Display Name Field : cn
Base Group Tree : DC=chetu,DC=com
Group Search Attributes
Group-Member association : uniqqueMember
Nested Groups
Paging chunksize

i will use these settings but can't get solution can you help me on this user listed on everyone tab and list all users.

**Comment by SPCnet** [comment]
We have just installed ownCloud 8.0.3 (stable) and configured the ldap authentication with a Active Directory Win 2008R2.

The Owncloud server is a CentOS release 6.6 (Final) with php5.4

When login, this error is displayed:

{"reqId":"48153d1c3681ed0a5d5ca09cb31f7ffe","remoteAddr":"172.20.10.11","app":"core","message":"Login failed: 'spcnet' (Remote IP: '172.20.10.11', X-Forwarded-For: '')","level":2,"time":"2015-05-20T08:58:15+00:00"}

+------------------------------+---------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport     | 1                                                                                                 |
| hasPagedResultSupport        |                                                                                                   |
| homeFolderNamingRule         |                                                                                                   |
| lastJpegPhotoLookup          | 0                                                                                                 |
| ldapAgentName                | CN=SPCnet,OU=Users Externos,DC=hoteles-silken,DC=com                                              |
| ldapAgentPassword            | ***                                                                                               |
| ldapAttributesForGroupSearch |                                                                                                   |
| ldapAttributesForUserSearch  |                                                                                                   |
| ldapBackupHost               |                                                                                                   |
| ldapBackupPort               |                                                                                                   |
| ldapBase                     | DC=hoteles-silken,DC=com                                                                          |
| ldapBaseGroups               | DC=hoteles-silken,DC=com                                                                          |
| ldapBaseUsers                | DC=hoteles-silken,DC=com                                                                          |
| ldapCacheTTL                 | 600                                                                                               |
| ldapConfigurationActive      | 1                                                                                                 |
| ldapEmailAttribute           | mail                                                                                              |
| ldapExperiencedAdmin         | 0                                                                                                 |
| ldapExpertUUIDGroupAttr      |                                                                                                   |
| ldapExpertUUIDUserAttr       |                                                                                                   |
| ldapExpertUsernameAttr       | samaccountname                                                                                    |
| ldapGroupDisplayName         | cn                                                                                                |
| ldapGroupFilter              | (&(|(objectclass=group))(|(cn=Departamento IT)(cn=IT Externos)))                                  |
| ldapGroupFilterGroups        | IT Externos                                                                                       |
| ldapGroupFilterMode          | 1                                                                                                 |
| ldapGroupFilterObjectclass   | group                                                                                             |
| ldapGroupMemberAssocAttr     | member                                                                                            |
| ldapHost                     | 172.16.156.8                                                                                      |
| ldapIgnoreNamingRules        |                                                                                                   |
| ldapLoginFilter              | (sAMAccountName=%uid)                                                                             |
| ldapLoginFilterAttributes    |                                                                                                   |
| ldapLoginFilterEmail         | 0                                                                                                 |
| ldapLoginFilterMode          | 1                                                                                                 |
| ldapLoginFilterUsername      | 0                                                                                                 |
| ldapNestedGroups             | 0                                                                                                 |
| ldapNoCase                   | 1                                                                                                 |
| ldapOverrideMainServer       | 0                                                                                                 |
| ldapPagingSize               | 500                                                                                               |
| ldapPort                     | 389                                                                                               |
| ldapQuotaAttribute           |                                                                                                   |
| ldapQuotaDefault             |                                                                                                   |
| ldapTLS                      | 0                                                                                                 |
| ldapUserDisplayName          | cn                                                                                                |
| ldapUserFilter               | (&(|(objectclass=person))(|(memberof=CN=IT Externos,OU=Users Externos,DC=hoteles-silken,DC=com))) |
| ldapUserFilterGroups         | IT Externos                                                                                       |
| ldapUserFilterMode           | 1                                                                                                 |
| ldapUserFilterObjectclass    | person                                                                                            |
| ldapUuidGroupAttribute       | auto                                                                                              |
| ldapUuidUserAttribute        | auto                                                                                              |
| turnOffCertCheck             | 1                                                                                                 |
+------------------------------+---------------------------------------------------------------------------------------------------+


In the User tab, all LDAP users are displayed, but anyone can login with their AD credentiales.

**Comment by blizzz** [comment]
Does the issue still exist?

**Comment by blizzz** [comment]
Closed for inactivity.

**Comment by neo13476** [comment]
Hi there,

we do have the same Error Message as seen below.

We use Owncloud on our server for about one year and everything works fine, but now I can login into the Website of my server and a user is not able to use the software client.

My personal user is connected with my sever from different devices. (Window 10 and Fedora Destkop)
But when I try to connect via web interface or with my android smartphone I've got the same Error.

The Owncloud server is a CentOS release 6 with Owncloud 8.2.

Is there any known solution?

Thanks you in advance

Regards
Tobias
