### ISSUE TITLE
WebDAV docker instance for autotest-external

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15897]
Provide a docker instance / test config for regular WebDAV servers.

This is important because some code paths need to fall back whenever the remote WebDAV server isn't ownCloud, for example when requesting etags or mtimes.

CC @MorrisJobke

**Comment by PVince81** [comment]
@MorrisJobke I see you already prepared something here https://registry.hub.docker.com/u/morrisjobke/webdav/ :smile:

**Comment by MorrisJobke** [comment]
> @MorrisJobke I see you already prepared something here https://registry.hub.docker.com/u/morrisjobke/webdav/ :smile:

Yes. And it worked like this: :bomb: :boom: :boom:

**Comment by DeepDiver1975** [comment]
This is already live on jenkins.

**Comment by PVince81** [comment]
@DeepDiver1975 really ? Maybe you meant the ownCloud external storage test, not the WebDAV one. There is no start script for the pure WebDAV one.

**Comment by MorrisJobke** [comment]
The webdav tests only work with ownCloud as webdav endpoint. Not with any other webdav endpoint ...:(

**Comment by DeepDiver1975** [comment]
https://ci.owncloud.org/job/server-master-linux-externals/

you are right ... too much things going on here ...

**Comment by PVince81** [comment]
I got it running, will submit a PR

**Comment by PVince81** [comment]
PR here to introduce the docker instance: https://github.com/owncloud/core/pull/16688

**Comment by cmonteroluque** [comment]
@PVince81 really old PR. Can this be closed soon?

**Comment by PVince81** [comment]
Only if I find some time to fix the last mysteriously failing test: https://github.com/owncloud/core/pull/16688#issuecomment-136685297

**Comment by PVince81** [comment]
Tried moving the PR forward but once again there are complications... hope to be able to fix them in 9.1
