### ISSUE TITLE
Don't get users from LDAP Server (no-tls)

### ISSUE THREAD

**Issue by Hoper** [owncloud/core#15907]
I have the owncloud server v7 with config user from LDAP - ok
But when I try to config LDAP owncloud v8 - I don't get  users from LDAP
LDAP server log:

============================
Apr 28 11:22:07 ldap-v3 slapd[1630]: conn=29094 fd=39 ACCEPT from IP=192.168.1.1:40747 (IP=0.0.0.0:389)
Apr 28 11:22:07 ldap-v3 slapd[1630]: conn=29094 op=0 EXT oid=1.3.6.1.4.1.1466.20037
Apr 28 11:22:07 ldap-v3 slapd[1630]: conn=29094 op=0 STARTTLS
Apr 28 11:22:07 ldap-v3 slapd[1630]: conn=29094 op=0 RESULT oid= err=0 text=
Apr 28 11:22:07 ldap-v3 slapd[1630]: conn=29094 fd=39 TLS established tls_ssf=128 ssf=128
Apr 28 11:22:07 ldap-v3 slapd[1630]: conn=29094 fd=39 closed (connection lost)
Apr 28 11:22:07 ldap-v3 slapd[1630]: conn=29095 fd=39 ACCEPT from IP=192.168.1.1:40748 (IP=0.0.0.0:389)
Apr 28 11:22:07 ldap-v3 slapd[1630]: conn=29095 op=0 EXT oid=1.3.6.1.4.1.1466.20037
Apr 28 11:22:07 ldap-v3 slapd[1630]: conn=29095 op=0 STARTTLS
Apr 28 11:22:07 ldap-v3 slapd[1630]: conn=29095 op=0 RESULT oid= err=0 text=
Apr 28 11:22:07 ldap-v3 slapd[1630]: conn=29095 fd=39 TLS established tls_ssf=128 ssf=128
Apr 28 11:22:07 ldap-v3 slapd[1630]: conn=29095 fd=39 closed (connection lost)

============================
!!!TLS 
On web-admin I can't find config TSL
Only change the mysql table (oc_appconfig) ldap_tls 1 -> 0
After this owncloud server get the users from LDAP.

**Comment by DeepDiver1975** [comment]
@blizzz please have a look - THX

**Comment by blizzz** [comment]
On command line, use ldap:show-config  to see your configuration. If ldapTLS is set to 1, change it to 0 using the ldap:set-config commands. For the LDAP command line commands please see:

https://doc.owncloud.org/server/8.0/admin_manual/configuration_server/occ_command.html#ldap-commands

Why did it happen? ownCloud detected is as false positive. What LDAP server are you using and on which OS is ownCloud running?

**Comment by Hoper** [comment]
OwnCloud 8.0 on server Ubuntu 14.04 
LDAP server - Ubuntu 12.04 - LDAPv3 (from pkg iRedMail http://iredmail.com) 

 ============= 
I setup a plugin "LDAP user and group backend 0.5.0" and I configure LDAP server in a webadmin panel OwnCloud. But I a can't connect to the LDAP server if the mysql table (oc_appconfig) ldap_tls = 1

**Comment by blizzz** [comment]
Did you set it to  0 as suggested?

**Comment by MorrisJobke** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [latest stable version](http://owncloud.org/install/) and then please use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md). You can also contribute directly by providing a patch – see the [developer manual](http://doc.owncloud.org/server/9.0/developer_manual/). :)

Thank you!
