### ISSUE TITLE
Set the Website of this GitHub repo to http://owncloud.org

### ISSUE THREAD

**Issue by dandv** [owncloud/core#15900]
Example:

[![Adding GitHub repo URL](https://cloud.githubusercontent.com/assets/33569/6536430/76a7d88e-c402-11e4-8883-6ab2c7b8c30a.png)](https://github.com/dandv/meteor-webix)

**Comment by PVince81** [comment]
@karlitschek @DeepDiver1975

**Comment by DeepDiver1975** [comment]
fixed
