### ISSUE TITLE
Unable to list files/folders using Http/WebDAV client for php

### ISSUE THREAD

**Issue by conxdev** [owncloud/core#15902]
Although the PROPFIND request returns the correct xml from the terminal we are unable to access any files/folders using the PROPFIND verb from the WebDAV client by sabre. (http://sabre.io/dav/davclient/)

Have also tried it using guzzle, but getting the same response object.

Code

        $settings = array(
            'baseUri' => $url,
            'userName' => $username,
            'password' => $password,
            );

        $client = new SabreClient($settings);
        $response = $client->propfind($url, array(
            '{DAV:}displayname',
            '{DAV:}getcontentlength',
            ));

The response is,

    Array
    (
        [{http://owncloud.org/ns}id] => 00000055oc7kjmpoe4t8
        [{http://owncloud.org/ns}permissions] => RDNVCK
        [{http://owncloud.org/ns}size] => 2754651
    )

Server configuration:
CentOS 6.6 (Final)
nginx 1.6.2
PHP 5.5.23
ownCloud version 8.0.2

If you need any more information, please leave a comment below. Thanks.

**Comment by PVince81** [comment]
@conxdev can you try with another client like cadaver and see if WebDAV is configured properly on your server ? Does the sync client work ?

ownCloud is using Sabre's davclient to mount server to server shares (federation) and also ownCloud as external storage, so it should work.

**Comment by PVince81** [comment]
also what do you mean with "unable to access any folder" ? What response are you getting when doing a PROPFIND on those folders ? 404 ?

**Comment by conxdev** [comment]
@PVince81 not a 404, but a multi status response with Guzzle and the one I have pasted using sabre davclient.

**Comment by PVince81** [comment]
Are you sure this is the complete response ? It looks like it's only the list of attributes for a specific entry (maybe the root).

Can you try with curl ?

For example:
`curl -X PROPFIND http://root:admin@localhost/owncloud80/remote.php/webdav/ `

gives me:
```
<?xml version="1.0" encoding="utf-8"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns">
  <d:response>
    <d:href>/owncloud80/remote.php/webdav/</d:href>
    <d:propstat>
      <d:prop>
        <oc:id>00000003oc97lz78dlwj</oc:id>
        <oc:permissions>RDNVCK</oc:permissions>
        <oc:size>2440096</oc:size>
        <d:getetag>"553e58736bb39"</d:getetag>
        <d:getlastmodified>Mon, 27 Apr 2015 15:40:27 GMT</d:getlastmodified>
        <d:resourcetype>
          <d:collection/>
        </d:resourcetype>
        <d:quota-used-bytes>2440096</d:quota-used-bytes>
        <d:quota-available-bytes>42112020480</d:quota-available-bytes>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
  <d:response>
    <d:href>/owncloud80/remote.php/webdav/Documents/</d:href>
    <d:propstat>
      <d:prop>
        <oc:id>00000009oc97lz78dlwj</oc:id>
        <oc:permissions>RDNVCK</oc:permissions>
        <oc:size>36227</oc:size>
        <d:getetag>"5536203e63417"</d:getetag>
        <d:getlastmodified>Tue, 21 Apr 2015 10:02:38 GMT</d:getlastmodified>
        <d:resourcetype>
          <d:collection/>
        </d:resourcetype>
        <d:quota-used-bytes>36227</d:quota-used-bytes>
        <d:quota-available-bytes>42112020480</d:quota-available-bytes>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
  <d:response>
    <d:href>/owncloud80/remote.php/webdav/Photos/</d:href>
    <d:propstat>
      <d:prop>
        <oc:id>00000004oc97lz78dlwj</oc:id>
        <oc:permissions>RDNVCK</oc:permissions>
        <oc:size>678556</oc:size>
        <d:getetag>"5536203e2caee"</d:getetag>
        <d:getlastmodified>Tue, 21 Apr 2015 10:02:38 GMT</d:getlastmodified>
        <d:resourcetype>
          <d:collection/>
        </d:resourcetype>
        <d:quota-used-bytes>678556</d:quota-used-bytes>
        <d:quota-available-bytes>42112020480</d:quota-available-bytes>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
  <d:response>
    <d:href>/owncloud80/remote.php/webdav/newfile.txt</d:href>
    <d:propstat>
      <d:prop>
        <oc:id>00000026oc97lz78dlwj</oc:id>
        <oc:permissions>RDNVW</oc:permissions>
        <d:getetag>"5d56262e4d365be423ed793f8f0ce855"</d:getetag>
        <d:getlastmodified>Mon, 27 Apr 2015 15:40:27 GMT</d:getlastmodified>
        <d:getcontentlength>27</d:getcontentlength>
        <d:resourcetype/>
        <d:getcontenttype>text/plain</d:getcontenttype>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
  <d:response>
    <d:href>/owncloud80/remote.php/webdav/ownCloudUserManual.pdf</d:href>
    <d:propstat>
      <d:prop>
        <oc:id>00000008oc97lz78dlwj</oc:id>
        <oc:permissions>RDNVW</oc:permissions>
        <d:getetag>"3c59304032c99660a6e56e5abe4481eb"</d:getetag>
        <d:getlastmodified>Tue, 21 Apr 2015 10:02:38 GMT</d:getlastmodified>
        <d:getcontentlength>1725286</d:getcontentlength>
        <d:resourcetype/>
        <d:getcontenttype>application/pdf</d:getcontenttype>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
</d:multistatus>
```

In your case I guess you'd only see the root entry without children ?

Maybe try explicitly passing the "Depth: 1" header to get the list of children ?

**Comment by conxdev** [comment]
@PVince81 It working with curl from the terminal, I got this as root, https://bpaste.net/show/d6e584debfe3 
On changing the depth to 1 from in the code: https://bpaste.net/show/67fa8452f6cf got the same result,
https://bpaste.net/show/353ffb4ff4c9

**Comment by PVince81** [comment]
Yes, so you were probably missing "Depth: 1" then.
Works as expected.

**Comment by PVince81** [comment]
Wait, you said the same result, I thought the same result as curl.
Reopening. But it's very unlikely to be an ownCloud bug.

Have you tried connecting to a regular WebDAV server (ex: Apache WebDAV or lighttp WebDAV) ?
