### ISSUE TITLE
Missing openLDAP users binding with a non-rootDN account with pagination limits

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#15905]
### Steps to reproduce
1. Modify the configuration of the openLDAP server to add pagination support limits in the server
    1. Add the olcRootDN and olcRootPW to /etc/ldap/slapd.d/cn=config/olcDatabase={0}config.ldif so we can change the configuration
    2. Change the configuration setting the size.pr limit. (Use the username and password set before so the configuration is changed successfully) `ldapmodify -D "cn=admin,cn=config" -x -w <password> -f ~/cfg.ldif` where cfg.ldif has the content below.

        ```
        dn: olcDatabase={1}hdb,cn=config
        changetype: modify
        add: olcLimits
        olcLimits: * size.pr=30
        ```
2. Configure OC to connect to the LDAP server with a normal user, not the admin one (for example uid=aaliyah_adams,ou=people,dc=owncloudqa,dc=com).
3. Check that the paging chunksize in the directory settings is lower than the size.pr configured in the server
4. Go to the users page

### Expected behaviour
At least a maximum of 500 users (the default size limit for users is 500) should appear, or all available users (it might not be possible).

### Actual behaviour
No user from the LDAP server is shown

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** 8.1 alpha 2

**Updated from an older ownCloud or fresh install:** fresh install

### Notes
This issue isn't reproducible if the user is the rootDN account (typically admin) because no limits are applied to that account.

The user count is expected (500 even though there are about 1000 users) due to the size limitation in the server.

If the OC admin set a paging chucksize greater than the size.pr limit the user count is 0 and no user will appear. This might be acceptable (sue to server limitations) but it would be better if an error message appears warning the user about this.

**Comment by jvillafanez** [comment]
@blizzz

**Comment by blizzz** [comment]
Is the user account allowed to read from LDAP at all?

**Comment by jvillafanez** [comment]
Looks like it was something with the cache. I've rechecked the issue and now it shows 500 users

**Comment by blizzz** [comment]
Ok, thx.
