### ISSUE TITLE
Add basic unit tests for app.php and routes.php

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#15917]
As per https://github.com/owncloud/core/pull/15915#issuecomment-97071508

**Comment by DeepDiver1975** [comment]
THX - solution proposal is welcome as well :wink:

**Comment by cmonteroluque** [comment]
@nickvergessen @DeepDiver1975 ping?

**Comment by nickvergessen** [comment]
Not really important, can be delayed
