### ISSUE TITLE
Owncloud Logo theming documentation is misleading

### ISSUE THREAD

**Issue by fira** [owncloud/core#15912]
According to Owncloud doc, all you have to do to get the logo changed is put it into themes/[name]/core/img/ as logo.svg (and variants).
After hours of not managing to get it to work, i found a static reference to the logo file in the CSS stylesheets of the core files (core/css/header.css)
Effectively, you apparently need to also override .logo in this stylesheet for it to work, and this isn't written anywhere in the theming documentation...

**Comment by LukasReschke** [comment]
Please file documentation issues at https://github.com/owncloud/documentation
