### ISSUE TITLE
Public link buttons dimensions broken

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15916]
![public-link-button-size](https://cloud.githubusercontent.com/assets/277525/7370177/7c4ab920-edb8-11e4-93c9-6e2f4b0c531a.png)

@jancborchardt can you have a look ?
It happens since https://github.com/owncloud/core/pull/15875

(use this branch https://github.com/owncloud/core/pull/15915 if master is still broken)

**Comment by MorrisJobke** [comment]
It's the `display: inline-block;` of the `.button` class.

**Comment by MorrisJobke** [comment]
This was caused by #15875

**Comment by MorrisJobke** [comment]
@jancborchardt Can you have a look?

**Comment by jancborchardt** [comment]
Fixed with the revert, please review: https://github.com/owncloud/core/pull/15942
