### ISSUE TITLE
Lazy propagate etags to all users except current one

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15910]
This PR https://github.com/owncloud/core/pull/14764 introduces lazy etag propagation.
But in some cases it still updates the etag of other users who are not the current one (ex: owner).

To reduce the number of cache updates, we should make sure that the etag propagation is only done for the currently logged in user (the one who performed an action), and lazily do it for other users.

This came to mind after getting feedback from @butonic regarding excessive PostgreSQL cache updates.

@icewind1991

**Comment by PVince81** [comment]
There is a test plan here: https://github.com/owncloud/core/pull/14764#issuecomment-91272178
If you monitor the DB changes, you can notice that in some cases the etag is changed directly (non-lazily) for more than a user.

**Comment by guruz** [comment]
Sounds smart!

**Comment by PVince81** [comment]
@icewind1991 I guess this is obsolete thanks to the new "storage-only etag propagation" + "compute etag of all mounted storages" logic ?

**Comment by icewind1991** [comment]
Yes
