### ISSUE TITLE
Public sharing broken on master

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#15913]
@icewind1991 While fixing the namespace in https://github.com/owncloud/core/blob/557b4a2cb0ae0367e5facb1e4be136de07ab8cff/apps/files_sharing/appinfo/application.php you broke public sharing in core completely, please take a look at https://github.com/owncloud/core/blob/557b4a2cb0ae0367e5facb1e4be136de07ab8cff/core/routes.php#L111-L126

Regression by the ETag PR from https://github.com/owncloud/core/pull/14764

**Comment by LukasReschke** [comment]
Wondering if Scrutinizer should have catched that, waiting for analysis as per https://github.com/owncloud/core/pull/14764#issuecomment-96648539

@DeepDiver1975 Anything we can do to catch such stuff on Jenkins?

**Comment by LukasReschke** [comment]
PR is at https://github.com/owncloud/core/pull/15915

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 Anything we can do to catch such stuff on Jenkins?

unit tests

**Comment by LukasReschke** [comment]
> unit tests

Of the routing file? – Long way to go :see_no_evil:
