### ISSUE TITLE
PHP Notice versions

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#15924]
````
{"reqId":"3OphSUQJnlPdis0GuFrF","remoteAddr":"::1","app":"PHP","message":"Undefined index: dirname at \/home\/deepdiver\/Development\/ownCloud\/core\/apps\/files_versions\/lib\/storage.php#314","level":3,"time":"2015-04-29T08:03:11+00:00","method":"GET","url":"\/oc\/core\/cron.php"}
{"reqId":"3pZRXjisIiw7qXJP1rTU","remoteAddr":"::1","app":"PHP","message":"Undefined index: dirname at \/home\/deepdiver\/Development\/ownCloud\/core\/apps\/files_versions\/lib\/storage.php#314","level":3,"time":"2015-04-29T08:03:18+00:00","method":"GET","url":"\/oc\/core\/cron.php"}

**Comment by nickvergessen** [comment]
http://php.net/manual/en/function.pathinfo.php doesn't say that dirname is "optional", I guess we could check for that, but several other places use it aswell:
https://github.com/owncloud/core/blob/master/apps/files_sharing/lib/helper.php#L246-246

**Comment by DeepDiver1975** [comment]
![fixit](https://cloud.githubusercontent.com/assets/1005065/7386838/7368cbd0-ee58-11e4-96db-21153fad8ab7.png)

**Comment by nickvergessen** [comment]
Thanks for your report, please use the issue template, so we have the necessary information:
https://raw.github.com/owncloud/core/master/issue_template.md

especially server php version might be of interest for developers trying to reproduce the issue

**Comment by DeepDiver1975** [comment]
> especially server php version might be of interest for developers trying to reproduce the issue

![touche](https://cloud.githubusercontent.com/assets/1005065/7386933/4a7b4666-ee59-11e4-9725-deb93bb65dbd.png)

**Comment by karlitschek** [comment]
@nickvergessen Do you have a minute to FIX IT?  ;-) ;-)

**Comment by nickvergessen** [comment]
we are still missing the necessary information. I can not reproduce it on my php version (5.5.24) so I don't think I can fix it currently.
The method as per php documentation returns this key in it's array, but for thomas it does not... :octocat:

**Comment by DeepDiver1975** [comment]
> http://php.net/manual/en/function.pathinfo.php doesn't say that dirname is "optional", I guess we could check for that, but several other places use it aswell:

looks like docs are not that precise

![bildschirmfoto von 2015-05-07 14 02 42](https://cloud.githubusercontent.com/assets/1005065/7514856/d0881112-f4c1-11e4-81c1-7ae105d48ad2.png)

**Comment by nickvergessen** [comment]
Nice, empty string seems to be the only exception.

```
$ php -r 'var_dump(pathinfo(""));'
array(2) {
  'basename' =>
  string(0) ""

$ php -r 'var_dump(pathinfo("."));'
array(4) {
  'dirname' =>
  string(1) "."
  'basename' =>
  string(1) "."
  'extension' =>
  string(0) ""
  'filename' =>
  string(0) ""
}

$ php -r 'var_dump(pathinfo("./"));'
array(4) {
  'dirname' =>
  string(1) "."
  'basename' =>
  string(1) "."
  'extension' =>
  string(0) ""
  'filename' =>
  string(0) ""
}

$ php -r 'var_dump(pathinfo("./console.php"));'
array(4) {
  'dirname' =>
  string(1) "."
  'basename' =>
  string(11) "console.php"
  'extension' =>
  string(3) "php"
  'filename' =>
  string(7) "console"
}
```
I guess we will just return with an empty array then, since there shouldn't be any versions returned, when the path is empty. (We do that aswell, when the path (which fails to be generated here) can not be opened)
