### ISSUE TITLE
Wrong behaviour with Edit LDAP Query configuration pop-up window and background

### ISSUE THREAD

**Issue by davitol** [owncloud/core#15929]
### Steps to reproduce
1. Modify the configuration of the openLDAP server.
2. Set a right configuration in server tab and continue
3. Click on Edit LDAP Query option. A pop-up window about Mode switch confirmation appears.
4. Without clicking on the pop-up window, click again on Edit LDAP query

### Expected behaviour
Edit LDAP Query option should not be enable for clicking

### Actual behaviour
It is allowed to click on Edit LDAP Query option in the background so many times as you want, with the corresponding pop-up window. 

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** 8.1 alpha 2

**Updated from an older ownCloud or fresh install:** fresh install

### Notes
![modeswitch](https://cloud.githubusercontent.com/assets/10596560/7389900/d720ca82-ee72-11e4-94e4-37c677d2469f.png)

**Comment by cmonteroluque** [comment]
I doubt it will get fixed anytime soon
