### ISSUE TITLE
Migrate keys in admin page after enabling encryption blocks owncloud server

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#15923]
### Steps to reproduce
1. Enable encryption app.
2. Go to admin page.
3. Click on enable encryption.
4. Click on migrate keys.
Note: don't relogin in any step.

### Expected behaviour
Keys are migrated and users can login again.

### Actual behaviour
Owncloud server is blocked, and nobody can use it again.

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
8.1 alpha2

**Updated from an older ownCloud or fresh install:**
Fresh

**Logs**
```
{"reqId":"xXA6xRypHII6ePBxRNIM","remoteAddr":"10.40.40.48","app":"no app in context","message":"Installation is in transit between the old Encryption (ownCloud <= 8.0)\n\t\t\tand the new encryption. Please enable the \"ownCloud Default Encryption Module\"\n\t\t\tand run 'occ encryption:migrate'","level":2,"time":"2015-04-29T07:37:51+00:00"}
{"reqId":"xXA6xRypHII6ePBxRNIM","remoteAddr":"10.40.40.48","app":"PHP","message":"opendir(\/var\/www\/html\/8.1alpha2\/data\/files_encryption\/keys): failed to open dir: No such file or directory at \/var\/www\/html\/8.1alpha2\/lib\/private\/files\/storage\/local.php#105","level":3,"time":"2015-04-29T07:37:51+00:00"}
```

**Comment by DeepDiver1975** [comment]
@th3fallen @schiesbn please have a look - THX

**Comment by SergioBertolinSG** [comment]
Rebooting has made server work again, this happened with 8.1alpha2 enterprise tarball. 
After enabling encryption in admin page instead of:
Select default encryption module:
    ownCloud Default Encryption 
There was a button.

I've retested with current master branch in community and not happened. Now the ownCloud default encryption was there instead of the button.

**Comment by schiesbn** [comment]
I couldn't reproduce it on master. Are you sure that you started with a complete fresh installation (no data and empty database)?

**Comment by SergioBertolinSG** [comment]
I have tested this again with the enterprise tarball but it didn't happen.
So I am closing this for now, keeping an eye open to revive it if i see it again.
