### ISSUE TITLE
App installer does set wrong user/group when installing new apps

### ISSUE THREAD

**Issue by JostBaron** [owncloud/core#15927]
My setup is as follows:
- Running Apache as webserver, using PHP-FPM for PHP.
- Apache runs as `www-data`, PHP as `php`.
- The code directory is owned by `www-data:php`.
- The data directory is outside the code directory and owned by `php:php`.

**Problem**: When installing an app using the web interface, the apps files are owned by `php:php`. This prevents `www-data` from reading them, which prevents loading stylesheets and JS for that App.

**Expected behavior**: Use some defined owner/group for files created over the web interface, ideally configurable in the `config.php`, and allow different user/group settings for installed apps and the data directory.

**Comment by karlitschek** [comment]
Not sure this is something we actually can do. Maybe the best possible fix is to run php and apache is the same user.
