### ISSUE TITLE
Recovery password box in users page overlaps search box when zooming in

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#15928]
## Steps to reproduce
1. Enable encryption app.
2. Go to admin page.
3. Click on enable encryption.
4. Relogin with admin user.
5. Enable recovery password.
6. Go to users page.
7. Zoom in.

### Expected behaviour
Elements in screen doesn't overlap.

### Actual behaviour
![screen shot 2015-04-29 at 13 07 33](https://cloud.githubusercontent.com/assets/9048796/7389970/7f85e77a-ee73-11e4-9e40-30dbbf0e50c1.png)

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
8.1 alpha2

**Updated from an older ownCloud or fresh install:**
Fresh

**Logs**
```

```

**Browser**
Chrome 41

**Comment by nickvergessen** [comment]
@jancborchardt

**Comment by jancborchardt** [comment]
We already hide the search box in mobile mode. Anything beyond that we have to fix by simply using the main search box up top: https://github.com/owncloud/core/issues/14973

**Comment by jancborchardt** [comment]
Probable fix at https://github.com/owncloud/core/pull/16283
