### ISSUE TITLE
Filesystem permisson requirements too strict in 8.0.x

### ISSUE THREAD

**Issue by JostBaron** [owncloud/core#15920]
Just updated from 7.0.2 to 8.0.2, with this setup:

 * Two users, `www-data` (apache) and `php` (php-fpm). 
 * Data directory outside of code directory, owner and group `php:php`, permissions 0660 (files) / 0770 (dirs).
 * Code directory has owner `www-data` and group `php`, permissions 0660 (files) / 0770 (dirs).

So apache can't even read the data directory, if someone finds a hole in it.

But at the update, running `sudo -u php php occ upgrade`, I got this message:

> Console has to be executed with the same user as the web server is operated
Current user: php
Web server user: www-data

Worked fine with the same command when update from 7.0.x to 7.0.(x+1).

When I try `sudo -u www-data php occ upgrade`, I get a message that my permissions are wrong, because the data directory can't be read, which is intentional.

Expected behaviour: Any user that can read the data can execute an update. Please remove that check again.

**Comment by Xenopathic** [comment]
You need to change the permission on `config/config.php` to match your PHP user.

**Comment by JostBaron** [comment]
Can you elaborate? `config/config.php` had permissions `0660`, with ownership `www-data:php`. To what do I need to set them, and how does this affect the above problem? Is the apache user determined as the user that is the owner of `config.php`?

**Comment by RealRancor** [comment]
Hi,

yes. The owner of config/config.php is used for this check:

https://github.com/owncloud/core/blob/v8.0.2/console.php#L33-L40
