### ISSUE TITLE
Cannot login in an user account using 2 LDAP servers and having a common user in both of them

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#15939]
### Steps to reproduce
1. Setup and configure 2 LDAP servers making sure that at least one user is “shared” in both servers (uid and display name are the same, an also with the same password)
2. Keep the basic configuration, so users can login with their uid
3. Go to the users page. You should see 2 different users from both LDAP servers with the same name
4. Try to login with both users.

### Expected behaviour
You can login with the both users in their respective account

### Actual behaviour
You can login only in the user account of the first LDAP server configured. Although it's possible to switch the login method to email, this could also happen in that case too.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 alpha 2

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by jvillafanez** [comment]
@blizzz

**Comment by blizzz** [comment]
IMHO this is an issue with your directory structure, not within ownCloud.
