### ISSUE TITLE
UTF-8 chars changed or deleted from the username column of the users page 

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#15936]
### Steps to reproduce
1. Configure an LDAP server with persons that have UTF-8 chars in the uid (checked with openLDAP and uids for persons such as "007_憲明" and "007_bärh")
2. Change the wizard configuration to use the uid as internal username attribute in the expert tab of the wizard.
3. Go to the users page

### Expected behaviour
All LDAP users have their LDAP uid as username

### Actual behaviour
UTF-8 chars of their uids are changed or deleted (check screenshot below - uid is the same as the full name but changing the whitespace to an underscore)

![screenshot from 2015-04-29 16 51 08](https://cloud.githubusercontent.com/assets/1477829/7393790/0ccba770-ee90-11e4-8b88-932f8840d43a.png)

Notice that it's likely to cause collisions in the data folder for users such as "007_barh", "007_bärh", "007_bárh" or "007_bârh"

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 alpha 2

**Updated from an older ownCloud or fresh install:** fresh install

### Notes
I've tried to create an normal user with UTF-8 chars in the name and it isn't allowed. Probably the expected behaviour won't be possible due to some kind of limitation.

**Comment by jvillafanez** [comment]
@blizzz

**Comment by blizzz** [comment]
only ascii letter are allowed as internal name (e.g.  also try to create a local  user with such characters). Also, it is documented even directly on the Expert tab right at the corresponding setting.
