### ISSUE TITLE
Default LDAP filter is wrong in Login Attributes tab

### ISSUE THREAD

**Issue by davitol** [owncloud/core#15933]
### Steps to reproduce
1. In assisted mode set a right configuration in the server and user tab
2. Continue to the Login Attributes tab

### Expected behaviour
The LDAP default filter should have (samaccountname=%uid)) part 
### Actual behaviour
The LDAP default filter in login attributes tab has no uid. 

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 alpha 2

**Updated from an older ownCloud or fresh install:** fresh install

![personfilteruid1](https://cloud.githubusercontent.com/assets/10596560/7391123/b457e3d0-ee7e-11e4-88fe-e31c8169e547.png)

**Comment by LukasReschke** [comment]
@blizzz

**Comment by davitol** [comment]
Maybe this behaviour is only with active directory

**Comment by blizzz** [comment]
Nope, default values for the wizard were sent to the browser, but not applied/saved with the configuration. When composing the filter, the backend "thought" username should not be used. Fix in #16069

**Comment by davitol** [comment]
:+1: It is fixed
