### ISSUE TITLE
Automatic activation of the LDAP configuration after changing the login filter

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#15941]
### Steps to reproduce
1. Have a completed configuration
2. Edit the login filter to a wrong one (for example, `(&(|(objectclass=inetOrgPerson))(uid=%u))`) in order to make the configuration invalid
3. Deactive the configuration (Advanced tab)
4. Reload
5. Fix the value
6. Go to Advanced tab, Connection settings
### Expected behaviour

Configuration should have not been activated again (to be more robust against undesired activation)
### Actual behaviour

Configuration is activated automatically
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 alpha 2

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by jvillafanez** [comment]
@blizzz

**Comment by blizzz** [comment]
For now, that is intended behaviour. The assumption is that if you edit something in an deactivated configuration, then you intend to activate is. Therefore this happens. Otherwise, robustness against undesired activation has been improved (browsing configurations without changing is safe).

Of course we can discuss whether the current state is good or not, and perhaps come up with a better/different solution, but not before 8.2. 

I'd be happy about your oppinion @jancborchardt.

**Comment by jancborchardt** [comment]
Yes, @blizzz’s assumption seems correct and makes it easier on people who might forget to specifically click »activate«.

**Comment by jvillafanez** [comment]
The problem is that if you change the host or port instead of the login filter following the same steps, the configuration doesn't get activated. This is confusing for me.

If changing some values will activate the configuration, and changing others not, maybe we need to distinguish somehow what are the ones that will activate the configuration.

**Comment by blizzz** [comment]
> The problem is that if you change the host or port instead of the login filter following the same steps, the configuration doesn't get activated. This is confusing for me.

Um, too robust now? Will check.

**Comment by PVince81** [comment]
Any update ?

**Comment by blizzz** [comment]
nope, but thanks for tagging.

**Comment by PVince81** [comment]
Reopen in user_ldap repo if important enough
