### ISSUE TITLE
[enc2] changepassword controller breaks encryption modularity

### ISSUE THREAD

**Issue by th3fallen** [owncloud/core#15940]
https://github.com/owncloud/core/blob/master/settings/changepassword/controller.php#L82-L109 is making calls straight to default encryption app methods.

These need to be decoupled immediately as they completely defeat the purpose of what we did in the refactor.

Also the `changeUserPassword` method errors have the chance of falling through and showing multiple errors that the frontend can't handle.

Also also controller should be made a REAL controller to enable ability to remov eusage of depreciated methods such as `OC_JSON`

Cc @DeepDiver1975 @schiesbn @PVince81 

related to https://github.com/owncloud/core/issues/15823 and https://github.com/owncloud/core/issues/15822

**Comment by th3fallen** [comment]
@DeepDiver1975 please confirm this can be done before release if so i'll get started on it.

**Comment by schiesbn** [comment]
Ideally we would decouple the recovery process from the user management and add it either to the admin setting, or as a "app" called something like "Recover Encrypted files" to the apps menu of the admin. But I think that's to late for 8.1. So for now I would keep it as it is and just fix the remaining issues we introduced during the re-write.
