### ISSUE TITLE
Previous versions of a file before enabling encryption won't be encrypted after edition

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#15943]
### Steps to reproduce
1. Have a file with some versions.
2. Enable encryption app.
3. Go to admin page.
4. Click on enable encryption.
6. Relogin.
7. Edit the file.
8. Restore first version of the file.

### Expected behaviour
To be discussed

### Actual behaviour
File is not encrypted.
Versions of the file before enabling encryption are not encrypted after an edit.

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
8.1 alpha2

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
Yes.

**Logs**
```

```

**Comment by schiesbn** [comment]
That's in line with the current behaviour for regular files. We don't encrypt existing files but only new files after the encryption was enabled. So old versions will stay unencrypted and new versions will be encrypted. Once we have a occ tool in 8.1 to initially encrypt all files we will also encrypt existing versions again

**Comment by PVince81** [comment]
@schiesbn and from what I heard you saying when I asked, this will continue to be the case in 8.2 even with the encrypt/decrypt CLI tool.

Should we keep this enhancement to implement versions encryption in the future or won't fix ?

**Comment by PVince81** [comment]
@MTRichards @cmonteroluque

**Comment by cmonteroluque** [comment]
@PVince81 I think this is won't fix. @MTRichards to confirm

**Comment by MTRichards** [comment]
Correct, this is expected - thanks @cmonteroluque .

**Comment by PVince81** [comment]
Closing, then
