### ISSUE TITLE
Do not ship dummy encryption test module

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#15950]
### Steps to reproduce

1. Install 8.1
2. Go to not enabled apps
3. Scroll down to the bottom for the encryption apps

### Expected behaviour

No dummy modules should be shipped

### Actual behaviour

There is a dummy test module 

### Server configuration

ownCloud Enterprise Edition 8.1 alpha 2 (testing)

**Comment by DeepDiver1975** [comment]
@karlitschek something to be added to the release script from my understanding. THX

**Comment by karlitschek** [comment]
@DeepDiver1975 possible. But maybe we can move this out of the core repository? By doing this we avoid to have special behaviors coded for special apps which will break in the future.

**Comment by DeepDiver1975** [comment]
> But maybe we can move this out of the core repository? By doing this we avoid to have special behaviors coded for special apps which will break in the future.

fine with me as well - onwcloud/apps should be enough from my understanding.
PRs on it's way
