### ISSUE TITLE
Abnormally large time loading the users page with a large LDAP server

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#15956]
### Steps to reproduce
1. Setup a large LDAP server (checked with two local server with 6 and 1000 users, and two additional servers inside a VPN with 1000 and 1M users)
2. Go to the users page

### Expected behaviour
Page is loaded in an acceptable amount of time (showing the first 30 users and taking into account the network speed, probably less than 30 secs)

### Actual behaviour
It takes an abnormal amount of time (11m 22s) to load just the first 30 users.

![screenshot from 2015-04-30 10 45 47](https://cloud.githubusercontent.com/assets/1477829/7409381/46038116-ef26-11e4-8b45-2e0c8132c50d.png)

![screenshot from 2015-04-30 10 57 31](https://cloud.githubusercontent.com/assets/1477829/7409581/bfe16af6-ef27-11e4-9cf1-914d47dd3fb5.png)

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 alpha 2

**Updated from an older ownCloud or fresh install:** fresh install

### Notes
To be checked if it because of the app, or due to a slow response of the LDAP server (bad configuration, LDAP server not optimized, server overloaded, etc)

**Comment by DeepDiver1975** [comment]
@blizzz please have a look once you are back - THX

**Comment by jvillafanez** [comment]
To be clearer (even I get confused), this issue is a matter of scaling the app to handle the servers described in the issue. Don't get confused with https://github.com/owncloud/core/issues/15930 because the later one might be due to having open PHP sessions that might block other requests

**Comment by karlitschek** [comment]
@blizzz Can we do something here?

**Comment by blizzz** [comment]
It's the user count that takes long. We improved this a bit for OC 8, so it would be cached. One possibility would be to have it running as a background job, and only when triggered by cron. Still not bulletproof. And it might be overkill, as the Users page is not called that often usually.

**Comment by blizzz** [comment]
Another aspect: the first time the Users page is called in those scenarios is after configuring LDAP, presumingly. In that case it would not help, either.

What might be better is to kickoff a count after logging in as admin. But even this might not be sufficient, dependent on the amount of available users.

The other solution would be to not count users and offers a button/clickable text instead to kick off count manually on the Users page. That can be made dependable on whether an external user backend is available and/or cancel fist count after finding 1001 users and offer counting only in this case.

Opinions?

cc @MorrisJobke for the Users page idea.

**Comment by MorrisJobke** [comment]
maybe count to 999 and then say `999+` which is clickable and then load the actual count?

**Comment by jvillafanez** [comment]
Is it possible / feasible to count up to 999 users (more or less) and then trigger an asynchronous job to keep counting? When the user clicks the "refresh count" button we get the count from the async job even if it haven't finished yet. The user should see something like "999 users and counting"

This way, the page loads in a constant amount of time regardless of the number of users, and at the same time we provide a more or less accurate counting.

**Comment by Yamakasi** [comment]
Hi,

I have this issue on 20 users also.

I think there is just something not right in handling of the ldap function and it tries forever.

**Comment by blizzz** [comment]
@MorrisJobke that was my suggestion, only i had the threshold with 1k.

**Comment by blizzz** [comment]
@Yamakasi i doubt it is the same issue. Can you do a screenshot of the network tab as well, just like @jvillafanez provided in the description?

**Comment by MorrisJobke** [comment]
> @MorrisJobke that was my suggestion, only i had the threshold with 1k.

:+1:

**Comment by blizzz** [comment]
@jancborchardt are you also ok with that approach? ^

**Comment by jancborchardt** [comment]
Yeah, just say »999+« and then load it on hover or so. That’s similar how it’s done in the News app.

**Comment by DeepDiver1975** [comment]
We would need to change some semantics on the backends here - seems out of scope for 8.1

@karlitschek @MTRichards @cmonteroluque

**Comment by MTRichards** [comment]
Possibly a high risk item, but the extremely long wait is just not acceptable. We have fallen down here before, we can't again - this is one of those obvious items that should just work regardless of the scale, and 11m seems a little extreme.

**Comment by DeepDiver1975** [comment]
Short term solution: don't show the counter on groups

**Comment by MTRichards** [comment]
But what about the comment above about 20 users? Is there a bigger problem here?

**Comment by blizzz** [comment]
@deepdiver actually, we might work around it by using getUsers instead of count first,  which offers the limit functionality. It is slower, but should be OK for small, initial amounts.

**Comment by blizzz** [comment]
> @deepdiver actually, we might work around it by using getUsers instead of count first, which offers the limit functionality. It is slower, but should be OK for small, initial amounts.

I tested it, and this approach is not good (i.e. not fast enough) either. Has room for optimization as well.

**Comment by jvillafanez** [comment]
About the 20 users, I think it's another problem, probably a misconfiguration that makes one of the requests crash at some point, leaving the interface in a bad state (such as the spinner wheel loading forever). I can't confirm this right now.

**Comment by DeepDiver1975** [comment]
> Short term solution: don't show the counter on groups

@nickvergessen can you please open a pr to implement this? THX

**Comment by nickvergessen** [comment]
PR to sort by name and hide the count is at https://github.com/owncloud/core/issues/16402

**Comment by jvillafanez** [comment]
It's still painfully slow (still waiting the page to load). Is a change needed in the LDAP side?

**Comment by jvillafanez** [comment]
Almost 18min without caching. 1 local LDAP server with 6 users, and a remote one over a VPN with 1M users and 1000 groups.
![screenshot from 2015-05-18 13 36 05](https://cloud.githubusercontent.com/assets/1477829/7680048/ec3c4438-fd62-11e4-9dd5-80d3bf661923.png)

**Comment by DeepDiver1975** [comment]
@jvillafanez thx for testing this - can we continue this on the PR - THX

**Comment by DeepDiver1975** [comment]
@jvillafanez which ldap server are you testing against? any idea if that server supports paginated search? just a wild guess?

**Comment by jvillafanez** [comment]
I've checked with `ldapsearch -x -h "172.18.5.121" -D 'cn=admin,dc=example,dc=com' -E pr=3 -b "dc=example,dc=com" "(&(objectClass=inetOrgPerson))"` and returns results in a paginated way, so it should be supported

**Comment by DeepDiver1975** [comment]
@jvillafanez thanks!

**Comment by DeepDiver1975** [comment]
:sleeping: filling an ldap with 300000 users ... :zzz: :snail: :zzz:

**Comment by DeepDiver1975** [comment]
@blizzz what is the plan here ? We need to come up with some solution within the next few days - THX

**Comment by blizzz** [comment]
*investigating/working on it*

**Comment by blizzz** [comment]
@DeepDiver1975 left comment here https://github.com/owncloud/core/pull/16402#issuecomment-107729139

**Comment by DeepDiver1975** [comment]
still requires #16736
