### ISSUE TITLE
Clicking on the name of an enable app, a new browser tab is opened with the same info.

### ISSUE THREAD

**Issue by davitol** [owncloud/core#15953]
### Steps to reproduce
1. In Apps menu select Enabled menu for example
2. Click on the name of any of the apps.

### Expected behaviour
Click on the name of apps should be disable. 

### Actual behaviour
A new tab with the same info is opened in the browser. That makes no sense.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 alpha 2

**Updated from an older ownCloud or fresh install:** fresh install

![enabledapp](https://cloud.githubusercontent.com/assets/10596560/7407671/feb54fe4-ef14-11e4-9642-e63028c6e4b6.png)

**Comment by jancborchardt** [comment]
That’s because clicking on the title is only useful for the apps from the store – a click on the name opens their store page. A click on the title for local apps should of course not do anything.

@DeepDiver1975 can you fix this?
