### ISSUE TITLE
Moving encrypted files to an external storage folder with encryption enabled decrypts them.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#15963]
### Steps to reproduce
1. Enable encryption app.
2. In admin page enable encryption.
3. Relogin.
4. Upload some files. Be sure they are encrypted.
5. Mount an amazon S3 folder and be sure encryption is enabled on it (gear on the right).
6. Move one of those files into S3 folder.
7. Open file in S3 using some program for connect like cyberduck or others. 

### Expected behaviour
File is encrypted.

### Actual behaviour
File is not encrypted.

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
8.1 alpha2

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes S3.

**Are you using encryption:** 
Yes.

**Logs**
```

```

**Comment by schiesbn** [comment]
This pr should fix it: https://github.com/owncloud/core/pull/15628
