### ISSUE TITLE
[enc2] occ encryption:migrate gives BadMethodCallException

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15979]
### Steps
1. Setup 8.0.2 with LDAP
2. Enable recovery key (not sure if relevant)
3. Login as a LDAP user, enable recovery key in personal page
4. Upgrade to 8.1 / master
5. Enable encryption in admin page
6. Enable default encryption module app
7. Go back to admin page: it tells you to run "./occ encryption:migrate"
8. Run `./occ encryption:migrate`

### Expected result
Migration successful

### Actual result:
```
vvortex:/srv/www/htdocs/owncloud # sudo -uwwwrun ./occ encryption:migrate
Reorganize system folder structure


                                                                                              
  [BadMethodCallException]                                                                    
  path needs to be relative to the system wide data folder and point to a user specific file  
                                                                                              


encryption:migrate [user_id1] ... [user_idN]
```

### Versions
ownCloud 8.1 git master (41d7870d7b8aa1b635fd1d2d589322160bb46d31)

**Comment by PVince81** [comment]
@schiesbn @th3fallen @DeepDiver1975

**Comment by PVince81** [comment]
and this appears in the log when running the command:
```
{"reqId":"+bk\/TubvBdhQb0tG7eUL","remoteAddr":"","app":"no app in context","message":"Installation is in transit between the old Encryption (ownCloud <= 8.0)\n\t\t\tand the new encryption. Please enable the \"ownCloud Default Encryption Module\"\n\t\t\tand run 'occ encryption:migrate'","level":2,"time":"2015-04-30T15:03:25+00:00","method":"--","url":"--"}
{"reqId":"+bk\/TubvBdhQb0tG7eUL","remoteAddr":"","app":"user_ldap","message":"No group filter is specified, LDAP group feature will not be used.","level":1,"time":"2015-04-30T15:03:25+00:00","method":"--","url":"--"}
```

**Comment by schiesbn** [comment]
Does this really only happen with LDAP? I don't see the connection here.

**Comment by PVince81** [comment]
Not sure, this happened when I tested with LDAP. Haven't tried without.

**Comment by schiesbn** [comment]
I can reprodue the error without LDAP... Will have a look at it
