### ISSUE TITLE
occ encryption:list-modules should display a message when encryption is not enabled

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#15976]
### Steps to reproduce

1. Install 8.1
2. From occ, list encryption modules

### Expected behaviour

The user gets a message that encryption is not enabled

### Actual behaviour

There is no command output.

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration:

ownCloud Enterprise Edition 8.1 alpha 2 (daily) Build:2015-04-30T03:08:25+00:00 4209757d61685346b9b3eb476035b4e86597ed6

**Comment by jnfrmarks** [comment]
It looks like there's no output after enabling encryption:

```
ubuntu-14-lts:/var/www/html/owncloud# sudo -u www-data php occ encryption:enable
Encryption is already enabled
Default module: OC_DEFAULT_MODULE
ubuntu-14-lts:/var/www/html/owncloud# sudo -u www-data php occ encryption:list-modules
ubuntu-14-lts:

```

**Comment by jnfrmarks** [comment]
More info:

I was able to get output after actually enabling the app itself, not just the encryption using occ.

**Comment by nickvergessen** [comment]
Well 
```
occ encryption:list-modules --output=json
```
out puts a json list, so doing any other output breaks this nice behaviour and makes the list not easily parsable anymore.

I'd say we can group that with the status request you made, and have `encryption:status` which then outputs:

1. is it enabled
2. what's the default module

**Comment by jnfrmarks** [comment]
@nickvergessen 

That sounds good.  I'll close this one since it will be covered in https://github.com/owncloud/core/issues/15977
