### ISSUE TITLE
Add occ encryption:status to allow users to query if it's enabled or not

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#15977]
### Steps to reproduce

1. Install 8.1

### Expected behaviour

A way to find out if encryption is enabled via occ

### Actual behaviour

There isn't a way to find out if encryption is enabled via occ
Maybe we can add a command occ encryption:status?

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration:

ownCloud Enterprise Edition 8.1 alpha 2 (daily) Build:2015-04-30T03:08:25+00:00 4209757d61685346b9b3eb476035b4e86597ed64

**Comment by DeepDiver1975** [comment]
@nickvergessen

**Comment by jnfrmarks** [comment]
One thing that has struck me is that we're using an internal variable OC_<name> to identify the module when referencing it in an occ command.  This was not intuitive to me when I first starting using OCC to manage encryption.  It wasn't until I did a list of the modules that I realized that I needed to enter the internal attribute and not the module name.  I'm not sure if there's a way to guide the customer there a bit more.

**Comment by nickvergessen** [comment]
@jnfrmarks well that's what an id is used for. The `--help` option shows that already.
I don't think we can do a lot more:
```
$ ./occ encryption:set-default-module --help
Usage:
 encryption:set-default-module module

Arguments:
 module                ID of the encryption module that should be used

Options:
 --help (-h)           Display this help message
