### ISSUE TITLE
LDAP wizard configuration. 'Test filter button' behaviour in Groups tab is wrong

### ISSUE THREAD

**Issue by davitol** [owncloud/core#15971]
### Steps to reproduce
1. Set a OK configuration in LDAP wizard.
2. In Groups tab click on the Test Filter button

### Expected behaviour

Test Filter button should test if filter is wrong.

### Actual behaviour
Test filter button has no functionality.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 alpha 2

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by karlitschek** [comment]
@blizzz

**Comment by blizzz** [comment]
Next to the button the number of groups found should appear. Is this not happening to you? Do you have anything configured there, and if what?

**Comment by davitol** [comment]
I'm talking about Test Filter button, not the "Verify setting and count groups".

![testfilter](https://cloud.githubusercontent.com/assets/10596560/7468641/45484c5a-f30b-11e4-9c89-fc451748accf.png)

**Comment by karlitschek** [comment]
@blizzz

**Comment by davitol** [comment]
Checked this in version beta1, key things:
- By default the button does not appear, however, if you
1.- Go to the admin view, LDAP wizard, section Groups
2.- Click on "Edit LDAP Query"
3.- Modify anything on the Query, such as delete a group
4.- click anywhere
5.- Click on edit (so you leave the edit mode)
6.- Click on edit again, so you access to edit mode again
7.- The button is shown

- Once the button is shown, if you click on it, nothing happens

So, should it be shown this button?

**Comment by blizzz** [comment]
The button used be shown only in expert mode, i.e. " Manually enter LDAP filters (recommended for large directories) " is checked in the server tab. But the functionality is now totally in "Verfiy settings and count stuff" button, so should be removed.

**Comment by blizzz** [comment]
setting to high not because it has any impact but just for confusion potential and can be removed easily.
