### ISSUE TITLE
Encryption can be enabled via occ even if the app itself is not enabled

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#15975]
### Steps to reproduce

1. Install 8.1
2. From occ, enable encryption

### Expected behaviour

Either the app gets enabled as part of the request to enable encryption or an error is thrown to inform the user that the encryption app is not yet enabled.

### Actual behaviour

Encryptoin gets enabled without enabling the app or throwing an error to inform the user that the encryption app is not yet enabled.

```
root@ubuntu-14-lts:/var/www/html/owncloud# sudo -u www-data php occ app:list
Enabled:
 - activity: 1.2.3
 - admin_audit: 0.6
 - enterprise_key: 0.1.0
 - files: 1.1.9
 - files_locking:
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.4
 - windows_network_drive: 0.1.1
Disabled:
 - encryption
 - encryption_dummy
 - external
 - files_antivirus
 - files_drop
 - files_external
 - files_ldap_home
 - firewall
 - firstrunwizard
 - objectstore
 - sharepoint
 - user_external
 - user_ldap
 - user_shibboleth
 - user_webdavauth
root@ubuntu-14-lts:/var/www/html/owncloud# sudo -u www-data php occ encryption:enable
Encryption enabled
Default module: OC_DEFAULT_MODULE
root@ubuntu-14-lts:/var/www/html/owncloud# sudo -u www-data php occ app:list       Enabled:
 - activity: 1.2.3
 - admin_audit: 0.6
 - enterprise_key: 0.1.0
 - files: 1.1.9
 - files_locking:
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.4
 - windows_network_drive: 0.1.1
Disabled:
 - encryption
 - encryption_dummy
 - external
 - files_antivirus
 - files_drop
 - files_external
 - files_ldap_home
 - firewall
 - firstrunwizard
 - objectstore
 - sharepoint
 - user_external
 - user_ldap
 - user_shibboleth
 - user_webdavauth
```

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration:

ownCloud Enterprise Edition 8.1 alpha 2 (daily) Build:2015-04-30T03:08:25+00:00 4209757d61685346b9b3eb476035b4e86597ed64

**Comment by nickvergessen** [comment]
The app is independent from the encryption itself and vice-versa.
Expected behaviour in my opinion.
There could be another encryption app, so enabling a random one might not be desired?

@schiesbn @DeepDiver1975

**Comment by jnfrmarks** [comment]
I understand what you're saying - as the end user though my initial thought was Great! I can enable encryption here.  

While the command option is new, this is a slight change in use of language from earlier versions.  Pre 8.1, "enabling encryption" meant file encryption is on and was part and parcel with enabling the app. 

In 8.1, enabling encryption is now a two step process: first enable the app in an encryption off state and then turn encryption on.

I'm wondering if we need some way to educate the end user on this change from either the UI or from occ?  I added the documentation tag for Carla to update this in our docs.

**Comment by nickvergessen** [comment]
Encryption docs have already been updated:
https://github.com/owncloud/documentation/pull/1088

I mean we can add output and tell the user to check if an encryption module is installed, but we shouldnt enable/install any app.

**Comment by jnfrmarks** [comment]
I like the idea of giving some indication that the user needs to check if the module is installed and enabled.  Maybe we can put that with the verbose option and with usage/help?
\

**Comment by jnfrmarks** [comment]
I now get the difference here and it is subtle (well to me anyway ;) )

Pre 8.1, encryption was enabled by enabling the app on the apps page.
In 8.1, encryption is enabled on the admin page.  In fact, you can try to enable it even if a module is not configured.  In that case, the UI displays a message to the user that an encryption module needs to be enabled - that is what we need to add here.

**Comment by DeepDiver1975** [comment]
> I mean we can add output and tell the user to check if an encryption module is installed, but we shouldnt enable/install any app.

yes for a warning/notice
no for automagically installing an app

**Comment by DeepDiver1975** [comment]
@nickvergessen can you please add that warning? Thansk a lot!

**Comment by jnfrmarks** [comment]
@DeepDiver1975 

I concur now that I understand the change a bit more :)
