### ISSUE TITLE
Enhancement Request: Encryption UI configuration wizard

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#15988]
Enhancement request:

As of 8.1 there are a few moving parts to enabling and configuring encryption.  Can we create a UI wizard similar to what we have for LDAP to keep everything together and guide the users through the configuration bits a bit more?

@MTRichards

**Comment by karlitschek** [comment]
@schiesbn

**Comment by jancborchardt** [comment]
Yes, we definitely need to make this easier. Also the whole new module stuff needs to be eased out.

**Comment by schiesbn** [comment]
Generally a nice idea, but I'm not sure if this will work in practice. 
Remember we want to enable users to write their own encryption module, maybe even encryption module we will never know about. How would a wizard integrate the settings of this modules if we don't know which module will will provide which settings and if it will have any settings at all. I also see scenarios where there is no point in time where the admin configures the whole encryption. But rather first enable encryption in general with module 1, at some point he set up a external storage and want to configure a different encryption module for it so at this point he enable the second encryption module, configure it etc.

As said the general idea is not bad, but don't think we can compare it to LDAP. The complexity level might be the same, but LDAP is a self-contained system while encryption has a much higher modularity and possible modules of which we know nothing.

**Comment by jancborchardt** [comment]
> Remember we want to enable users to write their own encryption module

This still sounds like overengineering to me. :\ Did a lot of people ask in the past for the ability to write their own encryption (I somehow think not)? So making it more difficult for most users just for the off-case someone wants to do their own thing is a bit misguided here. (And even if ppl wanted to do their own thing, they could write an own app or fork encryption or whatnot.)

**Comment by schiesbn** [comment]
> Did a lot of people ask in the past for the ability to write their own encryption (I somehow think not)?

Talk to @MTRichards and you will know :wink: 

Both users/customers want to write their own encryption and we want to provide different encryption algorithm, keymanagement etc in the feature because we learned in the last years that there is no one-size-fit-all solution.

**Comment by schiesbn** [comment]
@jnfrmarks now that we moved the settings closer to each other in the admin panel, do you think we can close this one? As said, I don't think it will be possible to write a wizard which takes all possible encryption modules and their possible settings into account.

**Comment by DeepDiver1975** [comment]
> @jnfrmarks now that we moved the settings closer to each other in the admin panel, do you think we can close this one?

I guess we did fight the confusion pretty good in the past weeks - THX @schiesbn
