### ISSUE TITLE
Missing focus style for radio buttons

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15983]
### Steps

(_Alternatively just go to the admin page and tab to the radio buttons of the cron settings. – Jan_)
1. Enable encryption
2. Go to admin page
3. Enter recovery password twice
4. Tab to the radio buttons
### Expected result

Visible focus/active style
### Actual result

Invisible focus. If you use the up/down arrows you can change the radio button value, which proves that the focus is there.
### Versions

stable8 and master

@owncloud/designers

**Comment by jancborchardt** [comment]
Another point to test this is the Cron settings in Admin. We have styles for focus/hover on checkbox labels, but not on radio button labels strangely enough.

**Comment by jancborchardt** [comment]
@owncloud/designers any idea why there are hover/focus styles for checkboxes but not for radio buttons?

**Comment by PVince81** [comment]
moved to more general UX group ticket: https://github.com/owncloud/core/issues/27578
