### ISSUE TITLE
occ check is silent

### ISSUE THREAD

**Issue by carlaschroder** [owncloud/core#15995]
Another new command to document: occ check "check dependencies of the server environment"
Is this a user command, and under what circumstances would a user run it?

**Comment by LukasReschke** [comment]
@jnweiger Care to explain what the use-case for this is?

**Comment by DeepDiver1975** [comment]
This command was purely design for packaging. Might makes sense for other use cases.

**Comment by carlaschroder** [comment]
So this is another scenario, like config.php, where there are things for users, and things user should not touch?

**Comment by carlaschroder** [comment]
@jnweiger, somebody, anybody :) Is there a use case for admins running this manually? Or do I say "hands off! not for you!" :)

**Comment by carlaschroder** [comment]
closing for lack of feedback, and if you don't like what the docs say you had your chance!
