### ISSUE TITLE
what are  ldap:create-empty-config and  ldap:delete-config  for?

### ISSUE THREAD

**Issue by carlaschroder** [owncloud/core#15991]
Will someone explain what the occ commands  ldap:create-empty-config and  ldap:delete-config are for? I need some basic use cases plz. Are these intended as normal LDAP maintenance commands?

 ldap:delete-config configID

Where does the configID come from? ldap:show-config?

**Comment by karlitschek** [comment]
@blizzz can you help with that?

**Comment by blizzz** [comment]
>  ldap:create-empty-config

let's you create an empty ldap configiuration on command line. You can modifiy it subsequently by using ldap:set-config $configID $key $value. With the combination of the two commands, you can programmatically set up LDAP configurations without manual interaction.

The equivalent in the wizard is the "Add Configuration" button.

>  ldap:delete-config

Well, this command deletes an LDAP configuration.

The equivalent in the wizard is the "Delete Configuration" button.

> Where does the configID come from? ldap:show-config?

Exactly. It is always at the start of the output, second column, here "s03":

```
+------------------------------+---------------------------------------------+
| Configuration                | s03                                         |
+------------------------------+---------------------------------------------+
| hasMemberOfFilterSupport     | 0                                           |
| hasPagedResultSupport        |                                             |
…
```

The first one usually is an empty string.

**Comment by carlaschroder** [comment]
thannsk @blizzz

**Comment by carlaschroder** [comment]
https://github.com/owncloud/documentation/pull/1098
