### ISSUE TITLE
apps/files/ajax/delete.php calls OC\Files\Filesystem::unlink() for directories

### ISSUE THREAD

**Issue by dagan** [owncloud/core#15999]
```php
//Now delete
foreach ($files as $file) {
	if (\OC\Files\Filesystem::file_exists($dir . '/' . $file) &&
		!(\OC\Files\Filesystem::isDeletable($dir . '/' . $file) &&
			\OC\Files\Filesystem::unlink($dir . '/' . $file))
	) {
		$filesWithError .= $file . "\n";
		$success = false;
	}
}
```
https://github.com/owncloud/core/blob/master/apps/files/ajax/delete.php#L55-L64

```\OC\Files\Filesystem``` has two methods for deleting objects—```unlink()``` to delete files and ```rmdir()``` to remove directories—which are forwarded to the view and then to the underlying storage. If the storage then implements ```unlink()``` using PHP's ```unlink()``` function, deleting a directory will fail. This forces the storage to perform an ```is_dir()``` test within ```unlink()``` and forward to ```rmdir()``` for directories.

**Comment by DeepDiver1975** [comment]
@icewind1991 can I ask you to have a look? THX

**Comment by PVince81** [comment]
Ideally this behavior should be changed and be made consistent across all storages and implementations.
I'd then say that "unlink()" would be strictly reserved for files and "rmdir()" for folders.

**Comment by DeepDiver1975** [comment]
> I'd then say that "unlink()" would be strictly reserved for files and "rmdir()" for folders.

thinking the REST/DAV/HTTP way: it's a delete on a resource .... :speak_no_evil:

**Comment by PVince81** [comment]
Yes, but most of the filesystem layer API is mimicking the ones from PHP. It even mimicks the fact that PHP doesn't throw exceptions.

If it were to be redesigned from scratch, I'd vote for custom-named methods (no more PHP mimicking) and we could do it the REST way, yes. And throw exceptions.

**Comment by PVince81** [comment]
ajax/delete.php is dead in 9.0. The web UI is using Webdav's DELETE method now.

Closing.
