### ISSUE TITLE
wrong manual version numbers in 8.1 server

### ISSUE THREAD

**Issue by carlaschroder** [owncloud/core#16002]
I have a test 8.1 alpha 2, and I noticed lots of links to documentation  incorporated throughout. Hurrah! Nice work. But, they point to the 8.0 manuals, so where does `go.php` get the oC version? Is that something I can fix?

![wrong-doc-links](https://cloud.githubusercontent.com/assets/8388387/7437496/b142be10-f00c-11e4-8e5a-148be4e4b11f.png)

**Comment by carlaschroder** [comment]
I'm pretty sure Morris told me long ago, but it's not in my notes. :scream_cat:

**Comment by LukasReschke** [comment]
Patch is at https://github.com/owncloud/core/pull/16015 :-)
