### ISSUE TITLE
PHP settings for installation

### ISSUE THREAD

**Issue by colmoneill** [owncloud/core#16006]
Installing ownCloud locally, I got prompted with this:
![screenshot from 2015-05-01 22 17 40](https://cloud.githubusercontent.com/assets/2122318/7438576/ce1ce57e-f066-11e4-9082-6e2bef713528.png)

Default ubuntu 14.04 
PHP 5.5.9-1ubuntu4.9 (cli) (built: Apr 17 2015 11:44:57)
Latest git master

**Comment by RealRancor** [comment]
Hi,

what problems do you have with following whats written in the boxes?

**Comment by karlitschek** [comment]
@LukasReschke @DeepDiver1975 is it possible to set this via ini_set instead of blocking the full owncloud setup? 
http://stackoverflow.com/questions/8229696/do-i-need-to-set-ini-set-default-charset-utf-8

**Comment by LukasReschke** [comment]
https://github.com/owncloud/core/pull/16020 should work in this case

**Comment by colmoneill** [comment]
Yes, I should have been more verbose, applying these settings is not a problem for me, it's more about pointing them out as possible enhancements to the install experience?

Thanks!

**Comment by RealRancor** [comment]
Mhhh, a short look into the PHP documentation how to set this settings should be enough from my PoV or what "more verbose" informations do you need?

**Comment by colmoneill** [comment]
Sorry, I'm causing confusion here; when I said "more verbose" I meant to say that *I should* have explained my initial concern in more detail, in a more verbose manor.

If these settings are normal, then no problem, and this issue can be closed;
It's just that I went though this installation with @jancborchardt and he seemed surprised by these  and asked me to report it to the core.

**Comment by RealRancor** [comment]
Ahh, sorry. Completely misunderstood that :/
