### ISSUE TITLE
Apps search should work across categories

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#16003]
Currently in the apps management, the search only works in the current category. However one of the most common usecases is to:
1. Open the apps mgmt
2. Wanting to enable a new app
3. Trying to find it through search

– which will not succeed because only the already enabled apps will be searched.

cc @icewind1991 would be a great enhancement. :)

**Comment by PVince81** [comment]
@DeepDiver1975 @Peter-Prochaska market stuff ?

**Comment by PVince81** [comment]
Apps section has changed and only shows disabled and enabled ones, no more app store apps. Closing.
