### ISSUE TITLE
Apps mgmt: add categories for »Recently updated« and »Most popular«

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#16004]
Similar to the site itself at https://apps.owncloud.com, it would be cool to have categories in the apps mgmt for »Recently updated« and »Most popular« apps.

@karlitschek @LukasReschke @DeepDiver1975

**Comment by PVince81** [comment]
@DeepDiver1975 @Peter-Prochaska idea for market ?

**Comment by PVince81** [comment]
Moved to https://github.com/owncloud/market/issues/203
