### ISSUE TITLE
Reconsider adding ob_end_clean() in remote.php for files app

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#16013]
@karlitschek has requested why we have an hard dependency on `output_buffering` set to `off` with ownCloud 8.1 – thus I investigated it a little bit.

This check has been introduced since [our documentation](https://doc.owncloud.org/server/7.0/admin_manual/configuration/big_file_upload_configuration.html#configuring-php), the [SabreDAV documentation](http://sabre.io/dav/large-files/) as well as @evert in https://github.com/fruux/sabre-dav/pull/331#issuecomment-16945953 claim that `output_buffering` should be disabled, without this PHP will return memory-related errors and we might effectively risk data loss or integrity loss issues. 

This indeed makes sense to me but we should reconsider if there is another way to address this issue, I stumbled upon [`ob_end_flush`](http://php.net/manual/en/function.ob-end-flush.php) and [`ob_end_clean`](http://php.net/manual/en/function.ob-end-clean.php) which we could just add to our [remote.php file of the files app](https://github.com/owncloud/core/blob/6528a17ea3c1f3ef81c463f6c84edaddad29e967/apps/files/appinfo/remote.php).

A little digging in our source showed me that @icewind1991 introduced this already once for stable45 in https://github.com/owncloud/core/pull/576 and it was indeed there until ownCloud 7 where @DeepDiver1975 removed it with https://github.com/owncloud/core/commit/79fc4f312604feb20f96378d052703ec4768ecad, the commit message states:

> Within OC:init() the minimum set of apps is loaded - which is filesystem, authentication and logging

This looks rather unrelated. @DeepDiver1975 do you remind why you removed it? I suspect you assumed that it was removed by mistake since the code was undocumented?

cc @evert I'd greatly appreciate if you can lend us your expertise once more on this. Just a short "yes that should work" or a "kittens will die – don't try it" would be a great guidance since you are obviously *the* SabreDAV expert :smile: 
cc @DeepDiver1975 @karlitschek

**Comment by LukasReschke** [comment]
(that said webservers that respect the `.htaccess` or our `.user.ini` are fine since we set this value ourselves)

**Comment by karlitschek** [comment]
I´m not arguing that output buffering should be disabled. Possible that this is a good idea. 
But we should at least first try to disable it automatically with ini_set before be block the complete owncloud. The default in most installations is output buffering on.
This means that owncloud will stop working for a huge number of users when upgrading to 8.1 
We can´t do this.

@LukasReschke Can you check if this is possible to disable it with ini_set and only block if this is not possible?
And even then we have to discuss if we a full block is really the bestfrom a user experience perspective or if the admin page is better

**Comment by LukasReschke** [comment]
Well - the way to go as described in the ticket is that @DeepDiver1975 and @icewind1991 explain the changes they did to the OB handling in remote.php - if it is as simple as re-adding it we can just re-add this...

**Comment by evert** [comment]
The reason output buffering needs to be off is simple. The purpose of the feature is to put the entire HTTP response into memory before sending it to the client.

So if your HTTP response is massive, the entire file goes into memory. This means if you have a big file, you can drag down an entire server.

Frankly it's completely baffling to me why anyone would pick it as the default setting, like ubuntu does. It should be treated as a bug.

**Comment by karlitschek** [comment]
@evert understood. Or we try to switch it off.
The UTF-8 ini_set PR worked brilliantly by the way.

**Comment by LukasReschke** [comment]
`output_buffering` cannot be set via `ini_set`. It is [`PHP_INI_PERDIR`](http://php.net/manual/en/configuration.changes.modes.php)

**Comment by DeepDiver1975** [comment]
> This looks rather unrelated. @DeepDiver1975 do you remind why you removed it? I suspect you assumed that it was removed by mistake since the code was undocumented?

:heavy_check_mark:  unrelated :question: 
:heavy_check_mark: no clue why I removed that
:heavy_check_mark: most probably by mistake

**Comment by LukasReschke** [comment]
Let's re-add this then and remove the check for now and hope it doesn't bite us at other places were we handle files stuff => https://github.com/owncloud/core/pull/16042
