### ISSUE TITLE
Consider workaround around always_populate_raw_post_data

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#16014]
@karlitschek has requested why we have an hard dependency on `always_populate_raw_post_data` set to `-1` with ownCloud 8.1 – thus I investigated a little bit.

As per https://www.bram.us/2014/10/26/php-5-6-automatically-populating-http_raw_post_data-is-deprecated-and-will-be-removed-in-a-future-version/ PHP 5.6 will throw the following notice in case a POST request using `application/json` as Content-Type is received. Notice that this itself is a completely valid request.

```
Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0
```

This breaks ownCloud in quite some cases were NOTICEs are sent back to the user, such as it is done in DEBUG mode and thus leading AJAX and other requests. This can be reproduced by creating the following file and requesting it via cURL `curl -X POST -H "Content-Type: application/json" -d "{foo: bar}" http://localhost/test.php`

```php
<?php

error_reporting(E_ALL | E_STRICT);
ini_set('display_errors', 1);
```

Will result in:

```
<br />
<b>Deprecated</b>:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in <b>Unknown</b> on line <b>0</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Unknown</b> on line <b>0</b><br />
```

What we can do here would be to modify our `error_reporting` setting in `base.php` from `error_reporting(E_ALL | E_STRICT);` to something like `error_reporting(E_ALL ^ E_DEPRECATED | E_STRICT);`. This would however only be working around ugly and buggy PHP behaviour and we would not get any other legitimate DEPRECATE notice anymore but this should usually not require the user to modify his PHP settings.

cc @karlitschek @DeepDiver1975

**Comment by karlitschek** [comment]
Yes. But this sounds like something we can leave on the admin page. So let´s first try to reconfigure php with ini_set and/or error_reporting. And only if this fails we should add a warning to the admin page.
@LukasReschke Can you look into that?

**Comment by LukasReschke** [comment]
We can't really use ini_set on this. PHP does not execute user-land code before this deprecation is thrown. What we can do is adjust the error_reporting and I'd strongly advise against yet another warning as users simply ignore it as we learned ;-)

**Comment by karlitschek** [comment]
agreed. let´s do that

**Comment by LukasReschke** [comment]
https://github.com/owncloud/core/pull/16050
