### ISSUE TITLE
MOD_X_ACCEL_REDIRECT stops working after upgrade from 7.0.4 to 8.0.3

### ISSUE THREAD

**Issue by ColinFinck** [owncloud/core#16022]
After upgrading from 7.0.4 to 8.0.3, my standard nginx MOD_X_ACCEL_REDIRECT configuration stopped working. The nginx error.log shows errors like:

2015/05/03 15:01:45 [error] 13096#0: *6 open() "/srv/www/public/srv/mydata/adminuser/files .....

For some reason, the document root /srv/www/public is now prepended to the data directory /srv/mydata. This wasn't the case previously.
I have updated nginx from 1.6.x to 1.8.0, but this didn't help either.

Excerpts from the configuration files:

**nginx site configuration**

        location ~ \.php(?:$|/) {
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                include fastcgi_params;
                fastcgi_param HTTPS on;
                fastcgi_param MOD_X_ACCEL_REDIRECT_ENABLED on;
                fastcgi_pass unix:/var/run/php5-fpm.sock;
        }

        location ^~ /owncloud/data {
                internal;
                alias /srv/mydata;
        }

**ownCloud config.php**

        'datadirectory' => '/srv/mydata',
        'overwriteprotocol' => 'https',
        'overwritewebroot' => '/owncloud',
        'overwrite.cli.url' => '/owncloud',

**Comment by RealRancor** [comment]
Will be fixed in OC 8.0.4: https://github.com/owncloud/core/pull/15287

**Comment by SergioBertolinSG** [comment]
Tested on stable8, working fine.
