### ISSUE TITLE
Allow for wider configuration of external storage

### ISSUE THREAD

**Issue by Aesculapius** [owncloud/core#16029]
As suggested in https://github.com/owncloud/core/issues/7234 https://github.com/owncloud/core/pull/15478 and https://github.com/owncloud/core/issues/15385 , there is a usecase where you'd like to have more control over the exact behavior of mounted external storage.

In my case, I'd like to offer a mount to incremental backups of the data share of a user. So having these folders either scanned into the database or synced to user's desktops is totally useless.

As mentioned in the above issues, fixing this by backend configuration is not preferable since it leaves no trail as to what current configuration for different directories is at the moment.
But I can imagine it to look something like this:

![Suggestion mock-up](https://arc.int32.nl/index.php/s/v2ypkmNT1wlFrxc/download)

As a suggestion done in one of the listed issues, this could probably be excluded from synchronization to desktops by using a special webdav parameter? I don't have any idea about the rest of implementation but luckily enough there are smarter people around ;-)

**Comment by Aesculapius** [comment]
Am I the only one who would find such functionality useful? Or am I posting in the wrong section or something?

**Comment by Xenopathic** [comment]
@Aesculapius well, in oC 8.1 we have some mount parameters, but AFAIK we still don't have client-don't-sync. That will be a fairly major feature - it involves cooperation of the client, the WebDAV connector and the external storage subsystem, which won't be an easy task. Not to mention of course that the external storage app is currently in a state of flux, with partial refactors happening every so often.

**Comment by Aesculapius** [comment]
What would be needed to get this on the roadmap? The usecase still exists...

**Comment by Xenopathic** [comment]
Closing in favour of #7234
