### ISSUE TITLE
Encryption UX Update

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#16021]
As of 8.1 there are new moving parts to enabling and configuring encryption. They are spread out and confusing, and need some quick cosmetic admin page changes to avoid creating MAJOR problems for support and pre-sales, and more importantly our customers.

We need to try to get this in for 8.1, as this is VERY confusing and a VERY tough UX.

The short term solution seems to be straight forward for 8.1 - we need to put these things together in the admin page.

Enable Server Side Encryption check box needs to be removed if there is no encryption module enabled. It just should not appear.
Once an encryption module is enabled, then (in the case of our app) the encryption relation configuration options appear on the server menu.
The first thing in the list is our "Recovery Key" option. This is still there even similar to how it is now. 

For the recovery key part, to the right, we need to explain why this is important and what the buttons do. 
"The recovery key is an extra encryption key that is used to encrypt files. It allows recovery of a user's files if the user forgets their password." Or something like that.

We also need the radio button to be named "Enable recovery key" and "Disable recovery key" so that the button functions are clear. 

the top check box is "enable server side encryption". We need text to describe that this is turning on / off encryption from that point forward. Something like:
"When checked, all user files uploaded to the server (new or updated) will be encrypted at rest. Files previously uploaded will not be encrypted unless they are updated by a user. 
When unchecked, all user files uploaded (new or upadted) to the server will be unencrypted. Files previously encrypted will not be unencrypted. For this reason, do not disable the ownCloud encryption module if you have previously encrypted files at any time on this server as the encrypted files will be become unreadable."

The multiple encryption popup is not an issue really, as it makes sense and will not show up in our stock system. 

Also needs documentation and a release note. @carlaschroder

**Comment by MTRichards** [comment]
@schiesbn @jnfrmarks @karlitschek @DeepDiver1975

**Comment by MorrisJobke** [comment]
ref #15988 #15669 #15987

**Comment by DeepDiver1975** [comment]
also relevant https://github.com/owncloud/core/pull/15880#discussion_r29266301

**Comment by jnfrmarks** [comment]
@SergioBertolinSG 

There are some UI changes coming for encryption.

**Comment by schiesbn** [comment]
@MTRichards all your comments are addressed with the merged pull request. Thanks for the valuable feedback! Fell free to checkout the latest master branch and give it a try.

There is only one point I want to question:

> Enable Server Side Encryption check box needs to be removed if there is no encryption module enabled. It just should not appear.

As a core feature I think it should be always visible. We also don't remove the ability to enable the share API if no app using the API is installed. 
If you enable encryption and no module is available you get this message: "No encryption module loaded, please load a encryption module in the app menu". It makes the feature more visible, gives some guidance for the admin how to get the encryption running and is consistent with other core features like the sharing API. So I would keep it always visible.

**Comment by MTRichards** [comment]
I see that. 

Can we update the message to say (one typo) "No encryption module loaded, please load an encryption module in the app menu."

**Comment by MorrisJobke** [comment]
> Can we update the message to say (one typo) "No encryption module loaded, please load an encryption module in the app menu."

Yes. I will do that.

**Comment by MorrisJobke** [comment]
Okay this is then the final PR to get this done: #16175

**Comment by schiesbn** [comment]
All suggestions are implemented in master

**Comment by jnfrmarks** [comment]
@schiesbn @MTRichards 

The new UI looks great! It's clean and easy to follow.  Thanks for making the change.
