### ISSUE TITLE
removing folders that have been shared by one from the personal cloud, also removes the folder in the store of the one who shared it

### ISSUE THREAD

**Issue by finius** [owncloud/core#16028]
In oc 8.0.2, when a user A shares a folder to user B, and user B renames the shared folder (link) of the folder -being shared to him using the web gui to remove it from his file list-, the rename didn't work, but the whole folder disappears in both accounts of user A and B!. However, the local data in the data directory is not touched and still present on the drive - but it doesn't seem to be in the database anymore. 
In fact, rescanning the data dir solves the visibility issue, but results in new replication problems:
The same rescanned folder is obviously seen as a new folder by owncloud which has manually to be shared again by user A. Since the folder didn't experience any name changes, it still has the same folder name, which results in name conflicts on the sync clients of user B because user B still got the old/first shared Folder that disappeared. So the new one is named with an Appendix of " (1)". Trying to rename this results in the above behaviour. 
So you are moving in a circle as long as you didn't delete all client syncs and start up a clean new connection/replication on all clients concerned.

**Comment by karlitschek** [comment]
Can you provide a full bug report as described here? https://github.com/owncloud/core/blob/master/CONTRIBUTING.md
Also a step by step description how to reproduce would be great.

**Comment by finius** [comment]
I must confess that I haven't been able to reproduce this with another user, so it's hard to provide this report. 
Maybe this was a single users situation. However, this user isn't a common user in several ways: He used to sync with the ownCloud client huge amounts of files (>200.000 files with more than 70GB) in a single sync process (which we changed some weeks ago - and the problems seems to have disappeared since then). He also used to have 3 clients (Windows and Mac) to sync his files. Futhermore he shared some the synced folders with other users who also use sync clients to sync these shared data.
Nevertheless we had some user complaints under the last time, because some users (old and new ones) got a message from their sync client if really all user content should be erased. When checking the web gui, it didn't show any content anymore. However, the data had still been in the users data dir on the server. After a rescan of the data dir, the data had been back into the ownCloud again. Unfortunately this had bad effects to the shares and the sync on each sync Client, which is very annoying. 
We as Administrator also face some strange behaviour of oc concerning the creation of new folders within the ownCloud data dir. Every now and then owncloud generates there new folders that are named as a GUID, but have in fact no real content (except the default content of the example folders of a newly created user). But in our Environment ownCloud is set up to create new user dirs with the SAMAccountName of the new user. So GUID folders may not be there as far as I understand it.

Generally, problems seem to increase the more we step forward in updating to newer ownCloud versions. IMHO the sanity of (an existing, to be updated) system decreases with every new version upgrade. (i.e. user compatibility issues of old users home dirs, when upgrading from oc7 to oc8. There may be set some more focus on a clean and seamless update of the already present data or configurations.

These are the ownCloud behaviours we face within our organisation. I know this might be not that helpful to solve any problem, but unfortunately it's all I can say about that. sorry!

**Comment by PVince81** [comment]
Please try again with 8.0.4 or 8.1.
A similar issue has been fixed there.

**Comment by DeepDiver1975** [comment]
> Please try again with 8.0.4 or 8.1.
> A similar issue has been fixed there.

@finius please verify - THX

**Comment by finius** [comment]
I haven't been able to reproduce it, so, it seems to be fixed. However, if it reoccurs I'll reopen this Case again

**Comment by DeepDiver1975** [comment]
> I haven't been able to reproduce it, so, it seems to be fixed. However, if it reoccurs I'm going to reopen this issue.

THX for getting back to us on this!
