### ISSUE TITLE
Deleting single files on fresh installation not possible ( Web Interface )

### ISSUE THREAD

**Issue by Jeahaha** [owncloud/core#16038]
Hello Folks, i've got the Problem that it is not possible to me, to delete single files using the web-interface.
Its running on Apache, on Windows 7 Pro.
I've Installed it several times. Today using the new 8.03, i didn't test older versions yet.

The Log shows errors in:
mappedlocal.php#289 
mappedlocal.php#275
lockingwrapper.php#140
mappedlocal.php#218
mappedlocal.php#289
mappedlocal.php#270
owncloud.php#48

Please help me

**Comment by karlitschek** [comment]
can you post a full bug report using this template please? https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by MorrisJobke** [comment]
> Its running on Apache, on Windows 7 Pro

Windows server is not a supported platform anymore :( https://doc.owncloud.org/server/8.0/admin_manual/release_notes.html#supported-platforms

**Comment by nickvergessen** [comment]
Please disable the files_locking app:
https://github.com/owncloud/core/issues/14513#issuecomment-76173623
