### ISSUE TITLE
LDAP wizard configuration: “Email field” should be filled in (given that at least one user has mail or mailPrimaryAddress set)

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16033]
## Steps to reproduce
1. In assisted mode configure a complete LDAP configuration using active directory.
2. Click on advanced tab
3. Open Special attributes

### Expected behaviour
“Email field” should be filled in.

### Actual behaviour
“Email field” is empty and there are at least one user that has mail. This wrong behaviour seems to appear only using Active Directory.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 alpha 2

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by karlitschek** [comment]
@blizzz

**Comment by blizzz** [comment]
Did you click on "Test Filter" on the user filter tab?

**Comment by davitol** [comment]
I've tried to reproduce again the bug, but i couldn't. Maybe it was something wrong with my configuration, now it seems to work perfect.

**Comment by blizzz** [comment]
ok, thanks for checking it again
