### ISSUE TITLE
owncloud Windows Client Randomly deleting files

### ISSUE THREAD

**Issue by thavincinew** [owncloud/core#16032]
Hi guys.

I would like to add that we also have these issues.
Randomly the windows client will remove entire collections of files.

We are not using mutiple sync clients. Latest version of windows client and owncloud server with mysql backend.

It seems files still exist on backend but all clients remove the files out of the blue.

We ran on owncloud version 7 something or another and the issue existed here as well.

Please advise what you need from me to have a look/advise.

**Comment by LukasReschke** [comment]
Please reopen your issue at https://github.com/owncloud/client and use the issue template: https://github.com/owncloud/client/blob/master/CONTRIBUTING.md
