### ISSUE TITLE
[user mgnt] add ellipsis to long group names in multiselect

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#16041]
![group dropdown](https://cloud.githubusercontent.com/assets/213943/7450668/dcfba53e-f247-11e4-9440-e5df2b94da7f.png)

Should we put an ellipse character at the end, it "looks broken" atm

--

I changed the label rule (`ul.multiselectoptions > li input[type="checkbox"] + label`) but it doesn't look good, because the overflow causes a higher line height somehow. 
```css
/* snip */
padding: 5px 5px 5px 27px;
box-sizing: border-box;
text-overflow: ellipsis;
overflow: hidden;
margin: 0 -27px;
```

![bildschirmfoto von 2015-05-04 13-28-58](https://cloud.githubusercontent.com/assets/245432/7452779/531b476e-f262-11e4-8be0-a8d975ec9313.png)
![bildschirmfoto von 2015-05-04 13-29-06](https://cloud.githubusercontent.com/assets/245432/7452780/54d41e6e-f262-11e4-9438-ccf2d0f9077f.png)

Ref https://github.com/owncloud/core/issues/15819#issuecomment-98632526 (and following comments)

**Comment by jancborchardt** [comment]
Maybe some bugfix you’d like to work on @raghunayyar @ChristophWurst @Henni @colmoneill @owncloud/designers?
