### ISSUE TITLE
.htaccess should not be in the sync-exclude.lst

### ISSUE THREAD

**Issue by aleishman01** [owncloud/core#16047]
I use ownCloud to synchronize website changes with a development server. I don't understand what the reason would be to exclude the .htaccess file.

**Comment by LukasReschke** [comment]
Blocked by https://github.com/owncloud/core/issues/13640 – once this is done we can somehow return the allowed paths to the client.

cc @DeepDiver1975 @danimo

**Comment by LukasReschke** [comment]
(Closing since the goal is pretty much the same in the end)
