### ISSUE TITLE
s3 external storage should use SSL/TLS by default

### ISSUE THREAD

**Issue by elad661** [owncloud/core#16055]
When adding external storage in the form of an s3 bucket, there's a little checkbox that says "use SSL". For user safety and security, this should be enabled by default.

**Comment by PVince81** [comment]
Makes sense. Set as junior job, should be an easy one.

**Comment by DeepDiver1975** [comment]
Secondary s3 storage integration just got move over to https://github.com/owncloud/files_external_s3.

Unfortunately GitHub does not allow to move issues. Please reopen the issue at https://github.com/owncloud/files_external_s3/issues
