### ISSUE TITLE
Unknown database type varchar requested

### ISSUE THREAD

**Issue by JanWelker** [owncloud/core#16051]
Upgrading to 8.0.3. does not start because of the following error:

./occ upgrade
Turned on maintenance mode
Unknown database type varchar  requested, OC\DB\OCSqlitePlatform may not support it.
Turned off maintenance mode
Update failed

**Comment by JanWelker** [comment]
This is related to a previous issue I filed:
https://github.com/owncloud/core/issues/14247


### Steps to reproduce
./occ upgrade

### Expected behaviour
Update should complete

### Actual behaviour
Update failed with message:
Unknown database type varchar requested, OC\DB\OCSqlitePlatform may not support it.

### Server configuration
Debian wheezy

Apache 2.2.22

OCSqlite

PHP 5.4.39

Owncloud 8.0.3


**List of activated apps:**
activity
calendar
contacts
documents
external
files
files_encryption
files_external
files_locking
files_pdfviewer
files_sharing
files_texteditor
files_trashbin
files_versions
files_videoviewer
firstrunwizard
gallery
provisioning_api
templateeditor
updater
user_external
user_ldap
user_webdavauth

**Comment by DeepDiver1975** [comment]
I guess we need a schema dump of your db.

**Comment by JanWelker** [comment]
@DeepDiver1975 here you go:

CREATE TABLE ` oc_roundcube `(` id `INTEGER PRIMARY KEY AUTOINCREMENT, ` oc_user `varchar (4096) NOT NULL DEFAULT '', ` mail_user `varchar (4096) NOT NULL DEFAULT '', `mail_password` varchar (4096) NOT NULL DEFAULT' ');
CREATE TABLE oc_appconfig (appid VARCHAR(32) DEFAULT '' NOT NULL, configkey VARCHAR(64) DEFAULT '' NOT NULL, configvalue CLOB DEFAULT NULL, PRIMARY KEY(appid, configkey));
CREATE TABLE oc_clndr_calendars (id INTEGER NOT NULL, userid VARCHAR(255) DEFAULT NULL COLLATE BINARY, displayname VARCHAR(100) DEFAULT NULL COLLATE BINARY, uri VARCHAR(255) DEFAULT NULL COLLATE BINARY, active INTEGER DEFAULT 1 NOT NULL, calendarcolor VARCHAR(10) DEFAULT NULL COLLATE BINARY, timezone CLOB DEFAULT NULL COLLATE BINARY, components VARCHAR(100) DEFAULT NULL COLLATE BINARY, "ctag" INTEGER UNSIGNED DEFAULT 0 NOT NULL, "calendarorder" INTEGER UNSIGNED DEFAULT 0 NOT NULL, PRIMARY KEY(id));
CREATE TABLE oc_clndr_objects (id INTEGER NOT NULL, startdate DATETIME DEFAULT '1970-01-01 00:00:00', enddate DATETIME DEFAULT '1970-01-01 00:00:00', summary VARCHAR(255) DEFAULT NULL COLLATE BINARY, calendardata CLOB DEFAULT NULL COLLATE BINARY, uri VARCHAR(255) DEFAULT NULL COLLATE BINARY, objecttype VARCHAR(40) DEFAULT '' NOT NULL COLLATE BINARY, "repeating" INTEGER DEFAULT 0, "lastmodified" INTEGER DEFAULT 0, "calendarid" INTEGER UNSIGNED DEFAULT 0 NOT NULL, PRIMARY KEY(id));
CREATE TABLE oc_clndr_repeat (id INTEGER NOT NULL, startdate DATETIME DEFAULT '1970-01-01 00:00:00', enddate DATETIME DEFAULT '1970-01-01 00:00:00', "eventid" INTEGER UNSIGNED DEFAULT 0 NOT NULL, "calid" INTEGER UNSIGNED DEFAULT 0 NOT NULL, PRIMARY KEY(id));
CREATE TABLE oc_clndr_share_calendar (active INTEGER DEFAULT 1 NOT NULL, owner VARCHAR(255) NOT NULL COLLATE BINARY, share VARCHAR(255) NOT NULL COLLATE BINARY, sharetype VARCHAR(6) NOT NULL COLLATE BINARY, "calendarid" BIGINT UNSIGNED DEFAULT 0 NOT NULL, "permissions" SMALLINT NOT NULL);
CREATE TABLE oc_clndr_share_event (owner VARCHAR(255) NOT NULL COLLATE BINARY, share VARCHAR(255) NOT NULL COLLATE BINARY, sharetype VARCHAR(6) NOT NULL COLLATE BINARY, "eventid" BIGINT UNSIGNED DEFAULT 0 NOT NULL, "permissions" SMALLINT NOT NULL);
CREATE TABLE oc_contacts_addressbooks (id INTEGER NOT NULL, displayname VARCHAR(255) DEFAULT NULL COLLATE BINARY, uri VARCHAR(200) DEFAULT NULL COLLATE BINARY, description VARCHAR(255) DEFAULT NULL COLLATE BINARY, active INTEGER DEFAULT 1 NOT NULL, userid VARCHAR(255) DEFAULT '' NOT NULL COLLATE BINARY, "ctag" INTEGER UNSIGNED DEFAULT 1 NOT NULL, PRIMARY KEY(id));
CREATE TABLE oc_contacts_cards (id INTEGER NOT NULL, fullname VARCHAR(255) DEFAULT NULL COLLATE BINARY, carddata CLOB DEFAULT NULL COLLATE BINARY, uri VARCHAR(200) DEFAULT NULL COLLATE BINARY, "addressbookid" INTEGER UNSIGNED DEFAULT 0 NOT NULL, "lastmodified" INTEGER UNSIGNED DEFAULT 0, PRIMARY KEY(id));
CREATE TABLE oc_contacts_cards_properties (id INTEGER NOT NULL, name VARCHAR(64) DEFAULT NULL COLLATE BINARY, value VARCHAR(255) DEFAULT NULL COLLATE BINARY, preferred INTEGER DEFAULT 1 NOT NULL, userid VARCHAR(255) DEFAULT '' NOT NULL COLLATE BINARY, "contactid" INTEGER UNSIGNED DEFAULT 0 NOT NULL, PRIMARY KEY(id));
CREATE TABLE oc_documents_invite (uid VARCHAR(64) DEFAULT NULL COLLATE BINARY, "es_id" VARCHAR(64) NOT NULL, "status" SMALLINT DEFAULT 0, "sent_on" INTEGER UNSIGNED DEFAULT 0);
CREATE TABLE oc_documents_member (member_id INTEGER NOT NULL, token VARCHAR(32) DEFAULT NULL COLLATE BINARY, uid VARCHAR(64) DEFAULT NULL COLLATE BINARY, color VARCHAR(32) DEFAULT NULL COLLATE BINARY, "es_id" VARCHAR(64) NOT NULL, "last_activity" INTEGER UNSIGNED DEFAULT NULL, "status" SMALLINT UNSIGNED DEFAULT 1 NOT NULL, "is_guest" SMALLINT UNSIGNED DEFAULT 0 NOT NULL, PRIMARY KEY(member_id));
CREATE TABLE oc_documents_op (seq INTEGER NOT NULL, "es_id" VARCHAR(64) NOT NULL, "opspec" CLOB DEFAULT NULL, "member" INTEGER UNSIGNED DEFAULT 1 NOT NULL, "optype" VARCHAR(64) DEFAULT NULL, PRIMARY KEY(seq));
CREATE TABLE oc_documents_revisions ("es_id" VARCHAR(64) NOT NULL, "save_hash" VARCHAR(128) NOT NULL, "file_id" VARCHAR(512) DEFAULT NULL, "seq_head" INTEGER UNSIGNED NOT NULL, "member_id" INTEGER UNSIGNED NOT NULL);
CREATE TABLE oc_documents_session ("es_id" VARCHAR(64) NOT NULL, "genesis_hash" VARCHAR(128) NOT NULL, "owner" VARCHAR(64) NOT NULL, "genesis_url" VARCHAR(512) DEFAULT NULL, "file_id" VARCHAR(512) DEFAULT NULL, PRIMARY KEY(es_id));
CREATE TABLE oc_file_map ("logic_path" VARCHAR(512) DEFAULT '' NOT NULL, "logic_path_hash" VARCHAR(32) DEFAULT '' NOT NULL, "physic_path" VARCHAR(512) DEFAULT '' NOT NULL, "physic_path_hash" VARCHAR(32) DEFAULT '' NOT NULL, PRIMARY KEY("logic_path_hash"));
CREATE TABLE oc_filecache (fileid INTEGER NOT NULL, storage INTEGER DEFAULT 0 NOT NULL, parent INTEGER DEFAULT 0 NOT NULL, name VARCHAR(250) DEFAULT NULL COLLATE BINARY, mimetype INTEGER DEFAULT 0 NOT NULL, mimepart INTEGER DEFAULT 0 NOT NULL, mtime INTEGER DEFAULT 0 NOT NULL, encrypted INTEGER DEFAULT 0 NOT NULL, path_hash VARCHAR(32) DEFAULT '' NOT NULL COLLATE BINARY, etag VARCHAR(40) DEFAULT NULL COLLATE BINARY, storage_mtime INTEGER DEFAULT 0 NOT NULL, path VARCHAR(4000) DEFAULT NULL COLLATE BINARY, permissions INTEGER DEFAULT 0, "size" BIGINT DEFAULT 0 NOT NULL, "unencrypted_size" BIGINT DEFAULT 0 NOT NULL, PRIMARY KEY(fileid));
CREATE TABLE oc_files_trash (id VARCHAR(250) DEFAULT '' NOT NULL, user VARCHAR(64) DEFAULT '' NOT NULL, timestamp VARCHAR(12) DEFAULT '' NOT NULL, location VARCHAR(512) DEFAULT '' NOT NULL, "type" VARCHAR(4) DEFAULT NULL, "mime" VARCHAR(255) DEFAULT NULL, "auto_id" INTEGER NOT NULL, PRIMARY KEY("auto_id"));
CREATE TABLE oc_gallery_sharing (gallery_id INTEGER DEFAULT 0 NOT NULL, token VARCHAR(64) NOT NULL, "recursive" INTEGER NOT NULL);
CREATE TABLE oc_group_admin ("gid" VARCHAR(64) DEFAULT '' NOT NULL, "uid" VARCHAR(64) DEFAULT '' NOT NULL, PRIMARY KEY("gid", "uid"));
CREATE TABLE oc_group_user ("gid" VARCHAR(64) DEFAULT '' NOT NULL, "uid" VARCHAR(64) DEFAULT '' NOT NULL, PRIMARY KEY("gid", "uid"));
CREATE TABLE oc_groups ("gid" VARCHAR(64) DEFAULT '' NOT NULL, PRIMARY KEY("gid"));
CREATE TABLE oc_jobs ("id" INTEGER NOT NULL, class VARCHAR(255) DEFAULT '' NOT NULL, argument VARCHAR(256) DEFAULT '' NOT NULL, last_run INTEGER DEFAULT 0, PRIMARY KEY("id"));
CREATE TABLE oc_locks (id INTEGER NOT NULL, userid VARCHAR(64) DEFAULT NULL COLLATE BINARY, owner VARCHAR(100) DEFAULT NULL COLLATE BINARY, token VARCHAR(100) DEFAULT NULL COLLATE BINARY, uri CLOB DEFAULT NULL COLLATE BINARY, "created" BIGINT DEFAULT NULL, "scope" SMALLINT DEFAULT NULL, "depth" SMALLINT DEFAULT NULL, "timeout" INTEGER UNSIGNED DEFAULT NULL, PRIMARY KEY(id));
CREATE TABLE "oc_lucene_status" ("fileid" INTEGER DEFAULT 0 NOT NULL, "status" VARCHAR(1));
CREATE TABLE "oc_media_albums" ("album_id" INTEGER PRIMARY KEY AUTOINCREMENT, "album_name" VARCHAR(200) DEFAULT ' ' NOT NULL, "album_artist" INTEGER DEFAULT 0 NOT NULL, "album_art" VARCHAR(200));
CREATE TABLE "oc_media_artists" ("artist_id" INTEGER PRIMARY KEY AUTOINCREMENT, "artist_name" VARCHAR(200) DEFAULT ' ' NOT NULL);
CREATE TABLE "oc_media_sessions" ("session_id" INTEGER PRIMARY KEY AUTOINCREMENT, "token" VARCHAR(64) DEFAULT ' ' NOT NULL, "user_id" VARCHAR(64) DEFAULT ' ' NOT NULL, "start" DATETIME DEFAULT '1970-01-01 00:00:00' NOT NULL);
CREATE TABLE "oc_media_songs" ("song_id" INTEGER PRIMARY KEY AUTOINCREMENT, "song_name" VARCHAR(200) DEFAULT ' ' NOT NULL, "song_artist" INTEGER DEFAULT 0 NOT NULL, "song_album" INTEGER DEFAULT 0 NOT NULL, "song_path" VARCHAR(200) DEFAULT ' ' NOT NULL, "song_user" VARCHAR(64) DEFAULT '0' NOT NULL, "song_length" INTEGER DEFAULT 0 NOT NULL, "song_track" INTEGER DEFAULT 0 NOT NULL, "song_size" INTEGER DEFAULT 0 NOT NULL, "song_playcount" INTEGER DEFAULT 0 NOT NULL, "song_lastplayed" INTEGER DEFAULT 0 NOT NULL);
CREATE TABLE "oc_media_users" ("user_id" VARCHAR(64) DEFAULT '0' NOT NULL, "user_password_sha256" VARCHAR(64) DEFAULT ' ' NOT NULL);
CREATE TABLE oc_mimetypes ("id" INTEGER NOT NULL, "mimetype" VARCHAR(255) DEFAULT '' NOT NULL, PRIMARY KEY("id"));
CREATE TABLE oc_permissions (fileid INTEGER DEFAULT 0 NOT NULL, permissions INTEGER DEFAULT 0 NOT NULL, "user" VARCHAR(64) DEFAULT NULL);
CREATE TABLE oc_pictures_images_cache ("uid_owner" VARCHAR(64) NOT NULL, "path" VARCHAR(256) NOT NULL, "width" INTEGER NOT NULL, "height" INTEGER NOT NULL);
CREATE TABLE oc_preferences (configvalue CLOB DEFAULT NULL, "userid" VARCHAR(64) DEFAULT '' NOT NULL, "appid" VARCHAR(32) DEFAULT '' NOT NULL, "configkey" VARCHAR(64) DEFAULT '' NOT NULL, PRIMARY KEY("userid", "appid", "configkey"));
CREATE TABLE oc_privatedata ("keyid" INTEGER NOT NULL, app VARCHAR(255) DEFAULT '' NOT NULL, "key" VARCHAR(255) DEFAULT '' NOT NULL, value VARCHAR(255) DEFAULT '' NOT NULL, user VARCHAR(64) DEFAULT '' NOT NULL, PRIMARY KEY("keyid"));
CREATE TABLE oc_properties (id INTEGER NOT NULL, userid VARCHAR(64) DEFAULT '' NOT NULL COLLATE BINARY, propertypath VARCHAR(255) DEFAULT '' NOT NULL COLLATE BINARY, propertyname VARCHAR(255) DEFAULT '' NOT NULL COLLATE BINARY, "propertyvalue" VARCHAR(255) NOT NULL, PRIMARY KEY(id));
CREATE TABLE "oc_queuedtasks" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "app" VARCHAR(255) DEFAULT ' ' NOT NULL, "klass" VARCHAR(255) DEFAULT ' ' NOT NULL, "method" VARCHAR(255) DEFAULT ' ' NOT NULL, "parameters" VARCHAR(255) DEFAULT ' ' NOT NULL);
CREATE TABLE oc_share (id INTEGER NOT NULL, share_with VARCHAR(255) DEFAULT NULL COLLATE BINARY, item_source VARCHAR(255) DEFAULT NULL COLLATE BINARY, item_target VARCHAR(255) DEFAULT NULL COLLATE BINARY, file_target VARCHAR(512) DEFAULT NULL COLLATE BINARY, expiration DATETIME DEFAULT NULL, token VARCHAR(32) DEFAULT NULL COLLATE BINARY, item_type VARCHAR(64) DEFAULT '' NOT NULL COLLATE BINARY, parent INTEGER DEFAULT NULL, file_source INTEGER DEFAULT NULL, uid_owner VARCHAR(64) DEFAULT '' NOT NULL COLLATE BINARY, "share_type" SMALLINT DEFAULT 0 NOT NULL, "permissions" SMALLINT DEFAULT 0 NOT NULL, "stime" BIGINT DEFAULT 0 NOT NULL, "accepted" SMALLINT DEFAULT 0 NOT NULL, "mail_send" SMALLINT DEFAULT 0 NOT NULL, PRIMARY KEY(id));
CREATE TABLE oc_share_external (id INTEGER NOT NULL, accepted INTEGER DEFAULT 0 NOT NULL, "remote" VARCHAR(512) NOT NULL, "share_token" VARCHAR(64) NOT NULL, "password" VARCHAR(64) DEFAULT NULL, "name" VARCHAR(64) NOT NULL, "owner" VARCHAR(64) NOT NULL, "user" VARCHAR(64) NOT NULL, "mountpoint" VARCHAR(4000) NOT NULL, "mountpoint_hash" VARCHAR(32) NOT NULL, "remote_id" INTEGER DEFAULT -1 NOT NULL, PRIMARY KEY(id));
CREATE TABLE oc_storages ("numeric_id" INTEGER NOT NULL, id VARCHAR(64) DEFAULT NULL, PRIMARY KEY("numeric_id"));
CREATE TABLE oc_users (displayname VARCHAR(64) DEFAULT NULL, "uid" VARCHAR(64) DEFAULT '' NOT NULL, "password" VARCHAR(255) DEFAULT '' NOT NULL, PRIMARY KEY("uid"));
CREATE TABLE oc_vcategory ("id" INTEGER NOT NULL, uid VARCHAR(64) DEFAULT '' NOT NULL, type VARCHAR(64) DEFAULT '' NOT NULL, category VARCHAR(255) DEFAULT '' NOT NULL, PRIMARY KEY("id"));
CREATE TABLE oc_vcategory_to_object (type VARCHAR(64) DEFAULT '' NOT NULL COLLATE BINARY, objid INTEGER UNSIGNED DEFAULT 0 NOT NULL, categoryid INTEGER UNSIGNED DEFAULT 0 NOT NULL, PRIMARY KEY("categoryid", "objid", "type"));
CREATE INDEX album_artist_index ON "oc_media_albums" (album_artist ASC);
CREATE INDEX album_name_index ON "oc_media_albums" (album_name ASC);
CREATE INDEX appconfig_appid_key ON oc_appconfig ("appid");
CREATE INDEX appconfig_config_key_index ON oc_appconfig (configkey);
CREATE UNIQUE INDEX artist_name ON "oc_media_artists" (artist_name ASC);
CREATE INDEX c_addressbook_userid_index ON oc_contacts_addressbooks (userid);
CREATE INDEX c_addressbookid_index ON oc_contacts_cards (addressbookid);
CREATE INDEX category_index ON oc_vcategory (category);
CREATE INDEX cp_contactid_index ON oc_contacts_cards_properties (contactid);
CREATE INDEX cp_name_index ON oc_contacts_cards_properties (name);
CREATE INDEX cp_value_index ON oc_contacts_cards_properties (value);
CREATE UNIQUE INDEX documents_op_eis_idx ON oc_documents_op (es_id, seq);
CREATE UNIQUE INDEX documents_rev_eis_idx ON oc_documents_revisions (es_id, seq_head);
CREATE UNIQUE INDEX file_map_pp_index ON "oc_file_map" (physic_path_hash);
CREATE INDEX file_source_index ON oc_share (file_source);
CREATE INDEX fs_parent_name_hash ON oc_filecache (parent, name);
CREATE INDEX fs_storage_mimepart ON oc_filecache (storage, mimepart);
CREATE INDEX fs_storage_mimetype ON oc_filecache (storage, mimetype);
CREATE UNIQUE INDEX fs_storage_path_hash ON oc_filecache (storage, path_hash);
CREATE INDEX fs_storage_size ON oc_filecache (storage, size, fileid);
CREATE INDEX group_admin_uid ON "oc_group_admin" (uid);
CREATE INDEX id_index ON oc_files_trash (id);
CREATE INDEX id_user_index ON "oc_permissions" ("fileid", "user");
CREATE INDEX item_share_type_index ON oc_share (item_type, share_type);
CREATE INDEX job_class_index ON oc_jobs (class);
CREATE UNIQUE INDEX mimetype_id_index ON "oc_mimetypes" (mimetype);
CREATE INDEX property_index ON oc_properties (userid);
CREATE UNIQUE INDEX sh_external_mp ON oc_share_external (user, mountpoint_hash);
CREATE INDEX sh_external_user ON oc_share_external (user);
CREATE INDEX song_album_index ON "oc_media_songs" (song_album ASC);
CREATE INDEX song_artist_index ON "oc_media_songs" (song_artist ASC);
CREATE INDEX song_name_index ON "oc_media_songs" (song_name ASC);
CREATE INDEX status_index ON "oc_lucene_status" (status ASC);
CREATE UNIQUE INDEX storages_id_index ON "oc_storages" (id);
CREATE INDEX timestamp_index ON oc_files_trash (timestamp);
CREATE INDEX token_index ON oc_share (token);
CREATE INDEX type_index ON oc_vcategory (type);
CREATE INDEX uid_index ON oc_vcategory (uid);
CREATE INDEX user_index ON oc_files_trash (user);
CREATE INDEX vcategory_objectd_index ON oc_vcategory_to_object (objid, type);

**Comment by cunningwasabi** [comment]
its because of your roundcube table in the owncloud database. it happens to me after most updates.
drop the table, upgrade the database, add the table again.
i've pretty much given up on the roundcube integration side. its caused the whole of owncloud to fail, when its really only a side benefit.

**Comment by nickvergessen** [comment]
@cunningwasabi are we talking about https://github.com/spali/owncloud-app-roundcube ?

**Comment by JanWelker** [comment]
Jip it's a roundcube table problem. I deleted the unused ` oc_roundcube ` table. And the update finished without problems.

Thanks for you help,
Jan

**Comment by cunningwasabi** [comment]
@nickvergessen yeh, although thats the more updated variety. the owncloud/roundcube integration app I have requires a specific table to be inserted into the owncloud database/

If its useful, these were my notes:

# backup database
cp -f owncloud.db owncloud.db.bak

# remove offending table
sqlite3 owncloud.db
DROP TABLE `*OC_DB_PREFIX*roundcube`;

# do the owncloud update
cd /var/www/html/owncloud/
./occ upgrade

# add table back in
sqlite3 owncloud.db
CREATE TABLE IF NOT EXISTS `*OC_DB_PREFIX*roundcube` (
 `id` INTEGER PRIMARY KEY AUTOINCREMENT,
 `oc_user` varchar (4096) NOT NULL DEFAULT '',
 `mail_user` varchar (4096) NOT NULL DEFAULT '',
 `mail_password` varchar (4096) NOT NULL DEFAULT''
 );
.tables

## use at your own risk. may contain traces of nuts.

**Comment by mehturt** [comment]
Sorry guys, I have a similar problem, although the offending database type is not listed in my case ("Unknown database type  requested, OC\DB\OCSqlitePlatform may not support it.").  Should I file a separate bug? Thanks.

**Comment by nickvergessen** [comment]
Updating via the web UI: roundcube app gets disabled

Also the cli update works fine for me:
```
$ ./occ upgrade
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Turned off maintenance mode
Update successful
```

which version of the app do you have installed?

**Comment by cunningwasabi** [comment]
@nickvergessen : version is 2.5.4
not sure what your first statement re the web UI is trying to say: looks like another issue.
re the cli update working, i presume you actually have integrated the roundcube component into the owncloud database schema? the roundcube app isnt breaking as such, its the owncloud updater that isnt able to cope with the unusual database schema.
thats my 2c anyway.

**Comment by cunningwasabi** [comment]
update: installed 2.6, dropped the roundcube table from the owncloud database, configured the app & tried again. 
the roundcube integration via the owncloud log in seems to work seamlessly.
happy days.. hurrah!

**Comment by nickvergessen** [comment]
I used version 2.5.1 of the app. ownCloud disables it and the update works just fine without removing a table manually or whatever. Please report back if the issue happens for you in a future version.
