### ISSUE TITLE
HHVM segfault via simplexml_load_file()

### ISSUE THREAD

**Issue by bantu** [owncloud/core#16056]
```
hhvm /usr/local/bin/phpunit --configuration phpunit-autotest.xml --tap --filter OC\\\\AppFramework\\\\AppTest
TAP version 13
ok 1 - OC\AppFramework\AppTest::testControllerNameAndMethodAreBeingPassed
Core dumped: Segmentation fault
Stack trace in /tmp/stacktrace.10181.log
Segmentation fault
```

```
#0  simplexml_load_file(/appinfo/info.xml) called at [lib/private/appframework/app.php:54]
```
This means `OC_App::getAppPath($appId)` returns an empty string (or something equivalent) in
https://github.com/owncloud/core/blob/master/lib/private/appframework/app.php#L52 which is suspicious. The root cause for the segfault is probably simpleXML not handling non-existing files properly.

**Comment by DeepDiver1975** [comment]
> https://github.com/owncloud/core/blob/master/lib/private/appframework/app.php#L52 which is suspicious.

Having a file_exists call seems a legitimate workaround - @bantu can you please submit a PR? THX

**Comment by bantu** [comment]
@DeepDiver1975 Yes and no. getAppPath() may return false, see https://github.com/owncloud/core/blob/master/lib/private/app.php#L561. There is no check for false, see https://github.com/owncloud/core/blob/master/lib/private/appframework/app.php#L52.

**Comment by bantu** [comment]
cc @Raydiation

**Comment by DeepDiver1975** [comment]
> Yes and no. getAppPath() may return false

feel free to check for false in addition :speak_no_evil:

**Comment by bantu** [comment]
These statements all do not check the return value of getAppPath(). Instead, all checks are implicit, e.g. because is_file(''/appinfo/info.xml') usually returns false because /appinfo/info.xml does not exist on the filesystem. This however is a coincidence and overall this is rather bad programming.
https://github.com/owncloud/core/blob/master/lib/private/app.php#L1153
https://github.com/owncloud/core/blob/master/lib/private/app.php#L1160
https://github.com/owncloud/core/blob/master/lib/private/app.php#L115
https://github.com/owncloud/core/blob/master/lib/private/app.php#L386
https://github.com/owncloud/core/blob/master/lib/private/app.php#L647

**Comment by bantu** [comment]
Made a new ticket for that, so this ticket can be about the HHVM segfault. #16118
