### ISSUE TITLE
occ upgrade - 'ownCloud is already latest version' exit code

### ISSUE THREAD

**Issue by pierreozoux** [owncloud/core#16068]
When you use `occ` little handy scritp (this is great!), I believe that if owncloud it is at the `latest version`, it should't exit 3. It is not an error for me, so it should exit 0.

What do you think?

If not, people like me need to do aweful stuff like this:
https://github.com/IndiePaaS/IndiePaaS/blob/master/dockerfiles/services/owncloud/startup-owncloud.sh#L14

(Which I just discover is wrong because, next time there is a real update, my code will fail :/ )

Thanks!

**Comment by pierreozoux** [comment]
The line of code is here: https://github.com/owncloud/core/blob/055c18a7b40135465d00932711dadebac147461c/core/command/upgrade.php#L167

But I don't know what to put instead :/

**Comment by karlitschek** [comment]
Can you post a full bug report using the template please?

**Comment by DeepDiver1975** [comment]
> Can you post a full bug report using the template please?

I don't think we need any further information - we did discus this already somewhere in another issue.

We use different error codes for the different results of execution of this command.

I understand the request to have a clean error feedback for scripting .... we need to think about how to do this properly -> 8.2

**Comment by pierreozoux** [comment]
@karlitschek yes, sorry.

I actually just noticed it is a duplicate of https://github.com/owncloud/core/issues/15795

**Comment by PVince81** [comment]
The advantage of having 3 is being able to detect that no upgrade has happened at all. Unless this can be detected by grepping the output ?

**Comment by cmonteroluque** [comment]
This issue will fall off 8.2 if not resolved by 6 Oct

**Comment by ypid** [comment]
I am also very interested in a clean interface as I make heavy use of `occ` in the [debops.owncloud](https://github.com/debops/ansible-owncloud) Ansible role. Currently, I also need to do [not so nice stuff](https://github.com/debops/ansible-owncloud/blob/64dff5c7da53494e72e4e914e657622c31e01541/tasks/configure_owncloud.yml#L134-L136) to get idempotent in Ansible.

There are two solutions I can think of:

1. Add the `--output` switch to all options and give useful information when called for example with: `--output=json`.
   The information I would need is if the command changed anything (was the app already enabled or did the command just enable it) and if it was successful.

2.  Return with non-zero error code when a failure occurred. Use a constant string in either stdout or stderr with a hint that no changes did need to be made.

I would prefer the first option.

**Comment by PVince81** [comment]
PR welcome for having an exit code for "ownCloud is already latest version"
