### ISSUE TITLE
Versions is not creating new versions.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16061]
### Steps to reproduce

1. Create a text file.
2. Edit it several times.
3. Click on the versions button to open the dropdown.

### Expected behaviour
File has versions.

### Actual behaviour
There are no versions of the file.

Please note that only happens with encryption deactivated. With encryption enabled it is working fine.

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.4","versionstring":"8.1 alpha 3","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in community edition.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** 
no

### Client configuration

**browser**
Chrome 41

**Operating system**
Mac OS X

**Comment by nickvergessen** [comment]
This also works for me, so maybe there is another problem in your instance in regards to encryption:
https://github.com/owncloud/core/issues/16062

Please check the log here aswell and retry on a new empty install.

**Comment by SergioBertolinSG** [comment]
logs seen when adding a new version of a file:
```
{"reqId":"CJvILeevwu5OM3wWZD5r","remoteAddr":"172.16.101.5","app":"hook","message":"error while running hook (OCA\\Files_Versions\\Hooks::write_hook): Could not obtain lock type 2 on \"\/\".","level":3,"time":"2015-05-05T09:31:27+00:00"}
{"reqId":"8Y4HSTpZKZqU1NNRK7fs","remoteAddr":"172.16.101.5","app":"PHP","message":"Array to string conversion at \/srv\/www\/daily\/master\/owncloud\/lib\/private\/template\/functions.php#36","level":3,"time":"2015-05-05T09:31:38+00:00"}
```

**Comment by MorrisJobke** [comment]
@SergioBertolinSG It seems that files_locking is enabled. Can you confirm this? Does it work with disabled files_locking app?

**Comment by SergioBertolinSG** [comment]
Yes, disabling files_locking it works correctly.

**Comment by MorrisJobke** [comment]
> Yes, disabling files_locking it works correctly.

Then it's a files_locking problem -> close this.
