### ISSUE TITLE
Error updating to 8.0.3

### ISSUE THREAD

**Issue by Weuxel** [owncloud/core#16066]
Following error occurred while updating from 8.0.2 to 8.0.3:

An exception occurred while executing 'INSERT INTO `oc_oc_appconfig_ddhuh08rrueow` SELECT * FROM `oc_appconfig`': SQLSTATE[HY000]: General error: 1665 Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at least one table uses a storage engine limited to row-based logging. InnoDB is limited to row-logging when transaction isolation level is READ COMMITTED or READ UNCOMMITTED.

**Comment by RealRancor** [comment]
Dup of: https://github.com/owncloud/core/issues/16008
