### ISSUE TITLE
Third encryption module is ignored and used the second.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16071]
### Steps to reproduce
Having prepared an own encryption module
With the correct IDs and names for your custom module:
https://github.com/owncloud/apps/blob/master/encryption_dummy/lib/dummymodule.php#L36
https://github.com/owncloud/apps/blob/master/encryption_dummy/lib/dummymodule.php#L45
https://github.com/owncloud/apps/blob/master/encryption_dummy/appinfo/app.php#L4
https://github.com/owncloud/apps/blob/master/encryption_dummy/appinfo/info.xml

Custom module and the dummy encryption module should be enabled apps.

1. Enable encryption app.
2. Enable default encryption module (admin page).
3. Log out and log in again.
4. Upload some files. (Check files are encrypted at this point with default encryption module).
5. Change to second module (dummy).
6. Upload some files. (Check they are encrypted with dummy module, check header).
7. Change to third module (custom dummy).
8. Upload some files.

### Expected behaviour
Files are encrypted using custom dummy module (Third one in the list).

### Actual behaviour
Files are encrypted using dummy module (Second one in the list).

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.4","versionstring":"8.1 alpha 3","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in community edition. + Encryption + Dummy module + my own dummy module.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** 
yes

### Client configuration

**browser**
Chrome 41

**Operating system**
Mac OS X

**Comment by karlitschek** [comment]
@schiesbn

**Comment by schiesbn** [comment]
@SergioBertolinSG You need to make some additional changes to the dummy encryption module to get a proper second dummy module by mail. I just found it by trying it by my own.

**Comment by SergioBertolinSG** [comment]
Following @schiesbn advice:

It is working fine changing:
 - Filename in lib from dummymodule.php to the new name, e.g. dummymodule2.php 
 - Class name and namespace in that file.
-  app.php file replacing
$module = new \OCA\Encryption_Dummy\DummyModule();
with
$module = new \OCA\Encryption_Dummy_2\DummyModule2();
(given that the namespace of the second module is
"OCA\Encryption_Dummy_2" and the class is named "DummyModule2")
