### ISSUE TITLE
Switching databases in install dialog makes page jump

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#16079]
Switch from SQLite to either MySQL or PostgreSQL (opening extra db attributes) and observe the page jump.

From this:
![capture du 2015-05-03 20 38 42](https://cloud.githubusercontent.com/assets/925062/7478250/bc94c074-f359-11e4-9fb5-5ed87637dc76.png)
it jumps up to this:
![capture du 2015-05-03 20 39 00](https://cloud.githubusercontent.com/assets/925062/7478256/c345d28c-f359-11e4-9061-3037e58236cb.png)

**Comment by jancborchardt** [comment]
cc @owncloud/designers

**Comment by PVince81** [comment]
moved to more general UX group ticket: https://github.com/owncloud/core/issues/27578
