### ISSUE TITLE
»Can’t write into config directory« page just white, not using any template

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#16077]
When just opening the owncloud zip folder with a webserver (without having set any permissions) people are faced with this:
![owncloud-setup](https://cloud.githubusercontent.com/assets/925062/7478131/b59b090a-f358-11e4-84c5-027357f4c391.png)

Instead it should use the normal layout.guest.php template which other errors also use.

I’m also pretty sure this used to be different so marking it as regression.

**Comment by karlitschek** [comment]
I see the point. But using a template would require a working ownCloud which it isn´t. So no a lot we can do here. And this is only an error message anyways.
