### ISSUE TITLE
Versioned files restore without confirmation

### ISSUE THREAD

**Issue by dwt** [owncloud/core#16074]
I was quite shocked a few seconds ago that I accidentally restored an old version of a file, by misclicking. (I was faster than my browser and realized that I had clicked on the versions field for a fiel, wanted to select another file below that instead, only to have the versions popup shove the restore button for an old version under my curser.)

File gone, just like that.

Now I do have backups  - but I have to admit that I would have expected a confirmation dialog for such a potentially quite deadly (to files) operation.

**Comment by karlitschek** [comment]
Well the former current file that was overwritten by restoring ther older version should now be in the version history and can be restored by clicking on it in the versions drop down.
Can you try this please?
