### ISSUE TITLE
when file shared with user file edit right removed but still user can edit file at "All files" 

### ISSUE THREAD

**Issue by iliyasbasir** [owncloud/core#16088]
#### Expected behavior
If file shared with user without an edit permission user should not able to edit file at "All Files" tab

#### Actual Behavior
When admin share file with other user even tho edit permission removed user can edit file at "All files" location , if user go to "shared with you" user can not edit file

#### Step to reproduce
This test done at 8.0.2 & 8.0.3
1) shared file with other user without given edit rights ,
2) Login as user
3) hover over file been shared with user and see edit "pen" pop-up at "All files"
4) when go "Shared with you" hover -over file been shared NO edit "pen" pop-up
Note:  Please review screen shot

#### Server Configuration
Web (1 server): 
- Operating system - Red Hat Enterprise Linux Server 7.1 (Maipo)
- Web server - Apache 2.4.6 (Red Hat Enterprise Linux)
- PHP version - 5.4.16
- ownCloud version - 8.0.2

Backend (1 server):
- Operating system - Red Hat Enterprise Linux Server 7.1 (Maipo)
- Database - 5.5.41-MariaDB MariaDB Server (Red Hat Enterprise Linux)
- Storage backend - 2TB xfs mount

Client:
- Operating system - Windows 7 Enterprise 64 bit
- OS language - English(US)
- Installation path of client - c:\Program Files (x86)\ownCloud\
- Client version - 1.8.0 (build 4893)
- Client configuration - see link
- Client log- see link

#### Screen Shot

![permission](https://cloud.githubusercontent.com/assets/10195796/7482814/1eb5cea4-f348-11e4-957e-f757281a7afa.png)

![edit_1](https://cloud.githubusercontent.com/assets/10195796/7482818/252f5368-f348-11e4-878f-4ea8e8ed0b84.png)

![edit_2](https://cloud.githubusercontent.com/assets/10195796/7482819/2820aa9a-f348-11e4-81c8-4d708d47c81d.png)

![servlet](https://cloud.githubusercontent.com/assets/10195796/7482825/2d2aaa72-f348-11e4-9079-cefff428876d.png)

![sharedwithyou 2](https://cloud.githubusercontent.com/assets/10195796/7482827/305cbf64-f348-11e4-91a9-cbc885ca8438.png)

**Comment by DeepDiver1975** [comment]
file edit permission applies to the file content - not the file name.

I'm closing this as "works-as-designed"
