### ISSUE TITLE
Help section does not highlight current entry

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#16083]
I’m in the user documentation, but the entry is not highlighted:
![capture du 2015-05-03 20 50 54](https://cloud.githubusercontent.com/assets/925062/7478343/7673a136-f35a-11e4-8755-320f3984aa6f.png)

@DeepDiver1975

**Comment by LukasReschke** [comment]
That's something in the CSS that is broken, not a PHP issue. Plain CSS one.

![2015-05-12_12-16-52](https://cloud.githubusercontent.com/assets/878997/7584842/c8a683d8-f8a0-11e4-86c8-2f3bb86791fe.png)

Actually you were the one to break it :see_no_evil: – https://github.com/owncloud/core/commit/2e6a27614e8da443bd6b29fb2a3f4a64b274c2a0 see settings/css/settings.css L184

**Comment by LukasReschke** [comment]
Alternatively we can just switch to `active` here, see https://github.com/owncloud/core/pull/16271 for that.

**Comment by jancborchardt** [comment]
Hehe, yes. We never used »pressed« anywhere. ;D
