### ISSUE TITLE
Grammar needs improvement on caching message

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#16084]
### Steps to reproduce

1. Install 8.1

### Expected behaviour

Grammar correct in caching message

### Actual behaviour

Grammar is incorrect:

```
{"reqId":"\/yXkUIG47H6frNvaMsvB","remoteAddr":"","app":"PHP","message":"xcache_clear_cache(): Cache not exists at \/var\/www\/html\/owncloud\/lib\/private\/util.php#1357","level":3,"time":"2015-05-05T18:23:35+00:00"}

```

It should read:

```
Cache does not exist at 

```

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration:

ownCloud Enterprise Edition 8.1 alpha 3 (daily) Build:2015-05-05T03:08:44+00:00 fa6a67ccc1a7919aea2b18b445c0a31546184326

**Comment by LukasReschke** [comment]
The error message is generated by the PHP XCache module at https://github.com/owncloud/core/blob/952a90f2e3ab60252b125b3e68193cc4995c0c54/lib/private/util.php#L1357, we can't change the tet.

**Comment by LukasReschke** [comment]
That said probably we should not throw any error at all…

**Comment by DeepDiver1975** [comment]
won't fix for me -> closing
