### ISSUE TITLE
file icon disappear at "Shared with ..." location

### ISSUE THREAD

**Issue by iliyasbasir** [owncloud/core#16086]
#### Expected behavior
File icon not showing  up at "Shared with you" , "Shared with others" & "Shared by link" 

#### Actual Behavior
Icon should show up at all the place like it's showing up at "All files"

#### Step to reproduce
1) share file with user placed screen shot for more elaboration

#### Server configuration
Web (1 server): 
- Operating system - Red Hat Enterprise Linux Server 7.1 (Maipo)
- Web server - Apache 2.4.6 (Red Hat Enterprise Linux)
- PHP version - 5.4.16
- ownCloud version - 8.0.2

Backend (1 server):
- Operating system - Red Hat Enterprise Linux Server 7.1 (Maipo)
- Database - 5.5.41-MariaDB MariaDB Server (Red Hat Enterprise Linux)
- Storage backend - 2TB xfs mount

Client:
- Operating system - Windows 7 Enterprise 64 bit
- OS language - English(US)
- Installation path of client - c:\Program Files (x86)\ownCloud\
- Client version - 1.8.0 (build 4893)
- Client configuration - see link
- Client log- see link

Screen Shot
![icone_1](https://cloud.githubusercontent.com/assets/10195796/7482620/cb47e4ce-f346-11e4-801c-87f2d1c511c7.PNG)

![edit_2](https://cloud.githubusercontent.com/assets/10195796/7482618/c1b0e708-f346-11e4-8eab-255f679f9915.png)

![icone_2](https://cloud.githubusercontent.com/assets/10195796/7482624/cf999f54-f346-11e4-8a87-af7962c37dd7.PNG)

![icone_3](https://cloud.githubusercontent.com/assets/10195796/7482627/d456c972-f346-11e4-9dfd-e64a4fcfc834.PNG)

**Comment by DeepDiver1975** [comment]
@jancborchardt can I ask you to have a look? THX

**Comment by jancborchardt** [comment]
This is not a design issue but likely something with the Javascript. @PVince81 @MorrisJobke?

**Comment by MorrisJobke** [comment]
Fix is at #16127
