### ISSUE TITLE
stack on owncloud upgrade

### ISSUE THREAD

**Issue by sajushko** [owncloud/core#16087]
I am running owncloud v6 and I clicked on upgrade button in web interface. Upgrade process started and then it want to upgrade PHP to version 5.4. I don't have root access to server so I moved all data to another server with PHP 5.4. Now I get a welcome screen with message "ownCloud will be updated to version 8.0.2.". When I click on upgrade button I get message "Updates between multiple major versions are unsupported.". I dont have ssh access so I can't run manual upgrade. Any ideas how to upgrade?

**Comment by DeepDiver1975** [comment]
You have to first more to the latest version of oc7 before moving to OC8

**Comment by sajushko** [comment]
And how I do it? There is only one option...upgrade to 8.0.2.

**Comment by DeepDiver1975** [comment]
> And how I do it? There is only one option...upgrade to 8.0.2.

that's what docs are for https://doc.owncloud.org/server/8.0/admin_manual/maintenance/upgrade.html#upgrading-your-owncloud-server

**Comment by sajushko** [comment]
I already read all of this. Like I wrote in the first post I don't have access to command line on the server. Is there a way to cancel upgrade?

**Comment by DeepDiver1975** [comment]
I see - the updater pushed you from oc6 to oc8?

**Comment by sajushko** [comment]
Yes, updater pushed me from version 6.0.4.1 to version 8.0.2.

**Comment by DeepDiver1975** [comment]
too bad - this should never happen @karlitschek @VicDeo

**Comment by DeepDiver1975** [comment]
@sajushko to fix your installation: I assume you have at least ftp access?

If so I suggest to perform the following steps:
1. backup the whole owncloud folder
2. remove all sub folders with exception of config and data
3. upload the content of the latest oc7 release https://owncloud.org/changelog/ - scroll down to 7.0.5
4. perform upgrade via the browser
5. now use the updater app to move onwards to oc8

**Comment by VicDeo** [comment]
@DeepDiver1975 this check is already implemented for Updater shipped with OC8 https://github.com/owncloud/updater/pull/35

**Comment by DeepDiver1975** [comment]
@VicDeo nice - thx - but this only applies to 8.1 - any chance to make this available to stable7 and stable8? THX

**Comment by VicDeo** [comment]
@DeepDiver1975 not exact. It's implemented since OC8.0.0

**Comment by sajushko** [comment]
Thanks a lot DeepDiver1975. Your instructions works perfectly.
