### ISSUE TITLE
Problem installing with database having an IP6v address

### ISSUE THREAD

**Issue by gig13** [owncloud/core#16081]
**Expected behavior**
Install ownCloud with the autoconfig.php and/or install page and use a remote database with an IP6v address.

**Actual behavior**
The installation does not complete/fails.

**Steps to reproduce**
Setup the autoconfig.php with an IPv6 address OR input one in the installation section during install
Click install

**Server configuration**
Ubuntu 14.0.4
MySQL
OC8.0.2

No server logs created since ownCloud is not installed

**Comment by bboule** [comment]
@felixboehm can I ask you to work with @gig13 I put in backlog as this is so old it may just be a close out?

**Comment by felixboehm** [comment]
mysql supports IP v6, but needs to be configured to permit access.
https://dev.mysql.com/doc/refman/5.5/en/ipv6-support.html

After you permit access by IPv6 to the mysql server in general, you can provide the mysql root user to the autoconfig or occ maintenance:install, and ownCloud generates a user oc_admin. But IPv6 access for a mysql user needs to be granted explicit, which might fail here.

Please try to create a user oc_admin with IPv6 access and verify to be able to connect with 
``` mysql -h <remote-IPv6-address> -u oc_admin -p<secret-password>```

You should be able to install ownCloud with this user then.

**Comment by gig13** [comment]
Updated customer, to close since it is very old.
