### ISSUE TITLE
OC 8.0.3. update - oc_lucene_status / mysqlerr1093hack

### ISSUE THREAD

**Issue by rootrwx** [owncloud/core#16097]
The following exception occured while updateting from the latest OC version via the updater.

An exception occurred while executing ' DELETE FROM `oc_lucene_status` WHERE `fileid` IN ( SELECT `fileid` FROM ( SELECT `fileid` FROM `oc_lucene_status` GROUP BY `fileid` HAVING count(`fileid`) > 1 ) AS `mysqlerr1093hack` )': SQLSTATE[HY000]: General error: 1665 Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at least one table uses a storage engine limited to row-based logging. InnoDB is limited to row-logging when transaction isolation level is READ COMMITTED or READ UNCOMMITTED.

**Comment by rootrwx** [comment]
Its required to set 
binlog_format = ROW
in the my.cnf 

Then its possible to update successfull to 8.0.3.

**Comment by RealRancor** [comment]
Yes, also a dup of https://github.com/owncloud/core/issues/16066 , https://github.com/owncloud/core/issues/16063, https://github.com/owncloud/core/issues/16008, https://github.com/owncloud/core/issues/16089

**Comment by abou9al** [comment]
tanks @rootrwx it work for me :D
=> SET GLOBAL binlog_format = 'ROW';

**Comment by RealRancor** [comment]
Better use MIXED as stated in the issues above
