### ISSUE TITLE
Unable to open documents

### ISSUE THREAD

**Issue by binarykitchen** [owncloud/core#16094]
When I click on a ODT file in the document app, wait some seconds until the toolbar appears but still see a white, empty screen, and hit the close button, then an alert dialog appears, saying just this:

```
ASSERTION FAILED:
editorSession should exist here.
```

**Comment by RealRancor** [comment]
Hi,

the issue tracker of the documents app is located here:

https://github.com/owncloud/documents/issues

**Comment by binarykitchen** [comment]
ok, thx
