### ISSUE TITLE
Apps disabled but cannot enable

### ISSUE THREAD

**Issue by binarykitchen** [owncloud/core#16092]
After migrating from v7 to v8 I see that many apps are disabled. When I try to enable these, I see the warning `App directory already exists` and cannot enable it.

What can I do here?

**Comment by RealRancor** [comment]
Hi,

there is a closed issues about this available here. Normally this should be fixed in 8.0.3

**Comment by nickvergessen** [comment]
> there is a closed issues about this available here. Normally this should be fixed in 8.0.3

If not, feel free to reopen with reproduction steps (e.g. the exact names of the apps as well as the version that was installed before the update):
https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version

**Comment by binarykitchen** [comment]
Okay, here is more info:

* I'm running owncloud v8.0.3 on PHP 5.5.24 under Ubuntu 14.10
* Before the migration I had owncloud v7
* The app I was trying to enable is Contacts 8.0 (0.3.0.18)

How to reproduce:
1. Log into owncloud
2. Click on Apps +
3. Browse to Recommended
4. Enable the contacts app
5. A red warning appears saying "App directory already exists"

Unable to enable the contact app.

**Comment by binarykitchen** [comment]
PS: Same error happens with the Bookmarks 8.0 (0.4) app !!

**Comment by nickvergessen** [comment]
Well try going to the "not enabled" section and activate the app there.

The problem has been reported to:
Bookmarks: https://github.com/owncloud/bookmarks/issues/147
Calendar: https://github.com/owncloud/calendar/issues/784
Contacts: https://github.com/owncloud/contacts/issues/892
Search lucene: https://github.com/owncloud/search_lucene/issues/85
Documents: https://github.com/owncloud/documents/issues/479

If you experience the problem with other apps aswell, please report the issue there.

**Comment by binarykitchen** [comment]
yes, i still experience the same issue. will report on their repos now ...

**Comment by nickvergessen** [comment]
of course they still exist now, I just reported the issue hours ago... you will have to wait for the next release...
