### ISSUE TITLE
ownCloud filepicker does not resize according to window

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#16100]
1. Open an ownCloud file picker, e.g. the image picker in the personal settings (or the first run wizard)
2. Resize the window – this could also be when rotating a tablet from landscape to portrait
3. Observe the file picker not resizing and becoming unusable:
![capture du 2015-05-06 10 21 14](https://cloud.githubusercontent.com/assets/925062/7489692/d8f3dca2-f3d9-11e4-83f5-c2e67c89de83.png)

@schiesbn @MorrisJobke we need to adjust that library.

**Comment by MorrisJobke** [comment]
Fix is in #16104

**Comment by jancborchardt** [comment]
You’re the hero we deserve right now.
