### ISSUE TITLE
File picker needs a spinner while loading

### ISSUE THREAD

**Issue by Xenopathic** [owncloud/core#16105]
Ref: owncloud/mail#621

TL;DR: Confusion arises from the lack of feedback in the file picker, so we need a spinner.

> When adding an attachment, the file chooser dialog is initially displayed empty while the file list is fetched. During this time the user may think something is broken, or that they must click on Choose to choose a file (I certainly did... ref https://github.com/owncloud/mail/issues/620). We should have a spinner indicating the content is loading.

cc @jancborchardt

**Comment by jancborchardt** [comment]
cc @MorrisJobke if you’re up for it while working on the file picker. ;)
