### ISSUE TITLE
File picker »choose« button should be disabled when no file was chosen

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#16106]
Led to bugs such as https://github.com/owncloud/mail/issues/620

@MorrisJobke can you help? cc @Xenopathic

**Comment by sharidas** [comment]
Hi,

I am bit new to owncloud. I have cloned the base using command: 
`ocdev setup --dir /var/www/owncloud-core base`
I am able to view the UI ( I am in the initial step though: http://imgur.com/a/MEbDp
May I know how to reproduce this issue in my setup? Any helping hand would be appreciated.

Thanks,
Sujith H

**Comment by butonic** [comment]
@sharidas have a look at https://github.com/owncloud/mail/issues/620. The current behavior (the choose button is never disabled) may confuse users. The headline of the issue says what should be done: disable the choose button until a file is selected (and disable it if the last file was deselected)

hope this helps.
