### ISSUE TITLE
File picker does not have empty content message

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#16108]
When you enter an empty folder with the file picker, there is no message saying »No file here« like in the Files app.

That’s important feedback missing as one could think the folder simply does not load.

cc @owncloud/designers

**Comment by nickvergessen** [comment]
what's the easiest way to get to the file picker?

**Comment by LukasReschke** [comment]
> what's the easiest way to get to the file picker?

Avatar selector / Files_Drop folder selector

**Comment by MorrisJobke** [comment]
> what's the easiest way to get to the file picker?

WebDev console: `OC.dialogs.filepicker()`

**Comment by PVince81** [comment]
Moved to general design issues group ticket: https://github.com/owncloud/core/issues/27578
