### ISSUE TITLE
Cannot enable or disable apps having redis cache active

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#16113]
### Steps to reproduce
1. Setup and configure a redis server (installed php5-redis, redis-server, and redis-tools from ubuntu repos; default configuration)
2. Configure ownCloud to use redis

    ```
     'memcache.local' => '\OC\Memcache\redis',
  'redis' => array(
        'host' => 'localhost', // can also be a unix domain socket: '/tmp/redis.sock'
        'port' => 6379,
        'timeout' => 0.0,
        'dbindex' => 0, // Optional, if undefined SELECT will not run and will use Redis Server's default DB Index.
  ),

    ```

3. Disable an enabled app

### Expected behaviour
App is disabled correctly

### Actual behaviour
Errors are thrown. The CLI also crashes with the same error.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 alpha 3

**Updated from an older ownCloud or fresh install:** fresh install

#### Web server error log
```
[Wed May 06 12:19:27.697092 2015] [:error] [pid 12475] [client 10.40.30.21:57928] PHP   3. OC\\Route\\Router->match() /home/jvillafanez/src/owncloud/owncloud2/lib/base.php:858, referer: http://10.40.30.21:8120/index.php/settings/apps
[Wed May 06 12:19:27.697142 2015] [:error] [pid 12475] [client 10.40.30.21:57928] PHP   4. call_user_func() /home/jvillafanez/src/owncloud/owncloud2/lib/private/route/router.php:272, referer: http://10.40.30.21:8120/index.php/settings/apps
[Wed May 06 12:19:27.697176 2015] [:error] [pid 12475] [client 10.40.30.21:57928] PHP   5. __lambda_func() /home/jvillafanez/src/owncloud/owncloud2/lib/private/route/router.php:272, referer: http://10.40.30.21:8120/index.php/settings/apps
[Wed May 06 12:19:27.697211 2015] [:error] [pid 12475] [client 10.40.30.21:57928] PHP   6. require_once() /home/jvillafanez/src/owncloud/owncloud2/lib/private/route/route.php(153) : runtime-created function:1, referer: http://10.40.30.21:8120/index.php/settings/apps
[Wed May 06 12:19:27.697256 2015] [:error] [pid 12475] [client 10.40.30.21:57928] PHP   7. OC_App::disable() /home/jvillafanez/src/owncloud/owncloud2/settings/ajax/disableapp.php:34, referer: http://10.40.30.21:8120/index.php/settings/apps
[Wed May 06 12:19:27.697299 2015] [:error] [pid 12475] [client 10.40.30.21:57928] PHP   8. OC\\App\\AppManager->disableApp() /home/jvillafanez/src/owncloud/owncloud2/lib/private/app.php:357, referer: http://10.40.30.21:8120/index.php/settings/apps
[Wed May 06 12:19:27.697343 2015] [:error] [pid 12475] [client 10.40.30.21:57928] PHP   9. OC\\App\\AppManager->clearAppsCache() /home/jvillafanez/src/owncloud/owncloud2/lib/private/app/appmanager.php:200, referer: http://10.40.30.21:8120/index.php/settings/apps
[Wed May 06 12:19:27.697387 2015] [:error] [pid 12475] [client 10.40.30.21:57928] PHP  10. OC\\Memcache\\Redis->clear() /home/jvillafanez/src/owncloud/owncloud2/lib/private/app/appmanager.php:208, referer: http://10.40.30.21:8120/index.php/settings/apps

```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"kDNpZBjWan50YOa3MfmJ","remoteAddr":"","app":"PHP","message":"Undefined class constant 'OPT_SCAN' at \/home\/jvillafanez\/src\/owncloud\/owncloud2\/lib\/private\/memcache\/redis.php#105","level":3,"time":"2015-05-06T10:17:16+00:00"}
{"reqId":"E5lxaDKGR49NPXrY7\/kN","remoteAddr":"","app":"PHP","message":"Undefined class constant 'OPT_SCAN' at \/home\/jvillafanez\/src\/owncloud\/owncloud2\/lib\/private\/memcache\/redis.php#105","level":3,"time":"2015-05-06T10:18:59+00:00"}
{"reqId":"mmy08xkXUHo847TU2zOH","remoteAddr":"10.40.30.21","app":"PHP","message":"Undefined class constant 'OPT_SCAN' at \/home\/jvillafanez\/src\/owncloud\/owncloud2\/lib\/private\/memcache\/redis.php#105","level":3,"time":"2015-05-06T10:19:27+00:00"}

```

**Comment by nickvergessen** [comment]
Sounds like your redis version is outdated:
https://github.com/phpredis/phpredis/issues/466

**Comment by Xenopathic** [comment]
Should we do a sanity check to ensure the right version of phpredis is installed before using it as an available memcache?

**Comment by jvillafanez** [comment]
@nickvergessen it seems so: php5-redis version 2.2.4

Personally, I'd prefer ownCloud to use the lowest version possible from the supported distributions (in this case 2.2.4 or lower) to prevent this kind of situations, if possible.

**Comment by jvillafanez** [comment]
I think we'll need php 5.6 for this...

**Comment by jnfrmarks** [comment]
@nickvergessen @DeepDiver1975 

We do version checks with APCu.  Do we want to do the same here, as suggested  by @Xenopathic

**Comment by cmonteroluque** [comment]
We need a development decision regarding the versions we are going to need installed as prerequisites.

**Comment by rperezb** [comment]
Hey, do we know about the prerequisites? thx

**Comment by DeepDiver1975** [comment]
@nickvergessen can you please add a version check for redis? Code is kind of identical as with apcu - THX

**Comment by nickvergessen** [comment]
Fix: https://github.com/owncloud/core/pull/16687; Documentation: https://github.com/owncloud/documentation/issues/1180

**Comment by nickvergessen** [comment]
@jvillafanez if you need help to update your redis, see https://github.com/phpredis/phpredis/issues/466#issuecomment-106082212

**Comment by SergioBertolinSG** [comment]
I've set up a server using redis using this comment phpredis/phpredis#466 (comment). It has worked, but I find it very manual, annoying for the user. Are we using mandatory functionality of redis > 2.2.4 ?

**Comment by nickvergessen** [comment]
Yes, e.g. 
> Undefined class constant 'OPT_SCAN'

**Comment by HellScaryMan** [comment]
Version  ["redis_version"]=> "3.0.1" , but anyway if I trying enable or disable any module had same error

**Comment by jvillafanez** [comment]
@HellScaryMan I guess you're talking about the redis server version. The versions we're talking about are for the php-redis module (which can be found in https://pecl.php.net/package/redis).

You need to update the php-redis module (2.2.5 might be enough, but I guess it's better with 2.2.7) so ownCloud can work properly. I checked with the redis server version from the standard ubuntu repositories, without any problem.

**Comment by HellScaryMan** [comment]
@jvillafanez thank You, I solved the problem of flushing redis before pressing turn on or off the module
