### ISSUE TITLE
Return values of OC_App::getAppPath() are insufficiently checked

### ISSUE THREAD

**Issue by bantu** [owncloud/core#16118]
OC_App::getAppPath() may return false, but some (most?) values returned by that function are not checked against false.

Examples
https://github.com/owncloud/core/blob/master/lib/private/app.php#L1153
https://github.com/owncloud/core/blob/master/lib/private/app.php#L1160
https://github.com/owncloud/core/blob/master/lib/private/app.php#L115
https://github.com/owncloud/core/blob/master/lib/private/app.php#L386
https://github.com/owncloud/core/blob/master/lib/private/app.php#L647

These statements all do not check the return value of getAppPath(). Instead, all checks are implicit, e.g. because is_file(''/appinfo/info.xml') usually returns false because /appinfo/info.xml does not exist on the filesystem. This however is a coincidence and overall this is rather bad programming.

Discovered via #16056

**Comment by MorrisJobke** [comment]
Time for an exception rather than false/null/whatever ... cc @LukasReschke

**Comment by oparoz** [comment]
@DeepDiver1975 , @LukasReschke - When fixing this, please add it to OCP or the AppFramework. It seems app devs don't have a reliable way of getting the root folder of their app.

**Comment by Xenopathic** [comment]
:+1: @oparoz
