### ISSUE TITLE
owncloud upgrade error

### ISSUE THREAD

**Issue by UwRo** [owncloud/core#16123]
OS: Debian 7.8
MySQL: 5.1.66

root@cloud:/etc/apt/sources.list.d# cat owncloud.list
deb http://download.opensuse.org/repositories/isv:/ownCloud:/community/Debian_7.0/ /

Upgrade owncloud 8.0.2 ->8.0.3 produces errors: 

root@cloud:/var/www/owncloud# sudo -u www-data php occ upgrade
An unhandled exception has been thrown:
exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1598 Binary logging not possible. Message: Transaction level 'READ-COMMITTED' in InnoDB is not safe for binlog mode 'STATEMENT'' in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91
Stack trace:
#0 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(Array)
#1 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(989): Doctrine\DBAL\Driver\PDOStatement->execute(Array)
#2 /var/www/owncloud/lib/private/db/connection.php(132): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM oc_...', Array, Array)
#3 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(595): OC\DB\Connection->executeUpdate('DELETE FROM *PR...', Array, Array)
#4 /var/www/owncloud/lib/private/appconfig.php(220): Doctrine\DBAL\Connection->delete('*PREFIX*appconf...', Array)
#5 /var/www/owncloud/lib/private/allconfig.php(152): OC\AppConfig->deleteKey('core', 'cronErrors')
#6 /var/www/owncloud/lib/base.php(579): OC\AllConfig->deleteAppValue('core', 'cronErrors')
#7 /var/www/owncloud/lib/base.php(1026): OC::init()
#8 /var/www/owncloud/console.php(12): require_once('/var/www/ownclo...')
#9 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')
#10 {main}

Next exception 'Doctrine\DBAL\Driver\PDOException' with message 'SQLSTATE[HY000]: General error: 1598 Binary logging not possible. Message: Transaction level 'READ-COMMITTED' in InnoDB is not safe for binlog mode 'STATEMENT'' in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93
Stack trace:
#0 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(989): Doctrine\DBAL\Driver\PDOStatement->execute(Array)
#1 /var/www/owncloud/lib/private/db/connection.php(132): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM oc_...', Array, Array)
#2 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(595): OC\DB\Connection->executeUpdate('DELETE FROM *PR...', Array, Array)
#3 /var/www/owncloud/lib/private/appconfig.php(220): Doctrine\DBAL\Connection->delete('*PREFIX*appconf...', Array)
#4 /var/www/owncloud/lib/private/allconfig.php(152): OC\AppConfig->deleteKey('core', 'cronErrors')
#5 /var/www/owncloud/lib/base.php(579): OC\AllConfig->deleteAppValue('core', 'cronErrors')
#6 /var/www/owncloud/lib/base.php(1026): OC::init()
#7 /var/www/owncloud/console.php(12): require_once('/var/www/ownclo...')
#8 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')
#9 {main}

Next exception 'Doctrine\DBAL\Exception\DriverException' with message 'An exception occurred while executing 'DELETE FROM oc_appconfig WHERE appid = ? AND configkey = ?' with params ["core", "cronErrors"]:

SQLSTATE[HY000]: General error: 1598 Binary logging not possible. Message: Transaction level 'READ-COMMITTED' in InnoDB is not safe for binlog mode 'STATEMENT'' in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115
Stack trace:
#0 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'DELETE FROM oc_...', Array)
#2 /var/www/owncloud/lib/private/db/connection.php(132): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM oc_...', Array, Array)
#3 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(595): OC\DB\Connection->executeUpdate('DELETE FROM *PR...', Array, Array)
#4 /var/www/owncloud/lib/private/appconfig.php(220): Doctrine\DBAL\Connection->delete('*PREFIX*appconf...', Array)
#5 /var/www/owncloud/lib/private/allconfig.php(152): OC\AppConfig->deleteKey('core', 'cronErrors')
#6 /var/www/owncloud/lib/base.php(579): OC\AllConfig->deleteAppValue('core', 'cronErrors')
#7 /var/www/owncloud/lib/base.php(1026): OC::init()
#8 /var/www/owncloud/console.php(12): require_once('/var/www/ownclo...')
#9 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')
#10 {main}root@speicher:/var/www/owncloud# ^C

**Comment by nickvergessen** [comment]
Duplicate https://github.com/owncloud/core/issues/7769
