### ISSUE TITLE
LDAP wizard configuration: trash bin button behaviour can be improved

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16126]
## Steps to reproduce
1. Go to LDAP wizard configuration using active directory.
2. Click on the trash bin button to delete the current configuration
### Expected behaviour

If there is no configuration yet, maybe a message should be shown indicating that you can delete nothing because there is no configuration yet, or the trash bin button should be disabled
### Actual behaviour

The configuration is "deleted" and the number in the combobox that indicates the server id is +1
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 alpha 3

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by blizzz** [comment]
> If there is no configuration yet,  maybe a message should be shown indicating that you can delete nothing because there is no configuration yet, or the trash bin button should be disabled

There is always at least one configuration (the current). 

> the number in the combobox that indicates the server id is +1

This seems worth fixing.

**Comment by PVince81** [comment]
moved to grouped UX ticket: https://github.com/owncloud/user_ldap/issues/69
