### ISSUE TITLE
Update 8.0.2 to 8.0.3 with updated failed

### ISSUE THREAD

**Issue by FloR707** [owncloud/core#16131]
I used the webinstaller to install OC on my webhoster webspace. Today I got the notification that there is an update available. When I used update tool I ended up with this error when OC tried to configure the new version:
An exception occurred while executing 'INSERT INTO `oc_oc_appconfig_gx0h7n8hrn4n5` SELECT * FROM `oc_appconfig`': SQLSTATE[HY000]: General error: 1598 Binary logging not possible. Message: Transaction level 'READ-COMMITTED' in ocDB is not safe for binlog mode 'STATEMENT'

The mentioned table oc_oc_appconfig... exits but is empty. So I assume that the script is not capable of copying the oc_appconfig table to a temp table. I tried to do it manually but every time I start the update script a new temp table is created on the scripts stops.
Is there a work around? Can I create the temp table and force the update script to use it?

**Comment by RealRancor** [comment]
Dup of https://github.com/owncloud/core/issues/7769 , https://github.com/owncloud/core/issues/16123 , https://github.com/owncloud/core/issues/16089
