### ISSUE TITLE
owncloud syncing issue

### ISSUE THREAD

**Issue by pollend** [owncloud/core#16138]
i can't sync some of my files for some reason. I just have this error running down my log file. the client will fail and retry constantly and still fail.

```
Error	PHP	Undefined offset: 3 at /var/www/owncloud/lib/private/files/stream/dir.php#29	2015-05-07T05:27:22+00:00
Error	PHP	Undefined offset: 3 at /var/www/owncloud/lib/private/files/stream/dir.php#29	2015-05-07T05:26:18+00:00
Error	PHP	Undefined offset: 3 at /var/www/owncloud/lib/private/files/stream/dir.php#29	2015-05-07T05:25:14+00:00
Error	PHP	Undefined offset: 3 at /var/www/owncloud/lib/private/files/stream/dir.php#29	2015-05-07T05:24:12+00:00
Error	PHP	Undefined offset: 3 at /var/www/owncloud/lib/private/files/stream/dir.php#29	2015-05-07T05:23:05+00:00
Error	PHP	Undefined offset: 7 at /var/www/owncloud/lib/private/files/stream/dir.php#29	2015-05-07T05:22:48+00:00
Error	PHP	Undefined offset: 4 at /var/www/owncloud/lib/private/files/stream/dir.php#29	2015-05-07T05:22:48+00:00
```

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by 67jeffh** [comment]
I have the same error in my log file.

8.0.3

**Comment by MorrisJobke** [comment]
Weird. The index is just checked lines above this code: https://github.com/owncloud/core/blob/stable8/lib/private/files/stream/dir.php#L29

**Comment by PVince81** [comment]
Please try again with 8.1.3 or 8.2. If you're still having issues, please use the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by pollend** [comment]
I haven't been syncing really large files recently. I'll make another issue request if the issue comes up again.
