### ISSUE TITLE
Mobile version layer problem

### ISSUE THREAD

**Issue by alve89** [owncloud/core#16139]
I tried to open ownCloud with Safari on iOS but the users menu lays under the file-list. So I'm not able to access my users menu.

See attachment for better understanding (I pulled the file-list down to make the problem visible). 
![image](https://cloud.githubusercontent.com/assets/11487054/7509473/5cfaeb1e-f491-11e4-808a-726f836d1a9b.jpg)

**Comment by MorrisJobke** [comment]
Should be fixed with #16017. Please reopen if this still is an issue in 8.1. Thanks :)
