### ISSUE TITLE
Versions not created when updated via webdav

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#16130]
When updating a file via webdav there is no version created. So basically if the sync client is used no version history. 

Command used:

```curl -X PUT --header "Content-Type:application/octet-stream" --data-binary @foo.txt http://user:pass@localhost/owncloud/remote.php/webdav/foo.txt```

Of course with modifications to the data file.
The file is actually updated. But no new version is added.

I assume it is a bug. But could be that is just not yet properly implemented.

**Comment by karlitschek** [comment]
There must be something wrong

**Comment by PVince81** [comment]
This used to work => regression

**Comment by PVince81** [comment]
@rullzer have you done any bisect before ?

**Comment by PVince81** [comment]
It could be related to the "view" bypass implemented in the sabre file class which works directly on the storage. But AFAIK it should still manually trigger the hooks after putting the file, which would then trigger the versions code.

Needs further research.

**Comment by PVince81** [comment]
I'll bisect this

**Comment by PVince81** [comment]
Regression introduced by https://github.com/owncloud/core/pull/12006 from @icewind1991 where we work directly on the storage. Maybe for some reason hooks and stuff do not get triggered properly.

I'll try and debug this.

**Comment by PVince81** [comment]
I see that hooks are triggered properly, they do reach the trashbin and sharing propagator. But somehow they don't reach the versions code, maybe the hook wasn't registered properly in this situation.

**Comment by PVince81** [comment]
@icewind1991 we seem to be missing the pre-hooks. Only post hooks are triggered. Was this on purpose or just an omission ?

We probably need to trigger the "create", "update" and "write" hooks too. Not sure when. Need to check when they were triggered in the "old" version.

**Comment by PVince81** [comment]
PR here: https://github.com/owncloud/core/pull/16292

**Comment by nickvergessen** [comment]
PR merged
