### ISSUE TITLE
gd-jpeg, libjpeg: recoverable error

### ISSUE THREAD

**Issue by binarykitchen** [owncloud/core#16135]
```
{"reqId":"e50ea44e3a86c2ec883844123aaf9552","remoteAddr":"203.84.135.120","app":"PHP","message":"imagecreatefromjpeg(): gd-jpeg, libjpeg: recoverable error: \b\n at \/var\/www\/owncloud\/lib\/private\/image.php#489","level":3,"time":"2015-05-06T22:24:58+00:00"}
```

Happens on the stable8 branch of galleryplus and on owncloud v8.0.3 with php5.5.24 and Ubuntu 14.10

**Comment by oparoz** [comment]
@georgehrke - Would a corrupt JPEG trigger that error message?

**Comment by RealRancor** [comment]
@binarykitchen As you're quite often reporting issues please try to use the issue template as advised here: https://github.com/owncloud/gallery/issues/185#issuecomment-99633159 when reporting issues.

This needs a little more time for you but saves a lot of time of the developers to get the needed infos.

**Comment by binarykitchen** [comment]
Understand but I can't do this every time. Eats too much time. I think it would be a smart move to have an automatic bug report integrated inside of owncloud, this to collect all the data you need automatically.

What info do you need in addition to the above? I'll provide you with these asap.

**Comment by MorrisJobke** [comment]
> Understand but I can't do this every time. Eats too much time. I think it would be a smart move to have an automatic bug report integrated inside of owncloud, this to collect all the data you need automatically.

@LukasReschke What is the state of your app?

**Comment by RealRancor** [comment]
Ref: https://github.com/owncloud/core/issues/13258

**Comment by binarykitchen** [comment]
Wonderful, #13258 is really great!

**Comment by RealRancor** [comment]
@binarykitchen 
Until #13258 is implemented the most important part of https://raw.githubusercontent.com/owncloud/core/master/issue_template.md is "### Steps to reproduce, ### Expected behaviour and ### Actual behaviour" which you could fill out when reporting issues.

**Comment by binarykitchen** [comment]
Honestly, I do not remember how this error occurred and am unable to write these three chapters. I have gigabytes of images here.

If you could improve these error messages, this would help a lot. For example **include the path of the corrupted image**. Like that I'll be able to reproduce. You see my point?

**Comment by DeepDiver1975** [comment]
> For example include the path of the corrupted image. Like that I'll be able to reproduce. You see my point?

this is an error message generated by php itself - not really much we can do ...

**Comment by binarykitchen** [comment]
how about wrapping a `try ... catch` block around that php function and throw a new error message with more information?

**Comment by DeepDiver1975** [comment]
> how about wrapping a try ... catch block around that php function and throw a new error message with more information?

these php messages you see in the log are no exceptions which we can try to catch ...

**Comment by binarykitchen** [comment]
I see. and how about reporting this to the PHP developers?

**Comment by DeepDiver1975** [comment]
> I see. and how about reporting this to the PHP developers?

Feel free ... nothing to do for us here - sorry
