### ISSUE TITLE
ocsclient should not try to retrieve an app without an ocsid

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#16136]
It seems on 8.0.3 the OCS client is trying to retrieve information about all installed apps without checking first if they have an ocsid.

That leads to "Invalid OCS content returned for app xyz" messages in the log for apps which don't exist in the app store.

It's not a major problem, but fixing it would prevent making unnecessary requests to the app store.

https://github.com/owncloud/core/blob/master/lib/private/ocsclient.php#L236
or
https://github.com/owncloud/core/blob/master/lib/private/ocsclient.php#L296

**Comment by PVince81** [comment]
obsoleted by marketplace code
