### ISSUE TITLE
Integration of 2 OwnCloud instances

### ISSUE THREAD

**Issue by hitam4450** [owncloud/core#16144]
integrating two OC 8.03 instances cretes the following error message:
\\\\Files\\\\Stora...', Array, false)\n#4 \/media\/www\/servers\/owncloud.ibt-global.net\/apps\/files_external\/ajax\/addMountPoint.php(25): OC_Mount_Config::addMountPoint('Torrents', '\\\\OC\\\\Files\\\\Stora...', Array, 'user', 'ireng', false)\n#5 \/media\/www\/servers\/owncloud.ibt-global.net\/lib\/private\/route\/route.php(135) : runtime-created function(1): require_once('\/media\/www\/serv...')\n#6 [internal function]: __lambda_func(Array)\n#7 \/media\/www\/servers\/owncloud.ibt-global.net\/lib\/private\/route\/router.php(250): call_user_func('\\x00lambda_30849', Array)\n#8 \/media\/www\/servers\/owncloud.ibt-global.net\/lib\/base.php(782): OC\\Route\\Router->match('\/apps\/files_ext...')\n#9 \/media\/www\/servers\/owncloud.ibt-global.net\/index.php(36): OC::handleRequest()\n#10 {main}","File":"\/media\/www\/servers\/owncloud.ibt-global.net\/lib\/private\/files\/storage\/dav.php","Line":594} 

What went worng??

**Comment by schiesbn** [comment]
Please use the issue template to give us some more context about what you are trying to do and what goes wrong: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by hitam4450** [comment]
Software is all the latest version, DEBIAN 8.0, mysql, php, Oc 8.03

**Comment by hitam4450** [comment]
tried it unsuccessful with webdav:
Exception: {"Message":"Sabre\\DAV\\Exception: [CURL] Error while making request: SSL certificate problem: self signed certificate (error code: 60)","Code":0,"Trace":"#0 \/media\/www\/servers\/owncloud.ibt-global.net\/lib\/private\/files\/storage\/dav.php(382): OC\\Files\\Storage\\DAV->convertSabreException(Object(Sabre\\DAV\\Exception))\n#1 \/media\/www\/servers\/owncloud.ibt-global.net\/lib\/private\/files\/storage\/common.php(393): OC\\Files\\Storage\\DAV->stat('')\n#2 \/media\/www\/servers\/owncloud.ibt-global.net\/apps\/files_external\/lib\/config.php(457): OC\\Files\\Storage\\Common->test(false)\n#3 \/media\/www\/servers\/owncloud.ibt-global.net\/apps\/files_external\/lib\/config.php(539): OC_Mount_Config::getBackendStatus('\\\\OC\\\\Files\\\\Stora...', Array, false)\n#4 \/media\/www\/servers\/owncloud.ibt-global.net\/apps\/files_external\/ajax\/addMountPoint.php(25): OC_Mount_Config::addMountPoint('Torrents', '\\\\OC\\\\Files\\\\Stora...', Array, 'user', 'dirk', false)\n#5 \/media\/www\/servers\/owncloud.ibt-global.net\/lib\/private\/route\/route.php(135) : runtime-created function(1): require_once('\/media\/www\/serv...')\n#6 [internal function]: __lambda_func(Array)\n#7 \/media\/www\/servers\/owncloud.ibt-global.net\/lib\/private\/route\/router.php(250): call_user_func('\\x00lambda_44498', Array)\n#8 \/media\/www\/servers\/owncloud.ibt-global.net\/lib\/base.php(782): OC\\Route\\Router->match('\/apps\/files_ext...')\n#9 \/media\/www\/servers\/owncloud.ibt-global.net\/index.php(36): OC::handleRequest()\n#10 {main}","File":"\/media\/www\/servers\/owncloud.ibt-global.net\/lib\/private\/files\/storage\/dav.php","Line":594}

**Comment by hitam4450** [comment]
Still cannot connect  two similar  OC 8.03 instances!

**Comment by RealRancor** [comment]
@hitam4450 
You still havn't used the issue template as requested above ;-)

**Comment by hitam4450** [comment]
Ok, thanks for the reminder. Please close the subject. If synchronizing to OC 8.03 instances including 2 shared directories, do not work at once - just forget it. I found a solution, of course more laborious, but it works fine!

**Comment by hitam4450** [comment]
I closed the issue!

Am 24.05.2015 um 00:29 schrieb RealRancor:
