### ISSUE TITLE
LDAP wizard configuration: Groups add/removed in Groups tab are shared with two AD configurations.

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16147]
### Steps to reproduce

1. Go to LDAP wizard configuration.
2. Configure two right Active Directories configurations installed in the same place
3. Add groups in one them, or remove some in the Groups tab

### Expected behaviour

The groups add/removed for each configuration should be independent

### Actual behaviour
Groups add or removed appears in both configurations

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 alpha 3

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by davitol** [comment]
@blizzz

**Comment by jvillafanez** [comment]
I'm having the same issue, although it seems more generic.

I'd say that the configuration isn't properly loaded in the browser. I've checked in the users and advanced tabs, and there are a lot of configuration values, if not all, that remain from the previous configuration.

I've found a js error that might be the cause:
![screenshot from 2015-05-07 18 33 29](https://cloud.githubusercontent.com/assets/1477829/7520590/07faabf2-f4e8-11e4-9271-7e3e5af3e2b8.png)

@jnfrmarks This might generate more bugs. Right now I had my first configuration active and the second inactive; the wizard shows (wrongly) that the second configuration is active (I've checked from the CLI that it's inactive) so I thought that users from both server should be showing in the users page. If @blizzz can reproduce, I'd increase the severity. It's a really annoying bug.

**Comment by jnfrmarks** [comment]
@davitol 

Is this AD only?

**Comment by blizzz** [comment]
That happens with the JS error on config switch. Fix ready soon.

**Comment by davitol** [comment]
@jnfrmarks No, it also happens with openLDAP.

**Comment by davitol** [comment]
Seems to be fixed :+1:
