### ISSUE TITLE
PHP 7 Compatibility Issue: Cannot use 'Null' as class name as it is reserved in /lib/private/memcache/null.php

### ISSUE THREAD

**Issue by CASIPC** [owncloud/core#16149]
Pretty simple. "Null" is not allowed as a class name in PHP 7. Class needs renamed. Something like OCNull.

From what I understand, the only use of this is in /lib/private/memcache/factory.php line 45: return new Null($prefix);

**Comment by Xenopathic** [comment]
Gah, we had this with ArrayCache too (that's why it has the Cache suffix). I wish builtins were considered like normal objects in PHP, overridable with `use` statements...

**Comment by th3fallen** [comment]
honestly what would be best imho would be to default to arraycache if no other is configured. 

On the topic a class named null should never exist anyway and im glad php7 is forcing removal of it honestly.

**Comment by LukasReschke** [comment]
Added this to the meta issue: https://github.com/owncloud/core/issues/16641

**Comment by LukasReschke** [comment]
Fixed with https://github.com/owncloud/core/pull/16869
