### ISSUE TITLE
LDAP wizard configuration: Users and groups textbox width should be higher

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16142]
### Steps to reproduce
1. Go to LDAP wizard configuration.
2. Click on Users or groups tab
### Expected behaviour

The whole name of the groups should be visible
### Actual behaviour

The whole names of the groups named a bit long are not visible
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 alpha 3

**Updated from an older ownCloud or fresh install:** fresh install

![groupswidth](https://cloud.githubusercontent.com/assets/10596560/7510810/4a3697c6-f4a0-11e4-804d-e13b0f4b1cd0.png)

**Comment by karlitschek** [comment]
@blizzz

**Comment by blizzz** [comment]
For now (as a hint), hovering on a group name will show the complete name in a tooltip.

**Comment by PVince81** [comment]
moved to grouped UX ticket: https://github.com/owncloud/user_ldap/issues/69
