### ISSUE TITLE
Module API missmatch

### ISSUE THREAD

**Issue by tps800** [owncloud/core#16148]
### Steps to reproduce
1. Install OwnCloud, Configure OwnCloud, Configure LDAP access
2. Upgrade to the latest version: 8.0.3-13.1 -- as available from repository

### Expected behaviour
* Web-Interface working
* occ-command working

### Actual behaviour
* Web-Interface shows empty screen (behind the scenes it doesn't deliver any output, because of module API-missmatches)
* occ-command cases to work because of module API-missmatch.

```
# sudo -u apache ./occ --help
PHP Warning:  PHP Startup: pam: Unable to initialize module
Module compiled with module API=20121212
PHP    compiled with module API=20131226
These options need to match
 in Unknown on line 0
PHP is configured to populate raw post data. Since PHP 5.6 this will lead to PHP throwing notices for perfectly valid code.
To fix this issue set <code>always_populate_raw_post_data</code> to <code>-1</code> in your php.ini
```

OwnCloud install is at:
```
owncloud-3rdparty-8.0.3-13.1.noarch
owncloud-8.0.3-13.1.noarch
owncloud-app-activity-8.0.3-13.1.noarch
owncloud-app-external-8.0.3-13.1.noarch
owncloud-app-files-8.0.3-13.1.noarch
owncloud-app-files_encryption-8.0.3-13.1.noarch
owncloud-app-files_external-8.0.3-13.1.noarch
owncloud-app-files_locking-8.0.3-13.1.noarch
owncloud-app-files_pdfviewer-8.0.3-13.1.noarch
owncloud-app-files_sharing-8.0.3-13.1.noarch
owncloud-app-files_texteditor-8.0.3-13.1.noarch
owncloud-app-files_trashbin-8.0.3-13.1.noarch
owncloud-app-files_versions-8.0.3-13.1.noarch
owncloud-app-files_videoviewer-8.0.3-13.1.noarch
owncloud-app-firstrunwizard-8.0.3-13.1.noarch
owncloud-app-gallery-8.0.3-13.1.noarch
owncloud-app-provisioning_api-8.0.3-13.1.noarch
owncloud-app-templateeditor-8.0.3-13.1.noarch
owncloud-app-updater-8.0.3-13.1.noarch
owncloud-app-user_external-8.0.3-13.1.noarch
owncloud-app-user_ldap-8.0.3-13.1.noarch
owncloud-app-user_webdavauth-8.0.3-13.1.noarch
owncloud-config-apache-8.0.3-13.1.noarch
owncloud-server-8.0.3-13.1.noarch
```

### Client configuration
**Operating system:** Ubuntu 14.04.2 LTS

**OwnCloud Client:** 1.8.0 (build 4847)

**Operating system:** Windows 7 Pro

**OwnCloud Client:** 1.8.0 (build 4847)

### Server configuration
**Operating system:** Oracle Linux 6.6

**Web server:** Apache 2.2.15-39.0.1

**Database:** PostgreSQL 9.3.6

**PHP version:** PHP 5.6.7

**ownCloud version:** 8.0.3-13.1

**Updated from an older ownCloud or fresh install:** Upgrade from 6.5

**List of activated apps:**
* Enabled:
 - activity
 - files
 - files_pdfviewer
 - files_sharing
 - files_trashbin
 - gallery
 - imprint
 - ocusagecharts
 - password_policy
 - user_ldap

* Disabled:
 - external
 - files_encryption
 - files_external
 - files_locking
 - files_texteditor
 - files_versions
 - files_videoviewer
 - firstrunwizard
 - provisioning_api
 - templateeditor
 - updater
 - user_external
 - user_webdavauth

**The content of config/config.php:** 

```
<?php
$CONFIG = array (
  'instanceid' => 'oc692ddacb52',
  'passwordsalt' => '',
  'trusted_domains' =>
  array (
    0 => '<server>.<local>.<domain>',
  ),
  'datadirectory' => '/data/owncloud/data',
  'dbtype' => 'pgsql',
  'version' => '8.0.3.4',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncld',
  'dbpassword' => '',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => '0',
  'mail_smtpmode' => 'php',
  'mail_smtpname' => 'admin',
  'mail_smtppassword' => '',
);

```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

### Client configuration
**Browser:**
* Windows XP/7/8:
 * Chrome (stable, beta, snapshot)
 * Chromium (stable, continuous)
 * Firefox (stable, nightly)
 * Opera (stable)
 * lynx (from cygwin)
 * w3m (from cygwin)
* Linux (Debian, Ubuntu 12.04/14.04/14.10, Fedora 19/20/21, Oracle Linux 6.5/7.0)
 * Chrome (stable, beta, snapshot)
 * Chromium (stable, continuous)
 * Firefox (stable, nightly)
 * Opera (last available)
 * Konqueror (stable)
 * lynx (stable)
 * w3m (stable)

#### Web server error log
```
Web server log
```

#### ownCloud log (data/owncloud.log)
```
ownCloud log
```

#### Browser log
```
Browser log
```

**Comment by RealRancor** [comment]
Hi,

thats a configuration problem within your PHP installation and not a problem of ownCloud itself. You're mixing an old version of the PHP pam module (API=20121212 is PHP 5.5) with the newer PHP version (API=20131226 is PHP 5.6).

Please fix your environment here.

**Comment by tps800** [comment]
Yes it was. After reinstalling pam.so with pecl this part of the problem was gone.
But the blank page remained.
After disabling some apps and enabling them again I could find the one responsible: EagleEye.
Even in the latest available version this will lead to a blank page if enabled. Seems it needs to be fixed!
