### ISSUE TITLE
New installed apps don't appear in the "not enabled" section of the settings/apps page with APCu or XCache cache active

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#16140]
### Steps to reproduce
1. Have APCu (or XCache) active
2. Install an app manually (download the app and copy it inside the apps folder with the correct permissions)
3. Go to the settings/apps page, "not enabled" section
### Expected behaviour

The app appear
### Actual behaviour

The app doesn't appear until cache expires
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 alpha 3

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by MorrisJobke** [comment]
cc @LukasReschke

**Comment by nickvergessen** [comment]
I think we should have a look whether the caching of this is worth it. It appears to cause more problems then it solves: https://github.com/owncloud/core/issues/15359 and https://github.com/owncloud/core/issues/16113

while it still does not solve the real problem why the page is slow: https://github.com/owncloud/core/issues/15851 (update checks against the app store)

**Comment by jvillafanez** [comment]
I've also checked with memcached with the same result

**Comment by LukasReschke** [comment]
Well – this is simply the expected behaviour as of now. ownCloud does not know at all whether a new application has been added. For such manual manipulations as well as https://github.com/owncloud/core/issues/15359 a manual cleanup button as suggested in https://github.com/owncloud/core/issues/15359#issuecomment-99841832 and https://github.com/owncloud/core/issues/16163 would make sense.

@DeepDiver1975 Please advise how to proceed further on this.

**Comment by jvillafanez** [comment]
Adding or deleting a folder should change the mtime of the parent folder in any FS we're supporting. I think we can rely on this to check if a new app has been added or deleted. If the mtime of the apps folder changes, clear the cache.

**Comment by LukasReschke** [comment]
> Adding or deleting a folder should change the mtime of the parent folder in any FS we're supporting. I think we can rely on this to check if a new app has been added or deleted. If the mtime of the apps folder changes, clear the cache.

Yes… But we will still face the same problem in other places… Such as for user related functions etc…

**Comment by jvillafanez** [comment]
> Yes… But we will still face the same problem in other places… Such as for user related functions etc…

Each app should be responsible for their own cache keys. In fact, although I've said that the action to be taken for this case is clear the cache, it should be delete the "apps-related" keys, or even better, update the keys with the correct content.

Having a "clear all cache" button might be a nice addition for debugging, but it won't be good performance-wise

**Comment by PVince81** [comment]
Not sure if related, but I had a one-time issue on stable8 where changing the version in version.php would not trigger the update screen. I could not update ownCloud any more, this was with memcache. Solved by re-running the setup.

**Comment by PVince81** [comment]
old issue, please reopen if still happening in recent version
