### ISSUE TITLE
LDAP wizard configuration: In User tab, object classes combobox has an erratic behaviour

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16145]
### Steps to reproduce
1. Go to LDAP wizard configuration.
2. Configure a right conf in Servers tab
3. Go to Users tab and select two object classes
4. Click in the screen in the zone marked with a cross in the picture below

### Expected behaviour
The object classes should be kept selected.

### Actual behaviour
Sometimes they are deselected. 

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 alpha 3

**Updated from an older ownCloud or fresh install:** fresh install

![occombobox](https://cloud.githubusercontent.com/assets/10596560/7511687/224a9260-f4a7-11e4-8e29-dceceb989558.png)

**Comment by blizzz** [comment]
Possibly duplicate of https://github.com/owncloud/core/issues/15859 ?

**Comment by davitol** [comment]
Yes, maybe is dupe of it. I close this one.
