### ISSUE TITLE
LDAP wizard configuration: Using two active directories. Users are shown in Users menu even if the ADs configuration are not active.

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16143]
### Steps to reproduce
1. Go to LDAP wizard configuration.
2. Configure two Active Directories.
3. Go to Users menu and check that the users of the ADs appears
4. Go back to LDAP wizard configuration
5. In Advanced tab deselect Configuration active in both ADs configuration
6. Go back to Users menu.

### Expected behaviour

The users of the ADs should not appear due to they are not active

### Actual behaviour
The users are shown

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 alpha 3

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by davitol** [comment]
@blizzz

**Comment by blizzz** [comment]
Cannot reproduce.

**Comment by jnfrmarks** [comment]
@davitol 

Please retry.  Let me know if you need some help with the configuration.

**Comment by davitol** [comment]
@blizzz With OC 8.1 Beta 1 , deselecting all configured ADs (configuration active not marked in Advanced tab), if you click on users, they still appear.

**Comment by cmonteroluque** [comment]
This issue will fall off 8.2 if not resolved by 6 Oct

**Comment by blizzz** [comment]
@davitol does it still happen? if so, could you give me access to such an instance?

**Comment by davitol** [comment]
@blizzz Tested again with ownCloud 9.0.0 RC1 and I cannot reproduce it. So let's close the issue
