### ISSUE TITLE
LDAP: Setup and configure 2 LDAP servers correctly, making sure that at least one user is “shared” in both servers (uid and display name are the same, with different password)

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16150]
### Steps to reproduce
1. Go to LDAP wizard configuration.
2. Configure two right Active Directories configurations with one user shared in both servers, but different password.
3. Log out as admin, and try to log in the shared user with both password
### Expected behaviour

User can login in his respective accounts
### Actual behaviour

Only one password is accepted, maybe the first that was configured.
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 alpha 3

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by davitol** [comment]
@blizzz

**Comment by PVince81** [comment]
@owncloud/ldap

**Comment by PVince81** [comment]
probably not critical, @jvillafanez ?

**Comment by jvillafanez** [comment]
Taking into account that the setup isn't common and noone has complained about it, I don't think it's critical. I'll have to check what we can do about this.

**Comment by PVince81** [comment]
Closing this old ticket as won't fix unless more people complain about this.
