### ISSUE TITLE
Sharing a file using federated sharing with encryption doesn't work

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16151]
### Steps to reproduce

1. Prepare two servers. 
2. Enable encryption in both.
3. Share a file with a remote user from server1 to server2.
4. Try to open the file in server2.

### Expected behaviour
File is opened.

### Actual behaviour
A dialog for accepting the remote shared file gets opened and after accepting it, the file is not there.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
Postgresql

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.4","versionstring":"8.1 alpha 3","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in community edition.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Chrome 41

**Comment by SergioBertolinSG** [comment]
Only happens when the sender-side is encrypted.
Sharing from a not encrypted server to an encrypted one works fine.

**Comment by schiesbn** [comment]
I can't reproduce it here on master... Works in both directions

**Comment by SergioBertolinSG** [comment]
Retested with latest code, working fine.
