### ISSUE TITLE
Misleading error message in the LDAP wizard trying to detect the port when it's correctly set

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#16154]
### Steps to reproduce
1. Setup a valid LDAP configuration with and ldap server in a non-standard port
2. Make sure there isn't anything active in the standard port (389)
3. In the wizard (with a valid configuration) click in the "detect port" button

### Expected behaviour
Since the port is already set and valid, a successful message should be shown

### Actual behaviour
"Please specify the port, it could not be auto-detected." message appear

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 alpha 3

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by blizzz** [comment]
Can't reproduce, works fine for me with OpenLDAP and AD, non-standard and standard port. Might be related to a already fixed issue. Please try again.

**Comment by jvillafanez** [comment]
Looks like it's happening with anonymous authentication errors.

I've checked with openLDAP with anonymous auth (it's not enabled in the server) and that error is shown. It might be overwritten and might hide the authentication error. With proper credentials works fine

**Comment by blizzz** [comment]
@jvillafanez still cannot reproduce. Thats what I tried (against both master and stable8.1):

1. I have a configuration to my local OpenLDAP, running on a non-standard port. It's fully configured, and fully successful.
2. I remove the User DN and the Password
3. I click on "Detect Port" → No error message is shown, the port stays at my non-standard one. In the owncloud log a message about the failed bind was written, however it was also stated that OpenLDAP was detected at the given port.

Note that an LDAP server can only be found on a standard port or if a non-standard port is already entered, either in the port field or appended to the host (as in ldap.example.org:7770).

@jvillafanez do I do anything wrong?

[…]

Now, I was able to manage to get the message. For me it appears when I enter a user DN, but leave the password field blank. There should be a different message in that case, yes. I will fix this.

**Comment by blizzz** [comment]
> Now, I was able to manage to get the message. For me it appears when I enter a user DN, but leave the password field blank. There should be a different message in that case, yes. I will fix this.

Um, actually not, if the server replies with something useful, we found him ;) Now, also when I have both User DN and password empty and the port added in the host, the detection does not succeed falsely.
