### ISSUE TITLE
setting a "char" limit or offset in the LDAP occ search command behaves as if the user set limit or offset = 0

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#16156]
### Steps to reproduce
1. Set a valid LDAP configuration with several users (more than 50)
2. Run from the command-line `sudo -u www-data ./occ ldap:search --limit=random ''`
### Expected behaviour

An error is thrown
### Actual behaviour

The command behaves the same as setting the limit = 0.
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apapche 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 alpha 3

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by jvillafanez** [comment]
Related to https://github.com/owncloud/core/issues/15765

**Comment by PVince81** [comment]
@jvillafanez didn't you have a PR for something similar ?

**Comment by jvillafanez** [comment]
I guess you're refering to https://github.com/owncloud/core/pull/25450 , but that one won't fix this issue

**Comment by PVince81** [comment]
Corner case, closing as won't fix unless someone is willing to submit a PR to the user_ldap repo
