### ISSUE TITLE
Feature request, server scripting.

### ISSUE THREAD

**Issue by schaefer0** [owncloud/core#16161]
Hi, 
Here's what I am trying to use owncloud for:
  I'm part of a team thats engineering distributed embedded data collectors for science, where each box tries to synch its collected data to own cloud periodically.
  The consequence for the server (at this point in time) is one directory receives gigabytes of files. The problem is afterwards, where the scientist logs into the server and attempts to download a gigabyte directory to their computer's local disk. The download fails due to browser issues for large data sets, I've tried several browsers, all fail at several hundred megabytes in, where the browser gives up, producing a bad zip file, as unzip says parts are missing.
  The improvement would be on my part to organize directories on the server by experiment, by year and day of year, so no lower level directory contains too much data for a browser to download. 
Here's the problem:
 If I want to set up the server directories I have to manually create 365 directories per year, for each year, per box. This problem does not scale because of the human involved (me) having to click buttons for creating each directory for hundreds of directories. What I would like is a scripting tool to command the owncloud server to create directories.
Any help? 
bob schaefer
mit haystack observatory
rps@haystack.mit.edu

**Comment by LukasReschke** [comment]
> What I would like is a scripting tool to command the owncloud server to create directories.

You can create an ownCloud application that does this for you, see https://doc.owncloud.org/server/8.0/developer_manual/app/tutorial.html for details. I doubt that it makes sense to add a such specific changeset to the core.

A very small and somewhat example would be the following (add to the same folder as index.php and access via browser), better make a real app out of it:

```php
<?php

include_once('./lib/base.php');

// Users to populate
$users = [
	'admin',
	'test',
];

foreach($users as $user) {
	\OC_Util::setupFS($user);

	$userFolder = \OC::$server->getUserFolder($user);

	for ($i = 1; $i <= 365; $i++) {
		$userFolder->newFolder($i);
	}

	\OC_Util::tearDownFS();
}
```

**Comment by schaefer0** [comment]
thank you, I am new to owncloud, its good to know this feature exists.
