### ISSUE TITLE
OC7 DB: "users" and "external storage files" relationship

### ISSUE THREAD

**Issue by Malinoski** [owncloud/core#16166]
Hello.

I have some questions that I could not find  :( , and would be grateful for some help.  :D.
In the [ownCloud forum] (https://forum.owncloud.org/viewtopic.php?f=29&t=28137) was suggested to me that my questions are for developers. At end of this message my configuration.

I am seeking information not found in the ownCloud 7.0.4 database.
As the entity relationship between "users" and "files stored in external storages".

In the example below, the entity relationship between "file" and "storage" exists, however, the relationship between "file" and "user" not:
```
oc_filecache  (fileid, storage, path, path_hash, parent, name, mimetype, mimepart,size, mtime, storage_mtime, encrypted, unencrypted_size, etag, permissions)
"53";5;"file.txt";"3d8e577bddb17db339eae0b3d9bcf180";30;"file.txt";12;10;0;1430919879;1430919879;0;0;"554a1ac74eb04";27

oc_storage (id, numeric_id)
"local::/var/repositorio03/"; "5"
```
I also know, that this relationship is done in ownCloud 7.0.4 outside of the database, in the file
../owncloud/data/mount.json. I know too, in ownCloud 5.0.18, this relationship is described
oc_permissions the table, however, this table is no longer used in ownCloud 7.0.4.

My questions are:
1) Why the oc_permissions table is no longer used?
2) Is there a way to match "users" and "files stored in external repositories" **in** ownCloud database 7.0.4?

Thank you!

### Server configuration
**Operating system**: Ubuntu 14.04 LTS

**Web server:** Apache 2

**Database:** PostgreSQL 9.3.6

**PHP version:** 5.5

**ownCloud 7 version:** 7.0.4
**ownCloud 5 version:** 5.0.18

**Updated from an older ownCloud or fresh install:** fresh install for ownCloud 7 and ownCloud 5.

**List of activated apps:**
**ownCloud 7.0.4**: Activity, Calendar, Contacts, Deleted files, Documents, External Storage Support, First Run Wizzard, Full Text Search, LDAP user and group backend, Mail Template, PDF Viewer, Pictures, Shared Files, Text Editor, Updater, Versions and Video Viewer.
**ownCloud 5.0.18** Calendar, Contacts, Deleted files, External Storage Support, First Run Wizzard, Full Text Search, LDAP user and group backend, Media, ODF Viewer, PDF Viewer, Pictures Shared Files, Text Editor, Updater, User Account Migration, Versions, Video Viewer, ownCloud Instance Migration.

**The content of config/config.php ownCloud 7.0.4:**
```
<?php
$CONFIG = array (
  'instanceid' => 'oc51fe08cdf9',
  'passwordsalt' => '********************',
  'secret' => '****************',
  'trusted_domains' =>
  array (
    0 => 'localhost',
  ),
#  'datadirectory' => '/var/www/html/owncloud-7.0.4/data',
  'datadirectory' => '/var/oc/data',
  'overwrite.cli.url' => 'http://localhost/owncloud-7.0.4',
  'dbtype' => 'pgsql',
  'version' => '7.0.4.2',
  'dbname' => 'owncloud704',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '***********',
  'dbpassword' => '**************',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
);
```

**The content of config/config.php ownCloud 5.0.18:**
```
<?php
$CONFIG = array (
  'instanceid' => '54aa7585960c4',
  'passwordsalt' => '**********************',
  'trusted_domains' =>
  array (
    0 => 'localhost',
  ),
  'datadirectory' => '/var/www/html/owncloud-5.0.18/data',
  'dbtype' => 'pgsql',
  'version' => '5.0.36',
  'dbname' => 'owncloud5018',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '*************',
  'dbpassword' => '***************',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
);
```
**Are you using external storage, if yes which one:** local for ownCloud 7.0.4 and local ownCloud 5.0.18

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP for ownCloud 5.0.18

**Comment by PVince81** [comment]
External storages are mapped to uses in mount.json.
Unfortunately this information is not in the database, and I agree that this is very bad.

There are plans to move mount.json to the database eventually: see https://github.com/owncloud/core/issues/11830 and https://github.com/owncloud/core/issues/15166

**Comment by Malinoski** [comment]
Thank you very much!
