### ISSUE TITLE
Maximum upload size not conserved on server upgrade

### ISSUE THREAD

**Issue by geez0x1** [owncloud/core#16165]
Upon upgrading to the latest 8.0.x releases I noticed that every time I upgrade, the maximum upload size is reset (to 2GB, iirc, while I usually have it set at 32GB). This requires me to change it again every time.

**Comment by RealRancor** [comment]
Hi,

there is a long open report available here: https://github.com/owncloud/core/issues/2692

**Comment by geez0x1** [comment]
Oh no, another bug opened because I didn't find an unresolved, but closed one :( Thanks for the heads-up, I reported it there as well but at least this one's open :) Since the issue hasn't been resolved in forever maybe I'll have a crack at it whenever my work slows down a bit and free time arises.

Since the information is contained in the htaccess file, it would seem trivial to include a htaccess template, and run it through a search-and-replace to fill in any settings that should be there from the database.

**Comment by RealRancor** [comment]
@geez0x1 Feel free to close this issue as it won't help having two issues about the same issue open.

**Comment by geez0x1** [comment]
Closing
