### ISSUE TITLE
EagleEye leads to blank page connection to owncloud

### ISSUE THREAD

**Issue by tps800** [owncloud/core#16167]
### Steps to reproduce
1. Install OwnCloud, Configure OwnCloud, Configure LDAP access
2. Upgrade to latest available version 8.0.3.4

### Expected behaviour
Seeing blank page connecting to owncloud

Searching for which app is responsible for the blank page by disabling, checking, then enabling every one app installed. I found it being EagleEye. It is not working any more together with the latest version of owncloud.

### Actual behaviour
Working as before.

### Client configuration
**Operating system:** Ubuntu 14.04.2 LTS

**OwnCloud Client:** 1.8.0 (build 4847)

**Operating system:** Windows 7 Pro

**OwnCloud Client:** 1.8.0 (build 4847)

### Server configuration
**Operating system:** Oracle Linux 6.6

**Web server:** Apache 2.2.15-39.0.1

**Database:** PostgreSQL 9.3.6-1

**PHP version:** PHP 5.6.8

**ownCloud version:** 8.0.3-13.1

**Updated from an older ownCloud or fresh install:** Upgrade from 6.5

**List of activated apps:**
* Enabled:
 - activity
 - files
 - files_pdfviewer
 - files_sharing
 - files_trashbin
 - gallery
 - imprint
 - ocusagecharts
 - password_policy
 - user_ldap

* Disabled:
 - external
 - files_encryption
 - files_external
 - files_locking
 - files_texteditor
 - files_versions
 - files_videoviewer
 - firstrunwizard
 - provisioning_api
 - templateeditor
 - updater
 - user_external
 - user_webdavauth

**The content of config/config.php:** 

```
<?php
$CONFIG = array (
  'instanceid' => 'oc692ddacb52',
  'passwordsalt' => '',
  'trusted_domains' =>
  array (
    0 => '<server1>.<local1>.<domain1>',
    1 => '<server2>.<local2>.<domain2>',
  ),
  'datadirectory' => '/data/owncloud/data',
  'dbtype' => 'pgsql',
  'version' => '7.0.1.1',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncld',
  'dbpassword' => '',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => '0',
  'mail_smtpmode' => 'php',
  'mail_smtpname' => 'admin',
  'mail_smtppassword' => '',
  'overwritewebroot' => '/owncloud',
  'overwrite.cli.url' => '/owncloud',
  'secret' => '',
);

```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

### Client configuration
**Browser:**
* Windows XP/7/8:
 * Chrome (stable, beta, snapshot)
 * Chromium (stable, continuous)
 * Firefox (stable, nightly)
 * Opera (stable)
 * lynx (from cygwin)
 * w3m (from cygwin)
* Linux (Debian, Ubuntu 12.04/14.04/14.10, Fedora 19/20/21, Oracle Linux 6.5/7.0)
 * Chrome (stable, beta, snapshot)
 * Chromium (stable, continuous)
 * Firefox (stable, nightly)
 * Opera (last available)
 * Konqueror (stable)
 * lynx (stable)
 * w3m (stable)

#### Web server error log
```
Web server log
```

#### ownCloud log (data/owncloud.log)
```
ownCloud log
```

#### Browser log
```
Browser log
```

**Comment by RealRancor** [comment]
Hi,

please report issues with 3rdparty apps to the issue tracker of this app. The EagleEye issue tracker is located here: https://github.com/noldmess/EagleEye/issues

**Comment by tps800** [comment]
Done it!
