### ISSUE TITLE
LDAP wizard configuration: Group tab, adding arrow wrong behaviour

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16169]
### Steps to reproduce
1. Go to LDAP wizard configuration.
2. Configure an Active Directory.
3. Go to users or Groups tab
4. Click on  the add group button ' >' without selection any group in the left box
### Expected behaviour

No group should be added or a default group always selected should be added
### Actual behaviour

A group called object window is added. Same wrong behaviour in users tab.
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 alpha 3

**Updated from an older ownCloud or fresh install:** fresh install
![arrowbtt](https://cloud.githubusercontent.com/assets/10596560/7517574/1f62f464-f4d6-11e4-98ca-04ce964dd9f0.png)

**Comment by PVince81** [comment]
moved to grouped UX ticket: https://github.com/owncloud/user_ldap/issues/69
