### ISSUE TITLE
Clear Caches button in admin settings

### ISSUE THREAD

**Issue by RobinMcCorkell** [owncloud/core#16163]
We've been bitten a couple of times now with caches needing to be invalidated manually (#15359, #13658), and it seems the best way to go about this is to introduce a button in the admin section that clears all caches - be that memcaches, LDAP cache, generated assets - just _everything_.

Marking as 8.2 for now since we have decent documentation already to restart the web server/clear caches manually for big changes. cc @carlaschroder 

cc @LukasReschke @DeepDiver1975 @PVince81 @nickvergessen

**Comment by karlitschek** [comment]
Well I actually think that the caches have to cleared automatically if a certain event happens that makes the  data invalid. an explicit clear button shouldn´t be necessary in good software :-)

**Comment by nickvergessen** [comment]
@karlitschek the problem is that CLI and web php use different caches, as stated in the linked tickets above. Not a lot we can do against

**Comment by Xenopathic** [comment]
@karlitschek Either way, this is a useful feature that can help in a variety of situations, forcing refresh of external binary paths as an example.

**Comment by carlaschroder** [comment]
I can see where a 'clear all caches' button would be useful. Because caches don't always behave correctly, it is convenient, and users on shared hosting don't have CLI access.

**Comment by PVince81** [comment]
We're past feature freeze => 9.0

**Comment by PVince81** [comment]
PR is here https://github.com/owncloud/core/issues/18475 for APCu

**Comment by PVince81** [comment]
Maybe web could simply invoke CLI to clear the CLI caches... that is, if proc_open works on that setup.

CC @VicDeo as the updater does something like that with OCC

Anyway, backlog for now
