### ISSUE TITLE
The name of the long named groups do not fit in the combobox in users menu.

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16174]
### Steps to reproduce
1. Go to users menu, having several groups. One of them named pretty long
2. Click on the group combobox next to create button

### Expected behaviour
The group should be shown clearly

### Actual behaviour
The name of the group is not shown properly as it is shown in the image attached.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

![grouplongcomb](https://cloud.githubusercontent.com/assets/10596560/7519563/47a54a70-f4e1-11e4-985f-bdeca55da753.png)

**Comment by davitol** [comment]
@jancborchardt

**Comment by jancborchardt** [comment]
Oh, that should be ellipsized. cc @owncloud/designers 

Will fix that.

**Comment by jancborchardt** [comment]
Fix at https://github.com/owncloud/core/pull/16282, please review.

**Comment by davitol** [comment]
![captura de pantalla 2015-05-25 a las 14 49 14](https://cloud.githubusercontent.com/assets/10596560/7797499/4249d400-02ed-11e5-8b94-5b91a30cc017.png)
Using firefox this is the actual behaviour. Maybe is the best option?

**Comment by jancborchardt** [comment]
@davitol that's the way I fixed it. ;)
