### ISSUE TITLE
Users menu. In the column of groups the number of member of the groups is hidden behind the slider if you move the mouse over it.

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16172]
### Steps to reproduce
1. Go to users menu, having more groups than it can be visible in the screen in a row
2. Slide down in the groups tab
3. Get the mouse over the slider 

### Expected behaviour
The number of members of each group should be visible

### Actual behaviour
The number of the members of the groups are hidden behind the slider as it is shown in the picture attached

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 alpha 3

![slider](https://cloud.githubusercontent.com/assets/10596560/7518427/27e61fda-f4db-11e4-9487-025766d86ab3.png)

**Comment by davitol** [comment]
@jancborchardt

**Comment by jancborchardt** [comment]
@raghunayyar you wanna pick that up? cc @owncloud/designers

**Comment by jancborchardt** [comment]
@davitol can not reproduce. Which browser is this? Can you reproduce it in both Firefox and Chrome?

**Comment by davitol** [comment]
@jancborchardt The browser where it is reproduce is Firefox 37.0.2. 
In Chrome V. 42.0.2311 it does not happen.

**Comment by jancborchardt** [comment]
I can still not reproduce this. @owncloud/designers @blizzz can you?

**Comment by MorrisJobke** [comment]
> I can still not reproduce this. @owncloud/designers @blizzz can you?

I can't reproduce. Firefox 38.

Any extensions enabled?

**Comment by MorrisJobke** [comment]
@davitol Which apps are enabled? Which theme?

**Comment by davitol** [comment]
@MorrisJobke 

Enterprise

Enabled:
 - activity: 1.2.3
 - admin_audit: 0.6
 - encryption: 1.0.0
 - enterprise_key: 0.1.0
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.4
 - user_ldap: 0.6.0
 - windows_network_drive: 0.1.1

**Comment by jancborchardt** [comment]
@davitol:
* try disabling the theme. Does it still happen?
* disable all apps. Does it still happen?

**Comment by davitol** [comment]
@jancborchardt it still happens (community, no apps enabled)

![barraoverg](https://cloud.githubusercontent.com/assets/10596560/7728142/adeb16e4-ff0d-11e4-94e5-3eda54218b4e.gif)

**Comment by MorrisJobke** [comment]
@jancborchardt Looks like a Mac OS X feature of making the scrollbar a bit wider once it is hovered.

**Comment by jancborchardt** [comment]
I would say this is a non-issue since it only appears in Firefox on OS X and when hovering. On Webkit (Chrome & Safari) it’s totally fine.
