### ISSUE TITLE
curl_setopt() expects parameter 2 to be long

### ISSUE THREAD

**Issue by trockenasche** [owncloud/core#16179]
### Steps to reproduce
1. Didn't do anything, the error is constantly coming.

### Expected behaviour
Everything these to be working, except that the android client doesn't see any files. But I don't know if these error are related to this error logs.

### Server configuration
**Operating system**: Linux data 3.4.6 #1 SMP Wed Apr 8 09:31:10 CST 2015 x86_64 unknown / QNAP NAS

**Web server:** Apache/2.2.29

**Database:** 5.5.40-MariaDB-log

**PHP version:** PHP/5.5.21

**ownCloud version:** 8.0.3

**Updated from an older ownCloud or fresh install:** updated from 8.0.2

**List of activated apps:** none

**The content of config/config.php:**

```
'dbtype' => 'mysql',
  'version' => '8.0.3.4',
  'dbname' => 'owncloud',
  'installed' => true,
  'forcessl' => true,
  'theme' => '',
  'logtimezone' => 'Europe/Berlin',
  'log_rotate_size' => 10485760,
  'updatechecker' => true,
  'check_for_working_htaccess' => true,
  'log_rotate_sizerotation' => 52428800,
  'maintenance' => false,
  'loglevel' => 2,

```

**Are you using encryption:** no

### Client configuration
**Browser:**

**Operating system:**

#### ownCloud log (data/owncloud.log)
```
Error	 PHP	curl_setopt() expects parameter 2 to be long, string given at /Web/owncloud/lib/private/httphelper.php#72	2015-05-07T18:58:07+02:00
Error	 PHP	Use of undefined constant CURLPROTO_HTTPS - assumed 'CURLPROTO_HTTPS' at /Web/owncloud/lib/private/httphelper.php#72	2015-05-07T18:58:07+02:00
Error	 PHP	Use of undefined constant CURLPROTO_HTTP - assumed 'CURLPROTO_HTTP' at //Web/owncloud/lib/private/httphelper.php#72	2015-05-07T18:58:07+02:00
Error	 PHP	Use of undefined constant CURLOPT_REDIR_PROTOCOLS - assumed 'CURLOPT_REDIR_PROTOCOLS' at /Web/owncloud/lib/private/httphelper.php#72	2015-05-07T18:58:53+02:00
```

**Comment by LukasReschke** [comment]
What cURL version? – Please provide the output of `phpinfo()`.

**Comment by trockenasche** [comment]
curl

cURL support	enabled
cURL Information	7.21.0
Age	3
Features
AsynchDNS	No
CharConv	No
Debug	No
GSS-Negotiate	Yes
IDN	Yes
IPv6	Yes
krb4	No
Largefile	Yes
libz	Yes
NTLM	Yes
SPNEGO	No
SSL	Yes
SSPI	No
Protocols	dict, file, ftp, ftps, http, https, imap, imaps, ldap, ldaps, pop3, pop3s, rtsp, smtp, smtps, telnet, tftp
Host	i686-pc-linux-gnu
SSL Version	OpenSSL/1.0.1m
ZLib Version	1.2.3.3

**Comment by reneretz** [comment]
Same error here

**Comment by trockenasche** [comment]
@reneretz it's a QNAP NAS aswell?

**Comment by reneretz** [comment]
Yes. It is.

**Comment by trockenasche** [comment]
@reneretz do you own an Android device? do see any files with the mobile app?

**Comment by reneretz** [comment]
@trockenasche Just tried it and did not see any of my files. I'm also Operation canceled and Connection closed error.

**Comment by LukasReschke** [comment]
Let me see what we can do about such old cURL versions… That said you might want to ping your vendor to actually provide properly updated cURL versions for performance, feature and security enhancements.

**Comment by LukasReschke** [comment]
Potential fix for stable8 is at https://github.com/owncloud/core/pull/16270, master is at https://github.com/owncloud/core/pull/16269. You are more than welcome to review those changes and report back on the referenced PRs whether it addresses your problems. Thanks :smile:
