### ISSUE TITLE
LDAP with active directory. Members of the group are not shown in the users menu

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16173]
### Steps to reproduce
1. Go to users menu, having several groups.
2. Click on one of the groups

### Expected behaviour
The members of the group should be listed

### Actual behaviour
The members of the group are not listed as it is shown in the image attached

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

![miembrosgrupo](https://cloud.githubusercontent.com/assets/10596560/7518898/18aa48f4-f4de-11e4-9da1-1e5c6555aca2.png)

**Comment by rperezb** [comment]
Checked with 8.1 beta1 and still happens

**Comment by blizzz** [comment]
Did you click on "Verify Settings and Count Groups" on the Groups tab after configuring it?

**Comment by DeepDiver1975** [comment]
> Did you click on "Verify Settings and Count Groups" on the Groups tab after configuring it?

@davitol @rperezb FYI

**Comment by DeepDiver1975** [comment]
Maybe we add a label to the wizard here to let the user know that he has to press the button @blizzz

**Comment by davitol** [comment]
@DeepDiver1975 Yes and they do not appear even clicking "Verify Settings and Count Groups"

**Comment by blizzz** [comment]
@davitol what is set up as group membership attribute? → advanced tab.

**Comment by davitol** [comment]
@blizzz 
Group Search Attributes is empty
Group-Member association: Member AD

**Comment by DeepDiver1975** [comment]
@blizzz what shall we do here now? THX

**Comment by blizzz** [comment]
Cannot reproduce it with the AD in our lab.

@davitol can you provde the whole config? ./occ ldap:show-config

**Comment by blizzz** [comment]
@davitol also, since May 14th there have been commits to master that were also related to groups.  Please retry, it might be fixed meanwhile.

**Comment by davitol** [comment]
@blizzz Tested again with 8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise" and it is NOT fixed. Now it does not appear neither the number nor the members

./occ ldap:show-config
+------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                |                                                                                                                                                                                                            |
+------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport     | 1                                                                                                                                                                                                          |
| hasPagedResultSupport        |                                                                                                                                                                                                            |
| homeFolderNamingRule         |                                                                                                                                                                                                            |
| lastJpegPhotoLookup          | 0                                                                                                                                                                                                          |
| ldapAgentName                |                                                                                                                                                                                                            |
| ldapAgentPassword            | ***                                                                                                                                                                                                        |
| ldapAttributesForGroupSearch |                                                                                                                                                                                                            |
| ldapAttributesForUserSearch  |                                                                                                                                                                                                            |
| ldapBackupHost               |                                                                                                                                                                                                            |
| ldapBackupPort               |                                                                                                                                                                                                            |
| ldapBase                     | dc=owncloudqa,dc=com                                                                                                                                                                                       |
| ldapBaseGroups               | dc=owncloudqa,dc=com                                                                                                                                                                                       |
| ldapBaseUsers                | dc=owncloudqa,dc=com                                                                                                                                                                                       |
| ldapCacheTTL                 | 600                                                                                                                                                                                                        |
| ldapConfigurationActive      | 1                                                                                                                                                                                                          |
| ldapEmailAttribute           |                                                                                                                                                                                                            |
| ldapExperiencedAdmin         | 0                                                                                                                                                                                                          |
| ldapExpertUUIDGroupAttr      |                                                                                                                                                                                                            |
| ldapExpertUUIDUserAttr       |                                                                                                                                                                                                            |
| ldapExpertUsernameAttr       |                                                                                                                                                                                                            |
| ldapGroupDisplayName         | cn                                                                                                                                                                                                         |
| ldapGroupFilter              | (&(|(objectclass=group))(|(cn=DnsAdmins)(cn=Grupo de replicación de contraseña RODC denegada)(cn=Invitados)(cn=Usuarios)))                                                                                 |
| ldapGroupFilterGroups        | DnsAdmins;Grupo de replicación de contraseña RODC denegada;Invitados;Usuarios                                                                                                                              |
| ldapGroupFilterMode          | 0                                                                                                                                                                                                          |
| ldapGroupFilterObjectclass   | group                                                                                                                                                                                                      |
| ldapGroupMemberAssocAttr     | member                                                                                                                                                                                                     |
| ldapHost                     | fr-vm02.solidgear.es                                                                                                                                                                                       |
| ldapIgnoreNamingRules        |                                                                                                                                                                                                            |
| ldapLoginFilter              | (&(&(|(objectclass=person)(objectclass=user)))(samaccountname=%uid))                                                                                                                                       |
| ldapLoginFilterAttributes    |                                                                                                                                                                                                            |
| ldapLoginFilterEmail         | 0                                                                                                                                                                                                          |
| ldapLoginFilterMode          | 0                                                                                                                                                                                                          |
| ldapLoginFilterUsername      | 1                                                                                                                                                                                                          |
| ldapNestedGroups             | 0                                                                                                                                                                                                          |
| ldapNoCase                   | 0                                                                                                                                                                                                          |
| ldapOverrideMainServer       |                                                                                                                                                                                                            |
| ldapPagingSize               | 500                                                                                                                                                                                                        |
| ldapPort                     | 2005                                                                                                                                                                                                       |
| ldapQuotaAttribute           |                                                                                                                                                                                                            |
| ldapQuotaDefault             |                                                                                                                                                                                                            |
| ldapTLS                      | 0                                                                                                                                                                                                          |
| ldapUserDisplayName          | displayName                                                                                                                                                                                                |
| ldapUserFilter               | (&(|(objectclass=person)(objectclass=user))(|(|(memberof=CN=Invitados,CN=Builtin,DC=owncloudqa,DC=com)(primaryGroupID=546))(|(memberof=CN=Usuarios,CN=Builtin,DC=owncloudqa,DC=com)(primaryGroupID=545)))) |
| ldapUserFilterGroups         | Invitados;Usuarios                                                                                                                                                                                         |
| ldapUserFilterMode           | 0                                                                                                                                                                                                          |
| ldapUserFilterObjectclass    | person;user                                                                                                                                                                                                |
| ldapUuidGroupAttribute       | auto                                                                                                                                                                                                       |
| ldapUuidUserAttribute        | auto                                                                                                                                                                                                       |
| turnOffCertCheck             | 0                                                                                                                                                                                                          |
+------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

**Comment by MorrisJobke** [comment]
> Now it does not appear neither the number nor the members

Number was removed because of performance reasons ;)

**Comment by blizzz** [comment]
Your User Filter is:

```
&(|(objectclass=person)(objectclass=user))(|(|(memberof=CN=Invitados,CN=Builtin,DC=owncloudqa,DC=com)(primaryGroupID=546))(|(memberof=CN=Usuarios,CN=Builtin,DC=owncloudqa,DC=com)(primaryGroupID=545))))
```

Or in pretty:

```
&(
    |(
        objectclass=person
    )
    (objectclass=user)
)
(|
    (|
        (memberof=CN=Invitados,CN=Builtin,DC=owncloudqa,DC=com)
        (primaryGroupID=546)
    )
    (|
        (memberof=CN=Usuarios,CN=Builtin,DC=owncloudqa,DC=com)
        (primaryGroupID=545)
    )
)
)
```

At least there is one bracket to much, i would wonder that it works anyway. Don't you see "Bad search filter (-7)" errors in your log?

**Comment by blizzz** [comment]
@davitol your user filter in pretty is

```
(&
    (|
        (objectclass=person)
        (objectclass=user)
    )
    (|
        (|
            (memberof=CN=Invitados,CN=Builtin,DC=owncloudqa,DC=com)
            (primaryGroupID=546)
        )
        (|
            (memberof=CN=Usuarios,CN=Builtin,DC=owncloudqa,DC=com)
            (primaryGroupID=545)
        )
    )
)
```

Which means: all users are listed that are either of objectclass person or user and at the same time member of the group Invitados or Usuarios.

The selected group is a different one. May it be that none of the selected groups members are also member of Invitados or Usuarios?

**Comment by davitol** [comment]
Tested with "version":"8.1.0.7","versionstring":"8.1 RC1","edition":"Enterprise" Fixed :+1:
It is need to test in previous versions

**Comment by SergioBertolinSG** [comment]
Tested in oc 7.0.5, it has the bug as well. Worthy/feasible to backport the fix?

**Comment by MorrisJobke** [comment]
> Tested in oc 7.0.5, it has the bug as well. Worthy/feasible to backport the fix?

Is it also broken in stable8?

**Comment by davitol** [comment]
Nop, in stable8 it works fine

**Comment by blizzz** [comment]
No plans to backport anything to 7 (fix, if there is one, is unknown). 

Glad it works now in 8.1.
