### ISSUE TITLE
How to increase memory_limit > 512M

### ISSUE THREAD

**Issue by hostingnuggets** [owncloud/core#16171]
I just upgraded to ownCloud 8.0.3 and my gallery has stopped working due to PHP memory exhaustion as you can see below:

```
2015/05/07 16:32:50 [error] 10198#0: *303 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 40704 bytes) in /var/www/owncloud/lib/private/image.php on line 489" while reading upstream, client: 10.0.0.10, server: cloud.local, request: "GET /index.php/apps/gallery/ajax/thumbnail/batch?token=...
```

So I tried to increase the memory_limit PHP setting to 1024M but somehow I still get the same error message and phpInfo() shows a local value of memory_limit to still be 512M. This means that somehow ownCloud is overriding my PHP setting. Does someone know where this is done?

Btw: I am using nginx 1.6.2 with PHP 5.5.24.

**Comment by RealRancor** [comment]
Hi,

see the .user.ini shipped with OC.

**Comment by hostingnuggets** [comment]
Thanks that was it... Upgrading the memory_limit to 768M fixed the Gallery app loading. Now still need to figure out why the contacts app shows the spinning wheel non-stop and nothing else.

**Comment by RealRancor** [comment]
@hostingnuggets Feel free to close this issue if it was fixed.

Btw. the issue tracker of contacts apps is available here:

https://github.com/owncloud/contacts/issues

There you might find some infos about your contacts app issue.

**Comment by hostingnuggets** [comment]
@RealRancor thanks yes I have opened an issue there directly: https://github.com/owncloud/contacts/issues/893
