### ISSUE TITLE
Upgrading from 8.0.3 to 8.1 with encryption doesn't warn you to migrate encryption.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16177]
### Steps to reproduce

1. Install 8.0.3 server.
2. Enable encryption.
3. Upload a lot of files.
4. Upgrade to 8.1 alpha3.

### Expected behaviour
I see two options:
1. Old encryption is disabled and new one enabled and migrated keys automatically in a transparent way when upgrading.
2. Warn the user that his server is unusable and that he has to enable new encryption app, go to the admin page, enable it there and do the migration.

### Actual behaviour
User is not warned at all, an unusable oc server happens until the user do the migration.
Also the migration doesn't show a progress and it seems stucked until it ends.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.4","versionstring":"8.1 alpha 3","edition":""}

**Updated from an older ownCloud or fresh install:**
Updated from 8.0.3

**List of activated apps:**
Default in enterprise edition.
Encryption.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
Yes

**Logs**
```
```
### Client configuration

**browser**
Chrome 41

**Comment by SergioBertolinSG** [comment]
cc @schiesbn

**Comment by schiesbn** [comment]
You should get a warning that you need to upgrade the encryption keys. But I'm not sure if it was already part of the alpha release. Please try master.

**Comment by SergioBertolinSG** [comment]
Tested upgrading from 8.0.3 to 8.1 beta 1, there's no warning, and users can't use server.
after doing occ encryption:migrate files are usable. But with old encryption. Files are still encrypted the old way. And new encryption wasn't enabled.

**Comment by SergioBertolinSG** [comment]
after using occ encryption:migrate, i didn't enabled encryption:enable and i saw the old headers in the file,  that confused me.
After using encryption:enable server is ready to use the default encryption module again.

I guess this should be documented to have new encryption ready.

Anyway user is not warned when he can't use the server if migration is needed after upgrade.

**Comment by schiesbn** [comment]
If you upgrade to oc8.1 and enable the new encryption without migrating the keys you will see this warning the next time you login:

![1](https://cloud.githubusercontent.com/assets/1589737/7534308/c323e18c-f579-11e4-967e-433bea3e17dc.png)

If you enable the new encryption in the web interface you see:

![2](https://cloud.githubusercontent.com/assets/1589737/7534327/fa9f746e-f579-11e4-9011-7a003bd589f9.png)

For large installation there will be no button but will point the admin to the occ tool

I don't think we can do much more here.

**Comment by SergioBertolinSG** [comment]
The problem i see is when upgrading from a 8.0.3  version with encryption enabled to 8.1.
But without doing migration and having not enabled the encryption module yet.
You can open the server, the files are there, no warnings, you try to download a file and web fails.

**Comment by schiesbn** [comment]
But there is nothing we can do about on a technical level. I think this "problem" needs to be addressed in the release notes which tells the user that we now have an new encryption and if they use encryption they need to enable server-side encryption, load the default module and run the migrate keys command.

**Comment by jnfrmarks** [comment]
@MTRichards @SergioBertolinSG @schiesbn 

Can we leave the server in maintenance mode until encryption has been properly configured in 8.1?  I'm concerned about usability here.

Should the message about migration above be for oC <= 8.1 and not 8.0?

**Comment by schiesbn** [comment]
> Can we leave the server in maintenance mode until encryption has been properly configured in 8.1? I'm concerned about usability here.

How do you want to detect this? Honestly every (semi-)professional admin read the release notes and upgrade notes before updating a productive server. If he doesn't do it it is really not our fault. Also there is no data-lose or anything if he forget to enable the new encryption.

> Is there anyway to print out some type of status (either dots or %complete) when doing the migration so users know that something is happening? 

The command line tool print out some status like:

````
Migrate keys for userX
Migrate keys for userX
...
````

and some more... but I'm sure you already saw it. 

As for the web interface, as already said this option is only available for small installation. Large installations will not even have the possibility to start the migration on the web interface. So this is not something which takes ages. The user still gets some feedback with a label called "Migration started …" and a success/error message at the end. Also if he tries to navigate away from the settings page while the migration is running he gets a warning "Migration in progress. Please wait until the migration is finished"

Personally I think this is more than enough for a fallback solution for small installations where the admin doesn't have shell access (this means really small hosters for home users)

**Comment by jnfrmarks** [comment]
@MTRichards

**Comment by jnfrmarks** [comment]
@SergioBertolinSG 

You commented that when the files are migrated, they are migrated with the old encryption model.  Is that still true?

**Comment by SergioBertolinSG** [comment]
No, that happens if you just upgrade without doing migration and without enabling default encryption module after upgrade.
The problem here is a situation when a user doesn't follow steps and upgrade without taking into account the new encryption. 
For me just showing a warning in this situation is enough.
If a warning can't be done, just clarify it in documentation and close this.

**Comment by DeepDiver1975** [comment]
> If a warning can't be done, just clarify it in documentation and close this.

@carlaschroder are you aware of this? Let me know if you need more information - THX

**Comment by carlaschroder** [comment]
How are users on shared hosting going to migrate keys?  They can't just go into CPanel, or whatever control they're using, and copy the keys in their file manager because they're different. On 8.0:

data/owncloud_private_key
data/public-keys
data/<user>/files_encryption
data/files_encryption

On 8.1:

data/<user>/files_encryption
data/files_encryption

**Comment by carlaschroder** [comment]
1st draft: https://github.com/owncloud/documentation/pull/1187

**Comment by DeepDiver1975** [comment]
case closed - documentation is in place

**Comment by SergioBertolinSG** [comment]
checked upgrading from last stable8 to last stable8.1, user is warned correctly when trying to open the file and when enabling the default module.
