### ISSUE TITLE
Debian: update failed - owncloud : Hängt ab von: owncloud-server (= 8.0.3-1) aber 8.0.2-8 ist installiert

### ISSUE THREAD

**Issue by berni123** [owncloud/core#16188]
apt repo: deb http://download.opensuse.org/repositories/isv:/ownCloud:/community/Debian_7.0/ /

apt-get upgrade:

Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 owncloud : Hängt ab von: owncloud-server (= 8.0.3-1) aber 8.0.2-8 ist installiert
 owncloud-3rdparty : Hängt ab von: owncloud-server (= 8.0.3-1) aber 8.0.2-8 ist installiert
 owncloud-app-activity : Hängt ab von: owncloud-server (= 8.0.3-1) aber 8.0.2-8 ist installiert
...

using aptitude update
it works

Regards,
Bernd

**Comment by LukasReschke** [comment]
cc @jnweiger

**Comment by LukasReschke** [comment]
cc @jnweiger

**Comment by RealRancor** [comment]
Hi,

the output of:

apt-cache policy owncloud-server

could be interesting here. But seems you already did the upgrade?

**Comment by berni123** [comment]
Yes I did the upgrade, it works with aptitude upgrade but does not work with apt-get upgrade ...

**Comment by openpaul** [comment]
I have the same error message.

apt-cache policy owncloud-server
```
???@???:~$ sudo apt-cache policy owncloud-server
owncloud-server:
  Installiert:           8.0.2-8
  Installationskandidat: 8.0.3-2
  Versionstabelle:
     8.0.3-2 0
        500 http://download.opensuse.org/repositories/isv:/ownCloud:/community/Debian_7.0/  Packages
 *** 8.0.2-8 0
        100 /var/lib/dpkg/status
```

**Comment by YogaKick** [comment]
Same issue here. Just to losen thigns up, this time an error message in English ;)

apt-get update: ok
apt-get upgrade:

Reading state information... Done
You might want to run 'apt-get -f install' to correct these.
The following packages have unmet dependencies:
 owncloud : Depends: owncloud-server (= 8.0.3-2) but 8.0.2-5 is installed
 owncloud-3rdparty : Depends: owncloud-server (= 8.0.3-2) but 8.0.2-5 is installed
 owncloud-app-activity : Depends: owncloud-server (= 8.0.3-2) but 8.0.2-5 is installed
...
owncloud-config-apache : Depends: owncloud-server (= 8.0.3-2) but 8.0.2-5 is installed
E: Unmet dependencies. Try using -f.

apt-get install -f:

Do you want to continue? [Y/n] Y
(Reading database ... 236146 files and directories currently installed.)
Preparing to unpack .../owncloud-server_8.0.3-2_all.deb ...
Unpacking owncloud-server (8.0.3-2) over (8.0.2-5) ...
dpkg: error processing archive /var/cache/apt/archives/owncloud-server_8.0.3-2_all.deb (--unpack):
 trying to overwrite '/var/www/owncloud/.htaccess', which is also in package owncloud-config-apache 8.0.3-2
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/owncloud-server_8.0.3-2_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

Same error goes for aptitude upgrade and install -f

**Comment by YogaKick** [comment]
Executing install -f several times didn't work for me.

However i managed to fix it using this thread: https://github.com/owncloud/core/issues/16007

**Comment by PVince81** [comment]
Is this still an issue with 8.0.5 ?

**Comment by Kawohl** [comment]
FIxed and closed
