### ISSUE TITLE
Owncloud share file not support video file player how can i include video also

### ISSUE THREAD

**Issue by kumarsanjeet101** [owncloud/core#16180]
When i am sharing a wmv file show invalid error then  i was checked the function lib/private/initProviders   
but not enable video file only mp3 and text file then how can i play my video file in owncloud

**Comment by kumarsanjeet101** [comment]
@LukasReschke 
@karlitschek 

no video with supported format and mime type found. i will add config.sample.php
OC\Preview\Movie enable and change the class name movies to movie what the solution for video thumbnail and video player .

**Comment by kumarsanjeet101** [comment]
@LukasReschke 
@karlitschek 

no video with supported format and mime type found. i will add config.sample.php
OC\Preview\Movie enable and change the class name movies to movie what the solution for video thumbnail and video player .

**Comment by DeepDiver1975** [comment]
@kumarsanjeet101 I'm having a hard time to understand your report. Please use the issue template - THX

https://github.com/owncloud/core/blob/master/CONTRIBUTING.md
