### ISSUE TITLE
LDAP wizard configuration: Configuration status does not update right when modifying Base DN

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16192]
### Steps to reproduce

1. Go to LDAP wizard configuration.
2. Configure a right configuration with an Active Directory
3. When we get Configuration OK, move to the Server tab again
4. Modify Base DN with a wrong value

### Expected behaviour

Configuration OK status should turn into Configuration incorrect

### Actual behaviour
Configuration status keeps in Configuration OK

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 beta 1

**Updated from an older ownCloud or fresh install:** fresh install

![basednown](https://cloud.githubusercontent.com/assets/10596560/7533207/cd50a96a-f56f-11e4-948c-ed496a02fbc3.png)
![ldapconsole](https://cloud.githubusercontent.com/assets/10596560/7533211/d551b7a8-f56f-11e4-84e5-a457f917085c.png)

**Comment by MorrisJobke** [comment]
cc @blizzz

**Comment by blizzz** [comment]
That is the case in older versions as well. Initially we just check the existence of the value. Agreed that it makes sense to add it to the functionality test.

**Comment by davitol** [comment]
:+1: fixed
