### ISSUE TITLE
Expain Federation to user

### ISSUE THREAD

**Issue by jospoortvliet** [owncloud/core#16190]
Add a “Federation” section to the personal page which shows the users' personal Federation Id.

Something like:

Federation
========
Your federation Id is "xxx@xxx.de/yyy”
Users on other ownCloud servers can share something with you by entering this ID into their sharing dialog. Find out more about federation on http://owncloud.org/federation (or documentation link?)

Share you Id on:
- Twitter
- Facebook
- Google+
- Diaspora
- website (provide website code)

Message:
“Share with me through my #ownCloud federation Id xxx@xxx/yyy see http://owncloud.org/federation"
Website code can be similar to above, just in html.

Text can perhaps use more discussion.

Depends on a page on owncloud.org/federation - owncloud/owncloud.org#544

For the future we have lots of ideas for improvement - that's for 8.2.

**Comment by PVince81** [comment]
@owncloud/designers

**Comment by jancborchardt** [comment]
@schiesbn any news here?

**Comment by schiesbn** [comment]
I will start working on it today and/or tomorrow

**Comment by schiesbn** [comment]
@jancborchardt do you already have some nice icons we should use for the networks listed above?

**Comment by schiesbn** [comment]
reopened because we still need a small adjustment to the webpage, @jospoortvliet will take care of it as discussed here: https://github.com/owncloud/core/pull/16692#issuecomment-113081588

**Comment by schiesbn** [comment]
- [ ] broken links need to be fixed on https://owncloud.org/federation https://github.com/owncloud/owncloud.org/issues/579

**Comment by jospoortvliet** [comment]
![screenshot 17](https://cloud.githubusercontent.com/assets/551757/8251674/d4cc6474-167e-11e5-9365-0406a3d00e91.png)
with my (rather long) ownCloud ID
![screenshot 17](https://cloud.githubusercontent.com/assets/551757/8251680/e6646646-167e-11e5-96e7-0ba1e5183b3f.png)
with a reasonable ID
![screenshot 17](https://cloud.githubusercontent.com/assets/551757/8251686/f361ceb0-167e-11e5-8941-39ff7376b6bb.png)
Without entering any ID

What do you think @schiesbn @jancborchardt @karlitschek

**Comment by jospoortvliet** [comment]
http://localhost:5000/federation/#guyfawkes@localhost/owncloud is an URL which thus works now.

**Comment by jospoortvliet** [comment]
Tested in firefox, conqueror and chromium.

**Comment by schiesbn** [comment]
looks great! :+1:

**Comment by karlitschek** [comment]
cool :+1:

**Comment by LukasReschke** [comment]
Great stuff, a little security nitpick though: Please escape the output or use jQuery's `.text` functionalities. This will introduce a really bad XSS vulnerability on owncloud.org otherwise.

See https://github.com/owncloud/owncloud.org/commit/fdefdf0eef67bc666320ded7b20d5d55294fb0c6#commitcomment-11766050

**Comment by LukasReschke** [comment]
With jQuery a secure approach would be the following:

```html
<script type='text/javascript' src='//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js'></script>

<script>
$(document).ready(function() {
	if(window.location.hash) {
		$('#userName').text(window.location.hash.substring(1));
    }  
 });
</script>

<span id="userName">username@owncloudserver/owncloud</span>
```

**Comment by jancborchardt** [comment]
Good stuff :+1: 

Except one thing: The example ID should be the same as it is in ownCloud: `username@example.com/owncloud`

**Comment by jospoortvliet** [comment]
All changes above done.  Links fixed, too, except for the one which needs a blog by frank to be released. Will fix that link as soon as that blog is out... promise :D

**Comment by jospoortvliet** [comment]
test on https://staging.owncloud.org/federation/

**Comment by jancborchardt** [comment]
Just noticed: Elsewhere we call it »Federated Cloud ID«. On the page it’s called »Federation ID«. Can you change that to reflect how we call it in ownCloud?

**Comment by jospoortvliet** [comment]
@jancborchardt of course, done: https://github.com/owncloud/owncloud.org/pull/581

**Comment by jancborchardt** [comment]
Thanks!
