### ISSUE TITLE
You don’t have permission to upload or create files here after update from oc7 to 8

### ISSUE THREAD

**Issue by julian-weiland** [owncloud/core#16198]
After i updated from ownCloud 7 to 8 i get follwing message displayed when I'm logged in 
"You don’t have permission to upload or create files here"
So I only can read but not write to any folder.
I created another user for testing purpose. New user does not have this problem. 
If found this:
https://github.com/owncloud/core/issues/11449

But when i do following command:
`php console.php files:scan --all`

I get this Message:
`Data directory (/www/htdocs/w01276f2/relay-data) is invalid
Please check that the data directory contains a file ".ocdata" in its root.

Data directory (/www/htdocs/w01276f2/relay-data) not writable by ownCloud
Permissions can usually be fixed by <a href="http://doc.owncloud.org/server/8.0/go.php?to=admin-dir_permissions" target="_blank">giving the webserver write access to the root directory</a>.`

So I checked the relay-data folder for the .ocdata file and it has one. I also checked the permissions and they are also right. (remember the other user can write to the data folder)

I have no idea what to check next.

Any Idea why this happens?

**Comment by DeepDiver1975** [comment]
> After i updated from ownCloud 7 to 8 i get follwing message displayed when I'm logged in

how did you upgrade? Using the console I assume.

Generally speaking: The user which runs the web server has to be the owner of all files within the data dir.

**Comment by PVince81** [comment]
Any more luck with 8.0.6 or 8.1.1 ?
The scan command should now properly check that it's running as the correct user.

Feel free to reopen if you're still having this issue with the newer versions.
