### ISSUE TITLE
Admin user can change password of a user with recovery password enabled.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16196]
### Steps to reproduce

1. Enable encryption app.
2. Enable encryption module in admin page.
3. Put a recovery password in the admin page.
4. Create a user1.
5. Login with user1 and enable recovery password.
6. Login with admin.
7. Go to users page.
8. Change password to user1 without entering recovery password.

### Expected behaviour
Error message.

### Actual behaviour
Password is changed.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Updated from 8.0.3

**List of activated apps:**
Default in enterprise edition.
Encryption.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
Yes

**Logs**
```
```
### Client configuration

**browser**
Chrome 41

**Comment by SergioBertolinSG** [comment]
this PR could solve it:
https://github.com/owncloud/core/pull/15978

**Comment by schiesbn** [comment]
pr merged
