### ISSUE TITLE
It is not possible to share a file/folder just after renaming it from the WEB

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/core#16191]
### Steps to reproduce
1. Open the Owncloud Client
2. Go to Open Folder "ownCloud" 
3. Create a new Folder, call dd
4. Right click on the folder sync folder
5. Select share with ownCloud
6. Click in "Password protect"
7. Write the password
8. Click Enter
9. Click to the Shared icon, and the same time rename the Folder
10. Click Enter

### Expected behaviour
If you click the share icon has to work

### Actual behaviour
If you click the share icon again does not work , it needs web owncloud closed

### Server configuration
###Version Desktop
Version 1.8.1-nightly20150508 (build 5006)

Web server:
{"installed":true,"maintenance":false,"version":"8.0.3.4","versionstring":"8.0.3","edition":"Enterprise"}

**Comment by schiesbn** [comment]
Not sure If I understand the problem correctly. All the steps you describe are performed on the desktop client, right? Where is the part where you rename the file?

**Comment by jnfrmarks** [comment]
@SergioBertolinSG 

Can you please update with your steps from the deletedFiles test plan?

**Comment by Dianafg76** [comment]
The Issue is in the Owncloud SERVER Client. And the steps are:

  1. Open the Owncloud Client
  2. Create a new Folder, call dd
  3. Shared the Folder dd
  4. Click in "Password protect"
  5. Write the password
  6. Click Enter
  7. Click to the Shared icon, and the same time rename the Folder
  8. Click Enter

**Comment by SergioBertolinSG** [comment]
I am seeing the problem (this is in the web ui):

*My steps*
1. Click in the share button of a file or folder.
2. With the sharing box open, rename the file or folder.
3. Click in sharing icons again, of that file or another.

Observed:
Sharing buttons doesn't work anymore.

**Comment by schiesbn** [comment]
@rullzer can you have a look at this? Thanks!

**Comment by rullzer** [comment]
So this is some dark js stuff. Basically what happens is the rename kills the sharing dialog.

However, the system is now in a state where it thinks that the share dialog is still open. So when you click on share it thinks well I should propbably first close the current dialog.

It tries to do that at [share.js:622](https://github.com/owncloud/core/blob/master/core/js/share.js#L622) but fails since the slideUp won't work anymore. And thus the callback is not executed. 

Probably not using the complete but the always callback should fix the problem... Let me try :)

**Comment by rullzer** [comment]
nope... the always callback does not solve the problem... @PVince81 could you help with the JS magic?

**Comment by PVince81** [comment]
Yeah, probably the event firing order is wrong or the rename action is preventing the event to reach the dialog (preventDefault()). Since this is only sev3-medium I suggest to defer to 8.2.

**Comment by rullzer** [comment]
Fine by me :)

**Comment by PVince81** [comment]
@Dianafg76 @rullzer does it still happen in the sidebar on 8.2 beta ?

**Comment by rullzer** [comment]
@PVince81 seems solved since the sidebar is updated on the rename

@Dianafg76 @SergioBertolinSG if you can still reproduce then please reopen this.
