### ISSUE TITLE
When the file .txt is shared by link with Internet Explorer you can't see the icon

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/core#16195]
### Steps to reproduce
1. Open your DESKTOP client
2. Go to Open Folder "ownCloud"
3. Create a new file, calle bb.TXT
4. Right click on the folder sync folder
5. Select share with ownCloud
6. Click to the link

### Expected behaviour
You can see de icon

### Actual behaviour
The Internet Explorer is open, but you can't see the Icon

![screen shot 2015-05-08 at 11 14 54](https://cloud.githubusercontent.com/assets/12032058/7533721/3f8006b2-f574-11e4-9989-a4b6d83b8886.png)

### Server configuration
###Version Desktop
Version 1.8.1-nightly20150508 (build 5006)

Web server:
{"installed":true,"maintenance":false,"version":"8.0.3.4","versionstring":"8.0.3","edition":"Enterprise"}

**Comment by jancborchardt** [comment]
Maybe a preview generation issue? @georgehrke @MorrisJobke?

**Comment by MorrisJobke** [comment]
On stable8 this works (even with IE8):

![bildschirmfoto von 2015-05-12 15-30-16](https://cloud.githubusercontent.com/assets/245432/7588199/d99b946a-f8bb-11e4-94ec-2a6e3ebe8d74.png)

@Dianafg76 Which browser is this?

**Comment by LukasReschke** [comment]
I guess this is because the txt file is empty? Then previews seem indeed to be broken.

**Comment by Dianafg76** [comment]
@MorrisJobke, is IE8

**Comment by MorrisJobke** [comment]
Could be solved with #12546

**Comment by Dianafg76** [comment]
I close the issue because it is working
