### ISSUE TITLE
If admin user changes password using recovery password of a user while he is logged in, he is not warned to relogin.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16197]
### Steps to reproduce
1. Enable encryption app.
2. Enable encryption module in admin page.
3. Put a recovery password in the admin page.
4. Create a user1.
5. Login with user1 and enable recovery password.
6. Keep user1 logged in.
7. Login with admin using a different browser.
8. Go to users page.
9. Change password to user1 entering recovery password correctly first.
### Expected behaviour

User1 gets an error message warning him to do relogin.
### Actual behaviour

Password is changed. User1 is not warned at all.
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Updated from 8.0.3

**List of activated apps:**
Default in enterprise edition.
Encryption.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
Yes

**Logs**

```
```
### Client configuration

**browser**
Chrome 41

**Comment by schiesbn** [comment]
typically the admin needs to recover the users files because the user lost his password. In this case we can assume that the user isn't logged in. If the user is logged in there is no reason why the admin should recover the users files.

**Comment by SergioBertolinSG** [comment]
Ok it is an edge situation. But users aren't warned at all.

**Comment by jnfrmarks** [comment]
@SergioBertolinSG 

What's the behavior in this case when encryption isn't enabled and the admin changes a user's password while they are logged in?  My guess is that the user's session is still valid and that they are not notified.

**Comment by SergioBertolinSG** [comment]
Without encryption, session is still valid for the user, yes.

**Comment by schiesbn** [comment]
Yes, that's the problem. The user has a valid session with a un-encrypted private key and everything he needs. So there is no way to detect that the key is no longer the right one. 

But as said, that's only a theoretical problem in a test scenario. In a real world the user will never ask the admin to recover his login while he is logged in and edit files.

**Comment by SergioBertolinSG** [comment]
There is no way to detect a password change for a user logged in? too expensive to check?

**Comment by schiesbn** [comment]
No, first I would consider it to expensive to test it on every request. Just for such a corner case for which I still miss the real world scenario. And second how do you want to test if the password changed? You could try to re-authorize with the "old" password but this would mean that we would need to cache your login password for the whole session somewhere in plain text -> security nightmare.

**Comment by PVince81** [comment]
Corner case, won't fix.

Also we recommend master key now
