### ISSUE TITLE
File_get_contents attempts to open the wrong file after rename

### ISSUE THREAD

**Issue by Fmstrat** [owncloud/core#16202]
The issue with the below example is that after renaming `Test 1.txt` to `Test 2.txt`, and then attempting to grab contents of `Test 2.txt`, file_get_contents for some reason attempts to read `Test 1.txt`. I can only imagine that the rename function is setting a variable that is overriding the file_get_contents, but I'm sure there could be other underlying issues.

Steps to reproduce
-----------
- Create "Test 1.txt" in the root of the user's filesystem
- Add the following code to any plugin:

                error_log('1');
                \OC\Files\Filesystem::rename("Test 1.txt", "Test 2.txt");
                error_log('2');
                $test = \OC\Files\Filesystem::file_get_contents("Test 2.txt");
                error_log('3');

- Refresh the page containing the plugin

Expected behavior
-------
1, 2, and 3 will be printed to error log, `Test 1.txt` will be renamed to `Test 2.txt`, and `Test 2.txt` will be read into the `$test` variable.

Actual behavior
-----
1, 2, and the error below are printed to the log, and `Test 1.txt` is renamed but reading `Test 2.txt` fails.

Server configuration
---
*Operating system:*
Ubuntu 15.04, Ubuntu 14.04 both tested

*Web server:*
Apache

*Database:*
Sqlite

*PHP version:*
5.5.9

*ownCloud version: (see ownCloud admin page)*
8.0.2

*Updated from an older ownCloud or fresh install:*
Updated from 8.0

*List of activated apps:*
Default
ownNote (Removed all other code other than the above test to be safe)

*The content of config/config.php:*

	$CONFIG = array (
	  'instanceid' => '<removed>',
	  'passwordsalt' => '<removed>',
	  'secret' => '<removed>',
	  'trusted_domains' => 
	  array (
		0 => '192.168.56.50',
	  ),
	  'datadirectory' => '/var/www/owncloud/data',
	  'overwrite.cli.url' => 'https://192.168.56.50/owncloud',
	  'dbtype' => 'sqlite3',
	  'version' => '8.0.2.0',
	  'installed' => true,
	  'forcessl' => true,
	  'forceSSLforSubdomains' => true,
	  'theme' => '',
	  'maintenance' => false,

*Are you using external storage, if yes which one: local/smb/sftp/...*
No

*Are you using encryption:*
No

*Logs*

	==> /var/log/apache2/error.log <==
	[Thu May 07 23:11:55.245508 2015] [:error] [pid 2574] [client 192.168.56.1:55009] 1, referer: https://192.168.56.50/owncloud/index.php/apps/ownnote/
	[Thu May 07 23:11:55.316388 2015] [:error] [pid 2574] [client 192.168.56.1:55009] 2, referer: https://192.168.56.50/owncloud/index.php/apps/ownnote/

	==> /var/www/owncloud/data/owncloud.log <==
	{"reqId":"4af0c28a32885e51c8945856c552fe77","remoteAddr":"192.168.56.1","app":"PHP","message":"fopen(\/var\/www\/owncloud\/data\/admin\/files\/Test 1.txt): failed to open stream: No such file or directory at \/var\/www\/owncloud\/apps\/files_locking\/lib\/lock.php#83","level":3,"time":"2015-05-08T03:11:55+00:00"}
	{"reqId":"4af0c28a32885e51c8945856c552fe77","remoteAddr":"192.168.56.1","app":"index","message":"Exception: {\"Message\":\"Could not obtain lock type 1 on \\\"\\\/var\\\/www\\\/owncloud\\\/data\\\/admin\\\/files\\\/Test 1.txt\\\".\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_locking\\\/lib\\\/lockingwrapper.php(44): OCA\\\\Files_Locking\\\\Lock->addLock(1, NULL)\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_locking\\\/lib\\\/lockingwrapper.php(80): OCA\\\\Files_Locking\\\\LockingWrapper->getLock('files\\\/Test 2.tx...', 1)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(212): OCA\\\\Files_Locking\\\\LockingWrapper->file_get_contents('files\\\/Test 2.tx...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(836): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->file_get_contents('files\\\/Test 2.tx...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(356): OC\\\\Files\\\\View->basicOperation('file_get_conten...', 'Test 2.txt', Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(645): OC\\\\Files\\\\View->file_get_contents('Test 2.txt')\\n#6 \\\/opt\\\/ownnote\\\/lib\\\/backend.php(154): OC\\\\Files\\\\Filesystem::file_get_contents('Test 2.txt')\\n#7 \\\/opt\\\/ownnote\\\/controller\\\/ownnoteapicontroller.php(45): OCA\\\\OwnNote\\\\Lib\\\\Backend->getListing('Notes', false)\\n#8 [internal function]: OCA\\\\OwnNote\\\\Controller\\\\OwnnoteApiController->ajaxindex()\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(158): call_user_func_array(Array, Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(86): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\OwnNote\\\\Controller\\\\OwnnoteApiController), 'ajaxindex')\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(97): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\OwnNote\\\\Controller\\\\OwnnoteApiController), 'ajaxindex')\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(44): OC\\\\AppFramework\\\\App::main('OwnnoteApiContr...', 'ajaxindex', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#13 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(767): OC\\\\Route\\\\Router->match('\\\/apps\\\/ownnote\\\/a...')\\n#16 \\\/var\\\/www\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#17 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/files_locking\\\/lib\\\/lock.php\",\"Line\":246}","level":4,"time":"2015-05-08T03:11:55+00:00"}

**Comment by LukasReschke** [comment]
cc @icewind1991

**Comment by Fmstrat** [comment]
As a note, this also in some way seems to have wreaked havok on my file db. For test files that were renamed, if I delete them, they're still coming up in the queries for file listings, even though they don't show up in the WebUI. I'm unsure if this is resulting for the same issue or everything I've done that led me to find this issue, however.

**Comment by PVince81** [comment]
@Fmstrat maybe the file wasn't renamed at all ? You could check if the return code is "true" and also check `\OC\Files\Filesystem::file_get_contents("Test 1.txt");` and `\OC\Files\Filesystem::file_get_contents("Test 2.txt");`

In general you should rather use the public API which starts at `\OC::$user->getUserFolder()`, see http://api.owncloud.org/classes/OCP.Files.Node.html

**Comment by PVince81** [comment]
Please try again with OC 8.2.2.

If this still happens, feel free to reopen.
