### ISSUE TITLE
REHL Repo issue

### ISSUE THREAD

**Issue by iliyasbasir** [owncloud/core#16204]
[3119,2983]

#### Summary of issue:
customer that use our repo via RHEL  they are using the“collections” repo from Red Hat to address the need for PHP 5.4 however, when they go to do the upgrade/install it is not finding the needed PHP
(as when it is installed in collections it seems to to using some non-standard conventions to puts the code some place other than where our scripts are looking for it so the install fails for missing PHP).

#### Problem description: 

When using the SCL PHP, the owncloud-server-scl-php54-8.0.2-16.1.noarch.rpm<https://download.owncloud.com/download/repositories/8.0/RHEL_6_PHP54/noarch/owncloud-server-scl-php54-8.0.2-16.1.noarch.rpm> package provides owncloud-server-core = 8.0.2, however owncloud-enterprise-app-admin_audit-8.0.2-28.1.noarch.rpm<https://download.owncloud.com/download/repositories/8.0/RHEL_6_PHP54/noarch/owncloud-enterprise-app-admin_audit-8.0.2-28.1.noarch.rpm>, which is a dependency of owncloud-enterprise-8.0.2-28.1.noarch.rpm<https://download.owncloud.com/download/repositories/8.0/RHEL_6_PHP54/noarch/owncloud-enterprise-8.0.2-28.1.noarch.rpm>, requires owncloud-server = 8.0.2. This will resolve in dependency issues since owncloud-server-scl-php54 does not provide owncloud-server = 8.0.2 and owncloud-server-php54 cannot be installed with only the SCL php54 packages. 

#### Error :
Error: Package: owncloud-server-8.0.2-16.1.noarch (dev-owncloud-php54-x86_64-server-8) 
Requires: php >= 5.4.0 
Installed: php-5.3.3-40.el6_6.x86_64 (@fortifile-dev-x86_64-server-3) 
php = 5.3.3-40.el6_6 

But, when we run audit

sudo yum deplist owncloud-enterprise-app-admin_audit 
Loaded plugins: aliases, changelog, downloadonly, product-id, rhnplugin, security, subscription-manager, tmprepo, verify, versionlock 
This system is receiving updates from RHN Classic or RHN Satellite. 
Finding dependencies: 
package: owncloud-enterprise-app-admin_audit.noarch 8.0.2-28.1 
dependency: owncloud-server >= 8.0.2 
provider: owncloud-server.noarch 8.0.2-16.1 

Since RHEL 6 does not offer a php54 package, we use the SCL php packages. 

[root@dvnv-fortifile01-node1 ~]# rpm -qa |grep php54 
php54-php-xml-5.4.16-22.el6.x86_64 

Now since the own cloud rpms require php54, there is a package that should go to help utilize the scl packages, which is provided by the package below. 

[root@dvnv-fortifile01-node1 ~]# yum search owncloud |grep scl 
owncloud-server-scl-php54.noarch : Common code server for ownCloud 

This package is supposed to cover the server-common-core component for owncloud, so we can install it and then owncloud-enterprise. 

#yum install owncloud-server-scl-php54 
… 
Installed: 
owncloud-server-scl-php54.noarch 0:8.0.2-16.1 

#### Steps to reproduce:

1. Install RHEL 6.6 x64 
2. Enable the RHEL SCL Repo (https://access.redhat.com/documentation/en-US/Red_Hat_Software_Collections/1/html/1.0_Release_Notes/chap-RHSCL.html) 
3. Install php54 packages from RHEL SCL 
4. Install any other dependencies (mysql, etc) 
5. Install Owncloud Enterprise Edition Repo: ttps://download.owncloud.com/download/repositories/8.0/RHEL_6_PHP54/ee:8.0.repo<https://download.owncloud.com/download/repositories/8.0/RHEL_6_PHP54/ee:8.0.repo>
6. Yum install owncloud-enterprise 

This will result in the environment below. We are looking for instructions to use the ownCloud 8.0 rpm repo with the RHEL SCL PHP54 packages. Currently we are seeing dependency issues with the owncloud-sever-scl-php54 package. ownCloud 7.0.x works fine with the current configuration.

#### Side Note: 
•	The default php available to RHEL 6 is 5.3.3-40.el6_6 which satisfies the dependancy php >= 5.3.3 To ensure that php 5.4 is being used, 
•	these dependencies need to be specified as php54-php, or php55-php for php 5.5  If I try to upgrade using php53 and the http://XXXXrepos@XXXXX.ownCLOUD.com/download/repositories/7.0/RHEL_6_PHP53 repo

I get below error
![image](https://cloud.githubusercontent.com/assets/10195796/7543633/0efd9084-f594-11e4-8c48-7b8f17bebbfc.png)

**Comment by DeepDiver1975** [comment]
This upgrade on Oracle has to be custom scripted - please get in touch with GCX.

@butonic FYI - THX

**Comment by DeepDiver1975** [comment]
@jnweiger FYI regarding the packaging stuff

**Comment by DeepDiver1975** [comment]
@iliyasbasir please open one issue for each problem you are facing - THX a lot!

**Comment by LukasReschke** [comment]
@DeepDiver1975 What about https://github.com/owncloud/core/blob/f057efc42e62cc0efd511d84969ba1679104627c/lib/private/db/mssqlmigrator.php#L34 for OCI as well?

**Comment by DeepDiver1975** [comment]
hmmm ... kind of too late - with 8.1 we have no database changes \o/

**Comment by DeepDiver1975** [comment]
and fro 8.2 I'd really love to move away from the xml schema based kung-fu - #14851

**Comment by iliyasbasir** [comment]
@DeepDiver1975  I have listed issue which customer face during repo install , all step taken during the install are listed in this GitHub; two customer effected with similar symptoms.

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 I have listed issue which customer face during repo install , all step taken during the install are listed in this GitHub; two customer effected with similar symptoms.

well - still: each problem is required to be handled individually in isolated issue - thx

**Comment by jnweiger** [comment]
Regarding packaging: Fixed owncloud-enterprise to require either owncloud-server-scl-php54 or owncloud-server 

@iliyasbasir  The fix is visible on https://download.owncloud.com/download/ with owncloud-enterprise-8.0.3-5.1 or later rebuild number.

**Comment by iliyasbasir** [comment]
@jnweiger I can not reach  https://download.owncloud.com/download/  Can you gave me alternative or way reach this URL

**Comment by jnweiger** [comment]
@iliyasbasir sorry, the url was short. Just edited the comment above.

**Comment by iliyasbasir** [comment]
@jnweiger : let  me try this "https://download.owncloud.com/download/repositories/8.0/RHEL_6_PHP54/noarch/"

**Comment by MorrisJobke** [comment]
The DB issue is handled in #16454

**Comment by MorrisJobke** [comment]
The RHEL repo issue is handled in #16343

**Comment by MorrisJobke** [comment]
Close this ticket, because it was split into two.
