### ISSUE TITLE
Add to ownCloud gave "Invalid or untrusted SSL certificate". Error

### ISSUE THREAD

**Issue by iliyasbasir** [owncloud/core#16205]
[3061]
#### Expected behavior
File should be down loaded without error
#### Actual Behavior
When trying to use "add to your ownCloud" option for shared links the ownCloud displays "Invalid or untrusted SSL certificate". The certificate is both valid.
#### Step to reproduce
1)	Login to oC
2)	Select file click on “share “ from drop Manu place add user name and click “Share link”
3)	Copy shared link url
4)	Log out & login as user you shared link 
5)	On browse placed shared link URL
6)	Remote share pop-up window click on “ Add remote share”
7)	You see top of oC yellow banner error message “Invalid or untrusted SSL certificate”
#### Server configuration
Web (1 server): 
•	Operating system - Red Hat Enterprise Linux Server 7.1 (Maipo)
•	Web server - Apache 2.4.6 (Red Hat Enterprise Linux)
•	PHP version - 5.4.16
•	ownCloud version - 8.0.2
Backend (1 server):
•	Operating system - Red Hat Enterprise Linux Server 7.1 (Maipo)
•	Database - 5.5.41-MariaDB MariaDB Server (Red Hat Enterprise Linux)
•	Storage backend - 2TB xfs mount
Client:
•	Operating system - Windows 7 Enterprise 64 bit
•	OS language - English(US)
•	Installation path of client - c:\Program Files (x86)\ownCloud\
•	Client version - 1.8.0 (build 4893)
•	Client configuration - see link
•	Client log- see link
#### Screen Shot

![3](https://cloud.githubusercontent.com/assets/10195796/7543918/8d81b424-f596-11e4-8d80-a1d9479813f7.PNG)

![2](https://cloud.githubusercontent.com/assets/10195796/7543924/96b89c74-f596-11e4-8781-8d545f472a33.png)

**Comment by RealRancor** [comment]
Hi,

sure that both certificates are valid?

At least the "remote share owncloud" has an IP address which leads to the assumption that this is a self-signed certificate. AFAIK for this you also need to import the certificate as described here: https://doc.owncloud.org/server/8.0/admin_manual/configuration_files/external_storage_configuration_gui.html#using-self-signed-certificates

**Comment by DeepDiver1975** [comment]
> The certificate is both valid.

I doubt that - otherwise the notification would not pop up.

**Comment by DeepDiver1975** [comment]
@LukasReschke is there any easy way to verify a cert? Maybe we can add an openssl command to be executed on the server .... THX

**Comment by LukasReschke** [comment]
> @LukasReschke is there any easy way to verify a cert? Maybe we can add an openssl command to be executed on the server .... THX

If life would only be that easy… :see_no_evil: – OpenSSL and cURL when called from the CLI usually behave differently than when executed from PHP.

Probably again a totally misconfigured "Enterprise Linux" system, because running software from the Stone Age is *the* thing :see_no_evil: :hear_no_evil: :speak_no_evil:

8.1 will ship our own certificate bundle, so things should work mostly automatically there even if somebody completely misconfigured their system. Meanwhile I can only provide the php.ini setting [`curl.cainfo`](http://php.net/manual/en/curl.configuration.php) which should point to a valid root certificate chain:

1. Download https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt
2.  Add `curl.cainfo=/wherever/you/stored/that/ca-bundle.crt` to the *used* `php.ini` (in doubt take a looka t the output of `phpinfo()`)
3. Restart your webserver
4. Hope
5. Use https://www.ssllabs.com/ssltest/index.html to verify that all required intermediate certs are sent

**Comment by LukasReschke** [comment]
@iliyasbasir In case https://github.com/owncloud/core/issues/16205#issuecomment-100793417 did not help we need the complete phpinfo() output as well as a "Red Hat Enterprise Linux Server 7.1" setup in our lab or somewhere where we can access it via SSH and the steps they have done to install ownCloud / PHP. (and no CentOS please – I want absolute the same build and nothing that is somehow similiar ;-) )

**Comment by LukasReschke** [comment]
Also they have improperly configured their SSL setup. Please always run a SSLLabs test before filing an issue, thanks…

See https://www.ssllabs.com/ssltest/analyze.html?d=docs.elasalle.com&latest:

![2015-05-11_09-20-04](https://cloud.githubusercontent.com/assets/878997/7560007/eb496992-f7be-11e4-8371-9fbdb0bf8447.png)

**Comment by bboule** [comment]
@iliyasbasir  Please status this issue... there are some next steps here....

**Comment by iliyasbasir** [comment]
@bboule i did send this step to  customer waiting for responded

**Comment by MorrisJobke** [comment]
@iliyasbasir Any news on this or can this be closed?

**Comment by MorrisJobke** [comment]
@bboule Ping

**Comment by MorrisJobke** [comment]
@bboule @gig13 Please reopen if this still exists

**Comment by EmilObermayr** [comment]
This issue does still exist (v8.2.5). 
I have a server with completely valid certificates from GoDaddy and Owncloud complains. 
I can not see any problems with the certificates. Neither Firefox nor IE nor Chrome have any complaints.

**Comment by MorrisJobke** [comment]
> Use https://www.ssllabs.com/ssltest/index.html to verify that all required intermediate certs are sent

Try the above to verify that the SSL is properly set up.
