### ISSUE TITLE
Upgrade Owncloud 7 to 8 failed : ERROR

### ISSUE THREAD

**Issue by nath5394** [owncloud/core#16219]
Hello, First thanks for developing Owncloud.
I tried to upgrade my Owncloud from 7 to 8, but I got an error, see at the end.
I put maintenance mode on, then backup data directory and config.php file, then disabled default and 3rd party apps, then rename owncloud directory to owncloud.old then wget and expand owncloud 8 and put back data and config.php. Disabled maintenance mod, go to my owncloud, click upgrade and get this :  
Thank you for helping me ! 
PS : I have skills in following and understanding tutorials but not really in writing or developing in javascript/C/php/MySQL etc.
An exception occurred while executing 'CREATE TABLE oc_filecache (fileid INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, storage INTEGER DEFAULT 0 NOT NULL, path_hash VARCHAR(32) DEFAULT '' NOT NULL COLLATE BINARY, parent INTEGER DEFAULT 0 NOT NULL, name VARCHAR(250) DEFAULT NULL COLLATE BINARY, mimetype INTEGER DEFAULT 0 NOT NULL, mimepart INTEGER DEFAULT 0 NOT NULL, mtime INTEGER DEFAULT 0 NOT NULL, storage_mtime INTEGER DEFAULT 0 NOT NULL, encrypted INTEGER DEFAULT 0 NOT NULL, etag VARCHAR(40) DEFAULT NULL COLLATE BINARY, path VARCHAR(4000) DEFAULT NULL COLLATE BINARY, permissions INTEGER DEFAULT 0, "size" BIGINT DEFAULT 0 NOT NULL, "unencrypted_size" BIGINT DEFAULT 0 NOT NULL)': SQLSTATE[HY000]: General error: 10 disk I/O error

**Comment by RealRancor** [comment]
Hi,

a:

> General error: 10 disk I/O error

mostly means there is no more space left on your device or there are any other problems within the filesystem of your server.

**Comment by nath5394** [comment]
Hi, thanks for reply, I have 11GB free space (Total 25GB), so the problem seems not to be here. Can you tell me more about problem with the filesystem ?

**Comment by RealRancor** [comment]
Hi,

unfortunately no but you might want to get some background infos what could cause the "General error: 10 disk I/O error" error when putting it into your favorite search engine.

**Comment by nath5394** [comment]
Okay thanks

**Comment by RealRancor** [comment]
Ah, when using SQLite it could be also possible that the permissions of your data/owncloud.db is wrong and the PHP process can't write into this database.

**Comment by nickvergessen** [comment]
For support please use the support forum:
https://forum.owncloud.org/ or try google on such general issues which are not directly related to owncloud

**Comment by nath5394** [comment]
So I will check the permissions for the SQLite db, and maybe try to use my MySQL server instead. @AMDG2 Can you help ?
