### ISSUE TITLE
Unable to use Thunderbird, SSH, cPanel while sync

### ISSUE THREAD

**Issue by francesco1119** [owncloud/core#16210]
I'm unable to use 
- Thunderbird
- SSH connection through terminal 
- the cPanel of the host I'm storing my files with OwnCloud
- ping 8.8.8.8 or whatever (but I'm connected because I can reach any page with my browser) 

I was thinking that the problem was on my client side but I now can reproduce the same issues both on Debian Wheezy and Windows 7. So the problem must be on the core

All problems end when I pause or logout from OwnCloud

**Comment by karlitschek** [comment]
owncloud doesn't influence or interact with this ither systems at all. so there us no way this can be an owncloud bug. the only thing i can think about are used ressources. i recommend to check that. nothing we can do here.
