### ISSUE TITLE
suddenly files have only 0 kB -> data loss!

### ISSUE THREAD

**Issue by janklostermann** [owncloud/core#16215]
What happened:
I have edited a (text *.md) file on my Android phone, 
the content made it to the server (the last version on the server contains that change), 
and not much later my PC client (Win7) updates the file with 0 kB (according to the activity log) and
the file is empty. 
Looking on the Server it is 0kB and empty too... :-(
Having a closer look, I realize that this happened to some more files. 
Does anybody have an idea, what is going on here (OC 7.0.5)

Data loss is the worst that can happen, as you loose trust in the system... Please fix this soon.

**Comment by hoho508** [comment]
same issue happen to me ... well lets face it

**Comment by karlitschek** [comment]
Can you both please post full bug reports using the issue template? Maybe there are similarities in the setup.

**Comment by janklostermann** [comment]
Where can I find this "issue template"? 
Is there a possibility to find out, from where the change came (Server UI, Andoid Client, PC Client, (external shared-link user - not in this case))? The change is registered in the Acitvities...

**Comment by RealRancor** [comment]
@janklostermann 
When creating a new issue a box is show containing this text "Please review the guidelines for contributing to this repository". At the link you will find the issue template.

**Comment by janklostermann** [comment]
The problem seems to me as a sync problem in the interplay between the server, the Win-Client and the Android-Client. 
##### Win-Client-Info 
(unfortunately hard to find and then not even copyable):
`Version 1.8.0 (build 4893)`
`Built from Git revision 38ef52 on Mar 26 2015, 09:31:11 using Qt 5.4.0, OpenSSL 1.0.1| 15 Jan 2015`
##### Android-Client:
`Version 1.7.1 auf Samsung S3`

I hope this helps anyway:
### Steps to reproduce
1. I don't know! 
2.
3.

### Expected behaviour
A file should not loose its content (exept I explicitly empty it)

### Actual behaviour
2 files had suddenly 0 byte content. 

### Server configuration
Gomez knows more: it is a Portknox single admin installation

**Web server:**
ask Gomez
**Database:**
ask Gomez
**PHP version:**
ask Gomez
**ownCloud version:** (see ownCloud admin page)
OC 7.0.5
**Updated from an older ownCloud or fresh install:**
ask Gomez
**List of activated apps:**
ask Gomez
**The content of config/config.php:**
ask Gomez
```
Insert your config.php content here
(Without the database password, passwordsalt and secret)
ask Gomez
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
ask Gomez
**Are you using encryption:** yes/no
ask Gomez
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
ask Gomez
#### LDAP configuration (delete this part if not used)
ask Gomez
```
run: sqlite3 data/owncloud.db
then execute:  select * from oc_appconfig where appid='user_ldap';
ask Gomez
Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
ask Gomez
### Client configuration
**Browser:**
Firefox 37.0.2
**Operating system:**
Win7
### Logs
#### Web server error log
```
Insert your webserver log here
```
ask Gomez
#### ownCloud log (data/owncloud.log)
```
ask Gomez
Insert your ownCloud log here
```
ask Gomez
#### Browser log
```
???
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by Gomez** [comment]
@janklostermann Can you give me date/time of the delete? I try to get logs for it and complete the missing infos.

**Comment by janklostermann** [comment]
@gomez: I sent you a private mail with the details... (as far as I could
identify them)

Am 14.05.2015 um 20:20 schrieb Steffen Lindner:
>
> @janklostermann <https://github.com/janklostermann> Can you give me
> date/time of the delete? I try to get logs for it and complete the
> missing infos.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/core/issues/16215#issuecomment-102126058>.
>

-- 
Jan Klostermann
Systems Engineer & Mediator
Am Isarkanal 24/15
81379 München

Tel.: +49-89/74563382
Mobil: +49-179/4628819
Sip: +49-89/21551663 <sip:08921551663@sipgate.de>
Skype: jan.klostermann <callto://jan.klostermann/>
Threema: P58VSJUY <threema://add?id=P58VSJUY>
Email: jk@janklostermann.de <mailto:jk@janklostermann.de>
Netzwerke: Xing <https://www.xing.com/profile/Jan_Klostermann>, LinkedIn
<http://de.linkedin.com/in/janklostermann>

**Comment by PVince81** [comment]
@Gomez did you find any clues ?

**Comment by PVince81** [comment]
Any update ?

**Comment by Gomez** [comment]
Does not happend again with most current version. Will close and reopen if it happens again.
