### ISSUE TITLE
Upgrade 8.0.2 -> 8.0.3 fails -- General error: 1665

### ISSUE THREAD

**Issue by SuziQ407** [owncloud/core#16214]
Hello,

we have installed ownCloud 8.0.2 on Ubuntu 12.04.5 LTS server,
Webserver: Apache 2.4.12 with PHP 5.5.24-1,
Database: MySQL 5.5.43

After upgrading oC over server command "aptitude safe-upgrade" the oC upgrade page appears normally. We have saved our data, configs and databases. After clicking "Start Upgrade" (translation from German version) the following error happens:

*An exception occurred while executing ' DELETE FROM `oc_lucene_status` WHERE `fileid` IN ( SELECT `fileid` FROM ( SELECT `fileid` FROM `oc_lucene_status` GROUP BY `fileid` HAVING count(`fileid`) > 1 ) AS `mysqlerr1093hack` )': SQLSTATE[HY000]: General error: 1665 Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at least one table uses a storage engine limited to row-based logging. InnoDB is limited to row-logging when transaction isolation level is READ COMMITTED or READ UNCOMMITTED.*

Is there a solution for this issue?
Many thanks in advance.

**Comment by RealRancor** [comment]
Duplicate of: https://github.com/owncloud/core/issues/16066 , https://github.com/owncloud/core/issues/16063, https://github.com/owncloud/core/issues/16008, https://github.com/owncloud/core/issues/16089, https://github.com/owncloud/core/issues/16097

**Comment by SuziQ407** [comment]
Sorry, I haven't found :-((
Thanks a lot.

**Comment by SuziQ407** [comment]
Issue #16008 solves the problem:
mysql> SET GLOBAL binlog_format = 'MIXED';
