### ISSUE TITLE
File is always encrypted in the backend even though it wasn't encrypted in the first place

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#16222]
### Steps to reproduce
1. Upload a file directly in the storage backend (file isn't encrypted)
2. Check that the file is downloadable from ownCloud without any trouble
3. Edit and upload another version of the file from ownCloud
4. Go to the storage backend

### Expected behaviour
The file remains decrypted, or there is an option to explicitly encrypt the file in the backend

### Actual behaviour
The file is always encrypted in the backend

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 beta 1

**Updated from an older ownCloud or fresh install:** fresh install

### Notes
A possible use case:

An external user uploads a file directly to the backend with the intention of sharing the file with the ownCloud user whose ownCloud is linked with this external storage. This external user isn't ownCloud related.

The file is visible for the ownCloud user in his account, and can be edited. If the user uploads another version through ownCloud, the file will be encrypted in the backend, and that external user won't be able to access "safely" to the file.

This can be mitigated using two different ownCloud storages over the same external storage, one encrypted and the other one non-encrypted.

**Comment by schiesbn** [comment]
By default files are encrypted. If you don't want to encrypt the external storage you can configure it in the admin/personal settings at the same place where you set-up the external storage (click on the "gear"-icon to get the settings for the external storage)
