### ISSUE TITLE
User saving a shared file as recipient which was deleted by owner in an encrypted server gets frozen without warning

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16227]
### Steps to reproduce

1. Enable encryption app.
2. Enable encryption module in admin page.
3. Relogin.
4. Create a user1 and user2.
5. Upload a file with user1. 
6. Share a file with user2.
7. Edit the file with user2.
8. user1 Deletes the file. 
9. user2 saves the edition.

### Expected behaviour
user2 gets a warning saying that file has changed and can't edit it.
(Which is the behaviour without encryption)

### Actual behaviour
Web ui keeps trying to save the file.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition.
Encryption.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
Yes

**Logs**
```
```
### Client configuration

**browser**
Firefox

**Comment by schiesbn** [comment]
Just tried it with current master and couldn't reproduce it. I used a text file and opened it for editing as recipient, deleted the original file by the owner. Once the recipient click on "save" het gets this message "Cannot save file as it has been modified since opening" (same as for unencrypted files)

**Comment by jnfrmarks** [comment]
@SergioBertolinSG  Please rerun

**Comment by SergioBertolinSG** [comment]
Retested using master, not happening there.
