### ISSUE TITLE
Files_texteditor gets frozen when a user tries to open a shared file as recipient which was deleted

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16225]
### Steps to reproduce

1. Create two users user1 and user2.
2. user1 shares a folder with files with user2.
3. Both users are logged in.
4. user1 deletes a file from the shared folder.
5. user2 opens the deleted file.

### Expected behaviour
Some message telling file was deleted.

### Actual behaviour
UI gets frozen.

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.4","versionstring":"8.1 alpha 3","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in community version.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** 
no

### Client configuration

**browser**
Chrome 41

**Operating system**
Mac OS X

**Comment by nickvergessen** [comment]
I get the normal exception page:
```
File not found

The specified document has not been found on the server.

You can click here to return to ownCloud.

**Comment by nickvergessen** [comment]
please run `./occ app:list --output=json_pretty` and provide us with the app list

**Comment by SergioBertolinSG** [comment]
@nickvergessen 
```
{
    "enabled": {
        "activity": "1.2.3",
        "admin_audit": "0.6",
        "encryption": "1.0.0",
        "enterprise_key": "0.1.0",
        "files": "1.1.9",
        "files_locking": "",
        "files_pdfviewer": "0.7",
        "files_sharing": "0.6.1",
        "files_sharing_log": "0.5",
        "files_texteditor": "0.4",
        "files_trashbin": "0.6.2",
        "files_versions": "1.0.5",
        "files_videoviewer": "0.1.3",
        "firewall": "0.91.2",
        "firstrunwizard": "1.1",
        "gallery": "0.6.0",
        "provisioning_api": "0.2",
        "templateeditor": "0.1",
        "updater": "0.4",
        "windows_network_drive": "0.1.1"
    },
    "disabled": {
        "external": null,
        "files_antivirus": null,
        "files_drop": null,
        "files_external": null,
        "files_ldap_home": null,
        "objectstore": null,
        "sharepoint": null,
        "user_external": null,
        "user_ldap": null,
        "user_shibboleth": null,
        "user_webdavauth": null
    }
}
```

**Comment by nickvergessen** [comment]
I think this might be a problem of an editor/viewer app, which file type did you try? and can you try it with disabled texteditor and on a txt file please

**Comment by SergioBertolinSG** [comment]
Yes, download the file works correctly. It gets freeze when using the editor. I was using textfiles.

**Comment by nickvergessen** [comment]
Please report in the respective repository then
