### ISSUE TITLE
prevent users to delete a shared folder

### ISSUE THREAD

**Issue by HLeemans** [owncloud/core#16223]
Environment is:
- desktop client version 1.8.1. Build 5050 (Windows & web GUI)
- owncloud server 8.0.2. stable (Debian 7 based cloudserver)

expected behaviour:
--------------------------
- admin setup users
- admin setup folders and share these with users, controlling securitylevel with settings
- folder is created on desktop after sharing it by the admin
- if security setting is set that users are NOT able to delete, files can not be deleted
- it security setting is set that users are NOT able to delete, the shared folder can NOT be deleted

Real behaviour:
--------------------
- independant on security setting the user can always delete the shared folder
- the OwnCloud server does not loose any data, but
- the share is terminated/lost and has to be set again if users needs access to the folder

This is confusing in an inhouse OwnCloud installation. The admin should be able to determine if the user is able to delete the share or not. It may otherwise generate a lot of extra work for the superadmin user.

Requirement: Add security setting to select if a user is allowed to delete shared folders

**Comment by tflidd** [comment]
This feature has been asked constantly on the user forum:
https://forum.owncloud.org/viewtopic.php?f=29&t=24669
https://forum.owncloud.org/viewtopic.php?f=3&t=7438
https://forum.owncloud.org/viewtopic.php?f=29&t=23134
https://forum.owncloud.org/viewtopic.php?t=24669&p=73189
https://forum.owncloud.org/viewtopic.php?t=7438&p=16924
https://forum.owncloud.org/viewtopic.php?f=31&t=28192

**Comment by RealRancor** [comment]
Seems there was also an feature requested here: https://github.com/owncloud/core/issues/14075 but the user didn't managed to create a new issue yet as requested in this closed issue.

**Comment by tomstephens89** [comment]
+1 on this. There is no way to prevent clients deleting a shared folder, or renaming for that matter. This feature is a MUST!

**Comment by schiesbn** [comment]
Will be addressed with the pending shares sidebar. Please continue the discussion here: https://github.com/owncloud/core/issues/13495
