### ISSUE TITLE
Sharing problem and typecasting if i share a link for public e.g. calendar

### ISSUE THREAD

**Issue by libasys** [owncloud/core#16224]
A long existing problem with the sharing api!
That line in core/share.js
https://github.com/owncloud/core/blob/master/core/js/share.js#L472
lead as to following problem:
If i share a calendar by link with public we running in following issue:
The database column item_source of the share table is as varchar defined, but i share a calendar via id so i have an integer! And the marked line (472) looks also for type safety:
```
if (itemSource === share.file_source || itemSource === share.item_source) {
```
And the itemSource Variable (on js side) we get per $('item').data() transform the result automatically to type "number"! So the if clausel not works for sharing a link for public on any other apps who works with the share api!

Two possible Solution: we have to change the item_source column in the share table to an integer value or we have to do a typecasting in the lib/private/share/share.php transformDBResults() and cast that value to integer!
Thanks

**Comment by PVince81** [comment]
Code is obsoleted by the move to OCS calls in 9.0
