### ISSUE TITLE
occ option to update all third party apps without disable

### ISSUE THREAD

**Issue by Gomez** [owncloud/core#16221]
Right now an upgrade disables all third party apps (but not gallery / activity, for some reason?).
Suggestion: If I know what I am doing and replace all third party apps (before the update) with working/tested versions, an option to "force" the update would be helpful. As a result core and all available apps (also the deactivated?) get the update. The user will never see the update screen. 

Can this be achieved? 

Similar discussion: https://github.com/owncloud/core/issues/14754

**Comment by RealRancor** [comment]
Hi,

> (but not gallery / activity, for some reason?)

both are still core apps: https://github.com/owncloud/core/wiki/Apps-in-the-release

**Comment by DeepDiver1975** [comment]
we have to improve upgrade UX for 8.1 @karlitschek @MTRichards do you agree?

**Comment by karlitschek** [comment]
We had the behavior in the past where 3rd party apps where not disabled. We then had a ton of users reporting broken owncloud during upgrade triggered by broken 3rd party apps. So we decided to be save and disable 3rd party apps. They can be enabled very easily of course.
So before we find a magical solution where broken 3rdparty code can´t kill the full ownCloud I suggest to keep on all the apps that are not in the release aka. fully properly tested

**Comment by DeepDiver1975** [comment]
There is at least one issue we have to solve:
on disable the selected groups get lost

**Comment by Gomez** [comment]
Just a switch like "./occ upgrade --force" to skip the disable of third party apps, is not a option?

**Comment by karlitschek** [comment]
@Gomez Well then one group of users who don´t use this switch still have disabled apps and the other group might have broken installations. So I´m not sure this improved the user experience :-)

From my perspective super stable upgrades that don't kill installations is the 100% focus at the moment. I personally consider the disabling of the 3rdparty apps a minor annoyance but not a disaster. But maybe this is only me.

**Comment by RealRancor** [comment]
How high are the chances that an app is breaking a minor version? IIRC there is already a request available at the tracker that the apps are only disabled on upgrade.

**Comment by Gomez** [comment]
@karlitschek And the group of users that "know what they doing" get installations without disabled apps on updates.  I think the magical solution where broken 3rdparty code cant harm the installation is far away. Form me the --force is a option results in a better user experience.  

@RealRancor Yes @PVince81 suggest it here https://github.com/owncloud/core/issues/14754

**Comment by karlitschek** [comment]
@Gomez I agree that it could be useful for the group of people who are sure that all their used apps are compatible. Not sure this group is bigger then you and maybe 2-3 people more :-)
But we could do a config switch for this. But no default please until someone finds the magic solution :-)

**Comment by Gomez** [comment]
Sure, not as default. Will try to make a PR.

**Comment by enoch85** [comment]
Maybe a different issue, but why limit this to a occ command? Would be nice to have a checkbox in the updater app that says something like "don't disable 3dparty apps on update". CCing @jancborchardt as it´s needs design.

**Comment by jancborchardt** [comment]
I wouldn’t say this should be in the UI necessarily. As @karlitschek said you can never really be sure that all your apps will be compatible. A config switch would be doable though.

**Comment by enoch85** [comment]
@jancborchardt But there is no risk for broken installations if we only allow the official apps provided by ownCloud, right? So in other words; "don't disable *official* 3dparty apps on update".

It's not a big deal to reactivate them, just annoying.

**Comment by jancborchardt** [comment]
@enoch85 there’s no such thing as »official apps provided by ownCloud«, except the shipped apps (files, sharing etc) and they do not get disabled. Everything like Contacts, Calendar, Mail etc is purely developed by the community.

**Comment by enoch85** [comment]
@jancborchardt Ok, now I understand the different levels.  If I remember it correctly there are different levels of 3dparty apps aswell. I mean, not all apps show up in the Apps-store in onwCloud, and those who does (Contacts, Calendar, Documents, Mail and so on) should be included in every update without disabling them - or at least an option like I wrote before. Do you agree?

**Comment by enoch85** [comment]
On the other hand @jancborchardt - this is what I mean by "Official"
![image](https://cloud.githubusercontent.com/assets/4511254/7602245/55e81c76-f922-11e4-8d72-2d2841771b6c.png)

"By and within the ownCloud community", that description fits Contacts, Calendar, and Mail for example. I mean, you and @DeepDiver1975 is the main devs of the mail app so that should count as Official.

**Comment by jancborchardt** [comment]
Right, true. Yes, probably we should always make sure that these apps which are labeled »Official« are always included in update tests and exempt from the default disabling.

**Comment by enoch85** [comment]
@jancborchardt Thanks! You just saved me alot of time. Handles a few servers that I keep updated, and have to go through this process *every* time. New issue, or keep it here?

**Comment by jancborchardt** [comment]
Let’s keep it here. Up to @karlitschek @DeepDiver1975 to decide now if we want to do it like that or not.

**Comment by karlitschek** [comment]
I think this is a good approach. Now we "only" need to implement it.
