### ISSUE TITLE
oc creates ghost-folders (with default content) named with a users GUID inside the data dir

### ISSUE THREAD

**Issue by finius** [owncloud/core#16226]
Every now and then ownCloud is creating (but seemingly random) a ghost-folder inside the data dir for certain already existing users. The folder is almost empty (except of the default content of a newly created user) but has never user uploaded content - so, it feels like a "dummy folder" for something...
The folder(s) are named as the users GUI like "CA63DE2E-0200-4808-A4D2-456C2BAD1267". 
Is this a common behaviour? What are these are folders for?
First we thought of a problem checking AD - but a spare DC is always available, so this is hardly reasonable. But we may suppose that these problems could have a relation to some other issues we are facing sometimes (see https://github.com/owncloud/core/issues/16028#issuecomment-100189267)

**Comment by LukasReschke** [comment]
Thanks a lot for reporting issues back to us!

We need some more information to properly support you with your issue!

Can I ask you to follow our guidelines for submitting bugs as described here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by finius** [comment]
@LukasReschke - not that simple as you can imagine, This is best I can provide you:


### Steps to reproduce
unfortunately this problem has no regular occurrence. It happens every now and then. Last time it happend 2 weeks ago.

### Expected behaviour
Only folders with the SAMAccountName (as defined in the LDAP config panel) should be existing in the data dir.

### Actual behaviour
oc is creating for single users, that already have an existing data dir, a new folder named with their GUI. So a folder (i.e. "C8E33C40-D55E-4E9F-A092-CB0B174E6F43" is created inside the data dir, with default example-content of a new user, but always without any user specific contents)

### Server configuration
**Operating system**: Ubuntu 14.04 LTS
**Web server:** Apache 2
**Database:** MySQL
**PHP version:** 5.5
**ownCloud version:** 8.0.2
**Updated from an older ownCloud or fresh install:** Fist install on 5.0.3, updated through 6 and 7 to 8.0.2

**List of activated apps:** Activity, Deleted files, First Run Wizard, LDAP user and group backend, Mail Template Editor, PDF Viewer, Share Files, Text Editor
Versions, Video Viewer

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => '5237fa326c94a',
  'passwordsalt' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'datadirectory' => '/cloudData',
  'dbtype' => 'mysql',
  'version' => '8.0.2.0',
  'dbname' => 'ownCloud',
  'dbhost' => '127.0.0.1',
  'filesystem_check_changes' => 2,
  'overwritehost' => 'cloud.xxxxxxxxx.net',
  'overwriteprotocol' => 'https',
  'overwritewebroot' => '/cloud-linux',
  'overwritecondaddr' => '^10\\.0\\.0\\.62$',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_Administrator',
  'dbpassword' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'theme' => '',
  'maintenance' => false,
  'mail_smtphost' => '10.0.0.12',
  'mail_smtpmode' => 'smtp',
  'mail_smtpport' => '2525',
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => 'cloud-linux',
    2 => 'cloud-linux.xxxxx.local',
    3 => '10.0.0.62',
    4 => 'cloud.xxxxxxxxx.net',
    5 => 'cloud.xxxxxxxxx.org',
  ),
  'mail_from_address' => 'systemadministrator',
  'mail_domain' => xxxxx.de',
  'loglevel' => 3,
  'secret' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
);

**Are you using external storage, if yes which one:** The data dir is on a Windows Share that is mounted into /cloudData

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** Windows Server 2012 R2 ActiveDirectory

#### LDAP configuration (delete this part if not used)
A primary and a backup LDAP Server (Windows AD Server) have been defined in ldap config. 
User is: CN=user_ldap,OU=Servicing,DC=xxxxx,DC=local
User filder is: (&(objectClass=user)(objectClass=person))
Login filter is: sAMAccountName=%uid
Turn off SSL certificate Validation = True
Case insensitive LDAP server (Windows)  = True
Disable Main Server = False
Cache Time-To-Live = 300
User Display Name Flied = displayname
User Home Folder Naming Rule = sAMAccountName
//no expert settings defined

### Client configuration
**Browser:** Firefox, Safari, IE 11

**Operating system:** Windows 7, Max OS 10.10, Ubuntu 14.04

### Logs
#### Web server error log
-

#### ownCloud log (data/owncloud.log)
no log is written neither at the time of the issue nor for the GUID concerned

#### Browser log
none

**Comment by LukasReschke** [comment]
cc @blizzz

**Comment by blizzz** [comment]
Known, fixed in master, but the backport to stable8 is not merged yet: https://github.com/owncloud/core/pull/15797 Please follow the progress there.

The original issue is https://github.com/owncloud/core/issues/13862
