### ISSUE TITLE
Invalid tzdata for Asia/Magadan

### ISSUE THREAD

**Issue by LebedinskySA** [owncloud/core#16238]
I create an event on the phone at 22:30
![screenshot_2015-05-11-22-17-08](https://cloud.githubusercontent.com/assets/12394295/7564618/75ee1a8e-f823-11e4-9901-4bfb07162ada.png)
But time moves on the calendar 2 hours
![screenshot1](https://cloud.githubusercontent.com/assets/12394295/7564894/16fe13e6-f826-11e4-9b48-cea48f5522cc.png)

**Comment by DeepDiver1975** [comment]
please reopen this issue in https://github.com/owncloud/calendar - THX
