### ISSUE TITLE
LDAP wizard configuration: The hostname is not shown in the combobox of servers tab.

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16231]
### Steps to reproduce
1. Go to LDAP wizard configuration.
2. Configure a right configuration
3. Go to users tab
### Expected behaviour

The direction should be visible after the ":"  in the servers tab combobox. e.g. 1. Server: 10.40.40.74
### Actual behaviour

The direction is not shown in the combobox with a right configuration.
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** "version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:** fresh install

![captura de pantalla 2015-05-11 a las 12 27 54](https://cloud.githubusercontent.com/assets/10596560/7562995/79e3acc0-f7d9-11e4-82e9-182fe9077cc9.png)

**Comment by DeepDiver1975** [comment]
@blizzz can you have a look please? THX

**Comment by blizzz** [comment]
Yes, it will be shown there only after reload. It has been always like this, i.e. not a regression or anything. Thus, it can be improved, though i do not see bigger severity here.

**Comment by PVince81** [comment]
@cmonteroluque Low severity, I suggest moving to 9.0 or backlog

**Comment by PVince81** [comment]
moved to grouped UX ticket: https://github.com/owncloud/user_ldap/issues/69
