### ISSUE TITLE
Corrupted shared file if the share recipent hasn't his encryption keys generated

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#16232]
### Steps to reproduce
1. Enable files_encryption and user_ldap apps
2. Setup a LDAP configuration in ownCloud with several users
3. Upload a file in userA account (checked with a local user but could be a LDAP user) having the encryption keys already generated
4. Share the file with a LDAP user (userB)
5. Enter the in userB account (for the first time) and download the file from there

### Expected behaviour
The file is downloaded correctly

### Actual behaviour
The file is downloaded corrupted. The userB MUST have entered his account and generated the encryption keys before the sharing take place.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 beta 1

**Updated from an older ownCloud or fresh install:** fresh install

**List of activated apps:**
- files_encryption
- files_external (probably not related)
- user_ldap (indirectly related, but probably reproducible without it)
- files_locking (probably not related)
- sharing

#### ownCloud log (data/owncloud.log)
```
{"reqId":"u8+s5hK+FeJILIGvToPu","remoteAddr":"10.40.10.254","app":"hook","message":"error while running hook (OC\\Encryption\\HookManager::postShared): Public Key missing for user: 3cf06726-8289-1034-8404-6b3cf12c4922","level":3,"time":"2015-05-11T09:21:56+00:00"}
{"reqId":"t0gf41zscnHrNJZjkbMT","remoteAddr":"10.40.10.254","app":"hook","message":"error while running hook (OC\\Encryption\\HookManager::postUnshared): Public Key missing for user: 3cf06726-8289-1034-8404-6b3cf12c4922","level":3,"time":"2015-05-11T09:23:24+00:00"}
{"reqId":"oaq0uaIfok+3Qzgy+8WF","remoteAddr":"10.40.10.254","app":"hook","message":"error while running hook (OC\\Encryption\\HookManager::postShared): Public Key missing for user: 3cf06726-8289-1034-8404-6b3cf12c4922","level":3,"time":"2015-05-11T09:23:55+00:00"}
{"reqId":"VjPgUIPBapjV7nTD54dE","remoteAddr":"10.40.30.21","app":"hook","message":"error while running hook (OCA\\Encryption\\Hooks\\UserHooks::login): Private Key missing for user: please try to log-out and log-in again","level":3,"time":"2015-05-11T09:24:58+00:00"}
```

### Notes
I think the main issue is that the sharing dialog shows all available users without filtering out the users who haven't login yet and don't have their keys generated (it shouldn't filter them out though). This implies that the "source" user can share his file with those users.

In addition, sharing with "already-logged-in" users might be affected by this issue because the hook might not be fully run and stop in the middle, so the sharing might not be take place for that user

**Comment by schiesbn** [comment]
Yes, one point is that we can block users from sharing if they don't have a valid key pair. But this will not work for group shares. Because there we don't want to block the whole group just because of one user. So we should fail with a proper error message which was the case in 8.0 and earlier... I will have a look.

**Comment by schiesbn** [comment]
Added a error page, similiar to what we had in oC <= 8.0, see https://github.com/owncloud/core/pull/16243

**Comment by rperezb** [comment]
ey @schiesbn is this the expected behavior for 8.2 too, just wondering for leaving the test plans with the right info.
thx
