### ISSUE TITLE
User can't update a single file shared from server1 to server2

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#16245]
Tested in current master:

- share a single text file from server1 to server2 (make sure that "can edit" is set)
- try to edit the file on server2 with the internal text editor
-> save will fail. The sabredav quotaplugin throws a \Sabre\DAV\Exception\InsufficientStorage, even if no quota is set.

cc @PVince81 

If I remember correctly we had a similar problem during the 8.0 development cycle. Vincent told me that this was fixed back than by @icewind1991 but it seems like the bug is back. @icewind1991 can you have a look at it? Thanks!

**Comment by icewind1991** [comment]
Regressions caused by f391f88d7f207dc15963eaf1bdee584bd36a573e, probably a case where null was used as root by error and it accidentally worked.
