### ISSUE TITLE
Restore from trash overwrites existing files/folders

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#16246]
### Steps to reproduce
1. Create a folder "folder"
1. Create a file "folder/test1.txt"
1. Delete folder "folder"
1. Create a folder "folder"
1. Create a file "folder/test2.txt"
1. Delete folder "folder"
1. Go to trashbin and see two "folder" entries
1. Restore both "folder" entries
1. Go back to files view

### Expected result
After restoring both folders, I should see "folder" and "folder (2)" (or "folder (restored)")

### Actual result
Only one "folder" is visible. Its contents is either "test1.txt" or "test2.txt" depending on the restore order.
Note that the other file is permanently lost.

### Versions
Observed on v8.0.3

@schiesbn @icewind1991 FYI

I'll try and look into this regression, possibly related to the trashbin wrapper.

**Comment by PVince81** [comment]
Works properly on stable7 (7.0.5)

Let's bisect this.

**Comment by PVince81** [comment]
Well well, it's probably not a surprise: 15ae6b47edf08a1fd60a0941c3786372afad5baa

The introduction of the trashbin storage wrapper broke file restoration.

Next step: fix it.

**Comment by PVince81** [comment]
PR here: https://github.com/owncloud/core/pull/16273

**Comment by MorrisJobke** [comment]
Master merged, stable8: #16374
