### ISSUE TITLE
Sidebar broken layout if "deleted files" is disabled

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#16244]
If "deleted files" is disabled "Shared by link" is no longer align to the other side bar entries, see attached screenshot:

![1](https://cloud.githubusercontent.com/assets/1589737/7568826/517fd21e-f805-11e4-840c-4d7e9ea9a657.png)

cc @jancborchardt

**Comment by jancborchardt** [comment]
Huh, I thought I reported that already.

As far as I remember, this is because »Deleted files« is not the last entry in the list. Can you make it so it is?

**Comment by jancborchardt** [comment]
@schiesbn has this been fixed as I commented above?

**Comment by jancborchardt** [comment]
@schiesbn hello?

**Comment by PVince81** [comment]
@jancborchardt there is no "Deleted files" entry when trashbin is disabled. The shift is due to this CSS rule https://github.com/owncloud/core/blob/v8.2RC1/apps/files/css/files.css#L96 that applies itself on the nth-child(2)

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/19624 which removes that block (works in Chrome and Firefox)

**Comment by nickvergessen** [comment]
@jancborchardt 
> As far as I remember, this is because »Deleted files« is not the last entry in the list. Can you make it so it is?

This issue appears when you disable "Deleted files", it should not appear, when the app is disabled....?

**Comment by PVince81** [comment]
Needs another approach that accomodates with the case described by @jancborchardt here https://github.com/owncloud/core/pull/19624#issuecomment-147268471

**Comment by PVince81** [comment]
New PR here https://github.com/owncloud/core/pull/19702

**Comment by PVince81** [comment]
Fixed through https://github.com/owncloud/core/pull/19702

**Comment by MorrisJobke** [comment]
stable8.2 #19779
