### ISSUE TITLE
NAS lokal einbinden

### ISSUE THREAD

**Issue by OwncloudProblem** [owncloud/core#16257]
Guten Tag OwnCloud Community,

Ich habe gestern versucht meine NAS "lokal" auf die OwnCloud einzubinden. Das Einbinden hat funktioniert, jedoch kann ich auf dem Webinterface keine Daten einsehen. Schaue ich dann unter dem Ordner nach, also unter Windows Explorer, da sind die Daten jedoch vorhanden. Ueber das Webinterface kann ich ebenfalls Daten erstellen, aber diese werden mir nicht angeziegt, befinden sich, wenn ich im Ordner unter Windows Explorer nachschaue jedoch dort. 
Wenn ich die NAS jedoch über FTP einbinde, funktioniert es einwandfrei.

Jedoch möchte ich die NAS "lokal" einbinden. 

Mit freundlichen Grüßen.

**Comment by karlitschek** [comment]
This is the issue tracker for ownCloud bugs. I recommend that you ask you question in the ownCloud forum at forum.owncloud.org
By the way. Please use english :-)
