### ISSUE TITLE
Upgrade with enabled files_encryption (8.0 -> 8.1) failed in the first run

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#16259]
### Steps
1. Setup stable8 f50fc14935369c37c08bff92008d66a0d1422fb7
2. Enable encryption (only files_texteditor was additionally enabled - beside the core apps)
3. Enable recovery key
4. Create user test
5. Login as test (to initialize keys) and upload some data to test encryption
6. Switch to master branch deeeca6
7. `./occ upgrade`

### Expected

```
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Turned off maintenance mode
Update successful
```

### Actual

```
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Disabled 3rd-party app: files_encryption
App does not provide an info.xml file
Turned off maintenance mode
Update failed
```

After a second run of `./occ upgrade` all went fine. But it's really scary to read a "upgrade failed" message.

### Info

* PHP-FPM with php 5.6.8
* Apache
* Log (sadly I don't know if this happens during the not working upgrade or during the working upgrade run):

```

{"reqId":"cb0e03095066d9d064d6cff6591c2f3c","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/lib\\\/private\\\/app.php(77): OC_App::loadApp('files_sharing')\\n#1 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/lib\\\/private\\\/util.php(75): OC_App::loadApps(Array)\\n#2 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/lib\\\/base.php(790): OC_Util::setupFS()\\n#3 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/index.php(36): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/lib\\\/private\\\/app.php\",\"Line\":96}","level":4,"time":"2015-05-11T14:25:35+00:00"}
```
cc @schiesbn @th3fallen

**Comment by schiesbn** [comment]
Are you sure that this error has anything to do with encryption? The encryption app has a info.xml https://github.com/owncloud/core/blob/master/apps/encryption/appinfo/info.xml

**Comment by schiesbn** [comment]
With this PR you should get a error page with the message from the exception: https://github.com/owncloud/core/pull/16243

**Comment by MorrisJobke** [comment]
> With this PR you should get a error page with the message from the exception: #16243

I'm on the console. I doubt that I get a redirect ;)

**Comment by schiesbn** [comment]
the comment should have added to this issue https://github.com/owncloud/core/issues/16260

Still, my first questions remains open.

**Comment by MorrisJobke** [comment]
Yes. Definetely related to encryption.

With encryption enabled (in stable8):

```
$ ./occ upgrade
ownCloud or one of the apps require upgrade - only a limited number of commands are available
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Disabled 3rd-party app: files_encryption
App does not provide an info.xml file
Turned off maintenance mode
Update failed
$ ./occ upgrade                                                                                                                                              130 ↵
ownCloud or one of the apps require upgrade - only a limited number of commands are available
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Turned off maintenance mode
Update successful
```

Without enabling encryption in stable8:

```
$ ./occ upgrade
ownCloud or one of the apps require upgrade - only a limited number of commands are available
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Turned off maintenance mode
Update successful
```

**Comment by MorrisJobke** [comment]
I think the problem with the "App does not provide an info.xml file" is that the files_encryption folder isn't present anymore and therefore it can't find any info.xml. I will try to fix this.

**Comment by MorrisJobke** [comment]
Looks like the updater tries to download the files_encryption app again from the appstore. (there is only a placeholder app in the appstore)

**Comment by MorrisJobke** [comment]
Together with #16290 I found out why the message is written and the upgrade fails:

```
$ ./occ upgrade                     
ownCloud or one of the apps require upgrade - only a limited number of commands are available
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Disabled 3rd-party app: files_encryption
Update 3rd-party app: files_encryption
App does not provide an info.xml file
Turned off maintenance mode
Update failed
```

It tries to re-enable the files_encryption app and because it isn't available anymore, it tries to download it from the appstore. There it founds a dummy apps and downloads it. This dummy app doesn't contain anything and crashes the upgrade for instances with enabled appstore and files_encryption enabled.

@karlitschek Can you please remove the files_encryption dummy from the appstore.


Some metadata about that app:

```
App does not provide an info.xml file
Array
(
    [source] => http
    [href] => https://apps.owncloud.com/CONTENT/content-files/166047-files_encryption.zip
    [appdata] => Array
        (
            [id] => 166047
            [name] => Files Encryption
            [version] => 0.0.1
            [type] => 925
            [label] => recommended
            [typename] => ownCloud other
            [personid] => owncloud
            [profilepage] => http://opendesktop.org/usermanager/search.php?username=owncloud
            [detailpage] => https://apps.owncloud.com/content/show.php?content=166047
            [preview1] => 
            [preview2] => 
            [preview3] => 
            [changed] => 1404743127
            [description] => Placeholder for future updates
            [score] => 50
        )

)
```

**Comment by karlitschek** [comment]
@MorrisJobke i deleted it. Thanks

**Comment by MorrisJobke** [comment]
@karlitschek Thanks. I just verified and it works now :+1:
