### ISSUE TITLE
Large Files E-Tag Issue

### ISSUE THREAD

**Issue by Boseley** [owncloud/core#16263]
### Steps to reproduce
1. Add a single file of size 6.7GB to owncloud desktop client folder.
2. Wait for upload to complete.
3. First error message appeared of "connection timeout" believe this may be related to the time it takes the server to put the files together, so increased ram and added another CPU (from 2GB ram to 4GB and 1 CPU to 2 CPU - purely for testing)
4. After memory and CPU increase re-tried sync and got the e-tag error instead. In both instances the file uploads to the server successfully, or at least it shows in the web browser anyway.
5. Activity log in client shows "The server did not acknowledge the last chunk. (No e-tag were present)".

### Expected behaviour
Large file should upload and client should receive acknowledgement from server. 

### Actual behaviour
First time around:
|0|ISOs/Windows 8 AIO.iso|INST_NEW|Up|1420449993||7220365312||1|Connection Timeout|0|0|0|||INST_NONE|

Second time around after memory and CPU increase:
|0|ISOs/Windows 8 AIO Test.iso|INST_NEW|Up|1420449993||7220365312||2|The server did not acknowledge the last chunk. (No e-tag were present)|0|0|0|||INST_NONE|
#=#=#=# Syncrun started 2015-05-12T05:53:40 until 2015-05-12T05:53:41 (952 msec)

### Server configuration
Fedora 20

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
5.5.24

**ownCloud version:** (see ownCloud admin page)
Server - 8.0.3
Windows Client - 1.8.1

**Updated from an older ownCloud or fresh install:**
Fresh install

**List of activated apps:**
None.

**The content of config/config.php:**
```php
<?php
$CONFIG = array (
  'instanceid' => 'ocnt14js99ax',
  'passwordsalt' => 'XXXXX',
  'secret' => 'XXXXX',
  'trusted_domains' =>
  array (
    0 => 'localhost', 'myowncloudaddress',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'overwrite.cli.url' => 'http://localhost/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.3.4',
  'dbname' => 'mydb',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'user',
  'dbpassword' => 'password',
  'installed' => true,
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** yes/no
No.

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No.

Thank you.

**Comment by LukasReschke** [comment]
@Boseley Your config contains sensitive data such as the secret – you just leaked it to the world – I removed it for now…

**Comment by Boseley** [comment]
@LukasReschke  Oops! I must be blind I actually looked for the salt and secret part but could not see it, thanks for removing, sorry it's early morning here and I've not had my coffee yet!

**Comment by PVince81** [comment]
Hmmm, it should not take more RAM to assemble the chunk files. ownCloud doesn't read in the whole file when assembling them.

Do you see any stray chunks for that file in "data/$user/cache" ?

Not sure why it would show that error if the file is uploaded properly. Maybe a timeout occurred exactly at the end of the transfer, between the end of assembling and the time it would return the etag.
But it is unlikely that this happens consistently. Does it ?

**Comment by Boseley** [comment]
HI @PVince81 I did check the cache folder and it currently has 999 chunk files in for that file like below:

-chunking-1559908574-284      Windows 8 AIO Test.iso-chunking-1559908574-998
Windows 8 AIO Test.iso-chunking-1559908574-285      Windows 8 AIO Test.iso-chunking-1559908574-999

I've actually deleted the file from my local owncloud folder now but the chunks remain, I had to delete is as another issue I've just encountered is that my machine has 200GB HDD and yet Owncloud client is showing only a total of 27GB server space instead of 200GB in the client. Unsure why this is either, the user is set to unlimited space and is the admin account and only account that exists. 

I thought it may be this discussed issue but I am not sure:
https://github.com/owncloud/core/issues/12097

**Comment by DeepDiver1975** [comment]
This is the in-famous timeout on chunk assembly issue.
