### ISSUE TITLE
Download of file after encryption migration throws HTTP 500

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#16260]
### Steps

* Doing the steps from #15979 ~~on master deeeca6~~ (I did these steps #16259 - on the written commits)
* Switch after the last step to 9dd517071e60ff3677ea79e84577f3556ac7d4cc (#15979)
* Try to download a file via web UI

### Expected

* getting the file

### Actual

Error 500 with following HTML body:

* Typ: OCA\Encryption\Exceptions\MultiKeyDecryptException
* Code: 0
* Nachricht: multikeydecrypt with share key failed:error:04065072:rsa routines:RSA_EAY_PRIVATE_DECRYPT:padding check failed
* Datei: /home/mjob/Projekte/owncloud/master/apps/encryption/lib/crypto/crypt.php
* Zeile: 439

	
```
#0 /home/mjob/Projekte/owncloud/master/apps/encryption/lib/keymanager.php(364): OCA\Encryption\Crypto\Crypt-&gt;multiKeyDecrypt(&#039;\xC5\xE7\xD7\xD0A\x8Cd\xC8F\xCE\x86\xF2\x83\xEB\xEA...&#039;, &#039;$\x08\xC9\xA3\xC9\r\x8E\xCB%sn\xD0Z\x83\xE0...&#039;, &#039;-----BEGIN PRIV...&#039;)
#1 /home/mjob/Projekte/owncloud/master/apps/encryption/lib/crypto/encryption.php(131): OCA\Encryption\KeyManager-&gt;getFileKey(&#039;/test/files/wel...&#039;, &#039;test&#039;)
#2 /home/mjob/Projekte/owncloud/master/lib/private/files/stream/encryption.php(245): OCA\Encryption\Crypto\Encryption-&gt;begin(&#039;/test/files/wel...&#039;, &#039;test&#039;, &#039;r&#039;, Array, Array)
#3 [internal function]: OC\Files\Stream\Encryption-&gt;stream_open(&#039;ocencryption://&#039;, &#039;r&#039;, 0, NULL)
#4 /home/mjob/Projekte/owncloud/master/lib/private/files/stream/encryption.php(185): fopen(&#039;ocencryption://&#039;, &#039;r&#039;, false, Resource id #23)
#5 /home/mjob/Projekte/owncloud/master/lib/private/files/stream/encryption.php(167): OC\Files\Stream\Encryption::wrapSource(Resource id #22, &#039;r&#039;, Resource id #23, &#039;ocencryption&#039;, &#039;OC\\Files\\Stream...&#039;)
#6 /home/mjob/Projekte/owncloud/master/lib/private/files/storage/wrapper/encryption.php(362): OC\Files\Stream\Encryption::wrap(Resource id #22, &#039;files/welcome.t...&#039;, &#039;/test/files/wel...&#039;, Array, &#039;test&#039;, Object(OCA\Encryption\Crypto\Encryption), Object(OC\Files\Storage\Home), Object(OC\Files\Storage\Wrapper\Encryption), Object(OC\Encryption\Util), Object(OC\Encryption\File), &#039;r&#039;, 8436, 163, 8192)
#7 /home/mjob/Projekte/owncloud/master/lib/private/files/storage/wrapper/encryption.php(169): OC\Files\Storage\Wrapper\Encryption-&gt;fopen(&#039;files/welcome.t...&#039;, &#039;r&#039;)
#8 /home/mjob/Projekte/owncloud/master/lib/private/files/storage/wrapper/wrapper.php(230): OC\Files\Storage\Wrapper\Encryption-&gt;file_get_contents(&#039;files/welcome.t...&#039;)
#9 /home/mjob/Projekte/owncloud/master/lib/private/files/view.php(938): OC\Files\Storage\Wrapper\Wrapper-&gt;file_get_contents(&#039;files/welcome.t...&#039;)
#10 /home/mjob/Projekte/owncloud/master/lib/private/files/view.php(471): OC\Files\View-&gt;basicOperation(&#039;file_get_conten...&#039;, &#039;//welcome.txt&#039;, Array)
#11 /home/mjob/Projekte/owncloud/master/lib/private/files/filesystem.php(669): OC\Files\View-&gt;file_get_contents(&#039;//welcome.txt&#039;)
#12 /home/mjob/Projekte/owncloud/master/apps2/files_texteditor/ajax/loadfile.php(39): OC\Files\Filesystem::file_get_contents(&#039;//welcome.txt&#039;)
#13 /home/mjob/Projekte/owncloud/master/lib/private/route/route.php(153) : runtime-created function(1): require_once(&#039;/home/mjob/Proj...&#039;)
#14 [internal function]: __lambda_func(Array)
#15 /home/mjob/Projekte/owncloud/master/lib/private/route/router.php(272): call_user_func(&#039;\x00lambda_1589&#039;, Array)
#16 /home/mjob/Projekte/owncloud/master/lib/base.php(860): OC\Route\Router-&gt;match(&#039;/apps/files_tex...&#039;)
#17 /home/mjob/Projekte/owncloud/master/index.php(40): OC::handleRequest()
#18 {main}
```

Nothing in the logs

* PHP-FPM with php 5.6.8
* Apache

cc @schiesbn @th3fallen

**Comment by MorrisJobke** [comment]
Seems to be unrelated to the PR I checked out. It is rather due to the migration from 8.0 to 8.1. (to be more precise: I did exactly the stuff from #16259)

**Comment by schiesbn** [comment]
You probably forget to enable the new encryption, the "default encryption module" and run "occ encryption:migrate"

**Comment by MorrisJobke** [comment]
o.O Hu?!? I didn't login. I simply switched to the new code and then got a warning. I don't want to see a warning there. It could maybe say: "Hey, you need to migrate your keys too, but that is fine - simply run occ enc:migrate". But I don't want to see: "Failed"

**Comment by schiesbn** [comment]
According to your steps you did a login, or how did you perform this step: ;-)

> Try to download a file via web UI

(BTW: With this PR you should get a error page with the message from the exception: #16243)

Generally speaking this should be part of the release notes. We don't upgrade the existing encryption app and just raise the version number but we replace it with something completely new. So the admin needs to take the extra steps to enable the new app and run the migration. As soon as the new app is enabled we will also tell him that he needs to run "occ encryption:migrate".

see also this discussion: https://github.com/owncloud/core/issues/16177
