### ISSUE TITLE
Upgrade from 7.0.4.2 to 8.0.3.4

### ISSUE THREAD

**Issue by alve89** [owncloud/core#16261]
After upgrading and running the database update, I got the following error message:

`Fatal error: Class OCA\Contacts\Share\Addressbook contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCP\Share_Backend::isShareTypeAllowed) in /www/htdocs/w00f5329/die-herzogs_com/cloud/owncloud-UPDATE/apps/contacts/lib/share/addressbook.php on line 130`

Can I just delcare it as abstract or are there functions need to be implemented?

**Comment by RealRancor** [comment]
Hi,

it seems you're still using the old contacts app from OC7 which are not compatible to OC8: https://github.com/owncloud/contacts/issues/804 , https://github.com/owncloud/contacts/issues/788 , https://github.com/owncloud/contacts/issues/745

Normally OC 8.0.3 should have disabled this old app.

**Comment by alve89** [comment]
But obviously it doesn't? I disabled it manually via database. Now the following problem appears:

`
Fatal error: Uncaught exception 'Exception' with message 'js file not found: script:js/chosen/chosen.jquery.min serverroot:/www/htdocs/w00f5329/die-herzogs_com/cloud/owncloud-UPDATE' in /www/htdocs/w00f5329/die-herzogs_com/cloud/owncloud-UPDATE/lib/private/template/resourcelocator.php:46 Stack trace: #0 /www/htdocs/w00f5329/die-herzogs_com/cloud/owncloud-UPDATE/lib/private/templatelayout.php(156): OC\Template\ResourceLocator->find(Array) #1 /www/htdocs/w00f5329/die-herzogs_com/cloud/owncloud-UPDATE/lib/private/templatelayout.php(107): OC_TemplateLayout::findJavascriptFiles(Array) #2 /www/htdocs/w00f5329/die-herzogs_com/cloud/owncloud-UPDATE/lib/private/template.php(118): OC_TemplateLayout->__construct('error', '') #3 /www/htdocs/w00f5329/die-herzogs_com/cloud/owncloud-UPDATE/lib/private/template/base.php(103): OC_Template->fetchPage() #4 /www/htdocs/w00f5329/die-herzogs_com/cloud/owncloud-UPDATE/lib/private/template.php(227): OC\Template\Base->printPage() #5 [internal function]: OC_Template::printExceptionErrorPage(Object in /www/htdocs/w00f5329/die-herzogs_com/cloud/owncloud-UPDATE/lib/private/template/resourcelocator.php on line 46`

**Comment by RealRancor** [comment]
Hi,

there are still some non-compatible apps enabled like calendar which is causing those errors: https://github.com/owncloud/core/issues/13999

**Comment by alve89** [comment]
I just read that these apps are not shipped with the upgrade. I think that should be better communicated to the users in future releases. But thank you anyway for the information.
