### ISSUE TITLE
[ldap] group filter buttons work if in "edit LDAP query" mode

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#16279]
1.- Go to the admin view, LDAP wizard, section Groups
2.- Click on "Edit LDAP Query"
3.- Clicking on `<` and `>` still works and adds the group `[object Window]`
### Expected

Buttons should not work 

cc @blizzz

**Comment by blizzz** [comment]
Right, but the entries need to be marked, since the lists itself are disabled. Buttons needs to be too, of course.

**Comment by PVince81** [comment]
moved to grouped UX ticket: https://github.com/owncloud/user_ldap/issues/69
