### ISSUE TITLE
Problems with Chunked upload

### ISSUE THREAD

**Issue by obstschale** [owncloud/core#16278]
I don't know if that is the right place to ask, so if I'm wrong please tell me where I can ask my question :)

I currently try to build a WebDAV / ownlcoud client to upload some files. Because some files are large I figured that I need to use so called "chunking". However I could not find a real good tutorial / instruction how to implement such chunking. I found this page: [spec: big-file-chunking](https://github.com/owncloud/core/wiki/spec:-big-file-chunking) but it does not really help.

So let me explain what I did so far and what questions I have:

I check for the filesize and if it is large than same predefined value I will chunk the data. I use PUT to upload each chunk and the chunks have the following name: `<path/filename>-chunking-<transferid>-<chunkcount>-<index>` like mentioned in the specs linked above.

I also set the following header types:
```
HTTP/1.1 206 Partial Content
Content-type: application/octet-stream
OC-Chunked: 1
Content-Range: bytes 0-499/1023
Transfer-Encoding: chunked
```

Each request is creates an empty file named like the chunk on my owncloud and each response of these PUTs request return 201 oder 204.

I also see that each response has their own ETag, but I read that this is not normal but I couldn't find out why this is.

Do you have any idea what I am doing wrong? 

PS: I am running the latest owncloud version.

**Comment by karlitschek** [comment]
Hi. I suggest to ask this question on the owncloud devel mailinglist. https://mailman.owncloud.org/mailman/listinfo/devel
