### ISSUE TITLE
Encryption app missing in deb package.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16275]
### Steps to reproduce
1. Install owncloud from internal repository.

### Observed behaviour
Encryption app is not included.

### Expected behaviour
New encryption app with default encryption module should be included.

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**Package version**
8.1.0~Beta1-1

**Comment by RealRancor** [comment]
Hi,

don't know this "internal repository" but at least on OBS the encryption app is a seperate package called "owncloud-app-files-encryption":

http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/xUbuntu_14.04/all/

**Comment by SergioBertolinSG** [comment]
Owncloud 8.0.3 has it included (the old encryption):  owncloud-app-files-encryption 8.0.3-2 [114 kB]

**Comment by schiesbn** [comment]
"files_encryption" is the old encryption. From 8.1 on the app is called just "encryption". It should be in the package, as it is also in the core repository. cc @jnweiger

**Comment by jnweiger** [comment]
https://build.opensuse.org/package/binaries/isv:ownCloud:community:testing/owncloud?repository=xUbuntu_14.04

as far as I can see it is there.

**Comment by RealRancor** [comment]
Ah, yes. It seems to be in:

http://download.opensuse.org/repositories/isv:/ownCloud:/community:/testing/xUbuntu_14.04/amd64/
http://download.opensuse.org/repositories/isv:/ownCloud:/community:/testing/xUbuntu_14.04/i386/

but not in:

http://download.opensuse.org/repositories/isv:/ownCloud:/community:/testing/xUbuntu_14.04/all/

**Comment by jnweiger** [comment]
There was a wrong Architecture: any in obs_check_deb_spec.sh and error propagation was moot.
Fixed both in the 8.1.0~Beta1-2 rebuild.

**Comment by SergioBertolinSG** [comment]
Tested used packages 8.1.0~Beta1-3. Not working, encryption app is installed in /usr/share. It should be with the rest of the apps.

**Comment by DeepDiver1975** [comment]
@jnweiger

**Comment by jnweiger** [comment]
That was a very old install file. been there since the beginning of 8.x probably. :-(
fixed to be in /var/www/owncloud as is everything else.

**Comment by SergioBertolinSG** [comment]
Tested using 8.1.0~Beta1-5

There is a problem with apache conf file, is missing in this version.
```
Setting up owncloud-config-apache (8.1.0~Beta1-5) ...
ERROR: Conf owncloud does not exist!
```

**Comment by RealRancor** [comment]
@SergioBertolinSG 
Looks to me unrelated to the missing encryption app itself. Isn't it better to create a new issue for this?

**Comment by DeepDiver1975** [comment]
@jnweiger can you please have a look once more - THX

**Comment by jnweiger** [comment]
@SergioBertolinSG all the 8.1.0~Beta1-5 packages are in https://s2.owncloud.com/package/binaries/ee:8.1/owncloud?repository=xUbuntu_14.04 -- including owncloud-config-apache.

Are you mixing in http://download.opensuse.org/repositories/isv:/ownCloud:/community:/testing/xUbuntu_14.04/all/ ? There we have 8.1.0~Beta1-4

**Comment by SergioBertolinSG** [comment]
@jnweiger I am testing with internal repo always. 

I think the problem is in owncloud-config-apache package. And not in the first install but in the second.
When installing 8.1.0~beta1-5 first time in debian (after removing previous 8.0 packages) :
```
Setting up owncloud-config-apache (8.1.0~Beta1-5) ...
Configuration file `/etc/apache2/conf-available/owncloud.conf'
 ==> Deleted (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** owncloud.conf (Y/I/N/O/D/Z) [default=N] ? Y
Installing new version of config file /etc/apache2/conf-available/owncloud.conf ...
```
This worked fine.

Uninstalling full owncloud and installing it for a second time throw a similar error than ubuntu:
```
Setting up owncloud-config-apache (8.1.0~Beta1-5) ...
Action 'configtest' failed.
The Apache error log may have more information.
Your Apache 2 configuration is broken, so we're not restarting it for you.
```

**Comment by cmonteroluque** [comment]
@jnweiger Any chance we can get this issue resolved? It's been dragging for over a week since the last comments

**Comment by jnweiger** [comment]
The original issue regarding the encryption app is fixed.
The remaining part is a general update issue. It revolves around the logic discussed in 
https://github.com/owncloud/core/issues/16189 https://github.com/owncloud/core/issues/14610 
I'll experiment with dropping the dpkg-divert call, as nobody seems to have an explanation what it is good for.

**Comment by jnweiger** [comment]
With rebuild 8.1.0~Beta2-3 we now have a much simpler debian.owncloud-config-apache.preinst
file: No more dpkg-divert, as this is not recommended for config files by debian anyway.
We create the backup copy and leave the original file in place now. This avoids an error about missing config file owncloud.conf for me.

@SergioBertolinSG  I cannot fully reproduce what you reported. The second install was never an issue.
Both with 

    apt-get remove owncloud; apt-get install owncloud

and 

    apt-get purge owncloud; apt-get install owncloud

the 8.1 package behaves the same. All Errors I saw were with the initial upgrade from 8.0.3 to 8.1
-- so I definitly fixed something else, but I hope this also improves the situation for you. Please retest.
