### ISSUE TITLE
Fix error message grammar

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#16286]
### Steps to reproduce

1. Install 8.1 
2. Check server log file for any messages

### Expected behaviour

The messages should have correct grammar.

### Actual behaviour

This one is a bit incorrect:

```
{"reqId":"prmEK\/9JlSXCTXF+drsJ","remoteAddr":"","app":"PHP","message":"xcache_clear_
cache(): Cache not exists at \/var\/www\/html\/owncloud\/lib\/private\/util.php#1338"
,"level":3,"time":"2015-05-12T15:24:35+00:00"}
```

It should read:

```

Cache does not exist at

```

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration:

ownCloud Enterprise Edition 8.1 beta 1 (daily) Build:2015-05-12T03:08:46+00:00 20d2d8d3ddee2750343bdec69a3e7031b710039a

**Comment by RealRancor** [comment]
Hi,

there was already a similar issue reported here. I can't find it at the moment but the other one was closed because the wording is broken upstream in xcache.

**Comment by jnfrmarks** [comment]
Ah yes!  At least I'm consistent ;)  Closing
