### ISSUE TITLE
Full long remote sharee address shown in »Shared with others« view

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#16281]
In the »Shared with others« view (and probably in the other views as well), we show the full `jan@localhorst/owncloud-dev` address:
![sharedwith](https://cloud.githubusercontent.com/assets/925062/7587972/3bb9aa76-f8ba-11e4-9023-b5f5711dd651.png)
Instead we should do it like in the main view and only show `jan@…` and show the full address as tipsy tooltip on hover. Otherwise we will quickly run out of horizontal space. And it’s just not as important to always see the full server address.

@schiesbn @PVince81 can you fix that?

**Comment by PVince81** [comment]
or @rullzer if you have time (I'm still busy fixing other regressions...)

**Comment by rullzer** [comment]
@jancborchardt in which view do we have the shorthand? I can't find it currently and would like to avoid duplication of the code.

**Comment by jancborchardt** [comment]
@rullzer in the »All files« view, for when you got something shared from someone on another server.

**Comment by MorrisJobke** [comment]
Fixed with #16380
