### ISSUE TITLE
User can't install root certificate

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#16288]
### Env
Master, PHP 5.5

### Steps to reproduce

1. Go to user settings
2. Click on "Import root certificate"
3. Select PEM encoded certificate

### Expected result

The certificate should be uploaded and listed in the admin area

### Actual result

The GUI shows the following error
"An error occurred. Please upload an ASCII-encoded PEM certificate."

which according to the logs is not what is happening

### Logs

`"app":"no app in context","message":"Logged in user must be an admin","level":0,"time":"2015-05-12T15:44:30+00:00","method":"POST","url":"\/index.php\/settings\/personal\/certificate" `

**Comment by LukasReschke** [comment]
Did I mention that I'm stupid?

**Comment by oparoz** [comment]
Err... We all make mistakes :)

**Comment by LukasReschke** [comment]
https://github.com/owncloud/core/pull/16289 :see_no_evil: :hear_no_evil: :speak_no_evil:

**Comment by oparoz** [comment]
OK, so #16289 takes care of the must-be-an-admin problem, but I still can't upload the cert as a user. No problem if I'm an admin.

**Comment by LukasReschke** [comment]
Ah… In Settings we also have a subadmin middleware… :dancers:

**Comment by LukasReschke** [comment]
Recheck please @oparoz. Works fine locally on a completely unprivileged newly created user.

**Comment by oparoz** [comment]
This is fixed by #16289 \o/
