### ISSUE TITLE
Some vCards would not upload via CardDAV

### ISSUE THREAD

**Issue by biolumin** [owncloud/core#16294]
In 8.0.2 I had issues importing several vCards from my Apple Mac Addressbook.app. They would not import whatsoever, and when attempting to upload them via CardDAV, would halt the upload cue once those problematic cards were trying to be uploaded. I had to delete those cards and create new ones with the same information in order to work around this issue.

Has anyone else had a similar issue?

**Comment by RealRancor** [comment]
Hi,

i think this is something which belongs to the issue tracker of the calendar app at: https://github.com/owncloud/calendar/issues

You can re-open this there using the issue template provided here:

https://raw.github.com/owncloud/core/master/issue_template.md

**Comment by biolumin** [comment]
Calendar app handles vCards and CardDAV requests? I would have presumed the Contacts app may have handled these requests, so I'm surprised to see you suggest I submit this to the Calendar app issue tracker.

Thanks for providing the issue submission template. I'll be sure to use it to re-submit my issue.

**Comment by RealRancor** [comment]
Arrghhs, you're right. Sorry, its the contacts app:

https://github.com/owncloud/cantacts/issues
