### ISSUE TITLE
autotest.sh broken if PHPUnit is installed using a script as facade

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#16296]
If PHPUnit is installed using a script as facade invoking it will fail, in my case this means:

```
➜  master git:(master) ✗ which phpunit
/usr/local/bin/phpunit
➜  master git:(master) ✗ cat /usr/local/bin/phpunit
#!/usr/bin/env bash

/usr/bin/env php -d allow_url_fopen=On -d detect_unicode=Off /usr/local/Cellar/phpunit/4.6.4/libexec/phpunit-4.6.4.phar $*%
```

Invoking `php /usr/local/bin/phpunit` will fail hard now. As it is a shell script and not a PHAR file.

Regression caused by https://github.com/owncloud/core/pull/16045

**Comment by DeepDiver1975** [comment]
8.1? 8.2? never?

**Comment by LukasReschke** [comment]
8.1 - annoys me as hell: https://github.com/owncloud/core/pull/16367
