### ISSUE TITLE
Apps are not listed in alphabetical order

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#16295]
### Steps to reproduce

1. Install 8.1 
2. Navigate to the not enabled apps page

### Expected behaviour

Apps should be in alphabetical order

### Actual behaviour

Apps are not in alphabetical order.  This is the same on the Enabled apps page as well. 

![p343](https://cloud.githubusercontent.com/assets/8480343/7595570/d8c83e04-f8b5-11e4-8959-ab905a74b903.PNG)

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration:

ownCloud Enterprise Edition 8.1 beta 1 (daily) Build:2015-05-12T03:08:46+00:00 20d2d8d3ddee2750343bdec69a3e7031b710039a

**Comment by jnfrmarks** [comment]
From the Enabled apps page:

![p344](https://cloud.githubusercontent.com/assets/8480343/7595771/0badc1da-f8b7-11e4-979b-5d4c8c38be36.PNG)

**Comment by PVince81** [comment]
I seem to remember seeing sort functions being called on the server, so it's probably a bug.

**Comment by DeepDiver1975** [comment]
Apps are sorted by the level - https://github.com/owncloud/core/blob/master/settings/js/apps.js#L95

**Comment by MorrisJobke** [comment]
> Apps are sorted by the level - https://github.com/owncloud/core/blob/master/settings/js/apps.js#L95

Then this isn't a bug?!?

**Comment by PVince81** [comment]
But when they have the same level, they should also be sorted alphabetically after that

**Comment by DeepDiver1975** [comment]
> But when they have the same level, they should also be sorted alphabetically after that

yep

**Comment by PVince81** [comment]
Will do

**Comment by PVince81** [comment]
Looks like the sorting is a mess.
There is server side sort and client side sort.
The client side sort is always run and sorts by level (and I'll add sort by name if the level is the same). This is regardless of the selected section.

Now I also see that some apps don't even have a "level" field. What's the default level to use then ?

**Comment by PVince81** [comment]
Ok, I'll make them default to 0. This means that experimental apps will now properly be listed at the end of the list instead of the top.

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/core/pull/16467
