### ISSUE TITLE
Remove "this is the final warning" from message

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#16298]
### Steps to reproduce

1. Install 8.1 
2. Enable Encryption module
3. Navigate to admin page
4. Click on server side encryption

### Expected behaviour

Get message about one way aspect of encryption

### Actual behaviour

For me the message should not include "this is the final warning" - that sounds a bit like a threat :)

Can we remove the 'This is the final warning' part of the message?

![p345](https://cloud.githubusercontent.com/assets/8480343/7596373/2c8309d4-f8bb-11e4-8b78-ef1cecebcfc5.PNG)

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration:

ownCloud Enterprise Edition 8.1 beta 1 (daily) Build:2015-05-12T03:08:46+00:00 20d2d8d3ddee2750343bdec69a3e7031b710039a

**Comment by jnfrmarks** [comment]
@MTRichards

**Comment by nickvergessen** [comment]
@schiesbn

**Comment by LukasReschke** [comment]
This text was requested by @MTRichards in https://github.com/owncloud/core/pull/16037#issuecomment-98758891

**Comment by schiesbn** [comment]
@jnfrmarks I agree with you but it was requested by @MTRichards so I think he should decide if we remove it or not.

**Comment by jnfrmarks** [comment]
@MTRichards 

Matt, what do you think about removing the "This is the final warning" from the message?

**Comment by MTRichards** [comment]
It is a little shocking, but this is on purpose. Encryption really is a one way process and if the final warning shocks some people to ensure that they really really mean it, then the phrase has served its purpose. I would rather leave it, and have a few people scratch their heads, then remove it and have even one person not really fully understand how serious the implication is for their ownCloud instance.

**Comment by jnfrmarks** [comment]
Closing based on above comment.
