### ISSUE TITLE
Versions Deletion: Guarantee Deletion Date and Retention Obligation

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#16301]
As an ownCloud administrator, I want to set the versions file expiration policy so that I can better manage the disk space of users within ownCloud.

Acceptance Criteria:
- Create a new config file option to manage the versions for a user
- App registers with Cron so it is run regularly and files are properly deleted on time
- A modified line in the sample.config.php would highlight how this works
- The setting is called versions retention obligation
- The description is "If the versions app is enabled (default), this is the minimum and / or maximum number of days a file is kept in the versions file before it is deleted. Setting can be number of days, auto or disabled" (auto = the auto expiration algorithm of today)
 Syntax is something like:
       'versions_retention_obligation' => min 30, max 31
        OR 'versions_retention_obligation' => min 30,auto
        OR 'versions_retention_obligation' => min 30
        OR 'versions_retention_obligation' => auto, max 30
        OR 'versions_retention_obligation' => auto
        OR 'versions_retention_obligation' => disabled (or just comment out the line in the config file)
- If Max is less than min, the min setting wins - so a file is always kept at least as long as the min, but in this case is immediately deleted as soon as the min is met
- If min is Auto, then the file is only kept as long as the space saving algorithm decides, up to a max of the max setting
- if max is auto, then the file is kept as long as the space saving algorithm says, and perhaps may never be actually deleted (this is the current behavior that we are adjusting)
- a setting of disabled (or a commented out config file line item) would remove this and all files would be kept forever
- if only a min value is specified, then really this is the same as no expiration or disabled
- Migration should be simple since there is no setting today for this in the config file

**Comment by MTRichards** [comment]
Additional acceptance Criteria:
- If the system runs out of quota (or gets within 10% of quota) the system needs to throw a warning of some kind. And again at 5%.

THIS needs to be figured out, and probably not here in this user story.

**Comment by schiesbn** [comment]
After thinking about this, is this something ownCloud has to monitor at all? This isn't really ownCloud related but a general server monitoring issue as such. Every admin should have some server monitoring which tells him when he runs out of memory. 

This is not only related to version and trash bin handling. Think about a ownCloud setup without any user quota. In this case you have the same problem, people will upload files and at some point the server can reach his storage limit. ownCloud will not detect this or issue any warnings but expects that the server admin control and monitor his server properly.

In another scenario you could also think about a server which doesn't only run ownCloud but also some additional applications. In this case ownCloud can't control it at all because the other applications could also fill up the hard-disk between two ownCloud server calls.

**Comment by MTRichards** [comment]
I agree that the system storage running out is something that needs to be monitored in general, and while this increases the risk of running out of storage, it does not raise a new problem.

**Comment by MTRichards** [comment]
One more acceptance criteria was just added from a customer
 
Acceptance Criteria:
- We can set the threshold for versions, so that files larger than (for example) 100MB are not versioned.
- Admin can set this in the admin panel under the versions settings and be any file size
- Option can be disabled so that there is no max version size, or enabled and then this version filesize entry is allowed

**Comment by DeepDiver1975** [comment]
@VicDeo cron is required here as well - see https://github.com/owncloud/core/issues/16300#issuecomment-129602374

Please open up two separate prs for this as well - THX

**Comment by VicDeo** [comment]
@MTRichards 
>Additional acceptance Criteria:
If the system runs out of quota (or gets within 10% of quota) the system needs to throw a warning of some kind. And again at 5%.
THIS needs to be figured out, and probably not here in this user story.

I suppose this is not related to versioning itself as it looks like  https://github.com/owncloud/core/issues/5352 to me

**Comment by MTRichards** [comment]
@VicDeo yes, it is a bigger problem and not solvable here. Lets track it in #5352

**Comment by VicDeo** [comment]
@MTRichards currently logic is not based on space solely but on how old the version is:

		//first 10sec, one version every 2sec
		//next minute, one version every 10sec
		//next hour, one version every minute
		//next 24h, one version every hour
		//next 30days, one version per day
		//until the end one version per week

**Comment by MTRichards** [comment]
Right. So the disk quota topic is somewhat irrelevant here anyway.

**Comment by PVince81** [comment]
@VicDeo seems you added quota logic in your PR ?

**Comment by VicDeo** [comment]
@PVince81 it existed before me. Something like `Let's kill all versions until `DEFAULTMAXSIZE` is freed

https://github.com/owncloud/core/blob/master/apps/files_versions/lib/storage.php#L48

**Comment by PVince81** [comment]
@VicDeo anything left to do for this task ?

**Comment by DeepDiver1975** [comment]
implemented -> close
