### ISSUE TITLE
ownCloud Right Side File / Folder Details

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#16308]
As a user, I want details about file and folder options to show on the right side of the screen when I mouse over a file or folder so that I can set comments, tags, see file details and make and remove sharing options. 

Acceptance Criteria:
- Essentially providing a construct to use the right side real estate on the files view
- Details would include full File name, the ownCloud owner (share owner or this user if not shared with this user), create time, last modified time, type (mimetype), Size
- Comments would be a linear oldest to newest
- Each of the categories of additional info (details, comments, tags, sharing) would be via a twisty of some kind so that the selected feature could use more of the real estate than the rest as per the user's decision. By default, file sharing is opened, and all details of a selected file or folder are shown.

Could look something like this (help!):
![untitled](https://cloud.githubusercontent.com/assets/1818977/7600530/22298c46-f8da-11e4-8fe4-b272ac4798d8.png)

@jancborchardt I know you have some thoughts here, can you help with a rough design?

**Comment by MorrisJobke** [comment]
Redesign sharing dialog: #3224

**Comment by jancborchardt** [comment]
First work-in-progress of a sidebar: https://github.com/owncloud/core/pull/16414

**Comment by jancborchardt** [comment]
Rough first mockup:
![](https://raw.githubusercontent.com/owncloud/design/master/Files/Sidebar-mockup.png)
([source in the design repo](https://github.com/owncloud/design/tree/master/Files))

**Comment by schiesbn** [comment]
Just a idea I had while looking at the mockup: Should the sidebar also handle versions. For consistency reasons I think this could be a good idea. Opinions?

**Comment by MTRichards** [comment]
yes I think it should.

**Comment by jancborchardt** [comment]
@schiesbn yes it should be – ideally inside the Activity tab because version are also chronological information. As you see the top entry »Updated by you minutes ago« would create a new version.

**Comment by schiesbn** [comment]
@jancborchardt makes sense. Although this could create problems with the current way our expire algorithm works, we don't only expire the oldest versions but also versions in between. So not all update activities will have a version attached which could be quite irritating from a user point of view.

Another thought: At some point the activity tab probably needs a way to filter for comments, changes, etc. to make it easier to get an overview.

**Comment by MTRichards** [comment]
For files and folders that are renamed, can we add a file detail about "file or folder originally shared as" option so that people can know if things got renamed? Clearly this would also be searchable...

**Comment by schiesbn** [comment]
> For files and folders that are renamed, can we add a file detail about "file or folder originally shared as" option so that people can know if things got renamed? Clearly this would also be searchable...

We could add it, from the technical point of view this would mean that we would need a exte column in the share table.

One general thought to make sure that we understand the overall problem correct before we are looking for a solution: The main reason why we want to have this is that the owner can say to a group of people something like "I have shared file foo.txt with you, please have a look". But what happens if the owner renamed the file a week later from foo.txt to bar.txt? The next time he talks to the people he would probably say "I have shared file bar.txt with you, please have a look". So maybe what we really want is not the name of the file when it was shared but the current name of the original file. On the other hand you could argue that this is a privacy issue if you always expose the filename from the owner to the recipients.

Maybe what we really want are Permalinks https://github.com/owncloud/core/issues/11732 instead of trying to keep different filenames in sync?

**Comment by PVince81** [comment]
Let's use this as the main ticket for the right sidebar work.

And raise separate tickets for the different sub-tasks:
- [ ] Ground work for right sidebar: 
- [ ] Convert FileActions to be a dropdown (@jancborchardt wasn't there already a specific ticket for this?)
- [ ] Move share dialog into a tab in the sidebar
- [ ] Tagging: https://github.com/owncloud/core/issues/16325
- [ ] Comments
- [ ] Activity list + API to register

@jancborchardt can you update the list of requirements (or delete them if they are obsolete) ?
Your PR mentions a few https://github.com/owncloud/core/pull/16414#issue-77652540 but I'm not sure whether they still match the latest discussions.

**Comment by PVince81** [comment]
@DeepDiver1975 @blizzz FYI

**Comment by jancborchardt** [comment]
@PVince81 updated the list in https://github.com/owncloud/core/pull/16414#issue-77652540 and linked the file actions dropdown issue: https://github.com/owncloud/core/issues/12081

**Comment by PVince81** [comment]
Raised https://github.com/owncloud/core/issues/17665 for moving the share dialog.

**Comment by PVince81** [comment]
Raised https://github.com/owncloud/core/issues/18164 to work on the generic event/activity mechanism that should allow to mix activities, comments and versions.

**Comment by PVince81** [comment]
The sharing dialog PR is here, for reference: https://github.com/owncloud/core/pull/18185

**Comment by jancborchardt** [comment]
Closing because this is basically done. The only parts left are tracked in their own respective issues: https://github.com/owncloud/core/issues/16325 (tagging) and https://github.com/owncloud/core/pull/18185 (sharing to sidebar pull request)
