### ISSUE TITLE
External Storage: Apps Inherit User Experience 

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#16304]
As an admin, I want the external storage app and any individual apps (such as SharePoint or WND) to share capabilities so that there is one code base to manage, and UX and interface elements are common across ownCloud.

Acceptance Criteria:
- Core file management behavior and error messages are shared with core
- Core error messages and display elements are shared with the existing WND
- Core behavior and external storage settings can be reused - Example: sharing. Admin must be able to turn on and off the ability for a user to share contents of a folder mounted with external storage.

@PVince81 I seem to remember a post from you on this. Any specifics to add?

**Comment by PVince81** [comment]
There was https://github.com/owncloud/core/issues/12338 for the UX improvements (UI elements and error detection) and also the bigger https://github.com/owncloud/core/issues/12216 for various mount options.

From your post it sounds like you'd like to schedule "disable sharing" as well for 8.2 ? This is here: https://github.com/owncloud/core/issues/8631

**Comment by MTRichards** [comment]
New Acceptance Criteria:
-  Take into account migration from the current state seamlessly into the new deployment so that existing external storage mounts (all of them - from WND and SharePoint to FTP etc) do not break

**Comment by PVince81** [comment]
For the migration: the WND and sharepoint apps should move the configurations from the database and then register it to the files_external backend. Currently this would be `OC_Mount_Config::addMountPoint` but it will be improved to have a more usable API thanks to @Xenopathic

**Comment by PVince81** [comment]
#### WND/Sharepoint side:
- [ ] update the Storage classes to match the ones from files_external (see other backends as examples, like SMB or SFTP)
- [ ] adapt the configuration to be registered as part of the storage backend in OC_Mount_Config. This will make the configuration options appear in the admin page
- [ ] write app-specific migration code (appinfo/update.php) that will move all the known storages from the database to the OC_Mount_Config API
- [ ] check whether custom fields / custom JS are required in case the field types don't match 100% in the ones supported files_external
@jmaciasportela

#### files_external changes
- [ ] Refactor the configuration code to support auth types + better API for registering backends: https://github.com/owncloud/core/pull/15914 (@Xenopathic)
- [ ] UX improvements like credential changes and unavailable storages: https://github.com/owncloud/core/issues/12338

**Comment by Xenopathic** [comment]
This will be done in 9.0, when the new API becomes OCP

**Comment by cmonteroluque** [comment]
Guys, "this will be done in 9.0" is not decided this way. We had a commitment to make it this release and it's not right that with a couple of days to go engineering unilaterally decides 9.0. Not a good situation.

**Comment by Xenopathic** [comment]
@cmonteroluque As it stands at the moment, the files_external UI does not have the requisite features for Sharepoint or WND to seamlessly integrate with it. Some of these features are pretty major and likely to cause regressions

**Comment by cmonteroluque** [comment]
@Xenopathic ping. Trying to reach you

**Comment by MTRichards** [comment]
The goal is to incorporate SharePoint into the External Storage app to share the UX from External Storage, while leaving SharePoint configuration an EE only capability. Specifically, this is about allowing usernames and passwords to be stored in the session, rather than in the ownCloud database. Sharing doesn't work, but it is seen as more secure. Also, we need to be able to detect and not allow folders with the same name to be created, for example, which is all handled in external storage.

**Comment by PVince81** [comment]
Let's keep this ticket in case we need further changes in core for Sharepoint's config stuff.

And use https://github.com/owncloud/sharepoint/issues/120 for the actual ticket to do the sharepoint code integration with files_external.

**Comment by MTRichards** [comment]
Added comments from Design Week:
- The backend code that talks to SharePoint remains inside the plugin
- SharePoint app becomes a plugin of the external storage app
- SharePoint plugin also handles the added dropdowns to connect to SharePoint

A plugin has multiple parts
1) Storage implementation (translates storage commands into sharepoint)
2) Config options (user name, path, etc) to be able to display it in the GUI and display in the database
3) SharePoint specific stuff (kept for later)


Work Package:
- 
- SharePoint migration scripts (see windows network drives migration for an example)

1 - Clean app. Delete some JS (keep dropdowns), AJAX CALLS, TEMPLATES. Save content from appinfo, imgs, lib, test.
2- Files external dependency. Check enabled, and enable if not. 
3- Create Files external backend with our Storage implementation. In case of sharepoint there is some elements in the UI that don't exists on files external. For example a button to retrieve available document list from SharePoint server. You will need to implement those elements, or change the way of how to create new mounts.
4- Merge SharePoint with WND into a new app called "Enterprise External Storage".
5- Migration is the biggest work. You have to map current scheme to files_external scheme. Should be almost the same work that WND
6- Documentation on the new structure, explanation, screenshots, new steps
7- Enable new app by default in the enterprise version (so does external storage)
8- TEST

**Comment by MTRichards** [comment]
Estimation: 3 weeks

**Comment by PVince81** [comment]
Feature/refactoring didn't make it into 9.1, moving to 9.2.

CC @dragotin @DeepDiver1975

**Comment by PVince81** [comment]
WND integration was done but not Sharepoint. Sharepoint integration is tracked in private repo, so closing in favor of that one: https://github.com/owncloud/sharepoint/issues/120

@pmaier1 FYI
