### ISSUE TITLE
External Storage: User Personal Page UX

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#16307]
As a user, I want to be able to see all of my external storage usernames and passwords are in one place, so that I can update passwords, add my own mounts, and delete mounts as appropriately allowed by the admin.

Acceptance Criteria:
- [x] These settings are in a new section in the user's personal settings page
- [x] The page has an external storage section (or if another external storage app like SharePoint is enabled, there are multiple sections, one per app)
- [x] The admin can check a box in the app admin panel – users can add their own external storage or not 
- [x] Only external storage mounts that were added by the user can be deleted by the user – admin created mounts cannot be deleted or removed (and the folder can't be deleted in the root view)
- [x] At the top of the page is a field “My Username and Password”. These fields can be used for each of the external storage mounts
- [x] Passwords are stored encrypted in the database (as securely as possible)
- [x] Each external storage site that an admin has set for this user (whether the user is part of all, a group, or an individual user assignment) appears as a row in this table
- [x] The user can assign a unique username and password at any time by unchecking the selection and entering a unique username and password

**Comment by PVince81** [comment]
There is already a section for external storages in the user's personal page, but it currently only lists the user-mounted ones. That list could be extended to have two sections: "Your storages" and "Admin configured storages".

This seems to be an extension of the different auth types proposed here #16305, which would require having this UI change to allow the user to enter credentials as required based on which authentication type was selected by the admin.

CC @Xenopathic

**Comment by Xenopathic** [comment]
@PVince81 Yup, that's exactly what I was thinking. We could have two sections, one read-only listing the admin storages that apply to the user, but what about showing those storages inline with existing storages, but greyed out to indicate read-only-ness?

**Comment by PVince81** [comment]
@Xenopathic it wouldn't be always grayed out (or not completely). There are some auth cases where the user should still be able to enter their credentials for that specific mount points, as requested here https://github.com/owncloud/core/issues/16305

**Comment by Xenopathic** [comment]
@PVince81 Of course, that's the flexibility of having it inline :smile:

**Comment by PVince81** [comment]
@Xenopathic I ticked some boxes. Weren't we done with all of them in 9.0 ?

**Comment by Xenopathic** [comment]
The 'personal credentials' feature was purposefully kept out of core, since it wouldn't be very useful to self-hosters and is only really a feature for enterprise customers, so I think that stayed in WND. The rest was merged though.
