### ISSUE TITLE
User with permission to share folder shares folder and duplicate is created

### ISSUE THREAD

**Issue by jason-vivid** [owncloud/core#16303]
Steps to reproduce:

1. User 1 owns Folder A and subfolders and gives share permission to Group 1
2. User 2 (member of Group 1) navigates to Subfolder B and shares Subfolder B with Group 2
3. User 3 (a member of both groups) sees two folders in this case they are "Finance Requests" and "Finance Requests (2)".  The first is owned by the original user and the second is owned by User 2.

**Comment by karlitschek** [comment]
@schiesbn

**Comment by PVince81** [comment]
@jason-vivid please use the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

This should work properly in 7.0.5 and 8.0.3

**Comment by PVince81** [comment]
Closing due to lack of info.
