### ISSUE TITLE
External Storage Interface: Trigering user username and password Entry

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#16302]
As an Admin, I want to be able to select an external storage password policy of "user credentials" so that a user will be automatically prompted to enter a username and password when logging into ownCloud.

Acceptance Criteria:
- The folder mount point becomes red with a little warning triangle and a warning is displayed, like in the current SharePoint plugin
- A yellow button on the top of the screen “Your credentials for <external storage type> are incorrect. Please click on the [mount] folder to update your credentials.”
- When the red highlighted external storage is clicked, a pop up appears over the current windows, with a text message:
	Please enter your username and password for [mount].
- Then a username and password field is there.
- A connect button is also there to set these settings when the username and password are enterred
- If more than one error exists, a user can update the entries by clicking on the folder with the error.
- Credentials can always be updated in the personal page
- If a credentials error is detected at any time by the app, the folder is once again triggered
- Credentials are stored as encrypted as possible in the database (and not LOGGED!)

**Comment by PVince81** [comment]
Relates to / depends on https://github.com/owncloud/core/issues/16305.

I guess this workflow would only apply for the authentication types "User Entered" and "User Login, DB" for system-wide mounts, and for any kind of personal mount.

**Comment by DeepDiver1975** [comment]
@MTRichards @cmonteroluque 9.0 ???

**Comment by MTRichards** [comment]
Has to be, but this is also covered under the "make WND like external storage" user story.

**Comment by cmonteroluque** [comment]
nod

**Comment by PVince81** [comment]
Discussed with @icewind1991 today.
- the "is password needed check" could be done as part of the storage availability check in the file list, as per https://github.com/owncloud/core/issues/20427
- when such storage is detected, show the notification then dialog
- after entering the password, the password is sent to the server to be saved

- [ ] build on status check to find out if password entry is required
- [ ] dialog for password (maybe reusable from WND code?)
- [ ] new endpoint for sending the password to the server (add this in files_external)
   - [ ] use the same DB table as "login credentials" auth to save the credentials (see https://github.com/owncloud/core/issues/18531)

**Comment by PVince81** [comment]
@jmaciasportela can you help with adding the JS part, on top of your PR https://github.com/owncloud/core/issues/20427 ? (or separately after it is merged)

**Comment by PVince81** [comment]
@icewind1991 can you take care of building the endpoint as soon as https://github.com/owncloud/core/pull/18531 is merged ?

**Comment by jmaciasportela** [comment]
@PVince81 We can reuse WND dialog to enter credentials and there are two cases to show this dialog:

- An admin create a mount point and is configured to use user credentials and the user doesn't enter them yet or stored credentials are incorrect.
- An user create a mount point and is configured to user user credentials or custom credentials and credentials are not stored yet or they are incorrect.

For that we need to use the new storage status codes https://github.com/owncloud/core/pull/20729. So maybe is better to merge it before.

**Comment by PVince81** [comment]
This was implemented in files_external as part of the integration, in 9.0.
Closing.
