### ISSUE TITLE
Add native support  for One time password [OTP]

### ISSUE THREAD

**Issue by jsalatiel** [owncloud/core#16309]
Please, add support for OTP passwords in owncloud. I know there is the 3rd part app named OTP, but it is not actively maintained, and there are several bugs and limitations.

**Comment by DeepDiver1975** [comment]
The power if ownCloud comes with its apps. Auth backends are a perfect example for apps which extend core functionalities. 

I suggest to fix the existing app and find a nww maintainer.

Closing this as this is not a core issue.
