### ISSUE TITLE
What is my group?

### ISSUE THREAD

**Issue by jhsnpk** [owncloud/core#16315]
I am a user of ownCloud 8.0 and I want to share a file with all user in my group.
How will I know that which group I am a member of?
How will I get a list of all members in my group so that I know the persons with whom my file has been shared.

**Comment by RealRancor** [comment]
Hi,

according to https://doc.owncloud.org/server/8.1/user_manual/whats_new.html#groups-listings-on-personal-page this will be possible in OC 8.1

**Comment by jhsnpk** [comment]
Thats good!
and what about the list of others in my group?

**Comment by MorrisJobke** [comment]
> and what about the list of others in my group?

I don't think we will add this. @butonic Had the idea to share with contacts, but this needs to be implemented first.

@DeepDiver1975 Close this or keep it open?

**Comment by DeepDiver1975** [comment]
From my pov we shall not disclose information like that. In addition: think about big installations with e.g. tens of thousands of users - it's of zero intetest to see that half of the company/university/organization is in groups with you.
