### ISSUE TITLE
owncloud and user otp full name search to share

### ISSUE THREAD

**Issue by lazyprogram** [owncloud/core#16311]
Owncloud with User OTP, Cannot share to a user by searching using full name.

Owncloud 7.0.4
User OTP Extension 2.5

FYI, If i disable user otp means its working fine. Please find the attached screenshot for my share settings.
![share](https://cloud.githubusercontent.com/assets/11037540/7602626/4822408a-f959-11e4-8e9b-c597b1e9fcf9.png)

**Comment by RealRancor** [comment]
Hi,

@lazyprogram 
not absolutely sure but i think you should report this in the issue tracker of the User OTP app located here:

https://github.com/loki36/user-otp/issues

**Comment by lazyprogram** [comment]
Ok thanks. Posted https://github.com/loki36/user-otp/issues/105
