### ISSUE TITLE
Fix for client authentication issues on some webhosts

### ISSUE THREAD

**Issue by rvega** [owncloud/core#16312]
Hi. Sorry I can't provide too much detail here (I'm not too sure what's going on) but this fixed my owncloud install and now the desktop client can authenticate to the server. Thought you might be interested in merging this into the codebase.

http://www.blaicher.com/2012/07/fixing-authentication-of-owncloud-for-webfaction/

**Comment by RealRancor** [comment]
Hi,

seems this was already discussed at some points at https://github.com/owncloud/core/issues/9880 and https://github.com/owncloud/core/issues/13398
