### ISSUE TITLE
Resharing with new user

### ISSUE THREAD

**Issue by jhsnpk** [owncloud/core#16316]
Using ownCloud 8.0, and Encryption app is ON.
I have shared a file/folder with a group. Now a new user is added into the same group. When the new user tries to open the file, error message appears.
"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you."
How to solve this issue?

**Comment by RealRancor** [comment]
Hi,

i think the message:

> Please ask the file owner to reshare the file with you

already tells you what to do.

**Comment by jhsnpk** [comment]
The problem is if the group has a large no. of people, even 500, then unsharing and resharing takes a lot of time.

**Comment by RealRancor** [comment]
Hi,

just read the whole issue linked above where you can find a solution for this: https://github.com/owncloud/core/issues/7352#issuecomment-47121487

**Comment by RealRancor** [comment]
@schiesbn Is this something which should be documented? Did that changed in encryption 2.0?

**Comment by PVince81** [comment]
I don't think this changed.

**Comment by schiesbn** [comment]
It is documented here https://doc.owncloud.org/server/8.1/user_manual/files/encrypting_files.html#sharing-encrypted-files

Nothing will change with encryption 2.0, the goal was to make it more modular for future development but didn't change the behavior to provide a smooth upgrade path

**Comment by jeremyclarke** [comment]
There needs to be a LOT more messaging inside the app about shares that won't be accessible to users. Currently it's an inscrutible black box of mystery access (or pretty much no access to existing shares for new users without manual intervention). 

When I create a new user and add them to a group the app should do one of two things:

1) Grant the user access to all the stuff the group has access to.
2) Warn the admin about the problem including steps to grant access to the files. 

Anything else is pretty much unacceptable, and leads to the admin waiting for the user to complain about broken files, then fixing them as they come up.
