### ISSUE TITLE
PDF download in PDF viewer does not work in Firefox

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#16319]
When I click on a PDF file the PDF viewer opens in the Browser. If i choose to download the file by clicking on the download button top right, it does not work in Firefox. It does work in Chrome though.

I tested this in our ownCloud instance as well as on your Demo Site.

@MorrisJobke 

00003145

**Comment by LukasReschke** [comment]
PDF Viewer tracker is at https://github.com/owncloud/files_pdfviewer/ and also test https://github.com/owncloud/files_pdfviewer/pull/53 which should fix this.

**Comment by cdamken** [comment]
@LukasReschke Thanks!
