### ISSUE TITLE
Encryption: Script to Encrypt All or Decrypt All

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#16327]
As an ownCloud admin, I want to be able to encrypt an existing ownCloud instance to begin to use encryption, or decrypt an entire ownCloud instance to turn off encryption so that I can secure my data operationally and have the flexibility to migrate if circumstances change.

Acceptance Criteria:
- Can be implemented as an occ command
- Will work in the background and put the system into a suspended mode while this is happening so that user data is not corrupted by interrupting mid process
- Will work as quickly as possible, but may take quite some time so some form of feedback to the admin at the command line would be nice to see
- Unencrypt command can only be set if there is a recovery key enabled. 
- If an admin is upgrading an ownCloud instance and has encryption enabled, this commend should be executed as part of the upgrade - with appropriate notifications and warnings about how long it will take
- If an error is encountered, such as a timeout, this process should be roll back capable, or at least can be halted in process and not destroy all user data.
- Maintenance mode will need to be set prior to doing any of this work, so the process is not interrupted.

@schiesbn Please add comments.

**Comment by schiesbn** [comment]
Possible implementation:

Encrypt all:

- first we create a public/private key for all users and encrypt the private key with a random password
- then we encrypt all the files, this was all shares can be encrypted right away to all recipients
- afterwards the admin gets a list of users and their random password for the private key
- if the user has set a email address in his personal settings we can send him the random password automatically, if not the admin needs to distribute the passwords somehow
- the next time the user login, they will get a message that their private key password doesn't match the login password and that they can adjust it in the personal settings (same as if the login password was changed on a LDAP server)
- the user can set the private key password to his login password in the personal settings
-> migration finished, the user can access all his files again and all files are encrypted

decrypt:

- if recovery-key is enabled for all users we can decrypt all files with the recovery key password
- if not we can still provide a option to decrypt a specific user files-folder and ask for the users login/key password (could be usable for smaller installations if no recovery key is used).

**Comment by schiesbn** [comment]
encrypt all script: https://github.com/owncloud/core/pull/18423
decrypt all script: https://github.com/owncloud/core/pull/18938

cc @rperezb would be great if you could add it to the test plan for encryption. It is important to test this with the local user backend and with LDAP and with (many) large files. Thanks!

cc @carlaschroder would be great to have this documented for 8.2. Thanks!
