### ISSUE TITLE
Adding comments to right sidebar for files & folders

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#16328]
(pulling some info from meta-data app https://github.com/owncloud/metadata/issues/1)

As an ownCloud user, I want to be able to add a threaded comment to a file and a folder inside ownCloud so that I can have a conversation about the file or the folder within ownCloud.

Acceptance Criteria:
- Comment window appears in right side window
- I can click in the comment window and add a comment to the file
- When I click submit on the comment, it appears at the top of the comment in the window
- Comments are reverse chronological order, and can be scrolled down. A popup can be clicked if there are more than three comments that are worth reading to simplify seeing many comments at once
- The popup has the ability to also add a comment, so the commenter can add the latest while also seeing the long list of other comments
- Comments can be up to 1000 characters in length, but the displayed comment is limited in length to 250 characters. Only when the user clicks the popup window will the full comment be displayed in the window.
- In the files view, when the file or folder is not focused (not clicked on my user) an icon simply shows that a comment(s) has/have been added to the file, only clicking on the file or folder brings up the right side panel can the latest be read.
- Comments sidebar show for each comment the username of who made the comment and when (date and time).
- Max number of comments on a file or folder is limited to a value configured in the admin panel for this app. The behavior if the max # is reached is also configurable (these are only example names):
     - max_comments > 100
     - disable_or_delete_comment_after_max > disable
        - disable means no more comments can be added
        - delete means the oldest comment will be deleted
- Users cannot delete comments they did not make at any time from the file / folder comment view with a little x. 

@jancborchardt input appreciated here to from a design standpoint.

**Comment by jancborchardt** [comment]
First work-in-progress of a sidebar: https://github.com/owncloud/core/pull/16414

**Comment by jancborchardt** [comment]
As mentioned in the work in progress pull request at #16414, it would be good if we can combine the versions and the comments in one timeline. They belong to each other since people will probably make revisions based on comments, and it makes it easily visible if someone acted upon a comment.

If we choose to also add the activity for that file/folder in that sidebar that should also be part of this timeline since it’s the same thing. That is, no separate sections needed for Activity, Versions and Comments.

**Comment by MTRichards** [comment]
Ok, as long as it can be done in a simple, easy to understand timeline...great.  Any screens to take a peek?

**Comment by jancborchardt** [comment]
Yep, I imagined a simple timeline. Will work on mockups!

**Comment by oparoz** [comment]
Please tag each entry with a category (comment, revision, etc.) as most people commenting on pictures will only care about comments while designers will be interested in the whole history, etc.

**Comment by PVince81** [comment]
- [ ] backend support for getting/setting comments (database table, etc)
- [ ] frontend JS classes for getting/setting comments (maybe together we the other things like versions and co)

**Comment by PVince81** [comment]
We might need a new special endpoint on the backend that returns all informations combined (comments, activity, versions)

**Comment by raimund-schluessler** [comment]
In my opinion we also need a separate permission for commenting, which allows a user to comment on a shared file which he might not be allowed to edit. This was suggested in https://github.com/owncloud/tasks/issues/169

**Comment by jancborchardt** [comment]
I would for now combine the ability of viewing and commenting. Otherwise we will be in permission-hell again.

**Comment by jancborchardt** [comment]
Moving the comment functionality to 9.0 as we have 8.2 feature freeze today.

**Comment by karlitschek** [comment]
yes. definitely 9.0

**Comment by PVince81** [comment]
- [ ] support for read/unread comments (to be able to support showing an indicator about new comments on the files list rows, as requested)

**Comment by PVince81** [comment]
- comments in plain text (for now)

**Comment by PVince81** [comment]
- [ ] integrate comments into timeline tab: https://github.com/owncloud/core/issues/20259

**Comment by PVince81** [comment]
- [ ] dav v2 endpoint for comments "http://.../dav/comments/{fileId}/" to retrieve (GET) comments for a given file id.
- [ ] extend file Webdav response with a new property "oc:comment-count" to retrieve the number of comments for that file (optional?)
- [ ] extend file Webdav response with a new property "oc:unread-comment-count" to retrieve the number of comments for that file, which would make it possible to show an indicator (optional?)
- [ ] optional: extend file webdav response to provide a link to the matching "comments" URL (that would be the spirit of Webdav, when linked responses), totally optional but could be nice to have :smile:

**Comment by PVince81** [comment]
If we decide to have the comments manager on storage level (storage specific) instead of global, then we also need to handle cross-storage move/copy to make sure the comments are read from comments manager CA from storage A and moved over to the tag manager CB from storage B.

- [ ] cross-storage move/copy, if applicable

**Comment by DeepDiver1975** [comment]
> If we decide to have the comments manager on storage level (storage specific) instead of global, then we also need to handle cross-storage move/copy to make sure the comments are read from comments manager CA from storage A and moved over to the tag manager CB from storage B.

the current design assumption is (basically the same as with sharing) that this is on home storage only.

**Comment by karlitschek** [comment]
we need a way to 'attach' to all kind of thing not just files. Think about commenting an activitiy in the feed or a tag change, of a calendar event or a status message or a bookmark or something else. 
So comments should always have a two dimensional type. type one says if it is attached to a file, activity, bookmark, contact, ... and type 2 is the correpsonding primary key depending on the type1. So fileid, activity id, bookmark id, contacts id and so on.

**Comment by PVince81** [comment]
Okay, so it's different than with Tags. Sorry, I might have mixed it up with that one (we discussed both recently).

So I assume that comments have nothing to do with the storage API.

**Comment by DeepDiver1975** [comment]
Taking into account our experience with the share api which was initially designed to work for any object and now we are focusing on files only, next steps on tagging and comments are only focusing on files only as well.

We need to consider that any other resource which wants to add tags and comments has a different data storage and a general approach will fail again - from my pov.

**Comment by PVince81** [comment]
- [ ] data structure must be able to support future entitiy/object type (objectid/objecttype)
- [ ] no threading for first version, but data structure must be able to support it in the future

**Comment by PVince81** [comment]
- [ ] future threading to be 1-level deep only => suggestion from @karlitschek, add a "replyCount" column in the table for the main comment entry

**Comment by PVince81** [comment]
- [ ] global CommentsManager that stores comments in the DB, **not** coupled to the storage.
- [ ] Provide a "config.php" option to override it with a custom implementation for CommentsManager globally

**Comment by PVince81** [comment]
@blizzz can you update the subtickets ?

**Comment by PVince81** [comment]
@blizzz note for you, you can have a look at the TagManager for inspiration: https://github.com/owncloud/core/blob/master/lib/private/tagmanager.php and https://github.com/owncloud/core/blob/master/lib/private/tags.php

**Comment by PVince81** [comment]
- [ ] make sure the Webdav endpoint for comments also supports several entity times: "http.//example.com/dav/comments/{{entityType}}/{{entityId}}/"

**Comment by PVince81** [comment]
- [ ] additional column "commentType" or "verb"s string which defaults to "comment" (but in the future could be "like", etc)

**Comment by PVince81** [comment]
- [ ] need to discuss whether to add a "userType" column to distinguish local users from remote users

**Comment by PVince81** [comment]
- [ ] publish activity when a user writes a comment on a file

**Comment by blizzz** [comment]
Manager-related items were not included in subtickets, i created a new one for them: https://github.com/owncloud/core/issues/20409

**Comment by blizzz** [comment]
More questions: what happens with comments, when a file is permanently deleted?

Obvious answer: also delete the comments.

What happens with comments, when a user is deleted?

Options:
1. Keep the Comments: ensures that on shared files with comments the context is not missing. Problem: user id would be flowing around, while it can be given to new users again.
2. Delete the Comments: since everything else of the user is erased just as well.
3. Keep the Comments, remove Actor information: moves the comment to a "special" "Deleted User". The message will still be shown, but the display name will just say "Deleted User".

I vote for 3. @jancborchardt ?

**Comment by MorrisJobke** [comment]
> 3. Keep the Comments, remove Actor information: moves the comment to a "special" "Deleted User". The message will still be shown, but the display name will just say "Deleted User".

I would also do it in that way. Github also has this user - it is called "Ghost" ;)

**Comment by karlitschek** [comment]
i agree. good idea.

**Comment by jancborchardt** [comment]
Same for reddit – they say `[deleted]` as name. So yeah, let’s call it »Deleted user« (lowercase »user«).

**Comment by blizzz** [comment]
Thx guys, updated tasks in description on https://github.com/owncloud/core/issues/20409

**Comment by blizzz** [comment]
@MTRichards 

> Users cannot delete comments they did not make at any time from the file / folder comment view with a little x

I interpret it as you can only delete the  comments you did yourself. correct?

cc @nickvergessen

**Comment by jancborchardt** [comment]
@blizzz yes.

**Comment by MTRichards** [comment]
While duplicative to @jancborchardt , I will still say to @blizzz Correct!

**Comment by jospoortvliet** [comment]
@select you were interested ;-)

**Comment by PVince81** [comment]
- [ ] publish notification ? (when?)

**Comment by nickvergessen** [comment]
activity, not notification

**Comment by PVince81** [comment]
@karlitschek mind posting your thoughts regarding notifications ?
Maybe something to discuss in a separate ticket.

**Comment by nickvergessen** [comment]
maybe on mentioning a notification makes sense, but not in general for any comment...

**Comment by karlitschek** [comment]
We should port notification if something 'interesting' happens. The question now is what is 'interesting' :-)
Definitely on mention as @nickvergessen Can we parse the comments already for all possible usernames? Otherwise maybe a new comment on a shared file that I own is also 'interesting'? Or if there are several comments in a short period of time?
@jancborchardt What do you think?

**Comment by karlitschek** [comment]
We should definitely do some kind of notification in some cases. Otherwise comments might not get noticed by the people.

**Comment by jancborchardt** [comment]
Yeah, definitely on mentions. Then a second setting could be to receive notifications for all files you can see.

For the first, default should be on for both Mail and Web. Second off by default.

**Comment by nickvergessen** [comment]
Notifications have no "mail and web", that's activities...

**Comment by PVince81** [comment]
@jancborchardt @karlitschek please re-read the acceptance criteria https://github.com/owncloud/core/issues/16328#issue-76013209 and tell me what you think about the popup approach. I know that @jancborchardt is against pop ups so might need to adjust the requirements accordingly.

**Comment by PVince81** [comment]
@MTRichards the acceptance criteria doesn't mention editing and deleting comments, or just indirectly.
It probably makes sense to let users edit and delete only their own comments. (pencil/trash icon)

**Comment by karlitschek** [comment]
what do you mean with popup approach?

**Comment by PVince81** [comment]
See @MTRichards's original requirement: https://github.com/owncloud/core/issues/16328#issue-76013209
Basically to post a comment, click on a button and have the "new comment" form inside a popup, and still be able to scroll through comments. I guess instead of a popup we could make the field on top sticky (doesn't scroll with the list)

**Comment by karlitschek** [comment]
ahh ok. i would suggest to do the comment form embedded inline in the sidebar and not doing an actual popup.
what do you think @mtrichards

**Comment by PVince81** [comment]
and it is also said that comments can be clicked to be displayed in a popup. The UI would only show 250 chars, to see the rest, click on the comment to see it in a popup.

But then @jancborchardt's mock up shows the comments on single lines...

**Comment by karlitschek** [comment]
can we show the first x characters of the comment and expand it in the sidebar when clicking a 'more' link/button ? :

**Comment by PVince81** [comment]
> can we show the first x characters of the comment and expand it in the sidebar when clicking a 'more' link/button ? :

Sounds good. Maybe a "..." button or something

**Comment by karlitschek** [comment]
yes :-)

**Comment by MTRichards** [comment]
@karlitschek 
>ahh ok. i would suggest to do the comment form embedded inline in the sidebar and not doing an actual popup.
what do you think @mtrichards

Yes - not trying to be literal, this is ok for me. 

also like the "..." button to expand it.

>>@MTRichards the acceptance criteria doesn't mention editing and deleting comments, or just indirectly.
It probably makes sense to let users edit and delete only their own comments. (pencil/trash icon)
>Users cannot delete comments they did not make at any time from the file / folder comment view with a little x. 

Yes! users should be able to edit / delete comments that they make. I like the pencil trashcan option.

**Comment by PVince81** [comment]
The main ticket was merged: https://github.com/owncloud/core/pull/21961

Here are open tasks to enhance it further:
- [ ] allow owner to edit/delete their own comments
- [ ] implement "mark as read" logic
- [ ] make sure that "deleted user" is handled properly
- [ ] needs upstream patch https://github.com/evert/davclient.js/pull/16
- [ ] show max 3 rows of each comment, add button/link to expand

**Comment by PVince81** [comment]
There are also some remaining backend tasks:
- [ ] backend tasks https://github.com/owncloud/core/issues/20409

**Comment by MorrisJobke** [comment]
Closing this because all is in :dancer:

**Comment by sorglos** [comment]
I'm using this new feature as a file description instead of a meta tag. Very good work and thank you very much for implementing!

Call me blind, but where can I find the setting to limit the number of comments?

**Comment by PVince81** [comment]
@sorglos there is no such setting

**Comment by sorglos** [comment]
@PVince81 Okay, thank you!
