### ISSUE TITLE
Missing  `item_target` on createSelectStatement in lib/private/share/share.php LN 2294

### ISSUE THREAD

**Issue by libasys** [owncloud/core#16329]
But this is needed if you would like to work with OCS API for local share!
I have written a  OCS Share API for calendar and other apps, this apps works all with item_source and item_target, if you share something! But now if you write a OCS Share Api and you would like to know what is the item_target, so you get nothing back, for sure than it is missing on the select statement.
Please add this column on the select statement (https://github.com/owncloud/core/blob/master/lib/private/share/share.php#L2294) 

Thanks

**Comment by PVince81** [comment]
@schiesbn @rullzer

**Comment by PVince81** [comment]
Share code has been reworked in 9.0 and the old share.php is obsolete.

**Comment by rullzer** [comment]
Also note that starting in 9.0 the internal sharing code will only handle files/folders. Calendar and contacts sharing has been moved to webdav. And all other stuff should implement their own sharing in an app.
