### ISSUE TITLE
share link with multiple E-Mail-adresses separated by comma

### ISSUE THREAD

**Issue by davidak** [owncloud/core#1632]

**Comment by MorrisJobke** [comment]
Works with `;`, `,` and ` ` - see https://github.com/owncloud/core/pull/20981

**Comment by davidak** [comment]
Thanks to everyone involved! :)

**Comment by ncsatech** [comment]
Hi I am trying to use this feature to send out a share link to multiple users with all the email addresses in bcc I have tried using , ; and a space but no matter what I do all the addresses are inserted into the to: field and I can see all of the email addresses when the email is received by the end user is this normal?
How can I can get the bcc option to work?

**Comment by RealRancor** [comment]
@ncsatech You can create a new feature request for that
