### ISSUE TITLE
Password Policy for Sharing Dialog

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#16324]
As an ownCloud admin, I want to be able to set password policy for the sharing dialog so that I can ensure that passwords are set, and ensure that the links are appropriately secured with a password of sufficient length.

Acceptance Criteria:
- Admin can set the minimum number of characters for the password
- Admin can set a required number of uppercase letters
- Admin can set a required number of numerals
- Admin can set a required number of special characters
- Admin can detmine which special characters are allowed
- The composite rule for what is required for the password is displayed to the user in a helpful manner when they are entering the 
- Admin sets all this on the admin page under the "require password" sharing checkbox
- No password criteria can also be set if the "require password" option is checked

**Comment by rullzer** [comment]
Yep this makes sense if you want to enforce passwords for public links. However our designers should help with how we want to present this to admins. 

On a somewhat related note it probably would also be good to have an generate password button. Since often it is just copy pasted anyway.

**Comment by cmonteroluque** [comment]
Higher priority

**Comment by DeepDiver1975** [comment]
Basic integration in core is done with https://github.com/owncloud/core/pull/17838 - UX improvments come with https://github.com/owncloud/core/pull/17827

**Comment by DeepDiver1975** [comment]
@jancborchardt as far as I remember you had concerns in putting the password policy into core and have it enabled by default - right?

So the explicit verification including the admin UI will be implemented as an isolated app.

Objections? @karlitschek @cmonteroluque @MTRichards

**Comment by karlitschek** [comment]
Good idea IMHO

**Comment by jancborchardt** [comment]
Yep, isolated app please.

**Comment by MTRichards** [comment]
Me three agreed, an isolated app is good. It enables far more flexibility for policies we can't see now as needed.

**Comment by DeepDiver1975** [comment]
> Me three agreed, an isolated app is good. It enables far more flexibility for policies we can't see now as needed.

community or enterprise :question:

**Comment by MTRichards** [comment]
Enterprise.

**Comment by jancborchardt** [comment]
Good teamwork @DeepDiver1975 :hand:

**Comment by MTRichards** [comment]
We need to be sure that we have an API to comminicate something to the desktop and mobile clients when a password policy is not met, so that they clients and apps can explain it to the user properly.

@rperezb

**Comment by DeepDiver1975** [comment]
the api is already handling this case properly:

```sh
$ curl -u admin http://localhost:8080/ocs/v1.php/apps/files_sharing/api/v1/shares --data "path=welcome.txt&shareType=3&password=1234"
Enter host password for user 'admin':
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>403</statuscode>
  <message>Password is too short. Minimum 8 characters are required.</message>
 </meta>
 <data/>
</ocs>

**Comment by MTRichards** [comment]
Oh great! Thank you. Just making sure, since we had not fully discussed.

**Comment by MTRichards** [comment]
@rperezb Looks like we have what we need here?

**Comment by rperezb** [comment]
thanks @DeepDiver1975, got it!
Probably, @dragotin @danimo will need this too

**Comment by SergioBertolinSG** [comment]
Just to clarify:
'No password criteria can also be set if the "require password" option is checked'

This means that admin user is not allowed to modify password criteria when that checkbox is enabled?
or it means that is not possible at all to set a password policy if "require password" is enabled?

**Comment by MTRichards** [comment]
@SergioBertolinSG That just means that the current behavior (a password required, but no complexity requirements) is still possible with these settings.
