### ISSUE TITLE
Download link in public link page downloads the whole folder

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#16336]
### Steps
1. Create a folder "test"
2. Put two files "test1.txt" and "test2.txt" in it
3. Share "test" with link
4. Open the link
5. In the row of "test1.txt", click on the "Download" link

### Expected result
Only "test1.txt" is downloaded

### Actual result
Zip file of the whole folder is delivered

### Versions
Happens on master (4789e87a5378776738706b48d0db1cf1d989709a)
Works properly on 8.0.3.

Wasn't something similar discovered/fixed recently ? @MorrisJobke @jancborchardt @LukasReschke ?

**Comment by oparoz** [comment]
I can confirm this

**Comment by jancborchardt** [comment]
We had this same bug some time ago. Time to write tests for it folks. :)

**Comment by LukasReschke** [comment]
Tests? You are kidding... It's impossible to write tests for that static part of the code.

That said I will take care of it.

**Comment by LukasReschke** [comment]
Yup. Small men like me cannot completely rewrite the files handling :see_no_evil:

**Comment by LukasReschke** [comment]
Regression has been introduced with https://github.com/owncloud/core/commit/58a87d0babcb91aab75b45e630d2fc2fee15691e by @oparoz, previously it was:
```javascript
return OC.generateUrl('/s/' + token + '/download') + '?' + OC.buildQueryString(params);
```

Which has been changed to:
```javascript
return OC.generateUrl('/s/' + token + '/download', params);
```

When using the `OC.generateUrl` JavaScript method it is important to note that parameters have to be specified manually such as in https://github.com/owncloud/core/blob/10d1fd1306400f61ad219c976557df6e8a431f0e/core/js/jquery.avatar.js#L78-L80

**Comment by LukasReschke** [comment]
PR coming.

**Comment by oparoz** [comment]
Hmm...I don't understand what's the difference between creating the params object beforehand ans creating it from within the call, as highlighted in jquery.avatar.js

**Comment by oparoz** [comment]
I've been enlightened, the parameters have to be specified in the URL as the method has not been designed to automagically add them.

**Comment by PVince81** [comment]
@oparoz here comes your enlightenment :high_brightness:

**Comment by oparoz** [comment]
:dancers:

**Comment by LukasReschke** [comment]
Sorry @oparoz that I couldn't reply on this. Had to catch my bus as I'm travelling atm. But glad you got enlightened :smile: 

That said, confusing method… Yes…

**Comment by oparoz** [comment]
No worries :ok_hand: I just had forgotten how that method works. It gets confusing when you write your own. You assume the others work like yours.
