### ISSUE TITLE
Impossible to update from 8.0.2 to 8.0.3 on Ubuntu

### ISSUE THREAD

**Issue by etiess** [owncloud/core#16330]
Hello,

I'm unable to update my OC installation from 8.0.2 to 8.0.3 on Ubuntu 15.04. The command 'apt-get install owncloud' gives this result:

Les paquets suivants contiennent des dépendances non satisfaites :
 owncloud : Dépend: owncloud-server (= 8.0.3-2) mais 8.0.2-4 devra être installé
            Dépend: owncloud-config-apache (= 8.0.3-2) mais 8.0.2-4 devra être installé
E: Impossible de corriger les problèmes, des paquets défectueux sont en mode « garder en l'état ».

Translation:
Following packages have dependencies unsatisfied:
owncloud: depend owncloud-server (= 8.0.3-2) but 8.0.2-4 will have to be installed
Depend: owncloud-config-apache (= 8.0.3-2) but 8.0.2-4 will have to be installed
E: Impossible to correct the problems, deffective packages are in mode "keep in state"

I don't know if this issue is related to https://github.com/owncloud/core/issues/16007 or https://github.com/owncloud/core/issues/16188

My config:
Ubuntu 15.04
3.19.0-16-generic
Server version: Apache/2.4.10 (Ubuntu)
PHP 5.6.4-4ubuntu6 (cli) (built: Apr 17 2015 15:47:51)
mysql  Ver 14.14 Distrib 5.6.24, for debian-linux-gnu (x86_64) using  EditLine wrapper

cc @jnweiger

**Comment by karlitschek** [comment]
@jnweiger. Do you know what the problem here is?

**Comment by etiess** [comment]
@jnweiger Any update on this one? Thank you!

**Comment by etiess** [comment]
For information, the command "sudo apt-cache policy owncloud" gives this result:

owncloud:
  Installed : 8.0.2-8
  Candidate : 8.0.3-2
 Version table:
     8.0.3-2 0
        500 http://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_15.04/  Packages
 *** 8.0.2-8 0
        100 /var/lib/dpkg/status

**Comment by etiess** [comment]
@jnweiger No news? It's still impossible to update.

**Comment by etiess** [comment]
@Kawohl Hello, and thank you!
If you need any detail or test, don't hesitate to ask me!

**Comment by Kawohl** [comment]
Hey @etiess,

i was not able to reproduce this behaviour. Also Ubuntu 15.04


This worked for me: 
I installed owncloud 8.0.2-7.

apt-get update
apt-get install owncloud

Can you please check which build of Owncloud 8.0.2 you have?
Thanks John

**Comment by etiess** [comment]
The commands you indicate are the ones I used (apt-get update and apt-get install owncloud).

**Comment by jnweiger** [comment]
@etiess maybe you need to run apt-get -f install
I learned that sometimes apt-get does not resolve dependencies automatically and wants a human to type that additional command instead.

**Comment by etiess** [comment]
@jnweiger same result :(

**Comment by etiess** [comment]
@Kawohl Were you able to reproduce it on 8.0.2.8 ?

**Comment by Kawohl** [comment]
Not yet, i should get to this this afternoon.

**Comment by Kawohl** [comment]
@etiess 
I´m waiting to get the 8.0.2.8 buildt since it is not on our repository server anymore.

@jnweiger will do a reverse engineered build so i can test the setup. I´ll notify you as soon as we get to it..sorry

**Comment by jnweiger** [comment]
https://build.opensuse.org/package/show/home:jnweiger:branches:isv:ownCloud:community:8.0/owncloud
has 8.0.2-8 now.

**Comment by Kawohl** [comment]
@etiess 
 I am sorry to disappoint you but i couldn't reproduce the error on my machine. I had the same Specs as you and the update went well.

**Comment by etiess** [comment]
Thank you to have tested it: do you need me to perform some test? Or do you want an access on my server?

**Comment by Soupala** [comment]
I'm having similar issue, Ubuntu 14.04.  Not sure what to do.  See terminal output below:

---------------------------------------------------------------------------

You might want to run 'apt-get -f install' to correct these.
The following packages have unmet dependencies:
 owncloud : Depends: owncloud-server (= 8.0.3-2) but 8.0.2-5 is installed
 owncloud-3rdparty : Depends: owncloud-server (= 8.0.3-2) but 8.0.2-5 is installed
 owncloud-app-activity : Depends: owncloud-server (= 8.0.3-2) but 8.0.2-5 is installed
 owncloud-app-external : Depends: owncloud-server (= 8.0.3-2) but 8.0.2-5 is installed
 owncloud-app-files : Depends: owncloud-server (= 8.0.3-2) but 8.0.2-5 is installed
 owncloud-app-files-encryption : Depends: owncloud-server (= 8.0.3-2) but 8.0.2-5 is installed
 owncloud-app-files-external : Depends: owncloud-server (= 8.0.3-2) but 8.0.2-5 is installed
 owncloud-app-files-locking : Depends: owncloud-server (= 8.0.3-2) but 8.0.2-5 is installed
 owncloud-app-files-pdfviewer : Depends: owncloud-server (= 8.0.3-2) but 8.0.2-5 is installed
 owncloud-app-files-sharing : Depends: owncloud-server (= 8.0.3-2) but 8.0.2-5 is installed
 owncloud-app-files-texteditor : Depends: owncloud-server (= 8.0.3-2) but 8.0.2-5 is installed
 owncloud-app-files-trashbin : Depends: owncloud-server (= 8.0.3-2) but 8.0.2-5 is installed
 owncloud-app-files-versions : Depends: owncloud-server (= 8.0.3-2) but 8.0.2-5 is installed
 owncloud-app-files-videoviewer : Depends: owncloud-server (= 8.0.3-2) but 8.0.2-5 is installed
 owncloud-app-firstrunwizard : Depends: owncloud-server (= 8.0.3-2) but 8.0.2-5 is installed
 owncloud-app-gallery : Depends: owncloud-server (= 8.0.3-2) but 8.0.2-5 is installed
 owncloud-app-provisioning-api : Depends: owncloud-server (= 8.0.3-2) but 8.0.2-5 is installed
 owncloud-app-templateeditor : Depends: owncloud-server (= 8.0.3-2) but 8.0.2-5 is installed
 owncloud-app-user-external : Depends: owncloud-server (= 8.0.3-2) but 8.0.2-5 is installed
 owncloud-app-user-ldap : Depends: owncloud-server (= 8.0.3-2) but 8.0.2-5 is installed
 owncloud-app-user-webdavauth : Depends: owncloud-server (= 8.0.3-2) but 8.0.2-5 is installed
 owncloud-config-apache : Depends: owncloud-server (= 8.0.3-2) but 8.0.2-5 is installed
E: Unmet dependencies. Try using -f.

------------------------------------------

root@NFPOwnCloud:/usr/bin# apt-get -f install
Reading package lists... Done
Building dependency tree
Reading state information... Done
Correcting dependencies... Done
The following extra packages will be installed:
  owncloud-server
Suggested packages:
  php5-apcu php-apc
The following packages will be upgraded:
  owncloud-server
1 upgraded, 0 newly installed, 0 to remove and 84 not upgraded.
22 not fully installed or removed.
Need to get 0 B/11.1 MB of archives.
After this operation, 16.4 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
(Reading database ... 100678 files and directories currently installed.)
Preparing to unpack .../owncloud-server_8.0.3-2_all.deb ...
Unpacking owncloud-server (8.0.3-2) over (8.0.2-5) ...
dpkg: error processing archive /var/cache/apt/archives/owncloud-server_8.0.3-2_all.deb (--unpack):
 trying to overwrite '/var/www/owncloud/.htaccess', which is also in package owncloud-config-apache 8.0.3-2
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/owncloud-server_8.0.3-2_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by Soupala** [comment]
Ah.  For anyone else running across this issue, here's what fixed it for me

dpkg -r --force-depends "owncloud-config-apache"
apt-get -f install

**Comment by Kawohl** [comment]
@etiess did @Soupala 's workaround help you?

**Comment by etiess** [comment]
Actually, I uninstalled it and reinstalled it. And it worked.
