### ISSUE TITLE
Public link page layout height is wrong

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#16335]
Observed on master (4789e87a5378776738706b48d0db1cf1d989709a) when sharing an empty folder with public link:

![publiclinklayout](https://cloud.githubusercontent.com/assets/277525/7615343/7001edbe-f99d-11e4-956c-47ed5a12d2d6.png)

I'm pretty sure this worked a few weeks ago when I brought back the "No files here" message.

So: regression

@owncloud/designers or anyone who fancies a bisect ?

**Comment by oparoz** [comment]
Might come from this:
https://github.com/oparoz/core/commit/8d3f88cf16f86212861db996023dadf1fb3e310f#diff-b145bf1a735fa4639d561f4352a0b45fL5

If that's the case, then the empty folder div needs to define its own height, like previews do.

**Comment by PVince81** [comment]
Not sure if it's the empty content div, it might be the list container too that is missing a min-height.

**Comment by oparoz** [comment]
I've just tried and if you add the min-height to the CSS of preview it works.

The problem is that empty-content is absolutely positioned.

**Comment by jancborchardt** [comment]
@oparoz so can you open a pull request to fix this? :)

**Comment by oparoz** [comment]
@jancborchardt - I can try, but I don't know much about OC's css, so I could make it worse (The C in CSS)... One solution might be to write some JS for it... Thoughts?

**Comment by PVince81** [comment]
It looks like you removed the min-height here: https://github.com/oparoz/core/commit/8d3f88cf16f86212861db996023dadf1fb3e310f#diff-b145bf1a735fa4639d561f4352a0b45fL5

In general I don't like the fact that the file list is inside of "#preview", but that's inherited from legacy stuff. To be cleant up one day with likely side effects.

It might be possible to move the min-height to the file list container instead.

**Comment by oparoz** [comment]
I don't think it affects the files list. It's only for single file previews.

I'm going to test if re-introducing a min-height of 200px works in all cases

**Comment by PVince81** [comment]
Thanks @oparoz
