### ISSUE TITLE
Preview does not update after overwrite

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#16338]
### Steps
1. Upload a file "test.txt" in the web UI
2. Wait for the preview to appear
3. Change the file locally then upload it again, select "New files" in the overwrite dialog

### Expected result
Preview is updated

### Actual result
The preview blinks once as if it is being reloaded, but still shows the old contents.

### Versions
ownCloud 8.1 master (4789e87a5378776738706b48d0db1cf1d989709a)
Works properly on 8.0.3 => regression

Any idea @oparoz @georgehrke ?
A bisect could help.

**Comment by georgehrke** [comment]
@icewind1991 Did some file hooks change?

**Comment by PVince81** [comment]
Note: the WebDAV PUT is missing some hooks calls: https://github.com/owncloud/core/pull/16292
But this also happens with web UI upload, so not sure

**Comment by oparoz** [comment]
I know this happened recently, but it seems OK
https://github.com/owncloud/core/pull/16099/files

**Comment by georgehrke** [comment]
No, it doesn't ^^
the default should be true and not false

**Comment by georgehrke** [comment]
will send a pull request

**Comment by oparoz** [comment]
Ah :)

**Comment by georgehrke** [comment]
fix is here: https://github.com/owncloud/core/pull/16342
