### ISSUE TITLE
Public sharing view of a PDF: double scrollbar

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#16331]
When sharing a PDF, the PDF.js container extends below the viewport which results in a double scrollbar. One from PDF.js and one from us:
![owncloud shared pdf double scrollbar](https://cloud.githubusercontent.com/assets/925062/7614243/d42133ca-f995-11e4-99b9-f58fba038523.png)
We should make sure the PDF.js container is only as high as the viewport _minus_ the header height to remove our scrollbar.

cc @tomneedham @owncloud/designers

**Comment by LukasReschke** [comment]
Should get tracked at https://github.com/owncloud/files_pdfviewer

**Comment by jancborchardt** [comment]
Right. New issue at https://github.com/owncloud/files_pdfviewer/issues/56
