### ISSUE TITLE
[IE9] Password is visible for just for 'one tenth of second' if you paste it using IE9

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16349]
### Steps to reproduce
1. Go to 'log in' page
2. Paste your Password

### Expected behaviour

The pwd should be pasted since first as periods

### Actual behaviour
The password is shown for 'one tenth of second' . This only happens in Internet Explorer.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** "version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by davitol** [comment]
@LukasReschke ?

**Comment by LukasReschke** [comment]
As discussed with @jnfrmarks yesterday:
```
14:21:06 <jennifer> can you look at https://github.com/owncloud/core/issues/16349
14:21:24 <jennifer> shojuld this be pulled down?
14:22:41 <lukas> It’s fine there. Though it works quite fine for me in IE 11 (probably a browsr bug as well)
14:22:51 <lukas> would be awesome if in case of IE we would also know the version
14:23:11 <jennifer> ok; I'll ask them to update the issue
```

**Comment by davitol** [comment]
@LukasReschke it is reproduce Internet Explorer 9.0.8112.16421 
In IE11 110.0.9600 the bug does not happen

**Comment by PVince81** [comment]
Possibly the placeholder shim or something.
We use a workaround for IE8/IE9 to be able to show a placeholder there in IE. The code from the placeholder (which is an external library) has a delay and is not able to detect password pasting fast enough.

I suggest we remove the placeholder an use regular labels. Will look ugly but better than nothing...

**Comment by jnfrmarks** [comment]
@LukasReschke 

What info are you looking for?

**Comment by LukasReschke** [comment]
The one provided in https://github.com/owncloud/core/issues/16349#issuecomment-102340475, should probably have removed the label afterwards ;)

**Comment by PVince81** [comment]
Maybe we should just use the IE8 workarounds also for IE9.
It seems IE9 has too many issues with placeholder + password fields and it's pointless to spend days to try and make them work.

**Comment by PVince81** [comment]
The placeholders library we are using is detecting field changes every 100 ms, see https://github.com/owncloud/core/blob/master/core/js/placeholders.js#L406

Here are the options:
1) Update the placeholders library => didn't fix the issue when I tried
2) Switch to another library: might be too much work and not worth the effort, especially that some do not detect changes automatically but require you to call `$el.placeholder()` on every field to activate its functionality. This means we'd need to manually add this code everywhere for every field.
3) Disable the placeholder library: in this case the password field is empty and the user might be confused
4) Same as 3) but add real labels like "User" and "Password". @jancborchardt might not like it and it's also more work (CSS alignment, etc) and might not be worth the hassle

My suggestion is won't fix as it's not critical enough.

Objections ?

**Comment by jancborchardt** [comment]
@PVince81 yeah, I’d say it’s not worth the hassle to be honest.
