### ISSUE TITLE
exclude hidden files from search results

### ISSUE THREAD

**Issue by chrisjscott** [owncloud/core#16345]
It's be great if there was a way to hide hidden files (those whose name begin with a period) from the search results of external storage sources (Samba, for example).

Looks like someone got part of the way there: https://forum.owncloud.org/viewtopic.php?f=31&t=26362&p=87165

Also appears that this request has been kicking around already (but was closed): https://github.com/owncloud/core/pull/13711

Any possibility of incorporating wildcards into the array specified?

**Comment by PVince81** [comment]
It was reopened here: https://github.com/owncloud/core/issues/2589

If hidden files are kept hidden as per the toggle, then the search code should also hide them, so keeping your ticket open for that.
