### ISSUE TITLE
Exclude groups from sharing stops working when user is a member of multiple groups

### ISSUE THREAD

**Issue by BloodyIron** [owncloud/core#16346]
I want to make a group to grant/deny sharing at my will.

The problem I have is, when a user is a member of ONLY that group it works, but when I add them to another group that isn't excluded from sharing, that user can share again.

I've observed this issue since before v8.x

I am currently on 8.0.3.4

**Comment by karlitschek** [comment]
can you post a full bug report using this template please? https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by nickvergessen** [comment]
This is the intended behaviour:
```php
				$remainingGroups = array_diff($usersGroups, $excludedGroups);
				// if the user is only in groups which are disabled for sharing then
				// sharing is also disabled for the user
				if (empty($remainingGroups)) {
					return true;
				}
```

But I agree that this comment should be part of the interface, as that indicates a different behaviour:
![bildschirmfoto vom 2015-05-15 11 27 59](https://cloud.githubusercontent.com/assets/213943/7650335/84dc52b6-faf5-11e4-89dd-c215def169be.png)

**Comment by BloodyIron** [comment]
@nickvergessen 

I want a way to block a user and/or those who are members of a specific group, from being able to share at all. Check reproduction steps.

@karlitschek 

I know it's not desirable, but in this case this is not something specific to my setup. It's been happening since v7, and is happening at 8.0.3.4 too. I'm not going to fill out the full template.

Reproduce:
1) Set group "noshare" (example) under "Exclude groups from sharing".
2) Add user to only group "noshare". Now they cannot share files/folders.
3) Add same user to a secondary group, any group, and now they CAN share files/folders.

It's just that easy. Running on Apache.

**Comment by rullzer** [comment]
Like @nickvergessen mentions this is the intended behaviour at the moment. 

Extending this setting with a checkbox to force this behaviour should be doable. I can have a look at that for 8.2.

**Comment by BloodyIron** [comment]
@rullzer 

Well, I opened it as a bug since the description and documentation didn't match the behavior. But that's semantics and history now.

I for one would greatly appreciate your help on this. Having granular control in such a way that serves me to control who can and cannot share based on group membership would be quite helpful.

**Comment by nickvergessen** [comment]
@BloodyIron for now you can change it yourself.
`lib/private/util.php`:
find
```php
			if (!empty($usersGroups)) {
				$remainingGroups = array_diff($usersGroups, $excludedGroups);
				// if the user is only in groups which are disabled for sharing then
				// sharing is also disabled for the user
				if (empty($remainingGroups)) {
					return true;
				}
			}
```
replace with
```php
			if (!empty($usersGroups)) {
				// if the user is in at least one group which are disabled for sharing then
				// sharing is also disabled for the user
				$usersExcludedGroups = array_intersect($usersGroups, $excludedGroups);
				if (!empty($usersExcludedGroups)) {
					return true;
				}
			}
```

**Comment by PVince81** [comment]
@rullzer @nickvergessen any update ?

**Comment by rullzer** [comment]
Ah mm forgot about this. We should probably get some designers involved on how to make this happen. In a way that does not confuse the users to much.

But 9.0 for sure.

**Comment by davitol** [comment]
Another situation:
Using an Active Directory with nested groups allowed. User belongs to group1 and this group is included in group2 (nested). If group2 is added to 'Exclude groups from sharing', the user should not be able to share files, even if group1 is not included in the forbidden groups specifically

**Comment by nickvergessen** [comment]
As per above this is currently the expected behaviour:
```php
                // if the user is only in groups which are disabled for sharing then
                // sharing is also disabled for the user
```

**Comment by PVince81** [comment]
@jesmrec see above, I remember you asked me this on IRC

**Comment by BloodyIron** [comment]
I don't know why this ticket was closed, just because that's the functionality as it is now, does not mean I'm not requesting such functionality.

I need to have a way to prevent people from sharing, but still be members of other groups, and have the "not allowed to share" element retained.

Consider this:

1. We have a secretary who needs access to files, but doesn't need to share them. Their access is delegated through a group, for specific files and folders, and they are a member of the "noshare" group. In this scenario, with how it is now, they would still be able to share the files, which could constitute a security risk. What we would need is the "noshare" group to completely revoke sharing functionality, despite this person being a member of other groups.
2. We have a department head who needs access to those files, but is trusted and does need to be able to share those files. Naturally, member of the same group as the Secretary, except not a member of "noshare". The expected behaviour is they should be able to share the files, and they can.

This is a potential security risk in its current form. Forcing it so that every group a person is a member of has to have sharing disabled is asinine and drastically increases administrative overhead. As it is now each set of access requires two groups, one for sharing one for not sharing.

This would be worlds simpler if, just like many ACLs out there, denies happen before allows, and take precedence.

**Comment by PVince81** [comment]
@BloodyIron the ticket was not closed and is still open as enhancement request

**Comment by PVince81** [comment]
@pmaier1 for some ideas around "exclude groups from sharing"

**Comment by BloodyIron** [comment]
So, what's going on with this? :/

2 years, and I thought it was going into 9.2?

**Comment by tomneedham** [comment]
@BloodyIron We are taking another look at this as it appears to not work as most people expect it - in fact, it is less restrictive than it perhaps should be.

**Comment by BloodyIron** [comment]
@tomneedham I'm interested in getting more granular permission control with things like this. So I hope a more flexible and granular method can be found! :D

**Comment by tomneedham** [comment]
@BloodyIron see https://github.com/owncloud/core/pull/31490

**Comment by phil-davis** [comment]
And backport PR #31737 merged to ``stable10`` -- so this behavior should be in the next release.

**Comment by BloodyIron** [comment]
Excellent! :D
