### ISSUE TITLE
Recover of file in a shared folder as recipient from trashbin with encryption enabled removes the content of the file.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16350]
### Steps to reproduce

1. Enable encryption app.
2. Enable encryption module in admin page.
3. Relogin.
4. Create user1.
5. As admin, share a folder "sub" with "user1"
6. Login as user1. (Relogin if needed).
7. Upload a text file "test.txt" with content in "sub" folder
8. Remove "sub/test.txt".
9. Restore "test.txt" from the trashbin.
10. Open the file.

### Expected behaviour
File can be opened an text is still readable.

### Actual behaviour
Content of the file is gone. File restored is empty.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition.
Encryption.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
Yes

**Logs**
```
```

### Client configuration

**browser**
Chrome 41, Firefox

**Comment by SergioBertolinSG** [comment]
Probably related with this closed issue: https://github.com/owncloud/core/issues/15640

**Comment by PVince81** [comment]
Hmm, but that one was fixed a while ago. So, broken again ?

**Comment by schiesbn** [comment]
@SergioBertolinSG The pull request above should fix it. Can you try the pr and report back if it works for you? Thanks!
