### ISSUE TITLE
Cannot share a file from a SMB storage with encryption enabled

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#16358]
### Steps to reproduce
1. Install and enable external storage and encryption apps.
2. Make sure you have the encryption keys active for userA (the current one) and userB (another user)
3. Configure a SMB mount correctly
4. Upload a file to the SMB mount (checked with small file to bypass https://github.com/owncloud/core/issues/16356)
5. Share the file with userB

### Expected behaviour
UserB can download the file correctly

### Actual behaviour
UserB downloads a corrupted file

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 beta 1

**Updated from an older ownCloud or fresh install:** fresh install

**List of activated apps:**
 - encryption: 1.0.0
 - files: 1.1.9
 - files_external: 0.2.3
 - files_sharing: 0.6.1
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5

### Notes
Checked also with and without files_locking enabled with the same result.

**Comment by LukasReschke** [comment]
cc @schiesbn Encryption related

**Comment by schiesbn** [comment]
The pull request above should fix it, please test it and report back. Thanks!

**Comment by jvillafanez** [comment]
I think it didn't work the first time, maybe due to the state it was left. After that it worked fine and I couldn't reproduce the bug :+1:

**Comment by jvillafanez** [comment]
It's no longer working in master branch f0e7ae5da803b4fc77f362b70e86b27e9b77f001

```
{"reqId":"Y0DBWO\/wXulKtanNVRD0","remoteAddr":"10.40.30.21","app":"no app in context","message":"Can not decrypt this file,\n\t\t\tprobably this is a shared file.\n\t\t\tPlease ask the file owner to reshare the file with you.","level":3,"time":"2015-05-19T07:24:10+00:00"}
{"reqId":"Y0DBWO\/wXulKtanNVRD0","remoteAddr":"10.40.30.21","app":"index","message":"Exception: {\"Exception\":\"OC\\\\Encryption\\\\Exceptions\\\\DecryptionFailedException\",\"Message\":\"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(430): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt('zSskGk9HnoTufZd...')\\n#1 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(278): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#2 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#3 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/files\\\/view.php(810): file_put_contents('\\\/tmp\\\/oc_tmp_ptx...', Resource id #41)\\n#4 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/preview\\\/image.php(50): OC\\\\Files\\\\View->toTmpFile('\\\/88888888.jpg')\\n#5 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/preview.php(798): OC\\\\Preview\\\\Image->getThumbnail('\\\/88888888.jpg', 2048, 2048, false, Object(OC\\\\Files\\\\View))\\n#6 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/preview.php(521): OC\\\\Preview->generatePreview(42200)\\n#7 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/preview.php(544): OC\\\\Preview->getPreview()\\n#8 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/core\\\/ajax\\\/preview.php(61): OC\\\\Preview->showPreview()\\n#9 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/route\\\/route.php(153) : runtime-created function(1): require_once('\\\/home\\\/jvillafan...')\\n#10 [internal function]: __lambda_func(Array)\\n#11 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/private\\\/route\\\/router.php(272): call_user_func('?lambda_1687', Array)\\n#12 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/lib\\\/base.php(862): OC\\\\Route\\\\Router->match('\\\/core\\\/preview.p...')\\n#13 \\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/index.php(40): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/home\\\/jvillafanez\\\/src\\\/owncloud\\\/owncloud2\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/encryption.php\",\"Line\":287}","level":4,"time":"2015-05-19T07:24:10+00:00"}
```

**Comment by schiesbn** [comment]
@jvillafanez I can't reproduce it. Are you sure that the share recipient had a valid public/private key while sharing the file. The error message indicate that this was not the case.

**Comment by jvillafanez** [comment]
The keys were generated for version 8.1 beta 1. I think they should be valid for the version in the master branch. I've also checked that sharing is working for other external storages such as dropbox with the same users.

**Comment by jvillafanez** [comment]
I've uploaded a file to an Amazon S3 storage, and shared it with a user without the encryption keys active. An error is thrown (as expected) after trying to download the file from the "target" user. I've logout and login to generate the keys but I can't still download the file from the "target" user

In addition, I've shared another file with the same user. The file was uploaded before the keys for the "target" user where generated, and shared with him after generating his keys, so the file should download, but that isn't the case.

**Comment by schiesbn** [comment]
> I've uploaded a file to an Amazon S3 storage, and shared it with a user without the encryption keys active. An error is thrown (as expected) after trying to download the file from the "target" user. I've logout and login to generate the keys but I can't still download the file from the "target" user

That's as expected. The owner needs to reshare the file after the target user has created his keys. That's also what the error message tells you.

> In addition, I've shared another file with the same user. The file was uploaded before the keys for the "target" user where generated, and shared with him after generating his keys, so the file should download, but that isn't the case.

In this case the download should work. It works for me with Samba.

**Comment by jvillafanez** [comment]
@schiesbn anything I can check to verify that everything is properly setup? I'm out of ideas

**Comment by jvillafanez** [comment]
I'm starting to think that I have a big mess regarding the sharing. I have a set of files in different storages, some of them shared with the same user. I guess that one of those "conflictive" files is shared from several sources, and the sharing app chooses the wrong source

**Comment by jvillafanez** [comment]
I cannot reproduce the issue now. I've checked with different external storages active at the same time. I think the issue could be due to several storages (specially SMB one) pointing to the same server, with and without encryption. After cleaning the storages list a bit I haven't been able to reproduce the issue, so closing for now.
