### ISSUE TITLE
OC 8.1: Add note when accessing remote.php/webdav

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#16359]
In OC 8.1 the SabreDAV browser on remote.php was removed. As this will causing confusion when users are not reading the release notes (which is often the case) please add a short note on this page like discussed in https://github.com/owncloud/core/issues/15648

**Comment by LukasReschke** [comment]
https://github.com/owncloud/core/pull/16364 has implemented this change set now. Testing welcome :smile:
