### ISSUE TITLE
Updated files messages loop

### ISSUE THREAD

**Issue by fbassas** [owncloud/core#16353]
Environment: Virtual machine on Xenserver
Server: ubuntu 14.04
Database:mysql 5.5
Client:1.8
OC-Version:8.0.2
PHP-Version:5.5.9

Hi,
my owncloud clients are showing every minute a message like "Shared and 19 files have been updated", on an on.
I have restarted client, server, made a occ files:scan, but it is the same.

Relevant log entries in owncloud.log:

{"reqId":"d00bfb3feb32b9dba48b71b46d33022e","remoteAddr":"147.83.182.24","app":"PHP","message":"Undefined index: by_file at \/var\/www\/owncloud\/apps\/files_versions\/lib\/storage.php#533","level":3,"time":"2015-05-14T09:01:01+00:00"}

{"reqId":"d00bfb3feb32b9dba48b71b46d33022e","remoteAddr":"147.83.182.24","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/owncloud\/apps\/files_versions\/lib\/storage.php#533","level":3,"time":"2015-05-14T09:01:01+00:00"}

{"reqId":"d00bfb3feb32b9dba48b71b46d33022e","remoteAddr":"147.83.182.24","app":"PHP","message":"ksort() expects parameter 1 to be array, null given at \/var\/www\/owncloud\/apps\/files_versions\/lib\/storage.php#556","level":3,"time":"2015-05-14T09:01:01+00:00"}

{"reqId":"b10015365c76c84aa4810eba073fae72","remoteAddr":"147.83.107.170","app":"PHP","message":"reset() expects parameter 1 to be array, null given at \/var\/www\/owncloud\/apps\/files_versions\/lib\/storage.php#557","level":3,"time":"2015-05-14T09:15:47+00:00"}

{"reqId":"c043d77f25cce5a3d7aceb4fece243ad","remoteAddr":"147.83.107.170","app":"PHP","message":"Undefined index: all at \/var\/www\/owncloud\/apps\/files_versions\/lib\/storage.php#531","level":3,"time":"2015-05-14T09:12:44+00:00"}

Thanks for your help

**Comment by karlitschek** [comment]
@icewind1991 Do you know what is broken here?

**Comment by fbassas** [comment]
I have disabled/enabled files_versions app, and the error messages have vanished.
So perhaps the issue was related to update from previos releases.
Thanks, and I am going to close this issue.

**Comment by fbassas** [comment]
Sorry, messages about "files_versions" and loop of desktop client messages "Shared and 19 files have been updated" go on.

These are the last ones:

{"reqId":"aa783ea8583e97f0db038a2399908efd","remoteAddr":"147.83.94.52","app":"PHP","message":"An exception occurred while executing 'SELECT `fileid` FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ?' with params [\"3074\", \"0fea6a13c52b4d4725368f24b045ca84\"]:\n\nSQLSTATE[HY000]: General error: 2006 MySQL server has gone away at \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php#115","level":3,"time":"2015-05-19T09:26:45+00:00"}
{"reqId":"a6476a4b9d57786ce23fdc9ea8a15cbd","remoteAddr":"147.83.94.52","app":"PHP","message":"An exception occurred while executing 'SELECT `fileid` FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ?' with params [\"3074\", \"0fea6a13c52b4d4725368f24b045ca84\"]:\n\nSQLSTATE[HY000]: General error: 2006 MySQL server has gone away at \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php#115","level":3,"time":"2015-05-19T09:26:45+00:00"}
{"reqId":"934117704f083df795bebbf482f590c9","remoteAddr":"147.83.107.170","app":"PHP","message":"Undefined index: all at \/var\/www\/owncloud\/apps\/files_versions\/lib\/storage.php#531","level":3,"time":"2015-05-19T09:27:54+00:00"}
{"reqId":"934117704f083df795bebbf482f590c9","remoteAddr":"147.83.107.170","app":"PHP","message":"Undefined index: by_file at \/var\/www\/owncloud\/apps\/files_versions\/lib\/storage.php#533","level":3,"time":"2015-05-19T09:27:54+00:00"}
{"reqId":"934117704f083df795bebbf482f590c9","remoteAddr":"147.83.107.170","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/owncloud\/apps\/files_versions\/lib\/storage.php#533","level":3,"time":"2015-05-19T09:27:54+00:00"}
{"reqId":"934117704f083df795bebbf482f590c9","remoteAddr":"147.83.107.170","app":"PHP","message":"ksort() expects parameter 1 to be array, null given at \/var\/www\/owncloud\/apps\/files_versions\/lib\/storage.php#556","level":3,"time":"2015-05-19T09:27:54+00:00"}
{"reqId":"934117704f083df795bebbf482f590c9","remoteAddr":"147.83.107.170","app":"PHP","message":"reset() expects parameter 1 to be array, null given at \/var\/www\/owncloud\/apps\/files_versions\/lib\/storage.php#557","level":3,"time":"2015-05-19T09:27:54+00:00"}

**Comment by cmonteroluque** [comment]
Performance improvements with 8.1. Please upgrade
