### ISSUE TITLE
No message in log file when antivirus is run as executable

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#16363]
### Steps to reproduce

1. Install 8.1 
2. Enable antivirus app
3. Enable all logging
4. Navigate to admin page and configure antivirus app to use executable.
5. upload a file

### Expected behaviour

There is a message in the server log file that the file was scanned

### Actual behaviour

There isn't a message in the server log file that the file was scanned.  I can see that the clamd process was started by the webserver user on file upload so I know it's being run.

If I change the antivirus configuration to daemon (socket) then there are messages in the log file.

### Server 1 Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration:

ownCloud Enterprise Edition 8.1 beta 1 (daily) Build:2015-05-13T03:08:44+00:00 b626de0b9f135e2993496a8d18f3200dfab72337

**Comment by jnfrmarks** [comment]
Marking as sev-3 because without the message, I'm not 100% sure the file is being scanned.

**Comment by LukasReschke** [comment]
Should probably go to https://github.com/owncloud/files_antivirus?

**Comment by DeepDiver1975** [comment]
Yes - antivirus repo please

**Comment by jnfrmarks** [comment]
Done: https://github.com/owncloud/files_antivirus/issues/44

Note: not all the same labels are in the files_antivirus repo, specifically there are not severity labels.
