### ISSUE TITLE
upgrading to 8.0.3

### ISSUE THREAD

**Issue by besterlabs** [owncloud/core#16361]
After upgrading to 8.0.3 on my hosting service, my owncloud sign in page only shows an option to upgrade to 8.0.3, even though it has been updated. No option to sign in at all. When I then click on update, it gives this error message.
An exception occurred while executing 'CREATE TABLE oc_ownc_appconfig_p97r2x374bv61 (`appid` VARCHAR(32) DEFAULT '' NOT NULL, `configkey` VARCHAR(64) DEFAULT '' NOT NULL, `configvalue` LONGTEXT DEFAULT NULL, INDEX oc_eurk1p785k4wg (`configkey`), INDEX oc_iqd00ugcnalmx (`appid`), PRIMARY KEY(`appid`, `configkey`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_ownc_appconfig_p97r2x374bv61' already exists

Restoring to 8.0.2 allows me to sign in again.

Hope this helps
Cheers

**Comment by LukasReschke** [comment]
Thanks a lot for reporting issues back to us!

We need some more information to properly support you with your issue!

Can I ask you to follow our guidelines for submitting bugs as described here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by RealRancor** [comment]
Looks to me like a dup of https://github.com/owncloud/core/issues/14916
