### ISSUE TITLE
password change not userfriendly

### ISSUE THREAD

**Issue by antigreen** [owncloud/core#16360]
Hi,
first I like owncloud! - great piece of work! ^_^
But I have one small issue:
changing the password in the owncloud admin page is not userfriendly. If you don't press "return" or "enter" after entering the pwd, it won't be accepted, but the entry field looks the same as before entering the pwd.
From my perspective a feedbeck would be great, like an info "password was changed".
Thanks and bye
antigreen

**Comment by nickvergessen** [comment]
related: https://github.com/owncloud/core/pull/15750

@MorrisJobke want to take on?

**Comment by MorrisJobke** [comment]
The solution for this should be something like #15750

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/issues/25532 which also contains a fix.
