### ISSUE TITLE
Third-party apps auto update / "app-store"

### ISSUE THREAD

**Issue by Dark-Fenix** [owncloud/core#16378]
Hi,

First, my apologies if the question has already been asked, or if it's not the right place to do so.

Is there any graphical method to automatically update specific apps to their latest stable versions, or allowing the administrator to chose the version/tag to install ?

I've seen during my update to 8.0.2 that the web interface indicates the available updates for the owncloud-supported apps, but not for the third-party ones (or maybe I missed it, but I needed to upgrade them manually through SSH). And what about the apps which are regularly updated, how can the administrators stay up-to-date without having to inspect each github repo ?

Is there any really efficient "app-store" currently on the roadmap, accessible directly from the administration interface of ownCloud and allowing everyone to set up apps ? :)

Thanks in advance for your answers !

**Comment by karlitschek** [comment]
Actually all the apps that are downloaded and activated directly from the apps page should also offer updates if available.

**Comment by RealRancor** [comment]
Hi,

yes i can confirm this for various 3rdparty apps like "News", "Gallery+" and "Music".

> And what about the apps which are regularly updated, how can the administrators stay up-to-date without having to inspect each github repo ?

Personally i have subscribed to the apps i'm using at https://apps.owncloud.com to get mail notifications on updates.

> Is there any really efficient "app-store" currently on the roadmap, accessible directly from the administration interface of ownCloud and allowing everyone to set up apps ? :)

At least this should be possible with OC 8.1 and the possibility to use "experimental" apps which are not yet approved in the appstore.

**Comment by DeepDiver1975** [comment]
@Dark-Fenix question answered? Please reopen if something is still not working for you as expected. THX
