### ISSUE TITLE
"sorry, the link is not existing"

### ISSUE THREAD

**Issue by lippoliv** [owncloud/core#16379]
Hey there,
I shared an File of an "shared Folder", so an Folder which is shared to me through another ownCloud-User via link.

So:

User 1 share Folder "something" with an GROUP of users
I'am in that Group.
Through my ownCloud Client (or through WEB, doesn't matter) I share an file of the Folder "something" via link.
I copy the link and send it via WhatsApp / Telegram / mail / whatever else can be used.

The Person who opens up that link (and me too) get's the message

```
Entschuldigung, dieser Link scheint nicht mehr zu funktionieren.

Gründe könnten sein:

    Das Element wurde entfernt
    Der Link ist abgelaufen
    Teilen ist deaktiviert

Für mehr Informationen, frage bitte die Person, die Dir diesen Link geschickt hat.
```

What do I do wrong?

ownCloud Client 1.8.1
ownCloud Server 7.0.4
Force HTTPS with valid SSL Certificate
Dedicated Server
AMD Opteron(tm) Processor 3280 , 8 cores
32 GB DDR3 RAM
2x2.000GB SATA as RAID 1
100Mbit Bandwidth

Hopefully someone can help me with some Infos :)

Regards
  Oli

**Comment by DeepDiver1975** [comment]
@schiesbn @rullzer sounds like some more sharing fun :rocket:

**Comment by rullzer** [comment]
I'll try to reproduce this on master this evening. And check if we have a test for this (we *should*).

**Comment by DeepDiver1975** [comment]
> I'll try to reproduce this on master this evening. And check if we have a test for this (we should).

Incredible - THX

**Comment by rullzer** [comment]
I checked yesterday and this does work on current master.
A quick check also showed working behaviour on stable8. So I think it is an OC7 issue.

If I have time in the not to distant future I'll setup an OC7 instance

**Comment by lippoliv** [comment]
Hey guys, thanks for investigate to this Problem.

I will try to update my OC to OC8 this Weekend, hopefully the problem will also stop to appear for me :) Will comment here :)

**Comment by DeepDiver1975** [comment]
Please reopen if issue persists - THX
