### ISSUE TITLE
Upgrade jump from v5 to v8 (skip intermediate major releases)

### ISSUE THREAD

**Issue by osarrat** [owncloud/core#16376]
Admin Manuel says: "You cannot skip major releases; for example, upgrading from 5.0 to 7.0."
But if you use v5.. this means you will have to go through upgrade process 3 times to jump from v5 to v8 (v5=>v6, v6=>v7, v7=>v8).
For small organizations like mine, this make the process too much time-consuming.. and will go for other solution to use the latest features like the online .odt edition feature.

An improvement of the upgrade system to be able to jump from v5 to v8 for example would be great!

**Comment by DeepDiver1975** [comment]
This is not possible.  Sorry. We do this for a reason.  Thx

**Comment by osarrat** [comment]
As a computer engineer myself, I often say "nothing is impossible in software development, it is just a question of effort and ressource"..
So I guessed OC is designed to work like this for a good reason. And I understand now in your reply that it should far too ressource-consuming to design and maintain such an upgrade-jump system.
It's a pity, because it makes sysadmin OC maintenance tasks very heavy for small organisations.
I thank you anyway for your reply, and congratulations in general for the work you do with OwnCloud!

**Comment by karlitschek** [comment]
@osarrat I think what @DeepDiver1975 wanted to say is that is is currently not possible. But we want to support more flexible upgrades in the future.
