### ISSUE TITLE
Version dropdown shows somewhat "encrypted" text on previews

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#16373]
![bildschirmfoto vom 2015-05-15 15 15 02](https://cloud.githubusercontent.com/assets/213943/7653331/38113a4e-fb15-11e4-9211-a9ed25cf07dc.png)

Actual file content was:
```
frefegfrgregre

rregrg

etewr
```
and:
```
frefegfrgregre
rregrg
etewr
```

@schiesbn related to the other problem with previews?

**Comment by schiesbn** [comment]
I can't reproduce it... Works fine here on master. Can you try it again? Make sure that you don't have some old previews cached.

**Comment by nickvergessen** [comment]
Hmm can't reproduce anymore at the moment.

**Comment by SergioBertolinSG** [comment]
I can reproduce it.
**Steps**
1. Create a text file 'test.txt', write something readable.
2. Upload a file called 'test.txt' using webdav with different text on it.
3. Refresh web ui and open the dropdown. 

**Observed**
Preview in dropdown shows the encrypted weird characters.

**Comment by schiesbn** [comment]
I can reproduce it. It happens only with webdav, that's why I couldn't reproduce it the first time... I will prepare a fix.

**Comment by schiesbn** [comment]
@SergioBertolinSG the pr above should fix it... please give it a try. Thanks!
