### ISSUE TITLE
Server 2 Server problem with external apps when connection broken, erase or unshare.

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#16372]
### Steps to reproduce:
1.- Share a file over server to server sharing.
2.- Open the file with the text editor in the second server
3.- Erase/unshare the file from the first server, or broken connection.
4.- Web interface will be freezes.

What we are worried about is that similar bugs might be hiding in other viewer apps (pictures, pdf, documents etc.) since apparently the error handling is up to the app in this case and doesn't happen in ownCloud core.

@MorrisJobke 

00003118

**Comment by cdamken** [comment]
@PVince81 Show me: https://github.com/owncloud/files_texteditor/pull/72

**Comment by oparoz** [comment]
One of the underlying problems will only be fixed on 8.1 since it was not backported: https://github.com/owncloud/core/pull/15721

The Gallery app in 8.1 allows the user to explicitly enable scanning external shares (because they're very slow) and discards images if the image can't be accessed.

**Comment by MorrisJobke** [comment]
> since apparently the error handling is up to the app in this case and doesn't happen in ownCloud core.

Yes. If the app doesn't handle the error properly: :boom: ...we can do nothing here. There is no magic we can put into every app and then expect that it will never cause an error. The app needs to work.

Also https://github.com/owncloud/files_texteditor/pull/59 could fix most of this.

**Comment by MorrisJobke** [comment]
@jnfrmarks Maybe also worth to test scenarios like this for all shipped apps ;)

**Comment by MorrisJobke** [comment]
This was fixed in 8.0.4
