### ISSUE TITLE
[IE9] Data paste in a textbox with a pageholder sometimes is mixed using Internet Explorer 9

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16371]
### Steps to reproduce
1. Paste some data in a textbox with a pageholder

### Expected behaviour

The data pasted should replace the pageholder.

### Actual behaviour
Sometimes the data is mixed with the pageholder.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** "version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise"

**Comment by karlitschek** [comment]
can you post a full bug report using the issue template please?

**Comment by DeepDiver1975** [comment]
> can you post a full bug report using the issue template please?

@davitol where does this happen for example? THX

**Comment by davitol** [comment]
@DeepDiver1975 I cannot reproduce it now with 8.1.3 version. I remember it was a weird behaviour for example in sharing textbox 'Share with users, groups or remote users …' If it was pasted some info, it was mixed with the placeholder, but as i told you before i cannot reproduce it right now.

**Comment by davitol** [comment]
@DeepDiver1975 I've just tested on IE8, with oc 8.2. beta1 version and it happens in the sidebar, related to sharing textboxes for example:
![screen shot 2015-09-22 at 18 03 35](https://cloud.githubusercontent.com/assets/10596560/10023902/b118015c-6154-11e5-9fbf-ebf73a341450.png)

**Comment by MorrisJobke** [comment]
IE8 support will be dropped with 9.0 (see https://github.com/owncloud/core/issues/15567) and it works in IE9 -> closing
