### ISSUE TITLE
After Upgrade to 8.0.3 / External Storage / "Cannot redeclare class smb"

### ISSUE THREAD

**Issue by BlueStar88** [owncloud/core#16385]
Expected behaviour:

External Storage module should work, even if there are multiple instances of OC installed on the same host.

Actual behaviour:

First OC instance wins, all successive ones die on visit with following lighttpd error:

---
Cannot redeclare class smb in /var/www/instance1/apps/files_external/3rdparty/smb4php/smb.php on line 45
---

The error points to the code of the first visited OC instance. The webserver delivers nothing to the webbrowser. The first visited OC instance works like expected.

OS: Ubuntu Server 14.04.2 LTS
DB: MySQL 5.5.43-0ubuntu0.14.04.1
PHP: 5.5.9+dfsg-1ubuntu4.9
OC: 8.0.3
Web: lighttpd 1.4.35-0.1
Updated Installation (from 8.0.2)
Apps: Activity,Bookmarks,Calendar,Contacts,Deleted Files,Documents,External Sites,External storage support,First Run Wizard,Full Text Search,Imprint,Mail Template Editor,PDF Viewer,Pictures,Server-side Encryption,Share Files,Text Editor,Updater,Versions,Video Viewer

config.php
```
<?php
$CONFIG = array (
  'instanceid' => 'XXX',
  'passwordsalt' => 'XXX',
  'datadirectory' => 'XXX',
  'dbtype' => 'mysql',
  'version' => '8.0.3.4',
  'dbname' => 'XXX',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'XXX',
  'dbpassword' => 'XXX',
  'installed' => true,
  'forcessl' => true,
  'maintenance' => false,
  'theme' => '',
  'loglevel' => '4',
  'trusted_domains' => 
  array (
    0 => 'XXX',
    1 => 'XXX',
  ),
  'share_folder' => '/Shared',
  'secret' => 'XXX',
  'overwrite.cli.url' => 'XXX',
);
```

Usage of external storage unknown. I can not speak on behalf of other users.

Encryption is used.

External User-Backend not used.

Deactivating "External Storage" module on successive OC instances on the same host helps to avoid webserver crashes.

Other information will be delivered on request.

**Comment by BlueStar88** [comment]
Deactivating "External Storage" module on successive OC instances on the same host helps to avoid webserver crashes.

**Comment by PVince81** [comment]
Possible autoloader issue ? @DeepDiver1975

**Comment by Xenopathic** [comment]
Are any memory caches enabled? E.g. APCu, XCache?

**Comment by BlueStar88** [comment]
XCache 3.1.0 is enabled

XCache Cacher is ON
XCache Coverager is OFF
XCache Optimizer is OFF

**Comment by Xenopathic** [comment]
It is very likely that as the first instance caches the autoloaded file, the other instances try to use the same one. Could you disable the cache (temporarily, it's not a fix) and see if the problem persists?

**Comment by BlueStar88** [comment]
Good shot. Disabled XCache, problem solved.
After re-enabling, problem appears again.

**Comment by Xenopathic** [comment]
Could you check the `instanceid`s of each ownCloud instance and make sure they are all different? It almost seems like the autoloader is caching the path to the smb4php file, then the `require_once` is seeing a different path so the file gets included again. That would only happen if the instance IDs are the same for different installations.

**Comment by BlueStar88** [comment]
The instanceids of all instances are different.

**Comment by PVince81** [comment]
Is this still an issue with recent ownCloud versions like 8.2.2 and recent PHP versions like 5.6 ?

Please reopen if that's still happening. Thanks.
