### ISSUE TITLE
Differences between list and gallery views for link-shared folders

### ISSUE THREAD

**Issue by nclm** [owncloud/core#16386]
When sharing a folder from a link, the web view has two display modes: list and gallery (I believe there’s no tip about their actual names). Here’s how the pages top looks like in each option:

![List view](https://cloud.githubusercontent.com/assets/923008/7671589/732b1b86-fcd7-11e4-9b64-317243f44c34.png)
*List view*

![Gallery view](https://cloud.githubusercontent.com/assets/923008/7671590/733354ae-fcd7-11e4-96b1-adec942b891e.png)
*Gallery view*

It’s not really consistent.

The list has this that the gallery doesn’t have:
* Add button
* Download button
* Upload button (optional)

The gallery has this that the list doesn’t have:
* Name of the shared folder
* Name of the sharing person

I think it’s quite confusing, and having the same header for both would be better.

Here’s a very crude mock-up:

![Mock-up](https://cloud.githubusercontent.com/assets/923008/7671737/0ebbfcfc-fcdb-11e4-877c-873b19def287.png)
*Mock-up*

It has everything from both, plus:
* Upload and Download buttons close to each other. It would also allow the Upload button to get a label when the screen is large enough, as the Download button currently does.
* A switch UI element instead of an action button, so the user gets more easily that they can switch between two display modes.

**Comment by oparoz** [comment]
The next Gallery already has the download and home button ([demo](https://oc8demo.interfacloud.com/index.php/apps/galleryplus/s/4jjwPv5E21l8Lnk)), but I agree that some uniformity would be welcome.
Having the view switcher could be interesting if we add more views, like the document view for the current folder, but I don't think the documents app supports that.

@jancborchardt and his team would need to come up with a design to apply to all apps.

**Comment by jancborchardt** [comment]
The design to be applied should be the one used in the Files app. That is:
* header with buttons for »Add to your ownCloud« and »Download«
* »Upload« button as last item in breadcrumbs

Can you apply that for the Gallery+ app @oparoz?

I do like the view switcher which shows both views and makes clear which is the currently selected state. Otherwise it might not be clear what it is.

**Comment by jancborchardt** [comment]
cc @owncloud/designers as well

**Comment by oparoz** [comment]
@jancborchardt - I think the "shared by X" is missing from the Files app. It's very useful to get a reminder of who's sent you the files.

**Comment by jancborchardt** [comment]
@oparoz we deliberately cut this because it leaks the user name which is done nowhere else. We wanted to remove it in the Gallery app a long time ago also but the pull request never got through …

**Comment by oparoz** [comment]
OK

**Comment by jancborchardt** [comment]
Referencing the pull requests where we worked on this: https://github.com/owncloud/gallery/pull/33 and https://github.com/owncloud/gallery/pull/121

They are obsolete because basically it is fixed in Gallery+. @oparoz if the header in Gallery+ looks different from what I described above it would be cool to change it accordingly. :)

**Comment by oparoz** [comment]
@jancborchardt - I've created the missing tickets in the tracker and that will be taken care of eventually, but in any case, before it becomes the official app.

**Comment by nclm** [comment]
Thanks for the answers!

Additionally, I think the name of the shared folder is really quite useful, and is more relevant than a home icon; it does not appears in the current list view, nor in the next gallery view. It’s a sort of page title, to know what is this folder being shared.

**Comment by jancborchardt** [comment]
@oparoz great! Can you link them here so we can close this?

@nclm good point actually. Can you open this as a new separate issue? You are very welcome in our IRC channel #owncloud-design as well :)

**Comment by oparoz** [comment]
- [ ] Turn the Gallery button into a switch https://github.com/owncloud/galleryplus/issues/145
- [ ] Add "Add to owncloud" button https://github.com/owncloud/galleryplus/issues/144
- [ ] Upload straight from the app https://github.com/owncloud/galleryplus/issues/25

**Comment by jancborchardt** [comment]
Closing this in favor of these linked issues then. Thank you for the suggestions @nclm – please give your input in these individual issues then. :)
