### ISSUE TITLE
Unable to download any files

### ISSUE THREAD

**Issue by maxidebiax** [owncloud/core#16383]
### Steps to reproduce
1. Access to my files via web interface
2. Clic to download a file
2 bis. Clic to download severals files

### Expected behaviour
Download the file or download an archive.

### Actual behaviour
If i'm downloading one file. I got a message from Firefox : "Unfound file, check syntax, check if file exist"
If i'm downloading severals files : i've got an undersized archive (90b, when i expect 150k). The archive is not readable.

### Server configuration
**Operating system**:
Linux
**Web server:**
Debian 3.16.7-ckt9-3~deb8u1 (2015-04-24) x86_64 GNU/Linux
**Database:**
Mysql
**PHP version:**
PHP 5.6.7-1
**ownCloud version:** (see ownCloud admin page)
v8.0.3
**Updated from an older ownCloud or fresh install:**
Update from v7.0.4
**List of activated apps:**
News, Contacts, Calendar, Mail, Activity, Pictures, Server-side Encryption
**The content of config/config.php:**
  'instanceid' => 'oc6bb46df7bb',
  'passwordsalt' => '7a9422344febd254a8c67a058371ca',
  'trusted_domains' => 
  array (
    0 => 'web.XXXXXXX.fr',
    1 => 'cloud.mXXXXXXX.fr',
  ),
  'datadirectory' => '/home/owncloud',
  'overwrite.cli.url' => 'http://cloud.XXXXXX.fr',
  'dbtype' => 'mysql',
  'version' => '8.0.3.4',
  'dbname' => 'cloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'cloud',
  'dbpassword' => 'XXXXXXXXX',
  'installed' => true,
  'forcessl' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => 'XXXXXX',
  'mail_smtpauth' => 1,
  'mail_smtpport' => '25',
  'mail_smtpsecure' => 'tls',
  'mail_smtpname' => 'XXXXXX',
  'mail_smtppassword' => 'XXXXXX',
  'mail_domain' => 'XXXXXXXXXX',
  'appcodechecker' => 'false',
  'overwritewebroot' => '/cloud',
  'mail_from_address' => 'admin',
  'theme' => '',
  'maintenance' => false,
  'secret' => 'XXXXXXXXXXXx',
  'loglevel' => 0,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Iceweasel
**Operating system:**
Debian x64 stretch (same result with wheezy x32)
#### Web server error log
Nothing about this error...

#### ownCloud log (data/owncloud.log)

{"reqId":"3abdfcf5a3791ae90969869671a55508","remoteAddr":"88.178.38.106","app":"core","message":"OC\\Tags::__construct, tags: Array\n(\n)\n","level":0,"time":"2015-05-16T05:53:10+00:00","method":"GET","url":"\/cloud\/index.php\/apps\/files\/ajax\/list.php?dir=%2Fclientsync%2FExercices&sort=name&sortdirection=asc"}
{"reqId":"285447af30a98e4c32fd2db9b4b90b37","remoteAddr":"88.178.38.106","app":"index","message":"Exception: ","level":4,"time":"2015-05-16T05:53:16+00:00","method":"GET","url":"\/cloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2Fclientsync%2FExercices&files=liste_exos_maths.ods"}

**Comment by PVince81** [comment]
Hmmm, upgraded from OC 7.

Did you experience a timeout while the upgrade was running ?
It is likely that not all encryption keys were migrated.

Please try running `./occ encryption:migrate-keys`. It should hopefully migrate the remaining keys.

**Comment by maxidebiax** [comment]
Yep, twas that. But i'm pretty sure i did it the first time (after the upgrade). Anyway, thanks a lot.

**Comment by maxidebiax** [comment]
After nine days, it did it again.... I'd to do "encryption:migrate-keys" again.... Is that normal ?

**Comment by maxidebiax** [comment]
BTW I'm not able to download anything... but the other users can...

**Comment by DeepDiver1975** [comment]
> BTW I'm not able to download anything... but the other users can...

hmmm ... sounds like the encryption keys are still not yet all migrated for all users.

**Comment by maxidebiax** [comment]
I dit it twice since two days.... nothing changed...

**Comment by DeepDiver1975** [comment]
@schiesbn can I ask you to assist here to recover the encryption keys for this user? THX a lot!

**Comment by maxidebiax** [comment]
I reinstalled owncloud server. Now everything is great... Thx.
