### ISSUE TITLE
User did not have the required privileges ({DAV:}read) for path "calendars/USER/privat"

### ISSUE THREAD

**Issue by jeppebundsgaard** [owncloud/core#16387]
My lightning and android calendars throws errors when connecting to http://sky.bundsgaard.net/remote.php/caldav/calendars/USER/privat/. I can create new events in lightning, but I cannot sync with existing events.

When accessing the url from my browser, I get the above mentioned error. But if I am not logged into Owncloud first, I am asked for my credentials and then get access to a list of .ics-files.

I am using Owncloud 8.03, so it is patched with the patches mentioned in this issue: https://github.com/owncloud/core/issues/14048. The problem began after the update to 8.03.

**Comment by RealRancor** [comment]
Hi,

there is an open issue about this at the issue tracker of the calendar app: https://github.com/owncloud/calendar/issues/782

**Comment by MorrisJobke** [comment]
@jeppebundsgaard Please report any further problems with the calendar in the calendar bug tracker. Thanks :)

**Comment by jeppebundsgaard** [comment]
Sorry for reporting the error the wrong place. For visitors to this bug, I found a workaround:
I ended up exporting all appointments from the calendar not working, then I created a new calendar, and imported the exported ics-file into this calendar in Thunderbird/Lightning. This calendar works both ways.
