### ISSUE TITLE
Files with Reserved characters are allowed to be created

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16396]
### Steps to reproduce
1. Create a new file or folder with reserved characters

### Expected behaviour

It should not be allowed to create files or folders with reserved characters

### Actual behaviour

The files are created.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** "version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise"

![captura de pantalla 2015-05-18 a las 11 21 41](https://cloud.githubusercontent.com/assets/10596560/7677916/515ec100-fd50-11e4-80fd-8ab8825a3e7f.png)

**Comment by nickvergessen** [comment]
@PVince81 any idea?

**Comment by DeepDiver1975** [comment]
with 8.1 these chars are allowed now - not a bug - a feature :wink:

**Comment by rperezb** [comment]
ey @DeepDiver1975, will this be backported? This change affects the mobile clients as well as the desktop ones cc @dragotin
