### ISSUE TITLE
Uploaded files using webdav can't be decrypted.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16395]
### Steps to reproduce

1. Enable encryption app.
2. Enable encryption module in admin page.
3. Relogin.
4. Upload some files using webdav interface.

### Expected behaviour
Uploaded files can be decrypted.

### Actual behaviour
Uploaded files can't be decrypted.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition.
Encryption.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
Yes

**Logs**
```
```

### Client configuration

**browser**
Chrome 41, Firefox

**Comment by nickvergessen** [comment]
Which version?

**Comment by SergioBertolinSG** [comment]
{"installed":true,"maintenance":false,"version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise"}

**Comment by nickvergessen** [comment]
Can you retry on master please. There have been some fixes around that code path in core since beta1

**Comment by SergioBertolinSG** [comment]
Tested in master branch, it was fixed.
