### ISSUE TITLE
Corrupted file downloading it from different external storages

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#16393]
### Steps to reproduce
1. Install and enabled external storage and encryption apps
2. Setup 2 different storages pointing to the same folder in the same server (checked with SFTP and FTP, against the same /tmp directory of the same server)
3. Upload correctly a file there (be aware of possible limitations such as https://github.com/owncloud/core/issues/16356) using one of the storages
4. Download the same file (which should be visible) from the other storage

### Expected behaviour
The file is downloaded correctly

### Actual behaviour
The file is corrupted

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 beta 1

**Updated from an older ownCloud or fresh install:** fresh install

**List of activated apps:**
 - encryption: 1.0.0
 - files: 1.1.9
 - files_external: 0.2.3
 - files_locking: 
 - files_sharing: 0.6.1
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - user_ldap: 0.6.0

**Comment by jvillafanez** [comment]
Setting as low severity because looks like an edge case. Users shouldn't need this kind of setup.

**Comment by PVince81** [comment]
I think this is not a valid use case: encrypted files should never be accessed through any other means than the original storage instance that was used to encrypt them.

This means that an admin should never setup two external storage instances that point to the same encrypted data. That will not work as they will be using different keys. ownCloud interprets them as different storages.

Closing as invalid.

Still, nice find :wink:

**Comment by PVince81** [comment]
I wonder if this should get documented though.

CC @carlaschroder @MTRichards

**Comment by MTRichards** [comment]
Gould idea to document this inside the standard encryption documentation.

**Comment by MTRichards** [comment]
Gould idea to document this inside the standard encryption documentation.
