### ISSUE TITLE
Menu 'New'  keeps dropped down after changing of screen 

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16394]
### Steps to reproduce
1. Click on New button, so the menu is visible
2. Go to 'Shared with you' menu for example.
3. Go back to All files menu

### Expected behaviour
The menu should not appear dropped down the second time.

### Actual behaviour

The ' New' menu appears dropped down

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** "version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise"

![captura de pantalla 2015-05-18 a las 10 36 33](https://cloud.githubusercontent.com/assets/10596560/7677346/81af7a2a-fd4b-11e4-90bd-09417dbbd59e.png)

**Comment by nickvergessen** [comment]
I think this should be an easy one. So it should be fixable on stable8 aswell

**Comment by jancborchardt** [comment]
@nickvergessen so you will be working on this?

**Comment by nickvergessen** [comment]
No, I just think that we can change this in 8.0 and not 8.2 only

**Comment by jancborchardt** [comment]
cc @MorrisJobke in that case. Can you work on that, or mention someone who can?

**Comment by nickvergessen** [comment]
The sev4 level is not what we are focusing on atm ;)

**Comment by MorrisJobke** [comment]
Fix is in #16444

**Comment by davitol** [comment]
Fixed :+1:

**Comment by MorrisJobke** [comment]
@davitol The ticket gets closed automatically once the code is in the master branch and accepted. Until the branch is merged, the ticket has to stay open, because it is only solved in a side branch.

**Comment by davitol** [comment]
@MorrisJobke OK, thanks for the info.

**Comment by MorrisJobke** [comment]
backport requested in #16462
