### ISSUE TITLE
Better UX: Provide info why "Only SQLite is available.." in installer

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#16391]
With the current installer of OC 8.0.3 the user gets this screen shown if only php5-sqlite on debian/ubuntu is installed:

![screenshot - 18 05 2015 - 09 57 14](https://cloud.githubusercontent.com/assets/2248459/7676485/6f70d8b0-fd44-11e4-86e9-ae6ada9097df.png)

This currently contains no informations why only SQLite is available. A user needs to install php5-pgsql or php5-mysql/php5-mysqlnd to get other database options shown within the installer.

This has lead to some confusion and forums postings in the past how to get other options shown.

The modules to install are listened at https://doc.owncloud.org/server/8.0/admin_manual/installation/source_installation.html but the experience has shown that users are not reading this informations or just can't find it.

**Comment by oparoz** [comment]
I think a simple link to the doc would help here.

**Comment by RealRancor** [comment]
Together with a short note that other PHP database drivers needs to be installed according to the documentation a link to the doc could be a possible solution.

**Comment by MorrisJobke** [comment]
Fix is in #16426
