### ISSUE TITLE
I can have two files with the same name

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/core#16408]
### Steps to reproduce
1. Open your Owncloud  Web Client
2. Create a new File, call aaa
3. Sync
4. Open your Owncloud Desktop client
5. Create other File, call aaa (the aplication said is a duplicate), but you can create de File call AAA(2)
6. Go to Owncloud Web Client
7. You have two Files (one call aaa, the second call AAA(2))
8.  If you change the name AAA(2) for AAA
### Expected behaviour

Sync the folder because the name is diferent
### Actual behaviour

Is not sync, and The following error appears

![screen shot 2015-05-18 at 14 08 24](https://cloud.githubusercontent.com/assets/12032058/7680516/7adf8c8c-fd67-11e4-9c44-f8d8e890e111.png)

LOGS:

```
05-18 14:06:22:517 0x7f9a3a507700 OCC::ownCloudGui::slotSyncStateChange: Sync state changed for folder  "ownCloud" :  "Sync Running"
05-18 14:06:22:517 0x7f9a3a507700 OCC::PropagateLocalRename::start: MOVE  "/Users/Diana/ownCloud/AAA (2).txt"  =>  "/Users/Diana/ownCloud/AAA.txt"
05-18 14:06:22:517 0x7f9a3a507700 OCC::SyncJournalErrorBlacklistRecord::update: This error is not blacklisted  0
05-18 14:06:22:517 0x7f9a3a507700 OCC::SyncEngine::slotJobCompleted: void OCC::SyncEngine::slotJobCompleted(const OCC::SyncFileItem &) "AAA (2).txt" INSTRUCTION_RENAME 2 "File AAA (2).txt can not be renamed to AAA.txt because of a local file name clash"
05-18 14:06:22:520 0x7f9a3a507700 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:ERROR:/Users/Diana/ownCloud/AAA.txt"
05-18 14:06:22:521 0x7f9a3a507700 OCC::SyncJournalDb::walCheckpoint: void OCC::SyncJournalDb::walCheckpoint() took 0 msec
05-18 14:06:22:522 0x7f9a3a507700 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString &, bool) Transaction commit  "All Finished." 
05-18 14:06:22:522 0x7f9a3a507700 OCC::SyncEngine::finalize: CSync run took  198
05-18 14:06:22:522 0x7f9a3a507700 OCC::BandwidthManager::~BandwidthManager: virtual OCC::BandwidthManager::~BandwidthManager()
05-18 14:06:22:523 0x7f9a3a507700 OCC::Folder::slotSyncFinished: -> SyncEngine finished without problem.
```
### Version Desktop

Version 1.8.2 (build 5083) WINDOWS
### Version Web

{"installed":true,"maintenance":false,"version":"8.0.3.4","versionstring":"8.0.3","edition":"Enterprise"}

**Comment by oparoz** [comment]
I agree, the Web GUI should not let a user create or rename a file with the same name as another one, when compared in lowercase, since that file will never sync to Windows clients.

**Comment by PVince81** [comment]
Hmm, but mixed casing is allowed on the server side (and was always, except on Windows servers)

That's a bigger discussion about what is allowed in file names, this discussion will need to continue at some point @dragotin @DeepDiver1975 @danimo

**Comment by PVince81** [comment]
Works as designed, closing
