### ISSUE TITLE
Wrong error message trying to rename a file with / at the end of the name

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16401]
### Steps to reproduce
1. Create a new file.
2. Try to rename it using ' / ' character at the final

### Expected behaviour

An error message should be shown about reserved characters

### Actual behaviour

The error shown says "The name is alreadt used in the folder..."

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** "version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise"

![captura de pantalla 2015-05-18 a las 11 27 17](https://cloud.githubusercontent.com/assets/10596560/7678898/36242292-fd58-11e4-9e40-fbe53e8839e1.png)

**Comment by nickvergessen** [comment]
`/` seem to be trimmed away, so it uses `.txt` and that already exists on your screen?

**Comment by nickvergessen** [comment]
Related to https://github.com/owncloud/core/issues/16396

Summoning @DeepDiver1975 do you have a link to the PR that changed all this?

**Comment by davitol** [comment]
@nickvergessen yes, it seems to be happen it.

**Comment by davitol** [comment]
:+1: fixed in version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"
