### ISSUE TITLE
Web Interface does not display correctly in IE9

### ISSUE THREAD

**Issue by gig13** [owncloud/core#16409]
**Expected Behavior**
The web interface should display correctly in IE9.

**Actual Behavior**
The log in screen does not display correctly when using IE9 (compatibility mode ON or OFF) and prevents the user from logging in.The password field is not accessible, and the login button is off center

*Steps to reproduce**
Use IE9 with compatibility mode ON or OFF and try to login using the login screen

**Server configuration**
CentOS 6
Database MySQL
OC 7.0.5
Browser: IE9

Note: When testing with IE8, the login screen works when compatibility mode is turned OFF. When compability mode is turned ON, the similar behavior is observed.

screenshot using IE9
![201514_display_issue_login_page](https://cloud.githubusercontent.com/assets/4803385/7681018/28b3adf8-fd3a-11e4-8538-9c314210f1e3.jpg)

**Comment by MorrisJobke** [comment]
And this is enterprise theme related. cc @jancborchardt

**Comment by jancborchardt** [comment]
@gig13 does this happen with ownCloud 8 as well? And with ownCloud 7 and 8 both also in the community version?

**Comment by MorrisJobke** [comment]
Fix for stable7 is in #16415

I will test stable8 and master now

**Comment by gig13** [comment]
@jancborchardt 
I am not testing with the community version, related to a customer using OC7.0.5 EE. I see similar behavior using OC803 and IE8 and IE9.

**Comment by MorrisJobke** [comment]
Stable8 #16416

**Comment by MorrisJobke** [comment]
master #16417

All PRs fixes issues with themes. The community theme is not affected (beside master where the footer is now also fixed, because it was broken)

**Comment by jancborchardt** [comment]
@gig13 please test if the above pull requests solve the problem. Thanks!

**Comment by gig13** [comment]
@jancborchardt 
The same behavior even after the change. No improvement.

**Comment by MorrisJobke** [comment]
> The same behavior even after the change. No improvement.

Really? Did you cleared the browser cache?

**Comment by gig13** [comment]
@MorrisJobke 
Yes, cleared the browser cache.

**Comment by MorrisJobke** [comment]
> @MorrisJobke
> Yes, cleared the browser cache.

Which apps are enabled?

**Comment by gig13** [comment]
The default from an Enterprise install. 
![apps](https://cloud.githubusercontent.com/assets/4803385/7732867/f26cd3c6-fef8-11e4-8731-bdb75d9ac75a.PNG)

**Comment by davitol** [comment]
:+1: fixed in IE9

**Comment by cmonteroluque** [comment]
@gig13 @MorrisJobke Can we close this?

**Comment by gig13** [comment]
@cmonteroluque 
Yes, and the clarification that we do not support "compatibility mode" is also useful knowledge!

**Comment by rperezb** [comment]
cc/ @carlaschroder probably this is for you :)

**Comment by MorrisJobke** [comment]
More IE fixes are referenced in https://github.com/owncloud/core/issues/15413#issuecomment-108251921

**Comment by carlaschroder** [comment]
IE? People still use that??

**Comment by gig13** [comment]
@carlaschroder 
Yes, tons of people still use IE.
