### ISSUE TITLE
FTP external storage doesn't get the updates made in the backend

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#16407]
### Steps to reproduce
1. Configure a FTP external storage
2. Upload a file directly in the backend
### Expected behaviour

The file should appear in ownCloud, in the configured mount point
### Actual behaviour

File is missing in the configured mount
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 beta 1

**Updated from an older ownCloud or fresh install:** fresh install

**List of activated apps:**
- encryption: 1.0.0
- files: 1.1.9
- files_external: 0.2.3
- files_locking: 
- files_sharing: 0.6.1
- files_trashbin: 0.6.2
- files_versions: 1.0.5
- user_ldap: 0.6.0

**Comment by RealRancor** [comment]
Hi,

very likely related to https://github.com/owncloud/core/issues/5036 where some workarounds like using a cronjob to rescan the external storage where posted.

**Comment by jvillafanez** [comment]
I don't think is related to #5036 because that issue affects all external storages (or at least it did). This issue affects only to FTP storage. Other storages get the new file correctly after reloading the page in the web, but not FTP

**Comment by RealRancor** [comment]
But #11797 says:

> None of Amazon/Ceph s3 #11652, Swift #8633, ftp #5655, ftps/proftpd #9630, smb on FAT correctly propagates mtime changes up the directory tree, so our hasUpdated() fails and we have yet to implement backend specific implementations that work.

**Comment by PVince81** [comment]
It might also depend on the FTP server. Some might deliver proper mtimes (in a format that the FTP stream wrapper from PHP is able to read) which makes it possible to detect updates. Some others might not.

**Comment by DeepDiver1975** [comment]
Known issue no some external storages - we need to address this in 8.2. nothing we can do in the livecycle of 8.1

**Comment by PVince81** [comment]
General ticket: sort out external storage update issues: https://github.com/owncloud/core/issues/11797

**Comment by PVince81** [comment]
@DeepDiver1975 move to 9.0 ?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 move to 9.0 ?

yes from my pov @cmonteroluque objections?

**Comment by cmonteroluque** [comment]
@DeepDiver1975 @PVince81 Yeah, part of the overall issue with external shares. Tough to accept but no choice at all.

**Comment by PVince81** [comment]
@DeepDiver1975 @icewind1991 what about the flysystem FTP implementation ? Didn't we want to replace the existing one with this new one ? Would be good to find out whether it fixes the mtime based change detection problem.

**Comment by PVince81** [comment]
Moving to 9.2

**Comment by PVince81** [comment]
Please try again with the "files_external_ftp" app which is based on flysystem.
