### ISSUE TITLE
Spinner keeps loading after renaming a file in a shared folder

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16410]
### Steps to reproduce
1. Share a folder from Server A to B with a txt file inside.
2. Rename the txt file in B

### Expected behaviour

The file should be renamed

### Actual behaviour

The spinner keeps loading, but if you move to another menu and then back to the folder, the file appears renamed. 

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** "version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise"

![captura de pantalla 2015-05-18 a las 14 50 02](https://cloud.githubusercontent.com/assets/10596560/7681179/12011ca6-fd6e-11e4-8eba-4e12e9be4647.png)

**Comment by nickvergessen** [comment]
Works for me. Please use the issue template: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version
In this case the important list of enabled apps is missing.

**Comment by davitol** [comment]
@nickvergessen The bug was reproduce using federated sharing, browsers: IE9 and Firefox 37.0.2. 
List of enabled apps:
- Default package
- LDAP user and group backend
The user in server B that renames the file is from an Active Directory.

**Comment by nickvergessen** [comment]
Things like "Default package" do not exist as a git repository.

Please simply run
```
./occ app:list
```

**Comment by davitol** [comment]
Enabled:
 - activity: 1.2.3
 - admin_audit: 0.6
 - encryption: 1.0.0
 - enterprise_key: 0.1.0
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.4
 - user_ldap: 0.6.0
 - windows_network_drive: 0.1.1
Disabled:
 - external
 - files_antivirus
 - files_drop
 - files_external
 - files_ldap_home
 - objectstore
 - sharepoint
 - user_external
 - user_shibboleth
 - user_webdavauth

**Comment by PVince81** [comment]
Are you sure it's not just slow and takes longer to rename ?

If not, then maybe something is wrong in the network response or in the JS code that should remove the spinner. (anything in the JS console ?)

**Comment by razyr** [comment]
I saw similar behaviour when I reported #16256.  Only a manual refresh of the page got rid of the spinner after a rename.

**Comment by davitol** [comment]
In "version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise does not reproduce.
