### ISSUE TITLE
shared document link points to the wrong folder (root) rather then to 'shared'

### ISSUE THREAD

**Issue by CaptionF** [owncloud/core#16418]
When sharing files or folders through ownCloud accounts, and inform the recipient that it is shared with him by selecting in the sharing dialog box "notification per email", 
then the email to the recipient contains a link that points to the root folder, rather then to the shared folder.
Also the shared file or folder is not highlighted, the user experience is not good!
oC 8.0.3
Web Interface (independent of the browser)

**Comment by nickvergessen** [comment]
Duplicates #16109
