### ISSUE TITLE
App manager needs a refresh button

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#16422]
### Env
8.0

### Steps to reproduce

1. Go to the app manager
2. Install an app via the shell
3. Go to the "not enabled" tab

### Expected result
The app should be listed

### Actual result
The app is NOT listed.
Hitting F5 doesn't help.
Logging out and back in doesn't help.

It seems the admin has to wait for the cron job to detect a new app and it's bad a UX.

**Comment by RealRancor** [comment]
Hi,

relating to or even duplicates https://github.com/owncloud/core/issues/16140

**Comment by oparoz** [comment]
Ah, I didn't think about the cache.

Looks like the special button will be implemented in 8.2
https://github.com/owncloud/core/issues/13658#issuecomment-71390263

**Comment by MorrisJobke** [comment]
Yes. This is a bug and a duplicate.

**Comment by jancborchardt** [comment]
Even if it would be that way without the cache – the proper solution would not be to »add a button« but to »fix it«. ;) More buttons rarely help.
