### ISSUE TITLE
several owncloud file corrupted

### ISSUE THREAD

**Issue by Battant** [owncloud/core#16425]
Hello,

I don't know why I get an error on syn whith owncloud server became corrupted when is downlouded and the synching betwinn owncloud 8 server and os x 10.10.3 client is interrupted whith an error.

Could you help me please

Best regaards

Battant

Actuel result
File corrupted
Expended result
Please implement this case and fix this issus
Owncloud client
owncloud for os x, ubuntu 14.04 and windows

Serveur hest information

https://www.kreativmedia.ch/fr/

Hebergergement mutualiser/Hébergement d'application

**Comment by karlitschek** [comment]
Can you please post a full bug report using the issue template? https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by PVince81** [comment]
Please try again with 8.0.6 or 8.1.1 and sync client 1.8.4.

If you're still having issues, feel free to reopen and then provide more information about your setup using the issue template: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md
