### ISSUE TITLE
Drop support for PHP 5.4 with ownCloud 8.2?

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#16428]
PHP 5.4 will be EOL when 8.2 hits the street, so should we focus on 5.5 for 8.2?
5.4 has only been getting security fixes for a while and serious issues which may affect ownCloud have not been fixed (i.e [default_socket_timeout does not work with SSL](https://bugs.php.net/bug.php?id=41631))

After that, 9.2 should be 5.6+ only and another change would not be required for a full year.

**Comment by karlitschek** [comment]
At the moment 5.4 is still widely used in Linux distributions and on existing servers out there. If we stop supporting this we would lose a lot of users. I recommend that we still support it until we find a valid reason why this is no longer possible. (significant feature or security regression)

**Comment by DeepDiver1975** [comment]
Fyi: after some discussion with evert we came to the agreement that sabredav 3.0 will also continue to support php 5.4.

So no reason to drop it for the time being.

**Comment by rullzer** [comment]
Still it probably would be good to add warnings to the security & setup section in the admin panel for 8.2.

**Comment by DeepDiver1975** [comment]
@lukasreschke ???

**Comment by oparoz** [comment]
@rullzer - I like your idea, maybe submit a new ticket for that? Some users will be stuck with what their OS give them, but I think it's a good idea to remind non-professional admins that they should try to find ways to upgrade

**Comment by rullzer** [comment]
PR for the warning in #17919

**Comment by MorrisJobke** [comment]
I will close this. It can be reevaluatet once a valid reason to drop it is known.

**Comment by RealRancor** [comment]
Follow-up now in https://github.com/owncloud/core/issues/25408
