### ISSUE TITLE
dbtableprefix doesn't work on MySQL

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#16438]
* add `'dbtableprefix' => 'ownc_',` to `config/my.config.php`
* run the installation and use a MySQL DB

## Expected

* table names are starting with `ownc_` (this is the case for sqlite installation)

## Actual

* table names start with `oc_`

Error on installation:
```
An exception occurred while executing 'SELECT `configvalue`, `appid` FROM `ownc_appconfig` WHERE `configkey` = ?' with params ["enabled"]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'oc.ownc_appconfig' doesn't exist
Datei: /home/mjob/Projekte/owncloud/master/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php
```

cc @PVince81 @DeepDiver1975

**Comment by PVince81** [comment]
The problem is the setup ignores the prefix in config.php. I didn't find any way to setup OC with a non-standard prefix.

**Comment by MorrisJobke** [comment]
> The problem is the setup ignores the prefix in config.php. I didn't find any way to setup OC with a non-standard prefix.

How could then existing instances with a different prefix be out there? And why did it work with SQLite? And why wasn't this fixed previously? Was it an option in the installer in pre-stable7?

**Comment by PVince81** [comment]
It probably worked with older ownClouds I guess.

The option was removed as per design decision.

Not sure why it worked with SQLite though.

**Comment by MorrisJobke** [comment]
> Was it an option in the installer in pre-stable7?

Ah ... it was an option until ownCloud 5 ;)

**Comment by DeepDiver1975** [comment]
starting with oc8.1 the prefix can be used during setup using the console

**Comment by DeepDiver1975** [comment]
case closed then?

**Comment by MorrisJobke** [comment]
> case closed then?

I just wonder why this works with SQLite but not with MySQL. BUt I'm fine with closing this. It is simp0ly not supported to set a prefix via web installer.
