### ISSUE TITLE
Recover login password

### ISSUE THREAD

**Issue by Z3roCoder** [owncloud/core#16431]
Hello there. Is it perhaps possible for me as admin of the DB, to be able to somehow see what password what user has?

I have been asked by one of my users to recover their passwords but they dont want to set a new one, so this is why I am asking

**Comment by RealRancor** [comment]
Hi,

ownCloud is creating a hash+salt of the users password so there is currently no way to recover this password without starting to bruteforce the password itself.

**Comment by nickvergessen** [comment]
For more information see https://forum.owncloud.org/viewtopic.php?f=23&t=9250#p30382
