### ISSUE TITLE
An advice should appear when we try to remote share a file and it is disabled

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16433]
### Steps to reproduce
1. Disable option Allow users on this server to send shares to other servers
2. Try to send a file to a user to another server

### Expected behaviour
A message or tooltip should appear about 'Allowing users of this server to send shares to other servers is not enabled' when we try it

### Actual behaviour
It is nothing said about it when we try to send a share to another server.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:** Default + LDAP user and group backend

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** ActiveDirectory

### Client configuration
**Browser:** Internet Explorer 9

![captura de pantalla 2015-05-19 a las 10 03 02](https://cloud.githubusercontent.com/assets/10596560/7698165/557a6e7e-fe0e-11e4-8259-98a13b284abf.png)

**Comment by nickvergessen** [comment]
Should we notify users about a feature that has never been on that instance?

**Comment by davitol** [comment]
well, at least the page holder is right and changes if federated sharing is enabled.

- Share with users or groups …

turns into

Share with users, groups or remote users …

so maybe it is enough.
