### ISSUE TITLE
Shared files does not appear in shared with you menu using federated sharing

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16435]
### Steps to reproduce
1. Enable option Allow users on this server to send shares to other servers
2. Send a file to a user to another server
3. Go to 'shared with you' menu in server 'B'

### Expected behaviour
The files shared with the user should appear

### Actual behaviour
The list of files is empty. It only happens with federated sharing. Local behaviour is right.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity: 1.2.3
 - admin_audit: 0.6
 - encryption: 1.0.0
 - enterprise_key: 0.1.0
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.4
 - user_ldap: 0.6.0
 - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** ActiveDirectory

### Client configuration
**Browser:** Internet Explorer 9

![captura de pantalla 2015-05-19 a las 11 10 03](https://cloud.githubusercontent.com/assets/10596560/7699398/e8160dd4-fe17-11e4-8823-87858556b3c3.png)

![captura de pantalla 2015-05-19 a las 11 10 33](https://cloud.githubusercontent.com/assets/10596560/7699400/eea53e86-fe17-11e4-8015-c4a06da0b7c5.png)

**Comment by PVince81** [comment]
I'm pretty sure there were one or two duplicates for this issue but I can't seem to find it.

**Comment by PVince81** [comment]
Ah, here it is: https://github.com/owncloud/core/issues/9098
It was wrongly tagged.

I'll close yours as duplicate and move over the tags.
