### ISSUE TITLE
Restoring deleted files with Federated sharing has a wrong behaviour

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16441]
### Steps to reproduce
1. Enable option Allow users on this server to send shares to other servers
2. Create a file in server 'B' named AAA for example
3.  Delete file 'AAA' in server 'B'
4.  Send a file named AAA from another server to 'B'
5.  Restore the deleted file in 'B'

### Expected behaviour
The file restored in server B should be renamed as AAA(2) for example, when it is restored.

### Actual behaviour

The file restored deletes the file AAA shared

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity: 1.2.3
 - admin_audit: 0.6
 - encryption: 1.0.0
 - enterprise_key: 0.1.0
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.4
 - user_ldap: 0.6.0
 - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** ActiveDirectory

### Client configuration
**Browser:** Internet Explorer 9 & Firefox

**Comment by PVince81** [comment]
There was a bug related to restoring files where it would overwrite existing files, unrelated to federated clouds: https://github.com/owncloud/core/issues/16246

Maybe the detection of existing files doesn't work properly in this specific case.

**Comment by PVince81** [comment]
Works for me on master (12aef311154f12050c4e33492dac1fb1c928060d)
It is very likely that this was fixed as part of https://github.com/owncloud/core/issues/16246
