### ISSUE TITLE
Handle aborted transactions properly

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#16445]
We introduced transactions in some code parts. We should properly handle them like described in http://doctrine-dbal.readthedocs.org/en/latest/reference/transactions.html#transactions

See https://github.com/owncloud/core/pull/13948#issuecomment-102378344
- [ ] https://github.com/owncloud/core/blob/a8b756154a533a2618f03c54aca56af957da12ae/lib/private/files/utils/scanner.php#L151
- [ ] https://github.com/owncloud/core/blob/a8b756154a533a2618f03c54aca56af957da12ae/lib/private/db/mdb2schemamanager.php#L169
- [ ] https://github.com/owncloud/core/blob/a8b756154a533a2618f03c54aca56af957da12ae/lib/private/db/migrator.php#L216
- [ ] https://github.com/owncloud/core/blob/a8b756154a533a2618f03c54aca56af957da12ae/lib/private/connector/sabre/custompropertiesbackend.php#L261
- [ ] https://github.com/owncloud/core/blob/80b892e7ed7b2d6b5220840e1bb3b11115c72cb4/lib/repair/repairlegacystorages.php#L164
- [ ] https://github.com/owncloud/core/blob/a13088818a73ecdf6f7d6600c011e0fa49054b51/lib/private/files/cache/scanner.php#L313
- [ ] https://github.com/owncloud/core/blob/f1903f61a11c9e9c7a5b50af82883031cb1e95c1/lib/private/files/cache/cache.php#L549

**Comment by MorrisJobke** [comment]
I added all occurences in core.

**Comment by PVince81** [comment]
@MorrisJobke if I understand well, there are some distributed systems on which the likeliness of failed transactions is higher ?

Do we know whether the fail is actually a "lock" or is it any SQL statement in the middle of the transaction that throws an exception ? Or does it happen on commit ?

With a locking situation, from what I observed it seemed to happen on commit.

**Comment by Helios07** [comment]
I don't know if it helps, we are getting errors like the following with our Galera cluster (OC 7.0.4 EE):

owncloud.log-20150523:{"app":"hook","message":"error while running hook (OCA\\Files_Trashbin\\Hooks::remove_hook): An exception occurred while executing 'UPDATE `oc_filecache` SET `mimepart` = ?, `mimetype` = ?, `mtime` = ?, `size` = ?, `etag` = ?, `storage_mtime` = ?, `permissions`=? WHERE `fileid` = ?':\n\nSQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction","level":3,"time":"2015-05-22T20:16:07+00:00"}
owncloud.log-20150523:{"app":"hook","message":"error while running hook (OCA\\Files_Trashbin\\Hooks::remove_hook): An exception occurred while executing 'UPDATE `oc_filecache` SET `mimepart` = ?, `mimetype` = ?, `mtime` = ?, `size` = ?, `etag` = ?, `storage_mtime` = ?, `permissions`=? WHERE `fileid` = ?':\n\nSQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction","level":3,"time":"2015-05-22T20:19:34+00:00"}
owncloud.log-20150523:{"app":"hook","message":"error while running hook (OCA\\Files_Trashbin\\Hooks::remove_hook): An exception occurred while executing 'UPDATE `oc_filecache` SET `mimepart` = ?, `mimetype` = ?, `mtime` = ?, `size` = ?, `etag` = ?, `storage_mtime` = ?, `permissions`=? WHERE `fileid` = ?':\n\nSQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction","level":3,"time":"2015-05-22T20:19:49+00:00"}
owncloud.log-20150523:{"app":"hook","message":"error while running hook (OCA\\Files_Trashbin\\Hooks::remove_hook): An exception occurred while executing 'UPDATE `oc_filecache` SET `mimepart` = ?, `mimetype` = ?, `mtime` = ?, `size` = ?, `etag` = ?, `storage_mtime` = ?, `permissions`=? WHERE `fileid` = ?':\n\nSQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction","level":3,"time":"2015-05-22T20:25:27+00:00"}
owncloud.log-20150523:{"app":"hook","message":"error while running hook (OCA\\Files_Trashbin\\Hooks::remove_hook): An exception occurred while executing 'UPDATE `oc_filecache` SET `mtime` = ?, `etag`=? WHERE `fileid` = ?':\n\nSQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction","level":3,"time":"2015-05-22T20:33:08+00:00"}
owncloud.log-20150523:{"app":"remote","message":"An exception occurred while executing 'UPDATE `oc_filecache` SET `mtime` = ?, `etag`=? WHERE `fileid` = ?':\n\nSQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction","level":4,"time":"2015-05-22T21:18:26+00:00"}
owncloud.log-20150523:{"app":"remote","message":"An exception occurred while executing 'UPDATE `oc_filecache` SET `mtime` = ?, `etag`=? WHERE `fileid` = ?':\n\nSQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction","level":4,"time":"2015-05-22T22:25:14+00:00"}
owncloud.log-20150524:{"app":"remote","message":"An exception occurred while executing 'UPDATE `oc_filecache` SET `mtime` = ?, `etag`=? WHERE `fileid` = ?':\n\nSQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction","level":4,"time":"2015-05-23T01:44:35+00:00"}

**Comment by PVince81** [comment]
I've seen the lock exceptions in local tests, it happened when two transactions clashed.

The only transaction that exists on OC 7.0.x is for the file scanner.
So it is likely that two scanner processes were trying to scan (and update the cache) for the same folder at the same time.

**Comment by DeepDiver1975** [comment]
@cmonteroluque @karlitschek I vote for moving this to 9.0 and explicit allocate time - this is not a bug fix we should do quickly

**Comment by cmonteroluque** [comment]
@DeepDiver1975 the pity is that this is a 19 May issue. But ok.

**Comment by MorrisJobke** [comment]
> @DeepDiver1975 the pity is that this is a 19 May issue. But ok.

It's a last years issue if you count this as argument ;) But I also tend to be against this, because it has a huge impact. We should focus on this in the early stage of development of 9.0 to have the chance to spot as many issues as possible. So 9.0 is a good decision.

**Comment by PVince81** [comment]
And now seems same story, move to 9.1 ? Would be good to have time allocated for this.

**Comment by PVince81** [comment]
Moving to 9.1

**Comment by PVince81** [comment]
CC @cmonteroluque
