### ISSUE TITLE
FreeNAS not supported?

### ISSUE THREAD

**Issue by thejrose1984** [owncloud/core#16455]
I noticed ownCloud has a plugin in FreeNAS and can be installed using a `pkg install owncloud` command. I'm assuming those installs are third party?

**Comment by RealRancor** [comment]
Hi,

please note that this is a bugtracker where bugs and feature requests for ownCloud are reported. Such general questions are better placed at either the forums:

https://forum.owncloud.org/

or the user mailinglist:

https://mailman.owncloud.org/mailman/listinfo/user
