### ISSUE TITLE
ownCloud Database issue

### ISSUE THREAD

**Issue by iliyasbasir** [owncloud/core#16454]
[3194]

#### Summary of issue:
Getting "not null" constraint violation when performing upgrade (Oracle)
#### Actual behavior
It's should be upgrade oC without this issue
#### Step to reproduce
Run upgrade.
#### Server configuration

Red Hat Enterprise Linux Server release 6.6 (Santiago)
httpd-2.2.15-39.el6.x86_64
php-common-5.3.3-40.el6_6.x86_64
owncloud-enterprise-7.0.5-3.1.noarch
storage is a cifs mount from a Windows 2012R2

#### Note
 Let me know what information do you need so i can collecet from customer {here is GitHub related issue they had with REHL repo for  your reference https://github.com/owncloud/core/issues/16343}

### Notes from Customer:
(directly from customer, they were attempting to self-diagnose the problem)
>The issue is they are trying to add a new column with a "not null" constraint without a default value to an existing table with data in it. The existing table has 9 rows of data. Oracle cannot not resolve how to add a "not null" constrained column to the existing rows of data because it does not know what to set them to (no default value provided) nor can it set them to null (violates the constraint) - they have created a situation that is impossible for Oracle to resolve without violating the ACID principle that is fundamental to RDBMSs - so it refuses. The easiest fixes are to truncate the table before it adds the column OR add the column without the constraint then update the existing rows to what the values should be set to and then add the constraint OR create the column with a default value and the "not null" constraint. 

> The table being modified has 9 rows of data in it.  You cannot add a column with a not null constraint and no default value on it

**Comment by karlitschek** [comment]
I don't understand this problem. No one should manually change db schema of owncloud. Please provide a full bug report as described here
https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by iliyasbasir** [comment]
Here is Comment from customer

```` 
we are not manually changing the owncloud schema. the upgrade process Jen is running is failing when It tries to add a new column to a table with data in it. Oracle refuses and throws the error Jen originally flagged. I looked at the error and checked the table. It has 9 rows of data in it. So Oracle should throw an error and not add the column if you do not provide a default value. Either your upgrade process needs to purge the table or you need to change how you add the column. If you really need to see the upgrade process fail, Jen will have to demonstrate. 
````

**Comment by iliyasbasir** [comment]
Here is screen shot 

![image](https://cloud.githubusercontent.com/assets/10195796/7729538/599862e2-fee3-11e4-895d-1cdf798e0f69.png)

**Comment by iliyasbasir** [comment]
#### Log
Here is an output from the owncloud.log when the update button is hit on the webpage:

s3/Shared/owncloud/support/github-issues/core/16454

**Comment by bboule** [comment]
Hey guys just to be clear (sorry this is a little confusing) it is not the user adding the column, he is pointing out in the narrative that our schema update process is trying to do this and that is why the update is failing.  Just that make more sense?

**Comment by DeepDiver1975** [comment]
> Either your upgrade process needs to purge the table or you need to change how you add the column.

as already explained in another issue - our schema migration mechanism cannot deal with such schema changes on oracle - not nice - but given the current state - no much we can do.

The solution would be (as already done with other customers running oracle) to generate the change script using occ and apply the changes manually to the db. Our update mechanism shall then detect no further changes to be applied and succeed.

**Comment by DeepDiver1975** [comment]
removing milestone as there is nothing we can do from the produc pov

**Comment by MorrisJobke** [comment]
> The solution would be (as already done with other customers running oracle) to generate the change script using occ and apply the changes manually to the db. Our update mechanism shall then detect no further changes to be applied and succeed.

cc @iliyasbasir @gig13

**Comment by MorrisJobke** [comment]
@bboule Ping

**Comment by bboule** [comment]
Please see https://github.com/owncloud/core/issues/16812 I think we are ok here  sorry for the delayed response!!
