### ISSUE TITLE
SFTP external storage doesn't allow to upload files with a white space after url and port.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16457]
### Steps to reproduce

1. Enable external storage app.
2. Mount a SFTP folder using this configuration 'url:port ' don't miss the whitespace, it is the key.
3. Upload files to the folder.

### Expected behaviour
Files are uploaded.

### Actual behaviour
Internal server error.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
```
Enabled:
 - activity: 2.0.0
 - admin_audit: 0.6
 - encryption: 1.0.0
 - enterprise_key: 0.1.0
 - files: 1.1.9
 - files_external: 0.2.3
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.4
 - windows_network_drive: 0.1.1
Disabled:
 - external
 - files_antivirus
 - files_drop
 - files_ldap_home
 - objectstore
 - sharepoint
 - user_external
 - user_ldap
 - user_shibboleth
 - user_webdavauth
```

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
Yes
(But tested also without encryption, same behaviour)

**Logs**
```
{"reqId":"pD8gwT09l+7Xu3X023wE","remoteAddr":"82.159.139.58","app":"PHP","message":"Unsupported operand types at \/opt\/owncloud\/3rdparty\/phpseclib\/phpseclib\/phpseclib\/Net\/SFTP\/Stream.php#175","level":3,"time":"2015-05-20T07:28:23+00:00"}
{"reqId":"2lweGFghTgXevCV8gPCc","remoteAddr":"82.159.139.58","app":"PHP","message":"Unsupported operand types at \/opt\/owncloud\/3rdparty\/phpseclib\/phpseclib\/phpseclib\/Net\/SFTP\/Stream.php#175","level":3,"time":"2015-05-20T07:28:46+00:00"}
{"reqId":"JCIrbKRGf+sPR7eWP\/I2","remoteAddr":"82.159.139.58","app":"PHP","message":"Unsupported operand types at \/opt\/owncloud\/3rdparty\/phpseclib\/phpseclib\/phpseclib\/Net\/SFTP\/Stream.php#175","level":3,"time":"2015-05-20T07:30:50+00:00"}
root@dc0a88784621:/opt/owncloud/data# 
```

### Client configuration

**browser**
Chrome 41, Firefox

**Comment by SergioBertolinSG** [comment]
It is fixed in master, it is just a beta2 problem.

**Comment by Xenopathic** [comment]
What SFTP configuration did you use? It seems likely the problem is with a malformed URL, as the fault at https://github.com/owncloud/3rdparty/blob/master/phpseclib/phpseclib/phpseclib/Net/SFTP/Stream.php#L175 is caused by `parse_url()` returning something other than an array.

cc @bantu

**Comment by SergioBertolinSG** [comment]
Happing in master again.

**Comment by Xenopathic** [comment]
@SergioBertolinSG Could you please post your SFTP configuration? Otherwise there's no way we can help.

**Comment by SergioBertolinSG** [comment]
@Xenopathic you were right, it is a URL malformed. I have a blank space between url: and port 'url: port'
Removing the blank space it worked.

**Comment by SergioBertolinSG** [comment]
So i think the bug is different, having spaces before port makes the connection to work according the green circle, but it doesn't so the circle should be red or remove that whitespaces.

**Comment by Xenopathic** [comment]
So the problem lies in incorrect validation of the URL field, not an actual SFTP problem. Downgrading severity.

**Comment by Xenopathic** [comment]
I cannot reproduce this. The storage works completely with a space before the port (`localhost: 22`), including uploading files.

@SergioBertolinSG Please re-open if you can still reproduce this.

**Comment by SergioBertolinSG** [comment]
I have reproduced this, but the space is after the port:
path: sftp://root@DOMAIN:port /root/SHARED/file.txt

**Comment by schiesbn** [comment]
Probably we need to remove whitespaces at the beginning and the end if we read the users input before we writing it to the config file... Just guessing, didn't looked at the code.

**Comment by PVince81** [comment]
@cmonteroluque Low severity, I suggest moving to 9.0 or backlog

**Comment by SergioBertolinSG** [comment]
This is no longer happening.
