### ISSUE TITLE
Files app can't show thumbnails of BMP pictures

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16461]
### Steps to reproduce

1. Upload BMP files.

### Expected behaviour
there is a thumbnail.

### Actual behaviour
In chrome there is no thumbnail.

![screen shot 2015-05-20 at 10 58 27](https://cloud.githubusercontent.com/assets/9048796/7722312/3638ccdc-fedf-11e4-9613-bba785bd6a9b.png)

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"}

### Client configuration

**browser**
Chrome 41

**Comment by nickvergessen** [comment]
Is this specific to chrome?

**Comment by SergioBertolinSG** [comment]
Yes, not happening in firefox, safari or ie.

**Comment by oparoz** [comment]
I don't get a preview at all with master on PHP 5.5

```
"message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"\\\\OC_Image::_output(): \\\"image\\\/x-ms-bmp\\\" is not supported when forcing a specific output format\",\"Code\":0,\"Trace\":\"#0 lib\\\/private\\\/image.php(193): OC_Image->_output(NULL, 'image\\\/x-ms-bmp')\\n#1 lib\\\/private\\\/preview.php(547): OC_Image->show(NULL)\\n#2 core\\\/ajax\\\/preview.php(61): OC\\\\Preview->showPreview()\\n#3 lib\\\/private\\\/route\\\/route.php(153) : runtime-created function(1): require_once('\\\/home\\\/icloud\\\/do...')\\n#4 [internal function]: __lambda_func(Array)\\n#5 lib\\\/private\\\/route\\\/router.php(272): call_user_func('\\\\x00lambda_97', Array)\\n#6 lib\\\/base.php(862): OC\\\\Route\\\\Router->match('\\\/core\\\/preview.p...')\\n#7 index.php(40): OC::handleRequest()\\n#8 {main}\",\"File\":\"lib\\\/private\\\/image.php\",\"Line\":260}
```

Tested with http://file.fyicenter.com/51_Image_Picture_.BMP_File_Extension_for_Bitmap_Image_Files.html

**Comment by oparoz** [comment]
The funny thing is that if I upload it again to overwrite it, I get previews in the dialogue asking me what I want to do.

**Comment by oparoz** [comment]
@georgehrke Any idea what's killing the filelist thumbnail generator?

**Comment by PVince81** [comment]
Is this still an issue with 8.2 beta ?

**Comment by SergioBertolinSG** [comment]
Yes, still happening.

**Comment by oparoz** [comment]
One possible fix was never merged:
https://github.com/owncloud/core/pull/17754

**Comment by cmonteroluque** [comment]
This issue will fall off 8.2 if not resolved by 6 Oct

**Comment by butonic** [comment]
Anyone interested in fixing this might want to have a look at https://blog.mozilla.org/nnethercote/2015/11/06/i-rewrote-firefoxs-bmp-decoder/ which contains a reference to testimages for the various bmp formats.
