### ISSUE TITLE
Editing a file, clicking on the name in the editor makes New button appear.

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16460]
### Steps to reproduce
1. Log in owncloud
2. Edit a file
3. Click the file name up-lefted.

### Expected behaviour
The 'new button' appears

### Actual behaviour
The 'new button' should not appear. It only happens if you first do the steps just after log in.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity: 1.2.3
 - admin_audit: 0.6
 - encryption: 1.0.0
 - enterprise_key: 0.1.0
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.4
 - user_ldap: 0.6.0
 - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** ActiveDirectory

### Client configuration
**Browser:** Internet Explorer 9

![captura de pantalla 2015-05-20 a las 10 31 23](https://cloud.githubusercontent.com/assets/10596560/7722052/e1fb048e-fedc-11e4-8cfe-2cb6f3476932.png)

**Comment by nickvergessen** [comment]
Wrong repo, reported at files_texteditor: https://github.com/owncloud/files_texteditor/issues/75
