### ISSUE TITLE
LDAP issue: some users can't login on the web, but remote desktop login works

### ISSUE THREAD

**Issue by oandarilho01** [owncloud/core#16476]
### Steps to reproduce
1. RDP session with terminal service works, user can log in
2. Web client login don't. Lost password message issued. Owncloud log register "Invalid credentials" and "Login failed" messages.

### Expected behaviour
Users should be able to login on the web client.

### Actual behaviour
Web client login don't. Lost password message issued. Owncloud log register "Invalid credentials" and "Login failed" messages. I've also noted some "ldap_search(): Partial search results returned: Sizelimit exceeded" messages when browsing LDAP configuration tabs.

### Server configuration
**Operating system**: 
Ubuntu Server 14.04.1 LTS (GNU/Linux 3.13.0-48-generic x86_64)

**Web server:** 
Server version: Apache/2.4.7 (Ubuntu)
Server built:   Mar 10 2015 13:05:59

**Database:**
mysql  Ver 14.14 Distrib 5.5.43, for debian-linux-gnu (x86_64) using readline 6.3

**PHP version:**
PHP 5.5.9-1ubuntu4.9 (cli) (built: Apr 17 2015 11:44:57) 

**ownCloud version:** (see ownCloud admin page)
ownCloud 8.0.2 (stable)

**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
Enabled:
 - activity
 - files
 - files_pdfviewer
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - files_videoviewer
 - gallery
 - templateeditor
 - updater
 - user_ldap
Disabled:
 - external
 - files_encryption
 - files_external
 - files_locking
 - firstrunwizard
 - provisioning_api
 - user_external
 - user_webdavauth

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => '---',
  'trusted_domains' => 
  array (
    0 => 'LOCAL_IP',
    1 => 'FQDN',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://FQDN/',
  'dbtype' => 'mysql',
  'version' => '8.0.2.0',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'log_query' => true,
  'log_level' => 3,
  'maintenance' => false,
  'loglevel' => 1,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes, smb

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Yes, LDAP/ActiveDirectory

#### LDAP configuration (delete this part if not used)
| user_ldap | cleanUpJobOffset                     | 50       
| user_ldap | enabled                              | yes                                                                                       
| user_ldap | installed_version                    | 0.5.0               
| user_ldap | ocsid                                | 166061 
| user_ldap | s01has_memberof_filter_support       | 1    
| user_ldap | s01home_folder_naming_rule           | attr:cn                                                         
| user_ldap | s01last_jpegPhoto_lookup             | 0       
| user_ldap | s01ldap_attributes_for_group_search          
| user_ldap | s01ldap_attributes_for_user_search                   
| user_ldap | s01ldap_backup_host                  |
| user_ldap | s01ldap_backup_port                  |
| user_ldap | s01ldap_base                         | dc=alias,dc=rdp
| user_ldap | s01ldap_base_groups                  | dc=alias,dc=rdp
| user_ldap | s01ldap_base_users                   | dc=alias,dc=rdp 
| user_ldap | s01ldap_cache_ttl                    | 600
| user_ldap | s01ldap_configuration_active         | 1
| user_ldap | s01ldap_display_name                 | displayname                       
| user_ldap | s01ldap_dn                           | owncloud      
| user_ldap | s01ldap_email_attr                   | mail                     
| user_ldap | s01ldap_experienced_admin            | 0 
| user_ldap | s01ldap_expert_username_attr         |
| user_ldap | s01ldap_expert_uuid_group_attr       |
| user_ldap | s01ldap_expert_uuid_user_attr        |  
| user_ldap | s01ldap_group_display_name           | cn  
| user_ldap | s01ldap_group_filter                 | (&(|(objectclass=group))(|(cn=Usuários do domínio)(cn=...)(...)))                                                       
| user_ldap | s01ldap_group_filter_mode            | 1 
| user_ldap | s01ldap_group_member_assoc_attribute | member   
| user_ldap | s01ldap_groupfilter_groups           | SHOWING ONLY ONE GROUP       
| user_ldap | s01ldap_groupfilter_objectclass      | group             
| user_ldap | s01ldap_host                         | AD_IP
| user_ldap | s01ldap_login_filter                 | (&(|(memberof=CN=Usuários do domínio,CN=Users,DC=alias,DC=rdp)(memberof=CN=...,OU=grupos,DC=alias,DC=rdp)(...))(|(samaccountname=%uid)(|(whenCreated=%uid)))) 
| user_ldap | s01ldap_login_filter_mode            | 1 
| user_ldap | s01ldap_loginfilter_attributes       | whenCreated   
| user_ldap | s01ldap_loginfilter_email            | 0 
| user_ldap | s01ldap_loginfilter_username         | 1 
| user_ldap | s01ldap_nested_groups                | 0  
| user_ldap | s01ldap_nocase                       | 0 
| user_ldap | s01ldap_override_main_server         | 0 
| user_ldap | s01ldap_paging_size                  | 500  
| user_ldap | s01ldap_port                         | 389  
| user_ldap | s01ldap_quota_attr                   |  
| user_ldap | s01ldap_quota_def                    |   
| user_ldap | s01ldap_tls                          | 0   
| user_ldap | s01ldap_turn_off_cert_check          | 0  
| user_ldap | s01ldap_user_filter_mode             | 1  
| user_ldap | s01ldap_userfilter_groups            | SHOW ALL THE GROUPS
| user_ldap | s01ldap_userfilter_objectclass       |   
| user_ldap | s01ldap_userlist_filter              | (|(memberof=CN=Usuários do domínio,CN=Users,DC=alias,DC=rdp)(memberof=CN=...,OU=grupos,DC=alias,DC=rdp)) 
| user_ldap | types                                | authentication     

### Client configuration
**Browser:**
Google Chrome Version 43.0.2357.45 beta (64-bit)
Mozilla Firefox 38.0.1

**Operating system:**
Gentoo Linux (but users on windows 7 and 8 can't login too)

#### Web server error log
(can't see anything related)

#### ownCloud log (data/owncloud.log)
{"reqId":"fce4b5f10ee04f23605503498bf3a37d","remoteAddr":"CLIENT_IP","app":"user_ldap","message":"Bind failed: 49: Invalid credentials","level":3,"time":"2015-05-20T12:09:35+00:00"}
{"reqId":"fce4b5f10ee04f23605503498bf3a37d","remoteAddr":"CLIENT_IP","app":"core","message":"Login failed: 'USER' (Remote IP: 'CLIENT_IP', X-Forwarded-For: '')","level":2,"time":"2015-05-20T12:09:35+00:00"}

#### Browser log
(don't know how to get it right now)

**Comment by karlitschek** [comment]
hmm. i think there might be a misconfiguration in your own cloud ldap config.

**Comment by oandarilho01** [comment]
Hi, karlitschek.
I'm trying to figure it out, but it's keeping hard.
I checked and a new user, created after the one is having problem, and included in the same group can perfectly log in.

**Comment by blizzz** [comment]
@oandarilho01 do you still face the issue? if so, did you retry with 8.1 or 8.2?

**Comment by blizzz** [comment]
Closed for inactivity
