### ISSUE TITLE
Open documentation buttons do not appear in admin menu using Internet explorer 9

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16477]
### Steps to reproduce
1. Using IE9 browser, go to admin menu

### Expected behaviour
The Open documentation buttons 'i' should appear.

### Actual behaviour
No button appears.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** "version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity: 1.2.3
 - admin_audit: 0.6
 - encryption: 1.0.0
 - enterprise_key: 0.1.0
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.4
 - user_ldap: 0.6.0
 - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** ActiveDirectory

### Client configuration
**Browser:** Internet Explorer 9

![captura de pantalla 2015-05-20 a las 17 36 54](https://cloud.githubusercontent.com/assets/10596560/7730159/e42801c6-ff18-11e4-92cd-4cc4fe916225.png)

**Comment by davitol** [comment]
@jancborchardt Maybe is the for the same reason as  #16409 ?

**Comment by MorrisJobke** [comment]
@jancborchardt Do you want to have a look at this?

**Comment by DeepDiver1975** [comment]
Can anybody please retest this with the current code base as of master? THX

**Comment by MorrisJobke** [comment]
> Can anybody please retest this with the current code base as of master? THX

I will do this

**Comment by MorrisJobke** [comment]
Used 8.1.0beta2:

![bildschirmfoto von 2015-06-16 15-54-25](https://cloud.githubusercontent.com/assets/245432/8184718/39b03848-1440-11e5-8c94-24f150a4ce13.png)


Works here.

**Comment by MorrisJobke** [comment]
I used the tar ball for this screenshot. But it works on master too.

**Comment by MorrisJobke** [comment]
@davitol Can you still reproduce? Otherwise I would close this.

**Comment by DeepDiver1975** [comment]
> @davitol Can you still reproduce? Otherwise I would close this.

@jnfrmarks @SergioBertolinSG for overall qa coordination - THX

**Comment by davitol** [comment]
:+1: Fixed in master
