### ISSUE TITLE
Files are not shared using federated-sharing between ownclouds of different versions

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16474]
### Steps to reproduce
1. Enable option Allow users on this server to send shares to other servers
2. Send a file to a user of another server

### Expected behaviour
The file in server B should appear

### Actual behaviour
User in server A has the shared notification in his file.
User in server B accepts the sharing but the file never appears.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** "version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise" and 
"version":"8.1.0.2","versionstring":"8.1 alpha 1","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity: 1.2.3
 - admin_audit: 0.6
 - encryption: 1.0.0
 - enterprise_key: 0.1.0
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.4
 - user_ldap: 0.6.0
 - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** ActiveDirectory

### Client configuration
**Browser:** Internet Explorer 9 & Firefox

![captura de pantalla 2015-05-20 a las 17 19 00](https://cloud.githubusercontent.com/assets/10596560/7729352/aaece6aa-ff14-11e4-97cb-aedca7a3b1a0.png)

![captura de pantalla 2015-05-20 a las 17 20 24](https://cloud.githubusercontent.com/assets/10596560/7729348/a0b7b89a-ff14-11e4-98d8-85d87063fe1e.png)

**Comment by davitol** [comment]
@PVince81 ?

**Comment by PVince81** [comment]
I don't think it's valid to test against older alpha versions as they might be broken and are not a valid deployment scenario.

However testing 8.1 (latest) connecting to 8.0 and the other way around makes sense.

**Comment by davitol** [comment]
Tested again between 8.1 and 8.0.3 and it works. :+1:
