### ISSUE TITLE
File restore from trash to ext storage appears twice in web UI

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#16475]
### Steps to reproduce
1. Enable encryption + default encryption module
2. Log out, log in
3. Enable external storage
4. Mount a SFTP storage under "/sftp"
5. Create a folder "/sftp/enc".
6. Create a file "/sftp/enc/test.txt"
7. Edit and save the file several times to create versions
8. Delete the folder "/sftp/enc" to trash
9. Restore the folder "enc" from trash
10. Check the contents of "/sftp/enc" in the web UI

### Expected result
"test.txt" appears once.

### Atcual result
"test.txt" appears **twice** in the web UI.
Strangely oc_filecache only has a single entry for "test.txt"

### Versions
ownCloud 8.1 git master 39d1e99228a22e232795b9800503697b866f5023

**Comment by PVince81** [comment]
Very strange: I checked with the DOM inspector and found that the entries have a different file id: 20 and 55.
I checked the database:
```
MariaDB [owncloud]> select * from oc_filecache where fileid in (20,55);
+--------+---------+-----------------------------------------------+----------------------------------+--------+----------+----------+----------+------+------------+---------------+-----------+------------------+---------------+-------------+
| fileid | storage | path                                          | path_hash                        | parent | name     | mimetype | mimepart | size | mtime      | storage_mtime | encrypted | unencrypted_size | etag          | permissions |
+--------+---------+-----------------------------------------------+----------------------------------+--------+----------+----------+----------+------+------------+---------------+-----------+------------------+---------------+-------------+
|     20 |       1 | files_trashbin/files/enc.d1432135538/test.txt | 2941ec723169e852c02b1733a4d930e8 |     19 | test.txt |        4 |        3 |   11 | 1432135569 |    1432135569 |         1 |                0 | 555ca79173816 |          27 |
|     55 |       3 | enc/test.txt                                  | 1ed4066eced7f3c94794f1eadcd61784 |     19 | test.txt |        4 |        3 |   11 | 1432135569 |    1432135569 |         1 |                0 | 555ca79179fc6 |          27 |
+--------+---------+-----------------------------------------------+----------------------------------+--------+----------+----------+----------+------+------------+---------------+-----------+------------------+---------------+-------------+
```

One of the entry is from the the trashbin ?!

However, on disk the "files_trashbin" folder is empty.
So there are two issues here:
1) The cache entry for the restore trashbin entry has not been deleted properly
2) Some weird bug is showing cache entries from the trashbin in the regular files view!

**Comment by SergioBertolinSG** [comment]
Reproduced using 8.1.0.6

**Comment by PVince81** [comment]
Ok I found something: when calling `getFolderContentsById()` we use the "parent" field.
And as you can see in the file cache entries above, they BOTH have the same "parent" value.

Something went wrong between cross-storage move. It seems we missed to update the "parent" field.

CC @icewind1991

**Comment by PVince81** [comment]
I'll try and debug this to find the exact location

**Comment by PVince81** [comment]
Upgrading to "critical", because such cache inconsistencies could have nasty side effects

**Comment by PVince81** [comment]
This is NOT related to the last change that makes the trashbin use storage instead of view. Also happens before that.

**Comment by PVince81** [comment]
I see it's using "$view->rename()" => "moveFromStorage()" which will then call "copyFromStorage()".
And the latter does a "copy" followed by "rmdir".

The big is that "rmdir" will retrigger "move2trash". So instead of deleting the trash entry... it will move the trash entry to trash...

**Comment by PVince81** [comment]
and this smells like a concat issue, calling move2trash with this:
```
$filesPath                       = (string[31]) '_trashbin/files/def.d1432137262';
```

**Comment by PVince81** [comment]
Arghhhh, getRelativePath() is so dumb with missing leading/trailing slashes.
I'll try and fix it once for all (with unit tests)

**Comment by PVince81** [comment]
Easier said than done... Forcing fakeRoot to have leading and trailing slash seems to break other things... Raised here https://github.com/owncloud/core/issues/16478 as it seems to be too dangerous.

I'll try limit the fix to getRelativePath for the obvious case. More extensive fix to be done in https://github.com/owncloud/core/issues/16478.

**Comment by PVince81** [comment]
First stage of the fix: https://github.com/owncloud/core/pull/16479
This prevents moving the trashed folder back to trash.

But it seems it's not enough, the cache entries in the trashbin are still not deleted properly.

**Comment by PVince81** [comment]
I think I'm onto something: the folder that appears in trash in the filecache has the mime type "application/octet-stream" instead of being a folder. So the moveFromCache operation doesn't move all its children.

Now to find why the mime type is wrong.

**Comment by PVince81** [comment]
Ok here it is: https://github.com/owncloud/core/blob/master/lib/private/files/cache/updater.php#L185

It calls `$sourceStorage->getMimeType($targetPath)` which basically asks the SFTP storage to tell us the mime type of a file that is on another storage. `getMimeType()` calls `is_dir` which obviously fails since the directory doesn't exist on the source storage any more.

I'll see if I can fix it by doing `$targetStorage->getMimeType($targetPath)` instead.

**Comment by PVince81** [comment]
Works! I'll submit a PR and add unit tests.

**Comment by cmonteroluque** [comment]
thanks @PVince81

**Comment by PVince81** [comment]
This issue can also happen when moving a folder cross-storage and changing its "extension": move "/test_folder" to "/sftp/test_folder.someext".
Changing the extension will trigger mimetype detection which will mess up.

Ideally mimetype detection should not be triggered if it was a folder anyway.

**Comment by PVince81** [comment]
The reason why it's triggered for the trashbin is because a deleted folder will have the name "folder.d123456" (with the numbers being the timestamp)

**Comment by PVince81** [comment]
PR is here: https://github.com/owncloud/core/pull/16493

**Comment by PVince81** [comment]
This issue does not exist on OC 8.0.x as `moveFromCache` didn't exist there, so no backport needed.

**Comment by PVince81** [comment]
Fixed by https://github.com/owncloud/core/pull/16493
