### ISSUE TITLE
Share a folder to a user at a specified path

### ISSUE THREAD

**Issue by fxshpac** [owncloud/core#16472]
I found out that I can share a folder to another user using pyocclient command line tool which is cool. However, the current behavior is that whenever a folder is shared to that user, the folder shows up at root level of that user's file view. So i have to manually login as that user and move the folder to the specified path which will then get synced across to that user. Is there a command which can allow me to specify target path when sharing a folder? This will combine the two-step procedure into one.

Thanks in advance

**Comment by RealRancor** [comment]
Hi,

the default behavior is that new files and folders are always ending up in the root folder. This can be overwritten globally in your config.php:

https://github.com/owncloud/core/blob/v8.0.3/config/config.sample.php#L768-L771

P.S. Normally this is a question which is better placed at the forums or the users mailinglist.

**Comment by fxshpac** [comment]
@RealRancor thx a lot for your response and that explains the behavior I'm seeing. I think the reason I post here is to propose an enhancement in Sharing API to allow dynamic target path which can be picked at the time of sharing instead of using the path set in config.php. Changing the path in config.php may work but I don't want to touch that file since it has its global impact. Hope you can consider supporting that functionality in the next API revisions. Thx

**Comment by rullzer** [comment]
I do not see this happening in the near future.
Giving somebody else control over how my files are organized seems like something most users do not want.

**Comment by PVince81** [comment]
I agree with @rullzer.

Also I can see potential security issues where a hacker would use such shares to try and guess the directory structure of the target user.

But also, the sharer has no way to know what directory structure the target user has so it is never guaranteed whether the target folder exists there.

**Comment by LukasReschke** [comment]
Agreed with @rullzer and @PVince81.

**Comment by PVince81** [comment]
Closing as won't fix.

@fxshpac you might want to share more details about your use case in case there would be other alternatives.
