### ISSUE TITLE
Fix various path issues with Views

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#16478]
Currently the View accepts an arbitrary $root, and concatenates it with other paths, sometimes without checking if there is a leading or trailing slash.

The common way we used was to create a view with `new View('/somepath/')` with both leading and trailing slashes. That usually works for everything.

I tried to quickfix this and enforce leading+trailing slash, but that seems to break autotest setup ?!

So instead of doing such dangerous fix directly, let's do this in a later release.

The idea is to normalize fakeRoot to have the proper slashes to avoid breakage.

CC @icewind1991 @DeepDiver1975 @schiesbn

**Comment by PVince81** [comment]
Setting to high. This has been the source of many recent troubles, some which involved data loss...

**Comment by PVince81** [comment]
From what I see currently is that the method "getRelativePath" results is unpredictable. Sometimes it will provide leading slashes, sometimes not. We need to make this consistent.

- [ ] enforce fakeRoot format
- [ ] fir getRelativePath to return sane and consistent results

**Comment by PVince81** [comment]
and the trouble is that some pieces of ownCloud depend on the "bad" behavior of these (like assuming that the response has a leading slash), so we cannot simply change and make them consistent without risks of breakage.

**Comment by PVince81** [comment]
This is even worse than I thought, I just discovered this:
When calling `Filesystem::getView()` it delivers a view that has the root "$user/files" (no trailing slash).
So if such a view is used with $view->getRelativePath('files_trashbin') it will return '_trashbin' because of the missing trailing slash. (this is what happens here https://github.com/owncloud/core/issues/16475)

And the worse part is that we cannot fix it reliably without causing side effects, so would need a full regression test.

**Comment by oparoz** [comment]
Thank goodnesss for that... It's really a pain to work with, especially when trying to use one function for both private and public files...

**Comment by PVince81** [comment]
- [ ] fix chroot to be consistent with the test, or even better: get rid of it!

**Comment by PVince81** [comment]
Side: the even more unfunny thing about the View's root is that the hooks firing logic depends on it. Basically if the View's root is "$user/files" then hooks will fire. However if the root is "/" but you touch a file inside "$user/files", it will not fire hooks either...

**Comment by PVince81** [comment]
- [ ] fix getAbsolutePath to auto-normalize output instead of doubling slashes...

**Comment by PVince81** [comment]
- [ ] fix getPath() signature to properly throw exceptions https://github.com/owncloud/core/pull/16957 for invalid paths instead of null

**Comment by LukasReschke** [comment]
- [ ] fix `getFileInfo` signature to properly throw exceptions for invalid paths instead of null

**Comment by PVince81** [comment]
- [ ] fix getInternalPath() in various places (MountPoint) to throw an exception if the path did not match

**Comment by PVince81** [comment]
dangerous territory, and unfortunately a risk to touch that past feature freeze => 9.0

**Comment by PVince81** [comment]
Past feature freeze again :frowning: => 9.1

**Comment by PVince81** [comment]
CC @cmonteroluque

**Comment by PVince81** [comment]
Risky, moving to 9.2.

Note that some fixes were made to internalPath and helped fix some issues.

**Comment by PVince81** [comment]
more details in this duplicate https://github.com/owncloud/core/issues/13887

**Comment by PVince81** [comment]
So far no new issues have popped up.

Will likely require a few days because it needs to find and fix all occurrences of View.
Last time I tried there were lots of test failures.

**Comment by PVince81** [comment]
estimate 2-5 md depending on how unlucky the dev is
