### ISSUE TITLE
File permissions to $datadirectory set to o-rx by cron.php - why?

### ISSUE THREAD

**Issue by DrSAR** [owncloud/core#16483]
I am exporting the `$datadirectory` as NFS share to other computers so that I can have a direct access to the files in the storage. This depends to some degree on certain permissions being set on those directories and it appears that `cron.php` cheerfully messes with them every 15min.

Is there a good reason not too have world-readability on `$datadirectory` (I am switching to `o-rx` for subdirectories, I export only part of `$datadirectory` via NFS)? How can I get `cron.php` to leave it at `o+rx`?

**Comment by MorrisJobke** [comment]
cc @LukasReschke @icewind1991

**Comment by DeepDiver1975** [comment]
@DrSAR this is where we set the permissions - https://github.com/owncloud/core/blob/master/lib/private/util.php#L840

Feel free to adopt this to your personal needs - currently I see no reason to adopt out code base.

THX
