### ISSUE TITLE
User Already Exists Error

### ISSUE THREAD

**Issue by 19kestier** [owncloud/core#16487]
When I try to create a user in ownCloud, it says that the user already exists, when it clearly doesn't. Screenshot of JS Console below.
![screenshot 2015-05-20 at 8 48 45 pm](https://cloud.githubusercontent.com/assets/4749568/7739605/dd7fb0da-ff31-11e4-8cf9-bc97edc46ebe.png)

**Comment by RealRancor** [comment]
Hi,

please disable the user_webdavauth (Webdav user backend) app.

**Comment by nickvergessen** [comment]
Closing as per the link above.

**Comment by nickvergessen** [comment]
PS: @carlaschroder is that something we want to add to the documentation? Or is an FAQ entry on the forum already enough?

**Comment by RealRancor** [comment]
@nickvergessen 
The app description is currently also saying:

> This app is not the webdav interface of ownCloud, if you don't understand what it does then do not enable it.

From my PoV the FAQ and the app description should be enough but regardless those such reports are coming up quite often.

**Comment by carlaschroder** [comment]
I'll take a look at this, thanks for the information.

**Comment by RealRancor** [comment]
> such reports are coming up quite often

Another one: https://github.com/owncloud/core/issues/16602

**Comment by nickvergessen** [comment]
@RealRancor btw since the feature is completly useless in case when an external user backend is active, should we just hide it in that case?

**Comment by RealRancor** [comment]
I don't have any insights in the external user backends available for oC so i can't answer this question. :-/

**Comment by MorrisJobke** [comment]
For 8.2 it is included into user external. I think this solves this ticket: https://github.com/owncloud/apps/pull/2106
