### ISSUE TITLE
Menu click events don't bubble up

### ISSUE THREAD

**Issue by Henni** [owncloud/core#16485]
### Steps to reproduce
1. Try clicking on the text Settings in the file app
or
1. Try clicking on the right side of a navigation item with a menu as described in the [css documentation](https://doc.owncloud.org/server/8.0/developer_manual/app/css.html#menus)

### Expected behaviour
The clicked section should be activated / opened

### Actual behaviour
Nothing happens. It seems like the event doesn't bubble up to the navigation item.

### Client configuration
**Browser:**
Chrome 43

**Operating system:**
Ubuntu 14.04

#### ownCloud log (data/owncloud.log)
```
nothing specific to this issue
```

#### Browser log
```
nothing special
```

**Comment by Henni** [comment]
The problem with the settings text was fixed by #16893.
The issue with navigation items still exists.

**Comment by jancborchardt** [comment]
@PVince81 @MorrisJobke any input here?

**Comment by PVince81** [comment]
@Henni is this still happening on OC 9.0 ? I seem to remember that @nickvergessen fixed something related to menu event bubbling

**Comment by PVince81** [comment]
If it still happens in 9.0.2, please reopen.
