### ISSUE TITLE
Add to your ownCloud button does not work in IE9, when sharing a file by link

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16489]
### Steps to reproduce
1. Enable option Allow users on this server to send shares to other servers
2. Share a file by link
3. Paste the link in IE9 browser and click on Add to your ownCloud button

### Expected behaviour
The button should let you add the file

### Actual behaviour
The button throws an error

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** "version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity: 1.2.3
 - admin_audit: 0.6
 - encryption: 1.0.0
 - enterprise_key: 0.1.0
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.4
 - user_ldap: 0.6.0
 - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** ActiveDirectory

### Client configuration
**Browser:** Internet Explorer 9
![captura de pantalla 2015-05-21 a las 9 17 38](https://cloud.githubusercontent.com/assets/10596560/7743423/e5559f5e-ff9a-11e4-96ad-a578f0d7fd5d.png)

**Comment by PVince81** [comment]
@oparoz looks like btoa is not supported in IE9 ?
There might be a workaround: http://stackoverflow.com/questions/18508582/alternative-btoa-encoding-in-internet-explorer

Do you want to take care of it or should I ?

**Comment by oparoz** [comment]
I see potentially 2 problems here:
* The text preview doesn't show up
* Add to ownCloud doesn't work

The use of btoa could be the reason the preview doesn't show up, but that would need to be confirmed by @davitol 

Now, regarding the 2nd point, I don't think this has anything to do with the previews or am I wrong @PVince81 ?

**Comment by PVince81** [comment]
@oparoz good point. I got blinded by the JS error.

But still, sometimes a single JS error will throw out and prevent subsequent Javascript to be executed. In this case, it might prevent the event handler to be registered on the button.

**Comment by PVince81** [comment]
Well, not "subsequent" but code that appears after the line that failed.
If the event handler was register before that failure, then it should work.

**Comment by PVince81** [comment]
@davitol works for me when sharing a folder in IE9, but I didn't share a text file.

When sharing a text file, the button is indeed broken.

I'll try and provide a replacement for btoa then.

**Comment by PVince81** [comment]
Damn, it looks like we don't have jquery.base64, which means we'd need a new dependency.

**Comment by oparoz** [comment]
Or disable support for text previews on irrelevant browsers? You can't have all the goodies on ancient technologies.

How do you generate the authorisation headers in other areas? Because the only reason we need btoa is for that.

**Comment by PVince81** [comment]
No idea... I guess other people might use jquery.base64 then. But from my experience adding deps to core is never met with open arms.

We could disable text preview in IE <= 9. But I'm pretty sure someone will raise a separate ticket for this too at some point.

Falling back to the picture preview is probably not an option, right ? (if I remember well it didn't look good)

**Comment by PVince81** [comment]
Oh, what the hell. I'll make it fallback to the picture preview now.

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/16607

**Comment by davitol** [comment]
:+1:
