### ISSUE TITLE
Unify icon style

### ISSUE THREAD

**Issue by Henni** [owncloud/core#16484]
The icons described at
https://doc.owncloud.org/server/8.0/developer_manual/app/css.html#icons
should be unified as there are black, grey, white and detailed version of icons.

@jancborchardt probably an issue for you

**Comment by jancborchardt** [comment]
Yup! I want to unify them to black with 50% opacity. Currently this is done in CSS but that’s not a good idea as it leads to inconsistencies when people use the black version.

**Comment by plastelina** [comment]
Quick question, what would you say to unify all the icons so they look consistent (shape as well as @jancborchardt mentioned colour). I'm happy to go through the whole list and create them, then save them as png or svg or whatever format needed as well as prepare a document that could be updated with new once as we go). So we could have open source design own set of icons as in http://line25.com/wp-content/uploads/2013/icons/16.jpg rather then having mismatch os styles/colours?

**Comment by jancborchardt** [comment]
@plastelina if you’re interested in doing that, that’d be pretty awesome! :) Basically what I think needs to be done:
* [ ] most of them changed to black with 50% opacity (except the white ones because they are for the detail view)
* [ ] most of them changed to 16*16px as most already are (except the white ones because they need to be slightly bigger for the detail view) – star and eye-toggle are notably different
* [ ] merge the »actions« and »places« folders into one »icons« folder
* the shape is good on almost all of them, pixel perfect and handmade. Maybe some of them need to be adjusted.

What do you think @plastelina? We need all the icons in both SVG and PNG (png because of IE8 fallback) and compressed. (A future step would be to put them in a sprite, but that’s separate – see https://github.com/owncloud/core/issues/15531 )

@plastelina you’re also very welcome in our IRC channel #owncloud-design :)

**Comment by jsimplicio** [comment]
Hey all and @jancborchardt, found this issue and started making the icons like@plastelina suggested she would. I made a couple and just wanted some feedback or if you think I should continue.

Here they are:
![add](https://cloud.githubusercontent.com/assets/7318958/12705467/0df5a88a-c838-11e5-8f3e-9db72dfaba4e.png)![bread crumbs](https://cloud.githubusercontent.com/assets/7318958/12705471/0e0f178e-c838-11e5-9be8-75d18bd268f8.png)![caret](https://cloud.githubusercontent.com/assets/7318958/12705472/0e133c60-c838-11e5-8240-35da7651321f.png)![checkmark](https://cloud.githubusercontent.com/assets/7318958/12705470/0e0c7d80-c838-11e5-9ba9-c6a81c470f08.png)![clock](https://cloud.githubusercontent.com/assets/7318958/12705468/0e069b68-c838-11e5-990f-c16b527993ad.png)![close](https://cloud.githubusercontent.com/assets/7318958/12705474/0e1844e4-c838-11e5-8be8-05706fa8c324.png)![confirm](https://cloud.githubusercontent.com/assets/7318958/12705469/0e06b12a-c838-11e5-9876-8d64f95421d2.png)![delete](https://cloud.githubusercontent.com/assets/7318958/12705473/0e1749cc-c838-11e5-9353-d885f738982b.png)![download](https://cloud.githubusercontent.com/assets/7318958/12705475/0e18de90-c838-11e5-9cfd-4c262ecb6d5b.png)![history](https://cloud.githubusercontent.com/assets/7318958/12705476/0e1c18d0-c838-11e5-801d-775a7304a035.png)![info](https://cloud.githubusercontent.com/assets/7318958/12705477/0e2914fe-c838-11e5-9fbe-21a67fdee200.png)![lock](https://cloud.githubusercontent.com/assets/7318958/12705478/0e2a9f04-c838-11e5-8a1a-4e5a0a45ba0e.png)![logout](https://cloud.githubusercontent.com/assets/7318958/12705480/0e2d7454-c838-11e5-9020-355b98d364f9.png)![spinner](https://cloud.githubusercontent.com/assets/7318958/12705479/0e2c5ce0-c838-11e5-8044-9da4bc9d9bc6.png)

**Comment by jsimplicio** [comment]
They still need adjustments this was a quick run. Some shapes are too thin or thick (depends how you look at it) compared to the overall look so I'd go ahead and make those adjustments

**Comment by jsimplicio** [comment]
Okay had a relaxing evening and evened out some of the thickness discrepancies...some work in progress

![add](https://cloud.githubusercontent.com/assets/7318958/12708746/e362b0d2-c868-11e5-9cc4-d779c20d4d52.png)![bread crumbs](https://cloud.githubusercontent.com/assets/7318958/12708751/e380e05c-c868-11e5-93c6-6bee2ccc51ea.png)![caret](https://cloud.githubusercontent.com/assets/7318958/12708750/e37aa192-c868-11e5-9371-0e58a5d470d6.png)![checkmark](https://cloud.githubusercontent.com/assets/7318958/12708748/e375409e-c868-11e5-8d10-735d1396c19b.png)![clock](https://cloud.githubusercontent.com/assets/7318958/12708749/e378c69c-c868-11e5-9fd2-330c9bbb61ac.png)![close](https://cloud.githubusercontent.com/assets/7318958/12708752/e380f4b6-c868-11e5-865c-46a1e8b9ab64.png)![confirm](https://cloud.githubusercontent.com/assets/7318958/12708747/e37484b0-c868-11e5-8e14-8eaf4a219bde.png)![delete](https://cloud.githubusercontent.com/assets/7318958/12708753/e38442ec-c868-11e5-8172-2b7660d80cfd.png)![download](https://cloud.githubusercontent.com/assets/7318958/12708754/e3844bfc-c868-11e5-8826-d1cdf89bc91a.png)![history](https://cloud.githubusercontent.com/assets/7318958/12708755/e38a6cee-c868-11e5-9b13-73a2894ca03e.png)![info](https://cloud.githubusercontent.com/assets/7318958/12708756/e38c55fe-c868-11e5-82a6-26233d70412f.png)![lock](https://cloud.githubusercontent.com/assets/7318958/12708757/e390975e-c868-11e5-8673-41a329765c8d.png)![logout](https://cloud.githubusercontent.com/assets/7318958/12708758/e3925cd8-c868-11e5-98ce-84c7c588e605.png)![spinner](https://cloud.githubusercontent.com/assets/7318958/12708759/e397bda4-c868-11e5-9fa2-1712d866142f.png)

**Comment by jsimplicio** [comment]
here are some more. These are all 24px at least, I know in some instances they are usually smaller like I noticed the play buttons. But could def be shrunk in svg if needed to be half size up or down.
![pause](https://cloud.githubusercontent.com/assets/7318958/12709440/bbb638ca-c871-11e5-8949-ef66efd7d9a9.png)
![play add](https://cloud.githubusercontent.com/assets/7318958/12709443/bbcbf75a-c871-11e5-96d6-a2f3d46163e7.png)
![play next](https://cloud.githubusercontent.com/assets/7318958/12709445/bbd208fc-c871-11e5-8eb3-07a3eb917b1b.png)
![play previous](https://cloud.githubusercontent.com/assets/7318958/12709444/bbce6152-c871-11e5-8674-baa9a3a09357.png)
![play](https://cloud.githubusercontent.com/assets/7318958/12709446/bbd3c57a-c871-11e5-8701-2cf7350f57be.png)
![rename](https://cloud.githubusercontent.com/assets/7318958/12709442/bbc9a7ac-c871-11e5-928b-fb1c7068c5f4.png)
![search](https://cloud.githubusercontent.com/assets/7318958/12709441/bbc6d608-c871-11e5-9eae-91162459719e.png)
![settings](https://cloud.githubusercontent.com/assets/7318958/12709447/bbd7e25e-c871-11e5-883b-a0b665734921.png)
![share](https://cloud.githubusercontent.com/assets/7318958/12709448/bbdadfa4-c871-11e5-8fce-8543e749f2ae.png)
![shared](https://cloud.githubusercontent.com/assets/7318958/12709449/bbdf7d0c-c871-11e5-9a0d-0f4a555f40e3.png)

**Comment by jancborchardt** [comment]
Hej @jsimplicio – sorry for the late answer, was snowboarding all of last week! :)

Awesome for taking this up! As mentioned above (https://github.com/owncloud/core/issues/16484#issuecomment-104283264 ), I would prefer if the forms would stay as they are in the first run, and mainly sizing and color to be adjusted. That way the first change is a »backend« change only and doesn’t have visual implications. After that we can think about any form changes. Does that sound good?

**Comment by jancborchardt** [comment]
By the way @jsimplicio you are very welcome in our IRC channel #owncloud-designers (on freenode) if you use IRC. :)

**Comment by jsimplicio** [comment]
Hey. I joined the channel. Thanks! I was wondering what you suggest me do if you want to keep the form. What necessarily needs to be done? Will I need their file ?

**Comment by jancborchardt** [comment]
Basically the points I mentioned before: https://github.com/owncloud/core/issues/16484#issuecomment-104283264

And as you know all the source files are at https://github.com/owncloud/core/tree/master/core/img :)

**Comment by jsimplicio** [comment]
Do I make these changes to all icons even the ones inside folders? For example to change them to black with 50% opacity. Some of them are in color.

**Comment by jancborchardt** [comment]
@jsimplicio I would suggest starting with just the `core/img/actions` folder, and doing it step by step. For example all in the file actions dropdown (rename, details, download, share, delete etc). And making sure they still look right everywhere they are used.

The colored ones should stay full opacity since they are a special state.

**Comment by jsimplicio** [comment]
Ah I understand. I've yet to set up ownCloud because am trying to figure out how I can go about serving it. But once I do I can get started on this

**Comment by jancborchardt** [comment]
@jsimplicio cool! It’s quite simple to set up ownCloud on your own laptop: https://doc.owncloud.org/server/9.0/developer_manual/general/devenv.html – please let me know if there’s problems at any point, so then we can improve the process. .)

**Comment by jsimplicio** [comment]
I need Linux?

**Comment by Henni** [comment]
Owncloud requires Linux on the server side (see [System Requirements](https://doc.owncloud.org/server/9.0/admin_manual/installation/system_requirements.html#supported-platforms) ).
Try running it in a virtual machine ([Virtual Box](https://www.virtualbox.org))

**Comment by PVince81** [comment]
@felixheidecke
