### ISSUE TITLE
Invalid storage advice does not dissapear.

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16495]
### Steps to reproduce
1. Enable option Allow users on this server to send shares to other servers
2. Share a folder by link
3. Unshare the folder
4. Open the fodler in server B

### Expected behaviour
The  advice error should dissapear after surfing the web

### Actual behaviour
The  advice error should keeps until the screen is refreshed

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** "version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity: 1.2.3
 - admin_audit: 0.6
 - encryption: 1.0.0
 - enterprise_key: 0.1.0
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.4
 - user_ldap: 0.6.0
 - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** ActiveDirectory

### Client configuration
**Browser:** Internet Explorer 9

![captura de pantalla 2015-05-21 a las 10 55 21](https://cloud.githubusercontent.com/assets/10596560/7745234/dce4f61c-ffa9-11e4-9133-0693fa6b49c2.png)

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/19634
