### ISSUE TITLE
Sharing a folder by link, it is not possible to get into the folder after sharing it

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16490]
### Steps to reproduce
1. Enable option Allow users on this server to send shares to other servers
2. Share a folder by link
3. Click in the folder once it has been shared (in server B)

### Expected behaviour
The folder is opened

### Actual behaviour
Nothing happens. It is necessary to log out and log in to open the folder

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** "version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity: 1.2.3
 - admin_audit: 0.6
 - encryption: 1.0.0
 - enterprise_key: 0.1.0
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.4
 - user_ldap: 0.6.0
 - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** ActiveDirectory

### Client configuration
**Browser:** Mozilla Firefox 38

![captura de pantalla 2015-05-21 a las 10 07 05](https://cloud.githubusercontent.com/assets/10596560/7744338/b551659c-ffa2-11e4-9006-65203b1913af.png)

**Comment by PVince81** [comment]
Works for me, I tried the following:
1. Login in server A
2. Create a folder "test"
3. Share "test" with link
4. Click "test" to enter it: works
5. Log out
6. Open the link
7. Click "Add to ownCloud", enter the URL of server B
8. Login in server B
9. Accept the share
10. Click "test" to enter it: works
11. Go back
12. Share "test" again with link
13. Click "test" to enter it: works

@davitol can you provide more detailed steps, especially to make it clear what happens on server A and server B ? Thanks.

**Comment by davitol** [comment]
@PVince81 In my lastest test it seems to work fine. I close the issue and if it happens again I reopen it and comment
