### ISSUE TITLE
Uploading of files ~50MiB using cadaver gets stucked.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16494]
### Steps to reproduce

1. Using [cadaver](http://www.webdav.org/cadaver/) upload a 50 MiB file.

### Expected behaviour
File is uploaded.

### Actual behaviour
File gets stucked while uploading.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
```
Enabled:
 - activity: 2.0.0
 - admin_audit: 0.6
 - encryption: 1.0.0
 - enterprise_key: 0.1.0
 - files: 1.1.9
 - files_external: 0.2.3
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.4
 - windows_network_drive: 0.1.1
Disabled:
 - external
 - files_antivirus
 - files_drop
 - files_ldap_home
 - objectstore
 - sharepoint
 - user_external
 - user_ldap
 - user_shibboleth
 - user_webdavauth
```

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
Yes
(But tested also without encryption, same behaviour)

**Logs**
```

```

### Client configuration

**browser**
Chrome 41, Firefox

**Comment by PVince81** [comment]
Works for me with a file that has 121 MB.

Is this uploading as owner or as recipient into a shared folder ?

Maybe there's an env issue on the daily server ?

**Comment by SergioBertolinSG** [comment]
Not shared folder, just uploading into root.

**Comment by PVince81** [comment]
I tested with cadaver against the same server and could successfully upload a 121MB file.
So might be something in your environement or connectivity issues ?

**Comment by SergioBertolinSG** [comment]
Closing at it seems to be a problem in my environment.

**Comment by SergioBertolinSG** [comment]
Confirmed, problem with my environment. My vagrant machines can't upload using cadaver.
