### ISSUE TITLE
[Sharing link] you have two folder share with other user, if you move one folder into the other folder, the option shared is not working

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/core#16508]
### Steps to reproduce
1. Open the Owncloud Client
2. Create two new Folder, calls dd and gg
3. Shared the folder with other user
2. Move the folder dd into the folder gg

### Expected behaviour
You can work with the opcion SHARE

### Actual behaviour
The option SHARE is not working anymore. You need logout de Server and login again 

### Server configuration
DESKTOP v1.8.2 (build 2373) MAC
WEB SERVER: {"installed":"true","version":"7.0.1.1","versionstring":"7.0.1","edition":""}

**Web server:**

**Database:**

**Comment by karlitschek** [comment]
@schiesbn

**Comment by PVince81** [comment]
I still see this in 8.1.3.
Here are clearer steps:

1. Create two users "user1" and "user2"
1. Login as "user1"
1. Create two folders "test1" and "test2"
1. Share "test1" with "user2"
1. Share "test2" with "user2"
1. Move "test2" into "test1"
1. Click the "Share" action for the folder "test1"

The share action does nothing.
However if you refresh the page it will work again.

Possibly an issue with the cached shares.
Setting to low as there is a quick workaround.

Let me test how 8.2 behaves

**Comment by PVince81** [comment]
This works properly with 8.2RC1 where the share dialog is in the sidebar.
Closing.
