### ISSUE TITLE
\OCP\IImage::save should use the internal ownCloud view

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#16509]
`\OCP\IImage::save` is acting on a regular FS path (i.e. `/var/www`) in `\OC_Image::_output` instead of the internal ownCloud view.

This makes it potentially insecure against directory traversals and other issues when used incorrectly. With the internal views of ownCloud the built-in security functions would prevent this.

@icewind1991 Thoughts?
@DeepDiver1975 @karlitschek This public API has been introduced with 8.1.0 by @nickvergessen I don't see any usage thus I vote to remove the public API for 8.1.0 to allow us to fix this in the future without breaking public API. - Thoughts? Objections?

**Comment by LukasReschke** [comment]
With removing the public API I just refer to the `save` method in the interface. All other existing code would of course stay where it is.

**Comment by nickvergessen** [comment]
I just created the interface, the method was already there publicly by OCP\Image which extends OC_Image

**Comment by LukasReschke** [comment]
>  OCP\Image which extends OC_Image.

ewwww… :see_no_evil:

**Comment by PVince81** [comment]
I guess this hasn't solved itself through other changes ?

**Comment by PVince81** [comment]
CC @oparoz @georgehrke

**Comment by oparoz** [comment]
I think it's a bit late to remove it now as it may be used by apps, but maybe mark it as deprecated ASAP so that people stop using it. Surely if it represents a security risk, you don't have to maintain it for 3 more years.
