### ISSUE TITLE
mkdir is calling code that deletes previews

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#16500]
Sounds suspicious:

When I create a folder with MKCOL (webdav), the post_write calls post_delete and deletes previews ?
Is that intended ? @georgehrke @oparoz 

```
0  OC\Files\View->rmdir() /srv/www/htdocs/owncloud/lib/private/files/view.php:282
1  OC\Preview->deleteAllPreviews() /srv/www/htdocs/owncloud/lib/private/preview.php:351
2  OC\Preview::post_delete() /srv/www/htdocs/owncloud/lib/private/preview.php:946
3  OC\Preview::post_write() /srv/www/htdocs/owncloud/lib/private/preview.php:864
4  call_user_func:{/srv/www/htdocs/owncloud/lib/private/hook.php:103}() /srv/www/htdocs/owncloud/lib/private/hook.php:103
5  OC_Hook::emit() /srv/www/htdocs/owncloud/lib/private/hook.php:103
6  OC\Files\View->runHooks() /srv/www/htdocs/owncloud/lib/private/files/view.php:1069
7  OC\Files\View->basicOperation() /srv/www/htdocs/owncloud/lib/private/files/view.php:1010
8  OC\Files\View->mkdir() /srv/www/htdocs/owncloud/lib/private/files/view.php:242
9  OC\Connector\Sabre\Directory->createDirectory() /srv/www/htdocs/owncloud/lib/private/connector/sabre/directory.php:118
10 Sabre\DAV\Server->createCollection() /srv/www/htdocs/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php:1177
11 Sabre\DAV\CorePlugin->httpMkcol() /srv/www/htdocs/owncloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php:583
12 call_user_func_array:{/srv/www/htdocs/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php:105}() /srv/www/htdocs/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php:105
13 Sabre\Event\EventEmitter->emit() /srv/www/htdocs/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php:105
14 Sabre\DAV\Server->invokeMethod() /srv/www/htdocs/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php:469
15 Sabre\DAV\Server->exec() /srv/www/htdocs/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php:254
16 require_once()  /srv/www/htdocs/owncloud/apps/files/appinfo/remote.php:83
17 {main}          /srv/www/htdocs/owncloud/remote.php:84

```

**Comment by PVince81** [comment]
I'd usually expect preview deletion to only happen when deleting files, or overwriting existing files (not new files).

**Comment by georgehrke** [comment]
> post_write

We need post_write when a file is updated. (e.g. with files_texteditor)
I'd be happy to know if there is a way to properly distinguish between whether a new file was created or an existing one was modified.

**Comment by PVince81** [comment]
But this here is a directory, not even a file. Probably also not easy to detect ?

**Comment by georgehrke** [comment]
We need at least post_delete also for directories, so previews for files inside a folder that's being deleted are properly removed.
We should indeed be able to skip directories for post_write, I'll prepare a PR.

**Comment by georgehrke** [comment]
I just checked again, the only purpose of post_write is to call post_delete, so we can't remove the hook to post write.

Which brings me back to my first question:
> I'd be happy to know if there is a way to properly distinguish between whether a new file was created or an existing one was modified.

cc @icewind1991

**Comment by georgehrke** [comment]
ping @icewind1991

**Comment by icewind1991** [comment]
> I'd be happy to know if there is a way to properly distinguish between whether a new file was created or an existing one was modified.

For created files a "create" hook will be emitted to, atm there is no hook that only gets emitted for existing files being changed

**Comment by PVince81** [comment]
likely obsolete
