### ISSUE TITLE
Sharing to remote groups is not allowed

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16507]
### Steps to reproduce
1. Enable option Allow users on this server to send shares to other servers
2. Send a file to a group of another server
### Expected behaviour

The file should be sent to the selected group in 'server B'
### Actual behaviour

Federated sharing with remote groups is not allowed.
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
- activity: 1.2.3
- admin_audit: 0.6
- encryption: 1.0.0
- enterprise_key: 0.1.0
- files: 1.1.9
- files_locking: 
- files_pdfviewer: 0.7
- files_sharing: 0.6.1
- files_sharing_log: 0.5
- files_texteditor: 0.4
- files_trashbin: 0.6.2
- files_versions: 1.0.5
- files_videoviewer: 0.1.3
- firewall: 0.91.2
- firstrunwizard: 1.1
- gallery: 0.6.0
- provisioning_api: 0.2
- templateeditor: 0.1
- updater: 0.4
- user_ldap: 0.6.0
- windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** ActiveDirectory
### Client configuration

**Browser:** Internet Explorer 9 & Firefox

**Comment by rullzer** [comment]
Well this is a more fundamental problem.

* Group names and user names are not unique. So you can have a user foo that is part of group foo. Now if you use foo@.... which one do you mean?
* Who can accept group shares? Any member of the group? The group admin? What if there is no group admin?

I agree that we should have it in future releases but we need to think about how...

**Comment by cantonios** [comment]
1) It should work the same way it does locally, i.e. both appear in the selection box, and you select whether you want foo@... (group), or foo@...

2) Since federated sharing requires the user to accept the file (unlike when sharing locally, which is another inconsistency... although maybe for security reasons), then it should ask each user of that group if they want to accept the file and share on a user-by-user basis.  Reasoning: if the "accept" mechanism is there to prevent accepting malicious files, then why should the group admin be able to decide for everyone?

**Comment by settermjd** [comment]
@PVince81 @rullzer @cantonios is this still an issue and is a documentation update required?

**Comment by davitol** [comment]
@settermjd It stills an issue. oC seems to make the share (the LDAP group even appears in the sharing box and makes a fake share), but when login with a user of that group, he does not get the share

**Comment by davitol** [comment]
@settermjd Yes, it stills an issue. It is not possible to share to remote groups

This is the error message shown:

Sharing parati.txt failed, could not find grupo@docker.oc.solidgear.es:61041, maybe the server is currently unreachable.

**Comment by PVince81** [comment]
Sharing to federated groups was never supported. This will requires a lot of concept and implementation work.

**Comment by PVince81** [comment]
@pmaier1 for feature "sharing with federated groups"

**Comment by settermjd** [comment]
Closing as there are no plans for this feature.
