### ISSUE TITLE
Use Sabre's IPatchSupport for chunking

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#16524]
See http://sabre.io/dav/http-patch/ and the matching examples https://github.com/owncloud/3rdparty/blob/master/sabre/dav/lib/DAV/FSExt/File.php

**Comment by PVince81** [comment]
And/or PartialUpdate: https://github.com/owncloud/core/issues/14162

**Comment by DeepDiver1975** [comment]
From my understanding using this would require active locking of the file by the client.
Furthermore this approach has no rollback option.

@dragotin and myself did discuss chunked upload recently - here is the first blog post: https://dragotin.wordpress.com/2015/06/22/owncloud-chunking-ng/

**Comment by PVince81** [comment]
we went for another custom protocol, closing for now
