### ISSUE TITLE
How to remove user's data while still testing all the features

### ISSUE THREAD

**Issue by titansmc** [owncloud/core#16529]
Hi all,
I am still testing the ldap plugin and having some troubles that I would like to debug, and therefore I would like to login with my ldap username, test what I want, and then remove all the user's related information/entries that owncloud has kept. I mean, DB entries, data/uid information....

So, could you please tell me what I have to remove if I want to start over?

Thank you very much.

**Comment by karlitschek** [comment]
I'm not sure this is a bug. I suggest to ask this question on the developer mailing list.
Thanks for your understanding.
