### ISSUE TITLE
Pause/Resume file on upload

### ISSUE THREAD

**Issue by jonaysanz** [owncloud/core#16525]
### Steps to reproduce
1. Login Owncloud
2. On File section
3. Upload a file by drag&drop or with the dialog
### Expected behaviour

It uploads and let the user pause/resume the uploading file
### Actual behaviour

It uploads 

On large files it's so good that user can pause/resume files to not block the internet bandwidhh.

There is some code:
https://hacks.mozilla.org/2011/04/resumeupload/

**Comment by oparoz** [comment]
@PVince81 - Something for https://github.com/owncloud/core/issues/12353?

**Comment by PVince81** [comment]
A possible follow up for resumable uploads https://github.com/owncloud/core/pull/21237

**Comment by PVince81** [comment]
I mean, first Webdav PUT, then resumable will be easier to implement.

**Comment by PVince81** [comment]
Might be possible with chunking https://github.com/owncloud/core/issues/8955
