### ISSUE TITLE
Allow scrolling when dragging a file or folder to the top of the filelist

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16523]
Now, when dragging a file to the top of the filelist we can't move it to a folder which is in the top of the list.

![moving_files_top](https://cloud.githubusercontent.com/assets/9048796/7766329/716c3fd4-0068-11e5-8de8-8e30093e967a.gif)

I suggest to add scrolling when moving files. This way we could move files to folders that aren't in the screen currently.

Tested on chrome.

**Comment by oparoz** [comment]
Yes, please!

**Comment by PVince81** [comment]
Duplicate of https://github.com/owncloud/core/issues/12329
