### ISSUE TITLE
Login canceled by app

### ISSUE THREAD

**Issue by nicocans** [owncloud/core#16522]
Hello,
yesterday, i updated to 8.0.3, and all was ok.
this morning, i enabled my apps: calendar, tasks, ownnote, etc., everything seemed to work fine.
then i tryed to log from another computer, i cannot login now and have the following message: "Chiffrement initial en cours... Veuillez ré-essayer ultérieurement." and then "Login canceled by app".
how to fix it?

**Comment by karlitschek** [comment]
I suggest to enable/disable the apps one after another to find the broken one.

**Comment by nicocans** [comment]
How can i do this without login?

**Comment by RealRancor** [comment]
Hi,

see this FAQ for some possibilities: https://forum.owncloud.org/viewtopic.php?f=17&t=7241

**Comment by nicocans** [comment]
thanks for the tips.
i found the guilty app: it's ServerSide Encryption, in database it's files_encryption set to yes.
this seems to be a bug.

**Comment by PVince81** [comment]
@nicocans did you just enable encryption ? Or was it enabled a while ago ? Is this a newly created user ?
Normally every new user gets the initial encryption in 8.0.x versions, at this should happen only once.

**Comment by nicocans** [comment]
if I remember well, encrpytion was already enabled and this is an already existing user.

**Comment by PVince81** [comment]
Initial encryption process is obsolete since 8.1 due to encryption 2.0 using another mechanism.

@nicocans if you're still seeing this issue you can reset the migration flag, see https://github.com/owncloud/core/issues/7533#issuecomment-36660925
