### ISSUE TITLE
Move icon from OCS Share API to javascript

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#16531]
#16127 introduced the icon field to OCS Share API responses for files. However in its current form it looks weird and clutters the response. Especially since it is only usable for the web front end.

I propose to remove the functionality from the OCS Share API and to have the icon handling done in javascript. Since the OCS Share API does provide the mime type of the file. Some static javascript file should be good enough.

This should not be a problem since the functionality is not yet released. And make the API responses be useful on all platforms again.

CC: @MorrisJobke @DeepDiver1975 @karlitschek @schiesbn

**Comment by rullzer** [comment]
Also it is weird that the icon field is not present when a single share is retrieved.

**Comment by oparoz** [comment]
A duplicate of https://github.com/owncloud/core/issues/14431 ?

**Comment by rullzer** [comment]
Fixed with #16724
