### ISSUE TITLE
Can't delete multiple files on external storage

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#16533]
Steps to reproduce:

- mount external storage on the admin settings (tried with samba and sftp)
- upload some files
- select the files
- download action at the top right for the selected files is missing

Tested with master https://github.com/owncloud/core/commit/b82d902e184960877110bc45124ed2399f779cac

**Comment by PVince81** [comment]
You mean "delete action" is missing ?

There is probably a permissions mix up

**Comment by PVince81** [comment]
Related, permissions mess: https://github.com/owncloud/core/issues/13202
