### ISSUE TITLE
Public upload folders with choosen criteria

### ISSUE THREAD

**Issue by jonaysanz** [owncloud/core#16537]
My suggestion is the possibility to create a public upload folder, to just give access to people. 
This folders can be used without user&pass.
To have just a easy sharing space, with a link.

But with a configurable limit criteria.

For example: 
- Do not allow to upload more than 1GB
- Expire date
- Do not allow to upload videos

**Comment by RealRancor** [comment]
Hi,

public uploads can be already configured without user/pass and with a expiration date:

https://doc.owncloud.org/server/8.0/user_manual/files/access_webgui.html#creating-a-public-link-share

**Comment by jonaysanz** [comment]
I think a great feature would be to limit maximum folder size, cause public folder can be a chaos (if it's shared with a group of people)
