### ISSUE TITLE
Public link manager

### ISSUE THREAD

**Issue by jonaysanz** [owncloud/core#16538]
A nice feature can be to have a place where are listed all links you generated to share files. This way you can remove those external access to files, generate new ones, or re-generate the access token.

**Comment by RealRancor** [comment]
Hi,

at least a list with all files/folders shared by link is already available:

https://demo.owncloud.org/index.php/apps/files/?dir=%2F&view=sharinglinks

**Comment by jonaysanz** [comment]
Ups... sorry I couldn't find it :+1: 
Thanks
