### ISSUE TITLE
File indexation by content

### ISSUE THREAD

**Issue by jonaysanz** [owncloud/core#16539]
Now the search box you can only search by filename.
Would be so useful to be able by content, at least in TXT/ODT/spreadsheet/PDF files

**Comment by RealRancor** [comment]
Hi,

this is already available: https://doc.owncloud.org/server/8.0/admin_manual/configuration_server/search_configuration.html

**Comment by PVince81** [comment]
Closing as invalid.

@jonaysanz if despite proper configuration you are still seeing issues, please reopen and use the issue template https://raw.githubusercontent.com/owncloud/core/master/issue_template.md with more details about your setup and reproduction steps.
Thanks.
