### ISSUE TITLE
The scrollbar is lost and you can't go down

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/core#16530]
### Steps to reproduce
1. Open your Owncloud Client
2. Click in your user
3. Click in Personal

### Expected behaviour
The scrollbar should not be lost

### Actual behaviour
you don't have the scrollbar, and you can't go down to change the language

### Server configuration
WEB SERVER: {"installed":"true","version":"7.0.1.1","versionstring":"7.0.1","edition":""}, in WINDOWS, IE8

**Comment by PVince81** [comment]
@Dianafg76 it looks like you are testing 7.0.1 ? That issue was fixed a while ago.
Please try again with 7.0.5 or 8.0.3.

Works for me in 8.0.3.

**Comment by PVince81** [comment]
Duplicate of https://github.com/owncloud/core/issues/9677
