### ISSUE TITLE
Contact sync CardDAV issues

### ISSUE THREAD

**Issue by jonathannz** [owncloud/core#16541]
I noticed today that changes I was making to my local copy of contacts (on a Mac) were disappearing. Turns out the OwnCloud server was not accepting them, and the changed (or newly added) contact details would revert back.
I see there is a 6.5 MB error log. Here is a snippet of *some* of the errors generated today by the Contacts app. I would appreciate help in figuring out what this issue is:

    {"reqId":"75f48e47af0e7a65b0ef878ffb077eb1","remoteAddr":"119.224.102.205","app":"contacts","message":"OCA\\Contacts\\Utils\\Properties::purgeIndexes, ids: Array\n(\n    [0] => 1240\n)\n","level":0,"time":"2015-05-23T07:55:29+00:00","method":"PATCH","url":"\/ocloud\/index.php\/apps\/contacts\/addressbook\/local\/1\/contact\/1240"},{"reqId":"75f48e47af0e7a65b0ef878ffb077eb1","remoteAddr":"119.224.102.205","app":"contacts","message":"OCA\\Contacts\\Utils\\Properties::purgeIndexes, ids: Array\n(\n    [0] => 1240\n)\n","level":0,"time":"2015-05-23T07:55:29+00:00","method":"PATCH","url":"\/ocloud\/index.php\/apps\/contacts\/addressbook\/local\/1\/contact\/1240"},{"reqId":"75f48e47af0e7a65b0ef878ffb077eb1","remoteAddr":"119.224.102.205","app":"contacts","message":"OCA\\Contacts\\Contact::setPropertyByName adding: FN Ashoka Sadhaka","level":0,"time":"2015-05-23T07:55:29+00:00","method":"PATCH","url":"\/ocloud\/index.php\/apps\/contacts\/addressbook\/local\/1\/contact\/1240"},{"reqId":"75f48e47af0e7a65b0ef878ffb077eb1","remoteAddr":"119.224.102.205","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-05-23T07:55:29+00:00","method":"PATCH","url":"\/ocloud\/index.php\/apps\/contacts\/addressbook\/local\/1\/contact\/1240"},{"reqId":"43769160e958945bbe6c132427216e77","remoteAddr":"119.224.102.205","app":"contacts","message":"OCA\\Contacts\\Utils\\Properties::purgeIndexes, ids: Array\n(\n    [0] => 916\n)\n","level":0,"time":"2015-05-23T07:55:21+00:00","method":"DELETE","url":"\/ocloud\/remote.php\/carddav\/addressbooks\/jonathan\/contacts\/65266670-62f4-4803-b7e4-c79db40c3912.vcf"},{"reqId":"43769160e958945bbe6c132427216e77","remoteAddr":"119.224.102.205","app":"contacts","message":"OCA\\Contacts\\Utils\\Properties::purgeIndexes, ids: Array\n(\n    [0] => 916\n)\n","level":0,"time":"2015-05-23T07:55:21+00:00","method":"DELETE","url":"\/ocloud\/remote.php\/carddav\/addressbooks\/jonathan\/contacts\/65266670-62f4-4803-b7e4-c79db40c3912.vcf"},{"reqId":"43769160e958945bbe6c132427216e77","remoteAddr":"119.224.102.205","app":"core","message":"OC\\Tags::__construct, tags: Array\n(\n    [0] => OC\\Tagging\\Tag Object\n        (\n            [owner:protected] => jonathan\n            [type:protected] => contact\n            [name:protected] => Boquete\n            [id] => 17\n            [_updatedFields:OCP\\AppFramework\\Db\\Entity:private] => Array\n                (\n                )\n\n            [_fieldTypes:OCP\\AppFramework\\Db\\Entity:private] => Array\n                (\n                    [id] => integer\n                )\n\n        )\n\n    [1] => OC\\Tagging\\Tag Object\n        (\n            [owner:protected] => jonathan\n            [type:protected] => contact\n            [name:protected] => Finland\n            [id] => 16\n            [_updatedFields:OCP\\AppFramework\\Db\\Entity:private] => Array\n                (\n                )\n\n            [_fieldTypes:OCP\\AppFramework\\Db\\Entity:private] => Array\n                (\n                    [id] => integer\n                )\n\n        )\n\n    [2] => OC\\Tagging\\Tag Object\n        (\n            [owner:protected] => jonathan\n            [type:protected] => contact\n            [name:protected] => Panama\n            [id] => 18\n            [_updatedFields:OCP\\AppFramework\\Db\\Entity:private] => Array\n                (\n                )\n\n            [_fieldTypes:OCP\\AppFramework\\Db\\Entity:private] => Array\n                (\n                    [id] => integer\n                )\n\n        )\n\n)\n","level":0,"time":"2015-05-23T07:55:21+00:00","method":"DELETE","url":"\/ocloud\/remote.php\/carddav\/addressbooks\/jonathan\/contacts\/65266670-62f4-4803-b7e4-c79db40c3912.vcf"},{"reqId":"43769160e958945bbe6c132427216e77","remoteAddr":"119.224.102.205","app":"contacts","message":"OCA\\Contacts\\Hooks::contactDeletion id: 916","level":0,"time":"2015-05-23T07:55:21+00:00","method":"DELETE","url":"\/ocloud\/remote.php\/carddav\/addressbooks\/jonathan\/contacts\/65266670-62f4-4803-b7e4-c79db40c3912.vcf"},{"reqId":"626304021f200014bcec2c2e465f644c","remoteAddr":"119.224.102.205","app":"carddav","message":"Exception: {\"Message\":\"No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/inspired\\\/public_html\\\/ocloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(126): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#1 \\\/home\\\/inspired\\\/public_html\\\/ocloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(106): OC_Connector_Sabre_Auth->auth(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#2 \\\/home\\\/inspired\\\/public_html\\\/ocloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Plugin.php(108): OC_Connector_Sabre_Auth->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod('PROPFIND', 'addressbooks\\\/jo...')\\n#4 \\\/home\\\/inspired\\\/public_html\\\/ocloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(433): call_user_func_array(Array, Array)\\n#5 \\\/home\\\/inspired\\\/public_html\\\/ocloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(455): Sabre\\\\DAV\\\\Server->broadcastEvent('beforeMethod', Array)\\n#6 \\\/home\\\/inspired\\\/public_html\\\/ocloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('PROPFIND', 'addressbooks\\\/jo...')\\n#7 \\\/home\\\/inspired\\\/public_html\\\/ocloud\\\/apps\\\/contacts\\\/appinfo\\\/remote.php(88): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/home\\\/inspired\\\/public_html\\\/ocloud\\\/remote.php(54): require_once('\\\/home\\\/inspired\\\/...')\\n#9 {main}\",\"File\":\"\\\/home\\\/inspired\\\/public_html\\\/ocloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":73}","level":0,"time":"2015-05-23T07:55:17+00:00","method":"PROPFIND","url":"\/ocloud\/remote.php\/carddav\/addressbooks\/jonathan\/"},{"reqId":"1b79a8d16f32b16bc9d60eed96a98602","remoteAddr":"119.224.102.205","app":"contacts","message":"OCA\\Contacts\\Utils\\Properties::purgeIndexes, ids: Array\n(\n    [0] => 109\n)\n","level":0,"time":"2015-05-23T07:54:16+00:00","method":"DELETE","url":"\/ocloud\/index.php\/apps\/contacts\/addressbook\/local\/1\/contact\/109"},{"reqId":"1b79a8d16f32b16bc9d60eed96a98602","remoteAddr":"119.224.102.205","app":"contacts","message":"OCA\\Contacts\\Utils\\Properties::purgeIndexes, ids: Array\n(\n    [0] => 109\n)\n","level":0,"time":"2015-05-23T07:54:16+00:00","method":"DELETE","url":"\/ocloud\/index.php\/apps\/contacts\/addressbook\/local\/1\/contact\/109"},{"reqId":"1b79a8d16f32b16bc9d60eed96a98602","remoteAddr":"119.224.102.205","app":"core","message":"OC\\Tags::__construct, tags: Array\n(\n    [0] => OC\\Tagging\\Tag Object\n        (\n            [owner:protected] => jonathan\n            [type:protected] => contact\n            [name:protected] => Boquete\n            [id] => 17\n            [_updatedFields:OCP\\AppFramework\\Db\\Entity:private] => Array\n                (\n                )\n\n            [_fieldTypes:OCP\\AppFramework\\Db\\Entity:private] => Array\n                (\n                    [id] => integer\n                )\n\n        )\n\n    [1] => OC\\Tagging\\Tag Object\n        (\n            [owner:protected] => jonathan\n            [type:protected] => contact\n            [name:protected] => Finland\n            [id] => 16\n            [_updatedFields:OCP\\AppFramework\\Db\\Entity:private] => Array\n                (\n                )\n\n            [_fieldTypes:OCP\\AppFramework\\Db\\Entity:private] => Array\n                (\n                    [id] => integer\n                )\n\n        )\n\n    [2] => OC\\Tagging\\Tag Object\n        (\n            [owner:protected] => jonathan\n            [type:protected] => contact\n            [name:protected] => Panama\n            [id] => 18\n            [_updatedFields:OCP\\AppFramework\\Db\\Entity:private] => Array\n                (\n                )\n\n            [_fieldTypes:OCP\\AppFramework\\Db\\Entity:private] => Array\n                (\n                    [id] => integer\n                )\n\n        )\n\n)\n","level":0,"time":"2015-05-23T07:54:16+00:00","method":"DELETE","url":"\/ocloud\/index.php\/apps\/contacts\/addressbook\/local\/1\/contact\/109"},{"reqId":"1b79a8d16f32b16bc9d60eed96a98602","remoteAddr":"119.224.102.205","app":"contacts","message":"OCA\\Contacts\\Hooks::contactDeletion id: 109","level":0,"time":"2015-05-23T07:54:16+00:00","method":"DELETE","url":"\/ocloud\/index.php\/apps\/contacts\/addressbook\/local\/1\/contact\/109"},{"reqId":"1b79a8d16f32b16bc9d60eed96a98602","remoteAddr":"119.224.102.205","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-05-23T07:54:16+00:00","method":"DELETE","url":"\/ocloud\/index.php\/apps\/contacts\/addressbook\/local\/1\/contact\/109"},{"reqId":"a9060fefacc65ead298e906b52f3e72b","remoteAddr":"119.224.102.205","app":"contacts","message":"OCA\\Contacts\\Utils\\Properties::purgeIndexes, ids: Array\n(\n    [0] => 44\n)\n","level":0,"time":"2015-05-23T07:54:05+00:00","method":"POST","url":"\/ocloud\/index.php\/apps\/contacts\/addressbook\/local\/1\/contact\/44\/save"},{"reqId":"a9060fefacc65ead298e906b52f3e72b","remoteAddr":"119.224.102.205","app":"contacts","message":"OCA\\Contacts\\Utils\\Properties::purgeIndexes, ids: Array\n(\n    [0] => 44\n)\n","level":0,"time":"2015-05-23T07:54:05+00:00","method":"POST","url":"\/ocloud\/index.php\/apps\/contacts\/addressbook\/local\/1\/contact\/44\/save"},{"reqId":"a9060fefacc65ead298e906b52f3e72b","remoteAddr":"119.224.102.205","app":"contacts","message":"OCA\\Contacts\\Contact::mergeFromArray adding: ADR Array\n(\n    [0] => \n    [1] => \n    [2] => \n    [3] => \n    [4] => \n    [5] => \n    [6] => New Zealand\n)\n Array\n(\n    [TYPE] => Array\n        (\n            [0] => HOME\n        )\n\n    [PREF] => 1\n)\n","level":0,"time":"2015-05-23T07:54:05+00:00","method":"POST","url":"\/ocloud\/index.php\/apps\/contacts\/addressbook\/local\/1\/contact\/44\/save"},{"reqId":"a9060fefacc65ead298e906b52f3e72b","remoteAddr":"119.224.102.205","app":"contacts","message":"OCA\\Contacts\\Contact::mergeFromArray adding: EMAIL support@2talk.co.nz Array\n(\n    [TYPE] => Array\n        (\n            [0] => INTERNET\n        )\n\n    [PREF] => 1\n)\n","level":0,"time":"2015-05-23T07:54:05+00:00","method":"POST","url":"\/ocloud\/index.php\/apps\/contacts\/addressbook\/local\/1\/contact\/44\/save"},{"reqId":"a9060fefacc65ead298e906b52f3e72b","remoteAddr":"119.224.102.205","app":"contacts","message":"OCA\\Contacts\\Contact::mergeFromArray adding: ORG Array\n(\n    [0] => 2talk Support\n    [1] => \n)\n Array\n(\n)\n","level":0,"time":"2015-05-23T07:54:05+00:00","method":"POST","url":"\/ocloud\/index.php\/apps\/contacts\/addressbook\/local\/1\/contact\/44\/save"},{"reqId":"a9060fefacc65ead298e906b52f3e72b","remoteAddr":"119.224.102.205","app":"contacts","message":"OCA\\Contacts\\Contact::mergeFromArray adding: FN 2talk Support Array\n(\n)\n","level":0,"time":"2015-05-23T07:54:05+00:00","method":"POST","url":"\/ocloud\/index.php\/apps\/contacts\/addressbook\/local\/1\/contact\/44\/save"},{"reqId":"a9060fefacc65ead298e906b52f3e72b","remoteAddr":"119.224.102.205","app":"contacts","message":"OCA\\Contacts\\Contact::mergeFromArray adding: N Array\n(\n    [0] => Support\n    [1] => 2talk\n    [2] => \n    [3] => \n    [4] => \n)\n Array\n(\n)\n","level":0,"time":"2015-05-23T07:54:05+00:00","method":"POST","url":"\/ocloud\/index.php\/apps\/contacts\/addressbook\/local\/1\/contact\/44\/save"},{"reqId":"a9060fefacc65ead298e906b52f3e72b","remoteAddr":"119.224.102.205","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-05-23T07:54:05+00:00","method":"POST","url":"\/ocloud\/index.php\/apps\/contacts\/addressbook\/local\/1\/contact\/44\/save"},{"reqId":"beb3a3e268614dc33b0bb22e07bf4684","remoteAddr":"119.224.102.205","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-05-23T07:53:48+00:00","method":"POST","url":"\/ocloud\/index.php\/apps\/contacts\/preference\/set"},{"reqId":"7722e3824b9057f4caaeb787d8cb26bf","remoteAddr":"119.224.102.205","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-05-23T07:53:00+00:00","method":"GET","url":"\/ocloud\/index.php\/apps\/contacts\/addressbook\/local\/1\/contacts"},{"reqId":"f7be969358bcec643e3e57e69975a651","remoteAddr":"119.224.102.205","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-05-23T07:52:59+00:00","method":"GET","url":"\/ocloud\/index.php\/apps\/contacts\/connectors\/%7Bbackend%7D"},{"reqId":"e581062ac2e92496539bf3229ff410c5","remoteAddr":"119.224.102.205","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-05-23T07:52:59+00:00","method":"GET","url":"\/ocloud\/index.php\/apps\/contacts\/addressbooks\/"},{"reqId":"e02dad3aaa3231309caff488f0b2f2d7","remoteAddr":"119.224.102.205","app":"core","message":"OC\\Tags::getFavorites, exception: Could not find category \"_$!<Favorite>!$_\"","level":0,"time":"2015-05-23T07:52:59+00:00","method":"GET","url":"\/ocloud\/index.php\/apps\/contacts\/groups\/"},{"reqId":"e02dad3aaa3231309caff488f0b2f2d7","remoteAddr":"119.224.102.205","app":"core","message":"OC\\Tags::__construct, tags: Array\n(\n    [0] => OC\\Tagging\\Tag Object\n        (\n            [owner:protected] => jonathan\n            [type:protected] => contact\n            [name:protected] => Boquete\n            [id] => 17\n            [_updatedFields:OCP\\AppFramework\\Db\\Entity:private] => Array\n                (\n                )\n\n            [_fieldTypes:OCP\\AppFramework\\Db\\Entity:private] => Array\n                (\n                    [id] => integer\n                )\n\n        )\n\n    [1] => OC\\Tagging\\Tag Object\n        (\n            [owner:protected] => jonathan\n            [type:protected] => contact\n            [name:protected] => Finland\n            [id] => 16\n            [_updatedFields:OCP\\AppFramework\\Db\\Entity:private] => Array\n                (\n                )\n\n            [_fieldTypes:OCP\\AppFramework\\Db\\Entity:private] => Array\n                (\n                    [id] => integer\n                )\n\n        )\n\n    [2] => OC\\Tagging\\Tag Object\n        (\n            [owner:protected] => jonathan\n            [type:protected] => contact\n            [name:protected] => Panama\n            [id] => 18\n            [_updatedFields:OCP\\AppFramework\\Db\\Entity:private] => Array\n                (\n                )\n\n            [_fieldTypes:OCP\\AppFramework\\Db\\Entity:private] => Array\n                (\n                    [id] => integer\n                )\n\n        )\n\n)\n","level":0,"time":"2015-05-23T07:52:59+00:00","method":"GET","url":"\/ocloud\/index.php\/apps\/contacts\/groups\/"},{"reqId":"e02dad3aaa3231309caff488f0b2f2d7","remoteAddr":"119.224.102.205","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-05-23T07:52:59+00:00","method":"GET","url":"\/ocloud\/index.php\/apps\/contacts\/groups\/"},{"reqId":"b48c85578f5276fa0e9a9c049785254b","remoteAddr":"119.224.102.205","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-05-23T07:52:51+00:00","method":"GET","url":"\/ocloud\/index.php\/apps\/contacts\/"},{"reqId":"ba2dbcce1eb03e76527da9529d27e439","remoteAddr":"119.224.102.205","app":"no app in context","message":"Current user is not logged in","level":0,"time":"2015-05-23T07:52:34+00:00","method":"GET","url":"\/ocloud\/index.php\/apps\/contacts\/"},{"reqId":"ba2dbcce1eb03e76527da9529d27e439","remoteAddr":"119.224.102.205","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-05-23T07:52:34+00:00","method":"GET","url":"\/ocloud\/index.php\/apps\/contacts\/"},{"reqId":"59602462b8ac58de6ca413b62c5b56cb","remoteAddr":"119.224.102.205","app":"core","message":"OC\\Tags::__construct, tags: Array\n(\n    [0] => OC\\Tagging\\Tag Object\n        (\n            [owner:protected] => jonathan\n            [type:protected] => contact\n            [name:protected] => Boquete\n            [id] => 17\n            [_updatedFields:OCP\\AppFramework\\Db\\Entity:private] => Array\n                (\n                )\n\n            [_fieldTypes:OCP\\AppFramework\\Db\\Entity:private] => Array\n                (\n                    [id] => integer\n                )\n\n        )\n\n    [1] => OC\\Tagging\\Tag Object\n        (\n            [owner:protected] => jonathan\n            [type:protected] => contact\n            [name:protected] => Finland\n            [id] => 16\n            [_updatedFields:OCP\\AppFramework\\Db\\Entity:private] => Array\n                (\n                )\n\n            [_fieldTypes:OCP\\AppFramework\\Db\\Entity:private] => Array\n                (\n                    [id] => integer\n                )\n\n        )\n\n    [2] => OC\\Tagging\\Tag Object\n        (\n            [owner:protected] => jonathan\n            [type:protected] => contact\n            [name:protected] => Panama\n            [id] => 18\n            [_updatedFields:OCP\\AppFramework\\Db\\Entity:private] => Array\n                (\n                )\n\n            [_fieldTypes:OCP\\AppFramework\\Db\\Entity:private] => Array\n                (\n                    [id] => integer\n                )\n\n        )\n\n)\n","level":0,"time":"2015-05-23T07:50:30+00:00","method":"PUT","url":"\/ocloud\/remote.php\/carddav\/addressbooks\/jonathan\/contacts\/7375d83c-d805-45de-8bf8-09b5259f5e0e.vcf"},{"reqId":"59602462b8ac58de6ca413b62c5b56cb","remoteAddr":"119.224.102.205","app":"contacts","message":"OCA\\Contacts\\Utils\\Properties::purgeIndexes, ids: Array\n(\n    [0] => 1209\n)\n","level":0,"time":"2015-05-23T07:50:30+00:00","method":"PUT","url":"\/ocloud\/remote.php\/carddav\/addressbooks\/jonathan\/contacts\/7375d83c-d805-45de-8bf8-09b5259f5e0e.vcf"},{"reqId":"59602462b8ac58de6ca413b62c5b56cb","remoteAddr":"119.224.102.205","app":"contacts","message":"OCA\\Contacts\\Utils\\Properties::purgeIndexes, ids: Array\n(\n    [0] => 1209\n)\n","level":0,"time":"2015-05-23T07:50:30+00:00","method":"PUT","url":"\/ocloud\/remote.php\/carddav\/addressbooks\/jonathan\/contacts\/7375d83c-d805-45de-8bf8-09b5259f5e0e.vcf"},{"reqId":"3e09e76ffcd15049f03c94e50faae48c","remoteAddr":"119.224.102.205","app":"carddav","message":"Exception: {\"Message\":\"No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/inspired\\\/public_html\\\/ocloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(126): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#1 \\\/home\\\/inspired\\\/public_html\\\/ocloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(106): OC_Connector_Sabre_Auth->auth(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#2 \\\/home\\\/inspired\\\/public_html\\\/ocloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Plugin.php(108): OC_Connector_Sabre_Auth->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod('PROPFIND', 'addressbooks\\\/jo...')\\n#4 \\\/home\\\/inspired\\\/public_html\\\/ocloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(433): call_user_func_array(Array, Array)\\n#5 \\\/home\\\/inspired\\\/public_html\\\/ocloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(455): Sabre\\\\DAV\\\\Server->broadcastEvent('beforeMethod', Array)\\n#6 \\\/home\\\/inspired\\\/public_html\\\/ocloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('PROPFIND', 'addressbooks\\\/jo...')\\n#7 \\\/home\\\/inspired\\\/public_html\\\/ocloud\\\/apps\\\/contacts\\\/appinfo\\\/remote.php(88): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/home\\\/inspired\\\/public_html\\\/ocloud\\\/remote.php(54): require_once('\\\/home\\\/inspired\\\/...')\\n#9 {main}\",\"File\":\"\\\/home\\\/inspired\\\/public_html\\\/ocloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":73}","level":0,"time":"2015-05-23T07:50:25+00:00","method":"PROPFIND","url":"\/ocloud\/remote.php\/carddav\/addressbooks\/jonathan\/"},{"reqId":"01bc4ca950b33c6a063f79084aaf4bf1","remoteAddr":"119.224.102.205","app":"carddav","message":"Exception: {\"Message\":\"No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/inspired\\\/public_html\\\/ocloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(126): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#1 \\\/home\\\/inspired\\\/public_html\\\/ocloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(106): OC_Connector_Sabre_Auth->auth(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#2 \\\/home\\\/inspired\\\/public_html\\\/ocloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Plugin.php(108): OC_Connector_Sabre_Auth->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod('PROPFIND', 'addressbooks\\\/jo...')\\n#4 \\\/home\\\/inspired\\\/public_html\\\/ocloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(433): call_user_func_array(Array, Array)\\n#5 \\\/home\\\/inspired\\\/public_html\\\/ocloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(455): Sabre\\\\DAV\\\\Server->broadcastEvent('beforeMethod', Array)\\n#6 \\\/home\\\/inspired\\\/public_html\\\/ocloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('PROPFIND', 'addressbooks\\\/jo...')\\n#7 \\\/home\\\/inspired\\\/public_html\\\/ocloud\\\/apps\\\/contacts\\\/appinfo\\\/remote.php(88): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/home\\\/inspired\\\/public_html\\\/ocloud\\\/remote.php(54): require_once('\\\/home\\\/inspired\\\/...')\\n#9 {main}\",\"File\":\"\\\/home\\\/inspired\\\/public_html\\\/ocloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":73}","level":0,"time":"2015-05-23T07:49:56+00:00","method":"PROPFIND","url":"\/ocloud\/remote.php\/carddav\/addressbooks\/jonathan\/contacts\/"},{"reqId":"5e815b1eef7d1cddf48d2eb3ddb1608e","remoteAddr":"119.224.102.205","app":"core","message":"OC\\Tags::__construct, tags: Array\n(\n    [0] => OC\\Tagging\\Tag Object\n        (\n            [owner:protected] => jonathan\n            [type:protected] => contact\n            [name:protected] => Boquete\n            [id] => 17\n            [_updatedFields:OCP\\AppFramework\\Db\\Entity:private] => Array\n                (\n                )\n\n            [_fieldTypes:OCP\\AppFramework\\Db\\Entity:private] => Array\n                (\n                    [id] => integer\n                )\n\n        )\n\n    [1] => OC\\Tagging\\Tag Object\n        (\n            [owner:protected] => jonathan\n            [type:protected] => contact\n            [name:protected] => Finland\n            [id] => 16\n            [_updatedFields:OCP\\AppFramework\\Db\\Entity:private] => Array\n                (\n                )\n\n            [_fieldTypes:OCP\\AppFramework\\Db\\Entity:private] => Array\n                (\n                    [id] => integer\n                )\n\n        )\n\n    [2] => OC\\Tagging\\Tag Object\n        (\n            [owner:protected] => jonathan\n            [type:protected] => contact\n            [name:protected] => Panama\n            [id] => 18\n            [_updatedFields:OCP\\AppFramework\\Db\\Entity:private] => Array\n                (\n                )\n\n            [_fieldTypes:OCP\\AppFramework\\Db\\Entity:private] => Array\n                (\n                    [id] => integer\n                )\n\n        )\n\n)\n","level":0,"time":"2015-05-23T07:49:55+00:00","method":"PUT","url":"\/ocloud\/remote.php\/carddav\/addressbooks\/jonathan\/contacts\/e42dddda-da85-4477-bf04-3786ee8a72fc.vcf"},{"reqId":"5e815b1eef7d1cddf48d2eb3ddb1608e","remoteAddr":"119.224.102.205","app":"contacts","message":"OCA\\Contacts\\Utils\\Properties::purgeIndexes, ids: Array\n(\n    [0] => 1225\n)\n","level":0,"time":"2015-05-23T07:49:55+00:00","method":"PUT","url":"\/ocloud\/remote.php\/carddav\/addressbooks\/jonathan\/contacts\/e42dddda-da85-4477-bf04-3786ee8a72fc.vcf"},{"reqId":"5e815b1eef7d1cddf48d2eb3ddb1608e","remoteAddr":"119.224.102.205","app":"contacts","message":"OCA\\Contacts\\Utils\\Properties::purgeIndexes, ids: Array\n(\n    [0] => 1225\n)\n","level":0,"time":"2015-05-23T07:49:55+00:00","method":"PUT","url":"\/ocloud\/remote.php\/carddav\/addressbooks\/jonathan\/contacts\/e42dddda-da85-4477-bf04-3786ee8a72fc.vcf"},{"reqId":"832c7bc5410cb7ddccc1bdc226a9fa0a","remoteAddr":"119.224.102.205","app":"carddav","message":"Exception: {\"Message\":\"No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/inspired\\\/public_html\\\/ocloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(126): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#1 \\\/home\\\/inspired\\\/public_html\\\/ocloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(106): OC_Connector_Sabre_Auth->auth(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#2 \\\/home\\\/inspired\\\/public_html\\\/ocloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Plugin.php(108): OC_Connector_Sabre_Auth->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod('PUT', 'addressbooks\\\/jo...')\\n#4 \\\/home\\\/inspired\\\/public_html\\\/ocloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(433): call_user_func_array(Array, Array)\\n#5 \\\/home\\\/inspired\\\/public_html\\\/ocloud\\\/3rdparty

**Comment by karlitschek** [comment]
can you open this bug in the contacts repository please?
Thanks.
