### ISSUE TITLE
Support dots in routes handled by the AppFramework

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#16540]
I'd like to be able to define routes like this
`/s/{token}.{extension}`
others may want to be able to specify a format
`/user/{id}.{format}`

@Raydiation @LukasReschke

**Comment by Raydiation** [comment]
Iirc this was already discussed but it's not possible because of some symfony routing internal code

**Comment by oparoz** [comment]
;( 

It's true that I didn't check the closed tickets...


   FROM: Bernhard Posselt
SENT: Saturday, 23 May 2015 07:17
TO: core@noreply.github.com
REPLY TO: owncloud/core
CC: Olivier Paroz
SUBJECT: Re: [core] Support dots in routes handled by the AppFramework
(#16540)

> Iirc this was already discussed but it's not possible because of some
> symfony routing internal code
>
> —
> Reply to this email directly or view it on GitHub[1].



Liens:
------
[1] https://github.com/owncloud/core/issues/16540#issuecomment-104846282

**Comment by oparoz** [comment]
Symfony supports it:
http://symfony.com/doc/2.2/book/routing.html#advanced-routing-example

**Comment by LukasReschke** [comment]
Were is the problem?

I adjusted the following in `routes.php` of core and it works just fine:
```php
		['name' => 'lost#resetform', 'url' => '/lostpassword/reset/form/{token}.{userId}', 'verb' => 'GET'],
```

**Comment by oparoz** [comment]
It doesn't seem to work with the AppFramework though, unless I've made a mistage somewhere
Change this line https://github.com/owncloud/galleryplus/blob/master/appinfo/routes.php#L42
from
`'/s/{token}/{extension}'`
to
`'/s/{token}.{extension}'`

and you'll get a token doesn't not link to a resource type of error

**Comment by oparoz** [comment]
The token is retrieved via 
`$token = $this->request->getParam('token');`
https://github.com/owncloud/galleryplus/blob/master/middleware/envcheckmiddleware.php#L125

**Comment by LukasReschke** [comment]
Well - that simply works fine and is a bug in your code, `page#public_index` collides with `public_download#download_file`. The `token` URL fragment can also contain a `.` - `/` is per default the dividing component.

Take a look at https://doc.owncloud.org/server/8.0/developer_manual/app/routes.html#matching-suburls and define something like `'requirements' => ['token' => '[a-zA-Z0-9]+'],` for the `page#public_index`.

That said, I'd really really really not go that route as this will explode huge when we adjust the components of a sharing token. – This can happen anytime without notice.

**Comment by oparoz** [comment]
OK, I'll keep `'/s/{token}/{extension}'` then. I need the overlap to be able to intercept these special cases where there is something after the token.
Thanks for having taken a look :thumbsup:

**Comment by Raydiation** [comment]
Ah this is not about the route name, my bad :P

**Comment by Raydiation** [comment]
Dot should just work fine BTW see the docs

**Comment by oparoz** [comment]
Well, Symfony supports both the / and . as a default segment separator, so it would be nice if the AppFramework did the same or at least let us define it, but as Lukas has mentioned, it will be a problem if the dot is introduced in the token...

**Comment by oparoz** [comment]
{_format} support would be great as well since it auto-populates the headers
