### ISSUE TITLE
[File picker] [File Dropper] ability for creating new folders, do file/folder opperations

### ISSUE THREAD

**Issue by ghost** [owncloud/core#16550]
I am a huge fan of the ownCloud Mail app. In the mail app you can save attachments to your files on ownCloud. But when saving attachments to files you can't make new folders, delete folders or rename stuff.

So I hope this can be integrated to the core because that would be truly amazing.

Cheers,

Damion

**Comment by PVince81** [comment]
Can you elaborate ?

Is this about adding a generic file picker / file save dialog to core that can be reused by apps ?
