### ISSUE TITLE
Preview text icon does not work in federated shared files

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16555]
### Steps to reproduce
1. Send a file to a user by link of other server
2. Accept the shared filed

### Expected behaviour
If the file has text written, the 'preview icon' should be shown.

### Actual behaviour
The standard icon is shown.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity: 1.2.3
 - admin_audit: 0.6
 - encryption: 1.0.0
 - enterprise_key: 0.1.0
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.4
 - user_ldap: 0.6.0
 - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** ActiveDirectory

### Client configuration
**Browser:** Firefox
![captura de pantalla 2015-05-25 a las 13 57 11](https://cloud.githubusercontent.com/assets/10596560/7796993/47dbb9bc-02e6-11e5-96d5-e8b9cb28895c.png)

**Comment by PVince81** [comment]
Your file has 0 kb. What about bigger files ? (more than 6 characters)

**Comment by davitol** [comment]
With bigger files it works, but I have realized of "another" issue/enhacement. Federated sharing files do not update their preview icon if the file is edited in server A. Refreshing does not solve it.
