### ISSUE TITLE
[Sharing link] If you have a shared file,  remove the share on the desktop , server icon is not removed

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/core#16554]
### Steps to reproduce
1. Oper your Owncloud Desktop client
2. Go to Open Folder "ownCloud"
3. Create a new File, call 444
4. Right click on the folder 444
5. Select share with ownCloud
6. "set expiration date" and select the date when you want it to expire
7. Open your Owncloud Web client
8. The File 444 is SHARED
9. Go to Owncloud Desktop
10. Right click on the folder 444
11. Disable the option "set expiration date"
12. Go to Owncloud Web client

### Expected behaviour
The icon should disappear , because the file is not shared

### Actual behaviour
The Shared icon has not disappeared. And It seems that the file was shared

![screen shot 2015-05-25 at 12 24 01](https://cloud.githubusercontent.com/assets/12032058/7795845/1d45eaa4-02d9-11e5-8b62-2712181945f2.png)

### Server configuration
DESKTOP v 1.8.2 (build 5104)
WEB SERVER: {"installed":"true","version":"7.0.1.1","versionstring":"7.0.1","edition":""}, in WINDOWS, IE8

**Comment by PVince81** [comment]
@Dianafg76 disabling "expiration date" doesn't automatically unshare. You have to uncheck "share link" to remote the share.

**Comment by Dianafg76** [comment]
@PVince81 Thanks
