### ISSUE TITLE
Missing translation in External storage back-end and LDAP wizard

### ISSUE THREAD

**Issue by vidaren** [owncloud/core#16559]
### Steps to reproduce
1. Run the owncloud web UI as admin, using a non-English UI language.
2. Activate the following apps: External storage support, LDAP user and group backend.
3. Go to the Admin page
4. Under External storage, observe that "SFTP with secret key login" is never translated.
5. Under LDAP, observe that the tool tips for the three small buttons top left are never translated.

### Expected behaviour
The following strings should be translated in web UI and translatable on Transifex:
* "SFTP with secret key login" (external storage back-end)
* "Adds a new and blank configuration" (tool-tip on button on page 1 of LDAP configuration)
* "Copy current configuration into new directory binding" (LDAP button tool-tip like above)
* "Delete the current configuration" (LDAP button tool-tip like above)

### Actual behaviour
The above strings are not translated in the web UI and do not appear on Transifex.

### Server configuration
**Operating system**: FreeBSD 10.1-RELEASE

**Web server:** nginx 1.8.0

**Database:** SQLite

**PHP version:** 5.6.8

**ownCloud version:** 8.1 beta 2 (daily) as of 2015-05-23

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:** All official apps, no other apps. Specifically for this issue: External storage support, LDAP user and group backend.

**The content of config/config.php:** 

```
(Unchanged after install with SQLite selected)
```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox 38.0.1

**Operating system:** OS X Mavericks

#### Web server error log
```
nothing relevant here
```

#### ownCloud log (data/owncloud.log)
```
nothing relevant here
```

#### Browser log
```
nothing relevant here

**Comment by PVince81** [comment]
@DeepDiver1975 can you check if the bot is sleeping ?

**Comment by DeepDiver1975** [comment]
String is not marked as translatable - https://github.com/owncloud/core/blob/master/apps/files_external/appinfo/app.php#L230

**Comment by mmattel** [comment]
As both PR are now merged, we can close this issue.
