### ISSUE TITLE
Thumbnail API asks for a preview twice each time

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#16551]
### ENV
Master only, PHP 5.5, Redis cache

### Steps to reproduce
1. Add this at the top of your getPreview method
`\OCP\Util::writeLog('core', 'CALLING GETPREVIEW ', \OCP\Util::DEBUG);`
2. Go to http://localhost/index.php/apps/files/api/v1/thumbnail/300/300/test.jpg
2. Check the logs

### Expected result
The logs should show one "CALLING GETPREVIEW" message

### Actual result
The logs show 2 "CALLING GETPREVIEW" message

The controller is here, but I don't see anything suspicious
https://github.com/owncloud/core/blob/master/apps/files/controller/apicontroller.php#L76

I thought it could be my code, but using the URL used by the Files app or the Gallery app don't exhibit the same problem.

**Comment by oparoz** [comment]
@rullzer - Can you confirm this?

**Comment by PVince81** [comment]
CC @georgehrke 

This can probably be bisected to find out when it got broken

**Comment by georgehrke** [comment]
I'm on PHP 5.5 as well and it's only called once for me.
- only one log entry
- XDebug hits the breakpoint only one time as well

I don't have a redis cache set up, but that shouldn't cause such errors (hopefully)

**Comment by georgehrke** [comment]
@PVince81 Can you reproduce this behavior?

**Comment by PVince81** [comment]
What am I doing wrong ?

I have a file called "test.jpg" in the root.
But this:
```
curl http://root:admin@localhost/index.php/apps/files/api/v1/thumbnail/300/300/test.jpg
```

gives me a 404

**Comment by PVince81** [comment]
damn copy-paste, I forgot the context path...

**Comment by PVince81** [comment]
I only get the log message once when downloading the preview with curl.

**Comment by PVince81** [comment]
aka WORKFORME :wink:

**Comment by rullzer** [comment]
Same here.. only 1 log message...

**Comment by PVince81** [comment]
@oparoz please double check your steps

**Comment by oparoz** [comment]
Hmmm... I've just tried again and same problem, but my branch is a bit behind. I'll try again after a pull.

```
  'version' => '8.1.0.6',
  'logtimezone' => 'UTC',
  'installed' => true,
  'forcessl' => true,
  'loglevel' => '0',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'preview_max_x' => 756,
  'preview_max_y' => 756,
  'preview_max_scale_factor' => 2,
  'theme' => '',
  'maintenance' => false,
  'skeletondirectory' => '',
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\JPEG',
    1 => 'OC\\Preview\\PNG',
    2 => 'OC\\Preview\\TXT',
    3 => 'OC\\Preview\\Postscript',
  ),
```

**Comment by oparoz** [comment]
Thanks for testing guys. It turns out it's a browser issue. I have no idea why, but after a while, Firefox tries to make the same request 2 or even 3 times... Might have something to do with having several tabs open for the same cloud.
