### ISSUE TITLE
"impossible to save email configuration"

### ISSUE THREAD

**Issue by gerroon** [owncloud/core#16552]
I get the exact same error as described in the forum posts.

 https://forum.owncloud.org/viewtopic.php?t=27861&p=85379

**Comment by PVince81** [comment]
This is suspicious:
```
Compilation failed: internal error: previously-checked referenced subpattern not found at offset 728 at \/volume1\/Web\/owncloud\/3rdparty\/phpmailer\/phpmailer\
```

Can you please use the issue template https://raw.githubusercontent.com/owncloud/core/master/issue_template.md ?

How did you install/upgrade ownCloud ? Maybe something went wrong when replacing the source code files ?

**Comment by RealRancor** [comment]
Dup of https://github.com/owncloud/core/issues/16720

Seems to be a bug in PHP

**Comment by MorrisJobke** [comment]
Looks like a PHP bug: https://github.com/owncloud/core/issues/16720#issuecomment-110051198

Therefore closing this.

@gerroon Feel free to report back and reopen this if this isn't the case.
