### ISSUE TITLE
Group Admin see wrong number of users in "Everyone"  counter.

### ISSUE THREAD

**Issue by arm2arm** [owncloud/core#16566]
My Setup is OC8.0.3 ubuntu 15 with mariadb.
Assuming we have group admin A with two groups GG and MM with: A,B,C,D,E,F 6  users

If we put all users to GG and MM groups then Everyone shows 12 instead of 6 users.
Everyone 12
GG 6 
MM 6 
Now if you click to Everyone you see 6 users but Everyone shows 12 which is confusing.
in the settings/ajax/gateeveryonecount.php the function for the group admin returns non unique count of the users:
  $userCountArray = \OC::$server->getUserManager()->countUsers();

        if (!empty($userCountArray)) {
                foreach ($userCountArray as $classname => $usercount) {
                        $userCount += $usercount;
                }
        }

**Comment by PVince81** [comment]
Ah yes, it seems to count users in several groups multiple times.

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/20157
