### ISSUE TITLE
http prequest run forever and freeze the interface

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#16560]
If the remote server doesn't response to a post request the http requests run forever and freeze the interface.

In the past we had a timeout to prevent it  (https://github.com/owncloud/core/commit/5f044ebf1bc6f45acec2e79dc05185acd0405f42#diff-d3fcad49ec7088a1005cfe4a3b4bd62fL181), but it seems that it gets lost with this changes by @LukasReschke  https://github.com/owncloud/core/commit/5f044ebf1bc6f45acec2e79dc05185acd0405f42

@LukasReschke can you have a look? Thanks!

@DeepDiver1975 @karlitschek should probably be addressed for 8.1 because it can for example freeze server-to-server sharing. I set the milestone to 8.1... Feel free to adjust it.

**Comment by LukasReschke** [comment]
Unit test and potential patch is at https://github.com/owncloud/core/pull/16561
