### ISSUE TITLE
Usability issue: Icon listing instead of dropdown

### ISSUE THREAD

**Issue by shaneonabike** [owncloud/core#16571]
When I first used ownCloud I did not realize that other functionality was available in the dropdown of Files (read: I didn't realize the other sections like Calendar, etc where located there). Normally, when I see this type of functionality I think that it is the settings for "Files". (I could be the only one).

BUT I got thinking why we don't provide icons across the top (with / without the option to display text of each app below). This way a user can click on each section as they need. One mobile apps we could use the standard three lined menu for users to compress all these icons if they don't fit properly.

Thoughts?

**Comment by jancborchardt** [comment]
I also thought about that often and we discussed it in the past. There’s even an app to implement that functionality: https://apps.owncloud.com/content/show.php/Direct+Menu?content=169148

What do you think @karlitschek @owncloud/designers?

**Comment by stefan-niedermann** [comment]
counterproposal: as part of first-run-wizard app, there should be a guide / tour through owncloud. 
e.g. we could
- draw an arrow to the drop-down-menu top left or
- expand the app-menu as default at first run (maybe hiding it again with an animation?)

if we show icon listing instead of drop down this clutters the interface too much imho - i like it clean at it is.
and: if a person only one time has clicked one of the drop down-menus, he will understand it.

**Comment by shaneonabike** [comment]
Could I propose that perhaps you offer both. In reference to
    usability I think it's important to think about all kinds of
    disabilities and accessibility. Specifically, when I reported this I
    was thinking that you cannot really tab through to various apps with
    the drop-down. Thus making the interface less accessible to users
    who need that functionality in order to navigate sites.
    
    Might I propose that the default is all icons displayed, and then
    the option to compact the icons into one dropdown?
    
    Sincerely
    
    Shane
    
    On 2015-09-18 07:41 AM, Niedermann
      IT-Dienstleistungen wrote:
    
    
      counterproposal: as part of first-run-wizard app, there should
        be a guide / tour through owncloud. 
        e.g. we could
      
        draw an arrow to the drop-down-menu top left or
        expand the app-menu as default at first run (maybe hiding it
          again with an animation?)
      
      if we show icon listing instead of drop down this clutters the
        interface too much imho - i like it clean at it is.
        and: if a person only one time has clicked one of the drop
        down-menus, he will understand it.
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 
      
        Shane Bill
        Web Development & Consultant
        
          
            
              E-mail
              shanebill@gmail.com
                
            
            
              Phone
              438-934-2624
            
            
              More information
              https://develop.beesonabike.com

**Comment by jancborchardt** [comment]
@stefan-niedermann yeah, I also thought about that. You want to take a stab at this?

@shaneonabike 

> you cannot really tab through to various apps with the drop-down

You can though. Tab to the dropdown, press enter and then continue tabbing.


> Might I propose that the default is all icons displayed, and then the option to compact the icons into one dropdown?

I’d say something like the most used apps could be shown by default – definitely not all. Files, Calendar, Mail come to mind as apps which could be shown by default. Others are not necessarily used on a daily basis.

**Comment by MorrisJobke** [comment]
I like the icons in the top bar. For sure only some of the "core"/official apps should be in there and all others are in the usual dropdown. The same applies for mobile interface. There the dropdown should hold everything.
