### ISSUE TITLE
Undefined index: dirname

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#16572]
```json


{
  "reqId": "yusKBpsXGq\/uZFpkjcmM",
  "remoteAddr": "192.168.178.24",
  "app": "PHP",
  "message": "Undefined index: dirname at \/home\/deepdiver\/Development\/ownCloud\/core\/apps\/files_versions\/lib\/storage.php#358",
  "level": 3,
  "time": "2015-05-27T07:53:55+00:00",
  "method": "GET",
  "url": "\/oc-shib\/core\/cron.php"
}

**Comment by PVince81** [comment]
I see this happen too when I rename a file that has versions.
Maybe we're just lucky that at the exact same time cron.php is running ?

**Comment by PVince81** [comment]
Hmm, cannot reproduce it consistently.

But I suspect that it might happen if the file was scheduled for expiration, but then before cron ran the file was renamed. So obviously at time of expiration the file is gone, so the expire job should give up.

**Comment by PVince81** [comment]
Steps:
1. Create a file "versions.txt" with some contents
2. Edit "versions.txt" again and save (this will create a version and schedule an expire job)
3. Directly rename "versions.txt" to "renamed.txt"
4. Run cron
