### ISSUE TITLE
External storage doesn't show groups in the "available for" field after reloading the page

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#16582]
### Steps to reproduce
1. Configure an external storage
2. For the configured storage In the "Available for" field configure a group
3. Reload the page

### Expected behaviour
The "Available for" contains the group previously set

### Actual behaviour
The "Available for" doesn't contain the group.  It seems to be a visual issue since the external storage app works as intended

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** sqlite3

**PHP version:** 5.5.9

**ownCloud version:** stable7 (55a122a9fecabc928162cab1346c22e3e7c86f70)

**Updated from an older ownCloud or fresh install:** fresh install

**List of activated apps:**
 - files
 - files_external
 - files_sharing
 - files_trashbin
 - files_versions
 - firstrunwizard
 - user_ldap

### Notes

It might be related to https://github.com/owncloud/core/issues/13781

OC 7.0.5 shows the groups but not the LDAP users. stable7 (55a122a9fecabc928162cab1346c22e3e7c86f70) shows the LDAP users but not the groups

**Comment by PVince81** [comment]
Hmmm, according to @MorrisJobke said here https://github.com/owncloud/core/issues/13781#issuecomment-99344802 that the fix should be on stable7 already but if you're still seeing it for groups.

@jvillafanez does this also happen on master ?

**Comment by PVince81** [comment]
CC @blizzz

**Comment by MorrisJobke** [comment]
ref #15833

**Comment by jvillafanez** [comment]
Master (b1ac53867948ce69941aab69695cb9b5bcaf56e0) seems to work fine, I can't reproduce the issue there

**Comment by blizzz** [comment]
On current stable7 i see neither local nor LDAP groups. However I continue to see both local and LDAP users.

**Comment by blizzz** [comment]
It also works on stable8. index.php/displaynames on stable7 does return the groups, but with boolean false as display name for groups. The implementation however solely returns usernames, but does nothing with groups. The implemtation in OC 8 does it too, but falls back on the provided name. In cases of groups, this is kind of OK … though not totally correct. master does not differ from OC 8 in this case.

I will prepare an PR to align this, but we should come up with a better solution in a future major release.

**Comment by blizzz** [comment]
Fixed by https://github.com/owncloud/core/pull/16773 for 7.0.7
