### ISSUE TITLE
[7.0.5] LDAP user can not be deleted.

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#16588]
### Expected behavior:
Erase LDAP user and the user does not appear, the data folder is erased and the user does not appear in any groups.
### Actual behavior:
Erase LDAP user and the user does not appear, the data folder still exist and the user appears in the groups.

### Architecture
oC7.0.5
php 5.4
Ubuntu 14.04

#### LDAP configuration:

S3-ownCloud\Shared\owncloud\support\github-issues\core\16588

@MorrisJobke 

00003201

**Comment by MorrisJobke** [comment]
This only happens when the username is different from the user folder name. (i.e. when you specified the home folder naming rule in the LDAP app)

Reason:

User gets deleted and afterwards the users folder is fetched in https://github.com/owncloud/core/blob/7385b5dad949e95786a54f56d39ea14f21057369/lib/private/user/user.php#L190 -> then the user is already deleted and the fallback of folder name is used in there: https://github.com/owncloud/core/blob/7385b5dad949e95786a54f56d39ea14f21057369/lib/private/user.php#L574-574

I tried the following, but didn't have the time yet to verify if this works:

```patch
diff --git a/lib/private/user/user.php b/lib/private/user/user.php
index 28b66d7..e1ee4aa 100644
--- a/lib/private/user/user.php
+++ b/lib/private/user/user.php
@@ -174,6 +174,9 @@ class User implements IUser {
                if ($this->emitter) {
                        $this->emitter->emit('\OC\User', 'preDelete', array($this));
                }
+               // homeDir needs to be retrieved before the user is deleted - otherwise it isn't correct and the fallback is used
+               $homeDir = \OC_User::getHome($this->uid);
+
                $result = $this->backend->deleteUser($this->uid);
                if ($result) {
 
@@ -187,7 +190,7 @@ class User implements IUser {
                        \OC::$server->getConfig()->deleteAllUserValues($this->uid);
 
                        // Delete user files in /data/
-                       \OC_Helper::rmdirr(\OC_User::getHome($this->uid));
+                       \OC_Helper::rmdirr($homeDir);
 
                        // Delete the users entry in the storage table
                        \OC\Files\Cache\Storage::remove('home::' . $this->uid);
```

**Comment by MorrisJobke** [comment]
For the group issue we need to have an additional look why the group memberships aren't updated. Maybe a caching issue.

**Comment by cdamken** [comment]
@MorrisJobke I have another case:

00002761

Where the username and folder are the same, but still does not delete the folders:

Full text in: S3-ownCloud\Shared\owncloud\support\github-issues\core\16588\00002761.txt

**Comment by MorrisJobke** [comment]
I will have a look at this today or tomorrow

**Comment by blizzz** [comment]
@cdamken 

>  the data folder still exist and the user appears in the groups.

The data folder removal is fixed in https://github.com/owncloud/core/pull/16890 but can you elaborate on the group thing?

**Comment by pako81** [comment]
I am following this up. Regarding the group issue, Customer wrote:

"Here's the output of the OCC tool, which works now. The User Heinrich has been removed from the ownCloud LDAP Group months ago.

root@atldwosx015:/var/www/owncloud# sudo -u www-data php occ ldap:check-user 
Heinrich

The user is still available on LDAP. What can we do to get this working?"

Thus group assignments are not removed upon cleanup.

**Comment by blizzz** [comment]
@cdamken @pako81 can you check whether  #16890 fixes the issue?

**Comment by MorrisJobke** [comment]
@cdamken I asked for a backport to stable7 and stable8

**Comment by karlitschek** [comment]
Backport is fine with me if @MorrisJobke and @blizzz agree.

**Comment by blizzz** [comment]
Backport to 7: #17034
Backport to 8: #17033

**Comment by bboule** [comment]
@cdamken do you have what you need to move forward here and deliver this to the user?

**Comment by MorrisJobke** [comment]
> @cdamken do you have what you need to move forward here and deliver this to the user?

We **ONLY** deliver releases.

**Comment by bboule** [comment]
OK Ill do it... thanks

**Comment by craigpg** [comment]
We may need to deliver a patch for 7.0.5 that we can test / validate with the user who reported this ahead of the next maintenance release.  Is #17034 what we need?

**Comment by cdamken** [comment]
@craigpg @blizzz @MorrisJobke  Yes, the patch is needed for 7.05.

In the other hand I see some problems like https://github.com/owncloud/core/pull/17110 that could affect the functionality? What should we do? Provide the patch or better try 7.0.7?

**Comment by MorrisJobke** [comment]
> We may need to deliver a patch for 7.0.5 that we can test / validate with the user who reported this ahead of the next maintenance release. Is #17034 what we need? @blizzz, @MorrisJobke

For testing purposed the patch can be delivered via https://patch-diff.githubusercontent.com/raw/owncloud/core/pull/17034.patch If this should go to production we need a QA run on the patch on top of 7.0.5 which needs to be coordinated with @jnfrmarks

**Comment by jnfrmarks** [comment]
I'm happy to test but need a bit of clarification on what needs to be tested and what version/patch is being tested.

**Comment by cdamken** [comment]
@jnfrmarks  we need to test:

https://patch-diff.githubusercontent.com/raw/owncloud/core/pull/17034.patch

against: 7.0.5 Server

**Comment by jnfrmarks** [comment]
@MorrisJobke @blizzz @cdamken 

Can I get some clarification on what needs to be tested?
