### ISSUE TITLE
LIKE queries do not properly escape special characters

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#16580]
While reviewing https://github.com/owncloud/core/pull/16576  I noticed that our code base is often using `LIKE` queries but not properly escaping special characters such as `%` or `_`. This leads to all kind of different bugs and unpredictable behaviour.

The easiest way to understand the impact is to mess with the file cache which calls [`\OC\Files\Cache\Cache::move`](https://github.com/owncloud/core/blob/3de945d13da0016cd8c602867ff18a33c2534418/lib/private/files/cache/cache.php#L503-L511) which in turns calls [`\OC\Files\Cache\Cache::moveFromCache`](https://github.com/owncloud/core/blob/3de945d13da0016cd8c602867ff18a33c2534418/lib/private/files/cache/cache.php#L523-L561) which performs the following query:

``` php
$sql = 'SELECT `path`, `fileid` FROM `*PREFIX*filecache` WHERE `storage` = ? AND `path` LIKE ?';
$result = \OC_DB::executeAudited($sql, [$sourceStorageId, $sourcePath . '/%']);
$childEntries = $result->fetchAll();
```

`$sourcePath` is the original file name and thus completely user controlled input.
1. Create a folder `test%` and upload a file `bar.txt` to it 
2. Create a folder `test` with a subfolder `foo` and a file `foo.txt` in the subfolder
3. Create a folder `newFolder` and move the folder `test%` to it

The file cache will now look like:

<table border="1" style="border-collapse:collapse">
<tr><th>fileid</th><th>storage</th><th>path</th><th>path_hash</th><th>parent</th><th>name</th><th>mimetype</th><th>mimepart</th><th>size</th><th>mtime</th><th>storage_mtime</th><th>encrypted</th><th>unencrypted_size</th><th>etag</th><th>permissions</th></tr>
<tr><td>1</td><td>1</td><td></td><td>d41d8cd98f00b204e9800998ecf8427e</td><td>-1</td><td></td><td>2</td><td>1</td><td>163</td><td>1432728755</td><td>1432728754</td><td>0</td><td>0</td><td>5565b4b3194a3</td><td>23</td></tr>
<tr><td>2</td><td>1</td><td>files</td><td>45b963397aa40d4a0063e0d85e4fe7a1</td><td>1</td><td>files</td><td>2</td><td>1</td><td>163</td><td>1432728790</td><td>1432728786</td><td>0</td><td>0</td><td>5565b4d62238a</td><td>31</td></tr>
<tr><td>12</td><td>1</td><td>files/newFolder</td><td>c78ce8e4561976a860eac269e36e2950</td><td>2</td><td>newFolder</td><td>2</td><td>1</td><td>163</td><td>1432728790</td><td>1432728786</td><td>0</td><td>0</td><td>5565b4d622a1f</td><td>31</td></tr>
<tr><td>8</td><td>1</td><td>files/newFolder/test%</td><td>fc1c5d837043687963e6af53d55b0294</td><td>12</td><td>test%</td><td>2</td><td>1</td><td>163</td><td>1432728769</td><td>1432728769</td><td>0</td><td>0</td><td>5565b4c136bbd</td><td>31</td></tr>
<tr><td>3</td><td>1</td><td>files/newFolder/test%/bar.txt</td><td>5d1ac08f101e4787b9718feaa4f2bdd2</td><td>8</td><td>bar.txt</td><td>4</td><td>3</td><td>163</td><td>1432728752</td><td>1432728752</td><td>0</td><td>0</td><td>00567aaadf23d59167fedf7ce994f42f</td><td>27</td></tr>
<tr><td>10</td><td>1</td><td>files/newFolder/test%foo</td><td>ed06cf9a38f1cb269f1e7cc5c302cad2</td><td>9</td><td>foo</td><td>2</td><td>1</td><td>0</td><td>1432728780</td><td>1432728780</td><td>0</td><td>0</td><td>5565b4ccdbdaf</td><td>31</td></tr>
<tr><td>11</td><td>1</td><td>files/newFolder/test%foo/bar.txt</td><td>af0d4adcf7153cfca3a9802f6c79e24c</td><td>10</td><td>bar.txt</td><td>4</td><td>3</td><td>0</td><td>1432728780</td><td>1432728780</td><td>0</td><td>0</td><td>957b1881d70547e1a631d4ea530da69c</td><td>27</td></tr>
<tr><td>9</td><td>1</td><td>files/test</td><td>d9da358780951c01e7388fcaa673ba64</td><td>2</td><td>test</td><td>2</td><td>1</td><td>0</td><td>1432728780</td><td>1432728778</td><td>0</td><td>0</td><td>5565b4ccdb5c1</td><td>31</td></tr>
<tr><td>4</td><td>1</td><td>thumbnails</td><td>3b8779ba05b8f0aed49650f3ff8beb4b</td><td>1</td><td>thumbnails</td><td>2</td><td>1</td><td>46083</td><td>1432728755</td><td>1432728754</td><td>0</td><td>0</td><td>5565b4b31990a</td><td>31</td></tr>
<tr><td>5</td><td>1</td><td>thumbnails/3</td><td>209c5872e8bcb201307e173b868b0b50</td><td>4</td><td>3</td><td>2</td><td>1</td><td>46083</td><td>1432728755</td><td>1432728755</td><td>0</td><td>0</td><td>5565b4b319d73</td><td>31</td></tr>
<tr><td>6</td><td>1</td><td>thumbnails/3/2048-2048-max.png</td><td>4316b1b309221bd91de28723a48e6c6c</td><td>5</td><td>2048-2048-max.png</td><td>6</td><td>5</td><td>44133</td><td>1432728755</td><td>1432728755</td><td>0</td><td>0</td><td>15c52a773db056e42d5a5e9be23b6c87</td><td>27</td></tr>
<tr><td>7</td><td>1</td><td>thumbnails/3/36-36.png</td><td>0b7c345caa4eeb6a11b973bbde9d3bf3</td><td>5</td><td>36-36.png</td><td>6</td><td>5</td><td>1950</td><td>1432728755</td><td>1432728755</td><td>0</td><td>0</td><td>a3e86e135513b0a1e8f8286c547438af</td><td>27</td></tr></table>

Any special characters needs to be properly escaped as done for example in the news app: https://github.com/owncloud/news/blob/7652b34dac7bd80b29345635632bfdd57b037e98/db/itemmapper.php#L59-L70

<hr/>

Proposed steps:
1. Grep through all usages of LIKE
2. Properly escape all wrong usages and assess the impact

<hr/>

@DeepDiver1975 Please triage.

**Comment by LukasReschke** [comment]
cc @icewind1991 Because file system fun :see_no_evil:

**Comment by LukasReschke** [comment]
This may have potential security impact as all other queries as well. Moved back to 9.0.

**Comment by PVince81** [comment]
PR from @icewind1991 here https://github.com/owncloud/core/issues/16604

**Comment by MorrisJobke** [comment]
Pas are merged. Will be in 8.2.1 and 9.0.0

**Comment by icewind1991** [comment]
Those PR's only fixed one specific case with the cache, not the overall issue

**Comment by PVince81** [comment]
@mrow4a I heard you like database stuff ? 😉
