### ISSUE TITLE
No file_locking if encryption is enabled

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#16586]
I just discovered that we disable file_locking completely if encryption is enabled.

This happens because the encryption stream wrapper returns always 'false' on isLocal() if encryption is enabled. This behavior was discussed and implemented here by @DeepDiver1975 @icewind1991 @VicDeo and @PVince81 https://github.com/owncloud/core/issues/15848

I can understand the reasons for that, but probably we need to adjust the way we apply the files_locking wrapper in this case. Maybe by changing https://github.com/owncloud/files_locking/blob/master/lib/lockingwrapper.php#L203 to something like:

````
if ($storage->instanceOfStorage('OC\Files\Storage\Local') && !$storage->instanceOfStorage('\OC\Files\Storage\MappedLocal'))
````

Opinions?

**Comment by PVince81** [comment]
From what I remember, in the past the files_locking app was active together with encryption (I remember seeing bugs in the past related to that).

The change @schiesbn proposed sounds sensible.
