### ISSUE TITLE
Database Error Leads to Internal Server Error (500)

### ISSUE THREAD

**Issue by marioskourtesis** [owncloud/core#16590]
### Actual behaviour

The server is responding Internal Server Error 500. This error is repeated and exhausts the server resources.

### Server configuration
**Operating system**: CentOS 7

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 5.4.16

**ownCloud version:** 8.0.3

**List of activated apps:**
Activity, Deleted files, external storage support, File locking, first run wizard,
mail template editor, pdf viewer, pictures, provisioning Api, share files, text editor,
updates, versions, video viewer.

**The content of config/config.php:**

  'dbtype' => 'mysql',
  'version' => '8.0.3.4',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'installed' => true,
  'maintenance' => false,
  'loglevel' => 0,

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** webdav

#### Web server error log

X.X.X.X - user [27/May/2015:16:30:46 +0200] "PUT /remote.php/webdav/Products/QualityMonitor/XXX/Pilot/Sample%20Documentation/XXX/79159.xhtml HTTP/1.1" 201 - "-" "Mozilla/5.0 (Macintosh) mirall/1.8.1"

#### MariaDB
```
SHOW ENGINE INNODB STATUS
---TRANSACTION A84B7ED, ACTIVE 3 sec starting index read
mysql tables in use 1, locked 1
LOCK WAIT 2 lock struct(s), heap size 488, 1 row lock(s)
MySQL thread id 61, OS thread handle 0x7fb9e85a3700, query id 21659 localhost owncloud Updating
UPDATE `oc_filecache` SET `permissions`='27' WHERE `fileid` = '79919'
------- TRX HAS BEEN WAITING 3 SEC FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 0 page no 14236 n bits 128 index `PRIMARY` of table `owncloud`.`oc_filecache` trx id A84B7ED lock_mode X locks rec but not gap waiting
------------------
TABLE LOCK table `owncloud`.`oc_filecache` trx id A84B7ED lock mode IX
RECORD LOCKS space id 0 page no 14236 n bits 128 index `PRIMARY` of table `owncloud`.`oc_filecache` trx id A84B7ED lock_mode X locks rec but not gap waiting
---TRANSACTION A84B79F, ACTIVE 23 sec
32 lock struct(s), heap size 10680, 1327 row lock(s), undo log entries 1327
MySQL thread id 33, OS thread handle 0x7fb9e8511700, query id 33246 localhost owncloud
TABLE LOCK table `owncloud`.`oc_filecache` trx id A84B79F lock mode IX
RECORD LOCKS space id 0 page no 14236 n bits 128 index `PRIMARY` of table `owncloud`.`oc_filecache` trx id A84B79F lock_mode X locks rec but not gap
RECORD LOCKS space id 0 page no 13675 n bits 136 index `PRIMARY` of table `owncloud`.`oc_filecache` trx id A84B79F lock_mode X locks rec but not gap

```
#### ownCloud log (data/owncloud.log)

```{"reqId":"d51760956bb7ad62958978cfadbd8768","remoteAddr":"X.X.X.X","app":"core","message":"Exception while scanning file \"QualityMonitor\/XXX\/Pilot\/Sample Documentation\/XXX\/76376.xhtml\": An exception occurred while executing 'UPDATE `oc_filecache` SET `permissions`=? WHERE `fileid` = ?' with params [27, \"79919\"]:\n\nSQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction","level":0,"time":"2015-05-27T14:09:11+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/Products\/QualityMonitor\/XXX\/Pilot\/Sample%20Documentation\/XXX"}```

**Comment by LukasReschke** [comment]
Transaction related stuff: cc @PVince81 @icewind1991

**Comment by PVince81** [comment]
@marioskourtesis are you sure it's 503 and not 500 ? Because 503 is "Service not available" while 500 is Internal server error.

This is likely to be due to two scanners trying to scan the same folder at the same time, but only one transaction can succeed.

On the other hand when trying to reproduce this I got different results: #16584

**Comment by marioskourtesis** [comment]
Hello PVince81,
I am sorry, you are right, I just checked Apache log files and and the error is 500.
Thanks

**Comment by marioskourtesis** [comment]
Hello,
This happening constantly, and the owncloud service after a few hours is not available... Is there anything that I can do about it?

**Comment by PVince81** [comment]
I see you don't have external storage.
Do you access the data folder outside of ownCloud ? Or is it used exclusively from ownCloud ?
If exclusive, you could try setting this https://github.com/owncloud/core/blob/master/config/config.sample.php#L910 to zero.

**Comment by marioskourtesis** [comment]
I access the data using the ownCloud client and web interface.

**Comment by PVince81** [comment]
Which both are through ownCloud, yes. So that setting should be safe to use for you.

**Comment by marioskourtesis** [comment]
Hello PVince81, 
Thank you very much from clarifying that!
The configuration that you mentioned fixed the problem!
Although, this seems to be a temporary fix, should I re-enable "filesystem_check_changes" after your official update ?

**Comment by PVince81** [comment]
I think you can leave it always disabled.

**Comment by PVince81** [comment]
In 8.1.3 and 8.2 there's this feature called transactional file locking which should prevent trying to access files or the DB when the file is locked. See https://doc.owncloud.org/server/8.1/admin_manual/configuration_files/files_locking_transactional.html

If you're still seeing issues in these versions, feel free to reopen.
