### ISSUE TITLE
Migrate password protected public link hashes to the new hash within DB

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#16594]
https://github.com/owncloud/core/blob/7385b5dad949e95786a54f56d39ea14f21057369/apps/files_sharing/lib/helper.php#L129-L140

#10671 is merged now 

Somthing like `\OCP\Share::setPassword($shareId, $password);` should do the trick

cc @LukasReschke @rullzer

**Comment by LukasReschke** [comment]
> Somthing like \OCP\Share::setPassword($shareId, $password); should do the trick

No. Because `\OCP\Share::setPassword` has an hard-coded dependency on `\OC\Server::getUserSession` and passes this to `\OC\Share\Share::setPassword`. `\OC\Share\Share::setPassword` in turn requires that the passed UserSession (we cant pass an uid!) belongs to the share owner :see_no_evil:

**Comment by rullzer** [comment]
Like @LukasReschke says there are some deps on the userSession. This to make sure that I users can only edit their own shares. 

A different function should not be to hard. But do we really want that? Or should be provide a way to override the current behaviour?

**Comment by rullzer** [comment]
This also seems like something we want to handle on a more abstract level. Basically we want to ask to the share stuff is this the correct password. That part of the code can then automatically update the hash.

**Comment by rullzer** [comment]
Assigning to myself so I don't forget this for sharing 2.0
