### ISSUE TITLE
Can't log out when using HTTP Basic Auth

### ISSUE THREAD

**Issue by vi** [owncloud/core#16598]
My ownCloud deployment is protected by HTTP Basic Auth.

If I specialy a HTTP user which is also a ownCloud user, ownCloud conveniently log me in automatically.

But I can't log out in that case. Pressing "log out" entry does nothing (probably ownCloud logs me in automatically the second time).

Workaround: specify some other user for HTTP Basic auth which is not ownCloud user. In this case ownCloud lets me log out and shows usual "login/password" page where I can log in as administrator, for example.

**Comment by LukasReschke** [comment]
This is actually the expected behaviour at the moment. Once we have refactored the login and something like https://github.com/owncloud/core/issues/15894 this should work better though…

**Comment by PVince81** [comment]
@LukasReschke would it make sense to create a new Github tag to track authentication/session related issues ?
