### ISSUE TITLE
Unable to create new user after update

### ISSUE THREAD

**Issue by ClaudeMa** [owncloud/core#16602]
Owncloud 8.0.3
Database Mysql 
after update from version 8.0.2
Unable to create user: Owncloud say "a user with that name exist" but no user with new name exists

see screenshoot
![owncloud](https://cloud.githubusercontent.com/assets/2773730/7857614/01f61e30-0532-11e5-9b43-0b87476183b6.JPG)

**Comment by RealRancor** [comment]
Hi,

please disable the user_webdavauth (Webdav user backend) and try again:

https://forum.owncloud.org/viewtopic.php?f=17&t=20221

Refs: https://github.com/owncloud/core/issues/16487 , https://github.com/owncloud/core/issues/14177 and so on.

**Comment by LukasReschke** [comment]
@karlitschek Can we rename "WebDav user backend" in something that hopefully less users click on? :-(

**Comment by karlitschek** [comment]
yes. i had the same tought. suggestions? :-)

**Comment by RealRancor** [comment]
Isn't it possible to integrate this app completely into the user_external app https://github.com/owncloud/apps/tree/master/user_external ?

**Comment by ClaudeMa** [comment]
@RealRancor 

thank it work disabling  user_webdavauth
