### ISSUE TITLE
After the Update to ownCloud 8.0.3 I could only sync one calendar

### ISSUE THREAD

**Issue by Tronde** [owncloud/core#16609]
Dear Developers,

a few days ago I have made an Update from ownCloud 8.0.2 to 8.0.3. Since then I'm not able to sync more than one calendar.

The first calendar in the ownCloud calendar-App is synced with two Thunderbird Lighting, an iOS device and an Android tablet. And everything works fine. In Lightning I use the CalDAV-Link from the calendar instead of the primary CalDAV-Address from the settings. On my Android-Device I use the primary CalDAV-Address from the settings.

I created a second calendar which I share with a group of my ownCloud users. I added this calendar to Lightning and Android, too.

For syncing with Android I use the App "CalDav Sync Adapter" from gege.

Everything seems to work fine.

The next day I noticed that the sync of the second calendar on all devices but one is broken. In Lightning I only see the message that the calendar is not available at the moment. In Android I get the message: "Only one root element allowed".

I deleted the second calender from all devices and from my ownCloud and created a new one which I added to all my devices again. I did it the same way I described above.

And today, after a day the sync was working, it is broken again.

It would be very nice if you could help me on this issue. If you need any further information, please don't hesitate to tell me what information do you need.

Best regards,
Tronde

**Comment by karlitschek** [comment]
Thanks for your bug report. This sounds like a bug in the calendar app. Can you please open this in the calendar app? Thanks

**Comment by RealRancor** [comment]
@Tronde 
When re-opening there make sure that you're using the issue template as described here:

https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version

which asks you for logfiles and some more infos about your environment which are currently missing.
