### ISSUE TITLE
Do not show upgrade button when new app is incompatible

### ISSUE THREAD

**Issue by sedrubal** [owncloud/core#16600]
### Steps to reproduce
1. Install oc `8.0.3` (not `8.1`)
2. Install News App v `5.2.8`
3. Go to admins app page

### Expected behaviour
Nothing special

### Actual behaviour
OC shows a button to upgrade the plugin to `5.3.4`, but this version is not supported for oc `8.0.3` and clicking on upgrade is not succsessful.

### Server configuration
**Operating system**: ubuntu
**Web server:** apache
**Database:** mysql
**PHP version:** `5.5.9`
**ownCloud version:** `8.0.3.4`
**Updated from an older ownCloud or fresh install:** almoust all older versions since 7
**List of activated apps:** news, ...
**The content of config/config.php:**

```
nothing interesting
```

**Are you using external storage, if yes which one:** no
**Are you using an external user-backend, if yes which one:** no

**Comment by PVince81** [comment]
There is a difference between "upgrade not successful due to an error during upgrade" and "app is known to not be supported on that OC version".

If what you observed is the latter (appfino/info.xml contains incompatible OC version), then it should be possible to hide the button.

However if this is an unpredictable upgrade issue, then it is not possible to hide the button in advance.

CC @Raydiation

**Comment by RealRancor** [comment]
Yepp, it seems that the News App 5.3.4 for which the update button is shown is currently only comaptible with OC 8.1:

https://github.com/owncloud/news/blob/master/appinfo/info.xml#L23-L24

So if an app is providing the "requiremin" in its info.xml with a higher version than the current the "Update" button should be hidden.

**Comment by PVince81** [comment]
@RealRancor ok thanks for confirming. So this is indeed a bug.

**Comment by Raydiation** [comment]
BTW it's even noted in the app store that 8.1 is required

**Comment by RealRancor** [comment]
@Raydiation
> BTW it's even noted in the app store that 8.1 is required

If the app is installed once its not very likely that some one is having a look at the app store again.

**Comment by Raydiation** [comment]
@RealRancor what I meant is that the app store API should note that 8.1 is required

**Comment by RealRancor** [comment]
Ah, sorry. I thought you mean that people didn't checked the app store for this requirement.

**Comment by PVince81** [comment]
Closing in favor of duplicate https://github.com/owncloud/core/issues/25782
