### ISSUE TITLE
External Storage and nginx Configuration

### ISSUE THREAD

**Issue by PrahlM93** [owncloud/core#16611]
I fixed it using the patched lib/private/files.php

Thank you for your help.

**Comment by RealRancor** [comment]
Hi,

AFAIK X-Accel is currently broken in OC 8.0.3 and should be fixed with the upcoming 8.0.4: https://github.com/owncloud/core/issues/16022

**Comment by PVince81** [comment]
I believe @SergioBertolinSG just tested this recently. Did you test it on stable8 ?

**Comment by RealRancor** [comment]
@PVince81 Yes, seems so: https://github.com/owncloud/core/issues/16022#issuecomment-106438427

**Comment by PVince81** [comment]
Closing then. Thanks.
