### ISSUE TITLE
Error templates url

### ISSUE THREAD

**Issue by fabdelgado** [owncloud/core#16617]
In the readme file says: "Should be developed here Themes: https://github.com/owncloud/themes".

This url page shows 404 error.

**Comment by karlitschek** [comment]
@jancborchardt FYI

**Comment by DeepDiver1975** [comment]
> In the readme file says: "Should be developed here Themes: https://github.com/owncloud/themes".

@fabdelgado can you please point us to the file you are mentioning - I cannot find this sentence. THX

**Comment by oparoz** [comment]
@DeepDiver1975 Fixed in master already, not sure if that can be backported since the example theme has probably been updated for 8.1
https://github.com/owncloud/core/commit/cd0fa062ebea4fd1c340a31e996e033754acd456

@jancborchardt should know.

**Comment by jancborchardt** [comment]
This is fixed in master through the introduction of the example theme. Any custom themes you can develop wherever you like.

**Comment by fabdelgado** [comment]
This readme is in / themes.
Version 8 downloaded from the official website owncloud.org.

Thanks

**Comment by RealRancor** [comment]
The file is there in OC 8.0.3:

https://github.com/owncloud/core/tree/v8.0.3/themes

Seems the theme repos was kicked out recently (this repos was available some time ago) and so the link gets an 404.

**Comment by jancborchardt** [comment]
Hm, so then we should backport at least part of the new readme there (excluding mentioning the example theme) to stable8. Can someone of you @owncloud/designers do that? (I'm on vacation for the coming week, could do it after.)

**Comment by MorrisJobke** [comment]
stable7 #16634 
stable8 #16635
