### ISSUE TITLE
Wrong preview size is used for the conflict resolution modal window

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#16616]
### Env
master

### Steps to reproduce
1. Upload a Jpg
2. Upload it again
3. Look at the 2 pictures presented to you

### Expected behaviour
Both pictures should look the same

### Actual behaviour
The one on the left is a 64x64 base64 encoded image
The one on the right is a stretched 36x36 preview filling the 64x64 space.

I think someone forgot to change the dimensions in the URL querying the preview
https://github.com/owncloud/core/blob/21a1995ad66cda2712786a1cc47227452b1d84ab/core/js/oc-dialogs.js#L384-L386

**Comment by oparoz** [comment]
Even if using the proper resolution, we can't compete with using the Canvas to do a resize of the full picture..

### Before
![compare_before](https://cloud.githubusercontent.com/assets/323220/7881847/a496bcaa-0607-11e5-9e67-53d3baf95b23.png)
### After
![compare_after](https://cloud.githubusercontent.com/assets/323220/7881850/b5badcfa-0607-11e5-8186-4f04e4e96438.png)

I think it's worth fixing, do you @jancborchardt @georgehrke @DeepDiver1975

**Comment by jancborchardt** [comment]
Good catch! worth fixing for sure.

As a sidenote: why does the left image have jagged edges like that? (the owncloud logo)

**Comment by oparoz** [comment]
The image on the left is resized by the browser using HTML5's drawImage and that doesn't work well with extreme resizing like this.
To fix this would require introducing a new drawImage method which resizes several times in smaller steps...

**Comment by oparoz** [comment]
To give you an idea, this is what someone has written as a replacement... :S 
https://gist.github.com/fisch0920/37bac5e741eaec60e983

I think a better alternative would be to save the file somewhere and to generate a preview. It would also solve the double uploading bug.

**Comment by MorrisJobke** [comment]
Fixed in #16623
