### ISSUE TITLE
Configuration checks for HTTP methods

### ISSUE THREAD

**Issue by RobinMcCorkell** [owncloud/core#16625]
Similar to how we check for charset, access to data/, and other configuration things, we should attempt to check the status of the more 'esoteric' HTTP methods on the web server, for example PUT and DELETE, which may require special configuration on shared hosters: ref #10084 

Suggested implementation - an (admin-only?) controller that responds to all CRUD methods, with a null 'true' response. The admin settings page tries to access each CRUD method of that controller, printing a warning for any that it cannot access with a link to the documentation: owncloud/documentation#1162

cc @carlaschroder @VincentvgNn @RealRancor @LukasReschke @DeepDiver1975

**Comment by PVince81** [comment]
Hmm, I didn't realize that. This means that WebDAV wouldn't work properly anyway if not all methods are allowed ?

At some point I'd like to make the web UI use WebDAV too (https://github.com/owncloud/core/issues/12353).

So I guess such check makes sense.

Also note that WebDAV requires other verbs like MKCOL, MOVE, COPY, PROPFIND, PROPPATCH

**Comment by oparoz** [comment]
In my experience, you have to allow so many verbs that it's easier to go with "allow all"...
`GET POST OPTIONS PROPFIND PUT DELETE MKCOL MOVE REPORT PROPPATCH LOCK UNLOCK COPY`

**Comment by RealRancor** [comment]
Hi,

i had used:

> DELETE PROPFIND PUT GET HEAD POST OPTIONS REPORT MKCOL MOVE PROPPATCH COPY

in the past without a problem but had missed the LOCK and UNLOCK. So it also really makes sense to have an initial documentation which verbs are needed...

**Comment by Xenopathic** [comment]
Let's implement this alongside the WebDAV files app work.

**Comment by DeepDiver1975** [comment]
Did we actually face an issue where PROPFIND was working but e.g. MKCOL not?

As long as there is no real world issue -> won't fix

**Comment by fisklask** [comment]
> Did we actually face an issue where PROPFIND was working but e.g. MKCOL not?
> 
> As long as there is no real world issue -> won't fix

Just spent 3h+ troubleshooting our whole setup only to find 403 errors for MKCOL and MOVE methods - we do have a strict set of allowed methods on our load balancer.
Please add those to the checks.
