### ISSUE TITLE
Using an AD, in the resulting filter using the wizard, (primaryGroupID=513) should appear, but it doesn't. 

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16626]
### Steps to reproduce
1. Configure a right Active Directory configuration in the server tab
2. Configure User Filter in the LDAP Wizard and select a group

### Expected behaviour
on AD, the resulting filter should look like (&(|(objectclass=person))(|(|((memberof=CN=Domain Users,CN=Users,DC=madder,DC=owncloud,DC=bzoc)(primaryGroupID=513)))(|((memberof=CN=Wolfpack 8,OU=packs,DC=madder,DC=owncloud,DC=bzoc)(primaryGroupID=968988)(2 selected groups)

### Actual behaviour
The primaryGroupID does not appear.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity: 1.2.3
 - admin_audit: 0.6
 - encryption: 1.0.0
 - enterprise_key: 0.1.0
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.4
 - user_ldap: 0.6.0
 - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** ActiveDirectory

### Client configuration
**Browser:** Firefox

**Comment by davitol** [comment]
![adbehaviour2](https://cloud.githubusercontent.com/assets/10596560/7834524/5ebdb596-0470-11e5-96f4-c9557155f7ce.gif)

**Comment by davitol** [comment]
Workaround:
    going to the user filter tab
    selecting the group
    => not present in the raw filter
    unselect the group
    select the group again
    => present in the raw filter

**Comment by MorrisJobke** [comment]
This was noticed during the tests of #16456. #16456 is a backport from master and also included there and the backport to stable7 is also already merged


So this applies to stable7, stable8 and master

**Comment by davitol** [comment]
Same behaviour in stable7/8

**Comment by MorrisJobke** [comment]
the behaviour is not present in stable8 yet, but it is present in #16456

**Comment by DeepDiver1975** [comment]
> the behaviour is not present in stable8 yet, but it is present in #16456

so a clear: no-merge then?

**Comment by MorrisJobke** [comment]
> so a clear: no-merge then?

https://github.com/owncloud/core/pull/16456#issuecomment-106794688

**Comment by PVince81** [comment]
Not sure what I am doing wrong ?

My steps:
1. Input host name and port, user, password and base dn on first page
2. Click "Continue"
3. Click "group1" then click on the arrow to the right

And now I see this, and "primaryGroupID" appears in the string:
![ad-group](https://cloud.githubusercontent.com/assets/277525/7883966/d46ff460-061a-11e5-9d0d-9994807cdce3.png)

But the UI looks different ?

**Comment by PVince81** [comment]
This is on master (01a241f71129c3980619f3981d3f7903c1a4cee8)

I'll try again in stable8, maybe the UI has changed

**Comment by MorrisJobke** [comment]
> I'll try again in stable8, maybe the UI has changed

Yes it has. Keep in mind to use the branch #16456 ;)

**Comment by PVince81** [comment]
There is a race condition when saving settings from the dropdown, fixed here https://github.com/owncloud/core/pull/16456

The workaround is to close then reopen the raw filter field if it contains the wrong values.

**Comment by MorrisJobke** [comment]
Fixing PR is #16627

It seems that it only happen on stable8 -> update milestone

**Comment by blizzz** [comment]
https://github.com/owncloud/core/pull/16627 still needs a tester :)

**Comment by cmonteroluque** [comment]
@davitol @jnfrmarks David can you test this?

**Comment by davitol** [comment]
The race condition is solved, but I can't get the field primaryGroupID in my result filter in the Users filter tab . :sob: Maybe there's something wrong with my configuration

**Comment by cmonteroluque** [comment]
@davitol even with @PVince81 's workaround above?

**Comment by MorrisJobke** [comment]
@davitol Retest with #16456 ...It hopefully now should work for you :)

**Comment by davitol** [comment]
Works for me in 8.1 RC1--> "version":"8.1.0.7","versionstring":"8.1 RC1","edition" for example, but not in stable8-backport-13740-and-15606

**Comment by blizzz** [comment]
Hum, works for me with #16456. 

@davitol did to pull again the branch from git?

**Comment by cmonteroluque** [comment]
@davitol

**Comment by rperezb** [comment]
@cmonteroluque commented on: https://github.com/owncloud/core/pull/16456 it is not working, 
stable8-backport-13740-and-15606 did not work.

**Comment by DeepDiver1975** [comment]
> Fixing PR is #16627

#16627 is merged now - can we close this one? THX

**Comment by davitol** [comment]
as I said the race condition was fixed but in 8.0.X versions i can't see the primaryGroupID in the filter configuring a right Active Directory. If there's another person that can see the primaryGroupID as part of the filter as it is supposed to be I would be eternally grateful if he can help me to get it

**Comment by rperezb** [comment]
@blizzz, perhaps we may set up a screen sharing to check what it´s wrong

**Comment by blizzz** [comment]
@rperezb sure, just sent me an invite for when it suits you.

**Comment by rperezb** [comment]
done, thx

**Comment by davitol** [comment]
Works with the core-stable8-backport-13740-and-15606 branch
OC server: "version":"8.0.6.0","versionstring":"8.0.6 beta1"

**Comment by blizzz** [comment]
Fixed with https://github.com/owncloud/core/pull/16456
