### ISSUE TITLE
files_encryption error: public key exists but private key is missing

### ISSUE THREAD

**Issue by ageis** [owncloud/core#16633]
One of our ownCloud users, whose files_encryption migration_status (in oc_preferences) is still 0, is receiving the following error:

```
 Encryption App is enabled but your keys are not initialized, please log-out and log-in again
```

In owncloud.log it says:

```
public key exists but private key is missing for <user>
```

He's tried logging in and out several times and it doesn't work—the error isn't going away. I've tried running encryption:migrate-keys; but the files and directories for keys don't exist. We need to trigger his migration to encryption and key generation, but I don't know how to get it to happen. rm'ing his files_encryption folder doesn't work, I wonder if there's a variable I need to edit in the database?

On another note, a while ago I manually deleted a couple unshared files out of his data folder, which I now realize was a mistake and strongly ill-advised. I've since run files:scan and maintenance:repair, but I suspect that this might be the cause of the fact that he's the only one of our users having issues with file encryption and who hasn't been migrated.

Based on a search of GitHub issues and Google, other people have had this problem, but I don't see any straightforward solution.

**Comment by LukasReschke** [comment]
Would you mind to fill out the issue template? Thx.

**Comment by ageis** [comment]
I'm not positive on the STR, but I'll try to give what I think the context might be:
### Steps to reproduce
1. Enable server-side file encryption
2. Have a user who doesn't log in afterward, and thus doesn't get migrated
3. Manually delete a couple files in their data directory
4. Now try to log in, they won't be migrated and they'll just keep getting the same error.

### Expected behaviour
The user's files should be encrypted, and their keys generated, when they log in the next time.

### Actual behaviour
The user sees "Encryption App is enabled but your keys are not initialized, please log-out and log-in again" and ownCloud's log says "public key exists but private key is missing".

Logging out and back in results in no change, neither does clearing the cookies and cache, or running encryption:migrate-keys, files:scan or maintenance:repair.

### Server configuration
**Operating system**:
Debian 8 "jessie" GNU/Linux

**Web server:**
Apache 2.4

**Database:**
MySQL

**PHP version:**
5.6.7

**ownCloud version:**
8.0.3

**Updated from an older ownCloud or fresh install:**
Updated from 6.x, and 7.x

**List of activated apps:**
Activity, Calendar, Deleted files, Documents, First Run Wizard, Full Text Search, Mail Template Editor, PDF Viewer, Pictures, Server-side encryption, Share Files, Text Editor, Updater, Versions, Video Viewer

**The content of config/config.php:**

```
$CONFIG = array (
  'instanceid' => 'oc77a4306702',
  'passwordsalt' => '',
  'trusted_domains' => 
  array (
    0 => 'cloud.freedom.press',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.0.3.4',
  'dbname' => 'fpf_owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin',
  'dbpassword' => '',
  'installed' => true,
  'mail_from_address' => 'webmaster',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'cloud.freedom.press',
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
  'secret' => '',
  'appstoreenabled' => true,
  'appstoreurl' => 'http://api.apps.owncloud.com/v1',
  'appcodechecker' => false,
  'forceSSLforSubdomains' => true,
);

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** yes/no
Yes, but we've since disabled it because of the bug.

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No.

### Client configuration
**Browser:**
Google Chrome 43.0.2357.81

**Operating system:**
n/a

### Logs
#### Web server error log
```
n/a
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"a60b9ab66eb952056f8512e7e05132ee","remoteAddr":"24.130.34.69","app":"Encryption library","message":"public key exists but private key is missing for \"username\"","level":4,"time":"2015-06-01T03:17:52+00:00"}

```

#### Browser log
```
n/a
```

**Comment by PVince81** [comment]
@schiesbn can you help ?

**Comment by schiesbn** [comment]
> public key exists but private key is missing for <user>

The error message is quite obvious. Please double check that the public key ````<user>.publicKey```` in data/files_encryption/public_keys exists and that the private key doesn't exist at ````<user>/files_encryption/<user>.privateKey````

If that's the case please restore the private key from your backups, I hope you have backups. ownCloud never deletes a private key, so I have now idea how you lost it. Maybe while you "Manually delete a couple files in their data directory"?

If the user never logged in all data should be still unencrypted. In this case you could also try to delete the public key. At next login ownCloud should create a new key pair and migrate his files. But keep in mind that in case some files are already encrypted, they will be lost.

**Comment by PVince81** [comment]
@ageis any update regarding @schiesbn's questions ?

**Comment by ageis** [comment]
@PVince81 regrettably that comment was not helpful. The `/data/user/files_encryption/user.privateKey` file is missing for this one user. Don't have backups. He does have a publicKey.

**Comment by SkullMasher** [comment]
Hello there, I got the same problem as well. I have enable the encryption module. All user can't upload siles because the privatekey does not get generated. I'm also on a Debian server.

Since i'm here. Thank you so very much to all the people involved in the owncloud project.

**Comment by schiesbn** [comment]
@SkullMasher did you also enabled "server side encryption" in the admin settings? Users need to re-login in order to create the private keys after encryption was enabled

**Comment by PVince81** [comment]
Closing due to lack of feedback
