### ISSUE TITLE
Missing translations in External storage back-end: Advanced settings

### ISSUE THREAD

**Issue by vidaren** [owncloud/core#16631]
### Steps to reproduce
1. Run the owncloud web UI as admin, using a non-English UI language
2. Activate the following apps: External storage support
3. Go to the Admin page
4. Under External storage, create a new external storage of any kind
5. Click the cogwheel on the right to bring up the Advanced settings panel
6. Observe that no text on that panel is translated:
![owncloud-externalstorage-advanced](https://cloud.githubusercontent.com/assets/4960432/7890958/a78e7fa0-0649-11e5-8a09-eeadfc48ef41.png)

### Expected behaviour
All strings in the Advanced settings panel should be translated in web UI and translatable on Transifex. E.g. "Enable previews" and "Check for changes".

### Actual behaviour
The strings in the Advanced settings panel are not translated in the web UI and do not appear on Transifex. It seems to me that the strings are coded as translatable in [js/settings.js](https://github.com/owncloud/core/blob/master/apps/files_external/js/settings.js), but somehow they don't find their way to Transifex?

### Server configuration
**Operating system**: FreeBSD 10.1-RELEASE

**Web server:** nginx 1.8.0

**Database:** SQLite

**PHP version:** 5.6.8

**ownCloud version:** 8.1 beta 2 (daily) Build:2015-05-29T03:31:34+00:00 67cef93fddc0d968ec7d3febe7f618450e59bb39 

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:** External storage support.

**The content of config/config.php:** 

```
(Unchanged after install with SQLite selected)
```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox 38.0.1

**Operating system:** OS X Mavericks

#### Web server error log
```
nothing relevant here
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"xzbSiA8L8JYl1c+auEjd","remoteAddr":"10.200.202.214","app":"core","message":"XCache opcode cache will not be cleared because \"xcache.admin.enable_auth\" is enabled.","level":2,"time":"2015-05-29T18:38:45+00:00"}
{"reqId":"xzbSiA8L8JYl1c+auEjd","remoteAddr":"10.200.202.214","app":"PHP","message":"Undefined offset: 0 at \/usr\/local\/www\/owncloud-daily\/lib\/private\/appframework\/http\/request.php#683","level":3,"time":"2015-05-29T18:38:45+00:00"}
{"reqId":"xzbSiA8L8JYl1c+auEjd","remoteAddr":"10.200.202.214","app":"PHP","message":"fopen(\/usr\/local\/www\/owncloud-daily\/config\/config.php): failed to open stream: No such file or directory at \/usr\/local\/www\/owncloud-daily\/lib\/private\/config.php#191","level":3,"time":"2015-05-29T18:38:46+00:00"}
{"reqId":"K6f+5TvBR2az\/3UjfGeI","remoteAddr":"10.200.202.214","app":"PHP","message":"Undefined offset: 0 at \/usr\/local\/www\/owncloud-daily\/lib\/private\/appframework\/http\/request.php#683","level":3,"time":"2015-05-29T18:39:01+00:00"}
{"reqId":"K6f+5TvBR2az\/3UjfGeI","remoteAddr":"10.200.202.214","app":"core","message":"XCache opcode cache will not be cleared because \"xcache.admin.enable_auth\" is enabled.","level":2,"time":"2015-05-29T18:39:01+00:00"}
{"reqId":"K6f+5TvBR2az\/3UjfGeI","remoteAddr":"10.200.202.214","app":"core","message":"XCache opcode cache will not be cleared because \"xcache.admin.enable_auth\" is enabled.","level":2,"time":"2015-05-29T18:39:02+00:00"}
{"reqId":"K6f+5TvBR2az\/3UjfGeI","remoteAddr":"10.200.202.214","app":"core","message":"XCache opcode cache will not be cleared because \"xcache.admin.enable_auth\" is enabled.","level":2,"time":"2015-05-29T18:39:02+00:00"}
{"reqId":"NmeK48rgE\/La0B4cgbdC","remoteAddr":"10.200.202.214","app":"core","message":"XCache opcode cache will not be cleared because \"xcache.admin.enable_auth\" is enabled.","level":2,"time":"2015-05-29T18:45:31+00:00"}
{"reqId":"AhOM8boiAm0Wc4mJZ31t","remoteAddr":"10.200.202.214","app":"PHP","message":"Array to string conversion at \/usr\/local\/www\/owncloud-daily\/lib\/private\/template\/functions.php#36","level":3,"time":"2015-05-29T19:32:16+00:00"}
{"reqId":"yB1c2H65rx0J3UTE4QmV","remoteAddr":"10.200.202.214","app":"PHP","message":"Array to string conversion at \/usr\/local\/www\/owncloud-daily\/lib\/private\/template\/functions.php#36","level":3,"time":"2015-05-29T19:41:13+00:00"}
```

#### Browser log
```
nothing relevant here

**Comment by MorrisJobke** [comment]
fix is in #16638
