### ISSUE TITLE
Missing translation of Official/Approved/Experimental and tool tips on Apps page

### ISSUE THREAD

**Issue by vidaren** [owncloud/core#16632]
### Steps to reproduce
1. Run the owncloud web UI as admin, using a non-English UI language
2. Go to the Apps management page. The active apps are listed.
3. Hover the mouse over the "Official" button on an app, to see the moseover tool tip
4. Observe that the tool tip is in English, even though the string is translated on Transifex

### Expected behaviour
The translated tool tips should be shown.

### Actual behaviour
The English tool tips are shown, even though the strings have been translated on Transifex.

I see in [settings/js/apps.js](https://github.com/owncloud/core/blob/master/settings/js/apps.js#L120) that the translation call is using 'core', whereas most other translations in that file use 'settings' for the first parameter, and the corresponding Transifex translations are indeed done in the 'settings' resource. 
As for the green-outlined Official/Approved/Experimental indicators themselves, it seems they are [not translatable](https://github.com/owncloud/core/blob/master/settings/js/apps.js#L15). 

### Server configuration
**Operating system**: FreeBSD 10.1-RELEASE

**Web server:** nginx 1.8.0

**Database:** SQLite

**PHP version:** 5.6.8

**ownCloud version:** 8.1 beta 2 (daily) Build:2015-05-29T03:31:34+00:00 67cef93fddc0d968ec7d3febe7f618450e59bb39 

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:** No extra apps activated.

**The content of config/config.php:** 

```
(Unchanged after install with SQLite selected)
```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox 38.0.1

**Operating system:** OS X Mavericks

#### Web server error log
```
nothing relevant here
```

#### ownCloud log (data/owncloud.log)
```
nothing relevant here
```

#### Browser log
```
nothing relevant here

**Comment by MorrisJobke** [comment]
Fix is in #16637
