### ISSUE TITLE
Filles missing after rename in sync client

### ISSUE THREAD

**Issue by cor-mt** [owncloud/core#16639]
On my server a folder with a lot of sub files got renamed and afterwards it had only 3 files in it. The files are all still on the server but dont show in owncloud.

From the forum and other bugs with same problem the answer is to run "sudo -u apache php console.php files:scan <user>" to get the files back, that don't work and I assume it is because the files are encrypted. How can I get the files back when they are encrypted?

This is OC 8.0.2, apache with an postgres db on Funtoo.

**Comment by LukasReschke** [comment]
Thanks a lot for reporting issues back to us!

We need some more information to properly support you with your issue!

Can I ask you to follow our guidelines for submitting bugs as described here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by PVince81** [comment]
Can you describe what you mean with "don't work" after rescan ?
Do the files appear again in the UI ?
If yes, can these be downloaded or are you seeing an error that they cannot be decrypted ?

The symptoms are likely to be related to #13391

**Comment by cor-mt** [comment]
Don't work, they don't appear again in oc after the rescan. If I do the scan the name, key, and migration backup key of each file/folder in the folder is printed, but that's it. Or is there a manual way to download and decrypt the files?

### Server configuration
**Operating system** Funtoo

**Web server:** apache-2.2.29

**Database:** postgresql-9.4.4

**PHP version:** php-5.5.26

**ownCloud version:** ownCloud 8.0.2 (stable)

**Updated from an older ownCloud or fresh install:** Updated

**List of activated apps:**
```
Enabled:
 - activity
 - bookmarks
 - calendar
 - contacts
 - files
 - files_encryption
 - files_pdfviewer
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - files_videoviewer
 - firstrunwizard
 - gallery
 - updater
 - user_webdavauth
Disabled:
 - external
 - files_external
 - files_locking
 - provisioning_api
 - templateeditor
 - user_external
 - user_ldap
```

**The content of config/config.php:**
```
<?php
define('DEBUG',true);
$CONFIG = array (
  'instanceid' => 'oc5d707da976',
  'passwordsalt' => '',
  'trusted_domains' => 
  array (
    0 => 'www.cor.za.net',
  ),
  'datadirectory' => '/var/example.com/htdocs/cloud/data',
  'dbtype' => 'pgsql',
  'version' => '8.0.2.0',
  'dbname' => '',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
  'mail_from_address' => 'cloud',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'example.com',
  'secret' => '',
  'overwrite.cli.url' => 'https://example.com/cloud',
);
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** ownCloud client.

**Operating system:** Funtoo

### Logs

#### ownCloud log (data/owncloud.log)
```
cat data/owncloud.log | grep "folderName"
{"reqId":"b80ca84ffe2b1b9c9c8206411e929ab3","remoteAddr":"x.x.x.x","app":"core","message":"unable to rename, file does not exists : files_versions\/folderName.v","level":3,"time":"2015-04-30T06:36:19+00:00"}
```

**Comment by PVince81** [comment]
@cor-mt did you use "./occ files:scan --all" ? I remember that older OC versions didn't output any error in case you missed the "--all" argument.

**Comment by PVince81** [comment]
The scanner should work even when the files are encrypted.

**Comment by PVince81** [comment]
@schiesbn

**Comment by cor-mt** [comment]
Did now again with "sudo -u apache php occ files:scan --all" nothing. The one thing I did when I saw the files are gone was to re create a folder with the same name it was before the rename, could that cause trouble?

**Comment by cor-mt** [comment]
(bump) Is there any thing else I can try? Will I screw my chances to recover those files if I update oc to the latest version?

**Comment by MorrisJobke** [comment]
> (bump) Is there any thing else I can try? Will I screw my chances to recover those files if I update oc to the latest version?

This should be fine. Please update and run the filescan again. We improved on the renaming issue a lot in 8.2 (we introduced file locking to prevent that cause of this).

Also the files:scan works better in newer versions. Feel free to reopen if you still have issues accessing the files.
