### ISSUE TITLE
[OC Sync Client] Files lost because of network problems

### ISSUE THREAD

**Issue by wazari972** [owncloud/core#16645]
Hello,

I suspect that Owncloud lost some of my files synchronized with Linux OC Sync Client, certainly in a period where my OC server network connection was unreliable. Is is possible? 

* server (S) and desktop (D) filesystem where not altered, the synchronized directories in the D FS were used normally
* at some points, files in D disappeared and reappeared
* eventually, some files in D never came back, and where missing in S filesystem as well
* S network is unreliable these days, maybe with some processes killed for resource management.

what I've got in mind is that the file list sent by the server got truncated, and the client deleted the missing files, is it possible ?

thanks,

Kevin

**Comment by LukasReschke** [comment]
Please open an issue in the client repository following the contributing guidelines. (i.e. use the issue template)

https://github.com/owncloud/client/blob/master/CONTRIBUTING.md
