### ISSUE TITLE
Feature Request - Share Link - Can Edit - Add ability to Download or not to the share

### ISSUE THREAD

**Issue by greavette** [owncloud/core#16644]
Hello,

Not sure where exactly to put this feature request...but basically I'd like to suggest a checkbox in the Can Edit section of a Share Link whereby you can decide if the users/groups have the ability to download a file or not.

Thank you.

**Comment by rullzer** [comment]
The whole purpose of a link share is for other people to be able to download it right?

Could you explain what you want with a use case?

**Comment by greavette** [comment]
In our office we share our operating procedure documents online using Owncloud using the built in PDF Viewer.  These documents are not in print and are to be only viewed online.  We have instructed the employees that it is against company policy to download these files.  Since the majority of our employees do not use Owncloud for any other purpose and do not have an Owncloud client account we setup a generic account and use that account as the share for the employees to view these protected documents at their workstations.  Seeing as we don't have user accounts for each person and each workstation is used by multiple people throughout the day it would be difficult to look in the logs and figure out who has downloaded a file.  

We understand that Owncloud is by design a file sharing system and for other folders that do not contain these operating procedures we do allow sharing and download. But in this case we want to keep these operating procedures only on the Owncloud webpage.  This is why I'd like to have the option of sharing folders/files with users/groups for shared documents that can be downloaded and I want to have the option to share folders/files for PDF viewing only that can't be downloaded.  Since the Share option already has checkboxes for delete and edit it makes sense to us to have a download checkbox added as well.

I realize that no system is foolproof from copying information...our employees can still find ways to print these files or even use their cellphones to take pictures.  But Owncloud is the closest system I've found that allows us to easily add pdf documents to an Owncloud sync folder and have this folder displayed in a webpage.  

Owncloud is for hosting data which does not necessarily mean sharing.  In our use case we want to continue to use this great system to host our data for viewing only.

Thank you,

**Comment by LukasReschke** [comment]
Introducing this would be a lot code to maintain and there would be other ways to download a file anyways. Thus it is very unlikely at all that we will ever introduce such a feature.

If you want to have such a feature for PDF files the easiest way to achieve this would be to create an own ownCloud theme and modify the public sharing HTML page to remove the sharing buttons.
