### ISSUE TITLE
PHP 7 Compatibility Issue: Uncaught TypeException: Argument 3 passed to OC\Share\SearchResultSorter::__construct() must implement interface OCP\ILogger

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#16643]
```
PHP Fatal error:  Uncaught TypeException: Argument 3 passed to OC\Share\SearchResultSorter::__construct() must implement interface OCP\ILogger, string given, called in /var/www/html/tests/lib/share/searchresultsorter.php on line 45 and defined in /var/www/html/lib/private/share/searchresultsorter.php:41
```

Ref https://github.com/owncloud/core/blob/a3bc11241230dda8709f98663d8fbc00bdbb2d2e/tests/lib/share/searchresultsorter.php#L41-L46

Either needs to get fixed in PHPUnit or we need to change this :see_no_evil:

**Comment by LukasReschke** [comment]
Should probably pass with https://github.com/sebastianbergmann/phpunit/pull/1766 - let's test that locally.

**Comment by DeepDiver1975** [comment]
What is the deeper meaning of this test anyhow?

**Comment by DeepDiver1975** [comment]
Okay - understood - necessary?
