### ISSUE TITLE
OpenCloud Client does not allow multiple accounts

### ISSUE THREAD

**Issue by elbarbudo** [owncloud/core#16647]
On my Androïd, I set up the blaucloud.de client for Android.
It has a very nice features which is missing on linux client :
You can "add an account" on it. 

It is very usefull : I use a "local" account at home and a "hosted" account on the road.

There is no way to set up more than one account in the linux client

**Comment by LukasReschke** [comment]
> There is no way to set up more than one account in the linux client

Duplicate https://github.com/owncloud/client/issues/43
