### ISSUE TITLE
Unclear quota warning for shared contend

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/core#16651]
### Steps to reproduce

1. User A uses 97% of its quota
2. User A shares directories with user B
3. If B accesses shared contend of user A, B gets a quota warning "Your storage is almost full (97%)"

### Expected behaviour

A correct message could be "Storage of A is almost full (97%)". 

### Actual behaviour

If B accesses shared contend of user A, B gets a quota warning "Your storage is almost full (97%)". 

This unclear warning about storage quota confuses our users.

@MorrisJobke

00003277

**Comment by PVince81** [comment]
Right. `getstoragestats` is called for the currently displayed folder.
In the case of a shared folder, the returned quota / free space is the one from the owner.

We should probably hide the message when in a shared folder.
Maybe that ajax call should return the name of the owner of the folder too to make that detection possible.

**Comment by MorrisJobke** [comment]
Fix is in #16771

**Comment by MorrisJobke** [comment]
@michaelstingl Will be fixed with 8.1
