### ISSUE TITLE
Version 8.0.3 Contacts index not changed when contact name changed

### ISSUE THREAD

**Issue by CaptainOfTheTitanic** [owncloud/core#16661]
I entered a new contact and saved it. I then noticed that I had misspelled the name and changed it. The name changed in the display, but it retained the old name in the index.
I exported the entry to vcf format and found that the FN: field had changed, but the N: field was unchanged.

I can work around this by exporting to vcf and editing the raw text, deleting and reimporting, but it would be nice to have it change automatically.

**Comment by RealRancor** [comment]
Hi,

the issue tracker of the contacts app is located here:

https://github.com/owncloud/contacts/issues

Please re-open there using the issue template as described in

https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version

**Comment by CaptainOfTheTitanic** [comment]
My apologies, I thought I was on the contacts issues page when I raised this.
