### ISSUE TITLE
External Storage on S3 (via Ceph RGW) : Cannot upload files > 1MB

### ISSUE THREAD

**Issue by ksingh7** [owncloud/core#16662]
Hello to owncloud great community

I have a running owncloud environment  on CentOS6.5 and ownCloud 8.0.3 (community version)
My external storage is on S3 backed by Ceph Rados Gateway

**What's Working** :+1: 
- Owncloud frontend
- Ceph storage
- Able to upload files under size 1MB , can create directories as well without problems.

**What's NOT working** :-1: 
- Unable to add any file larger than 1MB

**Troubleshooting:**

- Tried creating local storage for owncloud ( i.e. disabled external storage app ) and added files. i can upload files of any size 1G, 10G , even 15G single file
- Tried uploading files s3cmd ( command line tool ) to Ceph S3 storage and can upload files up to 20G without any problems. This shows that Ceph is working fine.

**Error message on owncloud**
- Not getting too much logs ( just 1 line )

```bash
{"reqId":"ea39b4a8bf7b5c93022fc7c993f3494b","remoteAddr":"193.166.2.205","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'DSC_0198.JPG' is not accessible or present !!!","level":0,"time":"2015-06-01T14:09:06+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files\/ajax\/upload.php"}
```
Trust me this file exists , logs are lying ;-)

- Error screen shots from owncloud 

Image 1 : It shows that its trying to upload file and waits on this screen for at least 10 minutes
![snap 2015-06-01 at 17 06 35](https://cloud.githubusercontent.com/assets/9701902/7915015/75b4fa54-0883-11e5-9bce-02ed47da9540.png)

Image 2 : It throws error message
![snap 2015-06-01 at 17 08 47](https://cloud.githubusercontent.com/assets/9701902/7915019/7ada8ed6-0883-11e5-83c1-31385769ebba.png)

Can anyone suggest what's the real problem.

**Comment by PVince81** [comment]
@Xenopathic didn't you have a ceph docker running lately ?

**Comment by Xenopathic** [comment]
Yes, it's the one used in the S3 tests: #19069. It's called `xenopathic/ceph-keystone` if anyone wants to use it

**Comment by andrewhatfield** [comment]
Is this still a problem?  Does it apply to Enterprise 8.1+ ?

**Comment by PVince81** [comment]
Is this still happening with 8.2.2 ?

We have CI tests running against Ceph using S3 and Swift and they work fine.

**Comment by PVince81** [comment]
Please reopen if the problem still exists with 8.2.6 or 9.0.3.
