### ISSUE TITLE
Renaming Files Corrupts Them

### ISSUE THREAD

**Issue by bkerensa** [owncloud/core#16676]
### Steps to reproduce
1. Rename File
2. Download File
3. Open and Discover File is Corrupted

### Expected behaviour
Tell us what should happen
Files should not get corrupted because of a rename

### Actual behaviour
Tell us what happens instead
Files get corrupted

### Server configuration
**Operating system**:
Ubuntu

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
PHP 5.6

**ownCloud version:** (see ownCloud admin page)
8.1 Beta 2

**Updated from an older ownCloud or fresh install:**
8.0.3

**List of activated apps:**
nan
**The content of config/config.php:**
Cannot provide due to OpSec
```
Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Nope
**Are you using encryption:** yes/no
Nope
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Nope
#### LDAP configuration (delete this part if not used)

```
run: sqlite3 data/owncloud.db
then execute:  select * from oc_appconfig where appid='user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
Firefox 
**Operating system:**
OSX
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by PVince81** [comment]
Is this repeataple or happens randomly ?

In what way is the file corrupt, is it truncated ?

**Comment by MorrisJobke** [comment]
@bkerensa Can you provide a list of enabled apps?

**Comment by MorrisJobke** [comment]
Is there something in the log file?

**Comment by PVince81** [comment]
Please try again with 8.1.1. The beta had some bugs.
