### ISSUE TITLE
User can create federated share when "Restrict users to only share with users in their groups" is enabled

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#16675]
### Steps to reproduce

1. Install 8.1 
2. Navigate to admin page
3. Click on Sharing
4. Check the "Restrict users to only share with users in their groups"
5. Try to share a file with a local user not in their group 
6. Try to share a file with a remote user

### Expected behaviour

In step 5: the user should be prevented from sharing the file.
In step 6: the user should be prevented from sharing the file.

### Actual behaviour

In step 5: the user is not allowed to share the file.
In step 6: the user is allowed to share the file.

### Server 1 Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration:

ownCloud Enterprise Edition 8.1 beta 2 (daily) Build:2015-06-01T03:08:44+00:00 8d23b3440286035c9f7183442f27c325b6263e10

**Comment by jnfrmarks** [comment]
I'm marking this a sev 2 because users are able to share when they shouldn't be able to share.

**Comment by PVince81** [comment]
Probably a misunderstanding in the settings. Federation is separate from regular sharing.

But I agree that the world gives the impressiom that federated sharing should be disabled for these users too.

@MTRichards @jancborchardt @schiesbn what do you think ?

**Comment by rullzer** [comment]
I assume we want to clarify and possibly fix this. Since you can do federated sharing with users on your own owncloud instance.

**Comment by PVince81** [comment]
Hmmm, right... local federated shares... still an open topic: https://github.com/owncloud/core/issues/9090 (to recognize shares to the same instance and convert them to local shares)

**Comment by nickvergessen** [comment]
The language strings in question:
> Restrict users to only share with users in their groups

Seperated by the section header of "Federated Cloud Sharing"
> Allow users on this server to send shares to other servers 

Well I'd say it is quite obvious and I don't think that the first setting should influence the second one.

**Comment by DeepDiver1975** [comment]
@jnfrmarks please have a look at the comments - THX

**Comment by jnfrmarks** [comment]
It sounds like what we're saying is that the settings for sharing and the settings for federated sharing are mutually exclusive.  If that's the case, at a minimum, I'd vote for a message to the effect on the admin page and maybe open up an enhancement  issue to discuss/implement combining the two, if that's what we even want.

@DeepDiver1975

**Comment by nickvergessen** [comment]
Let's document this in the UI. Nothing fix-worthy really:
https://github.com/owncloud/core/issues/9090#issuecomment-107953657

**Comment by DeepDiver1975** [comment]
> It sounds like what we're saying is that the settings for sharing and the settings for federated sharing are mutually exclusive.

No mutually exclusive - more of kind: not related at all. In a federated sharing environment there is no understanding of a group and therefore this setting does not apply.

@MTRichards do we want to add some more information on this in the admin section and/or the docs? Otherwise this is a wont-fix for me. THX

**Comment by nickvergessen** [comment]
Added a PR to the docs repo: https://github.com/owncloud/documentation/pull/1200
