### ISSUE TITLE
Get white screen when configuring 'redis' in config.php

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#16670]
### Steps to reproduce

1. Install 8.1 
2. Update config.php to support redis.  I used this configuration:

```

<?php
$CONFIG = array (
  'supportedDatabases' =>
  array (
    0 => 'mysql',
    1 => 'pgsql',
    2 => 'oci',
    3 => 'mssql',
  ),
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' =>
  array (
    0 => 'localhost',
    1 => 'x.x.x.x',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'overwrite.cli.url' => 'http://localhost',
  0 => 'x.x.x.x',
  'dbtype' => 'mysql',
  'version' => '8.1.0.6',
  'dbname' => 'owncloud',
  'dbhost' => 'x.x.x.x',
  'dbtableprefix' => '',
  'dbuser' => '',
  'dbpassword' => '',
  'logtimezone' => 'UTC',
  'installed' => true,
  'instanceid' => '',
  'license-key' => '',
  'memcache.local' => '\OC\Memcache\Redis'
  'redis' => array(
        'host' => '127.0.0.1',
        'port' => 6379,
        'timeout' => 0.0,
        'dbindex' => 0,
  ),

);

```

3. Access ownCloud via the browser

### Expected behaviour

Successful access

### Actual behaviour

Get a white screen.  

If I remove the 'redis' configuration, I am able to access ownCloud.

redis is running at 127.0.0.1/6379

There is nothing in the server log file.

I'm thinking that this is user error somehow but I don't see it. I copied the redis configuration from config.sample.php

### Server 1 Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration:

ownCloud Enterprise Edition 8.1 beta 2 (daily) Build:2015-06-01T03:08:44+00:00 8d23b3440286035c9f7183442f27c325b6263e10

**Comment by RealRancor** [comment]
Hi,

a white page mostly means an "internal server error" which should be logged somewhere in your logfiles. From a first view at the config.php it seems you're missing a ",". So try:

    'memcache.local' => '\OC\Memcache\Redis',

instead of:

    'memcache.local' => '\OC\Memcache\Redis'

**Comment by oparoz** [comment]
I have this in mine and it works:
`'memcache.local' => '\\OC\\Memcache\\Redis',`

*Note the double slashes*

**Comment by jnfrmarks** [comment]
I think it was both:
the missing comma and the double slashes.

Thanks!

**Comment by RealRancor** [comment]
@jnfrmarks 
I think it could be useful to know what of those have caused this or if it was really both. If the double slashes are also causing such issues it should be fixed in the config.sample.php

**Comment by edgetek** [comment]
having the same issue with 8.1.5 everything works fine without redis, but if I turn on redis it goes white album. redis works, i ping, I get PONG, I believe it is an issue with phpredis but if anyone can think of anything would be appreciated.
Thank you,

config.php cleaned here
<?php
$CONFIG = array (
  'datadirectory' => '/home/owncloud/html/data',
  'dbtype' => 'mysql',
  'version' => '8.1.5.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'password',
  'installed' => true,
  'maintenance' => false,
  'forcessl' => true,
  'theme' => '',
  'loglevel' => 4,
  'maxZipInputSize' => 0,
  'allowZipDownload' => true,
  'logtimezone' => 'America/Kentucky/Louisville',
  'trusted_domains' => 
  array (
    0 => 'oc.email.com',
  ),
  'secret' => 'e8f4b0ceee66f5b83146c4cfdcdc03e1c45aaa180f69989462b3756347c9aa1780a77526a249f8863261d9988176a0ba',
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'owncloud',
  'mail_domain' => 'email.com',
  'mail_smtphost' => 'mx.email.com',
  'mail_smtpport' => '465',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'ausername',
  'mail_smtppassword' => 'apassword',
);

**Comment by RealRancor** [comment]
@edgetek Please see https://owncloud.org/support/ for support options
