### ISSUE TITLE
"Strict-Transport-Security" HTTP header "2,678,400" seconds

### ISSUE THREAD

**Issue by carlaschroder** [owncloud/core#16671]
This message is displayed on the Admin page of 8.1 beta 2 enterprise, on https://daily.owncloud.com/enterprise-complete-master/owncloud/index.php/settings/admin:

'The "Strict-Transport-Security" HTTP header is not configured to least "2,678,400" seconds. This is a potential security risk and we recommend adjusting this setting.'

Maybe it's me, but it doesn't make sense.

![strict-transport](https://cloud.githubusercontent.com/assets/8388387/7920239/860f6db6-0852-11e5-8530-dc4cf5d70859.png)

**Comment by RealRancor** [comment]
Two refs about the changes and some documentation:

https://github.com/owncloud/documentation/issues/914 , https://github.com/owncloud/documentation/pull/989

**Comment by carlaschroder** [comment]
Oh, it's already documented. Excellent.

**Comment by carlaschroder** [comment]
I'll open a separate issue for the inconsistency in the value.

**Comment by RealRancor** [comment]
@carlaschroder 
Mhhh, but maybe left this open as a link to the documentation is missing?
