### ISSUE TITLE
Two different Strict-Transport-Security recommendations

### ISSUE THREAD

**Issue by carlaschroder** [owncloud/core#16673]
oC 8.1 displays this message on the Admin page "The "Strict-Transport-Security" HTTP header is not configured to least "2,678,400" seconds"

But the admin manual recommends "max-age=15768000".

They should be the same. Which one needs to change?

**Comment by karlitschek** [comment]
@LukasReschke

**Comment by carlaschroder** [comment]
yoohoo @LukasReschke :bowtie:

**Comment by LukasReschke** [comment]
Yihooo :skull: 

Yes… Yes… Yes, no worries. Will change before we release :see_no_evil:
