### ISSUE TITLE
Feature Request: Ability to upload files automatically to server

### ISSUE THREAD

**Issue by gigapouch** [owncloud/core#16677]
I think it would be nice if we could have it so that every week or so our computer would upload our important files to our OwnCloud server. This could be a setting in the Desktop client.

**Comment by RealRancor** [comment]
Hi,

@gigapouch 
this is the issue tracker of the ownCloud server. If you think your use-case is something which should be included in the sync client you could post this in:

https://github.com/owncloud/client/issues
