### ISSUE TITLE
Error logs from the files_external app (dropbox) even though the mount can be accessed normally

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#16679]
### Steps to reproduce
1. Setup a dropbox account as external storage (check you have access to the dropbox account, and you can read the files in the account from ownCloud)
2. Upload a file in the dropbbox mount from ownCloud

### Expected behaviour
The file is uploaded without any issue

### Actual behaviour
File is uploaded, but there are some errors in the logs

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 7.0.6RC2

**Updated from an older ownCloud or fresh install:** updated from 7.0.5

#### ownCloud log (data/owncloud.log)
```
{"app":"files_external","message":"Error: (401) Unauthorized\n","level":3,"time":"2015-06-02T08:52:29+00:00"}
{"app":"PHP","message":"Invalid argument supplied for foreach() at \/opt\/owncloud\/apps\/files_external\/3rdparty\/Dropbox\/OAuth\/Curl.php#78","level":3,"time":"2015-06-02T08:52:29+00:00"}
{"app":"files_external","message":"Error: (401) Unauthorized\n","level":3,"time":"2015-06-02T08:52:33+00:00"}
```

### Notes
The dropbox OAuth 2 redirect urls of the dropbox app are set to http://localhost:8120/index.php/settings/admin and http://localhost:8120/index.php/settings/personal . The ownCloud server we're connecting from is in another url. I'm not sure if that could be the cause. Nevertheless it's possible to access to the account and interact with it without any apparent issue.

**Comment by DeepDiver1975** [comment]
the whole dropbox integration needs an overhault - out of scope for me for oc7 - this is a major topic for oc8.2

**Comment by MorrisJobke** [comment]
@LukasReschke I only see fixes for stable branches is there one for master?

**Comment by LukasReschke** [comment]
Master uses the upstream library without custom patches. Should not be affected.
(that said even if it has other bugs we shall fix these upstream and not do what we used to do in the past :see_no_evil: )

**Comment by LukasReschke** [comment]
That said wrt. to the other errors: No idea - that library is strange from time to time :see_no_evil:

**Comment by MorrisJobke** [comment]
@jvillafanez I will close this as per the comments of @LukasReschke. Feel free to reopen if this is still valid for master

**Comment by MorrisJobke** [comment]
... or 8.1.0
