### ISSUE TITLE
Webdav ext storage lighttpd issue

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#16681]
### Steps to reproduce
1. Setup a Webdav server on lighttpd, use a subdir "ex: http://example.com/dav" (dav being the subdir)
2. Configure external storage of type "WebDAV" to connect to it, and specify "dav" in the root field
3. Try navigating into the mount point

### Expected result
Mount point can be navigated

### Actual result
Error, jumps back to root.

### Versions
ownCloud git master (d2f3710ede1fa72658a4c12264a90a1936faf9ca) 

The problem is that lighttpd/webdav's PROPFIND doesn't return the PROPFIND results in the expected order. This core here https://github.com/owncloud/core/blob/master/lib/private/files/storage/dav.php#L201 assumes that the first entry is the root, which is **not** the case for lighttpd/webdav...

Possibly broken since OC 7.

**Comment by PVince81** [comment]
I discovered this because I wanted to test something with a non-OC Webdav server.

**Comment by DeepDiver1975** [comment]
> lighttpd

isn't is dead?

**Comment by PVince81** [comment]
Dead as in ?

**Comment by PVince81** [comment]
I'm not talking about running OC on lighttpd.
Lighttpd is an external server which I use as a Webdav server to test Webdav external storage.

**Comment by DeepDiver1975** [comment]
> Dead as in ?

http://sabre.io/dav/webservers/ - looks like it has many known issues

**Comment by DeepDiver1975** [comment]
> I discovered this because I wanted to test something with a non-OC Webdav server.

@MorrisJobke once had a docker with some dav server inside ...

**Comment by PVince81** [comment]
Hmmm ok... then I'll test with Apache + mod_webdav then.

I started working on a fix but stripping the full path from the entries in opendir() is a bit tricky...

**Comment by MorrisJobke** [comment]
> @MorrisJobke once had a docker with some dav server inside ...

I had a docker container with Apache and mod_dav. Didn't worked either.

**Comment by MorrisJobke** [comment]
As this WebDAV implementation is dead: close this ticket
