### ISSUE TITLE
Cannot add a federated share from a non-LDAP user if the LDAP server is down

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#16699]
### Steps to reproduce
Some of the steps might not be required, but they're here to reproduce the situation

1. Setup an LDAP server in server B
2. In a LDAP user account (server B) upload a file and share it by link
3. Add that share to another ownCloud - server A (federated share)
4. Disconnect the LDAP server from server B (in my case, the LDAP server changed its ip address). LDAP configuration is still active.
5. In a local account in server B upload another file and share it by link
6. Add that share to server A (I used the same account that the previous file).

### Expected behaviour
The share is correctly added and can be accessed from server A

### Actual behaviour
Cannot add the share. Although the user in server B exists and can login, the share isn't added in server A. You must connect to the LDAP server in server B to be able to so even though the file belongs to a local user

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 7.0.6RC1 in server A and 7.0.6RC2 in server B

**Updated from an older ownCloud or fresh install:** fresh install

#### ownCloud log (data/owncloud.log) server B
```
{"app":"PHP","message":"ldap_start_tls(): Unable to start TLS: Can't contact LDAP server at \/opt\/owncloud\/apps\/user_ldap\/lib\/ldap.php#254","level":3,"time":"2015-06-03T07:35:14+00:00"}
{"app":"remote","message":"Lost connection to LDAP server.","level":4,"time":"2015-06-03T07:35:14+00:00"}
{"app":"PHP","message":"ldap_start_tls(): Unable to start TLS: Can't contact LDAP server at \/opt\/owncloud\/apps\/user_ldap\/lib\/ldap.php#254","level":3,"time":"2015-06-03T07:35:14+00:00"}
{"app":"remote","message":"Lost connection to LDAP server.","level":4,"time":"2015-06-03T07:35:14+00:00"}
```

**Comment by DeepDiver1975** [comment]
Yes - expected behavior

No LDAP as in No database as in No cloud
