### ISSUE TITLE
Using occ:  'Exception' with message 'Not installed'

### ISSUE THREAD

**Issue by eon01** [owncloud/core#16693]
Hi, I followed the official guide to use occ:

I am using a vagrant machine ( https://github.com/eon01/OwnCloud_Vagrant_SaltStack )
```
vagrant@vagrant-ubuntu-trusty-64:/var/www/owncloud$ sudo -u www-data php occ -h
```

I've got this error:

```
An unhandled exception has been thrown:
exception 'Exception' with message 'Not installed' in /var/www/owncloud/lib/base.php:223
Stack trace:
#0 /var/www/owncloud/lib/base.php(549): OC::checkInstalled()
#1 /var/www/owncloud/lib/base.php(1026): OC::init()
#2 /var/www/owncloud/console.php(12): require_once('/var/www/ownclo...')
#3 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')
#4 {main}
```

Is this an issue ?

**Comment by RealRancor** [comment]
Hi,

this is mostly caused if the user you're using has no permissions to either access the /config/ folder or the /config/config.php file.

**Comment by DeepDiver1975** [comment]
Given the version you are using: occ can only be used after owncloud is installed.

**Comment by thadboyd** [comment]
I've just installed Owncloud fresh from the repos; I'm running Ubuntu Studio 15.04.  I've configured the permissions as requested.

The very first time I run occ (sudo -u www-data php occ maintenance:install ...) it exits with this same error:

---
exception 'Exception' with message 'Not installed' in /var/www/owncloud/lib/base.php:223
Stack trace:
#0 /var/www/owncloud/lib/base.php(558): OC::checkInstalled()
#1 /var/www/owncloud/lib/base.php(1039): OC::init()
#2 /var/www/owncloud/console.php(12): require_once('/var/www/ownclo...')
#3 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')
#4 {main}
---

If there is no config.php prior to running occ, then it creates an empty file with that name; if there is a config.php (eg copied from config.php.sample) it is not altered when the script is run.

I get the same error no matter what parameters I use with occ.  Any ideas?

**Comment by DeepDiver1975** [comment]
occ install is new with oc8.1 - which version did you install?  Looks like oc8

**Comment by thadboyd** [comment]
8.1, latest from the repos.  But as I added in my edit, I just misunderstood the instructions; I thought I was supposed to run occ from the command line *before* running the setup wizard in my browser.  Once I ran the wizard everything got set up just fine.

Thanks for your time.
