### ISSUE TITLE
Show indicator when experimental locking is enabled

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#16702]
Maybe show this in the admin page ?

This should appear only if "filelocking.enabled" it true and also the redis server is properly configured for locking.

This is to make it easier to find out whether the locking setup is correct.

Another alternative would be to throw an exception directly if the setup is wrong, for example if redis is not reachable or no memcache provider was selected for locking ? @icewind1991 @jnfrmarks

**Comment by RealRancor** [comment]
Hi,

maybe i misunderstand this completely but isn't there already an indicator on the admin page if the experimental file lock is enabled/disabled on the admin page: https://github.com/owncloud/core/issues/16696

**Comment by PVince81** [comment]
Ah yes, I didn't see it. Thanks @RealRancor
