### ISSUE TITLE
Properly show locked file error message in web UI

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#16701]
Whenever a file is locked, instead of hanging, the web UI needs to show a proper error message.

Currently the network console will return "500 Internal server error" and the log will show that there was a LockingException.

The LockingException needs to be caught properly in the ajax endpoints to be translated into a proper error message.

Needed to be able to show the locking exceptions:

- [x] rename
- [x] move
- [x] new file
- [x] new folder
- [x] delete
- [x] upload
- [x] download
- [ ] getstoragestats

**Comment by PVince81** [comment]
This will require fixing all the ajax calls of the files web UI to properly catch exceptions and actually return them: (something which seems to have been missing for a long while)
- [ ] rename
- [ ] move
- [ ] new file
- [ ] new folder
- [ ] delete
- [ ] download
- [ ] upload
- [ ] getstoragestats ?

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/16718

**Comment by PVince81** [comment]
The PR above fixed many operations but not "Download".
Keeping open to address the "download" case which is more tricky.

**Comment by PVince81** [comment]
Download case here https://github.com/owncloud/core/pull/17009

**Comment by DeepDiver1975** [comment]
> getstoragestats

do we really need this? what's the impact? THX

**Comment by PVince81** [comment]
Probably not needed.
If that call fails because scanning failed, then the "max upload size" or "free space" will not be updated on the upload button, which isn't that bad.
