### ISSUE TITLE
Can't set "delete" permissions on "Shared with others" view

### ISSUE THREAD

**Issue by lawl** [owncloud/core#16709]
Steps to reproduce:
1. Create a folder.
2. Share it with a user on the same instance
3. Go to the "Shared with others" view
4. Edit the permissions for the user (expand "can edit")
5. "delete" flag is missing

Expected behavior:
Delete flag should be available the same way it is on the "All Files" view.

Version: 8.0.3

Additional Information:

PVince81 helped me debug this in IRC as I thought I couldn't set delete permissions at all.
He asked me to open this ticket, I'll just copy paste what he said here:

    <PVince81> it's because we disallow deleting the folder directly in this view, using permissions trickery
    <PVince81> but that seems to affect the dialog too
    <PVince81> just provide the steps to reproduce, and specify the version. then mention me
    <PVince81> that should be enough
    <PVince81> thanks

**Comment by PVince81** [comment]
Confirmed. Also happens 8.1 / master.

Need to find a another way to remove the delete icon in this view without touching the permissions.

**Comment by PVince81** [comment]
Setting to medium as there is a workaround: going to the "All files" view and share from there.

**Comment by PVince81** [comment]
also related: permissions mess https://github.com/owncloud/core/issues/13202

**Comment by cmonteroluque** [comment]
move forward to 9.0 because of #13202

**Comment by cdamken** [comment]
I have it on 8.1.3 too

**Comment by rullzer** [comment]
This seems to be fixed on master. @PVince81 can you verify?

**Comment by PVince81** [comment]
It's fixed with https://github.com/owncloud/core/pull/20160 on master and will be backported to 8.2.2.
