### ISSUE TITLE
Uploading a file with the forbidden character '\' using webdav interface returns 500

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16706]
### Steps to reproduce
1. Create a file called 'hola\hola.txt'
2. Using curl do:
     curl -v -X PUT "http://USER:PASSWORD@HOST/remote.php/webdav/hola\hola.txt" 

### Expected behaviour
It returns 400

### Actual behaviour
HTTP/1.1 500 Internal Server Error

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
```

```

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```

```

### Client configuration

**browser**
Chrome 43

**Comment by PVince81** [comment]
Right. It does return the expected "InvalidPathException" but the status code is 500 instead of 400.

I'll have a look.

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/16711
