### ISSUE TITLE
Mail notification does not work correctly ownCloud 8.0.3 (stable)

### ISSUE THREAD

**Issue by Boellerjoe** [owncloud/core#16717]
Hi,
mail-notification feature seems to be restricted since upgrade to OC 8.0.3
OC users receive activity mail with reference to their own activities although feature is disabled in OC user-preferences. But on the other hand they don´t receive any info if admin or different user changes/deletes/uploads new/shared content.
I have already tried several settings without success.

Please help me to fix this bug.

Server configuration
Operating system: Linux
Web server: Apache
Database:MySQL 5.6.19
PHP version:5-56 STABLE
ownCloud version: 8.0.3
**Updated from an older ownCloud or fresh install: upgraded
**List of activated apps: standard
The content of config/config.php:
<?php
$CONFIG = array (
'instanceid' => 'oc6373b8674c',
'passwordsalt' => '6926bf8655a7c0443151f1b60bf161',
'datadirectory' =>
'dbtype' => 'mysql',
'version' => '8.0.3.4',
'dbname' => 'db417304',
'dbhost' => ,
'dbtableprefix' => 'oc_',
'dbuser' => '',
'dbpassword' => '',
'installed' => true,
'forcessl' => true,
'loglevel' => '0',
'mail_smtpmode' => '',
'mail_smtphost' => '',
'mail_smtpsecure' => 'ssl',
'mail_smtpauth' => true,
'mail_smtpauthtype' => 'LOGIN',
'mail_smtpname' => '',
'mail_smtppassword' =>,
'theme' => '',
'maintenance' => false,
'trusted_domains' => 
array (
0 => '',
),
'share_folder' => '/Shared',
'mail_from_address' => '',
'mail_domain' => '',
'secret' => '',
);
Are you using encryption: yes

**Comment by RealRancor** [comment]
> @Boellerjoe your issue will be fixed in 8.0.4:
> https://github.com/owncloud/activity/pull/297/files

by @nickvergessen in https://github.com/owncloud/core/issues/16715#issuecomment-108367754
