### ISSUE TITLE
Mail notification does not work correctly ownCloud 8.0.3 (stable)

### ISSUE THREAD

**Issue by Boellerjoe** [owncloud/core#16715]
Hi,
mail-notification feature seems to be restricted since upgrade to OC 8.0.3
OC users receive activity mail with reference to their own activities although feature is disabled in OC user-preferences. But on the other hand they don´t receive any info if admin or different user changes/deletes/uploads new/shared content.

I have already tried several settings without success.

Please help me to fix this bug.

**Comment by DeepDiver1975** [comment]
@Boellerjoe Thanks a lot for reporting issues back to us!

We need some more information to properly support you with your issue!

Can I ask you to follow our guidelines for submitting bugs as described here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

Thanks a lot!

**Comment by kkretsch** [comment]
Same problem here:

preg_match(): Compilation failed: internal error: previously-checked referenced subpattern not found at offset 728 at /var/www/cloud803/3rdparty/phpmailer/phpmailer/class.phpmailer.php#893 

Even the email test in the admin menu doesn't work. Neither via mail nor via smtp I can send any email with version 803.

**Comment by DeepDiver1975** [comment]
@kkretsch according to phpmailer's implementation the email address is not valid

**Comment by kkretsch** [comment]
But it is my working address. I insert that in the two "@" separated fields (local part and domain part), clicking test email I get the error response (Ein Problem ist beim Senden der E-Mail aufgetreten. Bitte überprüfe deine Einstellungen) and that logfile lines. How does it validate the syntax?

**Comment by Boellerjoe** [comment]
@DeepDriver1975 Please find detailed information enclosed.

Fyi...deleted personal data....

Server configuration

Operating system: Linux

Web server: Apache

Database:MySQL 5.6.19

PHP version:5-56 STABLE

ownCloud version: 8.0.3

**Updated from an older ownCloud or fresh install: upgraded

**List of activated apps: standard

The content of config/config.php:

<?php
$CONFIG = array (
  'instanceid' => 'oc6373b8674c',
  'passwordsalt' => '6926bf8655a7c0443151f1b60bf161',
  'datadirectory' =>
  'dbtype' => 'mysql',
  'version' => '8.0.3.4',
  'dbname' => 'db417304',
  'dbhost' => ,
  'dbtableprefix' => 'oc_',
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'forcessl' => true,
  'loglevel' => '0',
  'mail_smtpmode' => '',
  'mail_smtphost' => '',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpauth' => true,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpname' => '',
  'mail_smtppassword' =>,
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' => 
  array (
    0 => '',
  ),
  'share_folder' => '/Shared',
  'mail_from_address' => '',
  'mail_domain' => '',
  'secret' => '',
);
Are you using encryption: yes

**Comment by DeepDiver1975** [comment]
@Boellerjoe @kkretsch please open separate issues - otherwise we are mixing up things - THX

**Comment by nickvergessen** [comment]
@Boellerjoe your issue will be fixed in 8.0.4:
https://github.com/owncloud/activity/pull/297/files
