### ISSUE TITLE
"Couldn't send mail to following users" from share.php with LDAP Backend if the user isn't in the mysql table oc_preferences

### ISSUE THREAD

**Issue by rolandbu** [owncloud/core#16716]
Hi

I'm using OwnCloud 8.0.2-8 with LDAP Backend. Everything works fin. If you share a file or directory with a user who never logged in at owncloud or nobody shared something with him then you get the error message "Couldn't send mail to following users" if you use the checkbox for the mail notification. It's only the fist contact with this user no problems after this point. 

More details:
<pre>
mysql> select * from oc_preferences where userid like "james.bond";
Empty set (0.00 sec)
</pre>

Share a file with the user "james.bond" and you get the error message. After that you can find an entry in the oc_preferences table:
<pre>
mysql> select * from oc_preferences where userid like "james.bond";
+-------------------+-----------+-----------+------------------------------------------+
| userid            | appid     | configkey | configvalue                              |
+-------------------+-----------+-----------+------------------------------------------+
| james.bond | user_ldap | homePath  | /var/lib/owncloud/data/james.bond |
+-------------------+-----------+-----------+------------------------------------------+
</pre>

My workaround for the problem is:
sudo -u www-data php /var/www/owncloud/occ user:lastseen "robin.hood"

<pre>
+------------------+----------+-----------+---------------------------+
| userid           | appid    | configkey | configvalue               |
+------------------+----------+-----------+---------------------------+
| robin.hood | files    | quota     | 1000MB                    |
| robin.hood | settings | email     | robin.hood@gmail.com |
+------------------+----------+-----------+---------------------------+
</pre>

**Comment by karlitschek** [comment]
@blizzz @nickvergessen What do you think?

**Comment by nickvergessen** [comment]
No email in the db => no email we can send to.
I think the ldap backend should take care of adding the email addresses to oc_preferences?

**Comment by blizzz** [comment]
LDAP backend does it, if it is configured. Also it is updated not earlier then every 24hrs, when the user is involved.

@rolandbu what's you ldap configuration? ```./occ ldap:show-config```

**Comment by rolandbu** [comment]
We have a correct entry for every LDAP-OwnCloud user in the MySQL table oc_ldap_user_mapping. After the first contact(user login, share a file with the user, ...) it will be another entry in the MySQL  table oc_preferences.
@nickvergessen correct without entry like this "no email we can send to"
<pre>
+------------------+----------+-----------+---------------------------+
| userid           | appid    | configkey | configvalue               |
+------------------+----------+-----------+---------------------------+
| robin.hood | files    | quota     | 1000MB                    |
| robin.hood | settings | email     | robin.hood@gmail.com |
+------------------+----------+-----------+---------------------------+
</pre>

This is our configuration, it works good with more then 3000 user accounts.
<pre>
+------------------------------+-----------------------------------------------------------------------+
| Configuration                |                                                                       |
+------------------------------+-----------------------------------------------------------------------+
| hasMemberOfFilterSupport     | 0                                                                     |
| hasPagedResultSupport        |                                                                       |
| homeFolderNamingRule         | attr:uid                                                              |
| lastJpegPhotoLookup          | 0                                                                     |
| ldapAgentName                | uid=owncloud.ldap,cn=users,dc=bla                             |
| ldapAgentPassword            | ***                                                                   |
| ldapAttributesForGroupSearch |                                                                       |
| ldapAttributesForUserSearch  | displayname;sn;uid                                                    |
| ldapBackupHost               | ldaps://server2                                     |
| ldapBackupPort               | 636                                                                  |
| ldapBase                     | dc=bla                                                        |
| ldapBaseGroups               | dc=bla                                                        |
| ldapBaseUsers                | dc=bla                                                        |
| ldapCacheTTL                 | 15                                                                    |
| ldapConfigurationActive      | 1                                                                     |
| ldapEmailAttribute           | mailprimaryaddress                                                    |
| ldapExperiencedAdmin         | 1                                                                     |
| ldapExpertUUIDGroupAttr      | gidNumber                                                             |
| ldapExpertUUIDUserAttr       | uidNumber                                                             |
| ldapExpertUsernameAttr       | uid                                                                   |
| ldapGroupDisplayName         | cn                                                                    |
| ldapGroupFilter              | (& (OwnCloudGroup=1)(objectClass=univentionGroup) ) |
| ldapGroupFilterGroups        |                                                                       |
| ldapGroupFilterMode          | 1                                                                     |
| ldapGroupFilterObjectclass   |                                                                       |
| ldapGroupMemberAssocAttr     | uniqueMember                                                          |
| ldapHost                     | ldaps://server1                                     |
| ldapIgnoreNamingRules        |                                                                       |
| ldapLoginFilter              | (& (!(shadowExpire=1)) (OwnCloud=1) (uid=%uid) )    |
| ldapLoginFilterAttributes    |                                                                       |
| ldapLoginFilterEmail         | 0                                                                     |
| ldapLoginFilterMode          | 1                                                                     |
| ldapLoginFilterUsername      | 1                                                                     |
| ldapNestedGroups             | 0                                                                     |
| ldapNoCase                   | 0                                                                     |
| ldapOverrideMainServer       | 0                                                                     |
| ldapPagingSize               | 0                                                                     |
| ldapPort                     | 636                                                                  |
| ldapQuotaAttribute           | OwnCloudQuota                                       |
| ldapQuotaDefault             | 1000MB                                                                |
| ldapTLS                      | 0                                                                     |
| ldapUserDisplayName          | displayname                                                           |
| ldapUserFilter               | (& (!(shadowExpire=1)) (OwnCloud=1) )               |
| ldapUserFilterGroups         |                                                                       |
| ldapUserFilterMode           | 1                                                                     |
| ldapUserFilterObjectclass    |                                                                       |
| ldapUuidGroupAttribute       | auto                                                                  |
| ldapUuidUserAttribute        | auto                                                                  |
| turnOffCertCheck             | 0                                                                     |
+------------------------------+-----------------------------------------------------------------------+
</pre>

**Comment by rolandbu** [comment]
Here the same problem: https://mailman.owncloud.org/pipermail/user/2015-June/001634.html

**Comment by rolandbu** [comment]
The same problem again: https://mailman.owncloud.org/pipermail/user/2015-June/001637.html

**Comment by blizzz** [comment]
Fixed with https://github.com/owncloud/core/pull/18469
