### ISSUE TITLE
Top of scroll bar cut off in ownCloud-7-based custome oC 

### ISSUE THREAD

**Issue by iliyasbasir** [owncloud/core#16725]
### Steps to reproduce
1. Open a Firefox browser and log into an ownCloud 7-based instance of 
2. EXPECTED: The scroll bar has an upward-pointing arrow at the top and a downward-pointing arrow at the bottom, for scrolling by clicking; see the attached screen shot Image 1

3. OBSERVED: The top of the scroll bar, including the upward-pointing arrow, is obscured by the banner at the top of the page; see the attached screen shot Image 2. 

4. This behavior can also be seen using an unmodified instance of ownCloud: https://demo.owncloud.org/ 

### Expected behavior
Scroll bar should not cut-off

### Actual behavior
Top of scroll bar cut off in ownCloud-7

### Server configuration
Operating system: Ubuntu 13.10
Web server: Apache/2.4.6 (Ubuntu) Server
Database: MySQL server version 5.6.19
PHP version: PHP 5.5.3-1ubuntu2.6 (cli) (built: Jul 7 2014 16:54:32)
ownCloud version: 7.0.5
Storage backend: local
Client configuration - Can you clarify/elaborate what you mean here? 
Client version: windshare version 1.8.0
Operating system: Any Linux system (in this case, we'll use Ubuntu 14.04)
OS language: English (US)
Installation path of client: /usr/bin/XXXhare

### Screen shot ###
![1](https://cloud.githubusercontent.com/assets/10195796/7962563/04be13ee-09dc-11e5-803c-cd186c576c9d.png)

![2](https://cloud.githubusercontent.com/assets/10195796/7962565/06aad7e6-09dc-11e5-91dc-9db47354ae7e.png)

**Comment by MorrisJobke** [comment]
This is fixed in 8.1.0 with #15260

I propose a backport of this to stable8.

**Comment by MorrisJobke** [comment]
stable8 backport: #16744

**Comment by MorrisJobke** [comment]
#16744  will be shipped with 8.0.5 -> close this
