### ISSUE TITLE
Changed maintenance mode behaviour during ./occ upgrade

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#16723]
Check if the maintenance mode behaviour chang during `./occ upgrade` breaks the packages, because the instance is left in maintanence mode (current implementation for 8.1 reminds the state of maintenance mode).

@cmonteroluque I talked with @jnweiger and he needs to check if the packages still work. Therefore this issue is a sev1, because it could be a breaking change for the packages (especially if they are used for the upgrade from 8.0 to 8.1). And this ticket should simply remind @jnweiger to do that ;)

See https://github.com/owncloud/core/pull/16434#issuecomment-107633735

**Comment by jnfrmarks** [comment]
@SergioBertolinSG @davitol 

We will need to test this.

**Comment by jnweiger** [comment]
RPM:
https://build.opensuse.org/package/view_file/isv:ownCloud:community:8.1:testing/owncloud/owncloud.spec?expand=1

Lines 691-696 switch on maintenance mode.
Lines 758-768 switch it off again.

DEB:
https://build.opensuse.org/package/view_file/isv:ownCloud:community:8.1:testing/owncloud/debian.owncloud-server.preinst?expand=1
and https://build.opensuse.org/package/view_file/isv:ownCloud:community:8.1:testing/owncloud/debian.owncloud-server.postinst?expand=1
should do the same logic. I cannot see the switch off part anywhere....

@MorrisJobke Maybe https://github.com/owncloud/core/issues/14351 also applies to DEB?

**Comment by MorrisJobke** [comment]
> @MorrisJobke Maybe #14351 also applies to DEB?

@jnweiger I would say you need to add it to DEB too. Are there any more packages beside rpm and deb?

**Comment by DeepDiver1975** [comment]
> Are there any more packages beside rpm and deb?

no

**Comment by DeepDiver1975** [comment]
@MorrisJobke @jnweiger case closed??? THX

**Comment by MorrisJobke** [comment]
> @MorrisJobke @jnweiger case closed??? THX

No. The .deb need the maintenance:mode --off too.

**Comment by DeepDiver1975** [comment]
@jnweiger any ETA? THX

**Comment by jnweiger** [comment]
DEB now also has maintenance:mode --off modelled after the codepath from RPM' spec file.
Smoke tests pending.
@Kawohl Please test upgrade from 8.0 to 8.1 beta2

**Comment by jnweiger** [comment]
@MorrisJobke is pull 16434 part of the Beta2 package?

**Comment by MorrisJobke** [comment]
> @MorrisJobke is pull 16434 part of the Beta2 package?

No. beta2 is 29 days old. This was merged 13 days ago.

**Comment by jnweiger** [comment]
Ouch. That leaves only isv:ownCloud:community:nightly/owncloud as a test target.

**Comment by Kawohl** [comment]
I tried to update from 8.04 to 8.1 on Ubuntu 14.04
This error  ocurred

Entpacken von owncloud (8.1-20150617) über (8.0.4-0) ...
dpkg: Fehler beim Bearbeiten des Archivs /var/cache/apt/archives/owncloud_8.1-20150617_all.deb (--unpack):
 Versuch, »/var/www/owncloud/l10n/l10n.pl« zu überschreiben, welches auch in Paket owncloud-server 8.0.4-0 ist
dpkg-deb: Fehler: Unterprozess einfügen wurde durch Signal (Datenübergabe unterbrochen (broken pipe)) getötet
Fehler traten auf beim Bearbeiten von:
 /var/cache/apt/archives/owncloud_8.1-20150617_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by jnweiger** [comment]
Package structure of nightly/owncloud is outdated. Fixed. 
@Kawohl do not retry before you see 8.1-20150617.1 or later.

**Comment by jnweiger** [comment]
Still waiting for the clock-icons to disappear ....

https://build.opensuse.org/project/monitor?utf8=%E2%9C%93&commit=Filter%3A&succeeded=1&failed=1&unresolvable=1&broken=1&blocked=1&dispatching=1&scheduled=1&building=1&finished=1&signing=1&locked=1&deleting=1&pkgname=&repo_SLE_12=1&repo_xUbuntu_15_04=1&arch_i586=1&arch_x86_64=1&project=isv%3AownCloud%3Acommunity%3Anightly&defaults=0

**Comment by Kawohl** [comment]
Ubuntu 15.04 worked!

**Comment by Kawohl** [comment]
@jnweiger you will hate me now but there is no community-owncloud package available for SLES12

**Comment by jnweiger** [comment]
No, no, John, all the blame goes to openSUSE.org for not publishing our packages.

**Comment by jnweiger** [comment]
@Kawohl Yesterdays build for SLE12 is ready for testing. https://software.opensuse.org/download.html?project=isv%3AownCloud%3Acommunity%3A8.1%3Atesting&package=owncloud

Please also test the upgrade from 8.0.4 to 8.1.0~RC1 on SLE12

**Comment by Kawohl** [comment]
Updating with the Webinterface works.
In the Command Line I run into this:

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php5/extensions/libsmbclient.so' - /usr/lib64/php5/extensions/libsmbclient.so: cannot open shared object file: No such file or directory in Unknown on line 0
Console has to be executed with the user that owns the file config/config.php
Current user: root
Owner of config.php: wwwrun

**Comment by Kawohl** [comment]
After chown
and
chmod g+w,o+w config.php

This is what i get.:

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php5/extensions/libsmbclient.so' - /usr/lib64/php5/extensions/libsmbclient.so: cannot open shared object file: No such file or directory in Unknown on line 0
ownCloud or one of the apps require upgrade - only a limited number of commands are available
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Updated <activity> to 2.0.0
Update successful
Turned off maintenance mode

**Comment by jnweiger** [comment]
@Kawohl You tried to run occ upgrade as root. It is okay that this fails.
The better approach is:
<pre>sudo -u wwwrun php /srv/www/htdocs/owncloud/occ upgrade</pre>

Confirmed good on SLE12 too:

<pre>
( 2/23) Installing: owncloud-server-8.1.0~RC1-10.1 ..........................................[done]
Additional rpm output:
owncloud-server: Upgrade starting
owncloud-server: occ maintenance:mode --on
Maintenance mode enabled
owncloud-server Upgrade complete
Maintenance mode disabled
owncloud-server: occ upgrade
ownCloud is already latest version
Maintenance mode disabled
</pre>
