### ISSUE TITLE
v8.0.4 is tagged but no corresponding release on owncloud.org?

### ISSUE THREAD

**Issue by untitaker** [owncloud/core#16743]

**Comment by LukasReschke** [comment]
Not yet released. This is only a WIP tag.

**Comment by RealRancor** [comment]
@untitaker 
Just some additional info: Final announcement is mostly done at https://owncloud.org/changelog/ and the mailinglists https://mailman.owncloud.org/pipermail/announcements/ and https://mailman.owncloud.org/mailman/listinfo/user
