### ISSUE TITLE
Wrong folder size in folder overview

### ISSUE THREAD

**Issue by tflidd** [owncloud/core#16742]
### Steps to reproduce
1. Use owncloud, sync larger folder with client on several computers
2. use it some time

### Expected behaviour
OC interface shows correct folder size

### Actual behaviour
In the folder view, the folder size is obviously wrong;
![bildschirmfoto vom 2015-06-04 11 56 05](https://cloud.githubusercontent.com/assets/8111200/7981707/04ab1674-0ab1-11e5-919e-e12a6d7ba6db.png)

But when I'm opening the folder, the size is different:
![bildschirmfoto vom 2015-06-04 11 56 15](https://cloud.githubusercontent.com/assets/8111200/7981708/08690bfe-0ab1-11e5-83ee-bf847941f48f.png)

du in the file system gives a size of 12 GB! 
sudo ... occ files:scan username doesn't help.

There is also a recent report on the forum: https://forum.owncloud.org/viewtopic.php?f=31&t=28525&p=88359

Somehow related to https://github.com/owncloud/core/issues/14298 but encryption has been disabled since then (the total storage on the user's personal page is 13.5 GB and in the filesystem it is 14 GB).

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache

**Database:** MySQL

**PHP version:**

**ownCloud version:** 7.0.5

**Updated from an older ownCloud or fresh install:** updated many times

**List of activated apps:**  - activity
 - bookmarks
 - calendar
 - contacts
 - documents
 - external
 - files
 - files_external
 - files_pdfviewer
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - gallery
 - maps
 - news
 - shorty

**Are you using external storage, if yes which one:** not this user

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

**Logfiles:** There is nothing specific in the logfiles, I can't say when it exactly appeared. Perhaps some interrupted sync or lost wifi connection??

**Comment by karlitschek** [comment]
@icewind1991 Can you have a look?

**Comment by tflidd** [comment]
I tried the fix for shared folders in https://github.com/owncloud/core/pull/14861 but it didn't work (there are no shared folders)

**Comment by PVince81** [comment]
@tflidd can you check the "size" values in oc_filecache of the folders ?

Maybe there were multiple scanners trying to compute the folder sizes at the same time concurrently and gave wrong results.

**Comment by tflidd** [comment]
The parent folder (shown in images above) has a size of: 12037693124 in the filecache-table. There is still the field with unencrypted size (encryption was turned off some months ago): 449034503 (this seems to be the size shown on the interface).

**Comment by PVince81** [comment]
Hmm, if I remember correctly, whenever you disable encryption, it will not automatically recompute the sizes, so you might still have old sizes there.

Did you try running `./occ files:scan --all` ?

**Comment by tflidd** [comment]
I did run the ./occ files:scan several times but it didn't change anything.
In the meantime, I repaired my filecache-table with this sql-command:
UPDATE `oc_filecache` SET `unencrypted_size`=0 WHERE `encrypted`=0

**Comment by PVince81** [comment]
Ah yes, that would work too.

**Comment by tflidd** [comment]
I leave it open for you, if you want to fix the encryption enabling/disabling-routine. From my point of view, the problem is solved.

**Comment by PVince81** [comment]
Thanks. I think I discussed this with @schiesbn before and decide to leave it.
Also, since 8.1 disabling encryption will be done using a separate mechanism.

@schiesbn your call

**Comment by PVince81** [comment]
Closing as obsolete.

Since encryption 2.0 (OC >= 8.1) the size column will always contain the unencrypted size, so doesn't need to be updated after encrypting/decrypting.
