### ISSUE TITLE
Message "Can not decrypt this file probably this is a shared file..." on some files *not* shared with anybody

### ISSUE THREAD

**Issue by arnoldu** [owncloud/core#16749]
### Steps to reproduce
1. Have a large tree of files which belong to one user and have never been shared to anybody under owncloud 7.0.x
2. Upgrade to owncloud 8.0.3 (stable) using the manual mode
3. Start the desktop sync on one client
4. Watch the progress and status log on the client which completly stops at certain files.
5. Log on to the web UI, find the files which makes the desktop stop and try to download the files manually
6. Receive the error message "can not decrypt the file probably this is a shard files". which it isnt. 

### Expected behaviour
All files which where accessable under Owncloud 7.x should be accessable under Owncloud 8.0.3 from the Desktop client as well as from the web UI.

### Actual behaviour
The Desktop client hangs and stops operation completly with the above error message. The desktop log shows "Connection terminated". When I restart the desktop client it happens at the very same file. When I manually delete the file another file is producing the same behaviour. I am sure that those files did work and were accessible some hours ago under Owncloud 7.

When accessing the stopping files from the web gui the above error message is shown for the file.

### Server configuration
**Operating system**: Linux / Ubuntu 14.0.2 LTS 64bit

**Web server:** NGinx

**Database:** MySQL

**PHP version:** 5.5

**ownCloud version:** 8.0.3 (stable)

**Updated from an older ownCloud or fresh install:**
Updated from Owncloud 7 using the manual method. 

**List of activated apps:**
Activity
Deleted Files
First Run Wizard
PDF-Viewer
Pictures
Server-Side encryption
Share files
text editor
updater
versions

**The content of config/config.php:**

<?php
  2 $CONFIG = array (
  3   'instanceid' => '516865f1bf519',
  4   'passwordsalt' => 'xxx',
  5   'datadirectory' => '/var/www/owncloud_data',
  6   'dbtype' => 'mysql',
  7   'version' => '8.0.3.4',
  8   'dbname' => 'owncloud',
  9   'dbhost' => 'localhost',
 10   'dbtableprefix' => 'oc_',
 11   'dbuser' => 'oc_administrator',
 12   'dbpassword' => 'xxxx',
 13   'installed' => true,
 14   'maintenance' => false,
 15   'theme' => '',
 16   'trusted_domains' =>
 17   array (
 18     0 => 'owncloud.udeedv.com',
 19   ),
 20   'mail_smtpmode' => 'smtp',
 21   'mail_smtpname' => 'xxx',
 22   'mail_smtppassword' => 'xxx',
 23   'mail_from_address' => 'xxx',
 24   'mail_domain' => 'xxx',
 25   'mail_smtpauth' => true,
 26   'mail_smtphost' => 'xxx',
 27   'mail_smtpport' => '587',
 28   'secret' => 'xxxx',
 29   'loglevel' => 5,
 30 );

**Are you using encryption:** yes

### Client configuration
**Browser:**

Firefox / Chrome

**Operating system:**

Ubuntu 15.04

#### Web server error log
```
the only line when accessing a stopping file is a redirection, there are no other hints of misfunction in any log file:
 93.232.142.71 - arnold [04/Jun/2015:12:54:14 +0200] "GET /remote.php/webdav/Dokumente_Arnold/putty/sessions/StephanSiebert-neu HTTP/1.1" 302 0        "-" "Mozilla/5.0 (Linux) csyncoC/0.91.5 neon/0.30.0"
```
#### ownCloud log (data/owncloud.log)
```
there are no related lines in the ownCloud.log !
```

**Comment by LukasReschke** [comment]
@schiesbn @th3fallen Any idea?
@arnoldu Thanks a lot for the detailled bug report! Much welcome :+1:

**Comment by arnoldu** [comment]
The upgrade process went well but one thing was strange - if related to this bug:

The web gui hung in maintenance mode forever, I had to manually cancel the maintenance mode in the config.php and restart the web server. After this my user could access some of his files (not all, see above) *but* the administrators password was "gone", e.g. it was not possible to log on with the old password which might be the case because in the password column of the oc_user was my admin the last user whose encryption method had not been changed to $2a$ which indicated me that his (very old) password was not readable anymore. I manually changed his password for the moment.

**Comment by arnoldu** [comment]
I should mention that I moved the data directory after the upgrade out of the /var/www/owncloud directory to /var/www/owncloud_data to make future upgrades easier. I changed this in the config.php as well. 

I already tried to delete all lines from the table oc_filecache, restarted the NGINX but to no avail.

**Comment by arnoldu** [comment]
If nothing helps I should mention that I use owncloud **only** to share around 5 GByte of Docs and Code between my three computers. So I could easily restart with a "fresh " owncloud 8.0.3 and reimport all files again from one the other computers. On the one I did the experiments all files after the stopping file were gone !!!

**Comment by PVince81** [comment]
The web GUI hung, that's the key. It was probably still doing the migration of the encryption keys. It might even have run into a PHP timeout.
Ideal is to always do the upgrades on the command line with `./occ upgrade`.

Please never delete the contents of oc_filecache. This will cause you to lose all shares and metadata.

I see you have moved the data folder, please check the oc_storages to make sure you do not have any hard-coded entries (from much earlier ownCloud versions).

Anyway, apart from that I think your problem is probably due to an incomplete migration.

@schiesbn can you point @arnoldu to the backup keys and/or steps to put them back and restart the migration ? Thanks. Do we have any documentation about this ?

**Comment by schiesbn** [comment]
Closed due to inactivity for almost a year. If this is still a issue feel free to re-open it. I assume that this was one of the early upgrade issues fixed a long time ago.
