### ISSUE TITLE
Deleting a remote shared file/folder does not delete the item for the sharee

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#16751]
Discovered when writing a new smashbox test: https://github.com/owncloud/smashbox/issues/102

### Steps to reproduce

1. As user1 remote share `test.txt` with `user2@localhost`
2. As user2 login and accept the share
3. As user2 see the preview on the share
4. As user1 delete the file (do **NOT** unshare before)
5. As user2 refresh the file list

### Expected
The file should be deleted

### Actual
The file is still in the list, but the preview is gone.
Clicking on the file brings up an empty error dialog:

![bildschirmfoto vom 2015-06-05 10 12 10](https://cloud.githubusercontent.com/assets/213943/8001988/6b7ad938-0b6b-11e5-86fe-3bda9955358c.png)

**Comment by nickvergessen** [comment]
Okay, the problem is, that we now have stable file ids. :eyes: 

We have a job, that cleans up shares. The check whether or not a share should be deleted checks whether the file id still exists.
This is the case, but the path is `files_trashbin/files/test.txt.d1433492504` now. So we retain the share.
So the "delete" never reaches the remote share, because the share is still "some what" valid.
I don't think that the idea is to keep those shares working, while they are in trashbin.

So I think we should unshare remote shares, when the share itself is moved to the trashbin. When the item is then restored the remote shares will have to be recreated (and send a new request to the sharee?).

@schiesbn @PVince81 I think I need your help here as well.

**Comment by DeepDiver1975** [comment]
@th3fallen just another federated-sharing issue - wana have a look? THX

**Comment by nickvergessen** [comment]
Actually https://github.com/owncloud/core/blob/760ce3bd6326d1c5d804bf0eba93f20de5e68e98/apps/files_sharing/lib/deleteorphanedsharesjob.php#L51-L62 could also be fixed, to notify remotes when a share is being deleted, so they know they can stop asking for it

**Comment by PVince81** [comment]
When a federated shared folder is deleted, we could send a removal request.
But I don't think we should resend the invitation on restore. Because to do this it means we need to track the deleted shares somewhere to be able to restore them, possibly a new table or column.

For now I'd rather go for simply notifying the remote recipient that the share is gone.

**Comment by nickvergessen** [comment]
> But I don't think we should resend the invitation on restore. Because to do this it means we need to track the deleted shares somewhere to be able to restore them, possibly a new table or column.

I ment manually resend the invitations

**Comment by schiesbn** [comment]
Would be possible for the file/folder you delete. But if it us a (huge) folder you would need to check every sub-file and sub-folder and send the un-share requests. This would probably create performance issues. Maybe this could be done in the clean-up job for orphaned shares?

**Comment by nickvergessen** [comment]
Well, then it would be nice to have a reliable way to trigger those, so we can call that in smashbox to see if they are expired correctly.

**Comment by DeepDiver1975** [comment]
since there is no sev assigned I'll move this to 8.2

**Comment by cmonteroluque** [comment]
@nickvergessen @DeepDiver1975 stay on 8.2?

**Comment by nickvergessen** [comment]
no sev as said, can be defered again

**Comment by PVince81** [comment]
@nickvergessen @rullzer is this still happening in 9.0beta1 ?

**Comment by nickvergessen** [comment]
The smashbox test doesn't work anymore, would need to debug

**Comment by nickvergessen** [comment]
yes, the [smashbox test](https://github.com/owncloud/smashbox/pull/102) still fails:
```
ERROR - sharee_two - File .../sharee_two/TEST_FILE_USER_RESHARE.dat does not exist but should
```

**Comment by nickvergessen** [comment]
Maybe @icewind1991 can help here a bit, I assume it's more of a storage problem

**Comment by nickvergessen** [comment]
After some lunch discussion the following idea was the conclusion:

When a remote share is deleted by moving it to the trash, the remote shares should stay intact.
This is needed, because otherwise the "restore" is not an undo of the delete anymore.

While the share is in the trash, the remote user however should be able to have the file synced (like with normal storage not available exception) and be able to unsubscribe, so we can not hide it from the file list, although the item itself gives a NotFound response.

@schiesbn can you think about this as well? If you agree, I'd go ahead and adjust the smashbox test to this.

**Comment by PVince81** [comment]
Should we keep this ticket solely for the unit test then ?

Some bogus behavior was fixed with https://github.com/owncloud/core/pull/22498

**Comment by jancborchardt** [comment]
I’d say for a single file share, or removal of the root of the share by the original sharer, it should basically be the same result for others as an unshare. They should still keep the files. This is also how Dropbox handles deletion of the share root.

**Comment by nickvergessen** [comment]
Yeah lets keep that so I have a reminder to finish the smashbox job

**Comment by PVince81** [comment]
@jancborchardt what do you mind with "they should still keep the files" ? Who are "they" ?
Federate shares do not make copies of files.

**Comment by jancborchardt** [comment]
> what do you mean with "they should still keep the files" ? Who are "they" ?

The people whom it was shared with.

> Federate shares do not make copies of files.

I know. However if we want to provide a consistent experience and make federated sharing as awesome as normal sharing, then the original sharer unsharing from me or deleting should **not** result in the file vanishing from my ownCloud. cc @DeepDiver1975 @karlitschek

**Comment by PVince81** [comment]
@jancborchardt please raise an enhancement ticket to discuss this for 9.1.
Also make sure to mention whether you suggest having this for both fed shares and local shares.

**Comment by rullzer** [comment]
> I know. However if we want to provide a consistent experience and make federated sharing as awesome as normal sharing, then the original sharer unsharing from me or deleting should not result in the file vanishing from my ownCloud. cc @DeepDiver1975 @karlitschek

What? That is exactly what should happen. The same as a local user unshares from me the files also vanish..

**Comment by PVince81** [comment]
> Yeah lets keep that so I have a reminder to finish the smashbox job

:alarm_clock:

**Comment by nickvergessen** [comment]
Ready to review https://github.com/owncloud/smashbox/pull/102#issuecomment-191694556

**Comment by nickvergessen** [comment]
Test adjusted and merged...
