### ISSUE TITLE
{PHP} Cannot modify header information at /var/www/owncloud/lib/private/files.php#166

### ISSUE THREAD

**Issue by srggavrilov** [owncloud/core#16754]
### Steps to reproduce
1. Let Apache handle static file serving as described [here] (https://doc.owncloud.com/server/8.0/admin_manual/configuration_files/serving_static_files_configuration.html).
2. Try to download file that doesn't exist

### Expected behaviour
No PHP errors in owncloud.log

### Actual behaviour
{PHP} Cannot modify header information - headers already sent by (output started at /var/www/owncloud/lib/private/template/base.php:108) at /var/www/owncloud/lib/private/files.php#166

### Server configuration
**Operating system**: 3.16.0-30-generic x86_64 GNU/Linux
**Web server:** Apache/2.4.7

**Database:** mysql  Ver 14.14 Distrib 5.5.43

**PHP version:** PHP 5.5.9-1ubuntu4.9

**ownCloud version:** ownCloud 8.0.3 (stable) 

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by DeepDiver1975** [comment]
@srggavrilov but it is working - right?

**Comment by cmonteroluque** [comment]
@srggavrilov are there any other symptoms besides this error message? We're marking it to have a look in the next maintenance cycle

**Comment by srggavrilov** [comment]
@DeepDiver1975 I've just checked it again and found out the strange behavior. 
I tried to download file in Chrome with X-Sendfile enabled and could resume download. Then I disabled X-Sendfile and could resume download anyway. Additionally it was failed in Firefox in both cases.
I'm not sure if this's somehow related to the original report. Just wonder how to check if it's working?

**Comment by cmonteroluque** [comment]
@jnfrmarks please add this to the test plan

**Comment by cmonteroluque** [comment]
@SergioBertolinSG @davitol can one of you check this please?

**Comment by SergioBertolinSG** [comment]
Tested it using X-sendfile in a 8.0.5beta server, no problems found. I suggest to close the issue.

**Comment by cmonteroluque** [comment]
thanks
