### ISSUE TITLE
Prevent DELETE of public webdav root

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#16757]
### Steps
1. Share a folder "test" with link, allow upload
2. `curl -X DELETE http://$TOKEN@localhost/owncloud/public.php/webdav/` (replace $TOKEN with the share token)

### Expected result
403 Forbidden

### Actual result
This deletes the folder "test" completely and destroys the share.
This means that someone who has write access to the share can remotely unshare it by deleting it.
So other people who might have had access before might be disappointed.

### Versions
ownCloud 8.1 git master (c747a58978ffd1985c547f94cedec29663d73496)

@SergioBertolinSG @jnfrmarks another one
@icewind1991 @LukasReschke

**Comment by nickvergessen** [comment]
certainly sounds indesired

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/16767
