### ISSUE TITLE
Get rid of the MP3 Preview Generation in core and getid3

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#16766]
The code is shabby and we really should get rid of it. Not worth it.

**Comment by karlitschek** [comment]
depends if this is used by someone like the music app. Or is this the preview only?

**Comment by LukasReschke** [comment]
> depends if this is used by someone like the music app. Or is this the preview only?

Preview in core only. Music app bundles it's own copy: https://github.com/owncloud/music

**Comment by oparoz** [comment]
You might not even need to take care of this if Preview finally moves to an app in 8.2 and I would try to ask in the forums to see if there is some resistance.

**Comment by MorrisJobke** [comment]
> depends if this is used by someone like the music app. Or is this the preview only?

Apps should be self containing. And this is a very special dependency, that is only used by the preview mechanism. As lukas already said: music bundles it's own version of getid3 (and uses it only if it isn't loaded already).

**Comment by PVince81** [comment]
Any update ? Move to 9.0 ? (I predict bigger code changes here)

**Comment by LukasReschke** [comment]
https://github.com/owncloud/core/pull/23766 will keep the preview in core and just makes getid3 more sane…
