### ISSUE TITLE
big file chunking not working

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#16760]
### Steps to reproduce
1. Upload a big file through webdav using file chunking (checked with a 50MB file and the desktop client 1.8.2beta1)

### Expected behaviour
File is uploaded correctly

### Actual behaviour
File isn't uploaded

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** 8.1 beta 2 (daily) Build:2015-06-05T03:07:57+00:00 5ea06f31b90b147662f3908d4f5de8c44987bf9b 

**Updated from an older ownCloud or fresh install:** fresh install

#### ownCloud log (data/owncloud.log)
```
{"reqId":"9Up8dM14RW7T4mkAqD9G","remoteAddr":"82.159.139.58","app":"admin_audit"
,"message":"User user logged into ownCloud from IP address: 82.159.139.58","leve
l":1,"time":"2015-06-05T10:51:21+00:00","method":"PROPFIND","url":"\/remote.php\
/webdav\/"}
{"reqId":"NprFqlMzcrqAN3XdLyZw","remoteAddr":"82.159.139.58","app":"admin_audit"
,"message":"Create \"\/user\/files\/folder\" by user user, owner: user","level":
1,"time":"2015-06-05T10:51:22+00:00","method":"MKCOL","url":"\/remote.php\/webda
v\/folder"}
{"reqId":"KdcdfMdMjfubrU1QcdAX","remoteAddr":"82.159.139.58","app":"PHP","messag
e":"Class 'OC\\Cache\\File' not found at \/opt\/owncloud\/lib\/private\/filechun
king.php#56","level":3,"time":"2015-06-05T10:51:23+00:00","method":"PUT","url":"
\/remote.php\/webdav\/folder\/bigfile.dat-chunking-3116926120-10-0"}
```

**Comment by DeepDiver1975** [comment]
> Class 'OC\\Cache\\File' not found at

WTF?

**Comment by DeepDiver1975** [comment]
AUTSCH - https://github.com/owncloud/core/pull/16200

**Comment by DeepDiver1975** [comment]
@blizzz looks like we did kill too much

**Comment by DeepDiver1975** [comment]
Let me see if I can get this working without reverting #16761

**Comment by nickvergessen** [comment]
@DeepDiver1975 why aren't the smashbox tests triggered nightly?

`bin/smash lib/oc-tests/test_uploadFiles.py -t=0` fails since #16200 is merged, which was some hours after our latest run https://ci.owncloud.org/job/smashbox/22/

The nightly execution would have discovered it 2 days ago :wink:

**Comment by DeepDiver1975** [comment]
> The nightly execution would have discovered it 2 days ago :wink:

Will have a look - maybe Jenkins has no constant understanding of time ....

**Comment by DeepDiver1975** [comment]
fixed with 16765
