### ISSUE TITLE
Setting up a Mobile and Desktop Client Communications Mechanism

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#16772]
As an ownCloud admin, I want to be able to push messages to users and prompt users with confirmations on desktop and mobile clients (as well as the web client) so that users can have a more complete and integrated experience while accessing external storage, two factor authentication, oAuth, and other capabilities of the server from the mobile and desktop clients.

Acceptance Criteria:
- Communications channel should communicate types of messages, allowing mobile and desktop to display the proper interaction dialogs for users to respond to messages from the server
   - One is a confirmation type error message with a yes/no response expected from the client and sent back to the server
      - Examples: confirm shared folders; confirm large folder syncs
   - One is a standard authentication dialog - so users can enter new passwords
      - Examples: password error results in a password change dialog for external storage backend
   - One is for communication purposes only, to tell users something
      - Examples: notify users of the need to upgrade; notify users of maintenance windows
   - One is a SSO authentication window
      - Examples: OAuth authentication; two factor addition

This channel for communication and interaction provides an entirely new level of server/client interaction, and helps customers handle the kinds of detailed workflows that exist in complex heterogeneous server environments.

@karlitschek

**Comment by MTRichards** [comment]
@cmonteroluque

**Comment by PVince81** [comment]
@MTRichards I thought we already had a ticket for this, but maybe it was actually the system-wide ticket https://github.com/owncloud/core/issues/19152

CC @nickvergessen

**Comment by MTRichards** [comment]
Yeah, I think #19152 supersedes this.

**Comment by nickvergessen** [comment]
Then lets close the smaller one
