### ISSUE TITLE
Better description of "Enforce HTTPS" in admin backend

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#16778]
Hi,

the option "Enforce HTTPS" within the admin backend is subject of a lot of misinterpretation. Quite often it happens that:

1. Users think they can magically enable SSL within their webserver when using this option
2. Users don't know at all why the checkbox is greyed out

Currently don't know if its better to just document this: https://github.com/owncloud/documentation/issues/1197 or just extend the description here:

https://github.com/owncloud/core/blob/v8.0.4/settings/templates/admin.php#L396

This affects only OC8 and below as OC8.1 has removed this checkbox: https://github.com/owncloud/core/pull/14651

**Comment by karlitschek** [comment]
What description would you suggest?
@LukasReschke We removed it for 8.1?

**Comment by RealRancor** [comment]
Maybe just an extension like:

> Forces the clients to connect to %s via an encrypted connection (If greyed out you need to configure your webserver for SSL and access the %s instance via https://).

**Comment by RealRancor** [comment]
Nevermind, just have seen that there is already such a description one line below:

https://github.com/owncloud/core/blob/v8.0.4/settings/templates/admin.php#L415-L423

If users are not reading this then i don't know what to do else...

**Comment by RealRancor** [comment]
Re-Open. Seems people still don't get it with the shown information that "Force SSL" doesn't mean that you enable SSL itself for the ownCloud instance:

https://forum.owncloud.org/viewtopic.php?f=21&t=28727

**Comment by gioman** [comment]
Hi, I'm running ownCloud 8.1.0 (stable), https is already configured on the web server, but the "enforce https" option is not available... while I can see it on a 7.* instance installed recently. Was this option removed? Thanks.

**Comment by RealRancor** [comment]
@gioman 

Yes, this was removed as written in the initial issue:

> This affects only OC8 and below as OC8.1 has removed this checkbox: https://github.com/owncloud/core/pull/14651

**Comment by gioman** [comment]
sorry I overlooked that. Cheers.

**Comment by MorrisJobke** [comment]
Fix is in #7917
