### ISSUE TITLE
Files and several other apps aren't working after update to 8.0.4

### ISSUE THREAD

**Issue by alex42ka** [owncloud/core#16777]
As described above. I've updated today to 8.0.4 over apt-get. Then, without testing, I've reactivated some apps. Now my users can't see their files and the admin (me) can't access the App-configuration anymore, it is not stopping to load . As well I couldn't see the users in the users-app but they can login. The configuration check is not stopping to load as well.
The following apps are working as expected:
- calendar
- contacts
- ownnote
- tasks
- music
- news
- roundcube-mail
- activity
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty
```
Web-Server:
```
$ apache2 -v
Server version: Apache/2.4.7 (Ubuntu)
Server built:   Mar 10 2015 13:05:59
```

Database:
```
$ mysql --version
mysql  Ver 14.14 Distrib 5.5.43, for debian-linux-gnu (x86_64) using readline 6.3
```
PHP version:
```
$ php -v
PHP 5.5.9-1ubuntu4.9 (cli) (built: Apr 17 2015 11:44:57) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```
Owncloud-Apps:
```
sudo -u www-data php ./occ app:list
Enabled:
 - activity
 - bookmarks
 - calendar
 - contacts
 - direct_menu
 - documents
 - external
 - files
 - files_pdfviewer
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - files_videoviewer
 - firstrunwizard
 - gallery
 - galleryplus
 - music
 - news
 - notes
 - ownnote
 - roundcube
 - tasks
 - templateeditor
 - user_ldap
Disabled:
 - files_encryption
 - files_external
 - files_locking
 - provisioning_api
 - tasks_enhanced
 - user_external
 - user_webdavauth
```
config.php without sensitive data:
```
<?php
$CONFIG = array (
  'instanceid' => 'oca4dff1e574',
  'passwordsalt' => '***',
  'trusted_domains' => 
  array (
    0 => '***',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.0.4.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '***',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'forcessl' => true,
  'mail_from_address' => 'owncloud',
  'mail_smtpmode' => 'php',
  'mail_domain' => '***',
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'logtimezone' => 'Europe/Berlin',
  'log_type' => 'syslog',
  'loglevel' => '0',
  'log_authfailip' => true,
  'theme' => '',
  'maintenance' => false,
  'secret' => '***',
  'forceSSLforSubdomains' => true,
  'overwrite.cli.url' => '/owncloud',
);
```

**Comment by alex42ka** [comment]
I've deactevated the following apps 
- notes
- gallery
- external

via:
```
$ sudo -u www-data php ./occ app:disable external
external disabled
```

and now everything is working again as expexted. Maybe a bug in one of these apps?

**Comment by RealRancor** [comment]
@alex42ka 
Which version do you have upgraded to OC 8.0.4?

Having a look at your logfiles of webserver, php and data/owncloud.log can give you some pointers about the issues of this apps.

**Comment by PVince81** [comment]
Please try and find out which of these three apps is breaking OC when you enable it.
Then report either to https://github.com/owncloud/notes https://github.com/owncloud/gallery/ or https://github.com/owncloud/apps (for "external"). Make sure to include a snippet of the owncloud.log

Thanks. You might have more luck with 8.0.6 or 8.1.1.
