### ISSUE TITLE
Layout broken for Users page

### ISSUE THREAD

**Issue by binarykitchen** [owncloud/core#16776]
### Steps to reproduce
Go to index.php/settings/users

### Expected behaviour
You see a nicely styled table with users

### Actual behaviour
Layout is broken, see screenshot
![disorted_users_layout](https://cloud.githubusercontent.com/assets/177641/8018707/d74fdac4-0c7d-11e5-8d27-07fe96245279.png)

### Server configuration

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty
```

```
$ uname -a      
Linux binarykitchen.com 3.12.27-xenU #1 SMP Thu Aug 28 23:13:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

Web server:

```
$ nginx -v
nginx version: nginx/1.8.0
```

Database:

```
$ mysql --version
mysql  Ver 14.14 Distrib 5.5.43, for debian-linux-gnu (x86_64) using readline 6.3
```

PHP version:

```
$ php -v
PHP 5.5.25-1+deb.sury.org~trusty+2 (cli) (built: May 24 2015 15:45:37) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies
```

ownCloud version:
ownCloud 8.0.4 (stable) 

Updated from an older ownCloud or fresh install:
Fresh install via apt-get

```
$ sudo -u www-data php ./occ app:list
Enabled:
 - activity
 - calendar
 - documents
 - files
 - files_encryption
 - files_locking
 - files_pdfviewer
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - files_videoviewer
 - gallery
 - galleryplus
 - mozilla_sync
 - music
 - provisioning_api
 - tasks
 - templateeditor
 - user_webdavauth
 - videos
Disabled:
 - external
 - files_external
 - firstrunwizard
 - user_external
 - user_ldap
```

The content of config/config.php: (Without sensitive data)

```
$ cat config.php
<?php
$CONFIG = array (
  'instanceid' => 'oc02ca513338',
  'passwordsalt' => 'xxx',
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.0.4.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'xxx',
  'installed' => true,
  'forcessl' => true,
  'loglevel' => 1,
  'logfile' => '/var/log/owncloud.log',
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' => 
  array (
    0 => 'xxx.yyy.com',
  ),
  'mail_smtpmode' => 'smtp',
  'secret' => 'xxx',
  'forceSSLforSubdomains' => true,
  'mail_smtpsecure' => 'tls',
  'mail_smtphost' => '127.0.0.1',
  'mail_smtpport' => '587',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'xxx',
  'mail_smtppassword' => 'xxx',
  'mail_smtpauthtype' => 'PLAIN',
);
```

Are you using external storage, if yes which one:
None

### Client configuration
Browser:
Firefox 38

Operating system:
Ubuntu 15.04

#### Web server error log
nginx error log is empty since a couple of days, hence irrelevant.

#### ownCloud log (data/owncloud.log)
N/A

#### Browser log
Irrelevant

**Comment by RealRancor** [comment]
Hi,

i don't know if this is the reason but try to disable the user_webdavauth / WebDAV user backend app which you shouldn't activate anyway (read the description of the app when you need to enable it).

**Comment by binarykitchen** [comment]
What does the WebDAV backend app have to do with this? Looks more likely a CSS problem within the layout. Figured out that disabling all the bad gallery apps solved this issue.

**Comment by DeepDiver1975** [comment]
> Figured out that disabling all the bad gallery apps solved this issue.
I'm able to reproduce this with galleryplus on stable8 branch - please reopen this in the galleryplus repo https://github.com/owncloud/galleryplus/issues
