### ISSUE TITLE
Debian 8 packages: Also recommend mariadb-server

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#16788]
With Debian 8/Jessie a new package "mariadb-server" is provided which is a Drop-In replacement for MySQL. The OBS packages could be changed to reflect this:

> Recommends: mysql-server, curl, exim4 | mail-transport-agent

to:

> Recommends: mysql-server | mariadb-server, curl, exim4 | mail-transport-agent

in: https://build.opensuse.org/package/view_file/isv:ownCloud:community:8.0/owncloud/debian.control?expand=1

**Comment by karlitschek** [comment]
@jnweiger FYI

**Comment by DeepDiver1975** [comment]
@jnweiger for 8.1 maybe? feel free to move - THX

**Comment by jnweiger** [comment]
@RealRancor Thanks for the info!

Definitly makes sense to have mysql-server and mariadb-server as alterinatives. It is so cool that DEB provides the notation of alternative requirements. Wish RPM also had that!

**Comment by jnweiger** [comment]
Fixed in isv:ownCloud:community:8.1:testing/owncloud commit#3, 8.1.0~Beta2-5
