### ISSUE TITLE
files getting deleted after gateway timeout on client

### ISSUE THREAD

**Issue by onelight17** [owncloud/core#16782]
So I have two separate clients and locations that sync for the same set of file. One of the locations is in a remote location with not the most stable internet. Every time this client fails to download a file it shows up in the activity log as "Gateway error" and then i see the file it failed to download is deleted completely from the system. This mostly happens with new files. I will create the file on one client here and then the remote location tries to download and fails and then the file gets removed from the server and my location.

What could be causing this? Is this a bug?

EDIT: 
just realized that I didn't provide much information about my setup
I am running OC 8.0.2 on Linux (Ubuntu) running behind nginx + php.

The clients are both the latest stable versions released.

EDIT2 (Sorry about not using the template, please see below):

### Steps to reproduce
1. Create/Edit a file on one client
2. Wait for other client to sync and get a timeout error while trying to download the new/changed file
3. Original file now gets deleted

### Expected behaviour
It should retry the download and not delete the file completely

### Actual behaviour
See original post above

### Server configuration
**Operating system**: Linux Mint (Ubuntu based)

**Web server:** Nginx + PHP5

**Database:** MySQL

**PHP version:** 5.5.9

**ownCloud version:** 8.0.2

**Updated from an older ownCloud or fresh install:**

**List of activated apps:** N/A

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'oc16c6f5705e',
  'passwordsalt' => 'xxx',
  'trusted_domains' =>
  array (
    0 => 'xxx',
    1 => 'xxx',
    2 => 'xxx',
  ),
  'datadirectory' => '/mnt/OCData/data',
  'dbtype' => 'mysql',
  'version' => '8.0.2.0',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'installed' => true,
  'loglevel' => '3',
  'mail_smtpmode' => 'smtp',
  'theme' => '',
  'maintenance' => false,
  'secret' => 'xxxx',
);

```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**

**Operating system: Windows 8

***********Will provide logs once I see the issue happen again and I can capture the activity in the logs.
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by karlitschek** [comment]
Can you please post a full bug report using our issue template? 
https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by nickvergessen** [comment]
Also please update your server to 8.0.3 or 8.0.4 (which is being released these days) and see if the problem is fixed.

**Comment by onelight17** [comment]
Yes I will try updating the server first and see if I still have the issue. I updated the ticket otherwise as well

**Comment by PVince81** [comment]
Please try again with 8.0.6 or 8.1.1, also with sync client 1.8.4.

If you're still having these issues, feel free to reopen.
