### ISSUE TITLE
Similar Paths are not possible to konfigurate

### ISSUE THREAD

**Issue by Kokomiko** [owncloud/core#16785]
I have 2 Paths in my documents folder which i like to synchronize with Linux Client e.g. documents/house and documents/housekeeping.

If i try to configure the second path, i get a Message "An already configured folder contains the specified folder".
I get the Message in german, therefore the english message should sound different.

Excuse me for my ugly english!  :-)

Version of Client is 1.5.0, 

cu
Kokomiko

**Comment by RealRancor** [comment]
Hi,

try to update to the latest version of the sync client (1.8.2) and try again. If this is still happening re-open in: https://github.com/owncloud/client/issues where the issue tracker of the sync client is located.

**Comment by Kokomiko** [comment]
Hi,

Excuse me, this idea I should have had by myself! 

Thanks!
