### ISSUE TITLE
autotest.sh fails without any feedback

### ISSUE THREAD

**Issue by krichter722** [owncloud/core#16789]
Running `./autotest.sh` in the source root fails without any feedback (returncode is `1`).

experienced with 35421487610462b12e3600954f23a777c54abee3

**Comment by DeepDiver1975** [comment]
Anything in the log? Phpunit missing?

**Comment by PVince81** [comment]
Possibly missing phpunit.

If you're still having issues, please provide more details about your env (PHP version, PHP unit version, etc).
