### ISSUE TITLE
All share by links invalid after upgrading from 8.0.2 to 8.0.3

### ISSUE THREAD

**Issue by watermark** [owncloud/core#16799]
All links we had generated in 8.0.2 are now invalid after upgrading to 8.0.3.  It returns the error: "File not found - The specified document has not been found on the server" when the link is used.  All of the links are still in the "share" database.

When a new link is generated for the exact same file, it uses a different id from the filecache which uses a different storage id.  The old storage path was "home::estimating" while the new one is "local::/home/username/ownclouddata/_shared_data/estimating/"

The links were for files in a local folder from the external storage plugin, perhaps this caused the issue?

**Comment by karlitschek** [comment]
@PVince81 hmm. is sounds bad. what do you think?

**Comment by PVince81** [comment]
@watermark did you move the data folder after upgrading ?
Do you have old hard-coded paths "local::$pathToOldDataDir" ?

**Comment by watermark** [comment]
The data folder was not moved.  Nothing was changed outside of the upgrade from 8.0.2 to 8.0.3.

I'm not quite sure what you're asking in the second question.  There are only 3 items with the prefix "local::" in the storage table: "local::/home/username/ownclouddata/", "local::/home/username/ownclouddata/_shared_data/estimating/", and "local::/home/username/ownclouddata/_shared_data/operations/".

We do have a database backup from just before the upgrade.  The upgrade has changed all (3) of the old links from "local::/path/to/share/foldername" to links like "home::foldername" in the storage table.  It then re-added the full "local::/path/to/share/foldername" as new storage ids.

The file cache grew quite a bit too after the upgrade.  It's kinda looking like it re-added all of the files to the cache under the new storage ids that it generated.

**Comment by PVince81** [comment]
If the upgrade properly renamed the "local::" entries to "home::" and did not leave any outdated paths, then this is not the known issue with storages that is causing trouble with link shares.

So are you saying that "local::/home/username/ownclouddata/_shared_data/estimating/" is an external storage of type "Local" ? Were the files shared from there ?
Such entries should stay as is and have nothing to do with the "home::" storages.

**Comment by watermark** [comment]
Yes, "local::/home/username/ownclouddata/_shared_data/estimating/" is an external storage of type local.

Yes, there were files shared from that local storage.

As an example, storage id 9 used to say "local::/home/username/ownclouddata/_shared_data/estimating/", but now says "home::estimating" after the upgrade.  Storage id 25 was not there before the upgrade and it is "local::/home/username/ownclouddata/_shared_data/estimating/".  All links that point to entries for storage id 9 come back as "file not found".  If a new share-by-link is created, it links it to the new storage id 25 (which works fine).

**Comment by MorrisJobke** [comment]
> As an example, storage id 9 used to say "local::/home/username/ownclouddata/_shared_data/estimating/", but now says "home::estimating" after the upgrade. Storage id 25 was not there before the upgrade and it is "local::/home/username/ownclouddata/_shared_data/estimating/". All links that point to entries for storage id 9 come back as "file not found". If a new share-by-link is created, it links it to the new storage id 25 (which works fine).

@PVince81 This looks like there is a problem in the migration of local:: to home:: storages.

@watermark What is your datadirectory? Can be found in the confi/config.php?

**Comment by watermark** [comment]
The data directory in the config file is "/home/username/ownclouddata".  There two paths in external storage of type local pointed to "/home/username/ownclouddata/_shared_data/estimating" and "/home/username/ownclouddata/_shared_data/operations"

**Comment by MorrisJobke** [comment]
@watermark Okay. I guess this is the problem. So you mounted files from within the data directory via the local storage provider in the external storage app? Sounds like a very weird setup.

**Comment by MorrisJobke** [comment]
@watermark Workaround for you: rename back the mount entries in the storages table and delete the newly created ones (new shares, that are created between the upgrade and now are lost). But this will occur again during the next upgrade, because there are repair steps, that cause this.

Other way to solve this: Move the mounted folders out of the data directory. It is reserved to ownCloud and shouldn't be used as source for local filesystem mounts from the files_external app.

**Comment by MorrisJobke** [comment]
@PVince81 or do we really want to support local files system mounts that point to a folder within the data dir?

**Comment by watermark** [comment]
> Move the mounted folders out of the data directory.

What are the side effects of doing this?  Will just the share-by-links be invalidated, or what else should I expect?

**Comment by MorrisJobke** [comment]
> What are the side effects of doing this? Will just the share-by-links be invalidated, or what else should I expect?

@PVince81 I guess we need to explain this somewhere. Is it sufficient to move the folder and rename the storage ID? Or is there some additional entry in a mount.json inside the data directory that needs to be adjusted too?

**Comment by PVince81** [comment]
@watermark move the mounted folders out of the data directory, then also update that "local::" entry to point at the new path. Since the link shares are pointing to the storage matching that entry, they should still work.

@MorrisJobke I think we should do a local test. I don't think the repair step would touch such entries because their format isn't "local::$datadir/$user". Unless it thought that "_shared_data/estimating" is the user name. Then it might be possible to detect if $user is valid and doesn't contain invalid chars like "/" to exclude such cases.

**Comment by PVince81** [comment]
The repair has two phases: one to process the non-md5 entries and one for the md5 entries by retrieving all users one by one. We could remove the non-md5 phase and only rely on user names from the user manager.

Note: the legacy storage repair is only done once, it will not be repeated next time unless there were errors (there is a flag in the DB).

@MorrisJobke you are right, mount.json needs to be adapted too.

So here are the manual steps for @watermark:
1) Set OC in maintenance mode
2) Move the folders of the "local" external storages out of the data directory, for example to "/srv/www/ocdata/example".
3) Set the proper permissions to "/srv/www/ocdata/example" for the web server to have access
4) In "oc_storages" table delete the entries "local::/home/username/ownclouddata/_shared_data/operations/" and "local::/home/username/ownclouddata/_shared_data/estimates/" (there were created by mistake)
5) Still in "oc_storages", rename "home::estimates" to "local::/srv/www/ocdata/example/estimates/" (the new path) and "home::operations" to "local::/srv/www/ocdata/example/operations/".
6) Update all "ownclouddata/mount.json" and "ownclouddata/$user/mount.json" files and change the "datadir" to point to the new path
7) Disable maintenance mode

This means that next time ownCloud tries to access the external storage, it will compute the storage id as "local::/srv/www/ocdata/example/estimates/" and find the correct entry in oc_storages, which then will match the oc_filecache and oc_share entries.

**Comment by watermark** [comment]
@PVince81 thanks for the steps.  They're applied and seem to be working well.

**Comment by PVince81** [comment]
@watermark glad to hear that.

Let's keep this ticket to fix the repair step to properly detect non-users in paths to be converted.

**Comment by blaskovic** [comment]
I have similar problem. I have updated from 8.something to 8.0.5. After update, all of my files started to redownload via desktop client.

Then I noticed, that I have exactly 0 shared files via URL (which I used on daily basis).

I found out that I can see shared files in oc_share, but I cannot find its 'file_source' in table oc_filecache as 'fileid'.
So I run occ files:scan from command line but it did not help.

I am pretty dissapointed. I tried to follow steps in this thread but I lost it because of watermarks weird setup ;)

Any ideas how to get it back and right?

**Comment by PVince81** [comment]
If the "file_source" doesn't point to any entry it means something broke or the original file was removed. I don't see why the mapping would break in OC 8.0.x.
The only way to fix it would be to find the new file id of the file in oc_filecache (if there is any) and then set that value in "file_source" and "item_source" for the share entry. You'd need to do this manually for every file. If the public link (token) wasn't important you might as well recreate the share manually.

If you manage to find why the file id of the file has changed, you might be able to find out what actually went wrong.

**Comment by PVince81** [comment]
@blaskovic any news ?

**Comment by blaskovic** [comment]
I did not figured it out :( It's just lost.

**Comment by PVince81** [comment]
Are you still seeing this in 8.1.5 or 8.2.2 ? If yes, please reopen
