### ISSUE TITLE
reset ownCloud (delete all users)

### ISSUE THREAD

**Issue by davidak** [owncloud/core#16793]
a customer of our company wants to clone a vm with owncloud and reset it. please provide an option to select all user accounts to delete them so we don't have to delete ~200 Accounts by hand.

**Comment by LukasReschke** [comment]
That can be done either using the provisoning API or using a custom PHP script. That said, if somebody wants to completely clean their ownCloud instance the way better way would be to resetup the whole instance by dropping the database.
