### ISSUE TITLE
Feedback of failure after sending test email is poor

### ISSUE THREAD

**Issue by krichter722** [owncloud/core#16790]
After a failure of sending a test email the feedback is `A problem occurred while sending the email. Please revise your settings.`. It'd be useful to provide the reason for the failure in a dialog and/or (and preferred) a link to the log file containing the detailed error message and the reason.

**Comment by LukasReschke** [comment]
Will be fixed with ownCloud 8.1: https://github.com/owncloud/core/blob/a968b8409d153257d63cc78f71139303557f4617/settings/controller/mailsettingscontroller.php#L158-L160

**Comment by vandijkstef** [comment]
Would be great if the test email contains the transport method. I can image more people just hitting all three and see which will come trough. At least I did.
