### ISSUE TITLE
csync tests fail with file locking enabled

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#16794]
https://ci.owncloud.org/job/client-test-matrix-linux-no-build/compiler=g++,label=master,mirallBranch=v1.8.1,qt=qt4,serverVersion=owncloud8.1-locking,tc=t4/49/console

````
!!! OCC::PUTFileJob created for "https://test1.owncloud.com/owncloud8.1-locking/" + "t1-20150606182231-23/test_ignored/sub/file.txt" 
void OCC::AbstractNetworkJob::slotFinished() 299 "Error downloading https://mirall-test:123456789@test1.owncloud.com/owncloud8.1-locking/remote.php/webdav/t1-20150606182231-23/test_ignored/sub/file.txt - server replied: Locked" 
void OCC::PropagateUploadFileQNAM::slotPutFinished()  QUrl( "https://mirall-test:123456789@test1.owncloud.com/owncloud8.1-locking/remote.php/webdav/t1-20150606182231-23/test_ignored/sub/file.txt" )  FINISHED WITH STATUS 299 "Error downloading https://mirall-test:123456789@test1.owncloud.com/owncloud8.1-locking/remote.php/webdav/t1-20150606182231-23/test_ignored/sub/file.txt - server replied: Locked" QVariant(int, 423) QVariant(QString, "Locked") 
"<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>OC\Connector\Sabre\Exception\FileLocked</s:exception>
  <s:message>files/31812182908e584fabc491926ff04e5c is locked</s:message>
</d:error>
" 
blacklisting  "test_ignored/sub/file.txt"  for  25 , retry count  1

**Comment by DeepDiver1975** [comment]
@PVince81 @icewind1991 @dragotin we need combined forces here - THX

**Comment by PVince81** [comment]
Yes, this is what happens when a file is locked.
So either the test isn't supposed to lock, maybe there's a stray lock.
Or the test is doing stuff in parallel and it triggers the new locking logic.

**Comment by PVince81** [comment]
@DeepDiver1975 where is the source code for those csync tests ?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 where is the source code for those csync tests ?

https://github.com/owncloud/client/tree/master/csync/tests/ownCloud

**Comment by PVince81** [comment]
I locally ran t1.pl and also t4.pl (which is the one that contains "test_ignored") and the tests passed.
Ran them several times and they worked fine.
So it's possibly a race condition of some sorts...

I also noticed with redis-cli and the `KEYS *` command that after the test run there are quite a few stray keys.
After t1.pl: 32 stray keys
After t4.pl: 19 stray keys
Leaking keys could be an explanation for the failing test on Jenkins.

I will try every possible file operation and find out which one is leaking keys.

**Comment by PVince81** [comment]
Here is a list of file operations and how many keys are left in redis after doing them:
(keys are cleared with the `FLUSHALL` command between runs)

#### web UI
- create file: 3
- create folder: 2
- upload file: 7
- delete file: 6
- delete folder: 4
- download file: 2
- display file list: 1 (it seems to recreate a preview over and over again for some reason ?)

#### WebDAV
- create folder: 2
- upload file: 2
- delete file: 7
- delete folder: 4
- download file: 2
- propfind: 0

For operations that use fopen(), I can understand that the keys aren't released until later due to the fclose() detection that happens only at GC time. I'm not sure why other operations like creating a folder would leak keys.

Any idea @icewind1991 ?

I'll redo a test run with t1.pl and check whether the keys auto-expire after a while.

**Comment by DeepDiver1975** [comment]
FYI: I'm using apcu on that test server as lock storage

**Comment by PVince81** [comment]
We might want to run these tests on redis on Jenkins instead, which we agreed would be the recommended approach, at least for the beginning.

I'll try with apcu later.

**Comment by DeepDiver1975** [comment]
> We might want to run these tests on redis on Jenkins instead, which we agreed would be the recommended approach, at least for the beginning.

I'm very much aware of this - the test server runs some old suse - I doubt we have redis at hand ... easily

**Comment by PVince81** [comment]
- [x] TODO: test if keys expire

t1.pl: 32 stray keys, after more than 5 minutes, the keys are still there.
If I restart Apache2, hoping to force GC, but the keys are still there.
That's bad.

- [ ] TODO: test with apcu
- [ ] TODO: unobfuscate key names (they are md5) to find out what paths are still locked

**Comment by PVince81** [comment]
Is the APCu cache cleared between test runs ? 
I suppose that Jenkins is running all the t*.pl tests in order ?
Maybe one of the previous tests is leaving something locked.

- [ ] TODO: run all t*.pl tests in order with redis
- [ ] TODO: run all t*.pl tests in order with APCu

**Comment by DeepDiver1975** [comment]
> I suppose that Jenkins is running all the t*.pl tests in order ?

No - pure random execution - can even be selective (what I do in case of one test failing)

**Comment by PVince81** [comment]
Ok, then it is unlikely that I'll be able to reproduce it consistently.
Is it: one Jenkins job == one script run or one Jenkins job runs several scripts, picked randomly ?

My theory still holds that the failure is due to stray locks between tests.

**Comment by PVince81** [comment]
Ideal would be finding out which script order was used during that failed run.

But it is very likely that the APCu cache is already polluted with locks from previous Jenkins runs.

**Comment by DeepDiver1975** [comment]
> Ok, then it is unlikely that I'll be able to reproduce it consistently.
> Is it: one Jenkins job == one script run or one Jenkins job runs several scripts, picked randomly ?
> 
> My theory still holds that the failure is due to stray locks between tests.

It's one job which executed t1-8.pl against two instances - the order of execution is not predictable (which should not matter either). The instances involved live on one remote server which is up and running for months.



> But it is very likely that the APCu cache is already polluted with locks from previous Jenkins runs.

Most probably ..... clear the cache?

**Comment by PVince81** [comment]
>Most probably ..... clear the cache?

Yeah, have a try.

And let's keep this ticket to investigate the stray locks.

**Comment by icewind1991** [comment]
Note that the locking code doesn't cleanup the keys when unlocking (afaik there is no atomic compare-and-delete) thus keys being left in redis after executing is expected as long as all the values are `0`

**Comment by PVince81** [comment]
@icewind1991 okay I can check that. But does it mean that redis will always be full of old keys ? Or will redis auto-clean itself after a certain period of time ?

**Comment by icewind1991** [comment]
No idea

**Comment by PVince81** [comment]
- [ ] TODO: find out whether redis auto-cleans out keys (this is important, else we'd just be polluting redis stores)
- [ ] TODO: check which of the stray keys are non-zero

**Comment by PVince81** [comment]
@icewind1991 it looks like redis doesn't support cas either and we have a workaround: https://github.com/owncloud/core/blob/master/lib/private/memcache/castrait.php#L42

Why not do the same for compare and deletion ?

Also it seems that Redis would support transactions: http://redis.io/topics/transactions

**Comment by icewind1991** [comment]
I'll look into it

**Comment by PVince81** [comment]
Ran all the csync tests locally in order, with APCu and redis. They all passed.
After that I dumped the redis DB and can confirm that all keys were set to "0" as @icewind1991 said.

**Comment by PVince81** [comment]
@DeepDiver1975 if APCu isn't cleant up and the tests are running since the PR existed and evolved over several commits, maybe there's a key that got stuck at that moment due to broken/old code ?

**Comment by icewind1991** [comment]
#16800 for cleaning up keys

**Comment by PVince81** [comment]
@icewind1991 thanks

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 if APCu isn't cleant up and the tests are running since the PR existed and evolved over several commits, maybe there's a key that got stuck at that moment due to broken/old code ?

let me kill the instance and install from scratch - this will generate a new instance id and result in a clean apc cache .....

.... wait - what is the TTL for our locks?

**Comment by PVince81** [comment]
I don't remember seeing any TTL logic in the locking providers. @icewind1991 ?
Might need to call "setTimeout()" on the keys every time we touch them to refresh the timeout.

**Comment by DeepDiver1975** [comment]
hmmm . didn't we initially talk about a TTL? Locks cannot stay forever

**Comment by PVince81** [comment]
Yes, still an open todo it seems: https://github.com/owncloud/core/issues/11804#issuecomment-96986765

**Comment by PVince81** [comment]
@icewind1991 can you add the TTL ? I saw in the redis API that it should be possible to set a timeout on lock keys. Let's keep this ticket open for that.

**Comment by icewind1991** [comment]
What do we want to do with the other memcache backends? from what I can tell not all of them have the ability to set the ttl separately and most of them don't handle ttl the way we want with inc/dec

**Comment by PVince81** [comment]
Hmmm, it means that for other backends we would need to implement the timeout logic ourselves. One possibility would be to add the lock time inside the value.

And then for every lock operation, we'd need to check the time first... and potentially lose atomicity.

**Comment by DeepDiver1975** [comment]
all green now -> close - THX

**Comment by PVince81** [comment]
Raised https://github.com/owncloud/core/issues/16966 for the TTL discussion (please schedule accordingly)
