### ISSUE TITLE
Update disables apps

### ISSUE THREAD

**Issue by dwt** [owncloud/core#16806]
We just gut an automatic update (via rpm on CentOS) for our OwnCloud instance - and lo and behold after the update the calendar module was disabled and needed manual enabling.

This should not happen. Modules should only be disabled if there is a compatibility problem - never by default during an update.

**Comment by rbu** [comment]
I had the same thing happen before and with the most recent update it happened again:

```
owncloud-server: Upgrade starting
owncloud-server}: occ maintenance:mode --on
Maintenance mode enabled
owncloud-server Upgrade complete
Maintenance mode disabled
owncloud-server}: occ upgrade
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Disabled 3rd-party app: calendar
Turned off maintenance mode
Update successful
Maintenance mode disabled
owncloud update: Checking for running Apache
Redirecting to /bin/systemctl status  httpd.service
Redirecting to /bin/systemctl stop  httpd.service
owncloud pre-install: Stopping Apache
owncloud-config-apache: Upgrade complete
owncloud-config-apache: Restarting
Redirecting to /bin/systemctl start  httpd.service
```

**Comment by RealRancor** [comment]
Hi,

this is the current (wanted) behaviour. All non-core apps like calendar and contacts are disabled during an update. See this existing issue for the whole story: https://github.com/owncloud/core/issues/14754

**Comment by RealRancor** [comment]
Btw. probably just can be closed as a dup of the second linked issue.

**Comment by rbu** [comment]
@RealRancor, thank you for finding the original bug.

The packages are advertised on the web site as "for auto updates".
![auto-update](https://cloud.githubusercontent.com/assets/65913/8054716/ebb3f6e8-0e9a-11e5-887e-b985d16b21b5.png)

Clearly, there seems to be a misunderstanding about the intention of the packages because according to #14754, the packages are not intended for unattended upgrades without manual testing.

**Comment by RealRancor** [comment]
@rbu 
Seems you're currently mixing **Updates** with **Upgrades**.

**Comment by PVince81** [comment]
Closing, please follow up in https://github.com/owncloud/core/issues/14754
