### ISSUE TITLE
Sync problem

### ISSUE THREAD

**Issue by normanfeltz** [owncloud/core#16808]
Hello,

I have a error after edit my folde in ownCloud :
![ownCloud Error](https://d1ro8r1rbfn3jf.cloudfront.net/ms_72730/2auIcQxPjo6ATUxvuDYUC1jTxFqA78/08-06-2015%2B19.54.43.png?Expires=1433872669&Signature=OJfkkDG8gJPHW~VJYskpM7UqZwQR5wmq0JtPXHL7A30BhBIlEbHZF8DxIoK27J1AhnssyPYfmHFRdi0PUJirAeYudwaSEGiJz-8N3rjoW976NQ-~DyXZN9dBlHHg7LFUA8e~Irqd2WhDaTzpkhHYXXKx6uCYeriV3ynSLLfFhqcP8Vl~5w7DCgj8CmxLaQRj-uFm2J4wz~M-e7jKeNIORQOtBYzuHxDKt7xRfX8K3axdEQhVPLGYo~r-ck7Rl8crgZwrjzNDEHK8uoRWs6iFRRHLzgc1Lgyp7e6ngywjMPx7RAEWiYMQ2JYmU7ZKDKFsAQU4GPozBucVJdf9CWFgRA__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

Cordialy

Norman FELTZ

**Comment by DeepDiver1975** [comment]
Thanks a lot for reporting issues back to us!

We need some more information to properly support you with your issue!

Can I ask you to follow our guidelines for submitting bugs as described here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

Thanks a lot!
