### ISSUE TITLE
Problem: user_ldap with user filter group in group not working

### ISSUE THREAD

**Issue by pierrejochem** [owncloud/core#16805]
Hello,

we are using a multidomain environment and in that cased I found a possible bug. If you use a group filter where you define a specific group and in this group is another group (via inheritance) where the users are located then the result is 0 what is incorrect. Is that a bug or a feature? :cry: 

Cheers,

Pierre

**Comment by MorrisJobke** [comment]
cc @blizzz

**Comment by blizzz** [comment]
Did you check "Nested Groups" in LDAP Advanced Settings → Directory Settings?

**Comment by pierrejochem** [comment]
I will try it tomorrow and will give feedback, but as far as I read the setting it could be the solution.

**Comment by blizzz** [comment]
any update @pierrejochem ?

**Comment by pierrejochem** [comment]
Will try it today after lunch. So will update it in a few hours. Sorry for the delay :-(

**Comment by pierrejochem** [comment]
It is working. Thank you for your support :smile:

**Comment by blizzz** [comment]
Great, you're welcome! :)
