### ISSUE TITLE
6.0.4 to 7.0.5 upgrade with Oracle as backend database

### ISSUE THREAD

**Issue by bboule** [owncloud/core#16812]
Summary of issue / actual behavior:

Getting "not null" constraint violation when performing upgrade (Oracle) for both the Files_Trashbin and activity applications.  Sample error message for Files_trashbin:

An exception occurred while executing 'ALTER TABLE "oc_files_trash" ADD ("auto_id" NUMBER(10) NOT NULL)': ORA-01758: table must be empty to add mandatory (NOT NULL) column

Sample errors for activity app:

An exception occurred while executing 'ALTER TABLE "oc_activity" MODIFY ("activity_id" NUMBER(10) DEFAULT NULL, "affecteduser" VARCHAR2(64) DEFAULT NULL, "type" VARCHAR2(255) DEFAULT NULL, "user" VARCHAR2(64) DEFAULT NULL)': ORA-01439: column to be modified must be empty to change datatype

***** NOTE THIS IS AFTER I HAVE GENERATED THE SCRIPTS, RUN THEM, PERFROMED THE UPGRADE AND ATTEMPTED TO RE-ENABLE THESE APPS****

Actual behavior

It's should be upgrade oC without this issue

Step to reproduce:

Disable the files_trash and activity applications
run the occ command to generate the database upgrade scripts
place the oc instance in maintenance mode
Run the database upgrade scripts (they run successfully)
process the OC upgrade via the occ command which completes
System is now upgraded

Can login etc.

Attempt to re-enable the Trash Bin application, upgrade screen renders and when you try to update the above error messages displays (until the app is disabled).

Same issue with Activity app

Server configuration

Red Hat Enterprise Linux Server release 6.6 (Santiago)
httpd-2.2.15-39.el6.x86_64
php-common-5.3.3-40.el6_6.x86_64
owncloud-enterprise-7.0.5-3.1.noarch
storage is a cifs mount from a Windows 2012R2

**Comment by MorrisJobke** [comment]
according to @DeepDiver1975 this needs a handcrafted script to migrate a oracle instance. Or should we build in some tricks to migrate these specific cases for oracle DB within the core?

**Comment by bboule** [comment]
OK that works where does one get such hand crafted scripts?  Or just some tips on what I need to add to the occ generated scripts!!  Either way will work for me!! 

Thanks for the help on this :) 

BB

**Comment by MorrisJobke** [comment]
> 'ALTER TABLE "oc_files_trash" ADD ("auto_id" NUMBER(10) NOT NULL)': ORA-01758: table must be empty to add mandatory (NOT NULL) column

Not easy solvable. Needs GCX engineer to do this.

cc @craigpg

**Comment by MorrisJobke** [comment]
Detailed steps are described multiple times: https://github.com/owncloud/apps/issues/2072#issuecomment-106036064 https://github.com/owncloud/apps/issues/2072#issuecomment-106474220

**Comment by MorrisJobke** [comment]
@bboule SFDC: 00003194 ;)

**Comment by bboule** [comment]
Yes  these steps do not work!!  I did them and it resulted in me not being able to re-enable the trash bin or activity so this is where I am confused this does not work!!!

**Comment by MorrisJobke** [comment]
> they can upgrade but re-enabling these apps continues to fail post upgrade.

But it seems like during the activation a schema update is done. This schema update needs to be done by hand on oracle. Or am I wrong @DeepDiver1975 ?

**Comment by DeepDiver1975** [comment]
> This schema update needs to be done by hand on oracle. Or am I wrong @DeepDiver1975 ?

yes - unfortunately our automated schema migration fails in cases like this on oracle.

just another case where why it seems reasonable to move to #14851

**Comment by bboule** [comment]
Hey Guys,

Thanks for the update this makes sense.  I still need some help!!  I have a user trying to upgrade and is stuck.  Do you guys happen to have scripts that will make the needed DB modifications that would not violate the constraints thrown in the error messages?

**Comment by DeepDiver1975** [comment]
> An exception occurred while executing 'ALTER TABLE "oc_files_trash" ADD ("auto_id" NUMBER(10) NOT NULL)': ORA-01758: table must be empty to add mandatory (NOT NULL) column

@bboule this one is pretty easy:
1. a new table has to be created following the new schema
2. data copied over from the old table to the new table
3. drop the old table
4. rename the new table to the old tables name

We can create a script for this case - this will happen in the dev schedule for 7.0.7

**Comment by DeepDiver1975** [comment]
> An exception occurred while executing 'ALTER TABLE "oc_activity" MODIFY ("activity_id" NUMBER(10) DEFAULT NULL, "affecteduser" VARCHAR2(64) DEFAULT NULL, "type" VARCHAR2(255) DEFAULT NULL, "user" VARCHAR2(64) DEFAULT NULL)': ORA-01439: column to be modified must be empty to change datatype

I did not yet see this one - we need to have a closer look. But most probably the same mechanism should be applied as above

**Comment by DeepDiver1975** [comment]
@VicDeo some more sql fun? :speak_no_evil: can you please have a look? thx

**Comment by cmonteroluque** [comment]
@bboule can you make sure @VicDeo has access to the Oracle set up please?

**Comment by VicDeo** [comment]
Arrrggghhh. 
I like it, thank you :santa:

**Comment by bboule** [comment]
Sure will send the needed tnsnames.ora and will create the needed tablespace on the DB  working on that now

**Comment by VicDeo** [comment]
er... I wonder whether it is possible to install OC6 on Oracle....

```
An exception occurred while executing &#039;CREATE TRIGGER &quot;contacts_cards_properties_AI_PK&quot;
   BEFORE INSERT
   ON &quot;contacts_cards_properties&quot;
   FOR EACH ROW
DECLARE
   last_Sequence NUMBER;
   last_InsertID NUMBER;
BEGIN
   SELECT &quot;contacts_cards_properties_SEQ&quot;.NEXTVAL INTO :NEW.&quot;id&quot; FROM DUAL;
   IF (:NEW.&quot;id&quot; IS NULL OR :NEW.&quot;id&quot; = 0) THEN
      SELECT &quot;contacts_cards_properties_SEQ&quot;.NEXTVAL INTO :NEW.&quot;id&quot; FROM DUAL;
   ELSE
      SELECT NVL(Last_Number, 0) INTO last_Sequence
        FROM User_Sequences
       WHERE Sequence_Name = &#039;contacts_cards_properties_SEQ&#039;;
      SELECT :NEW.&quot;id&quot; INTO last_InsertID FROM DUAL;
      WHILE (last_InsertID &gt; last_Sequence) LOOP
         SELECT &quot;contacts_cards_properties_SEQ&quot;.NEXTVAL INTO last_Sequence FROM DUAL;
      END LOOP;
   END IF;
END;&#039;:

ORA-00972: identifier is too long
```

**Comment by LukasReschke** [comment]
@VicDeo Only checkout core, calendar and Co. are completely unsupported and will go :boom:

**Comment by VicDeo** [comment]
I see no straightforward solution. Migration SQL is generated by Doctrine.
https://github.com/owncloud/core/blob/master/lib/private/app.php#L1162
https://github.com/owncloud/core/blob/master/lib/private/db/mdb2schemamanager.php#L121
https://github.com/owncloud/core/blob/master/lib/private/db/migrator.php#L217

**Comment by DeepDiver1975** [comment]
@VicDeo thanks for looking into this - I have to apologize because I might not have share all necessary information with you.

You are absolutely true: our schema migration mechanism totally fails on Oracle under certain conditions. What we need to come up with is a set of sql script which have to be applies manually to the dbs right before upgrade.

So the task would be to write these scripts.

Thanks a lot!

**Comment by VicDeo** [comment]
@DeepDiver1975 something like this: https://gist.github.com/VicDeo/559d03813adf371acada ?

**Comment by DeepDiver1975** [comment]
Nice! I was expecting a plain sqlscript. If we can make it work this way :+100:

**Comment by VicDeo** [comment]
@bboule Can you do the following:
- create a backup of the tables `oc_activity` and `oc_files_trash`
- put preupdate.php for both apps to the respective locations   
    [apps/activity/appinfo/preupdate.php](https://gist.github.com/VicDeo/559d03813adf371acada)  
    [apps/files_trashbin/appinfo/preupdate.php](https://gist.github.com/VicDeo/c715632e7cd5e915e0a1)
- try to enable the apps again

**Comment by bboule** [comment]
Roger that... I will give it a shot and report back...

**Comment by bboule** [comment]
@VicDeo @DeepDiver1975 @cmonteroluque  I can confirm that this works... I needed to do them one at a time (just a statement not suggesting anything wrong) but I was able to upgrade from 6.0.4 to 7.0.5 by:

Turning off activity and Trash bin in 6
Copying over config file and data
Generating DB Scripts with OCC commands
apply script to the database
Process the upgrade using occ command
apply pre-update file to activity
turn activity on
login and process update to activity
apply pre-update to trash bin 
login and prices upgrade to this app

Upgrade worked as expected!!

**Comment by VicDeo** [comment]
Activity: https://github.com/owncloud/activity/issues/308
Files_trashbin: https://github.com/owncloud/core/issues/17111

**Comment by MorrisJobke** [comment]
> Files_trashbin: #17111

But this is against master? Isn't this targeted for stable7?

**Comment by DeepDiver1975** [comment]
> But this is against master? Isn't this targeted for stable7?

we need to apply this change to all branches stable7, stable8 and master

**Comment by MorrisJobke** [comment]
> we need to apply this change to all branches stable7, stable8 and master

But it is useless, because in stable7 was already the upgrade to 0.6.1 of trashbin. So all stable7 instances are already on the new version of the trashbin table and upgrades from pre-stable7 to stable8/master aren't allowed.

https://github.com/owncloud/core/commit/fe8bae31dc80ac832323fa8d9a75fd4b543d36e0#diff-99fb6f2952c88f5b03417805c730c1b7R1

**Comment by DeepDiver1975** [comment]
> But it is useless, because in stable7 was already the upgrade to 0.6.1 of trashbin included. So all stable7 instances are already on the new version of the trashbin table and upgrades from pre-stable7 to stable8/master aren't allowed.
> 
> fe8bae3#diff-99fb6f2952c88f5b03417805c730c1b7R1

let me wrap my brain around this ....

**Comment by DeepDiver1975** [comment]
I guess you are right @MorrisJobke 

@VicDeo we need the pull requests only against stable7 - THX

**Comment by VicDeo** [comment]
@MorrisJobke @DeepDiver1975  I admit that we don't support skipping major releases while upgrading the core. 
 But it might happen that a OC6 user 
- disables files_trashbin
- migrates to OC7
- migrates to OC8
- enables files_trashbin 
- :boom: 

The proposed preupdate.php is executed _before_  increasing an app version and patches the existing schema.

**Comment by cmonteroluque** [comment]
@VicDeo I think we're just pending on the stable7 PR for this one

**Comment by cmonteroluque** [comment]
@DeepDiver1975 ready to merge?
