### ISSUE TITLE
Use GnuPG to encrypt mails send by ownCloud

### ISSUE THREAD

**Issue by schiessle** [owncloud/core#16813]
Mails send by ownCloud can contain sensitive informations and if someone can intercept a password reset mail a complete account can be hijacked.

Therefore it would be nice if each user could upload his PGP public key to ownCloud. The key could be used to encrypt mails send to the user (activities, password reset mails and other notifications).

cc @LukasReschke what do you think?

**Comment by oparoz** [comment]
Just like Facebook :). That would be a nice touch.

**Comment by schiesbn** [comment]
@oparoz indeed. I had this already in mind for quite some time but the facebook announcement reminded me that either I need to implement it by myself or at least create a feature request to make it happen :smile:

**Comment by oparoz** [comment]
The only problem I see is regarding the dependency it introduces.

**Comment by schiesbn** [comment]
Yes, but it doesn't need to be a hard dependency. Just check if GnuPG is available, if yes we provide the option if not we hide it... Just saw that there is even a nice PHP library https://php.net/manual/en/book.gnupg.php

**Comment by oparoz** [comment]
Dead easy to use too

```
<?php
$gpg = new gnupg();
$gpg -> addencryptkey("8660281B6051D071D94B5B230549F9DC851566DC");
$enc = $gpg -> encrypt("just a test");
echo $enc;
?>
```

and the key generation part could be added in a 2nd step. Interested parties probably already have keys or we would advise beginners to use something like the whiteout.io browser extension.

**Comment by DeepDiver1975** [comment]
We need to give the user the ability to upload their public key via the personal settings page.

I see no need in adding key generation - the users have to generate their keys on the machine where their mail client is running (local in shell or within the mail client or even in whiteout.io browser extension)

**Comment by DeepDiver1975** [comment]
where shall we store the key?
data/${user}/gpg ???

Would be great to have some kind of structure in there as I can see multiple keys for various purpose being added. Especially in conjunction with the mail app where a user might even wants to store his private key for decrypting

**Comment by DeepDiver1975** [comment]
@schiesbn or can we use the key manager for this purpose?

**Comment by oparoz** [comment]
You don't need to worry about key management. The PECL extension communicates with gpgme and the keys are then available to all apps invoking gnupg.

**Comment by schiesbn** [comment]
> and the key generation part could be added in a 2nd step. Interested parties probably already have keys or we would advise beginners to use something like the whiteout.io browser extension.

I don't think we need to generate any keys. If the user wants to get encrypted notifications from ownCloud we can assume that he already has a GnuPG key generated and integrated in his mail client, otherwise he can't read the encrypted mails. So I would just provide a option to upload the key.

I didn't looked into the library in detail yet. But if the uploaded public keys would be added directly to a gpg keyring, then it would be super easy and we wouldn't need to care about anything.

>  Especially in conjunction with the mail app where a user might even wants to store his private key for decrypting

Not sure if we want to encourage users to upload their private key to a server. It should be possible to use your local private key with some JavaScript magic, afaik Posteo does something similiar to enable gpg for their web interfaced.

**Comment by DeepDiver1975** [comment]
> Not sure if we want to encourage users to upload their private key to a server. It should be possible to use your local private key with some JavaScript magic, afaik Posteo does something similiar to enable gpg for their web interfaced.

I'm more revering to the scenario where a user trusts his server and wants to use the owncloud mail app to read encrypted mails.

**Comment by oparoz** [comment]
Minor issue: home users can't install the PECL extension on OSX

**Comment by oparoz** [comment]
Regarding a possible use in the mail app, apparently you can forget about letting users decrypt mail using the extension or even the binary itself because you can't send the passphrase to gnupg.
https://php.net/manual/en/function.gnupg-decrypt.php#95911

Less of a problem when sending notifications out as we can simply store everything in a text file.

**Comment by rullzer** [comment]
Regarding this, we should then also implement the admin uploading a key (or subkey) so that the e-mails coming from owncloud can also automatically be signed.

**Comment by rullzer** [comment]
@oparoz you can set the passphrase. see [gnupg_adddecryptkey](https://secure.php.net/manual/en/function.gnupg-adddecryptkey.php)

**Comment by rullzer** [comment]
> @oparoz you can set the passphrase. see [gnupg_adddecryptkey](https://secure.php.net/manual/en/function.gnupg-adddecryptkey.php)

Ah mmm, it seems it is ignored in GNUPG V2 and a pinetry app is launched... or tried to launch...

**Comment by oparoz** [comment]
@rullzer - Yep, it's the same problem for all PHP apps. That new behaviour is more secure, but breaks things...

**Comment by PVince81** [comment]
or implement a hook that lets app intercept and modify emails before they are sent out. This would make it possible to write an app that encrypts the emails in whichever format is desired

**Comment by PVince81** [comment]
ah yes, this https://github.com/owncloud/core/issues/17425
