### ISSUE TITLE
Not working password recovery with LDAP

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#16816]
### Architecture
ownCloud version": "7.0.3.4"
PHP Version": "5.4.34"
Apache 2.2.15 (SLES Expanded Support)
LDAP activated

### Expected behavior: 
LDAP User writes a wrong password and gets a message to contact the administrator.

### Actual behavior:
LDAP USer writes a wrong password and gets a link per Email, and the token is invalid. 

How to turn off this option?

### Steps to reporduce it:
1.- Write a valid user and a wrong password,
2.- ask to reset the password.
3.- The oC Server sends an Email with link but can't reset password (token is not valid).

### Logs

Apache and ownCloud Logs and LDAP configuration in 
S3-ownCloud\Shared\owncloud\support\github-issues\core\16816

@MorrisJobke 

00002757

**Comment by RealRancor** [comment]
Hi,

some basic discussion was done here: https://github.com/owncloud/core/issues/12215

**Comment by MorrisJobke** [comment]
I moved this request over to #12215
