### ISSUE TITLE
Scrolling gets stuck on file list search result

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#16823]
### Steps to reproduce

1. Create `test{$i}.txt` files until the file list is longer then your screen.
2. Create a `foobar/test.txt`
3. Search for `test` using the search field in the top right
4. Clicking on "1 search result in other places"
5. Scroll back to test1.txt

### Expected

No problem, you scroll and you get to the top

### Actual

After clicking on "1 search result in other places" you can not scroll up to the top of the list anymore. It keeps jumping back down to the headline.
![scrollingimpossible](https://cloud.githubusercontent.com/assets/213943/8054101/3dd8b81e-0e96-11e5-9c91-955f2b3f002f.png)

---

Found this while reviewing #16810

**Comment by PVince81** [comment]
Looks like the search results container is overlapping the scrollbar ? 
@jancborchardt

**Comment by MorrisJobke** [comment]
fixed with #16810
