### ISSUE TITLE
Renaming folders in webdav interface using backslash coded doesn't return proper error.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16825]
### Steps to reproduce

1. Rename a folder using curl:
```
curl -v -X MOVE 'http://User:Password@Host/remote.php/webdav/carpeta' -H 'Destination:http://User:Password@Host/remote.php/webdav/%2F'
```
or
```
curl -v -X MOVE 'http://User:Password@Host/remote.php/webdav/carpeta' -H 'Destination:http://User:Password@Host/remote.php/webdav/%2Fhola'
```
or
```
curl -v -X MOVE 'http://User:Password@Host/remote.php/webdav/carpeta' -H "Destination:http://User:Password@Host/remote.php/webdav/hola%2Fhola"
```

### Expected behaviour
It should answer error, forbidden characters.

### Actual behaviour
In first case it returns `<s:exception>Sabre\DAV\Exception\Forbidden</s:exception>`
In second case 'carpeta' is renamed to 'hola'
In third case it return "The destination node is not found"

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
None.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No.

**Logs**
```
```

### Client configuration

curl

**Comment by PVince81** [comment]
Again ? :frowning:

**Comment by PVince81** [comment]
SabreDAV (the library we use) normalizes the URL. If there are duplicate slashes they are converted to single ones.
So case 1 is normalized to "http://User:Password@Host/remote.php/webdav/" which is an invalid targe t=> 403 forbidden
Case 2 gets normalized to "http://User:Password@Host/remote.php/webdav/hola" which is acceptable.

Case 3 gets normalized to "http://User:Password@Host/remote.php/webdav/hola/hola" so it will search for the folder "hola" which does not exist.

This works as expected.
Closing.

**Comment by SergioBertolinSG** [comment]
But this are backslashes ('\') not slashes. Doesn't matter?

**Comment by PVince81** [comment]
I used your curl examples: %2F are slashes, not backslashes.

If you meant backslashes, then feel free to reopen if you see issues.

**Comment by purigarcia** [comment]
I have issues when renaming with backslashes

it does not work doing this
curl -v -X MOVE 'http://User:Password@Host/remote.php/webdav/carpeta' -H 'Destination:http://User:Password@Host/remote.php/webdav/%5C'

or 

curl -v -X MOVE 'http://User:Password@Host/remote.php/webdav/carpeta' -H 'Destination:http://User:Password@Host/remote.php/webdav/aaa%5C'

It works
curl -v -X MOVE 'http://User:Password@Host/remote.php/webdav/carpeta' -H 'Destination:http://User:Password@Host/remote.php/webdav/%5Caaa'

I am using master
{"installed":true,"maintenance":false,"version":"8.1.0.6","versionstring":"8.1 beta 2","edition":""}

**Comment by SergioBertolinSG** [comment]
@PVince81 Yes, I confused the encoding of slashes.

@purigarcia I've tried three commands, first one returns forbidden. 
Second and third returns "File name contains at least one invalid character"

**Comment by purigarcia** [comment]
yes, you are right @SergioBertolinSG , second one its working.
I'll give another example where it is not working
curl -v -X MOVE 'http://User:Password@Host/remote.php/webdav/folder' -H 'Destination:http://User:Password@Host/remote.php/webdav/folder%5C'

**Comment by SergioBertolinSG** [comment]
Ok this one is very tricky, it leads to data loss.

It returns <s:message>File with name folder could not be located</s:message> and folder 'folder' is deleted.

**Comment by DeepDiver1975** [comment]
@icewind1991 please have a look - THX

**Comment by icewind1991** [comment]
Fix is here: https://github.com/owncloud/core/pull/16880

**Comment by PVince81** [comment]
@SergioBertolinSG please verify

**Comment by PVince81** [comment]
(just got merged into master)

**Comment by PVince81** [comment]
Issue is not fixed.

**Comment by PVince81** [comment]
New fix from @icewind1991 is here https://github.com/owncloud/core/pull/16886

**Comment by nasli** [comment]
The exception response is different for rename and other options, should be both "InvalidPath"

 curl -v -X MOVE  'http://User:Password@Host/remote.php/webdav/test' -H 'Destination:http://User:Password@Host/remote.php/webdav/%5C’
<s:exception>OCP\Files\InvalidPathException</s:exception>

curl -u User:Password http://\Host/remote.php/webdav/%5C -X MKCOL
 <s:exception>OC\Connector\Sabre\Exception\InvalidPath</s:exception>

**Comment by PVince81** [comment]
Right, the exception wasn't translated properly to a sabre exception.

**Comment by PVince81** [comment]
@nasli fix for the wrong exception type here https://github.com/owncloud/core/pull/16943

**Comment by PVince81** [comment]
This issue is back from the dead on the new DAV endpoint...
