### ISSUE TITLE
Uploading a file with now-allowed character '?' in its name through the WebDAV interface for CHUNKED UPLOADS returns 500

### ISSUE THREAD

**Issue by davivel** [owncloud/core#16828]
### Steps to reproduce
1. Create a local file called ?.pdf in the folder [known_location]
2. Run: ```curl -v -X PUT "http://[user]:[pass]@[server]/remote.php/webdav/%3F.pdf-chunking-5678-1-0" -F myfile=@"[known_location]/?.pdf" -H "OC-Chunked: OC-Chunked"```

### Expected behaviour
Return 201, file is uploaded and created in the server.

### Actual behaviour
HTTP/1.0 500 Internal Server Error

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache/2.4.7

**Database:**
MySQL

**PHP version:**
PHP/5.5.9-1ubuntu4.9

**ownCloud version:** (see ownCloud admin page)
8.1 beta 2 (daily) Build:2015-06-03T03:33:43+00:00 1cccb227c398d3c5428672aaf9cf6b14e248e5f7

**Updated from an older ownCloud or fresh install:**
Don't know

**List of activated apps:**
Files, activity, images.

**The content of config/config.php:**

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Comment by davivel** [comment]
Maybe related to #16706 ?

**Comment by DeepDiver1975** [comment]
> HTTP/1.0 500 Internal Server Error

500 always has an error in the logs - please add - THX

**Comment by davivel** [comment]
Sure:

{"reqId":"duQOtNurm\/toqbkiBfe8","remoteAddr":"XXX.XXX.XXX.XXX","app":"PHP","message":"Class 'OC\\Cache\\File' not found at \/opt\/owncloud\/lib\/private\/filechunking.php#56","level":3,"time":"2015-06-09T12:34:05+00:00","method":"PUT","url":"\/remote.php\/webdav\/la%3F.pdf-chunking-7333-1-0"}

**Comment by PVince81** [comment]
Works for me on master, please update.

The error in the log has nothing to do with question marks. Chunking was broken recently and fixed through https://github.com/owncloud/core/pull/16762

**Comment by davivel** [comment]
Will do. Thanks

**Comment by davivel** [comment]
Double checked, working like a charm. 

Sorry for the noise and thanks for your help.
