### ISSUE TITLE
Upgrade to 8.0.4 fails

### ISSUE THREAD

**Issue by joachimvda** [owncloud/core#16820]
I get the following error:
---
INDEX 1ucwmxdoddudi ON appconfig_dw9wobm5w7861 ("appid")': SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "1" LINE 1: CREATE INDEX 1ucwmxdoddudi ON appconfig_dw9wobm5w7861 ("appi... ^
---
This is an installation on postgresql.

**Comment by RealRancor** [comment]
Hi,

looks like a duplicate of: https://github.com/owncloud/core/issues/16779 where you can find a link to a possible workaround in https://github.com/owncloud/core/pull/16807

**Comment by joachimvda** [comment]
Great, that worked.
Thanks.
