### ISSUE TITLE
Acquire locks before post-hooks, release afterwards

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#16829]
@icewind1991 @DeepDiver1975 
Let the discussion about acquiring locks in the prehooks continue here.

Some arguments here: https://github.com/owncloud/core/pull/16727#issuecomment-108468512

**Comment by PVince81** [comment]
Marking as bug as this is a potential bug.
Might be possible to trigger this somehow with carefully placed "sleep()" statements.

**Comment by icewind1991** [comment]
We already lock around pre-hooks, it's post-hooks that I'm unsure off

**Comment by PVince81** [comment]
Right, post-hooks.

Would it hurt to lock there ? Any negative consequences that comes to mind ?

**Comment by icewind1991** [comment]
if we lock around post-hooks then hooks can no longer write to the file.

I'm not sure if we currently have any hooks that write to the file but we have had those in the past and I would say there are valid use cases for it

**Comment by PVince81** [comment]
Hmm ok, so it means if an app really would do something with the file in a post-hook, it would go over the view anyway and re-lock the file.

Only if someone would rename/move away the file between the operation and the post-hook, then shit could happen.

I'll try and find a concrete case with reproduction steps then.

**Comment by PVince81** [comment]
### Steps:
1. Create a folder "folder"
1. Create a file "folder/test.txt"
2. Edit "folder/test.txt" multiple times to create versions.
3. Add a "sleep(10);" in versions post rename hook before the "renameOrCopy" call: https://github.com/owncloud/core/blob/master/apps/files_versions/lib/hooks.php#L103
4. Rename "folder/test.txt" to "folder/re.txt"
5. In another window or WebDAV, rename "folder" to "re"
6. Wait for all operations to finish
7. Check the versions of "re/re.txt"

The versions are still there. The reason is because renaming the folder also triggered the version copying logic, so this might be sheer luck.

However the file rename fails with 500, logs contain this:
```
{"reqId":"E6zC8T1E4xL1Sej3uG5G","remoteAddr":"127.0.0.1","app":"PHP","message":"Argument 1 passed to OCA\\Files\\Helper::formatFileInfo() must implement interface OCP\\Files\\FileInfo, boolean given, called in \/srv\/www\/htdocs\/owncloud\/apps\/files\/lib\/app.php on line 122 and defined at \/srv\/www\/htdocs\/owncloud\/apps\/files\/lib\/helper.php#135","level":3,"time":"2015-06-12T13:44:55+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/rename.php?dir=%2Ffolder&newname=re.txt&file=test.txt"}
{"reqId":"E6zC8T1E4xL1Sej3uG5G","remoteAddr":"127.0.0.1","app":"PHP","message":"Call to a member function getMimetype() on boolean at \/srv\/www\/htdocs\/owncloud\/apps\/files\/lib\/helper.php#77","level":3,"time":"2015-06-12T13:44:55+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/rename.php?dir=%2Ffolder&newname=re.txt&file=test.txt"}
```

The concurrency case happened at the time where both tried to copy the same versions.

The expected behavior is that the folder rename is locked until the post hook is done moving the versions.

**Comment by PVince81** [comment]
Please note that post hooks are already included in the lock transaction in the code path for WebDAV PUT of small files. So if we say we still don't want to include post hooks, we'll need to change that code path to exclude them too.

But I'd prefer if we would include them. Maybe we need to call changeLock again to SHARED.

**Comment by icewind1991** [comment]
Ok, I'll make a PR with shared locks around post-hooks so we can properly observe the impact

**Comment by PVince81** [comment]
In theory we can already observe them with Webdav PUT of small files :wink: 

Yes, please do. Thanks.

**Comment by PVince81** [comment]
You'll need to call `changeLock()` to convert the locks from EXCLUSIVE back to SHARED.
Had to do it for https://github.com/owncloud/core/issues/16900

**Comment by PVince81** [comment]
Ok I think I now see your point about "apps cannot modify the file in post hooks".
On the other hand, apps that want to modify the real file in pre or post hooks should then be ported to use storage wrappers instead.

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/17030
