### ISSUE TITLE
Debounce expiration background jobs

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#16826]
My concern is as follows:
1) Let's say a file is often updated, saved 10 times within a cron run (say 15 minutes), especially for the people who hit "save" multiple times in a row
2) The versions app will schedule 10 expiration jobs instead of one
3) Once the cron run arrives, it will run the expiration logic 10 times instead of just once.

The same applies with deleting files to trash: when deleting multiple times, it will create one expiration background job per file (unless maybe they were batch-deleted). So the trashbin expiration logic will be run several times in a row during the next cron run.

I'm not sure if that really scales well.
This means that on systems with lots of active users, cron will be very busy and could take a long time to run all those unneeded cycles for every user.

We should find a way to debounce such jobs. Maybe check if a similar job already exists in the database and just refresh it.

@DeepDiver1975 @icewind1991 @schiesbn @karlitschek @cmonteroluque 

also CC @jnfrmarks for testing cron performance/timings

**Comment by DeepDiver1975** [comment]
> This means that on systems with lots of active users, cron will be very busy and could take a long time to run all those unneeded cycles for every user.

For bigger installations cron is a suboptimal solution - that's why we need to integrate MQ systems.

@MTRichards @cmonteroluque we need to reserver some time within 8.2 (worst case 8.3) to integrate at least one MQ system (maybe we start with http://www.iron.io/ as this can be used by community users and smaller installations as well ????)

**Comment by DeepDiver1975** [comment]
> within a cron run (say 15 minutes)

we shall adjust the cron period in the docs and let it execute once per minute.

in addition it might be reasonable to start adding a occ command which executed scheduled jobs right away - as in build a worker process

**Comment by PVince81** [comment]
If one run takes more than a minute it would just stay locked, right ?

**Comment by DeepDiver1975** [comment]
> If one run takes more than a minute it would just stay locked, right ?
> @PVince81

cron has already a mechanism in place to prevent parallel execution.

**Comment by karlitschek** [comment]
A MQ system always has to be optional. This means we have to work properly without it too. If the described behavior is a real problem (not are yet) then we could modify out background system so that old waiting jobs can be replaced/removed with new ones.

**Comment by PVince81** [comment]
If some load testing can be done for this then we'll find out.

So far smashbox doesn't trigger cron, so maybe it should be extended to do so.

**Comment by DeepDiver1975** [comment]
> A MQ system always has to be optional. This means we have to work properly without it too.

never said anything different - but there is a point in time where an MQ system will push the overall system reaction time and reliability. And there will be a system size where we will encourage installations to rely on an MQ system.

**Comment by DeepDiver1975** [comment]
> So far smashbox doesn't trigger cron, so maybe it should be extended to do so.

indeed

**Comment by karlitschek** [comment]
@DeepDiver1975 I know :-)

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 I know :-)

:beers:

**Comment by PVince81** [comment]
@DeepDiver1975 you guys mentioned Laravel at some point. Is that system/library able to interchangeably switch between a cron system and MQ ? Or does it mean we need to implement both approaches ourselves ? (more code paths to maintain instead of having that done by the lib)

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 you guys mentioned Laravel at some point. Is that system/library able to interchangeably switch between a cron system and MQ

the switch is in the queue implementation - either database (which is what we basically have today) or an MQ system (which is what we will need to implement on day)

In laravel there are always (with one exception) dedicated executor processes to be started somewhere which read tasks from the queue. As of today our executor is the cron system.

The exception in laravel executor is the so called push-queue which is basically a web url which is triggered with the payload of the job. As explicit implementation iron.io is used in the laravel system.

Based on all that we have to split cron jobs (recurring jobs) and job on the job queue (jobs with specific payload).

**Comment by PVince81** [comment]
@DeepDiver1975 move to 9.0 ? Or should we find a quick workaround for 8.2 ?

**Comment by cmonteroluque** [comment]
@PVince81 @MTRichards @DeepDiver1975 as requested in https://github.com/owncloud/core/issues/16826#issuecomment-110320978 we should try and reserve time in 9.0 (8.3).

**Comment by PVince81** [comment]
Ticket about expire jobs piling up: https://github.com/owncloud/core/issues/20425

**Comment by MorrisJobke** [comment]
> A MQ system always has to be optional. This means we have to work properly without it too. If the described behavior is a real problem (not are yet) then we could modify out background system so that old waiting jobs can be replaced/removed with new ones.

@karlitschek Just to bring you up to date: https://github.com/owncloud/core/issues/20425#issuecomment-160076048 - it's a bigger instance but it is still a problem and they will run into limits (sooner than later)

**Comment by rullzer** [comment]
@PVince81  @MorrisJobke  I guess this is fixed now right? With the identical expire/trash jobs now merged?

**Comment by PVince81** [comment]
Yes. @MorrisJobke found out that there is already a system that debounces bkg jobs, given that their parameters are exactly the same.

**Comment by MorrisJobke** [comment]
versions https://github.com/owncloud/core/pull/21109 and  trashbin https://github.com/owncloud/core/pull/20790

Both are available in 8.1.5, 8.2.2 and 9.0.0.
