### ISSUE TITLE
Apps search: No feedback when there is no search result

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#16836]
Search in the apps management and type in »test« or some other term which does not give any result.

Instead of just leaving it blank, we should show a nice `.emptycontent` message is shown with an icon-search and a »No apps found for <searchterm>«.

@icewind1991 or someone from @owncloud/designers maybe? Using .emptycontent just like in the files app should work.

**Comment by MorrisJobke** [comment]
Also results are not shown.

**Comment by MorrisJobke** [comment]
@DeepDiver1975 Do you also experience this? I simply have an empty screen, but the response lists a result:
![bildschirmfoto von 2015-06-09 17-26-35](https://cloud.githubusercontent.com/assets/245432/8061776/cd1e43dc-0ecc-11e5-9234-c4e195bd85ff.png)

**Comment by MorrisJobke** [comment]
Oh. I was talking about the search in files. And it behaves similiar. @jancborchardt Sorry for abusing your issue, but it seems to be for the same reason.

**Comment by MorrisJobke** [comment]
sorry ... misread this issue. I created a new one: #16842

**Comment by jancborchardt** [comment]
Hello @icewind1991?
