### ISSUE TITLE
Add missing button to clear search terms in the search field

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#16838]
It's common to have a little cross at the end of the search field to be able to clear the current search without having to delete everything first. ownCloud should have it.
@jancborchardt

**Comment by jancborchardt** [comment]
Yeah – proper browsers like Chrome add it automatically. This has been requested in the past and probably it’s good to introduce a shim to help other browsers along.

cc @owncloud/designers

**Comment by PVince81** [comment]
Is there any supported browser left that doesn't automatically provide this button ?

**Comment by stefan-niedermann** [comment]
current firefox does not
