### ISSUE TITLE
Move legacy / deprecated APIs into a separate app

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#16849]
Idea:

Instead of keeping the deprecated classes, Javascript, APIs in core, how about moving them to a separate app called "compatibility" or "legacy" ?
The app's purpose would mostly be to keep ownCloud compatible with older apps that were not ported to the new APIs. It has the advantage of not cluttering the main project with older classes.
For many APIs, it would be a wrapper/adapter that provides classes and endpoints that internally call the new APIs, but still show the proper facade as expected by older apps.

This came to mind when talking with @schiesbn about the share dropdown which might be used by some apps, but is likely to get ported/rewritten differently (for the right hand sidebar #16308), so it wouldn't be compatible with older apps. Yet if we still want older apps to work, we'd need to keep "OC.Share" in core forever (and have it loaded at all times!). With the idea of a "legacy" app, we could move that JS code there.

For people who are using older apps, they could be advised to enable the "legacy" app to make them work. Or the app could auto-enable as soon as someone is enabling an app with maxversion < currentversion (or something along these lines).

If we say we need to support public APIs forever, then at least the old ones would all be gathered in one place while the new ones can be cleanly implemented in core and have less code clutter.

The autoloader could also be optimized: eventually we'd like to have all namespaces work properly with PSR-whatever. So we could just do that in core, also with the public API classes. And only the "legacy" app would have its own special custom autoloader to support the older non-compatible namespaces for older public APIs.

The app could either be hosted in another repo, or simply be in the core repo but under "apps/legacyapi" (with its respective tests, if applicable).

What do you think ?

@oparoz @DeepDiver1975 @LukasReschke @Raydiation @schiesbn @icewind1991 @MorrisJobke @nickvergessen

**Comment by oparoz** [comment]
I think it's a great idea, but I think you would need to keep it enabled at all times at the beginning as I can see core apps still relying on old APIs simply because they're waiting for a large change to take place before being able to move away from those APIs.

**Comment by PVince81** [comment]
It is fine to keep it enabled at first, and then we can see how it evolves.
If most apps moved to the new APIs, it could be disabled.
If too many apps are still lacking behind, we can keep it enabled.

But at least the main code would be clean, and the legacy stuff is all in one place instead of intermixed.

**Comment by karlitschek** [comment]
Hmm. This smells like a way to move the "old" stuff out of the sight of the developers. If we really care about stability than it has to be supported and fixed and tested and maintained and documented and so on. I don't see a benefit of moving it away.

**Comment by oparoz** [comment]
The doc stays, tests move, the real APIs are still maintained, but wrappers are moved away so that the core tree stays clean without 2-3 files doing the same thing, just using different names. At least, that's how I understand it.
