### ISSUE TITLE
No search results are shown in files app

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#16842]
Search for a file, that is in the subfolder.

### Actual

* white screen

### Expected

* list the result

@DeepDiver1975 Do you also experience this? I simply have an empty screen, but the response lists a result:
![bildschirmfoto von 2015-06-09 17-26-35](https://cloud.githubusercontent.com/assets/245432/8061776/cd1e43dc-0ecc-11e5-9234-c4e195bd85ff.png)

**Comment by MorrisJobke** [comment]
@jancborchardt Do you also experience this?

**Comment by DeepDiver1975** [comment]
Will test later ....

**Comment by DeepDiver1975** [comment]
works for me ....

**Comment by jancborchardt** [comment]
Also works fine for me. Closing?
