### ISSUE TITLE
Get " Encryption not ready" error running test_sharefile.py test when external storage is configured

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#16847]
### Steps to reproduce

1. Install 8.1 with encryption, files_locking, and external storage
2. As the admin user, create a global external storage on amazon s3 for all users
2. Run smashbox test test_shareFile.py

### Expected behaviour

Test passes with no errors in the server log

### Actual behaviour

I see the following errors in the server log:

```

{"reqId":"6Ce7L31B\/9w5zbZVQQby","remoteAddr":"172.18.5.144","app":"webdav","message":"Exce
ption: {\"Message\":\"HTTP\\\/1.1 503 Encryption not ready: multikeydecrypt with share key
failed:error:0407106B:rsa routines:RSA_padding_check_PKCS1_type_2:block type is not 02\",\"
Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/l
ib\\\/DAV\\\/CorePlugin.php(82): OC\\\\Connector\\\\Sabre\\\\File->get()\\n#1 [internal fun
ction]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\
\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event
\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/w
ww\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\
\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud
\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invo
keMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\
\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\S
erver->exec()\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(84): require_once('\\\/
var\\\/www\\\/html\\\/o...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\
/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":263}","level":4,"time":"2015-0
6-09T16:29:35+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/amazon-s3\/TEST_
FILE_USER_RESHARE.dat"}

```

and there is a conflict file in the local directory where the sync is happening.  I believe that the error is occurring when the file is being modified by the sharee user.

### Server 1 Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration:

ownCloud Enterprise Edition 8.1 beta 2 (daily) Build:2015-06-08T03:08:20+00:00 35421487610462b12e3600954f23a777c54abee3

### Client configuration:

owncloudcmd veresion 1.8.2

**Comment by nickvergessen** [comment]
I don't have S3 to test again, so I used an SFTP mount, but that worked like charm.
Can you please specify the name of the mount point you used (maybe it conflicted somehow with something).

**Comment by nickvergessen** [comment]
@jnfrmarks can you please provide us with the necessary information?

**Comment by jnfrmarks** [comment]
I used an amazon s3 mount point, named amazon-s3.

**Comment by jnfrmarks** [comment]
@nickvergessen 

Let me know if you need any more info.

**Comment by nickvergessen** [comment]
@jnfrmarks credentials for testing would be nice. but dont share them here

**Comment by jnfrmarks** [comment]
@nickvergessen ping me via irc or skype and I will share ;)

**Comment by MorrisJobke** [comment]
@nickvergessen @jnfrmarks Pong :P

**Comment by jnfrmarks** [comment]
I sent the amazon creds to @nickvergessen

**Comment by nickvergessen** [comment]
Closing, feel free to reopen, when you can reproduce it again.
