### ISSUE TITLE
Use a custom layout ?

### ISSUE THREAD

**Issue by lparmentier-quatral** [owncloud/core#16845]
Hi everybody, 

I'm stuck with the code in core. Cause we can't use a custom layout ? Could we add this ehnancement ?

It's useful to add an email layout, or a login layout.

**Comment by RealRancor** [comment]
Hi,

Theming for having a custom layout is available since a longer time:

https://doc.owncloud.org/server/8.0/admin_manual/operations/theming.html

Unfortunately its not complete so also have a look at: https://github.com/owncloud/documentation/issues/1060

**Comment by dnadeau-quatral** [comment]
Hi,
Owncloud got these layout files:
```
core/templates/layout.base.php
core/templates/layout.user.php
core/templates/layout.guest.php
```
We can "override" these layout by placing a file with the same name in ```themes/mytheme/core/templates/```

But it's not possible to add a custom layout like this:
```
themes/mytheme/core/templates/layout.mail.php
```

And use the custom layout by passing the name of layout as parameter
```
OCP\Template('accounts', 'register', 'mail');
```

We changed the code of ```lib/private/templatelayout.php``` to support other layout.

But does Owncloud have a better way of doing this ?

**Comment by DeepDiver1975** [comment]
What did you change in templatelayout.php? Thx

**Comment by lparmentier-quatral** [comment]
See first comment: It's useful to add an email layout, or a login layout.

**Comment by dnadeau-quatral** [comment]
We just added a condition if the $renderAs = 'mail'
```
			if($renderas =='mail' || $renderas == 'signup'){
				parent::__construct('core', 'layout.' . $renderas);
			}else{
				parent::__construct('core', 'layout.base');
			}
```

**Comment by jancborchardt** [comment]
Closing this. Theming is available and easily possible via CSS.
