### ISSUE TITLE
OWNCLOUD/DATA/.../CACHE doesn't empty?

### ISSUE THREAD

**Issue by reylon** [owncloud/core#16841]
Hi, I have the problem from a lot of time and on two different server and configuration about root file system full and system crash. I see that the folder /www/owncloud/data/.../cache doesn't empty and grow up until arrive at the maximum disk size, especially when the syncronization stop and restart very often. 
More details on https://forum.owncloud.org/viewtopic.php?f=31&t=28670. I will try to observ more the problem...

**Comment by karlitschek** [comment]
@PVince81 I remember that we fixed something with cleanup of old files. Do you remember?

**Comment by PVince81** [comment]
Unfortunately no.
See https://github.com/owncloud/core/issues/14646

**Comment by PVince81** [comment]
@reylon you should be able to work it around by setting up your own cron job that deletes old/outdated files.

**Comment by reylon** [comment]
Hello guys. I'm not so able... :( I'm studying the problem how I can... Can be very easy for each of you see if the directory grow up or no in time... sometimes a simple question is not observed:) Possible that no one has my problem?
