### ISSUE TITLE
8.1 App menu gone in mobile view

### ISSUE THREAD

**Issue by Raydiation** [owncloud/core#16844]
In the mobile view, the app menu is gone and only the cloud symbol is left

![bug](https://cloud.githubusercontent.com/assets/195053/8064342/631a1e6c-0eda-11e5-9165-f9bcb462b2e6.png)

@jancborchardt @MorrisJobke @PVince81

**Comment by jancborchardt** [comment]
Fix at https://github.com/owncloud/core/pull/16860 – thanks for noticing!
