### ISSUE TITLE
Make app descriptions translatable

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16855]
Currently app descriptions in the apps page are only in English.

Making them translatable requires development.

I suggest to make this strings able to be translated in transifex.

**Comment by DeepDiver1975** [comment]
We should really close this from my perspective - a hell of work needs to be invested and I really question it's need

@karlitschek @MTRichards @cmonteroluque

**Comment by cmonteroluque** [comment]
it's come up on mobile. I agree it's not a top priority

**Comment by karlitschek** [comment]
I agree. We could make our own app description translatable in the future with some work. But for 3rdparty ones this is tough.

**Comment by DeepDiver1975** [comment]
so close then?

**Comment by MTRichards** [comment]
ok. Close if you want. It just isn't a top priority at this moment.
