### ISSUE TITLE
Add X-Sendfile/X-Accel-Redirect for WebDAV GET request

### ISSUE THREAD

**Issue by lobeck** [owncloud/core#16851]
It seems as the X-Sendfile/X-Accel-Redirect feature is just in OC_Files, this is only called from download.php and therefore just available on the WebUI.

But there seems no such method available for WebDAV and therefore for example downloads made by the Client Apps are not accelerated.

So it would be great to get this feature there too and maybe also on other places i don't know about.

**Comment by RealRancor** [comment]
Hi,

this probably needs an update of SabreDAV which is on the roadmap for 3.1 according to: https://github.com/fruux/sabre-dav/issues/120

**Comment by DeepDiver1975** [comment]
This has to be implemented in sabredav one day.
