### ISSUE TITLE
App uninstall with option to delete database tables and appconfig

### ISSUE THREAD

**Issue by aidanamavi** [owncloud/core#16852]
For the admins who aren't developers, it would be beneficial to streamline the app removal process by providing a check box next to the uninstall button, which removes the relevant appconfig entries and tables in the database upon deletion.

Removing app folders was recently once a step that is no longer necessary because this process is streamlined, however the database removal is still not. Therefore, it would be logical to provide this enhancement to the UX.

**Comment by oparoz** [comment]
I agree. We end up with ghost apps which can't be removed from the list of "not enabled" apps and which may block the installation of newer versions.

**Comment by libasys** [comment]
ping @LukasReschke @PVince81 talked yesterday on IRC about!

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/issues/29059 which had more discussions.
