### ISSUE TITLE
"Add group" appearing for group admins

### ISSUE THREAD

**Issue by oquidave** [owncloud/core#16850]
Hello, I believe this is a bug. The "Add group" option on the left panel appears for group admins that don't have global system-wide (super admin) rights. The result is that when you click on "Add group", it says " logged in user must be an admin " which obviously doesn't make sense. 

PS: I would have liked group admins to create and manage their own groups, on top of adding and removing users which is supported. Consider this a feature request.

**Comment by karlitschek** [comment]
@blizzz any idea?

**Comment by PVince81** [comment]
Duplicate of https://github.com/owncloud/core/issues/10228
