### ISSUE TITLE
[Experimental file locking] Different kind of messages.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16858]
When telling the user that a folder/file is locked sometimes appears an error dialog and others a yellow warning on the top.

Examples:  

Renaming while locked shows an error dialog.
Uploading while locked shows warning message.

I suggest to choose only one way of displaying this message.

Also when trying to delete a file which is being moved instead of saying that the file is locked it says: 'Could not delete ' + $filename

**Comment by DeepDiver1975** [comment]
@jancborchardt your call - no dialogs - right?

**Comment by jancborchardt** [comment]
Messages where no action is required should be the yellow notifications, never dialogs.

**Comment by DeepDiver1975** [comment]
Next steps:
- search the code base fo OC.dialogs
- double check each occasion if is shall be converted into a notification

Any volunteer? @VicDeo @th3fallen @bantu - THX

**Comment by PVince81** [comment]
The dialogs are old stuff from the past. Many pieces of the files app contain dialogs when an exception is found. These should be replaced with notifications using `OC.Notification.showTemporary()`.
Tagging as junior job.

**Comment by PVince81** [comment]
Moving to 8.2. I might be touching this part anyway with #12353

**Comment by cmonteroluque** [comment]
#12353 already moved to 9.0. Same with this...

**Comment by PVince81** [comment]
With the move to Webdav, it consistently uses the orange notification now. Closing.
