### ISSUE TITLE
Missing TXT mime icon when sharing empty txt file by link

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16866]
### Steps to reproduce
1. Enable option Allow users on this server to send shares to other servers
2. Share a file by link
3. Paste the link in IE9 browser.

### Expected behaviour
No image should appear

### Actual behaviour
A red cross image appears as ii is shown in the screenshot attached.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** "version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity: 1.2.3
 - admin_audit: 0.6
 - encryption: 1.0.0
 - enterprise_key: 0.1.0
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.4
 - user_ldap: 0.6.0
 - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** ActiveDirectory

### Client configuration
**Browser:** Internet Explorer 9
![captura de pantalla 2015-06-10 a las 18 52 52](https://cloud.githubusercontent.com/assets/10596560/8088595/b5faea6c-0fa2-11e5-918a-8855cae455bd.png)

**Comment by oparoz** [comment]
What is the URL to the image?

**Comment by davitol** [comment]
![captura de pantalla 2015-06-11 a las 8 36 53](https://cloud.githubusercontent.com/assets/10596560/8101227/5c08e3ba-1015-11e5-9450-461fbc3906b8.png)
http://docker.oc.solidgear.es:50627/index.php/apps/files_sharing/ajax/publicpreview.php?x=1920&y=200&a=true&file=Compartir.txt&t=PoChlwczbCt7sGu&scalingup=0

**Comment by oparoz** [comment]
I'm getting an error 500, so we need logs of the error from both the sharing cloud and the original cloud,
There is either a problem with the TXT preview on the sharing cloud or the original file is not available.

**Comment by davitol** [comment]
In the original cloud owncloud.log has no info related to this problem, and it happens before we write down any info about server B.
The cross image appears due to the preview icon is not available, for example when the txt file is empty. If we write something in the txt file, it appears as it is shown in the folllowing image

![captura de pantalla 2015-06-11 a las 16 55 38](https://cloud.githubusercontent.com/assets/10596560/8110096/be71883c-105a-11e5-98bc-95304b7ca880.png)

**Comment by oparoz** [comment]
OK, so its an issue with publicpreview.php not finding the TXT mime icon on the server.

**Comment by rullzer** [comment]
Since we now have text previews this issues seems solved. It just has an empty text-preview div. @davitol should be fixed in master

**Comment by davitol** [comment]
:+1: tested in masted and it is fixed
