### ISSUE TITLE
Shared calendar can be deleted also by shared user

### ISSUE THREAD

**Issue by pengandy** [owncloud/core#16877]
Sharing a calendar by user A to user B: user B can delete the calendar. This action will also remove the calendar for user A. This should not be possible! It should still be available for user A!

ownCloud 8.0.3 (stable)
Calendar 0.6.4

**Comment by RealRancor** [comment]
Hi,

the issue tracker of the calendar app is located here:

https://github.com/owncloud/calendar/issues

AFAIK there is already an existing issue reported there so please have a short search before creating your issue there.

**Comment by RealRancor** [comment]
Ref: https://github.com/owncloud/calendar/issues/475 and a possible fix in https://github.com/owncloud/calendar/pull/495
