### ISSUE TITLE
Deleting a user adds "NaN" where the user count of groups used to be

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#16876]
Regression from https://github.com/owncloud/core/pull/16402

**Comment by jancborchardt** [comment]
I just now saw #16402 and commented there – am not happy about that change. Would be cool if next time I could at least be mentioned once, if design changes like that are made.

**Comment by nickvergessen** [comment]
It was not a design change, but a performance change.

**Comment by jancborchardt** [comment]
A performance change which happened to result in a very apparent design/interface change though. ;)

**Comment by davitol** [comment]
Testing in "7.0.7.0","versionstring":"7.0.7beta i found this behaviour. Is a backport to 7.0.7 planned?

**Comment by nickvergessen** [comment]
The problem that caused the NaN on master was not backported, so the fix to that (partly reverting it) does not get backported as well. If you are sure this is a problem with oC in 7.0, you'd need to go with a new ticket
