### ISSUE TITLE
Ability to search in Personal and Admin settings

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#16875]
As there are more and more settings (as it goes …) the sidebar is a good filter mechanism. But even better would be if search would also work in the Personal and Admin settings.

You can see that work very nicely in Chrome settings search:
![chrome settings search](https://cloud.githubusercontent.com/assets/925062/8104772/a93b2922-1033-11e5-8480-ca78cb5c8b6b.png)
The full text inside there gets searched and only the matching sections are displayed. We can do it just like that for the Personal and Admin settings.

**Comment by jancborchardt** [comment]
Moving to 9.0

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/issues/26765
