### ISSUE TITLE
Add to your ownCloud button should show a message, when sharing a file by link writting a URL like user@owncloud

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16870]
### Steps to reproduce
1. Enable option Allow users on this server to send shares to other servers
2. Share a file by link
3. Paste the link in the browser.
4. Write down a url in the up to the right corner textbox "Add to your owncloud" with the following syntax: user@owncloudURL that exists.
5. Click on the arrow.
### Expected behaviour

An error message about "No ownCloud installation (7 or higher) found at ..."
### Actual behaviour

You are redirected to an owncloud page of the instance that shares the file.
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** "version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
- activity: 1.2.3
- admin_audit: 0.6
- encryption: 1.0.0
- enterprise_key: 0.1.0
- files: 1.1.9
- files_locking: 
- files_pdfviewer: 0.7
- files_sharing: 0.6.1
- files_sharing_log: 0.5
- files_texteditor: 0.4
- files_trashbin: 0.6.2
- files_versions: 1.0.5
- files_videoviewer: 0.1.3
- firewall: 0.91.2
- firstrunwizard: 1.1
- gallery: 0.6.0
- provisioning_api: 0.2
- templateeditor: 0.1
- updater: 0.4
- user_ldap: 0.6.0
- windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Internet Explorer 9

**Comment by PVince81** [comment]
@davitol so basically you are expecting the logic to strip away the "user@" part of the URL ?
What if "user" doesn't match the currently logged in user in the target ownCloud ? This could cause confusion.

**Comment by cmonteroluque** [comment]
This issue will fall off 8.2 if not resolved by 6 Oct

**Comment by PVince81** [comment]
Won't fix. Don't use the "user" part.
