### ISSUE TITLE
[Experimental files locking] Files not fully uploaded to external storages should not appear.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16874]
### Steps to reproduce

1. Enable redis as cache system.
2. Enable experimental files locking.
3. Enable external storage app.
4. Mount a SFTP folder.
5. Create a folder 'folder'.
6. Upload a big file on it using webdav.
7. Using another browser log in and see files inside SFTP folder.

### Expected behaviour
Big file doesn't appear until it is fully uploaded.
or
It shows some kind of progress bar showing how much is left. (More development needed)

### Actual behaviour
Big file appears with an incorrect size. And you can interact with it, which leads to errors,  corrupt downloads, etc.
If you keep refreshing size increases.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Experimental files locking.
External storage.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
SFTP.

**Are you using encryption:** 
No.

**Logs**
```

```

### Client configuration

**browser**
Chrome 41, Firefox

**Comment by SergioBertolinSG** [comment]
@icewind1991 @DeepDiver1975 @PVince81 
I think experimental files locking is the right moment to avoid this behaviour. But I'm sure you have talk about this before.

**Comment by icewind1991** [comment]
I believe #16729 should fix this issue

**Comment by PVince81** [comment]
Hmm strange, normally the file should first be uploaded a part file on SFTP, and only renamed at the end. So it should never appear.

**Comment by PVince81** [comment]
@SergioBertolinSG can you retest this one on 8.2RC1 ?

**Comment by SergioBertolinSG** [comment]
@PVince81 Without redis?

**Comment by PVince81** [comment]
With either redis or db locking

**Comment by SergioBertolinSG** [comment]
Tested in 8.2RC1 I get a 500 Internal Server Error when the file finish the upload. But the file doesn't appear in the second browser, which is fine.

**Comment by SergioBertolinSG** [comment]
Tested using 8.2RC1 and no redis. It works fine, the file doesn't appear until uploading finished.
