### ISSUE TITLE
[Sharing by link] Modifying the password produces erratic behaviour in server B

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16873]
### Steps to reproduce
1. Enable option Allow users on this server to send shares to other servers
2. Share a file .txt by link and accept it in server B
3. Change the password in Server A

### Expected behaviour
The file should not be visible in server B any longer

### Actual behaviour
The icon of the file is visible but not the content of the file.txt. 
Note: If you refresh the screen twice, the file disappears.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** "version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity: 1.2.3
 - admin_audit: 0.6
 - encryption: 1.0.0
 - enterprise_key: 0.1.0
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.4
 - user_ldap: 0.6.0
 - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Internet Explorer 9

**Comment by schiesbn** [comment]
The first time you try to access the file after the password change we detect that we are no longer able to mount it and remove it. That's the only way to do it because there is no way server A could notify server B about a password change.

**Comment by davitol** [comment]
@schiesbn But I believe that it would be possible to 'delete' the file in server B after the first screen refresh, no? For example in the first screen refresh the preview icon turns into a generic one. Is it not possible to delete the file in server B instead of changing this preview icon in the first refreshing?

**Comment by PVince81** [comment]
It would be possible, but it means that for every file displayed in the list, it would have to send a remote request. This is indirectly related to https://github.com/owncloud/core/issues/5036 which contains a discussion why we don't want to check every ext storage visible for performance reasons.

**Comment by davitol** [comment]
OK, thanks for the info. I'll close it.
