### ISSUE TITLE
Search result misalignment if only results from subfolder

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#16878]
If there are no results in the current folder, the folder list is not shown. This leads to this error:
![music search mislayout](https://cloud.githubusercontent.com/assets/925062/8105214/6f043d6c-1037-11e5-846d-f24607e854cc.png)

Which is caused by the CSS which uses a negative margin-top to counter the whitespace on the bottom of the normal filelist. If the normal filelist doesn’t exist, there’s no whitespace to counter and instead the other search results are pushed up even more.

cc @owncloud/designers @aidanamavi @colmoneill anyone want to pick this up?

**Comment by aidanamavi** [comment]
I cannot replicate this issue with v8.1.0beta2 on Firefox nor Chrome. Let me know what browsers, and core versions you are using, if you'd like me to investigate further.

**Comment by jancborchardt** [comment]
I use latest master, and this happens for me in both Chrome and Firefox.

@owncloud/designers @colmoneill can you reproduce this?

**Comment by colmoneill** [comment]
I can't reproduce this either :(

in all cases of search I am presented with my breadcrumb / info bar under the 'new file' and 'upload' options.

**Comment by jancborchardt** [comment]
@aidanamavi @colmoneill so for you searching works totally fine in all cases, no bugs?

@MorrisJobke @owncloud/designers can anyone reproduce my above issue? If not, then we can close this.

**Comment by jancborchardt** [comment]
@schiesbn maybe if you have time check if you can reproduce this?

**Comment by schiesbn** [comment]
I can reproduce it on master, state 829f6474ff4cd4e39647bcb5b68b5e5c0fb1b483

![1](https://cloud.githubusercontent.com/assets/1589737/8186349/10d9e57c-144a-11e5-8911-ee9eee5e3657.png)

**Comment by schiesbn** [comment]
My steps to test it:

- create a folder "New Folder"
- move to "New Folder"
- create some files "New text file.txt"
- go back to the root
- search for "new" everything is OK
- rename the folder "new folder" to "folder"
- search again for "new" -> broken result as shown above

**Comment by th3fallen** [comment]
> I can create it by adding padding-top: 250px; to #app-content, of course this is not the solution. Just to illustrate it

also not a solution but instead of adding padding-top if you just disable the negative top margin it works as expected too.

**Comment by jancborchardt** [comment]
@schiesbn can you maybe add a class like `.search-empty` to `#app-content-files` when there are no results? Then I can adjust the margins to fix it. Start a pull request with adding that, and I will add a commit with the CSS to fix it.

**Comment by VicDeo** [comment]
Is there any reason why `tr.summary` has  height of 300px btw?
