### ISSUE TITLE
Force share a folder

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#16871]
In an organisation we want to share a folder of corporate documents (policies, procedures, forms...), email address book... Currently we can share the folder read-only to a group that has "everyone" in it. On some clients, the user can delete individual files in the folder, but they sync again immediately from the server - that is OK, the user still ends up being "forced" to have all the files in the folder.
But if they delete the folder itself, it does not get synced back again. There has been plenty of discussion about that, because we do not want others to be able to spam someone by sharing bucket-loads of rubbish with them. There is also discussion of how users can get back shares that they have previously deleted - e.g. https://github.com/owncloud/core/issues/14075 

However in this use case we really do want to spam all the users with a folder they can't get rid of.
Suggestion:
a) Have an option on sharing like "force share" that sets that share so it can't be deleted/renamed/changed by the recipients (or at least it resets/resyncs itself if the recipient manages to change something in their client).
b) Only allow this option to admins, or to accounts that have been authorised for it (perhaps add a privilege/role that can be set on accounts that allows them the rights to use "force share").

**Comment by schiesbn** [comment]
While I see the your use case I'm still not convinced that it is a good idea to force users to have files/folders they can't remove. This can create a serious spam problem. People should be always in control of their workspace. On a physical workspace you also can't put a address book on their desk and prevent them to move it away.

But there are plans to move unshared files back to a "panding shares" sidebar so that the user can get them back if they want as long as the file/folder is still shared by the owner.

https://github.com/owncloud/core/issues/13495

**Comment by phil-davis** [comment]
Yes, I had read #13495 also (somehow didn't reference it in my first post). That all looks good to have, particularly when I "foolishly" decide to delete some folder that has been shared to me, then I wish I hadn't deleted it and I would like it back...
One of my examples is that we have organisation address books that we provide for use in Thunderbird. Thunderbird has an Address Book Synchronizer add-on that can sync/update the internal Thunderbird address book from an external source. If that external source is a known folder in every user's ownCloud, then the Address Book Synchronizer can always run whenever it likes. If the computer is off-line, on-line on the public internet, or on-line in the office intranet, the address book "mab" file is always available. Whenever the device gets online somehow it will update to the current version from the ownCloud server.
There are other ways to "skin that cat" for Thunderbird, but it is just an example of how it can be handy to have some folder/file names fixed in ownCloud so that other apps can rely on them being there.
Anyway, it would be good to see if there is much interest in this. If no-one else really cares for it then there is no point in adding bloat to the number of checkboxes presented to someone when sharing a folder :)

**Comment by schiesbn** [comment]
> One of my examples is that we have organisation address books that we provide for use in Thunderbird. Thunderbird has an Address Book Synchronizer add-on that can sync/update the internal Thunderbird address book from an external source. If that external source is a known folder in every user's ownCloud, then the Address Book Synchronizer can always run whenever it likes. 

This way you also need to guarantee that this folder is for everyone the same, right. This is something you can't do with sharing because if you share the folder with a user who already has a folder or file with the same name the share will be named "folder (2)".

Maybe it would be a idea to create this folder which is the same for everyone with a external storage, mounted by the admin for all users. This way you can ensure that every user has the same folder and a external mount point can neither be renamed nor deleted. But here you have the problem that such a folder is always read/write. 

For the specific use case of a address book it might be better do distribute it over LDAP, carddav or any other protocol which was designed explicitly for this task? Carddav could be used with the contacts app.

**Comment by phil-davis** [comment]
Here is a wacky way to do it:
a) Create folder Corp-Docs-source in an (admin) user account. Put the docs to be shared read-only to everyone in there.
b) Share Corp-Docs-source read-only with some usera.
c) From the admin user, make an external storage mount called Corp-Docs that mounts usera folder Corp-Docs-source.
Now everyone gets a folder Corp-Docs with all the docs in it.
Here is what I can do with it as an ordinary user in the client:
1) Rename Corp-Docs to something else - result, in a minute or so another Corp-Docs folder appears and all the docs are downloaded into it. Now I have the official Corp-Docs and a copy of it that is private to me. Seems OK - that is the same as the user doing copy-paste anyway.
2) Delete Corp-Docs - it goes away and is promptly downloaded again.
3) Add a new document to Corp-Docs - errors are logged "Not allowed because you don't have permission to add files in that directory". The new file gets "stuck" in the local client folder. I guess ownCloud does not like to delete stuff that users have added.
4) Delete an existing document - it gets downloaded again with log message "Not allowed to remove, restoring", so it comes back.
5) Edit an existing document - the original document gets downloaded again. The edited one gets renamed to *_conflict-datetimestamp. Log message "Downloaded, renamed conflicting file".

The end-user can accumulate more crud in their local copy of Corp-Docs. But they always get force-fed the folder and set of original files that are in the read-only external storage mount.

Any extra crud can be cleaned out by deleting Corp-Docs folder and letting it all download again - maybe a little drastic, but an action that is guaranteed to reset the folder to a good known state.

I'm not sure if it was really intended to support a twisted read-only internally-mapping-back-inside-the-same-ownCloud-server external mount point. But it might be a solution.

Ideally clients would detect when a folder is read-only on the server and set the folder read-only in the client OS/filesystem. I expect that all OS/filesystem combinations would have some file permissions mechanism to set read-only. That would prevent the messy bits where users add/edit files that then cannot be uploaded.

**Comment by PVince81** [comment]
@phil-davis with "fixed file names" maybe you mean something like permalinks, see https://github.com/owncloud/core/issues/11732

**Comment by sweco-senari** [comment]
+ 1
I also have a use case where i want to force users to share files within groups. In example: every user that is added to group XX should be able to see (and edit) uploads from other users in the XX-group.

**Comment by PVince81** [comment]
is that what the "disableunsharing" app does ? https://github.com/owncloud/disableunsharing

**Comment by phil-davis** [comment]
@PVince81 a good question :)
with the ability coming for users to re-accept shares they previously declined/deleted, the original issue here is lessened. If the user has deleted the "corporate-policies"  folder and wants to find a policy, they can get it back themselves (or by calling their helpdesk who will walk them through how to get it back)

**Comment by phil-davis** [comment]
The "spaces" concept is coming in oCIS. The accept/decline share feature exists nowadays in oC10 and can be easily enabled. So if users "delete" a share that they have received, then they can get it back again.

The need for this "force share" option is less - closing.
