### ISSUE TITLE
[Sharing by link] Add to your owncloud textbox should shown the URL properly using IE9 as browser

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16887]
### Steps to reproduce
1. Enable option Allow users on this server to send shares to other servers
2. Share a file by link
3. Paste the link in IE9 browser.
4. Write down a owncloudURL in the Add to your cloud textbox

### Expected behaviour
Textbox height and lenght should fit with the owncloud URL

### Actual behaviour
Height is a little bit small and from the 19th character, it is not visible. You type blindly.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** "version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity: 1.2.3
 - admin_audit: 0.6
 - encryption: 1.0.0
 - enterprise_key: 0.1.0
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.4
 - user_ldap: 0.6.0
 - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Internet Explorer 9

![captura de pantalla 2015-06-11 a las 16 40 31](https://cloud.githubusercontent.com/assets/10596560/8110836/a4ce2724-105e-11e5-9a73-490e97f6dc23.png)

**Comment by oparoz** [comment]
The blindly typing problem is not browser specific, so I'm removing the browser specific label and asking @jancborchardt to take a look.

**Comment by jancborchardt** [comment]
Well, we just have to restrict the width of the textbox. On Firefox and Chrome you definitely don’t type blindly – it’s the default behavior and the end of the URL you type is always shown.

@davitol @owncloud/designers from my view this is a non-issue. Can we close?

**Comment by oparoz** [comment]
I have missed the point of the OP. We don't, indeed, type blindly on Firefox, but you can never see the full URL, so if that's an IE only problem, then this might indeed be a browser specific issue...

**Comment by jancborchardt** [comment]
In that case though that’s not necessarily something we would want to shim, right? cc @MorrisJobke 

@davitol does this problem only occur there, and not on other textboxes?

**Comment by davitol** [comment]
@jancborchardt It occurs in IE9 and I only found this behaviour there.

**Comment by jancborchardt** [comment]
Worth to fix it? What do you say @MorrisJobke? I honestly doubt it.

**Comment by MorrisJobke** [comment]
> Worth to fix it? What do you say @MorrisJobke? I honestly doubt it.

Feel free to try it. We officially support IE8 & IE9 ...so we should try our best. Maybe it isn't as hard as you think ;)

**Comment by jancborchardt** [comment]
We’ll drop IE9 support with ownCloud 9.1 and this doesn’t really seem like a grave issue to fix. It will take more workarounds than it’s worth.
