### ISSUE TITLE
[Experimental files locking] Using encryption renaming a locked folder returns 500

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16882]
### Steps to reproduce

1. Enable redis as cache system.
2. Enable experimental files locking.
3. Enable encryption.
4. In admin page use default encryption module.
5. Relogin with admin user.
5. Create a folder 'folder'.
6. Upload a big file 'bigfile' to 'folder' using webdav.
7. Using webdav rename 'folder' to 'renamed_folder' while 'bigfile' is still uploading. 

### Expected behaviour
It returns 423 locked.

### Actual behaviour
It returns 500 internal error.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Experimental files locking.
Encryption.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
Yes.

**Logs**
```

```

### Client configuration

Webdav, cadaver.

**Comment by cmonteroluque** [comment]
blocking testing...

**Comment by PVince81** [comment]
Works for me on master:

Thread A:
```
dav:/owncloud/remote.php/webdav/> ls
Listing collection `/owncloud/remote.php/webdav/': succeeded.
Coll:   folder                                 0  Jun 11 17:23
        bacon.txt                           2348  Jun 11 17:14
dav:/owncloud/remote.php/webdav/> cd folder
dav:/owncloud/remote.php/webdav/folder/> put data1.dat 
Uploading data1.dat to `/owncloud/remote.php/webdav/folder/data1.dat':
Progress: [=============================>] 100.0% of 126679286 bytes succeeded.
```

Thread B:
```
Moving `/owncloud/remote.php/webdav/folder' to `/owncloud/remote.php/webdav/folder2':  failed:
423 Locked
```

also with encryption enabled.

**Comment by PVince81** [comment]
@SergioBertolinSG if you still see a 500 internal server error, please also provide the matching logs. Thanks.

**Comment by SergioBertolinSG** [comment]
I've tested again with last master and it is being locked. No more 500 internal.
So I close this, I'll keep using encryption and if it appears again I'll reopen it.

**Comment by PVince81** [comment]
I just tried this again in a different situation and got a 500 internal server error on the "PUT" call, not the rename. Note that I have a "sleep()" inside of streamCopy to delay the file upload.

The 500 is because the "part file could not be renamed to final file". From reading the code https://github.com/owncloud/core/blob/master/lib/private/connector/sabre/file.php#L117 the lock is supposed to be set already before the streamCopy.

So if I was still able to rename the folder during stream copy, then it means something is wrong with the lock.

What do you think @icewind1991 ?

**Comment by PVince81** [comment]
and the exception:
```
{"reqId":"h7FiFg9yLbpLT6EVUS3g","remoteAddr":"127.0.0.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 500 Could not rename part file to final file\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1087): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #244)\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(501): Sabre\\\\DAV\\\\Server->updateFile('folder\\\/bacon.tx...', Resource id #244, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/remote.php(84): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#8 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":205}","level":4,"time":"2015-06-11T16:11:10+00:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/folder\/bacon.txt"}
```

**Comment by PVince81** [comment]
Wait a minute, I don't even have locking enabled :rage: 
Sorry for the noise...
