### ISSUE TITLE
Enable app in apps page logs a JS error, still works properly

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#16891]
### Steps
1. Go to apps page
2. Go to "Not enabled" section
3. Enable an app, for example "External storage"
4. Check Javascript console

### Expected result
No errors

### Actual result
App is enabled, but error is logged:
![enableapperror](https://cloud.githubusercontent.com/assets/277525/8112347/6e49251a-1067-11e5-95be-d9a27d0c535b.png)

**Comment by PVince81** [comment]
Possible regression, but not checked

**Comment by karlitschek** [comment]
@DeepDiver1975 FYI

**Comment by DeepDiver1975** [comment]
Will have a look on Monday.

**Comment by DeepDiver1975** [comment]
... anybody else is actually welcome to have a look as well.

**Comment by DeepDiver1975** [comment]
duplicate https://github.com/owncloud/core/issues/17344
