### ISSUE TITLE
File not decrypting

### ISSUE THREAD

**Issue by deanbruhn** [owncloud/core#16895]
I have an issue that's popped up occasionally. 

A user will copy a file into an owncloud shared directory from the agent. The files that are sync'ed back down to the others users machines will be encrypted on their machines, also attempting to open the files from the documents application will not work. 

I am seeing nothing in the owncloud log that would indicate a problem.

**Comment by deanbruhn** [comment]
### Steps to reproduce
1. User uploads file to shared directory from the sync agent
2. File syncs down to other users computers through the sync agent
3. File is encrypted for all users (Inconsistently happening)
4. Users are unable to open file with documents application also
5. File downloaded through web interface is encrypted

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:
CentOS Linux release 7.1.1503 (Core)

**Web server:**
Server version: Apache/2.4.6 (CentOS)


**Database:**
| innodb_version          | 5.5.40-MariaDB-36.1 |
| protocol_version        | 10                  |
| slave_type_conversions  |                     |
| version                 | 5.5.41-MariaDB      |
| version_comment         | MariaDB Server      |
| version_compile_machine | x86_64              |
| version_compile_os      | Linux  
**PHP version:**
PHP 5.6.9 (cli) (built: May 15 2015 09:31:38) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies

**ownCloud version:** 
8.0.4

**Updated from an older ownCloud or fresh install:**
Started at version 7, slowly updated. Issue did not present itself due to update, previous update was several months prior

**List of activated apps:**
Activity
Deleted Files
Documents
First Run Wizard
Mail Template Editor
PDF Viewer
Pictures
Server-side Encryption
Share Files
Text Editor
Updater
Versions
Video Viewer

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'occ975a36b02',
  'passwordsalt' => 'XXXXXXXX',
  'trusted_domains' =>
  array (
    0 => 'xxx.xxxxx.xxx',
  ),
  'datadirectory' => '/var/ownstore',
  'overwrite.cli.url' => 'http://172.16.64.80/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.4.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'XXXXXXXX',
  'dbpassword' => 'XXXXXXXX',
  'installed' => true,
  'forcessl' => true,
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'mail_from_address' => 'support',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'XXXXXX.XXXXX',
  'mail_smtphost' => '172.16.64.30',
  'mail_smtpport' => '25',
  'theme' => '',
  'maintenance' => false,
  'secret' => 'XXXXXXXXXXXX',
  'forceSSLforSubdomains' => true,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
Local
**Are you using encryption:** yes/no
Yes 
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No



Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
Agent is 1.8

**Operating system:**
OSX and Windows

### Logs


#### ownCloud log (data/owncloud.log)
{"reqId":"14df441923f7eaea952da3451ffb5791","remoteAddr":"71.193.89.18","app":"core","message":"unable to rename, file does not exists : files_encryption\/keys\/Band Stuff\/Treasons\/Individual Songs\/untitled folder\/","level":3,"time":"2015-06-11T04:39:03+00:00"}
{"reqId":"0a8f7637f1650368ed25e5d34fe08559","remoteAddr":"173.8.126.249","app":"PHP","message":"Undefined index: storage_mtime at \/var\/www\/html\/owncloud\/lib\/private\/files\/cache\/watcher.php#67","level":3,"time":"2015-06-11T16:08:31+00:00"}
{"reqId":"0a8f7637f1650368ed25e5d34fe08559","remoteAddr":"173.8.126.249","app":"PHP","message":"filemtime(): stat failed for \/var\/ownstore\/shahserver\/files\/ToDo\/6-8-2015 copy.odt at \/var\/www\/html\/owncloud\/lib\/private\/files\/storage\/local.php#138","level":3,"time":"2015-06-11T16:08:31+00:00"}
{"reqId":"73dd38599573f75a251455aa1d358d6e","remoteAddr":"173.8.126.249","app":"documents","message":"Starting a session failed. Reason: 510916 can not be resolved","level":2,"time":"2015-06-11T16:09:30+00:00"}
{"reqId":"b75188f2de7d523af5d8a0e3b588437d","remoteAddr":"173.8.126.249","app":"PHP","message":"Undefined index: mimetype at \/var\/www\/html\/owncloud\/lib\/private\/files\/cache\/scanner.php#263","level":3,"time":"2015-06-11T16:10:50+00:00"}
{"reqId":"b75188f2de7d523af5d8a0e3b588437d","remoteAddr":"173.8.126.249","app":"PHP","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/files\/cache\/scanner.php#265","level":3,"time":"2015-06-11T16:10:50+00:00"}
{"reqId":"b75188f2de7d523af5d8a0e3b588437d","remoteAddr":"173.8.126.249","app":"PHP","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/files\/cache\/scanner.php#268","level":3,"time":"2015-06-11T16:10:50+00:00"}
{"reqId":"b75188f2de7d523af5d8a0e3b588437d","remoteAddr":"173.8.126.249","app":"PHP","message":"Undefined index: storage_mtime at \/var\/www\/html\/owncloud\/lib\/private\/files\/cache\/watcher.php#67","level":3,"time":"2015-06-11T16:10:50+00:00"}
{"reqId":"b75188f2de7d523af5d8a0e3b588437d","remoteAddr":"173.8.126.249","app":"PHP","message":"filemtime(): stat failed for \/var\/ownstore\/shahserver\/files\/ToDo\/6-9-2015 copy.odt at \/var\/www\/html\/owncloud\/lib\/private\/files\/storage\/local.php#138","level":3,"time":"2015-06-11T16:10:50+00:00"}
{"reqId":"820eb2d96e6825413fa81a22452fe494","remoteAddr":"173.8.126.249","app":"remote","message":"An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory","level":4,"time":"2015-06-11T18:38:05+00:00"}
{"reqId":"3697364fa2d20cfc311f47c96edbdd15","remoteAddr":"71.193.89.18","app":"PHP","message":"Undefined index: storage_mtime at \/var\/www\/html\/owncloud\/lib\/private\/files\/cache\/watcher.php#67","level":3,"time":"2015-06-11T19:30:04+00:00"}
{"reqId":"3697364fa2d20cfc311f47c96edbdd15","remoteAddr":"71.193.89.18","app":"PHP","message":"filemtime(): stat failed for \/var\/ownstore\/shahserver\/files\/ToDo\/6-11-2015.odt at \/var\/www\/html\/owncloud\/lib\/private\/files\/storage\/local.php#138","level":3,"time":"2015-06-11T19:30:04+00:00"}
Insert your ownCloud log here
```

**Comment by karlitschek** [comment]
@schiesbn

**Comment by PVince81** [comment]
@deanbruhn can you check the "oc_filecache" table entries for the broken files and see if their "encrypted" flag is properly set to 1 ?

Or did you have any more luck with 8.0.8 or 8.1.3 ?
