### ISSUE TITLE
Set filesystem_check_changes to 0 by default

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#16897]
Many ownCloud setups are using the "data" folder exclusively through ownCloud, which means the data is never modified through external programs. This is even more true for people using encryption, in which case the files cannot be accessed externally anyway with direct access to the "data" folder.

Since 8.1, external storage mount points have their own "detect remote changes" setting. This means that "filesystem_check_changes" isn't global any more and only applies to the home/local storage (data directory).

So we could change it to 0 by default which would improve performance in such setups by avoiding unnecessary update checks and also potential issues related to concurrent scanner runs.

People who use an externally mounted data folder (ex: NAS) would then need to explicitly set that setting to 1. Unless we find a way to auto-detect such situations or ask the admin at setup time.

@icewind1991 @karlitschek @DeepDiver1975 @schiesbn @nickvergessen 

Also see https://github.com/owncloud/core/issues/13391#issuecomment-111401970

**Comment by nickvergessen** [comment]
@PVince81 

> Unless we find a way to auto-detect such situations or ask the admin at setup time.

Should be rather trivial: If encryption and no external storage (with encryption set to false)

Cache this result for 30mins and refresh the cache when external storage settings are changed, one is added or removed. We could also change the logic check for encryption and otherwise contact the external storage manager whether there is a storage that is external readable (not-encrypted). This way the ext storage manager could also say storage xyz is not encrypted by owncloud encryption, but is still encrypted due to the architecture of server/disk/storage backend, and therefor still not readable?

**Comment by PVince81** [comment]
I'm not sure yet whether "filesystem_check_changes" override the custom external storage settings.
In my proposal I'd say "filesystem_check_changes" would be changed to only affect the home storage and have no effect on external storages.

So if we'd use your detection logic instead of defaulting to 0, then enabling encryption could auto-switch this to 0.

**Comment by karlitschek** [comment]
Great idea! Makes sense

**Comment by icewind1991** [comment]
Note that we can overwrite the watcher settings on a per-storage basis

**Comment by PVince81** [comment]
@icewind1991 thanks. So this means the global one does not override.

So changing the default to 0 would be enough to make this work.

Let's set this to 8.2

**Comment by PVince81** [comment]
PR is here https://github.com/owncloud/core/pull/17950

**Comment by PVince81** [comment]
Some concurrency issues (not all) can be solved by setting it to zero, for example:
- https://github.com/owncloud/core/issues/17594#issuecomment-125565811
- https://github.com/owncloud/client/issues/3324#issuecomment-125899727

**Comment by PVince81** [comment]
We should add this to the release notes for 8.2 @MTRichards @carlaschroder.
This is only relevant for users who don't use the "data" directory exclusively through ownCloud, which is sometimes the case when people use NAS boxes and have an external HDD with the data folder in it, which content might change from outside and must be detected by OC.

**Comment by karlitschek** [comment]
i would support this change!

**Comment by MTRichards** [comment]
Yes, we must update the release notes and documentation.
I also support setting it to 0 to speed performance because MOST people use ownCloud this way. If the other 10-20% have to make the change, for it to work for them, so be it.

**Comment by karlitschek** [comment]
agreed. Just to be clear. It was never supported to be able to manually mess with the files in 'data'. So hopefully this doesn't surprise people. But you never know ;-)

**Comment by PVince81** [comment]
https://github.com/owncloud/documentation/commit/e4d5b5ae6915fb95e5c755b476f4ebd9926664e0#diff-92772bb6c1a548d97698c5ed357ec03fR8

**Comment by PVince81** [comment]
doc ticket https://github.com/owncloud/documentation/issues/3388
