### ISSUE TITLE
Select View: Hide / Unhide of left-sideoption panel  in OC

### ISSUE THREAD

**Issue by hitam4450** [owncloud/core#16894]
I refer to the following issue opened in the calenadar app:

https://github.com/owncloud/calendar/issues/804

and ask the question, if it could be a GENERAL Option in OC to introduce / implement a toggle switch to hide / unhide the left side panel for EVERY app to maximize the screen usage - especially on small (e.g. mobile) screens.

I just want to start a discussion  / brainstorming session!

Regards, hitam4450

**Comment by PVince81** [comment]
@hitam4450 when viewed on mobile, the sidebar is already collapsed and can be activated with a swipe gesture. Did you discover any mobile resolutions where it did not get hidden ?

**Comment by PVince81** [comment]
I'm talking about the files app actually. Not sure about the calendar app.

**Comment by hitam4450** [comment]
Hi, I tried it on my tablet (GALAXY TAB S 8.4 with ANDROID 5.0.2 and the 
latest firefox):

in file app no swipe gestures available, the feature does not bwork ! or 
ist it a bug??

in calendar app not avialable!

regards, hitam4450


Am 15.06.2015 um 17:53 schrieb Vincent Petry:
