### ISSUE TITLE
[Experimental files locking] Uploading files from a federated server to a locked folder returns 500

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16896]
### Steps to reproduce

Having two servers 'serverA' and 'serverB' with experimental files locking enabled do:

1. Enable external storage app in 'serverA'.
2. Mount a SFTP folder.
3. Inside 'SFTP' create a folder 'SUBDIR'.
4. Use federated sharing to share 'SUBDIR' with 'admin' in 'serverB'.
5. Upload a 50MiB file in 'SUBDIR'.
6. Open 'serverB' and accept the federated folder.
7. (Using webdav or web ui) Delete 'SUBDIR'.
8. (Using webdav) Upload a small file from 'serverB'

### Expected behaviour
'serverB' gets an error 423 about locked folder.

### Actual behaviour
'serverB' gets 500 Internal server error when trying to upload.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Experimental files locking.
External storage.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
SFTP.

**Are you using encryption:** 
No.

**Logs**
```

```

### Client configuration

**browser**
Chrome 43
**webdav**
Cadaver

**Comment by PVince81** [comment]
@SergioBertolinSG whenever you see a 500 error, please also post the matching log.
Thanks.

**Comment by PVince81** [comment]
Any update on the missing logs ?

**Comment by SergioBertolinSG** [comment]
serverB logs:
´´´
{"reqId":"H9jwNcsnuS4P20s3dU9S","remoteAddr":"82.159.139.58","app":"webdav","message":"Exception: {\"Message\":\"Not Found\",\"Code\":404,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Client.php(233): Sabre\\\\HTTP\\\\Client->send(Object(Sabre\\\\HTTP\\\\Request))\\n#1 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/dav.php(263): Sabre\\\\DAV\\\\Client->propFind('SUBDIR\\\/owncloud...', Array)\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/dav.php(685): OC\\\\Files\\\\Storage\\\\DAV->propfind('SUBDIR\\\/owncloud...')\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/common.php(605): OC\\\\Files\\\\Storage\\\\DAV->getPermissions('SUBDIR\\\/owncloud...')\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(543): OC\\\\Files\\\\Storage\\\\Common->getMetaData('SUBDIR\\\/owncloud...')\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(106): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getMetaData('SUBDIR\\\/owncloud...')\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(128): OC\\\\Files\\\\Cache\\\\Scanner->getData('SUBDIR\\\/owncloud...')\\n#7 \\\/opt\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/external\\\/scanner.php(55): OC\\\\Files\\\\Cache\\\\Scanner->scanFile('SUBDIR\\\/owncloud...', 0)\\n#8 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php(214): OCA\\\\Files_Sharing\\\\External\\\\Scanner->scanFile('SUBDIR\\\/owncloud...')\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php(111): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #35)\\n#10 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('owncloudgui.h', Resource id #35)\\n#11 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('COMPARTIDO\\\/SUBD...', Resource id #35, NULL)\\n#12 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#13 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#14 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#15 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#16 \\\/opt\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#17 \\\/opt\\\/owncloud\\\/remote.php(84): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#18 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/http\\\/lib\\\/Client.php\",\"Line\":154}","level":4,"time":"2015-06-12T07:47:57+00:00"}
{"reqId":"FGbqdLkPfIOfoH2um1cB","remoteAddr":"82.159.139.58","app":"webdav client","message":"curl GET http:\/\/docker.oc.solidgear.es:50666\/public.php\/webdav\/SUBDIR\/owncloudgui.h returned status code 423","level":3,"time":"2015-06-12T07:48:03+00:00"}
{"reqId":"FGbqdLkPfIOfoH2um1cB","remoteAddr":"82.159.139.58","app":"webdav","message":"Exception: {\"Message\":\"Not Found\",\"Code\":404,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Client.php(233): Sabre\\\\HTTP\\\\Client->send(Object(Sabre\\\\HTTP\\\\Request))\\n#1 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/dav.php(263): Sabre\\\\DAV\\\\Client->propFind('SUBDIR\\\/owncloud...', Array)\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/dav.php(685): OC\\\\Files\\\\Storage\\\\DAV->propfind('SUBDIR\\\/owncloud...')\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/common.php(605): OC\\\\Files\\\\Storage\\\\DAV->getPermissions('SUBDIR\\\/owncloud...')\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(543): OC\\\\Files\\\\Storage\\\\Common->getMetaData('SUBDIR\\\/owncloud...')\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(106): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getMetaData('SUBDIR\\\/owncloud...')\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(128): OC\\\\Files\\\\Cache\\\\Scanner->getData('SUBDIR\\\/owncloud...')\\n#7 \\\/opt\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/external\\\/scanner.php(55): OC\\\\Files\\\\Cache\\\\Scanner->scanFile('SUBDIR\\\/owncloud...', 0)\\n#8 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php(214): OCA\\\\Files_Sharing\\\\External\\\\Scanner->scanFile('SUBDIR\\\/owncloud...')\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php(111): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #35)\\n#10 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('owncloudgui.h', Resource id #35)\\n#11 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('COMPARTIDO\\\/SUBD...', Resource id #35, NULL)\\n#12 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#13 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#14 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#15 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#16 \\\/opt\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#17 \\\/opt\\\/owncloud\\\/remote.php(84): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#18 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/http\\\/lib\\\/Client.php\",\"Line\":154}","level":4,"time":"2015-06-12T07:48:04+00:00"}
root@38f1cd7492a4:/opt/owncloud/data# rm owncloud.log 
root@38f1cd7492a4:/opt/owncloud/data# cat owncloud.log 
{"reqId":"B+QmZOWmmGKspOdZHBHF","remoteAddr":"82.159.139.58","app":"webdav client","message":"curl GET http:\/\/docker.oc.solidgear.es:50666\/public.php\/webdav\/networksettings.ui returned status code 201","level":3,"time":"2015-06-16T08:54:06+00:00"}
{"reqId":"B+QmZOWmmGKspOdZHBHF","remoteAddr":"82.159.139.58","app":"hook","message":"error while running hook (OCA\\Files_Versions\\Hooks::write_hook): files\/61a03745f2b2971b9d7e76c05020f63e is locked","level":3,"time":"2015-06-16T08:54:06+00:00"}
{"reqId":"bRyzRt7rphMAzdzUGd9P","remoteAddr":"82.159.139.58","app":"webdav client","message":"curl GET http:\/\/docker.oc.solidgear.es:50666\/public.php\/webdav\/networksettings.cpp returned status code 423","level":3,"time":"2015-06-16T08:55:15+00:00"}
{"reqId":"bRyzRt7rphMAzdzUGd9P","remoteAddr":"82.159.139.58","app":"webdav","message":"Exception: {\"Message\":\"Not Found\",\"Code\":404,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Client.php(233): Sabre\\\\HTTP\\\\Client->send(Object(Sabre\\\\HTTP\\\\Request))\\n#1 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/dav.php(263): Sabre\\\\DAV\\\\Client->propFind('networksettings...', Array)\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/dav.php(685): OC\\\\Files\\\\Storage\\\\DAV->propfind('networksettings...')\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/common.php(605): OC\\\\Files\\\\Storage\\\\DAV->getPermissions('networksettings...')\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(543): OC\\\\Files\\\\Storage\\\\Common->getMetaData('networksettings...')\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(106): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getMetaData('networksettings...')\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(128): OC\\\\Files\\\\Cache\\\\Scanner->getData('networksettings...')\\n#7 \\\/opt\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/external\\\/scanner.php(55): OC\\\\Files\\\\Cache\\\\Scanner->scanFile('networksettings...', 0)\\n#8 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php(214): OCA\\\\Files_Sharing\\\\External\\\\Scanner->scanFile('networksettings...')\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php(111): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #35)\\n#10 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('networksettings...', Resource id #35)\\n#11 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('FOLDER\\\/networks...', Resource id #35, NULL)\\n#12 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#13 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#14 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#15 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#16 \\\/opt\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#17 \\\/opt\\\/owncloud\\\/remote.php(84): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#18 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/http\\\/lib\\\/Client.php\",\"Line\":154}","level":4,"time":"2015-06-16T08:55:16+00:00"}
´´´

serverA logs:
```
{"reqId":"GSuhVkP5gvWzRvgkLKlH","remoteAddr":"172.17.42.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 files\\\/77d32dc79f1e8b1abf9cf551dcfd4a5a is locked\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php(111): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #36)\\n#1 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('networksettings...', Resource id #36)\\n#2 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('networksettings...', Resource id #36, NULL)\\n#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#6 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/opt\\\/owncloud\\\/apps\\\/files_sharing\\\/publicwebdav.php(92): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/opt\\\/owncloud\\\/public.php(75): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#9 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":119}","level":4,"time":"2015-06-16T08:55:15+00:00"}
{"reqId":"C6hoEGqegVolLS3RfCc3","remoteAddr":"172.17.42.1","app":"core","message":"Can't get app storage, app files_external, user not logged in","level":3,"time":"2015-06-16T08:55:15+00:00"}
{"reqId":"C6hoEGqegVolLS3RfCc3","remoteAddr":"172.17.42.1","app":"core","message":"Can't get app storage, app files_external, user not logged in","level":3,"time":"2015-06-16T08:55:15+00:00"}
{"reqId":"R5MJ4RMLSvyRQeUnCCI4","remoteAddr":"172.17.42.1","app":"core","message":"Can't get app storage, app files_external, user not logged in","level":3,"time":"2015-06-16T08:55:16+00:00"}
{"reqId":"R5MJ4RMLSvyRQeUnCCI4","remoteAddr":"172.17.42.1","app":"core","message":"Can't get app storage, app files_external, user not logged in","level":3,"time":"2015-06-16T08:55:16+00:00"}
{"reqId":"vWZ6Pp3T9t9gg8g32jMt","remoteAddr":"172.17.42.1","app":"core","message":"Can't get app storage, app files_external, user not logged in","level":3,"time":"2015-06-16T08:55:16+00:00"}
{"reqId":"vWZ6Pp3T9t9gg8g32jMt","remoteAddr":"172.17.42.1","app":"core","message":"Can't get app storage, app files_external, user not logged in","level":3,"time":"2015-06-16T08:55:16+00:00"}
```


No idea why those errors about external storage appears, because SFTP folder is correctly mounted and working.

**Comment by PVince81** [comment]
Thanks, I'll have a look.

**Comment by PVince81** [comment]
This is what I see during webdav delete (I shared s2s with the same server):
```
{"reqId":"PiWE\/JaIiq8X7BUbWpGK","remoteAddr":"127.0.0.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#1 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_sharing\\\/publicwebdav.php(92): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/public.php(75): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#7 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2015-06-16T09:24:41+00:00","method":"PROPFIND","url":"\/owncloud\/public.php\/webdav\/"}
{"reqId":"ifCwq69GvOglFyHN\/8XV","remoteAddr":"127.0.0.1","app":"core","message":"Can't get app storage, app files_external, user not logged in","level":3,"time":"2015-06-16T09:24:41+00:00","method":"PROPFIND","url":"\/owncloud\/public.php\/webdav\/"}
{"reqId":"ifCwq69GvOglFyHN\/8XV","remoteAddr":"127.0.0.1","app":"core","message":"Can't get app storage, app files_external, user not logged in","level":3,"time":"2015-06-16T09:24:41+00:00","method":"PROPFIND","url":"\/owncloud\/public.php\/webdav\/"}
{"reqId":"fmo1oY6ixy+xhcBAm6NK","remoteAddr":"127.0.0.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#1 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_sharing\\\/publicwebdav.php(92): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/public.php(75): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#7 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2015-06-16T09:24:41+00:00","method":"PROPFIND","url":"\/owncloud\/public.php\/webdav\/"}
{"reqId":"vD+uSOCDzzY9a0GCRPHm","remoteAddr":"127.0.0.1","app":"core","message":"Can't get app storage, app files_external, user not logged in","level":3,"time":"2015-06-16T09:24:42+00:00","method":"PROPFIND","url":"\/owncloud\/public.php\/webdav\/"}
{"reqId":"vD+uSOCDzzY9a0GCRPHm","remoteAddr":"127.0.0.1","app":"core","message":"Can't get app storage, app files_external, user not logged in","level":3,"time":"2015-06-16T09:24:42+00:00","method":"PROPFIND","url":"\/owncloud\/public.php\/webdav\/"}
{"reqId":"0\/uz4obSYW1hjw+hA+ht","remoteAddr":"127.0.0.1","app":"PHP","message":"Undefined offset: 3 at \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/view.php#257","level":3,"time":"2015-06-16T09:24:42+00:00","method":"DELETE","url":"\/owncloud\/remote.php\/webdav\/SUBDIR\/"}
{"reqId":"wZNLUMuuuiDffHB1ks4I","remoteAddr":"127.0.0.1","app":"core","message":"Can't get app storage, app files_external, user not logged in","level":3,"time":"2015-06-16T09:24:42+00:00","method":"POST","url":"\/owncloud\/ocs\/v1.php\/cloud\/shares\/1\/decline?format=json"}
{"reqId":"wZNLUMuuuiDffHB1ks4I","remoteAddr":"127.0.0.1","app":"core","message":"Can't get app storage, app files_external, user not logged in","level":3,"time":"2015-06-16T09:24:42+00:00","method":"POST","url":"\/owncloud\/ocs\/v1.php\/cloud\/shares\/1\/decline?format=json"}
```

And the webdav upload:
```
{"reqId":"rKcgIqZWl\/nMFSRrbdyO","remoteAddr":"127.0.0.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 files\\\/ae70f992fdedf2730cd61d7801e5764a is locked\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php(111): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #258)\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('test8.txt', Resource id #258)\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('test8.txt', Resource id #258, NULL)\\n#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/remote.php(84): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#9 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":198}","level":4,"time":"2015-06-16T09:26:13+00:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/test8.txt"}
```

This is on master (7d8b728066987bd312b3225eff6cff67ca6a610a)

Two issues:
1) Cannot upload due to lock
2) The mysterious message "{"reqId":"wZNLUMuuuiDffHB1ks4I","remoteAddr":"127.0.0.1","app":"core","message":"Can't get app storage, app files_external, user not logged in","level":3,"time":"2015-06-16T09:24:42+00:00","method":"POST","url":"\/owncloud\/ocs\/v1.php\/cloud\/shares\/1\/decline?format=json"}"
3) Any why is it calling OCS with decline ?! The share has been mounted, no reason to decline the share.

Let's focus on 1)

**Comment by PVince81** [comment]
Note: the SFTP storage was mounted as personal mount, not system-wide mount.

@icewind1991 any comment on "Can't get app storage, app files_external, user not logged in" ?

**Comment by PVince81** [comment]
The locked issue from 1) is fixed in this PR: https://github.com/owncloud/core/pull/16955

**Comment by icewind1991** [comment]
> any comment on "Can't get app storage, app files_external, user not logged in" ?

Sounds s2s related, @schiesbn ?

**Comment by SergioBertolinSG** [comment]
Tested on 8.1.0RC2, still happening.

**Comment by PVince81** [comment]
PRs https://github.com/owncloud/core/pull/17268 and https://github.com/owncloud/core/pull/17282.
Will be backported later to 8.1 branch for 8.1.1.
So let's keep this ticket open still.

**Comment by MorrisJobke** [comment]
Only the backport of #17282 is missing :)

**Comment by PVince81** [comment]
and here it is https://github.com/owncloud/core/pull/17710

**Comment by MorrisJobke** [comment]
Changing the milestone. The backport PR is in 8.1.1 -> I will add the brown labels later.
