### ISSUE TITLE
Users shall not be able to gain a list of other users on the instance

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#16907]
As a privacy advocate, I do not want any user within ownCloud to be able to enumerate ownCloud users on this instance easily, such as in the sharing dialog, so that I can protect the privacy and email addresses of users within the ownCloud system.

Acceptance Criteria:
- Should be a simple configuration switch that disables user type ahead searching

**Comment by MTRichards** [comment]
@LukasReschke @karlitschek

**Comment by LukasReschke** [comment]
Thanks for creating a new issue, Matt.

**Comment by PVince81** [comment]
we already have a flag for autocomplete, closing
