### ISSUE TITLE
Upgrade to 8.0.4 broken: invalid syntax of SQL queries

### ISSUE THREAD

**Issue by pauleve** [owncloud/core#16901]
During upgrading to 8.0.4, the following message occurs:

  An exception occurred while executing 'CREATE INDEX 99mgrj5kk9o04 ON filecache_83shkm6zbxwgy ("parent", "name")': SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "99" LINE 1: CREATE INDEX 99mgrj5kk9o04 ON filecache_83shkm6zbxwgy ("pare... ^

I'm running owncloud with a postgresql database - which apparently doesn't support index names starting with numbers. Let me know how to fix this... Thanks

**Comment by LukasReschke** [comment]
> I'm running owncloud with a postgresql database - which apparently doesn't support index names starting with numbers. Let me know how to fix this... Thanks

Please apply https://github.com/owncloud/core/pull/16815
