### ISSUE TITLE
Owncloud 8.x with ceph s3 - path style doesn't work.

### ISSUE THREAD

**Issue by subodhkant** [owncloud/core#16916]
Hi Team,

I am trying to connect Owncloud 8.x  with ceph s3 storage. I am not able to connect. when i see the log files, it's (OC) trying to access s3 bucket by http://bucketname.hostname_of_RadowsGW and its not able to resolve it. I click on the "enable path style URL" option but still it's trying to access s3 bucket by http://bucketname.hostname only.

My ceph s3 bucket is able to access by web browser by using http://hostname/bucketname. In case of "path style" , what i understand, the owncloud should access s3 bucket by http://hostname/bucketname .

But owncloud is trying to access s3 bucket by http://bucketname.hostname only in case of "path style" also.

Please help on this to resolve this issue.

Thnaks
SK

**Comment by LukasReschke** [comment]
Thanks a lot for reporting issues back to us!

We need some more information to properly support you with your issue!

Can I ask you to follow our guidelines for submitting bugs as described here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by karlitschek** [comment]
It seems that you use the Enterprise edition. Please contact the ownCloud support for further assistance. Thanks

**Comment by RealRancor** [comment]
@karlitschek Do trial users getting enterprise support? The user is doing an evaluation of the enterprise edition so we have pointed him here:

https://forum.owncloud.org/viewtopic.php?f=31&t=28746#p89312

as we can't give support for the EE at the forums.

**Comment by karlitschek** [comment]
Yes. They should always work with the EE support when doing an EE trial.

**Comment by subodhkant** [comment]
Thank you Karlitschek, RealRancor,

I am trying to contact OC support but response is very slow. Can you please suggest quick solution for this issue.

**Comment by bboule** [comment]
@subodhkant I am a member of the ownCloud support team, in order to assist you we will need a little more information to help troubleshoot.  If you could send us your contact info to support@owncloud.com and I will make sure you request gets to the correct support channel and that you are contacted straight away!

Thanks,

ownCloud Support

**Comment by MorrisJobke** [comment]
cc @michaelstingl @cdamken @pako81

**Comment by RealRancor** [comment]
Hi,

i don't know if this is really related but a user had posted some code/patches for path style stuff at the forums:

https://forum.owncloud.org/viewtopic.php?f=31&t=27989#p86665

Unfortunately he didn't posted this on github yet after asking him.

**Comment by MorrisJobke** [comment]
owncloud/objectstore#25

**Comment by bboule** [comment]
@subodhkant it looks like @MorrisJobke has pointed you in the direction above, please let us know if you need any additional information.

**Comment by RealRancor** [comment]
@bboule I don't know github and the private repositories that much but the OP probably don't have access to the linked issue above.

**Comment by MorrisJobke** [comment]
> @bboule I don't know github and the private repositories that much but the OP probably don't have access to the linked issue above.

Yes. Should be handled internally only. Sorry. These are enterprise apps that are closed source :(

I think this needs to be communicated over the usual support channels to the customer directly.

@RealRancor Mostly the linked PR is just the fix from the forum. But with a different solution.

**Comment by MorrisJobke** [comment]
@RealRancor But anyway: Thanks for the pointer to the forum :)

**Comment by RealRancor** [comment]
@MorrisJobke No need to say sorry, just wanted to point out that the OP has probably no chance to open that URL.

> Mostly the linked PR is just the fix from the forum. But with a different solution.

Good to know so will give a short note for this at the forums. Unfortunately such patches or possible bugs are floating quite often at the forums where a user didn't managed to report it here even he was pointed / asked to report it.

**Comment by MorrisJobke** [comment]
> Good to know so will give a short note for this at the forums. Unfortunately such patches or possible bugs are floating quite often at the forums where a user didn't managed to report it here even he was pointed / asked to report it.

The weird thing is, that this doesn't got into the support chain. I will ask our support team for this specific case.

**Comment by RealRancor** [comment]
> The weird thing is, that this doesn't got into the support chain. I will ask our support team for this specific case.

Do you mean the request of the OP here or the forum posting at https://forum.owncloud.org/viewtopic.php?f=31&t=27989

The second wasn't an EE user so this can't reach the support team.
