### ISSUE TITLE
Issues migrating 704 to 804... database

### ISSUE THREAD

**Issue by githubos1** [owncloud/core#16918]
after several issues trying to automatically (by app) migrate from 704 to 804 (at my poviders KAS - ALL-INKL account) I'm, finally trying to find a way to manually or automatically migrate just the SQL database from 704 to 804. Next to my original 704 installation I have by now installed a brand new 804 version, but I guess just importing the 704 dsql database into the new 804 database will fail...  right ??

Thank's for any support in this matter,

Oliver

**Comment by RealRancor** [comment]
Hi,

as this doesn't look like a bug please have a look at:

https://owncloud.org/support/

where to ask for support.
