### ISSUE TITLE
Merging folders on web interface

### ISSUE THREAD

**Issue by colmoneill** [owncloud/core#16932]
## feature request?

Is there a way, or could there be a way of merging folders when they are selected like this:

![screenshot from 2015-06-15 11 14 01](https://cloud.githubusercontent.com/assets/2122318/8156777/b34aeb86-134f-11e5-9ce8-5835709dea0a.png)

When I search for 'merge' or 'merging' or 'folder merging' in the issues, I don't find anything corresponding, hope I'm not duplicating.

Thanks!

**Comment by PVince81** [comment]
Merging folders in what way ? Can you elaborate ?

**Comment by colmoneill** [comment]
This originates from an installation of oC I did for a customer needing to *manage*, **sort** and share files and folders. While they use the desktop sync client to keep some folders locally, the main archive (and majority of the bulk content) is on server and they only access it through the web interface. Therefor, there is a need for more advanced folder and file manipulation.

![screenshot from 2015-06-15 11 50 42](https://cloud.githubusercontent.com/assets/2122318/8157460/31e89ba0-1355-11e5-8bba-9877f59b77d8.png)
  
&uarr; I added a verbose 'merge' button beside the download, because I would imagine it being at that level of interaction. A fundamental action such as 'download'.

The order I imagine would be:
- select two or more folders
- click 'merge folders'
- be brought to the folder rename function as if I clicked the edit pencil beside the name of a file or folder.

I find oC to be super powerful for sync and share, but basic file and folder navigation could be enhanced. For an other example, moving a file out of a folder, then into an other one is very complicated, and impossible without a desktop sync client right? In this case, to do some re-organisation of an archived folder, the user would have to re select it in their desktop sync app, wait for it to entirely download locally, do changes in organization, then unselect it again to free space on the local drive.

Again, this is mentioned as a request, oC does millions of things brilliantly, that's what makes it so easy to dream and wish it could do even more :)

**Comment by PVince81** [comment]
I still don't understand what is supposed to happen when you click "merge". Can you describe the steps in detail ?

Should the contents of "test2" (and any other folder) be moved into "test" ?

The web UI does lack some advanced drag and drop features.

**Comment by colmoneill** [comment]
Yes, that is what I'd imagine:

- multi-select folders from the files view
- as long as items selected are folders, display the option to merge
- probably a need for warning message, we can't allow a user to merge a shared folder with an unshared folder for example
- when 'merge' is selected, all the content from each folder is moved to one combined view of all the content, with the condition of naming (renaming?) this (new?) folder
- old folders disappear to the vantage of the new combined content folder.

I guess drag and drop could be the interface for this.

**Comment by PVince81** [comment]
This already seems quite advanced, even regular desktop file managers do not have such feature. The "merge" feature is probably a good candidate for a separate app.

However I think improving the drag and drop situation is something that needs to be worked on, see https://github.com/owncloud/core/issues/10656 and https://github.com/owncloud/core/issues/8570

**Comment by colmoneill** [comment]
Thanks for the references, drag and drop is indeed probably the more logical first step in this direction.

**Comment by DeepDiver1975** [comment]
> Thanks for the references, drag and drop is indeed probably the more logical first step in this direction.

closing therefore - THX
