### ISSUE TITLE
LDAP Scope

### ISSUE THREAD

**Issue by smalchow** [owncloud/core#16933]
We are experiencing the problem that depending on the BaseDN that is used when carrying out ldap search we get answers or we dont.
I tested the following with everything configured, set the "Base User Tree" to "dc=domain,dc=com" and the User Filter to "(objectclass=inetOrgPerson)" and there are 0 users found, when i set the "Base USer Tree" to "ou=Organizational Unit,ou=internal,dc=domain,dc=com" (only change) i get 15 users, the users are in "ou=Users,ou=Organizational Unit,ou=internal,dc=domain,dc=com".

On the LDAP server the queries from owncloud look like this

base="dc=domain,dc=com" scope=2 filter="(&(objectClass=inetOrgPerson)(cn=*))" attrs="distinguishedName"

or

base="ou=Organizational Unit,ou=internal,dc=domain,dc=com" scope=2 filter="(&(objectClass=inetOrgPerson)(cn=*))" attrs="distinguishedName"

the second one works, the first one not, even though the scope indicates a subtree search.

If i execute

#> ldapsearch -H ldaps://LDAPSERVER:636 -D uid=BINDDN -b "dc=domain,dc=com" -s sub -W '(&(|(objectClass=inetOrgPerson))(cn=*))' 'distinguishedName'

I get 15 users as expected.

Somehow it looks as if there is a problem with the scope.

I have the following installed

owncloud 8.0.4 on CentOS 7.1 (all patches applied)
389-ds 1.3.3 on CentOS 7.1 (latest patches applied)

Cheers
Soeren

**Comment by PVince81** [comment]
@blizzz

**Comment by blizzz** [comment]
Well, the positive thing is that the more narrow base works, not the wider one ;)

The scope is correct as reported by your LDAP server, we also do not change methods based on the provided Base DNs. In PHP you define the scope by using dedicated methods (ldap_search, ldap_list and ldap_read). Currently I would not do why this is happening. In the LDAP log, did your server say it was returning results with the broad DN or did it already reply with none?

Were you able to reproduce it? Did you see any LDAP errors reported?

**Comment by blizzz** [comment]
Also, can you please provide reproduction steps.

**Comment by smalchow** [comment]
Hi,

for us the reproduction is very easy, when we search with the baseDN only "dc=domain,dc=com" then we get 0 results, when we search with a OU below that as base (ou=Unit,dc=domain,dc=com" then i get results, this is, when the users are in "ou=Users,ou=Orgunit,ou=Orgunit,dc=domain,dc=com" (yes, 2 levels orgunit) when i do the same query with ldapsearch on the commandline i get proper results in both cases.

Regards
Soeren

**Comment by blizzz** [comment]
> base="dc=domain,dc=com" scope=2 filter="(&(objectClass=inetOrgPerson)(cn=*))" attrs="distinguishedName"

Was your LDAP log reporting results when this was triggered via ownCloud?

Did you see any LDAP errors reported (either LDAP or ownCloud log)?

**Comment by cmonteroluque** [comment]
@smalchow did you have a chance to look at @blizzz's questions? Any update on your side? We'd love to get this resolved rather than keep moving the milestone forward

**Comment by smalchow** [comment]
Sorry, i missed the question (holidayseason). 
No, it was not reporting results and i did not see any errors.

Due to this fact we already had to change our setup and we are using our Active Directory as a backend now, in case of the AD we have no problem whereever we set the BAseDN.But we also already upgraded to owncloud 8.1.1
