### ISSUE TITLE
8.1 fails on Debian 8.0

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#16936]
Debian 8.0 has a stronger linitan checker. The following errors are reported as fatal:

<pre>
[  116s] E: owncloud source: source-is-missing core/vendor/zxcvbn/zxcvbn.js
[  117s] E: owncloud source: source-is-missing apps/files_videoviewer/js/flashmediaelement.swf
[  118s] E: owncloud source: source-is-missing core/doc/user/_static/underscore.js
[  118s] E: owncloud source: source-is-missing core/doc/user/_static/jquery.js
[  118s] E: owncloud source: source-is-missing core/doc/user/_static/bootstrap.js
[  118s] E: owncloud source: source-is-missing core/doc/admin/_static/underscore.js
[  118s] E: owncloud source: source-is-missing core/doc/admin/_static/jquery.js
[  118s] E: owncloud source: source-is-missing core/doc/admin/_static/bootstrap.js
[  119s] E: owncloud source: license-problem-json-evil 3rdparty/mrclay/minify/min/lib/JSMin.php
[  119s] E: owncloud source: license-problem-json-evil apps/files_texteditor/js/vendor/ace/src-noconflict/worker-javascript.js
[  119s] E: owncloud source: source-is-missing apps/files_texteditor/js/vendor/ace/src-noconflict/mode-autohotkey.js
[  119s] E: owncloud source: source-is-missing apps/files_texteditor/js/vendor/ace/src-noconflict/mode-actionscript.js
[  119s] E: owncloud source: source-is-missing apps/files_texteditor/js/vendor/ace/src-noconflict/ext-elastic_tabstops_lite.js
</pre>

Seen e.g. in https://build.opensuse.org/package/live_build_log/isv:ownCloud:community:nightly/owncloud/Debian_8.0/x86_64

@DeepDiver1975 Is this something we can resolve in the sources?
This currently prevents the build of Linux packages for Debian 8.0

**Comment by DeepDiver1975** [comment]
@jnweiger there are capabilities to sub-press lintian errors

**Comment by DeepDiver1975** [comment]
https://lintian.debian.org/manual/section-2.4.html

**Comment by jnweiger** [comment]
owncloud source: source-is-missing
seems to have no effect in debian.owncloud.lintian-overrides
Local builds succeed. OBS builds fail.

**Comment by jnweiger** [comment]
Debian 8.0 is not a supported platform.
Issues from their lintian are interesting mainly for improving code quality. 
The supress mechanism suggested above hide the issues. I'd rather have them as warnings. :-(

**Comment by DeepDiver1975** [comment]
> owncloud source: source-is-missing
> seems to have no effect in debian.owncloud.lintian-overrides

as example see: http://anonscm.debian.org/viewvc/pkg-games/packages/trunk/0ad/debian/source/lintian-overrides?view=markup

**Comment by DeepDiver1975** [comment]
> Debian 8.0 is not a supported platform.

It will soon-ish be released and we shall have working packages by then

**Comment by DeepDiver1975** [comment]
> Issues from their lintian are interesting mainly for improving code quality.

not really for source-is-missing, because we would need to totally revamp our source tar balls.

What we basically would need to do is ship the javascript source code (could be unminified code or even coffee script which requires a build step) which will render the tarballs unusable for plain drop-in-deployments.

**Comment by jnweiger** [comment]
@DeepDiver1975 Thanks for the review. 
Lintian rules added, so that it succeeds on Debian 8
