### ISSUE TITLE
Allow Multiple authentication backends

### ISSUE THREAD

**Issue by butonic** [owncloud/core#16939]
In bigger installations it happens frequently that an active directory is used as the identity provider. with user_shibboleth and user_ldap there are two ways of interacting with that idp. Currently, user_ldap detects when a uid is already in use and will append a random number to prevent uid collisions when multiple backends are used. this is a safeguard against malicious admins who could otharwise create local db users with the same uid and gain access to users files.

With an idp it actually makes sense to configure them to resolve to the same uid. Taking this a step further there are other authentication backends like apache authz, pam, oauth, facebook, twitter or smartcard systems that might be used to authenticate a user. the question is what parts of oc ned to change to make this possible.

The easy solution would be to just allow uid collisions, or allow collisions with a config option.

@LukasReschke @DeepDiver1975 @blizzz @bboule thoughts?

**Comment by karlitschek** [comment]
agreed. this is discussed at the moment for 8.2
@mtrichards

**Comment by DeepDiver1975** [comment]
Taking the ideas for 8.2 one step further:
This basically points to the idea where a user can have multiple authentication mechanisms assigned.

We would then basically talk about an account which is the single identity of a user (including a uid, full name, email, group assignments etc.) this is the instance which has a data directory assigned etc.

This account can then be linked to
- a LDAP identify 
- an eppn in terms of shibboleth
- a simple user/password challenge
- multiple tokens (api keys etc)
- and any other authentication system integrated into ownCloud

**Comment by MTRichards** [comment]
And encryption works...

**Comment by MTRichards** [comment]
This would be excellent, to allow not only multiple authentication mechanisms, but also the mapping of a username to an eppn, for example, so that user groups can be pulled as well in tandem with shibboleth, for example.

**Comment by bboule** [comment]
Guys I think we can close this as I think this is the WR app which is now part of the product?

**Comment by MTRichards** [comment]
I do think so, but want to confirm.
@butonic can you confirm this is in core now?

**Comment by butonic** [comment]
no @DeepDiver1975 and I were gathering this as an idea for future refactorings ... AFAIK @LukasReschke also has some ideas on how user backends should work.

The resolves_blue ticket can be removed though.

**Comment by butonic** [comment]
well no ... https://github.com/owncloud/enterprise/issues/879 still wants to be fixed

**Comment by bboule** [comment]
Changed to green ticket to reference  owncloud/enterprise#879  @CaptionF is this a feature request is it in SFDC?

**Comment by butonic** [comment]
clients can use tokens, user_shibboleth has sso-only mode. closing
