### ISSUE TITLE
Introduce release "channels" in the app store

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#16934]
As an app developer, I'd like to be able to push pre-releases of apps to people who are willing to test new features without having to use git.
- App developer select appropriate channel for a release: stable, beta, alpha
- User sets the channel for each app
- Apps are updated using the release channel chosen by the user

**Comment by karlitschek** [comment]
completely agreed. this is definitely something that we want to have in the future

**Comment by jab416171** [comment]
It would be sweet if Travis could automatically publish the latest code on develop to the alpha channel.

**Comment by PVince81** [comment]
raised https://github.com/owncloud/marketplace-issues/issues/14
