### ISSUE TITLE
General Housekeeping/Cleanup requests

### ISSUE THREAD

**Issue by jab416171** [owncloud/core#16930]
As I've been using ownCloud, I've noticed that there's a lot of cruft left over when files get deleted/moved/renamed/etc. For instance, the versions and encryption apps keeps versions/keys of deleted files, thumbnails don't get cleaned up, and there's records in the database that are left over when a file gets deleted or moved/renamed. I've also seen failed uploads left around in the cache folder. That makes me wonder what happens when I delete a file, and then later recreate a file with the same name/path but different contents. 

I think there should be an occ command, or a cron, or maybe even build parts of it into the versions/trashbin/encryption apps to periodically clean up leftover junk that's just taking up space and slowing down ownCloud. If I have an ownCloud install that's a year old, and one that's a day old, and they both have the same files in them right now but maybe the first one had a bunch of stuff added/deleted/moved around/etc, they should look very similar today in terms of disk usage and database row counts. My database/disk should not grow over time if there aren't any net new files.

**Comment by RealRancor** [comment]
Hi,

at least the garbage collection of chunks is discussed here: https://github.com/owncloud/core/issues/14646

I don't know if it will help but for the other stuff you can check if you're using Cron like described here:

https://doc.owncloud.org/server/8.0/admin_manual/configuration_server/background_jobs_configuration.html#cron

which should do some garbage collection.

**Comment by PVince81** [comment]
In the case of encryption and versions, there were many bugs in the past where versions were not moved properly or keys were not properly deleted. Hopefully this should all be solved already in the upcoming 8.1.

**Comment by jab416171** [comment]
@RealRancor Thanks, I did look through that issue before posting that one. I am using the owncloud cron, however, as far as I've noticed, it doesn't address any of the concerns that I mentioned.

**Comment by PVince81** [comment]
Yes, and there also will not be any cleanup job for stray versions and keys, because this situation is not supposed to happen. If it does, then it's a bug that needs to be fixed.
Do you still see new stray files appearing in files_versions or encryption keys when using 8.0.4 ?
If yes, might be worth having a look at it to find out what bug is causing it.

For the upload chunks, this ticket https://github.com/owncloud/core/issues/14646 is the plan to make ownCloud's cron cleanup chunks in the future.

**Comment by PVince81** [comment]
Note: a repair step could also be written that cleans up stray junk during update, in case the bug that was causing them was fixed in the next version.

**Comment by jab416171** [comment]
I have stray versions and keys for files that have been deleted.

**Comment by PVince81** [comment]
How old ? To find out whether it's old from OC 5 - OC 6 or if it's quite recent.
If very recent, might be a still existing bug.

**Comment by jab416171** [comment]
I've never used anything other than OC8. They're from the current version.

**Comment by PVince81** [comment]
OC 8.0.4 I assume ?

Then we need to find out the steps that leaves such stray files, whether it's deleting or renaming.

In 8.1 a few such bugs have been fixed, so it is likely that it will not happen any more in 8.1.
But finding out the steps could still help knowing if it is one of the fixed bugs or new ones.

**Comment by jab416171** [comment]
Yeah, 8.0.4. I was on 8.0.3 when I was seeing this, but in the short amount of time I've spent testing, I don't think I've seen it. Were there fixes in 8.0.4 for this?

**Comment by PVince81** [comment]
Not that I'm aware off. Most of the known fixes I mentioned are in 8.1.

**Comment by PVince81** [comment]
@jab416171 did you find any stray files in the latest versions ? There shouldn't be any.
If you're talking about part files or chunks, then see https://github.com/owncloud/core/issues/16570

If you're still having stray files about move/rename in 8.1.3 or 8.2RC1, feel free to reopen.
