### ISSUE TITLE
Desktop application move issue.

### ISSUE THREAD

**Issue by Grevous** [owncloud/core#16946]
So here is the issue, when moving a file in owncloud from a non admin client. There is a chance of duplicating the file. 

I started by moving a test file to a sub folder (see duplication1.png), which resulted in a successful move. 
![duplication1](https://cloud.githubusercontent.com/assets/12898260/8165056/80ed2636-134a-11e5-9c52-e62833ebbb63.png)

I then proceeded to move the image again to the folder try_moving_again (see duplication2.png). 
![duplication2](https://cloud.githubusercontent.com/assets/12898260/8165059/85875176-134a-11e5-8d93-3f54a15aa097.png)

This appears to show it moving successfully again waiting for the sync to occur. When it does duplication3.png occurs. 
![duplication3](https://cloud.githubusercontent.com/assets/12898260/8165065/8a1841e6-134a-11e5-9e65-f459672b286c.png)

The file is synced in its current directory and waiting to sync in the folder i wished to move it to. It is still waiting to sync. The only way to finish it is to pause and resume the sync.

On one of these attempts I noticed the file contents itself where edited. See instanceOfDataLossOne and Two.
![instanceofdatalossone](https://cloud.githubusercontent.com/assets/12898260/8165072/978d3854-134a-11e5-9039-bebf29ca472f.png)

![instanceofdatalosstwo](https://cloud.githubusercontent.com/assets/12898260/8165074/9bfc245e-134a-11e5-8a24-3c9db07f3396.png)

Any Ideas?

**Comment by Grevous** [comment]
Oh, forgot build info, 
Version 1.8.1(build 2335)

**Comment by karlitschek** [comment]
Can you open this to the clients repository please? thanks

**Comment by Grevous** [comment]
Oh sorry, I'll set it up over there then.
