### ISSUE TITLE
Cron unexpected error

### ISSUE THREAD

**Issue by belzebubek** [owncloud/core#16945]
Debian wheezy, ownCloud 8.0.4-0 stable.
Cron started to send me below messages, help would be appreciated:

PHP Fatal error:  Call to a member function file_exists() on a non-object in /var/www/owncloud/lib/private/files/filesystem.php on line 630
PHP Stack trace:
PHP   1. {main}() /var/www/owncloud/cron.php:0
PHP   2. OC\BackgroundJob\TimedJob->execute() /var/www/owncloud/cron.php:138
PHP   3. OC\BackgroundJob\Job->execute() /var/www/owncloud/lib/private/backgroundjob/timedjob.php:38
PHP   4. OCA\user_ldap\lib\Jobs->run() /var/www/owncloud/lib/private/backgroundjob/job.php:36
PHP   5. OCA\user_ldap\lib\Jobs::updateGroups() /var/www/owncloud/apps/user_ldap/lib/jobs.php:43
PHP   6. OCA\user_ldap\lib\Jobs::handleKnownGroups() /var/www/owncloud/apps/user_ldap/lib/jobs.php:59
PHP   7. OCP\Util::emitHook() /var/www/owncloud/apps/user_ldap/lib/jobs.php:97
PHP   8. OC_Hook::emit() /var/www/owncloud/lib/public/util.php:365
PHP   9. call_user_func() /var/www/owncloud/lib/private/hook.php:78
PHP  10. OC\Share\Hooks::post_addToGroup() /var/www/owncloud/lib/private/hook.php:78
PHP  11. OC\Share\Helper::generateTarget() /var/www/owncloud/lib/private/share/hooks.php:64
PHP  12. OC_Share_Backend_File->generateTarget() /var/www/owncloud/lib/private/share/helper.php:74
PHP  13. OCA\Files_Sharing\Helper::getShareFolder() /var/www/owncloud/apps/files_sharing/lib/share/file.php:69
PHP  14. OC\Files\Filesystem::file_exists() /var/www/owncloud/apps/files_sharing/lib/helper.php:262
Unexpected error!

**Comment by RealRancor** [comment]
Hi,

seems the cron error was also reported here: https://github.com/owncloud/core/issues/16740

**Comment by belzebubek** [comment]
Duplcate. Thanks
