### ISSUE TITLE
LDAP: play nicely with dead LDAP servers served by Round Robin DNS

### ISSUE THREAD

**Issue by blizzz** [owncloud/core#16958]
You have a set of LDAP servers reachable under a single domain (ldap.example.com). Via DNS Round Robin ownCloud will connect to one of them, but never the same. Also, some LDAP servers might be dead/offline while they are not being removed from the pool. 

Currently (tested 8.0.3), ownCloud will hang desperately, as an odd server will not respond. A timeout on the observed setups would be terribly big (unlike usual HTTP or LDAP 60s). The running request is blocking and might cause weird side effects.

What we need to do is to check whether the host is really alive before throwing LDAP calls on it. A possible approach: https://php.net/manual/de/function.ldap-connect.php#115662

cc @butonic

**Comment by foobarable** [comment]
It is bad practise to use DNS Round Robin for high availability (for the reasons you named). 
We solved this issue by connecting to a haproxy instead of the ldap servers directly.

**Comment by Xenopathic** [comment]
@blizzz you might want to see how we solved this problem for unavailable external storages: https://github.com/owncloud/core/blob/master/lib/private/files/storage/wrapper/availability.php

**Comment by PVince81** [comment]
@butonic please reopen in user_ldap repo if there is still interest in having this
