### ISSUE TITLE
[Admin > User panel] Intead of Quota "Standard" show Quota "xx GB (Standard)" size

### ISSUE THREAD

**Issue by Wikinaut** [owncloud/core#16953]
On the User admin panel, I see a meaningless "Standard" Quota information, but this does not indicate the size.

Output should be changed to show the correct current size value, perhaps in the Form "2 GB (Standard)" (proposed).

**Comment by DeepDiver1975** [comment]
@Wikinaut thanks a lot for your suggestion - I'm putting this to the backlog - contributions to fix this are welcome any time. THX

**Comment by Wikinaut** [comment]
@DeepDiver1975 allow me a clarification request (instead of opening just another issue).

Where is the "Standard" quota value defined, I could **not** find such a parameter/value pair (1 GB on my server) in config/config.php or in the apps/files directory. 

It is my view, that not only the current value should be printed (subject of this enhancement issue), but that the standard value should be configurable via the config.php settings.
