### ISSUE TITLE
Metadata for file types in external storage #markdown #metadata

### ISSUE THREAD

**Issue by stampf** [owncloud/core#16950]
I have an file.md inside an external storage (Dropbox), but when I click it, it is downloaded, not opened in the editor (in owncloud-markdown).
MD files in normal ownCloud are edited properly, as well as .txt files inside Dropbox.

I have ownCloud 8.0.2 and latest version of owncloud-markdown as well.

Could it be that we can activate some predefined file types in external editors so the behavior works as expected?

**Comment by DeepDiver1975** [comment]
> I have ownCloud 8.0.2 and latest version of owncloud-markdown as well.

maybe something to talk to the developer of owncloud-markdown?

**Comment by stampf** [comment]
He sent me here: the problem is that Dropbox doesn't send the correct mime type thus owncloud doesn't launch the proper application to open it.

**Comment by DeepDiver1975** [comment]
> He sent me here: the problem is that Dropbox doesn't send the correct mime type thus owncloud doesn't launch the proper application to open it.

Thanks - very valuable input.

@icewind1991 we shall address this within 8.2 as soon as we start pushing dropbox integration. THX

**Comment by stampf** [comment]
I haven't read your code, but it's probably endemic to all external storage? That would probably mandate having an equivalent /etc/mime-types inside owncloud... How to do it gracefully is key IMHO :) Especially when one sees the huge list available at IANA: http://www.iana.org/assignments/media-types/media-types.xhtml.

As they say in "Mission: impossible": good luck, Jim ;-)

**Comment by PVince81** [comment]
Another idea is to disable reading mimetype from Dropbox and simply use ownCloud's own mimetype detection.

**Comment by cmonteroluque** [comment]
external storage work

**Comment by PVince81** [comment]
As per 9.0, the mime type for Dropbox is read from ownCloud, not Dropbox.

See https://github.com/owncloud/core/pull/19758
