### ISSUE TITLE
NaN label appears when trying to count users after creating a new one.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16954]
### Steps to reproduce

1. As an admin go to users page.
2. Create a new user. 

### Expected behaviour
A number.

### Actual behaviour
Not a number.

![screen shot 2015-06-16 at 11 25 42](https://cloud.githubusercontent.com/assets/9048796/8180030/5b1a9b74-141b-11e5-8918-b4804c0cdc18.png)

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Windows network drive.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
WND.

**Are you using encryption:** 
No.

**Logs**
```

```

### Client configuration

**browser**
Firefox

**Comment by nickvergessen** [comment]
https://github.com/owncloud/core/issues/16876

**Comment by nickvergessen** [comment]
And PR: https://github.com/owncloud/core/issues/16889
