### ISSUE TITLE
OC8.0.4 Mail notification for yesterday with today content

### ISSUE THREAD

**Issue by PhilJung** [owncloud/core#16962]
Hi, 

### Actual behaviour

A user received this message:

> Hello XXXX,
>
> You receive this mail because YESTERDAY activity happened on /
> You deleted xxxxx - Today 10:41:19

Moreover, in french notification mail, the ' char is encoded:
`Vous recevez ce courriel car hier l&#039;activité suivante a eu lieu sur /`

### Expected behaviour

No data from today in yesterday summary
No encoded char

### Server configuration
**Operating system**: CentOS 6.6

**Web server:** Apache 2.2.15

**Database:** MySQL

**PHP version:**  5.4.41

**ownCloud version:** (see ownCloud admin page) 8.0.4.2

**Updated from an older ownCloud or fresh install:** updated

**List of activated apps:**  
Activity 1.2.0
Deleted files 0.6.2
File Locking 
LDAP user and group backend 0.5.0
Mail Template Editor 0.1
PDF Viewer 0.7
Pictures 0.6.0
Provisioning API 0.2
Share Files 0.6.1
Text Editor 0.4
Versions 1.0.5
Video Viewer 0.1.3

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => '_secret_',
  'version' => '8.0.4.2',
  'installed' => true,
  'adminlogin' => '_secret_',
  'adminpass' => '_secret_',
  'dbtype' => 'mysql',
  'dbname' => 'owncloud',
  'dbuser' => '_secret_',
  'dbpassword' => '_secret_',
  'dbhost' => '_secret_',
  'dbtableprefix' => 'oc_',
  'passwordsalt' => '_secret_',
  'forcessl' => false,
  'blacklisted_files' => 
  array (
    0 => '.htaccess',
  ),
  'overwritehost' => '',
  'overwriteprotocol' => '',
  'overwritewebroot' => '',
  'overwritecondaddr' => '',
  'proxy' => '',
  'proxyuserpwd' => '',
  'trusted_domains' => 
  array (
    0 => '_secret_',
    1 => '_secret_',
  ),
  'theme' => '',
  'default_language' => 'fr',
  '3rdpartyroot' => '',
  '3rdpartyurl' => '',
  'defaultapp' => 'files',
  'knowledgebaseenabled' => true,
  'appstoreenabled' => false,
  'appstoreurl' => 'https://api.owncloud.com/v1',
  'mail_domain' => '_secret_',
  'mail_from_address' => 'owncloud',
  'mail_smtpdebug' => false,
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => '_secret_',
  'mail_smtpport' => 25,
  'mail_smtptimeout' => 10,
  'mail_smtpsecure' => '',
  'mail_smtpauth' => false,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpname' => '',
  'mail_smtppassword' => '',
  'trashbin_retention_obligation' => 30,
  'trashbin_auto_expire' => true,
  'allow_user_to_change_display_name' => true,
  'appcodechecker' => true,
  'updatechecker' => false,
  'has_internet_connection' => false,
  'check_for_working_webdav' => true,
  'check_for_working_htaccess' => true,
  'log_type' => 'owncloud',
  'logfile' => '/var/log/owncloud/owncloud.log',
  'loglevel' => 2,
  'logdateformat' => 'Y-m-d H:i:s',
  'logtimezone' => 'Europe/Paris',
  'log_query' => false,
  'cron_log' => true,
  'log_rotate_size' => false,
  'remember_login_cookie_lifetime' => 1296000,
  'session_lifetime' => 86400,
  'session_keepalive' => true,
  'custom_csp_policy' => 'default-src \'self\'; script-src \'self\' \'unsafe-eval\'; style-src \'self\' \'unsafe-inline\'; frame-src *; img-src *; font-src \'self\' data:; media-src *',
  'xframe_restriction' => true,
  'datadirectory' => '/mnt/glustervolume/ownclouddata',
  'maintenance' => false,
  'customclient_desktop' => '_secret_',
  'customclient_android' => '',
  'customclient_ios' => '',
  'enable_previews' => true,
  'preview_max_x' => NULL,
  'preview_max_y' => NULL,
  'preview_max_scale_factor' => 10,
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'preview_office_cl_parameters' => '',
  'enable_avatars' => true,
  'openssl' => 
  array (
  ),
  'cipher' => 'AES-256-CFB',
  'singleuser' => false,
  'asset-pipeline.enabled' => false,
  'mount_file' => '',
  'cache_path' => '',
  'quota_include_external_storage' => false,
  'filesystem_check_changes' => 1,
  'filesystem_cache_readonly' => false,
  'share_folder' => '/',
  'ldapIgnoreNamingRules' => false,
  'secret' => '_secret_',
);

**Are you using external storage, if yes which one:** local

**Are you using encryption:**no

**Are you using an external user-backend, if yes which one:** LDAP

**Comment by RealRancor** [comment]
Hi,

isn't this handled by the activity app? https://github.com/owncloud/activity/issues

**Comment by DeepDiver1975** [comment]
@nickvergessen please triage - THX

**Comment by nickvergessen** [comment]
https://github.com/owncloud/activity/blob/master/templates/email.notification.php#L11-L15

So this is a problem with the french translation: https://www.transifex.com/projects/p/owncloud/viewstrings/#fr/activity/25578087

About the encoded `'` I shall have a look tomorrow

**Comment by PhilJung** [comment]
> So this is a problem with the french translation

For the encoded char. 

Just to be sure: it is a two parts problem : I don't believe it's normal to see a file modified Today in a summary of yesterday activities (should have logged 2 tickets :-) )

**Comment by nickvergessen** [comment]
Okay, let me split up my comment:

### Problem 1: "Yesterday"

https://github.com/owncloud/activity/blob/master/templates/email.notification.php#L11-L15

So this is a problem with the french translation: https://www.transifex.com/projects/p/owncloud/viewstrings/#fr/activity/25578087

English translation does not use the word "yesterday"

> Or is it also a translation problem ? I mean "during the last day" is "yesterday" or now() - 24 x 3600s ?

so yes, thats the issue. It is "now() - 24 x 3600s" while the french translator decided to translate "yesterday"

### Problem 2: Escaped single quote

About the encoded `'` I shall have a look tomorrow

**Comment by nickvergessen** [comment]
PR for problem 2 has been merged. problem 1 is nothing we can fix, just leave a comment on transifex.
