### ISSUE TITLE
Experimental file locking database support

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#16967]
Store locks in the database instead of memcache.
(or write our own database-based memcache?)

@DeepDiver1975 @icewind1991 @karlitschek for later

**Comment by karlitschek** [comment]
yes. as discussed.

**Comment by DeepDiver1975** [comment]
a topic for 8.2 from my pov

we want to enable locking for the broad mass - requiring a redis server is out-of-scope for small installations - we can only fallback to the database in these cases (other memcaches have been proven to be not reliable enough)

**Comment by PVince81** [comment]
Yes, I'd love to have locking on my server too, but not willing to install redis there.

**Comment by PVince81** [comment]
This was added on 8.2 through https://github.com/owncloud/core/pull/17662

@icewind1991 please update the wiki accordingly https://github.com/owncloud/core/wiki/ownCloud-8.2-Features and then close this ticket. Thanks.

**Comment by cmonteroluque** [comment]
@icewind1991 this looks close to a resolution.

**Comment by icewind1991** [comment]
Added it to the wiki
