### ISSUE TITLE
Add lock info in sabre response

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#16968]
Currently the Sabre LockedException is thrown as is.

It needs to be extended to contain proper locking information.

@DeepDiver1975 @icewind1991

**Comment by DeepDiver1975** [comment]
THX

**Comment by PVince81** [comment]
@DeepDiver1975 move to 9.0 ?

**Comment by PVince81** [comment]
Seems the current info was already sufficient. Moving to backlog.

If we ever want to show more info in the client we can try adding that info there.
