### ISSUE TITLE
PHP 5.4 issues with RHEL/CentOS 6

### ISSUE THREAD

**Issue by carlaschroder** [owncloud/core#16974]
re: https://github.com/owncloud/core/issues/16343

I tested the steps in https://github.com/owncloud/core/issues/16343#issuecomment-104700724 and they work, so I'm going to add them to the README on customer.owncloud.com.

One of my friends at RHEL asked "Have you thought about shipping it as a containerized app?" 

@jnweiger @MorrisJobke

**Comment by jnweiger** [comment]
If they mean docker, when they say containerized, then it is trivial to do. I am generating the instruction steps for all supported platforms from a single source as part of th epackage installation test suite.

**Comment by carlaschroder** [comment]
@jnweiger Will that resolve dependency issues, and issues like php 5.3/php 5.4?

**Comment by carlaschroder** [comment]
No https? Dang.

**Comment by carlaschroder** [comment]
Please review: https://github.com/owncloud/documentation-enterprise/issues/239
 please review: using Software Collections w RHEL 6 #239

**Comment by jnweiger** [comment]
Yep, no https, I never neeed that for testing the installation. 

When I install my docker containers with obs-docker-install, *all* dependency issues are properly handled. Yes. Handling them all is a prerequisite to have the testsuite fully automated, so I am pretty certain in this respect :-)

**Comment by carlaschroder** [comment]
The relevant READMEs on customer.owncloud.com and presales.owncloud.com have been updated.
