### ISSUE TITLE
List of users and groups does not render correctly when there is a group with a long name

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#16977]
### Steps to reproduce

1. Install 8.1 
2. create a group with a long name 
3. enable external storage
4. configure an external storage and select a group

### Expected behaviour

Drop down list of users and groups display correctly

### Actual behaviour

Drop down list of users and groups does not display correctly

![p359](https://cloud.githubusercontent.com/assets/8480343/8191340/8de14796-1435-11e5-8ed9-205febd48541.PNG)

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration:

ownCloud Enterprise Edition 8.1 beta 2 (daily) Build:2015-06-15T03:10:33+00:00 fe9b28a800514315eba17ac5da84b8b93abd9ffc

**Comment by PVince81** [comment]
Need to add "text-overflow: ellipsis" on that dropdown's row style.

@jancborchardt maybe ?

**Comment by cmonteroluque** [comment]
This issue will fall off 8.2 if not resolved by 6 Oct
