### ISSUE TITLE
iOS Sabre DAV errors when attempting connection with owncloud app v. 3.4.1

### ISSUE THREAD

**Issue by stickr** [owncloud/core#16979]
Hi,

The iOS app previously worked great, after an OC upgrade it stopped.I haven't been able to use the iOS app for a while, each attempt to enter the server address into the app it displays the error "Server not found" and the below is entered into my ./owncloud/data/owncloud.log file.

{"reqId":"6446da50fb429ae2377c7cb112f319a4","remoteAddr":"XX.XX.XX.XX","app":"webdav","message":"Exception: {\"Message\":\"No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/media\\\/raid\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(126): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#1 \\\/media\\\/raid\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(106): OC_Connector_Sabre_Auth->auth(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#2 \\\/media\\\/raid\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Plugin.php(108): OC_Connector_Sabre_Auth->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod('GET', 'status.php')\\n#4 \\\/media\\\/raid\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(433): call_user_func_array(Array, Array)\\n#5 \\\/media\\\/raid\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(455): Sabre\\\\DAV\\\\Server->broadcastEvent('beforeMethod', Array)\\n#6 \\\/media\\\/raid\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('GET', 'status.php')\\n#7 \\\/media\\\/raid\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(61): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/media\\\/raid\\\/www\\\/owncloud\\\/remote.php(54): require_once('\\\/media\\\/raid\\\/www...')\\n#9 {main}\",\"File\":\"\\\/media\\\/raid\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":73}","level":0,"time":"2015-06-17T02:27:28+00:00","method":"GET","url":"\/remote.php\/webdav\/status.php"}

Ubuntu 15.04
LAMP Stack

Let me know if you need anything additional

**Comment by stickr** [comment]
whoops should've probably put this into sabre

**Comment by stickr** [comment]
I have no idea what I'm doing :)

**Comment by PVince81** [comment]
The error in the log is normal (it's in debug level), it appears when clients are trying to request authorization type by not sending the headers.

"Server not found" sounds more like a connectivity issue.

**Comment by stickr** [comment]
I found the problem...I was originally putting https://owncloud.servername.com/remote.php/webdav into the ios app for an address. I changed it to https://owncloud.servername.com and it worked.  For all those who see this "/remote.php/webdav" is not needed in the ios app's address field.

**Comment by RealRancor** [comment]
Hi,

there is no note in:

https://doc.owncloud.org/ios/ios_app.html

that you need to add the/ remote.php/webdav . Its telling you to enter the server URL only.
