### ISSUE TITLE
Install on SLES: Nothing provides php54-sqlite needed by owncloud-8.0.4.12.1.noarch

### ISSUE THREAD

**Issue by Kawohl** [owncloud/core#16981]
I tried to install owncloud Community Version on SLES 12.

During the install this error ocurred:

Install on SLES: Nothing provides php54-sqlite needed by owncloud-8.0.4.12.1.noarch

I think this somehow related to the missing php posix module on SLES 12

any thoughts? @jnweiger

**Comment by RealRancor** [comment]
Hi,

seems you need to first enable a module to get PHP 5.4 for SLES12 according to:

https://forums.suse.com/showthread.php?6354-PHP-version-in-SLES-12&p=27760#post27760

**Comment by Kawohl** [comment]
Hey there, the Module is installed.

**Comment by RealRancor** [comment]
Ah, yes. Seems you're getting PHP 5.5 as you already have noted:

https://forums.suse.com/showthread.php?6354-PHP-version-in-SLES-12&p=27760#post27760

So the package is probably called php55-sqlite which doesn't match the requirement php54-sqlite?

**Comment by jnweiger** [comment]
owncloud-8.0.4.12.1.noarch is the build release number from the SLE_11_SP3 repo.
Please remove that repo and try again.
