### ISSUE TITLE
Drag and dropping a file inside a folder that contains a file named in the same way, you get "an error" message

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16984]
### Steps to reproduce
1. Create a folder
2. Create inside the folder a file named AAA.txt
3. Go to the home folder and create another file named as the previous one (e.g. AAA.txt)
4. Drag and drop the file from the Home folder to the folder previously created.

### Expected behaviour
A message that let us choose with file version we want to keep should be shown, like the behaviour if you upload a message from local for example.

### Actual behaviour
Could not move AAA.txt - File with this name already exists is error message shown

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** "version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity: 1.2.3
 - admin_audit: 0.6
 - encryption: 1.0.0
 - enterprise_key: 0.1.0
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.4
 - user_ldap: 0.6.0
 - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

![movedrag2](https://cloud.githubusercontent.com/assets/10596560/8203316/1f159734-14e1-11e5-9ef8-e01f6342760a.gif)

**Comment by PVince81** [comment]
Currently the move operation does not use the conflict dialog.

The conflict dialog logic is currently crammed into the upload code. It needs to be extracted first to make it usable by other operations.

**Comment by PVince81** [comment]
@MTRichards @cmonteroluque @DeepDiver1975 I suggest to implement this later after the move to Webdav.
The conflict dialog code is currently intertwined with the upload code and needs to be decoupled first.

**Comment by DeepDiver1975** [comment]
> @MTRichards @cmonteroluque @DeepDiver1975 I suggest to implement this later after the move to Webdav.
> The conflict dialog code is currently intertwined with the upload code and needs to be decoupled first.

yep - 9.0 then

**Comment by cmonteroluque** [comment]
ok

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/issues/24885
