### ISSUE TITLE
Webdav not working on https://mycloud.site/remote.php/webdav

### ISSUE THREAD

**Issue by gladiac** [owncloud/core#16986]
I'm running owncloud 8.0.4 and if I try to access owncloud with a webdav client it doesn't work.

asn@magrathea:~> cadaver https://mycloud.site/remote.php/webdav
Could not open collection:
503 Service Unavailable

[17/Jun/2015:11:04:19 +0200] "OPTIONS /remote.php/webdav/ HTTP/1.1" 503 6816

If you try it with KDE's webdav slave which does a PROPFIND you get:

[17/Jun/2015:11:01:46 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 503 6816

Firefox which uses GET which works ...

**Comment by DeepDiver1975** [comment]
503 is returned in case the installation is in maintenance mode.

You might also want to have a look at the logs-

**Comment by gladiac** [comment]
The web interface works just fine. So what part do you think is in maintenance mode?

**Comment by RealRancor** [comment]
@gladiac 
This could also happen if you have enabled the singleusermode in your config.php

**Comment by gladiac** [comment]
The cloud is not in maintenance mode nor in singleuser mode. The owncloud.log doesn't log an entry if I try to connect.

Help or explanation for better debugging is much appreciated. You also find me on Freenode

**Comment by RealRancor** [comment]
Hi,

ok then have a look at https://forum.owncloud.org/viewtopic.php?f=17&t=7536 which gives a lot of infos about WebDAV issues.

You could also give some more infos about your environment as asked in the issue template: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version (Linked in the yellow box when creating a new issue).

Until know we even don't know what webserver you're using.

**Comment by gladiac** [comment]
It worked before the upgrade with owncloud 7.0.6 it stopped with 8.0.4, so it can't be a configuration issue of the webserver. However the server running is:

apache2-2.4.10-22.1.x86_64
php5-5.6.1-27.1.x86_64

Also as I told earlier a GET request works but not a PROPFIND or OPTIONS ...

**Comment by gladiac** [comment]
caldav and carddav are working, so it is only an issue of the file serving part ...

**Comment by LukasReschke** [comment]
@gladiac Any way to get me a non-administrative test account on the instance? THX. (you can find my user name in my profile)

Alternatively: Do you use external storage? If so: Is one of them down?

**Comment by gladiac** [comment]
Lukas, there is no external storage. I'm happy to give you an account. Are you on freenode?

**Comment by RealRancor** [comment]
@gladiac 
> It worked before the upgrade with owncloud 7.0.6 it stopped with 8.0.4, so it can't be a configuration issue of the webserver. 

Exactly such infos are really useful in the initial post when creating such issues. :-)

**Comment by gladiac** [comment]
The issue was that the config directory was not writeable by the server.

As I was logged it the information that everything was working is cached in the session so I didn't get the error message that the config directory is not writeable. Logging out would show it ...

**Comment by jgillich** [comment]
I get the same for `demo.owncloud.org`, does anyone know why?
```
jakob@thinkpad ~/d/hyperdav> cadaver https://test:test@demo.owncloud.org/owncloud/remote.php/webdav/
WARNING: Untrusted server certificate presented for `demo.owncloud.org':
Issued to: demo.owncloud.org
Issued by: Let's Encrypt, US
Certificate is valid from Thu, 04 Feb 2016 13:36:00 GMT to Wed, 04 May 2016 13:36:00 GMT
Do you wish to accept the certificate? (y/n) yes
Could not open collection:
500 Internal Server Error
```

**Comment by RealRancor** [comment]
@jgillich Very very unlikely that you have the same issue here. Please see https://owncloud.org/support where to get support.

Btw. the URL for the demo instance is https://test:test@demo.owncloud.org/remote.php/webdav/

**Comment by jgillich** [comment]
Ah I see, got the URL wrong. Thanks!
