### ISSUE TITLE
File locking and X-Sendfile

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#16997]
I just realized that with X-Sendfile we won't be able to lock the file during transfer (experimental file locking). This is because X-sendfile just tells the browser where the file is on-disk so it can stream it back to the client after the PHP request finished. This means that there is no way to unlock the file after the transfer.

We might then want to disable X-Sendfile when locking is enabled...

@DeepDiver1975 @icewind1991

**Comment by DeepDiver1975** [comment]
As soon as we did migrate the files app to webdav this will be obsolete by itself as sabre does not support xsendfile.

The only remaining question then is if we want to bring back xsendfile then at all.

**Comment by RealRancor** [comment]
> as sabre does not support xsendfile

Not yet: https://github.com/fruux/sabre-dav/issues/120 :)

**Comment by RealRancor** [comment]
File locking was removed in https://github.com/owncloud/core/pull/18881 as discussed in https://github.com/owncloud/core/issues/18870
