### ISSUE TITLE
(Vulnerable) [7.1/debian] Filename with spaces and russian letters gives 404 and isn't accessible at all

### ISSUE THREAD

**Issue by amaxcz** [owncloud/core#16999]
trying open file (russian name with spaces)
its gives me 404

"GET /index.php/apps/files/ajax/download.php?dir=%2FOLD%2Fbigone%2Fpublic&files=2011.06.01%20%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D0%B5%20%D0%BE%D1%84%D0%B8%D1%81%D0%B0%20%D0%BD%D0%B0%20%D0%A1%D1%83%D1%89%D1%91%D0%B2%D1%81%D0%BA%D0%BE%D0%BC%20%D0%B2%D0%B0%D0%BB%D1%83.mp4 HTTP/1.1" 404

looking at /var/www/owncloud/apps/files/ajax/download.php
the bug in OC_Files::get($dir, $files_list, $_SERVER['REQUEST_METHOD'] == 'HEAD');
because its takes $files_list with content:

array(1) {
  [0]=>
  string(75) "2011.06.01 Открытие офиса на Сущёвском валу.mp4"
}

So, this filename BROKE all.

**Comment by LukasReschke** [comment]
Thanks a lot for reporting issues back to us!

We need some more information to properly support you with your issue!

Can I ask you to follow our guidelines for submitting bugs as described here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by PVince81** [comment]
There were such known issues where the server was running on Windows.
This isn't supported any more, need to run on Linux instead.

Closing.
