### ISSUE TITLE
8.0.4: HTTP DELETE requests result in 500 Internal Server Error suddenly

### ISSUE THREAD

**Issue by dragotin** [owncloud/core#16994]
Today I deleted a lot of files spread over directories from a sync directory. All went smooth, but suddenly the server began to answer with 500 on all subsequent deletes, until the end. For the last operation the client also received a *Operation canceled*.

owncloud.log gives me 
```
{"reqId":"402df055ec2435e3bd1fa2b0f3996c60","remoteAddr":"172.18.16.181","app":"remote","message":"An exception occurred while executing 'SELECT * FROM `oc_locks` WHERE `userid` = ? AND (`created` + `timeout`) > 1434546174 AND (( `uri` = ?) OR (`uri` LIKE ?))' with params [\"kf\", \"sharefolder\", \"sharefolder\\\/%\"]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'oc10.oc_locks' doesn't exist","level":4,"time":"2015-06-17T13:02:54+00:00"}
```
for every file deletion request (probably).

Server version is 8.0.4, branch *stable8* on commit 5fcab24e592c5f0f35d3293449dbd2f15a40f5f8

**Comment by LukasReschke** [comment]
> Base table or view not found: 1146 Table 'oc10.oc_locks' doesn't exist

:confused:  - do we have this table on stable8?

cc @icewind1991

**Comment by LukasReschke** [comment]
Ok. This is the WebDAV locking stuff that we killed with master. But why does this error appear? :confused:

**Comment by dragotin** [comment]
Probably because the implementations in ```lib/private/connector/sabre/locks.php``` are not really concurrency save.

**Comment by dragotin** [comment]
but.... why is my table oc_locks deleted? This is *mysterious*

**Comment by LukasReschke** [comment]
Crazy assumption: Did you switch from master to stable8 without a new DB? In this case the table would be missing and once locking is used everything goes :boom:

**Comment by dragotin** [comment]
hmm, not sure, but possible. What should we do? Close?

**Comment by LukasReschke** [comment]
Unless we can reproduce this again, I'd vote for yes.
