### ISSUE TITLE
Usernames are case sensitive in federated sharing

### ISSUE THREAD

**Issue by manuelVo** [owncloud/core#17002]
### Steps to reproduce
1. Create user with uppercase letters (e.g. USERNAME)
2. From another owncloud share with this user but write the username in lowercase letters (e.g. username@example.org)

### Expected behaviour
The share should be created successfully

### Actual behaviour
The share won't appear in the target installation. However the folder is displayed as shared on the sharing installation.

### Server configuration
**Operating system**:
Arch Linux

**Web server:**
nginx 1.8.0

**Database:**
MariaDB 10.0.19

**PHP version:**
5.6.10

**ownCloud version:** (see ownCloud admin page)
8.0.4

**Updated from an older ownCloud or fresh install:**
Updated to 8.0.4 (fresh install was version 8 though)

**List of activated apps:**
I don't think they are relevant in this case, but just in case here are the apps on the source installation.

- Bookmarks
- Calendar
- Contacts
- Deleted files
- File Locking
- Music
- Personal Wall Tattoo
- Pictures
- Provisioning API
- Share Files
- Versions

Unfortunately right now I don't know which apps are installed on the target system

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'oct78ptwufox',
  'passwordsalt' => 'secret',
  'secret' => 'secret',
  'trusted_domains' =>
  array (
    0 => 'example.org'
  ),
  'datadirectory' => '/usr/share/webapps/owncloud/data',
  'overwrite.cli.url' => 'https://example.org',
  'dbtype' => 'mysql',
  'version' => '8.0.4.2',
  'dbname' => 'owncloud',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',  
  'dbuser' => 'secret',
  'dbpassword' => 'secret',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => 1,
);
```

**Are you using external storage, if yes which one:**
no

**Are you using encryption:**
no

**Are you using an external user-backend, if yes which one:**
no

### Logs
Nothing is logged while reproducing this bug

**Comment by MorrisJobke** [comment]
ref #13716

**Comment by PVince81** [comment]
closing in favor of https://github.com/owncloud/core/issues/19399
