### ISSUE TITLE
Update doesn't start -- only message to reload page

### ISSUE THREAD

**Issue by flying-squirrel** [owncloud/core#17007]
Hello! I have a little problem with the update to OwnCloud 8.0.4 (from 8.0.3). I have some web space at a German hoster where my OC is located. I started the update process in the Update Center inside the OC admin page. First everything started fine. It made a backup of OC. Afterwards the update process took me to this page where I hit "Aktualisierung starten" (Start update).
![screenshot - 18 06 2015 - 10 10 33](https://cloud.githubusercontent.com/assets/5991131/8226832/8118b378-15a2-11e5-971d-2708f8792b41.png)

After that, it showed me this page. The content of the page is: Updating to OwnCloud 8.0.4. This could take a while.
![screenshot - 18 06 2015 - 10 10 59](https://cloud.githubusercontent.com/assets/5991131/8226837/86bb8760-15a2-11e5-90d4-99bc6f4f6e3b.png)

And after a split second there is the notice to "Please reload the page". When I do this, I get to the page to start the update. When I start the update, I get to the page where I have to reload and so on.

I tried to do the update from several Computers and Browsers. It's always the same problem.

Is this a known problem and/or does anyone know how I can fix it.

Thanks in advance for your help!

**Comment by LukasReschke** [comment]
Anything in owncloud.log? Does it help if you try the update from an "incognito" window?

**Comment by flying-squirrel** [comment]
Dear Lukas,
the incognito window didn't help. A little notice to the errors in the logfile. I know about the two errors before the update (calendar app and tempmanager). I was told there are fixes on the way. But there is a new error. It is logged several times. Sometimes every few minutes, sometimes every few hours and sometimes in the middle of the night (where I definitely didn't try to update). The log file shows the following errors.

Before the update:
{"reqId":"06e0662250a31f5d9699dd6579d8052d","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/kunden\/261236_94081\/webseiten\/mannichl\/subdomains\/owncloud\/apps\/calendar\/appinfo\/app.php#41","level":3,"time":"16.06.15 11:15:02"}
{"reqId":"06e0662250a31f5d9699dd6579d8052d","remoteAddr":"","app":"PHP","message":"opendir(\/tmp): failed to open dir: Permission denied at \/kunden\/261236_94081\/webseiten\/mannichl\/subdomains\/owncloud\/lib\/private\/tempmanager.php#134","level":3,"time":"16.06.15 11:15:02"}

After the update (I only post the first appearance of the error):
{"reqId":"f0ce5d072a7745848f1ea25195ee7609","remoteAddr":"91.17.49.111","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"16.06.15 11:21:25"}

Might this help?

**Comment by LukasReschke** [comment]
First error: Remove the apps from the apps folder and replace them with the new versions from the appstore.

Second error: Change that setting in the php.ini - this is a very annoying PHP5.6 behaviour that shouldn't break anything though.

**Comment by flying-squirrel** [comment]
I added the line to the php.ini. Also I updated the apps, but nothing changed. Now I even deleted the 3rd-party apps from the app folger (calendar and contacts).

There is still no update happening. Can you please re-open the issue?

**Comment by LukasReschke** [comment]
The same errors do appear? That is unlikely. Can you please report the error log?

Also:
```
{"reqId":"06e0662250a31f5d9699dd6579d8052d","remoteAddr":"","app":"PHP","message":"opendir(\/tmp): failed to open dir: Permission denied at \/(...)\/owncloud\/lib\/private\/tempmanager.php#134","level":3,"time":"16.06.15 11:15:02"}
```

Do you have write permissions to the tmp folder?

**Comment by flying-squirrel** [comment]
No, not the same errors do appear. There is no new entry in the log. Since I started the update process, there was only one error (the one with the notion that I should add the line in the php.ini).

I added that line, and now there are no more new entries in the log.

But still: when I go to my OwnCloud page and click on "Start Update" I get to the page where it says "Please reload site" (see my entry statement).

To your second question about the tmp folder. That error is with my hosting provider. He does not allow any search in this folder. But I don't think that this error message is the issue here. That error happened even before the update and everything worked fine.

To make it clear: since I started the update process, there was only one error that showed up in the log multiple times. I will provide the last five errors in the log if that's ok, because they are all the same:

{"reqId":"3e20c9b1c5643d4498c76815ec48cd28","remoteAddr":"91.53.94.8","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"18.06.15 11:44:51"}
{"reqId":"826412706101970c3e3bb3fec53e0a7e","remoteAddr":"91.53.94.8","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"18.06.15 11:56:51"}
{"reqId":"202d9effbc394ddf21b4acdac7e3a2c7","remoteAddr":"91.53.94.8","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"18.06.15 12:08:51"}
{"reqId":"259207e3c802206e07397430124f61eb","remoteAddr":"91.53.94.8","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"18.06.15 12:20:51"}
{"reqId":"779e0a926b8ffac6d0ba464b11dbda6a","remoteAddr":"91.53.94.8","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"18.06.15 12:32:51"}

Then I implemented said line in the php.ini and now there are no more errors logged.

**Comment by LukasReschke** [comment]
Mhm. Can you get me the link to your instance via mail? - I will then take a look what might fail there from the web interface. You can find my mail address in my profile. Thanks a lot!

(regarding the error, this is due to https://github.com/owncloud/core/issues/13592)

**Comment by flying-squirrel** [comment]
Is this even a core issue? Or should it be moved to OwnCloud updater?

**Comment by LukasReschke** [comment]
This is a core issue. Thanks for sending me the link.

This looks fishy, a CSRF exception is thrown in `ajax/update.php`. That should not happen as far I can see the correct token is sent to the remote server.

Could you upload a file named `test.php` to the server with the following content, place it next to `index.php` of ownCloud please:

```php
<?php
require_once('./lib/base.php');
var_dump(\OC_Util::callRegister());
```

That script won't do any harm except me allowing to potentially see if the CSRF token is not correctly stored. Also can you check where you store your PHP sessions in your php.ini? Also do you have write access to that location?

**Comment by flying-squirrel** [comment]
I uploaded the file.

With the PHP session, do you mean the "session.save_path"? This is in the OC instance in the folder /tmp. The permissions to this folder are 777.

**Comment by LukasReschke** [comment]
That is strange. The results of test file looks actually consistent, the data is stored within the session. 

Can you modify https://github.com/owncloud/core/blob/v8.0.4/lib/private/appframework/http/request.php#L377-L405 in a way that you add below each `$token =` a `var_dump($token)`? - That may help further to debug what causes the issue here. Also do you have access via OCC and can disable any application except files?

**Comment by flying-squirrel** [comment]
I modified the file. I hope I did it correct.

Unfortunately, I do not have access via OCC.

**Comment by LukasReschke** [comment]
Sorry… You need to add a  `;` after the `)`, forget to add that :speak_no_evil:

**Comment by flying-squirrel** [comment]
Done!

**Comment by LukasReschke** [comment]
Ok. The output does indicate that the `IRequest` class did not have an item with the key `requesttoken`. This indicates that the class is populated in an `appinfo/app.php` without the proper initialization values. 

The confusing thing is this would likely to have also shown symptoms before. 

To verify that this is the bug in which direction I'd need to add could you modify in `passesCSRFCheck` the following lines:

```php
		if($this->items['requesttoken'] === false) {
			return false;
		}
```

to

```php
		if($this->items['requesttoken'] === false) {
			echo("This should not happen");
			return false;
		}
```

**Comment by flying-squirrel** [comment]
Ok, I changed the lines. I hope it helps.

**Comment by LukasReschke** [comment]
Indeed. This is the root cause. Investigating. Stay tuned. Thanks for your collaboration, very much appreciated.

**Comment by LukasReschke** [comment]
I was unfortunately not able to reproduce this situation locally using a similar setup. But I have a few suspicions that there went something wrong with the updates in the past.

Before we proceed with may I ask you:

1. How did you perform updates in the past?
2. Do all files equal the one from https://download.owncloud.org/community/owncloud-8.0.4.tar.bz2?

I ask this because especially with the shipped ownCloud updater app we had a few bugs where in the end not all files have been replaced. This resulted in not debuggable situations and a huge confusion at user and developer site.

It would be super awesome if it would be possible if you could – just to ensure that we don't waste a lot of time because of this specific bug – all ownCloud folders and replace them with the one from said tar file. Be aware, keep the config and data folder. Do in no case replace these.

Furthermore, if this does not solve this problem it would need to get a stacktrace which may leak sensitive information. – I will provide further information about this once we are sure that it is no problem with outdated files.

Thanks a lot for your collaboration and sorry for the encountered problem. I really appreciate that you work together with us in resolving this.

**Comment by flying-squirrel** [comment]
Lukas, thanks for all the work you are putting into this problem! I really appreciate it. Right now I am deleting all the files from the OwnCloud instance (except the data and config folder). Afterwards I will upload everything from the linked tar file.

I had a problem with the OwnCloud Update a few weeks ago. I didn't update my OwnCloud in a long time and skipped several releases. I wanted to make an update from 6.x to 8.x. This obviously didn't work, so I made a fresh install of OwnCloud 8.0.3. This would have been my first update after this fresh install.

I now uploaded all the files in the linked tar and went to my OwnCloud instance. There was the "Start update" button again. I pressed it and I got the same result: please reload page.

**Comment by LukasReschke** [comment]
> This obviously didn't work, so I made a fresh install of OwnCloud 8.0.3. This would have been my first update after this fresh install.

Just to be sure: Did the fresh install happen on another table?

> I now uploaded all the files in the linked tar and went to my OwnCloud instance. There was the "Start update" button again. I pressed it and I got the same result: please reload page.

Strange. Can you add a `print_r(debug_backtrace());` at the first line of `\OC\AppFramework\Http\Request::passesCSRFCheck`?

**Comment by flying-squirrel** [comment]
Dear Lukas,
sorry you didn't hear from me, but I was away for a few days. I will try to help you. About your first question. I don't know exactly what you mean. The MySQL table? I deleted all the tables and let it create again at the install from OwnCloud. But then I copied some files back (like Contacts and Calendar events).

I will add the line, but I can't find the file you are mentioning. Can you give me the path to the file?

**Comment by flying-squirrel** [comment]
Ok, I found the issue. I deactivated my php.ini (I simply deleted the .ini) and started the update again. It was a success. The content of my php.ini is as follows:

session.save_path = "path/to/owncloud/tmp/"
upload_tmp_dir = "path/to/owncloud/tmp/"
always_populate_raw_post_data = -1

Thank you Lukas for all your help! I appreciate it!
