### ISSUE TITLE
Fix experimental tag for cloned and disabled apps

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#17003]
(do a lookup at server if ocsid is provided)

**Comment by MorrisJobke** [comment]
cc @nickvergessen @libasys

**Comment by MorrisJobke** [comment]
@LukasReschke just mentioned that an app is labeled as "experimental" if it is not approved. Maybe we should rename this to "not approved". Because it is a huge difference

**Comment by LukasReschke** [comment]
Just FTR: I'm fine with the experimental rating.
