### ISSUE TITLE
config.php refers to mssql as a supported db

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#17000]
### Steps to reproduce

1. Install 8.1 
2. open initial config.php

### Expected behaviour

No reference to mssql as a supported DB

### Actual behaviour

mssql is identified as a supported DB:

```

<?php
$CONFIG = array (
  'supportedDatabases' =>
  array (
    0 => 'mysql',
    1 => 'pgsql',
    2 => 'oci8',
    3 => 'mssql',
  ),
  'instanceid' => 'ocwwpt7h3mb9',
);

```

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration:

ownCloud Enterprise Edition 8.1 beta 2 (daily) Build:2015-06-15T03:10:33+00:00 fe9b28a800514315eba17ac5da84b8b93abd9ffc

See https://github.com/owncloud/documentation/issues/1221.

@MTRichards @karlitschek

**Comment by LukasReschke** [comment]
Is fixed.

**Comment by jnfrmarks** [comment]
Is it removed from ee.config.php too?

**Comment by LukasReschke** [comment]
https://github.com/owncloud/enterprise/pull/680 - might need a merge and backport to stable8. Don't know how building works.

**Comment by RealRancor** [comment]
CE is already merged: https://github.com/owncloud/core/pull/16978

AFAIK the rebuild of the documentation needs to be done manually.

**Comment by LukasReschke** [comment]
Yup. @carlaschroder wrote about how it works :)

http://carlaschroder.com/auto-generate-doc-page/

**Comment by jnfrmarks** [comment]
I'm still seeing references to mssql in config.php and ee.config.php.

ownCloud Enterprise Edition 8.1 RC1 (daily) Build:2015-06-29T03:08:30+00:00 774a38256d718363a7a501f4e6ff42e1a89dab3a

**Comment by LukasReschke** [comment]
> I'm still seeing references to mssql in config.php and ee.config.php.

config.php: Well it will stay there unless you remove it. We shall not mess with the config file. Any value that is in it will stay in it.
ee.config.php: You shall review v

**Comment by jnfrmarks** [comment]
I'm running a fresh installation so config.php is being written out as part of the install process.  I don't expect to see mssql referenced in the array of DBs.

**Comment by LukasReschke** [comment]
>>  I'm running a fresh installation so config.php is being written out as part of the install process. I don't expect to see mssql referenced in the array of DBs.

>ee.config.php: You shall review owncloud/enterprise#680

See https://github.com/owncloud/documentation/pull/1224

**Comment by LukasReschke** [comment]
As long as there is a config file that contains the DB array it will simply get written into the main config.

**Comment by jnfrmarks** [comment]
ohhhhh, I see what's going on here!  It's in ee.config.php so it's going into config.php.  Closing this.
