### ISSUE TITLE
Webdav endpoint for zip download

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#17014]
To be consistent with #12353 
and to get rid of the ugly https://github.com/owncloud/core/blob/master/lib/private/files.php#L50

Need to discuss whether to use the existing "remote.php/webdav" or have a new special webdav endpoint for bulk downloads.

@DeepDiver1975 @icewind1991

**Comment by DeepDiver1975** [comment]
> Need to discuss whether to use the existing "remote.php/webdav" or have a new special webdav endpoint for bulk downloads.

will be it's own endpoint - I did start with an experimental app called dav.
the root entrypoint will be remote.php/dav
it's children: files, uploads, deltas - and now with zip or comporessed or what so ever

@dragotin FYI

**Comment by PVince81** [comment]
PR or it didn't happen :wink:

**Comment by PVince81** [comment]
Cool

**Comment by DeepDiver1975** [comment]
> PR or it didn't happen :wink:

The code is on the SSD which was inside my now broken laptop ..... :bomb:

**Comment by DeepDiver1975** [comment]
Anyway - most important is the concept @dragotin and myself discussed last week regarding chunked-upload-ng and delta-sync

**Comment by LukasReschke** [comment]
> The code is on the SSD which was inside my now broken laptop ..... :bomb:

Can confirm. @DeepDiver1975 has now to work with a mobile "Ziegelstein" which is very loud and very heavy. :speak_no_evil:

**Comment by DeepDiver1975** [comment]
@dragotin where are the notes? :hide:

**Comment by dragotin** [comment]
@DeepDiver1975 yes, yes, blog is prepared, notes are written.

**Comment by DeepDiver1975** [comment]
![youre-awesome](https://cloud.githubusercontent.com/assets/1005065/8232224/2c6a6840-15ce-11e5-88e8-94d31ca91d80.jpg)

**Comment by icewind1991** [comment]
> The code is on the SSD which was inside my now broken laptop ..... 

Push early, push often

**Comment by DeepDiver1975** [comment]
No worries - I have the ssd here - the laptop will return tomorrow - nothing lost - all good ....

**Comment by PVince81** [comment]
nothing lost, so you have the PR ? :wink:

**Comment by DeepDiver1975** [comment]
I need to search my wip branches .,,.

**Comment by PVince81** [comment]
Some spec of yours: https://github.com/DeepDiver1975/dav/issues/5

**Comment by PVince81** [comment]
Some trouble with Webdav endpoints for download in the web browser: https://github.com/owncloud/core/issues/23500

The problem is that Webdav is supposed to deliver XML, so in case or error/exception/forbidden it would return XML instead of an error page.

**Comment by PVince81** [comment]
Zip folder plugin PR: https://github.com/owncloud/core/pull/24178
