### ISSUE TITLE
Reduce size of *.tar.gz by removing documentation

### ISSUE THREAD

**Issue by tflidd** [owncloud/core#17015]
A user on the forum reported, that the owncloud*.tar.gz files contain a documentation folder in core/doc. Is this really needed? It is about 17 MB in size. Without it I could reduce the archive's size from 24.5 MB to 18.8 MB.
ref: https://forum.owncloud.org/viewtopic.php?f=31&t=28740#p89711

**Comment by DeepDiver1975** [comment]
> Is this really needed?

yes - otherwise we would not have put it there.

To be honest - does it make a difference these days if the package has a size of 25MB or 19MB?
