### ISSUE TITLE
Cannot delete empty folder from SFTP

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#17019]
### Steps
1. Mount an SFTP external storage to "/sftp"
1. Setup sync client
1. Create a folder "/sftp/emptyfolder"
1. Wait for sync
1. Delete the folder "/sftp/emptyfolder"
1. Wait for sync

### Expected result
Folder deleted

### Actual result
403 Forbidden

```
{"reqId":"bOAHNz1bUo6N6OukfASr","remoteAddr":"127.0.0.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 403 Forbidden\",\"Code\":0,\"Trace\":\"
#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(179): OC\\\\Connector\\\\Sabre\\\\Directory->delete()\\n
#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(287): Sabre\\\\DAV\\\\Tree->delete('sftp\\\/emptyfolde...')\\n
#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpDelete(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n
#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:DELETE', Array)\\n
#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n
#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/remote.php(84): require_once('\\\/srv\\\/www\\\/htdocs...')\\n
#8 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php\",\"Line\":240}","level":0,"time":"2015-06-18T14:46:34+00:00","method":"DELETE","url":"\/owncloud\/remote.php\/webdav\/sftp\/emptyfolder"}
```

Observed on ownCloud 8.1 git master (7a0917e5b2c25b2d90e503e30a3016dbe06a780c)

**Comment by PVince81** [comment]
Works on stable8 => regression

**Comment by PVince81** [comment]
The folder is deleted properly, but for some reason the `rmdir()` call returns false here https://github.com/owncloud/core/blob/master/lib/private/connector/sabre/directory.php#L238

**Comment by PVince81** [comment]
Looks like SFTP has its own stat cache which is not up to date for this check https://github.com/owncloud/core/blob/master/apps/files_trashbin/lib/trashbin.php#L222

**Comment by PVince81** [comment]
@bantu did phpseclib have a stat cache in the version from stable8 (0.3.6) vs master (0.3.9)

Anyway, there should be a unlink somewhere in the trashbin code which should be propagated to phpseclib, which I expect to also remove the entry from the stat cache.

Let's see what debugging shows.

**Comment by PVince81** [comment]
@bantu I debugged into phpseclib (0.3.9 used in master/8.1) and found that here https://github.com/owncloud/3rdparty/blob/master/phpseclib/phpseclib/phpseclib/Net/SFTP.php#L2128 the status is 4 ('NET_SFTP_STATUS_FAILURE') instead of OK, even though the empty folder was properly deleted remotely.

This prevents the stat cache entry to be cleared properly later.

Any idea how to debug this ? Are you able to reproduce this locally ?

**Comment by bantu** [comment]
@PVince81 Indeed, stat cache was introduced in 0.3.7 by https://github.com/phpseclib/phpseclib/commit/e09a6968da704dd26729e369b8f7a2b4a3df1a0a

**Comment by PVince81** [comment]
It seems to work fine if the folder was not empty.

So this issue is only for empty folders.

**Comment by bantu** [comment]
The fact that NET_SFTP_STATUS_FAILURE is returned for empty but existing directories is interesting. Feel free to report this to phpseclib.

**Comment by PVince81** [comment]
Raised here https://github.com/phpseclib/phpseclib/issues/706

I'll prepare a workaround

**Comment by PVince81** [comment]
PR is here https://github.com/owncloud/core/pull/17025
