### ISSUE TITLE
External folders are not sharable with change or delete permissions

### ISSUE THREAD

**Issue by patrick1990** [owncloud/core#17010]
<h4>How to reproduce:</h4>
1) Attach an external storage to the Owncloud of user1 named folderA (in my case I did this with the admin user, not with the personal external storage feature and I used local external folders).
2) Share folderA to user2. Owncloud doesn't show you the checkboxes to allow user2 to change or delete files in folderA. It just gives you the option to permit creation of files.

<h4>Actual behaviour:</h4>
user2 can just create files in folderA but he cannot modify files (not even his own created files).
But when you share a subfolder of folderA called folderB to user2 owncloud shows you all permission options and everything works like expected.

<h4>Expected behaviour:</h4>
I should be able to share base folders of external storages to other users with the option to select change or delete permissions. It seams that owncloud doen't have a problem with sharing external folders if they are subfolders.

<h4>Versions:</h4>
Owncloud: 8.0.4

**Comment by PVince81** [comment]
Possibly the similar core issue like https://github.com/owncloud/core/issues/16533

**Comment by patrick1990** [comment]
I can reproduce issue #16533 but I do not have to share the external folder to another user like I've described above in my issue. I think my problem is related with the possible-permissions Variable in core/js/share.js but I wasn't able to debug it completly.

**Comment by PVince81** [comment]
Yes, likely to be related to possible-permissions. This might be tricky to fix as it might require separating the permissions in yet another third permissions var.

**Comment by PVince81** [comment]
Related, permissions mess: #13202

**Comment by cmonteroluque** [comment]
moving to 9.0

**Comment by patrick1990** [comment]
It seams that you have solved this problem with OC 8.2.0 or 8.2.1. I'm testing OC 8.2.1 at the moment and cannot reproduce this issue anymore.

**Comment by PVince81** [comment]
@patrick1990 thanks for the update, closing.
