### ISSUE TITLE
Improve error log and response when DTSTART missing from caldav entry

### ISSUE THREAD

**Issue by GrahamCobb** [owncloud/core#17037]
I had an incorrectly formatted ical VEVENT, which was missing the (mandatory) DTSTART line.  When I tried to PUT that entry into my calendar the server response was HTTP status 500 (Internal Server Error).  Checking the apache error_log I found:

```
PHP Fatal error:  __clone method called on non-object in /var/www/owncloud/apps/calendar/lib/object.php on line 451
```

It would making finding these problems easier if owncloud could return a more useful error message and/or log a more useful error message in the log.

Of course, this is a low priority issue but it could be useful.

**Comment by RealRancor** [comment]
Hi,

the calendar app has its own issue tracker located here:

https://github.com/owncloud/calendar/issues

You could re-open there using the issue template provided here:

https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version
