### ISSUE TITLE
Cannot remove large files uploaded in Dropbox as external storage

### ISSUE THREAD

**Issue by davitol** [owncloud/core#17047]
### Steps to reproduce
1. Upload a large file using dropbox as external storage
2. Try to delete it

### Expected behaviour
The file is deleted in the dropbox folder

### Actual behaviour
The spinal keeps in the screen and the file is never removed

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:**"version":"8.1.0.7","versionstring":"8.1 RC1","edition":"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity: 1.2.3
 - admin_audit: 0.6
 - encryption: 1.0.0
 - enterprise_key: 0.1.0
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.4
 - user_ldap: 0.6.0
 - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** yes; Dropbox
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

**Comment by davitol** [comment]
owncloud.log

{"reqId":"zUgzwwPmThexwQEdbVF3","remoteAddr":"82.159.139.58","app":"PHP","message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 330832198 bytes) at \/opt\/owncloud\/apps\/files_external\/3rdparty\/Dropbox\/OAuth\/Curl.php#112","level":3,"time":"2015-06-19T11:23:44+00:00"}

**Comment by PVince81** [comment]
Does it happen if you disable the trashbin app ? ("Deleted files")

What usually happens on delete is that it will first download the file and put it into the trashbin before deleting it.

**Comment by PVince81** [comment]
It looks like this Dropbox library is downloading the file in memory !!!

@LukasReschke @DeepDiver1975 I think this is another argument that speaks for using a better library in the future.

**Comment by PVince81** [comment]
This is the line where it crashes: https://github.com/owncloud/core/blob/stable8.1/apps/files_external/3rdparty/Dropbox/OAuth/Curl.php#L112

As you can see it's not doing any streaming to file, but simply retrieves the full response from the server and puts it into memory. This cannot work with bigger files.
I'll try and find the related reports and close them as duplicate.

We need a better library.

**Comment by Xenopathic** [comment]
There's the Dropbox SDK which we could investigate?

**Comment by PVince81** [comment]
Yes, once time permits.

**Comment by PVince81** [comment]
@Xenopathic the other alternative is using flysystem's Dropbox plugin.

**Comment by PVince81** [comment]
Ok, I found the original memory ticket: https://github.com/owncloud/core/issues/4040
Let's use that one to track the lib update.

Closing as duplicate.
