### ISSUE TITLE
What is the purpose of Shibboleth admin GUI?

### ISSUE THREAD

**Issue by carlaschroder** [owncloud/core#17049]
Hey all, I just discovered that there is a Shibboleth GUI on the Admin page of oC 8.0.4. It has a checkbox to 'Activate Shibboleth' and a Save button. The Save button, as far as I can tell, doesn't actually save anything, or at least it doesn't save to a configuration file. Can someone explain what this is for and how to use it? Thanks!
![shib-gui](https://cloud.githubusercontent.com/assets/8388387/8257765/e060d7da-1664-11e5-9035-6d6714ce4e05.png)

**Comment by LukasReschke** [comment]
As far I can tell from the source: This is just there to transfer the state of the checkbox, so checking the checkbox and then clicking the button will save the state. Just checking ain't enough. Don't count my word 100% on it, also better try it before :speak_no_evil:

**Comment by carlaschroder** [comment]
@PVince81 @DeepDiver1975

**Comment by PVince81** [comment]
I have zero idea about shibboleth, sorry.

**Comment by DeepDiver1975** [comment]
It might be bad UX - but with the checkbox the admin can activate the shibboleth integration. The save button is used to save the state of the checkbox.

**Comment by carlaschroder** [comment]
thanks @DeepDiver1975 
@PVince81 I plucked your name from here https://github.com/owncloud/user_shibboleth/blob/34707a8d7302d64bdd3ce4a230f033e5fc67fde3/templates/settings.php#L19-L30
