### ISSUE TITLE
WebDAV external storage ignore MIME type & use file endings

### ISSUE THREAD

**Issue by Scindix** [owncloud/core#17059]
Hi,
I've set up a WebDAV external storage in my ownCloud 8.1 Server (root). However the provider of my WebDAV storage (1&1 in Germany) seems to return application/octet-stream as MIME for ANY file. I know that this is a bad situation, but I have no influence to that. This means that all files are displayed as binary files in ownCloud. Furthermore I can only download and upload files. I cannot play music, view photos or open text files. Can I force ownCloud to ignore the MIME type returned by the WebDAV server and use the file endings instead (like .jpg, .txt or .mp3)?

Thanks in advance.
Scindix

**Comment by DeepDiver1975** [comment]
@karlitschek might be something we can implement with the mount options.

**Comment by karlitschek** [comment]
@DeepDiver1975 yes. But I'm not are how common this behavior is. What do you think?

**Comment by DeepDiver1975** [comment]
I have recently see an issue where mimetypes are not properly taking into account on dropbox (no idea if this is a bug in our code base or a general issue) - might be worth to elaborate ...

**Comment by PVince81** [comment]
@DeepDiver1975 sometimes mime types are retrieved directly from the ext storage instead of using ownCloud's internal mime types. This is what happens with Dropbox.
Switching to use the mime type from oc_filecache usually solves the problem.

I don't think this is related to this ticket here.

**Comment by PVince81** [comment]
As per 8.2.2 and 9.0, mime types from storages aren't used any more. We only rely on ownCloud's own extension to mime type mappings instead of trusting external storages to return correct values.
