### ISSUE TITLE
Calendar Sharing : Firefox no share button (Safari OK)

### ISSUE THREAD

**Issue by LughI0** [owncloud/core#17053]
OS client : OS X 10.9.5 (Mavericks)
Browser : Firefox 38.0.5 
Bug : No way to share a calendar on Firefox, the Share button is not present : 
![firefox_38](https://cloud.githubusercontent.com/assets/12976854/8266825/4d7a6d34-1743-11e5-89b8-f956c5eff47d.png)

On Safari 7.1.5 the button is present, all is ok :
![safari_715](https://cloud.githubusercontent.com/assets/12976854/8266826/5782305a-1743-11e5-9449-6310394fb56f.png)

**Comment by RealRancor** [comment]
Hi,

@LughI0 
the issue tracker of the calendar app is located here:

https://github.com/owncloud/calendar/issues

There you can find various issues like: https://github.com/owncloud/calendar/issues/810 , https://github.com/owncloud/calendar/issues/794 , https://github.com/owncloud/calendar/issues/747

Disable Adblock and the share button should appear again.

**Comment by LughI0** [comment]
OK. Indeed, it works by disabling AddBlock.

(Is there any way to move this issue to the right GitHub project ?)

**Comment by RealRancor** [comment]
Unfortunately github don't allow to move issues. But as this is something which still needs to be fixed in the Adblock rules rather than in ownCloud you should contact the author of this ruleset.

**Comment by LughI0** [comment]
Ok. I close the topic then. 
The AdBlock is also on my Safari... So the setup not working is Firefox+AdBlock.

**Comment by RealRancor** [comment]
Hi,

it seems the "Fanboy's Social Blocking List" is causing this when reading the second link. Maybe this is just not enabled on Safari?
