### ISSUE TITLE
Feature idea: Add option to share upload-only link without sharing folder

### ISSUE THREAD

**Issue by te-online** [owncloud/core#17054]
I would like to add a feature request for the public upload option.

The request to offer users a link where they can upload files is a common scenario.
However, this is already possible with selecting »allow upload« when sharing a folder.

But, sometimes you might want the users not to see what other users uploaded or what else is contained in this folder. That is, you don't want to share a folder at all, but only a link where users can upload files to this folder.

Like Dropbox introduced few days ago.
https://blogs.dropbox.com/dropbox/2015/06/introducing-file-requests/

Maybe this could just be the change of making the »allow upload« checkbox not a conditional element that only appears when the folder is shared but an equal option to the »share folder« checkbox.

Thanks for considering this or giving feedback about it. :smile: (And I hope opening an issue here for new ideas is also okay. Maybe someone thinks this is important, too, and also feels he/she is able to implement it.)

**Comment by DeepDiver1975** [comment]
we already have that feature request somewhere in here (couldn't find it myself)

**Comment by te-online** [comment]
Wow, found multiple ones on first try now.

A few minutes ago I couldn't find anything – the correct search terms probably only ermerged to me after writing the issue :smile: 

https://github.com/owncloud/core/issues/12658
