### ISSUE TITLE
Idea: OpenID Provider

### ISSUE THREAD

**Issue by aspdye** [owncloud/core#17058]
Hi,

I think it would be cool if it would be possible to Login on "OpenID"-Sites with your OwnCloud-Account.

**Comment by RealRancor** [comment]
Hi,

not quite sure if this is what you're looking for:

https://github.com/owncloud/apps/tree/master/user_openid_provider

If yes there is an open request to make this to work with newer oC versions here: https://github.com/owncloud/apps/issues/1992
