### ISSUE TITLE
tempmanager error fill owncloud.log to large gigabyte file since 8.x

### ISSUE THREAD

**Issue by Xandersoft** [owncloud/core#17064]
iam searching for a solution to setup the "/tmp" Dir order to an rw path at /www/htdocs/...

Error	PHP	opendir(/tmp): 
failed to open dir: Permission denied at /www/htdocs/<all-inkl-account/lib/private/tempmanager.php#134

this error grow the owncloud.log into an inadmissible large file in minutes

what can i do?

**Comment by RealRancor** [comment]
Hi,

duplicate of: https://github.com/owncloud/core/issues/14886

**Comment by Xandersoft** [comment]
no access to php.ini

**Comment by RealRancor** [comment]
Nothing what you can do then except wait for oC 8.1. As there is already an open issue about this please close here.
