### ISSUE TITLE
Upload movie fail : chunking loop

### ISSUE THREAD

**Issue by francesco1119** [owncloud/core#17066]
![schermata del 2015-06-22 12 19 13](https://cloud.githubusercontent.com/assets/3397477/8274968/5c945984-18f0-11e5-9aef-78d89e56bc40.png)
![owncloud log](https://cloud.githubusercontent.com/assets/3397477/8274973/674b4630-18f0-11e5-80d9-997a18b0eb8f.jpg)

### Actual behaviour
Owncloud sync cannot upload a movie (350MB) but as the problem appears both on Windows sync and Linux sync the problem should be on the core or on my server configuration.
As you an see in the .log that I put here in attach the file is chunked:

<code>...
.mp4-chunking-1449427939-35-2
.mp4-chunking-1449427939-35-3
.mp4-chunking-1449427939-35-4
.mp4-chunking-1449427939-35-5
.... etc.</code>

until 
<code>.mp4-chunking-1449427939-35-34</code>

and then it starts again from the beginning:

<code>.mp4-chunking-1449427939-35-0</code>

### Server configuration
**Operating system**:
Ubuntu 12.04  x86_64

**Web server:**
Apache2

**Database:**
MySQL

**PHP version:**
PHP Version 5.5.25

**ownCloud version:** (see ownCloud admin page)
8.0.4 (Also previous version was affected)

**List of activated apps:**
NONE

**The content of config/config.php:**
ownCloud standard config.php file

**Are you using external storage, if yes which one:** local/smb/sftp/...
NO

**Are you using encryption:** yes/no
NO

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO

**Operating system:**

Both Linux Debian and Windows 7

#### ownCloud log (data/owncloud.log)

Just wget this file:
![owncloud log](https://cloud.githubusercontent.com/assets/3397477/8274985/ccb159b0-18f0-11e5-8d47-370656e6cc23.jpg)
and turn it to from .jpg to .log

**Comment by RealRancor** [comment]
Hi,

i think it probably won't help but to fix the first errors in the screenshot please read the description of the WebDAV user backend app and disable it.

**Comment by francesco1119** [comment]
ok, here the logs without debug
![schermata del 2015-06-22 20 48 20](https://cloud.githubusercontent.com/assets/3397477/8278518/19bdbf12-1920-11e5-9cc5-01c60d958692.png)

**Comment by DeepDiver1975** [comment]
The log file holds nothing suspicious.

Please follow the trouble shooting guide on sync issues - https://doc.owncloud.org/desktop/1.8/troubleshooting.html THX

**Comment by francesco1119** [comment]
As you suggested in others posts I've used litmus. I did have some problem with cadaver: first it connected without problem but then it give me 403

here the output with litmus

litmus http://xxx.xxx.xxx/remote.php/webdav XXX XXX
-> running `basic':
 0. init.................. pass
 1. begin................. pass
 2. options............... pass
 3. put_get............... pass
 4. put_get_utf8_segment.. pass
 5. mkcol_over_plain...... pass
 6. delete................ pass
 7. delete_null........... pass
 8. mkcol................. pass
 9. mkcol_again........... pass
10. delete_coll........... pass
11. mkcol_no_parent....... pass
12. mkcol_with_body....... pass
13. finish................ pass
<- summary for `basic': of 14 tests run: 14 passed, 0 failed. 100.0%
-> running `copymove':
 0. init.................. pass
 1. begin................. pass
 2. copy_init............. pass
 3. copy_simple........... pass
 4. copy_overwrite........ pass
 5. copy_cleanup.......... pass
 6. copy_coll............. pass
 7. move.................. pass
 8. move_coll............. pass
 9. move_cleanup.......... pass
10. finish................ pass
<- summary for `copymove': of 11 tests run: 11 passed, 0 failed. 100.0%
-> running `props':
 0. init.................. pass
 1. begin................. pass
 2. propfind_invalid...... FAIL (PROPFIND with non-well-formed XML request body failed: Could not read status line: connection was closed by server.)
 3. propfind_invalid2..... FAIL (PROPFIND with invalid namespace declaration in body (see FAQ) failed: Could not read status line: connection was closed by server.)
 4. propfind_d0........... pass
 5. propinit.............. pass
 6. propset............... pass
 7. propget............... pass
 8. propmove.............. pass
 9. propget............... pass
10. propdeletes........... pass
11. propget............... pass
12. propreplace........... pass
13. propget............... pass
14. propnullns............ FAIL (PROPPATCH of property with null namespace (see FAQ):
Could not read status line: connection was closed by server.)
15. propget............... FAIL (No value given for property {}nonamespace)
16. prophighunicode....... FAIL (PROPPATCH of property with high unicode value:
Could not read status line: connection was closed by server.)
17. propget............... FAIL (No value given for property {http://webdav.org/neon/litmus/}high-unicode)
18. propvalnspace......... FAIL (PROPPATCH of property with value defining namespace:
Could not read status line: connection was closed by server.)
19. propwformed........... FAIL (PROPFIND on `/remote.php/webdav/litmus/prop2': Could not read status line: connection was closed by server.)
20. propinit.............. pass
21. propmanyns............ FAIL (PROPPATCH on `/remote.php/webdav/litmus/prop': 400 Bad request)
22. propget............... FAIL (PROPFIND on `/remote.php/webdav/litmus/prop': 400 Bad request)
23. propcleanup........... pass
24. finish................ pass
<- summary for `props': of 25 tests run: 15 passed, 10 failed. 60.0%
See debug.log for network/debug traces.

launching litmus a second time it give me FAIL after point 2. I do think that the firewall of the machine is pushing me out, isn't it?!

**Comment by francesco1119** [comment]
I've contacted my hosting and I've told them not to blacklist my IP address.

When I do: 

make URL=http://xxx.xxxxxx/remote.php/webdav CREDS="xxx xxx" check

it says:

make: *** No rule to make target `check'.  Stop.

**Comment by francesco1119** [comment]
Installed litmus properly thanks to this guide: https://forum.owncloud.org/viewtopic.php?f=8&t=21185&p=90519#p90519

make URL=http://xxx.xxx.xxx/remote.php/webdav CREDS="xxx xxx" check
make[1]: Entering directory `/usr/src/litmus-0.13/lib/neon'
Bundled neon build not being used.
make[1]: Leaving directory `/usr/src/litmus-0.13/lib/neon'
gcc  -o basic src/basic.o -L. -ltest -lneon-gnutls  
gcc  -o copymove src/copymove.o -L. -ltest -lneon-gnutls  
gcc  -o props src/props.o -L. -ltest -lneon-gnutls  
gcc  -o locks src/locks.o -L. -ltest -lneon-gnutls  
gcc  -o http src/http.o -L. -ltest -lneon-gnutls  
-> running `basic':
 0. init.................. pass
 1. begin................. pass
 2. options............... pass
 3. put_get............... pass
 4. put_get_utf8_segment.. pass
 5. put_no_parent......... pass
 6. mkcol_over_plain...... pass
 7. delete................ pass
 8. delete_null........... pass
 9. delete_fragment....... WARNING: DELETE removed collection resource with Request-URI including fragment; unsafe
    ...................... pass (with 1 warning)
10. mkcol................. pass
11. mkcol_again........... pass
12. delete_coll........... pass
13. mkcol_no_parent....... pass
14. mkcol_with_body....... pass
15. finish................ pass
<- summary for `basic': of 16 tests run: 16 passed, 0 failed. 100.0%
-> 1 warning was issued.
-> running `copymove':
 0. init.................. pass
 1. begin................. pass
 2. copy_init............. pass
 3. copy_simple........... pass
 4. copy_overwrite........ pass
 5. copy_nodestcoll....... pass
 6. copy_cleanup.......... pass
 7. copy_coll............. pass
 8. copy_shallow.......... pass
 9. move.................. pass
10. move_coll............. pass
11. move_cleanup.......... pass
12. finish................ pass
<- summary for `copymove': of 13 tests run: 13 passed, 0 failed. 100.0%
-> running `props':
 0. init.................. pass
 1. begin................. pass
 2. propfind_invalid...... FAIL (PROPFIND with non-well-formed XML request body failed: Could not read status line: connection was closed by server)
 3. propfind_invalid2..... FAIL (PROPFIND with invalid namespace declaration in body (see FAQ) failed: Could not read status line: connection was closed by server)
 4. propfind_d0........... pass
 5. propinit.............. pass
 6. propset............... pass
 7. propget............... pass
 8. propextended.......... FAIL (PROPFIND on `/remote.php/webdav/litmus/prop': Could not read status line: connection was closed by server)
 9. propmove.............. pass
10. propget............... pass
11. propdeletes........... pass
12. propget............... pass
13. propreplace........... pass
14. propget............... pass
15. propnullns............ FAIL (PROPPATCH of property with null namespace (see FAQ):
Could not read status line: connection was closed by server)
16. propget............... FAIL (No value given for property {}nonamespace)
17. prophighunicode....... FAIL (PROPPATCH of property with high unicode value:
Could not read status line: connection was closed by server)
18. propget............... FAIL (PROPFIND on `/remote.php/webdav/litmus/prop2': 403 OK)
19. propremoveset......... FAIL (PROPPATCH remove then set)
20. propget............... FAIL (PROPFIND on `/remote.php/webdav/litmus/prop2': 403 OK)
21. propsetremove......... FAIL (PROPPATCH remove then set)
22. propget............... FAIL (PROPFIND on `/remote.php/webdav/litmus/prop2': 403 OK)
23. propvalnspace......... FAIL (PROPPATCH of property with value defining namespace)
24. propwformed........... pass
25. propinit.............. FAIL (PUT of `�z?': 403 OK)
26. propmanyns............ FAIL (PROPPATCH on `/remote.php/webdav/litmus/prop': 403 OK)
27. propget............... FAIL (PROPFIND on `/remote.php/webdav/litmus/prop': 403 OK)
28. propcleanup........... pass
29. finish................ pass
<- summary for `props': of 30 tests run: 15 passed, 15 failed. 50.0%
See debug.log for network/debug traces.
make: *** [check] Error 1

**Comment by DeepDiver1975** [comment]
@francesco1119 Thanks a lot for the detailed report. For each FAIL on litmus I'd expect at least one matching log entry in data/owncloud.log

**Comment by francesco1119** [comment]
What should I search for in the .log file here in attach?

![owncloud](https://cloud.githubusercontent.com/assets/3397477/8444425/74b41e3c-1fe4-11e5-9442-1726012b6340.png)

**Comment by Kawohl** [comment]
Closing because of no information since three months.
