### ISSUE TITLE
owncloud 6 to 8 ---> having difficulty 

### ISSUE THREAD

**Issue by superinterstellar** [owncloud/core#17062]
I am getting an error as follows:-

anyone can help me solve this? 

An exception occurred while executing 'UPDATE "oc_filecache" SET "mtime" = ?, "etag" = ?, "storage_mtime" = ?, "permissions"=? WHERE ("mtime" <> ? OR "etag" <> ? OR "storage_mtime" <> ? OR "permissions" <> ? ) AND "fileid" = ? ': SQLSTATE[HY000]: General error: 1 no such column: storage_mtime

Thanks
Kevin

**Comment by RealRancor** [comment]
Hi,

have you done the following upgrade steps:

Your oC 6.0.x version -> oC 6.0.8 -> oC 7.0.6 -> oC 8.0.4

as described in the upgrading manuals?

**Comment by PVince81** [comment]
Closing due to lack of information.

See https://github.com/owncloud/core/issues/17062#issuecomment-113928518

If you're still having issues, feel free to reopen and use the issue template https://raw.githubusercontent.com/owncloud/core/master/issue_template.md
