### ISSUE TITLE
link-sharing a shared folder already link-shared by owner does not work

### ISSUE THREAD

**Issue by jospoortvliet** [owncloud/core#17069]
### Steps to reproduce
1. create a folder and share a public link (enable 'editing' for uploading).
2. Upload some files in the folder via the public link in an anonymous browser window
3. share the folder with another user. Enable editing, sharing.
4. log in as other user and try to share the folder via a link. 

Enjoy the spinner, but don't expect any actual progress ;-)

### Expected behaviour
You should be able to share the folder

### Actual behaviour
You look at a nice spinner for a while until you give up

### Server configuration
**Operating system**:
openSUSE Tumbleweed (rolling release)

**Web server:**
Apache 2.4.12

**Database:**
MariaDB 10.0.17

**PHP version:**
5.6.9

*ownCloud version:** (see ownCloud admin page)
daily snapshot from 22-6-2015

**Updated from an older ownCloud or fresh install:**
Updated from daily snapshot from last week, which was a fresh install

**List of activated apps:**
Files/activity/pictures

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'oc7jqt7p8otl',
  'trusted_domains' =>
  array (
    0 => 'localhost',
  ),
  'datadirectory' => '/srv/www/htdocs/owncloud/data',
  'overwrite.cli.url' => 'http://localhost/owncloud',
  'dbtype' => 'sqlite3',
  'version' => '8.1.0.7',
  'logtimezone' => 'UTC',
  'installed' => true,
  'loglevel' => 0,
  'maintenance' => false,
);

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
There is a folder with local external storage

**Are you using encryption:**
no

**Are you using an external user-backend
No

### Client configuration
**Browser:**
Firefox
**Operating system:**
openSUSE Linux
#### Web server error log
```
[Mon Jun 22 11:15:09.424568 2015] [php5:error] [pid 4802] [client ::1:49944] PHP Fatal error:  Call to a member function format() on string in /srv/www/htdocs/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Types/DateTimeType.php on line 53, referer: http://localhost/owncloud/index.php/apps/files/?dir=%2F
[Mon Jun 22 11:16:18.347283 2015] [authz_core:error] [pid 27468] [client ::1:49976] AH01630: client denied by server configuration: /srv/www/htdocs/owncloud/data/htaccesstest.txt
[Mon Jun 22 11:16:27.398332 2015] [php5:error] [pid 27636] [client ::1:49977] PHP Fatal error:  Call to a member function format() on string in /srv/www/htdocs/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Types/DateTimeType.php on line 53, referer: http://localhost/owncloud/index.php/apps/files/?dir=%2F
[Mon Jun 22 11:19:30.189788 2015] [authz_core:error] [pid 27469] [client ::1:50088] AH01630: client denied by server configuration: /srv/www/htdocs/owncloud/data/htaccesstest.txt
[Mon Jun 22 11:39:39.816682 2015] [authz_core:error] [pid 27309] [client ::1:50340] AH01630: client denied by server configuration: /srv/www/htdocs/owncloud/data/htaccesstest.txt
[Mon Jun 22 11:39:58.203148 2015] [authz_core:error] [pid 4802] [client ::1:50351] AH01630: client denied by server configuration: /srv/www/htdocs/owncloud/data/htaccesstest.txt
[Mon Jun 22 11:40:33.228538 2015] [php5:error] [pid 27467] [client ::1:50359] PHP Fatal error:  Call to a member function format() on string in /srv/www/htdocs/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Types/DateTimeType.php on line 53, referer: http://localhost/owncloud/index.php/apps/files/?dir=%2F
[Mon Jun 22 11:40:44.914871 2015] [authz_core:error] [pid 27469] [client ::1:50371] AH01630: client denied by server configuration: /srv/www/htdocs/owncloud/data/htaccesstest.txt
```

#### ownCloud log (data/owncloud.log)
```
Error 	PHP 	Call to a member function format() on string at /srv/www/htdocs/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Types/DateTimeType.php#53 	2015-06-22T09:40:33+00:00
Debug 	files_locking 	INFO: Incrementing lock type 1 count for /srv/www/htdocs/owncloud/data/RosaLuxemburg/avatar.jpg 	2015-06-22T09:40:31+00:00
Debug 	files_locking 	INFO: Incrementing lock type 1 count for /srv/www/htdocs/owncloud/data/RosaLuxemburg/avatar.jpg 	2015-06-22T09:40:31+00:00
Debug	files_locking	INFO: Incrementing lock type 1 count for /srv/www/htdocs/owncloud/data/RosaLuxemburg/avatar.jpg	2015-06-22T09:40:31+00:00
Debug	files_locking	PASS: Acquired read lock for /srv/www/htdocs/owncloud/data/RosaLuxemburg/avatar.jpg	2015-06-22T09:40:31+00:00
Debug	files_locking	INFO: Read lock requested for /srv/www/htdocs/owncloud/data/RosaLuxemburg/avatar.jpg	2015-06-22T09:40:31+00:00
Error	PHP	Array to string conversion at /srv/www/htdocs/owncloud/lib/private/template/functions.php#36	2015-06-22T09:39:54+00:00
```

#### Browser log
```
GET 
XHR 
http://localhost/owncloud/index.php/core/ajax/share.php [HTTP/1.1 200 OK 98ms]
GET 
XHR 
http://localhost/owncloud/index.php/avatar/RosaLuxemburg/28.65671730041504 [HTTP/1.1 200 OK 105ms]
POST 
XHR 
http://localhost/owncloud/index.php/core/ajax/share.php [HTTP/1.0 500 Internal Server Error 95ms]
```

**Comment by PVince81** [comment]
@schiesbn @rullzer

**Comment by jospoortvliet** [comment]
btw you don't need to give editing rights, a folder which is shared by a public link can not be shared again by another person via a public link.

(that in itself might be fine - it's a restriction which makes sense, but then it should give an error, not hang)

**Comment by jospoortvliet** [comment]
![video](https://cloud.githubusercontent.com/assets/551757/8279948/ef61cde0-18d8-11e5-99ee-8a5ba06da938.gif)
Because I was making video anyway - here's a gif showing what's wrong ;-)

**Comment by rullzer** [comment]
@jospoortvliet are you just randomly clicking away to break stuff? ;)

I'll have a look soon.

**Comment by jospoortvliet** [comment]
@rullzer I represent a 100 monkeys clicking away randomly, yes ;-)

**Comment by rullzer** [comment]
@jospoortvliet I can't reproduce this using your steps on my machine.
I also can't reproduce this using the OCS Share API.

**Comment by jospoortvliet** [comment]
I can indeed no longer reproduce this on the latest daily snapshot (today). Looks like it is fixed!

**Comment by nazar-pc** [comment]
I have the same on ownCloud 8.1 stable:
* share directory to some group of users
* login as one of users from that group of user
* click sharing, try to share link

Also have infinite spinner, 500 error and the same info in log:
> Call to a member function format() on string at /usr/share/nginx/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Types/DateTimeType.php#53

This issue is 100% reproducible using Docker as described here: https://github.com/nazar-pc/docker-webserver-apps/tree/master/owncloud

Was it fixed after release?

**Comment by nazar-pc** [comment]
However, re-sharing to other users and groups works fine

**Comment by jospoortvliet** [comment]
It was fixed before release -so the problem you have must be caused by something else.

**Comment by rullzer** [comment]
@nazar-pc that seems to be a different issue.
However, I can't repoduce your issue with the steps you describe... not on 8.1 (release) and the stable 8.1 branch (future 8.1.1). I haven't tried your docker images.

Could you check if the problem is persistent with the stable8.1 branch?

**Comment by nazar-pc** [comment]
@rullzer, just tried fresh installation from Docker image - it works, I'm investigating how to reproduce issue, since it definitely present (on another installation of exactly the same version), but happens under certain conditions.

**Comment by nazar-pc** [comment]
OK, some more details.
For whatever reason `$value` has string `2015-07-28 00:00:00` in it instead of `\DateTime` instance.
Here is backtrace from error place:
```
Array
(
    [0] => Array
        (
            [file] => /usr/share/nginx/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php
            [line] => 114
            [function] => convertToDatabaseValue
            [class] => Doctrine\DBAL\Types\DateTimeType
            [type] => ->
        )

    [1] => Array
        (
            [function] => bindValue
            [class] => Doctrine\DBAL\Statement
            [type] => ->
        )

    [2] => Array
        (
            [file] => /usr/share/nginx/html/owncloud/lib/private/db/statementwrapper.php
            [line] => 57
            [function] => call_user_func_array
        )

    [3] => Array
        (
            [file] => /usr/share/nginx/html/owncloud/lib/private/share/share.php
            [line] => 2228
            [function] => __call
            [class] => OC_DB_StatementWrapper
            [type] => ->
        )

    [4] => Array
        (
            [file] => /usr/share/nginx/html/owncloud/lib/private/share/share.php
            [line] => 2228
            [function] => bindValue
            [class] => OC_DB_StatementWrapper
            [type] => ->
        )

    [5] => Array
        (
            [file] => /usr/share/nginx/html/owncloud/lib/private/share/share.php
            [line] => 2086
            [function] => insertShare
            [class] => OC\Share\Share
            [type] => ::
        )

    [6] => Array
        (
            [file] => /usr/share/nginx/html/owncloud/lib/private/share/share.php
            [line] => 754
            [function] => put
            [class] => OC\Share\Share
            [type] => ::
        )

    [7] => Array
        (
            [file] => /usr/share/nginx/html/owncloud/lib/public/share.php
            [line] => 264
            [function] => shareItem
            [class] => OC\Share\Share
            [type] => ::
        )

    [8] => Array
        (
            [file] => /usr/share/nginx/html/owncloud/core/ajax/share.php
            [line] => 63
            [function] => shareItem
            [class] => OCP\Share
            [type] => ::
        )

    [9] => Array
        (
            [file] => /usr/share/nginx/html/owncloud/lib/private/route/route.php(154) : runtime-created function
            [line] => 1
            [args] => Array
                (
                    [0] => /usr/share/nginx/html/owncloud/core/ajax/share.php
                )

            [function] => require_once
        )

    [10] => Array
        (
            [function] => __lambda_func
        )

    [11] => Array
        (
            [file] => /usr/share/nginx/html/owncloud/lib/private/route/router.php
            [line] => 274
            [function] => call_user_func
        )

    [12] => Array
        (
            [file] => /usr/share/nginx/html/owncloud/lib/base.php
            [line] => 867
            [function] => match
            [class] => OC\Route\Router
            [type] => ->
        )

    [13] => Array
        (
            [file] => /usr/share/nginx/html/owncloud/index.php
            [line] => 40
            [function] => handleRequest
            [class] => OC
            [type] => ::
        )

)
```

`2015-07-28` is anyway a weird date, which is less than 4 days from todays `2015-07-24` and I have required expiration time set to 7 days be default.

Still working on figuring out where and why that happens.

**Comment by nazar-pc** [comment]
OK, I found that expiration date format becomes incorrect here: https://github.com/owncloud/core/blob/master/lib/private/share/share.php#L2162

While `$expirationDate` is a correct `\DateTime` instance, `$checkReshare['expiration']` is string with weird `2015-07-28 00:00:00` value.

`\OC\Share\Share::getItems()` method seems to be extremely complex and barely maintainable, can anyone from the core team check what happens there?

**Comment by rullzer** [comment]
crap... I was hoping not to touch getItems for a long time. I'll try to find some time this weekend.

**Comment by rullzer** [comment]
@nazar-pc ok I still can't reproduce this. I have an idea what might be going on but it is hard to test ;)

I'm going to close this issue since the original issue is fixed. Could you open a new issue so we can keep proper track of it? And update the steps to reproduce etc.

**Comment by nazar-pc** [comment]
@rullzer, combined from comments into #17867

**Comment by PVince81** [comment]
@MorrisJobke is your PR https://github.com/owncloud/core/pull/17489 related to this issue ?
