### ISSUE TITLE
files:scan does not scan external storage using the --path option

### ISSUE THREAD

**Issue by matzex** [owncloud/core#17067]
This issue were discussed in #14507 already.

### Steps to reproduce
1. use an external storage provider like Dropbox
2. execute the files:scan command on the external folder:
`./occ files:scan --path /user/files/oc/Dropbox`
3. see the command line output, the external storage folders are not scanned

### Expected behaviour
The external storage folders should be scanned. The external storage folders are scanned if you use the --all option but then every time the whole storage has to be scanned what needs more resources.

### Actual behaviour
The external storage folders are not scanned.

### Server configuration
**Operating system**: Ubuntu 12.04.1 LTS, Kernel: 2.6.32-042stab092.3
**Web server:** Apache/2.2.22 (Ubuntu)
**Database:** mysqld 5.5.43-0ubuntu0.12.04.1
**PHP version:** 5.4.42-1+deb.sury.org~precise+1

**ownCloud version:** 8.0.4 (stable) 

**Updated from an older ownCloud or fresh install:** updated several times

**List of activated apps:**
Calendar, Contacts, News, Roundcube, External Storage Support, PDF Viewer, Share Files, Updater
**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => '51eecfbd4d1a0',
  'passwordsalt' => 'salt',
  'datadirectory' => '/var/www/example.com/cloud/data',
  'dbtype' => 'mysql',
  'version' => '8.0.4.2',
  'dbname' => 'dbname',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'dbuser',
  'dbpassword' => 'dbpassword',
  'installed' => true,
  'maxZipInputSize' => 0,
  'allowZipDownload' => true,
  'loglevel' => 0,
  'theme' => '',
  'maintenance' => false,
  'forcessl' => true,
  'trashbin_retention_obligation' => '1',
  'trusted_domains' => 
  array (
    0 => 'cloud.example.com',
  ),
  'mail_smtpmode' => 'php',
  'mail_from_address' => 'mail',
  'mail_domain' => 'example.com',
  'appcodechecker' => false,
  'secret' => 'xxx',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
Dropbox
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

I don't know if this issue affects also other external storages than Dropbox but i would expect this as a general problem with the --path option from files:scan.

**Comment by DeepDiver1975** [comment]
> This issue were discussed in #14507 already.

so why open a new issue then?

**Comment by DeepDiver1975** [comment]
> so why open a new issue then?

ah - sorry

**Comment by PVince81** [comment]
CC @icewind1991

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/17077

**Comment by matzex** [comment]
Thanks, i tried it and the fix works for me.

**Comment by jvillafanez** [comment]
Validated for 8.2 and 8.1.1. No plans to backport to earlier versions, I guess

**Comment by jvillafanez** [comment]
Please remove the "approved by qa" label if there are plans to backport to 8.0.x and 7.0.x
