### ISSUE TITLE
webdav - no connection to Cloud with Android-App since v8.0.3

### ISSUE THREAD

**Issue by Xandersoft** [owncloud/core#17063]
+ work on v8.02
- not work on updated v8.03 and v8.04
Provider: all-inkl.com

Debug Report:

Debug	webdav	Exception: 
{"Message":"No basic authentication headers were found","Code":0,"Trace":"#0 \/www\/htdocs\<all-inkl-account>\/lib\/private\/connector\/sabre\/auth.php(126): Sabre\\DAV\\Auth\\Backend\\AbstractBasic->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')\n#1 \/www\/htdocs\<all-inkl-account>\/lib\/private\/connector\/sabre\/auth.php(106): OC_Connector_Sabre_Auth->auth(Object(OC_Connector_Sabre_Server), 'ownCloud')\n#2 \/www\/htdocs\<all-inkl-account>\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Auth\/Plugin.php(108): OC_Connector_Sabre_Auth->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')\n#3 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod('HEAD', '')\n#4 \/www\/htdocs\<all-inkl-account>\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(433): call_user_func_array(Array, Array)\n#5 \/www\/htdocs\<all-inkl-account>\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(455): Sabre\\DAV\\Server->broadcastEvent('beforeMethod', Array)\n#6 \/www\/htdocs\<all-inkl-account>\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(214): Sabre\\DAV\\Server->invokeMethod('HEAD', '')\n#7 \/www\/htdocs\<all-inkl-account>\/apps\/files\/appinfo\/remote.php(61): Sabre\\DAV\\Server->exec()\n#8 \/www\/htdocs\<all-inkl-account>\/remote.php(54): require_once('\/www\/htdocs\/w01...')\n#9 {main}","File":"\/www\/htdocs\<all-inkl-account>\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Auth\/Backend\/AbstractBasic.php","Line":73}

help please

**Comment by RealRancor** [comment]
Hi,

very likely caused by: https://github.com/owncloud/core/issues/17064 which duplicates https://github.com/owncloud/core/issues/14886

**Comment by Xandersoft** [comment]
the problem with the tempfilemanager is older than the webdav problem. on v8.0.2 works the webdav connection.

**Comment by DeepDiver1975** [comment]
> {"Message":"No basic authentication headers were found","Code":0,"Trace":"#0 \/www\/htdocs<all-

hmmm ... hard to tell the cause of this.

Can you connect to your web dav url using a regular webdav client (e.g. cadaver on linux)?
You might want to run the libneon litmus test suite against your server.

**Comment by PVince81** [comment]
Closing due to lack of feedback
