### ISSUE TITLE
SELinux labels for assets in CentOS/RHEL/Fedora builds

### ISSUE THREAD

**Issue by mrflow** [owncloud/core#17065]
The assets folder will need a `httpd_sys_rw_content_t` label for the asset management feature to work.

sadly, i could not find the rpmspec on github, but the change should be as follows:

```
557a558,559
>     semanage fcontext -a -t httpd_sys_rw_content_t '%{oc_dir}/assets'
>     restorecon '%{oc_dir}/assets'
```

**Comment by RealRancor** [comment]
Hi,

the source code of the files to build the packages are located here:

https://build.opensuse.org/package/view_file/isv:ownCloud:community:8.0/owncloud/owncloud.spec

You could also report this to:

https://github.com/owncloud/documentation/issues

to also get this included in the official documentation.

**Comment by mrflow** [comment]
Hi RealRancor,

I already found the owncloud rpm spec there (actually the patch I included is to be applied on that file). I just find it confusing that these files are not maintained here on github (I guess there will be some reason for that).

It should not be documented, it should be fixed. Otherwise the label will disappear after every update, and no assets can be loaded (ownCloud web interface will be completely unfunctional – happened to me because I switched to 8.1-nightly builds).

**Comment by RealRancor** [comment]
Hi,

> It should not be documented, it should be fixed.

not everyone is using the OBS packages

**Comment by mrflow** [comment]
Hi, 

yes you're right, didn't realize there was a documentation for doing this manually

**Comment by MorrisJobke** [comment]
cc @jnweiger

**Comment by jnweiger** [comment]
Thanks for the selinux input!
I tried to guess the exact location for the patch. Please double check this:
https://build.opensuse.org/package/rdiff/isv:ownCloud:community:8.0:testing/owncloud?linkrev=base&rev=8

If it is correct, I'll roll that out to all branches.

**Comment by jnweiger** [comment]
We already have a git repository for the owncloud-client meta files, the same for the server is still to be done. Menawhile I am collecting bits in here: 

https://github.com/owncloud/administration/tree/master/jenkins/obs_integration/templates/owncloud

**Comment by RealRancor** [comment]
I'm not familiar with SElinux but what happens if the asset folder don't exist during the initial setup?

**Comment by mrflow** [comment]
@jnweiger: That should do the job, the place in %postun config-apache has escaped me yesterday.

one slightly pedantic change i would propose is retaining the same order for the four directories in both scriptlets (i.e. data, config, apps, assets).

**Comment by jnweiger** [comment]
@RealRancor I am not familiar with SElinux either, but I have an easy answer: Both, DEB and RPM setup assert that the assets folder is preset.  :-)

**Comment by mrflow** [comment]
So i updated the latest nightly rpm package for centos 7. Looks like the change took effect.

I'm closing this. Thanks!
