### ISSUE TITLE
Prefer scalar types (PHP 7) instead of PHPdoc annotations if available

### ISSUE THREAD

**Issue by BernhardPosselt** [owncloud/core#17076]
Currently you can use PHPdoc annotations to tell the controller to which types the incoming parameters should be casted too, e.g.

```php
/**
 * @param int $id
 */
public function destroy($id)
```

would cast the $id parameter to an int before it is passed into the method

In PHP you've got scalar type hints, meaning: int, bool, float. For more information see https://wiki.php.net/rfc/scalar_type_hints_v5

Now if a scalar type is given that one should be preferred. The following example would be identical to the one above:

```php
public function destroy(int $id)
```

In case we've got both, we should prefer the scalar type hint and log a warning in debug mode, e.g.:

```php
/**
 * @param int $id
 */
public function destroy(float $id)
```

would cast to a float instead of int

Why do we need to handle this? Certain requests like GET or POST with form data submit all data as strings. By convention we cast the string 'false' to the boolean false if an annotation is given. This can not be done by the internal PHP 7 casting in non strict mode.

@LukasReschke @DeepDiver1975 @MorrisJobke @ChristophWurst @Xenopathic @PVince81

**Comment by DeepDiver1975** [comment]
But this code will then no longer work on pre-php7 - right?

So I don't see this happening that soon.

**Comment by Raydiation** [comment]
Fully optional of course
