### ISSUE TITLE
Log all upgrade events during upgrade

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#17089]
Have a look at all the listened events in https://github.com/owncloud/core/blob/2654696086988c11c57cc9d72579ce3912aa08c6/core/command/upgrade.php#L121-L166 and add listeners for this to [updater class](https://github.com/owncloud/core/blob/master/lib/private/updater.php). These listeners then log everything. Then web and CLI based updates are fully logged in case of a failure and it doesn't need to rerun the upgrade with a verbose command line option.

I just came to this, because often the upgrade is run and something bad happens. Then you need to reproduce this and add all the listeners and make the upgrade verbose. Logging this directly would help a lot of people I think

Opinions on this?

@LukasReschke @nickvergessen @DeepDiver1975 @karlitschek @rullzer @jancborchardt @Xenopathic @schiesbn @icewind1991 @PVince81 

@RealRancor Maybe you have interesting insights from the forum ;)

**Comment by MorrisJobke** [comment]
ref #17088

**Comment by karlitschek** [comment]
yes. completely agreed!!!

**Comment by schiesbn** [comment]
agreed, I think it makes totally sense to log this stuff. Especially for a update which is executed only once I would rather log too much than too little to have as much information as possible if something goes wrong.

**Comment by RealRancor** [comment]
Sounds a good idea :+1: 

Had also some additional requests of users in the forums to make the upgrade steps more verbose as often the questions where asked like "what is the update process currently doing".

**Comment by oparoz** [comment]
Finally! :)
This should make it much easier to quickly pinpoint where the upgrade goes wrong...

Would it be possible to change the log level to 0 and turn debug mode on in verbose mode (if it's not done already)?

**Comment by PVince81** [comment]
@MorrisJobke didn't we add something recently that changes log level to debug then back during an upgrade ?

**Comment by MorrisJobke** [comment]
> @MorrisJobke didn't we add something recently that changes log level to debug then back during an upgrade ?

Yes. https://github.com/owncloud/core/pull/19441
