### ISSUE TITLE
Move the rename icon back with the other file actions

### ISSUE THREAD

**Issue by KenBW2** [owncloud/core#17086]
The variable length of file/folder names means that the position of the rename icon moves depending on which row you're hovering over.

This means it's difficult to click a row to open a folder because you quite often end up accidentally clicking Rename.

It'd be nice if it was in a predictable position so that clicking the file/folder itself was less of a gamble

**Current**

![files](https://cloud.githubusercontent.com/assets/366540/8291437/86062834-1921-11e5-8607-617fa96b149e.png)

**With Rename as FileAction**

![files-2](https://cloud.githubusercontent.com/assets/366540/8291503/f8aa863c-1921-11e5-861e-bcc6f8ec2d8f.png)

**Comment by LukasReschke** [comment]
@jancborchardt

**Comment by jancborchardt** [comment]
This will be solved with moving the action buttons into a dropdown, to also make it usable on smaller screens and tablets, see https://github.com/owncloud/core/issues/12081

@KenBW2 I’m closing this as we can continue there. :)

**Comment by KenBW2** [comment]
As long as rename is moved over to the right, rather than next to the filename, then fine by me

**Comment by jancborchardt** [comment]
@KenBW2 great! Thanks a lot for the feedback. You’re very welcome in our IRC channel #owncloud-design, and if you notice any other design issues please don’t hesitate to let us know. :)
