### ISSUE TITLE
Cache folder content instead of getting it from the server every time

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#17080]
Every time we enter a folder, a request is made to `apps/files/ajax/list.php` in order to get data to build the view.
It can take between 100ms and 500ms to get that information (on top of the time it takes to connect) on a fast server, depending on the folder's content. Probably much more on a Raspberry.

It turns out that even a 100ms delay is noticeable when you do a A/B comparison.

I propose the following change:
- cache the data structures which are built after receiving fresh data. It might not be possible to cache everything because of the memory it would require I guess.
- send the folder's etag to `list.php`
- the server returns an empty files array if the etag is the same as the current one
- the client uses either the cache or the fresh data, depending on if there's been an etag change or not

Letting the Files experts decide if that's feasible and worth it
@schiesbn @PVince81 @butonic @LukasReschke @icewind1991 @DeepDiver1975

**Comment by oparoz** [comment]
This is also a talk about UX, so including @jancborchardt .

**Comment by icewind1991** [comment]
Another option would be to have the etag of the folder folder in the html of the files app so the js can determine whether it's cache is still up to date.

That way the client doesn't need to do any requests if the folder hasn't changed

**Comment by oparoz** [comment]
That would be great, but how is the etag updated in the HTML? If that's via a 15 minutes cron per example, that might not be the most reliable solution. If etags are pushed in real time via EventSource, then that would work really well.

**Comment by jancborchardt** [comment]
Yeah – as a general rule any delay / load time significantly more than 100ms is annoying to people and makes the app feel sluggish. Good call to improve performance here @oparoz

**Comment by PVince81** [comment]
@icewind1991 Bäääh no etags in html templates, but I get your point. Yes, checking the etag would work.

@oparoz forget about "list.php", PROPFIND is the future :wink: (see #12353)

I think you don't need a cron update. If we have a file list cache on the JS side like @oparoz proposed, then every time you open a folder you send a PROPFIND with the existing etag. If the etag did not change, no result is returned. Hmm, but that request itself might still take some time.

**Comment by oparoz** [comment]
Yeah, I don't know how much time a PROPFIND request takes to complete.

In Gallery, I implemented what I described in the OP, but shaving another 50-100ms by not having to do any HTTP request is tempting.

**Comment by DeepDiver1975** [comment]
Out of scope for 8.2 (where we will move to webdav in the files app) - something to work on after 8.2 - THX

**Comment by oparoz** [comment]
:ok:

**Comment by jancborchardt** [comment]
Maybe time to create an 8.3 milestone so we can already scope it a bit?

**Comment by ckruetze** [comment]
Just a comment from a user point.
To get around the problem that PROPFIND request with an empty result (as suggested above)
How about this:
1) If a js cache exists, show it, if not create it first and then show it.
2) at the same time as 1) start an async job to send the PROPFIND and see if the etag changed
3a) If it didn't change done, the use has a fast js cached list
3b) If it did change, update the js cache and redraw the screen to get the updated version to the user.

There won't be a visible delay for the user, the only thing that could happen is the user sees an outdated folder for a very short while (until the cache is updated and the list is reloaded), but it is very likely that not everything is outdated, so the user might not even notice that something changed.

**Comment by jancborchardt** [comment]
@ckruetze yeah, very good call! Show what’s in the cache first and check for new stuff in the background – how most normal desktop apps with network services do it as well. :)

**Comment by oparoz** [comment]
@ckruetze - That only works if you're able to insert new elements without having to do a full refresh. Not sure Files is capable of doing that yet.

For Gallery, I intend on using Redis to keep the cache constantly updated. That way, every time you make a request, you know if your cache is valid or not and when the view is idling, you can show a notification letting the user know he should click on the refresh button.

**Comment by jancborchardt** [comment]
@oparoz you want to use Redis? That'll introduce a requirement which is not likely to be on all servers, eh? Hope that's optional cc @DeepDiver1975

**Comment by oparoz** [comment]
It's already a requirement for file locking, that's why I'm thinking of using it. But it will only be used to improve the performance of the app, not to introduce new features.

**Comment by PVince81** [comment]
@oparoz redis is only for the first beta version of file locking. A database backend might be provided later.

The FileList class supports inserting elements on the fly. But this means you'd need to do a diff between the cached list and the newly received list and then update according. Might as well refresh the whole list instead.

**Comment by oparoz** [comment]
A database backend would prolly not work for what I want to do, so that would be a new optional requirement.

@PVince81, If you listen for specific event, you don't need to diff anything, you just insert, delete, modify the element. Events can be throttled and the GUI even "frozen", with a warning shown to the user if the queue gets too long. Not really possible to implement in Gallery because of the layout, but shouldn't be hard to do with a files list.
But the first step would simply be to invalidate the cache, no diff there either. The goal is to avoid making HTTP requests if they're not absolutely needed.

**Comment by jancborchardt** [comment]
cc @MTRichards @PVince81 @DeepDiver1975 I’d suggest to keep this in mind for 9.1 maybe to improve performance in browsing files.

**Comment by MTRichards** [comment]
Yeah, we have to finish the webdav consolidation first. Then we can work on this for 9.1. A UI performance improvement would be nice to see, if a cache proves faster. Interested in @DeepDiver1975 and @karlitschek input on the likely performance impacts as well.

**Comment by PVince81** [comment]
or cache on redis level ? @DeepDiver1975 @butonic

**Comment by PVince81** [comment]
Moving this to backlog for now.

@DeepDiver1975 @butonic if you had another ticket about your idea regarding caching filesystem view from the user's perspective, please link it here.
