### ISSUE TITLE
Request - Drop box (not the company Dropbox), aka deposit box, function

### ISSUE THREAD

**Issue by petrasteri** [owncloud/core#17084]
Currently, when someone wants to give me some (big) files, eg his photos in the last journey, this is usually what he will do:
1. Attach the file(s) in a mail and send it to me, or
    Upload the file(s) to some cloud-based file-hosting services like, ahem, OndDrive, Sendspace, Box, etc, and send me the link via email

2. I open the mail.  Either I save the attached file(s) inside my computer or I open the link to download the file(s) inside my computer

3. I upload the file(s) to my ownCloud server!

I'm thinking, why couldn't we skip all these and let the user upload the files directly to my ownCloud account??

That's the idea of having a drop box (no relationship with the company called Dropbox), or if you like, deposit box.

The implementation can be like this:
* The person opens a link, preferably easy to remember by me or my friends (http://my-owncloud-server/my-user-name/dropbox would be fine) and uploads the files to me
* The server puts the file in a "quarantine" area while waiting for my approval.  The server could send me a notification mail.
* When I login to my ownCloud account, I can go to the "quarantine" area and choose what file I accept (otherwise, I could delete them) and where to move to.

Alternatively, if http connection if not possible for the sender, ownCloud server could propose FTP, mail or some other means, but I reckon that these alternatives might be hard to implement.  So we could put this part aside.

Someone might warn us of possible upload flooding and make our ownCloud account reach the quota.  That's true.  But that's also true for mail -- someone might send a lot of mails and flood my mailbox.  Currently, I don't see any remedy to this mail problem, so I don't expect there's any perfect solution to the dropbox.  But of course, we could and should implement files size limit.  1GB limit for all the files in one upload should be a good and acceptable limit.

What do you think of this?

**Comment by RealRancor** [comment]
Related: https://github.com/owncloud/core/issues/7747 and https://doc.owncloud.org/server/8.0/admin_manual/enterprise_files_drop/index.html

**Comment by petrasteri** [comment]
Oh, 8.0 ... I'm still at 7.0.5 [because, on a digression, I haven't found the procedure to correctly migrate version 7 to version 8. Of course, I could just move the files to another server but in this way, I'll lost the file history/version and I'll lost my settings]

But commenters in the other issue #7747 said that other users can see the content of the folder.  That's not really a drop box -- a mail drop box is when you drop a letter inside it, others can't see what it is or get to it.  That's the idea.

And your second link points to Enterprise Subscription.  So I suppose this request would never see the light in community server?

**Comment by Xenopathic** [comment]
The Enterprise Files Drop app implements this, so for now it won't be coming to the community edition, sorry :disappointed:
