### ISSUE TITLE
LDAP Errors with FreeIPA

### ISSUE THREAD

**Issue by Mebus** [owncloud/core#17087]
Hallo, 

I get these errors when trying to configure OC with FreeIPA:

<code>
{"reqId":"b7ab5b853f17c2f5d46dbd15887eff26","remoteAddr":"10.10.10.2","app":"user_ldap","message":"Requested attribute auto not found for uid=testuser,cn=users,cn=accounts,dc=hbs,dc=lala,dc=de","level":0,"time":"2015-06-22T22:35:57+00:00","method":"POST","url":"\/owncloud\/"}
{"reqId":"b7ab5b853f17c2f5d46dbd15887eff26","remoteAddr":"10.10.10.2","app":"user_ldap","message":"Cannot determine UUID for uid=testuser,cn=users,cn=accounts,dc=hbs,dc=lala.de,dc=de. Skipping.","level":1,"time":"2015-06-22T22:35:57+00:00","method":"POST","url":"\/owncloud\/"}
</code>

Especially this error: "Cannot determine UUID". How can this be fixed? 

I used the tutorial here:

http://www.freeipa.org/page/Owncloud_Authentication_against_FreeIPA

but it's not working.

Mebus

**Comment by DeepDiver1975** [comment]
@blizzz anything we can do to support this user? THX

**Comment by blizzz** [comment]
@Xenopathic did not you do a bit with FreeIPA? It seems we don't find an UUID on his setup, which sounds rather odd. Any clue?

**Comment by Xenopathic** [comment]
@blizzz No, unfortunately I never did anything with FreeIPA, only Samba4 and OpenLDAP.

**Comment by blizzz** [comment]
@Xenopathic okay … i thought, because you opened https://github.com/owncloud/core/pull/7823

**Comment by blizzz** [comment]
@Mebus well, you can try to set ipauniqueid manually in the expert tab for the UUID attributes.

**Comment by Mebus** [comment]
Hi,

ok, what should I fill in there?

Additional information: I am using FreeIPA Version: 4.1.4 and OC Version 8.0.4.

Mebus

**Comment by Mebus** [comment]
Ha! I set the UUID-Attribute for users to "ipauniqueid" and now it works! Great!

**Comment by blizzz** [comment]
good. but it should do it by default as well.

Did you upgrade? If so, from which version to which?

**Comment by Mebus** [comment]
I think I upgraded from owncloud 8.0.1 or something.

My group filter now ist "(|(cn=owncloud))" but also users who are not in that group may login into owncloud. What's the correct way to fix this?

Mebus

**Comment by blizzz** [comment]
Was "auto" entered there before on the Expert tab before you changed it?

> My group filter now ist "(|(cn=owncloud))" but also users who are not in that group may login into owncloud. What's the correct way to fix this?

Adjust User and Login filter. Please read
https://doc.owncloud.org/server/8.0/admin_manual/configuration_user/user_auth_ldap.html

**Comment by Mebus** [comment]
Which "auto" in export mode do you mean? I think the update was done by CentOS, because the owncloud installation comes from CentOS.

I set the user filter to:

(&(objectClass=*)(memberOf=cn=owncloud,cn=groups,cn=accounts,dc=hbs,dc=lala,dc=de))

I set the Login Fitter to:

(&(memberOf=cn=owncloud,cn=groups,cn=accounts,dc=hbs,dc=lala,dc=de)(&(objectclass=*)(uid=%uid)))

It seems to work now. I hope this is correct.

Mebus

**Comment by blizzz** [comment]
OK, I'm glad you're up and running.
