### ISSUE TITLE
Make CLI upgrade the default to avoid timeouts, web UI upgrade only for shared hosters

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#17091]
#### Disambiguation:
- "updater app": this app https://github.com/owncloud/updater. The app that appear in the admin page and automatically downloads the new tarball and installs it.
- "update page": whenever an upgrade is due, the updater page appears with a "Start upgrade" button:
  ![update_page](https://cloud.githubusercontent.com/assets/277525/8302123/55880fec-1994-11e5-8ba3-3da3f97b279a.png)
#### The problem:
- When upgrading from the update page (web UI) with a lot of data, it is likely that PHP will run into timeouts and could result in half-migrated instances (ex: encryption keys). So far, it was advised on that page to run a CLI upgrade instead.
- It is tempting for an admin who sees this page to simply click "Start upgrade" and hope it all works fine.
#### Goal:
- goal is to make CLI upgrade the default to reduce accidental timeout issues and only have web UI update page if really necessary (ex: shared hosters where no CLI is available)
#### Proposal:
- separate the CLI upgrade from the web UI upgrade
- make CLI upgrade the default, display a simple page "Upgrade required, please update on the CLI" instead of the regular _update page_ when an update is due
- only if the _updater app_ is enabled, then show the usual _update page_, the one with "Start upgrade" button
- this means that the web UI _update page_ becomes part of the _updater app_
- disable the "updater app" by default and have people using shared hosters enable it manually (auto-detect if possible, maybe when installed from the magic owncloud-install.php script)

**Comment by karlitschek** [comment]
We need to offer both options. A ver prominent hint how it is done via the cli and optionally and only for smaller instances the option via the web interface.
Another important point it that long running upgrade steps have to move into background jobs. This is important for cli AND web upgrades.
We should also look into other solutions like Wordpress why they are able to provide a we b updater for years without problems.

**Comment by Xenopathic** [comment]
Ref #14239

**Comment by oparoz** [comment]
> We should also look into other solutions like Wordpress why they are able to provide a we b updater for years without problems.

AFAIK, a standard Wordpress config doesn't encrypt tens of GBs


@Pvince, in your proposal, the web updater should be the preferred option when updating apps, but for that to happen, it first needs to learn about the difference between a core and an app update (https://github.com/owncloud/core/issues/16272)

**Comment by PVince81** [comment]
No. In my proposal the CLI update should be the preferred option.

The update page (see disambiguation above) should only be there for people who have no CLI access (ex: shared hosters) and that could be achieved by having that page being a part of the updater app (see disambiguation above).

The update process (the one from the update page) can know about core and app update, it just doesn't show the correct message.

**Comment by Xenopathic** [comment]
Actually, @PVince81's proposal will help massively in reducing the ambiguity surrounding an 'update' or an 'upgrade', if we move the web upgrader to the Updater app. As long as the Updater app is installed by default on all releases (I think it is?) then it's :+1: from me.

**Comment by oparoz** [comment]
I disagree with a cli only approach for app updates, unless you disable the app store as well.

1. User enables app in the Web GUI
2. Operation triggers an update
3. **User is forced to SSH to his account to perform the upgrade before being able to use oC again**

That's just nonsense for a UX point of view.

**Comment by DeepDiver1975** [comment]
> That's just nonsense for a UX point of view.

this is indeed true - so we have to differentiate between core and app updates?

**Comment by oparoz** [comment]
I think we should. It's much safer to upgrade oC from the cli and since there are plans to log everything when performing an upgrade, an admin will have quick access to the logs and will be able to fix things quickly.

For apps, a web upgrade is perfectly fine, except if the encryption app wants to make massive changes all the sudden, but that has always been introduced with oC upgrades.

**Comment by DeepDiver1975** [comment]
we should have a detailed discussion about this - maybe there is something to do within the cycle of 8.2

**Comment by karlitschek** [comment]
It's the design goal of ownCloud to provide a solution that can be hosted on a private webspace. We should be able to deliver that. 
Like I said. Let's check how other do it. For example Wordpress updates itself completely automatic even without an upgrade button. Background jobs can help to reduce the execution time for an upgrade significantly.

**Comment by sergiocallegari** [comment]
The problem is more serious that that indicated at the beginning of this thread.

The problem is that *everybody* on the internet is given the opportunity to start the upgrade with the button.

This means that when the administrator upgrades owncloud, he cannot know for sure when the updated will be triggered. This is a bad and potentially dangerous situation.

**Comment by jancborchardt** [comment]
@karlitschek @DeepDiver1975 @PVince81 I assume this is something for 9.0? Do we have another issue with a lowdown of what we discussed at the conf about the updater process?

**Comment by Xenopathic** [comment]
@jancborchardt An implementation is available over at #18782 btw

**Comment by DeepDiver1975** [comment]
upgrade is one big topic for 9.0 - setting milestone accordingly

**Comment by PVince81** [comment]
Not sure if we want to do this right now, could do later, or drop the topic.

Thoughts ? @DeepDiver1975 @butonic @pmaier1 @felixboehm

**Comment by PVince81** [comment]
probably just a matter of 1md to add an option.
Maybe "setup-install.php" could be made to change that option to allow web UI update.

**Comment by pmaier1** [comment]
Well, this does not block anything since you can always use OCC to upgrade. If app upgrades can still be done via web (https://github.com/owncloud/core/issues/17091#issuecomment-114838302) this makes the behavior better and guides admins so it should definitely not be abandoned. Moreover I'd regard it as bad practice that anyone can trigger the update via the WebUI. Should be changed!
Priority: If there's time left, we do it, else postpone.

**Comment by PVince81** [comment]
Moving to backlog for now, unless someone is willing to contribute a PR for this
