### ISSUE TITLE
  Why using utf8_bin table encoding everywhere?

### ISSUE THREAD

**Issue by Loki3000** [owncloud/core#17099]
It's case sensitive. So search becomes case sensitive too. Is it really necessary in "contacts" for example?
Maybe it's to be better to use something like utf8_general_ci or make search case insensitive?

**Comment by DeepDiver1975** [comment]
Especially on file names we want case sensitivity - for case insensitive queries we have methods in place. Most probably contacts did not yet take advantage of it.

**Comment by Raydiation** [comment]
Search in News is also case insensitive btw.
