### ISSUE TITLE
[locking] login denied because file system is locked

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#17097]
```json



{
  "reqId": "TqpKAi1sKahezdx89LJT",
  "remoteAddr": "178.25.225.40",
  "app": "handleLogin",
  "message": "Exception: {\"Exception\":\"OCP\\\\Lock\\\\LockedException\",\"Message\":\"\\\"\\\" is locked\",\"Code\":0,\"Trace\":\"
#0 \\\/srv\\\/www\\\/owncloud8.1-locking\\\/lib\\\/private\\\/files\\\/view.php(1000): OC\\\\Files\\\\View->changeLock('\\\/test\\\/files', 2)\\n
#1 \\\/srv\\\/www\\\/owncloud8.1-locking\\\/lib\\\/private\\\/files\\\/view.php(243): OC\\\\Files\\\\View->basicOperation('mkdir', '\\\/test\\\/files', Array)\\n
#2 \\\/srv\\\/www\\\/owncloud8.1-locking\\\/lib\\\/private\\\/files\\\/node\\\/folder.php(205): OC\\\\Files\\\\View->mkdir('\\\/test\\\/files')\\n
#3 \\\/srv\\\/www\\\/owncloud8.1-locking\\\/lib\\\/private\\\/server.php(548): OC\\\\Files\\\\Node\\\\Folder->newFolder('\\\/files')\\n
#4 \\\/srv\\\/www\\\/owncloud8.1-locking\\\/lib\\\/private\\\/user.php(247): OC\\\\Server->getUserFolder('test')\\n
#5 \\\/srv\\\/www\\\/owncloud8.1-locking\\\/lib\\\/base.php(1067): OC_User::login('test', 'test')\\n
#6 \\\/srv\\\/www\\\/owncloud8.1-locking\\\/lib\\\/base.php(963): OC::tryFormLogin()\\n
#7 \\\/srv\\\/www\\\/owncloud8.1-locking\\\/lib\\\/base.php(925): OC::handleLogin()\\n
#8 \\\/srv\\\/www\\\/owncloud8.1-locking\\\/index.php(40): OC::handleRequest()\\n
#9 {main}\",\"File\":\"\\\/srv\\\/www\\\/owncloud8.1-locking\\\/lib\\\/private\\\/files\\\/view.php\",\"Line\":1763}",
  "level": 4,
  "time": "2015-06-23T09:44:31+00:00"
}

**Comment by DeepDiver1975** [comment]
@PVince81

**Comment by PVince81** [comment]
Issue template ? :wink:

**Comment by DeepDiver1975** [comment]
With another user on the same system login is successful - but fails a bit later:


````
{"reqId":"5uJDsCntfNZOiya5X9Mg","remoteAddr":"178.25.225.40","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/owncloud8.1-locking\\\/apps\\\/files\\\/index.php(85): OC_Helper::getStorageInfo('\\\/', false)\\n#1 \\\/srv\\\/www\\\/owncloud8.1-locking\\\/lib\\\/private\\\/route\\\/route.php(153) : runtime-created function(1): require_once('\\\/srv\\\/www\\\/ownclo...')\\n#2 [internal function]: __lambda_func(Array)\\n#3 \\\/srv\\\/www\\\/owncloud8.1-locking\\\/lib\\\/private\\\/route\\\/router.php(274): call_user_func('\\\\x00lambda_147', Array)\\n#4 \\\/srv\\\/www\\\/owncloud8.1-locking\\\/lib\\\/base.php(867): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#5 \\\/srv\\\/www\\\/owncloud8.1-locking\\\/index.php(40): OC::handleRequest()\\n#6 {main}\",\"File\":\"\\\/srv\\\/www\\\/owncloud8.1-locking\\\/lib\\\/private\\\/helper.php\",\"Line\":971}","level":4,"time":"2015-06-23T09:49:51+00:00"}

**Comment by DeepDiver1975** [comment]
This is from our failing smashbox test on jenkins

**Comment by PVince81** [comment]
Can you switch to maintenance mode then do "keys *" on redis ?
If it shows entries it means there are stray keys.

**Comment by DeepDiver1975** [comment]
> Can you switch to maintenance mode then do "keys *" on redis ?

no redis on that server - using apcu for locking

**Comment by nickvergessen** [comment]
Just to make sure, this is with locking + encryption

I can't reproduce it locally nor in my VM

**Comment by DeepDiver1975** [comment]
> Just to make sure, this is with locking + encryption

indeed - lock'n'crypt

**Comment by DeepDiver1975** [comment]
Do we need these user account for further debugging?

Otherwise I'll recreate the accounts to get our smashbox testing up and running again

**Comment by nickvergessen** [comment]
Smashbox should create all necessary accounts, so feel free to delete `test*`

**Comment by DeepDiver1975** [comment]
> Smashbox should create all necessary accounts,

yes - it does - question is if we need this environment for debugging.

**Comment by DeepDiver1975** [comment]
wait - aren't the accounts anyhow recreated by smashbox for every run?

So - locks continue to persist after deletion of accounts?

**Comment by nickvergessen** [comment]
> wait - aren't the accounts anyhow recreated by smashbox for every run?

They should be, we delete and then create the users (at least if the config is set correctly https://github.com/owncloud/smashbox/blob/master/etc/smashbox.conf.template#L98-L106 )

> So - locks continue to persist after deletion of accounts?

Well locks should be removed at the end of the php request, so that shouldn't matter

**Comment by DeepDiver1975** [comment]
So there is something really fishy!

**Comment by DeepDiver1975** [comment]
locks stay even if user is deleted - I'm thinking about if we should have a simple page to list all active locks and maybe the capability for the admin to release?

Or finally add TTL?

**Comment by DeepDiver1975** [comment]
@icewind1991 @PVince81 @nickvergessen

**Comment by nickvergessen** [comment]
TTL might be odd, because for a GB large file a log might take hours, but then again in case of an error the log is not released although the request died hours ago?

I don't know how the problem happened on jenkins, but for me that never happened.

**Comment by PVince81** [comment]
TTL ticket here #16966

**Comment by DeepDiver1975** [comment]
Error no longer occurs - I'm unable to reproduce this in the past days ..... let's close this for now
