### ISSUE TITLE
Update from 8.0.2 to 8.0.4

### ISSUE THREAD

**Issue by boschma1** [owncloud/core#17108]
Hi 

After copying all replacing all files (but config.php) into the OC directory, setting "maintenance" to "true", resetting all access rights on files to httpdusr:administrators for the new files and pressing UPDATE on the web interface, I receive the following error message:

An exception occurred while executing ' DELETE FROM `oc_lucene_status` WHERE `fileid` IN ( SELECT `fileid` FROM ( SELECT `fileid` FROM `oc_lucene_status` GROUP BY `fileid` HAVING count(`fileid`) > 1 ) AS `mysqlerr1093hack` )': SQLSTATE[HY000]: General error: 1598 Binary logging not possible. Message: Transaction level 'READ-COMMITTED' in InnoDB is not safe for binlog mode 'STATEMENT'

Please advise.

Cheers
Markus

**Comment by LukasReschke** [comment]
Duplicate of https://github.com/owncloud/core/issues/16008, you can find a solution at https://github.com/owncloud/core/issues/16008#issuecomment-98889298

**Comment by RealRancor** [comment]
Also documented here: https://doc.owncloud.org/server/8.0/admin_manual/maintenance/upgrade.html#troubleshooting
