### ISSUE TITLE
AppStore does not return applications for 8.1

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#17101]
Request sent:

```
GET /v1/content/data?version=8x1x0x7&filter=all&categories=920&sortmode=new&page=0&pagesize=100&approved=all HTTP/1.1
Host: api.owncloud.com
User-Agent: ownCloud Server Crawler
```

Response:
```
HTTP/1.0 200 OK
Date: Tue, 23 Jun 2015 11:33:05 GMT
Server: Apache/2.4.7 (Ubuntu)
X-Powered-By: PHP/5.5.9-1ubuntu4.9
X-Frame-Options: SAMEORIGIN
Set-Cookie: PHPSESSID=h6o149gj2m2bo7kcie3hkskh72; path=/; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Vary: Accept-Encoding
Content-Length: 200
Connection: close
Content-Type: application/xml

<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message></message>
  <totalitems>0</totalitems>
  <itemsperpage>100</itemsperpage>
 </meta>
 <data/>
</ocs>
```

Why does it not return applications such as [News](https://apps.owncloud.com/content/show.php/News?content=168040) which is set to 8.1 and also approved?

@karlitschek Any idea?

**Comment by LukasReschke** [comment]
App settings:

![2015-06-23_13-37-15](https://cloud.githubusercontent.com/assets/878997/8305193/fbd593e8-19ac-11e5-8c28-7da5be0c9a32.png)

**Comment by oparoz** [comment]
But it returns upgrades designed for 8.1 to users on oC 8.0... https://github.com/owncloud/core/issues/16600

**Comment by karlitschek** [comment]
So the appstore and the api supports several different downloads per app now. yay. But there is still an open question.
At the moment the current owncloud version is not send to the detail GET call. So we can't return the version that fits best automatically. Option 1 is to fix that.
The other option is what is currently implemented. ownCloud gets all the available download options back and has to figure out on it's one which one is the best.
I suggest the following logic. 
Download link 1 is always the default and fallback. But it should check if one of the other links is for precisely the current ownCloud server version and in that case should be used.
@LukasReschke What do you think? 
We should chat tomorrow :-)

**Comment by DeepDiver1975** [comment]
> At the moment the current owncloud version is not send to the detail GET call. So we can't return the version that fits best automatically. Option 1 is to fix that.

The ownCloud instance is sending the version in the call to query all apps: https://github.com/owncloud/core/blob/master/lib/private/ocsclient.php#L172

Do we need more? THX

**Comment by nickvergessen** [comment]
I guess we need to add the version here as well:
https://github.com/owncloud/core/blob/master/lib/private/ocsclient.php#L244-L247

**Comment by LukasReschke** [comment]
We need it in all functions. `getApplicationDownload` is called to get the download URI,  thus I'd just add it to all requests to the appstore so we never have to worry again about such things.

**Comment by DeepDiver1975** [comment]
Ah - yes - and maybe here as well - https://github.com/owncloud/core/blob/master/lib/private/ocsclient.php#L303 - this is where we ask for the download link

**Comment by nickvergessen** [comment]
I will make a patch for those then

**Comment by DeepDiver1975** [comment]
> Option 1 is to fix that.

yes - we shall be explicit on what we want and add the version to the request.

What will the behavior looks like for oc8 and earlier versions?

I guess we shall add the version there as well.
Topic for the current maintenance releases from my POV.

@karlitschek @cmonteroluque objections?

**Comment by nickvergessen** [comment]
Patch is here: https://github.com/owncloud/core/pull/17222 should be easy enough to backport

**Comment by karlitschek** [comment]
Thinking about this a bit more...
This breaks with older releases independently if we choose option 1 or 2.
The app store can always fall back to delivering the first link if no version is sent from the owncloud server. But this can break in a lot of ways depending in which order the developers adds the links.

We really shoudn't do a change like that directly before a release. :-(
@LukasReschke, @DeepDiver1975 time for a quick call to discuss this?

**Comment by nickvergessen** [comment]
> We really shoudn't do a change like that directly before a release. :-(

Well if we don't there will be tones of new issues with failing updates after the release and people will be annoyed yet again. :cry: 
Having it optional is nothing that breaks something. It was already broken and people can help to fix it. I'd say it's worth a try.

**Comment by DeepDiver1975** [comment]
> We really shoudn't do a change like that directly before a release. :-(

Hmmm ... we need multiple downloads - right? So better now then never.

> @LukasReschke, @DeepDiver1975 time for a quick call to discuss this?

Sure - anytime within the next 4 hours

**Comment by LukasReschke** [comment]
> Sure - anytime within the next 4 hours

Same here.

**Comment by oparoz** [comment]
Testing using the API URL mentioned in the OP, I still get 0 releases for 8.1 and the same 4 as before on 8.0.
Is this bug really addressed or does #17222 only takes care of serving the proper app version?

**Comment by nickvergessen** [comment]
17222 only sends the version to the app store, now the app developers need to add the packages for each version, then they will be served (from my understanding)

**Comment by LukasReschke** [comment]
Technically we still require on-going changes on the server but hopefully stuff should then all work :speak_no_evil:

**Comment by oparoz** [comment]
OK.

Re-reading comments, it seems the appstore was only fixed for the use case where a request is made for a specific app, so I'll be waiting for the list retrieval fix :)

**Comment by DeepDiver1975** [comment]
I'm reopening this - we don't yet get any apps displayed in 8.1

**Comment by karlitschek** [comment]
Fixed now. Yay.
The bad news is that a bunch of apps now show up that are most likely not compatible with 8.1
This is not a problem in the logic but the apps don't have proper min and max requirements set on apps.owncloud.com
Can someone go trough it and fix the settings on apps.owncloud.com? And ping me if someone needs full admin rights to help with that.

**Comment by LukasReschke** [comment]
> Can someone go trough it and fix the settings on apps.owncloud.com? And ping me if someone needs full admin rights to help with that.

:speak_no_evil: - on it.

**Comment by oparoz** [comment]
Well done :)

**Comment by DeepDiver1975** [comment]
@karlitschek 

![youre-awesome](https://cloud.githubusercontent.com/assets/1005065/8443513/ad4ec34e-1f87-11e5-8545-a9a267a8ec94.jpg)

**Comment by karlitschek** [comment]
Holy shit. This Appstore thing seems to work really well in 8.1 Finally as it should be.
Thanks a lot to everyone  @DeepDiver1975 @LukasReschke @jancborchardt @jancborchardt :-)

**Comment by LukasReschke** [comment]
Shall I be the party crasher? ;-) – There is a bug in ownCloud that somehow leads to crazy behaviour when loading the "Multimedia" category… Debugging this atm but besides this it seems actually to work :tada:

**Comment by LukasReschke** [comment]
Ok. Great fun. – PR coming. – Great to use a programming language that can't handle UTF8 … :angry:

**Comment by LukasReschke** [comment]
PR at https://github.com/owncloud/core/pull/17264

**Comment by LukasReschke** [comment]
> Can someone go trough it and fix the settings on apps.owncloud.com? And ping me if someone needs full admin rights to help with that.

Done. Most apps have disappeared now for ownCloud 8.1 because they are either completely unsupported and do not run anymore since ages or – also a likely case – the person did not upload the tar ball correctly and thus ownCloud fails to extract the application. Seems like we need a tutorial on "how to upload applications", I can take care of that.

Approved apps should all work. The official ones may need to get updates pushed using the new feature where one can specify different versions. The experimental ones mostly do work but I didn't test them throughly.

Ah, and the "Games" category is completely empty. :speak_no_evil: 

@oparoz Happier now with Gallery+? ;-)

![2015-07-01_02-10-57](https://cloud.githubusercontent.com/assets/878997/8444858/73551a26-1f96-11e5-9b8f-815fcfd48b11.png)

**Comment by oparoz** [comment]
Thank you very much for your work @LukasReschke, it's much appreciated. I'm looking forward to testing the new versioning functionality :)

**Comment by LukasReschke** [comment]
> I'm looking forward to testing the new versioning functionality :)

Me too. But it unfortunately requires some incompatible server backend changes so we can first launch them once we have the next stable releases out. 

So won't work yet :smile:

**Comment by oparoz** [comment]
Ah, so we still need to open one app per version until 8.2 lands?

**Comment by oparoz** [comment]
It's going to be confusing for devs which upload all versions in one app, only to realise later on that it doesn't work.

**Comment by LukasReschke** [comment]
> Ah, so we still need to open one app per version until 8.2 lands?

Nope. Until 8.1, 8.0.5, 7.0.7, etc. do land (and if @karlitschek got enough time to do the needed changes)

**Comment by oparoz** [comment]
cool :)

**Comment by karlitschek** [comment]
By the way. We should have this by tomorrow and definitely before the 8.1 launch

**Comment by oparoz** [comment]
:tada: :balloon:
