### ISSUE TITLE
Notification design: distinguish types via color & icon, not only yellow

### ISSUE THREAD

**Issue by stefan-niedermann** [owncloud/core#17109]
**Current Situation**
Every Message has the same style (Black Color on Yellow Background-Color). It's very hard to distinguish between different message types. Example: If i write an e-Mail with the Mail App i get the same Message Style when the e-Mail was sent without errors or if the e-Mail could not be sent.

**Suggestion**
There should be a difference between the Message Types
- "Success" (Green)
- "Info" (Blue)
- "Warning" (Yellow)
- "Error" (Red)

See for example the Atlassian Design Guidelines:

![aui-messages](https://cloud.githubusercontent.com/assets/4741199/8308600/063774f0-19c6-11e5-81a0-fd7c16dad0e8.png)

cc @owncloud/designers 
cc @jancborchardt

**Comment by stefan-niedermann** [comment]
Maybe related to https://github.com/owncloud/activity/issues/10 since this issue would also help to get a better overview about the notifications.

**Comment by jancborchardt** [comment]
Really damn good call! There’s probably 4 use cases / colors:

* Success (green): for successfully sending an email (can’t think of anything else right now)
* Feedback & action (yellow): for operations which offer undo or other actions
* Error (red): mail account not connected successfully for example, and you’re redirected to the previous screen
* Info (blue): new version information, etc

**Comment by jancborchardt** [comment]
@stefan-niedermann are you in the #owncloud-design IRC channel by the way? And in the @owncloud/designers team? ;)

**Comment by stefan-niedermann** [comment]
@jancborchardt i'm in the designers-team, otherwise i wouldn't be able to mention the group ;) but i do not often use irc...

**Comment by oparoz** [comment]
Great, should be as simple as defining a few CSS classes and adding an argument to the methods of  [OC.Notification](
https://github.com/owncloud/core/blob/3b0b1a7ceb34596fb0f0ea89786b425b49fcd2f8/core/js/js.js#L727)

**Comment by PVince81** [comment]
Moving to backlog for now. If anyone is up for the task, feel free to submit a PR.

From what I see we already have a second argument `options` to `showHtml` and since OC 9 or so notifications can already stack. So it's just a matter of adding an extra `cssClass` arg or so and define CSS styles for the colors.

But then also every app that pushes this kind of notifications also need to be changed to set that arg.

CC @felixheidecke

**Comment by stefan-niedermann** [comment]
> But then also every app that pushes this kind of notifications also need to be changed to set that arg.

I am sure this can be handled using a default argument in the function to keep it backwardscompatible :)

**Comment by PVince81** [comment]
Yes, of course. But I was mostly referring to using the actual color classes depending on the type of notification. Basically: find all warning notifications in the code and set them to `cssClass: "warning"` or so.
