### ISSUE TITLE
AppStore: How to handle 8.1 update for shipped apps?

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#17103]
With 8.1 the calendar and contacts app needs to get bumped or users will run in a fatal error (if they enable the apps again after the update) as we updated SabreDAV which was used directly in app.php by these apps.

This means that the 8.1 calendar and contacts app is a different one than the one in 8.0 - how can we handle this with the appstore?

@karlitschek Any idea?

**Comment by LukasReschke** [comment]
Also we should enforce the `max-version` tag on all shipped apps in info.xml, for example:

```xml
    <!-- dependencies -->
    <requiremin>8.1</requiremin>
    <dependencies>
        <owncloud min-version="8.1" max-version="8.1"/>
    </dependencies>
```

This would prevent such problems. I'd suggest that we already ship updates out there for the old apps in the appstore so that users can't enable them again…

**Comment by LukasReschke** [comment]
cc @PVince81 You also brought this up.

**Comment by LukasReschke** [comment]
Calendar:
- https://github.com/owncloud/calendar/pull/818
- https://github.com/owncloud/calendar/pull/819

Contacts:
- https://github.com/owncloud/contacts/pull/930
- Master already has this change.

@karlitschek Is it possible to ship these updates already so that at least we're not going to get bombarded with frustrated users?

**Comment by oparoz** [comment]
That's exactly how Gallery is doing it since the app store doesn't support versioning.

It's a PITA regarding ratings because you start from scratch for each new oC release and it's what's being used to decide whether an app should be approved or not.

**Comment by DeepDiver1975** [comment]
setting sev1 - we shall not release yet another major version where calendar and conatcts are broken

**Comment by karlitschek** [comment]
Lets discuss over there
https://github.com/owncloud/core/issues/17101#issuecomment-114648376
