### ISSUE TITLE
User in group counts disappear when LDAP is configured

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#17118]
### Steps to reproduce

1. Install 8.1 
2. Create users and groups
3. Validate see user in group count
4. Configure ldap 
5. Go to users page
6. See ldap users and groups but no longer see user in group counts

### Expected behaviour

Always see user in group counts.

### Actual behaviour

Do not see user in group counts when LDAP is configured

![p361](https://cloud.githubusercontent.com/assets/8480343/8312485/ce204652-19aa-11e5-9b28-133290a7d915.PNG)

![p360](https://cloud.githubusercontent.com/assets/8480343/8312486/d04c1fb4-19aa-11e5-9b41-8ff77b1dc1cd.PNG)

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration:

ownCloud Enterprise Edition 8.1 RC1 (daily) Build:2015-06-23T03:09:53+00:00 25581c7b638a5349c0180b6210b2e1d332e19e49

**Comment by jnfrmarks** [comment]
root@ubuntu-14-lts:/var/www/html/owncloud# sudo -su www-data php occ app:list
Enabled:
 - activity: 2.0.0
 - admin_audit: 0.6
 - enterprise_key: 0.1.0
 - files: 1.1.9
 - files_external: 0.2.3
 - files_locking:
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.4
 - user_ldap: 0.6.0
 - windows_network_drive: 0.1.1
Disabled:
 - encryption
 - external
 - files_antivirus
 - files_drop
 - files_ldap_home
 - firewall
 - firstrunwizard
 - objectstore
 - sharepoint
 - user_external
 - user_shibboleth
 - user_webdavauth

**Comment by DeepDiver1975** [comment]
User counts on LDAP groups are currently not shown by intention. Calculating the user count is a performance nightmare with LDAP. I vote for moving this to the backlog
