### ISSUE TITLE
large file upload (10GB) via sync client 1.8.2 finishes concatenation only after the 2nd sync process

### ISSUE THREAD

**Issue by CaptionF** [owncloud/core#17117]
### Steps to reproduce
1. put a 10 GB file into a synced folder on a windows 7 laptop / PC
2. sync client starts to upload in chunks
3. Server creates an error  "Der Server hat den letzten Block nicht bestätigt. (Der E-Tag war nicht vorhanden)“,  even on an English system and sync client starts uploading again

Start insertion:               10:12:15
End insetion, start upload:  10:15:10
End Upload, Start Concat:    10:32:15
error E-Tag:                 10:37:28

on the second upload /sync process, the error does not happen.
Session life time is set to 1 hour.
 

### Expected behaviour
Tell us what should happen
the file should be uploaded and concatenation of the many small files should create 1 single large file, that is then moved to the correct location

### Actual behaviour
Tell us what happens instead
When the large file has been transmitted to the server in many small chunks, 
and server starts to concatenate the many files, then the server  creates an error.

### Server configuration
**Operating system**:
SLES 12

**Web server:**
apache 2.4
**Database:**
Oracle RAC
**PHP version:**
5.5.14
**ownCloud version:** (see ownCloud admin page)
oc 8.0.3
**Updated from an older ownCloud or fresh install:**
oc 7.0.5
**List of activated apps:**

**The content of config/config.php:**
Please see S3 due to enterprise prospect

**Are you using external storage, if yes which one:** local/smb/sftp/...
NETApp through NFS
**Are you using encryption:** yes/no
NO
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**
Firefox 38.0.5
**Operating system:**
Win 7 64 bit
### Logs
See S3 # 17117

**Comment by CaptionF** [comment]
@bboule I do need get back to the prospect with a statement, when this will be fixed. Not top critical, but preferable 8.2 latest.

**Comment by bboule** [comment]
@cmonteroluque would it be possible to have someone take a look?

**Comment by DeepDiver1975** [comment]
This is a known issue.  We plan to dive into deeper discussion in the scope of 8.2


@dragotin @karlitschek this is the time out on assembly of chunked upload.

**Comment by bboule** [comment]
@CaptionF i think this is what you need?

**Comment by CaptionF** [comment]
@bboule yes, that's what I needed. Thanks.

**Comment by CaptionF** [comment]
@DeepDiver1975 This seems to be slipped through the current 8.2 bugs! Please ensure it will be in 8.2;

**Comment by CaptionF** [comment]
@cmonteroluque this one needs to be in 8.2 too. the labels don't indicate this yet.

**Comment by DeepDiver1975** [comment]
This is not possible with a deeper architectural change - see https://dragotin.wordpress.com/2015/06/22/owncloud-chunking-ng/

We had the hope to get this into 8.2 - but this was not possible

@cmonteroluque 9.0 I assume

**Comment by cmonteroluque** [comment]
@DeepDiver1975 @CaptionF I talked to @bboule about this. Engineering's position is that this should be in 9.0, waiting for confirmation from GCX

**Comment by dragotin** [comment]
I investigated the logs a bit. It seems that the locking app is enabled during the upload of the big file. Is it supposed to be production ready? I see a lot of log lines like 
```
{"reqId":"xxx","remoteAddr":"www.xxx.yyy.zzz","app":"lock","message":"INFO: Incrementing lock type 2 count for \/data\/Z208263@XYZ.com\/cache\/9_file_10g-chunking-1439864212-132","level":0,"time":"2015-06-22T10:42:02+02:00","method":"PUT","url":"\/remote.php\/webdav\/large\/9_file_10g-chunking-1439864212-2048-132"}
```
Apart from that, it really looks like if the client uploaded all the chunks. The last chunk took 5:14 minutes to return to the client but **not** with a timeout error message, but also not with an etag, which would the server normally sends.

Things to investigate:
- The "lock-app" has  a bug that prevents the server from sending the ETag back with the last chunk.
- There was a timeout on the way that does not show up as a timeout, maybe in a load balancer or so?

@CaptionF please ask the users to try with a recent client version (the log was done with 1.8.2) and also check if that also fails if the lock app is disabled. Thanks.

**Comment by DeepDiver1975** [comment]
> I investigated the logs a bit. It seems that the locking app is enabled during the upload of the big file. Is it supposed to be production ready? I see a lot of log lines like

this log messages signals no issue

**Comment by CaptionF** [comment]
@dragotin New log file provided by the prospect! Could you please validate Thanks

**Comment by CaptionF** [comment]
prospect confirms: large file gets synced correctly!
Case closing
@DeepDiver1975 @dragotin @bboule @cmonteroluque  Thanks!

**Comment by cmonteroluque** [comment]
@CaptionF great, thanks!

**Comment by DeepDiver1975** [comment]
> prospect confirms: large file gets synced correctly!

@CaptionF nice! May I ask for the reasoning why it did fail in the past and now it works?

**Comment by CaptionF** [comment]
@DeepDiver1975: the client log from 20150622 states after uploading that the E-Tag was not set correctly. Line 9312. At that time, the prospect performed this multiple times. always the same error & sync client started the upload again (2x 10 GB) line 9740 in log file.
Take a look at the log file in S3.
I don't know the changes between oC 805 and oC 813 server. When the customer performs the same procedure again, and it works, and you guys check the log files and there is no problem any more - I think the case is solved. Customer/prospect is happy! So am I :-)
