### ISSUE TITLE
Can't sync CalDAV on Mac OS X 10.9.5 Calendar

### ISSUE THREAD

**Issue by kr15h** [owncloud/core#17113]
After updating it is not possible to sync the calendars - password is not recognised anymore. Calendar.app version 7.0. Mac OS X 10.9.5.

**Comment by RealRancor** [comment]
Hi,

the issue of the calendar app is located here:

https://github.com/owncloud/calendar/issues

It could be useful to also provide additional infos about your problem and your environment as asked in the issue template: 

https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version

which is linked in the yellow box when creating a new issue.
