### ISSUE TITLE
missing documentation: LDAP user quota sync updated after unknown time

### ISSUE THREAD

**Issue by igormitelman** [owncloud/core#17129]
OC 8.0.4
Ubuntu 14
MariaDB
MS AD

All working fine, except LDAP user quota sync not update immediately,   unfortunately i not found information about times of update user quota from LDAP.

Where can i see this info?
How we can control this times?

Thanks.

**Comment by RealRancor** [comment]
Hi,

i think this is something for the documentation tracker:

https://github.com/owncloud/documentation/issues

**Comment by RealRancor** [comment]
Ref: https://github.com/owncloud/documentation/issues/1250

As this issue already contains some additional infos you might want to close here.
