### ISSUE TITLE
Security issue - ownCloud-8.0.3 download doesn't match md5sum

### ISSUE THREAD

**Issue by agriffaut** [owncloud/core#17121]
Main download files for owncloud server v8.0.3
https://download.owncloud.org/community/owncloud-8.0.3.tar.bz2 and https://download.owncloud.org/community/owncloud-8.0.3.zip doesn't match md5sum
respectively https://download.owncloud.org/community/owncloud-8.0.3.tar.bz2.md5 and https://download.owncloud.org/community/owncloud-8.0.3.zip.md5

**Comment by LukasReschke** [comment]
@karlitschek THX

**Comment by oparoz** [comment]
@agriffaut - It won't work if you check the 8.0.3 archives with the 8.0.4 md5, unless the web server was serving the 8.0.3 archives instead of the 8.0.4 ones and that has now been fixed.

**Comment by RealRancor** [comment]
@oparoz 
I think this is just a typo. Just tested and confirmed this:

```
wget https://download.owncloud.org/community/owncloud-8.0.3.tar.bz2
wget https://download.owncloud.org/community/owncloud-8.0.3.tar.bz2.md5

cat owncloud-8.0.3.tar.bz2.md5 
c22ca3211a5c99ae2353afaa619da51f  -

md5sum owncloud-8.0.3.tar.bz2
b49c20123cc955b7d85a55b86d099282  owncloud-8.0.3.tar.bz2
```

and:

```
wget https://download.owncloud.org/community/owncloud-8.0.3.zip
wget https://download.owncloud.org/community/owncloud-8.0.3.zip.md5

cat owncloud-8.0.3.zip.md5 
460e47e536cedc871a6192f649d80cce  -

md5sum owncloud-8.0.3.zip
7d7775dfba76e928bc617644570a4c60  owncloud-8.0.3.zip
```

**Comment by agriffaut** [comment]
@oparoz ok, indeed owncloud-8.0.4.zip md5 is 7d7775dfba76e928bc617644570a4c60

**Comment by oparoz** [comment]
@RealRancor - Thanks. I've updated the OP. The zip contains 8.0.4. Maybe an autobuild issue.

**Comment by MorrisJobke** [comment]
@karlitschek @cmonteroluque

**Comment by JoshData** [comment]
Any update here? My [project](https://github.com/mail-in-a-box/mailinabox) is dependent on 8.0.3 and I'm in a bind with users not being able to download it....

**Comment by karlitschek** [comment]
@cmonteroluque Who can help here?

**Comment by cmonteroluque** [comment]
@danimo please have a look, let's see if there's a way to figure out what happened here

**Comment by danimo** [comment]
Looks like the upload to the primary download server went wrong. several files are also missing for 8.0.3:

```
owncloud-8.0.3.tar.bz2
owncloud-8.0.3.tar.bz2.asc
owncloud-8.0.3.tar.bz2.md5
owncloud-8.0.3.tar.bz2.sha256
owncloud-8.0.3.zip
owncloud-8.0.3.zip.asc
owncloud-8.0.3.zip.md5
owncloud-8.0.3.zip.sha256
```

vs

```
owncloud-3rdparty-8.0.4.tar.bz2
owncloud-3rdparty-8.0.4.tar.bz2.asc
owncloud-3rdparty-8.0.4.tar.bz2.md5
owncloud-3rdparty-8.0.4.tar.bz2.sha256
owncloud-8.0.4.tar.bz2
owncloud-8.0.4.tar.bz2.asc
owncloud-8.0.4.tar.bz2.md5
owncloud-8.0.4.tar.bz2.sha256
owncloud-8.0.4.zip
owncloud-8.0.4.zip.asc
owncloud-8.0.4.zip.md5
owncloud-8.0.4.zip.sha256
owncloud-apps-8.0.4.tar.bz2
owncloud-apps-8.0.4.tar.bz2.asc
owncloud-apps-8.0.4.tar.bz2.md5
owncloud-apps-8.0.4.tar.bz2.sha256
owncloud-core-8.0.4.tar.bz2
owncloud-core-8.0.4.tar.bz2.asc
owncloud-core-8.0.4.tar.bz2.md5
owncloud-core-8.0.4.tar.bz2.sha2
```

**Comment by danimo** [comment]
@karlitschek , please re-upload

**Comment by MorrisJobke** [comment]
> @karlitschek or whoever did the release, please re-upload

@cmonteroluque

**Comment by karlitschek** [comment]
O.K. The md5 files are now fixed. The other "missing" files shouldn't matter. Stuff that is not used anymore and should be killed soon anyways.

**Comment by JoshData** [comment]
Hang on. The problem wasn't the md5s, it was the package files. When I download https://download.owncloud.org/community/owncloud-8.0.3.zip, `version.php` shows I'm downloading 8.0.4:

    <?php 
    $OC_Version = array(8,0,4,2);
    $OC_VersionString = '8.0.4';
    $OC_Channel = 'stable';
    $OC_Build = '2015-06-04T13:45:27+00:00 5fcab24e592c5f0f35d3293449dbd2f15a40f5f8';

**Comment by karlitschek** [comment]
Ahh o.k. Super strange. We are working on that.

**Comment by macinjosh** [comment]
Any progress on fixing this?

**Comment by JoshData** [comment]
Folks, if your download server was hacked and someone replaced one of the ZIP files, would you just compute a new MD5 to make people's hash warnings go away? It is a little concerning that an incorrect file remains posted at the 8.0.3 URL with a matching MD5.

**Comment by oparoz** [comment]
That's not what happened. 8.0.4 was uploaded as 8.0.3 and so the MD5 for 8.0.3 doesn't match, but the one for 8.0.4 does.

**Comment by JoshData** [comment]
> and so the MD5 for 8.0.3 doesn't match

It didn't, but it does now after @karlitschek overwrote it with the 8.0.4 MD5.

**Comment by oparoz** [comment]
Ah, so no now we have 8.0.4 twice? One named 8.0.4 and once named 8.0.3? :open_mouth:
