### ISSUE TITLE
Experimental apps are always shown

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#17122]
On my local copy of master, I did not tick the box to show experimental apps and yet I see all the apps I installed myself, labelled as experimental.

The first step would be to fix the bug and respect the tick box when showing/hiding non-approved apps.

In 8.2, it would be great if the system could differentiate between a corporate, private app which was installed in a specific, trusted folder and one coming from the app store.

**Comment by LukasReschke** [comment]
Experimental apps only affect the one displayed in the categories from the appstore. – Nothing is filtered on already installed or disabled applications as this will give a wrong expectation what actually is installed.

**Comment by oparoz** [comment]
Then I think the wording of that setting should be changed. It's not about enabling experimental apps, but about listing the ones which are available through the app store.

**Comment by DeepDiver1975** [comment]
@jancborchardt you might have an idea to get better UX on this one?

**Comment by jancborchardt** [comment]
Well, you must have enabled experimental apps then before or installed apps locally. Which apps does this happen for?

**Comment by oparoz** [comment]
It happens for all apps which were installed locally and which are not labelled as official.
You can't have a tick box for "Enable experimental apps" and then still show them when it's disabled.

Perhaps the description should be modified to "List experimental apps from the app store", but it might still be confusing if a user enables an experimental app, disables it, unticks the setting and still sees it listed in his "Not enabled" list, under "Experimental applications ahead"...

**Comment by jancborchardt** [comment]
For apps which are approved / official in the app store but you clone locally, the fix is at https://github.com/owncloud/core/pull/17050 – please review :)

In the other cases I think the behavior is correct.

**Comment by oparoz** [comment]
OK, that fix will at least remove the label from official/approved apps, but we still need to either filter out experimental apps if the switch is disabled or rename the switch to make it clear that it's only about the app store.

![nonsense](https://cloud.githubusercontent.com/assets/323220/8355635/9989428e-1b50-11e5-8d35-afb5dbbeaad2.png)

**Comment by jancborchardt** [comment]
Ah right! Ok so what we need to fix in this case is to not show experimental applications which are disabled, when the setting is not checked. (Sorry it took me so long to get it. ;)

But when you checked »enable experimental apps«, then installed one, and then uncheck the setting again – that app should still be listed and be installed of course. Only once you disable it should it be removed from the list.

So @oparoz can you submit a pull request for this? :)

**Comment by LukasReschke** [comment]
I disagree with this one. From my PoV we _should_ show even untrusted applications even if they are disabled since the code is technically still existent on the server. – Either we change the wording or we leave it as-is (what I'd do) from my PoV.

That local applications get an experimental rating if they don't have a rated OCS ID and no shipped tag is a whole other topic.

**Comment by oparoz** [comment]
Maybe add a warning at the end of the list that experimental applications are not listed due to our preferences (something along those lines), just to make sure those apps are not forgotten?

**Comment by jancborchardt** [comment]
Right, they still exist on the server. I don’t have strong design arguments either way so I think it’s fine to just keep it as it is. You installed stuff yourself after all, so it’s non-standard usage.

If there’s massive confusion coming up, we can still change this. But for now I would say let’s keep it as it is. Ok @oparoz? (We’ll see how it’s received with the 8.1 release.)

**Comment by oparoz** [comment]
I think it wouldn't hurt to reword the title. The description needs to be rewritten anyway since it's not using proper English and is too aggressive.

**Comment by jancborchardt** [comment]
Keep in mind this warning is for regular admins who don’t necessarily all know what they are doing on their small instances. So it’s ok to state that there are likely to be security issues etc.

**Comment by oparoz** [comment]
True, but it's the pot calling the kettle black. I've lost more data through the use of core apps than with 3rd party apps ;).
Some points could be softened as follows
"... have not been as thoroughly tested"
"... could cause unwanted side effects"

You have to think about the feelings of app devs who've spent a lot of time working on their projects and whose apps are instantaneously categorized as something to avoid, when an app like `owncloud/mail` per example, which is alpha quality and under "heavy development" gets the "approved" rating.

**Comment by oparoz** [comment]
One more reason to quickly introduce channels (https://github.com/owncloud/core/issues/16934). So that even approved apps can be filtered out, depending on their stability.

And I think "Experimental" is the wrong adjective. "Untested" maybe?

**Comment by jancborchardt** [comment]
@oparoz you are welcome to join the ownCloud apps review team! :) Join #owncloud-app-review
The Mail app was approved because well, it was thoroughly tested by @DeepDiver1975, @LukasReschke and me – so it’s basically design-, dev- and security-reviewed. Also, it’s in pretty wide use already and hasn’t eaten any emails. :)

**Comment by oparoz** [comment]
I would probably only have time to review apps once a month :S and I don't think I would approve many apps as most use private APIs and/or are missing descriptions.

Regarding mail, I was referring to the statement made on the project's page in the app store. It's a 0.1 release "under heavy development" which is exactly how the apps settings page describes experimental apps. 
I think you have to be careful how you manage this side of things. I've already heard devs grumble about how their work is being treated and @karlitschek is hoping to increase the number of apps tenfold. That requires happy devs :)

**Comment by jancborchardt** [comment]
As you know, the problem is always time. Any devs in particular who are unhappy about the state of app reviews? Then we should all get them into the app review team. :)

**Comment by oparoz** [comment]
I agree that the problem is time, but for something as sensitive as app reviews, I think this needs to be semi-professionally done. People need to be trained, there needs to be a security review, etc. or the approved status is meaningless.

1. oC names dev an approver
2. Approver approves apps with backdoors (easy to implement and easy to miss unless trained) by mistake
3. Users start to find their data on public forums
4. App is removed, etc., but it's too late, the damage is done

But even with a thorough review process, apps slip through... Look at all the nasty apps which went through Apple's net and they take their sweet time to review apps.

On top of that oC doesn't have a remote kill switch... I need to open an issue about that.

**Comment by jancborchardt** [comment]
@oparoz I just had a chat with @karlitschek about a related topic and was wondering what you think: How about we explicitly ask devs to submit their apps for reviewing?

That makes sure that these devs have some kind of commitment and we can be sure that they at least in some way are dedicated to maintaining their app. Then from us (@LukasReschke, me and others) they will get code-, security- and design-feedback for their app. And eventually they get approved.

I think a call for reviewing like this allows us to focus a bit. Currently one big problem is also that we simply don’t know where to start with the app reviews. If we have a simple submission queue we can work through that more easily. cc @jospoortvliet if there’s any promo we need to do there.

**Comment by oparoz** [comment]
I think it absolutely makes sense. All mobile devs have to do it in order for their apps to even show in the app stores. It will also help with the communication side and devs will be happy to get feedback on their work.

Don't underestimate the amount of work involved on the approving side though. You'll need to publish reasonable acceptance criteria and stick to it.

Also, if you're committed to make the AppFramework the preferred way to develop apps, you should definitely introduce a label for it, just like BlackBerry did with their "Built for BlackBerry" label. It definitely helps making a first selection. I try to avoid all apps which don't use the framework as it's almost certain they use private APIs and will break sooner rather than later (+ I wont be able to fix them as easily)

**Comment by jospoortvliet** [comment]
@oparoz a few thoughts.

* https://doc.owncloud.org/server/8.1/developer_manual/general/publishing.html -> what do you think? This should at least explain our goals ;-)
* I think even if you have only time to review an app once a month it would still rock if you were able to join the review team. yes, reviews should be done professionally, but we can't limit the reviewers to ownCloud employees, imho.
* we probably should set up a wiki page where people can easily add a link to their app as a first step in getting a review queue. That would work, yes? That is a barrier for those app developers without a github account but it's a start.
* and the risks you mention - well, as you say, this even happened to Apple. It is probably not really possible to fully prevent that but once we're target for hackers like that, ownCloud must be so popular we will be able to afford a big team of ppl who review apps ;-)
* with regards to the wording: we have to find a balance between 'properly' scaring (warning) users about the risk of entirely unreviewed apps and being nice to developers. I think the best solution is to ensure that apps get reviewed promptly so the ones in the 'experimental' category really are that - experimental. I know, this is an hard-to-achieve ideal but as @jancborchardt points out - that is why we need help ;-)

**Comment by oparoz** [comment]
Some thoughts about the documentation
* Approved apps deemed " to be stable for casual to normal use" as opposed to be ready for serious use. What about if a MDM company creates a connector so that ownCloud can be used in their secure container and keeps it in their repo?
* "minimum 5 ratings, average score 60/100 or better". Unfortunately, I think the maths doesn't work here. Apps start at 50 and each click is worth 1 point. There is also an issue with how versioning works. 8.1 apps start at 50 again, so that might confuse users who see approved app with a rating of below 60 when the previous version was in the 70s or 80s.
* I like the notes about trust levels and audits. Gives a better idea of what is expected of devs to be approved
* "warning shows for security/stability risks" I still don't think it's a good idea. Name one mobile app store which labels its apps as possibly insecure or experimental, apart from the ones in the beta programmes.
* "Apps can only use the public ownCloud API" `can` has to be modified to `should`. The public API is not mature enough. An alternative could be to ask developers to request permission to use some APIs and approvers could use the list of well known methods which don't exist in the public space to vet apps. It would help guide devs into using the proper APIs in case they took the wrong approach and would help the core team better understand which APIs are missing.
* Why not force the use of the AppFramework for new apps? It would make things much easier to review.
* There are still a few typos left ;)


> even if you have only time to review an app once a month

Regarding taking part in reviewing apps, I need to do a dry run to see if I can afford the time and if I would add any value to the process.

> we probably should set up a wiki page 

I hate mailing lists, but it does make sense to ask for approval there. Maybe you should provide a template or a web submission form which would auto post to the list and all further communication would happen off list. The only reply to a list post should be that someone has been assigned to the task.

> with regards to the wording

After having read the publishing page, I feel better about the review process and the value of the approved label, but I still don't agree on the benefit of scaring away users. Show me another app store which treats its developers that way. If an app is approved by Apple, BlackBerry or Google, it's considered good enough to be of help to any user. Some apps may have a special "verified" label next the company name in some store so that you know you're getting the real thing, but it's usually not implied that they're superior. This is certainly not true of quite a few official oC apps which don't meet the criteria on that publishing page.
If you get the man power, you could create a special Black label for official and approved apps which are of excellent quality. That could help users pick the superior Calendar, Tasks or Mail app instead of blindly trusting unmaintained "official" apps.

**Comment by LukasReschke** [comment]
> "Apps can only use the public ownCloud API" can has to be modified to should. The public API is not mature enough. An alternative could be to ask developers to request permission to use some APIs and approvers could use the list of well known methods which don't exist in the public space to vet apps. It would help guide devs into using the proper APIs in case they took the wrong approach and would help the core team better understand which APIs are missing.

Won't happen. If something is missing app developers has to add new APIs to core but we won't approve apps that use the private API. There may be cases where we do accept excuses but this is not going to be the default and a "should" implies otherwise. - We should stay with the "can" here from my PoV.

> After having read the publishing page, I feel better about the review process and the value of the approved label, but I still don't agree on the benefit of scaring away users. Show me another app store which treats its developers that way. If an app is approved by Apple, BlackBerry or Google, it's considered good enough to be of help to any user. Some apps may have a special "verified" label next the company name in some store so that you know you're getting the real thing, but it's usually not implied that they're superior. This is certainly not true of quite a few official oC apps which don't meet the criteria on that publishing page.

Mobile apps run sandboxed. We can't do this. Installing an ownCloud app really means "all your data is going to be eaten". There is a reason why we add a huge scary text. I mean we have no problem with giving 100 apps an approved rating as long as know that the developer is a somewhat trustworthy person and the app looks somewhat sane. But we should be scary.

> Why not force the use of the AppFramework for new apps? It would make things much easier to review.

I'd go with something like "should follow best practises, i.e. using the AppFramework and not deprecated APIs where possible", but we should not make this an hard requirement. I mean if code works: Fine. We can make it clear that using the AppFramework makes reviewing easier and thus makes us approve the app faster but we should not enforce the full technology stack.

> "minimum 5 ratings, average score 60/100 or better". Unfortunately, I think the maths doesn't work here. Apps start at 50 and each click is worth 1 point. There is also an issue with how versioning works. 8.1 apps start at 50 again, so that might confuse users who see approved app with a rating of below 60 when the previous version was in the 70s or 80s.

The latter part will be fixed with an upcoming AppStore update that @karlitschek is working on. The same app in the appstore can then serve multiple versions.

**Comment by LukasReschke** [comment]
upcoming AppStore update === will _very_ likely be in 8.1

**Comment by oparoz** [comment]
>  If something is missing app developers has to add new APIs to core

Everything which relates to public sharing is not in the public space and it's not something that an app dev can fix on its own. On top of that it would probably take 6-12 months to fix issues in core before being able to start working on the app. You have to be realistic about your expectations. Very few, if any, core apps pass the code_checker test. The "do as I say, not as I do" attitude is not the best way to get developers to work on expanding the ecosystem. A lot of apps come from the need to improve what's available in core, but devs might get discouraged because their app would be stuck in the experimental bin or frustrate users because of missing key functionalities.

> Mobile apps run sandboxed

Good point, but they can still wipe your internal or external storage, wreck your contacts list, corrupt your calendar, etc. The user chooses to trust the app with his data.

> We can make it clear that using the AppFramework makes reviewing easier and thus makes us approve the app faster 

Works for me.

> The latter part will be fixed with an upcoming AppStore update

Good news :)

**Comment by LukasReschke** [comment]
> Everything which relates to public sharing is not in the public space and it's not something that an app dev can fix on its own. On top of that it would probably take 6-12 months to fix issues in core before being able to start working on the app.

Which probably really means that the current public sharing API is not to be really expected to be widely used by third-party developers :speak_no_evil: 

> Good point, but they can still wipe your internal or external storage, wreck your contacts list, corrupt your calendar, etc.

Only with granting explicit permission.

**Comment by oparoz** [comment]
> Which probably really means that the current public sharing API is not to be really expected to be widely used by third-party developers :speak_no_evil:

Indeed, which means that 3rd party apps can't compete. Devs have to choose between getting their apps approved or give users what they want, leading to an unappealing app store littered with constrained and experimental apps :dr_doom: 

> Only with granting explicit permission.

And that's a model you could follow, sort of. Get rid of the warning in the app store and add a warning which pops up when someone tries to enable an approved app. Would work with occ as well.

**Comment by jospoortvliet** [comment]
How about we get together and discuss this at the conf, see what we can improve. By that time we have had about 6-7 weeks of experience with it... I don't think this is, like, totally burning down, is it?

**Comment by oparoz** [comment]
I think you should hold an open forum on these sort of issues, to try and get some feedback. You could also ask everyone to fill in a questionnaire since some people might not feel comfortable coming forward publicly.

**Comment by jospoortvliet** [comment]
well, we do mail to the ML and discuss it here ;-)

That's about as much open forum as you can have here, I suppose. I'll also blog about this at some point soon. And there is the conference....

**Comment by oparoz** [comment]
Let's see how the change is received by the community at large. If people are unhappy, you'll know -> No growth, Twitter rants, blog posts, etc.

I think the first reaction is going to be devs trying to get approved in order to avoid the experimental label and that's a good thing if approval or rejection happens within a week. I still think a form is a good idea because you can link to the terms and people won't be able to ignore your criteria.

**Comment by jospoortvliet** [comment]
yes, a form might be a good idea. But I don't see much effort put in until the release, at least not by me - I've been crazy busy with promotion/marketing preparations for the release, writing my fingers blue, editing videos etc. And everybody else is busy fixing bugs. So, for now - and maybe that is a mistake, but it is what it is - this is where we stand.

Also note that apps, right now, would simply not show up AT ALL if they weren't added to the app store. Users had to install them manually. So in that regard, this is a step forward for most apps.

And yes, the idea is of course to motivate app developers to try and get their app from 'experimental' to 'approved' ;-)

**Comment by oparoz** [comment]
No problem about the form, just an idea. Maybe do an annual survey with some prices when there is not a release or a conference to organise? ;) In my experience, surveys have to be short or the incentive large (a copy of the $2000 report, etc.)

**Comment by jancborchardt** [comment]
This is fixed, eh? @LukasReschke
