### ISSUE TITLE
Change the name of "experimental file locking" to "transactional locking"

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#17120]
I can't find this issue and I know we filed it and discussed it.

Let's change the name of "experimental file locking" to "transactional locking"

At a minimum, this will have an impact on the admin server status information and config.php. 

@MTRichards @icewind1991 @PVince81 @cmonteroluque

**Comment by LukasReschke** [comment]
So does this indicate that experimental file locking is not experimental anymore?

**Comment by jnfrmarks** [comment]
I don't think it's an experiment.  I do think it may be beta quality.

**Comment by jnfrmarks** [comment]
Maybe we could do something like "transactional locking (beta)" ....

**Comment by LukasReschke** [comment]
That sound good! :+1:

**Comment by oparoz** [comment]
Now if only we had [release channels](https://github.com/owncloud/core/issues/16934)... :)

**Comment by PVince81** [comment]
I agree with "beta" quality.

@oparoz it's a beta feature disabled by default.

"transactional locking" sounds fine. Technically it's not as transactional as I wish it should be, but seems to get the job done.

**Comment by oparoz** [comment]
@PVince81 - It doesn't matter if it's disabled by default. People will enable it, just like the current file locking, hoping it improves their experience. Adding the beta to the app name is fine, but I'm just saying it would be much easier if people could filter out apps based on their stability preference, as stated in the other ticket.

**Comment by PVince81** [comment]
It's not an app, it's a feature deep in core.
Also currently you need a redis server to make it work, which not everyone has.
This is how to enable it:

**Comment by PVince81** [comment]
https://doc.owncloud.org/server/8.1/admin_manual/configuration_files/files_locking_experimental.html

CC @carlaschroder

**Comment by MTRichards** [comment]
@jnfrmarks 
Thank you.

**Comment by carlaschroder** [comment]
At some point the name has to change :) Just let me know when.

**Comment by jnfrmarks** [comment]
I've marked this as sev-1 so it doesn't get lost in the shuffle of releasing 8.1

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/17190

**Comment by carlaschroder** [comment]
Does this mean it is time to update the docs?
@PVince81 @MTRichards

**Comment by PVince81** [comment]
@carlaschroder yes please, jump in the transactional bandwagon!

**Comment by carlaschroder** [comment]
Yay, we're all going for a ride!

**Comment by davitol** [comment]
:+1: Fixed in ersion":"8.1.0.8","versionstring":"8.1 RC2"
