### ISSUE TITLE
Differentiate between private, trusted apps and ones downloaded from the app store

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#17123]
It's fine to have ratings for apps coming from the app store, but we should be able to trust some apps, just like we can trust PGP keys.

Currently, privates apps are shown as experimental and dangerous.

I'd like to be able to put my trusted apps in a folder and get them recognized as such in the settings. A blue label would look nice :)

```
'apps_paths' => array(
    array(
        'path'=> '/var/www/owncloud/corporateapps',
        'url' => '/corporateapps',
        'writable' => false,
        'trusted' => true,
    ),
),
```

**Comment by PVince81** [comment]
@LukasReschke

**Comment by LukasReschke** [comment]
Well. Contributions welcome. That said, for single apps that are not distributed via the app store this can already be achieved by setting the shipped flag in info.xml

**Comment by oparoz** [comment]
Hacking the shipped flag is just that, a hack, but I can study that example to make it work for my use case

**Comment by PVince81** [comment]
Would the new app signing process be suitable for this requirement ?

**Comment by oparoz** [comment]
I don't think so, simply because each and every app needs to be approved by ownCloud before delivering a certificate. If anything, the situation got worse, because shipped app need to be signed, so private apps can't use this trick any more.

Signing needs to be extended to trust developers instead of apps. It could be very useful as it could be used to revoke the certs of all apps delivered by a rogue dev. That's how it works on mobile platforms afaik.
