### ISSUE TITLE
External Storage - E-Tag did not exist

### ISSUE THREAD

**Issue by JT1301** [owncloud/core#17137]
Hello, I hope someone can help to fix this issue:

<h5>Expected behaviour:

Client Application (Desktop) should sync Files to the Owncloud (external storage / smb)

<h5>Actual behavior:

If you create a new file the sync to the external storage works but when you trying to modify an existing file there is an error (E-Tag did not exist)

<h5>Steps to repdoduce:

1. ![owncloud](https://cloud.githubusercontent.com/assets/10863564/8327825/afbe3d6a-1a6b-11e5-825a-40dd9915b050.JPG)
2. Now create an Excel File on a client, save and close the file
3. Wait for sync
4. Edit this File and save (do not change the name)
5. Find the Error in the log
6. Rename the file and the sync works fine

**Modify files without the External Storage App works fine too.**

<h5>Server configuration

Remark: Configuration described below are equal for both servers (ServerA, ServerB).

Operating system: Debian Wheezy

Web server: Apache

Database: MySQL

PHP version: 5.4.41

ownCloud version: 8.0.4 (stable) 
<h5>Client configuration

Operating system: Windows 8 (x64) / Windows 7 (x64) (same result)

Client app: Windows Owncloud Client 1.8.1 & for testing ownCloud-1.8.3.5212rc3 (same result)

<h5>Client-Log:

>06-24 12:08:29:144 0x3fea28 OCC::SyncEngine::slotDiscoveryJobFinished: <<#### Post-Reconcile end ####################################################  1080
06-24 12:08:29:157 0x3fea28 OCC::Folder::slotSyncStarted: #### Propagation start #################################################### >>
06-24 12:08:29:158 0x3fea28 OCC::SocketApi::slotUpdateFolderView: Not sending UPDATE_VIEW for "ownCloud" because status() is 3
06-24 12:08:29:160 0x3fea28 OCC::ownCloudGui::slotComputeOverallSyncStatus: Folder in overallStatus Message:  OCC::Folder(0x573cc88)  with name  "ownCloud"
06-24 12:08:29:166 0x3fea28 OCC::ownCloudGui::slotSyncStateChange: Sync state changed for folder  "ownCloud" :  "Sync Running"
06-24 12:08:29:169 0x3fea28 OCC::BandwidthManager::registerUploadDevice: void OCC::BandwidthManager::registerUploadDevice(OCC::UploadDevice*) OCC::UploadDevice(0x6352308)
06-24 12:08:29:172 0x3fea28 OCC::AbstractNetworkJob::start: !!! OCC::PUTFileJob created for "https://cloud.opus-mode.de" + "/Test/Test.xlsx"
06-24 12:08:29:199 0x3fea28 OCC::BandwidthManager::unregisterUploadDevice: void OCC::BandwidthManager::unregisterUploadDevice(OCC::UploadDevice*) OCC::UploadDevice(0x6352308)
06-24 12:08:29:984 0x3fea28 OCC::PropagateUploadFileQNAM::slotPutFinished: void OCC::PropagateUploadFileQNAM::slotPutFinished()  QUrl( "https://cloud.opus-mode.de/remote.php/webdav/Test/Test.xlsx" )  FINISHED WITH STATUS 0 "" QVariant(int, 200) QVariant(QString, "OK")
06-24 12:08:29:986 0x3fea28 OCC::SyncJournalErrorBlacklistRecord::update: blacklisting  "Test/Test.xlsx"  for  25 , retry count  1
06-24 12:08:29:987 0x3fea28 OCC::SyncJournalDb::updateErrorBlacklistEntry: set blacklist entry for  "Test/Test.xlsx" 1 "Der Server hat den letzten Block nicht bestätigt. (Der E-Tag war nicht vorhanden)" 1435140509 25 1435140505 "558a818c9d7e2"
06-24 12:08:29:987 0x3fea28 OCC::SyncEngine::slotJobCompleted: void OCC::SyncEngine::slotJobCompleted(const OCC::SyncFileItem&) "Test/Test.xlsx" INSTRUCTION_SYNC 2 "Der Server hat den letzten Block nicht bestätigt. (Der E-Tag war nicht vorhanden)"
06-24 12:08:29:995 0x3fea28 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:ERROR:C:\Users\t.junker.OPUS\ownCloud\Test\Test.xlsx"
06-24 12:08:29:996 0x3fea28 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:ERROR:C:\Users\t.junker.OPUS\ownCloud\Test\Test.xlsx"
06-24 12:08:29:997 0x3fea28 OCC::BandwidthManager::unregisterUploadDevice: void OCC::BandwidthManager::unregisterUploadDevice(OCC::UploadDevice*) OCC::UploadDevice(0x6352308)
06-24 12:08:30:007 0x3fea28 OCC::SyncJournalDb::walCheckpoint: void OCC::SyncJournalDb::walCheckpoint() took 0 msec
06-24 12:08:30:008 0x3fea28 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "All Finished." 
06-24 12:08:30:010 0x3fea28 OCC::SyncEngine::finalize: CSync run took  1947
06-24 12:08:30:011 0x3fea28 OCC::BandwidthManager::~BandwidthManager: virtual OCC::BandwidthManager::~BandwidthManager()
06-24 12:08:30:012 0x3fea28 OCC::Folder::slotSyncFinished: -> SyncEngine finished without problem.
06-24 12:08:30:014 0x3fea28 OCC::Folder::bubbleUpSyncResult: Processing result list and logging took  1  Milliseconds.
06-24 12:08:30:069 0x3fea28 OCC::Folder::bubbleUpSyncResult: OO folder slotSyncFinished: result:  3
06-24 12:08:30:069 0x3fea28 OCC::Folder::slotSyncFinished:   ** error Strings:  ("Test/Test.xlsx: Der Server hat den letzten Block nicht bestätigt. (Der E-Tag war nicht vorhanden)")
06-24 12:08:30:070 0x3fea28 OCC::Folder::slotSyncFinished:     * owncloud csync thread finished with error
06-24 12:08:30:070 0x3fea28 OCC::Folder::slotSyncFinished: the last 1 syncs failed

<h5>Owncloud Server Log:

>Error	PHP	Semicolon not supported in commands at /var/www/owncloud/apps/files_external/3rdparty/smb4php/smb.php#116	2015-06-24T10:32:58+00:00
Error	PHP	Undefined index: size at /var/www/owncloud/lib/private/files/cache/scanner.php#268	2015-06-24T10:32:44+00:00
Error	PHP	Undefined index: size at /var/www/owncloud/lib/private/files/cache/scanner.php#265	2015-06-24T10:32:44+00:00
Error	PHP	Undefined index: mimetype at /var/www/owncloud/lib/private/files/cache/scanner.php#263	2015-06-24T10:32:44+00:00
Error	PHP	Undefined index: size at /var/www/owncloud/lib/private/files/cache/scanner.php#268	2015-06-24T10:32:44+00:00
Error	PHP	Undefined index: size at /var/www/owncloud/lib/private/files/cache/scanner.php#265	2015-06-24T10:32:44+00:00
Error	PHP	Undefined index: mimetype at /var/www/owncloud/lib/private/files/cache/scanner.php#263	2015-06-24T10:32:44+00:00
Error	PHP	Undefined index: size at /var/www/owncloud/lib/private/files/cache/scanner.php#268	2015-06-24T10:32:44+00:00
Error	PHP	Semicolon not supported in commands at /var/www/owncloud/apps/files_external/3rdparty/smb4php/smb.php#116	2015-06-24T10:36:17+00:00
Error	PHP	Semicolon not supported in commands at /var/www/owncloud/apps/files_external/3rdparty/smb4php/smb.php#116	2015-06-24T10:35:12+00:00

It would be nice if someone can help.

Thanks and best regards

**Comment by LukasReschke** [comment]
Looks like a duplicate of https://github.com/owncloud/core/issues/16853, can you try to use the patch from https://github.com/owncloud/core/pull/16862? Will be properly fixed with 8.0.5

**Comment by LukasReschke** [comment]
Btw. thanks a lot for filling out the issue template. Much appreciated!

**Comment by JT1301** [comment]
Sorry for the duplicated issue.

It works! You fixed it! Thanks a lot
