### ISSUE TITLE
Plug Doctrine logger in OC logger for log_query

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#17132]
Currently the `log_query` setting is going through custom code/wrappers that log queries.
However these logs are missing many things like transactions.

I noticed that Doctrine has its own logger, so why not just use that whenever "log_query" is set to true ?

@DeepDiver1975 @icewind1991

**Comment by DeepDiver1975** [comment]
agreed

**Comment by PVince81** [comment]
Looks like we already got something: https://github.com/owncloud/core/blob/master/lib/private/diagnostics/querylogger.php

Only enabled when `define('DEBUG', 1)`.
Now to find out where it logs...

**Comment by DeepDiver1975** [comment]
> Now to find out where it logs...

another app is required https://github.com/icewind1991/owncloud-clockwork

Writing to a file should still be another option

**Comment by PVince81** [comment]
We should rewire "log_query" to log in the regular console using DEBUG log level when true.

**Comment by PVince81** [comment]
Moving to 9.0 to find a solution that doesn't involve enabling third party apps

**Comment by PVince81** [comment]
Nice to have, moving to backlog for now

**Comment by butonic** [comment]
log_query was removed with https://github.com/owncloud/core/commit/a5095447b72437586830d5252eb57ca28c98dc34 and is now part of https://github.com/owncloud/diagnostics

there is still logging related code in core. needs reevaluation if cleanup is still needed
