### ISSUE TITLE
removeMount should lock

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#17144]
@icewind1991 looks like "$view->removeMount()" doesn't lock.

We should exclusive-lock the mount point path (not the storage root) to avoid concurrent processes to access that path during the umount (in case sharing takes a while...)

Requires https://github.com/owncloud/core/pull/17070 to be merged first for the extra argument.

The same should be done for adding mount points (when sharing, etc)

**Comment by PVince81** [comment]
@cmonteroluque @karlitschek @DeepDiver1975 moving to 8.1.1.
Needed to make locking more watertight.

**Comment by MorrisJobke** [comment]
@PVince81 Is there any PR for this?

**Comment by PVince81** [comment]
No

**Comment by DeepDiver1975** [comment]
@PVince81 what is the criticality of this?

**Comment by PVince81** [comment]
Not critical. This should be seldom as it's only when unsharing files.
I documented this for completeness.

We should make sure that locking is water-tight eventually by covering
all operations.

**Comment by cmonteroluque** [comment]
@PVince81 agree that it needs to be better, 8.1.2 not looking possible at this point.

**Comment by PVince81** [comment]
Not sure why we put this on 8.1.4. Other remaining locking tasks like https://github.com/owncloud/core/issues/17243 are now set to 9.0.

**Comment by icewind1991** [comment]
I'm not sure this is needed, I don't think there is any chance for data loss since the worst that can happen is a different process writing to a mount that is being removed, which is the same result as when the other processed finished it's write before the storage is removed

**Comment by PVince81** [comment]
Best would be to do a test with `sleep()` in the right places to make sure it works as you think it does.

**Comment by PVince81** [comment]
@nickvergessen mind taking over ? If we find that we don't need a lock there then I'm fine dropping it, but we need to verify this.
