### ISSUE TITLE
Deleted shares that point to a deleted user

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#17146]
- [ ] Extend DeleteOrphanedSharesJob to also delete shares that point to a delete user
- [ ] Schedule that job whenever a user was just deleted (post delete user hook)

@MorrisJobke

**Comment by schiesbn** [comment]
If we schedule the jib for explicitly deleted users I'm fine with it. But I'm not sure if it is a good idea if we delete all shares of a user who just disappeared. How can we guarantee that the user was really deleted? It could also happen that we don't find a user just because the user back-end is temporarily unavailable, it would be really bad if we would delete shares in this case.

**Comment by PVince81** [comment]
Good point. But I thought we had a local cache list of users ?
If not, maybe it's time to introduce this ?

**Comment by MorrisJobke** [comment]
> It could also happen that we don't find a user just because the user back-end is temporarily unavailable, it would be really bad if we would delete shares in this case.

Then another exception (in the case of LDAP: ServerNotAvailable) will be thrown. We shouldn't handle backend not availabe and user couldn't be find on an available backend in the same way... then it's a bug in the backend.

**Comment by PVince81** [comment]
Tricky stuff, moving this enhancement to 9.0

**Comment by PVince81** [comment]
CC @cmonteroluque @MTRichards @DeepDiver1975

**Comment by cmonteroluque** [comment]
ok @PVince81

**Comment by PVince81** [comment]
We're past feature freeze and this is tricky. Moving to 9.1.

**Comment by PVince81** [comment]
tricky and dangerous :wink:

**Comment by rullzer** [comment]
Actually we already listen to hooks for user deletion... so most shares *should* already be handeld.

**Comment by PVince81** [comment]
Hmm, I think @cdamken observed this lately. Or was it @SergioBertolinSG ?

**Comment by SergioBertolinSG** [comment]
@PVince81 I noticed this while checking the database.

**Comment by PVince81** [comment]
Hmm, I thought I already saw something deleting shares from deleted users, but it's not in that class...
