### ISSUE TITLE
getUserFolder() in AppFrameWork should work with tokens

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#17151]
An app shouldn't have to try and figure out which folder a token gives access to.
The system should be able to figure out which user has to be used and use it to compute the reply it will give to the `getUserFolder()` request.

@Raydiation @LukasReschke

**Comment by Raydiation** [comment]
Belongs to sharing rather than the file system, correct?

**Comment by oparoz** [comment]
Well, yes, the current code which checks for the token is in the sharing app, since there is still no middleware which does it in the AppFramework. That's request https://github.com/owncloud/core/issues/12832

And this request can be a sub-task of https://github.com/owncloud/core/issues/12676

I knew I did highlight that gap before, but used the wrong search terms to find it...

**Comment by oparoz** [comment]
Well, the code which checks for the token is in the sharing app, but it should move to the AppFramework middleware https://github.com/owncloud/core/issues/12676.

Once that's done, the user should be known to the framework and getCurrentUser and getUserFolder should just work and return the needed information

**Comment by Raydiation** [comment]
Well you pass the token to a service that retrieves the user I'd, then you can return the appropriate user folder right?

**Comment by Raydiation** [comment]
Id*

**Comment by oparoz** [comment]
That's what I do, yes, but devs shouldn't have to build that service into every app which wants to present public information. It should be part of the framework.

And if the framework can provide, the id, it can also provide the folder.

**Comment by Raydiation** [comment]
Well then your'e coupling sharing and the file system together which are ATM decoupled. I personally see no harm in having two instead of one line to do this.

**Comment by oparoz** [comment]
Yes, the only reason I'm asking is that it's already working that way when a user is logged in. You don't need to provide a userId, the method will get it for you. So it's shouldn't be any different when using a token, otherwise we have to duplicate all our calls.

**Comment by oparoz** [comment]
After discussing it via IRC, it's clear that getUserFolder($user) should always be passed a user. The way to make it consistent with apps is to always get a userId before asking for the folder.
