### ISSUE TITLE
Add notice when app lists fail to load from owncloud.org

### ISSUE THREAD

**Issue by pkay42** [owncloud/core#17156]
The apps page: /index.php/settings/apps will check against owncloud.org for lists of available apps to enable.  However, if owncloud.org cannot be reached (for example, if root certificates don't include owncloud.org) then the app list silently fails, and nothing is displayed (only enabled apps show up).

Better would be a warning that a secure connection to owncloud.org could not be established.  At the least a log message, but a message on the screen would help.

**Comment by PVince81** [comment]
The question is maybe rather why wouldn't the root certificates be included ? I'd expect them to always be the case.

But still, you are right that some kind of notification should be displayed in case of any error.

**Comment by pkay42** [comment]
That's another thing that might could be done & would make things easier
for the administrator.  On the other hand, installing root certificates
could be a big hassle (I don't know, but I can guess), and if the admin
knows they're out of date (thanks to a warning) they can use their native
tools to update them.

**Comment by RealRancor** [comment]
Cross-Post from #18269 :

Currently a lot of users are struggling with failed logins to the appstore for various reasons like:

    Missing /config/ca-bundle.crt (Currently unknown why this was missing)
    Wrong 'appstoreurl' in config.php (e.g. by copy over the config.sample.php in the past)
    Buggy OpenSSL/NSS/PHP versions
    Accidentally disabled 'appstoreenabled' in config.php
    Empty or wrong configured 'proxy' => '', in config.php (e.g. by copy over the config.sample.php in the past)
    Anything else?

This is causing an app overview with only the "Enabled" and "Not Enabled" categories but no other categories like "Productivity".

It could be useful to be a little bit more verbose on the app overview if a connection is failing to prevent a lot of duplicate issues / posts about the same problems.

**Comment by PVince81** [comment]
@RealRancor has this appear again lately ?

I'll move this ticket to 9.2 for now as we should still have some kind of visible error message in the UI.

**Comment by RealRancor** [comment]
@PVince81 It happens from time to time if a user is e.g. blocking the outbound access to apps.owncloud.com.

**Comment by PVince81** [comment]
Will be obsoleted by the market. @DeepDiver1975 please make sure to have such error handling there.
