### ISSUE TITLE
OC 8.1beta2 shared file download problem

### ISSUE THREAD

**Issue by zsirmo** [owncloud/core#17168]
php log:

```
PHP Fatal error:  Call to a member function isReadable() on a non-object in /var/www/ownstorage/lib/private/files/storage/wrapper/encryption.php on line 273, referer: https://ownstorage/index.php/apps/files?dir=.......
```

owncloud log:

```
Call to a member function isReadable() on a non-object at \/var\/www\/ownstorage\/lib\/private\/files\/storage\/wrapper\/encryption.php#273","level":3,"time": "2015-06-25T09:07:39+00:00","method":"GET","url":"\/index.php\/apps\/files\/ajax\/download.php?dir=......"
```

**Comment by DeepDiver1975** [comment]
@zsirmo Thanks a lot for reporting issues back to us!

We need some more information to properly support you with your issue!

Can I ask you to follow our guidelines for submitting bugs as described here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

Thanks a lot!

**Comment by zsirmo** [comment]
### Steps to reproduce
1. don't reproduce problem, but file owner don't download original file 

### Server configuration
Ubuntu 12.04.5 LTS
apache2                                       2.2.22-1ubuntu1.9
mysql-server-5.5                              5.5.43-0ubuntu0.12.04.1
libapache2-mod-php5                           5.4.17-1~lucid+1
owncloud 8.1 beta2

**List of activated apps:**
activity

**The content of config/config.php:**
$CONFIG = array (
  'instanceid' => '51542b12e6e20',
  'datadirectory' => '/home/storage',
  'dbtype' => 'mysql',
  'version' => '8.1.0.6',
  'dbname' => 'storage',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'installed' => true,
  'maintenance' => false,
  'forcessl' => true,
  'trashbin_retention_obligation' => 5,
  'theme' => '',
  'loglevel' => '0',
  'trusted_domains' =>
  array (
    0 => 'storage.mediaexchange.hu',
  ),


**Are you using external storage, if yes which one:
NO

**Are you using encryption:** yes/no
NO

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
webdav

### Client configuration
tested:
Windows 7 Firefox/Chrome
MAC OS X Firefox/Safari

### Logs
#### Web server error log
PHP Fatal error:  Call to a member function isReadable() on a non-object in /var/www/ownstorage/lib/private/files/storage/wrapper/encryption.php on line 273, referer: https://ownstorage/index.php/apps/files?dir=.......

#### ownCloud log (data/owncloud.log)
Call to a member function isReadable() on a non-object at \/var\/www\/ownstorage\/lib\/private\/files\/storage\/wrapper\/encryption.php#273","level":3,"time": "2015-06-25T09:07:39+00:00","method":"GET","url":"\/index.php\/apps\/files\/ajax\/download.php?dir=......"

#### Browser log

**Comment by compuguy** [comment]
I can confirm a similar issue, but on a different line in encryption.php (upgrade and key migrate seemed to have worked without issue): 
Error	PHP	Call to a member function isReadable() on a non-object at /var/www/owncloud/lib/private/files/storage/wrapper/encryption.php#288

**Comment by PVince81** [comment]
@schiesbn

**Comment by oparoz** [comment]
@zsirmo - Are you using Gallery+ from the app store?

**Comment by PVince81** [comment]
Please try again with 8.1.1.
There were some issues with the encryption wrapper on 8.1.0. Note that the encryption wrapper is active even when encryption is disabled, but it shouldn't do anything.

If you're still having trouble with 8.1.1, feel free to reopen.
Thanks.
