### ISSUE TITLE
When the file .MOV is shared by link with Internet Explorer you can't see the icon

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/core#17167]
### Steps to reproduce
1. Open your DESKTOP client
2. Go to Open Folder "ownCloud"
3. Upload a big file (2.8 GB) .MOV
4. Right click on the file sync filer
5. Select share with ownCloud
6. Click to the link

### Expected behaviour
You can see the icon

### Actual behaviour
The Internet Explorer is open, but you the Icon say "It not found any video that has a compatible format and MIME type"

![screen shot 2015-06-25 at 13 41 02](https://cloud.githubusercontent.com/assets/12032058/8353594/f89bc3c0-1b3f-11e5-92e2-d7a5394e238f.png)

### Server configuration
Desktop v ownCloud-1.8.3.2465-nightly20150625.pkg 
Server v {"installed":true,"maintenance":false,"version":"8.0.5.0","versionstring":"8.0.5beta","edition":"Enterprise"}

**Comment by DeepDiver1975** [comment]
This is because IE is a browser with not that many features -> won't fix
