### ISSUE TITLE
Packaged default settings in htaccess and user.ini confusing

### ISSUE THREAD

**Issue by RobinMcCorkell** [owncloud/core#17174]
Imagine these scenarios:
- Alice, with moderate knowledge of Apache and PHP, wants to install ownCloud. She installs the tarball/distribution package, configures as necessary in Apache, and knows that large files will be uploaded so sets `upload_max_filesize` and `post_max_size` in `php.ini`. However, she still gets 'Upload (max. 513MB)', due to the `.htaccess` file.
- Bob, with advanced knowledge of nginx but moderate knowledge of PHP (FPM), wants to install ownCloud. Ditto as above, and he gets the same 513MB limit due to `.user.ini`. Unlike `.htaccess` however, this is less known about. (PS @carlaschroder the [doc on large uploads](https://doc.owncloud.org/server/8.0/admin_manual/configuration_files/big_file_upload_configuration.html) only mentions `php.ini`, with only an (unrelated) footnote even acknowledging the presence of `.user.ini`)

The problem isn't just with the max upload size. A `memory_limit` directive exists in both `.htaccess` and `.user.ini`, set to 512MB. This is almost guaranteed to be wrong - most systems will have it set way higher, and embedded devices are lucky to have 256MB.

My point is, we shouldn't be setting these configuration parameters, which override the system php.ini parameters, unless the admin has specifically asked for that in the web interface (we used to have a selector for the upload size - I couldn't find it in a quick search though). We should not package any default settings for the upload size or memory limit.

Note, I'm not saying admins never read the documentation (although they often don't), or that admins don't know what their software does, but rather that we should be sensible with packaged defaults.

Thoughts? cc @PVince81 @DeepDiver1975 @MorrisJobke @LukasReschke

**Comment by RealRancor** [comment]
Hi,

1. If the .htaccess file of Alice is writable and working (mod_env also installed) she should get an "File handling" input box shown in the admin box

2. Bob's problem could be solved by https://github.com/owncloud/core/issues/14748

In general oC 8.1 will always show the "File handling" input box: https://github.com/owncloud/core/issues/10600 and https://github.com/owncloud/core/pull/14133

**Comment by Xenopathic** [comment]
@RealRancor Ah, knew it was there somewhere. My `ack` skills clearly aren't sufficient. However, that still only fixes half the problem - we shouldn't set *any* defaults in the package, because they will inevitably be wrong.

**Comment by RealRancor** [comment]
> we shouldn't set any defaults in the package, because they will inevitably be wrong.

Completely agree on this. But the main problem on this is probably that the .htaccess is overwritten on each update so user configured values are also overwritten.

**Comment by oparoz** [comment]
I think the defaults should be sane, for most home users.
The solution for sysadmins is to disable htaccess and put everything in their vhost and ini directives (based on doc provided by oC). It's both safer and faster.

**Comment by Xenopathic** [comment]
@oparoz So what would you consider a 'sane' `memory_limit` as a default? There is no way we can predict what kind of machine oC will be running on or how much throughput it will get. The same applies for the upload limit parameters, when they haven't been set in the UI yet.

**Comment by oparoz** [comment]
@Xenopathic - Maybe oC could ship with some profiles, S, M, L, but there is no way around manually setting those limits, either via the admin settings or by editing the files themselves. What's needed is top notch documentation.

**Comment by Xenopathic** [comment]
@oparoz We know from experience that admins often don't look at documentation :laughing: Besides, the idea of defaults is that they are unintrusive and work in all but the most esoteric circumstances, which unfortunately the keys such as `memory_limit` and the upload limit parameters are not. I see no way around this other than removing those keys from the default configuration, and only writing the upload limit if the admin changes the setting from the admin settings in oC (which is protected by read/write checks so will be greyed out if we cannot write to the required files). That way the admin's system-wide settings will work out of the box, which IMHO is the expected behaviour of any well-behaved web application.

**Comment by oparoz** [comment]
The problem is that ownCloud is not a regular web app. It's OK for a web app to have 30 seconds timeouts, 128MB memory limits and a 64MB upload limit, but that wouldn't work for ownCloud, so not setting those defaults could increase the number of support requests in the forums, don't you think?

**Comment by Xenopathic** [comment]
The point that I'm trying to make is, no matter what defaults we set for certain parameters, they *will* be wrong for the majority of cases. The defaults ownCloud should use for those parameters are the ones set at a system level in `php.ini`. If the admin wants to change the upload limit, they can do so through the web interface, at which point `.htaccess` and `.user.ini` will be updated with the relevant values. If the admin wants to change the memory limit, then that's something that should be handled at the system level (and not overridden to 512MB no matter what `php.ini` says!)

**Comment by oparoz** [comment]
We need more people's opinion :) @DeepDiver1975 @PVince81 @LukasReschke

**Comment by RealRancor** [comment]
With the current behavior we havn't that much complains at the forums. Only the .user.ini wasn't that known.

**Comment by carlaschroder** [comment]
Ted and Carol use Nginx. Now what? :)

IMO this is a documentation issue. If it's not coming up in the forums a lot, then a minor doc issue. It's already on my todo list to clean up the existing pages because they need improvement. It's a low priority at the moment, so PRs are welcome. (Anyone can report problems, my adoration goes to those who help fix them <g>)

**Comment by RealRancor** [comment]
> Ted and Carol use Nginx. Now what? :)

They are using the .user.ini which is also written after https://github.com/owncloud/core/issues/17182 was merged.

**Comment by Xenopathic** [comment]
I must admit, my experience of this was through `.user.ini` (I use nginx + PHP-FPM), but I hadn't heard of `.user.ini` before now, so perhaps it's skewing my perception. I was just annoyed that the packaged defaults are wrong, and I can't see them being correct for a lot of use cases.

**Comment by carlaschroder** [comment]
@Xenopathic PHP annoys me a lot :) Way too many ways to do things.  I see your point- sane defaults are good, though difficult to choose.
