### ISSUE TITLE
Shared folder no access when ldap server is down

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/core#17170]
Steps to reproduce
1. I have an LDAP server, with some user
2. Entered with the user1 in Oc server (with Ldap)
3. The user 1 create a new folder, call "New folder for share"
4. Go to the folder "New folder for share", and download some files
5. Share this folder with other user (user2) with Ldap
6.throw down the Ldap server

### Expected behaviour
You can go into the Folder

### Actual behaviour
I have two errors:
1. If you go to the user1, and click in the "New folder for share", the name of the folder doubles and does nothing

![screen shot 2015-06-25 at 11 40 07](https://cloud.githubusercontent.com/assets/12032058/8354403/27bfa588-1b48-11e5-98ac-250a9120a193.png)

2. And appears the error 500 
![screen shot 2015-06-25 at 11 44 53](https://cloud.githubusercontent.com/assets/12032058/8354387/08079b1a-1b48-11e5-9634-2972ee728b0f.png)

### Server configuration

DESKTOP v ownCloud-1.8.3.2465-nightly20150625.pkg
Server v {"installed":true,"maintenance":false,"version":"8.1.0.7","versionstring":"8.1 RC1","edition":"Enterprise"}

**Comment by DeepDiver1975** [comment]
> Expected behaviour
> 
> You can go into the Folder

This expectation is wrong - as soon as a critical system component is not available we have to degrade into an exceptional state and basically stop further operations.

LDAP is such a critical system component.

**Comment by DeepDiver1975** [comment]
The correct expectation would be to get an error page displayed.

**Comment by DeepDiver1975** [comment]
@th3fallen  @blizzz @schiesbn @nickvergessen anybody of you with some spare time to look into this?

This is of the same kind as https://github.com/owncloud/core/pull/17048

**Comment by nickvergessen** [comment]
Sounds like https://github.com/owncloud/core/pull/17110 ?!

**Comment by DeepDiver1975** [comment]
@Dianafg76 can you please retest this with current gt master branch? THX

**Comment by Dianafg76** [comment]
@DeepDiver1975 OK

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 OK

THX

**Comment by Dianafg76** [comment]
@DeepDiver1975 Good morning. I tested with Server v (daily master {"installed":true,"maintenance":false,"version":"8.1.0.7","versionstring":"8.1 RC1","edition":""} and the Desktop v 1.8.3 (2472 build) and happend the same

**Comment by DeepDiver1975** [comment]
Thanks @Dianafg76 for retest.



> @th3fallen @blizzz @schiesbn @nickvergessen anybody of you with some spare time to look into this?
> 
> This is of the same kind as #17048

@th3fallen can you have a look at this? - THX

**Comment by nickvergessen** [comment]
@Dianafg76 if you are in the shared file before you kill LDAP, then kill it and then press F5 (to refresh the page) what does happen?

**Comment by Dianafg76** [comment]
@nickvergessen I kill the server LDAP and then press F5, is this happening:

![screen shot 2015-06-29 at 09 28 11](https://cloud.githubusercontent.com/assets/12032058/8403034/74b87d28-1e41-11e5-9ca4-e80a13b15846.png)


![screen shot 2015-06-29 at 09 28 30](https://cloud.githubusercontent.com/assets/12032058/8403037/7a732fd8-1e41-11e5-8085-0ac357aa22c7.png)

**Comment by Dianafg76** [comment]
related in the issue #2516
it is not working
