### ISSUE TITLE
RHDS ldap paged search, incomplete data results or 0 users

### ISSUE THREAD

**Issue by AndreFelipeMachado** [owncloud/core#17173]
RHDS ldap paged search, incomplete data results or 0 users

Hello,
We have been struggling with a kind of incompatibility between owncloud 8.0.4 and RHDS 9.1 on RHEL regarding paged searches.

Some searchs are interpreted by owncloud as incomplete number of results or even zero results, even when we know there are users corresponding to the filters.

After some digging into code we discovered that Owncloud counts results of paged searches until it finds a zero content page.

AFAIK, this does not follow RFC 2696 for reliably knowing when the result finished, as the only reliable control is an empty cookie (rhds distorts this by returning "0").

Some valid ldap queries return the first pages with no data (only comments) but valid cookie, followed by pages with data, maybe even other no data pages, more data pages, etc, until return of an empty null cookie.
This is a valid behaviour of a ldap server, as per rfc 2696.

By reading also https://github.com/owncloud/core/blob/master/apps/user_ldap/lib/access.php at the private function count($filter, $base, $attr = null, $limit = null, $offset = null, $skipHandling = false) implementation it seems that control is done only by data content until zero on a page , not by cookie.

Did we wrongly understand the rfc 2696 and or the code?
https://www.ietf.org/rfc/rfc2696.txt

What If we disable paged searches, may it overload servers?

Regards.
Andre Felipe

### Steps to reproduce
1. RHDS 9.1
2. Tens of thousands users in each LDAP branch from a common root.
3. Try to configure LDAP filter wizard up to the common root.

### Expected behaviour
The LDAP filter wizard should display sum of all users on server common root.
The users of different branches should be able to login

### Actual behaviour
The LDAP filter wizard display zero users, despite filter being triple checked on command line.
But configuring filter to only a branch gives expected results.

### Server configuration
**Operating system**:
Debian GNU/Linux 7.x running on VmWare 5.5

**Web server:**
Apache 2.2.22

**Database:**
Postgresql 9.4.1 backported and packaged for Debian 7.x

**PHP version:**
5.4.41

**ownCloud version:** (see ownCloud admin page)
8.0.4 (stable)

**Updated from an older ownCloud or fresh install:**
8.0.2

**List of activated apps:**
LDAP, Federated cloud sharing, mail templates, cron, sharing, security, email server, log.

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'our_instance_id',
  'passwordsalt' => 'our_salt',
  'secret' => 'our_SECRET',
  'enable_avatars' => false,
  'trusted_domains' => 
  array (
    0 => '127.0.0.1',
    1 => 'our_domain',
  ),
  'datadirectory' => '/opt/data/p_07275_our_name',
  'overwrite.cli.url' => 'our_url',
  'dbtype' => 'pgsql',
  'version' => '8.0.4.2',
  'dbname' => 'dbp_07275_our_name',
  'dbhost' => 'our_db_server_ip:our_db_server_port',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owner_our_name_p',
  'dbpassword' => 'our_db_password',
  'installed' => true,
  'overwriteprotocol' => 'https',
  'loglevel' => 2,
  'logfile' => '/var/log/owncloud.log',
  'asset-pipeline.enabled' => false,
  'logtimezone' => 'America/Sao_Paulo',
  'log_query' => true,
  'ldapIgnoreNamingRules' => false,
  'ldapUserCleanupInterval' => 0,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'our_name',
  'mail_domain' => 'our_domain',
  'mail_smtphost' => 'our_smtp_relay',
  'mail_smtpport' => '25',
  'has_internet_connection' => false,
  'trashbin_retention_obligation' => 30,
  'trashbin_auto_expire' => true,
  'activity_expire_days' => 30,
  'check_for_working_htaccess' => true,
  'enable_previews' => false,
  'theme' => 'our_theme',
  'serpro.admingroup' => 'our_admin_group',
  'serpro.ldapserver' => 'our_ldap_server',
  'serpro.ldapport' => 389,
  'serpro.ldapuser' => 'cn=our_user,ou=our_ou,ou=corp,dc=our_dc,dc=gov,dc=br',
  'serpro.basedn' => 'dc=gov,dc=br',
  'maintenance' => false,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
Using NFSv4 storage mounted on local point and mapped by "our_directory_attribute" user attribute.

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP

#### LDAP configuration (delete this part if not used)

   appid   |              configkey               |                                        configvalue                                         
-----------+--------------------------------------+--------------------------------------------------------------------------------------------
 user_ldap | cleanUpJobOffset                     | 0
 user_ldap | installed_version                    | 0.5.0
 user_ldap | types                                | authentication
 user_ldap | enabled                              | yes
 user_ldap | s01ldap_tls                          | 0
 user_ldap | s01ldap_host                         | our_ldap_server
 user_ldap | s01ldap_dn                           | uid=our_user,ou=our_ou,ou=corp,dc=our_dc,dc=gov,dc=br
 user_ldap | s01ldap_agent_password               | our_ldap_agent_password
 user_ldap | s01ldap_userfilter_objectclass       | inetOrgPerson
 user_ldap | s01ldap_email_attr                   | mail
 user_ldap | s01ldap_user_filter_mode             | 1
 user_ldap | s01has_memberof_filter_support       | 
 user_ldap | s01ldap_group_filter_mode            | 1
 user_ldap | s01ldap_login_filter_mode            | 1
 user_ldap | s01ldap_experienced_admin            | 1
 user_ldap | s01ldap_userlist_filter              | (&(objectclass=our_object)(objectClass=person)(phpgwAccountType=u)(phpgwAccountStatus=A))
 user_ldap | s01ldap_login_filter                 | (&(objectclass=our_object)(mail=%uid)(phpgwAccountType=u)(phpgwAccountStatus=A))
 user_ldap | s01ldap_group_filter                 | (&(objectclass=our_object)(objectClass=posixGroup))
 user_ldap | s01ldap_configuration_active         | 1
 user_ldap | s01ldap_display_name                 | cn
 user_ldap | s01ldap_quota_attr                   | our_quota_attr
 user_ldap | s01ldap_quota_def                    | 1000000000
 user_ldap | s01ldap_override_main_server         | 0
 user_ldap | s01ldap_attributes_for_user_search   | mail                                                                                      +
           |                                      | sn                                                                                        +
           |                                      | givenName
 user_ldap | s01home_folder_naming_rule           | attr:our_directory_attribute
 user_ldap | s01ldap_port                         | 389
 user_ldap | s01ldap_backup_host                  | 
 user_ldap | s01ldap_backup_port                  | 
 user_ldap | s01ldap_nocase                       | 0
 user_ldap | s01ldap_turn_off_cert_check          | 0
 user_ldap | s01ldap_userfilter_groups            | 
 user_ldap | s01ldap_groupfilter_objectclass      | 
 user_ldap | s01ldap_groupfilter_groups           | 
 user_ldap | s01ldap_group_display_name           | cn
 user_ldap | s01ldap_group_member_assoc_attribute | uniqueMember
 user_ldap | s01ldap_loginfilter_email            | 0
 user_ldap | s01ldap_loginfilter_username         | 1
 user_ldap | s01ldap_loginfilter_attributes       | 
 user_ldap | s01ldap_attributes_for_group_search  | 
 user_ldap | s01ldap_expert_username_attr         | 
 user_ldap | s01ldap_expert_uuid_user_attr        | 
 user_ldap | s01ldap_cache_ttl                    | 600
 user_ldap | s01ldap_expert_uuid_group_attr       | 
 user_ldap | s01last_jpegPhoto_lookup             | 0
 user_ldap | s01ldap_nested_groups                | 0
 user_ldap | s01ldap_paging_size                  | 500
 user_ldap | s01ldap_base                         | dc=our_dc,dc=gov,dc=br
 user_ldap | s01ldap_base_groups                  | dc=our_dc,dc=gov,dc=br
 user_ldap | s01ldap_base_users                   | dc=our_dc,dc=gov,dc=br
(49 registros)

### Client configuration
**Browser:**
Mostly Firefox 24.8.0 ESR, IE  and Gogle Chrome

**Operating system:**
Ubuntu Linux 12.04 and Windows 7

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by DeepDiver1975** [comment]
@blizzz anything we can do to support this user? THX

**Comment by blizzz** [comment]
@AndreFelipeMachado Possibly fixed with https://github.com/owncloud/core/pull/14875. Please update to 8.0.4 and retry.

**Comment by AndreFelipeMachado** [comment]
Hello,
Thanks for your answer.
But unfortunately, these are not exactly the same problem cause.
We already updated to 8.0.4 before posting issue.
The unsuitable code logic of controlling by empty data content instead of empty ldap cookie as per rfc 2696 is still there at access.php even at github head.
Please, take a look at "count" function at access.php.
The concept  may impact other parts of code, as users are blocked from login.
Regards.
Andre Felipe

**Comment by blizzz** [comment]
>  We already updated to 8.0.4 before posting issue.

Sorry, my bad, I read the wrong version number.

> The unsuitable code logic of controlling by empty data content instead of empty ldap cookie as per rfc 2696 is still there at access.php even at github head.
Please, take a look at "count" function at access.php.

If you have the doubtful line already found, can you just point me on it, please? By browsing it I don't see anywhere where we cancel based on empty results returned. Also, I don't have an RHDS to test against.

**Comment by AndreFelipeMachado** [comment]
Hello,
Thanks for your answer
We are suspecting of entire concept of function count (line 809 on github repository)
https://github.com/owncloud/core/blob/master/apps/user_ldap/lib/access.php#L809
that uses another funcion countEntriesInSearchResults
https://github.com/owncloud/core/blob/master/apps/user_ldap/lib/access.php#L847
that control flow by data content instead of using empty cookie as per rfc 2696.
Please, take a look at them.
Regards.
André Felipe

**Comment by AndreFelipeMachado** [comment]
Hello
I hope an example could help to understand the RHDS output.
Even the estimate is not mandatory nor cast in stone, only an estimate.
See the first pages with no data.


root@oc-server-1:~# ldapsearch -x -LLL -h our_ldap_server -D uid=our_uid,ou=our_ou,ou=corp,dc=gov,dc=br -w "our_passwd" -b dc=gov,dc=br "(&(objectclass=our_object)(objectClass=person)(phpgwAccountType=u)(phpgwAccountStatus=A))" mail -E pr=2
# pagedresults: cookie=MA==
Press [size] Enter for the next {2|size} entries.

# pagedresults: cookie=MA==
Press [size] Enter for the next {2|size} entries.

dn: uid=our_user_uid1,ou=gna,ou=regbsa,ou=our_domain_level3,dc=our_domain_level2,dc=gov,dc=br
mail: mary.jane@our_domain_level3.gov.br

dn: uid=our_user_uid2,ou=arq,ou=regspo,ou=our_domain_level3,dc=our_domain_level2,dc=gov,dc=br
mail: john.doe@our_domain_level3.gov.br

# pagedresults: estimate=916 cookie=MA==
Press [size] Enter for the next {2|size} entries.

dn: uid=our_user_uid3,ou=arq,ou=regspo,ou=our_domain_level3,dc=our_domain_level2,dc=gov,dc=br
mail: mary.jane2@our_domain_level3.gov.br

dn: uid=our_user_uid4,ou=gna,ou=regbsa,ou=our_domain_level3,dc=our_domain_level2,dc=gov,dc=br
mail: john.doe2@our_domain_level3.gov.br

# pagedresults: estimate=914 cookie=MA==
Press [size] Enter for the next {2|size} entries.

**Comment by AndreFelipeMachado** [comment]
Hello
Did you confirm the Owncloud non compliant behaviour against RFC 2696?
Regards.
Andre Felipe

**Comment by blizzz** [comment]
Not yet, sorry.

**Comment by esakol** [comment]
Hi,
We have developed a workaround for this problem over v8.0.6. How can I submit it to further discuss the issue?

**Comment by blizzz** [comment]
@esakol good news! You can open a pull request ([Github Help](https://help.github.com/articles/using-pull-requests/)), which is basically a request to merge your git branch into (in this case) stable8. Usually the workflow is to have the pull request against master and backport it afterwards to the affected stable branches (here stable8.1 and stable8).
