### ISSUE TITLE
Can create multiple shares of the same file with the same remote user

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#17183]
### Steps to reproduce

1. Install 8.1 on two servers
2. create users on both severs
3. share a file from server 1 with a user on server 2 multple times

### Expected behaviour

Message indicating that file is already shared.

### Actual behaviour

The share is created multiple times

![p366](https://cloud.githubusercontent.com/assets/8480343/8363117/efef0088-1b4a-11e5-8191-b9934b7e8619.PNG)

I was validating the fix to #13765 and don't know if this is the expected behavior.  This behaves the same in both 8.1 and 8.0.5

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration:

ownCloud Enterprise Edition 8.1 RC1 (daily) Build:2015-06-25T03:10:29+00:00 58439c337c2e242c199f153d0529e0b0b482f03a

@cmonteroluque @DeepDiver1975 @nickvergessen

**Comment by nickvergessen** [comment]
Nothing crucial => 8.2?

**Comment by jnfrmarks** [comment]
I agree that this is nothing crucial except that we're providing a fix in 8.0.5 around this and I feel like we're trading one bug for another.

**Comment by jnfrmarks** [comment]
One more comment:

For ever share created, a share is created for the remote user.  So, in the example above, when user abagail_runolfsdottir logs in, she sees three shares for the same file

![p367](https://cloud.githubusercontent.com/assets/8480343/8364612/80f1cb10-1b55-11e5-9e8a-233053bd88a9.PNG)

**Comment by nickvergessen** [comment]
Well the previous bug blocked anyone from sharing a file with the same name with you. Thats worse than being able to "molest" people with sharing the same folder. Also the first bug was a problem on the remote instance. This one now is a problem on the local instance... i think it might be easy to resolve, so we might be able to backport this in the end, if we think its necessary.

**Comment by rullzer** [comment]
Start of a fix in #17195

**Comment by rullzer** [comment]
Should be fixed with #17195.
