### ISSUE TITLE
  Split Users page to page view

### ISSUE THREAD

**Issue by wesleyhuang** [owncloud/core#1718]
We have more than 2000 users in our OC beta site with AD backend. It may be more if it comes to production. Current Users page is extremely a troublesome for us to manage users/group. It take a long long time to load the users and the search function isn't working.  In most case, the Users page cannot fully load all the users.  This limits us to group the users etc.  It would be great if OC can customize this page to a more work-able page view?

**Comment by jancborchardt** [comment]
This has been fixed some time ago already:

* there’s lazy loading for the users
* groups can be viewed separately
* filtering works nicely
