### ISSUE TITLE
Feature Request: Additional auth methods for external user support

### ISSUE THREAD

**Issue by alve89** [owncloud/core#17184]
I think it was great to offer a simple REST auth method: Call a RESTful API URL, get true or false if authentication is successful or not. Was that possible? I think this should be implementable quite simple.
That's almost better than an extra LDAP, WebDAV, ... authentication, because everyone could it implement on his server as he wants and just needs to output a boolean value.

**Comment by karlitschek** [comment]
This is exactly what user_webdavauth does. Expect it works on the http return code instead.

**Comment by alve89** [comment]
I already tried to setup this but didn't get it working:

Which HTTP method is used? I tried to debug it but didn't get any information of what was sent to my server. 

Which variable-keys are used within this method?

An additional secret to access this REST API was quite nice to prevent misusing.
