### ISSUE TITLE
Share Thumbnails for shared files

### ISSUE THREAD

**Issue by symphoniker** [owncloud/core#17186]
### Steps to reproduce
1. user1: create a folder with an image in it
2. share this folder with user2
3. open this folder as user1 and user2 in the gallery app
### Expected behaviour

the thumbnail creation for the image should be done once. (Store thumbnails in the thumbnails folder of the original file owner or a thumbnail folder for all users (based on fileid))
### Actual behaviour

thumbnails are created in the folder /data/user1/thumbnails and /data/user2/thumbnails

This seems to be related to the core as the thumbnail creation for the gallery app happens in core. On slower setups this is quite an issue for me, as thumbnail creation for many files takes quite long.

**Comment by oparoz** [comment]
This can't happen for the following reason:

1. User1 gives read-only access to his share
2. User2 wants thumbnail for file 1234
3. Thumbnail folder of user1 doesn't contain a thumbnail for 1234
4. User2 can't generate a new thumbnail on User1's space.

@georgehrke for possibly more ideas

**Comment by oparoz** [comment]
One thing we could do is perhaps copy thumbnails over the first time the user connects to the share...

**Comment by georgehrke** [comment]
There are a few other issues I see here:
1. there hasn't been a decision yet, whether we want to encrypt previews in the future
2. if we decide against 1, it would probably make sense to move the thumbnails folder out of the user directory and put in directly into data/, because the file ids are unique for all users

**Comment by oparoz** [comment]
Good point. Since I'm in favour of encrypting thumbnails, since it's leaking private data, I think 2) is the solution and this request should be denied.

**Comment by vbouchet31** [comment]
Hi guys,
I'm not sure to understand why these thumbnails can't be shared even if the user only has read-only access, or if thumbnails are encrypted.
Even if the user has read-only access, the thumbnail should remain the same so the system can generate the thumbnail and share it across users who can access it (from my point of view, read-only is only in terms of feature, the user can't update the picture, etc)

It is also an issue for me as I have directories with thousands of pictures and it's killing my raspberry even if someone has already visited this gallery before. (Related ticket: https://github.com/owncloud/gallery/issues/163)

**Comment by symphoniker** [comment]
I don't know exactly how the encryption in owncloud works. But let me made a guess, I never used it and I do not have an installation for testing at the moment:

user1 has folder1 encrypted (of course with his public key)
user1 shares this folder with user2
         ---> owncloud decrypts folder1 with user1's private key
         ---> owncloud encrypts folder1 with user2's public key
         ---> owncloud stores folder1 for user2 in the data directory of user2

this leeds me for 2 things.

1. Thumbnails should be generated where the physical file is stored. 
    - For non encrypted files this is always the data folder of the original owner
    - For encrypted files this would be the data folder of the user accessing the data

2. If encryption works as described above, this would proove that user1 could write to the data directory of user2 without user2 has given him any write permissions for his data folder in general

    - Beside this, it is not clear why write access should be restricted to a users data/thumbnail folder as this is all managed by the core. Of course read access should be restricted based on actual permissions.
    - If this really is a problem I could also imagine of using a file structure outside the data folder like
      /cache/thumbnail/user/ which would make it as well possible to store the thums for the user that hosts the physical version of the file


Of course file locking will be an issue to consider when more than one user creates thumbnails in the same place.

I don't know how linked shares are handled in owncloud but if there are also thumbnails created for them we should also think about this.


In any case I would love to see a possiblity to let a cron worker do the job of thumbnail generation for all unencrypted files. (In this case the on demand feature needs to be possible as well [in case a file is accessed before the cron did it's job], so we don't need any special treatment for encrypted files. Just ignore them in the cron)

**Comment by schiesbn** [comment]
> user1 has folder1 encrypted (of course with his public key)

correct.

> user1 shares this folder with user2
> ---> owncloud decrypts folder1 with user1's private key
> ---> owncloud encrypts folder1 with user2's public key

correct.

> ---> owncloud stores folder1 for user2 in the data directory of user2

wrong.we don't copy the folder to user2. The folder stays in the owners data directory. If user1 access the file we decrypt it with user1s private key, if user2 access the file we decrypt it with user2s private key.

**Comment by symphoniker** [comment]
Thx for correcting me and for your input. 
Option 3 sounds good to me.

**Comment by georgehrke** [comment]
@karlitschek @MTRichards @DeepDiver1975 @PVince81 Would it be possible to have a decision about encrypting previews for 9.0? :)

**Comment by karlitschek** [comment]
hmmm. encrypting previews sounds like a can of worms that I really would try to avoid. If people consider previews security leaks and want to use encryption then I suggest to disable them in the config file. 
Also funny that this discussion came out of a request to improve the performance. encrypting them would definitely makes things significantly slower. :-) 
So I option 3 would be good to have. But I'm not really sure if this is something that is super high on the list of things to do. imho.

**Comment by PVince81** [comment]
closing in favor of https://github.com/owncloud/core/issues/28939
