### ISSUE TITLE
Sharing file with group and then deleting it does not delete the file for group recipients

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#17188]
### Config
* Encryption enabled
* Local sharing
* **NO** locking

### Steps to reproduce

1. user1 creates a file (size=9,8K)
2. user1 shares file to group1 (which is only user2)
3. user2 modifies the file (size=9,9K)
     + Remember smashbox uploads via WebDav using part files
4. user1 verifies the modified file (size=22K)
5. user1 deletes the file
6. user2 checks if the file is deleted => :boom: 
    + file is retained as conflict file, since it was not the deleted file I guess
    + file is owned by user2 and not marked as shared by user1

or

```
bin/smash lib/oc-tests/test_shareGroup.py -a
```

Breaking commit is 95602d4069a1eb9a45e1d08edeecc0d5b90e01ca from #17045 

Will try to find out if I can fix it similar to #16803 but since we are close to lock down, calling @schiesbn for the rescue as well.

@DeepDiver1975 this is the failing smashbox test on jenkins +enc -locking

**Comment by schiesbn** [comment]
I tried to reproduce it with the steps you described but I can't reproduce it. After user1 delete the file it is no longer visible for user2 and user3. Also if I call file_exists() as user3 for the previous mount point I get "false" without any error. Further I set a break point on all the lines I changed in #17045, this code is never called after the file was deleted.

**Comment by schiesbn** [comment]
If I try to call file_get_contents() on the no longer visible file for user3 I reach https://github.com/owncloud/core/commit/95602d4069a1eb9a45e1d08edeecc0d5b90e01ca#diff-a36b9c0307e0126dd50baa38fb4bb74aL606 but it went through the method without any error. At the end we don't have a encryption module, assume that the file is not encrypted and hand the call over to the parent storage (skipping all the encryption parts). The result of the file_get_contents() call will be false.

**Comment by nickvergessen** [comment]
Okay, after some debugging it seems that part files are involved again. I stripped out some information which seems to be relevant now, let me update the initial steps

**Comment by nickvergessen** [comment]
Okay, I'm sorry I mixed up two file names. This is what happens, the file is being modified and thereby creates a different file:

### Steps to reproduce

1. user1 creates a file (size=9,8K)
2. user1 shares file to group1 (which is only user2)
3. user2 modifies the file (size=9,9K)
     + Remember smashbox uploads via WebDav using part files
4. user1 verifies the modified file (size=22K)
5. user1 deletes the file
6. user2 checks if the file is deleted => :boom: 
    + file is retained as conflict file, I guess, since it was not the deleted file 
    + file is owned by user2 and not marked as shared by user1

**Comment by nickvergessen** [comment]
I fixed the test and sent a PR to cern, to make sure the test now fails at step4, because the file user1 downloads is not the file user2 uploaded: https://github.com/cernbox/smashbox/pull/34
