### ISSUE TITLE
Missing OCP replacement for \OC_Util::tearDownFS()

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#17197]
According to the way the path to the files a token gives access to in files_sharing, we need to use this method before requesting access to a node
https://github.com/owncloud/core/blob/446f628136532fe556757c3fe39655c6304e3cb9/apps/files_sharing/lib/controllers/sharecontroller.php

```
OC_Util::tearDownFS();
OC_Util::setupFS($userId);
Filesystem::getPath($nodeId)
```

`Filesystem::getPath($nodeId)` can be replaced with `$this->userFolder->getById($nodeId)`
but can both the preceding methods be replaced by `$this->userFolder = $server->getUserFolder($userId)` ?

_I have no idea where it should sit (OCP or AppFramework), but it's either missing or not required and new OCP methods or new documentation needs to be provided_

**Comment by Raydiation** [comment]
You should not have to call these methods at all, if you get the filesystem from the container, everything should be set up

**Comment by Raydiation** [comment]
Usecase?

**Comment by oparoz** [comment]
Use case: settting up the filesystem when given a token
https://github.com/owncloud/core/blob/446f628136532fe556757c3fe39655c6304e3cb9/apps/files_sharing/lib/controllers/sharecontroller.php

The container is not yet capable of doing that https://github.com/owncloud/core/issues/17151

**Comment by Raydiation** [comment]
Well, write a function that returns a user id based on a token and then use getUserFolder no need at all to use tearDown and setupFs

**Comment by oparoz** [comment]
Well, through all the refactoring, I ended up using both in the same setup method. First tearDown+setupFS, then getUserFolder, thinking the first step was a requirement.

I've just tested without those OC methods and I was able to access the encrypted files, even in a different tab. I'm testing more scenarios and hopefully you're right and I'll be able to get rid of those 2 methods!

**Comment by oparoz** [comment]
Maybe @icewind1991 could explain why he's using setupFs here before calling getUserFolder?: 
https://github.com/owncloud/core/blob/master/lib/private/command/fileaccess.php

It could well be that it isn't required at a higher level because the FS is already there.

**Comment by oparoz** [comment]
Looking at what's in getUserFolder, it seems that setupFS is indeed redundant.
`\OC\Files\Filesystem::initMountPoints($userId);` - > `self::mount($homeStorage['class'], $homeStorage['arguments'], $user);` -> `\OC_Util::setupFS();`

So maybe a technical debt.

**Comment by oparoz** [comment]
This ticket is about `tearDownFS` and I have no idea when it needs to be used.

**Comment by PVince81** [comment]
Apps should not call `tearDownFS()`, this should happen automatically.

In the usual case, the tear down is never called within a single PHP request as everything gets detroyed anyway once the PHP request finished.

As for background jobs, `tearDownFS()` is called between every bkg job.
