### ISSUE TITLE
Wrong signature in OCA\Files_Sharing\External\Scanner

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#17194]
OCA\Files_Sharing\External\Scanner
`public function scan($path, $recursive = self::SCAN_RECURSIVE, $reuse = -1)`

extends OC\Files\Cache\Scanner
`public function scan($path, $recursive = self::SCAN_RECURSIVE, $reuse = -1, $lock = true)`

@PVince81

**Comment by PVince81** [comment]
or @icewind1991 

@oparoz mind sending a PR ? Just add "$lock = true" in all the scan() signatures where it's missing.
Thanks.

**Comment by oparoz** [comment]
I just named you because you were working on locking recently :).

I'll do the PR.

**Comment by oparoz** [comment]
https://github.com/owncloud/core/pull/17202

**Comment by nickvergessen** [comment]
Merged the branch, @oparoz you failed to use the magic words, see:
https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues

**Comment by oparoz** [comment]
Yep, I forget sometimes... :older_man:
