### ISSUE TITLE
Missing OCP replacement for \OC_Util::setupFS()

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#17196]
According to the way the path to the files a token gives access to in files_sharing, we need to use this method before requesting access to a node
https://github.com/owncloud/core/blob/446f628136532fe556757c3fe39655c6304e3cb9/apps/files_sharing/lib/controllers/sharecontroller.php

```
OC_Util::tearDownFS();
OC_Util::setupFS($userId);
Filesystem::getPath($nodeId)
```

`Filesystem::getPath($nodeId)` can be replaced with `$this->userFolder->getById($nodeId)`
but can both the preceding methods be replaced by `$this->userFolder = $server->getUserFolder($userId)` ?

_I have no idea where it should sit (OCP or AppFramework), but it's either missing or not required and new OCP methods or new documentation needs to be provided_

**Comment by PVince81** [comment]
Thanks @oparoz 

I believe that @icewind1991 started some refactoring that would make it public somehow.

Ideally the FS stuff should not be static. It should be possible to use the FS from multiple users in parallel by using instances of Filesystem or the Node API.

There is some preliminary work from @icewind1991 here https://github.com/owncloud/core/pull/11091

**Comment by oparoz** [comment]
Looking at what's in `getUserFolder`, it seems that `setupFS` might be redundant.
`\OC\Files\Filesystem::initMountPoints($userId);` - > `self::mount($homeStorage['class'], $homeStorage['arguments'], $user);` -> `\OC_Util::setupFS();`

So maybe this is a technical debt.

**Comment by PVince81** [comment]
Moving to 9.0.

We definitely need some better API for apps to provide public mode

**Comment by oparoz** [comment]
I can just confirm that `$server->getUserFolder($userId)` cannot replace `\OC_Util::setupFS($user);`.

The view is not setup properly. 

### Env
* oC VM with master cloned
* Gallery occ command at this revision: https://github.com/owncloud/gallery/blob/f5f42482a28351e4cda1dd6ec0b6911992411c11/command/createthumbnails.php

### Steps to reproduce
1. Add this corrupt file to a folder named corrupt: https://github.com/owncloud/gallery/blob/master/tests/_data/testimage-corrupt.jpg
2. Use the following occ gallery command: `# sudo -uwww-data ./occ gallery:create-thumbnails --path=/admin/files/corrupt`

### Expected result

> There was a problem generating a preview for /admin/files/corrupt/testimage-corrupt.jpg

### Actual result

> PHP Fatal error:  Call to a member function file_get_contents() on a non-object in /var/www/owncloud/lib/private/files/filesystem.php on line 703

### Notes

If I replace `$server->getUserFolder($userId)` with the private method `\OC_Util::setupFS($user);`, then I don't get the fatal error any more.

**Comment by oparoz** [comment]
Maybe this will help: https://github.com/owncloud/core/pull/19416

**Comment by PVince81** [comment]
Filesystem stuff should be transparent for apps, apps should not need to care about setting up FS and tearing down. So we need to fix those APIs and/or complete them.

From what I see, `initMountPoints` is called already in `getUserFolder()`: https://github.com/owncloud/core/blob/v9.1.2/lib/private/Files/Node/Root.php#L346
