### ISSUE TITLE
Naming a file beginning with a dot, the whole name is shown in the same grey color as the extensions.

### ISSUE THREAD

**Issue by davitol** [owncloud/core#17193]
### Steps to reproduce
1. Create a file naming it with a dot at beginning (e.g.) .filename.txt

### Expected behaviour
The colour should be different from the filename and the extension as it was in previous versions.

### Actual behaviour
The colour is grey for the whole filename

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:**"version":"8.1.0.7","versionstring":"8.1 RC1","edition":"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity: 2.0.0
 - admin_audit: 0.6
 - enterprise_key: 0.1.0
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.4
 - user_shibboleth: 1.0.1.0
 - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

**Comment by LukasReschke** [comment]
> The colour is grey for the whole filename

This is expected. - See https://github.com/owncloud/core/pull/15206
