### ISSUE TITLE
Scrolling as admin through users. Web page jumps to the top all the time.

### ISSUE THREAD

**Issue by Kawohl** [owncloud/core#17209]
### Steps to reproduce
1. Open webinterface of owncloud

2. Go to the Admin page and Scroll through users
3.

### Expected behaviour
Scrolling down with either the mouse or by using the arrow keys. The Content should Display to where you scrolled.

### Actual behaviour
Scrolled down and the content jumped to the top of the page again.

**Web server:**
s3

### Client configuration

**Operating system:**
Mac OSX 10.10.3

**Comment by LukasReschke** [comment]
With s3 you refer to s3.owncloud.con/owncloud/?

**Comment by LukasReschke** [comment]
Also we miss other information such as the browser etc…

**Comment by LukasReschke** [comment]
Also why is s3 on 8.0.2?

**Comment by Kawohl** [comment]
@LukasReschke 
Yes i meant s3 on owncloud.com 

We discovered this when Markus Rex wanted to reshare some stuff to me.

**Comment by PVince81** [comment]
Possible duplicate of https://github.com/owncloud/core/issues/12962

But from what I see, the PR was put in 8.0.0, so not sure why it would still appear in 8.0.2.

I'd still recommend upgrading to 8.0.5.

**Comment by Kawohl** [comment]
is resolved....
