### ISSUE TITLE
No more SabreDAV?

### ISSUE THREAD

**Issue by carlaschroder** [owncloud/core#17205]
I need a clarification, please. The 8.1 Features wiki says:

"The SabreDAV browser at /remote.php/webdav has been removed. Only pure WebDAV access is permitted anylonger."

Does this mean no more SabreDAV, and oC 8.1 uses WebDAV?

**Comment by carlaschroder** [comment]
https://github.com/owncloud/core/wiki/ownCloud-8.1-Features#administrators

**Comment by LukasReschke** [comment]
SabreDAV is our WebDAV server. We just disabled the web interface of it :) - All other things are the same.

**Comment by carlaschroder** [comment]
ok thanks!
