### ISSUE TITLE
logout url redirection to internal URL when using reverse-proxy

### ISSUE THREAD

**Issue by mwellnitz** [owncloud/core#17201]
Hello, First of all: **MANY MANY THANKS for this very good software solution.**

When OwnCloud is used behind a reverse-proxy the logout url redirection is wrong:

in **lib/base.php**
```php
public static function handleRequest() { 
[...]
                                // redirect to webroot and add slash if webroot is empty
                                header("Location: " . OC::$WEBROOT.(empty(OC::$WEBROOT) ? '/' : ''));
```
The redirect is done to the internal server URL and not to the external configured.
everything other is working properly.

If I change the code to
```php
                               header("Location: /oc-context-root/");
or 
                               header("Location: https://external.oc.url/oc-context-root/");
```
everything is fine. (that's my dirty hack  :D )

It seems that ```$WEBROOT``` does not have only the webroot but also the full URL in this context.

This error occures at least since OC 7.X

**Comment by karlitschek** [comment]
This can be configured in the config.php. https://github.com/owncloud/core/blob/master/config/config.sample.php
Please check the overwrite parameters.

**Comment by mwellnitz** [comment]
Hi Frank,
I already set overwritehost and overwriteprotocol and everything works like a charme __except__ of the logout url.
Context root (webroot) is the same in external as well as the internal URL. During the logout process the browser is redirected to ```http://my.internal.domain/context-root/``` instead of  /context-root/``` or ```https://external.domain/context-root/```
Can you please do some invesigation into this?

**Comment by karlitschek** [comment]
Ahh O.K. So maybe this is a real bug :-)
What do you think @DeepDiver1975 @LukasReschke ?

**Comment by LukasReschke** [comment]
Bug? We don't have bugs. **Must** be a feature. Will look into this ;-)

**Comment by LukasReschke** [comment]
@mwellnitz Can you try to set `overwritewebroot` to `oc-context-root`?  (see https://doc.owncloud.org/server/8.1/admin_manual/configuration_server/reverse_proxy_configuration.html?highlight=overwritewebroot#parameters)

**Comment by mwellnitz** [comment]
srange error:
if i set webroot to ```/context-root``` the server can't let me in. with ```/context-root/``` (with aditional slash) I can login.
BUT... after login: with ```/context-root/``` the server gives me an error and with ```/context-root``` it's OK (after reload)
```
Interner Serverfehler

Der Server hat einen internen Fehler und konnte Ihre Anfrage nicht vervollständigen.

Bitte wende Dich an den Serveradministrator, sollte dieser Fehler mehrfach auftreten, und füge Deiner Anfrage die unten stehenden technischen Details bei.

Weitere Details können im Serverprotokoll gefunden werden.
```

**Comment by mwellnitz** [comment]
btw: That's a cool feature ;-)

**Comment by LukasReschke** [comment]
```
Interner Serverfehler

Der Server hat einen internen Fehler und konnte Ihre Anfrage nicht vervollständigen.

Bitte wende Dich an den Serveradministrator, sollte dieser Fehler mehrfach auftreten, und füge Deiner Anfrage die unten stehenden technischen Details bei.

Weitere Details können im Serverprotokoll gefunden werden.
```

Means we need more information which can all be found in our issue template: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md :wink:

**Comment by mwellnitz** [comment]
### Steps to reproduce
see above :-)

### Expected behaviour
Login should work

### Actual behaviour
Error Message ```Interner Serverfehler``` (see above)

### Server configuration
Ubuntu 14.04

apache reverse-proxy, apache

**Database:**
mySQL

**PHP version:**
5.5.9+dfsg-1ubuntu4.9

**ownCloud version:** (see ownCloud admin page)
owncloud-8.0.3.tar.bz2
fresh install 

<?php
$CONFIG = array (
  'instanceid' => 'geheim',
  'passwordsalt' => 'geheimer',
  'secret' => 'am Geheimsten',
  'trusted_domains' => 
  array (
    0 => 'external.domain',
  ),
  'datadirectory' => '/var/www/oc-context-root/data',
  'overwrite.cli.url' => 'https://external.domain/oc-context-root/',
  'dbtype' => 'mysql',
  'version' => '8.0.3.4',
  'dbname' => 'geheim',
  'dbhost' => 'mySQL-Server',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc',
  'dbpassword' => 'oc',
  'installed' => true,
  'overwriteprotocol' => 'https',
  'overwritewebroot' => '/oc-context-root/',
);

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Firefox
**Operating system:**
Ubuntu 14.04

### Logs
#### Web server error log
No Errors are reported

#### ownCloud log (data/owncloud.log)
Insert your ownCloud log here
if i set ```overwritewebroot``` to ```/context-root``` and try to login:
```
{"reqId":"dbbd6beac2eda50451d720a483b62199","remoteAddr":"192.168.XXX.XXX","app":"index","message":"Exception: {\"Message\":\"The requested uri(\\\/oc-context-root\\\/index.php\\\/apps\\\/files\\\/) cannot be processed by the script '\\\/oc-context-root\\\/\\\/index.php')\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/oc-context-root\\\/lib\\\/base.php(782): OC_Request::getRawPathInfo()\\n#1 \\\/var\\\/www\\\/oc-context-root\\\/index.php(36): OC::handleRequest()\\n#2 {main}\",\"File\":\"\\\/var\\\/www\\\/oc-context-root\\\/lib\\\/private\\\/request.php\",\"Line\":297}","level":4,"time":"2015-06-27T20:28:30+00:00"}
```

**Comment by mwellnitz** [comment]
any upgrade?

**Comment by PVince81** [comment]
Information was provided, removing label

**Comment by Schroedingers-Cat** [comment]
While the bug remains unfixed, open the file `/var/www/owncloud/lib/base.php` with a text editor and replace the line `header("Location: " . OC::$WEBROOT.(empty(OC::$WEBROOT) ? '/' : ''));` with `header("Location: " . '/');`.

**Comment by mlino** [comment]
Hi,

I'm facing the same issue on version 6.0.2, but seems that de base.php file is a little bit different from the comment above. I just can't found  `header("Location: " . OC::$WEBROOT.(empty(OC::$WEBROOT) ? '/' : ' ')); ` on base.php file

**Comment by ljsjl** [comment]
Another possible workaround is a redirect from ^/owncloud$ to https://your.site.foo/owncloud/ That's what I've had to do with an HAProxy / NginX / PHP-FPM setup. Working so far but I haven't tested it thoroughly.

It seems in this case that always adding a trailing '/' in the logout redirect would have the desired effect for this case, but I don't have a test system setup to see how it would affect the non-proxied case.

**Comment by tbartenstein** [comment]
I may be able to provide more info on this issue.

I have a "server cascade" with NGINX running Owncloud listening on port 8081, Varnish on 8080 and NGINX as SSL terminator on port 443.
In my config, "overwritewebroot" is set to "/owncloud" (without trailing slash).

When I call "https://example.de/owncloud" (without traiing slash), I am redirected to "https://example.de:8081/owncloud/" (with trailing slash), which, as expected, fails due to a closed port.
If I enter the URL including the trailing slash, everything is fine.
Until I'm logging out, that is, as now I'm again redirected to "https://example.de:8081/owncloud/".
When I change the mentioned line in the `base.php` to `header("Location: " . OC::$WEBROOT . '/');`, the logout behaviour is as expected.

Changing the "overwritewebroot" to "/owncloud/" with slash does not change anything.

**Comment by PVince81** [comment]
Is this still happening in 9.0.3 or 9.1.0 RC1 ?
If yes, please reopen.

**Comment by Paulodile** [comment]
I am running owncloud 9.1stable behind a reverse proxy and this logout link problem persists. I haven't changed any overwrite rules yet.

**Comment by NvL-WEAP** [comment]
These lines did the trick for me. My nextcloud is behind a NginX reverse proxy, which listens to HTTPS and forwards the nextcloud through HTTP.

`'overwritecondaddr' => 'https://my.url.ext,
'overwritehost' => 'my.url.ext',`

The last line solved the logout issue(URL), and corrected the webdav URL.

Running version 9.1.0.16

**Comment by patillacode** [comment]
Hi there!

I am running OwnCloud 9.1.2 and the issue persists.
I am also running NGINX redirection
For what I have been able to test, logout is the only redirect that is not working properly.

I fixed the issue in my installation adding `'overwritehost' => 'mydomain.com',` under file `/var/www/owncloud/config/config.php` as @Paulodile and others suggested.

Hope this gives some insight.

**Comment by RealRancor** [comment]
@patillacode Yes, these parameter are needed for various environments / setups. This is documented at the docs:

> The automatic hostname, protocol or webroot detection of ownCloud can fail in certain reverse proxy situations. This configuration allows the automatic detection to be manually overridden.

https://doc.owncloud.org/server/latest/admin_manual/configuration_server/reverse_proxy_configuration.html
