### ISSUE TITLE
Long similar group names in the Users mgmt sidebar can not be distinguished

### ISSUE THREAD

**Issue by pako81** [owncloud/core#17204]
Customer is asking for enhancements in the layout of the group column on the "Users" administration page.

Specifically, they wrote:

Our group naming scheme is so defined that the group names can be quite long and may have the same base (meaning that the first 30 or 40 characters could potentially be the same and only the last 2 characters would differ). In the user administration interface, the left side column indicates how many people belong to each group. However, in our case it is too narrow to allow us to distinguish between similar group names. Besides, since the group name is too long, it overlapses with the number of members, making it unreadable.
Is there a way to allow the administrator to resize this column?

Probably adding a horizontal scroll bar to the group column would solve their issue.

@MorrisJobke /cc @jancborchardt could you please help?

00003421

**Comment by jancborchardt** [comment]
@pako81 do you have examples of their group names?

* the overlapping with member numbers should not happen, that’s a bug
* we better not introduce a resizable column, that will be hell to maintain and break on mobile
* a horizontal scrollbar is ugly and difficult to use – we _could_ do that with some CSS specifically for them but honestly it would be not good and overlap the user count as well.

What we _can_ do and what would solve this problem for others as well is to change the ellipsis to ellipsize the middle of the name instead of the end. For that we would need a library though. cc @owncloud/designers does anyone of you have experience with that?

**Comment by pako81** [comment]
Yes, this is a screenshot from the Customer:

![image001](https://cloud.githubusercontent.com/assets/12248713/8390860/991a2ab6-1ca9-11e5-827c-c0cca265c45e.png)

**Comment by MorrisJobke** [comment]
> Yes, this is a screenshot from the Customer:

The overlapping here is definitely a bug.

**Comment by jancborchardt** [comment]
@pako81 which browser is this? The overlapping starts way earlier usually.

**Comment by pako81** [comment]
They are using Firefox ESR 31.3.0

**Comment by nickvergessen** [comment]
The ellipse should also have a tooltip with the full name?

**Comment by jancborchardt** [comment]
Right. @pako81 would having a tooltip solve the issue for them? It needs to be hovered to show the full name of course but it’s better than not knowing it at all. And it can easily be done.

**Comment by jancborchardt** [comment]
(That would be for every entry though. We can’t really detect if it’s being ellipsized or not except if we introduce some JS for detection – which isn’t really necessary.)

**Comment by pako81** [comment]
@jancborchardt Thanks. I will ask the Customer if having a tooltip would be a feasible solution for them.

**Comment by pako81** [comment]
Customer just replied and they seem to be not very keen with the tooltip workaround. Here below what they wrote:

"While I think it's a good idea, I don't think it will solve the fact that the group names and the number or members overlap, making it unreadable (unless you implement a tooltip on the number of members as well).
You could also swap the group name and number of member, that is put the number of members on the left hand side of the column and the name on the right hand side with a left padding equivalent to the space necessary to show a 3 digit number. You'd be sure the number would be readable. Besides it would make sense since you order them by the descending number of members anyway."

**Comment by nickvergessen** [comment]
Well when we have the tool tipp they of course will not overlap anymore...

**Comment by cdamken** [comment]
@MorrisJobke @jancborchardt @nickvergessen 

How about the full name with line breaks?   that way you can still see the number of uses in that group, and it grows down:

eg:  
I have 3 groups called:
```
primer_grupo_connectado_con_los_mejores_desarrolladores  (30 Users)
los_jefes (3 Users)
segundo_grupo_connectado_con_los_malos_desarrolladores  (80 Users)
```
now  the display could be:
```
primer_grupo_connec\   30
tado_con_los_mejore\
s_desarrolladores  
los_jefes               3
segundo_grupo_conne\   80
ctado_con_los_malos\
_desarrolladores 
```

That way the user can see the whole names immediately and you only have to scroll down.

What do you think about it?

**Comment by jancborchardt** [comment]
@cdamken well, that would make entries with long group names bigger in the sidebar, even though they might not have a bigger importance.

It can easily be achieved though by putting this in the theme CSS:
```
.isgroup .groupname {
  white-space: normal;
}
```

But solving this in core like that is extremely unelegant. So is that custom solution sufficient?

**Comment by cdamken** [comment]
@jancborchardt  Thanks a lot,I MHO, I think that could be the solution/workaround for now. we'll ask if that solves the problem

**Comment by michaelstingl** [comment]
There are several examples which shows tooltip only when text is ellipsed:

- http://docs.telerik.com/kendo-ui/web/tooltip/how-to/show-on-ellipsis
- http://ovaraksin.blogspot.de/2012/12/elegant-truncated-text-with-ellipses-in.html

Some also include hacks for older IE's

**Comment by michaelstingl** [comment]
@pako81 @jancborchardt Overlapping group names with member count is fixed in current master.

This solution from master could be used in theme to fix overlapping:

```
.isgroup .groupname {
	width: 85%;
	display: block;
	overflow: hidden;
	text-overflow: ellipsis;
}
```

**Comment by pako81** [comment]
@michaelstingl thanks! Customer applied the solution from master and confirmed is working. There is no more overlapping with the number of members. At this stage, implementing a tooltip for displaying the full group names would then solve entirely the issue.
Maybe it would be possible to come up with a more elegant solution in the future; this seems to be indeed a sub-optimal workaround (at least for this Customer):

"As for the tooltip, it would be acceptable. However, I have to admit I find it a pity that so much space will be wasted on the right hand side of the screen (for wide screens at least) while the left column would be so cramped. But once again, a tooltip would do."

**Comment by jancborchardt** [comment]
@pako81 as said above, you can add this CSS to make the names wrap multiline in the left sidebar:
```
.isgroup .groupname {
  white-space: normal;
}
```

Changing the width of the sidebar is a bit out of the question since – where does it end? The current width works fine with most apps. Having it wider would make a lot of apps look strange, and then there will always be folks with even longer group names.

**Comment by michaelstingl** [comment]
@jancborchardt please check the group names in @pako81 's Screenshot. They don't use whitespace.

**Comment by jancborchardt** [comment]
Ugh … well. Then we would need to do ellipsizing in the middle, which has to be done via Javascript cc @PVince81 

@DeepDiver1975 should we go for that?

**Comment by jancborchardt** [comment]
@pako81 so I assume the workaround took care of this issue? I would like to close this because we offered custom solutions.

**Comment by pako81** [comment]
Ellipsizing in the middle of the group name and having a tooltip showing the full group name would definitely solve the issue. Would this not be delivered at this stage?
