### ISSUE TITLE
Unable to signin using the external api while a user is already loggedin

### ISSUE THREAD

**Issue by DjazzLab** [owncloud/core#17213]
Hi,

I've followed the documentation to create an external API for my application (ocDownloader) : https://doc.owncloud.org/server/8.0/developer_manual/core/externalapi.html
But I'm facing a weird issue.

1. If no user is loggedin in ownCloud, then everything works fine. I can exec an API declared function from my local computer using https://user:password@yourowncloud.com/ocs/v1.php/apps/yourapp/method
2. If one user is loggedin (even if the user is not the one I use to contact the API), I get the 997 errorcode (unauthorized). So I try to signout all the users from ownCloud, then the API call works fine.

Do you know if there is an issue ? or if I miss something in the application development ?

Thank you for your reply
Best
DjazzLab

**Comment by LukasReschke** [comment]
Please provide cURL examples or dumps of your requests. THX.

Generally speaking: All requests need to have a `OCS-APIREQUEST: true` header if they use an existing session.

**Comment by DjazzLab** [comment]
I do not use cURL but a simple AJAX function, executing a request like https://user:password@yourowncloud.com/ocs/v1.php/apps/yourapp/method

I'll try the `OCS-APIREQUEST: true` in the header

Thanks !

**Comment by DjazzLab** [comment]
Ok `OCS-APIREQUEST: true` in the header seems to works fine even if the session is in use or not.

Thanks.
