### ISSUE TITLE
Public sharing download function

### ISSUE THREAD

**Issue by alve89** [owncloud/core#17218]
I'm despairing - could please someone help me with the file path of the downloading method for the following URL:

https://owncloud.myDomain.com/public.php?service=files&t=.....&download

I think this should be a header() call with some applications contents. So where are the headers for the download defined?

I know this isn't an issue but I don't know where else I could get help. Many thanks in advance!

**Comment by RealRancor** [comment]
Hi,

> but I don't know where else I could get help.

i think either https://mailman.owncloud.org/mailman/listinfo/devel or the irc channel #owncloud-dev on freenode is the better place.

**Comment by LukasReschke** [comment]
https://github.com/owncloud/core/blob/stable7/apps/files_sharing/public.php
https://github.com/owncloud/core/blob/c1bed643a0698d8c5027e4c7dd54d9198e915e72/lib/private/files.php#L59-L161
