### ISSUE TITLE
Raise SabreException for every WebDAV code path

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#17220]
Currently, the WebDAV upload code in the Sabre node catches a few exceptions explicitly then converts them to SabreException. In some cases, exceptions might be missed or thrown as error pages.

See https://github.com/owncloud/core/blob/master/lib/private/connector/sabre/file.php#L146

We should adapt this code and have a single catch-all block that will call a function `convertSabreException()` to rethrow the matching Sabre exception with appropriate details.

This would also make it possible to properly cleanup before rethrowing and avoid repeating code, see https://github.com/owncloud/core/pull/17189

**Comment by PVince81** [comment]
- [x] upload
- [ ] download ?
- [ ] move
- [ ] copy
- [ ] mkdir
- [ ] delete
- [ ] propfind / getChildren

**Comment by cmonteroluque** [comment]
reflecting related severity

**Comment by DeepDiver1975** [comment]
such a major code resturctureing is something I'd prefer to do while working on the unified dav backend -> 9.0

@cmonteroluque @karlitschek agree?

**Comment by karlitschek** [comment]
@DeepDiver1975 Agreed.

**Comment by cmonteroluque** [comment]
@DeepDiver1975 ok

**Comment by PVince81** [comment]
Idea: instead of trying to cover all code paths, try converting the exceptions inside Sabre's "Exception" plugin

**Comment by PVince81** [comment]
Tagging as bug because the move to Webdav made us lose the detail of error messages.

**Comment by PVince81** [comment]
Ah, never mind. I thought it was that other ticket.
