### ISSUE TITLE
AppStore: Improve performance by offering a huge JSON blob / zipped response with all entries

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#17223]
Basically like all distributions do. We can refresh these via a cron job.

> Regarding your caching fun - we should try to mimic linux package managers which have a local cache which is explicitly updated by the user (apt-get update) - any further operation will then use the local cache (apt-get install / apt-get upgrade).
> As a result we require a non-optional cache mechanism - we cannot use memcaches.

Ref https://github.com/owncloud/core/pull/17050#issuecomment-116576786

**Comment by LukasReschke** [comment]
@karlitschek @DeepDiver1975

**Comment by PVince81** [comment]
It could even have an Etag, so further updates would send the old etag and the remote server would only deliver a response when there are changes. :smile:

**Comment by PVince81** [comment]
What to do with this ? Move to 9.1 ?

Note that https://github.com/owncloud/core/issues/17230 would require it

**Comment by LukasReschke** [comment]
IMHO backlog.

**Comment by DeepDiver1975** [comment]
-> market
