### ISSUE TITLE
AppStore: Make updates more prominent with sidebar entry + notification

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#17230]
We should make updates more prominent with a dedicated side bar entry and also a yellow notification such as we have for normal system updates to remind admins. Probably worth doing together with https://github.com/owncloud/core/issues/17223

Updating applications currently requires to go to the apps menu as well as select update which nearly no admin does :speak_no_evil: 
![2015-06-29_14-41-04](https://cloud.githubusercontent.com/assets/878997/8408041/eeb769d8-1e6c-11e5-860c-aa5facb4b9f5.png)

**Comment by LukasReschke** [comment]
@jancborchardt Input?

**Comment by PVince81** [comment]
It should probably be like on Android: have a grouped block at the top containing all the apps that need upgrading. Even more fancy would be to have a section in the sidebar "Apps that have updates".

**Comment by LukasReschke** [comment]
Or we go the Wordpress route which basically is: Update all the stuff automagically. Which is great once we would have code signing :smile:  (Ref https://github.com/owncloud/core/issues/13056)

**Comment by karlitschek** [comment]
Yes. But even more important then code signing we have code that works in all corner-cases ;-)

**Comment by LukasReschke** [comment]
> Yes. But even more important then code signing we have code that works in all corner-cases ;-)

Pffff. A fatal PHP exception a day keeps the sysadmin awake :speak_no_evil: ;-)

**Comment by karlitschek** [comment]
LOL

**Comment by jancborchardt** [comment]
> It should probably be like on Android: have a grouped block at the top containing all the apps that need upgrading.

Exactly what I would have suggested. Just sort the apps which need upgrade up top in the »Enabled« list.

**Comment by LukasReschke** [comment]
> Exactly what I would have suggested. Just sort the apps which need upgrade up top in the »Enabled« list.

Requires us "just" to get https://github.com/owncloud/core/issues/17223 since otherwise the listing of all apps will be really slow :speak_no_evil:

**Comment by RealRancor** [comment]
Ref to an existing issue / feature request for this: https://github.com/owncloud/core/issues/14520

**Comment by jancborchardt** [comment]
Moving to 9.0 and setting severity to high since we want to improve the update process across the board.

**Comment by PVince81** [comment]
Seems https://github.com/owncloud/core/issues/17223 is still open
