### ISSUE TITLE
Lock sharing operations when file is locked

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#17243]
### Steps to reproduce
1. Enable transactional locking
2. Create two users "user1" and "user2"
3. Add the following lines:
```php
					if ($operation === 'unlink') {
						sleep(30);
					}
```
here before this line https://github.com/owncloud/core/blob/b88a0e7080cd5b1844cfb286b06744f3a2fead20/lib/private/files/view.php#L995
(this will delay the delete operation)
4. Create a file "bacon.txt"
5. Start cadaver and delete the file "bacon.txt"
6. During the deletion, in the web UI, share "bacon.txt" with "user2"

### Expected result
File cannot be shared because it is locked by the deletion.

### Actual result
File can still be shared.
If the file disappears during the sharing logic, there might be unpredictable results as the sharing code assumes the file is still there.

### Versions
ownCloud git master (b88a0e7080cd5b1844cfb286b06744f3a2fead20)

@icewind1991 @jnfrmarks @schiesbn

**Comment by PVince81** [comment]
@DeepDiver1975 @cmonteroluque I scheduled to 8.2, I don't think there is time left for this

**Comment by PVince81** [comment]
In general we should look into locking paths when calling Share APIs (whether share, unshare, unshare from self, etc).

**Comment by cmonteroluque** [comment]
https://github.com/owncloud/core/issues/17243#issuecomment-116740894

Nod, moving to 9.0

**Comment by rullzer** [comment]
So what is the behaviour we want here?

* Can we still share if there is a read lock?
* Should we lock if we create/modify a share? (lock exclusive?)
* Should we read lock if we fetch a share?

**Comment by PVince81** [comment]
> Can we still share if there is a read lock?

Yes, as the action of sharing it doesn't affect it.
However the question is what happens if the recipient's parent folder (the folder that will receive the share) currently has an exclusive lock :frowning: 
Maybe that last part should be handled at the time the mount point is created (the one that also resolves naming conflicts), not when the share is created.

>    Should we lock if we create/modify a share? (lock exclusive?)

Not sure. The question is also what to lock, the parent folder ? If creating/modifying a share, it might be enough to set a "shared lock" on the file to prevent people deleting/moving the file while the share is in the process of being created.

>    Should we read lock if we fetch a share?

If with fetching a share you mean getting the contents of the file/folder, we already do that. The shared lock is set on the owner's file/folder.

**Comment by icewind1991** [comment]
I think we only need a read lock when creating a share

**Comment by rullzer** [comment]
So with the share manager this is getting easier. Since we can do proper locking and unlocking in one place now. However I would like to have locking operations on the node level then. Can that be arranged @icewind1991 ?

Anyway not 9.0 I think @PVince81 @cmonteroluque

**Comment by PVince81** [comment]
Problem is: the Webdav code doesn't use the Node API... so locking will not happen if we do it on the Node API level.

However locking is usually done on View level, and the Node API is using the view. Any trouble with this ?

**Comment by PVince81** [comment]
Maybe add locking methods on the Node API ?

**Comment by rullzer** [comment]
@PVince81 I mean basically wrapper methods in OCP for the Node API.. Since I try to use only node stuff in the share manager (we pass those around etc). So yeah we can do it in the view. But just add wrapper stuff to the node API.

**Comment by cmonteroluque** [comment]
@MTRichards

**Comment by MTRichards** [comment]
Any specific question of operation, or just FYI?

**Comment by icewind1991** [comment]
> Problem is: the Webdav code doesn't use the Node API... so locking will not happen if we do it on the Node API level.

> However locking is usually done on View level, and the Node API is using the view. Any trouble with this ?

I'm not sure what you mean with this, it doesn't matter what code path is used to get a lock, it will work properly any which way.

> However I would like to have locking operations on the node level then. Can that be arranged @icewind1991 ?


Would be a simple PR

**Comment by rullzer** [comment]
> Would be a simple PR

@icewind1991 mind creating it ;)?

**Comment by icewind1991** [comment]
Where you go https://github.com/owncloud/core/pull/22812

**Comment by rullzer** [comment]
Ok so after looking into this. I don't think we can do the locking in the manager. We also require the manager for ownership transfers (where we require lazy shares). And locking the node makes it so the node has to resolve to something.

However, I think we can get away here with locking in the OCS Share API. Which is the most logic place anyway. Other parts that want to use the Share Manager have to do their own locking.
