### ISSUE TITLE
Missing icon caret after theming ownCloud

### ISSUE THREAD

**Issue by gig13** [owncloud/core#17248]
### Steps to reproduce
1. Create a new theme
2. Modify the theme by changing images and the defaults.php

### Expected behavior
After modifying the them, the icon caret as seen in the upper left of the page should still be visible.
![icon_caret](https://cloud.githubusercontent.com/assets/4803385/8416549/84f50002-1e74-11e5-8efb-19a29215096d.PNG)

### Actual behaviour
After modifying the theme, the icon caret is not visible like the original theme.
![no_caret](https://cloud.githubusercontent.com/assets/4803385/8416523/5907c61e-1e74-11e5-8d7f-c47c1121eafb.PNG)

### Server configuration
**Operating system**: CentOS 6

**Web server:** apache

**Database:** MySQL

**PHP version:** 5.4

**ownCloud version:**  803

**Updated from an older ownCloud or fresh install:** Updated from an older version

**List of activated apps:** -- N/A

**The content of config/config.php:** -- N/A

**Are you using encryption:** no

### Client configuration
**Browser:** IE Explorer and FireFox

**Operating system:** Windows 7

**Comment by LukasReschke** [comment]
We shall post what we have modified.

**Comment by gig13** [comment]
@LukasReschke 
Yes, uploaded to s3
https://s3.owncloud.com/owncloud/index.php/apps/files?dir=%2FShared%2Fowncloud%2Fsupport%2Fgithub-issues%2Fcore%2F17248

**Comment by LukasReschke** [comment]
We shall take a look at the Chrome developer tools:
![2015-06-29_21-45-52](https://cloud.githubusercontent.com/assets/878997/8416778/42006e4c-1ea8-11e5-9d66-abf5db419eb2.png)

**Comment by LukasReschke** [comment]
Also I'm not quite convinced that this is the actual logo that you want to use :see_no_evil:

**Comment by gig13** [comment]
@LukasReschke 
The theme was missing that actions directory under img .. ok thanks!! Fixed!
