### ISSUE TITLE
Failing smashbox test

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#17247]
### Steps to reproduce

1. Install 8.1 
2. Run smashbox test test_shareDir.py

The test does the following:

1. User 1 creates a local directory and 3 local files in the directory
2. User 1 syncs the directory using owncloudcmd
3. User 1 shares the directory with user 2
4. User 2 syncs, modifies one of the files locally, and then resyncs
5. User 1 resyncs to get the modification
6. Check the log file for errors

### Expected behaviour

Test passes

### Actual behaviour

The file appears to be properly synced but the test fails due to an error in the server log file:

```
{"reqId":"Dvry5c9EOHOUr4J1j2W7","remoteAddr":"172.18.5.144","app":"PHP","message":"filesize(): stat failed fo
r \/var\/www\/html\/owncloud\/data\/user1\/files\/localShareDir\/TEST_FILE_USER_SHARE.dat.ocTransferId1595434
675.part at \/var\/www\/html\/owncloud\/lib\/private\/files\/storage\/local.php#149","level":3,"time":"2015-0
6-29T19:20:38+00:00"}
{"reqId":"Dvry5c9EOHOUr4J1j2W7","remoteAddr":"172.18.5.144","app":"PHP","message":"filesize(): stat failed fo
r \/var\/www\/html\/owncloud\/data\/user1\/files\/localShareDir\/TEST_FILE_USER_SHARE.dat.ocTransferId1595434
675.part at \/var\/www\/html\/owncloud\/lib\/private\/files\/storage\/local.php#149","level":3,"time":"2015-0
6-29T19:20:38+00:00"}
```
This error message was not present last week when testing 1.8.3rc1 with 8.1 and I do not see this error when testing 1.8.3 and 8.0.5

I tried to reproduce this using the webUI and could not.

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration:

ownCloud Enterprise Edition 8.1 RC1 (daily) Build:2015-06-29T03:08:30+00:00 774a38256d718363a7a501f4e6ff42e1a89dab3a

### Client configuration:

owncloudcmd veresion 1.8.3

@DeepDiver1975 @nickvergessen

**Comment by DeepDiver1975** [comment]
test_shareDir passes on 8.1 for us - using b55f71ee032a77105b823ee01653f39fe066977f

**Comment by jnfrmarks** [comment]
Are you testing with 1.8.3?

I will retest with a newer build.

**Comment by DeepDiver1975** [comment]
> Are you testing with 1.8.3?

yes

**Comment by nickvergessen** [comment]
Investigating
