### ISSUE TITLE
Prevent version app operations when file is locked

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#17245]
### Steps to reproduce
1. Enable transactional locking
2. Create a file "test.txt"
3. Edit "test.txt" and save multiple times to create versions
4. A `sleep(30);` here to delay rename operation: https://github.com/owncloud/core/blob/b88a0e7080cd5b1844cfb286b06744f3a2fead20/lib/private/files/view.php#L664
5. In a separate tab, rename "test.txt" to "renamed.txt" (this should take a while)
6. In the first tab, during renaming, try downloading a version

### Expected result
File is locked, cannot download (or restore) version.

### Actual result
It is still possible to download or restore a version

### Versions
ownCloud 8.1 git master b88a0e7080cd5b1844cfb286b06744f3a2fead20

File actions from apps like versions need to also lock the file.

@icewind1991 @jnfrmarks @DeepDiver1975 @schiesbn

**Comment by PVince81** [comment]
Tentatively setting to 8.1, but not sure if enough time to fix it.

**Comment by PVince81** [comment]
@cmonteroluque @karlitschek @DeepDiver1975 moving to 8.1.1.
Needed to make locking more watertight.

**Comment by schiesbn** [comment]
I think it is probably OK that the download of a version works. The version is a different file then the original one. So why should we block the version if the original file gets manipulated.

I agree that restore shouldn't work. But what is the problem here? File versions always uses a view, so the same locking logic should be applied as for every other file? If you try to move a version to the original file and the original file is already locked the restore operation should be blocked.

**Comment by PVince81** [comment]
Downloading a version might work yes, thanks to the background job expiration the old "to be expired" version might still exist at the time of the download, even though the pending upload would expire it.

Even if the versions app uses the view, the restore operations aren't done within a view operation. Also if the view is working on the version file instead of the original one, it will lock the version file instead of the original file.
I think like for encryption and others we need to explicitly set a lock on the original file before we start the sub-operations for a file restore, and unlock at the end of it. (to make it a real transaction)

**Comment by PVince81** [comment]
Without transaction, have a look at https://github.com/owncloud/core/blob/master/apps/files_versions/lib/storage.php#L294 and for every file operation, ask yourself what could go wrong if someone else moved/deleted/overwrote the original file in-between.

**Comment by PVince81** [comment]
Same question actually for `getVersions()`: https://github.com/owncloud/core/blob/master/apps/files_versions/lib/storage.php#L349

If someone is currently moving the file, there is another process that will move the versions in process B while process A is trying to retrieve its list. We should at least set a shared lock on the original file here. The move operation would then set an exclusive lock on the file.
