### ISSUE TITLE
Upgrade from 6.0.8 to 7.0.7 beta broken

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#17253]
### Steps to reproduce
1. Install ownCloud 6.0.8
2. Upgrade the installation to 7.0.7beta (current commit 4448c06f145349847faf061ad64394b9673928cc) using occ

### Expected behaviour
Upgrade is successful

### Actual behaviour
Upgrade is done, but installation is broken. Blank page is shown.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 7.0.7 4448c06f145349847faf061ad64394b9673928cc

**Updated from an older ownCloud or fresh install:** update from 6.0.8

#### ownCloud log (data/owncloud.log)
```
{"app":"PHP","message":"Class 'Sabre\\DAV\\URLUtil' not found at \/opt\/owncloud\/lib\/private\/request.php#253","level":3,"time":"2015-06-30T09:43:02+00:00"}
```

**Comment by DeepDiver1975** [comment]
How did up install the 7.0.7 code base?
Looks like 3rdparty code is missing

**Comment by jvillafanez** [comment]
Now that you say that... I've picked the code from github, not from the tarball :scream: 

I'll check again with the tarball. Closing for now.

**Comment by jvillafanez** [comment]
Confirmed that I grabbed the code from the wrong place. The upgrade is fine.
