### ISSUE TITLE
"NaN" appears instead of the count of members of the group in the sidebar

### ISSUE THREAD

**Issue by davitol** [owncloud/core#17260]
### Steps to reproduce
1. Create new users in different groups

### Expected behaviour
The count of the member of a group should appear in the sidebar

### Actual behaviour
NaN is shown instead of the count of members of the group in the sidebar

### Server configuration
**Operating system**: centOS 6.6

**Web server:** Apache/2.2.15

**Database:** mysql

**PHP version:** 5.4.

**ownCloud version:**""7.0.7.0","versionstring":"7.0.7beta

**Updated from an older ownCloud or fresh install:** Fresh install
**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

**Comment by PVince81** [comment]
I thought we already had a ticket for this but cannot find it.

**Comment by davitol** [comment]
@PVince81 Maybe you are talking about this:
https://github.com/owncloud/core/issues/16876

**Comment by PVince81** [comment]
Yes, possibly.

Why did you set the milestone to 7.0.7 ? We only backport critical fixes to older versions.

**Comment by davitol** [comment]
@PVince81 Ok, you're right, i'll remove and let it without Milestone. The reason was due to the original issue has a regression label, so I thought it should be also fixed in the previous ones

**Comment by PVince81** [comment]
From the linked ticket I had the feeling that this was already fixed in older versions, but someone forgot to put the fix on master. So it might still be fixing on master / 8.1

**Comment by nickvergessen** [comment]
While reproducing make sure to create a new Group, existing groups are updated just fine.

**Comment by MorrisJobke** [comment]
This only happens on stable7.

**Comment by davitol** [comment]
:+1: Fixed in "7.0.7.2","versionstring":"7.0.7","edition":"enterprise"
