### ISSUE TITLE
Streaming issues when locking is enabled

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#17262]
See https://github.com/owncloud/core/issues/17242

Basically when locking is enabled, the music player stops after a while.

Needs further research.

**Comment by PVince81** [comment]
@icewind1991 assigned to you as you said you would look into a permanent solution.

**Comment by icewind1991** [comment]
Problem is not related to locking but comes down to https://bugs.php.net/bug.php?id=30936, the music player tries to read more then 8192 bytes from the stream and assumes it receives that much.

That works for local streams but not for any network or custom stream wrapper (yay "historical reaons")

**Comment by PVince81** [comment]
@icewind1991 any possible workarounds ? Should the music player be fixed then ?
