### ISSUE TITLE
UpdateChecker not working: Undefined variable: lastCheck

### ISSUE THREAD

**Issue by derkostka** [owncloud/core#17263]
### Steps to reproduce
1. Go to the Admin-Settings and change the Update Channel
2. Watch the Log-Output
3.

### Expected behaviour
No Error

### Actual behaviour
Undefined Variable thrown to Log

### Server configuration
Ubuntu 15.04
Apache2
MySQL
PHP 5.6
Owncloud 8.1 RC1

#### ownCloud log (data/owncloud.log)
```
{"reqId":"VZL6A38AAAEAAG160AMAAAAF","remoteAddr":"192.168.6.128","app":"PHP","message":"Undefined variable: lastCheck at \/var\/www\/owncloud\/apps\/updater\/ajax\/channel.php#25","level":3,"time":"June 30, 2015 22:20:20"}
```

**Comment by LukasReschke** [comment]
Can you please reopen at https://github.com/owncloud/updater? Thanks a lot!

**Comment by derkostka** [comment]
Sorry just seen this myself :( Thanks !
