### ISSUE TITLE
Part file error handling with s2s might cause original file deletion

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#17284]
### Steps
1. Setup two servers A and B
1. Create a folder "local" on A
1. Create a file "local/test.txt" on A
1. Share "local" with a user on server B
1. On server B, modify https://github.com/owncloud/core/blob/master/lib/private/connector/sabre/file.php#L143 and add `+1` to the condition to simulate a size mismatch / upload issue
1. On server B, use WebDAV and PUT a file in "local/test.txt" to overwrite it

### Expected result
Upload fails, original file still exists on A.

### Actual result
Upload fails with "Internal server error", original file disappears from A.

### Versions
ownCloud 8.1 RC2

This problem is introduced by https://github.com/owncloud/core/pull/17189.
When using federation, part files are disabled so $partPath contains the real path.
Whenever an error appears, the exception handling will try and delete the $partPath believing that it's the part file when in fact it's the real file.

Fix is here https://github.com/owncloud/core/pull/17268#issuecomment-117603059

**Comment by PVince81** [comment]
@cmonteroluque @karlitschek @DeepDiver1975 please evaluate severity/priority.

**Comment by MorrisJobke** [comment]
Fixed with #17268

**Comment by MorrisJobke** [comment]
Backport for 8.1.1 is ready: #17289
