### ISSUE TITLE
Regression in 8.1: wrong z-index positioning for unread count, menu and settings area in mobile view

### ISSUE THREAD

**Issue by Raydiation** [owncloud/core#17292]
When checking the mobile view of the News app, the unread count and menu button is floating over the content. This seems to be caused by z-index changes in 8.1.

Left side is 8.1, right side is 8.0:

![bug](https://cloud.githubusercontent.com/assets/195053/8456249/7e0119d8-200a-11e5-9112-1326771b5098.png)

@MorrisJobke @jancborchardt @PVince81

**Comment by Raydiation** [comment]
Also the settings area is not hidden properly

**Comment by PVince81** [comment]
@karlitschek @cmonteroluque @DeepDiver1975

**Comment by karlitschek** [comment]
And @jancborchardt

**Comment by jancborchardt** [comment]
Am about to fix this

**Comment by Raydiation** [comment]
:clap: :clap:

**Comment by jancborchardt** [comment]
Please review https://github.com/owncloud/core/pull/17293
