### ISSUE TITLE
Avatar route

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/core#17305]
Hello,

I am developing the navigator drawer for android.
Therefore I want to display all accounts with their avatars.
Is there a public route where I can get the avatar? Either the image or the capital first letter with the right color? There should also be an option to specify the size.

Thank you

**Comment by LukasReschke** [comment]
Will come in the future https://github.com/owncloud/core/pull/14856.

**Comment by tobiasKaminsky** [comment]
Great :)
And thanks for the very quick reply.
