### ISSUE TITLE
unit test on external filesystem is failing

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#17306]
0:00:26.692 ......................................PHP Fatal error:  Call to a member function getHome() on null in /var/jenkins/workspace/server-master-linux-externals/database/sqlite/external/webdav-ownCloud/label/vm-slave-02/apps/files_external/lib/config.php on line 674
00:00:30.668 PHP Stack trace:
00:00:30.668 PHP   1. {main}() /usr/local/bin/phpunit:0
00:00:30.668 PHP   2. PHPUnit_TextUI_Command::main() /usr/local/bin/phpunit:537
00:00:30.668 PHP   3. PHPUnit_TextUI_Command->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:105
00:00:30.668 PHP   4. PHPUnit_TextUI_TestRunner->doRun() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:153
00:00:30.668 PHP   5. PHPUnit_Framework_TestSuite->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/TestRunner.php:406
00:00:30.668 PHP   6. PHPUnit_Framework_TestSuite->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php:722
00:00:30.668 PHP   7. PHPUnit_Framework_TestCase->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php:722
00:00:30.668 PHP   8. PHPUnit_Framework_TestResult->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:699
00:00:30.668 PHP   9. PHP_Invoker->invoke() phar:///usr/local/bin/phpunit/phpunit/Framework/TestResult.php:607
00:00:30.668 PHP  10. call_user_func_array:{phar:///usr/local/bin/phpunit/php-invoker/Invoker.php:93}() phar:///usr/local/bin/phpunit/php-invoker/Invoker.php:93
00:00:30.668 PHP  11. PHPUnit_Framework_TestCase->runBare() phar:///usr/local/bin/phpunit/php-invoker/Invoker.php:93
00:00:30.668 PHP  12. PHPUnit_Framework_TestCase->runTest() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:743
00:00:30.668 PHP  13. ReflectionMethod->invokeArgs() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:866
00:00:30.668 PHP  14. OCA\Files_external\Tests\Service\UserStoragesServiceTest->testAddStorage() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:866
00:00:30.668 PHP  15. OCA\Files_external\Service\StoragesService->addStorage() /var/jenkins/workspace/server-master-linux-externals/database/sqlite/external/webdav-ownCloud/label/vm-slave-02/apps/files_external/tests/service/userstoragesservicetest.php:72
00:00:30.668 PHP  16. OCA\Files_external\Service\UserStoragesService->readConfig() /var/jenkins/workspace/server-master-linux-externals/database/sqlite/external/webdav-ownCloud/label/vm-slave-02/apps/files_external/service/storagesservice.php:283
00:00:30.668 PHP  17. OCA\Files_external\Service\StoragesService->readConfig() /var/jenkins/workspace/server-master-linux-externals/database/sqlite/external/webdav-ownCloud/label/vm-slave-02/apps/files_external/service/userstoragesservice.php:73
00:00:30.668 PHP  18. OCA\Files_external\Service\UserStoragesService->readLegacyConfig() /var/jenkins/workspace/server-master-linux-externals/database/sqlite/external/webdav-ownCloud/label/vm-slave-02/apps/files_external/service/storagesservice.php:92
00:00:30.668 PHP  19. OC_Mount_Config::readData() /var/jenkins/workspace/server-master-linux-externals/database/sqlite/external/webdav-ownCloud/label/vm-slave-02/apps/files_external/service/userstoragesservice.php:62

**Comment by DeepDiver1975** [comment]
@Xenopathic this is failing since https://github.com/owncloud/core/commit/728a22cda18845f831d65eac0c6f49b9f9b3b42f

**Comment by DeepDiver1975** [comment]
@karlitschek @cmonteroluque 8.1 is NOT affected - just FYI

**Comment by MorrisJobke** [comment]
> @karlitschek @cmonteroluque 8.1 is NOT affected - just FYI

Then move this to 8.2 milestone?
