### ISSUE TITLE
Should "Enable User External Storage" be checked after enabling external storage app?

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#17303]
### Steps to reproduce
1. Install 8.1 
2. Enable external storage
3. Go to admin page - see that the "Enable User External Storage" checkbox is checked 
4. Go to user's personal page and try to configure external storage
### Expected behaviour

Not sure - my guess is that the "enable user external storage" box should not be checked when external storage is enabled
### Actual behaviour

The user can't configure external storage even though it looks like they should be able to.

![p369](https://cloud.githubusercontent.com/assets/8480343/8462056/159e0672-1fff-11e5-9bca-4fae17d6632b.PNG)

![p370](https://cloud.githubusercontent.com/assets/8480343/8462058/19367666-1fff-11e5-8fc2-37fecff49db9.PNG)
### Server Host info:

Ubuntu 14.04
PHP 5.5.9
### Server configuration:

ownCloud Enterprise Edition 8.1 RC2 (testing)

**Comment by PVince81** [comment]
@LukasReschke what do you think ?

I believe these options were added for security, to avoid having users being able to mount anything.
It might be fine to have it default to "nothing" by default to avoid oversight.

**Comment by PVince81** [comment]
Hmm right, I see. Could be a bug that it's set by default without any selection.

We should probably disable the main checkbox by default.

**Comment by oparoz** [comment]
If you want to keep it checked, then you need to hide the panel from users until at least one backend is selected, because it doesn't make sense to show users a dialogue they can't use.

**Comment by PVince81** [comment]
Won't fix, unless someone wants to submit a PR.
