### ISSUE TITLE
Owncloud server not reporting etag changes for newly added groups

### ISSUE THREAD

**Issue by shoelzle** [owncloud/core#17301]
In summary, the problem is that the owncloud server doesn't report etag changes if a user is added to a group which already has shares.

I intially reported this issue in the owncloud client project: https://github.com/owncloud/client/issues/3274
More information including used versions, steps to reproduce and a client log can be found there.

**Comment by karlitschek** [comment]
@icewind1991 What do you think?

**Comment by PVince81** [comment]
@shoelzle to clarify: before the user was added in the group, the user did not have a folder say "newshares". And as soon as the user got added to the group, a folder "newshares" appears but that apparition did not trigger an etag change in the parent folders.
Is that correct ?

**Comment by PVince81** [comment]
### Steps

1. Login as admin
1. Create two users "user1" and "user2"
1. Add "user1" into a new group "group1"
1. Create a folder "test"
1. Share "test" with "group1"
1. On the CLI/Webdav/cadaver, propget the etag of user2's root
1. Now add "user2" to "group1"
1. Check the etag of user2's root again

### Expected result
etag changes

### Actual result
etag did not change

### Version
Tested on OC 8.0.5 RC1

**Comment by PVince81** [comment]
Also if you remove "user2" from the group, the etag also does not change on OC 8.0.5 RC1.

Does not work either on 8.1 RC 1.
Well, actually I saw it change once, but it might have been luck.
Alternating between "user2" is in group and not in group did not change the etag on further requests.

@schiesbn I seem to vaguely remember a discussion about user hooks and FS mounts problems ?

**Comment by shoelzle** [comment]
@PVince81 to answer your earlier question: yes, this sounds like the problem to me, although I don't know exactly what you mean by appartition.

**Comment by PVince81** [comment]
I tried it several times. The etag only changes the very first time the user is assigned to the group.
Further changes like removing the user from the group or adding again will not change the etag any more.

I wonder if the hooks aren't firing properly, or something.

**Comment by PVince81** [comment]
Weiiird. I tried to find the location where the etag was changed and it happens exactly when this SQL query is executed: https://github.com/owncloud/core/blob/stable8.1/lib/private/group/database.php#L130
It doesn't even make sense.

Otherwise I didn't find any location that would propagate etags within these hooks. The code seems to be missing completely and will need to be added.

**Comment by PVince81** [comment]
Ok I think I understand. What probably happens is that the `PROPFIND` I'm doing to check the etag is actually finding the new DB entry and updating the etag. So there is logic after all. Now the question is why it doesn't redo it the subsequent times.

**Comment by PVince81** [comment]
The etag change is happening here for any Webdav request (setupfs) happening after the group membership was added, but I still can't explain why it happens yet:
```
0  OC\Files\Cache\Cache->update() /srv/www/htdocs/owncloud/lib/private/files/cache/cache.php:344
1  OC\Files\Cache\ChangePropagator->propagateChanges() /srv/www/htdocs/owncloud/lib/private/files/cache/changepropagator.php:79
2  OCA\Files_Sharing\Propagation\RecipientPropagator->propagateDirtyMountPoints() /srv/www/htdocs/owncloud/apps/files_sharing/lib/propagation/recipientpropagator.php:84
3  OCA\Files_Sharing\MountProvider->getMountsForUser() /srv/www/htdocs/owncloud/apps/files_sharing/lib/mountprovider.php:64
4  OC\Files\Config\MountProviderCollection->OC\Files\Config\{closure}() /srv/www/htdocs/owncloud/lib/private/files/config/mountprovidercollection.php:61
5  array_map()     /srv/www/htdocs/owncloud/lib/private/files/config/mountprovidercollection.php:62
6  OC\Files\Config\MountProviderCollection->getMountsForUser() /srv/www/htdocs/owncloud/lib/private/files/config/mountprovidercollection.php:62
7  OC\Files\Filesystem::initMountPoints() /srv/www/htdocs/owncloud/lib/private/files/filesystem.php:425
8  OC\Cache\File->getStorage() /srv/www/htdocs/owncloud/lib/private/cache/file.php:50
9  OC\Cache\File->gc() /srv/www/htdocs/owncloud/lib/private/cache/file.php:171
10 OC::{closure:/srv/www/htdocs/owncloud/lib/base.php:735-744}() /srv/www/htdocs/owncloud/lib/base.php:738
11 call_user_func_array:{/srv/www/htdocs/owncloud/lib/private/hooks/emittertrait.php:98}() /srv/www/htdocs/owncloud/lib/private/hooks/emittertrait.php:98
12 OC\Hooks\BasicEmitter->emit() /srv/www/htdocs/owncloud/lib/private/hooks/emittertrait.php:98
13 OC\Hooks\PublicEmitter->emit() /srv/www/htdocs/owncloud/lib/private/hooks/publicemitter.php:32
14 OC\User\Session->login() /srv/www/htdocs/owncloud/lib/private/user/session.php:223
15 OC_User::login() /srv/www/htdocs/owncloud/lib/private/user.php:242
16 OC\Connector\Sabre\Auth->validateUserPass() /srv/www/htdocs/owncloud/lib/private/connector/sabre/auth.php:76
17 Sabre\DAV\Auth\Backend\AbstractBasic->authenticate() /srv/www/htdocs/owncloud/3rdparty/sabre/dav/lib/DAV/Auth/Backend/AbstractBasic.php:74
18 OC\Connector\Sabre\Auth->auth() /srv/www/htdocs/owncloud/lib/private/connector/sabre/auth.php:149
19 OC\Connector\Sabre\Auth->authenticate() /srv/www/htdocs/owncloud/lib/private/connector/sabre/auth.php:122
20 Sabre\DAV\Auth\Plugin->beforeMethod() /srv/www/htdocs/owncloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php:118
21 call_user_func_array:{/srv/www/htdocs/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php:105}() /srv/www/htdocs/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php:105
22 Sabre\Event\EventEmitter->emit() /srv/www/htdocs/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php:105
23 Sabre\DAV\Server->invokeMethod() /srv/www/htdocs/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php:456
24 Sabre\DAV\Server->exec() /srv/www/htdocs/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php:254
25 require_once()  /srv/www/htdocs/owncloud/apps/files/appinfo/remote.php:83
26 {main}          /srv/www/htdocs/owncloud/remote.php:132
```

CC @icewind1991

**Comment by PVince81** [comment]
Ok got it... the reason the etag change might be another bug.
Since this user never had any share propagation before, the "last_propagate" value is 0.
But also, the new share has no last propagate value either, so it's also 0.
This means that the first time this share is encountered, it is considered as dirty here https://github.com/owncloud/core/blob/stable8.1/apps/files_sharing/lib/propagation/recipientpropagator.php#L96

So this has nothing to do with intentional propagation at this stage.

For now: we need to add code to explicitly trigger (or schedule or mark as dirty) propagation after a user has been added or removed from a group.

**Comment by PVince81** [comment]
The trickiest part is to find out what shares were available before adding to group and then the ones after, then gather the folders in which they are mounted. Then propagate etags in these folders.

**Comment by PVince81** [comment]
First tentative PR: https://github.com/owncloud/core/pull/18128
