### ISSUE TITLE
OC 8.0.4 Invalid OCS content returned for app .....

### ISSUE THREAD

**Issue by zubanst** [owncloud/core#17307]
OC 8.0.4 fresh install, only default application enabled, when you clic on +Apps to see the application list, you get sistematically the following error in the log:

Fatal 	core 	Invalid OCS content returned for app 166049 	2015-07-02T02:39:00+00:00
Fatal 	core 	Invalid OCS content returned for app 166055 	2015-07-02T02:39:00+00:00
Fatal 	core 	Invalid OCS content returned for app 166059 	2015-07-02T02:39:00+00:00
Fatal	core	Invalid OCS content returned for app 166053	2015-07-02T02:38:59+00:00
Fatal	core	Invalid OCS content returned for app 166052	2015-07-02T02:38:59+00:00
Fatal	core	Invalid OCS content returned for app 166038	2015-07-02T02:38:59+00:00
Fatal	core	Invalid OCS content returned for app 166056	2015-07-02T02:38:59+00:00
Fatal	core	Invalid OCS content returned for app 166051	2015-07-02T02:38:59+00:00

**Comment by RealRancor** [comment]
Very likely a dup of https://github.com/owncloud/core/issues/16136

**Comment by LukasReschke** [comment]
Seems like we need to remove the OCS IDs as well. Stupid mistake of mine, error is non-fatal and will be fixed with the next releases.

**Comment by LukasReschke** [comment]
@RealRancor Nope. This one is happening because I cleaned up the AppStore and deleted placeholders :-/

**Comment by RealRancor** [comment]
@LukasReschke 

Isn't this the same then:

> That leads to "Invalid OCS content returned for app xyz" messages in the log for apps which don't exist in the app store.

**Comment by LukasReschke** [comment]
That one is a bug when an app has no OCS ID specified. Then it does a lookup with the App Name which fails. In this case the OCS ID is specified but points to a not existing entry. Same message, different root cause :smiley:

**Comment by RealRancor** [comment]
Ahh, got it :)

**Comment by LukasReschke** [comment]
Will be fixed once all of the linked PRs are merged.

**Comment by MorrisJobke** [comment]
This is now fixed

**Comment by zubanst** [comment]
This is not fixed in owncloud 8.0.5
Fatal 	core 	Invalid OCS content returned for app 166048 	2015-08-10T12:45:59+00:00
Fatal 	core 	Invalid OCS content returned for app 166049 	2015-08-10T12:45:59+00:00
Fatal 	core 	Invalid OCS content returned for app 166055 	2015-08-10T12:45:58+00:00 
...

**Comment by Megachip** [comment]
@MorrisJobke @zubanst same here:

**Comment by MorrisJobke** [comment]
@LukasReschke Are all apps are updated in the appstore?

**Comment by blue-bean** [comment]
Also in 8.0.7 it's not fixed.

**Comment by disy-mk** [comment]
And also present in 7.0.10

**Comment by blue-bean** [comment]
+1 (for 8.0.8)

**Comment by koumdros** [comment]
+1 for 8.0.10

**Comment by RealRancor** [comment]
Just upgrade to 8.1.5 or 8.2.2 and the messages will disappear
