### ISSUE TITLE
Repair info during the upgrade isn't being shown

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#17313]
Checked upgrading 7.0.6 to 7.0.7 and with MySQL

### Steps to reproduce
1. Install ownCloud 7.0.6 with a MySQL DB
2. Modify some table charset and the collation to something different than utf8 (checked with charset = latin1 and collation = latin1_bin)
3. Upgrade the installation to 7.0.7 using cli

### Expected behaviour
Messages changing the collation of the tables to utf8 should be shown

### Actual behaviour
Those messages aren't shown.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** MySQL

**PHP version:** 5.5.9

**ownCloud version:** OC 7.0.7

**Updated from an older ownCloud or fresh install:** upgrade from 7.0.6

ref https://github.com/owncloud/core/pull/17020

**Comment by PVince81** [comment]
Maybe because on OC 7 we simply did not log detailed info.
That has been introduced later, either in 8.0 or 8.1

**Comment by MorrisJobke** [comment]
> Maybe because on OC 7 we simply did not log detailed info.
> That has been introduced later, either in 8.0 or 8.1

The emit is fired and the listen was also introduced. I've seen the steps in a local stable7 here. I simply need to check for this specific emit, that didn't show up. ;)

**Comment by jvillafanez** [comment]
I think the listen is attached to the updater, but the emit isn't there but in the repair object. Probably the signal isn't being forwarded to the updater. Basically, you're listening for the signal in the wrong object.

**Comment by MorrisJobke** [comment]
@cmonteroluque I just submitted the fix ;)
