### ISSUE TITLE
Editing of phonetic name got lost from OC7 to OC8

### ISSUE THREAD

**Issue by norbusan** [owncloud/core#17315]
### Steps to reproduce
1. create a new contact with main name in kanji
2. there is no way to edit the phonetic name

### Expected behaviour
In OC7 there was a "pen" symbol next to the name, when clicking on it it allowed to change the phonetic names.

### Actual behaviour
No pen icon

### Server configuration
**Operating system**: Debian/wheezy

**Web server:** apache

**Database:** mysql

**PHP version:** 5.4.41

**ownCloud version:** 8.0.4.2

**Updated from an older ownCloud or fresh install:** fresh install

**List of activated apps:** files, activity, pictures, contacts, calendar

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'trusted_domains' => 
  array (
    0 => 'cloud.preining.info',
  ),
  'overwrite.cli.url' => 'https://cloud.preining.info',
  'dbtype' => 'mysql',
  'version' => '8.0.4.2',
  'dbhost' => 'localhost',
  'installed' => true,
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
);
```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** firefox/iceweasel 38.0.1

**Operating system:** linux (Debian/sid)

#### Web server error log
```
none
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"46253e1548e35528c3c015724565081d","remoteAddr":"110.4.213.3","app":"PHP","message":"Array to string conversion at \/home\/web\/preining.info\/cloud\/lib\/private\/l10n\/string.php#75","level":3,"time":"2015-07-02T05:52:36+00:00"}
{"reqId":"46253e1548e35528c3c015724565081d","remoteAddr":"110.4.213.3","app":"PHP","message":"chmod(): Operation not permitted at \/home\/web\/preining.info\/cloud\/lib\/private\/log\/owncloud.php#85","level":3,"time":"2015-07-02T05:52:37+00:00"}
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log

```
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://cloud.preining.info 'unsafe-eval'").
```

**Comment by RealRancor** [comment]
Hi,

isn't this an issue within the contacts app?

https://github.com/owncloud/contacts/issues

If yes this is very likely related to https://github.com/owncloud/contacts/issues/823 which got fixed by https://github.com/owncloud/contacts/pull/850

**Comment by norbusan** [comment]
Indeed, thanks, I didn't realize there a different contact and core issue trackers. I close the bug. The bug of the contact app is exactely what I meant. 

Thanks
