### ISSUE TITLE
"Remove image" button appears in the avatar section of the personal page just by changing the full name of the user

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#17320]
### Steps to reproduce
1. Go to the personal page
2. Delete any avatar you might have
3. Change the full name of the user

### Expected behaviour
The avatar section should remain unchanged

### Actual behaviour
A "remove image" button appears in the avatar section even though the avatar is the default one

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** MySQL

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1RC2

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by MorrisJobke** [comment]
@Henni Mind to have a look at this? :)

**Comment by PVince81** [comment]
@Henni any update ?

**Comment by Henni** [comment]
I didn't have any time to look at this. Maybe after contacts is released.
