### ISSUE TITLE
Third party app code update during OC upgrade fails OC upgrade

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#17323]
Normally the upgrade process should disable third party apps.
I suspect that the package might be using the option to prevent disabling third party apps.
@jnweiger can you confirm ?

Before the update I had the calendar app version 0.6.4 installed and contacts 0.3.0.18 installed from git (because the app store versions weren't ready back then)

I did a `zypper update`, updating from 8.1.0~RC1

```
( 1/23) Installing: owncloud-server-8.1.0~RC2-2.1 .............................................................................................................[done]
Additional rpm output:
owncloud-server: Upgrade starting
owncloud-server: occ maintenance:mode --on
Maintenance mode enabled
owncloud-server Upgrade complete
ownCloud or one of the apps require upgrade - only a limited number of commands are available
Maintenance mode disabled
owncloud-server: occ upgrade
ownCloud or one of the apps require upgrade - only a limited number of commands are available
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Disabled 3rd-party app: calendar
Disabled 3rd-party app: contacts
Update 3rd-party app: calendar
Exception: App can't be installed because it is not compatible with this version of ownCloud
Update failed
Maintenance mode is kept active
ownCloud or one of the apps require upgrade - only a limited number of commands are available
Maintenance mode disabled


( 2/23) Installing: owncloud-app-files_trashbin-8.1.0~RC2-2.1 .................................................................................................[done]
( 3/23) Installing: owncloud-app-gallery-8.1.0~RC2-2.1 ........................................................................................................[done]
( 4/23) Installing: owncloud-app-firstrunwizard-8.1.0~RC2-2.1 .................................................................................................[done]
( 5/23) Installing: owncloud-app-files_sharing-8.1.0~RC2-2.1 ..................................................................................................[done]
( 6/23) Installing: owncloud-app-files_pdfviewer-8.1.0~RC2-2.1 ................................................................................................[done]
( 7/23) Installing: owncloud-app-encryption-8.1.0~RC2-2.1 .....................................................................................................[done]
( 8/23) Installing: owncloud-app-files_texteditor-8.1.0~RC2-2.1 ...............................................................................................[done]
( 9/23) Installing: owncloud-app-user_ldap-8.1.0~RC2-2.1 ......................................................................................................[done]
(10/23) Installing: owncloud-app-files-8.1.0~RC2-2.1 ..........................................................................................................[done]
(11/23) Installing: owncloud-app-templateeditor-8.1.0~RC2-2.1 .................................................................................................[done]
(12/23) Installing: owncloud-app-activity-8.1.0~RC2-2.1 .......................................................................................................[done]
(13/23) Installing: owncloud-app-external-8.1.0~RC2-2.1 .......................................................................................................[done]
(14/23) Installing: owncloud-app-user_external-8.1.0~RC2-2.1 ..................................................................................................[done]
(15/23) Installing: owncloud-app-files_versions-8.1.0~RC2-2.1 .................................................................................................[done]
(16/23) Installing: owncloud-app-files_external-8.1.0~RC2-2.1 .................................................................................................[done]
(17/23) Installing: owncloud-app-provisioning_api-8.1.0~RC2-2.1 ...............................................................................................[done]
(18/23) Installing: owncloud-app-files_videoviewer-8.1.0~RC2-2.1 ..............................................................................................[done]
(19/23) Installing: owncloud-3rdparty-8.1.0~RC2-2.1 ...........................................................................................................[done]
(20/23) Installing: owncloud-app-user_webdavauth-8.1.0~RC2-2.1 ................................................................................................[done]
(21/23) Installing: owncloud-app-files_locking-8.1.0~RC2-2.1 ..................................................................................................[done]
(22/23) Installing: owncloud-config-apache-8.1.0~RC2-2.1 ......................................................................................................[done]
Additional rpm output:
owncloud update: Checking for running Apache
owncloud-config-apache: Upgrade complete
owncloud-config-apache: Reloading


(23/23) Installing: owncloud-8.1.0~RC2-2.1 ....................................................................................................................[done]
```

When opening my server I was presented with the usual update screen.
When I clicked "Update now", the update worked.

This ticket is about discussing whether packages should auto-disable third party apps or not. (currently it doesn't).

In theory the script could even first run the update and if an app update failed, then re-run it with app disabling. (I wonder if we could do that on the PHP side instead)

Please confirm whether this is expected behavior. I can understand that on environment that work with packages admins do not want to have to re-enable apps automatically.

@jnweiger @DeepDiver1975 @karlitschek

**Comment by RealRancor** [comment]
> (currently it doesn't).

Mhhh, isn't the posted output exactly showing the opposite or am i wrong?

> Disabled 3rd-party app: calendar
> Disabled 3rd-party app: contacts

**Comment by PVince81** [comment]
Right... sorry... I didn't read the output...

Still strange that after that it says `Exception: App can't be installed because it is not compatible with this version of ownCloud`

**Comment by DeepDiver1975** [comment]
calendar and contacts are not yet ready for 8.1 @jancborchardt and myself are working on this.

@PVince81 Where are these apps coming from? Appstore? are there packages?

**Comment by PVince81** [comment]
When I installed 8.1.0RC1 I took the git master from calendar and contacts because I needed these apps. Then I upgraded to 8.1.0RC2 with the package manager.

I'd expect the upgrade to disable the apps and then continue. But it didn't, I had to click in the UI to retry the update.

**Comment by DeepDiver1975** [comment]
I see two issues in here:
- first contacts and calendar where not yet ready for 8.1 (should be as of now)
- at any point in time an app upgrade can cause this issue - should the package upgrade fail hard?

**Comment by PVince81** [comment]
The issue I see here, regardless, is that both things happened at the same time:
1) it disabled the app
2) it still tried to upgrade it

Normally it should either do 1) (default behavior) **or** do 2) if the option `--no-app-disable` was passed.

**Comment by DeepDiver1975** [comment]
> The issue I see here, regardless, is that both things happened at the same time:
> 1) it disabled the app
> 2) it still tried to upgrade it

so true ...

**Comment by PVince81** [comment]
Hmm it could also be a caching issue. Maybe at the time the app was disabled, the "list of enabled apps" cache wasn't updated. I think I have APC:
```
i | php5-APC                     | package | 3.1.14_git201309121127-3.1 | x86_64 | phpextensions 
```

**Comment by RealRancor** [comment]
But isn't this more a problem within core itself rather then the packages?

**Comment by PVince81** [comment]
I'll see if I can reproduce this locally. (the above was on my productive server).

@RealRancor yes, seems like it.

**Comment by PVince81** [comment]
Steps to reproduce:
1. Checkout 8.1.0RC1 from git (d5ef1f28ce0d4014161155e2d0a2493bdba52913)
1. Setup ownCloud
1. Check out calendar app (master) into the "apps" folder
1. Enable calendar app
1. Switch core to 8.1RC2
1. Run upgrade on the CLI: `sudo -uwwwrun ./occ upgrade`

Result without cache:
```
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Disabled 3rd-party app: admin_migrate
Disabled 3rd-party app: calendar
Disabled 3rd-party app: files_odfviewer
Disabled 3rd-party app: user_migrate
Update successful
Turned off maintenance mode
```

Will try with APC cache next

**Comment by PVince81** [comment]
Hmmm that server only had APC enabled.
As far as I understand this is only a code/opcache, not a memcache. Not sure in what way it would influence the upgrade.

**Comment by PVince81** [comment]
Ok so APCu CLI update doesn't work, raised as https://github.com/owncloud/core/issues/17329.

**Comment by PVince81** [comment]
Never mind, user error.
APCu CLI update worked, also to note that 3rd party apps were disabled properly.

Now trying the old APC module.

**Comment by PVince81** [comment]
More info about the server:
- openSUSE 13.1 x86_64
- php5-5.4.20-58.1.x86_64
- apache2-2.4.6-6.47.1.x86_64

Looks like I'll have to setup an older VM since recent systems run on PHP 5.6 which has opcache instead of APC (and saw no issues wih opcache)

**Comment by PVince81** [comment]
Found a bit more info in the log from the time of the CLI update on the server:
```
{
  "reqId": "fI3xJiho48WGmy2L4jfj",
  "remoteAddr": "",
  "app": "update",
  "message": "Exception: {\"Exception\":\"Exception\",\"Message\":\"App can't be installed because it is not compatible with this version of ownCloud\",\"Code\":0,\"Trace\":\"
#0 /srv/www/htdocs/owncloud/lib/private/installer.php(191): OC_Installer::checkAppsIntegrity(Array, '/tmp/oc_tmp_6Zt...', '/tmp/oc_tmp_NCg...', false)\n
#1 /srv/www/htdocs/owncloud/lib/private/installer.php(244): OC_Installer::updateApp(Array)\n
#2 /srv/www/htdocs/owncloud/lib/private/updater.php(474): OC_Installer::updateAppByOCSId('168707')\n
#3 /srv/www/htdocs/owncloud/lib/private/updater.php(295): OC\Updater->upgradeAppStoreApps(Array)\n
#4 /srv/www/htdocs/owncloud/lib/private/updater.php(195): OC\Updater->doUpgrade('8.1.0.8', '8.1.0.7')\n
#5 /srv/www/htdocs/owncloud/core/command/upgrade.php(172): OC\Updater->upgrade()\n
#6 /srv/www/htdocs/owncloud/3rdparty/symfony/console/Symfony/Component/Console/Command/Command.php(253): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))\n
#7 /srv/www/htdocs/owncloud/3rdparty/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))\n
#8 /srv/www/htdocs/owncloud/3rdparty/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))\n
#9 /srv/www/htdocs/owncloud/3rdparty/symfony/console/Symfony/Component/Console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))\n
#10 /srv/www/htdocs/owncloud/lib/private/console/application.php(94): Symfony\Component\Console\Application->run(NULL, NULL)\n
#11 /srv/www/htdocs/owncloud/console.php(68): OC\Console\Application->run()\n
#12 /srv/www/htdocs/owncloud/occ(11): require_once('/srv/www/htdocs...')\n
#13 {main}\",\"File\":\"/srv/www/htdocs/owncloud/lib/private/installer.php\",\"Line\":342}",
  "level": 4,
  "time": "2015-07-02T08:12:44+00:00",
  "method": "--",
  "url": "--"
}
```

**Comment by PVince81** [comment]
Hmmm, looking at the code, it looks like it's trying to actually upgrade the disabled apps, see:
https://github.com/owncloud/core/blob/v8.1RC2/lib/private/updater.php#L295

Is that intended @DeepDiver1975 ?

The OCSID in the stack trace is from the calendar app.

On my setup, the calendar version was on version 0.6.4 but the app store provides 0.6.5.
So even though the app was disabled, it found an update for it.

I'll revisit the steps to reproduce to include that.

**Comment by PVince81** [comment]
@DeepDiver1975 hmmm it might be correct to try and update the **code** of disabled app from the app store during an upgrade. It's just that in this specific situation the app store version tells that the app is not compatible with 8.1, so did not update its code.

**Comment by jnweiger** [comment]
@PVince81 
The package install/upgrade scripts do 
  occ maintenance:mode --on 
before install, and 
  occ maintenance:mode --off
  occ upgrade
after install. There is currently no dedicated logic regarding 3dparty apps.

**Comment by DeepDiver1975** [comment]
> Is that intended @DeepDiver1975 ?

to be honest: yes, no - maybe - we can construct any meaningful scenario around this.

For 8.2 we will adopt this to show upgraded apps explicitly in the apps management so that the admin can upgrade them individually. Reasonable for 8.1 as well?

**Comment by PVince81** [comment]
Hmmm, I'm having trouble reproducing it.
On my server I had the git master version of calendar which was somewhere between 0.6.3 and 0.6.4.

Anyway, the specific issue I bumped into seems to be a corner case. It will disappear once the app store app is properly updated.

In case an app store app code update fails during upgrade (for example due to compatibility), we could add a try/catch to make it fail gracefully and still carry on instead of failing.

As you said, a list of failed app could be displayed for convenience.

Probably something for 8.2 then.

**Comment by PVince81** [comment]
@DeepDiver1975 Do we agree about the approach of silently failing upgrading the apps code here https://github.com/owncloud/core/blob/v8.1.1/lib/private/updater.php#L476 (adding try/catch)

The admin can always retry to upgrade them in the apps page.

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 Do we agree about the approach of silently failing upgrading the apps code here https://github.com/owncloud/core/blob/v8.1.1/lib/private/updater.php#L476 (adding try/catch)

worth a try
