### ISSUE TITLE
Large "local" external storage hangs ownCloud

### ISSUE THREAD

**Issue by radistmorse** [owncloud/core#17334]
I have two local mounts, one ~3TB and the other ~1TB. Every time I log in to ownCloud, the php process starts eating RAM like crazy, even though I limited the RAM usage to 256M in php.ini (is there a way I can limit it harder?)
```
# ps aux | grep php
root      1225  0.0  0.0 418336   764 ?        Ss   июн15   0:40 php-fpm: master process (/etc/php5/fpm/php-fpm.conf)
www-data  1418  0.0 17.6 1216112 714556 ?      S    июн15   0:15 php-fpm: pool www
www-data  1462  0.0 33.2 2710892 1346132 ?     S    июн15   0:17 php-fpm: pool www
www-data  1484  0.0 33.2 2708892 1345568 ?     S    июн15   0:18 php-fpm: pool www
www-data  3975  0.1  3.7 559456 151000 ?       S    13:16   0:02 php-fpm: pool www
www-data  3976  0.1  3.6 559448 149180 ?       S    13:16   0:01 php-fpm: pool www
```
When it eats all the memory (4GB), it starts swapping, and at that point everything dies. The OC log has only this to say about it
```
Debug 	core 	OC\Tags::__construct, tags: Array ( [0] => OC\Tagging\Tag Object ( [owner:protected] => morse [type:protected] => files [name:protected] => _$!<Favorite>!$_ [id] => 3 [_updatedFields:OCP\AppFramework\Db\Entity:private] => Array ( ) [_fieldTypes:OCP\AppFramework\Db\Entity:private] => Array ( [id] => integer ) ) ) 
```
Is there a way to disable the indexing for the external storages?

**Comment by PVince81** [comment]
Is that "Local" external storage used exclusively through ownCloud ?
If yes, in 8.1 there is a new options dropdown where you can tell it to never detect external updates.

If in your OC setup you only have storage used exclusively by ownCloud, you could then set that option globally, see https://github.com/owncloud/core/blob/v8.1RC2/config/config.sample.php#L909

Regardless, it seems to be a bug that the scan process eats that much RAM!

@icewind1991 any idea what could be causing this ? Etag propagation cache during scan or other local caches ?

**Comment by radistmorse** [comment]
No, they are used outside ownCloud as well. Moreover, ownCloud has the read-only access to them. The thing I would like to turn off is not the indexing of every particular folder once I try to browse it, but rather the deep indexing that happens on mounting the storage. Right now these mounts have "unknown" size, which might be because OC was never able to finish that indexing.

**Comment by radistmorse** [comment]
BTW, when I try to do the deep scanning manually with
```
sudo -u www-data sh -c "./occ files:scan --path /path/to/mount"
```
It also finishes unsuccessfully after php process reaches the 512M memory limit which I put in cli/php.ini (well, at least it honors the limit). It takes considerable more time in that case though, in the situation described in the report all the 4GB of RAM gets eaten in the matter of minutes.

**Comment by PVince81** [comment]
Thanks for the info. "files:scan" is what I would have suggested. Unfortunately it doesn't seem to finish either :frowning: 

Which ownCloud version are you currently using ? Have you tried with 8.0.4 ?

**Comment by radistmorse** [comment]
I have 8.0.3 right now, but I can try 8.0.4 if there is a chance it'll fix the things.

**Comment by PVince81** [comment]
If I remember well, the indexing is usually trying to scan everything where the size is "-1", it doesn't limit itself to the currently browsed folder. I'm not aware of any way of disabling that, apart from what I suggested which disable update detection completely but would still require an initial full scan.

8.0.4 doesn't seem to bring any fixes related to scanning/indexing unfortunately.

How many files do you have in total on that storage ? (file count, not size)
From what I understand is that if you manage to finish the full scan, it should never have the need to rescan it completely.

Question: do you have any symbolic links ? If yes, there is a slight chance that it is running into an infinite loop.

**Comment by radistmorse** [comment]
There shouldn't be any symbolic links, and the storage has 676303 files. While checking the files, I found out that several folders are read-protected (i.e. non-readable), don't know if it could cause anything.

Also, the folders are not exactly "local", they are actually NFS-mounted, if it could affect anything.

Right now I'm upgrading to 8.0.4 and will try to run "files:scan" with bigger limit in cli/php.ini

**Comment by radistmorse** [comment]
Nope, still can't finish the scan. It was doing files without any errors, then it reached some folder and just stopped
```
Scanning folder /path/to/my/folder
```
This was the last message I saw, and then it just hanged for quite some time, during which it used a bit of CPU and was constantly increasing the memory usage, and eventually
```
PHP Fatal error:  Allowed memory size of 2147483648 bytes exhausted (tried to allocate 1935 bytes) in /usr/share/nginx/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 128
```
The folder seems to be fine, just 967 files for a total of 16GB, not much different from the previous folder that was scanned OK.

**Comment by alexpdp7** [comment]
I am also suffering from this- I'm trying to use an OC5 instance as external storage (using WebDav), but the scan never ends...

**Comment by PVince81** [comment]
Is this still happening with 8.2.2 ?

**Comment by radistmorse** [comment]
I updated my OC installation and launched full rescan. It's still going, which is a good thing, I guess, since it would've hanged by this point before. So there is a good chance it's fixed, but I'll wait until the scan finishes.

**Comment by PVince81** [comment]
@radistmorse still going ?

**Comment by radistmorse** [comment]
Oh, sorry, I forgot to answer. No, it didn't finish. Again, it just stopped, but this time it didn't start eating memory, but just hanged. So whatever this is now, it's probably a different issue. Unfortunately, I don't have time to investigate it right now. Also, as it doesn't eat all the RAM, this hanging doesn't DoS my server, so it's not that much of a problem anymore.

**Comment by PVince81** [comment]
Hmm ok. I'll close this ticket then.

If at some point you have more information about the new issue, please make a new ticket. Thanks.
