### ISSUE TITLE
AWS Keys in Plain Text

### ISSUE THREAD

**Issue by vikas027** [owncloud/core#17331]
I am using owncloud v8.0.4 and just noticed that AWS Secret keys are placed in plain text in `/var/www/html/owncloud/data/mount.json`.

This is a big security hole in my humble opinion. Is there an option to encrypt these ?

**Comment by LukasReschke** [comment]
We can only encrypt these with values accessible to the ownCloud server and thus any admin. Thus if an attacker gains access to these files it is very likely that he gains access to all other secrets as well.

However, we can do this for the sake of obfuscation and making it not that easy...

**Comment by DeepDiver1975** [comment]
mount.json will die in 8.2 and any information is stored in the db - I see no further action required.

close?

**Comment by LukasReschke** [comment]
> mount.json will die in 8.2 and any information is stored in the db - I see no further action required.

Depends on whether we want to encrypt the information in the DB. As I already see a bunch of other people complaining about this I'd say should be consistent: If we continue to encrypt the other creds then we should encrypt this as well. if we don't then we don't here as well.

**Comment by DeepDiver1975** [comment]
I have no strong feelings on this topic - as in: me not cares ... :speak_no_evil:

**Comment by LukasReschke** [comment]
Was actually a customer requirement at some point. So I think we shall do this even if it is snake-oily :speak_no_evil:

**Comment by LukasReschke** [comment]
Ref https://github.com/owncloud/core/pull/7794 and https://github.com/owncloud/core/issues/7717

**Comment by hutchic** [comment]
bumping as this can probably be closed now that https://github.com/owncloud/core/pull/7794 merged
