### ISSUE TITLE
Own cloud doesn't display files with names with spaces at the end

### ISSUE THREAD

**Issue by tastle73** [owncloud/core#17350]
I know this is a edge case here, but one of my users reported that a bunch of his files were not syncing to owncloud v 8.0.4 on RHEL7 

We found that the missing files were actually in the /var/www..../data/ directory but had spaces at the end of them.  I don't know how this happened, but when we 'sed'-ed the blanks off the end, they appeared in the web interface and the sync programs.

**Comment by oparoz** [comment]
I've just done 2 tests in the WebGUI

1. Create a file test .txt. The file is correctly stored in the DB cache and is visible, but the HTML is trimming the filename to test.txt

2- Create a file called "test ". The file is correctly stored in the DB cache and is visible. No trimming is taking place.

So it seems the GUI itself doesn't have a problem with those files, unless they're of a specific media type.

Would you mind using [this template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) to describe your problem in more details?

**Comment by PVince81** [comment]
@oparoz I think he meant the desktop sync doesn't work for such files.

**Comment by oparoz** [comment]
@PVince81 I just wasn't sure if the sed happened on the server or on the client side. I just wanted to see if the interface itself had problems with such files.
I imagine those files have an invisible character. That has happened to me before.

**Comment by PVince81** [comment]
I think the web UI trims spaces in file names when displaying them, but internally still uses the correct name in the "data-file" attribute.

Just tried with Webdav on master and it works fine, so should work in the upcoming 8.1 too.
Sync client 1.8.3 works too, upload and download.

**Comment by tastle73** [comment]
Make sure your test has a trailing slash. 
My end user was having trouble with the sync program for osx. Nobody was seeing the files he was adding 


Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone

-------- Original message --------

**Comment by PVince81** [comment]
@tastle73 a trailing slash ? Can you give an example file name ?

I heard that OS X allowed people to add slashes in file names, which internally are actually colons, see https://github.com/owncloud/client/issues/854
I think such files containing colons aren't synced by the client.

**Comment by tastle73** [comment]
I’m sorry, I meant a trailing space.  So a filename with a space at the end of it  
> On Jul 3, 2015, at 11:01 AM, Vincent Petry <notifications@github.com> wrote:
> 
> @tastle73 <https://github.com/tastle73> a trailing slash ? Can you give an example file name ?
> 
> I heard that OS X allowed people to add slashes in file names, which internally are actually colons, see owncloud/client#854 <https://github.com/owncloud/client/issues/854>
> I think such files containing colons aren't synced by the client.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/owncloud/core/issues/17350#issuecomment-118369342>.
> 

Thomas Astle
System Administrator

Physician's Computer Company
20 Winooski Falls Way, Suite 7
Winooski, VT 05404
+1 800.722.7708
tom@pcc.com

**Comment by PVince81** [comment]
I already tried with trailing spaces and it worked fine with sync client 1.8.4.
Which version did that user have ?

**Comment by tastle73** [comment]
I updated them to the latest on the site: 1.8.4 .   I have more clarification.  It seems to be files that are a hop beyond the OC server on a SMB share from a RHEL 6 machine not syncing TO his OS X machine if they have these space characters after the filename.




> On Aug 21, 2015, at 6:48 AM, Vincent Petry <notifications@github.com> wrote:
> 
> I already tried with trailing spaces and it worked fine with sync client 1.8.4.
> Which version did that user have ?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/owncloud/core/issues/17350#issuecomment-133371588>.
> 

Thomas Astle
System Administrator

Physician's Computer Company
20 Winooski Falls Way, Suite 7
Winooski, VT 05404
+1 800.722.7708
tom@pcc.com

**Comment by mmccarn** [comment]
I've been reporting on this issue in this ticket:
https://github.com/owncloud/client/issues/3694
"Damaged folder names prevent completion of client 'discovering' step"

Files or folders with either a leading or trailing space in the name fail to sync.

**Comment by MorrisJobke** [comment]
This seems to be fixed in the client 2.0.2. Please test with an updated client and report back if this is still happening.

Thanks
