### ISSUE TITLE
Move permanent notifications to a new entry in the user menu and add a badge next to the userId

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#17351]
The current notifications implementation works well for instant feedback, but it's not designed for more permanent messages like update notifications.

I propose the creation of a new entry in the user menu and the use of badges, which should be introduced through https://github.com/owncloud/core/issues/15309.

1. User sees the badge next to his name
2. User clicks on menu, sees badge again, next to notifications
3. User clicks on notifications and gets redirected to a notifications summary page. The rationale being that notifications could originate from many different apps (FTP is down, Gallery has been updated, app has been disabled, etc.)
4. User discards notifications he deems to be of no importance or relevance to him.
5. Badges are updated.

I don't think public pages need such notifications.

@jancborchardt @DeepDiver1975

**Comment by oparoz** [comment]
cc @LukasReschke because he thinks app updates are hidden (Agreed!) https://github.com/owncloud/core/issues/17230

**Comment by LukasReschke** [comment]
:+1:

**Comment by PVince81** [comment]
We already have a notification app now in 8.2.2 and 9.0 CC @nickvergessen
