### ISSUE TITLE
Enhanced error handling to enable throwing exceptions.

### ISSUE THREAD

**Issue by aidanamavi** [owncloud/core#17361]
Can we had a function like this to core?
https://github.com/owncloud/news/blob/master/appinfo/app.php#L22

Would be helpful to app developers at the very least.

@brantje @Raydiation and I approve of this message as discussed in #owncloud-dev

**Comment by DeepDiver1975** [comment]
@aidanamavi sounds reasonable - interested in contributing and submit a PR? THX

**Comment by brantje** [comment]
Indeed, i had a blank page when downloading a file.
Turns out i had something wrong with xsendfile.
It was missing xsendfilepath /volume1 
It would be better if that error is logged to owncloud.log

**Comment by PVince81** [comment]
On 10.0 the white page now will contain an exception stack trace if the error happens early, closing.
Ref: https://github.com/owncloud/core/pull/26075
