### ISSUE TITLE
Apps dropdown menus should link to the settings of an app.

### ISSUE THREAD

**Issue by Kawohl** [owncloud/core#17372]
I think it would be a lot more convenient if you could acccess the Settings of an app by clicking a link and you're redirected to the settings of the specific app.

@butonic

**Comment by LukasReschke** [comment]
@jancborchardt

**Comment by DeepDiver1975** [comment]
this is afaik a duplicate - we discussed this many times in the past.

**Comment by jancborchardt** [comment]
I’m not aware of there being any issue in the tracker yet though. And it’s a good point. Having a settings deepling (if there are settings for the app) in the appstore entry (if the app is enabled).

**Comment by PVince81** [comment]
This is the responsibility of every app. It is already possible to link to individual sections using the URL anchor, so apps need to provide a link wherever they can and when it makes sense.

If you had any app in mind, please open a ticket for that app and explain where the link should be.
