### ISSUE TITLE
Bug fixing for 8.2

### ISSUE THREAD

**Issue by cmonteroluque** [owncloud/core#17371]
This issue will have the prioritized list of bugs to work during the 8.2 development schedule. TBD at this point. oC developers, please allocate about 25% of your time during 8.2 to work on this list....

More to come...

**Comment by oparoz** [comment]
What about features?

**Comment by DeepDiver1975** [comment]
> What about features?

The feature list for 8.2 will be published there days.

**Comment by PVince81** [comment]
Why make an issue and list everything here and not simply use the milestone + "Bug" tag ?

**Comment by DeepDiver1975** [comment]
> Why make an issue and list everything here and not simply use the milestone + "Bug" tag ?

It will be a checklist in here kind of what you did with the open locking issues.

**Comment by PVince81** [comment]
So... anything to add to this list ?

**Comment by PVince81** [comment]
@cmonteroluque I guess it's probably time to fill in this ticket ? :wink:

**Comment by DeepDiver1975** [comment]
> @cmonteroluque I guess it's probably time to fill in this ticket ? :wink:

https://github.com/issues?page=13&q=is%3Aopen+user%3Aowncloud+milestone%3A8.2-current+sort%3Aupdated-asc&utf8=%E2%9C%93

**Comment by cmonteroluque** [comment]
nod
