### ISSUE TITLE
File owner by file name

### ISSUE THREAD

**Issue by dud3** [owncloud/core#17376]
## Problem space
Getting file info before downloading it.

## Description
Hi Guys how do we get the info about the file and it's owner, something similar to `$linkItem = Share::getShareByToken($token, false);` where we get the stuff by `token` but this time by the `file name`.

## Summary
How do we distinguish between our file and files shared with us, by other users ? Basically I want to know if I'm downloading my own files or files that are shared with me.

Thanks.

**Comment by dud3** [comment]
Probably someone else made similar or the same request, sorry couldn't find it on the issues.

**Comment by dud3** [comment]
Hmm I think `OCP\Share::getItemSharedWith('file', $files);` should do it, if there's a better way of getting info on a file, please let me know :D>.

**Comment by DeepDiver1975** [comment]
> Hmm I think OCP\Share::getItemSharedWith('file', $file); should do it, if there's a better way of getting info on a file, please let me know :D>.

this should give you the necessary information.

**Comment by dud3** [comment]
+1

**Comment by dud3** [comment]
@DeepDiver1975 I've just tried on another `owncloud` the same method: OCP\Share::getItemSharedWith('file', 'sharedfile.txt'); It just got me an empty array, any ideas ?

BTW: The file is already shared.

**Comment by dud3** [comment]
Any other methods similar to `getItemSharedWith` that would do the job ?

**Comment by dud3** [comment]
Is there a way of getting the owner id from `getFileInfo()` method ?
