### ISSUE TITLE
e-mail notification for app updates

### ISSUE THREAD

**Issue by JKawohl** [owncloud/core#17373]
We are really improving our Notifications on the Webinterface as in #17351, nevertheless i would like to suggest  e-mail notification for app updates.

As soon as app updates are available user/admins should be notified by e-mail about the update.

**Comment by RealRancor** [comment]
Until this is implemented you can already subscribe to your specific apps on apps.owncloud.com to get mail notifications on updates.

**Comment by PVince81** [comment]
There is already code in place that triggers a notification (bell icon) when there are app updates.

Once we make it possible to also send emails for notifications, this will already work.
