### ISSUE TITLE
exclude public shares on external drives from encryption

### ISSUE THREAD

**Issue by Scindix** [owncloud/core#17375]
I have a Dropbox account that has a shared folder in it. I mounted it in my Owncloud via "files_external" as my personal storage (not in the admin section). I also enabled encryption.
A few days ago Owncloud started to encrypt this public folder. The other users of this shared dropbox folder were not amused. Does owncloud check if a Dropbox folder is shared with others before it encrypts it? Is this even possible with the Dropbox API? If not it would be helpful if you could manually exclude a folder from encryption.
I now mounted it in the admin section and made it accessible to a group in which I'm the only member. It doesn't seem to get encrypted now. However I'm not sure if this is reliable and also owncloud doesn't encrypt the rest of the Dropbox anymore (Which I would want to).

**Comment by DeepDiver1975** [comment]
Please wait for 8.1 - encryption can then be enabled/disabled for external storages

**Comment by Scindix** [comment]
@DeepDiver1975 Just to be totally clear: What I request is disabling encryption just for a specific folder. I want my Dropbox to be encrypted! I only want to exclude the shared folder in my Dropbox. Will this also be available in 8.1?

If not than this only partially solves my problem.
This is really important to me. So if this functionality has any chance of ending up in this repository I would dig into the code and fork it.
