### ISSUE TITLE
Expose get path by file id on node interface

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#17385]
Expose `\OC\Files\Filesystem::getPath($fileId);` on the node API.

@icewind1991

**Comment by icewind1991** [comment]
https://github.com/owncloud/core/blob/master/lib/public/files/folder.php#L150

**Comment by PVince81** [comment]
Ok cool, thanks. I was looking for it in the `Root` class.
Actually it's even neater to have it in the `Folder` class.
