### ISSUE TITLE
settings/app is retrieving the wrong version for updates

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#17388]
There is nothing open regarding this issue and it's going to affect every dev who is distributing 2 versions of his app from the app store.

On 8.0, if you ask to get the latest update for your version, you get the default/fallback one, which is probably for 8.1 or even 8.2.

I don't think there is quick fix for this if the ap store is always serving the default version, since switching them up would mean that people on 8.1 would be getting the app for 8.0.

To confirm the issue, simple log your versions here:
https://github.com/owncloud/core/blob/c7968d202f9d825b41cb79ea23787be6891b2b30/lib/private/app.php#L1036

I get `"requireMin 8.1 , localVer 8.0"`

The appstore is returning the correct links when settings is asking about available options.

**Comment by oparoz** [comment]
The query URL for the download link contains a hardcoded value which makes make the app store always return the first link.
`$url = $this->getAppStoreUrl() . '/content/download/' . urlencode($id) . '/1';`
https://github.com/owncloud/core/blob/c7968d202f9d825b41cb79ea23787be6891b2b30/lib/private/ocsclient.php#L311

**Comment by LukasReschke** [comment]
> I don't think there is quick fix for this if the ap store is always serving the default version, since switching them up would mean that people on 8.1 would be getting the app for 8.0.

This is what https://github.com/owncloud/core/issues/17101#issuecomment-117398494 is supposed to do. When a version is sent (which 8.0.5 is doing) then the appstore is supposed to return only compatible versions.

If this is implemented yet: No idea.

cc @karlitschek

**Comment by oparoz** [comment]
Thanks. I've looked at the commits in core and it seems at one point, the ocsclient was supposed to pick the proper url (/1, /2, etc.), but that would require waiting for new versions of oC where as fixing the backend would make it work for everyone, so :fingers_crossed:

**Comment by oparoz** [comment]
An update on the situation
* Gallery from the app store doesn't show a version any more and can't be updated
* Enabled Gallery shows the old version
* The XML only shows one version and it's the one for 8.1, so that may be why there is no update being offered
* The download URL now works with versions and picks the correct archive. Great!

At least now users are not presented with an update they can't apply. Still hoping they'll be able to upgrade soon :)

**Comment by DeepDiver1975** [comment]
@oparoz you have to specify the app version with the downloads in the appstore. This was added last night and meanwhile tested with contacts.

Please test with Gallery an let me know. Thanks

**Comment by oparoz** [comment]
@DeepDiver1975 - Indeed, the link works, but the settings page itself is not seeing an update on 8.0. I just read on IRC that people are also having issues on 8.1, but that it should work.

Should I change the milestone to 8.0.5 since I read from @jospoortvliet that an upgrade will be required for this to work on 8 and 7?

**Comment by karlitschek** [comment]
@oparoz Do you have a link to the gallery antry on apps.owncloud.com? I guess the version number is missing as pointed out by @DeepDiver1975

**Comment by oparoz** [comment]
@karlitschek - Maybe the patch that has been applied is assuming 8.0 to be listed first, but I did the opposite.

![gallery_versions](https://cloud.githubusercontent.com/assets/323220/8545760/f49cb4e8-24b1-11e5-9d26-339a32054dd1.png)

**Comment by oparoz** [comment]
Ahhh... Looking at the screenshot, I see the version field! My bad!

**Comment by oparoz** [comment]
So, @DeepDiver1975 @karlitschek, the app version now appears in settings. Only thing missing is the update button.

**Comment by oparoz** [comment]
Is the fix in 8.0.5 or do people have to wait for 8.0.6 to be able to upgrade from ownCloud directly?

**Comment by oparoz** [comment]
OK, so on 8.0.5, updates fail, but after a few logout/logins, it's possible to enable the apps, so I'm closing this.
