### ISSUE TITLE
8.1.0 ship with “ownCloud 8.2” documentation

### ISSUE THREAD

**Issue by DavidPrevot** [owncloud/core#17389]
Hi,

The admin and user documentation from the tarball of the just tagged 8.1.0 claims it is related to ownCloud 8.2.

**Comment by DeepDiver1975** [comment]
@cmonteroluque packaging issue? Can I ask you to have a look? THX

**Comment by DeepDiver1975** [comment]
@jnfrmarks something for the test plan - please add - THX

**Comment by jnfrmarks** [comment]
Do we need this resolved before shipping?

@cmonteroluque @carlaschroder @DeepDiver1975

**Comment by karlitschek** [comment]
There was indeed something missing in the scripts to use the new stable8.1 branch in the documentation repo. This is fixed now.
Opinions if we should redo the packages to fix this?
Just to be clear. The content of the documentation should be 99.9% the same. It is mainly about the version number that shows up in the documentation.
And next time we should make sure to catch this error a bit earlier in the cycle. ;-)

**Comment by DavidPrevot** [comment]
Hi,

Le 03/07/2015 20:33, Frank Karlitschek a écrit :

> And next time we should make sure to catch this error a bit earlier in the cycle. ;-) 

FWIW, that was the main goal of this bug report.

Regards

David

**Comment by DeepDiver1975** [comment]
8.1.1 no need to overreact. Have a nice weekend.

**Comment by DeepDiver1975** [comment]
@rperezb can you please verify this is fixed with the daily packages? Furthermore this should be double checked with RC1 of 8.1.1 - THX

**Comment by rperezb** [comment]
@DeepDiver1975 thx, added to the regression test

**Comment by rperezb** [comment]
@owncloud/qa

**Comment by jvillafanez** [comment]
Checked with 8.1.0 (daily) Build:2015-07-20T03:17:48+00:00 6383bd3744b4773e239c576e2af8d96be197472d  shows 8.1 documentation

**Comment by DeepDiver1975** [comment]
THX @jvillafanez
