### ISSUE TITLE
Emptycontent message often visible below loading spinner when switching categories

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#17393]
When refreshing the page or in a new browser session, the emptycontent is often shown below the loading spinner for the categories of the files sidebar.

Now seeing »No files shared with you« or »No favorites yet« when you know there are some makes you really worry. They appear after the loading, but this is really not clean. The emptycontent should not show while the loading is going on.

cc @owncloud/designers @PVince81

**Comment by jancborchardt** [comment]
This results in quite a bad UX, feeling for a second that your files are gone. We need to fix and backport this. @PVince81 @DeepDiver1975

**Comment by PVince81** [comment]
This fixes it: https://github.com/owncloud/core/pull/18125
