### ISSUE TITLE
Updates between multiple major versions are unsupported.

### ISSUE THREAD

**Issue by ottochili** [owncloud/core#17396]
I wanted to update owncloud for Qnap from Version 6 to Version 8.0.4. but this seems to be unsupported. message: Updates between multiple major versions are unsupported.
Is there a how to?

**Comment by LukasReschke** [comment]
Download a ownCloud 7 release from https://owncloud.org/changelog/ first and then do 6 -> 7 -> 8

**Comment by RealRancor** [comment]
Also make sure you're firs updating to the latest 6.0.x first
