### ISSUE TITLE
First run experience: Missing emptycontent icon for share categories

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#17392]
I tried to debug this before but couldn’t find the reason. The share icon in the emptycontent is missing, even though the class is set:
![capture du 2015-07-04 01-02-21](https://cloud.githubusercontent.com/assets/925062/8505516/74aeefa6-21e8-11e5-832d-55a721b59981.png)

cc @PVince81 @owncloud/designers @schiesbn

**Comment by rullzer** [comment]
@jancborchardt could you recheck... the icon shows up here.

**Comment by jancborchardt** [comment]
Hm, I guess it’s maybe just a problem specific to my setup. If no one else can reproduce, I’ll close it.

**Comment by jancborchardt** [comment]
I could reproduce this on an install on a completely different server (helping a friend installing). First install does not show the sharing icon in the emptycontent placeholder. No idea why – does not seem to be a design issue.

@owncloud/designers can you test?

**Comment by PVince81** [comment]
Cannot reproduce on master.

Next time you see it happening, please use the DOM inspector and inspect the icon. Then check the network console and see whether the icon got a 200 ok or maybe 404.

**Comment by jancborchardt** [comment]
Right, thanks for the hint. Will do that next time.
