### ISSUE TITLE
»Server status« entry problems

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#17395]
In the navigation it’s above the Tips & tricks, in the list it’s below:
![capture du 2015-07-04 01-24-09](https://cloud.githubusercontent.com/assets/925062/8505614/b37aecc8-21eb-11e5-9223-f6868eb266db.png)
Let’s put it below in the navigation as well @DeepDiver1975 @PVince81 

Also: Correct capitalization please! »Server status« – only the first word is capitalized as all the other items.

And not to mention that this section seems completely useless. What does it want to tell me? How can I enable »Transactional File Locking«? Please next time something like this is introduced at least _try_ to let me know.

**Comment by DeepDiver1975** [comment]
@jancborchardt pull requests are welcome - THX
