### ISSUE TITLE
Memcached - Error - Invalid Keys

### ISSUE THREAD

**Issue by ofriedrich** [owncloud/core#17397]
The memcache-extension of owncloud uses keys "as they are". This may result in errors in some cases (see example). A workaround could be, to hash keys. See lib/private/memcache/memcached.php

Test example:
```php
<?php
$key = 'octipkt3b48c/routemydomain.de#/mycloud/index.phpcore_ajax_public_preview{"file":"\/Bildschirmfoto 2015-06-05 um 14.17.15.png","t":"QdKkVHMo7WfFA6r","y":1024,"x":1024}';
$mc = new Memcached();
$mc->addServer("127.0.0.1", 11211);
// This works
$mc->set(hash('crc32', $key), 'MY TEST') or die ("Failed to save data at Memcached server with hashed key");
// This does not work
$mc->set($key, 'MY TEST') or die ("Failed to save data at Memcached server without hashed key");
```

**Comment by LukasReschke** [comment]
I predicted that this will cause problems already in March at https://github.com/owncloud/core/issues/14950. Also stuff such as https://github.com/owncloud/core/issues/14185

cc @DeepDiver1975 @karlitschek Either we _really_ should have proper QA on all of our supported memcaches or we should drop unsupported ones. If we can't ensure proper QA then we should use Stash or another library that can take care of such stuff.

**Comment by LukasReschke** [comment]
@cmonteroluque We should resolve this before EE release as 8.1 introduced a lot of new caching which _will_ lead to problems.

**Comment by LukasReschke** [comment]
Also see https://github.com/owncloud/enterprise/issues/567

**Comment by ofriedrich** [comment]
I've fixed this temporary by adding the following line to the related methods:
```php
$key = hash('crc32', $key);
```
Really simple and it works.

**Comment by LukasReschke** [comment]
Yes - but this will solve only the memcached PR and I suspect others have other problems.

PR welcome! :smile:

**Comment by LukasReschke** [comment]
CRC32 seems also quite problematic with regard to collisions: http://preshing.com/20110504/hash-collision-probabilities/ - let's better go with sha256 or sha512.

**Comment by Xenopathic** [comment]
Gotta say, Stash looks really awesome. It's just a shame it doesn't support compare-and-set or other more advanced methods.

**Comment by karlitschek** [comment]
Agreed. This needs attention,

**Comment by jknockaert** [comment]
Adding to this discussion I wanted to make the point while memcached is generally used as caching backend for distributed data (memcache.distributed), it can also be used for locally stored data (memcache.local). Latency is not really an issue when using a socket rather than tcp. And memcached is much more stable than the apcu that comes with Ubuntu 14.04 (and which is not supported in OC). So I think there is a good case for fully supporting memcached.

**Comment by DeepDiver1975** [comment]
moving to 8.1.2

**Comment by cmonteroluque** [comment]
@DeepDiver1975 Not sure who's handling this

**Comment by DeepDiver1975** [comment]
Discussions and analysis in the past weeks did show that we need a bigger change to fix this.
Given the state of 8.2 this is more a topic for 9.0.

Solution: move to http://www.stashphp.com/

**Comment by MorrisJobke** [comment]
> Solution: move to http://www.stashphp.com/

* [ ] verify that owncloud/core#18849 won't happen with stash

**Comment by Xenopathic** [comment]
@MorrisJobke I had a poke through the code of Stash - it doesn't support the `clear($prefix)` method like we do, so our code would need to change. It only supports a total flush, not flush with key prefix.

Side note: if we hash our keys before storing them in the memcache, we can't flush by key prefix anyway...

**Comment by MorrisJobke** [comment]
@Xenopathic Yes, this was just a note to not forget what needs to be done if we want to move this way. Nothing we should care about now.

**Comment by DeepDiver1975** [comment]
let's throw exceptions in case a too long key is used
