### ISSUE TITLE
Send password/activation link to new user

### ISSUE THREAD

**Issue by tflidd** [owncloud/core#17398]
An e-mail can be sent to new users. It makes absolutely no sense that the password is not included since users can reset their passwords. This leads to rather strange user creation procedures:
https://forum.owncloud.org/viewtopic.php?f=21&t=29055#p90693 (in german)

@enoch85 already proposed this idea:
https://github.com/owncloud/core/issues/12603#issuecomment-66285419

**Comment by Xenopathic** [comment]
cc @MorrisJobke @LukasReschke @jancborchardt

**Comment by RealRancor** [comment]
Sending Passworts via E-Mail is a absolutely no-go but maybe the mail could contain a link like the lost password page where they can set their own password.

**Comment by MorrisJobke** [comment]
Sending a link that then shows a page to allow the user to set it's own password is a proper way to handle this "create a user" feature.

**Comment by RealRancor** [comment]
Yes, i think this is the only acceptable solution for this.

**Comment by jancborchardt** [comment]
What @MorrisJobke said. The one-time-password solution is just a complicated version of the easy link-to-set-own-password method.

**Comment by LukasReschke** [comment]
Agreeing with @MorrisJobke and @jancborchardt here.

**Comment by MorrisJobke** [comment]
00005462

**Comment by PVince81** [comment]
seems there is a PR with this: https://github.com/owncloud/core/pull/18485

**Comment by tedstrauss** [comment]
Subscribing.
Would love to have this feature on OC 8.

**Comment by PVince81** [comment]
@pmaier1 for scheduling. There is a PR already that needs to be revived / finalized: https://github.com/owncloud/core/pull/18485.

**Comment by PVince81** [comment]
@imujjwal96 would you like to work on this ? You already have a lot of experience now with password reset and emailing 😄 (it's ok if you don't)

**Comment by imujjwal96** [comment]
I am kinda busy with my University exams right now. I hope you wouldn't mind if I send a PR by the weekend.

**Comment by PVince81** [comment]
There is absolutely no urgency, so up to you. Just thought you might be
interested

**Comment by PVince81** [comment]
already implemented in some other form in 10.0.10
