### ISSUE TITLE
Admin settings navigation entry for »Security & setup warnings« missing

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#17394]
See:
![capture du 2015-07-04 01-07-59](https://cloud.githubusercontent.com/assets/925062/8505534/2fa79fa6-21e9-11e5-8a46-922e78ec3652.png)

There obviously are setup warnings, but the navigation entry is missing. @DeepDiver1975 @PVince81

**Comment by DeepDiver1975** [comment]
seems to be fixed in master - cannot reproduce
