### ISSUE TITLE
Better feedback during update process

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#17391]
This update screen has no immediately visible feedback:
![owncloud update spinner](https://cloud.githubusercontent.com/assets/925062/8505357/b2be70f0-21e3-11e5-8191-10a1dc3db296.png)

Just needs a simple .icon-loading-dark below the text. It should also be there when you are about to be redirected. cc @LukasReschke @MorrisJobke @owncloud/designers

**Comment by LukasReschke** [comment]
What does the text say? - Please use English or explain what update screen exactly as lazy devs as me are not really keen to lookup the translation first :speak_no_evil:

**Comment by jancborchardt** [comment]
»Update to ownCloud 8.1.0 in progress. This can take some time«

**Comment by PVince81** [comment]
Sometimes there isn't directly a redirect but a box that shows the progress.
I agree that there should be a spinner anyway in both cases.

**Comment by jancborchardt** [comment]
@VicDeo @DeepDiver1975 it would be good to know by the way how the updater goes along in regards to design. Any … update here? Will it basically be the same, or entirely new?

**Comment by VicDeo** [comment]
@jancborchardt entirely new
![updater](https://cloud.githubusercontent.com/assets/991300/13255844/23eb8352-da59-11e5-93e9-737aa680d5f5.png)

**Comment by jancborchardt** [comment]
Ah, cool. Opened an issue about the design directly in the repo: https://github.com/owncloud/updater/issues/250

**Comment by MorrisJobke** [comment]
@jancborchardt The current web update step you posted above has now a lot more detailed output that clearly highlights the current state. I would rate this fixed. @jancborchardt Just try an update of 8.2 to 9.0 ;)

Please open more specific issues otherwise.

**Comment by jancborchardt** [comment]
@MorrisJobke as said – we moved the discussion to an issue in the updater repo. ;)
