### ISSUE TITLE
Upgrade 7.0.6->8.0.4 failed

### ISSUE THREAD

**Issue by rnalrd** [owncloud/core#17409]
PostgreSQL 9.4 is the backend

test:/usr/share/webapps/owncloud# ./occ upgrade
Turned on maintenance mode
An exception occurred while executing 'CREATE UNIQUE INDEX 3sibnkcwcpoj2 ON mimetypes_usv389y2sqx3f ("mimetype")':

SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "3"
LINE 1: CREATE UNIQUE INDEX 3sibnkcwcpoj2 ON mimetypes_usv389y2sqx3f...
                                                      ^
Turned off maintenance mode
Update failed

test:/usr/share/webapps/owncloud# cat /etc/owncloud/config.php
<?php
$CONFIG = array (
  'datadirectory' => '/var/lib/owncloud/data',
  'dbtype' => 'pgsql',
  'version' => '7.0.6.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => '',
  'dbuser' => 'owncloud',
  'dbpassword' => '%obfuscated%',
  'installed' => true,
  'loglevel' => '0',
  'instanceid' => '%obfuscated%',
  'versions' => 'false',
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' => 
  array (
    0 => 'localhost',
  ),
  'appstoreenabled' => false,
  'share_folder' => '/Shared',
  'mail_from_address' => '%obfuscated%',
  'mail_smtpmode' => 'php',
  'mail_domain' => '%obfuscated%',
  'secret' => '%obfuscated%',
);

Thanks!

**Comment by PVince81** [comment]
I see you don't have a table prefix, and the generated index name starts with a 3 ("3sibnkcwcpoj2") which can happen.

Looks like supporting empty prefix is buggy.

**Comment by PVince81** [comment]
@DeepDiver1975 did we talk about enforcing a database prefix before ?

**Comment by DeepDiver1975** [comment]
AFAIK this will be fixed with the next maintenance releases

**Comment by DeepDiver1975** [comment]
@rnalrd 7.0.7 and 8.0.5 will be releases soon-ish (technically speaking tomorrow) - please wait for these releases
