### ISSUE TITLE
Add view people involve in the shared file/folder

### ISSUE THREAD

**Issue by jack05ryan02** [owncloud/core#17402]
Hi,

First, thank you for ownCloud, it's a very cool replacement for dropbox.  I just have an issue which is stated here:
https://forum.owncloud.org/viewtopic.php?f=31&t=29083

Hope someone can help.

Thanks.

**Comment by PVince81** [comment]
So if I understand well what you suggested is:
1. "user1" shares folder "test" with "user2" and "user3"
2. When opening the share dropdown, "user2" can see that both "user1" and "user3" have access to the folder.

Is that correct ?

Then there's the question what happens when the option "Only allow sharing with users in the same group" is enabled. Should users be able to see what users from **other** groups have access or only users from their own groups ?

Currently due to the way how reshares create a sharing chain this won't be possible.
Requires https://github.com/owncloud/core/issues/9058 first.

@MTRichards

**Comment by PVince81** [comment]
also @owncloud/designers

**Comment by jack05ryan02** [comment]
1. "user1" shares folder "test" with "user2" and "user3"
2.  Currently when opening the share dropdown, "user2" can only see "Shared by user1".  It would be cool if "user2" can see on the share dropdown that "user1" and "user3" has also access to the folder.  same goes to "user3" where he can also see "user1" and "user2" has access to the folder.  this is present on dropbox which is not on owncloud.

To answer your question on item number 2, yes, that is correct.  Users should be able to who are the people who have access to the shared folder regardless of the group.

**Comment by jancborchardt** [comment]
Yup, definitely. Also when resharing, the info is completely unclear. I thought we already had an issue for this but can’t find anything. I consider this high priority to make sharing more usable. cc @MTRichards 

This is also related to »Design forward: Sharing dialog«: https://github.com/owncloud/core/issues/3224

**Comment by jack05ryan02** [comment]
thanks guys for the great work.  this is really a cool replacement for dropbox.  will be waiting for the feature that will allow users to view who has access to the shared file/folder as this will be really useful especially when there are already lots of users.

**Comment by MorrisJobke** [comment]
This is completely covered by #9058:

> As an ownCloud user, I want people with reshare privileges on a file or folder that I have shared with them to be able to reshare that with other users, and I want those "reshared" recipients to appear in my shared to list, so that myself - and everyone that the file is shared with - knows who has access to the file.

Closing this as duplicate. Feel free to add comments over there.

**Comment by jack05ryan02** [comment]
great! thank you for fixing the issue.  it seems that the issue is still present on version 8.1.  just to verify, issue is fixed on 8.2?

thanks.

**Comment by MorrisJobke** [comment]
> great! thank you for fixing the issue.

Sadly it's not fixed. It's just a issue, that is already tracked in another issue. And to remove duplicate open issues I closed this one in favour of the other. Nevertheless it is planned for the 8.2 to implement such a feature. If it in the end went into the version can't be said that early in the development process.

**Comment by jack05ryan02** [comment]
oh okay. will just wait for the fix then. thanks for the great work.
