### ISSUE TITLE
Webinterface should show error message: User not found

### ISSUE THREAD

**Issue by Kawohl** [owncloud/core#17408]
Steps to reproduce:

Use Webinterface to share a file/folder.

Type in an username that is not existing.

Current behaviour:

You type in the fictional username and no error message is shown when you hit Enter.
 
Expected behaviour:

The web-interface should display an error Message: "Username" doesn´t exist. Check your spelling?

![bildschirmfoto 2015-07-06 um 11 36 27](https://cloud.githubusercontent.com/assets/12275313/8519628/5a07f6c8-23d4-11e5-96b8-e12c24d2d826.png)

**Comment by Julian1998** [comment]
@jancborchardt What is a good error message?

Red color - User doesn't exist

Any suggestions? ;)

**Comment by jancborchardt** [comment]
@Julian1998 thanks for picking this up! A good error message is the same as I mentioned in https://github.com/owncloud/core/issues/8517 – should ideally appear as the dropdown where normally the name suggestions are shown.

**Comment by Julian1998** [comment]
@jancborchardt But do we really need a message. I mean you know that there is no user existing if there is no content.... ;)

**Comment by MorrisJobke** [comment]
@PVince81 I just got asked where to find the rendering of the user list. Do you know by any change out of your head where this is?

**Comment by PVince81** [comment]
In 9.0 it's moved to the sidebar, the code is here: https://github.com/owncloud/core/blob/master/core/js/sharedialogview.js#L21 and the sharee (recipient) list here https://github.com/owncloud/core/blob/master/core/js/sharedialogshareelistview.js#L17

**Comment by jancborchardt** [comment]
@Julian1998 yes, the message is necessary because no content could also mean that there is a system error, or no connection. Showing nothing is confusing, there always needs to be proper feedback. :)

**Comment by Julian1998** [comment]
@jancborchardt @PVince81 @MorrisJobke  Thx :)

**Comment by Julian1998** [comment]
@MorrisJobke @PVince81 
Problem: How to use sth to show the error

My solution at the moment:
if (suggestions.length > 0) {
    $('.shareWithField').autocomplete("option", "autoFocus", true);
    response(suggestions);
} <b>else {
    //TODO Design
    OC.Notification.show(t('core', 'No users or groups found for ' + $('.shareWithField').val()));
    window.setTimeout(OC.Notification.hide, 1000);
    response();
}</b>

source: core/js/sharedialogview.js

Can you help me :$

**Comment by PVince81** [comment]
`OC.Notification.showTemporary(message)`

**Comment by Julian1998** [comment]
@PVince81
But I need the Error Message in the filesharewith tab

**Comment by Julian1998** [comment]
Response shows the tab
But is not compatible with a String parameter

**Comment by jancborchardt** [comment]
As said above ideally the error should be shown in the dropdown directly instead of as a showNotification – because that is too far away to be noticed, we can integrate it more nicely here.

**Comment by PVince81** [comment]
@Julian1998 then you might want to look at making it a tooltip instead and showing the field in red.
See how it's done when password is wrong: https://github.com/owncloud/core/blob/master/core/js/sharedialoglinkshareview.js#L197

**Comment by MorrisJobke** [comment]
Adding 9.0 because #22319 was added to 9.0

**Comment by rullzer** [comment]
Fixed with #21837
