### ISSUE TITLE
Switching to admin page: The top Icon is named Apps

### ISSUE THREAD

**Issue by Kawohl** [owncloud/core#17410]
Steps to reproduce:
1. Login as admin.
2. Switch to the admin panel on the upper right.

Current behaviour: The button on the top left says "Apps".

Expected behaviour: The Button on the top left should say something like "Admin settings, log"

![bildschirmfoto 2015-07-06 um 11 52 57](https://cloud.githubusercontent.com/assets/12275313/8519895/3f0d8a34-23d6-11e5-828a-2bf869ca2ec2.png)
![bildschirmfoto 2015-07-06 um 11 50 30](https://cloud.githubusercontent.com/assets/12275313/8519898/423fe616-23d6-11e5-9d34-01bdf46f6c24.png)

Edit:
Owncloud version 8.04 community. fresh install.
Browser: Google Chrome

**Comment by LukasReschke** [comment]
Thanks a lot for reporting issues back to us!

We need some more information to properly support you with your issue!

Can I ask you to follow our guidelines for submitting bugs as described here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

---

Missing: ownCloud version, etc…

**Comment by RealRancor** [comment]
I think there is at least one duplicate for this but i can't find it at the moment.

**Comment by MorrisJobke** [comment]
I think this was by intention. @jancborchardt Want to show that you can reach the apps up there. But it feels inconsistent, because every other app lists it's name up there.

**Comment by LukasReschke** [comment]
Why I asked for the version:
![2015-07-06_14-38-47](https://cloud.githubusercontent.com/assets/878997/8522294/c035b288-23ec-11e5-92d5-a026508b3208.png)

**Comment by LukasReschke** [comment]
I believe this has been fixed with https://github.com/owncloud/core/pull/16888. This is not a big bug and thus should be closed from my POV.

**Comment by MorrisJobke** [comment]
Was fixed in 8.1 -> close
