### ISSUE TITLE
Heavy client bandwidth usage

### ISSUE THREAD

**Issue by dzecchin** [owncloud/core#17423]
Team,

I have installed owncloud in our web server last week. In order to test it, I have synchronized only one folder of my local computer with several files. In total, they occupy around 40mb. I have been working on the weekend in some of them and using Windows client over XP to have this work being replicated in the server and another computer. All the files I have edited are less than 1Mb and each save was made approximately half an hour from each other. So there was a lot of inactivity time besides each modification. The client was running all the weekend in both computers (both with MS Win XP). 

Today I examined the bandwidth usage in our server and it was too high, having three days over 1Gb. The server it is only running owncloud and all the connections were from my computers. Some screen captures follows:

![photo_2015-07-06_20-38-04](https://cloud.githubusercontent.com/assets/13054995/8535729/f60c3fc6-241e-11e5-9f8a-5059fe68d0b1.jpg)

![photo_2015-07-06_20-39-36](https://cloud.githubusercontent.com/assets/13054995/8535746/306466bc-241f-11e5-9f38-de41b1b2f0cd.jpg)

Also I have checked every connection in a hour and I have noticed that there were around of 4 and 6 connections by minute (polling to get new updates) from each computer when both are idle (no savings or modifications). This it is fine, since the bandwidth consumed in an hour was about 10 Kb. However, the behavior showed by the captures indicates that there is a symptom of hanging or something related. 

The server installation I have made it is using slqlite and today I noticed that the fileinfo php's module was disabled (now is active). Also, we use only HTTP mode, no SSL enabled. The version installed it is the last: 8.0.4.

The client version is the latest too, 1.8.3.5250.

Our server data:

Apache Version: 2.2.29
PHP Version: 5.4
Architecture: x86_64
OS: linux

Please let me know if you need any information to complete this report. Unfortunately, I do not have bandwidth usage log from any of my computers and actually I have closed both clients to monitor bandwidth server usage.

Thanks in advance.

**Comment by karlitschek** [comment]
This is unusual. I would suggest to check the Desktop Client activity log to see if maybe something is constantly syncing. If something goes wrong with your replication then it is possible that the mtimes on the server change and then owncloud would detect this as changes and constantly sync down the files.
But this is only speculation. 
But at this time I guess that this is a setup issue and not an owncloud bug. So please post this question at forum.owncloud.org
Thanks a lot.
