### ISSUE TITLE
admin page in 8.1 design is broken

### ISSUE THREAD

**Issue by Kawohl** [owncloud/core#17428]
### Steps to reproduce
1.Create fresh install of 8.1
2.Go to admin page and scroll down to the sections: antivirus behaviour and tipps and tricks,

### Expected behaviour
These sections should have the same padding as the others

### Actual behaviour
They are indented all the way to the left

![bildschirmfoto 2015-07-07 um 09 45 41](https://cloud.githubusercontent.com/assets/12275313/8541338/ad6bf738-248d-11e5-86a2-ba6c0040335c.png)
![bildschirmfoto 2015-07-07 um 09 46 33](https://cloud.githubusercontent.com/assets/12275313/8541362/d563ae48-248d-11e5-8c86-71353f13e927.png)

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS
**Web server:**
Apache2
**Database:**
Mysql
**PHP version:**
PHP 5.5.9-1ubuntu4.11 (cli) (built: Jul  2 2015 15:23:08)
**ownCloud version:** (see ownCloud admin page)
8.1
**Updated from an older ownCloud or fresh install:**
fresh install
**List of activated apps:**
Enabled:
 - activity: 2.0.1
 - files: 1.1.9
 - files_antivirus: 0.4.2
 - files_external: 0.2.3
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - search_lucene: 0.6.0
 - templateeditor: 0.1
**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => 'won.der.ful.ip',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'myurl',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_root',
  'dbpassword' => '',
  'logtimezone' => 'UTC',
  'installed' => true,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Google Chrome 43.0.2357.130 (64-bit), Safari Version 8.0.6 (10600.6.3)
**Operating system:**
Mac OSX 10.10.3

**Comment by PVince81** [comment]
@Kawohl can you confirm that you have the latest code from the antivirus app ? I see that the latest version is 0.7.0 here https://github.com/owncloud/files_antivirus/blob/master/appinfo/version. But maybe it wasn't published yet in the app store, @VicDeo ?

**Comment by PVince81** [comment]
The tipps app probably has the same issue and is not up to date.

**Comment by Kawohl** [comment]
This seems  to be the matter.

The antivirus app provided by the installation is v. 0.42

![bildschirmfoto 2015-07-07 um 10 21 38](https://cloud.githubusercontent.com/assets/12275313/8541936/0aca696a-2492-11e5-8ed3-4524b6cf2d59.png)

This is probably also the issue with tipps and tricks

**Comment by PVince81** [comment]
@Kawohl how did you install 8.1 ? Using tarballs or DEB packages ? Could be a packaging issue ?

**Comment by DeepDiver1975** [comment]
Antivirus   0.4.2 is the latest version on the appstore - we should update it @VicDeo

**Comment by Kawohl** [comment]
I installed from the testing Repo with DEB Packages. The Antivirus app is not packaged but pulled from the appstore after activating the antivirus app. 

The app is outdated.

@karlitschek

**Comment by MorrisJobke** [comment]
@Kawohl Having the dots of the list in the tips and tricks section is by intention. cc @jancborchardt

**Comment by Kawohl** [comment]
@MorrisJobke 
It just looks like as if it was wrong to me, since all others are  padded to the right. We looked at 8.1 with a few users last night, and they also mentioned this as an (of course minor) issue.

**Comment by jancborchardt** [comment]
The antivirus app should work since it uses the `.section` class and a h2: https://github.com/owncloud/files_antivirus/blob/master/templates/settings.php

The hanging bullet points are that way so the text is flush with the rest. See http://www.markboulton.co.uk/journal/five-simple-steps-to-better-typography-part-2

**Comment by DeepDiver1975** [comment]
> The antivirus app should work since it uses the .section class and a h2: https://github.com/owncloud/files_antivirus/blob/master/templates/settings.php

This is related to the stone age antivirus app in the appstore - it's dead - even not updatable because the app was uploaded without ocsid - as a result we cannot recognize updates. :boom:

**Comment by karlitschek** [comment]
O.K. Can someone disable the old antivirus app? or even better, replace it with the new and working one?

**Comment by jancborchardt** [comment]
Is it this one? https://apps.owncloud.com/content/show.php/Antivirus?content=157439

If so, can’t we replace it? Otherwise I guess we can close this issue?

**Comment by DeepDiver1975** [comment]
> O.K. Can someone disable the old antivirus app? or even better, replace it with the new and working one?

I can push the 8.1 version today - but this will only help on new installations. Updates will never be triggered.

**Comment by DeepDiver1975** [comment]
v0.7.0 is now active on the appstore - can anybody please test? THX

https://apps.owncloud.com/content/show.php?content=157439

**Comment by Kawohl** [comment]
The antivirus updated itsself to v.0.7.0 then i turned it off and tried to activate it again.

Then i got this:

![bildschirmfoto 2015-07-07 um 10 21 38](https://cloud.githubusercontent.com/assets/12275313/8546035/82995416-24b4-11e5-92ec-86c45ffe5ac0.png)

**Comment by DeepDiver1975** [comment]
@Kawohl this is in the installed old version - please kill that one with fire

the app from the appstore is listed in the tools category

**Comment by Kawohl** [comment]
I took it from the tool category and the result was the upper failure.

**Comment by DeepDiver1975** [comment]
Can please somebody add a faceplam meme in here? THX

**Comment by Kawohl** [comment]
Sorry I don't get it, :still I'm new to all of this and learning.

**Comment by DeepDiver1975** [comment]
> Can please somebody add a faceplam meme in here? THX

@Kawohl no worries this ^^^ was pure developer jokes in madness during the release - sorry for the confusion.

I'll update the app in a minute or two

**Comment by DeepDiver1975** [comment]
@Kawohl please test again - THX a lot!

**Comment by Kawohl** [comment]
Now it works fine!

Thanks a lot!
