### ISSUE TITLE
Missing public API \OC_Helper::mimetypeIcon

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#17421]
Where should we put this one?

- Create an \OCP\IHelper
- Add it to IUrlGenerator

@MorrisJobke @PVince81

**Comment by rullzer** [comment]
I already started on this some time ago in #15543 
That needs cleaning up. I'll look into it soonish.

**Comment by MorrisJobke** [comment]
Available in master: https://github.com/owncloud/core/blob/b5ea97ef817cc2b33269f4518727db259ec6c960/lib/public/files/imimetypedetector.php#L77
