### ISSUE TITLE
Adding a user to a group does not manipulate the user count

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#17420]
Same for removing.

Found while working on https://github.com/owncloud/core/issues/17260

### Steps to reproduce
1. Create a new user
2. Create a new group
3. Add a user to a group

### Expected
Group has user count "1"

### Actual
Group has no user count

PS: works fine on 7.0, it's broken since 8.0

**Comment by PVince81** [comment]
Still happening in 8.2 beta.

**Comment by cmonteroluque** [comment]
This issue will fall off 8.2 if not resolved by 6 Oct
