### ISSUE TITLE
occ and machinereadability

### ISSUE THREAD

**Issue by Kawohl** [owncloud/core#17427]
### Steps to reproduce
1.Use fresh install of owncloud 8.1
2.go to /var/www/owncloud (on ubuntu)
3.sudo -u www-data php occ

### Expected behaviour
In the List it should show a possible command to make the commands machinereadable

### Actual behaviour
ownCloud version 8.1.0

Usage:
 [options] command [arguments]

Options:
 --help (-h)           Display this help message
 --quiet (-q)          Do not output any message
 --verbose (-v|vv|vvv) Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
 --version (-V)        Display this application version
 --ansi                Force ANSI output
 --no-ansi             Disable ANSI output
 --no-interaction (-n) Do not ask any interactive question

Available commands:
 check                           check dependencies of the server environment
 help                            Displays help for a command
 list                            Lists commands
 status                          show some status information
 upgrade                         run upgrade routines after installation of a new release. The release has to be installed before.
app
 app:check-code                  check code to be compliant
 app:disable                     disable an app
 app:enable                      enable an app
 app:list                        List all available apps
background
 background:ajax                 Use ajax to run background jobs
 background:cron                 Use cron to run background jobs
 background:webcron              Use webcron to run background jobs
db
 db:convert-type                 Convert the ownCloud database to the newly configured one
 db:generate-change-script       generates the change script from the current connected db to db_structure.xml
encryption
 encryption:disable              Disable encryption
 encryption:enable               Enable encryption
 encryption:list-modules         List all available encryption modules
 encryption:set-default-module   Set the encryption default module
 encryption:status               Lists the current status of encryption
files
 files:cleanup                   cleanup filecache
 files:scan                      rescan filesystem
l10n
 l10n:createjs                   Create javascript translation files for a given app
maintenance
 maintenance:mode                set maintenance mode
 maintenance:repair              repair this installation
 maintenance:singleuser          set single user mode
user
 user:add                        adds a user
 user:delete                     deletes the specified user
 user:lastseen                   shows when the user was logged it last time
 user:report                     shows how many users have access
 user:resetpassword              Resets the password of the named user

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS
**Web server:**
Apache2
**Database:**
MYSQL
**PHP version:**
PHP 5.5.9-1ubuntu4.11 (cli) (built: Jul  2 2015 15:23:08) 
**ownCloud version:** (see ownCloud admin page)
8.1
**Updated from an older ownCloud or fresh install:**
fresh install
**List of activated apps:**

Enabled:
 - activity: 2.0.1
 - files: 1.1.9
 - files_antivirus: 0.4.2
 - files_external: 0.2.3
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - search_lucene: 0.6.0
 - templateeditor: 0.1

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => '',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://xx.xx.xx.xx/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_root',
  'dbpassword' => 'xxxxxxx',
  'logtimezone' => 'UTC',
  'installed' => true,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

@MorrisJobke

**Comment by DeepDiver1975** [comment]
EDIT: remove dbpassword and server ip :see_no_evil:

**Comment by DeepDiver1975** [comment]
already possible:

```sh
$ ./occ list --raw
$ ./occ list --format=xml

**Comment by Kawohl** [comment]
@DeepDiver1975 
Thanks for the edit,

i think we need to document this stuff somewhere.

**Comment by DeepDiver1975** [comment]
> i think we need to document this stuff somewhere.

````
$ ./occ help list
Usage:
 list [--xml] [--raw] [--format="..."] [namespace]

Arguments:
 namespace  The namespace name

Options:
 --xml      To output list as XML
 --raw      To output raw command list
 --format   To output list in other formats (default: "txt")

Help:
 The list command lists all commands:
 
   php ./occ list
 
 You can also display the commands for a specific namespace:
 
   php ./occ list test
 
 You can also output the information in other formats by using the --format option:
 
   php ./occ list --format=xml
 
 It's also possible to get raw list of commands (useful for embedding command runner):
 
   php ./occ list --raw

**Comment by Kawohl** [comment]
Upps thank you very much!

**Comment by MorrisJobke** [comment]
I also didn't know about the list command and it's options ... :+1: Nice one

**Comment by MorrisJobke** [comment]
cc @carlaschroder Can you document this command?

**Comment by RealRancor** [comment]
Its a little bit hidden but its already there:

```
$ ./occ

*snip*

Available commands:
  help                                Displays help for a command
  list                                Lists commands
```

**Comment by MorrisJobke** [comment]
> Its a little bit hidden but its already there:

I know, but it's not that intuitive, because I checked it like this:

```
./occ --help
```

and there was no hint about the options. ;)

**Comment by DeepDiver1975** [comment]
Please file all your concerns against the upstream project: symfony/console
