### ISSUE TITLE
Update screen layout and wording fix

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#17437]
![update-warning](https://cloud.githubusercontent.com/assets/277525/8545320/a2ca647a-24ad-11e5-8645-1b0f8085e5aa.png)
The text »the following apps have been disabled« is in another container, and uses the word »3rdparty« which can be dropped.

cc @owncloud/designers @PVince81

**Comment by PVince81** [comment]
Nah, this will conflict with my PRs :wink:

**Comment by PVince81** [comment]
Ah it's a ticket, not a PR. Then let me remove the text here https://github.com/owncloud/core/pull/17434

**Comment by PVince81** [comment]
Another PR: https://github.com/owncloud/core/pull/17439

**Comment by MorrisJobke** [comment]
The layout is not fixed yet.

**Comment by jancborchardt** [comment]
Actually the layout is fine like it is now for the separation.
