### ISSUE TITLE
Unable to parse OCS content when trying to install app on 8.0

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#17438]
### Steps to reproduce

1. Install 8.0
2. Go to the app store
3. Install ShareLinks https://apps.owncloud.com/content/show.php/ShareLinks?content=170527

### Expected result

App installs

### Actual result

App pretends to install

### Logs
`"app":"core","message":"Unable to parse OCS content","level":4,"time":"2015-07-07T12:23:04+00:00","method":"POST","url":"\/index.php\/settings\/ajax\/enableapp.php"`

**Comment by RealRancor** [comment]
Not sure but could be possible that your app is missing the ocsid in the info.xml

**Comment by DeepDiver1975** [comment]
@oparoz  The ocsid is missing on your info.xml

**Comment by oparoz** [comment]
@DeepDiver1975 @RealRancor You are correct that the app was missing the ocsid, but that's not the problem. It still can't be installed

**Comment by oparoz** [comment]
I've also tested with this patch, but it didn't change anything
https://github.com/owncloud/core/pull/17297

Works fine on 8.1 though.

**Comment by AdamWill** [comment]
I - and some of my (Fedora package) users - are seeing the same thing trying to enable first party apps, like Calendar:

    Jul 07 15:19:42 localhost.localdomain ownCloud[1521]: {core} Invalid OCS content returned for app 168707
    Jul 07 15:19:43 localhost.localdomain ownCloud[1521]: {core} Invalid OCS content returned for app 168707
    Jul 07 15:19:44 localhost.localdomain ownCloud[1521]: {core} Unable to parse OCS content

Perhaps something was changed in the app store stuff for 8.1, which has broken it for 8.0?

**Comment by oparoz** [comment]
I've just tried on 8.0.5 and I was able to install ShareLinks.

Would be good if someone else could confirm that this is no longer an issue.

**Comment by AdamWill** [comment]
Yeah, 8.0.5 seems good here too. It had a bunch of obviously-relevant commits. +1 to close this.

**Comment by rperezb** [comment]
@oparoz added to the @owncloud/qa list of things to be tested within 8.0.6 thx
