### ISSUE TITLE
.htaccess file has the wrong version. - occurs when updating from 8.0.4 to 8.1.0 

### ISSUE THREAD

**Issue by matt407** [owncloud/core#17447]
Hi,

maybe you could assist in this case. I'm not sure if a bug it is.
My webserver runs on nginx and I tried to upgrade owncloud to version 8.1.0 manually (no debian repository) and the upgrade fails.
After I ran  "sudo -u www-data php occ upgrade", I got the following output:

ownCloud or one of the apps require upgrade - only a limited number of commands are available
Turned on maintenance mode
Exception: .htaccess file has the wrong version. Please upload the correct version. Maybe you forgot to replace it after updating?
Update failed
Maintenance mode is kept active

The output looks completely strange for me - I don't use apache on the server.....

Regards,
Matt

**Comment by LukasReschke** [comment]
You need to upload all new files. I suspect you did not update the .htaccess file? (also required to be updated for not apache servers)

**Comment by matt407** [comment]
Hi Lukas,

your are right, thank you! 8.1.0 is now running! :) 

Regards,
Matthias
