### ISSUE TITLE
After update to 8.1 an error message appears, that not internet access is available.

### ISSUE THREAD

**Issue by tuxmaster** [owncloud/core#17448]
Under the admin page on the top the error message:
Security & setup warnings:
This server has no working Internet connection. This means that some of the features like mounting external storage, notifications about updates or installation of third-party apps will not work. Accessing files remotely and sending of notification emails might not work, either. We suggest to enable Internet connection for this server if you want to have all features.

But the server is connect to the internet. Other application that makes internal downloads are working perfectly witch runs on the same server. In the log files I can't find an error.

**Comment by PVince81** [comment]
Did you set `has_internet_connection` to false in your config.php ?
If not, then the internet check will try and connect to some owncloud server to find if the connection works. Maybe that server was overloaded due to the recent release.

**Comment by tuxmaster** [comment]
No I don't have set the option has_internet_connection to anything.

**Comment by RealRancor** [comment]
Maybe a dup of: https://github.com/owncloud/core/issues/16255

**Comment by tuxmaster** [comment]
Yes this can be, because the test on it report the same buggy result.
But an complete other system.
I my case RHEL based, at the reference Ubuntu.

**Comment by maelange** [comment]
See a solution on centos/fedora/redhat setup :  #16255

**Comment by jpaechnatz** [comment]
'has_internet_connection' => false, or true... changed nothing...

The Server itself is reachable, up and running as before 8.1 ...

**Comment by NetBit73** [comment]
the same problem,
'has_internet_connection' => false, or true... changed nothing...
The Server itself is reachable, up and running as before 8.1 ...

**Comment by RealRancor** [comment]
@jpaechnatz @NetBit73 see just the comment one above your posts: https://github.com/owncloud/core/issues/17448#issuecomment-119532101

**Comment by jpaechnatz** [comment]
So, there is no Solution until curl gets fixed in upstream rhel. Mixing up the enterprise grade Distribution with selfcompiled source packages is not prefered. 
Owncloud should offer a Solution for it's supported Distributions that work with it's "official" provided packages

**Comment by RealRancor** [comment]
> Owncloud should offer a Solution for it's supported Distributions that work with it's "official" provided packages

Disabling strong ciphers to work around an upstream bug? :see_no_evil:

**Comment by PVince81** [comment]
Someone on the mailing list pointed out that switching the test URL from https://www.owncloud.org to https://owncloud.org would fix the problem.

I don't have this problem on my server though.

Maybe we just need a proper URL, not sure if https is even necessary for that.

**Comment by PVince81** [comment]
with proper URL I mean a real endpoint, not just some random server.

**Comment by corneverbruggen** [comment]
This issue also affects owncloud on Ubuntu 14.04 with PHP 5.5.9 after upgrading to OwnCloud 8.1. Removing the www from www.owncloud.org in settings/controller/checksetupcontroller.php does not "solve" this.

**Comment by b1ggjoe** [comment]
Gents,

Are we any closer to getting this solved?

J.

**Comment by ianmcxa** [comment]
I have this same issue on Owncloud 8.1 running on Ubuntu 14.04.

**Comment by Takif** [comment]
CentOS 7. Same issue. 
OC 8.0 worked flawlessly prior to update. 
PHP 5.4.16 (cli)
Cant use sendmail from OC althought can send test mail from cli without any problem. 
Updated using the repo.

**Comment by RealRancor** [comment]
See https://github.com/owncloud/core/issues/16255#issuecomment-119531656

**Comment by ianmcxa** [comment]
I ended up wiping the config and reinstalling. That appeared to fix the problem.

**Comment by RealRancor** [comment]
@ianmcxa Then you probably had copied over the config.sample.php to config.php and had the empty proxy settings in the config which is also causing such a problem.

**Comment by Jas2Ma** [comment]
I have had this bug, too. I was able to fix it, by adding the "config/ca-bundle.crt" file, which I hadn't in my 8.0 config directory. The file can be found in the zip of the owncloud server download file.

**Comment by shibukk** [comment]
@Jas2Ma Please teach me, how did you add ca-bundle.crt?
I tried the following steps, but didn't work well...

1. copy "config/ca-bundle.crt" in the zip of the owncloud server download file.
2. put that file in "/etc/pki/ca-trust/source/anchors/".
3. run command `update-ca-trust enable` and `update-ca-trust extract`.

**Comment by Jas2Ma** [comment]
@shibukk it's not so complicated as you think. What helped me was:

1. copy "config/ca-bundle.crt" in the zip of the owncloud server download file
2. put it in the "config/" directory of my owncloud instance (for me "/var/www/config" as absolute path)

that's all, afterwards the warning was gone.

**Comment by RealRancor** [comment]
@Jas2Ma Do you know why this file was missing at your installation? How did you do the upgrade?

**Comment by Jas2Ma** [comment]
@RealRancor I am using Docker for easy maintenance and backuping. So what I do is building a new docker image with the updated docker files and bind my specific directories as shared volumes into my container. That's why new files are missing in these directories at first at the moment. Maybe I will improve this a time or another.
I don't think this procedure is what most people are doing, but the file could have been lost in other ways, too. So I thought, I should write here about how I was able to get rid of this warning.

**Comment by shibukk** [comment]
@Jas2Ma I tried your advice, but didn't work as well.
Thanks for your comment!

**Comment by shibukk** [comment]
@RealRancor This file was missing on my environment too.
I am using [ownCloud powered by owncloud.jp](https://aws.amazon.com/marketplace/pp/B00F8I7IXG/ref=srh_res_product_title?ie=UTF8&sr=0-3&qid=1380794974138) in AWS marketplace.

And It isn't the error when I create EC2 instance at version 8.0, but It is the error at version 8.1.
So, I am searching the differences between two version on this AMI.

**Comment by DeepDiver1975** [comment]
I guess the solution is clear -> closing

**Comment by mschoeler** [comment]
Copying ca-bundle.crt from the owncloud zip to my config folder solved the problem for me, too.

**Comment by RealRancor** [comment]
@mschoeler Do you know why you have missed this file?

**Comment by Takif** [comment]
Adding this file did not solve my problem. 
I updated through this repo:
http://download.opensuse.org/repositories/isv:/ownCloud:/community/CentOS_CentOS-7/

**Comment by RealRancor** [comment]
@Takif Getting the warnings about buggy OpenSSL/NSS version in the admin backend of oC 8.1.1? If yes follow the advices at: https://doc.owncloud.org/server/8.1/admin_manual/configuration_server/security_setup_warnings.html. Nothing more what can be done here.

**Comment by mschoeler** [comment]
@Takif  I just updated using the update app in owncloud. I guess it forgot to put it into the config folder.
Copying it manually solved this problem for me.
My access-bits of the config folder: drwxrws---   2 www-data  www-data

**Comment by mschoeler** [comment]
Sorry meant to address @RealRancor

**Comment by cearap01** [comment]
@mschoeler thank you! - this fixed my issue

"Copying ca-bundle.crt from the owncloud zip to my config folder"

this was driving me nuts for days ... even though it was critical just hate seeing error msgs.

Thank you once again!

**Comment by RealRancor** [comment]
@cearap01 Also used the updater app?

**Comment by cearap01** [comment]
@RealRancor 
i didn't need to - just copied the crt file to my config/ directory and it's done.

**Comment by RealRancor** [comment]
@cearap01 Sure, but it could be useful to know WHY this file was missing. So the question is if you also had used the updater app to go from oC 8.0.x to 8.1.1?

**Comment by cearap01** [comment]
@RealRancor sorry misunderstood.
yes from 8.0.5 to 8.1.1 i did use the updater ... i had the same 3 errors as everyone else did.
the error for internet which was the crt file missing - which was in my web folder "/home/website/owncloud/config" not sure why it was there and not the main.
the "memcached" was not properly configured in config.php 
- which i fixed based on owncloud forums
and the "Strict-Transport-Security" which was missing from my /etc/apache2/apache2.conf file
Ii added at the end of /etc/apache2/apache2.conf
<IfModule mod_headers.c> 
        Header always set Strict-Transport-Security "max-age=15768000; includeSubDomains; preload" 
</IfModule>

hope that was helpful.

**Comment by okaenrique** [comment]
i just install new owncloud on centos 7 and get all the error 


Security & setup warnings

This server has no working Internet connection. This means that some of the features like mounting external storage, notifications about updates or installation of third-party apps will not work. Accessing files remotely and sending of notification emails might not work, either. We suggest to enable Internet connection for this server if you want to have all features.

Your data directory and your files are probably accessible from the Internet. The .htaccess file is not working. We strongly suggest that you configure your web server in a way that the data directory is no longer accessible or you move the data directory outside the web server document root.

No memory cache has been configured. To enhance your performance please configure a memcache if available. Further information can be found in our documentation.

cURL is using an outdated NSS version (NSS/3.15.4). Please update your operating system or features such as installing and updating apps via the app store or Federated Cloud Sharing will not work reliably.

You are accessing this site via HTTP. We strongly suggest you configure your server to require using HTTPS instead as described in our security tips.



any help please ?

**Comment by RealRancor** [comment]
@okaenrique Please see https://doc.owncloud.org/server/8.1/admin_manual/configuration_server/security_setup_warnings.html and use the user mailinglist or the forums for such support questions

**Comment by RealRancor** [comment]
Have raised https://github.com/owncloud/updater/issues/164 for the missing ca-bundle.crt issue.

**Comment by mik997** [comment]
+1 for this

running update from 8.0.5 --> 8.1.1 resulted in the "This server has no working Internet connection .." warning.

manually copying the ca-bundle.crt to /usr/share/owncloud/config/ fixed the problem, tnx Jas2Ma!!

[ Ubuntu 14.04 with owncloud 8.1.1/nginx 1.9.3/php5-fpm 5.5.9 ]

**Comment by RealRancor** [comment]
@mik997 See https://github.com/owncloud/updater/issues/164

**Comment by sobrien808** [comment]
On CentOS 7 this is what I did to resolve:
rpm -Uvh http://nervion.us.es/city-fan/yum-repo/city-fan.org-release-1-13.rhel7.noarch.rpm
edit the /etc/yum.repos.d/city-fan.org.repo end change enabled=1 to 0
yum --enablerepo=city-fan.org update curl

Fixed all my errors

**Comment by adundovi** [comment]
@sobrien808 tnx, this worked, even though is not recommended to install all kind of 3rd party repositories we bumped on. :-)
