### ISSUE TITLE
8.1. Help shows wrong version

### ISSUE THREAD

**Issue by felixboehm** [owncloud/core#17445]
### Steps to reproduce
1. In scaffolding file ```ownCloudUserManual.pdf``` or top right menu item "Help"

![bildschirmfoto 2015-07-07 um 16 06 33](https://cloud.githubusercontent.com/assets/1204907/8547963/78c3aa82-24c2-11e5-8061-d504032275de.png)

On the help page: "ownCloud 8.2 User Manual Introduction"

### Expected behaviour
Manual should be for version 8.1

**ownCloud version:** (see ownCloud admin page)
ownCloud 8.1.0 (stable)

**Comment by karlitschek** [comment]
Yes. Known problem. Will be fixed in 8.1.1

**Comment by RealRancor** [comment]
Ref for a dup: https://github.com/owncloud/core/issues/17389
