### ISSUE TITLE
ownCloud 8.1 wrongly reports broken .htacces-file

### ISSUE THREAD

**Issue by BenS89** [owncloud/core#17449]
Steps to reproduce:
1. Have an ownCloud Server 8.0.5 with working .htacces-file so that /ownCloud/data is not accessible
2. Upgrade to ownCloud 8.1
3. Go to the admin panel and check the security messages and warnings

Expected behaviour:
No error messages

Actual behaviour:
ownCloud states that my files were accessible via Internet and that my .htaccess-file is not working. 
In german, you can read: "Ihr Datenverzeichnis und Ihre Dateien sind wahrscheinlich vom Internet aus erreichbar. Die .htaccess-Datei funktioniert nicht. Es wird dringend empfohlen, Ihren Webserver dahingehend zu konfigurieren, dass das Datenverzeichnis nicht mehr vom Internet aus erreichbar ist oder dass Sie es aus dem Document-Root-Verzeichnis des Webservers herausverschieben."

I tried to call /owncloud/data and I correctly get the forbidden-page. Therefore, .htaccess is working correctly.

**Comment by karlitschek** [comment]
You have to update the .htaccess in the ownCloud root directory.

**Comment by BenS89** [comment]
.htaccess in the ownCloud root directory says # Version: 8.1.0
Could you give me some more information on how to update the .htaccess? 

Thank you

**Comment by RealRancor** [comment]
@karlitschek 

This isssue is not about the wrong version of the .htaccess file but about a failed check for a .htaccess file.

**Comment by BenS89** [comment]
Since this issue did not occur in 8.0.5, I do not know why this happens now. By testing the .htaccess manually, I could see that everything is working fine. Any ideas?

Thanks and best regards
Ben

**Comment by RealRancor** [comment]
@BenS89 
If no one is re-opening this issue maybe create one stating this is not about the version of the .htaccess file but about the test to check if the .htaccess file is protecting the datadir.
