### ISSUE TITLE
shared folder synchronization fails because of one file

### ISSUE THREAD

**Issue by atroxix** [owncloud/core#17444]
One shared file causes interruption of the whole synchronization progress.
Error in client: 1.8.3 (OpenSUSE)
  07/07/2015 16:35:57  security/myfile.xlsx       ownCloudShared Connection closed  14 KiB

Error in server: 8.0.2 (Debian)
```
{"reqId":"65cfdcb383ac5bfc66cf24cbec3b0b9a","remoteAddr":"client-ip","app":"lock","message":"INFO: Read lock requested for \/var\/ownclouddata\/myuser\/files\/Documents\/security\/myfile.xlsx","level":0,"time":"2015-07-07T16:34
:52+03:00","method":"GET","url":"\/remote.php\/webdav\/Shared\/security\/myfile.xlsx"}
{"reqId":"65cfdcb383ac5bfc66cf24cbec3b0b9a","remoteAddr":"client-ip","app":"lock","message":"PASS: Acquired read lock for \/var\/ownclouddata\/myuser\/files\/Documents\/security\/myfile.xlsx","level":0,"time":"2015-07-07T16:34:
52+03:00","method":"GET","url":"\/remote.php\/webdav\/Shared\/security\/myfile.xlsx"}
{"reqId":"65cfdcb383ac5bfc66cf24cbec3b0b9a","remoteAddr":"client-ip","app":"lock","message":"INFO: Incrementing lock type 1 count for \/var\/ownclouddata\/myuser\/files\/Documents\/security\/myfile.xlsx","level":0,"time":"2015-
07-07T16:34:52+03:00","method":"GET","url":"\/remote.php\/webdav\/Shared\/security\/myfile.xlsx"}
{"reqId":"65cfdcb383ac5bfc66cf24cbec3b0b9a","remoteAddr":"client-ip","app":"lock","message":"INFO: Incrementing lock type 1 count for \/var\/ownclouddata\/myuser\/files\/Documents\/security\/myfile.xlsx","level":0,"time":"2015-
07-07T16:34:52+03:00","method":"GET","url":"\/remote.php\/webdav\/Shared\/security\/myfile.xlsx"}
{"reqId":"65cfdcb383ac5bfc66cf24cbec3b0b9a","remoteAddr":"client-ip","app":"lock","message":"INFO: Incrementing lock type 1 count for \/var\/ownclouddata\/myuser\/files\/Documents\/security\/myfile.xlsx","level":0,"time":"2015-
07-07T16:34:52+03:00","method":"GET","url":"\/remote.php\/webdav\/Shared\/security\/myfile.xlsx"}
{"reqId":"65cfdcb383ac5bfc66cf24cbec3b0b9a","remoteAddr":"client-ip","app":"lock","message":"INFO: Incrementing lock type 1 count for \/var\/ownclouddata\/myuser\/files\/Documents\/security\/myfile.xlsx","level":0,"time":"2015-
07-07T16:34:52+03:00","method":"GET","url":"\/remote.php\/webdav\/Shared\/security\/myfile.xlsx"}
{"reqId":"65cfdcb383ac5bfc66cf24cbec3b0b9a","remoteAddr":"client-ip","app":"lock","message":"INFO: Read lock requested for \/var\/ownclouddata\/myuser\/files_encryption\/keys\/Documents\/security\/myfile.xlsx\/fileKey","level":
0,"time":"2015-07-07T16:34:52+03:00","method":"GET","url":"\/remote.php\/webdav\/Shared\/security\/myfile.xlsx"}
{"reqId":"65cfdcb383ac5bfc66cf24cbec3b0b9a","remoteAddr":"client-ip","app":"lock","message":"PASS: Acquired read lock for \/var\/ownclouddata\/myuser\/files_encryption\/keys\/Documents\/security\/myfile.xlsx\/fileKey","level":0
,"time":"2015-07-07T16:34:52+03:00","method":"GET","url":"\/remote.php\/webdav\/Shared\/security\/myfile.xlsx"}
{"reqId":"65cfdcb383ac5bfc66cf24cbec3b0b9a","remoteAddr":"client-ip","app":"lock","message":"INFO: Incrementing lock type 1 count for \/var\/ownclouddata\/myuser\/files_encryption\/keys\/Documents\/security\/myfile.xlsx\/fileKey","level":0,"time":"2015-07-07T16:34:52+03:00","method":"GET","url":"\/remote.php\/webdav\/Shared\/security\/myfile.xlsx"}
{"reqId":"65cfdcb383ac5bfc66cf24cbec3b0b9a","remoteAddr":"client-ip","app":"lock","message":"INFO: Releasing locks on \/var\/ownclouddata\/myuser\/files_encryption\/keys\/Documents\/security\/myfile.xlsx\/fileKey","level":0,"time":"2015-07-07T16:34:52+03:00","method":"GET","url":"\/remote.php\/webdav\/Shared\/security\/myfile.xlsx"}
{"reqId":"65cfdcb383ac5bfc66cf24cbec3b0b9a","remoteAddr":"client-ip","app":"lock","message":"INFO: Released lock handle Resource id #605 on \/var\/ownclouddata\/myuser\/files_encryption\/keys\/Documents\/security\/myfile.xlsx\/fileKey","level":0,"time":"2015-07-07T16:34:52+03:00","method":"GET","url":"\/remote.php\/webdav\/Shared\/security\/myfile.xlsx"}
{"reqId":"65cfdcb383ac5bfc66cf24cbec3b0b9a","remoteAddr":"client-ip","app":"lock","message":"FREE: Released locks on \/var\/ownclouddata\/myuser\/files_encryption\/keys\/Documents\/security\/myfile.xlsx\/fileKey","level":0,"time":"2015-07-07T16:34:52+03:00","method":"GET","url":"\/remote.php\/webdav\/Shared\/security\/myfile.xlsx"}
```

**Comment by PVince81** [comment]
I hope it's the exact same issue, because I observed some discrepancies between my steps and your statements in the other ticket. Symptoms were the same.

We'll see. Here were my steps: https://github.com/owncloud/core/issues/15856#issuecomment-118049614

**Comment by PVince81** [comment]
By the way, you might want to update to 8.0.5.

**Comment by PVince81** [comment]
Any more luck with 8.0.6 or 8.1.3 ?

**Comment by atroxix** [comment]
We have 8.1.3 now, but the error remains.

**Comment by kalletabur** [comment]
Any updates on this?

**Comment by PVince81** [comment]
I see `Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you`. I'd expect that if the owner shares the file again (or the containing folder), the target user should get access again. @atroxix said it didn't work.

Something to check: look at the folder "data/$SHARE_OWNER/files_encryption/.../security/myfile.xls" and see if the list of "*.shareKey" files contains one for the recipient user.

**Comment by PVince81** [comment]
@schiesbn

**Comment by kalletabur** [comment]
There is no .shareKey file(s) in atroxix folder, only fileKey.

But there is actually 2 folders called /myfile.xls/ under user/files_encryption/keys folder
One is located user/files_encryption/keys/**files**/SeveralFolders/myfile.xls/ and it's content is folder OC_DEFAULT_MODULE/fileKey
the other is located at user/files_encryption/keys/SeveralFolders/myfile.xls/ and is empty.

Do you know why is that? Owncloud manual ([where keys stored](https://doc.owncloud.org/server/8.1/admin_manual/configuration_files/encryption_configuration.html?highlight=where%20keys%20stored#where-keys-are-stored)) doesn't say anything about sorting keyfile folder structure under "files" folder

**Comment by kalletabur** [comment]
Any thoughts?

**Comment by PVince81** [comment]
The "Length parameter" issue was reported here https://github.com/owncloud/core/issues/18402 but without outcome. Just for reference.

You could try disabling the "file_locking" app and see if it helps.

**Comment by PVince81** [comment]
@schiesbn please advise

**Comment by kalletabur** [comment]
We tried disabling file_locking but this didn't fix this.
Has @schiesbn investigated this issue?

**Comment by kalletabur** [comment]
Do you have updates on this issue? Is there any progress?

**Comment by PVince81** [comment]
@schiesbn can you please have a look ?

**Comment by cmonteroluque** [comment]
@schiesbn ping

**Comment by schiesbn** [comment]
> user/files_encryption/keys/files/SeveralFolders/myfile.xls/OC_DEFAULT_MODULE/

That's the correct path. It should contain a fileKey and at least a `<owber>.shareKey`.

The other folder is the old folder used in ownCloud <=8.0. Do you remember if the migration between 8.0 and 8.1 went fine? Looks something during upgrade went wrong.

**Comment by schiesbn** [comment]
From the migration 8.0 -> 8.1 you should have a backup of the keys in `data/user/encryption_migration_backup_<date>`. Look there for the folder named like the file and copy the share keys over to the new location `user/files_encryption/keys/files/SeveralFolders/myfile.xls/OC_DEFAULT_MODULE/` this should fix it.

**Comment by cmonteroluque** [comment]
any response to 
https://github.com/owncloud/core/issues/17444#issuecomment-197938155 ?

**Comment by PVince81** [comment]
@kalletabur @atroxix

**Comment by kalletabur** [comment]
Before this issue arise we had only one migration that has _migration backups_. Time between these (migration to this issue) was ~3 months.
In this /encryption_migration_backup_date_time/.. folder there is one file
myfile.xlsx.key
and there is no difference between this file and 
user/files_encryption/keys/files/SeveralFolders/myfile.xls/OC_DEFAULT_MODULE/fileKey

No share keys about that (myfile.xlsx.key) file on server.

And migrations so far have been successful.

**Comment by PVince81** [comment]
If the file "myfile.xlsx" has no share keys, then encryption will not work for that file.

**Comment by PVince81** [comment]
Without keys this file will not be restore-able. Not sure why the key would disappear completely from the server and not even be found in backup folders. It is likely that this was caused by older encryption bugs.

I'm closing this now. If you experience further issues with more recent OC versions, feel free to reopen.
