### ISSUE TITLE
ownCloud 8.1 gets broken after enabling the calendar app

### ISSUE THREAD

**Issue by BenS89** [owncloud/core#17441]
Stepts to reproduce:

Upgrade from ownCloud Server 8.0.5 to 8.1
Enable the calendar-app.

Expected behaviour:
The app gets enabled and ownCloud is working properly

Actual behaviour:
ownCloud is broken, you only see a blank page. In the error log, you can see the following:

<code>{"reqId":"H+kjRn0w1u91xbANOsK4","remoteAddr":"213.95.x.x","app":"PHP","message":"Access to undeclared static property: Sabre\\VObject\\Property::$classMap at \/share\/MD0_DATA\/Web\/owncloud\/apps\/calendar\/appinfo\/app.php#37","level":3,"time":"2015-07-07T13:25:54+00:00"}</code>

The same is true for the contacts app:

<code>{"reqId":"3Zuo6RAU8\/GiySHt2ojV","remoteAddr":"213.95.x.x","app":"PHP","message":"Access to undeclared static property: Sabre\\VObject\\Component::$classMap at \/share\/MD0_DATA\/Web\/owncloud\/apps\/contacts\/appinfo\/app.php#15","level":3,"time":"2015-07-07T13:33:11+00:00"}
</code>

**Comment by karlitschek** [comment]
Have you updated the calendar to the 8.1 version? or do you use the old one?

**Comment by BenS89** [comment]
Indeed, updating the calendar to version 0.7.0 and updating the contacts to 0.4.0.0 did the trick. This issue can be closed. I was just wondering why this was not happening automatically. Because I saw that other apps were updated automatically as well.

**Comment by PVince81** [comment]
There is a different between code update and DB update. Maybe at some point we should make it clearer in the wording.

The automatic updates you observed were probably DB updates for apps that already had their code updated, which did not include the calendar.

Anyway, glad to hear that it worked now :smile:

**Comment by BenS89** [comment]
Thanks for this clarification. You are absolutely right.
