### ISSUE TITLE
"occ encryption:migrate" throws different exceptions (8.1)

### ISSUE THREAD

**Issue by mistersixt** [owncloud/core#17443]
Hi all,

I have just upgraded from 8.0.4 to 8.1.0, and the syslog was showing :

"Installation is in transit between the old Encryption (ownCloud <= 8.0) and the new encryption. Please enable the "Default encryption module" and run 'occ encryption:migrate'"

Which I just tried, I activated the Default encryption in the administration page, put OC in the maintenance mode, but when running "./occ encryption:migrate" I get back this:

------------------------------------------------- cut --------------------------------------------
$ ./occ encryption:migrate
Reorganize system folder structure
                                                                                                                                                   
  [Doctrine\DBAL\Exception\UniqueConstraintViolationException]                                                                                     
  An exception occurred while executing 'UPDATE "oc_appconfig" SET "appid" = ? WHERE "appid" = ?' with params ["encryption", "files_encryption"]:  
  SQLSTATE[23000]: Integrity constraint violation: 19 columns appid, configkey are not unique                                                      
                                                            
  [Doctrine\DBAL\Driver\PDOException]                                                          
  SQLSTATE[23000]: Integrity constraint violation: 19 columns appid, configkey are not unique  

  [PDOException]                                                                               
  SQLSTATE[23000]: Integrity constraint violation: 19 columns appid, configkey are not unique  
                                                                                               
encryption:migrate [user_id1] ... [user_idN]

$
------------------------------------------------- cut --------------------------------------------

Backend is SQLite. Any help is welcome,

kind regards, Joerg.

**Comment by karlitschek** [comment]
@schiesbn What do you think?

**Comment by jolorant** [comment]
I get this error now as well, see #16928 for what I did.

**Comment by maste9** [comment]
I had this one some minutes ago after upgrading to 8.1 on debian.
> sudo -u www-data ./occ encryption:migrate

> Reorganize system folder structure

> PHP Fatal error:  Call to a member function getRelativePath() on a non-object in /var/www/owncloud/apps/files_trashbin/lib/storage.php on line 123

**Comment by danilocanel** [comment]
root@sdtsystems:/var/www/owncloud# sudo -u www-data php occ status
 - installed: true
 - version: 8.1.0.8
 - versionstring: 8.1.0
 - edition:
root@x:/var/www/owncloud# sudo -u www-data php occ encryption:migrate
Reorganize system folder structure
PHP Fatal error:  Call to a member function getRelativePath() on a non-object in /var/www/owncloud/apps/files_trashbin/lib/storage.php on line 123
root@x:/var/www/owncloud# sudo -u www-data php occ encryption:migrate
Reorganize system folder structure
PHP Fatal error:  Call to a member function getRelativePath() on a non-object in /var/www/owncloud/apps/files_trashbin/lib/storage.php on line 123
root@sdtsystems:/var/www/owncloud#

**Comment by danilocanel** [comment]
root@x:/var/www/owncloud# sudo -u www-data php occ status
  installed: true
  version: 8.1.0.8
  versionstring: 8.1.0
  edition:
root@x:/var/www/owncloud# sudo -u www-data php occ encryption:migrate
Reorganize system folder structure
PHP Fatal error:  Call to a member function getRelativePath() on a non-object in /var/www/owncloud/apps/files_trashbin/lib/storage.php on line 123
root@sdtsystems:/var/www/owncloud# sudo -u www-data php occ encryption:migrate
Reorganize system folder structure
PHP Fatal error:  Call to a member function getRelativePath() on a non-object in /var/www/owncloud/apps/files_trashbin/lib/storage.php on line 123
root@x:/var/www/owncloud#

**Comment by danilocanel** [comment]
root@x:/var/www/owncloud# sudo -u www-data php occ status
  installed: true
  version: 8.1.0.8
  versionstring: 8.1.0
  edition:

root@x:/var/www/owncloud# sudo -u www-data php occ encryption:migrate
Reorganize system folder structure
PHP Fatal error:  Call to a member function getRelativePath() on a non-object in /var/www/owncloud/apps/files_trashbin/lib/storage.php on line 123

root@x:/var/www/owncloud# sudo -u www-data php occ encryption:migrate
Reorganize system folder structure
PHP Fatal error:  Call to a member function getRelativePath() on a non-object in /var/www/owncloud/apps/files_trashbin/lib/storage.php on line 123

root@x:/var/www/owncloud#

**Comment by schiesbn** [comment]
@danilocanel this are known errors. Sorry that we didn't found them before the release. All of the issues will be fixed with 8.1.1. Here I described how to recover from a failed migration run: https://github.com/owncloud/core/issues/17574
