### ISSUE TITLE
Unable to install apps from the appstore with 8.1

### ISSUE THREAD

**Issue by BenjaminXiao** [owncloud/core#17456]
### Steps to reproduce
1. Try to install any app from app store

### Expected behaviour
App gets installed

### Actual behaviour
App install fails with message: Client error response [url] https://apps.owncloud.com/CONTENT/content-files/169116-galleryplus-12.0.1.zip [status code] 400 [reason phrase] Bad Request

### Server configuration
**Operating system**:
Fedora 22

**Web server:**
Apache 2.4.12-1

**Database:**
mariadb 1:10.0.20-1

**PHP version:**
php 5.6.10-1

**ownCloud version:** (see ownCloud admin page)
8.1.0

**Updated from an older ownCloud or fresh install:**
Updated from 8

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder

Enabled:
 - activity: 2.0.1
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
Disabled:
 - encryption
 - external
 - files_external
 - user_external
 - user_ldap
 - user_webdavauth
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system --public
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)

<?php
define('DEBUG', true);
$CONFIG = array (
  'instanceid' => 'ocpleicxwygq',
  'passwordsalt' => 'REMOVED',
  'secret' => 'REMOVED',
  'trusted_domains' =>
  array (
    0 => 'benxiao.me',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'overwrite.cli.url' => 'https://benxiao.me/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'owncloud_db',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'REMOVED',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'benxiao.me',
  'mail_domain' => 'gmail.com',
  'mail_smtpsecure' => 'tls',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'smtp.gmail.com',
  'mail_smtpport' => '587',
  'mail_smtpname' => 'benxiao.me',
  'mail_smtppassword' => 'REMOVED',
  'theme' => '',
  'maintenance' => false,
  'loglevel' => 2,
  'forcessl' => true,
  'appstore.experimental.enabled' => true,
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

No external

**Are you using encryption:** yes/no

No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

No

### Client configuration
**Browser:**
Chrome 43

**Operating system:**
Fedora 22

#### Web server error log
```
Nothing interesting besides repeated:

[Tue Jul 07 10:04:31.407985 2015] [authz_core:error] [pid 2717] [client 192.168.1.1:39544] AH01630: client denied by server configuration: /var/www/html/owncloud/data/htaccesstest.txt

```

#### ownCloud log (data/owncloud.log)
```
Client error response [url] https://apps.owncloud.com/CONTENT/content-files/169116-galleryplus-12.0.1.zip [status code] 400 [reason phrase] Bad Request
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by BenjaminXiao** [comment]
I've been looking up related issues with SSL and curl, specifically regarding the ones about owncloud saying it doesn't have internet access. I am not sure if my issue is related. I've already ran these two files

```
<?php

require_once('./lib/base.php');


$client = \OC::$server->getHTTPClientService()->newClient();
try {
    $client->get('https://www.owncloud.org/');
    $client->get('http://www.owncloud.org/');
} catch (\Exception $e) {
    throw $e;
}
```

and 

```
<?php
function doCurl($url) {
    $ch = curl_init($url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    $result = curl_exec($ch);
    $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    return $code;
}
echo "HTTP Status: ".doCurl("https://owncloud.org")."\n";
echo "HTTP Status: ".doCurl("https://www.owncloud.org")."\n";
```


They give me:

```
Internal Server Error
The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.

Technical details
Remote Address: 192.168.1.1
Request ID: VZwPe@zg5ukkkIHgbBdGSwAAAAw
Type: GuzzleHttp\Exception\ClientException
Code: 400
Message: Client error response [url] https://owncloud.org/ [status code] 400 [reason phrase] Bad Request
File: /var/www/html/owncloud/3rdparty/guzzlehttp/guzzle/src/Exception/RequestException.php
Line: 89

Trace
#0 /var/www/html/owncloud/3rdparty/guzzlehttp/guzzle/src/Subscriber/HttpError.php(33): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Message\Response))
#1 /var/www/html/owncloud/3rdparty/guzzlehttp/guzzle/src/Event/Emitter.php(109): GuzzleHttp\Subscriber\HttpError->onComplete(Object(GuzzleHttp\Event\CompleteEvent), 'complete')
#2 /var/www/html/owncloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php(91): GuzzleHttp\Event\Emitter->emit('complete', Object(GuzzleHttp\Event\CompleteEvent))
#3 /var/www/html/owncloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php(132): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
#4 /var/www/html/owncloud/3rdparty/react/promise/src/FulfilledPromise.php(24): GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(Array)
#5 /var/www/html/owncloud/3rdparty/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
#6 /var/www/html/owncloud/3rdparty/guzzlehttp/guzzle/src/Message/FutureResponse.php(43): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
#7 /var/www/html/owncloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php(135): GuzzleHttp\Message\FutureResponse::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
#8 /var/www/html/owncloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php(132): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
#9 /var/www/html/owncloud/3rdparty/react/promise/src/FulfilledPromise.php(24): GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(Array)
#10 /var/www/html/owncloud/3rdparty/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
#11 /var/www/html/owncloud/3rdparty/guzzlehttp/guzzle/src/Message/FutureResponse.php(43): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
#12 /var/www/html/owncloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php(135): GuzzleHttp\Message\FutureResponse::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
#13 /var/www/html/owncloud/3rdparty/guzzlehttp/guzzle/src/Client.php(232): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
#14 /var/www/html/owncloud/3rdparty/guzzlehttp/guzzle/src/Client.php(192): GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))
#15 /var/www/html/owncloud/lib/private/http/client/client.php(122): GuzzleHttp\Client->get('https://www.own...', Array)
#16 /var/www/html/owncloud/test.php(8): OC\Http\Client\Client->get('https://www.own...')
#17 {main}
```

and

```
HTTP Status: 200
HTTP Status: 400
```

**Comment by oparoz** [comment]
Could you try again? The app store was mis-behaving earlier and it could be that it wasn't responding properly to your requests.

(Also, don't forget to disable Pictures before installing Gallery)

**Comment by BenjaminXiao** [comment]
Calendar and Contacts now work, but Documents, Bookmarks, Tasks, Gallery, and Music still give the same error.

**Comment by BenjaminXiao** [comment]
ShareLinks, Mail, and Antivirus also work. The rest do not. What are the differences between these apps?

**Comment by oparoz** [comment]
Regarding Gallery, did you install the app during the beta or RC phase? If yes, that could be a separate issue.

**Comment by BenjaminXiao** [comment]
I installed an older version of the Gallery app for OwnCloud 8 stable.

**Comment by oparoz** [comment]
Thanks. there shouldn't be a problem then. People on 8.1 installed a different app because the store wasn't capable of managing several versions of the same app.

It seems your problem could be related to https://bugs.php.net/bug.php?id=67639 , so maybe you need to try several times before being successful.

**Comment by BenjaminXiao** [comment]
I've clicked on Documents many times and it never adds. Meanwhile Calendar and Contacts seem to work every time. I feel like there's definitely some difference between how the apps are downloaded.

**Comment by oparoz** [comment]
And do you always get those HTTP errors or do you see something different?

**Comment by BenjaminXiao** [comment]
Always the same error for all of the apps.

**Comment by Lebernd** [comment]
after serval errors trying to install apps:
` [status code] 400 [reason phrase] Bad Request`
I also get a
`cURL error 60: See http://curl.haxx.se/libcurl/c/libcurl-errors.html`
error.

(I have downloaded the documents-app manually and copied it to the /apps folder - I can then enable the app, but when I click a document I just get the turning circle)

**Comment by BenjaminXiao** [comment]
@Lebernd 

I also get the turning circle on the documents app (manually installed). This shows up in the logs every time I open a document: Class 'OC_FileProxy' not found at /var/www/html/owncloud/apps/documents/lib/genesis.php#90

**Comment by jpaechnatz** [comment]
Client error response [url] https://apps.owncloud.com/CONTENT/content-files/169116-galleryplus-12.0.1.zip [status code] 400 [reason phrase] Bad Request

Or

Client error response [url] https://apps.owncloud.com/CONTENT/content-files/150271-files_mv.tar.gz [status code] 400 [reason phrase] Bad Request

**Comment by africanforest** [comment]
Seeing the same.
When i try to update an app like treebookmarks for example, the error is:

Client error response [url] https://apps.owncloud.com/CONTENT/content-files/169927-appstore.tar.gz [status code] 400 [reason phrase] Bad Request

**Comment by africanforest** [comment]
The problem occurs with all apps i try to activate from the appstore:

Another example:

Client error response [url] https://apps.owncloud.com/CONTENT/content-files/151523-roundcube_v2.6.1_build429.zip [status code] 400 [reason phrase] Bad Request

@ core team: 
Is there something we could do as a quick fix?

**Comment by ronielsen** [comment]
Centos 7 fresh install + ownCloud 8.1 - same issue here :-(

**Comment by ntnn** [comment]
I'm experiencing the same issue after updating today on CentOS 7, from ownCloud 8.0.2 (iirc) to 8.1.0 via yum.

**Comment by bloodyle** [comment]
Same exact behavior here.
Tasks, Bookmarks and probably more Apps affected.
Tried many times without success so far.

Client error response [url] https://apps.owncloud.com/CONTENT/content-files/164356-tasks.zip [status code] 400 [reason phrase] Bad Request

**Comment by mschloesser** [comment]
Unfortunately, same error here (tried Bookmarks and Tasks).
Downloading the file via curl CLI client works as expected.

I assume it is possible to download the files manually and install from disk?!

**Comment by africanforest** [comment]
> I assume it is possible to download the files manually and install from disk?!
Of course, for me that's actually the only way to install apps in some cases.

**Comment by jmeile** [comment]
I have the same problem; I tried to install "Delete Confirmation" and "Storage Charts 2", but I got a similar error as the original poster. Only the link was different. The only solution was to take those links and download and install them manually.

The strange thing is that with the "Antivirus App for files" and "Search Lucene" it worked. So, it seems to be a but in ownCloud 8.1.0

**Comment by DeepDiver1975** [comment]
Can you all please double check which version of openssl which is used on your systems? THX



refs https://github.com/owncloud/core/issues/17446#issuecomment-122275555

**Comment by LukasReschke** [comment]
Also I'd appreciate if you could run the test script from https://github.com/owncloud/core/issues/16255#issuecomment-112481294 and report back the status.

**Comment by LukasReschke** [comment]
That said if this is really the bug here as well we need to disable SNI on our web servers. :speak_no_evil:

**Comment by LukasReschke** [comment]
Ah the test script has already run at https://github.com/owncloud/core/issues/17456#issuecomment-119280154

@karlitschek Is SNI enabled on apps.owncloud.com? From what I can tell yes:

```
➜  master git:(master) ✗ dig apps.owncloud.com

; <<>> DiG 9.8.3-P1 <<>> apps.owncloud.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 3990
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;apps.owncloud.com.		IN	A

;; ANSWER SECTION:
apps.owncloud.com.	3440	IN	CNAME	main.hive01.com.
main.hive01.com.	812	IN	A	188.138.57.103
```

Some PHP and cURL versions cannot handle this really at all. See https://bugs.php.net/bug.php?id=67639 - I have the suspicion that disabling SNI may really help.

**Comment by LukasReschke** [comment]
So what I assume happens here is that first a request goes to api.owncloud.com for accessing the OCS API and then goes to apps.owncloud.com for downloading.

Both resolve to the same IP which matches the error described at https://bugs.php.net/bug.php?id=67639

**Comment by DeepDiver1975** [comment]
So we can solve this by using multiple IPs?

**Comment by karlitschek** [comment]
What we discovered in a debugging session last week is that somehow the communication with apps.owncloud.com/api.owncloud.com actually works fine. ownCloud shows all the necessary content on the apps page. Bus as soon as someone tries to download or update an app then it fails. The reason is that the download file is hosted somewhere else. In that case on github.com

**Comment by LukasReschke** [comment]
> What we discovered in a debugging session last week is that somehow the communication with apps.owncloud.com/api.owncloud.com actually works fine. ownCloud shows all the necessary content on the apps page. Bus as soon as someone tries to download or update an app then it fails. The reason is that the download file is hosted somewhere else. In that case on github.com

That's yet another different bug from what I can tell in the OpenSSL / PHP stack :)

**Comment by LukasReschke** [comment]
So what we have is:

1. A bug in older OpenSSL versions that make redirects not really possible. This is tracked at https://github.com/owncloud/core/issues/17446. More in-depth comments can be found at https://github.com/owncloud/core/issues/17446#issuecomment-122275555 and https://github.com/owncloud/core/issues/17446#issuecomment-122877546. Basically all modern distributions have newer OpenSSL versions.
2. A bug in some PHP / cURL versions that leads to problems in combination with SNI. This is tracked at https://bugs.php.net/bug.php?id=67639

I'm pretty sure we're experiencing No. 2 here.

**Comment by LukasReschke** [comment]
@ronielsen I'm trying to reproduce this on CentOS 7 but it works fine here. Please always post the detailed system versions.

**Comment by LukasReschke** [comment]
@karlitschek I got some environment where I can reproduce this. Can you check if in the ssl error log for around 16:11 you can find from the following IP: 46.14.22.157 an entry like:

> Hostname api.owncloud.com provided via SNI and hostname apps.owncloud.com provided via HTTP are different

Or:

> Hostname apps.owncloud.com provided via SNI and hostname api.owncloud.com provided via HTTP are different

Or something like that? – If yes then this is in fact this PHP bug.

**Comment by africanforest** [comment]
Please let me note that this issue does NOT occur with every app, but only with some apps - actually, as far as i have experienced, mainly with apps labeled as "experimental".
If it was a PHP bug, wouldn't installation of apps fail all the time?

**Comment by LukasReschke** [comment]
> Please let me note that this issue does NOT occur with every app, but only with some apps - actually, as far as i have experienced, mainly with apps labeled as "experimental".
> If it was a PHP bug, wouldn't installation of apps fail all the time?

No. They are installed differently. For example the app "Calendar" downloads it's code from GitHub, whereas apps such as "roundcube" ("Approved" - "Productivity") download their code from apps.owncloud.com.

**Comment by LukasReschke** [comment]
You can check this by going to https://apps.owncloud.com/ and downloading the 8.1 versions of the apps. Apps that are delivered from "apps.owncloud.com" should fail to install from what I can tell.

**Comment by africanforest** [comment]
I see. Thanks for the information!

**Comment by BenjaminXiao** [comment]
@DeepDiver1975 My software versions are:
openssl 1.0.1k-11.fc22
php 5.6.11-1.fc22
curl 7.40.0-5.fc22

@LukasReschke @karlitschek Oddly enough, Calendar works for me even though its downloading from GitHub, but roundcube does not.

**Comment by africanforest** [comment]
This is why i thought by myself that it maybe might usefull to list these apps that can be installed sucessfully, in comparison to those, that lead to error messages.

**Comment by LukasReschke** [comment]
> @LukasReschke @karlitschek Oddly enough, Calendar works for me even though its downloading from GitHub, but roundcube does not.

Yes. GitHub works, apps.owncloud.com does not work. – The bug here is the following:

1. When you click "install" on an application a request to api.owncloud.com is sent requesting the URL where the data resides.
2. api.owncloud.com returns a link to the application data, this can be:
 1. An application stored on apps.owncloud.com
 2. An application stored on another domain
3. Now the resource from 2 is downloaded

api.owncloud.com and apps.owncloud.com reside on the same host and are accessible via SNI. This means that the client has to indicate which host it wants to access in the TLS handshake, the advantage of this is that we don't require multiple IP addresses. However, this requires that the client does support SNI which nearly every client does since it is quite old already.

PHP and cURL however do have a bug when a request goes to multiple hosts residing on the same SNI host. So the first request goes to "api.owncloud.com" which passes just fine, that's why you see all the apps listed. The second one goes then to "apps.owncloud.com" to download the application, PHP however indicates however it wants to access "api.owncloud.com" which obviously isn't going to work.

Then again there are also other bugs, for example https://bugzilla.redhat.com/show_bug.cgi?id=1241172 which also may have the same result (not working - same error) while the root cause is completely different.

As a somewhat fail-safe solution I'd propose that we drop SNI on apps.owncloud.com and api.owncloud.com together in combination with the patch of https://bugzilla.redhat.com/show_bug.cgi?id=1241172 this should then work just fine.

@karlitschek

**Comment by LukasReschke** [comment]
Also please note that due to yet another bug in OpenSSL at least 1.0.1d or 1.0.2b is required, see https://github.com/owncloud/core/issues/17446#issuecomment-122275555 for some more details. This is usually the case and also here as stated in https://github.com/owncloud/core/issues/17456#issuecomment-122950768 by @BenjaminXiao. Also [really every major distribution](https://github.com/owncloud/core/issues/17446#issuecomment-122877546) is nowadays shipping new versions.

**Comment by LukasReschke** [comment]
@karlitschek As an alternate quick workaround you might modify the download links returned in the OCS response from apps.owncloud.com to api.owncloud.com, for example:

> https://apps.owncloud.com/CONTENT/content-files/170674-ownbackup.tar.gz

to 

> https://api.owncloud.com/CONTENT/content-files/170674-ownbackup.tar.gz

Theoretically this _should_ work around the SNI issue at least since we request the same host.

See https://api.owncloud.com/v1/content/download/170674/1?version=8x0x0x0

**Comment by LukasReschke** [comment]
This also applies to the preview pic links from https://api.owncloud.com/v1/content/data/170674?version=8x0x0x0

**Comment by ruspantini** [comment]
Hi LukasReschke, I am a newbie to ownCloud and don't understand most of what you are discussing. I see you have a version of Calendar (downloaded on Gitub) working on (I hope) ownCloud 8.1. Could you give me the link please ? I can't find it by browsing.
If you have any working contact app I would be grateful for a link to that too.
Thanks in advance for your time and knowledge

**Comment by africanforest** [comment]
@ruspantini 

Hi Luca,

if you are looking for a great calendar app for ownCloud, i can warmly recommend Calendar Plus (current version 1.0.2), which is a full featured calendar that smoothly integrates Task Plus, another great app. I cannot praise those two apps enough because of their quality and usefulness. Maybe you like it too.

https://apps.owncloud.com/content/show.php/Calendar+Plus?content=170560

**Comment by ruspantini** [comment]
Thanks for your help africanforest. Will this sync with thunderbird and android ? I still haven't been able to sync anything. I only lost complete calendar in thunderbird. Very frustrating experiences ...

**Comment by rperezb** [comment]
@DeepDiver1975 hey, is the milestone right? thx

**Comment by karlitschek** [comment]
so api.owncloud.com and apps.owncloud.com are both have dedicated IP. Nothing more we can do here.  If this is still not working with certain openssl/curl versions then I'm running out of options.

**Comment by LukasReschke** [comment]
Confirmed.

- [x] Installing apps served from apps.owncloud.com works on CentOS 7 with newest patches ("roundcube")
- [x] Installing apps served from GitHub works on CentOS 7 with newest patches. ("mail")

Thanks @karlitschek.

**Comment by ynott** [comment]
I have been tested on ownCloud ver.9 beta 2.
same error occured on installing Applications.

![applicationinstallerror](https://cloud.githubusercontent.com/assets/2724312/13373252/7bd7038a-dda5-11e5-9d91-64bd6e327d8c.png)

■Error occur when install these Applications.
OwnBackup 0.3.7
ownCloud Shortcut (Chrome app) 1.0
PDFLint Viewer 1.0
ActivityDefaults 0.1.0
AgreeDisclaimer 1.0.4
All Activity 0.0.6
disclaimer 0.2.1
Files move 0.8.2
GpxPod 0.9.15
Imprint 0.2.5
logreader 1.1.2
OC IPv6 1.0.rc3
piwik 0.1.0
Publisher 0.0.4
Sketch 0.1.2
Spreed.ME 0.1.2


### Server configuration
**Operating system**:
CentOS Linux release 7.2.1511 (Core) 

**Web server:**
nginx version: nginx/1.8.1

**Database:**
MariaDB-server.x86_64            10.0.24-1.el6

**PHP version:**
PHP 7.0.3 (cli) (built: Feb  3 2016 11:30:45) ( NTS )

**ownCloud version:** (see ownCloud admin page)
owncloud.noarch                9.0.0~beta2-3.1                 @ce_nightly

**Updated from an older ownCloud or fresh install:**
Updated from owncloud 9  beta1

**Signing status (ownCloud 9.0 and above):**

**Comment by LukasReschke** [comment]
@ynott Please file a new issue. THX.
