### ISSUE TITLE
Owncloud 8.1: Unable to logout

### ISSUE THREAD

**Issue by alex42ka** [owncloud/core#17454]
Since my upgrade to OC 8.1 my user aren't able to logout. When trying to logout I get a blank page and when I'm then going back to my owncloud link I'm again at the files view of the user.

OS: Ubuntu 14.04
Apache
 here comes my app:list:

```
Enabled:
 - activity: 2.0.1
 - bookmarks: 0.4
 - calendar: 0.7.1
 - contacts: 0.4.0.0
 - direct_menu: 0.3
 - documents: 0.9.0
 - external: 1.2
 - files: 1.1.9
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - galleryplus: 12
 - music: 0.3.5
 - news: 5.3.8
 - ownnote: 1.0
 - roundcube: 2.5.4
 - tasks: 0.6.0
 - templateeditor: 0.1
 - user_ldap: 0.6.1
Disabled:
 - encryption
 - files_external
 - files_locking
 - gallery
 - provisioning_api
 - tasks_enhanced
 - user_external
 - user_webdavauth
 - videos
```

**Comment by RealRancor** [comment]
Please check your logfiles as asked in the issue template:

https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version

**Comment by alex42ka** [comment]
Seems to be an issue of the roundcube app. After I've deactivated the app OC again works as expected.
