### ISSUE TITLE
Upgrade to 8.1 error

### ISSUE THREAD

**Issue by seblezinzin** [owncloud/core#17459]
Hi

Please find my error during upgrade :

OC\DB\MigrationException: An exception occurred while executing 'ALTER TABLE oc_oc_activity_ga7adr3z4klwh CHANGE `subjectparams` `subjectparams` VARCHAR(4000) NOT NULL, CHANGE `messageparams` `messageparams` VARCHAR(4000) DEFAULT NULL, CHANGE `file` `file` VARCHAR(4000) DEFAULT NULL, CHANGE `link` `link` VARCHAR(4000) DEFAULT NULL': SQLSTATE[HY000]: General error: 1114 The table '#sql-32c0_1289c42' is full

**Comment by alon1205** [comment]
Another error:
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing ' DELETE FROM `oc_lucene_status` WHERE `fileid` IN ( SELECT `fileid` FROM ( SELECT `fileid` FROM `oc_lucene_status` GROUP BY `fileid` HAVING count(`fileid`) > 1 ) AS `mysqlerr1093hack` )': SQLSTATE[HY000]: General error: 1598 Binary logging not possible. Message: Transaction level 'READ-COMMITTED' in InnoDB is not safe for binlog mode 'STATEMENT'

**Comment by RealRancor** [comment]
@alon1205 thats an different issue where you can find the infos here:

https://doc.owncloud.org/server/8.1/admin_manual/maintenance/upgrade.html#troubleshooting

**Comment by alon1205** [comment]
Forgive me. I thought this is just a general thread on problems with 8.1 upgrades. I am sorry and thank you for your link!

-A

**Comment by seblezinzin** [comment]
any idea on my problem ?

**Comment by seblezinzin** [comment]
Environment

Server Configuration

OS: Linux 3.10.23-xxxx-std-ipv6-64
Web server: Apache2 2.2.22
Database: MySQL Ver 14.14 Distrib 5.5.43,
PHP version: 5.4.42
ownCloud version: 8.4.0

Client Configuration

Browser: Chrome
Operating system: Windows 7


How to reproduce : 
run ./occ upgrade 

upgrade from 8.0.4 to 8.1

**Comment by DeepDiver1975** [comment]
> General error: 1114 The table '#sql-32c0_1289c42' is full

running out f disk space :wild_guess:

**Comment by karlitschek** [comment]
Yes. No diskspace or some other configuration problem on the DB side. Please check your database log why the DB it is 'full'
