### ISSUE TITLE
Allow the administrator to define the base URL for Federated Cloud IDs

### ISSUE THREAD

**Issue by strugee** [owncloud/core#17458]
I have an ownCloud server at `cloud.strugee.net`. I control both `cloud.strugee.net` and `strugee.net`. It would be super neat if I was able to e.g. define something in `strugee.net/.well-known` that other ownCloud servers would then use to find the ownCloud server at `cloud.strugee.net`. Then I could use "alex@strugee.net" as my Federated Cloud ID, instead of "alex@cloud.strugee.net".

This is useful because then I can use the same address for my email and my Federated Cloud ID.

**Comment by rullzer** [comment]
Dup (kind of) of #14746
