### ISSUE TITLE
oC 8.1.0 "Installation is in transit between the old Encryption" even encryption wasn't enabled

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#17450]
### Steps to reproduce
1. Have a working 8.0.5 installation which never had the old encryption app enabled
2. Update to oC 8.1.0
3. Have a look at the error logs

### Expected behaviour
No messages about old Encryption shown in logfiles

### Actual behaviour
Messages about old Encryption shown in logfiles

### Server configuration
**Operating system**: Debian Jessie

**Web server:** NginX 1.7.x

**Database:** MariaDB 10.0.x

**PHP version:** 5.6.x

**ownCloud version:** 8.1.0

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

#### ownCloud log (data/owncloud.log)
```
{"reqId":"JJZ1j54fC7Dyn+SXpoN4","remoteAddr":"x.x.x.x","app":"no app in context","message":"Installation is in transit between the old Encryption (ownCloud <= 8.0)\n\t\t\tand the new encryption. Please enable the \"Default encryption module\"\n\t\t\tand run 'occ encryption:migrate'","level":2,"time":"2015-07-07T16:56:53+02:00"}
```

**Comment by karlitschek** [comment]
@schiesbn Can you have a look?

**Comment by RealRancor** [comment]
In the database the following can be found:

oc_encryption
$Username 	server-side 	0 	0

oc_preferences
No entries with migration_status or files_encryption

**Comment by t2d** [comment]
same here

**Comment by ekric** [comment]
Here too, Apache 2.2.22, PHP 5.4, MySQL 5.5

**Comment by RealRancor** [comment]
@t2d and @ekric

> same here 
> Here too

In form of you're getting the same error or you never had enabled the encryption app?

**Comment by t2d** [comment]
I never had the encryption app and get the same error.

**Comment by ekric** [comment]
I may have had it enabled in version 7 but not since then.

I'm getting the same error but I dont want to enable the app.

**Comment by schiesbn** [comment]
do you have any encryption related entries in you oc_appconfig table?

**Comment by schiesbn** [comment]
Unfortunately there is now way to distinguish between:

- Encryption was enabled on ownCloud 8.0 and the migration disabled the app
- Encryption was enabled at some point in time, you disabled it already and continued without encryption and updated to 8.1.

The system state is in both cases exactly the same.

**Comment by t2d** [comment]
> do you have any encryption related entries in you oc_appconfig table?

I only find the following

| files_encryption | enable_encryption | false      |
| files_encryption | enabled           | no         |
| files_encryption | installed_version | 0.2        |
| files_encryption | types             | filesystem |

**Comment by RealRancor** [comment]
My appconfig is containing:

```
| files_encryption       | enabled                            | no                                                  |
| files_encryption       | installed_version                  | 0.4                                                 |
| files_encryption       | publicShareKeyId                   | pubShare_21905fbd                                   |
| files_encryption       | recoveryAdminEnabled               | 1                                                   |
| files_encryption       | recoveryKeyId                      | recovery_e2acb2ff                                   |
| files_encryption       | types                              | filesystem
```

but i'm sure i never had encryption enabled (also not accidentally).

**Comment by schiesbn** [comment]
You can just delete them. You need to have enabled encryption at some point in time. That's the only way you can get this entries.

**Comment by t2d** [comment]
I don't remember, but maybe. For future notice, I deleted the
corresponding lines with `DELETE FROM oc_appconfig WHERE appid =
'files_encryption';`

**Comment by RealRancor** [comment]
Just wanted to post the same. Deleting the lines from oc_appconfig solved the issue. @schiesbn case close or is there something else to do here?

**Comment by schiesbn** [comment]
I don't think there is more we can do beside telling people to delete this entries. As said, it is not possible to decide between the two states (1) encryption was just disabled on upgrade and you need to migrate to the new one (2) the database entries are old entries from the past

**Comment by ekric** [comment]
Error 	PHP 	Array to string conversion at .../lib/private/template/functions.php#36 	2015-07-08T17:46:02+00:00
Error 	PHP 	Array to string conversion at ../lib/private/template/functions.php#36 	2015-07-08T17:45:36+00:00

Since it was mentioned here: https://github.com/owncloud/core/issues/16928

Does it have something to do with encryption?

**Comment by RealRancor** [comment]
@ekric Just picking a random issue about encryption and asking a question is not the best way. If you got problem with that post a new issue using the issue template. :-)
