### ISSUE TITLE
Undefined index: REMOTE_ADDR 

### ISSUE THREAD

**Issue by fda77** [owncloud/core#17460]
In logfile:

Error 	PHP 	Undefined index: REMOTE_ADDR at /www/htdocs/web/owncloud/lib/private/appframework/http/request.php#481 

I think this is because i use a SSL proxy (all-inkl.com). The client ip is there in "HTTP_X_FORWARDED_FOR"

SO the forward to https if accesing by http does not work

**Comment by DeepDiver1975** [comment]
@fda77 which owncloud version are you using? THX

**Comment by fda77** [comment]
Oh, sorry i forgot.
I noticed this after updating 8.0 > 8.1

**Comment by webwude** [comment]
Same here:
Upgrade from 8.0. to 8.1. Provider all-inkl.com with SSL proxy.

Log looks quite overcrowded:
Error	PHP	Undefined index: REMOTE_ADDR at /www/htdocs//owncloud/lib/private/appframework/http/request.php#481	July 09, 2015 11:47:14
Error	PHP	Undefined index: REMOTE_ADDR at /www/htdocs//owncloud/lib/private/appframework/http/request.php#481	July 09, 2015 11:47:14
Error	PHP	Undefined index: REMOTE_ADDR at /www/htdocs//owncloud/lib/private/appframework/http/request.php#481	July 09, 2015 11:47:13
Error	PHP	Undefined index: REMOTE_ADDR at /www/htdocs//owncloud/lib/private/appframework/http/request.php#481	July 09, 2015 11:47:13
Error	PHP	Undefined index: REMOTE_ADDR at /www/htdocs//owncloud/lib/private/appframework/http/request.php#481	July 09, 2015 11:47:12
Error	PHP	Undefined index: REMOTE_ADDR at /www/htdocs//owncloud/lib/private/appframework/http/request.php#481	July 09, 2015 11:46:29
Error	PHP	Undefined index: REMOTE_ADDR at /www/htdocs//owncloud/lib/private/appframework/http/request.php#481	July 09, 2015 11:46:29
Error	PHP	Undefined index: REMOTE_ADDR at /www/htdocs//owncloud/lib/private/appframework/http/request.php#481	July 09, 2015 11:46:29
Error	PHP	Undefined index: REMOTE_ADDR at /www/htdocs//owncloud/lib/private/appframework/http/request.php#481	July 09, 2015 11:46:29
Error	PHP	Undefined index: REMOTE_ADDR at /www/htdocs//owncloud/lib/private/appframework/http/request.php#481	July 09, 2015 11:46:29
Error	PHP	Undefined index: REMOTE_ADDR at /www/htdocs//owncloud/lib/private/appframework/http/request.php#481	July 09, 2015 11:46:29
Error	PHP	Undefined index: REMOTE_ADDR at /www/htdocs//owncloud/lib/private/appframework/http/request.php#481	July 09, 2015 11:46:29
Error	PHP	Undefined index: REMOTE_ADDR at /www/htdocs//owncloud/lib/private/appframework/http/request.php#481	July 09, 2015 11:46:29
Error	PHP	Undefined index: REMOTE_ADDR at /www/htdocs//owncloud/lib/private/appframework/http/request.php#481	July 09, 2015 11:46:29
Error	PHP	Undefined index: REMOTE_ADDR at /www/htdocs//owncloud/lib/private/appframework/http/request.php#481	July 09, 2015 11:46:28
Error	PHP	Undefined index: REMOTE_ADDR at /www/htdocs//owncloud/lib/private/appframework/http/request.php#481	July 09, 2015 11:46:28
Error	PHP	Undefined index: REMOTE_ADDR at /www/htdocs//owncloud/lib/private/appframework/http/request.php#481	July 09, 2015 11:46:28
Error	PHP	Undefined index: REMOTE_ADDR at /www/htdocs//owncloud/lib/private/appframework/http/request.php#481	July 09, 2015 11:46:27
Error	PHP	Undefined index: REMOTE_ADDR at /www/htdocs//owncloud/lib/private/appframework/http/request.php#481	July 09, 2015 11:46:20
Error	PHP	Undefined index: REMOTE_ADDR at /www/htdocs//owncloud/lib/private/appframework/http/request.php#481	July 09, 2015 11:46:20

**Comment by DeepDiver1975** [comment]
fix for 8.1.1 is there https://github.com/owncloud/core/pull/17697
