### ISSUE TITLE
no files visible in webbrowser after upgrade 8.0.4 to 8.1

### ISSUE THREAD

**Issue by dh-connect** [owncloud/core#17461]
can't see my files in the webbrowser, tried it in different webbrowsers safari 8.0.7 and firefox 39.0 on different systems windows/mac, i set strong permissions by script, i changed location of ocdata folder to other location (not under /var/www/owncloud), syncing files with oc client 1.8.3 works, no error in oc log, whatever link i click in files menue (all files, trash can, ... besides settings) nothing changes in the right frame, it stays white, in other apps the menue works

system: debian 8u1
php: 5.6.9
apache: 2.4.10
oc version: 8.1.0.8
mysql: 5.5.43
active apps:
 Activity 2.0.1/ Bookmarks 0.4/ Calendar 0.7.0/Contacts 0.4.0.0/ Deleted files 0.6.3/ Documents 0.9.0/ File Locking/First Run Wizard 1.1/ Mail Template Editor 0.1/ PDF Viewer 0.7/Pictures 0.6.0/
Provisioning API 0.2/ Share Files 0.6.2/ Text Editor 0.4/ Updater 0.6 /Versions 1.0.6/ Video Viewer 0.1.3/ Gallery 12/ Mail 0.1.3/ News 5.3.8/ Share Links 1.0.1/Tasks 0.6.0/ Mozilla Sync 1.4/ Music 0.3.5/ Notes 1.1.0/ocPassman 1.2.30/ownCloud SMS 1.5.0

config.php
<?php
$CONFIG = array (
  'instanceid' => '?',
  'passwordsalt' => '?',
  'secret' => '?',
  'trusted_domains' => 
  array (
    0 => '?',
  ),
  'datadirectory' => '/home/oc/data',
  'overwrite.cli.url' => 'http://?/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'oc',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '?',
  'dbpassword' => '?',
  'installed' => true,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => '?',
  'mail_domain' => '?',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtpsecure' => 'ssl',
  'mail_smtphost' => '?',
  'mail_smtpname' => '?',
  'mail_smtppassword' => '?',
  'theme' => '',
  'maintenance' => false,
  'loglevel' => 1,
);

Are you using external storage: no
Are you using encryption: no
Are you using an external user-backend: no

**Comment by dh-connect** [comment]
found this here: 
"Occasionally, files do not show up after a upgrade. A rescan of the files can help:
$ sudo -u www-data php console.php files:scan --all"

i ran it, but i didn't stop scanning files, it scans my files over an over again like an infinite loop,
so i had to kill the process, scan had no effect on the issue

**Comment by oparoz** [comment]
Try disabling the Pictures app and do a ctrl+F5 to see if it helps

**Comment by dh-connect** [comment]
thanks that was it, now i can see my files

**Comment by oparoz** [comment]
Thanks!

**Comment by fidelito** [comment]
Do both things above work for me as well. i am running the latest owncloud 8 version.
