### ISSUE TITLE
Upgrade from 8.0.4 to 8.1.0.8 produces erroneous "/dev/urandom" warning

### ISSUE THREAD

**Issue by anonimal** [owncloud/core#17465]
### Steps to reproduce
Upgrade from 8.0.4 to 8.1.0.8 via the WebUI

### Expected behaviour
Smooth sailing.

### Actual behaviour
On admin page, under "Security & setup warnings":

"/dev/urandom is not readable by PHP which is highly discouraged for security reasons. Further information can be found in our documentation."

### Reality

/dev/urandom IS readable by PHP, it is enabled in open_basedir, and a tweaked excerpt from settings/controller/checksetupcontroller.php proves that PHP has /dev/urandom access:

$ vim test.php
<?php
if(@file_exists('/dev/urandom')) {
  echo "Exists\n";
  $file = fopen('/dev/urandom', 'rb');
  if($file) {
    echo "We can open\n";
    fclose($file);
    return true;
  } else { echo "We cannot open\n"; }
} else { echo "Does not exist\n"; }
?>
$ php test.php
Exists
We can open
$

POSSIBLE IMPORTANT NOTE:

I did NOT have /dev/urandom enabled in open_basdir before/during the upgrade. It was only AFTER the upgrade that I enabled /dev/urandom. Perhaps this warning is simply cached somewhere and it won't go away?

### Server configuration
**Operating system**:
Arch Linux, latest stable kernel
**Web server:**
Apache 2.4.12-4
**Database:**
MariaDB 10.0.20
**PHP version:**
PHP 5.6.10
**ownCloud version:** (see ownCloud admin page)
ownCloud 8.1.0 (git)
**Updated from an older ownCloud or fresh install:**
Upgrade from 8.0.4-2
**List of activated apps:**
Default official
```
If you have access to your command line run e.g.:
sudo -u http php occ app:list
from within your ownCloud installation folder
```
No relevant errors.

**The content of config/config.php:**

A default, properly configured, config. Nothing of relevance.

```
If you have access to your command line run e.g.:
sudo -u http php occ config:list system --public
from within your ownCloud installation folder
```
No relevant errors.

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

### Client configuration
Firefox

**Operating system:**
Linux

#### Web server error log
```
[authz_core:error] [pid 6023] [client 127.0.0.1:39940] AH01630: client denied by server configuration: /usr/share/webapps/owncloud/data/htaccesstest.txt
```
^ I imagine this has something to do with security checking and is not related to this issue

#### ownCloud log (data/owncloud.log)
No relevant errors reported.
Adding define( "DEBUG", 1); to config.php produces no errors.

#### Browser log
No relevant errors reported.

#### Actions
Multiple logins/logouts, clearing of cache, restarting of httpd service, produces no different result.

**Comment by rullzer** [comment]
Could put that file in a location where you can access it via your webbrowser.
Right now you are testing if the current user can acces /dev/urandom via php..

**Comment by anonimal** [comment]
Yes. Done, with same results.

$ sudo chown root:http test.php && sudo chmod o-r test.php
$ stat test.php | grep -i uid
Access: (0640/-rw-r-----)  Uid: (    0/    root)   Gid: (   33/    http)
$ sudo mv test.php /srv/http/ && firefox http://127.0.0.1/test.php
``` Browser output: "Exists We can open" ```
$ sudo -u http php test.php
Exists
We can open
$

I'll be happy to dive into some code if anyone can point me in the right direction.

**Comment by anonimal** [comment]
Update: a package uninstall, dropping of all database entries, and subsequent fresh install of ownCloud produces the same results. Seeing as this issue may not be widespread, perhaps this is an Arch Linux specific issue? I don't see how packaging would be a factor but food-for-thought none-the-less.

Attaching screenshot for posterity.

![owncloud_dev-urandom_error](https://cloud.githubusercontent.com/assets/12156341/8704295/9e9d09a6-2b11-11e5-8365-01b4da7dd489.png)

**Comment by rogatec** [comment]
Can't confirm this @anonimal - I have the same problem on a debian wheezy machine too.

**Comment by rullzer** [comment]
@LukasReschke can you have a look after your holiday?

**Comment by Bugsbane** [comment]
I have this too, also on a machine running Arch (Manjaro) + Nginx + php-fpm

/dev/urandom is world readable. Here are the permissions:
crw-rw-rw- 1 root root

**Comment by MorrisJobke** [comment]
I also tested it on my ArchLinux machine. It works here.

@LukasReschke Any idea what else could interfer the check? Something like apparmor/SELinux?

@Bugsbane @anonimal @rogatec Is some permission restricting software (apparmor/selinux) installed?

**Comment by LukasReschke** [comment]
As far I can see you executed your test script from the shell. PHP has often different permissions when running from there. Please access the following file from the web and report back the results:

```php
<?php
if(@file_exists('/dev/urandom')) {
	$file = fopen('/dev/urandom', 'rb');
	echo("File exists<br/>");
	if($file) {
		echo("File read<br/>");
		fclose($file);
	}
} else {
	echo("File does not exist<br/>");
}
```

**Comment by LukasReschke** [comment]
That said the above code is exactly what runs as setup check.

**Comment by Bugsbane** [comment]
When I run that I get "File does not exist"

**Comment by Bugsbane** [comment]
@MorrisJobke No SeLinux or Apparmor here. I checked.

**Comment by MorrisJobke** [comment]
> When I run that I get "File does not exist"



> I did NOT have /dev/urandom enabled in open_basdir before/during the upgrade. It was only AFTER the upgrade that I enabled /dev/urandom.

Also in the correct php.ini file? And I just looked at your ingo: ArchLinux usually only has one php.ini for CLI and webserver. But sometimes the settings is only applied to one of them or the webserver/php-fpm isn't restarted and the setting isn't loaded already. Can you check that?

**Comment by Bugsbane** [comment]
So, not quite clear. Which ini files should I be checking for what exactly? I restarted php-fpm repeatedly.

**Comment by Xenopathic** [comment]
Unable to reproduce here too. I could get the warning to appear if I enabled `open_basedir` without specifying `/dev`, but adding `/dev` or `/dev/urandom` makes the error disappear.

**Comment by rogatec** [comment]
* @MorrisJobke neither Selinux nor apparmor is installed.
* I checked the small script from @LukasReschke and the browser output was "file does not exist".
* Afterwards I did the procedure from @Xenopathic and put /dev/urandom in the open_basedir in my loaded php.ini (not cgi).
* This time the script output was "file exists".

> **Unfortunately** the security hint in the administration view still says ""/dev/urandom is not readable by PHP which is highly discouraged for security reasons. Further information can be found in our documentation."

**Comment by MorrisJobke** [comment]
@Bugsbane To check which php.ini is loaded for the webserver environment place following file in the webserver directory and open it in a browser:

```
<?php

phpinfo();
```

There you can see "Loaded Configuration File" and "Additional .ini files parsed" where all ini files that are loaded specified. Hopefully this helps to fix your issue.

**Comment by Xenopathic** [comment]
@anonimal can you try the above steps and see if it fixes your issue?

**Comment by anonimal** [comment]
Hello everyone, I'm glad to see that more people have found the time to look at this issue. I will respond for historical purposes before providing a solution because apparently, for this specific issue, we were all looking in the wrong places - but we were all correct in doing so, :satisfied: lol.

@LukasReschke that is essentially the same code I tried in my original report and I've already posted those results when viewing it from a browser. The new code snippet also produces the same positive results - as it is nearly identical code.

I am running grsecurity with gradm currently disabled. No errors, no events, nothing blocked, nothing reported kernel-side, TPE is currently *not* enabled. I have no evidence supporting the possibility that this is an ASLR or RBAC issue.

@MorrisJobke php.ini settings look fine. Countless restarts, checks, re-checks, and more checks. There is only one instance of php.ini running and <code>phpinfo();</code> proves that. The only other extensions running are <code>apcu</code> and <code>suhosin</code>. I have disabled <code>suhosin</code> but still receive the same erroneous <code>/dev/urandom</code> result.

@Xenopathic as I said in my original report, <code>/dev/urandom</code> has been added to <code>open_basedir</code> in <code>php.ini</code> but OC still gives the same erroneous <code>/dev/urandom</code> message. I've also tried adding <code>/dev/</code> to <code>open_basedir</code> for *testing purposes only* **and** added both <code>/dev/</code> and  <code>/dev/urandom</code> to <code>open_basedir</code> but the same erroneous result is given. IMHO: giving the entire <code>/dev</code> tree to PHP for what we're doing here is silly and bad opsec, so I don't see that option as a viable solution.

#### Solution
The problem was not with PHP but with the Apache VirtualHost file provided by Arch for ownCloud. And by problem, I mean not necessarily a problem but an oversight that was <i>mostly my fault</i> but easy enough for anyone to have encountered.

The addition of <code>/dev/urandom</code> needed to be in <code>php_admin_value open_basedir</code> <b>within the vhost file</b>, and not within <code>/etc/php/php.ini</code>


 Thank you everyone for contributing.

**Comment by Bugsbane** [comment]
So, @anonimal, if we now accurately know what the problem was - how can we who oare encountering it, patch our current installs to fix the issue? Can we use the same text in the vhosts file if we're on nginx as if we were on Apache?

**Comment by tetsuo76** [comment]
I had the same problem under Centos 6.5. Adding /dev/urandom in open_basedir solved it for me. Many thanks.

**Comment by Spelaea** [comment]
I also had the same problem with my docker-image (running on Arch Linux). Adding /dev/urandom to the apache-vhost-section fixed it. Thank's a lot! :)

**Comment by jgeerdink** [comment]
@anonimal In what directory did you placed this? Because when I add it for my root folder, where owncloud is placed, it does not work.

**Comment by Spelaea** [comment]
@jgeerdink you have to put it in the apache-configuration; the relevant portion of my apache2-configuration looks like this:
```
<Directory /usr/share/webapps/owncloud/>
    Options FollowSymlinks
    AllowOverride all
    Require all granted
    php_admin_value open_basedir "/srv/http/:/home/:/tmp/:/usr/share/pear/:/usr/share/webapps/owncloud/:/etc/webapps/owncloud:/dev/urandom"
</Directory>
```
I just added the ":/dev/urandom" to the line.

**Comment by jgeerdink** [comment]
@Spelaea I use this line, but that does not work:

Am I missing something?

	<Directory /home/admin/domains/mydomain.com/public_html>
    Options FollowSymlinks
    AllowOverride all
    Require all granted
    php_admin_value open_basedir "/home/admin/:/tmp:/var/tmp:/usr/local/lib/php/:/usr/local/php55/lib/php/:/dev/urandom"
	</Directory>

**Comment by Spelaea** [comment]
Did you restart apache / reload the configuration? Are you sure apache is using this specific configuration file?
I stopped my docker container, edited the file and started it again; it worked straight away, I can't think what else it could be.

**Comment by anonimal** [comment]
@Bugsbane Yes, the solution is simply a matter of adding <code>:/dev/urandom</code> to your PHP's <code>open_basedir</code>. The solution is independent of webserver-type as it relates solely to PHP. The issue I was facing was simply a matter of precedence: Apache gave higher precedence to the vhost's file than to <code>httpd.conf</code>, and I was unaware of that at the time.

@jgeerdink Your vhost file should look more like what @Spelaea provided. <code>\<Directory ...\></code>should point to your OC installation instance. What you provided does not appear to have any relation to OC. Also, be sure that your <code>httpd.conf</code> has the OC vhost file included with the <code>Include</code> directive.

**Comment by jgeerdink** [comment]
@anonimal Thanks! But my OC installation is not placed in a folder like that. Its placed directly in the public_html folder of DirectAdmin. The httpd.conf does include the vhost file.

**Comment by RealRancor** [comment]
Btw. only /dev should be added to open_basedir not /dev/urandom. open_basedir is, as the name is saying used for dirs and not for such virtual files like /dev/urandom

**Comment by anonimal** [comment]
@RealRancor WRONG! Sorry, but that *seriously* needs to be emphasized.

1. As I've stated before, with similar wording: granting read access to your entire <code>/dev</code> tree on a compromised webserver is just plain stupid. Type <code>find /dev -perm -o+r</code> to see what could be readily available to any malicious PHP. On a per-system basis, there may be sensitive information available that could be easily made *unavailable* with a properly designed <code>open_basedir</code>.

2. Read https://github.com/php/php-src/blob/master/main/fopen_wrappers.c in its entirety and follow the white rabbit until you see that PHP (without discriminating between file and directory in it's implemenation of file-handling) simply and eloquently wraps the wonderful <code>fopen()</code> call which, in itself, does not discriminate against files or directories because, in Linux/UNIX: <b>everything is a file</b> or a process and <b>a directory is nothing more than a file that lists other files</b>. This is why <code>/dev/urandom</code> works at all (please, prove me wrong).  As for Windows, I imagine the abstraction is left to the Windows API, but this ticket is for Linux so I really don't care.

3. Regarding the decision to call it <code>open_basedir</code>: if you look in the log, dating back to August 15, 1998, the decision was made to change it from <code>fopen_basedir</code> to <code>open_basedir</code> to <i>"be a little more accurate about what it does"</i>. This makes complete sense and supports the claims made in point 2 in that directories and files are interchangeable and <code>fopen_basedir</code> was not limited to either a "file" or "directory" since both were mutually handled by the same code. Perhaps the original authors can make a statement on this if anyone cares to contact them and refer them to this thread.

To those reading: please be aware of the aforementioned and - virtual or not - do not give your webserver access to your entire <code>/dev</code> filesystem or any branch that could recursively expose sensitive information - unless it is necessary. For anyone wishing to argue these points, please provide empirical evidence that argues on the contrary so that we can all learn. Thank you.

**Comment by RealRancor** [comment]
@anonimal And then why my PHP is not able to access /dev/urandom when /dev/urandom is added to an open_basedir but is able when only /dev is added?

**Comment by anonimal** [comment]
@RealRancor Thanks for the tip-off, I'll take a look.
