### ISSUE TITLE
Allow automatic Dropbox registration with an administrator-provided API key

### ISSUE THREAD

**Issue by strugee** [owncloud/core#17462]
The current "add Dropbox to ownCloud" flow is extremely non-user-friendly. Registering an app with Dropbox will be really confusing for less technical users, even with documentation.

It would be awesome if the server admin could register their ownCloud instance with Dropbox, once, and then everyone on the server could use those API keys to link their personal storage.

**Comment by strugee** [comment]
Is something ownCloud is interested in implementing? I understand you don't have infinite time but it'd be nice to at least get this off the "proposed" list

**Comment by PVince81** [comment]
closing in favor of https://github.com/owncloud/core/issues/24496
