### ISSUE TITLE
Error messages when using syslog for logging

### ISSUE THREAD

**Issue by tuxmaster** [owncloud/core#17467]
Version: 8.1
When set:
'log_type' => 'syslog',
'loglevel' => 1,
'logfile' => '',
'logtimezone' => 'FooTZ',
'log_authfailip' => true,

every call to the admin page will result an error message like this: {PHP} filesize(): stat failed for /var/www/html/owncloud/data/owncloud.log at /var/www/html/owncloud/settings/admin.php#49

**Comment by MorrisJobke** [comment]
Fix is in #17969
