### ISSUE TITLE
go.php for 8.1 ES is not correct

### ISSUE THREAD

**Issue by carlaschroder** [owncloud/core#17463]
hey all, after a lovely and uneventful upgrade to 8.1 ES I found that the doc links are all incorrect. These examples are from the Admin page:

Sharing http://doc.owncloud.com/server/8.0EE/go.php?to=admin-sharing
Federated Cloud Sharing http://doc.owncloud.com/server/8.0EE/go.php?to=admin-sharing-federated
Cron http://doc.owncloud.com/server/8.0EE/go.php?to=admin-background-jobs

As you can see, it's the wrong version and should be 8.1 and not 8.0, and it's plain 8.1, not 8.1EE, and they should be https. So the Cron URL, for example, should be https://doc.owncloud.com/server/8.1/go.php?to=admin-background-jobs 

I don't know how go.php is sourced when the builds are created; both Server and Enterprise 8.1 should use the exact same go.php, https://github.com/owncloud/documentation/blob/stable8.1/go.php. The 8.x  documentation manuals are unified in the owncloud/documentation repo; the owncloud/documentation-enterprise repo is only for legacy manuals 7.xEE and older.

Anything I can do let me know.

**Comment by carlaschroder** [comment]
By the way, I know we have not released the Enterprise edition yet, but my local 8.whatever ES displayed the upgrade notification, so I upgraded.

**Comment by karlitschek** [comment]
@danimo @jospoortvliet FYI

**Comment by jospoortvliet** [comment]
@karlitschek doesn't this have to be fixed in the code of core? Nothing we can do on the server about broken links in ownCloud... Though, like Carla, I don't know how these links are generated.

**Comment by karlitschek** [comment]
Got it. True. 
@DeepDiver1975 What do you think?

**Comment by carlaschroder** [comment]
I also need to know how the ownCloud PDF manuals are packaged with the releases, so I can make sure they get the most current versions.

**Comment by karlitschek** [comment]
@carlaschroder There are generated using the corresponding branch. So everything that is in the documentation 8.1 branch will be in the PDF in the 8.1 releases. 
Or do you mean the EE release? :-)

**Comment by carlaschroder** [comment]
@karlitschek, I mean the 8.1 ES release, to be pedantically accurate :)  All 8.x manuals, Server and Enterprise, are in the owncloud/documentation repo. The documentation-enterprise repo is only for 7.x and older.

**Comment by carlaschroder** [comment]
I think I get it now :)

**Comment by carlaschroder** [comment]
Who packages the builds, @jnweiger? This looks like a packaging issue.

**Comment by jnweiger** [comment]
The build in ee:8.1 pulls a copy of the server admin manual from https://doc.owncloud.org/server/8.1/ownCloudServerAdminManual.pdf
I've triggered a rebuild pulling in the Manual dated July 10.

Regarding go.php: This is not touched during my part of packaging.

**Comment by carlaschroder** [comment]
Thanks @jnweiger. So getting the correct go.php is not packaging but building. Help me out here peoples!! We can't have releases all full of bad doc URLs. Who can fix this?

**Comment by karlitschek** [comment]
@danimo Can you help to clarify how this works?

**Comment by DeepDiver1975** [comment]
go.php is in the documentation repos and is pushed to the doc servers as soon as any new docs are being built.

^ this is at least how we initially did build it.

**Comment by DeepDiver1975** [comment]
> As you can see, it's the wrong version and should be 8.1 and not 8.0, and it's plain 8.1, not 8.1EE, and they should be https. So the Cron URL, for example, should be https://doc.owncloud.com/server/8.1/go.php?to=admin-background-jobs

the version in this case is taken from the theme - which points to 8.0 and not to 8.1.

https://github.com/owncloud/enterprise/blob/master/theme/defaults.php#L92

@rperezb @jnfrmarks another task for the qa check list for major releases

**Comment by carlaschroder** [comment]
Setting the version number in the theme seems daft. I expect the settings in conf.py to be used.

**Comment by DeepDiver1975** [comment]
Well - the links to the docs are generated with in the owncloud instance. The instance knows it's version. In case of theming we allow modifying the url so that different doc installations can be used.

**Comment by carlaschroder** [comment]
Is it really necessary to configure the version number in the theme? This seems like asking for trouble. The doc branches are the same as the core branches, so just pull from the same branch.

**Comment by DeepDiver1975** [comment]
> Is it really necessary to configure the version number in the theme? This seems like asking for trouble. The doc branches are the same as the core branches, so just pull from the same branch.

Well simply because of the fact that we once had 8.0 vs 8.0EE we made the decision back then.
Thinking about actually somebody rebranding ownCloud - changing the version to some extend might be kind of reasonable.

**Comment by carlaschroder** [comment]
OK that makes sense. Thanks for clarifying @DeepDiver1975

**Comment by DeepDiver1975** [comment]
fixed
