### ISSUE TITLE
Debian packages: "owncloud-server" transitively depends on "owncloud"

### ISSUE THREAD

**Issue by SebastianS90** [owncloud/core#17469]
### Steps to reproduce
1. Have "owncloud-server" 8.0 installed from the provided debian 7.0 packages.
2. "owncloud" and "owncloud-config-apache" are not installed
3. Try to update to 8.1 via aptitude

### Expected behaviour
"owncloud-config-apache" does not get installed

### Actual behaviour
"owncloud-server" depends on "owncloud-app-encryption" which depends on "owncloud". "owncloud" depends on "owncloud-config-apache" and therefore that package gets installed.

### Server configuration
**Operating system**: Debian 7.0

**Web server:** Nginx

**Comment by karlitschek** [comment]
@jnweiger Can you have a look?

**Comment by jnweiger** [comment]
Thanks for testing with nginx!
sr with a fix: https://build.opensuse.org/request/show/315612

**Comment by jnweiger** [comment]
Deployed. rebuild 8.1.0-2 will have the fix, as soon as the mirrors propagate this.

**Comment by SebastianS90** [comment]
Thanks, it works now as expected.

**Comment by jnweiger** [comment]
Thanks for confirming!
