### ISSUE TITLE
SQL Error while upgrading to 8.1 

### ISSUE THREAD

**Issue by Sickboy2003** [owncloud/core#17479]
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing ' DELETE FROM `oc_lucene_status` WHERE `fileid` IN ( SELECT `fileid` FROM ( SELECT `fileid` FROM `oc_lucene_status` GROUP BY `fileid` HAVING count(`fileid`) > 1 ) AS `mysqlerr1093hack` )': SQLSTATE[HY000]: General error: 1665 Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at least one table uses a storage engine limited to row-based logging. InnoDB is limited to row-logging when transaction isolation level is READ COMMITTED or READ UNCOMMITTED.

**Comment by RealRancor** [comment]
See: https://github.com/owncloud/core/issues/17470 and all the other duplicates
