### ISSUE TITLE
Nginx proxy_pass working partially

### ISSUE THREAD

**Issue by domrod** [owncloud/core#17476]
Hi,

I have the following architecture:

- 1 VM (Debian 8) with ownCloud (installed by packages) with local IP 10.250.222.220.
This VM stands as a backend. 

ownCloud may be accessed directly through http://10.250.222.220

- 1 VM (Debian 8) with Nginx installed which stands as a front end.

In the latter, the following line should proxy pass the ownCloud VM:

        location /drive/ {
                proxy_pass http://10.250.222.220/;
        }

to have owncloud accessible through http://PUBLIC_IP/drive/

However, this is the result:

![proxy_pass](https://cloud.githubusercontent.com/assets/5418910/8567512/2aa18ffa-2566-11e5-8377-ecc1c64781d1.png)

So all css, img and scripts are not correctly transformed.

I've done numerous tests, following many recommandations on Nginx proxy pass for ownCloud, but I did not see any improvement.

Does anybody have some advice on that issue?

Thanks.

**Comment by Xenopathic** [comment]
Thanks for reporting this issue to us! Could you please fill out the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md), it will really help us diagnose and fix your problem.

**Comment by domrod** [comment]
Thanks for your reply. 

I will collect informations as shown in on your template and upload those shortly.

**Comment by slasse** [comment]
I am working on a similar setup, a front-end server running nginx as a reverse proxy and a back-end server running owncloud with apache2 as web server.

i initially had the same problem you have and solved it by adding another location block in the nginx config file on the front-end server:

server {
       listen 80;
       server_name "url";
       access_log /var/log/nginx/owncloud.access;
       error_log /var/log/nginx/owncloud.error;
       location / {
       proxy_pass http://"back-end ip"/owncloud/;
       proxy_set_header Accept-Encoding "";
       proxy_set_header Host $host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       client_max_body_size 1024M;
       proxy_read_timeout 600s;
       proxy_send_timeout 600s;
       proxy_connect_timeout 600s;
       }

location /owncloud {
       proxy_pass http://"back-end ip"/owncloud;
       proxy_set_header Accept-Encoding "";
       proxy_set_header Host $host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       client_max_body_size 1024M;
       proxy_read_timeout 600s;
       proxy_send_timeout 600s;
       proxy_connect_timeout 600s;
       }
}


you need to edit for your url and back-end ip.

but then i run into another issue, when i try to login i just get the login screen again.

i suspect that i am missing something else in the nginx proxy but am not sure what yet.

there are 2 errors in the owncloud log that are entered when i try to log in:

Error	PHP	Invalid argument supplied for foreach() at /var/www/owncloud/lib/private/app.php#1233	
Error	PHP	preg_split() expects parameter 2 to be string, array given at /var/www/owncloud/lib/private/app.php#1230	

and one in the nginx access log that i havn't figured out yet: 
"GET /owncloud/core/vendor/jquery/dist/jquery-migrate.min.map HTTP/1.1" 404 280 "-" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36"

"/owncloud/core/vendor/jquery/dist" doesn't exist on the server running onwcloud so that could explain it but it works perfectly when i connect directly to the owncloud server so i am not sure if that is the cause of the problem.

maybe you can try with the nginx config i provided and let me know if you also have the problem with logging in

**Comment by domrod** [comment]
Thanks slasse, this is a nice workaround which works :)

The drawback is that I have now:

http://public_url/ 
and
http://public_usrl/drive 

which give the same (correct) ownCloud page, making ownCloud the default home page, which is the not the wanted behavior.

But at least, there is a progression on that subject :)

**Comment by domrod** [comment]
@sasse: I don't obtain the login screen again after login. 

Do you put a "/" after your login url in your browser? In my case, it solves the problem.

**Comment by domrod** [comment]
As asked by @Xenopathic, here are informations based on [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md), when I don't use the workaroung provided by @slasse.

### Steps to reproduce
1. install owncloud in a vm (debian 8 or opensuse 13.2, whatever) with distribution packages
Say that this VM has a local IP 10.250.222.220
2. install nginx in another vm (debian8)
3. use the 2nd vm to proxy pass the 1st one with  the following option in nginx conf

```javascript
    location /drive/ {
            proxy_pass http://10.250.222.220/;
    }
```
### Expected behaviour

* What should appear:

![waited](https://cloud.githubusercontent.com/assets/5418910/8590228/0ca288a6-261f-11e5-9ba3-f41159056ef7.png)

* What we have

![obtained](https://cloud.githubusercontent.com/assets/5418910/8590242/376cabf2-261f-11e5-9e4a-6f59059eae8c.png)

### Server configuration
**Operating system**: Debian 8 or opensuse 13.2

**Web server:** 
* Apache on owncloud server (also tested with nginx on owncloud server)
* nginx on proxy server

**Database:** Mysql 5.5.43-0+deb8u1

**PHP version:** 5.6.9+dfsg-0+deb8u1

**ownCloud version:** 8.1

**Updated from an older ownCloud or fresh install:**
fresh install

**List of activated apps:**

Enabled:
 - activity: 2.0.1
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1

Disabled:
 - encryption
 - external
 - files_external
 - user_external
 - user_ldap
 - user_webdavauth

**The content of config/config.php:**

```javascript
<?php
$CONFIG = array (
  'instanceid' => 'xxxxxxxxxx',
  'passwordsalt' => 'xxxxxxxxxxxxxx',
  'secret' => 'xxxxxxxxxxxx',
  'trusted_domains' => 
  array (
    0 => 'xxx_owncloud_public_ip_xxx',
    1 => '10.250.222.220',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://xxx_owncloud_public_ip_xxx',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'xxxxx_db',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxxxx_dbadmin',
  'dbpassword' => 'xxxxxxxxxxxx',
  'logtimezone' => 'UTC',
  'installed' => true,
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

No ldap

### Client configuration
**Browser:** firefox and chrome

**Operating system:** linux


### Logs

#### ownCloud log (data/owncloud.log)
```
{"reqId":"pMWPXx8CPSwHadulP4Re","remoteAddr":"[HIDDEN_IP]","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/l
ib\/private\/appframework\/http\/request.php#684","level":3,"time":"2015-07-08T11:01:47+00:00"}
{"reqId":"pMWPXx8CPSwHadulP4Re","remoteAddr":"[HIDDEN_IP]","app":"PHP","message":"fopen(\/var\/www\/owncloud\/config\/config.php
): failed to open stream: No such file or directory at \/var\/www\/owncloud\/lib\/private\/config.php#191","level":3,"time":"2015-
07-08T11:01:47+00:00"}
```

#### Browser log

* The network log 
```
GET http://xxx_proxy_public_ip_xxx/core/css/styles.css [HTTP/1.1 404 Not Found 39ms]
GET http://xxx_proxy_public_ip_xxx/core/css/header.css [HTTP/1.1 404 Not Found 42ms]
GET http://xxx_proxy_public_ip_xxx/core/css/mobile.css [HTTP/1.1 404 Not Found 49ms]
GET http://xxx_proxy_public_ip_xxx/core/css/icons.css [HTTP/1.1 404 Not Found 54ms]
GET http://xxx_proxy_public_ip_xxx/core/css/fonts.css [HTTP/1.1 404 Not Found 61ms]
GET http://xxx_proxy_public_ip_xxx/core/css/apps.css [HTTP/1.1 404 Not Found 65ms]
GET http://xxx_proxy_public_ip_xxx/core/css/fixes.css [HTTP/1.1 404 Not Found 76ms]
GET http://xxx_proxy_public_ip_xxx/core/css/multiselect.css [HTTP/1.1 404 Not Found 82ms]
GET http://xxx_proxy_public_ip_xxx/core/vendor/jquery-migrate/jquery-migrate.min.js [HTTP/1.1 404 Not Found 39ms]
GET http://xxx_proxy_public_ip_xxx/core/vendor/underscore/underscore.js [HTTP/1.1 404 Not Found 39ms]
GET http://xxx_proxy_public_ip_xxx/core/vendor/handlebars/handlebars.js [HTTP/1.1 404 Not Found 40ms]
GET http://xxx_proxy_public_ip_xxx/core/js/placeholders.js [HTTP/1.1 404 Not Found 39ms]
GET http://xxx_proxy_public_ip_xxx/core/js/compatibility.js [HTTP/1.1 404 Not Found 36ms]
GET http://xxx_proxy_public_ip_xxx/core/js/oc-dialogs.js [HTTP/1.1 404 Not Found 37ms]
GET http://xxx_proxy_public_ip_xxx/core/js/l10n.js [HTTP/1.1 404 Not Found 39ms]
GET http://xxx_proxy_public_ip_xxx/core/js/octemplate.js [HTTP/1.1 404 Not Found 38ms]
GET http://xxx_proxy_public_ip_xxx/core/js/config.js [HTTP/1.1 404 Not Found 36ms]
GET http://xxx_proxy_public_ip_xxx/core/js/oc-requesttoken.js [HTTP/1.1 404 Not Found 38ms]
GET http://xxx_proxy_public_ip_xxx/core/vendor/snapjs/dist/latest/snap.js [HTTP/1.1 404 Not Found 37ms]
GET http://xxx_proxy_public_ip_xxx/core/js/jquery.avatar.js [HTTP/1.1 404 Not Found 35ms]
GET http://xxx_proxy_public_ip_xxx/core/js/backgroundjobs.js [HTTP/1.1 404 Not Found 36ms]
GET http://xxx_proxy_public_ip_xxx/apps/files_sharing/l10n/fr.js [HTTP/1.1 404 Not Found 38ms]
GET http://xxx_proxy_public_ip_xxx/apps/files_sharing/js/external.js [HTTP/1.1 404 Not Found 37ms]
GET http://xxx_proxy_public_ip_xxx/apps/files_versions/js/versions.js [HTTP/1.1 404 Not Found 37ms]
GET http://xxx_proxy_public_ip_xxx/apps/files_videoviewer/js/viewer.js [HTTP/1.1 404 Not Found 39ms]
GET http://xxx_proxy_public_ip_xxx/apps/firstrunwizard/js/jquery.colorbox.js [HTTP/1.1 404 Not Found 35ms]
GET http://xxx_proxy_public_ip_xxx/apps/gallery/l10n/fr.js [HTTP/1.1 404 Not Found 37ms]
GET http://xxx_proxy_public_ip_xxx/apps/gallery/js/slideshow.js [HTTP/1.1 404 Not Found 38ms]
GET http://xxx_proxy_public_ip_xxx/core/vendor/jsTimezoneDetect/jstz.js [HTTP/1.1 404 Not Found 38ms]
GET http://xxx_proxy_public_ip_xxx/core/js/lostpassword.js [HTTP/1.1 404 Not Found 37ms]
GET http://xxx_proxy_public_ip_xxx/core/img/loading-dark.gif [HTTP/1.1 404 Not Found 37ms]
GET http://xxx_proxy_public_ip_xxx/core/img/actions/user.svg [HTTP/1.1 404 Not Found 37ms]
GET http://xxx_proxy_public_ip_xxx/core/img/actions/password.svg
```

**Comment by slasse** [comment]
Hi Domrod,

thanks for the feedback and the tip but i keep having the same issue,

could you maybe post your nginx config file with the workaround 

and if possible also your back-end config file (apache?) so i can compare 

thanks in advance

**Comment by domrod** [comment]
@slasse I think the tip is in config.php.

Here is my updated *config.php* file

```javascript
<?php
$CONFIG = array (
  'instanceid' => 'XXXXXXXX',
  'passwordsalt' => 'XXXXXXXXXXXXXXXXXXX',
  'secret' => 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  'trusted_domains' =>
  array (
    0 => '10.250.222.220',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://PROXY_PUBLIC_IP/drive',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'XXXX_ocdb',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'XXXX_dbadmin',
  'dbpassword' => 'XXXXXXXXXX',
  'logtimezone' => 'UTC',
  'installed' => true,
  'overwritehost' => 'PROXY_PUBLIC_IP',
  'overwritewebroot'  => '/drive/',
);
```

Note the last 2 lines with *overwritehost* and *overwritewebroot* which are the parameters for my proxy VM (the second one).

**Comment by Xenopathic** [comment]
Indeed, the `overwritewebroot` and `overwritehost` parameters are vital here - ownCloud has no way of retrieving that information when run behind a reverse proxy. Do those lines fix your issue @domrod ?

**Comment by domrod** [comment]
@Xenopathic you are absolutely right. Using these 2 lines solved everything.

@slasse you don't need anymore to proxy pass "/" to onwcloud backend with the `overwritewebroot` and `overwritehost` parameters. And if your frontend uses SSL, you may also add:

`'overwriteprotocol' => 'https',`

in your config.php file.

Thanks all for your feedback.

**Comment by Xenopathic** [comment]
No problem, glad you got it fixed.

**Comment by slasse** [comment]
thanks for the help guys, i will try these suggestions later when i have the chance
