### ISSUE TITLE
SQL Error while upgrading from 8.0.4 to 8.1

### ISSUE THREAD

**Issue by Garog** [owncloud/core#17470]
An exception occurred while executing 'INSERT INTO `oc_oc_appconfig_cn2rg76a222ib` SELECT * FROM `oc_appconfig`': SQLSTATE[HY000]: General error: 1665 Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at least one table uses a storage engine limited to row-based logging. InnoDB is limited to row-logging when transaction isolation level is READ COMMITTED or READ UNCOMMITTED.

**Comment by RealRancor** [comment]
See: https://doc.owncloud.org/server/8.1/admin_manual/maintenance/upgrade.html#troubleshooting and upgrade your MySQL configuration accordingly.

If you can't follow this discussion here: https://github.com/owncloud/core/issues/16008

**Comment by Garog** [comment]
i allready did, thank you
now i need to fix my replication.

**Comment by MorrisJobke** [comment]
Solution presented -> case solved

Or am I wrong @Garog ?
