### ISSUE TITLE
Make JS getMimeIcon use the new JS mime API

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#17477]
Basically need to rewire https://github.com/owncloud/core/blob/master/apps/files/js/files.js#L166 to use the new JS mimeicon API, then mark that function as deprecated.

And of course, test that the files app, public page and co still work :smile: 

Please note that this API requires a callback, so you'll need to call the new API and then directly call the callback with the result.

@rullzer can you take care of this ?

**Comment by PVince81** [comment]
and then once we have this, we can try and find all locations in core that use the old OCA.Files.Files.getMimeIcon() and replace them directly with the new calls.

However we need to keep that old method in case third party apps are relying on it. => deprecate

**Comment by rullzer** [comment]
I'll add it to the TODO :)

**Comment by rullzer** [comment]
Start of PR in #17483

**Comment by rullzer** [comment]
Fixed in #17483
