### ISSUE TITLE
After migrating server I get a lot of conflicts on files changed during migration

### ISSUE THREAD

**Issue by enricocanino** [owncloud/core#17478]
Hi all,

I am migrating from old server to new server, in dry test, before do it definitively.

I have a server running OC 8.0.4 and Apache and I need to setup a new server with big capacity, running NGINX and the same OC 8.0.4.

I am following this procedure:

1 - install new server
2 - put old server in maintenance mode
3 - backup all data directory, including OC and APP
4 - backup up all tables on mysql
5 - restore on new server all data directory, including OC and APP
6 - restore on new server all tables on mysql
7 - modify config.php only for new server address and db parameters (db, user, password)

Testing web interface, I lost shares, the rest works fine.

Unfortunately if I start Windows Client, with the same directory monitoring, modifying only server addr and user, after few minutes it start to mark all files modified during migration as in conflict and download them.

This means that if I start all user's clients I will get a very big number of files in conflict!

On Windows we are running client version 1.8.3.5213.

Aspected behaviour: files modified during migration must be uploaded to server because they are newer, not in conflict.

I also made the following attempts:
1 - truncate os_filecache and reconstructs it by occ files:scan --all (nothing to do, the same problem but client says that download of all files)

2 - truncate os_filecache, delete .csync_journal.* from client, reconstructs oc_filecache by occ files:scan --all (nothing to do, the same problem but client says that conflict renamed all files)

Any ideas? 

Thanks in advance, I am very confused and sad.

**Comment by karlitschek** [comment]
You should never truncate the filecache table. By doing this you lose all the metadata.
The reason for the conflict files is that you no longer have the metadata and the mtimes of the files on the new server is probably different. 
I don't think this is an owncloud bug so I suggest to discuss best practices further on the owncloud forum.
Please ask this question at forum.owncloud.org
Thanks a lot.

**Comment by enricocanino** [comment]
Thanks a lot, I will better backup & restore mysql from server1 to server2.
Thanks again.
