### ISSUE TITLE
User quota is set to 10 GB, but "files" directory has a size of 16 GB

### ISSUE THREAD

**Issue by DerZeitspringer** [owncloud/core#17471]
Dear ownclouder,

there's an issue with the user quota.

### Steps to reproduce
no specific steps

### Expected behaviour
I've set a quota of "10 GB" for a regular user, before the user has logged in the first time.
I expect this to be a "hard limit".

### Actual behaviour
On the file system, the user directory has a total size of 19 GB. The "files" directory has a size of 16 GB.
afaik, all content has been uploaded via most recent Sync-Client on Windows... (this is a customers cloud, so i don't have much details about that)

![01-usermanagement](https://cloud.githubusercontent.com/assets/10948258/8565789/04df6efc-2559-11e5-903f-143bfce4069a.png)
![02-diskusage--userfolder](https://cloud.githubusercontent.com/assets/10948258/8565791/0542f8e6-2559-11e5-8fea-8a134eb594ad.png)
![03-diskusage--filesfolder](https://cloud.githubusercontent.com/assets/10948258/8565790/04fed940-2559-11e5-8b54-48a3fa7d3333.png)

### Server configuration
**Operating system**: 
Debian 8.1
ext4 filesystem

**Web server:** 
Apache 2.4.10-10

**Database:** 
MySQL 5.5.43-0+deb8u1

**PHP version:** 
5.6.9.+dfsg-0+deb8u1

**ownCloud version:** (see ownCloud admin page) 
ownCloud 8.0.4 (stable) 

**Updated from an older ownCloud or fresh install:** 
Fresh installed with 8.0, upgraded to 8.0.4 through each release

**List of activated apps:**
```
Enabled:
 - activity
 - bookmarks
 - calendar
 - contacts
 - documents
 - files
 - files_encryption
 - files_locking
 - files_pdfviewer
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - files_videoviewer
 - firstrunwizard
 - gallery
 - provisioning_api
 - templateeditor
Disabled:
 - external
 - files_external
 - user_external
 - user_ldap
 - user_webdavauth
```

**The content of config/config.php:**

```
  'instanceid' => 'ocm7qlpkz6b8',
  'trusted_domains' => 
  array (
    0 => xxx.de',
    1 => 'www.xxx.de',
  ),
  'datadirectory' => '/data/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.4.2',
  'dbname' => 'xxx',
  'dbhost' => 'xxx',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'installed' => true,
  'has_internet_connection' => false,
  'check_for_working_webdav' => false,
  'check_for_working_htaccess' => false,
  'log_type' => 'syslog',
  'proxy' => 'xxx:8083',
  'mail_from_address' => 'info',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'xxx.de',
  'theme' => '',
  'maintenance' => false,
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** 
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
independent

**Operating system:**
independent

#### Web server error log
```
if relevant, i will attach it on request
```

#### ownCloud log (data/owncloud.log)
```
if relevant, i will attach it on request
```

#### Browser log
```
if relevant, i will attach it on request
```

**Comment by karlitschek** [comment]
@PVince81 Any idea?

**Comment by PVince81** [comment]
The quota is a soft quota, and also it's the quota from the user's perspective.
Since you are using encryption, there is an additional size overhead for every file.
So while the user's actual unencrypted data is only 10 GB, encrypted data will take more space, in your case 16 GB. This is explained in the documentation here: https://doc.owncloud.org/server/8.1/user_manual/files/quota.html

**Comment by PVince81** [comment]
Works as documented => closing.
