### ISSUE TITLE
ownCloud 8.1 Debian package dependency issues

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#17487]
Dear owncloud users / developers... I'm stuck with a similar problem here.
I did the upgrade of owncloud from 8.0.4-1 to 8.1.0-1 using the debian package.
There was a dependency problem during the install
```
dpkg: owncloud-app-files-encryption: dependency problems, but removing anyway as you requested:
 owncloud-server depends on owncloud-app-files-encryption (= 8.0.4-1); however:
  Package owncloud-app-files-encryption is to be removed.
```

copied over from here: https://github.com/owncloud/core/issues/16928#issuecomment-119537807 to keep track of it

cc @jnweiger

**Comment by jnweiger** [comment]
There is no bug here. The message says that owncloud-app-files-encryption is removed during the upgrade. That is correct, as it is obsoleted by owncloud-app-encryption.

I've checked the 8.1 control file. It only mentions owncloud-app-files-encryption in Breaks and Replaces declarations, not in dependencies. 

I confirm I get the same message 'owncloud-server depends on owncloud-app-files-encryption' -- but I believe it is all misleading. It probably means, that version 8.0.4 depended(!) on owncloud-app-files-encryption although version 8.1.0 no longer does so.

It can be safely ignored. Any ideas how to suppress the message welcome.

**Comment by schiesbn** [comment]
@jnweiger thanks for checking it.
