### ISSUE TITLE
OC 8.1 logout after a couple minutes

### ISSUE THREAD

**Issue by thinking-aloud** [owncloud/core#17488]
Even with the remember me checkbox I get the message "Request unauthorized. Are you logged in?" after like 2 minutes.
This was not there before in 8.0.4/5. I stayed logged in for as long, as my browser was open(cookie deletion on closing browser).

**Comment by karlitschek** [comment]
Can you please post a full bug report using the issue template?
https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by thinking-aloud** [comment]
I hope this helps:

### Steps to reproduce
1. log in
2. wait

### Expected behaviour
stay logged in

### Actual behaviour
logout after about 2 minutes

### Server configuration
**Operating system**:
Debian 7.8

**Web server:**
2.2.22-13+deb7u4

**Database:**
MySql 5.5.43-0+deb7u1

**PHP version:**
5.4.41-0+deb7u1

**ownCloud version:** (see ownCloud admin page)
8.1

**Updated from an older ownCloud or fresh install:**
updated

**List of activated apps:**
- bookmarks: 0.4
 - calendar: 0.7.0
 - contacts: 0.4.0.0
 - documents: 0.9.0
 - files: 1.1.9
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - gallery: 0.6.1
 - news: 5.3.8
```

**The content of config/config.php:**
<?php 
$CONFIG = array ( 
  'instanceid' => '', 
  'passwordsalt' => '', 
  'secret' => '', 
  'trusted_domains' => 
  array (
    0 => 'url',
    1 => '192.168.0.7',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'https://url/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'pw',
  'installed' => true,
  'overwritewebroot' => '/owncloud',
  'session_lifetime' => 86400,
  'theme' => '',
  'maintenance' => false,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'loglevel' => 3,
);
 /var/www/owncloud/config/config.php   CWD: /var/www/owncloud   Line: 16                                                                               
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Chromium

**Operating system:**
Manjaro (Arch) x64

### Logs
#### Web server error log
```
Insert your webserver log here
Fatal	index	Exception: {"Exception":"OC\\AppFramework\\Middleware\\Security\\SecurityException","Message":"CORS requires basic auth","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/appframework\/middleware\/middlewaredispatcher.php(92): OC\\AppFramework\\Middleware\\Security\\CORSMiddleware->beforeController(Object(OCA\\News\\Controller\\FeedApiController), 'index')\n#1 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(88): OC\\AppFramework\\Middleware\\MiddlewareDispatcher->beforeController(Object(OCA\\News\\Controller\\FeedApiController), 'index')\n#2 \/var\/www\/owncloud\/lib\/private\/appframework\/app.php(108): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\News\\Controller\\FeedApiController), 'index')\n#3 \/var\/www\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('FeedApiControll...', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#4 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#5 \/var\/www\/owncloud\/lib\/private\/route\/router.php(274): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#6 \/var\/www\/owncloud\/lib\/base.php(867): OC\\Route\\Router->match('\/apps\/news\/api\/...')\n#7 \/var\/www\/owncloud\/index.php(40): OC::handleRequest()\n#8 {main}","File":"\/var\/www\/owncloud\/lib\/private\/appframework\/middleware\/security\/corsmiddleware.php","Line":86}
```

#### ownCloud log (data/owncloud.log)
 owncloud.log                                                                                                                                                                                               
```
Insert your ownCloud log here
{"reqId":"f043a26b700c369863f4201ef90260fa","remoteAddr":"","app":"core","message":"unable to rename, file does not exists :              files_versions\/clientsync\/HAW\/MARS\/build.v","level":3,"time":"2015-03-20T16:34:06+00:00"}
{"reqId":"4ca35f2a38d9238d67cf786b1ea18af1","remoteAddr":"","app":"PHP","message":"Undefined index: extension at \/var\/www\/owncloud\/    apps\/files_versions\/lib\/storage.php#320","level":3,"time":"2015-03-24T11:20:16+00:00"}
{"reqId":"4ca35f2a38d9238d67cf786b1ea18af1","remoteAddr":"","app":"core","message":"unable to rename, file does not exists :               files_versions\/clientsync\/HAW\/1_MI.v","level":3,"time":"2015-03-24T11:20:16+00:00"}
{"reqId":"1381f3547eb2c53e13727c4f10d446d8","remoteAddr":"","app":"webdav","message":"Exception: {\"Message\":\"expected filesize 5242880 got 2260992\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php(74): OC_Connector_Sabre_File-   >createFileChunked(Resource id #269)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php(84):                     OC_Connector_Sabre_File->put(Resource id #269)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(1647): OC_Connector_Sabre_Directory->createFile('R2014b_glnxa64....', Resource id #269)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(900): Sabre\\\\DAV\\\\Server->createFile('clientsync\\\/Soft...', Resource id #269, NULL)\\n#4 [internal function]:         Sabre\\\\DAV\\\\Server->httpPut('clientsync\\\/Soft...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server. php(474): call_user_func(Array, 'clientsync\\\/Soft...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server. php(214): Sabre\\\\DAV\\\\Server->invokeMethod('PUT', 'clientsync\\\/Soft...')\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.  php(61): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(54): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",  \"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":288}","level":4,"time":"2015-03-26T14:18:04+00:   00"}
{"reqId":"271b6b311acca3479cfed070c6ae859b","remoteAddr":"192.168.0.5","app":"PHP","message":"require_once():  at \/var\/www\/owncloud\/lib\/          autoloader.php#114","level":3,"time":"2015-03-29T08:02:45+00:00"}
{"reqId":"ea063e66d0bad274b8354ba0ab5797b0","remoteAddr":"192.168.0.5","app":"PHP","message":"require_once():  at \/var\/www\/owncloud\/lib\/          autoloader.php#114","level":3,"time":"2015-03-29T08:02:47+00:00"}
{"reqId":"3f1790fe33645ea2966f3ef2788b1735","remoteAddr":"192.168.0.5","app":"PHP","message":"require_once():  at \/var\/www\/owncloud\/lib\/          autoloader.php#114","level":3,"time":"2015-03-29T08:03:19+00:00"}
 /var/www/owncloud/data/owncloud.log   CWD: /var/www/owncloud/data   Line: 16          
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by thinking-aloud** [comment]
I updated from Debian Wheezy to Jessie and now the logout is not happening as far as I can tell from the last 10 minutes.
Are you interested in my new versions, to reproduce the bug?
It is either something with my old configs or some bugs with one of the involved programs.

**Comment by PVince81** [comment]
@thinking-aloud I assume you see this when staying on the files app page ?

**Comment by thinking-aloud** [comment]
on the file page not directly, but once I click something Files goofs around and reloading the page or clicking something that loads a page brings me to the login.
In News(were I am most the time) I get "Request unauthorized. Are you logged in?"

**Comment by PVince81** [comment]
There should be a heartbeat request to "/heartbeat" that refreshes the session.
Can you check the network console whether you see it shortly before the timeout ? I suspect that it might not be sent in your case.

**Comment by thinking-aloud** [comment]
I can't see it in network console.
I see this was once an error were you were involved https://github.com/owncloud/core/issues/8872

**Comment by thinking-aloud** [comment]
now that this is the case, any ideas on what I can do about it?

**Comment by thinking-aloud** [comment]
I just checked inside a chrome porn tab and it sends the heartbeat message. I guess one of my Chrome plugin is blocking it. I will find out which one it is and report back.
Probably disconnect or uBlock Origin.

**Comment by PVince81** [comment]
Can you type this command in the JS console:
`oc_config.session_lifetime`

That value should be the same as in your config. Maybe it wasn't communicated properly with the JS side.

The code for the heartbeat is here: https://github.com/owncloud/core/blob/v8.1.0/core/js/js.js#L1098

It should send a heartbeat every half session_limetime. If yours is 86400 then it would send a heartbeat call every 43200 seconds.
But you said your session expires earlier ?

**Comment by thinking-aloud** [comment]
it gives me 1440 which are 24 minutes. Mhm weird.

**Comment by PVince81** [comment]
Hmm. 1440 looks like the default value.

I tried setting "session_lifetime" to 86400 in config.php as well on master, and I still see 1440 in the UI.
Looks like a bug.

**Comment by PVince81** [comment]
https://github.com/owncloud/core/blob/v8.1.0/core/js/config.php#L100

Looks like it takes the minimum between that config value and php.ini's "session.gc_maxlifetime".

**Comment by thinking-aloud** [comment]
oh, but sending the heartbeat to often is not the bug I am having, but I have the reason I think.

The ownCloud News Chrome extension seems to kill the session every time it looks for new news. I had it disabled and no logout in the last hour. I activated it and 2 logouts within a minute.
I will deactivate it for now.

Can we somehow move this issue to OC news?

**Comment by PVince81** [comment]
Yes... that's it. If I remove the "session.gc_maxlifetime" part it works.
I tried evaluating that value and it gives 1440.

It was changed in 764e695cb65e4b11edfc1357c2b8adf95dc069c0 last year it seems.
Strangely I did not find any matching PR.

**Comment by PVince81** [comment]
@thinking-aloud issues cannot be moved. Please raise in the https://github.com/owncloud/news repo.

I found the PR here: https://github.com/owncloud/core/pull/9693

**Comment by thinking-aloud** [comment]
Well, thank you for your help. I will report it in the news section then. Guess the Chrome extensions need some work. I will see if I can find either that bug or the one with the OC Chrome Bookmarks once I am done with my exams.
