### ISSUE TITLE
Server 500 internal errors, desktop client not working and log filled with PHP Fatal error messages

### ISSUE THREAD

**Issue by gig13** [owncloud/core#17484]
### Steps to reproduce
Not sure

### Expected behaviour
The server should respond normally and desktop clients should connect to ownCloud.

### Actual behaviour
The server is reporting 500 internal error, the desktop clietns are not responding, and the log is filled with PHP fatal error messages.

### Server configuration
**Operating system**: Ubuntu 12

**Web server:** Apache 2.2

**Database:** PostgreSQL

**PHP version:** 5.4.42

**ownCloud version:** 8.0.3.4

**Updated from an older ownCloud or fresh install:** Updated from older version

**List of activated apps:** In report config
https://s3.owncloud.com/owncloud/index.php/apps/files?dir=%2FShared%2Fowncloud%2Fsupport%2Fgithub-issues%2Fcore%2F17484

**The content of config/config.php:**: To obtain

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** Firefox

**Operating system:** Windows

#### Web server error log
To obtain

#### ownCloud log (data/owncloud.log)
On s3: https://s3.owncloud.com/owncloud/index.php/apps/files?dir=%2FShared%2Fowncloud%2Fsupport%2Fgithub-issues%2Fcore%2F17484

**Comment by gig13** [comment]
@MorrisJobke

**Comment by MorrisJobke** [comment]
;)

**Comment by gig13** [comment]
@MorrisJobke 
The issue was solved with an upgrade to OC8.0.5. Unfortunately I do not have any additional information. Please take a quick look, but I think its ok to close out.
