### ISSUE TITLE
oc8.1 z-index for #app-content on mobile.css is to high

### ISSUE THREAD

**Issue by libasys** [owncloud/core#17485]
please make a lower z-index for div#app-content on mobile.css, i am running with a lot of apps into the issue that some popover division on mobile view doesn't show up!

This line is the problem: https://github.com/owncloud/core/blob/master/core/css/mobile.css#L103
Change it to z-index:140; 
and all works as expected!

Thanks

**Comment by karlitschek** [comment]
@jancborchardt What do you think?

**Comment by jancborchardt** [comment]
@libasys since you already propose a solution, please simply submit a pull request. :) Make sure to really test it well with other apps like Contacts, Calendar, Tasks, Files, Mail etc so we don’t run into the same issues we had before with the z-index change. Thanks! :)

**Comment by jancborchardt** [comment]
Also cc @Raydiation who made the change at https://github.com/owncloud/core/commit/c9012be0b6d737e27fe52b2096e7bece206763f6

> * use z-index for app content on mobile to prevent navigation items from sticking out

**Comment by raghunayyar** [comment]
does this issue still persist? @libasys
