### ISSUE TITLE
Federated cloud sharing not possible with @ in remote username

### ISSUE THREAD

**Issue by Helios07** [owncloud/core#17492]
### Steps to reproduce
1. Create a user abc@def.de in owncloud instance owncloud.server-a.de
2. Share with this user via federated cloud sharing with his username abc@def.de@owncloud.server-a.de from another owncloud instance

### Expected behaviour
The sharing user should be able to click on the username to trigger the sharing mechanism

### Actual behaviour
ownCloud seems to parse the username after the first @, but when entering the second @, the result list disappears. The result is that the share cannot be established

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache 2.4

**Database:** MySQL

**PHP version:** 5.5

**ownCloud version:** (see ownCloud admin page) 8.1

**Updated from an older ownCloud or fresh install:** Updated from 6

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... no

#### Web server error log
 nothing related

#### ownCloud log (data/owncloud.log)
nothing related

**Comment by karlitschek** [comment]
Known limitation
What do you think @schiesbn ?

**Comment by schiesbn** [comment]
The back-end should be able to handle it, this was fixed here https://github.com/owncloud/core/pull/17008

But maybe we need to adjust the share dialog as well

**Comment by felixboehm** [comment]
Sharing Dialog fixed with PR #17565
