### ISSUE TITLE
./occ app:check-code should check signatures of overriding functions

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#17494]
We had some issues lately (and even one in 8.1!  #17455) where a function is overridden but with different/incomplete parameter list. Besides being bad practise this leads to a lot of log messages.

The app checker could come to the rescue once again.

**Comment by DeepDiver1975** [comment]
from my understanding something like this is to be caught by unit testing - the app code checker will not help since there is very little overriding on the apps.
