### ISSUE TITLE
After upgrade to OC 8.1 Android OwnCloud client dont connect

### ISSUE THREAD

**Issue by cleocir** [owncloud/core#17497]
Yesterday i upgraded my oc server from 8.0.4 to 8.1 (stable) and after this my Android mobile client (OwnCloud) stoped connect.

Linux OwnCloud Client continue work perfect! But mobile client don't.

**Comment by cleocir** [comment]
More details:

Ubuntu 14.04 / PHP-FPM / NGINX (with all recommended parameters https://doc.owncloud.org/server/8.1/admin_manual/installation/nginx_configuration.html)

Before upgraded to OC 8.1 my mobile client was perfect working.

My mobile client version is 1.7.2

**Comment by karlitschek** [comment]
something in the ownCloud or webserver logfile? Can you post a full bug report using the issue template please? 
https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by cleocir** [comment]
Hello. 

I found the problem.

This problem was wrong permissions of data/<user>/cache files on OC server.

I owned all data/<user>/cache files to http running user and it back ok!

Thanks.

**Comment by PVince81** [comment]
Thanks, closing.
