### ISSUE TITLE
Update from 7.0.5 to 8.1.0 failed

### ISSUE THREAD

**Issue by Biopticon** [owncloud/core#17493]
Hello,

I attempted to upgrade my OwnCloud to 8.1.0 from v 7.0.5 by using the opensuse repository. My OC data folder is on an external drive. The server is Raspberry Pi using Debian. To update I repeated the following twice. What is the problem? How can I fix it?

--------------
root@Raspberrypi-3:~# echo 'deb http://download.opensuse.org/repositories/isv:/o                           wnCloud:/community:/7.0/Debian_7.0/ /' > /etc/apt/sources.list.d/owncloud.list

root@Raspberrypi-3:~# apt-get update

root@Raspberrypi-3:~# apt-get dist-upgrade

-------------------

The following is the output of the installation process:

![capture](https://cloud.githubusercontent.com/assets/6756426/8572720/004b317a-255c-11e5-9b92-4299a2fc8f67.PNG)

The command window output show the following errors. 

Installing new version of config file /etc/apache2/conf-available/owncloud.conf
 ...                                          
ln: failed to create symbolic link `/etc/apache2/conf.d/owncloud.conf': File exists                                          

dpkg: error processing owncloud-config-apache (--configure): subprocess installed post-installation script returned error exit status 1

Errors were encountered while processing: owncloud-config-apache

E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by karlitschek** [comment]
Do you use and 3rdparty apps? Can you try to remove the from the apps folder and try the upgrade again?

**Comment by Biopticon** [comment]
Hello Frank,

Thank you for your prompt response.I copied the contents to a folder called apps_orig and emptied it. Then when I tried to upgrade, It responded with blank page. It seems that config folder does not have the right privileges. Here is my owncloud directory. Anything wrong?

root@Raspberrypi-3:/var/www/owncloud# ls -la
total 176
drwxr-xr-x 14 www-data www-data  4096 Jul  8 11:10 .
drwxr-xr-x  4 root     root      4096 Jul  4 12:01 ..
drwxr-xr-x 26 www-data www-data  4096 Jul  7 22:58 3rdparty
drwxr-xr-x  2 www-data www-data  4096 Jul  8 11:12 apps
drwxr-xr-x 22 www-data www-data  4096 Jul  8 11:12 apps_orig
drwxrwx---  2 www-data www-data  4096 Jul  7 08:54 assets
-rw-r--r--  1 www-data www-data   477 Jul  2 18:31 AUTHORS
drwxr-xr-x  2 www-data www-data  4096 Jul  7 23:00 config
-rw-r--r--  1 www-data www-data  2492 Jul  2 18:31 console.php
-rw-r--r--  1 www-data www-data 34520 Jul  2 18:31 COPYING-AGPL
drwxr-xr-x 19 www-data www-data  4096 Jul  7 23:00 core
-rw-r--r--  1 www-data www-data  5179 Jul  2 18:31 cron.php
drwxrwx---  2 www-data www-data  4096 Dec 25  2014 data
-rw-r--r--  1 www-data www-data 22276 Jul  2 18:31 db_structure.xml
-rw-r--r--  1 www-data www-data  2029 Jul  2 18:31 .htaccess
-rw-r--r--  1 www-data www-data   179 Jul  2 18:31 index.html
-rw-r--r--  1 www-data www-data  2076 Jul  2 18:31 index.php
-rw-r--r--  1 www-data www-data  2595 Jul  2 18:31 indie.json
drwxr-xr-x  2 www-data www-data  4096 Jul  7 22:59 l10n
drwxr-xr-x  6 www-data www-data  4096 Jul  7 23:00 lib
-rw-r--r--  1 www-data www-data   283 Jul  2 18:31 occ
drwxr-xr-x  2 www-data www-data  4096 Jul  7 23:00 ocs
-rw-r--r--  1 www-data www-data  3058 Jul  2 18:31 public.php
-rw-r--r--  1 www-data www-data  4337 Jul  2 18:31 remote.php
-rw-r--r--  1 www-data www-data    26 Jul  2 18:31 robots.txt
drwxr-xr-x 13 www-data www-data  4096 Jul  7 22:59 settings
-rw-r--r--  1 www-data www-data  1727 Jul  2 18:31 status.php
drwxr-xr-x  3 www-data www-data  4096 Jul  7 23:00 themes
-rw-r--r--  1 www-data www-data   190 Jul  2 18:34 version.php

**Comment by jospoortvliet** [comment]
We do not support skipping a major release when upgrading. You have to upgrade to 8.0.x first before you can move to 8.1.

There also does seem a packaging problem with dpkg but that might also be due to skipping a version. First grab 8.0 from the release channels page and try to upgrade to that first:
https://owncloud.org/release-channels/

I hope that the half-way upgrade didn't break anything.
