### ISSUE TITLE
[8.1.0] Can't sync files. Server returns: "Module with id: OC_DEFAULT_MODULE does not exist."

### ISSUE THREAD

**Issue by Krishath** [owncloud/core#17505]
### Steps to reproduce
1. Put file into directory
2. Try to upload it

### Expected behaviour
File correctly uploaded.

### Actual behaviour
File doesn't get uploaded and returns error.

### Server configuration
**Operating system**: Debian 8.0

**Web server:** 1.9.1-1

**PHP version:** 5.6.9

**ownCloud version:** 8.1.0

**Updated from an older ownCloud or fresh install:** updated from 8.0

**List of activated apps:**

Enabled:
 - files: 1.1.9
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
Disabled:
 - activity
 - calendar
 - contacts
 - encryption
 - external
 - files_external
 - files_locking
 - files_texteditor
 - files_videoviewer
 - firstrunwizard
 - gallery
 - provisioning_api
 - rainloop
 - templateeditor
 - user_external
 - user_ldap
 - user_webdavauth

**The content of config/config.php:**
````
<?php
$CONFIG = array (
  'instanceid' => '*********',
  'passwordsalt' => '******',
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => '***',
  'dbhost' => '****',
  'dbtableprefix' => 'oc_',
  'dbuser' => '****',
  'dbpass' => '****',
  'installed' => true,
  'forcessl' => true,
  'maxZipInputSize' => 8388608000,
  'allowZipDownload' => true,
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' => 
  array (
    0 => '****',
  ),
);
```

**Are you using external storage, if yes which one:** No.

**Are you using encryption:**  No

**Are you using an external user-backend, if yes which one:** No.

### Logs
#### Web server error log
```
**address** - user [08/Jul/2015:19:42:26 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 419 "-" "Mozilla/5.0 (Linux) mirall/1.8.3"
**address** - user [08/Jul/2015:19:42:30 +0200] "PUT /remote.php/webdav/directory/file HTTP/1.1" 500 278 "-" "Mozilla/5.0 (Linux) mirall/1.8.3"
```
(nothing more)

#### ownCloud log (data/owncloud.log)
```
Exception: {"Message":"Module with id: OC_DEFAULT_MODULE does not exist.","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/encryption.php(647): OC\\Encryption\\Manager->getEncryptionModule('OC_DEFAULT_MODU...')\n#1 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/encryption.php(218): OC\\Files\\Storage\\Wrapper\\Encryption->getEncryptionModule('files\/Politecni...')\n#2 [internal function]: OC\\Files\\Storage\\Wrapper\\Encryption->unlink('files\/Politecni...')\n#3 \/var\/www\/owncloud\/apps\/files_trashbin\/lib\/storage.php(116): call_user_func_array(Array, Array)\n#4 \/var\/www\/owncloud\/apps\/files_trashbin\/lib\/storage.php(89): OCA\\Files_Trashbin\\Storage->doDelete('files\/Politecni...', 'unlink')\n#5 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/file.php(149): OCA\\Files_Trashbin\\Storage->unlink('files\/Politecni...')\n#6 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1087): OC\\Connector\\Sabre\\File->put(Resource id #19)\n#7 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(501): Sabre\\DAV\\Server->updateFile('Politecnico\/Ter...', Resource id #19, NULL)\n#8 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#9 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#10 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#11 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#12 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n#13 \/var\/www\/owncloud\/remote.php(132): require_once('\/var\/www\/ownclo...')\n#14 {main}","File":"\/var\/www\/owncloud\/lib\/private\/encryption\/manager.php","Line":159}
```

**Comment by blackcoder** [comment]
same thing happened to me after upgrading to 8.1.0 
My Server-side encryption was enabled, now it's disabled. I am worried that if I re-enable it, it will re-encrypt my files rendering them useless. Help please !

**Comment by blackcoder** [comment]
Ok, so I am following the info on this site: https://doc.owncloud.org/server/8.1/admin_manual/configuration_files/encryption_configuration.html the section related to migrating from 8.0 . I enabled the encryption and the module, and now I get a warning message to migrate using : 
```
You need to migrate your encryption keys from the old encryption (ownCloud <= 8.0) to the new one. Please run 'occ encryption:migrate' or contact your administrator
```
but when I run  : ``` /usr/local/php54/bin/php occ encryption:migrate ``` I get the following : 
``` Reorganize system folder structure ``` and nothing happens after. Any hints ?

**Comment by blackcoder** [comment]
Ok, solved. 
Basically you have to follow the steps here: https://github.com/owncloud/core/issues/16928 
Specifically: 
 - You have to backup the files_encryption folders first before attempting anything:
  - data/files_encryption
  - data/user_name/files_encryption (replace user_name with the name of all your users)
- Replace the two files "migration.php" and "storage.php" with the new files as described in the issue above
- Enable the encryption from your admin page
- Enable the encryption module in the apps page
- Run the encryption migration: ```php occ encryption:migrate```
- Log out and login and try to access your file
- If you can't access your files, try to replace the files_encryption folders with the backup folders and try again

**Comment by orson74** [comment]
Same Problem here. 

Press New Textfile Button -> File was created. Try to edit -> Editor appears, but can't save anything.

**Comment by tuxayo** [comment]
Same problem here.

I'll try @blackcoder instructions in the next days, thanks for finding this.

**Comment by orson74** [comment]
What's the solution ???

**Comment by DeepDiver1975** [comment]
@orson74 your error message looks like to be a totally different issue - please open a new issue - THX

**Comment by tuxayo** [comment]
@blackcoder it worked, thanks! :-)

**Comment by AykutCevik** [comment]
Can't fix that issue.
I updated owncloud from 8.0.5 to 8.1.0 and could not access any file after that. I tried to migrate keys, changed the files storage.php and migration.php and did all the ways which were mentioned here. Any ideas? It still can't access any file with the following error: ```Call to a member function isReadable() on null at encryption.php#288","level":3``` and also ``` {"reqId":"f0rCd2ea21bg91lQU0XS","remoteAddr":"80.153.140.164","app":"no app in context","message":"Encryption module \"\" not found, file will be stored unencrypted (Module with id: OC_DEFAULT_MODULE does not exist.)","level":2,"time":"2015-07-13T14:14:41+02:00"}
 ```

I reverted everything to 8.0.5, which works fine.

**Comment by Thomanji** [comment]
@blackcoder It seems the links for "migration.php" and "storage.php" are now giving 404 not found. I have the same issue and wanted to follow the steps. Any way o get these 2 files again?

**Comment by Foggalong** [comment]
I don't have encryption enabled but I'm still experiencing this error :/

**Comment by lightweight** [comment]
I've got the same problem - upgraded from 8.0.4, and don't have encryption turned on, but got same OC_DEFAULT_MODULE error...

**Comment by XMSSystems** [comment]
Got the same error after upgrading to 8.1.2 using Softaculous. Not 100% sure of my last version but definitely in the 8.1 series.

**Comment by augustseptember** [comment]
Same error here. Was upgrading from 7.0.4. Encryption was not enabled during update process. But some months before I enabled encryption for testing but disabled it again after a while.

**Comment by FidoroChun** [comment]
I got this message, when the client tried to upload a broken image file... i deleted it and the rest uploadet just fine :)

**Comment by leizh** [comment]
I support it but at a slow pace. `files_clipboard` is a few hours work, with some contestable design choices (use of `sessionStorage` to store the clipboard). I use it only in a private context and I do not have the time to maintain a enterprise-grade feature. Nonetheless, I think the ability to move files is an essential feature which should be in core.
On the question of interaction, my feeling is that copy/paste is the most appropriate to a page-based file manager like ownCloud.
