### ISSUE TITLE
update 8.04 to 8.1.0 (nginx) => ".htaccess file has the wrong version....

### ISSUE THREAD

**Issue by kas70** [owncloud/core#17502]
...Please upload the correct version. Maybe you forgot to replace it after updating?"

no update possible. does nginx use .htaccess?

**Comment by RealRancor** [comment]
Nope, NginX doesn't use .htaccess but you need to overwrite the old .htaccess with the never one anyway.

**Comment by kas70** [comment]
can you tell me how to do this?

**Comment by kas70** [comment]
somehow the .htaccess file was not extracted correctly from the tarball. everything is working now.
