### ISSUE TITLE
Error occured while checking server setup / Admin Panel / 8.1

### ISSUE THREAD

**Issue by tuxbox** [owncloud/core#17508]
### Steps to reproduce
1. Login to admin panel

### Expected behaviour
checksetup is successful

### Actual behaviour
The following error message is shown:

Error occurred while checking server setup
Please double check the installation guides ↗, and check for any errors or warnings in the log.

which occurs when requesting https://my.domain/index.php/settings/ajax/checksetup

### Server configuration
**Operating system**: FreeBSD 10.1

**Web server:** nginx

**Database:** mysql

**PHP version:** 5.6

**ownCloud version:** 8.1

**Updated from an older ownCloud or fresh install:**

**List of activated apps:** default apps

I would expect to have a checksetup.php in the $OWNCLOUD_HOME/settings/ajax directory. This is missing in the git repo as well as in both downloadable files (tar.bz2 & zip)

**Comment by RealRancor** [comment]
> I would expect to have a checksetup.php in the $OWNCLOUD_HOME/settings/ajax directory. This is missing in the git repo as well as in both downloadable files (tar.bz2 & zip)

This path is just a route / virtual file
