### ISSUE TITLE
After update to 8.1 "Last cron job execution: 23 hours ago. Something seems wrong"

### ISSUE THREAD

**Issue by jsalatiel** [owncloud/core#17511]
After upgrade from 8.0.4 to 8.1 the cron job appears not be running, at least for the admin ui.
Even if i run manually and it exits with '0' , i still get the "Last cron job execution: 23 hours ago. Something seems wrong" message in the ui.

**Comment by RealRancor** [comment]
Please use the issue template as asked here:

https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version

Especially the part of the logfiles is important.

**Comment by smfzutzg** [comment]
Same problem here!
When running php -f cron.php from the command line I get "The posix extensions are required - see http://php.net/manual/en/book.posix.php"
New dependency that nobody told us about?

**Comment by RealRancor** [comment]
@smfzutzg A not running cron could have various sources. The dependency / requirement of posix is a little bit hidden here: https://doc.owncloud.org/server/8.1/admin_manual/installation/source_installation.html#prerequisites

**Comment by smfzutzg** [comment]
I see. Nevertheless it used to work without posix before 8.1 that is why I did not install it.

**Comment by RealRancor** [comment]
Hi,

it should be obvious that major versions like 8.1 are changing / improving stuff. The main reason here is because users sometimes did not run the cron.php or console.php with the correct users and so broke some permissions / stuff.

**Comment by blue-bean** [comment]
And another note for this:
you have to add apc.enable_cli=1 in the php.ini of the server.
