### ISSUE TITLE
Encryption keys from 3rd party user providers are not migrated

### ISSUE THREAD

**Issue by BattleMage** [owncloud/core#17514]
After fixing issue #16928 with #17473, users present in the owncloud database are now migrated properly. But the migration command won't migrate users provided by 3rd party apps. Most of my users are provided by the user_sql app. Trying to migrate the keys using `occ encryption:migrate <username>` results in an error "Unknown user <username>".
#### Steps to reproduce:
1. Have your users in another table and provide them by the user_sql app.
2. Try to migrate all users by executing `occ encryption:migrate`
3. Only local users are migrated
4. Try to migrate the keys executing `occ encryption:migrate <username>` as the webserver user where <username> is a valid username provided by user_sql app.
5. Error is thrown
#### Expected result

User keys are migrated
#### Further comments

Perhaps it would be saver to check the data folder for old encryption keys instead of getting them from the database.

**Comment by DeepDiver1975** [comment]
Looks like the app user_sql is not loaded. Please post the app's info.xml

**Comment by BattleMage** [comment]
Here's the info.xml:
```xml
<?xml version="1.0"?>
<info>
       <id>user_sql</id>
       <name>SQL user backend</name>
       <description>Authenticate Users by SQL</description>
       <licence>AGPL</licence>
       <author>Andreas Boehler &lt;andreas (at) aboehler
(dot) at &gt;</author>
       <require>5.0</require>
       <shipped>false</shipped>
       <types>
            <authentication/>
       </types>
</info>
```

According to the occ output, the app is loaded: ``sudo -u www-data php occ app:enable user_sql``: user_sql is already enabled.

If I disable maintenance mode, I'm able to login with SQL users. The app seems to be working properly.

**Comment by DeepDiver1975** [comment]
hmmm ... can you please get in touch with the app developer? from what I can tell there might be something strange going on within the app.

E.g. the user_ldap backend properly is loaded - my suspect was that the authentication type entry was missing in the info.xml

**Comment by BattleMage** [comment]
As I'm sending him the 8.1 patch for the now deprecated use of \OC\Cache right now, I'll ask for support.

**Comment by schiesbn** [comment]
@BattleMage anything new here? Could the issue be solved on the app level?

**Comment by andyboeh** [comment]
I am the developer of user_sql. In the meantime, a lot has changed within user_sql and I do not know if the problem still persists. 
Personally, I do not use encryption and thus I cannot test with encryption enabled.

**Comment by karlitschek** [comment]
@andyboeh great app by the way :-)

**Comment by andyboeh** [comment]
@karlitschek Thank you very much, I really appreciate your positive feedback!

**Comment by PVince81** [comment]
@BattleMage is this still an issue ? From what I remember there might have been fixes before to make sure the user management apps are loaded before the migration starts because there were similar issues with the LDAP user manager.

**Comment by PVince81** [comment]
Closing due to lack of feedback. If this is still happening in recent versions, please reopen.
