### ISSUE TITLE
After update to 8.1 contact birthdays are not shown in calendar anymore

### ISSUE THREAD

**Issue by smfzutzg** [owncloud/core#17515]
After update to 8.1 contact birthdays are not shown in calendar anymore

**Comment by DeepDiver1975** [comment]
please reopen this issue in https://github.com/owncloud/contacts THX

**Comment by RealRancor** [comment]
Dup of: https://github.com/owncloud/calendar/issues/824, got fixed with calendar 0.7.1 and the next release of the contacts app with https://github.com/owncloud/contacts/pull/970
