### ISSUE TITLE
unable to access dav shares in ownCloud 8.0.5

### ISSUE THREAD

**Issue by j-ed** [owncloud/core#17510]
## Expected behavior
It should be possible to access WebDAV shares in ownCloud 8.0.5 as it was possible in ownCloud 8.0.4.

## Current behavoir
It is not possible to access WebDAV shares in ownCloud 8.0.5 anymore and the following messages is written to the log file:
```
...,"app":"PHP","message":"Call to undefined method OC\\Files\\Storage\\DAV::propfind() at \/var\/www\/htdocs\/owncloud\/lib\/private\/files\/storage\/dav.php#487","level":3,"time":"2015-07-08 23:26:31+02:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/scan.php?force=false&dir=&requesttoken=VOkEK...
```

## Steps to reproduce
1. Upgrade ownCloud 8.0.4 to 8.0.5
2. try to access a WebDAV share
3. check the log file

#### Server Configuration
OS: Linux 3.2.67
Web server: Apache2 2.4.12
Database: MySQL 5.1.73
PHP version: 5.4.42
ownCloud version: 8.0.5

#### Client Configuration
Browser: Firefox 39.0
Operating system: Windows 7

**Comment by j-ed** [comment]
If checked line 487 in `lib/private/files/storage/dav.php`and found out that the `propfind` command is used as follows in function `getETag($path)` and `getPermissions($path)`:
```
$response = $this->propfind(...
```
All other function are using  the `propfind` command as follows:
```
$response = $this->client->propfind(...
```
Could this be the root cause of the problem? I've changed the two appearances as described and now I'm able to access my WebDAV shares again.

**Comment by PVince81** [comment]
Is the "WebDAV share" a remote server, and that server is not ownCloud ?
What WebDAV server are you using ?

`$this->propfind()` is used to do some caching, maybe something is wrong there.

**Comment by j-ed** [comment]
The WebDAV share is on a Synology NAS. As described in my previous comment, I was able to fix the missing `$this->propfind()` call on my ownCloud server by renaming the two appearances in `dav.php` to `$this->client->propfind()`. The WebDAV shares are now accessible again and no error messages are logged anymore. I assume that this might be a typo in `dav.php`, that's the reason why I've not close this issue and to give you the chance to fix it, if necessary.

**Comment by PVince81** [comment]
Is the WebDAV server running on lighttpd on the NAS ? Or is it specific to Synology ?

Can you do this:
`curl -X PROPFIND http://synologyhost/...` and replace the URL to the WebDAV endpoint containing folders ? I want to check if the order of the results is correct.

**Comment by j-ed** [comment]
The WebDAV server is running on Apache on the NAS:
```
./httpd -V
Server version: Apache/2.2.29 (Unix)
Server built:   Jun 15 2015 21:18:07
Server's Module Magic Number: 20051115:36
Server loaded:  APR 1.5.1, APR-Util 1.5.3
Compiled using: APR 1.5.1, APR-Util 1.5.3
Architecture:   32-bit
Server MPM:     Worker
  threaded:     yes (fixed thread count)
    forked:     yes (variable process count)
```
The curl command returns the following output:
```
# curl -X PROPFIND -u <user>:<pass> https://<synologyhost>:5006/...
<?xml version="1.0" encoding="utf-8"?>
<D:multistatus xmlns:D="DAV:">
<D:response xmlns:lp1="DAV:" xmlns:lp2="http://apache.org/dav/props/">
<D:href>/homes/juergen/Eigene</D:href>
<D:propstat>
<D:prop>
<lp1:resourcetype/>
<lp1:creationdate>2015-07-06T20:01:16Z</lp1:creationdate>
<lp1:getcontentlength>873687</lp1:getcontentlength>
<lp1:getlastmodified>Mon, 06 Jul 2015 20:02:41 GMT</lp1:getlastmodified>
<lp1:getetag>"4c018b-d54d7-51a3a636288bb"</lp1:getetag>
<lp2:executable>F</lp2:executable>
<D:supportedlock>
<D:lockentry>
<D:lockscope><D:exclusive/></D:lockscope>
<D:locktype><D:write/></D:locktype>
</D:lockentry>
<D:lockentry>
<D:lockscope><D:shared/></D:lockscope>
<D:locktype><D:write/></D:locktype>
</D:lockentry>
</D:supportedlock>
<D:lockdiscovery/>
</D:prop>
<D:status>HTTP/1.1 200 OK</D:status>
</D:propstat>
</D:response>
</D:multistatus>
```

**Comment by j-ed** [comment]
I  must correct my previous statement that no errors are logged anymore. I've just seen that renaming the function doesn't solved the whole problem. It seems that the call need to be modified too. This is what is being logged when after renaming the function call:
```
...,"app":"PHP","message":"Argument 2 passed to Sabre\\DAV\\Client::propFind() must be of the type array, none given, called in \/var\/www\/htdocs\/owncloud\/lib\/private\/files\/storage\/dav.php on line 487 and defined at \/var\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Client.php#152","level":0,"time":"2015-07-09 15:49:18+02:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
...,"app":"PHP","message":"Undefined variable: properties at \/var\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Client.php#158","level":0,"time":"2015-07-09 15:49:18+02:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
...,"app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Client.php#158","level":0,"time":"2015-07-09 15:49:18+02:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
```

**Comment by PVince81** [comment]
If it worked in 8.0.4 then best is to bisect this to find the commit that broke it.

**Comment by j-ed** [comment]
I've copied over the `dav.php` file from 8.0.4 and the problem seems to be solved. A file compare is showing the following differences:
```
<               $response = $this->propfind($path);
---
>               $response = $this->client->propfind($this->encodePath($path), array('{http://owncloud.org/ns}permissions'));
483,493d482
<       /** {@inheritdoc} */
<       public function getETag($path) {
<               $this->init();
<               $path = $this->cleanPath($path);
<               $response = $this->propfind($path);
<               if (isset($response['{DAV:}getetag'])) {
<                       return trim($response['{DAV:}getetag'], '"');
<               }
<               return parent::getEtag($path);
<       }
<
535,539c524,525
<                               $etag = null;
<                               if (isset($response['{DAV:}getetag'])) {
<                                       $etag = trim($response['{DAV:}getetag'], '"');
<                               }
<                               if (!empty($etag) && $cachedData['etag'] !== $etag) {
---
>                               $etag = trim($response['{DAV:}getetag'], '"');
>                               if ($cachedData['etag'] !== $etag) {
```

**Comment by PVince81** [comment]
Argh, I think I know what happened. Possibly a failed backport from 8.1, this one: https://github.com/owncloud/core/pull/16734

8.1 has the method `$this->propfind()` due to caching. But 8.0 did not have the cache code, so needs to use `$this->client->propfind()`.

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/17566

**Comment by j-ed** [comment]
@PVince81 Please have a look on one of my previous comments. I had already tested that but it doesn't solve the whole problem. I think the list of parsed parameters need to be modified too, because the following messages are logged after renaming the function call:
```
...,"app":"PHP","message":"Argument 2 passed to Sabre\\DAV\\Client::propFind() must be of the type array, none given, called in \/var\/www\/htdocs\/owncloud\/lib\/private\/files\/storage\/dav.php on line 487 and defined at \/var\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Client.php#152","level":0,"time":"2015-07-09 15:49:18+02:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
...,"app":"PHP","message":"Undefined variable: properties at \/var\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Client.php#158","level":0,"time":"2015-07-09 15:49:18+02:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
...,"app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Client.php#158","level":0,"time":"2015-07-09 15:49:18+02:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
```
It seems that the new function call requires three parameter, the old function call required only one, e.g.:
old: ```$this->propfind($path);```
new: ```$this->client->propfind($this->encodePath($path), array(), 1);```

**Comment by PVince81** [comment]
Ah yes, perhaps the method signature is not the same.

**Comment by PVince81** [comment]
Fix will be in 8.0.6.

**Comment by PVince81** [comment]
@rperezb FYI

**Comment by rperezb** [comment]
thx @PVince81 on the list to be qa
@owncloud/qa

**Comment by SergioBertolinSG** [comment]
Tested using stable8, both with http and https, working fine.
