### ISSUE TITLE
cant't edit and download textfile, upload doesn't work

### ISSUE THREAD

**Issue by orson74** [owncloud/core#17522]
### Steps to reproduce
1.
create a textfile in browser
2.
try to edit and save
3.
download file

### Expected behaviour
create a file with content and download to local folder

### Actual behaviour
file was created, changes didn't save
try to download show 'an error occurs'
 
### Server configuration
**Operating system**:
Debian
**Web server:**
Apache
**Database:**
mySQL
**PHP version:**
PHP 5.4.41-0+deb7u1 (cli) (built: May 22 2015 12:49:18) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
**ownCloud version:** (see ownCloud admin page)
8.1
**Updated from an older ownCloud or fresh install:**
8.0.4
**List of activated apps:**
Enabled:
 - activity: 2.0.1
 - encryption: 1.0.0
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - user_ldap: 0.6.1
Disabled:
 - external
 - files_external
 - user_external
 - user_webdavauth
**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system --public
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
<?php
$CONFIG = array (
  'instanceid' => 'XXX',
  'passwordsalt' => 'XXX',
  'secret' => 'XXX',
  'trusted_domains' => 
  array (
    0 => '192.168.3.235',
    1 => 'XXX',
    2 => 'XXX',
    3 => 'XXX',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => '',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'ldapUserCleanupEnabled' => true,
  'ldapUserCleanupInterval' => 10,
  'logtimezone' => 'Europe/Berlin',
  'loglevel' => 0,
  'maintenance' => false,
  'dbname' => 'oc_database',
  'dbhost' => '127.0.0.1',
  'dbuser' => 'oc_mysql_user',
  'dbpassword' => 'oc',
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'undeliverable',
  'mail_domain' => 'XXX',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'XXX',
  'mail_smtpname' => 'XXXX',
  'mail_smtppassword' => 'XXX',
  'mail_smtpport' => '25',
  'mail_smtpsecure' => 'tls',
  'theme' => '',
);
**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP
#### LDAP configuration (delete this part if not used)

```
On ownCloud 7+ with access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

On ownCloud 6 with access to your command line run e.g.:
sqlite3 data/owncloud.db or mysql -u root -p owncloud
then execute:  select * from oc_appconfig where appid='user_ldap';

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query above.

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
Chrome, Safari
**Operating system:**
Windows, MacOs
#### Web server error log
[Wed Jul 08 21:55:50 2015] [error] [client XXX.XXX.XXX.XXX] File does not exist: /var/www/owncloud/HTTP
[Wed Jul 08 21:55:51 2015] [error] [client XXX.XXX.XXX.XXX] File does not exist: /var/www/owncloud/recordings
[Wed Jul 08 21:55:53 2015] [error] [client XXX.XXX.XXX.XXX] File does not exist: /var/www/owncloud/admin
[Wed Jul 08 22:48:28 2015] [error] [client XXX.XXX.XXX.XXX] PHP Fatal error:  Class 'OCA\\Encryption\\KeyManager' not found in /var/www/owncloud/apps/encryption/appinfo/application.php on line 143
[Wed Jul 08 22:48:34 2015] [error] [client XXX.XXX.XXX.XXX] PHP Fatal error:  Class 'OCA\\Encryption\\KeyManager' not found in /var/www/owncloud/apps/encryption/appinfo/application.php on line 143
[Wed Jul 08 22:48:35 2015] [error] [client XXX.XXX.XXX.XXX] PHP Fatal error:  Class 'OCA\\Encryption\\KeyManager' not found in /var/www/owncloud/apps/encryption/appinfo/application.php on line 143
[Wed Jul 08 22:48:35 2015] [error] [client 192.XXX.XXX.34] PHP Fatal error:  Class 'OCA\\Encryption\\KeyManager' not found in /var/www/owncloud/apps/encryption/appinfo/application.php on line 143
[Wed Jul 08 22:48:38 2015] [error] [client 192.XXX.XXX.35] PHP Fatal error:  Class 'OCA\\Encryption\\KeyManager' not found in /var/www/owncloud/apps/encryption/appinfo/application.php on line 143
[Wed Jul 08 22:48:39 2015] [error] [client 192.XXX.XXX.39] PHP Fatal error:  Class 'OCA\\Encryption\\KeyManager' not found in /var/www/owncloud/apps/encryption/appinfo/application.php on line 143
[Wed Jul 08 23:24:28 2015] [error] [client 10.XXX.XXX.6] PHP Fatal error:  Call to a member function isReadable() on a non-object in /var/www/owncloud/lib/private/files/storage/wrapper/encryption.php on line 288, referer: https://XXX.XXX.XXX.XXX/index.php/apps/files/?dir=%2FDokumente%2FTest
[Wed Jul 08 23:24:28 2015] [error] [client 10.XXX.XXX.6] File does not exist: /var/www/owncloud/favicon.ico, referer: https://XXX.XXX.XXX.XXX/index.php/apps/files/ajax/download.php?dir=%2FDokumente%2FTest&files=Neue%20Textdatei.txt
[Wed Jul 08 23:30:47 2015] [error] [client XXX.XXX.XXX.XXX] Negotiation: discovered file(s) matching request: /var/www/owncloud/settings/admin (None could be negotiated).
[Wed Jul 08 23:30:52 2015] [error] [client 192.XXX.XXX.235] client denied by server configuration: /var/www/owncloud/data/htaccesstest.txt
[Wed Jul 08 23:30:54 2015] [error] [client XXX.XXX.XXX.XXX] Negotiation: discovered file(s) matching request: /var/www/owncloud/settings/admin (None could be negotiated)., referer: https://XXX.XXX.XXX.XXX/index.php/settings/admin
[Wed Jul 08 23:30:56 2015] [error] [client XXX.XXX.XXX.XXX] Negotiation: discovered file(s) matching request: /var/www/owncloud/settings/admin (None could be negotiated)., referer: https://XXX.XXX.XXX.XXX/index.php/settings/admin
[Wed Jul 08 23:30:57 2015] [error] [client XXX.XXX.XXX.XXX] Negotiation: discovered file(s) matching request: /var/www/owncloud/settings/admin (None could be negotiated)., referer: https://XXX.XXX.XXX.XXX/index.php/settings/admin
[Wed Jul 08 23:30:59 2015] [error] [client XXX.XXX.XXX.XXX] Negotiation: discovered file(s) matching request: /var/www/owncloud/settings/admin (None could be negotiated)., referer: https://XXX.XXX.XXX.XXX/index.php/settings/admin
[Wed Jul 08 23:31:01 2015] [error] [client XXX.XXX.XXX.XXX] Negotiation: discovered file(s) matching request: /var/www/owncloud/settings/admin (None could be negotiated)., referer: https://XXX.XXX.XXX.XXX/index.php/settings/admin
[Thu Jul 09 06:25:03 2015] [notice] Graceful restart requested, doing restart
[Thu Jul 09 06:25:03 2015] [warn] Init: (XXX.XXX.XXX.XXX:443) You configured HTTP(80) on the standard HTTPS(443) port!
[Thu Jul 09 06:25:03 2015] [notice] Apache/2.2.22 (Debian) PHP/5.4.41-0+deb7u1 mod_ssl/2.2.22 OpenSSL/1.0.1e configured -- resuming normal operations

#### ownCloud log (data/owncloud.log)
{"reqId":"jtypCMxOhnAhBERtQRoF","remoteAddr":"XXX.XXX.XXX.XXX","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Encryption not ready: multikeydecrypt with share key failed:error:0407106B:rsa routines:RSA_padding_check_PKCS1_type_2:block type is not 02\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(82): OC\\\\Connector\\\\Sabre\\\\File->get()\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":256}","level":4,"time":"2015-07-09T07:53:50+02:00","method":"GET","url":"\/remote.php\/webdav\/Dokumente\/Test\/Neue%20Textdatei.txt"}
{"reqId":"a3myvkAgGLVbt6PPG1Ym","remoteAddr":"XXX.XXX.XXX.XXX","app":"webdav","message":"Exception: {\"Message\":\"Encryption library: Decryption (symmetric) of content failed: error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(296): OCA\\\\Encryption\\\\Crypto\\\\Crypt->decrypt(false, false, '6kXZ5ITc5kSeVe7...', 'AES-256-CFB')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/encryption.php(294): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('---------------...', '6kXZ5ITc5kSeVe7...', 'AES-256-CFB')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(443): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt('---------------...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(282): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#4 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/http\\\/lib\\\/Sapi.php(70): file_put_contents('php:\\\/\\\/output', Resource id #392)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\HTTP\\\\Sapi::sendResponse(Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php\",\"Line\":353}","level":4,"time":"2015-07-09T07:53:50+02:00","method":"GET","url":"\/remote.php\/webdav\/ownCloudUserManual.pdf"}
{"reqId":"TLGzWnDCzHQ2uZMIInBd","remoteAddr":"XXX.XXX.XXX.XXX","app":"webdav","message":"Exception: {\"Message\":\"Could not obtain lock type 1 on \\\"\\\/var\\\/www\\\/owncloud\\\/data\\\/denis\\\/files\\\/Dokumente\\\/Neues Textdokument.txt.ocTransferId1740557420.part\\\".\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_locking\\\/lib\\\/lockingwrapper.php(45): OCA\\\\Files_Locking\\\\Lock->addLock(1, Resource id #395)\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_locking\\\/lib\\\/lockingwrapper.php(172): OCA\\\\Files_Locking\\\\LockingWrapper->getLock('files\\\/Dokumente...', 1, Resource id #395)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/encryption.php(622): OCA\\\\Files_Locking\\\\LockingWrapper->fopen('files\\\/Dokumente...', 'r')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/encryption.php(642): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->getHeader('files\\\/Dokumente...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/encryption.php(218): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->getEncryptionModule('files\\\/Dokumente...')\\n#5 [internal function]: OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->unlink('files\\\/Dokumente...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/storage.php(116): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/storage.php(89): OCA\\\\Files_Trashbin\\\\Storage->doDelete('files\\\/Dokumente...', 'unlink')\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php(149): OCA\\\\Files_Trashbin\\\\Storage->unlink('files\\\/Dokumente...')\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php(113): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #230)\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('Neues Textdokum...', Resource id #230)\\n#11 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('Dokumente\\\/Neues...', Resource id #230, NULL)\\n#12 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#13 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#14 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#15 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#16 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#17 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/files_locking\\\/lib\\\/lock.php\",\"Line\":257}","level":4,"time":"2015-07-09T07:53:52+02:00","method":"PUT","url":"\/remote.php\/webdav\/Dokumente\/Neues%20Textdokument.txt"}
{"reqId":"Z9b2VHfk7xx8TqcfMRoI","remoteAddr":"XXX.XXX.XXX.XXX","app":"webdav","message":"Exception: {\"Message\":\"Encryption library: Decryption (symmetric) of content failed: error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(296): OCA\\\\Encryption\\\\Crypto\\\\Crypt->decrypt(false, false, '6kXZ5ITc5kSeVe7...', 'AES-256-CFB')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/encryption.php(294): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('---------------...', '6kXZ5ITc5kSeVe7...', 'AES-256-CFB')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(443): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt('---------------...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(282): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#4 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/http\\\/lib\\\/Sapi.php(70): file_put_contents('php:\\\/\\\/output', Resource id #392)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\HTTP\\\\Sapi::sendResponse(Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php\",\"Line\":353}","level":4,"time":"2015-07-09T08:25:10+02:00","method":"GET","url":"\/remote.php\/webdav\/ownCloudUserManual.pdf"}

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by DeepDiver1975** [comment]
@orson74 did you successfully run the encryption key migration?

**Comment by orson74** [comment]
@DeepDiver1975 what does successful mean. formerly encrypted files can be downloaded after copying the privatekey from "backup" into "files_encryption/OC_DEFAULT_MODULE". i think the public could be the wrong.

**Comment by orson74** [comment]
are there any news

**Comment by PVince81** [comment]
@schiesbn

**Comment by schiesbn** [comment]
There seems to be something broken with your installation. Can you check if the file apps/encryption/lib/keymanager.php exists and that the content looks like this: https://raw.githubusercontent.com/owncloud/core/backport-17464-stable8.1/apps/encryption/lib/keymanager.php

**Comment by schiesbn** [comment]
> what does successful mean. formerly encrypted files can be downloaded after copying the privatekey from "backup" into "files_encryption/OC_DEFAULT_MODULE". i think the publickey could be the wrong.

You could try to copy the public key from the backup in your data folder to the ````data/<user>/files_encryption/OC_DEFAULT_MODULE/<user>.publicKey```` next to the users private key.

But what really worries me is the error message above, so please first check the keymanager.php as described above.

Generally, the migration in 8.1 was broken. In order to successfully migrate you need to perform this steps: https://github.com/owncloud/core/issues/17574

**Comment by PVince81** [comment]
@orson74 did you try it ?

**Comment by orson74** [comment]
With the current version and manually copying the correct private/public keys related directories. It works.
