### ISSUE TITLE
Font change after clicking/downloading a file

### ISSUE THREAD

**Issue by eraaijmakers** [owncloud/core#17520]
@jancborchardt

### Steps to reproduce
1. Go to any folder with files listed
![before click](https://cloud.githubusercontent.com/assets/1861365/8590948/2f3505fa-2625-11e5-8ab7-0d776c3471bb.png)
2. Click a file to download, font changes, when navigating away or reload the page the font changes back to normal
![after click](https://cloud.githubusercontent.com/assets/1861365/8590947/2f319a64-2625-11e5-99de-637de2183c55.png)

### Expected behaviour
Font should stay the same

### Actual behaviour
Font changes

### Server configuration
**Operating system:**
Debian Jessie

**Web server:**
Apache/2.4.10

**Database:**
MySQL 5.5.43-0+deb8u1

**PHP version:**
5.6.9-0+deb8u1

**ownCloud version:**
8.1.0 (stable8.1 branch)

**Updated from an older ownCloud or fresh install:**
Updated since at least 7

**List of activated apps:**
 - activity: 2.0.1
 - documents: 0.10.0
 - files: 1.1.9
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - gallery: 0.6.0

**The content of config/config.php:**
```
<?php
$CONFIG = array (
  'installed' => true,
  'dbtype' => 'mysql',
  'dbname' => '***',
  'dbuser' => '***',
  'dbpassword' => '***',
  'dbhost' => '***',
  'dbtableprefix' => '***',
  'passwordsalt' => '***',
  'forcessl' => true,
  'blacklisted_files' =>
  array (
    0 => '.htaccess',
  ),
  'overwritehost' => '',
  'overwriteprotocol' => '',
  'overwritewebroot' => '',
  'overwritecondaddr' => '',
  'proxy' => '',
  'proxyuserpwd' => '',
  'theme' => '',
  'default_language' => 'en',
  '3rdpartyroot' => '',
  '3rdpartyurl' => '',
  'defaultapp' => 'files',
  'knowledgebaseenabled' => true,
  'appstoreenabled' => false,
  'appstoreurl' => 'http://api.apps.owncloud.com/v1',
  'mail_domain' => '***',
  'mail_smtpdebug' => false,
  'mail_smtpmode' => 'php',
  'mail_smtphost' => '127.0.0.1',
  'mail_smtpport' => '25',
  'mail_smtptimeout' => 10,
  'mail_smtpauthtype' => 'LOGIN',
  'memcached_server' =>
  array (
    0 => 'localhost',
    1 => 11211,
  ),
  'trashbin_retention_obligation' => 30,
  'trashbin_auto_expire' => true,
  'allow_user_to_change_display_name' => true,
  'appcodechecker' => '',
  'updatechecker' => true,
  'has_internet_connection' => true,
  'check_for_working_webdav' => true,
  'check_for_working_htaccess' => true,
  'log_type' => 'owncloud',
  'logfile' => '',
  'loglevel' => 2,
  'logdateformat' => 'F d, Y H:i:s',
  'logtimezone' => 'Europe/Amsterdam',
  'log_query' => false,
  'log_authfailip' => false,
  'log_rotate_size' => 52428800,
  'remember_login_cookie_lifetime' => 1296000,
  'session_lifetime' => 86400,
  'custom_csp_policy' => 'default-src \'self\'; script-src \'self\' \'unsafe-eval\'; style-src \'self\' \'unsafe-inline\'; frame-src *; img-src *; font-src \'self\' data:; media-src *',
  'xframe_restriction' => true,
  'datadirectory' => '/storage',
  'maintenance' => false,
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/var/www/***/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/var/www/***/owncloud/apps2',
      'url' => '/apps2',
      'writable' => false,
    ),
  ),
  'customclient_desktop' => '',
  'customclient_android' => '',
  'customclient_ios' => '',
  'enable_previews' => true,
  'preview_max_x' => NULL,
  'preview_max_y' => NULL,
  'preview_max_scale_factor' => 10,
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'preview_office_cl_parameters' => '',
  'enable_avatars' => true,
  'openssl' =>
  array (
  ),
  'singleuser' => false,
  'instanceid' => 'oc28e77e20c5',
  'version' => '8.1.0.8',
  'trusted_domains' =>
  array (
    0 => '***',
  ),
  'secret' => '***',
);
```

**Are you using external storage, if yes which one:**
No

**Are you using encryption:**
No

**Are you using an external user-backend, if yes which one:**
No

### Client configuration
**Browser:**
Version 43.0.2357.130 (64-bit)

**Operating system:**
Ubuntu 14.04

#### Web server error log
```
No related log entries found
```

#### ownCloud log (data/owncloud.log)
```
No related log entries found
```

#### Browser log
```
Resource interpreted as Document but transferred with MIME type application/vnd.openxmlformats-officedocument.spreadsheetml.sheet: "https://***/index.php/apps/files/ajax/download.php?dir=%2FS…g%2FSeizoen%202014-2015%2FBevers%2FZomerkamp&files=Bevers%20Checklist.xlsx".
Uncaught TypeError: Cannot read property 'classList' of null
```

**Comment by jancborchardt** [comment]
Wow, never seen that. :D

@eraaijmakers can you right-click and inspect any of the text and see which CSS line causes this change?

cc @owncloud/designers

**Comment by eraaijmakers** [comment]
Will this do?

![inspect element](https://cloud.githubusercontent.com/assets/1861365/8592926/8410f3e6-2633-11e5-95d6-366f974359bd.png)

**Comment by PVince81** [comment]
@eraaijmakers please search the styles list and see which one is defining the font.
Do this before and after the problem appears.

**Comment by eraaijmakers** [comment]
Just found out that the Chrome extension "Sight" is causing this. After disabling the extension everything works as expected.
