### ISSUE TITLE
Shares for contacts and calendars not visible in IOS 8.3

### ISSUE THREAD

**Issue by Allibabba** [owncloud/core#17529]
Dear developers,

I just upgraded from OC 7.0.4 to OC 8.1. I shared calendars and contacts between two accounts which works pretty good within OC.
Unfortunately these shares are not visible in my IOS 8.3 devices as they only show the data of the linked sync-account. 
The IOS sync-URLs and -parameters are the same as for OC 7.0.4 where they worked without any problem.
All related "Share" parameters on the admin page are checked.

Any idea what's going wrong?

If further information are needed please let me know.

Cheers, Ralf
------------------
EDIT:
Log file entry which occurs repeatingly:

Error	PHP	opendir(/mnt/shared/tmp): failed to open dir: Permission denied at /mnt/webu/xx/xx/xxxxxxx/htdocs/owncloud/lib/private/tempmanager.php#179	2015-07-09T14:37:49+00:00

**Comment by RealRancor** [comment]
> failed to open dir: Permission denied

Seems you have an permission issue on this folder which you should fix first.

**Comment by Allibabba** [comment]
@RealRancor 
Thanks, but I suppose another problem:

From Logfile:

Debug calendar 
OC_Calendar_App::generateEventOutput Object contains not event: Array ( [id] => 0 [vevent] => Sabre\VObject\Component\VCalendar Object ( [name] => VCALENDAR [children] => Array ( [0] => Sabre\VObject\Property\FlatText Object ( [delimiter] => , [structuredValues:protected] => Array ( [0] => N [1] => ADR [2] => ORG [3] => GENDER [4] => REQUEST-STATUS ) [minimumPropertyValues:protected] => Array ( [N] => 5 [ADR] => 7 ) [name] => VERSION [group] => [parameters] => Array ( ) [value:protected] => 2.0 [parent] => Sabre\VObject\Component\VCalendar Object *RECURSION* [iterator:protected] => [root:protected] => Sabre\VObject\Component\VCalendar Object *RECURSION* ) [1] => Sabre\VObject\Property\FlatText Object ( [delimiter] => , [structuredValues:protected] => Array ( [0] => N [1] => ADR [2] => ORG [3] => GENDER [4] => REQUEST-STATUS ) [minimumPropertyValues:protected] => Array ( [N] => 5 [ADR] => 7 ) [name] => PRODID [group] => [parameters] => Array ( ) [value:protected] => -//ownCloud//NONSGML Contacts 0.4.0.0//EN [parent] => Sabre\VObject\Component\VCalendar Object *RECURSION* [iterator:protected] => [root:protected] => Sabre\VObject\Component\VCalendar Object *RECURSION* ) [2] => Sabre\VObject\Property\FlatText Object ( [delimiter] => , [structuredValues:protected] => Array ( [0] => N [1] => ADR [2] => ORG [3] => GENDER [4] => REQUEST-STATUS ) [minimumPropertyValues:protected] => Array ( [N] => 5 [ADR] => 7 ) [name] => CALSCALE [group] => [parameters] => Array ( ) [value:protected] => GREGORIAN [parent] => Sabre\VObject\Component\VCalendar Object *RECURSION* [iterator:protected] => [root:protected] => Sabre\VObject\Component\VCalendar Object *RECURSION* ) ) [parent] => [iterator:protected] => [root:protected] => Sabre\VObject\Component\VCalendar Object *RECURSION* ) [repeating] => 1 [summary] => [calendardata] => BEGIN:VCALENDAR VERSION:2.0 PRODID:-//ownCloud//NONSGML Contacts 0.4.0.0//EN CALSCALE:GREGORIAN END:VCALENDAR ) 

Debug Caldav:
Exception: {"Message":"HTTP\/1.1 401 No basic authentication headers were found","Code":0,"Trace":"#0 \/mnt\/webu\/d2\/04\/53748104\/htdocs\/owncloud\/lib\/private\/connector\/sabre\/auth.php(149): Sabre\\DAV\\Auth\\Backend\\AbstractBasic->authenticate(Object(Sabre\\DAV\\Server), 'ownCloud')\n#1 \/mnt\/webu\/d2\/04\/53748104\/htdocs\/owncloud\/lib\/private\/connector\/sabre\/auth.php(122): OC\\Connector\\Sabre\\Auth->auth(Object(Sabre\\DAV\\Server), 'ownCloud')\n#2 \/mnt\/webu\/d2\/04\/53748104\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php(118): OC\\Connector\\Sabre\\Auth->authenticate(Object(Sabre\\DAV\\Server), 'ownCloud')\n#3 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/mnt\/webu\/d2\/04\/53748104\/htdocs\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#5 \/mnt\/webu\/d2\/04\/53748104\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#6 \/mnt\/webu\/d2\/04\/53748104\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#7 \/mnt\/webu\/d2\/04\/53748104\/htdocs\/owncloud\/apps\/calendar\/appinfo\/remote.php(57): Sabre\\DAV\\Server->exec()\n#8 \/mnt\/webu\/d2\/04\/53748104\/htdocs\/owncloud\/remote.php(132): require_once('\/mnt\/webu\/d2\/04...')\n#9 {main}","File":"\/mnt\/webu\/d2\/04\/53748104\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Backend\/AbstractBasic.php","Line":70}

**Comment by Allibabba** [comment]
I close this ticket as I was able to clean most of the problems so there are no more entries in the logfile so far. Unfortunately the mentioned IOS share problem still persists. I'll have another try in the forum.

**Comment by bcutter** [comment]
So how did you manage to "clean most of the problems"? I have the problem that calender event sync from/to iDevices doesn´t work anymore since OC v8.1.1...

**Comment by Allibabba** [comment]
Sorry for my late response...
I had the same problems with calendar and contacts sync. Contacts could be fixed with a small adjustment in app.php. The calendar problem could be solved with the latest master version 0.7.2.

"clean most of the problems" was related to some problems shown in the logfile which had nothing to do with sync issues.
