### ISSUE TITLE
Web App inaccessible with 8.1 - Sync OK

### ISSUE THREAD

**Issue by aproposnix** [owncloud/core#17525]
Hi Everyone,

After upgrading to 8.1 today from the Ubuntu PPA (maintained by SuSE I think) I am not able to access the app from a browser. I just get a blank page. 

Here are the steps before breaking it: 
1. Upgraded to 8.1 via system update in Ubuntu 14.04
2. Started the Upgrade process. 
3. Finished the upgrade process without issue
4. Opened up the app manager (as most of the apps were disabled) 
5. Tried to upgrade the Owncloud News app (which was not enabled) by clicking on the upgrade button. Nothing happened. 
6. Tried going back to 'Files' and then I got the blank page. 

Synchronization *is* working. Only the web app is not accessible. 

Could anyone give me some guidance on how to recover from this?

**Comment by DeepDiver1975** [comment]
> I just get a blank page.

Please have a look at the log for errors

**Comment by aproposnix** [comment]
I'm looking at the log (which is almost 30mb). I'm not really sure what I should be looking for. Any pointers?

**Comment by DeepDiver1975** [comment]
1. tail -f data/owncloud.log
2. hit reload on the browser
3. paste new listed log messages in here

**Comment by oparoz** [comment]
It would be useful to post the list of enabled and disabled apps.

**Comment by aproposnix** [comment]
@DeepDiver1975 
Thanks for that. The output is as follows: 

>"reqId":"5CpCW6ug+o2oaDQ8HUhN","remoteAddr":"10.0.0.138","app":"PHP","message":"Access to undeclared static property: Sabre\\VObject\\Property::$classMap at \/var\/www\/owncloud\/apps\/calendar\/appinfo\/app.php#37","level":3,"time":"2015-07-09T13:14:32+00:00"}

So I guess it's a problem with calendar (though I did not enable it - it was disabled during the upgrade process).  Any ideas on how to resolve this? Manually deleting the calendar app? 

@oparoz - All apps were disabled during the upgrade (Only files and Pictures were available).  The disabled apps were calendar, News, Text Search, Tasks, and all other oob apps.
