### ISSUE TITLE
Prevent closing upgrade page while upgrade in progress

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#17528]
### Steps to reproduce
1. Run OC upgrade using the web UI by clicking on "Start update"
2. During the upgrade, close the browser tab

### Expected result
A warning shows that upgrade is in progress.

### Actual result
Tab can be closed.

@owncloud/designers

**Comment by jancborchardt** [comment]
Is it necessary to keep the window open though? Isn’t it just a PHP process kicked off by the click on the update button?

If it indeed needs to be kept open, we need to go for one of these on tab close JS listeners.

**Comment by PVince81** [comment]
That's something that needs to be verified.
Some environments might kill the PHP process when the connection is gone, possibly php-fpm.

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/19748

**Comment by enoch85** [comment]
Nice fix! I actually thought of this a while but never knew how it actually was.
