### ISSUE TITLE
unsuccessful update 8.0.4 to 8.1

### ISSUE THREAD

**Issue by ruspantini** [owncloud/core#17534]
Hail to all,

My computer is set in French. I have just installed ownCloud this week and not yet finished configuring it to synchronise my contacts and calendar.
I tried the recent upgrade and got this error :

La mise à jour de ownCloud vers la version 8.1.0 est en cours. 
Cela peut prendre un certain temps.

Mode de maintenance activé
Mise à jour du schéma de la base de données vérifiée
Mise à jour du schéma de la base de données pour les applications vérifiée
Base de données mise à jour
Mise à jour de « updater » vers 0.6
Mise à jour de « activity » vers 2.0.1
Mise à jour de « files_sharing » vers 0.6.2
Mise à jour de « files_trashbin » vers 0.6.3
Mise à jour de « files_versions » vers 1.0.6
GuzzleHttp\Exception\RequestException: cURL error 60: See http://curl.haxx.se/libcurl/c/libcurl-errors.html
The update was unsuccessful. Please report this issue to the ownCloud community.

Please help me to finish upgrading and maybe configure an android connection (this may not be the right place ?)

Thanks in advance
Luca

**Comment by DeepDiver1975** [comment]
Thanks a lot for reporting issues back to us!

We need some more information to properly support you with your issue!

Can I ask you to follow our guidelines for submitting bugs as described here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

Thanks a lot!

**Comment by ruspantini** [comment]
Hi DeepDiver, 

Thanks for your swift answer.

I just reinstalled the upgrade and it seems to have worked fine :-) Should I still report this as you asked ?
Furthermore, can I get help here to connect an android device to ownCloud here ?

**Comment by ruspantini** [comment]
Looks like I need help to fill this out. Is what I have done enough ?

### Steps to reproduce
1.
2.
3.

### Expected behaviour
update from 8.0.4 to 8.4.

### Actual behaviour
Error message posted above. Seems to work after reinstall. Calendar and Contacts have disappeared. Do I have to go all the way through that again ? I only configured one PC. Still have to configure another Labtop + android device

### Server configuration
**Operating system**:
Windows seven

**Web server:**
http://www.architectes.pro/owncloud

**Database:**
?
**PHP version:**
?

**ownCloud version:** (see ownCloud admin page)
8.1

**Updated from an older ownCloud or fresh install:**
8.0.4 to 8.1

**List of activated apps:**
all were deleted
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```
I don't know ?
**The content of config/config.php:**
Have to look it up
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system --public
from within your ownCloud installation folder
I don't know ?
or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
SoGo
```
On ownCloud 7+ with access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder
I use ownCloud 8.1.0 (stable) updated today from 8.0.4

On ownCloud 6 with access to your command line run e.g.:
sqlite3 data/owncloud.db or mysql -u root -p owncloud
then execute:  select * from oc_appconfig where appid='user_ldap';

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query above.

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
Firefox

**Operating system:**
Windows 7
### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by ruspantini** [comment]
I tried to reinstall "calendar" and got this error : cURL error 60: See http://curl.haxx.se/libcurl/c/libcurl-errors.html
I tried to reinstall "contacts" and got the same error : cURL error 60: See http://curl.haxx.se/libcurl/c/libcurl-errors.html

**Comment by RealRancor** [comment]
The curl error is discussed here: https://github.com/owncloud/core/issues/17446

**Comment by ruspantini** [comment]
Thank you RealRancor I will look it up

**Comment by ruspantini** [comment]
They don't seem to have found a solution ? Forgive my lack of knowledge. I don't understand most of all this. They only speak of calendar app. I have a contact issue too. Should I wait for a fix ?

**Comment by ruspantini** [comment]
Avertissements de sécurité & configuration

    Le module PHP 'fileinfo' est manquant. Il est vivement recommandé de l'activer afin d'obtenir de meilleurs résultats de détection mime-type.

    Aucun cache de la mémoire n'est configuré. Si possible, configurez un "memcache" pour augmenter les performances. Pour plus d'information consultez la documentation.
    /dev/urandom n'est pas lisible par PHP, ce qui est fortement déconseillé pour des raisons de sécurité. Plus d'informations peuvent être trouvées dans notre documentation.
    Vous accédez à ce site via HTTP. Nous vous recommandons fortement de configurer votre serveur pour forcer l'utilisation de HTTPS, comme expliqué dans notre aide à la sécurité.

**Comment by RealRancor** [comment]
Please avoid posting untranslated error messages. You can't expect that people are speaking french in here or translating the errors.

The messages itself are clear and needs to be fixed by you according to the documentation available at https://docs.owncloud.org

**Comment by ruspantini** [comment]
Forgive me RealRancor, I was just trying to help giving some more information that might solve our problems.

**Comment by MorrisJobke** [comment]
Seems like everything in here is working now. I can't find any further useful information and will close this now.

@ruspantini Feel free to report back and we can reopen if you want.
