### ISSUE TITLE
More options per  Windows Network Drive 

### ISSUE THREAD

**Issue by Froster** [owncloud/core#17532]
Hi,

as Administrator i would configure a Windows Network Drive (each of them) with the following Options:

1) User could share yes / no (actually only global)

2) Will be synchronized with clients  yes / no

If you have global shares in an enterprise with TB of Data there is no sense to sync them to you local hard disk. Actual default is "No" i think.

**Comment by cdamken** [comment]
@MorrisJobke @MTRichards 

00003499

**Comment by MorrisJobke** [comment]
Opened in the WND repo.
