### ISSUE TITLE
occ command to update thumbnails

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#17536]
Some users might upload large collections of media files to their instance and they won't be able to use Gallery until a significant amount of thumbnails are generated.

There are on-going discussions on how to queue that process, but in the mean time, it could be very useful to have an occ command which generates all thumbnails.

@libasys @jospoortvliet @DeepDiver1975

**Comment by DeepDiver1975** [comment]
sounds reasonable - as long as encryption is not enabled and no remote storage is used

**Comment by DeepDiver1975** [comment]
pull request is welcome

**Comment by jospoortvliet** [comment]
agreed on all points ;-)

**Comment by oparoz** [comment]
There is now a solution in https://github.com/owncloud/gallery/pull/387

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/issues/11685.

At some point bkg jobs will be triggerable through occ
