### ISSUE TITLE
Restarting aborted encryption migration results in faulty folder-nesting

### ISSUE THREAD

**Issue by xn--nding-jua** [owncloud/core#17545]
### Steps to reproduce
1. Prepare update from ownCloud 8.0.2 to 8.1.0 (unpack zip-file to folder, copy data-folder, etc.)
2. Start update with "php occ upgrade"
3. Install DEFAULT-ENCRYPTION-MODULE over the App-Store within ownCloud web-interface
3. start migration of encryption "php occ encryption:migrate"
4. Abort migration (maybe because of an ssh-interruption)
5. restart migration with "php occ encryption:migrate"

### Expected behaviour
The migration to v2 should recognize the started but aborted migration, restore the backup and restart the fresh migration (maybe with a pre-created file called "migratingfilesinprogress.php" which can be deleted after the migration-process again).

### Actual behaviour
The aborted migration started to reorder the folder-structure of the keys. The restart of the migration creates an additional folder "files" within the folder "data/files/USERNAME/files_encryption/keys/" resulting in "data/files/USERNAME/files_encryption/keys/files/files/files/files" after several restarts of the migration. Several subfolders named "OC_DEFAULT_MODULE" are created as well so an unexperienced user will mess up his installtion completely (like me *lol*)

After restoring the key-structure with the backup and do a fresh migration, everything seems to be OK again.

Maybe this will happen with the web-interface-migration as well!?

### Server configuration
**Operating system**:
Ubuntu 14.04.2 LTS

**Web server:**
Apache (unknown version)

**Database:**
SQL 5.4

**PHP version:**
PHP 5.5

**ownCloud version:** (see ownCloud admin page)
old one: 8.0.2
upgraded one: 8.1.0.8

**Updated from an older ownCloud or fresh install:**
from an older installation (8.0.2)

**List of activated apps:**
 activity: 2.0.1
 - bookmarks: 0.4
 - calendar: 0.7.1
 - contacts: 0.4.0.0
 - documents: 0.9.0
 - encryption: 1.0.0
 - files: 1.1.9
 - files_gpxviewer_extended: 1.4
 - files_locking:
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - galleryplus: 12
 - mail: 0.1.3
 - music: 0.3.6
 - tasks: 0.6.0
 - updater: 0.6
Disabled:
 - external
 - files_external
 - gallery
 - ocsms
 - provisioning_api
 - templateeditor
 - user_external
 - user_ldap
 - user_webdavauth

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => 'xxxx',
  'passwordsalt' => 'xxxx',
  'trusted_domains' => 
  array (
    0 => 'www.xxxx.de',
    1 => 'cloud.xxxx.de',
    2 => 'xxxx.de',
  ),
  'datadirectory' => '/www/htdocs/xxxx/xxxx/cloud/data',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'xxxx',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxxx',
  'dbpassword' => 'xxxx',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'mail_from_address' => 'xxxx',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'xxxx.de',
  'forcessl' => true,
  'trashbin_retention_obligation' => 60,
  'trashbin_auto_expire' => true,
  'loglevel' => 2,
  'log_rotate_size' => false,
  'logtimezone' => 'Europe/Berlin',
  'check_for_working_webdav' => true,
  'check_for_working_htaccess' => true,
  'xframe_restriction' => false,
  'secret' => 'xxxx',
  'forceSSLforSubdomains' => true,
  'tempdirectory' => '/www/htdocs/xxxx/tmp',
  'enable_previews' => true,
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\Image',
    1 => 'OC\\Preview\\MP3',
    2 => 'OC\\Preview\\TXT',
    3 => 'OC\\Preview\\MarkDown',
    4 => 'OC\\Preview\\Illustrator',
    5 => 'OC\\Preview\\Postscript',
    6 => 'OC\\Preview\\Photoshop',
    7 => 'OC\\Preview\\TIFF',
  ),
  'singleuser' => false,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox 39

**Operating system:**
Windows 7 64-Bit

**Comment by karlitschek** [comment]
@schiesbn

**Comment by PVince81** [comment]
I believe that migration can now be resumed if I remember correctly, @schiesbn can you confirm ?

**Comment by PVince81** [comment]
From what I remember there were fixes to make the migration process resumable.
Please try again with 8.1.5 or 8.2.2
