### ISSUE TITLE
is 8.05ES supposed to upgrade to 8.1?

### ISSUE THREAD

**Issue by carlaschroder** [owncloud/core#17541]
Hellos! My local installation of 8.05ES displayed an upgrade notification when 8.1 Server was released. So I upgraded. The upgrade went fine, but was it supposed to do that? It doesn't seem like Enterprise releases should get the same upgrade notifications as Server.

**Comment by carlaschroder** [comment]
BTW, I know everyone still calls them Community and Enterprise, but the official 8.x names are Server and Enterprise Subscription. Just so y'all know what I'm talking about :)

**Comment by karlitschek** [comment]
How did you install that? Via a linux package? Because the updater app is not activated yet.

**Comment by carlaschroder** [comment]
Yes, via the enterprise repo, and yes, there is no updater app. 
I bet this is due to my confused owncloud.list:

deb http://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_14.04/ /
deb https://***:***@download.owncloud.com/download/repositories/8.0.2/xUbuntu_14.04/ /

**Comment by karlitschek** [comment]
@jnweiger There should be no update in the enterprise repo yet. Can you check please?

**Comment by carlaschroder** [comment]
I'll do a bit of testing, but I'll wager a good German beer that's the cause. Closing; if it does it again with a clean owncloud.list I'll open a new issue.
