### ISSUE TITLE
Upgrade error

### ISSUE THREAD

**Issue by dehein** [owncloud/core#17542]
After upgrading my ubuntu 14.04 machine via terminal or website.  I get this:
my server was encrypted, also i had a webdav dropbox drive. even after deactivating both. nothing happens to get better.

Wartungsmodus eingeschaltet
Datenbankschema-Aktualisierung überprüft
Datenbankschema-Aktualisierung für Apps überprüft
Datenbank aktualisiert
„user_webdavauth“ zu 1.1.0.2 aktualisiert
Wartungsmodus ausgeschaltet

and it returns again to the website to prompt me for an upgrade. it loops itself.
my owncloud.log:
http://pastebin.com/HMsbvnKY

**Comment by MorrisJobke** [comment]
@dehein Can you run the upgrade steps on the console? See https://doc.owncloud.org/server/8.1/admin_manual/configuration_server/occ_command.html#upgrade-command

**Comment by dehein** [comment]
This is what happens:
root@hein:/var/www/owncloud# sudo -u www-data php occ upgrade
ownCloud or one of the apps require upgrade - only a limited number of commands are available
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Disabled 3rd-party app: files_encryption
Disabled 3rd-party app: files_mv
Disabled 3rd-party app: grauphel
Disabled 3rd-party app: notes
Updating <user_webdavauth> ...
Updated <user_webdavauth> to 1.1.0.2
Updating <activity> ...
Updated <activity> to 2.0.1
Updating <files_sharing> ...
Updated <files_sharing> to 0.6.2
Updating <files_versions> ...
Updated <files_versions> to 1.0.6
Update successful
Turned off maintenance mode
root@hein:/var/www/owncloud# sudo -u www-data php occ upgrade
ownCloud or one of the apps require upgrade - only a limited number of commands are available
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Updating <user_webdavauth> ...
Updated <user_webdavauth> to 1.1.0.2
Update successful
Turned off maintenance mode
root@hein:/var/www/owncloud#

**Comment by MorrisJobke** [comment]
It seems to have problems with user_webdavauth. Can you disable this app and try again?

**Comment by dehein** [comment]
The fix was to disable my Dropbox which i had integrated as external space. Now it works.
