### ISSUE TITLE
Restarting aborted file encryption migration fails

### ISSUE THREAD

**Issue by underflyer** [owncloud/core#17547]
Hi,

after trying to migrate my 8.0.4 to 8.1 with newest migration.php and storage.php from @schiesbn  migration seems to work. Even LDAP-User-Files seems to work.

but after about x-Users my php ran out of memory with this error:
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 181 bytes) in /var/www/owncloud/htdocs/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 91

and when i try to restart the migration
apache@owncloud ~/owncloud/htdocs/owncloud $ php occ encryption:migrate
Reorganize system folder structure
Migrating keys for users on backend Database
   admin

  [OCP\Files\LockNotAcquiredException]
  Could not obtain lock type 1 on "/home/owncloud/data/admin/files_encryption/admin.privateKey".

Can you fix this by change the migration.php to discover already updated user, to be able to restart the migration-process?

Thanks

**Comment by karlitschek** [comment]
@schiesbn

**Comment by SerialG** [comment]
Hi, 
I've got the same problem! 
Is there something new?
Could you also specify a "secure" memory_limit setting fro PHP in order to avoid this error?

Thanks!

**Comment by schiesbn** [comment]
If I remember this is a LDAP issue and how we fetch the users. I remember @blizzz run into a similar issue but afaik only with xdebug enabled. @blizzz anything we can do here?

**Comment by blizzz** [comment]
Oh, we have seen something indeed, but did not we fix it @schiesbn? My memory is somewhat dark.

**Comment by schiesbn** [comment]
If I remember correctly you got a "max nested level reached" because LDAP fetch the users recursively. Then you disabled xdebug and it was no longer an issue. But of course this only solved the limit of nested function calls. The memory still increases for every call, so you can still reach a memory limit. The obvious solution would be to switch from recursive function calls to a simple loop. But it is probably not easy/possible to change the way the LDAP connection works?

**Comment by blizzz** [comment]
Of course. But did not we took some kind of action?

**Comment by schiesbn** [comment]
I don't remember anything. Afaik it was just a side effect while you tested another issue. So the action was to disable xdebug if I remember correctly... Let me try to find the issue.

**Comment by PVince81** [comment]
@schiesbn did you find the issue eventually ?

**Comment by PVince81** [comment]
Memory usage and speed was reduced a while ago in recent versions using capped caches, please try those.

If the problem persists, please reopen.
