### ISSUE TITLE
OC.Previews utility in JS side telling what preview mimetypes are available

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#17543]
@rullzer @oparoz as discussed, a utility class on the JS side that stores a list of mimetypes for which previews are supported.

This makes it possible to get rid of "isPreviewAvailable" so the server doesn't have to compute and return this for every file.

**Comment by PVince81** [comment]
This could go even further and provide utility methods to retrieve previews either for file icons or also real thumbnails. Basically move "lazyLoadPreviews" here but give it a better name.

Then also find a way to override it for the public page.

**Comment by oparoz** [comment]
OK from me. Gallery already uses such an array to build the thumbnails list or the slideshow, so all good.

**Comment by PVince81** [comment]
@VicDeo didn't we add something recently to avoid 404s ?

**Comment by VicDeo** [comment]
@PVince81 here you go https://github.com/owncloud/core/blob/master/core/js/config.php#L172
Seems to be done.
