### ISSUE TITLE
Upgrading from 8.0.2 to 8.1.0 messes up encryption public-keys

### ISSUE THREAD

**Issue by xn--nding-jua** [owncloud/core#17544]
### Steps to reproduce
1. Prepare update from ownCloud 8.0.2 to 8.1.0 (unpack zip-file to folder, copy data-folder, etc.)
2. Start update with "php occ upgrade"
3. After update finishes start migration of encryption over the console directly (which is not the correct way - as I realized later) "php occ encryption:migrate"

### Expected behaviour
The encryption-migration to version 2 should be aborted with an error, that the DEFAULT-ENCRYPTION-MODULE ist not installed/set

### Actual behaviour
The encryption creates a backup of the old keys and starts migrating the key-structure to the new folder-structure. As the DEFAULT-ENCRYPTION-MODULE is missing, at least the public-keys of all users are mixed up without an error. The file-keys are still OK as they are not affected by the migration itself.

After restoring everything and installing the DEFAULT-ENCRYPTION-MODULE the ownCloud 8.1 installation could be finished. The problem is, that all encrypted files can be opened without problem, so that nobody cares about the problem until a new file has to be encrypted. Then the bad public-key will be used and corrupts the encrypted file that is useless from then on!!!

Sorry, but within my panic I did not saved the log-files so the description above is everything I have. Fact is, that several users had new public-keys at the end of the migration while the private-keys and file-keys as well as the restore-key remain the old (working/correct) one.

### Server configuration
**Operating system**:
Ubuntu 14.04.2 LTS

**Web server:**
Apache (unknown version)

**Database:**
SQL 5.4

**PHP version:**
PHP 5.5

**ownCloud version:** (see ownCloud admin page)
old one: 8.0.2
upgraded one: 8.1.0.8

**Updated from an older ownCloud or fresh install:**
from an older installation (8.0.2)

**List of activated apps:**
 activity: 2.0.1
 - bookmarks: 0.4
 - calendar: 0.7.1
 - contacts: 0.4.0.0
 - documents: 0.9.0
 - encryption: 1.0.0
 - files: 1.1.9
 - files_gpxviewer_extended: 1.4
 - files_locking:
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - galleryplus: 12
 - mail: 0.1.3
 - music: 0.3.6
 - tasks: 0.6.0
 - updater: 0.6
Disabled:
 - external
 - files_external
 - gallery
 - ocsms
 - provisioning_api
 - templateeditor
 - user_external
 - user_ldap
 - user_webdavauth

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => 'xxxx',
  'passwordsalt' => 'xxxx',
  'trusted_domains' => 
  array (
    0 => 'www.xxxx.de',
    1 => 'cloud.xxxx.de',
    2 => 'xxxx.de',
  ),
  'datadirectory' => '/www/htdocs/xxxx/xxxx/cloud/data',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'xxxx',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxxx',
  'dbpassword' => 'xxxx',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'mail_from_address' => 'xxxx',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'xxxx.de',
  'forcessl' => true,
  'trashbin_retention_obligation' => 60,
  'trashbin_auto_expire' => true,
  'loglevel' => 2,
  'log_rotate_size' => false,
  'logtimezone' => 'Europe/Berlin',
  'check_for_working_webdav' => true,
  'check_for_working_htaccess' => true,
  'xframe_restriction' => false,
  'secret' => 'xxxx',
  'forceSSLforSubdomains' => true,
  'tempdirectory' => '/www/htdocs/xxxx/tmp',
  'enable_previews' => true,
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\Image',
    1 => 'OC\\Preview\\MP3',
    2 => 'OC\\Preview\\TXT',
    3 => 'OC\\Preview\\MarkDown',
    4 => 'OC\\Preview\\Illustrator',
    5 => 'OC\\Preview\\Postscript',
    6 => 'OC\\Preview\\Photoshop',
    7 => 'OC\\Preview\\TIFF',
  ),
  'singleuser' => false,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox 39

**Operating system:**
Windows 7 64-Bit

**Comment by MorrisJobke** [comment]
cc @schiesbn

**Comment by MorrisJobke** [comment]
@th3fallen

**Comment by cmonteroluque** [comment]
@schiesbn

**Comment by PVince81** [comment]
8.1.0 is old, might be fixed in 8.1.5 already.

@xn--nding-jua was this with your live system or were you able to reproduce this on a test system ?

**Comment by cmonteroluque** [comment]
update?

**Comment by xn--nding-jua** [comment]
Hi, I've got no updates for this. It was my productive system and I was glad that my backup has worked. So maybe we can close it.

**Comment by PVince81** [comment]
Ok, thanks for the feedback. Closing.
