### ISSUE TITLE
8.1 apps list has disappeared.

### ISSUE THREAD

**Issue by lachlan-00** [owncloud/core#17550]
After my upgrade to 8.1yesterday i was able to enable all my apps. I logged out and it about 4 times as well as upgrade/disable apps after the initial upgrade

today i went into the apps list and it's empty.
![screenshot from 2015-07-10 13-37-02](https://cloud.githubusercontent.com/assets/1305249/8611750/3797dbb6-2709-11e5-9acb-d1ec5539163b.png)

all my active apps are still enabled.

There are a heap of search_lucene errors in my log but that's about it.

**Comment by RealRancor** [comment]
Could be a dup of https://github.com/owncloud/core/issues/14185

**Comment by lachlan-00** [comment]
could be related, i do get warnings in my admin page that memory cache isn't set up

    No memory cache has been configured. To enhance your performance please configure a memcache if available. Further information can be found in our documentation.

    The "Strict-Transport-Security" HTTP header is not configured to least "15768000" seconds. For enhanced security we recommend enabling HSTS as described in our security tips.

**Comment by lachlan-00** [comment]
By enabling caching in my config i get my app list back.

https://owncloud.org/blog/making-owncloud-faster-through-caching/

APCu (for PHP 5.5 and above) (php5-apcu in debian)

edit config.php and add
'memcache.local' => '\OC\Memcache\APCu',

This information really needs to go into the "documentation" link. [https://doc.owncloud.org/server/8.1/admin_manual/configuration_server/performance_tuning.html#caching]

The current docs make absolutely no sense as to what you actually have to do to turn caching on. It explains what caching is for different versions of php and then hides the settings for the average php version in a separate link.

The blog post should be aped into the doc link instead as well as split those links up into smaller pages.

**Comment by RealRancor** [comment]
@lachlan-00 See https://github.com/owncloud/documentation/issues/1233
