### ISSUE TITLE
log messages should contain the app name

### ISSUE THREAD

**Issue by j-ed** [owncloud/core#17554]
## Expected behavior
It should be possible to identify log messages, which are caused by an app, by the app name.

## Current behavior
All log messages are currently logged under the same app name `core`. This doesn't allow to filter messages based on an app. Example:
```
{"reqId":"095ebff419020d5b326d09d33a32c20f","remoteAddr":"192.168.1.67","app":"core","message":"DB prepare : SELECT ` ...
{"reqId":"095ebff419020d5b326d09d33a32c20f","remoteAddr":"192.168.1.67","app":"core","message":"DB execute with arguments : array ( )",...
```
#### Server Configuration
OS: Linux 3.2.67
Web server: Apache2 2.4.12
Database: MySQL 5.1.73
PHP version: 5.4.42
ownCloud version: 8.0.5

#### Client Configuration
Browser: Firefox 39.0
Operating system: Windows 7

**Comment by PVince81** [comment]
The messages produced by core code will have "core" as app name.
If another app logs a message, then their app name will be used instead.

The core code has no way to find out which app called the core database utility routines, so this is not technically possible.

It looks like what you are requesting here is specific to database calls ?

**Comment by j-ed** [comment]
I realized that almost all logged messages were labled "core", although some of the log message had been initiated by e.g. the calendar app. Additionally I wondered why a field "app" exists in every log entry if it didn't contain the calling app and why it shouldn't be possible to use the correct app name for it.
I think that had been the intension why I opened this issue report that time.

**Comment by PVince81** [comment]
Detecting which app made a call is difficult and would require parsing the stack trace to find out where the call is coming from. This would also be quite slow especially if it needs to be done for every single log entry.

Not technically possible in the OC architecture, closing.
