### ISSUE TITLE
Sharing from server A daily (https) to server B (http) federated sharing does not work

### ISSUE THREAD

**Issue by davitol** [owncloud/core#17551]
### Steps to reproduce
1. Share a file from the browser A (https) to another server.(http)

### Expected behaviour
The file is shared and visible in server B

### Actual behaviour
The file is not show in server B and the following log appears:
{"reqId":"ecf34012a78c62e927e9ba953f304943","remoteAddr":"82.159.139.58","app":"PHP","message":"Call to undefined method OCA\\Files_Sharing\\External\\Storage::propfind() at \/opt\/owncloud\/lib\/private\/files\/storage\/dav.php#487","level":3,"time":"2015-07-10T08:48:42+00:00"}

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** Server A: version":"8.2.0.1","versionstring":"8.2 pre alpha","edition"
                                    Server B :"8.0.5.2","versionstring":"8.0.5 

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity
 - admin_audit
 - enterprise_key
 - files
 - files_locking
 - files_pdfviewer
 - files_sharing
 - files_sharing_log
 - files_texteditor
 - files_trashbin
 - files_versions
 - files_videoviewer
 - firewall
 - firstrunwizard
 - gallery
 - provisioning_api
 - templateeditor
 - updater
 - windows_network_drive

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

**Comment by davitol** [comment]
1.- Using a browserX connect to an ownCloud server whose version is 8.1, user1
2.- From user1 (8.1) share a file (federated sharing) with user2 (8.0.5)
3.- Log in user2, accept the shared file
4.- The file is not included on user2 file list
5.- From user1, share another file
6.- It is shown the message to accept the shared file

Current behaviour
Nothing is shown on the file list, but files are kept in the data folder. It is only a webUI bug

**Comment by karlitschek** [comment]
@schiesbn Can you have a look? :-)

**Comment by DeepDiver1975** [comment]
fixes with #17566

**Comment by jvillafanez** [comment]
Checked with server A (https) ownCloud Enterprise Edition 8.2 pre alpha (daily) Build:2015-07-16T03:10:28+00:00 dce462c28db1d5e5b144efcfb26a466bd290621c and server B (http) ownCloud Enterprise Edition 8.0.5 (daily) Build:2015-07-16T03:25:43+00:00 96b252195b421a6bb1c5643dbd15a958d0317295
