### ISSUE TITLE
Feature Request: Admin List Shares

### ISSUE THREAD

**Issue by guyfromwork** [owncloud/core#17552]
Hi,

good day to all of you.

Not sure, if this is the right place, but I'd like to post a feature-request:

As Admin I'd have to check shares, since users keep forgetting about them.
So I would like to know:
- Name of the share
- Shared since when
- Protected with a password?
- Expiration date set? If so: which date?

I haven't figured out a Linux-command to get these informations.
There is an app (List of shares 0.1), but since this has been posted 2014 (for owncloud 6), I am not sure if using it would be a good idea. Anyhow, there is no manual (app-installation) and I'm not a Linux-native, so I would have to find out how to do so first.

Looking forward to hearing from you,
Maurice Moss, wait no, me: Alex :)

**Comment by bitking** [comment]
Good feature request, is there more information about this?

**Comment by PVince81** [comment]
Closing in favor of duplicate: https://github.com/owncloud/core/issues/20492
