### ISSUE TITLE
share mulitiplication on sharing a subfolder

### ISSUE THREAD

**Issue by litauer** [owncloud/core#17560]
Running owncloud 8.05 we have the following behavior when sharing a subfolder of an already shared folder:
- Create Folder1 and share it to user1 and user2
- Create Folder1/Folder2 and share it to user3 und user4

Now, when looking at the shares of Folder2 you see: user1, user2, user1, user2
Adding user5 to Folder2 leads to: user1, user2, user1, user2, user1, user2

Seems as if the shared users of Folder1 are multiplied by the number of shared users of Folder2.

**Comment by PVince81** [comment]
### Steps

1. Login as admin
1. Create users "user1", "user2", "user3" ,"user4"
1. Create a folder "folder1"
1. Share "folder1" with "user1"
1. Share "folder1" with "user2"
1. Create a folder "folder1/folder2"
1. Share "folder1/folder2" with "user3"
1. Share "folder1/folder2" with "user4"
1. Reopen the share dropdown for "folder1/folder2"

### Expected result
"Shared in folder1 with user1, user2"

### Actual result
"Shared in folder1 with user1, user2, user1, user2"
![share-repeated](https://cloud.githubusercontent.com/assets/277525/10394988/e4b35dc4-6e9a-11e5-84b0-2ec5d87040b5.png)

Confirmed on 8.1.3 and still happening in 8.2RC1.

**Comment by PVince81** [comment]
@rullzer @schiesbn

**Comment by amc2002** [comment]
@PVince81 - this is the same issue as 19517? The "user" referenced in my example that showed up 100 times wasn't an account user, it was the actual admin who shared the folder originally. Just checking.

**Comment by PVince81** [comment]
@amc2002 yes it is the same issue. In your case you probably had 100 subshares.
I just find that these steps here contains more clues: it seems that the number of times it is repeated is the same as the number of subshares. :smile:

**Comment by amc2002** [comment]
Is there a one stop place to see how many subshares? This is a relatively new share, and I don't think there are more than two or three subshares. I don't want to divert this thread too much, so if this issue above gets fixed, I'll test it out and then reopen my issue if necessary. Thanks.

**Comment by PVince81** [comment]
@amc2002 normally you should be able to see all the subshares inside the share dropdown in the screenshot you posted in https://github.com/owncloud/core/issues/19517
However there might not be scrollbars in it. You can try using the browser's DOM inspector and edit the long "admin, admin, admin" text and make it short enough. At this point hopefully you'll be able to see the share list in the current window.

**Comment by amc2002** [comment]
If I click on *each* folder under that main shared folder (before re-sharing it), every single one shows that list. I know for a fact not all of these folders are subshared. I'm inclined to think my issue is different (but could be caused by the same bug of course), as I see this *before* have shared anything. Perhaps I needed to be more clear in my description of the issue.

**Comment by PVince81** [comment]
How about the main share (the parent folder) ? Is it shared with several people ?

**Comment by amc2002** [comment]
Parent folder is shared with six *groups*, yes. If it seems like it might be caused by the same bug, I'm content to leave my bug closed and just retest once 17560 has been fixed.

**Comment by rullzer** [comment]
I'll look into this

**Comment by rullzer** [comment]
PR in #19730

**Comment by amc2002** [comment]
This fix in #19730 worked for my case AFTER I share the item. Once I share the item with any user or allow external sharing and enter a password, the list is correct.

Before I share the sub-folder, however, I still get the full list of repeating names.
