### ISSUE TITLE
APCu not working with memcache.so and apcu.so enabled

### ISSUE THREAD

**Issue by f-s** [owncloud/core#17562]
Hello,

with memcache.so 3.0.8 and apcu.so 4.0.2 enabled on both CLI and HTTPd on Ubuntu14.04, OC 8.1.0-2, I still get 

`ownCloud[32736]: {PHP} OC\HintException: Missing memcache class \OC\Memcache\APCu for local cache at /var/www/owncloud/lib/private/memcache/factory.php#75`

I have 
`memcache support => enabled`
and
`APCu Support => enabled`
for CLI environment and HTTPd, dbl checked.

My config.php line is:
`'memcache.local' => '\OC\Memcache\APCu',`
and
`apc.enable_cli=1`
for the inis

I use PHP 5.5.9-1ubuntu4.11 and php5-memcache, php5-apcu also not working with manual apcu 4.0.7 install.

Thank you

**Comment by giancarlobi** [comment]
My steps to make it working on Ubuntu 14.04 and OC8.1:
wget http://es.archive.ubuntu.com/ubuntu/pool/universe/p/php-apcu/php5-apcu_4.0.6-1_amd64.deb
dpkg -i php5-apcu_4.0.6-1_amd64.deb
service apache2 restart
cd /var/www/owncloud/
sudo -u www-data nano -w config/config.php
	'memcache.local' => '\OC\Memcache\APCu',

While I have to set apc.enable_cli=1 into /etc/php5/cli/php.ini to make cron job working with system cron and scheduled by contab.

**Comment by f-s** [comment]
Hello,

because of armv7, I did try your source ball, because the pear package did not work previously.

**Not** working: `php pickle.phar install --source apcu`

Working:

<pre>
wget http://es.archive.ubuntu.com/ubuntu/pool/universe/p/php-apcu/php-apcu_4.0.7.orig.tar.gz
tar xzfv php-apcu_4.0.7.orig.tar.gz
cd apcu-4.0.7/
phpize
./configure
make
checkinstall
made sure: /etc/php5/apache2/conf.d/20-apcu.ini loads the module
</pre>

The diff. is this source seems to have MMAP Support enabled, the other did not, compile it in, although selected during config.

Thanks!!!

**Comment by zaclys** [comment]
you have to enable apcu for cli 

on centos/fe/dora/redhat edit /etc/php.d/apcu.ini
apc.enable_cli=1

**Comment by smarek** [comment]
@zaclys verified this as correct solution for 8.1.0 install on Debian systems
