### ISSUE TITLE
Support for CMIS as external storage

### ISSUE THREAD

**Issue by remixtj** [owncloud/core#17563]
Hello,

i had a request from my collegues of the middleware dept. They would like to connect owncloud to their document management systems like Alfresco and IBM Filenet. The idea is to use owncloud as frontend to document management system and copy documents from and to it.
They told me that CMIS is a protocol used by their systems for communicate with Alfresco.

What about providing CMIS as supported protocol in External Storage (like S3, i.e.)?

**Comment by MorrisJobke** [comment]
cc @MTRichards @karlitschek  @icewind1991 @nickvergessen

**Comment by alekiy** [comment]
see also #8000

**Comment by remixtj** [comment]
I think that #8000 is about exposing CMIS services for owncloud. Instead this request is about implementing CMIS as external storage, so i can see file that are in alfresco/filenet like i can see files on external SMB/S3/ecc

**Comment by MTRichards** [comment]
We do have this in the backlog, but of course it depends on which CMIS we are talking about. This is really awaiting a definitive peak in demand for this connector, which is tough - not a lot of folks have documentum or FileNet sitting around outside of the enterprise, and CMIS is not really CMIS across implementations.

**Comment by httng** [comment]
There will never be a 'peak in demand' for this. It's a strategic decision to implement this as a Unique Selling Point: Many Enterprises will love to have one client that gives them access to all their files, regulated by a nice RBAC implementation. By adding a CMIS connector that is able to retrieve files from a Document Management System, Owncloud gains value for Enterprises.

I'd like it for my Enterprise solution.
