### ISSUE TITLE
files_encryption folder structure after migration to 8.1

### ISSUE THREAD

**Issue by jknockaert** [owncloud/core#17564]
After running the occ encryption key migration I noticed that for one user the filekeys were migrated to `data/<user>/files_encryption/keys/files/files/files/<path>/<filename>/OC_DEFAULT_MODULE/OC_DEFAULT_MODULE/OC_DEFAULT_MODULE/fileKey` (similar for the sharekeys). Not sure what triggered this nesting, but it's definitely not correct.
For the other users the keys were correctly moved to `data/<user>/files_encryption/keys/files/<path>/<filename>/OC_DEFAULT_MODULE/fileKey`. Note that for these users there was also an (empty?) folder structure created at `data/<user>/files_encryption/keys/<path>/<filename>`; these folders do not seem to serve any purpose and can be removed?

**Comment by jknockaert** [comment]
@schiesbn one more encryption issue that I hit.

**Comment by jknockaert** [comment]
pls note that I updated the first comment

**Comment by schiesbn** [comment]
> Note that for these users there was also an (empty?) folder structure created at `data/<user>/files_encryption/keys/<path>/<filename>`; these folders do not seem to serve any purpose and can be removed?

This is the old structure from oC8.0. The folders are empty because all keys where moved to the new location. Should be save to remove it.

Regarding the other issue, no idea what triggered it, especially if it only happens for one user. Is this re-producible? What happens if you restore the backup for this user and run ````occ encryption:migrate username````? Does it again create the wrong structure?

**Comment by jknockaert** [comment]
Running the migration for a specific user doesn't seem to do any significant action.

**Comment by ffflorian** [comment]
I'm not sure if this belongs to @jknockaert's error, but after upgrading to 8.1 I try to run
```occ encryption:migrate``` and I only get an error message:
```PHP Fatal error:  Call to a member function getRelativePath() on null in /var/www/owncloud/apps/files_trashbin/lib/storage.php on line 123```

**Comment by schiesbn** [comment]
@ffflorian no, that's discussed in great detail here: https://github.com/owncloud/core/issues/16928 Also with the patches and steps to fix it. I will write the necessary steps together and publish them later today

**Comment by ffflorian** [comment]
@schiesbn Thanks for the quick reply. I'll head over there then :smiley:

**Comment by schiesbn** [comment]
> Running the migration for a specific user doesn't seem to do any significant action.

Hm, I just tried it again. This command should migrate only the keys from the given user in his data directory

**Comment by jknockaert** [comment]
OK, I think it didn't work here because I forgot to reapply #17473 and #17474.
While checking the results of previous (failed) migrations to 8.1 I noticed that this nesting happened for other accounts as well. No clear pattern though.

**Comment by dizzy2604** [comment]
What should be the new structure looks like? i would like to place key manualy to appropriate directories. thanks

**Comment by schiesbn** [comment]
The new structure is described at the end of this document: https://doc.owncloud.org/server/8.1/admin_manual/configuration_files/encryption_configuration.html

**Comment by ffflorian** [comment]
@dizzy2604: I managed the problem with the keys with this structure:
```owncloud/data/files_encryption/OC_DEFAULT_MODUL/pubShare_[id].privateKey
owncloud/data/files_encryption/OC_DEFAULT_MODUL/pubShare_[id].publicKey
owncloud/data/[user]/files_encryption/OC_DEFAULT_MODULE/[user].privateKey
owncloud/data/[user]/files_encryption/OC_DEFAULT_MODULE/[user].publicKey```

**Comment by jknockaert** [comment]
OK it first didn't work because I forgot to set the owner right after moving the old keys back. Now I manage to do a one-user migration. The nested structure is however not reproduced. Seems like a fairly random event.

**Comment by jknockaert** [comment]
Actually the final file key folder structure for that user suggests that the file key migration happened three times in row, so for `folder/file.txt` it finally gives the folders:
*`files_encryption/keys/folder/file.txt/` (original file key location, empty after migration)
*`files_encryption/keys/files/folder/file.txt/OC_DEFAULT_MODULE/` (intermediate file key location?, empty after migration)
*`files_encryption/keys/files/files/folder/file.txt/OC_DEFAULT_MODULE/OC_DEFAULT_MODULE/` (intermediate file key location?, empty after migration)
*`files_encryption/keys/files/files/files/folder/file.txt/OC_DEFAULT_MODULE/OC_DEFAULT_MODULE/OC_DEFAULT_MODULE/` (final file key location)
If we have no idea how this happens I suggest that we leave the issue for now and advise users to rerun the migration for specific users if this happens. Until we do find out we should leave the issue open.

**Comment by dizzy2604** [comment]
after placing keys to appropriate directories, still can't open files via web interface, looks like some keys are not converted? is there any chance for recovery from this situation?

**Comment by xn--nding-jua** [comment]
Here is the reason, why the folder-nesting occurs:  #17545

**Comment by jknockaert** [comment]
@xn--nding-jua Thanks for pointing out. But in my case I can almost rule out this cause, as I first restored the pre-8.1 `files_encryption` folders using a short script that loops over the users. Upon running the migration script again the folder-nesting happened for only one user. But rather than finding the bug we may opt for a more generic approach that tackles both the issue I had (whatever caused it) and #17545.
