### ISSUE TITLE
forcessl => true not working for me since upgrade from 8.0.4 to 8.1

### ISSUE THREAD

**Issue by eomot** [owncloud/core#17567]
Hi.

I'm running owncloud on a Ubuntu 14.4 (but NOT a packaged owncloud) with apache 2.4.7
and MYSQL version: 5.5.43
Since upgrading to 8.1 (and running into lot's of migration problems - but that's a different story) I noticed that I can access my installation without SSL. Before the upgrade forcessl did work.
Now I had to include some .htaccess mod_rewrite stuff to make sure SSL is always used. But since the .htaccess file get's overwritten with every update that's not really a solution.

I do use a self signed certificate and I do use GnuTLS.

In config/config.php I have set the following (obviously a lot of stuff removed or redacted):
<?php
$CONFIG = array (
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'installed' => true,
  'allowZipDownload' => true,
  'maintenance' => false,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'loglevel' => '0',
  'trusted_domains' =>
  array (
    0 => '[redacted]',
  ),
 );

Any ideas what's causing this ?
Thanx!

**Comment by RealRancor** [comment]
This was removed in oC 8.1 and needs to be configured within your webserver:

https://doc.owncloud.org/server/8.1/admin_manual/configuration_server/harden_server.html#redirect-all-unencrypted-traffic-to-https

**Comment by novij** [comment]
why was this useful option removed? it made it a lot easier if using ispconfig

**Comment by RealRancor** [comment]
@novij 
> This changes also applies to the HTTPS enforcement of ownCloud that now has to happen on the web server layer and not anymore in the ownCloud configuration. While this is slightly less comfortable it ensures an overall better security level

from https://statuscode.ch/2015/05/security-and-owncloud-8.1/#security-related-headers-can-now-be-sent-by-the-web-server
