### ISSUE TITLE
[OC 8.1] WebDav missing permissions

### ISSUE THREAD

**Issue by deangenovski** [owncloud/core#17561]
It seems that in OC 8.1 the permissions for the webdav are missing. On Ubuntu when I mount an owncloud webdav resource and try to look up the permissions it says that permission information is not available. On Mac os the problem is even bigger because when not given any permissions the mac os client assumes readonly permission and does not allow for modifications of the files/folders.

Is there a known workaround because we use webdav most of the time and we are all using mac os.

**Comment by DeepDiver1975** [comment]
AFAIK we never exported webdav permission in the past - did this work in previous version?

**Comment by deangenovski** [comment]
Something must have changed because before the update this was working OK

**Comment by DeepDiver1975** [comment]
We did remove WebDAV locking support and the SabreDAV libraries have been updated - maybe something got lost on it's way .....

**Comment by martinsauter** [comment]
Just tried on OC 8.0.4 and the behavior is already present there when used with Ubuntu 14.04 webdav. When querying the permissions with the native Ubuntu GUI file browser I get a "The permissions of "xxxxx" could not be determined" (xxxxx = filename) instead of the permissions in the window. So this did not break in 8.1.

**Comment by vco1** [comment]
I can second this issue. It seems to prevent uploading via the files plugin in Zarafa too. Using OC 8.1 and ZCP 7.2. With OC < 8 this was working fine.

**Comment by DeepDiver1975** [comment]
It would be great to get someone on this who actually knows the nautilus code base and has an understanding of the requirement to display the permissions.

@jancborchardt @MorrisJobke maybe you find someone at guadec

**Comment by jancborchardt** [comment]
Maybe @cosimoc @csoriano89 of Nautilus know about this.

**Comment by cosimoc** [comment]
@jancborchardt This does not sound an issue with nautilus or gvfs, since the original comment mentions it also affects Mac OS. Let me know if I'm missing something though.

**Comment by DeepDiver1975** [comment]
Thx @cosimoc for your feedback. 

I'm not saying there is an issue with nautilus. 
My question is rather: what information needs to be returned by the server so that there is something displayed.

Is it related to the missing lock support?

**Comment by cosimoc** [comment]
@DeepDiver1975 I am not very familiar with the WebDAV implementation in gvfs; @rosslagerwall or @gicmo perhaps can answer that.

**Comment by rosslagerwall** [comment]
gvfs doesn't implement permissions support for webdav (neither reading permissions nor writing permissions). As far as I know, webdav doesn't expose these operations in any way. There is RFC 3744 which adds ACLs to webdav and Sabredav apparently supports it, but none of the major webdav clients support it.

**Comment by rosslagerwall** [comment]
I can test out a OC < 8 and see what's going on.

**Comment by DeepDiver1975** [comment]
> I can test out a OC < 8 and see what's going on.

That would really be awesome! THX a lot!

Just to repeat in case it got lost: From my pov this is either the missing LOCK support in 8.1 or some properties are not longer communicated to the client because of the changes in the area of the sabre dav upgrade

**Comment by rosslagerwall** [comment]
The permissions aren't there for owncloud < 8 either. I doubt they've ever worked... as you can see, the responses are the same for a PROPFIND:

8.0.0:
```
  <d:response>
    <d:href>/owncloud/remote.php/webdav/ownCloudUserManual.pdf</d:href>
    <d:propstat>
      <d:prop>
        <oc:id>00000010oc9so7n75w41</oc:id>
        <oc:permissions>RDNVW</oc:permissions>
        <d:getetag>"aec969e52b846734adb1ac724a8b319e"</d:getetag>
        <d:getcontentlength>1771241</d:getcontentlength>
        <d:getcontenttype>application/pdf</d:getcontenttype>
        <d:getlastmodified>Sat, 28 Feb 2015 18:42:40 GMT</d:getlastmodified>
        <d:resourcetype/>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
    <d:propstat>
      <d:prop>
        <d:creationdate/>
        <d:displayname/>
      </d:prop>
      <d:status>HTTP/1.1 404 Not Found</d:status>
    </d:propstat>
  </d:response>
```

7.0.1:
```
  <d:response>
    <d:href>/owncloud7/owncloud/remote.php/webdav/ownCloudUserManual.pdf</d:href>
    <d:propstat>
      <d:prop>
        <oc:id>00000005oc50b791e6a7</oc:id>
        <oc:permissions>RDNVW</oc:permissions>
        <d:getetag>"55bbb3230b232"</d:getetag>
        <d:getcontentlength>2250593</d:getcontentlength>
        <d:getcontenttype>application/pdf</d:getcontenttype>
        <d:getlastmodified>Fri, 31 Jul 2015 17:40:50 GMT</d:getlastmodified>
        <d:resourcetype/>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
    <d:propstat>
      <d:prop>
        <d:creationdate/>
        <d:displayname/>
      </d:prop>
      <d:status>HTTP/1.1 404 Not Found</d:status>
    </d:propstat>
  </d:response>
```

Apparently the OS X client requires LOCK support (see http://sabre.io/dav/clients/finder/) which is why @deangenovski finds everything read-only on OS X, but afaict it has nothing to do with permissions.

**Comment by DeepDiver1975** [comment]
> Apparently the OS X client requires LOCK support (see http://sabre.io/dav/clients/finder/) which is why @deangenovski finds everything read-only on OS X, but afaict it has nothing to do with permissions.

yes - this is a know issue

**Comment by DeepDiver1975** [comment]
> Just tried on OC 8.0.4 and the behavior is already present there when used with Ubuntu 14.04 webdav. When querying the permissions with the native Ubuntu GUI file browser I get a "The permissions of "xxxxx" could not be determined" (xxxxx = filename) instead of the permissions in the window. So this did not break in 8.1.

Oh I was miss interpreting this comment ..... :facepalm:

@rosslagerwall I'm so sorry to waste your time

**Comment by DeepDiver1975** [comment]
So my statement is: permissions where never there -> no bug -> won't fix

The OSX lock issue is handled in here https://github.com/owncloud/core/issues/17732

**Comment by rosslagerwall** [comment]
> @rosslagerwall I'm so sorry to waste your time

No problem :-)
