### ISSUE TITLE
ldap_read error after upgrading to OwnCloud 8.1

### ISSUE THREAD

**Issue by nismoryco** [owncloud/core#17570]
I have been having problems with ldap_read errors in my log after upgrade to 8.1.  I wasn't having any issues with ldap in 8.0.  I think this error is causing trouble with some of my users ability to login and sync with the server.  The ldap configuration says that my active directory config is OK, and it is able to find my users.

These are the messages from the log:
Error	PHP	ldap_read(): Search: Invalid DN syntax at /var/www/html/owncloud/apps/user_ldap/lib/ldap.php#257	2015-07-10T07:35:24-07:00
Error	PHP	Array to string conversion at /var/www/html/owncloud/lib/private/template/functions.php#36	2015-07-10T07:35:23-07:00
Error	PHP	ldap_read(): Search: Invalid DN syntax at /var/www/html/owncloud/apps/user_ldap/lib/ldap.php#257	2015-07-10T07:34:59-07:00
Error	PHP	Array to string conversion at /var/www/html/owncloud/lib/private/template/functions.php#36	2015-07-10T07:35:23-07:00
Error	PHP	ldap_read(): Search: Invalid DN syntax at /var/www/html/owncloud/apps/user_ldap/lib/ldap.php#257	2015-07-10T07:34:59-07:00
Error	PHP	ldap_read(): Search: Invalid DN syntax at /var/www/html/owncloud/apps/user_ldap/lib/ldap.php#257	2015-07-10T07:34:38-07:00
Error	PHP	ldap_read(): Search: Invalid DN syntax at /var/www/html/owncloud/apps/user_ldap/lib/ldap.php#257	2015-07-10T07:34:00-07:00

**Comment by karlitschek** [comment]
@blizzz any idea?

**Comment by blizzz** [comment]
@nismoryco could you please provide details to your bug report based on the issue template? https://raw.githubusercontent.com/owncloud/core/master/issue_template.md 

Thank you!

**Comment by nexusVI** [comment]
Had the same issue here after upgrading to 8.1. 

Saw corresponding message in slapd log: 
```<= bdb_equality_candidates: (memberOf) not indexed```

Fixed by setting: 
```./occ ldap:set-config "s01" useMemberOfToDetectMembership 0```

8.1 seems to use the "memberof" attribute by default, which is yet to be activated on our OpenLDAP setup.

**Comment by Xenopathic** [comment]
I had the same issue, and @nexusVI 's fix seems to have done the trick.

**Comment by blizzz** [comment]
Could you @nismoryco @nexusVI @Xenopathic check what is the output for `./occ ldap:show-config | grep hasMemberOfFilterSupport`? There is a check before `useMemberOfToDetectMembership` is checked and we are supposed to enter this one only if the server was detected to support memberOf.

**Comment by nexusVI** [comment]
```./occ ldap:show-config | grep hasMemberOfFilterSupport```
```| hasMemberOfFilterSupport      | 1                                                                             |```

This is easily explained, the MemberOf attribute _is_ basically available, but there is only one "groupOfNames" group for handling OwnCloud access, while the privileges inside OwnCloud have to be handled via existing POSIX groups (used for Samba etc.). Checking those via memberOf attribute is of course not possible.

**Comment by blizzz** [comment]
@nexusVI good point. Lines 388-392 should then be moved up into  the `if (is_array($groupDNs)) {` block, since an unsuccessful read attempt  would return false. This way, the backup method would still work, while the error message would continue to be logged.

**Comment by nexusVI** [comment]
@blizzz the proposed solution sounds viable. Is it possible to set the value for "useMemberOfToDetectMembership" in the WebGUI? That may be helpful.

**Comment by blizzz** [comment]
@nexusVI we can think about it for the next major release (8.2), but so far I don't see any urge. It's nasty that this bug appeared, but it's easy to fix. Then there is no immediate necessity to disable it (while of course it makes sense to do so in order to avoid useless traffic), so having the possibility to switch it on or off in console only is sufficient. Kind of like browser settings, you only have most common stuff in the config dialog, everything else is "hidden" in about:config (yes, it is not exactly the same but the principle is close).

**Comment by nismoryco** [comment]
### Steps to reproduce
Server configured to use LDAP

### Expected behaviour
No LDAP error messages in log

### Actual behaviour
Log messages with:
Error	PHP	ldap_read(): Search: Invalid DN syntax at /var/www/html/owncloud/apps/user_ldap/lib/ldap.php#257
Error	PHP	Array to string conversion at /var/www/html/owncloud/lib/private/template/functions.php#36

### Server configuration
**Operating system**: Ubuntu 14.04.2 LTS

**Web server:** Apache/2.4.12 (Ubuntu)

**Database:** 15.1 Distrib 10.0.20-MariaDB

**PHP version:** 5.5.26-1+deb.sury.org~trusty+1

**ownCloud version:** 8.1.0

**Updated from an older ownCloud or fresh install:** updated from 8.0.4

**List of activated apps:**

Enabled:
 - activity: 2.0.1
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.6
 - user_ldap: 0.6.1
Disabled:
 - encryption
 - external
 - files_encryption
 - files_external
 - user_external
 - user_webdavauth

**The content of config/config.php:**

$CONFIG = array (
  'instanceid' => 'ocmksfawy4wl',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => '',
  ),
  'datadirectory' => '/var/owncloud/data',
  'overwrite.cli.url' => '',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'mail_smtpmode' => 'php',
  'theme' => '',
  'maintenance' => false,
  'logtimezone' => 'America/Los_Angeles',
  'loglevel' => 1,
);

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** ActiveDirectory

#### LDAP configuration (delete this part if not used)

+-------------------------------+-------------------------------------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                                                     |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                       |
| hasPagedResultSupport         |                                                                                                                         |
| homeFolderNamingRule          |                                                                                                                         |
| lastJpegPhotoLookup           | 0                                                                                                                       |
| ldapAgentName                 | cn=owncloud,dc=blueh2o,dc=local                                                                                         |
| ldapAgentPassword             | ***                                                                                                                     |
| ldapAttributesForGroupSearch  |                                                                                                                         |
| ldapAttributesForUserSearch   |                                                                                                                         |
| ldapBackupHost                |                                                                                                              |
| ldapBackupPort                | 389                                                                                                                     |
| ldapBase                      | dc=blueh2o,dc=local                                                                                                     |
| ldapBaseGroups                | dc=blueh2o,dc=local                                                                                                     |
| ldapBaseUsers                 | dc=blueh2o,dc=local                                                                                                     |
| ldapCacheTTL                  | 600                                                                                                                     |
| ldapConfigurationActive       | 1                                                                                                                       |
| ldapEmailAttribute            | mail                                                                                                                    |
| ldapExperiencedAdmin          | 0                                                                                                                       |
| ldapExpertUUIDGroupAttr       |                                                                                                                         |
| ldapExpertUUIDUserAttr        |                                                                                                                         |
| ldapExpertUsernameAttr        |                                                                                                                         |
| ldapGroupDisplayName          | cn                                                                                                                      |
| ldapGroupFilter               | (|(cn=OwncloudUsers))                                                                                                   |
| ldapGroupFilterGroups         | OwncloudUsers                                                                                                           |
| ldapGroupFilterMode           | 0                                                                                                                       |
| ldapGroupFilterObjectclass    |                                                                                                                         |
| ldapGroupMemberAssocAttr      | member                                                                                                                  |
| ldapHost                      |                                                                                                              |
| ldapIgnoreNamingRules         |                                                                                                                         |
| ldapLoginFilter               | (&(&(|(objectclass=person))(|(memberof=CN=OwncloudUsers,OU=Security Groups,DC=blueh2o,DC=local)))(samaccountname=%uid)) |
| ldapLoginFilterAttributes     |                                                                                                                         |
| ldapLoginFilterEmail          | 0                                                                                                                       |
| ldapLoginFilterMode           | 0                                                                                                                       |
| ldapLoginFilterUsername       | 1                                                                                                                       |
| ldapNestedGroups              | 0                                                                                                                       |
| ldapNoCase                    | 1                                                                                                                       |
| ldapOverrideMainServer        |                                                                                                                         |
| ldapPagingSize                | 0                                                                                                                       |
| ldapPort                      | 389                                                                                                                     |
| ldapQuotaAttribute            |                                                                                                                         |
| ldapQuotaDefault              |                                                                                                                         |
| ldapTLS                       | 0                                                                                                                       |
| ldapUserDisplayName           | displayname                                                                                                             |
| ldapUserFilter                | (&(|(objectclass=person))(|(|(memberof=CN=OwncloudUsers,OU=Security Groups,DC=blueh2o,DC=local)(primaryGroupID=6277)))) |
| ldapUserFilterGroups          | OwncloudUsers                                                                                                           |
| ldapUserFilterMode            | 0                                                                                                                       |
| ldapUserFilterObjectclass     | person                                                                                                                  |
| ldapUuidGroupAttribute        | auto                                                                                                                    |
| ldapUuidUserAttribute         | auto                                                                                                                    |
| turnOffCertCheck              | 0                                                                                                                       |
| useMemberOfToDetectMembership | 1                                                                                                                       |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------+

### Logs
#### Web server error log

{"reqId":"MIXo3Nj0d+yMSsuY+K8Y","remoteAddr":"216.144.236.250","app":"PHP","message":"Array to string conversion at \/var\/www\/html\/owncloud\/lib\/private\/template\/functions.php#36","level":3,"time":"2015-07-11T23:52:10-07:00"}
{"reqId":"k9Dq92jW8Pyuam552zuq","remoteAddr":"216.144.236.250","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-07-11T23:52:13-07:00"}

#### ownCloud log (data/owncloud.log)
{"reqId":"01rlvPZUF\/oZD9lUXvBE","remoteAddr":"192.168.0.41","app":"PHP","message":"Array to string conversion at \/var\/www\/html\/owncloud\/lib\/private\/template\/functions.php#36","level":3,"time":"2015-07-13T16:01:58-07:00"}
{"reqId":"uF81zh57pi5vQvj0ZnRj","remoteAddr":"192.168.0.41","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-07-13T16:02:05-07:00"}

**Comment by nismoryco** [comment]
./occ ldap:show-config | grep hasMemberOfFilterSupport
| hasMemberOfFilterSupport | 1 |

**Comment by mzaian** [comment]
sudo -u www-data php occ ldap:show-config | grep hasMemberOfFilterSupport
| hasMemberOfFilterSupport      | 1     

Hello,

I just upgraded from 7.0.4 to 8.1 and i can see the error in my ownCloud log files :+1: 

"app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-07-29T08:57:27+00:00"}

I just need to know if its affecting my users or not? if not i will wait for the next proposed update but if its affecting i just need to know how to fix this.

**Comment by neopaws** [comment]
I don't understand how to fix this:

$ ./occ --version
ownCloud version 8.1.0

$ ./occ ldap:show-config | grep hasMemberOfFilterSupport
| hasMemberOfFilterSupport      | 1                                      |

$ ./occ ldap:set-config "s01" useMemberOfToDetectMembership 0
Invalid configID



my LDAP users cannot login,
Error	PHP	ldap_read(): Search: Invalid DN syntax at /var/www/owncloud/apps/user_ldap/lib/ldap.php#257

**Comment by nexusVI** [comment]
"s01" is probably not the correct configID for your setup. 

from docs:
```ldap:create-empty-config creates an empty LDAP configuration. The first one you create has no configID```

correct command could therefore be 
```./occ ldap:set-config "" useMemberOfToDetectMembership 0```
(just omit configID)

**Comment by mzaian** [comment]
nexusVI,

Does this work for me too?

**Comment by nexusVI** [comment]
@mzaian i am seeing the same messages in my log, even after setting the config value as demonstrated. there seems to be no impact, though - owncloud is working normally for my users.

**Comment by mzaian** [comment]
My users are working fine i'm afraid it has something to do with the groups and sharing function as well.

**Comment by nexusVI** [comment]
try setting the useMemberOfToDetectMembership value as suggested then. you can check slapd log before as well to be sure that this is the source of the problem, see my first post here.

**Comment by mzaian** [comment]
Actually i'm integrating my owncloud with M$ active directory.

**Comment by nexusVI** [comment]
i misread this.
as i am no owncloud dev, i'm afraid i can't answer that question. 

for me, no further problems arose from the specified error in the logfile.

**Comment by mzaian** [comment]
I will wait for an update from owncloud developers.

@PVince81 can you help us in this?

**Comment by PVince81** [comment]
@blizzz can you help ?

**Comment by neopaws** [comment]
@nexusVI 
$ ./occ ldap:set-config "" useMemberOfToDetectMembership 0

(nothing shows up)

$ ./occ ldap:show-config | grep hasMemberOfFilterSupport
| hasMemberOfFilterSupport      | 1   |

**Comment by nexusVI** [comment]
@neopaws the value you are checking is different from the value you are setting: 
```./occ ldap:show-config | grep useMemberOfToDetectMembership```

**Comment by neopaws** [comment]
@nexusVI 

$ ./occ ldap:show-config | grep useMemberOfToDetectMembership
| useMemberOfToDetectMembership | 0 |

Error	PHP	ldap_read(): Search: Invalid DN syntax at /var/www/owncloud/apps/user_ldap/lib/ldap.php#257

**Comment by nexusVI** [comment]
@neopaws I don't see your point exactly. Is this about the error message, which does not affect services in my case? I have no further information regarding that.  

If OwnCloud is still not working for you, there might be another problem in your case.

**Comment by blizzz** [comment]
@nismoryco @nexusVI @Xenopathic and everbody else seeing it: 

About

``Error PHP ldap_read(): Search: Invalid DN syntax``

You can safely ignore this for now.  It  is triggered by this line:

https://github.com/owncloud/core/blob/master/apps/user_ldap/ajax/testConfiguration.php#L52

I am looking into hiding the message. I found some other questions while looking at it, but that's fine so far.

To get rid off

`` Error PHP Array to string conversion at /var/www/html/owncloud/lib/private/template/functions.php#36 2015-07-10T07:35:23-07:00``

do as suggested by @nexusVI here https://github.com/owncloud/core/issues/17570#issuecomment-120916650
Adjust the s01 according to your configuration id. See output of ``./occ ldap:show-config``, e.g.

```
+-------------------------------+----------------------------------------------------+
| Configuration                 | s02                                                |
+-------------------------------+----------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                  |
| hasPagedResultSupport         |                                                    |
```

s02 here.  If there is nothing, use "" instead.

**Comment by Xenopathic** [comment]
@blizzz Either this needs fixing, or it needs added to the release notes for 8.2. cc @carlaschroder

**Comment by cmonteroluque** [comment]
release note, please

**Comment by carlaschroder** [comment]
Release note PR here, please review https://github.com/owncloud/documentation/pull/1701

**Comment by blizzz** [comment]
> @blizzz Either this needs fixing, or it needs added to the release notes for 8.2. cc @carlaschroder

Not critical, and Release Note is good info for now, still I be happier to fix it at some point to have it clean. Especially some smarter way of dealing with the memberOf-usage.

**Comment by cmonteroluque** [comment]
This issue will fall off 8.2 if not resolved by 6 Oct

**Comment by jasondickert** [comment]
For reference in 8.2 I still get the following even with useMemberOfToDetectMembership set to 0:
Error	PHP	array_slice() expects parameter 1 to be array, object given at /var/www/html/owncloud/apps/user_ldap/group_ldap.php#530	2015-10-20T20:35:25+00:00
Error	PHP	array_slice() expects parameter 1 to be array, object given at /var/www/html/owncloud/apps/user_ldap/group_ldap.php#530	2015-10-20T20:35:16+00:00
Error	PHP	array_slice() expects parameter 1 to be array, object given at /var/www/html/owncloud/apps/user_ldap/group_ldap.php#530	2015-10-20T20:35:15+00:00
Error	PHP	array_slice() expects parameter 1 to be array, object given at /var/www/html/owncloud/apps/user_ldap/group_ldap.php#530	2015-10-20T20:35:10+00:00
Error	PHP	ldap_read(): Search: Invalid DN syntax at /var/www/html/owncloud/apps/user_ldap/lib/ldap.php#257	2015-10-20T19:53:37+00:00
Error	PHP	Array to string conversion at /var/www/html/owncloud/lib/private/template/functions.php#36	2015-10-20T19:53:35+00:00
Error	PHP	ldap_read(): Search: Invalid DN syntax at /var/www/html/owncloud/apps/user_ldap/lib/ldap.php#257

**Comment by blizzz** [comment]
@jasondickert unrelated, different issue. Open a new bug report (using the issue template), please.

**Comment by Und3rWorld** [comment]
i have the same problems, but in my case, the LDAP no write anything in config.php. And no user can login. some help

**Comment by blizzz** [comment]
@Und3rWorld Github is not a support platform, but our code repository and issue tracker. Please read the [LDAP documentation](https://doc.owncloud.org/server/8.2/admin_manual/configuration_user/user_auth_ldap.html), if you are still not lucky try the [Forums](https://forum.owncloud.org/) or [User Mailinglist](https://mailman.owncloud.org/pipermail/user/) for further help.
