### ISSUE TITLE
Encryption: recover from a broken migration to ownCloud 8.1

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#17574]
Because it become a real mess to find all the necessary steps to recover from a broken migration I decided to summarize it in a separate issue. This will be closed as soon as 8.1.1 is released.

Unfortunately the migration from ownCloud 8.0 to ownCloud 8.1.0 with encryption contain some bugs which break the migration. But no data are lost, you just need to perform some extra steps and re-run the migration. If you didn't updated yet I would suggest to wait for ownCloud 8.1.1 at the end of this month which will contain all the necessary fixes. If you already tried the migration and it failed I recommend following steps to recover your installation:

Make sure to read the ownCloud documentation about encryption, especially this part: https://doc.owncloud.org/server/8.1/admin_manual/configuration_files/encryption_configuration.html?highlight=encryption#upgrading-from-owncloud-8-0

1. Make a backup from your data folder

2. before ownCloud migrate your keys from the old encryption to the new one it creates a backup of your old keys. Restore this backups. The backups are located in ````/data```` and in ````data/<user>````. Each backup is called ````files_encryption_backup_<timestamp>````. In case you tried to run the migration multiple time you will have more then one backup per folder. Make sure to always pick the oldest one (the backup which was created during your first try). Remove the ````data/files_encryption```` folder and copy the ````data/files_encryption_backup_<timestamp>/files_encryption```` folder to ````data/files_encryption````.  For each user remove the ````data/<user>/files_encryption```` folder and copy the content of ````data/<user>/files_encryption_backup_<timestamp>/```` to ````data/<user>/files_encryption/````. 

3. Now you need to apply some patches to fix the issues. The easiest way is to just copy some files:

   - https://raw.githubusercontent.com/owncloud/core/enc_quick_fix_8.1/apps/encryption/lib/keymanager.php to apps/encryption/lib/keymanager.php
   - https://raw.githubusercontent.com/owncloud/core/enc_quick_fix_8.1/apps/encryption/lib/migration.php to apps/encryption/lib/migration.php
   - https://raw.githubusercontent.com/owncloud/core/enc_quick_fix_8.1/apps/files_trashbin/lib/storage.php to apps/files_trashbin/lib/storage.php
  - https://raw.githubusercontent.com/owncloud/core/enc_quick_fix_8.1/lib/private/files/storage/wrapper/encryption.php to lib/private/files/storage/wrapper/encryption.php
  - https://raw.githubusercontent.com/owncloud/core/enc_quick_fix_8.1/settings/controller/encryptioncontroller.php to settings/controller/encryptioncontroller.php
  - https://raw.githubusercontent.com/owncloud/core/enc_quick_fix_8.1/apps/encryption/command/migratekeys.php to apps/encryption/command/migratekeys.php

4. after that you can try to run the migration again: ./occ encryption:migrate. This time it should finish without an error and after you login again you should be able to access your files

**Comment by MorrisJobke** [comment]
> This will be closed as soon as 8.1.1 is released.

8.1.1 is out -> close
