### ISSUE TITLE
S3 and 8.1 upgrade with “Download Broker”?

### ISSUE THREAD

**Issue by stevespaw** [owncloud/core#17576]
We recently upgraded from 7.x to 8.1 and it was fairly smooth.

We have OwnCloud on EC2 and use S3 as our "external" storage (it is our only storage). It has been working OK for a year, upload and download performance was an issue but usable. We have 1000's of large files, 4-16 GB. The pinch point of all files going through the EC2 first and then to S3 has been a bottleneck.

Now with 8.1 everything is slower. :-) and existing folders read "pending", but work.

We upgraded because of the allure of this feature which we thought is exactly what we needed:

"Download Broker Improves Performance¶ When ownCloud delivers universal file access to end users, files from many different document sources are aggregated into a single interface and served to end users. In some cases, passing all of the files aggregated in this interface through a single server, ownCloud, slows down data access. ownCloud now supports direct downloads of files from select storage back-ends, reducing the load on the ownCloud server without sacrificing control over the files that are stored in the various back end systems."

I cannot find any information about this feature and how we can use it.

The holy grail for us is to allow power users on our system to use s3 directly for storage and have those files sync with OwnCloud for the technically challenged clients we have that need to download some of these files and send some to us. We were hoping that 8.1 would get us closer.

Where are we going wrong and what should we expect?

Thanks a lot for any insight. Steve

**Comment by karlitschek** [comment]
Thanks for your question. I'm not sure this is really an ownCloud bug. So the bugtracker is the wrong place to ask this questions. Please post it at forum.owncloud.org.  Thanks a lot.

**Comment by RealRancor** [comment]
@karlitschek Please direct such questions to the mailinglist as we don't have any knowledge about such oC changes at the forums.

**Comment by karlitschek** [comment]
@RealRancor Good point. Will do. :-)
