### ISSUE TITLE
update 8.0.2 to 8.1.0 binary log issue

### ISSUE THREAD

**Issue by plReynaerde** [owncloud/core#17577]
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing ' DELETE FROM `oc_lucene_status` WHERE `fileid` IN ( SELECT `fileid` FROM ( SELECT `fileid` FROM `oc_lucene_status` GROUP BY `fileid` HAVING count(`fileid`) > 1 ) AS `mysqlerr1093hack` )': SQLSTATE[HY000]: General error: 1665 Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at least one table uses a storage engine limited to row-based logging. InnoDB is limited to row-logging when transaction isolation level is READ COMMITTED or READ UNCOMMITTED.

**Comment by RealRancor** [comment]
Documented here: https://doc.owncloud.org/server/8.0/admin_manual/maintenance/upgrade.html#troubleshooting

There are also tons of duplicated reported here, should be easy to find.
