### ISSUE TITLE
cron.php won't run after update to 8.1 ("another instance is already running")

### ISSUE THREAD

**Issue by tribut** [owncloud/core#17578]
Updated my owncloud from 8.0.4 to 8.1.0 yesterday. Since then, cron.php always fails with

    Another instance of cron.php is still running!

I've added `$lockFile` and `$isLocked` to the output and the file does not exist (creating it with `touch /tmp/owncloud-server-XXX-cron.lock` does not change behavior) and `$isLocked === false`. A simple test script, that just opens `/tmp/testfile` and locks it works (flock returns true). The error persists through restarts.
Is this a known problem? Any idea for a fix?

Running on Debian jessie. `php --version` says:

    PHP 5.6.9-0+deb8u1 (cli) (built: Jun  5 2015 11:03:27) 
    Copyright (c) 1997-2015 The PHP Group
    Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
        with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies

**Comment by jsalatiel** [comment]
My problem was an wrong memcache configuration.

**Comment by tribut** [comment]
After some more research I found the culprit: If `cron.lockfile.location` is unset, the return value of `sys_get_temp_dir()` is used, which default to `/tmp` and is outside of the `open_basedir` setting.
I've now added `sys_temp_dir` (which is new as of php 5.5) to php.ini to resolve this.
Sorry for not figuring that out before opening a bug report.
