### ISSUE TITLE
Owncloud says it has no internet connection?

### ISSUE THREAD

**Issue by frozen1980** [owncloud/core#17571]
### Steps to reproduce
1. Unknown, I just upgraded to OC 8.1

### Expected behaviour
Show no error and be able to install apps

### Actual behaviour
I see an error message in the Admin-Page stating owncloud has no internet connection.
Also I can't install apps, I just get "cURL error 56: Proxy CONNECT aborted" but I do not use any proxy. I downloaded and installed my needed apps manually..
Using test.php from https://github.com/owncloud/core/issues/16255#issuecomment-112481294 I get 200 and 301 and since I am not on Fedora / CentOS I am probably not affected by issue  #16255

### Server configuration
**Operating system**: Debian stable (8.1)

**Web server:** Apache/2.4.10

**Database:** mysql  Ver 14.14 Distrib 5.5.43

**PHP version:** PHP 5.6.9-0+deb8u1

**ownCloud version:** ownCloud 8.1.0 (stable) 

**Updated from an older ownCloud or fresh install:** Update from 8.0.4
Enabled:
 - activity: 2.0.1
 - bookmarks: 0.4
 - calendar: 0.7.1
 - contacts: 0.4.0.0
 - files: 1.1.9
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - gallery: 0.6.0

Disabled:
 - encryption
 - external
 - files_external
 - files_locking
 - files_videoviewer
 - firstrunwizard
 - provisioning_api
 - templateeditor
 - updater
 - user_external
 - user_ldap
 - user_webdavauth

**The content of config/config.php:**
define('DEBUG',true);
$CONFIG = array (
  'installed' => true,
  'dbtype' => 'mysql',
  'dbname' => 'ownclouddb',
  'dbuser' => 'owncloud',
  'dbpassword' => 'removed',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'passwordsalt' => 'removed',
  'forcessl' => true,
  'blacklisted_files' =>
  array (
    0 => '.htaccess',
  ),
  'overwritehost' => '',
  'overwriteprotocol' => '',
  'overwritewebroot' => '',
  'overwritecondaddr' => '',
  'proxy' => '',
  'proxyuserpwd' => '',
  'theme' => '',
  'default_language' => 'de',
  '3rdpartyroot' => '',
  '3rdpartyurl' => '',
  'defaultapp' => 'files',
  'knowledgebaseenabled' => true,
  'knowledgebaseurl' => 'http://api.apps.owncloud.com/v1',
  'appstoreenabled' => true,
  'appstoreurl' => 'http://api.apps.owncloud.com/v1',
  'mail_smtpdebug' => false,
  'mail_smtpmode' => 'php',
  'mail_smtphost' => '127.0.0.1',
  'mail_smtpport' => '25',
  'mail_smtptimeout' => 10,
  'mail_smtpauthtype' => 'LOGIN',
  'trashbin_retention_obligation' => 180,
  'allow_user_to_change_display_name' => true,
  'appcodechecker' => '',
  'updatechecker' => true,
  'log_type' => 'owncloud',
  'logfile' => '',
  'loglevel' => 0,
  'remember_login_cookie_lifetime' => 1296000,
  'session_lifetime' => 86400,
  'custom_csp_policy' => 'default-src \'self\'; script-src \'self\' \'unsafe-eval\'; style-src \'self\' \'unsafe-inline\'; frame-src *; img-src *; font-src \'self\' data:; media-src *',
  'xframe_restriction' => true,
  'maintenance' => false,
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/var/www/server/owncloud/apps',
      'url' => '/apps',
      'writable' => true,
    ),
  ),
  'customclient_desktop' => '',
  'customclient_android' => '',
  'customclient_ios' => '',
  'logdateformat' => 'F d, Y H:i:s',
  'logtimezone' => 'Europe/Berlin',
  'instanceid' => 'removed',
  'version' => '8.1.0.8',
  'trusted_domains' =>
  array (
    0 => 'www.mydomain.de',
  ),
  'mail_from_address' => 'webmaster',
  'mail_domain' => 'mydomain.de',
  'secret' => 'removed',
  'singleuser' => false,
  'memcache.local' => '\OC\Memcache\APCu',
);

**Are you using external storage, if yes which one:** none

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** none

### Client configuration
**Browser:** Several

**Operating system:** Several

#### Web server error log
Nothing interesting

#### ownCloud log (data/owncloud.log)
{"reqId":"++8tJ+CD+qfRclQdF7m7","remoteAddr":"93.130.229.15","app":"core","message":"No update found at the ownCloud appstore for app 166056","level":1,"time":"July 10, 2015 17:02:59","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"++8tJ+CD+qfRclQdF7m7","remoteAddr":"93.130.229.15","app":"core","message":"No update found at the ownCloud appstore for app 166051","level":1,"time":"July 10, 2015 17:02:59","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"++8tJ+CD+qfRclQdF7m7","remoteAddr":"93.130.229.15","app":"core","message":"No update found at the ownCloud appstore for app 166049","level":1,"time":"July 10, 2015 17:02:59","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"iqvOjfVr01MMlcbDUsnC","remoteAddr":"93.130.229.15","app":"core","message":"cURL error 56: Proxy CONNECT aborted","level":3,"time":"July 10, 2015 17:03:18","method":"POST","url":"\/owncloud\/index.php\/settings\/ajax\/enableapp.php"}
{"reqId":"NYRh4Js+uZw3IJnT6gKG","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/var\/www\/server\/owncloud\/apps\/contacts\/appinfo\/app.php#35","level":0,"time":"July 10, 2015 17:09:16","method":"--","url":"--"}
{"reqId":"Q6cKpVI8hh+55HGSDKnL","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/var\/www\/server\/owncloud\/apps\/contacts\/appinfo\/app.php#35","level":0,"time":"July 10, 2015 17:09:45","method":"--","url":"--"}
{"reqId":"t00nFR9KyIBU3c0zIbFu","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/var\/www\/server\/owncloud\/apps\/contacts\/appinfo\/app.php#35","level":0,"time":"July 10, 2015 17:10:05","method":"--","url":"--"}
{"reqId":"rAflbGKd1h3FB+BTASnL","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/var\/www\/server\/owncloud\/apps\/contacts\/appinfo\/app.php#35","level":0,"time":"July 10, 2015 17:10:09","method":"--","url":"--"}
{"reqId":"E6ZKEHG6bcqIWKcG8P\/V","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/var\/www\/server\/owncloud\/apps\/contacts\/appinfo\/app.php#35","level":0,"time":"July 10, 2015 17:10:11","method":"--","url":"--"}
{"reqId":"7zSXkcQTVyWUqa8TzTtE","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/var\/www\/server\/owncloud\/apps\/contacts\/appinfo\/app.php#35","level":0,"time":"July 10, 2015 17:10:14","method":"--","url":"--"}

**Comment by rullzer** [comment]
Did you just copy the config sample file and modify it? Because we had that issue before... (CC: @DeepDiver1975 @LukasReschke , do you remember that as well?)

Try to remove the proxy related stuff
> 'proxy' => '',
> 'proxyuserpwd' => '',

**Comment by frozen1980** [comment]
I can't remember doing such a thing, but it's an old installation, updated all the way from at least 5.0.13.. 

Thanks for that hint, this did solve the problem.. Sometimes one seems to be blind.. :-)

Now calendar and contacts seem to be experimental which seems weird, but this is an entirely different thing.

Thank you very much!
