### ISSUE TITLE
Update from 8.0.4 to 8.1.0 on debian based installation from repository failed

### ISSUE THREAD

**Issue by mrm2m** [owncloud/core#17582]
After starting the update process on the root web page I get this result:

* It starts maintenance mode
* it checks the dabase scheme update
* it checks the dabase scheme update for APPs
* It fails with this message:

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'DROP INDEX category_object_index': SQLSTATE[42704]: Undefined object: 7 ERROR: index "category_object_index" does not exist

**Comment by RealRancor** [comment]
Hi,

try to first go to oC 8.0.5 as described in the upgrade manuals.

**Comment by mrm2m** [comment]
I was wrong with the old version - it was 8.0.4. So first I wanted to check if that still works. So I removed all owncloud packages with aptitude. Next thing I did was to install the old packages from the cache: 

dpkg -i /var/cache/apt/archives/owncloud*8.0.4*.deb
service apache2 reload

After that I have a at least a working 8.0.4 again. I will make a backup and then I'll give 8.0.5 a try. So probably there's no good in using the APT packages from http://download.opensuse.org/repositories/isv:/ownCloud:/community/Debian_8.0/all/.

**Comment by mrm2m** [comment]
Which manuals do you mean? I found that one: https://doc.owncloud.org/server/8.1/admin_manual/maintenance/upgrade.html

There 8.0.5 is just an example for what intermediate releases are. There is no explicit suggestion what version you should have before updating to 8.1.0. 

I did exactly what the manual says about updating your debian installation with the packet manager, because that's how you update your debian: https://doc.owncloud.org/server/8.1/admin_manual/maintenance/upgrade.html#upgrading-with-your-linux-package-manager

**Comment by RealRancor** [comment]
Hi,

its described in your first link:

> install all point releases and major releases without skipping any of them, as skipping releases increases the risk of errors. Major releases are 6.0, 7.0, and 8.0, and point releases are intermediate releases for each major release. For example, 8.0.1 and 8.0.2 are point releases.

**Comment by mrm2m** [comment]
Well - there are point releases, major releases and intermediate releases? OK.

I think this is probably not related to the update process at all:
```Shell
root@osmc:/var/www# mv owncloud/ owncloud.bak
root@osmc:/var/www# wget https://download.owncloud.org/community/owncloud-8.0.5.tar.bz2
root@osmc:/var/www# tar xf owncloud-8.0.5.tar.bz2 
root@osmc:/var/www# cp -a owncloud.bak/config/config.php owncloud/config/
root@osmc:/var/www# cp -a owncloud.bak/data/ owncloud/
root@osmc:/var/www/owncloud# sudo -u www-data php occ upgrade
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
An exception occurred while executing 'DROP INDEX category_object_index':

SQLSTATE[42704]: Undefined object: 7 ERROR:  index "category_object_index" does not exist
Turned off maintenance mode
Update failed
```
I would say there's something wrong with the database. So what is that category_object_index?

**Comment by RealRancor** [comment]
Strange thing. The index category_object_index is defined here:

https://github.com/owncloud/core/blob/v8.1.0/db_structure.xml#L1076

**Comment by mrm2m** [comment]
Here is everything that I have in my database backup about the table in question: 
```SQL
--
-- Name: oc_vcategory_to_object; Type: TABLE; Schema: public; Owner: ocdb; Tablespace: 
--

CREATE TABLE oc_vcategory_to_object (
    objid integer DEFAULT 0 NOT NULL,
    categoryid integer DEFAULT 0 NOT NULL,
    type text NOT NULL
);


ALTER TABLE oc_vcategory_to_object OWNER TO ocdb;
```

**Comment by mrm2m** [comment]
I tried to create the missing index. I even tried to remove it with the SQL statement from the error message:
```SQL
ocdb=> CREATE UNIQUE INDEX category_object_index 
             ON oc_vcategory_to_object 
             USING btree (categoryid, objid, type);
CREATE INDEX
ocdb=> DROP INDEX category_object_index;
DROP INDEX
ocdb=> DROP INDEX category_object_index;
ERROR:  index "category_object_index" does not exist
ocdb=> CREATE UNIQUE INDEX category_object_index 
             ON oc_vcategory_to_object 
             USING btree (categoryid, objid, type);
CREATE INDEX
```
But still the error message remains if I run the upgrade script.

**Comment by gbmaster** [comment]
I'm having this same issue while upgrading from 8.1.0 to 8.1.1. Any idea on how to solve this?

**Comment by genofire** [comment]
Update to 8.2.2.2 same problem (on enabling calendar again).
I created the index manuelle like mrm2m and the problem still exists.
(It mean that there is no index, but i could delete it manuelle afterwarts)

**Comment by PVince81** [comment]
Any more luck with 8.2.6 ?

CC @DeepDiver1975 @georgehrke
