### ISSUE TITLE
Update to 8.1 failure / could not fetch app info

### ISSUE THREAD

**Issue by shiznix** [owncloud/core#17587]
Updating ownCloud to version 8.1.0, this may take a while.

Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Updated "updater" to 0.6
Updated "files_sharing" to 0.6.2
Updated "files_trashbin" to 0.6.3
Updated "files_versions" to 1.0.6
Exception: Could not fetch app info!
The update was unsuccessful. Please report this issue to the ownCloud community.

**Comment by RealRancor** [comment]
Please use the issue template as asked here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version

**Comment by MorrisJobke** [comment]
@shiznix Of special interest is the owncloud log in this case. It will most like hold the info what exception occured.

**Comment by shiznix** [comment]
Here is the offending log message -> https://gist.github.com/shiznix/50c69892af57ac897dda

Hope it helps.

**Comment by MorrisJobke** [comment]
Fixing PR: #17606 @shiznix Please test :)

**Comment by MorrisJobke** [comment]
@shiznix Thanks for the report :)
