### ISSUE TITLE
Upgrading to 8.1 breaks Android client upload / Sabre HEAD request

### ISSUE THREAD

**Issue by tohojo** [owncloud/core#17586]
The Android client refused to upload anything after upgrading to Owncloud 8.1.

Tracked it down to an issue with HEAD requests in WebDav. See https://github.com/fruux/sabre-dav/issues/684 for the upstream issue.

**Comment by Jockelchen** [comment]
Did u update the client to the newest version? That fixed it for me :). https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client

**Comment by PVince81** [comment]
I just tried uploading with the official Android app 1.7.2 against my ownCloud 8.1 server and uploading worked fine. I did so by selecting pictures in the Photos app and sharing them through ownCloud, and selected an upload directory. The pictures were uploaded properly.

Maybe this is somehow related to some environments/configs ?

**Comment by PVince81** [comment]
@tohojo mind sharing details about your setup ? Is there anything like a reverse proxy or anything that could affect HEAD requests in your environment ?

**Comment by mhzawadi** [comment]
Hi @PVince81 I have this same issue, first is the owncloud log then the nginx log.

{"reqId":"YU4CEgasn65Ynu2ss+Fq","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/mnt\/data1\/var\/data\/websites\/3rd_party\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at \/mnt\/data1\/var\/data\/websites\/3rd_party\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#58","level":3,"time":"2015-07-12T11:24:16+00:00"}
{"reqId":"JpGJ09YOfWUH+LTBzjIK","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/mnt\/data1\/var\/data\/websites\/3rd_party\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at \/mnt\/data1\/var\/data\/websites\/3rd_party\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#58","level":3,"time":"2015-07-13T11:21:27+00:00"}


xxx.xxx.xxx.xxx - username [12/Jul/2015:11:24:19 +0000] "HEAD /remote.php/webdav/photos/HTC/IMAG0431%20(2).jpg HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/1.7.2"

xxx.xxx.xxx.xxx - username [13/Jul/2015:11:21:29 +0000] "HEAD /remote.php/webdav/photos/IMAG0434.jpg HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/1.7.2"
xxx.xxx.xxx.xxx - username [13/Jul/2015:11:21:30 +0000] "HEAD /remote.php/webdav/photos/IMAG0434%20(2).jpg HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/1.7.2"
nginx/1.8.0
PHP 5.4.41-0+deb7u1 (fpm-fcgi) with XCache v2.0.0
ownCloud 8.1.0 with 'memcache.local' => '\OC\Memcache\XCache' & 'memcache.distributed' => '\OC\Memcache\Memcached',
ownCloud-android/1.7.2 on HTC M8 android 5.0.1

**Comment by PVince81** [comment]
@tohojo do you also have nginx ?

I have Apache 2.4. Maybe it's nginx specific.

**Comment by tohojo** [comment]
Vincent Petry <notifications@github.com> writes:

> @tohojo do you also have nginx ?
>
> I have Apache 2.4. Maybe it's nginx specific.

Yep, I'm on nginx+uwsgi :)

-Toke

**Comment by DemoFreak** [comment]
I experience the same problem since upgrade from 8.0.5 to 8.1

Setup: Apache2, PHP5.6.1
Android: FolderSync

owncloud.log shows lines like this:
{"reqId":"8TQApoEgllyAALc+vilM","remoteAddr":"x.x.x.x","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Cod
e\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/clients\\\/client4\\\/web27\\\/web\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(149): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasi
c->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#1 \\\/srv\\\/www\\\/clients\\\/client4\\\/web27\\\/web\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.p
hp(122): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#2 \\\/srv\\\/www\\\/clients\\\/client4\\\/web27\\\/web\\\/3rdparty\\\/sa
bre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#3 [internal function
]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/srv\\\/www\\\/clients\\\/client4\\\/web27\\\/web\\\/3
rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/srv\\\/www\\\/clients\\\/client4\\\/web27\\\/web\\\/3rdparty\\\/sabre\\
\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/srv\\\/www\\\/clients\\\/client4\\\/web27\\\/web\\\/3rdparty\\\/sabre\
\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/srv\\\/www\\\/clients\\\/client4\\\/web27\\\/web\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/srv\\\/www\\\/clients\\\/client4\\\/web27\\\/web\\\/remote.php(132): require_once('\\\/srv\\\/www\\\/client...')\\n#9 {main}\",\"File\":\"\\\/srv\\\/www\\\/clients\\\/client4\\\/web27\\\/web\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2015-07-13T20:15:28+00:00","method":"PUT","url":"\/remote.php\/webdav\/Documents\/stopperstek-2.pdf"}

Apache error.log shows:
x.x.x.x - - [13/Jul/2015:22:15:27 +0200] "PUT /remote.php/webdav/Documents/stopperstek-2.pdf HTTP/1.1" 403 1103 "-" "android-cloud-api - Android 4.4.4"

**Comment by wvandelli** [comment]
I think I have the same problem here. My configuration includes:

* Owncloud server 1.8.1, Android client 1.7.1
* nginx+uwsgi behind a nginx proxy

nginx access.log:
127.0.0.1 - username [15/Jul/2015:11:57:43 +0200] "HEAD /owncloud/remote.php/webdav/archive/saleve/ HTTP/1.1" 502 0 "-" "Mozilla/5.0 (Android) ownCloud-android/1.7.1"


nginx error.log:
2015/07/15 11:57:43 [error] 18067#0: *54811 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: servername, request: "HEAD /owncloud/remote.php/webdav/archive/saleve/ HTTP/1.1", upstream: "uwsgi://unix:///run/uwsgi/owncloud.sock:", host: "webname"


uwsgi:
Jul 15 11:57:43 servername uwsgi[280]: [pid: 7293|app: -1|req: -1/9170] 127.0.0.1 () {38 vars in 607 bytes} [Wed Jul 15 11:57:43 2015] HEAD /owncloud/remote.php/webdav/archive/saleve/ => generated 0 bytes in 191 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)

**Comment by tohojo** [comment]
Maybe the reason it only breaks on nginx is that it turns the 500 into a 502 that the client doesn't recognise?

**Comment by DemoFreak** [comment]
@tohojo 
It don't only break on Nginx. In my setup it breaks with Apache too.

**Comment by tohojo** [comment]
Ah, my bad, missed that.

**Comment by DemoFreak** [comment]
Any news in that?
Which further info do you need? I'm willing to help in any manner... ;-)

/Hannes

**Comment by magicmyth** [comment]
My Android uploads were broken as well with the upgrade to 8.1. I had been running Owncloud using NGINX+UWSGI under Arch Linux based on the Arch Linux Owncloud manual:
https://wiki.archlinux.org/index.php/OwnCloud#Nginx_.2B_uwsgi_php_configuration
I've switched it over to using PHP FPM and my Android client uploads are working once again. Is everybody with the issue using UWSGI for PHP?

**Comment by mhzawadi** [comment]
Hi @magicmyth 
I run nginx+FPM and still cant get the uploads to work, but I didnt get your error.
Could you post your config to see if there is anything that might help?

**Comment by magicmyth** [comment]
Hi @mhzawadi 

This is the part of my NGINX config that handles my owncloud site:
```
upstream php-handler {
  #server 127.0.0.1:9000;
  server unix:/run/php-fpm/php-fpm.sock;
}

server {
  server_name domain.com;
  listen 80;
  listen 443 ssl;

  ssl_certificate     /etc/ssl/domain.com.crt;
  ssl_certificate_key /etc/ssl/server.key;

  # Add headers to serve security related headers
  add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;";
  add_header X-Content-Type-Options nosniff;
  add_header X-Frame-Options "SAMEORIGIN";
  add_header X-XSS-Protection "1; mode=block";
  add_header X-Robots-Tag none;

  # Path to the root of your installation
  root /usr/share/webapps/owncloud/;
  # set max upload size
  client_max_body_size 10G;
  fastcgi_buffers 64 4K;

  # Disable gzip to avoid the removal of the ETag header
  gzip off;

  # Uncomment if your server is build with the ngx_pagespeed module
  # This module is currently not supported.
  #pagespeed off;

  rewrite ^/caldav(.*)$ /remote.php/caldav$1 redirect;
  rewrite ^/carddav(.*)$ /remote.php/carddav$1 redirect;
  rewrite ^/webdav(.*)$ /remote.php/webdav$1 redirect;

  index index.php;
  error_page 403 /core/templates/403.php;
  error_page 404 /core/templates/404.php;

  location = /robots.txt {
    allow all;
    log_not_found off;
    access_log off;
  }

  location ~ ^/(?:\.htaccess|data|config|db_structure\.xml|README){
    deny all;
  }

  # Custom writable apps folder.
  location /wapps {
    alias /var/www/owncloud/apps;
  }

  location / {
    # The following 2 rules are only needed with webfinger
    rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
    rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json last;

    rewrite ^/.well-known/carddav /remote.php/carddav/ redirect;
    rewrite ^/.well-known/caldav /remote.php/caldav/ redirect;

    rewrite ^(/core/doc/[^\/]+/)$ $1/index.html;

    try_files $uri $uri/ /index.php;
  }

  location ~ \.php(?:$|/) {
    #root /usr/share/webapps/owncloud/;
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    #fastcgi_pass unix:/run/php-fpm/php-fpm.sock;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PATH_INFO $fastcgi_path_info;
    fastcgi_param HTTPS on;
    fastcgi_param modHeadersAvailable true; #Avoid sending the security headers twice
    fastcgi_pass php-handler;
  }

   # Optional: set long EXPIRES header on static assets
   # @todo This breaks the 'wapps' alias. Need to figure out how to make
   # them work together.
   #location ~* \.(?:jpg|jpeg|gif|bmp|ico|png|css|js|swf)$ {
   #  expires 30d;
   #  # Optional: Don't log access to assets
   #  access_log off;
   #}

}
```

My PHP-FPM config is the default config with the following changes to the pool:
```
; Environment variables needed for OwnCloud
env[HOSTNAME] = $HOSTNAME
env[PATH] = /usr/local/bin:/usr/bin:/bin
env[TMP] = /tmp
env[TMPDIR] = /tmp
env[TEMP] = /tmp

; Directory access
php_admin_value[open_basedir] = /my/owncloud/data/:/tmp/:/usr/share/pear/:/usr/share/webapps/owncloud/:/etc/webapps/owncloud:/var/www/owncloud/apps/:/dev/urandom
```

I hope that helps?

**Comment by mhzawadi** [comment]
Good afternoon,

I have got my setup working, I started by adding the gzip off setting, then the modHeadersAvailable. But nether made any difference, so I added all the add_headers from @magicmyth and I now have uploads working :)

**Comment by wvandelli** [comment]
Hello,

still no luck for me. I believe I have the same settings reported by @magicmyth and @mhzawadi, but with uWSGI. Maybe the latter has an effect as well.

Wainer

**Comment by boltronics** [comment]
I had this (Apache 2.4 with mod_php). I just "solved" it by making two changes to my setup. I don't know which one made the difference.

First, I installed Redis and got file locking working. Second was to get xcache running for local cache. Now my ownCloud photos auto-upload again.

**Comment by PVince81** [comment]
@josh4trunks can you help with these nginx issues ?

**Comment by josh4trunks** [comment]
Just to be clear, who is still having upload issues? From reading through it looks like @tohojo @DemoFreak and @wvandelli 

If you are having issues please post..
* webserver + php backend (i.e. nginx + uwsgi)
* nginx config
* nginx error message

**Comment by teemu-torma** [comment]
I am using nginx+uwsgi and I do get same error messages as @wvandelli on July 15 comment - uwsgi generates 500 error with 0 bytes and nginx turns that into 502 error, nothing on owncloud.log.  This happens with both foldersync and owncloud client on android.  The config is pretty much the same as has been posted here before.

Linux clients work just fine.  ownCloud desktop sync works fine both ways, and mounting the ownCloud files with webdav also works both ways.

**Comment by josh4trunks** [comment]
@teemu-torma the only nginx config I see is the one here https://github.com/owncloud/core/issues/17586#issuecomment-128646401, which is said to be working. Should I assume this is your config and it doesn't work with uwsgi?

**Comment by DemoFreak** [comment]
@josh4trunks 

Apache 2.4.12
PHP 5.6.10
PHP as Fast-CGI (mod_fcgid)

Error messages see some posts above. ;-)

**Comment by teemu-torma** [comment]
@josh4trunks sorry, that's for fastcgi, I am using something like in https://gist.github.com/gdamjan/e98672fe86b7a11e0520

At least what I can tell, it is only Android client uploads that are broken, download works and Linux clients work both ways.

**Comment by josh4trunks** [comment]
@teemu-torma not sure why that config wouldn't work with uwsgi. I use nginx+php-fpm personally and didn't have any problems with the upgrade from 8.0.5 > 8.1.1

An unrelated notie, the config you linked matches and captures the script_name and path_info. This is better done with "fastcgi_split_path_info" as seen in the owncloud docs
https://doc.owncloud.org/server/8.1/admin_manual/installation/nginx_configuration.html

**Comment by wvandelli** [comment]
Hi @josh4trunks,

   thanks for looking into this. I will try to post my configuration files later. In the meanwhile I have another piece of information I wanted to share.

I seem to fail uploading files only from the Owncloud Android client. On the other hand, on the same phone, I also use MyOwnNotes (https://github.com/aykit/MyOwnNotes) as well as the calendar via DAVdroid (https://github.com/bitfireAT/davdroid) with no problems. Especially with the former, I can create new files, which to me, naively, corresponds to a file upload operation.

Cheers
         Wainer

**Comment by josh4trunks** [comment]
@wvaandelli I bet myownnotes talks to ownnotes with an api, not directly by uploading files. in this case, it is irrelevant to the issue being discussed.

**Comment by simonbru** [comment]
I am using nginx+uwgsi and I also have this issue. I started with the config on [ArchWiki](https://wiki.archlinux.org/index.php/OwnCloud) but slightly derived with time.
I put my config and some log extracts there, though the errors are basically the same as for @wvandelli :
https://gist.github.com/simonbru/a61b8897249afc9136cd

The problem only happens with a HEAD request and correct user/password. A GET request with the same input returns 200 OK.
I also haven't noticed any issue when using the desktop client, DAVDroid, Thunderbird, or even webdav mounts from Nautilus.

**Comment by teemu-torma** [comment]
I did a parallel virtual domain against the same owncloud installation, but this time using php5-fpm.  That works as expected.

The difference is the "HEAD /remote.php/webdav/", where owncloud under php5-fpm gives 200, but when using uwsgi it gives 502 and it stops there.  As seen in the logs posted here, it error really seems to come from owncloud.

It seems to be only HEAD command that fails.  GET and PROPFIND on /remote.php/webdav/ appear to work fine.

**Comment by gdamjan** [comment]
I've found that commenting out 
```php
$server->addPlugin(new \OC\Connector\Sabre\DummyGetResponsePlugin());
```
in apps/files/appinfo/remote.php fixes this issue. I don't know what the exact reason for this is. and if Dummy....Plugin is really needed.

**Comment by DemoFreak** [comment]
https://github.com/owncloud/core/commit/432d7be8cc66da0de1e174522333e5b5dd004c91

**Comment by matzex** [comment]
I have this problem too. The android app is not able to upload files.
Ubuntu 12.04.4, PHP 5.4.44. (no nginx)
The workaround from @gdamjan (https://github.com/owncloud/core/issues/17586#issuecomment-134363081) is not working for me. Does anyone has an idea how to solve this problem?

**Comment by gdamjan** [comment]
we've had a discussion on this [sabre-dav issue](https://github.com/fruux/sabre-dav/issues/684)  too. The reason why DummyGetResponsePlugin trips uwsgi is that it isn't setting a status.

**Comment by PVince81** [comment]
@LukasReschke

**Comment by LukasReschke** [comment]
Patch is at https://github.com/owncloud/core/pull/18562, please review.

**Comment by gdamjan** [comment]
thanks for the fix.

I'd say this is a problem that's has its roots in all 3 of projects: uwsgi, sabre-dav and owncloud.
owncloud didn't set the status, sabre-dav didn't catch that case, and uwsgi failed pretty bad on a status of 'HTTP/1.1 '.

let's see this fixed in all 3 :)

**Comment by tohojo** [comment]
Yup, this fixes the issue for me as well. Thanks! :)
