### ISSUE TITLE
Cron mode in autoconfig

### ISSUE THREAD

**Issue by nazar-pc** [owncloud/core#17584]
I'm working on awesome docker container which configures everything in completely automated way, even CRON tasks, but I can't specify anyhow to use system cron by default right after installation (AJAX is used by default).

Any chance to add option for that in `autoconfig.php`?

**Comment by RealRancor** [comment]
Have a look at the latest comments from @DeepDiver1975, he had explained in an issue how to use additional parameters in a seperate config file.

**Comment by nazar-pc** [comment]
@RealRancor, just checked his last comments - nothing like that, would you be so kind to point me there?

**Comment by RealRancor** [comment]
Sorry, that was an older comment from last year:

https://github.com/owncloud/core/issues/8022#issuecomment-60391346

which was linked in https://github.com/owncloud/core/issues/17302

**Comment by nazar-pc** [comment]
Well, can't find how to specify cron mode, not sure whether such option exists.
Found `backgroundjobs_mode` in template file, but setting it in `config.php` doens't have any effect on running instance. No mentions about this in admin guide.

**Comment by Xenopathic** [comment]
Cron mode is stored in the DB, and the best way to change it in a container setup script is by executing `./occ background:cron` after ownCloud setup.

**Comment by nazar-pc** [comment]
What about changing it before actual setup?

**Comment by Xenopathic** [comment]
Before setup no DB is initialised, so this cannot work.

**Comment by nazar-pc** [comment]
This is what I was talking about from the beginning. There is default value `ajax` and no way to specify alternative before installation. But I need it.

**Comment by karlitschek** [comment]
Agreed. We need a way to set this via an occ command or REST API call.

**Comment by DeepDiver1975** [comment]
> This is what I was talking about from the beginning. There is default value ajax and no way to specify alternative before installation. But I need it.

As described by @Xenopathic there is a occ command to change the cron mode.
So the automated/scripted installation can look like:

```sh
./occ install
./occ background:cron
```

I really see no need to add anything else

**Comment by nazar-pc** [comment]
I'm using `autoconfig.php`, which means I do not call `./occ install`, user does that when enter Web UI for the first time, and when user click "Finish", I want him to get background tasks set to `cron`.
Well, I can hack around owncloud system files and achieve what I want, but that would be rude and error-prone.
What I currently do is:
> su git -c 'php occ background:cron' && su git -c 'php -f cron.php > /dev/null 2>&1'

But this is quite ugly, even though it works.

This is not about REST API or CLI interface, I need to specify default value before installation.

To be more specific, look at how it works with Docker compose: https://github.com/nazar-pc/docker-webserver-apps/tree/master/owncloud including corresponding Dockerfile's

**Comment by DeepDiver1975** [comment]
> I'm using autoconfig.php, which means I do not call ./occ install

From my perspective it's time to switch - we will not invest further into autoconfig.php.
Any future development will go into ./occ
