### ISSUE TITLE
occ broken in 8.1.0-2 in Ubuntu 14.0.4: Fatal error in mdb2schemareader.php on line 71

### ISSUE THREAD

**Issue by timon-schroeter** [owncloud/core#17583]
While doing a clean install on Ubuntu 14.0.4 via the preferred method (package via apt-get) when executing 
```
sudo -u www-data php /var/www/owncloud/occ  maintenance:install --database "mysql" --database-name "owncloud"  --database-user "root" --database-pass "hidden" --admin-user "admin-timon" --admin-pass "hidden"
```
I geht the following output:
```
ownCloud is not installed - only a limited number of commands are available
PHP Fatal error:  Call to a member function children() on a non-object in 
/var/www/owncloud/lib/private/db/mdb2schemareader.php on line 71
```

Tried this two times, same result each time. After removing the db and db users I tried running the install wizard in the browser which worked just fine. Either way I would prefer occ and if it's there and advertised it should work on a fresh vserver via the preferred method of installation!?

**Comment by karlitschek** [comment]
Which package do you use to install? The one from the official ownCloud repo or something else?

**Comment by timon-schroeter** [comment]
I installed the current package from the official ownCloud repo.

More specifically I executed the exact commands listet here:
https://software.opensuse.org/download/package?project=isv:ownCloud:community&package=owncloud 
in the Section on Ubuntu 14.04, namely
```
sudo sh -c "echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_14.04/ /' >> /etc/apt/sources.list.d/owncloud.list"
sudo apt-get update
sudo apt-get install owncloud
```

**Comment by DeepDiver1975** [comment]
Looks like the xml could not be loaded in https://github.com/owncloud/core/blob/master/lib/private/db/mdb2schemareader.php#L69

Can you please add following statement right before this:

```php
\OCP\Util::writeLog("Xml schema: $file", \OCP\Util::FATAL);

**Comment by timon-schroeter** [comment]
I'd like to help debug this. And I've worked around occ by using the install wizard in the browser which worked just fine. So now I've got this ownCloud Instance completely setup and in production with users on it. And I only have this one vserver running Ubuntu Ubuntu 14.0.4.
So:
How can I help debug this while preserving the (now) live ownCloud instance?

**Comment by DeepDiver1975** [comment]
@timon-schroeter I'm happy you finally got your instance setup. Thanks for the feedback! We will analyze this issue.

@jnweiger Can you reproduce this issue with the packages? Using the pure source code this is working. THX

**Comment by jnweiger** [comment]
Yes, reproducable with owncloud-8.1.0-1-obs-isv-owncloud-community-8.1-testing-xubuntu_14.04

Investigating...

**Comment by DeepDiver1975** [comment]
@jnweiger please add this debug statement - https://github.com/owncloud/core/issues/17583#issuecomment-120762729

I suspect that due to the location of the code and the working dir of occ the xml is not found

**Comment by jnweiger** [comment]
The file is located in /var/www/owncloud/db_structure.xml, but the code tries to open it without any path names: 
{"reqId":"jjVy4kbalo4xGLsjp6f6","remoteAddr":"","app":"core","message":"OC\\DB\\MDB2SchemaReader::loadSchemaFromFile, Xml schema: db_structure.xml","level":4,"time":"2015-07-13T10:10:24+00:00"}
{"reqId":"jjVy4kbalo4xGLsjp6f6","remoteAddr":"","app":"PHP","message":"simplexml_load_file(): I\/O warning : failed to load external entity \"db_structure.xml\" at \/var\/www\/owncloud\/lib\/private\/db\/mdb2schemareader.php#70","level":3,"time":"2015-07-13T10:10:24+00:00"}

**Comment by jnweiger** [comment]
Patching the code like this makes it work:

<pre>
        public function loadSchemaFromFile($file) {
                $schema = new \Doctrine\DBAL\Schema\Schema();
                $loadEntities = libxml_disable_entity_loader(false);
                if (!file_exists($file)) {
                        $file = \OC::$SERVERROOT . '/' . $file;
                }
                $xml = simplexml_load_file($file);
                libxml_disable_entity_loader($loadEntities);
                foreach ($xml->children() as $child) {
</pre>

@carlaschroder As a workaround, the instructions for running occ maintenance:install should say

<pre>
cd  /var/www/owncloud
sudo -u www-data php ./occ  maintenance:install --database
 "mysql" --database-name "owncloud"  --database-user "root" --database-pass "root" --admin-user
 "admin" --admin-pass "admin"
</pre>

**Comment by DeepDiver1975** [comment]
So from my understanding we should make sure occ is ALWAYS executed within the server root.
I'd suspect other operation to fail as well if not ....

Objections? @PVince81 @icewind1991 @karlitschek @jnweiger THX

**Comment by karlitschek** [comment]
I completely agree. Otherwise things will break.

**Comment by Xenopathic** [comment]
@DeepDiver1975 @karlitschek There is no reason why we shouldn't support running `occ` from outside the server root. Imagine a command that reads a file and inserts it into ownCloud somehow - if I'm in `/home/xenopathic`, then I can run `/srv/http/owncloud/occ foobar:loadfile myfile.dat` and it should load `/home/xenopathic/myfile.dat`. Obviously at the moment the priority is to document this, which is fine, but IMHO we should aim to get all `occ` commands working with absolute paths, referencing `OC::$SERVERROOT` and friends.

**Comment by DaniSancas** [comment]
Same bug encountered (clean installation from official package repo), but the @jnweiger 's hack did the trick.

I'll keep an eye in this thread, waiting for an official fix ;)

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 @karlitschek There is no reason why we shouldn't support running occ from outside the server root. Imagine a command that reads a file and inserts it into ownCloud somehow - if I'm in /home/xenopathic, then I can run /srv/http/owncloud/occ foobar:loadfile myfile.dat and it should load /home/xenopathic/myfile.dat. Obviously at the moment the priority is to document this, which is fine, but IMHO we should aim to get all occ commands working with absolute paths, referencing OC::$SERVERROOT and friends.

In an ideal world: yes - there should be no difference where occ is executed - maybe even a simple http://php.net/manual/en/function.chdir.php is enough - PR welcome

**Comment by Xenopathic** [comment]
@DeepDiver1975 Unfortunately a `chdir()` won't be much help - it'll solve the problem, sure, but it'll remove any benefit of running `occ` from outside the ownCloud server root, since every command will see the current dir as the server root instead of the place `occ` was called from, and relative paths won't work.

**Comment by carlaschroder** [comment]
docs updated 
https://github.com/owncloud/documentation/issues/1311

**Comment by Kawohl** [comment]
couldn't reproduce with https://software.opensuse.org/download/package?project=isv:ownCloud:community:8.1:testing&package=owncloud

So i assume its fixed and close.
