### ISSUE TITLE
Unable to share or unshare with link on OC 7.0.4, 8.1.0

### ISSUE THREAD

**Issue by Neraste** [owncloud/core#17581]
Hi people

This problem started to happen on OC 7.0.4, and I was hoping for it to be solved with 8.1.0 update, but nope. So, the problem is, I can't share or unshare folders or files with links.

### Steps to reproduce

Share a folder or a file with link in Files app.
OR
Unshare a previously (old) shared with link folder or file in Files app.

### Expected behaviour

Folder or file is shared.
OR
Folder or file isn't shared anymore.

### Actual behaviour

When sharing, I get an error message:

```
Error while sharing
Error
```

And sharing fails. When unsharing, I get another one:

```
Error
Error while unsharing
```

Unsharing fails; I can't share or unshare any more.

So, it was working before, but now it doesn't, and I have no idea what happened in between. And the error messages don't help.

### Server configuration

OS: OpenSUSE 13.2 on Cubox-i ARMv7hl
Webserver: Nginx 1.8.0
Database: Mariadb 10.0.13-MariaDB openSUSE package
PHP version: 5.6.1-27.1
Owncloud version: 8.1.0 (updated from 7.0.4)
Apps:

 - activity: 2.0.1
 - direct_menu: 0.3
 - files: 1.1.9
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - mail: 0.1.3
 - templateeditor: 0.1
 - updater: 0.6

Config:

```php

$CONFIG = array (
  ...
  'datadirectory' => '/data1/cloud',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  ...
  'installed' => true,
  'mail_smtpmode' => 'php',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'loglevel' => 1,
  'log_query' => false,
  'maintenance' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'asset-pipeline.enabled' => true,
  'appstore.experimental.enabled' => true,
);
```

No external storage (at least, data are on a dedicated HDD which is mounted)
No encryption
No user backend

### Client configuration

Browser: Mozilla Firefox 38.0.1-30.1, Chromium 43.0.2357.130-34.1 (seems to not be browser dependant)
Operating system: OpenSUSE Tumbleweed, MS Windows 7 (seems to not be OS dependant)

### Logs

Logs don't say anything (server's and Owncloud's) about this.

**Comment by karlitschek** [comment]
Can you try a clean and second installation for debugging? Maybe disable APCu and aeet pipelining support as a test?

**Comment by PVince81** [comment]
@Neraste can you confirm that the problem also exist with newly created shares ?
Because if it's only about old shares, then you might have broken old share entries that might be caused by an issue from OC < 7.0.4

**Comment by Neraste** [comment]
@PVince81 I can't share any more, so I can't tell. But since the problem started with OC 7.0.4, you're right to say it's a 7.0.4 issue. So the title of this issue is misleading.

As @karlitschek said, I will run a second installation.

**Comment by Neraste** [comment]
@karlitschek I've installed a pure fresh version to check, I encounter the very same problem.

**Comment by zaromarco** [comment]
I've installed a fresh new 8.1 into a sinology nas but i have quite the same error.
i'm able to upload a file , then if i share it and click on the link received by mail i get on the download page but on download button press i get file not found 
ERR_INVALID_RESPONSE
https://xxx.tradexsrl.com/owncloud/index.php/s/6gIEJWyrLQtvHYR/download 
also if i try to directly download the same file just uploaded from the web interface i get the same error.

**Comment by PVince81** [comment]
Did you double check your nginx settings to see if they match the documentation ?
From what I heard there might have been some changes.

**Comment by Neraste** [comment]
Yeah, I have checked, it is all the same.

**Comment by Neraste** [comment]
I still have the same problem after updating my system:

* PHP: 5.6.1-36.1
* Web server: nginx 1.8.0-1.1
* Database server: mariadb 10.0.20-2.12.1
* Owncloud: still 8.1.0 (and 8.1.1)

Not being able to share is quite annoying T_T !

**Comment by PVince81** [comment]
@zaromarco please raise a separate issue. You are able to share but not able to download the shared file => different issue.

The issue here is about not being able to **create** shares in the first place.

**Comment by PVince81** [comment]
@Neraste can you try setting up a second ownCloud instance on your NAS and see if it also happens there ? Goal is to find out whether your current database might contain corrupt data in oc_share that might be disturbing the sharing code.

**Comment by Neraste** [comment]
I have set up a second OC installation, a fresh one, and the problem is still there.

I can re-run the setup, to be sure, but it appears vanilla.

**Comment by PVince81** [comment]
Ok, so that excludes the database case.

Did you change any settings related to sharing in the admin page ?

**Comment by Neraste** [comment]
Not an answer or an explanation, but upgrading to 8.2.2 eventually solved the problem.

**Comment by Neraste** [comment]
Well, I was too quick...

With OC 8.2.2 as fresh install or as update, sharing works, but unsharing is still broken...

```
Error

Error while unsharing
```

**Comment by PVince81** [comment]
Do you by any chance have any ad blocker enabled ?

Because unsharing should work on fresh installs, but sometimes ad blockers might mess with URLs...

**Comment by Neraste** [comment]
Just deactivated AdBlock Plus, it didn't changed anything.

**Comment by PVince81** [comment]
And I guess still nothing in the logs ?

Can you check the browser's network console and paste a screenshot of the matching call ? It should be a POST to share.php that fails (red). We need to see the request body and the response body.

**Comment by PVince81** [comment]
Closing due to lack of feedback.
Feel free to reopen if you're still having issues with v9.0.2.
