### ISSUE TITLE
Owncloud 8.1 upgrade breaks applications

### ISSUE THREAD

**Issue by shiznix** [owncloud/core#17588]
Official apps. 'Contacts' and 'Calendar' are broken by the 8.1 upgrade.

The admin page offers to update the apps but this fails with 'Couldn't update app.'

**Comment by RealRancor** [comment]
Please use the issue template as asked here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version

**Comment by MorrisJobke** [comment]
@shiznix Can you retry the update? For more info see: https://mailman.owncloud.org/pipermail/devel/2015-July/001408.html

**Comment by shiznix** [comment]
Thanks Morris.
Frank said it perfectly. I was able to get each app upgraded by logging out and back in as admin and updating each app one by one.
