### ISSUE TITLE
Enhancement: Make Reverse Proxy Configuration possible via admin frontend

### ISSUE THREAD

**Issue by farson2003** [owncloud/core#17585]
At present it is still necessary to edit the config/config.php manually to allow access ownCloud via a multiple domains reverse SSL proxy https://ssl-proxy.tld/domain.tld/owncloud. 

Similar to the new email frontend setup, the admin should  be able to set this Reverse Proxy Configuration up via his admin frontend, whith which he could then edit the parameters below:
overwritehost"     => "ssl-proxy.tld",
  "overwriteprotocol" => "https",
  "overwritewebroot"  => "/domain.tld/owncloud",
  "overwritecondaddr" => "^10\.0\.0\.1$",

This would be a usability improvement of owncloud.

**Comment by karlitschek** [comment]
Well the thought is the reverse proxy configuration is a quite basic configuration. It is easy to kill the webinterface by typing something wrong into the form. This is something that should be done in the config file. And someone with a complicated setup like that should be able to edit a config file anyways.

**Comment by DeepDiver1975** [comment]
We already discussed this in the past - mainly all config parameters are kind of once-setup-an-done kind. Adding a WebUI is kind of overkill. Futhermore as described by @karlitschek - the web ui can easily be killed by setting something wrong by accident and being logged out for ever.
