### ISSUE TITLE
Blank Page after Upgrade to OC 7.0.7

### ISSUE THREAD

**Issue by corsch** [owncloud/core#17589]
Hi,

I've just updated my OC7 from 7.0.6 to 7.07 without any errors.

I can see the normal login page, but as soon as I login to my Owncloud, I'll get a blank Page in FF (HTTP 500 in IE11) and the following text in my owncloud.log.

{"app":"PHP","message":"syntax error, unexpected '[' at ...\/htdocs\/apps\/contacts\/lib\/addressbookprovider.php#123","level":3,"time":"2015-07-12T11:17:14+02:00"}

CentOS 5 with Apache 2.2.3 and PHP 5.3.19

Best Regards,
Corvin

**Comment by RealRancor** [comment]
Please report this to the issue tracker of the contacts app. Seems you currently need PHP 5.4 for that app.

**Comment by RealRancor** [comment]
@corsch Already reported here: https://github.com/owncloud/contacts/issues/981

Feel free to close here.
