### ISSUE TITLE
Update to 8.0.1 breaks existing installation

### ISSUE THREAD

**Issue by angelodag** [owncloud/core#17590]
### Steps to reproduce
1. Upgrade to 8.0.1 version

### Expected behaviour
After performing the update (started from the web interface) and rebooting the server Owncloud should just work...

### Actual behaviour
After reboot of the server the Owncloud home page does not show.

### Server configuration
**Operating system**: Debian Wheezy

**Web server:** nginx 1.2.1-2.2+wheezy3

**Database:** embedded (Sqlite)

**PHP version:** 5.4.41-0+deb7u1

**ownCloud version:** 8.1.0-2 (from package, admin page does not show up)

**Updated from an older ownCloud or fresh install:** updated from 8.0

**List of activated apps:**
Contacts, Tasks, Calendar, Activities

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder

PHP Fatal error:  Access to undeclared static property: Sabre\VObject\Property::$classMap in /var/www/owncloud/apps/calendar/appinfo/app.php on line 37

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => '***',
  'passwordsalt' => '***',
  'datadirectory' => '/media/589f8922-66f0-4e51-b76c-28a9a54d7690/owncloud/data',
  'dbtype' => 'sqlite3',
  'version' => '8.1.0.8',
  'installed' => true,
  'loglevel' => '0',
  'maintenance' => false,
  'theme' => '',
  'forcessl' => true,
  'log_rotate_size' => '1 MiB',
  'trusted_domains' => 
  array (
    0 => '*****',
    1 => '*****',
  ),
  'maxZipInputSize' => 838860800,
  'allowZipDownload' => true,
  'secret' => '*',
);
```
**Are you using external storage, if yes which one:** NO

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** NO

On ownCloud 7+ with access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

PHP Fatal error:  Access to undeclared static property: Sabre\VObject\Property::$classMap in /var/www/owncloud/apps/calendar/appinfo/app.php on line 37

### Client configuration
**Browser:**
Firefox 38.0.1
**Operating system:**
Opensuse 13.2

#### Web server error log
```
2015/07/05 15:16:53 [error] 2124#0: *2291 open() "/var/www/owncloud/apps/contacts/css/Jcrop.gif" failed (2: No such file or directory), client: ::ffff:**.**.**.**, server: owncloud, request: "GET /apps/contacts/css/Jcrop.gif HTTP/1.1", host: "pippo.server.org:####", referrer: "https://pippo.server.org:####/apps/contacts/css/jquery.Jcrop.min.css?v=4ee1af17891f093023b7bcfcd31f19a3"
2015/07/12 12:40:45 [error] 2125#0: *4839 upstream timed out (110: Connection timed out) while reading response header from upstream, client: ::ffff:**.**.**.**, server: owncloud, request: "GET /index.php/core/preview.png?file=%2FOperazioni.txt&c=548329664193d&x=36&y=36&forceIcon=0 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm-owncloud-omv.sock:", host: "pippo.server.org:####", referrer: "https://pippo.server.org:####/
index.php/apps/files/"
2015/07/12 12:48:43 [error] 2121#0: *4921 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Access to undeclared static property: Sabre\VObject\Property::$classMap in /var/www/owncloud/apps/calendar/appinfo/app.php on line 37" while reading response header from upstream, client: ::ffff:**.**.**.**, server: owncloud, request: "GET /index.php/settings/ajax/navigationdetect.php?app=calendar HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm-owncloud-omv.sock:", host: "pippo.server.org:####", referrer: "https://pippo.server.org:####/index.php/settings/apps"
2015/07/12 12:48:44 [error] 2121#0: *4919 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Access to undeclared static property: Sabre\VObject\Property::$classMap in /var/www/owncloud/apps/calendar/appinfo/app.php on line 37" while reading response header from upstream, client: ::ffff:**.**.**.**, server: owncloud, request: "POST /index.php/settings/ajax/enableapp.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm-owncloud-omv.sock:", host: "pippo.server.org:####", referrer: "https://pippo.server.org:####/index.php/settings/apps"
2015/07/12 12:48:44 [error] 2121#0: *4919 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Access to undeclared static property: Sabre\VObject\Property::$classMap in /var/www/owncloud/apps/calendar/appinfo/app.php on line 37" while reading response header from upstream, client: ::ffff:**.**.**.**, server: owncloud, request: "GET /index.php/settings/ajax/navigationdetect.php?app=contacts HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm-owncloud-omv.sock:", host: "pippo.server.org:####", referrer: "https://pippo.server.org:####/index.php/settings/apps"
2015/07/12 12:48:45 [error] 2121#0: *4919 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Access to undeclared static property: Sabre\VObject\Property::$classMap in /var/www/owncloud/apps/calendar/appinfo/app.php on line 37" while reading response header from upstream, client: ::ffff:**.**.**.**, server: owncloud, request: "POST /index.php/settings/ajax/enableapp.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm-owncloud-omv.sock:", host: "pippo.server.org:####", referrer: "https://pippo.server.org:####/index.php/settings/apps"
2015/07/12 12:48:45 [error] 2121#0: *4919 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Access to undeclared static property: Sabre\VObject\Property::$classMap in /var/www/owncloud/apps/calendar/appinfo/app.php on line 37" while reading response header from upstream, client: ::ffff:**.**.**.**, server: owncloud, request: "GET /index.php/settings/ajax/navigationdetect.php?app=tasks HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm-owncloud-omv.sock:", host: "pippo.server.org:####", referrer: "https://pippo.server.org:####/index.php/settings/apps"
2015/07/12 12:49:19 [error] 2121#0: *4919 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Access to undeclared static property: Sabre\VObject\Property::$classMap in /var/www/owncloud/apps/calendar/appinfo/app.php on line 37" while reading response header from upstream, client: ::ffff:**.**.**.**, server: owncloud, request: "POST /index.php/settings/ajax/enableapp.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm-owncloud-omv.sock:", host: "pippo.server.org:####", referrer: "https://pippo.server.org:####/index.php/settings/apps"
2015/07/12 12:49:19 [error] 2121#0: *4919 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Access to undeclared static property: Sabre\VObject\Property::$classMap in /var/www/owncloud/apps/calendar/appinfo/app.php on line 37" while reading response header from upstream, client: ::ffff:**.**.**.**, server: owncloud, request: "GET /index.php/settings/ajax/navigationdetect.php?app=contacts HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm-owncloud-omv.sock:", host: "pippo.server.org:####", referrer: "https://pippo.server.org:####/index.php/settings/apps"
2015/07/12 12:49:20 [error] 2121#0: *4919 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Access to undeclared static property: Sabre\VObject\Property::$classMap in /var/www/owncloud/apps/calendar/appinfo/app.php on line 37" while reading response header from upstream, client: ::ffff:**.**.**.**, server: owncloud, request: "POST /index.php/settings/ajax/enableapp.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm-owncloud-omv.sock:", host: "pippo.server.org:####", referrer: "https://pippo.server.org:####/index.php/settings/apps"
2015/07/12 12:49:20 [error] 2121#0: *4919 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Access to undeclared static property: Sabre\VObject\Property::$classMap in /var/www/owncloud/apps/calendar/appinfo/app.php on line 37" while reading response header from upstream, client: ::ffff:**.**.**.**, server: owncloud, request: "GET /index.php/settings/ajax/navigationdetect.php?app=contacts HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm-owncloud-omv.sock:", host: "pippo.server.org:####", referrer: "https://pippo.server.org:####/index.php/settings/apps"
2015/07/12 12:49:44 [error] 2121#0: *4919 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Access to undeclared static property: Sabre\VObject\Property::$classMap in /var/www/owncloud/apps/calendar/appinfo/app.php on line 37" while reading response header from upstream, client: ::ffff:**.**.**.**, server: owncloud, request: "POST /index.php/settings/ajax/enableapp.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm-owncloud-omv.sock:", host: "pippo.server.org:####", referrer: "https://pippo.server.org:####/index.php/settings/apps"
2015/07/12 12:49:45 [error] 2121#0: *4919 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Access to undeclared static property: Sabre\VObject\Property::$classMap in /var/www/owncloud/apps/calendar/appinfo/app.php on line 37" while reading response header from upstream, client: ::ffff:**.**.**.**, server: owncloud, request: "GET /index.php/settings/ajax/navigationdetect.php?app=tasks HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm-owncloud-omv.sock:", host: "pippo.server.org:####", referrer: "https://pippo.server.org:####/index.php/settings/apps"
2015/07/12 12:56:50 [error] 2121#0: *4971 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Access to undeclared static property: Sabre\VObject\Property::$classMap in /var/www/owncloud/apps/calendar/appinfo/app.php on line 37" while reading response header from upstream, client: ::ffff:**.**.**.**, server: owncloud, request: "GET /index.php/settings/admin HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm-owncloud-omv.sock:", host: "pippo.server.org:####", referrer: "https://pippo.server.org:####/index.php/settings/apps"
2015/07/12 12:57:00 [error] 2121#0: *4971 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Access to undeclared static property: Sabre\VObject\Property::$classMap in /var/www/owncloud/apps/calendar/appinfo/app.php on line 37" while reading response header from upstream, client: ::ffff:**.**.**.**, server: owncloud, request: "GET /index.php/settings/admin HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm-owncloud-omv.sock:", host: "pippo.server.org:####", referrer: "https://pippo.server.org:####/index.php/settings/apps"
2015/07/12 12:57:03 [error] 2121#0: *4971 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Access to undeclared static property: Sabre\VObject\Property::$classMap in /var/www/owncloud/apps/calendar/appinfo/app.php on line 37" while reading response header from upstream, client: ::ffff:**.**.**.**, server: owncloud, request: "GET /index.php/settings/apps HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm-owncloud-omv.sock:", host: "pippo.server.org:####", referrer: "https://pippo.server.org:####/index.php/apps/files/"
2015/07/12 12:57:09 [error] 2121#0: *4971 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Access to undeclared static property: Sabre\VObject\Property::$classMap in /var/www/owncloud/apps/calendar/appinfo/app.php on line 37" while reading response header from upstream, client: ::ffff:**.**.**.**, server: owncloud, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm-owncloud-omv.sock:", host: "pippo.server.org:####"
2015/07/12 13:00:12 [error] 2122#0: *8 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Access to undeclared static property: Sabre\VObject\Property::$classMap in /var/www/owncloud/apps/calendar/appinfo/app.php on line 37" while reading response header from upstream, client: ::ffff:**.**.**.**, server: owncloud, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm-owncloud-omv.sock:", host: "pippo.server.org:####"
2015/07/12 13:02:12 [error] 2120#0: *17 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Access to undeclared static property: Sabre\VObject\Property::$classMap in /var/www/owncloud/apps/calendar/appinfo/app.php on line 37" while reading response header from upstream, client: ::ffff:**.**.**.**, server: owncloud, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm-owncloud-omv.sock:", host: "pippo.server.org:####"
2015/07/12 13:03:34 [error] 2120#0: *17 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Access to undeclared static property: Sabre\VObject\Property::$classMap in /var/www/owncloud/apps/calendar/appinfo/app.php on line 37" while reading response header from upstream, client: ::ffff:**.**.**.**, server: owncloud, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm-owncloud-omv.sock:", host: "pippo.server.org:####"
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"ER\/hYhw4fmmwlcbxHJuu","remoteAddr":"::ffff:192.168.0.139","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(149): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#1 \\\/var\\
\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(122): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\
Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/
sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/
sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2015-07-12T11:16:24+00:00","method":"PROPFIND","url":"\/remote.php\/webdav"}
{"reqId":"HD9uzo3AH6BvZxenUJ4g","remoteAddr":"::ffff:192.168.0.139","app":"core","message":"Adding default user backend WEBDAVAUTH.","level":0,"time":"2015-07-12T11:16:24+00:00","method":"PROPFIND","url":"\/remote.php\/webdav"}
{"reqId":"e+8+z4V8kMBiWOQ88\/+L","remoteAddr":"::ffff:192.168.0.139","app":"core","message":"Adding default user backend WEBDAVAUTH.","level":0,"time":"2015-07-12T11:16:41+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/"}
{"reqId":"N2P1ptn6TKFaRNWKRKQC","remoteAddr":"::ffff:192.168.0.139","app":"core","message":"Adding default user backend WEBDAVAUTH.","level":0,"time":"2015-07-12T11:17:12+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/"}
{"reqId":"VsetGm+y7Z7SYt5sIkSu","remoteAddr":"::ffff:192.168.0.139","app":"core","message":"Adding default user backend WEBDAVAUTH.","level":0,"time":"2015-07-12T11:17:22+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/"}
{"reqId":"k6wcFtREd20QrBRuDKWo","remoteAddr":"::ffff:192.168.0.139","app":"core","message":"Adding default user backend WEBDAVAUTH.","level":0,"time":"2015-07-12T11:17:42+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/"}
{"reqId":"KkznEQp7HiHMZD0c+OSB","remoteAddr":"::ffff:192.168.0.139","app":"core","message":"Adding default user backend WEBDAVAUTH.","level":0,"time":"2015-07-12T11:17:52+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/"}
{"reqId":"L0Ua2SBi5O7xpuUchM5c","remoteAddr":"::ffff:192.168.0.139","app":"core","message":"Adding default user backend WEBDAVAUTH.","level":0,"time":"2015-07-12T11:18:12+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/"}
{"reqId":"8L4YeOm\/pFroktcbeknR","remoteAddr":"::ffff:192.168.0.139","app":"core","message":"Adding default user backend WEBDAVAUTH.","level":0,"time":"2015-07-12T11:18:22+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/"}
{"reqId":"1MTndMGM1RPPnKz5OTH6","remoteAddr":"::ffff:192.168.0.139","app":"core","message":"Adding default user backend WEBDAVAUTH.","level":0,"time":"2015-07-12T11:18:43+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/"}
{"reqId":"QkwSX8ppisRuSP7uqYrZ","remoteAddr":"::ffff:192.168.0.139","app":"core","message":"Adding default user backend WEBDAVAUTH.","level":0,"time":"2015-07-12T11:18:52+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/"}```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
Empty

**Comment by RealRancor** [comment]
Seems you have an old version of the calendar app not compatible with oC 8.1. Remove the calendar folder in the app folder

**Comment by angelodag** [comment]
Hi RealRancor, thank you for your help.
Indeed removing the calendar app lets me accessing the web interface.
I had a running configuration with the "basic" apps: contacts, calendar, bookmarks and tasks, after the upgrade calendar is completely broken and the others are marked as experimental and do not start.

**Comment by DeepDiver1975** [comment]
Something went wrong during upgrade.  Please remove the calendar app and try to install it again.  Thx

**Comment by angelodag** [comment]
Thank you DeepDiver, something must have changed since I installed owncloud the first time, if I remove the calendar app then it does not show it in the list of installable apps...

**Comment by angelodag** [comment]
Downloading the latest calendar app zip from the site (https://github.com/owncloud/calendar/releases/download/v0.7.2/calendar.zip)
the occ app:ckeco-code says the app is not compliant.

./occ app:check-code calendar                                                                                                             :(
Analysing /var/www/owncloud/apps/calendar/js/l10n.php
 4 errors
    line   27: == - is discouraged
    line   81: == - is discouraged
    line   81: == - is discouraged
    line   82: == - is discouraged
Analysing /var/www/owncloud/apps/calendar/templates/part.import.php
 2 errors
    line   40: OC_Util - static method call on private class
    line   40: OC_Util - static method call on private class
Analysing /var/www/owncloud/apps/calendar/templates/part.choosecalendar.rowfields.php
 2 errors
    line   13: == - is discouraged
    line   27: == - is discouraged
Analysing /var/www/owncloud/apps/calendar/templates/calendar.php
 9 errors
    line    1: OC_Helper - static method call on private class
    line   27: OC_Util - static method call on private class
    line   30: != - is discouraged
    line   65: != - is discouraged
    line   66: != - is discouraged
    line   68: OC_Util - static method call on private class
    line   72: OC_Util - static method call on private class
    line   72: OC_Util - static method call on private class
    line   72: == - is discouraged
Analysing /var/www/owncloud/apps/calendar/templates/part.share.php
 8 errors
    line   17: == - is discouraged
    line   17: == - is discouraged
    line   24: == - is discouraged
    line   24: == - is discouraged
    line   42: == - is discouraged
    line   60: OC_Util - static method call on private class
    line   75: == - is discouraged
    line   95: OC_Util - static method call on private class
Analysing /var/www/owncloud/apps/calendar/templates/part.editcalendar.php
 3 errors
    line   18: OC_Util - static method call on private class
    line   18: == - is discouraged
    line   18: OC_Util - static method call on private class
Analysing /var/www/owncloud/apps/calendar/templates/part.eventform.php
 6 errors
    line    1: OC_Helper - static method call on private class
    line    9: != - is discouraged
    line   73: != - is discouraged
    line  206: == - is discouraged
    line  229: != - is discouraged
    line  231: != - is discouraged
Analysing /var/www/owncloud/apps/calendar/templates/part.showevent.php
 5 errors
    line   22: == - is discouraged
    line   22: == - is discouraged
    line   28: OC_Util - static method call on private class
    line   31: OC_Util - static method call on private class
    line  229: == - is discouraged
Analysing /var/www/owncloud/apps/calendar/appinfo/remote.php
 5 errors
    line   10: == - is discouraged
    line   10: OC_App - static method call on private class
    line   10: OC_App - static method call on private class
    line   11: OC_App - static method call on private class
    line   16: OC_App - static method call on private class
Analysing /var/www/owncloud/apps/calendar/appinfo/preupdate.php
 2 errors
    line   12: OC_DB - static method call on private class
    line   14: OC_Config - static method call on private class
Analysing /var/www/owncloud/apps/calendar/appinfo/update.php
 10 errors
    line   10: == - is discouraged
    line   25: == - is discouraged
    line   36: == - is discouraged
    line   39: == - is discouraged
    line   42: OC_User - static method call on private class
    line   54: == - is discouraged
    line   57: == - is discouraged
    line   60: OC_User - static method call on private class
    line   72: OC_User - static method call on private class
    line   74: OC_User - static method call on private class
Analysing /var/www/owncloud/apps/calendar/ajax/event/new.form.php
 1 errors
    line   38: != - is discouraged
Analysing /var/www/owncloud/apps/calendar/ajax/event/edit.php
 1 errors
    line   41: != - is discouraged
Analysing /var/www/owncloud/apps/calendar/ajax/event/edit.form.php
 16 errors
    line   76: == - is discouraged
    line   83: == - is discouraged
    line   87: == - is discouraged
    line   88: == - is discouraged
    line   90: == - is discouraged
    line   93: == - is discouraged
    line  100: == - is discouraged
    line  102: == - is discouraged
    line  105: == - is discouraged
    line  113: == - is discouraged
    line  123: == - is discouraged
    line  133: == - is discouraged
    line  144: == - is discouraged
    line  161: == - is discouraged
    line  164: == - is discouraged
    line  266: != - is discouraged
Analysing /var/www/owncloud/apps/calendar/ajax/categories/rescan.php
 2 errors
    line   28: == - is discouraged
    line   36: == - is discouraged
Analysing /var/www/owncloud/apps/calendar/ajax/import/dropimport.php
 1 errors
    line   27: == - is discouraged
Analysing /var/www/owncloud/apps/calendar/ajax/import/import.php
 4 errors
    line   31: == - is discouraged
    line   34: == - is discouraged
    line   47: != - is discouraged
    line   62: == - is discouraged
Analysing /var/www/owncloud/apps/calendar/ajax/import/calendarcheck.php
 1 errors
    line   13: == - is discouraged
Analysing /var/www/owncloud/apps/calendar/ajax/events.php
 1 errors
    line   14: == - is discouraged
Analysing /var/www/owncloud/apps/calendar/ajax/calendar/delete.php
 1 errors
    line   18: == - is discouraged
Analysing /var/www/owncloud/apps/calendar/ajax/calendar/new.php
 2 errors
    line   14: == - is discouraged
    line   20: == - is discouraged
Analysing /var/www/owncloud/apps/calendar/ajax/calendar/update.php
 5 errors
    line   16: == - is discouraged
    line   22: != - is discouraged
    line   25: != - is discouraged
    line   25: == - is discouraged
    line   45: != - is discouraged
Analysing /var/www/owncloud/apps/calendar/ajax/settings/guesstimezone.php
 2 errors
    line   20: OC_JSON - static method call on private class
    line   24: == - is discouraged
Analysing /var/www/owncloud/apps/calendar/ajax/settings/timezonedetection.php
 1 errors
    line   12: == - is discouraged
Analysing /var/www/owncloud/apps/calendar/settingswrapper.php
 1 errors
    line    2: OC_L10N - static method call on private class
Analysing /var/www/owncloud/apps/calendar/index.php
 7 errors
    line   13: == - is discouraged
    line   19: == - is discouraged
    line   22: == - is discouraged
    line   25: == - is discouraged
    line   28: == - is discouraged
    line   36: == - is discouraged
    line   36: == - is discouraged
Analysing /var/www/owncloud/apps/calendar/lib/export.php
 1 errors
    line   25: == - is discouraged
Analysing /var/www/owncloud/apps/calendar/lib/object.php
 56 errors
    line  117: != - is discouraged
    line  159: != - is discouraged
    line  204: != - is discouraged
    line  250: != - is discouraged
    line  284: != - is discouraged
    line  315: != - is discouraged
    line  335: != - is discouraged
    line  376: == - is discouraged
    line  381: == - is discouraged
    line  390: == - is discouraged
    line  390: == - is discouraged
    line  393: == - is discouraged
    line  396: == - is discouraged
    line  412: == - is discouraged
    line  415: == - is discouraged
    line  418: == - is discouraged
    line  421: == - is discouraged
    line  424: == - is discouraged
    line  468: == - is discouraged
    line  472: == - is discouraged
    line  506: == - is discouraged
    line  719: == - is discouraged
    line  744: != - is discouraged
    line  765: != - is discouraged
    line  770: == - is discouraged
    line  774: == - is discouraged
    line  833: == - is discouraged
    line  833: == - is discouraged
    line  837: == - is discouraged
    line  837: == - is discouraged
    line  841: == - is discouraged
    line  841: == - is discouraged
    line  845: == - is discouraged
    line  845: == - is discouraged
    line  845: == - is discouraged
    line  852: == - is discouraged
    line  921: != - is discouraged
    line  936: == - is discouraged
    line  955: == - is discouraged
    line  957: == - is discouraged
    line  958: == - is discouraged
    line  967: == - is discouraged
    line  973: == - is discouraged
    line  981: == - is discouraged
    line  986: == - is discouraged
    line  995: == - is discouraged
    line 1000: == - is discouraged
    line 1007: == - is discouraged
    line 1012: == - is discouraged
    line 1024: == - is discouraged
    line 1036: == - is discouraged
    line 1050: != - is discouraged
    line 1053: == - is discouraged
    line 1056: == - is discouraged
    line 1119: == - is discouraged
    line 1149: == - is discouraged
Analysing /var/www/owncloud/apps/calendar/lib/calendar.php
 9 errors
    line   98: != - is discouraged
    line  191: != - is discouraged
    line  222: != - is discouraged
    line  276: == - is discouraged
    line  291: != - is discouraged
    line  377: == - is discouraged
    line  391: == - is discouraged
    line  422: == - is discouraged
    line  428: OC_User - static method call on private class
Analysing /var/www/owncloud/apps/calendar/lib/sabre/backend.php
 3 errors
    line   45: != - is discouraged
    line  137: == - is discouraged
    line  229: == - is discouraged
Analysing /var/www/owncloud/apps/calendar/lib/sabre/object.php
 1 errors
    line   47: != - is discouraged
Analysing /var/www/owncloud/apps/calendar/lib/sabre/calendar.php
 1 errors
    line   49: != - is discouraged
Analysing /var/www/owncloud/apps/calendar/lib/share/calendar.php
 3 errors
    line   39: != - is discouraged
    line   85: == - is discouraged
    line   92: == - is discouraged
Analysing /var/www/owncloud/apps/calendar/lib/share/event.php
 2 errors
    line   32: == - is discouraged
    line   35: == - is discouraged
Analysing /var/www/owncloud/apps/calendar/lib/repeat.php
 3 errors
    line   88: == - is discouraged
    line  150: != - is discouraged
    line  164: != - is discouraged
Analysing /var/www/owncloud/apps/calendar/lib/app.php
 9 errors
    line  108: != - is discouraged
    line  342: == - is discouraged
    line  344: == - is discouraged
    line  353: == - is discouraged
    line  354: == - is discouraged
    line  408: == - is discouraged
    line  485: != - is discouraged
    line  509: == - is discouraged
    line  553: == - is discouraged
Analysing /var/www/owncloud/apps/calendar/lib/search/event.php
 2 errors
    line   82: OC_l10n - is instanciated
    line   98: != - is discouraged
Analysing /var/www/owncloud/apps/calendar/lib/search/provider.php
 3 errors
    line   37: == - is discouraged
    line   47: != - is discouraged
    line   74: == - is discouraged
App is not compliant
./occ app:check-code calendar  8.46s user 0.58s system 99% cpu 9.061 total

**Comment by angelodag** [comment]
Never mind, despite the errors, enabling the app and performing then the upgrade brings to a functioning situation.

**Comment by RealRancor** [comment]
appcodechecker is nothing what needs to be used by a user. Its more for developers checking their code
