### ISSUE TITLE
Let admins uninstall RPM/DEB packages of apps but keep the server

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#17595]
Not sure if bug or feature.

I thought that the reason why separate packages are provided for apps was to make it possible to uninstall such apps when not needed.

So I tried this on my server:
`sudo zypper remove owncloud-app-user_webdavauth owncloud-app-user_ldap owncloud-app-external`

Zypper wants to remove all packages.

@jnweiger is this intended ? Are there plans to make these packages "recommended" so they auto-install the first time, but still let the user uninstall them if they want to ? Is that even supported by RPM and co ?

**Comment by RealRancor** [comment]
@PVince81 As all apps got merged back with 8.1.3 into owncloud-server this could be closed.
