### ISSUE TITLE
Flag experimental apps as experimental before they are installed

### ISSUE THREAD

**Issue by MightyCreak** [owncloud/core#17592]
### Steps to reproduce
1. Fresh install of ownCloud 8.1
2. Activate Contacts or Calendar apps (that are flagged "official", it's green, it seems perfect)
3. See in the activated apps that in fact they are experimental

### Expected behaviour
If an app is just flagged "official" and green, you expect it to be stable for the current ownCloud version.

If an app is "experimental", it should be flagged so **before** you install it.

### Actual behaviour
The contacts and Calendar app is flagged "Experimental" only **once** you activated them, so it's a unwanted surprise.

### Server configuration
**Operating system**: Debian 8.1

**Web server:** nginx 1.6.2

**Database:** mysql 5.5.43

**PHP version:** 5.6.7

**ownCloud version:** 8.1.0

**Updated from an older ownCloud or fresh install:** From and older ownCloud (8.0)

**List of activated apps:**

```
Enabled:
 - calendar: 0.7.2
 - contacts: 0.4.0.0
 - files: true
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
Disabled:
 - files_external
 - user_external
 - user_ldap
 - user_webdavauth

```

**The content of config/config.php:**
Note: `sudo -u www-data php occ config:list system --public` doesn't work with OC 8.1: `config` namespace doesn't exist.

```php
<?php
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' => 
  array (
    0 => 'xxx',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'xxx',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'xxx',
  'logtimezone' => 'UTC',
  'installed' => true,
);
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 38.0.5

**Operating system:** Fedora 22

#### Web server error log
Nothing interesting regarding calendar. The errors are from previous tests I was doing.
```
```

#### ownCloud log (data/owncloud.log)
```
```

**Comment by karlitschek** [comment]
Strange. @LukasReschke Can you have a look once you are back? :-)

**Comment by MightyCreak** [comment]
Apparently @RealRancor have the same problem. Extract from IRC:

    <RealRancor> They are also flagged experimental here at my installation

**Comment by PVince81** [comment]
Maybe something is wrong with the code that retrieves the approval flag for already installed apps.
Note that it shows "Experimental" because the flag might be missing, and "Experimental" is the default.

**Comment by CRCinAU** [comment]
Also note that if there is a newer version of the application available (I use Calendar and Contacts as an example here), then the app will show as EXPERIMENTAL and there is no option in the web interface to upgrade the application.

To then install the newer app version, you need to log into the host via ssh and rm -fR apps/contacts apps/calendar - and then install the apps again.

There really should be an "Upgrade" option - and it may well be the same problem as this bug causing it to go screwy.

**Comment by RealRancor** [comment]
@CRCinAU I think you have a different issue here as i got the update buttons from 0.7.0 to 0.7.1 and then to 0.7.2. I think its the best to create a new issue for this using the issue template.

**Comment by PVince81** [comment]
I see that there might be even another problem: if you disable the app store in the config under "appstoreenabled => false", then OC will not be able to retrieve the app levels of approval from the app store.

Maybe if the app store is disabled, the apps should simply not be shown as experimental at all ? (remove the warning) In such cases it means people already manually installed apps from git/tarballs.

**Comment by Gomez** [comment]
:+1: for @PVince81 suggestion. 
I dont use the appstore and have disabled it in the config. With this settings it should ignore the experimental flag stuff.

**Comment by RealRancor** [comment]
Possible fix in: https://github.com/owncloud/core/pull/17689 ?

**Comment by RealRancor** [comment]
Mhhh, at my installation its seems that this is no fixed by correctly flagging the Calendar and Contacts app at the appstore. Now both apps appears as "checked" instead of "flagged".

**Comment by PVince81** [comment]
Is this still happening in 8.2.3 ?

**Comment by enoch85** [comment]
Is this still happening in 9.0.2?

**Comment by MightyCreak** [comment]
Didn't have the bug again, but maybe it is because Contacts and Calendar and considered stable now, so it never is considered experimental anymore...

**Comment by enoch85** [comment]
Ok, I close this then. Feel free to reopen if it happens again.
