### ISSUE TITLE
Only read app version from one source

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#17598]
See https://github.com/owncloud/core/issues/17457

The updater app had 0.5 in info.xml but 0.6 in version, and this caused update loops.

The code that reads app versions needs to be changed to only read the version in a single location.

**Comment by PVince81** [comment]
@karlitschek @LukasReschke @icewind1991 @DeepDiver1975 FYI

**Comment by PVince81** [comment]
Would be nice if the code checker could also check that.

**Comment by karlitschek** [comment]
good catch!

**Comment by DeepDiver1975** [comment]
So the single location is then the xml?

**Comment by DeepDiver1975** [comment]
Regarding the version file: as far as I can tell from the code path being executed there is no speed benefit because the xml will be read right before or afterwards.

**Comment by MorrisJobke** [comment]
Fix is in #18332

**Comment by PVince81** [comment]
Anything left to do here ? Do we want to deprecate the "version" file ?

**Comment by DeepDiver1975** [comment]
> Do we want to deprecate the "version" file ?

I'd say yes - @karlitschek you did have some string opinion on this in the past since the version file introduce by purpose

**Comment by karlitschek** [comment]
You mean strong or string? ;-)
My only comment was that we should do this in a way that 3rdparty apps don't break. And so far they use the version file and not info.xml.

**Comment by DeepDiver1975** [comment]
> You mean strong or string? ;-)

yes - strong :facepalm:

**Comment by MorrisJobke** [comment]
See #19306 for app code check stuff that gives hints about the preferred version in `info.xml`

**Comment by MorrisJobke** [comment]
@cmonteroluque @DeepDiver1975 @karlitschek Let's move this to 9.0. The soft check for this is in the app code check.

**Comment by karlitschek** [comment]
agreed. too risky for 8.2

**Comment by PVince81** [comment]
@MorrisJobke what to do with this ? It's 9.0 'o'clock :wink:

**Comment by MorrisJobke** [comment]
Early 9.1 days?

**Comment by DeepDiver1975** [comment]
We did already stop using the version file - so we can finally drop it from the code base as well
