### ISSUE TITLE
Upgrade from 8.0.5 to 8.1 reports success, but loops

### ISSUE THREAD

**Issue by Bugsbane** [owncloud/core#17596]
Hi there,

When I do the upgrade from 8.0.5 to 8.1, whether by the webapp or by occ, it reports that everything was successful, but when I go to visit the ownCloud login page (or am redirected there by the webapp) it just goes back to the "ownCloud will be updated to version 8.1.0." screen.

I chown'd all the files to be owned by the usual http user and version.php reports:
$OC_Version = array(8,1,0,8);
$OC_VersionString = '8.1.0';
$OC_Edition = '';
$OC_Channel = 'stable';

There is nothing in owncloud,log. I'm running an Arch derivative (Manjaro) with Nginx.

This seems similar to https://github.com/owncloud/core/issues/5847

**Comment by PVince81** [comment]
Anything in the logs ?
The loop means that the upgrade didn't actually finish so it did not set the installed version in config.php.

Please post more information using the issue template https://raw.githubusercontent.com/owncloud/core/master/issue_template.md.

**Comment by Bugsbane** [comment]
Actually, when I tried it again, I did get this in the logs:
{"reqId":"dyFzqJjIk0MyPouLUVPc","remoteAddr":"192.168.1.99","app":"core","message":"XCache opcode cache will not be cleared because \"xcache.admin.enable_auth\" is enabled.","level":2,"time":"2015-07-13T06:17:29+00:00"}
{"reqId":"cCArZ1dBF307tKO\/gKGi","remoteAddr":"74.116.191.190","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Service unavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/srv\\\/http\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/srv\\\/http\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/srv\\\/http\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/srv\\\/http\\\/webapps\\\/owncloud\\\/remote.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/srv\\\/http\\\/webapps\\\/owncloud\\\/remote.php(135): handleException(Object(RemoteException))\\n#6 {main}\",\"File\":\"\\\/srv\\\/http\\\/webapps\\\/owncloud\\\/remote.php\",\"Line\":55}","level":4,"time":"2015-07-13T06:17:45+00:00"}
{"reqId":"qU0SmG8PO6iLAIU27vm3","remoteAddr":"74.116.191.190","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Service unavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/srv\\\/http\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/srv\\\/http\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/srv\\\/http\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/srv\\\/http\\\/webapps\\\/owncloud\\\/remote.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/srv\\\/http\\\/webapps\\\/owncloud\\\/remote.php(135): handleException(Object(RemoteException))\\n#6 {main}\",\"File\":\"\\\/srv\\\/http\\\/webapps\\\/owncloud\\\/remote.php\",\"Line\":55}","level":4,"time":"2015-07-13T06:17:45+00:00"}
{"reqId":"dyFzqJjIk0MyPouLUVPc","remoteAddr":"192.168.1.99","app":"core","message":"XCache opcode cache will not be cleared because \"xcache.admin.enable_auth\" is enabled.","level":2,"time":"2015-07-13T06:18:09+00:00"}


It seems that these redirect loops on Nginx are often caused by xcache, and xcache.admin.enable_auth more specifically. I do have xcache enabled, but phpinfo() tells me xcache.admin.enable_auth is off.

**Comment by Bugsbane** [comment]
It's funny though. If I delete the log, and go through another upgrade loop, the message above isn't in the log just afterwards, infact the log is empty.

It looks like OC really is completing the upgrade though, I'm getting this text (copied and pasted) onscreen just before the redirect:


Updating ownCloud to version 8.1.0, this may take a while.

Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Updated "updater" to 0.6
Turned off maintenance mode

The update was successful. Redirecting you to ownCloud now.

**Comment by PVince81** [comment]
Does XCache do code caching ? If it does, then maybe it is still using the old version of "config.php" that has the old OC version in it, which would explain why the updater believes the OC is still on the old version.

Are you able to clear it somehow ?

**Comment by PVince81** [comment]
@josh4trunks any idea about XCache issues ?

**Comment by Bugsbane** [comment]
Hmmm... I'm not so sure it is xcache any more. I completely disabled xcache to the point that it no longer shows up at all in phpinfo(), I cleared Firefox's cache for my site and did another round of the updater... and it still does the same thing.

**Comment by Bugsbane** [comment]
Nothing in the logs (is it possible to increase the logging output level with occ?)

**Comment by Bugsbane** [comment]
Could it be something like point 4 in this blog post:
http://possiblelossofprecision.net/?p=1774
(although I'm using Manjaro / Arch, not Fedora or CentOS)

Um, is it normal for PHP session.save_path to be "no value"?

**Comment by josh4trunks** [comment]
I don't know anything about xcache. I thought everyone had switched to using the built in zend opcache?

@Bugsbane what version of PHP are you on?

**Comment by Bugsbane** [comment]
@josh4trunks 5.6.10. Temporarily, you can see my phpinfo() [here](https://files.piersduruz.com/info.php).

**Comment by PVince81** [comment]
@Bugsbane ok then the core update worked. There is an app for which the version number on disk (see $appname/appinfo/version file or $appname/appinfo/info.xml) that does not match the current version in the database:  Try this `select * from oc_appconfig where configkey='installed_version';`

**Comment by Bugsbane** [comment]
activity, installed_version, 1.2.1
bookmarks, installed_version, 0.4
calendar, installed_version, 0.6.4
contacts, installed_version, 0.3.0.18
conversations, installed_version, 0.2.1
documents, installed_version, 0.8.2
files, installed_version, 1.1.9
files_embeddedvideo, installed_version, 0.0.6
files_mv, installed_version, 0.7.1
files_pdfviewer, installed_version, 0.5
files_sharing, installed_version, 0.6.2
files_texteditor, installed_version, 0.4
files_trashbin, installed_version, 0.6.3
files_versions, installed_version, 1.0.5
files_videoviewer, installed_version, 0.1.3
firstrunwizard, installed_version, 1.1
gallery, installed_version, 0.6.1
notes, installed_version, 0.8
search_lucene, installed_version, 0.5.3
tasks, installed_version, 0.5
templateeditor, installed_version, 0.1
updater, installed_version, 0.4.1

**Comment by Bugsbane** [comment]
hang on... it says updater is 0.4.1 despite the actual upgrader saying it had been upgraded to 0.6...

**Comment by Bugsbane** [comment]
It's not just the updater app. Here's a list of apps I've checked and their versions:

** app / file version / db version: **
activity / 2.0.1 / 1.2.1

**Comment by PVince81** [comment]
The version mismatch is normal before an update. What the update does is run the update routines of every app and also update their database structure.

In your case there might be one app that does not update itself properly so its version number stays on the old one.

You could try disabling the apps one by one using `./occ app:disable appname`. Disable one, then try updating. If it doesn't work, carry on until you find which one was broken.

**Comment by Bugsbane** [comment]
Hmm... I've already updated *all* of them, except for files...

**Comment by Bugsbane** [comment]
Can I safely disable that?

**Comment by PVince81** [comment]
You cannot disable the files app, as it would render ownCloud useless (no files, no webdav, etc).
Apps without versions shouldn't be an issue, but if you want to be sure, you could temporarily move away their folders into a temp subfolder.

From your listing above it seems the files app has the correct version too.
So you are saying that the command `./occ app:list` only shows the files app now ?

And still the update runs in a loop ? :frowning:

**Comment by Bugsbane** [comment]
It only shows files as being active, yes. It shows the other apps, but under a "Deactivated" category.

**Comment by PVince81** [comment]
Mind posting your config.php ? (make sure to remove the password salt and other secret info)

**Comment by Bugsbane** [comment]
<?php
$CONFIG = array (
  'instanceid' => 'oc105b6e9afc',
  'passwordsalt' => 'XXXXXXXXXXXXXXXXXX',
  'trusted_domains' => 
  array (
    0 => 'my.domain.tld',
  ),
  'datadirectory' => '/path/to/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'oc',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'XXXX_',
  'dbuser' => 'XXXXXXXX',
  'dbpassword' => 'XXXXXXXXXX',
  'installed' => true,
  'theme' => '',
  'maintenance' => true,
  'overwrite.cli.url' => 'https://my.domain.tld',
  'forcessl' => true,
  'secret' => 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  'preview_libreoffice_path' => '/bin/libreoffice',
  'mail_domain' => 'XXXXXXXXXXX',
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'XXXXXXXXX',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'XXXXXXXXXXXXX',
  'mail_smtpport' => 'XXX',
  'mail_smtpname' => 'XXXXXXX@XXXXXXX.XXX',
  'mail_smtppassword' => 'XXXXXXXXXXXXX',
  'mail_smtpsecure' => 'ssl',
);

**Comment by RealRancor** [comment]
Try to change the version of the updater app as described here: https://github.com/owncloud/core/issues/17457

**Comment by Bugsbane** [comment]
Ok, downgrading the version number of the upgrader and the notes apps let me log in. I think we can call this a dupe of #17457

**Comment by PVince81** [comment]
Glad to hear that.

Closing as duplicate.
