### ISSUE TITLE
occ encryption:migrate fails

### ISSUE THREAD

**Issue by R3s1stanc3** [owncloud/core#17603]
Hi
I just upgraded owncloud and it tells me to execute occ encryption:migrate to migrate my old encryption keys.
When executing "sudo -u www-data ./occ encryption:migrate" i get the following error:
$ sudo -u www-data ./occ encryption:migrate
Reorganize system folder structure
PHP Fatal error:  Call to a member function getRelativePath() on null in /var/www/owncloud/apps/files_trashbin/lib/storage.php on line 123

Edit: deacitvating the deleted files app solved the issue.
but i think it is strange that you have to execute occ encryption:migrate for every user seperatly. for me this is no problem, since there are only 4 users but for bigger installations with more users, this might be problematic

**Comment by RealRancor** [comment]
Very likely a dup of https://github.com/owncloud/core/issues/16928

**Comment by karlitschek** [comment]
Hmm. Should also work without trash bin. @schiesbn What do you think?

**Comment by MorrisJobke** [comment]
Please continue the discussion in #16928
