### ISSUE TITLE
ownCloud 8.1 isHtaccessWorking wrongly fails

### ISSUE THREAD

**Issue by BenS89** [owncloud/core#17604]
### Steps to reproduce
1. Upgrade from ownCloud 8.0.5 with working .htaccess to 8.1
2. Open the admin-panel
3. The security-check component states that .htaccess is not working and that files may be accessible via the internet

### Expected behaviour
No errors should come up in the admin-panel since the .htaccess-protection still works

### Actual behaviour
The security-check component says in german: "Ihr Datenverzeichnis und Ihre Dateien sind wahrscheinlich vom Internet aus erreichbar. Die .htaccess-Datei funktioniert nicht. Es wird dringend empfohlen, Ihren Webserver dahingehend zu konfigurieren, dass das Datenverzeichnis nicht mehr vom Internet aus erreichbar ist oder dass Sie es aus dem Document-Root-Verzeichnis des Webservers herausverschieben."

I tested the .htaccess-protection with a browser and with a wget. In both ways, I correctly got the forbidden-page. The .htaccess-version is 8.1

### Server configuration
QNAP Embedded Linux QTS 4.2

**Web server:**
Apache web server

**Database:**
MySQL

**PHP version:**
5.5.25

**ownCloud version:** (see ownCloud admin page)
8.1 stable

**Updated from an older ownCloud or fresh install:**
Updated from 8.0.5

**List of activated apps:**
Calendar 0.7.2
Contacts 4.0.0

**Comment by PVince81** [comment]
@BenS89 are you using the default "data" directory or did you configure "datadirectory" to point somewhere outside the owncloud directory ? In which case it could be similar to https://github.com/owncloud/core/issues/17652#issuecomment-121520483

**Comment by BenS89** [comment]
@PVince81 I use the default "data" directory. I also tested the apache-vhost config in terms of AllowOverride All. Is is all correct. Nevertheless, ownCloud still tells me that my .htaccess is broken.

**Comment by BenS89** [comment]
My .htaccess-file in the owncloud root looks like this:

```xml
 #Version: 8.1.0
<IfModule mod_headers.c>
  <IfModule mod_fcgid.c>
    <IfModule mod_setenvif.c>
       SetEnvIfNoCase ^Authorization$ "(.+)" XAUTHORIZATION=$1
       RequestHeader set XAuthorization %{XAUTHORIZATION}e env=XAUTHORIZATION
    </IfModule>
  </IfModule>

  <IfModule mod_env.c>
    # Add security and privacy related headers
    Header set X-Content-Type-Options "nosniff"
    Header set X-XSS-Protection "1; mode=block"
    Header set X-Robots-Tag "none"
    Header set X-Frame-Options "SAMEORIGIN"
    SetEnv modHeadersAvailable true
  </IfModule>

  # Add cache control for CSS and JS files
  <FilesMatch "\.(css|js)$">
    Header set Cache-Control "max-age=7200, public"
  </FilesMatch>
</IfModule>
<IfModule mod_php5.c>
php_value upload_max_filesize 2G
php_value post_max_size 2G
php_value memory_limit 512M
php_value mbstring.func_overload 0
php_value always_populate_raw_post_data -1
php_value default_charset 'UTF-8'
php_value output_buffering off
<IfModule mod_env.c>
  SetEnv htaccessWorking true
</IfModule>
</IfModule>
<IfModule mod_rewrite.c>
RewriteEngine on
RewriteRule .* - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteRule ^\.well-known/host-meta /public.php?service=host-meta [QSA,L]
RewriteRule ^\.well-known/host-meta\.json /public.php?service=host-meta-json [QSA,L]
RewriteRule ^\.well-known/carddav /remote.php/carddav/ [R=301,L]
RewriteRule ^\.well-known/caldav /remote.php/caldav/ [R=301,L]
RewriteRule ^apps/calendar/caldav\.php remote.php/caldav/ [QSA,L]
RewriteRule ^apps/contacts/carddav\.php remote.php/carddav/ [QSA,L]
RewriteRule ^remote/(.*) remote.php [QSA,L]
RewriteRule ^(build|tests|config|lib|3rdparty|templates)/.* - [R=404,L]
RewriteRule ^(\.|autotest|occ|issue|indie|db_|console).* - [R=404,L]
</IfModule>
<IfModule mod_mime.c>
AddType image/svg+xml svg svgz
AddEncoding gzip svgz
</IfModule>
<IfModule mod_dir.c>
DirectoryIndex index.php index.html
</IfModule>
AddDefaultCharset utf-8
Options -Indexes
<IfModule pagespeed_module>
  ModPagespeed Off
</IfModule>

ErrorDocument 403 /owncloud/core/templates/403.php
ErrorDocument 404 /owncloud/core/templates/404.php
```

.htaccess within the data folder:

```xml

# Generated by ownCloud on 2015-07-13 08:33:11
# line below if for Apache 2.4
<ifModule mod_authz_core.c>
Require all denied
</ifModule>

# line below if for Apache 2.2
<ifModule !mod_authz_core.c>
deny from all
Satisfy All
</ifModule>

# section for Apache 2.2 and 2.4
IndexIgnore *
```

And my apache-config for /share/Web/owncloud:

```xml
DocumentRoot "/share/Web"
<Directory />
	Options FollowSymLinks
	AllowOverride All
	Order deny,allow
	Deny from all
</Directory>
<Directory "/share/Web">
	Options FollowSymLinks MultiViews
	AllowOverride All
	Order allow,deny
	Allow from all
</Directory>
```

And since I use ssl, here my apache-ssl.conf

```xml
<Directory />
	Options FollowSymLinks
	AllowOverride ALL
	Order deny,allow
	Deny from all
	SSLRequire %{SSL_CIPHER} !~ m/^(EXP|NULL)/
</Directory>
```

**Comment by BenS89** [comment]
Can be closed since this is not reproducible anymore. No idea why it is working now...

**Comment by Xenopathic** [comment]
Since we have #17652 and your problem is resolved, I'm closing this.
