### ISSUE TITLE
occ encryption:migrate LockNotAcquiredException

### ISSUE THREAD

**Issue by R3s1stanc3** [owncloud/core#17611]
When migrating the encrytion app, it throws a LockNotAcquiredException:
[OCP\Files\LockNotAcquiredException]                                         
  Could not obtain lock type 1 on "[owncloud data dir]/[user]/files_encryption/[use].privateKey".

I checked, but the file doesn't exist. The first time, I executed occ, I got the following error:
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 4104 bytes) in /var/www/owncloud/lib/private/log.php on line 201

**Comment by PVince81** [comment]
@R3s1stanc3 please use the issue template https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

CC @schiesbn

**Comment by PVince81** [comment]
I believe this should be fixed in 8.1.1, please try again with that version.

If it still doesn't work, please reopen and fill out the issue template.
Thanks.
