### ISSUE TITLE
LInk sharing/download broken in 8.0.4

### ISSUE THREAD

**Issue by 4a616d6573205265696c6c79** [owncloud/core#17617]
Expected: Able to see/download image at shared url
Actual: No image displayed, download link 404's

Repro (for me anyway):
Share any image/file by link.
Visit link while logged out or in another session.
Download link is a 404

**Comment by karlitschek** [comment]
Not reproducible. Please post a bug report using the full issue template 
https://github.com/owncloud/core/blob/master/CONTRIBUTING.md
Strange username by the way :-)
