### ISSUE TITLE
Security & Setup Warnings for X-Content-Type-Options and X-Frame-Options

### ISSUE THREAD

**Issue by 4fd81048a9cd8a3fd43f1f4e52f84181** [owncloud/core#17613]
### Steps to reproduce
1. View the admin page

### Expected behaviour
No warnings

### Actual behaviour
```
The "X-Content-Type-Options" HTTP header is not configured to equal to "nosniff". This is a potential security or privacy risk and we recommend adjusting this setting.
The "X-Frame-Options" HTTP header is not configured to equal to "SAMEORIGIN". This is a potential security or privacy risk and we recommend adjusting this setting.
```

### Server configuration
**Operating system**: Ubuntu 15.04

**Web server:**  Apache/2.4.10 (Ubuntu)

**Database:** postgres (PostgreSQL) 9.4.4

**PHP version:** PHP Version 5.6.4-4ubuntu6.2

**ownCloud version:** ownCloud 8.1.0 (stable)

**Updated from an older ownCloud or fresh install:** Updated

### Details
```
curl -I https://www.buchananworldcorp.com/owncloud/
HTTP/1.1 200 OK
Date: Mon, 13 Jul 2015 13:50:36 GMT
Server: Apache/2.4.10 (Ubuntu)
Strict-Transport-Security: max-age=63072000; includeSubdomains; preload
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *; connect-src *
Set-Cookie: oc9a1e2ea845=e7mao7domb5cokpjki09evlb56; path=/owncloud; HttpOnly; Secure
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Robots-Tag: none
X-Frame-Options: SAMEORIGIN
Content-Type: text/html; charset=UTF-8
```

These headers are being set twice in the response.  In Issue #15342 LukasReschke suggests that this is likely the problem.  (Actually two problems, the headers should not be set twice and the check should handle the header appearing twice)

I found that these headers were getting set in /etc/apache2/mods-enabled/ssl.conf and in .htaccess.

In /etc/apache2/mods-enabled/ssl.conf I commented out these two lines, reloaded Apache and the warnings went away.
```
#Header always set X-Frame-Options DENY
#Header always set X-Content-Type-Options nosniff
```

**Comment by DeepDiver1975** [comment]
So I guess this is something for the docs @carlaschroder

**Comment by LukasReschke** [comment]
Yes - headers shall not be double sent. :speak_no_evil:

**Comment by oparoz** [comment]
In the documentation, make sure the headers are not completely disabled, but suggest to modify the directives so that ownCloud can modify them.

**Comment by carlaschroder** [comment]
@oparoz , how do you do that?

**Comment by oparoz** [comment]
@carlaschroder - Replace `always` with set. @4fd81048a9cd8a3fd43f1f4e52f84181, please confirm that it still works for you if you make that change.

**Comment by AW-UC** [comment]
Same here, but even more headers set twice:
```
HTTP/1.1 200 OK
Date: Mon, 13 Jul 2015 21:13:45 GMT
Server: Apache/2.2.29 (Unix)
X-Powered-By: PHP/5.6.10
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *; connect-src *
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: Sameorigin
X-Robots-Tag: none
Set-Cookie: 51963f658a09f=julaeck5quun61mje37i754nk3; path=/owncloud; HttpOnly
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Robots-Tag: none
X-Frame-Options: SAMEORIGIN
Content-Type: text/html; charset=UTF-8
```
I think setting the headers twice, shouldn't be a problem. In shared hosting environments that scenario might be difficult to prevent.

**Comment by DeepDiver1975** [comment]
Out of scope for me for 8.1.1 - let's address this in 8.1.2 once @LukasReschke is back from :palm_tree:

**Comment by LukasReschke** [comment]
> I think setting the headers twice shouldn't be a problem. 

It is. You shall not send headers twice. From my opinion this goes back to: Needs to get documented, no software fix needed from my opinion.

**Comment by AW-UC** [comment]
> It is. You shall not send headers twice. From my opinion this goes back to: Needs to get documented, no software fix needed from my opinion.
That is definately correct, but on shared hosting you might not be able to prevent this. Of course, one could include in the docs, that one has to edit owncloud's `.htaccess`, if these headers are already set and you can't prevent that. The problem with this approach is, that it will get reverted on each owncloud upgrade.

**Comment by LukasReschke** [comment]
> That is definately correct, but on shared hosting you might not be able to prevent this. Of course, we could include in the docs, that one has to edit owncloud's .htaccess, if these headers are already set without possibility to opt-out. The problem with this approach is, that it will get reverted on each owncloud upgrade.

There is no reason at all why shared hosters should modify such headers. If they do this: Get a new hoster.

**Comment by AW-UC** [comment]
@LukasReschke yes, sorry my mistake: I didn't check the headers correctly. Indeed, the headers are set twice but only for the `owncloud` directory. For other directories beneath `owncloud`, these headers are not even set once. So it is not the hoster that is messing with the headers.
Now I wonder what else might be responsible for setting the headers apart from `.htaccess`? I don't think it can be ` /etc/apache2/mods-enabled/ssl.conf` as suggested above, because then the headers should be present on directories beneath `owncloud`.

**Comment by LukasReschke** [comment]
Mhm. Interesting. If you in .htaccess comment out the headers is this still the same behaviour? I might have an idea...

**Comment by AW-UC** [comment]
>If you in .htaccess comment out the headers is this still the same behaviour?

If I do that, the headers are still there but only **once**. Owncloud's headers-check stops complaining then.

**Comment by carlaschroder** [comment]
This is all interesting but inconclusive. When there is a definitive solution to this that I can use in the admin manual, please open a PR in owncloud/documentation. If this is one of those "it depends" scenarios, then it's a perfect candidate for a page in the documentation wiki https://github.com/owncloud/documentation/wiki

**Comment by aptalca** [comment]
Owncloud documentation suggests adding this line to nginx config:
`fastcgi_param modHeadersAvailable true; #Avoid sending the security headers twice`
https://doc.owncloud.org/server/8.1/admin_manual/installation/nginx_configuration.html

I noticed that after adding that line, I believe all headers from the owncloud .htaccess get ignored. Because if I remove the nosniff line from nginx conf, but have the line from above in there, my headers are missing the nosniff even though it is still in the .htaccess

But in summary, adding the line from above, along with all necessary headers into the nginx config should solve the problems

**Comment by AW-UC** [comment]
@aptalca thanks for the input, but this issue is about Apache webservers (see first post). Apart from that, if **all** header entries from `.htaccess` files are ignored after adding that line, there seems to be yet another issue. What are the headers of folders next to your `owncloud` folder (with that `fastcgi...` setting and without)?

**Comment by aptalca** [comment]
Oops, my bad. I was looking at multiple threads about this issue and ended up replying to the wrong one.

**Comment by Gomez** [comment]
Is this a bug in the "Security & setup warnings" check? 
I removed this from my NGINX reverse proxy setting (to get rid of the warning):
```
add_header X-Frame-Options SAMEORIGIN;
```
But i like to add it again, as it makes sure its there...

**Comment by LukasReschke** [comment]
> But i like to add it again, as it makes sure its there...

https://github.com/owncloud/core/issues/17613#issuecomment-130429388 - this will stop from ownCloud sending the headers so that you can do it on your own.

**Comment by LukasReschke** [comment]
Sample documentation seems correct. Thus closing.

**Comment by AW-UC** [comment]
@LukasReschke Why did you close this? @Gomez comment was about **NGINX**. The linked comment and the sample documentation that you refer to is also about **NGINX**.
However, this issue (see OP) concerns **Apache**.

**Comment by Gomez** [comment]
> https://github.com/owncloud/core/issues/17613#issuecomment-130429388 - this will stop from ownCloud sending the headers so that you can do it on your own.
In a reverse proxy setup, it does not solve the problem. @AW-UC is correct, some similar solution (if it exists) should be added/tested..

**Comment by AW-UC** [comment]
@LukasReschke ping! May you elaborate, why you closed this? Which part of the documentation are you referring to? The issue is still present on 8.1.3 for me. In https://github.com/owncloud/core/issues/17613#issuecomment-130176949 you mentioned that you have an idea... any news here?

**Comment by ckujau** [comment]
I only found [this documentation article](https://doc.owncloud.org/server/8.2/admin_manual/installation/nginx_configuration.html "Nginx Configuration") on how to configure "Nginx", where a FastCGI parameter is mentioned to [not send headers twice](https://github.com/owncloud/documentation/issues/1327 "Add fastcgi_param modHeadersAvailable true; to NginX conf of oC 8.1.x"), but I couldn't find a hint for Apache and/or ```php-fpm``` users. I'm setting ```X-Content-Type-Options``` and ```X-Frame-Options``` globally and the had to disable both in ```owncloud/lib/private/response.php``` to get of the warning and to _not_ send these headers twice:

<pre>
--- owncloud/lib/private/response.php.orig      2015-12-21 13:46:53.000000000 +0100
+++ owncloud/lib/private/response.php   2016-02-17 00:48:33.628246055 +0100
@@ -257,8 +257,8 @@ class OC_Response {
                // custom headers on the webserver side
                if(getenv('modHeadersAvailable') !== 'true') {
                        header('X-XSS-Protection: 1; mode=block'); // Enforce browser based XSS filters
-                       header('X-Content-Type-Options: nosniff'); // Disable sniffing the content type for IE
-                       header('X-Frame-Options: Sameorigin'); // Disallow iFraming from other domains
+               //      header('X-Content-Type-Options: nosniff'); // Disable sniffing the content type for IE
+               //      header('X-Frame-Options: Sameorigin'); // Disallow iFraming from other domains
                        header('X-Robots-Tag: none'); // https://developers.google.com/webmasters/control-crawl-index/docs/robots_meta_tag
                }
        }
</pre>

**Comment by xshadow** [comment]
The problem is that the Header is set twice: 

First in the vhost file: 

```
# /etc/apache2/sites-enabled/cloud.foo.conf
--- 8< ---
    <IfModule mod_headers.c>
        Header add Strict-Transport-Security: "max-age=15768000;includeSubdomains"
        Header add X-Frame-Options "SAMEORIGIN"
    </IfModule>

--- >8 ---
```
and a second time in owncloud/lib/private/response.php as @ckujau in https://github.com/owncloud/core/issues/17613#issuecomment-184931387 mentioned. Removing it from your vhost conf should do the trick. Because it is set as sane default in owncloud/lib/private/response.php .

**Comment by AndreasMaros** [comment]
This issue still exists unchanged but worse: If I comment out lines in .htaccess [as suggested above](https://github.com/owncloud/core/issues/17613#issuecomment-130176949) the integrity checks will fail – either way I'm stuck with warnings.

While headers should not be sent twice the warning displayed when they are is misleading and wrong. The issues caused by missing headers are addressed by double headers.

Any help on this?

**Comment by nicolasrabier** [comment]
I run Owncloud 10 with Apache on a dedicated machine operated by Ubuntu 16.04

I fixed this warning by commenting the two lines `Header` in the file */etc/apache2/conf-enabled/ssl-params.conf*

```
# Header always set X-Frame-Options DENY
# Header always set X-Content-Type-Options nosniff
```
