### ISSUE TITLE
Mac OS 1.8.4.2527 Package keeps Crashing

### ISSUE THREAD

**Issue by jaal2001** [owncloud/core#17614]
Updated to 1.8.4.2527.
After update the App keeps crashing, only displays the option to send a bug report.

Deleted App.
Clean install, still the same issue.

Crash seems to happen before contacting the owncloud server, as I can't see any http(s) request on my owncloud server.

**Comment by DeepDiver1975** [comment]
Please reopen in https://github.com/owncloud/client - THX
