### ISSUE TITLE
Overhaul and align the app rating system

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#17616]
The current rating system is broken and sends the wrong message. It's not aligned with what you find in other app stores and is confusing to users.

### Problems

1. Apps start at 50%. It makes zero sense
2. You're trying to match stars with a rating system with an entirely different scaling mechanism. Another fail
3. It doesn't reflect the truth. An app could have gotten 30 votes 3 years ago and be half-broken today. People install it only to realise it's doesn't live up to its rating
4. Now that the app store within oC is working, people don't have a reason to visit the app store and thus won't vote for apps unless devs start adding reminders in their app or heavily promote them on social media

### Solutions

The best solution would be to fix the app store to use the same stars rating used in ownCloud and to let users pick how many stars they want to award. That's how it works virtually everywhere else.
As a bonus, you could even let admins vote from within ownCloud, but that would mean tracking userid@instance to make sure they can only vote once.
And of course, there wouldn't be a rating, unless 10 (or more) votes have been collected.
Current votes can be converted to a 5 and ratings can be modified at any times. There is no reason to leave an app at 5 stars if you can't even install it on the latest version of ownCloud.

If it's too difficult to change system in the app store, then fix how you present the information. Show votes, not a percentage and use votes in the app store as well. Sure, a good app would only have something like 20-30 votes which is ridiculous compared to the number of downloads, but it wouldn't show 3.5 or 4 stars when it's really a 4.5 or 5 stars app.

People are usually looking for 5 stars app in mobiles app stores, when you see 4 or less, it usually means that something is wrong.

@karlitschek @DeepDiver1975 @jancborchardt @libasys @nickvergessen @Raydiation @jospoortvliet 
And forward this to as many devs as possible to get some feedback.

**Comment by Raydiation** [comment]
Please reopen here https://github.com/owncloud/appstore-issues/issues

**Comment by oparoz** [comment]
It also concerns the app itself, since it's the one showing to admins the useless stars rating...

**Comment by Raydiation** [comment]
Not really, if you adjust the app store the client should fetch better values.

**Comment by oparoz** [comment]
But if you can't fix the app store, then settings/apps needs to remove the stars rating. We currently don't know what's possible with the app store.

**Comment by jancborchardt** [comment]
What @Raydiation said is correct – @oparoz this belongs in https://github.com/owncloud/appstore-issues/issues

**Comment by oparoz** [comment]
Split in 2 then
https://github.com/owncloud/appstore-issues/issues/28
https://github.com/owncloud/core/issues/17629
