### ISSUE TITLE
No file displayed in file app after 8.1 upgrade

### ISSUE THREAD

**Issue by FrenchHope** [owncloud/core#17624]
But files are displayed on Android app...

Maybe my ownCloud server installation lacks a required PHP module ? But other apps like News seems OK...

**Comment by karlitschek** [comment]
Sorry but this ticket lacks any useful information. I suggest that you ask this question at the forum at forum.owncloud.org  Thanks.

**Comment by FrenchHope** [comment]
Sorry but I found nothing in owncloud.log.

**Comment by FrenchHope** [comment]
Thanks for the advice but that seems to be bug related to the picture app :

https://github.com/owncloud/core/issues/17461#issuecomment-119326318
