### ISSUE TITLE
Remove the stars rating system for apps until the app store supports it

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#17629]
The current stars rating system is misleading. Apps start from 3 stars which means average and which in no way reflects the quality of the app. On top of that, older apps may get more stars, simply because they've existed for a long time, not because they're currently worth 4 or 5 stars.

The problem comes from the app store which only includes a voting system instead of a proper rating system, so until the root problem is fixed, apps showing up in `settings/apps` should either
- show no rating besides official/approved/experimental. That would be the best solution. "No rating" is doing less damage than one which isn't accurate.
- show the number of votes the app release matching the ownCloud version the admin is using got above (:seven: :+1: ) or below zero (:five: :-1: ) like on comments in blogs. Using the global number would be misleading, because it wouldn't reflect the reality of the situation since older apps would get more votes, but maybe the data is not available per version.

@karlitschek @DeepDiver1975 @jancborchardt @libasys @nickvergessen @Raydiation @jospoortvliet 
And forward this to as many devs as possible to get some feedback.

**Comment by PVince81** [comment]
@karlitschek please have a look

**Comment by karlitschek** [comment]
this is a nice idea for an improvement in the future. For the moment it will stay like it is and improved in the future.

**Comment by PVince81** [comment]
Close or defer ?

**Comment by oparoz** [comment]
Defer! :P It's getting more and more important as the in-app app store is getting more apps. It's impossible to decide which **new** app is good based on what we see.

**Comment by PVince81** [comment]
Obsoleted by market app.

CC @DeepDiver1975
