### ISSUE TITLE
Update 8.0.4->8.1 encryption update error

### ISSUE THREAD

**Issue by specialist383** [owncloud/core#17621]
During an update from OC8.0.4 with encrypted files to OC8.1, the suggested modification command ....occ encryption:migrate threw an exception ":..while UPDATE 'oc_config' SET 'appid'= ? WHERE 'appid'= ? with params {encryption;file_encryption}"  with the error message "SQLSTATE{23000}: Integrity constraint violation: 1062 Duplicate entry 'encryption-publicShareKeyId' for key 'PRIMARY'. The process did not migrate anything.
When checking the MYSQL files, the table oc_appconfig index has 2 parameters appid(varchar32) and configkey(varchar64) as PRIMARY. Please check and advise.
Now with OC8.1 the OC user accounts are accessable and the files inside exist but cannot be opened (encrypted).
Server:Linux Ubuntu14.04LTS, Apache2.4, PHP5.5, MySQL

**Comment by karlitschek** [comment]
@schiesbn

**Comment by specialist383** [comment]
Following the suggestions of schiesbn to recover from a broken migration 8.0.4->8.1 I reset the backup keys and started ...occ encryption:migrate. After a moment it showed an error: "PHP fatal error: Call to a member function getRelativePath() on a non-object in /var/www/owncloud/apps/files_trash_bin/lib/storage.php on line 123". That file had been replaced before according to schiesbn's list of patches. 
In my installation I have owncloud in /var/www/owncloud/.. but the data store with a symlink in /srv/www/oc/data.... due to space availability. This OC installation worked perfect up to now including the 8.1 update. Could be a code or a link problem (?).
