### ISSUE TITLE
CENTOS 6 - Upgrade problem from OC 8.0.4 to 8.1.0

### ISSUE THREAD

**Issue by pastynko** [owncloud/core#17637]
I've got a problem upgrading OC from 8.0.4 to 8.1.0 on Centos6 with scl php54. 
When I run yum update it will stop on dependency error for package owncloud-8.1.0 - requires owncloud-server = 8.1.0

However, I'm using owncloud-server-scl-php54

I upgraded from OC 7.x.x to 8 using SCL PHP54 and I was able to update up to 8.0.4 without any problems.

**Comment by DeepDiver1975** [comment]
@jnweiger

**Comment by agru** [comment]
I have the same problem and should upgrade urgently because we have a presentation of ownCloud. I have to servers running on CentOS6. One did upgrade without this issue, the other one has the same issue.

The second server had originally PHP 5.4 installed, but is upgraded to PHP 5.5 since a longer time and this works without problems. I have no idea why ownCloud thinks it has to use owncloud-server-scl-php54 instead of owncloud-server-scl-php54!?

Is there any solution to what I can do to solve this?

**Comment by jnweiger** [comment]
@pastynko do you have a full log of yum output? 
'requires owncloud-server = 8.1.0' is okay. owncloud-server-scl-php54 should provide that.

**Comment by jnweiger** [comment]
@pastynko maybe going via 8.0.5 works?
You can do it like this:
<pre>
wget -nv http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/CentOS_6/isv:ownCloud:community:8.0.repo -O /etc/yum.repos.d/isv:ownCloud:community:8.0.repo
yum update owncloud-server-scl-php54
rm /etc/yum.repos.d/isv:ownCloud:community:8.0.repo
yum update owncloud-server-scl-php54
</pre>

I just tried the update from 8.0.5 to 8.1 with owncloud-server-scl-php54 and it works just fine.
(I cannot try 8.0.4 to 8.0.5 though. Don't have a reference system installed.)

**Comment by pastynko** [comment]
I will try it during the weekend.

Thanks for help!

**Comment by DeepDiver1975** [comment]
Let's move this to 8.1.2 then - THX

**Comment by pastynko** [comment]
@jnweiger 
I was able to update to 8.0.5 but when I try to do yum update owncloud-server-scl-php54, it gives me now this error: 
Transaction Check Error:
file /var/www/html/owncloud/.htaccess from install of owncloud-server-scl-php54-8.1.0-17.1.noarch conflicts with file from package owncloud-config-apache-8.0.5-7.1.noarch

I'm unable to do yum history undo because owncloud-8.0.4.2 is not in repo anymore.

Any help???

Thanks!

**Comment by pastynko** [comment]
No one is able to help me out of this situation?

**Comment by pastynko** [comment]
Just to let you know I was able to fix it by running yum remove owncloud which removed OC and then install OC 8.1 by running yum install.

Thanks!
