### ISSUE TITLE
8.1 php ldap segfault when some users login

### ISSUE THREAD

**Issue by benwilliams** [owncloud/core#17631]
Upgraded from 8.0.5 to 8.1 on Ubuntu 14.04.2 LTS using deb package from repo http://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_14.04/

Now when some users login the php process segfaults in the ldap library. Doesn't effect all users. When an effected user attempts to login, owncloud generates thousands of queries in a loop to the ldap server and CPU goes to 100% until the process segfaults.

```
Jul 13 09:03:40 hostname kernel: [1567616.839869] php5-fpm[10623]: segfault at 7ffef0922b40 ip 00007fb6100d55e2 sp 00007ffef0922b10 error 6 in libldap_r-2.4.so.2.8.3[7fb6100c2000+4d000]
Jul 13 09:04:12 hostname kernel: [1567648.823291] php5-fpm[10637]: segfault at 7ffef0922b40 ip 00007fb6100d55e2 sp 00007ffef0922b10 error 6 in libldap_r-2.4.so.2.8.3[7fb6100c2000+4d000]
Jul 13 09:04:44 hostname kernel: [1567680.722195] php5-fpm[10599]: segfault at 7ffef0922b40 ip 00007fb6100d55e2 sp 00007ffef0922b10 error 6 in libldap_r-2.4.so.2.8.3[7fb6100c2000+4d000]
Jul 13 09:05:16 hostname kernel: [1567712.781160] php5-fpm[10608]: segfault at 7ffef0922b40 ip 00007fb6100d55e2 sp 00007ffef0922b10 error 6 in libldap_r-2.4.so.2.8.3[7fb6100c2000+4d000]
Jul 13 09:05:48 hostname kernel: [1567744.849465] php5-fpm[10653]: segfault at 7ffef0922b40 ip 00007fb6100d55e2 sp 00007ffef0922b10 error 6 in libldap_r-2.4.so.2.8.3[7fb6100c2000+4d000]
Jul 13 09:06:19 hostname kernel: [1567776.664817] php5-fpm[10661]: segfault at 7ffef0922b40 ip 00007fb6100d55e2 sp 00007ffef0922b10 error 6 in libldap_r-2.4.so.2.8.3[7fb6100c2000+4d000]
Jul 13 09:06:52 hostname kernel: [1567808.746284] php5-fpm[10673]: segfault at 7ffef0922b40 ip 00007fb6100d55e2 sp 00007ffef0922b10 error 6 in libldap_r-2.4.so.2.8.3[7fb6100c2000+4d000]
Jul 13 09:07:24 hostname kernel: [1567840.915549] php5-fpm[10681]: segfault at 7ffef0922b40 ip 00007fb6100d55e2 sp 00007ffef0922b10 error 6 in libldap_r-2.4.so.2.8.3[7fb6100c2000+4d000]
Jul 13 09:07:56 hostname kernel: [1567872.782323] php5-fpm[10683]: segfault at 7ffef0922b40 ip 00007fb6100d55e2 sp 00007ffef0922b10 error 6 in libldap_r-2.4.so.2.8.3[7fb6100c2000+4d000]
Jul 13 09:08:28 hostname kernel: [1567904.752068] php5-fpm[10690]: segfault at 7ffef0922b40 ip 00007fb6100d55e2 sp 00007ffef0922b10 error 6 in libldap_r-2.4.so.2.8.3[7fb6100c2000+4d000]
```

**Comment by MorrisJobke** [comment]
cc @blizzz

**Comment by DeepDiver1975** [comment]
> php5-fpm

@benwilliams can you try to reproduce this with mod_php please? THX

What version of php are you using?

**Comment by benwilliams** [comment]
All packages are up to date so php is 5.5.9+dfsg-1ubuntu4.11

Installed mod_php instead but the effected users still cannot login. Apache uses 100% for about 20s then returns HTTP 200 with login screen. If php memory_limit is not sufficient it exhausts the limit. No segfault is logged when using mod_php.

The ldap server is logging the queries generated by owncloud. When the effected user attempts to login, thousands of repeated queries for SRCH attr=jpegPhoto are generated on another ldap user that is not the one trying to login.

**Comment by benwilliams** [comment]
This seems to be a workaround that has allowed them to login now.
```
/var/www/owncloud/apps/user_ldap/lib/user# diff user.php /tmp/user.php  -u
--- user.php	2015-07-15 00:02:00.149989842 +0000
+++ /tmp/user.php	2015-07-15 00:01:52.934217940 +0000
@@ -173,7 +173,8 @@
 			}
 		}
 
-		return $this->avatarImage;
+		#return $this->avatarImage;
+		return false;
 	}
 
 	/**

```

**Comment by blizzz** [comment]
Is that all the log you have? Can you  check the owncloud.log in your data folder, please?

Currently it does not seem that there were significant changes or new calls to getAvatarImage() respectively canChangeAvatar() of user_ldap and update(), which triggers that one.

**Comment by Nick-Lock** [comment]
This has affected our installation as well, and the above patch corrects the problem.

Ubuntu 14.04.2 LTS
php5 5.5.9+dfsg-1ubuntu4.11
php5-ldap 5.5.9+dfsg-1ubuntu4.11
libldap-2.4-2 2.4.31-1+nmu2ubuntu8.1
apache2 2.4.7-1ubuntu4.4
(and apache2-mpm-prefork 2.4.7-1ubuntu4.4)

Owncloud 8.1.0-2 from the OpenSuse repository:
root@owncloud:/etc/apt# cat ./sources.list.d/owncloud.list
deb http://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_14.04/ /


owncloud.log shows many repetitions of:

{"reqId":"c2Y1ShCQTpOqngAARGO7","remoteAddr":"82.xxx.212.195","app":"PHP","message":"ldap_control_paged_result_response(): Result is: No such object (32) at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/ldap.php#63","level":3,"time":"2015-07-15T15:21:58+00:00"}

Other than that, I don't have any additional information at this time :(

**Comment by blizzz** [comment]
@Nick-Lock anything else in the log?

**Comment by Nick-Lock** [comment]
Actually, there is (now I look a little further back)!

Interspersed in the blocks of the above lines are entries like these:



{"reqId":"B2kQcns92zp15vX9AsrM","remoteAddr":"82.xxx.13.81","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Doctrine\\\\DBAL\\\\Exception\\\\DriverException: An exception occurred while executing 'SELECT `uid`, `displayname` FROM `oc_users` WHERE LOWER(`uid`) = LOWER(?)' with params [\\\"d2a8e508-efc8-1033-8b1d-9d18beeb60f2\\\"]:\\n\\nSQLSTATE[HY000]: General error: 2006 MySQL server has gone away\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/remote.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(135): handleException(Object(Doctrine\\\\DBAL\\\\Exception\\\\DriverException))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/remote.php\",\"Line\":62}","level":4,"time":"2015-07-15T14:49:21+00:00"}
{"reqId":"KTtlaAJzqFqEJVnj4rW\/","remoteAddr":"82.xxx.212.195","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Doctrine\\\\DBAL\\\\Exception\\\\DriverException: An exception occurred while executing 'SELECT `configvalue` FROM `oc_preferences` WHERE `userid` = ? AND `appid` = ? AND `configkey` = ?' with params [\\\"d2a8e508-efc8-1033-8b1d-9d18beeb60f2\\\", \\\"settings\\\", \\\"email\\\"]:\\n\\nSQLSTATE[HY000]: General error: 2006 MySQL server has gone away\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#1 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php\",\"Line\":129}","level":4,"time":"2015-07-15T14:49:21+00:00"}
{"reqId":"BsF1YjWVzzzFxtwkzKjo","remoteAddr":"192.xxx.2.60","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Doctrine\\\\DBAL\\\\Exception\\\\DriverException: An exception occurred while executing 'SELECT `uid`, `displayname` FROM `oc_users` WHERE LOWER(`uid`) = LOWER(?)' with params [\\\"d2a8e508-efc8-1033-8b1d-9d18beeb60f2\\\"]:\\n\\nSQLSTATE[HY000]: General error: 2006 MySQL server has gone away\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#1 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php\",\"Line\":129}","level":4,"time":"2015-07-15T14:49:21+00:00"}
{"reqId":"uWSI+XARmlhtWozLWNKR","remoteAddr":"192.xxx.2.68","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Doctrine\\\\DBAL\\\\Exception\\\\DriverException: An exception occurred while executing 'SELECT `configvalue` FROM `oc_preferences` WHERE `userid` = ? AND `appid` = ? AND `configkey` = ?' with params [\\\"d2a8e508-efc8-1033-8b1d-9d18beeb60f2\\\", \\\"settings\\\", \\\"email\\\"]:\\n\\nSQLSTATE[HY000]: General error: 2006 MySQL server has gone away\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#1 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php\",\"Line\":129}","level":4,"time":"2015-07-15T14:49:21+00:00"}


(accesses from both our public IPs and our internal network, IPs obfuscated again)

I'd be happy to email you a full copy of the log file if cutting and pasting excerpts here isn't the right way to do it.

**Comment by blizzz** [comment]
> MySQL server has gone away

o.O That's also somewhat strange. @benwilliams do you see the same?

@benwilliams @Nick-Lock how did you do your upgrade?

**Comment by Nick-Lock** [comment]
apt-get dist-upgrade (!)

Here's the list of packages that were updated:

Start-Date: 2015-07-14  09:46:56
Commandline: apt-get dist-upgrade
Install: owncloud-app-encryption:amd64 (8.1.0-2, automatic)
Upgrade: bind9-host:amd64 (9.9.5.dfsg-3ubuntu0.2, 9.9.5.dfsg-3ubuntu0.3), liblwres90:amd64 (9.9.5.dfsg-3ubuntu0.2, 9.9.5.dfsg-3ubuntu0.3), owncloud-app-files-external:amd64 (8.0.4-1, 8.1.0-2), owncloud-app-files-locking:amd64 (8.0.4-1, 8.1.0-2), libdns100:amd64 (9.9.5.dfsg-3ubuntu0.2, 9.9.5.dfsg-3ubuntu0.3), python-samba:amd64 (4.1.6+dfsg-1ubuntu2.14.04.7, 4.1.6+dfsg-1ubuntu2.14.04.8), libisccfg90:amd64 (9.9.5.dfsg-3ubuntu0.2, 9.9.5.dfsg-3ubuntu0.3), libbind9-90:amd64 (9.9.5.dfsg-3ubuntu0.2, 9.9.5.dfsg-3ubuntu0.3), owncloud:amd64 (8.0.4-1, 8.1.0-2), owncloud-3rdparty:amd64 (8.0.4-1, 8.1.0-2), owncloud-app-user-external:amd64 (8.0.4-1, 8.1.0-2), owncloud-app-files-trashbin:amd64 (8.0.4-1, 8.1.0-2), owncloud-app-files-sharing:amd64 (8.0.4-1, 8.1.0-2), grub-common:amd64 (2.02~beta2-9ubuntu1.2, 2.02~beta2-9ubuntu1.3), dh-python:amd64 (1.20140128-1ubuntu8, 1.20140128-1ubuntu8.1), owncloud-app-firstrunwizard:amd64 (8.0.4-1, 8.1.0-2), owncloud-server:amd64 (8.0.4-1, 8.1.0-2), owncloud-app-files-pdfviewer:amd64 (8.0.4-1, 8.1.0-2), owncloud-app-activity:amd64 (8.0.4-1, 8.1.0-2), owncloud-app-files-texteditor:amd64 (8.0.4-1, 8.1.0-2), dnsutils:amd64 (9.9.5.dfsg-3ubuntu0.2, 9.9.5.dfsg-3ubuntu0.3), owncloud-app-provisioning-api:amd64 (8.0.4-1, 8.1.0-2), grub2-common:amd64 (2.02~beta2-9ubuntu1.2, 2.02~beta2-9ubuntu1.3), libnss3-nssdb:amd64 (3.17.4-0ubuntu0.14.04.1, 3.19.2-0ubuntu0.14.04.1), owncloud-app-user-webdavauth:amd64 (8.0.4-1, 8.1.0-2), owncloud-app-templateeditor:amd64 (8.0.4-1, 8.1.0-2), owncloud-app-files-versions:amd64 (8.0.4-1, 8.1.0-2), samba-common-bin:amd64 (4.1.6+dfsg-1ubuntu2.14.04.7, 4.1.6+dfsg-1ubuntu2.14.04.8), owncloud-app-files:amd64 (8.0.4-1, 8.1.0-2), samba-libs:amd64 (4.1.6+dfsg-1ubuntu2.14.04.7, 4.1.6+dfsg-1ubuntu2.14.04.8), libnss3:amd64 (3.17.4-0ubuntu0.14.04.1, 3.19.2-0ubuntu0.14.04.1), owncloud-app-gallery:amd64 (8.0.4-1, 8.1.0-2), owncloud-config-apache:amd64 (8.0.4-1, 8.1.0-2), grub-pc-bin:amd64 (2.02~beta2-9ubuntu1.2, 2.02~beta2-9ubuntu1.3), owncloud-app-external:amd64 (8.0.4-1, 8.1.0-2), grub-pc:amd64 (2.02~beta2-9ubuntu1.2, 2.02~beta2-9ubuntu1.3), smbclient:amd64 (4.1.6+dfsg-1ubuntu2.14.04.7, 4.1.6+dfsg-1ubuntu2.14.04.8), linux-firmware:amd64 (1.127.12, 1.127.13), owncloud-app-files-videoviewer:amd64 (8.0.4-1, 8.1.0-2), libwbclient0:amd64 (4.1.6+dfsg-1ubuntu2.14.04.7, 4.1.6+dfsg-1ubuntu2.14.04.8), owncloud-app-user-ldap:amd64 (8.0.4-1, 8.1.0-2), samba-common:amd64 (4.1.6+dfsg-1ubuntu2.14.04.7, 4.1.6+dfsg-1ubuntu2.14.04.8), libisccc90:amd64 (9.9.5.dfsg-3ubuntu0.2, 9.9.5.dfsg-3ubuntu0.3), libsmbclient:amd64 (4.1.6+dfsg-1ubuntu2.14.04.7, 4.1.6+dfsg-1ubuntu2.14.04.8), libisc95:amd64 (9.9.5.dfsg-3ubuntu0.2, 9.9.5.dfsg-3ubuntu0.3)
Remove: owncloud-app-files-encryption:amd64 (8.0.4-1)
End-Date: 2015-07-14  09:47:39

**Comment by johansmitsnl** [comment]
I can confirm the same issue, but unknown to me witch user is responsible for this.
I run a Ubuntu 14.04 and the CRON.php does not complete and I get an error in syslog.

```
kernel: [7710065.974050] php[30863]: segfault at 7ffed0286e30 ip 00007fc55d4265e2 sp 00007ffed0286e00 error 6 in libldap_r-2.4.so.2.8.3[7fc55d413000+4d000]

ii  libapache2-mod-php5                   5.5.9+dfsg-1ubuntu4.11               amd64        server-side, HTML-embedded scripting language (Apache 2 module)
ii  php-apc                               4.0.2-2build1                        all          APC User Cache for PHP 5 (transitional package)
ii  php-auth                              1.6.4-1                              all          Creating an authentication system
ii  php-auth-sasl                         1.0.6-1                              all          Abstraction of various SASL mechanism responses
ii  php-db                                1.7.14-2                             all          PHP PEAR Database Abstraction Layer
ii  php-http-request                      1.4.4-4                              all          PEAR class to provide an easy way to perform HTTP requests
ii  php-log                               1.12.7-1                             all          Logging Framework
ii  php-mail                              1.2.0-6                              all          Class that provides multiple interfaces for sending emails
ii  php-mail-mime                         1.8.8-1                              all          PHP PEAR module for creating MIME messages
ii  php-mdb2                              2.5.0b5-1                            all          merge of the PEAR DB and Metabase php database abstraction layers
ii  php-net-dime                          1.0.2-2                              all          class that implements DIME encoding
ii  php-net-smtp                          1.6.1-1                              all          PHP PEAR module implementing SMTP protocol
ii  php-net-socket                        1.0.14-1                             all          PHP PEAR Network Socket Interface module
ii  php-net-url                           1.0.15-3                             all          easy parsing of Urls
ii  php-pear                              5.5.9+dfsg-1ubuntu4.11               all          PEAR - PHP Extension and Application Repository
ii  php-soap                              0.13.0-1                             all          SOAP Client/Server class for PHP
ii  php5                                  5.5.9+dfsg-1ubuntu4.11               all          server-side, HTML-embedded scripting language (metapackage)
ii  php5-apcu                             4.0.2-2build1                        amd64        APC User Cache for PHP 5
ii  php5-cli                              5.5.9+dfsg-1ubuntu4.11               amd64        command-line interpreter for the php5 scripting language
ii  php5-common                           5.5.9+dfsg-1ubuntu4.11               amd64        Common files for packages built from the php5 source
ii  php5-curl                             5.5.9+dfsg-1ubuntu4.11               amd64        CURL module for php5
ii  php5-gd                               5.5.9+dfsg-1ubuntu4.11               amd64        GD module for php5
ii  php5-imagick                          3.1.2-1build1                        amd64        ImageMagick module for php5
ii  php5-imap                             5.4.6-0ubuntu5                       amd64        IMAP module for php5
ii  php5-intl                             5.5.9+dfsg-1ubuntu4.11               amd64        internationalisation module for php5
ii  php5-json                             1.3.2-2build1                        amd64        JSON module for php5
ii  php5-ldap                             5.5.9+dfsg-1ubuntu4.11               amd64        LDAP module for php5
ii  php5-mcrypt                           5.4.6-0ubuntu5                       amd64        MCrypt module for php5
ii  php5-mysql                            5.5.9+dfsg-1ubuntu4.11               amd64        MySQL module for php5
ii  php5-pgsql                            5.5.9+dfsg-1ubuntu4.11               amd64        PostgreSQL module for php5
ii  php5-readline                         5.5.9+dfsg-1ubuntu4.11               amd64        Readline module for php5
ii  php5-sqlite                           5.5.9+dfsg-1ubuntu4.11               amd64        SQLite module for php5
```

Disable the jpegPhoto retrieval lets the cron job finish but without a photo. Setting the code back, the cron keeps running for me now.

**Comment by benwilliams** [comment]
@blizzz upgrade was done with `apt-get dist-upgrade`. Nothing is logged to owncloud.log during the login failure for the effected users.

**Comment by blizzz** [comment]
> Disable the jpegPhoto retrieval lets the cron job finish but without a photo. Setting the code back, the cron keeps running for me now, can it have something to do with the type of task it needs to run on each run?

It will actually execute  an LDAP job once an hour, IIRC.

**Comment by blizzz** [comment]
@benwilliams @johansmitsnl @Nick-Lock Could you check whether https://github.com/owncloud/core/pull/17464 fixes your issue?

**Comment by Nick-Lock** [comment]
Might need to wait until the back of the afternoon, as we're a little stretched right now - but I'll give it a go.

**Comment by benwilliams** [comment]
With [this version](https://github.com/owncloud/core/blob/eb32b4fd278024861093ce41343afcd9e9c6da38/apps/user_ldap/lib/user/user.php) of the file installed it still crashed with the segfault.

**Comment by Nick-Lock** [comment]
Interesting results at my end, but no real progress. After reverting the code last night, and having the system continue working, I arrived into the office this morning to find that it had started segfaulting while logging in again. Odd... is there any PHP or LDAP caching going on that wouldn't be restarted by merely restarting the Apache service?

In this state, replacing the owncloud installation with a downloaded version of #17464 resulted in the site only displaying:

```Composer autoloader not found, unable to continue. Check the folder "3rdparty".```

and as we have users on the system I can't perform any more experiments right now, and have gone back to using the patched version from before in order to get through today alive :)

I also notice that there is a package update available, from version 8.1.0-2 to version 8.1.0-3; I'll try this later on this afternoon.

**Comment by blizzz** [comment]
@Nick-Lock 

About LDAP Caching read: https://doc.owncloud.org/server/8.1/admin_manual/configuration_user/user_auth_ldap.html#caching

Also mind https://github.com/owncloud/core/issues/17631#issuecomment-121926031 about the cron jobs.

If you get ownCloud from git, ideally use ``git clone`` and subsequentially ``git submodule init`` and ``git submodule update``, because the 3rdparty contents are part of a different repository.

**Comment by blizzz** [comment]
@ Everybody:

would it be possible for you to get a backtrace (e.g. using PHP's xdebug)?  So far I was not able to reproduce it :-(

**Comment by Nick-Lock** [comment]
Thanks for the extra info above.

If I can re-break the installation, would a gdb backtrace be any use? I managed to get one of those from Apache yesterday, but because I'm dumb I didn't save it...

**Comment by blizzz** [comment]
I doubt, I'd like to see the PHP execution paths that lead thereto. GDB'ing Apache won't give that info, probably?

**Comment by Nick-Lock** [comment]
OK, if I can break it again I'll go down the xdebug route.

It's been working for the past 6 hours without the patch from above, but to fix the errors I quoted I also removed APCu, installed Memcached and added the memcache.local setting to config.php . I've reverted *these* changes as well now, but it's still working fine :)

**Comment by Nick-Lock** [comment]
OK, it's broken again. I've installed xdebug from PECL, enabled it, and now even the Owncloud login page doesn't work (shows a white screen).

The apache error log is now showing a LOT of this:

http://pastebin.com/XvemV0Lv

(not sure if this will help or not)

**Comment by blizzz** [comment]
@Nick-Lock That may be it!

@ All: do you all have encryption enabled?

**Comment by Nick-Lock** [comment]
Server side encryption is disabled on our installation - the checkbox under Admin --> Server-side encryption is not checked.

We are running under HTTPS, but I don't think that's what you were after?

No cache is configured in config/config.php .


Apologies for not resetting the maximum nesting level in the XDebug logging - I'll set it higher to capture the full trace next time.

**Comment by johansmitsnl** [comment]
Testing the try fix as suggested for the cron.

Running without encryption here.

**Comment by blizzz** [comment]
@Nick-Lock no, that's perfect, thank you!

The ever-repeating steps are those:

```
121. OC\\User\\Manager->userExists() /var/www/owncloud/lib/private/encryption/util.php:374
122. OC\\User\\Manager->get() /var/www/owncloud/lib/private/user/manager.php:161
123. OCA\\user_ldap\\USER_LDAP->userExists() /var/www/owncloud/lib/private/user/manager.php:132
124. OCA\\user_ldap\\lib\\user\\User->update() /var/www/owncloud/apps/user_ldap/user_ldap.php:218
125. OCA\\user_ldap\\lib\\user\\User->updateAvatar() /var/www/owncloud/apps/user_ldap/lib/user/user.php:133
126. OCA\\user_ldap\\lib\\user\\User->setOwnCloudAvatar() /var/www/owncloud/apps/user_ldap/lib/user/user.php:319
127. OC\\Avatar->set() /var/www/owncloud/apps/user_ldap/lib/user/user.php:346
128. OC\\Files\\View->unlink() /var/www/owncloud/lib/private/avatar.php:118
129. OC\\Files\\View->basicOperation() /var/www/owncloud/lib/private/files/view.php:600
130. OCA\\Files_Trashbin\\Storage->unlink() /var/www/owncloud/lib/private/files/view.php:1006
131. OCA\\Files_Trashbin\\Storage->doDelete() /var/www/owncloud/apps/files_trashbin/lib/storage.php:89
132. call_user_func_array:{/var/www/owncloud/apps/files_trashbin/lib/storage.php:136}() /var/www/owncloud/apps/files_trashbin/lib/storage.php:136
133. OC\\Files\\Storage\\Wrapper\\Encryption->unlink() /var/www/owncloud/apps/files_trashbin/lib/storage.php:136
134. OC\\Encryption\\Util->isExcluded() /var/www/owncloud/lib/private/files/storage/wrapper/encryption.php:214
135. OC\\User\\Manager->userExists() /var/www/owncloud/lib/private/encryption/util.php:374
```

a userExists checks goes around. In the LDAP backend, a successful user exists also updates the user. However, before it does, it will cache the result, to just return this next time. But with no cache available or the cache turned off, the whole procedure is repeated and ends up in an infinite loop.

Ok, maybe encryption does not play a role, but at least ``/var/www/owncloud/lib/private/encryption/util.php:374`` is involved. Now that's a core thing, so independent from the encryption app, anyway asking userExists() is totally fine, so that's not the problem. 

The problem is the missing cache when an avatar is being updated. This did not happen in 8.0, because we had a fallback cache that was removed.

OTOH we also flag whether the avatar was already refreshed in the runtime. So it should happen once only, anyway.  Except, the user object is created newly, which should not happen either.

We're very close, and I should be able to reproduce this now.

**Comment by blizzz** [comment]
Gotcha. Runtime caching the user manager was broken. Fix will be there in no time.

**Comment by johansmitsnl** [comment]
@blizzz testing the fix with cron job also now.

**Comment by blizzz** [comment]
@johansmitsnl the other PR mentioned before will have no influence.

@ all: Please test the real fix: https://github.com/owncloud/core/pull/17723
