### ISSUE TITLE
Yum update requires php54

### ISSUE THREAD

**Issue by rasusmilch** [owncloud/core#17645]
Running a CentOS 7 server. Have installed OwnCloud and am running ownCloud 8.0.4 (stable). Attempting to upgrade via yum complains. I have read about using IUS yum replace, and they have php56u. However this is a production server and I'm wary of replacing packages.

yum update
Loaded plugins: priorities
100 packages excluded due to repository priority protections
Resolving Dependencies
--> Running transaction check
---> Package owncloud-3rdparty.noarch 0:8.0.4-15.1 will be updated
---> Package owncloud-3rdparty.noarch 0:8.1.0-13.1 will be an update
---> Package owncloud-app-activity.noarch 0:8.0.4-15.1 will be updated
---> Package owncloud-app-activity.noarch 0:8.1.0-13.1 will be an update
---> Package owncloud-app-external.noarch 0:8.0.4-15.1 will be updated
---> Package owncloud-app-external.noarch 0:8.1.0-13.1 will be an update
---> Package owncloud-app-files.noarch 0:8.0.4-15.1 will be updated
---> Package owncloud-app-files.noarch 0:8.1.0-13.1 will be an update
---> Package owncloud-app-files_external.noarch 0:8.0.4-15.1 will be updated
---> Package owncloud-app-files_external.noarch 0:8.1.0-13.1 will be an update
---> Package owncloud-app-files_locking.noarch 0:8.0.4-15.1 will be updated
---> Package owncloud-app-files_locking.noarch 0:8.1.0-13.1 will be an update
---> Package owncloud-app-files_pdfviewer.noarch 0:8.0.4-15.1 will be updated
---> Package owncloud-app-files_pdfviewer.noarch 0:8.1.0-13.1 will be an update
---> Package owncloud-app-files_sharing.noarch 0:8.0.4-15.1 will be updated
---> Package owncloud-app-files_sharing.noarch 0:8.1.0-13.1 will be an update
---> Package owncloud-app-files_texteditor.noarch 0:8.0.4-15.1 will be updated
---> Package owncloud-app-files_texteditor.noarch 0:8.1.0-13.1 will be an update
---> Package owncloud-app-files_trashbin.noarch 0:8.0.4-15.1 will be updated
---> Package owncloud-app-files_trashbin.noarch 0:8.1.0-13.1 will be an update
---> Package owncloud-app-files_versions.noarch 0:8.0.4-15.1 will be updated
---> Package owncloud-app-files_versions.noarch 0:8.1.0-13.1 will be an update
---> Package owncloud-app-files_videoviewer.noarch 0:8.0.4-15.1 will be updated
---> Package owncloud-app-files_videoviewer.noarch 0:8.1.0-13.1 will be an update
---> Package owncloud-app-firstrunwizard.noarch 0:8.0.4-15.1 will be updated
---> Package owncloud-app-firstrunwizard.noarch 0:8.1.0-13.1 will be an update
---> Package owncloud-app-gallery.noarch 0:8.0.4-15.1 will be updated
---> Package owncloud-app-gallery.noarch 0:8.1.0-13.1 will be an update
---> Package owncloud-app-provisioning_api.noarch 0:8.0.4-15.1 will be updated
---> Package owncloud-app-provisioning_api.noarch 0:8.1.0-13.1 will be an update
---> Package owncloud-app-templateeditor.noarch 0:8.0.4-15.1 will be updated
---> Package owncloud-app-templateeditor.noarch 0:8.1.0-13.1 will be an update
---> Package owncloud-app-user_external.noarch 0:8.0.4-15.1 will be updated
---> Package owncloud-app-user_external.noarch 0:8.1.0-13.1 will be an update
---> Package owncloud-app-user_ldap.noarch 0:8.0.4-15.1 will be updated
---> Package owncloud-app-user_ldap.noarch 0:8.1.0-13.1 will be an update
---> Package owncloud-app-user_webdavauth.noarch 0:8.0.4-15.1 will be updated
---> Package owncloud-app-user_webdavauth.noarch 0:8.1.0-13.1 will be an update
---> Package owncloud-server.noarch 0:8.0.4-15.1 will be updated
--> Processing Dependency: owncloud-server-core = 8.0.4 for package: owncloud-app-files_encryption-8.0.4-15.1.noarch
--> Processing Dependency: owncloud-server-core = 8.0.4 for package: owncloud-app-files_encryption-8.0.4-15.1.noarch
---> Package owncloud-server.noarch 0:8.1.0-13.1 will be an update
--> Processing Dependency: owncloud-app-encryption = 8.1.0 for package: owncloud-server-8.1.0-13.1.noarch
--> Running transaction check
---> Package owncloud-app-encryption.noarch 0:8.1.0-13.1 will be installed
---> Package owncloud-server-scl-php54.noarch 0:8.1.0-13.1 will be installed
--> Processing Dependency: php54 for package: owncloud-server-scl-php54-8.1.0-13.1.noarch
--> Processing Dependency: php54-php-process for package: owncloud-server-scl-php54-8.1.0-13.1.noarch
--> Processing Dependency: php54-php-zip for package: owncloud-server-scl-php54-8.1.0-13.1.noarch
--> Processing Dependency: php54-php-xml for package: owncloud-server-scl-php54-8.1.0-13.1.noarch
--> Processing Dependency: php54-php-mbstring for package: owncloud-server-scl-php54-8.1.0-13.1.noarch
--> Processing Dependency: php54-php for package: owncloud-server-scl-php54-8.1.0-13.1.noarch
--> Processing Dependency: php54-php-gd for package: owncloud-server-scl-php54-8.1.0-13.1.noarch
--> Processing Dependency: php54-php-common for package: owncloud-server-scl-php54-8.1.0-13.1.noarch
--> Processing Dependency: php54-php-pdo for package: owncloud-server-scl-php54-8.1.0-13.1.noarch
--> Processing Dependency: php54-php-posix for package: owncloud-server-scl-php54-8.1.0-13.1.noarch
--> Finished Dependency Resolution
Error: Package: owncloud-server-scl-php54-8.1.0-13.1.noarch (isv_ownCloud_community)
           Requires: php54-php-mbstring
Error: Package: owncloud-server-scl-php54-8.1.0-13.1.noarch (isv_ownCloud_community)
           Requires: php54-php-zip
Error: Package: owncloud-server-scl-php54-8.1.0-13.1.noarch (isv_ownCloud_community)
           Requires: php54-php-gd
Error: Package: owncloud-server-scl-php54-8.1.0-13.1.noarch (isv_ownCloud_community)
           Requires: php54-php-xml
Error: Package: owncloud-server-scl-php54-8.1.0-13.1.noarch (isv_ownCloud_community)
           Requires: php54-php-common
Error: Package: owncloud-server-scl-php54-8.1.0-13.1.noarch (isv_ownCloud_community)
           Requires: php54-php-process
Error: Package: owncloud-server-scl-php54-8.1.0-13.1.noarch (isv_ownCloud_community)
           Requires: php54
Error: Package: owncloud-server-scl-php54-8.1.0-13.1.noarch (isv_ownCloud_community)
           Requires: php54-php-pdo
Error: Package: owncloud-server-scl-php54-8.1.0-13.1.noarch (isv_ownCloud_community)
           Requires: php54-php-posix
Error: Package: owncloud-server-scl-php54-8.1.0-13.1.noarch (isv_ownCloud_community)
           Requires: php54-php
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

#yum info php
Loaded plugins: priorities, replace
100 packages excluded due to repository priority protections
Installed Packages
Name        : php
Arch        : x86_64
Version     : 5.4.16
Release     : 36.el7_1
Size        : 4.4 M
Repo        : installed
From repo   : sl-security
Summary     : PHP scripting language for creating dynamic web sites
URL         : http://www.php.net/
License     : PHP and Zend and BSD
Description : PHP is an HTML-embedded scripting language. PHP attempts to make it
            : easy for developers to write dynamically generated web pages. PHP also
            : offers built-in database integration for several commercial and
            : non-commercial database management systems, so writing a
            : database-enabled webpage with PHP is fairly simple. The most common
            : use of PHP coding is probably as a replacement for CGI scripts.
            : 
            : The php package contains the module (often referred to as mod_php)
            : which adds support for the PHP language to Apache HTTP Server.

And here is php info                                                                                                                                                    
phpinfo()
PHP Version => 5.4.16

**Comment by DeepDiver1975** [comment]
@jnweiger @carlaschroder is the proper installation of php54 on Centos documented somewhere? Please link - THX

**Comment by carlaschroder** [comment]
I thought CentOS 4 shipped with PHP 5.4? At any rate CentOS has multiple third-party repos to get PHP 5.4. The official Red Hat repo is SCL. These are the instructions for oC enterprise customers running  CentOS 6. I haven't tested them on CentOS 7. I'll test &  add them to the community documentation tomorrow.

CentOS 6, PHP 5.3 and PHP 5.4
-----------------------------
 
Note that CentOS 6 ships with PHP 5.3. This is supported in ownCloud 7, though 
we recommend PHP 5.4. PHP 5.4 is required for ownCloud 8. To upgrade to PHP 5.4, use the 
Software Collections (SCL) repository. SCL is the only supported repository in 
Red Hat Enterprise Linux 6 for installing PHP 5.4.  

First install the SCL repo:

 yum install centos-release-SCL
 
Then install PHP 5.4 and these modules: 

 yum install php54 php54-php php54-php-gd php54-php-mbstring
 
You must also install the updated database module. This installs the new PHP 
5.4 module for MySQL/MariaDB: 
 
 yum install php54-php-mysqlnd
 
Activate the new PHP version permanently:
 
 source /opt/rh/php54/enable
 
Disable loading the old PHP 5.3 Apache module: 

 mv /etc/httpd/conf.d/php.conf /etc/httpd/conf.d/php.conf/old
 
You should have a /etc/httpd/conf.d/php54-php.conf file, which loads the 
correct PHP 5.4 module for Apache.

Finally, restart Apache:
 
 service httpd restart

Verify with phpinfo that your Apache server is using PHP 5.4 and loading the 
correct modules; see   
https://doc.owncloud.com/server/8.0/admin_manual/configuration_server/performance_tuning.html#php-version-and-information
performance_tuning.html to learn how to use phpinfo.

**Comment by carlaschroder** [comment]
Sorry, I see you do have PHP 5.4 and SCL already. I'll look at this again in the morning.

**Comment by carlaschroder** [comment]
@rasusmilch, not sure what's going on with your system. I did some test runs with clean installations of RHEL 7 and CentOS 7, first installating oC 8.05, and then upgrading to stable 8.1 ( 8.1.0-14.1). I didn't take any extra steps, but only installed the base operating systems, and then let yum pull in all the oC dependencies. I had no issues (and on clean systems with little ownCloud data I sure hope there would not be issues). My oC versions are slightly different from yours, but I doubt that is the problem. My PHP version is identical to yours. 

Sorry I can't be more helpful.

**Comment by rasusmilch** [comment]
@carlaschroder, I figured it out. At some point in the past I enabled yum priorities. I disabled it after doing an update first. After disabling it, I reran yum update and the only updates were for owncloud which yum then happily updated successfully. I'm unsure what was blocking it, as the only thing it did update afterwards was owncloud, not a

I can log into the website and my clients connect happily so far. I see a message about owncloud working better if it's connected to the internet. Iron considering this is a VPS and I'm a few thousand miles away working on it.

However, my issue is solved. Thank you for your time and forgive my incompetence!

Dependencies Resolved

=============================================================================================================================================================================================================================================
 Package                                                            Arch                                       Version                                                      Repository                                                  Size
=============================================================================================================================================================================================================================================
Installing:
 owncloud                                                           noarch                                     8.1.0-14.1                                                   isv_ownCloud_community                                      23 k
     replacing  owncloud-app-files_encryption.noarch 8.0.4-15.1
Updating:
 owncloud-3rdparty                                                  noarch                                     8.1.0-14.1                                                   isv_ownCloud_community                                     3.2 M
 owncloud-app-activity                                              noarch                                     8.1.0-14.1                                                   isv_ownCloud_community                                     106 k
 owncloud-app-external                                              noarch                                     8.1.0-14.1                                                   isv_ownCloud_community                                      55 k
 owncloud-app-files                                                 noarch                                     8.1.0-14.1                                                   isv_ownCloud_community                                     254 k
 owncloud-app-files_external                                        noarch                                     8.1.0-14.1                                                   isv_ownCloud_community                                     803 k
 owncloud-app-files_locking                                         noarch                                     8.1.0-14.1                                                   isv_ownCloud_community                                      20 k
 owncloud-app-files_pdfviewer                                       noarch                                     8.1.0-14.1                                                   isv_ownCloud_community                                     1.7 M
 owncloud-app-files_sharing                                         noarch                                     8.1.0-14.1                                                   isv_ownCloud_community                                     187 k
 owncloud-app-files_texteditor                                      noarch                                     8.1.0-14.1                                                   isv_ownCloud_community                                     897 k
 owncloud-app-files_trashbin                                        noarch                                     8.1.0-14.1                                                   isv_ownCloud_community                                      74 k
 owncloud-app-files_versions                                        noarch                                     8.1.0-14.1                                                   isv_ownCloud_community                                      56 k
 owncloud-app-files_videoviewer                                     noarch                                     8.1.0-14.1                                                   isv_ownCloud_community                                     184 k
 owncloud-app-firstrunwizard                                        noarch                                     8.1.0-14.1                                                   isv_ownCloud_community                                      71 k
 owncloud-app-gallery                                               noarch                                     8.1.0-14.1                                                   isv_ownCloud_community                                      71 k
 owncloud-app-provisioning_api                                      noarch                                     8.1.0-14.1                                                   isv_ownCloud_community                                      21 k
 owncloud-app-templateeditor                                        noarch                                     8.1.0-14.1                                                   isv_ownCloud_community                                      52 k
 owncloud-app-user_external                                         noarch                                     8.1.0-14.1                                                   isv_ownCloud_community                                      17 k
 owncloud-app-user_ldap                                             noarch                                     8.1.0-14.1                                                   isv_ownCloud_community                                     291 k
 owncloud-app-user_webdavauth                                       noarch                                     8.1.0-14.1                                                   isv_ownCloud_community                                      46 k
 owncloud-server                                                    noarch                                     8.1.0-14.1                                                   isv_ownCloud_community                                      17 M
 swig                                                               x86_64                                     2.0.11-3.1.el7.kolab_3.3                                     Kolab_3.3                                                  1.3 M
Installing for dependencies:
 owncloud-app-encryption                                            noarch                                     8.1.0-14.1                                                   isv_ownCloud_community                                     106 k
 owncloud-config-apache                                             noarch                                     8.1.0-14.1                                                   isv_ownCloud_community                                      15 k

Transaction Summary
=============================================================================================================================================================================================================================================
Install   1 Package  (+2 Dependent packages)
Upgrade  21 Packages

**Comment by carlaschroder** [comment]
Thanks for the followup, @rasusmilch, it's always good to have answers!
