### ISSUE TITLE
8.1.0: "Shared with..." button not working when clicking between "shared with/by you"

### ISSUE THREAD

**Issue by muonIT** [owncloud/core#17644]
Hi,
this bug is in 8.1.0. Tested browsers are Firefox 38.0.5 and IE11.

Reproduce:
Share a folder with someone and/or get a shared folder.
Click "Shared with you/Mit dir geteilt" at the lefthand side, then on the "Shared with/Geteilt mit ..." button next to a shared item.
This is important: While the textbox with infos regarding the who-shared-what-with is open, click on the lefthand  side on "Shared by you/Von dir geteilt". Now you can't click on "Shared with/Geteilt mit ..." in both menus anymore. Nothing happens if you click, no textbox comes up.
If you click on "Versions/Versionen" right in front of "Shared with/Geteilt mit ...", after that textbox has come up then the button starts working again.
Best regards,
Udo Puetz

**Comment by rullzer** [comment]
Mmmm seems like an issue with the window not being properly closed. Thus the UI still thinks there is already a share window open.

@PVince81 If I remember correctly we had (/have) this somewhere else as well.. Do you remember if (and how) we fixed that?

**Comment by PVince81** [comment]
If I remember well @dttpy observed this before, but can't find a matching ticket.

@rullzer in general closing dropdowns when clicking anywhere is often troublesome because some event handlers might stop propagation of the event.

**Comment by muonIT** [comment]
The box is not specific to either "shared by or with" - it's generic id="dropdown".
I just edited core/js/share.js in line 373 to this:
 var html = '<div id="dropdown'+itemSource+'"
i.e. added the +itemSource.
That way the dropdown Box is specific to each link. When I open a box then and, with the box still open, switch to the other sidebar, it works.
But: now the css isn't good, the box is misshapen. That's where my css/js foo ends.

**Comment by muonIT** [comment]
Ping @rullzer and @PVince81 - is my last comment of any use?

**Comment by rullzer** [comment]
@muonIT well your suggestion doesn't solve the problem it just moves it. The problem still persist if you then switch back to the original view and try to share the file. It basically breaks since we say that only 1 sharing dialogue can be open at a time. And since it is not properly closed. Stuff breaks :(

Hopefully we can address this when the right sidebar comes in: #17656

**Comment by PVince81** [comment]
Obsoleted by moving the share dialog into the sidebar in 8.2
