### ISSUE TITLE
OwnCloud v8 general errors

### ISSUE THREAD

**Issue by tx7** [owncloud/core#17647]
Hi guys,

I'm new to OwnCloud, and I just installed it on OpenMediaVault.
I being testing the OC, and it's working fine, but I got some errors in the OC web portal.
I been spent a few days search for solutions, but it didn't work out.
Hope someone can help me:

1. Error  PHP	Array to string conversion at /media/82468379-6874-47f3-9a21-615766f2ccab/www/owncloud/lib/private/template/functions.php#36

2. php does not seem to be setup properly to query system environment 
variables. The test with getenv("PATH") only returns an empty response.
I thought remove the line env [PATH] in /etc/php5/fpm/pool.d/www.conf , it should be fixed, but it isn't.

3. No memory cache has been configured. To enhance 
your performance please configure a memcache if available.

4. "Strict-Transport-Security" HTTP header is not configured to least 
"15768000" seconds.

5. Sometimes, this error: "unable to load template"

**Comment by RealRancor** [comment]
1. Please create a separate issue using the issue template provided here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version

2. See https://doc.owncloud.org/server/8.1/admin_manual/installation/source_installation.html?highlight=env#configuration-notes-to-php-fpm

3. See https://github.com/owncloud/core/blob/v8.1.0/config/config.sample.php#L834-L878 and https://doc.owncloud.org/server/8.1/admin_manual/configuration_server/config_sample_php_parameters.html#memory-caching-backend-configuration

4. See https://doc.owncloud.org/server/8.1/admin_manual/configuration_server/harden_server.html#enable-http-strict-transport-security

5. Please create a separate issue using the issue template provided here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version

**Comment by happyreacer** [comment]
to 2.
I have add the line env[PATH] = /usr/local/bin:/usr/bin:/bin in the php.ini 
no changes
everybody an other solution?

**Comment by tx7** [comment]
Hi RealRancor,

Thanks for the quick responses.

However, I still getting error for number 2, & 4.

4. I add this: <VirtualHost *:443>
   ServerName cloud.owncloud.com
   Header always add Strict-Transport-Security "max-age=15768000; includeSubDomains; preload"
</VirtualHost>  to 'apache2 default-ssl'  but didn't work out either.

**Comment by heavyt** [comment]
Had the same problem  For #4. This was what I forgot to do "Furthermore it shall be noted that this requires that the mod_headers extension is installed".

**Comment by tx7** [comment]
@heavyt,

I installed the headers, add the lines like the OC doc stated, restarted the server, still  have same error.
I even add my server name to default, and default ssl virtual host.
It didn't make a difference.

I don't know why OwnCloud have so many issues.
Even for advanced users, they still have issues. 

I think it would be easier if the dev have the options ready with a switch on or off in the script, which would make everybody life easier.

**Comment by RealRancor** [comment]
@tx7 You know that these are security warnings and recommendations which are provided by the Devs as an service to you? They just could remove all those recommendations and leave it up to you to configure your server securely??

**Comment by tx7** [comment]
I know what you're saying.
The doc instructions are lack of details. 
It stated that: "Furthermore it shall be noted that this requires that the mod_headers extension is installed."
However, it didn't stated how or the name of the headers.
Therefore, how people know what are they talking about.
Not everybody know what are the headers.

I'm not coming in here to argue about this, but if they giving instruction details, at least give full details.
Don't give half instructions, then make the users find out somewhere else.

**Comment by RealRancor** [comment]
If you think the instructions are missing you can request them here:

https://github.com/owncloud/documentation/issues
