### ISSUE TITLE
Let admins vote for apps from settings/apps

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#17649]
Now that admins can download apps from ownCloud again, there is very little chance that they will visit the app store again, unless something goes wrong.

Which means that apps will get downloaded, but won't get any votes, apart from their respective fan clubs or from fellow developers posting their own apps.

The problems
- admins are missing a quick way to assess the quality of an app
- devs need a good rating in order to get their apps approved

The best solution would be to be able to sign in/sign up from ownCloud and to be able to rate apps directly, by picking between 1 and 5 stars.

Not sure who handles settings/apps, but at least @LukasReschke for the inter system link.

**Comment by PVince81** [comment]
So this means that first the admin needs to be able to provide app store credentials. Ideally this should be oauth, not basic auth.
And then need to find out whether the app store has an API to rate apps. I guess it might have one because it's the same software as kde-look.org, and if I remember well you can rate wallpapers and other content directly from the desktop. Isn't it @karlitschek ?

**Comment by oparoz** [comment]
The API is described here:
http://freedesktop.org/wiki/Specifications/open-collaboration-services/

```
Syntax: /v1/content/vote/"contentid"
HTTP Method: POST
Arguments: contentid - Id of a content
POST Arguments: vote - The vote. "good" or "bad" (deprecated) or an integer between 0 to 100. 0 equals bad and 100 equals good
Result: status xml
Statuscodes:
100 - successful
101 - content not found
200 - too many API requests in the last 15 minutes from your IP address. please try again later.
Example: http://api.opendesktop.org/v1/content/vote/12345 with the POST variable vote=good Example:

ok
```

**Comment by PVince81** [comment]
@pmaier1 @hurradieweltgehtunter interesting for marketplace ?

**Comment by hurradieweltgehtunter** [comment]
Indeed. This is a topic for @felixheidecke / @patrickjahns / market app.
This is a workflow which will become more and more important - apart from voting. @oparoz is completely right, admins won't visit the marketplace very often. The market app needs to be enhanced to cover these things.

**Comment by patrickjahns** [comment]
Created an issue in market repository for tracking - closing
