### ISSUE TITLE
Database password in plain text in config.php when installed from command line

### ISSUE THREAD

**Issue by Neraste** [owncloud/core#17646]
Hi people

I've tried to install Owncloud 8.1.0 with command line (it works great), but the database password is stored in plain text in config.php file. On my previous OC setup (7.0.4,, installed with installation wizard), the password was stored salted.

### Steps to reproduce
Install Owncloud using command line.

### Expected behavior
Database password appears in config.php, but is salted and unreadable (as it does when using installation wizard).

### Actual behavior
Database password appears in plain text.

### Server configuration
OS: OpenSUSE 13.2 on Cubox-i ARMv7hl
Webserver: Nginx 1.8.0
Database: Mariadb 10.0.13-MariaDB openSUSE package
PHP version: 5.6.1-27.1
Owncloud version: 8.1.0 (fresh install)
Apps:

 - activity: 2.0.1
 - direct_menu: 0.3
 - files: 1.1.9
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - templateeditor: 0.1
 - updater: 0.6

Config file: problem happens during config file generation.
```php
<?php
$CONFIG = array (
  ...
  'trusted_domains' =>
  array (
    0 => 'localhost',
  ),
  'datadirectory' => '/srv/www/owncloud-8.1.0_debug/data',
  'overwrite.cli.url' => 'http://localhost',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'owncloud_debug',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud_debug_user',
  'dbpassword' => 'plain text here!!!',
  'logtimezone' => 'UTC',
  'installed' => true,
);
```
No external storage
No encryption
No user backend

### Client configuration
Browser: Mozilla Firefox 39
Operating system: MS Windows 7

**Comment by RealRancor** [comment]
Hi,

> On my previous OC setup (7.0.4,, installed with installation wizard), the password was stored salted.

database passwords where never hashed/salted in the config.php. This was just a strong generated password which looked like a hash.

**Comment by LukasReschke** [comment]
Exact. Closing as non-issue.
