### ISSUE TITLE
.htaccess is working but Owncloud keeps giving security warnings

### ISSUE THREAD

**Issue by KKyang** [owncloud/core#17652]
OS: Ubuntu 14.04
Owncloud version: 8.1
Updated from Owncloud 8.0.5
Using MySQL

I think my .htaccess is working because if I changed the upload limit size of .htaccess, it actually effects the upload size of a file.
Server also gives me permission denied if I try to access the folder **apps** by browser.

## Expected Result
No error message.
## Actual Result
Error message:
Your data directory and your files are probably accessible from the Internet. The .htaccess file is not working. We strongly suggest that you configure your web server in a way that the data directory is no longer accessible or you move the data directory outside the web server document root.

Did I miss any thing?

Below is my apache ssl config
```
<IfModule mod_ssl.c>
<VirtualHost _default_:443>
        ServerName <.......>
        Header always add Strict-Transport-Security "max-age=15768000; includeSubDomains; preload"
        ServerAdmin <........>
        DocumentRoot /var/www/owncloud
        <Directory />
                Options FollowSymLinks
                AllowOverride None
        </Directory>
        <Directory /var/www/>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride None
                Require all granted
        </Directory>
        ErrorLog ${APACHE_LOG_DIR}/error.log
        LogLevel warn
        CustomLog ${APACHE_LOG_DIR}/ssl_access.log combined
        SSLEngine on
        SSLCertificateFile    /etc/apache2/ssl/owncloud.pem
        SSLCertificateKeyFile /etc/apache2/ssl/owncloud.key
        <FilesMatch "\.(cgi|shtml|phtml|php)$">
                SSLOptions +StdEnvVars
        </FilesMatch>
        <Directory /usr/lib/cgi-bin>
                SSLOptions +StdEnvVars
        </Directory>
        BrowserMatch "MSIE [2-6]" \
                nokeepalive ssl-unclean-shutdown \
                downgrade-1.0 force-response-1.0
        BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown
        <Directory /var/www/owncloud>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Require all granted
                # add any possibly required additional directives here
                # e.g. the Satisfy directive (see below for details):
                Satisfy Any
        </Directory>
</VirtualHost>
</IfModule>
```

**Comment by RealRancor** [comment]
Hi,

you can test that by accessing a known file like:

https://example.com/data/$username/files/yourfile

If you're getting an access denied there your .htaccess protection should work. Then there is a similar issue reported here: https://github.com/owncloud/core/issues/17604

**Comment by KKyang** [comment]
@RealRancor 
Because I store the **data** folder in another drive, I'm not able to test whether I can access or not.
I update the post. I tried by entering the Url **https://..../apps**

The browser gives me Forbidden
```
Forbidden

You don't have permission to access /apps/ on this server.


Apache/2.4.7 (Ubuntu) Server at <......> Port 443
```

**Comment by RealRancor** [comment]
> Because I store the data folder in another drive

Mhhh, maybe this is what you have in common with the user in the other report?

**Comment by PVince81** [comment]
Hmm, works for me.

I tried setting "datadirectory" to another path, but the admin page doesn't show the warning.
Also I tried removing the local empty "data" folder, but I still don't see the warning.

**Comment by PVince81** [comment]
@LukasReschke any clue?

**Comment by nodomain** [comment]
Just as an idea because the same happened to me: in the global ssl.conf from Apache there were also some header settings that contradicted the .htaccess settings. After removing the "global" settings, the warnings went away.

**Comment by mislav-eu** [comment]
This warning is really annoying. My .htaccess is indeed working, I have AllowOverride all in all locations mentioned, data folder is outside owncloud and strong permissions are set according to admin documentation. Yet, I get this warning sometimes, then I delete htaccesstest.txt file in data folder and restart apache and error is gone. And it goes in circle.

**Comment by linucksrox** [comment]
Me too! Same issue, but I can't get the error to go away no matter what I try. The good news is that my files are not really accessible, according to the test described by @RealRancor. I can't remember, but I thought I saw a PHP file somewhere, the one that does the .htaccess test and writes htaccesstest.txt, which uses hardcoded paths to /var/www/owncloud/data. Maybe that's a clue to why this test is failing?

**Comment by RealRancor** [comment]
@linucksrox The check is not using a fixed file path to the datadir:

https://github.com/owncloud/core/blob/v8.1.1/lib/private/util.php#L1144-L1149

How did you moved the datadir to another place?

**Comment by linucksrox** [comment]
Oops, that makes sense in the php file. Yes, my data directory was originally /mnt/backup/owncloud/[username] but then in an attempt to resolve this issue I moved that to /mnt/backup/owncloud/data/[username].
I did update the owncloud config file and and apache config references to /var/www/owncloud/data to point to /mnt/backup/owncloud/data.

**Comment by linucksrox** [comment]
I wish I knew what changed, because I don't remember making any configuration changes in the past three days (except on a reverse proxy server pointing to this vm but running in a totally separate vm). However, when looking back at the admin console today (I've been ignoring it), there are no more warning messages. Does this warning get cached somewhere or something crazy?

**Comment by Jocko-plugout** [comment]
@RealRancor
I installed version 8.1.3.0 on a linux platform with apache2.4.3, and I got a similar issue: warning about htaccess not working.

In my case, I understood why:
- if I create a file test.txt in the folder data and I test the url  https://myDDNS/data/test.txt, I get a forbidden access. So my htaccess is really working
- my server web is behind a router without loopback feature and block any url with my ddns if I try from my LAN.
- If I open the admin page from a remote host (so out of my LAN), isHtaccessWorking will use my ddns set in $WEBROOT to build the url to try to get the content of htaccesstest.txt.
- As my server web is hosting on a NAS server behind the router,  getUrlContent fails with a not handled error :isHraccessWorking does not run the other code lines after the calling getUrlContent (htaccesstest.txt is not deleted).

**Comment by RealRancor** [comment]
@Jocko-plugout You need to ping someone else as i don't have any knowledge about the oC internals.

**Comment by nyklspree** [comment]
@Jocko-plugout 
I am facing the same scenario as you described (no error when accessing owncloud from LAN, but the error comes out when accessing owncloud from a remote host), just wondering if you have any fixes for this problem?

**Comment by MorrisJobke** [comment]
Duplicate of #17652 -> workaround is to remove the file `htaccesstest.txt` in the data directory

**Comment by MorrisJobke** [comment]
Fix is in https://github.com/owncloud/core/pull/21479

**Comment by enoch85** [comment]
I get this as well on my [demo server](https://owncloudphp7.techandme.se/data/testuser/files/README.md). Though I set strong permissions it doesn't seem to work.

```
root@owncloud:/var/www/html/owncloud/data# ll
total 24
drwxr-x---  4 www-data www-data 4096 jan 14 23:13 ./
drwxr-x--- 14 root     www-data 4096 jan 14 23:00 ../
-rw-r--r--  1 root     www-data  284 jan 13 00:51 .htaccess
-rw-r-----  1 www-data www-data    0 jan 13 00:51 index.html
-rw-r-----  1 www-data www-data    0 jan 13 00:51 .ocdata
-rw-r-----  1 www-data www-data  283 jan 14 23:05 owncloud.log
drwxr-x---  5 www-data www-data 4096 jan 13 00:51 testuser/
drwxr-x---  2 www-data www-data 4096 jan 13 00:51 updater_backup/
```

**Server**
ownCloud 8.2.2 fresh install. 
Ubuntu 14.04.3
PHP 7

**Comment by RealRancor** [comment]
@enoch85 Your .htaccess is not working so its unrelated to this issue. Strong permissions also won't help here.

**Comment by enoch85** [comment]
@RealRancor Ok then please help. What could be the issue? I've tried adding a htaccesstest.txt to the daatadir, but it won't help. Any suggestions? Fresh install as stated above. --^ cc @LukasReschke

**Comment by RealRancor** [comment]
@enoch85 The issue tracker shouldn't be used for webserver config issues ;-)

**Comment by enoch85** [comment]
@RealRancor, Ofc, I knew that. Just shouting out for help. ;)

**Comment by mmattel** [comment]
I am currently running in my test system git master
(latest commit 4f25f341788b3edad1bf4baf739cd632785c9abb)
My webserver is nginx, so htaccess has no purpose here,
but I am getting the same security warning.

I tried to add ``fastcgi_param htaccessWorking true; `` without success.

The data dir is in the standard location as setup defines it.
Trying to do a https://example.com/data/$username/files/yourfile gives me a permission denied as defined by rule.

**Comment by karlitschek** [comment]
Strange. We are doing the exact same test from inside owncloud. Can you check if your rules maybe allow to access the url from the same host? but not the outside?

**Comment by mmattel** [comment]
Just tested also from the inside, proper response - access denied.
Will do further testing.

**Comment by mariostevenson** [comment]
Unsure of the status, but it's easier to make a directory _owncloud-data_ . Change the data directory in _config.php_ . Then run _chown -R www-data:www-data /var/www/owncloud-data_

Hope it helps to close this out.

**Comment by BetaStacks** [comment]
Same thing happening here. v9.1.6
