### ISSUE TITLE
Implement right sidebar in files app

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#17655]
See https://github.com/owncloud/core/issues/16325 and https://github.com/owncloud/core/issues/16308#issuecomment-113521360 for mock ups.

This ticket is to track and discuss the ground work of the implementation of the right sidebar.
This is mostly about implementing the namespaces and classes, and the ability to register panels.

So far, it would look like this:
- [x] files app implements the right sidebar
    - [x] clicking a file triggers right sidebar
    - [x] default detail view on top
    - [x] tabs + public API to register tabs with name + DOM element for inside the panel

**Comment by PVince81** [comment]
Since this is the files app, everything would be under the `OCA.Files` namespace.
Unless we want the sidebar to be reusable by other apps, in which case we need to have the code in core. I remember that @oparoz mentioned being interested in using the panel in the gallery app ?

@DeepDiver1975 @blizzz @jancborchardt

**Comment by oparoz** [comment]
Imho, as far as the design is concerned, Files is considered a reference implementation, so if you want apps to look integrated, then the GUI toolkit should be made available in a public API.

**Comment by PVince81** [comment]
I started here: https://github.com/owncloud/core/pull/17656

We'll need to find a way to make this API public.
I don't like it that apps would first need to do "OCA.Files.FileList.getDetailView().addTabView(...)", that's too cumbersome.

**Comment by PVince81** [comment]
Raised https://github.com/owncloud/core/issues/18170 to make it usable by other apps in different contexts.
