### ISSUE TITLE
ownCloud 8.1, PHP 5.5 - Installation of owncloud-server-scl-php54

### ISSUE THREAD

**Issue by agru** [owncloud/core#17654]
While trying to upgrade to ownCloud 8.1 via OBS-repo the installation on my CentOS 6 machine wants to install `owncloud-server-scl-php54` and serveral packages with `php54`. But on this server PHP 5.5 is installed and I do not want to have packages from PHP 5.4 on the system. According to the release notes ownCloud 8.1 is working with PHP5.4+, and this includes PHP 5.5 - or do I missunderstand this?

Any help welcome because I should upgrade this week.

**Comment by RealRancor** [comment]
@agru 
Why create another issue if you have already found the existing duplicate and also posted there? https://github.com/owncloud/core/issues/17654

**Comment by agru** [comment]
@RealRancor 
Because I recognized later that our issues are different. User "pastinko" has the problem that although PHP 5.4 is installed via SCL and `owncloud-server-scl-php54` is used there is still a dependency error. 

In my case I have installed PHP 5.5 and to solve dependencies the upgrade process wants to install `owncloud-server-scl-php54` and as further dependencies several php54-packages. But my server is running with PHP 5.5 and not with PHP 5.4 as in the case of "pastinko".

I'm going to delete my comment / posting on #17637 as I think this is a different issue. If I am wrong, I can stay in the other issue.

**Comment by RealRancor** [comment]
Ah, then it might be even related to https://github.com/owncloud/core/issues/17645 ?

**Comment by agru** [comment]
Not really. This user, rasusmilch, has PHP 5.4 and also the package `owncloud-server-scl-php54` installed. The PHP packages that are installed in his case start with `php-*`. With his `yum info ...` command he shoes for example that the package `php` is in fact PHP in version 5.4. But during the upgrade process it is tried to install several packages that start with `php54-*`.

My case is still different: I do not have installed `owncloud-server-scl-php54` in ownCloud 8.0.4. Instead of this I have the package `owncloud-server`. Now, during my try to upgrade, the systems wants to install `owncloud-server-scl-php54` and to solve the dependencies also wants to install the packages that start with `php54-*`, although I have PHP 5.5 installed.

Similar is, that my installed packages do not have names that start with `php55-*` but only with `php-*`. So something is similar, but I have a different PHP-version and I do not want to have `owncloud-server-scl-php54`

**Comment by RealRancor** [comment]
Arghss, sorry. Sometimes i should read the issue completely.

**Comment by agru** [comment]
I am not sure whether the following is correct ... but it is a try :-)
It looks for me as if the package 'owncloud-app-encryption` pulls in `owncloud-server-scl-php54`. When I use the command `yum deplist owncloud-app-encryption` the following is shown:
`Paket: owncloud-app-encryption.noarch 8.1.0-13.1
  Abhängigkeit: owncloud-server-core = 8.1.0
   provider: owncloud-server.noarch 8.1.0-13.1
   provider: owncloud-server-scl-php54.noarch 8.1.0-13.1`

**Comment by jnweiger** [comment]
I don't think that owncloud-server-scl-php54 would work with php55. It has an obvious dependencies to php54.

**Comment by DeepDiver1975** [comment]
> I don't think that owncloud-server-scl-php54 would work with php55.

won't fix?

**Comment by agru** [comment]
Sorry ... this is the next misunderstanding of this issue! I do NOT want to have `owncloud-server-scl-php54` installed on my PHP 5.5 system! The functionality for PHP 5.5 is delivered by the package `owncloud-server` and I want to have this package. But the package management system insists on installing the package for systems with PHP 5.4. But this is the wrong package. As already described the package `owncloud-server-scl-php54` pulls in several packages for PHP 5.4 and I do not want to have all of this.

So, yes - please fix - if this is a issue of the packaging from ownCloud.

**Comment by jnweiger** [comment]
@agru For  'owncloud-server-core >= 8.1.0' your installer sees two providers:
'owncloud-server' and 'owncloud-server-scl-php54'  -- it seems to choose the wrong one. 
What happens if you explicitly ask for 'yum install owncloud-server' ?

Also, can you try to disable the repository that provides the unwanted php54 packages? Maybe that already convinces the installer to choose the other one.

I haven't seen such weird behaviour before. Normally the installer prefers upgrading an already installed package over replacing it by a different one, even if both provide the same symbols.

**Comment by jnweiger** [comment]
I've commited changes to https://build.opensuse.org/package/show/isv:ownCloud:community:8.1:testing/owncloud

There is now a new repository https://build.opensuse.org/package/binaries/isv:ownCloud:community:8.1:testing/owncloud?repository=CentOS_6_PHP55 with
* no longer require php > 5.4.0 there, as the php packages there are rarely named php. Often php55 something, and with 1.x.y version numbers, rather than 5.5.x version numbers.
* no longer provide owncloud-server-scl-php54 as this can only cause confusion here.

**Comment by agru** [comment]
@jnweiger I tried your suggested installation command `yum install owncloud-server`. The result is the same and looks like this:

    Aktualisieren:
     owncloud-server                             noarch              8.1.0-16.1                        isv_ownCloud_community               17 M
    Installiert für Abhängigkeiten:
     owncloud-app-encryption                     noarch              8.1.0-16.1                        isv_ownCloud_community              108 k
     owncloud-server-scl-php54                   noarch              8.1.0-16.1                        isv_ownCloud_community               17 M
     php54                                       x86_64              2.1-1.el6.remi                    remi                                3.3 k

The disabling of the remi-Repository (delivers the php54 packages) is not possible. I only get errors because there are the no repos for the requested dependencies for php54.

I'm gonna try your new repos and will report the results ... maybe begin of next week.
Thanks a lot so far.

**Comment by rperezb** [comment]
hey @DeepDiver1975  is this expected in 8.1.1? thx

**Comment by jnweiger** [comment]
@agru, the issue should be solved by now, owncloud-server-scl-php54 no longer appears in CENTOS_6_PHP55 projects.

**Comment by rperezb** [comment]
thanks @jnweiger, added to the new version tests

**Comment by jnweiger** [comment]
Closing here. I tried to reproduced after the fix. The Issue no longer shows for me.
