### ISSUE TITLE
owncloud 8.0.4 on QNAP TS-220 (PHP issue)

### ISSUE THREAD

**Issue by pulp26** [owncloud/core#17650]
Have NAS QNAP TS 220. Upgraded Qnap OS to 4.1.4 (2015/05/22). Upgraded ownCloud from 6.xx to 8.0.4 using current Qnap app center repository. Now OwnCloud refuse to launch due to PHP. Here is the error message:
"This version of ownCloud requires at least PHP 5.4.0
You are currently running 5.3.29. Please update your PHP version."

Qnap support didn't provide any solution. Advised to ask here ))
Did somebody test stock owncloud 8.0.4 on stock Qnap firmware? Is there any solution?

**Comment by RealRancor** [comment]
Hi,

funny that Qnap is providing the upgrade packages from 6.x to 8.x (without oC 7 in between) which is not supported by oC and know redirects users here.

**Comment by pulp26** [comment]
There is a solution actually. I have found PHP 5.5.25 in Qnap app center repository (Developer Tools section).
Now it is starting. Will check for possible bugs ))
I have translated your comments to QNAP support. Hope they will take appropriate actions.
Thank you!

**Comment by standio** [comment]
I have the same problem with makiing upgrade to version 8.0.4.

**Comment by RealRancor** [comment]
@standio Please read https://github.com/owncloud/core/issues/17650#issuecomment-121512281 and contact the Qnap support / community if you don't know how to update your PHP on this system.
