### ISSUE TITLE
TBD: Legacy / not used rewrites in .htaccess? removal of them?

### ISSUE THREAD

**Issue by ghost** [owncloud/core#17651]
Hi,

we're currently struggling in updating the nginx config https://github.com/owncloud/documentation/issues/1297

At the moment three rewrites are provided within the .htaccess:

https://github.com/owncloud/core/blob/v8.1.3/.htaccess#L43-L45

where a clear statement is missing if those are still needed or what their purpose is.

It seems they are even not needed any more as the nginx config is not providing them since ages so they could be just removed from the .htaccess?

Any insights in this?

cc @Xenopathic @josh4trunks

**Comment by RealRancor** [comment]
Seems at least:

```
RewriteRule ^apps/calendar/caldav\.php remote.php/caldav/ [QSA,L]
RewriteRule ^apps/contacts/carddav\.php remote.php/carddav/ [QSA,L]
```

are from pre-4.0.x as even 4.0.15 just redirects to /remote.php/caldav or /remote.php/carddav

https://github.com/owncloud/core/blob/v4.0.15/apps/calendar/caldav.php
https://github.com/owncloud/core/blob/v4.0.15/apps/contacts/carddav.php

**Comment by LukasReschke** [comment]
I'd say the first two can die with :fire:, with the latter one I'm not sure. I actually _think_ it was not ever really used and will likely not be fully (or at all?) supported but better not break stuff :speak_no_evil:

**Comment by RealRancor** [comment]
@LukasReschke 

Just did some further tests on a local setup of Apache with the latter one. I think this is also something which could be kicked out as it either never worked or is just broken:

```
curl -i http://127.0.0.1/remote/abc

HTTP/1.1 404 Not Found
Date: Tue, 13 Oct 2015 12:43:31 GMT
Server: Apache
Content-Length: 267
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /remote/abc was not found on this server.</p>
<hr>
<address>Apache Server at 127.0.0.1 Port 80</address>
</body></html>
```

**Comment by RealRancor** [comment]
Ok, so just closing this. If anyone consider to remote that rules in the future please ping me for updating the nginx conf.

**Comment by RealRancor** [comment]
Need to re-open this as i did some digging into the other rewrite-rule which wasn't removed with https://github.com/owncloud/core/pull/19802:

```
RewriteRule ^remote/(.*) remote.php [QSA,L]
```

It seems this was introduced within https://github.com/owncloud/core/commit/f69f764e8bd92d7d8eb10263eefcb6ee0d745d87 to rewrite:

```
/remote/caldav.php
/remote/carddav.php
/remote/webdav.php
```

to:

```
/remote.php/caldav
/remote.php/carddav
/remote.php/webdav
```

as seen in https://github.com/owncloud/core/commit/9bdd00c0f22deea144eebe4773ef70063ea45575

I don't have that much knowledge about .htaccess but from my PoV this rewrite rules can't work at all. A call to:

http://www.example.com/remote/caldav.php

is just redirected to:

http://www.example.com/remote.php

and causing the 500 as shown above (https://github.com/owncloud/core/issues/17651#issuecomment-147704708)

**Comment by PVince81** [comment]
@LukasReschke any update ? Move to 9.1 ?
