### ISSUE TITLE
ownCloud 8.1 - Unable to Mount Windows Server SMB Shares

### ISSUE THREAD

**Issue by area51pilot** [owncloud/core#17666]
Recently upgraded from OC 8.0.5 to OC 8.1 on Ubuntu 14.04 LTS. After upgrade, ALL SMB shares previously connected to a Windows 2011 server were disconnected. I removed and attempted to re-add shares but it would not authenticate and connect.  I was however able to connect to password protected Windows 7 Pro shares on the network as well as shares on a Linux box.

I performed a clean install on another piece of hardware as well as a VM instance and both rendered the same results as above.

Reverted back to to 8.0.5 and was able to utilize the Windows Server SMB shares again.  Issue exists in 8.1 pertaining to external SMB connections.

**Comment by enoch85** [comment]
Related: #17657

**Comment by LukasReschke** [comment]
@icewind1991 icewind/smb related?

**Comment by directict** [comment]
Thanks @area51pilot i made a copy of my production env... updated to 8.1.. waiting for a solution now :)

**Comment by icewind1991** [comment]
Is the windows server part of a domain?

**Comment by PVince81** [comment]
Please try again with 8.2.2.

If the issue persists, please use the issue template https://raw.githubusercontent.com/owncloud/core/master/issue_template.md and provide more information about the share.
