### ISSUE TITLE
"Feature" request: Owncloud-Server for Android

### ISSUE THREAD

**Issue by Nichtraucher** [owncloud/core#17664]
Hi (I hope this fits in here?),

essentially, what I'd like to do is something like this: http://klonom.com/turn-your-old-android-device-into-a-cloudserver/

For linux-challenged users like myself, this learning-curve is a little steep. As such, an Android-app that does the job would be wonderful. Is there a chance, that this may happen -  at any time in the future?

cheers,

Robert

**Comment by rullzer** [comment]
I do not think this is a feasible idea. It is very non trivial to port ownCloud server and all its dependencies to android which does not even have official PHP support. 

And even if there was proper php support. Nobody would really run ownCloud server on their phone. Assume you want to sync your desktop with the ownCloud server running on your phone, how would it know where to find your phone?

Or you could run the android owncloud client on your phone and sync with ownCloud server on it. But then the whole benefit is kind of gone.

The only use case I can see here is when you have an old phone around that you want to do something cool with. But even then there are several limitations to the practical use.


I think you would be much better off buying a raspberry pi 2 and following one of the many guides online. As a bonus you can learn a bit of linux on the way.

**Comment by Nichtraucher** [comment]
"...how would it know where to find your phone?"
I don't know, perhaps DynDS + port forwarding in the router?

"when you have an old phone around that you want to do something cool with. But even then there are several limitations"
That's what I have in mind. I just want to access/synchronize small files/data. I believe that the performance should not be an issue.

"I think you would be much better off buying a raspberry pi 2"
Performance-wise surely. The point is that I have this perfectly working phone that would otherwise be lying around unused or even thrown away. Another (albeit small) advantage is that the phone has a screen. I don't have to fire up my pc if I want to make any administrative changes.

cheers

**Comment by karlitschek** [comment]
Well it would be cool because this would enable us to turn ownCloud into a real peer to peer / federated network. A few more people have phones on this planet then root servers. ;-)
I'm sure it is not trivial. I think it would require to build and Android app that contains a webserver and php because this is not provided from the OS.
Even with dyndns and port forwarding this doesn't work because mobile carriers usually put their network behind NAT. So this only works with a reverse proxy service. Luckily I heard that some people are working on bringing this to ownCloud.
But I agree. definitely not easy.

**Comment by Nichtraucher** [comment]
"this doesn't work because mobile carriers usually put their network behind NAT"

That's not what I mean. As I no longer use (read: carry) this phone, I'd connect it to my home router (power supply) and my home w-lan.

cheers
