### ISSUE TITLE
Feature request: Unix-like symbolic links

### ISSUE THREAD

**Issue by tYYGH** [owncloud/core#17669]
First, this is _NOT_ about transparently following links because files would be already laid out as wanted. As pointed out elsewhere, _that_ feature is covered client-side by the configuration, and server-side by the external storage options.

My feature request is about being able to _store_ Unix-like symbolic links on owncloud.

Synology did this by having a [convention for naming links](http://forum.synology.com/wiki/index.php/Permanent_symbolic_links) (`l_*`), much like Windows does with its `*.url` files.
In my opinion, this should be avoided, because whatever convention we choose, we may encounter files that conflict with this convention by having their name look like a symlink's name.

I suggest that [RFC4437](http://greenbytes.de/tech/webdav/rfc4437.html) should be used instead, especially since some clients on Linux and Windows seem to [implement this RFC](http://stackoverflow.com/questions/3715572/webdav-link-resource) already.

I cannot speak for others, but my need would be both:
- in-repo symlinks, eg:

```
OC_ROOT/projects/mymodule_1st_try
OC_ROOT/projects/mymodule_2nd_try
OC_ROOT/projects/mymodule_3rd_try
OC_ROOT/projects/mymodule -> mymodule_2nd_try
```
- and out-of-repo symlinks, eg:

```
OC_ROOT/home.local/bin/xterm -> /usr/bin/mate-terminal
```

**Comment by DeepDiver1975** [comment]
I honestly don't see the need - in addition the RFC appears experimental for a long time.

But maybe somebody is willing to catch this and give the implementation a try. THX

**Comment by tYYGH** [comment]
The need is simple, really.
I have a login on several machines at several places; Linux on desktop, Linux on laptop, Android, occasionally Windows… Besides, network connectivity is not always good, nor is it always present, which is why NFS is not suitable for all situations.

I use owncloud, _not_ for storing movies or photos, but rather to act as a cached network drive. And on this "cloud" drive, I store development projects, development environments, as well as the preference files (aka. "dot-files") of several programs for which I wish to have the same settings on all machines (eg: same Geany or Skype or Gftp settings).

This is a very Linux-centered usage, and symbolic links are not rare at all, nor are they always dispensable.

**Comment by joernroeder** [comment]
i like the use case and i would love to see this works with ownclud, which will be turned in a synced preference manager… :+1:

**Comment by PVince81** [comment]
closing in favor of https://github.com/owncloud/core/issues/6771
