### ISSUE TITLE
OwnCloud YUM Path

### ISSUE THREAD

**Issue by Thomanji** [owncloud/core#17667]
Hi,

I am not sure if this is something I should ask somewhere else but I could not really find anything 

about it. I use the Owncloud repro to install and update OC. However it install it in the following 

directorry:

This package installs as follows: 
oc_dir: /var/www/html/owncloud 
oc_data_dir: /var/www/html/owncloud/data 
oc_config_dir: /var/www/html/owncloud/config 
apache_confdir: /etc/httpd/conf.d 
apache_serverroot: /var/www/htmlig 

Is there a way to change this to for example install it at:

/home/domainname/htdocs/owncloud/

instead of the above?

The repro is like this. Any way to put a path into this to set the default?

[isv_ownCloud_community]
name=Latest stable community release of ownCloud (CentOS_CentOS-6)
type=rpm-md
baseurl=http://download.opensuse.org/repositories/isv:/ownCloud:/community/CentOS_CentOS-6/
gpgcheck=1
gpgkey=http://download.opensuse.org/repositories/isv:/ownCloud:/community/CentOS_CentOS-

6/repodata/repomd.xml.key
enabled=1

Here is the environment:

Environment: Apache 2.2.15-39.el6.centos
Server: CentOS Linux 6.6
Database: MySql 55 5.5.31-2.w6
Client: 1.8.4
OC-Version: 8.1.0-13.1
PHP-Version: 5.4.16-1.ius.el6

Thank you for the help.
Best wishes,
Thomas

**Comment by karlitschek** [comment]
@jnweiger Can you help here?

**Comment by jnweiger** [comment]
No. The filesystem layout of the linux packages is static. It can only be changed at compile time.
I once tried to offer packages with an alternative FHS compatible layout. But abondoned the idea, as it is not maintainable.

Your best option is to grab that source tar and unpack it in  /home/domainname/htdocs/owncloud/
Installing the linux package from isv:ownCloud:community once might be still helpful to get the dependencies all set.
