### ISSUE TITLE
Delete button should be hidden from shared linkes if no permission to delete

### ISSUE THREAD

**Issue by osamak** [owncloud/core#17673]
As of ownCloud 8.1, shared links have a delete button on hovering a file or folder, even if the link does not allow public uploads. This button always indicates that there is "No permission to delete."  Such a button should be removed because it serves no purpose, and it only leads users to getting an error message.

**Comment by rullzer** [comment]
@jancborchardt what do you think?

**Comment by jancborchardt** [comment]
It serves as an indicator because if the icon simply isn’t there people might be confused as to why it is not.

The current behavior of showing the delete icon but giving direct feedback via tipsy is a good approach. What do you think @owncloud/designers?

**Comment by osamak** [comment]
@jancborchardt but why would we assume that people are expecting a delete button in shared links? this wasn't the behaiouvor of previous ownCloud versions anyway.

**Comment by jancborchardt** [comment]
@osamak well, we added it because it was confusing to people that there was no icon at all, because other files have it. That’s the feedback we received and it’s valid, so we improved it.

If you get shared a folder without edit rights, now at least you know why you can not use the delete button. Sure, it’s there for every file, but at least you have feedback why – and the button isn’t simply _not_ there.

**Comment by bsmiller** [comment]
Is there a way we can make it so we can use that delete button to actually delete the files/folders?

**Comment by jancborchardt** [comment]
@bsmiller not on the individual files which are inside the shared folder where you have no permission to. You can use the delete button on the shared folder which will then simply Unshare it from you (as the tooltip also says).

**Comment by PVince81** [comment]
@bsmiller if you are referring to the public link page where upload permissions are granted, see #6635 (which is about other file operations in the public link page)
