### ISSUE TITLE
[master] Migration issue

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#17671]
````
Doctrine\DBAL\DBALException: Unknown database type bool requested, OC\DB\OCSqlitePlatform may not support it.

**Comment by DeepDiver1975** [comment]
not really a sev2 - only happens if one create a table with a bool column in the sqlite database.

**Comment by cmonteroluque** [comment]
This issue will fall off 8.2 if not resolved by 6 Oct

**Comment by DeepDiver1975** [comment]
I tend to close it - people should not have other tables in the sqlite database. Criticality is close to :zero:
