### ISSUE TITLE
Password protected link displays username/password prompt in certain browsers

### ISSUE THREAD

**Issue by PartisanEntity** [owncloud/core#17675]
Reproduce:

1. select a file in your owncloud
2. share it using link and password (i.e. you want to share the link with someone who does not have an owncloud account)
3. open the link as a visitor (while not logged in)
4. enter password and click on the small arrow to continue
5. owncloud will load in the background, while in the foreground you will see a username/password prompt in the browser with the following message: 

"The server (url here):443 requires a username and password. The server says: owncloud" 

Browsers affected:

Chrome 43.0.2357.134 m
IE 11

Browsers unaffected:

Firefox 39.0

Expected behavior:

After calling up the link and entering the password owncloud should load the file/folder without displaying a username/password prompt in the browser.

owncloud version: 8.1.0

**Comment by MorrisJobke** [comment]
cc @schiesbn @PVince81

**Comment by PVince81** [comment]
Maybe some ajax call got a 401 authentication failed.
Normally after entering the password, a session cookie is created.

Maybe there is something in the environment that prevented this cookie to be set ?

**Comment by LukasReschke** [comment]
@PartisanEntity Are you by any chance using third-party applications?  - Are you able to provide us with a link to such a protected share and the password? If you don't want to disclose your instance URL here you can mail it to me to the mail address specified in my profile.

**Comment by PartisanEntity** [comment]
Apologies may have been a temporary issue. I cannot reproduce this anymore. Closing issue.
