### ISSUE TITLE
LDAP: Remove "Case insensitive LDAP server" setting as it is not in use.

### ISSUE THREAD

**Issue by blizzz** [owncloud/core#17677]
```
$ ack-grep ldap_nocase --type=php  apps/user_ldap
apps/user_ldap/templates/settings.php
81:                             <p><label for="ldap_nocase"><?php p($l->t('Case insensitive LDAP server (Windows)'));?></label><input type="checkbox" id="ldap_nocase" name="ldap_nocase" data-default="<?php p($_['ldap_nocase_default']); ?>"  value="1"<?php if (isset($_['ldap_nocase']) && ($_['ldap_nocase'])) p(' checked'); ?>></p>

apps/user_ldap/lib/configuration.php
382:                    'ldap_nocase'                       => 0,
439:                    'ldap_nocase'                       => 'ldapNoCase',

apps/user_ldap/ajax/setConfiguration.php
36:                               'ldap_nocase', 'ldap_turn_off_cert_check');
```

```
$ ack-grep ldapNoCase --type=php  apps/user_ldap
apps/user_ldap/lib/configuration.php
46:             'ldapNoCase' => null,
439:                    'ldap_nocase'                       => 'ldapNoCase',
```

All these occurrences are just the template, default valeus and reading-from/writing-to-DB related.

*ldap_nocase* was once introduced to indicate whether attribute names would have been needed to lowercase when parsing the server results: https://github.com/owncloud/core/commit/dd7a411f9aaceab1bf8eab551e5f95ff5feff6fb#diff-8f8c85e2bc7e4aea46a03f77c54622c7R119

Meanwhile, we do this in general anyway. The user/admin should not bring this knowledge. 

Thus the remaining code is a left over that just should go. With the cleanup, there should be an update script that removes the setting from  the database as well.

**Comment by Takuto88** [comment]
Now, there is a PR for that. Please review and merge if this is acceptable.

**Comment by blizzz** [comment]
Resolved by https://github.com/owncloud/core/pull/18244
