### ISSUE TITLE
provide independent database packages, preventing installation of unrequired db packages

### ISSUE THREAD

**Issue by CaptionF** [owncloud/core#17684]
running oC in DMZ 
server security teams dont like to have software installed, that is not required.
In case of database packages, this means independent database packages instead of mandatory package with all supported databases.

Prospect uses Oracle, and does not want mysql, postgress nor sql lite
current installed package: oC 8.0.5 on SLES 12

**Comment by karlitschek** [comment]
@jnfrmarks something we can do here?

**Comment by DeepDiver1975** [comment]
@jnweiger and the packaging nightmare continues ...

**Comment by DeepDiver1975** [comment]
> something we can do here?

@CaptionF  AFAIK there are different packages which pull in different dependencies - at least with 8.1 this is the case.

There is one package which pulls in the owncloud server code and another packages which installs the server code AND dbms

**Comment by jnweiger** [comment]
I can add this to the long term list of packaging enhancements. 
apache-config is already split, but dbms-config is not.

**Comment by bboule** [comment]
Sounds like we need to prioritize this list... @CaptionF do you see this as a reoccurring issue in the felid?

**Comment by CaptionF** [comment]
fulfilled with the new package structure of 9.x
