### ISSUE TITLE
files_external webdav SSL error

### ISSUE THREAD

**Issue by deviousway** [owncloud/core#17685]
trying  attach webdav.yandex.ru (famous russian webdav server),  got

{"reqId":"vahUW+5Zh0Nxs5XPFyJK","remoteAddr":"192.168.1.1","app":"files_external","message":"SSL certificate problem: unable to get local issuer certificate","level":3,"time":"2015-07-16T15:32:32+00:00","method":"PUT","url":"\/index.php\/apps\/files_external\/userstorages\/1"}
tryed to add with cert to trusted (in OS and in owncloud), no luck some issue

##i think it curl, need ability to disable any SSL checking 
curl --help |grep "insecure"
 -k, --insecure      Allow connections to SSL sites without certs (H)
or something like
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);

**Comment by LukasReschke** [comment]
Interesting. That looks like a legit bug. May I ask you to add some more information as described in our reporting guidelines? Thanks! https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by deviousway** [comment]
### Steps to reproduce
1.Personal -> add external storage
2.You can use nex credentials (crated user for test)
name:yandex
external storage:webdav
host:webdav.yandex.ru
user:owncloudtest
pass:owncloud
dir:/
https checkbox: should be yes

Trying different combination (with/Without https checkbox, hostname https://webdav.yandex.ru,webdavs://webdav.yandex.ru)
In other clients all fine (foldersync on android, dolphin on linux)


### Expected behaviour
webdav should be connected
also you can check manual
https://yandex.com/support/disk/webdav.xml

### Actual behaviour
webdav not connected

### Server configuration
**Operating system**:
Archlinux rolling release

my-web ~ $ uname -a
Linux deviousway.ru 4.1.0-1-mainline #1 SMP PREEMPT Sun Jul 5 02:29:40 KRAT 2015 x86_64 GNU/Linux

**Web server:**
my-web ~ $ nginx -v
nginx version: nginx/1.8.0
+php-fpm

**Database:**
my-web ~ $ mysql --version
mysql  Ver 15.1 Distrib 10.0.20-MariaDB, for Linux (x86_64) using readline 5.1


**PHP version:**
my-web ~ $ php -v
PHP 5.6.11 (cli) (built: Jul 10 2015 17:04:11) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies


**ownCloud version:** (see ownCloud admin page)
ownCloud 8.1.0 (stable) 
**Updated from an older ownCloud or fresh install:**

**List of activated apps:**

my-web ~ $ php occ app:list
```
Enabled:
 - activity: 2.0.1
 - bookmarks: 0.4
 - calendar: 0.7.2
 - contacts: 0.3.1.0
 - documents: 0.10.0
 - external: 1.2
 - files: 1.1.9
 - files_archive: 0.2
 - files_embeddedvideo: 0.0.7
 - files_external: 0.2.3
 - files_locking: 
 - files_mv: 0.8.1a
 - files_odfviewer: 0.1
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - mail: 0.1.3
 - mozilla_sync: 1.4
 - music: 0.3.5
 - news: 5.3.8
 - notes: 1.1.0
 - tasks: 0.7.1
 - updater: 0.6
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'occ9881ef12d',
  'passwordsalt' => '###############################,
  'datadirectory' => '/srv/http/webapps/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '###########',
  'dbpassword' => '###################',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'forcessl' => true,
  'loglevel' => 0,
  'trusted_domains' => 
  array (
    0 => 'my.deviousway.ru',
  ),
  'ldapIgnoreNamingRules' => false,
  'mail_smtpmode' => 'php',
  'xframe_restriction' => false,
  'secret' => '####################################',
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'mail_smtpsecure' => 'tls',
  'mail_from_address' => 'deviousway',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'mail.deviousway.ru',
  'mail_smtpport' => '465',
  'mail_domain' => 'deviousway.ru',
  'mail_smtpname' => 'deviousway@deviousway.ru',
  'mail_smtppassword' => '######################',
  'forceSSLforSubdomains' => true,
  'appstore.experimental.enabled' => true,
  'app.mail.imaplog.enabled' => true,
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no


### Client configuration
latest Firefox/Cromium/Opera

**Operating system:**
Archlinux 

### Logs
#### Web server error log
```
192.168.1.1 - - [17/Jul/2015:10:31:07 +0700] "PUT /index.php/apps/files_external/userstorages/1 HTTP/1.1" 200 199 "https://my.deviousway.ru/index.php/settings/personal" "Mozilla/5.0 (X11; Linux x86_64; rv:39.0) Gecko/20100101 Firefox/39.0"

```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"m+arcsnOpkNW6hFhmRkQ","remoteAddr":"192.168.1.1","app":"files_external","message":"SSL certificate problem: unable to get local issuer certificate","level":3,"time":"2015-07-17T03:32:07+00:00","method":"PUT","url":"\/index.php\/apps\/files_external\/userstorages\/1"}
{"reqId":"m+arcsnOpkNW6hFhmRkQ","remoteAddr":"192.168.1.1","app":"files_external","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\StorageNotAvailableException\",\"Message\":\"Sabre\\\\HTTP\\\\ClientException: SSL certificate problem: unable to get local issuer certificate\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/http\\\/webapps\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/dav.php(569): OC\\\\Files\\\\Storage\\\\DAV->convertException(Object(Sabre\\\\HTTP\\\\ClientException))\\n#1 \\\/srv\\\/http\\\/webapps\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/common.php(408): OC\\\\Files\\\\Storage\\\\DAV->stat('')\\n#2 \\\/srv\\\/http\\\/webapps\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(497): OC\\\\Files\\\\Storage\\\\Common->test(false)\\n#3 \\\/srv\\\/http\\\/webapps\\\/owncloud\\\/apps\\\/files_external\\\/controller\\\/storagescontroller.php(123): OC_Mount_Config::getBackendStatus('\\\\\\\\OC\\\\\\\\Files\\\\\\\\Stora...', Array, false)\\n#4 \\\/srv\\\/http\\\/webapps\\\/owncloud\\\/apps\\\/files_external\\\/controller\\\/userstoragescontroller.php(182): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus(Object(OCA\\\\Files_external\\\\Lib\\\\StorageConfig))\\n#5 [internal function]: OCA\\\\Files_External\\\\Controller\\\\UserStoragesController->update(1, 'yandex', '\\\\\\\\OC\\\\\\\\Files\\\\\\\\Stora...', Array, NULL)\\n#6 \\\/srv\\\/http\\\/webapps\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#7 \\\/srv\\\/http\\\/webapps\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_External\\\\Controller\\\\UserStoragesController), 'update')\\n#8 \\\/srv\\\/http\\\/webapps\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_External\\\\Controller\\\\UserStoragesController), 'update')\\n#9 \\\/srv\\\/http\\\/webapps\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('UserStoragesCon...', 'update', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#10 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#11 \\\/srv\\\/http\\\/webapps\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(274): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#12 \\\/srv\\\/http\\\/webapps\\\/owncloud\\\/lib\\\/base.php(867): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#13 \\\/srv\\\/http\\\/webapps\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/srv\\\/http\\\/webapps\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/dav.php\",\"Line\":800}","level":4,"time":"2015-07-17T03:32:07+00:00","method":"PUT","url":"\/index.php\/apps\/files_external\/userstorages\/1"}
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log

b) The network log 
backendClass
	"\OC\Files\Storage\DAV"
	
backendOptions
	Object { host="webdav.yandex.ru",  user="owncloudtest",  password="owncloud",  ещё...}
host
	"webdav.yandex.ru"
password
	"owncloud"	
root
	"/"
secure
	true
user
	"owncloudtest"
id
	1
mountPoint
	"yandex"
source
{"mountPoint":"yandex","backendClass":"\\OC\\Files\\Storage\\DAV","backendOptions":{"host":"webdav.yandex
.ru","user":"owncloudtest","password":"owncloud","root":"/","secure":true},"id":1}
c) ...
```

**Comment by RealRancor** [comment]
Seems that webdav.yandex.ru itself has a valid (but just not optimal) SSL config: https://www.ssllabs.com/ssltest/analyze.html?d=webdav.yandex.ru

**Comment by deviousway** [comment]
yes i know it, same result with openssl verfy (SSL certificate problem: unable to get local issuer certificate), may be issue with Certum Level IV CA.  And i ask  	
So I ask to add an option "Ignore all SSL errors",

**Comment by RealRancor** [comment]
> So I ask to add an option "Ignore all SSL errors"

From my PoV this is :see_no_evil:

**Comment by deviousway** [comment]
On 17.07.2015 16:46, RealRancor wrote:
>
>     So I ask to add an option "Ignore all SSL errors"
>
> From my PoV this is :see_no_evil:
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/owncloud/core/issues/17685#issuecomment-122231003>.
>

This option is present in many clients.
The user can't do anything with it, so I don't see another option

**Comment by RealRancor** [comment]
I think such an option is just an ugly workaround not a real solution. Instead try to import the certificate like described here:

https://doc.owncloud.org/server/8.1/admin_manual/configuration_files/external_storage_configuration_gui.html#using-self-signed-certificates

**Comment by deviousway** [comment]
On 17.07.2015 16:55, RealRancor wrote:
>
> I think such an option is just an ugly workaround not a real solution. 
> Instead try to import the certificate like described here:
>
> https://doc.owncloud.org/server/8.1/admin_manual/configuration_files/external_storage_configuration_gui.html#using-self-signed-certificates
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/owncloud/core/issues/17685#issuecomment-122232645>.
>
Already tryed,
 >>>
tryed to add with cert to trusted (in OS and in owncloud), no luck some 
issue
this certificates alredy added to trusted in OS ( 
/etc/ca-certificates/trust-source/anchors/), In Browser and in owncloud 
Konsole output Konsole output

**Comment by deviousway** [comment]
I think you understand that this option should be applied only to a separate connection, not to all

**Comment by PVince81** [comment]
8.1.0 is old. Please try again with a more recent version of ownCloud like 8.1.5 or 8.2.2 where some SSL issues were fixed.

Your issue could also be related to curl bugs, try to upgrade curl and the php curl library.

If you're still having issues with the latest versions, feel free to reopen.

**Comment by deviousway** [comment]
Php7, owncoud 8.2.2, latest curl, still not working (((

Отправлено из AquaMail для Андроида
http://www.aqua-mail.com


Vincent Petry <notifications@github.com> 1 марта 2016 г. 22:58:16 написал:

**Comment by PVince81** [comment]
So if I understand well, the part that doesn't work is that even though you imported certificate it still cannot connect to the remote ?

**Comment by deviousway** [comment]
On 02.03.2016 02:00, Vincent Petry wrote:
>
> So if I understand well, the part that doesn't work is that even 
> though you imported certificate it still cannot connect to the remote ?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/owncloud/core/issues/17685#issuecomment-190852799>.
>
yes,correct.
but error now another
data/owncloud.log


```
{"reqId":"ZgFRVnUzenN\/WhuyiAg2","remoteAddr":"192.168.1.21","app":"files","message":"Exception: 
{\"Exception\":\"OCP\\\\Files\\\\StorageNotAvailableException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 
\\\/srv\\\/http\\\/my.deviousway.ru\\\/public_html\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/availability.php(388): 
OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->checkAvailability()\\n#1 
\\\/srv\\\/http\\\/my.deviousway.ru\\\/public_html\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(377): 
OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->hasUpdated('', 
1333569600)\\n#2 
\\\/srv\\\/http\\\/my.deviousway.ru\\\/public_html\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(377): 
OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->hasUpdated('', 
1333569600)\\n#3 
\\\/srv\\\/http\\\/my.deviousway.ru\\\/public_html\\\/lib\\\/private\\\/files\\\/cache\\\/watcher.php(123): 
OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->hasUpdated('', 
1333569600)\\n#4 
\\\/srv\\\/http\\\/my.deviousway.ru\\\/public_html\\\/lib\\\/private\\\/files\\\/view.php(1205): 
OC\\\\Files\\\\Cache\\\\Watcher->needsUpdate('', Array)\\n#5 
\\\/srv\\\/http\\\/my.deviousway.ru\\\/public_html\\\/lib\\\/private\\\/files\\\/filesystem.php(861): 
OC\\\\Files\\\\View->getFileInfo('\\\/deviousway\\\/fil...', true)\\n#6 
\\\/srv\\\/http\\\/my.deviousway.ru\\\/public_html\\\/apps\\\/files\\\/ajax\\\/list.php(34): 
OC\\\\Files\\\\Filesystem::getFileInfo('\\\/WebDAV')\\n#7 
\\\/srv\\\/http\\\/my.deviousway.ru\\\/public_html\\\/lib\\\/private\\\/route\\\/route.php(154) 
: runtime-created function(1): 
require_once('\\\/srv\\\/http\\\/my.de...')\\n#8 [internal function]: 
__lambda_func()\\n#9 
\\\/srv\\\/http\\\/my.deviousway.ru\\\/public_html\\\/lib\\\/private\\\/route\\\/router.php(291): 
call_user_func('\\\\x00lambda_6320', Array)\\n#10 
\\\/srv\\\/http\\\/my.deviousway.ru\\\/public_html\\\/lib\\\/base.php(851): 
OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/aja...')\\n#11 
\\\/srv\\\/http\\\/my.deviousway.ru\\\/public_html\\\/index.php(39): 
OC::handleRequest()\\n#12 
{main}\",\"File\":\"\\\/srv\\\/http\\\/my.deviousway.ru\\\/public_html\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/availability.php\",\"Line\":63}","level":3,"time":"2016-03-01T19:25:39+00:00","method":"GET","url":"\/index.php\/apps\/files\/ajax\/list.php?dir=%2FWebDAV&sort=name&sortdirection=asc"}
```

**Comment by PVince81** [comment]
Try again in 15 minutes.

If a storage has an error (maybe you had the SSL error before importing the cert), the storage is marked "not available" for 10 minutes. Alternatively you can reset the value of "last_checked" in "oc_storages"

**Comment by deviousway** [comment]
On 02.03.2016 02:30, Vincent Petry wrote:
>
> Try again in 15 minutes.
>
> If a storage has an error (maybe you had the SSL error before 
> importing the cert), the storage is marked "not available" for 10 
> minutes. Alternatively you can reset the value of "last_checked" in 
> "oc_storages"
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/owncloud/core/issues/17685#issuecomment-190865232>.
>
Still same,
1)green icon in configuration, but still can't connect
tried to re-create this webdav - no luck
tried via http (this option sypported by webdav.yandex.ru) - no luck

2)>> you can reset the value of "last_checked" in "oc_storages"
please provide more detail

**Comment by PVince81** [comment]
if even "http" doesn't work then maybe your server is missing some important libraries. Are you seeing any warnings in the admin page ?

**Comment by deviousway** [comment]
20.05.2016 19:33, Vincent Petry пишет:
>
> if even "http" doesn't work then maybe your server is missing some 
> important libraries. Are you seeing any warnings in the admin page ?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub 
> <https://github.com/owncloud/core/issues/17685#issuecomment-220593552>
>
Nope, with other wedavs servers all ok, but now i get another error
  503 Storage not available
So this ticket can be colsed
