### ISSUE TITLE
occ config:system:set does not allow to set arrays, integer and booleans

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#17687]
Need to find an easy way to supply them. `config:app:set` does not suffer from this problem, as all values are strings there.

Values that can not be set correctly directly atm:
```php
  'loglevel' => 1,
  'filelocking.enabled' => true,
  'redis' => 
  array (
    'host' => '127.0.0.1',
    'port' => 6379,
    'timeout' => 0,
    'dbindex' => 0,
  ),
```

as a work around import can be used, but that is not really what we want to do.

**Comment by PVince81** [comment]
@nickvergessen enhancement for 9.0 or bugfix for 8.2 ?

**Comment by nickvergessen** [comment]
Don't care a lot. But I guess it would be nice to have.
Without that the occ tool is not fully functional for all values

**Comment by cmonteroluque** [comment]
bug for 8.2

**Comment by nickvergessen** [comment]
The PR to implement this missing feature however was delayed to 9.0

**Comment by DeepDiver1975** [comment]
> bug for 8.2

@cmonteroluque the "fix" was postpone to 9.0 because of open questions - not really critical from my pov

**Comment by cmonteroluque** [comment]
ok, moving to 9.0

**Comment by DeepDiver1975** [comment]
> ok, moving to 9.0

thx
