### ISSUE TITLE
Feature Request: view photos without downloading entire photo

### ISSUE THREAD

**Issue by binarydad** [owncloud/core#17692]
Services like OneDrive, DropBox, and Seafile have this feature. I have libraries of large photos (10+MB). I would like to be able to view the photo without having to download all 10 MB of it first, but rather, a fullscreen, smaller version that is light on the data transfer. 

This is the only feature that is keeping me from using OC full time. It's a bother when I can't simply swipe through my folders without accumulating hundreds of MB of downloaded data.

**Comment by Aesculapius** [comment]
I'd support this. Using an owncloud gallery with shared link as means to show your gallery to other people is currently not doable with original photo's.

**Comment by MegaMattMiller** [comment]
I'd also like to see this. Every time I view a photo in a new directory, I have to tell Android not to back up that folder. It get's really annoying after a couple.

**Comment by ErikPel** [comment]
Enabling the gallery app gives you this feature.

![](http://i.imgur.com/QFgkSE6.gif)

**Comment by MegaMattMiller** [comment]
Awesome thanks!

**Comment by PVince81** [comment]
install it from the marketplace https://marketplace.owncloud.com/apps/gallery
