### ISSUE TITLE
Offline install of apps from appstore

### ISSUE THREAD

**Issue by geiseri** [owncloud/core#17694]
Right now the occ can offline enable/disable applications.  Is there a way to request an install via the app store with occ?  This would be very nice in cases where you want to update/install applications via an ssh shell script.

**Comment by enoch85** [comment]
+1

**Comment by nickvergessen** [comment]
Hmm well I guess the problem is you'd need to use the ocsid not the app name then, so that will be somewhat difficult. Or can we assume people find it out?

**Comment by enoch85** [comment]
@nickvergessen So you mean it's possible to use the ocsid to activate the app already, or does it have to be implemented? 

Would be preferable to use the app name if that's not too hard to implement. On the other hand, the ocsid isn't that hard to find out.

**Comment by geiseri** [comment]
I do not see a problem with the ocsid.  In a way if you are bootstrapping this is not an issue since your cloud-init or Dockerfile could just include that ID.  If I want the name then I would use the UI, right?  Just my 2c.

**Comment by nickvergessen** [comment]
> @nickvergessen So you mean it's possible to use the ocsid to activate the app already, or does it have to be implemented?

Would need to implement

> Would be preferable to use the app name if that's not too hard to implement.

The problem is anyone can use the same app name, so if you install gallery which one is it? Is news the RSS reader from raydiation, or the announcement news app I wrote locally?
So we need something unique and the ocsid is.

**Comment by enoch85** [comment]
OK, ocsid is fine by me.

**Comment by nickvergessen** [comment]
Feel free to turn it into a patch:
```php
		$ocsClient = new OCSClient(
			\OC::$server->getHTTPClientService(),
			\OC::$server->getConfig(),
			\OC::$server->getLogger()
		);
		$appData = $ocsClient->getApplication($ocsId, \OC_Util::getVersion());

		if ($appData === null) {
			$output->writeln('<error>The appstore does not know the ocsid ' . $ocsId . '</error>');
			return 1;
		}

		$appId = '';
		try {
			$appId = \OC_App::downloadApp($ocsId);
		} catch (\Exception $e) {
			$output->writeln('<error>Failed to download the app</error>');
			throw $e;
		}

		\OC_App::installApp($appId);
		$output->writeln('<info>App ' . $appId . ' was installed successfully');
```

**Comment by pierreozoux** [comment]
Do you think a part of this could be an update of an app also?

I start to really like the `occ` command and it looks more and more as complete as [wp-cli](http://wp-cli.org/commands/plugin/) :)

**Comment by PVince81** [comment]
CC @LukasReschke @karlitschek

**Comment by PVince81** [comment]
use market:install --local appname.tar.gz
