### ISSUE TITLE
Packages: Enable all Apache modules from .htaccess

### ISSUE THREAD

**Issue by ghost** [owncloud/core#17691]
Currently the packages (at least on Debian) are only enabling the mod_rewrite module:

https://build.opensuse.org/package/view_file/isv:ownCloud:community:8.0/owncloud/debian.owncloud-config-apache.postinst?expand=1

However the .htaccess from 8.1.0 (https://github.com/owncloud/core/blob/v8.1.0/.htaccess) is using  four other modules:

mod_header
mod_env
mod_dir
mod_mime

It could make sense to enable those also.

cc @jnweiger 

Ref: https://github.com/owncloud/documentation/pull/1335

**Comment by LukasReschke** [comment]
:+1:

**Comment by RealRancor** [comment]
When running mod_fcgid the .htaccess is also using mod_setenvif. No idea if it makes sense to also detected or enabled it.

**Comment by enoch85** [comment]
ping @jnweiger

**Comment by jnweiger** [comment]
Hmmm. I have no idea if people would love or hate us, when we mess with their apache settings. 
Are there scenarios, where we would conflict with other existing settings, e.g. exclusive modules?

For fcgid, it is not just an a2enmod, it is best used when properly configured too. That is not really our business, is it?

**Comment by RealRancor** [comment]
I have no idea about conflicting modules but i think the users should enable them anyway after the package install.

**Comment by crrodriguez** [comment]
We won't be altering users webserver configuration, it has to be documented though.
