### ISSUE TITLE
Asset Pipeline really speeding up stuff?

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#17693]
I somehow have my concerns. Instead of 1x loading 20 JS files which get cached anyways in the browser and then loading small single JS files on demand (for other views) I end up with loading:
```
➜  assets git:(master) ✗ ls -lah *.js
-rw-r--r--  1 lukasreschke  staff   1.2M Jul 16 22:56 018140419db2cb05d2de849ecb1a2a7b.js
-rw-r--r--  1 lukasreschke  staff   1.2M Jul 16 22:56 10424586b7ef7e5332c60c07b46d7edf.js
-rw-r--r--  1 lukasreschke  staff   1.2M Jul 16 22:57 1341a8f88bd1ef6d1ca7142fda425748.js
-rw-r--r--  1 lukasreschke  staff   1.3M Jul 16 22:54 6c48d8d195fa1bcc553c8e71a014f6bb.js
-rw-r--r--  1 lukasreschke  staff   1.3M Jul 16 22:56 9bd3518f4bf1324d605e9f794376a554.js
-rw-r--r--  1 lukasreschke  staff   1.2M Jul 16 22:57 b3436b11b43e1adfd19488172d7debe0.js
-rw-r--r--  1 lukasreschke  staff   810K Jul 16 22:58 ea5e69e947e3ad2e33c6b6b70c492b6e.js
```

So I have quite some concern if this helps to speed up stuff. At least with my very slow network link here this is nearly unusable in real life scenarios.

I think this is likely caused by us abusing JS in a way that make @PVince81 cry. Would proper JS classes help in the future here or so…?

**Comment by LukasReschke** [comment]
cc @DeepDiver1975

**Comment by LukasReschke** [comment]
Without asset pipeline: ~2 MB JS
With asset pipeline: ~8.5 MB JS

**Comment by LukasReschke** [comment]
Also another 700k in CSS.

**Comment by Xenopathic** [comment]
@LukasReschke Note that you will only ever load one of those JS files, so it's 1.2MB not 8.5MB. A new file is created every time the source JS files change, be it due to an enabled/disabled app or something else.

**Comment by LukasReschke** [comment]
That's not quite it. The asset pipeline works on a "addScript" base. So each page that includes different scripts has another pipelined JS and CSS file.

This means when I open the login I do have another file than in the files view than in the personal interface etc. - Without it I basically have the same locally cached static assets plus a few not that large files.

In fact, these are just the files by clicking around.

So as long as the connection is slower than the time required for the TCP connectioms to single resources the asset pipeline is making things slower :-(

**Comment by LukasReschke** [comment]
So for example the admin interface has some super small admin.js but however instead of just downloading that file my browser is forced to download 1.2 MB again.

**Comment by LukasReschke** [comment]
From my opinion what would make sense is concatenate all these JS and CSS files we load globally but not app specific ones. - Or concatenate app specific ones to another file. Then we have to do maybe 2-3 requests more but those will be way smaller.

**Comment by PVince81** [comment]
>That's not quite it. The asset pipeline works on a "addScript" base. So each page that includes different scripts has another pipelined JS and CSS file.

Argh, really? That sounds wasteful.
I thought the asset pipeline would package stuff app-wise: for example a big core.js for the code JS, a big files.js for the files app, etc. That would make more sense.

>Would proper JS classes help in the future here or so…?

Yes and no. It's mostly whether we switch to another approach to load JS dependencies, see #17169. With some frameworks when the deps graph is known, it is possible to package JS modules together that are often needed together. I never did that before, just heard that it existed.

I think short term the best would be to deliver JS app-wise:
- core.js
- files.js
- files_sharing.js
- files_external.js
- ...

In the future there will be even more JS classes, considering that the JS side of OC is getting heavier. So we might want to reconsider this soon.

**Comment by DeepDiver1975** [comment]
> That's not quite it. The asset pipeline works on a "addScript" base. So each page that includes different scripts has another pipelined JS and CSS file.

Yes - this is the only reasonable way we can some up with.



> I thought the asset pipeline would package stuff app-wise: for example a big core.js for the code JS, a big files.js for the files app, etc. That would make more sense.

And load only core.js and $APP.js? Then we will loose any additional scripts/styles which are added my apps during runtime - we gain nothing then.

Loading all apps will break everything because apps are no properly isolated with respect to js function scope and CSS namespace. Futhermore in some cases not all apps js files should be loaded.

**Comment by PVince81** [comment]
>And load only core.js and $APP.js? Then we will loose any additional scripts/styles which are added my apps during runtime - we gain nothing then.

Are you refering to Javascript's `OC.addScript` ? AFAIK this also would not work with the asset pipeline.

**Comment by PVince81** [comment]
I wonder if we should not just force apps to provide the list of scripts to be loaded upfront instead of being able to have several code paths with different JS files.
If that is not acceptable, then at least provide a mechanism for apps to provide a list of scripts that should **always** be loaded. Then we can bundle these into the main JS. The other ones would have to be loaded separately outside of the asset pipline.

**Comment by DeepDiver1975** [comment]
> Are you refering to Javascript's OC.addScript ? AFAIK this also would not work with the asset pipeline.

OC.addScript() will not work with asset pipeline - this is true.
I'm referring to the fact that e.g. files_pdfviewer adds some scripts during app initialization which is used in the files app.

But we are anyhow already in the position where we experiment with a more explicit loading of scripts.
And yes - maybe a declarative approach (in info.xml) might help. On the other hand this will break a hell of apps.

Regarding the original concerns: how many different pages do exist a user has open?
It's basically the login screen and a few apps. I think the penalty of duplicating some js files is acceptable for the sake of having to download one js instead of 20.

**Comment by LukasReschke** [comment]
> > Regarding the original concerns: how many different pages do exist a user has open?
It's basically the login screen and a few apps. I think the penalty of duplicating some js files is acceptable for the sake of having to download one js instead of 20.

Well from my opinion it simply makes ownCloud quite cumbersome on any slow connection connection compared to not using the pipeline. Yes, it might be faster if you have a fast connection but not all of our users have and the expectation would generally be that stuff is faster when enabling it regardless what :speak_no_evil:  

That said our JS loading is really a mess considering all the apps that inject JS in all possible places. So this is certainly not a high priority issue just something to think about :smile:

**Comment by oparoz** [comment]
### Gallery

oC 8.1
Loading the root directory doing a CTRL+ F5 in Firefox

#### Without
122 requests 2MB 4.5s

#### With
36 requests 1.5MB 4.5s

#### Conclusion

I don't see much of a difference, but it used to make a larger impact. Maybe with apps which only have a couple of very long Js files and don't use 3rd party minified scripts?

**Comment by etiess** [comment]
@LukasReschke Any decision on this? Should owncloud still advise administrator to enable asset pipeline? I'm in the same case, with server having a very slow internet connection: should I enable it?

**Comment by MorrisJobke** [comment]
> @LukasReschke Any decision on this? Should owncloud still advise administrator to enable asset pipeline? I'm in the same case, with server having a very slow internet connection: should I enable it?

I don't think so. Having the caching done in the browser is most likely better and faster. From a client side and from a server side.

**Comment by Xenopathic** [comment]
@LukasReschke @MorrisJobke @DeepDiver1975 @PVince81 Proposal: remove asset pipeline entirely?

**Comment by DeepDiver1975** [comment]
> Proposal: remove asset pipeline entirely?

no - why?

From my pov the reduction of http requests is still a big benefit.
Furthermore this was explicitly added upon user request -> case closed
