### ISSUE TITLE
External storage icon isn't shown for mounted external storages in 8.2

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#17696]
### Steps to reproduce
1. Mount any external storage
2. Go to the files page

### Expected behaviour
You see the mounted storage with the external storage icon

### Actual behaviour
You see the mounted storage with the normal folder icon, not the external one

![screenshot from 2015-07-17 09 59 29](https://cloud.githubusercontent.com/assets/1477829/8742940/a50ce68a-2c6a-11e5-919a-172b467476cc.png)

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** ownCloud Enterprise Edition 8.2 pre alpha (daily) Build:2015-07-17T03:12:03+00:00 15877ac7eba002df64493b036191759e939b16e9 

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by rullzer** [comment]
Mmmm that is probably a case in my mimetype patch that I missed. I'll look into it.

**Comment by rullzer** [comment]
PR with fix in #17706
