### ISSUE TITLE
Lack of feedback regarding the steps to be done to the encryption update from OC 8.0.x to 8.1

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#17705]
### Steps to reproduce
1. Install OC 8.0.x (checked with 8.0.4 and 8.0.5) with encryption enabled
2. Upload several files
3. Upgrade OC to 8.1
......

### Expected behaviour
Information about how to setup the new encryption should show up

### Actual behaviour
There are no clear steps in the app to know what to do.

Downloading a file shows `Can't read file Module with id: OC_DEFAULT_MODULE does not exist. Please enable it in your apps settings or contact your administrator.`. Viewers such as gallery and pdf viewer doesn't work properly (the file is encrypted), and there won't be enough info to know what's happening in those apps.

After enabling the default encryption module, the following message is shown: `You need to migrate your encryption keys from the old encryption (ownCloud <= 8.0) to the new one. Please run 'occ encryption:migrate' or contact your administrator`. After doing the action, the message still persists until you log out and log in, but this isn't said

It's unclear if you must log out and log in you have access to the encrypted files again. First time I update seemed to be needed, but the second time not.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** ownCloud Enterprise Edition 8.1.0 (daily) Build:2015-07-17T03:18:17+00:00 816910baf17052d6b3c8fd1185996aa8b4988dca 

**Updated from an older ownCloud or fresh install:** updated from 8.0.5 and 8.0.4

**Comment by MorrisJobke** [comment]
cc @schiesbn

**Comment by schiesbn** [comment]
I think that's the same we already discussed here: https://github.com/owncloud/core/issues/16177

The problem is that only the encryption module can decide if it is ready nor. But in order to do it it needs to be enabled. That's why we decided already for 8.1.0 that this need to be handled by good upgrade documentation and release announcements.
