### ISSUE TITLE
zotero stopped synchronising binary files with owncloud after upgrade to ownCloud 8.1

### ISSUE THREAD

**Issue by cunio** [owncloud/core#17712]
I used to use owncloud's webdav as a space for zotero's binary files storage as described here: https://www.zotero.org/support/sync#webdavhttps://www.zotero.org/support/sync#webdav

I think that just after the ownCloud has been upgraded to 8.1 on Centos7 (PHP5.4) the webdav synchronisation on zotero got broken. Zotero put only two files in the zotero directory gave an error message 400. Each time I retry get the same.

Here is what I have been founding in the owncloud.log:

```
{"reqId":"VakHwvGuYo1oTZ3-cedXDwAAAAA","remoteAddr":"10.0.0.7","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 expected filesize 110 got 0\",\"Code\":0,\"Trace\":\"
#0 \\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php(113): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #251)\\n
#1 \\\/home\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('A3ZH6IP5.prop', Resource id #251)\\n
#2 \\\/home\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('zotero\\\/A3ZH6IP5...', Resource id #251, NULL)\\n
#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#4 \\\/home\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n
#5 \\\/home\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n
#6 \\\/home\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#7 \\\/home\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n
#8 \\\/home\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/home\\\/www\\\/owncl...')\\n
#9 {main}\",\"File\":\"\\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":144}","level":4,"time":"2015-07-17T13:48:51+00:00"}
```

**Comment by mhl66** [comment]
Same for me ("expected filesize 110 got 0"), log:

Exception: {"Message":"HTTP\/1.1 400 expected filesize 110 got 0","Code":0,"Trace":"#0 \/volume1\/web\/owncloud\/lib\/private\/connector\/sabre\/directory.php(113): OC\\Connector\\Sabre\\File->put(Resource id #30)\n#1 \/volume1\/web\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1053): OC\\Connector\\Sabre\\Directory->createFile('55VH7BUU.prop', Resource id #30)\n#2 \/volume1\/web\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(513): Sabre\\DAV\\Server->createFile('zotero\/55VH7BUU...', Resource id #30, NULL)\n#3 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/volume1\/web\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#5 \/volume1\/web\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#6 \/volume1\/web\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#7 \/volume1\/web\/owncloud\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n#8 \/volume1\/web\/owncloud\/remote.php(132): require_once('\/volume1\/web\/ow...')\n#9 {main}","File":"\/volume1\/web\/owncloud\/lib\/private\/connector\/sabre\/file.php","Line":144}

**Comment by andreas-h** [comment]
I'm having the same problem using the latest Owncloud on a Ubuntu 14.04 server. `expected filesize 110 got 0`. I'm using WebDAV over HTTPS with a certificate from StartSSL, and don't have any SSL problems whatsoever (just thought I'd mention it here).

**Comment by PVince81** [comment]
Are you all getting "110" for any file size ?
Normally that number should be the actual file size that's being uploaded.

Do you guys have a proxy that might mangle the requests ?

**Comment by andreas-h** [comment]
> Are you all getting "110" for any file size ?
> Normally that number should be the actual file size that's being uploaded.

Yes, I get "110" for any file size.

> Do you guys have a proxy that might mangle the requests ?

No.

**Comment by PVince81** [comment]
The file size is read from the CONTENT_LENGTH header. If the value is always 110 it means that something (SSL?) is sending that size, maybe it's not sending the real file but something else to ownCloud.
Is anyone of you able to hook up a packet monitor and see what request is actually sent to the server ?

**Comment by andreas-h** [comment]
In my case, the connection is SSL-enabled -- so I guess there's no way
to see the actual request, right?  I installed wireshark but it seems I
can only see SSL syn/ack and then encrypted payload data ...

**Comment by PVince81** [comment]
Another idea is to hook up a PHP debugger put a breakpoint here https://github.com/owncloud/core/blob/master/apps/files/appinfo/remote.php#L83 and then evaluate `$_SERVER`.

**Comment by cunio** [comment]
I have no idea how to debug the thing but for sure my connection is via SSL. And as I also get 110 as a file as filesize. I haven't any proxies in between.

**Comment by PVince81** [comment]
Just to rule out any environment problems: can you try with another WebDAV client which is not zotero ?
For example "cadaver" or KDE's Dolphin ?

**Comment by PVince81** [comment]
Basically check if uploads (put) work with such clients.

**Comment by cunio** [comment]
Dolphin works OK.

**Comment by andreas-h** [comment]
Yes, that works.

**Comment by PVince81** [comment]
Another thing to try would be setting up a test OC instance without SSL and seeing whether zotero can connect properly.

The only change regarding Webdav I can think of in 8.1 is the upgrade to the new Sabre library. But that shouldn't affect request headers in any way. The problem seems to be on the transport layer somehow.

Did you guys only upgrade ownCloud to 8.1 or did you upgrade your whole system ? (maybe it brought updates to Apache, openssl and co too)

**Comment by DeepDiver1975** [comment]
> Same for me ("expected filesize 110 got 0") on SYNOLOGY DiskStation 5.1 running ownCloud 8.1.0 (production), log:

We have seen this kind of error in the past with LOCK.

A LOCK on a not existing file will internally call createFile() and this is where the size check did cause issues .... but this has been a PUT :question: strange

**Comment by cunio** [comment]
PVince81, I do't know if the Apache was updated in the same time, right now I have httpd-2.4.6-31.el7.centos.x86_64 apache version on Centos

I use self-signed SSL certificate.

**Comment by cunio** [comment]
I have tried http connection with no help, the same problem as when connected via https

**Comment by cunio** [comment]
The apache has't been updated in the same time as the ownCloud. I use the same Centos apache package as for owncloud 8.0.4

**Comment by PVince81** [comment]
Maybe check the apache access log, it might show more info about the request, and whether it does something before and after like locking ?

**Comment by cunio** [comment]
the access.log extract is here:

x.x.x.x - j [28/Jul/2015:15:52:52 +0200] "PUT /owncloud/remote.php/webdav/zotero/3RUM3M25.prop HTTP/1.1" 400 221 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:39.0) Gecko/20100101 Firefox/39.0"
::1 - - [28/Jul/2015:15:52:53 +0200] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips mod_fcgid/2.3.9 PHP/5.4.16 mod_wsgi/3.4 Python/2.7.5 (internal dummy connection)"
::1 - - [28/Jul/2015:15:52:54 +0200] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips mod_fcgid/2.3.9 PHP/5.4.16 mod_wsgi/3.4 Python/2.7.5 (internal dummy connection)"


the only strange thing in the error.log is:
[Tue Jul 28 13:26:51.917071 2015] [authz_core:error] [pid 11212] [client x.x.x.x:45138] AH01630: client denied by server configuration: /home/www/owncloud/data/htaccesstest.txt

**Comment by andreas-h** [comment]
Apache access.log:

    134.102.186.40 - andreas [28/Jul/2015:16:09:12 +0200] "GET /remote.php/webdav/zotero/lastsync.txt HTTP/1.1" 200 4952 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:39.0) Gecko/20100101 Zotero/4.0.27.6"
    134.102.186.40 - andreas [28/Jul/2015:16:09:19 +0200] "GET /remote.php/webdav/zotero/3HW7N73Q.prop HTTP/1.1" 404 1209 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:39.0) Gecko/20100101 Zotero/4.0.27.6"
    134.102.186.40 - andreas [28/Jul/2015:16:09:19 +0200] "GET /remote.php/webdav/zotero/4TB7362B.prop HTTP/1.1" 404 1209 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:39.0) Gecko/20100101 Zotero/4.0.27.6"
    134.102.186.40 - andreas [28/Jul/2015:16:09:19 +0200] "PUT /remote.php/webdav/zotero/4TB7362B.zip HTTP/1.1" 204 907 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:39.0) Gecko/20100101 Zotero/4.0.27.6"
    134.102.186.40 - andreas [28/Jul/2015:16:09:19 +0200] "PUT /remote.php/webdav/zotero/3HW7N73Q.zip HTTP/1.1" 204 907 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:39.0) Gecko/20100101 Zotero/4.0.27.6"
    134.102.186.40 - andreas [28/Jul/2015:16:09:20 +0200] "PUT /remote.php/webdav/zotero/4TB7362B.prop HTTP/1.1" 400 1010 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:39.0) Gecko/20100101 Zotero/4.0.27.6"
    134.102.186.40 - andreas [28/Jul/2015:16:09:23 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 5185 "-" "Mozilla/5.0 (Linux) mirall/1.8.4"
    134.102.186.40 - andreas [28/Jul/2015:16:09:22 +0200] "PUT /remote.php/webdav/zotero/3HW7N73Q.prop HTTP/1.1" 400 1010 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:39.0) Gecko/20100101 Zotero/4.0.27.6"
    134.102.186.40 - andreas [28/Jul/2015:16:09:29 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 5231 "-" "Mozilla/5.0 (Linux) mirall/1.8.4"

Apache error.log:

    [Tue Jul 28 16:09:10.053756 2015] [ssl:info] [pid 28470] [client 134.102.186.40:49884] AH01964: Connection to child 1 established (server cloud.andreas-h.info:443)
    [Tue Jul 28 16:09:17.464954 2015] [reqtimeout:info] [pid 28470] [client 134.102.186.40:49884] AH01382: Request header read timeout
    [Tue Jul 28 16:09:17.482716 2015] [ssl:info] [pid 28470] (70007)The timeout specified has expired: [client 134.102.186.40:49884] AH01991: SSL input filter read failed.
    [Tue Jul 28 16:09:19.502522 2015] [ssl:info] [pid 28472] [client 134.102.186.40:5483] AH01964: Connection to child 3 established (server cloud.andreas-h.info:443)
    [Tue Jul 28 16:09:19.521117 2015] [ssl:info] [pid 28473] [client 134.102.186.40:24589] AH01964: Connection to child 4 established (server cloud.andreas-h.info:443)
    [Tue Jul 28 16:09:19.523037 2015] [ssl:info] [pid 28469] [client 134.102.186.40:30499] AH01964: Connection to child 0 established (server cloud.andreas-h.info:443)
    [Tue Jul 28 16:09:23.208466 2015] [ssl:info] [pid 28534] [client 134.102.186.40:35878] AH01964: Connection to child 5 established (server cloud.andreas-h.info:443)
    [Tue Jul 28 16:09:28.348528 2015] [reqtimeout:info] [pid 28534] [client 134.102.186.40:35878] AH01382: Request header read timeout
    [Tue Jul 28 16:09:28.348583 2015] [ssl:info] [pid 28534] (70007)The timeout specified has expired: [client 134.102.186.40:35878] AH01991: SSL input filter read failed.
    [Tue Jul 28 16:09:29.849408 2015] [ssl:info] [pid 28471] [client 134.102.186.40:57642] AH01964: Connection to child 2 established (server cloud.andreas-h.info:443)
    [Tue Jul 28 16:09:35.006363 2015] [reqtimeout:info] [pid 28471] [client 134.102.186.40:57642] AH01382: Request header read timeout
    [Tue Jul 28 16:09:35.006416 2015] [ssl:info] [pid 28471] (70007)The timeout specified has expired: [client 134.102.186.40:57642] AH01991: SSL input filter read failed.
    [Tue Jul 28 16:09:55.209520 2015] [ssl:info] [pid 28470] [client 134.102.186.40:21520] AH01964: Connection to child 1 established (server cloud.andreas-h.info:443)
    [Tue Jul 28 16:10:05.121153 2015] [reqtimeout:info] [pid 28470] [client 134.102.186.40:21520] AH01382: Request header read timeout
    [Tue Jul 28 16:10:05.121209 2015] [ssl:info] [pid 28470] (70007)The timeout specified has expired: [client 134.102.186.40:21520] AH01991: SSL input filter read failed.

**Comment by mhl66** [comment]
ownCloud has it´s own WebDAV implementation (sabre), which is obviously faulty (see first posts). Thus, apache logs (server) will not reveal any solution for this (except the ZOTERO one, of course), since the WebDAV function works with most of the clients, obviously!? Please correct me if I´m wrong.

16 days without any clue?

**Comment by andreas-h** [comment]
> 16 days without any clue?

Dear mhl66, please keep in mind Owncloud is an open-source project, with
mostly volunteers working on it during their spare time.  I'm sure your
tone is not appreciated.

**Comment by cunio** [comment]
I have been extracting the code from zotero in which the error reveals (the last function):
``` javascript
	/**
	 * Set mod time of file on storage server
	 *
	 * @param<----->{Zotero.Item}<->item
	 */
	function setStorageModificationTime(item) {
		var uri = getItemPropertyURI(item);
		
		var mtime = item.attachmentModificationTime;
		var hash = item.attachmentHash;
		
		var prop = '<properties version="1">'
			+ '<mtime>' + mtime + '</mtime>'
			+ '<hash>' + hash + '</hash>'
			+ '</properties>';
		
		return Zotero.HTTP.promise("PUT", uri,
				{ body: prop, debug: true, successCodes: [200, 201, 204] })
			.then(function (req) {
				return { mtime: mtime, hash: hash };
			})
			.catch(function (e) {
				throw new Error("HTTP " + e.xmlhttp.status
					+ " from WebDAV server for HTTP PUT");
			});
	};
	
```

**Comment by mhl66** [comment]
I would like to emphasize that this is not the exquisite problem of cunio and me, but obviously an error in the WebDAV implementation, as I stated 24 (!) days ago (proof: the synology implementation works as it should). @andreas-h: Therefore, the thread should be considered as a constructive hint towards stable code, and it simply can not be denied that ownCloud is an open source projects with a remarkable gap between claim (one-for-all solution) and reality (see forums, i.e. updating versions, address book usability, platform (windows) availability etc. etc.).

**Comment by flop25** [comment]
same for me 
php 5.4.43 Centos 6.5
just after updating owncloud to 8.1
indeed owncloud is very complexe and brings lots of issues
@andreas-h where did you find the log with "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips mod_fcgid/2.3.9 PHP/5.4.16 mod_wsgi/3.4 Python/2.7.5 (internal dummy connection)" inside ?
I don't see anything but access log as you

**Comment by flop25** [comment]
but it seems it uploads 
I checked on owncloud side and zoetro debug output: I found that the lastsync file is never updated and so i get 
```
(3)(+0000000): Last successful WebDAV sync was Thu Aug 13 2015 22:52:45 GMT+0200
where as tonight I tested by adding a random ref -> it uploads again anything which has been added, but it uploads successfully!

ex for one ref
3)(+0000946): HTTP GET http://foo/remote.php/webdav/zotero/GFATA4BJ.prop succeeded with 404

(3)(+0000000): <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>File with name zotero/GFATA4BJ.prop could not be located</s:message>
</d:error>


(5)(+0000000): SELECT syncState FROM itemAttachments WHERE itemID=?

(5)(+0000000): Binding parameter 1 of type int: 977

(3)(+0000000): Remote file not found for item 977

(3)(+0000007): HTTP PUT of GFATA4BJ.zip to http://foo/remote.php/webdav/zotero/GFATA4BJ.zip

(3)(+0000002): onStatus with 2152398853

(3)(+0000000): onStatus with 2152398853

(3)(+0000000): onProgress with 98304/393937

(2)(+0000000): progressMax has changed from 0 to 393937 for request '0/GFATA4BJ'

(3)(+0000265): onStatus with 2152398853

(3)(+0000000): onProgress with 163840/393937

(3)(+0000001): onStatus with 2152398853

(3)(+0000000): onProgress with 229376/393937

(3)(+0000128): onStatus with 2152398853

(3)(+0000000): onProgress with 294912/393937

(3)(+0000139): onStatus with 2152398853

(3)(+0000000): onProgress with 360448/393937

(3)(+0000054): HTTP GET http://foo/remote.php/webdav/zotero/3RR2AU6J.prop succeeded with 404

(3)(+0000000): <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>File with name zotero/3RR2AU6J.prop could not be located</s:message>
</d:error>


(5)(+0000000): SELECT syncState FROM itemAttachments WHERE itemID=?

(5)(+0000000): Binding parameter 1 of type int: 972

(3)(+0000000): Remote file not found for item 972

(3)(+0000006): HTTP PUT of 3RR2AU6J.zip to http://foo/remote.php/webdav/zotero/3RR2AU6J.zip

(3)(+0000023): onStatus with 2152398853

(3)(+0000000): onProgress with 32768/444277

(2)(+0000000): progressMax has changed from 0 to 444277 for request '0/3RR2AU6J'

(3)(+0000000): onStatus with 2152398853

(3)(+0000000): onProgress with 98304/444277

(3)(+0000262): onStatus with 2152398853

(3)(+0000000): onProgress with 163840/444277

(3)(+0000000): onStatus with 2152398853

(3)(+0000000): onProgress with 229376/444277

(3)(+0000092): onStatus with 2152398853

(3)(+0000000): onProgress with 262144/444277

(3)(+0000164): onStatus with 2152398853

(3)(+0000000): onProgress with 294912/444277

(3)(+0000000): onStatus with 2152398853

(3)(+0000000): onProgress with 360448/444277

(3)(+0000102): onStatus with 2152398858

(3)(+0000284): onStartRequest

(3)(+0000000): Starting request

(3)(+0000000): onStopRequest with 0

(3)(+0000000): Request ended with status 0

(3)(+0000003): Upload of attachment GFATA4BJ finished with status code 201

(3)(+0000008): HTTP PUT <properties version="1"><mtime>1440191764000</mtime><hash>0d14ba18657fc0901e396d10e387561b</hash></properties> to http://foo/remote.php/webdav/zotero/GFATA4BJ.prop

(1)(+0001251): HTTP PUT http://foo/remote.php/webdav/zotero/GFATA4BJ.prop failed: Unexpected status code 400

(3)(+0000000): <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\BadRequest</s:exception>
  <s:message>expected filesize 110 got 0</s:message>
</d:error>


(3)(+0000000): Upload request 0/GFATA4BJ failed

(1)(+0000000): Error: HTTP 400 from WebDAV server for HTTP PUT
    ===== Stack Trace =====
    setStorageModificationTime/Zotero.Sync.Storage.WebDAV<@chrome://zotero/content/xpcom/storage/webdav.js:151:1
    _rejected@resource://zotero/q.js:897:24
    when/</<@resource://zotero/q.js:924:30
    reject/rejection<.when@resource://zotero/q.js:743:31
    makePromise/promise.promiseDispatch@resource://zotero/q.js:563:26
    defer/become/</<@resource://zotero/q.js:474:17
    onTick@resource://zotero/q.js:163:17
    setTimeout</setTimeout/<.notify@resource://zotero/q.js:78:7
    =======================

(3)(+0000000): Stopping upload queue for library 0

(3)(+0000000): Finishing upload/0 request '0/3RR2AU6J'
```

**Comment by mhl66** [comment]
As a fortunate user of Synology DiskStation, I´m able to circumvent this error by using its WebDAV implementation (port 5006, over httpproxy with virtual host). @andreas-h: as I commented 20 (sic) days ago, your apache access log which confused @flop25 above does not make sense: "Thus, apache logs (server) will not reveal any solution for this (except the ZOTERO one, of course), since the WebDAV function works with most of the clients, obviously". It most probably is the faulty ownCloud Sabre implementation, and after over one month it´s more than strange that this bug is not assigned nor seems to worry anyone (maybe holiday time)?

**Comment by flop25** [comment]
what I don't understand is why is it working with some files ( in my case zips are ok) but not with others (.prop)?
on the other hand the client owncloud for win works well
for me it looks like a specific issue with zotero And owncloud 8.1

**Comment by andreas-h** [comment]
@mhl66 What do you mean by *does not make sense*? One of the Owncloud developers, @PVince81, asked me to provide one, so I did.  I agree that the level of detail it gives doesn't help, but I'm being constructive and let the devs decide for themselves.

**Comment by mhl66** [comment]
@andreas-h: with *does not make sense* I wanted to state that (in my humble opinion) the *zotero* apache log (server-client) would reveal the error and not the *user* log (client-server).
Anyway, **thank you** in the name of the others for helping @PVince81 and hopefully he (and the other developers) will succeed at last. The developer´s blog stated that the WebDAV backend is crucial for the whole system, so I assume(d) that the whole thing is of general importance, even if there are few zotero users...

**Comment by PVince81** [comment]
Are you all using a NAS / Synology ?
Does its Apache come with the mod_dav module enabled ? Some mentioned that the NAS had its own Webdav interface, so I suspect that the module might be enabled and could interfere with ownCloud, see https://doc.owncloud.org/server/8.1/admin_manual/issues/index.html?highlight=mod_dav#webserver-and-php-modules

You could try disabling mod_dav temporarily and see whether it solves the problem.

Another possibility is that something (module, proxy?) is mangling the HTTP headers.

Looking at this part https://github.com/owncloud/core/issues/17712#issuecomment-127737009 I'm guessing that zotero might be PUTting this XML content as a ".prop" file, which has been reported not working. I wonder if the "Content-Length" header is missing in this specific PUT case, while for regular files it might send the content length properly.

I'm not sure whether PUTting works without Content-Length on ownCloud, something to try.

**Comment by andreas-h** [comment]
No, I'm on a Ubuntu 14.04 server using Apache2 httpd.

**Comment by flop25** [comment]
i'm on a dedicated server apache, php 5.4.43, Centos 6.5
do you know how we could intercept the whole HTTP requests?
indeed that's strange we all have 'expected filesize 110 got 0'

**Comment by PVince81** [comment]
You could use a packet sniffer, not sure what's available on Windows/Mac.
On Linux you can do it with Wireshark.

**Comment by flop25** [comment]
hmm thank you
I will search for such a software

**Comment by flop25** [comment]
Wireshark too on win and mac
I will provide the .pcapng file only by email: ping me flop25 at piwigo.org

**Comment by PVince81** [comment]
I tried installing Zotero standalone locally but I have no idea how to use it or how to make it sync.
I set "Sync attachments with Webdav" then specified my ownCloud URL "http://localhost/owncloud/remote.php/webdav".

How to make it sync things ? Can someone provide the exact steps (where to click and what to do) so I can trigger the issue ?

Thanks.

**Comment by PVince81** [comment]
It created the folder "zotero" but whatever I do in the UI, create attachments or "attach stored copy of a file", it doesn't even attempt to sync anything.
There is a button "sync" on the top right it seems but when I click it it asks me to provide zotero.org credentials instead of syncing with Webdav as configured.

**Comment by flop25** [comment]
arf can't tell you until hours, at home... I will try to remove my zotero account in the settings

**Comment by Xenopathic** [comment]
@PVince81 Zotero WebDAV is just for attachment files, like a PDF from a website. The actual database and index is either stored locally (in which case WebDAV is completely disabled) or on the Zotero servers, when WebDAV can be optionally used. So you'll have to set up a Zotero account and connect it to use the WebDAV attachment sync (WTF I know...)

**Comment by Xenopathic** [comment]
I've just tested this, and cannot reproduce the problems. Zotero successfully puts `.prop` and `.zip` files in the configured directory on ownCloud, via WebDAV. The files there are valid (at least, the ZIPs are extractable and contain sensible information).

I am running ownCloud 8.1.1.

**Comment by flop25** [comment]
@Xenopathic  os/php/apache?

**Comment by Xenopathic** [comment]
@flop25 Linux, Zotero was on Windows 7 with Firefox, using nginx + PHP-FPM

**Comment by flop25** [comment]
well i don't know what to say...
could you use a pre 8.1 version, sync, update owncloud, add item to zotero and sync again? Also try zotero standalone instead (don't know for the others but i'm using that one)
i still can send my packet capture

**Comment by Xenopathic** [comment]
@flop25 I've just tried with Zotero Standalone, and that worked fine too.

Do you get any errors with other WebDAV clients?

**Comment by lupa18** [comment]
Here similar problem: 
Ubuntu 14.04
OC 8.1
Zotero 4

**Comment by flop25** [comment]
I don't have other client avalaible
and honestly don't have much time to get into the installation of a new one...

@lupa18 Could you be more specific about what you are experiencing, like do you the same errors in zotero logs, do you have the zip uploaded but not prop neither .lastsync file etc

**Comment by flop25** [comment]
more info:
I have disabled the two dav module from apache, then restarted and -as expected- no change
also those issues looks like https://forum.owncloud.org/viewtopic.php?f=14&t=28354&start=10#p87579
can the files of owncloud be overwritten though ftp just to be sure all files have been updated?

**Comment by Xenopathic** [comment]
@flop25 Could you send me some test credentials for your ownCloud instance, so that I can connect a Zotero locally to it to try and reproduce the problems? That seems like the only way forward... please use my email on my GitHub profile.

**Comment by Xenopathic** [comment]
@flop25 Do you use mod_pagespeed for Apache? It's been known to break ownCloud: #416. Please disable that module for the ownCloud instance.

**Comment by flop25** [comment]
no mod_pagespeed found or any reference to its options etc

**Comment by Xenopathic** [comment]
@flop25 From the link you sent me, I see all the CSS and JS concatenated into the HTML, which indicates mod_pagespeed. You have to disable that.

**Comment by flop25** [comment]
?
I don't know what you mean by "concatenated into the HTML" What I see is now minification, no combination of the js/css ; they all called from source one by one 
<script src="/foo_cloud/apps/files/js/files.js?v=4e1c52f5bf49365ffcca6f18ad0c2c2f"></script>
					<script src="/foo_cloud/apps/files/js/navigation.js?v=4e1c52f5bf49365ffcca6f18ad0c2c2f"></script>
					<script src="/foo_cloud/apps/files/js/keyboardshortcuts.js?v=4e1c52f5bf49365ffcca6f18ad0c2c2f"></script>

**Comment by flop25** [comment]
grep'ed 'speed' by ignoring case in etc/httpd and found only libphp5.so and libphp5-zts.so So i really think it's not enabled

**Comment by Xenopathic** [comment]
@flop25 This is what I see on the login page: https://gist.github.com/Xenopathic/cb5731c230bd82c49bcc

As a result, the Log In button does not work (as JS is FUBARed).

**Comment by flop25** [comment]
that's not what I have
please remove that ; I don't want to see paths here

**Comment by flop25** [comment]
disabled cloudflare, maybe you could try again

**Comment by Xenopathic** [comment]
@flop25 Right, I've just reproduced the error with your server. The ZIP is correctly uploaded, but no .prop files are, and the Zotero client is reporting an HTTP 400 error.

**Comment by flop25** [comment]
ok logic is back again ^^
thank you for your work

at least now you can capture your own packets

**Comment by Xenopathic** [comment]
So, Zotero tries to send the prop files with the `application/x-www-form-urlencoded` content type, which ownCloud handles specially and attempts to decode it. This seems to break the WebDAV PUT.

I've got a reproducable test with `netcat` now, to eliminate Zotero from the equation. Investigating.

**Comment by flop25** [comment]
\o/ THx!

**Comment by Xenopathic** [comment]
Yet that same test file works just fine on my `master` development environment...

**Comment by Xenopathic** [comment]
And it just worked on 8.1.1 as well... I think there's something different in your environment. Perhaps Apache or PHP is attempting to decode the data when the content type is application/x-www-form-urlencoded, so ownCloud cannot read it directly?

**Comment by flop25** [comment]
@mhl66 mentioned that's working using the inbuild synology ( #issuecomment-122659823) 

it's happening apiori on centos and ubuntu too... Don't you soemone in the team with a similar setup (no nginx you have)

https://forums.zotero.org/discussion/51067/zotero-stopped-syncing-attached-files-via-webdav-after-owncloud-has-been-upgraded-from-v8-to-81/ -> maybe you can suggest to change the content type used as a hot fix

**Comment by Xenopathic** [comment]
Finally reproducable on my own hardware! (On a Docker image of Ubuntu 14.04). That was with a completely stock installation, so there's something going wrong right down at the PHP level...

**Comment by Xenopathic** [comment]
OK, *that's* an obsure bug.

So, PHP <5.6 had a bug on certain SAPIs (including mod_php it seems) where `php://input` can only be read once. (http://php.net/manual/en/wrappers.php.php): 

>     Note: Prior to PHP 5.6, a stream opened with php://input could only be read once; the stream did not support seek operations. However, depending on the SAPI implementation, it may be possible to open another php://input stream and restart reading. This is only possible if the request body data has been saved. Typically, this is the case for POST requests, but not other request methods, such as PUT or PROPFIND. 

That in itself isn't a significant problem, however ownCloud's Request class reads the contents of `php://input` and attempts to decode it if the content type is `application/json` or `application/x-www-form-urlencoded` (https://github.com/owncloud/core/blob/master/lib/private/appframework/http/request.php#L112-L131).

The result is that after the ownCloud Request class has read the data, the attempt by Sabre DAV to read the data only returns an empty stream, thus leading to the issue of no content found while some was expected.

**Comment by flop25** [comment]
owww! You dug sooo far... and you succeed !

**Comment by cunio** [comment]
@Xenopathic, I confirm your finding. After upgrade php from 5.4 to 5.6 in Centos via IUS repo the problem with zotero and webdav disappeared,

**Comment by michaelstingl** [comment]
@MorrisJobke Just to be sure: Did the fix (https://github.com/owncloud/core/issues/18691?) made it it 8.1.4 ?

**Comment by MorrisJobke** [comment]
> @MorrisJobke Just to be sure: Did the fix (#18691) made it it 8.1.4 ?

Yes: https://github.com/owncloud/core/pull/18703/files (but 8.1.4 is not yet released: planned for next Tuesday https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule)

**Comment by michaelstingl** [comment]
@MorrisJobke This is good news. Thank you very much!

**Comment by childnode** [comment]
yay back ... OC 8.2.2, php 5.6.17 and .18 with any webDav client ;( that's sooo frustrating

**Comment by PVince81** [comment]
@childnode mind giving more details ? Is this exactly the same issue ? (same logs, etc)
If not, please raise a separate ticket and provide logs.

**Comment by childnode** [comment]
> mind giving more details
yes ;)
can't find any relevant logs at that time anymore neither can I reproduce it today, but: I reproduced it that day -11 with exactly the same error type (1MB constraint as before php 5.6)  ... what I changed: I deleted the remote file, pushed it again ... since I can upload it getting bigger than 1MB ... if noone else comes up sharing this issue ... I'll revoke my complaint, sorry for bothering the subscribers ;)
