### ISSUE TITLE
X_SENDFILE does not work - Apache Mod is there

### ISSUE THREAD

**Issue by Gomez** [owncloud/core#17717]
The check for the Apache MOD is here: https://github.com/owncloud/core/blob/v8.0.5/lib/private/files.php#L65
There is `MOD_X_SENDFILE_ENABLED`. If i output my $_SERVER var can see this:
```
 ["REDIRECT_MOD_X_SENDFILE_ENABLED"]=> string(1) "1"
```
I replaced it, still no success. Someone with more insight? 

### Steps to reproduce
1. Install libapache2-mod-xsendfile
2. Restart apache2 / php-fqm
3. Add stuff to apache conf like told here: https://doc.owncloud.org/server/8.0/admin_manual/configuration_files/serving_static_files_configuration.html?highlight=sendfile#apache2-x-sendfile 
4.  curl -I "https://cloud.xxx/index.php/s/DpwNrgfRflBNb4y/download" 

### Expected behaviour
X-Sendfile header should be there

### Actual behaviour
X-Sendfile is not there

### Server configuration
**Operating system**:
Ubuntu 14.04
**Web server:**
Apache (Nginx as reverse proxy infront)
**Database:**
Mysql

**PHP version:**
PHP 5.5.9-1ubuntu4.11 

**ownCloud version:** (see ownCloud admin page)
8.0.5

**Are you using external storage, if yes which one:** local/smb/sftp/...
only local
**Are you using encryption:** yes/no
no

**Comment by LukasReschke** [comment]
> X-Sendfile header should be there

The end-user will never see these headers, Apache will just kill the PHP script as soon as it encounters a configured header and will send the file configured in that header.

Are you sure that it doesn't work? :speak_no_evil:

**Comment by Gomez** [comment]
Understood. 
Does not work. No resume or pause possible on a big file. 
If i read the code correctly $xsendfile = true; never happens with my `REDIRECT_MOD_X_SENDFILE_ENABLED`

If you like, i can provide more info over irc....

**Comment by PVince81** [comment]
Why is it called "REDIRECT_MOD_X_SENDFILE_ENABLED" instead of "MOD_X_SENDFILE_ENABLED" ?

**Comment by Gomez** [comment]
Maybe because i use a nginx reverse proxy? Tell me if i can provide more infos!

**Comment by DeepDiver1975** [comment]
In this setup we might need to send the headers for Apache and nginx?

Fyi: xsendfile does not work for webdav.

**Comment by Gomez** [comment]
Something i can do here?

**Comment by DeepDiver1975** [comment]
Hmm ... I honestly dont now. Please note that 8.2 will drop xsendfile support.

**Comment by MorrisJobke** [comment]
As support for xsendfile was dropped with 8.2 I will close this ticket - resuming download will be possible with WebDAV - see https://github.com/owncloud/core/issues/20413
