### ISSUE TITLE
unable to get movie thumbs

### ISSUE THREAD

**Issue by johansmitsnl** [owncloud/core#17726]
I run version 8.1
Ubuntu 14.04 LTS x64

config:
```php
  'enable_previews' => true,
  'enabledPreviewProviders' =>
  array (
   0 => 'OC\Preview\PNG',
   1 => 'OC\Preview\JPEG',
   2 => 'OC\Preview\GIF',
   3 => 'OC\Preview\BMP',
   4 => 'OC\Preview\XBitmap',
   5 => 'OC\Preview\MarkDown',
   6 => 'OC\Preview\MP3',
   7 => 'OC\Preview\TXT',
   8 => 'OC\Preview\Illustrator',
   9 => 'OC\Preview\Movie',
   10 => 'OC\Preview\MSOffice2003',
   11 => 'OC\Preview\MSOffice2007',
   12 => 'OC\Preview\MSOfficeDoc',
   13 => 'OC\Preview\OpenDocument',
   14 => 'OC\Preview\PDF',
   15 => 'OC\Preview\Photoshop',
   16 => 'OC\Preview\Postscript',
   17 => 'OC\Preview\StarOffice',
   18 => 'OC\Preview\SVG',
   19 => 'OC\Preview\TIFF',
   20 => 'OC\Preview\Font',
  ),
```

Installed packages:
```
ii  ffmpegthumbnailer                     2.0.8-2                              amd64        fast and lightweight video thumbnailer
ii  libav-tools                           6:11-2~leftclick1                    amd64        Multimedia player, encoder and transcoder
ii  php5-imagick                          3.1.2-1build1                        amd64        ImageMagick module for php5
```

I get thumbs of images, odt documents etc..., but not video's. I have mixed video's with WMV and MP4 files.

It did also not work on 8.0.4 but the needed depends for this is not clear if i'm missing anything.

**Comment by RealRancor** [comment]
Hi,

i think the main problem here is that there are several dependencies also not really logged if they are missing (Ref: https://github.com/owncloud/core/issues/17738).

I had a quick look at the files and collected the dependencies:

php functions not disabled in php.ini/disabled_functions: exec(), shell_exec(), escapeshellarg(), escapeshellcmd()

Needed binaries: avconv (from libav-tools) or ffmpeg (from ffmpeg package, not ffmpegthumbnailer)

**Comment by RealRancor** [comment]
Ah, the commands which are used for preview generation are also available here:

https://github.com/owncloud/core/blob/v8.1.0/lib/private/preview/movie.php#L85-L95

so you could also test on your console if ffmpeg / avconv are able to create a thumbnail at all.

**Comment by PVince81** [comment]
Please try again with 8.2.2. If the problem still happens, feel free to reopen.
