### ISSUE TITLE
webdav rejects file upload using "application/json"

### ISSUE THREAD

**Issue by domako** [owncloud/core#17722]
OC 8.1.0.8
when uploading any file using the content-type application/json via webdav an error (400) is reported, file is not uploaded.
To reproduce you may use any file regardless of the content.
webdav works with other content-type, like application/octet-stream.
Unfortunately some applications use json (like xmarks).
Error also occured on demo.owncloud.org

**Comment by LukasReschke** [comment]
Thanks a lot for reporting issues back to us!

We need some more information to properly support you with your issue!

Can I ask you to follow our guidelines for submitting bugs as described here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by PVince81** [comment]
Works for me with 8.1.1, both using cadaver and the sync client.

Closing due to lack of information. See https://github.com/owncloud/core/issues/17722#issuecomment-122364128
