### ISSUE TITLE
No access to server after update to 8.1

### ISSUE THREAD

**Issue by NordicTux** [owncloud/core#17724]
After updating to 8.1 I have no access to the server, neither by webinterface ("Cannot write into "config" directory!") nor by clients (Windows and Android). 

I'am running opensuse 13.2, Apache 2.4

**Comment by cunio** [comment]
Did you check SELinux context as written int the README.SELinux file in your installation directory?

**Comment by NordicTux** [comment]
Thanks for your reply.
As it is written in the file you mentioned there should be no need to follow the procedure because I have installed the official rpms.
However when I try execute the commands I receive the error "ValueError: SELinux policy is not managed or store cannot be accessed". I also set the rights for the user "wwwrun" for the config and data directory.

**Comment by keynet** [comment]
I have a maybe a related issue. I updated from 8.03 to 8.1 on SLES11/PHP 5.6.9 and the web login button is not working in Chrome on several platforms. It works OK, in IE8, IE11, Firefox (current) on Win32, Safari on IOS, Chrome on IOS

It doesn't work for me on Chrome on Win32(XP) or Win64(win7) or Android 4.3
* The login button just doesn't respond at all *

I have a warning about The "X-Frame-Options" HTTP header is not configured to equal to "SAMEORIGIN". Hoverer an inspection of the config and actual headers shows it is present, not cure that's related.

More importantly though, using the inspector, the login box code when working is: 
<input original-title="" id="submit" class="login primary" value="Log in" type="submit">

But when not working as above in Chrome:
<input type="submit" id="submit" class="login primary" value="Log in" disabled="disabled">

Which might help explain?

**Comment by RealRancor** [comment]
@keynet The not working login button is a completely different issue.

**Comment by NordicTux** [comment]
Thanks for the hints. 
Finally the solution was the script which can be found on the page when you follow the link with the error message ("Cannot write into "config" directory!"). After changing it according to my system an correcting "some" errors (chown -R root:${htuser} ==> chown -R root:${htgroup} 3 times) anything works fine again.

>>> START SCRIPT
#!/bin/bash
ocpath='/srv/www/htdocs/owncloud'
htuser='wwwrun'
htgroup='www'

find ${ocpath}/ -type f -print0 | xargs -0 chmod 0640
find ${ocpath}/ -type d -print0 | xargs -0 chmod 0750

chown -R root:${htgroup} ${ocpath}/
chown -R ${htuser}:${htgroup} ${ocpath}/apps/
chown -R ${htuser}:${htgroup} ${ocpath}/config/
chown -R ${htuser}:${htgroup} ${ocpath}/data/
chown -R ${htuser}:${htgroup} ${ocpath}/themes/

chown root:${htgroup} ${ocpath}/.htaccess
chown root:${htgroup} ${ocpath}/data/.htaccess

chmod 0644 ${ocpath}/.htaccess
chmod 0644 ${ocpath}/data/.htaccess 
>>> END SCRIPT
