### ISSUE TITLE
PHP Fatal error:  Uncaught EngineException: Class 'Imagick' not found on CI for PHP7

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#17727]
Ref https://github.com/owncloud/core/issues/16641

**Comment by LukasReschke** [comment]
Probably requires https://github.com/mkoppanen/imagick/tree/phpseven to be merged and installed on the CI server then :speak_no_evil:

**Comment by LukasReschke** [comment]
@DeepDiver1975 On a scale from :imp: to :beer: how likely is it that I can motivate you to compile this manually and install the module from the phpseven branch? :speak_no_evil:

**Comment by DeepDiver1975** [comment]
Let me try to find out if this is installed from apt or selfcompiled .....

**Comment by DeepDiver1975** [comment]
ah - yes phpenv install master

well - imagick has to be installed as pecl extension .... pfff

**Comment by DeepDiver1975** [comment]
imagick extenstion is now installed -> close
