### ISSUE TITLE
Update-loop on version bump if app is only enabled for a certain group

### ISSUE THREAD

**Issue by pbek** [owncloud/core#17734]
### Steps to reproduce
1. Enable app for only one group, for example "admin". (In table `oc_appconfig` the configValue for `enabled` would be `["admin"]`, everything is ok if it is `yes`.)
2. Version-bump an app
3. Do an `./occ upgrade`

### Expected behaviour
ownCloud should be "upgraded" and usable again. The version number in table `oc_appconfig` changes to the new version number.

### Actual behaviour
ownCloud tries to upgrade each time you are using `./occ upgrade`. The version number in table `oc_appconfig` doesn't change to the new version number.

### Server configuration
**Operating system**:
Ubuntu Linux 15.04
**Web server:**
Apache
**Database:**
MySQL
**PHP version:**
5.6.4
**ownCloud version:** (see ownCloud admin page)
8.2 pre alpha
**Updated from an older ownCloud or fresh install:**
update
**List of activated apps:**
Here's an other "issue", I enabled my app *ownbackup* for one group only, it shows as disabled in this list generated by `php occ app:list`.

Enabled:
  - bookmarks: 0.4
  - calendar: 0.7.2
  - contacts: 0.4.0.0
  - files: 1.1.9
  - files_external: 0.2.3
  - files_sharing: 0.6.2
  - files_trashbin: 0.6.3
  - files_versions: 1.0.6
  - news: 5.3.8
  - tasks: 0.7.1

Disabled:
  - encryption
  - ownbackup
  - provisioning_api
  - sharelinks
  - user_ldap
  - user_webdavauth

**The content of config/config.php:**
```json
{
    "system": {
        "instanceid": "ociuf2r3opzp",
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "\/home\/omega\/Web\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/localhost:8080",
        "dbtype": "mysql",
        "version": "8.2.0.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "maintenance": false
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### Web server error log
nothing was logged

#### ownCloud log (data/owncloud.log)
nothing was logged

**Comment by LukasReschke** [comment]
Confirmed. This also affects the web interface which does not allow updates anymore and the instance is inaccessible.

cc @icewind1991 @DeepDiver1975

**Comment by LukasReschke** [comment]
https://github.com/owncloud/core/pull/17698 will fix this

**Comment by LukasReschke** [comment]
Backport is at https://github.com/owncloud/core/pull/17736

**Comment by pbek** [comment]
Great!
Will the issue with `php occ app:list` also be handled?

**Comment by LukasReschke** [comment]
No. Can I ask you to file a new issue about this one? Thanks!

**Comment by pbek** [comment]
Done, thank you!

**Comment by LukasReschke** [comment]
Ref https://github.com/owncloud/core/issues/17737

**Comment by MorrisJobke** [comment]
master: #17698
