### ISSUE TITLE
Regression: linking to mysql db on ARMHF

### ISSUE THREAD

**Issue by poVoq** [owncloud/core#17735]
On a fresh Lubuntu 14.04 install (on a armhf system using the official .deb repositories) it is not possible to finalize the installation of owncloud 8.1 as it always shows the error that the user or password of the mysql is wrong (even with the root pw).

While when going back to 8.0 it works without a problem.

Will try next to upgrade from 8.0, but it would be good if direct installation of 8.1 was fixed.

**Comment by LukasReschke** [comment]
Thanks a lot for reporting issues back to us!

We need some more information to properly support you with your issue!

Can I ask you to follow our guidelines for submitting bugs as described here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by poVoq** [comment]
### Steps to reproduce
1. Install Lubuntu 14.04 on an ARM system (in my case a ODROID-X2)
2. Add official repository, install via apt-get, configure mysql database
3. open owncloud in browser, input all the mysql credentials, click on proceed.

### Expected behaviour
Should accept configured database credentials and forward to files view of the admin account.

### Actual behaviour
Gives an error that username or password of database is incorrect (both for the configured user and the mysql root user).

### Workaround
Install owncloud version 8.0 from the official repository, configure everything as described above, then everything works as expected. Afterwards add 8.1 repository and update owncloud.

### Server configuration
**Operating system**: Lubuntu 14.04 for ARM

**Web server: LAMP

**Database: Mysql

**PHP version: 5.4 (not sure)

**ownCloud version: 8.1

**Updated from an older ownCloud or fresh install: fresh

**Comment by LukasReschke** [comment]
@jnweiger THX

**Comment by PVince81** [comment]
@poVoq any more luck with the 8.1.1 package ?

**Comment by PVince81** [comment]
@poVoq when you say official, you mean the ones from ownCloud's OBS, not official from Debian/Ubuntu itself ?

Any more luck with 8.1.4 that just came out last week ?

**Comment by PVince81** [comment]
@jnweiger are we providing packages for ARM ?

**Comment by jnweiger** [comment]
@PVince81 that must be downstream packages. At OBS we only build openSUSE packages for ARM.

**Comment by jnweiger** [comment]
@poVoq it is unclear, what an official repository is to you. 
For me, the official repositories are defined as 'maintained by ownCloud'. They are
* 8.0  https://software.opensuse.org/download.html?project=isv%3AownCloud%3Acommunity%3A8.0&package=owncloud
* 8.1 https://software.opensuse.org/download.html?project=isv%3AownCloud%3Acommunity%3A8.1&package=owncloud
* 8.2 https://download.owncloud.org/download/repositories/8.2/owncloud/

**Comment by poVoq** [comment]
Well in this case official as in provided by the distribution. I guess this is fixed now, but I actually did not try to install it fresh again, so not sure. Anyways, I think we can close this for now.
