### ISSUE TITLE
Decryption and accessing files fail with 8.1 => encryption OK!

### ISSUE THREAD

**Issue by superacki** [owncloud/core#17730]
Hi all, 

at first: issue template will come directly after this post, wanted to add some background-information before: 
After update from 8.0 to 8.1 (with encryption enabled) I tried to migrate the enc-keys as mentioned in the documentation, but this failed due to the same several reasons already discussed here in the issue tracker. 
I tried some of the mentioned workarounds, but none of them put me trough the whole enc-migration process. 

That's why I chose another approach: I deleted all user data from the files-folder on server side using the web-interface and afterwards emptying also the trash bin.
Afterwards I synced my local client (Laptop) which deleted all data there as wellm (which I was aware of). 
Afterwards I uploaded all data again from my backup to the owncloud server using this local client. 
Result: all data on the server is encrypted (which is fine until here). It seems that this newly uploaded data is encrypted with the new encryption code, because I see this OC_DEFAULT-MODULE-strings inside the
encrypted files. 
Until here: everything fine so far. 

Problem: DEcryption seems to not work at all! :( => always same error message
- opening text-files in the webinterface: error message 
- downloading files via webdav (e.g. opening them on iOS-client): error message
- syncing files to another laptop: error message
- viewing pictures with galleryplus-app: error message and turning cursor

Error message is always this one: "503 Encryption not ready: multikeydecrypt with share key failed:error:0407106B:rsa routines:RSA_padding_check_PKCS1_type_2:block type is not 02"

I googled a bit and found that one possible reason *COULD BE* that public and private key do not match each other. 
I tried to check this and one interesting thing I can see on the filesystem: looking at the creation timestamp of the key files I can see that the public key was created 27 minutes later than the private key. 
Assuming that generating a key pair usually should run in some seconds, this really could be the reason for my problems.

QUESTIONs: 
- is my assumption right? 
- if so: how can I check if the keys match each other? 
- if they do not match: what could I do to solve this issue? 

Thanks a lot in advance. 

Issue template below.

**Comment by superacki** [comment]
### Steps to reproduce
1. started Update from 8.0 to 8.1
2. in between: running encryption key migration and run into several errors, but new keys were generated and new default module was activated
3. deleted all user-data from the server and the local laptop
4. uploaded user-data back from my backup => everything gets encrypted with new encryption infrastructure
5. try to access some of the uploaded data via web interface or iOS-client

### Expected behaviour
automatic decryption runs and accessing files is possible

### Actual behaviour
Decryption seem to fail and accessing as well as syncing these files raises error message: 
503 Encryption not ready: multikeydecrypt with share key failed:error:0407106B:rsa routines:RSA_padding_check_PKCS1_type_2:block type is not 02

### Server configuration
**Operating system**:
Ubuntu 14.04.2 LTS
**Web server:**
Apache 
**Database:**
Mysql 
**PHP version:**
5.5
**ownCloud version:** (see ownCloud admin page)
8.1.0.8
**Updated from an older ownCloud or fresh install:**
Updated from 8.0
**List of activated apps:**
 activity: 2.0.1
 - bookmarks: 0.4
 - calendar: 0.7.2
 - contacts: 0.4.0.0
 - documents: 0.10.0
 - encryption: 1.0.0
 - files: 1.1.9
 - files_locking:
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - galleryplus: 13.0.0
 - news: 5.3.8
 - ownnote: 1.02
 - provisioning_api: 0.2
 - tasks: 0.7.1
 - templateeditor: 0.1
 - user_webdavauth: 1.1.0.2
Disabled:
 - external
 - files_external
 - gallery
 - user_external
 - user_ldap

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system --public
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
<?php
$CONFIG = array (
  'instanceid' => 'oc83zk9bc0mv',
  'trusted_domains' => 
  array (
    0 => 'v97419.1blu.de',
    1 => 'www.axeldreher.net',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'https://v97419.1blu.de/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'ownlouddata',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_cloudhai',
  'installed' => true,
  'loglevel' => 1,
  'custom_csp_policy' => 'default-src \'self\'; script-src \'self\' \'unsafe-inline\' \'unsafe-eval\'; style-src \'self\' \'unsafe-inline\'; frame-src *; img-src *; font-src \'self\' data:; media-src *',
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'theme' => '',
  'maintenance' => false,
  'singleuser' => false,
  'appstore.experimental.enabled' => true,
  'enable_previews' => true,
  'enabledPreviewProviders' => array(
	'OC\Preview\PNG',
	'OC\Preview\JPEG',
	'OC\Preview\GIF',
	'OC\Preview\BMP',
	'OC\Preview\XBitmap',
	'OC\Preview\MP3',
	'OC\Preview\TXT',
	'OC\Preview\MarkDown'
),
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
NO
**Are you using encryption:** yes/no
YES
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO

### Client configuration
**Browser:**
Firefox 39.0
**Operating system:**
Windows 7
### Logs
#### ownCloud log (data/owncloud.log)
```
{"reqId":"tQfk5HT+Cb5UMrfQYOUY","remoteAddr":"79.232.80.139","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Encryption not ready: multikeydecrypt with share key failed:error:0407106B:rsa routines:RSA_padding_check_PKCS1_type_2:block type is not 02\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php(150): OC\\\\Connector\\\\Sabre\\\\File->convertToSabreException(Object(OCA\\\\Encryption\\\\Exceptions\\\\MultiKeyDecryptException))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1087): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #34)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(501): Sabre\\\\DAV\\\\Server->updateFile('axeld\\\/Dokumente...', Resource id #34, NULL)\\n#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":450}","level":4,"time":"2015-07-18T14:06:12+00:00"}
```

**Comment by karlitschek** [comment]
@schiesbn

**Comment by dcom42** [comment]
Same problem here too, logfile entry looks the same:

Exception: {"Message":"HTTP\/1.1 503 Encryption not ready: multikeydecrypt with share key failed:error:0407109F:rsa routines:RSA_padding_check_PKCS1_type_2:pkcs decoding error","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/file.php(197): OC\\Connector\\Sabre\\File->convertToSabreException(Object(OCA\\Encryption\\Exceptions\\MultiKeyDecryptException))\n#1 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1087): OC\\Connector\\Sabre\\File->put(Resource id #26)\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(501): Sabre\\DAV\\Server->updateFile('       ...     ', Resource id #26, NULL)\n#3 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#5 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#6 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#7 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n#8 \/var\/www\/owncloud\/remote.php(132): require_once('\/var\/www\/ownclo...')\n#9 {main}","File":"\/var\/www\/owncloud\/lib\/private\/connector\/sabre\/file.php","Line":450}

**Comment by xn--nding-jua** [comment]
Hi,

on my upgrade from 8.0.2 to 8.1 the migration failed and mixed up the public-keys of my users. I had to overwrite the public-keys of all users with a backed-up version. Afterwards everything worked well again. Maybe you can try this step.

BUT: if your problem is the same as mine: the already encrypted files have been encrypted using the wrong public-key that does not fit to your private key. So all encrypted files are (please correct me if I'm wrong) useless now and have to be reuploaded again using the corret public key.

You can check the public- and private-keys using a text-editor like notepad++. Open the backup-file and the current file and do a comparison. If they do not match, use the backup-version.

kind regards,
Chris

**Comment by superacki** [comment]
Hi, 

hrm, I really appreciate your help. I am not quite sure if I understand you right: 
What do you mean with backup-version? The old key which was used before update to 8.1? 
If so: Yeah, I can do that but I expect that they are different, because the private keys are different as well if I remember correctly. It seems to me that OC created completely new public and private keys with 8.1 so I Iguess that they will not match to the old versions anyway. But I will check, maybe I mixed something. If I am right than I still need a hint how to check if new private key and new public key match together or as an alternative I would need a hint how to generate a completely new pair of keys from scratch and re-encrypt all files again (which should also solve this issue at the end). 

Kind regards, 
Axel

**Comment by xn--nding-jua** [comment]
Hi,

yes, I mean the pre-8.1-keyfiles. If the private- and public-keys would be changed, than you could not access your files anymore, because they have been encrypted using public- and private-keys together. Because your private- and/or public-keys have changed during the migration you cannot access your files any more now.

You can do the following:
1. make a backup of the newly generated 8.1 keyfiles
2. replace these new 8.1 keyfiles with the old pre-8.1-keyfiles (your old files should now be decryptable again)
3. if something goes wrong, you can use your new backup again.


But for me replacing the wrong new 8.1 keyfiles with the pre-8.1 files worked.


kind regards,
Chris

**Comment by PVince81** [comment]
@schiesbn any hints ? Is this fixed in 8.1.1 ?

**Comment by superacki** [comment]
Thanks to Chris, his hint worked for me as well. I replaced the strange not matching 8.1-key-pair with the keys from the oldest migration backup, deleted all files then on server and loaded data back up from local clients which encrypted them again with the replaced keys- everything seems to be fine now: 

- Accessing files from web-interface works again, gallery works again
- syncing with all local clients (including iOS) works again. 

So.... what's the conclusion here? I guess I ran into a maybe seldom situation during generation of the keypair. I checked all migration-encryption-backup-folders which were created during my several failed runs of migrating the keys. Each of these backup-folders had a newly created keypair with same timestamps for private key and public key. 
Except the "working" folder: those keys were generated with more than 20 minutes time in between. I guess that in this case something with the key-generation went wrong which I didn't notice. 

Maybe it would be good to add some checks in the migrate:keys-procedure to have a look if the keys really match together before the procedure finishes its work (maybe with encrypting and decrypting a test file and check if the result is the same and then delete the test file or something.)

Thanks for all hints which brought me to this point :)

**Comment by Vectrex** [comment]
After having substantial problems with migrating from 8.0 to 8.1 (see issue #17683), I wiped both user files and database entirely and it seemed as if the application was behaving properly over the last few weeks. However, this morning I got a batch of error messages like the one below. Any idea how "incopatible" keys could have sneaked into the system? Any suggestions how to fix this?

Exception: {"Message":"multikeydecrypt with share key failed:error:0407106B:rsa routines:RSA_padding_check_PKCS1_type_2:block type is not 02","Code":0,"Trace":"#0 \/var\/www\/owncloud\/apps\/encryption\/lib\/keymanager.php(364): OCA\\Encryption\\Crypto\\Crypt->multiKeyDecrypt('????????|??5:7u...', '?N\"?????1???+?X...', '-----BEGIN PRIV...')\n#1 \/var\/www\/owncloud\/apps\/encryption\/lib\/crypto\/encryption.php(141): OCA\\Encryption\\KeyManager->getFileKey('\/isolde\/files\/I...', 'susie')\n#2 \/var\/www\/owncloud\/lib\/private\/files\/stream\/encryption.php(249): OCA\\Encryption\\Crypto\\Encryption->begin('\/isolde\/files\/I...', 'susie', 'r', Array, Array)\n#3 [internal function]: OC\\Files\\Stream\\Encryption->stream_open('ocencryption:\/\/', 'r', 0, NULL)\n#4 \/var\/www\/owncloud\/lib\/private\/files\/stream\/encryption.php(189): fopen('ocencryption:\/\/', 'r', false, Resource id #30)\n#5 \/var\/www\/owncloud\/lib\/private\/files\/stream\/encryption.php(171): OC\\Files\\Stream\\Encryption::wrapSource(Resource id #29, 'r', Resource id #30, 'ocencryption', 'OC\\Files\\Stream...')\n#6 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/encryption.php(425): OC\\Files\\Stream\\Encryption::wrap(Resource id #29, 'files\/Inge\/SRVM...', '\/isolde\/files\/I...', Array, 'susie', Object(OCA\\Encryption\\Crypto\\Encryption), Object(OCA\\Files_Locking\\LockingWrapper), Object(OC\\Files\\Storage\\Wrapper\\Encryption), Object(OC\\Encryption\\Util), Object(OC\\Encryption\\File), 'r', 2821528, 2103808, 8192)\n#7 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(285): OC\\Files\\Storage\\Wrapper\\Encryption->fopen('files\/Inge\/SRVM...', 'r')\n#8 \/var\/www\/owncloud\/apps\/files_sharing\/lib\/sharedstorage.php(416): OC\\Files\\Storage\\Wrapper\\Wrapper->fopen('files\/Inge\/SRVM...', 'r')\n#9 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(285): OC\\Files\\Storage\\Shared->fopen('SRVM_290615_fin...', 'r')\n#10 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/encryption.php(514): OC\\Files\\Storage\\Wrapper\\Wrapper->fopen('SRVM_290615_fin...', 'r')\n#11 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/encryption.php(449): OC\\Files\\Storage\\Wrapper\\Encryption->copyBetweenStorage(Object(OCA\\Files_Trashbin\\Storage), 'SRVM_290615_fin...', 'files_trashbin\/...', true, true)\n#12 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(535): OC\\Files\\Storage\\Wrapper\\Encryption->moveFromStorage(Object(OCA\\Files_Trashbin\\Storage), 'SRVM_290615_fin...', 'files_trashbin\/...')\n#13 \/var\/www\/owncloud\/apps\/files_trashbin\/lib\/trashbin.php(213): OC\\Files\\Storage\\Wrapper\\Wrapper->moveFromStorage(Object(OCA\\Files_Trashbin\\Storage), 'SRVM_290615_fin...', 'files_trashbin\/...')\n#14 \/var\/www\/owncloud\/apps\/files_trashbin\/lib\/storage.php(152): OCA\\Files_Trashbin\\Trashbin::move2trash('Inge\/SRVM_29061...')\n#15 \/var\/www\/owncloud\/apps\/files_trashbin\/lib\/storage.php(94): OCA\\Files_Trashbin\\Storage->doDelete('SRVM_290615_fin...', 'unlink')\n#16 \/var\/www\/owncloud\/lib\/private\/files\/view.php(1006): OCA\\Files_Trashbin\\Storage->unlink('SRVM_290615_fin...')\n#17 \/var\/www\/owncloud\/lib\/private\/files\/view.php(600): OC\\Files\\View->basicOperation('unlink', '\/Inge\/SRVM_2906...', Array)\n#18 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/file.php(279): OC\\Files\\View->unlink('\/Inge\/SRVM_2906...')\n#19 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Tree.php(179): OC\\Connector\\Sabre\\File->delete()\n#20 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(287): Sabre\\DAV\\Tree->delete('Inge\/SRVM_29061...')\n#21 [internal function]: Sabre\\DAV\\CorePlugin->httpDelete(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#22 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#23 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:DELETE', Array)\n#24 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#25 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n#26 \/var\/www\/owncloud\/remote.php(132): require_once('\/var\/www\/ownclo...')\n#27 {main}","File":"\/var\/www\/owncloud\/apps\/encryption\/lib\/crypto\/crypt.php","Line":441}

**Comment by Foggalong** [comment]
Same problem here, and I never even had encryption enabled :/

**Comment by PVince81** [comment]
Please try upgrading to 9.0.1. A lot of encryption bugs have been fixed meanwhile.

If you're still having this issue, please reopen.

**Comment by cdamken** [comment]
Looks like is still happening in 9.0. and 9.1: https://github.com/owncloud/core/issues/18786#issuecomment-235304198
