### ISSUE TITLE
Excessive error messages on Files_Trashbin after upgrade from OC6 to OC7

### ISSUE THREAD

**Issue by gig13** [owncloud/core#17747]
### Steps to reproduce
1. Upgrade from OC6 to OC7

### Expected behaviour
All apps should upgrade successfully

### Actual behaviour
There are an excessive amount of error messages regarding the trashbin app and cannot insert NULL into oc_files_trash.

### Server configuration
**Operating system**: RHEL

**Web server:** Apache

**Database:** Oracle 11.2

**PHP version:** 5.4.40

**ownCloud version:** 7.0.6.2

**Updated from an older ownCloud or fresh install:** Updated

**List of activated apps:** See Configuration Report

**The content of config/config.php:**

```
"config": {
        "instanceid": "12345",
        "passwordsalt": "xxxx Value is set but was removed by reporting app for security reasons xxxx",
        "trusted_domains": [
            "blah1",
            "blah2",
            "blah3"
        ],
        "datadirectory": "\/var\/www\/html\/owncloud-enterprise\/data",
        "dbtype": "oci",
        "version": "7.0.6.2",
        "dbname": "owntest",
        "dbhost": "blah",
        "dbtableprefix": "oc_",
        "dbtablespace": "users",
        "loglevel": "2",
        "dbuser": "owncloud",
        "dbpassword": "xxxx Value is set but was removed by reporting app for security reasons xxxx",
        "installed": true,
        "log_type": "owncloud",
        "logfile": "\/var\/log\/owncloud\/owncloud.log",
        "ldapIgnoreNamingRules": false,
        "theme": "",
        "maintenance": false,
        "overwriteprotocol": "https",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "blah.blah",
        "mail_smtpport": 25,
        "session_lifetime": 5400,
        "trashbin_retention_obligation": 45,
        "singleuser": false,
        "appstoreenabled": false,
        "has_internet_connection": false,
        "supportedDatabases": [
            "mysql",
            "pgsql",
            "oci",
            "mssql"
        ],
        "secret": "blah",
        "share_folder": "\/Shared"
    },
```

**Are you using external storage, if yes which one:** NO

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration 

```
In config report
```

#### ownCloud log (data/owncloud.log)
```
I{"app":"hook","message":"error while running hook
(OCA\\Files_Trashbin\\Hooks::remove_hook): An exception occurred while
executing 'INSERT INTO \"oc_files_trash\"
(\"id\",\"timestamp\",\"location\",\"user\") VALUES
(?,?,?,?)':\n\nORA-01400: cannot insert NULL into
(\"OWNCLOUD\".\"oc_files_trash\".\"type\")","level":3,"time":"2015-07-17T17:25:04+00:00"}
{"app":"hook","message":"error while running hook
(OCA\\Files_Trashbin\\Hooks::remove_hook): An exception occurred while
executing 'INSERT INTO \"oc_files_trash\"
(\"id\",\"timestamp\",\"location\",\"user\") VALUES
(?,?,?,?)':\n\nORA-01400: cannot insert NULL into
(\"OWNCLOUD\".\"oc_files_trash\".\"type\")","level":3,"time":"2015-07-17T17:26:40+00:00"} 
```

@MorrisJobke

**Comment by bboule** [comment]
@VicDeo this was the user that we did the oracle upgrade with and it seems we are having some post upgrade issues as it relates to trash bin (one of the problematic apps during the upgrade) any thoughts?

**Comment by gig13** [comment]
@bboule @VicDeo @MorrisJobke 
Any updates?

**Comment by VicDeo** [comment]
@bboule I can assume that not null requirement for `type` column 
https://github.com/owncloud/core/blob/stable6/apps/files_trashbin/appinfo/database.xml#L52 was not changed to 
https://github.com/owncloud/core/blob/stable7/apps/files_trashbin/appinfo/database.xml#L61
But this is only a guess without looking `oc_files_trash` structure after upgrade

**Comment by felixboehm** [comment]
Please update to at least to version 7.0.8, there is an important fix for the trashbin app

**Comment by MorrisJobke** [comment]
> Please update to at least to version 7.0.8, there is an important fix for the trashbin app

@gig13 @bboule @cburnard This is for you ;)

**Comment by PVince81** [comment]
Did it work ?

**Comment by gig13** [comment]
Yes, closing!
