### ISSUE TITLE
Changing password is not possible

### ISSUE THREAD

**Issue by Ninos** [owncloud/core#17740]
Since OwnCloud 8.1 users cannot change their passwords anymore. They always get following message:
"Passwort konnte nicht geändert werden" -> "Password could not be changed"

I activated and deactivated apcu without success. I just added following changes in the config.php
```
'skeletondirectory' => '',
'memcache.local' => '\OC\Memcache\APCu',
```

DB: MariaDB
PHP: php-fpm 5.6
OS: Debian Jessie
Webserver: Apache2.4

**Comment by DeepDiver1975** [comment]
Works for me.

@Ninos Any errors in the browser console or in data/owncloud.log? THX

**Comment by nickvergessen** [comment]
Please use:
https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

was it "Das Passwort konnte nicht geändert werden. Vielleicht war das alte Passwort falsch."?

The exact string helps to find the place that fails.

**Comment by Ninos** [comment]
Ok sorry guys, can be closed. Was too stupid and wrote the new password into both fields (old password, new password). The feedback message is just:
`Das Passwort konnte nicht geändert werden`. `. Vielleicht war das alte Passwort falsch.` is missing here. I may would add such info, because most systems have also a validation field for the new password, so there should be also other peoples, which add the new password to both fields.
