### ISSUE TITLE
HTTP Basic auth broken

### ISSUE THREAD

**Issue by Dreamsorcerer** [owncloud/core#17742]
When trying to use basic auth to sync notes with the ownCloud notes app, I receive a 500 error. For basic auth to work correctly, the server should return a 401 error.

This worked correctly in OC 8.0, but has changed to returning a 500 error in 8.1. This breaks some implementations, such as libsoup, see: https://mail.gnome.org/archives/libsoup-list/2015-July/msg00007.html

This can be reproduced by installing the notes app and navigating to:
http://user:password@owncloud.url/index.php/apps/notes/api/v0.2/notes

**Comment by LukasReschke** [comment]
Potential patch at https://github.com/owncloud/core/pull/17743
