### ISSUE TITLE
& needs encoding in HTML

### ISSUE THREAD

**Issue by szepeviktor** [owncloud/core#17757]
Please encode the ampersand sign.

```html
<a id="logout" href="/index.php?logout=true&requesttoken=I0c4Ocfd3eqIC%2FHu8jLNHf">
```
v8.1.0.8
URL: https://*.net/index.php/apps/files

**Comment by szepeviktor** [comment]
Here it is:
https://github.com/owncloud/core/blob/7959605e4e389ee26705094656f636f23b9cfb8d/lib/private/user.php#L408

**Comment by MorrisJobke** [comment]
@szepeviktor Please have a look at #17766

**Comment by szepeviktor** [comment]
Thank you.
You have an interesting project.

**Comment by MorrisJobke** [comment]
This ticket will be closed automatically once the change enters the main code. ;)

**Comment by jancborchardt** [comment]
@szepeviktor you’re very welcome in our #owncloud-dev channel on IRC by the way. :) If you find any more issues, you can also have a try at them.
