### ISSUE TITLE
Owncloud freezes when moving folders/ files from non-shared folders to shared folders shared by another user

### ISSUE THREAD

**Issue by KKyang** [owncloud/core#17769]
### Steps to reproduce
1. Upload something to account A
2. Drag the file to a shared folder shared by B

### Expected behaviour
The file is moved and the permissions is changed correctly.

### Actual behaviour
Owncloud freezes and acts really slow. If refresh, sometimes the file is successfully moved and sometimes isn't.

While operating, the log keeps repeating debug messages:
```
Debug DeleteOrphanedSharesJob 0 orphaned share(s) deleted 2015-07-21T00:45:01+00:00 
Debug DeleteOrphanedSharesJob 0 orphaned share(s) deleted 2015-07-21T00:15:01+00:00 
Debug DeleteOrphanedSharesJob 0 orphaned share(s) deleted 2015-07-20T23:45:01+00:00 
Debug DeleteOrphanedSharesJob 0 orphaned share(s) deleted 2015-07-20T23:15:02+00:00 
```
### Server configuration
**Operating system**:
Ubuntu 14.04
**Web server:**
Apache 2.4.7
**Database:**
MySQL
**PHP version:**
5.5.9
**ownCloud version:** (see ownCloud admin page)
8.1 upgrade from 8.0.5
**Updated from an older ownCloud or fresh install:**
 upgrade from 8.0.5
**List of activated apps:**
All default settings.

**Comment by karlitschek** [comment]
@schiesbn any idea?

**Comment by nickvergessen** [comment]
Are you using the web cron?

**Comment by KKyang** [comment]
I'm using Ubuntu system's cron service.

**Comment by PVince81** [comment]
@KKyang was the folder already shared before the upgrade ?
Does the problem appear for new folders / new shares ?
Is it a big file ?

**Comment by PVince81** [comment]
also please check the Javascript console in the browser and also the network console, you might see a red entry with an error code.

**Comment by KKyang** [comment]
No, the folder is uploaded after upgrade to OwnCloud 8.1, and the shared file is created before the upgrade. It's a folder with total size about 51MB with hundreds of files in it. I'll check the Javascript console later for further information.

**Comment by PVince81** [comment]
Does it happen also if the share is created after the upgrade ? This is mostly to rule out potential issues in the "oc_share" data structure.

You might want to retry with 8.1.3 which contains many fixed related to shares.

**Comment by MorrisJobke** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. 

Please reopen if you still encounter this issue with the [latest stable version](http://owncloud.org/install/) and then please use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md). 

Thank you!
