### ISSUE TITLE
backspace key in document editing does not work for Tor Browser

### ISSUE THREAD

**Issue by mdik** [owncloud/core#17772]
It is not possible to use the backspace key while editing a document in Tor Browser 5.0a3 (based on Mozilla Firefox 38.1.0) in Linux – tested with owncloud 8.1.x.

Vanilla Mozilla Firefox works.

Steps to reproduce:

1. open http://demo.owncloud.org
2. open a document and try to edit it --> backspace key won't work: deleting a character is only possible with delete key

**Comment by mdik** [comment]
This is related to https://github.com/owncloud/core/issues/11530

**Comment by PVince81** [comment]
Are you talking about the documents app with a rich editor ? If yes, please raise in https://github.com/owncloud/documents instead.

**Comment by MorrisJobke** [comment]
Please report this in the documents app -> therefore closing it here.
