### ISSUE TITLE
Follow IEEE 1541-2002 to show folders and files sizes

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#17774]
Currently sizes are using the old system for example 1048576 bytes are written as 1MB.

I suggest to follow the standard [IEEE 1541-2002] (https://en.wikipedia.org/wiki/IEEE_1541-2002) and call it 1MiB.

![screen shot 2015-07-21 at 09 50 19](https://cloud.githubusercontent.com/assets/9048796/8795608/a644279e-2f8e-11e5-920b-c680d8dd2f85.png)

**Comment by DeepDiver1975** [comment]
@jancborchardt UX related - optinion?

**Comment by jancborchardt** [comment]
We had the discussion before, not sure about the issue number. Bottom line: I don’t particularly care, but neither Dropbox nor Google Drive nor another popular system I saw do it like this. Hence I think it might result in more confusion rather than benefit simply for the sake of being scientifically correct.

**Comment by tflidd** [comment]
You could as well use the real MB=10⁶ bytes like OS X and Ubuntu.
here is the duplicate: https://github.com/owncloud/core/issues/13386

**Comment by SergioBertolinSG** [comment]
I think seeing the units with the correct abbreviation would make oC feel more precise and increase the willingness to use it. Also might be interesting in some scientific environments to have the unit clear. I'd go for the MiB/GiB/KiB abbreviation.

**Comment by jancborchardt** [comment]
@SergioBertolinSG that sounds like completely subjective arguments. ;) Let's continue in the original issue https://github.com/owncloud/core/issues/13386, closing this.
