### ISSUE TITLE
After migration from 8.0.4 to 8.1.0 some of files are not readable

### ISSUE THREAD

**Issue by alexxy** [owncloud/core#17776]
### Steps to reproduce
1. Update from 8.0.4 to 8.1.0 with encryption enabled

### Expected behaviour
All should be fine (files should be readable)
### Actual behaviour
Some of user files are not readable
part of files has header 
HBEGIN:cipher:AES-256-CFB:HEND
part has 
HBEGIN:oc_encryption_module:OC_DEFAULT_MODULE:cipher:AES-256-CFB:HEND
### Server configuration
**Operating system**:
Gentoo Linux
**Web server:**
Apache
**Database:**
MariaDB
**PHP version:**
5.6
**ownCloud version:** (see ownCloud admin page)
8.1.0
**Updated from an older ownCloud or fresh install:**
Updated from 8.0.4
**List of activated apps:**
encryption
**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:**
yes

**Comment by karlitschek** [comment]
@schiesbn can you have a look?

**Comment by nickvergessen** [comment]
IIRC that is the problem in 8.1.0 that is fixed in 8.1.1?

**Comment by nickvergessen** [comment]
Possibly related https://github.com/owncloud/core/issues/17574

**Comment by alexxy** [comment]
I tryed #17574 however data still inacessible.

**Comment by schiesbn** [comment]
> HBEGIN:cipher:AES-256-CFB:HEND

This are files written with ownCloud < 8.1

> HBEGIN:oc_encryption_module:OC_DEFAULT_MODULE:cipher:AES-256-CFB:HEND

This are files written with ownCloud 8.1

That's OK ownCloud is able to handle both headers correctly. Do you have any errors in your log file? What is the exact message you get if you try to open a broken file.

Also pick one of the broken files and check following:
- How does the header look like
- Does all keys exists you need at least ````data/<user>/files_encryption/keys/files/<path_of_file>/<filename>/OC_DEFAULT_MODULE/fileKey```` and ````data/<user>/files_encryption/keys/files/<path_of_file>/<filename>/OC_DEFAULT_MODULE/<user>.shareKey````

**Comment by PVince81** [comment]
@alexxy any update ?

**Comment by MorrisJobke** [comment]
Closed due to inactivity
