### ISSUE TITLE
Sharing folder in S3, the first letter of the folder is missed in the share dialog.

### ISSUE THREAD

**Issue by davitol** [owncloud/core#17770]
### Steps to reproduce
1. Upload a file using S3 as external storage inside a Subfolder
2. Share the subfolder with another user
3. Browse into the Subfolder and click on the share button of the file

### Expected behaviour
The name of the subfolder should be visible

### Actual behaviour
The first letter of the subfolder's name is missed

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:"version":"8.0.5.2","versionstring":"8.0.5","edition":""

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - files
 - files_encryption
 - files_external
 - files_sharing
 - files_trashbin
 - files_versions
 - provisioning_api
Disabled:
 - user_ldap
 - user_webdavauth

**Are you using external storage, if yes which one:** yes; S3
**Are you using encryption:** yes
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

![captura de pantalla 2015-07-21 a las 8 53 09](https://cloud.githubusercontent.com/assets/10596560/8794879/c8c6cd82-2f87-11e5-9df5-ddb5cd222ab7.png)

**Comment by cmonteroluque** [comment]
annoying but giving timing and severity, move to 8.0.7

**Comment by PVince81** [comment]
Hmm, missing first letter. Let me guess: there might be code that assumes that a path had a leading slash so it trims the first char, but in that situation it doesn't, for some reason.
There are plenty of places in the code where such assumptions are made...

That's just a very wild guess.

**Comment by cmonteroluque** [comment]
@Xenopathic are you working on files_external right now? Is this something you could have a look?

**Comment by Xenopathic** [comment]
Just reproduced this with SFTP, I think it's a generic problem with all external storages. Investigating.

**Comment by MorrisJobke** [comment]
@cmonteroluque Regarding the backportt (stable8 and stable8.1) read https://github.com/owncloud/core/pull/18389#issuecomment-132199493

**Comment by MorrisJobke** [comment]
8.2 only -> see https://github.com/owncloud/core/pull/18389#issuecomment-132203009
