### ISSUE TITLE
webdav (davfs): percent character (%) in filename leads to file renaming

### ISSUE THREAD

**Issue by tYYGH** [owncloud/core#17771]
### Steps to reproduce
1. Mount (mount.davfs) Owncloud (https://my_server.org/OC/remote.php/webdav) on ```~/OC/```.
2. Copy file ```800px-Dette_publique_france_%25_du_PIB.png``` under a subdirectory of ```~/OC/```.
3. Compare source and destination (under the data/ folder): filename has changed; contents is OK.

### Expected behaviour
The destination file should be named ```800px-Dette_publique_france_%25_du_PIB.png```.

### Actual behaviour
The destination file is named ```800px-Dette_publique_france_%_du_PIB.png```.

### Server configuration
**Operating system**: 3.16.0-4-kirkwood #1 Debian 3.16.7-ckt11-1 (2015-05-24) armv5tel GNU/Linux

**Web server:** nginx-full                     1.6.2-5                      armel

**Database:** postgresql-9.4                 9.4.3-0+deb8u1               armel

**PHP version:** php5-fpm                       5.6.9+dfsg-0+deb8u1          armel

**ownCloud version:** 8.1

**Updated from an older ownCloud or fresh install:** updated from older

**List of activated apps:**

```
Enabled:
 - activity: 2.0.1
 - calendar: 0.7.1
 - contacts: 0.4.0.0
 - files: 1.1.9
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - updater: 0.6
Disabled:
 - encryption
 - external
 - files_external
 - files_locking
 - files_pdfviewer
 - provisioning_api
 - templateeditor
 - user_external
 - user_ldap
 - user_webdavauth
```

**The content of config/config.php:**

```
  'instanceid' => 'fake instance id',
  'passwordsalt' => 'fake password salt',
  'overwriteprotocol' => 'https',
  'overwritehost' => 'my_server.org:443',
  'trusted_domains' =>
  array (
    0 => 'my_server.org',
  ),
  'datadirectory' => '/var/owncloud/data',
  'dbtype' => 'pgsql',
  'version' => '8.1.0.8',
  'dbname' => 'fake db name',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'fake db user',
  'dbpassword' => 'fake db password',
  'enable_previews' => false,
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'mail_from_address' => 'OwnCloud',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'my_server.org',
  'loglevel' => 2,
  'secret' => 'fake secret',
  'forcessl' => true,
```

**Are you using external storage, if yes which one:** NO

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** NO

### Client configuration
**Browser:** davfs2                         1.5.2-1                      armel

**Operating system:** 3.16.0-4-kirkwood #1 Debian 3.16.7-ckt11-1 (2015-05-24) armv5tel GNU/Linux

#### Web server error log
No visible error.

#### ownCloud log (data/owncloud.log)
No visible error.

#### Browser log
No visible error while ```cp -a``` is running.

**Comment by DeepDiver1975** [comment]
@tYYGH can you try with another webdav client? e.g. cadaver - THX

**Comment by tYYGH** [comment]
Just to be sure, I first logged in to the owncloud web UI. The file was there, and it was wrongly named ```800px-Dette_publique_france_%_du_PIB.png```, just like I saw under the data/ directory.

Next, I logged to owncloud using cadaver, and listed the contents. The results are strange:
```
dav:/owncloud/remote.php/webdav/…/> ls 800px-Dette_publique_france_%25_du_PIB.png
Listing collection `/owncloud/remote.php/webdav/…/800px-Dette_publique_france_%2525_du_PIB.png/': succeeded.
dav:/owncloud/remote.php/webdav/…/> ls 800px-Dette_publique_france_%_du_PIB.png
Listing collection `/owncloud/remote.php/webdav/…/800px-Dette_publique_france_%25_du_PIB.png/': collection is empty.
```
:-/
I don't know what to make of this… There is obviously something special with the "percent" character, probably due to URL-encoding.

Then I tried to copy it anew, and "ls" again:
```
dav:/owncloud/remote.php/webdav/…/> put "800px-Dette_publique_france_%25_du_PIB.png"
Uploading 800px-Dette_publique_france_%25_du_PIB.png to `/owncloud/remote.php/webdav/…/800px-Dette_publique_france_%2525_du_PIB.png':
Progress: [=============================>] 100,0% of 87043 bytes succeeded.
dav:/owncloud/remote.php/webdav/…/> ls 800*
[Matching... 1 match.]
Listing collection `/owncloud/remote.php/webdav/…/800px-Dette_publique_france_%2525_du_PIB.png/': succeeded.
dav:/owncloud/remote.php/webdav/…/> ls 800px-Dette_publique_france_%25_du_PIB.png
Listing collection `/owncloud/remote.php/webdav/…/800px-Dette_publique_france_%2525_du_PIB.png/': succeeded.
dav:/owncloud/remote.php/webdav/…/> ls 800px-Dette_publique_france_%_du_PIB.png
Listing collection `/owncloud/remote.php/webdav/…/800px-Dette_publique_france_%25_du_PIB.png/': collection is empty.
```

So, no change, and the output is still confusing.
In the web UI, the file still has the wrong name, and DavFS still reports the same, too:
```
$ mount ~/OC
$ ls -l ~/OC/…/800*
-rwxr-xr-x 1 me me 87043 juil. 22 13:59 /home/me/OC/…/800px-Dette_publique_france_%_du_PIB.png
```

**Comment by PVince81** [comment]
It looks like cadaver uploaded it properly when you did a PUT. But for some reason the web UI still shows that file wrong ?

**Comment by tYYGH** [comment]
With '%25' being the URL-encoded version of '%', I suppose that a message such as ```Listing collection `…': …``` from cadaver shows the URL-encoded web address, not the file path, which would explain the difference between my command and the output. Based on this hypothesis, cadaver is completely coherent, if a bit misleading.

My guess is that the ownCloud server does not handle the URL-encoding correctly:
- upon receiving an URL-encoded path, the server seems to double-decode it, with '%2525' becoming '%25', and then simply '%';
- likewise, the URL-encoded '_%25_du' would become '_%_du', and then fail in the second decode pass, because '%_d' is an invalid URL-encoded character, which would explain the second ls' failure;
- upon listing the contents of a collection, the reverse would happen: '%' becomes '%25', then '%2525', which is decoded back to '%25' by cadaver: success in the first ls.

However, this does not agree with what is shown by DavFS. The apparent difference between DavFS and Cadaver is troubling. I'll have to do more tests using an alternate webdav server…

**Comment by PVince81** [comment]
@tYYGH did you get a chance to test with another DAV server like Apache's mod_dav ?

You might also want to try with more recent ownCloud versions where the Sabre library was updated, which is the one processing URLs and Webdav routes.

If it still doesn't work, feel free to reopen.
