### ISSUE TITLE
Unable to drag and drop a folder using Firefox

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#17788]
### Env
8.0, 8.1, PHP 5.5

### Steps to reproduce

1. Create a folder which contains a few files
2. Drag and drop the folder in the list of file in the Web GUI

### Expected results

Folder should be updated and structure should be created in the GUI

### Actual result

Firefox
On 8.0. An empty yellow notification is shown and nothing happens
On 8.1. A yellow notification telling me I can't upload a directory or that my files has 0 bytes

Chrome
Works as expected

### Logs

Nothing in the browser's logs

### Solution

If folders are blocked on Firefox because it's not technically possible to upload them, then maybe the message should be improved to indicate that it's a browser limitation, if not, it would be nice to fix this for Firefox.

**Comment by RealRancor** [comment]
Drag'n'drop of folders only works with Chrome according to: https://github.com/owncloud/documentation/pull/1326 and https://doc.owncloud.org/server/8.1/user_manual/webinterface.html#navigating-the-main-user-interface

**Comment by szepeviktor** [comment]
Do you have CSP on your browser console?
https://github.com/owncloud/core/issues/17758#issuecomment-122980055

**Comment by KKyang** [comment]
Opera also works.

**Comment by szepeviktor** [comment]
Opera has the same engine as Chrome.

**Comment by RealRancor** [comment]
If https://github.com/owncloud/documentation/pull/1326 needs update please report this to https://github.com/owncloud/documentation/issues

**Comment by oparoz** [comment]
The problem is that nobody is going to read the documentation for something like this. At least there is now an error message on 8.1, but I think it can still be confusing if someone gives you the instruction to drag and drop a folder (or you used to doing it using another browser) and you get that error message. 

Maybe the link to the documentation should be added there?

**Comment by PVince81** [comment]
I agree: if it is possible to catch this error, then show the proper message. I thought there was already a ticket for this but couldn't find it.

**Comment by ggeorgg** [comment]
It seems that this API is going to be implemented in Firefox but I don't know when this really will be the case (or maybe it is already implented?).

https://wicg.github.io/directory-upload/proposal.html

https://bugzilla.mozilla.org/show_bug.cgi?id=1164310
https://bugzilla.mozilla.org/show_bug.cgi?id=1188880

https://jwatt.org/blog/2015/09/14/directory-picking-and-drag-and-drop

https://dev.windows.com/en-us/microsoft-edge/platform/status/directoryupload
https://dev.windows.com/en-us/microsoft-edge/platform/status/webkitdirectoryandwebkitrelativepath

**Comment by oparoz** [comment]
Thanks @ggeorgg

**Comment by PVince81** [comment]
Not a bug in ownCloud. Once Firefox implements the API like Chrome does, drag and drop upload should work directly. If it doesn't at this time, please reopen.
