### ISSUE TITLE
Prepare for PHP 7

### ISSUE THREAD

**Issue by szepeviktor** [owncloud/core#17783]
[Beta is out](http://php.net/archive/2015.php).
Please add PHP 7 to CI.

**Comment by DeepDiver1975** [comment]
duplicate - please use the search

**Comment by szepeviktor** [comment]
Excuse me.

**Comment by LukasReschke** [comment]
Meta issue: https://github.com/owncloud/core/issues/16641

**Comment by szepeviktor** [comment]
Thank you.
