### ISSUE TITLE
Upgrade Problem (No internet connection)

### ISSUE THREAD

**Issue by aspdye** [owncloud/core#17784]
You speak German? - Read the Theard in the OwnCloud Forum: 
https://forum.owncloud.org/viewtopic.php?f=21&t=29364

### Steps to reproduce
 1. Have a OwnCloud Instance!
 2. Try an manual upgrade (delete all, save config and data) and Upgrade to 8.1
 3. After Upgrade, server tells me, that I have no Internet connection.

### Expected behaviour
Server should have an Internet Connection. (for appstore, updater,...)
Internet connection works with 8.0.4 and 8.1 (for 8.1 only if i make an clean install)

### Actual behaviour
Error Message in Admin Panel of OwnCloud. No Internet Connection. -> No way to connect to the Appstore or Updater.

Error message in German:

Dieser Server hat keine funktionierende Internetverbindung. Dies bedeutet, dass einige Funktionen wie das Einhängen externen Speicherplatzes, Update-Benachrichtigungen oder die Installation von Drittanbieter-Apps nicht funktionieren werden. Der Fernzugriff auf Dateien und der Versand von E-Mail-Benachrichtigungen kann ebenfalls nicht funktionieren. Es wird empfohlen, die Internetverbindung dieses Servers zu aktivieren, wenn Du alle Funktionen nutzen möchtest.

### Server configuration
**Operating system:**
Shared Hosting Linux (1and1)
**Web server:**
Shared Hosting Linux (1and1)
**Database:**
MySQL 5
**PHP version:**
PHP 5.6
**ownCloud version:** (see ownCloud admin page)
8.1
**Updated from an older ownCloud or fresh install:**
updated from 8.0.4
**List of activated apps:**
Calendar, Contacts
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**
<?php
$CONFIG = array (
'instanceid' => 'XX',
'passwordsalt' => 'XX',
'secret' => 'XX',
'trusted_domains' =>
array (
0 => 'XX',
),
'datadirectory' => 'XX',
'overwrite.cli.url' => 'XX',
'dbtype' => 'mysql',
'version' => '8.1.0.8',
'dbname' => 'XX',
'dbhost' => 'XX',
'dbtableprefix' => 'oc_',
'dbuser' => 'XX',
'dbpassword' => 'XX',
'logtimezone' => 'UTC',
'installed' => true,
);
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system --public
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

```
On ownCloud 7+ with access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

On ownCloud 6 with access to your command line run e.g.:
sqlite3 data/owncloud.db or mysql -u root -p owncloud
then execute:  select * from oc_appconfig where appid='user_ldap';

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query above.

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
Microsoft Edge, Google Chrome, Mozilla Firefox
**Operating system:**
Windows 10 RTM, Ubuntu 14.10
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by RealRancor** [comment]
See the existing / probably duplicated issues like: https://github.com/owncloud/core/issues/16255#issuecomment-122663640

**Comment by aspdye** [comment]
Already seen :) But: The Bug is only there when I use a Upgrade Instance. Clean Installs work fine ;)

**Comment by RealRancor** [comment]
Ah, yes. I think we had that talk at the forums?

**Comment by aspdye** [comment]
@RealRancor Exactly. For this reason, I the forum post is linked in this bug report :)

**Comment by aspdye** [comment]
Any ideas?

**Comment by aspdye** [comment]
Hi. Tried to fix by myself. Does not work. Any ideas?

**Comment by MorrisJobke** [comment]
@PVince81 @LukasReschke Didn't one of you wrote the internet connection check? Any hints to solve this?

**Comment by PVince81** [comment]
No, the internet connection check exists since a long time.
But the recent changes to SSL rules / setups might cause it to fail now as it's trying to connect to "https://www.owncloud.org/"

**Comment by RealRancor** [comment]
@PVince81 

This looks like a different issue than to the SSL problem as the issue only appears after the update from oC 8.0.4 to 8.1.0 and not on a clean oC 8.1.0 when i'm reading the issue template correctly.

**Comment by LukasReschke** [comment]
My bet is on https://github.com/owncloud/core/pull/17935, I have no idea what distribution 1and1 is using there but it seems like a CentOS derivate with old NSS.

**Comment by MorrisJobke** [comment]
@aspdye Please reopen if #17935 doesn't solve the issue for you. (it will be released with 8.1.1 in the next days/weeks.

**Comment by RealRancor** [comment]
From my PoV #17935 can't fix this issue as it only happens on an upgrade from 8.0.4 to 8.1.0 but not on a  fresh installation of 8.1.0 on the same system.

**Comment by Scherar** [comment]
Try copy /config/ca-bundle.crt from a new installation to your upgraded. this worked for me...

**Comment by RealRancor** [comment]
Yes, thats an issue within the updater app: https://github.com/owncloud/updater/issues/164

**Comment by nicolasbonnici** [comment]
Same problem here, due to the updater app that don't migrate the config/ca-bundle.crt file. Solved by restoring it. See for more infos: https://raw.githubusercontent.com/owncloud/core/master/config/ca-bundle.crt

**Comment by FreeMinded** [comment]
I just upgraded to OC 8.1.3 and I'm still experiencing this issue. I did also manually copy ca-bundle.crt file but that didn't change anything (as expected as I always do manual upgrades/updates).
All reading and googleing did not point me to a possible solution.
Any ideas?

**Comment by RealRancor** [comment]
@FreeMinded See https://forum.owncloud.org/viewtopic.php?f=17&t=29790

**Comment by FreeMinded** [comment]
@RealRancor thanks for the hint. Unfortunately it still does not help.
1. I'm on a shared host (Hostpoint) and have no ssh access. So I can't check the curl access to apps.owncloud.com 
2. But as I understand my oC 8.1.3 checks for the cURL version and there is no warning about a outdated version.
3. I uploaded the ca-bundle.crt manually.
4. none of the mentioned config options apear in m config.

I'm really lost here.
Not sure if this is connected to this issue, but
1.  the server uses a CA cert certificate for https. But this is inbound and not outbound. So AFIK it should matter.
2. I get a lot of these errors in the oc log:
rmdir(/tmp/oc_tmp_snFIkJ-folder/news/vendor/bin) [<a href='http://ch2.php.net/manual/en/function.rmdir.php'>function.rmdir.php</a>]: Permission denied at /home/mydomain/www/oc.mydomain.tld/lib/private/helper.php#466

unlink() [<a href='http://ch2.php.net/manual/en/function.unlink.php'>function.unlink.php</a>]: No such file or directory at /home/mydomain/www/oc.mydomain.tld/lib/private/helper.php#468

rmdir(/tmp/oc_tmp_BOGzbO-folder) [<a href='http://ch2.php.net/manual/en/function.rmdir.php'>function.rmdir.php</a>]: Operation not permitted at /home/mydomain/www/oc.mydomain.tld/lib/private/helper.php#472

rmdir(/tmp/oc_tmp_BOGzbO-folder/news) [<a href='http://ch2.php.net/manual/en/function.rmdir.php'>function.rmdir.php</a>]: Permission denied at /home/mydomain/www/oc.mydomain.tld/lib/private/helper.php#466

rmdir(/tmp/oc_tmp_BOGzbO-folder/news/vendor) [<a href='http://ch2.php.net/manual/en/function.rmdir.php'>function.rmdir.php</a>]: Permission denied at /home/mydomain/www/oc.mydomain.tld/lib/private/helper.php#466

**Comment by RealRancor** [comment]
@FreeMinded Then please create a new issue using the issue template provided here:

https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by FreeMinded** [comment]
@RealRancor I found the problem, but still don't understand it.
I use a CAcert certificate (www.cacert.org)  for securing https connections.
Now I have added the CAcert root certificates to the ca-bundle.crt and the error message does not appear anymore. And the apps installer works now as well (I can see other categories).
What I do not understand is, why the certificate I use for the server has to be in the ca-bundle.crt for it to work. Is this a bug?
This leads me to the question how can I add root certificates (other than by modifying ca-bundle.crt) for all users (I know each user can upload certificates individually)

Thanks a lot for your support!

**Comment by RealRancor** [comment]
Hi,

strange. That doesn't make any sense as the certificate of https://apps.owncloud.com is not signed by CACert but by Godaddy.

**Comment by FreeMinded** [comment]
Could it be that the internet connectivity check does something strange? 
But I don't understand what could be the problem except if there is a connection attempt to the server from the outside (which would fail as the certificate does not verify if CAcert root is not install. Still this would not explain why it works with the CAcert root in ca-bundle. And I guess everyone using self signed certificates would suffer from the same problem.
