### ISSUE TITLE
Make sure Preview tests don't require ImageMagick to run

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#17786]
https://github.com/owncloud/core/pull/17342 will disable most integration tests for the Preview class if one doesn't have ImageMagick installed. It's not ideal as it might back fire once the PR is submitted.

The solution is to only use the samples which don't require ImageMagick, so that standard tests still run.

**Comment by PVince81** [comment]
probably not worth the effort, and as you said it will be caught when the PR is submitted.
