### ISSUE TITLE
Comments starting with '#' are deprecated in ini files

### ISSUE THREAD

**Issue by szepeviktor** [owncloud/core#17781]
Could you please use `//` for line comments?

https://github.com/owncloud/core/blob/master/apps/user_ldap/tests/wizard.php#L143
219 and 434

**Comment by szepeviktor** [comment]
Also in `3rdparty/mcnetic/phpzipstreamer`:

549:ZipStreamer.php
550:ZipStreamer.php
551:ZipStreamer.php
552:ZipStreamer.php
553:ZipStreamer.php
554:ZipStreamer.php
555:ZipStreamer.php
564:ZipStreamer.php

Issues not enabled in that repo.

**Comment by szepeviktor** [comment]
https://github.com/owncloud/core/blob/master/apps/files_external/tests/backends/sftp_key.php#L53

**Comment by szepeviktor** [comment]
Sorry!
This is for comments in *ini* files.
But it is consistent to use slashes for line comments.

**Comment by Xenopathic** [comment]
Err, neither `#` or `//` are valid INI comments, `;` is the correct delimiter.

**Comment by szepeviktor** [comment]
Yes. Your right. Initially I thought it is a code error.

**Comment by DeepDiver1975** [comment]
@szepeviktor feel free to contribute and submit pull requests which address these issues - THX

**Comment by szepeviktor** [comment]
Here you are: https://github.com/owncloud/core/pull/17792

**Comment by Deepakchawla** [comment]
It shows that in your php.ini file have some error.To resolve it you can load default php.ini file by using below command.
 
It will rename your pervious php.ini file to php.ini_old.

    sudo mv /etc/php5/apache2/php.ini /etc/php5/apache2/php.ini_old
than it will copy default php.ini file to /etc/php5/apache2/ location. 

    sudo cp /usr/share/php5/php.ini-production /etc/php5/apache2/php.ini

Hope it works.
