### ISSUE TITLE
Rename Shared Folder in OwnCloud 8.0.4?

### ISSUE THREAD

**Issue by GjorgeLa** [owncloud/core#17780]
I am using owncloud version 8.0.4 stable and I noticed problem with renaming shared folders.

I have user A, and as user A I am creating folder test, this folders creates on server in files with name test. When as user A I am sharing this folder to user B, if user B change the name from test to Test, in web interface this change is visible at user A and user B but than on server folder name is changing from test to test-0 and after this neither user A neither user B can access to the files of original folder test/Test or upload new files in folder test/Test, every time gets error Upload Failed. Could not find uploaded files because system can not find correct name of the folder on Server.

Anyone have solution for this? How to prevent this from happening? I know that one solution is when user A is sharing folder not to give privilege to change to user B, but this is not excellent solution, this is just quick prevention as many users can share folders and files and they may give further more privilege to change to other users.

Thank you

**Comment by karlitschek** [comment]
@schiesbn any idea?

**Comment by schiesbn** [comment]
> if user B change the name from test to Test, in web interface this change is visible at user A and user B but than on server folder name is changing from test to test-0 

If user B changes the name of the shared folder the name should only change for user B. In this case we don't perform any file operations, we just adjust the target in the share table.

Can you please use the issue template to provide some additional information: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

Thanks!

**Comment by GjorgeLa** [comment]
Again I am testing and working today and same thing happens. This is online work, I am working on online solution, nothing to do with desktop.
Steps to reproduce:
1. Have main folder My Personal with other folders and files with for example total 1 GB, when I create folder My Personal on server in my area folder is mapping like my-personal
2. After some time I am changing the name of the main folder into My personal, now i see this change in the WEB Interface, but after this change my mapped folder on server goes in my-personal-0 and I can not see any folder and file from that 1GB it says to me that folder is empty, but on server I have all of them in main folder with changed name and path like my-personal-0, but 0 KB in my WEB Interface, and that is because I simply changed one letter in the name
????

**Comment by rullzer** [comment]
> 1. Have main folder My Personal with other folders and files with for example total 1 GB, when I create folder My Personal on server in my area folder is mapping like my-personal

I don't get what you try to describe here. If you crate a folder ```My Personal``` then that is the name of the folder. Where and how is it mapped like this?


Also, like @schiesbn said please fill in the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by PVince81** [comment]
The only case where folder names are mapped are when running ownCloud on a Windows server (oc_filemapper).
Please note that running the server on Windows will not be supported any more starting with ownCloud 8.1, see https://owncloud.org/blog/owncloud-server-8-1-will-not-support-windows-as-server-platform-natively/
