### ISSUE TITLE
PHP Error: Array to string conversion

### ISSUE THREAD

**Issue by szepeviktor** [owncloud/core#17782]
https://github.com/owncloud/core/blob/master/lib/private/template/functions.php#L36
`p()` was designed to accept arrays:
```
@param string|array $string the string which will be escaped and printed
```
But it triggers an error in PHP 5.6.9.

**Comment by szepeviktor** [comment]
`array_walk_recursive()` in `sanitizeHTML()` returns an array for print.

**Comment by RealRancor** [comment]
Related: https://github.com/owncloud/core/issues/17468

**Comment by oparoz** [comment]
I think this should be the main ticket about this issue. sanitizeHTML() is simply not doing its work right and can sometimes return arrays instead of strings.

**Comment by MorrisJobke** [comment]
Closing as duplicate of #17468
