### ISSUE TITLE
Ui error in External storage selector in Firefox 41

### ISSUE THREAD

**Issue by szepeviktor** [owncloud/core#17793]
1. Open `selectBackend` list
1. Click somewhere else
1. New storage is created: "Add storage"

![UI error](http://i.snag.gy/6jANF.jpg)

**Comment by oparoz** [comment]
I can't reproduce. Where do you see `selectBackend` ?

**Comment by szepeviktor** [comment]
On Admin and on Personal settings.
https://github.com/owncloud/core/blob/063071b58db926238e895105e13a116a5ceebddb/apps/files_external/templates/settings.php#L30

**Comment by oparoz** [comment]
OK, but that's not what's shown in the dropdown.

I see the full list of available backends and if I click somewhere else, the dropdown simply disappears and nothing gets created.

Which ownCloud version and browser are you using?

**Comment by szepeviktor** [comment]
v8.1.0.8
Firefox 41 https://www.mozilla.org/en-US/firefox/developer/all/

**Comment by oparoz** [comment]
Maybe a Firefox beta issue then.

**Comment by karlitschek** [comment]
@szepeviktor Can you please try with a different browser?

**Comment by szepeviktor** [comment]
This is Firefox Developer Edition problem only.
I think Mozilla will release it in a few week as stable.

**Comment by karlitschek** [comment]
O.K. Then I assume that it has something to do with this new beta you use. Please reopen as soon as this is reproducable with a stable browser release.
Thanks

**Comment by szepeviktor** [comment]
BTW. After restarting the browser. The first item is not even on the list after opening.
