### ISSUE TITLE
Make it more obvious that some external storage options can be configured from the GUI

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#17795]
When you create a new folder using external storage, you get presented with the fields required to connect to the external location, but you're not shown the options panel. There is also nothing in the documentation regarding that new feature and an admin will only find those options if he's heard about it through maybe the mailing list or by looking at commits.

**Options are not presented**
![new_storage](https://cloud.githubusercontent.com/assets/323220/8814167/dec75f20-3009-11e5-8509-20ce28ac5b6a.png)

**A keen observer will notice the new settings button**
![new_storage_rollover](https://cloud.githubusercontent.com/assets/323220/8814208/36baf822-300a-11e5-87f0-e00ab0c9f777.png)

I think the first step should be [to document that feature](https://github.com/owncloud/documentation/issues/1354), but since a lot of people only read the doc when encountering a problem, we should try to make it more obvious that these options exist.

@jancborchardt

**Comment by PVince81** [comment]
Yeah... together with https://github.com/owncloud/core/issues/22479, this page really needs a good revamp.

@owncloud/design
