### ISSUE TITLE
FTP usernames should be URL-encoded

### ISSUE THREAD

**Issue by szepeviktor** [owncloud/core#17796]
This is the return value of `$this->constructUrl($path)` when using the FTP external storage.
`ftp:\/\/username@szepe.net:secretpass@eu1.solid-hosting.net\/`
It should look like: `ftp:\/\/username%40szepe.net:secretpass@eu1.solid-hosting.net\/`

**Comment by szepeviktor** [comment]
Maybe `urlencode()` should be called in `constructUrl()`.

**Comment by PVince81** [comment]
Pull requests are welcome if you feel like it @szepeviktor :smile:
