### ISSUE TITLE
Include SabreDAV 2.1.6 in ownCloud 8.1.1

### ISSUE THREAD

**Issue by jakobsack** [owncloud/core#17790]
There is a very important bugfix/workaround for Windows Phone users in SabreDAV 2.1.6 (see owncloud/calendar#853 and fruux/sabre-dav#692).

SabreDAV 2.1.6 will be released within the next few days and should be integrated in the 3rdparty repository ASAP.

**Comment by DeepDiver1975** [comment]
The diff between 2.1.3 and 2.1.6 is not critical - we can update sabredav within 8.1.1 from my POV.

@jakobsack feel free to submit PRs - THX a lot!

**Comment by jakobsack** [comment]
Fixed by @nickvergessen (owncloud/3rdparty#187)

**Comment by DeepDiver1975** [comment]
Keeping this open until core submodules have been updated
