### ISSUE TITLE
Please test allow_url_fopen

### ISSUE THREAD

**Issue by szepeviktor** [owncloud/core#17797]
After a bit of struggle I've found that `allow_url_fopen` was off for security reasons but - for example - the FTP backend needed it.

Please consider checking it with `ini_get()`.
At least on setup.

**Comment by karlitschek** [comment]
It wou;d be great if you would post a full bug report using this template https://github.com/owncloud/core/blob/master/CONTRIBUTING.md
Or even a pull request :-)

**Comment by szepeviktor** [comment]
I've search your codebase for `allow_url_fopen`.
I think the actual bug (FTP does not connect) is not important, other parts of ownCloud could reqire `allow_url_fopen` to be turned on.

**Comment by szepeviktor** [comment]
I think I am not yet up to a PR. I am just getting acquainted with the code.

**Comment by szepeviktor** [comment]
Please don't ask me to fill in your "form". I think it is for no use in the case.

**Comment by RealRancor** [comment]
Should be enough if you post this to: https://github.com/owncloud/core/issues/14092 including which app needs that option.

**Comment by RealRancor** [comment]
Documentation part in https://github.com/owncloud/documentation/pull/1368

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/issues/14092#issuecomment-123661439
