### ISSUE TITLE
mime_content_type(\/Photos): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by szepeviktor** [owncloud/core#17798]
I think directories should not be passed to `mime_content_type()`.
https://github.com/owncloud/core/blob/master/lib/private/files/type/detection.php#L120

**Comment by szepeviktor** [comment]
BTW. Is this condition redundant?
```php
(strpos($path, '://') !== false) and (substr($path, 0, 7) === 'file://')
```
https://github.com/owncloud/core/blob/master/lib/private/files/type/detection.php#L117

**Comment by karlitschek** [comment]
Please post a full bug report using this template
https://github.com/owncloud/core/blob/master/CONTRIBUTING.md
You can also send a pull request or ask this question on the developer mailinglist :-)

**Comment by nickvergessen** [comment]
We already check for directories
```php
		if (@is_dir($path)) {
			// directories are easy
			return "httpd/unix-directory";
		}
```

However not for non existing files. In theory they also all exist. Only in case of the activity app they may not, which is why the app was changed for 8.1.1: #16039

**Comment by szepeviktor** [comment]
Thank you!
I see https://github.com/owncloud/activity/pull/336.

**Comment by szepeviktor** [comment]
I see you are progressing with ownCloud every day.
