### ISSUE TITLE
Update 8.0 to 8.1 File/Folder links based on SMB shares are not working anymore

### ISSUE THREAD

**Issue by directict** [owncloud/core#17800]
Steps to reproduce

   mount SMB external storage in 8.0
     make folder/file link on 1 of the files/folders
    update from 8.0 to 8.1
    the link previously made is not working anymore.
  

Expected behaviour

the link previously made should work

Actual behaviour
 the link previously made is not working anymore.

Server configuration

Operating system: centos 6.6

Web server:
NGINX

Database:
mySQL

PHP version:
5.5

ownCloud version: (see ownCloud admin page)
8.1
Updated from an older ownCloud or fresh install:
updated from 8.0 / 8.04

List of activated apps:

    activity: 2.0.1
    files: 1.1.9
    files_external: 0.2.3
    files_locking:
    files_pdfviewer: 0.7
    files_sharing: 0.6.2
    files_texteditor: 0.4
    files_trashbin: 0.6.3
    files_versions: 1.0.6
    files_videoviewer: 0.1.3
    firstrunwizard: 1.1
    gallery: 0.6.0
    provisioning_api: 0.2
    templateeditor: 0.1
    user_ldap: 0.6.1

The content of config/config.php:
<?php
$CONFIG = array (
'instanceid' => xxxxx',
'passwordsalt' => 'xxxxx',
'secret' => 'xxxxx',
'trusted_domains' =>
array (
0 => xxxxxxx',
),
'datadirectory' => '/var/www/html/owncloud/data',
'overwrite.cli.url' => 'xxxx',
'dbtype' => 'mysql',
'version' => '8.1.0.8',
'dbname' => 'owncloud',
'dbhost' => 'localhost',
'dbtableprefix' => 'oc_',
'dbuser' => 'oc_admin',

'installed' => true,
'ldapIgnoreNamingRules' => false,
'theme' => 'DirectICT-8.1',
'mail_from_address' => 'no-reply-dev',
'mail_smtpmode' => 'smtp',
'mail_domain' => 'directict.nl',
'forcessl' => true,
'loglevel' => 0,
'mail_smtphost' => 'xxxx,
'mail_smtpport' => '25',
'maintenance' => false,
);

Are you using external storage, if yes which one: SMB

Are you using encryption: no

Are you using an external user-backend, if yes which one: LDAP/ActiveDirectory/...
LDAP configuration (delete this part if not used)

+-------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Configuration | |
+-------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport | 1 |
| hasPagedResultSupport | |
| homeFolderNamingRule | |
| lastJpegPhotoLookup | 0 |
| ldapAgentName | CN=xxxxx,OU=Users,OU=MyBusiness,DC=xxxx,DC=local |
| ldapAgentPassword | *** |
| ldapAttributesForGroupSearch | |
| ldapAttributesForUserSearch | |
| ldapBackupHost | |
| ldapBackupPort | |
| ldapBase | DC=xxxxx |
| ldapBaseGroups | DC=xxxx |
| ldapBaseUsers | DC=xxxxxxx |
| ldapCacheTTL | 600 |
| ldapConfigurationActive | 1 |
| ldapEmailAttribute | mail |
| ldapExperiencedAdmin | 0 |
| ldapExpertUUIDGroupAttr | |
| ldapExpertUUIDUserAttr | |
| ldapExpertUsernameAttr | |
| ldapGroupDisplayName | cn |
| ldapGroupFilter | (&(|(objectclass=group))(|(xxxxxxx;xxxxxxx;xxxxxxxx;xxxxxxxxxxx ))) |
| ldapGroupFilterGroups | xxxxxxx;xxxxxxx;xxxxxxxx;xxxxxxxxxxx |
| ldapGroupFilterMode | 0 |
| ldapGroupFilterObjectclass | group |
| ldapGroupMemberAssocAttr | member |
| ldapHost | xxxxx |
| ldapIgnoreNamingRules | |
| ldapLoginFilter | (&(&(|(objectclass=user))(|(memberof=CN=xxxxxxx,OU=Program Groups,OU=Groups,OU=Direct ICT,DC=xxxxxx,DC=local)))(|(|(mailPrimaryAddress=%uid)(mail=%uid))(|(mail=%uid)(userPrincipalName=%uid)))) |
| ldapLoginFilterAttributes | mail;userPrincipalName |
| ldapLoginFilterEmail | 1 |
| ldapLoginFilterMode | 0 |
| ldapLoginFilterUsername | 0 |
| ldapNestedGroups | 0 |
| ldapNoCase | 0 |
| ldapOverrideMainServer | |
| ldapPagingSize | 500 |
| ldapPort | 389 |
| ldapQuotaAttribute | |
| ldapQuotaDefault | |
| ldapTLS | 0 |
| ldapUserDisplayName | displayname |
| ldapUserFilter | (&(|(objectclass=user))(|(memberof=CN=xxxxxxxxxxxxx,OU=Program Groups,OU=Groups,OU=xxxxxxx,DC=xxxxxxx,DC=local))) |
| ldapUserFilterGroups | xxxxxx |
| ldapUserFilterMode | 0 |
| ldapUserFilterObjectclass | user |
| ldapUuidGroupAttribute | auto |
| ldapUuidUserAttribute | auto |
| turnOffCertCheck | 0 |
| useMemberOfToDetectMembership | 1 |
+-------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.

### Client configuration
**Browser:** Firefox

**Operating system:** Windows 8

#### Web server error log

Insert your webserver log here

**Comment by karlitschek** [comment]
@icewind1991 any idea what might have changed?

**Comment by directict** [comment]
i think everyone using SMB in combination with folder/file links has this issue when upgrading to 81..

**Comment by PVince81** [comment]
Tried the following:

1. Setup OC 8.0.4
1. Enable external storage app
1. Mount a system-wide SMB external storage on "/smb" (admin page)
1. Upload a file "test.txt" into a folder "/smb/folder"
1. Share "folder" with link
1. Open the link: works
1. Update to OC 8.1.0
1. Open the link again

Confirmed, it says "file not found".

I tried with SFTP before and it worked fine.
So possibly related to SMB.

**Comment by directict** [comment]
Yes, exactly!

Met vriendelijke groet,
Gert-jan Slot
Direct ICT
________________________________
Van: Vincent Petry<mailto:notifications@github.com>
Verzonden: ‎28-‎7-‎2015 10:48
Aan: owncloud/core<mailto:core@noreply.github.com>
CC: NOC | Direct ICT<mailto:NOC@directict.nl>
Onderwerp: Re: [core] Update 8.0 to 8.1 File/Folder links based on SMB shares are not working anymore (#17800)


Tried the following:

  1.  Setup OC 8.0.4
  2.  Enable external storage app
  3.  Mount a system-wide SMB external storage on "/smb" (admin page)
  4.  Upload a file "test.txt" into a folder "/smb/folder"
  5.  Share "folder" with link
  6.  Open the link: works
  7.  Update to OC 8.1.0
  8.  Open the link again

Confirmed, it says "file not found".

I tried with SFTP before and it worked fine.
So possibly related to SMB.

**Comment by PVince81** [comment]
Before upgrade:
```
MariaDB [owncloud]> select * from oc_filecache where path like '%folder%';
+--------+---------+----------------------+----------------------------------+--------+---------------+----------+----------+------+------------+---------------+-----------+------------------+---------------+-------------+
| fileid | storage | path                 | path_hash                        | parent | name          | mimetype | mimepart | size | mtime      | storage_mtime | encrypted | unencrypted_size | etag          | permissions |
+--------+---------+----------------------+----------------------------------+--------+---------------+----------+----------+------+------------+---------------+-----------+------------------+---------------+-------------+
|     16 |       3 | folder               | 851148b4fd8fd7ae74bd9100c5c0c898 |      8 | folder        |        2 |        1 |  504 | 1438073075 |    1438073075 |         0 |                0 | 55b742f05d303 |          31 |
|     17 |       3 | folder/proppatch.txt | 8f312a4af37f07d7ac2b9896e520540f |     16 | proppatch.txt |        4 |        3 |  504 | 1438073075 |    1438073075 |         0 |                0 | 55b742f9a5978 |          27 |
+--------+---------+----------------------+----------------------------------+--------+---------------+----------+----------+------+------------+---------------+-----------+------------------+---------------+-------------+
2 rows in set (0.00 sec)

MariaDB [owncloud]> select * from oc_share;
+----+------------+------------+-----------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-----------------+-----------+
| id | share_type | share_with | uid_owner | parent | item_type | item_source | item_target | file_source | file_target | permissions | stime      | accepted | expiration | token           | mail_send |
+----+------------+------------+-----------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-----------------+-----------+
|  1 |          3 | NULL       | root      |   NULL | folder    | 16          | /16         |          16 | /folder     |           1 | 1438073588 |        0 | NULL       | rsw7UpIootFXXzI |         0 |
+----+------------+------------+-----------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-----------------+-----------+
1 row in set (0.00 sec)

MariaDB [owncloud]> select * from oc_storages;
+---------------------------------------+------------+
| id                                    | numeric_id |
+---------------------------------------+------------+
| home::root                            |          1 |
| local::/srv/www/htdocs/owncloud/data/ |          2 |
| smb::vincent@localhost//shared//      |          3 |
+---------------------------------------+------------+
3 rows in set (0.00 sec)
```

After upgrade:
```
MariaDB [owncloud]> select * from oc_storages;
+---------------------------------------+------------+
| id                                    | numeric_id |
+---------------------------------------+------------+
| home::root                            |          1 |
| local::/srv/www/htdocs/owncloud/data/ |          2 |
| smb::vincent@localhost//shared//      |          3 |
| smb::vincent@localhost/shared//       |          4 |
+---------------------------------------+------------+
4 rows in set (0.00 sec)
```

A new storage entry is created with one less slash... It's the wicked storage ids again... (https://github.com/owncloud/core/issues/11830)

The shares are mapped by file id to the old storage entry, that's why they cannot be accessed.

The quick workaround after the upgrade is to set the numeric id of the new entry "smb::vincent@localhost//shared//" to 3 (the old one) after deleting the old entry.
This should remap everything properly.

A fix is still needed in the SMB storage id computation.

**Comment by directict** [comment]
Ok, so the problem is located, will it be added to an update you think?

My system has over 200 links and its on 8.0.4 atm.

Met vriendelijke groet,
Gert-jan Slot
Direct ICT
________________________________
Van: Vincent Petry<mailto:notifications@github.com>
Verzonden: ‎28-‎7-‎2015 11:00
Aan: owncloud/core<mailto:core@noreply.github.com>
CC: NOC | Direct ICT<mailto:NOC@directict.nl>
Onderwerp: Re: [core] Update 8.0 to 8.1 File/Folder links based on SMB shares are not working anymore (#17800)


Before upgrade:

MariaDB [owncloud]> select * from oc_filecache where path like '%folder%';
+--------+---------+----------------------+----------------------------------+--------+---------------+----------+----------+------+------------+---------------+-----------+------------------+---------------+-------------+
| fileid | storage | path                 | path_hash                        | parent | name          | mimetype | mimepart | size | mtime      | storage_mtime | encrypted | unencrypted_size | etag          | permissions |
+--------+---------+----------------------+----------------------------------+--------+---------------+----------+----------+------+------------+---------------+-----------+------------------+---------------+-------------+
|     16 |       3 | folder               | 851148b4fd8fd7ae74bd9100c5c0c898 |      8 | folder        |        2 |        1 |  504 | 1438073075 |    1438073075 |         0 |                0 | 55b742f05d303 |          31 |
|     17 |       3 | folder/proppatch.txt | 8f312a4af37f07d7ac2b9896e520540f |     16 | proppatch.txt |        4 |        3 |  504 | 1438073075 |    1438073075 |         0 |                0 | 55b742f9a5978 |          27 |
+--------+---------+----------------------+----------------------------------+--------+---------------+----------+----------+------+------------+---------------+-----------+------------------+---------------+-------------+
2 rows in set (0.00 sec)

MariaDB [owncloud]> select * from oc_share;
+----+------------+------------+-----------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-----------------+-----------+
| id | share_type | share_with | uid_owner | parent | item_type | item_source | item_target | file_source | file_target | permissions | stime      | accepted | expiration | token           | mail_send |
+----+------------+------------+-----------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-----------------+-----------+
|  1 |          3 | NULL       | root      |   NULL | folder    | 16          | /16         |          16 | /folder     |           1 | 1438073588 |        0 | NULL       | rsw7UpIootFXXzI |         0 |
+----+------------+------------+-----------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-----------------+-----------+
1 row in set (0.00 sec)

MariaDB [owncloud]> select * from oc_storages;
+---------------------------------------+------------+
| id                                    | numeric_id |
+---------------------------------------+------------+
| home::root                            |          1 |
| local::/srv/www/htdocs/owncloud/data/ |          2 |
| smb::vincent@localhost//shared//      |          3 |
+---------------------------------------+------------+
3 rows in set (0.00 sec)


After upgrade:

MariaDB [owncloud]> select * from oc_storages;
+---------------------------------------+------------+
| id                                    | numeric_id |
+---------------------------------------+------------+
| home::root                            |          1 |
| local::/srv/www/htdocs/owncloud/data/ |          2 |
| smb::vincent@localhost//shared//      |          3 |
| smb::vincent@localhost/shared//       |          4 |
+---------------------------------------+------------+
4 rows in set (0.00 sec)


A new storage entry is created with one less slash... It's the wicked storage ids again... (#11830<https://github.com/owncloud/core/issues/11830>)

The shares are mapped by file id to the old storage entry, that's why they cannot be accessed.

The quick workaround after the upgrade is to set the numeric id of the new entry "smb::vincent@localhost//shared//" to 3 (the old one) after deleting the old entry.
This should remap everything properly.

A fix is still needed in the SMB storage id computation.

**Comment by PVince81** [comment]
@directict yes, please wait for 8.1.2. A fix is on the way.

**Comment by directict** [comment]
Great, then I can finally update :-) smb and links working then. Thanks !

Met vriendelijke groet,
Gert-jan Slot
Direct ICT
________________________________
Van: Vincent Petry<mailto:notifications@github.com>
Verzonden: ‎28-‎7-‎2015 11:39
Aan: owncloud/core<mailto:core@noreply.github.com>
CC: NOC | Direct ICT<mailto:NOC@directict.nl>
Onderwerp: Re: [core] Update 8.0 to 8.1 File/Folder links based on SMB shares are not working anymore (#17800)


@directict<https://github.com/directict> yes, please wait for 8.1.2. A fix is on the way.

**Comment by PVince81** [comment]
@directict thanks for your report and sorry for inconvenience.

**Comment by PVince81** [comment]
PR is here https://github.com/owncloud/core/issues/17922

**Comment by directict** [comment]
Great ! I'll just wait :)
Met vriendelijke groet,
Gert-jan Slot
Direct ICT
________________________________
Van: Vincent Petry<mailto:notifications@github.com>
Verzonden: ‎28-‎7-‎2015 11:50
Aan: owncloud/core<mailto:core@noreply.github.com>
CC: NOC | Direct ICT<mailto:NOC@directict.nl>
Onderwerp: Re: [core] Update 8.0 to 8.1 File/Folder links based on SMB shares are not working anymore (#17800)


PR is here #17922<https://github.com/owncloud/core/pull/17922>
