### ISSUE TITLE
Unsuccessful password change always shows "Unable to change your password"

### ISSUE THREAD

**Issue by michag86** [owncloud/core#17817]
If the password change failes, the generated error like "wrong password" is not shown.
The issue exists since
https://github.com/owncloud/core/commit/e5c6af51027f786d74f859584f0aa6c85db6ead6#diff-a1c52fafc7d1f682c8849c5c62297682

This is because the error message is written to #passworderror and not to #password-error

I think this will fix it:
```
 					if (typeof(data.data) !== "undefined") {
 						$('#password-error').html(data.data.message);
 					} else {
 						$('#password-error').html(t('Unable to change password'));
 					}
```

**Comment by karlitschek** [comment]
@jancborchardt What do you think?

**Comment by jancborchardt** [comment]
Closing cause @michag86 fixed it with https://github.com/owncloud/core/pull/17818 – thank you! :) You’re very welcome in our IRC channel #owncloud-dev (on freenode).

**Comment by Xenopathic** [comment]
@jancborchardt You actually need to press the 'Close' button :laughing:
