### ISSUE TITLE
Folder disappears when moved to another folder until you access it manually via URL

### ISSUE THREAD

**Issue by llucax** [owncloud/core#17822]
### Steps to reproduce
1. Create folder `/A/B` with some files
2. Create <del>`/C/B`</del> `/C/BB` with some other files (but no file/folder called `B`) <del>(not the same as in `/A/B`)</del>
3. Move via drag&drop the folder `/A/B` to `/`
4. Move via drag&drop the folder `/B` to `/C`

### Expected behaviour
The contents of `/B` should be <del>merged with the contents of</del> placed in `/C/B` <del>(probably warning and asking for user input if there are conflicts), or just give an error and cancel the operation</del>. Certainly **DO NOT DESTROY DATA**.

### Actual behaviour
Contents of <del>`/C/B`</del> `/C` remains the same as before step 4 and `/B` disappears. The files are in the filesystem though, and accessing to `/C/B` manually writing the URL shows the files, after that, the expected behaviour happens (i.e. the web interface can see the contents in `/C` appropriately (see comments for more details).

### Server configuration
**Operating system**: Ubuntu 15.04

**Web server:** Apache 2.4.10-9ubuntu1

**Database:** MySQL 5.6.25-0ubuntu0.15.04.1

**PHP version:** 5.6.4+dfsg-4ubuntu6.2

**ownCloud version:** ownCloud 8.1.0 (stable)

**Updated from an older ownCloud or fresh install:** Updated from 8.0.x (a while ago)

**List of activated apps:** 

Enabled:
- activity: 2.0.1
- calendar: 0.7.1
- contacts: 0.4.0.0
- direct_menu: 0.3
- documents: 0.9.0
- external: 1.2
- files: 1.1.9
- files_external: 0.2.3
- files_pdfviewer: 0.7
- files_sharing: 0.6.2
- files_texteditor: 0.4
- files_trashbin: 0.6.3
- files_versions: 1.0.6
- files_videoviewer: 0.1.3
- firstrunwizard: 1.1
- galleryplus: 12
- search_lucene: 0.6.0

Disabled:

- encryption
- files_locking
- gallery
- provisioning_api
- templateeditor
- user_external
- user_ldap
- user_webdavauth

config.php
```
<?php
$CONFIG = array (
  'defaultapp' => 'calendar',
  'instanceid' => 'XXX',
  'passwordsalt' => 'XXX',
  'datadirectory' => '/srv/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'appstoreenabled' => true,
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/owncloud/apps',
      'url' => '/apps',
      'writable' => true,
    ),
  ),
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'XXX',
  'dbpassword' => 'XXX',
  'installed' => true,
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' => 
  array (
    0 => 'XXX',
  ),
  'mail_from_address' => 'XXX',
  'mail_smtpmode' => 'php',
  'mail_smtpname' => 'XXX',
  'mail_smtppassword' => 'XXX',
  'mail_domain' => 'XXX',
  'secret' => 'XXX',
  'remember_login_cookie_lifetime' => 1296000,
  'session_lifetime' => 259200,
  'session_keepalive' => true,
  'preview_max_scale_factor' => 1,
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\Image',
    1 => 'OC\\Preview\\Illustrator',
    2 => 'OC\\Preview\\Postscript',
    3 => 'OC\\Preview\\Photoshop',
    4 => 'OC\\Preview\\TIFF',
  ),
  'forceSSLforSubdomains' => true,
);
```

**Are you using external storage, if yes which one:** Not where this happened, all was internal storage

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** NO

### Client configuration
**Browser:** FF 39.0+build5-0ubuntu0.15

**Operating system:** Ubuntu 15.04

#### Web server error log
```
Nothing current
```

#### ownCloud log (data/owncloud.log)
The logfile was empty, but the admin interface showed this log:
```
{"reqId":"mailF\/8Vvmo\/w4eu4RGf","remoteAddr":"10.1.1.141","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#58","level":3,"time":"2015-07-22T20:20:42+00:00"}
{"reqId":"rSuLTP1B57ei+d5IOxZP","remoteAddr":"10.1.1.141","app":"hook","message":"error while running hook (OCA\\Search_Lucene\\Hooks\\Files::indexFile): An exception occurred while executing 'INSERT INTO `oc_lucene_status`(`status`) VALUES(?)' with params [\"N\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'","level":3,"time":"2015-07-22T20:20:45+00:00"}
{"reqId":"tQvAtjTuc121OVh+d4pf","remoteAddr":"10.1.1.141","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#58","level":3,"time":"2015-07-22T20:20:58+00:00"}
{"reqId":"HoymKyZZf6NXyGWFEhBx","remoteAddr":"10.1.1.141","app":"hook","message":"error while running hook (OCA\\Search_Lucene\\Hooks\\Files::indexFile): An exception occurred while executing 'INSERT INTO `oc_lucene_status`(`status`) VALUES(?)' with params [\"N\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'","level":3,"time":"2015-07-22T20:21:01+00:00"}
{"reqId":"cXbqDcScajZZ1D+Zr0Gx","remoteAddr":"10.1.1.141","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#58","level":3,"time":"2015-07-22T20:21:13+00:00"}
{"reqId":"2r4yqL\/a2ZNubHYMgZ5s","remoteAddr":"10.1.1.141","app":"hook","message":"error while running hook (OCA\\Search_Lucene\\Hooks\\Files::indexFile): An exception occurred while executing 'INSERT INTO `oc_lucene_status`(`status`) VALUES(?)' with params [\"N\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'","level":3,"time":"2015-07-22T20:21:19+00:00"}
```

#### Browser log
```
Nothing was captured during the incident
```

**Comment by LukasReschke** [comment]
I cannot reproduce this on my instance. Can you please provide the missing data from the issue template? Thanks.

**Comment by llucax** [comment]
Done, sorry, the issue was accidentally submitted before I could fill it up, I didn't expect for someone to comment before I could edit the issue description properly :)

**Comment by llucax** [comment]
Wait, this might be a web cache issue or something, I just looked into the filesystem storage and the files are there, and actually both folders are not even named the same (one is in plural and the other in singular).

**Comment by llucax** [comment]
Nope, there seems to be an issue, quite different from what I thought before, the desktop client is not getting the data either, and a force-refresh doesn't show the moved folder at all. In the filesystem is in `/C/B`, not in `/B`. At least I didn't lose my data... phew!

**Comment by llucax** [comment]
If I hit the folder manually via the URL, the contents are also there, so it seems to be some kind of listing issue.

**Comment by llucax** [comment]
And after hitting the folder manually via the URL, it was picked up by the desktop client, and going back to `/C` in the web interface, is listed too, so it seems like poking the folder updated something...

**Comment by llucax** [comment]
Nothing new in the logs to bring some light to the issue.

**Comment by llucax** [comment]
I updated the issue title and description, trying to preserve the history.

**Comment by llucax** [comment]
Updated with owncloud log entries found via the web admin interface (the log file in `data/` is missing so I don't know where that log comes from :unamused:

**Comment by PVince81** [comment]
@llucax there is a bit of confusion regarding the updated steps.
At step 3 you said move the files that are inside "/A/B" to "/".
But at step 4 you mention a folder "/B". However there is no such folder.
Unless at step 3 you meant "move the folder /A/B to /". Then it makes sense.
Please double check.

You might want to try with another browser like Chrome to see if it's browser-related.

You can also have a look at the "oc_filecache" table, for example `select * from oc_filecache where path like '%B' order by path` to see if it matches whatever is on the filesystem.

**Comment by llucax** [comment]
> @llucax there is a bit of confusion regarding the updated steps.
> At step 3 you said move the files that are inside "/A/B" to "/".
> But at step 4 you mention a folder "/B". However there is no such folder.
> Unless at step 3 you meant "move the folder /A/B to /". Then it makes sense.
> Please double check.

Yes, that was a silly mistake, I meant to move the entire folders. I updated the description again.

**Comment by llucax** [comment]
> You might want to try with another browser like Chrome to see if it's browser-related.

Is not something I can reproduce actually, I guess there was some failure in the request and the operation was half done or something.

> You can also have a look at the "oc_filecache" table, for example select * from oc_filecache where path like '%B' order by path to see if it matches whatever is on the filesystem.

Would this make sense after my particular problem was fixed after I accessed the folder manually via the URL?

**Comment by PVince81** [comment]
@llucax I could not reproduce the issue.
However as you are moving the same folder twice, I was wondering whether you are waiting for the first move to be completely finished before moving the folder to its second location ?
Are there lots of files and subfolders in "B" ?

It is likely that it took a while to do the move and that what you observed was a in-between state, which eventually seemed to "fix" itself because at the time you looked at the final folder it just finished moving.

In any case, this situation will not be possible any more with transactional locking (https://doc.owncloud.org/server/8.1/admin_manual/configuration_files/files_locking_experimental.html) as it will prevent you to move a busy folder.

**Comment by llucax** [comment]
> However as you are moving the same folder twice, I was wondering whether you are waiting for the first move to be completely finished before moving the folder to its second location ?

How do I know if I'm waiting for the first move to complete? It appeared in the / directory, so I could drag it to the new subfolder. In any case, the user shouldn't be able to break the server by just moving stuff too fast.

But yeah, in any case it smells like a timing issue/race condition.

> Are there lots of files and subfolders in "B" ?

~1500

> It is likely that it took a while to do the move and that what you observed was a in-between state, which eventually seemed to "fix" itself because at the time you looked at the final folder it just finished moving.

Oh, so you are suggesting that the folder was not shown in either / or /C because it was in a "in the move" state? If that's the case, why the first move worked instantly. Also, we are talking about instant vs. a lot of minutes, maybe close to an hour, even when it might have been a coincidence that the folder reappeared when I accessed it manually by typing the URL, it seems a bit unlikely in this scenario.

Also, I don't know how are you doing it filesystem-wise, but if you do a `rename()` *syscall*, that's an instant and **atomic** operation.

> In any case, this situation will not be possible any more with transactional locking (https://doc.owncloud.org/server/8.1/admin_manual/configuration_files/files_locking_experimental.html) as it will prevent you to move a busy folder.

Just for the record, if by "busy folder" you mean a folder with a lot of activity, then it wasn't the case, is a personal owncloud instance and nobody else was accessing that folder at the time.

**Comment by PVince81** [comment]
There are a few possible explanations for this.
You are right that it is strange that the first move, even though not finished, would show the folder already.

First to explain how the rename works: it is not only renaming the folder on disk with a system call, but also needs to update the database index (oc_filecache) and needs to update many entries, which might take a while due to the way the structure is designed.

Second, there is a file scanner that tries to detect changes directly on disk, changes that aren't present in the database. If the rename is in the situation of above, where folder is renamed on disk but not yet in the database, it can happen that the scanner (aka change detector) finds the folder and think it is new, because there is no entry in the database for it. This kind of concurrency can cause side-effects like what you observed and also make the folder sometimes be visible during the move and sometimes not depending on the timing. This was analyzed here https://github.com/owncloud/core/issues/13391

With "busy folder" I only meant "folder that is currently being moved" (FS move and DB update), not with a lot of activity.

If you're operating a small ownCloud instance I recommend to set filesystem_check_changes to 0 in config.php to avoid having the change detector running and prevent such issues (this will be the default starting with 8.2 #16897)

In 8.1 the transactional file locking as specified above is designed to prevent such concurrency issues.
