### ISSUE TITLE
Scrolling in mobile view opens menu to easy

### ISSUE THREAD

**Issue by Bullnados** [owncloud/core#17821]
If you want scroll just up and down the side menu is opened to easy. If u dont scroll in a perfect y-axis the side menu is opened. Would be nice to implement a bigger tolerance in x-axis

The "proplem" is in all apps, so I post it here in core.

**Comment by karlitschek** [comment]
@jancborchardt What do you think?

**Comment by jancborchardt** [comment]
Duplicate of #11193  – @Bullnados please search existing issues before opening new ones. :) See the fix attempt at https://github.com/owncloud/core/pull/17785 and please review that.

**Comment by Bullnados** [comment]
Oh sorry :( Will do that
