### ISSUE TITLE
Disabling and re-enabling file sharing breaks files app

### ISSUE THREAD

**Issue by Bugsbane** [owncloud/core#17829]
I recently did an upgrade to 8.1, but after the upgrade he option to share files no longer seems to exist in the GUI. Basically the share icon no longer showed when hovering over the file, like the edit and download icons do.

I tried disabling and removing the file_sharing and sharelinks apps. When I reinstalled and enabled the file_sharing app, now all I see in the main content area of the file app doesn't actually show any files, as in the screenshot below:

![file-screenshot](https://cloud.githubusercontent.com/assets/401733/8846059/18ccea12-30f2-11e5-89f9-09cf1bfbd0a5.png)

Unfortunately it persists even if I disable the file_sharing app again. In the logs I see:

> Fatal
> Index
> Exception: {"Exception":"Exception","Message":"Sharing backend for file not found","Code":0,"Trace":"#0 \/srv\/http\/webapps\/owncloud\/lib\/private\/share\/share.php(1476): OC\\Share\\Share::getBackend('file')\n#1 \/srv\/http\/webapps\/owncloud\/lib\/private\/share\/share.php(305): OC\\Share\\Share::getItems('file', NULL, -1, 'USERNAME', NULL, -1, NULL, -1, false)\n#2 \/srv\/http\/webapps\/owncloud\/lib\/public\/share.php(122): OC\\Share\\Share::getItemsSharedWithUser('file', 'USERNAME', -1, NULL, -1, false)\n#3 \/srv\/http\/webapps\/owncloud\/apps\/files_sharing\/lib\/mountprovider.php(62): OCP\\Share::getItemsSharedWithUser('file', 'USERNAME')\n#4 \/srv\/http\/webapps\/owncloud\/lib\/private\/files\/filesystem.php(446): OCA\\Files_Sharing\\MountProvider->getMountsForUser(Object(OC\\User\\User), Object(OC\\Files\\Storage\\StorageFactory))\n#5 [internal function]: OC\\Files\\Filesystem::OC\\Files\\{closure}(Object(OCA\\Files_Sharing\\MountProvider))\n#6 \/srv\/http\/webapps\/owncloud\/lib\/private\/hooks\/emittertrait.php(98): call_user_func_array(Object(Closure), Array)\n#7 \/srv\/http\/webapps\/owncloud\/lib\/private\/files\/config\/mountprovidercollection.php(72): OC\\Files\\Config\\MountProviderCollection->emit('\\\\OC\\\\Files\\\\Confi...', 'registerMountPr...', Array)\n#8 \/srv\/http\/webapps\/owncloud\/apps\/files_sharing\/appinfo\/application.php(131): OC\\Files\\Config\\MountProviderCollection->registerProvider(Object(OCA\\Files_Sharing\\MountProvider))\n#9 \/srv\/http\/webapps\/owncloud\/apps\/files_sharing\/appinfo\/app.php(46): OCA\\Files_Sharing\\Appinfo\\Application->registerMountProviders()\n#10 \/srv\/http\/webapps\/owncloud\/lib\/private\/app.php(389): require('\/srv\/http\/webap...')\n#11 \/srv\/http\/webapps\/owncloud\/settings\/ajax\/navigationdetect.php(29): OC_App::getAppNavigationEntries('files_sharing')\n#12 \/srv\/http\/webapps\/owncloud\/lib\/private\/route\/route.php(154) : runtime-created function(1): require_once('\/srv\/http\/webap...')\n#13 [internal function]: __lambda_func(Array)\n#14 \/srv\/http\/webapps\/owncloud\/lib\/private\/route\/router.php(274): call_user_func('\\x00lambda_880', Array)\n#15 \/srv\/http\/webapps\/owncloud\/lib\/base.php(867): OC\\Route\\Router->match('\/settings\/ajax\/...')\n#16 \/srv\/http\/webapps\/owncloud\/index.php(40): OC::handleRequest()\n#17 {main}","File":"\/srv\/http\/webapps\/owncloud\/lib\/private\/share\/share.php","Line":1357} 

I'm on:
ownCloud 8.1.0
Nginx 1.8.0-1
Php 5.6.11
Manjaro Linux
MySQL 10.0.20-1

**Comment by karlitschek** [comment]
@schiesbn any idea?

**Comment by schiesbn** [comment]
> I tried disabling and removing the file_sharing and sharelinks apps. When I reinstalled and enabled the file_sharing app

What is the sharelinks app? A 3rd-party app from the app store? How did you reinstall the app? Did you copied it back from the 8.1.0 tar file?

**Comment by oparoz** [comment]
ShareLinks is a 3rd party app, but I don't think it has anything to do with this.
It looks like something else was disabled as well, like external storage and it wasn't re-enabled.

**Comment by Bugsbane** [comment]
I don't use external storage... Here's my app list:
Enabled:
 - activity: 1.2.1
 - bookmarks: 0.4
 - calendar: 0.7.2
 - contacts: 0.4.0.0
 - documents: 0.10.0
 - files: 1.1.9
 - files_mv: 0.8.1a
 - files_pdfviewer: 0.7
 - gallery: 0.6.1
 - galleryplus: 13.0.0
 - news: 5.3.8
 - tasks: 0.7.1
Disabled:
 - admin_dependencies_chk
 - conversations
 - encryption
 - external
 - files_embeddedvideo
 - files_encryption
 - files_external
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - files_videoviewer
 - firstrunwizard
 - provisioning_api
 - templateeditor
 - updater
 - user_external
 - user_ldap
 - user_webdavauth

**Comment by oparoz** [comment]
Disabling gallery 0.6.1 (Pictures) and hitting ctrl + F5 should solve your problem.

**Comment by Bugsbane** [comment]
...and so it did. Not quite sure how you figured that one out, but thank you, @oparoz

**Comment by oparoz** [comment]
It's a known problem when both apps are enabled together and it's difficult to tackle automatically as it would be problematic if apps could disable other apps.

**Comment by Bugsbane** [comment]
Maybe we need some kind of "Conflicts with" in the manifest file (if OC apps have manifest files), so we can then detect when conflicting apps are installed and warn the admin.

**Comment by oparoz** [comment]
I've made the suggestion already, but nobody has shown an interest:
https://github.com/owncloud/core/issues/16073
