### ISSUE TITLE
Introduce check_for_available_memcache flag

### ISSUE THREAD

**Issue by BenS89** [owncloud/core#17828]
There are already some flags to explicitely enable or disable some checks like check_for_working_webdav or check_for_working_htaccess. Since not all users can install a php memory cache like APCu or memcached, there should be an option to disable this check so that no warnings are displayed in the admin-panel.

**Comment by karlitschek** [comment]
Why not show the warning when there is a good reason to show the warning? It has a performance impact so I'm not sure why this should be hidden. We implemented the warning so that people can see it and are reminded that something could be improved.
