### ISSUE TITLE
Restore file version does not work for images

### ISSUE THREAD

**Issue by davitol** [owncloud/core#17833]
### Steps to reproduce
1. Upload a local .jpg file to OC
2. Upload another .jpg file with the same as the previous one
3. Restore the first file

### Expected behaviour
The first image file should be shown

### Actual behaviour
The image file is not restore

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:ersion":"8.1.0.8","versionstring":"8.1.0"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity: 2.0.1
 - files: 1.1.9
 - files_external: 0.2.3
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.1
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.6
Disabled:
 - encryption
 - external
 - user_external
 - user_ldap
 - user_webdavauth

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

**Comment by DeepDiver1975** [comment]
Works for me with two exceptions:
- [ ] preview in files app is not updated
- [ ] image viewer shows old image as well

Both cases are related to the preview caching - looks like previews are not cleared in case.

**Comment by DeepDiver1975** [comment]
@georgehrke is there a hook missing? THX

**Comment by georgehrke** [comment]
I'll check

**Comment by DeepDiver1975** [comment]
> I'll check

THX

**Comment by DeepDiver1975** [comment]
From my understanding there is no explicit hook on the versions app when a version is rolled back

@schiesbn can you confirm?

**Comment by georgehrke** [comment]
dup of https://github.com/owncloud/core/issues/10559?
