### ISSUE TITLE
Don't log fatal error for each WebDAV request when quota is exceeded

### ISSUE THREAD

**Issue by fmkaiser** [owncloud/core#17836]
When a user who has exceeded his quota tries to upload stuff via WebDAV, a fatal error is logged for each PUT request - see also #14516. 

First of all, thanks for making the error message more understandable in #14791.

With lots of users and quite a few of them regularily exceeding their quota, this still fills up the error log fast and makes it difficult to read. 

For our own use, we added Sabre\DAV\Exception\InsufficientStorage to nonFatalExceptions in lib/private/connector/sabre/exceptionloggerplugin.php, thereby logging the message only in DEBUG level. I'll attach a pull request shortly.

Not sure whether that's a good solution for all ownCloud users. For smaller installations where e.g. the hard drive runs full, the error may be beneficial (unless that's logged some other way still).

**Comment by PVince81** [comment]
Closing as won't fix, see PR for explanation https://github.com/owncloud/core/pull/17837
