### ISSUE TITLE
Infintive Loop for some WebDAV Requests

### ISSUE THREAD

**Issue by smelchior** [owncloud/core#17835]
After Upgrading from 8.0 to 8.1 we noticed an increased memory usage for our owncloud server. The instance is connected to our AD Ldap server for user management.
When investigating we found that some requests from the Owncloud WebDAV Client result in a fatal error:
"PROPFIND /remote.php/webdav/ HTTP/1.1" 500 -

PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 65552 bytes) in /var/www/html/owncloud/lib/private/log.php on line 201

This only seems to happen for some users. 
When stracing the process we noticed that it requests user data from the database and ldap in a recursive loop:
- SELECT `configvalue` FROM `oc_preferences` WHERE `userid` = 'USER' AND `appid` = 'files' AND `configkey` = 'quota'
- SELECT `configvalue` FROM `oc_preferences` WHERE `userid` = 'USER' AND `appid` = 'settings' AND `configkey` = 'email'
- LDAP attribute request for jpegPhoto
- LDAP attribute request for thumbnailPhoto
- SELECT `uid`, `displayname` FROM `oc_users` WHERE LOWER(`uid`) = LOWER('USER')
- SELECT `ldap_dn` FROM `oc_ldap_user_mapping` WHERE `owncloud_name` = 'USER'
- LDAP attribute request objectclass
- LDAP attribute request mail

Looking at the database we noticed that the lastFeatureRefresh timestamp for the users that failed was more than 1 day old. Once one of the users logged in via the web interface and the lastFeatureRefresh was updated, the WebDAV request were fine. 

Investigating some more in the apps/user_ldap/lib/user/user.php update() function showed that the $this->updateAvatar() does not finish for these requests. The call stack shows:
apps/user_ldap/lib/user/user.php $this->updateAvatar() ->
apps/user_ldap/lib/user/user.php $this->setOwnCloudAvatar() ->
apps/user_ldap/lib/filesystemhelper.php $this->fs->setup($this->uid) -> 
lib/private/util.php \OC_Util::setupFS($uid) ->
lib/private/app.php OC_App::loadApps(array('filesystem')) 

It seems as if loadapps triggers an update () for the user somehow, so here we have the infinite loop.

As a temporary fix i moved the	$this->markRefreshTime(); before the $this->updateAvatar(); in the update() function. After that change it works again but i guess that is not the correct fix.

**Comment by DeepDiver1975** [comment]
@smelchior what is the size of the avatar images within your ldap tree?

**Comment by smelchior** [comment]
Each avatar has about 8kb. As they are updated properly when logging in via the web interface, i do not think that that is the issue.

**Comment by DeepDiver1975** [comment]
@blizzz mind taking a look - THX

**Comment by blizzz** [comment]
Sounds like a duplicate  of https://github.com/owncloud/core/issues/17631 which is fixed with  https://github.com/owncloud/core/pull/17723. 

@smelchior can you confirm?

**Comment by smelchior** [comment]
Yes, you are correct, the fix in #17723 does also fix this issue
