### ISSUE TITLE
Events in shared calendars are not downloaded anymore

### ISSUE THREAD

**Issue by maystar** [owncloud/core#17847]
### Steps to reproduce
1. Share another user a calendar with full access
2. Add some events to this calendar
3. Let other user add events using different caldav clients (tested IOS 7/8, Mac OS X Calendar, KDE Akonadi)

### Expected behaviour
All events are shown for me and the other user

### Actual behaviour
Events are shown for me and the other users owncloud web interface but not in its caldav clients, except the event was added from this client. So new events the other user created are uploaded to the server, but new ones added somewhere else are not synchronized to his clients. And to make it even more surprisingly: Events he added on a device, which are deleted by me, are deleted on his device, too. 

There where no issues with this calendar since I started to use owncloud years ago. I guess an update broke this feature.

### Server configuration

**Operating system**: opensuse 13.2 

**Web server:** apache 2.4.10

**Database:** mysql 5.6.17

**PHP version:** php 5.6.1

**ownCloud version:** 8.1.0 

**Updated from an older ownCloud or fresh install:** updated since owncloud 3

**List of activated apps:**
Enabled:
 - activity: 2.0.1
 - bookmarks: 0.4
 - calendar: 0.7.1
 - contacts: 0.4.0.0
 - documents: 0.9.0
 - files: 1.1.9
 - files_external: 0.2.3
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - mozilla_sync: 1.4
 - music: 0.3.5
 - news: 5.3.8
 - tasks: 0.7.1

Disabled:
 - encryption
 - external
 - files_locking
 - files_videoviewer
 - galleryplus
 - provisioning_api
 - search_lucene
 - templateeditor
 - user_external
 - user_ldap
 - user_webdavauth

**The content of config/config.php:**
```<?php
$CONFIG = array (
  'passwordsalt' => '*********************',
  'datadirectory' => '/media/USB-Platte/.data/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'installed' => true,
  'loglevel' => 1,
  'instanceid' => '506360c5c8c8f',
  'maintenance' => false,
  'theme' => '',
  'trusted_domains' => 
  array (
    0 => '*************',
    1 => '***********',
    2 => '**********',
  ),
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'owncloud',
  'mail_domain' => '********',
  'mail_smtphost' => '********',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbuser' => 'ownclouduser',
  'dbpassword' => '*********',
  'mail_smtpport' => '25',
  'secret' => '*****************************',
  'forcessl' => true,
);```

**Comment by karlitschek** [comment]
Can you reopen this in the calendar repository please?
Thanks.

**Comment by RealRancor** [comment]
@maystar 
> calendar: 0.7.1

Also make sure you're using the latest 0.7.2 providing some fixes for the principals URLs which might be used by your clients.

**Comment by maystar** [comment]
Sorry, I didn't recognized the core apps have own projects here. 
But anyway, upgrading to the calendar app version 0.7.2 solved this issue. Thanks for that hint! Should I reopen and close this issue anyway?
