### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#17846]
In case encryption was not enabled, we accidently set encrypted = 1 for files inside mount points (and shares), since 8.1.0. This breaks opening the files in 8.1.1+ because we fixed the code that checks if a file is encrypted.
In order to fix the file, we need to reset the flag of the file. However, the flag might be set because the file is in fact encrypted because it was uploaded at a time where encryption was enabled.

So we only do this when:
- Current version of ownCloud before the update is `version === 8.1.0` or `8.2.0.0 < version < 8.2.0.3`
- Encryption is disabled
- files_encryption is not known in the app config (so encryption was never on)

If the first two are not the case, this is save and nothing needs to be done, because no files can possibly be uploaded in the time, or encryption is on anyway.

However, if files_encryption values exist in the config, we might have a false negative. Now if there is no file with unencrypted size greater 0, that means there are no files that are still encrypted with "files_encryption" encryption. So we can also safely reset the flag.

If this is not the case, we go with "better save then sorry" and don't change the flag but write a message to the ownCloud log file, which is why you most-likely ended up here.

If you never had encryption enabled while files where uploaded you can manually reset the flags for the affected files.
If you had it enabled, then disabled it at some point, updated to 8.1.0 uploaded files and now updated to 8.1.1, you have to check manually which files have the encrypted flag set, although the file is not encrypted and then reset the value for those manually.

**Comment by oparoz** [comment]
![dkjhx9l](https://cloud.githubusercontent.com/assets/323220/8859588/77edd204-317e-11e5-92d3-a475bded1b07.gif)
