### ISSUE TITLE
SFTP external storage - Can not set custom port

### ISSUE THREAD

**Issue by Iznogood1** [owncloud/core#17841]
Hi,

SFTP external stareg woks fine if I let the default port (22).

But if I modifiy the SFTP port of my serveur, and try to connect it in the ownCloud external storage module by specifying xxx.xxx.xxx.xxx:ppp, then ownClound can not connect to it.

**Comment by Xenopathic** [comment]
Thanks for reporting this to us! We need some more information to help you with your issue though, could you please fill out the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md)?

**Comment by Iznogood1** [comment]
Hi Robin,

please find attached the issue description.

Summary : I can connect my STPF server as a enternal storage if I let the SFTP defaut port (22)
It fails if I change the setting of my SFTP server with another port number.

Rgds




----- Mail original -----
De: "Robin McCorkell" <notifications@github.com>
À: "owncloud/core" <core@noreply.github.com>
Cc: "Iznogood1" <denisns1@free.fr>
Envoyé: Jeudi 23 Juillet 2015 16:00:58
Objet: Re: [core] SFTP external storage - Can not set custom port (#17841)



Thanks for reporting this to us! We need some more information to help you with your issue though, could you please fill out the issue template ? 

— 
Reply to this email directly or view it on GitHub . 


### Steps to reproduce
1. Modify the SFTP port of a server (Ex with Apache Edit /etc/shh/sshd_config and change the line PORT 22 by Port 222)
2. Try to use SFTP External storage on OwnClound
3. Fill the server address to xxx.xxx.xxx.xxx:222

### Expected behaviour
Connection to the serveur by SFTP

### Actual behaviour
Unable to connect to the SFTP : Eror 110 - Time out

### Server configuration
**Operating system**:
Apache

**Web server:**
1and1 mutualize account

**Database:**
MySQL

**PHP version:**
5.8

**ownCloud version:** (see ownCloud admin page)
8.1

**Updated from an older ownCloud or fresh install:**
Fresh installation

**List of activated apps:**
Activity 2.0.1
Default encryption module 1.0.0
Deleted files 0.6.3
External storage support 0.2.3
File Locking
First Run Wizard 1.1
Mail Template Editor 0.1
PDF Viewer 0.7
Pictures 0.6.0
Provisioning API 0.2
Share Files 0.6.2
Text Editor 0.4
Updater 0.6
Versions 1.0.6
Video Viewer 0.1.3



**The content of config/config.php:**
PRIVATE INFORMATION CHANGES TO XXX
<?php
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' => 
  array (
    0 => 'xxx',
    1 => 'xxx',
  ),
  'datadirectory' => '/xxx',
  'overwrite.cli.url' => 'xxx',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'xxx',
  'dbhost' => 'xxx',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'logtimezone' => 'UTC',
  'installed' => true,
  'loglevel' => 0,
);


**Are you using external storage, if yes which one:** local/smb/sftp/...
DropBox OK
FTP OK
SFTP OK without specifying any port -> using 22
SFTP NOT OK if specifying another port number (despite that port is well set up on the SFTP server)

**Are you using encryption:** yes/no
Yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO


### Client configuration
**Browser:**
Firefox

**Operating system:**
Win 7 64 bits

### Logs
#### Web server error log
I repalce my actual SFTP server address by XXX.XXX.XXX.XXX for confidentiality purpose

{"reqId":"VbHgXAouACwAAHQQEpAAAAAj","remoteAddr":"89.167.129.49","app":"PHP","message":"Cannot connect to XXX.XXX.XXX.XXX. Error 111. Connection refused at \/homepages\/22\/d159534284\/htdocs\/cloud\/3rdparty\/phpseclib\/phpseclib\/phpseclib\/Net\/SSH2.php#966","level":3,"time":"2015-07-24T06:51:09+00:00","method":"POST","url":"\/index.php\/apps\/files_external\/globalstorages"}
{"reqId":"VbHgXAouACwAAHQQEpAAAAAj","remoteAddr":"89.167.129.49","app":"files_external","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Login failed\",\"Code\":0,\"Trace\":\"#0 \\\/homepages\\\/22\\\/d159534284\\\/htdocs\\\/cloud\\\/apps\\\/files_external\\\/lib\\\/sftp.php(129): OC\\\\Files\\\\Storage\\\\SFTP->getConnection()\\n#1 \\\/homepages\\\/22\\\/d159534284\\\/htdocs\\\/cloud\\\/apps\\\/files_external\\\/lib\\\/config.php(497): OC\\\\Files\\\\Storage\\\\SFTP->test(false)\\n#2 \\\/homepages\\\/22\\\/d159534284\\\/htdocs\\\/cloud\\\/apps\\\/files_external\\\/controller\\\/storagescontroller.php(123): OC_Mount_Config::getBackendStatus('\\\\\\\\OC\\\\\\\\Files\\\\\\\\Stora...', Array, false)\\n#3 \\\/homepages\\\/22\\\/d159534284\\\/htdocs\\\/cloud\\\/apps\\\/files_external\\\/controller\\\/globalstoragescontroller.php(100): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus(Object(OCA\\\\Files_external\\\\Lib\\\\StorageConfig))\\n#4 [internal function]: OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController->create('SFTP', '\\\\\\\\OC\\\\\\\\Files\\\\\\\\Stora...', Array, NULL, Array, Array, 100)\\n#5 \\\/homepages\\\/22\\\/d159534284\\\/htdocs\\\/cloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#6 \\\/homepages\\\/22\\\/d159534284\\\/htdocs\\\/cloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'create')\\n#7 \\\/homepages\\\/22\\\/d159534284\\\/htdocs\\\/cloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'create')\\n#8 \\\/homepages\\\/22\\\/d159534284\\\/htdocs\\\/cloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('GlobalStoragesC...', 'create', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#9 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#10 \\\/homepages\\\/22\\\/d159534284\\\/htdocs\\\/cloud\\\/lib\\\/private\\\/route\\\/router.php(274): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#11 \\\/homepages\\\/22\\\/d159534284\\\/htdocs\\\/cloud\\\/lib\\\/base.php(867): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#12 \\\/homepages\\\/22\\\/d159534284\\\/htdocs\\\/cloud\\\/index.php(40): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/homepages\\\/22\\\/d159534284\\\/htdocs\\\/cloud\\\/apps\\\/files_external\\\/lib\\\/sftp.php\",\"Line\":113}","level":4,"time":"2015-07-24T06:51:09+00:00","method":"POST","url":"\/index.php\/apps\/files_external\/globalstorages"}
{"reqId":"VbHgXAouACwAAHQQEpAAAAAj","remoteAddr":"89.167.129.49","app":"PHP","message":"Connection closed prematurely at \/homepages\/22\/d159534284\/htdocs\/cloud\/3rdparty\/phpseclib\/phpseclib\/phpseclib\/Net\/SSH2.php#3143","level":3,"time":"2015-07-24T06:51:09+00:00","method":"POST","url":"\/index.php\/apps\/files_external\/globalstorages"}
{"reqId":"VbHgXAouACwAAHQQEpAAAAAj","remoteAddr":"89.167.129.49","app":"PHP","message":"fclose() expects parameter 1 to be resource, boolean given at \/homepages\/22\/d159534284\/htdocs\/cloud\/3rdparty\/phpseclib\/phpseclib\/phpseclib\/Net\/SSH2.php#3379","level":3,"time":"2015-07-24T06:51:09+00:00","method":"POST","url":"\/index.php\/apps\/files_external\/globalstorages"}
{"reqId":"VbHgXAouACwAAHQQEpAAAAAj","remoteAddr":"89.167.129.49","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2015-07-24T06:51:09+00:00","method":"POST","url":"\/index.php\/apps\/files_external\/globalstorages"}


#### ownCloud log (data/owncloud.log)

**Comment by SergioBertolinSG** [comment]
beware of https://github.com/owncloud/core/issues/16457

**Comment by Iznogood1** [comment]
Thanks SergioBertolinSG.

I have tried with another prot and it works fine !
Port 222 = issue
Another one is OK !

The bug can be close.

Rgds
