### ISSUE TITLE
Make conditional logging work with exclusions

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#17845]
### Current situation
- the files_locking app is flooding the logs with Info messages
- I need to add all the other apps in the log.condition array and maintain that list
### Ideal solution

I simply exclude files_locking in log.condition, maybe using `['!files_locking']`

What do you think @MorrisJobke ?

**Comment by MorrisJobke** [comment]
I would simply add another category `excluded_apps` and not put in many conditions, because the logging is a very critical subsystem and it is called very often. So I would like to keep the logic in there as low as possible.
