### ISSUE TITLE
Cannot install any app. Invalid OCS Content for everything

### ISSUE THREAD

**Issue by floweh** [owncloud/core#17844]
Error Log says:
Fatal	core	Invalid OCS content returned for app 168708	2015-07-23T15:45:11+00:00

168708 is the Contacts App. When trying to install it it says "activating" for a second. Then "activated" but after refreshing nothing happened. No other error messages than the small log entry.
Version: ownCloud 8.0.4 (stable)

**Comment by RealRancor** [comment]
Try to update to the latest stable 8.0.5

**Comment by floweh** [comment]
8.0.5 is not available via the updater for me.

**Comment by RealRancor** [comment]
Then just do the manual update.

**Comment by LukasReschke** [comment]
Yes. Requires a manual update.

**Comment by floweh** [comment]
Now after the update there is a new error:
`Could not get application: SSL CA bundle not found: /var/www/virtual/whnr/vectoapp/owncloud/config/ca-bundle.crt`

**Comment by RealRancor** [comment]
@floweh Yes, thats a known issue of the updater app.
