### ISSUE TITLE
Make it possible to scroll with keys

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#17848]
It's not possible to scroll with the arrow keys as it is today, tough other keys work, like [esc] i.e. It would be nice to be able to scroll with the keys as well, i.e. when you have a long list of files.

What do you think @jancborchardt ?

**Comment by Xenopathic** [comment]
Arrow keys should be used to select an entry in the file list, not scroll the file list. That way, pressing Enter opens that file entry, like clicking on it.

**Comment by enoch85** [comment]
@Xenopathic Let´s say that I want to scroll through the activities, can it do both?

**Comment by Xenopathic** [comment]
@enoch85 Ah, I see, not just the Files app. Unfortunately that all gets controlled by the app, with `tabindex` and related attributes.

**Comment by oparoz** [comment]
Works for me using Firefox in both Files and Gallery

**Comment by enoch85** [comment]
@oparoz Which versions are you running?

**Comment by nickvergessen** [comment]
Works here as well with FF39 and master's file list.
However, I have no idea why and how. Would be nice if someone can post the details how I can get it working on activities (but I think it needs a table?!)

**Comment by jancborchardt** [comment]
@nickvergessen no table needed, just focusable elements. Give an element `tabindex="0"` and it will be focusable. Read more at https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex

**Comment by enoch85** [comment]
I close this as it works in core.
