### ISSUE TITLE
Undefined index: REMOTE_ADDR at /www/htdocs/w016666/domain.xxx.com/folder/lib/private/appframework/http/request.php#481

### ISSUE THREAD

**Issue by farson2003** [owncloud/core#17859]
Hello,
new error detectd:

I tried to configure OC8.1 via changing the config.php to make use of allinkl's SSL Proxy.
In the config.php I changed to:
'overwrite.cli.url' => 'https://ssl-account.com//domain.xxx.com/folder/',

and added:

'overwritehost' => 'ssl-account.com',
'overwriteprotocol' => 'https',
'overwritewebroot' => '/domain.xxx.com/folder',
'overwritecondaddr' => '^85\\.13\\.128\\.137$',

Now I get the error message in the log:
Undefined index: REMOTE_ADDR at /www/htdocs/w0666/domain.xxx.com/folder/lib/private/appframework/http/request.php#481

It is a fresh OC8.1 instllation.

OC appears to work normally through the proxy.
Thank you

**Comment by Xenopathic** [comment]
Fixed in #17682 (backport #17697), will be released with 8.1.1.
