### ISSUE TITLE
Help with using the provisioning api with php

### ISSUE THREAD

**Issue by Rustypredator** [owncloud/core#17857]
Im trying to use the provisioning api with my site using php.
when i use a linux cli with curl it works without problems:
```
curl https://<username>:<pass>@clangaming.net/cloud/ocs/v1.php/cloud/users -d userid="peter" -d password="peter" --insecure
```
so it ist an problem with my code:
```php
<?php
        $apiurl = 'https://<username>:<pass>@clangaming.net/cloud/ocs/v1.php/cloud/users -d userid="peter" -d password="peter"';
        $call = curl_init($apiurl);
        curl_setopt($call, CURLOPT_POST, true);
        curl_setopt($call, CURLOPT_SSL_VERIFYPEER, false);
        print curl_exec($call);
        curl_close($call);
?>
```
this is the output:
```xml
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>101</statuscode>
  <message>Bad request</message>
 </meta>
 <data/>
</ocs>
```
What am i doing wrong?
i used this as reference:https://secure.php.net/manual/de/curl.examples-basic.php
Should i use something other than php curl?

**Comment by RealRancor** [comment]
Hi,

i think such questions are better placed at the developers mailinglist:

https://mailman.owncloud.org/mailman/listinfo/devel

or the irc channel #owncloud-dev at freenode. This here is an issue tracker where you can report bugs or feature requests.

**Comment by Rustypredator** [comment]
Ok, thanks.
I will ask there

**Comment by LukasReschke** [comment]
>         $apiurl = 'https://<username>:<pass>@clangaming.net/cloud/ocs/v1.php/cloud/users -d userid="peter" -d password="peter"';

Is completely wrong. Please take a look on how to send post data with cURL in PHP: http://stackoverflow.com/questions/28395/passing-post-values-with-curl
