### ISSUE TITLE
Sync Issue with desktop app

### ISSUE THREAD

**Issue by heartsaver1859** [owncloud/core#17856]
### Steps to reproduce
1. new file created

### Expected behaviour
sync new file

### Server configuration
**Operating system**:
Ubuntu 14.04.2

**Web server:**
Apache 2.4.12

**Database:**
Mysql 5.5.44-0ubuntu0.14.04.1

**PHP version:**
PHP 5.6.11-1+deb.sury.org~trusty+1

**ownCloud version:** (see ownCloud admin page)
8.1

**Updated from an older ownCloud or fresh install:**
fresh install

**List of activated apps:**
 - activity: 2.0.1
 - calendar: 0.7.1
 - contacts: 0.4.0.0
 - documents: 0.9.0
 - files: 1.1.9
 - files_locking:
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.6

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' => 
  array (
    0 => 'xxx',
  ),
  'datadirectory' => '/data/var/data',
  'overwrite.cli.url' => 'xxx',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'owncloud_8_1',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'ssl',
  'mail_from_address' => 'owncloud',
  'mail_domain' => 'xxx',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'xxx',
  'mail_smtpport' => 'xxx',
  'mail_smtpname' => 'xxx',
  'mail_smtppassword' => 'xxx',
  'theme' => '',
  'maintenance' => false,
  'memcache.local' => '\OC\Memcache\Memcached',
);

**Are you using encryption:** yes/no
no

### Client configuration
**Browser:**
Chrome 44

**Operating system:**
Windows 8.1

#### Web server error log
```
Insert your webserver log here
[Fri Jul 24 21:03:23.135508 2015] [authz_core:error] [pid 2016] [client xxx] AH01630: client denied by server configuration: /data/var/www/owncloud/
[Fri Jul 24 22:00:22.496989 2015] [authz_core:error] [pid 4274] [client xxx] AH01630: client denied by server configuration: /data/var/www/owncloud/

#### ownCloud log (data/owncloud.log)
{"reqId":"dC8FStQTtV3dMroAG4td","remoteAddr":"87.160.110.25","app":"PHP","message":"Array to string conversion at \/data\/var\/www\/owncloud\/lib\/private\/template\/functions.php#36","level":3,"time":"2015-07-19T20:35:16+00:00"}
{"reqId":"5NvqvccBUxB0q0wJ\/FD2","remoteAddr":"87.160.104.216","app":"PHP","message":"Array to string conversion at \/data\/var\/www\/owncloud\/lib\/private\/template\/functions.php#36","level":3,"time":"2015-07-20T22:45:01+00:00"}
{"reqId":"RtKY4Nx5gZZUH7bh61mN","remoteAddr":"2.206.201.137","app":"PHP","message":"Array to string conversion at \/data\/var\/www\/owncloud\/lib\/private\/template\/functions.php#36","level":3,"time":"2015-07-23T14:43:41+00:00"}
{"reqId":"+pMoSUfWnvLoPuoWmgmB","remoteAddr":"2.243.227.231","app":"PHP","message":"Array to string conversion at \/data\/var\/www\/owncloud\/lib\/private\/template\/functions.php#36","level":3,"time":"2015-07-24T20:16:21+00:00"}
{"reqId":"a+Jw5ZJ3pce3rRF1anAh","remoteAddr":"2.243.227.231","app":"PHP","message":"Array to string conversion at \/data\/var\/www\/owncloud\/lib\/private\/template\/functions.php#36","level":3,"time":"2015-07-24T20:27:48+00:00"}
Insert your ownCloud log here
```

#### Desktop App log
```
24.07.2015 22:00:59Bilder/Lightroom/daten/Lightroom Catalog Previews.lrdata/0/0FE9/0FE979B7-70C2-40E7-97AF-B9B264DCED14-1a79e75ea6e901ca1dbdcbd0949760be.lrfprevownCloud       Nicht erlaubt, da Sie keine Rechte zum Hinzufügen von Dateien in diesen Ordner haben          
24.07.2015 22:00:59Bilder/Lightroom/daten/Lightroom Catalog Previews.lrdata/0/0ED7/0ED7C227-9BE4-46FF-A00F-DA55DB844ECB-6dad2e057908512ea42a5305de35a1a7.lrfprevownCloud       Nicht erlaubt, da Sie keine Rechte zum Hinzufügen von Dateien in diesen Ordner haben          
24.07.2015 22:00:59Bilder/Lightroom/daten/Lightroom Catalog Previews.lrdata/0/0A97/0A971909-8A28-4579-8E64-F8AEB22A1BFB-8964bbbf68ffc698e34526a4b6f128c1.lrfprevownCloud       Nicht erlaubt, da Sie keine Rechte zum Hinzufügen von Dateien in diesen Ordner haben          
24.07.2015 22:00:59Bilder/Lightroom/daten/Lightroom Catalog Previews.lrdata/0/077B/077B6877-F7C8-4ECC-B36B-3B48D1EF63EA-609e7f854ef5cf7a16088ae7d151404d.lrfprevownCloud       Nicht erlaubt, da Sie keine Rechte zum Hinzufügen von Dateien in diesen Ordner haben          
24.07.2015 22:00:59Bilder/Lightroom/daten/Lightroom Catalog Previews.lrdata/0/0377/037718CA-72CF-433B-94F2-EA4C78F71C9A-40b0e44b57a275fab692976ef69391af.lrfprevownCloud       Nicht erlaubt, da Sie keine Rechte zum Hinzufügen von Dateien in diesen Ordner haben          
24.07.2015 22:00:59Bilder/Lightroom/daten/Lightroom Catalog Previews.lrdata/0/02D3/02D3D6F9-C191-4AF3-B510-12D55E86A39F-63aeeff4f8a46cf1b7b19a4ad7f72a2b.lrfprevownCloud       Nicht erlaubt, da Sie keine Rechte zum Hinzufügen von Dateien in diesen Ordner haben     
```

**Comment by guruz** [comment]
Which client version?

**Comment by heartsaver1859** [comment]
Version 1.8.4

**Comment by heartsaver1859** [comment]
Can someone please help this is really annoying....

**Comment by PVince81** [comment]
Array to string conversion error spotted here: https://github.com/owncloud/core/issues/17782
Not sure if related...

**Comment by DeepDiver1975** [comment]
looks like a permission issue - is that a local folder/file?
Bilder/Lightroom/daten/Lightroom Catalog Previews.lrdata/0/0ED7/0ED7C227-9BE4-46FF-A00F-DA55DB844ECB-6dad2e057908512ea42a5305de35a1a7.lrfprevownCloud

**Comment by heartsaver1859** [comment]
Yes it is a local file and folder

**Comment by MorrisJobke** [comment]
@heartsaver1859 What are the permissions of this file and the parent folder on the server side?

**Comment by Kawohl** [comment]
Closing since no reaction in two months.
