### ISSUE TITLE
Crash when creating folder with Chinese characters

### ISSUE THREAD

**Issue by hphuangpu** [owncloud/core#17850]
When I try to create a folder with Chinese characters, the system will crash and I can't rename or delete that folder. 

The OS is windows server 2012 R2 with 64bit

**Comment by karlitschek** [comment]
Can you post a full bug report using this template please?
https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

@PVince81 any idea?

**Comment by hphuangpu** [comment]
Ok I do my best.

**Comment by hphuangpu** [comment]
How to give the report to you ? @karlitschek

**Comment by hphuangpu** [comment]
-I will use a new installed Owncloud without any configuration. This is the report.
-We are a company and we want to use Owncloud to manage the company files and share to our college.
-We are glad to see the Owncloud can run in our server and hope to get your response.
-Any further questions you can also send email to hi@hphuangpu.com


### Steps to reproduce
1. I use account "admin" to install the owncloud system and login as "admin"
2. rename the name of folder with Chinese
3. crash

### Expected behaviour
Create Folder with Chinese Name

### Actual behaviour
The final name of the folder in webpage becomes "files", I can't rename or delete that folder anymore. But in /owncloud/data/admin/files in the computer, I can see the folder but its name is changing to "d2fb1e3e171039bde5e15f5e35b1756e"

### Server configuration
**Operating system:**
Windows server 2012 R2 with 64 bit

**Web server:**
Apache 2.4.9(win64)

**Database:**
Mysql 5.6.17

**PHP version:**
php 5.5.12

**ownCloud version:** (see ownCloud admin page)
Owncloud 8.0.4

**Updated from an older ownCloud or fresh install:**
fresh install

**List of activated apps:**
fresh install without any changes
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system --public
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
<?php
$CONFIG = array (
  'instanceid' => 'oczh0umnok7a',
  'passwordsalt' => '******confidential*******',
  'secret' => '******confidential*******',
  'trusted_domains' => 
  array (
    0 => 'localhost',
 '****otherserver****' ),
  'datadirectory' => 'F:\\www\\owncloud\\data',
  'overwrite.cli.url' => 'http://localhost/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.4.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin3',
  'dbpassword' => '******confidential*******',
  'installed' => true,
);



**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)

```
On ownCloud 7+ with access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

On ownCloud 6 with access to your command line run e.g.:
sqlite3 data/owncloud.db or mysql -u root -p owncloud
then execute:  select * from oc_appconfig where appid='user_ldap';

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query above.

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
Internet explorer 11, safari 8.0.7 (10600.7.12)

**Operating system:**
winserver 2012 r2, Macos 10.10.4
### Logs
#### Web server error log
```
Insert your webserver log here
```

[Fri Jul 24 10:28:12.322178 2015] [authz_core:error] [pid 1352:tid 948] [client ::1:62947] AH01630: client denied by server configuration: F:/www/owncloud/data/htaccesstest.txt
[Fri Jul 24 10:30:02.712308 2015] [authz_core:error] [pid 1352:tid 968] [client ::1:62960] AH01630: client denied by server configuration: F:/www/owncloud/data/htaccesstest.txt
[Fri Jul 24 10:30:34.572908 2015] [authz_core:error] [pid 1352:tid 932] [client ::1:62992] AH01630: client denied by server configuration: F:/www/owncloud/data/htaccesstest.txt
[Fri Jul 24 10:49:18.710217 2015] [authz_core:error] [pid 1352:tid 976] [client 192.168.31.104:63059] AH01630: client denied by server configuration: F:/www/owncloud/data/htaccesstest.txt
[Fri Jul 24 10:50:11.839365 2015] [authz_core:error] [pid 1352:tid 976] [client 192.168.31.104:63069] AH01630: client denied by server configuration: F:/www/owncloud/data/htaccesstest.txt


#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

{"reqId":"b7824ce495e17ac24711495ab02aff62","remoteAddr":"::1","app":"PHP","message":"touch(): Unable to create file F:\/www\/owncloud\/data\/owncloud.log because No such file or directory at F:\\www\\owncloud\\lib\\private\\log\\owncloud.php#48","level":3,"time":"2015-07-24T02:28:12+00:00"}


#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
JS error:Failed to load resource: the server responded with a status of 404 (Not Found)  http://****server****/owncloud/core/vendor/jquery/dist/jquery-migrate.min.map

**Comment by hphuangpu** [comment]
-I will use a new installed Owncloud without any configuration. This is the report.
-We are a company and we want to use Owncloud to manage the company files and share to our college.
-We are glad to see the Owncloud can run in our server and hope to get your response.
-Any further questions you can also send email to hi@hphuangpu.com


### Steps to reproduce
1. I use account "admin" to install the owncloud system and login as "admin"
2. rename the name of folder with Chinese
3. crash

### Expected behaviour
Create Folder with Chinese Name

### Actual behaviour
The final name of the folder in webpage becomes "files", I can't rename or delete that folder anymore. But in /owncloud/data/admin/files in the computer, I can see the folder but its name is changing to "d2fb1e3e171039bde5e15f5e35b1756e"

### Server configuration
**Operating system:**
Windows server 2012 R2 with 64 bit

**Web server:**
Apache 2.4.9(win64)

**Database:**
Mysql 5.6.17

**PHP version:**
php 5.5.12

**ownCloud version:** (see ownCloud admin page)
Owncloud 8.0.4

**Updated from an older ownCloud or fresh install:**
fresh install

**List of activated apps:**
```
fresh install without any changes
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'oczh0umnok7a',
  'passwordsalt' => '******confidential*******',
  'secret' => '******confidential*******',
  'trusted_domains' => 
  array (
    0 => 'localhost',
 '****otherserver****' ),
  'datadirectory' => 'F:\\www\\owncloud\\data',
  'overwrite.cli.url' => 'http://localhost/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.4.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin3',
  'dbpassword' => '******confidential*******',
  'installed' => true,
);
```




**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no


### Client configuration
**Browser:**
Internet explorer 11, safari 8.0.7 (10600.7.12)

**Operating system:**
winserver 2012 r2, Macos 10.10.4
### Logs
#### Web server error log
```
[Fri Jul 24 10:28:12.322178 2015] [authz_core:error] [pid 1352:tid 948] [client ::1:62947] AH01630: client denied by server configuration: F:/www/owncloud/data/htaccesstest.txt
[Fri Jul 24 10:30:02.712308 2015] [authz_core:error] [pid 1352:tid 968] [client ::1:62960] AH01630: client denied by server configuration: F:/www/owncloud/data/htaccesstest.txt
[Fri Jul 24 10:30:34.572908 2015] [authz_core:error] [pid 1352:tid 932] [client ::1:62992] AH01630: client denied by server configuration: F:/www/owncloud/data/htaccesstest.txt
[Fri Jul 24 10:49:18.710217 2015] [authz_core:error] [pid 1352:tid 976] [client 192.168.31.104:63059] AH01630: client denied by server configuration: F:/www/owncloud/data/htaccesstest.txt
[Fri Jul 24 10:50:11.839365 2015] [authz_core:error] [pid 1352:tid 976] [client 192.168.31.104:63069] AH01630: client denied by server configuration: F:/www/owncloud/data/htaccesstest.txt
```




#### ownCloud log (data/owncloud.log)
```
{"reqId":"b7824ce495e17ac24711495ab02aff62","remoteAddr":"::1","app":"PHP","message":"touch(): Unable to create file F:\/www\/owncloud\/data\/owncloud.log because No such file or directory at F:\\www\\owncloud\\lib\\private\\log\\owncloud.php#48","level":3,"time":"2015-07-24T02:28:12+00:00"}
```



#### Browser log
```
JS error:Failed to load resource: the server responded with a status of 404 (Not Found)  http://****server****/owncloud/core/vendor/jquery/dist/jquery-migrate.min.map
```

**Comment by nickvergessen** [comment]
Sorry, but windows is no longer supported since ownCloud8 as an operating system for the server.

**Comment by hphuangpu** [comment]
I give you some screenshots

1. 2 default folders and a sample pdf file when first login.
<img width="349" alt="step-1" src="https://cloud.githubusercontent.com/assets/3396735/8867334/801325b6-31fa-11e5-9691-4c80bcca8003.png">

2. Click rename icon and begin to rename it.
<img width="316" alt="step-2" src="https://cloud.githubusercontent.com/assets/3396735/8867377/14537442-31fb-11e5-8f83-2262b6401940.png">

3. There is no error when rename with English.
<img width="358" alt="step-3" src="https://cloud.githubusercontent.com/assets/3396735/8867380/20b1db5c-31fb-11e5-8def-416e683209c7.png">

4. But when I try to rename with Chinese
<img width="337" alt="step-4" src="https://cloud.githubusercontent.com/assets/3396735/8867386/33888dfc-31fb-11e5-968b-e2a5b3b1c72a.png">

5. When I press ENTER, the name changes to "files"
<img width="301" alt="step-5" src="https://cloud.githubusercontent.com/assets/3396735/8867394/4672b1e0-31fb-11e5-84d0-b1b83a3de324.png">

6. Then I try to delete it
<img width="728" alt="step-6" src="https://cloud.githubusercontent.com/assets/3396735/8867402/5f14ee34-31fb-11e5-9e38-0ba4c7eca93c.png">

7. Now it is deleted, like this
<img width="725" alt="step-7" src="https://cloud.githubusercontent.com/assets/3396735/8867404/78e8dfa0-31fb-11e5-9c4d-bf3064b1a03e.png">

8. But when I refresh the webpage, it comes again
<img width="723" alt="step-8" src="https://cloud.githubusercontent.com/assets/3396735/8867410/8daa4e10-31fb-11e5-8dcb-171c203e92c8.png">

9. And when I try to rename it again
<img width="471" alt="step-9" src="https://cloud.githubusercontent.com/assets/3396735/8867418/a3817128-31fb-11e5-8642-e0d5f699b065.png">

10. It says I can't rename because the folder is already been deleted.
<img width="470" alt="step-10" src="https://cloud.githubusercontent.com/assets/3396735/8867424/ada99ae0-31fb-11e5-9ac1-337d52dcffaf.png">

11. I checked the catalog of the real path, the name of the error folder changes to "d2fb1e3e171039bde5e15f5e35b1756e"(still exist)
![img_7528](https://cloud.githubusercontent.com/assets/3396735/8868180/45ca1dd0-3207-11e5-927a-25ef82a4b82c.JPG)

**Comment by hphuangpu** [comment]
Sorry, do you mean OwnCloud(< 8) is fully support windows without this problem? @nickvergessen

**Comment by LukasReschke** [comment]
No. It will have the same bugs there.

**Comment by DeepDiver1975** [comment]
windows server is no longer supported - sorry

**Comment by hphuangpu** [comment]
If the problem is caused by encoding difference. I hope i can do something to fix it. Could you guide me where the problem comes from? At least other functions can run on windows well.
