### ISSUE TITLE
Windows ownCloud client kills VNC

### ISSUE THREAD

**Issue by jdwirtz** [owncloud/core#17854]
On my windows 7 64bit PC, I run a lot of VNC sessions and when ownCloud runs an update, it causes all my VNC sessions to  crash. It also disconnects my weather gadget.  This will also happen if I Quit Owncloud.  Is there a fix for this??

**Comment by DeepDiver1975** [comment]
Can I ask you to reopen this issue in https://github.com/owncloud/client ? THX

**Comment by jdwirtz** [comment]
Just did it.

Jim
