### ISSUE TITLE
OC with proxy: Fialure to redirect to https Proxy Address

### ISSUE THREAD

**Issue by farson2003** [owncloud/core#17860]
Hello,
Following error detectd:

W configured OC8.1 via changing the config.php to make use of allinkl's SSL Proxy.
In the config.php I changed to:
'overwrite.cli.url' => 'https://ssl-account.com/subd.domain.xxx.com/',

and added:

'overwritehost' => 'ssl-account.com',
'overwriteprotocol' => 'https',
'overwritewebroot' => '/subd.domain.xxx.com',
'overwritecondaddr' => '^85\.13\.128\.137$',
  'forcessl' => true,

It is a fresh OC8.1 instllation.

OC appears to work normally through the proxy ('https://ssl-account.com/subd.domain.xxx.com/)

But:
When typing in the browser line: subd.domain.xxx.com or www.subd.domain.xxx.com we are NOT redirected to https://ssl-account.com/subd.domain.xxx.com and the page shows a corrupted login screen (see screenshot):
![corrupted login](https://cloud.githubusercontent.com/assets/3358665/8888741/246b0018-32b2-11e5-8897-123fd6b3c8ce.png)

**Comment by karlitschek** [comment]
the forcessl option does no longer exist in 8.1 This should be done with a webserver redirect rule.

**Comment by RealRancor** [comment]
Ref to the documentation part of this: https://doc.owncloud.org/server/8.1/admin_manual/configuration_server/harden_server.html#use-https
