### ISSUE TITLE
Can't reset password

### ISSUE THREAD

**Issue by nucshuco** [owncloud/core#17869]
ownCloud 8.1.0 (stable)
FreeNAS-9.3-STABLE-201506292130

If I try to reset it, email is sent, the link work, you can put the new password in and click on reset password, but nothing happens. Page doesn't change and if you try to login with new password it doesn't work.

the only thing in the log is
Warning	core	Login failed: 'jerrt' (Remote IP: '70.197.72.48)
![2514](https://cloud.githubusercontent.com/assets/8262089/8890913/42456758-32c7-11e5-8c0f-881db40b20db.PNG)

**Comment by LukasReschke** [comment]
Thanks a lot for reporting issues back to us!

We need some more information to properly support you with your issue!

Can I ask you to follow our guidelines for submitting bugs as described here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by urvishpatel15** [comment]
if you can't change password of admin or forgotten admin password,then, watch this video https://www.youtube.com/watch?v=o5z_RpnIZM8

read this post : http://dimslab.ml/main/?p=48  :100: % working !

**Comment by nucshuco** [comment]
I was just testing the forgotten password. I'm not locked out.

**Comment by amitfocis** [comment]
Confirmed -- I'm experiencing this issue with OwnCloud running with Apache/Ubuntu 14.04 LTS. OwnCloud version is 8.1.0 (stable)

**Comment by DeepDiver1975** [comment]
@rperezb the password reset scenario has to be added to the test plan - we got some reports on this already in the past - this should really work :speak_no_evil:

**Comment by rperezb** [comment]
yes, @DeepDiver1975 having this in mind, perhaps, we should spend some time checking the user view as well as functionality related to passwords, such as this one.
@cmonteroluque, what do you think? we may plan this, once the new versions are released.

**Comment by SergioBertolinSG** [comment]
tested using 8.1.1, working correctly in firefox and safari, password is reset.
