### ISSUE TITLE
Admin-Page: Sharing-settings are available when sharing app is disabled

### ISSUE THREAD

**Issue by tflidd** [owncloud/core#17863]
OC 8.0.4 setup. OC 8.1 as well.

reproduce: 
1. disable sharing app
2. go to admin-page

expected result:
- no settings of the sharing should be possible
  or
- settings are available, but a warning that sharing app must be enabled to use sharing (or button to do so)

current situation:
- full configuration of the sharing app is possible as if sharing was available and working. Users might be wondering why sharing is not possible in the file app

**Comment by karlitschek** [comment]
Well there is also sharing beside file sharing. for example in calendar, gallery and so on. 
@schiesbn @jancborchardt   Do you think this can be clarified?

**Comment by jancborchardt** [comment]
But … when you disable the sharing app, then it should be disabled for Calendar, Gallery etc as well?

**Comment by PVince81** [comment]
The "sharing app" so far was actually "files_sharing", so only for files.

As per 9.0 the sharing code will be decoupled, but we might still want to clean up this phenomenon.

@rullzer

**Comment by rullzer** [comment]
Yes we do. We need to decouple and move some stuff around. Which we can now since the files_sharing is about just files/folders now.
