### ISSUE TITLE
Prefix QueryBuilder stuff with *PREFIX*

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#17862]
Since we now have the query builder I'd appreciate if we could automatically prepend the prefix. 

e.g.:

```php
$qb = $this->connection->getQueryBuilder();
$qb->insert('*PREFIX*vcategory_to_object')
	->values([
		'objid'			=> $qb->createNamedParameter($objectId, \PDO::PARAM_INT),
		'categoryid'	=> $qb->createNamedParameter($category, \PDO::PARAM_INT),
		'type'			=> $qb->createNamedParameter($type),
	])
	->execute();
```

vs.

```php
$qb = $this->connection->getQueryBuilder();
$qb->insert('vcategory_to_object')
	->values([
		'objid'			=> $qb->createNamedParameter($objectId, \PDO::PARAM_INT),
		'categoryid'	=> $qb->createNamedParameter($category, \PDO::PARAM_INT),
		'type'			=> $qb->createNamedParameter($type),
	])
	->execute();
```

@DeepDiver1975 @nickvergessen Any reason that we can't do this?

**Comment by LukasReschke** [comment]
Also let's summon some other folks such as @rullzer

**Comment by rullzer** [comment]
yes please! Makes the code a lot more readable since we use it everywhere anyway.

Should we check in the functions for `PREFIX` ? And if somebody uses them with it write to the log or something?

**Comment by LukasReschke** [comment]
> Should we check in the functions for PREFIX ? And if somebody uses them with it write to the log or something?

Mhm. New public API with 8.2 and not really widely used. I'd vote for adjusting the existing stuff just if we decide that we can get this in.

**Comment by rullzer** [comment]
Ok, agreed. Lets not make this more complicated :)

**Comment by nickvergessen** [comment]
But that breaks querys of apps to third party tables which don't have the prefix. E.g. my to-be-developed phpbb-auth plugin

**Comment by LukasReschke** [comment]
Which is like 0.01% of all apps? :speak_no_evil: 

What about having an additional `->usePrefix(false)` which defaults to `true`?

**Comment by rullzer** [comment]
> What about having an additional `->usePrefix(false)` which defaults to `true`?

Could be... but assume you want to join a table X with and owncloud table Y

```
$qb->usePrefix(false)
  ->select(...)
  ->from(X)
  ...
  ->usePrefix(true)
  ->innerJoin(Y)
```

I'm not sure that gets more readable.
Maybe just add an extra argument to the commands accepting a table? (usePrefix, which defaults to true).

```
$qb->select(...)
  ->from(X, null, false)
  ...
  ->innerJoin(Y)
```

Altough also not that nice.


I'm fine either way. But like @LukasReschke says. almost all apps will probably want to use the prefix by default. so it makes sense to make the common case nice, pretty and easy, and the exception maybe a little harder to write.

**Comment by nickvergessen** [comment]
usePrefix sounds fine, could also make the prefix magic string a public method to make it easier, when usePrefix is off. Just call a method in all table name usages, when it's on prefix with the method call to getPrefix()
