### ISSUE TITLE
Non-standard HTTPS port

### ISSUE THREAD

**Issue by peterkahl** [owncloud/core#17872]
I've been using a non 443 HTTPS port on my ownCloud server for a while, but only recently noticed that in many situations the URL does not pass the port number string.
Should be:
```
https://sub.domain.tld:XXXXX/index.php
```
Incorrectly is:
```
https://sub.domain.tld/index.php
```
Not sure if this is related to my php.ini settings?

**Comment by peterkahl** [comment]
Looking at the server log, the request is
```
GET https://sub.domain.tld:6992/index.php HTTP/1.1
```
...to which ownCloud replies with status 302
```
302 FOUND https://sub.domain.tld/index.php
```

**Comment by RealRancor** [comment]
Hi,

have a look at this setting:

https://github.com/owncloud/core/blob/v8.1.0/config/config.sample.php#L341-L347

**Comment by peterkahl** [comment]
This might be the life saver! Will give it a try! Thanks. 

--
"You can only lose what you cling to." ~ Siddhartha Gautama

**Comment by peterkahl** [comment]
It seems to be working now with the above solution. Strange that OC cannot detect hostname and port number. I think the developers could try harder.
