### ISSUE TITLE
Failing first try at update to 8.1.0

### ISSUE THREAD

**Issue by ElToro1966** [owncloud/core#17874]
When I tried to update to 8.1.0 from 8.0.4 I got:
GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate

This appears after "Updated "files_versions" to 1.0.6" in the list of successfully completed update tasks.

Note: I started the update via Softacoulous (CPanel). When I tried to update via my ownCloud URL, the upgrade completed successfully on the second attempt.

**Comment by RealRancor** [comment]
Hi,

very likely a dup of https://github.com/owncloud/core/issues/17446

Seems this is a bug in openssl according to: https://github.com/owncloud/core/issues/17446#issuecomment-122275555 and https://github.com/owncloud/core/issues/17446#issuecomment-122875425

**Comment by ytrezq** [comment]
@ElToro1966    
 
@batermj hello I know this is unrelated to this page, but I saw you are [one of](https://gist.github.com/ytrezq/b88bfb074b70885cd543/stargazers) my [followers](https://gist.github.com/ytrezq/b88bfb074b70885cd543). Can you please send your e-mail ? I have a few question for you.
