### ISSUE TITLE
bootstrap tooltip broke tipsy for app levels

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#17870]
Regression caused by https://github.com/owncloud/core/pull/17075

**Comment by LukasReschke** [comment]
Basically everything using `.fallback` is broken, see https://github.com/owncloud/core/blob/1e48eb88828acd10e53bbb727fbe306b09400ebe/settings/js/apps.js#L121-L123 for the affected code.

**Comment by LukasReschke** [comment]
Proposed patch is at https://github.com/owncloud/core/pull/17871

**Comment by davitol** [comment]
:+1: Looks good
