### ISSUE TITLE
Log spammed with `Service unavailable` during upgrade

### ISSUE THREAD

**Issue by Xenopathic** [owncloud/core#17885]
When ownCloud needs an upgrade, any WebDAV connections made will result in log entries (these ones are from syslog btw). These are all at the FATAL log level:

```
{webdav} Exception: {"Message":"HTTP\/1.1 503 Service unavailable","Code":0,"Trace":"#0 [internal function]: {closure}(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/usr\/share\/webapps\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\n#2 \/usr\/share\/webapps\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \/usr\/share\/webapps\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/usr\/share\/webapps\/owncloud\/remote.php(64): Sabre\\DAV\\Server->exec()\n#5 \/usr\/share\/webapps\/owncloud\/remote.php(135): handleException(Object(RemoteException))\n#6 {main}","File":"\/usr\/share\/webapps\/owncloud\/remote.php","Line":55}
{remote} Service unavailable
```

This is due to `remote.php` indiscriminately logging any exception thrown, and an exception is thrown (with the status STATUS_SERVICE_UNAVAILABLE) when the instance needs an upgrade.

It seems that in general `remote.php` is far too verbose in its logging, as it will also log any Not Found errors. I can imagine this could quickly lead to a DoS, as log files fill up rapidly with (ultimately useless) error messages.

Relevant code:

 - https://github.com/owncloud/core/blob/master/remote.php#L50-L63
 - https://github.com/owncloud/core/blob/master/remote.php#L70

**Comment by karlitschek** [comment]
not goot :-(
Do you want to take a look?

**Comment by Xenopathic** [comment]
@karlitschek I can have a poke around, but this is unfamiliar code so I might get stuff wrong :smile:
