### ISSUE TITLE
federation autocompletion

### ISSUE THREAD

**Issue by karlitschek** [owncloud/core#17888]
federation autocompletion 

Overview:
To share something with a user on a different server the Federation ID needs to be known. The Federation ID is the combination of the remote server url and the username on the server. There are different option to ‘get’ this Federation ID which work in different situation. Because of that we should have autocompletion ’plugins’ that can be implemented in apps for different architectures.

- Manual
We should make it super obvious that a user can enter the Federation ID into the sharing dialog. We should also tell the users their Federation ID on there personal page. Additionally we should make it easy for users to publish their Federation ID via social media and email. This is the basic way that always works. No plugin is needed for this.
(This was done in 8.1. Maybe needs UX review and slight polish)

- Recent
The sharing dialog should remember the last X used Federation IDs and store it internally. So if a user always shares with the same group of people they will be listed in the autocompletion dropdown.

- Contacts
If the Contacts app is enabled then users with Federation ID entries from the Contacts app should be used for autocompletion. If the user enters manually a Federation ID into the sharing dialog then a new entry in the Contacts app should be created. The user can later add the clear text name to the Federation ID in the Contacts app. 

- LDAP
It should be possible to use entries from a central LDAP server to autocomplete users that are not present in the currently used LDAP or on the current server.
Option 1: A second LDAP server is used to autocomplete this users. The Federation ID is read from a special LDAP attribute and used for the Federated sharing. 
Option 2: The same LDAP server is used to autocomplete the users but with a different LDAP login filter. So users that can’t log into the current server can still be found in the Sharing autocompletion. The Federation ID is read via a special LDAP attribute and used for Federated sharing.

- DHT
In this scenario users can be found and autocompleted in the Sharing dialog that are not on the current server or in the LDAP or Contacts app. The idea is that every user on every ownCloud in the world can publish the personal information including Name and Federation ID i a DHT that can be queried from every ownCloud.

**Comment by karlitschek** [comment]
The next step that we should implement is the LDAP part including the autocompleter plugin system. The DHT idea is something for the future.

**Comment by karlitschek** [comment]
@schiesbn @DeepDiver1975 @MTRichards @cmonteroluque @jancborchardt Feedback?

**Comment by jancborchardt** [comment]
Yup, agree as discussed in the past.

The Distributed-Hash-Table part is probably the most important one here, otherwise this will always remain some technical copy-pasting of user IDs (at least to start out).

**Comment by DeepDiver1975** [comment]
Querying the Federation ID from contacts is already in place - THX @schiesbn 

Regarding LDAP: do I understand correctly that we want to query a total different LDAP server compared to the servers which are configured in the user_ldap app?

Sounds like a can of worms thinking about the configuration nightmare we are already in with respect to user_ldap

**Comment by karlitschek** [comment]
@DeepDiver1975 I totally agree. Having to configure a second ldap is something that we only should allow if absolutely necessary. 
@bboule @felixboehm Do the current use-cases / customers require this? Or is one ldap that is replicated across sites with different login filters also ok?
Also adding @blizzz here.

**Comment by blizzz** [comment]
We can configure multiple LDAP servers since when? OC 6? However,, they are all on an equal footing. If I understand correctly, you look for an LDAP server with a specific role: only searching for federated users. At least for option A. Correct?

> The same LDAP server is used to autocomplete the users but with a different LDAP login filter. So users that can’t log into the current server can still be found in the Sharing autocompletion. The Federation ID is read via a special LDAP attribute and used for Federated sharing.

Technically, the login filter only applies for logins. What applies for search is the User Filter. Only to speak with correct terms.

Having an additional attribute to look into when search is not a problem (already possible), but it needs extra behaviour. We would need to seperate such remote users within the backend internally, e.g. not apply the internal username setting on them, but use the value from the federated cloud id attribute. As such, mails, avatars and so one should not be applied (as such, they should not be in LDAP anyway). There would not be too many changes necessary, probably.

What should be done is also to offer a reference objectClass/attribute for LDAP for Admins to extend their directory with. Ain't not a big deal either, I think.

**Comment by bboule** [comment]
Hey Guys,

So let me run through a very specific use case that we brought a user through:

They have ten offices each will have its own ownCloud, and they want to ensure the ability of users to be able to share with one another without knowing the full Server to Server User Stings.  Here is what we did:

Picked one unused field in AD this field is used to host the server/office they are running in so for example for someone in the Toronto office they populate this field with @xxx.toronto.com  this is scripted to be added to this specific field for all users at this location.  This is also added to the account generation script they use in AD.

Next we pick another used field and script a concatenate of the filed they normally search on (In this case samAccountName) and the field we used to populate their home server (@xxx.tornto.com) what you end up with is samAccountName@xxx.tornoto.com in this FINAL search filed.  

Next we simply add this felid (the concatenation of the two elements) to the search fields in the OC LDAP Wizard.  

Now what you end up with is when a user goes to search and this is set up correctly, they will search for the users sAMAccountName as they type that in what will be returned in the result set is the users proper server to server sharing name.

This is how I got this to work in this use case, and while it was some extra work for the AD Person, I was able to help by providing some powershell scripts for this.

They were able to accomplish this without a second LDAP server, just needed to use a few extra unused fields!!

Does this help at all?

Bob

**Comment by karlitschek** [comment]
O.K. I also checked the requirements and discussed with several people
I think the full lookup of an external/2nd LDAP is not needed. We should add the option to implement a plugin that for example gets the federation id from LDAP (as bob describes) or another source like user types in frank@myowncloud.org which is transformed into frank@myowncloud.org:88/owncloud (or whatever logic is needed). Basically a plugin that reads or generates the federation id somehow and passes it to the code behind the form. 
@schiesbn Do you know what I mean? does this make any sense?  :-)

**Comment by DeepDiver1975** [comment]
We decided in Berlin to postpone this

**Comment by karlitschek** [comment]
replaced with this: https://github.com/owncloud/core/issues/19566
