### ISSUE TITLE
[ownCloud 8.1] URLGenerator fails app when cache is "broken".

### ISSUE THREAD

**Issue by WaylandAce** [owncloud/core#17892]
## What I see:

blank screen
## What I suspect to see:

Missing memcache class \OC\Memcache\Redis for local cache
Is the matching PHP module installed and enabled ?"
## Steps to reproduce:

Install owncloud
Enable redis to store distributed cache
disable php-redis module.

layout.guest.php which used to generate error page has shortcut favicons, where image_path function is used. This function uses URLGenerator and last one uses cache factory, which is reason of fail.

**Comment by Xenopathic** [comment]
In 8.1 a missing memcache is considered to be a hard failure, as it is a missing component of the ownCloud installation.

Just noticed we don't actually document that though... incoming PR...

**Comment by WaylandAce** [comment]
Yes, but removing icons from template solves problem and it's very simple to see error and fix it. As option it can be different template for error page.

**Comment by Xenopathic** [comment]
Ahh, I see. So the error page generated by ownCloud in case of broken memcache is itself broken?

**Comment by WaylandAce** [comment]
Yes

**Comment by PVince81** [comment]
likely fixed in recent versions like 10.0.2 where better error handling has been added
