### ISSUE TITLE
Chunk files must NOT be indexed in file cache

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#17895]
### Steps to reproduce
1. Upload a huge file with the sync client
2. During upload, observe oc_filecache: `select * from oc_filecache where path like '%cache%';`

### Expected result
Chunks are never indexed.

### Actual result
Chunk file names temporarily appear in the file cache.

@icewind1991 this might be due to recent changes to the chunking code or was it always the case ?
I think we should prevent anything under "cache" to appear in the file cache. Should also slightly improve performance.

**Comment by PVince81** [comment]
Or alternatively we do use this information to find out how many chunks we already have ? But that would be a LIKE query...

**Comment by guruz** [comment]
> Chunk file names temporarily appear in the file cache.

btw, do they also gc in ```oc_filecache``` if a chunk of a never-completed file is ```gc()```ed ?

> Or alternatively we do use this information to find out how many chunks we already have ? But that would be a LIKE query...

FYI the complete-check is optimized by @rullzer in https://github.com/owncloud/core/pull/22602 (I can't judge if this is faster than checking via DB, I feel they should not be in DB either..)

**Comment by rullzer** [comment]
@guruz well even if they are in the db the fix in #22602 should still be faster ;)

**Comment by PVince81** [comment]
Ok, I think this is necessary in case someone uses home object store because having the file in oc_filecache will map it by fileid to object id. Closing.
