### ISSUE TITLE
Calendar broken for LDAP users

### ISSUE THREAD

**Issue by d-tamm** [owncloud/core#17905]
### Steps to reproduce
1. Log in as an LDAP user.
2. Access calendar web interface
-> timeout
3. Log off, log on as (local) admin user.
4. Access calendar web interface
-> works fine
5. Go to Admin and refresh LDAP link by changing some details and then restoring the previous setting.
6. Go to Users to trigger LDAP lookup
7. Log off, log in as LDAP user.
8. Access calendar web interface
-> now it works
9. Wait some time (1 hour?)
10. Repeat step 8 -> timeout

When getting the timeout, also CalDAV sync stops working.

### Expected behaviour
Calendar should be shown / synchronized.

### Actual behaviour
The clients (browser, Thunderbird etc) get a timeout. In the meantime, my web server (apache2) shows extremy high CPU usage. This is true for all LDAP users, and only for LDAP users. Normal users' calendars work fine all the time.
After changing LDAP settings, the calendars work fine for all users, but after some time, I get the timeout.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache2

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:**
8.1.0.8
(worked at least until 8.0)

**Updated from an older ownCloud or fresh install:**
Updated

**List of activated apps:**
Enabled:
 - calendar: 0.7.2
 - contacts: 0.4.0.0
 - external: 1.2
 - files: 1.1.9
 - files_external: 0.2.3
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - user_ldap: 0.6.1
Disabled:
 - activity
 - direct_menu
 - encryption
 - files_locking
 - files_versions
 - files_videoviewer
 - provisioning_api
 - tasks
 - templateeditor
 - user_external
 - user_webdavauth

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'occ537937d2f',
  'passwordsalt' => 'xxx',
  'trusted_domains' => 
  array ( ... ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'xxx',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'forcessl' => false,
  'theme' => '',
  'maintenance' => false,
  'mail_from_address' => 'owncloud',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'biomil.se',
  'mail_smtpsecure' => 'tls',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => true,
  'mail_smtphost' => 'send.one.com',
  'mail_smtpport' => '2525',
  'mail_smtpname' => 'owncloud@biomil.se',
  'mail_smtppassword' => 'owncloud',
  'log_rotate_size' => 10485760,
  'secret' => 'xxx',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
Only enabled, not in use.

**Are you using encryption:**
Occurs both with and without SSL

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP 

#### LDAP configuration (delete this part if not used)
+-------------------------------+------------------------------------------------------------+
| Configuration                 |                                                            |
+-------------------------------+------------------------------------------------------------+
| hasMemberOfFilterSupport      |                                                            |
| hasPagedResultSupport         |                                                            |
| homeFolderNamingRule          |                                                            |
| lastJpegPhotoLookup           | 0                                                          |
| ldapAgentName                 |                                                            |
| ldapAgentPassword             | ***                                                        |
| ldapAttributesForGroupSearch  |                                                            |
| ldapAttributesForUserSearch   |                                                            |
| ldapBackupHost                |                                                            |
| ldapBackupPort                |                                                            |
| ldapBase                      | dc=biomil,dc=se                                            |
| ldapBaseGroups                | dc=biomil,dc=se                                            |
| ldapBaseUsers                 | dc=biomil,dc=se                                            |
| ldapCacheTTL                  | 600                                                        |
| ldapConfigurationActive       | 1                                                          |
| ldapEmailAttribute            | mail                                                       |
| ldapExperiencedAdmin          | 0                                                          |
| ldapExpertUUIDGroupAttr       |                                                            |
| ldapExpertUUIDUserAttr        | uid                                                        |
| ldapExpertUsernameAttr        |                                                            |
| ldapGroupDisplayName          | cn                                                         |
| ldapGroupFilter               | (&(|(objectclass=posixGroup)))                             |
| ldapGroupFilterGroups         |                                                            |
| ldapGroupFilterMode           | 0                                                          |
| ldapGroupFilterObjectclass    | posixGroup                                                 |
| ldapGroupMemberAssocAttr      | memberUid                                                  |
| ldapHost                      | localhost                                                  |
| ldapIgnoreNamingRules         |                                                            |
| ldapLoginFilter               | (&(|(objectclass=inetOrgPerson))(|(uid=%uid)(|(cn=%uid)))) |
| ldapLoginFilterAttributes     | cn                                                         |
| ldapLoginFilterEmail          | 0                                                          |
| ldapLoginFilterMode           | 0                                                          |
| ldapLoginFilterUsername       | 1                                                          |
| ldapNestedGroups              | 0                                                          |
| ldapNoCase                    | 0                                                          |
| ldapOverrideMainServer        | 0                                                          |
| ldapPagingSize                | 500                                                        |
| ldapPort                      | 389                                                        |
| ldapQuotaAttribute            |                                                            |
| ldapQuotaDefault              |                                                            |
| ldapTLS                       | 1                                                          |
| ldapUserDisplayName           | displayname                                                |
| ldapUserFilter                | (|(objectclass=inetOrgPerson))                             |
| ldapUserFilterGroups          |                                                            |
| ldapUserFilterMode            | 0                                                          |
| ldapUserFilterObjectclass     | inetOrgPerson                                              |
| ldapUuidGroupAttribute        | auto                                                       |
| ldapUuidUserAttribute         | auto                                                       |
| turnOffCertCheck              | 0                                                          |
| useMemberOfToDetectMembership | 1                                                          |
+-------------------------------+------------------------------------------------------------+

### Client configuration
**Browser:**
Firefox, Rekonq (Ubuntu)
Thunderbird Lightning (Ubuntu)
CalDAV Sync (Android)

#### Web server error log
[Mon Jul 27 13:44:48.387263 2015] [core:notice] [pid 57443] AH00051: child pid 19194 exit signal Segmentation fault (11), possible coredump in /etc/apache2

#### ownCloud log (data/owncloud.log)
nothing here

#### Browser log
timeout

**Comment by DeepDiver1975** [comment]
please reopen in calendar repo - THX

**Comment by d-tamm** [comment]
Oh, sorry. Will do that!
