### ISSUE TITLE
Move ajax/scan.php to cron job

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#17906]
Not sure why we are triggering a background scan from the JS side with "ajax/scan.php" ?
This should probably be moved to a cron job instead.

@icewind1991 @LukasReschke @DeepDiver1975 what do you think ?

**Comment by DeepDiver1975** [comment]
AFAIK back in the days we had no background jobs/cron jobs ......

**Comment by LukasReschke** [comment]
Seconded.

**Comment by PVince81** [comment]
There is already a BackgroundScan cron job, but I'm not sure whether it serves the same purpose or properly covers this, so we need to be careful.

**Comment by DeepDiver1975** [comment]
> There is already a BackgroundScan cron job,

Hmm ... from the anitvirus app afaik - nothing for files afaik ...

**Comment by PVince81** [comment]
Okay, I misunderstood it. Actually the "backgroundScan" method is currently called by ajax/scan.php only: https://github.com/owncloud/core/blob/master/apps/files/ajax/scan.php#L55
I thought there was a cron job too...

The background scan seems to be implemented in a way that it only scans a small bunch of files/folders every time, not everything at once. That would also fit a cron job.

**Comment by PVince81** [comment]
I renamed the title: move ajax/scan.php to cron job.

**Comment by PVince81** [comment]
Moving this enhancement to 9.0.

**Comment by LukasReschke** [comment]
PR is at https://github.com/owncloud/core/pull/20545
