### ISSUE TITLE
Users are not displayed if they are deleted and created again.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#17900]
### Steps to reproduce

1. Create several users, one called user1.
2. Delete user1 of them.
3. Create user1 again.

### Expected behaviour
user1 is created and it is displayed in the list.

### Actual behaviour
user1 doesn't appear anymore. Also the list displayed is corrupted since their index are wrong, and if you creates a new user and tries to delete it, you delete user1.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.1.0","versionstring":"8.1.1 beta1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
```
Enterprise by default.

**The content of config/config.php:**

```

```


**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No



### Client configuration

**browser**
Chrome 43

**Comment by DeepDiver1975** [comment]
afaik a duplicate - we had this one already

**Comment by PVince81** [comment]
Here https://github.com/owncloud/core/issues/13589.
