### ISSUE TITLE
Share by Link unavailable for a file within a folder shared with Group

### ISSUE THREAD

**Issue by pyheme** [owncloud/core#17914]
Hi, 
I did various searches for this but can't seem to find posts for this point here or in the forum. Should there already be one, sorry for the duplicate entry. 

I'm using OC 8.0.4 on a Ubuntu install (with PHP 5.5.4 should it matter).
I have 4 internal users, all in the group "Team". 
At this point, all team members are placing files within a share folder "Company" that belongs to User1. 
User1 shared folder "Company" with group "Team".  
Files are encrypted using OC's default encryption module. The "Company" folder contains roughly 10GB of data at this point across probably 20,000+ files within 800+ different subfolders.

Today, as User1, I tried to share a file that is within a subfolder of "Company" with a client (not user of our OC platform) via Share by Link feature but could not. When clicking on Share, OC tells me "Shared with you and the group Company by User1" (while logged in as User1) and that Resharing is not allowed.

In the Admin page, under Sharing, I have:
Allow Apps to use the Share API -> Checked
Allow users to share via link -> Checked
    - Allow users to send mail notification for shared files -> Checked
Allow Resharing -> Checked
Restrict users to only share with users in their groups -> Unchecked
Allow users to send mail notification for shared files to other users -> Checked
Exclude groups from sharing -> Unchecked

Before the recent change in the encryption algorithm, I was able to do so.
Is it a bug or was this option voluntarily removed?
Moving the file to another, non-shared, folder, I am able to share it by link as before. 

I considered upgrading to 8.1 but I see that the encryption package changed again and I am hesitant to do the upgrade as, historically, everytime the encryption changed, it broke my install (the last one was no exception but I managed to properly convert everything from backups but had to unshare/reshare the folders, allowing the server to compute 3-4 hours between every change).

Thanks in advance for your help and guidance. 

Pierre

**Comment by PVince81** [comment]
I'm not aware of any changes in the sharing stuff regarding encryption.

@schiesbn

**Comment by PVince81** [comment]
@pyheme I read through your report (thanks for the many details by the way): I think this isn't related at all to encryption and could be a bug in the permissions.

So "user1" is in the group "Team" and "Company" belongs to "user1". So "user1" is at the same time owner and recipient of "Company". This sounds like https://github.com/owncloud/core/issues/15771 but is supposed to be fixed in 8.1.0 already.

Let me have a try locally.

**Comment by PVince81** [comment]
Here are my steps:

1. Setup OC 8.1.0
1. Create four users "user1", "user2", "user3", "user4"
1. Add them in a new group "team"
1. Login as "user1"
1. Create a folder "Company"
1. Share "Company" with the group "team" and leave all permissions enabled
1. Create a subdir "Company/reshare"
1. Share "Company/reshare" with link

Works for me:
![reshare-works](https://cloud.githubusercontent.com/assets/277525/8929628/3a5e4368-3527-11e5-9c79-b53ee333c2a1.png)

Now let me try upgrading from 8.0.4 with this setup.

**Comment by PVince81** [comment]
Hmmm, I setup 8.0.4, then ran the above steps except for "Share link". Then upgraded to 8.1.0. After that "Share link" for "reshare" still works.

Now again with encryption (in case that changes the permissions somehow)

**Comment by PVince81** [comment]
Still works for me.

@pyheme please check the oc_filecache entry: `select * from oc_filecache where path like '%Company%'` and the same for the subfolder. Post it here if possible, or at least the "permissions" column.

In my case where it works it looks like this:
```
MariaDB [owncloud]> select * from oc_filecache where path like '%Company%';
+--------+---------+-----------------------+----------------------------------+--------+---------+----------+----------+------+------------+---------------+-----------+------------------+---------------+-------------+
| fileid | storage | path                  | path_hash                        | parent | name    | mimetype | mimepart | size | mtime      | storage_mtime | encrypted | unencrypted_size | etag          | permissions |
+--------+---------+-----------------------+----------------------------------+--------+---------+----------+----------+------+------------+---------------+-----------+------------------+---------------+-------------+
|     46 |       3 | files/Company         | e1881eccaf680604bb62323134b5f8a8 |     40 | Company |        2 |        1 |    0 | 1438089877 |    1438089877 |         0 |                0 | 55b782953e1d9 |          31 |
|     47 |       3 | files/Company/reshare | 70bda7fcb6b368acff91b04257ae4740 |     46 | reshare |        2 |        1 |    0 | 1438089877 |    1438089877 |         0 |                0 | 55b7829538f1f |          31 |
+--------+---------+-----------------------+----------------------------------+--------+---------+----------+----------+------+------------+---------------+-----------+------------------+---------------+-------------+
```

Permissions are 31.

You can also double check this: login as "user1" click "Share" on "Company" and check that the "share" checkbox is set properly for that share.

Then one last try, get the matching share entry:
```
MariaDB [owncloud]> select * from oc_share where file_source=46;
+----+------------+------------+-----------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-------+-----------+
| id | share_type | share_with | uid_owner | parent | item_type | item_source | item_target | file_source | file_target | permissions | stime      | accepted | expiration | token | mail_send |
+----+------------+------------+-----------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-------+-----------+
|  1 |          1 | team       | user1     |   NULL | folder    | 46          | /46         |          46 | /Company    |          31 | 1438089874 |        0 | NULL       | NULL  |         0 |
|  2 |          2 | user2      | user1     |      1 | folder    | 46          | /46         |          46 | /Company    |          31 | 1438089874 |        0 | NULL       | NULL  |         0 |
|  3 |          2 | user3      | user1     |      1 | folder    | 46          | /46         |          46 | /Company    |          31 | 1438089874 |        0 | NULL       | NULL  |         0 |
|  4 |          2 | user4      | user1     |      1 | folder    | 46          | /46         |          46 | /Company    |          31 | 1438089874 |        0 | NULL       | NULL  |         0 |
+----+------------+------------+-----------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-------+-----------+
```

Replace "46" by the file id of the "Company" folder found in the previous query.

I hope this will reveal more clues :smile:

**Comment by pyheme** [comment]
Hi @PVince81, Thanks for the follow up and for the guidance.  

You are right, it is the issue #15771, somehow I just did not manage to find it before posting. 
I am still on 8.0.4 so if 8.1 corrects it, then I'll start by upgrading today and technically the problem should be resolved. 

I'll post back the query results if not. 

Thanks for your help.

Pierre

**Comment by PVince81** [comment]
@pyheme I see that this was backported and will be in OC 8.0.6 too: https://github.com/owncloud/core/pull/17158

I recommend you to wait for 8.1.1 before upgrading as 8.1.0 had some possible issues with encryption.

**Comment by PVince81** [comment]
I'll close the ticket now. Please reopen if you still see the issue in 8.0.6 or 8.1.1.
