### ISSUE TITLE
Installation: Wrong info / error state causes database credential fields to be wiped

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#17918]
1. Open the setup process
2. Choose MySQL
3. Put in your credentials.

Now if there is any error like the username already existing (for whatever reason) the database credential fields will be reset. This is quite annoying because they need to be put in again. We should preserve them.

**Comment by jancborchardt** [comment]
cc @owncloud/designers

**Comment by Kawohl** [comment]
I've tested in 8.2rc1 this is fixed.
