### ISSUE TITLE
Links to documentation in admin page of oC 8.1.1 takes you to 8.0

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#17926]
### Steps to reproduce
1. Go to admin page
2. Open a info link like these:

![screen shot 2015-07-28 at 13 03 46](https://cloud.githubusercontent.com/assets/9048796/8929902/3ad692da-3529-11e5-9392-39cf9b89bbc9.png)
 
Expected behaviour:
Documentation for 8.1 opens.

Actual behaviour:
Documentation for 8.0 opens.

**ownCloud version:**
{"installed":true,"maintenance":false,"version":"8.1.1.1","versionstring":"8.1.1 beta1","edition":"Enterprise"}

**Comment by karlitschek** [comment]
@carlaschroder @danimo What do you think?

**Comment by carlaschroder** [comment]
I believe this is an issue in the build process, see https://github.com/owncloud/core/issues/17463

**Comment by carlaschroder** [comment]
See https://github.com/owncloud/core/issues/17463#issuecomment-121251147

**Comment by DeepDiver1975** [comment]
@SergioBertolinSG is this EE of CE?

**Comment by SergioBertolinSG** [comment]
it is EE.

**Comment by DeepDiver1975** [comment]
fixed
