### ISSUE TITLE
Upgrade error from 7.0.2 to 7.0.7 from RPM repository

### ISSUE THREAD

**Issue by rmazgon** [owncloud/core#17936]
After upgrade all needed packages, the DB updater does not work via HTTP or console. The output error:
```
An exception occurred while executing 'SELECT min_value, increment_by FROM events_ID_seq':

SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "events_id_seq" does not exist
LINE 1: SELECT min_value, increment_by FROM events_ID_seq
```
The error is generated from `<installation dir>/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Schema/PostgreSqlSchemaManager.php`
```
    protected function _getPortableSequenceDefinition($sequence)
    {
        if ($sequence['schemaname'] != 'public') {
            $sequenceName = $sequence['schemaname'] . "." . $sequence['relname'];
        } else {
            $sequenceName = $sequence['relname'];
        }
        $data = $this->_conn->fetchAll('SELECT min_value, increment_by FROM ' . $sequenceName);
        return new Sequence($sequenceName, $data[0]['increment_by'], $data[0]['min_value']);
    }
```

In postgresql, that query made on a sequence (because events_id_seq is a sequence), does not work.

Environment:
 OS: Red Hat Enterprise Linux Server release 6.5 (Santiago)
 RPM Repo: isv_ownCloud_community_7.0
 Data base backend: PostgreSQL Server 9.3
 HTTP Server: Apache Web Server 2.2.X
 PHP version: 5.3.3
 *ownCLoud preview version: 7.0.2
 ownCLoud upgrade version: 7.0.7

*This version had been upgraded from ownCloud 6.0.4 without any problems.

**Comment by rmazgon** [comment]
Please, if someone could explain me what is trying to be done with the function "protected function _getPortableSequenceDefinition($sequence)" in the database upgrade execution, I could search any solution. Thanks!

**Comment by MorrisJobke** [comment]
@DeepDiver1975 doctrine DB stuff ;)

**Comment by PVince81** [comment]
@icewind1991 any idea ?

**Comment by icewind1991** [comment]
Sounds like doctrine is not detecting db changes correctly and tries to update a sequence instead of creating it, no clue why tough

**Comment by PVince81** [comment]
Are you still seeing this in recent ownCloud versions like 8.1.5 or 8.2.2 ? If yes, please reopen.
