### ISSUE TITLE
Owncloud : Fatal error: Call to a member function getSystemConfig() on a non-object in /lib/private/log.php on line 59

### ISSUE THREAD

**Issue by jordyderosa** [owncloud/core#17937]
Hello everbody ,
i've a problem whith owncloud . in log.php at line 59 there is this code:
$config = \OC::$server->getSystemConfig();
that cause fatal error beacuse of \OC::$server is null . 
I don't know why is null and where $sever should be setted by the way i've tried to reinstall a new instances of owncloud but without success. i use aruba linux hosting .

**Comment by oparoz** [comment]
Please fill in this template, so that we can better understand how the error gets triggered. Thank you

https://raw.github.com/owncloud/core/master/issue_template.md

**Comment by DeepDiver1975** [comment]
please reopen once all required information has been compiled - THX

**Comment by jordyderosa** [comment]
### Steps to reproduce
1. Go to owncloud's homepage url
2. Error will be reproduced
3.

### Expected behaviour
Should appear login page

### Actual behaviour
Appear this error:
Fatal error: Call to a member function getSystemConfig() on a non-object in xxxx.it/owncloud/lib/private/log.php on line 59 

### Server configuration
**Operating system**: Linux

**Web server:** Aruba Apache

**Database:** Mysql

**PHP version:** 5.5.25

**ownCloud version:** i've tried to installed a new owncloud instance version 8.1 and previus versions.

**Updated from an older ownCloud or fresh install:** i've tried both with the same result

**List of activated apps:** standard

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
``` i can't access to command line

**The content of config/config.php:** 
config/config.php fresh install :
empty

config/config.php backup version:
<?php
$CONFIG = array (
  'instanceid' => 'oc8dd1a4121f',
  'passwordsalt' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'trusted_domains' => 
  array (
    0 => my domain ,
  ),
  'datadirectory' => '/xxxxxxxx/xxxx/xx/owncloud/mycloud/data',
  'dbtype' => 'mysql',
  'version' => '8.1',
  'dbname' => 'Sql789086_1',
  'dbhost' => my host ip,
  'dbtableprefix' => 'oc_',
  'dbuser' => my db username,
  'dbpassword' => 'xxxxxxxxx',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'theme' => '',
  'maintenance' => false,
  'secret' => 'xxxxxxxxxxxxxxxx/x',
);  

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system --public
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:**  No external storage


**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:**  NO

On ownCloud 7+ with access to your command line run e.g.: i can't
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

On ownCloud 6 with access to your command line run e.g.: i can't
sqlite3 data/owncloud.db or mysql -u root -p owncloud
then execute:  select * from oc_appconfig where appid='user_ldap';

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query above.


this is the query result:
	appid 		configkey 			configvalue
	user_ldap 		enabled 			no
	user_ldap 		installed_version 	0.4.3
	user_ldap 		ocsid 			166061
	user_ldap 		types 			authentication

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:** Internet Explorer and Firefox

**Operating system:**

### Logs
#### Web server error log
```
Insert your webserver log here
```
[Thu Jul 30 13:36:14 2015] [error] [client 2.226.14.144] PHP Fatal error: Call to a member function getSystemConfig() on a non-object in xxxx/xx/lib/private/log.php on line 59 

#### ownCloud log (data/owncloud.log)
```
{"reqId":"VbZVkH8AAAEAAHiVfIsAAAAM","remoteAddr":"95.110.221.32","app":"PHP","message":"Undefined offset: 0 at \/web\/htdocs\/\/lib\/private\/appframework\/http\/request.php#684","level":3,"time":"2015-07-27T16:00:16+00:00"}
{"reqId":"VbZVkH8AAAEAAHiVfIsAAAAM","remoteAddr":"95.110.221.32","app":"PHP","message":"touch(): Unable to create file \/web\/htdocs\/\/data\/owncloud.log because No such file or directory at \/web\/htdocs\/\/lib\/private\/log\/owncloud.php#53","level":3,"time":"2015-07-27T16:00:17+00:00"}
{"reqId":"VbdiIH8AAAEAACrwRVgAAAAS","remoteAddr":"66.249.64.194","app":"PHP","message":"Undefined offset: 0 at \/web\/htdocs\/\/lib\/private\/appframework\/http\/request.php#684","level":3,"time":"2015-07-28T11:06:09+00:00"}
{"reqId":"VbeAIH8AAAEAADEiEuUAAACA","remoteAddr":"95.110.221.45","app":"PHP","message":"Undefined offset: 0 at \/web\/htdocs\/\/lib\/private\/appframework\/http\/request.php#684","level":3,"time":"2015-07-28T13:14:10+00:00"}
{"reqId":"VboMJH8AAAEAADsW0aYAAABa","remoteAddr":"2.226.14.144","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Could not acquire an exclusive lock on the config file \\\/web\\\/htdocs\\\/www.amministrazioniderosa.it\\\/home\\\/owncloud\\\/mycloud_old\\\/config\\\/config.php\",\"Code\":0,\"Trace\":\"#0 \\\/web\\\/htdocs\\\/www.amministrazioniderosa.it\\\/home\\\/owncloud\\\/mycloud_old\\\/lib\\\/private\\\/config.php(124): OC\\\\Config->writeData()\\n#1 \\\/web\\\/htdocs\\\/www.amministrazioniderosa.it\\\/home\\\/owncloud\\\/mycloud_old\\\/lib\\\/private\\\/util.php(1043): OC\\\\Config->setValue('instanceid', 'oc5frrxk5aiu')\\n#2 \\\/web\\\/htdocs\\\/www.amministrazioniderosa.it\\\/home\\\/owncloud\\\/mycloud_old\\\/lib\\\/base.php(442): OC_Util::getInstanceId()\\n#3 \\\/web\\\/htdocs\\\/www.amministrazioniderosa.it\\\/home\\\/owncloud\\\/mycloud_old\\\/lib\\\/base.php(594): OC::initSession()\\n#4 \\\/web\\\/htdocs\\\/www.amministrazioniderosa.it\\\/home\\\/owncloud\\\/mycloud_old\\\/lib\\\/base.php(1115): OC::init()\\n#5 \\\/web\\\/htdocs\\\/www.amministrazioniderosa.it\\\/home\\\/owncloud\\\/mycloud_old\\\/index.php(38): require_once('\\\/web\\\/htdocs\\\/www...')\\n#6 {main}\",\"File\":\"\\\/web\\\/htdocs\\\/www.amministrazioniderosa.it\\\/home\\\/owncloud\\\/mycloud_old\\\/lib\\\/private\\\/config.php\",\"Line\":252}","level":4,"time":"2015-07-30T11:36:04+00:00"}
{"reqId":"VboMJH8AAAEAADsW0aYAAABa","remoteAddr":"2.226.14.144","app":"PHP","message":"fopen(\/web\/htdocs\/_old\/config\/config.php): failed to open stream: No such file or directory at lib\/private\/config.php#191","level":3,"time":"2015-07-30T11:36:05+00:00"}
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by DeepDiver1975** [comment]
> {"reqId":"VboMJH8AAAEAADsW0aYAAABa","remoteAddr":"2.226.14.144","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Could not acquire an exclusive lock on the config file \\\/web\\\/htdocs\\\/www.amministrazioniderosa.it\\\/home\\\/owncloud\\\/mycloud_old\\\/config\\\/config.php\",\"Code\":0,\"Trace\":\"#0 \\\/web\\\/htdocs\\\/www.amministrazioniderosa.it\\\/home\\\/owncloud\\\/mycloud_old\\\/lib\\\/private\\\/config.php(124): OC\\\\Config->writeData()\\n#1 \\\/web\\\/htdocs\\\/www.amministrazioniderosa.it\\\/home\\\/owncloud\\\/mycloud_old\\\/lib\\\/private\\\/util.php(1043): OC\\\\Config->setValue('instanceid', 'oc5frrxk5aiu')\\n#2 \\\/web\\\/htdocs\\\/www.amministrazioniderosa.it\\\/home\\\/owncloud\\\/mycloud_old\\\/lib\\\/base.php(442): OC_Util::getInstanceId()\\n#3 \\\/web\\\/htdocs\\\/www.amministrazioniderosa.it\\\/home\\\/owncloud\\\/mycloud_old\\\/lib\\\/base.php(594): OC::initSession()\\n#4 \\\/web\\\/htdocs\\\/www.amministrazioniderosa.it\\\/home\\\/owncloud\\\/mycloud_old\\\/lib\\\/base.php(1115): OC::init()\\n#5 \\\/web\\\/htdocs\\\/www.amministrazioniderosa.it\\\/home\\\/owncloud\\\/mycloud_old\\\/index.php(38): require_once('\\\/web\\\/htdocs\\\/www...')\\n#6 {main}\",\"File\":\"\\\/web\\\/htdocs\\\/www.amministrazioniderosa.it\\\/home\\\/owncloud\\\/mycloud_old\\\/lib\\\/private\\\/config.php\",\"Line\":252}","level":4,"time":"2015-07-30T11:36:04+00:00"}

this is the root problem

Please double check permissions/ownership of config folder and config/config.php to match up the web server user.

**Comment by DeepDiver1975** [comment]
in addition: what is the filesystem being used where the code is hosted? Maybe something which has issue with file locks

**Comment by jordyderosa** [comment]
Technical support says that ownership it's correct. I will ask for file locks. Just 10 days ago all works correctly and support says me that they haven't changed anything on server.

**Comment by codvio** [comment]
same error occurs.

**Comment by helmo** [comment]
Had the same error, file permissions on config/config.php we the cause for me. The webserver could not read it.

From lib/private/config.php:
```php
      $filePointer = @fopen($file, 'r');
      if($file === $this->configFilePath &&
        $filePointer === false &&
        @!file_exists($this->configFilePath)) {
        // Opening the main config might not be possible, e.g. if the wrong
        // permissions are set (likely on a new installation)
        continue;
      }
```

I think that the check above could be improved. The config file did exist in my case, so the !file_exists would fail and the code would try to run flock on an invalid $filePointer.

**Comment by thinkive** [comment]
same error occurs.

**Comment by thinkive** [comment]
Fatal error: Call to a member function getSystemConfig() on null in ................/owncloud/lib/private/log.php on line 59

**Comment by znsstudio** [comment]
Same error on Amazon EC2

**Comment by PVince81** [comment]
Can you guys all provide logs ? Or are the log entries 100% identical to the original report ?

So far this isn't enough information to be able to fix anything.

**Comment by karyon** [comment]
i had this error when i messed with the ownership of owncloud's files and fixed it with `chown www-data -R /var/www/owncloud`.

**Comment by PVince81** [comment]
Seems to be environment issues. If message still misleading in 10.0.4, please reopen.
