### ISSUE TITLE
Issue when activate "LDAP user and group backend"

### ISSUE THREAD

**Issue by Antjac** [owncloud/core#17939]
### Expected behaviour
I'm trying to activate "LDAP user and group backend" module from a fresh installation of OC.
Same error after deleting the table "DROP TABLE oc_ldap_user_mapping;"

### Actual behaviour
An exception occurred while executing 'CREATE TABLE `oc_ldap_user_mapping` (`ldap_dn` VARCHAR(255) DEFAULT '' NOT NULL, `owncloud_name` VARCHAR(255) DEFAULT '' NOT NULL, `directory_uuid` VARCHAR(255) DEFAULT '' NOT NULL, UNIQUE INDEX ldap_dn_users (`ldap_dn`), PRIMARY KEY(`owncloud_name`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_ldap_user_mapping' already exists

### Server configuration
**Operating system**: Debian GNU/LINUX

**Web server:** 2.4.10-10

**Database:** MySQL 5.5.43

**PHP version:** 5.6.7

**ownCloud version:** 8.1

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no.

```

#### ownCloud log (data/owncloud.log)
```
An exception occurred while executing 'CREATE TABLE `oc_ldap_user_mapping` (`ldap_dn` VARCHAR(255) DEFAULT '' NOT NULL, `owncloud_name` VARCHAR(255) DEFAULT '' NOT NULL, `directory_uuid` VARCHAR(255) DEFAULT '' NOT NULL, UNIQUE INDEX ldap_dn_users (`ldap_dn`), PRIMARY KEY(`owncloud_name`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_ldap_user_mapping' already exists
```

**Comment by karlitschek** [comment]
@blizzz any idea?

**Comment by blizzz** [comment]
Did you delete from the correct DB?

Does it happen for other apps as well?

**Comment by Antjac** [comment]
Yep, I deleted from the owncloud db.

I've the same issue with "External user support 0.4" 
An exception occurred while executing 'CREATE TABLE `oc_users_external` (`backend` VARCHAR(128) DEFAULT '' NOT NULL, `uid` VARCHAR(64) DEFAULT '' NOT NULL, `displayname` VARCHAR(64) DEFAULT NULL, PRIMARY KEY(`uid`, `backend`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_users_external' already exists

But no error with  External storage support 0.2.3 or  External Sites 1.2

**Comment by blizzz** [comment]
@Antjac how did you install?

@DeepDiver1975 did you hear or see anything similar? Maybe related to https://github.com/owncloud/core/issues/11047

**Comment by Antjac** [comment]
By using the debian package:
echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/community/Debian_8.0/ /' >> /etc/apt/sources.list.d/owncloud.list 
apt-get update
apt-get install owncloud

**Comment by Antjac** [comment]
Any idea ?

**Comment by blizzz** [comment]
Could you setup xdebug and retry, so have a backtrace?

**Comment by Antjac** [comment]
I tried to increase the rights of the user of the database and rename tables and it's ok now... I can't explain why....

**Comment by blizzz** [comment]
OK, glad it works now for you. Strange error message for insufficient privileges.
