### ISSUE TITLE
Add alternative "download all files as zip" format like .tar

### ISSUE THREAD

**Issue by Zauberfisch** [owncloud/core#17930]
given that there currently is no working zip download for mac users, and from what I understand a fix is not happening any time soon due to the complexity of the issue, perhaps a temporary solution for #10001 would be to offer the "download all files" as both, zip and tar. 
I have just tested tar downloads on mac and it is supported natively (successfully tested: .tar, .tar.gz and .tar.bz2).
In fact, as a Linux user I would generally appreciate the availability of a .tar download, given that not all distributions ship with unzip pre installed.

Interface wise it would just be an additional button. (Optionally, with a hint that .zip is recommended for windows and .tar for mac and linux). For example:
![files](https://cloud.githubusercontent.com/assets/186158/8931377/5ecd9ffc-3525-11e5-81ca-e073b3ea7c5a.png)
![shared](https://cloud.githubusercontent.com/assets/186158/8931378/60074e90-3525-11e5-9a99-fa838b487b88.png)

From a technological point of view, I haven't really looked into tar yet. I have only ever used it in its basics for handling archives. But given how you can use it with pipes, I assume it is capable of streaming files.

PS: I would have posted this as a comment on #10001, but that issues is locked for non team members.

**Comment by DeepDiver1975** [comment]
might help with respect to this: https://github.com/barracudanetworks/ArchiveStream-php

This repo holds a zip and a tar stream combined with a factory creating tar of zip depending on the platform of the user agent.

**Comment by Zauberfisch** [comment]
I am not sure am I am fan of doing it depending on the platform.
Guessing what the users system is can go wrong to easily.

I think highlighting one of the options depending on the system is a good idea to help novice users decide which button to click. But an informed user should always have the option to choose the format if we already provide different formats.

**Comment by PVince81** [comment]
@Zauberfisch I'm pretty sure designers won't be happy about the extra button (CC @jancborchardt)

Also the case you proposed is only for the public link.

There is another case to be covered when you are in the regular files app and select a bunch of files: the file list header will contain a "Download" link. As per your approach we'd need a second download link there too.

And also the "Download" link for folders within the file list would need two links too (or a dropdown with both entries).

Well, a dropdown could make the UI look less cluttered but I'm not sure whether it's the best solution.

**Comment by PVince81** [comment]
Still, nice try :wink:

**Comment by Zauberfisch** [comment]
yeah, I figured as much, and have no expectations that this will be adopted. It was just a mockup to make sure everyone understands what I mean ;)

**Comment by jancborchardt** [comment]
I agree with @DeepDiver1975 that the best solution here is to check for the operating system and use the according format. We’ll definitely not have 2 buttons, and the majority of people don’t really care about the archive format as long as it simply works.

**Comment by PVince81** [comment]
Another problem with detecting the OS is that some people might download the file then attach it to an email. If you do so from Linux and send an email to a Windows person, that person will get a tar file.
Well, maybe not the most common use case though... the goal of zip/tar download is rather designed to download then extract directly.

**Comment by jancborchardt** [comment]
@PVince81 well, we can’t really take care of everything. Here the main problem is that the zips generated don’t work with OS X, and that’s what we should solve.

**Comment by jancborchardt** [comment]
(And yeah – zips are basically just an intermediate solution. Really the folder should be downloaded as-is because no one cares about unzipping. The only advantage of course is faster download because of compression.)

**Comment by PVince81** [comment]
yeah... maybe one day browsers will support folder downloads.

**Comment by DeepDiver1975** [comment]
> The only advantage of course is faster download because of compression.

Which is a false assumption - zip streamer does not compress.
It's just like tar - only bundle things together

**Comment by Zauberfisch** [comment]
@jancborchardt I disagree. Yes, solving the download thing for mac is important. But I think offering an zip alternative to users that don't have unzip installed is important too.

**Comment by DeepDiver1975** [comment]
> But I think offering an zip alternative to users that don't have unzip installed is important too.

which environment would that be?
