### ISSUE TITLE
Changed Instance URL, can't login anymore except Admin

### ISSUE THREAD

**Issue by christiandreher** [owncloud/core#17941]
Hey folks.
I recently decided to move my owncloud instance from one layer up in the subdomains (from x.y.z.tld to x.z.tld).
I applied the following changes: 
In the config.php, i changed following parameters to match the new domain:
`'trusted_domains'`, `'overwrite.cli.url'`, `'mail_domain'`. Also I updated Apache for the new URL.
After I made the changes, I called the new URL and owncloud showed up like expected. I then tried to login with my user-account, but without any error message, just a box appeared with "forgot your password? reset it!". There is nothing unusual when I check the developer console in chrome. Now the weird thing: I have no problem with logging in with the admin account. Here is what the error log says: `Warning | core | Login failed: 'Chris' (Remote IP: 'xyz.xyz.xyz.xyz', X-Forwarded-For: '') | 2015-07-28T22:40:15+00:00` (ip is mine and not blacklisted by fail2ban or so)
Here are some more information:

 * According to config.php, I am running owncloud version `8.0.4.2`.
 * I am using encryption. (without the possibility to recover it)
 * I am using SSL and forcing it
 * I tried deleting cache/cookies everything
 * I am 100% sure what my password is, since I used it a lot lately and I can check it up in my stored passwords in chrome for my old URL
 * It worked seconds before I made the changes; It was not a previous update or anything.

Since my admin account does not have any files in his storage, but my user does, I can just assume that the installation URL is somehow hashed into the encryption key or something? Can you confirm this? Or do you have any other explanation for this?

I would be glad if you could help me with it. I am using owncloud just for myself, so I am not in a hurry or anything and I have backups of all data. I just don't want to reset my password and reupload 20GB of data :(

If you need any further information, please let me know, I will happily provide anything. I already tried to give as much info as possible, but well, I am sure I forgot about something...

**Comment by karlitschek** [comment]
I'm sorry to hear about your problem. I'm actually not sure if this is an ownCloud bug. Could you ask this question at the ownCloud forum at forum.owncloud.org? Thanks a lot.

**Comment by christiandreher** [comment]
Okay thank you :) I opened the thread right here: https://forum.owncloud.org/viewtopic.php?f=31&t=29552
(Mentioning it here, so maybe if someone has a similar problem and stumbles upon this in the future, he doesn't have to search for it)
