### ISSUE TITLE
"New file from Link" is missing after upgrade to 8.1

### ISSUE THREAD

**Issue by TheReal1604** [owncloud/core#17944]
Hi Guys,

after upgrading my owncloud installation from 8.0 to 8.1 the option "File from Link" in the "new" menu is missing.

Anyone some ideas on this? Is that by design? can not find something on this problem..
![2015-07-29 10_19_13-dateien - owncloud](https://cloud.githubusercontent.com/assets/5877910/8952895/568e0c9e-35db-11e5-80f7-aa6874191ac4.jpg)

Greetz
TheReal

**Comment by LukasReschke** [comment]
https://statuscode.ch/2015/05/security-and-owncloud-8.1/#from-link-download-functionality-has-been-removed

**Comment by RealRancor** [comment]
Even documented in the release notes:

https://doc.owncloud.org/server/8.1/admin_manual/release_notes.html
