### ISSUE TITLE
Federated sharing between 8.1.1 and 7.0.8 is not possible.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#17955]
### Steps to reproduce

Having server7 being an oC server v7.0.8 and server81 being an oC server v8.1.1
1. Federate share a folder from admin user in  server81 to admin user in server7
1. Federate share a folder from admin user in  server7 to admin user in server81

### Expected behaviour
Folders are shared.

### Actual behaviour
It is not allowed in both directions.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.1.0","versionstring":"8.1.1 beta1","edition":""}
and
{"installed":"true","version":"7.0.8.0","versionstring":"7.0.8 beta1","edition":"enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default ones.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

### Client configuration

**browser**
Chrome 43

**Comment by karlitschek** [comment]
@schiesbn

**Comment by schiesbn** [comment]
Federated sharing over the share dialog was implemented in oC8. So you can't share this way from oC8.1 to oC7. The only way to share from oC8.1 to oC7 is with a public link share

**Comment by schiesbn** [comment]
@SergioBertolinSG  sharing with a public link and the "add to your ownCloud" button should work in both direction, can you verify it? Thanks!

**Comment by SergioBertolinSG** [comment]
Works fine, and LDAP users shows display name instead of the LDAP ui. 

Please @carlaschroder Have this in mind for documentation, federated sharing can only be used between servers >=8.0 . Involving 7 servers requires to share using public shares, which is a different way to do it.

**Comment by carlaschroder** [comment]
docs updated https://github.com/owncloud/documentation/issues/1377

**Comment by SergioBertolinSG** [comment]
Great, thanks.
