### ISSUE TITLE
Sharing doesn't work

### ISSUE THREAD

**Issue by OTt8** [owncloud/core#17952]
Hi,
i use owncloud 8.0.4 stable and i get this error: undefined is not an object (evaluating 'OC.Share.droppedDown') while clicking on Share button on the folders i want to share.

I've tried different browsers ( Chrome Safari Firefox) but it didn't work.

Thanks

**Comment by PVince81** [comment]
Please use the issue template https://raw.githubusercontent.com/owncloud/core/master/issue_template.md to provide more info about your setup.

Also important is whether you upgraded from an older version and what update method did you use (updater app, distro packages or manually extracting the tarball)

**Comment by OTt8** [comment]
### Steps to reproduce

1. Login into my owncloud with Admin user
2. click on share button on one my folder
3. nothing happen

### Expected behaviour
should appear the sharing menu

### Actual behaviour
nothing appear

### Server configuration
**Operating system**: 
Centos 6.6

**Web server:** 
tried with apache and nginx

**Database:** 
MYSQL 5.5.44-cll-lve MySQL Community Server

**PHP version:** 
PHP 5.4.43

**ownCloud version:** 
8.0.4 stable

**Updated from an older ownCloud or fresh install: 
no , it's a fresh install

**List of activated apps:**  

Server-side Encryption 0.7.1, Share Files 0.6.1, Storage Charts 2 Application 2.6.0

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder 


 The posix extensions are required - see http://php.net/manual/en/book.posix.php
```

**The content of config/config.php:**  

<?php
$CONFIG = array (
  'instanceid' => 'ocx0g9hy5nnm',
  'passwordsalt' => '********',
  'secret' => '********',
  'trusted_domains' =>
  array (
    0 => 'pressarea.sellesanmarco.it',
  ),
  'datadirectory' => '/var/www/vhosts/pressarea.sellesanmarco.it/httpdocs/data',
  'overwrite.cli.url' => 'http://pressarea.sellesanmarco.it',
  'dbtype' => 'mysql',
  'version' => '8.0.4.2',
  'dbname' => 'ssm_pressarea',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'ssm',
  'dbpassword' => '******',
  'installed' => true,
  'theme' => 'ssm',
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  "default_language" => "en",
);

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system --public
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no 

YES

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...


### Client configuration
**Browser:** Chrome Versione 44.0.2403.107 (64-bit) MAC

**Operating system:** MAC OSX 10.10.4

### Logs
#### Web server error log

NO ERROR
```
Insert your webserver log here

```

#### ownCloud log (data/owncloud.log)

{"reqId":"8e3001d6e16bbd17ad0fc0fea689ef6b","remoteAddr":"********","app":"core","message":"Invalid OCS content returned for app 166038","level":4,"time":"2015-07-29T13:35:13+00:00"}
{"reqId":"8e3001d6e16bbd17ad0fc0fea689ef6b","remoteAddr":"********","app":"core","message":"Invalid OCS content returned for app 166051","level":4,"time":"2015-07-29T13:35:13+00:00"}
{"reqId":"8e3001d6e16bbd17ad0fc0fea689ef6b","remoteAddr":"********","app":"core","message":"Invalid OCS content returned for app 166054","level":4,"time":"2015-07-29T13:35:13+00:00"}
{"reqId":"8e3001d6e16bbd17ad0fc0fea689ef6b","remoteAddr":"********","app":"core","message":"Invalid OCS content returned for app 166059","level":4,"time":"2015-07-29T13:35:13+00:00"}
{"reqId":"8e3001d6e16bbd17ad0fc0fea689ef6b","remoteAddr":"********","app":"core","message":"Invalid OCS content returned for app 166055","level":4,"time":"2015-07-29T13:35:14+00:00"}
{"reqId":"8e3001d6e16bbd17ad0fc0fea689ef6b","remoteAddr":"********","app":"core","message":"Invalid OCS content returned for app 166053","level":4,"time":"2015-07-29T13:35:14+00:00"}
{"reqId":"8e3001d6e16bbd17ad0fc0fea689ef6b","remoteAddr":"********","app":"core","message":"Invalid OCS content returned for app 166050","level":4,"time":"2015-07-29T13:35:14+00:00"}
{"reqId":"8e3001d6e16bbd17ad0fc0fea689ef6b","remoteAddr":"********","app":"core","message":"Invalid OCS content returned for app 166052","level":4,"time":"2015-07-29T13:35:14+00:00"}
{"reqId":"8e3001d6e16bbd17ad0fc0fea689ef6b","remoteAddr":"********","app":"core","message":"Invalid OCS content returned for app 166047","level":4,"time":"2015-07-29T13:35:14+00:00"}
{"reqId":"8e3001d6e16bbd17ad0fc0fea689ef6b","remoteAddr":"********","app":"core","message":"Invalid OCS content returned for app 166056","level":4,"time":"2015-07-29T13:35:15+00:00"}
```
Insert your ownCloud log here
```

#### Browser log

Uncaught TypeError: Cannot read property 'loadIcons' of undefined
share.js:107 Uncaught TypeError: Cannot read property 'droppedDown' of undefined
share.js?v=eeeec757a7fca81898221a9e219f9f76:107 Uncaught TypeError: Cannot read property 'droppedDown' of undefined

```
Insert your browser log here, this could for example include:

Uncaught TypeError: Cannot read property 'loadIcons' of undefined
share.js:107 Uncaught TypeError: Cannot read property 'droppedDown' of undefined
share.js?v=eeeec757a7fca81898221a9e219f9f76:107 Uncaught TypeError: Cannot read property 'droppedDown' of undefined

**Comment by PVince81** [comment]
Thanks for the details.

Did you change any settings related to sharing on the "Admin" page ?
Did you disable the "Share files" app ?

It looks like for some strange reason your OC instance didn't load the file core/js/share.js

**Comment by OTt8** [comment]
i've disabled share files app, but re-enabled the problems remain.
I've a demo area , without any style editing, and there is the same problem.

I think is a problem with "new browsers"

**Comment by PVince81** [comment]
I have Chrome 43 here and it works.
If you think it's related to Chrome 44, can you have a try with Firefox instead ? Even Safari should work.

**Comment by OTt8** [comment]
Solved.

Enabling the plugin it isn't enough. In the admin panel, under Sharing, you've to flag  Allow apps to use the Share API. Without that it doesn't work.

Thanks a lot anyway.
