### ISSUE TITLE
[Stable 8.1] [Debian Server] search bug on mobil device (Android)

### ISSUE THREAD

**Issue by srt10coupe** [owncloud/core#17967]
when i'm on the search in files, open the keyboard. But the keyboard and search will be closed immediately.

it is not possible for me to enter something and hit enter to press.

This strange behavior is however only the tab 'Files'.

In the tab 'Apps' can i run the search normally.

**Comment by MorrisJobke** [comment]
cc @jancborchardt @butonic

**Comment by jancborchardt** [comment]
I guess this might be related to https://github.com/owncloud/core/issues/15163 »Resizing the window makes search results vanish«. cc @oparoz 

@butonic @DeepDiver1975 setting sev to medium because this makes search useless on mobile.

**Comment by Arvidas** [comment]
Try: in apps\files\js\app.js add
$(window).resize(function(){
	$("#searchbox").active();
});

**Comment by MorrisJobke** [comment]
maybe @PVince81 is currently in the mood to fix this :D

**Comment by jancborchardt** [comment]
@Arvidas any serious fixes are very welcome in the form of pull requests. ;)

**Comment by tombou** [comment]
Got the same issue with 8.2.2 and not just on Android devices. On Blackberry using the default web browser and in iOS with Chrome. iOS with safari actually works well.

**Comment by michaelstingl** [comment]
@MorrisJobke What is the status here?

00005171

**Comment by MorrisJobke** [comment]
> @MorrisJobke What is the status here?

Still an issue.

**Comment by michaelstingl** [comment]
@PVince81 Who can help here? /cc @cmonteroluque

**Comment by PVince81** [comment]
We already merged a fix which might be suitable and needs backport: https://github.com/owncloud/core/pull/24682

**Comment by michaelstingl** [comment]
@PVince81 In my specific case, backport to 8.2 would be enough.
