### ISSUE TITLE
LDAP: when sanitizing, also trim dn

### ISSUE THREAD

**Issue by blizzz** [owncloud/core#17964]
It may happen that when configuring an LDAP connection, by accident a white space is added to the base DN. This will result in not working LDAP logins, because the check on whether the user belongs to a configured base DN will fail, as the user will not have that whitespace.

**Comment by blizzz** [comment]
empty newlines are also exciting…

**Comment by davitol** [comment]
Cannot reproduce #17964 in ownCloud Enterprise Edition 8.2 beta1 (daily) Build:2015-10-05T03:08:46+00:00 2ffb1c2135d80ac82f62c2bd403fe452e2c4e51d. It works for me before the fix. :flushed:

white space should be add to the base DN in a specific place?

**Comment by blizzz** [comment]
> white space should be add to the base DN in a specific place?

At the front or at the end

**Comment by davitol** [comment]
@blizzz  I've tried this way with today's daily version mentioned in the previous comment and as i told before I could not be able to reproduce it.

**Comment by blizzz** [comment]
@davitol on existing configs, change the Base User Tree in Advanced tab. https://doc.owncloud.org/server/8.1/admin_manual/configuration_user/user_auth_ldap.html#directory-settings

**Comment by davitol** [comment]
@blizzz Got it, thx. The issue is solved with the fix :+1:
