### ISSUE TITLE
[7.0.6] unable to rename, file is not writable

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#17962]
### Steps to reproduce
It appears many times in the log:
{"app":"core","message":"unable to rename, file is not writable : fXXXXXX","level":3,"time":"2015-07-07T21:23:09+02:00"}

### Expected behavior
No errors in the log

### Actual behavior
some errors appears in log

### Server configuration
**Operating system**:
Webserver: Red Hat Enterprise Linux Server release 7.1 (Maipo)
Databaseserver: Red Hat Enterprise Linux Server release 6.6 (Santiago)

**Web server:**
Apache/2.4.6 (Red Hat Enterprise Linux)

**Database:**
mysql  Ver 14.14 Distrib 5.1.73, for redhat-linux-gnu (x86_64) using readline 5.1

**PHP version:**
PHP 5.4.16 (cli) (built: Jun 10 2015 04:34:17)

**ownCloud version:** (see ownCloud admin page)
7.0.6

**Updated from an older ownCloud or fresh install:**
4.5 -> 5.0.9 -> 5.0.10 -> 5.0.11 -> 5.0.12 -> 5.0.13 -> 6.0.3 -> 6.0.4 -> 6.0.5 -> 6.0.6 -> 6.0.8 -> 7.0.6

**Enabled Apps**
```
 - enterprise_key
 - files
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - user_ldap
```

**The content of config/config.php:**

```
    "config": {
        "datadirectory": "\/mnt\/XXXXSERVER_NAME_data\/data",
        "dbtype": "mysql",
        "version": "7.0.6.2",
        "installedat": "1336391237.9587",
        "lastupdatedat": "1337968446.9932",
        "dbname": "ownCloudDB1",
        "dbhost": "SERVER_NAMEdb.DOMAIN_NAME",
        "dbtableprefix": "oc_",
        "dbuser": "XXXXXXXX",
        "dbpassword": "xxxx Value is set but was removed by reporting app for security reasons xxxx",
        "installed": true,
        "loglevel": "4",
        "ldapIgnoreNamingRules": false,
        "instanceid": "508fc14d93fa7",
        "maintenance": false,
        "updatechecker": false,
        "theme": "SERVER_NAME",
        "enable_avatars": false,
        "forcessl": true,
        "trashbin_auto_expire": true,
        "trashbin_retention_obligation": 6,
        "trusted_domains": [
            "SERVER_NAME07.DOMAIN_NAME",
            "SERVER_NAME.DOMAIN_NAME",
            "SERVER_NAME08.DOMAIN_NAME",
            "SERVER_NAME09.DOMAIN_NAME",
            "SERVER_NAMEt01.DOMAIN_NAME",
            "SERVER_NAME02.DOMAIN_NAME",
            "SERVER_NAME03.DOMAIN_NAME",
            "SERVER_NAME04.DOMAIN_NAME",
            "SERVER_NAME05.DOMAIN_NAME",
            "SERVER_NAME06.DOMAIN_NAME"
        ],
        "memcached_servers": [
            [
                "SERVER_NAME-memcached.DOMAIN_NAME",
                11211
            ]
        ],
        "license-key": "xxxxxxxxxxx",
        "appstoreenabled": false,
        "has_internet_connection": false,
        "supportedDatabases": [
            "mysql",
            "pgsql",
            "oci",
            "mssql"
        ],
        "secret": "xxxxxxxxxxxxxxx",
        "share_folder": "\/Shared",
        "logtimezone": "Europe\/MYHOME",
        "asset-pipeline.enabled": "true"
    },
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
NFS

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Open-LDAP

**LDAP configuration**
No needed for this case

### Logs:
Full log in S3-ownCloud\Shared\owncloud\support\github-issues\core\17962\owncloud.log

@MorrisJobke

00002588

**Comment by cdamken** [comment]
@MorrisJobke  Who can help?

**Comment by MorrisJobke** [comment]
A weird thing is that ~ 400 log lines are related to `files_versions` and a file name like this `files_versions/abc.v`. They are all missing the time part of the version file name.

@PVince81 @schiesbn Have you ever seen a versioned file without the time info?

**Comment by MorrisJobke** [comment]
except the above mentioned log lines, there are 4 other log lines present:

three with:
```
unable to rename, file is not writable : files/path.extension.ocTransferId3764822684.part
```

And one with

```
unable to rename, file is not writable : files_versions/path.vSOMEBRANDINGSTRING
```

**Comment by PVince81** [comment]
The last time I saw something as weird as this was with a race condition with encryption and trashbin.

I suspect there is something similar happening here but with versions.

**Comment by PVince81** [comment]
@cdamken is ownCloud still usable, or is some functionality broken due to this error ? For example overwriting files ?

**Comment by PVince81** [comment]
Ok let's have a look at the source code of 7.0.6 and guess what code paths could lead to empty timestamps.

**Comment by PVince81** [comment]
Looking at the code, this is what I could infer so far:
- the error message is from here https://github.com/owncloud/core/blob/v7.0.6/lib/private/files/storage/local.php#L177 so the file name shows in the log message is the source file
- the place where the versions app calls rename: https://github.com/owncloud/core/blob/v7.0.6/apps/files_versions/lib/versions.php#L235
- there are other places related to restoring files, but since the message happens often, I'll assume that it is caused by renaming/moving a file which has several versions (rolling back versions is unlikely to happen that often )

**Comment by PVince81** [comment]
So now the question is why `$v['version']` is not defined.

The version list is obtained from `getVersions` here: https://github.com/owncloud/core/blob/v7.0.6/apps/files_versions/lib/versions.php#L323

Now as you can see, the `$timestamp` is somehow extracted from the file extension.

Interestingly, if you look at the file names in the error messages, they all seem to have no extension.
For example: "04_Unix.v", "data.v", "silva.v".

So let's do some local testing and find out how the versions app behaves for files that have no extension.

**Comment by PVince81** [comment]
I did some local tests but don't see any problems with files that have no extension. They produce valid versions and can be moved between folders without problems.

There is also a chance that an older versions bug produced invalid file, lost files or missed version files, so when someone tries to move a file, the matching versions aren't found.
Let's see if we can reproduce that.

**Comment by PVince81** [comment]
I tried purposefully deleting versions from data/$user/files_versions or renaming them to "file.v" but it didn't produce the error message.

Looking at most of the paths in the log file I almost have the feeling that these were directories, not files. But the versions app doesn't create any ".v" folders. It just creates regular folders and puts the versions of the files inside into that folder. So a file "$user/files/sub/test.txt" has its versions in "$user/files/sub/test.txt.v1234", ""$user/files/sub/test.txt.v1235", etc.

**Comment by PVince81** [comment]
Hmm, another interesting case (I changed the names):
```
{"app":"core","message":"unable to rename, file is not writable : files_versions\/sub1\/sub2\/something.v","level":3,"time":"2015-07-12T13:01:41+02:00"}
{"app":"core","message":"unable to rename, file is not writable : files_versions\/sub1\/sub2.v","level":3,"time":"2015-07-12T13:15:36+02:00"}
```
These two entries were appearing in that order. This means that "sub2" might be a folder, and "sub2.v" a tentative to access the versions of that folder as if it was a file ?!

**Comment by PVince81** [comment]
I think I got something:

1. Create a folder "sub"
1. Create another folder "sub2"
1. Create a text file as "sub/test.txt"
1. Edit the file and save several times to create versions
1. Move "sub" into "sub2"

```
{"reqId":"55d34dd12bb4c","app":"PHP","message":"Undefined index: extension at \/srv\/www\/htdocs\/owncloud\/apps\/files_versions\/lib\/versions.php#320","level":3,"time":"2015-08-18T15:22:57+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files\/ajax\/move.php"}
{"reqId":"55d34dd12bb4c","app":"core","message":"unable to rename, file is not writable : files_versions\/sub.v","level":3,"time":"2015-08-18T15:22:57+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files\/ajax\/move.php"}
```

Here we go. :smile:

**Comment by PVince81** [comment]
This happens when moving folders which have versions inside.

The code is taking the wrong code path when moving folders and only moves the contents, not the actual directory. It seems to break the versions too as the association of folder to version doesn't match any more.

The reason why it takes the wrong code path is because here https://github.com/owncloud/core/blob/v7.0.6/apps/files_versions/lib/versions.php#L228 at the time where it checks whether the source path is a directory, the directory was **already** moved, so the check fails and it goes into the else clause.

Now this sounds familiar and is likely to be fixed in OC 8, let's have a look...

**Comment by PVince81** [comment]
This works properly in OC 8.0.6
It was fixed through https://github.com/owncloud/core/pull/16369, original PR https://github.com/owncloud/core/pull/15881.

There was no original ticket as this was fixed as part of something else.

**Comment by cdamken** [comment]
@PVince81  Thanks a lot!
>This works properly in OC 8.0.6

The solution is upgrade, is that right?

**Comment by PVince81** [comment]
Yes :smile:

**Comment by cdamken** [comment]
@PVince81  Perfect!, then I suppose we can close until the upgrade and if the problem appears again, then I reopen it. Thanks a lot!
