### ISSUE TITLE
LDAP with two web servers -> Authentication failed popups on User Interface

### ISSUE THREAD

**Issue by PhilJung** [owncloud/core#17979]
I have 2 web servers with a front haproxy to distribute load on a round robin way (no session persistance). When I go on login screen, I type login and password, validate. The main user interface is displayed. But, several times, a yellow window is displayed on top of screen with "Authentication failed". 

My bet is that authentication is ok on one server but not on the other one.

My configuration is two Apache (2.2) based web servers with OC 8.1.0.8, Centos 6. PHP 5.4.26, php-pecl-apcu-4.0.7-2.el6.remi.5.4.x86_64, php-pecl-memcache-3.0.8-2.el6.remi.5.4.x86_64

In php, sessions are managed by

```
extension=memcache.so
session.save_handler=memcache
session.save_path="udp://172.X.X.X:11211?persistent=0&weight=1&timeout=1&retry_interval=15"
```

config.php:

```
<?php
$CONFIG = array (
  'instanceid' => 'bla',
  'version' => '8.1.0.8',
  'installed' => true,
  'adminlogin' => 'admin',
  'adminpass' => 'bla',
  'dbtype' => 'mysql',
  'dbname' => 'owncloud',
  'dbuser' => 'owncloud',
  'dbpassword' => 'owncloud',
  'dbhost' => '172.X.X.X:4040',
  'dbtableprefix' => 'oc_',
  'passwordsalt' => 'bla',
  'forcessl' => false,
  'blacklisted_files' => 
  array (
    0 => '.htaccess',
  ),
  'overwritehost' => '',
  'overwriteprotocol' => '',
  'overwritewebroot' => '',
  'overwritecondaddr' => '',
  'proxy' => '',
  'proxyuserpwd' => '',
  'trusted_domains' => 
  array (
    0 => '10.X.X.X',
    1 => 'nuage',
  ),
  'theme' => '',
  'default_language' => 'fr',
  '3rdpartyroot' => '',
  '3rdpartyurl' => '',
  'defaultapp' => 'files',
  'knowledgebaseenabled' => true,
  'appstoreenabled' => false,
  'appstoreurl' => 'https://api.owncloud.com/v1',
  'mail_domain' => 'X.fr',
  'mail_from_address' => 'owncloud',
  'mail_smtpdebug' => false,
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => '10.X.X.X',
  'mail_smtpport' => 25,
  'mail_smtptimeout' => 10,
  'mail_smtpsecure' => '',
  'mail_smtpauth' => false,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpname' => '',
  'mail_smtppassword' => '',
  'trashbin_retention_obligation' => 30,
  'trashbin_auto_expire' => true,
  'allow_user_to_change_display_name' => true,
  'appcodechecker' => true,
  'updatechecker' => false,
  'has_internet_connection' => false,
  'check_for_working_webdav' => true,
  'check_for_working_htaccess' => true,
  'log_type' => 'owncloud',
  'logfile' => '/var/log/owncloud/owncloud.log',
  'loglevel' => 2,
  'logdateformat' => 'Y-m-d H:i:s',
  'logtimezone' => 'Europe/Paris',
  'log_query' => false,
  'cron_log' => true,
  'log_rotate_size' => false,
  'remember_login_cookie_lifetime' => 1296000,
  'session_lifetime' => 86400,
  'session_keepalive' => true,
  'custom_csp_policy' => 'default-src \'self\'; script-src \'self\' \'unsafe-eval\'; style-src \'self\' \'unsafe-inline\'; frame-src *; img-src *; font-src \'self\' data:; media-src *',
  'xframe_restriction' => true,
  'datadirectory' => '/mnt/glustervolume/ownclouddata',
  'maintenance' => false,
  'customclient_desktop' => 'https://nuage/sync-clients/index.html',
  'customclient_android' => '',
  'customclient_ios' => '',
  'enable_previews' => true,
  'preview_max_x' => NULL,
  'preview_max_y' => NULL,
  'preview_max_scale_factor' => 10,
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'preview_office_cl_parameters' => '',
  'enable_avatars' => true,
  'openssl' => 
  array (
  ),
  'cipher' => 'AES-256-CFB',
  'singleuser' => false,
  'asset-pipeline.enabled' => false,
  'mount_file' => '',
  'cache_path' => '',
  'quota_include_external_storage' => false,
  'filesystem_check_changes' => 1,
  'filesystem_cache_readonly' => false,
  'share_folder' => '/',
  'ldapIgnoreNamingRules' => false,
  'secret' => 'bla',
  'memcache.local' => '\OC\Memcache\APCu',
);

```

**Comment by PhilJung** [comment]
| cleanUpJobOffset: 12200
| enabled: yes
| has_memberof_filter_support: 0
| home_folder_naming_rule: 
| installed_version: 0.6.1
| last_jpegPhoto_lookup: 0
| ldap_agent_password:  XXXXXX
| ldap_attributes_for_group_search: 
| ldap_attributes_for_user_search:  
| ldap_backup_host:
| ldap_backup_port: 
| ldap_base: o=gouv,c=fr 
| ldap_base_groups: o=gouv,c=fr
| ldap_base_users: o=gouv,c=fr
| ldap_cache_ttl: 600
| ldap_configuration_active: 1
| ldap_display_name: cn
| ldap_dn: cn=XXXXXXXX
| ldap_email_attr: mail
| ldap_experienced_admin: 0
| ldap_expert_username_attr:
| ldap_expert_uuid_group_attr:
| ldap_expert_uuid_user_attr: mail
| ldap_group_display_name: cn
| ldap_group_filter_mode: 0
| ldap_group_member_assoc_attribute: member
| ldap_groupfilter_groups:
| ldap_groupfilter_objectclass:
| ldap_host: 10.X.X.X
| ldap_login_filter: (&(|(objectclass=inetOrgPerson))(|(mailPrimaryAddress=%uid)(mail=%uid)))
| ldap_login_filter_mode: 1
| ldap_loginfilter_attributes:
| ldap_loginfilter_email: 1
| ldap_loginfilter_username: 1
| ldap_nested_groups: 0
| ldap_nocase: 0
| NULL
| ldap_paging_size: 500
| ldap_port: 389
| ldap_quota_attr:
| ldap_quota_def:
| ldap_tls: 0
| ldap_turn_off_cert_check: 0
| ldap_user_filter_mode: 1
| ldap_userfilter_groups:
| ldap_userfilter_objectclass: dgcpPersonne inetOrgPerson mefiPersonne organizationalPerson sambaAccount
| ldap_userlist_filter: (|(objectclass=dgcpPersonne)(objectclass=inetOrgPerson)(objectclass=mefiPersonne)(objectclass=organizationalPerson)(objectclass=sambaAccount)) |
| types: authentication
| use_memberof_to_detect_membership: 1

**Comment by MorrisJobke** [comment]
cc @blizzz

**Comment by PVince81** [comment]
Please try again with 8.1.5 or 8.2.2 where many LDAP issues were fixed.

If you still have this issue, feel free to reopen.
