### ISSUE TITLE
Tooltip doesn't dissapear when a file is deleted.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#17977]
### Steps to reproduce

Having several files:
1. Delete one file and quickly put the cursor on the modified date and time of that file (before it is deleted).

### Expected behaviour
A tooltip appears and it closes a few seconds after.

### Actual behaviour
Tooltip appears and never disappears, until you refresh the page.

![screen shot 2015-07-30 at 10 19 11](https://cloud.githubusercontent.com/assets/9048796/8978665/802e9194-36a4-11e5-818e-098bfe00bada.png)

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.1.1","versionstring":"8.1.1 beta1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default ones.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

### Client configuration

**browser**
Chrome 43

**Comment by PVince81** [comment]
Yeah. probably because the mouseout event is never triggered because the element disappeared.
This means the tipsy should detect element removal too, not sure if that works in all browsers.

**Comment by jancborchardt** [comment]
@irgendwie this looks a lot like the issue we had in Mail with the tooltips. Do you want to prepare a pull request to fix it here?

**Comment by jancborchardt** [comment]
This will be fixed with 8.2 because we switched the tooltip library.
