### ISSUE TITLE
(Only) Admin Settings Page not showing/loading in OC 8.1

### ISSUE THREAD

**Issue by HiFiJ** [owncloud/core#17970]
Hi everybody,

I updated from 8.0.5 to 8.1 and not can not access the admin page anymore (via drop down menu in the upper right corner); it gives a ."Sorry, the page you are looking for is not found." which is the 404 from my Synology NAS where it is hosted.
The log file gives me no related message, no entry when re-/loading the admin page.
I ran into issues with enabled apps during the update and had to disable Contacts and Calendar via console.php.

The File/Contact/Calendar apps are accessible and working well, as is the personal user settings page. It's just the Admin Settings which are not available.

I found a couple of previous messages about similar problems, but they are of no help as they treat specific errors in the log file which are not showing up for me. Btw, this is not the "100% CPU when loading the admin settings" problem.

Thanks for any help,

Joost

**Comment by karlitschek** [comment]
This looks like a configuration specific problem. I suggest to ask this question in the forum at forum.owncloud.org Thanks

**Comment by Kawohl** [comment]
Thanks for your contribution, this surely looks like a configuration error. 

If people at forum.owncloud.org couldn't help you, could you please use the issue template.
https://raw.githubusercontent.com/owncloud/core/master/issue_template.md


This will help us finding the problem and providing a solution. I´ll close until more information is provided.
