### ISSUE TITLE
Allow configuring memcache settings in autoconfig.php

### ISSUE THREAD

**Issue by andrewsomething** [owncloud/core#17971]
Currently there isn't a great way to preconfigure memcache settings. It would be great to be able to use autoconfig.php

**Comment by RealRancor** [comment]
Just quoting from https://github.com/owncloud/core/issues/8022#issuecomment-60391346

>Just to clarify: autoconfig.php's job is to get over the setup page - only parameters which are >required for the setup are taken from the autoconfig.php file.
>
>Any further additional config parameters which are of interest to be setup can be put into additional >config files in the config directory.

where you can also find such an example config file.

**Comment by andrewsomething** [comment]
Thanks. I just came across that. Sorry for the noise.

**Comment by DeepDiver1975** [comment]
> Sorry for the noise.

no worries
