### ISSUE TITLE
Settings button (bottom left) does not work on Firefox and IE

### ISSUE THREAD

**Issue by hypnotoad** [owncloud/core#17973]
The button at the bottom left
here
https://demo.owncloud.org/index.php/apps/files/
and here
https://demo.owncloud.org/index.php/settings/users
should reveal a menu with hidden options and infos. At least on Firefox and IE, nothing happens when clicking on it. It used to work some months ago and on Chrome/Chromium it still works.

**Comment by Xenopathic** [comment]
Works fine for me, on Firefox 39 on Windows. What version of Firefox/IE are you using and on what operating system? Do you see anything in the browser logs?

**Comment by hypnotoad** [comment]
Browser versions which do not work:
Linux/Debian: Iceweasel 31.8.0
Windows: Firefox ESR 31.8.0   (tested with a clean new profile)
Windows: IE 11 (11.0.9600)

The Firefox JS Console displays: TypeError: event.target.closest is not a function upon a click on the settings symbol.

**Comment by Xenopathic** [comment]
Ah, that's the `element.closest` bug. Fix has been pushed to master (#17490), and will be released in 8.1.1 (#17707). Thanks for the prompt reply!
