### ISSUE TITLE
Unable to log in via Web interface

### ISSUE THREAD

**Issue by EtienneBruines** [owncloud/core#17988]
### Steps to reproduce
1. Go to the web interface of the owncloud installation
2. Enter credentials
3. Press "enter"

### Expected behaviour
I expect to be logged in, and see the directory listing or something. 

### Actual behaviour
* I am shown the exact same login page as before. 
* No errors (see below), not even in user-friendly HTML
* HTTP Status `200` is returned
* HTTP-cookies are being set
* Desktop client does work

### Server configuration
**Operating system**:
Debian Jessie
**Web server:**
`Apache/2.4.10`
**Database:**
`MariaDB 10.0.20`
**PHP version:**
`PHP 5.6.9-0+deb8u1 `
**ownCloud version:** (see ownCloud admin page)
Admin page doesn't work; downloaded latest stable zip. `8.1.0`
**Updated from an older ownCloud or fresh install:**
Updated.
**List of activated apps:**
```
Enabled:
 - activity: 2.0.1
 - files: 1.1.9
 - files_external: 0.2.3
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
Disabled:
 - calendar
 - contacts
 - documents
 - encryption
 - external
 - files_locking
 - provisioning_api
 - search_lucene
 - templateeditor
 - updater
 - user_external
 - user_ldap
 - user_webdavauth
```
**The content of config/config.php:**
```php
<?php
$CONFIG = array (
  'instanceid' => 'ocfc594258ce',
  'passwordsalt' => 'salt',
  'trusted_domains' => 
  array (
	  0 => 'owncloud.huperwebs.nl',
	  1 => '185.96.6.22'
  ),
  'datadirectory' => '/var/www/html/data',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost:/var/run/mysqld/mysqld.sock',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud_user',
  'dbpassword' => 'password',
  'installed' => true,
  'forcessl' => false,
  'theme' => '',
  'maintenance' => false,
  'mail_smtpmode' => 'smtp',
  'loglevel' => '0',
  'secret' => 'secret',
  'mail_smtphost' => 'localhost',
  'mail_smtpport' => '25',
  'mail_from_address' => 'noreply',
  'mail_domain' => 'huperwebs.nl',
);
?>
```
However, `sudo -u www-data php occ config:list system --public` returns:
```
  [InvalidArgumentException]                                
  There are no commands defined in the "config" namespace.  
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Not relevant

**Are you using encryption:** yes/no
Through proxy; but without encryption doesn't work either. 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No. 

### Client configuration
**Browser:**
Latest Chrome (44), Firefox, ...

**Operating system:**
Linux

#### Web server error log
Nothing logged at all (except for apache startup). 

#### ownCloud log (data/owncloud.log)
Nothing logged related to this.

#### Browser log
No errors in javascript, resources, etc.

**Comment by LukasReschke** [comment]
As far I can see on https://owncloud.huperwebs.nl/index.php your sessions are not stored correctly. Please check if PHP can write to the sessions directory.

**Comment by EtienneBruines** [comment]
Using `is_writable(session_save_path())`, it shows that it *is* in fact writable. 

Manually setting it using `ini_set(' session.save_path','/var/www/html/session');` and then `chmod 777 -R /var/www/html/session` does not bring anything either. 

(I'm doing all of this at the top of `index.php`)

**Comment by LukasReschke** [comment]
Anything in the apache log?

**Comment by LukasReschke** [comment]
`ini_set(' session.save_path','/var/www/html/session');` this also looks like one space too much?

**Comment by EtienneBruines** [comment]
You're right, that was one space too much. Fixed it, but didn't change anything. 

Apache log is empty so far

**Comment by EtienneBruines** [comment]
Increasing logging level of apache to debug, doesn't really output anything useful. 

I'm seeing a lot of these now; not sure if it's related:
```
2015-07-30T14:08:08.202606+00:00 55da3a03a6f1 apache: [Thu Jul 30 14:08:08.201584 2015] [authz_core:debug] [pid 10400] mod_authz_core.c(809): [client 172.17.42.1:50767] AH01626: authorization result of <RequireAny>: granted
Jul 30 14:08:08 55da3a03a6f1 apache: [Thu Jul 30 14:08:08.201584 2015] [authz_core:debug] [pid 10400] mod_authz_core.c(809): [client 172.17.42.1:50767] AH01626: authorization result of <RequireAny>: granted
2015-07-30T14:08:08.203268+00:00 55da3a03a6f1 apache: [Thu Jul 30 14:08:08.201631 2015] [authz_core:debug] [pid 10400] mod_authz_core.c(809): [client 172.17.42.1:50767] AH01626: authorization result of Require all granted: granted
Jul 30 14:08:08 55da3a03a6f1 apache: [Thu Jul 30 14:08:08.201631 2015] [authz_core:debug] [pid 10400] mod_authz_core.c(809): [client 172.17.42.1:50767] AH01626: authorization result of Require all granted: granted
```

**Comment by PVince81** [comment]
Any more luck with 8.1.3 ?

**Comment by EtienneBruines** [comment]
Apologies for the delay. Have been quite busy. Planned the update to 8.1.3 later this week, so it'll take a bit longer :-(. 

But I'll post results in this thread.

**Comment by MorrisJobke** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [latest stable version](http://owncloud.org/install/). :)

Thank you!
