### ISSUE TITLE
[7.0.5] Erasing files takes to long

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#17986]
Description:
As a test in I'm deleting a 75MB file and it is already running for like 10 minutes and I don't see any change on the filesystem what so-ever. no copy in the trash bin and no delete file in the source location.

I thought that could be related with: https://github.com/owncloud/core/commit/7432c73f5c2871a708dd8c51487197f12eb2458a

but as workaround the customer told me that deleting this line make the job:
https://github.com/owncloud/core/blob/stable7/apps/files_trashbin/lib/trashbin.php#L893
which causes unwanted and unneeded file-scans.

I'm not sure that is the appropriate approach or solution.

@MorrisJobke 

00003483

**Comment by MorrisJobke** [comment]
> https://github.com/owncloud/core/blob/stable7/apps/files_trashbin/lib/trashbin.php#L893

This is a function definition. This will never work. Please select the line and then press "y" to generate a permalink. ;)

**Comment by DeepDiver1975** [comment]
Solution: upgrade to OC8+

**Comment by MorrisJobke** [comment]
The line is https://github.com/owncloud/core/blob/v7.0.6/apps/files_trashbin/lib/trashbin.php#L893 #17630 was backported to 7.0.8 and should fix a lot.

**Comment by cdamken** [comment]
@MorrisJobke Thank you very much, I will provide the solution to the customer. Upgrading to 7.0.8 is more reasonable and easier that they do.
