### ISSUE TITLE
occ app:enable and app:disable don't return error code in case of failure

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#17980]
### Steps to reproduce
1. Try to enable or disable a non-existing app -> `occ app:enable random_app` and / or `occ app:disable random_app`

### Expected behaviour
The command returns an error code so it's easier to script with it

### Actual behaviour
The command exits fine

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1.0

**Updated from an older ownCloud or fresh install:** fresh install

### Notes
It's likely to happen with more versions and other commands

**Comment by PVince81** [comment]
here https://github.com/owncloud/core/pull/18384
