### ISSUE TITLE
[CentOS 6.6] Moving a group of files into a SMB mount using encryption raises a warning about database

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#17985]
### Steps to reproduce

1. Mount a SMB folder correctly.
2. Upload several files on it.
3. Enable encryption 2.0 correctly.
4. Move all files from SMB folder to the root folder.
5. Move again all those files from root folder to SMB folder.

### Expected behaviour
Files are moved smoothly without problems.

### Actual behaviour
There is a warning about one file randomly and that file is not moved.

```
An exception occurred while executing 'UPDATE `filecache` SET `storage` = ?, `path` = ?, `path_hash` = ?, `name` = ?, `parent` =? WHERE `fileid` = ?' with params ["3", "oc_crash \u00e1.png", "e30ec050947b01d93e6145f1c0774f04", "oc_crash \u00e1.png", "10", 924]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3-e30ec050947b01d93e6145f1c0774f04' for key 'fs_storage_path_hash'
```

### Server configuration
**Operating system**:
CentOS 6.6

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.4

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.1.1","versionstring":"8.1.1 beta1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
```
Enabled:
 - activity: 2.0.1
 - admin_audit: 0.6
 - encryption: 1.0.0
 - enterprise_key: 0.1.0
 - files: 1.1.10
 - files_external: 0.2.3
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.6
 - windows_network_drive: 0.1.1
Disabled:
 - external
 - files_antivirus
 - files_drop
 - files_ldap_home
 - objectstore
 - sharepoint
 - user_external
 - user_ldap
 - user_shibboleth
 - user_webdavauth
```
**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes, SMB

**Are you using encryption:** 
Yes

**Server Logs**
```
{"reqId":"cgph6edCKMT2jQPv9E8K","remoteAddr":"82.159.139.58","app":"no app in context","message":"Error while running background job: Backends provided no user object for ","level":3,"time":"2015-07-30T11:11:02+00:00"}
```

In one of the tests this log came out, it doesn't correspond to the warning detailed, but the problem was the same:
```
{"reqId":"cgph6edCKMT2jQPv9E8K","remoteAddr":"82.159.139.58","app":"files","message":" Backends provided no user object for ","level":3,"time":"2015-07-30T11:11:02+00:00"}
{"reqId":"cgph6edCKMT2jQPv9E8K","remoteAddr":"82.159.139.58","app":"no app in context","message":"Error while running background job: Backends provided no user object for ","level":3,"time":"2015-07-30T11:11:02+00:00"}
{"reqId":"p5ig\/7+hi9zq+Wj\/dhAv","remoteAddr":"82.159.139.58","app":"files","message":"Could not get node for path: \\\"22hotspot.png\\\" : File with name 22hotspot.png could not be located","level":2,"time":"2015-07-30T11:11:02+00:00"}
{"reqId":"p5ig\/7+hi9zq+Wj\/dhAv","remoteAddr":"82.159.139.58","app":"files","message":"Could not get node for path: \\\"paris.jpg\\\" : File with name paris.jpg could not be located","level":2,"time":"2015-07-30T11:11:02+00:00"}
```
### Client configuration

**browser**
Chrome 43

**Comment by schiesbn** [comment]
@SergioBertolinSG does this only happen with Samba? How you you move the files? With the sync client or drag&drop with the web interface. Does this only happen if you mount a specific number of files and can you re-produce it reliable?

**Comment by SergioBertolinSG** [comment]
I've tested this again in same environment and same steps using stable8.1 and it works correctly.
