### ISSUE TITLE
Stray DB entries after upload (Encryption's part folder isn't indexed)

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#17997]
### Steps to reproduce

1. Enable encryption
1. Add logging to addToCache in the scanner: `\OC_Log::write('ENCDEBUG', 'addToCache: "' . $path . '" ' . json_encode($data), \OC_Log::DEBUG);`
1. Using the sync client, upload a big file (chunking)

### Expected result
No cache entry is created with NULL parent

### Actual result
When creating files into the part folder, entries are added with NULL parent.
So there is no entry for "files_encryption/keys/files/data1.dat.ocTransferId4040295251.part" but there is one for its subdir "files_encryption/keys/files/data1.dat.ocTransferId4040295251.part/OC_DEFAULT_MODULE". The hole disappears as soon as the part file is renamed to the final file.

This isn't critical but could have side-effects.
Observed here https://github.com/owncloud/core/issues/17956#issuecomment-126338894

@schiesbn @icewind1991 to discuss a solution.

**Comment by PVince81** [comment]
Two possible approaches:
1) Make sure that if any path section ends with ".part", don't  use the cache. This instead of just the last section
or
2) Don't index anything under "files_encryption"

@schiesbn @icewind1991 what do you think ?

This issue has been observed again: https://github.com/owncloud/core/pull/18423#issuecomment-134127335

**Comment by PVince81** [comment]
Not sure if related but I see that encryption leaves the cache entries for the part files in the DB:
```
+--------+---------+------------------------------------------------------------------------------------------------------------+----------------------------------+--------+-------------------+----------+----------+---------+------------+---------------+-----------+------------------+----------------------------------+-------------+
| fileid | storage | path                                                                                                       | path_hash                        | parent | name              | mimetype | mimepart | size    | mtime      | storage_mtime | encrypted | unencrypted_size | etag                             | permissions |
+--------+---------+------------------------------------------------------------------------------------------------------------+----------------------------------+--------+-------------------+----------+----------+---------+------------+---------------+-----------+------------------+----------------------------------+-------------+
|     61 |       1 | files_encryption/keys/files/Food/IMAG0100.jpg.ocTransferId1083153640.part/OC_DEFAULT_MODULE                | 13eb5287a6e43dddfcb046be6ff1827e |     -1 | OC_DEFAULT_MODULE |        2 |        1 |     556 | 1440511936 |    1440511936 |         0 |                0 | 55dc77c017806                    |          31 |
|     64 |       1 | files_encryption/keys/files/Food/IMAG0100.jpg.ocTransferId1083153640.part/OC_DEFAULT_MODULE/fileKey        | d23acfbd9b048d408f38e08b47a7a40d |     61 | fileKey           |        8 |        7 |      44 | 1440511935 |    1440511935 |         0 |                0 | 595eabb6e6e1624eba1db0d84f4f35b3 |          27 |
|     67 |       1 | files_encryption/keys/files/Food/IMAG0100.jpg.ocTransferId1083153640.part/OC_DEFAULT_MODULE/root.shareKey  | 981d564590030bb5cf0d67385574466c |     61 | root.shareKey     |        8 |        7 |     512 | 1440511936 |    1440511936 |         0 |                0 | 888456ab79cf7af01d36410ad5123ade |          27 |
|     69 |       1 | files_encryption/keys/files/Food/IMAG0100.jpg                                                              | 7ddcb78cf5a6985392ed5b45a102a78e |     21 | IMAG0100.jpg      |        2 |        1 |      -1 | 1440511935 |    1440511935 |         0 |                0 | 55dc77c019a5c                    |          31 |
|     70 |       1 | files_encryption/keys/files/Food/IMAG0100.jpg/OC_DEFAULT_MODULE                                            | aa8a6a8d7cda51003c5ec418d4517cda |     69 | OC_DEFAULT_MODULE |        2 |        1 |      -1 | 1440511936 |    1440511936 |         0 |                0 | 55dc77c01ab93                    |          31 |
|     71 |       1 | files/Food/IMAG0100.jpg                                                                                    | e853550e383d1188c0b4627c2e1fb0cf |     18 | IMAG0100.jpg      |        9 |        5 | 1049452 | 1440511932 |    1440511932 |         1 |                0 | 2570cf5c395d6ef66dea4032bd6bc3b5 |          27 |
|    537 |       1 | files_encryption/keys/files/Food2/IMAG0100.jpg.ocTransferId1479728775.part/OC_DEFAULT_MODULE               | 544e125ebc4d466afc6434df91546928 |     -1 | OC_DEFAULT_MODULE |        2 |        1 |     556 | 1440511970 |    1440511970 |         0 |                0 | 55dc77e284ca1                    |          31 |
|    538 |       1 | files_encryption/keys/files/Food2/IMAG0100.jpg.ocTransferId1479728775.part/OC_DEFAULT_MODULE/fileKey       | ac96dbddb47e7fd75527cd0a76f8f336 |    537 | fileKey           |        8 |        7 |      44 | 1440511970 |    1440511970 |         0 |                0 | 3b076b6694da409e7857d1fc2181359c |          27 |
|    540 |       1 | files_encryption/keys/files/Food2/IMAG0100.jpg.ocTransferId1479728775.part/OC_DEFAULT_MODULE/root.shareKey | 8aefa20ed895893c8041d139366203d6 |    537 | root.shareKey     |        8 |        7 |     512 | 1440511970 |    1440511970 |         0 |                0 | d11073edc42bb66fb894f3e0e6621485 |          27 |
|    543 |       1 | files_encryption/keys/files/Food2/IMAG0100.jpg                                                             | ef11bbced09ec428e6ff6fa992538adf |    499 | IMAG0100.jpg      |        2 |        1 |      -1 | 1440511970 |    1440511970 |         0 |                0 | 55dc77e288d60                    |          31 |
|    544 |       1 | files_encryption/keys/files/Food2/IMAG0100.jpg/OC_DEFAULT_MODULE                                           | e39f6ee767501be0b6b69c3d637aee9c |    543 | OC_DEFAULT_MODULE |        2 |        1 |      -1 | 1440511970 |    1440511970 |         0 |                0 | 55dc77e28b8ae                    |          31 |
|    546 |       1 | files/Food2/IMAG0100.jpg                                                                                   | a359589ad942a91d7be81035c011c9d4 |    498 | IMAG0100.jpg      |        9 |        5 | 1049452 | 1440511966 |    1440511966 |         1 |                0 | a79e4176f881537b3f9fadfe08c4ab18 |          27 |
+--------+---------+------------------------------------------------------------------------------------------------------------+----------------------------------+--------+-------------------+----------+----------+---------+------------+---------------+-----------+------------------+----------------------------------+-------------+
```

The entries with octransferid should be gone.
I suspect it might be related to the part folder issue.

**Comment by xn--nding-jua** [comment]
Hi,

got the same problem on my ownCloud 8.1.0. When I search the oc_filecache with
```SELECT * FROM `oc_filecache` WHERE `path` LIKE '%.ocTransfer%' ```

I will get about 84769 results directing to:
a) files_encryption/keys/files_trashbin/files/Filename.ABC.ocTransferId123456789.part
b) files_encryption/keys/files/Filename.ABC.ocTransferId932952332.part

and the corresponding /OC_DEFAULT_MODULE-folder as well the fileKey and shareKey.

Each entry has a parent set (-1 or a number above 0).


At the moment I delete all ".ocTransferId"-entries every month right after the DB-backup. Not a nice solution.

kind regards,
Chris

**Comment by schiesbn** [comment]
@icewind1991 what could we do here? Would it be a option to limit the special part-file handling to files stored in the files folder? We probably shouldn't have such limitations for meta data.

**Comment by icewind1991** [comment]
That would make sense yes

It would require logic changes in multiple parts though, not sure if we want to change it for 8.2

cc @DeepDiver1975

**Comment by DeepDiver1975** [comment]
> It would require logic changes in multiple parts though, not sure if we want to change it for 8.2

let's decide on this once we have the code at hand - but I'd consider this not really critical for 8.2rc1

@cmonteroluque I propose to address this issue through out the RC1 bug fixing phase

**Comment by schiesbn** [comment]
@icewind1991 you probably know best what needs to be changed.

I would have just changed this ones:

````
$ grep -ir "ispartialfile" *
how:    rename isIgnoredFile to isPartialFile, remove check of blacklisted files in isPartialFile, correct usage of isPartialFile and isFileBlacklisted
lib/private/files/view.php:			if ($this->shouldEmitHooks($path1) && (Cache\Scanner::isPartialFile($path1) && !Cache\Scanner::isPartialFile($path2))) {
lib/private/files/view.php:				if ((Cache\Scanner::isPartialFile($path1) && !Cache\Scanner::isPartialFile($path2)) && $result !== false) {
lib/private/files/view.php:				if ((Cache\Scanner::isPartialFile($path1) && !Cache\Scanner::isPartialFile($path2)) && $result !== false) {
lib/private/files/view.php:		if ($path && Cache\Scanner::isPartialFile($path)) {
lib/private/files/view.php:		if (Cache\Scanner::isPartialFile($path)) {
lib/private/files/view.php:				} else if (!Cache\Scanner::isPartialFile($internalPath) && $watcher->checkUpdate($internalPath, $data)) {
lib/private/files/cache/scanner.php:		if (!self::isPartialFile($file)
lib/private/files/cache/scanner.php:	public static function isPartialFile($file) {
lib/private/files/cache/updater.php:		if (Scanner::isPartialFile($path)) {
lib/private/files/cache/updater.php:		if (!$this->enabled or Scanner::isPartialFile($path)) {
lib/private/files/cache/updater.php:		if (!$this->enabled or Scanner::isPartialFile($path)) {
lib/private/files/cache/updater.php:		if (!$this->enabled or Scanner::isPartialFile($source) or Scanner::isPartialFile($target)) {
````

But not sure if this is the complete list. As you are more familiar with the code, can you (@icewind1991)  prepare a pull request so that we can see the impact? Thanks!

**Comment by icewind1991** [comment]
Not all of those cases should be adjusted from what I can tell, and it requires having the decision whether or not a file should be ignored made by the storage of the file instead of being able to use the same logic for every file

**Comment by schiesbn** [comment]
> and it requires having the decision whether or not a file should be ignored made by the storage of the file instead of being able to use the same logic for every file

not sure about that. I think the part file handling should be the same for every file stored in user/files, no matter which storage is used. Because that's the logic we use to hide files as long as the upload isn't finished. I would say, we just need to change the semantic from "hide all part files" to "hide all part files in user/files". But maybe I miss something?

**Comment by icewind1991** [comment]
detecting if a file is inside `/user/files` requires the decision to be on the storage, since with the scanner we're working with internal paths (relative to the storage) so to check if it's inside `/user/files` we either need to get the mountpoint or check the if it's a home storage.

Thinking about it the best way would be to add a storage wrapper that removes any part file from the directory listening.
Since storage wrappers get to know the mountpoint it will be easy to correctly handle the different storage cases

**Comment by schiesbn** [comment]
> Thinking about it the best way would be to add a storage wrapper that removes any part file from the directory listening.

So you would suggest to remove all the isPartialFile() checks and instead filter the part files on storage level on operations like getDirectoryContent()? As far as I can see they can't be wrapped by a storage wrapper.

And what happens for single file operations? How do we decide in this case if it should be scanned or not. I don't see the equivalent to the  isPartialFile() check on storage level. For example in this case: https://github.com/owncloud/core/blob/master/lib/private/files/view.php#L699

**Comment by icewind1991** [comment]
if we block part files from opendir we prevent it going into the cache, any direct operation on the part file will still work.

This is the same behavior as we currently have only we can properly handle the "outside `/user/files`" case

**Comment by schiesbn** [comment]
I played a bit around with it but I have some doubts that this works.

> if we block part files from opendir we prevent it going into the cache

as far as I can see this only works for .part folders. What about part files within the folder? In this case we would need to apply a stream wrapper and remove the .part files on readdir(), right? Which lead to the question why we shouldn't use a stream wrapper at the first place?

Also what about individual files? If I create a file /data/user/foo.part we call scanFile directly on the file and don't perform a opendir('data/user').

Personally I don't have a good feeling here. I think the changes are to big at this stage of 8.2, at least I don't feel comfortable playing around with it at this stage. Also according to @PVince81 it doesn't seem to be critical. Nothing breaks, we just have some warnings. @icewind1991 feel free to propose a PR if you think it is possible to fix it without to much changes and without the risk of breaking other stuff.

**Comment by PVince81** [comment]
I'm more worried about the stray database entries:

1. Enable encryption
1. Upload file
1. `select * from oc_filecache where path like '%part%';`

Just found 5K entries on my productive server which I now manually deleted.

Definitely something to look into for 8.2.1

**Comment by PVince81** [comment]
Would it be possible to do a fix specifically for the encryption app that prevents it to use the file cache at all for anything outside "files/" ?

**Comment by schiesbn** [comment]
> Would it be possible to do a fix specifically for the encryption app that prevents it to use the file cache at all for anything outside "files/" ?

Please no! This screams for follow-up bugs. If you want to get a dir listing for a keys folder, etc. Also it would completely break if you use a object storage as primary storage.

Everything needs to be in the file cache and part file handling should be limited to user/files.

**Comment by schiesbn** [comment]
One quick fix I discussed with @PVince81 could be to change isPartialFile() to also return true if one of the directories within the path contains '.part'. So the method would not only reaturn true for ````files/foo/test.txt.part```` but also for ````files/foo.part/test.txt````.

This could be a simple fix to avoid the filecache entries with  parent=0. But I wonder if this would work with a object storage as primary storage. After the upload we would need to rename ````user/files_encryption/keys/foo.part/```` to ````user/files_encryption/foo```` does this work if foo.part is not stored in the file cache? How would we find the correct ID for the part folder stored on the object storage? On the other hand it seems to work somehow for the upload of part files where we first write a "file.part" and then rename it to "file" without having "file.part" in the file cache. Actually I really wonder how and if this works? When was it tested the last time? Maybe @butonic or @DeepDiver1975 can say something about it?

I think the long-term solution (oc9) should be to index all files in the file cache, no matter if it is a part file or not and no matter where it is stored and just filter it on output. Especially if we use webdav for the web interface as well there is mount point where all the data leave ownCloud and at this point we should simply remove .part so that they don't get displayed to the user but otherwise handled internally like every other file.

**Comment by icewind1991** [comment]
I tihnk we should only ignore .part files when scanning a folder for files but still put them in the cache when the scanner is triggered from an operation done directly on the part files.

Places where .part files are used (like upload) it can either directly work on storage to keep the part files out of the cache or use the to-be-introduced-in-9.0 api which makes it easy to do multiple operation without updating the cache for in-between states

**Comment by icewind1991** [comment]
For the short term I think ignore folders with .part in the name would be fine

**Comment by schiesbn** [comment]
I will create a pull request for it
