### ISSUE TITLE
OC v8: Music playing error?

### ISSUE THREAD

**Issue by tx7** [owncloud/core#18002]
Hi all,

I keep having this error whenever I tried to play mp3 or video on my iphone.
Neither the audio or video was played though.

Thanks.

Error 	PHP 	Cannot modify header information - headers already sent by (output started at /media/82468379-6874-47f3-9a21-615766f2ccab/www/owncloud/3rdparty/sabre/http/lib/Sapi.php:70) at /media/82468379-6874-47f3-9a21-615766f2ccab/www/owncloud/3rdparty/sabre/http/lib/Sapi.php#63 	2015-07-30T18:29:08-04:00
Error 	PHP 	Cannot modify header information - headers already sent by (output started at /media/82468379-6874-47f3-9a21-615766f2ccab/www/owncloud/3rdparty/sabre/http/lib/Sapi.php:70) at /media/82468379-6874-47f3-9a21-615766f2ccab/www/owncloud/3rdparty/sabre/http/lib/Sapi.php#63 	2015-07-30T18:29:08-04:00
Error	PHP	Cannot modify header information - headers already sent by (output started at /media/82468379-6874-47f3-9a21-615766f2ccab/www/owncloud/3rdparty/sabre/http/lib/Sapi.php:70) at /media/82468379-6874-47f3-9a21-615766f2ccab/www/owncloud/3rdparty/sabre/http/lib/Sapi.php#63	2015-07-30T18:29:08-04:00

**Comment by RealRancor** [comment]
Hi,

isn't this something for the music app repository https://github.com/owncloud/music/issues or how are you trying to play those filetypes? Could be also useful to fill out the issue template as asked in https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version (Linked in the yellow box when creating new issues).

**Comment by RealRancor** [comment]
Btw. are you using the music app for this? If yes looks like a dup of https://github.com/owncloud/music/issues/404

**Comment by tx7** [comment]
I forgot to fill out the template.
I'm currently using music app, direct menu.
OC v8.1.0

**Comment by RealRancor** [comment]
@tx7 Feel free to close this issue and continue in the one of the music apps issue tracker linked above.
