### ISSUE TITLE
[oC 7.0.8] Admin and personal pages doesn't have scroll bar in IE 8

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#18008]
### Steps to reproduce

Using internet explorer 8 with an admin user do:
1. Go to admin or personal page.
2. Try to scroll down.

### Expected behaviour
Page is scrolled down.

### Actual behaviour
You can't scroll.

![screen shot 2015-07-31 at 12 51 27](https://cloud.githubusercontent.com/assets/9048796/9005995/05eb3ca4-3783-11e5-9440-71f0ece47ccd.png)

### Server configuration

Operating system:
Ubuntu 14.04 LTS

Web server:
Apache

Database:
MySQL

PHP version:
5.5.9

ownCloud version: (see ownCloud admin page)
{"installed":"true","version":"7.0.8.0","versionstring":"7.0.8 beta1","edition":""}

Updated from an older ownCloud or fresh install:
fresh

List of activated apps:
Default ones.

Are you using external storage, if yes which one: local/smb/sftp/...
No.

Are you using encryption: 
No.

### Client configuration
Internet Explorer 8

**javascript errors shown in the screenshot:**
```
Webpage error details

Message: Invalid argument.
Line: 1097
Char: 9
Code: 0
URI: http://HOST/apps/files_texteditor/js/vendor/ace/src-noconflict/ace.js?v=030b014df605ac5c7bcdb3cd9a5edc52
```

**Comment by karlitschek** [comment]
@jancborchardt any idea?

**Comment by PVince81** [comment]
Looks like this bug is back from the dead https://github.com/owncloud/core/issues/9677

**Comment by cmonteroluque** [comment]
@jancborchardt @PVince81 IE 8 continues to be the bane of our existence. Any chance one of you could have a look here?

**Comment by SergioBertolinSG** [comment]
This is still broken in 7.0.9RC1, I think oC is totally unusable with this bug. Good reason to drop IE 8 support.

**Comment by jancborchardt** [comment]
@SergioBertolinSG is it not possible to scroll even with the scrollwheel or touchpad?

**Comment by SergioBertolinSG** [comment]
@jancborchardt Yes, not possible at all. (tested in 7.0.10 as well)

**Comment by jancborchardt** [comment]
Debugged with @SergioBertolinSG and the CSS values are exactly the same for ownCloud 8 and master (where scrolling works). The problem must lie somewhere else then.

**Comment by cmonteroluque** [comment]
won't fix for 7.x any longer.
