### ISSUE TITLE
Long path names causes OC requests to never return

### ISSUE THREAD

**Issue by xieliwei** [owncloud/core#18015]
Since last month's OC update, directories longer than ~68 characters on SMB external storage causes any requests to it to fail. Not sure what the exact length is, but I've narrowed it down to, for my case, creating a directory with a 69 character long name causes OC to fail when trying to open or sync the directory.

### Steps to reproduce
1. Configure a SMB external storage source
2. Create a directory with a 100 character-long name
3. Attempt to sync (with OC client) or browse with web interface the newly created directory

### Expected behaviour
The contents of the newly created directory should appear. Synchronisation should occur without issue.

### Actual behaviour
The WebDAV request never returns. On the web interface, the spinning wait image goes on forever after clicking on the directory.

On the server side, it can be seen that a new smbclient and apache instance is started each time a request occurs. Over time, clients trying to sync the offending folders cause hundreds of smbclient and apache instances to exist, causing the server to stop responding properly.

smbclient has no issue navigating into any directory when using the command line. No issues for other samba clients in Windows (7, 8, XP) or Linux (Ubuntu 14.04).

### Server configuration
**Operating system:** openSUSE 13.2 (Harlequin) (x86_64)

**Web server:** Apache/2.4.10 (Linux/SUSE) PHP/5.6.1

**Database:** mysqld  Ver 5.6.25 for Linux on x86_64 (openSUSE package)

**PHP version:** PHP 5.6.1

**Samba version:** Version 4.1.19-11.1-3442-SUSE-oS13.2-x86_64

**ownCloud version:** ownCloud 8.1.0 (stable)

**Updated from an older ownCloud or fresh install:** Was on owncloud-server-8.0.4-12.1

**List of activated apps:** 
Enabled:
 - files: 1.1.9
 - files_external: 0.2.3
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
Disabled:
 - activity
 - encryption
 - external
 - files_locking
 - provisioning_api
 - templateeditor
 - user_external
 - user_ldap
 - user_webdavauth

**The content of config/config.php:**
("sudo -u www-data php occ config:list system --public" reported that there is no "config" command)

<?php
define('DEBUG',true);
$CONFIG = array (
  'datadirectory' => '/srv/www/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => 1,
);

**Are you using external storage, if yes which one:** SMB

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

#### Web server error log
No relevant entries are generated

#### ownCloud log (data/owncloud.log)
Debug is turned on and I've followed this: https://forum.owncloud.org/viewtopic.php?f=17&t=7330
This is all I get in my logs (lots of it):
{"reqId":"kvIOmM8+x13pbiIXdyZZ","remoteAddr":"","app":"DeleteOrphanedSharesJob","message":"0 orphaned share(s) deleted","level":0,"time":"2015-07-31T18:30:02+00:00","me
thod":"--","url":"--"}

#### Interesting Stuff
After numerous requests to the offending directory

~ ps ax|grep smb
 1876 ?        Ss     0:02 /usr/sbin/smbd -D
 1881 ?        S      0:00 /usr/sbin/smbd -D
 3565 ?        S      0:00 smbclient --authentication-file=/proc/self/fd/3 //x.x.x.x/TEST
31711 ?        S      0:00 smbclient --authentication-file=/proc/self/fd/3 //x.x.x.x/TEST
31802 ?        S      0:00 smbclient --authentication-file=/proc/self/fd/3 //x.x.x.x/TEST
31840 ?        S      0:00 smbclient --authentication-file=/proc/self/fd/3 //x.x.x.x/TEST
31842 ?        S      0:00 smbclient --authentication-file=/proc/self/fd/3 //x.x.x.x/TEST
31864 ?        S      0:00 smbclient --authentication-file=/proc/self/fd/3 //x.x.x.x/TEST
32350 ?        S      0:00 smbclient --authentication-file=/proc/self/fd/3 //x.x.x.x/TEST
32379 ?        S      0:00 smbclient --authentication-file=/proc/self/fd/3 //x.x.x.x/TEST
32408 ?        S      0:00 smbclient --authentication-file=/proc/self/fd/3 //x.x.x.x/TEST
32423 ?        S      0:00 smbclient --authentication-file=/proc/self/fd/3 //x.x.x.x/TEST
32452 ?        S      0:00 smbclient --authentication-file=/proc/self/fd/3 //x.x.x.x/TEST
32458 ?        S      0:00 smbclient --authentication-file=/proc/self/fd/3 //x.x.x.x/TEST
32478 ?        S      0:00 smbclient --authentication-file=/proc/self/fd/3 //x.x.x.x/TEST
32502 ?        S      0:00 smbclient --authentication-file=/proc/self/fd/3 //x.x.x.x/TEST
32536 ?        S      0:00 smbclient --authentication-file=/proc/self/fd/3 //x.x.x.x/TEST
32562 ?        S      0:00 smbclient --authentication-file=/proc/self/fd/3 //x.x.x.x/TEST
32588 ?        S      0:00 smbclient --authentication-file=/proc/self/fd/3 //x.x.x.x/TEST
32593 ?        S      0:00 smbclient --authentication-file=/proc/self/fd/3 //x.x.x.x/TEST
32611 ?        S      0:00 smbclient --authentication-file=/proc/self/fd/3 //x.x.x.x/TEST

~ ps ax|grep apache
 1606 ?        Ss     0:04 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start
 1940 ?        S      1:28 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start
 1942 ?        S      1:25 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start
 1944 ?        S      1:27 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start
 1945 ?        S      1:28 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start
 1946 ?        S      1:26 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start
 3573 ?        S      0:01 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start
 3602 ?        S      0:01 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start
 3603 ?        S      0:01 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start
 4464 ?        S      1:26 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start
 6114 ?        S      1:24 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start
31704 ?        S      0:00 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start
31705 ?        S      0:04 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start
31706 ?        S      0:02 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start
31708 ?        S      0:00 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start
31798 ?        S      0:03 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start
31860 ?        S      0:01 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start
31869 ?        S      0:00 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start
31870 ?        S      0:00 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start
32403 ?        S      0:03 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start
32414 ?        S      0:04 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start
32415 ?        S      0:01 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start
32419 ?        S      0:00 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start
32421 ?        S      0:00 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start
32500 ?        S      0:00 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start
32513 ?        S      0:01 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start
32532 ?        S      0:01 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start
32558 ?        S      0:00 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start
32614 ?        S      0:02 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start
32615 ?        S      0:02 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start

Compare to a newly booted server
~ ps ax|grep smb
 1876 ?        Ss     0:02 /usr/sbin/smbd -D
 1881 ?        S      0:00 /usr/sbin/smbd -D

~ ps ax|grep apache
 4259 ?        Ss     0:00 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start
 4282 ?        S      0:00 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start
 4283 ?        S      0:00 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start
 4284 ?        S      0:00 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start
 4285 ?        S      0:00 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start
 4286 ?        S      0:00 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start
 4295 ?        S      0:00 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start
 4776 ?        S      0:00 /usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SYSTEMD -DFOREGROUND -k start

**Comment by DeepDiver1975** [comment]
Please try it with the libsmbclient php module : https://github.com/eduardok/libsmbclient-php

**Comment by xieliwei** [comment]
Well that fixed it! Is the smbclient wrapper deprecated?

**Comment by DeepDiver1975** [comment]
> Is the smbclient wrapper deprecated?

it's a fallback in case libsmbclient is not available - obviously with drawbacks :wink:

**Comment by priestoferis** [comment]
I think I'm having the same problem, but I'm not sure what the instructions mean. Should I install this php module and then enable it in apache? Or where? Thanks for the help!
