### ISSUE TITLE
Failed to login

### ISSUE THREAD

**Issue by stevejordi** [owncloud/core#18014]
Hi,
We have a major question, we have installed our server and everything is fine. But some users can't connect via their mobile devices.
We have noticed that their access are blocked by our brute force prevention technology (fail2ban) because each time a mobile connects, it keeps sending "login failed" message even when they connect correctly.
A folder refresh send "login failed" in the owncloud.log.
Those are regarded as hacks. In this case they are not.

As an example, when I connect I generate 10 lines like this one
{"app":"core","message":"Login failed: 'jordi' (Remote IP: 'nnn.nnn.nnn.nnn', X-Forwarded-For: '')","level":2,"time":"2015-07-01T13:39:19+02:00"}

Why are the mobile apps sending those login failed messages?
Android and iOS all behave the same way.

We have submitted ownCloud to a security audit company and it's not related to reverse proxies. They told us it's on the coding side.

ownCloud support told us that our webdav server is incorrectly configured. But where to you configure the webdav part? Is it on the end-user side? 

Thanks for any idea, clue, suggestion ;)

**Comment by Xenopathic** [comment]
Thanks for the report! Could you fill out our [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) to provide us with more information about your issue?

**Comment by stevejordi** [comment]
Well I did fill an issue and was sent to the forums telling me my webdav server was not correctly configured and I should post in the forums :-(

**Comment by DeepDiver1975** [comment]
Might be an encoding issue of username and password - any special characters in place?

**Comment by stevejordi** [comment]
No everything is standard user/pwd from an active directory. No special characters, no accents.
But besides the failed message, it still correctly logs in…

This is just when connecting to ownCloud via mobile devices

Steve

**Comment by DeepDiver1975** [comment]
strange

**Comment by Xenopathic** [comment]
Do you have Basic auth (or some kind of external web server authentication) enabled?

Also, please fill out the rest of the issue template (I checked your other issue reports but couldn't find a complete template) - it'll really help us!

**Comment by stevejordi** [comment]
OK I will do this once back to work on Monday.

**Comment by cdamken** [comment]
@stevejordi 

Are you using EE o CE? Which apps are enabled?

Can you provide your Fail2Ban paramethers?

**Comment by stevejordi** [comment]
Hi all,
We do not have another kind of authentication than an ActiveDirectory (on a Windows server).
All Users and groups are correctly accessed.

The Failed to Login appears in the logs for each attemps, but users can log in.

Our configuration is:
- Apache to redirect everthing to https on port 443
- We use the Community Edition 8.x on linux (CentOS 6)
- The failed to login are only generated by iOS and Android. Web based actions and DesktopSync do not cause any troubles.
- As it is exposed to the Internet, it's accessed through a reverse proxy. If we fully bypass it, the messages remain, the RP is not the cause.
- Fail2Ban config
[owncloud]
enabled = true
filter  = owncloud
action  = iptables[name=Owncloud, port=443, protocol=tcp]
          sendmail-whois[name=OwnCloud, dest=mail@ourmail.nn, sender=mail@ourmail.nn]
logpath = /var/log/owncloud/owncloud.log
#Ban time in seconds
bantime  = 1800
# # IP address is banned if it generated maxtry during the "findtaime" last seconds
findtime  = 300

- Log message
{"app":"core","message":"Login failed: 'jordi' (Remote IP: 'nnn.nnn.nnn.nnn', X-Forwarded-For: '')","level":2,"time":"2015-08-03T10:06:01+02:00"}
{"app":"core","message":"Login failed: 'jordi' (Remote IP: 'nnn.nnn.nnn.nnn', X-Forwarded-For: '')","level":2,"time":"2015-08-03T10:06:01+02:00"}
{"app":"core","message":"Login failed: 'jordi' (Remote IP: 'nnn.nnn.nnn.nnn', X-Forwarded-For: '')","level":2,"time":"2015-08-03T10:06:01+02:00"}

**Comment by PVince81** [comment]
CC @blizzz for AD

**Comment by Xenopathic** [comment]
I am unable to reproduce this. My Android client connects successfully, running without a reverse proxy but using an LDAP user, and I get no 'Login failed' messages in the logs.

**Comment by blizzz** [comment]
@davivel @masensio have you ever seen something like this?

**Comment by davivel** [comment]
No. But I don't fully understand the context.

> some users **can't connect** via their mobile devices.
We have noticed that their access are blocked by our brute force prevention technology (fail2ban) because each time a mobile connects, it keeps sending "login failed" message **even when they connect correctly.**

Do they connect or do not connect? Or the message appears in the logs no matter if they connect or not? In that case, the message is not necessarily related to the connection error...

Just to clarify, the mobile clients don't **send** that message to the server side, that's a message generated by the server. 


> Apache to redirect everthing to https on port 443

Is that redirecting also URLs explicitly starting with **http://** (no SSL) to HTTPS? That's a configuration I don't remember have tested, at least recently. Could or could not have nothing to do.

**Comment by stevejordi** [comment]
Sorry all,

You’re right, this sounds like it’s not making sense.

One user is using ownCloud from an secured wifi protected by Fail2Ban and get blocked with his devices since he is immediately rejected with the 10 attempts to login that own cloud logs.
If he uses cellular data or a public wifi, it works as those ones are not monitored by Fail2Ban.

This triggered our investigation about the causes to “login failed” and we checked the logged and have seen that all mobile connection give about 10-13 login failed messages before actually letting the users connect correctly. 
That’s why I said that people eventually connect, but they load our logs like crazy. Each time you access a file or refresh the directory lists from the devices, you generate tens of login failed messages even thought it eventually goes through. 

We had a security expert checking our infrastructure and everything’s fine except the code on own cloud side which seems to lose tokens between different requests. I have to ask him again exactly what the problem was.

Steve

**Comment by PVince81** [comment]
>We had a security expert checking our infrastructure and everything’s fine except the code on own cloud side which seems to lose tokens between different requests. I have to ask him again exactly what the problem was.

@stevejordi did you get any more info ?

**Comment by stevejordi** [comment]
Just called him. Slipped out of my mind sorry.

Obviously, the iOS/Android clients start communicating with the server without first checking authentication.
Once the auth response is negative, the client continues to send requests before responding to the authentication failed error and display the login screen, which leads to tens of Login  Failed that are then caught by our Fail2Ban.

It should immediately respond to the auth response before sending other requests to avoid this.

**Comment by blizzz** [comment]
@masensio anything known? ^

**Comment by davivel** [comment]
Is it possible to check if this happens for both iOS and Android, or just one of them? The implementations are independent. Please, check the user agent in the logs, should be clear what app sends each request.

**Comment by stevejordi** [comment]
Both apps. Unfortunately,

**Comment by davivel** [comment]
> Obviously, the iOS/Android clients start communicating with the server without first checking authentication.
Once the auth response is negative, the client continues to send requests before responding to the authentication failed error and display the login screen

Then, this is happening only in the login screen, right? Because I didn't understan that before:

> . Each time you access a file or refresh the directory lists from the devices, you generate tens of login failed messages even thought it eventually goes through.

Only login screen, or in other actions too? Both for iOS and Android?

In the login screen there are several unauthenticated interactions with the server before the user clicks 'connect'. That's an expected behaviour.

It's not expected in other views or actions in the app.

Is the status.php page in your server protected by password? It shouldn't.

**Comment by stevejordi** [comment]
We just upgraded two servers from 8.1.0 to 8.1.3 and this seems to have solved the problem.

It was not a problem with login prompt only, it was ALL transactions from the iOS  and Android
apps:  refresh, download, upload, share, delete… Each interaction was generating those problems.
Consider it closed now. 

I will monitor what is going on in the coming days and re-open the ticket if that behavior starts again,

Steve

**Comment by davivel** [comment]
OK, thanks. Will keep an eye on it.

**Comment by strayobject** [comment]
Since this issue comes up in search results. In my case the `"message":"Login failed: <username> (Remote IP: <ip>)"` log entries were caused by the TOTP module. Once I removed it, not only were new users able to log in, there was also 0 new 'login failed' messages generated.
