### ISSUE TITLE
Settings-button doesn't work in all apps

### ISSUE THREAD

**Issue by mcladyz** [owncloud/core#18018]
### Steps to reproduce
1. Click on the settings-button in any of the following apps: news, mail, files (Could affect other apps too, but at least calendar and contacts work)

### Expected behaviour
Application specific settings-dialog should open

### Actual behaviour
Nothing

### Server configuration
**Operating system**: Linux 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Web server:** nginx 1.6.2

**Database:** 10.0.20-MariaDB-0ubuntu0.15.04.1

**PHP version:** 5.6.4-4ubuntu6.2

**ownCloud version:** 8.1.0 (daily) Build:2015-07-02T22:33:50+00:00 06ec916b1128b9a1ec79751bdd78cc4a8c64ace8
**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
 - activity: 2.0.1
 - calendar: 0.7.2
 - contacts: 0.4.0.0
 - delete_confirmation: 1.0.1
 - files: 1.1.9
 - files_external: 0.2.3
 - files_locking: 
 - files_mv: 0.8.1a
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - mail: 0.1.3
 - news: 5.3.9
 - ocdownloader: 1.2.3
 - ownnote: 1.05
 - provisioning_api: 0.2
 - tasks: 0.7.1
 - templateeditor: 0.1
 - updater: 0.6
 - user_ldap: 0.6.1
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' => 
  array (
    0 => 'xxx',
  ),
  'datadirectory' => 'xxx',
  'overwrite.cli.url' => 'xxx',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin',
  'dbpassword' => 'xxx,
  'logtimezone' => 'UTC',
  'installed' => true,
  'memcache.local' => '\OC\Memcache\APCu',
  'ldapIgnoreNamingRules' => false,
  'loglevel' => 2,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_from_address' => 'xxx',
  'mail_domain' => 'xxx',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'xxx',
  'mail_smtpport' => '587',
  'mail_smtpname' => 'xxx',
  'mail_smtppassword' => 'xxx',
);

```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration

```
hasMemberOfFilterSupport      | 1                                                                                                                                          |
| hasPagedResultSupport         |                                                                                                                                            |
| homeFolderNamingRule          |                                                                                                                                            |
| lastJpegPhotoLookup           | 0                                                                                                                                          |
| ldapAgentName                 | cn=xxx,dc=xxx,dc=xxx                                                                                                           |
| ldapAgentPassword             | ***                                                                                                                                        |
| ldapAttributesForGroupSearch  |                                                                                                                                            |
| ldapAttributesForUserSearch   |                                                                                                                                            |
| ldapBackupHost                |                                                                                                                                            |
| ldapBackupPort                |                                                                                                                                            |
| ldapBase                      | dc=xxx,dc=xxx                                                                                                                      |
| ldapBaseGroups                | dc=xxx,dc=xxx                                                                                                                      |
| ldapBaseUsers                 | dc=xxx,dc=xxx                                                                                                                      |
| ldapCacheTTL                  | 600                                                                                                                                        |
| ldapConfigurationActive       | 1                                                                                                                                          |
| ldapEmailAttribute            | mail                                                                                                                                       |
| ldapExperiencedAdmin          | 0                                                                                                                                          |
| ldapExpertUUIDGroupAttr       |                                                                                                                                            |
| ldapExpertUUIDUserAttr        |                                                                                                                                            |
| ldapExpertUsernameAttr        |                                                                                                                                            |
| ldapGroupDisplayName          | cn                                                                                                                                         |
| ldapGroupFilter               | (&(|(objectclass=groupOfNames)))                                                                                                           |
| ldapGroupFilterGroups         |                                                                                                                                            |
| ldapGroupFilterMode           | 0                                                                                                                                          |
| ldapGroupFilterObjectclass    | groupOfNames                                                                                                                               |
| ldapGroupMemberAssocAttr      | member                                                                                                                                     |
| ldapHost                      | localhost                                                                                                                                  |
| ldapIgnoreNamingRules         |                                                                                                                                            |
| ldapLoginFilter               | (&(&(|(objectclass=posixAccount)(objectclass=simpleSecurityObject))(|(memberof=cn=owncloud,ou=Groups,dc=xxx,dc=xxx)))(|(cn=%uid))) |
| ldapLoginFilterAttributes     | cn                                                                                                                                         |
| ldapLoginFilterEmail          | 0                                                                                                                                          |
| ldapLoginFilterMode           | 0                                                                                                                                          |
| ldapLoginFilterUsername       | 0                                                                                                                                          |
| ldapNestedGroups              | 0                                                                                                                                          |
| ldapNoCase                    | 0                                                                                                                                          |
| ldapOverrideMainServer        |                                                                                                                                            |
| ldapPagingSize                | 500                                                                                                                                        |
| ldapPort                      | 389                                                                                                                                        |
| ldapQuotaAttribute            |                                                                                                                                            |
| ldapQuotaDefault              |                                                                                                                                            |
| ldapTLS                       | 1                                                                                                                                          |
| ldapUserDisplayName           | cn                                                                                                                                         |
| ldapUserFilter                | (&(|(objectclass=posixAccount)(objectclass=simpleSecurityObject))(|(memberof=cn=owncloud,ou=Groups,dc=xxx,dc=xxx)))                |
| ldapUserFilterGroups          | owncloud                                                                                                                                   |
| ldapUserFilterMode            | 0                                                                                                                                          |
| ldapUserFilterObjectclass     | posixAccount;simpleSecurityObject                                                                                                          |
| ldapUuidGroupAttribute        | auto                                                                                                                                       |
| ldapUuidUserAttribute         | auto                                                                                                                                       |
| turnOffCertCheck              | 0                                                                                                                                          |
| useMemberOfToDetectMembership | 1                                    
```

### Client configuration
**Browser:** Chromium Version 43.0.2357.130 Built on Ubuntu 14.04, running on LinuxMint 17 (64-bit)

**Operating system:** Linux 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

### Logs
#### Web server error log
```
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"\/bv9pBM1t7KLEZZzUUOM","remoteAddr":"192.168.1.1","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2015-08-01T13:01:52+00:00"}
{"reqId":"gpw83BxanWqyjTnCgoc5","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/srv\/www\/owncloud\/apps\/contacts\/appinfo\/app.php#35","level":3,"time":"2015-08-01T13:01:52+00:00"}
```

#### Browser log
```
```

**Comment by Xenopathic** [comment]
You didn't mention, but I'm assuming you are using Google Chrome? Do you see any JavaScript errors in the browser logs?

**Comment by mcladyz** [comment]
Sorry about that, I was testing with Chromium but the same occurs with Icecat (Firefox) as well.

**Comment by LukasReschke** [comment]
Please disable all third-party applications step by step. My bet is it is one of those that is causing this problems.

**Comment by mcladyz** [comment]
No dice. I disabled all applications that are tagged "Experimental applications" and "Approved" but the problem persists.

**Comment by LukasReschke** [comment]
Would it be possible for you to give us an non-administrative user account on this server? You can contact me privately via my mail address lukas (at) owncloud (dot) com.

**Comment by 8l4ckSh33p** [comment]
@ Luke, I have the same problem in my ownCloud instance. I'm using a custom theme. Would you like to have an account?

**Comment by yellowcow1100** [comment]
Got the same issue.

**Comment by MorrisJobke** [comment]
> I have the same problem in my ownCloud instance. I'm using a custom theme. Would you like to have an account?

Feel free to provide me with credentials - then I can have a look. For my email see my github profile.

**Comment by mcladyz** [comment]
Updated to 8.1.1 and the bug is gone.
