### ISSUE TITLE
PHP Fatal error:  Class 'OCA\\Files_Sharing\\API\\Server2Server' not found in /var/www/owncloud/ocs/routes.php on line 107

### ISSUE THREAD

**Issue by Tr4sK** [owncloud/core#18019]
### Steps to reproduce
1. Upgrading owncloud to 8.1.0;
2. Activate calendar, contact, roundcube apps;
3. Upgrade those apps.

### Expected behaviour
Work like a boss.

### Actual behaviour
White/empty page.

### Server configuration
**Operating system**:
Debian 7.8

**Web server:**
apache2

**Database:**
sqllite

**PHP version:**
PHP 5.4.41-0+deb7u1 (cli) (built: May 28 2015 18:22:26) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies

**ownCloud version:** (see ownCloud admin page)
8.1.0

**Updated from an older ownCloud or fresh install:**
Updated

**List of activated apps:**
Contact, calendar, note…
For now, I moved "apps" to "appsback". Still similar issue.

```
If you have access to your command line run e.g.:

root@cloud:/var/www/owncloud# sudo -u www-data php occ app:list
Enabled:
Disabled:

```
<?php
$CONFIG = array (
  'instanceid' => '********',
  'passwordsalt' => '*******************',
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'sqlite3',
  'version' => '8.1.0.8',
  'dbname' => '********',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'installed' => true,
  'forcessl' => true,
  'maintenance' => false,
  'loglevel' => '0',
  'theme' => '',
  'ldapIgnoreNamingRules' => false,
  'trusted_domains' => 
  array (
    0 => 'cloud.*******.fr',
  ),
  'share_folder' => '/Shared',
  'mail_smtpmode' => 'php',
  'mail_smtpsecure' => 'tls',
  'mail_from_address' => 'noreply',
  'mail_domain' => '*******.fr',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'mail.********.fr',
  'mail_smtpname' => '*******',
  'mail_smtppassword' => '*************',
  'mail_smtpport' => '465',
  'secret' => 'dbcc584ddf27c410b9bdbdf6f8c79a317c71f52e722094c7d066b62811cafcf81a9e70e652dfbe81fee11bbe2eb649b4',
  'enable_previews' => true,
  'preview_max_x' => NULL,
  'preview_max_y' => NULL,
  'preview_max_scale_factor' => 10,
  'preview_max_filesize_image' => 50,
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'preview_office_cl_parameters' => ' --headless --nologo --nofirststartwizard --invisible --norestore -convert-to pdf -outdir ',
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\Image',
    1 => 'OC\\Preview\\MP3',
    2 => 'OC\\Preview\\TXT',
    3 => 'OC\\Preview\\MarkDown',
    4 => 'OC\\Preview\\OpenDocument',
  ),
);

```
root@cloud:/var/www/owncloud# sudo -u www-data php occ config:list system --public                       
  [InvalidArgumentException]                                
  There are no commands defined in the "config" namespace.  
                                                            
```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend:** no

#### LDAP configuration (delete this part if not used)

```
On ownCloud 7+ with access to your command line run e.g.:
root@cloud:/var/www/owncloud# sudo -u www-data php occ ldap:show-config
  [InvalidArgumentException]                              
  There are no commands defined in the "ldap" namespace.  
                                                          


On ownCloud 6 with access to your command line run e.g.:
root@cloud:/var/www/owncloud# sqlite data/owncloud.db
SQLite version 2.8.17
Enter ".help" for instructions
sqlite> select * from oc_appconfig where appid='user_ldap';
SQL error: no such table: oc_appconfig
sqlite> 
```

### Client configuration
**Browser:**
Mozilla Iceweasel 31.8.0

**Operating system:**
Debian 8.1

#### Web server error log
```
[Sat Aug 01 16:44:14 2015] [error] [client 1*******] PHP Fatal error:  Class 'OCA\\Files_Sharing\\API\\Server2Server' not found in /var/www/owncloud/ocs/routes.php on line 107
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"yRvBKU5RwjmksJ5TcB8v","remoteAddr":"***************","app":"PHP","message":"Class 'OCA\\Files_Sharing\\API\\Server2Server' not found at \/var\/www\/owncloud\/ocs\/routes.php#107","level":3,"time":"2015-08-01T14:45:42+00:00","method":"GET","url":"\/"}
{"reqId":"6TCUTlvkBq\/M3ZHSOliE","remoteAddr":"*******************","app":"PHP","message":"require_once(\/appinfo\/remote.php): failed to open stream: No such file or directory at \/var\/www\/owncloud\/remote.php#132","level":3,"time":"2015-08-01T14:46:02+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/"}
{"reqId":"6TCUTlvkBq\/M3ZHSOliE","remoteAddr":"************","app":"PHP","message":"require_once(): Failed opening required '\/appinfo\/remote.php' (include_path='\/var\/www\/owncloud\/3rdparty\/pear\/pear_exception:\/var\/www\/owncloud\/3rdparty\/pear\/archive_tar:\/var\/www\/owncloud\/3rdparty\/phpseclib\/phpseclib\/phpseclib:\/var\/www\/owncloud\/lib\/private:\/var\/www\/owncloud\/config:\/var\/www\/owncloud\/3rdparty:\/var\/www\/owncloud\/apps:\/var\/www\/owncloud\/lib:.:\/usr\/share\/php:\/usr\/share\/pear:\/var\/www\/owncloud') at \/var\/www\/owncloud\/remote.php#132","level":3,"time":"2015-08-01T14:46:02+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/"}

```

#### Browser log
```

**Comment by PVince81** [comment]
@Tr4sK how did you upgrade to 8.1 ? Distro package, updater app or manually extract tarball ?

It looks like there's an issue in core (not related to apps) and a class is missing.
Does the file "apps/files_sharing/api/server2server.php" exists in your installation ?
If not you might need to delete the OC code and then extract the tarball again (depending on how you installed/updated on your system)

**Comment by nickvergessen** [comment]
Dup of #18626 ?

**Comment by Tr4sK** [comment]
@PVince81 I do it trough distro package. Anyway, after upgrading to 8.1.1 everything went fine again :)
