### ISSUE TITLE
owncloud on centos server fais to update (apparent repo problems with file versions?)

### ISSUE THREAD

**Issue by lpallard1** [owncloud/core#18021]
When trying to update my local centos 7 server on which owncloud runs, all packages were successfully updated except the owncloud packages.  At the end of "yum update", I receive the following errors:

--> Finished Dependency Resolution
Error: Package: owncloud-app-files_encryption-8.0.4-12.1.noarch (@isv_ownCloud_community)
           Requires: owncloud-server-core = 8.0.4
           Removing: owncloud-server-8.0.4-12.1.noarch (@isv_ownCloud_community)
               owncloud-server-core
               owncloud-server-core = 8.0.4
           Updated By: owncloud-server-8.1.0-18.1.noarch (isv_ownCloud_community)
               owncloud-server-core = 8.1.0
Error: Package: owncloud-app-updater-8.0.4-12.1.noarch (@isv_ownCloud_community)
           Requires: owncloud-server-core = 8.0.4
           Removing: owncloud-server-8.0.4-12.1.noarch (@isv_ownCloud_community)
               owncloud-server-core
               owncloud-server-core = 8.0.4
           Updated By: owncloud-server-8.1.0-18.1.noarch (isv_ownCloud_community)
               owncloud-server-core = 8.1.0
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

OwnCloud was installed with the proper owncloud repo (isv_ownCloud_community) like shown below:

[root@centos-cloud ~]# yum list installed | grep @isv_ownCloud_community
owncloud-3rdparty.noarch              8.0.4-12.1                       @isv_ownCloud_community
owncloud-app-activity.noarch          8.0.4-12.1                       @isv_ownCloud_community
owncloud-app-external.noarch          8.0.4-12.1                       @isv_ownCloud_community
owncloud-app-files.noarch             8.0.4-12.1                       @isv_ownCloud_community
owncloud-app-files_encryption.noarch  8.0.4-12.1                       @isv_ownCloud_community
owncloud-app-files_external.noarch    8.0.4-12.1                       @isv_ownCloud_community
owncloud-app-files_locking.noarch     8.0.4-12.1                       @isv_ownCloud_community
owncloud-app-files_pdfviewer.noarch   8.0.4-12.1                       @isv_ownCloud_community
owncloud-app-files_sharing.noarch     8.0.4-12.1                       @isv_ownCloud_community
owncloud-app-files_texteditor.noarch  8.0.4-12.1                       @isv_ownCloud_community
owncloud-app-files_trashbin.noarch    8.0.4-12.1                       @isv_ownCloud_community
owncloud-app-files_versions.noarch    8.0.4-12.1                       @isv_ownCloud_community
owncloud-app-files_videoviewer.noarch 8.0.4-12.1                       @isv_ownCloud_community
owncloud-app-firstrunwizard.noarch    8.0.4-12.1                       @isv_ownCloud_community
owncloud-app-gallery.noarch           8.0.4-12.1                       @isv_ownCloud_community
owncloud-app-provisioning_api.noarch  8.0.4-12.1                       @isv_ownCloud_community
owncloud-app-templateeditor.noarch    8.0.4-12.1                       @isv_ownCloud_community
owncloud-app-updater.noarch           8.0.4-12.1                       @isv_ownCloud_community
owncloud-app-user_external.noarch     8.0.4-12.1                       @isv_ownCloud_community
owncloud-app-user_ldap.noarch         8.0.4-12.1                       @isv_ownCloud_community
owncloud-app-user_webdavauth.noarch   8.0.4-12.1                       @isv_ownCloud_community
owncloud-config-apache.noarch         8.0.4-12.1                       @isv_ownCloud_community
owncloud-server.noarch                8.0.4-12.1                       @isv_ownCloud_community

Is there a problem with package management on the repo??

**Comment by karlitschek** [comment]
@jnweiger Any idea?

**Comment by jnweiger** [comment]
@lpallard1 do you have a full log?
Do you still have that issue with 8.1.1?

**Comment by lpallard1** [comment]
@jnweiger  I issued a "yum erase owncloud-server-core" then a "yum  install owncloud-server-core" and all went fine!

Somehow, it wouldnt allow upgrading from 8.0.4 to 8.1.1..

The only output that was available was what I provided before.  I managed to create a full VM backup before trying this so worst case scenario I have a functioning setup, so if you need me to do more testing I can restore it and try more stuff.

Now its working with 8.1.1 but I have many warnings to take care off...
Thanks!

**Comment by jnweiger** [comment]
Great to hear that it works now.

There was an unversioned owncloud-server-core symbol in 8.0.4 which caused issues. This is now replaced by a properly versioned provides symbol in 8.0.6 and 8.1.1  -- I believe this explains the weird behaviour. yum erase owncloud-server-core was the right solution. 

Thanks for the report anyway!
