### ISSUE TITLE
Feature Request- Sub folder permission settings

### ISSUE THREAD

**Issue by KKyang** [owncloud/core#18025]
I'm using Owncloud 8.1 now. Is Owncloud able to change the permission of the sub folder in a shared folder?

For example:
folder A : group a read only, group b read only
 |_ folder A-1 :  group a read only, group b read / write
 |_ folder A-2 :   group a read / write, group b read only

**Comment by Kawohl** [comment]
This is already possible.

**Comment by Kawohl** [comment]
https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by KKyang** [comment]
No, it's not possible.
If I shared the folder A with group a, I'm not able to set additional permission of group a of folder A-1.

**Comment by Kawohl** [comment]
Hey KKyang thanks for reporting,
could you please use the issue template to make your request.

https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

I can't reproduce this. 

Could you eventually add snapshots?

**Comment by Kawohl** [comment]
Possibly the same issue as
 https://github.com/owncloud/core/issues/18075  ?
