### ISSUE TITLE
Rename oc_filecache to oc_fileindex

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#18027]
The problem:
- many people believe this table is just a cache that can be cleared and sometimes resort to clearing it
- clearing the file cache loses association of shares, tags, etc with files

Solution:
- rename oc_filecache to oc_fileindex

Also: the file cache table is really more an index or a metadata index than a cache.
If people do find about old blogs advising to clear oc_filecache, they won't find this table.
Having the table as oc_fileindex will give the impression that it is something different, so more of a psychological solution :smile: 

Not sure if the table can be rename properly with a change of db_structure.xml.

@icewind1991 @DeepDiver1975 @karlitschek @schiesbn @nickvergessen

**Comment by DeepDiver1975** [comment]
Well - people need to learn not to play around with the database.

Regarding the migration - db_structure.xml cannot handle this. 

I vote for won't fix

**Comment by MorrisJobke** [comment]
I also think that this will add more trouble. Don't mess around with the DB - that's it.

**Comment by PVince81** [comment]
Okay, thanks for the feedback.

**Comment by cmonteroluque** [comment]
don't truncate the filecache table, EVER. You will lose data. Don't do it. Don't!!!!

**Comment by gael-ian** [comment]
> Well - people need to learn not to play around with the database.

So don't give them a way to do it easily via `occ`

**Comment by PVince81** [comment]
@gael-ian I wasn't aware that there was an `occ` command to allow this... Will investigate and destroy it

**Comment by PVince81** [comment]
There's a command `occ files:cleanup`. I tested it and it doesn't clear the file cache but only tries to repair and remove orphaned entries.
