### ISSUE TITLE
Thumbnail on Android after core update are not working

### ISSUE THREAD

**Issue by DevTeamPostCy** [owncloud/core#18033]
Thumbnail are not viewable on android .

Also when I locate from core website to /remote.php/webdav/Photos/Paris.jpg the thumbnail is automatically open in a download link and not in a preview mode. 

Does anybody know how to fix that issue?

**Comment by karlitschek** [comment]
Can you please post this on the android repo. Thanks a lot.

**Comment by DevTeamPostCy** [comment]
But this is an issue that became after core update. So it might be not a problem of Android.... But ok, I will post also there, thank you.
