### ISSUE TITLE
OC 8.0.5 - file access rights are not correctly set when uploading a file to a WebDAV share

### ISSUE THREAD

**Issue by j-ed** [owncloud/core#18036]
## Expected behavior
File access rights should correctly been set if files are uploaded to a WebDAV share.

## Current behavior
If a file is uploaded to a WebDAV share the owner(UID) and group (GID) are correctly set but no access rights are set at all.

## Steps to reproduce
1. mount a WebDav share for a users with e.g. user name 'juergen'.
2. make sure that the WebDAV share can be accessed from the files menu.
3. change to the mounted WebDAV share and upload a file by pressing the upload button and selecting a file.
4. The file is uploaded and displayed in the folder but it couldn't be opened when selected.
5. Check the access rights of the file on the server console.
   The owner and group have been correctly been set but the access rights are missing:

   ```
   # ls -ald test.jpg
   ---------- 1 juergen users 44775 Aug  3 17:15 test.jpg
   ```
6. Change the access rights manually and the file can be opened when selected.

   ```
   # chmod 0750 test.jpg
   # ls -ald test.jpg
   -rwxr-x--- 1 juergen users 44775 Aug  3 17:15 test.jpg
   ```

#### Server Configuration
OS: Linux 3.2.67
Web server: Apache2 2.4.12
Database: MySQL 5.1.73
PHP version: 5.4.42
ownCloud version: 8.0.5

#### Client Configuration
Browser: Firefox 39.0
Operating system: Windows 7

**Comment by PVince81** [comment]
That is really weird.
Does your server have a non-standard umask value ?

**Comment by PVince81** [comment]
AFAIK ownCloud doesn't explicitly chmod the files to the proper permissions and relies on the default

**Comment by j-ed** [comment]
The umask is set to `0022` on both servers and hasn't been changed - in 8.0.3 everything worked fine.

**Comment by PVince81** [comment]
@j-ed is this still on your custom distro ? I don't see any reason why the chmod would be wrong.

You could try creating a small PHP file "test.php" in the owncloud folder: 
```php
<?php
    file_put_contents('data/test.txt', 'test contents');
```

Then open "test.php" with the web UI and see if the file that was created in "data/test.txt" has the correct permissions.

**Comment by j-ed** [comment]
@PVince81 Yes it's on my custom distro. Your example works fine because it creates a file on the local store. I've also tested it by uploading a file in ownCloud to the local store which also works fine. The problem only appears if a WebDAV share has been mounted using the ownCloud admin interface.
```
# ls -ald test.txt
-rw-r--r-- 1 wwwrun nogroup 13 Aug  4 10:20 test.txt
```

**Comment by PVince81** [comment]
What Webdav server are you using for the remote storage ? Are you sure it's not a configuration issue in the remote Webdav server ?
ownCloud doesn't send any permission information when working with remote Webdav mounts.

**Comment by j-ed** [comment]
I'm using a Synology NAS for the remote storage. I've double-checked the permissions of the WebDAV share and found out that the access rights haven't been set correctly. After granting 'read/write' instead of 'read' permission for the user files are created correctly again. Thank you for the kicking me in the right direction.
