### ISSUE TITLE
Automatically update encryption keys on shared folders with groups

### ISSUE THREAD

**Issue by kevinkk525** [owncloud/core#18046]
Please add an automatic update of encryption keys if a new user gets added to a group that shares folders. Re-sharing  folders just to update the encryption is a lot of work and depending on the size this takes some time.
And just sharing it with that new user and then removing the share while he remains in the group the folder was shared with does not work.
So I have to remove the share for the group and re-share it with the group every time I add a user to that group. That's quite a lot of work.

**Comment by schiesbn** [comment]
Will be addressed here: https://github.com/owncloud/core/issues/16332. But keep in mind that all this stuff will increase convenience but decrease security. You can't have both.

> And just sharing it with that new user and then removing the share while he remains in the group the folder was shared with does not work.

This should work. Please use the issue template https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by PVince81** [comment]
Also this was discussed here: https://github.com/owncloud/core/issues/10010

**Comment by schiesbn** [comment]
> And just sharing it with that new user and then removing the share while he remains in the group the folder was shared with does not work.

But that's probably the same issue you have here. So for this part continue here: https://github.com/owncloud/core/issues/18053
