### ISSUE TITLE
owncloud 7.0.7 broken

### ISSUE THREAD

**Issue by cwittmer** [owncloud/core#18040]
A fresh new install of owncloud 7.0.7 is broken ...
... with apache 2.2.17
... php 5.3.17

PHP Parse error:  syntax error, unexpected '[' in /srv/www/htdocs/owncloud/apps/contacts/lib/addressbookprovider.php on line 123

**Comment by LukasReschke** [comment]
Please apply https://github.com/owncloud/contacts/pull/995, will be fixed with the next 7.0.8

**Comment by cwittmer** [comment]
Thanks for the quick response ...
