### ISSUE TITLE
ldap: autodetected memberof settings break user-group mapping

### ISSUE THREAD

**Issue by mdik** [owncloud/core#18048]
### Steps to reproduce
1. Install a fresh ownCloud in version 8.1
2. Enable LDAP app
3. Share files/calendars/addressbooks with a group
### Expected behaviour

The members of the group the file/calendar/addressbook can be seen/used by the members of the group.

Table `oc_ldap_group_members` is filled with what is given in the LDAP tree.
### Actual behaviour

The members of the group can't see the file/calendar/addressbook.

Table `oc_ldap_group_members` is empty.
### Server configuration

The configuration is as stated in https://github.com/owncloud/contacts/issues/1004,

the only important parameters are in the LDAP config, though (see below).
#### LDAP configuration

The group management is done almost entirely with posixGroups, there is one groupOfNames and memberOf modules enabled in slapd, though. The groupOfNames is of no use for the ownCloud, though and could/should be safely ignored.

```
ownclouddb=# select * from oc_appconfig where appid='user_ldap' and configkey 
~ '.*memberof.*';
   appid   |             configkey             | configvalue 
-----------+-----------------------------------+-------------
 user_ldap | use_memberof_to_detect_membership | 1
 user_ldap | has_memberof_filter_support       | 1
```
### Workaround

Set `use_memberof_to_detect_membership` and `has_memberof_filter_support` to 0.

ownCloud 8.0 did so and kept this setting as is even after upgrading. Please revert the behaviour back to the 8.0 one or expose these settings in the Advanced or Expert LDAP settings.

**Comment by blizzz** [comment]
@mdik thanks for your report!

> Table oc_ldap_group_members is filled with what is given in the LDAP tree.

No, this is not what should happen immediately and is only of interest for updating group memberships if necessary (files sharing for instance does not need it).

However, the group members are supposed to see the calendar.

> The group management is done almost entirely with posixGroups, there is one groupOfNames and memberOf modules enabled in slapd, though.

That's the reasons why the group association does not work and we need to improve.  Setting use_memberof_to_detect_membership is the correct way to get around this for the time being.

**Comment by PVince81** [comment]
8.1 is quite outdated and there have been a lot of changes and fixed in LDAP.

Please try again with a recent version like 9.0.7 or 9.1.3. If the problem persists, please reopen.
