### ISSUE TITLE
Another instance of cron.php is still running!

### ISSUE THREAD

**Issue by fossxplorer** [owncloud/core#18049]
## Steps to reproduce
1. Install stable8.1 and enable system cron
2. When the second round of cron is run, i get email with "Another instance of cron.php is still running!"

Lock file exists in /tmp/owncloud-server-513a1eb54g123-cron.lock and the problem obviously is that this lock file isn't removed after cron run.

Nothing in the oC log related to this issue. 

## Expected result
oC cron runs without any issues.

## Versions
stable8.1
PHP 5.5.20 

@Raydiation any idea what causes this?

**Comment by MorrisJobke** [comment]
I think then simply another cron process is running. #14400 

Once the process dies/exits the systems handles the removal of the lock file AFAIK.

**Comment by Raydiation** [comment]
The lock file is not supposed to be removed, it's locked and other instances won't execute the cron if the file is locked. 

The issue here is that you're not supposed to be notified because this is not an error. It is what should actually happen

**Comment by fossxplorer** [comment]
Ok. 
But this did not happend prior to upgrade to stable8.1. Has things changed around the cron runs?

**Comment by MorrisJobke** [comment]
> But this did not happend prior to upgrade to stable8.1. Has things changed around the cron runs?

Usually not. Maybe the runtime of a cron job has increased and it never happened before for you.

**Comment by Raydiation** [comment]
@MorrisJobke just wanted to say the same :)

**Comment by MorrisJobke** [comment]
> Cron job has been running since 11:15 today, so for over 2.5H now.

Can happen ... Maybe some external file scan?

Any news regarding your problem?

**Comment by MorrisJobke** [comment]
@fossxplorer Do you still notice these problems?

**Comment by MorrisJobke** [comment]
As there is no feedback I will close this here. Feel free to reopen if there are more info about this suspicious cron run.

**Comment by rdalmaso78gmailcom** [comment]
Hi I have the same problem... OC 8.2.2 on Ubuntu 14.04 lts. Notifications activity does not work at all, email setup is ok. Thanks in advance for your help
