### ISSUE TITLE
files_archive blocks archive files deletion

### ISSUE THREAD

**Issue by fossxplorer** [owncloud/core#18045]
## Steps to reproduce
  1. Enable files_archive
  2. upload an archive file, e.g a zip file
  3. Notice the size being reported as "pending" and "No permission to delete" when hovering over delete (trashbin) button. Also the folder icon is used and not archive one.
  4 Reload the page and everything looks normal but trying to delete the newly uploaded zip file gives "Could not delete: myfile.zip" 
Web server logs shows:  "POST /index.php/apps/files/ajax/delete.php HTTP/1.1" 200 239 "http://example.com/index.php/apps/files/?dir=%2F"
    
Nothing in the oC log related to this issue. 

## Expected result

Zip file size is updated with Ajax to reflect the size of the file right after upload.
Deletion of the file should work without any errors.

## Versions
stable8.1

@icewind1991

**Comment by DeepDiver1975** [comment]
as discussed - pleaser reopen in https://github.com/owncloud/apps
