### ISSUE TITLE
LDAP host tipsy shifts position of port field

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#18044]
### Steps to reproduce

1. Open LDAP wizard
1. Hover on the host field to make the tipsy appear
1. Observe the "Port" field

### Expected result
Port field stays where it is

### Actual result
Port field moves to the next line

Before hovering:
![portslide-before](https://cloud.githubusercontent.com/assets/277525/9053893/86d251a4-3a7b-11e5-81e4-25d4b7f83831.png)

After hovering:
![portslide-after](https://cloud.githubusercontent.com/assets/277525/9053895/8ea13c1a-3a7b-11e5-9d57-374150b4d409.png)

### Versions
ownCloud 8.2 git master (92da1a64b40a224db58f4456837dee9bb71f8d2e)
Chromium 43

@blizzz

**Comment by blizzz** [comment]
do we drop support for chromium 43? :laughing:

**Comment by LukasReschke** [comment]
> do we drop support for chromium 43? :laughing:

Quite easy. Just add support for IE 6 and Chrome will automatically be unsupported :speak_no_evil:

**Comment by PVince81** [comment]
Tipsy disappeared completely: https://github.com/owncloud/core/issues/19684
But once it's back, the problem might be back too.

**Comment by PVince81** [comment]
This PR fixes it https://github.com/owncloud/core/pull/19940
