### ISSUE TITLE
Memory exhausted

### ISSUE THREAD

**Issue by fossxplorer** [owncloud/core#18051]
I've started to see the following in the FPM error log:
NOTICE: PHP message: PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 8192 bytes) in /var/www/oc/3rdparty/sabre/vobject/lib/Parser/MimeDir.php

I've increased PHP's memory limit from 256M to 512M, but still getting this error.
Not sure what really triggers it though, but willing to contribute with more debug info when needed.

Versions
stable8.1
PHP 5.5.20

**Comment by MorrisJobke** [comment]
@fossxplorer Is there any change to get the stacktrace of this? Or even the steps to reproduce this? I also have a memory limit of 512M for my php-fpm instance and all is fine.

**Comment by RealRancor** [comment]
> 3rdparty/sabre/vobject

Looks also like related to the contacts app or am i wrong?

**Comment by MorrisJobke** [comment]
@fossxplorer Do you have a big address book?

**Comment by PVince81** [comment]
Very likely to be either calendar or contacts app, nothing in core.
Please raise in the corresponding repo.
