### ISSUE TITLE
.htaccess gets overwritten on update (packages used)

### ISSUE THREAD

**Issue by cwittmer** [owncloud/core#18058]
using packages from obs (8.0.5) ...
.htaccess file is not marked as 'config(noreplace)' in spec file ...
so when you change e.g. upload_max_filesize to 1G, then this will be overwritten on the next update with the default, which is 513MB.
... this is not nice ... :(

**Comment by RealRancor** [comment]
> ... this is not nice ... :(

but the wanted behavior as the .htaccess also contains rewrite-rules which needs to be replaced/updated from time to time.

**Comment by cwittmer** [comment]
then put 'static' stuff (rewriteRules) into the config file e.g. /etc/apache2/conf.d/owncloud
and 'dynamic' stuff into the .htaccess ...

**Comment by RealRancor** [comment]
I can't put anything anywhere ;-)

From what i can see the reorganization of the config files are already tracked here: https://github.com/owncloud/core/issues/10751

**Comment by cwittmer** [comment]
Thank you for referencing ...

**Comment by blizzz** [comment]
Closing  as duplicate as pointed out by @RealRancor 

One hint: I have the same story with Drupal and updating that is even more of a pain. There, I did a patch of my modified .htaccess (and also robots.txt) and apply it after each update (acually have a script that does the ``patch .htaccess /path/to/my/htaccess.patch``, amongst others).
