### ISSUE TITLE
Encryption unusable for shares

### ISSUE THREAD

**Issue by kevinkk525** [owncloud/core#18053]
At the moment i have the problem that if i share a folder with a new user, he can't open any file in it except files that I uploaded after i shared that folder with the user.
This makes the encryption unusable for me.

**Comment by MorrisJobke** [comment]
@schiesbn I guess this is a limitation of the encryption, or am I wrong?

**Comment by schiesbn** [comment]
> At the moment i have the problem that if i share a folder with a new user, he can't open any file in it except files that I uploaded after i shared that folder with the user.

The new user can only open the file if he had a private/public key at the point when you shared the folder with him. If you created the user with the ownCloud user management a key should be created so you should be able to share a file/folder right after the user was created. If the user was created on a external user management (e.g LDAP) the user needs to login at least once to generate his key pair.

If you provide more information I can also try to re-produce it and check if this is a bug or not, please use the issue template for it: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by PVince81** [comment]
Closing due to incomplete information.
See previous comment
