### ISSUE TITLE
database configuration reset

### ISSUE THREAD

**Issue by grexe** [owncloud/core#18056]
may be related to issue #9736

We are using a dockerized ownCloud 8.1. instance (I believe from the official Docker hub registry) and observed some strange behaviour:
Recently, when restarting the docker instance, the database configuration would be reset (in config.php), but other options would remain.
We even _lost_ our MySQL ownCloud database, but never touched it ourselves.

Currently trying with default SQLite, but we could not yet determine the exact cause for this.

**Comment by karlitschek** [comment]
I'm quite sure this is a problem of the docker container or some of the used configurations in the container. Not a lot we can do here from the ownCloud side. 
I suggest to ask this question in the forum at forum.owncloud.org or report back to the developers of the docker container. Thanks a lot.
