### ISSUE TITLE
Replace tipsy with tooltip calls

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#18069]
"Deprecation warning: tipsy is deprecated. Use tooltip instead"

Replace all usage of `$(...).tipsy()` with `$(...).tooltip()` in the Javascript code.

**Comment by MorrisJobke** [comment]
Maybe @Henni want to try it :)

**Comment by MorrisJobke** [comment]
Just have seen that @Henni even moved to `.tooltip()` :)

**Comment by Henni** [comment]
Besides switching to `tooltip()` all the current `tipsy()` calls should be moved out of the central js.js file. (I believe most of them should be part of the files app)

I'll take a look at this.

**Comment by oparoz** [comment]
The first step would be to fix the Files app which doesn't have any tooltips any more since the move to `tooltip()`

**Comment by Henni** [comment]
@oparoz did you notice other issues with the new tooltips?

**Comment by oparoz** [comment]
@Henni - Not yet, no. I do see lots of messages in the browser logs, but it's impossible to trace back.

This give an idea of where to start to look
https://github.com/owncloud/core/search?l=javascript&q=tipsy%28&utf8=%E2%9C%93
