### ISSUE TITLE
v8.1.0: Installation Wizard rejects correct mysql dbusr & dbpwd

### ISSUE THREAD

**Issue by schokobass** [owncloud/core#18066]
Hi, I would like to install OC 8.1.0 in a Host Europe webspace (WebPack 4L with  MySQL 5.5.38-1~dotdeb.0-log and PHP5.5).

I have tried both upload options (by side with setup-owncloud.php, and the .zip). In both cases I get stuck  at the same point when trying to create a MySQL-based installation:

After reaching the page for defining the OC administrator name & pwd, the DB type, and the DB credentials (dbhost, dbusr, dbname, dbpwd), in any case I just get the error message

"MySQL/MariaDB-Benutzername und/oder -Passwort sind nicht gültig Du musst entweder ein existierendes Benutzerkonto oder das Administratorenkonto angeben."

These things I already did test without success:

1.
set the MySQL dbpwd for the global dbusr again -> I am sure that I do type in the correct string;

2.
trying the setup step
a)
for a db object not existing via global db usr (similar to MySQL root usr) and
b)
trying it with an existing db instance with own dbusr & dbpwd (refer to https://doc.owncloud.org/server/8.1/admin_manual/installation/installation_wizard.html#required-settings -> "Storage & Database" -> "The database you want to use must already be installed, and you must have the database administrative user and password for all databases except SQLite, which does not have an admin user. Enter any arbitrary name for the ownCloud Database name. This must be a database that does not already exist." => my point of view: the MySQL runtime environment has to be active, but the database which I will use for OC must not already exist);

3.
at the end, I even tried to install the v8.1.0 tar.bz2 under Ubuntu 14.04 locally confirming to https://doc.owncloud.org/server/7.0/admin_manual/installation/source_installation.html - and ended at exactly the same point.

4.
In the directory /data, no htaccesstest.txt file is to be found. Under Ubuntu 14.04, all file and directory rights are set accordingly to the description in the user manual. I do not get any error message besides the rejection of my MySQL credentials.

I would be very grateful for any suggestion, what could be wrong . . .

**Comment by schokobass** [comment]
addendum #1: Host Europe PHP version is 5.5.27-1~he.0

**Comment by DeepDiver1975** [comment]
Anything in data/owncloud.log ?

**Comment by schokobass** [comment]
Hi DeepDiver1975,

yes: here the owncloud.log content from Host Europe, first:

{"reqId":"DrSS\/kx1P85Tzl2HwLae","remoteAddr":"93.223.111.64","app":"PHP","message":"Undefined offset: 0 at \/is\/htdocs\/wp1153294_8HXHJGLCTN\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#684","level":3,"time":"2015-08-04T20:18:17+00:00"}

{"reqId":"DrSS\/kx1P85Tzl2HwLae","remoteAddr":"93.223.111.64","app":"PHP","message":"touch(): Unable to create file \/is\/htdocs\/wp1153294_8HXHJGLCTN\/www\/owncloud\/data\/owncloud.log because No such file or directory at \/is\/htdocs\/wp1153294_8HXHJGLCTN\/www\/owncloud\/lib\/private\/log\/owncloud.php#53","level":3,"time":"2015-08-04T20:18:17+00:00"}

{"reqId":"ETVtOVxLUW4vH6YnRghz","remoteAddr":"93.223.111.64","app":"PHP","message":"Undefined offset: 0 at \/is\/htdocs\/wp1153294_8HXHJGLCTN\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#684","level":3,"time":"2015-08-04T20:19:38+00:00"}

Best regards!

**Comment by schokobass** [comment]
Hi,

under Ubuntu, the setup now did succeed: I had a look into {oc-path}/data/.htaccess and had to realize that it was missing . . . after touching it and inserting the two lines
----.htaccess----
deny from all
IndexIgnore *
--------------------
, all went well ^^ .

So the question remains why the wizard does not work in the Host Europe webspace . . .

**Comment by schokobass** [comment]
Hi,

inspired by this first success under Ubuntu, I had a look into the {oc-path}/data/.htaccess file on Host Europe webspace. Here is what I found - seems to be the default value, right?

----Hoste Europe FILE .htaccess--------------
# Generated by ownCloud on 2015-08-05 12:13:12
# line below if for Apache 2.4
<ifModule mod_authz_core.c>
Require all denied
</ifModule>

# line below if for Apache 2.2
<ifModule !mod_authz_core.c>
deny from all
Satisfy All
</ifModule>

# section for Apache 2.2 and 2.4
IndexIgnore *
----ENDOF Host Europe FILE .htaccess-----

Well, I just had a try with outcommented lines and only two lines remaining active:
"deny from all" and
"IndexIgnore *"
(as under Ubuntu), but this did not change the situation *sob* . . .

Permissions in {oc-path} are 750 for directories and 640 for files, that should work. But the owner and the group options are less granular than under Ubuntu. At Host Europe, there are only two users/groups: wpxxxxxxx, and ftpxxxxxxx (with wpxxxxxxx as the eqivalent to www-data, I think) - but no option to have an explicit "root" usr/grp . . .

Best regards!

**Comment by schokobass** [comment]
BTW: despite the usr/pwd rejections from today, there are no new entries in {oc-path}/data/owncloud.log

 - best regards!

**Comment by PVince81** [comment]
Please try http://owncloud.org/support

Your case looks more like an environment issue than a bug.
