### ISSUE TITLE
Client keeps asking to trust self signed certificate after it was changed on the server and accepted several times manually

### ISSUE THREAD

**Issue by ET-Bent** [owncloud/core#18060]
### Steps to reproduce

1. Set up OwnCloud server with self signed SSL certificate
2. Set up client with that server
3. Change the SSL certificate on the server
4. Reboot client pc and accept the warning dialogue that the server is using a self signed certificate

### Expected behaviour

Do above steps and accept the warning dialogue once after changing the certificate. Warning dialogue should not reappear after a reboot or restart of the app. App should work normally.

### Actual behaviour

After every restart of the client (PC and/or app) the warning dialogue shows up again and asks the user to confirm. After confirmation everything works as expected.

### Server configuration
**Operating System:** Ubuntu 14.04.2 LTS

**Web server:** Nginx 1.9.3 (https://launchpad.net/~chris-lea/+archive/ubuntu/nginx-devel)

**Database:** MySQL 5.6.24-2+deb.sury.org~trusty+2 (https://launchpad.net/~ondrej/+archive/ubuntu/mysql-5.6)

**PHP version:** PHP 5.5.27-1+deb.sury.org~trusty+1 (cli) (built: Jul 15 2015 12:14:44) (https://launchpad.net/~ondrej/+archive/ubuntu/php5)

**ownCloud version:** 8.0.4 (stable)

**Updated from an older ownCloud or fresh install:** Made all updates from 7.X

**List of activated apps:**
```
Enabled:
 - activity
 - calendar
 - dashboard
 - files
 - files_clipboard
 - files_external
 - files_locking
 - files_pdfviewer
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - files_videoviewer
 - firstrunwizard
 - gallery
 - provisioning_api
 - tasks
 - templateeditor
 - updater
Disabled:
 - external
 - files_encryption
 - user_external
 - user_ldap
 - user_webdavauth
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'XXXXXXXXXXXX',
  'passwordsalt' => 'XXXXXXXXXXXX',
  'secret' => 'XXXXXXXXXXXX',
  'trusted_domains' => 
  array (
    0 => 'SOMEURL'
  ),
  'datadirectory' => 'SOMELOCALPATHONMYSYSTEM',
  'overwrite.cli.url' => 'https://SOMEURL',
  'dbtype' => 'mysql',
  'version' => '8.0.4.2',
  'dbname' => 'owncloud_8',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'XXXXXXXXXXXX',
  'dbpassword' => 'XXXXXXXXXXXX',
  'installed' => true,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'mail_from_address' => 'cloud',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'SOMEURL,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => 0,
);
```

### Client configuration
**Browser:** Google Chrome Version 44.0.2403.125 (64-bit)

**Operating system:** Ubuntu 15.04 (64 bit) latest updates

### Logs

***wont help much here because its most likely client side problem...***

### Formal description

>
Today I changed the SSL certificate on my OwnCloud server. The certificate I use is a self signed one (was self signed one before as well). 
After the change the OwnCloud Client `1.8.4` running on `Ubuntu 15.04` asked me if I trust the certificate after I restarted my computer. I accepted the new certificate and the client started working normal again. 
>
The problem is that it shows the same confirm dialogue every time I reboot my computer or restart the OwnCloud client. It seems like the old certificate is not overwritten by the new one on the client side. The dialogue that pops up is the same that opens up if you setup your client the first time and need to trust the certificate manually.

>What not helps is clicking "Change Account" nor does re-adding the OwnCloud folder help.

**Comment by RealRancor** [comment]
Hi,

the issue tracker of the client is located here: https://github.com/owncloud/client/issues

**Comment by Xenopathic** [comment]
As @RealRancor said, please re-open this issue over at the client repository. Thanks!
