### ISSUE TITLE
Duplicate shared folder keeps generating database entries

### ISSUE THREAD

**Issue by Armada651** [owncloud/core#18071]
### Steps to reproduce
1. Share the folder "Documents" with a group that is already sharing a "Documents" folder.
2. For everyone else in the group "Documents" will show up as "Documents (2)"
3. Watch the server go down.

### Expected behaviour
One database entry that shares the "Documents" folder with the group.

### Actual behaviour
50k entries of the owner sharing "Documents (2)" with every user in the group.

### Server configuration
**Operating system**: Ubuntu Server 14.04

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.5.9-1ubuntu4.11

**ownCloud version:**  8.1.0 (stable)

**Updated from an older ownCloud or fresh install:** Updated from older version

**List of activated apps:** 

Enabled:
 - activity: 2.0.1
 - files: 1.1.9
 - files_locking:
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1

Disabled:
 - calendar
 - contacts
 - encryption
 - external
 - files_external
 - files_versions
 - user_external
 - user_ldap
 - user_webdavauth

**The content of config/config.php:**

  [InvalidArgumentException]
  There are no commands defined in the "config" namespace.

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

**Operating system:** Windows 8.1

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by LukasReschke** [comment]
@icewind1991 @PVince81 Any idea?

**Comment by Armada651** [comment]
I was able to fix this by removing all "Documents (2)" entries from the database. Then by logging in as the owner of the "Documents" I was able to unshare the folder.

If I don't unshare the folder ownCloud will just continue to generate new entries for this share, even if the owner is not logged in and not running a client.

**Comment by PVince81** [comment]
Did you have 7.0.2 on this server at some point and did these shares existed since then up to 8.1.0 ?

Answer (from IRC):  I'm not sure, but that's highly likely, I set this server up in december last year

**Comment by PVince81** [comment]
I tried to reproduce the issue but found another problem.
The server isn't going down in my case but I can imagine that the sync client or other processes might be confused by having the same contents in two directories.

Since I'm not sure whether it's related, I raised it separately: https://github.com/owncloud/core/issues/18075

@Armada651 You might want to check my steps to see whether they match what you observed.

**Comment by PVince81** [comment]
I ran the sync client but it doesn't seem to break the server. It just shows the same contents in both folders. When uploading into one folder, the next sync iteration finds it in the second folder, too.

@icewind1991 @schiesbn

**Comment by PVince81** [comment]
Next up: test with such shares that were created with 7.0.4.

**Comment by PVince81** [comment]
I tried upgrading from 7.0.4 and while the mix up starts appearing after upgrading to 8.0.5, I didn't see any server load issues.

**Comment by Armada651** [comment]
There must be other factors at play that I'm not aware of.

**Comment by PVince81** [comment]
The bug about duplicate contents was fixed: https://github.com/owncloud/core/issues/18075

Now I have no clue how we could find what other factors you had at play that might cause the performance issue.

**Comment by PVince81** [comment]
@Armada651 please try with 8.1.3 which contains some fixes related to oc_share issues

**Comment by PVince81** [comment]
Please try again with 8.1.5 or 8.2.2. If you still have issues, feel free to reopen.
