### ISSUE TITLE
Unable to create new user

### ISSUE THREAD

**Issue by jbyvosges** [owncloud/core#18070]
### Actual behaviour :
Cannot create new user if the name contains one (of more) accent (s). Example " invité" (guest in English)
In database, I leave invite without accent (home::invite) but I put "invité" in others tables
### Server configuration
**Operating system : Ubuntu; Linux x86_64; rv:39.0
**Web server : Apache 
**Database : MySql
**PHP version : 5.5.22
**ownCloud version : 8.1.0

**Comment by DeepDiver1975** [comment]
AFAIK this has already bee reported ...

**Comment by DeepDiver1975** [comment]
@rperezb @SergioBertolinSG I guess you detected this in the past

**Comment by jbyvosges** [comment]
Sorry ...

Le 05/08/2015 12:26, Thomas Müller a écrit :
> AFAIK this has already bee reported ...


-- 
jbyvosges

**Comment by DeepDiver1975** [comment]
> Sorry ...

no worries - I failed to find it myself ;-)

**Comment by rperezb** [comment]
@DeepDiver1975 this one: https://github.com/owncloud/core/issues/14955 ?

**Comment by DeepDiver1975** [comment]
THX @rperezb
