### ISSUE TITLE
 "NaN" appears instead of the count of members of the group in the sidebar when we undo the deletion of a user

### ISSUE THREAD

**Issue by davitol** [owncloud/core#18072]
### Steps to reproduce
1. Create a user in a group
2. Delete the user
3. Undo the deletion

### Expected behaviour
The count of users of members of the group should appear in the sidebar

### Actual behaviour

NaN is shown instead of the count of members of the group in the sidebar

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:"version":"8.1.1.2","versionstring":"8.1.1 RC1"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity: 2.0.1
 - admin_audit: 0.6
 - enterprise_key: 0.1.0
 - files: 1.1.10
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.6
 - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

**Comment by DeepDiver1975** [comment]
Not critical - next major release - since we have no resources within 8.2 -> 8.3
