### ISSUE TITLE
Federated sharing is not allowed for Active Directory users

### ISSUE THREAD

**Issue by davitol** [owncloud/core#18079]
### Steps to reproduce
1. Configure an Active Directory using the wizard in OC
2. Log in with an AD user
3. Try to share a file with a user of other server (federated sharing)

### Expected behaviour
The file is shared

### Actual behaviour

An error message is shown: "Sharing papa.txt failed, because the permissions exceed permissions granted to ... "

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:"version":"8.1.1.2","versionstring":"8.1.1 RC1"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity: 2.0.1
 - admin_audit: 0.6
 - enterprise_key: 0.1.0
 - files: 1.1.10
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.6
 - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

![fedsherr](https://cloud.githubusercontent.com/assets/10596560/9085944/72cab316-3b81-11e5-9df6-c0561be59f99.png)

**Comment by DeepDiver1975** [comment]
Known issue #14043

Here is the fix https://github.com/owncloud/core/pull/14401 - please test - THX

**Comment by PVince81** [comment]
8.1.1 has been released, moving to 8.1.2

**Comment by cmonteroluque** [comment]
@davitol test?

**Comment by davitol** [comment]
@cmonteroluque Here is the fix #14401 ; already tested, but it is needed another reviewer
