### ISSUE TITLE
Queries that run indefinitely 

### ISSUE THREAD

**Issue by fossxplorer** [owncloud/core#18086]
Monitoring the DB after upgrade from 7.0.4 -> 8.0.5->8.1.1 beta2, the following queries run for ever: 
 Copying to tmp table | SELECT `oc_share`.`id`, `item_type`, `item_source`, `item_target`,`oc_share`.`parent`, `share_type`, `share_with`, `uid_owner`,`file_source`, `path`, `file_target`, `oc_share`.`permissions`,`stime`, `expiration`, `token`, `storage`, `mail_send`,`oc_storages`.`id` AS `storage_id`, `oc_filecache`.`parent` as `file_parent` FROM `oc_share` INNER JOIN `oc_filecache` ON `file_source` = `oc_filecache`.`fileid`  AND `file_target` IS NOT NULL INNER JOIN `oc_storages` ON `numeric_id` = `oc_filecache`.`storage`  AND ((`share_type` in ('0', '2') AND `share_with` = 'user99') ) AND `uid_owner` != 'piper' ORDER BY `oc_share`.`id` ASC     | 0.000    |
 Copying to tmp table | SELECT `oc_share`.`id`, `item_type`, `item_source`, `item_target`,`oc_share`.`parent`, `share_type`, `share_with`, `uid_owner`,`file_source`, `path`, `file_target`, `oc_share`.`permissions`,`stime`, `expiration`, `token`, `storage`, `mail_send`,`oc_storages`.`id` AS `storage_id`, `oc_filecache`.`parent` as `file_parent` FROM `oc_share` INNER JOIN `oc_filecache` ON `file_source` = `oc_filecache`.`fileid`  AND `file_target` IS NOT NULL INNER JOIN `oc_storages` ON `numeric_id` = `oc_filecache`.`storage`  AND ((`share_type` in ('0', '2') AND `share_with` = 'user11') ) AND `uid_owner` != 'user77' ORDER BY `oc_share`.`id` ASC

It's been running for 2 days now with some different values for share_with and uid_owner!
Since our filcache is ~10mill records, avoiding such queries that join filecache would be good.

Tried to grep to see where this query comes from, but i couldn't find it.
[me@centos1 core]\# git clone https://github.com/owncloud/core.git -b stable8.1
[me@centos1 core]\# cd core
[me@centos1 core]\# grep -r 'SELECT\.\*\\\*PREFIX\\\*share\.\*IS NOT NULL INNER JOIN\.\*' \*
\#

These queries didn't run for ever on stable7.

## Versions
oc 8.1.1 beta2
PHP 5.5.20 
MariaDB 10.0.0.20

**Comment by PVince81** [comment]
@fossxplorer please retest with this patch https://github.com/owncloud/core/pull/18054

**Comment by fossxplorer** [comment]
@PVince81 i already did it last night and it seems those queries are still being run :(

**Comment by PVince81** [comment]
Do you know how to trigger them ? Is it uploading to a shared folder or simply displaying the list ?

**Comment by fossxplorer** [comment]
Not really. But i can tell you that these queries come from a backend to which i'm only routing the following requests to:
(remote|public).php/(caldav|carddav|webdav)
/status.php 
/ocs/v1.php/cloud/
/ocs/v1.php/apps/files_sharing/api  - this route is JUST FOR ANDROID Clients!
Another
All other requests are routed to another backend which doesn't generate these queries.

I can tell you this based on the query IP info from the DB server.

**Comment by PVince81** [comment]
Can you post a snippet of oc_share so we can see the matching share entries ? (and reshares / parent shares)

**Comment by PVince81** [comment]
@fossxplorer can you try again with 8.1.3 ? There were fixes related to share queries and bogus entries.

**Comment by PVince81** [comment]
With forever did you mean they took a long time ?

Can you try again with 8.2.2 or 9.0 and reopen if this still occurs.
