### ISSUE TITLE
oC's PHPUnit bootstrap does not work with encryption

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#18085]
ownCloud's TestCase comes with some utility methods such as `loginAsUser`, but that doesn't work when encryption is enabled, preventing app devs from easily testing their app with encryption enabled.

When trying to do `$file->putContent('foobar');`
The error message is

> OCA\Encryption\Exceptions\PrivateKeyMissingException: Private Key missing for user: please try to log-out and log-in again

Logging out and back in doesn't help.

@schiesbn @DeepDiver1975 @icewind1991

**Comment by schiesbn** [comment]
Most likely because the loginAsUser() method doesn't trigger the login hooks. In ownCloud <= 8.0 we had a extra login helper for the encryption tests which make sure that the hook gets executed, see https://github.com/owncloud/core/blob/stable8/apps/files_encryption/tests/testcase.php#L21

I don't know the loginAsUser() code out of my head. But I think it need to be changed in a way that it makes sure that (a) all hooks are registered and (b) the login hooks get emitted.

**Comment by oparoz** [comment]
@schiesbn You're right
https://github.com/owncloud/core/blob/master/tests/lib/testcase.php#L200-L208
It seems it's missing

```
		if ($loadEncryption) {
			$params['uid'] = $user;
			$params['password'] = $password;
			\OCA\Files_Encryption\Hooks::login($params);
		}
```

**Comment by schiesbn** [comment]
@oparoz yes, but this was for the old encryption. The exact same method no longer work. I think a more generic solution which makes sure that the hooks from all enabled apps are loaded and then emit the login hooks in loginAsUser() would make more sense. Similiar to what we do during the real login: https://github.com/owncloud/core/blob/master/lib/private/user/session.php#L215

**Comment by PVince81** [comment]
From what I understood after discussing with @schiesbn is that this is not critical for 8.2.1 and more a nice to have (and not directly a bugfix).

@cmonteroluque can we move this to 9.0 ?

**Comment by cmonteroluque** [comment]
done

**Comment by icewind1991** [comment]
https://github.com/owncloud/core/blob/master/tests/lib/traits/encryptiontrait.php can be used to create tests with encryption enabled

**Comment by PVince81** [comment]
would likely be better to test encryption with integration tests instead of unit tests
