### ISSUE TITLE
Cron runs for ever

### ISSUE THREAD

**Issue by fossxplorer** [owncloud/core#18087]
### Steps to reproduce
1.Upgrade from 7.0.4 -> 8.0.5->8.1.1 beta2 and enable system cron
Check that lock file exists in /tmp/owncloud-server-513a1eb54g123-cron.lock.

### Expected behaviour
oC cron runs without any issues and exits after executing jobs from oc_jobs
### Actual behaviour
Cron runs for ever and never exits.
__The oc_jobs table has grown to ~ 28000 records after the upgrade, which i find strange.__ 

### Server configuration
**Operating system**:
CentOS 6.6
**Web server:**
Nginx 
**Database:**
MariaDB 10.0.20
**PHP version:**
PHP 5.5.20 
**ownCloud version:** (see ownCloud admin page)
8.1.1 beta2

**Updated from an older ownCloud or fresh install:**
updated from 7.0.4
**List of activated apps:**
$ ./occ app:list
Enabled:
 - activity: 2.0.1
 - bookmarks: 0.4
 - calendar: 0.7.2
 - contacts: 0.4.0.0
 - documents: 0.10.0
 - files: 1.1.10
 - files_external: 0.2.3
 - files_odfviewer: 0.1
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - galleryplus: 14.0.0
 - mozilla_sync: 1.4
 - music: 0.3.7
 - news: 5.3.9
 - notes: 1.1.0

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => '123e1dc54b123',
  'passwordsalt' => 'ffe9sfdsfsdfsfdsdfsdfsdfsdf6f3e3d5',
  'datadirectory' => '/var/data/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.1.1.1',
  'dbname' => 'owncloud',
  'dbhost' => '192.168.1.100',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'pass',
  'installed' => true,
  'loglevel' => '2',
  'mail_smtpauth' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'mail.server.com',
  'mail_smtpname' => 'mail@server.com',
  'mail_smtppassword' => 'pass',
  'mail_smtpport' => '587',
  'mail_domain' => 'server.com',
  'maintenance' => false,
  'tokenInfoEndpoint' => 'https://www.googleapis.com/oauth2/v1/tokeninfo',
  'custom_csp_policy' => 'default-src \'self\'; script-src \'self\' \'unsafe-eval\'; style-src \'self\' \'unsafe-inline\'; frame-src *; img-src *; font-src \'self\' data:; media-src *',
  'xframe_restriction' => true,
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/vhosts/owncloud/apps',
      'url' => '/apps',
      'writable' => true,
    ),
    1 => 
    array (
      'path' => '/var/www/vhosts/owncloud/apps3',
      'url' => '/apps3',
      'writable' => true,
    ),
    2 => 
    array (
      'path' => '/var/www/vhosts/owncloud/apps2',
      'url' => '/apps2',
      'writable' => true,
    ),
  ),
  'singleuser' => false,
  'theme' => 'owncloud',
  'enable_previews' => true,
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'preview_max_scale_factor' => 1,
  'preview_max_x' => NULL,
  'preview_max_y' => NULL,
  'enabledPreviewProviders' => 
  array (
	 0 => 'OC\\Preview\\PNG',
	 1 => 'OC\\Preview\\JPEG',
	 2 => 'OC\\Preview\\GIF',
	 11 => 'OC\\Preview\\Illustrator',
	 12 => 'OC\\Preview\\Postscript',
	 13 => 'OC\\Preview\\Photoshop',
	 14 => 'OC\\Preview\\TIFF',
	 15 => 'OC\\Preview\\Raw',
	 16 => 'OC\Preview\Office',
	 17 => 'OC\Preview\OpenDocument',
	 ),
  'enable_avatars' => true,
  'forcessl' => true,
  'trusted_domains' => 
  array (
    0 => 'server.com',
  ),
  'secret' => '2ef0bdfa2a2sdfsdffsdfsdfsdfsd6aa28dd5asfdsdfsdfsdfsdfsdfsdfdsfdsfsdfsdfe5fe5c06e',
  //'share_folder' => '/Shared',
  'trashbin_retention_obligation' => 30,
  'trashbin_auto_expire' => true,
  'log_rotate_size' => 1048576000,
  'memcache.local' => '\\OC\\Memcache\\APCu',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
yes, users use Google Drive, Dropbox, SFTP, FTP and WebDAV
**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

#### ownCloud log (data/owncloud.log)
Nothing in the oC log related to this issue. 

FYI: i also did turn off the cron and manually ran cron.php, it ran for ~24H without exiting. 

Obviously something is wrong here.

**Comment by karlitschek** [comment]
Can you post a full bug report using the issue template? 
https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by fossxplorer** [comment]
Updated. Thx!

**Comment by fossxplorer** [comment]
The reason oc_jobs is getting bigger is due to files_trashbin and files_version cleanup commands being scheduled. So this is more or less expected for a bigger installation i guess.

**Comment by fossxplorer** [comment]
Update: tried to run the cron.php manually again and after 2 days i got
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 32 bytes) in /var/www/vhosts/oc/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 128.

It's obvious that the cron.php isn't quitting as it should and runs out of allowed memory size of 1GiB.

**Comment by MorrisJobke** [comment]
Trashbin jobs are deduplicated with https://github.com/owncloud/core/pull/20790
Version jobs with https://github.com/owncloud/core/pull/21109
