### ISSUE TITLE
Sharing a folder that contains a shared filed is not possible

### ISSUE THREAD

**Issue by davitol** [owncloud/core#18080]
### Steps to reproduce
1. Share a file with a user of another server
2. Move the file into a Folder
3. Try to share the folder with a user of other server (federated sharing)

### Expected behaviour
The folder is shared

### Actual behaviour

The folder cannot be shared due to it contains a file shared with me. (But the single file can be shared)

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:"version":"8.1.1.2","versionstring":"8.1.1 RC1"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity: 2.0.1
 - admin_audit: 0.6
 - enterprise_key: 0.1.0
 - files: 1.1.10
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.6
 - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

**Comment by davitol** [comment]
A bug, an enhacement or it is the expected behaviour?

**Comment by MorrisJobke** [comment]
@davitol Bug and known as #13695 -> close this one
