### ISSUE TITLE
Unable to set sub-shared folder's permission correctly

### ISSUE THREAD

**Issue by KKyang** [owncloud/core#18092]
### Steps to reproduce

This is how my folder looks, a folder named **shared A** with folder **A**, **B** inside.
![5](https://cloud.githubusercontent.com/assets/2676255/9102359/c86c5dcc-3c23-11e5-94db-7a8d18f81563.png)

**Case 1**
Now I'm going to share it to user **DummyCat** and start setting the permission from folder **shared A**
1. Set the permission to read only.
![6](https://cloud.githubusercontent.com/assets/2676255/9102383/fca55be8-3c23-11e5-864a-b1ffb970453e.png)
1. Then I navigate inside the folder **shared A**, I cannot change the permission of folder **A** for **DummyCat**. The name didn't show up.
   ![7](https://cloud.githubusercontent.com/assets/2676255/9102392/1080279c-3c24-11e5-8308-d834787fe9c7.png)

**Case 2**
This time, I'll setup the permission start from folder **A**, then the folder **shared A**
1.  I was able to set the permission correctly. But when **DummyCat** logs into his account, he'll see two folders in his explorer.
![8](https://cloud.githubusercontent.com/assets/2676255/9102424/9032ea1a-3c24-11e5-8c21-2813720bebf0.png)
![9](https://cloud.githubusercontent.com/assets/2676255/9102433/c18dfb5e-3c24-11e5-97ff-6a81ef22c4d0.png)

![10](https://cloud.githubusercontent.com/assets/2676255/9102452/f2e266a4-3c24-11e5-8528-78b57da80f6e.png)
### Expected behaviour

I'm able to set the permission coreectly without duplicated folders.
### Actual behaviour

In case 1, I failed to set the permissions for the sub folders.
In case2, when **DummyCat** logs into his account, he'll see two folders in his explorer.
![10](https://cloud.githubusercontent.com/assets/2676255/9102457/0ec3a8c4-3c25-11e5-98db-4c009746e1c6.png)
### Server configuration

**Operating system**:
Ubuntu 14.04
**Web server:**
Apache 2.4.7
**Database:**
MySQL
**PHP version:**
5.5.9
**ownCloud version:** (see ownCloud admin page)
8.1.0
**Updated from an older ownCloud or fresh install:**
from 8.0.4
**List of activated apps:**
default settings

**Comment by KKyang** [comment]
https://github.com/owncloud/core/issues/18025

**Comment by PVince81** [comment]
Case 1: Changing sub-folder permissions was never supported, this would be a feature request.

Case 2: looks more like a workaround. By sharing the parent folder you're basically creating a second share, that's why the recipient sees it twice. Not sure if such operation should be allowed.

**Comment by PVince81** [comment]
@schiesbn

**Comment by Kawohl** [comment]
originally mentioned in :  https://github.com/owncloud/core/issues/18025

**Comment by PVince81** [comment]
@rullzer

**Comment by rullzer** [comment]
Yep this is currently not possible. This would require us to for each entry in the current dir check if it is shared with us. And if so update permissions. This won't scale. Just think about a folder with 1k entries.

Currently I see no way we can make this work (efficiently).
