### ISSUE TITLE
Exception error during 8.1.0 update

### ISSUE THREAD

**Issue by Feodore** [owncloud/core#18093]
Hi,

Got the following error when trying to run 8.1.0 update:

Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'DELETE FROM `oc_music_scanned_users`;': SQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.oc_music_scanned_users' doesn't exist

Thanks in advance

**Comment by LukasReschke** [comment]
@MorrisJobke

**Comment by MorrisJobke** [comment]
Looks like some version mixup. @Feodore How did you installed the music app?

**Comment by Feodore** [comment]
I have installed the music app using the OC web interface: logged in as admin and then enabled the musuc app. The strangest thing is that I had already 8.1.0 installed - why did I get this prompt to update to 8.1.0?

**Comment by RealRancor** [comment]
> why did I get this prompt to update to 8.1.0?

I think because of this: https://github.com/owncloud/core/issues/14977

**Comment by Feodore** [comment]
Thanks for the hint. I have read all messages in the thread, but I could not find instructions about what to do to fix the issue. What shall I do to fix this?

**Comment by RealRancor** [comment]
This is not directly related to your initial problem. Thats why i've only quoted your question why you're getting a prompt to update to 8.1.0 on app installation.

**Comment by MorrisJobke** [comment]
@Feodore Should be fixed with https://github.com/owncloud/music/commit/1246243cefb0620571ad0c12b55d20ecaebead0b

**Comment by freakyy85** [comment]
i got the same problem. 
ownCloud or one of the apps require upgrade - only a limited number of commands are available
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Updating <music> ...
Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'DELETE FROM `oc_music_scanned_users`;':

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.oc_music_scanned_users' doesn't exist
Update failed
Maintenance mode is kept active

**Comment by RealRancor** [comment]
@freakyy85 Please use a current version of the music app (v0.3.7) which should already include a fix for this (See https://github.com/owncloud/core/issues/18093#issuecomment-130460383)

If this still doesn't fix your issue create a new issue at https://github.com/owncloud/music/issues and fill out the issue template (https://github.com/owncloud/music/blob/master/CONTRIBUTING.md#short-version) when doing so.
