### ISSUE TITLE
JS TypeError when deleting user

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#18099]
You get a JS error after having deleted a user
`TypeError: result is undefined deleteHandler.js:197:0`

Not sure who deals with this. @PVince81 ?

**Comment by PVince81** [comment]
@blizzz @MorrisJobke

**Comment by MorrisJobke** [comment]
The response is empty and doesn't have an status included anymore. We need to check the status code here.

**Comment by MorrisJobke** [comment]
Fix is in #18114
