### ISSUE TITLE
Encryption warning does not work on "personal" page

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#18098]
This is what I get when reaching settings/personal on master
`TypeError: OC.Encryption.displayEncryptionWarning is not a function`

@schiesbn

**Comment by schiesbn** [comment]
This happens only on the personal settings page...

@PVince81 any idea why this happens? The js file is loaded (https://github.com/owncloud/core/blob/master/apps/encryption/js/encryption.js), so why does the call at L36 works on all pages expect the personal settings page?

**Comment by PVince81** [comment]
Maybe the personal page doesn't load the JS containing the displayEncryptionWarning function ?
Note that some apps need to load JS in appinfo/app.php which makes the script available in **all** pages. There is currently no way around this.

The script should be adapted to first test if that function exists.
Or the other script containing the actual function should be loaded too.

**Comment by PVince81** [comment]
Hmmm I see the method is actually in the same file... very strange.

**Comment by PVince81** [comment]
Ok got it. It seems there is another JS file that overwrites the namespace instead of extending it.
I'll have a look.

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/18106

**Comment by schiesbn** [comment]
fix was merged for 8.2
