### ISSUE TITLE
[8.1.1. RC1 Community package] Waiting too long for federated sharing.

### ISSUE THREAD

**Issue by davitol** [owncloud/core#18107]
### Steps to reproduce

1. Share a file from 8.1.1 RC1 version ("version":"8.1.1.2","versionstring":"8.1.1 RC1") to another server (fed.sharing)

### Expected behaviour

The file is shared.

### Actual behaviour

A spinner appers and the share takes a huge amount of time. Finally after several minutes, the file appears.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:"version":"8.1.1.2","versionstring":"8.1.1 RC1"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity: 2.0.1
 - admin_audit: 0.6
 - enterprise_key: 0.1.0
 - files: 1.1.10
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.6
 - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

**Comment by rperezb** [comment]
cc @DeepDiver1975 please check this one

**Comment by rperezb** [comment]
Hey @Xenopathic the label packaging was added because it has been reproduced with the package, with the tar.ball was not reproduced

**Comment by PVince81** [comment]
@rperezb the label "packaging" is for packaging-related issues

**Comment by PVince81** [comment]
Possible duplicate / related to the known performance issues: https://github.com/owncloud/core/issues/13882

**Comment by PVince81** [comment]
@davitol if the server is in the same intranet it shouldn't take that long. Where was the remote server ?

**Comment by davitol** [comment]
@PVince81 I was using a OC local installation using vagrant for the 'serverA', and a docker container for 'serverB'.

**Comment by DeepDiver1975** [comment]
I would suspect some side effects within the setup to be responsible for this.

**Comment by jancborchardt** [comment]
@schiesbn cc'ing you for federated sharing. Any idea here?

Or is this resolved and can we close?

**Comment by davitol** [comment]
@jancborchardt I think we can close it. It seems not to be further reproduce
