### ISSUE TITLE
Frond-End -Wrong count of users 

### ISSUE THREAD

**Issue by karthikjaps** [owncloud/core#18100]
hi , i have an problem in owncloud front page , while i check the count in owncloud user , its show wrong 

i check the table "oc_storages"   i see  users like ,,,,, example  :karthik ,  karthik_2355  , karthik_567334 , any idea why this occurs ? 

Then ,  i delete all wrong user like  karthik_2355 , karthik_567334 , but in front page show wrong , Anyone face this issue ?

**Comment by LukasReschke** [comment]
Thanks a lot for reporting issues back to us!

We need some more information to properly support you with your issue!

Can I ask you to follow our guidelines for submitting bugs as described here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md
