### ISSUE TITLE
Always save/restore the data folder when PHPUnit is used

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#18101]
When testing an app, the data folder gets wiped. I suggest it gets moved aside and restored when the tests have completed.
That way, we wouldn't have to maintain a separate setup just for automated tests. We can keep the data we need to perform behavioural or user testing

I'm sure there is a way we could add this to custom app boostraps, but I don't think it would do any harm to make this the default behaviour.

**Comment by Xenopathic** [comment]
How do you test your app? `autotest.sh` sets up a completely fresh environment, with separate DB and data folder...

**Comment by oparoz** [comment]
As described in the App developer [documentation about unit testing](https://doc.owncloud.org/server/8.1/developer_manual/core/unit-testing.html) and in [the tutorial](https://doc.owncloud.org/server/8.1/developer_manual/app/tutorial.html)

`phpunit tests/testaddtwo.php`
`phpunit --bootstrap tests/bootstrap.php apps/myapp/tests/testsuite.php`
`phpunit -c phpunit.integration.xml`

You get the idea.

The doc stipulates that  `autotest.sh` is

> a script that runs all the core unit tests

which app devs don't want.

**Comment by Xenopathic** [comment]
There's actually no reason why you can't use `autotest.sh` for app testing: pass it a path to the file you want to test like so: `./autotest.sh db-type ../apps/myapp/tests/mytest.php`. Then you get all the benefits that `autotest.sh` brings, without running any core tests. You will need to enable the app in `tests/bootstrap.php` though.

That actually gives me quite a good idea - perhaps we should support passing an entire directory to `autotest.sh`, such that it tests that particular app? It would enable the app automatically too, saving the hassle of modifying the bootstrap file. Thoughts? cc @LukasReschke @MorrisJobke @PVince81

**Comment by oparoz** [comment]
I've just tried on a single test and it can't find the parent classes it needs to run (because the app is not enabled yet), which means that each test class would have to include bootstrap.php. Not very convenient.

Maybe the solution is to provide the same script, but for apps. I guess you would have used PHP and added it in the bootstrap if that was possible to do it that way.

**Comment by MorrisJobke** [comment]
No. Please don't use autotest to run apps unit tests. Autotest fires up a whole new instance and is therefore more an integration test than a unit test. Running plain php unit is totally fine
