### ISSUE TITLE
Documentation on how to install Google Drive as external storage is outdated

### ISSUE THREAD

**Issue by jzee** [owncloud/core#18112]
Documentation refers to Drive SDK which Google no longer offers. 
From https://github.com/owncloud/client/issues/3544 one could think that push notifications need to be added for proper synchronization with OC but it is unclear if this is required and how this would have to be properly configured.

**Comment by RealRancor** [comment]
Hi,

the issue tracker for the docs is located here: https://github.com/owncloud/documentation/issues

There you can find an existing issue about gdrive: https://github.com/owncloud/documentation/issues/1127
