### ISSUE TITLE
[feat] Upload from URL

### ISSUE THREAD

**Issue by szepeviktor** [owncloud/core#18111]
It would be nice to have an app that downloads a file from a URL directly to ownCloud.

Idea: https://www.urldroplet.com/

**Comment by aspdye** [comment]
Does already exist ;) its called ocdownload. You can Download via http(s), youtube, ftp(s) and bittorrent.

https://apps.owncloud.com/content/show.php/ocDownloader+%28NG%29?content=169974&PHPSESSID=aj72tspaac9g1tumcq04j09e91

**Comment by szepeviktor** [comment]
Thank you very much.

https://github.com/DjazzLab/ocdownloader
