### ISSUE TITLE
Folder of downloaded app is empty

### ISSUE THREAD

**Issue by michag86** [owncloud/core#18116]
### Steps to reproduce
1. login as admin
2. go to Apps
3. add documents or search lucene

### Expected behaviour
app should be installed and enabled
### Actual behaviour
under /apps/ is an empty folder with the appid created

### Server configuration
**Operating system**: CentOS 7.1
**Web server:** Apache
**Database:** MariaDB
**PHP version:** 5.4.16
**ownCloud version:** 8.1.0
owncloud is installed from repository 

**Updated from an older ownCloud or fresh install:** fresh install
**List of activated apps:**
[root@host]# sudo -u apache php /var/www/html/owncloud/occ app:list
Enabled:
 - files: 1.1.9
 - files_antivirus: 0.7.0.1
 - files_locking:
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1

Disabled:
 - activity
 - calendar
 - contacts
 - encryption
 - external
 - files_external
 - files_videoviewer
 - firstrunwizard
 - user_external
 - user_ldap
 - user_webdavauth

#### ownCloud log (data/owncloud.log)
```
{"reqId":"VcSJiPl3dtmj@2s@S5ha4wAAAAM","remoteAddr":"172.31.245.101","app":"core","message":"No update found at the ownCloud appstore for app 166055","level":1,"time":"2015-08-07T12:33:44+02:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"VcSJiPl3dtmj@2s@S5ha4wAAAAM","remoteAddr":"172.31.245.101","app":"core","message":"No update found at the ownCloud appstore for app 166056","level":1,"time":"2015-08-07T12:33:45+02:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"VcSJiPl3dtmj@2s@S5ha4wAAAAM","remoteAddr":"172.31.245.101","app":"core","message":"No update found at the ownCloud appstore for app 166049","level":1,"time":"2015-08-07T12:33:45+02:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"VcSJiPl3dtmj@2s@S5ha4wAAAAM","remoteAddr":"172.31.245.101","app":"core","message":"No update found at the ownCloud appstore for app 166051","level":1,"time":"2015-08-07T12:33:45+02:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
```

**Comment by DeepDiver1975** [comment]
@michag86 there should be some more error messages

**Comment by michag86** [comment]
That is everything I can find. I purged the logfile before installing/enabling the app.
Loglevel is set to debug.
In apache error log are no errors generated.

**Comment by michag86** [comment]
After enabling the app it is not listed under enabled. But when I go to the productivity category I can see Documents as enabled. If I disable and reenable, this is logged:
```
{"reqId":"VcSwYsDSvZRE7eNRTuBZ8gAAAAI","remoteAddr":"172.31.245.101","app":"core","message":"App directory already exists","level":3,"time":"2015-08-07T15:19:33+02:00","method":"POST","url":"\/index.php\/settings\/ajax\/enableapp.php"}
```

I've noticed that the file is downloaded to the php tmp Folder:
```
insgesamt 9252
-rw-------. 1 apache apache       0  7. Aug 16:20 oc_tmp_iJx9sJ
-rw-------. 1 apache apache 9469483  7. Aug 16:20 oc_tmp_iJx9sJ-.zip
-rw-------. 1 apache apache       0  7. Aug 16:20 oc_tmp_rBO6cQ
drwxr-xr-x. 3 apache apache    4096  7. Aug 16:20 oc_tmp_rBO6cQ-folder
```
They stay there only for a short moment.

**Comment by michag86** [comment]
https://github.com/owncloud/core/blob/v8.1.0/lib/private/installer.php#L109
Installer copys extractfolder/appid
In my case this is search_lucene and documents.
But the the archives from apps.owncloud.com contain folders like "search_lucene-8.1.0" and "documents-stable8.1"

**Comment by DeepDiver1975** [comment]
@VicDeo did you upload these apps recently? Looks like the zips have a wrong internal format.

General rule of thumb: test what you do! :imp:

**Comment by RealRancor** [comment]
Ref for the issue reported some time ago ad the issue tracker: https://github.com/owncloud/documents/issues/508

**Comment by VicDeo** [comment]
@DeepDiver1975 
A) it was not me but @karlitschek who published it.
B) Appstore doesn't allow to publish _packages_ for different OC version but 1 package and everything else should be put as  as links. Currently we have a package for 8.0  and a link to stable8.1 branch.

**Comment by VicDeo** [comment]
and I have no idea who and in which manner published search_lucene. 
This comment was regarding documents app ^^

**Comment by michag86** [comment]
search_lucene for 8.1.0 is a github link too. Download for all other versions is a package.
In this way, the integrated store is useless for applications with different version located on github.

**Comment by DeepDiver1975** [comment]
Sorry vicdeo for suspecting you.

Its not useless - one simply need to upload aproper ZIP to github releases.

**Comment by karlitschek** [comment]
@DeepDiver1975 @VicDeo now I'm also confused. :-)  Both apps.owncloud.com entries (documents and search_lucene) have entries for 8.1 that point to the proper github zip. Shouldn't this be correct?
What is missing? :-)

**Comment by LukasReschke** [comment]
@karlitschek Packaged apps needs to contain a folder same as the app id. So for example "documents".

The one downloaded here from GitHub from branches is however "appid-branch". This makes the installation go wrong as the extraction fails. - We can't thus link to branches on GitHub.

**Comment by RealRancor** [comment]
@karlitschek 

Have a look at the 8.1 version of calendar:

https://apps.owncloud.com/content/show.php/Calendar?content=168707

which downloads refers to:

https://github.com/owncloud/calendar/releases/download/v0.7.2/calendar.zip

where the 8.1 downloads of search_lucene and documents are referring to:

https://github.com/owncloud/search_lucene/archive/v8.1.0.zip
https://github.com/owncloud/documents/archive/stable8.1.zip

The whole difference is the release page of the apps:

https://github.com/owncloud/calendar/releases

vs

https://github.com/owncloud/search_lucene/releases
https://github.com/owncloud/documents/releases

**Comment by LukasReschke** [comment]
Note: I'm not talking about the ZIP name but about the name of the zipped folder.

**Comment by LukasReschke** [comment]
@RealRancor is right. With tagged releases it *should* work.

**Comment by RealRancor** [comment]
Mhhh, but search_lucene and documents are also tagged or am i wrong? So its really only the content of the archive?

**Comment by LukasReschke** [comment]
They are tagged but take a look at the link. They are pointing to the raw Git download instead to the release. (/archive/ vs /releases/)

Tagged release:

https://github.com/owncloud/calendar/releases/download/v0.7.2/calendar.zip

Raw download:

https://github.com/owncloud/documents/archive/stable8.1.zip

Raw downloads always have the branch name in the downloaded folder which is what breaks things here.

**Comment by karlitschek** [comment]
Got it. :-) I updated both and I hope it works now.

**Comment by RealRancor** [comment]
At least documents are now linking:

https://github.com/owncloud/documents/archive/v8.1.1.zip

which contains a "documents-8.1.1" folder instead of a plain "documents" one. With that the issue is still there.

**Comment by karlitschek** [comment]
grmpf. @DeepDiver1975 @LukasReschke any advise what to do here? Didn't this work in the past?

**Comment by LukasReschke** [comment]
> grmpf. @DeepDiver1975 @LukasReschke any advise what to do here? 

Yes.

> Didn't this work in the past?

No. https://github.com/owncloud/documents/archive/v8.1.1.zip leads to a ZIP that has no subfolder. This is a different method than used at https://github.com/owncloud/calendar/releases/.

Take a look at https://github.com/owncloud/calendar/releases/ and https://github.com/owncloud/documents/releases, as you can see these are different. You need to manually draft a release by clicking:

1. "Draft a new release"
2. Choosing 8.1.1
3. Download 8.1.1 and ZIP it within a folder called "documents"
4. Upload the resulting ZIP
5. Publish the release

As you can see at https://github.com/owncloud/documents/releases/tag/v8.1.1 you do now have an additional "documents.zip", you can link to that one: https://github.com/owncloud/documents/releases/download/v8.1.1/documents.zip

This should work. I already updated the entry in the appstore.

**Comment by LukasReschke** [comment]
Note: This has the implication that really everybody that has contributor permissions on GitHub (i.e. the half world) can edit the ZIP and run arbitrary code on ownCloud instances.

**Comment by LukasReschke** [comment]
By the way, while it worked in mine and @PVince81's testing I'd appreciate if somebody else could confirm as well.

**Comment by jancborchardt** [comment]
> Packaged apps needs to contain a folder same as the app id.

This is definitely a requirement we need to remove so people can more easily publish apps. You should be able to just link to the Github release. @karlitschek can you fix that in the appstore?

**Comment by LukasReschke** [comment]
> This is definitely a requirement we need to remove so people can more easily publish apps. You should be able to just link to the Github release. @karlitschek can you fix that in the appstore?

That's not something we can fix in the appstore. This is something that the core handles. The appstore just does content-delivery.

**Comment by LukasReschke** [comment]
See also https://github.com/owncloud/core/pull/18159 for some more help for devs.

**Comment by RealRancor** [comment]
documents is working now: https://github.com/owncloud/documents/issues/508#issuecomment-129469812

**Comment by michag86** [comment]
What about changing the rule to: 
Packaged apps needs to contain a folder **starting** with the app id
?

This will make it possible to use the github archives as they are.


```
$extractDir = glob($extractDir . '/' . $info['id'] . '*', GLOB_ONLYDIR)[0]
```
This will return the first directory starting with the appid. It's also possible to check if there is only one directory that matches.

**Comment by LukasReschke** [comment]
Sounds good. @michag86 mind opening a PR?

**Comment by oparoz** [comment]
@LukasReschke - It won't work as translations need the folder to be named exactly like the appid.

**Comment by michag86** [comment]
This can be closed. documents app package is refreshed.
For search_lucene I've opened another issue:
https://github.com/owncloud/search_lucene/issues/99
