### ISSUE TITLE
Avatar cropper default size is smaller than full image

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#18113]
This is especially annoying for profile images in Contacts where you need to adjust the manual cropper nearly every time.

Compare how it initially shows you:
![capture du 2015-08-05 22-47-55](https://cloud.githubusercontent.com/assets/925062/9131543/d3cd0b02-3cec-11e5-870d-061263e24cb3.png)

And how you adjust it / how you expect it to be by default:
![capture du 2015-08-05 22-48-16](https://cloud.githubusercontent.com/assets/925062/9131542/d3ccee4c-3cec-11e5-93c4-0998229897f0.png)

Of course the required dimensions (like square) should be taken into account, so it’s fine to cut off a landscape photo. In that case the cropper should always be centered on the image (cause that’s where the subject is likely going to be).

**Comment by noveens** [comment]
@PVince81 ,
close the issue?

**Comment by PVince81** [comment]
Protip: in your next PR use the text "Fixes #18113" (replace with issue name).
Then when the PR is merged, Github will automatically close the issue 😄
