### ISSUE TITLE
Dropdown bubble pointer missing right border

### ISSUE THREAD

**Issue by Bullnados** [owncloud/core#18137]
The whole dropdown has a dark border/line around. But the right edge of the pointer doesnt have that dark border/line.
See #17709

**Comment by karlitschek** [comment]
@PVince81

**Comment by Bullnados** [comment]
Ah forgot.
@jancborchardt meant to open New issue

**Comment by jancborchardt** [comment]
We fixed this by getting rid of the border altogether.
