### ISSUE TITLE
data/owncloud.db not encrypted.

### ISSUE THREAD

**Issue by hellmachine2000** [owncloud/core#18133]
Hi,
the whole database with addresses and calendars is not encrypted while being in an ecrypted oc environment. Opening with a text editor shows all data. I never expected this and it is shocking!
Is this an error?

Any insights?

Best regards,
Marc

**Comment by karlitschek** [comment]
Databases are not encrypted. If a hacker has access to the server and can access all files, code and databases then the data is exposed. This is how it is. You need to protect your server against unauthorized access from the outside.

**Comment by hellmachine2000** [comment]
Well, this doesn't help with a shared host. This should really be documented, because it is mission critical for users who want all data to be encrypted.

**Comment by RealRancor** [comment]
Read the documentation of the encryption app, there the purpose of the app is documented
