### ISSUE TITLE
Update Exception: no info.xml 

### ISSUE THREAD

**Issue by partnerwerk** [owncloud/core#18136]
When updating to version 8.1.0 I receive an error message:
Exception: Die Applikation enthält keine info.xml Datei
Translates to: The application does not contain a info.xml file

What do I have to do in order to make the update complete?

**Comment by karlitschek** [comment]
Can you post a full bug report using the bug template please?
https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by partnerwerk** [comment]
Thank you for your quick reply. Actually I cannot post a full report. I retried the update and it went through without errors.
