### ISSUE TITLE
Cannot delete as recipient files that have versions

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#18132]
### Steps

1. Enable encryption
1. Create two users "user1" and "user2"
1. Login as "user2"
1. Create folder "test"
1. Share "test" with "user1"
1. Login as "test1"
1. Create a file "test/versions.txt"
1. Edit the file several times to create versions
1. Delete the file

### Expected result
Successful deletion

### Actual result
Cannot delete

```
{"reqId":"itR1UfaeJ7gBt+j3yDEq","remoteAddr":"127.0.0.1","app":"no app in context","message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","level":3,"time":"2015-08-07T16:09:14+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files\/ajax\/delete.php"}
```

### Versions
Observed on 8.2 pre-alpha git master cf532247e04a25fac776616a3a0ad5a5eebe8019

@schiesbn

**Comment by PVince81** [comment]
Also broken on stable8.1.

**Comment by tflidd** [comment]
You have to reshare the folder after the key for user test1 were created at his first login (step 6). Step 6 must be before step 5.

**Comment by PVince81** [comment]
@tflidd not really because the keys for user "user1" were already created at the time the admin created them. Your comment only applies if "user1" existed before encryption was enabled. :smile:

**Comment by PVince81** [comment]
also broken in v8.1.0, but works in v8.0

This is a regression from v8.0 introduced by the new encryption.

@schiesbn please have a look

**Comment by PVince81** [comment]
@schiesbn any update on this regression ?
