### ISSUE TITLE
Root view getDirectoryContent missing entries after moving data folder

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#18134]
Remember that the oc_storages table had a mysterious remaining "local::" entry that points to the data directory. It seems that it is used when creating a root view and calling getDirectoryContent.
After moving the data folder, it doesn't properly rescan the new storage.

### Steps

1. Setup OC
1. Create a user "user1"
1. Login as "user1"
1. Upload some files
1. Create a root view and call `$rootView->getDirectoryContent('')`
1. Enable maintenance mode
1. Move the data directory to a new location, including contents
1. Change config.php to point to the new location
1. Disable maintenance mode
1. Create a root view and call `$rootView->getDirectoryContent('')`

### Expected result
Result set of second call contains same files as with first call.

### Actual result
Second call doesn't contain all files.
It seems that it didn't rescan.

### Versions
ownCloud 8.2 pre-alpha git master (78203ecc2ffffd9e26e117223d3e7533e52938ea)

This breaks some of the encryption migration code https://github.com/owncloud/core/pull/17899 which relies on a root view to find all user's homes.
There might be other parts of code that rely on it.

```
MariaDB [owncloud]> select * from oc_storages;
+---------------------------------------+------------+
| id                                    | numeric_id |
+---------------------------------------+------------+
| home::root                            |          1 |
| home::user1                           |          3 |
| home::user2                           |          4 |
| local::/srv/www/htdocs/owncloud/data/ |          2 |
| local::/srv/www/ocdata/               |          5 |
+---------------------------------------+------------+
5 rows in set (0.00 sec)
```

The new cache with id 5 doesn't contain any of the user folders, it probably didn't properly scan.

For now I suggest to always the user manager to find the user's homes instead of a root view.

@icewind1991 @schiesbn

**Comment by PVince81** [comment]
CC @MorrisJobke in case you heard mysterious stories which might be explained by this

**Comment by MorrisJobke** [comment]
@PVince81 I just got told by @icewind1991 that the local:: storage is created for the data directory by default and is needed. :see_no_evil: 

I also told everybody that moving the data dir requires the update in config.php and update of that one local storage in the DB.

**Comment by oparoz** [comment]
> and update of that one local storage in the DB

How does one do that? Should it be added to the doc?

**Comment by MorrisJobke** [comment]
> How does one do that? Should it be added to the doc?

No. It's a huge hack and requires more steps. Nothing we want to support because you really need to know what you do.

**Comment by PVince81** [comment]
Or provide a "./occ" command to move the data directory.
@schiesbn has been doing something similar with the new "keystore" folder https://github.com/owncloud/core/pull/17899

**Comment by PVince81** [comment]
@icewind1991 how about renaming this entry to "root://" instead ?

**Comment by PVince81** [comment]
or "homes://" or "data://"

**Comment by PVince81** [comment]
Regardless of the duplicate entry, we observed that the admin user's entry is missing in the root storage. This is blocking: https://github.com/owncloud/core/pull/17899#issuecomment-131736429

@icewind1991 can you have a look why the root storage entry isn't (re)scanned properly ?
To reproduce, use the branch from https://github.com/owncloud/core/pull/17899#issuecomment-131736429:

1. create "root" as admin
1. Enable encryption
1. Create two users "user1" and "user2"
1. Create folder "data/keystore" and give write permissions for the web server
1. Run the keys migration with `./occ encryption:change-key-storage-root keystore`.

This uses `getDirectoryContent()` but only migrates "user1" and "user2" because the user "root" wasn't indexed. I would expect the scanner to keep this updated properly.

**Comment by PVince81** [comment]
Hmmm, since 8.2 we have `filesystem_check_changes` set to 0 by default.
Maybe the watcher policy for this specific root storage needs to be kept on 1. Or it needs a proper initial scan.

**Comment by PVince81** [comment]
bit even if I explicitly set it to 1 before running the encryption migration, the administrator user's folder never gets indexed.

**Comment by PVince81** [comment]
Raised https://github.com/owncloud/core/issues/18346 to fix the issue specific to the missing admin users.

Let's keep this ticket here to address the "initial rescan" of the root folder after its creation.

One idea would be to find out whether the root storage entry has just be created, and in such case automatically scan its contents regardless of the "filesystem_check_changes" setting to make sure to have an initial state. However, note that any FS scan will not work with home object stores.

**Comment by PVince81** [comment]
Note: the encryption migration code had been changed to not rely on this any more

**Comment by PVince81** [comment]
Closing as obsolete. One must not sure the `View` class when accessing files anyway but the Node API.
