### ISSUE TITLE
Strange language codes in the language switcher

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#18141]
In the personal settings language switcher, lower down there are a bunch of technical language codes without any label.

They should not be there like that, they need a proper label. Maybe some of them are even duplicates, or this is a bug. @DeepDiver1975 @danimo

**Comment by DeepDiver1975** [comment]
> In the personal settings language switcher, lower down there are a bunch of technical language codes without any label.

We should analyze each of them - please supply a list - THX

**Comment by MorrisJobke** [comment]
```
ach
ady
ak
am_ET
az
bn_IN
bs
ca@valencia
cy_GB
en@pirate
en_NZ
es_BO
es_CL
es_CO
es_CR
es_EC
es_PE
es_PY
es_US
es_UY
eu_ES
fi
fil
fr_CA
fy_NL
gu
hi_IN
hy
io
jv
km
lo
mg
ml
ml_IN
mn
mr
mt_MT
nds
ne
nqo
or_IN
pa
polski
română
sk
su
sw_KE
ta_IN
te
tg_TJ
tl_PH
tzm
ur
uz
yo
```

Especially all the different spanish languages are quite strange.

**Comment by DeepDiver1975** [comment]
> Especially all the different spanish languages are quite strange.

Many of the Spanish languages have been removed from tranisfex and need to be purged from github.

For all the others: these are simply not finished or yet have been started

**Comment by DeepDiver1975** [comment]
we might want to pull in an explicit list of languages

**Comment by DeepDiver1975** [comment]
@MTRichards would it be enough to have a solution in the scope of 8.2 or are you seeking for backport to 8.1 or even earlier versions?

background: the affected code base will change in the scope of 8.2 - backport would mean: implement it again.

**Comment by DeepDiver1975** [comment]
@PVince81 this affects your work on files app via webdav

**Comment by MTRichards** [comment]
We found this ourselves, and I have not had a lot of compaints that I know of. At this time, 8.2 is acceptable to me.

**Comment by DeepDiver1975** [comment]
> At this time, 8.2 is acceptable to me.

great - @PVince81 let's finish the webdav work first and integrate tar afterwards - objections?

generally speaking this would fit since the files app requires qa attention anyhow after this work

**Comment by PVince81** [comment]
@DeepDiver1975 did you post in the wrong ticket ? Webdav has nothing to do with language codes ?!

**Comment by DeepDiver1975** [comment]
hell ..... to hot to choose proper browser tab? :imp:

**Comment by MorrisJobke** [comment]
@DeepDiver1975 After your cleanup I checked for the `__language_name__` string and following languages have it not set or a wrong one (mostly translated to `__lanugaug_name__`)

```
af_ZA.json
ar.json
az.json
bn_BD.json
bn_IN.json
bs.json
cy_GB.json
el.json
en@pirate.json
es_CL.json
fa.json
fi_FI.json
hi.json
hr.json
hu_HU.json
hy.json
id.json
is.json
jv.json
ka_GE.json
km.json
ku_IQ.json
lb.json
lo.json
lv.json
mk.json
mn.json
ms_MY.json
my_MM.json
nb_NO.json
pa.json
pt_BR.json
pt_PT.json
ro.json
si_LK.json
sr@latin.json
sv.json
ta_IN.json
ta_LK.json
te.json
uk.json
ur_PK.json
vi.json
zh_HK.json
zh_TW.json
```

**Comment by DeepDiver1975** [comment]
Job of the translators. We might want to add a hint in the source code on what this string is about.

**Comment by MorrisJobke** [comment]
> Job of the translators. We might want to add a hint in the source code on what this string is about.

#18598

**Comment by MorrisJobke** [comment]
> Job of the translators.

@DeepDiver1975 As these are already translated for some languages, can you remove the translation of `__language_name__` for following languages:

```
ar
az
bn_BD
bs
el
fa
fi_FI
hr
hu_HU
id
is
ka_GE
km
lb
lv
mk
ms_MY
nb_NO
pa
pt_BR
pt_PT
ro
sv
ta_LK
uk
vi
zh_TW
```

**Comment by jancborchardt** [comment]
![language chooser](https://cloud.githubusercontent.com/assets/925062/9544189/cf7a44a0-4d7e-11e5-8328-0b6e0953ff0d.png)

These valid languages should be sorted before the ones with the weird language codes. Also, we should fix the language codes being shown only before the release.
