### ISSUE TITLE
oc.js referenced in 8.1.0 (ubuntu-package)

### ISSUE THREAD

**Issue by aheusingfeld** [owncloud/core#18144]
Curently owncloud 8.1.0-4 (installed via Ubuntu package manager) is unusable for me (see https://github.com/owncloud/core/issues/13476#issuecomment-128981693) because each webpage references `oc.js`. It seems this reference is coming from `core/routes.php`:
```
$this->create('js_config', '/core/js/oc.js')
	->actionInclude('core/js/config.php');
```

FYI: None of the apps is working and therefore no caldav, carddav and webdav and the admin interface isn't functional either but I don't know, yet, whether that's related. All I can say is these services were working before the `apt-get upgrade`.
Suggestions for a workaround are a very welcome!

**Comment by RealRancor** [comment]
Hi,

as also written in https://github.com/owncloud/core/issues/13476 the oc.js is an autogenerated .js file: https://demo.owncloud.org/index.php/core/js/oc.js

Please fill out the issue template as described here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version (linked in the yellow box when creating a new issue).

**Comment by aheusingfeld** [comment]
### Steps to reproduce
1. Have an Ubuntu 14.04 LTS system installed with the latest owncloud 8.1.0 package available via the aptitude package manager on Wednesday morning Aug 5th
2. run `sudo apt-get update && sudo apt-get upgrade` on Thursday morning to update to the latest version of the package (see current package version below)
3. run `sudo -u www-data /usr/bin/php5 /var/www/owncloud/occ upgrade`

### Expected behaviour
owncloud services like webdav, carddav, caldav and the web interface continue working as before.

### Actual behaviour
1. I can login through the web interface so that the files app (default) is opened. But the file list is empty and there is the above mentioned error message in the webconsole.
2. Calls to `/cloud/remote.php/webdav` fail with the error "Path not found"

### Server configuration
**Operating system**:
$ cat /etc/issue
Ubuntu 14.04.3 LTS

**Web server:**
$ nginx -v
nginx version: nginx/1.4.6 (Ubuntu)

**Database:**
$ mysqld --version
mysqld  Ver 5.5.44-0ubuntu0.14.04.1 for debian-linux-gnu on i686 ((Ubuntu))

**PHP version:**
```
$ php5-fpm -v
PHP 5.5.9-1ubuntu4.11 (fpm-fcgi) (built: Jul  2 2015 15:32:44)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```

**ownCloud version:** (see ownCloud admin page)
The admin page (/cloud/index.php/settings/admin) is NOT SCROLLABLE due to the CSS property "#content-wrapper { height: 100%}"! I changed the property in `core/css/styles.css` so I can scroll to get to the bottom of the page which says: *ownCloud 8.1.0 (stable)*

I additionally checked:
```
$ sudo -u www-data php occ status
 - installed: true
 - version: 8.1.0.8
 - versionstring: 8.1.0
 - edition:

$ sudo apt-cache show owncloud-server
Package: owncloud-server
Source: owncloud
Version: 8.1.0-4
Architecture: all
...
```
Is that a known mismatch?

**Updated from an older ownCloud or fresh install:**
See above, updated from the previously installed 8.1.0 package

**List of activated apps:**

```
Enabled:
 - activity: 2.0.1
 - calendar: 0.7.2
 - contacts: 0.4.0.0
 - external: 1.2
 - files: 1.1.9
 - files_embeddedvideo: 0.0.5
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - tasks: 0.7.1
 - templateeditor: 0.1
Disabled:
 - encryption
 - files_external
 - files_locking
 - files_versions
 - files_videoviewer
 - music
 - news
 - provisioning_api
 - user_external
 - user_ldap
 - user_webdavauth
```

**The content of config/config.php:**
```
$ sudo -u www-data php occ config:list system --public

  [InvalidArgumentException]
  There are no commands defined in the "config" namespace.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### LDAP configuration (delete this part if not used)
no

### Client configuration
**Browser:**
- Firefox DevEdition 41.0a2
- Safari 9.0 (11601.1.43)

**Operating system:**
OS X 10.11

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
Only a small excerpt of the log lines I saw, when I requested `https://MYDOMAIN.de/cloud/remote.php/webdav`:
```
{"reqId":"2q1+cWpYMB6OhoCdlDEC","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/var\/www\/owncloud\/apps\/contacts\/appinfo\/app.php#35","level":3,"time":"2015-08-08T13:45:01+00:00"}
{"reqId":"Gk9BdOm\/2GIahSQi3deP","remoteAddr":"176.199.29.81","app":"remote","message":"Path not found","level":4,"time":"2015-08-08T13:45:44+00:00"}
{"reqId":"4+zI6W7oNR9jkKPJwTBd","remoteAddr":"176.199.29.81","app":"remote","message":"Path not found","level":4,"time":"2015-08-08T13:45:44+00:00"}
{"reqId":"0WrW3BKfD1c5hi5gBKii","remoteAddr":"176.199.29.81","app":"remote","message":"Path not found","level":4,"time":"2015-08-08T13:46:54+00:00"}
{"reqId":"msvxeyMXuyYi\/DifT\/S8","remoteAddr":"176.199.29.81","app":"remote","message":"Path not found","level":4,"time":"2015-08-08T14:44:43+00:00","method":"PROPFIND","url":"\/cloud\/remote.php\/webdav"}
{"reqId":"1j+2E+X1jRWxxo6pJC5q","remoteAddr":"176.199.29.81","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 404 Path not found\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/remote.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(135): handleException(Object(RemoteException))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/remote.php\",\"Line\":57}","level":0,"time":"2015-08-08T14:44:53+00:00","method":"PROPFIND","url":"\/cloud\/remote.php\/webdav\/"}
```

NOTE: Requests to `https://MYDOMAIN.de/cloud/index.php/core/js/oc.js?v=c04b0b7a02635b9daf737108ded3718e` didn't show anything in owncloud.log!

#### Browser log
See above.


## Solution:
I got the solution from what I found to be missing in this template: The webserver config - in my case nginx!

```
upstream php-handler {
  #server 127.0.0.1:9000;
  server unix:/var/run/php5-fpm.sock;
}


server {
        listen 443;
        server_name localhost MYDOMAIN.de;

        error_log /var/log/nginx/ssl_error.log error;

  # Add headers to serve security related headers
  add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;";
  add_header X-Content-Type-Options nosniff;
  add_header X-Frame-Options "SAMEORIGIN";
  add_header X-XSS-Protection "1; mode=block";
  add_header X-Robots-Tag none;


        ssl on;
        ssl_certificate /etc/apache2/ssl/startssl-2015.pem;
        ssl_certificate_key /etc/apache2/ssl/startssl.key;
        ssl_session_timeout 5m;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers "-ALL:EECDH+AES256:EDH+AES256:AES256-SHA:EECDH+AES:EDH+AES:!ADH:!NULL:!aNULL:!eNULL:!EXPORT:!LOW:!MD5:!3DES:!PSK:!SRP:!DSS:!AESGCM:!RC4";
        ssl_dhparam /etc/nginx/dh4096.pem;
        ssl_prefer_server_ciphers on;
        keepalive_timeout    70;

        root /var/www/ssl;
        index index.html index.htm;

        location / {
                # The following 2 rules are only needed with webfinger
                rewrite ^/.well-known/host-meta /cloud/public.php?service=host-meta last;
                rewrite ^/.well-known/host-meta.json /cloud/public.php?service=host-meta-json last;
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
        }

        rewrite ^/.well-known/carddav /cloud/remote.php/carddav/ redirect;
        rewrite ^/.well-known/caldav /cloud/remote.php/caldav/ redirect;
        rewrite ^/caldav(.*)$ /cloud/remote.php/caldav$1 redirect;
        rewrite ^/carddav(.*)$ /cloud/remote.php/carddav$1 redirect;
        rewrite ^/webdav(.*)$ /cloud/remote.php/webdav$1 redirect;

        rewrite ^/owncloud/(.*) /cloud/$1 permanent;
        location /cloud/ {
            alias /var/www/owncloud/;
            index index.php;
            # set max upload size
            client_max_body_size 10G;
            fastcgi_buffers 64 4K;

            # Disable gzip to avoid the removal of the ETag header
            gzip off;

            location ~ ^/cloud/(data|config|\.ht|db_structure\.xml|README) {
                    deny all;
            }

            #rewrite ^/cloud/apps/([^/]*)/(.*\.(css|php))$ /cloud/index.php?app=$1&getfile=$2 last;
            #rewrite ^(/cloud/core/doc/[^\/]+/)$ $1/index.html;

            try_files $uri $uri/ index.php;
            error_page 403 /cloud/core/templates/403.php;
            error_page 404 /cloud/core/templates/404.php;

            # Optional: set long EXPIRES header on static assets
            location ~* \.(?:jpg|jpeg|gif|bmp|ico|png|js|css|swf)$ {
                expires 30d;
                # Optional: Don't log access to assets
                access_log off;
            }

            location ~ ^/cloud/(.+?\.php)/? {  # note the question mark here and in the next line!
                    fastcgi_split_path_info ^/cloud/(.+?\.php)(/?.*)$;
                    include fastcgi_params;
                    fastcgi_param SCRIPT_FILENAME /var/www/owncloud/$fastcgi_script_name;
                    fastcgi_param SCRIPT_NAME /cloud/$fastcgi_script_name;  # !!!
                    fastcgi_param PATH_INFO $fastcgi_path_info;
                    fastcgi_param HTTPS on;
                    fastcgi_param modHeadersAvailable true; #Avoid sending the security headers twice
                    fastcgi_pass php-handler;
                    set $path_info $fastcgi_path_info;  # workaround for bug: try_files resets fastcgi_path_info for some reason.
                    #try_files $fastcgi_script_name = 404;
            }
        }
}
```

As you can see I had to do quite some modifications compared to the nginx config suggested on owncloud.org in order to server owncloud under the context root `/cloud/`.

The malicious line - which didn't cause trouble before - was this one: `location ~* \.(?:jpg|jpeg|gif|bmp|ico|png|js|css|swf)$ {`

I changed it to `location ~* \.(?:jpg|jpeg|gif|bmp|ico|png|css|swf)$ {` removing the caching of .js files and the oc.js was available again. Very, very strange!

Anyway thanks for your help, @RealRancor! I'll leave this here in case anyone else runs into an issue like this.

**Comment by RealRancor** [comment]
Hi,

instead of removing the caching of .js files put this location block below the .php block and it also should work.

**Comment by aheusingfeld** [comment]
:+1: that works too, thanks!

**Comment by edgardleal** [comment]
Thanks. work to me using nginx.

**Comment by RealRancor** [comment]
Thats now also documented here: https://doc.owncloud.org/server/8.2/admin_manual/installation/nginx_configuration.html#javascript-js-or-css-css-files-not-served-properly
