### ISSUE TITLE
Connection closed on one particular file across desktop clients and web interface.

### ISSUE THREAD

**Issue by tuxayo** [owncloud/core#18149]
### Context
One file, a PDF of 75KiO is concerned by this. In the past there were several other random files (various types and size) with the same behavior. Deleting and re uploading all the files juste changed which files have this problem, it was like a lottery...
But after a difficult Encryption V2 migration, they all synced properly, I thought the issue was fixed until I added that file.

### Steps to reproduce
1. Perform a sync with desktop client or try to view the PDF with the PDF Viewer app.

### Expected behaviour (three cases)
- It should sync successfully on desktop
- It should be displayed in the PDF Viewer app
- It should download the file from the web interface

### Actual behaviour (three cases)
- It fails with Connection closed after 50KiB of download
- ```Message: Unexpected server response (0) while retrieving PDF``` with PDF Viewer app.
  - Network monitoring on Firefox shows that the GET was successful (200) by only 50KiB were downloaded.
- After few seconds, Firefox reports the download as "Failed"
  - depending if a choose to save or open I can also get ```/tmp/FJicB87N.pdf.part could not be saved, because the source file could not be read.``` from Firefox

### Server configuration
**Operating system**:
Arch Linux
**Web server:**
lighttpd 1.4.35
**Database:**
postgresql 9.3.5
**PHP version:**
5.6.11
**ownCloud version:** (see ownCloud admin page)
8.1.0 (git)
**Updated from an older ownCloud or fresh install:**
Old install regularly updated since ownCloud 6.x
**List of activated apps:**
 - contacts: 0.4.0.0
 - encryption: 1.0.0
 - files: 1.1.9
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '526f95a5a9ffd',
  'passwordsalt' => 'has_been_replaced',
  'datadirectory' => '/usr/share/webapps/owncloud/data',
  'dbtype' => 'pgsql',
  'version' => '8.1.0.8',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'has_been_replaced',
  'dbpassword' => '',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' => 
  array (
    0 => 'some-domain.net',
    1 => 'other-domain.net',
  ),
  'loglevel' => '0',
  'secret' => 'has_been_replaced',
  'singleuser' => false,
);

```

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:**
Firefox 39.0.3

**Operating system:**
Antergos(Arch Linux)

#### Web server error log
With almost every logging option enabled, because otherwise there was nothing.
```
debug.log-request-handling = "enable"
debug.log-timeouts = "enable"
fastcgi.debug = 1
webdav.log-xml = "enable"
```
So here are the logs for one download from the web interface (to have only one request)
[the concerned file](http://pastebin.com/aepeBVAr) (called "Attestation d'affiliation.pdf")
[a working file](http://pastebin.com/KY4ynCHn) (called "LMDE Attestation d'affiliation.pdf")
There seems to be nothing different.
#### ownCloud log (data/owncloud.log)
```
Nothing when the errors happen! I checked that the log level is maximal.
```

**Comment by tuxayo** [comment]
I also logged on lighttpd with ```debug.log-condition-handling = "enable"``` which is a hell lot more verbose and still no difference between a successful download and a failed one.

**Comment by RealRancor** [comment]
Not quite sure if this is relevant: https://github.com/owncloud/core/issues/13642

**Comment by tuxayo** [comment]
The fact that lighttpd is dropped is big but I don't know if this issue is caused by lighttpd. I don't know if the problem that caused dropping support have a link with this issue.

**Comment by MorrisJobke** [comment]
Can you test this with apache? Otherwise we can't judge on the fact that lighttpd is used, which is unsupported to very serious know issues.

I will close this now. Please reopen if this still exists on apache too.

**Comment by tuxayo** [comment]
I will test on Nginx and if the problem persists, hopefully I'll have the motivation to setup an Apache server to try.

**Comment by tuxayo** [comment]
@MorrisJobke 

I have the exact same issue with Nginx and a clean 8.0 install that was upgraded regularly.

Same client sync issues, same web interface download issues. (also with wget and curl)

Every two day or so I have a new file that get in this state and I have to:
- copy it client side
- delete it server side (with the web interface)
- delete it client side
- wait for sync to succeed
- client: rename the copy to the original name

owncloud.log: still nothing (not a single line added by the request)
nginx log: only a GET request, nothing else.

What could I do to gather more infos?
