### ISSUE TITLE
Packaging php5-smbclient for 8.1

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#18152]
Hi,

according to https://github.com/owncloud/core/issues/13022 php5-smbclient is only shipped/packages for the EE in oC7.

But starting with the new SMB implementation in oC 8.1 (https://github.com/owncloud/core/pull/10673) it seems that this is now also needed / recommended for oC 8.1.

Ref for the clarification request in the docs: https://github.com/owncloud/documentation/issues/1447

**Comment by RealRancor** [comment]
Ah, this is for Ubuntu/Debian. No idea about other distros.

**Comment by DeepDiver1975** [comment]
The packages should have been made available in obs

**Comment by PVince81** [comment]
CC @jnweiger

**Comment by jnweiger** [comment]
Linked in from isv:ownCloud:devel

https://build.opensuse.org/package/show/isv:ownCloud:community:8.1/php5-libsmbclient?expand=0

Hmm. Should the main owncloud package also have a Requires: for this?

**Comment by RealRancor** [comment]
> Hmm. Should the main owncloud package also have a Requires: for this?

As it's only used for the files_external that package is probably the better place or am i wrong?

**Comment by jnweiger** [comment]
@RealRancor you are right, that makes sense for now. :-)
I plan to merge the apps into owncloud-server for next release, like this:
https://build.opensuse.org/package/show/isv:ownCloud:community:8.1:testing:merged/owncloud
(alpha testing welcome... )

**Comment by jnweiger** [comment]
8.1.1 won't see a Requires anyway. We are too late in the release process.

**Comment by RealRancor** [comment]
I think Requires is also not that important as this new lib is optional.

**Comment by JT1301** [comment]
Can anyone create a howto to install this new smbclient?
I need the package for https://github.com/owncloud/core/issues/17499
but so far it has not worked with this guide https://github.com/eduardok/libsmbclient-php/blob/master/README.md

**Comment by RealRancor** [comment]
@JT1301 Document request is already linked above: https://github.com/owncloud/documentation/issues/1447

But if this is packaged you probably don't need an how-to, you just need to know how to install packages via your package manager.

**Comment by RealRancor** [comment]
Seems the binary is currently only built for amd64. Shouldn't there be a binary for i686?

**Comment by jnweiger** [comment]
Added i586 to https://build.opensuse.org/package/show/isv:ownCloud:community:8.1/php5-libsmbclient

**Comment by RealRancor** [comment]
@jnweiger Normally we could close this or any veto?

**Comment by Xenopathic** [comment]
@RealRancor you really should sign the contributor agreement, then you could close all these issues yourself :smile:
