### ISSUE TITLE
User management on mobile: left/right scrolling not possible or difficult

### ISSUE THREAD

**Issue by Bullnados** [owncloud/core#18153]
In demo it is not possible to scroll left-right in user management with my S2 Android Opera. The scrollbar is visible all the time

**Comment by karlitschek** [comment]
@jancborchardt @blizzz any idea?

**Comment by jancborchardt** [comment]
@Bullnados does it work with the stock Android browser (Android) or Firefox?

**Comment by Bullnados** [comment]
Also doesn't work in both. Android(horizontal scrollbar visible) and Firefox Beta Browser(scrollbar not visible).

**Comment by jancborchardt** [comment]
@Bullnados what happens instead? Nothing moves, or the sidebar comes out?

**Comment by Bullnados** [comment]
In all browser no left-right/horizontal move possible and aditional in FF there is no horizontal scrollbar visible

**Comment by Bullnados** [comment]
On AcerA700 i can scroll left-right in vertical mode(FF Beta). Here the left sidebarmenu is visible all the time.

**Comment by PVince81** [comment]
Is this still an issue with OC 9.0.2 ?

**Comment by Bullnados** [comment]
Tested again with demo. The scrollbar isn't visible anymore. But now see screenshot. Again with Firefox and Chrome on Sony Z2
![screenshot_20160618-194812](https://cloud.githubusercontent.com/assets/11041576/16172720/2cb8496c-358e-11e6-910d-f3a6adebd4d2.png)
