### ISSUE TITLE
Sync client downloads files that are already there.

### ISSUE THREAD

**Issue by lhartmann** [owncloud/core#18150]
ownCloud 8.2
desktop client 1.8.4, linux 14.04, installed via the server-provided instructions.

I had 100GB+ of files previously synced between 4 of my computers (notebook, home server, office workstation, office backup), using linux+unison+rsync to keep them up to date, and it was good. In order to help my co-workers and a bunch of our students (about 50-70 people total), I decided to go owncloud as is is more windows, MAC, android and iStuff friendly.

When migrating to owncloud I already expected the first upload to take a while, so I left my workstation online for a couple of days and everything was uploaded OK.

When I went on to configure my notebook I expected the desktop client to realize the files were already there, but no. The client started downloading all the 100GB+ of data regardless of it being already there! Thousands of "Transfered, conflicting file renamed" messages were showing up on activity log (I don't know the exact words, my interface is translated pt_BR). Files were not duplicated on the folders, at least.

Assuming the same would happen on my other 2 computers, and on every computer of every user, I can not allow access to the server as this would clog our network for weeks!

If the protocol can not tell that the files are the same, then these issues should happen even after initial sync. If, for instance, I download a DVD image at work and use a flash drive to save time when bringing it home, then owncloud will not understand it, and will download the DVD again.

Potential solution (I know very little of owncloud's internals, but let me try brainstorming):
- Add hash column to the file database (filecache?). (DO NOT REPLACE ETAG)
- Let hash column accept, and default to, "null" values for unknown hashes.
- Offload hashing to the client when possible and safe (desktop/mobile client, not-shared file).
- Optionally have a cron job hashing null-hashed files every now and then.
- Optionally hash and update table on demand.
- If the file exists check just a hash of the file (MD5 or SHA) against the server.

P.S.: I do realize that hashing is CPU- and disk-expensive on the server side, but pointless downloading is network intensive and uses jus as much disk io...
P.S.: I do realize that owncloud uses webdav as a transport protocol and it may not support hashes. It is a matter of "supporting webdav" or "limiting to webdav".

**Comment by RealRancor** [comment]
Dup of https://github.com/owncloud/client/issues/3422

There you can also find the issue tracker of the client

**Comment by lhartmann** [comment]
Yup. Duplicate.

**Comment by RealRancor** [comment]
I think your input at the linked issue could be still useful.
