### ISSUE TITLE
Activity/event list for files in right sidebar

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#18164]
Before we can show comments or versions inline, we need the groundwork to be done, which is the ability to display a list of events/activities inside a panel.

An event can be one of:
- file activity, as delivered by the activity list
- comments, as delivered by the comments component https://github.com/owncloud/core/issues/16328
- versions, as delivered by the version app

The API needs to be generic enough for such apps to be able to embed their rows into the list.

@jancborchardt @nickvergessen @schiesbn @DeepDiver1975 

I'll have a go at the generic interface/API on the Javascript side.

The question is whether we want a PHP-side API (app framework) that can deliver all events in one go or do we want each event type to be retrieved separately. Each approach has its own challenges.

@nickvergessen we probably need something similar to the activity manager where apps can push events. Or should we reuse the activity manager / activities as a base for all this ?

**Comment by jancborchardt** [comment]
Keep in mind this is something we most likely want to display in the mobile and desktop clients as well somehow. So it needs to be generic and performant.

**Comment by PVince81** [comment]
Mock up here: https://github.com/owncloud/core/issues/16308#issuecomment-113521360

Or is there anything more recent ?

**Comment by jancborchardt** [comment]
That’s still the spec and the current plan.

**Comment by karlitschek** [comment]
I think this is the most recent one. It's still an open question if we really want to mix the activities with comments and version. I think it is a neat idea but could totally kill the clearness and makes old versions impossible to find. I suggest to start with notmal activities first.

**Comment by jancborchardt** [comment]
We’ll do it step by step of course, but the comments, version and activity should all be mixed of course. It’s one chronological list.

**Comment by PVince81** [comment]
Activity tab WIP PR here: https://github.com/owncloud/activity/issues/358

**Comment by nickvergessen** [comment]
Merged
