### ISSUE TITLE
Encryption problem after upgrade from 8.0.x to 8.1

### ISSUE THREAD

**Issue by fschloegl** [owncloud/core#18162]
Hi, the following error apears after the upgrade vom 8.0.x to 8.1 and after a sucessfull encyption migration with 
> sudo -u www-data php occ encryption:migrate

_ 
> Exception: {"Message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/files\/stream\/encryption.php(443): OCA\\Encryption\\Crypto\\Encryption->decrypt('imo67VPC49bYURf...')\n#1 \/var\/www\/owncloud\/lib\/private\/files\/stream\/encryption.php(282): OC\\Files\\Stream\\Encryption->readCache()\n#2 [internal function]: OC\\Files\\Stream\\Encryption->stream_read(8192)\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php(70): file_put_contents('php:\/\/output', Resource id #382)\n#4 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(479): Sabre\\HTTP\\Sapi::sendResponse(Object(Sabre\\HTTP\\Response))\n#5 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#6 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n#7 \/var\/www\/owncloud\/remote.php(132): require_once('\/var\/www\/ownclo...')\n#8 {main}","File":"\/var\/www\/owncloud\/apps\/encryption\/lib\/crypto\/encryption.php","Line":289}

_
> Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.	

I can download old files from the webinterface, the sync clients can upload new files to the server, but other sync clients can't download the file. And the new files can't opened at the web interface.

**Comment by RealRancor** [comment]
Hi,

there are known issues with migrating the encryption app from oC 8.0.x to 8.1. Thats why the release notes (https://doc.owncloud.org/server/8.1/admin_manual/release_notes.html) are stating:

> It is not recommended to upgrade encryption-enabled systems from ownCloud Server 8.0 to version 8.1.0 as there is a chance the migration will break. We recommend to migrate to the first bugfix release, ownCloud Server 8.1.1.

Either roll back to your backup and wait until oC 8.1.1 is released tomorrow or try the hints here: https://github.com/owncloud/core/issues/17574

**Comment by MorrisJobke** [comment]
@fschloegl Please comment here if the proposed ways doesn't fix your problem and I will reopen the ticket.
