### ISSUE TITLE
LDAP bind not working for a specific set of users

### ISSUE THREAD

**Issue by averi** [owncloud/core#18165]
We (the GNOME Project) are using an Owncloud instance bound to our internal LDAP database. Binds are working properly for pretty much all the user base except for two specific users which are are failing to login with the following error:

```
{"reqId":"bcQNMM58AHbNvisP7Pch","remoteAddr":"x.x.x.x","app":"user_ldap","message":"LDAP Login: Could not get user object for DN uid=user1,cn=users,cn=accounts,dc=gnome,dc=org. Maybe the LDAP entry has no set display name attribute?","level":2,"time":"2015-08-09T13:50:42+00:00"}
{"reqId":"bcQNMM58AHbNvisP7Pch","remoteAddr":"x.x.x.x","app":"core","message":"Login failed: 'user1' (Remote IP: 'x.x.x.x)","level":2,"time":"2015-08-09T13:50:42+00:00"}
```

The user has no display name set and neither do most of the other LDAP users on the tree. I tried diffing the user1 entry with another random user object and there were no relevant differences to justify a failed bind. 

CCing @blizzz as @jancborchardt suggested me during our meet up at GUADEC. I'm happy to provide more logs.

**Comment by blizzz** [comment]
Then configure the display name attribute in LDAP advanced settings to a value that is available for all (desired) users. cn for instance should work all the time.

**Comment by averi** [comment]
That's what we actually do already:

Advanced --> User Display Name Field --> cn

The error is however still printed and two users in particular are still not able to login through their LDAP account at all.

**Comment by blizzz** [comment]
@averi do you have something else in the log? what is your LDAP configuraton (``./occ ldap:show-config``), which versions do you use (ownCloud and PHP) and on which OS?

My guess out of the blue is https://github.com/owncloud/core/issues/17631 (in 8.1.0), which will be fixed in 8.1.1 by https://github.com/owncloud/core/pull/17723

**Comment by averi** [comment]
LDAP configuration:

```
+-------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                                                                          |
+-------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      |                                                                                                                                              |
| hasPagedResultSupport         |                                                                                                                                              |
| homeFolderNamingRule          |                                                                                                                                              |
| lastJpegPhotoLookup           | 0                                                                                                                                            |
| ldapAgentName                 | uid=ownclouduser,cn=users,cn=accounts,dc=gnome,dc=org                                                                                        |
| ldapAgentPassword             | ***                                                                                                                                          |
| ldapAttributesForGroupSearch  |                                                                                                                                              |
| ldapAttributesForUserSearch   | uid                                                                                                                                          |
| ldapBackupHost                |                                                                                                                                              |
| ldapBackupPort                |                                                                                                                                              |
| ldapBase                      | dc=gnome,dc=org                                                                                                                              |
| ldapBaseGroups                | cn=groups,cn=accounts,dc=gnome,dc=org                                                                                                        |
| ldapBaseUsers                 | cn=users,cn=accounts,dc=gnome,dc=org                                                                                                         |
| ldapCacheTTL                  | 600                                                                                                                                          |
| ldapConfigurationActive       | 1                                                                                                                                            |
| ldapEmailAttribute            | mail                                                                                                                                         |
| ldapExperiencedAdmin          | 1                                                                                                                                            |
| ldapExpertUUIDGroupAttr       |                                                                                                                                              |
| ldapExpertUUIDUserAttr        |                                                                                                                                              |
| ldapExpertUsernameAttr        |                                                                                                                                              |
| ldapGroupDisplayName          | cn                                                                                                                                           |
| ldapGroupFilter               |                                                                                                                                              |
| ldapGroupFilterGroups         |                                                                                                                                              |
| ldapGroupFilterMode           | 1                                                                                                                                            |
| ldapGroupFilterObjectclass    |                                                                                                                                              |
| ldapGroupMemberAssocAttr      | memberUid                                                                                                                                    |
| ldapHost                      | account.gnome.org                                                                                                                            |
| ldapIgnoreNamingRules         |                                                                                                                                              |
| ldapLoginFilter               | (&(&(objectClass=person)(memberOf=cn=foundation,cn=groups,cn=accounts,dc=gnome,dc=org))(|(uid=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid)))) |
| ldapLoginFilterAttributes     |                                                                                                                                              |
| ldapLoginFilterEmail          | 1                                                                                                                                            |
| ldapLoginFilterMode           | 0                                                                                                                                            |
| ldapLoginFilterUsername       | 1                                                                                                                                            |
| ldapNestedGroups              | 0                                                                                                                                            |
| ldapNoCase                    | 0                                                                                                                                            |
| ldapOverrideMainServer        | 0                                                                                                                                            |
| ldapPagingSize                | 500                                                                                                                                          |
| ldapPort                      | 389                                                                                                                                          |
| ldapQuotaAttribute            |                                                                                                                                              |
| ldapQuotaDefault              |                                                                                                                                              |
| ldapTLS                       | 0                                                                                                                                            |
| ldapUserDisplayName           | cn                                                                                                                                           |
| ldapUserFilter                | (&(objectClass=person)(memberOf=cn=foundation,cn=groups,cn=accounts,dc=gnome,dc=org))                                                        |
| ldapUserFilterGroups          | cn=foundation,cn=groups,cn=accounts,dc=gnome,dc=org                                                                                          |
| ldapUserFilterMode            | 1                                                                                                                                            |
| ldapUserFilterObjectclass     | posixAccount                                                                                                                                 |
| ldapUuidGroupAttribute        | auto                                                                                                                                         |
| ldapUuidUserAttribute         | auto                                                                                                                                         |
| turnOffCertCheck              | 0                                                                                                                                            |
| useMemberOfToDetectMembership | 1                                                                                                                                            |
+-------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+

Owncloud release we're using is 8.1.1 (just upgraded the instance and asked the person with the failing login to try again and still no luck), about php packages:

php-5.4.43
php-ldap-5.4.43

OS is RHEL 6.

The log excerpt with log_level set to debug:

```
{"reqId":"5NK8p1\/\/xWYopUDJZ4AR","remoteAddr":"X.X.X.X","app":"core","message":"Login failed: 'username' (Remote IP: "X.X.X.X")","level":2,"time":"2015-08-12T10:09:44+00:00","method":"POST","url":"\/"}
{"reqId":"\/A6iD8XwH6KXZXISV3wi","remoteAddr":"172.31.1.55","app":"user_ldap","message":"No group filter is specified, LDAP group feature will not be used.","level":1,"time":"2015-08-12T10:09:47+00:00","method":"GET","url":"\/index.php\/core\/js\/oc.js?v=f1497eac749318dc8ccb9e9174730af3"}
{"reqId":"\/A6iD8XwH6KXZXISV3wi","remoteAddr":"X.X.X.X","app":"user_ldap","message":"No DN found for  on account.gnome.org","level":0,"time":"2015-08-12T10:09:47+00:00","method":"GET","url":"\/index.php\/core\/js\/oc.js?v=f1497eac749318dc8ccb9e9174730af3"}
```

**Comment by averi** [comment]
On a side note with today's update to 8.1.1, the whole set of ldap users are not able to login anymore with the exact same configuration. OC suggests to try the user query locally and that just works:

```
ldapsearch -x -D 'uid=user1,cn=users,cn=accounts,dc=gnome,dc=org' -W -H ldap://account.gnome.org -b dc=gnome,dc=org '(&(&(objectClass=person)(memberOf=cn=foundation,cn=groups,cn=accounts,dc=gnome,dc=org))(|(uid=user1)(|(mailPrimaryAddress=%uid)(mail=%uid))))' -W
```

results in:

```
# requesting: ALL
#

# user1, users, accounts, gnome.org
dn: uid=user1,cn=users,cn=accounts,dc=gnome,dc=org
krbLastSuccessfulAuth: datetime
memberOf: cn=group1,cn=groups,cn=accounts,dc=gnome,dc=org
memberOf: cn=group2,cn=groups,cn=accounts,dc=gnome,dc=org
memberOf: cn=group3,cn=groups,cn=accounts,dc=gnome,dc=org
```

**Comment by averi** [comment]
Seems the cause of the above was "(|(uid=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))))'"  being on the search filter, making it (uid=%uid) did the trick but the same query was used to work just fine before today's upgrade. At least it looks properly formatted to me and will result in a true value in case either uid=%uid or one of the two between mailPrimaryAddress and mail are found.

I asked the person who had the failing login to try again and what we had again is:

```
{"reqId":"Uulq\/J4mSclAQ1Z2Bu0J","remoteAddr":"X.X.X.X","app":"user_ldap","message":"LDAP Login: Could not get user object for DN uid=user1,cn=users,cn=accounts,dc=gnome,dc=org. Maybe the LDAP entry has no set display name attribute?","level":2,"time":"2015-08-12T12:41:39+00:00"}
{"reqId":"Uulq\/J4mSclAQ1Z2Bu0J","remoteAddr":"X.X.X.X","app":"core","message":"Login failed: 'user1' (Remote IP: '172.31.1.56)","level":2,"time":"2015-08-12T12:41:39+00:00"}
```

Querying that DN from user2, it being my personal user as I don't have access to user1's password:

```
ldapsearch -x -D 'uid=user2,cn=users,cn=accounts,dc=gnome,dc=org' -H ldap://account.gnome.org -b dc=gnome,dc=org '(&(&(objectClass=person)(memberOf=cn=foundation,cn=groups,cn=accounts,dc=gnome,dc=org))(uid=user1))' -W
```

results in:

```
# user1, users, accounts, gnome.org
dn: uid=user1,cn=users,cn=accounts,dc=gnome,dc=org
krbLastSuccessfulAuth: datetime
krbPasswordExpiration: datetime
krbLastPwdChange: datetime
memberOf: cn=foundation,cn=groups,cn=accounts,dc=gnome,dc=org
```

**Comment by jancborchardt** [comment]
@averi thanks for the details! :) @blizzz said he will have a look later.

**Comment by blizzz** [comment]
Config looks OK.

> On a side note with today's update to 8.1.1, the whole set of ldap users are not able to login anymore with the exact same configuration. OC suggests to try the user query locally and that just works:

> ```
ldapsearch -x -D 'uid=user1,cn=users,cn=accounts,dc=gnome,dc=org' -W -H ldap://account.gnome.org -b dc=gnome,dc=org '(&(&(objectClass=person)(memberOf=cn=foundation,cn=groups,cn=accounts,dc=gnome,dc=org))(|(uid=user1)(|(mailPrimaryAddress=%uid)(mail=%uid))))' -W
```

@averi The %uid placeholder was not replaced for mailPrimaryAddress and mail. Did you copy-paste it just like this? Since uid was replaced correctly the result of ldapsearch is as desired (I assume "cn", "objectclass" and such were listed with the correct value but you reduced the output – correct?).

And another thing: Is the PHP extension mbstring installed? If not, please do so and retry.

**Comment by averi** [comment]
Before updating to 8.1.1 we had the following LDAP filter in place:

```
(&(&(objectClass=person)(memberOf=cn=foundation,cn=groups,cn=accounts,dc=gnome,dc=org))(|(uid=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))))
```

Using the 'Test configuration against user' tool against a few uids resulted in no users found and that was actually surprising as the same filter has been there since months. Removing references to mailPrimaryAddress and mail seems to have fixed the issue. The above query was working just fine with ldapsearch (as it's a "look for the uid field OR (mailPrimaryAddress or mail)") but not on OC itself.

As said removing the | operator and leaving just uid around fixed the issue as pretty much everyone is used to login through their GNOME Account uid and not their email (which is completely different from the uid itself as that's the alias to where the @gnome.org email forwards to). What surprised me is the filter above wasn't expected to fail as uid=%uid always had to evaluate to true if the GNOME username was actually found (true or (false or false)).

That said two users are still not able to login with the error reported on my very first comment. 

P.S php-mbstring is there.

**Comment by blizzz** [comment]
@averi got this somehow out of sight - does the issue still exist?

**Comment by averi** [comment]
@blizzz I do confirm the error is still there and appears only with specific users, the most recent failure:

{"reqId":"\/Q0FsJpBqFB6KMJjUi3z","remoteAddr":"172.x.x.x","app":"user_ldap","message":"LDAP Login: Could not get user object for DN uid=foo,cn=users,cn=accounts,dc=gnome,dc=org. Maybe the LDAP entry has no set display name attribute?","level":2,"time":"2016-02-22T14:25:56+00:00"}

The user has the cn attribute correctly set and the LDAP configuration is setup to pick cn as the "Group Display Name Field". I can provide a screenshot if needed but the above configuration excerpt still applies.

**Comment by blizzz** [comment]
@averi Which LDAP server do you use? Can you provide the LDAP record of an affected user? As you did in https://github.com/owncloud/core/issues/18165#issuecomment-130281668 but with uid, cn. 

> As said removing the | operator and leaving just uid around fixed the issue as pretty much everyone is used to login through their GNOME Account uid and not their email (which is completely different from the uid itself as that's the alias to where the @gnome.org email forwards to). What surprised me is the filter above wasn't expected to fail as uid=%uid always had to evaluate to true if the GNOME username was actually found (true or (false or false)).

That's really fishy. Could you check the LDAP server log for the related request? Whether an error was thrown or results actually delivered?

**Comment by averi** [comment]
@blizzz we're using FreeIPA's bundle shipping the 389-ds directory service. I'm including both the LDAP record and the LDAP query result for one of the users failing to login:

LDAP Record:

```
# mlundblad, users, compat, gnome.org
dn: uid=mlundblad,cn=users,cn=compat,dc=gnome,dc=org
objectClass: posixAccount
objectClass: ipaOverrideTarget
objectClass: top
gecos: Marcus Lundblad
cn: Marcus Lundblad
uidNumber: 
gidNumber: 
loginShell: /bin/bash
homeDirectory: /home/users/mlundblad
ipaAnchorUUID:: 
uid: mlundblad

# mlundblad, users, accounts, gnome.org
dn: uid=mlundblad,cn=users,cn=accounts,dc=gnome,dc=org
ipaSshPubKey: foo
description: foo
displayName: Marcus Lundblad
cn: Marcus Lundblad
objectClass: ipaobject
objectClass: person
objectClass: FoundationFields
objectClass: top
objectClass: ipasshuser
objectClass: inetorgperson
objectClass: organizationalperson
objectClass: krbticketpolicyaux
objectClass: krbprincipalaux
objectClass: inetuser
objectClass: posixaccount
objectClass: ipaSshGroupOfPubKeys
objectClass: mepOriginEntry
loginShell: /bin/bash
initials: ML
gecos: Marcus Lundblad
homeDirectory: /home/users/mlundblad
uid: mlundblad
mail:
givenName: Marcus
sn: Lundblad
ipaUniqueID:
uidNumber: 
gidNumber: 
```

And LDAP response, which seems successful:

```
[23/Feb/2016:13:58:26 +0000] conn=50268 op=1 SRCH base="cn=users,cn=accounts,dc=gnome,dc=org" scope=2 filter="(&(&(objectClass=person)(memberOf=cn=foundation,cn=groups,cn=accounts,dc=gnome,dc=org))(uid=mlundblad))" attrs="distinguishedName uid samaccountname memberOf  mail cn jpegPhoto thumbnailphoto"
[23/Feb/2016:13:58:26 +0000] conn=50268 op=1 RESULT err=0 tag=101 nentries=1 etime=0 notes=P pr_idx=0
[23/Feb/2016:13:58:26 +0000] conn=50268 op=2 SRCH base="uid=mlundblad,cn=users,cn=accounts,dc=gnome,dc=org" scope=0 filter="(objectClass=*)" attrs="entryuuid"
[23/Feb/2016:13:58:26 +0000] conn=50268 op=2 RESULT err=0 tag=101 nentries=1 etime=0 notes=P pr_idx=0
[23/Feb/2016:13:58:26 +0000] conn=50268 op=3 SRCH base="uid=mlundblad,cn=users,cn=accounts,dc=gnome,dc=org" scope=0 filter="(objectClass=*)" attrs="nsUniqueId"
[23/Feb/2016:13:58:26 +0000] conn=50268 op=3 RESULT err=0 tag=101 nentries=1 etime=0 notes=P pr_idx=0
[23/Feb/2016:13:58:26 +0000] conn=50268 op=4 SRCH base="uid=mlundblad,cn=users,cn=accounts,dc=gnome,dc=org" scope=0 filter="(objectClass=*)" attrs="objectguid"
[23/Feb/2016:13:58:26 +0000] conn=50268 op=4 RESULT err=0 tag=101 nentries=1 etime=0 notes=P pr_idx=0
[23/Feb/2016:13:58:26 +0000] conn=50268 op=5 SRCH base="uid=mlundblad,cn=users,cn=accounts,dc=gnome,dc=org" scope=0 filter="(objectClass=*)" attrs="guid"
[23/Feb/2016:13:58:26 +0000] conn=50268 op=5 RESULT err=0 tag=101 nentries=1 etime=0 notes=P pr_idx=0
[23/Feb/2016:13:58:26 +0000] conn=50268 op=6 SRCH base="uid=mlundblad,cn=users,cn=accounts,dc=gnome,dc=org" scope=0 filter="(objectClass=*)" attrs="ipaUniqueID"
[23/Feb/2016:13:58:26 +0000] conn=50268 op=6 RESULT err=0 tag=101 nentries=1 etime=0 notes=P pr_idx=0
[23/Feb/2016:13:58:26 +0000] conn=50268 op=7 SRCH base="uid=mlundblad,cn=users,cn=accounts,dc=gnome,dc=org" scope=0 filter="(objectClass=*)" attrs="auto"
[23/Feb/2016:13:58:26 +0000] conn=50268 op=7 RESULT err=0 tag=101 nentries=1 etime=0 notes=P pr_idx=0
[23/Feb/2016:13:58:26 +0000] conn=50268 op=8 UNBIND
```

**Comment by blizzz** [comment]
Mh, FreeIPA/389ds is not tested, but the latter should work. 

I wonder whether the entry uid=mlundblad,cn=users,cn=compat,dc=gnome,dc=org could cause an issue. It should not, because it should be excluded by the user base dn. We can rule out this Also because the correct DN appears in the log.

The LDAP log looks shiny, always one result set returned. Except, that all supported values for the UUID are tried, plus auto. This does not feel right, the first hit should succeed. 

Could you query the failing user and a correct one for the attributes  ``entryuuid``, ``nsuniqueid``, ``objectguid``, ``guid``, ``ipauniqueid``? I assume the last one should bring a result. While doing this, you could also check whether there is an entry about this user in the table ``oc_ldap_user_mapping``.

Please also make sure that there is not white space in the ``ldapExpertUUIDUserAttr`` setting (expert tab).

**Comment by averi** [comment]
I can confirm the only attribute that is found on both a working and not-working entry is ipauniqueid. There's no mapping under oc_ldap_user_mapping of this specific user:

mysql> select * from oc_ldap_user_mapping where ldap_dn = 'uid=mlundblad,cn=users,cn=accounts,dc=gnome,dc=org';
Empty set (0.00 sec)

A working user is definitely found on the oc_ldap_user_mapping table. Are those created automatically for all the users specified on the user base or right after user's first successful login attempt?

**Comment by blizzz** [comment]
> I can confirm the only attribute that is found on both a working and not-working entry is ipauniqueid. There's no mapping under oc_ldap_user_mapping of this specific user:

Was there anything weird about the value of the non-working user? For instance, another user has the same UUID in the mappings table (collision).

> Are those created automatically for all the users specified on the user base or right after user's first successful login attempt?

They are created automatically, either on login or on any reference to the user (e.g. searching in the share dialog, listing on the users page).

Does it help to set ``ipauniqueid`` as UUID attriubte for users on the expert tab?

**Comment by averi** [comment]
Manually specifying ipauniqueid as the UUID attribute did the trick. I have some questions based on the resolution of this issue ticket:

What's the default way to generate UUIDs if not specified manually on the expert tab? What kind of LDAP attribute is parsed to then generate the UUID? does it look at an LDAP attribute at all?

Thanks for your help!

**Comment by blizzz** [comment]
> Manually specifying ipauniqueid as the UUID attribute did the trick.

Good. But confusing at the same time. It should have succeeded by default.

> What's the default way to generate UUIDs if not specified manually on the expert tab? What kind of LDAP attribute is parsed to then generate the UUID? does it look at an LDAP attribute at all?

There are a couple of default attributes ( ``entryuuid``, ``nsuniqueid``, ``objectguid``, ``guid``, ``ipauniqueid``) that are read from LDAP. If this is needed, there is a discovery running and using the first that returns a result (there is no official standard, many vendors have their picks). Subsequently, the detected attribute is used.

**Comment by averi** [comment]
It's even more confusing when you go and check the mappings that were created before this change. None of them matches the ipauniqueid found on the LDAP tree and none of the other user-related objects can be looked up on the tree either. I'm wondering how the previous mappings were created. 

Additionally searching the whole tree for any of the pre-existing mappings UUIDs results empty.

**Comment by blizzz** [comment]
@averi how do they look like and how is it supposed to be?

**Comment by averi** [comment]
An example for the very first two entries I have from the SQL database:

```
| uid=frnsantos,cn=users,cn=accounts,dc=gnome,dc=org  | 153ba401-5f7511e4-af73cd61-60aa6371 | 153ba401-5f7511e4-af73cd61-60aa6371 |
| uid=bootingman,cn=users,cn=accounts,dc=gnome,dc=org | 1906b101-861d11e4-af73cd61-60aa6371 | 1906b101-861d11e4-af73cd61-60aa6371 |
```

And the relevant query results:

```
ldapsearch -x -H ldap://127.0.0.1 -b dc=gnome,dc=org '(ipaUniqueID=153ba401-5f7511e4-af73cd61-60aa6371)'
# extended LDIF
#
# LDAPv3
# base <dc=gnome,dc=org> with scope subtree
# filter: (ipaUniqueID=153ba401-5f7511e4-af73cd61-60aa6371)
# requesting: ALL
#

# search result
search: 2
result: 0 Success
```

and 

```

ldapsearch -x -H ldap://127.0.0.1 -b dc=gnome,dc=org '(ipaUniqueID=1906b101-861d11e4-af73cd61-60aa6371)'
# extended LDIF
#
# LDAPv3
# base <dc=gnome,dc=org> with scope subtree
# filter: (ipaUniqueID=1906b101-861d11e4-af73cd61-60aa6371)
# requesting: ALL
#

# search result
search: 2
result: 0 Success

# numResponses: 1
```

The ipaUniqueID value is different for both users on the LDAP tree as explained above.

**Comment by blizzz** [comment]
While you were running ownCloud was the used LDAP server changed or migrated?

A wrong UUID will hurt you if a DN changes, because then the user cannot be found again and a new one will be generated.

**Comment by PVince81** [comment]
Closing due to lack of feedback.

Please try again with a more recent version like 9.0.4RC1 and reopen if the problem persists.
Thanks.
