### ISSUE TITLE
Upload deduplication

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#18166]
It would be nice if files to be uploaded could be deduplicated and save being uploaded at all.
This is a combination of thoughts in https://github.com/owncloud/client/issues/3545 and https://github.com/owncloud/core/issues/3030
It is all very well to do dedup in the server file system back end. That saves physical server space, "a good thing" (tm).
But when a user puts the same file in their client folder structure multiple times, or a backup tool makes multiple "copies" of the file in the client folder by making hardlinks, or multiple users put the same file into their client folders (e.g. they all get a copy of some report, multiple people save the same binary installer...) then it would be nice to save even uploading it.
a) Send some file checksum/hash/whatever calculation to represent the file content with acceptably super-minimal chance of checksum/hash-collision. That can be sent with the initial file create request.
b) If the server already has that file then it can respond "got it, do not bother sending me all the content". Server makes hard-links (or whatever is available to it) to the existing file. If the server side file system is really dumb then the server has to do some work making an actual copy of the file in the back end file system.

On slow links it is nicer to use the compute power that is free at either end to compute this stuff.
Maybe such a feature would need to be user-selectable, since some people might rather use network bandwidth than compute power.

**Comment by karlitschek** [comment]
on the server side we rely on depublication in the filesystem. we don't want to reimplement this. What is needed to save the transfer is so see that the file already exists on the server as a different name. Let's track this feature in a client issue.
