### ISSUE TITLE
Position of edit options in sharing menu confuses user

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/core#18163]
Based on user feedback, I would like to suggest to better structure the sharing menu. It is not clear at first sight, where the create, change, delete buttons belong.

**Problem:**
<img width="948" alt="files_-_owncloud" src="https://cloud.githubusercontent.com/assets/214010/9168857/9c9efa5e-3f59-11e5-9634-f65066414070.png">

**Re-structured sharing menu:**
<img width="948" alt="files_-_owncloud" src="https://cloud.githubusercontent.com/assets/214010/9168858/9ca0dc20-3f59-11e5-8149-9bd91f81c308.png">

@jancborchardt What do you think?

**Comment by DeepDiver1975** [comment]
with 8,2 sharing will be move into the sidebar. UX will change.

@jancborchardt @PVince81 @blizzz screenshot of WIP at hand?

**Comment by michaelstingl** [comment]
@DeepDiver1975 Thank you!

**Comment by karlitschek** [comment]
Independent if the sharing is in the dropdown or in the sidebare, a better grouping of the checkboxes and options is probably a good idea :-)

**Comment by DeepDiver1975** [comment]
> Independent if the sharing is in the dropdown or in the sidebare, a better grouping of the checkboxes and options is probably a good idea :-)

thats the background of the request to see a screenshot of the side bar :wink:

**Comment by jancborchardt** [comment]
How it should look like is the second screenshot of https://github.com/owncloud/core/issues/3224

@MorrisJobke @PVince81 @owncloud/designers we can use the same bubble popover we use in https://github.com/owncloud/core/pull/17709#issuecomment-128374485

**Comment by MorrisJobke** [comment]
Example of wrong behaviour:

![image](https://cloud.githubusercontent.com/assets/12275313/8654154/fb61096a-2988-11e5-859f-1c624c8ab75e.png)

**Comment by PVince81** [comment]
@MorrisJobke probably missing a white-space: nowrap or &nbsp.

I'd vote for a quickfix here if really needed and add the dropdown when in the sidebar. Because a dropdown in a dropdown isn't too nice (and detecting auto-close mouse click outside of dropdowns is such a pain)

**Comment by MTRichards** [comment]
Quick fix is ok for now, we just need it into 8.2. then sidebar for making it better as we have time, which might be 8.2 though probably not. Thank you!

**Comment by MorrisJobke** [comment]
The behaviour is already fixed in 8.1.0 - cc @CaptionF

**Comment by blizzz** [comment]
@MorrisJobke sure? current stable8.1 gives me:

![screenshot](https://cloud.githubusercontent.com/assets/2184312/9235534/8b9f3bdc-413f-11e5-9e16-8ba176cf4b06.jpg)

**Comment by MorrisJobke** [comment]
@blizzz Yes. Looks good. Checkbox and label are no longer on different lines. That was the problem that @CaptionF described.

The additional problems described in this ticket aren't fixed, but the screenshot I posted is fixed ;)

**Comment by cmonteroluque** [comment]
move to 9.0 then for the remaining issues

**Comment by jancborchardt** [comment]
@PVince81 @MorrisJobke @owncloud/designers for 9.0 we should actually move all the options (can edit, share etc) in a dropdown which is next to the delete function. The dropdown will have an indicator icon if that person can only read (eye, icon-toggle), or write as well (icon-rename).

**Comment by jancborchardt** [comment]
With dropdown, I mean in the same style as the file actions.

**Comment by PVince81** [comment]
@jancborchardt sounds good.

**Comment by bboule** [comment]
Hey guys so it seems like this is cosmetic however it is listed as a green ticket @michaelstingl this has an OC9 milestone I assume this is ok?

**Comment by Xenopathic** [comment]
The share options are now in the sidebar, although the options still don't have a very good layout:

![screenshot_2016-01-04_19-35-07](https://cloud.githubusercontent.com/assets/2016878/12098453/54e9664c-b31a-11e5-931a-3eb90b40c9d0.png)

**Comment by jancborchardt** [comment]
@PVince81 or @MorrisJobke let’s work on using a 3-dot dropdown menu here at the Nuremberg meetup. We should use the same as for the actions menu in files, but I had some problems when playing around with it.

**Comment by michaelstingl** [comment]
With 8.2.3, the can-edit-dropdown-arrow still gets separated from "can edit":

<img width="890" alt="files_-_owncloud_enterprise_edition_and_skype_and_new_case_ _mstingl_owncloud_com__kerio___2772_messages_" src="https://cloud.githubusercontent.com/assets/214010/13875366/bca69166-ecfd-11e5-965f-6fc3ac7b7659.png">

**Comment by PVince81** [comment]
Ok, let me throw in a quick `&nbsp;` for 9.0.1 there.

**Comment by PVince81** [comment]
Boo, even the checkbox can separate itself sometimes...

**Comment by PVince81** [comment]
Turns out it was bit more work, but ok, PR is here https://github.com/owncloud/core/pull/23386.
This will keep the checkboxes together.

**Comment by michaelstingl** [comment]
I've got feedback from a user and I want to forward his input to this discussion:

> It would be much more seamless to have this tabular, i.e. like this:

<img width="687" alt="document1" src="https://cloud.githubusercontent.com/assets/214010/14378110/ba2df560-fd73-11e5-9c88-929f85735eb4.png">

**Comment by PVince81** [comment]
The tabular view is even less readable and would require sticky headers when you scroll down so you don't lose sight. I think this is a no go.

Since the original issue is fixed I'm closing this.

@michaelstingl feel free to reopen if you think otherwise
