### ISSUE TITLE
Admin settings section broken

### ISSUE THREAD

**Issue by fossxplorer** [owncloud/core#18161]
I'm trying to change some settings such as enable email notification for sharing and SMTP settings in admin section, but i can't do any changes. Every time i refresh or access /index.php/settings/admin i'm promoted for username/password as well.
Trying to tick on "Allow users to send mail notification for shared files" i see 
https://examle.com/index.php?redirect_url=%2Findex.php%2Fcore%2Fajax%2Fappconfig.php 200 OK in the console, but the setting is not saved on refresh.

oC log:
{"reqId":"H\/MCWx9KDoT4BxKbtvlv","remoteAddr":"192.168.0.100","app":"no app in context","message":"Current user is not logged in","level":0,"time":"2015-08-10T09:04:45+00:00","method":"POST","url":"\/index.php\/settings\/admin\/mailtest"}

Console:
NetworkError: 401 Unauthorized - https://example.com/index.php/settings/admin/mailtest"

Also i see This server has no working Internet connection. This means that some of the features like mounting external storage, notifications about updates or installation of third-party apps will not work. Accessing files remotely and sending of notification emails might not work, either. We suggest to enable Internet connection for this server if you want to have all features. 
This could be totally unrelated to the above mentioned issues though. I think it does a /remote.php/webdav for a check and that is routed to another backend on my instance.

Versions:

Stable 8.1 (8.1.1)
**Nginx reverse proxy is being used**
PHP 5.5

**Comment by PVince81** [comment]
This sounds like an environment issue if it's asking you to reauth every time
