### ISSUE TITLE
Call to a member function getFileInfo() on null

### ISSUE THREAD

**Issue by mpugler** [owncloud/core#18168]
### Steps to reproduce
1. Set up Domain Controller on Windows Server 2012 R2
2. Install OwnCloud and connect to Active Directory with LDAP
3. Create a new user in AD with Common Name = Hans Test
4. Log into the OwnCloud with that user

### Expected behaviour
A new folder should be created in the data folder containing the folders "cache" and "files"

### Actual behaviour
folders "cache" and "files" are created in the data folder

### Server configuration
Debian GNU/Linux 8.1 (jessie)

Apache/2.4.10 (Debian)

mysql Ver 14.14 Distrib 5.5.44, for debian-linux-gnu (x86_64) using readline 6.3

PHP 5.6.9-0+deb8u1 (cli) (built: Jun  5 2015 11:03:27)
Zend Engine v2.6.0 with Zend 0Pcache v7.0.4-dev

ownCloud 8.1.0 (stable)

fresh install

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

datadirectory = /mnt/OwnCloud
overwrite.cli.url = http://127.0.0.1
dbtype = mysql
version = 8.1.0.8
dbname = owncloud
dbhost = 127.0.0.1
logtimezone = utc
installed = true
ldapignorenamingrules = false

```

mounted network share on windows server 2012 using cifs

no encryption

#### LDAP configuration 

hasmemberoffiltersupport  1
ldapbase: dc=TestDomain,dc=local
ldapbasegroups and ldapbaseusers the same
ldapcachettl: 600
ldapconfigurationactive: 1
ldabexpertusernameattr: samaccountname=%uid
ldapgroupdisplayname: cn
ldapgroupfilter: (&/|(objectclass=group))(|(cn=ownclouduser)))
ldapgroupfiltergroups: ownclouduser
ldapgroupfiltermode: 0
ldapgroupfilterobjectclass: group
ldapgroupmomberassocattr: member
ldaploginfilter: (&(&(|(objectclass=user))(|(|(memberof=cn=ownclouduser,cn=users,dc=testdomain,dc=local)(primarygroupid=1105))))(|(samaccountname=%uid)(samaccounttype=%uid))))
ldaploginfilterattributes: samaccountname;samaccounttype
ldaploginfilteremail: 0
ldaploginfiltermode: 0
ldaploginfilterusername: 1
ldapnestedgroups: 0
ldapnocase: 1
ldappagingsize: 500
ldapport: 389
ldaptls: 0
ldapuserdisplayname: displayname
ldapuserfilter: (&(|(objectclass=user))(|(|(memberof=cn=ownclouduser,cn=users,dc=testdomain,dc=local)(primarygroupid=1105))))
ldapuserfiltergroups: ownclouduser
ldapuserfiltermode: 0
ldapuserfilterobjectclass: user
ldapuuidgroupattribute: auto
ldapuuiduserattribute: auto
turnoffcertcheck: 0
usememberoftodetectmembership: 1



### Client configuration
Iceweasel / Internet Explorer

Debian / Windows Server

#### ownCloud log (data/owncloud.log)

{"reqId":"psCAR1QilIHoZJZQTPVP","remoteAddr":"127.0.0.1","app":"PHP","message":"Call to a member function getFileInfo() on null at \/var\/www\/html\/lib\/private\/files\/filesystem.php#861","level":3,"time":"2015-08-10T09:40:18+00:00"}

**Comment by PVince81** [comment]
Eww, that's weird. So you're saying it creates the user's folders directly under "data" as "data/files" and "data/cache" ?

If that's the case I suspect that somewhere the user id is an empty string.

@blizzz any idea ?

**Comment by blizzz** [comment]
@mpugler I am missing the homeFolderNamingRule setting from your LDAP config.

> ldabexpertusernameattr: samaccountname=%uid

That's definitely wrong, there is no filter in use here. Just use samaccountname and clear the user mappings.

> ldaploginfilter: (&(&(|(objectclass=user))(|(|(memberof=cn=ownclouduser,cn=users,dc=testdomain,dc=local)(primarygroupid=1105))))(|(samaccountname=%uid)(samaccounttype=%uid))))

I did not look up ``samaccounttype`` but this does not  sound to uniquely identify a user, does it? Would not cause the issue anyway, just a heads up.

**Comment by mpugler** [comment]
Thanks for the replies,

homeFolderNamingRule is empty. 

I changed ldapexpertusernameattr to samaccountname only. I also got rid of the samaccounttype.

I might add that every other cn I tried is working fine (I narrowed it down to cn by changing various attributes in the AD). Folders were created as "_****" where the * are random numbers. 
I reinstalled Debian and the DC and i got the same result.

**Comment by blizzz** [comment]
Glad it works for you now!
