### ISSUE TITLE
config amazon s3 error

### ISSUE THREAD

**Issue by novoxudonoser** [owncloud/core#18183]
php5, 8.1, ubuntu, nginx, posgres

config:
```
objectstore' => array(
'class' => 'OCA\ObjectStore\S3',
'arguments' => array(
'key' => 'some',
'secret' => 'some',
'bucket' => 'some',
),
```

logs:
```
{"reqId":"r+yWXa5hUODmf28Pyxed","remoteAddr":"95.32.4.187","app":"PHP","message":"Class 'OCA\\ObjectStore\\S3' not found at \/var\/www\/owncloud\/lib\/private\/util.php#94","level":3,"time":"2015-08-10T18:29:01+00:00"}
```

**Comment by karlitschek** [comment]
Hmm. which S3 app have you installed? This is not part of the normal release. Can you post a full bug report using the template please? https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by RealRancor** [comment]
@karlitschek As @novoxudonoser has posted this also in https://forum.owncloud.org/viewtopic.php?f=31&t=29735 its very likely that the OP is trying to configure a EE feature in the CE.

**Comment by novoxudonoser** [comment]
@RealRancor, it seems you are right, I used this guide:  https://doc.owncloud.org/server/8.0/admin_manual/enterprise_external_storage/s3_swift_as_primary_object_store_configuration.html

**Comment by RealRancor** [comment]
@novoxudonoser 

Yes, then you need the EE from https://www.owncloud.com to get this to work.
