### ISSUE TITLE
After update to 8.1 i got an error cURL error 60: SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by sbh01** [owncloud/core#18189]
When i'm trying to turn on any App, for example, Gallery, i got an error
"cURL error 60: SSL certificate problem: unable to get local issuer certificate"

I'm using selfsigned certificate on my Apache server.
On 8.0.1 version it works fine.
After update to 8.1 i got this error.

**Comment by karlitschek** [comment]
the curl/openssl/php packages on you linux distribution are outdated. please try to move to a more modern distro.
@LukasReschke

**Comment by LukasReschke** [comment]
If you believe that this is a valid bug please edit your issue text to use the issue template. We cannot assist you in any way without these information,

**Comment by yapbreak** [comment]
Hi,
I run into same trouble. I try to grab information from issue https://github.com/owncloud/core/issues/16255
When I reach test.php (the one describes in previous issue) page, I get the following error message:

Type : GuzzleHttp\Exception\RequestException
Code : 0
Message : cURL error 60: SSL certificate problem: unable to get local issuer certificate

Everything was OK yesterday with oC 8.0.5. I update it with oC updater to 8.1.1 this morning and fix the other issue successfully.
I run oC on Archlinux whith:
- Nginx 1.8.0,
- nss 3.19.2
- curl 7.43.0
- php 5.6.12
- openssl 1.0.2d

I use nginx configuration found here https://doc.owncloud.org/server/8.1/admin_manual/installation/nginx_configuration.html

I try to update libcurl to the last curl git version (found here https://github.com/bagder/curl) but nothing better happened!
Moreover, my Nginx is behind sslh but I run into this issue with and without it.

**Comment by yapbreak** [comment]
From command line, curl seems to work properly…

% curl -v -I https://owncloud.org/ http://www.owncloud.org
*   Trying 50.30.33.236...
* Connected to owncloud.org (50.30.33.236) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.0 (IN), TLS handshake, Server hello (2):
* TLSv1.0 (IN), TLS handshake, Certificate (11):
* TLSv1.0 (IN), TLS handshake, Server key exchange (12):
* TLSv1.0 (IN), TLS handshake, Server finished (14):
* TLSv1.0 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.0 (OUT), TLS change cipher, Client hello (1):
* TLSv1.0 (OUT), TLS handshake, Finished (20):
* TLSv1.0 (IN), TLS change cipher, Client hello (1):
* TLSv1.0 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.0 / DHE-RSA-AES128-SHA
* ALPN, server did not agree to a protocol
* Server certificate:
* 	 subject: OU=Domain Control Validated; CN=www.owncloud.org
* 	 start date: 2015-02-09 23:47:38 GMT
* 	 expire date: 2015-12-10 10:32:11 GMT
* 	 subjectAltName: owncloud.org matched
* 	 issuer: C=US; ST=Arizona; L=Scottsdale; O=GoDaddy.com, Inc.; OU=http://certs.godaddy.com/repository/; CN=Go Daddy Secure Certificate Authority - G2
* 	 SSL certificate verify ok.
> HEAD / HTTP/1.1
> Host: owncloud.org
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Date: Wed, 12 Aug 2015 09:32:16 GMT
Date: Wed, 12 Aug 2015 09:32:16 GMT
< Server: Apache
Server: Apache
< X-Frame-Options: SAMEORIGIN
X-Frame-Options: SAMEORIGIN
< Strict-Transport-Security: max-age=31536000
Strict-Transport-Security: max-age=31536000
< X-XSS-Protection: 1; mode=block
X-XSS-Protection: 1; mode=block
< Vary: Accept-Encoding,Cookie
Vary: Accept-Encoding,Cookie
< Cache-Control: max-age=3, must-revalidate
Cache-Control: max-age=3, must-revalidate
< WP-Super-Cache: Served supercache file from PHP
WP-Super-Cache: Served supercache file from PHP
< Content-Type: text/html; charset=UTF-8
Content-Type: text/html; charset=UTF-8

< 
* Connection #0 to host owncloud.org left intact
* Rebuilt URL to: http://www.owncloud.org/
*   Trying 50.30.33.236...
* Connected to www.owncloud.org (50.30.33.236) port 80 (#1)
> HEAD / HTTP/1.1
> Host: www.owncloud.org
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
HTTP/1.1 301 Moved Permanently
< Date: Wed, 12 Aug 2015 09:32:17 GMT
Date: Wed, 12 Aug 2015 09:32:17 GMT
< Server: Apache
Server: Apache
< Location: https://owncloud.org/
Location: https://owncloud.org/
< Content-Type: text/html; charset=iso-8859-1
Content-Type: text/html; charset=iso-8859-1

< 
* Connection #1 to host www.owncloud.org left intact

**Comment by sbh01** [comment]
Sure it work Ok from curl because you are checking oncloud.org domain!
I have this problem with my own domain and with my selfsigned certificate.

**Comment by yapbreak** [comment]
Of course I am checking owncloud.org domain since this request is tested in owncloud to check if instance has access to Internet!

I use a startssl signed certificate on my own instance.

Curl result I posted before are from server and I just wanted to show that, as webserver user on my server, I can access to owncloud domain so I do not understand why I have this cURL error 60 when owncloud itself try to reach owncloud.org domain.

**Comment by yapbreak** [comment]
After more investigation, I have a root certificate registered on my user setting page… My bad. I removed it and everything is back to normal.
