### ISSUE TITLE
Add more Options to Admin-Settings.

### ISSUE THREAD

**Issue by aspdye** [owncloud/core#18199]
I think you should make settings like:

-Force SSL
-Logo changing (directly into Settings)

**Comment by LukasReschke** [comment]
> -Force SSL

Not feasible doable. Should be done via web server config as this has other implications as well.

> -Logo changing (directly into Settings)

Already doable via theming. Offering an interface for something like this makes it easier to break stuff.

**Comment by RealRancor** [comment]
>    -Force SSL
>
>>Not feasible doable. Should be done via web server config as this has other implications as well.

Not only not feasible doable. This was already there in pre-8.1 versions and wasn't removed just for fun.
