### ISSUE TITLE
Remove Apps "loading screen"

### ISSUE THREAD

**Issue by aspdye** [owncloud/core#18197]
Hi,

I think it would be nice, if you click on an app...

-not the complete site is loading new (top-bar and basic-ui should be there always)
-the loading wheel should be removed

What do you think?

**Comment by DeepDiver1975** [comment]
Would indeed be nice, but given the fact that we do not share a common JavaScript framework among all apps this is kind of hard.

**Comment by aspdye** [comment]
Then...maybe you should share :) At least Contacts, Calendar, Mail and Files and other apps designed by the OwnCloud Team could support this. For the 3.party apps you could make this optional, but recommend for the dev's.

**Comment by DeepDiver1975** [comment]
> Then...maybe you should share :) At least Contacts, Calendar, Mail and Files and other apps designed by the OwnCloud Team could support this. For the 3.party apps you could make this optional, but recommend for the dev's.

well ... feel free to come up with a solution - I'll happily discuss the result :wink:

**Comment by PVince81** [comment]
This would probably need a full rewrite of the JS of the core and also of all apps.
A lot of JS code is abusing the global namespace which will likely cause conflicts between apps...

**Comment by karlitschek** [comment]
No full rewrite of all the JS code anytime soon. Thanks

**Comment by DeepDiver1975** [comment]
> No full rewrite of all the JS code anytime soon. Thanks

ACK -> close
