### ISSUE TITLE
Seperate "Files" App from Core / Make it deactivatable

### ISSUE THREAD

**Issue by aspdye** [owncloud/core#18198]
I think "Files" is an app like calendar, contacts and mail. Therefore i think, as a user, you should be able to remove the files app from your ownCloud Instance.

**Comment by DeepDiver1975** [comment]
One day ...

**Comment by aspdye** [comment]
also has advantages: Update the Files-App does not require a complete Update of the OwnCloud-Version :) And you could seperate this on GitHub:

-core (App Platform)
-files (Files-App)

**Comment by PVince81** [comment]
It could be just the files app ui, but not the Webdav interface.
Some other apps might want to access files too (for example the Notes app stores notes as files), so the files API need to stay accessible.

**Comment by DeepDiver1975** [comment]
> It could be just the files app ui, but not the Webdav interface.

having webdav bundled with the files app is kind of :nose: 

we should over time come to a point where we can differentiate between frontend apps and backend apps ... on day

**Comment by jancborchardt** [comment]
Having this as an issue doesn’t really make sense as it’s way off in the future and no one really committed to doing it. @aspdye if you want to do it please coordinate and propose a plan, and then collaborate.
