### ISSUE TITLE
Share button gets blocked if you share a file, leaving the Sharing Dropdown menu and moving the file to a folder.

### ISSUE THREAD

**Issue by davitol** [owncloud/core#18196]
### Steps to reproduce

1. Share a file
2. Without closing the share dropdown menu move the file inside a folder
3. Try to share another file or folder without refreshing the screen

### Expected behaviour

The share button should be enabled

### Actual behaviour

The share button gets blocked but if you refresh the screen it is enabled again

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:"version":"8.1.1.2","versionstring":"8.1.1 RC1"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity: 2.0.1
 - admin_audit: 0.6
 - enterprise_key: 0.1.0
 - files: 1.1.10
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.6
 - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

**Comment by rullzer** [comment]
Yes this is known. It is caused by the javascript handling it all. Hopefully we can fix with the new sidebar (https://github.com/owncloud/core/pull/18185)

**Comment by rullzer** [comment]
@davitol can you verify if this is fixed with the new sidebar? Thanks.

**Comment by davitol** [comment]
@rullzer Yes, with the new sidebar is fixed. Let's close it :+1:
