### ISSUE TITLE
Activate Apps - GuzzleHttp error

### ISSUE THREAD

**Issue by Pingumann** [owncloud/core#18191]
Activation of any Apps provoke error: "    save_to must be a GuzzleHttp\Stream\StreamInterface or resource"

Description on 2 different Forums:
1. https://forum.owncloud.org/viewtopic.php?f=31&t=29561&p=93692#p93692
2. https://github.com/owncloud/core/issues/18088
_______________________________________

Issue with ownCloud 8.1.0 (stable) on CentOS 6 Minimal System (64 Bit) VPS.

uname: 2.6.32-042stab108.2 #1 SMP Tue May 12 18:07:50 MSK 2015 x86_64 x86_64 x86_64 GNU

httpd: httpd -version
Server version: Apache/2.2.15 (Unix)
Server built: Oct 16 2014 14:48:21

mySQL:
mysqld Ver 10.0.20-MariaDB for Linux on x86_64 (MariaDB Server)
Copyright (c) 2000, 2015, Oracle, MariaDB Corporation Ab and others.

PHP:
php --version
PHP 5.4.42 (cli) (built: Jun 10 2015 14:19:12)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies

I updated the VPS CentOS 6.6 (Final) to 6.7 (Final). 116 Packages updated.

The bug is still present. :-/

**Comment by LukasReschke** [comment]
Duplicate. Thus closed.

**Comment by Pingumann** [comment]
Which #?????

**Comment by LukasReschke** [comment]
You linked to it and also wrote at #18088, there is no need to have different issues open for this.
