### ISSUE TITLE
Migration mark few files as encrypted (Module with id: OC_DEFAULT_MODULE does not exist.)

### ISSUE THREAD

**Issue by maystar** [owncloud/core#18206]
### Steps to reproduce
1. Migrate from 8.1 to 8.1.1
2. Try to download each file of each user with client, web ui or webdav

### Expected behaviour
Download should work for all files

### Actual behaviour
Some files can't be downloaded. In the web ui the following error appears: 
```
Module with id: OC_DEFAULT_MODULE does not exist. Please enable it in your apps settings or contact your administrator.
```
The server has never been used the file encryption, but the files which can't be downloaded have the value 1 in the column encrypted in the oc_filecache database. 

Can please anybody provide the sql command which resets the encrypted flag to 0. I'm not familiar with sql. But I've tested this manual for a file. Afterwards it could be downloaded again.

### Server configuration
**Operating system**: opensuse 13.2 

**Web server:** apache 2.4.10

**Database:** mysql 5.6.17

**PHP version:** php 5.6.1

**ownCloud version:** 8.1.1

**Updated from an older ownCloud or fresh install:** updated since owncloud 3

**List of activated apps:**
```
Enabled:
 - activity: 2.0.1
 - bookmarks: 0.4
 - calendar: 0.7.1
 - contacts: 0.4.0.0
 - documents: 0.9.0
 - files: 1.1.9
 - files_external: 0.2.3
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - mozilla_sync: 1.4
 - music: 0.3.5
 - news: 5.3.8
 - tasks: 0.7.1

Disabled:
 - encryption
 - external
 - files_locking
 - files_videoviewer
 - galleryplus
 - provisioning_api
 - search_lucene
 - templateeditor
 - user_external
 - user_ldap
 - user_webdavauth
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'passwordsalt' => '*********************',
  'datadirectory' => '/media/USB-Platte/.data/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'installed' => true,
  'loglevel' => 1,
  'instanceid' => '506360c5c8c8f',
  'maintenance' => false,
  'theme' => '',
  'trusted_domains' => 
  array (
    0 => '*************',
    1 => '***********',
    2 => '**********',
  ),
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'owncloud',
  'mail_domain' => '********',
  'mail_smtphost' => '********',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbuser' => 'ownclouduser',
  'dbpassword' => '*********',
  'mail_smtpport' => '25',
  'secret' => '*****************************',
  'forcessl' => true,
);
```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:**  no

#### ownCloud log (data/owncloud.log)
```
{"reqId":"qZkNkg4yNkU5RXj9zbVk","remoteAddr":"134.28.42.31","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Encryption not ready: Module with id: OC_DEFAULT_MODULE does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(82): OC\\\\Connector\\\\Sabre\\\\File->get()\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/remote.php(132): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#7 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":259}","level":4,"time":"2015-08-11T13:31:51+00:00"}

```

**Comment by maystar** [comment]
Probably related issues:
https://github.com/owncloud/core/issues/17505
https://github.com/owncloud/client/issues/3448

**Comment by maystar** [comment]
Found the sql command: 
```
UPDATE oc_filecache SET encrypted='0' WHERE encrypted='1';
```
It seems that this is a valid workaround for me.

**Comment by PVince81** [comment]
@maystar which 8.1 were you using ? Was it one of the broken betas ?

**Comment by maystar** [comment]
I get the updates from here:
http://download.opensuse.org/repositories/isv:/ownCloud:/community/openSUSE_13.2
So I guess it was no beta.

**Comment by maystar** [comment]
BTW: There were about 1500 of 160000 rows affected in the oc_filecache. 
I'm not sure if it is somehow related: I've got some trouble with the deactivation of server apps during the upgrade. The sharing app was disabled, too. So all "imported" directories where gone right after updating. When I reactivate the app most shared directories got a " (2)" postfix in there name. I have to rename them manually.
Not all shared files were marked as encrypted, but perhaps all pseudo encrypted files are in shared folders.

**Comment by Oliwally** [comment]
I've got the same problem: "OC_DEFAULT_MODULE does not exist. Please enable it in your apps settings or contact your administrator" after upgrading to 8.1.1.3
When I access OC through my browser, I see that error. However my Win client seems to be seeing & opening the files just fine. My android client however is not working any longer - can no longer open files using my phone.

I'd love some more help with this please. I'm only half-witted about this stuff.

Environment: Server hosted by NameCheap
Server: Apache Version 2.2.29
Database: MySQL
Client:Firefox & Chrome
OC-Version: 8.1.1.3
PHP-Version: 5.4.41

**Comment by maystar** [comment]
@Oliwally 
I assume you do not use the encryption app. Before you follow these steps make a data base backup!
- Login to your machine and connect to your data base with something like
```
mysql -p -u ownclouduser owncloud
```
(enter database password)
- Check if there any pseudo encrypted files
```
SELECT `storage`, `path`, `parent`, `name`, `size`, `encrypted` FROM `oc_filecache` WHERE `encrypted` = 1 ;
```
- If output is not empty you can change the encrypted flag with 
```
UPDATE oc_filecache SET encrypted='0' WHERE encrypted='1';
```

**Comment by Oliwally** [comment]
Hi maystar. Thanks so much for helping out. 
No encryption is not enabled now, but was in previous version.

Ok, at the risk of sounding really daft - the only access I have is through cpanel to get to my externally hosted owncloud installation. So, is there a way to do this through phpmyadmin or something like that? Sorry, I need a lot of help...

**Comment by Oliwally** [comment]
I've managed to get into the right area (I think) through phpmyadmin. Attached is a screenshot of my oc_filecache table. Most of the entries there show '0' in the 'encrypted' column. Is that what I'm looking for?
![firefox_screenshot_2015-08-23t11-09-31 849z](https://cloud.githubusercontent.com/assets/5593249/9427976/c7e0e6aa-49db-11e5-80de-6605ac3eaca9.png)

**Comment by maystar** [comment]
You can fire the two sql commands in the SQL tab of phpMyAdmin. 
Can you access your files on the server with ftp or similar to check if they are not encrypted anymore. I wouldn't expect any file to be encrypted if server encryption has been disabled.

**Comment by Oliwally** [comment]
Fantastic, thanks Fabian - that worked in the SQL tab, although it doesn't seem to have solved my problem of the files being unreadable by owncloud via a browser. The original error "OC_DEFAULT_MODULE does not exist. Please enable it in your apps settings or contact your administrator" no longer shows, so I guess that part of it is fixed.

I just re-read what I had written earlier and realize that it was a bit confusing (double negatives due to typo...). So, I had the encryption enabled in my previous version of OC, but I have not re-enabled it my latests update (8.1.1.3). It very much seems that the files are now encrypted, but are not getting de-crypted when I try to open them. I have downloaded some through the cpanel file browser, and they are all 'corrupted' so-to-speak. Could you help me with that at all? How do I re'enable encryption withouth breaking stuff? Perhaps I need to start a new topic because it's not quite the problem indicated in the title of this topic?

Thansk again. I think I need lots more help.

Regards,

Oli

**Comment by maystar** [comment]
Ok, in that case I wouldn't suggest you to change any database values! You should revert all changes. I'm not familiar with the encryption. But when looking for a solution for my issue I found this: https://github.com/owncloud/core/issues/17505#issuecomment-119709169 (from the related issues above)

**Comment by Oliwally** [comment]
Is there a trick to reverting the changes?

**Comment by maystar** [comment]
Restore the backup.

**Comment by Oliwally** [comment]
Hmm, in the end I got tired of playing around with it all and I re-uploaded all my un-encrypted files. I figured that would be faster than solving the problem. I know - a bit of a cop-out...
So now encryption is unfortunately not enabled (I'm scared of it now), and everything seems to be as it should be.
Thanks again for your help Fabian.

**Comment by schiesbn** [comment]
Seems like all problems discussed here are solved.

**Comment by Germano0** [comment]
@maystar you should consider removing your message that states to change the database manually, since it damages Owncloud installation

**Comment by maystar** [comment]
My workaround can help to solve a problem described above. Of course I can't guarantee that it work, produce no other issues or even kill your cat. For me it helps to access my files again. It's up to you to follow these steps. If you know a better way please tell us!
