### ISSUE TITLE
Use SVG sprites or font instead of multiple single SVG files

### ISSUE THREAD

**Issue by ldidry** [owncloud/core#18204]
### Steps to reproduce
1. Use owncloud

### Expected behaviour
The browser should load one SVG file per app, containing all the SVG images of the app and a CSS to use it (see <https://css-tricks.com/svg-fragment-identifiers-work/> to learn about SVG fragment (what I called SVG sprite). You can create SVG fragment easily with <https://icomoon.io/app/>.

This way, there would be only a few HTTP connections (one for SVG, one for CSS, for each app.) instead of a lot (I counted 34 requests for SVG files while using files app). Less HTTP connections means improved loading time.

Caching SVG improves the loading time, but there's no caching headers in web server documentation.

It is possible to use fonts instead of SVG fragments. <https://icomoon.io/app/> can produce fonts too.

### Actual behaviour
Each icon is set with a class, which css contains a `background-image` pointing to a single SVG file.

### Server configuration
**ownCloud version:** 8.1.1

**Comment by oparoz** [comment]
I could be possible to use https://github.com/jkphl/iconizr and generate everything automatically, ready to be integrated into the project.
One problem is that there is already a PNG fallback mechanism in place and that would need to be replaced or updated.
Another is that the barrier to entry would be higher for anyone wanting to add an icon to the project.

cc @jancborchardt

**Comment by raghunayyar** [comment]
I like what I read here. @jancborchardt we should move to SVG sprites, what do you think?

**Comment by jancborchardt** [comment]
@raghunayyar to be discussed for 9.0 probably. :)

**Comment by jancborchardt** [comment]
Closing in favor of  https://github.com/owncloud/core/issues/15531
