### ISSUE TITLE
Quota warning in shared folder don't disappear after leaving shared folder

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/core#18208]
### Steps to reproduce

1. Alice uses 95% of her quota
2. Alice shares folder with Bob
3. Bob opens Alices shared folder ==> notification: "Storage of Alice is almost full (95%)" (on top)
4. Bob leaves Alices shared folder ==> notification don't disappear
5. Bob needs to fully reload the page to get rid of the notification

<img width="673" alt="files - owncloud - quota" src="https://cloud.githubusercontent.com/assets/214010/9201442/7156a80c-404d-11e5-9203-a7be1d30031c.png">

### Expected behaviour

Quota notification should disappear after leaving the quota limited folder.

### Actual behaviour

Quota notification stays forever.

### Server configuration

**ownCloud version:**
oC 8.1.0

**Updated from an older ownCloud or fresh install:**
fresh install

### Client configuration

**Browser:**
Chrome 44

**Operating system:**
Mac OS X

@MorrisJobke 

00003624

**Comment by PVince81** [comment]
Someone should replace OC.Notification.show with OC.Notification.showTemporary for this.

Setting as junior job.

**Comment by MorrisJobke** [comment]
Fix is in #18231

**Comment by MorrisJobke** [comment]
@michaelstingl This fix is in 8.1.2 and 8.2.0

**Comment by michaelstingl** [comment]
@MorrisJobke Thanks!
