### ISSUE TITLE
Switch from Math.floor() to Math.ceil() when sending the dimension to Preview

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#18203]
We're using Math.floor() when we want to round one of the dimensions of an image after applying window.devicePixelRatio, but I think what we really want is Math.ceil(), as otherwise pictures can still end up being a bit blurry since they will be smaller than the expected size.

@PVince81 @jancborchardt , please confirm.

**Comment by PVince81** [comment]
Yeah, makes sense

**Comment by DeepDiver1975** [comment]
PR welcome :wink:

**Comment by jancborchardt** [comment]
I guess if @oparoz and @PVince81 say it makes sense then go for it. :)

**Comment by PVince81** [comment]
@oparoz any update ? Or move to 9.0 ?

**Comment by oparoz** [comment]
We're past feature freeze and this is labelled as enhancement, so the logical step would be to defer, but I can submit a PR if nobody has any objection...

**Comment by DeepDiver1975** [comment]
> but I can submit a PR if nobody has any objection...

no objections - thx
