### ISSUE TITLE
Upgrade to Owncloud 8.0.5

### ISSUE THREAD

**Issue by sebastian312** [owncloud/core#18209]
An exception occurred while executing 'CREATE TABLE `oc_oc_appconfig_trwxfaqm6rm7f` (LIKE `oc_appconfig`)': SQLSTATE[HY000]: General error: 3 Error writing file './cloud/oc_oc_appconfig_trwxfaqm6rm7f.frm' (Errcode: 28)

**Comment by karlitschek** [comment]
Can you post a full bug report using the template please? https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by DeepDiver1975** [comment]
please reopen once all information has been submitted - THX
