### ISSUE TITLE
Incorrect time in activity notification email message

### ISSUE THREAD

**Issue by Jungingen** [owncloud/core#18205]
Owncloud 7.0.4. 
Time zone is set correctlly on server, in PHP, Mysql, but activity notification email still uses GMT+0 time, then informing users about their activity. On application though (file upload, for instance), time is set correctlly.
 Also, in Mysql database, email messages, stored to be processed by Ajax CRON, have timestamp in GMT+0, so it looks like Ajax CRON, then reading messages from database, do not shift time acording to the time zone configured.

Any help is appreciated.

**Comment by karlitschek** [comment]
@nickvergessen

**Comment by nickvergessen** [comment]
Fixed since 8.0.0: https://github.com/owncloud/activity/pull/176

So sorry, but you need to update to 8.0+
Also when you say you run 7.0.4 you should at least update to 7.0.8 so you have the latest updates on your version branch.
