### ISSUE TITLE
Too many highlight states in files list

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#18210]
We currently have:
1) The highlight when selected (checkbox, CSS class "selected")
2) The highlight for the right sidebar (CSS class "highlight")
3) The highlight for the actions menu (CSS class "mouseOver")

![highlight-types](https://cloud.githubusercontent.com/assets/277525/9201601/24b11a90-404e-11e5-8d2b-d238e8e2f3f2.png)

I suggest to try and consolidate these because:
- it is confusing for the user, for example if you used highlight 2) but then Ctrl+Click on another file, the first one wasn't considered as selected
- programmatically it's already a big mess to track which state is supposed to be the focussed one

I suggest to try and merge the states together into one or two states.

If we merge them all into a single one it means that:
- clicking in the middle of a row will tick the checkbox (selection), highlight it and also show the sidebar
- opening the actions menu would auto-select the current row and also display the sidebar. Might not be the best.

@owncloud/designers any better ideas ?

**Comment by jancborchardt** [comment]
@PVince81 I would say that right now the only weird thing is that clicking on the empty space of a row does nothing at all. Can we hook that up to opening the file/folder?

**Comment by PVince81** [comment]
I could revert the change and make it work as it was before: triggering the default action.
But then the question is: how can the user select the row they want to be displayed in the sidebar once it's already open ?

**Comment by PVince81** [comment]
The only remaining ways to update the sidebar contents would be:
1) Select the file by clicking the thumbnail: but this triggers the checkbox, not convenient to move from file to file

2) Clicking the "Share" icon, which might not always be there

3) Opening the file actions menu again, then clicking "Details". But one does not want to do that for every file one by one.

**Comment by jancborchardt** [comment]
Ah right. Then actually the only weird thing is that there’s a row highlight when the sidebar was not opened before, and you click on the empty space. That highlight should only be there when the sidebar was open, to highlight the currently open file.

Otherwise everything is fine then. :)

**Comment by PVince81** [comment]
Just discovered yet another highlight (fourth one) which is used by the keyboard navigation.

**Comment by PVince81** [comment]
Keyboard shortcuts seem to be broken and don't behave as expected, especially when switching lists.
I'd like to move this to 9.0 because it will be a bigger change.

**Comment by cmonteroluque** [comment]
This issue will fall off 8.2 if not resolved by 6 Oct

**Comment by jancborchardt** [comment]
This is basically fixed, or the situation changed a lot. If there’s any follow-up issues, let’s solve them on a case-by-case basis.
