### ISSUE TITLE
PDOException: SQLSTATE[HY000]: General error: 1 cannot commit transaction - SQL statements in progress

### ISSUE THREAD

**Issue by datorexpert** [owncloud/core#18217]
Trying to manually upgrade from v8.0.4 to v8.1.1 and get the error.
I manually copied the new files over the old one.
Permission is set to 777 for all files and directories.
What is wrong?

**Comment by karlitschek** [comment]
can you please post a full bug report using the template? https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by DeepDiver1975** [comment]
Please reopen once all information has been supplied - THX
