### ISSUE TITLE
Undefined index: REQUEST_URI at /var/www/owncloud/apps/contacts/appinfo/app.php#35 

### ISSUE THREAD

**Issue by dersch81** [owncloud/core#18219]
I have this with OC 8.1 as well as 8.1.1.
Error 	PHP 	Undefined index: REQUEST_URI at /var/www/owncloud/apps/contacts/appinfo/app.php#35 	2015-08-11T22:30:06+02:00
Error 	PHP 	Undefined index: REQUEST_URI at /var/www/owncloud/apps/contacts/appinfo/app.php#35 	2015-08-11T22:15:10+02:00
Error 	PHP 	Undefined index: REQUEST_URI at /var/www/owncloud/apps/contacts/appinfo/app.php#35 	2015-08-11T22:00:06+02:00
Error	PHP	Undefined index: REQUEST_URI at /var/www/owncloud/apps/contacts/appinfo/app.php#35	2015-08-11T22:00:06+02:00
Error	PHP	Undefined index: REQUEST_URI at /var/www/owncloud/apps/contacts/appinfo/app.php#35	2015-08-11T21:45:09+02:00
Error	PHP	Undefined index: REQUEST_URI at /var/www/owncloud/apps/contacts/appinfo/app.php#35	2015-08-11T21:30:04+02:00
Error	PHP	Undefined index: REQUEST_URI at /var/www/owncloud/apps/contacts/appinfo/app.php#35	2015-08-11T21:15:07+02:00
Error	PHP	Undefined index: REQUEST_URI at /var/www/owncloud/apps/contacts/appinfo/app.php#35	2015-08-11T21:00:07+02:00
Error	PHP	Undefined index: REQUEST_URI at /var/www/owncloud/apps/contacts/appinfo/app.php#35	2015-08-11T20:45:02+02:00
Error	PHP	Undefined index: REQUEST_URI at /var/www/owncloud/apps/contacts/appinfo/app.php#35	2015-08-11T20:30:06+02:00
Error	PHP	Undefined index: REQUEST_URI at /var/www/owncloud/apps/contacts/appinfo/app.php#35	2015-08-11T20:15:03+02:00
Error	PHP	Undefined index: REQUEST_URI at /var/www/owncloud/apps/contacts/appinfo/app.php#35	2015-08-11T20:00:02+02:00
Error	PHP	Undefined index: REQUEST_URI at /var/www/owncloud/apps/contacts/appinfo/app.php#35	2015-08-11T19:45:06+02:00
Error	PHP	Undefined index: REQUEST_URI at /var/www/owncloud/apps/contacts/appinfo/app.php#35	2015-08-11T19:30:05+02:00
Error	PHP	Undefined index: REQUEST_URI at /var/www/owncloud/apps/contacts/appinfo/app.php#35	2015-08-11T19:15:01+02:00
Error	PHP	Undefined index: REQUEST_URI at /var/www/owncloud/apps/contacts/appinfo/app.php#35	2015-08-11T19:00:09+02:00
Error	PHP	Undefined index: REQUEST_URI at /var/www/owncloud/apps/contacts/appinfo/app.php#35	2015-08-11T18:45:03+02:00
Error	PHP	Undefined index: REQUEST_URI at /var/www/owncloud/apps/contacts/appinfo/app.php#35	2015-08-11T18:30:07+02:00
Error	PHP	Undefined index: REQUEST_URI at /var/www/owncloud/apps/contacts/appinfo/app.php#35	2015-08-11T18:15:06+02:00
Error	PHP	Undefined index: REQUEST_URI at /var/www/owncloud/apps/contacts/appinfo/app.php#35	2015-08-11T18:00:07+02:00
Error	PHP	Undefined index: REQUEST_URI at /var/www/owncloud/apps/contacts/appinfo/app.php#35	2015-08-11T17:45:07+02:00
Error	PHP	Undefined index: REQUEST_URI at /var/www/owncloud/apps/contacts/appinfo/app.php#35	2015-08-11T17:30:04+02:00
Error	PHP	Undefined index: REQUEST_URI at /var/www/owncloud/apps/contacts/appinfo/app.php#35	2015-08-11T17:15:01+02:00
Error	PHP	Undefined index: REQUEST_URI at /var/www/owncloud/apps/contacts/appinfo/app.php#35	2015-08-11T17:00:04+02:00
Error	PHP	Undefined index: REQUEST_URI at /var/www/owncloud/apps/contacts/appinfo/app.php#35	2015-08-11T16:45:05+02:00
Error	PHP	Undefined index: REQUEST_URI at /var/www/owncloud/apps/contacts/appinfo/app.php#35	2015-08-11T16:30:04+02:00
Error	PHP	Undefined index: REQUEST_URI at /var/www/owncloud/apps/contacts/appinfo/app.php#35	2015-08-11T16:15:03+02:00
Error	PHP	Undefined index: REQUEST_URI at /var/www/owncloud/apps/contacts/appinfo/app.php#35	2015-08-11T16:00:03+02:00
Error	PHP	Undefined index: REQUEST_URI at /var/www/owncloud/apps/contacts/appinfo/app.php#35	2015-08-11T15:45:05+02:00
Error	PHP	Undefined index: REQUEST_URI at /var/www/owncloud/apps/contacts/appinfo/app.php#35	2015-08-11T15:30:01+02:00

as you can see very frequent.

Its on a Zentyal 4.0 Server based on Ubunut 14.02

**Comment by karlitschek** [comment]
can you please post a full bug report using the issue template. thanks

**Comment by Xenopathic** [comment]
This is an issue with the Contacts app, and is a known issue. Please see the relevent issue in the Contacts repository.

**Comment by RealRancor** [comment]
Ref: https://github.com/owncloud/contacts/issues/972, needs a new release of the contacts app as requested here: https://github.com/owncloud/contacts/issues/1016
