### ISSUE TITLE
Upgrade to OC 8.1.1 failed

### ISSUE THREAD

**Issue by hitam4450** [owncloud/core#18215]
A few minutes ago i received a message that for my current OC 8.1 installation, that an upgrade was available.

I selected Administration --> Updater -->> update and hit the button at once!

However during the 3rd step I received the following message:

Unable to move /media/www/servers/owncloud.ibt-global.net/_oc-upgrade/8.1.1.3/core/ocs-provider to /media/www/servers/owncloud.ibt-global.net/ocs-provider
And the cursor keeps spinning ........until eternity!

What went wrong & Why ??

After refreshing the tab in FF 39 I received the possibility of hitting the update button once again!

regards, hitam4450

**Comment by LukasReschke** [comment]
Can you please reopen at https://github.com/owncloud/updater? Thanks!
