### ISSUE TITLE
Allow apps to request the full content area (like in mobile mode, with nav hidden) by default

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#18213]
For the Maps app for sure (and maybe for Calendar) it would be very cool if the app can specify to hide the left navigation by default. This is similar to how Google Maps works.

Ideally this would be exposed as a parameter in core. cc @Henni @DJaeger @stefan-niedermann as discussed in https://github.com/owncloud/maps/issues/45#issuecomment-129826878

**Comment by z000ao8q** [comment]
hello,
does anyone still have this on the agenda?
I would like to use this for the mp3 player app also.
Being able to hide app-navigation would make the screen on tablets more usable
