### ISSUE TITLE
Owncloud 8.1.0 Update Notification shows the wrong documentation.

### ISSUE THREAD

**Issue by Tronde** [owncloud/core#18218]
In owncloud 8.1.0 appears the yellow update-notifier at the upper border of the browser window. On click it opens the owncloud 8.0 documentation instead the one for 8.1.

The update-notifier uses the URL https://doc.owncloud.org/server/8.0/admin_manual/maintenance/upgrade.html. But it should use the URL https://doc.owncloud.org/server/8.1/admin_manual/maintenance/upgrade.html instead.

**Comment by DeepDiver1975** [comment]
@rperezb another release check point?

**Comment by LukasReschke** [comment]
That's hard to do since it is caused by the update server: https://updates.owncloud.com/server/?version=8x0x0x7x1382907615.86x1435439812xstablexx2015-02-07T02:34:55+00:00

**Comment by LukasReschke** [comment]
@karlitschek ^

**Comment by DeepDiver1975** [comment]
THX @LukasReschke

**Comment by DeepDiver1975** [comment]
I just fixed it
