### ISSUE TITLE
Server does not send email notifications via smtp when set to AJAX

### ISSUE THREAD

**Issue by Isonite** [owncloud/core#18226]
When the server is set to AJAX, it does not send notification emails about shared files, deleted files, etc.

When the server is set to Cron, it sends emails as expected. I had to follow the instructions in the documentation to add the cronjob to crontab to get this to work.

In either setup, sending a test email is successful.

It this the expected behavior? If so, should it notify the user that they will not get messages using AJAX?

I am using ownCloud 8.1.1.

**Comment by karlitschek** [comment]
it should send notifications too. Just a bit delayed because someone has to login and use the system to trigger a background sending job.

**Comment by Isonite** [comment]
That makes sense. But that's not what happened. I had my server set to AJAX for about two weeks and didn't get a single email.

Is there any difference between the background tasks that are run?
