### ISSUE TITLE
Exception: App can't be installed because it contains the true tag which is not allowed for non shipped apps

### ISSUE THREAD

**Issue by Thomanji** [owncloud/core#18220]
Hi, I upgrated to 8.1.1 and all worked fine from the rero. However the first time I go to the browser and access it it asks me to upgrade to 8.1.1 and if I click to start the upgrade I get the following:

Updating ownCloud to version 8.1.1, this may take a while.

Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Updated "files" to 1.1.10
Exception: App can't be installed because it contains the true tag which is not allowed for non shipped apps
The update was unsuccessful. Please report this issue to the ownCloud community.

What Can I do to get this to complete? What does this error message mean?

Thank you for the help.

Best wishes,
Thomas

**Comment by Thomanji** [comment]
This was resolved.
the solution was to run the upgrate in the command prompt instead.

./occ upgrade

This did work, I think maybe the error happened because the config.php file was not writable.

Thank you,
Thomas

**Comment by DeepDiver1975** [comment]
@rperezb please verify this upgrade procedure. Smells fishy

**Comment by rperezb** [comment]
@jvillafanez this one is for you,

thx!

**Comment by jvillafanez** [comment]
@Thomanji could you provide the list of installed apps? I haven't been able to reproduce the issue with the default apps that come by default, neither through web nor console.

I'm upgrading from 8.1.0 to 8.1.1. If this isn't your case, please add the info too.

**Comment by Thomanji** [comment]
Hi,
I try my best since I made it work after using the occ command instead of the browser login.
I use the repro to do updated on my CentOS and I uprated from 8.1.0-19.1  to  8.1.1-12.1. However the upgrade to 8.1.1-12.1 was part of a huge 325 packages uprate because in my list was also the upgrade from CentOS 6.6 to 6.7.  So it might not be a case that happens to others. Also using the ssh and doing ./occ upgrade worked and my OwnCloud seems to work fine now.

For info, here is my app list:
./occ app:list
Enabled:
 - activity: 2.0.1
 - external: 1.2
 - files: 1.1.10
 - files_antivirus: 0.7.0.1
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - templateeditor: 0.1
Disabled:
 - bookmarks
 - calendar
 - contacts
 - dashboard
 - direct_menu
 - documents
 - encryption
 - files_external
 - files_locking
 - files_versions
 - gallery
 - galleryplus
 - ownnote
 - provisioning_api
 - user_external
 - user_ldap
 - user_webdavauth

Its actually strange because I see lots of stuff seems to be disabled now that was enabled before. This included bookmarks, calendar, contacts, dashboard, documents, gallery and ownnote. Its strange but I did not disable them. I still remember last week to fight to get the documents to work using libreoffice.

I actually only wanted to share that this happened and that it was resolved using the manual uprate.

I have enabled my apps again that somehow diabled themselfes on this upgrate:

./occ app:list
Enabled:
 - activity: 2.0.1
 - bookmarks: 0.4
 - calendar: 0.7.2
 - contacts: 0.4.0.0
 - dashboard: 1.6.0beta
 - direct_menu: 0.3
 - documents: 0.10.0
 - external: 1.2
 - files: 1.1.10
 - files_antivirus: 0.7.0.1
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - galleryplus: 13.0.0
 - ownnote: 1.05
 - templateeditor: 0.1
Disabled:
 - encryption
 - files_external
 - files_locking
 - files_versions
 - gallery
 - provisioning_api
 - user_external
 - user_ldap
 - user_webdavauth

I tested it after enabling them and all seems to be fine. So just take this as a note and maybe it helps someone else should this error come up for someone else.

Thank you for the quick attention to this ticket. It appriciate it.

**Comment by jvillafanez** [comment]
I guess it could be related to https://github.com/owncloud/core/issues/18043

**Comment by RealRancor** [comment]
@Thomanji 
> I have enabled my apps again that somehow diabled themselfes on this upgrate

Thats the expected behavior as 3rdparty / non-shipped apps (like calendar, contacts or bookmark) are known to break oC if they are not compatible with the new version.

**Comment by Thomanji** [comment]
@RealRancor thank you for the explenation, makes sense to do this.
