### ISSUE TITLE
Sidebar not shown if the share one is shown

### ISSUE THREAD

**Issue by rperezb** [owncloud/core#18223]
### Steps to reproduce
1. Click on share link
2. Click on ...

### Expected behaviour
Share menu dissapears

### Actual behaviour
Share menu keeps on the view and the ... menu is below

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.2.0.4","versionstring":"8.2 pre alpha","edition":""}

Browser: FF

![screen shot 2015-08-12 at 9 22 35](https://cloud.githubusercontent.com/assets/1846927/9218618/2a5c98ee-40d4-11e5-8584-b38d035676ab.png)

**Comment by DeepDiver1975** [comment]
@rperezb the share dialog is currently being moved to the sidebar - I would not expect this to work properly in the current state.

@blizzz @PVince81

**Comment by PVince81** [comment]
Let's keep it open for now. Some things don't work properly yet.

**Comment by jancborchardt** [comment]
Will be fixed with the share dialog being moved to the sidebar. Closing because this will be irrelevant. https://github.com/owncloud/core/pull/18185
