### ISSUE TITLE
File and directorry permissions

### ISSUE THREAD

**Issue by Thomanji** [owncloud/core#18221]
Hi,

I wonder if there is anywhere a list of r&w permission for files and directorries within owncloud?
I would like to go trugh and ensure all files are having the minimum permissions required for the cloud to work.

Best wishes,
Thomas

**Comment by DeepDiver1975** [comment]
> I wonder if there is anywhere a list of r&w permission for files and directorries within owncloud?

We don't have anything like that in detail.

The only requirements we have (which are checked within the code base):
the web server/php user has to be owner and requires full write permissions on:
- config folder
- config/config.php file
- data folder and any contents
- apps folder (if appstore enabled)

Hope this helps.

Take care
