### ISSUE TITLE
Filepicker: Can't select multiple files on Mac OS X

### ISSUE THREAD

**Issue by petermueller87** [owncloud/core#18228]
https://github.com/owncloud/core/blob/eb13cb8d75634c0423dbcde4b0f55239c0dfb1e7/core/js/oc-dialogs.js#L720

### Steps to reproduce
1. Open the Filepicker using `OC.dialogs.filepicker`
2. Try to select multiple files on Mac OS X
3. It doesn't work. As Ctrl+click shows the browser's context menu on OS X, one should rely on another meta key to select multiple files instead.

### Expected behaviour
You should be able to select multiple files

### Actual behaviour
You can't select multiple files

### Client OS
Mac OS X

### ownCloud version
8.1

**Comment by karlitschek** [comment]
Can you please post a full an meaningful bug report using the issue template?
Please note that ownCloud doesn't pick any modifier keys. This is done by the browser.

**Comment by petermueller87** [comment]
Please reopen. I have added further details as requested.

**Comment by Kawohl** [comment]
closed since it is handled here https://github.com/owncloud/core/issues/18282
