### ISSUE TITLE
Issue with external storage On Centos 7

### ISSUE THREAD

**Issue by gbusoni** [owncloud/core#18233]
### Steps to reproduce
1. Install OS on VM run on Hyperv-V
2. Add VM to active directory
3. Install owncloud from repositories for CentOs
4. Enable External storage and LDAP support
5. Add external storage network share running on WIN2012R2 server with either fixed credentials or user credentials

### Expected behaviour
The folders of the share should be shown in the user account when the user logs in

### Actual behaviour
For fixed credentials: folder is shown, but when I open it is shown as empty. If I try to upload anything it gets uploaded but I get error and the files is not shown.
For user credentials folder is not even shown in the user account.

### Server configuration
**Operating system**: Centos 7

**Web server:** Apache bundled with occ

**Database:** mysql 5.6.25 for windows running on LAN server

**PHP version:** 5.4

**ownCloud version:** 8.1.1

**Updated from an older ownCloud or fresh install:** installed 8.1, update to 8.1.1

**List of activated apps:**

http://postimg.org/image/9g74fmrix/

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => 'ocg5e289j4gu',
  'passwordsalt' => 'XXX',
  'secret' => 'XXX',
  'trusted_domains' =>
  array (
    0 => 'localhost',
    1 => 'cloud1.busoni.local',
    2 => 'cloud.busoni.it',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'overwrite.cli.url' => 'http://localhost/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'dbname' => 'owncloud',
  'dbhost' => 'sql1.busoni.local',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin',
  'dbpassword' => 'XXX',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_from_address' => 'administrator',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'busoni.it',
  'mail_smtphost' => 'exch1.busoni.local',
  'mail_smtpport' => '25',
  'mail_smtpauthtype' => 'PLAIN',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'administrator@busoni.local',
  'mail_smtppassword' => 'XXX',
  'ldapIgnoreNamingRules' => false,
  'maintenance' => false,
  'loglevel' => 2,
);

**Are you using external storage, if yes which one: SMB

**Are you using encryption: NO

**Are you using an external user-backend, if yes which one: ACTIVE DIRECTORY on WIN2012R2.

+-------------------------------+--------------------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                                    |
+-------------------------------+--------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                      |
| hasPagedResultSupport         |                                                                                                        |
| homeFolderNamingRule          |                                                                                                        |
| lastJpegPhotoLookup           | 0                                                                                                      |
| ldapAgentName                 | CN=owncloud,CN=Users,DC=busoni,DC=local                                                                |
| ldapAgentPassword             | ***                                                                                                    |
| ldapAttributesForGroupSearch  | sAMAccountName                                                                                         |
| ldapAttributesForUserSearch   | sAMAccountName;mail                                                                                    |
| ldapBackupHost                | dc3.busoni.local                                                                                       |
| ldapBackupPort                | 389                                                                                                    |
| ldapBase                      | CN=Users,DC=busoni,DC=local                                                                            |
| ldapBaseGroups                | CN=Users,DC=busoni,DC=local                                                                            |
| ldapBaseUsers                 | CN=Users,DC=busoni,DC=local                                                                            |
| ldapCacheTTL                  | 600                                                                                                    |
| ldapConfigurationActive       | 1                                                                                                      |
| ldapEmailAttribute            | mail                                                                                                   |
| ldapExperiencedAdmin          | 0                                                                                                      |
| ldapExpertUUIDGroupAttr       |                                                                                                        |
| ldapExpertUUIDUserAttr        |                                                                                                        |
| ldapExpertUsernameAttr        | sAMAccountName                                                                                         |
| ldapGroupDisplayName          | cn                                                                                                     |
| ldapGroupFilter               | (&(|(objectclass=group))(|(cn=ocusers)))                                                               |
| ldapGroupFilterGroups         | ocusers                                                                                                |
| ldapGroupFilterMode           | 0                                                                                                      |
| ldapGroupFilterObjectclass    | group                                                                                                  |
| ldapGroupMemberAssocAttr      | member                                                                                                 |
| ldapHost                      | dc1.busoni.local                                                                                       |
| ldapIgnoreNamingRules         |                                                                                                        |
| ldapLoginFilter               | sAMAccountName=%uid                                                                                    |
| ldapLoginFilterAttributes     |                                                                                                        |
| ldapLoginFilterEmail          | 1                                                                                                      |
| ldapLoginFilterMode           | 1                                                                                                      |
| ldapLoginFilterUsername       | 1                                                                                                      |
| ldapNestedGroups              | 0                                                                                                      |
| ldapNoCase                    | 1                                                                                                      |
| ldapOverrideMainServer        |                                                                                                        |
| ldapPagingSize                | 500                                                                                                    |
| ldapPort                      | 389                                                                                                    |
| ldapQuotaAttribute            |                                                                                                        |
| ldapQuotaDefault              | 1024                                                                                                   |
| ldapTLS                       | 0                                                                                                      |
| ldapUserDisplayName           | sAMAccountName                                                                                         |
| ldapUserFilter                | (&(|(objectclass=person))(|(|(memberof=CN=ocusers,CN=Users,DC=busoni,DC=local)(primaryGroupID=8113)))) |
| ldapUserFilterGroups          | ocusers                                                                                                |
| ldapUserFilterMode            | 0                                                                                                      |
| ldapUserFilterObjectclass     | person                                                                                                 |
| ldapUuidGroupAttribute        | auto                                                                                                   |
| ldapUuidUserAttribute         | auto                                                                                                   |
| turnOffCertCheck              | 1                                                                                                      |
| useMemberOfToDetectMembership | 1                                                                                                      |
+-------------------------------+--------------------------------------------------------------------------------------------------------+

### Client configuration
**Browser: IE, Firefox, Chrome

**Operating system: Windows 8.1

#### Web server error log

[Sun Aug 09 03:30:02.177640 2015] [auth_digest:notice] [pid 1189] AH01757: generating secret for digest authentication ...
[Sun Aug 09 03:30:02.178741 2015] [lbmethod_heartbeat:notice] [pid 1189] AH02282: No slotmem from mod_heartmonitor
[Sun Aug 09 03:30:02.290749 2015] [mpm_prefork:notice] [pid 1189] AH00163: Apache/2.4.6 (CentOS) PHP/5.4.16 configured -- resuming normal operations
[Sun Aug 09 03:30:02.290772 2015] [core:notice] [pid 1189] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Sun Aug 09 03:38:50.423981 2015] [authz_core:error] [pid 14356] [client 192.168.1.206:55784] AH01630: client denied by server configuration: /var/www/html/owncloud/data/htaccesstest.txt
[Sun Aug 09 03:40:03.702067 2015] [:error] [pid 14358] [client 192.168.1.41:61946] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 65552 bytes) in /var/www/html/owncloud/lib/private/log.php on line 201, referer: http://cloud.busoni.it:8081/owncloud/index.php/settings/admin
[Sun Aug 09 03:40:03.917148 2015] [:error] [pid 14357] [client 192.168.1.41:61743] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 65552 bytes) in /var/www/html/owncloud/lib/private/log.php on line 201, referer: http://cloud.busoni.it:8081/owncloud/index.php/settings/admin
[Sun Aug 09 10:56:18.640708 2015] [autoindex:error] [pid 14458] [client 183.60.48.25:24257] AH01276: Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.html,index.php) found, and server-generated directory index forbidden by Options directive
[Sun Aug 09 18:42:10.594800 2015] [authz_core:error] [pid 14358] [client 192.168.1.206:55823] AH01630: client denied by server configuration: /var/www/html/owncloud/data/htaccesstest.txt
[Sun Aug 09 18:43:20.722286 2015] [:error] [pid 14354] [client 192.168.1.41:52445] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 65552 bytes) in /var/www/html/owncloud/lib/private/log.php on line 201, referer: http://cloud.busoni.it:8081/owncloud/index.php/settings/admin
[Sun Aug 09 18:43:21.055224 2015] [:error] [pid 14356] [client 192.168.1.41:52360] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 65552 bytes) in /var/www/html/owncloud/lib/private/log.php on line 201, referer: http://cloud.busoni.it:8081/owncloud/index.php/settings/admin
[Mon Aug 10 00:47:35.942081 2015] [authz_core:error] [pid 14358] [client 192.168.1.206:55888] AH01630: client denied by server configuration: /var/www/html/owncloud/data/htaccesstest.txt
[Mon Aug 10 00:48:54.201908 2015] [:error] [pid 14355] [client 192.168.1.41:59334] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 65552 bytes) in /var/www/html/owncloud/lib/private/log.php on line 201, referer: http://cloud.busoni.it:8081/owncloud/index.php/settings/admin
[Mon Aug 10 00:48:54.928300 2015] [:error] [pid 14458] [client 192.168.1.41:59331] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 65552 bytes) in /var/www/html/owncloud/lib/private/log.php on line 201, referer: http://cloud.busoni.it:8081/owncloud/index.php/settings/admin
[Mon Aug 10 00:51:24.702856 2015] [mpm_prefork:notice] [pid 1189] AH00170: caught SIGWINCH, shutting down gracefully
[Mon Aug 10 00:51:27.005777 2015] [suexec:notice] [pid 26575] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Mon Aug 10 00:51:27.076068 2015] [auth_digest:notice] [pid 26575] AH01757: generating secret for digest authentication ...
[Mon Aug 10 00:51:27.076774 2015] [lbmethod_heartbeat:notice] [pid 26575] AH02282: No slotmem from mod_heartmonitor
[Mon Aug 10 00:51:27.188897 2015] [mpm_prefork:notice] [pid 26575] AH00163: Apache/2.4.6 (CentOS) PHP/5.4.16 configured -- resuming normal operations
[Mon Aug 10 00:51:27.188926 2015] [core:notice] [pid 26575] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Mon Aug 10 00:54:04.827241 2015] [:error] [pid 26579] [client 192.168.1.41:59418] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 65552 bytes) in /var/www/html/owncloud/lib/private/log.php on line 201, referer: http://cloud.busoni.it:8081/owncloud/index.php/settings/admin
[Mon Aug 10 00:54:25.903750 2015] [authz_core:error] [pid 26579] [client 192.168.1.206:56088] AH01630: client denied by server configuration: /var/www/html/owncloud/data/htaccesstest.txt
[Mon Aug 10 00:55:44.140702 2015] [authz_core:error] [pid 26624] [client 192.168.1.206:56143] AH01630: client denied by server configuration: /var/www/html/owncloud/data/htaccesstest.txt
[Mon Aug 10 00:56:44.342735 2015] [authz_core:error] [pid 26581] [client 192.168.1.206:56179] AH01630: client denied by server configuration: /var/www/html/owncloud/data/htaccesstest.txt
[Mon Aug 10 00:57:13.094430 2015] [:error] [pid 26694] [client 192.168.1.41:59492] PHP Fatal error:  Call to a member function getMimetype() on a non-object in /var/www/html/owncloud/apps/files/lib/helper.php on line 77, referer: http://cloud.busoni.it:8081/owncloud/index.php/apps/files/?dir=%2FArchivio
[Mon Aug 10 00:58:00.581195 2015] [authz_core:error] [pid 26637] [client 192.168.1.206:56220] AH01630: client denied by server configuration: /var/www/html/owncloud/data/htaccesstest.txt
[Mon Aug 10 00:58:12.492986 2015] [:error] [pid 26724] [client 192.168.1.41:59504] PHP Fatal error:  Call to a member function getMimetype() on a non-object in /var/www/html/owncloud/apps/files/lib/helper.php on line 77, referer: http://cloud.busoni.it:8081/owncloud/index.php/apps/files/?dir=%2FArchivio
[Mon Aug 10 00:58:42.891166 2015] [authz_core:error] [pid 26624] [client 192.168.1.206:56261] AH01630: client denied by server configuration: /var/www/html/owncloud/data/htaccesstest.txt
[Mon Aug 10 01:02:01.741294 2015] [authz_core:error] [pid 26755] [client 192.168.1.206:56418] AH01630: client denied by server configuration: /var/www/html/owncloud/data/htaccesstest.txt
[Mon Aug 10 07:13:49.501682 2015] [suexec:notice] [pid 1169] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Mon Aug 10 07:13:49.609650 2015] [auth_digest:notice] [pid 1169] AH01757: generating secret for digest authentication ...
[Mon Aug 10 07:13:49.611180 2015] [lbmethod_heartbeat:notice] [pid 1169] AH02282: No slotmem from mod_heartmonitor
[Mon Aug 10 07:13:50.068081 2015] [mpm_prefork:notice] [pid 1169] AH00163: Apache/2.4.6 (CentOS) PHP/5.4.16 configured -- resuming normal operations
[Mon Aug 10 07:13:50.068158 2015] [core:notice] [pid 1169] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Mon Aug 10 10:58:22.366183 2015] [autoindex:error] [pid 1308] [client 183.60.48.25:40428] AH01276: Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.html,index.php) found, and server-generated directory index forbidden by Options directive
[Mon Aug 10 13:45:15.315650 2015] [authz_core:error] [pid 1304] [client 192.168.1.206:38445] AH01630: client denied by server configuration: /var/www/html/owncloud/data/htaccesstest.txt
[Mon Aug 10 15:45:33.479361 2015] [authz_core:error] [pid 1307] [client 192.168.1.206:38519] AH01630: client denied by server configuration: /var/www/html/owncloud/data/htaccesstest.txt
[Mon Aug 10 17:32:20.104055 2015] [authz_core:error] [pid 8777] [client 192.168.1.206:38603] AH01630: client denied by server configuration: /var/www/html/owncloud/data/htaccesstest.txt
[Mon Aug 10 20:40:11.534668 2015] [authz_core:error] [pid 1304] [client 192.168.1.206:38639] AH01630: client denied by server configuration: /var/www/html/owncloud/data/htaccesstest.txt
[Mon Aug 10 23:52:41.737396 2015] [authz_core:error] [pid 1304] [client 192.168.1.206:38682] AH01630: client denied by server configuration: /var/www/html/owncloud/data/htaccesstest.txt
[Tue Aug 11 00:47:36.483574 2015] [authz_core:error] [pid 12667] [client 192.168.1.206:38804] AH01630: client denied by server configuration: /var/www/html/owncloud/data/htaccesstest.txt
[Tue Aug 11 00:50:01.150987 2015] [:error] [pid 6374] [client 192.168.1.41:53269] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 65552 bytes) in /var/www/html/owncloud/lib/private/log.php on line 201, referer: http://cloud.busoni.it:8081/owncloud/index.php/apps/files/?dir=%2FArchivio
[Tue Aug 11 00:50:55.858493 2015] [authz_core:error] [pid 8777] [client 192.168.1.206:38840] AH01630: client denied by server configuration: /var/www/html/owncloud/data/htaccesstest.txt
[Tue Aug 11 00:52:08.819691 2015] [:error] [pid 12667] [client 192.168.1.41:53289] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 65552 bytes) in /var/www/html/owncloud/lib/private/log.php on line 201, referer: http://cloud.busoni.it:8081/owncloud/index.php/settings/admin
[Tue Aug 11 00:52:09.734313 2015] [:error] [pid 7624] [client 192.168.1.41:53290] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 65552 bytes) in /var/www/html/owncloud/lib/private/log.php on line 201, referer: http://cloud.busoni.it:8081/owncloud/index.php/settings/admin
[Tue Aug 11 00:53:02.759506 2015] [:error] [pid 6377] [client 192.168.1.41:53331] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 65552 bytes) in /var/www/html/owncloud/lib/private/log.php on line 201, referer: http://cloud.busoni.it:8081/owncloud/index.php/apps/files/?dir=%2FArchivio
[Tue Aug 11 01:05:53.209805 2015] [:error] [pid 13339] [client 192.168.1.41:53505] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 65552 bytes) in /var/www/html/owncloud/lib/private/log.php on line 201, referer: http://cloud.busoni.it:8081/owncloud/index.php/apps/files/?dir=%2FArchivio
[Tue Aug 11 01:13:29.631231 2015] [authz_core:error] [pid 14539] [client 192.168.1.206:38896] AH01630: client denied by server configuration: /var/www/html/owncloud/data/htaccesstest.txt
[Tue Aug 11 01:14:11.602404 2015] [authz_core:error] [pid 14539] [client 192.168.1.206:38961] AH01630: client denied by server configuration: /var/www/html/owncloud/data/htaccesstest.txt
[Tue Aug 11 01:14:39.774965 2015] [:error] [pid 8777] [client 192.168.1.41:53561] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 65552 bytes) in /var/www/html/owncloud/lib/private/log.php on line 201
[Tue Aug 11 01:15:19.413000 2015] [:error] [pid 7624] [client 192.168.1.41:53570] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 65552 bytes) in /var/www/html/owncloud/lib/private/log.php on line 201, referer: http://cloud.busoni.it:8081/owncloud/index.php/settings/admin
[Tue Aug 11 01:15:19.450504 2015] [:error] [pid 12667] [client 192.168.1.41:53569] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 65552 bytes) in /var/www/html/owncloud/lib/private/log.php on line 201, referer: http://cloud.busoni.it:8081/owncloud/index.php/settings/admin
[Tue Aug 11 01:15:49.077267 2015] [:error] [pid 6377] [client 192.168.1.41:53591] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 65552 bytes) in /var/www/html/owncloud/lib/private/log.php on line 201, referer: http://cloud.busoni.it:8081/owncloud/index.php/settings/admin
[Tue Aug 11 03:16:00.060619 2015] [autoindex:error] [pid 8777] [client 192.168.1.203:56553] AH01276: Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.html,index.php) found, and server-generated directory index forbidden by Options directive
[Tue Aug 11 12:38:20.385136 2015] [authz_core:error] [pid 6380] [client 192.168.1.206:39195] AH01630: client denied by server configuration: /var/www/html/owncloud/data/htaccesstest.txt
[Tue Aug 11 12:39:18.335225 2015] [:error] [pid 10683] [client 192.168.1.41:52030] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 65552 bytes) in /var/www/html/owncloud/lib/private/log.php on line 201, referer: http://cloud.busoni.it:8081/owncloud/index.php/settings/admin
[Tue Aug 11 20:17:39.737418 2015] [mpm_prefork:notice] [pid 1169] AH00170: caught SIGWINCH, shutting down gracefully
[Tue Aug 11 20:17:41.413228 2015] [suexec:notice] [pid 25304] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Tue Aug 11 20:17:41.452675 2015] [auth_digest:notice] [pid 25304] AH01757: generating secret for digest authentication ...
[Tue Aug 11 20:17:41.453816 2015] [lbmethod_heartbeat:notice] [pid 25304] AH02282: No slotmem from mod_heartmonitor
[Tue Aug 11 20:17:41.489398 2015] [mpm_prefork:notice] [pid 25304] AH00163: Apache/2.4.6 (CentOS) PHP/5.4.16 configured -- resuming normal operations
[Tue Aug 11 20:17:41.489438 2015] [core:notice] [pid 25304] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Wed Aug 12 07:30:22.237283 2015] [authz_core:error] [pid 31483] [client 192.168.1.206:39415] AH01630: client denied by server configuration: /var/www/html/owncloud/data/htaccesstest.txt
[Wed Aug 12 07:31:08.621148 2015] [authz_core:error] [pid 25306] [client 192.168.1.206:39482] AH01630: client denied by server configuration: /var/www/html/owncloud/data/htaccesstest.txt
[Wed Aug 12 12:41:29.346288 2015] [authz_core:error] [pid 31499] [client 192.168.1.206:39520] AH01630: client denied by server configuration: /var/www/html/owncloud/data/htaccesstest.txt
[Wed Aug 12 12:57:25.198160 2015] [authz_core:error] [pid 25307] [client 192.168.1.206:39578] AH01630: client denied by server configuration: /var/www/html/owncloud/data/htaccesstest.txt
[Wed Aug 12 12:58:07.522021 2015] [authz_core:error] [pid 34340] [client 192.168.1.206:39641] AH01630: client denied by server configuration: /var/www/html/owncloud/data/htaccesstest.txt
[Wed Aug 12 14:38:34.937254 2015] [:error] [pid 34594] [client ::1:56126] PHP Warning:  phpinfo(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /var/www/html/info.php on line 2
[Wed Aug 12 14:38:34.957217 2015] [:error] [pid 34340] [client ::1:56128] PHP Warning:  mysql_connect(): Access denied for user 'owncloud'@'cloud.busoni.it' (using password: YES) in /var/www/html/mysql.php on line 2

#### ownCloud log (data/owncloud.log)

{"reqId":"VcfaH7VaG9S7UwInBGQ7aAAAAAM","remoteAddr":"192.168.1.41","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-08-09T22:54:24+00:00"}
{"reqId":"VcfabVdsGNZm5rXM7yrL@gAAAAQ","remoteAddr":"192.168.1.41","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-08-09T22:55:41+00:00"}
{"reqId":"VcfaqduidQXnCPMbyGXGEAAAAAk","remoteAddr":"192.168.1.41","app":"core","message":"Exception while scanning storage \"smb::foo@192.168.1.200\/e$\/\/\": Icewind\\SMB\\Exception\\AuthenticationException: ","level":3,"time":"2015-08-09T22:56:42+00:00"}
{"reqId":"VcfaquhClwMEaeEO6Zb3CQAAAAA","remoteAddr":"192.168.1.41","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-08-09T22:56:42+00:00"}
{"reqId":"VcfayNEAKoOzkhYWV1d@wAAAAAI","remoteAddr":"192.168.1.41","app":"PHP","message":"Argument 1 passed to OCA\\Files\\Helper::formatFileInfo() must implement interface OCP\\Files\\FileInfo, boolean given, called in \/var\/www\/html\/owncloud\/apps\/files\/ajax\/newfile.php on line 99 and defined at \/var\/www\/html\/owncloud\/apps\/files\/lib\/helper.php#135","level":3,"time":"2015-08-09T22:57:13+00:00"}
{"reqId":"VcfayNEAKoOzkhYWV1d@wAAAAAI","remoteAddr":"192.168.1.41","app":"PHP","message":"Call to a member function getMimetype() on a non-object at \/var\/www\/html\/owncloud\/apps\/files\/lib\/helper.php#77","level":3,"time":"2015-08-09T22:57:13+00:00"}
{"reqId":"Vcfa9ITBpQW3g31CYYXDFgAAAAc","remoteAddr":"192.168.1.41","app":"core","message":"Exception while scanning storage \"smb::foo@192.168.1.200\/e$\/\/\": Icewind\\SMB\\Exception\\AuthenticationException: ","level":3,"time":"2015-08-09T22:57:57+00:00"}
{"reqId":"Vcfa9plUBZD81hNzw1UwZAAAAAY","remoteAddr":"192.168.1.41","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-08-09T22:57:59+00:00"}
{"reqId":"VcfbAfiTEQoHuO@6K6p75wAAAAE","remoteAddr":"192.168.1.41","app":"PHP","message":"Argument 1 passed to OCA\\Files\\Helper::formatFileInfo() must implement interface OCP\\Files\\FileInfo, boolean given, called in \/var\/www\/html\/owncloud\/apps\/files\/ajax\/newfile.php on line 99 and defined at \/var\/www\/html\/owncloud\/apps\/files\/lib\/helper.php#135","level":3,"time":"2015-08-09T22:58:12+00:00"}
{"reqId":"VcfbAfiTEQoHuO@6K6p75wAAAAE","remoteAddr":"192.168.1.41","app":"PHP","message":"Call to a member function getMimetype() on a non-object at \/var\/www\/html\/owncloud\/apps\/files\/lib\/helper.php#77","level":3,"time":"2015-08-09T22:58:12+00:00"}
{"reqId":"VcfbHduidQXnCPMbyGXGMgAAAAk","remoteAddr":"192.168.1.41","app":"core","message":"Exception while scanning storage \"smb::foo@192.168.1.200\/e$\/\/\": Icewind\\SMB\\Exception\\AuthenticationException: ","level":3,"time":"2015-08-09T22:58:40+00:00"}
{"reqId":"VcfbH4TBpQW3g31CYYXDNwAAAAc","remoteAddr":"192.168.1.41","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-08-09T22:58:42+00:00"}
{"reqId":"Vcfb3PW6gNPdOXwz62J-LgAAAA4","remoteAddr":"192.168.1.41","app":"core","message":"Exception while scanning storage \"smb::foo@192.168.1.200\/e$\/\/FILE SERVER\/documenti\/giorgiobusoni\/\": Icewind\\SMB\\Exception\\AuthenticationException: ","level":3,"time":"2015-08-09T23:01:49+00:00"}
{"reqId":"Vcfb5plUBZD81hNzw1UwjAAAAAY","remoteAddr":"192.168.1.41","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-08-09T23:02:00+00:00"}

#### Browser log
```
Insert your browser log here, this could for example include:

Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
window.controllers è deprecato. Non utilizzarlo per rilevare l’User Agent del browser. ace.js:1716:0
Content Security Policy: Il caricamento di una risorsa su self è stato bloccato dalle impostazioni della pagina (“script-src http://cloud1.busoni.local 'unsafe-eval'”). files
L’utilizzo di getPreventDefault() è deprecato. Al suo posto utilizzare defaultPrevented. jquery.min.js:5:0

**Comment by Xenopathic** [comment]
cc @icewind1991

**Comment by RealRancor** [comment]
Hi,

it could be useful to completely clean the /data/owncloud.log and re-produce this to get only the relevant logfiles for this problem. Currently you have logfiles in the range of three days.

**Comment by gbusoni** [comment]
This was done already here: https://forum.owncloud.org/viewtopic.php?f=31&t=29526#p93606

**Comment by RealRancor** [comment]
Then please update the issue here with the stripped down logs. This helps:

- that someone having a look at the issue here don't need to have a look at the forums to see the relevant logfiles
- to avoid confusion (for example while searching) with the non-relevant logfiles

**Comment by PVince81** [comment]
Is this still happening with 8.1.5 or 8.2.2 ?

**Comment by gbusoni** [comment]
?Sorry, I am not using owncloud anymore, it has never worked fine for me unfortunately, so i am not able to tell you....

________________________________
Da: Vincent Petry <notifications@github.com>
Inviato: mercoledì 2 marzo 2016 20:41
A: owncloud/core
Cc: Giorgio Busoni
Oggetto: Re: [core] Issue with external storage On Centos 7 (#18233)


Is this still happening with 8.1.5 or 8.2.2 ?

-
