### ISSUE TITLE
CentOS 6 with SCL PHP54 and 8.1.1 from repository.

### ISSUE THREAD

**Issue by lrowen** [owncloud/core#18239]
The isv:ownCloud:community repository for either CentOS 6 or CentOS CentOS 6 no longer has the owncloud-server-scl-php54 package.  The owncloud-server-8.1.1-12.1 package requires php >=5.4.0 which the SCL PHP54 package does not provide.  Current packages installed:
    # rpm -qa|grep ^owncloud
    owncloud-app-provisioning_api-8.1.0-19.1.noarch
    owncloud-app-files_texteditor-8.1.0-19.1.noarch
    owncloud-server-scl-php54-8.1.0-19.1.noarch
    owncloud-3rdparty-8.1.0-19.1.noarch
    owncloud-app-user_webdavauth-8.1.0-19.1.noarch
    owncloud-app-files_videoviewer-8.1.0-19.1.noarch
    owncloud-app-files_sharing-8.1.0-19.1.noarch
    owncloud-app-encryption-8.1.0-19.1.noarch
    owncloud-app-files_pdfviewer-8.1.0-19.1.noarch
    owncloud-app-user_external-8.1.0-19.1.noarch
    owncloud-app-user_ldap-8.1.0-19.1.noarch
    owncloud-app-files_trashbin-8.1.0-19.1.noarch
    owncloud-app-templateeditor-8.1.0-19.1.noarch
    owncloud-app-files_versions-8.1.0-19.1.noarch
    owncloud-app-firstrunwizard-8.1.0-19.1.noarch
    owncloud-app-activity-8.1.0-19.1.noarch
    owncloud-config-apache-8.1.1-12.1.noarch
    owncloud-app-files-8.1.0-19.1.noarch
    owncloud-app-gallery-8.1.0-19.1.noarch
    owncloud-app-files_external-8.1.0-19.1.noarch
    owncloud-app-files_locking-8.1.0-19.1.noarch
    owncloud-app-external-8.1.0-19.1.noarch

A `yum update` fails due to the lack of the owncloud-server-scl-php54 package.

This is on CentOS6 with php54 installed from the Software Collections.  The 8.1.0 site is working fine, but just won't update.

**Comment by karlitschek** [comment]
@jnweiger

**Comment by jnweiger** [comment]
We have 3 different repos supporting 3 different versions of php from SCL:

https://build.opensuse.org/package/show/isv:ownCloud:community:8.1/owncloud
CentOS_6_PHP54
CentOS_6_PHP55
CentOS_6_PHP56

**Comment by Kawohl** [comment]
i could not reproduce this, did you try this?


yum install centos-release-SCL
yum clean all
yum makecache
yum install yum install php54-php-bcmath php54 php54-php-cli php54-php-gd php54-php-ldap php54-php-mbstring php54-php-xmlrpc php54-php php54-php-pdo php54-php-pear php54-php-pecl-apc php54-php-mysqlnd php54-php-process


#### enable php5.4
source /opt/rh/php54/enable
### eventually you want to delete /etc/httpd/conf.d/php.conf

rm -fr /etc/httpd/conf.d/php.conf

### check php version
php -v 

Anyway thanks for your contribution.

If the issue still persists please reopen using the issue template. 
https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by lrowen** [comment]
@Kawohl 

Did all that; as I said, the 8.1.0 site WORKS; if I hadn't done all that already, 8.x of any version would not have worked.  

The yum update is blocked by the rpm dependency on php>=5.4, not the output of php -v.  Enabling php54 using SCL does not in any way affect the rpm dependency issue, as Requires: doesn't care about SCL.  The correct answer is what @jnweiger posted, but there is still a significant disconnect there, with all of the different repositories on OBS, and the instructions for CentOS do not point to these repos.  Further, the CentOS_6_PHP54 repo contains an older release (8.1.3-2.1 at the moment) than the repo pointed to by the website's instructions (8.1.3-13.1 last I checked).   

I fixed it for myself by patching the rpm using rpmrebuild to edit the dependencies to be for the SCL packages.  I'll leave this bug closed, since the issue is fixed if you have the correct repo enabled, but I'll open a new report later dealing with the repository confusion (which repo is the correct repo?  It's certainly not the one you get by default going through the website's download instructions as of 10/1/2015 (the last time I looked)!).

**Comment by jnweiger** [comment]
@lrowen The discrepancy in build release numbers 8.1.3-2.1 vs 8.1.3-13.1 is an unfortunate side effect of looking at diffferent repositories. It does not mean that one is newer or older than the other.
Comparing build release numbers makes most sense within the same repository.

https://build.opensuse.org/package/show/isv:ownCloud:community:8.1/owncloud
and
https://build.opensuse.org/package/show/isv:ownCloud:community/owncloud

should offer the same packages.

**Comment by lrowen** [comment]
@jnweiger 
??!!!??  As far as yum and rpm are concerned, using the standard EVR comparison, with Epoch and Version being the same a Release of 13.1 > a release of 2.1 and thus the 13.1 Release package will never be upgraded by yum to a 2.1 package, even if %{BUILDTIME} is newer. (And since you haven't set Epoch, that really isn't part of it.)

So, to get properly upgraded from the hand-patched 13.1 I did (from the repo that you get if you use the website's download directions) to the 2.1 in PHP54, I'll need to change the repo to which I'm pointing in the .repo file in /etc/yum.repos.d and do a yum downgrade owncloud to get upgraded to the 'correct' version.....

So, can you confirm for me that 8.1.3-2.1 is actually the newest production package?  Thanks.

**Comment by jnweiger** [comment]
yes, changelog of 8.1.3-2.1 from https://build.opensuse.org/package/show/isv:ownCloud:community:8.1/owncloud and changelog of 8.1.3-13.1 from https://build.opensuse.org/package/show/isv:ownCloud:community/owncloud are identical.

**Comment by lrowen** [comment]
@jnweiger 
Thanks; enabling the proper repo ( baseurl=http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.1/CentOS_6_PHP54/ ) in /etc/yum.repos.d/isv:ownCloud:community.repo (along with it's corresponding gpgkey= line), running a 'yum clean all' to purge the older repo, and then a 'yum downgrade owncloud owncloud-server owncloud-config-apache' pulled in those 'newer' packages.

Will http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.1/CentOS_6_PHP54/ remain the 'best' repo for 8.1.x on CentOS 6 with PHP54 from SCL so that future 'yum update' invocations will work as expected?

Thanks much for the packaging; just have to work through a few niggles, that's all.

**Comment by koumdros** [comment]
trying to upgrade from 8.0.14 to 8.1.9 I get more or less the same error.

I do have php 5.4 :  php -v PHP 5.4.40 , OC 8.0.14 runs with it.
I installed the isv:/ownCloud:/community:/8.1/CentOS_6_PHP54 repo.. to try and make minimal changes 

If I try to do an upgrade ( either yum update owncloud or owncloud-server-scl-php54 as I had been doing up to this point), I end up with a broken dependency and yum barfsup

`Error: Package: owncloud-app-files_antivirus-8.0.14-1.1.noarch (@isv_ownCloud_community_8.0)
           Requires: owncloud-server-core = 8.0.14
           Removing: owncloud-server-scl-php54-8.0.14-1.1.noarch (@isv_ownCloud_community_8.0)
               owncloud-server-core
               owncloud-server-core = 8.0.14
           Obsoleted By: owncloud-8.1.9-1.1.noarch (isv_ownCloud_community_8.1)
               Not found`
