### ISSUE TITLE
"Please reload the page" should be clickable to reload the page

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#18241]
At first I thought it wouldn't bother me, but after many updates, I still hate to be forced to use the keyboard when I'm using the mouse.

### Steps to reproduce
1) Install unofficial apps
2) Perform an ownCloud upgrade

### Expected result

I should see the message about all the apps which were disabled and I should be able to click on "reload the page"

### Actual result

I see the message about all the apps which were disabled, but I have to hit F5 to go back to what I was doing

**Comment by karlitschek** [comment]
I agree. We should do that.

**Comment by PVince81** [comment]
I felt frustrated as well when seeing this repeatedly. It was mostly because I thought it was still working but it was actually saying "there were warnings".

I suggest to add a real button or visible link to "continue to owncloud".

@jancborchardt thoughts ?

**Comment by jancborchardt** [comment]
Is there anything preventing us from doing an automatic redirect?

If yes, then we should indeed do what @PVince81 suggests and add a button to »Continue to ownCloud«.

**Comment by oparoz** [comment]
> Is there anything preventing us from doing an automatic redirect?

Yes. The user has to be given time to read the message. The auto-redirect was removed recently because of riots in the clouds.

**Comment by jancborchardt** [comment]
@oparoz open a pull request maybe? :)

**Comment by oparoz** [comment]
I'll think about it. 8.2.1 is faaaaaar away.

**Comment by jancborchardt** [comment]
I’d consider this a bug, and if you have a pull request then this is the time to fix this.

**Comment by cmonteroluque** [comment]
This issue will fall off 8.2 if not resolved by 6 Oct

**Comment by hutchic** [comment]
_bump_ this can be closed now
