### ISSUE TITLE
Delete user but keep files

### ISSUE THREAD

**Issue by elfeffe** [owncloud/core#18240]
We found a problem.
We delete some user that is not working anymore in the company, but we need to keep the files he had uploaded.
When we delete user, it simply delete it even without ask for a confirmation. And all his files dissapear.

**Comment by DeepDiver1975** [comment]
> When we delete user, it simply delete it even without ask for a confirmation. And all his files dissapear.

this is the expected behavior - in case you want to keep the files you need to backup them

**Comment by elfeffe** [comment]
ok
And how can override /core/settings/templates/users/part.userlist.php to
delete the "remove" section?
