### ISSUE TITLE
hubiC backend

### ISSUE THREAD

**Issue by szepeviktor** [owncloud/core#18249]
It would be nice to have hubiC backend.
https://api.hubic.com/sandbox/

hubiC is made up of OAuth2 and Openstack object storage (swift).
I think both of them are in OC already.

**Comment by Xenopathic** [comment]
Does the OpenStack storage type not cover this usecase?

**Comment by szepeviktor** [comment]
It covers the data transfer (all requests) but not the authentication.

**Comment by LukasReschke** [comment]
https://github.com/arelange/owncloud-files-hubic
