### ISSUE TITLE
Failed to mkdir /assets (in version 8.1.0)

### ISSUE THREAD

**Issue by peterkahl** [owncloud/core#18253]
This might be caused by my permissions...

I have enabled the config option:
```
'asset-pipeline.enabled' => true
```
Noticed the error in log:
```
mkdir(): Permission denied at /srv/www/XXXXXXXX/public_html/lib/private/template.php#257
Folder </srv/www/XXXXXX/public_html/assets> does not exist and/or could not be generated.
```
So, I created the directory by hand and all is fine now.
You should make the assets directory part of the installation.
Cheers.

**Comment by peterkahl** [comment]
Another one...
```
2015/08/13 13:23:33 [error] 18898#0: *121 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: X.X.X.X, server: DDDDDDD, request: "GET /assets/jquery.min.map HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "DDDDDDDDD", referrer: "https://DDDDDDDDDD/index.php/settings/admin"
```
Meaning the jQuery file couldn't be found. Where is it? Failed yo put it into the asset dir?

**Comment by DeepDiver1975** [comment]
Enabling and setup of the asset pipeline is a manual process as documented .

The jquery map file is not part of our codebase.

**Comment by peterkahl** [comment]
I wasn't looking for help. I've helped myself.
I was trying to help you. You're welcome.
