### ISSUE TITLE
Mobile:No possibilty to delete files on Smartphone

### ISSUE THREAD

**Issue by Bullnados** [owncloud/core#18256]
Is it possible to delete files in mobile theme for smartphones? In FF Beta and Stock Android browser are just download and share button

**Comment by karlitschek** [comment]
@jancborchardt Can you have a look please?

**Comment by jancborchardt** [comment]
@Bullnados please when you encounter issues, always try to verify them with latest master. As you see in latest master we moved to an action dropdown with the missing actions (Rename, Versions, Delete) which were previously not present on mobile. See #17709

**Comment by Bullnados** [comment]
I know. But #17709 won't be backported? So 8.0 and 8.1 it is not possible to delete files/folders with smartphones. But isn't that a essential function or is here a missunderstanding on my side.

**Comment by jancborchardt** [comment]
@Bullnados features are never backported, only bugfixes.

**Comment by Bullnados** [comment]
With that point of view you are right.^^
For me it was a bug. But in the end we got together. :+1:
