### ISSUE TITLE
No 'Apps' page and false 'No Internet Connection ' upgrading to 8.1.0 and every version after

### ISSUE THREAD

**Issue by MU7L3Y** [owncloud/core#18252]
Edited title....

### Steps to reproduce
1. Upgrade to 8.1.0 or 8.1.1 and others since.

### Expected behaviour
Able to enable/disable apps and have no false errors.

### Actual behaviour
I can't enable/disable apps. It tries to load apps but is just blank with no apps listed and says "No apps found for your version."
I get these errors in the admin page:

**This is false because I am accessing my cloud remotely to upgrade it:**
This server has no working Internet connection. This means that some of the features like mounting external storage, notifications about updates or installation of third-party apps will not work. Accessing files remotely and sending of notification emails might not work, either. We suggest to enable Internet connection for this server if you want to have all features.

**Don't know how to fix this one even with reading the documentation:**
/dev/urandom is not readable by PHP which is highly discouraged for security reasons. Further information can be found in our documentation.

### Server configuration

**Operating system:**
Linux Hosting Package
**Web server:**
Apache
**Database:**
MySQL
**PHP version:**
5.5.11
**ownCloud version:**
8.1.1
**Updated from an older ownCloud or fresh install:**
Upgraded manually
**List of activated apps:**
Files, activity, pictures and trying to enable music but can't as no apps are loaded.
**Config:**
```
<?php
$CONFIG = array (
  'instanceid' => 'removed',
  'passwordsalt' => 'removed',
  'trusted_domains' => 
  array (
    0 => 'removed.com',
  ),
  'datadirectory' => '/removed/cloud/data',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'dbname' => 'removed',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'removed',
  'dbpassword' => 'removed',
  'installed' => true,
  'theme' => '',
  'logtimezone' => 'Australia/Melbourne',
  'maintenance' => false,
  'mail_smtpmode' => 'php',
  'mail_smtpname' => 'removed',
  'mail_smtppassword' => 'removed',
  'overwritewebroot' => '/cloud',
  'overwrite.cli.url' => 'http://removed/cloud',
  'has_internet_connection' => true,
  'appstoreenabled' => true,
  'updatechecker' => true,
  'check_for_working_webdav' => true,
  'check_for_working_htaccess' => true,
  'xframe_restriction' => true,
  'cipher' => 'AES-256-CFB',
  'enable_previews' => true,
  'filesystem_check_changes' => 1,
  'loglevel' => '1',
  'skeletondirectory' => '',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.distributed' => '\\OC\\Memcache\\Memcached',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
    'dbindex' => 0,
  ),
  'memcached_servers' => 
  array (
    0 => 
    array (
      0 => 'localhost',
      1 => 11211,
    ),
  ),
  'secret' => 'removed',
  'appstore.experimental.enabled' => true,
  'appcodechecker' => false,
);
```
**Are you using external storage, if yes which one:**
Yes, dropbox.
**Are you using encryption:**
No
**Are you using an external user-backend, if yes which one:**
No

### Client configuration
**Browser:** Chrome

**Operating system:** Win 7

#### ownCloud log (data/owncloud.log)
```
Error	PHP	array_map(): Argument #2 should be an array at /home/removed/public_html/cloud/settings/controller/appsettingscontroller.php#262
Error	PHP	Array to string conversion at /home/removed/public_html/cloud/lib/private/template/functions.php#36
```

**Comment by Jenselme** [comment]
Same here.

**Comment by MU7L3Y** [comment]
Did 8.1.2 fix this? I can't tell because the download page has a 404 error.

**Comment by MU7L3Y** [comment]
I haven't looked at my owncloud log for a while but just did and found a whole heap of other errors that keep repeating....

```
Error	files_external	Forbidden. Bad or expired token. This can happen if the user or Dropbox revoked or expired an access token. To fix, you should re-authenticate the user.	2015-08-27T14:16:10+10:00
Fatal	webdav	Exception: {"Message":"SQLSTATE[HY000]: General error: 2006 MySQL server has gone away","Code":"HY000","Trace":"#0 \/home\/removed\/public_html\/cloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(1176): PDO->beginTransaction()\n#1 \/home\/removed\/public_html\/cloud\/lib\/private\/db.php(179): Doctrine\\DBAL\\Connection->beginTransaction()\n#2 \/home\/removed\/public_html\/cloud\/lib\/private\/files\/cache\/scanner.php(337): OC_DB::beginTransaction()\n#3 \/home\/removed\/public_html\/cloud\/lib\/private\/files\/cache\/scanner.php(267): OC\\Files\\Cache\\Scanner->scanChildren('', false, 3, Array, true)\n#4 \/home\/removed\/public_html\/cloud\/lib\/private\/files\/cache\/watcher.php(91): OC\\Files\\Cache\\Scanner->scan('', false)\n#5 \/home\/removed\/public_html\/cloud\/lib\/private\/files\/view.php(1182): OC\\Files\\Cache\\Watcher->checkUpdate('', Array)\n#6 \/home\/removed\/public_html\/cloud\/lib\/private\/connector\/sabre\/objecttree.php(148): OC\\Files\\View->getFileInfo('DropBox')\n#7 \/home\/removed\/public_html\/cloud\/lib\/private\/connector\/sabre\/custompropertiesbackend.php(101): OC\\Connector\\Sabre\\ObjectTree->getNodeForPath('DropBox')\n#8 \/home\/removed\/public_html\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/PropertyStorage\/Plugin.php(86): OC\\Connector\\Sabre\\CustomPropertiesBackend->propFind('DropBox', Object(Sabre\\DAV\\PropFind))\n#9 [internal function]: Sabre\\DAV\\PropertyStorage\\Plugin->propFind(Object(Sabre\\DAV\\PropFind), Object(OC\\Connector\\Sabre\\Directory))\n#10 \/home\/removed\/public_html\/cloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#11 \/home\/removed\/public_html\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1016): Sabre\\Event\\EventEmitter->emit('propFind', Array)\n#12 \/home\/removed\/public_html\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(936): Sabre\\DAV\\Server->getPropertiesByNode(Object(Sabre\\DAV\\PropFind), Object(OC\\Connector\\Sabre\\Directory))\n#13 \/home\/removed\/public_html\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(327): Sabre\\DAV\\Server->getPropertiesForPath('', Array, 1)\n#14 [internal function]: Sabre\\DAV\\CorePlugin->httpPropfind(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#15 \/home\/removed\/public_html\/cloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#16 \/home\/removed\/public_html\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PROPFIND', Array)\n#17 \/home\/removed\/public_html\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#18 \/home\/removed\/public_html\/cloud\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n#19 \/home\/removed\/public_html\/cloud\/remote.php(132): require_once('\/home\/removed\/...')\n#20 {main}","File":"\/home\/removed\/public_html\/cloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php","Line":1176}
Error	files_external	Error: (504) Internal Server Error
Fatal	cron	An exception occurred while executing 'UPDATE `oc_jobs` SET `last_run` = ? WHERE `id` = ?' with params [1440469646, "8"]: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
Error	files_external	Error: (502)
Error	files_external	Curl error: (7) Failed to connect to api.dropbox.com port 443: Connection timed out
Error	PHP	fread() expects parameter 1 to be resource, boolean given at /home/removed/public_html/cloud/lib/private/files/storage/wrapper/encryption.php#625
Error	PHP	Cannot modify header information - headers already sent by (output started at /home/removed/public_html/cloud/3rdparty/sabre/http/lib/Sapi.php:70) at /home/removed/public_html/cloud/3rdparty/sabre/http/lib/Sapi.php#58
```

**Comment by dper** [comment]
@MU7L3Y It sounds like the errors in your log are not like others mentioned above.

Although, you know that this issue itself is ambiguously-titled and could possibly include many different errors.  That would not be particularly useful to anyone, though.

**Comment by MU7L3Y** [comment]
Correct but do you expect me to have a different thread for each error? Hardly seems worth it when they could all be discussed here.

**Comment by MU7L3Y** [comment]
Just upgraded to 8.1.2 but doesn't seem to have fixed anything. Still can't enable disable apps and still get errors below plus a false no internet connection.
```
Error	PHP	array_map(): Argument #2 should be an array at /home/mutleypr/public_html/cloud/settings/controller/appsettingscontroller.php#262
Error	PHP	Array to string conversion at /home/removed/public_html/cloud/lib/private/template/functions.php#36
Fatal	index	Exception: {"Exception":"OC\\NeedsUpdateException","Message":"","Code":0,"Trace":"#0 \/home\/removed\/public_html\/cloud\/lib\/private\/app.php(99): OC_App::loadApp('activity')\n#1 \/home\/removed\/public_html\/cloud\/lib\/private\/util.php(127): OC_App::loadApps(Array)\n#2 \/home\/removed\/public_html\/cloud\/lib\/base.php(872): OC_Util::setupFS()\n#3 \/home\/removed\/public_html\/cloud\/index.php(40): OC::handleRequest()\n#4 {main}","File":"\/home\/removed\/public_html\/cloud\/lib\/private\/app.php","Line":118}
```

**Comment by MU7L3Y** [comment]
I have now fixed the /dev/urandom error but still have a false "no internet connection" error.

**Comment by dper** [comment]
@MU7L3Y What if you try a fresh installation? I mean, don't delete your current one, but just make a separate directory and try installing there to see if your server is working properly. That would at least allow you to be certain that PHP and Apache are working properly.

**Comment by MU7L3Y** [comment]
When upgrading I just extracted the contents of the std owncloud.tar.bz2 and moved my config and data over to it. Do you mean something different than that? As in a whole new database?

**Comment by dper** [comment]
@MU7L3Y To try to isolate the problem, make a second totally clean installation. Don't copy any data from your old installation. (Save that data so you can use it later.) Just install from scratch in a separate directory and see what works out of the box. This will let you confirm that Apache and PHP are in working order.  If you can confirm that a clean installation is error-free, you will know that the problem lies either in your data files, your config files, or your database.

**Comment by MU7L3Y** [comment]
@dper ok I will try that when I get some spare time.

**Comment by MU7L3Y** [comment]
I have just upgraded to 8.1.3 and only got these errors when going to the apps page:
```
Error	PHP	Array to string conversion at /home/REMOVED/public_html/cloud/lib/private/template/functions.php#36
Error	PHP	array_map(): Argument #2 should be an array at /home/REMOVED/public_html/cloud/settings/controller/appsettingscontroller.php#262
```
I also just tried to install a new test cloud using the 'setup-owncloud.php' and it fails. Here are the errors on page 2:
```
Warning: rename(tmp-owncloud1442449655/owncloud,./owncloudtest): No such file or directory in /home/REMOVED/public_html/setup-owncloud.php on line 158
```
```
Error
ownCloud is NOT installed
download of ownCloud source file failed.
SSL: no alternative certificate subject name matches target host name 'download.owncloud.org'SSL: no alternative certificate subject name matches target host name 'download.owncloud.org'
```
Any ideas?

**Comment by MU7L3Y** [comment]
Upgraded to 8.2.0 and still the same stuff. Also web installer still has the same problems.

**Comment by dper** [comment]
@MU7L3Y Sad to hear your problem is still ongoing. Here's one way to isolate the problem...
* Download the installation tarball from https://download.owncloud.org/community/owncloud-8.2.0.tar.bz2.  For example, using `wget`.
* Unpack it and put it in a web accessible directory.  For example, using `tar`.
* Browse to the index page in your web browser.
* See what happens.
If you get errors along the way -- or even if you don't -- this should help indicate what's not working.  Specifically, do *not* upgrade a previous installation and do *not* use the downloader script.  Download and unpack the tarball manually.  When you provide a description here, try to be more specific about what exactly you've tried.

**Comment by MU7L3Y** [comment]
@dper Thanks for the tips. I do try to provide any info I can/know how.
I have done as you said and created a new installation using SQLite. Going to the admin page I get these messages at the top.

```
Security & setup warnings

APCu below version 4.0.6 is installed, for stability and performance reasons we recommend to update to a newer APCu version.
This server has no working Internet connection. This means that some of the features like mounting external storage, notifications about updates or installation of third-party apps will not work. Accessing files remotely and sending of notification emails might not work, either. We suggest to enable Internet connection for this server if you want to have all features.
You are accessing this site via HTTP. We strongly suggest you configure your server to require using HTTPS instead as described in our security tips.
Transactional file locking is using the database as locking backend, for best performance it's advised to configure a memcache for locking. See the documentation ↗ for more information.
No memory cache has been configured. To enhance your performance please configure a memcache if available. Further information can be found in our documentation.
Please double check the installation guides ↗, and check for any errors or warnings in the log.
```
I get this one in the log:
```
Error	PHP	touch(): Unable to create file /home/REMOVED/public_html/owncloud/data/owncloud.log because No such file or directory at /home/REMOVED/public_html/owncloud/lib/private/log/owncloud.php#53
```
Going to the Apps page loads and works correctly somehow in this installation.

**Comment by dper** [comment]
It is good that we only see those warnings.  None of those warnings would cause the problems you reported above.  Although you might want to address each of them at some point, they involve things that work properly and could or should be improved.  They do not involve things that are broken.  So that is very nice to see!

The log file error is disconcerting.  If the log file is not being properly written, my first guess is a permissions issue.  As in, does the web server have write access to all the necessary folders?  Since you are using a hosted service, I cannot tell you what to look for.  It varies based on the company you rent server space from.

**Comment by MU7L3Y** [comment]
Even with that error it did create the a log file. The data directory is a 770. The log file itself is a 640. These are the same as my normal installation.

So what can I do to fix my normal installation?

**Comment by dper** [comment]
> So what can I do to fix my normal installation?

What I would do (and what I did do, in fact), is to not fix the old 
installation.  Either copy or export/import the data from your old 
installation to your new working installation.  Depending on what data 
you have in OwnCloud, this could be very easy.  Just be careful not to 
accidentally delete your old data.

A few users (including me) have had problems upgrading with 8.1.0 and 
8.1.1, and we never figured out precisely why or what went wrong.  But 
since it's only a few users reporting this kind of behavior, why spend 
time trying to debug it when we can ignore the whole issue and it 
probably won't ever come up again.  :-)

**Comment by MU7L3Y** [comment]
My problem is that I have a few GB of data. I don't fancy uploading it into owncloud again. And what about my few users (granted it's family) that have passwords etc all set up already?
If there is an easy way to import everything I'm happy to but don't fancy having to basically set everything up again...

**Comment by dper** [comment]
Ah, I see.  Well, you can try doing a manual upgrade.  Copy `data` and 
`config/config.php` from your old installation into your new 
installation.  If you are lucky, everything will work.  (Note that you 
will temporarily have two copies of all your data.  Be careful not to 
exceed your web host's storage limits.)

**Comment by MU7L3Y** [comment]
Sorry but that's how I always upgrade and I still have the problem.

**Comment by dper** [comment]
That is indeed unfortunate. I have little knowledge of databases and cannot help you there. :-(

**Comment by MU7L3Y** [comment]
Manually upgraded to 8.2.1 just now and still have problems. Anyone from owncloud reading this? I need some help here...The apps page still says, "No apps found for your version."
And while upgrading it disabled the music app and then in the admin panel I have these errors:
```
Error	no app in context	Error while running background job: Autoload path not allowed: /home/REMOVED/public_html/cloud/apps/music/backgroundjob/cleanup.php	2015-11-19T11:30:05+11:00
Error	core	Exception: {"Exception":"Symfony\\Component\\Routing\\Exception\\RouteNotFoundException","Message":"Unable to generate a URL for the named route \"music.page.index\" as such route does not exist.","Code":0,"Trace":"#0 \/home\/REMOVED\/public_html\/cloud\/lib\/private\/route\/router.php(314): Symfony\\Component\\Routing\\Generator\\UrlGenerator->generate('music.page.inde...', Array, false)\n#1 \/home\/REMOVED\/public_html\/cloud\/lib\/private\/route\/cachingrouter.php(53): OC\\Route\\Router->generate('music.page.inde...', Array, false)\n#2 \/home\/REMOVED\/public_html\/cloud\/lib\/private\/urlgenerator.php(65): OC\\Route\\CachingRouter->generate('music.page.inde...', Array)\n#3 \/home\/REMOVED\/public_html\/cloud\/apps\/music\/appinfo\/app.php(26): OC\\URLGenerator->linkToRoute('music.page.inde...')\n#4 \/home\/REMOVED\/public_html\/cloud\/lib\/private\/app.php(160): require_once('\/home\/REMOVED\/...')\n#5 \/home\/REMOVED\/public_html\/cloud\/lib\/private\/app.php(141): OC_App::requireAppFile('music')\n#6 \/home\/REMOVED\/public_html\/cloud\/lib\/private\/app.php(1171): OC_App::loadApp('music', false)\n#7 \/home\/REMOVED\/public_html\/cloud\/lib\/private\/installer.php(219): OC_App::updateApp('music')\n#8 \/home\/REMOVED\/public_html\/cloud\/lib\/private\/installer.php(249): OC_Installer::updateApp(Array)\n#9 \/home\/REMOVED\/public_html\/cloud\/lib\/private\/updater.php(509): OC_Installer::updateAppByOCSId('164319')\n#10 \/home\/REMOVED\/public_html\/cloud\/lib\/private\/updater.php(323): OC\\Updater->upgradeAppStoreApps(Array)\n#11 \/home\/REMOVED\/public_html\/cloud\/lib\/private\/updater.php(205): OC\\Updater->doUpgrade('8.2.1.4', '8.2.0.12')\n#12 \/home\/REMOVED\/public_html\/cloud\/core\/ajax\/update.php(111): OC\\Updater->upgrade()\n#13 {main}","File":"\/home\/REMOVED\/public_html\/cloud\/3rdparty\/symfony\/routing\/Symfony\/Component\/Routing\/Generator\/UrlGenerator.php","Line":134}
```
Also these errors have appeared now too:
```
Error	PHP	array_map(): Argument #2 should be an array at /home/REMOVED/public_html/cloud/settings/controller/appsettingscontroller.php#262	2015-11-19T11:48:13+11:00
Debug	DeleteOrphanedSharesJob	0 orphaned share(s) deleted	2015-11-19T11:48:01+11:00
Error	PHP	Array to string conversion at /home/REMOVED/public_html/cloud/lib/private/template/functions.php#36	2015-11-19T11:34:34+11:00
```

**Comment by bubu47** [comment]
Hello, I have setup a brand new system (INTEL NUC, debian jessie, owncloud 8.2) anf get the very same error when I open the administrators admin page
Array to string conversion at /var/www/owncloud/lib/private/template/functions.php#36 

can anyone give me some hints on what to do about this?

thanks and regards

**Comment by dper** [comment]
@bubu47 You'll want to include more information. What version of PHP? What web browser, and what version? What database, and what version? What exactly shows up in the log file?

If you have a brand new system, are you upgrading, or are you installing?

The simplest workaround that many of us found is to do a clean installation, because the upgrade failed and we never figured out why.  It's not ideal, but it's functional. :-/  This workaround doesn't work well if you already have a lot of data or users.  But you're talking about a brand new system, so I expect that you don't.

**Comment by bubu47** [comment]
Hi Douglas
- I have a brand new installationls, no upgrade
- I use win10 and firefox 42
- owncloud is running on a Intel nuc and original debian (jessie, 8.2,
downloaded by from debian.org))
- I installed owncloud (8.2) as instructed by the release channel, the OC
installation job installs PHP  5.6.14, I and mysql (5.5.46-0+deb8u1
(Debian))
- I run OC with mysql and have installed php5-apcu
- no fancy things  except I moved the OC data directory to a different HDD,
I set the owner of the data directory to www-data
- the only "Security & setup warnings" is the Transactional file locking,I
have not install redis

here what I find in the log when I open the admin page:
{"reqId":"d57eQQ7NMpBVthE5sY0Q","remoteAddr":"192.168.2.1","app":"PHP","message":"Array
to string conversion at
\/var\/www\/owncloud\/lib\/private\/template\/functions.php#36","level":3,"time":"2015-11-26T09:06:47+00:00"}
{"reqId":"PaFYiDlNFmk\/OggxLGOf","remoteAddr":"192.168.2.1","app":"PHP","message":"Array
to string conversion at
\/var\/www\/owncloud\/lib\/private\/template\/functions.php#36","level":3,"time":"2015-11-26T09:07:35+00:00"}

Thanks for your help

eugen

**Comment by MU7L3Y** [comment]
@PVince81 Is there anything I can do or look for in the database? There is clearly an issue somewhere in my system...

**Comment by MU7L3Y** [comment]
Pretty sad I've had no guidance here to help resolve these problems. I'm happy to debug but don't know where to look???

**Comment by dper** [comment]
@MU7L3Y This is just my speculation, but it seems like something other than OwnCloud in your system is configured in a peculiar way. For example, PHP, mysql, Apache, nginx, and your PHP handler are all crucial. If you have firewall software running, that might matter, too. Or if you have any weird firewall software or broken file permissions, all bets are off.

The thing is, if the problem is outside of OwnCloud, you can't expect to find an answer here.  Of course if anyone knew what was wrong at a glance they would tell you, but we don't, and this is not generic tech support.  Sorry...

The nuclear option is to reinstall Debian.  That should solve your problem.  But it takes a long time and you have to reconfigure everything.

**Comment by MU7L3Y** [comment]
Makes no sense to me though because everything was working in v7 and I think from memory even in 8.0. I understand that these other things play a part but I don't know where to look, especially since all I do to upgrade is decompress the full package, I never use the updater. As written in the OP I have a shared hosting package so I can't do too much. It would be useful to know where to look for the problem like inside the db etc. I've tried looking but no closer to finding a solution. Appreciate the reply @dper

**Comment by dper** [comment]
@MU7L3Y Shared hosting may be relevant. Some web hosting providers limit what you can do with PHP and MySQL (and other things), and this can create difficult-to-diagnose problems. You can try asking your provider's tech support and see what they say.  Or, wait for 9.0 and see what things look like then.

**Comment by MU7L3Y** [comment]
mmmm at this stage I'll wait for 9...

**Comment by MU7L3Y** [comment]
At this stage with 8.2.3 I am only getting these errors:

1. This server has no working Internet connection.
2. Error	PHP	Array to string conversion at /home/REMOVED/public_html/cloud/lib/private/template/functions.php#36
3. Error	PHP	array_map(): Argument #2 should be an array at /home/REMOVED/public_html/cloud/settings/controller/appsettingscontroller.php#262

I'll try 9 sometime soon..

**Comment by MU7L3Y** [comment]
Running 9.0.2 now and I can finally access the apps page. All other errors that I had before in the admin page and not appearing yet either. I'll close this for now.
