### ISSUE TITLE
Array to string conversion error

### ISSUE THREAD

**Issue by aptalca** [owncloud/core#18250]
Hi,

Just updated to 8.1.1 from 8.0.5 and I keep getting this error in my log:
`Array to string conversion at /var/www/owncloud/lib/private/template/functions.php#36`

Any ideas?

Thanks

**Comment by MU7L3Y** [comment]
I also get this error along with this one:
array_map(): Argument #2 should be an array at /removed/cloud/settings/controller/appsettingscontroller.php#262

### Server configuration
Operating system: Linux Hosting Package
Web server: Apache
Database: MySQL
PHP version: 5.5.11
ownCloud version: 8.1.1

### Config
<?php
$CONFIG = array (
  'instanceid' => 'removed',
  'passwordsalt' => 'removed',
  'trusted_domains' => 
  array (
    0 => 'removed.com',
  ),
  'datadirectory' => '/removed/cloud/data',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'dbname' => 'removed',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'removed',
  'dbpassword' => 'removed',
  'installed' => true,
  'theme' => '',
  'logtimezone' => 'Australia/Melbourne',
  'maintenance' => false,
  'mail_smtpmode' => 'php',
  'mail_smtpname' => 'removed',
  'mail_smtppassword' => 'removed',
  'overwritewebroot' => '/cloud',
  'overwrite.cli.url' => 'http://removed/cloud',
  'has_internet_connection' => true,
  'appstoreenabled' => true,
  'updatechecker' => true,
  'check_for_working_webdav' => true,
  'check_for_working_htaccess' => true,
  'xframe_restriction' => true,
  'cipher' => 'AES-256-CFB',
  'enable_previews' => true,
  'filesystem_check_changes' => 1,
  'loglevel' => '1',
  'skeletondirectory' => '',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.distributed' => '\\OC\\Memcache\\Memcached',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
    'dbindex' => 0,
  ),
  'memcached_servers' => 
  array (
    0 => 
    array (
      0 => 'localhost',
      1 => 11211,
    ),
  ),
  'secret' => 'removed',
  'appstore.experimental.enabled' => true,
  'appcodechecker' => false,
);

**Comment by RealRancor** [comment]
Hi,

please use the search function before posting a new issue. There are already some duplicates reported here, this one is still open: https://github.com/owncloud/core/issues/17468

**Comment by aptalca** [comment]
My bad
