### ISSUE TITLE
Create Links for Shared Files or Folders (not a public share)

### ISSUE THREAD

**Issue by altmagalhaes** [owncloud/core#18251]
I have a Owncloud 8.1 running in partnership with my samba4 domain, file sharing and active directory authentication. Everything works fine and I do prefer to use the external storage other than the provided by owncloud instalation (although I still have some space for users in owncloud so they do now lose some features like editing documents colaborativelly, etc).
One issue that I have the urge to report and I think that it is a great flaw in the system (or I am wrong because as far as I researched no one ever askeb about that before) it that you can share files with the authenticaded users and you can share links with the "public", but you cannot share a link with authenticated users and that could add a whole new use to the system as I could securelly display links  in a wabpage and some links would be accessible to all visitors but some would ask for a login first to verify permission to access that content.

Is that an issue to much complex to implement? Am I wrong and that have already been pointed up?

I do believe that the sharing system is great but when is come to a scenario where a lot of users share a lot of links with a lot of users and groups its better to use another content manager like a webpage to store the static links to make it ease for users to find some files or documents.

**Comment by PVince81** [comment]
Permalinks could be a solution: https://github.com/owncloud/core/issues/11732
Closing as duplicate.
