### ISSUE TITLE
SMB Shares redownload after upgrade to 8.1.1

### ISSUE THREAD

**Issue by JT1301** [owncloud/core#18267]
Hello,

I have a small problem. After I update my server from 8.0.4 to 8.1.1 and the new smb client (https://github.com/owncloud/documentation/issues/1447)
There is no connection to my smb shares!

I have to change the username from domain/username to only username. (In 8.0.4 the user had to be domain/username)

But after I change the username - all clients want do redownload the full folder.

Can someone take a look on this?

My test environment configuration:
Operating system: Debian Wheezy
Web server: Apache
Database: MySQL
PHP version: 5.4.41
ownCloud version: 8.1.1
Windows Server 2012 R2 with DFS Shares

Regards,
JT

**Comment by PVince81** [comment]
@JT1301 can you check the oc_storages table, it should contain a single entry "smb://".
I suspect that when you changed the user name, it recreated a new entry there instead of reusing the old one.

**Comment by PVince81** [comment]
@icewind1991

**Comment by PVince81** [comment]
Ah yes of course, since you changed the user name it will create a new entry.

Now the question is rather why the old "domain/username" stopped working. You shouldn't need to change it. As a workaround, enable maintenance mode and delete the new oc_storages entry that has only the username. Then rename the old entry that has domain/username to the id of the deleted one. The goal is to have an entry with username alone but pointing to the old numeric_id.

@icewind1991 @Xenopathic any clues ?

**Comment by PVince81** [comment]
@JT1301 note: if you already let all clients redownload everything it is best to leave the system as is, unless you find that OC shares from the SMB storage went missing. (this because the shares are associated to the old storage entry)

**Comment by JT1301** [comment]
@PVince81 at the moment it is just a test environment. But the problem will be the same in my productive environment...
In my admin panel are 26 SMB Shares with different users for different privileges.

id | numeric_id
------------ | -------------
09001829f6cac5be6f24cad4ac0bb80d|"72"
09f04b4839ea929885c9e1df47a7b1ba|"11"
147432279de12d07d7c8c2b6f6c55559|"60"
1e379359d23b0450009f1edf62c47a7d|"80"
218b532c4134bc08b4f3cebc3d4420a3|"56"
277f8ce58416574f9e0db7dafdb8fd0a|"55"
2a3f631ff17c69c7165bc56a6e8e9d01|"99"
33cdfcdc818caaa19427c1dfe1412411|"75"
376eca179c88ccf37813a5b3948b6d60|"66"
415aae2cae6b8add0f5ca5fc7d47b6ff|"59"
455fdc27fb01093b75e2520336a1cdfe|"44"
57087b46d95d383ac8a9ceffabe1ae91|"69"
5dd78f638c7e8a1a567478e33cbd27e6|"49"
618a3470f06fdf5243d2e5301de08231|"51"
64726ca2ab48aa06d3edc23c172f9b40|"82"
69f900ef50d40d05303871538bb78708|"68"
6a7d173e533ff9b8642a23ba3c149d97|"93"
6bee5173443a6e3cdfc33ffe0760bfab|"85"
6e41642b995f9d8452e96d0925663a18|"48"
6e9c8a8a85e4f5fac67b8d4013e5c84a|"96"
72486230aa02fab5ba798a35b89bf708|"10"
7b33ca9d640120016870d23541a90ce1|"52"
80e592f6b1da6ab5a5c36d6a6b5ab0a5|"77"
8280f860cc5945a79c847d7e3ded591c|"61"
8386df0d88a63cf4e19958ed81a890d1|"64"
86512f2b62acfc068241123c5f0f8335|"50"
8cfa7b6b66a998e6acef08983a7e3abd|"95"
908c3666230571c37daee9fa05c0eb37|"84"
90d0ee65aeeae092409e5f96271e9260|"58"
9eb3a25641c464fc1d40c8d2582472d7|"54"
a26712978430573c7fb84d656a90f9fc|"74"
af23454e7bf5177d52d384919cf7ed12|"76"
b3d9380e276fa09480635351ed81b362|"94"
b7b3edd7812eae3363d4c99e52f62451|"78"
bb7bf314c52b497010c71e98600680dd|"45"
bcba6c804686f8b0de933fb01e9fff87|"86"
c57e0ed8b5eb32783e292f47fab0d576|"73"
d2db72bd4e6d095b11c565131884508b|"47"
d44518b1196f203a6e0bc97a954b2cc4|"57"
dae12514b6354c5ebf6ef70646b22d78|"53"
dec3f74667328e84c6959faee4ebf01d|"79"
e36f5dacd805691e89aae8d7ab751196|"46"
home::a.hen|"15"
home::a.vo|"71"
home::c.ga|"35"
home::f.ma|"42"
home::j.pru|"70"
home::j.ruyt|"34"
home::k.prp|"33"
home::l.duec|"32"
home::l.oesch|"16"
home::l.verh|"37"
home::o.dre|"12"
home::owncloudsu|"1"
home::r.oer|"14"
home::s.schr|"36"
home::s.scers|"19"
home::t.junr|"13"
local::/home/ownclouddata/|"2"
smb::cloud.share@172.26.110.47//CS Cloud - domain$//|"92"
smb::cloud.share@172.26.110.47//DH Cloud - domain$//|"91"
smb::cloud.share@172.26.110.47//DM - FM$//Corporate documents/|"81"
smb::cloud.share@172.26.110.47//DM - FM$//Global/53 Arjan /|"97"
smb::cloud.share@172.26.110.47//DM - FM$//domain/53 Arjan /|"98"
smb::cloud.share@172.26.110.47//E-Commerce Cloud - domain$//|"90"
smb::cloud.share@172.26.110.47//ID Cloud - domain$//|"89"
smb::cloud.share@172.26.110.47//Shop in Shop Cloud - domain$//|"88"
smb::cloud.share@172.26.110.47//WM Cloud - domain$//|"87"
smb::cloud.share@172.26.110.47//corporate documents//domain/|"83"
smb::domain/cloud.shar@172.26.110.47//corporate documents//domain/|"41"
smb::domain/cloud.share@172.26.110.47//CS Cloud - domain$//|"62"
smb::domain/cloud.share@172.26.110.47//DH Cloud - domain$//|"63"
smb::domain/cloud.share@172.26.110.47//DM - FM$//|"43"
smb::domain/cloud.share@172.26.110.47//ID Cloud - domain$//|"65"
smb::domain/cloud.share@172.26.110.47//WM Cloud - domain$//|"67"
smb::domain/cloud.share@172.26.110.47//corporate documents//domain/|"40"
smb::domain\\cloud.share@172.26.110.13//Corporate documents$//|"7"
smb::domain\\cloud.share@172.26.110.13//Corporate documents$//domain/|"9"
smb::domain\\cloud.share@172.26.110.13//ods$//|"8"
smb::domain\\cloud.share@172.26.110.47//corporate documents//|"38"
smb::domain\\cloud.share@172.26.110.47//corporate documents//domain/|"39"
smb::domain\\t.junker@172.26.110.13//ods$//|"6"
smb::domain\\t.junker@domain.local//\\//|"3"
smb::domain\\t.junker@domain.local//\\Corporate documents\//"|"5"
smb::domain\\t.junker@domain.local//\\Corporate documents//|"4"
webdav::owncloudsu@172.26.112.7//owncloud/remote.php/webdav//|"30"
webdav::owncloudsu@172.26.112.7/owncloud/remote.php/webdav///|"31"
webdav::owncloudsu@172.26.112.7/remote.php/webdav//|"27"
webdav::owncloudsu@172.26.112.7/remote.php/webdav///|"28"
webdav::t.junker@172.26.112.7//owncloud/remote.php/webdav//|"29"
webdav::t.junker@172.26.112.7//remote.php/webdav//|"26"
webdav::t.junker@172.26.112.7/remote.php/webdav//|"25"
webdav::t.junker@cloud.domain-mode.de//remote.php/webdav//|"21"
webdav::t.junker@cloud.domain-mode.de/remote.php/webdav//|"23"
webdav::t.junker@cloud.domain-mode.de/remote.php/webdav///|"22"
webdav::t.junker@cloud.domain-mode.de/remote.php/webdav/ODS//|"24"
webdav::t.junker@cloud.domain-fashion.com//remote.php/webdav//|"20"

![phpmyadmin](https://cloud.githubusercontent.com/assets/10863564/9249439/29f75dd4-41c5-11e5-8b59-6d8fec6bc877.JPG)


I am confused and would not like to change something in the database, because I am very uncertain in this thema. I can't match all entries from the db to the smb shares from the admin panel?!

Can someone help?

**Comment by PVince81** [comment]
@JT1301 if you don't want to touch the database, best is to not upgrade now.

We need to investigate why domain/username stopped working and make it work again in 8.1.x so you won't need to change anything.

**Comment by JT1301** [comment]
@PVince81 I need the update urgently but I must ensure that it can continue running smoothly in the future so I'd rather wait for the update.

I like to help so if I can do something please let me know.

Regards

**Comment by icewind1991** [comment]
You can try using [libsmbclient-php](https://github.com/eduardok/libsmbclient-php) some people had more luck with that then the smbclient fallback.

I'll look into the domain/user issue

**Comment by JT1301** [comment]
> After I update my server from 8.0.4 to 8.1.1 and the new smb client (owncloud/documentation#1447)

I think this is the same one? Without installing the libsmbclient I didn't get a connection to my smb shares -> https://github.com/owncloud/core/issues/18268

**Comment by icewind1991** [comment]
Yes, it is the same one

**Comment by JT1301** [comment]
Are there already any solution? Or is there a patch in prospect?

**Comment by icewind1991** [comment]
You can see if #18397 fixes the problem

**Comment by JT1301** [comment]
I've tried it this way: (Was my first time? Did I do something wrong?)
> wget https://github.com/owncloud/core/commit/b9e58098692eaf387e366754b03c5225e2bd6898.patch 
git apply --reject --whitespace=fix b9e58098692eaf387e366754b03c5225e2bd6898.patch
service apache2 restart

Still unable to connect to the SMB Shares.

###### Disable extension="libsmbclient.so" in php.ini:
>**Aug 19 15:22:38 NTSH054 ownCloud[26947]: {PHP}** Cannot modify header information - headers already sent at /var/www/owncloud/lib/private/response.php#103
**Aug 19 15:22:38 NTSH054 ownCloud[26951]: {webdav}** Exception: {"Message":"Invalid hostname","Code":0,"Trace":"#0 \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Connection.php(43): Icewind\\SMB\\Connection->checkConnectionError('tree connect fa...')\n#1 \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Share.php(343): Icewind\\SMB\\Connection->read()\n#2 \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Share.php(119): Icewind\\SMB\\Share->execute('allinfo \"\\\\Somed...')\n#3 \/var\/www\/owncloud\/apps\/files_external\/lib\/smb.php(102): Icewind\\SMB\\Share->stat('\/Someday\/11 Myr...')\n#4 \/var\/www\/owncloud\/apps\/files_external\/lib\/smb.php(136): OC\\Files\\Storage\\SMB->getFileInfo('')\n#5 \/var\/www\/owncloud\/lib\/private\/files\/storage\/common.php(167): OC\\Files\\Storage\\SMB->stat('')\n#6 \/var\/www\/owncloud\/apps\/files_external\/lib\/smb.php(171): OC\\Files\\Storage\\Common->filemtime('')\n#7 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(376): OC\\Files\\Storage\\SMB->hasUpdated('', 1438074137)\n#8 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(376): OC\\Files\\Storage\\Wrapper\\Wrapper->hasUpdated('', 1438074137)\n#9 \/var\/www\/owncloud\/lib\/private\/files\/cache\/watcher.php(89): OC\\Files\\Storage\\Wrapper\\Wrapper->hasUpdated('', 1438074137)\n#10 \/var\/www\/owncloud\/lib\/private\/files\/view.php(1182): OC\\Files\\Cache\\Watcher->checkUpdate('', Array)\n#11 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/objecttree.php(148): OC\\Files\\View->getFileInfo('11 Myriam Bleck...')\n#12 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/custompropertiesbackend.php(101): OC\\Connector\\Sabre\\ObjectTree->getNodeForPath('11 Myriam Bleck...')\n#13 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/PropertyStorage\/Plugin.php(86): OC\\Connector\\Sabre\\CustomPropertiesBackend->propFind('11 Myriam Bleck...', Object(Sabre\\DAV\\PropFind))\n#14 [internal function]: Sabre\\DA
**Aug 19 15:22:43 NTSH054 ownCloud[26945]: {index}** Exception: {"Exception":"Icewind\\SMB\\Exception\\InvalidHostException","Message":"Invalid hostname","Code":0,"Trace":"#0 \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Connection.php(43): Icewind\\SMB\\Connection->checkConnectionError('tree connect fa...')\n#1 \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Share.php(343): Icewind\\SMB\\Connection->read()\n#2 \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Share.php(119): Icewind\\SMB\\Share->execute('allinfo \"\\\\Somed...')\n#3 \/var\/www\/owncloud\/apps\/files_external\/lib\/smb.php(102): Icewind\\SMB\\Share->stat('\/Someday\/26 Sus...')\n#4 \/var\/www\/owncloud\/apps\/files_external\/lib\/smb.php(272): OC\\Files\\Storage\\SMB->getFileInfo('PV&SEPA')\n#5 \/var\/www\/owncloud\/lib\/private\/files\/storage\/common.php(90): OC\\Files\\Storage\\SMB->filetype('PV&SEPA')\n#6 \/var\/www\/owncloud\/lib\/private\/files\/storage\/common.php(124): OC\\Files\\Storage\\Common->is_dir('PV&SEPA')\n#7 \/var\/www\/owncloud\/lib\/private\/files\/storage\/common.php(148): OC\\Files\\Storage\\Common->isCreatable('PV&SEPA')\n#8 \/var\/www\/owncloud\/lib\/private\/files\/storage\/common.php(605): OC\\Files\\Storage\\Common->getPermissions('PV&SEPA')\n#9 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/encryption.php(149): OC\\Files\\Storage\\Common->getMetaData('PV&SEPA')\n#10 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(543): OC\\Files\\Storage\\Wrapper\\Encryption->getMetaData('PV&SEPA')\n#11 \/var\/www\/owncloud\/lib\/private\/files\/cache\/scanner.php(113): OC\\Files\\Storage\\Wrapper\\Wrapper->getMetaData('PV&SEPA')\n#12 \/var\/www\/owncloud\/lib\/private\/files\/cache\/scanner.php(141): OC\\Files\\Cache\\Scanner->getData('PV&SEPA')\n#13 \/var\/www\/owncloud\/lib\/private\/files\/cache\/scanner.php(265): OC\\Files\\Cache\\Scanner->scanFile('PV&SEPA', 1, -1, NULL, true)\n#14 \/var\/www\/owncloud\/lib\/private\/files\/c
**Aug 19 15:22:43 NTSH054 ownCloud[26945]: {PHP}** Cannot modify header information - headers already sent at /var/www/owncloud/lib/private/response.php#103

###### Enable extension="libsmbclient.so" in php.ini:
>**Aug 19 15:34:03 NTSH054 ownCloud[28299]: {index}** Exception: {"Exception":"Icewind\\SMB\\Exception\\ForbiddenException","Message":"Invalid request for smb:\/\/172.26.110.47\/DM - FM$\/Someday\/26%20Susanne%20Martini\/PV%26SEPA","Code":13,"Trace":"#0 \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/NativeState.php(72): Icewind\\SMB\\NativeState->handleError('smb:\/\/172.26.11...')\n#1 \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/NativeState.php(180): Icewind\\SMB\\NativeState->testResult(false, 'smb:\/\/172.26.11...')\n#2 \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/NativeShare.php(113): Icewind\\SMB\\NativeState->stat('smb:\/\/172.26.11...')\n#3 \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/NativeShare.php(108): Icewind\\SMB\\NativeShare->getStat('\/Someday\/26 Sus...')\n#4 \/var\/www\/owncloud\/apps\/files_external\/lib\/smb.php(102): Icewind\\SMB\\NativeShare->stat('\/Someday\/26 Sus...')\n#5 \/var\/www\/owncloud\/apps\/files_external\/lib\/smb.php(272): OC\\Files\\Storage\\SMB->getFileInfo('PV&SEPA')\n#6 \/var\/www\/owncloud\/lib\/private\/files\/storage\/common.php(90): OC\\Files\\Storage\\SMB->filetype('PV&SEPA')\n#7 \/var\/www\/owncloud\/lib\/private\/files\/storage\/common.php(124): OC\\Files\\Storage\\Common->is_dir('PV&SEPA')\n#8 \/var\/www\/owncloud\/lib\/private\/files\/storage\/common.php(148): OC\\Files\\Storage\\Common->isCreatable('PV&SEPA')\n#9 \/var\/www\/owncloud\/lib\/private\/files\/storage\/common.php(605): OC\\Files\\Storage\\Common->getPermissions('PV&SEPA')\n#10 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/encryption.php(149): OC\\Files\\Storage\\Common->getMetaData('PV&SEPA')\n#11 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(543): OC\\Files\\Storage\\Wrapper\\Encryption->getMetaData('PV&SEPA')\n#12 \/var\/www\/owncloud\/lib\/private\/files\/cache\/scanner.php(113): OC\\Files\\Storage\\Wrapper\\Wrapper->getMetaData('PV&SEPA')\n#13 \/var\/www\/own
**Aug 19 15:34:03 NTSH054 ownCloud[28299]: {PHP}** Cannot modify header information - headers already sent at /var/www/owncloud/lib/private/response.php#103

**Comment by JT1301** [comment]
@icewind1991 @PVince81 Any Idea?

**Comment by JT1301** [comment]
Can someone give me an info?

Do I need to change the account information for the SMB drive?
Or is an update planned?

**Comment by PVince81** [comment]
> Do I need to change the account information for the SMB drive?

@Xenopathic @icewind1991 ^

**Comment by icewind1991** [comment]
I believe 8.1.3 correctly trims the domain from the the username when used in the storage id so that should be with the storage id as it was in 8.0.x

**Comment by icewind1991** [comment]
Can you re-test this with 8.1.5/8.2.1

**Comment by seabird** [comment]
@icewind1991 I installed 8.2.1 and got the error  [code]Exception: {"Exception":"Icewind\\SMB\\Exception\\Exception","Message":"Unknown error (NT_STATUS_OBJECT_NAME_INVALID) for \/","Code":0,"Trace":"#0 \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Share.php(365): Icewind\\SMB[code] So I installed libsmbclient and php -i confirms it is enabled version 0.5

Now I get a new error: [code]Exception: {"Message":"Invalid request for smb:\/\/localhost\/jacco\/Documents","Exception":"Icewind\\SMB\\Exception\\ForbiddenException","Code":13,"Trace":"#0 \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/NativeState.php(72): Icewind\\SMB\\NativeState->handleError('smb:\/\/localhost...')\n#1 \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/NativeState.php(180): Icewind\\SMB\\NativeState->testResult(false, 'smb:\/\/localhost...')\n#2 \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/NativeShare.php[code[

**Comment by icewind1991** [comment]
> Exception: {"Exception":"Icewind\\SMB\\Exception\\Exception","Message":"Unknown error (NT_STATUS_OBJECT_NAME_INVALID) for \/","Code":0,"Trace":"#0 \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Share.php(365): Icewind\\SMB

Are you using DFS?

**Comment by seabird** [comment]
What do you mean with DFS? The samba shares are hosted on the same Debian server as owncloud. The only reason to not use local folder is the ownership of the files

**Comment by MorrisJobke** [comment]
@JT1301 Can I ask you to test with 8.1.5 or 8.2.1? Is this then still an issue?

**Comment by michaelstingl** [comment]
@MorrisJobke re-install solved the problem.
