### ISSUE TITLE
PHP Error with files_sharing after Update from Owncloud 8.0.5 to 8.1.1

### ISSUE THREAD

**Issue by Plumlum** [owncloud/core#18263]
### Steps to reproduce
First try was to update my owncloud 8.0.5 via web updater - has given me a timeout.

So i tried php occ upgrade, worked fine, until the end of the process it showed a php error.

### Expected behaviour
clean upgrade to 8.1.1

### Actual behaviour
PHP Fatal error: Class 'OC_FileProxy' not found in /var/www/virtual/user/html/owncloud/apps/files_sharing/appinfo/app.php on line 28 (after update on command line)

The Windows sync client throws a https://domain/owncloud/remote.php/webdav/ - server replied: Internal Server Error

### Server configuration
CentOS release 6.7 (Final)
Server version: Apache/2.2.15 (Unix)
Database: MYSQL 8.1.1.3
PHP 5.6.10 (cli) (built: Jun 12 2015 23:08:43)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
**Updated from an older ownCloud or fresh install:**
Update from 8.0.5 to 8.1.1.

**List of activated apps:**
 - activity: 1.2.1
 - files: 1.1.9
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - gallery: 0.6.0
 - updater: 0.4

config.php
'datadirectory' => '/var/www/virtual/user/html/owncloud/data', 'dbtype' => 'mysql', 'version' => '8.1.1.3', 'dbname' => 'user', 'dbhost' => 'localhost', 'dbtableprefix' => 'oc_', 'dbuser' => 'user, 'dbpassword' => 'pw', 'installed' => true, 'forcessl' => true, 'theme' => '', 'maintenance' => false, 'secret' => 

Alerts within the admin webpanel (in german)

Wenn sich Ihre Installation nicht im Wurzelverzeichnis der Domain befindet und Cron aus dem System genutzt wird, kann es zu Fehlern bei der URL-Generierung kommen. Um dies zu verhindern, setzen Sie bitte die „overwrite.cli.url“-Option in Ihrer config.php auf das Web-Wurzelverzeichnis Ihrer Installation (Vorschlag: „/owncloud“).
Ihr Webserver ist noch nicht hinreichend für Datei-Synchronisation konfiguriert, weil die WebDAV-Schnittstelle vermutlich defekt ist.
Fehler beim Überprüfen der Servereinrichtung
Der „Strict-Transport-Security“-HTTP-Header ist nicht auf mindestens „15768000“ Sekunden eingestellt. Für umfassende Sicherheit wird das Aktivieren von HSTS empfohlen, wie es in unseren Sicherheitshinweisen erläutert ist.

@MorrisJobke

**Comment by PVince81** [comment]
@Plumlum the class "OC_FileProxy" was removed a while ago.

How did you upgrade ? Did you make sure to delete the old PHP code and replace it with the new version of the PHP code ?

**Comment by PVince81** [comment]
@Plumlum ok I see, you used the updater app and it gave a timeout.
It is likely that the updater app has replaced only half of the PHP code resulting in a broken state.

Please try manually removing the old code and extracting the tar.bz2 from 8.1.1 there.

Also note that `./occ upgrade` and the updater are NOT the same thing.
`./occ upgrade` only updates the database to match the schemas, it doesn't actually update the code. This command must be run after manually updating the code. (maybe we should rename this to avoid confusion...).

**Comment by PVince81** [comment]
CC @VicDeo for the updater app. We need to find a way to prevent such broken states.

**Comment by MorrisJobke** [comment]
@Plumlum is there anything in the owncloud.log inside the data directory?

**Comment by Plumlum** [comment]
This is the text of the german update center (the step before you click the update button):

ownCloud wird auf Version 8.1.1 aktualisiert.

Stellen Sie vor dem Fortsetzen bitte sicher, dass die Datenbank, der Konfigurationsordner und der Datenordner gesichert wurden.

Zur Vermeidung von Zeitüberschreitungen bei größeren Installationen können Sie stattdessen den folgenden Befehl in Ihrem Installationsverzeichnis ausführen:
./occ upgrade"


So, the short version: To avoid timeouts, use occ. I´m totally able to use a shell, 
But if a system provides me with a easy one click solution, i´ll use it, and if it offers me also a alternative solution, i try it. Both, the update center (because timeout) and the occ are not working right in that case, am i right?

The official Documentation says: https://doc.owncloud.org/server/8.0/admin_manual/maintenance/upgrade.html

Note
"The occ command does not download ownCloud updates. You must first download and install the updated code (steps 1-3), and then occ performs the final upgrade steps."

Maybe the text in the upgrade center should be adjusted. It misguids.

@MorrisJobke yeah, pretty much stuff, but i don´t have time to censor my private informations out of the log now to post it.

**Comment by MorrisJobke** [comment]
Just FYI: I will meet this evening with @Plumlum and have a look at the log file. I wil lreport back.

**Comment by arpee** [comment]
Workaround confirmation as posted by @PVince81 

* replaced codebase with clean copy
* moved old config and data folders into place
* checked all file permissions correct
* (i did not have any 3rd party apps in place but this is where you would copy those in place)

Opened owncloud url in browser successfully.

Richard

**Comment by MorrisJobke** [comment]
A second run of the upgrade with a backup of the data before the upgrade just worked on @Plumlum's instance. I will get the log provided - maybe something useful can be found in there.

**Comment by pylight** [comment]
Had the same error when upgrading to 8.1.1 today. I did the following to get owncloud working again (don't know if it was clever / should be followed, but it worked for me :p)
* moved owncloud/apps/files_sharing/ and owncloud/apps/files/ folders away to /tmp/
  * note: files folder was also needed, otherwise webdav didn't work anymore after the update
* downloaded oc 8.1.1 from https://github.com/owncloud/core/releases and unpacked it
* copied the unpacked apps/files_sharing and apps/files to my owncloud installation 
* executed the upgrade comand on comand line:
  * sudo -u www-data php occ upgrade
* note: I had to update my linux occ sync client after the update but this seems to be [wanted behavior](https://forum.owncloud.org/viewtopic.php?f=31&t=29102)

**Comment by viasys** [comment]
I have the same Issue when I try to upgrade from 8.04, i already get an error during the updater procedure. The first step of backuping works fine but the "Download & Extract" step gives me a error and tells me to look into the webserver logs. I cannot find any errors in the webserver or the owncloud logs. I tried it twice with a rollback to a snapshot, same result in both times, the Updater just keeps going but will end up with the error described by the creater of this report. Is there any option on how to prevent this other than doing a manual update?

**Comment by dp87** [comment]
@viasys If you don't want to go through a manual upgrade, disabling the files_sharing app should allow you to complete the upgrade successfully:

`sudo -u your_web_server_user php occ app:disable files_sharing`
`sudo -u your_web_server_user php occ upgrade`

When this completes, you have to manually exit maintenance mode:

`sudo -u apache php occ maintenance:mode --off`

**Comment by DeepDiver1975** [comment]
As far as I can tell the upgrade was not properly performed -> closing
