### ISSUE TITLE
SMB shares will not be downloaded

### ISSUE THREAD

**Issue by JT1301** [owncloud/core#18268]
Hello, 
I have a problem with the OwnCloud Client 1.8.4 after upgrading from 8.0.4 to 8.1.1.

My test environment configuration:

Operating system: Debian Wheezy
Web server: Apache
Database: MySQL
PHP version: 5.4.41
ownCloud version: 8.1.1

Windows Server 2012 R2 with DFS Shares

Client configuration
Operating system: Windows 8 (x64) / Windows 7 (x64) (same result)
Client app: Windows Owncloud Client 1.8.4 (Problem)
**Client app: Windows OwnCloud Client (Version 2.0.0-nightly20150812 (build 5391)) (Works fine!)**

**The Client can download data that is stored on the owncloud server but there are problems with data on smb shares.**

###### My upgrade process:

I tried to upgrade from Owncloud 8.0.4 to the latest version.

> apt-get update
apt-get dist-upgrade

###### While Upgrading:

> owncloud-server: occ upgrade
ownCloud or one of the apps require upgrade - only a limited number of commands are available
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Updating <files> ...
Updated <files> to 1.1.10
Updating <activity> ...
{"reqId":"QRoXPLW3TpIWlxuBlOFN","remoteAddr":"","app":"acitivity","message":"Deleting 0 activities with a broken subjectparams value.","level":0,"time":"2015-07-29T12:59:48+00:00","method":"--","url":"--"}
{"reqId":"QRoXPLW3TpIWlxuBlOFN","remoteAddr":"","app":"acitivity","message":"Deleting 0 activities with a broken messageparams value.","level":0,"time":"2015-07-29T12:59:49+00:00","method":"--","url":"--"}
{"reqId":"QRoXPLW3TpIWlxuBlOFN","remoteAddr":"","app":"acitivity","message":"Deleting 0 activities with a broken amq_subjectparams value.","level":0,"time":"2015-07-29T12:59:49+00:00","method":"--","url":"--"}
Updated <activity> to 2.0.1
Updating <files_sharing> ...
Updated <files_sharing> to 0.6.2
Updating <files_trashbin> ...
Updated <files_trashbin> to 0.6.3
Updating <files_versions> ...
Updated <files_versions> to 1.0.6
Update successful
Turned off maintenance mode

Here I tried to connect to my smb shares but there is no connection. Try to reconnect in the Adminpanel but no entry in the owncloud log.

###### SMB Client Update:
When I try to install the new smb client:

> echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.1/Debian_7.0/ /' >> /etc/apt/sources.list.d/php5-libsmbclient.list 
wget http://download.opensuse.org/repositories/isv:ownCloud:community:8.1/Debian_7.0/Release.key
apt-key add - < Release.key  
apt-get update
apt-get install php5-libsmbclient

I check the adminpanel again but no connection. **First when I change the username from domain\username to username I got a connection.**  (In OwnCloud 8.0.4 only the username didn't work!) Sometimes it takes several attempts until it is green. And sometimes it is just red again until I rescann it manually.

Client LOG:
![owncloud1](https://cloud.githubusercontent.com/assets/10863564/9247468/80a10fc0-41b3-11e5-8da8-8e7701f926a2.JPG)

> 08-13 11:54:30:005 0x3d9c9f8 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://cloud.owncloud-server.com" + "/"
08-13 11:54:35:213 0x60187b8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x87f5c70) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-13 11:54:35:213 0x60187b8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x87f5c70) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-13 11:54:35:214 0x60187b8 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x87f5c70) QObject(0x0)  0 false 3 0
08-13 11:54:38:711 0x3d9c9f8 OCC::AbstractNetworkJob::start: !!! OCC::CheckQuotaJob created for "https://cloud.owncloud-server.com" + "/"
08-13 11:54:39:676 0x3d9c9f8 OCC::FolderMan::slotEtagPollTimerTimeout: void OCC::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag
08-13 11:54:43:924 0x60187b8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x87f5c70) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-13 11:54:43:926 0x60187b8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x87f5c70) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-13 11:54:43:926 0x60187b8 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x87f5c70) QObject(0x0)  0 false 3 0
08-13 11:55:05:926 0x3d9c9f8 unknown: Failed to resolve EGL function eglGetPlatformDisplayEXT (Die angegebene Prozedur wurde nicht gefunden.)
08-13 11:55:05:928 0x3d9c9f8 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): Could not initialize EGL display: error 0x3001

> 08-13 11:55:05:928 0x3d9c9f8 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): When using ANGLE, check if d3dcompiler_4x.dll is available
08-13 11:55:06:013 0x3d9c9f8 unknown: Failed to resolve EGL function eglGetPlatformDisplayEXT (Die angegebene Prozedur wurde nicht gefunden.)
08-13 11:55:06:014 0x3d9c9f8 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): Could not initialize EGL display: error 0x3001

> 08-13 11:55:06:015 0x3d9c9f8 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): When using ANGLE, check if d3dcompiler_4x.dll is available
08-13 11:55:07:233 0x60187b8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x87f5c70) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-13 11:55:07:234 0x60187b8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x87f5c70) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-13 11:55:07:234 0x60187b8 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x87f5c70) QObject(0x0)  0 false 3 0
08-13 11:55:08:912 0x3d9c9f8 OCC::AbstractNetworkJob::start: !!! OCC::CheckQuotaJob created for "https://cloud.owncloud-server.com" + "/"
08-13 11:55:09:677 0x3d9c9f8 OCC::FolderMan::slotEtagPollTimerTimeout: void OCC::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag
08-13 11:55:10:130 0x3d9c9f8 unknown: Failed to resolve EGL function eglGetPlatformDisplayEXT (Die angegebene Prozedur wurde nicht gefunden.)
08-13 11:55:10:131 0x3d9c9f8 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): Could not initialize EGL display: error 0x3001

> 08-13 11:55:10:132 0x3d9c9f8 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): When using ANGLE, check if d3dcompiler_4x.dll is available
08-13 11:55:10:213 0x3d9c9f8 unknown: Failed to resolve EGL function eglGetPlatformDisplayEXT (Die angegebene Prozedur wurde nicht gefunden.)
08-13 11:55:10:215 0x3d9c9f8 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): Could not initialize EGL display: error 0x3001

> 08-13 11:55:10:215 0x3d9c9f8 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): When using ANGLE, check if d3dcompiler_4x.dll is available
08-13 11:55:14:119 0x60187b8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x87f5c70) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-13 11:55:14:119 0x60187b8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x87f5c70) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-13 11:55:14:119 0x60187b8 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x87f5c70) QObject(0x0)  0 false 3 0
08-13 11:55:28:676 0x3d9c9f8 unknown: Failed to resolve EGL function eglGetPlatformDisplayEXT (Die angegebene Prozedur wurde nicht gefunden.)
08-13 11:55:28:678 0x3d9c9f8 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): Could not initialize EGL display: error 0x3001

> 08-13 11:55:28:678 0x3d9c9f8 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): When using ANGLE, check if d3dcompiler_4x.dll is available
08-13 11:55:34:004 0x3d9c9f8 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
08-13 11:55:34:006 0x3d9c9f8 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://cloud.owncloud-server.com" + "/"

Can someone help me there?

Regards,

JT

PS: There is a Bugreport in https://github.com/owncloud/client/issues/3614 but they told me to create one in owncloud/core too.

Perhaps it is also related to my other problem
https://github.com/owncloud/core/issues/18267

**Comment by icewind1991** [comment]
@JT1301 could you try out #18287 **without** having `libsmbclient-php` installed

**Comment by JT1301** [comment]
@icewind1991 Can you tell me what I need to do? I think the update icewind/smb to 1.0.3 isn't created 
so far..?

**Comment by JT1301** [comment]
Ok, I build the new libsmbclient-php and uninstall the package.

> apt-get remove php5-libsmbclient
 sudo apt-get install libsmbclient-dev libsmbclient php5-dev
wget -O /tmp/libsmbclient-php.zip https://github.com/eduardok/libsmbclient-php/archive/master.zip
unzip /tmp/libsmbclient-php.zip -d /tmp
cd /tmp/libsmbclient-php-master
phpize && ./configure && make && sudo make install
echo 'extension="libsmbclient.so"' >> /etc/php5/apache2/php.ini

The Logs are long but it didn't work.
https://cloud.simplicity.ag/index.php/s/FzCdJZhBr7uLVrp
Password: github

Offtopic: Is there another way to upload files or to post long logs?

**Comment by JT1301** [comment]
Is there something new?

**Comment by MorrisJobke** [comment]
> Is there something new?

@icewind1991

**Comment by icewind1991** [comment]
Can you re-test this with 8.1.5/8.2.1 and libsmbclient-php enabled

**Comment by MorrisJobke** [comment]
> Can you re-test this with 8.1.5/8.2.1 and libsmbclient-php enabled

I guess you are referring to https://github.com/eduardok/libsmbclient-php#getting-started

**Comment by icewind1991** [comment]
Yes, we also provided packages for it for various distros (dont know where though)

**Comment by MorrisJobke** [comment]
> Yes, we also provided packages for it for various distros (dont know where though)

@jnweiger Can you provide us with a link to the packages? That would be really nice ;)

**Comment by JT1301** [comment]
It is not the smbclient in this repository, right? http://download.owncloud.org/download/repositories/stable/Debian_7.0/

With this "apt-get install php5-libsmbclient" I can connect to the shares in 8.2.1 when I change the username from "domain/username" to "username"

![unbenannt](https://cloud.githubusercontent.com/assets/10863564/11401462/f6a8f6fc-9392-11e5-9b10-17cc2b6e05c7.JPG)

**Comment by MorrisJobke** [comment]
@icewind1991 Any further idea, what this could be?

**Comment by bboule** [comment]
@icewind1991 @cmonteroluque any thoughts on this??

**Comment by cmonteroluque** [comment]
@icewind1991 ping

**Comment by michaelstingl** [comment]
@MorrisJobke re-install solved the problem.
