### ISSUE TITLE
Still have "forbidden 403" with 8.1.1

### ISSUE THREAD

**Issue by brunodegoyrans** [owncloud/core#18264]
Hello

On 30th JULY, I have upgraded to 8.1 and got the known encryption module failed bug.
As a result:
1) Within the web interface, I get a "forbidden 403" when I try to download most of the files.
2) In one directory structure, all the files had been set to 0 byte size.
Maybe other directories are impacted but I didnt check all my (huge) date structures.

In the owncloud forum, one told me to wait for 8.1.1. I was hoping that this release would solve the issues.
Today, I have installed 8.1.1. It does not solve the issue. I still have "forbidden 403" messages and several files are still set to 0 byte.

**Comment by PVince81** [comment]
@brunodegoyrans was it 8.1.0 ? or any of the 8.1.1 betas ?

**Comment by PVince81** [comment]
@schiesbn can you help ?

**Comment by nickvergessen** [comment]
I think you need to follow https://github.com/owncloud/core/issues/17574

The problem is you already broke your installation with the migration, so 8.1.1 does not auto fix it.

*might not be true, but that's what I understood about the issue*

**Comment by brunodegoyrans** [comment]
@PVince81 I first upgraded to 8.1.0 on 30th july, then upgraded to 8.1.1 today.

**Comment by brunodegoyrans** [comment]
@nickvergessen I had understood that 8.1.1 would fix it. It is written "This will be closed as soon as 8.1.1 is released.".

**Comment by brunodegoyrans** [comment]
Now this is a real mess. I can't follow https://github.com/owncloud/core/issues/17574 since, in step 3, it tells about quick fix that are avaiblable for 8.1.0
Should I apply these fixes for 8.1.1?

**Comment by nickvergessen** [comment]
No, skip step 3

**Comment by brunodegoyrans** [comment]
It has worked!

Thanks to all
