### ISSUE TITLE
Show failed connection to appstore in app overview (be more verbose)

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#18269]
Currently a lot of users are struggling with failed logins to the appstore for various reasons like:

- Missing /config/ca-bundle.crt (Currently unknown why this was missing)
- Wrong 'appstoreurl' in config.php (e.g. by copy over the config.sample.php in the past)
- Buggy OpenSSL/NSS/PHP versions
- Accidentally disabled 'appstoreenabled' in config.php
- Empty or wrong configured 'proxy' => '', in config.php (e.g. by copy over the config.sample.php in the past)
- Anything else?

This is causing an app overview with only the "Enabled" and "Not Enabled" categories but no other categories like "Productivity".

It could be useful to be a little bit more verbose on the app overview if a connection is failing to prevent a lot of duplicate issues / posts about the same problems.

**Comment by karlitschek** [comment]
Agreed. More verbose would be good. What do you think @LukasReschke ?

**Comment by RealRancor** [comment]
Sorry, dup of https://github.com/owncloud/core/issues/17156
