### ISSUE TITLE
Missing OCP replacement for \OC::$SERVERROOT

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#18276]
We have methods to get the data and user folders, but AFAIK when we need to get the server root to fetch data from the `tests` folder per example, then we don't have anything in the public space.

Should there be a way or are we happy letting apps use private APIs in their tests?

@DeepDiver1975 @LukasReschke @Raydiation

**Comment by DeepDiver1975** [comment]
We should have an OCP way to access this value - and others.

At the end the class OC has to die since it conflicts with the namespace OC

**Comment by DeepDiver1975** [comment]
What about introducing an interface IEnvironment where we add methods to get this and other values in the future?

**Comment by oparoz** [comment]
I don't know if IEnvironment is suitable. Let's ask more people. @PVince81 @MorrisJobke @rullzer @nickvergessen  @schiesbn

**Comment by Raydiation** [comment]
@DeepDiver1975 good idea, we've could also bundle the webroot with it. Maybe adjust the naming so that it's clear that it does not hold environment variables.

**Comment by nickvergessen** [comment]
Well it's the onwcloud enviroment right?

But yes +1 for a class that is mockable :)

**Comment by rullzer** [comment]
Yes please have it in some mockable way!
IEnviroment indeeds sounds confusing. IOCEnviroment maybe?

**Comment by nickvergessen** [comment]
> IEnviroment indeeds sounds confusing. IOCEnviroment maybe?

`OCP\IOCEnviroment`? sounds redundant to me, that is what namespaces are for. `OCP\IEnviroment` should be fine?

**Comment by LukasReschke** [comment]
`SystemEnvironment`, `ServerEnvironment`?

**Comment by DeepDiver1975** [comment]
feature freeze -> 9.0

**Comment by VicDeo** [comment]
inject EnvironmentHelper.
```
use OC\Helper\EnvironmentHelper;

	public function __construct(EnvironmentHelper $environmentHelper) {
		$this->environmentHelper = $environmentHelper;
	}

     public function doWhatever() {
		$serverRoot = $this->environmentHelper->getServerRoot();
		$webRoot = $this->environmentHelper->getWebRoot();
		$appsRoots = $this->environmentHelper->getAppsRoots();
		$fakeMustacheEnvVar = $this->environmentHelper->getEnvVar('FAKE_MUSTACHE');
	}
```
