### ISSUE TITLE
Consistent error messages if the provisioning API is disabled

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#18272]
Trying use the provisioning API while it's disabled returns different error messages depending on the specific call you're sending. This is confusing both because the error message doesn't mention that the provisioning API is disabled and also because of the different behaviour of the endpoints.

GET request to /ocs/v1.php/cloud/users?search=ad

```
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failed</status>
  <statuscode>999</statuscode>
  <message>Invalid query, please check the syntax. API specifications are here: http://www.freedesktop.org/wiki/Specifications/open-collaboration-services. DEBUG OUTPUT:
debug output:
http request method: GET
http request uri: /ocs/v1.php/cloud/users?search=ad
get parameter: search-&gt;ad
</message>
 </meta>
</ocs>
```

A DELETE request to /ocs/v1.php/cloud/users/qwerty ("qwerty" user is missing) returns a HTTP 405 code with no info.

**Comment by karlitschek** [comment]
O.K. But if a user disables an app then no useful error message can be expected. No not high priority from my point of view.

**Comment by mantir** [comment]
I didn't know that the API was disabled and was looking for a solution for more than have an hour. It would be a time saver for people to have a good error message there.
