### ISSUE TITLE
Order of actions in action dropdown, move Delete to last position

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#18280]
The current order of actions is:
* Download
* Rename
* Delete
* Versions

Delete should be moved to the last position though, as it’s a destructive action. It should always be last and not just somewhere in the list. @PVince81 @owncloud/designers

**Comment by PVince81** [comment]
File actions cannot be ordered.

The order you see is the order in which they were registered. Since the code of the versions app ran last, the versions entry appears last. Further third party app actions might appear below.

I suggest to introduce a "sort" or "order" attribute in `FileActions.registerAction()` to make it possible to order them.

**Comment by PVince81** [comment]
So basically "Delete" would get a "order" value of 1000 or more to make sure it's always at the bottom.
Others I'd say "10", "20", "30", etc to make it possible for apps to insert their actions in-between.

**Comment by jancborchardt** [comment]
Not another order value like the crazy one we have for apps please – it allows any app to mess with the order.

I would say we should force that from core so Delete is always last. And Download and Rename should always be first. The rest can just be sorted inbetween there however it wants (I only care about Versions). Ok?

**Comment by PVince81** [comment]
Ok, I'll see what I can do.

**Comment by jancborchardt** [comment]
Thanks!

**Comment by MorrisJobke** [comment]
I have to agree with @jancborchardt ...another order value doesn't solve this properly :see_no_evil:

**Comment by PVince81** [comment]
@MorrisJobke @jancborchardt then please tell me how should I specify the order of items, knowing that many items are provided by plugins. Do we want to hard-code plugin names in the core JS and given them priority ?

This will be important not only for the file actions menu which needs a specific order but also the order of the sidebar tabs.

**Comment by PVince81** [comment]
Note that the proposed "index"/"sort" setting could also be made internal/secret and undocumented, so only core plugins would explicitly specify their order and not third party ones.

**Comment by PVince81** [comment]
Let's have a meeting today about this to discuss solutions for this dilemma.

**Comment by PVince81** [comment]
The order will be:
* Details
* Download
* Rename
* ~~Versions~~
* Delete

(from https://github.com/owncloud/core/pull/18273#issuecomment-137271842)

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/core/pull/19401
