### ISSUE TITLE
apcu fails to load in 8.1.1

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#18285]
Ubuntu 14.04, ownCloud-8.1.1 deb installation.

apt-get install php5-apcu
Get:1 http://archive.ubuntu.com/ubuntu/ utopic/universe php5-apcu amd64 4.0.6-1 [78.4 kB]

php -m | grep apcu
shows apcu.

I am enabling the memcache according to config.sample.php like this in config.php:
<pre>
   'memcache.local' => '\\OC\\Memcache\\APCu',
</pre>

sudo -u www-data php /var/www/owncloud/occ status
An unhandled exception has been thrown:
OC\HintException: [0]: Missing memcache class \OC\Memcache\APCu for local cache (Is the matching PHP module installed and enabled ?)

Same procedure on 8.0.5 works fine. 
Thanks to @cdamken for double checking with tar installs and 8.0.5.

**Comment by BenMatheja** [comment]
is apcu enabled for php-cli? (e.g. via apcu.enable_cli = 1 in /etc/php5/cli/php.ini)

**Comment by Xenopathic** [comment]
14.04 packages APCu 4.0.2, while we require a minimum version of 4.0.6: #14386

**Comment by jnweiger** [comment]
ah, I was looking at a 14.10 box to check the version -- for 14.04 it is 4.0.2 indeeed. Thanks.

**Comment by jnweiger** [comment]
I am having this issue on a 14.10 box with 

* owncloud-8.1.1
* php5-apcu 4.0.6 and 
* apcu.enable_cli = 1 in /etc/php5/cli/php.in

As soon as I add 'memcache.local' => '\OC\Memcache\APCu', to config.php two things happen:

The memcache warning in http://WEBSERVER/owncloud/index.php/settings/admin disappears, and occ fails to work as described above.

Whereas with owncloud-8.0.6 the memcache warning disappears as expected, and occ still works.
Am I still doing something wrong?

**Comment by jnweiger** [comment]
confirmed with ubuntu 14.10,  apcu 4.0.6, owncloud 8.1.1
if we have apc.enable_cli = 1
in /etc/php5/cli/php.ini, then occ works again.

**Comment by jnweiger** [comment]
As the officially supported Ubuntu 14.04 LTS does not provide the required version, and everybody seems to come up with strange workarounds, I am providing a Debian package here: http://software.opensuse.org/download.html?project=isv%3AownCloud%3Acommunity%3A8.1&package=php5-apcu

**Comment by cdamken** [comment]
Habemus ACPU!! 

@jnweiger Thanks!!! finally the error in the admin page disappear,

but: 

I have in config.php ``` 'memcache.local' => '\OC\Memcache\APCu',```
an the error still appears:

```
root@ubuntu-test:/var/www/html/oc811# sudo -u www-data php ./occ status
An unhandled exception has been thrown:
OC\HintException: [0]: Missing memcache class \OC\Memcache\APCu for local cache (Is the matching PHP module installed and enabled ?)
```

**Comment by jnweiger** [comment]
@cdamken 
Since 8.1.1 you also need to say
```echo 'apcu.enable_cli=1' >> /etc/php5/cli/php.ini```

**Comment by RealRancor** [comment]
Seems there are some issues with this newer package: https://forum.owncloud.org/viewtopic.php?f=31&t=29826

**Comment by cdamken** [comment]
@jnweiger  https://github.com/owncloud/core/issues/18324
