### ISSUE TITLE
Better feedback on upgrade page

### ISSUE THREAD

**Issue by Xenopathic** [owncloud/core#18281]
When an upgrade is being performed, the page can sit for quite a while at 'Turned on maintenance mode' (and other steps, but mainly this one) while it calculates the required DB changes. During this time, there is no feedback to the user that stuff is going on. At the very least, there should be a spinner or 'scrolling' progress bar. An ideal solution would involve a pinging service that checks if the upgrade is still in progress and hasn't broken (this could be difficult though, so this ticket is for the spinner).

cc @jancborchardt

**Comment by jancborchardt** [comment]
Yeah, there should be a spinner displayed. This seems to be a duplicate or at least basically the same as https://github.com/owncloud/core/issues/17391 ?

**Comment by Xenopathic** [comment]
/me should search for existing issues before posting a new one...

**Comment by jancborchardt** [comment]
@Xenopathic oh yes! And next time fill out the issue template too ;D
