### ISSUE TITLE
Misleading error message when sharing file after having shared parent folder

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#18298]
### Steps to reproduce

1. Share folder with another user
2. Click on folder
3. Share file with the same user

If that doesn't work through the GUI, try the client, the api or through code commands.

### Expected behaviour

> Sharing 1893009 failed, because a parent folder is already shared with tester

There must be a condition triggering that message, so it should be easy to change the message at that point.

### Actual behaviour

> Sharing 1893009 failed, because this item is already shared with tester

The message is confusing, because the actual item is shared indirectly

**Comment by karlitschek** [comment]
good point. pull request welcome :-)

**Comment by PVince81** [comment]
@rullzer didn't you fix the message lately ?

**Comment by rullzer** [comment]
Yes this should not happen anymore in 9.0.x

**Comment by cmonteroluque** [comment]
ok, re-open if necessary
