### ISSUE TITLE
Sidebar design details

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#18291]
![capture du 2015-08-13 17-18-22](https://cloud.githubusercontent.com/assets/925062/9253703/9153660c-41df-11e5-8854-b37405c0161f.png)

@PVince81 @MorrisJobke @blizzz someone of you needs to do:
* [x] do not show the sections if there is only one, for example sharing. In that case the switcher is not needed
* [x] do not show the owner info if I myself am the owner.

I or @owncloud/designers needs to do:
* [ ] the tooltips on the details are transparent because the text is transparent. Can we move them out of that container? Otherwise we need to adjust the text color (instead of opacity)
* [ ] the tooltip for the folder name is always shown in the middle of the sidebar. Needs to be fixed by setting display:inline-block

**Comment by PVince81** [comment]
Two first items addressed here: https://github.com/owncloud/core/pull/18318

**Comment by jancborchardt** [comment]
Last item superseded by https://github.com/owncloud/core/issues/18601
