### ISSUE TITLE
when smb connection is dropped it break syncing for all local storage

### ISSUE THREAD

**Issue by lachlan-00** [owncloud/core#18299]
I turned off a file server for maintenance and have noticed that if your file connection is lost it will break syncing for all storage. I have my owncloud data folder, a local folder and an smb connection connected to my owncloud.

I also got this error in admin:
Your web server is not yet set up properly to allow file synchronization because the WebDAV interface seems to be broken.

```
Exception: {"Message":"","Code":0,"Trace":"
#0 \/opt\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Connection.php(37): Icewind\\SMB\\Connection->checkConnectionError('Connection to f...')\n
#1 \/opt\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Share.php(346): Icewind\\SMB\\Connection->read()\n
#2 \/opt\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Share.php(122): Icewind\\SMB\\Share->execute('allinfo \"\"')\n
#3 \/opt\/owncloud\/apps\/files_external\/lib\/smb.php(102): Icewind\\SMB\\Share->stat('\/')\n
#4 \/opt\/owncloud\/apps\/files_external\/lib\/smb.php(272): OC\\Files\\Storage\\SMB->getFileInfo('')\n
#5 \/opt\/owncloud\/lib\/private\/files\/storage\/common.php(90): OC\\Files\\Storage\\SMB->filetype('')\n
#6 \/opt\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(98): OC\\Files\\Storage\\Common->is_dir('')\n
#7 \/opt\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(98): OC\\Files\\Storage\\Wrapper\\Wrapper->is_dir('')\n
#8 \/opt\/owncloud\/lib\/private\/files\/cache\/watcher.php(90): OC\\Files\\Storage\\Wrapper\\Wrapper->is_dir('')\n
#9 \/opt\/owncloud\/lib\/private\/files\/view.php(1182): OC\\Files\\Cache\\Watcher->checkUpdate('', Array)\n
#10 \/opt\/owncloud\/lib\/private\/connector\/sabre\/objecttree.php(148): OC\\Files\\View->getFileInfo('Video')\n
#11 \/opt\/owncloud\/lib\/private\/connector\/sabre\/custompropertiesbackend.php(101): OC\\Connector\\Sabre\\ObjectTree->getNodeForPath('Video')\n
#12 \/opt\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/PropertyStorage\/Plugin.php(86): OC\\Connector\\Sabre\\CustomPropertiesBackend->propFind('Video', Object(Sabre\\DAV\\PropFind))\n
#13 [internal function]: Sabre\\DAV\\PropertyStorage\\Plugin->propFind(Object(Sabre\\DAV\\PropFind), Object(OC\\Connector\\Sabre\\Directory))\n
#14 \/opt\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n
#15 \/opt\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1016): Sabre\\Event\\EventEmitter->emit('propFind', Array)\n
#16 \/opt\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(936): Sabre\\DAV\\Server->getPropertiesByNode(Object(Sabre\\DAV\\PropFind), Object(OC\\Connector\\Sabre\\Directory))\n
#17 \/opt\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(327): Sabre\\DAV\\Server->getPropertiesForPath('', Array, 1)\n
#18 [internal function]: Sabre\\DAV\\CorePlugin->httpPropfind(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n
#19 \/opt\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n
#20 \/opt\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PROPFIND', Array)\n
#21 \/opt\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#22 \/opt\/owncloud\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n#23 \/opt\/owncloud\/remote.php(132): require_once('\/opt\/owncloud\/a...')\n#24 {main}","File":"\/opt\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Connection.php","Line":65} 
```

**Comment by PVince81** [comment]
> turned off a file server for maintenance 

Can you elaborate ? Did you remove the remove SMB server from the network and OC still tried to contact it ?

Might be related to https://github.com/owncloud/core/issues/11792

**Comment by PVince81** [comment]
@icewind1991 would be good if the SMB backend could throw StorageNotAvailableException when the connection failed

**Comment by lachlan-00** [comment]
Sorry, I mean I just physically turned off the samba sever and that broke the sync. I would think that any break in the samba connection would probably cause the same issue but would be short enough not to notice.

I only noticed because it was off while I was trying to sync files to a PC at the same time.

Hopefully there's an easy way to ignore missing network file systems without breaking the entire sync.

**Comment by Xenopathic** [comment]
@PVince81 The SMB library used by the backend is correct in throwing its own exceptions, but we need a translation layer (like convertException() in the DAV backend) that will convert the library exceptions to ones ownCloud can use, like StorageNotAvailableException. This doesn't just affect the SMB backend, but all storage backends.

**Comment by MorrisJobke** [comment]
@Xenopathic Any news here?

**Comment by Xenopathic** [comment]
As per my last comment, we need to translate exceptions from the storage libraries themselves into ones ownCloud can use, namely StorageNotAvailableException.

**Comment by PVince81** [comment]
I tried this on 9.0RC1 expecting it to work already but am getting the following 500 error when doing a PROPFIND on the unavailable smb (I shut down the SMB server):
```
{"reqId":"FyYLxp0gkunmHr11TsbI","remoteAddr":"127.0.0.1","app":"PHP","message":"Call to a member function getMessage() on null at \/srv\/www\/htdocs\/owncloud\/apps\/files_external\/lib\/failedstorage.php#202","level":3,"time":"2016-03-02T11:06:52+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/files\/smb"}
```

**Comment by PVince81** [comment]
Oh, that's bad. Some code paths initialize the class with "null" as exception.

I'll fix this...

**Comment by PVince81** [comment]
### Steps to reproduce:

1. Setup a SMB mount as "/smb", make sure it works
1. Navigate into "/smb", sync it, etc
1. Shut down the SMB server
1. Do a PROPFIND on "/smb"

### Expected result
503 "Storage not available" status

### Actual result
500 Internal server error

PR is here: https://github.com/owncloud/core/pull/22774

**Comment by PVince81** [comment]
Also happens on v8.2.2, getting 500 internal server error:
```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Icewind\SMB\Exception\ConnectionRefusedException</s:exception>
  <s:message>smb://localhost/shared/</s:message>
</d:error>
```

**Comment by PVince81** [comment]
Turns out this issue completely breaks syncing on stable9 and also v8.2.2.
This is because a PROPFIND on "/" will produce an error.

**Comment by PVince81** [comment]
Fixed through https://github.com/owncloud/core/pull/22816
