### ISSUE TITLE
LDAP Wizard Group Tab: infinite loop when having more than 400 groups

### ISSUE THREAD

**Issue by blizzz** [owncloud/core#18297]
### Steps to reproduce
1. Have an LDAP with ~~more than~~ a multiple of 400 groups
2. Configure everything accordingly (assisted mode) until group tab
3. Go group tab

### Expected behaviour
Object classes and groups are being loaded

### Actual behaviour
Object classes are loaded, but groups are stuck in a infinite group

Seen with master. It appears that this line https://github.com/owncloud/core/blob/master/apps/user_ldap/lib/wizard.php#L435 returns always the first 400 groups, no matter the offset.

**Comment by PVince81** [comment]
@blizzz any update ? Setting to sev-high, infinite loops aren't nice

**Comment by blizzz** [comment]
Actually happens with a group number which is a multiplier of 400. Stupid run condition.

**Comment by blizzz** [comment]
Fix ready for the reported issue is ready, but it uncovers an error with searching for groups with an offset. basically always returns the first set of group… still investigating.
