### ISSUE TITLE
jquery.strengthify requires tipsy

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#18308]
### Steps

1. Run ownCloud setup
1. Open the JS console
1. Type in a password

### Expected result
Tooltip appears with password strength check

### Actual result
No tooltip
JS error:
```
jquery.strengthify.js?v=d5f1d30960adba1ed9e421bc974d82c8:113 Uncaught TypeError: Cannot read property 'tipsy' of undefined
(anonymous function) @ jquery.strengthify.js?v=d5f1d30960adba1ed9e421bc974d82c8:113
x.event.dispatch @ jquery.min.js?v=d5f1d30960adba1ed9e421bc974d82c8:5
x.event.add.v.handle @ jquery.min.js?v=d5f1d30960adba1ed9e421bc974d82c8:5
```

### Versions
owncloud 8.2 pre-alpha git master 4e327d058c66b98b8ff357589f339e57400c7a63

@Henni @jancborchardt 

Maybe the tipsy to tooltip adapter isn't loaded properly on the login page ?

**Comment by Henni** [comment]
I would solve this by replacing the tipsys with tooltips in strengthify by @MorrisJobke.
But I will also take another look at the shim.

**Comment by PVince81** [comment]
Any update on this ?

**Comment by MorrisJobke** [comment]
> But I will also take another look at the shim.

Shim is the way to go. Because otherwise we would also break other apps. BUt there is already something like a shim in place. I think it only misses some option?! :confused:

**Comment by PVince81** [comment]
Any update ? How difficult is it to fix jquery.strengthify ? (I wasn't aware that this was our own plugin)
