### ISSUE TITLE
"Unknown filetype" popup when sharing to a group

### ISSUE THREAD

**Issue by eLvErDe** [owncloud/core#18304]
Hello,

I had this weird behavior so I had to dig into Owncloud code and figured out this was related to avatar.
So I patched the file throwing the exception like this:
```
--- avatar.php	2015-08-08 00:28:56.000000000 +0000
+++ avatar.php.debug	2015-08-14 07:50:31.831338184 +0000
@@ -13,6 +13,7 @@
 class OC_Avatar implements \OCP\IAvatar {
 
 	private $view;
+	private $userattr;
 
 	/**
 	 * constructor
@@ -20,6 +21,7 @@
 	*/
 	public function __construct ($user) {
 		$this->view = new \OC\Files\View('/'.$user);
+                $this->userattr = $user;
 	}
 
 	/**
@@ -63,7 +65,7 @@
 		}
 		if ($type !== 'jpg' && $type !== 'png') {
 			$l = \OC_L10N::get('lib');
-			throw new \Exception($l->t("Unknown filetype"));
+			throw new \Exception($l->t("Unknown filetype ".$this->userattr));
 		}
```

$type was containing "gif" and this small piece of patch allowed me to see which user was responsible for the error.

Turned out this user (LDAP backend) had uploaded a picture in the "jpegPhoto" field in GIF format. It worked properly in other softwares but not in OwnCloud.

Despite I understand "jpegPhoto" should probably always contains jpeg file, I think it's a bad behavior to have a single avatar issue on ONE user breaking filesharing for everyone (and no useful log for an administrator to fix the issue).

What's the idea behind throwing an exception here ? Why not trying and let it go if something goes wrong ?

Best regards, Adam.

**Comment by MorrisJobke** [comment]
cc @oparoz @blizzz

**Comment by oparoz** [comment]
I agree. I think logging the error would make more sense. Maybe the mimetype icon should be sent back to clearly show that there is a problem?

**Comment by eLvErDe** [comment]
Well it's even worse because at the first look I had absolutely no idea what "file" this was about. I though about a file being in the folder or something and was very surprised to find the log string into avatar related code ;-)
At least say it's about the avant, and display the username who's failing.

**Comment by MorrisJobke** [comment]
Can we use an `UnsupportedFiletypeException` here and properly handle this in the LDAP code?

**Comment by blizzz** [comment]
Avatar throws Exceptions and those are fetched meanwhile.
