### ISSUE TITLE
Add ownCloud file integrity checker to web updater and occ

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#18309]
When an upgrade times out or breaks, users will try again, until it works, sort of. They don't know which state their instance is in, but they assume it's fine, until something more serious happens.

**Maybe the installation should be checked at the end of the upgrade to make sure it contains all the files of the new release and only those files?**

Of course, advanced users will see warnings about additional debug files they might be using, but that might also remind them not to leave some of these lying around, in case they're old and contain vulnerabilities per example.

Non-tech people, oC's target market, will get useful feedback regarding their installation and will know that everything went according to plan.

@karlitschek @DeepDiver1975 @jancborchardt @LukasReschke @MorrisJobke @PVince81 @Raydiation @nickvergessen @schiesbn @Xenopathic @RealRancor 

#### Possible plan

* Ship file containing sha256 of each file
* Add scanner and comparator to occ
* Use methods implemented for occ in the web updater

**Comment by LukasReschke** [comment]
Generally speaking without going into technical details yet: Yes. Would make sense from my PoV.

**Comment by Raydiation** [comment]
Just added something similar in the news app, check the news:verify-install command. Don't we have an issue open for that specific thing already?

**Comment by oparoz** [comment]
> Don't we have an issue open for that specific thing already?

When I looked, I only found similar requirements for apps, but not for the core install

> check the news:verify-install command

Well done, this can probably be reused. It's not a proper security check unless that json file gets PGP signed, but it's a good tool to have imho.

**Comment by karlitschek** [comment]
Funny. Just yesterday I started to think about an integrity check feature for ownCloud 9. Additionally to signing apps we should also 'sign' ownCloud itself. Without the config folder, apps and themes or course. So we can check and guarantee the ownCloud is unchanged. This could increase the security, protect again update problems and also make sure that no one has applied 'interesting' patches to the core. We should have an option in config.php to switch it off or course but also show it in the admin page if differences are found.

**Comment by PVince81** [comment]
@VicDeo @LukasReschke is this done ? If yes, then close.

**Comment by oparoz** [comment]
Since #19036 has been closed and it seems to achieve the same thing, I'm closing this, yes :)
