### ISSUE TITLE
Error:A problem occurred configuring root project 'android-master'. > Cannot evaluate module owncloud-android-library : Configuration with name 'default' not found.

### ISSUE THREAD

**Issue by poonamvibhute** [owncloud/core#18301]
Error:A problem occurred configuring root project 'android-master'.
> Cannot evaluate module owncloud-android-library : Configuration with name 'default' not found.

**Comment by PVince81** [comment]
Please raise in https://github.com/owncloud/android-library or https://github.com/owncloud/android

**Comment by PVince81** [comment]
also please make sure to include details like how you checked out the code and which commands you run. Thanks!
