### ISSUE TITLE
Error occured while checking server setup

### ISSUE THREAD

**Issue by geekcomputing** [owncloud/core#18303]
Steps to reproduce:
Login to admin panel

Expected behaviour:
Check setup is successful

Actual behaviour:
The following error message is shown:
Error occurred while checking server setup
Please double check the installation guides ↗, and check for any errors or warnings in the log.

Operating system: 
CentOS 7

Web server: 
Apache 2.4.6 

Database:
 mysql

PHP version: 
5.4.16

OwnCloud version: 
8.1.1

Updated from an older OwnCloud or fresh install:
Updated from OwnCloud 8.0.5.2

List of activated apps: 
default apps

We believe all my permissions are correct. We are not seeing any concerning errors in OwnCloud logs.

**Comment by PVince81** [comment]
@LukasReschke

**Comment by PVince81** [comment]
Do you see a red row in the network console in the web browser appearing after runnnig the check ?

**Comment by LukasReschke** [comment]
> Please double check the installation guides ↗, and check for any errors or warnings in the log.

Yeah. Also would be somewhat useful to check for errors and warnings in the log :speak_no_evil:

**Comment by geekcomputing** [comment]
This is all I receive under the Admin panel

Security & setup warnings

Error occurred while checking server setup

Please double check the installation guides ↗, and check for any errors or warnings in the log.

@LukasReschke 
I do not have any errors or warnings other then above.

**Comment by geekcomputing** [comment]
This is another error that is currently showing:

Error 	core 	Could not get application: cURL error 60: See http://curl.haxx.se/libcurl/c/libcurl-errors.html

**Comment by LukasReschke** [comment]
@geekcomputing What files are there in the config folder?

**Comment by geekcomputing** [comment]
@LukasReschke Below are the 3 files in the config directory:

ca-bundle.crt
config.php
.htaccess

**Comment by PVince81** [comment]
Is this still happening with 8.2.2 ?

**Comment by AndreaGiardini** [comment]
I have this error with Debian and nginx

**Comment by PVince81** [comment]
Mind sharing more details ?

See issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by AndreaGiardini** [comment]
### Expected behaviour
When i open the admin panel it should show me the warning is the `Security & setup warnings` section

### Actual behaviour
It doesn't... only thing it shows it's `Error occurred while checking server setup`

### Server configuration
**Operating system**:
Debian 8

**Web server:**
nginx 1.6.2

**Database:**
mysql  Ver 14.14 Distrib 5.5.47

**PHP version:**
PHP 5.6.17-0+deb8u1

**ownCloud version:** (see ownCloud admin page)
8.2.2

**Updated from an older ownCloud or fresh install:**
fresh install

**Where did you install ownCloud from:**
downloaded from official website

**List of activated apps:**

```
Enabled:
  - activity: 2.1.3
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - updater: 0.6
Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\Memcached",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "my.domain.com"
        ],
        "datadirectory": "\/var\/www\/my.domain.com\/data",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "owncloud_db",
        "dbhost": "localhost",
        "dbtableprefix": "",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "instanceid": "ockg4l7mbny2"
    }
}

```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Logs
#### Web server error log
```
 [03/Mar/2016:08:36:01 -0500] "GET /index.php/settings/admin HTTP/1.1" 200 32511 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0 Iceweasel/38.6.1"
 [03/Mar/2016:08:36:01 -0500] "GET /index.php/core/js/oc.js?v=a4f7ba2560e2f2aec99aec81ff08ac05 HTTP/1.1" 200 2142 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0 Iceweasel/38.6.1"
 [03/Mar/2016:08:36:02 -0500] "GET /cron.php HTTP/1.1" 200 31 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0 Iceweasel/38.6.1"
[03/Mar/2016:08:36:02 -0500] "GET /index.php/heartbeat HTTP/1.1" 200 5 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0 Iceweasel/38.6.1"
[03/Mar/2016:08:36:02 -0500] "PROPFIND /remote.php/webdav HTTP/1.1" 207 5423 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0 Iceweasel/38.6.1"
[03/Mar/2016:08:36:02 -0500] "GET /index.php/avatar/Giardo/128 HTTP/1.1" 200 33 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0 Iceweasel/38.6.1"
[03/Mar/2016:08:36:02 -0500] "GET /index.php/apps/notifications HTTP/1.1" 204 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0 Iceweasel/38.6.1"
[03/Mar/2016:08:36:02 -0500] "GET /index.php/apps/updater/backup/index HTTP/1.1" 200 30 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0 Iceweasel/38.6.1"
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"+f3Oh0vp5VDOqUkDCoNb","remoteAddr":"151.42.52.175","app":"PHP","message":"Array to string conversion at \/var\/www\/my.domain.com\/www\/lib\/private\/template\/functions.php#36","level":3,"time":"2016-03-03T13:44:21+00:00"}
{"reqId":"N2csFlJEFgizEaFfsmDL","remoteAddr":"151.42.52.175","app":"PHP","message":"Array to string conversion at \/var\/www\/my.domain.com\/www\/lib\/private\/template\/functions.php#36","level":3,"time":"2016-03-03T13:44:49+00:00"}
```

#### Browser log
```
shows an error in https://cloud.ifndef.it/index.php/settings/ajax/checksetup
```

**Comment by AndreaGiardini** [comment]
https://trac.nginx.org/nginx/ticket/235

The error was due to this bug... adding:

```
ssl_session_cache    shared:SSL:10m;
```

to /etc/nginx/nginx.conf solved the issue
