### ISSUE TITLE
Upgrade from 8.1.0 to 8.1.1

### ISSUE THREAD

**Issue by blackcoder** [owncloud/core#18314]
Once again, another upgrade and another nightmare ! 
Upgrade went well, it asked me to do an ```php occ encryption:migrate``` which I did, and now I have a lot of my files with size zero and inaccessible. 
This is horrible, I've been using owncloud since version 1, it had it's share of instability every now and then, but recently it's getting out of hand, isn't there some sort of quality control ? 

I really regret upgrading, and I am seriously contemplating ditching owncloud all together due to these stupid issues. 

Any  idea why this might have happened? and how can I restore my files ?

**Comment by tflidd** [comment]
> This is horrible, I've been using owncloud since version 1, it had it's share of instability every now and then, but recently it's getting out of hand, isn't there some sort of quality control ?

The community does testing. Probably not enough. I sometimes do test a little bit before I update. That's the best way to make sure that there won't be too much bad surprises. And I keep a backup that allows me to go back to the previous version.

**Comment by LukasReschke** [comment]
While I do understand your frustration please follow our guidelines for submitting bugs as described here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

We need some more information to properly support you with your issue.

**Comment by DeepDiver1975** [comment]
> isn't there some sort of quality control ?

No - we are perfect and never do mistakes - as a result we have no need to test.

**Comment by karlitschek** [comment]
@DeepDiver1975 Why was this closed? I assume that there is still a bug somewhere?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 Why was this closed? I assume that there is still a bug somewhere?

general rule of thumb: incomplete bug report are being closed until all required information is supplied
