### ISSUE TITLE
Clicking on a thumbnail should bring the large preview (slideshow)

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#18311]
So, I was testing the new UI and ran into several issues. One of which is the action which is selected based on where we click.

If I click on the filename, then I get a preview... strange.
Now if I click on the thumbnail, I select that row and get the right-sidebar...even stranger!

Switching things around would work nicely for images, but are there other cases to consider?

@jancborchardt

**Comment by PVince81** [comment]
Also see interaction problems: https://github.com/owncloud/core/issues/18238

**Comment by jancborchardt** [comment]
I would say clicking on the filename as well as the thumbnail should open the file.

Dropbox for example triggers the select action on clicking the empty space in the row (what we currently use for triggering the sidebar).

Maybe with the »Details« action in the file actions dropdown and the fact that the sidebar is also triggered by clicking Share and Versions, we can get rid of the sidebar trigger by whitespace click, and use that for selection instead?

@PVince81 @owncloud/designers what do you think?

**Comment by PVince81** [comment]
Try out https://github.com/owncloud/core/pull/18273

But you still need to click on the white space.
@jancborchardt do you mean merging the "sidebar highlight" with the "selection highlight" ?

Basically clicking on the thumbnail currently selects the file (checkbox)

**Comment by jancborchardt** [comment]
@PVince81 I’m suggesting this:

* clicking thumbnail or name opens the detail view, or the file (currently only on clicking the name)
* clicking the whitespace around the file selects the row, and does _not_ open the sidebar (currently opens the sidebar) – then we either 1) get rid of the checkboxes and use just the highlight style for checking (like Dropbox) or 2) use it as it is, with the ability to uncheck (but not check) via the checkbox over the thumbnail or 3) introduce a new column for the checkboxes (which I would not recommend at all)
* clicking on »Details«, »Share« and »Versions« in the actions dropdown opens the sidebar

**Comment by MorrisJobke** [comment]
> 2) use it as it is, with the ability to uncheck (but not check) via the checkbox over the thumbnail

That is super weird. I really like to be able to click everything around the checkbox (thumbnail) to select a row. Clicking the row(including name) opens the file and only clicking the action opens the sidebar. So basically as it was before introducing the sidebar.

**Comment by oparoz** [comment]
Maybe it's time to introduce double-click actions :)

**Comment by oparoz** [comment]
Maybe it's time to introduce double-click actions :)

* One click, selects
* Double on thumb -> slideshow
* Double on name -> edit
* Double anywhere -> right-sidebar

**Comment by PVince81** [comment]
@oparoz what about mobile ? Long press instead of double click ?

I'm not aware of any web app out there that uses double click for anything. Might not be the best approach.

**Comment by MorrisJobke** [comment]
No. Please no double click. And no fancy new ways to interact with stuff. You never have two ways of interact with a thing (inside owncloud) -> Click on it -> do the action (slideshow for images, editor for text,...) Nothing more.

**Comment by oparoz** [comment]
I agree. 

* One click on the thumbnail = default action

The selector issue is a tough one. I'm not really in favour of 3), but it's the less confusing option. 1) could work, but where would the global checker/unchecker be placed?

**Comment by jancborchardt** [comment]
> Maybe it's time to introduce double-click actions :)

No. Double-click as well as right-click are very hard to discover and we should never use them anywhere. They are old desktop paradigms which are very confusing (I know a lot of older folks double-clicking on links for example…) and need to be phased out.

**Comment by oparoz** [comment]
Don't forget this. The way it currently works makes it difficult to select multiple files.

**Comment by jancborchardt** [comment]
Well, now it’s pretty much like before. Selecting files does not open the sidebar.

Any other improvements like selecting vs opening detail view on clicking the filetype icon / thumbnail will have to be deferred to 9.0

**Comment by oparoz** [comment]
OK, but let's not forget about it. It's really awkward to not be able to drag and drop by clicking on the row.

**Comment by jancborchardt** [comment]
@oparoz I can drag & drop just fine either by dragging on the filename or the empty space of the row. What do you mean exactly?

**Comment by oparoz** [comment]
Just checked with a rebased version and it works properly.

**Comment by cmonteroluque** [comment]
@oparoz is this ready to close?

**Comment by oparoz** [comment]
I still find it strange that we have to click on the filename in order to be able to get the fullscreen preview and the behaviour is inconsistent since sometimes we end up in an editor and at other times in a viewer.

I feel the checkbox should be kept separate from the thumbnail in order to make it easier to differentiate between actions on mobile
