### ISSUE TITLE
OCS routes should be unique

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#18319]
Currently we merge OCS responses since we can register the same route multiple times (we used to do this for the capabilities).

We  now that we have the capabilities manager (https://github.com/owncloud/core/pull/15093) in core. And all core apps are already migrated to this. As far as I know the multiple routes (and thus the merging of responses) was only for the capabilities.

Since we now allow header in OCS responses (https://github.com/owncloud/core/pull/18118 and https://github.com/owncloud/core/pull/18184) we should really rethink allowing the same route to be registered multiple times. Since the merging of headers is even less trivial than merging responses.

Merging of responses is a bit fishy as it might not yield the desired result. And this can happen undetected since 2 apps can behave totally according to specs but if they register the same route there is no guarantee their merged output is also what you want.

The way I see it we have a few options.

1. Leave everything as it is
2. Require unique routes and force all apps to use the capabilties manager (I don't know if 3rdparty apps use it anyway?)
3. Require unique routes for everything except the capabilities for some time, to allow migration time to the capabilities manager.

The main advantage I see here is that it could simplify the OCS code significantly. 

And as a bonus maybe make migration to the appframework for OCS stuff simpler (#16684 and #15894).

Comments?
@DeepDiver1975 @Raydiation @LukasReschke @karlitschek and others I forgot.

**Comment by PVince81** [comment]
@DeepDiver1975 obsoleted by the OCS to app framework bridging ?

**Comment by DeepDiver1975** [comment]
Afaik yes
