### ISSUE TITLE
[Feature request] Federated cloud share self signed certificate notification

### ISSUE THREAD

**Issue by madpipeline** [owncloud/core#18328]
I have 2 OC servers. The first one uses a self signed certificate.

Sharing a folder via federated cloud with the second one bring in a notification on the second one asking to accept the share. After the share is accepted, nothing. Nothing happens.

I've checked the logs and it seems that the self signed certificate is stopping the share form being added.

A notification when this occurs with a link to the documentation where it shows how to add custom SSL certificates would be very informative. Compared with nothing.

**Comment by oparoz** [comment]
@LukasReschke @jancborchardt

**Comment by LukasReschke** [comment]
ACK - to quote myself from https://github.com/owncloud/enterprise/issues/696#issuecomment-125252768:

> A personal certificate bundle will only lead to problems when we come to functionalities such as file scanning. As in: Which bundle shall get used when commands get invoked from the CLI? The area of potential issues continues endlessly here. We stumbled upon even grave problems in owncloud/core#14913 for example.

> I'm not denying that this feature makes sense. I'm just stating that it is confusing as hell and documentation does not help further.

> The thing here is having a per-user certificate store which is valid for all requests an ownCloud instance does is just questionable if you're an enterprise. As an admin you simply do not want that an user can control certificates themselves that way. Which makes very much sense since this could lead to some kind of privilege escalation. And parsing certificates is also something you really don't want to do if you don't have to.

> So let's think about the problem more. What makes sense is having a certificate store on a mountpoint base. This way also file scanning and Co. would be much easier. – And we would not need to have these hacks that we have for the personal bundle creation.

> …

> Basically something like:

> - Users specify external mountpoint
> - SSL error gets detected when trying to connect
> - User gets option to trust the certificate via popup

**Comment by oparoz** [comment]
> SSL error gets detected when trying to connect
User gets option to trust the certificate via popup

Yes, please

**Comment by jancborchardt** [comment]
So, what to do here @LukasReschke @schiesbn?

**Comment by LukasReschke** [comment]
> So, what to do here @LukasReschke @schiesbn?

Waiting for somebody to implement it :speak_no_evil:
