### ISSUE TITLE
8.1.1 still cannot login using Chrome

### ISSUE THREAD

**Issue by keynet** [owncloud/core#18326]
I updated from 8.03 to 8.1, then 8.1.1. on SLES11/PHP 5.6.9 and since 8.03 the web login button is not working in Chrome on several platforms.
It works OK, in IE8, IE11, Firefox (current) on Win32, Safari on IOS, Chrome on IOS
It doesn't work for me on Chrome on Win32(XP) or Win64(win7) or Android 4.3
The login button just doesn't respond at all

I have a warning about The "X-Frame-Options" HTTP header is not configured to equal to "SAMEORIGIN". Hoverer an inspection of the config and actual headers shows it is present, not cure that's related.

**Comment by MorrisJobke** [comment]
@keynet Is there anything else listed in the webdeveloper console (F12)? Do you have any apps installed additionally in you ownCloud. Try to disable as many as possible non-official apps (step by step and retry to login would be nice).

You can disable an app with the ownCloud command line tool: https://doc.owncloud.org/server/8.0/admin_manual/configuration_server/occ_command.html#apps-commands

**Comment by keynet** [comment]
No - nothing except Chrome reports cookies are disabled (3rd party).  If I re-enable them, it makes no difference.
I have no 3rd party apps in Owncloud at all.
It's not that nothing happens when I click login, but the login button appears to be completely disabled. It doesn't change colour when you hover over it for example, which suggests it's deliberately being disabled by some logic.
This happened immediately after the 8.03 update to 8.1

**Comment by MorrisJobke** [comment]
@keynet The disabling is there by intention. The problem seems to be that the redirect to the files app doesn't work. Can you have a look at the network tab in the webdev tools? It should show a new request after you clicked "Login". Can you provide the information about this request? (you can click on the request for more info)

**Comment by keynet** [comment]
Not sure what you mean by "network tab in webdav tools" Please explain some more?
Thanks

**Comment by MorrisJobke** [comment]
![bildschirmfoto von 2015-08-16 14-43-56](https://cloud.githubusercontent.com/assets/245432/9293307/44d78242-4426-11e5-9026-f28717aae70d.png)

1 - network tab
2 - click on the request
3 - see the request/response headers (maybe also provide data of the response tab)

Best would be a screenshot like the above.

**Comment by keynet** [comment]
![untitled1](https://cloud.githubusercontent.com/assets/5302023/9293392/b38e2272-4421-11e5-9b5a-484623fc25c5.jpg)

Is it maybe the MIME type problem? - I noticed a bunch of errors

**Comment by MorrisJobke** [comment]
Weird looks like your webserver provides this with a broken mimetype. It should be `application/javascript` for all the `.js` files.

What webserver are you using?

**Comment by MorrisJobke** [comment]
Maybe try somethin like http://stackoverflow.com/a/1990668 first (if you're using apache). If this fixes the issue your webserver is missing some mimetype info.

**Comment by keynet** [comment]
I'm not an expert on this, but it's running on Stock Apache 2.2.12 / SLES11, and the mime types are from the distribution mime.types file - unchanged. 
There are several other vhosts on this machine, they all work OK, as did Owncloud until 8.1
Is text-js right for an executable script?  Should it be application/javascript ?

**Comment by MorrisJobke** [comment]
> Is text-js right for an executable script? Should it be application/javascript ?

cc @LukasReschke

**Comment by LukasReschke** [comment]
> Is text-js right for an executable script? 

No. That's a terrible wrong mimetype and the reason why we nowadays have an insecure web due to mimetype sniffing ;-)

Generally speaking: Since a lot of admins set the wrong mimetype on JS files such as "plain/text" web browsers are now accepting everything as executable file. We enable strict mimetype checking which tells browsers not to interpret such files for security reasons.

> I'm not an expert on this, but it's running on Stock Apache 2.2.12 / SLES11, and the mime types are from the distribution mime.types file - unchanged. 

Then you know where to complain to.  Please use `application/javascript` as per RFC 4329.

**Comment by keynet** [comment]
For the benefit of others, here's a more helpful suggestion:
It appears that the distribution's mime.types contains multiple entries for .js, and outdated.
Apache's current one can be found here
http://svn.apache.org/viewvc/httpd/httpd/trunk/docs/conf/mime.types
