### ISSUE TITLE
Encryption: Segmentation Fault on migration of large user

### ISSUE THREAD

**Issue by theCalcaholic** [owncloud/core#18323]
I'm trying to upgrade from 8.0 to 8.1.1. I'm using encryption and all users are on local storage. Every time I try to migrate the keys of the users who occupies most of the disk space (about 200GB) I ran into a segmentation fault after about 50h.
I'm invoking the migration with the command "occ encryption:migration <username>".
How could I possibly debug this and what are possible sources of the problem?

I appreciate your time.

EDIT: The same issue occured with the attempt to upgrade to 8.1.0 after having applied all fixes. Before every attempt I reverted all migration backups.

**Comment by karlitschek** [comment]
Please post a full bug report using the issue template.
But if you see a 'segmentation fault' then this is definitelt not the fault of owncloud. this means that the php/apache process has crashed which can't be triggered from inside a php script.
there is probably a problem with your hardware/distribution or php packages.
