### ISSUE TITLE
Web front-end extremely slow, PROPFIND takes minutes

### ISSUE THREAD

**Issue by thomsmits** [owncloud/core#18325]
### Expected behaviour

PROPFIND should return in seconds not minutes. Application should be usable.

### Actual behaviour

  * PROPFIND takes minutes.
  * Apache servers run at very high load
  * Web frontend and sync client are not working with usable performance

### Server configuration

**Operating system**: Ubuntu 14.04.3 LTS

**Web server:** Apache/2.4.7 (Ubuntu)

**Database:** mysqld 5.5.44

**PHP version:** PHP 5.5.9

**ownCloud version:** 8.1.1

**Updated from an older ownCloud or fresh install:** Updated

**List of activated apps:**

````
Enabled:
 - calendar: 0.7.2
 - contacts: 0.4.0.0
 - files: 1.1.10
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - gallery: 0.6.0
Disabled:
 - activity
 - appframework
 - encryption
 - external
 - files_external
 - files_locking
 - files_videoviewer
 - firstrunwizard
 - news
 - provisioning_api
 - shorty
 - templateeditor
 - user_external
 - user_ldap
 - user_webdavauth
```

**The content of config/config.php:**

    $CONFIG = array (
      'instanceid' => 'ID',
      'passwordsalt' => 'SALT',
      'datadirectory' => '/var/www/owncloud/data',
      'dbtype' => 'mysql',
      'version' => '8.1.1.3',
      'dbname' => 'ownCloud',
      'dbhost' => '127.0.0.1',
      'dbtableprefix' => 'oc_',
      'dbuser' => 'USER',
      'dbpassword' => 'SECRET',
      'installed' => true,
      'forcessl' => true,
      'maintenance' => false,
      'ldapIgnoreNamingRules' => false,
      'theme' => '',
      'trusted_domains' =>
      array (
        0 => 'OUR_DOMAIN',
      ),
      'loglevel' => 0,
      'log_rotate_size' => 52428800,
      'log_rotate_sizerotation' => 209715200,
      'logtimezone' => 'Europe/Berlin',
      'secret' => 'SECRET',
      'memcache.local' => '\\OC\\Memcache\\APCu',
      'mail_from_address' => 'ADMIN',
      'mail_smtpmode' => 'php',
      'mail_domain' => 'DOMAIN',
    );

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration

**Browser:** Opera, Chrome, Safari

**Operating system:** Mac OS and Windows

# Description of the problem

We are running a small OwnCloud installation with 25 GB of data and 90,000 files. One user (lets say A) is sharing a folder with 1.5 GB of data and 5000 files with two other users (users B and C). Additionally he shares a second folder with 133 MB and 120 files with B and C and several other users.

We are now experiencing the following problems:

  * Access to the Web front-end for B and C is very slow (login and other actions take minutes)
  * Apache processes on the server are running with high load (100%) for minutes
  * File sync with the OwnCloud client is slow, especially when the client starts up and discovers files and folders

Users without access to the shared folder do not experience the problems and everything runs smoothly.

We did some profiling on the server and found that the PROPFIND method seems to be the cause of the problem. For the mentioned users, a PROPFIND call can take several minutes, with an average around 110 seconds. For users without the shared folders it returns in a second or less. Due to the fact that the sync client issues PROPFIND calls faster than the server can answer them, the server load is even more increased.

The network setup cannot be the issue because we executed a local PROPFIND call for the problematic users with curl and got the same results.

    curl --user B:secret -X PROPFIND -i http://localhost/remote.php/webdav/

I traced the file system calls of the Apache web server but there was no suspicious access to the file system during the PROPFIND call and high load situations. The Web server process is only performing a small number of read operations that return quickly.

My first thought was that the database may be part of the problem. Therefore, I traced the issued SQL statements and found one that returns a lot of rows (in the 10,000 range).

```sql
SELECT `oc_share`.`id`, `item_type`, `item_source`, `item_target`,`oc_share`.`parent`, 
       `share_type`, `share_with`, `uid_owner`,`file_source`, `path`, `file_target`, 
       `oc_share`.`permissions`,`stime`, `expiration`, `token`, `storage`, 
       `mail_send`,`oc_storages`.`id` AS `storage_id`, `oc_filecache`.`parent` as `file_parent` 
    FROM `oc_share` 
        INNER JOIN `oc_filecache` ON `file_source` = `oc_filecache`.`fileid`  
              AND `file_target` IS NOT NULL 
        INNER JOIN `oc_storages` ON `numeric_id` = `oc_filecache`.`storage`  
              AND ((`share_type` in ('0', '2') AND `share_with` = 'B')  
              OR (`share_type` = '1' AND `share_with` IN ('GROUP_1','GROUP_2','GROUP_3','admin')) ) 
              AND `uid_owner` != 'B' ORDER BY `oc_share`.`id` ASC 
```

The table `oc_share` contains 72,000 records, the table `oc_filecache` 100,000 records.

The problem is not the execution time of the statement on the database which was around 120 ms.

So my suspicion is that somewhere in the PHP code, the result of the database call is handled in a manner that does not scale linearly with the returned data and this will cause the delays. Unfortunately I was not able to find the code that does the handling of the PROPFIND call. Another tought was that PROPFIND does a recursive scan with infinite depth (`lib/private/connector/sabre/server.php` contains the line `$this->enablePropfindDepthInfinity = true;` but changing this to `false` does not help.)

Best regards,

  Thomas

**Comment by oparoz** [comment]
@thomsmits - From which ownCloud version did you upgrade from?

**Comment by thomsmits** [comment]
@oparoz - The server has a long history. We started 2013 with version 4.5 of OwnCloud and regularly updated it. The last update was - as far as I can remember - from 8.0.x. Unfortunately, I do not know the exact version before the recent update.

**Comment by LukasReschke** [comment]
> So my suspicion is that somewhere in the PHP code, the result of the database call is handled in a manner that does not scale linearly with the returned data and this will cause the delays. Unfortunately I was not able to find the code that does the handling of the PROPFIND call. Another tought was that PROPFIND does a recursive scan with infinite depth (lib/private/connector/sabre/server.php contains the line $this->enablePropfindDepthInfinity = true; but changing this to false does not help.)

Any chance to install Blackfire and do a trace? - https://blackfire.io/

**Comment by oparoz** [comment]
@thomsmits - Thanks. I was thinking it could be related to the generation of thumbnails, but that should only happen if going from 7 to 8.1.

**Comment by thomsmits** [comment]
@LukasReschke I installed blackfire and created two traces:

1. for a user with shared folder and very slow PROPFIND:
https://www.dropbox.com/s/v52rd5kgsj0hv1s/user_with_shared_folder.zip?dl=1

2. for a user without a shared folder and a fast PROPFIND
https://www.dropbox.com/s/z47dpcwjrm8tcib/user_without_shared_folder.zip?dl=1

I hope that helps.

 If you need more information, let me know.

**Comment by PVince81** [comment]
The traces are not usable, any click redirects to the blackfire page.
Can you use blackfire's "share" feature and post a link ?

**Comment by PVince81** [comment]
The fact that the sharing query returns 10K entries is already suspicious, unless you have one user who is recipient for 10K different shares ?

**Comment by PVince81** [comment]
CC @schiesbn @rullzer

**Comment by thomsmits** [comment]
@PVince81 
I shared the profiles. The links are:

1. for a user with shared folder and very slow PROPFIND:
https://blackfire.io/profiles/70e9bd3a-3c76-405f-86ea-7888d7289757/graph

1. for a user without a shared folder and a fast PROPFIND
https://blackfire.io/profiles/01c6b1a1-2ead-4e21-8f43-3e9270dda5d9/graph

**Comment by LukasReschke** [comment]
Awesome. That will help us! :rocket:

**Comment by rullzer** [comment]
So you should not have that many entries in your sharing table. It should be 1 share is 1 entry in the table. So I do not get where that huge number is coming from.

I am for simplicity assuming that both folder are distinct (e.g. folder 1 is not subfolder of folder 2 or vice versa). Is this correct?

Could you post the output of ```SELECT * FROM oc_share``` somewhere?

**Comment by PVince81** [comment]
@rullzer please note that in the case of group shares, there are sub-entries per shares.
In the Blackfire result I see that `groupItems` is at the bottom, maybe related.

Maybe one of the group contains 10k users ?

**Comment by rullzer** [comment]
So groupItems is a nasty function since it has ```N*N``` complexity. Which means that if your db result is around 10K then you do that inner loop max 100M times. Which still takes a significant amount of time especially since we do string comparison inside..

**Comment by rullzer** [comment]
> @rullzer please note that in the case of group shares, there are sub-entries per shares.

Didn't we (at least partially) get rid of that?
But since the machine is upgraded many times this might very well be the case.

**Comment by rullzer** [comment]
@thomsmits could you as a test modify https://github.com/owncloud/core/blob/master/lib/private/share/share.php#L1905

And put a ```return $items;``` there and see if it is then works acceptable?

**Comment by thomsmits** [comment]
@rullzer Here are the first 1000 lines of oc_shares. The table in total contains around 80,000 entries

https://www.dropbox.com/s/6fkq4smjtpdx253/oc_shares_first_1000_rows.txt?dl=1

**Comment by thomsmits** [comment]
@rullzer I changed the code of `lib/private/shares/share.php` from

```php
protected static function groupItems($items, $itemType) {

    $fileSharing = ($itemType === 'file' || $itemType === 'folder') ? true : false;

    $result = array();
````

to

```php
protected static function groupItems($items, $itemType) {

    $fileSharing = ($itemType === 'file' || $itemType === 'folder') ? true : false;
    return $items;
    $result = array();
```

The change reduced the time for the PROPFIND call from 2 minutes (1:54) to 7 seconds (0:07). 

Can I leave the change in place or does the loop, which is now skipped by the return, perform any important operation?

**Comment by thomsmits** [comment]
@PVince81 
> Maybe one of the group contains 10k users ?

We have only 50 users in the whole system (`oc_users` has 50 entries). Additionally, I can provide the following information about the size of the db tables (sorry for the image, but the MySQL-Tool does not allow textual export of this view).

![table-sizes](https://cloud.githubusercontent.com/assets/197846/9306773/9f7bbb62-44fa-11e5-8798-95621ebf85bf.png)

**Comment by rullzer** [comment]
@thomsmits well it could break sharing from the web. The grouping is actually used there. But let me think about it. Or a way to properly fix it.

**Comment by rullzer** [comment]
> @rullzer Here are the first 1000 lines of oc_shares. The table in total contains around 80,000 entries
>
> https://www.dropbox.com/s/6fkq4smjtpdx253/oc_shares_first_1000_rows.txt?dl=1

Jikes... that looks like your share is listed there multiple times... (start at sharid 145).. This should not happen.. Time to investigate more.

**Comment by rullzer** [comment]
@thomsmits mmm so there is something wrong. your file is 50k rows..

But sorting, filtering etc.

```cat  oc_shares_first_1000_rows.txt  | cut -d$'\t' -f 2- | sort | uniq | wc -l```

You have only 63 unique shares in that...
So something fishy is going on...

**Comment by thomsmits** [comment]
@rullzer Sorry, I thought I truncated the file. But it is an original database export - just with LIMIT 50000 instead of 1000. So what you see is what we have in the database.

**Comment by thomsmits** [comment]
@rullzer I was wondering, how all these entries came into the table the first place. Therefore, I looked at a database trace I created when investigating the issue the first time. I found several INSERT-statements that were executed during the PROPFIND call and that were blowing up the oc_shares table (user names removed):

```sql
INSERT INTO `oc_share` 
(`item_type`, `item_source`, `item_target`, `share_type`, `share_with`, `uid_owner`,
 `permissions`, `stime`, `file_source`, `file_target`, `token`, `parent`) 
VALUES ('folder','23018','/23018','2','xxxx','xxxx','1','1399466065','23018','/ProfI',NULL,'74')
````

The context of the insert call is (user_2 is experiencing the problem, user_3 is sharing the folder `ProfI` with user_1 und user_2 and the folder `Dekanat` with user_2):

```sql
SELECT * FROM oc_users WHERE LOWER(uid) = LOWER('user_1')
SELECT * FROM oc_preferences WHERE userid = 'user_1'
SELECT * WHERE id = 'local::/var/www/owncloud/data/user_1/'
SELECT * FROM oc_group_user WHERE uid = 'user_1'
SELECT * FROM oc_share INNER JOIN oc_filecache ON file_source = oc_filecache.fileid  AND file_target IS NOT NULL INNER JOIN oc_storages ON numeric_id = oc_filecache.storage  AND ((share_type in ('0', '2') AND share_with = 'user_1')  OR (share_type = '1' AND share_with IN ('FBI','Profi')) ) AND uid_owner != 'user_1' ORDER BY oc_share.id ASC

INSERT INTO oc_share (item_type, item_source, item_target, share_type, share_with, uid_owner, permissions, stime, file_source, file_target, token, parent) VALUES ('folder','23018','/23018','2','user_2','user_3','1','1399466065','23018','/ProfI',NULL,'74')

SELECT * FROM oc_share_external	WHERE user = 'user_2' AND accepted = '1'
SELECT * FROM oc_storages WHERE id = 'home::user_2'
SELECT * FROM oc_filecache WHERE storage = '50' AND path_hash = '45b963397aa40d4a0063e0d85e4fe7a1'
SELECT * FROM oc_mimetypes
SELECT * FROM oc_share INNER JOIN oc_filecache ON file_source = oc_filecache.fileid INNER JOIN oc_storages ON numeric_id = oc_filecache.storage  AND ((share_type in ('0', '2') AND share_with = 'user_2')  OR (share_type = '1' AND share_with IN ('Dekanat','FBI','Profi','admin')) ) AND uid_owner != 'user_2' AND file_target = '/ProfI' ORDER BY oc_share.id DESC LIMIT 3
SELECT * FROM oc_share WHERE id = '74' LIMIT 1
SELECT * FROM oc_storages WHERE numeric_id = '13'
SELECT * FROM oc_storages WHERE id = 'home::user_3'
SELECT * FROM oc_filecache WHERE storage = '13' AND path_hash = '246ad0a78f4d5dacd830a9e811d37beb'
SELECT * FROM oc_share INNER JOIN oc_filecache ON file_source = oc_filecache.fileid INNER JOIN oc_storages ON numeric_id = oc_filecache.storage  AND ((share_type in ('0', '2') AND share_with = 'user_2')  OR (share_type = '1' AND share_with IN ('Dekanat','FBI','Profi','admin')) ) AND uid_owner != 'user_2' AND file_target = '/ProfI' ORDER BY oc_share.id DESC LIMIT 3
SELECT * FROM oc_share WHERE id = '74' LIMIT 1
SELECT * FROM oc_share INNER JOIN oc_filecache ON file_source = oc_filecache.fileid INNER JOIN oc_storages ON numeric_id = oc_filecache.storage  AND ((share_type in ('0', '2') AND share_with = 'user_2')  OR (share_type = '1' AND share_with IN ('Dekanat','FBI','Profi','admin')) ) AND uid_owner != 'user_2' AND file_target = '/Dekanat' ORDER BY oc_share.id DESC LIMIT 3
SELECT * FROM oc_share WHERE id = '49' LIMIT 1
SELECT * WHERE numeric_id = '13'
SELECT * FROM oc_filecache WHERE storage = '13' AND path_hash = '8eb3db8557d95b035f6250da4c1a6b1b'
SELECT * FROM oc_share INNER JOIN oc_filecache ON file_source = oc_filecache.fileid INNER JOIN oc_storages ON numeric_id = oc_filecache.storage  AND ((share_type in ('0', '2') AND share_with = 'user_2')  OR (share_type = '1' AND share_with IN ('Dekanat','FBI','Profi','admin')) ) AND uid_owner != 'user_2' AND file_target = '/Dekanat' ORDER BY oc_share.id DESC LIMIT 3
SELECT parent, uid_owner FROM oc_share WHERE id = '49' LIMIT 1
```

I removed the column names for readability and replaced them with `*`.

So OwnCloud seems to be writing the problematic entries itself.

**Comment by rullzer** [comment]
@thomsmits thanks for the detailed info. I'm trying to figure out why (and where in the code) that insert statement is done. unfortunately blackfire does not provide me with that info.

@schiesbn any idea how or why this might happen?

**Comment by rullzer** [comment]
Somebody with some more blackfire experince should help me out. The number I see for the calls do not add up for me. 

E.g.

OC\Share\Share::getItems has a call count of 30

But I can't seem to find where it comes from (30). Since OC\Share\Share::getItemsSharedWith is called only 4 times. etc.

**Comment by PVince81** [comment]
@rullzer I think when a group share is involved, there is some code that will "expand" the group by inserting subitems for each member. This is to make it possible for the members to rename the target folder or opt out of the share. This might happen at the time where the share mount point is mounted for the recipient, which would explain why it happens on PROPFIND.

However, the strange thing is that it would do the INSERT every time instead of just once.
Maybe there's a bug in the code that tries and detect whether such entry still exists ?

**Comment by rullzer** [comment]
Ah this is 8.1.1 and not master. The bug hunting continues then.

In any case we should probably come up with a repair command. Since possibly more people have this issue.

**Comment by rullzer** [comment]
@thomsmits could you add some debug stuff to:

https://github.com/owncloud/core/blob/master/lib/private/share/share.php#L959

and

https://github.com/owncloud/core/blob/master/apps/files_sharing/lib/sharedmount.php#L103

So we know which one gets executed.

**Comment by thomsmits** [comment]
@rullzer In my code base the line numbers are different; for `share.php`, it is 946. This may be because you are on master and I'm on 8.1.1. 

Nevertheless, the result is that the INSERT statement for `apps/files_sharing/lib/sharedmount.php` is triggered and not the one in `share.php`. So it **sharedmount.php** is guilty for polluting the database.

I wrote the arguments of the INSERT statement to a file and got the following results:

  * I can see exactly one insert for one PROPFIND.
  * All inserts are for the same share (`/ProfI`). Although, we have at least two shares for the user (`Dekanat` and `ProfI`) sending the PROPFIND request, it is only one (`ProfI`) that triggers inserts.
  * I added a new user to the group with access to the `/ProfI` share and then remove him again, but the inserts still happen when he does a PROPFIND. So as soon as a user once had access to the share, his PROPFINDs will pollute the database.

So it looks to me as there is something wrong with this specific share and/or the group behind it. Nevertheless, the inserts should not happen.

**Comment by thomsmits** [comment]
@rullzer On addition to the database actions of OwnCloud: When I clear the `oc_share` table from all entries of the problematic share, with the following requests OwnCloud writes

  * One entry with `permissions` 1
  * One entry with `permissions` 31
  * One entry with `permissions` 1
  * One entry with `permissions` 31
  * And then all following (thousands) entries have `permissions` 1

The last `permissions` 31 entry has a `stime` different from all other entries.

I don't know if this hints to anything but maybe it is important.

**Comment by abika** [comment]
any news here? The server is totally unusable, very frustrating.

oc_share:
```
id|share_with|parent|item_type|item_source|item_target|file_source|file_target|expiration|token|uid_owner|share_type|permissions|stime|accepted|mail_send
1|||file|62|/62|62|/My_Calendar.ics||e5b05be1b8acd4345ed1cb772e2c6ae7|testuser|3|1|1401969268|0|0
5|alle||addressbook|3|Kontakte(verteilt)|||||verteilt|1|31|1402402494|0|0
19|alle||file|443|/443|443|/Shared/Kalender_von_Jasm.ics|||jasmin|1|17|1402413285|0|0
20|alle||file|452|/452|452|/Shared/Kalender_von_Linda.ics|||linda|1|17|1402414655|0|0
27|alle||file|514|/514|514|/Shared/icloud_addressen.txt.txt|||verteilt|1|17|1402665144|0|0
28|alle||folder|561|/561|561|/Shared/StatE_Team|||julia|1|31|1403075714|0|0
29|GF||folder|659|/659|659|/Shared/StatE_GF|||julia|1|31|1403076296|0|0
42|alle||file|17125|/17125|17125|/Kalender_von_Rox.ics|||roxana|1|17|1415904468|0|0
44|||file|17125|/17125|17125|/Kalender_von_Rox.ics||34a23a98348dbd7ac7de73d7b0bfcde4|roxana|3|1|1415907439|0|0
52|alle||file|18329|/18329|18329|/Kalender_von_Isabel.ics|||isabel|1|17|1417791939|0|0
53|alle||file|18395|/18395|18395|/Kalender_von_Anj.ics|||anja|1|17|1417800288|0|0
54|roxana|19|file|443|/443|443|/Kalender_von_Jasm.ics|||jasmin|2|17|1402413285|0|0
55|roxana|20|file|452|/452|452|/Kalender_von_Linda.ics|||linda|2|17|1402414655|0|0
57|roxana|28|folder|561|/561|561|/StatE_Team|||julia|2|31|1403075714|0|0
58|nic|19|file|443|/443|443|/Kalender_von_Jasm.ics|||jasmin|2|17|1402413285|0|0
59|nic|20|file|452|/452|452|/Kalender_von_Linda.ics|||linda|2|17|1402414655|0|0
61|nic|28|folder|561|/561|561|/StatE_Team|||julia|2|31|1403075714|0|0
62|nic|19|file|443|/443|443|/Kalender_von_Jasm.ics|||jasmin|2|17|1402413285|0|0
63|nic|20|file|452|/452|452|/Kalender_von_Linda.ics|||linda|2|17|1402414655|0|0
65|nic|28|folder|561|/561|561|/StatE_Team|||julia|2|31|1403075714|0|0
66|nic|19|file|443|/443|443|/Kalender_von_Jasm.ics|||jasmin|2|17|1402413285|0|0
67|nic|20|file|452|/452|452|/Kalender_von_Linda.ics|||linda|2|17|1402414655|0|0
69|nic|28|folder|561|/561|561|/StatE_Team|||julia|2|31|1403075714|0|0
70|nic|19|file|443|/443|443|/Kalender_von_Jasm.ics|||jasmin|2|17|1402413285|0|0
71|nic|20|file|452|/452|452|/Kalender_von_Linda.ics|||linda|2|17|1402414655|0|0
73|nic|28|folder|561|/561|561|/StatE_Team|||julia|2|31|1403075714|0|0
74|nic|19|file|443|/443|443|/Kalender_von_Jasm.ics|||jasmin|2|17|1402413285|0|0
75|nic|20|file|452|/452|452|/Kalender_von_Linda.ics|||linda|2|17|1402414655|0|0
77|nic|28|folder|561|/561|561|/StatE_Team|||julia|2|31|1403075714|0|0
78|nic|19|file|443|/443|443|/Kalender_von_Jasm.ics|||jasmin|2|17|1402413285|0|0
79|nic|20|file|452|/452|452|/Kalender_von_Linda.ics|||linda|2|17|1402414655|0|0
81|nic|28|folder|561|/561|561|/StatE_Team|||julia|2|31|1403075714|0|0
82|nic|19|file|443|/443|443|/Kalender_von_Jasm.ics|||jasmin|2|17|1402413285|0|0
83|nic|20|file|452|/452|452|/Kalender_von_Linda.ics|||linda|2|17|1402414655|0|0
85|nic|28|folder|561|/561|561|/StatE_Team|||julia|2|31|1403075714|0|0
86|nic|19|file|443|/443|443|/Kalender_von_Jasm.ics|||jasmin|2|17|1402413285|0|0
87|nic|20|file|452|/452|452|/Kalender_von_Linda.ics|||linda|2|17|1402414655|0|0
89|nic|28|folder|561|/561|561|/StatE_Team|||julia|2|31|1403075714|0|0
90|nic|19|file|443|/443|443|/Kalender_von_Jasm.ics|||jasmin|2|17|1402413285|0|0
91|nic|20|file|452|/452|452|/Kalender_von_Linda.ics|||linda|2|17|1402414655|0|0
93|nic|28|folder|561|/561|561|/StatE_Team|||julia|2|31|1403075714|0|0
94|nic|19|file|443|/443|443|/Kalender_von_Jasm.ics|||jasmin|2|17|1402413285|0|0
95|nic|20|file|452|/452|452|/Kalender_von_Linda.ics|||linda|2|17|1402414655|0|0
97|nic|28|folder|561|/561|561|/StatE_Team|||julia|2|31|1403075714|0|0
98|nic|19|file|443|/443|443|/Kalender_von_Jasm.ics|||jasmin|2|17|1402413285|0|0
99|nic|20|file|452|/452|452|/Kalender_von_Linda.ics|||linda|2|17|1402414655|0|0
101|nic|28|folder|561|/561|561|/StatE_Team|||julia|2|31|1403075714|0|0
102|nic|19|file|443|/443|443|/Kalender_von_Jasm.ics|||jasmin|2|17|1402413285|0|0
103|nic|20|file|452|/452|452|/Kalender_von_Linda.ics|||linda|2|17|1402414655|0|0
105|nic|28|folder|561|/561|561|/StatE_Team|||julia|2|31|1403075714|0|0
106|nic|19|file|443|/443|443|/Kalender_von_Jasm.ics|||jasmin|2|17|1402413285|0|0
107|nic|20|file|452|/452|452|/Kalender_von_Linda.ics|||linda|2|17|1402414655|0|0
109|nic|28|folder|561|/561|561|/StatE_Team|||julia|2|31|1403075714|0|0
110|nic|19|file|443|/443|443|/Kalender_von_Jasm.ics|||jasmin|2|17|1402413285|0|0
111|nic|20|file|452|/452|452|/Kalender_von_Linda.ics|||linda|2|17|1402414655|0|0
113|nic|28|folder|561|/561|561|/StatE_Team|||julia|2|31|1403075714|0|0
114|nic|19|file|443|/443|443|/Kalender_von_Jasm.ics|||jasmin|2|17|1402413285|0|0
115|nic|20|file|452|/452|452|/Kalender_von_Linda.ics|||linda|2|17|1402414655|0|0
117|nic|28|folder|561|/561|561|/StatE_Team|||julia|2|31|1403075714|0|0
118|nic|19|file|443|/443|443|/Kalender_von_Jasm.ics|||jasmin|2|17|1402413285|0|0
119|nic|20|file|452|/452|452|/Kalender_von_Linda.ics|||linda|2|17|1402414655|0|0
121|nic|28|folder|561|/561|561|/StatE_Team|||julia|2|31|1403075714|0|0
122|nic|19|file|443|/443|443|/Kalender_von_Jasm.ics|||jasmin|2|17|1402413285|0|0
123|nic|20|file|452|/452|452|/Kalender_von_Linda.ics|||linda|2|17|1402414655|0|0
125|nic|28|folder|561|/561|561|/StatE_Team|||julia|2|31|1403075714|0|0
126|nic|19|file|443|/443|443|/Kalender_von_Jasm.ics|||jasmin|2|17|1402413285|0|0
127|nic|20|file|452|/452|452|/Kalender_von_Linda.ics|||linda|2|17|1402414655|0|0
129|nic|28|folder|561|/561|561|/StatE_Team|||julia|2|31|1403075714|0|0
130|nic|19|file|443|/443|443|/Kalender_von_Jasm.ics|||jasmin|2|17|1402413285|0|0
131|nic|20|file|452|/452|452|/Kalender_von_Linda.ics|||linda|2|17|1402414655|0|0
133|nic|28|folder|561|/561|561|/StatE_Team|||julia|2|31|1403075714|0|0
134|nic|19|file|443|/443|443|/Kalender_von_Jasm.ics|||jasmin|2|17|1402413285|0|0
135|nic|20|file|452|/452|452|/Kalender_von_Linda.ics|||linda|2|17|1402414655|0|0
137|nic|28|folder|561|/561|561|/StatE_Team|||julia|2|31|1403075714|0|0
138|nic|19|file|443|/443|443|/Kalender_von_Jasm.ics|||jasmin|2|17|1402413285|0|0
139|nic|20|file|452|/452|452|/Kalender_von_Linda.ics|||linda|2|17|1402414655|0|0
141|nic|28|folder|561|/561|561|/StatE_Team|||julia|2|31|1403075714|0|0
142|nic|19|file|443|/443|443|/Kalender_von_Jasm.ics|||jasmin|2|17|1402413285|0|0
143|nic|20|file|452|/452|452|/Kalender_von_Linda.ics|||linda|2|17|1402414655|0|0
145|nic|28|folder|561|/561|561|/StatE_Team|||julia|2|31|1403075714|0|0
146|nic|19|file|443|/443|443|/Kalender_von_Jasm.ics|||jasmin|2|17|1402413285|0|0
147|nic|20|file|452|/452|452|/Kalender_von_Linda.ics|||linda|2|17|1402414655|0|0
149|nic|28|folder|561|/561|561|/StatE_Team|||julia|2|31|1403075714|0|0
150|nic|19|file|443|/443|443|/Kalender_von_Jasm.ics|||jasmin|2|17|1402413285|0|0
151|nic|20|file|452|/452|452|/Kalender_von_Linda.ics|||linda|2|17|1402414655|0|0
153|nic|28|folder|561|/561|561|/StatE_Team|||julia|2|31|1403075714|0|0
154|nic|19|file|443|/443|443|/Kalender_von_Jasm.ics|||jasmin|2|17|1402413285|0|0
155|nic|20|file|452|/452|452|/Kalender_von_Linda.ics|||linda|2|17|1402414655|0|0
157|nic|28|folder|561|/561|561|/StatE_Team|||julia|2|31|1403075714|0|0
158|nic|19|file|443|/443|443|/Kalender_von_Jasm.ics|||jasmin|2|17|1402413285|0|0
159|nic|20|file|452|/452|452|/Kalender_von_Linda.ics|||linda|2|17|1402414655|0|0
161|nic|28|folder|561|/561|561|/StatE_Team|||julia|2|31|1403075714|0|0
162|nic|19|file|443|/443|443|/Kalender_von_Jasm.ics|||jasmin|2|17|1402413285|0|0
163|nic|20|file|452|/452|452|/Kalender_von_Linda.ics|||linda|2|17|1402414655|0|0
165|nic|28|folder|561|/561|561|/StatE_Team|||julia|2|31|1403075714|0|0
166|nic|19|file|443|/443|443|/Kalender_von_Jasm.ics|||jasmin|2|17|1402413285|0|0
167|nic|20|file|452|/452|452|/Kalender_von_Linda.ics|||linda|2|17|1402414655|0|0
169|nic|28|folder|561|/561|561|/StatE_Team|||julia|2|31|1403075714|0|0
170|nic|19|file|443|/443|443|/Kalender_von_Jasm.ics|||jasmin|2|17|1402413285|0|0
```
... and ~60000 more entries. Login takes forever, file syncing not possible.

**Comment by abika** [comment]
update: I added the the early return in `share.php` fix by @thomsmits and removed all duplicate rows in the `oc_share` table. But the database is still continuously filled with the same duplicates making access impossible after some time again.

Can someone plz provide a quick&dirty solution for this? Anything to make owncloud working is appreciated. I'm thinking of a script/cron job to clean the database periodically, but this would be more than ugly.

**Comment by icewind1991** [comment]
#18833 might prevent the creation of duplicate entries

**Comment by icewind1991** [comment]
#18835 should solve the symptoms of high server load caused by the duplicate entries, doesn't prevent the duplicates though

**Comment by abika** [comment]
just tested #18833. Not fixed, duplicates still created on every login

**Comment by PVince81** [comment]
There have been several improvements in 8.1.3 regarding oc_share inefficiencies.
Are you still observing issues on that version ?

**Comment by thomsmits** [comment]
@PVince81 We just performed an update to 8.1.3 on our productive system and removed the thousands of duplicate entries in the oc_share table manually with a SQL query.

After 12 hours of usage, no duplicate entries were written. So it seems as if **8.1.3 has fixed the problem**. Thanks a lot!

After spending five weeks with the bug, I am really curious: Could you explain the reason for the duplicate entries or at least point me to the commit that fixed it?

**Comment by PVince81** [comment]
I don't know the exact details but from what I heard it was a combination of several issues in the sharing code, mixed with a bunch of older broken oc_share entries (from previous bugs)
