### ISSUE TITLE
"php5-apcu" package in the opensuse.org owncloud repository is broken for ubuntu users

### ISSUE THREAD

**Issue by Akhenaton** [owncloud/core#18324]
Why a PHP5 package in the ownCloud repositories... ? That should be handled only by dependencies.
Anyway, the "php5-apcu" one is causing a big mess for ubuntu users... It broke my system.

http://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_**.**/

See the thread on the forum here https://forum.owncloud.org/viewtopic.php?f=31&t=29826

**Comment by DeepDiver1975** [comment]
@jnweigert i question the effort to provide that packages. Hopefully ubuntu will update the packages in day.

**Comment by MorrisJobke** [comment]
cc @jnweiger

**Comment by enoch85** [comment]
This is why the package is included: https://github.com/owncloud/vm/commit/58f7f7572c3a8b2b4f5e09ec74140640992efdf4

**Comment by MorrisJobke** [comment]
I liked the previous way a lot more :see_no_evil: :speak_no_evil: :hear_no_evil:

**Comment by jnweiger** [comment]
I removed the package immediatly after seeing the bug report.
@Akhenaton apparently had a php upgrade installed in his system that breaks phpapi compatibility with the stock Ubuntu 14.04 LTS distribution. 

Our php5-apcu package was tested on Ubuntu 14.04 before and I repeated the tests now, pulling nice cache hit statistics from apcu. 

While preparing a detection for incompatible php upgrades, I ran into  https://bugzilla.novell.com/show_bug.cgi?id=941911

A workaround for this is already included in http://software.opensuse.org/download.html?project=isv%3AownCloud%3Adevel&package=php5-apcu
I'd like to invite everybody to test this package. To my knowledge this is the only apcu package offering version 4.0.6 that was actually built for ubuntu 14.04 -- many other 'solutions' float the internet, most of them recommend to pull the package from 14.10, or from Andrej's personal ppa repository.

**Comment by jnweiger** [comment]
We have now 3 safety precautions in place to avoid this issue in future.
1) it is only in devel and testing repositories for now,
2) its version number is less than 4.0.6-1+deb.sury.org~utopic+1
3) its phpapi-20121212 version check now actually works.

I am closing here, but still waiting for a response in the forum.
