### ISSUE TITLE
"Updater" app refers to "README", but no "README" exists

### ISSUE THREAD

**Issue by alvar-freude** [owncloud/core#18330]
The Updater app has the description "ownCloud updater plugin. Check README for details."

But there is no README file. No file with this name in app/updater and subfolders.

**Comment by MorrisJobke** [comment]
I don't know if this is bundled within the app. But it is in the repo: https://github.com/owncloud/updater/blob/master/README.md

@alvar-freude Can I ask you to open this in the updater bug tracker? Thanks

https://github.com/owncloud/updater/issues
