### ISSUE TITLE
Error occurred while checking server setup after upgrade to OC 8.1.1

### ISSUE THREAD

**Issue by danielkoch** [owncloud/core#18336]
### Steps to reproduce
1. Upgrade from 8.0.5 to 8.1.1
2. Open Browser Developer Tools (Network tab or console)
2. Call Admin panel <HOST>/index.php/settings/admin

### Expected behaviour
No errors in admin panel:
<HOST>/index.php/settings/admin

### Actual behaviour
Call <HOST>/index.php/settings/admin
Shows the following Error:
"Error occurred while checking server setup
Please double check the installation guides ↗, and check for any errors or warnings in the log."

### Server configuration
**Operating system**:
CentOS

**Web server:**
Apache 2

**Database:**
MySQL

**PHP version:**
5.5.15

**ownCloud version:** (see ownCloud admin page)
8.1.1

**Updated from an older ownCloud or fresh install:**
Update from 8.0.5

**List of activated apps:**
* activity: 2.0.1
* calendar: 0.7.3
* contacts: 0.4.0.0
* encryption: 1.0.0
* files: 1.1.10
* files_pdfviewer: 0.7
* files_sharing: 0.6.2
* files_texteditor: 0.4
* files_trashbin: 0.6.3
* gallery: 0.6.1
* templateeditor: 0.1
* updater: 0.6

### Client configuration
Chrome (current)

**Operating system:**
Mac OS X

#### Web server error log
No logs

#### ownCloud log (data/owncloud.log)
No Logs

#### Browser log
The network tab or console:
"GET <HOST>/index.php/settings/ajax/checksetup 403 (Forbidden)"
If I open the url that is called via ajax I get an: ERR_TOO_MANY_REDIRECTS

**Comment by geekcomputing** [comment]
I am receiving the same error also. #18303

**Comment by PVince81** [comment]
@LukasReschke

**Comment by LuckySB** [comment]
I am receiving the same error

**Comment by ToonOwncloud** [comment]
I got the same error message after upgrading to OC 8.1.1

**Comment by twrhills** [comment]
Same error on OC 8.1.3

**Comment by fuco809** [comment]
same error with centos6 (latest 6.7) and remi-php56 and postgresql9.3 with owncloud 8.1.3 behind a proxy!

**Comment by xylo** [comment]
Same error with owncloud 8.1.3, centos 6.7, php 5.6 (via fastcgi, built from sources), mysql 5.1.73, apache 2.2.15.

**Comment by PVince81** [comment]
>"GET /index.php/settings/ajax/checksetup 403 (Forbidden)"
> If I open the url that is called via ajax I get an: ERR_TOO_MANY_REDIRECTS

So all of you are getting "ERR_TOO_MANY_REDIRECTS" ?

Mind posting your config.php ? Is the domain name / path missing from the "checksetup" URL ?
Does the proxy allow the browser to connect to that URL ?

**Comment by danielkoch** [comment]
I get a "ERR_TOO_MANY_REDIRECTS" also without a proxy.

The browser console the slashes are encoded:  
/index.php?redirect_url=%2Findex.php%2Fsettings%2Fajax%2Fchecksetup

Which config parameter do you mean?

**Comment by fuco809** [comment]
tried it again with browsers network log, same result as described.
opening /index.php/settings/admin results in the 403 of checksetup, others mostly with 200.
--> all requests without domainname.
opening /index.php/settings/ajax/checksetup directly, make a redirect loop with 307,302,307,...
when 307 its with the domainname, when 302 its without domainname.

and the proxy should allow the access.

**Comment by sgonzalez3884** [comment]
I am seeing the same thing, with this in the owncloud.log:

{"reqId":"d\/5GH3y5ZT7u++RUTKj2","remoteAddr":"xxx.xxx.xxx.xxx","app":"no app in context","message":"CSRF check failed","level":0,"time":"2015-10-14T14:09:59+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/ajax\/checksetup"}

And my config.php:

<?php
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'trusted_domains' =>
  array (
    0 => '*my fqdn*',
  ),
  'datadirectory' => '/srv/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.0.3.4',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'owncloud',
  'installed' => true,
  'forcessl' => true,
  'mail_from_address' => 'oc',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'google.com',
  'theme' => '',
  'maintenance' => false,
  'secret' => 'xxx',
  'forceSSLforSubdomains' => true,
);

**Comment by sgonzalez3884** [comment]
After upgrading manually from 8.1.1 to 8.1.3 this problem stopped.

**Comment by danielkoch** [comment]
Not for me. I get this error also with 8.1.3

**Comment by fuco809** [comment]
have update from 8.1.3 to 8.2.0 by replacing owncloud folder method. problem still exists.

**Comment by jlamer** [comment]
Same on 8.2.1, fresh install.

**Comment by ToonOwncloud** [comment]
Same on 8.2.1, after update from 8.2.0
The issue persists.

**Comment by mitar** [comment]
Same issue here. Using nginx for web server.

**Comment by mitar** [comment]
I am also getting `"app":"no app in context","message":"CSRF check failed"`.

**Comment by mitar** [comment]
I made a pull request which fixes this issue for me: #20806

**Comment by mitar** [comment]
Although, I would claim that redirecting to `index.php` if CSRF check fails is probably a bad idea. It should just return HTTP access code 400 and this is it.

**Comment by LukasReschke** [comment]
> Although, I would claim that redirecting to index.php if CSRF check fails is probably a bad idea. It should just return HTTP access code 400 and this is it.

Let's just redirect to the index.php for now: https://github.com/owncloud/core/pull/20807

**Comment by PVince81** [comment]
Can you guys help testing the PR  https://github.com/owncloud/core/pull/20807/ ? I'm not sure how to reproduce this locally.

**Comment by danielkoch** [comment]
Was this fix already delivered? I have the same problems with oc 8.2.2

**Comment by PVince81** [comment]
The fix is in 9.0beta1 which was released yesterday.

**Comment by AndreaGiardini** [comment]
@PVince81 Will this patch be backported to 8.2.3 ?

**Comment by PVince81** [comment]
Not sure. From looking at the code it looks quite intrusive and risky to backport.
@LukasReschke ?

**Comment by LukasReschke** [comment]
I'd prefer not to. While the error may be annoying it is easy to workaround it and also very rare. IMHO not worth backporting.

**Comment by notaduck** [comment]
@LukasReschke did you guys find a slution for this ?

**Comment by AndreaGiardini** [comment]
@notaduck In my case the error was caused by this bug in nginx https://trac.nginx.org/nginx/ticket/235

**Comment by notaduck** [comment]
@AndreaGiardini did you solve the problem?

**Comment by AndreaGiardini** [comment]
Yes, adding this line `ssl_session_cache shared:SSL:10m;` to /etc/nginx/nginx.conf (http section) solved the problem

**Comment by Trefex** [comment]
I have the same issue on Apache.

Any ideas?
