### ISSUE TITLE
upgrade to 8.1.1 failure

### ISSUE THREAD

**Issue by ludwigschuster** [owncloud/core#18334]
i have tried to upgrade my 8.1. OC installation to 8.1.1 via the updater. 
it failed with the following message

Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "calendar_index" as such route does not exist.
The update was unsuccessful.

and i was supposed to report this here.

**Comment by ludwigschuster** [comment]
the second time i started the Database Upgrade it was successfully. Strange - isn't it?

**Comment by RealRancor** [comment]
Dup of https://github.com/owncloud/core/issues/18333, https://github.com/owncloud/core/issues/18317, https://github.com/owncloud/core/issues/18329, https://github.com/owncloud/core/issues/18296, https://github.com/owncloud/core/issues/18224 and many more...

**Comment by MorrisJobke** [comment]
Continue discussion in #18224

**Comment by ludwigschuster** [comment]
thanks
