### ISSUE TITLE
Arrow that shouldn't be there

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#18338]
![image](https://cloud.githubusercontent.com/assets/4511254/9296177/e232ea6c-4486-11e5-89ff-8787c581ac84.png)

I´m sure this is not intended, is it?

**Server 8.1.1**

@jancborchardt

**Comment by MorrisJobke** [comment]
@enoch85 Which browser do you use? Can you inspect that element (right click -> inspect)

**Comment by enoch85** [comment]
@MorrisJobke Chrome  44.0.2403.155 m (64-bit) It only happens sometimes. Working now. Will update when it happens again.

**Comment by enoch85** [comment]
@MorrisJobke It happened again, but when I pressed F12, it came back to normal. Is it Chrome that's playing tricks on me? :)

**Comment by MorrisJobke** [comment]
@jancborchardt Didn't you had some trouble while introducing this arrow and somehow slightly adjusted some values to get it working. Maybe it's related to DPI of the screen or something like that and simply needs a bit wider area.

**Comment by jancborchardt** [comment]
Maybe a caching issue? Please inspect the CSS when this happens again.

**Comment by enoch85** [comment]
@jancborchardt Yeah I would if not:

> It happened again, but when I pressed F12, it came back to normal.

So how should I check the CSS?

**Comment by jancborchardt** [comment]
Well, then most likely this is a caching issue. Does this happen with any other machine or browser?

**Comment by enoch85** [comment]
@jancborchardt All my computers, have not tested in other browsers than Chrome. But anyway, just a small issue, not so important.
