### ISSUE TITLE
Database upgrade files to 1.1.10

### ISSUE THREAD

**Issue by ridwande** [owncloud/core#18333]
Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "calendar_index" as such route does not exist.

**Comment by RealRancor** [comment]
Dup of https://github.com/owncloud/core/issues/18317, https://github.com/owncloud/core/issues/18329, https://github.com/owncloud/core/issues/18296, https://github.com/owncloud/core/issues/18224 and many more...

**Comment by MorrisJobke** [comment]
@ridwande Run the upgrade a second time and it will succeed.

Let's continue discussion in #18224
