### ISSUE TITLE
Exception: App does not provide an info.xml file

### ISSUE THREAD

**Issue by rasco2** [owncloud/core#18337]
Updating ownCloud to version 8.1.1, this may take a while.

Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Updated "updater" to 0.6
Updated "files" to 1.1.10
Updated "activity" to 2.0.1
Exception: App does not provide an info.xml file

**Comment by RealRancor** [comment]
Have a look at existing issues like https://github.com/owncloud/core/issues/17767 or https://github.com/owncloud/core/issues/17591 for some pointers.

Could be also useful if you're filling out the issue template as askend in the yellow box when creating a new issue.

**Comment by DeepDiver1975** [comment]
Closing since this is a potential duplicate
