### ISSUE TITLE
Email address can't be set or changed for external user 

### ISSUE THREAD

**Issue by netnut404** [owncloud/core#18335]
In a fresh install of owncloud 8.1.1  from yum repository  with a added external backed user ( I used pwauth "Unix user backend" ) the built in account can have it's email address edited, but the backedn user's email address cannot be set or changed
when attempting to, you get unable to change mail address as seen below.
![owncloud-email-fail](https://cloud.githubusercontent.com/assets/1848285/9294660/ec60535e-4408-11e5-9d4e-5455cca03e16.png)

**Comment by Xenopathic** [comment]
It's hardly surprising that external users cannot be modified. The real issue here is that the 'Email' section isn't being disabled when the user is from an external backend, giving the false impression that it can be adjusted when it cannot.

cc @jancborchardt @blizzz

**Comment by MorrisJobke** [comment]
I would allow to overwrite this if the backend doesn't provide email addresses

**Comment by DeepDiver1975** [comment]
It is the reponsibility of the Backend to support this or not. Please get in touch with the developer of pwauth. THX
