### ISSUE TITLE
fail to run cron job

### ISSUE THREAD

**Issue by jlmttn** [owncloud/core#18344]
Steps to reproduce
1.	Run the cron job by php –f cron.php as wwwrun user
2.	Have a look at the error logs

Expected behaviour
Cron jobs working

Actual behaviour
At cron.php messages in owncloud.log :
{"reqId":"6qSPicWQa5gG3s+9NP+T","remoteAddr":"","app":"no app in context","message":"Error while running background job: Expected response code 250 but got code \"\", with message \"\"","level":3,"time":"2015-08-17T11:00:05+02:00"}
Same simptom with « test email settings » :
A problem occurred while sending the email. Please revise your settings. (Error: Expected response code 250 but got code "", with message "")

Server configuration
Operating system: OpenSuse 13.2
Web server: 
apache2, Version 2.4.10, Release 25.1, Architecture: x86_64apache
Database:
mysql-community-server, version 5.6.25, release 2.6.2
PHP :
PHP5, version 5.6.1, release 33.1
ownCloud :
version 8.1.1, release 12.1
Are you using external storage, if yes which one: no
Are you using encryption: no
Logs
ownCloud log (data/owncloud.log)

**Comment by MorrisJobke** [comment]
@jlmttn Looks like your email settings are not correct. This is a error message of the email sending code.

**Comment by MorrisJobke** [comment]
Error line: https://github.com/owncloud/core/blob/15da671349727ab26449ca4cc4e3140b7b455a9a/settings/controller/mailsettingscontroller.php#L159-159

The message is generated by SwiftMailer: https://github.com/swiftmailer/swiftmailer/blob/b11f0054d96fa49200d10401e34d879e46c2a2c6/lib/classes/Swift/Transport/AbstractSmtpTransport.php#L383-L387

**Comment by MorrisJobke** [comment]
From http://stackoverflow.com/a/11161978

> There could be a number of things causing this. The most likely one is that your server has connecting to external hosts turned off. Other possibilities are that you're using an old version of PHP that has an openSSL error or that you're being rate limited by something.

Can you try to send a mail from this server with command line tools and the same email setup?

**Comment by jlmttn** [comment]
Hi,
thes 2 issues appear since upgrade to OC 8.1 from OC 8.0.
For cron.php job and email settings no change:
cron.php run by the cron sheduler.
Email setting : send by sendmail and from with no change.
At upgrade mistake with search-lucene for database maintenance ( as an open isue)

**Comment by MorrisJobke** [comment]
@jlmttn Do you still experience this issue?

**Comment by jlmttn** [comment]
@MorrisJobke 
No, I do a workarround.
Before I use the local sendmail, now I use OC itself to send email.
With sendmail I ave the local buffering in case of broken internet connection.

**Comment by MorrisJobke** [comment]
> With sendmail I ave the local buffering in case of broken internet connection.

In case of broken internet it should be okay to log something. Or am I wrong? The log entries during cron run only occurs sometimes, or do they occur always?

**Comment by jlmttn** [comment]
the occur always.
Now with this config all work fine.
But today I am to busy to test more.
But after upgrade to OC 8.2 I can test more.
