### ISSUE TITLE
Admin user is missing in "root" storage

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#18346]
There is a root storage called "local::/srv/www/htdocs/owncloud/data/".

When creating users, entries are created for each user.
However the administrator user doesn't have an entry and that entry never ever appears.

This makes it problematic when using `$rootView->getDirectoryContents()` with "filesystem_check_changes" set to 0 (the new default in 8.2).

We need to fix the core problem and make sure that the administrator user's folder is also indexed there.

Furthermore we noticed that the order of storages is incorrect:
```
MariaDB [owncloud]> select * from oc_storages;
+---------------------------------------+------------+
| id                                    | numeric_id |
+---------------------------------------+------------+
| home::admin                            |          1 |
| local::/srv/www/htdocs/owncloud/data/ |          2 |
+---------------------------------------+------------+
```

The admin user's storage is created before the root storage.

To fix:
1) Make sure the root storage exists before creating the admin user at setup time
2) Write a repair step that ensures that the admin user exists in the root storage (this could be done by iterating over the local users using the local user manager and making sure the home folder entries exist in the root storage)

Please note that we cannot rely on FS detection due to the "filesystem_check_changes" setting, also there is another bug with update detection that can make this not work properly. (will be raised separately)

This blocks https://github.com/owncloud/core/pull/17899#issuecomment-131736429

@icewind1991 @schiesbn

**Comment by PVince81** [comment]
Set to critical as this is blocking a feature scheduled for 8.2

**Comment by PVince81** [comment]
This isn't a blocker anymore.

In general it's not a good idea to rely on the root storage entry in the database to iterate over the user.
One should use the UserManager for that.

The PR https://github.com/owncloud/core/pull/17899 that was originally blocked by this has been modified to use the UserManager instead.

I am not aware of other code paths that would use the "wrong" approach so I suggest reducing severity to high or medium. @cmonteroluque

**Comment by icewind1991** [comment]
I dont think we should keep this issue open at all, users folders showing up in the root storage is not the case for all setups so nothing should rely on it

**Comment by cmonteroluque** [comment]
ok, closing
