### ISSUE TITLE
sidebar breaks file move operation

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#18349]
Steps to reproduce:

- create a folder "folder"
- create a file 
- try to drag & drop file to folder

Expected:
file gets moved to folder

Actual result:
empty sidebar opens and move operation fails

JS Console:

````TypeError: $el.attr is not a function                share.js:66:32````

![1](https://cloud.githubusercontent.com/assets/1589737/9304122/22857568-44e5-11e5-8491-5cc52c13cc6b.png)

cc @jancborchardt @PVince81 @blizzz

**Comment by PVince81** [comment]
First breaking commit: c964eff17b1a7feeab794f6035a7beff8143ac85

**Comment by jancborchardt** [comment]
The sidebar should only open on mouseup then, not on mousedown.

**Comment by PVince81** [comment]
It's not about opening, it's about highlighting the current row.
Changing the highlight of the current row through any action would trigger the sidebar opening.
I'd rather we focus on https://github.com/owncloud/core/issues/18238 instead where we discussed alternatives.
