### ISSUE TITLE
No ldap user appears

### ISSUE THREAD

**Issue by pretorien51** [owncloud/core#18340]
Hi,
I configure correctly ldap connection it says that all is ok (test also) but no user appears in user panel and in logs i have the error below:

Error	PHP	ldap_read(): Search: Invalid DN syntax at /var/www/owncloud/apps/user_ldap/lib/ldap.php#257

Someone could help me?
**Operating system**:

**Web server:apache

**Database:mysql

**ownCloud version:**8.1.1.3

Fresh Install

Thanks

**Comment by PVince81** [comment]
@pretorien51 what LDAP server are you using ? You should use the issue template when reporting issues, see https://raw.githubusercontent.com/owncloud/core/master/issue_template.md.
Thanks.

@blizzz does this error message ring any bells ?

**Comment by pretorien51** [comment]
I'm using active directory 2012 R2

**Comment by MorrisJobke** [comment]
Looks very much like #17570

**Comment by pretorien51** [comment]
yes i already test 
./occ ldap:set-config "" useMemberOfToDetectMembership 0

**Comment by blizzz** [comment]
configuration  please

**Comment by pretorien51** [comment]
+-------------------------------+----------------------------------------------------+
+-------------------------------+----------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                  |
| hasPagedResultSupport         |                                                    |
| homeFolderNamingRule          |                                                    |
| lastJpegPhotoLookup           | 0                                                  |
| ldapAgentName                 | cn=download,cn=Users,dc=fmb,dc=local               |
| ldapAgentPassword             | ***                                                |
| ldapAttributesForGroupSearch  |                                                    |
| ldapAttributesForUserSearch   |                                                    |
| ldapBackupHost                |                                                    |
| ldapBackupPort                |                                                    |
| ldapBase                      | cn=Users,dc=fmb,dc=local                           |
| ldapBaseGroups                | cn=Users,dc=fmb,dc=local                           |
| ldapBaseUsers                 | cn=Users,dc=fmb,dc=local                           |
| ldapCacheTTL                  | 60                                                 |
| ldapConfigurationActive       | 1                                                  |
| ldapEmailAttribute            |                                                    |
| ldapExperiencedAdmin          | 1                                                  |
| ldapExpertUUIDGroupAttr       | objectClass=group                                  |
| ldapExpertUUIDUserAttr        | objectClass=person                                 |
| ldapExpertUsernameAttr        | sAMAccountName                                     |
| ldapGroupDisplayName          | cn                                                 |
| ldapGroupFilter               | (&(|(objectclass=group)))                          |
| ldapGroupFilterGroups         |                                                    |
| ldapGroupFilterMode           | 0                                                  |
| ldapGroupFilterObjectclass    | group                                              |
| ldapGroupMemberAssocAttr      | member                                             |
| ldapHost                      | 192.168.0.85                                       |
| ldapIgnoreNamingRules         |                                                    |
| ldapLoginFilter               | (&(&(|(objectclass=person)))(samaccountname=%uid)) |
| ldapLoginFilterAttributes     |                                                    |
| ldapLoginFilterEmail          | 0                                                  |
| ldapLoginFilterMode           | 1                                                  |
| ldapLoginFilterUsername       | 1                                                  |
| ldapNestedGroups              | 0                                                  |
| ldapNoCase                    | 1                                                  |
| ldapOverrideMainServer        |                                                    |
| ldapPagingSize                | 500                                                |
| ldapPort                      | 389                                                |
| ldapQuotaAttribute            |                                                    |
| ldapQuotaDefault              |                                                    |
| ldapTLS                       | 0                                                  |
| ldapUserDisplayName           | displayname                                        |
| ldapUserFilter                | (&(|(objectclass=person)))                         |
| ldapUserFilterGroups          |                                                    |
| ldapUserFilterMode            | 0                                                  |
| ldapUserFilterObjectclass     | person                                             |
| ldapUuidGroupAttribute        | auto                                               |
| ldapUuidUserAttribute         | auto                                               |
| turnOffCertCheck              | 1                                                  |
| useMemberOfToDetectMembership | 0                                                  |
+-------------------------------+----------------------------------------------------+

**Comment by pretorien51** [comment]
any clue?

**Comment by blizzz** [comment]
is the displayname set for your users? try with cn as display name attribute (advanced settings). 

```
Error PHP ldap_read(): Search: Invalid DN syntax at /var/www/owncloud/apps/user_ldap/lib/ldap.php#257
```

you can ignore this savely. something else in the log?

**Comment by pretorien51** [comment]
I try with cn or displayname as display name attribute and nothing else.
Yes display name is set for users. all test seems ok but nothing appears

2015-08-19 13:31 GMT+02:00 blizzz <notifications@github.com>:

**Comment by blizzz** [comment]
Are there any trailing spaces in your base DNs?

**Comment by pretorien51** [comment]
no spaces

2015-08-19 15:00 GMT+02:00 blizzz <notifications@github.com>:

**Comment by blizzz** [comment]
```
| ldapExpertUUIDGroupAttr | objectClass=group |
| ldapExpertUUIDUserAttr | objectClass=person |
```

values there must be attributes, not filters

**Comment by blizzz** [comment]
Closing this as configuration issue.
