### ISSUE TITLE
Properly set update detection default for ext storage

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#18347]
Remember that since 8.2 filesystem_check_changes defaults to 0.

### Steps

1. Mount SFTP ext storage
1. Upload a file remotely (not through ownCloud)
1. Refresh the UI: change not detected
1. Go to the admin page
1. Change the mount option "Check for changes" to "Never", and then back again to "Once ..."
1. Refresh the UI

### Expected result
Mount option should default to "Once every direct access".

### Actual result
The admin UI shows that the default is "Once every direct access", but "mount.json" doesn't contain any value. This makes it default to "Never".

### Versions
ownCloud 8.2 pre-alpha git (f74416a0cb6bbb17ae646c952987e5eeea8390cf)

@Xenopathic will your new backend mechanism automatically and explicitly set the default values for mount options ?

**Comment by Xenopathic** [comment]
It's not currently designed to apply default mount options, but it could be adjusted to. If we want that feature though, I'd suggest implementing it after the PR is merged.

However, you say that changing the mount options to Once... doesn't actually save it? That sounds like a different bug

**Comment by PVince81** [comment]
@Xenopathic no, it does save it.
The problem is that initially, even though the UI shows that, "mount.json" doesn't contain the mount options, so internally it defaults to the new default which is 0 (never).
You have to "shake" it by changing the setting back and forth in the UI to force-save the mount options, so it can have the correct values instead of nothing at all.

Let's fix it after https://github.com/owncloud/core/pull/15914 is merged.

**Comment by Xenopathic** [comment]
Ahh, I see. The 'default' is actually set in the dropdown template, which is probably the root of the problem.

**Comment by PVince81** [comment]
Your PR was merged, time to fix this.
Do you want to take care of it or should I ?

**Comment by Xenopathic** [comment]
@PVince81 I'll have a look at it. :smile:

**Comment by Xenopathic** [comment]
Perhaps the best solution for this is to move the mount options from their current place, hardcoded into the dropdown template, to a dedicated MountOptionsService where mount options can be registered (much like backends/auth mechanisms can now). Only problem with this approach is the time investment needed.

**Comment by PVince81** [comment]
@Xenopathic I think we will need this eventually, the ability for backends to tell what mount options they support and what not. But probably not now.
