### ISSUE TITLE
Changing activity related interfaces for 8.2

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#18358]
# Extending the Activity Manager

The manager's `publishActivity()` method needs two new parameters $objectType (string) and $objectId (int),
which are used to filter the list of activities, e.g. in the right side bar, to a given object (file + id).
Possible solutions:
1. Don't change the interface
2. Change the interface

### Don't change the interface

Positive:
+ Interface is kept stable
+ Feature is still available

Negative:
- Interface does not match the signature of the implementation, this might be problematic when dealing with mocks in unit tests (which are generated from the interface):
```php
	public function publishActivity(..., $type, $priority);
```
vs.
```php
	public function publishActivity(..., $type, $priority, $objectType = '', $objectId = 0) { ... }
```

### Change the interface

Positive:
+ Interface matches the signature of the implementation
+ Feature is still available

Negative:
- Interface is broken :zap: - But let's be honest, there shouldn't be any other activity manager implementations out there (apart from unit tests, which mostly rely on the interface instead of the implementation, when they use a mock)

## Suggestion

My suggestion would be changing the interface, it keeps the code cleaner and the risk to break anything is quite low I'd say

---

# Extending the Activity Consumer

Similar to the manager, the consumer also needs the new arguments on the `receive()` method.
Possible solutions:
1. Don't change the interface (see above)
2. Change the interface (see above)
3. :new: Add a second interface `IConsumer2` or `IConsumerv2`

### Add a second interface

Positive:
+ Interface is kept stable
+ Feature is still available

Negative:
- Calling the consumers is more complicated:
```php
	public function publishActivity($app, $subject, $subjectParams, $message, $messageParams, $file, $link, $affectedUser, $type, $priority, $objectType = '', $objectId = 0) {
		foreach($this->getConsumers() as $c) {
			if ($c instanceof IConsumer) {
				$c->receive(..., $type, $priority);
			} else {
				$c->receive(..., $type, $priority, $objectType, $objectId);
			}
		}
	}
```

## Suggestion

My suggestion would be to use Solution 2 here again, as the only known IConsumer is again the one from the activity app itself, which would be updated immediately.

---

# Extending the Activity Extension

In case we change the IExtension interface, my suggestion would be to use the Solution 3. There are quite a number of extensions out there and we want people to keep using it. I have currently two changes on my mind, which make developing an extension easier for app devs. But for now they are not needed, just nice to have (opposed to the IConsumer and IManager changes which we need for the right sidebar feature)

@DeepDiver1975 awaiting your comment

**Comment by PVince81** [comment]
How about using this opportunity to introduce a new class `ActivityEvent` or something that contains all the required attributes ? This would make adding new attributes easier as you wouldn't need to change the method signature any more.
