### ISSUE TITLE
[owncloud][PHP][3] file_put_contents(/media/owncloud/data/.htaccess): failed to open stream: Permission denied at /var/www/owncloud/lib/private/setup.php#435

### ISSUE THREAD

**Issue by ezraholm50** [owncloud/core#18351]
[owncloud][PHP][3] file_put_contents(/media/owncloud/data/.htaccess): failed to open stream: Permission denied at /var/www/owncloud/lib/private/setup.php#435

When performing sudo -u www-data php occ upgrade i get the error stated above. Also the upgrade seems to hang.

"ubs:@server:/var/www/owncloud# sudo -u www-data php occ upgrade -v
ownCloud or one of the apps require upgrade - only a limited number of commands are available
Turned on maintenance mode
[owncloud][PHP][3] file_put_contents(/media/owncloud/data/.htaccess): failed to open stream: Permission denied at /var/www/owncloud/lib/private/setup.php#435
Repair step: Repair MySQL database engine
Repair step: Repair MySQL collation
Repair step: Repair SQLite autoincrement
Repair step: Repair duplicate entries in oc_lucene_status
Repair info: lucene_status table does not exist -> nothing to do
Repair step: Repair config"

Last thing stated is repair config then does nothing for over half an hour right now, everything worked like a charm before. Manually rm -rf /apps/agreedisclaimer && mv /xxxxx/agreedisclaimer /apps/agreedisclaimer (new version) then tried occ upgrade and this stuff started.

oc 8.1.1
ubuntu 14.04
php 5.5

Will provide additional info if needed.
Thanks alot!

**Comment by RealRancor** [comment]
Hi,

have you fixed the permission issue before doing the update:

> failed to open stream: Permission denied

**Comment by ezraholm50** [comment]
Yep, everything to www-data or are there any other guidelines?

**Comment by RealRancor** [comment]
As your data dir is on an external device (/media) other permissions (like on mount time) could apply here.

**Comment by ezraholm50** [comment]
Like some cron jobs or something? 

I just did a reboot, permission issue is gone now, should be instant gone right?
Now the long config line stated above still is valid, any thoughts?
Thanks for the help!
