### ISSUE TITLE
File share menu | Not searching throug contacts

### ISSUE THREAD

**Issue by prilly** [owncloud/core#18356]
It seems the files share is not searching throug contact upon creating a share with url.
if i try to share a folder i get the dialog where to input username or external user. old behavior was that it searched trough contacts for email adresses AND internal users. Now only users from owncloud is showing up.

search lucene is not in use. this is also a clean install no upgrade. there is also only one contact list. i have no errors in logs.

**Comment by karlitschek** [comment]
Users of the ownCloud server are used for the sharing. This is different then the users in the contacts apps. This works as designed.
