### ISSUE TITLE
DB-Schema update fails, 8.1.0 to 8.1.1

### ISSUE THREAD

**Issue by timreeves** [owncloud/core#18350]
This is a very lean installation with hardly any apps enabled, and not much user accounts or data. I really did not expect a problem, but there was:

Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "calendar_index" as such route does not exist.

Here follow the 2 log entries:

Exception: {"Exception":"OC\\NeedsUpdateException","Message":"","Code":0,"Trace":"#0 \/var\/www\/vhosts\/biblische-reisen.de\/owncloud.biblische-reisen.de\/lib\/private\/app.php(99): OC_App::loadApp('files')\n#1 \/var\/www\/vhosts\/biblische-reisen.de\/owncloud.biblische-reisen.de\/lib\/private\/util.php(127): OC_App::loadApps(Array)\n#2 \/var\/www\/vhosts\/biblische-reisen.de\/owncloud.biblische-reisen.de\/lib\/base.php(872): OC_Util::setupFS()\n#3 \/var\/www\/vhosts\/biblische-reisen.de\/owncloud.biblische-reisen.de\/index.php(40): OC::handleRequest()\n#4 {main}","File":"\/var\/www\/vhosts\/biblische-reisen.de\/owncloud.biblische-reisen.de\/lib\/private\/app.php","Line":118} 

 	Exception: {"Exception":"Symfony\\Component\\Routing\\Exception\\RouteNotFoundException","Message":"Unable to generate a URL for the named route \"calendar_index\" as such route does not exist.","Code":0,"Trace":"#0 \/var\/www\/vhosts\/biblische-reisen.de\/owncloud.biblische-reisen.de\/lib\/private\/route\/router.php(306): Symfony\\Component\\Routing\\Generator\\UrlGenerator->generate('calendar_index', Array, false)\n#1 \/var\/www\/vhosts\/biblische-reisen.de\/owncloud.biblische-reisen.de\/lib\/private\/route\/cachingrouter.php(53): OC\\Route\\Router->generate('calendar_index', Array, false)\n#2 \/var\/www\/vhosts\/biblische-reisen.de\/owncloud.biblische-reisen.de\/lib\/private\/urlgenerator.php(65): OC\\Route\\CachingRouter->generate('calendar_index', Array)\n#3 \/var\/www\/vhosts\/biblische-reisen.de\/owncloud.biblische-reisen.de\/lib\/private\/helper.php(139): OC\\URLGenerator->linkToRoute('calendar_index', Array)\n#4 \/var\/www\/vhosts\/biblische-reisen.de\/owncloud.biblische-reisen.de\/lib\/public\/util.php(306): OC_Helper::linkToRoute('calendar_index', Array)\n#5 \/var\/www\/vhosts\/biblische-reisen.de\/owncloud.biblische-reisen.de\/apps\/calendar\/appinfo\/app.php(30): OCP\\Util::linkToRoute('calendar_index')\n#6 \/var\/www\/vhosts\/biblische-reisen.de\/owncloud.biblische-reisen.de\/lib\/private\/app.php(139): require_once('\/var\/www\/vhosts...')\n#7 \/var\/www\/vhosts\/biblische-reisen.de\/owncloud.biblische-reisen.de\/lib\/private\/app.php(120): OC_App::requireAppFile('calendar')\n#8 \/var\/www\/vhosts\/biblische-reisen.de\/owncloud.biblische-reisen.de\/lib\/private\/app.php(1173): OC_App::loadApp('calendar', false)\n#9 \/var\/www\/vhosts\/biblische-reisen.de\/owncloud.biblische-reisen.de\/lib\/private\/installer.php(214): OC_App::updateApp('calendar')\n#10 \/var\/www\/vhosts\/biblische-reisen.de\/owncloud.biblische-reisen.de\/lib\/private\/installer.php(244): OC_Installer::updateApp(Array)\n#11 \/var\/www\/vhosts\/biblische-reisen.de\/owncloud.biblische-reisen.de\/lib\/private\/updater.php(480): OC_Installer::updateAppByOCSId('168707')\n#12 \/var\/www\/vhosts\/biblische-reisen.de\/owncloud.biblische-reisen.de\/lib\/private\/updater.php(301): OC\\Updater->upgradeAppStoreApps(Array)\n#13 \/var\/www\/vhosts\/biblische-reisen.de\/owncloud.biblische-reisen.de\/lib\/private\/updater.php(195): OC\\Updater->doUpgrade('8.1.1.3', '8.1.0.8')\n#14 \/var\/www\/vhosts\/biblische-reisen.de\/owncloud.biblische-reisen.de\/core\/ajax\/update.php(87): OC\\Updater->upgrade()\n#15 {main}","File":"\/var\/www\/vhosts\/biblische-reisen.de\/owncloud.biblische-reisen.de\/3rdparty\/symfony\/routing\/Symfony\/Component\/Routing\/Generator\/UrlGenerator.php","Line":134} 

When I called my ownCloud URL a 2nd time it again offered the update, which then seemed to work, I'm back online.

**Comment by RealRancor** [comment]
Dup of https://github.com/owncloud/core/issues/18333, https://github.com/owncloud/core/issues/18317, https://github.com/owncloud/core/issues/18329, https://github.com/owncloud/core/issues/18296, https://github.com/owncloud/core/issues/18224 and many more...

#18224 contains the ongoing discussion.
