### ISSUE TITLE
Can't delete remote share when remote cloud is gone

### ISSUE THREAD

**Issue by chrsch** [owncloud/core#18360]
### Steps to reproduce
1. Share a directory on cloud A via link
2. Integrate share to cloud B
3. Delete cloud A

### Expected behaviour
After deleting cloud A and re-login to cloud B I would expect the directory to be gone or to have ownCloud noticed me the share is no longer available.

### Actual behaviour
First the folder disappears from the folder list in the web ui. After a refresh it is there again with all of it contents. But of course no files can be opened. Unsharing doesn't produce any error in error.log of web server. If I try to access one of the files I get the error in the log posted below.

### Server configuration
**Operating system**: Linux 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Web server:** Apache/2.4.7 (Ubuntu)

**Database:** mysql  Ver 14.14 Distrib 5.5.43, for debian-linux-gnu (x86_64) using readline 6.3

**PHP version:** PHP 5.5.9-1ubuntu4.11 (cli) (built: Jul  2 2015 15:23:08) 

**ownCloud version:** (see ownCloud admin page) 7.0.5 (stable)

**Updated from an older ownCloud or fresh install:** Yes (7.0.3 -> 7.0.4)

**List of activated apps:**
 - activity
 - calendar
 - contacts
 - files
 - files_clipboard
 - files_encryption
 - files_pdfviewer
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - files_videoviewer
 - gallery
 - imprint
 - search_lucene
 - templateeditor
 - updater

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'ocxxxxxxxx',
  'passwordsalt' => 'xxxxxxxxxxxxxxxx',
  'secret' => 'xxxxxxxxxxxxxxxxx',
  'trusted_domains' =>
  array (
    0 => 'owncloud.xxxxxxx.xx',
  ),
  'datadirectory' => '/var/owncloud/data',
  'overwrite.cli.url' => 'https://owncloud.xxxxxxx.xx',
  'dbtype' => 'mysql',
  'version' => '7.0.5.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => '',
  'dbuser' => 'xxxxxxxxxx',
  'dbpassword' => 'xxxxxxxxx',
  'installed' => true,
  'mail_domain' => 'xxxxxxx.xx',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'mail.xxxxxxx.xx',
  'mail_smtpport' => '25',
  'mail_smtpsecure' => 'tls',
  'mail_smtpauth' => 1,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpname' => 'xxxxxx',
  'mail_smtppassword' => 'xxxxxx',
  'mail_from_address' => 'no-reply',
  'filesystem_check_changes' => 0,
  'forcessl' => true,
  'custom_csp_policy' => 'default-src \'self\'; script-src \'self\' \'unsafe-inline\' \'unsafe-eval\'; style-src \'self\' \'unsafe-inline\'; frame-src *; img-src *; font-src \'self\' data:; media-src *',
  'maintenance' => false,
);
```

**Are you using external storage, if yes which one:** none

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome Version 44.0.2403.130 (64-bit)

**Operating system:** OS X 10.10.4

#### Web server error log
```
[Mon Aug 17 17:04:01.590506 2015] [:error] [pid 7385] [client 185.17.xxx.xxx:6107] Resource not found., referer: https://owncloud.xxxxx.xx/index.php/apps/files?dir=%2Fcore-master%20(2)
```

#### ownCloud log (data/owncloud.log)
```
{"app":"webdav client","message":"Resource not found.","level":3,"time":"2015-08-17T15:43:35+00:00"}
{"app":"webdav client","message":"Resource not found.","level":3,"time":"2015-08-17T15:43:36+00:00"}
{"app":"webdav client","message":"Resource not found.","level":3,"time":"2015-08-17T15:43:57+00:00"}
{"app":"webdav client","message":"Resource not found.","level":3,"time":"2015-08-17T15:43:58+00:00"}
```

#### Browser log
**Response from delete.php:** {"data":{"dir":"\/","files":["core-master (2)"],"uploadMaxFilesize":1073741824,"maxHumanFilesize":"Hochladen (max. 1 GB)","freeSpace":32212254720,"usedSpacePercent":0},"status":"success"}

**Response from getstoragestats.php:** {"data":{"uploadMaxFilesize":1073741824,"maxHumanFilesize":"Hochladen (max. 1 GB)","freeSpace":32212254720,"usedSpacePercent":0},"status":"success"}

**Comment by karlitschek** [comment]
@schiesbn

**Comment by chrsch** [comment]
And by the way.. is there a workaround to get rid of the dead share manually?

**Comment by MorrisJobke** [comment]
@chrsch Deleting it from `PREFIX_share_external` should remove the entry.

**Comment by PVince81** [comment]
@chrsch when you say "Delete cloud A", so you mean:
- delete the ownCloud instance/server ?
- delete the link share that was created on cloud A by deleting the file ?
- unshare the link share that was created on cloud A by unsharing ?

**Comment by PVince81** [comment]
I get both cloud A and cloud B were both running OC 7.0.5 ?

**Comment by schiesbn** [comment]
The problem here is that we can't really decide if a server is only temporary not available or if it is gone forever. Would be bad if we remove all your federated shares just because the remote server was down for maintenance.

**Comment by PVince81** [comment]
@schiesbn we already have logic for this: whenever a remote share cannot be reached, it will try and retrieve the remote "shareinfo.php". If shareinfo.php tells us explicitly that the share is gone, then we remove it locally.
In any other case, it is considered as temporary failure.

Now here the question is which one of the situations it is and why it didn't work.

**Comment by chrsch** [comment]
@PVince81 
Both clouds A and B run on the same server but are different instances. Same versions throughout (both instances share very same owncloud served from a ramdisk via overlayfs).

By deleting I mean purge the complete cloud instance so it is permanently gone.

I understand that a federate share should not be removed automatically if the server is in maintenance mode. Maybe a good solution is to mark the share as not reachable (eg. broken share symbol) so the user can decide to remove broken shares (or even a feature remove all broken shares).

But for this issue: I simply want to remove the share manually now and this is not working (maybe because the other cloud is not reachable anymore).

**Comment by PVince81** [comment]
@chrsch okay got it. It makes sense.
A user should always be able to delete a remote share even when not available.

I thought this was fixed already.
