### ISSUE TITLE
permission question

### ISSUE THREAD

**Issue by ezraholm50** [owncloud/core#18365]
Hey guys i cant thank you enough for owncloud! After google'ing i couldnt find a real clear awnser.
Can i chmod 770 and chown -R www-data:www-data my /var/www/owncloud + /media/owncloud/data dir? or what should i do? Thanks alot

Regards of a newbie at coding!

**Comment by karlitschek** [comment]
Thanks :-)
I recommend that you ask this question on the forum or mailing list. This is not really a bug that should be tracked in the owncloud bugtracker :-)
