### ISSUE TITLE
Public page shows "***" (more.svg) but clicking does not bring up anything

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#18371]
![bildschirmfoto vom 2015-08-18 09 22 23](https://cloud.githubusercontent.com/assets/213943/9324484/2507eda6-458b-11e5-8f70-9a70cfcd70f7.png)

**Comment by MorrisJobke** [comment]
cc @PVince81

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/18381
