### ISSUE TITLE
Group gets deleted if last member is removed

### ISSUE THREAD

**Issue by michag86** [owncloud/core#18379]
### Steps to reproduce
1. remove the last user of a group
2. group is deleted after this action

### Expected behaviour
group stays after remove of last user

### Actual behaviour
group gehts deleted after remove of user

This also happens if a group admin removes a user from a group.

This applies to the internal user management.

**Comment by MorrisJobke** [comment]
Just for reference: This can also be done by a subadmin which should be denied.

**Comment by michag86** [comment]
I think this is the source:
https://github.com/owncloud/core/blob/master/settings/ajax/togglegroups.php#L64

After removing this line, group stays after removing of last user.

```
	if(count($usersInGroup) === 0) {
		OC_Group::deleteGroup($group);
	}
```
Should this be removed?
