### ISSUE TITLE
Info link in the sharing menu points to 8.0 documentation.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#18373]
### Steps to reproduce

Open sharing dialog, click on the info button:

![screen shot 2015-08-18 at 09 56 13](https://cloud.githubusercontent.com/assets/9048796/9325023/b2c500bc-458f-11e5-86cf-fcf90e83ac08.png)

### Expected behaviour
8.2 Documentation appears.

### Actual behaviour
8.0 Documentation opens.

**oC Version**
{"installed":true,"maintenance":false,"version":"8.2.0.4","versionstring":"8.2 pre alpha","edition":"Enterprise"}

**Comment by DeepDiver1975** [comment]
@SergioBertolinSG which doc link is opened?

**Comment by SergioBertolinSG** [comment]
@DeepDiver1975 : https://doc.owncloud.com/server/8.0/user_manual/

**Comment by DeepDiver1975** [comment]
> ,"edition":"Enterprise"

aha - enterprise - different theme .... installation source?

**Comment by SergioBertolinSG** [comment]
tarball with daily master

**Comment by DeepDiver1975** [comment]
should be fixed with this https://github.com/owncloud/enterprise/commit/52e49330c98406b147bab94c894267e979a790c4

Let's double check tomorrow

**Comment by PVince81** [comment]
@DeepDiver1975 tomorrow has arrived :smile:

**Comment by PVince81** [comment]
@SergioBertolinSG can you retest ?

**Comment by SergioBertolinSG** [comment]
Working fine in the sidebar 'i'. Using master.
