### ISSUE TITLE
Extend provisioning api getUsers to return more user infos

### ISSUE THREAD

**Issue by michag86** [owncloud/core#18388]
If I want to query 300 users with username, displayname, email address and quota I have to query first /ocs/v1.php/cloud/users and than 300 times /ocs/v1.php/cloud/users/[userid].

Therefore, the server must process 301 requests which is very inperformant.

If I also want query also the group memberships, I have to do additional 300 requests.

If getUsers will be extended to return more info, how to do this?
Add a parameter that must be set to true, if more infos should be requested?

The actual data part of the result looks like this:

```
  <data>
    <users>
      <element>Frank</element>
     </users>
  </data>
```

How to extend it and stay compatible to the actual response?

**Comment by PVince81** [comment]
@MTRichards @tomneedham
