### ISSUE TITLE
Right sidebar pushes icons over file names

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#18383]
![1234](https://cloud.githubusercontent.com/assets/323220/9273931/5397500a-4291-11e5-96c7-99aa22505362.png)

- [ ] Add ellipsis to filename when the sidebar pushes the icons over it

**Comment by PVince81** [comment]
Thanks @oparoz 

I had a quick try localy and this seems tricky.
It looks like in the past we set a hard-coded width, which cannot work properly with narrow views (mobile and sidebar). Might need to find a better way.

@jancborchardt

**Comment by PVince81** [comment]
Now thinking of it, if we could actually add a new column for the file actions.
Not sure why this was never done in the past.

With a new column for the inline file actions, it makes it possible have better control over the sizes/ellipsis.

Problem: moving file actions to a separate column is not a small task as it affects a lot of jquery selectors.

**Comment by jancborchardt** [comment]
@PVince81 we could indeed do that now with the separate column. It wasn’t done in the past because we wanted to have the file actions in more relevant places (like rename next to the name) which is moot now.

But I would wait for 9.0 with that? For now we just have to fix this specific issue.

**Comment by PVince81** [comment]
Yes, let's do the separate column with 9.0 and the quickfix in 8.2.
It seems that the max width has been set arbitrarily in the past ?
