### ISSUE TITLE
files_external smb_oc.php username_as_share is logical not string

### ISSUE THREAD

**Issue by mmccarn** [owncloud/core#18386]
External storage support 0.2.3

Line 42 sets local username_as_share if the parameter is the string 'true', but the data item is a logical value:
```
$this->username_as_share = ($params['username_as_share'] === 'true');
```

The local value of username_as_share is used in this code block:
```
     58                         if ($this->username_as_share) {
     59                                 $share = '/' . $user;
     60                         } elseif (isset($params['share'])) {
     61                                 $share = $params['share'];
     62                         } else {
     63                                 throw new \Exception();
     64                         }
```

I was customizing the code in line 59 to execute a transformation I need to apply to my username values (my  usernames are <folder>@domain.tld, and I need to strip off the extra cruft), but the resulting code was never invoked.

However, my custom code worked fine after changing line 42::
```
$this->username_as_share = ($params['username_as_share'] === TRUE);
```

**Comment by Xenopathic** [comment]
Which ownCloud version was this? cc @PVince81 I think the new StoragesControllers correctly map checkboxes to boolean values, not strings like they were back with AJAX.

**Comment by mmccarn** [comment]
> Version
> ownCloud 8.1.1 (stable)
> 
> Developed by the ownCloud community, the source code is licensed under the AGPL.


I've proposed a patch here:
https://github.com/owncloud/core/compare/master...mmccarn:patch-1

**Comment by PVince81** [comment]
@Xenopathic has submitted a more extensive patch here https://github.com/owncloud/core/pull/18446
