### ISSUE TITLE
Enable provisioning api addUser for subadmins

### ISSUE THREAD

**Issue by michag86** [owncloud/core#18382]
At the moment only admins can user addUser from provsioning api, but not subadmins.

To enable it for subadmins, there is one problem.
If a subadmin creates a user, this user has to be added to a group that the subadmin can manage.

In the internal user management, the user can select the groups, when he adds the user. If no group is selected, all groups are assigned.

At the moment the provisioning api adduser does not support a list of groups that the user is assigned to after creation.

**Comment by PVince81** [comment]
One idea would be to auto-add that user to the group for which the subadmin (API user) is an admin.
But then what happens if the subadmin is admin of several groups ?

I think @michag86 is right that the user creation API needs to allow specifying initial groups to make this work.

@MTRichards @tomneedham @DeepDiver1975

**Comment by MTRichards** [comment]
>I think @michag86 is right that the user creation API needs to allow specifying initial groups to make this work.

I don't see another way around it, but it should be limited to the groups for which the subadmin is an admin and error otherwise. It should also allow multiple groups to be added at once subject to the same limitation.

**Comment by michag86** [comment]
So the plan is to add groups[] to post parameters, check if the user is subadmin of all given groups and assigne the new user to the given groups.
If no groups are given and the user that wants to create the new user is a subadmin, all groups are assigned that the subadmin can manage. That's the way like the internal user management works.

Other suggestions?

**Comment by PVince81** [comment]
That sounds good.

**Comment by michag86** [comment]
@PVince81 @MTRichards If the subadmins gives a group, that he cannot manage, just ignore the group or throw an error?

**Comment by MTRichards** [comment]
Hm. Thinking.
I would throw an error, to require the subadmin fix the API call. No sense in being smart and making them think it worked, and then to find out it didn't later - better to get their call to the API correct.
@DeepDiver1975 ok?

**Comment by michag86** [comment]
Okay and what error to throw?
101 - invalid input data 
RESPOND_UNAUTHORISED
10? - cannot create user with membership of $group

**Comment by MTRichards** [comment]
I like that last one...nice and specific on the problem. 
@DeepDiver1975 @karlitschek Who has insight into our error codes for the OCS APIs?

**Comment by michag86** [comment]
If a subadmin wants to add a user and no groups are given, should we assign all groups that are manageable by subadmin or just throw an error message for this? 

After thinking about this I'm not sure. This is something that seems to be smart. But it also can be a problem, if you can manage many groups and there are many shares for all those groups. In this case the user can access many shares. Maybe that isn't what the subadmin expected.

So is it better to throw an error if a subadmin does not define at least one group to assign?

**Comment by MTRichards** [comment]
I would be explicit here too. If no group is specified, then an error. Since it is almost certain that the API is for a system to system call, we should require the system calling the API to be explicit consistent.

**Comment by michag86** [comment]
ok, so there are:
'group does not exist: '. $group
'user is not a subadmin of the group: '. $group
'no group specified (for subadmin required)'

What error code do I use for this?

**Comment by MTRichards** [comment]
@cmonteroluque @DeepDiver1975 who can assist with codes?

**Comment by PVince81** [comment]
@karlitschek can OCS codes be invented for a specific endpoint or is there a predefined list to draw from ? See https://github.com/owncloud/core/issues/18382#issuecomment-132746600

**Comment by tomneedham** [comment]
@PVince81 They are fairly random from my experience. Although these ones are more consistent: https://github.com/owncloud/core/blob/master/lib/public/api.php#L54. Anything else is made up from 101 upwards with 100 being success.

**Comment by PVince81** [comment]
@individual-it @svigneux  just thought this might interest you as well :smile:

**Comment by individual-it** [comment]
That feature sounds interesting for us. We are planing to assign users to groups by a batch script. If I understand it correctly this would allow us not to use the super-admin but a sub-admin account for that. I like that idea

> 'group does not exist: '. $group

I would not tell in the reply that a group does not exist. Just reply with "'user is not a subadmin of the group: '. $group"

**Comment by rullzer** [comment]
#18605 is merged. So closing this.

**Comment by PVince81** [comment]
Please add an entry here https://github.com/owncloud/core/wiki/ownCloud-9.0-Features
