### ISSUE TITLE
Change User Mail Adress Failed

### ISSUE THREAD

**Issue by VamteTamte** [owncloud/core#18387]
/var/www/owncloud/config/config.php

'allow_user_to_change_display_name' => true,

if the Option is set to "false", users cannot Change their Mail Adress.
Also the Admin cannot Change the Mail Adress after the User is created.

is it possible to split this Option?

- allow user to Change Display Name
- allow user to Change Mail adress

**Comment by PVince81** [comment]
Duplicate of https://github.com/owncloud/core/issues/14127
