### ISSUE TITLE
recursive wget access over webdav

### ISSUE THREAD

**Issue by lu-kas** [owncloud/core#18394]
Hi,

I have used to use wget to recursively download folders from an owncloud server with previous versions of owncloud. However, with version 8.1.0, I just receive the following information (only a single file is downloaded, with the following content):

"This is the WebDAV interface. It can only be accessed by WebDAV clients such as the ownCloud desktop sync client." 

Is this behaviour intended for wget?

Best,
Lukas

**Comment by RealRancor** [comment]
If you have relied on links within the remote.php/webdav then this is the expected behavior. The SabreDAV browser was removed in oC 8.1 because of security reasons.
