### ISSUE TITLE
ownCloud 8.1.1 community repository on openSUSE - owncloud-server-core dependency not met

### ISSUE THREAD

**Issue by kcoombs** [owncloud/core#18406]
There appears to be a dependency issue in the openSUSE repositories for ownCloud 8.1.1 (for at least openSUSE 13.1 and 13.2). Upon adding the ownCloud repository (e.g, http://download.opensuse.org/repositories/isv:/ownCloud:/community/openSUSE_13.2/, for openSUSE 13.2) and selecting the 'owncloud' package in YaST, a dependency error is presented:

> "owncloud-8.1.1-12.1.noarch requires owncloud-sever-core = 8.1.1, but this requirement cannot be provided"

I have reproduced this on openSUSE 13.1 x86_64 (with its corresponding repository) and on openSUSE 13.2 x86 and x86_64 (with the above-listed repository). I have also tried this during OS installation and after OS installation (the image below is during installation).

![opensuse - owncloud](https://cloud.githubusercontent.com/assets/13858275/9342748/ce10c75e-45ba-11e5-951c-f88ec74b8cf0.png)

**Comment by PVince81** [comment]
@jnweiger any idea ?

Note that I had no troubles upgrading to 8.1.1 on openSUSE 13.2 x86_64 using the repos.

**Comment by jnweiger** [comment]
Here is where that symbol comes from:
<pre>
wget http://download.opensuse.org/repositories/isv:/ownCloud:/community/openSUSE_13.2/noarch/owncloud-server-8.1.1-12.1.noarch.rpm
rpm -qp --provides owncloud-server-8.1.1-12.1.noarch.rpm
owncloud-enterprise-server = 8.1.1
owncloud-server = 8.1.1-12.1
owncloud-server-core = 8.1.1
</pre>

I'd suspect your mirror did not give you all needed packages. Please test these commands. Probably wget already fails on you...

**Comment by kcoombs** [comment]
I think I sussed it out. When I have been installing openSUSE, I have been using the "Minimal Server Selection (Text Mode)" pattern. The owncloud-server-8.1.1-12.1.noarch.rpm package depends on PHP5. However, it seems that with this minimal sever selection pattern selected, some of the packages upon which PHP5 depends cannot be installed:

> linux-091g:~ # zypper in php5
> Loading repository data...
> Reading installed packages...
> Resolving package dependencies...
> 
> Problem: php5-5.6.1-33.1.x86_64 requires smtp_daemon, but this requirement cannot be provided
>  uninstallable providers: exim-4.83-3.1.8.i586[openSUSE-13.2-0]
>                   msmtp-mta-1.4.32-2.1.3.i586[openSUSE-13.2-0]
>                   postfix-2.11.0-5.2.2.i586[openSUSE-13.2-0]
>                   sendmail-8.14.9-2.2.2.i586[openSUSE-13.2-0]
>                   exim-4.83-3.1.8.x86_64[openSUSE-13.2-0]
>                   msmtp-mta-1.4.32-2.1.3.x86_64[openSUSE-13.2-0]
>                   postfix-2.11.0-5.2.2.x86_64[openSUSE-13.2-0]
>                   sendmail-8.14.9-2.2.2.x86_64[openSUSE-13.2-0]
>                   exim-4.85-3.3.1.i586[repo-update]
>                   exim-4.85-3.3.1.x86_64[repo-update]
>                   postfix-2.11.3-5.5.1.i586[repo-update]
>                   postfix-2.11.3-5.5.1.x86_64[repo-update]
>  Solution 1: deinstallation of patterns-openSUSE-minimal_base-conflicts-20141007-2.1.x86_64
>  Solution 2: do not install php5-5.6.1-33.1.x86_64
>  Solution 3: do not install php5-5.6.1-33.1.x86_64
>  Solution 4: break php5-5.6.1-33.1.x86_64 by ignoring some of its dependencies

Upon selection of the option to deinstall "patterns-openSUSE-minimal_base-conflicts-20141007-2.1.x86_64", everything installs fine.

**Comment by jnweiger** [comment]
@kcoombs thanks for investigating! Now it all makes sense :-)
The pattern:minimal-base-conflicts is often misunderstood:
It does not assert to have at least a minimal system, it tries to assert that the system is only a minimal base system, with nothing added. (That idea never made sense to me anyway.)
