### ISSUE TITLE
PROPPATCH returns 403

### ISSUE THREAD

**Issue by untitaker** [owncloud/core#18409]
*Regression of ownCloud 8.1*

## Steps to reproduce

Run the following using [httpie](https://github.com/jakubroztocil/httpie/):

    echo '<?xml version="1.0" encoding="utf-8" ?><D:propertyupdate xmlns:D="DAV:"><D:set><D:prop><D:displayname>hello world</D:displayname></D:prop></D:set></D:propertyupdate>' | http --auth asdf:asdf proppatch http://127.0.0.1:8080/remote.php/caldav/calendars/asdf/test

## Expected behavior

ownCloud should let me rename my collection.

## Actual behavior

ownCloud rejects the change. As far as I can see, this behavior is not dependent on any server configuration. I can reproduce it on both ArchLinux and Ubuntu.

    HTTP/1.1 207 Multi-Status
    Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
    Connection: close
    Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-s
    rc *; img-src *; font-src 'self' data:; media-src *; connect-src *
    Content-Type: application/xml; charset=utf-8
    Expires: Thu, 19 Nov 1981 08:52:00 GMT
    Host: 127.0.0.1:8080
    Pragma: no-cache
    Set-Cookie: oc6vzxemf45u=4877ed6b63d7617a7ca6a854e1ba4f51; path=/; HttpOnly
    Vary: Brief,Prefer
    X-Content-Type-Options: nosniff
    X-Frame-Options: Sameorigin
    X-Powered-By: PHP/5.6.11
    X-Robots-Tag: none
    X-Sabre-Version: 2.1.6
    X-XSS-Protection: 1; mode=block

    <?xml version="1.0" encoding="utf-8"?>
    <ns0:multistatus xmlns:ns0="DAV:">
        <ns0:response>
            <ns0:href>/remote.php/caldav/calendars/asdf/test</ns0:href>
            <ns0:propstat>
                <ns0:prop>
                    <ns0:displayname />
                </ns0:prop>
                <ns0:status>HTTP/1.1 403 Forbidden</ns0:status>
            </ns0:propstat>
        </ns0:response>
    </ns0:multistatus>

## Further information

I'm posting this on core because many such bugs were introduced when upgrading from 8.0.6 to 8.1.1 for both contacts and calendar. In another instance of this regression, an addressbook was named "{DAV:}displayname". 

In this particular case the problem seems to be that the method updateCalendar
recieves a corrupted array that looks roughly like this:

    0 => "{DAV:}displayname"

instead of this:

    "{DAV:}displayname" => "hello world"

**Comment by MorrisJobke** [comment]
cc @DeepDiver1975

**Comment by untitaker** [comment]
It seems that this is slipping through the cracks -- could somebody take a look at this? This regression essentially makes it impossible to rename addressbooks and calendars. I've edited the issue to roughly follow the issue template.

**Comment by untitaker** [comment]
Thanks @MorrisJobke :beer:

**Comment by PVince81** [comment]
Can you try again with 8.2.1 ?

**Comment by untitaker** [comment]
The exact same behavior is reproducible in 8.2.1.

**Comment by MorrisJobke** [comment]
Isn't this (until 8.2) part of the calendar app?

How has this changed with the move to the core dav endpoint - cc @DeepDiver1975

**Comment by untitaker** [comment]
It is an issue both in the contacts and calendar app, and it's been a problem since 8.1.1. Some major related core refactor must've led to this.

**Comment by PVince81** [comment]
In 8.1 the Sabre library was updated and due to API changes it needed adjusting of core and calendar and contacts. Maybe some adjustments were missing.

You mention a corrupted array, from what I remember the array handling changed in the new Sabre. It is likely that the calendar code needs adjustment to tell it somehow that the property is an array.

@georgehrke any idea ?

**Comment by georgehrke** [comment]
I guess it's related to the array issue mentioned by @untitaker. I'll check.

**Comment by untitaker** [comment]
Did you change anything recently? This issue seems to be fixed, both in CardDAV and CalDAV.

**Comment by georgehrke** [comment]
If by recently you refer to ownCloud 9, yes, we changed a lot concerning everything DAV

**Comment by untitaker** [comment]
I'll close this issue after fully verifying fix. Thanks!

**Comment by untitaker** [comment]
Awesome, everything works.
