### ISSUE TITLE
Cannot access encrypted Data after updating to 8.1/8.11 

### ISSUE THREAD

**Issue by teconomix** [owncloud/core#18401]
Hi,

we did update out encrypted owncloud installation from 8.04 to 8.1, losing access to the encrypted data. 

My co-admin tried to restore access, following https://github.com/owncloud/core/issues/17574
He got as far as being able to access his data again, but strangely he could not upload new files via the web interface. Updating to 8.1.1 solved the issue for him. 
I was on vacation and just came back – and unfortunately my account does not work. It seems like I cannot access the encrypted data, while his account works just fine.
So I repeated the instructions from #17574, copying the old key files and the old key structure and then starting the migration again. But it is still not working.

When I log into my account I get the following messages:

> Die Verschlüsselung-App ist aktiviert, aber Deine Schlüssel sind nicht initialisiert. Bitte melde Dich nochmals ab und wieder an. (encryption activated, please sign off and on) 

When I try to upload a file in the web interface I end up with a 0kb file in my ownCloud and get the error:

> Private Key missing for user: please try to log-out and log-in again

When I try to download a file I get:

> Can't read file

Signing on and off did not help 

The desktop client does not connect at all and reports “forbidden” 
the android clients show the file and folder structure but fails’ to up- or download anything.

What can I do? How can I regain access to my files? Why is there one working account and another one not working?

Thank you! :)

**Comment by karlitschek** [comment]
@schiesbn any idea?

**Comment by PVince81** [comment]
@teconomix when upgrading to 8.1.1, did you follow the instructions that tells to enable the default encryption module and run the migration routine ?

**Comment by teconomix** [comment]
Yes we did the migration and we repeated the process several times since then...

**Comment by PVince81** [comment]
Have you been able to upgrade meanwhile ?
