### ISSUE TITLE
Length parameter must be greater than 0

### ISSUE THREAD

**Issue by kF13Ld** [owncloud/core#18402]
As suggested by the [forum](https://forum.owncloud.org/viewtopic.php?f=31&t=29894), I am opening a new ticket.

When setting up a fresh client installation, the initial download of the content fails with "Operation canceled" and "Connection closed", while just a few files could successfully be downloaded.
The problem remains with linux and windows clients, always version 1.8.4.

In my owncloud.log on the server (Debian Squeeze, apache2, php 5.6.9, ownCloud 8.1.1) I see several lines like this:

`fread(): Length parameter must be greater than 0 at /var/www/owncloud/apps/files_external/3rdparty/icewind/streams/src/Wrapper.php#67`

The server has been running ownCloud since version 2 or 3 and always been upgraded and working fine until now. I don't know, what changed...

Encryption is enabled and has been migrated to 8.1 a couple of weeks ago.

Any hints?

**Comment by karlitschek** [comment]
@icewind1991 Your code. :-) Any idea?

**Comment by PVince81** [comment]
@kF13Ld can you provide more information about your env ? Are you using encryption ?
See issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by PVince81** [comment]
Okay, I see you are mentionned using encryption.

I guess the log doesn't contain more information, a stack trace maybe ?

@schiesbn does this ring any bells ?

**Comment by icewind1991** [comment]
@kF13Ld can you get a stracktrace? without it it's pretty much impossible to tell where this error is coming from

**Comment by kF13Ld** [comment]
Stack trace of what? Client or server? How do I do either?

**Comment by kF13Ld** [comment]
Here is some additional information:

**List of activated apps:**
Enabled:
 - activity: 2.0.1
 - encryption: 1.0.0
 - files: 1.1.10
 - files_external: 0.2.3
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - templateeditor: 0.1
Disabled:
 - bookmarks
 - calendar
 - contacts
 - documents
 - external
 - files_locking
 - provisioning_api
 - user_external
 - user_ldap
 - user_webdavauth

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => '555555555555',
  'passwordsalt' => 'aaaaaaaa',
  'datadirectory' => '/var/www/owncloud_data',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'dbname' => 'ownc',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'aaaa',
  'dbpassword' => 'Password,
  'installed' => true,
  'maxZipInputSize' => 0,
  'allowZipDownload' => true,
  'forcessl' => true,
  'maintenance' => false,
  'theme' => '',
  'log_type' => 'owncloud',
  'loglevel' => 3,
  'logfile' => 'owncloud.log',
  'logtimezone' => 'Europe/Berlin',
  'log_query' => false,
  'trusted_domains' =>
  array (
    0 => 'oc.example.org',
    1 => 'oc.example.org',
  ),
  'secret' => 'aaaaaaaaaaaaaaaaaaaaaaa',
  'memcache.local' => '\\OC\\Memcache\\APCu',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** 
No

### Client configuration
**Operating system:**
Windows 10 and Kubuntu 15.04, v1.8.4 each

### Logs
#### Web server error log: 
Apache access-log containing lots of PROPFINDs
```
"PROPFIND /remote.php/webdav/random_file HTTP/1.1" 207 2225 "-" "Mozilla/5.0 (Linux) mirall/1.8.4"
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"DYOEZsMAyWWX7jaBHSNU","remoteAddr":"AAA.BBB.CCC.DDD","app":"PHP","message":"fread(): Length parameter must be greater than 0 at \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php#67","level":3,"time":"2015-08-19T21:29:49+02:00"}
```

**Comment by kF13Ld** [comment]
Also I recently enabled the caching and disabled it temporarily by uncommenting " 'memcache.local' => '\OC\Memcache\APCu'," in config.php, but this did not help.

**Comment by kF13Ld** [comment]
I couldn't live without a working ownCloud setup, so I deleted the MySQL tables and started over with a new installation. 
The upload of all the files is still in progress, but so far it seems, as if it's working now. Don't know what resulted in the above error.
