### ISSUE TITLE
Synchronising Calendars with CalDAV / CalendarSync

### ISSUE THREAD

**Issue by Gasmann0815** [owncloud/core#18400]
Steps to reproduce:
Upgrade to 7.0.4 -> 8.0.3/8.1.1 https://github.com/owncloud/core/issues/16737

Android Calendar syncing is not possible 

Server configuration
HP Proliant Mircoserver - AMD Turion(tm) II Neo N54L Dual-Core Processor
Freenas Jail
https://forums.freenas.org/index.php?threads/drkks-definitive-guide-to-installing-owncloud-in-freenas-or-freebsd.19605/

Operating system:
FreeNAS-9.3-STABLE-201505040117

Web server:
lighttpd-1.4.35_5

Database:
3.8.10.2 2015-05-20 18:17:19 

PHP version:
PHP Version 5.6.11

ownCloud version: 
ownCloud 8.1.1 (stable) 

List of activated apps:
Only Core Apps

The content of config/config.php:
$CONFIG = array (
  'instanceid' => 'ocyzlawmg3e3',
  'passwordsalt' => 'xxxx',
  'secret' => 'xxx',
  'trusted_domains' => 
  array (
    0 => '192.168.2.10',
  ),
  'datadirectory' => '/usr/local/www/owncloud/data',
  'overwrite.cli.url' => 'http://192.168.2.10',
  'dbtype' => 'sqlite3',
  'version' => '8.1.1.3',
  'installed' => true,
  'loglevel' => 1,
  'theme' => '',
  'maintenance' => false,
);

No external storage, no encyprytion
external user-bachend: webfrontend, android: caldav calendar-sync carddav-sync

ownCloud log (data/owncloud.log)
Fatal 	caldav 	Exception: {"Message":"HTTP\/1.1 403 This calendar only supports 0. We found a VEVENT","Code":0,"Trace":"#0 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Plugin.php(832): Sabre\\CalDAV\\Plugin->validateICalendar('BEGIN:VCALENDAR...', 'calendars\/rolf\/...', false, Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response), true)\n#1 [internal function]: Sabre\\CalDAV\\Plugin->beforeCreateFile('calendars\/rolf\/...', 'BEGIN:VCALENDAR...', Object(OC_Connector_Sabre_CalDAV_Calendar), false)\n#2 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#3 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1051): Sabre\\Event\\EventEmitter->emit('beforeCreateFil...', Array)\n#4 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(513): Sabre\\DAV\\Server->createFile('calendars\/rolf\/...', Resource id #319, NULL)\n#5 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#6 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#7 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#8 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#9 \/usr\/local\/www\/owncloud\/apps\/calendar\/appinfo\/remote.php(57): Sabre\\DAV\\Server->exec()\n#10 \/usr\/local\/www\/owncloud\/remote.php(132): require_once('\/usr\/local\/www\/...')\n#11 {main}","File":"\/usr\/local\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Plugin.php","Line":912}

**Comment by karlitschek** [comment]
please open this in the calendar repository. thanks.
