### ISSUE TITLE
in_array() expects parameter 2 to be array, string given at /lib/private/files/filesystem.php#607

### ISSUE THREAD

**Issue by thehijacker** [owncloud/core#18405]
I can see lots of error of this string:

in_array() expects parameter 2 to be array, string given at /lib/private/files/filesystem.php#607

They come from URL at work where I only use Windows client and the web interface. I also noticed that this error comes from my home router IP 192.168.0.10 where my Ubuntu 14.04 LTS server with owncloud is.

Everything is still working but the error message fills the log files.

Let me know if I can help pin-point the problem any further.

**Comment by karlitschek** [comment]
@icewind1991 We get several reports for that. and idea?

**Comment by thehijacker** [comment]
I have enabled debug log level and I get now this:

{"reqId":"BfHrrJTnWdwlI07\/7ECb","remoteAddr":"192.168.0.10","app":"PHP","message":"in_array() expects parameter 2 to be array, string given at \/home\/sysadmin\/Data\/OwnCloud_WWW\/lib\/private\/files\/filesystem.php#607","level":3,"time":"August 18, 2015 21:27:21","method":"GET","url":"\/owncloud\/index.php\/settings\/admin"}
{"reqId":"BfHrrJTnWdwlI07\/7ECb","remoteAddr":"192.168.0.10","app":"PHP","message":"in_array() expects parameter 2 to be array, string given at \/home\/sysadmin\/Data\/OwnCloud_WWW\/lib\/private\/files\/filesystem.php#607","level":3,"time":"August 18, 2015 21:27:22","method":"GET","url":"\/owncloud\/index.php\/settings\/admin"}
{"reqId":"BfHrrJTnWdwlI07\/7ECb","remoteAddr":"192.168.0.10","app":"PHP","message":"in_array() expects parameter 2 to be array, string given at \/home\/sysadmin\/Data\/OwnCloud_WWW\/lib\/private\/files\/filesystem.php#607","level":3,"time":"August 18, 2015 21:27:22","method":"GET","url":"\/owncloud\/index.php\/settings\/admin"}
{"reqId":"I01HaK6QPyJTbzlUsols","remoteAddr":"192.168.0.10","app":"PHP","message":"in_array() expects parameter 2 to be array, string given at \/home\/sysadmin\/Data\/OwnCloud_WWW\/lib\/private\/files\/filesystem.php#607","level":3,"time":"August 18, 2015 21:27:24","method":"GET","url":"\/owncloud\/index.php\/avatar\/admin\/166.95XX?requesttoken=XX"}
{"reqId":"I01HaK6QPyJTbzlUsols","remoteAddr":"192.168.0.10","app":"PHP","message":"in_array() expects parameter 2 to be array, string given at \/home\/sysadmin\/Data\/OwnCloud_WWW\/lib\/private\/files\/filesystem.php#607","level":3,"time":"August 18, 2015 21:27:24","method":"GET","url":"\/owncloud\/index.php\/avatar\/admin\/166.95XX?requesttoken=XX"}
{"reqId":"0rQBUfbjVwyvxbWNaEcD","remoteAddr":"192.168.0.10","app":"PHP","message":"in_array() expects parameter 2 to be array, string given at \/home\/sysadmin\/Data\/OwnCloud_WWW\/lib\/private\/files\/filesystem.php#607","level":3,"time":"August 18, 2015 21:27:24","method":"GET","url":"\/owncloud\/index.php\/settings\/ajax\/checksetup"}
{"reqId":"0rQBUfbjVwyvxbWNaEcD","remoteAddr":"192.168.0.10","app":"PHP","message":"in_array() expects parameter 2 to be array, string given at \/home\/sysadmin\/Data\/OwnCloud_WWW\/lib\/private\/files\/filesystem.php#607","level":3,"time":"August 18, 2015 21:27:27","method":"GET","url":"\/owncloud\/index.php\/settings\/ajax\/checksetup"}

I had the web interface opened and refreshed this files page. Does this help?

**Comment by Xenopathic** [comment]
Can you post your config.php? With the secret parameters removed of course.

**Comment by thehijacker** [comment]
Gladly.

<?php
$CONFIG = array (
  'instanceid' => 'XX',
  'passwordsalt' => 'XX',
  'secret' => 'XX',
  'trusted_domains' =>
  array (
    0 => 'domain.info:580',
    1 => 'domain.info:680',
    2 => 'domain.info'
  ),
  'datadirectory' => '/home/sysadmin/Data/OwnCloud',
  'overwrite.cli.url' => 'http://domain.info:580/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'installed' => true,
  'enable_previews' => false,
  'mail_from_address' => 'XX',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'domain.info',
  'blacklisted_files' => '',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'maintenance' => false,
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbuser' => 'owncloud',
  'dbpassword' => 'XX',
  'loglevel' => 2,
  'logdateformat' => 'F d, Y H:i:s',
  'logtimezone' => 'Europe/Ljubljana',
  'log_rotate_size' => 26214400,
  'forcessl' => true,
);

**Comment by Xenopathic** [comment]
Your value of 'blacklisted_files' is incorrect, it must be an array. Either remove it, or replace it with an empty array: `'blacklisted_files' => [],`

**Comment by thehijacker** [comment]
Oh my. Sorry about that. I was trying to remove the .htaccess file sync ban that of course did not work and left this setting in config.php. That error is now gone. The only error I see now was already reported:

{"reqId":"Ey4GnBs1ad4WUkuKo8xP","remoteAddr":"192.168.0.10","app":"PHP","message":"Array to string conversion at \/home\/sysadmin\/Data\/OwnCloud_WWW\/lib\/private\/template\/functions.php#36","level":3,"time":"August 18, 2015 22:09:29","method":"GET","url":"\/owncloud\/index.php\/settings\/admin"}

But that error is not showing that often. So I can wait for a fix. Thank you!

**Comment by Xenopathic** [comment]
Excellent, we'll keep the relevant discussions for that bug in the appropriate issue. Glad to help!

**Comment by RealRancor** [comment]
@Xenopathic Is there anything what could be done to detect such broken config options as its not clear from the error message that this is a problem within the config?

**Comment by Xenopathic** [comment]
@RealRancor We document that particular option as 'only use this if you REALLY know what you are doing', and besides, it's easy to see the problem if you read the surrounding 5 lines of the error.

The ultimate solution would be some kind of validation logic in Config, such that if the default parameter is an `array`, the returned value must also be an `array` (e.g. if the config contains a string, return the default or wrap it in an array so the value is sane). The same would apply for other value types: numeric, string, array.

**Comment by RealRancor** [comment]
@Xenopathic 
> We document that particular option as 'only use this if you REALLY know what you are doing', and besides, it's easy to see the problem if you read the surrounding 5 lines of the error.

Not that easy if you're not familiar with that coding stuff. We had the OP posted this at the forums and there we just don't have the knowledge for this.
