### ISSUE TITLE
Server generates no picture preview-thumbnails on request from Android-app

### ISSUE THREAD

**Issue by suparol** [owncloud/core#18417]
Worked fine since owncloud 8.0, but is broken  since update to 8.1.1
No issue when  using Webinterface, but inside the Android-APP its broken.

If the Webinterface has once generated the previews for a folder, then the previews inside the APP also work for this single folder.

attached please find my email correspondence with owncloud-App Team

okay i did several tests on this:
 
1. positive result
if it is a folder which i had already opened before from the web interface, then there is  a small thumbnail picture on the location you pointed me to. 
 
http://**mydomain**.com/owncloud/index.php/apps/files/api/v1/thumbnail/25/25/pictures/20150819/20150819_08-28__37/20150819_08-28-01__00.jpg
 
 
2. negative result
if it is a folder which i had NOT opened before from the web interface, then there is NO thumbnail picture on the location you pointed me to. Even if i navigate to the folder inside the app to trigger the preview, there is no thumbnail generated on the server location you pointed me to.
 
http://**mydomain**.com/owncloud/index.php/apps/files/api/v1/thumbnail/25/25/pictures/20150819/20150819_05-54__26/20150819_05-54-52__00.jpg
 
3. finally positive from number 2
if i go to the same folder used under point 2 in the webinterface, then there is a thumbnail generated and can be found on the location you pointed me to. If i try to open the folder from the app afterwards, preview-pictures work fine inside the app... so i always have to load it in the webinterface first in order to have the app picture preview working. 
 
http://**mydomain**.com/owncloud/index.php/apps/files/api/v1/thumbnail/25/25/pictures/20150819/20150819_05-54__26/20150819_05-54-52__00.jpg
 
2015-08-19 8:59 GMT+02:00 Raquel Perez <apps@owncloud.com>:
Can you please try something?

>From the web browser access to: server/index.php/apps/files/api/v1/thumbnail/25/25/PATH

Your path would be something such as:
20150819/20150819_08-28_37/20150819_08-28-01_00.jpg

Is the thumbnail shown?

Kind regards,

Raquel Perez
Your ownCloud Team!

--
apps@owncloud.com
ownCloud Inc. - http://www.owncloud.com

Your Data, Your Cloud, Your Way!

19/08/2015 - 02:50 - me escribió:
Attached  you find a Screenshot Form the filenames. The folderstructure is generated automatically using date and time + event number from a Webcam.
Files are named the same way.

Worked fine since owncloud 8.0, but is broken  since update to 8.1.1

No issue when  using Webinterface, but inside the APP its broken.

If the Webinterface has once generated the previews for a folder, then the previews inside the APP also work for this single folder.

Am 19.08.2015 08:38 schrieb "Raquel Perez" <apps@owncloud.com>:
Thanks for reporting this.

Is it broken for every image?

We are aware of a issue related to images whose names contains special characters.

We'd appreciate further details, from our end, it´s working.

Thanks,

Kind regards,

Raquel Perez
Your ownCloud Team!

--
apps@owncloud.com
ownCloud Inc. - http://www.owncloud.com

Your Data, Your Cloud, Your Way!

18/08/2015 - 17:00 - me escribió:
Picture Preview is broken  with owncloud 8.1.1 Server! APP displays no preview pictures.

**Comment by PVince81** [comment]
Did you upgrade from 8.1.0 and had encryption enabled ?

**Comment by PVince81** [comment]
Are you able to download these files with the Android client ?
Are these shared files ?

**Comment by suparol** [comment]
No the files are directy from my owncloud account
Am 19.08.2015 14:07 schrieb "Vincent Petry" <notifications@github.com>:

**Comment by suparol** [comment]
And yes i can download them  from the Android APP, independent of usage of
the Webinterface before downloading. Only previews dont work, download is
fine.
Am 19.08.2015 14:07 schrieb "Vincent Petry" <notifications@github.com>:

**Comment by suparol** [comment]
I upgraded from 8.04 to 8.1.1 via Distribution packages (apt-get
update/upgrade)

I never had  encryption active
Am 19.08.2015 14:06 schrieb "Vincent Petry" <notifications@github.com>:

**Comment by PVince81** [comment]
Ok thanks for the info. Then this is not an issue I heard of.

**Comment by PVince81** [comment]
@oparoz @georgehrke

**Comment by oparoz** [comment]
It's been reported before, but there is a mix of bugs.

@suparol - Could you try the same test, but with files with simple names? test.jpg per example.

**Comment by suparol** [comment]
Not even test.jpg works, sorry!
Am 19.08.2015 15:21 schrieb "Olivier Paroz" <notifications@github.com>:

**Comment by tobiasKaminsky** [comment]
@oparoz Is there something I can help/debug you with?

**Comment by tobiasKaminsky** [comment]
Additional info: For me this only happens if a sharee opens a folder, which he did not open with webUI.
The owner of the folder can see the thumbnails right away.

**Comment by PVince81** [comment]
Is this fixed in 9.1.0 beta2 ?

There was something slightly related here https://github.com/owncloud/core/issues/21173 that was fixed

**Comment by PVince81** [comment]
Please reopen if the issue still exists in the upcoming 8.2.6, 9.0.3 or the current 9.1.0 beta2.
The PR that might fix this is here: https://github.com/owncloud/core/pull/24564
