### ISSUE TITLE
Updates between multiple major versions are unsupported.

### ISSUE THREAD

**Issue by nicoverbaan** [owncloud/core#18413]
Installing owncloud on my QNAP, I get this message. I need to update (only choice when I try to logon) and it's about updating to 8.0.4. Please help me out.

**Comment by DeepDiver1975** [comment]
You need to upgrade one by one major Version.

5 > 6 > 7 > 8

**Comment by RealRancor** [comment]
@nicoverbaan We had a lot of such reports of Qnap users at the forum. Please contact their support again and make them aware that they can't skip versions within their plugin.
