### ISSUE TITLE
Update to 8.1.1

### ISSUE THREAD

**Issue by lesiah** [owncloud/core#18419]
Hie trying to update but getting the below error.

Doctrine\DBAL\Exception\ConnectionException: An exception occurred while executing 'DROP TABLE `oc_oc_appconfig_wzn8w0pxfumgz`': SQLSTATE[42000]: Syntax error or access violation: 1142 DROP command denied to user 'owncloud'@'localhost' for table 'oc_oc_appconfig_wzn8w0pxfumgz'

**Comment by DeepDiver1975** [comment]
> DROP command denied to user 'owncloud'@'localhost'

you need to grant that use the necessary rights

**Comment by lesiah** [comment]
Done thanks
