### ISSUE TITLE
Issues with ownCloud 8.1.1

### ISSUE THREAD

**Issue by thejrose1984** [owncloud/core#18429]
Recently had to redo my setup, which included an instance of ownCloud running from a FreeNAS Jail. Currently running with the following:

FreeNAS 9.3 Jail
ownCloud 8.1.1
Apache 2.4
PHP 5.6
MariaDB 5.5 (hosted from another jail on FreeNAS)

I tried RTFM but finding there are issues that either won't go away or can't be explained. Specifically, I couldn't get LDAP to work (it was fine previously when running PHP 5.6, ownCloud 8.0.2, MariaDB 5.5, Lighttpd 1.4.2). I gave up on LDAP not working and dismissed it to the Directory Server that was running from a Synology box.

The main issue now is that even with users and groups setup within ownCloud Admin and mapping FreeNAS datasets to the respective 'files' directories, I am noticing that it doesn't show all files from the directory. The files are acknowledged (can confirm via item count), but from the WebGUI, they're invisible. I have no idea if this is an issue with Apache, PHP, ownCloud, or some combination of the above. What logs do I need to provide and/or look through to investigate further (I'm assuming the ownCloud and Apache logs, but want to confirm before submitting).

**Comment by MorrisJobke** [comment]
@thejrose1984 Can you try to run the filescan command?

```
./occ files:scan
```

Keep in mind to run this as the web server user: https://doc.owncloud.org/server/8.1/admin_manual/configuration_server/occ_command.html#run-occ-as-your-http-user

**Comment by MorrisJobke** [comment]
Is there anything in your owncloud.log inside your `data` directory?

**Comment by thejrose1984** [comment]
I can run OCC fine when I do this:
`cd /usr/local/www/owncloud`
`sudo -u www php occ files:scan --all`

Here is the owncloud log:
http://pastebin.com/Qek30pRB

**Comment by MorrisJobke** [comment]
The only notable log entries are:
```
{"reqId":"RihLSxJ9UCpBS29VAIK1","remoteAddr":"192.168.1.14","app":"PHP","message":"Array to string conversion at \/usr\/local\/www\/owncloud\/lib\/private\/template\/functions.php#36","level":3,"time":"2015-08-19T03:03:31+00:00","method":"GET","url":"\/index.php\/settings\/admin"}
{"reqId":"BgKukjj0YwHxu+F+fzzu","remoteAddr":"192.168.1.14","app":"PHP","message":"Array to string conversion at \/usr\/local\/www\/owncloud\/lib\/private\/template\/functions.php#36","level":3,"time":"2015-08-19T03:06:06+00:00","method":"GET","url":"\/index.php\/settings\/admin"}
{"reqId":"TOLiFwEQmGVkwGrQznn8","remoteAddr":"192.168.1.14","app":"PHP","message":"Array to string conversion at \/usr\/local\/www\/owncloud\/lib\/private\/template\/functions.php#36","level":3,"time":"2015-08-19T03:10:06+00:00","method":"GET","url":"\/index.php\/settings\/admin"}
{"reqId":"gXZ2qZ8yTg\/cSYir3l+x","remoteAddr":"192.168.1.14","app":"PHP","message":"Array to string conversion at \/usr\/local\/www\/owncloud\/lib\/private\/template\/functions.php#36","level":3,"time":"2015-08-19T03:46:15+00:00","method":"GET","url":"\/index.php\/settings\/admin"}
{"reqId":"PYYPOVw1HeolnUdDibLu","remoteAddr":"192.168.1.14","app":"PHP","message":"rename(\/ocdata\/thejrose1984\/files\/desktop\/.DS_Store,\/ocdata\/thejrose1984\/files_trashbin\/files\/.DS_Store.d1439987668): Operation not permitted at \/usr\/local\/www\/owncloud\/lib\/private\/files\/storage\/local.php#245","level":3,"time":"2015-08-19T12:34:28+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/delete.php"}
{"reqId":"1fZzVuYKiAFl5b5mlv2C","remoteAddr":"192.168.1.14","app":"PHP","message":"imagecreatefromstring(): Data is not in a recognized format at \/usr\/local\/www\/owncloud\/lib\/private\/image.php#571","level":3,"time":"2015-08-19T12:34:42+00:00","method":"GET","url":"\/index.php\/core\/preview.png?file=%2Fdownloads%2Fo-WET-KOALA-PHOTOSHOP-570.jpg&c=faff393f7ef14893ff400d05b9265595&x=36&y=36&forceIcon=0"}
{"reqId":"fYHPcMbLpI9oAAkS675W","remoteAddr":"192.168.1.14","app":"PHP","message":"imagecreatefromstring(): Data is not in a recognized format at \/usr\/local\/www\/owncloud\/lib\/private\/image.php#571","level":3,"time":"2015-08-19T12:34:43+00:00","method":"GET","url":"\/index.php\/core\/preview.png?file=%2Fdownloads%2Fngbbs50f4ecd976b78.jpg&c=6a98e20cae24b88a259e8526bca94089&x=36&y=36&forceIcon=0"}
{"reqId":"bMcURTT2MC3enmCE0Izj","remoteAddr":"192.168.1.14","app":"PHP","message":"imagecreatefromstring(): Data is not in a recognized format at \/usr\/local\/www\/owncloud\/lib\/private\/image.php#571","level":3,"time":"2015-08-19T12:34:43+00:00","method":"GET","url":"\/index.php\/core\/preview.png?file=%2Fdownloads%2Fo-WET-KOALA-PHOTOSHOP-570.jpg&c=faff393f7ef14893ff400d05b9265595&x=36&y=36&forceIcon=0"}
{"reqId":"xOXfjvqUKiErk7MyEFlY","remoteAddr":"192.168.1.14","app":"PHP","message":"imagecreatefromstring(): Data is not in a recognized format at \/usr\/local\/www\/owncloud\/lib\/private\/image.php#571","level":3,"time":"2015-08-19T12:34:43+00:00","method":"GET","url":"\/index.php\/core\/preview.png?file=%2Fdownloads%2Fngbbs50f4ecd976b78.jpg&c=6a98e20cae24b88a259e8526bca94089&x=36&y=36&forceIcon=0"}
{"reqId":"KZS6hLgLau6Lrgrku1U9","remoteAddr":"192.168.1.14","app":"PHP","message":"imagecreatefromstring(): Data is not in a recognized format at \/usr\/local\/www\/owncloud\/lib\/private\/image.php#571","level":3,"time":"2015-08-19T12:34:46+00:00","method":"GET","url":"\/index.php\/core\/preview.png?file=%2Fdownloads%2Ftrollface.jpg&c=7e73a994ab8024d87c4e6840dd8b8436&x=36&y=36&forceIcon=0"}
{"reqId":"Cxl2qqO+1ykipnNJ6Au7","remoteAddr":"192.168.1.14","app":"PHP","message":"imagecreatefromstring(): Data is not in a recognized format at \/usr\/local\/www\/owncloud\/lib\/private\/image.php#571","level":3,"time":"2015-08-19T12:34:46+00:00","method":"GET","url":"\/index.php\/core\/preview.png?file=%2Fdownloads%2Ftrollface.jpg&c=7e73a994ab8024d87c4e6840dd8b8436&x=36&y=36&forceIcon=0"}
{"reqId":"XhVreFqrdIiEk9rLFnkm","remoteAddr":"192.168.1.14","app":"PHP","message":"Array to string conversion at \/usr\/local\/www\/owncloud\/lib\/private\/template\/functions.php#36","level":3,"time":"2015-08-19T12:44:02+00:00","method":"GET","url":"\/index.php\/settings\/admin"}
{"reqId":"FfLcI6Elwwg5x63A9Nr0","remoteAddr":"192.168.1.14","app":"PHP","message":"Array to string conversion at \/usr\/local\/www\/owncloud\/lib\/private\/template\/functions.php#36","level":3,"time":"2015-08-19T12:47:43+00:00","method":"GET","url":"\/index.php\/settings\/admin"}
{"reqId":"M\/iC7yKZv1d7obJbf1P2","remoteAddr":"192.168.1.14","app":"PHP","message":"Array to string conversion at \/usr\/local\/www\/owncloud\/lib\/private\/template\/functions.php#36","level":3,"time":"2015-08-19T13:23:24+00:00","method":"GET","url":"\/index.php\/settings\/admin"}
```

**Comment by MorrisJobke** [comment]
> I can run OCC fine when I do this:

Did the missing files show up?

**Comment by thejrose1984** [comment]
No, I ran that command two or three times last night

**Comment by thejrose1984** [comment]
Ran again just now - the files are "there" but are not visible. I only know something is there because of the scroll bar and when I hover over an "invisible" item, I can see the file name mentioned during the file scan.

**Comment by thejrose1984** [comment]
Keep in mind this is a fresh install, so if there's a PHP setting I overlooked, please advise because I have already checked documentation and could not find anything relevant. As it is, I'm having a hard time sorting out memcache warnings (which is another issue altogether).

**Comment by MorrisJobke** [comment]
@PVince81 @icewind1991 Can you help out with files not showing up in ownCloud?

**Comment by PVince81** [comment]
Are the files listed in the `oc_filecache` table ?
Are you using the data folder outside of ownCloud or exclusively through ownCloud ?

Can you explain what you mean that "files are invisible" ? Are the DOM elements rendered in the web UI but set to hidden ?

**Comment by thejrose1984** [comment]
No (see below)
![2015-08-19 09_56_40-sql-rosekp _ localhost _ owncloud _ oc_filecache _ phpmyadmin 4 4 13 1](https://cloud.githubusercontent.com/assets/7573083/9358168/a84dc4ec-4658-11e5-9b06-13068ddcc42e.png)

As for what I mean by invisible...see below
![2015-08-19 09_57_57-](https://cloud.githubusercontent.com/assets/7573083/9358208/ce324386-4658-11e5-8780-8d58c56a5df1.png)
If you look in the lower left hand corner, you can see the file is acknowledged, but doesn't get displayed (no preview). Meanwhile I can access the file just fine.

**Comment by MorrisJobke** [comment]
Ah....so they are listed, but are hidden by something. What apps do you have enabled?

Can you inspect the HTML? (right click -> inspect - at least in firefox and chrome)

**Comment by PVince81** [comment]
Can you check the Javascript console for errors ?

This looks like similar to https://github.com/owncloud/core/issues/15856 but that one was fixed in 8.1.1 already.

**Comment by thejrose1984** [comment]
Wait, I just thought of something...permissions wise I have 750, could it be as simple as that? Should I try `chmod 755` to see if that helps?

**Comment by thejrose1984** [comment]
Nevermind - I disabled the Sharing App (no clue why this helped, but it was noted in [#15856] (https://github.com/owncloud/core/issues/15856) so I didn't have to change file permissions. Now to sort out memcache warnings and getting my SSL Cert installed in Apache...
