### ISSUE TITLE
getAppFolder() is not compatible with composer binaries

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#18421]
One more case illustrating how broken getAppFolder() is.

### Steps to reproduce

1. Write a test for an app named `myapp`
2. Use `$this->server->getAppFolder()->getPath()` 
3. Launch the test from the apps's root folder using `vendor/bin/sometool`

### Expected result

`/myapp` ?

### Actual result

`endor/`

**Comment by DeepDiver1975** [comment]
@oparoz  By chance you have the code at hand? THX

**Comment by PVince81** [comment]
@VicDeo @georgehrke anything we can do here ?

**Comment by georgehrke** [comment]
Not sure I can follow that this has to do with composer binaries 😕 
Some example code would really help here.

ping @oparoz

**Comment by DeepDiver1975** [comment]
> @oparoz By chance you have the code at hand? THX
> @cmonteroluque

it is totally unclear what this is about @oparoz please reopen once more information is availble - THX a lot
