### ISSUE TITLE
Can't upgrade with recommended permissions

### ISSUE THREAD

**Issue by nazar-pc** [owncloud/core#18436]
ownCloud 8.1.0 was installed as Docker container using [image](https://github.com/nazar-pc/docker-webserver-apps/tree/master/owncloud) and [recommended permissions](https://doc.owncloud.org/server/8.1/admin_manual/installation/installation_wizard.html#setting-strong-directory-permissions).
While everything is set as recommended, upgrade from administration panel to 8.1.1 fails because there is no write access to many files and directories.
So either documentation should be updated, or it should be possible to run `occ` under root and upgrade instance from terminal.
List of files that doesn't have write access: http://pastebin.com/cf8Uv0f9

**Comment by karlitschek** [comment]
This seems to be a packaging problem with your container or other packages or the way is is manually installed. Nothing we can do from inside ownCloud.
Please report this to whoever provided your container.

**Comment by nazar-pc** [comment]
I did that container, permissions were set as recommended in official administrator guide, and with that OFFICIAL permissions it is impossible to update ownCloud.
You need either to update documentation (section about permissions setting) or allow to run `occ` from root and upgrade ownCloud instance leaving permissions as is.

**Comment by nazar-pc** [comment]
There is very simple set of commands to install ownCloud - just extract official archive, apply officially recommended permissions and copy autoconfig file to finish installation on first visit:
https://github.com/nazar-pc/docker-webserver-apps/blob/master/owncloud/installer/Dockerfile

**Comment by RealRancor** [comment]
Hi,

its documented here:

https://doc.owncloud.org/server/8.1/admin_manual/maintenance/update.html#setting-strong-permissions

that you need to change the permissions back if you want to use the updater.

**Comment by nazar-pc** [comment]
Wow, thanks, @RealRancor
