### ISSUE TITLE
ownCloud tells me HSTS is not enabled

### ISSUE THREAD

**Issue by stonerl** [owncloud/core#18443]
### Steps to reproduce
1. Goto the Admin page and look for Security Issues,

### Expected behaviour
There shouldn't be a warning about HSTS.

### Actual behaviour
I get a warning that HSTS is not enabled. But when I [check my page] (https://www.ssllabs.com/ssltest/analyze.html?d=rokuhara.japanologie.kultur.uni-tuebingen.de) on Qualys SSL Labs Tests  it says it is enabled.

### Server configuration
**Operating system**: Ubuntu 14.04.3

**Web server:** Apache/2.4.7

**Database:** mysql  Ver 14.14 Distrib 5.5.44, for debian-linux-gnu (x86_64) using readline 6.3

**PHP version:** PHP 5.5.9-1ubuntu4.11

**ownCloud version:** 8.1.1

**Updated from an older ownCloud or fresh install:** upgrade from 8.0.6

**List of activated apps:**

```
 - activity: 2.0.1
 - calendar: 0.7.3
 - contacts: 0.4.0.0
 - conversations: 0.2.2
 - documents: 0.10.1
 - files: 1.1.10
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - firstrunwizard: 1.1
 - mail: 0.1.3
 - polls: 0.6.2
 - provisioning_api: 0.2
 - tasks: 0.6.0
 - user_external: 0.4
```
**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** IMAP

**Comment by Xenopathic** [comment]
According to the SSL Labs report you linked, your HSTS value is set to something rather strange:

> ���max-age=31556926���

I don't think ownCloud (or any browser for that matter) likes those funny characters. Please check your web server configuration.

**Comment by stonerl** [comment]
@Xenopathic You were totally right, I used the wrong quotation marks in the Apache config. Sorry for opening this pointless  issue.
