### ISSUE TITLE
php5-redis in Ubuntu 14.04 is too old for ownCloud

### ISSUE THREAD

**Issue by Xenopathic** [owncloud/core#18442]
I don't know what the final conclusion was for the APCu backport, but we have the same situation with the Redis PHP module. ownCloud requires 2.2.5, Ubuntu 14.04 only provides 2.2.4.

@jnweiger Your call :smile:

**Comment by karlitschek** [comment]
grmpf. so had would it be for us to also support 2.2.4 ?
otherwise i don't think this is a huge problem because ubuntu is not really an enterprise distribution and redis is mot of the time used in bigger enterprise installations.

**Comment by Xenopathic** [comment]
There is a crash fix in 2.2.5, so we require that

**Comment by jnweiger** [comment]
My prefered solution would be to push all python packages we need into 
https://build.opensuse.org/project/requests/server:php:extensions

**Comment by PVince81** [comment]
Is that still the case right now ? Does Ubuntu update minor versions ?

**Comment by jnweiger** [comment]
Still an issue.
This also bites the appliance. We cannot use 2.2.4 there.
If 2.2.4 is installed, owncloud will explode with a white screen, leaving the impression that apache is not properly configured.
http://s13.postimg.org/s7pvtg5rr/image.png

**Comment by jnweiger** [comment]
https://build.opensuse.org/package/show/isv:ownCloud:devel/php5-redis builds 2.2.7 for Ubuntu 14.04
taken from home:lrupp php5-redis ...
