### ISSUE TITLE
SMB External Storage over WebDav in 8.1+

### ISSUE THREAD

**Issue by jrh7675** [owncloud/core#18448]
Hi. I don't know if this it the right protocol or whatever but I thought I'd try.... I've sort of been struggling with an issue since 8.1 (including 8.1.1) and I'm at my wit's end.

I've got a folder full of pictures on SMB/CIFS storage that, many of which, when accessed via webDav, are not accessible (they don't "load" or are not viewable). If I mount this folder within the Ubuntu 14.04 OS and then create an ownCloud external storage link of type "local" to the OS mounted folder - it works! The same exact pictures also work fine from 8.0.5 via the SMB external link, the problem was introduced in 8.1 (and caused me to roll back to 8.0.5).

Three sample pictures are shared via the link below, served up by the 8.0.5 instance that works fine. 

Steps To Reproduce?
Put one of these pictures at the below link on an SMB share that is externally shared via ownCloud 8.1 or above then try to open those pictures via webDav.

https://www.hellriegel.us/owncloud/index.php/s/KSVqv53GWZs3rd5

Overall, I've actually got thousands of pictures shared out and it is only this group that exhibits the problem. One difference with these pictures from the others is that they came from an iPhone versus the others that came from anything but… It's not all of the iPhone pictures either - just some and with no apparent pattern.

When I access them via webDav it is usually via Android's QuickPic or ES File Explorer apps and both have trouble with the same files and from multiple phones running different Android versions. Accessing the files via the web always works fine.

**Comment by PVince81** [comment]
@jrh7675 please use the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md
It will ask you to check the owncloud.log for clues.

I suspect that the log will contain entries at the time you try to download these images over Webdav.

Also would be good to know how you mounted the SMB share (system-wide mount or personal page mount) and whether you use SMB or SMB_OC.
Do you use encryption ?

CC @icewind1991

**Comment by jrh7675** [comment]
I am using a system wide SMB (not SMB_OC) and I am not using encryption. The log files don't reveal much but maybe I need to turn it up or something. A WireShark of the problem reveals some RST sequences of packets.

I've tried to answer all the questions but some were easier (and more relevant) than others.

Thank you!

Jim

----------------------------------------------------------------------------------------------------

### Steps to reproduce

Copy one of the files located at this web site to an SMB share. https://www.hellriegel.us/owncloud/index.php/s/KSVqv53GWZs3rd5

Within ownCloud create a system wide SMB / CIFS external storage share.

Attempt to view the pictures within that share via webDav, preferably with QuickPic or ES File Explorer on Android (version doesn't matter but I've done it on an S3 with 4.x and an S5 with 4.x and 5.x)

Note that when I mount the SMB share within the Ubuntu OS to a folder like /media/share and then create an ownCloud local external storage link to that folder it works via webDav.

### Expected behaviour
The pictures should be viewable.

### Actual behaviour
Within QuickPic thumbnails can be generated but the full picture cannot be viewed. With ES File Explorer no thumbnail or picture can be viewed.

### Server configuration
Ubuntu 14.04

Apache2

MySql (Located on a Windows server)

PHP Version 5.5.9-1ubuntu4.11

8.1.1 (also happened in 8.1, doesn't happen in 8.0.5)

**List of activated apps:**

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list

Unfortunately this command isn't working at the moment - I get :

An unhandled exception has been thrown:
OC\HintException: [0]: Missing memcache class \OC\Memcache\APCu for local cache (Is the matching PHP module installed and enabled ?)

It's been acting wonky with 8.1.1, haven't had a change to fix it but I get it if you don't care about my problem until this one is fixed.

<?php
$CONFIG = array (
  'instanceid' => 'ocuufuhnt24a',
  'trusted_domains' =>
  array (
    0 => '192.168.1.199',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://192.168.1.199/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'dbname' => 'dbowncloud_dev',
  'dbhost' => 'mine.hellriegel.com.',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'logtimezone' => 'UTC',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'loglevel' => 1,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'theme' => '',
  'maintenance' => false,
);

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system --public
from within your ownCloud installation folder

An unhandled exception has been thrown:
OC\HintException: [0]: Missing memcache class \OC\Memcache\APCu for local cache (Is the matching PHP module installed and enabled ?)

**Are you using external storage, if yes which one:** local/smb/sftp/…

Yes - that's the whole point of the problem.

**Are you using encryption:** yes/no

No - not even httpS (it is a test server, I'll use httpS later)

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

Yes - Active Directory

#### LDAP configuration (delete this part if not used)

If this is needed I'll work more on it.

### Client configuration
**Browser:**

QuickPic or ES File Explorer

**Operating system:**

Android

### Logs
#### Web server error log
```
Nothing of consequence is in the log at the time of the event - can I turn up logging maybe?

#### ownCloud log (data/owncloud.log)
```
Nothing of consequence is in the log at the time of the event - can I turn up logging maybe?

#### Browser log
```
N/A

I did do a sniffer trace of the problem and see a series of RST packets as part of / interrupting the conversation …

**Comment by jrh7675** [comment]
Any input anyone?

**Comment by PVince81** [comment]
@jrh7675 any more luck with 8.1.3 ?

@icewind1991 @Xenopathic

**Comment by jrh7675** [comment]
I can no longer reproduce the problem, I don't know if it was 8.1.3 or if it was simply re-saving the pictures as new files inside of a photo viewer but some combination has made the problem to disappear. Consider this closed. Thanks for the follow-up!
