### ISSUE TITLE
ownCloud generates intermittent "An error occurred while loading the PDF" message since upgrading 8.0.4 to 8.1.1

### ISSUE THREAD

**Issue by mik997** [owncloud/core#18458]
Typical error at PDF viewer page:

PDF.js v1.0.712 (build: 6969ed4)
Message: Unexpected server response (0) while retrieving PDF "https://...........pdf"

- happens infrequently only on some PDFs.
- encryption is not enabled.
- deleting and re-uploading the same PDF does not correct.

**Comment by MorrisJobke** [comment]
Hi @mik997 thanks for the report. Can I ask you to open this issue in the pdf app issue tracker https://github.com/owncloud/files_pdfviewer/issues

Thanks
