### ISSUE TITLE
PROPFIND on federated share takes long

### ISSUE THREAD

**Issue by ckamm** [owncloud/core#18450]
As discussed in owncloud/client#3524, @PVince81 @DeepDiver1975 @phil-davis 

Phil provided me with access to a blaucloud.de server

    {"installed":true,"maintenance":false,"version":"8.0.0.7","versionstring":"8.0","edition":""}

The account has about 500MB of data (mostly local shares) and one federated share to another instance also hosted on blaucloud.de. The federated shared folder has about 1MB of data in 6 files.

Web interface: Browsing / is fast. Going into /my-federated-share is slow (takes about a minute to load).

API: PROPFINDs on / and /my-federated-share are slow (1 minute) and consecutive requests stay slow. PROPFINDs on /local-subfolder are fast.

These PROPFINDs should probably also be using cached data?

**Comment by dragotin** [comment]
Note that this breaks the experience when **setting up** the sync client, as we do this PROPFIND to display the file tree for the user to select which parts she wants to sync. It's not only that a sync takes longer.

**Comment by DeepDiver1975** [comment]
We need to improve the meta data cache on federated shares - just like any external mounts.

@icewind1991 @schiesbn ideas welcome - THX

**Comment by PVince81** [comment]
Here is a plan: https://github.com/owncloud/core/issues/13882#issuecomment-73927046

**Comment by DeepDiver1975** [comment]
> Here is a plan: #13882 (comment)

but this is out of scope for 8.2 - I don't see any time left for this

**Comment by ckamm** [comment]
Would there be a chance for easy speed up if we send a request that explicitly doesn't ask for the quota-used-bytes, like

```
<?xml version="1.0" ?>
<d:propfind xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">
  <d:prop>
    <d:resourcetype />
  </d:prop>
</d:propfind>
```

Currently the reply always contains the size information anyway.

**Comment by PVince81** [comment]
Not sure.
A PROPFIND on such folder might trigger the storage scan for the remote folder, so might be slow anyway.

@icewind1991 can you confirm ?

**Comment by guruz** [comment]
> The federated shared folder has about 1MB of data in 6 files.

Is that in the _same_ folder? "about a minute" for one directory listing? That sounds fishy in itself and can't really explained by slow network?

**Comment by phil-davis** [comment]
Somewhere else it was mentioned that a PROPFIND was taking 66 seconds to complete. But actually for me it seems to be 16 seconds. Maybe the "66" was a typo?
The 16 seconds is for the User2 client waiting to receive the "folders to sync" tree list that contains an External Storage defined by User2 that refers to a folder owned by User1. User1 and User2 are on the same ownCloud 8.0 server. The same time delay is experienced when User2 makes an External Storage to a folder owned by Userx on another ownCloud 8.0 server that even hosted by the same hosting provider.
In both cases there should be completely minimal network delays in making the External Storage connection.

**Comment by ckamm** [comment]
I'm pretty sure I saw 66 seconds using `time curl -X PROPFIND ...` - right now I also only see 16s.

**Comment by dragotin** [comment]
maybe server update in between?

**Comment by phil-davis** [comment]
These measurements are on a hosted ownCloud at blaucloud.de that started as "ownCloud 8.0 (stable)" and is still on that version.

**Comment by PVince81** [comment]
Since 8.1 there have been some speed improvements with the introduction of a stat cache to reduce the number of requests: https://github.com/owncloud/core/pull/14120
It's still not the ideal speed but is already an improvement.

**Comment by PVince81** [comment]
@ckamm is 8.2.2 still that slow ?

**Comment by PVince81** [comment]
Improving performance for PROPFIND on fed shares require bigger risky changes as per https://github.com/owncloud/core/issues/13882#issuecomment-73927046 and https://github.com/owncloud/core/issues/5383#issuecomment-173610139 (auth redundancy)

Moving to 9.1. @cmonteroluque 

Would still be good to know whether the performance got better in 9.0 beta2 compared to 8.x.

**Comment by PVince81** [comment]
I'm going to close this now.

Improving the performance with fed sharing is ongoing and see https://github.com/owncloud/core/issues/13882#issuecomment-73927046 and https://github.com/owncloud/core/issues/5383#issuecomment-173610139 for the places to start with.

Note that in 9.1 a feature called "pluggable auth" was added and will make it possible to avoid sessions when using remote DAV calls, which will bring performance benefits as said in the linked tickets.
