### ISSUE TITLE
encryption:migrate needs maintenance mode disabled for ldap users

### ISSUE THREAD

**Issue by carlaschroder** [owncloud/core#18464]
I need an expert opinion on this, please. Does user_ldap require special handling when upgrading encrypted ownCloud instances?

"I am upgrading from 7.0.8 to 8.1.1 on Ubuntu 14.04 with encryption enabled...
OK. I managed to get the command to process the LDAP users.
It needs to be out of "maintenance mode" before running the migrate command. Also the encryption app is disabled after the upgrade and needs to be re-enabled before the "migrate" command is available."
https://forum.owncloud.org/viewtopic.php?f=31&t=29881

I was not able to reproduce this, and the forum post didn't really arrive at a conclusion.

**Comment by MorrisJobke** [comment]
cc @schiesbn @blizzz

**Comment by schiesbn** [comment]
I'm not sure if I understand him correctly but during the migration from oC8.0 to oC8.1 the old encryption app is of course disabled and you enable the new encryption module and server-side-encryption in the admin settings. All this is documented here https://doc.owncloud.org/server/8.2/admin_manual/configuration_files/encryption_configuration.html?highlight=encryption#upgrading, including the correct command to migrate the keys. The documentation also advice to only enabled single user mode, not maintenance mode during migration.

The first sentence at the forum makes me worry:

> I am upgrading from 7.0.8 to 8.1.1 on Ubuntu 14.04 with encryption enabled. 

I hope he didn't tried to upgrade from 7.0.8 to 8.1.1 directly. This is not supported and will fail for encryption for sure, probably for other parts if the system as well.

**Comment by carlaschroder** [comment]
Thanks @schiesbn. That's what I thought, and that whole thread is confused.

**Comment by RealRancor** [comment]
> The documentation also advice to only enabled single user mode, not maintenance mode during migration.

But the upgrading docs in https://doc.owncloud.org/server/8.1/admin_manual/maintenance/upgrade.html#manual-upgrade-procedure are telling the people to go into maintenance mode during the upgrade.
