### ISSUE TITLE
Desktop client crashing if server down

### ISSUE THREAD

**Issue by mbouchar** [owncloud/core#18467]
With the desktop client version 1.8.4-1, the app crash at launch if the owncloud server is not available.

traps: owncloud[15409] general protection ip:7ff7b192f9d8 sp:7ffd5cae9dc0 error:0 in libQtNetwork.so.4.8.6[7ff7b18af000+14d000]

Kubuntu 15.10

**Comment by Xenopathic** [comment]
Please report this on the client issue tracker: https://github.com/owncloud/client/issues
