### ISSUE TITLE
Owner of shared folder cannot share subfolders when sharing is not allowed for others

### ISSUE THREAD

**Issue by FloMiLe** [owncloud/core#18465]
### Steps to reproduce
1. Create a folder "SharedFolder".
2. Share "SharedFolder" with group "G", of which you are a member, and uncheck "can share" for "G".
3. Create folder "SubFolder" inside "SharedFolder" and try to share.

### Expected behaviour
It should be possible to share "SubFolder".

### Actual behaviour
Sharing is not possible. It says: "Shared with you and the group G by <my username>. Resharing is not allowed."

### Server configuration
**ownCloud version:** 8.0.4

**Comment by MorrisJobke** [comment]
cc @schiesbn

**Comment by PVince81** [comment]
Let's first have a try with 8.0.6 and 8.1.1

**Comment by PVince81** [comment]
Ah yes, this one. It's fixed already, please upgrade.

**Comment by PVince81** [comment]
Duplicate of https://github.com/owncloud/core/issues/15771
