### ISSUE TITLE
Federated share must auto-delete when remote is gone

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#18474]
### Steps

1. Create two users "user1" and "user2"
1. Login as "user1"
1. Create a folder "test"
1. Share "test" using federated share with "user2@localhost/owncloud" (or whichever local URL, yes it works)
1. Login as "user2"
1. Accept the share
1. Login as "user1" again
1. Delete the folder "test"
1. Login as "user2"
1. Access the folder "test"

### Expected result
After accessing, a message "Storage invalid" is displayed and the folder disappears.

### Actual result
The folder can be entered and any file operation will cause "Internal Server Error".

### Versions
ownCloud 8.2 pre-alpha git master 510010e774c4019b7fc616c90085649abb7afac3

Regression from 8.1.1 and 8.0.6.
Note: 8.1.1 seems to show "storage not available" instead of "storage invalid", something to be investigated too...

**Comment by PVince81** [comment]
Regression introduced by https://github.com/owncloud/core/pull/17950 which is disabling `filesystem_check_changes` by default.

We need to statically set the watcher for federated shares to make sure it can detect remote changes.

This also means that if people manually set the option `filesystem_check_changes` to 0 in the config in previous versions, they'd experience the same issues.

**Comment by PVince81** [comment]
- [ ] fix watcher for federated shares
- [ ] investigate why we're getting "storage not available" instead of "storage invalid"

**Comment by PVince81** [comment]
I just checked and indeed on stable8 the folder disappears upon entering it. In 8.1.1 it's just temporarily unavailable. I'll bisect that.

**Comment by PVince81** [comment]
First breaking commit: 5f044ebf1bc6f45acec2e79dc05185acd0405f42
But I know that this is not something revertable. I remember many subsequent fixes to bring all the exceptions in line. Maybe something is missing or mixed up there.
I'll have a look.

**Comment by PVince81** [comment]
Messy stuff on master (with https://github.com/owncloud/core/issues/18477 applied) 
```
{"reqId":"y52\/diZPB2e9IvfQl4so","remoteAddr":"127.0.0.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#1 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_sharing\\\/publicwebdav.php(73): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/public.php(76): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#7 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2015-08-21T13:59:24+00:00","method":"PROPFIND","url":"\/owncloud\/public.php\/webdav\/"}
{"reqId":"L3EqMxxXsvp2gnPW+Jh8","remoteAddr":"127.0.0.1","app":"PHP","message":"Call to a member function getType() on boolean at \/srv\/www\/htdocs\/owncloud\/lib\/private\/connector\/sabre\/serverfactory.php#81","level":3,"time":"2015-08-21T13:59:24+00:00","method":"PROPFIND","url":"\/owncloud\/public.php\/webdav\/"}
{"reqId":"hxopq++3VdXQP4o0kgBx","remoteAddr":"127.0.0.1","app":"files_external","message":"Internal Server Error","level":3,"time":"2015-08-21T13:59:24+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/list.php?dir=%2Fpest&sort=name&sortdirection=asc"}
{"reqId":"OFUdX3eu5akh0AUySnH0","remoteAddr":"127.0.0.1","app":"PHP","message":"Argument 1 passed to OCA\\Files\\Helper::formatFileInfo() must implement interface OCP\\Files\\FileInfo, boolean given, called in \/srv\/www\/htdocs\/owncloud\/apps\/files_sharing\/ajax\/shareinfo.php on line 84 and defined at \/srv\/www\/htdocs\/owncloud\/apps\/files\/lib\/helper.php#135","level":0,"time":"2015-08-21T13:59:24+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files_sharing\/shareinfo?t=9TBlyb1cuiSPL4X"}
{"reqId":"OFUdX3eu5akh0AUySnH0","remoteAddr":"127.0.0.1","app":"PHP","message":"Call to a member function getMimetype() on boolean at \/srv\/www\/htdocs\/owncloud\/apps\/files\/lib\/helper.php#77","level":3,"time":"2015-08-21T13:59:24+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files_sharing\/shareinfo?t=9TBlyb1cuiSPL4X"}
{"reqId":"hxopq++3VdXQP4o0kgBx","remoteAddr":"127.0.0.1","app":"files","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\StorageNotAvailableException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/external\\\/storage.php(184): OCA\\\\Files_Sharing\\\\External\\\\Storage->getShareInfo()\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/external\\\/storage.php(169): OCA\\\\Files_Sharing\\\\External\\\\Storage->checkStorageAvailability()\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/watcher.php(89): OCA\\\\Files_Sharing\\\\External\\\\Storage->hasUpdated('', 1440165424)\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1187): OC\\\\Files\\\\Cache\\\\Watcher->checkUpdate('', Array)\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(861): OC\\\\Files\\\\View->getFileInfo('\\\/pest', true)\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files\\\/ajax\\\/list.php(35): OC\\\\Files\\\\Filesystem::getFileInfo('\\\/pest')\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(154) : runtime-created function(1): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#7 [internal function]: __lambda_func(Array)\\n#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(280): call_user_func('\\\\x00lambda_5', Array)\\n#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(894): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/aja...')\\n#10 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/external\\\/storage.php\",\"Line\":258}","level":4,"time":"2015-08-21T13:59:24+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/list.php?dir=%2Fpest&sort=name&sortdirection=asc"}
```

**Comment by PVince81** [comment]
Ok, I guess in 8.0 the detection logic was slightly different.

The external/storage calls the remote "ajax/shareinfo.php". If that one returns 404, it is interpreted as "not available" because it could also be a server failure.

Maybe "ajax/shareinfo.php" should actually return 401 or 403 when the passed token is invalid. This would cause the called to think the share is deleted.

But then what if the server is misconfigured and returns bogus 401 or 403 ?

"Maybe we should have shareinfo.php" always return valid JSON/XML that contains clear information whether the share still exists or not.

But then why use "shareinfo.php" at all and not rely solely on Webdav ? It is important the Webdav makes it possible too to find out whether a remote share still exists or not.

Or make this an OCS call...

Removing "regression" label, I think the current approach was done on purpose to avoid false positive for remote deletion.

**Comment by PVince81** [comment]
Maybe using the Webdav endpoint is enough.

When calling it with an expired token, the response looks like this:
```
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
  <s:message>Username or password does not match</s:message>
</d:error>
```

But if this was a generic server error, there would be no XML response.
This means that the caller can check:
- is it an XML response + 401 error code ? => the share is gone / creds have changed, so the mount can be deleted
- is it 401 but not XML ? keep the share, mark as "temporarily not available"

**Comment by MorrisJobke** [comment]
@michaelstingl 00004076

**Comment by nickvergessen** [comment]
Btw isn't this what https://github.com/owncloud/core/issues/16751 is about?

**Comment by MorrisJobke** [comment]
> Btw isn't this what #16751 is about?

Could you merge those two tickets somehow? Either closing this and moved the information over to the other one or do it vice versa.

**Comment by nickvergessen** [comment]
Well first we need to be sure it is the same

**Comment by MorrisJobke** [comment]
> Well first we need to be sure it is the same

The steps look the same. So I think so

**Comment by PVince81** [comment]
There is one step missing: empty trashbin.

In any cases, the expected behavior is as follows:
- whenever the deleted folder is in the trashbin, the recipient receives "Storage not available"
- whenever the deleted folder disappeared from the trashbin, the recipient receives "Storage invalid" and the folder is removed

This was fixed as part of https://github.com/owncloud/core/pull/22498
