### ISSUE TITLE
[OCS API] Return all data in public shares

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#18476]
Currently requesting data of a public share only returns share_id, path, link and token.

Example:
PublicShare(id=142,path=/Photos,link=http://OC_URL/index.php/s/sCAtEP3peiMn4LS,token=sCAtEP3peiMn4LS)

We need to have the info regarding permissions, public_upload and expiration_date.

**Comment by rullzer** [comment]
??
This is all there for the getShares response.

Are you talking about the create response?

**Comment by PVince81** [comment]
No, the response is missing:
- expiration date
- public upload flag / permissions

**Comment by rullzer** [comment]
So the create share. I'll look into it.

**Comment by rullzer** [comment]
See #18631
