### ISSUE TITLE
cron.php and console.php use fallacious test (PATCH)

### ISSUE THREAD

**Issue by mattcaron** [owncloud/core#18470]
Code:
```
		$user = posix_getpwuid(posix_getuid());
		$configUser = posix_getpwuid(fileowner(OC::$SERVERROOT . '/config/config.php'));
		if ($user['name'] !== $configUser['name']) {
			echo "Console has to be executed with the user that owns the file config/config.php" . PHP_EOL;
			echo "Current user: " . $user['name'] . PHP_EOL;
			echo "Owner of config.php: " . $configUser['name'] . PHP_EOL;
			exit(0);
		}
```

My setup is in my homedir, so I own all the files. The webserver can write to the necessary places because everything is group owned by www-data.

Suggested fix:
```
			$user = posix_getpwuid(posix_getuid());
			$configUser = posix_getpwuid(fileowner(OC::$SERVERROOT . '/config/config.php'));
			$configGroup = posix_getpwuid(filegroup(OC::$SERVERROOT . '/config/config.php'));
			if ($user['name'] !== $configUser['name'] &&
			    $user['name'] !== $configGroup['name']) {
				echo "Console has to be executed with the same user as the web server is operated" . PHP_EOL;
				echo "Current user: " . $user['name'] . PHP_EOL;
				echo "Web server user: " . $configUser['name'] . PHP_EOL;
				exit(0);
			}
```
The diff is:
```
-               if ($user['name'] !== $configUser['name']) {
+               $configGroup = posix_getpwuid(filegroup(OC::$SERVERROOT . '/conf
+               if ($user['name'] !== $configUser['name'] &&
+                   $user['name'] !== $configGroup['name']) {
```

If folks are happy with this, I'll grab the code and do a pull request.

**Comment by MorrisJobke** [comment]
@mattcaron Looks good to me. @DeepDiver1975 Opinion?

**Comment by DeepDiver1975** [comment]
@mattcaron please submit a PR - I'm willing to test this ... Thanks a lot!

**Comment by mattcaron** [comment]
So, I was thinking about this more, and I had a few thoughts.

First, the patch is wrong - I should be getting the name of the user's primary group and comparing that to the group of the file. (as in something like, `$group = posix_getgrgid(posix_getuid());`)

But then I realized that this only covers the user's primary group, not all the supplementary groups.

But, what we're really trying to figure out here is if the file is writeable, right? I'd think we'd use is_writeable(), but the user contributed notes suggest that all this would do is the same UID (and possibly GID, if you set it to be so in php.ini) compare as we're doing above.

Forgive my lack of experience with modern PHP - It's been about 10 years since I've done anything besides tweak Wordpress stuff. But, if this were C, I'd do an `fopen("file", "w")`,check the return value for NULL and, if it failed, check `errno` for the error - which would likely be something like EPERM, IIRC. Is there a way to do something similar in PHP? Because trying to open it would be the authoritative way to be certain if it was writeable, right?

**Comment by mattcaron** [comment]
So, no one has responded to my question, but it was referenced in #18746, and the consensus there was that "this is working as designed". So, does that mean that this should be closed too?

**Comment by PVince81** [comment]
@DeepDiver1975 @icewind1991 @Xenopathic close ? See previous comment
