### ISSUE TITLE
The OCC-command files:cleanup not operating as expected

### ISSUE THREAD

**Issue by hoorna** [owncloud/core#18497]
I use OC several years now and upgraded several times from version 6 to version 8.1.1 (on this moment). Great piece of software!!

In the database table oc_filecache I find very much entries to files that no longer exist in the data-directory. So I used the "php occ files:cleanup" command.
As a result I got: "0 orphaned file cache entries deleted". The database table oc_filechache seems to be unchanged.

Is this normal behaviour (and do I have the wrong expectations) or is this a bug? How can I cleanup the filecache or isn't this nessecary?

Thanks for the reply

**Comment by karlitschek** [comment]
thanks a lot for your feedback and question. we use this bugtracker to track owncloud bugs and feature requests. i recommend that you ask this question in the forum or on the user mailinglist. thanks for your understanding

**Comment by RealRancor** [comment]
@karlitschek Better point such questions to the developers mailinglist or #owncloud-dev as we don't have the knowledge about such oC internals at the forums.

**Comment by hoorna** [comment]
@karlitschek
@RealRancor 
That was exactly the reason why I placed the question here. :-)

According to Karlitschek suggestion I placed the question now on the owncloud forum and got I suggestion from RealRancor. I am willing to place the question on the developers mailinglist or #onwcloud-dev but I don't know how this works. Please help.

**Comment by RealRancor** [comment]
@hoorna Have a look at https://mailman.owncloud.org/mailman/listinfo/devel where you can find the part "Using Devel" which describes how to post a question on the mailinglist.

**Comment by karlitschek** [comment]
@realrancor point taken :-)

**Comment by hoorna** [comment]
I will give it a try. Thanks for the reply and help!


------ Origineel bericht ------
Van: "RealRancor" <notifications@github.com>
Aan: "owncloud/core" <core@noreply.github.com>
CC: "hoorna" <email@alfredvanhoorn.nl>
Verzonden: 23-8-2015 18:37:29
Onderwerp: Re: [core] The OCC-command files:cleanup not operating as 
expected (#18497)

**Comment by hoorna** [comment]
Hello,

As you suggested, last sunday I placed a message in the 
developers-mailinglist with the title "OCC-command "flies:cleanup" not 
working as expected". Until now I did not received any reaction exept a 
conformation mail (see attachment). Please can you help me what to do 
now?

Many thanks for your reply!


------ Origineel bericht ------
Van: "RealRancor" <notifications@github.com>
Aan: "owncloud/core" <core@noreply.github.com>
CC: "hoorna" <email@alfredvanhoorn.nl>
Verzonden: 23-8-2015 18:37:29
Onderwerp: Re: [core] The OCC-command files:cleanup not operating as 
expected (#18497)

**Comment by RealRancor** [comment]
Hi,

if you haven't subscribed to the mailinglist you need to wait until a moderator is accepting your post.

**Comment by hoorna** [comment]
Thanks for your quick reply. I few moments ago I subscribed to the mailinglist and sent my question to this. And now I have to wait. ;-)
Thanks again.
