### ISSUE TITLE
cron.php - checking for owner of config/config.php is not a reliable way to find owner of web server process

### ISSUE THREAD

**Issue by Kerrnel** [owncloud/core#18495]
cron.php reported 

console has to be executed with the same user as the web server is operated
Current user: www
Web server user: cfgfowner

Having a different owner of config.php (and having it www-group-writable) is valid - yet causes cron.php to break due to this method.

Better:

$processUser = posix_getpwuid(posix_geteuid());
print $processUser['name'];

**Comment by RealRancor** [comment]
Probably a dup of https://github.com/owncloud/core/issues/18470

**Comment by Kerrnel** [comment]
Agree - sorry
