### ISSUE TITLE
InvalidHostException when attempting to mount an SMB share

### ISSUE THREAD

**Issue by atrauzzi** [owncloud/core#18492]
I'm able to mount the share using nautilus on the same machine (using the same credentials), but in owncloud, I'm getting this error:

    Exception while scanning storage "smb::MYUSER@SMBHOST//SHARE%20NAME//": Icewind\SMB\Exception\InvalidHostException:

There is one thing that sticks out to me here, which is the format of the share appears slightly off to what I use in nautilus:

    smb://SMBHOST/SHARE%20NAME"

Which if you notice in owncloud, it's generating this:

    smb::MYUSER@SMBHOST//SHARE%20NAME//

Does that matter? I don't know... :)

**Comment by Xenopathic** [comment]
Does your share name include a space character?

Also, could you please fill out the [issue template](https://github.com/owncloud/core/blob/master/issue_template.md), thanks.

**Comment by atrauzzi** [comment]
It does, I unfortunately don't have control over it as it's an Apple Airport+TimeCapsule 3TB.  But I have no troubles accessing it from Nautilus under Ubuntu.

---

### Steps to reproduce
1. Attempt to set up an SMB share

### Expected behaviour
All my users should gain access to the remote share I configure.

### Actual behaviour
Red square (I assume indicating an error, you should put an `alt=""` on that!) and an error in the logs.

### Server configuration
**Operating system**: Ubuntu 15.04

**Web server**: Apache

**Database**: sqlite

**PHP version**: 5.6.*

**ownCloud version**: Most current on your PPA

**Updated from an older ownCloud or fresh install**: Fresh

**List of activated apps**: Defaults, plus the remote filesystem plugin.

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one**: no

---

If you need anything more, just ask.  I'm in the middle of a few things at the moment and I think my original report covers most of what's needed.  Again though, I don't mind answering specific questions.

**Comment by Xenopathic** [comment]
Thanks for the info.

@icewind1991 Perhaps your smbclient wrapper does not properly handle spaces in share names?

**Comment by icewind1991** [comment]
Can you try #18397

**Comment by atrauzzi** [comment]
Any info on how I'd go about doing that?

**Comment by PVince81** [comment]
You can wait for 8.1.2 which should be out soon. It contains the fix in question.

**Comment by Xenopathic** [comment]
s/soon/now/ -> https://download.owncloud.org/community/owncloud-8.1.2.tar.bz2

**Comment by PVince81** [comment]
@Xenopathic it hasn't been announced yet. Please don't post such links before the announcement.
The final packages need to be tested first...

**Comment by PVince81** [comment]
Please try again with 8.1.5 or 8.2.2.

If you still have the exact same problem, feel free to reopen.
