### ISSUE TITLE
Owncloud update with updater to 8.1.1.10

### ISSUE THREAD

**Issue by lek2011** [owncloud/core#18490]
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Updated "files" to 1.1.10

GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate

**Comment by RealRancor** [comment]
Very likely caused by the buggy OpenSSL/NSS versions or the missing /config/ca-bundle.crt

**Comment by lek2011** [comment]
Thanks fixed a few hours ago but there are a lot other errors.. you were right about this error :)
