### ISSUE TITLE
Email template | Changes not taking effect

### ISSUE THREAD

**Issue by prilly** [owncloud/core#18496]
Editing email templates has no effect, default templates are used. owncloud 8.1.1

**Comment by karlitschek** [comment]
please post a full bug report using this template. 
https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by DeepDiver1975** [comment]
and please reopen once all required information has been entered - THX

**Comment by prilly** [comment]
You can tel me why you need more information, the problem is clear, owncloud core does not work with template. If you cant figure it out you are probably not the right guy to fix it either.

There is no need for more information, fix it or not, i dont care.

-------- Opprinnelig melding --------
Fra: Frank Karlitschek <notifications@github.com> 
Dato:23.08.2015  16:58  (GMT+01:00) 
Til: owncloud/core <core@noreply.github.com> 
Ko: Prilly <prilly@speedbox.me> 
Emne: Re: [core] Email template | Changes not taking effect (#18496) 

please post a full bug report using this template. 
https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by Dacit** [comment]
For anyone wondering, tracked the issue down after having the same problem (persists at least with slightly newer versions): 

Theme is not set in config, but mail templates for theme "example" can be changed in admin ui. This leads user to believe that changes in the mail templates will affect sent emails, but as theme "example" is not set, no changes are visible.

Also illustrates why additional info like config.php is absolutely necessary.

**Comment by sibidharan** [comment]
Simple, inside `config/config.php`, add `'theme'=>'example'` to the array! And thats all.
