### ISSUE TITLE
Missing PDF File when accessing by subdomain + vHost

### ISSUE THREAD

**Issue by nasmacs** [owncloud/core#18500]
Hello Everyone,

First of all, sorry for my english that is not perfect.

After browsing all the WWW without finding anything about my case, I expect fo find out some answers here.

I host owncloud on a personal synology NAS.
I would like to host some services behind ony one domain so I recently declared a virtual host to point "cloud.mydomain.fr" in /web/owncloud directory.

So far there are no problems except with the PDF viewer and also the file download.
I get the red box message: 

"PDF.js v1.0.712 (identifiant de compilation : 6969ed4)
Message : Missing PDF "https://cloud.mondomaine.fr/index.php/apps/files/ajax/download.php?dir=%2FNotices&files=Climasiteur%20Mobile%20Bosch.pdf"."

When I don't use the subdomain with virtual host, everything is ok by accessing my owncloud from "https://mydomain.fr/owncloud"

After a complete re-installation of owncloud with the subdomain/ vHost, same problem.
I think this is not only linked with PDF files or the viewer so that downloading another type of file result to an error too (ERR_INVALID_RESPONSE) from the web browser.
On another side, no problem with the sync client.
Maybe the URL is not correctly translated, i don't know.

I am not an expert in web hosting but I hope to be clear with my explanations.
Every suggestions are welcomed. Thank you all.

**Comment by PVince81** [comment]
You might need to set the "overridehost" in your config.php and set it to "mydomain.fr"

**Comment by nasmacs** [comment]
Ok but it redirects all owncloud to mydomain.fr.
cloud.mydomain.fr is not available anymore.

**Comment by PVince81** [comment]
Try putting the correct domain in there instead, maybe "cloud.mydomain.fr"

**Comment by nasmacs** [comment]
I agree with you, owncloud is ok but same problem with the viewer or downloading files.
![screenshot050](https://cloud.githubusercontent.com/assets/13219190/9437068/574c719c-4a54-11e5-9aef-9c47e96cfb36.png)

**Comment by PVince81** [comment]
Maybe a routing bug.
Does downloading the file directly in the web UI work ?

**Comment by nasmacs** [comment]
It work only when i acces with https://mydomain.fr/cloud, not with https://cloud.mydomain.fr after declaring a vhost.

![screenshot051](https://cloud.githubusercontent.com/assets/13219190/9437424/9264e0d2-4a56-11e5-9f78-5f5d9dc05c23.png)

**Comment by nasmacs** [comment]
For Information, displaying images in owncloud works, although a PDF file (or other) need to be downloaded before display.
It seems that the download part is the problem.
Maybe (apps/files/ajax/download.php) ?

**Comment by PVince81** [comment]
This should work, I also have ownCloud deployed on a vhost "owncloud.mydomain.net" and it works fine (every URL goes through the vhost, I didn't need any overrides). Not sure what is wrong in your environment.

**Comment by nasmacs** [comment]
Well, I'll keep looking for it and try to install it on another environment than a Synology NAS.

**Comment by PVince81** [comment]
@nasmacs any more luck with a different environment and with a more recent ownCloud like 8.2.2 ?

Please reopen if you're still having issues.
You might also want to check http://owncloud.org/support as this looks more like an environment issue than a bug. Thanks.
