### ISSUE TITLE
view->getPath($id) returns strange path for delete files

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#18509]
If a file is deleted and moved to the trashbin, `getPath($id)` returns `_trashbin/$path.$timestamp`.
Looks like we just cut off `files` no ignoring whether it is `files/` or not.

Is this intended? @icewind1991 @PVince81

**Comment by PVince81** [comment]
Unlikely to be intended.

We should probably limit getPath() to return files under "files" or from ext storages.

**Comment by nickvergessen** [comment]
Okay, maybe it's a question of setting up. When you use `chroot('/user/files')` the problem exists. Using `chroot('/user/files/')` does not have the problem. But then you need to have all paths without leading slash.

So I think it's still worth fixing

**Comment by PVince81** [comment]
This also affects federated shares where the source was moved to trash.

**Comment by PVince81** [comment]
The view's root is "/root/files" and it calls "getRelativePath('/root/files_trashbin/files/tetsac.d1440425391')". This sounds like the known getRelativePath issues: https://github.com/owncloud/core/pull/16479

**Comment by PVince81** [comment]
Mega-dirty-quickfix:
```
	$ownerView->chroot($ownerView->getRoot() . '/');
```

**Comment by PVince81** [comment]
Also happens in setupFromToken for public shares... I guess it's time to revive https://github.com/owncloud/core/pull/16479

**Comment by PVince81** [comment]
In my case it looks like https://github.com/owncloud/core/pull/16479 fixes the issue.
Can you try it too ?

**Comment by cmonteroluque** [comment]
@PVince81 @nickvergessen pick up this issue again?

**Comment by nickvergessen** [comment]
Well it is fixed by #16479 which is waiting for merge iirc
