### ISSUE TITLE
Login fault, because disabled="disabled" only by some router or provider ?

### ISSUE THREAD

**Issue by rolfjoseph** [owncloud/core#18504]
huawei b593 disabled over LTE vodafone germany
( default settings oft the router )

unitymedia and LTE O2 haven´t any problem with
fritzbox 7050 ok 
fritzbox 7390 ok
tc 7200.U ok

**Comment by karlitschek** [comment]
can you please post a full bug report using the issue template? https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by rolfjoseph** [comment]
I think it´s the compression of the provider side web.vodafone.de. But performance.vodafone.de doesen´t works for me, because it´s a contract over otelo.

Is there an other way ? I think it´s the compression of the css and javascript.

**Comment by rolfjoseph** [comment]
That´s the way. The correct delivery looks with many stylesheet links and script links, but the incorrect delivery show some script details like:

		<link rel="apple-touch-icon-precomposed" href="/core/img/favicon-touch.png">
					<link rel="stylesheet" href="/core/css/styles.css?v=fcf3cb41816c677e8a32a6ab65654267" media="screen">
					<link rel="stylesheet" href="/core/css/header.css?v=fcf3cb41816c677e8a32a6ab65654267" media="screen">
					<link rel="stylesheet" href="/core/css/mobile.css?v=fcf3cb41816c677e8a32a6ab65654267" media="screen">
					<link rel="stylesheet" href="/core/css/icons.css?v=fcf3cb41816c677e8a32a6ab65654267" media="screen">
					<link rel="stylesheet" href="/core/css/fonts.css?v=fcf3cb41816c677e8a32a6ab65654267" media="screen">
					<link rel="stylesheet" href="/core/css/apps.css?v=fcf3cb41816c677e8a32a6ab65654267" media="screen">
					<link rel="stylesheet" href="/core/css/fixes.css?v=fcf3cb41816c677e8a32a6ab65654267" media="screen">
					<link rel="stylesheet" href="/core/css/multiselect.css?v=fcf3cb41816c677e8a32a6ab65654267" media="screen">
					<link rel="stylesheet" href="/core/vendor/jquery-ui/themes/base/jquery-ui.css?v=fcf3cb41816c677e8a32a6ab65654267" media="screen">
					<link rel="stylesheet" href="/core/css/jquery-ui-fixes.css?v=fcf3cb41816c677e8a32a6ab65654267" media="screen">
					<link rel="stylesheet" href="/core/css/jquery-tipsy.css?v=fcf3cb41816c677e8a32a6ab65654267" media="screen">
					<link rel="stylesheet" href="/core/css/jquery.ocdialog.css?v=fcf3cb41816c677e8a32a6ab65654267" media="screen">
					<style media="screen" style="display:none">#mvDrop{
	display:block;
	position:absolute;
	right:0;
	margin-right:7em;
	padding:0.5em;
	background:#eee;
	border-left:1px solid #ccc;
	border-right:1px solid #ccc;
	border-bottom:1px solid #ccc;
	border-bottom-right-radius:1em;
	border-bottom-left-radius:1em;
	z-index:100;
}
.action, .selectedActions a, #logout { opacity:1; -webkit-transition:0; -moz-transition:0; -o-transition:0; transition:0; }
.mv{
	margin-top:1.5em;
	margin-right:9em;
	top:1em;
}
#mvDrop label{ font-weight:normal; }
#mvForm {
	margin: 0;
	padding: 0;
}

</style>

					<link rel="stylesheet" href="/core/css/share.css?v=fcf3cb41816c677e8a32a6ab65654267" media="screen">
					<link rel="stylesheet" href="/apps/files_versions/css/versions.css?v=fcf3cb41816c677e8a32a6ab65654267" media="screen">
					<style media="screen" style="display:none">#searchbox.indexing {
	background-image: none;
}
form.searchbox #spinner {
	width: 16px;
	height: 16px;
	margin-top: 14px;
	float: right;
	margin-right: -27px;
	background-size: 16px;
}

</style>

Is there a solution to suppress the incorrect output over vodafone ?

It´s alltimes the same browser, but different connecxtions.

**Comment by Xenopathic** [comment]
Can you please post a full bug report as per @karlitschek 's request?

**Comment by MorrisJobke** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. It also looks like there is other code injected into our web page. There isn't much we can do then. :see_no_evil: 

Please reopen if you still encounter this issue with the [latest stable version](http://owncloud.org/install/) and then please use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md). You can also contribute directly by providing a patch – see the [developer manual](http://doc.owncloud.org/server/9.0/developer_manual/). :)

Thank you!

**Comment by rolfjoseph** [comment]
Sorry, i´am forgotten the answer.

After a few months by mailing with the support of LTE vodafone germany, it works now. It was the incorrect settings at the transparency proxy server. The vodafone germany proxy server has inject the stupid code, so that wasn´t able to sign in into the owncloud.

Now is the delivered browser-code clean without directy injected stylesheet and javascript from the head section. It´s fine now, thanks.

**Comment by MorrisJobke** [comment]
@rolfjoseph Thanks for the feedback
