### ISSUE TITLE
App update broken on master

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#18519]
### Env

Master from 26th of August
PHP 5.5

### Steps to reproduce

1. `git pull` the activity app
2. GUI asks for an update
3. Click on the update button

### Expected result

A new screen with the result of the update

### Actual result

The news screen contains an empty message and refreshing the page goes back to square 1. This is pretty severe for regular users not used to using occ.

![empty](https://cloud.githubusercontent.com/assets/323220/9441118/68fc9ad2-4a74-11e5-9ad1-272f2dc78913.png)

Luckily `occ upgrade` does still work

**Comment by MorrisJobke** [comment]
@oparoz Is there anything in the logs?

**Comment by MorrisJobke** [comment]
@oparoz Any change to get to know which versions of server (old & new) and activity (old & new) you used?

**Comment by oparoz** [comment]
Nothing in the ownCloud log, apart from the updateexception, but Firefox refused to connect to the update endpoint and the reply way an unparsable response error.

There was no server upgrade, just a git pull. For the activity app:
```
From https://github.com/owncloud/activity
   7847faa..dddba49  master     -> origin/master
```

But if nobody else is seeing this, then it's probably just a glitch when using master as opposed to releases.

**Comment by PVince81** [comment]
Refresh the page, update again.
Problem solved :wink:

**Comment by PVince81** [comment]
Duplicate of https://github.com/owncloud/core/issues/18557

**Comment by oparoz** [comment]
Nope, I refreshed many times and ended up in a loop.

So this needs to stay open until I can either reproduce or confirm it as fixed.

**Comment by PVince81** [comment]
Argh, so possible yet another bug.

Does it disappear when you clear the cache + cookies ? (to check if related to session)

**Comment by oparoz** [comment]
Since I manually upgraded using occ (or I couldn't use the instance), I can't test any more, until I need to upgrade another app.

Let me see if I can find another app to update...

**Comment by PVince81** [comment]
You can also install a test app then manually increase its version to trigger an app update. Then make sure to delete that app afterwards :smile:

**Comment by oparoz** [comment]
Is there such a test app somewhere? If I use a normal app, then it messes up the next updates since app info is never removed from the DB.

**Comment by oparoz** [comment]
Just updated an app and got the problem you described in the other ticket. The updater wants to update the Files app.

I cleared the cache and hit ctrl+f5 and still get the empty message.

In the web console, I definitely see weird things...

* 2 oc_sessionPassphrase request cookies, with different hashes
* 2 response cookies. 1 with a hash, another saying "deleted"

**Comment by oparoz** [comment]
If I switch to PR #18574

Then I get an error message in the GUI

> Possible CSRF attack. Connection will be closed.

**Comment by PVince81** [comment]
CC @LukasReschke

**Comment by oparoz** [comment]
A recent git pull fixed the issue. So, I'm closing it and will re-open if it breaks again.
