### ISSUE TITLE
Set filesystem_check_changes to 2 for tests?

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#18520]
It's great that there is a new setting to let the user decide what is most important to him, but for testing, shouldn't we have the default set at 2, so that we can make quick, behind the scene changes for the next test?

@DeepDiver1975 @PVince81 @icewind1991 @MorrisJobke

**Comment by PVince81** [comment]
Not really because it might not reflect the regular use case if you leave it to 2 while testing.

If you want to change files in "data" directory when testing, you can just run "./occ files:scan --all" to rescan the changes

**Comment by MorrisJobke** [comment]
I'm also against this change

**Comment by oparoz** [comment]
> Not really because it might not reflect the regular use case if you leave it to 2 while testing.

I think it's the opposite, using external shares is not the regular case and this setting should maybe only be turned on when such a share is mounted?

**Comment by MorrisJobke** [comment]
> I think it's the opposite, using external shares is not the regular case and this setting should maybe only be turned on when such a share is mounted?

Yes. And 0 means turned off and 2 is turned on.

**Comment by PVince81** [comment]
This setting is only for the "data" directory itself, not external storage.

External storages have their own settings (mount options) in the UI, they default to 1 which is "check once every access".

**Comment by oparoz** [comment]
@PVince81 - Ah, then this text should maybe be altered?

https://github.com/owncloud/core/blob/c7b0d50cb225b22bdf3d9470ea7da799443f677e/config/config.sample.php#L995-L996

**Comment by MorrisJobke** [comment]
> @PVince81 - Ah, then this text should maybe be altered?

Right. @oparoz: Can you create the PR?

**Comment by PVince81** [comment]
I'm confused about what the doc change is supposed to be.
@oparoz did you mean we should add a sentence that tells that this setting is only for the home storage, not external storage ?

**Comment by MorrisJobke** [comment]
> @oparoz did you mean we should add a sentence that tells that this setting is only for the home storage, not external storage ?

Yes

**Comment by PVince81** [comment]
this mode has been removed completely already, closing
