### ISSUE TITLE
blank screen on load when apcu is enabled

### ISSUE THREAD

**Issue by MarcusMoeller** [owncloud/core#18537]
On oc 8.1.1.3 when I try to use apcu I only got a blank page on load.

I have set:  'memcache.local' => '\OC\Memcache\APCu', in config.php

php5-apcu_4.0.6 is installed and cli is enabled as well:

apc.coredump_unmap => Off => Off
apc.enable_cli => On => On
apc.enabled => On => On
apc.entries_hint => 4096 => 4096
apc.gc_ttl => 3600 => 3600
apc.mmap_file_mask => no value => no value
apc.preload_path => no value => no value
apc.rfc1867 => Off => Off
apc.rfc1867_freq => 0 => 0
apc.rfc1867_name => APC_UPLOAD_PROGRESS => APC_UPLOAD_PROGRESS
apc.rfc1867_prefix => upload_ => upload_
apc.rfc1867_ttl => 3600 => 3600
apc.serializer => php => php
apc.shm_segments => 1 => 1
apc.shm_size => 32M => 32M
apc.slam_defense => On => On
apc.smart => 0 => 0
apc.ttl => 0 => 0
apc.use_request_time => On => On
apc.writable => /tmp => /tmp

There is no debug information availalbe, neither in webserver log nor in php-fpm log. Webserver is nginx.

**Comment by RealRancor** [comment]
Hi,

also check your data/owncloud.log as requested in the issue template:

https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version

which should be filled out in general.

**Comment by MarcusMoeller** [comment]
This is logged in owncloud.log: 

remoteAddr":"192.168.2.250","app":"remote","message":"Missing memcache class \\OC\\Memcache\\APCu for local cache","level":4,"time":"2015-08-25T09:35:36+00:00"}

**Comment by RealRancor** [comment]
Yes, that means your PHP hasn't loaded APCu correctly. The output above seems to be from php -m? Please check with an phpinfo.php if APCu is also loaded correctly for your webserver.

**Comment by MarcusMoeller** [comment]
Thanks for the hint. Had to restart php5-fpm in order to make it work.
