### ISSUE TITLE
OC.addScript and OC.addStyle should add app version to URL

### ISSUE THREAD

**Issue by VicDeo** [owncloud/core#18533]
After an app upgrade js and css files are loaded from a browser cache sometimes.

Adding something like `?v=APP_VERSION` to an URL here https://github.com/owncloud/core/blob/master/core/js/js.js#L306 would be extremely helpful.

**Comment by MorrisJobke** [comment]
Is already done: https://github.com/owncloud/core/blob/010c03fc30a6d5d1765889431905dc415d289018/lib/private/templatelayout.php#L158-158

**Comment by MorrisJobke** [comment]
Which also contains all app versions: https://github.com/owncloud/core/blob/010c03fc30a6d5d1765889431905dc415d289018/lib/private/templatelayout.php#L139-L141

**Comment by VicDeo** [comment]
@MorrisJobke this is PHP implementation. OC.addScript  is javascript

**Comment by MorrisJobke** [comment]
> @MorrisJobke this is PHP implementation. OC.addScript is javascript

Ah right. Sorry

**Comment by PVince81** [comment]
For this to work, the app version needs to be available in the JS side.
