### ISSUE TITLE
apps/files_sharing/api/externalShares 404 (Not Found)

### ISSUE THREAD

**Issue by nilsm** [owncloud/core#18530]
Hi there,

after updating to owncloud 8 file sharing stopped working. I share a single folder with another user and the 'share' wasn't available anymore after upgrading. I can't re-share the folder via the web interface because I get a 404 error:

/index.php/apps/files_sharing/api/externalShares 404 (Not Found)

When I click the 'share' button, I get another JS error from share.js:

Cannot read property 'droppedDown' of undefined

This is v8.1.1, I've tried reinstalling 3 times via apt-get and manually to no avail.

Thanks - Nils

**Comment by karlitschek** [comment]
hmm. there seems to be something strange with your package.
@jnweiger 
@schiesbn 
Any idea?

**Comment by jnweiger** [comment]
@nilsm From which version did you upgrade?
Do you have a log from the upgrade procedure?

**Comment by nilsm** [comment]
@jnweiger Thanks - I initially upgraded from a 7.something version. It was a few weeks ago, no log file unfortunately, I thought everything had gone ok and only noticed the issue when our bookkeeper needed access via the share last week.

**Comment by PVince81** [comment]
@nilsm can you check whether the "Share files" app is still enabled ? If yes, also check the admin page to see if the checkbox "Allow apps to use the Share API" is still enabled and also "Allow users on this server to receive shares from other servers	"

**Comment by nilsm** [comment]
@PVince81 Thanks for looking into this - I eventually reinstalled owncloud from scratch and re-uploaded all the files.The 'Share files' app was definitely enabled and the sharing UI was showing in the user front-end. I can't test anything else unfortunately, I didn't keep the old installation. I'll close the issue as I can't test / troubleshoot effectively anymore.
