### ISSUE TITLE
Wrong german translation in "external_storage" app

### ISSUE THREAD

**Issue by pierrejochem** [owncloud/core#18540]
There is a wrong translation in the external_storage app.
![2015-08-25_12-34-36](https://cloud.githubusercontent.com/assets/9192953/9464666/fedb2800-4b25-11e5-9648-53cbbd047616.png)

It should be **Speicher Typ**

**Comment by karlitschek** [comment]
can you please report this in transifex? https://www.transifex.com/owncloud_robot/owncloud/
Thanks a lot.

**Comment by pierrejochem** [comment]
Your join request for the German (Germany) (de_DE) language has been submitted. You will receive a notification upon acceptance or denial
