### ISSUE TITLE
Update stable8.1 to master gives strange error

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#18557]
### Steps

1. Checkout stable8.1 727cb3b2a3358215dc8cc8bfdc419d86bffd74dc
1. Setup OC
1. Check out master 1dc9283413dd5547d6b2080efbd33e0ce1f383d3
1. Run the upgrade in the web UI

### Expected result
Successfull update

### Actual result
```
{"reqId":"Yi0SJKePtbbdziBKljeo","remoteAddr":"192.168.177.239","app":"index","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"
#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/app.php(109): OC_App::loadApp('files')\\n
#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/util.php(127): OC_App::loadApps(Array)\\n
#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(884): OC_Util::setupFS()\\n
#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n
#4 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/app.php\",\"Line\":128}","level":4,"time":"2015-08-25T15:27:23+00:00","method":"GET","url":"\/owncloud\/index.php\/core\/js\/oc.js?v=189e2355831f806ce7399925f50fdf06"}
```

I noticed that the UI says that the "files" app needs to be updated, maybe something hangs there.
Refreshing the page once and running the update again makes it work.

**Comment by PVince81** [comment]
```
The first bad commit could be any of:
36eef2ddabd77ff6279f3bd6896ced4959f1c370
6a3fb0d3b36dce7a6583d58ded1b133f086e2a95
We cannot bisect more!
```

**Comment by PVince81** [comment]
Regression introduced through https://github.com/owncloud/core/pull/18482

**Comment by PVince81** [comment]
Strangely this is the commit that increases the files version later: e88b380973b54bc7b8bc86f888b1f11ae8e54076 https://github.com/owncloud/core/pull/18510
So not sure if this is related in any way.

**Comment by PVince81** [comment]
On master if I manually increase the version of "files" and do an app update (web UI), it works.
Also a simultaneous core + files update (increase both versions) starting from master works too.

So there is something happening only when coming directly from stable8.1

**Comment by PVince81** [comment]
I wonder if this has something to do with routing and loading apps too early.

@LukasReschke @nickvergessen @Xenopathic in case you have an idea

**Comment by MorrisJobke** [comment]
@PVince81 Is this only about the exception? This exception is logged on every owncloud core upgrade

**Comment by PVince81** [comment]
Is it ? I didn't notice.

Then it's more about the broken page that appears:
![update-empty](https://cloud.githubusercontent.com/assets/277525/9472591/9f996952-4b56-11e5-84c3-b61edfab2b22.png)

**Comment by PVince81** [comment]
Reloading will re-show the update page, and then the update can be performed.

Then maybe something is stored in the session which makes the subsequent update work ? That would make sense as the above commits are about the session.

**Comment by MorrisJobke** [comment]
@PVince81 can you run `./occ upgrade` ... the broken page looks like an exception, which is properly logged in the console command.

**Comment by PVince81** [comment]
I wonder, maybe there is a previous unencrypted session and the transition doesn't work, but then refreshing the page might recreate a new one.

Something to investigate...

**Comment by PVince81** [comment]
Just tried upgrading on the CLI and it works directly, no errors.
On the CLI there is no session.

I'll try debugging around the session code and see if I can find something.

**Comment by PVince81** [comment]
Ha... If I clear the browser cache before opening the web page for upgrade, no error appears.
It is indeed a session issue.

**Comment by MorrisJobke** [comment]
Something similiar: #10579

**Comment by MorrisJobke** [comment]
> Ha... If I clear the browser cache before opening the web page for upgrade, no error appears.
> It is indeed a session issue.

Nice catch :+1:

**Comment by PVince81** [comment]
Not related to the files app due update. If I switch back the files app version the problem still appears.

It must happen in base.php because a breakpoint in ajax/update.php is not reached when clicking "Start upgrade"

**Comment by PVince81** [comment]
"Token expired. Please reload page." happening in `callCheck()` from ajax/update.php

This is supposed to be the error message. I'll make a separate fix to make sure this can be displayed properly.

**Comment by PVince81** [comment]
Showing an error message is trickier than I thought. To show a message we need to init the event source and then send the message.
But then as soon as you send the first message, OC_EventSource calls its own internal "init()" which also does a CSRF check, and then produces its own error message.

So the hack here would be to send a message very early to trigger that CSRF check...
This, only to have a proper message displayed, not to fix the session issue.

**Comment by PVince81** [comment]
Here is a PR that properly displays the CSRF error and other upgrade exceptions: https://github.com/owncloud/core/pull/18574

The session issue still needs to be investigated and fixed.

**Comment by PVince81** [comment]
Cannot reproduce on latest stable8.1 (0b279f9a132080af5965716dd10f4d842e785ba2) to master (b049a0538465489b4e8159a5c2486a9f703d1b1e)
