### ISSUE TITLE
[mobile] Autocomplete drop down in sharing dialog not shown 

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#18551]
* have a small browser window (mobile UI)
* open share dialog
* enter username

### expected

* show autocomplete list

### actual

* autocomplete list is not shown, but there, because you can simply hit enter and the first item is used
* if you resize the window to a wider viewport it will show the autocomplete list

cc @owncloud/designers @jancborchardt

**Comment by PVince81** [comment]
@MorrisJobke does it still happen with the share dialog inside the sidebar ?

**Comment by jancborchardt** [comment]
Yes it does. It’s fixable by changing the z-index on `.ui-autocomplete` from 501 to 1001. However this is set at runtime and I didn’t find out yet where.

**Comment by PVince81** [comment]
probably some jquery-ui magic...

**Comment by jancborchardt** [comment]
@PVince81 so, are you on it or not? Comment doesn’t help ;)

**Comment by PVince81** [comment]
Not

**Comment by jancborchardt** [comment]
I would say this needs JS since I think adding a `z-index: 1001 !important` to the `.ui-autocomplete` might result in issues with other apps.

@MorrisJobke can you do it?

**Comment by MorrisJobke** [comment]
> @MorrisJobke can you do it?

Nope.

**Comment by cmonteroluque** [comment]
okey dokey

**Comment by jancborchardt** [comment]
This is still an issue as far as I can see. If no one else can work on it I will hack it with CSS, but as I said it might cause problems. In any case we should fix it.
