### ISSUE TITLE
Securing login

### ISSUE THREAD

**Issue by szepeviktor** [owncloud/core#18565]
As I am seeing now there is no limit on login tries.

How is it possible to trigger fail2ban with a simple `error_log()` call?

**Comment by szepeviktor** [comment]
In `data/owncloud.log` there is `Login failed:`. Should I rely on it?

```
{"reqId":"a4KCXbAD7xv9i5+yxNfM","remoteAddr":"94.21.133.16","app":"core","message":"Login failed: '435345' (Remote IP: '94.21.133.16)","level":2,"time":"2015-08-25T18:44:05+00:00"}
```

**Comment by LukasReschke** [comment]
> In data/owncloud.log there is Login failed:. Should I rely on it?

Yes. Note that the layout changed with 8.1 but will stay consistent now.

**Comment by szepeviktor** [comment]
Thank you.

I prefer using a server-wide solution.
