### ISSUE TITLE
Missing memcache class \OC\Memcache\APC

### ISSUE THREAD

**Issue by zubanst** [owncloud/core#18570]
Steps to reproduce:
-migrate owncloud 8.0.5 -> 8.1.1
-install and enable php-apc
-configure memcache in owncloud as described here https://doc.owncloud.org/server/8.1/admin_manual/configuration_server/config_sample_php_parameters.html#memory-caching-backend-configurationconfig 
Expected result:
Page loads correctly
Actual behavior:
Blank page displayed with following errors errors in the log:
OC\HintException: Missing memcache class \OC\Memcache\APC for local cache at /var/www/owncloud/lib/private/memcache/factory.php#75 

OS: Ubuntu 12.04
WS: Apache 2.2.22
PHP: 5.4.44
OC:8.1.1.3
Migration from 8.0.5 to 8.1.1

Applications enabled:

Activity 2.0.1
Deleted files 0.6.3
External Sites 1.2
External storage support 0.2.3
File Locking
First Run Wizard 1.1
Mail Template Editor 0.1
PDF Viewer 0.7
Pictures 0.6.0
Provisioning API 0.2
Share Files 0.6.2
Text Editor 0.4
Updater 0.6
Versions 1.0.6
Video Viewer 0.1.3
Antivirus App for files 0.4.2
Bookmarks 0.4
Delete Confirmation 1.0.1
Documents 0.10.1
Files Move 0.8.1a
Mail 0.1.3
Music 0.3.7
News 5.2.8
Shorty 0.5.0
Storage Charts 2 Application 2.6.0

Applications disabled:

Default encryption module 1.0.0
External user support 0.4
LDAP user and group backend 0.6.1
Server-side Encryption 0.7.2
Calendar 0.6.6
Contacts 0.3.0.19
Gallery 13.0.0
Share Links 1.0.1
Tasks 0.6.0

config.php
...
'memcache.local' => '\OC\Memcache\APC',
...
tried with \OC\Memcache\Memcached',

No external storage
No encryption
No external user backend

Client: firefox

No related error on the webserver

OC log:

OC\HintException: Missing memcache class \OC\Memcache\APC for local cache at /var/www/owncloud/lib/private/memcache/factory.php#75	2015-08-25T20:47:00+00:00
Error	PHP	OC\HintException: Missing memcache class \OC\Memcache\APC for local cache at /var/www/owncloud/lib/private/memcache/factory.php#75	2015-08-25T20:46:50+00:00
Error	PHP	OC\HintException: Missing memcache class \OC\Memcache\APC for local cache at /var/www/owncloud/lib/private/memcache/factory.php#75	2015-08-25T20:46:47+00:00
Error	PHP	OC\HintException: Missing memcache class \OC\Memcache\APC for local cache at /var/www/owncloud/lib/private/memcache/factory.php#75	2015-08-25T20:46:39+00:00
Error	PHP	OC\HintException: Missing memcache class \OC\Memcache\APC for local cache at /var/www/owncloud/lib/private/memcache/factory.php#75	2015-08-25T20:36:47+00:00
Error	PHP	OC\HintException: Missing memcache class \OC\Memcache\Memcached for distributed cache at /var/www/owncloud/lib/private/memcache/factory.php#81	2015-08-25T20:25:22+00:00
Error	PHP	OC\HintException: Missing memcache class \OC\Memcache\Memcached for distributed cache at /var/www/owncloud/lib/private/memcache/factory.php#81	2015-08-25T20:25:20+00:00
Error	PHP	OC\HintException: Missing memcache class \OC\Memcache\Memcached for distributed cache at /var/www/owncloud/lib/private/memcache/factory.php#81	2015-08-25T20:25:18+00:00
Error	PHP	OC\HintException: Missing memcache class \OC\Memcache\APC for local cache at /var/www/owncloud/lib/private/memcache/factory.php#75	2015-08-25T20:22:28+00:00
Error	PHP	OC\HintException: Missing memcache class \OC\Memcache\APC for local cache at /var/www/owncloud/lib/private/memcache/factory.php#75

**Comment by RealRancor** [comment]
Hi,

this means APC is not enabled within your PHP environment and is not a bug within oC.
