### ISSUE TITLE
Warning when moving two files to different storages.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#18575]
### Steps to reproduce

1. Enable external storage.
2. Mount a SFTP mount and an amazon S3 mount.
3. having two files, move one to SFTP folder and one to S3.

### Expected behaviour
Files are moved without problems.

### Actual behaviour
Warning with mysql problems.

![sftp s3](https://cloud.githubusercontent.com/assets/9048796/9489484/b088fb0c-4be1-11e5-8b49-a96900a0a548.gif)

### Server configuration

Operating system:
Ubuntu 14.04 LTS

Web server:
Apache

Database:
EDIT (Sorry for mistake): Oracle

PHP version:
5.5.9

ownCloud version: (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.0.6.2","versionstring":"8.0.6","edition":"Enterprise"}
(stable8)

Updated from an older ownCloud or fresh install:
fresh

List of activated apps:
Default ones + external storage.

Are you using external storage, if yes which one: local/smb/sftp/...
Yes, amazon s3 and SFTP.

Are you using encryption: 
No.

### Client configuration
Chrome.

**Comment by SergioBertolinSG** [comment]
Working fine in stable7.

**Comment by Xenopathic** [comment]
Unable to reproduce on master (tested with SFTP and Local mount points). Both moves complete successfully.

**Comment by Xenopathic** [comment]
Can you copy the exception that is printed to the screen into this issue? It's a little difficult trying to read it from your GIF.

**Comment by SergioBertolinSG** [comment]
![errorlittle](https://cloud.githubusercontent.com/assets/9048796/9492528/a96f7708-4bf8-11e5-8019-b0402652d53b.png)

**Comment by MorrisJobke** [comment]
@SergioBertolinSG Can you copy the message? Then we can also find it more easiely in the future ;)

**Comment by SergioBertolinSG** [comment]
I could

An exception occurred while executing 'INSERT INTO "filecache" ("mimepart","mimetype","mtime","size","etag","storage_mtime","permissions","path_hash","path","parent","name","storage") SELECT ?,?,?,?,?,?,?,?,?,?,?,? FROM "filecache" WHERE "storage" = ? AND "path_hash" = ? HAVING COUNT(*) = 0' with params ["3", "12", "245091883258", "0", "55dda7b1be78e", "245091883258", "27", "b9633f8316157e9e717bca98616c7c99", "NUEVO_NOMBRE copy 2.pl", "25", "NUEVO_NOMBRE copy 2.pl", "6", "6", "b9633f8316157e9e717bca98616c7c99"]: ORA-01438: value larger than specified precision allowed for this column

**Comment by Xenopathic** [comment]
Are you using an Oracle DB?

**Comment by DeepDiver1975** [comment]
> Database:
> MySQL

@Xenopathic

**Comment by Xenopathic** [comment]
@DeepDiver1975 I didn't think MySQL could result in an `ORA-01438` error? That sounds like an Oracle error to me...

I think I know what the problem is: the `mtime` trying to be stored of `245091883258` requires at least 5 bytes to represent, while the `mtime` field in the DB is only 4 bytes long. Thus, a precision error occurs.

I think the mtime is retrieved from the storage. Try moving a file only into S3, and/or creating a new file there. See if it gives the same error.

**Comment by DeepDiver1975** [comment]
> I didn't think MySQL could result in an ORA-01438 error? That sounds like an Oracle error to me...

for sure not - @SergioBertolinSG has to update the description to give proper information

**Comment by SergioBertolinSG** [comment]
Yes, sorry, this instance is using oracle. 
(We had mysql as default before, now default is oracle)

**Comment by DeepDiver1975** [comment]
> I think I know what the problem is: the mtime trying to be stored of 245091883258 requires at least 5 bytes to represent, while the mtime field in the DB is only 4 bytes long. Thus, a precision error occurs.

@Xenopathic can I ask you to extract this sample and implement a unit test on this ? THX

**Comment by Xenopathic** [comment]
@DeepDiver1975 What do we want to unit test? That the DB throws an error if we try to store a number that exceeds the defined precision? Or that no storage implementation should ever give an mtime greater than 32-bit signed?

**Comment by DeepDiver1975** [comment]
This sql statment is called in the file cache class - we need to ensure that valid timestamps are used.
Question is:
- where is this high number coming from?
- should we fail or default this to some meaningful value?

@PVince81

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 What do we want to unit test? That the DB throws an error if we try to store a number that exceeds the defined precision? Or that no storage implementation should ever give an mtime greater than 32-bit signed?

ignore - i was on the wrong track ...

**Comment by Xenopathic** [comment]
Well, I tried to get a Ceph setup working with the S3 API layer, but it's not working. @SergioBertolinSG @DeepDiver1975 I'd appreciate some S3 credentials to test this, THX.

**Comment by Xenopathic** [comment]
OK, so I tried with an Amazon S3 mount (via Ceph) and FTP (via @MorrisJobke's brilliant Docker image), moving two files from ownCloud root into each storage with no wait between, and both are moved successfully. Everything works as expected, no exceptions.

@SergioBertolinSG I'm going to need credentials to the S3 you are mounting. Please send them via email (or wait until we meet at the conf :smile:)

**Comment by PVince81** [comment]
@SergioBertolinSG does it also happen when you only move a single file directly to S3 ?

I also see that the file you are moving contains a special unicode character, could it be related ? Does it work with a file with ASCII file name ?

**Comment by cmonteroluque** [comment]
@SergioBertolinSG update please

**Comment by SergioBertolinSG** [comment]
Not able to reproduce this on master again. 
I'm closing it. If someone can reproduce this again, please reopen.
