### ISSUE TITLE
Edit of the SFTP root folder is not possible.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#18578]
### Steps to reproduce

1. Enable external storage.
2. Mount a SFTP mount.
3. Change the root folder.

### Expected behaviour
root folder is saved, and changed.

### Actual behaviour
It doesn't change and in fact it mounts the / folder which isn't desirable at all.

### Server configuration

Operating system:
Ubuntu 14.04 LTS

Web server:
Apache

Database:
MySQL

PHP version:
5.5.9

ownCloud version: (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.2.0.4","versionstring":"8.2 pre alpha","edition":"Enterprise"}
(master)

Updated from an older ownCloud or fresh install:
fresh

List of activated apps:
Default ones + external storage.

Are you using external storage, if yes which one: local/smb/sftp/...
Yes, amazon s3 and SFTP.

Are you using encryption: 
No.

### Client configuration
Chrome.

**Comment by SergioBertolinSG** [comment]
@PVince81 @Xenopathic

**Comment by PVince81** [comment]
I tried on master (08a490df32e7744be5e5f47067746591e7fac05a) and had "/home/vincent/temp/sftpmount" as root, then navigated into it, it worked.
Then I went back to the admin page and changed it to "/home/vincent/temp/sftpmount2" and then it was saved properly. Navigating into it showed the new content.

Not sure what you are doing differently @SergioBertolinSG ?
Maybe there's a save delay that causes https://github.com/owncloud/core/issues/17148.
Are you sure this isn't https://github.com/owncloud/core/issues/17148 ? (not a regression)

**Comment by SergioBertolinSG** [comment]
Well it is related, I didn't put any root, and later tried to add it. But it doesn't work.

**Comment by PVince81** [comment]
Does it work on stable8.1 ? (just to find out if it's a regression)

**Comment by SergioBertolinSG** [comment]
Yes, no problems in stable8.1.
I've checked mounting another point with another rootdifferent than default with same result, it cannot be edited.

**Comment by LukasReschke** [comment]
stable8.1 as the current stable8.1 from Git? Or an older one?

**Comment by SergioBertolinSG** [comment]
Current from tonight. (daily stable8.1).

**Comment by SergioBertolinSG** [comment]
Working fine in stable7.

**Comment by Xenopathic** [comment]
Unable to reproduce on master. I created an SFTP storage with no root, tested it (I see the contents of '/' in the files view), then added a root ('/tmp') and tested again (I see the contents of '/tmp' in the files view).

**Comment by SergioBertolinSG** [comment]
Tested again with very latest master, community version. Same issue.

**Comment by Xenopathic** [comment]
@SergioBertolinSG Do you allow time for the storage config to be saved after changing it? So, do you see the green dot at the far left become a spinner briefly then return to a green dot? Also, browser logs?

**Comment by SergioBertolinSG** [comment]
Yes, it turns red first, but after a little time it turns green. In the logs nothing appears.

**Comment by Xenopathic** [comment]
>  it turns red first

That means there's an issue saving the storage. Perhaps it's something benign, like it trying to save the storage while you are still inputting parameters, but it could be a sign of a bigger issue.

**Comment by Xenopathic** [comment]
@SergioBertolinSG Could you please retest? This is currently unreproducible by me...

**Comment by cmonteroluque** [comment]
@SergioBertolinSG @rperezb please retest

**Comment by SergioBertolinSG** [comment]
@Xenopathic Working fine in 8.1beta1. Hence closing.
