### ISSUE TITLE
Activity notifications sent after login via web

### ISSUE THREAD

**Issue by kalletabur** [owncloud/core#18581]
### Steps to reproduce
1. User1 shares something with user2 (normal share or federated ID)
2. User2 has mail notifications enabled (on personal page all check, hourly)
3. User2 uses owncloud client (not web)

### Expected behaviour
Email should be sent with activity notification

### Actual behaviour
User gets activity notification only after he/she login over web

### Question about
Is it possible to eg. periodically send OwnCloud notifications to users, instead of notifications being triggered by users logons (or whatever triggers them currently).

### Server configuration
**Operating system**:
Debian 7.8

**Web server:**
NGINX 1.2.1-2.2+wheezy3

**Database:**
MySQL 5.5.44-0+deb7u1

**PHP version:**
PHP 5.4.41-0+deb7u1

**ownCloud version:** (see ownCloud admin page)
8.0.2-8

**Updated from an older ownCloud or fresh install:**
updated

**List of activated apps:**

```
Enabled:
 - activity
 - files
 - files_encryption
 - files_locking
 - files_pdfviewer
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - files_videoviewer
 - firstrunwizard
 - gallery
 - user_ldap
Disabled:
 - external
 - files_external
 - provisioning_api
 - templateeditor
 - user_external
 - user_webdavauth

```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '8a7s6df87as76',
  'passwordsalt' => '8a7s6df87as76',
  'trusted_domains' => 
  array (
    0 => 'oc.oc.oc',
  ),
  'datadirectory' => '/var/ocdatafolder/',
  'dbtype' => 'mysql',
  'version' => '8.0.2.0',
  'dbname' => 'ocmysqldatabase',
  'dbhost' => 'ocmysqldatabasehost',
  'dbtableprefix' => 'oc_dbtableprefix',
  'dbuser' => 'dbuser',
  'dbpassword' => '8a7s6df87as76',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'loglevel' => '0',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'smtp.oc.oc',
  'mail_smtpport' => '25',
  'forcessl' => true,
  'maintenance' => false,
  'logtimezone' => 'Europe/Europe',
  'theme' => '',
  'share_folder' => '/Shared',
  'preview_libreoffice_path' => 'libreoffice',
  'secret' => '8a7s6df87as76',
);

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
ActiveDirectory

#### LDAP configuration (delete this part if not used)

```
|appid|configkey|configvalue|
|user_ldap|cleanUpJobOffset|600|
|user_ldap|enabled|yes|
|user_ldap|has_memberof_filter_support|1|
|user_ldap|home_folder_naming_rule||
|user_ldap|installed_version|0.5.0|
|user_ldap|last_jpegPhoto_lookup|0|
|user_ldap|ldap_agent_password||
|user_ldap|ldap_attributes_for_group_search||
|user_ldap|ldap_attributes_for_user_search||
|user_ldap|ldap_backup_host||
|user_ldap|ldap_backup_port||
|user_ldap|ldap_base|DC=example,DC=local|
|user_ldap|ldap_base_groups|DC=example,DC=local|
|user_ldap|ldap_base_users|DC=example,DC=local|
|user_ldap|ldap_cache_ttl|600|
|user_ldap|ldap_configuration_active|1|
|user_ldap|ldap_display_name|displayname|
|user_ldap|ldap_dn|CN=Comp-Ownc,OU=COM,OU=Company,DC=example,DC=local|
|user_ldap|ldap_email_attr|mail|
|user_ldap|ldap_experienced_admin|0|
|user_ldap|ldap_expert_username_attr|sAMAccountName|
|user_ldap|ldap_expert_uuid_group_attr||
|user_ldap|ldap_expert_uuid_user_attr||
|user_ldap|ldap_group_display_name|cn|
|user_ldap|ldap_group_filter|(&(|(objectclass=group))(|(cn=Dev)(CN=Comp-Ownc)(cn=Comp-admis)))|
|user_ldap|ldap_group_filter_mode|0|
|user_ldap|ldap_group_member_assoc_attribute|member|
|user_ldap|ldap_groupfilter_groups|Comp-DevComp-Owncloud Comp-admis|
|user_ldap|ldap_groupfilter_objectclass|group|
|user_ldap|ldap_host|dc300|
|user_ldap|ldap_login_filter|(&(&(|(objectclass=person))(|(memberof=CN=Comp-Ownc,OU=DL,OU=Company,DC=example,DC=local)(memberof=CN=Comp-Dev,OU=DL,OU=Company,DC=example,DC=local)(memberof=CN=Comp-admis,OU=DL,OU=Company,DC=example,DC=local)))(samaccountname=%uid))|
|user_ldap|ldap_login_filter_mode|0|
|user_ldap|ldap_loginfilter_attributes||
|user_ldap|ldap_loginfilter_email|0|
|user_ldap|ldap_loginfilter_username|1|
|user_ldap|ldap_nested_groups|0|
|user_ldap|ldap_nocase|1|
|user_ldap|ldap_override_main_server|0|
|user_ldap|ldap_paging_size|500|
|user_ldap|ldap_port|389|
|user_ldap|ldap_quota_attr||
|user_ldap|ldap_quota_def||
|user_ldap|ldap_tls|0|
|user_ldap|ldap_turn_off_cert_check|1|
|user_ldap|ldap_user_filter_mode|1|
|user_ldap|ldap_userfilter_groups||
|user_ldap|ldap_userfilter_objectclass||
|user_ldap|ldap_userlist_filter|(&(|(objectclass=person))(|(memberof=CN=Comp-Ownc,OU=DL,OU=Company,DC=example,DC=local)(memberof=CN=Comp-Dev,OU=DL,OU=Company,DC=example,DC=local)(memberof=CN=Comp-SystemAdministrators,OU=DL,OU=Company,DC=example,DC=local)))|
|user_ldap|ocsid|166061|
|user_ldap|types|authentication|
```

### Client configuration
**Browser:**
FireFox

**Operating system:**
Any 

**OwnCloud Client**
1.8.4

### Mail source

Date: Wed, 26 Aug 2015 10:17:59 +0000
Subject: Activity notification
From: ownCloud <no-reply@oc.allmighty.com>
To: user2 <user2@allmighty.com>

Hello user2,

You are receiving this email because in the last week the following things happened at https://oc.allmighty.com/

* User1 shared Shared/Paris.jpg with you - August 17, 2015 at 5:40:30 PM
* User1 shared Shared/San Francisco.jpg with you - August 17, 2015 at 5:41:13 PM
* User1 shared Shared/Squirrel.jpg with you - August 17, 2015 at 5:41:56 PM
* User1 shared Shared/jagame with you - August 17, 2015 at 5:45:12 PM
* User1 shared Shared/jagame with you - August 17, 2015 at 5:46:10 PM
* User1 shared Shared/jagame with you - August 17, 2015 at 5:47:19 PM
* user2@oc.allmighty.com accepted remote share API - August 17, 2015 at 6:16:45 PM

### Owncloud log
{"reqId":"ajklsdhf98ASD98FA","remoteAddr":"10.10.10.10","app":"core","message":"Sent mail to \"Array\n(\n    [user2@allmighty.com] => User2\n)\n\" with subject \"Activity notification\"","level":0,"time":"2015-08-26T13:18:00+03:00","method":"GET","url":"\/cron.php"}

**Comment by karlitschek** [comment]
@nickvergessen Can you have a look?

**Comment by nickvergessen** [comment]
> Is it possible to eg. periodically send OwnCloud notifications to users, instead of notifications being triggered by users logons (or whatever triggers them currently).

It is done via a cron job. So what you need to do is make sure your cron is triggered often enough. Looking at your config, it looks like you have no cron configured, which means that oC uses Ajax cron jobs. Those are triggered after each page load, so activities will be sent once any user logs in.

I recommend changing the cron to system cron or web cron:
https://doc.owncloud.org/server/8.1/admin_manual/configuration_server/activity_configuration.html?highlight=notification#configuring-your-owncloud-for-the-activity-app

So closing this as invalid.
