### ISSUE TITLE
Cron doesn't show cron.php was run in system cron mode

### ISSUE THREAD

**Issue by zubanst** [owncloud/core#18593]
Steps to reproduce:
-migrate owncloud 8.0.5 -> 8.1.1
-set cron to webcron
-execute https://[mysite]/cron.php; result: {"status":"success"}
-set cron to system's cron; setup cron job with:
crontab -u www-data -e
*/15  *  *  *  * php -f /var/www/owncloud/cron.php > /dev/null 2>&1
Restart cron service
Expected result:
cron.php runs correctly; admin shows sign cron was run
Actual behavior:
Admin page doesn't show as cron was run
Try to run command manually:
sudo -u www-data php -f /var/www/owncloud/cron.php
Command executes correctly, no return message; admin page doesn't show as cron was run.
So the question is: why running https://[mysite]/cron.php runs correctly and sudo -u www-data php -f /var/www/owncloud/cron.php doesn't seem to give any result.

OS: Ubuntu 12.04
WS: Apache 2.2.22
PHP: 5.4.44
OC:8.1.1.3
Migration from 8.0.5 to 8.1.1

Applications enabled:

Activity 2.0.1
Deleted files 0.6.3
External Sites 1.2
External storage support 0.2.3
File Locking
First Run Wizard 1.1
Mail Template Editor 0.1
PDF Viewer 0.7
Pictures 0.6.0
Provisioning API 0.2
Share Files 0.6.2
Text Editor 0.4
Updater 0.6
Versions 1.0.6
Video Viewer 0.1.3
Antivirus App for files 0.4.2
Bookmarks 0.4
Delete Confirmation 1.0.1
Documents 0.10.1
Files Move 0.8.1a
Mail 0.1.3
Music 0.3.7
News 5.2.8
Shorty 0.5.0
Storage Charts 2 Application 2.6.0

Applications disabled:

Default encryption module 1.0.0
External user support 0.4
LDAP user and group backend 0.6.1
Server-side Encryption 0.7.2
Calendar 0.6.6
Contacts 0.3.0.19
Gallery 13.0.0
Share Links 1.0.1
Tasks 0.6.0

config.php
...
not relevant
...
tried with \OC\Memcache\Memcached',

No external storage
No encryption
No external user backend

Client: firefox

No related error on the webserver

OC log:

Fatal 	cron 	Missing memcache class \OC\Memcache\APC for local cache

**Comment by zubanst** [comment]
Additional information: 
I figured out: it is linked to the APC configuration. When I enable the the APC from the configuration file with 'memcache.local' => '\OC\Memcache\APC', and execute manually the sudo -u www-data php -f /var/www/owncloud/cron.php I get the following error in the log:
Fatal 	cron 	Missing memcache class \OC\Memcache\APC for local cache 
So cron.php crashes with APC enabled though APC seems configured correctly.
I can't figure out what's wrong with my APC configuration.

**Comment by DeepDiver1975** [comment]
Most probably APC is not enabled for cli.
Please double check the PHP.ini

**Comment by RealRancor** [comment]
Yes, when getting this error APC is not enabled for cli: https://github.com/owncloud/core/issues/17329#issuecomment-119248944

**Comment by zubanst** [comment]
Yes, apc.enable_cli=1 was missing from /etc/php5/cli/php.ini
Thank you guys. it was not clear for me if this was required for my older configuration with APC too, or only with the newer APCu.

**Comment by flotho** [comment]
:+1:
