### ISSUE TITLE
LDAP test of configuration with invalid DN

### ISSUE THREAD

**Issue by timeos** [owncloud/core#18592]
Hello
there is an following LDAP testing connection in place in "apps/user_ldap/ajax/testConfiguration.php":

$ldapWrapper->read($connection->getConnectionResource(), 'neverwhere', 'objectClass=*', array('dn'));

I am not very happy with it, because it produces LDAP error "invalid DN". Yes, I know that the point is not to have valid DN, but just test if connectivity to LDAP is working with provided credentials, host and port. But it would be better to use empty string in comparison to invalid string "neverwhere".

In current situation I get "invalid DN" error in LDAP log (which is not that important), but I get this error in owncloud log, which could point me to some configuration issue as false alarm.

I am really recommending you to use empty string '' instead of 'neverwhere' to make things more clear.

thank you

michal

**Comment by MorrisJobke** [comment]
cc @blizzz

**Comment by blizzz** [comment]
This was reported here as well, https://github.com/owncloud/core/issues/18340, but I keep it open as the main issue on the other report is a different one.

**Comment by blizzz** [comment]
Setting to next maintenance release, because noisy log is annoying and we'll have more complaints.

**Comment by blizzz** [comment]
Was actually already  fixed with https://github.com/owncloud/core/pull/21037
