### ISSUE TITLE
Always emit post-hook if pre-hook was emitted

### ISSUE THREAD

**Issue by schiessle** [owncloud/core#18590]
While debugging some failing unit tests (https://github.com/owncloud/core/issues/17877) I found something interesting  I never thought about before.

Let's look at the rename operation as a example:

We have one condition to check if we execute the pre hooks https://github.com/owncloud/core/blob/master/lib/private/files/view.php#L645

```
if ($this->shouldEmitHooks($path1) && (Cache\Scanner::isPartialFile($path1) && !Cache\Scanner::isPartialFile($path2))) 
```

for the post hook we have a different check: https://github.com/owncloud/core/blob/master/lib/private/files/view.php#L695

```
if ((Cache\Scanner::isPartialFile($path1) && !Cache\Scanner::isPartialFile($path2)) && $result !== false)
```

Does this makes sense, beside the check for the result? I think in general we should always call the post hook if the pre hook was executed. The pre-hook sometimes store some state and it can be really bad if the state doesn't get reset properly, e.g. the trash bin storage wrapper.

Opinions?

cc @DeepDiver1975 @icewind1991

**Comment by PVince81** [comment]
Risky change if we do it => 9.1

**Comment by PVince81** [comment]
While it makes sense conceptually, I don't see this as critical. Moving to backlog.

**Comment by PVince81** [comment]
I think I'd rather have another hook that is triggered when there was an error, so it's easier to distinguish. The hook could be called "error.create.file" or something
