### ISSUE TITLE
Calendar sharing using LDAP groups on diskstation not working anymore after upgrade from 6.0.3 to 6.0.9.2

### ISSUE THREAD

**Issue by integras** [owncloud/core#18596]
I am trying to pull up a 6.0.3 installation to 8.1.x and having several isssues.

Here the first one.

After the upgrade which returned no errors I do not see part of my calendars anymore. Some investigation shows that this seems to be related to sharing calendar using LDAP groups. When sharing alternatively or in addition with direct share to user, this works. Only sharing via groups does not work anymore but worked before.

Environment information:
- Users all have only LDAP accounts, no other account type is used
- Sharing user shares via group, which fails. Sharing for individual users works
- Sharing parameters are: Only Create, Change, Delete. Share (for cascaded sharing) is not included (ticked)
- Old version: 6.0.3.1 sharing worked flawlessly
- New version (from version.php): 6.0.9.2 sharing stopped working
- LDAP server on diskstation, OS version: DSM 5.2-5592 Update 3

I do not see anything in the forum or here. Has someone encountered this? Is it fixed in 7.x or 8.x?

And here the long version...

### Steps to reproduce
1. Take a LDAP user (source) on diskstation LDAP being in a LDAP group
2. Share one of his calendars to another user (target) being in the same LDAP group
3. Login as the user target, click on calendar and on the crank wheel
4. Calendar should show up, but does not
5. As user source share calendar in addition to user target
6. Login as user target, look at calendars, the calendar is there

### Expected behaviour
The calendar should be accessible by user target as it was up to 6.0.3.1

### Actual behaviour
Calendar not visible to user target in version 6.0.9.2

### Server configuration
**Operating system**: Diskstation DSM 5.2-5592 Update 3

**Web server:** unknown

**Database:** SQLITE

**PHP version:** 5.5.26
phpinfo()
PHP Version => 5.5.26

System => Linux dshpl1 3.10.35 #5592 SMP Wed Aug 19 13:38:50 CST 2015 x86_64
Build Date => Jun 29 2015 17:42:59
Server API => Command Line Interface
Virtual Directory Support => disabled
Configuration File (php.ini) Path => /etc/php
Loaded Configuration File => /etc/php/php.ini
Scan this dir for additional .ini files => /etc/php/conf.d
Additional .ini files parsed => /etc/php/conf.d/SYNO.SDS.PhotoStation.ini,
/etc/php/conf.d/extensions.ini,
/etc/php/conf.d/mysql.ini,
/etc/php/conf.d/opcache.ini,
/etc/php/conf.d/user-settings.ini

PHP API => 20121113
PHP Extension => 20121212
Zend Extension => 220121212
Zend Extension Build => API220121212,NTS
PHP Extension Build => API20121212,NTS

**ownCloud version:** (see ownCloud admin page) 6.0.9.2

**Updated from an older ownCloud or fresh install:** 6.0.3.1

**List of activated apps:**contact, calendar, picture, links, documents

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder

not available due to failed subsequent upgrade to 7.x, error thrown (will be reported in a separate issue):

exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 11 malformed database schema (owncloud_name_groups) - index owncloud_name_groups already exists' in /volume1/web/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:638

**The content of config/config.php:**

$CONFIG = array (
  'instanceid' => '...',
  'passwordsalt' => '...',
  'datadirectory' => '/volume1/web/owncloud_data/data',
  'dbtype' => 'sqlite3',
  'version' => '6.0.9.2',
  'installed' => true,
  'forcessl' => true,
  'ldapIgnoreNamingRules' => false,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => '1',
  'trusted_domains' => 
  array (
    0 => '...',
    1 => '...',
  ),
);

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

sqlite3 data/owncloud.db or mysql -u root -p owncloud
then execute:  select * from oc_appconfig where appid='user_ldap';

not available:

/volume1/web/owncloud # sqlite3 ../owncloud_data/data/owncloud.db
SQLite version 3.8.10.2 2015-05-20 18:17:19
Enter ".help" for usage hints.
sqlite> select * from oc_appconfig where appid='user_ldap';
Error: malformed database schema (owncloud_name_groups) - index owncloud_name_groups already exists

### Client configuration
**Browser:** Chrome Version 44.0.2403.155

**Operating system:** Ubuntu 15.04

### Logs

I do not think that the below matters in this case

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by integras** [comment]
I forgot to mention: from the behaviour of the sync client the same problem seems to exist for files too. I have not investigated thoroughly though, so this should merely be taken as a hint. Thanks!

**Comment by integras** [comment]
Further investigation shows that this is limited to Calendars, files are shared properly via LDAP groups. Please disregard my last comment.

**Comment by integras** [comment]
And some more tests show that while files are ok, contacts are also affected. That means that Calendar and Contacts do not work as expected anymore

**Comment by PVince81** [comment]
@blizzz not sure what changed with sharing/LDAP that would break calendar/contact sharing in 6.0.9

**Comment by blizzz** [comment]
Neither do I know what changed back than. Given that OC 6 is EOL (https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule) and there are DB issues present as pointed out in the description I honestly don't feel like looking into it, especially because there will be no more OC 6 releases a fix could go into. Closing therefore, sorry.
