### ISSUE TITLE
Error updating owncloud 8.0.2 to 8.0.4 or higher on a QNAP

### ISSUE THREAD

**Issue by fglasena** [owncloud/core#18595]
This error was generated when I tried to update my running owncloud 8.0.2 instance to a higher version i.e. 8.0.4 or even 8.1.1. Owncloud is installed on a QNAP TS 239Pro+ with QTS 414 and PHP 5.5.26 as an App. I use contacts and calendar apps with owncloud and know that these have to be exchanged if I udate from 8.0.x to 8.1.x:

An exception occurred while executing 'ALTER TABLE oc_contacts_cards ENGINE=InnoDB;': SQLSTATE[HY000]: General error: 1598 Binary logging not possible. Message: Transaction level 'READ-COMMITTED' in InnoDB is not safe for binlog mode 'STATEMENT'

**Comment by RealRancor** [comment]
Hi,

have a look at: https://doc.owncloud.org/server/8.0/admin_manual/maintenance/upgrade.html#troubleshooting where the needed MySQL config change is documented.

You should also find plenty of bugreports here like https://github.com/owncloud/core/issues/16008

**Comment by fglasena** [comment]
Thanks RealRancor. Perfect, it works. Update was ok! First of all I used phpmyadmin to set the sql command SET GLOBAL binlog_format = 'MIXED' for server localhost, then to be sure that everything is still set after reboot I changed /etc/my.cnf by inserting binlog-format=MIXED behind log-bin=mysql-bin. I hope that this will do it.

Friedrich
