### ISSUE TITLE
Unable to Update Private Key in 8.1.1 with LDAP

### ISSUE THREAD

**Issue by gnohp** [owncloud/core#18607]
### Steps to reproduce
1. Start with 8.0.4
2. Configure LDAP app to allow users to login using sAMAccountName and identifier to be objectGUID
3. Enable encryption 
4. Log in with AD user
5. Change user password
6. Log out
7. Upgrade to 8.1.1
8. Enable encryption app
9. Execute occ encryption:migrate
10. Log in to ownCloud
11. Go to Name > Personal
12. Type old password in the Old Password textbox
13. Type new password in the New Password textbox
14. Click Update Private Key button

### Expected behaviour
Was expecting the message Private key password successfully updated.

### Actual behaviour
Fails and always throws The current log-in password was not correct, please try again although password is correct.

### Workaround
With the current configuration, UID stores the objectGUID and not the user login id. This is then passed as an argument in checkPassword which fails. I modified the file settingscontroller.php under apps/encryption/controller:

public function updatePrivateKeyPassword(...) {
...
  $uid = $this->userSession->getUser()->getUID();
  // Code added here
  $uname = $this->userSession->getLoginName();
  ...
  //check if password is correct (Modified: changed first argument from $uid to $uname)
  $passwordCorrect = $this->userManager->checkPassword($uname, $newPassword);
  ...
...
}  

### Server configuration
**Operating system**:
CentOS 6.6

**Web server:**
Apache

**Database:**
Galera Cluster

**PHP version:**
5.6

**ownCloud version:** (see ownCloud admin page)
8.1.1

**Updated from an older ownCloud or fresh install:**
8.0.4

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
ActiveDirectory

**Comment by karlitschek** [comment]
@schiesbn can you have a look please?

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/18556

**Comment by schiesbn** [comment]
Fixed in master, backport for 8.1.4 is here: https://github.com/owncloud/core/pull/18747
