### ISSUE TITLE
[daily-master] internal server error on smashbox execution

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#18600]
see https://ci.owncloud.org/job/smashbox-on-docker-daily-master/DOCKER_IMAGE=ubuntu_oc_lamp_redis,TEST_NAME=test_shareFile,compiler=g++,label=master,mirallBranch=v1.8.3,qt=qt4,serverVersion=daily-master,slave=SMASH/35/console

curl: (22) The requested URL returned error: 500 Internal Server Error

@nickvergessen @jmaciasportela mind taking a look? THX

**Comment by jmaciasportela** [comment]
Hey @DeepDiver1975 the image ubuntu-lamp-redis has not the last changes to detect if the container is ready.

I can add last enhancements to this image, and modify jenkins script to use it, but I'm traveling to Berlin just now. Tomorrow morning?

Stop the last execution, is on unfinishable loop.

**Comment by PVince81** [comment]
@DeepDiver1975 still happening ?

**Comment by DeepDiver1975** [comment]
this issue is solved - yes
