### ISSUE TITLE
Class 'Pimple\\Container' not found  (when multi installs)

### ISSUE THREAD

**Issue by Samarian78** [owncloud/core#18604]
As advised here:  https://forum.owncloud.org/viewtopic.php?f=31&t=30097

### Steps to reproduce
1. Install owncloud in two completely separate locations (separate databases and datafiles)  - hereon referred to as an 'Instance', using the setup-owncloud.php script.
2. Restart the apache2 service
3. Try and access each of the instances

### Expected behaviour
Both instances should be accessible

### Actual behaviour
Both instances install and work fine to begin, HOWEVER:

Any service restart of Apache2 after this point causes ONE of the instances to error out with the following error:

PHP Fatal error:  Class 'Pimple\\Container' not found in /var/www/clients/client0/web2/web/lib/private/appframework/utility/simplecontainer.php on line 36

As to which one works and which one errors out follows this critera:

- If Instance1 is accessed first after the service restart, then Instance2 will fail.
- If Instance2 is accessed first after the service restart, then Instance1 will fail.

I will note at this point I have tried this multiple times, and the error occurs even on fresh installs. The error also occurs DURING install of the second instance, if the apache service is restarted after the install of the first instance.

### Server configuration
**Operating system**:
Ubuntu 14.04.3 LTS

**Web server:**
Apache/2.4.7
w/ ISPConfig and multiple domains

**Database:**
mysqld 5.5.44-0ubuntu0.14.04.1

**PHP version:**
5.5.9-1ubuntu4.11

**ownCloud version:** (see ownCloud admin page)
8.1.1

**Updated from an older ownCloud or fresh install:**
Fresh Install

**List of activated apps:**
Enabled:
 - activity: 2.0.1
 - files: 1.1.9
 - files_locking:
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.6
Disabled:
 - encryption
 - external
 - files_external
 - user_external
 - user_ldap
 - user_webdavauth

**The content of config/config.php:**
sudo -u www-data php occ config:list system --public
Returns:
[InvalidArgumentException]
  There are no commands defined in the "config" namespace.

...
Instance1:
$CONFIG = array (
  'instanceid' => 'ocp6vutgqqob',
  'passwordsalt' => *REMOVED*
  'secret' => *REMOVED*
  'trusted_domains' =>
  array (
    0 => 'cloud.DOMAIN1REMOVED.com',
  ),
  'datadirectory' => '/var/www/clients/client1/web14/private/data',
  'overwrite.cli.url' => 'http://cloud.DOMAIN1REMOVED.com',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'c1cloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'c1cloud',
  'dbpassword' => *REMOVED*
  'logtimezone' => 'UTC',
  'installed' => true,
);

Instance2:
$CONFIG = array (
  'instanceid' => 'ocmsjbr96l2q',
  'passwordsalt' => '*REMOVED*',
  'secret' => '*REMOVED*',
  'trusted_domains' =>
  array (
    0 => 'cloud.DOMAIN2REMOVED.com',
  ),
  'datadirectory' => '/var/www/clients/client3/web16/private/data',
  'overwrite.cli.url' => 'http://cloud.DOMAIN2REMOVED.com',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'c3cloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'c3cloud',
  'dbpassword' => '*REMOVED*',
  'logtimezone' => 'UTC',
  'installed' => true,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
NA

#### Web server error log
[Thu Aug 27 15:33:40.342924 2015] [:error] [pid 8823] [client 192.168.0.1:62233] PHP Warning:  is_file(): open_basedir restriction in effect. File(/var/www/clients/client3/web16/web/3rdparty/pimple/pimple/src/Pimple/Container.php) is not within the allowed path(s): (/var/www/clients/client1/web14/web:/var/www/clients/client1/web14/private:/var/www/clients/client1/web14/tmp:/var/www/cloud.andyturner.online/web:/srv/www/cloud.andyturner.online/web:/usr/share/php5:/usr/share/php:/tmp:/usr/share/phpmyadmin:/etc/phpmyadmin:/var/lib/phpmyadmin:/dev) in /var/www/clients/client3/web16/web/3rdparty/composer/ClassLoader.php on line 383
[Thu Aug 27 15:33:40.342963 2015] [:error] [pid 8823] [client 192.168.0.1:62233] PHP Fatal error:  Class 'Pimple\\Container' not found in /var/www/clients/client1/web14/web/lib/private/appframework/utility/simplecontainer.php on line 36

#### ownCloud log (data/owncloud.log)
Empty (fresh install)

#### Browser log
NA

**Comment by Xenopathic** [comment]
> PHP Warning: is_file(): open_basedir restriction in effect. File(/var/www/clients/client3/web16/web/3rdparty/pimple/pimple/src/Pimple/Container.php) is not within the allowed path(s): (/var/www/clients/client1/web14/web:/var/www/clients/client1/web14/private:/var/www/clients/client1/web14/tmp:/var/www/cloud.andyturner.online/web:/srv/www/cloud.andyturner.online/web:/usr/share/php5:/usr/share/php:/tmp:/usr/share/phpmyadmin:/etc/phpmyadmin:/var/lib/phpmyadmin:/dev) in /var/www/clients/client3/web16/web/3rdparty/composer/ClassLoader.php on line 383

You need to add the relevant directories to `open_basedir` in `php.ini`

**Comment by Samarian78** [comment]
That's fair enough I can do that or disable the open_basedir all together.    
I'm still baffled by though.  Any ideas as to why the error only occurs with more than one instance of owncloud?

**Comment by DeepDiver1975** [comment]
> Any ideas as to why the error only occurs with more than one instance of owncloud?

most probably some side effects .... closing since the fix seems obvious

**Comment by cwallbaum** [comment]
I had the same issue. My problem was the php cache. I deactivated xcache/opcache et voila: my two oc instances run flawlessly side by side.

**Comment by Samarian78** [comment]
Thankyou for this useful feedback cwallbaum.  I may circle back and give this product another chance later this week.

~Andy
