### ISSUE TITLE
Sidebar filename tooltip mispositioned

### ISSUE THREAD

**Issue by Xenopathic** [owncloud/core#18601]
With a short filename that does not result in an ellipsis, the tooltip is mispositioned to the center of the element instead of on the text.

![screenshot_2015-08-27_12-33-37](https://cloud.githubusercontent.com/assets/2016878/9519608/f181ddf0-4cb7-11e5-81ec-975ad6832abb.png)

cc @PVince81 @jancborchardt

**Comment by jancborchardt** [comment]
Needs to be fixed by setting display:inline-block and adjusting the layout.
