### ISSUE TITLE
Very slow user management 

### ISSUE THREAD

**Issue by witchi** [owncloud/core#18603]
We have a lot of users (250+) and if you open the user management screen you have to wait few minutes to complete the request. Please order the users by name in different tabs, so you have only to load the users for one tab in a request, it will increase the usability of the tool.

Thanks
Andre

**Comment by DeepDiver1975** [comment]
Which OC Version?

**Comment by witchi** [comment]
8.1.0

**Comment by witchi** [comment]
As tab I mean a letter of the alphabet or a digit, so you could have i.e. 26 tabs (some tabs could contain a range like x-z) plus 10 tabs for every digit.

**Comment by MorrisJobke** [comment]
UX -> @jancborchardt

**Comment by jancborchardt** [comment]
Well – lazy loading is the solution to this.

**Comment by DeepDiver1975** [comment]
from my understanding there is already a report about this issue somewhere -> closing. THX
