### ISSUE TITLE
Special folder icons also for starred folders

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#18617]
With the new filetype icons, I also added a folder icon for `icon-starred` we should use that for starred folders.

@owncloud/designers @PVince81 @blizzz

**Comment by PVince81** [comment]
What's priority for the icon ?

Which of of these should win if applied at the same time:
- shared
- external storage
- starred

**Comment by jancborchardt** [comment]
I’d say in that order that you listed, shared is at the top.

**Comment by DeepDiver1975** [comment]
9.0 - we are beyond feature freeze

**Comment by stefan-niedermann** [comment]
>What's priority for the icon ?
>
>Which of of these should win if applied at the same time:
>
>    shared
>    external storage
>    starred

why not at the same time? the android client does the same - showing starred and downloaded-images at the same time.

**Comment by jancborchardt** [comment]
> why not at the same time?

@stefan-niedermann that’s already the case – there is a star indicator on the left next to the filetype icon.
