### ISSUE TITLE
IE8 issues with new design

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#18619]
![bildschirmfoto von 2015-08-27 23-51-17](https://cloud.githubusercontent.com/assets/245432/9534103/a954d2f8-4d16-11e5-8c85-9791eebafe7d.png)
![bildschirmfoto von 2015-08-27 23-50-59](https://cloud.githubusercontent.com/assets/245432/9534106/aa78e624-4d16-11e5-8566-b4a484a67320.png)

@jancborchardt ;)

**Comment by jancborchardt** [comment]
@MorrisJobke yeah, the filetype icons I also noticed – I need to export them properly in 48px. Will do on Sunday or so when I have more time.

**Comment by jancborchardt** [comment]
For the log in screen
* So background-size doesn’t work. I would suggest to remove the text in the actual logo. This will also directly solve it in the installation and password protect page.
* Where’s the button?
* For the width maybe we need an .ie8 specific fix CSS line?

**Comment by aspdye** [comment]
The IE 8 is not longer integrated in an modern OS that is supported in Mainstream Support. Vista, 7, 8, 8.1, 10 have at least IE 9, 10, 11 or EDGE. XP is not longer supported. And Vista SP 1 users still having IE 8 should update asap. Users without the newest service packs and updates are not supported by Microsoft this time (Vista)

However, IE 8 is supported in Vista SP 1 until 01/2016. 

IE 8 does not support modern web apps and i think oC  should not try to do. Thats not longer neccesary. 

https://support.microsoft.com/en-us/gp/microsoft-internet-explorer

**Comment by MorrisJobke** [comment]
> IE 8 does not support modern web apps and i think oC should not try to do. Thats not longer neccesary.

We should and we will: #15567 ;)

**Comment by PVince81** [comment]
Cute little cloud in the login page

**Comment by davitol** [comment]
LDAP wizard does not work properly.
Also the icons from the sidebar are broken.

**Comment by jancborchardt** [comment]
cc @blizzz for the LDAP wizard – that’s a separate issue.

@davitol can you show a screenshot of the sidebar icons?

**Comment by davitol** [comment]
@jancborchardt Sidebar icons & checkboxes snapshots:

![filesidebb](https://cloud.githubusercontent.com/assets/10596560/10039322/12cd6104-61d1-11e5-9219-97aa9a29cacd.png)
![filesideb](https://cloud.githubusercontent.com/assets/10596560/10039327/17195e34-61d1-11e5-9c69-99c8cc028681.png)

**Comment by jancborchardt** [comment]
cc @Henni for the checkboxes.

@MorrisJobke @Henni @owncloud/designers do you have any idea how we handle the filetype icons? Background-size is not available in internet explorer. Maybe we could have an .ie8 rule which makes the container smaller or something like that?

**Comment by blizzz** [comment]
Checkboxes display value was set to none here https://github.com/owncloud/core/pull/18735/files#diff-463c027b5536faafc395f8fd4d09792bR166

**Comment by Henni** [comment]
@blizz this is intended as we replace the checkboxes with images.

See #19301 for a fix for checkboxes in ie8

**Comment by PVince81** [comment]
(Blizzz with 3 z :wink:)

**Comment by davitol** [comment]
LDAP buttons that do not appear:
- Add new conf
- Copy current conf

![ldapicon8](https://cloud.githubusercontent.com/assets/10596560/10067917/88098a18-62a0-11e5-9c1e-648f00759d71.png)

**Comment by raghunayyar** [comment]
Oh lord.

**Comment by PVince81** [comment]
From master, seems now the checkboxes are shown everywhere: (CC @Henni)
![ie8-ewwww](https://cloud.githubusercontent.com/assets/277525/10141271/e10b2d4c-660b-11e5-86bb-27835857e984.png)

**Comment by PVince81** [comment]
and the header is shifted

**Comment by karlitschek** [comment]
argh

**Comment by PVince81** [comment]
Yes, next time a design overhaul is done, please also allocate time for fixing IE8.

- [ ] logo + password field: https://github.com/owncloud/core/pull/19451
- [ ] checkboxes

**Comment by PVince81** [comment]
- [ ] file name width too large, makes clicking the space for sidebar not work properly
![ie8-madness-filenamewidth](https://cloud.githubusercontent.com/assets/277525/10169247/85890d3e-66d0-11e5-87f4-bebbb32ebf8e.png)

The reason why it's large is because of a former IE8 fix, which we can't remove because then the file name becomes too narrow... need to invent a new fix, or disable the "click on empty space" for the sidebar and force IE8 users to use the "Details" menu item.

**Comment by PVince81** [comment]
- [ ] file type icons PNG are too big: 48x48 but we need 32x32.
- [ ] file type icon in sidebar requires even bigger size, would need yet another PNG version of them...

**Comment by PVince81** [comment]
- [ ] "New" menu also needs smaller PNG icons, seems to be 16x16

**Comment by PVince81** [comment]
- [ ] missing borders in dropdown/popovers, probably because IE8 doesn't support drop shadow ("New" menu and actions menu)

**Comment by PVince81** [comment]
I fixed the icons, please review https://github.com/owncloud/core/pull/19454

**Comment by davitol** [comment]
Icons for 'special actions' done on folder, are not well-centered in the foldel icon. e.g.

![screen shot 2015-09-30 at 10 08 25](https://cloud.githubusercontent.com/assets/10596560/10187827/626da0e0-675b-11e5-913a-2af8e662347d.png)

**Comment by PVince81** [comment]
- [ ] "New" menu button is too wide

**Comment by PVince81** [comment]
- [ ] issue with some mime type icons (empty text file): https://github.com/owncloud/core/pull/19468

**Comment by PVince81** [comment]
Note to self: this b94f7d38f6e13825fd34c7113827d3c369a689ad is the commit before the custom checkbox styles were introduced, here the alignment is correct. Now to find out the CSS rules that breaks the alignment.

**Comment by PVince81** [comment]
The problem with checkboxes: the DOM layout has changed to make it work with the new checkbox styles. However the CSS is trying to make it look like before, and this breaks the layout.
So now trying to make IE8 use the new checkboxes styles instead...

**Comment by Henni** [comment]
@PVince81 Probably won't work, as IE8 doesn't support `:checked`

**Comment by PVince81** [comment]
Yes, so I tried using `[checked=checked]` as a workaround, but it turns out that IE8 doesn't always set the attribute "checked" to true when clicking a label...

**Comment by PVince81** [comment]
So looks like we're doomed to do pixel pushing in IE8 to make it look like it should instead of making it use the new checkbox style, because the old styles do not fit with the new layout. ("input" box vs "input + label:before"

**Comment by PVince81** [comment]
Ok, let's try and bring back the old styles using `:not(.ie8)`. Since IE8 itself doesn't support `:not` it will ignore these rules...

**Comment by Henni** [comment]
`checked=checked` is an attribute. The browsers only update the **property** which isn't represented in the dom.

**Comment by PVince81** [comment]
Yeah, that sucks

**Comment by PVince81** [comment]
I also found this polyfill: https://github.com/rdebeasi/checked-polyfill/blob/master/checked-polyfill.js
But it would require us to call its function every time we dynamically create checkboxes, not convenient at all.

**Comment by PVince81** [comment]
Ok, I'm close to a solution, PR will follow soon. The trick was to exclude the new styles in files.css with `html:not(.ie8)`

**Comment by PVince81** [comment]
Checkboxes fix: https://github.com/owncloud/core/pull/19484

**Comment by PVince81** [comment]
- [ ] Select some files, see how the "Delete" action is hanging in the air (it also does that in stable8.1), looks shitty

**Comment by Bullnados** [comment]
how mich time did you invest for supporting a nearly dead Browser?

**Comment by MorrisJobke** [comment]
> how mich time did you invest for supporting a nearly dead Browser?

There was a long discussion on this #15567 we will support it in 8.2.

**Comment by PVince81** [comment]
- [ ] ridiculously small trash icon
![ie8-trash-icon](https://cloud.githubusercontent.com/assets/277525/10200683/202d492c-67a8-11e5-9a21-63af91fcdf86.png)

**Comment by PVince81** [comment]
I haven't looked everywhere, there might be more :wink: 

I intend to focus on https://github.com/owncloud/core/issues/18619#issuecomment-144096505 that is important for the sidebar, and maybe https://github.com/owncloud/core/issues/18619#issuecomment-144464342

Everything else should be raised later as separate less important tickets.

**Comment by MorrisJobke** [comment]
@butonic The ticket you merged only solved one of many issues ;)

**Comment by PVince81** [comment]
Let's raise the remaining issue as separate tickets

**Comment by PVince81** [comment]
@davitol please raise a separate issue for the LDAP wizard: https://github.com/owncloud/core/issues/18619#issuecomment-142842169

Raised other minor issues here https://github.com/owncloud/core/issues/19527
