### ISSUE TITLE
[Login screen] Login arrow should be located in the same place, regardless the browser

### ISSUE THREAD

**Issue by davitol** [owncloud/core#18629]
Chrome (ouside)
![chromelog](https://cloud.githubusercontent.com/assets/10596560/9549094/7ebbe494-4da4-11e5-9209-9b657dea4e38.png)

Firefox (inside)

![mozillalog](https://cloud.githubusercontent.com/assets/10596560/9549099/83dd724e-4da4-11e5-962c-4e3e5f8d30ec.png)

"version":"8.2.0.4","versionstring":"8.2 pre alpha","edition":"Enterprise"

**Comment by raghunayyar** [comment]
I see it uniform across my chrome / firefox as well as safari. Can you mention the version you are talking about? Thx @davitol

**Comment by davitol** [comment]
@raghunayyar 
Firefox 40.0.3 
Chrome 44.0.2403.157 (64-bit) 
Both of them in mac OSX Yosemite

**Comment by PVince81** [comment]
cc @jancborchardt who worked on the arrow

**Comment by raghunayyar** [comment]
This seems like the enterprise one seeing the screenshot, the community one doest have that issue (on Yosemite at least. cc @jancborchardt

**Comment by davitol** [comment]
@raghunayyar Same behaviour in community version. The screenshot is from Chrome browser

![captura de pantalla 2015-08-30 a las 16 24 39](https://cloud.githubusercontent.com/assets/10596560/9567624/2285d73a-4f33-11e5-8bd8-ed53c023d63d.png)

**Comment by raghunayyar** [comment]
@davitol can you delete your cache? because, I am also on Yosemite and I can't reproduce this on Chrome / FF / Safari. I am so sorry to ask this again and again though. thx.

**Comment by jancborchardt** [comment]
The button needs to be in the same container as the input fields. But yeah, can you please clear your cache first and also test it with an incognito browser?

**Comment by davitol** [comment]
Cleaning the cache and using an incognito tab in chrome does not solve my problem in my laptop. But testing in another computers with the same configuration and versions, it seems to work fine. :confused:

**Comment by raghunayyar** [comment]
@davitol check my PR.

**Comment by MorrisJobke** [comment]
@davitol I checked the PR and it fixes this issue.
