### ISSUE TITLE
Thumbnail of shared file not updated on change

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#18633]
1. Upload a picture
2. Share it with someone
3. Other person edits file
4. You still see the initial thumbnail image, even in the detail view

@oparoz @georgehrke

**Comment by oparoz** [comment]
On master, you shouldn't get the old one in the slideshow. If that's the case ,then it's a regression in Gallery.

Regarding the thumbnail, there is already a ticket about it. I think a hook is missing in Preview.

**Comment by PVince81** [comment]
Wasn't there a recent fix for this ?

**Comment by PVince81** [comment]
Might or might not be related: https://github.com/owncloud/core/issues/18759

**Comment by PVince81** [comment]
Still happening on master (67231ed9a75eafe5b417e4525e3d80b1a3f8826b)

**Comment by oparoz** [comment]
Duplicate of https://github.com/owncloud/core/issues/14572
