### ISSUE TITLE
[Login window] Password textbox becomes smaller when writing down the password using IE9 as browser

### ISSUE THREAD

**Issue by davitol** [owncloud/core#18634]
![reduccion](https://cloud.githubusercontent.com/assets/10596560/9551432/701c8300-4db1-11e5-87df-dacab47e94be.png)

OC server version: "8.2.0.4","versionstring":"8.2 pre alpha"
Browser: Internet Explorer 9

**Comment by jancborchardt** [comment]
This is such a tiny issue we shouldn’t waste time trying to fix it. Let’s focus on the important issues instead and prioritize the really breaking issues in IE: https://github.com/owncloud/core/issues/18619
