### ISSUE TITLE
When Group admin attempts to delete the Ownclouds Superadmin in user panel, GUI behavior is suboptimal.

### ISSUE THREAD

**Issue by farson2003** [owncloud/core#18649]
Steps to reproduce:

 Have a „Superadmin“ who has „all rights“ (the actual main admin of Owncloud) and is member of “group A”, “group B”, and “group admin”.

Create a group A with users as well as one group admin for group A.
Create a group B with users as well as one group admin for group B.

When group admin for group A logs in and goes to the user panel he now sees all users in group A including the Superadmin.

When group admin for group A clicks on the delete button to delete the superadmin, the deletion apparently takes place (including the yellow message “deleted superadmin undelete) until the page is refreshed, when it returns back to the unedited user list. 

This behavior is not ideal, as it ínitially implies some changes did in fact take effect. Instead an error, e.g. “You have no rights to delete this user’s name” should appear.

**Comment by Xenopathic** [comment]
Please only open one issue for a report -> #18650
