### ISSUE TITLE
When Group admin attempts to edit the Ownclouds Superadmin’s “Full Name“, GUI behavior is suboptimal.

### ISSUE THREAD

**Issue by farson2003** [owncloud/core#18647]
Steps to reproduce:

Have a „Superadmin“ who has „all rights“ (the actual main admin of Owncloud) and is member of “group A”, “group B”, and “group admin”.

Create a group A with users as well as one group admin for group A.
Create a group B with users as well as one group admin for group B.

When group admin for group A logs in and goes to the user panel he now sees all users in group A including the Superadmin.

When group admin for group A is trying to edit the Superadmin’s “Full Name“, the changes apparently take effect, until the page is refreshed, when it returns back to the unedited name. 

This behavior is not ideal. Instead an error,e.g. “You have no rights to change this user’s name” should appear.

**Comment by Xenopathic** [comment]
Please only open one issue for a report -> #18650
