### ISSUE TITLE
Unable to setup some apps getting cURL error 60: SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by mazate** [owncloud/core#18643]
I'm getting this error when trying to setup calendar and contacts apps:

cURL error 60: SSL certificate problem: unable to get local issuer certificate

I would love to know what is causing this since it seems to have followed me from a different hosting provider.  I changed providers just to get around this and here it is again...  Thanks for the assistance.

**Comment by mazate** [comment]
P.S. I was getting this error even before installing the SSL.

**Comment by RealRancor** [comment]
Sure you're getting this before the activation of SSL as this message only appears for the SSL connection to the appstore and not your server.

For the error itself see: https://forum.owncloud.org/viewtopic.php?f=17&t=29790

**Comment by mazate** [comment]
That page doesn't address the error I'm getting. I appreciate your linking
skills but specific steps to address the problem would be appreciated.




On Fri, Aug 28, 2015 at 4:08 PM, RealRancor < notifications@github.com [notifications@github.com] > wrote:
Sure you're getting this before the activation of SSL as this message only
appears for the SSL connection to the appstore and not your server.

For the error itself see: https://forum.owncloud.org/viewtopic.php?f=17t=29790]

—
Reply to this email directly or view it on GitHub
[https://github.com/owncloud/core/issues/18643#issuecomment-135907875] .[https://github.com/notifications/beacon/ANWugWrHPGax6_20M_Xy7H-_dhEGIGMhks5osOF0gaJpZM4F0T2z.gif]

**Comment by RealRancor** [comment]
That page IS giving you pointers what to check...

**Comment by RealRancor** [comment]
Btw. especially the issue with buggy OpenSSL/NSS versions (https://github.com/owncloud/core/issues/17446) is described there. You will also get this error if you're missing the config/ca-bundle.crt.

I'm not pointing you to this FAQ just for fun. :see_no_evil:
