### ISSUE TITLE
When "one click update" for an app is available Owncloud instance should send an email to admin.

### ISSUE THREAD

**Issue by farson2003** [owncloud/core#18646]
As the title suggests:
When "one click update" for an app is available Owncloud should send an email to admin.

**Comment by RealRancor** [comment]
Dup of https://github.com/owncloud/core/issues/17373

**Comment by RealRancor** [comment]
@karlitschek I think its not needed to tag this as an enhancement as the same is already available here: https://github.com/owncloud/core/issues/17373 and tagged correctly.

**Comment by karlitschek** [comment]
agree.d let's close :-)
