### ISSUE TITLE
Root storage scan must not enter user's folders

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#18656]
Whenever a user was deleted but the home folder still exists, it can happen that when the root storage is rescanned it will enter the user's folders.

I suggest to restrict the root storage rescan to the first level. It doesn't make much sense to go deeper ?

@icewind1991 @schiesbn

**Comment by PVince81** [comment]
It might even be scanning into the user's folder as if it was a simple folder.
Or does the global files:scan --all automatically mount every user's homes ? I doubt it.

@icewind1991

**Comment by PVince81** [comment]
CC @MorrisJobke

**Comment by MorrisJobke** [comment]
I can't reproduce this

**Comment by PVince81** [comment]
@icewind1991 pointed out that maybe it's happening inside a cron job.
It is also more likely to happen if `filesystem_check_changes` is 1 instead of 0.

**Comment by PVince81** [comment]
From what I remember when investigating this issue with @MorrisJobke, we noticed that it never actually entered the user's folders in recent versions. There was an older bug where it would go there whenever it had entries with size -1 but it was fixed.
