### ISSUE TITLE
First run wizard does not load the first time we log in OC

### ISSUE THREAD

**Issue by davitol** [owncloud/core#18657]
### Steps to reproduce

1. Open OC for the first time

### Expected behaviour

The 'welcome window' should be loaded with all the info

### Actual behaviour
The 'welcome window' is not loaded

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:"OC version "version":"8.2.0.4","versionstring":"8.2 pre alpha"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
  - activity: 2.1.2
  - files: 1.1.11
  - files_locking: 
  - files_pdfviewer: 0.7
  - files_sharing: 0.6.2
  - files_texteditor: 0.4
  - files_versions: 1.0.6
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - provisioning_api: 0.2
  - templateeditor: 0.1
  - updater: 0.6
Disabled:
  - encryption
  - external
  - files_external
  - files_trashbin
  - gallery
  - user_external
  - user_ldap
  - user_webdavauth

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox
![captura de pantalla 2015-08-29 a las 18 37 15](https://cloud.githubusercontent.com/assets/10596560/9563171/42a7765c-4e7c-11e5-8c8d-b275b43ab760.png)

**Comment by DeepDiver1975** [comment]
Server logs?
Browser logs?

**Comment by karlitschek** [comment]
I can reproduce this with the nightly build

**Comment by davitol** [comment]
server log:

{"reqId":"7rmKptPZxhlziLxmSq6P","remoteAddr":"141.23.106.91","app":"PHP","message":"fopen(\/opt\/owncloud\/config\/config.php): failed to open stream: No such file or directory at \/opt\/owncloud\/lib\/private\/config.php#188","level":3,"time":"2015-09-02T14:39:32+00:00"}
{"reqId":"npLbafw14yAE1nkcWf1K","remoteAddr":"141.23.106.91","app":"index","message":"Exception: {\"Exception\":\"RuntimeException\",\"Message\":\"image not found: image:places\\\/folder.svg webroot: serverroot:\\\/opt\\\/owncloud\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/lib\\\/public\\\/util.php(418): OC\\\\URLGenerator->imagePath('core', 'places\\\/folder.s...')\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/firstrunwizard\\\/templates\\\/wizard.php(51): OCP\\\\Util::imagePath('core', 'places\\\/folder.s...')\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/template\\\/base.php(160): include('\\\/opt\\\/owncloud\\\/a...')\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/template\\\/base.php(138): OC\\\\Template\\\\Base->load('\\\/opt\\\/owncloud\\\/a...')\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/template.php(125): OC\\\\Template\\\\Base->fetchPage()\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/template\\\/base.php(121): OC_Template->fetchPage()\\n#6 \\\/opt\\\/owncloud\\\/apps\\\/firstrunwizard\\\/wizard.php(40): OC\\\\Template\\\\Base->printPage()\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(154) : runtime-created function(1): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#8 [internal function]: __lambda_func(Array)\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(280): call_user_func('?lambda_28', Array)\\n#10 \\\/opt\\\/owncloud\\\/lib\\\/base.php(896): OC\\\\Route\\\\Router->match('\\\/apps\\\/firstrunw...')\\n#11 \\\/opt\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/lib\\\/private\\\/urlgenerator.php\",\"Line\":189}","level":4,"time":"2015-09-02T14:39:35+00:00"}

**Comment by SergioBertolinSG** [comment]
This is fixed with last master in community version, but not in enterprise.

**Comment by cmonteroluque** [comment]
https://github.com/owncloud/core/issues/18657#issuecomment-142203938 @DeepDiver1975 ?

**Comment by nickvergessen** [comment]
Fix is here https://github.com/owncloud/firstrunwizard/pull/31

**Comment by SergioBertolinSG** [comment]
Working fine in master.
