### ISSUE TITLE
Files: The right sidebar should'nt be visible if the file is clicked to drag.

### ISSUE THREAD

**Issue by raghunayyar** [owncloud/core#18652]
### Steps to reproduce
1. Open files app.
2. Long press on a file to drag

### Expected behaviour
Drag shouldn't open the sidebar.

### Actual behaviour
It opens the sidebar.

@owncloud/designers @jancborchardt

**Comment by PVince81** [comment]
See #18238 and review the proposed alternative PR

**Comment by MorrisJobke** [comment]
> See #18238 and review the proposed alternative PR

#18273

**Comment by jancborchardt** [comment]
Basically the sidebar should only open on keyup (mouse release), not on keydown.

**Comment by PVince81** [comment]
Or not at all, if we go with the toggle button / "Details" menu entry approach

**Comment by jancborchardt** [comment]
Right, yes. That’s probably less confusing in the first place. It will also be simpler as soon as sharing and versions invokes the sidebar anyway.

**Comment by MorrisJobke** [comment]
> Or not at all, if we go with the toggle button / "Details" menu entry approach

I really would like this :)

**Comment by PVince81** [comment]
@MorrisJobke then please test and comment https://github.com/owncloud/core/pull/18273 (and find people to do the same)
I won't continue until I get a green light from you guys that it is what we want.

**Comment by PVince81** [comment]
Obsoleted by https://github.com/owncloud/core/pull/18273
