### ISSUE TITLE
error while upgrading 7.0.4 to 8.1.1

### ISSUE THREAD

**Issue by novazur** [owncloud/core#18665]
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO `oc_oc_appconfig_66qc8dt5rupm2` SELECT * FROM `oc_appconfig`': SQLSTATE[HY000]: General error: 1665 Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at least one table uses a storage engine limited to row-based logging. InnoDB is limited to row-logging when transaction isolation level is READ COMMITTED or READ UNCOMMITTED.

**Comment by RealRancor** [comment]
Documented here: https://doc.owncloud.org/server/8.1/admin_manual/maintenance/upgrade.html#troubleshooting

There are also tons of duplicated reported issue here, should be easy to find.

Please also be aware that a direct upgrade from oC 7.x to 8.1.x is not supported. You need to upgrade to oC 8.0.x first.

**Comment by PVince81** [comment]
The upgrade restriction didn't detect it properly, will be adressed here: https://github.com/owncloud/core/pull/18625
