### ISSUE TITLE
Provide public API for Storage implementations

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#18667]
Currently Storage implementations can be written, but need to use private APIs and extend private classes.
See https://github.com/owncloud/documentation/issues/1112.

A public API needs to be provided to make it possible for developers to provide their own home storages. Currently it is only possible using external storages (but I believe the API isn't that public either) which can only be mounted on subfolders, not the user's homes.

@icewind1991 @labkode @Xenopathic

**Comment by PVince81** [comment]
CC @DeepDiver1975 @karlitschek

**Comment by icewind1991** [comment]
Would also be a good opportunity to cleanup the storage interface

**Comment by PVince81** [comment]
At some point I suggested renaming oc_filecache to oc_fileindex, but @labkode said it's more a namespace and he might be right. Still, renaming the table will not work properly due to the way how migrations are done. See https://github.com/owncloud/core/issues/18027

However what we could do is rename (or name) the new public APIs with the new names, and maybe the private ones too (but there might be a risk of breaking ext storages).

**Comment by labkode** [comment]
@PVince81 The name we have at CERN for projects that deal with metadata is File catalog, and that is what it is. File catalog or File repository as you mentioned sound nice!

Some definitions:

http://searchsqlserver.techtarget.com/definition/catalog
http://alien2.cern.ch/index.php?option=com_content&view=article&id=53&Itemid=99

**Comment by icewind1991** [comment]
Wrote a quick proposal for a new, reduced storage interface: #18668

**Comment by labkode** [comment]
@icewind1991 I will reduce the interface even more. I don´t think anymore in local filesystems (folders, files) I think in resources (like WebDAV), and these resources can be of two types: containers/collections and objects.

For the data flow (get and put binary data) you just need two methods:
+ get(uri, range)
+ put(uri, data)

get can accept byte range requests and put can accept chunks.

For the metadata flow the minimal methods are:
+ getMetdata(uri)
+ list(containerUri)

All extra methods you add on top of this minimal set are just redundant.

With these 4 methods you can get most of the usability implemented in OC nowadays.

**Comment by labkode** [comment]
I forgot to mention;
+ rename(fromUri, toUri)
+ createContainer(uri)
+ remove(uri)

**Comment by icewind1991** [comment]
reduced it further

**Comment by PVince81** [comment]
@foobarable check this out

**Comment by DeepDiver1975** [comment]
9.0 topic.

**Comment by PVince81** [comment]
Storage API discussion here. https://github.com/owncloud/core/issues/20394

**Comment by PVince81** [comment]
Storage API has been improved and adjusted https://github.com/owncloud/core/issues/20401. Closing.
If there are remaining things that could be done for 9.1, please raise a separate ticket.
