### ISSUE TITLE
Add a external storage CDMI (Cloud Data Management Interface) standard support

### ISSUE THREAD

**Issue by ht68** [owncloud/core#18669]
How implement a new feature on owncloud, For add a new external storage CDMI (Cloud Data Management Interface) standard Support ?
For example in owncloud supported swift external storage, but not supported CDMI => http://www.snia.org/cdmi

**Comment by karlitschek** [comment]
a feature request for cdmi already exist. closing as duplicate.

**Comment by ht68** [comment]
not found issue for cdmi?
please help me

**Comment by karlitschek** [comment]
O.K. It seems that you are right. We talked about this for years so I assumed that someone has opened an issue for this already. But it seems that this is the first one. :-) reopened

**Comment by Xenopathic** [comment]
@karlitschek More to the point, this can be implemented as an app :smile: as per #18678
