### ISSUE TITLE
Malware injected in https://apps.owncloud.com/kb

### ISSUE THREAD

**Issue by prilly** [owncloud/core#18664]
Seems there has been injected malware on apps.owncloud.com

http://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?name=Backdoor%3aPHP%2fRST.AC&threatid=2147597022&enterprise=0

Windows defender reporting: backdoor:PHP/RST.AC upon entering this link: https://apps.owncloud.com/kb

**Comment by LukasReschke** [comment]
Thanks. We will look into this.

**Comment by LukasReschke** [comment]
Can you let us know what OS and browser you use? THX

**Comment by prilly** [comment]
yes ofcourse: Windows 7 ultimate 64bit and FireFox 40.0.3

**Comment by LukasReschke** [comment]
We do have some problems to reproduce this. Can you please let us know:

1. Do you see this kind of warning also on other pages?
2. If you see the warning can you save the page's HTML and send it to me? (you can find my profile in my mail address)

**Comment by prilly** [comment]
No, the warning is only loaded on this url: https://apps.owncloud.com/kb

i have looked throug the site html and it seems fine, normaly it would include a javascript or php code encoded in base 64 but i can not find it. the html is including alot of external javascript that is very large, all linked urls are possible places where the malicius code is hiding.

windows defender is not complaining directly on your sites html code, firefox do cache: 

file:C:\Users\Raymond\AppData\Local\Mozilla\Firefox\Profiles\9yaogjs5.default\cache2\entries\23AC7284B529448B41A90CAE2C3483DFEFB5F4C7

this cache file generated by your site is what windows security essentials is complaining about. sins iam on a workstation with server access i can not whitelist it and copy/open it to investigate what it contain.
