### ISSUE TITLE
debian repo packages for version 8.0.6 missing

### ISSUE THREAD

**Issue by Dani3lSun** [owncloud/core#18660]
The deb files for 8.0.6 are missing for debian 7 / 8. Is that normal?
For ubuntu the packages are available...
Repo URLs:
http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/Debian_8.0/
http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/Debian_7.0/

**Comment by RealRancor** [comment]
Seems a lot of builds of oC 8.0.x are failing (right box "Build Results").

https://build.opensuse.org/package/show/isv:ownCloud:community:8.0/owncloud

**Comment by LukasReschke** [comment]
@jnweiger

**Comment by Dani3lSun** [comment]
any news on this topic?

**Comment by tlei** [comment]
It seems, that this has been resolved by the regular upgrade to oC 8.0.8 (and not by active fixing from anyone): https://build.opensuse.org/package/show/isv:ownCloud:community:8.0/owncloud

**Comment by Dani3lSun** [comment]
ok haven´t seen that this release was today...anyway good to hear that the builds succeeded!
