### ISSUE TITLE
Admin panel shows cron is not run yet even though I ran the script manually.

### ISSUE THREAD

**Issue by tapir** [owncloud/core#18670]
So I've set up a cron job on my Ubuntu 15.04 box. Whatever I did, the admin panel was showing that the cron was not run yet. So I tried to run the cron.php manually to see if it has an effect. The script did not print any messages so I'm assuming it ran ok. To my surprise the admin panel still showed 'Cron was not executed yet!' message.

PS: I'm using ownCloud 8.1.1 and install it with 'occ'. I set the background job to cron with 'occ' as well.

Thanks

**Comment by RealRancor** [comment]
Hi,

check your data/owncloud.log if your cron was running successfully.

**Comment by tapir** [comment]
Turn out the problem was with apc. Thanks.

**Comment by RealRancor** [comment]
Hi,

yes thats why i have asked for data/owncloud.log. For further issues you want to report please also fill out the issue template provided here:

https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version

as asked in the "Guidelines for contributing" (linked in the yellow box when creating a new issue).
