### ISSUE TITLE
Select files with the checkbox open sidebar

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#18673]
Tested on master:

Try to select multiple files with the check boxes. The first file you select will open the side bar, the second one will close it again. After that it will stay closed for any additional file. The side bar should never open when the user selects multiple files.

cc @PVince81 @jancborchardt

**Comment by raghunayyar** [comment]
Already been tackled here : https://github.com/owncloud/core/pull/18273

**Comment by jancborchardt** [comment]
@schiesbn can you test that pull request?
