### ISSUE TITLE
How to add a cloud storage as external storage into owncloud

### ISSUE THREAD

**Issue by ht68** [owncloud/core#18678]
Hi all
I am going to add a new cloud storage based on CDMI standard, I wrote it, something like Swift or other storage which their plugins already exist in owncloud admin dashboard. The question is how can I do it? I mean, I decided to develop some parts of owncloud in order to support my own storage as an external storage, but I don't know what should I do and where should I change.

Regards

**Comment by Xenopathic** [comment]
Prior to oC 8.2, you can use `OC_Mount_Config::registerBackend()`, as of 8.2 you can still use that legacy function, or use the new BackendService API (although it's currently undocumented and will be moved into core for 9.0!). See files_external for examples and the classes themselves. #18676 might also be relevant for you.

In other words, it's a bit of a mess at the moment :disappointed:

**Comment by ht68** [comment]
Thanks for your concern. I looked at the source of where you mentioned, however, I got nothing! :) Is there any document for developing owncloud?anything, even for dummies!? :)

**Comment by ht68** [comment]
Thanks for your concern. I looked at the source of where you mentioned, however, I got nothing! Is there any document for developing owncloud? I read this doc: https://doc.owncloud.org/server/8.2/ownCloudDeveloperManual.pdf,  but there is no section about external storage.

**Comment by Xenopathic** [comment]
See apps/files_external/appinfo/app.php, apps/files_external/appinfo/application.php and apps/files_external/lib/backend/*.php

**Comment by DeepDiver1975** [comment]
Please get in touch with us on IRC .THX
