### ISSUE TITLE
When Owncloud update is available Owncloud instance should send an email to the admin

### ISSUE THREAD

**Issue by farson2003** [owncloud/core#18696]
When Owncloud update is available Owncloud instance should send an email to the admin (i.e. 8.0.0 to 8.0.1. and so on)..

Reopeneing of: https://github.com/owncloud/updater/issues/167

**Comment by aspdye** [comment]
Already available: https://mailman.owncloud.org/mailman/listinfo ;)
or just look at GitHub or the official Website (owncloud.org).

My idea: Weekly statistic mail: (Updates OwnCloud, User Activity Graphs, Storage, AND Updates etc.)

Will create a special reference for this.

**Comment by farson2003** [comment]
@aspdye @DeepDiver1975 Please reopen.

 I was not suggesting a weekly statistic email (which might be another reasonable idea), but just a simple email notification for admins when an update for a running Owncloud instance becomes available. - Not every admin wants weekly emails.
