### ISSUE TITLE
Share link broken whith official mobile android apps

### ISSUE THREAD

**Issue by kevinfly1** [owncloud/core#18694]
Hi,

We tried the Android official application plugged on the demo site (https://demo.owncloud.org/)
and we are facing the following issue :
- Sharing a file "toto.txt" by mail build a link like : https://demo.owncloud.org/index.php/s/xxxxxxxxxxx
-> This shared link work
- Then share the same file "toto.txt" again (which is already shared) by mail build a different link like https://demo.owncloud.org/public.php&se ... xxxxxxxxxx
-> This shared link doesn't work -> White page

Same issue on our internal installation based on owncloud 8.1.0

Can samebody help us ?
Thanks

**Comment by rperezb** [comment]
This is related to: https://github.com/owncloud/core/issues/14281
on iOS, the share link generation will change for oc8.2: https://github.com/owncloud/ios/commits/modify_share_link
on Android it will come soon too, expected for next release https://github.com/owncloud/android/issues/1127

**Comment by kevinfly1** [comment]
Thank you very much for your reply

**Comment by PVince81** [comment]
Closing as duplicate then

**Comment by rperezb** [comment]
and it should be fixed too :)
