### ISSUE TITLE
"apps.owncloud.com" spamming

### ISSUE THREAD

**Issue by aspdye** [owncloud/core#18698]
Hi,

In the last time, there is much spam at "apps.owncloud.com". As an "not-removed" example:
https://apps.owncloud.com/content/show.php/Go+onion?content=171220

I think we should check the apps before they are public ;)

Another question: What is the diffrence between "apps.owncloud.com" and the apps showed directly in "+ Apps"? I like the new "Experimental" "Official" etc. badges at "+ Apps". Maybe we should add them also on "apps.owncloud.com".

A bit like: #18201

**Comment by aspdye** [comment]
Same: https://apps.owncloud.com/content/show.php/premium+chat?content=171222

**Comment by DeepDiver1975** [comment]
There is a repo for appstore issues. THX
