### ISSUE TITLE
"Enable only for specific groups" of App shows it disabled in occ app:list

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#18690]
### Steps to reproduce
1. Install Calendar app
2. See that ./occ app:list shows the App as enabled
3. Restrict access to the app by using it to "Enable only for specific groups"
4. See that ./occ app:list shows the App as disabled

### Expected behaviour
App showing up as enabled in ./occ app:list

### Actual behaviour
App is not showing up as enabled in ./occ app:list

### Server configuration
**ownCloud version:** 8.1.1

I think everything else is not relevant for this issue but feel free to ask for more info if needed.

**Comment by cdamken** [comment]
@MorrisJobke  could be have it as "partially enabled" or so on?

**Comment by RealRancor** [comment]
Sorry, duplicate of https://github.com/owncloud/core/issues/17737

**Comment by cdamken** [comment]
@RealRancor You are closing all the repeated :smile: :+1:
