### ISSUE TITLE
E-Mail an Account Overview

### ISSUE THREAD

**Issue by aspdye** [owncloud/core#18697]
Some users want "update notices" via Mail. ( #18696)

I think we should expand that by sending weekly / monthly statistic mails, like "Google Apps for Work" does.
We could include:

-Setup Warnings / Erros
-Statistics (how many logins, etc.)
-Storage Statistics 
-App Usage Informations (if supported by app dev)
-Update informations (as example "OwnCloud 8.2 available" or "oC Mail 0.3 available") with direct "Login & Update" Buttons.
-Tips & Tricks for using OwnCloud better

A kind of "individual Newsletter" for your OwnCloud.

How Google does it:
[German/Deutsch]

![ga](https://cloud.githubusercontent.com/assets/12893462/9576329/0189f2b0-4fd7-11e5-97d2-f86f5e068a25.PNG)
![ga1](https://cloud.githubusercontent.com/assets/12893462/9576331/05a3312c-4fd7-11e5-8243-496fb501fab3.PNG)
![ga3](https://cloud.githubusercontent.com/assets/12893462/9576332/070dface-4fd7-11e5-8dd6-9acbe916d102.PNG)

**Comment by PVince81** [comment]
CC @schiesbn
