### ISSUE TITLE
Default mount options specified by storage backends

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#18708]
@Xenopathic as discussed yesterday to make it possible for some storage backends to disable encryption/sharing by default.

Also could help to fix https://github.com/owncloud/core/issues/18347

**Comment by PVince81** [comment]
@Xenopathic any update ? This is quite important, especially for fixing this regression https://github.com/owncloud/core/issues/18347

**Comment by Xenopathic** [comment]
How to approach this without introducing a MountOptionService?

**Comment by PVince81** [comment]
Hmm, then we'll need a quick workaround for https://github.com/owncloud/core/issues/18347 then

**Comment by Xenopathic** [comment]
Given that at the moment, storages can change mount options the 'hacky way' (e.g. with manipulateStorageConfig()), I'd suggest moving this to 8.2 and doing a quick workaround for #18347

**Comment by PVince81** [comment]
Moved to 9.1

**Comment by PVince81** [comment]
Backlog for now. PRs welcome
