### ISSUE TITLE
[stable8.1] Files inside a shared folder as owner only appears as shared if the recipient modifies it.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#18700]
### Steps to reproduce

Having two users:

1. Share a folder from user1 with user2 including textfiles making user2 having edit permissions.
2. Edit with user2 one of those textfiles. 
3. Open the shared folder with the owner user (user1).

### Expected behaviour
None files appears as shared.

### Actual behaviour
Only modified files by recipient appears as shared.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
8.1.2RC1

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition..

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Chrome 41

**Comment by PVince81** [comment]
Do they appear as shared after you refresh the page ?
Could be a similar issue like https://github.com/owncloud/core/issues/6813

**Comment by SergioBertolinSG** [comment]
Tested with last stable8.1, not seeing the problem anymore.
