### ISSUE TITLE
Backup Host for LDAP server does not automatically connect

### ISSUE THREAD

**Issue by gig13** [owncloud/core#18701]
### Steps to reproduce
1. Setup an LDAP connection with a Backup server
2. Block the network access to the main LDAP server -- To simulate failure, I've added an entry to the owncloud host file pointing the ldap server to localhost, when this is in place users are unable to login to the web interface with the error "An internal error occurred.
3.

### Expected behaviour
Once the Main LDAP server is unreachable, the Backup server should be used for connections

### Actual behaviour
Errors are displayed when a user attempts to login. Logins will happen if the check box disable main server is enabled, so we are certain the backup host configuration is correct.
```
{"app":"handleLogin","message":"OC\\ServerNotAvailableException: Lost connection to LDAP server.","level":4,"time":"2015-08-28T09:23:44-06:00"}
{"app":"handleLogin","message":"OC\\ServerNotAvailableException: Lost connection to LDAP server.","level":4,"time":"2015-08-28T09:25:31-06:00"} 
```

### Server configuration
**Operating system**: RHEL 6

**Web server:** Apache

**Database:** Oracle

**PHP version:** 5.4.40

**ownCloud version:** 7.0.8

**Updated from an older ownCloud or fresh install:** Updated

**List of activated apps:** See config report https://s3.owncloud.com/owncloud/index.php/apps/files?dir=%2FShared%2Fowncloud%2Fsupport%2Fgithub-issues%2Fcore%2F18701

**The content of config/config.php:**

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration
See config report

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
{"app":"handleLogin","message":"OC\\ServerNotAvailableException: Lost connection to LDAP server.","level":4,"time":"2015-08-28T09:23:44-06:00"}
{"app":"handleLogin","message":"OC\\ServerNotAvailableException: Lost connection to LDAP server.","level":4,"time":"2015-08-28T09:25:31-06:00"} 
```

**Comment by gig13** [comment]
@MorrisJobke @blizzz

**Comment by gig13** [comment]
The ldap servers are setup with master and 2 slaves.  I've configured one slave as the primary and the other slave as the backup.  I thought object UUUIDs would be the same between the two slaves.

**Comment by blizzz** [comment]
Probably introduced with https://github.com/owncloud/core/pull/15489

**Comment by gig13** [comment]
@bboule 
Can you check the release?

**Comment by bboule** [comment]
Looks like the fix for this was merged in 15489 which should be in 8.1.3 so I think we are good here.

**Comment by MorrisJobke** [comment]
> Looks like the fix for this was merged in #15489 which should be in 8.1.3 so I think we are good here. and the back port is #15797 and is in 8.0.4 does that work for you @gig13 ?

Correct -> close

**Comment by gig13** [comment]
@bboule @MorrisJobke 
I was looking for a backport to 7.x since that is what version the case is opened with.

**Comment by MorrisJobke** [comment]
cc @blizzz

**Comment by blizzz** [comment]
No, the regression was introduced, not fixed in #15489

**Comment by MorrisJobke** [comment]
> No, the regression was introduced, not fixed in #15489

@butonic @blizzz Any idea how to detect that the backup host needs to be used then?

**Comment by gig13** [comment]
@MorrisJobke 
Not seeing this with 7.0.10. Closed from my perspective.

**Comment by blizzz** [comment]
There was another report seeing it on 8.1.1, thus I'd prefer to keep it open and investigate. 
https://github.com/owncloud/core/issues/19336

**Comment by DeepDiver1975** [comment]
@cmonteroluque I suggest to add this to the milestone 8.2.1 since master is affected as well and we should first fix master before we discuss backport of fixes.

**Comment by cmonteroluque** [comment]
@DeepDiver1975 agreed

**Comment by johnripper1** [comment]
I can confirm this issue with ownCloud 8.1.3 (stable), so this problem persists.

What works perfect is if you check the "Disable Main Server" box and enter a "Backup (Replica) Host" under User Authentication with LDAP -> Configuration -> Advanced Settings.

Anyway the error is the following:
ldap_start_tls(): Unable to start TLS: Can't contact LDAP server at /share/MD0_DATA/Web/owncloud/apps/user_ldap/lib/ldap.php#257

**Comment by MorrisJobke** [comment]
Another report by @pierrejochem in #19855

> We have 5 domain controllers integrated in our cloud server, but if one of them is not available then the user search (sharing area) is not working and others stuff like the activity app. Is there a way to improve this because it is a thing what can happen sometimes.

**Comment by pierrejochem** [comment]
@johnripper1 Confirm too

**Comment by johnripper1** [comment]
Did some more testing, losing LDAP connection results in the following:

**LDAP users:**
- Users cannot login (error see above):

-> This is independent from the cache time
-> Cache is currently set to 3600 for testing purpose
-> Users cannot login evenif they logged and out only a few moments (<1min) ago

- If user is logged in any page request returns error "Internal Server Error":

> Internal Server Error
> The server encountered an internal error and was unable to complete your request.
> Please contact the server administrator if this error reappears multiple times, please include the > 
> technical details below in your report.
> More details can be found in the server log.
> Technical details
> Remote Address: xx.xx.xx.xx
> Request ID: xxxxxxxxxxxx

- All connections to the OC instance are lost (e.g. Windows Desktop Client)
- Usersearch cannot even be accessed anymore

**Local (database) users (including admin):**
- Usersearch aborts with error "An error occured. Please try again"
- Admin only: No access to the user administration ("index.php/settings/users")  -> "Internal server error" (see above)

If required I can do some more testing with apps, as well as fill out the template, but currently I consider this is as unnecessary.

**Comment by johnripper1** [comment]
Oh: And I tested the function of the backup host:

Steps:
1. Enable tickbox "Disable Main Server"
2. Shutdown primary LDAP server or interrupt connection
(or do vice versa)

Result = expected result
No issues occur from what I have seen
(all connections are recovered)

**Comment by johnripper1** [comment]
The following log is the result of a user trying to login while the LDAP server is not avaible:

{"reqId":"xxxxxxxxxxxxxxxxxxxxx","remoteAddr":"XX.XX.XX.XX","app":"PHP","message":"ldap_start_tls(): Unable to start TLS: Can't contact LDAP server at \/share\/MD0_DATA\/Web\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-19T22:23:05+00:00"}
{"reqId":"xxxxxxxxxxxxxxxxxxxxx","remoteAddr":"XX.XX.XX.XX","app":"handleLogin","message":"Exception: {\"Exception\":\"OC\\\\ServerNotAvailableException\",\"Message\":\"Lost connection to LDAP server.\",\"Code\":0,\"Trace\":\"#0 \\\/share\\\/MD0_DATA\\\/Web\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/ldap.php(259): OCA\\\\user_ldap\\\\lib\\\\LDAP->postFunctionCall()\\n#1 \\\/share\\\/MD0_DATA\\\/Web\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/ldap.php(211): OCA\\\\user_ldap\\\\lib\\\\LDAP->invokeLDAPMethod('start_tls', Resource id #26)\\n#2 \\\/share\\\/MD0_DATA\\\/Web\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/connection.php(583): OCA\\\\user_ldap\\\\lib\\\\LDAP->startTls(Resource id #26)\\n#3 \\\/share\\\/MD0_DATA\\\/Web\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/connection.php(540): OCA\\\\user_ldap\\\\lib\\\\Connection->doConnect('domaincontroller1...', '389')\\n#4 \\\/share\\\/MD0_DATA\\\/Web\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/connection.php(160): OCA\\\\user_ldap\\\\lib\\\\Connection->establishConnection()\\n#5 \\\/share\\\/MD0_DATA\\\/Web\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/connection.php(168): OCA\\\\user_ldap\\\\lib\\\\Connection->init()\\n#6 \\\/share\\\/MD0_DATA\\\/Web\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/access.php(767): OCA\\\\user_ldap\\\\lib\\\\Connection->getConnectionResource()\\n#7 \\\/share\\\/MD0_DATA\\\/Web\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/access.php(915): OCA\\\\user_ldap\\\\lib\\\\Access->executeSearch('(&(&(|(objectcl...', Array, Array, NULL, NULL)\\n#8 \\\/share\\\/MD0_DATA\\\/Web\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/access.php(703): OCA\\\\user_ldap\\\\lib\\\\Access->search('(&(&(|(objectcl...', Array, Array, NULL, NULL)\\n#9 \\\/share\\\/MD0_DATA\\\/Web\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/access.php(660): OCA\\\\user_ldap\\\\lib\\\\Access->searchUsers('(&(&(|(objectcl...', Array, NULL, NULL)\\n#10 \\\/share\\\/MD0_DATA\\\/Web\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/access.php(648): OCA\\\\user_ldap\\\\lib\\\\Access->fetchListOfUsers('(&(&(|(objectcl...', Array)\\n#11 \\\/share\\\/MD0_DATA\\\/Web\\\/owncloud\\\/apps\\\/user_ldap\\\/user_ldap.php(85): OCA\\\\user_ldap\\\\lib\\\\Access->fetchUsersByLoginName('atest', Array)\\n#12 \\\/share\\\/MD0_DATA\\\/Web\\\/owncloud\\\/lib\\\/private\\\/user\\\/manager.php(178): OCA\\\\user_ldap\\\\USER_LDAP->checkPassword('atest', 'Test1234')\\n#13 \\\/share\\\/MD0_DATA\\\/Web\\\/owncloud\\\/lib\\\/private\\\/user\\\/session.php(217): OC\\\\User\\\\Manager->checkPassword('atest', 'Test1234')\\n#14 \\\/share\\\/MD0_DATA\\\/Web\\\/owncloud\\\/lib\\\/private\\\/user.php(242): OC\\\\User\\\\Session->login('atest', 'Test1234')\\n#15 \\\/share\\\/MD0_DATA\\\/Web\\\/owncloud\\\/lib\\\/base.php(1074): OC_User::login('atest', 'Test1234')\\n#16 \\\/share\\\/MD0_DATA\\\/Web\\\/owncloud\\\/lib\\\/base.php(970): OC::tryFormLogin()\\n#17 \\\/share\\\/MD0_DATA\\\/Web\\\/owncloud\\\/lib\\\/base.php(932): OC::handleLogin()\\n#18 \\\/share\\\/MD0_DATA\\\/Web\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n#19 {main}\",\"File\":\"\\\/share\\\/MD0_DATA\\\/Web\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/ldap.php\",\"Line\":289}","level":4,"time":"2015-10-19T22:23:05+00:00"}

I think the routine https://github.com/owncloud/core/blob/master/apps/user_ldap/lib/connection.php#L542-L551 is never called unless there is not even a try to reach the backup/replica host.

**Comment by johnripper1** [comment]
Confirmed with OC 8.2 btw

**Comment by gig13** [comment]
@bboule @MorrisJobke 
I would like to request a back port since there are several users on OC7 and OC8.0 that will need this functionality.

**Comment by cmonteroluque** [comment]
I don't think we're doing anything but security fixes any longer for 7. Still an issue for later releases

**Comment by johnripper1** [comment]
So this has no prio?

**Comment by karlitschek** [comment]
@johnripper1 Not for ownCloud 7. Please update to a newer version

**Comment by johnripper1** [comment]
See above I run OC 8.2, so I am waiting for fix the most recent version : )

**Comment by karlitschek** [comment]
@johnripper1 Yes :-)

**Comment by blizzz** [comment]
Fixed in https://github.com/owncloud/core/issues/20271, need another reviewer

**Comment by PVince81** [comment]
Code makes sense :+1:

**Comment by MorrisJobke** [comment]
@gig13 This will be in 8.0.10, 8.1.5, 8.2.1 and 9.0.0 ;)

**Comment by gig13** [comment]
Cool!
