### ISSUE TITLE
upgrade to 8.1.1 failed

### ISSUE THREAD

**Issue by vasyugan** [owncloud/core#18712]
Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'DELETE FROM `oc_queuedtasks` WHERE `app`=?' with params ["search_lucene"]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xx_owncloud.oc_queuedtasks' doesn't exist

**Comment by vasyugan** [comment]
worked after second run.

**Comment by rperezb** [comment]
@jvillafanez can you check?
thx

**Comment by vasyugan** [comment]
after upgrade, found all apps disable, after trying to re-enable same shit again.

**Comment by RealRancor** [comment]
Dup of https://github.com/owncloud/search_lucene/issues/90

**Comment by jvillafanez** [comment]
@vasyugan please provide the list of installed apps (I guess search_lucene is important) and also the version you're upgrading from.
In addition, if you're upgrading using package or tarballs, please provide that info too.

**Comment by RealRancor** [comment]
@jvillafanez The issue is already known and fixed in search_lucene as written above. :)

**Comment by jvillafanez** [comment]
:+1:
