### ISSUE TITLE
[Stable 8] Uploading a second personal picture fails to draw correct picture.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#18711]
### Steps to reproduce

1. Go to the personal page.
2. Upload a personal image and choose the splitted part.
3. Upload another personal image and choose the splitted part.

### Expected behaviour
You get as personal image the splitted part your choose of the second uploaded image.

### Actual behaviour
You get a portion of the first image you uploaded, not the second.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
8.0.7RC1

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition..

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Chrome 41

**Comment by MorrisJobke** [comment]
I can't reproduce this on master anymore -> closed

**Comment by SergioBertolinSG** [comment]
Tested on daily community, works fine.
