### ISSUE TITLE
AppFramework does not allow caching

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#18719]
The avatar controller sets the etag to the crc32 of the avatar.
However if I then use that etag with curl like:

```curl -D - https://server/index.php/avatar/rullzer/32 --header 'If-None-Match: "4146254073"'```

I do not get an 304.

I think this is caused by https://github.com/owncloud/core/blob/master/lib/private/appframework/http.php#L124. Since it compares the set ETag with the provided ETag. But the provided ETag has quotes.

**Comment by Raydiation** [comment]
Can't do this one, fix should be straight forward though. Can you take care of this?

**Comment by rullzer** [comment]
Yep will do :)
