### ISSUE TITLE
Storage Abstraction Layer

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#18723]
Placeholder for discussion of storage abstraction layer for plugging storage.

**Comment by labkode** [comment]
@MTRichards some discussions and work already started at  #18667, #18668 , #12274

**Comment by MTRichards** [comment]
@labkode Great! Thanks for linking the issues.

**Comment by MTRichards** [comment]
Also linking to https://github.com/owncloud/core/issues/18771 For what needs to be abstracted.

**Comment by PVince81** [comment]
We already have this, it's not that good. Closing as duplicate, we have enough tickets to discuss this.
