### ISSUE TITLE
OC v8.1.1: http redirect to https

### ISSUE THREAD

**Issue by tx7** [owncloud/core#18725]
Hi all,

I'm running OC v8.1.1 on an OpenMediaVault server, and I'm try to set up an OwnCloud auto redirect HTTP to HTTPS.
Some users said find and edit the 'httpd' file, while others say edit the '.htaccess' of OwnCloud.
I need somebody point me to the right direction, please.
I would like my domain to redirect from : http://www.neo.me.com:9443 to https://www.neo.me.com:9443

Thanks.

This is the error when I entered my hostname or local IP without 'https':

400 Bad Request
The plain HTTP request was sent to HTTPS port
nginx/1.2.1

I modified .htaccess and used this code, but it error still persist:

RewriteCond %{HTTPS} off
//First, rewrite any request to the wrong domain to use www.
RewriteCond %{HTTP_HOST} !^www\.
RewriteRule ^(.*)$ https://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
//Then rewrite to HTTPS:
// Don't put www. here. If it is already there it will be included, if not
//the subsequent rule will catch it.
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

**Comment by RealRancor** [comment]
Hi,

please note this is an issue tracker where bugs and feature request for ownCloud are tracked. For support questions either use the users mailinglist:

https://mailman.owncloud.org/mailman/listinfo/user

or the forums: https://forum.owncloud.org/

**Comment by tx7** [comment]
Ok, but do you know the link to the solution?

**Comment by RealRancor** [comment]
Please close and ask that question at the listed support channels above.
