### ISSUE TITLE
Faulty „Strict-Transport-Security“-check

### ISSUE THREAD

**Issue by norgoe** [owncloud/core#18727]
By accident I configured the extra Header for Strict-Transport-Security two times in my ssl.conf.
Both issued a value for max-age of 15768000 or more seconds.
The error message of owncloud is misleading as it tells me that max-age is set to less than 15768000 seconds - which is wrong.
Instead it's a duplicated setting and thus two header lines for STS.

Here is an example query to the server (sorry, I have no idea how to tell github to display the code and not render the html in it):

```
$curl -si myserver.de
HTTP/1.1 400 Bad Request
Date: Tue, 01 Sep 2015 06:52:15 GMT
Server: Apache/2.4.10 (Debian)
Strict-Transport-Security: max-age=15768000
Strict-Transport-Security: max-age=15768001
Content-Length: 442
Connection: close
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
Reason: You're speaking plain HTTP to an SSL-enabled server port.<br />
 Instead use the HTTPS scheme to access this URL, please.<br />
</p>
<hr>
<address>Apache/2.4.10 (Debian) Server at myserver.de Port 443</address>
</body></html>
```

**Comment by LukasReschke** [comment]
Two headers = You shall not do this = Expected behaviour, correct your setting ;-)

**Comment by norgoe** [comment]
Sorry, but "wrong size" and "duplicate headers" are different things and thus should lead to different error messages.
The current behaviour pushes the user in the wron direction. He searches for the max_age and checks if it is large enough while the error is a duplicate header line.
Thus an error message like "uplicate STS header, please fix this" would be suitable for this and not "wrong max_age size".

**Comment by LukasReschke** [comment]
Fair enough.

**Comment by RealRancor** [comment]
@LukasReschke The duplicate header issue is already tracked/reported here: https://github.com/owncloud/core/issues/17613
