### ISSUE TITLE
Installation to 8.1.1 doesn´t work

### ISSUE THREAD

**Issue by HansPeterHerkenrath** [owncloud/core#18728]
Hello,
the instalation to V 8.1.1 doesn´t work on my NAS Synology 214+.

Here the installation-request:
![owncloud](https://cloud.githubusercontent.com/assets/14068939/9598321/95700182-508a-11e5-94bb-e7fb3bbfea12.png)

what can be the reason?
best regards
Hans-Peter

**Comment by RealRancor** [comment]
Dup of https://github.com/owncloud/core/issues/18224, https://github.com/owncloud/core/issues/18333, https://github.com/owncloud/core/issues/18334, https://github.com/owncloud/core/issues/18350 and some more.

Btw. you're currently doing an update not an installation.

**Comment by Xenopathic** [comment]
Indeed, let's keep it at #18224
