### ISSUE TITLE
No error message is shown trying to modify the password of an LDAP user

### ISSUE THREAD

**Issue by davitol** [owncloud/core#18732]
### Steps to reproduce

1. As admin configure a LDAP using the wizard
2. Go to the users view
3. Try to change the password to a LDAP user

### Expected behaviour

An error message should be shown

### Actual behaviour

There's no message and it 'seems' that the password has been changed.

Note: 8.0.7. oc server version works fine. The image with the error message comes from this version.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:"8.1.2.0","versionstring":"8.1.2RC1"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
nabled:
 - activity: 2.0.2
 - admin_audit: 0.6
 - enterprise_key: 0.1.0
 - files: 1.1.10
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.6
 - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

![captura de pantalla 2015-09-01 a las 11 08 06](https://cloud.githubusercontent.com/assets/10596560/9600424/4dc11068-509b-11e5-87dd-423f7665ca69.png)

**Comment by karlitschek** [comment]
@blizzz

**Comment by blizzz** [comment]
@MorrisJobke @LukasReschke

**Comment by blizzz** [comment]
This is fixed in current stable8.1 to master
