### ISSUE TITLE
Get rid of jquery UI

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#18739]
### Libs

- jquery-fileupload (used in core)
- $.autocomplete() comes from jquery UI => move to select2
- http://jqueryui.com/sortable/
- http://jqueryui.com/draggable/
- http://jqueryui.com/droppable/
- http://jqueryui.com/progressbar/
- date picker
- ...

### Apps
- [ ] LDAP wizard
- [ ] calendar
    - jqueryui-timepicker
- [ ] contacts
    - jqueryui-timepicker
- [ ] gallery
    - jquery.ui.touch-punch

**Comment by jancborchardt** [comment]
cc @georgehrke @raghunayyar @libasys for Calendar – if jQuery UI is still used there, get rid of it.

@blizzz use the tabs as in the sidebar. No accordion of possible. If needed, do it similarly as in the Proxy app or in the installation with simple JS expanding cc @LukasReschke

**Comment by georgehrke** [comment]
What's about the date picker when setting an expiration date for a share?

**Comment by jancborchardt** [comment]
Can we isolate that or get it from a library instead? If that’s the only part we use of jQuery UI then it doesn’t warrant pulling in the whole thing.

**Comment by raghunayyar** [comment]
@jancborchardt for calendar we intend to move to popover in rework as soon as we get rid of jquery UI in core.

**Comment by libasys** [comment]
what's about sortable, drag & drop and so on, all primary usefull functions?

**Comment by jancborchardt** [comment]
@libasys can you analyze where those functions are used? And those are from jQuery UI, not simply jQuery?

**Comment by jancborchardt** [comment]
@raghunayyar then basically already move to popover now because we will definitely get rid of jQuery UI for 9.0.

**Comment by libasys** [comment]
http://jqueryui.com/sortable/
http://jqueryui.com/draggable/
http://jqueryui.com/droppable/
http://jqueryui.com/progressbar/

and so on!

**Comment by jancborchardt** [comment]
@libasys where are they used?

**Comment by libasys** [comment]
i think many community apps use this functions! progressbar as example for the import dialog! 
drag, drop & sortables in contacts app and so on!
you can't say get rid of jquery ui, this lib is since a few year in the core integrated! what should community apps devs do in future? i think the first point is get rid of jquery ui dialog but not get rid of jquery ui! the second step get rid of tables for more fluid & responsive design!

**Comment by jancborchardt** [comment]
@libasys yeah, what I was saying is that we should try to isolate which parts of jQuery UI we actually use. And then only ship those.

**Comment by oparoz** [comment]
> libasys where are they used?

You can't drag and drop in the files app without it

>  i think the first point is get rid of jquery ui dialog but not get rid of jquery ui! 

It doesn't really matter as it's a library which can be included in the apps themeselves. It's more of a problem when core JS stuff is thrown away.

**Comment by georgehrke** [comment]
What's the state on this? Will jQuery UI be removed with 9.1?

**Comment by PVince81** [comment]
No, there are still too many components using it unfortunately... Need to sort these out first.

@felixheidecke

**Comment by PVince81** [comment]
@felixheidecke please investigate whether we can/should update to the latest jquery.ui version and how much time it would need to migrate (find out with migration guide and function usage)

**Comment by PVince81** [comment]
@felixheidecke can you prepare and run your script for the two jquery.ui migrations ? we need to evaluate how much work this is compared to getting rid of jquery.ui altogether

**Comment by PVince81** [comment]
@felixheidecke bad things will already happen when updatingjust from jquery-ui 1.10.0 to 1.10.4, see https://github.com/owncloud/core/pull/30088#issuecomment-410327858

The worse part is that OC has a file jquery-ui-fixes.css that overrides styles which will likely change in future versions. So when updating we'd need to adjust these hacks.

**Comment by PVince81** [comment]
@felixheidecke let's compare how much time we'd need to update jquery.ui including the existing OC hacks (jquery-ui-fixes.css) with the time it would take to replace all components with non-jquery-ui ones...

**Comment by PVince81** [comment]
Updated plan: we carry on with updating jquery.ui and will fix jquery.ui.fixes.

Considering that Phoenix is the future, it's not worth investing time trying to replace the jquery.ui plugins with alternatives.

**Comment by PVince81** [comment]
- [ ] jquery.fileupload from files app also requires jquery.ui: https://github.com/blueimp/jQuery-File-Upload

**Comment by PVince81** [comment]
Ticket for the jquery ui upgrade: https://github.com/owncloud/core/issues/32484

**Comment by felixheidecke** [comment]
@PVince81 can we close this as there is a [new upgrade Issue](https://github.com/owncloud/core/issues/32484) instead of getting rid?
