### ISSUE TITLE
share link problem

### ISSUE THREAD

**Issue by aberndt2406** [owncloud/core#18737]
Steps to reproduce
1. click on share (to share a file)
2. click on share link (to create a link)

Expected behaviour
 link generation

Actual behaviour
no link generation
popup window appears on the screen with following error message:
 -> error while sharing
     error
-> no error message in Apache error.log or owncloud.log
If we enable "Set default expiration date" and / or
"Enforce password protection" -> it works.

Server configuration
Operating system:openSUSE 13.2
Web server: apache 2.4.10
Database: mysql
PHP version: 5.6.1
**ownCloud version:"8.1.1"

Updated from an older ownCloud or fresh install:
Fresh install

**Comment by karlitschek** [comment]
@schiesbn how should this work?

**Comment by aberndt2406** [comment]
1. click on share (to share a file)
2. click on share link (to create a link)
3. link generation

**Comment by schiesbn** [comment]
I can't reproduce it with a fresh installation. Did you changed any of the share settings or did you tried it with the default settings?

**Comment by aberndt2406** [comment]
I use it with the default settings, but I tried to generate a "share link" with a
file in a with me shared folder (local storage).

**Comment by schiesbn** [comment]
@aberndt2406 thanks for the additional information. This works for me too. To isolate the problem a bit:

1. Does it only happen for the file in the shared folder or also for files the user owns?
2. If it only happens in this folder: With what permissions was the folder shared to you,.

**Comment by aberndt2406** [comment]
1. It happens also with owned files
2. all permission are selected.
3. I have to enable "enforce password protection"
4. If I want to unshare it, I get a popup window with
    following error message: error while unsharing
5. I have to set a expiration date to delete the "share link".

**Comment by schiesbn** [comment]
@rullzer any idea? You can't reproduce it too, right?

**Comment by aberndt2406** [comment]
I can reproduce it, if I disable the option "enforce password protection".
In that case I get a popup window witjh the error message "error while sharing".
If I enable the option, I can can generate the link, but if I want to delete the link
I get a popup window with the error message: "error while unsharing"

**Comment by rullzer** [comment]
Yes it also works here.

I have a clean 8.1.1 installation.

Steps I did:

1. Share folder `foo` with user test
2. Login as user test
3. Share folder `foo` with link
4. Everything works.

So all default settings.

Can you enable debug logs and see if it shows anything?

**Comment by aberndt2406** [comment]
debug mode of owncloud.log:
Error 	PHP 	Array to string conversion at /srv/www/htdocs/owncloud/lib/private/template/functions.php#36

**Comment by aberndt2406** [comment]
can I check something more?

**Comment by aberndt2406** [comment]
If I try to delete the link, I get following error mesagge in the systemlog:

Sep 01 15:26:46 ftp1 suhosin[22210]: ALERT - ASCII-NUL chars not allowed within request variables - dropped variable 'shareWith' (attacker '192.168.10.20', file '/srv/www/htdocs/owncloud/index.php')

Sep 01 15:26:46 ftp1 suhosin[22210]: ALERT - dropped 1 request variables - (0 in GET, 1 in POST, 0 in COOKIE) (attacker '192.168.10.20', file '/srv/www/htdocs/owncloud/index.php')

**Comment by rullzer** [comment]
Can you try wit curl?

```curl -u USER:PASS 'SERVERl/ocs/v1.php/apps/files_sharing/api/v1/shares' -X POST -d 'path=FILE&shareType=3'```

Replace, ```USER, PASS, SERVER, FILE```

See if that works. It might be something in our javascript that your suhosin does not like.

**Comment by aberndt2406** [comment]
Hello,

I get following error message as response:
moved permanently.
Should I define the absolute path of the file for the variable "path"?

regards
Achim

**Comment by PVince81** [comment]
Weird, I wonder if suhoshin is preventing to pass an empty password variable, or something.
@LukasReschke do you know anything about suhoshin ?

**Comment by MorrisJobke** [comment]
Duplicate of https://github.com/owncloud/core/issues/13908 and https://github.com/owncloud/core/issues/13720

Any news here?

**Comment by PVince81** [comment]
Is this still happening in 8.1.5 or 8.2.2 ? @aberndt2406

**Comment by rullzer** [comment]
I still have no way to reproduce this.

@aberndt2406 can you check if this is till happening on 9.0.0? We moved to the OCS Share API also for the webinterface there.

**Comment by MorrisJobke** [comment]
No feedback for a long time. I will close this now.

@aberndt2406 This can easily be reopened once we have more information about this :)
