### ISSUE TITLE
Public share link requests for credentials. 

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#18731]
### Steps to reproduce

**EDIT II** 1. Share publicly a plain text file by link
**EDIT I**  2. Add a password to the public link. 
3. Open the link from a different browser without being logged in.

### Expected behaviour
Anonymous user can open the link.

### Actual behaviour
Link redirects to the login page.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
master branch (8.2alpha)

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in community edition..

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Chrome 41

**Comment by PVince81** [comment]
@SergioBertolinSG is this a regression on master ?

**Comment by PVince81** [comment]
Works for me on master (85b62c7d82695dd4cd1c73e7c1d81269ec17170b).
Link was created in Chromium 44 and opened in Firefox 39.0.3

**Comment by SergioBertolinSG** [comment]
Yes a regression.

**Comment by PVince81** [comment]
Clear the cache maybe ?

This is not enough information to be able to reproduce or fix it.

**Comment by SergioBertolinSG** [comment]
Same problem with cache cleared. I forgot to mention that the public share has to have a password (edited in the steps).

**Comment by SergioBertolinSG** [comment]
I've fixed the problem installing the last version of Firefox.

**Comment by SergioBertolinSG** [comment]
It is still happening. It happens only with plain text files. When opening the share and entering the password a dialog for credentials appears. (And it shouldn't).
Observed on chrome and safari for ipad.

**Comment by oparoz** [comment]
Confirmed.... And it's probably because of that ¦@#°% Gallery app ;)

**Comment by oparoz** [comment]
Apparently, it's not phewww... But I still need to see if I can prevent making Ajax calls before the password is entered.

What I'm seeing in the POST request is a 307 and 2 oc_sessionPassphrase with different passwords in them.
@LukasReschke must be able to fix this :)

**Comment by oparoz** [comment]
Could be related to https://github.com/owncloud/core/issues/18891 (double passphrase)

**Comment by SergioBertolinSG** [comment]
Still happening on today's master. Tested on firefox and safari.

**Comment by PVince81** [comment]
Is Safari maybe somehow auto-filling the password field ? Can you try clearing the autofill cache ?

**Comment by davitol** [comment]
I've cleaned all the browsing data, and using chrome it happens the same behaviour as @SergioBertolinSG has said.

**Comment by PVince81** [comment]
@LukasReschke are you able to reproduce this on your mac?

**Comment by nickvergessen** [comment]
Can reproduce, the issue is the preview.
For plain text files we don't show an image, but make a webdav request and write the first characters into the preview box instead of an image, which requires authentification:
![bildschirmfoto vom 2015-09-25 10 25 40](https://cloud.githubusercontent.com/assets/213943/10096238/21f04d72-6370-11e5-880b-885c2982b146.png)

**Comment by PVince81** [comment]
@oparoz is the text preview sending the password to the Webdav endpoint ?

**Comment by oparoz** [comment]
@PVince81 Yes https://github.com/owncloud/core/blob/master/apps/files_sharing/js/public.js#L120

**Comment by PVince81** [comment]
Hmm, but the password isn't appended behind the ":".

Let me check how I did it with the "move to webdav" branch.

**Comment by PVince81** [comment]
Hmm, it seems I'm not passing the password either. If the browser has a session cookie related to this public share, it should be able to reuse it when doing webdav requests.

**Comment by oparoz** [comment]
The token is used as the username. There is no password

**Comment by PVince81** [comment]
### Steps to reproduce (for clarity)

1. Create a text file
1. Share text file with link
1. Set password to "test"
1. Open the link
1. Enter the password "test"

At this point the popup appears for the Webdav call.

**Comment by PVince81** [comment]
I suspect it might be related to the recent refactoring in publicwebdav to use "ServerFactory". I'll try and debug the server.

**Comment by PVince81** [comment]
Hmmm no, it looks like this never worked before.
Stable8.1 is broken too and so is v8.1.1.

**Comment by PVince81** [comment]
Hmmmmmmm it works on my Webdav branch https://github.com/owncloud/core/pull/16902 which uses public webdav for the file list and also text preview.

I'll try and find out why it works there...

**Comment by PVince81** [comment]
Aha, this one: https://github.com/owncloud/core/commit/e6f007dd75531cb22a97dee09673dac08c89a1ab

I'll make a separate PR for that

**Comment by oparoz** [comment]
:dancers:

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/19402

**Comment by oparoz** [comment]
![awesome](https://s3-eu5.ixquick.com/cgi-bin/serveimage?url=http:%2F%2Fi3.kym-cdn.com%2Fphotos%2Fimages%2Foriginal%2F000%2F122%2F820%2FLOLB.jpg&sp=56972c244b167c7023bc8c6c5d5f2ab8)

**Comment by SergioBertolinSG** [comment]
This happens in 8.1 as well. backport?
