### ISSUE TITLE
Getting File Sync Error after an update

### ISSUE THREAD

**Issue by yeonbinkim** [owncloud/core#18749]
Hello,

I am running into an issue syncing files after running a server update to 8.1.1.3.
I am on CentOS 6 and running apache.

The error message on the admin panel says "Error PHP	Class 'OC_Connector_Sabre_Auth' not found at /state/partition1/www/owncloud/apps/files/appinfo/remote.php#27"

It seems like OC_Connector_Sabre_Auth is being called when it is expecting OC/Connector/Sabre/Auth. 

Thanks,
Eddy

**Comment by RealRancor** [comment]
Can you compare your remote.php with the one here:

https://github.com/owncloud/core/blob/v8.1.1/apps/files/appinfo/remote.php#L27

Seems there is no callnto a class in line 27 at all. Seems to me that you currently have running the files app of oC 8.0.x:

https://github.com/owncloud/core/blob/v8.0.6/apps/files/appinfo/remote.php#L27

**Comment by yeonbinkim** [comment]
The file is different from the one that was linked.

Line 27 shows "$authBackend = new OC_Connector_Sabre_Auth();"

It seems like the system was updated to 8.1 but the app is still at 8.0?

Is there a way to only upgrade the app to match the version?

**Comment by RealRancor** [comment]
You can download the archives from here:

https://owncloud.org/changelog/

which are including the newer versions.

**Comment by PVince81** [comment]
You might want to try again updating to 8.1.3. I assume you were using the package manager of CentOS ? Were all the owncloud packages properly updated to the same version ?

**Comment by MorrisJobke** [comment]
@yeonbinkim Please reopen, if you still have the problems with 8.1.3
