### ISSUE TITLE
Information icon of the sharing dialog moves when passing over it.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#18745]
### Steps:

1. Open a sharing dialog.
2. Pass the cursor over the info icon.

### Expected behaviour:
Fixed icon.

### Current behaviour:

![information_icon_moving](https://cloud.githubusercontent.com/assets/9048796/9607864/b7a2bf6a-50cb-11e5-87ce-e15367d950bb.gif)

**Browser:**
Chrome

**Server Version**
Master (8.2alpha)

**Comment by karlitschek** [comment]
@jancborchardt

**Comment by jancborchardt** [comment]
Can not reproduce. @SergioBertolinSG does it occur with any other browsers?

**Comment by jancborchardt** [comment]
Also, I would close this since it becomes obsolete anyway with moving the share dialog to the sidebar.
