### ISSUE TITLE
Wrong link clicking on developer documentation

### ISSUE THREAD

**Issue by davitol** [owncloud/core#18740]
### Steps to reproduce

1. Go to the apps menu
2. Click on the developer documentation button

### Expected behaviour

https://doc.owncloud.org/server/8.1/developer_manual/app/index.html should be shown (8.1)

### Actual behaviour

https://doc.owncloud.org/server/8.0/developer_manual/app/index.html is shown (8.0)

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:"8.1.2.0","versionstring":"8.1.2RC1"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
nabled:
 - activity: 2.0.2
 - admin_audit: 0.6
 - enterprise_key: 0.1.0
 - files: 1.1.10
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.6
 - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

![captura de pantalla 2015-09-01 a las 15 08 07](https://cloud.githubusercontent.com/assets/10596560/9605078/da70d35c-50bb-11e5-9c8a-f320c04fe798.png)

**Comment by davitol** [comment]
@carlaschroder ?

**Comment by LukasReschke** [comment]
Does the defaults.php in the theme look like https://github.com/owncloud/enterprise/blob/stable8.1/theme/defaults.php#L92?

**Comment by carlaschroder** [comment]
That was fixed June 29.....it should be building correct URLs, shouldn't it?

**Comment by davitol** [comment]
The rest of the documentations links seem to be ok, except the one I pointed above, that guides us to an 8.0 documentation

**Comment by LukasReschke** [comment]
That's caused by https://github.com/owncloud/core/blame/stable8.1/settings/templates/apps.php#L34, `https://owncloud.org/dev` is redirecting to 8.0

**Comment by carlaschroder** [comment]
Someone else has to fix this..I am sick.

**Comment by LukasReschke** [comment]
Sysadmin has to do this :)

cc @danimo

**Comment by carlaschroder** [comment]
Yay. Other people doing the work :+1:

**Comment by MorrisJobke** [comment]
@cmonteroluque Moved to 8.1.3

**Comment by cmonteroluque** [comment]
Really needs to be fixed

**Comment by PVince81** [comment]
Any update, has this been fixed ?

**Comment by LukasReschke** [comment]
No.
```
➜  ~  curl https://owncloud.org/dev -v
*   Trying 50.30.33.236...
* Connected to owncloud.org (50.30.33.236) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: www.owncloud.org
* Server certificate: Go Daddy Secure Certificate Authority - G2
* Server certificate: Go Daddy Root Certificate Authority - G2
> GET /dev HTTP/1.1
> Host: owncloud.org
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Date: Wed, 16 Sep 2015 16:17:37 GMT
< Server: Apache
< X-Frame-Options: SAMEORIGIN
< Strict-Transport-Security: max-age=31536000
< X-XSS-Protection: 1; mode=block
< Location: http://doc.owncloud.org/server/8.0/developer_manual/app/index.html
< Content-Length: 274
< Content-Type: text/html; charset=iso-8859-1
<
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://doc.owncloud.org/server/8.0/developer_manual/app/index.html">here</a>.</p>
</body></html>
* Connection #0 to host owncloud.org left intact
```

**Comment by LukasReschke** [comment]
@danimo @msrex @whoeverhasadminaccesstoourservers

**Comment by danimo** [comment]
Done
