### ISSUE TITLE
File upload/delete and folder delete through web UI doesn't trigger corresponding hooks

### ISSUE THREAD

**Issue by pellaeon** [owncloud/core#18759]
### Steps to reproduce
Upload/delete/create a file or delete a folder through web UI

### Expected behaviour
Corresponding [hooks](https://doc.owncloud.org/server/8.2/developer_manual/app/hooks.html#filesystem-root) like `postWrite`, `postDelete` should be invoked.

### Actual behaviour
The hooks are never invoked.

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache 2.4.7

**Database:** MySQL

**PHP version:**  5.5.9

**ownCloud version:** ownCloud 8.2 pre alpha (git) (master@f8d8de5)

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

**Comment by pellaeon** [comment]
Related: https://github.com/owncloud/documentation/issues/1256

**Comment by PVince81** [comment]
Strange, this used to work. Might explain issues with thumbnails that weren't updating.

@icewind1991 @schiesbn any idea ? Has anything changed ?

**Comment by PVince81** [comment]
Please note that when updating/deleting a folder, the hook should be triggered only on the folder itself, not its children. Is that what you meant @pellaeon ?

**Comment by PVince81** [comment]
I tested the internal "post_delete" and "post_write" with the versions app, they work fine.
But from the docs it seems it's the public ones from the Node API.

@icewind1991 does the Node API transfer the internal hooks to public ones ?
From looking at the code it seems that it didn't, and the behavior is to only fire the hooks whenever the Node API is used (which isn't the case from the web UI or Webdav)

**Comment by pellaeon** [comment]
@PVince81 actually I want to put a listener on the root folder, and from what I heard from someone at the conference, operations on a Node should trigger its parent's event.

And yes, this issue is about the public Node API.

**Comment by PVince81** [comment]
>operations on a Node should trigger its parent's event.

@icewind1991 is that so ?

Internal hooks only trigger on the file itself, not on parents.

**Comment by icewind1991** [comment]
Atm only the root folder provides a `listen` which works for any event in the filesystem, in the future I would like to add listen support to any file and folder which filter hooks accordingly

**Comment by cmonteroluque** [comment]
This issue will fall off 8.2 if not resolved by 6 Oct
