### ISSUE TITLE
PHP7: Add allowed_classes to unserialize

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#18757]
=> http://php.net/manual/en/function.unserialize.php

Either we add our own wrapper for unserialize or we do an if check for the version everywhere

**Comment by Xenopathic** [comment]
We actually use `unserialize()`? :hear_no_evil:

**Comment by LukasReschke** [comment]
Sure. Caching magic and IJobs ;-)

**Comment by PVince81** [comment]
@Peter-Prochaska thoughts ?

**Comment by Peter-Prochaska** [comment]
We have to write a wrapper class for unserialize with version check, because allowed_classes was introduced in PHP 7.0. @PVince81

**Comment by PVince81** [comment]
@settermjd FYI
