### ISSUE TITLE
cant encryption:migrate after update from 7.0.4 to 8.1.1

### ISSUE THREAD

**Issue by Hideio** [owncloud/core#18751]
### Steps to reproduce

1. Have a working installation of owncloud version 7.0.4. with files_encryption enabled.
2. upgrade to 8.1.1 whit updater app

### Expected behaviour

The upgrade should succeed.

### Actual behaviour

The upgrade succeed but files still decryptet and encryption:migrate doesnt work

root@omv:/var/www/owncloud# sudo -u www-data php occ encryption:migrate                
Reorganize system folder structure
PHP Fatal error:  Call to undefined method OC\DB\Connection::getQueryBuilder() in /var/www/owncloud/apps/encryption/lib/migration.php on line 164

root@omv:/var/www/owncloud# sudo -u www-data php occ encryption:status                 
  - enabled: true
  - defaultModule: (its empty)

### Server configuration
**Operating system**:
Linux version 3.16.0-0.bpo.4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.6.3 (Debian 4.6.3-14) ) #1 SMP Debian 3.16.7-ckt11-1+deb8u3~bpo70+1 (2015-08-08)
**Web server:**
nginx version: nginx/1.2.1
**Database:**
(Debian) 5.5.44-0+deb7u
**PHP version:**
PHP 5.4.44-0+deb7u1
**ownCloud version:** (see ownCloud admin page)
sudo -u www-data php occ status
 - installed: true
 - version: 8.1.1.3
 - versionstring: 8.1.1
 - edition

**Updated from an older ownCloud or fresh install:**

yes updated from 7.0.4 whit updater app

**List of activated apps:**
sudo -u www-data php occ app:list
Enabled:
 - activity: 2.0.1
 - admin_dependencies_chk: 0.02
 - calendarplus: 1.0.7
 - contacts: 0.4.0.0
 - delete_confirmation: 1.0.1
 - documents: 0.10.1
 - encryption: 1.0.0
 - files: 1.1.10
 - files_external: 0.2.3
 - files_mv: 0.8.1a
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - logreader: 1.0.0
 - news: 5.3.9
 - ocusagecharts: 3.4.5
 - tasksplus: 1.0.1
 - updater: 0.6

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'oc38783831644832528616193372038454673505',
  'passwordsalt' => '---,
  'version' => '8.1.1.3',
  'dbtype' => 'mysql',
  'dbname' => 'owncloud',
  'dbhost' => '127.0.0.1',
  'dbuser' => 'owncloud',
  'dbpassword' => '---',
  'dbtableprefix' => 'oc_',
  'forcessl' => true,
  'blacklisted_files' => 
  array (
    0 => '.htaccess',
  ),
  'default_language' => 'de',
  'defaultapp' => 'files',
  'knowledgebaseenabled' => false,
  'knowledgebaseurl' => 'http://api.apps.owncloud.com/v1',
  'appstoreenabled' => true,
  'allow_user_to_change_display_name' => false,
  'updatechecker' => true,
  'theme' => '',
  'log_type' => 'owncloud',
  'loglevel' => '2',
  'logdateformat' => 'F d, Y H:i:s',
  'logtimezone' => 'Europe/Berlin',
  'cron_log' => true,
  'log_rotate_size' => '5242880',
  'log_rotate_sizerotation' => '104857600',
  'cipher' => 'AES-256-CFB',
  'memcache.local' => '\\OC\\Memcache\\APC',
  'memcache.distributed' => '\\OC\\Memcache\\Memcached',
  'filesystem_check_changes' => 1,
  'asset-pipeline.enabled' => true,
  'datadirectory' => '/media/983cbc4d-f06f-465b-a931-525b26a21dd7/owncloud/',
  'trusted_domains' => 
  array (
    0 => 'omv.fritz.box',
    1 => '192.168.1.23',
    2 => 'omv.fritz.box',
    3 => 'omv',
  ),
  'secret' => '---',
  'overwrite.cli.url' => 'https://omv.fritz.box:8443',
  'installed' => true,
  'maintenance' => false,
  'appstore.experimental.enabled' => true,
);

**Are you using external storage, if yes which one:**
Ähm No? data is only at a second hdd
**Are you using encryption:** yes/no
yes
**Are you using an external user-backend, if yes which one:**
no
### Client configuration
Firefox 40.0.3

**Operating system:**
Win7
#### ownCloud log (data/owncloud.log)
```
{"reqId":"6uSMTRsDVMRgji9UFohZ","remoteAddr":"::ffff:192.168.1.21","app":"no app in context","message":"Installation is in transit between the old Encryption (ownCloud <= 8.0)\n\t\t\tand the new encryption. Please enable the \"Default encryption module\"\n\t\t\tand run 'occ encryption:migrate'","level":2,"time":"September 02, 2015 08:04:42"}
{"reqId":"+va+NXFeBIUmFdHut7yF","remoteAddr":"::ffff:192.168.1.20","app":"no app in context","message":"Installation is in transit between the old Encryption (ownCloud <= 8.0)\n\t\t\tand the new encryption. Please enable the \"Default encryption module\"\n\t\t\tand run 'occ encryption:migrate'","level":2,"time":"September 02, 2015 08:04:43"}
{"reqId":"31RqEzIlFa1oHxe7lSb0","remoteAddr":"::ffff:192.168.1.20","app":"no app in context","message":"Installation is in transit between the old Encryption (ownCloud <= 8.0)\n\t\t\tand the new encryption. Please enable the \"Default encryption module\"\n\t\t\tand run 'occ encryption:migrate'","level":2,"time":"September 02, 2015 08:04:58"}
{"reqId":"sHQgyBreQXs10S2Ijp8D","remoteAddr":"::ffff:192.168.1.21","app":"no app in context","message":"Installation is in transit between the old Encryption (ownCloud <= 8.0)\n\t\t\tand the new encryption. Please enable the \"Default encryption module\"\n\t\t\tand run 'occ encryption:migrate'","level":2,"time":"September 02, 2015 08:04:58"}
```

**Comment by karlitschek** [comment]
@schiesbn

**Comment by RealRancor** [comment]
Direct upgrades from oC 7.0.x to 8.1.x are not supported and will break the migration process:

https://github.com/owncloud/core/issues/18464#issuecomment-133466324

**Comment by schiesbn** [comment]
Yes, you need to migrate from 7.0 to 8.0 (make sure that encryption and everything else was migrated correctly) and afterwards migrate to 8.1
