### ISSUE TITLE
Expose \OC\BackgroundJob\TimedJob in public namespace.

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#18756]
We use this in different apps (activity, ldap, music, ...) and it is very useful. Should be properly define, that there is `setInterval` and a method called `run` needs to be implemented.

@VicDeo @icewind1991 @blizzz @nickvergessen Opinion on this?

**Comment by nickvergessen** [comment]
:+1:

**Comment by blizzz** [comment]
ack

**Comment by DeepDiver1975** [comment]
I would welcome a proper solution to cron Jobs instead of declaring this public.

**Comment by MorrisJobke** [comment]
> I would welcome a proper solution to cron Jobs instead of declaring this public.

? Do you mean "exectue at 10:04 pm" or what does "cron jobs" mean? Because this is exactly what can be addressed by this but with relative time => aka execute at most every x seconds.

**Comment by icewind1991** [comment]
For async jobs we have a new public api, what we miss is an easy way for apps to run  background job every X min

**Comment by DeepDiver1975** [comment]
> ? Do you mean "exectue at 10:04 pm" or what does "cron jobs" mean? Because this is exactly what can be addressed by this but with relative time => aka execute at most every x seconds.

I did start a discussion about this already in one issue - we need a dedicated cron job entry point for cron jobs. 
Same for async jobs - these are two isolated mechanisms - we currently try to solve both with one approach - which is wrong.

**Comment by DeepDiver1975** [comment]
I want the separation of these two mechanisms
