### ISSUE TITLE
Can not Upload Folder through WebUI, Cannot Drag and Drop Folder In All Browser except Chorme

### ISSUE THREAD

**Issue by IYOTTA** [owncloud/core#18761]
I cannot upload folder through upload button and Drag and Drop Folder only work in Chrome. 

Safari,IE, Firefox not supported. 
At least, How I can upload Folder through WebUI (Upload button)

**Comment by karlitschek** [comment]
This is a limitation of html5 and other browsers. nothing we can do to fix until this is implemented.

**Comment by IYOTTA** [comment]
Thank you very much.

**Comment by RealRancor** [comment]
Thats also documented here:

> You can also drag and drop files from your file manager into the ownCloud Files Application View to upload them to ownCloud. Currently, the only Web browsers that support drag-and-drop folders are Chrome and Chromium.

https://doc.owncloud.org/server/8.1/user_manual/webinterface.html#navigating-the-main-user-interface
