### ISSUE TITLE
Disk low message

### ISSUE THREAD

**Issue by pellaeon** [owncloud/core#18760]
Related: #8491 , #5475

The conclusion reached in #8491 is to add a disk low message.

I plan to show it to the admin users once they log in.

What do you think?

**Comment by DeepDiver1975** [comment]
You cannot reliably ask the OS for the diskspace.
There are system monitoring tools which do a much better job.

**Comment by PVince81** [comment]
There has been a change of behavior regarding "unlimited quota", see https://github.com/owncloud/core/issues/19988

Not sure if this ticket is still relevant ?

Basically ownCloud will not show the disk's actual free space any more when no quota is set. It will only show "Unlimited". The only case where the disk's actual free space could become visible is for example if a user has a quota of 5 GB but there is only 2 GB free space, in which case the UI will show "2 GB" available space.

**Comment by PVince81** [comment]
Won't fix for now
