### ISSUE TITLE
username and Display_name owncloud mail share

### ISSUE THREAD

**Issue by wnnz34** [owncloud/core#18766]
Hello to every one,
i'm working on a Project and i want in the mail Share display the user Display_Name (the one who is sharing the data) and username (the one who is receving the sharing data by email notification in owncloud).
for the one who is sharing the data is very simple but i also want to display the displayname or username of the one who's receiving the Mail Notification of Owncloud. some exemples:
hello (the displayname of the one who is receiving the mail notification)  ....... that admin... shared ........ with you.

any idea ?

thank you for your Reply

**Comment by PVince81** [comment]
@wnnz34 you can try changing the email templates https://github.com/owncloud/core/blob/master/core/templates/mail.php

**Comment by wnnz34** [comment]
thx for the reply.
but i also want to display the name ou user name of the one who's receiving the Mail notification insteat of Hello i would like to say hello PVince81 , wnnz34 want to share something with you etc.. etc...
and i don't know how.
thank you for the replies
