### ISSUE TITLE
Wrong Version Info in OC 8.1.2

### ISSUE THREAD

**Issue by hitam4450** [owncloud/core#18768]
![oc-8 1 2](https://cloud.githubusercontent.com/assets/9738727/9631174/83e8739a-517f-11e5-9f08-bf68cd2ccb0b.png)
 I just Installed OC 8.1.2 - Version Info does not match!

regards, hitam4450

**Comment by karlitschek** [comment]
how did you install ownCloud? Can you check the content of version.php?
@jnweiger @cmonteroluque

**Comment by hitam4450** [comment]
I installed by setup-owncloud.script:

Content of version.php:
<?php 
$OC_Version = array(8,1,1,3);
$OC_VersionString = '8.1.1';
$OC_Edition = '';
$OC_Channel = 'stable';
$OC_Build = '2015-08-08T00:57:40+00:00 ca66a705ec59cce1ac60c2fb92ec543e296c23f9'

Regards, hitam4450

**Comment by DeepDiver1975** [comment]
From my pov the release itself is okay. Maybe something went wrong on execution of the Installation.

https://github.com/owncloud/core/blob/v8.1.2/version.php

**Comment by karlitschek** [comment]
hmm. i checked this and it is fetching the correct version for me. matybe the download mirrors where not synced yet.

**Comment by hitam4450** [comment]
Hi, I installed again with setup-owncloud.script: This time is was successful. After installing did finished, it upgraded bey maintenance mode to 8.1.2.

However, i do had to add a new admin account. Could not use the old one from the main installation.

Both OC instances running on the same server, same webserver, same database, different directories.
Is this a bug or a feature??

regards, Hitam4450

**Comment by karlitschek** [comment]
this script is only for new installations. you shouldn't use it for upgrade

**Comment by hitam4450** [comment]
Thanks for your reply and info. Prior to install i erase the content of the test directory. So at least from this point, it is anew installation. perhaps not necessarily for th mysql database! However, i always use the same login information. 

regards, hitam4450

**Comment by hitam4450** [comment]
However, in the users section I see all 'old' admin accounts!

regards, hitam4450
