### ISSUE TITLE
Unit tests of apps are broken

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#18765]
```
PHP Fatal error:  Uncaught exception 'Exception' with message 'Path not allowed: /home/nickv/ownCloud/master/core/tests/lib/testcase.php' in /home/nickv/ownCloud/master/core/lib/autoloader.php:132
Stack trace:
#0 /home/nickv/ownCloud/master/core/lib/autoloader.php(152): OC\Autoloader->isValidPath('/home/nickv/own...')
#1 [internal function]: OC\Autoloader->load('Test\\TestCase')
#2 /home/nickv/ownCloud/master/core/repos/notifications/tests/testcase.php(24): spl_autoload_call('Test\\TestCase')
#3 /home/nickv/ownCloud/master/core/lib/autoloader.php(163): require_once('/home/nickv/own...')
#4 [internal function]: OC\Autoloader->load('OCA\\Notificatio...')
#5 /home/nickv/ownCloud/master/core/repos/notifications/tests/appinfo/RoutesTest.php(26): spl_autoload_call('OCA\\Notificatio...')
#6 /home/nickv/Tools/vendor/phpunit/phpunit/src/Util/Fileloader.php(93): include_once('/home/nickv/own...')
#7 /home/nickv/Tools/vendor/phpunit/phpunit/src/Util/Fileloader.php(77): PHPUnit_Util_Fileloader::load('/home/nickv/own...')
#8 /home/nickv/To in /home/nickv/ownCloud/master/core/lib/autoloader.php on line 132
```

Caused by #18396

FIX IT @icewind1991 @Xenopathic 
or give an example on the activity/mail/gallery/notifications app so devs can copy it.
Also send an email to the dev mailing list with a code snippet that can be used to fix it.

// cc @oparoz

**Comment by Xenopathic** [comment]
`include \OC::$SERVERROOT . '/tests/bootstrap.php`

**Comment by icewind1991** [comment]
Or add `\OC::$loader->addValidRoot(OC::$SERVERROOT . '/tests');` to your own bootstrap

**Comment by nickvergessen** [comment]
Tests is removed on packaging, so why do this on the git repo?

**Comment by icewind1991** [comment]
Because we want to make the autoloader as tight as possible, only allowing paths that are actually needed to run the code, /tests is not required to run the code, only the tests, so it should only be allowed for the tests

**Comment by nickvergessen** [comment]
Well then follow one of the other steps I suggested above

**Comment by Xenopathic** [comment]
@nickvergessen Email has been sent to devel@owncloud.org, all done :smile:
