### ISSUE TITLE
[7.0.X] Sharing a text file without editing it, the thumbnail is lost

### ISSUE THREAD

**Issue by davitol** [owncloud/core#18774]
### Steps to reproduce

1. Create a txt file and do NOT write anything in it.
2. Share the file with another user.
3. Log in with 'user B' and go to the files view 

### Expected behaviour

The thumbnail should be shown in the files view of user B

### Actual behaviour

The preview icon is not shown

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:"8.1.2.0","versionstring":"8.1.2RC1"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity
 - admin_audit
 - enterprise_key
 - files
 - files_locking
 - files_sharing
 - files_sharing_log
 - files_texteditor
 - files_trashbin
 - files_versions
 - firstrunwizard
 - provisioning_api
 - sharepoint
 - templateeditor
 - user_ldap
 - windows_network_drive
**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome

![captura de pantalla 2015-09-02 a las 15 54 56](https://cloud.githubusercontent.com/assets/10596560/9633382/eb95e6be-518c-11e5-9f84-fb9ccb2e8e07.png)

**Comment by MorrisJobke** [comment]
Doesn't happen anymore in master -> closing
