### ISSUE TITLE
An endpoint for fast etag retrieval.

### ISSUE THREAD

**Issue by ogoffart** [owncloud/core#18776]
The owncloud client currently do a PROPFIND every 30 second to know the etag of the configured directory to sync to know if it should start a sync.

I heard rumors saying that this was causing a lot of load on the server. And it is the bottleneck for having more user on the same hardware.

@icewind1991 suggested to add a new special endpoint which would query the database to return quickly the etag of a given path by querying the database without having to check for authentication, or to load all the apps.

For example:
 GET cloud.example.com/getetag.php?fileid=1234
would  just quickly query the cache for the etag of the directory whose id is 1234.
That would be perfect for the client need.

We need to review the security implications of having this information available without authentication.  The fileids are not easy to guess, and the etag does not  convey so much information, so I think it should not allow any information leak.

**Comment by icewind1991** [comment]
From the server's pov this makes it easier for us since we dont need to do any of the bootstrap besides getting the db connection which saves us like 90% of the time spent

cc @LukasReschke for the performance impact of getting etag for file ids without any auth

**Comment by guruz** [comment]
Can we have the endpoint in the capabilities result? 
As a list item? Then at a later point there could be different endpoints e.g. ```long-polling``` or ```websocket```.

**Comment by guruz** [comment]
Further idea: Have support for checking multiple folders.

**Comment by DeepDiver1975** [comment]
No longer polli or websockets. This will not work in our architecture.

From my pov the propfind is exactly the call to get the etag. Instead of introducing yet another special URL we need to improve the code path involved in the webdav calls.

**Comment by icewind1991** [comment]
> From my pov the propfind is exactly the call to get the etag. Instead of introducing yet another special URL we need to improve the code path involved in the webdav calls.

The simple fact is that we will never be able to get "normal" propfind as fast, with a specific endpoint we only need to get the db connection and run a single query. We can skip *everything* else, no apps, no auth, no filesystem, just a single query.

**Comment by DeepDiver1975** [comment]
This approach is too simplistic. Think about objectstore Integration or storage based meadata cache.

**Comment by icewind1991** [comment]
We could ship the endpoint in a seperate app, expose it with the capabilities api and allow other apps to provide alternate implementations for specific use cases

**Comment by DeepDiver1975** [comment]
Too much special logic. Lets focus on improving all the crazy around base.PHP -  this will help all request.

**Comment by guruz** [comment]
@DeepDiver1975 The goal here is to get improvements that the current API can't handle.
If I remember correctly the call is supposed to be something like:

```/our/new/api/fileId=12345&expectedEtag=DHKJWOEWEDSLD```

That could boil down to 1 simple SQL query without instanciating any apps or any other fancy things (maybe even without authentication since it would just return true or false)

**Comment by icewind1991** [comment]
main reasoning behind the need of such an endpoint being that the vast majority of all request made by the client is polling to see if something changed on the server, if we can optimize the those calls it could greatly reduce the server load for large instances
