### ISSUE TITLE
Change password flow

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#18784]
@guruz forced @jancborchardt to dictate this:
1. Disable change password button after it has been clicked
2. Put the checkmark on the right of the change password button
3. While the change is happening but a spinner in place where the checkmark should be
4. Hide the checkmark again after 5 seconds
5. Activate the change password button again
6. Hide the tipsy as soon as the button is clicked

**Comment by jancborchardt** [comment]
@owncloud/designers @MorrisJobke someone of you up for this?

**Comment by PVince81** [comment]
@owncloud/design
