### ISSUE TITLE
Feature request: user/group/device policies for desktop client

### ISSUE THREAD

**Issue by camerondw** [owncloud/core#18789]
I like the new options in the version 2 desktop client, especially the one where it asks for confirmation before downloading folders larger than XX GB.

However the default value seems to be 500MB, which is a bit high for my liking. Some of my road warriors use USB mobile broadband dongles or built in 3G/LTE wireless devices in their laptops. I don't want to have to micromanage their client install and set everyone's confirmation limit to something lower. Or edit their ignored files in case something goes strange with their smartphone client.

Some sort of central policy for clients based on their ID, group, client type and device name would be great. Then I can configure one for my roadies that asks for confirmation for anything larger than 50MB, prevents them adding a second account, maybe prevent them from removing the one I've configured, limit the download bandwidth automatically, things like that. Would be super nice if the desktop client could determine if it was connected by Wifi and make policy determinations based on that as well (no confirmations based on folder size and no bandwidth limits).

**Comment by karlitschek** [comment]
please reopen this in the client repository.
