### ISSUE TITLE
Upgrade issue 8.1.1 to 8.1.2

### ISSUE THREAD

**Issue by redhell** [owncloud/core#18785]
./occ upgrade:

ownCloud or one of the apps require upgrade - only a limited number of commands are available
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Disabled 3rd-party app: calendar
Disabled 3rd-party app: contacts
Disabled 3rd-party app: documents
Disabled 3rd-party app: galleryplus
Disabled 3rd-party app: tasks
Update 3rd-party app: calendar
Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "calendar_index" as such route does not exist.
Update failed
Maintenance mode is kept active

rerun ./occ upgrade after deleting calendar folder is successful.

Here is the log entry:
Exception: {"Exception":"Symfony\\Component\\Routing\\Exception\\RouteNotFoundException","Message":"Unable to generate a URL for the named route \"calendar_index\" as such route does not exist.","Code":0,"Trace":"#0 \/lib\/private\/route\/router.php(306): Symfony\\Component\\Routing\\Generator\\UrlGenerator->generate('calendar_index', Array, false)\n#1 \/lib\/private\/route\/cachingrouter.php(53): OC\\Route\\Router->generate('calendar_index', Array, false)\n#2 \/lib\/private\/urlgenerator.php(65): OC\\Route\\CachingRouter->generate('calendar_index', Array)\n#3 \/lib\/private\/helper.php(139): OC\\URLGenerator->linkToRoute('calendar_index', Array)\n#4 \/lib\/public\/util.php(306): OC_Helper::linkToRoute('calendar_index', Array)\n#5 \/apps\/calendar\/appinfo\/app.php(30): OCP\\Util::linkToRoute('calendar_index')\n#6 \/lib\/private\/app.php(139): require_once('\/var\/www\/vhosts...')\n#7 \/lib\/private\/app.php(120): OC_App::requireAppFile('calendar')\n#8 \/lib\/private\/app.php(1173): OC_App::loadApp('calendar', false)\n#9 \/lib\/private\/installer.php(218): OC_App::updateApp('calendar')\n#10 \/lib\/private\/installer.php(248): OC_Installer::updateApp(Array)\n#11 \/lib\/private\/updater.php(487): OC_Installer::updateAppByOCSId('168707')\n#12 \/lib\/private\/updater.php(308): OC\\Updater->upgradeAppStoreApps(Array)\n#13 \/lib\/private\/updater.php(195): OC\\Updater->doUpgrade('8.1.2.1', '8.1.1.3')\n#14 \/core\/command\/upgrade.php(181): OC\\Updater->upgrade()\n#15 \/3rdparty\/symfony\/console\/Symfony\/Component\/Console\/Command\/Command.php(253): OC\\Core\\Command\\Upgrade->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#16 \/3rdparty\/symfony\/console\/Symfony\/Component\/Console\/Application.php(874): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#17 \/3rdparty\/symfony\/console\/Symfony\/Component\/Console\/Application.php(195): Symfony\\Component\\Console\\Application->doRunCommand(Object(OC\\Core\\Command\\Upgrade), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#18 \/3rdparty\/symfony\/console\/Symfony\/Component\/Console\/Application.php(126): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#19 \/lib\/private\/console\/application.php(94): Symfony\\Component\\Console\\Application->run(NULL, NULL)\n#20 \/console.php(68): OC\\Console\\Application->run()\n#21 \/occ(11): require_once('\/var\/www\/vhosts...')\n#22 {main}","File":"\/3rdparty\/symfony\/routing\/Symfony\/Component\/Routing\/Generator\/UrlGenerator.php","Line":134}

**Comment by RealRancor** [comment]
Dup of https://github.com/owncloud/core/issues/18350, https://github.com/owncloud/core/issues/18334, https://github.com/owncloud/core/issues/18333, https://github.com/owncloud/core/issues/18317, https://github.com/owncloud/core/issues/18329, https://github.com/owncloud/core/issues/18296, https://github.com/owncloud/core/issues/18224 and many more...

**Comment by redhell** [comment]
Oops. Was too lazy to search... closing this issue.
