### ISSUE TITLE
initTemplateEngine() is unnecessarily  called for WebDAV clients

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#18795]
in base.php ````initTemplateEngine()```` loads a bunch of JS files.
This is also done when the client connects by WebDAV (remote.php) In that case all the JS is obviously not needed, so I suggest to skip the call of  ````initTemplateEngine()```` for every request that does not need JS.
Anything that would break by that?

**Comment by PVince81** [comment]
Not sure if it would break anything, might be worth a try :wink: 

@nickvergessen @icewind1991 @Xenopathic

**Comment by PVince81** [comment]
Also see https://github.com/owncloud/core/issues/18804
For many requests there is too much that gets initialized.

**Comment by individual-it** [comment]
here the PR  #19114

**Comment by DeepDiver1975** [comment]
THX @individual-it - for sure an interesting approach.

Looking at that code segment I'm asking myself if this isn't something we should move into the ctor of the template class.

Might be worth a try ...

**Comment by individual-it** [comment]
"interesting" out of the mount of a German sounds pretty bad :grinning: 

actually I would say for WebDAV and the REST API no theme or an empty one should be loaded

**Comment by DeepDiver1975** [comment]
> "interesting" out of the mount of a German sounds pretty bad :grinning:

hehe .... but I'm into pure english speaking it business for more then 15 years ... I *most probably* know how to use this language :speak_no_evil:

**Comment by individual-it** [comment]
here an other "interesting" approach: #19144 
That does combine #19114 and the idea of @icewind1991 https://github.com/owncloud/core/pull/19114#issuecomment-141071599

**Comment by individual-it** [comment]
fixed by #19293
