### ISSUE TITLE
messy Federation html code

### ISSUE THREAD

**Issue by karlitschek** [owncloud/core#18797]
The html code and the banner look a bit messy on the personal page. I think we should collapse this and only show it when clicking on a 'blog' button that should be next to the other sharing buttons.

![fed](https://cloud.githubusercontent.com/assets/867445/9654777/1ebe83ac-522d-11e5-93b9-61b6e1803bf2.jpg)

**Comment by karlitschek** [comment]
@jancborchardt

**Comment by karlitschek** [comment]
@schiesbn

**Comment by jancborchardt** [comment]
So much nicer now, really good call @karlitschek :) and good work @LukasReschke

**Comment by jancborchardt** [comment]
(Btw let’s always tag the issues with the correct milestone. Then when writing up release notes / changelog, we simply need to look through the closed milestone issues and merged pull requests. cc @jospoortvliet)
