### ISSUE TITLE
Can not Upload Unnamed FileName

### ISSUE THREAD

**Issue by IYOTTA** [owncloud/core#18790]
I can not Upload Unnamed File.
It's show me "Upload failed. Could not find uploaded file"

Example:
.htaccess 
I cannot upload this file.

**Comment by individual-it** [comment]
.htaccess is blacklisted by default.
check the documentation of the config file: https://doc.owncloud.org/server/8.0/admin_manual/configuration_server/config_sample_php_parameters.html#all-other-config-options

````
/**
 * Blacklist a specific file or files and disallow the upload of files
 * with this name. ``.htaccess`` is blocked by default.
 * WARNING: USE THIS ONLY IF YOU KNOW WHAT YOU ARE DOING.
 */
'blacklisted_files' => array('.htaccess'),

**Comment by IYOTTA** [comment]
Thank you so much.

**Comment by IYOTTA** [comment]
@individual-it It doesn't related with config file.I have removed that line but still occur error.
I think it about Unname File, not File Extension.

sry for my terrible English.

**Comment by individual-it** [comment]
If you delete the complete line it will fallback to the default, what is to block .htaccess files.
To allow them I guess you will have to empty that array

````'blacklisted_files' => array(''),

Am 3. September 2015 16:03:55 NPT, schrieb Sally <notifications@github.com>:
>@individual-it It doesn't related with config file.I have removed that
>line but still occur error.
>I think it about Unname File, not File Extension.
>
>sry for my terrible English.
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/owncloud/core/issues/18790#issuecomment-137401598

Artur Neumann

-- 
www.individual-it-services.de
EDV Lösungen, die auf Ihre Wünsche und Anforderungen angepasst sind.
Blog: http://individualit.wordpress.com/
Aktuelle Infos: http://twitter.com/INDIVIDUALIT

Bankverbindung:
KtoNr:    46201786
BLZ:     47650130
Sparkasse Detmold

Steuernummer:   313/5277/1775
Ust-IdNr: 	DE239103348
