### ISSUE TITLE
cramped preview in sidebar

### ISSUE THREAD

**Issue by karlitschek** [owncloud/core#18796]
The picture thumbnail in the sidebar looks a bit cramped. Maybe we should add some padding similar to the other and smaller thumbnails in the sidebar 
![pic](https://cloud.githubusercontent.com/assets/867445/9654680/9cbf5354-522c-11e5-8c21-ad79a86907ad.jpg)

**Comment by karlitschek** [comment]
@jancborchardt what do you think?

**Comment by karlitschek** [comment]
@jancborchardt who do you suggest can look into that?

**Comment by jancborchardt** [comment]
I will check this out.

**Comment by karlitschek** [comment]
thanks :-)

**Comment by karlitschek** [comment]
So should we close this if I'm the only one who thinks this is not pretty? I'm happy to close if everybody is happy with that :-)

**Comment by jancborchardt** [comment]
@karlitschek I'm undecided. I too think it's a bit strange to have the image stick to the header, but at the same time it's nice to have it a bit bigger.

@owncloud/designers @oparoz what do you think, current behavior or https://github.com/owncloud/core/pull/18900 ?

**Comment by stefan-niedermann** [comment]
current behaviour (big picture) looks better from my pov.

**Comment by raghunayyar** [comment]
I am okay with this as well.

**Comment by oparoz** [comment]
I understand what Frank means. One reason is probably that the sidebar is too flat. Even in today's world of flat UIs, there are still shadows to help separate overlapping elements.
https://www.google.de/design/spec/what-is-material/elevation-shadows.html#elevation-shadows-elevation-android-

And it's also OK to have different shades of white. Right now, all the panels are the same colour and they're only separated by a thin border.

Maybe there should be a background colour for the header and then the padding would work? It would also help when we need to pick the right background colour for the image ;)

**Comment by oparoz** [comment]
## 2 examples

### Looks weird
![cramped](https://cloud.githubusercontent.com/assets/323220/9800045/1744948e-580b-11e5-935b-b6d52ee1e312.png)

### What am I looking at ?!?
![cramped_white](https://cloud.githubusercontent.com/assets/323220/9800058/2822648e-580b-11e5-84eb-a7ace0ced792.png)

**Comment by jancborchardt** [comment]
@icewind1991 can you maybe fix those examples? Small images like icons should never be zoomed in in the sidebar. Only centered vertically and horizontally.

**Comment by icewind1991** [comment]
Fix in #18979

**Comment by oparoz** [comment]
Let's re-open until the PR is merged.

**Comment by jancborchardt** [comment]
Huh, I thought we closed this? Closing this and the PR too, cause people seem to like the current behavior better (see above).

**Comment by oparoz** [comment]
The PR is still open and fixes issues mentioned here.
