### ISSUE TITLE
Files app jumps to top position after going back from a sub-folder

### ISSUE THREAD

**Issue by vader2014** [owncloud/core#18805]
When i go up from a sub-folder (via the back button in Firefox) the list view jumps back to the top of the file list. This is counterintuitive (and annoying) especially if there are a lots of sub-folders. This is similar to issue https://github.com/owncloud/gallery/issues/126 of the gallery app .

Can this behavior be changed/fixed?

**Comment by oparoz** [comment]
You'll have to wait for ownCloud to drop support for IE8, probably in 9.x

**Comment by PVince81** [comment]
This means the JS code would need to keep track of what the last focussed folder was.
This can either be done by appending "?scrollTo" to the URL before pushing it on the history stack, or by using the "stack entry attributes" of the history API.

**Comment by PVince81** [comment]
CC @owncloud/designers 

I think this makes sense

**Comment by jancborchardt** [comment]
Yeah, the scroll state should be saved when going back up from inside folders. Ideally we also highlight the folder where you just came out of.

**Comment by enoch85** [comment]
Any news here?

**Comment by gw0** [comment]
Same thing happens when coming back from the slideshow image viewer. The file list seems to reload causing the browser to forget the scrolling position.

**Comment by pellaeon** [comment]
#20132 fixes this, but I have not completed the JS tests in the PR.
