### ISSUE TITLE
[l10n] *.pl script crashes in 8.0.6

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/core#18808]
A user reported that the *.pl script to start translation crashes in 8.0.6. In 8.0.2 it didn't crashed. The user took the script from 8.0.2 and ran it in 8.0.6. This worked too.

### Steps to reproduce
1. run *.pl translation script in 8.0.6 ==> crash

### Expected behaviour
*.pl script in 8.0.6 shouldn't crash

### Actual behaviour
*.pl script to start translation crashes in 8.0.6

### Server configuration
**ownCloud version:** (see ownCloud admin page)
8.0.6

**Updated from an older ownCloud or fresh install:**
fresh install

@MorrisJobke Is this already fixed?

00003729

**Comment by MorrisJobke** [comment]
Works here. Tested on 8.0.2 and 8.0.6. Also there was no change that maybe fixed something.

You need to install Locale::PO

Error when it is not installed:
```
$ perl l10n/l10n.pl 
Can't locate Locale/PO.pm in @INC (you may need to install the Locale::PO module) (@INC contains: /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl .) at l10n/l10n.pl line 3.
BEGIN failed--compilation aborted at l10n/l10n.pl line 3.
```

**Comment by michaelstingl** [comment]
@MorrisJobke Thanks!
