### ISSUE TITLE
Remove 'raw' php for app loading - aka kill app.php

### ISSUE THREAD

**Issue by icewind1991** [owncloud/core#18804]
Currently loading apps is done by including various php files from the apps (app.php, routes.php, etc) and have the app do whatever it wants inside those php files.

That leads to core having little controll about the timing of loading the various parts of an app which leads to performance issues (loading navigation entries every request) and potential bugs (generating urls before routes are properly loaded).

Instead of loading raw php files we (@Xenopathic and me) had the idea of moving all the app initialization code to the `Application` use by appframework apps, the application class can be extended with methods for the various things that apps need to do (`getRoutes`, `getAppNavigation`, `setUpStorages`, etc) which gives core controll about the order we do those steps in (we can finally be sure that we have all routes loaded before we need to generate a url).

For backwards compatibility the plan was to have the contructor of the base application class fallback to loading app.php if it exists and fallback to loading routes.php for routes.
That way we can introduce these changes gradually without breaking 3rdparty apps and slowly move apps over to a more modern way of loading.
We can slowly move more and more  code over from app.php to a dedicated methods without ever breaking old apps.

cc @DeepDiver1975 @PVince81 @MorrisJobke @Xenopathic  
- This plan is brought to you by chinese food

**Comment by icewind1991** [comment]
PR for the first step (load the application class from core instead of app.php): #18758

**Comment by PVince81** [comment]
@icewind1991 I think another extension for this is also having the following be registered in a controlled manner:
- registering commands
- registering background jobs
- routes
- navigation entries
- etc ...

Instead of having these register for **every** call when apps.php is loaded, these would be loaded on-demand inside of functions from the `Application` class.

CC @nickvergessen we discussed something similar a while ago

**Comment by Xenopathic** [comment]
@PVince81 Correct, that'd be a nice way to introduce easy async capabilities to applications, without requiring that *everything* is a closure.

Also, some way to get rid of `OCP\Util::registerPersonal()` and `OCP\Util::registerAdmin()` for settings page templates would be really nice...

**Comment by Xenopathic** [comment]
PS: Also brought to you by the Round Robin Talkshow cc @cdamken

**Comment by jospoortvliet** [comment]
Darn, this sounds like something @evert said was a good idea when I asked him how he thought ownCloud should be handling apps ;-)

If I understood his comments and understand what this does correctly...

**Comment by evert** [comment]
It is partially yea =)

**Comment by cdamken** [comment]
> PS: Also brought to you by the Round Robin Talkshow cc @cdamken

Next time I will prepared with the video camera ;)

**Comment by cdamken** [comment]
> This plan is brought to you by chinese food

Next time we go to spicy mexican food to improve the sharing performace ;D

**Comment by PVince81** [comment]
progress has been made already for registering commands, repair steps, etc.

Ideal would be to be able to register generic services, like described in https://central.owncloud.org/t/service-based-app-imlpementation-to-solve-inter-app-dependencies/1615

An example service could be `Storage\IBackend` for apps that provide external storage providers
