### ISSUE TITLE
Installation experience: Permissions section too complicated

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#18800]
Permissions are complicated and technical as they are already. Every time I install ownCloud and click to get to the permissions page, it seems to be more complicated than before: https://doc.owncloud.org/server/8.2/admin_manual/installation/installation_wizard.html#setting-strong-directory-permissions
- Lots of text which no one wants to read just to get ownCloud installed.
- No clear commands.
- No clear 1-2-3 steps.

Instead I always use my personal setup script with these chmod commands:
https://github.com/jancborchardt/owncloud-scripts/blob/master/owncloud-setup.sh#L35-L41

```
mkdir data
sudo chown www-data:www-data data
sudo chown :www-data config/
sudo chmod 775 config/
sudo chown :www-data apps/
sudo chmod 775 apps/
```

Can we simplify that documentation part a bit please? Or even better just show the help directly on this page:
![capture du 2015-09-03 02-09-26](https://cloud.githubusercontent.com/assets/925062/9655150/6d1466be-522f-11e5-8628-0a3f41c03734.png)
Or even have something like an install.sh/update.sh as a single point for people to run which takes care of the permissions (for most common setups at least), similar to my installation & update scripts. For devs, this could include a git pull and git submodule update if it’s detected that the git version is run.

cc @LukasReschke @karlitschek @danimo

**Comment by jancborchardt** [comment]
cc @owncloud/designers as well and @carlaschroder for documentation.

**Comment by karlitschek** [comment]
good idea. Let's add it to the error page or add a link to the documentation or both.

**Comment by carlaschroder** [comment]
How odd...my standard convention is to use phpinfo to find  the http user, not the php commands in the setting strong permissions section. Not sure where they came from. I shall replace them.

The permissions script is battle-tested so don't mess with it. It's the product of much feedback from multiple environments & multiple reviews. You can't have a single universal permissions script unless you write it to auto-detect the ownCloud directories and HTTP user on all distro packages. Or write custom scripts for each distro package.

The issue with simplifying the text is a problem of organization. Sysadmins must know everything on that page-- setting strong permissions, trusted domains, how to find their HTTP user...I'll do what I can to improve the page, as it certainly needs improving, but if you want less text then more of these steps need to be handled by the installer, and not require manual configuration.

**Comment by carlaschroder** [comment]
It's also worth noting that we recommend locating the data/ dir outside of owncloud/. Not sure if that's an appropriate task for the installer. I've already been thinking of something like 'basic' and 'advanced' installation pages.

**Comment by Xenopathic** [comment]
From the documentation page, I think the entire section about 'detecting your HTTP user' should be removed. We should list the values for common distros (as we do), but for other distros the admin should be expected to know what the web server user is.

**Comment by carlaschroder** [comment]
@Xenopathic my master plan is to cross-reference a single phpinfo doc page everywhere it's appropriate, which is many places. Then it's in one place and more maintainable.

**Comment by RealRancor** [comment]
> We should list the values for common distros (as we do), but for other distros the admin should be expected to know what the web server user is.

Keep all the shared hosting users out there in mind. Those are the users with probably the least knowledge. And shared hosters have the strangest permission/user setup.

**Comment by jancborchardt** [comment]
Exactly as @RealRancor said: Not everyone installing ownCloud is a sysadmin. Actually I guess most people are _not_, or rather we should aim to also reach those which aren’t, like Wordpress etc.

**Comment by carlaschroder** [comment]
Right @jancborchardt & @RealRancor. Which is why I also list the correct permissions in addition to the script, because the script is no good to shared hosting users.
