### ISSUE TITLE
Developer experience: Submodule installation error page

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#18801]
Currently looks like this:
![capture du 2015-09-03 01-59-38](https://cloud.githubusercontent.com/assets/925062/9655258/30011780-5230-11e5-9ce7-939841dac6fa.png)

Instead of that we should directly already hint at the command you need to run which is `git submodule update --init`

cc @karlitschek @DeepDiver1975 @owncloud/designers

**Comment by karlitschek** [comment]
sure. We can just add the text.

**Comment by MorrisJobke** [comment]
Fix is in #18811
