### ISSUE TITLE
Cleanup of the oc_ldap_group_mapping table

### ISSUE THREAD

**Issue by ryno83** [owncloud/core#18819]
After testing a lot of configurations for ldap group in my environment, I found that deleted ldap group are not removed from the oc_ldap_group_mapping table. After investigation, i think the cleanup of this table is not implemented at all in user_ldap. Is that true ?

Is this feature planned for future developpement ?

**Comment by PVince81** [comment]
@blizzz

**Comment by blizzz** [comment]
There is no clean up method for groups implemented, correct, and in the moment there are also no plans about it.

**Comment by PVince81** [comment]
Please reopen in [user_ldap app repo](https://github.com/owncloud/user_ldap) if issue persists with 10.0.4 and the latest user_ldap app from marketplace.
