### ISSUE TITLE
Sharing causes recursive mount point initialization

### ISSUE THREAD

**Issue by Xenopathic** [owncloud/core#18818]
Problem seems to be in apps/files_sharing/lib/sharedmount.php:73, where is_dir() is called on a view. This can lead to filesystems being initialized for other users, which calls the sharedmount.php line again...

```
if (!$this->recipientView->is_dir($parent)) {
$parent = Helper::getShareFolder();
}
```

cc @icewind1991 You touched this code in 8cb40f6043c9eb7d2285954a404bd52162851beb? That commit also caused the previous recursion issue

**Comment by LukasReschke** [comment]
cc @danimo Probably the bug on S3

**Comment by LukasReschke** [comment]
cc @karlitschek @cmonteroluque Related to https://github.com/owncloud/core/pull/18810, seems to be what makes S3 very slow.

**Comment by PVince81** [comment]
@icewind1991 any update on this critical issue ?

**Comment by icewind1991** [comment]
I dont think this issue is critical anymore since the share duplication issue was resolved.

We should still look into changing the share code so this is no longer needed though

**Comment by cmonteroluque** [comment]
s3 had a bunch of apache processes spawned the last time it was overwhelmed (this Monday), would this issue cause that? @LukasReschke @Xenopathic

**Comment by LukasReschke** [comment]
> s3 had a bunch of apache processes spawned the last time it was overwhelmed (this Monday), would this issue cause that? @LukasReschke @Xenopathic

Let me get my :crystal_ball: 

:crystal_ball: tells me we should get proper Application Monitoring before @LukasReschke can comment on this. Such as ZendServer etc.

Otherwise we're really just going to continue to guess forever…

**Comment by cmonteroluque** [comment]
sharing will be changed in 9.0
