### ISSUE TITLE
IE9 Login Layout Problem

### ISSUE THREAD

**Issue by IYOTTA** [owncloud/core#18827]
Remember me button and text are wrong position in IE9

![11111](https://cloud.githubusercontent.com/assets/14050802/9679951/473b5a08-531d-11e5-9e3d-3744a20ba763.jpg)
![111112](https://cloud.githubusercontent.com/assets/14050802/9679950/4739f636-531d-11e5-9a25-2c51291a93ce.jpg)

**Comment by karlitschek** [comment]
@jancborchardt

**Comment by jancborchardt** [comment]
@IYOTTA please use the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by PVince81** [comment]
Assuming this was observed on master. It's already fixed in 8.2RC1.
