### ISSUE TITLE
Gallery/Gallery+ Doesn't Load (Solved)

### ISSUE THREAD

**Issue by raj0rshi** [owncloud/core#18824]
Latest jQuery and adding custom Content-Security-Policy will solve this problem.
Step 1: replace the /core/vendor/jquery/jquery.min.js with the latest jQuery from https://jquery.com/download/.
Step 2: add custom csp in config file.
       'custom_csp_policy' => "img-src * data:;",

**Comment by karlitschek** [comment]
@LukasReschke

**Comment by LukasReschke** [comment]
Thanks for the report! Could you fill out our [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) to provide us with more information about your issue?

**Comment by oparoz** [comment]
Interesting... Jquery needs its own policy?

**Comment by raj0rshi** [comment]
### Expected behaviour
Galary shoud produce some preview of images.

### Actual behaviour
When go to galary app from the menu. the loading never ends. error in the brouser log that says content security policy blocks loading image.

### Server configuration
**Operating system**:
Ubuntu 14.04.2 LTS (GNU/Linux 3.16.0-30-generic x86_64)
**Web server:**
Apache/2.4.12 (Ubuntu) 
**Database:**
Oracle 11g
**PHP version:**
PHP 5.5.27-1+deb.sury.org~trusty+1 (cli) (built: Jul 15 2015 12:14:44)
**ownCloud version:** (see ownCloud admin page)
8.0.3

**Updated from an older ownCloud or fresh install:**
Fresh Install

**List of activated apps:**
Activity, Gallery+,
Deleted files 0.6.2,
File Locking 
Mail Template Editor 0.1
PDF Viewer 0.7
Provisioning API 0.2
Versions 1.0.5
Share Files 0.6.1

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'oc3wxibk1u59',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
,
  ),
  'datadirectory' => '/var/www/data',
  'overwrite.cli.url' => '',
  'dbtype' => 'oci',
  'version' => '',
  'dbname' => 'cloudr',
  'dbhost' => '',
  'dbtableprefix' => '',
  'dbuser' => '',
  'dbpassword' => '',
  'logtimezone' => 'UTC',
  'installed' => true,
  'loglevel' => 4,
  'maintenance' => false,
  'mail_smtpmode' => 'php',
  'mail_smtpauthtype' => 'PLAIN',
);


**Are you using external storage, if yes which one:** 
NO

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
YES, Webdav

**Browser:**
All browsers
**Operating system:**
All OS
#### ownCloud log (data/owncloud.log)
No error in log

#### Browser log

a) The javascript console log
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https:******.com 'unsafe-eval'").

**Comment by oparoz** [comment]
Fixed in the next Gallery+
