### ISSUE TITLE
Asterisks Fill Blank Password Field in IE8

### ISSUE THREAD

**Issue by ncwolf** [owncloud/core#18820]
### Steps to reproduce
When logging into owncloud 8.1.1 on IE8, asterisks fill the blank password field. This is confusing to users b/c it looks like they are overwriting a password in the field to enter their own.

http://nicolewolfart.com/dir

### Expected behaviour
Password field should contain the word "password" (as in all other browsers.)

### Actual behaviour
Blank password field contains asterisks.

### Server configuration
**Operating system**: Linux

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.4.43

**ownCloud version:** 8.1.1

**Updated from an older ownCloud or fresh install:** Fresh Install

**List of activated apps:** None. Performed default install on 9/1/15.

**Comment by oparoz** [comment]
@jancborchardt @MTRichards

**Comment by PVince81** [comment]
It's probably the placeholder shim that isn't working properly on IE8.

**Comment by PVince81** [comment]
For IE8 the  placeholder doesn't work properly, so best is to simply make the fields empty when IE8 is detected. There are already fallback labels for that.

**Comment by davitol** [comment]
As IE8 support is dropped in 9.0 I will close this issue.
