### ISSUE TITLE
Oauth 2.0 universal external storage connection

### ISSUE THREAD

**Issue by krsvital** [owncloud/core#18822]
I'd like to see universal type to external storage connection by Oauth 2.0 authorization, now oneDrive, Yandex.Disk doesn't supported but Google and Dropbox works well. Will you do this feature in future?

**Comment by PVince81** [comment]
@Xenopathic

**Comment by Xenopathic** [comment]
Currently only Google Drive external storages use OAuth 2.0, Dropbox uses OAuth 1.0 (we use an outdated SDK), and we don't have implementations of oneDrive or Yandex.Disk. The OAuth 2.0 implementation is theoretically generic and can be applied to any compatible storage, but the URL is currently hardcoded. Once that is somehow injected into the storage then any storage type could use OAuth 2.0, with the same code.

**Comment by krsvital** [comment]
implementation for yandex disk - https://tech.yandex.ru/disk/rest/

video for OneDrive API - https://channel9.msdn.com/Events/BUILD/2012/3-139

**Comment by PVince81** [comment]
oauth 2.0 is only the authentication protocol, not the storage access protocol. Each are different.

External storages should be written as external apps. Not related to core.

Feel free to open discussions on http://central.owncloud.org/ about writing apps for other storages.
