### ISSUE TITLE
Problems with CIFS and OC login

### ISSUE THREAD

**Issue by gig13** [owncloud/core#18837]
### Steps to reproduce
1. Setup LDAP for users
2. Setup CIFS and OC login
3. Try to login without domain information

### Expected behaviour
Users should be able to login and access the mount

### Actual behaviour
A logon failure with -- Path is not readable error is logged in the owncloud,log

### Server configuration
**Operating system**: RHEL 6

**Web server:** Apache 2.4

**Database:** MariaDB 5.5.41

**PHP version:** 5.4.16

**ownCloud version:** 8.1.1

**Updated from an older ownCloud or fresh install:** Updated

**List of activated apps:** See config report at https://s3.owncloud.com/owncloud/index.php/apps/files?dir=%2FShared%2Fowncloud%2Fsupport%2Fgithub-issues%2Fcore%2F18837

**The content of config/config.php:**

**Are you using external storage, if yes which one:** Yes - CIFS

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** LDAP -- see config report

#### LDAP configuration (delete this part if not used)
See config report

#### ownCloud log 
See screenshot at https://s3.owncloud.com/owncloud/index.php/apps/files?dir=%2FShared%2Fowncloud%2Fsupport%2Fgithub-issues%2Fcore%2F18837

We suspect their is an issue with the login due to a confusion with the domain.

@MorrisJobke @blizzz

**Comment by Xenopathic** [comment]
This sounds like a similar issue to #13407, where there is no way to specify a domain for SMB mounts (with OC login, with the normal one the user field can be extended). There is a PR open to fix this: #18473

**Comment by bboule** [comment]
@gig13 looks like this PR was set for 8.2  #18473  it looks like this was merged into 8.2 does this solve the problem?

**Comment by gig13** [comment]
Double checking with originator
