### ISSUE TITLE
Unable to generate a URL for the named route "contacts_index"

### ISSUE THREAD

**Issue by github-user-1** [owncloud/core#18836]
I just tried to upgrade to version 8.1.2 - the upgrade was manual, i.e. I effectively deleted all folders except "config" and "data" and copied all 8.1.2 files in overwrite mode onto the server via ftp. I got the following error-message (see screenshot) with the request to raise the issue encountered here.

![owncloud issue](https://cloud.githubusercontent.com/assets/6796538/9690671/2c38f938-533e-11e5-871d-a24b9a01c6fe.gif)

**Comment by RealRancor** [comment]
Looks similar to https://github.com/owncloud/core/issues/18224 expected that it's "contacts_index"

**Comment by MorrisJobke** [comment]
Fixed in #18839

**Comment by schiesbn** [comment]
Seems to be only fixed for 8.2 but it is a upgrade issue from 8.0 to 8.1, so we also need a fix for 8.1.

@Xenopathic You created the fix for 8.2. any chance to have a small fix for 8.1? Don't like the idea to change the way the autoloader works as a bug fix for a maintenance release, so backport is probably not a option.

**Comment by LukasReschke** [comment]
> @Xenopathic You created the fix for 8.2. any chance to have a small fix for 8.1? Don't like the idea to change the way the autoloader works as a bug fix for a maintenance release, so backport is probably not a option.

There is https://github.com/owncloud/core/pull/18844, https://github.com/owncloud/core/pull/18843 and https://github.com/owncloud/core/pull/18843

**Comment by schiesbn** [comment]
@LukasReschke thanks... didn't saw the backports.

@github-user-1 Maybe you can try if this solves the upgrade issue for your (you only need to change two lines) https://github.com/owncloud/core/pull/18844/files

**Comment by schiesbn** [comment]
backports merged, will be fixed with 8.1.3
