### ISSUE TITLE
Wrong method documentation in INavigationManager 

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#18838]
> 	 * @param array|\Closure $entry Array containing: id, name, order, icon and href key
	 *					The use of a closure is preferred, because it will avoid
	 * 					loading the routing of your app, unless required.

The only way to add an entry from now on is to use a closure, so the documentation has to be fixed, correct?

@Xenopathic @tomneedham

**Comment by Xenopathic** [comment]
@oparoz FIXIT! :laughing:

**Comment by cmonteroluque** [comment]
lovely. Running out of time to keep in 8.2

**Comment by cmonteroluque** [comment]
This issue will fall off 8.2 if not resolved by 6 Oct

**Comment by nickvergessen** [comment]
No? It still does and should allow the array
https://github.com/owncloud/core/blob/master/lib/private/navigationmanager.php#L48-L54

**Comment by oparoz** [comment]
@nickvergessen The problem is not whether the navigationmanager allows the array or not. It doesn't work if you do, so that bit of code should also get removed.

**Comment by nickvergessen** [comment]
No, if normal array is not working, we need to fix it, not remove it.

**Comment by oparoz** [comment]
We can't, I've edited my previous comment, but because of Github's cache, you may not see it:

> By doesn't work, I mean it breaks ownCloud because, iirc, without the closure app routes are loaded before core is ready.

**Comment by nickvergessen** [comment]
```php

$navigationEntry = function () use ($c) {
	return [
		'id' => $c->getAppName(),
		'order' => 1,
		'name' => $c->query('ActivityL10N')->t('Activity'),
		'href' => $c->query('URLGenerator')->linkToRoute('activity.Activities.showList'),
		'icon' => $c->query('URLGenerator')->imagePath('activity', 'activity.svg'),
	];
};
$c->getServer()->getNavigationManager()->add($navigationEntry);
$c->getServer()->getNavigationManager()->add($navigationEntry());
$c->getServer()->getNavigationManager()->add([
	'id' => $c->getAppName(),
	'order' => 1,
	'name' => $c->query('ActivityL10N')->t('Activity'),
	'href' => $c->query('URLGenerator')->linkToRoute('activity.Activities.showList'),
	'icon' => $c->query('URLGenerator')->imagePath('activity', 'activity.svg'),
]);
```

Just tested and it displayes all three just perfect.

**Comment by oparoz** [comment]
Well, I don't think @Xenopathic agrees: https://github.com/owncloud/gallery/issues/293

**Comment by oparoz** [comment]
And creating the routes work, but the provisioning API is then broken.

**Comment by nickvergessen** [comment]
Well, it works for old apps and that is what it is for.
See it as deprecated, but it still works and therefor must not be removed from the doc block and from the code.

**Comment by Xenopathic** [comment]
Hmm, the 'old' syntax should definitely still be supported. If an app route is used in app.php of that app, then the routes should get loaded regardless, if they don't then it's a bug. Obviously there are some race conditions that could arise with that so the closure should definitely be the recommended form.

**Comment by oparoz** [comment]
> Obviously there are some race conditions that could arise with that

OK, so more something for the documentation then, because otherwise devs will break core without knowing what they're doing wrong.
