### ISSUE TITLE
Memcached broken, invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by Xenopathic** [owncloud/core#18849]
I don't know if it worked before, but with the latest Memcached all unit tests fail. Some debugging reveals the problem is with `->getAllKeys()`, which returns FALSE now. I suspect Memcached changed some behaviour with the (undocumented) `stats cachedump` protocol command, which PHP uses when `->getAllKeys()` is called.

In summary, we can no longer clear the cache with Memcached, and trying to throws an error as we don't properly check the return from `->getAllKeys()`... I can't think of a sensible fallback to that, other than just calling `->flush()` and removing ALL keys, not just those for the ownCloud instance...

**Comment by LukasReschke** [comment]
Another cry for stash :speak_no_evil: - See also https://github.com/owncloud/core/issues/17397#issuecomment-134560407

cc @DeepDiver1975

**Comment by Xenopathic** [comment]
@LukasReschke Actually, I think this is a more fundamental problem. The PHP Memcached library always returns false for `getAllKeys()` on my setup, and Stash will encounter exactly the same problem. Hopefully it handles it properly, but maybe it just reports the error and does nothing...
