### ISSUE TITLE
Upgrade from 8.0.7 to 8.1.2 encryption problem

### ISSUE THREAD

**Issue by Micha-Btz** [owncloud/core#18841]
Hi there,

i tried to update my 8.0.7 to 8.1.2 with encryption enabled. 
As described, i turn on maintaince mode, the update itself, runs trough with the same problem 
like this https://github.com/owncloud/core/issues/18836 but after a second run it works.

After this i enabled the server side encryption and the owncloud default encryption module.

Then the guide says:

Return to your Admin page to see the ownCloud Default Encryption Module added to the module selector, and automatically selected. Now you must log out and then log back in to initialize your encryption keys.

But the modul selector is not shown in the admin page, can i check if the app is really enabled?
It is shown a enabled, in the app section, but even does not work.

The installation is on the hoster so i have no access to occ to start the encryption migration.

Any ideas?

log file
 https://gist.github.com/Micha-Btz/198999261e52f31f55c2

**Comment by karlitschek** [comment]
@schiesbn

**Comment by Micha-Btz** [comment]
I roll back to 8.0.7 an give the upgrade a new try, same problem as bevor. nothing new in log files.
clueless what should i do

**Comment by schiesbn** [comment]
Can you show a screenshot of the "Server-side encryption" section in your admin settings? Please also double-check that the "default encryption module" is listed in the "Enabled" section of your apps page.

**Comment by schiesbn** [comment]
This error message looks like something is wrong with the PHP installation.

````
Error PHP PHP Startup: Unable to load dynamic library '/usr/lib/php5/20121212/http.so' - /usr/lib/php5/20121212/http.so: cannot open shared object file: No such file or directory at Unknown#0 2015-09-05T07:38:11+00:00
````

I would suggest to contact your hoster and ask him about this particular error message.

**Comment by Micha-Btz** [comment]
will see, what the hoster says to this.
attached
![unbenannt](https://cloud.githubusercontent.com/assets/4420944/9731456/4f8620c8-561d-11e5-83a9-1406c218f3ed.png)
![unbenannt2](https://cloud.githubusercontent.com/assets/4420944/9731457/4f9317d8-561d-11e5-88c2-198457561c47.png)

 the pictures.

**Comment by schiesbn** [comment]
Can you post a complete list of all enabled apps? Do you have any external user backends enabled?

**Comment by Micha-Btz** [comment]
Default encryption module 1.0.0
Deleted files 0.6.3
PDF Viewer 0.7
Pictures 0.6.0
Share Files 0.6.2
Text Editor 0.4
Updater 0.6
User backend using remote HTTP servers 1.1.0.2
Versions 1.0.6
Video Viewer 0.1.3

all this apps are enabled by default after upgrade, except Default encryption

**Comment by schiesbn** [comment]
> User backend using remote HTTP servers 1.1.0.2

That's the "problem". We wanted that only people with small installations with really no shell access to use the "migrate keys" buttons to avoid people with large installations running into timeouts. But as you can imagine it is hard to distinguish between this two groups of user. As a easy way we just checked for the use of external user backends with the assumption small installations will most likely always use the internal user backend and large installation will probably always use something like LDAP.

An easy fix, just to get you to the button to migrate your keys is to modify two lines:

change this one https://github.com/owncloud/core/blob/v8.1.2/settings/templates/admin.php#L366
to
````
if ($_['encryptionReady'] === false) {
````

and this one https://github.com/owncloud/core/blob/v8.1.2/settings/templates/admin.php#L368
to
````
} elseif ($_['encryptionReady'] === false) {
````

(Basically remove the 'externalBackendsEnabled' check in both if statement)

If you make this changes and reload the admin page you should see a button to run the migration.

I will think about a better way to distinguish large and small installations for the future.

**Comment by Micha-Btz** [comment]
thanks, that solves that problem
