### ISSUE TITLE
Add @internal to phpdoc of /lib/private classes

### ISSUE THREAD

**Issue by Henni** [owncloud/core#18846]
Adding [@&#8203;internal](http://www.phpdoc.org/docs/latest/references/phpdoc/tags/internal.html) to phpdoc class blocks hides these classes in the php documentation.
This would allow to generate two different documentations. One for core developers and another for app developers.

Alternatively/Additionally the [@&#8203;api](http://www.phpdoc.org/docs/latest/references/phpdoc/tags/api.html) tag could be used to highlight /lib/public classes which may be used by apps.

**Comment by oparoz** [comment]
:+1: , but the documentation would also need to be automatically generated (maybe I've missed some recent development).

**Comment by Xenopathic** [comment]
Surely this is made redundant by our OC/OCP split? All classes in OCP are available for apps to use, while using any OC ones are at your own risk.

**Comment by Henni** [comment]
@Xenopathic  do you think this addition would still make sense to clarify it for newcomers?
