### ISSUE TITLE
Cardav authentication broken after upgrade to version 8.1.1

### ISSUE THREAD

**Issue by mschaaf** [owncloud/core#18853]
I use the following url for syncing contacts to my mobile phone:

https://<server>/owncloud/remote.php/carddav/addressbooks/<user name>/kontakte

Before my upgrade to version 8.1.1 this worked very well. After the upgrade it stopped working With the following error

```
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<s:sabredav-version>2.1.6</s:sabredav-version>
<s:exception>Sabre\DAVACL\Exception\NeedPrivileges</s:exception>
<s:message>
User did not have the required privileges ({DAV:}read) for path "addressbooks/<username>/kontakte"
</s:message>
<d:need-privileges>
<d:resource>
<d:href>
/owncloud/remote.php/carddav/addressbooks/<username>/kontakte
</d:href>
<d:privilege>
<d:read/>
</d:privilege>
</d:resource>
</d:need-privileges>
</d:error>
```

**Comment by RealRancor** [comment]
Hi,

might be related or a duplicate https://github.com/owncloud/contacts/issues/814

In general its recommended to report issues with apps in the apps bugtracker.

**Comment by mschaaf** [comment]
No, I don't have a LDAP backend.

**Comment by RealRancor** [comment]
Then close here and re-open in https://github.com/owncloud/contacts/issues by using the issue template as described here:

https://github.com/owncloud/contacts/blob/master/CONTRIBUTING.md#short-version

**Comment by mschaaf** [comment]
Re-opended in contacts app under https://github.com/owncloud/contacts/issues/1038
