### ISSUE TITLE
QNAP 4.2.0 and Owncloud

### ISSUE THREAD

**Issue by Eastcoastsounds** [owncloud/core#18859]
Sept 6 2015 Owncloud no longer works as the support for Optware IPKG has been removed - any known fixes please

**Comment by RealRancor** [comment]
Please fill out the issue template: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version

**Comment by Eastcoastsounds** [comment]
### Steps to reproduce
1. Update QNAP - new version does not support Optware IPKG
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead When attempting to log on I receive the following message

### Server configuration
**Operating system**: QNAP TS470-PRO version 4.2.0

**Web server:**

**Database:**

**PHP version:**Optware

**ownCloud version:** (see ownCloud admin page) 8.02 Client 2.0.1

**Updated from an older ownCloud or fresh install:** Updated

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system --public
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
On ownCloud 7+ with access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

On ownCloud 6 with access to your command line run e.g.:
sqlite3 data/owncloud.db or mysql -u root -p owncloud
then execute:  select * from oc_appconfig where appid='user_ldap';

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query above.

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:** Safari

**Operating system:** Mac OS 10.10.5

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here - when trying to connect
server replied: - Internal server error
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
