### ISSUE TITLE
External Storage Issue

### ISSUE THREAD

**Issue by braddanford** [owncloud/core#18854]
Hello all, 
I had just installed latest OC on a Ubuntu server. During the installation, I ticked LAMP and Samba server. All was running well, so I enabled external storage. I connected the external storage to a Windows 2008 R2 file server running on a domain. Most dirs function properly, but I did run into a couple issues that I couldn't resolve and cannot see to find the solution as of yet. 
1. On the CIFS folders, I cannot seem to download .EXE or.ZIP files. This is not every time, but is easy to recreate on the files that fail. If I compress to .7zip, the files do seem to download properly. 
An example of the issue is, if I create a share link to a .EXE or .ZIP, the file shows at either bytes or less than 1kb. If I click on link, it downloads a small file. If I compress to .7zip, it shows the proper size and in most cases downloads properly. Note: I am using an AD account that has modify permissions on all folders that are attached. 
I am a bit lost on this as some files work and some don't. I don't know if it is large file downloads causing the issue and if I need to adjust in Apache and PHP. I know I have downloaded a 350 MB +/- file from one folder and had the same size fail in another. Both folders have the same permissions. As a test, I used a Domain Admin account to connect the folders and found the same issue persisted.
2. I am having issues with desktop sync to CIFS. I get an error that the service is not available when I attempt to sync and the error is presented when the files are being pulled from OC.
And I will admit I may have missed something in the setup docs. But if not and this sounds familiar, I appreciate the help.

**Comment by Xenopathic** [comment]
Please fill out the issue template

**Comment by PVince81** [comment]
Can ZIP and EXE be downloaded from non-CIFS folders ?

**Comment by PVince81** [comment]
@braddanford please use the issue template https://raw.githubusercontent.com/owncloud/core/master/issue_template.md and reopen
