### ISSUE TITLE
Version 8.1.2 is not available as Debian Package

### ISSUE THREAD

**Issue by DerZeitspringer** [owncloud/core#18860]
Dear maintainer,

the new version 8.1.2 is not available as Debian package (Debian 8.2 Jessie).
https://software.opensuse.org/download/package?project=isv:ownCloud:community&package=owncloud still lists version 8.1.1, also does the repository.

Best regards,
Martin

**Comment by tflidd** [comment]
ref: https://github.com/owncloud/core/issues/18750#issuecomment-136949158

**Comment by karlitschek** [comment]
The reason is that 8.1.2 is not released yet.

**Comment by DerZeitspringer** [comment]
Then there is a misunderstanding here, as https://owncloud.org/changelog/ lists a version 8.1.2 with a release date "September 1 2015"
![changelog _ owncloud org](https://cloud.githubusercontent.com/assets/10948258/9711252/7a032cbe-5542-11e5-8f35-f0a69a5b8bc6.png)

**Comment by DerZeitspringer** [comment]
sorry, haven't seen the comment by @tflidd 
OK, issue accepted :)
