### ISSUE TITLE
OC_App::loadApps is not working properly

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#18863]
In a bootstrap.php for testing, I get the following results:

* `OC_App::loadApps(['filesystem', 'logging', 'gallery']);` does **NOT** load gallery (not sure about the other ones)
* `OC_App::loadApp('gallery');` does load gallery
* `OC_App::loadApps();` does load gallery

That's on master from tonight.

**Comment by oparoz** [comment]
@Xenopathic @MorrisJobke @LukasReschke

**Comment by DeepDiver1975** [comment]
The array with load apps is not about app namens but app types.

**Comment by MorrisJobke** [comment]
> The array with load apps is not about app namens but app types.

Yep. we have something of this in core too, which is really bad.

**Comment by DeepDiver1975** [comment]
Bad? No
Suboptimal naming? Yes
Lack of proper phpdocs? To verify

**Comment by nickvergessen** [comment]
> Lack of proper phpdocs? To verify 

```php
	/**
	 * loads all apps
	 *
	 * @param array $types
	 * @return bool
	 *
	 * This function walks through the ownCloud directory and loads all apps
	 * it can find. A directory contains an app if the file /appinfo/info.xml
	 * exists.
	 *
	 * if $types is set, only apps of those types will be loaded
	 */
```

Lack of proper phpdocs? Yes
Lack of docs explaining it's not the app names? No

**Comment by DeepDiver1975** [comment]
THX. Case closed
