### ISSUE TITLE
CA bundle chaos

### ISSUE THREAD

**Issue by rahra** [owncloud/core#18862]
The ownCloud installation package currently (8.1.1) comes with 6 (!) CA bundles with different versions. It should use the system default CA bundle and probably a second configurable in owncloud/config. All other modules should access this one but should not ship with their own bundles. Configuring TLS properly is not easy at all but this makes it much more difficult to maintain.

Bundles in the package:
owncloud/config/ca-bundle.crt
owncloud/3rdparty/guzzle/http/Guzzle/Http/Resources/cacert.pem
owncloud/3rdparty/rackspace/php-opencloud/tests/OpenCloud/Tests/Common/cacert.pem
owncloud/apps/files_external/3rdparty/google-api-php-client/src/Google/IO/cacerts.pem
owncloud/apps/files_external/3rdparty/Dropbox/OAuth/ca-bundle.pem
owncloud/apps/files_external/3rdparty/aws-sdk-php/Guzzle/Http/Resources/cacert.pem

**Comment by karlitschek** [comment]
@LukasReschke What do you think?
Partly unrelated. I think we should move the ca-bundle from the config directory to a place in /core. 
This is not really configuration but part of our release. And we saw reports that the installation breaks if people keep the config folder unchanged during upgrades which is recommended in our documentation.
What do you think?

**Comment by rahra** [comment]
Yes, that's probably a better solution. But still, ownCloud shall use the system's ca-bundle and the one in core/ (config/) just as a backup. Since it depends on curl und openssl, the system should already have a ca-bundle.

**Comment by LukasReschke** [comment]
> Partly unrelated. I think we should move the ca-bundle from the config directory to a place in /core. 
This is not really configuration but part of our release. And we saw reports that the installation breaks if people keep the config folder unchanged during upgrades which is recommended in our documentation.

8.1.2 will show a warning in this case, for 8.2 we can change this as others meanwhile also use `config`.

> Yes, that's probably a better solution. But still, ownCloud shall use the system's ca-bundle and the one in core/ (config/) just as a backup. Since it depends on curl und openssl, the system should already have a ca-bundle.

Sorry. That's not possible. ownCloud allows you to import custom root certificates which means that we need to ship a defined root certificate bundle and merge them together. Yes, I do dislike the feature as well but I didn't add it ;-)

cc @schiesbn
