### ISSUE TITLE
XSendfile is missing function implementation

### ISSUE THREAD

**Issue by mirekys** [owncloud/core#18869]
### Steps to reproduce
1. Download folder from website as a ZIP with XSendfile mod enabled.

### Expected behaviour
Zip file should be created and downloaded.

### Actual behaviour
Blank page and 'Call to undefined method' PHP error

### Server configuration
**Operating system**: RHEL 6.6

**Web server:** Apache/2.2.15

**Database:** PostgreSQL 9.4.1
**PHP version:** PHP 5.4.37

**ownCloud version:** 6.0.9

**Updated from an older ownCloud:** yes

**List of activated apps:** 
 - calendar
 - contacts
 - documents
 - files
 - files_pdfviewer
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - firstrunwizard
 - gallery
 - mail_notifications
 - user_saml

**Are you using encryption:** no

#### Web server error log
[Mon Sep 07 10:15:31 2015] [notice] Apache/2.2.15 (Unix) mod_ssl/2.2.15 OpenSSL/1.0.1e-fips PHP/5.4.37 configured -- resuming normal operations
[Mon Sep 07 10:15:38 2015] [error] [client X.X.X.X] PHP Fatal error:  Call to undefined method OC_Helper::moveToNoClean() in /ocroot/lib/private/files.php on line 104, referer: https://blahblah/index.php/apps/files

#### ownCloud log (data/owncloud.log)
nothing here

#### Browser log
just HTTP 500

I've tracked down that **OC_Helper::moveToNoClean()** is missing since the 6.0.7 release. But the caller function in **files.php** still uses it here: https://github.com/owncloud/core/blob/v6.0.9/lib/private/files.php#L79-L81 and here: https://github.com/owncloud/core/blob/v6.0.9/lib/private/files.php#L103-L105.

**Comment by MorrisJobke** [comment]
cc @icewind1991 @Xenopathic

**Comment by Xenopathic** [comment]
XSendfile will no longer be supported in 8.2, since it conflicts with file locking

**Comment by Xenopathic** [comment]
Also, the `moveToNoClean()` issue was fixed in 7.0.0.

**Comment by LukasReschke** [comment]
ownCloud 6 is also EoL.
