### ISSUE TITLE
Add missing tests for #18632

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#18875]
https://github.com/owncloud/core/pull/18632 has touched the preview class, adding a new public method.
It was merged despite the lack of test, so I'm tracking this here to make sure they go in.

**Comment by DeepDiver1975** [comment]
@icewind1991 any ETA on these test? would be nice ... thx

**Comment by cmonteroluque** [comment]
This issue will fall off 8.2 if not resolved by 6 Oct

**Comment by icewind1991** [comment]
#19373 added tests for the changes to the preview class
