### ISSUE TITLE
User management not accessible anymore

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#18871]
```
Autoload path not allowed: /home/nickv/ownCloud/master/core/apps/user_ldap/group_ldap.php
File: /home/nickv/ownCloud/master/core/lib/autoloader.php
```

@Xenopathic 

4th regression from the "restrict autoloading path"

This has to stop! 

@DeepDiver1975 @karlitschek

**Comment by nickvergessen** [comment]
@cmonteroluque

**Comment by MorrisJobke** [comment]
> 4th regression from the "restrict autoloading path"

Okay. We should revert it simply.

**Comment by Xenopathic** [comment]
> 4th regression from the "restrict autoloading path"

*First* regression from "Restrict autoloading path". 3rd regression involving autoloader improvements, but not just that PR
