### ISSUE TITLE
8.2 remove xsendfile support

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#18870]
To ensure proper locking support we have to drop xsendfile support.

**Comment by karlitschek** [comment]
Agreed. Unfortunately. So we have to remove the config options and add it to the release notes and documentation. Who can help with that?
@carlaschroder @DeepDiver1975 ?

**Comment by LukasReschke** [comment]
Killing code? - Easy task.

https://github.com/owncloud/core/pull/18881
https://github.com/owncloud/documentation/pull/1648

**Comment by LukasReschke** [comment]
Still requires release notes though :speak_no_evil:

**Comment by RealRancor** [comment]
...and proper testing if a still configured XSendFile is then breaking the whole instance as no one cares about release notes :speak_no_evil:

**Comment by LukasReschke** [comment]
There never was a configuration switch. XSendFile was automatically enabled if the modules were available :-)

**Comment by RealRancor** [comment]
This probably also just solves https://github.com/owncloud/core/issues/15091 and https://github.com/owncloud/core/issues/16997?

> XSendFile was automatically enabled if the modules were available :-)

Ah, yes. Thanks for the info.

**Comment by LukasReschke** [comment]
Correct. Thanks :smile:

**Comment by carlaschroder** [comment]
Geez, you lot keep making work for me.

**Comment by rfnx** [comment]
Hello !

I don't know if this is the right place to ask, but I really like X-Accel support because of start/stop downloads and very light load on the server (no php involved).
Will it be replaced by a php library or something that allows users to at least start/stop downloads?

**Comment by DeepDiver1975** [comment]
> Will it be replaced by a php library or something that allows users to at least start/stop downloads?

I'm not aware of any solution which would fit into this. no

**Comment by rfnx** [comment]
Of course this exist, I remember using it in another project, one or 2 years ago. Basically, php can just read the header that indicate the range and start downloads at the right position, it is very easy.

But I heard somewhere that oC will soon use webdav even for files app, will it solve the issue and give us the ability to start and pause again ?

**Comment by DeepDiver1975** [comment]
> Of course this exist, I remember using it in another project, one or 2 years ago. Basically, php can just read the header that indicate the range and start downloads at the right position, it is very easy.

Pull requests are very much welcome :speak_no_evil:

**Comment by rfnx** [comment]
I can help :) but first I need to know if my second point (about webdav for files app) is right because it can also solve the issue, thus no need to use another solution like a php library for that.

**Comment by MorrisJobke** [comment]
> I can help :) but first I need to know if my second point (about webdav for files app) is right because it can also solve the issue, thus no need to use another solution like a php library for that.

Yes. There are plans to move the files app to webdav: #16902 or as alternative #17668 - both are planned for the next major version (9.0)
