### ISSUE TITLE
Ugly spinner on sidebar

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#18878]
If you open the sidebar for the first time on a new file ownCloud needs to create a new preview. During this process we show a spinner which looks quite blurred, probably because we scale it up to the size of the preview.

Can we improve this somehow?

![1](https://cloud.githubusercontent.com/assets/1589737/9718554/2d989b94-557d-11e5-9c20-a9278d1a6cd8.png)

cc @jancborchardt @PVince81

**Comment by jancborchardt** [comment]
Yes, it should only be the standard size of .icon-loading. Not a giant version of it. @georgehrke @Blizzz @schiesbn someone of you has got to do it, I have no idea how to.

**Comment by georgehrke** [comment]
@jancborchardt Wouldn't it be the easiest solution to add `background-size: ... !important` to `.icon-loading` so it doesn't happen in other areas either?

**Comment by karlitschek** [comment]
@georgehrke Well if it works ;-)
Can yo help with that?

**Comment by georgehrke** [comment]
Sure, I can check tomorrow

**Comment by jancborchardt** [comment]
@georgehrke hm, make sure this doesn’t break anything, and only apply it for the `.icon-loading` please.

**Comment by georgehrke** [comment]
> hm

Sounds a bit skeptical, we can for sure take a different approach, this was just a suggestion and I was seeking your opinion ;)

**Comment by karlitschek** [comment]
@georgehrke What do you suggest? Can we fix this until Monday?

**Comment by georgehrke** [comment]
Yes, will look into it when I'm back home in like 2 hours.
