### ISSUE TITLE
Update from 7.0.8 to 7.0.9 fails

### ISSUE THREAD

**Issue by qswroot** [owncloud/core#18877]
### Steps to reproduce
1. Download OC 7.0.9 and install in second webroot 
2. Activate new site with a2ensite
3. open OC startpage and run upgrade script / run upgrade script from commandline

### Expected behaviour
Upgrade is running

### Actual behaviour
Maintenance mode is switched on and nothing happens. When upgrade is done via command line, error message "PHP Fatal error: Using $this when not in object context in [...]/owncloud709/lib/private/updater.php on line 256" appears.

### Server configuration
**Operating system**: Ubuntu 12.04

**Web server:** Apache 2.2

**Database:** MySQL 5

**PHP version:** 5.3

**ownCloud version:** (see ownCloud admin page) 7.0.8/7.0.9

**Updated from an older ownCloud or fresh install:** update from 7.0.8

**List of activated apps:**
Enabled:
 - files
 - files_antivirus
 - files_mv
 - files_share_watcher
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - gallery
 - search_lucene
 - templateeditor
 - updater
 - user_ldap
Disabled:
 - activity
 - bookmarks
 - calendar
 - contacts
 - documents
 - external
 - files_encryption
 - files_external
 - files_pdfviewer
 - files_videoviewer
 - firstrunwizard
 - user_external
 - user_webdavauth

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
{"app":"PHP","message":"Using $this when not in object context at \/var\/www\/owncloud709\/lib\/private\/updater.php#256","level":3,"time":"September 07, 2015 13:46:29"}

**Comment by LukasReschke** [comment]
Seems to be introduced with https://github.com/owncloud/core/commit/2ce22eeefbac5eb3355298f8ad3c9ff5c3303fd4 by @MorrisJobke. Potential regression.

**Comment by LukasReschke** [comment]
Yes. Showstopper. Completely broken on 5.3 - we need to repackage :speak_no_evil: 
![2015-09-08_10-54-53](https://cloud.githubusercontent.com/assets/878997/9730632/0aecdbb4-5618-11e5-8217-6505dc7ed645.png)

And we also really need to have Jenkins back :speak_no_evil: 

cc @karlitschek @cmonteroluque @DeepDiver1975

**Comment by LukasReschke** [comment]
See also http://php.net/manual/en/functions.anonymous.php:

> Version	Description
> 5.4.0	$this can be used in anonymous functions.

**Comment by LukasReschke** [comment]
Potential patch is at https://github.com/owncloud/core/pull/18889.

@qswroot Mind testing?

**Comment by LukasReschke** [comment]
Patched with https://github.com/owncloud/core/pull/18898
