### ISSUE TITLE
"New" Button doesn't work on small screens

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#18879]
I just discovered the the new "New" Button doesn't work on small screens:

Steps to reproduce:

1. Reduce the size of your browser window until the sidebar at the left gets closed.
2. Click on the "New" button to create a new folder/file

Expected Result:

Dropdown opens and let you create a new file/folder

Actual Result:

Nothing happens

cc @PVince81

**Comment by davitol** [comment]
Tested with Safari in iPhone 6 Plus and it does not work too. Maybe is the same origin problem

**Comment by schiesbn** [comment]
@davitol yes, I think it fails as soon as the left sidebar is minimized.

**Comment by PVince81** [comment]
Did the old menu work ? Regression ?

**Comment by PVince81** [comment]
CC @jancborchardt

**Comment by jancborchardt** [comment]
Fix at https://github.com/owncloud/core/pull/19066

**Comment by davitol** [comment]
Tested in iPhone 6 Plus and it works. Great job

**Comment by jancborchardt** [comment]
@davitol comment is only necessary on pull request. ;)
