### ISSUE TITLE
OC doesn't propose update for app news

### ISSUE THREAD

**Issue by awikatchikaen** [owncloud/core#18884]
Hi,
 like i said on this issue : https://github.com/owncloud/news/issues/851
Owncloud 8.1.1 with php 5.6 doesn't propose to update the news app. I'm still on 5.2.8

Thank you

**Comment by RealRancor** [comment]
Please fill out the issue template.

**Comment by awikatchikaen** [comment]
### Steps to reproduce
1. log as admin
2. go to apps management
3.

### Expected behaviour
OC should propose to update app news to 6.0.3

### Actual behaviour
Nothing

### Server configuration
**Operating system**:

**Web server:**
apache
**Database:**
sqlite
**PHP version:**
5.6
**ownCloud version:** (see ownCloud admin page)
8.1.1
**Updated from an older ownCloud or fresh install:**
updated
**List of activated apps:**
 - calendar: 0.7.2
 - contacts: 0.4.0.0
 - contactsplus: 1.0.7
 - external: 1.2
 - files: 1.1.10
 - files_external: 0.2.3
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_videoviewer: 0.1.3
 - gallery: 0.6.1
 - music: 0.3.5
 - news: 5.2.8
 - tasks: 0.6.0
 - updater: 0.6


**The content of config/config.php:**
$CONFIG = array (
  'instanceid' => '513866b4dcd2b',
  'passwordsalt' => '',
  'datadirectory' => '/opt/owncloud/data',
  'dbtype' => 'sqlite3',
  'version' => '8.1.1.3',
  'installed' => true,
  'forcessl' => true,
  'knowledgebaseenabled' => true,
  'knowledgebaseurl' => 'http://api.apps.owncloud.com/v1',
  'appstoreenabled' => true,
  'appstoreurl' => 'http://api.apps.owncloud.com/v1',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/opt/owncloud/apps',
      'url' => '/apps',
      'writable' => true,
    ),
  ),
  'maintenance' => false,
  'theme' => '',
  'loglevel' => '0',
  'defaultapp' => 'files',
  'trusted_domains' => 
  array (
    0 => '.***.fr',
    1 => '***..fr',
  ),
  'xframe_restriction' => false,
  'share_folder' => '/Shared',
  'appcodechecker' => false,
  'enable_avatars' => true,
  'mail_smtpmode' => 'smtp',
  'mail_domain' => '.fr',
  'mail_from_address' => '',
  'mail_smtpsecure' => 'tls',
  'mail_smtphost' => 'mail..net',
  'mail_smtpport' => '587',
  'mail_smtpauthtype' => 'PLAIN',
  'mail_smtpauth' => 1,
  'mail_smtpname' => '@.fr',
  'mail_smtppassword' => 't',
  'secret' => '',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration
**Browser:** firefox

**Operating system:** debian testing

### Logs
#### Web server error log
none afetr accessing admin page

#### ownCloud log (data/owncloud.log)
{"reqId":"ujKNfOCkpMvdqtlcG6N\/","remoteAddr":"192.168.1.72","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-09-07T20:35:44+00:00","method":"GET","url":"\/index.php\/settings\/apps"}
{"reqId":"Shy6UqV23Cgn\/3JThDJ3","remoteAddr":"192.168.1.72","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-09-07T20:35:45+00:00","method":"GET","url":"\/index.php\/core\/js\/oc.js?v=28cd50b2086de517f3d90ea094601623"}
{"reqId":"V40GAZ2IJ7acilqmIq2i","remoteAddr":"192.168.1.72","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-09-07T20:35:46+00:00","method":"GET","url":"\/index.php\/settings\/apps\/categories"}
{"reqId":"V40GAZ2IJ7acilqmIq2i","remoteAddr":"192.168.1.72","app":"core","message":"Could not get categories: SSL CA bundle not found: \/opt\/owncloud\/config\/ca-bundle.crt","level":3,"time":"2015-09-07T20:35:47+00:00","method":"GET","url":"\/index.php\/settings\/apps\/categories"}
{"reqId":"bsLI1l489uuSWCFSzkJQ","remoteAddr":"192.168.1.72","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-09-07T20:35:47+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=0"}
{"reqId":"bsLI1l489uuSWCFSzkJQ","remoteAddr":"192.168.1.72","app":"core","message":"Could not get application: SSL CA bundle not found: \/opt\/owncloud\/config\/ca-bundle.crt","level":3,"time":"2015-09-07T20:35:47+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=0"}
{"reqId":"bsLI1l489uuSWCFSzkJQ","remoteAddr":"192.168.1.72","app":"core","message":"Could not get application: SSL CA bundle not found: \/opt\/owncloud\/config\/ca-bundle.crt","level":3,"time":"2015-09-07T20:35:47+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=0"}
{"reqId":"bsLI1l489uuSWCFSzkJQ","remoteAddr":"192.168.1.72","app":"core","message":"Could not get application: SSL CA bundle not found: \/opt\/owncloud\/config\/ca-bundle.crt","level":3,"time":"2015-09-07T20:35:47+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=0"}
{"reqId":"bsLI1l489uuSWCFSzkJQ","remoteAddr":"192.168.1.72","app":"core","message":"Could not get application: SSL CA bundle not found: \/opt\/owncloud\/config\/ca-bundle.crt","level":3,"time":"2015-09-07T20:35:47+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=0"}
{"reqId":"bsLI1l489uuSWCFSzkJQ","remoteAddr":"192.168.1.72","app":"core","message":"Could not get application: SSL CA bundle not found: \/opt\/owncloud\/config\/ca-bundle.crt","level":3,"time":"2015-09-07T20:35:47+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=0"}
{"reqId":"graUU13jLVUnAI8xYmEN","remoteAddr":"192.168.1.72","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-09-07T20:35:47+00:00","method":"GET","url":"\/index.php\/avatar\/admin\/178.60464477539062?requesttoken=Qo4N%2FY9B8uMVPIHcWYD6CTK174Z0qR"}
{"reqId":"6sLiA53Em0QMb2ayyzxH","remoteAddr":"192.168.1.72","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-09-07T20:35:48+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"0zF43FpzfBkf3p4X4Bnl","remoteAddr":"46.218.53.170","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-09-07T20:35:48+00:00","method":"GET","url":"\/index.php\/apps\/news\/feeds"}
{"reqId":"6sLiA53Em0QMb2ayyzxH","remoteAddr":"192.168.1.72","app":"core","message":"Could not get application: SSL CA bundle not found: \/opt\/owncloud\/config\/ca-bundle.crt","level":3,"time":"2015-09-07T20:35:48+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"6sLiA53Em0QMb2ayyzxH","remoteAddr":"192.168.1.72","app":"core","message":"Could not get application: SSL CA bundle not found: \/opt\/owncloud\/config\/ca-bundle.crt","level":3,"time":"2015-09-07T20:35:48+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"6sLiA53Em0QMb2ayyzxH","remoteAddr":"192.168.1.72","app":"core","message":"Could not get application: SSL CA bundle not found: \/opt\/owncloud\/config\/ca-bundle.crt","level":3,"time":"2015-09-07T20:35:48+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"6sLiA53Em0QMb2ayyzxH","remoteAddr":"192.168.1.72","app":"core","message":"Could not get application: SSL CA bundle not found: \/opt\/owncloud\/config\/ca-bundle.crt","level":3,"time":"2015-09-07T20:35:48+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"6sLiA53Em0QMb2ayyzxH","remoteAddr":"192.168.1.72","app":"core","message":"Could not get application: SSL CA bundle not found: \/opt\/owncloud\/config\/ca-bundle.crt","level":3,"time":"2015-09-07T20:35:48+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"6sLiA53Em0QMb2ayyzxH","remoteAddr":"192.168.1.72","app":"core","message":"Could not get application: SSL CA bundle not found: \/opt\/owncloud\/config\/ca-bundle.crt","level":3,"time":"2015-09-07T20:35:48+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"6sLiA53Em0QMb2ayyzxH","remoteAddr":"192.168.1.72","app":"core","message":"Could not get application: SSL CA bundle not found: \/opt\/owncloud\/config\/ca-bundle.crt","level":3,"time":"2015-09-07T20:35:48+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"6sLiA53Em0QMb2ayyzxH","remoteAddr":"192.168.1.72","app":"core","message":"Could not get application: SSL CA bundle not found: \/opt\/owncloud\/config\/ca-bundle.crt","level":3,"time":"2015-09-07T20:35:48+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"6sLiA53Em0QMb2ayyzxH","remoteAddr":"192.168.1.72","app":"core","message":"Could not get application: SSL CA bundle not found: \/opt\/owncloud\/config\/ca-bundle.crt","level":3,"time":"2015-09-07T20:35:48+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"6sLiA53Em0QMb2ayyzxH","remoteAddr":"192.168.1.72","app":"core","message":"Could not get application: SSL CA bundle not found: \/opt\/owncloud\/config\/ca-bundle.crt","level":3,"time":"2015-09-07T20:35:48+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"6sLiA53Em0QMb2ayyzxH","remoteAddr":"192.168.1.72","app":"core","message":"Could not get application: SSL CA bundle not found: \/opt\/owncloud\/config\/ca-bundle.crt","level":3,"time":"2015-09-07T20:35:48+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"6sLiA53Em0QMb2ayyzxH","remoteAddr":"192.168.1.72","app":"core","message":"Could not get application: SSL CA bundle not found: \/opt\/owncloud\/config\/ca-bundle.crt","level":3,"time":"2015-09-07T20:35:48+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"6sLiA53Em0QMb2ayyzxH","remoteAddr":"192.168.1.72","app":"core","message":"Could not get application: SSL CA bundle not found: \/opt\/owncloud\/config\/ca-bundle.crt","level":3,"time":"2015-09-07T20:35:48+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"6sLiA53Em0QMb2ayyzxH","remoteAddr":"192.168.1.72","app":"core","message":"Could not get application: SSL CA bundle not found: \/opt\/owncloud\/config\/ca-bundle.crt","level":3,"time":"2015-09-07T20:35:48+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"6sLiA53Em0QMb2ayyzxH","remoteAddr":"192.168.1.72","app":"core","message":"Could not get application: SSL CA bundle not found: \/opt\/owncloud\/config\/ca-bundle.crt","level":3,"time":"2015-09-07T20:35:48+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"6sLiA53Em0QMb2ayyzxH","remoteAddr":"192.168.1.72","app":"core","message":"Could not get application: SSL CA bundle not found: \/opt\/owncloud\/config\/ca-bundle.crt","level":3,"time":"2015-09-07T20:35:48+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"6sLiA53Em0QMb2ayyzxH","remoteAddr":"192.168.1.72","app":"core","message":"Could not get application: SSL CA bundle not found: \/opt\/owncloud\/config\/ca-bundle.crt","level":3,"time":"2015-09-07T20:35:48+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"6sLiA53Em0QMb2ayyzxH","remoteAddr":"192.168.1.72","app":"core","message":"Could not get application: SSL CA bundle not found: \/opt\/owncloud\/config\/ca-bundle.crt","level":3,"time":"2015-09-07T20:35:48+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"s+6XyYbviGDl3EepFJT+","remoteAddr":"46.218.53.170","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-09-07T20:35:49+00:00","method":"GET","url":"\/index.php\/apps\/news\/folders"}

**Comment by RealRancor** [comment]
Hi,

please remove those entries from your config.php:

'''
'forcessl' => true,
'knowledgebaseenabled' => true,
'knowledgebaseurl' => 'http://api.apps.owncloud.com/v1',
'appstoreenabled' => true,
'appstoreurl' => 'http://api.apps.owncloud.com/v1',
'apps_paths' =>
array (
0 =>
array (
'path' => '/opt/owncloud/apps',
'url' => '/apps',
'writable' => true,
),
),
'''

and copy over the https://github.com/owncloud/core/blob/v8.1.1/config/ca-bundle.crt into your /config folder.

**Comment by awikatchikaen** [comment]
I've done it. but still no update proposed. Now I have an error : 

{"reqId":"aOwSRm00LJHuVxCs25m5","remoteAddr":"192.168.1.72","app":"core","message":"Could not get application: cURL error 77: error setting certificate verify locations:\n  $

**Comment by RealRancor** [comment]
Check http://curl.haxx.se/libcurl/c/libcurl-errors.html and your favorite search engine for the error:

cURL error 77: error setting certificate verify locations:

**Comment by awikatchikaen** [comment]
I have this erro more precise : 
Could not get application: cURL error 77: error setting certificate verify locations: CAfile: /opt/owncloud/config/ca-bundle.crt CApath: /etc/ssl/certs

I don't inderstant why it look in "/etc/ssl/certs" and why the CAfile isn't only ca-bundle.crt. Is this configured somewhere ?

**Comment by RealRancor** [comment]
> CURLE_SSL_CACERT_BADFILE (77)
> 
> Problem with reading the SSL CA cert (path? access rights?) 

from the link above. Try to fix the read permissions to this file. Overall i don't think that this is an issue with ownCloud so you might want to continue either at the forums or the users mailinglist.

**Comment by awikatchikaen** [comment]
I have already resolve the permissions.

**Comment by RealRancor** [comment]
So you don't get this error anymore?

**Comment by awikatchikaen** [comment]
I have always this error, i had correct the permissions on the file after downloading it

**Comment by RealRancor** [comment]
Then please use your favorite search engine like suggested above to find some infos how to fix such an error at your setup/environment.

**Comment by awikatchikaen** [comment]
Well, it seems to me owncloud don't specify good files to libcurl...

**Comment by awikatchikaen** [comment]
Ok, my fault, i've done a "wget" on the link you gave me.
Good one was : https://raw.githubusercontent.com/owncloud/core/v8.1.1/config/ca-bundle.crt

Thank you

**Comment by RealRancor** [comment]
@awikatchikaen Feel free to close here.

**Comment by awikatchikaen** [comment]
don't know how to do it ...
