### ISSUE TITLE
can't update daily to daily, version number broken?

### ISSUE THREAD

**Issue by jospoortvliet** [owncloud/core#18880]
Sooh, I can't upgrade the daily snapshot to a newer daily snapshot - version of that seems '100.0.0.0' or something. I can upgrade to 'stable' (which is newer than my snapshot, indeed) but then I'm stuck. Beta is also on 100.0.0.0...

![upgrade](https://cloud.githubusercontent.com/assets/551757/9718906/f3a6fcfc-557f-11e5-88e7-1c20d7081656.gif)

The video shows it all, at a very low resolution to save you bandwidth ;-)

**Comment by karlitschek** [comment]
@VicDeo Any idea? Maybe I did something wrong with the versions of the daily builds?

**Comment by VicDeo** [comment]
@karlitschek yep..  there is a check that prevents from migration from 6 to 8 directly.
the same with migration from 8.1 to 100.0

**Comment by jospoortvliet** [comment]
Perhaps version 100.0 should be special-cased. Or, to allow updating to newer versions of the daily built we'll need the version number to increment from 100.0.000 to 100.0.001 and so on, every day... ?

Not sure who made the built scripts behind the daily packages. You, @VicDeo ?

**Comment by VicDeo** [comment]
@jospoortvliet not me. 
I can just skip this check for daily builds at all.

**Comment by karlitschek** [comment]
Maybe the best soltion is to skip the check for 100 aka. daily build. I hope the rest of the logic is correct

**Comment by jospoortvliet** [comment]
@VicDeo ah, that would be perfectly fine. Also be sure to always allow updating to a newer version (there is one once a day after all) because if the version in daily is always 100.0, the updater might decide you're on the latest version - always.

**Comment by MorrisJobke** [comment]
@VicDeo What is the status of this?

**Comment by VicDeo** [comment]
@MorrisJobke status is `haven't looked at` due to no milestone and severity

**Comment by VicDeo** [comment]
@jospoortvliet  please replcae your s updater with this one https://github.com/owncloud/updater/archive/fix-injection.zip

PR pending https://github.com/owncloud/updater/pull/179

**Comment by VicDeo** [comment]
By the way, daily is packed with bz2 and https://github.com/owncloud/core/pull/19182 assigned to 9,0

Which means that you won't be able to upgrade anyway

**Comment by VicDeo** [comment]
cc @karlitschek

**Comment by PVince81** [comment]
@VicDeo is this fixed by your PR ?

**Comment by PVince81** [comment]
@jospoortvliet are you still seeing this with the latest dailies ?

**Comment by VicDeo** [comment]
Current status:
I. all OC versions including master know nothing about bz2 extension which makes OC_Archive fail on extraction bz2
Solution: add bz2 to known mimetypes 
"bz2": ["application/x-bzip2"], to mimetypemapping.dist.json
II. 8.2.x and below need owncloud/core@a543d20 because bz2 support is broken for these versions.

**Comment by MorrisJobke** [comment]
> Solution: add bz2 to known mimetypes

Can you create a PR (and don't forget to increase the version number and add the repair step)

**Comment by PVince81** [comment]
Any update ?

**Comment by VicDeo** [comment]
@PVince81 this particular issue is not relevant to 9.x because new updater doesn't rely on OC_Archive any more.
OC_Archive fix  is pushed in https://github.com/owncloud/core/issues/22875

**Comment by VicDeo** [comment]
Can be closed since all channels ship `zip` packages now.
