### ISSUE TITLE
Empty folder is not upload.

### ISSUE THREAD

**Issue by IYOTTA** [owncloud/core#18892]
If i drag "Upload" Folder to upload. Only "Empty Folder" is not upload. 

Every file is important even that Folder is empty.

![cats](https://cloud.githubusercontent.com/assets/14050802/9731340/7dcf3c48-5646-11e5-90e8-0a0657218f9f.jpg)

**Comment by LukasReschke** [comment]
Please reopen at https://github.com/owncloud/client using the issue template https://github.com/owncloud/client/blob/master/CONTRIBUTING.md
