### ISSUE TITLE
Versions tab in sidebar shouldn’t show for folders

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#18899]
* [x] Versions tab should be rightmost tab: https://github.com/owncloud/core/pull/19404
* [x] Show feedback like »There are no previous versions of this file«
* [ ] There are no Versions for folders … so the tab should not be shown for folders https://github.com/owncloud/core/pull/19409
* [x] Where is the »Versions« action in the menu? Do we cut it in favor of only showing it in the sidebar?

@blizzz @PVince81 @owncloud/designers

**Comment by PVince81** [comment]
> Where is the »Versions« action in the menu? Do we cut it in favor of only showing it in the sidebar?

Yes, I removed it. I think having the versions in the sidebar is enough (unlike sharing)

**Comment by PVince81** [comment]
@jancborchardt you can change the feedback message yourself in the template. It appears only for files.
For folders the tab is empty, I'll look into hiding in for folders.

**Comment by jancborchardt** [comment]
@PVince81 cool, thanks! Only thing left is to not show the tab for folders. :)

**Comment by PVince81** [comment]
@jancborchardt how did you manage to make the Versions tab the rightmost ? Luck ? :wink:

**Comment by jancborchardt** [comment]
@PVince81 strange – could have sworn it was fixed … must have been confusion cause it’s still the same. ;)

**Comment by PVince81** [comment]
The order can be random, depending in which order the apps initialize themselves

**Comment by jancborchardt** [comment]
@PVince81 that is, in https://github.com/owncloud/core/pull/18185 (share menu in sidebar) it’s fixed. : )

**Comment by MorrisJobke** [comment]
> @PVince81 that is, in #18185 (share menu in sidebar) it’s fixed. : )

Versions is still available for folders.

**Comment by PVince81** [comment]
I didn't fix it yet

**Comment by PVince81** [comment]
Hiding tabs isn't trivial. The implementation and interface of TabView need to be adapted and the lazy-loading system needs to be implemented differently.

**Comment by jancborchardt** [comment]
Can we not hack it by adding a class somewhere that it’s a folder and simply display:none it via CSS?

Cause showing versions for folders is just not correct, and saying »No versions for this« every time will be ridiculous cause people will be under the false impression there _are_ versions for folders.

**Comment by PVince81** [comment]
Yeah, I'll try and hack it somehow. Also to keep in mind: if the versions tab was the selected one, it should automatically select another tab in case it gets hidden.

**Comment by PVince81** [comment]
Tab order fix: https://github.com/owncloud/core/pull/19404
Visibility fix not included.

**Comment by PVince81** [comment]
Visibility fix is here: https://github.com/owncloud/core/pull/19409

I had to use a different approach, but still better than the proposed CSS hack.
