### ISSUE TITLE
"New" button appears multiple times when switching categories

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#18894]
On current master.

1. Go to file view 
2. Click "Shared with others"
3. Click "All files"

![2015-09-08_12-52-36](https://cloud.githubusercontent.com/assets/878997/9733016/855f1e2e-5628-11e5-81d9-3535be0dc342.png)

cc @PVince81

**Comment by davitol** [comment]
It also happens with Share by link and Windows Network Drive (enterprise version)

**Comment by LukasReschke** [comment]
Closed in favour of https://github.com/owncloud/core/issues/19020
