### ISSUE TITLE
using apps per user leads to redirect loop

### ISSUE THREAD

**Issue by menedas** [owncloud/core#18890]
Hello, when I set up to use apps per user, ownCloud goes into a redirect loop when trying to login again.

### Steps to reproduce
1. Go to apps.
2. Search for App able to "Enable only for specific groups"
3. enable it and select any group
4. Log off and in again

### Expected behaviour
show the login page

### Actual behaviour
redirect loop

### Server configuration
**Operating system**: openSUSE 13.1

**Web server:**

**Database:** sqlite3

**PHP version:** 5.4.20

**ownCloud version:** 8.1.2.1

**Updated from an older ownCloud or fresh install:** Updated in a row from 6 to 7 to 8.

**List of activated apps:**
Enabled:
 - activity: 2.0.2
 - bookmarks: 0.4
 - contacts: 0.4.0.0
 - delete_confirmation: 1.0.1
 - direct_menu: 0.3
 - documents: 0.10.2
 - external: 1.2
 - files: 1.1.10
 - files_external: 0.2.3
 - files_locking:
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - ocusagecharts: 3.4.5
 - pinit: 1.0.1
 - search_lucene: 0.6.0
 - storagecharts2: 2.6.1
 - updater: 0.6
Disabled:
 - encryption
 - files_videoviewer
 - firstrunwizard
 - gallery
 - provisioning_api
 - templateeditor
 - user_external
 - user_ldap
 - user_webdavauth

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => 'REMOVED',
  'datadirectory' => '/home/REMOVED/owncloud-data',
  'dbtype' => 'sqlite3',
  'version' => '8.1.2.1',
  'installed' => true,
  'forcessl' => false,
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' =>
  array (
    0 => 'REMOVED',
    1 => 'REMOVED',
  ),
  'loglevel' => '1',
  'appstore.experimental.enabled' => true,
);

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Comment by Xenopathic** [comment]
Can you please fill out the issue template? Thanks

**Comment by menedas** [comment]
Auto template for new posts would be more user friendly, IMO.

**Comment by Xenopathic** [comment]
And logs?

**Comment by menedas** [comment]
Log is empty.

**Comment by Xenopathic** [comment]
> {"reqId":"CcWtLo9pbcSwWQH+E2l0","remoteAddr":"141.70.118.71","app":"PHP","message":"Array to string conversion at \/u\/www\/REMOVED\/htdocs\/owncloud\/lib\/pri$

Can you please show the full line of this particular log entry?

Also, there are known bugs with those two apps, you may want to consider disabling them and trying with different apps, for example the official bundled apps.

**Comment by menedas** [comment]
I have only removed the user name in that line.

Whats the name of a bundled storage charts app? I could not find any.

**Comment by Xenopathic** [comment]
Your log entries are cut off at the end, you were probably using nano to read the log file and the lines run off the edge. The interesting data is further along.

**Comment by menedas** [comment]
Sorry, didn't recognized it. I've created a new log:
{"reqId":"RxLTWHrj9RZJVmB33e6k","remoteAddr":"REMOVED-IP","app":"core","message":"No update found at the ownCloud appstore for app 166051","level":1,"time":"2015-09-08T10:49:01+00:00"}
{"reqId":"RxLTWHrj9RZJVmB33e6k","remoteAddr":"REMOVED-IP","app":"core","message":"No update found at the ownCloud appstore for app 166049","level":1,"time":"2015-09-08T10:49:01+00:00"}
{"reqId":"RxLTWHrj9RZJVmB33e6k","remoteAddr":"REMOVED-IP","app":"core","message":"No update found at the ownCloud appstore for app 166046","level":1,"time":"2015-09-08T10:49:01+00:00"}
{"reqId":"RxLTWHrj9RZJVmB33e6k","remoteAddr":"REMOVED-IP","app":"core","message":"No update found at the ownCloud appstore for app 166048","level":1,"time":"2015-09-08T10:49:01+00:00"}

But thats only showing after disable the group feature. Its not during activation and not during redirect loop.

Can you please remove the IP from your quoted line? Thank you.

**Comment by emtie** [comment]
Had the same issue, but could not find anything in the log. After modifying the oc_appconfig table to disable the per group permission owncloud worked like charme again.

cu emtie

**Comment by bruennlein** [comment]
Same for me. Solution from emtie worked for me. Deleted **all** per-user settings for apps from **oc_appconfig** (replaced config value ["NameOfMyUserGroup"]) with **no**. Now I can log-in.

**Comment by menedas** [comment]
Delete or rename the app in the app folder makes oc also accessible again. Reconfigure the app in oc and rename the folder back.

**Comment by luxifr** [comment]
just want to confirm that as well

OC 8.1.3, fresh install...

**Comment by cdamken** [comment]
have you try to disable the apps:
e.g: sudo -u www-data php occ app:disable (app name)

**Comment by luxifr** [comment]
Yes, it solves the redirect issue. Also removing the group limitation
directly in the db works. I just wanted to give confirmation to this bug.
Am 24.09.2015 21:57 schrieb "Carlos Damken" <notifications@github.com>:

**Comment by PVince81** [comment]
Is this still happening in 8.1.5, 8.2.2 or 9.0 RC1 ?

**Comment by PVince81** [comment]
Closing due to lack of feedback, also this is quite an old entry.
If the problem persists with recent versions like 8.2.8, 9.0.5, 9.1.1, please reopen.
