### ISSUE TITLE
[.deb-packages] to many dependencies in ownCloud-server.deb

### ISSUE THREAD

**Issue by stonerl** [owncloud/core#18902]
I just tried to do a minimal ownCloud installation, but the problem is that all owncloud-app* packages are a dependency of the owncloud-server.deb package. As far as I understand the packaging the owncloud. deb-package should be the "full-installation" package and the owncloud-server.deb the "minimal-installation". But, since all owncloud-app* packages are not a dependency of owncloud.deb, one cannot remove unneeded apps. It should look like this instead:

```
Package: owncloud
Architecture: all
Depends: ${misc:Depends}, owncloud-server (= ${binary:Version}), owncloud-config-apache (= ${binary:Version}),
	owncloud-app-activity          (= ${binary:Version}),
	owncloud-app-files             (= ${binary:Version}),
	owncloud-app-files-pdfviewer   (= ${binary:Version}),
	owncloud-app-files-trashbin    (= ${binary:Version}),
	owncloud-app-files-external    (= ${binary:Version}),
	owncloud-app-files-sharing     (= ${binary:Version}),
	owncloud-app-files-versions    (= ${binary:Version}),
	owncloud-app-files-locking     (= ${binary:Version}),
	owncloud-app-files-texteditor  (= ${binary:Version}),
	owncloud-app-provisioning-api  (= ${binary:Version}),
	owncloud-app-firstrunwizard    (= ${binary:Version}),
	owncloud-app-templateeditor    (= ${binary:Version}),
	owncloud-app-user-ldap         (= ${binary:Version}),
	owncloud-app-external          (= ${binary:Version}),
	owncloud-app-files-videoviewer (= ${binary:Version}),
	owncloud-app-gallery           (= ${binary:Version}),
	owncloud-app-user-webdavauth   (= ${binary:Version}),
	owncloud-app-user-external     (= ${binary:Version}),
	owncloud-app-encryption	       (= ${binary:Version})
## Do not do Depends: owncloud-app-updater
Replaces: owncloud (<< 7.9.9), 
	owncloud-app-updater (<< ${binary:Version}),
	owncloud-app-files-encryption (<< ${binary:Version})
Breaks:   owncloud (<< 7.9.9), 
	owncloud-app-updater (<< ${binary:Version}),
	owncloud-app-files-encryption (<< ${binary:Version})
Recommends: mysql-server | mariadb-server, curl, exim4 | mail-transport-agent
Suggests: clamav | clamav-daemon, smbclient, libreoffice-writer
Provides: owncloud
Description: The ownCloud Server - Private file sync and share server
 ownCloud Server provides you a private file sync and share
 cloud. Host this server to easily sync business or private documents
 across all your devices, and share those documents with other users of
 your ownCloud server on their devices.
 .
 ownCloud - Your Cloud, Your Data, Your Way!  www.owncloud.org

Package: owncloud-server
Architecture: all
Depends: ${misc:Depends}, php5 (>= 5.4.0), php5-mysqlnd | php5-mysql, php5-sqlite, php5-pgsql, 
	php5-common, php5-gd, php-xml-parser, php5-intl, php5-mcrypt, php5-curl, php5-json, php5-cli,
	owncloud-3rdparty              (= ${binary:Version})
# Caution: Provides: cannot satisfy versioned Depends, according to https://www.debian.org/doc/debian-policy/ch-relationships.html
Provides: owncloud-server-core
# Don't recommend php5-apcu for Ubuntu-14.04 https://github.com/owncloud/core/issues/14188
# Don't use apcu before 4.0.6 https://github.com/owncloud/core/issues/14175
Suggests: php5-apcu (>= 4.0.6) | php-apc
Description: The owncloud-server package
 .
 Server internals. For a complete system install package owncloud.
```

**Comment by karlitschek** [comment]
@jnweiger  can you have a look?

**Comment by stonerl** [comment]
just saw that there is another issue about the same problem #17595

**Comment by jnweiger** [comment]
the distinction between a minimal and a full installation never really worked. A sane minimal install is surprisingly difficult to maintain, as no tests are made with this configuration. All test cases assume that the standard apps are *all* present. 

Your suggestion would e.g. suffer from not having a files app in the minimal configuration. Such a server is unusable.

Starting with 8.1.2 we will merge back the apps into the server package, so that there is only one type of installation which is identical to the tar ball installation.

As this asks for a minimal install that is less than what a tar ball installation would bring, I am afraid this is a non-supported configuration. I'll have to close this as wontfix. sorry.

**Comment by stonerl** [comment]
That is perfectly fine for me. I just was confused because there were so many different packages and my assumption was that this would be intentional to have such different installation types, but only with the dependencies in the wrong package.

So does this mean that there will be only 4 packages left then?
owncloud
owncloud-server
owncloud-3rdparty
owncloud-config-apache

**Comment by jnweiger** [comment]
owncloud-3rdparty also merges into owncloud-server. What remains is

owncloud, owncloud-server, owncloud-config-apache.

You can review the current setup in https://software.opensuse.org/download.html?project=isv%3AownCloud%3Acommunity%3A8.1%3Atesting%3Amerged&package=owncloud
