### ISSUE TITLE
Class OC_FileProxy not found

### ISSUE THREAD

**Issue by amenk** [owncloud/core#18906]
My update from 7.0.0 to ownCloud 8.1.1 (stable) was interrupted, I was left with the maintenance page.
When I tried the update using `occ` I had to disable files_sharing. After enabling it, it dose not f ind the OC_FileProxy class anymore. What is going on?

	$ php occ app:enable files_sharing
        $ php occ
	PHP Fatal error:  Class 'OC_FileProxy' not found in /var/www/virtual/xxx/html/apps/files_sharing/appinfo/app.php on line 28

**Comment by RealRancor** [comment]
Hi,

have you done the steps in between like:

Your oC 7 version -> latest oC 7 -> latest oC 8.0 -> latest oC 8.1

**Comment by amenk** [comment]
Not sure. I just clicked update... it did not let me choose anything. How can I repair it? Do I have to make a fresh install?

**Comment by RealRancor** [comment]
Then you probably have done an unsupported upgrade from oC 7 to oC 8.1.

I think the best is to revert to your backup and first upgrade (manually) to oC 8.0.6 before going to oC 8.1.1.

**Comment by amenk** [comment]
I ended up doing a reinstall and copied the `config.php` - this seemed to work.
