### ISSUE TITLE
Login not possible in some browsers under OS X.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#18919]
### Steps to reproduce

Using firefox, opera o safari in OS X do:
1. Go to the login page.
2. Login as admin.

### Expected behaviour
You get logged in.

### Actual behaviour
You are not logged in and redirected to the login page again.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
master 
{"installed":true,"maintenance":false,"version":"8.2.0.4","versionstring":"8.2 pre alpha","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition..

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Firefox, Opera and Safari (Works fine in chrome)

**Firefox logs**
```
Content Security Policy: Page options have blocked loading of a resource in self (script-src http://HOST:52301 'unsafe-eval').
```

**Comment by karlitschek** [comment]
@LukasReschke What do you think?

**Comment by LukasReschke** [comment]
Works fine here. Please provide the actual URL you are using.

**Comment by LukasReschke** [comment]
Ok. After discussion with @SergioBertolinSG I can reproduce this, it seems to be caused by the fact that cookies are shared between different ports and our docker infrastructure uses the same domain *sigh*

**Comment by LukasReschke** [comment]
The docker infrastructure uses "daily" which has a way different code when it comes to session handling than current master. Let's retest this tomorrow thus :speak_no_evil:

**Comment by oparoz** [comment]
Same problem using "Chrome" on Windows and a recent master. This has been going on for a while.
No errors in the browser or owncloud.log.

No problems with Firefox.

I'm using several different version of oC in dub-domains.

Deleting the cookies manually doesn't help.

**Comment by SergioBertolinSG** [comment]
Same problem with today's daily (2015-09-10).

**Comment by SergioBertolinSG** [comment]
A mate has seen this problem in chrome using OS X as well.

**Comment by LukasReschke** [comment]
Nasty one. Please test https://github.com/owncloud/core/pull/19010.

**Comment by SergioBertolinSG** [comment]
Not working, I have the same problem today with master using firefox. (I am using the enterprise theme)

**Comment by LukasReschke** [comment]
@SergioBertolinSG Did you clean your cache and cookies. Also send me the host names and access data via mail. I highly doubt that this is the same issue.

**Comment by SergioBertolinSG** [comment]
Nevermind, cleaning cache and cookies was enough. :+1:

**Comment by SergioBertolinSG** [comment]
Issue is still alive in safari. Tested with Safari Version 7.0.6 (9537.78.2). Removed cache and cookies before test.

**Comment by SergioBertolinSG** [comment]
After upgrading to safari 7.1.8 it works fine, so I close this.
