### ISSUE TITLE
PDF preview not working in Google Chrome any longer

### ISSUE THREAD

**Issue by mbressman** [owncloud/core#18917]
Very strange - PDF preview doesn't seem to be working in Google Chrome any longer.  It works fine in IE 11, and previously worked in Google Chrome, but now clicking on a PDF in the ownCloud web interface just shows up blank white pages and doesn't actually display the contents of the PDF.  I've tested it on two other Chrome installs (so not just on my one PC) and same result.  

I'm running oC v8.1.1 and Chrome v45.0.2454.85 m

Any help is greatly appreciated!  Thanks.

(Hopefully this was the right place to post this issue since it seems to be part of the core install of oC)

P.S. For a shared ownCloud folder/file that is password protected, is there any built-in protection so that someone couldn't just brute-force the password (such as a time-out after a certain amount of incorrect password attempts, etc.)?  Just wondering...  Thanks!

**Comment by karlitschek** [comment]
@LukasReschke can you have a look please?

**Comment by LukasReschke** [comment]
> Very strange - PDF preview doesn't seem to be working in Google Chrome any longer. It works fine in IE 11, and previously worked in Google Chrome, but now clicking on a PDF in the ownCloud web interface just shows up blank white pages and doesn't actually display the contents of the PDF. I've tested it on two other Chrome installs (so not just on my one PC) and same result.

Send the PDF to lukas@owncloud.com and if you want a faster result you could also create me a non-administrative account on your instance so I can test it there on my own.

**Comment by mbressman** [comment]
Hi LukasReschke - thanks so much for the fast reply!  The issue isn't just happening to one or two PDF's in ownCloud v8.1.1 via Chrome v45, but every PDF.  So I don't have a particular one to send you.  Do you want me to create a non-administrative account so you can login and see?  How can I transmit such credentials to you so they are not posted publicly?  Thanks again!

**Comment by LukasReschke** [comment]
> Do you want me to create a non-administrative account so you can login and see? How can I transmit such credentials to you so they are not posted publicly? Thanks again!

Regular E-Mail to lukas@owncloud.com is enough  :-)

**Comment by mbressman** [comment]
Hey Lukas - Just wanted to touch base with you to see if you had received my email and had a chance to look at my ownCloud installation and see the issue.  

I had also mentioned in my email to you that I was incorrect in my initial post above about the issue - it’s not all PDF previews that aren’t working in Chrome – just some PDF files that don’t appear to preview at all.  In the user account I created for you on my ownCloud install I had uploaded two add'l PDF's (one which preview's correctly and one which doesn't for some reason).

Thanks again for your assistance!

P.S. I'm also getting prompted to upgrade to v8.1.3 (from my current v8.1.1) and not sure if I should proceed (and maybe even upgrading might fix the issue?)?

**Comment by mbressman** [comment]
Making the changes to the pdf viewer app that were specified here (https://github.com/owncloud/core/issues/19473) definitely seems to have fixed it for Chrome, although I can confirm it still doesn't work for Firefox.  It seems to also work in IE, and I didn't try Safari since I don't use it.

Does the new oC v8.2 fix this problem completely?  Just wondering.  Thanks again!

**Comment by LukasReschke** [comment]
Yes. This will be fixed with 8.2.0 and 8.1.4.
