### ISSUE TITLE
File downloaded hook (mainly for shared files)

### ISSUE THREAD

**Issue by derekblankmccoy** [owncloud/core#18923]
This is related to issue https://github.com/owncloud/core/issues/13158 although this is to see if its possible using a file system hook and elasticsearch to log it.

I think there is a need for a share owner to know when a file in a local share has been downloaded (specifically to know if a shared memo has been read)

There are file system hooks for writes, deletes etc but not downloads.

Is a file download hook is a possibility to log when a user downloads a locally shared file?

The aim would be to have a then use elasticsearch to access logs on who has downloaded the shared files.

**Comment by PVince81** [comment]
@nickvergessen isn't there one already ? How does the activity app find out when someone downloads a file from a public link ?

**Comment by derekblankmccoy** [comment]
This is for local shares

**Comment by nickvergessen** [comment]
@PVince81 https://github.com/owncloud/core/pull/12997/files

**Comment by ppaysant** [comment]
@nickvergessen @PVince81 the pull/12997  (that fixes #12928) does only process public sharing, not local sharing. And it creates hard link between files_share and activity app (bad practice, IMHO).As asked  in #17495 (by @LydSC), it would be nice to have some core hooks to monitor the use of public (via link) or local shares.

**Comment by nickvergessen** [comment]
> And it creates hard link between files_share and activity app (bad practice, IMHO).

No it does not, the `getActivityManager` method is not from the activity app.
