### ISSUE TITLE
[8.1][Cron] Problem with cron job

### ISSUE THREAD

**Issue by pierrejochem** [owncloud/core#18927]
Hi Guys,

I receive the following message in the owncloud.log:

**Error while running background job: could not set up user home for null**

Any ideas why this happens?

**Comment by karlitschek** [comment]
@icewind1991 Any idea?

**Comment by PVince81** [comment]
Any stack trace ?

**Comment by pierrejochem** [comment]
How to get the right one? It is on our production server and the cron job is not running till the end

**Comment by MorrisJobke** [comment]
> Could this happen when the connection to one of our ldap servers is getting lost?

Could be.

If you are using 8.2 you can try to apply https://github.com/owncloud/core/pull/21799 (use following patch: https://github.com/owncloud/core/pull/21799.patch and apply via `patch -p1 < 21799.patch`) Then you get more details about the actual failing job.

**Comment by pierrejochem** [comment]
Thank you, after upgrading to 8.2.2 is see this in the logs. So the mystic is solved:

Error while running background job: Lost connection to LDAP server.

Thank you very much @MorrisJobke 

can be closed now.
