### ISSUE TITLE
Sharee api pagination makes page 0 and 1 be the same. 

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#18924]
When requesting a list of users and groups for sharing and specifying a limit now the page 0 and page 1 are the same.

Having a server with several users and groups.

This request
```
curl -X GET "http://CRE:DENTIALS@HOST/ocs/v1.php/apps/files_sharing/api/v1/sharees?itemType=file&limit=3&page=0" 
```
Returns the same as
```
curl -X GET "http://CRE:DENTIALS@HOST/ocs/v1.php/apps/files_sharing/api/v1/sharees?itemType=file&limit=3&page=1" 
```

Happens the same with negative numbers. (page=-1).

I think it should start in 0 and return a 404 or similar with negative numbers.

@DeepDiver1975 @nickvergessen @rullzer

**Comment by nickvergessen** [comment]
Well I added some check to make it `max of 1 or $value`
We can easily add a return 404 on an invalid value.

But that should then also happen for all other values:
https://github.com/owncloud/core/pull/18234/files#diff-886a10da112f95e34855011648581522R291
