### ISSUE TITLE
A lot of empty and not used tables

### ISSUE THREAD

**Issue by tflidd** [owncloud/core#18935]
I have an old setup (updated from OC 4.5), now in version 8.0.6. There are some repair steps to remove old stuff during updates (@MorrisJobke ). But there are still some tables where I'm not sure to use them:

* [x] activity_mq
* [x] files_antivirus - still used by antivirus app: https://github.com/owncloud/files_antivirus/blob/5e354a343c03dfe93df5b1b6f05df8630f8854c3/appinfo/database.xml#L12
* [ ] file_map - #20320
* [x] foldersize (old partial data)
* [x] locks
* [x] log
* [ ] metadata
* [ ] principals (seems like old contact app entries, there is also a new tables clndr_*) - #20321
* [ ] principalgroups - #20321
* [x] privatedata
* [x] properties (seems to be old data)
* [x] queuedtasks

**Comment by RealRancor** [comment]
Some of those seems to be on the repairstep of oC 8.1:

https://github.com/owncloud/core/blob/v8.1.1/lib/repair/dropoldtables.php#L73-L89

**Comment by tflidd** [comment]
I cleaned my list (I had some more tables that I thought were important), it's time to install OC 8.1 ;-)

* activity_mq
* files_antivirus
* file_map
* metadata
* principals (seems like old contact app entries, there is also a new tables clndr_*)
* principalgroups
* privatedata
* properties (seems to be old data)

**Comment by RealRancor** [comment]
Just don't drop "locks" on oC 8.0 as this was only removed in 8.1 :)

**Comment by MorrisJobke** [comment]
> file_map

Definetely old and not used anymoe (I think pre oc 5)

> files_antivirus

I guess we need to look this up.

> activity_mq

I think this is actually nothing to keep and is used - cc @nickvergessen 

> principals (seems like old contact app entries, there is also a new tables clndr_*)
> principalgroups

I think this is old.

> privatedata
> properties (seems to be old data)

Keep them. the first one is use to store stuff that comes in via OCS ... cc @karlitschek @LukasReschke 

The second one is for webdav properties we need to support, because it's in the webdav spec.

> metadata

Never heard of this one.

**Comment by nickvergessen** [comment]
file_map is from windows support?

activity_mq is the mailing queue, still used! It's only empty when all notiffications are sent out or no one choosed to be notified by email.

**Comment by MorrisJobke** [comment]
> metadata

@tflidd I can't find where this table comes from. Just drop it yourself. For principals, principalgroups and file_map I created PRs. They should be gone really soon. I will close this here now, because everything is addressed.
