### ISSUE TITLE
Using the right side-bar adds permanent scroller to the UI

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#18939]
### Steps to reproduce

1. Pick a folder with a couple of files
2. Click on a file to bring out the sidebar
3. Close the sidebar, somehow

### Expected result

The general UI should not be modified

### Actual result

There is now a scroller on the right, even though there are only a couple of images in the list

@PVince81 @MorrisJobke @jancborchardt

**Comment by jancborchardt** [comment]
I can not replicate this behavior. Everything fine for me. @owncloud/designers can you check?

**Comment by oparoz** [comment]
Confirmed as fixed.
