### ISSUE TITLE
Upload to SMB share sets the modification time into the future (delorian bug)

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#18947]
### Steps to reproduce
1. enable external storage App
2. as admin user connect to an external SMB storage (in my case a share on Windows 2008R2)
3. make this connection available to a user/group
4. upload a file into that share with the desktop client or upload / create a file from the webinterface

### Expected behaviour
file is uploaded to OC and from there to the share. Modification time of the file is when it was saved. 

### Actual behaviour
Modification date in Owncloud is set to the future (its correct on the Share) and so during the next sync the desktop client downloads that file again.

After downloading the time on the client machine is also set to the future
![smb_bug](https://cloud.githubusercontent.com/assets/2425577/9783937/bae1b700-57c7-11e5-99c0-3da6e3ab5fbf.png)

I'm guess this is a problem with time zones. I'm in the Nepali time zone (Kathmandu) UTC +5:45. But the future time (in 8h) does not fit to anything. All servers are set to local time zone and receive their time from NTP

### Server configuration
**Operating system**:
Linux deepthought2 4.0.0-2-amd64 #1 SMP Debian 4.0.4-1tanglu2 (2015-05-31) x86_64 GNU/Linux
**Web server:**
Apache/2.4.10
**Database:**
MySQL  5.5.44-0
**PHP version:**
PHP Version 5.6.12-0+deb8u1~tanglu3.1

**ownCloud version:** (see ownCloud admin page)
* 8.2 pre alpha (git)

**Updated from an older ownCloud or fresh install:**
updated
**List of activated apps:**

```
Enabled:
  - files: 1.1.11
  - files_external: 0.2.3
  - files_sharing: 0.6.3
  - files_versions: 1.0.6
  - provisioning_api: 0.2
Disabled:
  - encryption
  - files_trashbin
  - user_ldap
  - user_webdavauth
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocv62j2zwgab",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "\/home\/www\/owncloud-core\/data",
        "overwrite.cli.url": "http:\/\/localhost\/owncloud-core",
        "dbtype": "mysql",
        "version": "8.2.0.4",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "singleUser": true
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
smb
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox  40.0.3
**Operating system:**
Linux deepthought2 4.0.0-2-amd64 #1 SMP Debian 4.0.4-1tanglu2 (2015-05-31) x86_64 GNU/Linux

#### Web server error log
```
[Thu Sep 10 13:54:36.863081 2015] [authz_core:error] [pid 19147] [client ::1:35497] AH01630: client denied by server configuration: /home/..../owncloud-core/data/htaccesstest.txt

```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"pqSArF+rVF1uArO8umcO","remoteAddr":"::1","app":"no app in context","message":"Trying to acquire a lock for 'files\/369638a2222fb4d47734ccc1dc289575' while inside a transition","level":2,"time":"2015-09-10T08:03:10+00:00"}

```

#### Client log
parts of the log that I thought might be usefull
```
09-10 13:46:45:495 0x1715de0 !!! OCC::PropfindJob created for "http://localhost/owncloud-core" + "/" 
09-10 13:46:45:513 0x1715de0 Saving  1  unknown certs. 
09-10 13:46:45:513 0x1715de0 Saving cookies. 
09-10 13:46:45:514 0x1715de0 "/home/xxxxx/.local/share/data//ownCloud//cookies.db" 
09-10 13:46:45:577 0x1715de0 !!! OCC::PropfindJob created for "http://localhost/owncloud-core" + "/" 
09-10 13:46:57:356 0x1715de0 detected changes in paths: QSet("/home/xxxxx/OwnCloud/test4@localhost/SMB/document.txt") 
09-10 13:46:57:361 0x1715de0 SocketApi:  Sending message:  "STATUS:OK:/home/xxxxx/OwnCloud/test4@localhost/" 
09-10 13:46:57:361 0x1715de0 SocketApi:  Sending message:  "UPDATE_VIEW:/home/xxxxx/OwnCloud/test4@localhost/" 
09-10 13:46:57:361 0x1715de0 Schedule folder  "ownCloud2"  to sync! 
09-10 13:46:57:361 0x1715de0 Scheduling a sync in 2 seconds 
09-10 13:46:57:361 0x1715de0 void OCC::Folder::watcherSlot(QString) "/home/xxxxx/OwnCloud/test4@localhost/SMB/document.txt" "SMB" "SMB/" 

9-10 13:46:59:399 0x19a5c28 _csync_detect_update: file: SMB, instruction: INSTRUCTION_EVAL <<=
09-10 13:46:59:399 0x19a5c28 sqlite_profile: _SQL_ SELECT * FROM metadata WHERE phash=?1: 0
09-10 13:46:59:399 0x19a5c28 csync_walker: file: /home/xxxxx/OwnCloud/test4@localhost/SMB/document.txt [inode=4463872 size=246]
09-10 13:46:59:399 0x19a5c28 sqlite_profile: _SQL_ SELECT * FROM metadata WHERE phash=?1: 0
09-10 13:46:59:399 0x19a5c28 _csync_detect_update: Checking for rename based on inode # 4463872
09-10 13:46:59:399 0x19a5c28 sqlite_profile: _SQL_ SELECT * FROM metadata WHERE inode=?1: 0
09-10 13:46:59:399 0x19a5c28 _csync_detect_update: file: SMB/document.txt, instruction: INSTRUCTION_NEW <<=
09-10 13:46:59:399 0x19a5c28 csync_ftw:  <= Closing walk for /home/xxxxx/OwnCloud/test4@localhost/SMB with read_from_db 0
09-10 13:46:59:400 0x19a5c28 sqlite_profile: _SQL_ SELECT * FROM metadata WHERE phash=?1: 1000000
09-10 13:46:59:400 0x19a5c28 csync_walker: file: /home/xxxxx/OwnCloud/test4@localhost/.owncloudsync.log [inode=4200686 size=132829]
09-10 13:46:59:400 0x19a5c28 _csync_detect_update: .owncloudsync.log excluded  (1)


09-10 13:47:01:141 0x1715de0 _csync_merge_algorithm_visitor: INSTRUCTION_NEW      client file: SMB/document.txt

09-10 13:47:01:143 0x1715de0 <<#### Reconcile end ####################################################  1781 
09-10 13:47:01:144 0x1715de0 SocketApi:  Sending message:  "STATUS:SYNC:/home/xxxxx/OwnCloud/test4@localhost/SMB/" 
09-10 13:47:01:144 0x1715de0 SocketApi:  Sending message:  "STATUS:SYNC:/home/xxxxx/OwnCloud/test4@localhost/SMB/document.txt" 
09-10 13:47:01:144 0x1715de0 Permissions of the root folder:  "RDNVCK" 
09-10 13:47:01:145 0x1715de0 void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "post treewalk" and starting new transaction 
09-10 13:47:01:145 0x1715de0 void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "post stale entry removal" and starting new

09-10 13:47:01:145 0x1715de0 Using QNAM/HTTP parallel code path 
09-10 13:47:01:145 0x1715de0 <<#### Post-Reconcile end ####################################################  1783 
09-10 13:47:01:145 0x1715de0 #### Propagation start #################################################### >> 
09-10 13:47:01:145 0x1715de0 Not sending UPDATE_VIEW for "ownCloud2" because status() is 3 
09-10 13:47:01:145 0x1715de0 Sync state changed for folder  "ownCloud2" :  "Sync Running" 
09-10 13:47:01:146 0x1715de0 !!! OCC::PUTFileJob created for "http://localhost/owncloud-core" + "/SMB/document.txt" 

09-10 13:47:08:178 0x1715de0 void OCC::PropagateUploadFileQNAM::slotPutFinished()  QUrl( "http://localhost/owncloud-core/remote.php/webdav/SMB/document.txt" )  FINISHED WITH STATUS 0 "" QVariant(int, 201) QVariant(QString, "Created") 
09-10 13:47:08:178 0x1715de0 *==* duration UPLOAD 246 0 7032 
09-10 13:47:08:178 0x1715de0 OCC::SyncJournalFileRecord::SyncJournalFileRecord(const OCC::SyncFileItem&, const QString&) "/home/xxxxx/OwnCloud/test4@localhost/SMB/document.txt" Retrieved inode  4463872 (previous item inode:  4463872 ) 
09-10 13:47:08:178 0x1715de0 "INSERT OR REPLACE INTO metadata (phash, pathlen, path, inode, uid, gid, mode, modtime, type, md5, fileid, remotePerm, filesize, ignoredChildrenRemote) VALUES (?1 , ?2, ?3 , ?4 , ?5 , ?6 , ?7,  ?8 , ?9 , ?10, ?11, ?12, ?13, ?14);" -606132528359848226 16 "SMB/document.txt" 4463872 0 "1441872117" "0" "55f138fd1904f" "00027780ocv62j2zwgab" "" 246 0 
09-10 13:47:08:178 0x1715de0 "DELETE FROM uploadinfo WHERE path=?1" "SMB/document.txt" 
09-10 13:47:08:178 0x1715de0 void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "upload file start" and starting new transaction 
09-10 13:47:08:322 0x1715de0 void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "SMB/document.txt" INSTRUCTION_NEW 4 "" 
09-10 13:47:08:322 0x1715de0 SocketApi:  Sending message:  "STATUS:OK:/home/xxxxx/OwnCloud/test4@localhost/SMB/document.txt" 
09-10 13:47:08:322 0x1715de0 OCC::SyncJournalFileRecord::SyncJournalFileRecord(const OCC::SyncFileItem&, const QString&) "/home/xxxxx/OwnCloud/test4@localhost/SMB" Retrieved inode  4463765 (previous item inode:  4463765 ) 
09-10 13:47:08:323 0x1715de0 "INSERT OR REPLACE INTO metadata (phash, pathlen, path, inode, uid, gid, mode, modtime, type, md5, fileid, remotePerm, filesize, ignoredChildrenRemote) VALUES (?1 , ?2, ?3 , ?4 , ?5 , ?6 , ?7,  ?8 , ?9 , ?10, ?11, ?12, ?13, ?14);" -6185090565311121885 3 "SMB" 4463765 0 "1441872117" "2" "55f1347ccd2f3" "00027779ocv62j2zwgab" "RMCK" 0 0 
09-10 13:47:08:323 0x1715de0 void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "SMB" INSTRUCTION_SYNC 0 "" 
09-10 13:47:08:323 0x1715de0 SocketApi:  Sending message:  "STATUS:OK:/home/xxxxx/OwnCloud/test4@localhost/SMB" 
09-10 13:47:08:455 0x1715de0 void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "" INSTRUCTION_NONE 0 "" 
09-10 13:47:08:457 0x1715de0 SocketApi:  Sending message:  "STATUS:OK:/home/xxxxx/OwnCloud/test4@localhost/" 
09-10 13:47:08:458 0x1715de0 void OCC::SyncJournalDb::walCheckpoint() took 0 msec 
09-10 13:47:08:458 0x1715de0 void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "All Finished."  
09-10 13:47:08:459 0x1715de0 CSync run took  9097 

09-10 13:48:13:595 0x2cdab88 csync_ftw: Uniq ID from Database: SMB -> 55f1347ccd2f3
09-10 13:48:13:595 0x2cdab88 csync_walker: directory: /home/xxxxx/OwnCloud/test4@localhost/SMB [inode=4463765]
09-10 13:48:13:595 0x2cdab88 _csync_detect_update: Database entry found, compare: 1441872117 <-> 1441872117, etag: 55f1347ccd2f3 <-> 55f1347ccd2f3, inode: 4463765 <-> 4463765, size: 4096 <-> 0, perms:  <-> RMCK, ignore: 0
09-10 13:48:13:595 0x2cdab88 _csync_detect_update: file: SMB, instruction: INSTRUCTION_NONE <<=
09-10 13:48:13:595 0x2cdab88 csync_ftw: Uniq ID from Database: SMB/document.txt -> 55f138fd1904f
09-10 13:48:13:595 0x2cdab88 csync_walker: file: /home/xxxxx/OwnCloud/test4@localhost/SMB/document.txt [inode=4463872 size=246]
09-10 13:48:13:596 0x2cdab88 _csync_detect_update: Database entry found, compare: 1441872117 <-> 1441872117, etag: 55f138fd1904f <-> 55f138fd1904f, inode: 4463872 <-> 4463872, size: 246 <-> 246, perms:  <-> , ignore: 0
09-10 13:48:13:596 0x2cdab88 _csync_detect_update: file: SMB/document.txt, instruction: INSTRUCTION_NONE <<=
09-10 13:48:13:596 0x2cdab88 csync_ftw:  <= Closing walk for /home/xxxxx/OwnCloud/test4@localhost/SMB with read_from_db 0
09-10 13:48:13:596 0x2cdab88 sqlite_profile: _SQL_ SELECT * FROM metadata WHERE phash=?1: 0
09-10 13:48:13:596 0x2cdab88 csync_walker: file: /home/xxxxx/OwnCloud/test4@localhost/.owncloudsync.log [inode=4200686 size=133110]
09-10 13:48:13:596 0x2cdab88 _csync_detect_update: .owncloudsync.log excluded  (1)
09-10 13:48:13:596 0x2cdab88 csync_ftw:  <= Closing walk for /home/xxxxx/OwnCloud/test4@localhost with read_from_db 0
09-10 13:48:13:596 0x2cdab88 csync_update: Update detection for local replica took 0,03 seconds walking 197 files.
09-10 13:48:13:596 0x2cdab88 csync_memstat_check: Memory: 1670472K total size, 101108K resident, 55416K shared
09-10 13:48:13:596 0x2cdab88 csync_ftw: URI without fuzz for owncloud://localhost/owncloud-core/remote.php/webdav is ""
09-10 13:48:13:596 0x2cdab88 static csync_vio_handle_t* OCC::DiscoveryJob::remote_vio_opendir_hook(const char*, void*) OCC::DiscoveryJob(0x25c9020)  Calling into main thread...

**Comment by individual-it** [comment]
8.1.1 behaves similar but only with 1 min difference.
file saved:
Sep 10 15:55 owncloud_perf.ods

the client uploads the file, in the next sync it downloads the file again and the timestamp is changed:
Sep 10 15:56 owncloud_perf.ods

**Comment by individual-it** [comment]
The behavior is basically the same as in #6672
@PVince81 says :"Unfortunately there is no way to set the mtime to the SMB file directly" https://github.com/owncloud/core/issues/6672#issuecomment-32255939

Sadly the fix seems not to work anymore in 8.1 & 8.2

**Comment by PVince81** [comment]
@icewind1991 can you have a look ?

**Comment by individual-it** [comment]
seems to be a problem with ````strtotime()```` in https://github.com/owncloud/core/blob/master/apps/files_external/3rdparty/icewind/smb/src/Parser.php#L101

Window Server 2008R2 File Server replies: ````write_time:     Tue Sep 15 15:39:49 2015 NPT````
 ````strtotime()```` makes it to unix time stamp: 1442340589
what is: Tue Sep 15 23:54:49 2015 Asia/Katmandu
when having the timezone called "Asia/Katmandu" or "Asia/Kat**h**mandu" (what is more correct)  ````strtotime()```` works correctly 
Nepal Standard Time: https://en.wikipedia.org/wiki/Nepal_Standard_Time

**Comment by individual-it** [comment]
Oh no ````echo timezone_name_from_abbr("NPT")```` returns "America/St_Johns"
:scream_cat:

**Comment by phil-davis** [comment]
http://www.timeanddate.com/time/zones/ - NPT is supposed to be the abbreviation for Nepal Time UTC+05:45
```timezone_name_from_abbr("NPT")``` has the same problem on FreeBSD 10.1 / pfSense 2.2.4 / PHP 5.5.27 - so that is just a PHP mess.
I will look around in PHP bugs to see if that has been reported anywhere.

**Comment by phil-davis** [comment]
@individual-it In https://github.com/php/php-src/blob/PHP-5.5.27/ext/date/lib/timezonemap.h search for "npt" - there are a whole list of places that like to use "npt" as their time zone abbreviation. That is a bit unfortunate.

**Comment by icewind1991** [comment]
Closing as it's an upstream problem with php

Also you can try installing the ph-libsmbclient bindings, if available that will be used instead of wrapping smblcient and it might give the correct time since it doesn't rely on parsing strings to dates

**Comment by individual-it** [comment]
@icewind1991 same problem with php-libsmbclient. Actually I first run into that problem on our production system that has php-libsmbclient

**Comment by individual-it** [comment]
Sorry I have to reopen this one. Looks like we are dealing with multiple problems here. 
1. the timezone issue of strtotime() that was discussed enough
2. it looks like the file on the destination share is not checked often enough for changes. (I'm now working with php-libsmbclient)

here what happens with time stamps in 8.1.1:
### starting situation
local file: 1.txt 1442385304 - 16-09-2015 12:20:04 
file on server: 1.txt 1442385304 - 16-09-2015 12:20:04 
oc_filecache.mtime: 1442385304 - 16-09-2015 12:20:04 
oc_filecache.storage_mtime: 1442385304 - 16-09-2015 12:20:04 
oc_filecache.etag: 55f90facde923

### changing file + upload from the desktop client
local file: 1.txt 1442386013 - 16-09-2015 12:31:53
file on server: 1.txt 1442386023 - 16-09-2015 12:32:03
oc_filecache.mtime: 1442386013 - 16-09-2015 12:31:53
oc_filecache.storage_mtime: 1442385304  - 16-09-2015 12:20:04 **is does not correspond with the time on the storage, was not change after upload**
oc_filecache.etag: 55f9106728aac

### client downloads the file again
local file: 1.txt 1442386023 - 16-09-2015 12:32:03 **local file was overwritten**
file on server: 1.txt 1442386023 - 16-09-2015 12:32:03
oc_filecache.mtime: 1442386023 - 16-09-2015 12:32:03 
oc_filecache.storage_mtime: 1442386023 - 16-09-2015 12:32:03 **all in sync again***
oc_filecache.etag: 55f910d287e08

## solution?
the problem seems to be in ````getFileInfo()```` in https://github.com/owncloud/core/blob/stable8.1/apps/files_external/lib/smb.php#L101
It happens that old data is delivered even we really would like to have an update. 
If I disable the surrounding if statement it works. But of course that does hit the destination file system much more often.
I cannot reproduce the problem with the master branch, so somehow that problem was fixed

**Comment by individual-it** [comment]
Updated to 8.1.3 same problem there

**Comment by PVince81** [comment]
Hmm if you say it's fixed on master it means the fix will make it into 8.2.
Now the question could also be: what commit did fix it on master.
Maybe the SMB library was upgraded to a more recent version there ?

**Comment by Xenopathic** [comment]
There were a few SMB library changes by @icewind1991, perhaps one of them fixed the problem.

**Comment by PVince81** [comment]
@individual-it is this working now in 8.2.2 or 9.0 RC 1?

**Comment by individual-it** [comment]
At the moment I have no chance to find time to explore this.
I will close the issue and if I ever stumble over it again I can reopen it or open a new one
