### ISSUE TITLE
Oracle broken on master

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#18949]
I suppose caused by https://github.com/owncloud/core/pull/18799

```
15:48:07 exception 'Doctrine\DBAL\Driver\OCI8\OCI8Exception' with message 'ORA-00932: inconsistent datatypes: expected - got CLOB' in /var/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:33
15:48:07 Stack trace:
15:48:07 #0 /var/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php(214): Doctrine\DBAL\Driver\OCI8\OCI8Exception::fromErrorInfo(Array)
15:48:07 #1 /var/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(987): Doctrine\DBAL\Driver\OCI8\OCI8Statement->execute()
15:48:07 #2 /var/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/connection.php(203): Doctrine\DBAL\Connection->executeUpdate('UPDATE "oc_appc...', Array, Array)
15:48:07 #3 /var/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(208): OC\DB\Connection->executeUpdate('UPDATE `*PREFIX...', Array, Array)
15:48:07 #4 /var/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/querybuilder/querybuilder.php(121): Doctrine\DBAL\Query\QueryBuilder->execute()
15:48:07 #5 /var/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/appconfig.php(183): OC\DB\QueryBuilder\QueryBuilder->execute()
15:48:07 #6 /var/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/app/appmanager.php(170): OC\AppConfig->setValue('files_sharing', 'enabled', 'yes')
15:48:07 #7 /var/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/app.php(312): OC\App\AppManager->enableApp('files_sharing')
15:48:07 #8 /var/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/enable_all.php(13): OC_App::enable('files_sharing')
15:48:07 #9 /var/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/enable_all.php(19): enableApp('files_sharing')
15:48:07 #10 {main}
15:48:07 
15:48:07 Next exception 'Doctrine\DBAL\Exception\DriverException' with message 'An exception occurred while executing 'UPDATE "oc_appconfig" SET "configvalue" = ? WHERE ("appid" = ?) AND ("configkey" = ?) AND ("configvalue" <> ?)' with params ["yes", "files_sharing", "enabled", "yes"]:
```
cc @DeepDiver1975

**Comment by LukasReschke** [comment]
@cmonteroluque Just that this is on your radar.

**Comment by Xenopathic** [comment]
See https://github.com/owncloud/core/blob/master/lib/private/allconfig.php#L226-L231 for how it was fixed elsewhere in the code base - no easy way with the query builder :disappointed: 

Why can't Oracle just behave normally?

**Comment by DeepDiver1975** [comment]
Stop crying and fix it! :speak_no_evil:

**Comment by Xenopathic** [comment]
`rm -f /usr/bin/oci` :see_no_evil:

**Comment by karlitschek** [comment]
Thanks for the nice tipp. I tried this command on my production machine and everything is a lot faster now. We should add this to our documentation as hint how to make ownCloud faster. How does it work by the way? Something to do with indexes? It's amazing that such a short command can have such a huge impact.

**Comment by Xenopathic** [comment]
@karlitschek It upgrades your database from the legacy version to a more modern codebase that is standards compliant. This allows ownCloud to better utilize system resources, resulting in significantly lower load and less memory usage.

I should be on the marketing team :laughing: 

Seriously though, the fix lies in getting the query builder to wrap `to_char()` around the column name that contains a CLOB. It *might* be possible with `$qb->createLiteral()` or something?

**Comment by cmonteroluque** [comment]
@Xenopathic that was beautiful poetry ;-)

**Comment by nickvergessen** [comment]
The problem is not literal or parameter, but that CLOB columns are not allowed in WHERE clauses.
I made a fix so we only check that on non-oracle now. This helps to prevent unnecessary writes on MySQL, Postgres etc while Oracle still behaves correctly:
https://github.com/owncloud/core/pull/18973

**Comment by Xenopathic** [comment]
@nickvergessen I've just prepared an alternative fix that uses `to_char()`, like AllConfig does
