### ISSUE TITLE
That new tiny login arrow is not a proper way to login

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#18940]
That tiny arrow in the field just doesn't work.

* It gets completely masked if a user uses a password manager like Lastpass
* It looks tiny
* It's almost invisible
* it looks like it's part of the design, not like an actionable item

It needs to be overhauled or it needs to go.

@jancborchardt - Call your army to fix this!

**Comment by oparoz** [comment]
Some reference work by major brands:
* https://accounts.google.com/login
* https://twitter.com/login
* https://www.facebook.com/login.php?login_attempt=1
* https://onedrive.live.com/about/en-gb/#
* https://login.microsoftonline.com/
* https://www.dropbox.com/login
* https://app.box.com/login

Notice the huge "login", "sign in" or "next" button being used in 100% of the cases

**Comment by jancborchardt** [comment]
Yeah, this was modeled after https://www.icloud.com, and previously also after https://www.tumblr.com/login

@owncloud/designers what do you think? I’d say maybe another thing to explore is to remove the user/password icons on the left since they don’t really add anything but complexity to the layout, cause it’s pretty standard what these fields are for.

**Comment by oparoz** [comment]
Of course...it had to be them :D 
As you've just mentioned, they only have one icon and it's circled to indicate the link to an action. Also, their icon doesn't disappear when the user uses a password manager. That's because the button is actually a separate item and not part of the field.

**Comment by enoch85** [comment]
Is this on 8.2? Prtscr please. :)

**Comment by LukasReschke** [comment]
![2015-09-10_14-59-54](https://cloud.githubusercontent.com/assets/878997/9788843/9b4b8cea-57cc-11e5-8cab-acb625704264.png)

**Comment by enoch85** [comment]
Wow, I think it looks nice!

@oparoz 

> Almost invinsible

Maybe if we make it less transparent?

**Comment by oparoz** [comment]
### Where is the login button?!?
![missing_button](https://cloud.githubusercontent.com/assets/323220/9800368/e0dbd9f0-580c-11e5-851d-2e5dcfa443f9.png)

### Strange login, but I see a button
![i_see_a_button](https://cloud.githubusercontent.com/assets/323220/9800392/01be4a68-580d-11e5-8a69-4c84427c7e97.png)

**Comment by oparoz** [comment]
Here is an example without the icons and with a proper separation between the field and the button

![owncloudlogin](https://cloud.githubusercontent.com/assets/323220/9800718/e49da134-580e-11e5-8eea-877618cb782d.png)

**Comment by karlitschek** [comment]
hmm. not a bad idea. What do you think @jancborchardt ?

**Comment by raghunayyar** [comment]
I think we can do without a vertical separator.

**Comment by oparoz** [comment]
But then we get that tiny, lost effect. The circle is there for a reason. Also, something else which helps is that the iCloud arrow is darker than the text in the fields.

**Comment by jancborchardt** [comment]
I guess that 2 changes already do a lot:
* remove the icons on the left
* restructure the HTML in a way that the password manager issue doesn’t occur

Maybe we additionally should make the arrow darker too, but the separator is not needed I think. Ok?

**Comment by oparoz** [comment]
Yes, either the arrow darker or the text lighter.
Bear in mind though that the authentication page for public links uses a button for the arrow and there is a very thin line on the left. You may want to harmonize the two password areas.

**Comment by oparoz** [comment]
Oh yeah and there is an alignment problem in `/authenticate` . Not worth opening a PR if you fix it while fixes this issue.

![line-lines-lines](https://cloud.githubusercontent.com/assets/323220/9819352/b0011df8-58ad-11e5-901e-9528b74388df.png)

**Comment by DeepDiver1975** [comment]
@oparoz all concerns addressed? can we close this? THX

**Comment by oparoz** [comment]
@DeepDiver1975 Nothing has changed. The merged PR was to fix the password dialogue.
If you want to wait until you get more designers/users feedback before considering this an issue, then let's postpone this to 8.2.1

**Comment by DeepDiver1975** [comment]
> If you want to wait until you get more designers/users feedback

I don't need more feedback - I want agreement on a solution :wink: 

@jancborchardt please drive this to a collaborative solution - THX

**Comment by cmonteroluque** [comment]
moving to 8.2.1

**Comment by dragotin** [comment]
This is especially bad when we think of normal people using the enterprise edition who are not design nerds but simply wanna work.

**Comment by DeepDiver1975** [comment]
@jancborchardt please respond as requests 23 days back - THX

**Comment by jancborchardt** [comment]
Yeah, I’m thinking about it. For one-field flows like password-protected links, adding new bookmarks, groups etc the inline button works very well. Here the issue seems to be that there are two fields, and the button is not identified as such.

Now I’d say for both log in and password-protection, removing the icons (as said above and sketched by oparoz) will emphasize the log in button. It also reduces the complexity because for the simple username-password combo we really don’t need icons.
Now in addition we can think about adding a line between arrow and password input field, but I would only do that in this specific case for the log in, because elsewhere we always have only one field and there the emphasis is not necessarily needed.

@owncloud/designers what do you think?

**Comment by HLFH** [comment]
@jancborchardt 

> Now I’d say for both log in and password-protection, removing the icons (as said above and sketched by oparoz) will emphasize the log in button. It also reduces the complexity because for the simple username-password combo we really don’t need icons.
Now in addition we can think about adding a line between arrow and password input field, but I would only do that in this specific case for the log in, because elsewhere we always have only one field and there the emphasis is not necessarily needed.

I fully agree with you.

**Comment by EtlamGit** [comment]
I would vote to get the separated bigger button back! (And I also liked the small icons...)

Only Apple is using this strange embedded button. Even the mentioned tumblr has a separated button (now). It is much easier to hit a larger separated button than to find this tiny thing.

If there are still some Apple fan boys insisting to have this strange layout:
Maybe it is possible for the login screen to be configured by a simple parameter in config.php or Admin interface?
Then Apple users and all the rest can get the interface they are used to.

**Comment by jancborchardt** [comment]
> Maybe it is possible for the login screen to be configured by a simple parameter in config.php or Admin interface?

**Comment by jancborchardt** [comment]
> Maybe it is possible for the login screen to be configured by a simple parameter in config.php or Admin interface?

@EtlamGit if you insist on changing it you can always theme your ownCloud. See https://github.com/owncloud/core/blob/master/themes/README – we do not recommend theming templates but it’s possible.

The small icons were mostly noise since two input fields with the label username and password are about as obvious as it gets. Since you refer to Tumblr, they also don’t have the icons.

**Comment by EtlamGit** [comment]
I know about theming (and doing it in little extend), but when doing that you have to ensure at each version change that your theme is still compatible to the new core files. This is a bit annoying work...

At the moment I always click on the "[ ] remember" button, as this is the only thing that is visually emphasized. I think more users will comment on this topic in the coming month when 8.2 is installed on a broader basis.

In case I'm able to understand the code to check for parameters in config.php I could try to create a pull request with both interfaces. Then you can decide if it is worth to merge or if I have to theme...

**Comment by dragotin** [comment]
Yes, there should be a separate login button for good usability.

**Comment by jancborchardt** [comment]
@EtlamGit I opened this new issue to take care of your »remember« checkbox remark which is a good point: https://github.com/owncloud/core/issues/20477 (trigger log in when »Stay logged in« checkbox is clicked)

@dragotin especially _you_ should know better to not comment with these "+1"-style comments devoid of any value. ;)

**Comment by enoch85** [comment]
I vote NO for a separete login button. Just FYI.

It's ugly, and the new design is not hard to understand. I don't see how the usability would be better with a separete button.

**Comment by dragotin** [comment]
@jancborchardt how can *my* opinion be of no value? Yeah, ok, sorry... :beers:

**Comment by EtlamGit** [comment]
Just for the records: It is not intended by the main developers to have new configuration options to change this part of the user interface (and no other parts in general).

As I have to change the files for my installation anyways, I provide them in an own repository here:
https://github.com/EtlamGit/owncloud_button
