### ISSUE TITLE
Files/Folders are not listed after some scrolling

### ISSUE THREAD

**Issue by TheAndr3w** [owncloud/core#18941]
### Steps to reproduce
1. Upload many files via webdav/web/sync client

### Expected behaviour
All the files shouldn't be listed and after some scrolling, there should be much white space but the files are actually there (should be clicked etc.)

### Actual behaviour
Actual behaviour is really like in the expected behaviour. 
After some scrolling, there is much white space and files can be clicked as well.
The file names, classes etc. are in the html source code!
After uploading files through the web, the progress bar stuck and isn't displaying the files as mentioned above.
Also, when I select one or multiple files via the checkbox, the horizontal navigation bar is popping up, but there are no buttons or anything else.

### Server configuration
**Operating system**:
Ubuntu 14.04.3 LTS
**Web server:**
Apache/2.4.7 (Ubuntu)
**Database:**
MySQL 5.5.4
**PHP version:**
PHP 5.5.9-1ubuntu4.11 
**ownCloud version:** (see ownCloud admin page)
Fresh installed 8.1.1.3 via Ubuntu Repository
**Updated from an older ownCloud or fresh install:**
no
**List of activated apps:**
Enabled:
 - activity: 2.0.1
 - encryption: 1.0.0
 - files: 1.1.10
 - files_locking:
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - gallery: 0.6.0
 - templateeditor: 0.1
Disabled:
 - direct_menu
 - external
 - files_external
 - firstrunwizard
 - provisioning_api
 - user_external
 - user_ldap
 - user_webdavauth

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' =>
  array (
    0 => 'cloud.domain.com',
  ),
  'datadirectory' => '/cloud',
  'overwrite.cli.url' => 'https://cloud.domain.com',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud_db_usr',
  'dbpassword' => 'xxx',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_from_address' => 'donotreply',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'domain.com',
  'loglevel' => 0,
  'log_rotate_size' => 52428800,
  'memcache.local' => '\OC\Memcache\APCu',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox 40.0.3

**Operating system:**
Windows 7, Ubuntu 14.04, Mac OSX 10.10
#### Web server error log
none apache errors

#### ownCloud log (data/owncloud.log)
none errors

#### Browser log
TypeError: OC.Share is undefined share.js:75:5
TypeError: OC.Share is undefined share.js:75:5

![owncloud_error1](https://cloud.githubusercontent.com/assets/4334020/9770790/7ac689ba-5732-11e5-83d3-7f7a1085e0ce.png)

![owncloud_error2](https://cloud.githubusercontent.com/assets/4334020/9821548/3ada4a14-58bb-11e5-85ae-09c63a707baf.png)

**Comment by PVince81** [comment]
Ah yes, that one. Will be fixed in 8.1.4, see https://github.com/owncloud/core/pull/19439

Please go to the admin page and re-enable "Allow apps to use the Share API"
