### ISSUE TITLE
Interface not updated when link expired.

### ISSUE THREAD

**Issue by IYOTTA** [owncloud/core#18944]
### Steps to reproduce
1. Set Link Expired

### Expected behaviour
If link has expired. File will show as normal file. not Shared.
### Actual behaviour
![232323](https://cloud.githubusercontent.com/assets/14050802/9780081/093d5572-57ae-11e5-9178-1566a2b0da2e.jpg)
If no have people go to that Link or user is not click "Shared" button,
WebUI is not updated when link has expired. It's still "shared" in this pic. 

### Server configuration
**Operating system**:
FreeBSD 9.3-RELEASE-p21
**Web server:**
Apache/2.4.16 (FreeBSD)
**Database:**
MySQL 5.6.25
**PHP version:**
PHP Version 5.5.27
**ownCloud version:** (see ownCloud admin page)
8.1.1.3
**Updated from an older ownCloud or fresh install:**
fresh install
**List of activated apps:**
Activity  2.0.1
Deleted files  0.6.3
File Locking  
LDAP user and group backend  0.6.1
Mail Template Editor  0.1
PDF Viewer  0.7
Pictures  0.6.0
Provisioning API  0.2
Share Files  0.6.2
Text Editor  0.4
Updater  0.6
Versions  1.0.6
Video Viewer  0.1.3

**The content of config/config.php:**
$CONFIG = array (
  'instanceid' => xxx',
  'passwordsalt' => 'xxx',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => 'xxxx',
  ),
  'datadirectory' => '/owncloud/data',
  'overwrite.cli.url' => 'xxx',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'dbname' => 'share_owncloud',
  'dbhost' => 'xxx',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin',
  'dbpassword' => 'xxx',
  'logtimezone' => 'UTC',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'theme' => 'theme',
  'trashbin_auto_expire' => true,
  'trashbin_retention_obligation' => 3,
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP


### Client configuration
**Browser:**
Chrome 45.0.2454.85 m
**Operating system:**
Window Vista, 7

**Comment by PVince81** [comment]
This is fixed in 9.0. The link share will expire as soon as it's requested through the API.

CC @rullzer
