### ISSUE TITLE
Remove or mark Pictures app in oC 8.1 as deprecated

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#18953]
Hi,

we're getting tons of the same reports that the file list of oC 8.1 is missing at forums and IRC. This is fixed again by disabling the pictures app.

As the pictures app doesn't get any updates/fixes anymore and will be replaced by Gallery+ it could make sense to remove the pictures app completely in oC 8.1 or at least mark it at "deprecated".

**Comment by karlitschek** [comment]
well it is a normal part of the release, supported and not deprecated. :-)

**Comment by RealRancor** [comment]
A normal part which is known to cause various bugs and tons of reports at the forums?

**Comment by RealRancor** [comment]
Just some pointers:

https://forum.owncloud.org/viewtopic.php?f=31&t=30357
https://forum.owncloud.org/viewtopic.php?f=31&t=29514
https://forum.owncloud.org/viewtopic.php?f=31&t=29347

and counting.

**Comment by karlitschek** [comment]
I understand your pain. The _correct_ fix would still be to fix the bugs instead of deprecated a core functionality.
