### ISSUE TITLE
Font style is too narrow and looks blurry using 'old screens'

### ISSUE THREAD

**Issue by davitol** [owncloud/core#18954]
![screen shot 2015-09-10 at 13 14 34](https://cloud.githubusercontent.com/assets/10596560/9786963/990f5604-57be-11e5-8bb3-53e78c1b4d04.png)
The letters are too narrow and they seem to be designed for high definition screens

**Comment by LukasReschke** [comment]
@davitol The screenshot here looks fine. Maybe you can do a photo using your mobile phone so we see how it looks on the screen instead the video buffer?

**Comment by oparoz** [comment]
### Colour for left sidebar items is too "light"

Because the font is so thin, there needs to be a higher level of contrast to make the labels legible on as many devices as possible.
While the filenames look crisp, it's really not the case with the items on the left. 

I think this should be fixed in 8.2 since it introduces the new theme.

**Comment by oparoz** [comment]
![blurrrrrrr](https://cloud.githubusercontent.com/assets/323220/10079518/d0748e48-62ea-11e5-8e16-e20fa624b095.png)

**Comment by oparoz** [comment]
You can see how some of the letters are blurred away

**Comment by davitol** [comment]
@LukasReschke Ups, i've never sent the photo from my mobile phone, but the reason was it looked better in the photo than in the screen :see_no_evil: 
I agree with @oparoz

**Comment by jancborchardt** [comment]
(I’m on vacation, this is an exception.)

Together with the report by @BernhardPosselt at https://github.com/owncloud/core/issues/19555 – what’s the call here on the usage of the Light style? It seems to have some problems on some setups. Do we just go ahead with it, or switch it back to regular? cc @karlitschek @owncloud/designers

**Comment by carlaschroder** [comment]
FWIW, I also find the new fonts to be difficult to read. They're thin and gray, even on a hi-resolution 24" screen.

**Comment by mroi** [comment]
I’ll chime in. I tried the new font style, but found it much harder to read than the previous fonts. It may be OK for labels and other short texts, but it’s a reduction in usability for longer reads and writes. I tested on standard and HiDPI displays and found it too light on both. Looks should not outweigh productivity, so I ultimately reverted the font change in my installation.

**Comment by Akhenaton** [comment]
I"ll back your comment. New fonts are unreadable... I found also that the new icons theme is AMHA ugly... I much prefer the "old" one. How can we revert ?

**Comment by jancborchardt** [comment]
Ok, I’m thinking headings could be Light, emphasis SemiBold (both like now) but all normal body text except that Regular.

What do you think @owncloud/designers @karlitschek?

**Comment by mroi** [comment]
That sounds like a sensible compromise.
Just for the record: I like all the other design changes and I much appreciate your hard work on moving ownCloud forward.

**Comment by Akhenaton** [comment]
Yes, thank you !
Just for info, have a look at this thread https://forum.owncloud.org/viewtopic.php?f=36&t=31090

**Comment by BernhardPosselt** [comment]
@jancborchardt Even the headings are hard to read, only place i see for regular is the app name in the navigation for instance where the font is way bigger than usual (if thats what you mean by headings :))

**Comment by oparoz** [comment]
The readability issues stems not only from the font, but also from the lack of enough contrast, so maybe playing with colours could be an alternative in some areas.

**Comment by MorrisJobke** [comment]
More examples of unsharp font: https://github.com/owncloud/core/issues/20114#issue-113803640

**Comment by BernhardPosselt** [comment]
Another thing: checked the fonts at home on my 22" 1080p monitor and even the headings look bad.

**Comment by Akhenaton** [comment]
Hi,
Sure, it's only "cosmetic" feature, but this lack of readability is really annoying for many users... I don't know if it's possible to do something already for the next  8.2.1-current-maintenance due by November 17, 2015 instead of waiting full 3 months for the 9.0 release (due by February 9, 2016)
Regards,

**Comment by jancborchardt** [comment]
Phew, yeah – I need to evaluate what we can do here and discuss it with the team.

It would be great to get your input here @karlitschek @MorrisJobke @PVince81, especially on my proposal at https://github.com/owncloud/core/issues/18954#issuecomment-150517675

**Comment by MorrisJobke** [comment]
> It would be great to get your input here @karlitschek @MorrisJobke @PVince81, especially on my proposal at #18954 (comment)

Best would be to have a PR to play with. I have several different devices with different DPI here and would like to have a real view of it. ;)

**Comment by karlitschek** [comment]
Yes an PR to test the approach would be great. What do you think @jancborchardt ?

**Comment by jancborchardt** [comment]
Ok, I’ll prepare it.

**Comment by jancborchardt** [comment]
We’ll see how the feedback is with this change for 8.2.1.

**Comment by spap2** [comment]
After upgrade to 8.2.2 from 8.1.5 we've got complains from every !!! user about fonts.
Though we use HP EliteDisplay E232 model, we do have problem.
Please make an easier update than the 7 steps proposed or make a selection menu for old/new style.

**Comment by SergioBertolinSG** [comment]
This is still happening using Edge.

![screen shot 2016-01-14 at 13 14 18](https://cloud.githubusercontent.com/assets/9048796/12324178/2de268c4-bac1-11e5-8f2b-fd9ba5e9c052.png | width=100)

**Comment by MorrisJobke** [comment]
@SergioBertolinSG Can you please open this as a separate issue, because it is fixed in all other browsers.

**Comment by SergioBertolinSG** [comment]
@MorrisJobke Sure, opened here https://github.com/owncloud/core/issues/21715

**Comment by MorrisJobke** [comment]
> @MorrisJobke Sure, opened here #21715

Thanks :)
