### ISSUE TITLE
Encryption improved handling of recovery keys

### ISSUE THREAD

**Issue by schiessle** [owncloud/core#18951]
At the moment we create a recovery key-pair and use the public key to encrypt all files if the user enabled the recovery feature. Basically the recovery key works like a additional user to whom all files are shared. This can have some performance impacts if a user enable/disable the recovery key with a lot of files.

Therefore the idea is to make a copy of the users private key, encrypted with the recovery password. In this case we only have to copy one file (the private key) to a backup location and encrypt it with the recovery password instead of updating every individual file key. Also disabling the recovery key is much easier because we just need to delete the copy of the private key. The performance of the recovery process would also improve significantly because on recovery we no longer have to decrypt/re-encrypt all file keys but just copy over the backup of the private key and re-encrypt the private key with the users new password.

Only thing which needs to keep in mind:
- If there are situations where we replace the users private key we also need to update the backup created for recovery.

This was a idea from @jknockaert. I just decided to summarize it here to make sure that it doesn't get lost. If I missed something, feel free to add it. If you have some time and want to implement it feel free to assign the issue to yourself.

**Comment by schiesbn** [comment]
cc @cmonteroluque @karlitschek maybe also interesting for you.

**Comment by karlitschek** [comment]
interesting idea. Let's look into this at a later point in time when we have time :-)

**Comment by cmonteroluque** [comment]
@schiesbn definitely. Nice idea.

**Comment by schiesbn** [comment]
One possible drawback:
This way we always use the same private key. In case the private key was compromised the current recovery key method is a nice way to replace the keys with new ones. If we would change the behavior as explained above we would probably need a additional functionality to replace the private key.

Still I think the changes discussed above are worth considering. In most cases you probably just want to recover access to the files and don't need a new private key.

**Comment by jknockaert** [comment]
I would favour a solution that implements both features separately. What I'm worried most about is php timeouts. The current recovery implementation is not robust with respect to timeouts (think of a timeout happening upon activation by a user who has a lot of files in his/here account). The changes discussed here would at least make the recovery less prone to key corruption. The file key replacement functionality should be implemented in the occ command line script; the recovery password and the new user password could be entered then interactively by an admin.

**Comment by chrsch** [comment]
How will you handle the recovery password? Let's assume an admin did enable recovery feature at some point in time. Later on an user decides to turn on the recovery feature for himself. If I understand the proposal, now the encryption app basically needs to copy the unencrypted private key of the user and afterwards store it encrypted with the recovery password set by the admin. But hey... where do we get the recovery password from? It can't be stored within the cloud... Did I miss something?

**Comment by chrsch** [comment]
Hmm any thoughts on this? @schiesbn

**Comment by jknockaert** [comment]
The recovery passwd is only needed to enable the recovery private key which is used to decrypt the user private key. To encrypt the user private key the recovery public key would be used.
