### ISSUE TITLE
"Clear Username-LDAP User Mapping" & "Clear Groupname-LDAP Group Mapping" should be coloured border buttons

### ISSUE THREAD

**Issue by davitol** [owncloud/core#18956]
### Steps to reproduce

1. Enable LDAP app.
2. Configure a LDAP and click on expert tab

### Expected behaviour
"Clear Username-LDAP User Mapping" & "Clear Groupname-LDAP Group Mapping" should be border coloured buttons due to they appear among a lot of text

### Actual behaviour
"Clear Username-LDAP User Mapping" & "Clear Groupname-LDAP Group Mapping"  seem to be part of the text instead two buttons.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
master version:"8.2.0.4","versionstring":"8.2 pre alpha"

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Firefox
![botonesldap](https://cloud.githubusercontent.com/assets/10596560/9787879/a6621a0a-57c6-11e5-9d02-4cbec405b165.png)

**Comment by jancborchardt** [comment]
@blizzz just make them `<button>` buttons.

**Comment by DeepDiver1975** [comment]
> @blizzz just make them <button> buttons.

@jancborchardt blizz is on vac - pr welcome - THX

**Comment by blizzz** [comment]
@jancborchardt they are already button buttons:

![buttons](https://cloud.githubusercontent.com/assets/2184312/9992159/609c0816-6070-11e5-8f40-bcc5d2e37f3c.png)

**Comment by PVince81** [comment]
What's the next step ? Is it a bug ? @jancborchardt is off currently.

**Comment by cmonteroluque** [comment]
moving to 8.2.1

**Comment by jancborchardt** [comment]
@Blizzz how are they different from the »Text configuration« button below which displays fine? If there’s any difference, simply adjust it.

**Comment by PVince81** [comment]
The button at the bottom has the class "ui-button" and others from jquery UI.

**Comment by PVince81** [comment]
We probably need a new style "standard button on dark background" additionally to the regular button style.

**Comment by jancborchardt** [comment]
Then we just add ui-button there? And for a longer-term solution we need to remove the jQuery style from there (hope I get around to it with 9.0).

**Comment by PVince81** [comment]
It seems that this class is not enough. The hover is missing and is done by jquery UI's Javascript.

To make it work we need to trigger jquery UI using `.button` like it's done here: https://github.com/owncloud/core/blob/master/apps/user_ldap/js/wizard/view.js#L352
