### ISSUE TITLE
Two useless arrows appear in the textboxes of LDAP wizard

### ISSUE THREAD

**Issue by davitol** [owncloud/core#18955]
### Steps to reproduce
1. Enable LDAP app.
2. Configure a LDAP and click on users tab
### Expected behaviour

Textboxes should appear without an arrow
### Actual behaviour

Two useless arrows appear. Same behaviour in groups tab.
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
master version:"8.2.0.4","versionstring":"8.2 pre alpha"

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```
```
### Client configuration

**browser**
Firefox
![flechasmal](https://cloud.githubusercontent.com/assets/10596560/9787627/a626626e-57c4-11e5-9b92-d8480a1c9a4d.png)

**Comment by PVince81** [comment]
moved to grouped UX ticket: https://github.com/owncloud/user_ldap/issues/69
