### ISSUE TITLE
[Windows] [2.0.1] [build 5446] Changes in ignored files trigger full discovery and sync, killing performance.

### ISSUE THREAD

**Issue by cluelessperson** [owncloud/core#18965]
#### Issue:

When ignored files or directories are modified, discovery and synchronization is triggered.

#### Example Case:

Hexchat portable application in ownCloud directory is run, updating scrollback, logs, and conf files constantly as new messages are received.  This directory has been marked as ignore.

![owncloud](https://cloud.githubusercontent.com/assets/5635253/9800851/fc9669ea-57d4-11e5-8306-bdabb14f3231.PNG)

**Comment by karlitschek** [comment]
please open this issue in the client repository.  thanks
