### ISSUE TITLE
Asset cache is updated for every client

### ISSUE THREAD

**Issue by seebk** [owncloud/core#18962]
Recently I have activated the asset pipeline/cache for my owncloud installation. I expected that the first load of a certain page will slow down due to the initial generation of the js and css files. However, it seems that at least the js files are additionally regenerated everytime I visit owncloud from a different client which is a quite annoying slowdown. This happens if I use a different computer, different browser, or cleared my browser cache.

Is it really necessary to regenerate the js file specificly for a client?

**Comment by LukasReschke** [comment]
> Recently I have activated the asset pipeline/cache for my owncloud installation. I expected that the first load of a certain page will slow down due to the initial generation of the js and css files. However, it seems that at least the js files are additionally regenerated everytime I visit owncloud from a different client which is a quite annoying slowdown. This happens if I use a different computer, different browser, or cleared my browser cache.

This should not be the case. Can you check if the CSS and JS links are the same? It will generate different JS and CSS views for different views but besides this, this should not really matter.

**Comment by seebk** [comment]
Opening the login page I get
Chromium browser: https://cloud.sebastiankraft.net/assets/8fd3509bbf8803e31d3b8c336f3da504.js
Firefox: https://cloud.sebastiankraft.net/assets/1a6663afcdcf4f5d6c41559ee3db6f7c.js

The files are different in size, however I could not spot the difference on a first glance.

**Comment by PVince81** [comment]
Please try again with 8.2.2 or 9.0 RC1.

If you're still having issues, please use the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by seebk** [comment]
Problem does not appear anymore. Now Chrome, Firefox, ... all get the same cached assets.
