### ISSUE TITLE
Continue to get cURL errors with 8.1.1

### ISSUE THREAD

**Issue by nestsman** [owncloud/core#18961]
I just installed 8.1.1 thinking it would resolve the issue, "cURL error 60: See http://curl.haxx.se/libcurl/c/libcurl-errors.html", but it did not. The change log seemed to indicate this was one of the fixes. I do use centOS on my VPS server. Is there anything that can be done besides manually installing apps?

Thank you.

**Comment by RealRancor** [comment]
Just cross-posting my comment in the other issue (https://github.com/owncloud/core/issues/17446#issuecomment-139351724) you posted the same:

> @nestsman ownCloud 8.1.1 isn't fixing an issue you're having with outdated/buggy libs on CentOS. It only shows in your admin backend if you're affected as also described here:
>
>https://doc.owncloud.org/server/8.1/admin_manual/configuration_server/security_setup_warnings.html#outdated-nss-openssl-version
>
>There you can also see the info what to do to fix this issue.

**Comment by RealRancor** [comment]
Btw. if you have used the updater app make sure the /config/ca-bundlers.crt is in place as pointed out here: https://forum.owncloud.org/viewtopic.php?f=17&t=29790
