### ISSUE TITLE
Some figures are lost in ownCloudUserManual.pdf documentation file

### ISSUE THREAD

**Issue by davitol** [owncloud/core#18969]
### Steps to reproduce

1. Open ownCloudUserManual.pdf file

### Expected behaviour
All figures should be shown

### Actual behaviour
"Selecting VCF files" figure in page 37 and "Cropping contact image" figure in page 40 are not shown

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** 8.1.3.0","versionstring":"8.1.3","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Firefox

**Comment by RealRancor** [comment]
Isn't this something for https://github.com/owncloud/documentation/issues ?

**Comment by carlaschroder** [comment]
Are the figures present on the HTML pages?

**Comment by davitol** [comment]
Yes, they appear, e.g. https://doc.owncloud.org/server/8.1/user_manual/pim/contacts.html
Selecting VCF files and "Cropping contact image" figures are shown

**Comment by carlaschroder** [comment]
Thanks for reporting this, davitol, and making a proper bug report. The images are present in the current user manual downloads from doc.owncloud.com and doc.owncloud.org. The PDF manuals are generated from the same source files as the HTML files, so my guess is something went haywire in an older build, and it fixed itself in a later build. The newest PDF manuals are at  https://doc.owncloud.org/server/8.1/ownCloud_User_Manual.pdf and https://doc.owncloud.org/server/8.1/ownCloud_User_Manual.pdf.
