### ISSUE TITLE
php 32 bit (arm) filemtime on large file issue

### ISSUE THREAD

**Issue by cyberb** [owncloud/core#18971]
I am facing an issue with running file:scan on arm:

filemtime(): stat failed

Looks like the reason is filemtime [1] is not working for files over 2G on 32 bit php [2]

Fixing function according to php website comment solved the problem:

```
  exec ('stat -c %Y '. escapeshellarg ($this->getSourcePath($path)));
```

I am sure that worked fine in past with older owncloud/php versions on the same hardware.

Is there something I am missing or this never worked on php (32bit) / arm?
Or is it possible to have some if, like:

```
if (PHP_INT_SIZE === 4)
   return exec ('stat -c %Y '. escapeshellarg ($this->getSourcePath($path)));
else
   return filemtime($this->getSourcePath($path));
```

I cannot upgrade php to 64 bit on arm board as there there is no such thing yet as arm64 or at least not popular enough on single board computers yet.

[1] http://php.net/manual/en/function.filemtime.php#68814
[2] https://github.com/owncloud/core/blob/master/lib/private/files/storage/local.php#L159

My system:
ownCloud version 8.0.4
PHP Version => 5.6.9
System => Linux cubietruck 3.4.79-sun7i #13 SMP PREEMPT Thu Jul 3 06:34:55 CST 2014 armv7l
Configure Command =>  './configure'  '--enable-fpm' '--with-pgsql' '--with-pdo-pgsql' '--enable-opcache' '--prefix' '--with-config-file-path=/root/build/install/config' '--with-gd' '--enable-zip' '--with-zlib' '--with-curl' '--with-readline' '--with-ldap' '--with-ldap-sasl' '--with-libdir=lib/arm-linux-gnueabihf' '--enable-mbstring'

**Comment by hoorna** [comment]
Hi,

I am also facing an issue with file:scan. I hope I am allowed to post it here.

While running the file:scan command I am receiving many, many, many times the next message:

         stat: invalid option -- 'c'
         BusyBox v1.16.1 (2015-06-29 18:12:44 CST) multi-call binary.

         Usage: stat [OPTIONS] FILE...

         Display file (default) or filesystem status

         Options:
                 -f      Display filesystem status
                 -L      Follow links
                 -t      Display info in terse form

I am running OwnCloud on a Synology Diskstation. Synology implemented the Busybox shell on their Diskstations.

I don't know if there is something going wrong nor how to solve this.

**Comment by cyberb** [comment]
After digging a little bit more I have found that there is already exist some large file support for file size:
https://github.com/owncloud/core/blob/master/lib/private/largefilehelper.php#L164

So probably the right way to fix filemtime issue is to add getFileMTime similar to getFileSize.
I can add one in a branch but I can do only linux.

@hoorna 
Your issue must be with getFileSize which tries 'stat -c' on linux:
https://github.com/owncloud/core/blob/master/lib/private/largefilehelper.php#L170
but busybox probably does not implement -c option.

**Comment by polrus** [comment]
this is still an issue in 32bit x86 in owncloud 8.2.2 - is there any patch ?

**Comment by cyberb** [comment]
@polrus Someone from ownCloud team should probably do a complete fix to cover other platforms as I care only about linux.

**Comment by PVince81** [comment]
@cyberb not sure what other platforms you mean. Windows server support has been dropped a while ago and so far only Linux is supported. (some people run on FreeBSD but it's not officially supported)

**Comment by cyberb** [comment]
If that is true then it should be easy to integrate my fix

**Comment by DeepDiver1975** [comment]
> If that is true then it should be easy to integrate my fix

Feel free to submit a pull request - THX

**Comment by PVince81** [comment]
PR https://github.com/owncloud/core/pull/25428 got merged, closing
