### ISSUE TITLE
Disabling "Allow apps to use the Share API" option, the files shared by link are available

### ISSUE THREAD

**Issue by davitol** [owncloud/core#18970]
### Steps to reproduce

1. Share a file by link
2. Copy the link
3. Admin User unchecks "Allow apps to use the Share API" option

### Expected behaviour
The file should not be shared any longer

### Actual behaviour
The file is available by link

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
master version:"8.2.0.4","versionstring":"8.2 pre alpha"

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Firefox

**Comment by PVince81** [comment]
Makes sense, maybe it's missing a check.

**Comment by PVince81** [comment]
@rullzer want to take on this hopefully easy one ?

**Comment by rullzer** [comment]
Fix in #19262
