### ISSUE TITLE
feature: add global quota for whole installation

### ISSUE THREAD

**Issue by hostingnuggets** [owncloud/core#18988]
It would be really a nice feature if the OC administrator account could set a max disk space usage (global quota) for the whole installation.

In order to acheive that right now I use file system quotas (quotatool on ext4 on Linux) and this doesn't work nicely with OC. As soon as the quota is reached a PUT will lead to an HTTP error 400 which doesn't mean much for the end user.

**Comment by RealRancor** [comment]
Hi,

sounds to me like a dup of https://github.com/owncloud/core/issues/1347

**Comment by hostingnuggets** [comment]
it is indeed but that issue #1347 is from 2013 and it looks like nothing has really moved yet...

**Comment by RealRancor** [comment]
> from 2013 and it looks like nothing has really moved yet...

it's on the "backlog" and tagged as an enhancement. Another open issue about the same request probably won't help going faster with that request. :-)

**Comment by hostingnuggets** [comment]
good to know that its on the backlog so from my point of view this issue can be closed and hopefully this feature will soon be available

**Comment by RealRancor** [comment]
Feel free to close this issue yourself via the "Comment & Close" button below the textbox.
