### ISSUE TITLE
Filenames in right sidebar need more space around them to breath

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#18981]
![](https://cloud.githubusercontent.com/assets/323220/9816729/fc103ed6-589e-11e5-9160-2231d66bb0b0.png)

The g,p etc. are eaten away

@jancborchardt

**Comment by jancborchardt** [comment]
Yup, we need to increase the height a bit. Good catch @oparoz! :)

We also need to add some whitespace below the name and details so the switcher for Activites/Versions/Sharing is not stuck directly below that.

@owncloud/designers anyone wants to take that up?
