### ISSUE TITLE
Folder name allowed, but can't upload anything to it

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#18987]
### Env

PHP 5.5
master
local storage

### Steps to reproduce
1. Create a folder named `duck...`
2. Open it
3. Upload a file

### Expected result

A new row

### Actual result

An error message saying

> Invalid directory

### Logs
 
Zip, naught, nada

**Comment by individual-it** [comment]
````if (strpos($dir, '..') === false)```` is to restrictive in
https://github.com/owncloud/core/blob/master/apps/files/ajax/upload.php#L151

**Comment by individual-it** [comment]
fixed with #19006 
please review.
In my opinion this should be also back ported to 8.1

**Comment by individual-it** [comment]
please review 8.1 backport: #19013
