### ISSUE TITLE
Issue with command "occ files:scan"

### ISSUE THREAD

**Issue by hoorna** [owncloud/core#18994]
Hi,

I am facing an issue with the command "php occ files:scan". While running this command I am receiving many, many, many times the next message:

         stat: invalid option -- 'c'
         BusyBox v1.16.1 (2015-06-29 18:12:44 CST) multi-call binary.

         Usage: stat [OPTIONS] FILE...

         Display file (default) or filesystem status

         Options:
                 -f      Display filesystem status
                 -L      Follow links
                 -t      Display info in terse form

Probably it has to do with the shell which is running on my Synology DiskStation (with the latest firmware DSM 5.2-5592 update 4): Busybox 1.16.1. In this version of Busybox the option "--c" of the stat command seems not to be implemented.
Synology uses this rather old version of Busybox on all of his DiskStations and it is hardly impossible to upgrade Busybox to a newer version without creating operating problems on these NAS systems.

I have three questions:
1) What is the meaning of the messages I get from "occ files:scan": are these warnings or error-messages?
2) Is "occ files:scan" on my box operating as supposed or are there things going wrong?
3) I don't see a solution for my issue with "occ files:scan" . Can I do something about it or is it a bug?

**Comment by karlitschek** [comment]
hmm. there most be something busybox specific on your synology. I don't have one so I can't test.
I suggest to ask this question in the forum. maybe some ownCloud user has better idea. If there is something on the owncloud side to be improved then let us know. But until then I assume that this is a busybox specific problem.

**Comment by cyberb** [comment]
@hoorna 
Try commenting getFileSizeViaExec call in https://github.com/owncloud/core/blob/master/lib/private/largefilehelper.php#L104 
and rerun file scan

````
public function getFileSize($filename) {
                $fileSize = $this->getFileSizeViaCurl($filename);
                if (!is_null($fileSize)) {
                        return $fileSize;
                }
                $fileSize = $this->getFileSizeViaCOM($filename);
                if (!is_null($fileSize)) {
                        return $fileSize;
                }
                # $fileSize = $this->getFileSizeViaExec($filename);
                # if (!is_null($fileSize)) {
                #        return $fileSize;
                # }
                return $this->getFileSizeNative($filename);
        }
````

**Comment by hoorna** [comment]
@karlitschek

Hmmm ....

A few weeks ago I placed this question consciously on github. I have chosen for github because I thougth the forum is not able to answer my question.

On github you responded (weeks ago): place the question on the forum and/or on the developers mailinglist.

So I did. I first tried the forum, but the forum responded (as I had expected): you have to place this question on github or on the developers mailinglist.

So my next step was to do a registration on the developers mailinglist and place the question there. After some discussion, they said yesterday: place the question on github.

So .... today I am back on github where I started ..... and now you say go to the forum. Although I am very patient person, I hope you understand that I am a little bit disappointed.

Also ..... today you stated that the issue is specific for MY Synology. I think you are right, it is specific for Synology, but not only MINE. It is specific for all Synology DiskStations ...... and there are thousands and thousands of users with a Synology DiskStation.

I hope it is possible to discuss the issue with each other ánd I hope there is coming up an answer on my questions which I think they are reasonable.

**Comment by hoorna** [comment]
@cyberb

I am sorry and feeling stupid, but .... where can I find the php-file in my owncloud directory and what should I type in the line to comment it out.
Sorry but I am not as handy as you might think. ;-)

**Comment by cyberb** [comment]
File is here:
[owncloud]/lib/private/largefilehelper.php

Find using vim or nano the following text: 
public function getFileSize

Comment by adding hash symbol (#) the lines around getFileSizeViaExec, so it looks like in my previous comment.

**Comment by RealRancor** [comment]
Good to know that snipped. From a first look it might be even not needed to modify the file if the PHP curl module is installed?

@hoorna Try to install the PHP curl package. It depends on your OS but its called php5-curl or php-curl on most distros.

**Comment by hoorna** [comment]
Hi,

@RealRancor
Sorry for my late reply. The PHP curl module was already installed. See the attached image from phpinfo.
What should I do now?

![schermafdruk 2015-09-20 19 03 28](https://cloud.githubusercontent.com/assets/7532234/9981901/9db795fe-5fca-11e5-803d-c41486e4f0c0.png)

**Comment by RealRancor** [comment]
@hoorna Just stumbled over this again make sure:

1. cURL is enabled for your command line

To check this run ```php -i | grep -i curl`` instead of using a phpinfo.php, the latter is just showing the loaded modules within your webserver

2. Make sure no open_basedir is set. Run:

``php -i | grep open_basedir``

which should show:

``open_basedir => no value => no value``

**Comment by lsmith77** [comment]
For the record I also ran into this issue.

I have open_basedir restrictions enabled but did allow ``/volume1/owncloud`` (aka the directory in which the files live) .. commenting the above noted code did fix things .. lets see if it does the reindex properly
