### ISSUE TITLE
Too difficult to see and use the razor thin scrollbar when the right sidebar is out

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#18990]
![scrollbar](https://cloud.githubusercontent.com/assets/323220/9834524/2c5aed6a-59bd-11e5-8f06-3b81e7e344d9.png)

I'm not sure if it's because it's still wip or not, but at least it's tracked.

**Comment by jancborchardt** [comment]
This is because at some point the sidebar has to overlay the content rather than move it to the left. The scrollbar is not razor thin, it’s below the sidebar. Having it otherwise would squish the content in very strange ways.

Hence I’d close this.
