### ISSUE TITLE
Missing shadow on "new" dropdown on all of Microsoft's browsers

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#18992]
![border](https://cloud.githubusercontent.com/assets/323220/9836644/4db73ad6-5a21-11e5-806e-71a5561bdd77.png)

@jancborchardt

**Comment by karlitschek** [comment]
clearly a bug. this looked correct in the original PR as far as I remember.

**Comment by nickvergessen** [comment]
We don't have a border anymore, only shadow.

**Comment by oparoz** [comment]
Yep and it's missing

**Comment by PVince81** [comment]
IE doesn't support drop shadow AFAIK, need a fallback

**Comment by oparoz** [comment]
:S That will probably require a PNG in a container...

**Comment by PVince81** [comment]
Hmm, no. Looks like IE >= 9 should support it: http://caniuse.com/#feat=css-boxshadow

**Comment by PVince81** [comment]
Wait a minute, I don't see a shadow in Chrome either on master. I think we removed it completely ? Or did you mean the button's background color ?

**Comment by nickvergessen** [comment]
works for me on chrome:
![bildschirmfoto vom 2015-10-07 12 58 32](https://cloud.githubusercontent.com/assets/213943/10335724/2b82a61e-6cf3-11e5-9f9c-f18b69c96ef6.png)

**Comment by PVince81** [comment]
Ah sorry. I thought the button, you mean the dropdown. Need more :coffee: 

The dropdown uses drop shadow, maybe in IE the CSS rules order is different for some reason.

**Comment by PVince81** [comment]
Turns out that "drop shadow" != "box shadow" ...

**Comment by PVince81** [comment]
The drop shadow covers the box and also the arrow. But box shadow can only handle the box without the arrow...

**Comment by PVince81** [comment]
and IE's DropShadow filter doesn't have the same properties, which means it will never look the same.
I suggest to go with a simple border.

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/19630 (border instead of shadow)

**Comment by oparoz** [comment]
Approved

**Comment by davitol** [comment]
better than before, but, i'm not sure if it is good enough :speak_no_evil: 
![screen shot 2015-10-08 at 13 54 11](https://cloud.githubusercontent.com/assets/10596560/10365506/3058eaf0-6dc4-11e5-8ff9-f9ce31e7d73b.png)
