### ISSUE TITLE
GPG signing key for Ubuntu repository at OpenSuSE build service not available

### ISSUE THREAD

**Issue by moritzheiber** [owncloud/core#18995]
The signing key for the Ubuntu repository on OpenSuSE's build service has expired. This has been going on for a couple of weeks actually. Unfortunately, the repository and all the packages have been signed with the expired key .. ?

Running `apt-get update`:
```
[...]
W: GPG error: http://download.opensuse.org  Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1AEB1FC2795FB238
[...]
```

This is the key I have in the system's keyring:
```
pub   1024D/BA684223 2012-02-08 [expires: 2017-04-19]
uid                  isv:ownCloud OBS Project <isv:ownCloud@build.opensuse.org>
```

The key I downloaded and imported: http://download.opensuse.org/repositories/isv:ownCloud:community/xUbuntu_14.04/Release.key

(as indicated [on the build service website](https://software.opensuse.org/download/package?project=isv:ownCloud:community&package=owncloud)).

The key doesn't seem to be available anywhere (and shouldn't be since it is expired):
```
$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1AEB1FC2795FB238
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.fp1vXuenVG --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/brightbox-ruby-ng.gpg --keyserver keyserver.ubuntu.com --recv-keys 1AEB1FC2795FB238
gpg: requesting key 795FB238 from hkp server keyserver.ubuntu.com
gpgkeys: key 1AEB1FC2795FB238 not found on keyserver
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
```

**Comment by RealRancor** [comment]
Hi,

please post the output of:

```apt-cache policy | grep download.opensuse```

**Comment by karlitschek** [comment]
@jnweiger

**Comment by moritzheiber** [comment]
@RealRancor Nice catch, thank you! I was indeed having another build service repository lying around which was causing this issue. Apologies for the noise!

**Comment by jnweiger** [comment]
I just double checked, key 1024D/BA684223 from isv:ownCloud:community expires 2017-04-19
