### ISSUE TITLE
100% CPU usage - strace gives files/Notes ENOENT (No such file or directory)

### ISSUE THREAD

**Issue by Leryan** [owncloud/core#19009]
Hi,

We have a problem with ownCloud 8.1.1, all processes consum 100%, and strace -p <pid> gives that:

```
...
access("/var/www/html/owncloud/data/c45e9390-ac9b-102f-8e6d-53d67d2d0954/files/Notes (2)", F_OK) = -1 ENOENT (No such file or directory)
...
```

It loops forever with that line. I could paste gigabytes of this line if it was in a logfile.

I disabled `ownnote` app, restarted apache, no changes.

**Comment by LukasReschke** [comment]
https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version

**Comment by Leryan** [comment]
Well, we had something like 50000 rows of a strange share `Notes (2)`. Dropped them:

```sql
delete from oc_share where file_target like '/Notes (2)';
```

**Comment by LukasReschke** [comment]
@icewind1991
