### ISSUE TITLE
Need to click Shared by link to update file expiration?

### ISSUE THREAD

**Issue by zVerdomorez** [owncloud/core#19005]
I have set folder expire in 3 day ago, but file and folder are show me that folder is still shared.

![123456456](https://cloud.githubusercontent.com/assets/14266988/9840677/fed25f78-5abf-11e5-9659-9f96ed3aa2a9.jpg)

Until I have click on Shared by Link then go back to All File. Everything is ok. 

![121212](https://cloud.githubusercontent.com/assets/14266988/9840706/6d93de96-5ac0-11e5-80e0-2623d967a7fd.jpg)

**Comment by karlitschek** [comment]
This is a known limitation. the share expires but the icon currently doesn't change.

**Comment by zVerdomorez** [comment]
@karlitschek Thank you. Is it possible to run this java script once a day? I can't find js file when click "Shared by link"

**Comment by zVerdomorez** [comment]
I have write cronjob run once a day.and Yeah!

$query = "DELETE FROM `oc_share` WHERE expiration < now()";

**Comment by PVince81** [comment]
9.0 will come with a background job that does just that.

CC @rullzer

**Comment by rullzer** [comment]
Actually it is even better. Now that we use the OCS Share API if we find shares during fetching that are expired we delete them.
