### ISSUE TITLE
Grey colors in the sidebar very hard to read 

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#19016]
The new grey colors in the side bar are really hard to read. They may look fancier but besides this I think they decrease UX. At least I _really_ do prefer the previous 8.0 ones…

The following pictures are from about 80cm distance from a 27' monitor with 2560x1440 pixel.

Before (8.0): 

![photo-2015-09-14-15-23-31_2610](https://cloud.githubusercontent.com/assets/878997/9850726/d124cc7a-5af4-11e5-8daa-19e6ec2b2a9e.png)

After (master):
![photo-2015-09-14-15-21-22_2609](https://cloud.githubusercontent.com/assets/878997/9850750/0387b182-5af5-11e5-84c4-9f6db8ece597.png)

<hr/>

cc @jancborchardt

**Comment by PVince81** [comment]
@LukasReschke you can also try and reduce the brightness of the ceiling ? :wink:

**Comment by jancborchardt** [comment]
Lol @PVince81 … fix at https://github.com/owncloud/core/pull/19055 ;)

**Comment by LukasReschke** [comment]
Can confirm, working in a cage works. Let's add this to our documentation ;)
