### ISSUE TITLE
Turkish character error

### ISSUE THREAD

**Issue by MtaTech** [owncloud/core#19015]
vers. ; 8.1.2
Php : 5.4
![ownerror](https://cloud.githubusercontent.com/assets/14275511/9850497/9e1469a6-5afb-11e5-8283-9019e5e34797.JPG)

**Comment by DeepDiver1975** [comment]
Thanks a lot for reporting issues back to us!

We need some more information to properly support you with your issue!

Can I ask you to follow our guidelines for submitting bugs as described here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

Thanks a lot!

**Comment by DeepDiver1975** [comment]
please open a new issue with all necessary information about the issue - thx
