### ISSUE TITLE
allow user to create multiple File drop location

### ISSUE THREAD

**Issue by yannick-b** [owncloud/core#19025]
The new File drop issue is great. I would event better is 1 user could create more than one file drop location.

**Comment by karlitschek** [comment]
What feature do you mean exactly?

**Comment by yannick-b** [comment]
The app "files_drop" allows user to create 1 file upload url to 1 folder. It would be great if a user could create more than one.

**Comment by karlitschek** [comment]
So this is not part of the normal community edition. I assume that you ask you contact person at ownCloud Inc. for that.
