### ISSUE TITLE
Feature request: Files/directory list should scroll automatically on drag&drop

### ISSUE THREAD

**Issue by africanforest** [owncloud/core#19027]
It would be nice, if the list of directories and files (files module) would scroll automatically according to the direction in which directories or files are dragged, in order to be able to drop them easily to the desired place.
Currently, when a file or directory is dragged beyond the visible window frame, nothing happens,  no scrolling of the list takes place as expected. Only sometimes, after some weird movement of the mouse, some minimal scrolling is perceivable.
OwnCloud 8.1.1, Macbook, OS Yoshemite, Firefox 40.0.3. Can't tell anything about Safari, because it doesn't show anything.
[Sorry, if this is a dublicate of an already reported issue, in this case i just couldn't find it.]

**Comment by PVince81** [comment]
The funny thing about some tickets that get rarely commented is that when someone do comment on it, someone else will have the same idea on the same day and raise a new ticket. :wink:
This makes it easier for me to find the duplicate.

Here you go: https://github.com/owncloud/core/issues/12329
Have a nice day!

**Comment by africanforest** [comment]
Thanks for the information! 
So it seems we have to wait for that basic functionality until version 9.0 :(

But then... it would be very nice, if the breadcrumb menu would get involved in the drag and drop procedure, so we could drag items even to parent directories in one move! :))

**Comment by PVince81** [comment]
@africanforest in that case you might want to subscribe here: https://github.com/owncloud/core/issues/8570

**Comment by africanforest** [comment]
Thanks Vincent!
