### ISSUE TITLE
Smashbox test_basicSync failing on master

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#19031]
Just setup master (4dc1ab0a5ead610b2f90aece3454a0deb5b76c5a)

Run smashbox test_basicSync:

```
± % bin/smash -a lib/test_basicSync.py                                                                                                     !10205
SUMMARY:smash.:runid: 150914-213433
SUMMARY:smash.:URL: http://test:***@127.0.0.1/owncloud/remote.php/webdav/
SUMMARY:smash.:Running iteration 1
SUMMARY:smash.:running lib/test_basicSync.py in /home/vincent/work/smashdir/test_basicSync as test testset #0 {'basicSync_filesizeKB': 1, 'basicSync_rmLocalStateDB': False}
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
md5sum: /home/vincent/work/smashdir/test_basicSync/loser/TEST_FILE_MODIFIED_WINNER.datmd5sum: /home/vincent/work/smashdir/test_basicSync/checker/TEST_FILE_MODIFIED_WINNER.dat: No such file or directory
: No such file or directory
2015-09-14 21:34:50,688 - ERROR - checker - inconsistent md5 of /home/vincent/work/smashdir/test_basicSync/checker/TEST_FILE_MODIFIED_WINNER.dat: expected cac0c3f51680222f14025641074e35fa, got NO_CHECKSUM_ERROR error_check(actual_md5 == md5, "inconsistent md5 of %s: expected %s, got %s"%(fn,md5,actual_md5)) failed in expect_content() ["/home/vincent/work/workspace/smashbox/lib/test_basicSync.py" at line 61]
2015-09-14 21:34:50,694 - ERROR - loser - inconsistent md5 of /home/vincent/work/smashdir/test_basicSync/loser/TEST_FILE_MODIFIED_WINNER.dat: expected cac0c3f51680222f14025641074e35fa, got NO_CHECKSUM_ERROR error_check(actual_md5 == md5, "inconsistent md5 of %s: expected %s, got %s"%(fn,md5,actual_md5)) failed in expect_content() ["/home/vincent/work/workspace/smashbox/lib/test_basicSync.py" at line 61]
2015-09-14 21:34:50,703 - ERROR - creator - inconsistent md5 of /home/vincent/work/smashdir/test_basicSync/creator/TEST_FILE_MODIFIED_WINNER.dat: expected cac0c3f51680222f14025641074e35fa, got 88bb69a5d5e02ec7af5f68d82feb1f1d error_check(actual_md5 == md5, "inconsistent md5 of %s: expected %s, got %s"%(fn,md5,actual_md5)) failed in expect_content() ["/home/vincent/work/workspace/smashbox/lib/test_basicSync.py" at line 61]
2015-09-14 21:34:51,687 - ERROR - loser - 1 error(s) reported
2015-09-14 21:34:51,689 - ERROR - creator - 1 error(s) reported
2015-09-14 21:34:51,689 - ERROR - checker - 1 error(s) reported
CRITICAL:smash.:Aborting run -- non-zero exit code (2)
```

Anyone fancies a bisect ?

@nickvergessen @DeepDiver1975 @icewind1991

**Comment by DeepDiver1975** [comment]
not only basic sync:

https://ci.owncloud.org/job/smashbox-on-docker-daily-master/

![bildschirmfoto von 2015-09-14 21-41-07](https://cloud.githubusercontent.com/assets/1005065/9859931/546af5c6-5b29-11e5-9364-b4ab7a06b9d9.png)

**Comment by PVince81** [comment]
Argh.

I'm already bisecting test_basicSync now.

**Comment by PVince81** [comment]
The bisect pointed to this commit that enables transactional locking by default: https://github.com/owncloud/core/pull/18777
Possibly related to the DB-based locking.

More to try:
- [ ] try smashbox test with locking disabled on master
- [ ] try smashbox with redis instead of DB

**Comment by PVince81** [comment]
Setting to critical as it's a regression and affects syncing consistency.

@icewind1991 can you have a look ?

**Comment by PVince81** [comment]
Also fails with redis, so it's a general issue with locking.

**Comment by nickvergessen** [comment]
basicSync is always the worst test to use for debugging because it does everything in one step.
I can take this over

**Comment by PVince81** [comment]
Feel free to take over this and dig deeper. The bisect is done and it's a locking issue.

**Comment by nickvergessen** [comment]
Tested the failing stuff locally with DB locking:

Test | Result
---- | ------
shareFile | :white_check_mark: 
sharePermissions | :white_check_mark: 
uploadFiles | :x:  
basicSync | :x:

**Comment by icewind1991** [comment]
I dont get any error while running smashbox, but it seems to freeze after a while, it doesn't seem to do any file operation from what I can tell from the [lock log](https://github.com/icewind1991/locktools) but I can see a few php-fpm processes with high cpu usage

**Comment by DeepDiver1975** [comment]
timeout in the fpm setup???

**Comment by icewind1991** [comment]
Looking at the db it seems that locks are still being modified but without going trough the storage layer (where my log works)

**Comment by nickvergessen** [comment]
well it's syncing

It's also not getting stuck here. The tests just take some time because they transfer GBs of Data

**Comment by icewind1991** [comment]
If it as transfering a lot of files it would show that in the lock log and if it was a single big file it wouldn't be changing locks.

Also it seems to be getting stuck no matter which tests I run, I don't remember `sharePermissions` taking a lot of time

**Comment by nickvergessen** [comment]
sharePermissions passes here, as per above. Only basicSync and uploadFiles fail

**Comment by PVince81** [comment]
I travelled far back in time and saw that it also fails on v8.1.1 with locking enabled (redis).
v8.1.0 seems to pass.

**Comment by PVince81** [comment]
False alarm, forgot to enable php5-redis ...
I'll redo the bisect with redis locking enabled.

**Comment by PVince81** [comment]
And here we go:
This is the breaking commit: d979e54030b0069572affe173c06680597cc831d.
It comes from the DB locking PR: https://github.com/owncloud/core/pull/17662

Note: sometimes you need to run the smashbox test several times to make it fail...

**Comment by PVince81** [comment]
Hmmm, but I was testing with redis locking. That doesn't make sense, as the commit is for DB locking.

**Comment by icewind1991** [comment]
#19098 fixes the problem with db locking for me

**Comment by PVince81** [comment]
@icewind1991 pointed out that there was a bug where DB locking was always used even when redis was selected... so this invalidates what I observed in the bisect.

I'll check out that PR.

**Comment by PVince81** [comment]
Fixed by https://github.com/owncloud/core/pull/19098
