### ISSUE TITLE
correct logging levels in config.sample.php

### ISSUE THREAD

**Issue by carlaschroder** [owncloud/core#19035]
Hello, on the ownCloud Admin page there are five loggings levels, but in config.sample.php there are only four: 0 = Debug, 1 = Info, 2 = Warning, 3 = Error. Shouldn't there also be 4 = Fatal?

**Comment by nickvergessen** [comment]
yes

**Comment by carlaschroder** [comment]
thanks @nickvergessen

**Comment by carlaschroder** [comment]
https://github.com/owncloud/core/pull/19059

**Comment by nickvergessen** [comment]
Let's keep this open, until the fix is merged ;)
