### ISSUE TITLE
appConfig values should have proper defaults

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#19032]
As raised in #18950
I created this issue to keep track and to discuss the path we want to walk.

Currently there are multiple places where appConfigs getValue is called. If multiple places call the same value but with different defaults this can lead to confusing behaviour.

There are two possible approaches here https://github.com/owncloud/core/pull/18950#issuecomment-140163016 and https://github.com/owncloud/core/pull/18950#issuecomment-140165854 Both result in only a single code path for calls to config values.

**Comment by nickvergessen** [comment]
Well apps have update.php and install.php
They can call set there and then use `get` without default values? :P

**Comment by DeepDiver1975** [comment]
> and #18950 (comment)

my comment still stays valid - I suggest to simply open PRs to fix the explicit issues - no need for a global discussion - THX

**Comment by DeepDiver1975** [comment]
@rullzer can I ask you to compile an explicit list of defaults which are used wrong - THX

**Comment by rullzer** [comment]
@DeepDiver1975 Just to be claer, we want to make sure that for each config variable there is only one place that calls getValue. All the other stuff will use some wrapper class to make sure the default is always the same right?

I'll add it to the TODO list.

**Comment by DeepDiver1975** [comment]
> I'll add it to the TODO list.

THX - just to be clear - I see only a need to fix explicit missusage of config parameters with different default values.
