### ISSUE TITLE
"Other" value in users quota is replaced by a "B".

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#19038]
### Steps to reproduce

As admin user do:
1. Go to users management.
2. Create a user.
3. Click in quota dropdown, choose other.
4. Don't introduce any value and click out of the textbox.
5. Open again the quota dropdown.

### Expected behaviour
Default quota is kept, and when you open the dropdown the last value is other.

### Actual behaviour
When you open the dropdown other is changed by B.

![screen shot 2015-09-15 at 10 53 44](https://cloud.githubusercontent.com/assets/9048796/9872228/2fff765c-5b98-11e5-9d55-072ce20ffd19.png)

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
master 
{"installed":true,"maintenance":false,"version":"8.2.0.4","versionstring":"8.2 pre alpha","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in community edition..

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Chrome. Firefox.

**Comment by karlitschek** [comment]
I see that you are using the spanish translations. Does this problem also exists if you switch to english :-)
8.2 is not fully translated yet.

**Comment by SergioBertolinSG** [comment]
Sorry I forget to put the english screenshot. It is happening as well in english.

![screen shot 2015-09-15 at 13 49 37](https://cloud.githubusercontent.com/assets/9048796/9875701/a930a664-5bb0-11e5-84ad-e361fb35cbe3.png)

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/issues/24664 which has the PR
