### ISSUE TITLE
User removed from ownCloud AD group still has data directory checked

### ISSUE THREAD

**Issue by gig13** [owncloud/core#19045]
### Steps to reproduce
1. Remove a user from an LDAP group that has access to ownCloud
2. Run the ldap cleanup tool (occ)
3. Remove the data directory since it is not cleaned up by occ

### Expected behaviour
The user should not be able to access ownCloud since they were removed from the group that provides access. The user still remains in AD for other services -- still in the organization.

### Actual behaviour
After removing them from the AD group providing ownCloud access, removing the user's data directory and running the occ ldap cleanup the log still shows owncloud trying to access the user's data directory.

```
{"app":"PHP","message":"filemtime(): stat failed for
\/path1\/abc\/owncloud\/. at
\/var\/www\/html\/owncloud-enterprise\/lib\/private\/files\/storage\/local.php#134","level":3,"time":"2015-09-10T16:00:44-06:00"}
{"app":"PHP","message":"filemtime(): stat failed for
\/path1\/abc\/owncloud\/. at
\/var\/www\/html\/owncloud-enterprise\/lib\/private\/files\/storage\/local.php#134","level":3,"time":"2015-09-10T16:00:57-06:00"} 
```

### Server configuration
**Operating system**: RHEL 6

**Web server:** Apache

**Database:** Oracle

**PHP version:** 5.4.40

**ownCloud version:** 7.0.8

**Updated from an older ownCloud or fresh install:** Updated

**List of activated apps:** See config report https://s3.owncloud.com/owncloud/index.php/apps/files?dir=%2FShared%2Fowncloud%2Fsupport%2Fgithub-issues%2Fcore%2F18701

**The content of config/config.php:**

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration
See config report

@MorrisJobke @schiesbn

**Comment by gig13** [comment]
@bboule @blizzz 
Can anyone look at this?

**Comment by blizzz** [comment]
Cleanup works only against **deleted** users on LDAP by now.

**Comment by gig13** [comment]
Feedback from @cdamken thanks

Run the insert command or as a script the following
```
mysql -u root --password=$2 -e "insert into owncloud.oc_preferences (userid, appid, configkey, configvalue) VALUES ('$1', 'user_ldap', 'isDeleted', '1')"
sudo -u www-data php occ user:delete $1

sh ldap-force-delete username db-root-password
```

**Comment by bboule** [comment]
@gig13 closing as it seems no code changes needed perhaps some documentation needed?

**Comment by gig13** [comment]
I added a Solution for SF 3808
