### ISSUE TITLE
Ldap Group Shares are not honored

### ISSUE THREAD

**Issue by Yamakasi** [owncloud/core#19040]
Hi,
When I share a folder with a Ldap-group where 2 users are in, the non-owner of these files cannot see anything, or the shared folder at all.

When I type the ldap group it's shown in the "dropdown" while sharing.

Is this a bug ?

Thanks,

Matt

**Comment by karlitschek** [comment]
@blizzz what do you think?

**Comment by Yamakasi** [comment]
Any news on this ? I'm kinda stuck here.

**Comment by blizzz** [comment]
@Yamakasi can you please provide more information using the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md)? Thank You!

**Comment by Yamakasi** [comment]
### Steps to reproduce
1. Add a user to GROUP1 in ldap
2. Add a folder in owncloud and share this with GROUP1 (comes from ldap)
3. Try to locate the folder as th groupuser in ownCloud, and it's not shown.

### Expected behaviour
We should see the shared folder as we are a user in the group where the OwnCloud folder is shared with

### Actual behaviour
I don' t see the folder

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Server version: Apache/2.4.7 (Ubuntu)

**Database:** Percona 5.6

**PHP version:** PHP 5.5.9-1ubuntu4.11

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**

**List of activated apps:**


Enabled:
 - activity: 2.0.2
 - direct_menu: 0.3
 - files: 1.1.10
 - files_antivirus: 0.7.0.1
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - galleryplus: 13.0.0
 - news: 6.0.3
 - ownnote: 1.05
 - passwords: 8.0.13
 - provisioning_api: 0.2
 - storagecharts2: 2.6.1
 - templateeditor: 0.1
 - updater: 0.6
 - user_ldap: 0.6.1
Disabled:
 - documents
 - encryption
 - external
 - files_external
 - files_mv
 - files_texteditor
 - gallery
 - mail
 - oc-custom-tags
 - oclife
 - user_external
 - user_webdavauth
**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system --public
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
ldap

#### LDAP configuration (delete this part if not used)

+-------------------------------+----------------------------------------------------------+
| Configuration                 |                                                          |
+-------------------------------+----------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                        |
| hasPagedResultSupport         |                                                          |
| homeFolderNamingRule          | attr:uid                                                 |
| lastJpegPhotoLookup           | 0                                                        |
| ldapAgentName                 | uid=admin,cn=users,cn=accounts,dc=domain,dc=local |
| ldapAgentPassword             | ***                                                      |
| ldapAttributesForGroupSearch  |                                                          |
| ldapAttributesForUserSearch   |                                                          |
| ldapBackupHost                |                                                          |
| ldapBackupPort                |                                                          |
| ldapBase                      | cn=users,cn=accounts,dc=domain,dc=local           |
| ldapBaseGroups                | cn=groups,cn=accounts,dc=domain,dc=local          |
| ldapBaseUsers                 | cn=users,cn=accounts,dc=domain,dc=local           |
| ldapCacheTTL                  | 600                                                      |
| ldapConfigurationActive       | 1                                                        |
| ldapEmailAttribute            | mail                                                     |
| ldapExperiencedAdmin          | 0                                                        |
| ldapExpertUUIDGroupAttr       | cn                                                       |
| ldapExpertUUIDUserAttr        | uid                                                      |
| ldapExpertUsernameAttr        | uid                                                      |
| ldapGroupDisplayName          | cn                                                       |
| ldapGroupFilter               | (|(objectClass=posixGroup))                              |
| ldapGroupFilterGroups         |                                                          |
| ldapGroupFilterMode           | 1                                                        |
| ldapGroupFilterObjectclass    |                                                          |
| ldapGroupMemberAssocAttr      | uniqueMember                                             |
| ldapHost                      | ldap.domain.local                                    |
| ldapIgnoreNamingRules         |                                                          |
| ldapLoginFilter               | (&(|(objectclass=person))(uid=%uid))                     |
| ldapLoginFilterAttributes     |                                                          |
| ldapLoginFilterEmail          | 0                                                        |
| ldapLoginFilterMode           | 0                                                        |
| ldapLoginFilterUsername       | 1                                                        |
| ldapNestedGroups              | 0                                                        |
| ldapNoCase                    | 0                                                        |
| ldapOverrideMainServer        |                                                          |
| ldapPagingSize                | 500                                                      |
| ldapPort                      | 389                                                      |
| ldapQuotaAttribute            |                                                          |
| ldapQuotaDefault              |                                                          |
| ldapTLS                       | 0                                                        |
| ldapUserDisplayName           | displayname                                              |
| ldapUserFilter                | (|(objectclass=person))                                  |
| ldapUserFilterGroups          |                                                          |
| ldapUserFilterMode            | 0                                                        |
| ldapUserFilterObjectclass     | person                                                   |
| ldapUuidGroupAttribute        | auto                                                     |
| ldapUuidUserAttribute         | auto                                                     |
| turnOffCertCheck              | 0                                                        |
| useMemberOfToDetectMembership | 1                     
```

### Client configuration
**Browser:** Firefox

**Operating system:** Windows 10/OSX 10.10.5/Ubuntu 14.04

**Comment by Yamakasi** [comment]
@blizzz is this enough info ?

**Comment by blizzz** [comment]
@Yamakasi looks sufficient, will know better when i will came around to it, probably start of next week.

**Comment by Yamakasi** [comment]
@blizzz OK, would be nice to know... if I need to check some things, let me know! thanks!

**Comment by blizzz** [comment]
@Yamakasi which ownCloud version? I assume 8.1.x? If so, what is x in your case?

I fail to reproduce your error, it works for me.

Are the group associations configured correctly, i.e. are the users's groups shown on the Users page? Or for that specific user on his personal page? If not,  you may want to try to disable useMemberOfToDetectMembership via command line (as web user!):

```./occ ldap:set-config "" useMemberOfToDetectMembership 0```

**Comment by skoenen** [comment]
Hi there,

i have the same problem.
The command given above solves at first that.
What could be the root cause?

Has the ldap server to be configured? (Is it missing memberOf-Support)
Or is it a bug in owncloud?

I think the workaround, to not use memberOf, slows down some stuff,right?

**Comment by Yamakasi** [comment]
@blizzz sorry for my very late response, busy time and I set this on a sidepath as I was not able to spend time on it.

It's still the same, I updated to 8.2.1 and also the config setting doesn't fix it. I don't see the users added to the owncloud group also atm when they are @ ldap.

**Comment by Yamakasi** [comment]
OK this is fixed now :)

**Comment by flypenguin** [comment]
if someone is still reading here - I have the very same problem as well. 

when I go to the "users" page, I see a UUID under the "username" column, but the users have the correct groups assigned in the "groups" column. 

yet, when I share to a group the group members (except me, of course) don't see anything shared at all. that is a bit annoying, and I have no idea why. sharing with the users directly works.

any hints here?

**Comment by bkoffler** [comment]
Hi - following up on this item - i see that it is marked as closed a few years back but i am with flypenguin - this issue continues to occur. I am able to share with custom groups and groups created within OC - i can share directly as well. However, the groups created in openldap, while appearing in OC and assigned properly to users, do not actually allow for sharing. 

Thoughts on this?
