### ISSUE TITLE
[Ubuntu Packaging] Change dependecy on owncloud-config-apache from depend to recommends

### ISSUE THREAD

**Issue by janhenke** [owncloud/core#19050]
The ```owncloud``` meta package currently defines a dependency on ```owncloud-config-apache```. This makes it hard to use an alternative httpd like nginx instead of apache on the server.

Please lower the dependency of the meta package from "depend" to "recommend". With the latter, the ```owncloud-config-apache``` will still be installed by default, but it can be removed by advanced users without having to remove the ```owncloud``` package.

**Comment by karlitschek** [comment]
@jnweiger

**Comment by jnweiger** [comment]
@janhenke can we make sure that a recommended package is considered for installation in every default setting. I know that with RPM installers, this is not guaranteed. With e.g. zypper, sysadmins can configure the installer to either include or ignore Recommends.

**Comment by janhenke** [comment]
You can configure you apt to not install recommended packages, but that is a non-default settings. Both Debian and Ubuntu always install recommended packages along the dependencies in their default apt configurations.

**Comment by janhenke** [comment]
I might add, in the Debian world there is just apt as the basic package management tool. All other tools (aptitude, synpatic, ...) are just front-ends for apt. So the apt default is always the system default. And as mentioned, apt always defaults to install recommended packages as well.

**Comment by jnweiger** [comment]
Submitted as https://build.opensuse.org/package/rdiff/isv:ownCloud:community:8.1:testing/owncloud?linkrev=base&rev=58
Please check out 
https://software.opensuse.org/download.html?project=isv%3AownCloud%3Acommunity%3A8.1%3Atesting&package=owncloud

**Comment by janhenke** [comment]
There is a bug with the repository. ```owncloud```, ```owncloud-server``` and ```owncloud-config-apache``` are available in the new version 8.1.3-13.1, but the rest of the owncloud packages do not have corresponding updates and remain at 8.1.1-1, breaking the installation. Can you check that please?

**Comment by jnweiger** [comment]
@janhenke That is a new topic. Please open a new issue. thanks. I've seen that on the [users] list to, but it works well for me. @davitol fyi

**Comment by janhenke** [comment]
The issue has already been reported as #19102, I have added a comment on that issue.

**Comment by janhenke** [comment]
@jnweiger I have added the mentioned testing repository, but it does not provide a newer version than stable? I see nothing I could test.

**Comment by davitol** [comment]
I've just tried and it works well for me too :eyes:

**Comment by jnweiger** [comment]
@janhenke Version numbers are the same, Build release numbers may or may not differ. Probably the build release number in testing is currently lower. 
In that case you need to remove both the main repo and any installed owncloud packages first.

**Comment by janhenke** [comment]
Hmm, I cannot intentionally break the installation for testing purpose right now, so removing the currently installed packages is unfortunately not an option. But it seems to work for @davitol.

Can you bump the Debian version? I.e. make it 8.1.3-13.4 or so?

**Comment by jnweiger** [comment]
you can try to specify an exact version and build release like this:
apt-get install owncloud-server=8.1.3-5.1 owncloud=8.1.3-5.1
(or ...-6.1 or so, by the time you try that)

but please don't break your production installation, just because I say so :-)

**Comment by janhenke** [comment]
Well we have the feedback from @davitol, so it seems to work. Thanks for making it possible to use your own server configuration. I will wait for the next regular update then to make use of it. So I close this one as solved. If there are any future issues I would open a new issue for that.

**Comment by francwalter** [comment]
I didn't understand 100% this.
Does it mean best is to wait till all packages are updated?
Yet I have 3 new packages in aptitude: 
owncloud
owncloud-server
owncloud-config-apache
all in version 8.1.3-13.1
Installing them will break a lot of 20 other packages, aptitude propose to uninstall them. 
I wont do that ;)
So just wait will solve the issue?
Thank

**Comment by jnweiger** [comment]
@janhenke Mint 17 has 
<pre>
apt-config dump | grep :Install
 APT::Install-Recommends "false";
 APT::Install-Suggests "0";
</pre>

**Comment by janhenke** [comment]
Another questionable decision by Mint. So you are breaking it for either Ubuntu user or Mint users. Since the packaging is for Ubuntu in the first place, I would rather see this based on the sane defaults of Ubuntu than Mint.

Especially since Ubuntu Server is quite popular, but I hardly hear about serious Mint usage in the server area.

**Comment by jnweiger** [comment]
@felixboehm FYI regarding dependency cleanup.
