### ISSUE TITLE
Deactivate sort order logic when in multiselect

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#19056]
When you select multiple files, the sort order arrow is still next to the »2 folders, 1 file« text. Also, clicking that text will change the sort order and remove the selection.

This should not happen – when in multiselect, the sort order switcher in the header should be fully disabled and the sort order arrow invisible.

@MorrisJobke @schiesbn @rullzer

**Comment by PVince81** [comment]
It should be possible to do this with pure CSS. When selection mode is enabled, an extra class is set on the header (forgot which one).

**Comment by jancborchardt** [comment]
@PVince81 not entirely, as:

> clicking that text will change the sort order and remove the selection.

So there’s still logic left.

**Comment by PVince81** [comment]
Hmm, right.

**Comment by MorrisJobke** [comment]
@PVince81 Is this now fixed or is something left? - #19310 is merged now ;)

**Comment by PVince81** [comment]
It's fixed
