### ISSUE TITLE
Controls bar width overlays the scrollbar

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#19057]
The controls bar width does not take into account the scrollbar anymore:
![capture du 2015-09-15 18-07-42](https://cloud.githubusercontent.com/assets/925062/9882407/c1ca5dc2-5bd4-11e5-821b-bd92094e9211.png)

@PVince81 @MorrisJobke

**Comment by PVince81** [comment]
Or is it because we have two scrollbars when the sidebar is present ?

**Comment by jancborchardt** [comment]
Then the logic should still be:
`width of controls bar = width of #app-content minus width of scrollbar`

**Comment by PVince81** [comment]
`... minus width of sidebar if visible`

**Comment by PVince81** [comment]
From what I see in the code and while debugging, it does call `getScrollBarWidth()`.
Maybe the recent styling changes have introduced margins which might in some case affect the width measurements ?

I also see that `getScrollbarWidth()` is using some weird tricks using a hidden container to measure the scrollbar width, maybe that one was affected too ?

**Comment by jancborchardt** [comment]
@PVince81 I got that getScrollbarWidth code off Stackoverflow as a closed function. ;) No idea why it’s ot working unfortunately, my JS fu ends there.

**Comment by PVince81** [comment]
Ok, so next step is to debug the resizing code and very if the pixel values of each matches what is actually on screen, to find which element might be "lying" about its size.

**Comment by PVince81** [comment]
It's not the controls bar, it's the multiselect bar. Its calculation is in a different location and wasn't adjusted.

**Comment by cmonteroluque** [comment]
This issue will fall off 8.2 if not resolved by 6 Oct

**Comment by MorrisJobke** [comment]
Fix is in #19524

**Comment by PVince81** [comment]
better fix here https://github.com/owncloud/core/pull/19539
