### ISSUE TITLE
If thumbnail then large preview in sidebar

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19054]
A handful of media types are hard-coded inside the isImage() method which decides whether we show a slightly larger preview than the thumbnail or if we show a large preview, filling up the header, if possible.

```
return this.get('mimetype').substr(0, 6) === 'image/'
                || this.get('mimetype') === 'application/postscript'
                || this.get('mimetype') === 'application/illustrator'
                || this.get('mimetype') === 'application/x-photoshop';
```

I think ownCloud can do better. If a thumbnail can be generated in the list view, then there should be a larger preview in the sidebar, so that people can see what it's about without having to launch the slideshow.

**The right sidebar is not a media player, it's a detail view.**

@PVince81 @georgehrke @icewind1991

**Comment by PVince81** [comment]
@jancborchardt

**Comment by schiesbn** [comment]
> If a thumbnail can be generated in the list view, then there should be a larger preview in the sidebar, 

I would also vote for sticking to one size. Looks strange if you navigate through your sidebar ans sometimes you have large previews and sometimes small ones. Also that sometimes the name is next to the icon/preview and sometimes below.
I think we should have a unique behavior with a defined preview area and a defined "information" area which is always at the same position no matter if we have a preview or not and which type of preview we have.

**Comment by jancborchardt** [comment]
@schiesbn so you disagree with @oparoz?

@oparoz the point of the hardcoding is that this:

> If a thumbnail can be generated in the list view, then there should be a larger preview in the sidebar,

will results in big previews shown in the sidebar for stuff like text files – which is pointless. It should only happen for images.

**Comment by oparoz** [comment]
@schiesbn agrees with me I think, but it's true that there will still be 2 sizes since it would be pretty useless to show a large mime icon.

> will results in big previews shown in the sidebar for stuff like text files – which is pointless. It should only happen for images.

I disagree. At 32x32, there is little chance you can tell what the file is about unless the filename is ringing a bell. Now if you have a large text, pdf, office preview, then you know.
That's how all filesystems are doing it. They don't differentiate. If they can show a preview, they do.

**Comment by oparoz** [comment]
We have to remember that this is a details view. If that was a media tab, with meta data, then it would be a different story.

**Comment by schiesbn** [comment]
yes, I basically agree with @oparoz but I would go one step further and have only one size. I like the large previews and we should have it for all file types. If we don't have a preview  I would try to center the mime icon or something like that so that the basic layout stays the same: At the top a defined area for the preview and below the details so that it doesn't jump around while navigating through your files list.

**Comment by oparoz** [comment]
> If we don't have a preview I would try to center the mime icon

I think this could work. Lots of empty space, but it makes it clear we don't have a preview and it doesn't change the layout.

**Comment by schiesbn** [comment]
> I think this could work. Lots of empty space, but it makes it clear we don't have a preview and it doesn't change the layout.

right, and I think we have enough space at the sidebar, so we don't have to worry.

@jancborchardt 
> I think this could work. Lots of empty space, but it makes it clear we don't have a preview and it doesn't change the layout.

Why is it pointless. The same way it is useful to show more content/details of a image with a larger preview it can be useful to show more content of a document by displaying a larger preview.

**Comment by jancborchardt** [comment]
We tried that out, with cropping the image and such. It just looked wrong for pictures. Everything was cropped in strange ways. Unless we do face detection, stuff will not come out right. cc @icewind1991 @owncloud/designers

**Comment by schiesbn** [comment]
> We tried that out, with cropping the image and such. It just looked wrong for pictures.

Hm, I thought that pictures are the file type where we agree that larger previews are a nice feature.

**Comment by oparoz** [comment]
> We tried that out, with cropping the image and such. It just looked wrong for pictures

Yes, we tried cropping pictures, but in this case, we don't touch the standard previews, we just remove the media type detection mechanism and only centre the media type icons when we can't get a preview.

**Comment by jancborchardt** [comment]
So … we end up with giant filetype icons when there is no preview to be generated? That doesn’t look very good.

**Comment by schiesbn** [comment]
> So … we end up with giant filetype icons when there is no preview to be generated? That doesn’t look very good.

Not giant, more or less the same size (depends on some fine tuning) centered at the top with the file info below

**Comment by schiesbn** [comment]
Let my try to show it with a example:

![1](https://cloud.githubusercontent.com/assets/1589737/10022953/d20878ec-614f-11e5-8fa2-f883f40198e8.png)

![2](https://cloud.githubusercontent.com/assets/1589737/10022955/d5f163ce-614f-11e5-95dd-670a7d7ce2d4.png)

Of course this is just some copy&paste with gimp. It probably need some adjustment. Maybe the area for the preview can a bit smaller and maybe we can adjust the mime-type icon size. But the idea should be clear.

**Comment by oparoz** [comment]
I was hoping for some special effects :)

![warhol](https://cloud.githubusercontent.com/assets/323220/10023157/d2ed876a-6150-11e5-8c56-e8e798724754.png)

**Comment by schiesbn** [comment]
@oparoz of course something like this could be also a option.

**Comment by oparoz** [comment]
Nah, I think, we ought to keep it simple :). The icons are SVGs, so there is no rendering issue. As you've said, we just need to find the right size to make it work.

**Comment by jancborchardt** [comment]
Folks, exactly this stuff is what we did not want to have. It just doesn’t look good to put a stupid filetype icon on a pedestal like this. Even with the vertical whitespace removed, it being centered and taking up so much space is ridiculous.

**Comment by oparoz** [comment]
It may be ridiculous, but that's how 98% of file managers do it and what users are used to.

![detail](https://cloud.githubusercontent.com/assets/323220/10027448/43198dc0-6167-11e5-92fe-3790def43922.png)
![](http://appletoolbox.com/wp-content/uploads/2014/12/3-Preview-Pane-Add-Tags.png)

I propose we go with a unique preview mechanism first and see if we can find a better option later.

**Comment by schiesbn** [comment]
@oparoz thanks for the examples

Additionally I want to mention the layout argument once more, because I consider it really important. If you navigate through the file list it is really disturbing if the complete layout changes between different file types. You go to a different file, look back to the sidebar and expect a specific content on a specific place and everything is different. IMHO that's really bad UX.

**Comment by jancborchardt** [comment]
What do @owncloud/designers think?

@schiesbn @oparoz if you think it’s better, then maybe best whip up a prototype PR so we can testdrive it.
