### ISSUE TITLE
Error during update

### ISSUE THREAD

**Issue by arturomj** [owncloud/core#19065]
While I was updating form 8.0 to 8.1 I lost the internet conection and now it shows this problem:

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO oc_activity (activity_id, timestamp, priority, type, user, affecteduser, app, subject, subjectparams, message, messageparams, file, link) SELECT activity_id, timestamp, priority, type, user, affecteduser, app, subject, subjectparams, message, messageparams, file, link FROM __temp__oc_activity': SQLSTATE[HY000]: General error: 10 disk I/O error

**Comment by RealRancor** [comment]
Hi,

such issues are mostly caused by some issues within your database:

https://dba.stackexchange.com/questions/53090/occasional-disk-i-o-errors-in-sqlite

**Comment by MorrisJobke** [comment]
> General error: 10 disk I/O error

I don't think we can do much here.

cc @DeepDiver1975
