### ISSUE TITLE
Group creation from top menu 

### ISSUE THREAD

**Issue by ximbesto** [owncloud/core#19067]
Clean install on centos 6.7 / php 5.4  - installed by yum 
Tested by Firefox  40.0.3 - Windows 10
after adding new group  and refreshing page - nothing saved.

![owncloud-adding new group](https://cloud.githubusercontent.com/assets/11258879/9891253/6320e8ae-5c1a-11e5-8e5f-18ada1b2ad28.jpg)

**Comment by ximbesto** [comment]
Same issue on chrome

**Comment by MorrisJobke** [comment]
This is at least fixed in 8.2 (will be released in ~ 2 weeks)

It's also possible that this was backported to 8.1.4, but I'm not sure.
