### ISSUE TITLE
Opensuse Repository not up to date

### ISSUE THREAD

**Issue by mapaongh** [owncloud/core#19063]
I am using the owncloud repo from opensuse for ubuntu 14.04. 

It seems according to the release notes version 8.1.3 is released.

https://owncloud.org/changelog/

It seems that the repo is not up to date? It is still 8.1.1.

https://build.opensuse.org/package/view_file/isv:ownCloud:community/owncloud/debian.changelog?expand=1

The same happens with 8.1.2.

**Comment by RealRancor** [comment]
8.1.3 is already there:

http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.1/xUbuntu_14.04/all/

You just need to have patience and wait until all builds are finished and the mirrors updated.

**Comment by janhenke** [comment]
This has nothing to do with patience. There must never be such a partial update available on the mirrors. If you did not pay attention, this situation breaks installations.

**Comment by RealRancor** [comment]
What do you mean with partial update?

**Comment by janhenke** [comment]
No, 8.1.3 was not fully available. The repository just had the ```owncloud```, ```owncloud-server``` and ```owncloud-config-apache``` packages with the new version, the rest of the owncloud packages was just available with the old version (8.1.1-1), thus breaking installations on installing this (partial) update.

**Comment by RealRancor** [comment]
@janhenke See my edit above. Those are all packages needed as the packages where merged together back according to @jnweiger

**Comment by janhenke** [comment]
Then it is very poorly documented. None of the package descriptions mentions something like this. (Changelog is not directly visible for third party packages)

An update that just updates a few of the related packages while removing the rest is very suspicious for being a bug. If there is any change in packaging like that it must be properly documented.

**Comment by RealRancor** [comment]
Thats not an issue here. Please read the post of the OP again.

**Comment by jnweiger** [comment]
Packages are there, by now. Communitcation should also have reached those missed the merged packages by now. Closing here.

To me it is still unclear, if the Replaces: / Breaks: configuration can be improved. There were reports that apt-get would abort the update instead of removing any packages. If you can help there, please let me know.
