### ISSUE TITLE
MySQL database error when uploading lots of files

### ISSUE THREAD

**Issue by GrimDemon** [owncloud/core#19068]
Problem appeared few times when I was uploading about 1k JPG files to my OC. It looks like database is overflowed. At the moment I solved the problem by deleting locked files from OC web gui and reauploading them from OC Win client. What is the core of my problem and what can I do to improve muy instance?

```
Fatal	webdav	Exception: {"Message":"Could not obtain lock type 1 on \"\/var\/www\/owncloud\/data\/grimdemon\/files\/Fotki\/20090803_Pobierowo\/IMG_0023.JPG.ocTransferId1217684769.part\".","Code":0,"Trace":"
#0 \/var\/www\/owncloud\/apps\/files_locking\/lib\/lockingwrapper.php(45): OCA\\Files_Locking\\Lock->addLock(1, Resource id #48)\n
#1 \/var\/www\/owncloud\/apps\/files_locking\/lib\/lockingwrapper.php(172): OCA\\Files_Locking\\LockingWrapper->getLock('files\/Fotki\/200...', 1, Resource id #48)\n
#2 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/encryption.php(624): OCA\\Files_Locking\\LockingWrapper->fopen('files\/Fotki\/200...', 'r')\n
#3 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/encryption.php(692): OC\\Files\\Storage\\Wrapper\\Encryption->readFirstBlock('files\/Fotki\/200...')\n
#4 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/encryption.php(722): OC\\Files\\Storage\\Wrapper\\Encryption->getHeader('files\/Fotki\/200...')\n
#5 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/encryption.php(217): OC\\Files\\Storage\\Wrapper\\Encryption->getEncryptionModule('files\/Fotki\/200...')\n
#6 [internal function]: OC\\Files\\Storage\\Wrapper\\Encryption->unlink('files\/Fotki\/200...')\n
#7 \/var\/www\/owncloud\/apps\/files_trashbin\/lib\/storage.php(143): call_user_func_array(Array, Array)\n
#8 \/var\/www\/owncloud\/apps\/files_trashbin\/lib\/storage.php(94): OCA\\Files_Trashbin\\Storage->doDelete('files\/Fotki\/200...', 'unlink')\n
#9 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/file.php(150): OCA\\Files_Trashbin\\Storage->unlink('files\/Fotki\/200...')\n
#10 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/directory.php(113): OC\\Connector\\Sabre\\File->put(Resource id #35)\n
#11 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1053): OC\\Connector\\Sabre\\Directory->createFile('IMG_0023.JPG', Resource id #35)\n
#12 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(513): Sabre\\DAV\\Server->createFile('Fotki\/20090803_...', Resource id #35, NULL)\n
#13 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n
#14 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n
#15 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n
#16 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n
#17 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n
#18 \/var\/www\/owncloud\/remote.php(132): require_once('\/var\/www\/ownclo...')\n
#19 {main}","File":"\/var\/www\/owncloud\/apps\/files_locking\/lib\/lock.php","Line":257}	2015-09-15T19:07:58+00:00
Error	PHP	imagecreatefromjpeg(): gd-jpeg, libjpeg: recoverable error:  at /var/www/owncloud/lib/private/image.php#512	2015-09-15T19:00:54+00:00
Error	PHP	Undefined index: REQUEST_URI at /var/www/owncloud/apps/contacts/appinfo/app.php#35	2015-09-15T19:00:02+00:00
Fatal	webdav	Exception: {"Message":"An exception occurred while executing 'INSERT INTO `oc_filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`encrypted`,`parent`,`path_hash`,`path`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,? FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ? HAVING COUNT(*) = 0' with params [\"3\", \"4\", 1442342936, 1164503, \"b1ce6da250e24df8561d90cf744600d3\", 1442342936, 27, 1, \"90432\", \"eefff64f389363338b9a805791895f13\", \"files\\\/Fotki\\\/20090705_Piknik EC\\\/IMG_1697.JPG\", \"IMG_1697.JPG\", \"4\", \"4\", \"eefff64f389363338b9a805791895f13\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4-eefff64f389363338b9a805791895f13' for key 'fs_storage_path_hash'","Code":0,"Trace":"
#0 \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n
#1 \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(996): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'INSERT INTO `oc...', Array)\n
#2 \/var\/www\/owncloud\/lib\/private\/db\/connection.php(151): Doctrine\\DBAL\\Connection->executeUpdate('INSERT INTO `oc...', Array, Array)\n
#3 \/var\/www\/owncloud\/lib\/private\/db\/adapter.php(93): OC\\DB\\Connection->executeUpdate('INSERT INTO `*P...', Array)\n
#4 \/var\/www\/owncloud\/lib\/private\/db\/connection.php(190): OC\\DB\\Adapter->insertIfNotExist('*PREFIX*filecac...', Array, Array)\n
#5 \/var\/www\/owncloud\/lib\/private\/files\/cache\/cache.php(322): OC\\DB\\Connection->insertIfNotExist('*PREFIX*filecac...', Array, Array)\n
#6 \/var\/www\/owncloud\/lib\/private\/files\/cache\/scanner.php(225): OC\\Files\\Cache\\Cache->put('files\/Fotki\/200...', Array)\n
#7 \/var\/www\/owncloud\/lib\/private\/files\/cache\/scanner.php(188): OC\\Files\\Cache\\Scanner->addToCache('files\/Fotki\/200...', Array, -1)\n
#8 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/file.php(211): OC\\Files\\Cache\\Scanner->scanFile('files\/Fotki\/200...')\n
#9 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/directory.php(113): OC\\Connector\\Sabre\\File->put(Resource id #35)\n
#10 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1053): OC\\Connector\\Sabre\\Directory->createFile('IMG_1697.JPG', Resource id #35)\n
#11 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(513): Sabre\\DAV\\Server->createFile('Fotki\/20090705_...', Resource id #35, NULL)\n
#12 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n
#13 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n
#14 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n
#15 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n
#16 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n
#17 \/var\/www\/owncloud\/remote.php(132): require_once('\/var\/www\/ownclo...')\n
#18 {main}","File":"\/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":66}
```

**Comment by RealRancor** [comment]
Hi,

please fill out the issue template provided here:

https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

as asked in the "guidelines for contributing" (linked in the yellow box when creating an issue).

**Comment by GrimDemon** [comment]
Sorry, I didn't know of that template.

### Steps to reproduce
1. Upload many small files (eg. pictures) with Windows sync client (100mbps connection between client and server)
2. Client reports error "upload interrupted"
3. Errors provided in the first post appears

### Expected behaviour
Normally it should be no problem to upload many files at the same time

### Actual behaviour
It looks like database is overloaded by INSERTs/UPDATEs

### Server configuration
**Operating system**:
Debian 8.2 (Jessie) 64-bit

**Web server:**
Apache 2.4.10 

**Database:**
MySQL 5.5.44-0

**PHP version:**
PHP 5.6.12-0

**ownCloud version:** (see ownCloud admin page)
ownCloud 8.1.1

**Updated from an older ownCloud or fresh install:**
ownCloud 8.0

**List of activated apps:**
Enabled:
 - activity: 2.0.1
 - bookmarks: 0.4
 - calendar: 0.7.3
 - contacts: 0.4.0.0
 - encryption: 1.0.0
 - files: 1.1.10
 - files_external: 0.2.3
 - files_locking:
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - storagecharts2: 2.6.1
 - templateeditor: 0.1
Disabled:
 - external
 - user_external
 - user_ldap
 - user_webdavauth

**The content of config/config.php:**
$CONFIG = array (
  'instanceid' => '***',
  'passwordsalt' => '***',
  'secret' => '***',
  'trusted_domains' =>
  array (
    0 => '***',
    1 => '***',
    2 => '***',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '***',
  'dbpassword' => '***',
  'installed' => true,
  'overwrite.cli.url' => 'https://***:8080/owncloud',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.distributed' => '\\OC\\Memcache\\Memcached',
  'memcached_servers' =>
  array (
    0 =>
    array (
      0 => 'localhost',
      1 => 11211,
    ),
  ),
  'mail_from_address' => '***',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => '***',
  'mail_smtpauth' => 1,
    'mail_smtpname' => '***',
  'mail_smtppassword' => '***',
  'mail_smtphost' => '***',
  'mail_smtpport' => '465',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpauthtype' => 'LOGIN',
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'theme' => '',
  'maintenance' => false,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox

**Operating system:**
Windows 10

### Logs
#### Web server error log
[Wed Sep 16 06:25:11.432312 2015] [mpm_prefork:notice] [pid 872] AH00163: Apache/2.4.10 (Debian) OpenSSL/1.0.1k configured -- resuming normal operations
[Wed Sep 16 06:25:11.432355 2015] [core:notice] [pid 872] AH00094: Command line: '/usr/sbin/apache2'

#### ownCloud log (data/owncloud.log)
Interesting part provided in the first post

#### Browser log
Problem occurs in sync client, so no browser logs this time

**Comment by RealRancor** [comment]
> ownCloud version: (see ownCloud admin page)
> ownCloud 8.1.1

Ok, i thought about this bug https://github.com/owncloud/files_locking/issues/17 but it seems this particular was already fixed on oC 8.0.4 according to the milestone.

**Comment by GrimDemon** [comment]
I have read this topic as well. It's strange - this problem occurs exactly with very fast uploading. If I limit the transfer to ~800kbps then everything is OK.

**Comment by PVince81** [comment]
@GrimDemon you can try setting "filesystem_check_changes" to 0 in config.php. This will prevent OC to try detecting updates in the "data" folder. Usually this detection is not needed unless you are manually adding files directly into the "data" folder which isn't recommended anyway.

**Comment by PVince81** [comment]
if that doesn't solve the problem, another workaround is to disable the "files_locking" app.

If you're worried about concurrency and still want to have locking, you can use the new transactional locking that works better but requires a redis server, see https://doc.owncloud.org/server/8.1/admin_manual/configuration_files/files_locking_experimental.html
(in 8.2 there will also be a DB backend which removes the need of having redis, but redis should be much faster)

Hope this helps a bit.

**Comment by GrimDemon** [comment]
I disabled File Locking App and enabled TFL with Redis as memcache locking. So far so good. I'll check how it behaves with my JPG upload storm and provide some feedback :+1:

**Comment by MorrisJobke** [comment]
> I disabled File Locking App and enabled TFL with Redis as memcache locking. So far so good. I'll check how it behaves with my JPG upload storm and provide some feedback :+1:

@GrimDemon Any news here? Hopefully positive because you didn't complained about problems yet ;)

**Comment by GrimDemon** [comment]
Yup, everything is fine with Transactional File Locking and Redis as backend even with local (LAN) upload  :)

Thank you OC team for your help, I think this ticket can be closed.

**Comment by PVince81** [comment]
Glad to hear that it worked :smile:
