### ISSUE TITLE
Encryption setting to disable encryption for the home storage

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#19061]
The use case of server-side encryption is to protected the users against malicious 3rd party storage providers. The user can already enable/disable encryption for different external storages but he can't disable encryption for the home storage. With the use case of server-side encryption in mind it would make a lot of sense to disable encryption for the home storage and only enable it for some external storages.

Therefore I suggest a setting to disable encryption for the home storage. This was also suggested by multiple users during the ownCloud conference. We still need to decide if it makes more sense to have such a setting in core or on a per-encryption-module level. Opinions? Suggestions?

cc @DeepDiver1975 @cmonteroluque @karlitschek @jknockaert

**Comment by jknockaert** [comment]
I'm not sure I agree with narrowing the use case of server-side encryption to protect against malicious 3rd party storage providers. In the context of small deployments (I guess that's where the "own" in ownCloud comes from) physical access to the server is typically not very secured. In this case encryption also protects against hardware theft.
That said, the suggested setting seems a good idea to me. Would it end up in config.php, or would each individual user be able to specify account-specific encryption settings through the user interface?

**Comment by cmonteroluque** [comment]
I also see @jknockaert's point regarding protection of hardware compromise. @MTRichards what do you think about the scope change? My first instinct is to include home

**Comment by schiesbn** [comment]
> In this case encryption also protects against hardware theft.

For this case I would always suggest to use hard disc encryption provided by your operating system. E.g. Luks or something similar on GNU/Linux. That's more secure, has a way better performance and has less sources of error.

> @MTRichards what do you think about the scope change?

imho it's not about changing the scope. Protecting against third party storage providers was always the advertised use case, let me quote https://doc.owncloud.org/server/8.2/admin_manual/configuration_files/encryption_configuration.html:

> Encryption keys are stored only on the ownCloud server, eliminating exposure of your data to third party storage providers. The encryption app does not protect your data if your ownCloud server is compromised, and it does not prevent ownCloud administrators from reading user’s files. This would require client-side encryption, which this app does not provide. If your ownCloud server is not connected to any external storage services then it is better to use other encryption tools, such as file-level or whole-disk encryption. Read How ownCloud uses encryption to protect your data for more information.

I don't want to change the scope in any way, I just want to add a option which makes a lot of sense for many use cases. Also the default will stay the same.

**Comment by MTRichards** [comment]
The major use case I focused on was to protect against server administrators seeing files on the server that they should not be looking at. That is the primary use case for commercial concerns, which cannot be solved by disk level encryption.

The idea that we could have the primary storage unencrypted, and the secondary storage encrypted...I can see a case for that, I just don't have a real world example where that is interesting at this time. Still, I can see where it could be useful for some instances.

A setting to disable encryption for home storage is probably a nice to have. Not critical, but if it is simple enough to do, it does make something like a hybrid ownCloud feasible where the secondary storage is S3, for example, and primary storage is ownCloud local.

**Comment by jknockaert** [comment]
@schiesbn I don't know of a concept of hard disc encryption that makes sense in the context of a web server. And if you want to combine it with data integrity, think of putting the datafolder on a ZFS volume. ZFS on Linux provides formidable data integrity but is lacking disc encryption (at least in its more common version). And ownCloud encryption performance should be fine, as common versions of OpenSSL (1.0.1 and up) are using native cpu encryption features transparently. In the case of home-and-kitchen deployments of ownCloud I wouldn't think of encryption being a performance issue anyhow.

**Comment by schiesbn** [comment]
@jknockaert 

> I don't know of a concept of hard disc encryption that makes sense in the context of a web server. 

It depends against which attacks you want to protect yourself. If you want to protect yourself against someone break into your basement, steal your server then hard disc encryption on OS level is what you want.

If you want to protect against someone who breaks into your server online you want client side encryption, because if the attacker has root access on your server server-side-encryption can't protect you any longer

If you have a distributed setup: ownCloud server at one serverA administrated by adminA and storage on serverB administrated by adminB and you trust adminA but not adminB then server-side encryption on serverA is a feasible solution. 

For performance issues look for example at: https://github.com/owncloud/core/issues/18359
Sure we can (and have to) improve this. But at the end server-side encryption will always be slower then hard disc encryption on OS level.

**Comment by schiesbn** [comment]
> The major use case I focused on was to protect against server administrators seeing files on the server that they should not be looking at. 

If the server administrator is the same as the ownCloud administrator then it just protects you against someone seeing some files by accident. It doesn't protect you against a admin who really want to see it because he can bypass the encryption quite easy. We should be really clear here with respect to our communication otherwise we rise expectations we can't satisfy.

As far as I understood it, at enterprise setups  this administrators are often two different persons, the admin who administrate the ownCloud server and the admin who administrate the storage server. In this case it makes totally sense if you wants protect against the server administrator who administrate the storage server. That's basically also what our documentation says. 3rd party storage provider not necessarily have to be at a complete different company, it is just a different server than the ownCloud server.

>  I just don't have a real world example where that is interesting at this time. Still, I can see where it could be useful for some instances.

Exactly this is the use case where server-side encryption makes totally sense to enable it only for the S3 mount point:

> Not critical, but if it is simple enough to do, it does make something like a hybrid ownCloud feasible where the secondary storage is S3, for example, and primary storage is ownCloud local.

In fact that's probably the main use case in the community environment. They don't change the primary storage from local to S3. But they mount their Dropbox, GDrive, whatever to their ownCloud to use the extra GB. But of course they don't want to give Google or someone else their data, else they could use GDrive right away. So they enable server-side encryption but want to have it only for the external mount points.

I think the switch is relatively easy to add. Sure it is probably not (yet) a must have enterprise feature. But it is a really nice feature for millions of community users out there. It is also nothing which needs to be scheduled explicitly. It is just something which will probably happen at some point in time unless you are completely against this option.

**Comment by jknockaert** [comment]
@schiesbn
> If you want to protect yourself against someone breaking into your basement, steal your server and try to access the data on the server later. Then hard disc encryption on OS level is what you want.
I'm actually indifferent as to whether ownCloud or the OS encrypted the data when the hardware is compromised. But in the context of usability (from a sysadmin point of view) ownCloud encryption is much easier to handle.
> For performance issues look for example at: #18359
I didn't study the issue closely, but it seems to me caused by an overload of queries. That would be file management overhead which happens to be related to encrypted files. But I'm not convinced that the solution to this issue should be to turn off encryption.

**Comment by schiesbn** [comment]
> But in the context of usability (from a sysadmin point of view) ownCloud encryption is much easier to handle.

I think not everybody will agree on it. Think about adding user to groups, recovery case, additional source of errors,...

> But I'm not convinced that the solution to this issue should be to turn off encryption.

I don't say that the answer to performance issues is to disable encryption. I just say that server-side encryption come with some overhead.

The reason for the issue is that their are valid use cases where it makes sense to enable encryption only for the external storage the same way that it can make sense to disable it for external storages. That's why we added the option to the external storage settings but missed a setting for the opposite which is, depending on the audience, similar useful.

**Comment by jknockaert** [comment]
>I think not everybody will agree on it.

That's not a necessary requirement to make it a valid use case. If at least some agree, the use case exists.

**Comment by schiesbn** [comment]
> That's not a necessary requirement to make it a valid use case. If at least some agree, the use case exists.

I don't say that this use case doesn't exists. I just say that server-side encryption wasn't designed with this use case in mind. Of course everyone can use it for whatever he wish. This issue is about a other use case which exists as well. :wink:

**Comment by MTRichards** [comment]
Ok, given the timing, consideration for 9?

**Comment by schiesbn** [comment]
> Ok, given the timing, consideration for 9?

Of course, definitely not earlier.

**Comment by jknockaert** [comment]
Seems like the use case I was defending here is now being advertised as a design feature of Encryption 2.0:
>With ownCloud’s new Encryption 2.0  it is possible for enterprises to achieve complete control over their encryption keys AND files as ownCloud is an on-premises solution.

from: https://owncloud.com/box-keysafe-not-so-safe/
