### ISSUE TITLE
8.1.3 german translation incomplete

### ISSUE THREAD

**Issue by tuxmaster** [owncloud/core#19070]
The option " Allow username autocompletion in share dialog. If this is disabled the full username needs to be entered." in the admin panel is not translated.
![bildschirmfoto von 2015-09-16 06 58 24](https://cloud.githubusercontent.com/assets/6240474/9896743/ca568616-5c40-11e5-9414-3df355721b56.png)

**Comment by RealRancor** [comment]
Hi,

translations are handled via Transifex. Have a look at this page for some basic info: https://owncloud.org/contribute/translation/
