### ISSUE TITLE
HowTo Change External Storage User without redownload

### ISSUE THREAD

**Issue by JT1301** [owncloud/core#19074]
Hello,

i have already reported this issue: #18267 

How can I change the user in the External Storage without everything is newly downloaded.

In OwnCloud 8.0.4 i neet to set the user to "domain\username" but in 8.1.1 and 8.1.3 i need only "username" When I change the this field every Client will download it as a new storage. Any Idea?

Regards JT

**Comment by MorrisJobke** [comment]
cc @icewind1991 @Xenopathic

**Comment by Xenopathic** [comment]
@JT1301 Please don't open duplicate reports, we know about the problem, but currently there is no solution.
