### ISSUE TITLE
Webdav responds with 500 when in maintenance mode (Autoloading issue)

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#19076]
## Steps to reproduce
1. Enable maintenance mode
2. curl -v http://localhost/remote.php/webdav/

## Expected
`HTTP/1.1 503 Service Unavailable` with https://github.com/owncloud/core/pull/19075
or
`HTTP/1.1 401 Unauthorized` without https://github.com/owncloud/core/pull/19075

## Actual
`HTTP/1.1 500 Internal Server Error`

Page content:
```
Type: OCP\AutoloadNotAllowedException

Message: Autoload path not allowed: /home/nickv/ownCloud/master/core/apps/files/lib/app.php
File: /home/nickv/ownCloud/master/core/lib/autoloader.php:134

Trace
#0 /home/nickv/ownCloud/master/core/lib/autoloader.php(154): OC\Autoloader-&gt;isValidPath(&#039;/home/nickv/own...&#039;)
#1 [internal function]: OC\Autoloader-&gt;load(&#039;OCA\\Files\\App&#039;)
#2 /home/nickv/ownCloud/master/core/apps/files/appinfo/app.php(47): spl_autoload_call(&#039;OCA\\Files\\App&#039;)
#3 /home/nickv/ownCloud/master/core/lib/private/app.php(158): require_once(&#039;/home/nickv/own...&#039;)
#4 /home/nickv/ownCloud/master/core/lib/private/app.php(139): OC_App::requireAppFile(&#039;files&#039;)
#5 /home/nickv/ownCloud/master/core/remote.php(132): OC_App::loadApp(&#039;files&#039;)
#6 {main}
```

@Xenopathic

**Comment by DeepDiver1975** [comment]
@Xenopathic @nickvergessen is there a fix coming up? THX

**Comment by nickvergessen** [comment]
@Xenopathic has to take this, I'm busy with other stuff

**Comment by Xenopathic** [comment]
@LukasReschke regressed this, as I said would happen in https://github.com/owncloud/core/pull/19039#issuecomment-140394559. I'll fix it...
