### ISSUE TITLE
Share secure password generator

### ISSUE THREAD

**Issue by zyrill** [owncloud/core#19079]
I recently had to share a few files too big for email with sensitive content. I put them on my owncloud and password encrypted the container and the download itself. It would be immensely cool if there was the option to auto-generate a secure password (with some options like: length, allowed charsset [asd/ASD/123/!"§...] and a sensible default [password entropy at least 56 bit...]) that was available in the share file dialogue. It would be even cooler if you could send this password not via email but via a second channel (SMS?) but that is probably another feature request.

(OT: I had a look in the source but got so lost I didn't even know where to start implementing such a feature and the dev guide isn't helping)

**Comment by zyrill** [comment]
To specify: the password generator obviously should only create a password for the share, not for encrypting the file itself.

**Comment by MorrisJobke** [comment]
I think this would be something nice for an app. cc @PVince81 @schiesbn

**Comment by PVince81** [comment]
@pmaier1

**Comment by ThinkerIV** [comment]
Does ownCloud have any procedures for sponsoring features? We are very interested in this feature request and would like to see it move forward. It would probably be much more efficient to sponsor a developer who is already familiar with ownCloud code, rather than having one of our own developers figure it out.

**Comment by PVince81** [comment]
The only system I'm aware of is BountySource: https://www.bountysource.com/issues/26723467-share-secure-password-generator
