### ISSUE TITLE
In Maintenance mode, the server should return 503 via WebDAV

### ISSUE THREAD

**Issue by danimo** [owncloud/core#19073]
In 8.1.3, the server returns  `HTTP/1.1 401 Unauthorized` when in maintenance mode. It used to return `503`, which is how the clients detect that the server is not available and silently go offline until it returns a different status code. With the current behavior, all clients will display a password prompt because they assume that the password has changed. This is an important issue in production.

Once this issue is resolved, please make sure we have a test for this behavior.

(Related: https://github.com/owncloud/client/issues/3836).

/cc @DeepDiver1975 @cmonteroluque @karlitschek, pls.

**Comment by nickvergessen** [comment]
Stable8.1 returns a 503, just tested.

**Comment by danimo** [comment]
@nickvergessen But you could confirm it for v8.1.3? Any idea which commit fixed it?

**Comment by danimo** [comment]
Additional information: I am seeing that on an installation with LDAP.
