### ISSUE TITLE
Dynamic file listings prevent use of navigation, search and scrollbar

### ISSUE THREAD

**Issue by despens** [owncloud/core#19072]
Using ownCloud 8.1.1

If there are many items in a directory (BTW, exactly how many?), the web client does not render all of them, but is dynamically adding new items when scrolling down.

This behavior prevents the following activities:
- jumping to the bottom of the list
- using the browser's search function to find a file in a directory
- seeing, via scrollbar, what part of the list is visible, and understanding how many items are in that directory

I don't think the quicker response from the oc files app is worth discarding all this standard functionality.

**Comment by mtiersch** [comment]
I can confirm that this is a real issue.
When sharing a link to a directory with many files, the web interface does not display all the files in list view but only as many as fit into the current window.

Scrolling down does *not* reveal the remaining items in the list view on desktop and mobile Safari. Resizing the window (making it taller) helps to reveal some more files in the list, but is limited to the screen size. This renders the share link feature partly dysfunctional,

This issue does not appear in the list view on desktop and mobile Safari when logged in as a user.

**Comment by fefrei** [comment]
I can also reproduce this on Chrome (`Version 47.0.2526.111 m (64-bit)`).

**Comment by PVince81** [comment]
This would require rewriting the file list code to work with virtual scrolling instead of "append on scroll".

The reason this logic was added is because appending 1000 file entries upfront would cause a big browser slow down.

**Comment by despens** [comment]
With 1000 files there will be a slowdown, either the browser is busy rendering the page or the user is busy waiting for the files they want to get to finally showing up on "infinite scroll". I would prefer waiting for the browser to render the page any day over not being able to jump to the bottom of the page or doing an in-page search.
