### ISSUE TITLE
[Share API] Error message includes an unuseful error code

### ISSUE THREAD

**Issue by rperezb** [owncloud/core#19083]
AC:
1.- Prerrequisite: Having shared with the user user1 a folder folder1 without sharing privileges
2.- Login as user1
3.- Select to share by link the folder1

EXPECTED BEHAVIOR
An error message is shown 

CURRENT BEHAVIOR
The error shown is: You are not allowed to share 313
The 313...is not helpul

{"installed":true,"maintenance":false,"version":"8.1.3.0","versionstring":"8.1.3","edition":""}

Not sure whether this is already open, I have not found it.

**Comment by rperezb** [comment]
cc @Xenopathic

**Comment by PVince81** [comment]
@rullzer did you cover this one yet ?

**Comment by rullzer** [comment]
@PVince81 I think so. I'll verify.

**Comment by rullzer** [comment]
Yes this is fixed. Closing.
