### ISSUE TITLE
update to 8.1.3-12.1 = not working

### ISSUE THREAD

**Issue by directict** [owncloud/core#19080]
Dear,

when updating my owncloud 8.1 instance 
![1](https://cloud.githubusercontent.com/assets/12065695/9900378/a3916bb6-5c60-11e5-85cf-dea441eb2ef8.png)

i get these failures/errors:
yum update
Loaded plugins: fastestmirror
Setting up Update Process
Loading mirror speeds from cached hostfile
 * base: mirror.widexs.nl
 * extras: mirror.widexs.nl
 * updates: centos.mirror.triple-it.nl
 * webtatic: uk.repo.webtatic.com
Resolving Dependencies
--> Running transaction check
---> Package owncloud-3rdparty.noarch 0:8.1.1-12.1 will be obsoleted
---> Package owncloud-app-activity.noarch 0:8.1.1-12.1 will be obsoleted
---> Package owncloud-app-encryption.noarch 0:8.1.1-12.1 will be obsoleted
---> Package owncloud-app-external.noarch 0:8.1.1-12.1 will be obsoleted
---> Package owncloud-app-files.noarch 0:8.1.1-12.1 will be obsoleted
---> Package owncloud-app-files_external.noarch 0:8.1.1-12.1 will be obsoleted
---> Package owncloud-app-files_locking.noarch 0:8.1.1-12.1 will be obsoleted
---> Package owncloud-app-files_pdfviewer.noarch 0:8.1.1-12.1 will be obsoleted
---> Package owncloud-app-files_sharing.noarch 0:8.1.1-12.1 will be obsoleted
---> Package owncloud-app-files_texteditor.noarch 0:8.1.1-12.1 will be obsoleted
---> Package owncloud-app-files_trashbin.noarch 0:8.1.1-12.1 will be obsoleted
---> Package owncloud-app-files_versions.noarch 0:8.1.1-12.1 will be obsoleted
---> Package owncloud-app-files_videoviewer.noarch 0:8.1.1-12.1 will be obsoleted
---> Package owncloud-app-firstrunwizard.noarch 0:8.1.1-12.1 will be obsoleted
---> Package owncloud-app-gallery.noarch 0:8.1.1-12.1 will be obsoleted
---> Package owncloud-app-provisioning_api.noarch 0:8.1.1-12.1 will be obsoleted
---> Package owncloud-app-templateeditor.noarch 0:8.1.1-12.1 will be obsoleted
---> Package owncloud-app-user_external.noarch 0:8.1.1-12.1 will be obsoleted
---> Package owncloud-app-user_ldap.noarch 0:8.1.1-12.1 will be obsoleted
---> Package owncloud-app-user_webdavauth.noarch 0:8.1.1-12.1 will be obsoleted
---> Package owncloud-server.noarch 0:8.1.1-12.1 will be updated
---> Package owncloud-server.noarch 0:8.1.3-12.1 will be obsoleting
--> Finished Dependency Resolution

Dependencies Resolved

==================================================================================================================================================================
 Package                                 Arch                           Version                              Repository                                      Size
==================================================================================================================================================================
Installing:
 owncloud-server                         noarch                         8.1.3-12.1                           isv_ownCloud_community                          26 M
     replacing  owncloud-3rdparty.noarch 8.1.1-12.1
     replacing  owncloud-app-activity.noarch 8.1.1-12.1
     replacing  owncloud-app-encryption.noarch 8.1.1-12.1
     replacing  owncloud-app-external.noarch 8.1.1-12.1
     replacing  owncloud-app-files.noarch 8.1.1-12.1
     replacing  owncloud-app-files_external.noarch 8.1.1-12.1
     replacing  owncloud-app-files_locking.noarch 8.1.1-12.1
     replacing  owncloud-app-files_pdfviewer.noarch 8.1.1-12.1
     replacing  owncloud-app-files_sharing.noarch 8.1.1-12.1
     replacing  owncloud-app-files_texteditor.noarch 8.1.1-12.1
     replacing  owncloud-app-files_trashbin.noarch 8.1.1-12.1
     replacing  owncloud-app-files_versions.noarch 8.1.1-12.1
     replacing  owncloud-app-files_videoviewer.noarch 8.1.1-12.1
     replacing  owncloud-app-firstrunwizard.noarch 8.1.1-12.1
     replacing  owncloud-app-gallery.noarch 8.1.1-12.1
     replacing  owncloud-app-provisioning_api.noarch 8.1.1-12.1
     replacing  owncloud-app-templateeditor.noarch 8.1.1-12.1
     replacing  owncloud-app-user_external.noarch 8.1.1-12.1
     replacing  owncloud-app-user_ldap.noarch 8.1.1-12.1
     replacing  owncloud-app-user_webdavauth.noarch 8.1.1-12.1

Transaction Summary
==================================================================================================================================================================
Install       1 Package(s)

Total download size: 26 M
Is this ok [y/N]: y
Downloading Packages:
owncloud-server-8.1.3-12.1.noarch.rpm                                                                                                      |  26 MB     00:02
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
owncloud-server: Upgrade starting
owncloud-server: occ maintenance:mode --on
Maintenance mode enabled
/var/tmp/rpm-tmp.QGzdBY: line 12: /run/occ_maintenance_mode_during_owncloud_install: No such file or directory
error: %pre(owncloud-server-8.1.3-12.1.noarch) scriptlet failed, exit status 1
Error in PREIN scriptlet in rpm package owncloud-server-8.1.3-12.1.noarch
error:   install: %pre scriptlet failed (2), skipping owncloud-server-8.1.3-12.1
owncloud-app-external-8.1.1-12.1.noarch was supposed to be removed but is not!
  Verifying  : owncloud-app-external-8.1.1-12.1.noarch                                                                                                       1/22
owncloud-app-provisioning_api-8.1.1-12.1.noarch was supposed to be removed but is not!
  Verifying  : owncloud-app-provisioning_api-8.1.1-12.1.noarch                                                                                               2/22
owncloud-app-encryption-8.1.1-12.1.noarch was supposed to be removed but is not!
  Verifying  : owncloud-app-encryption-8.1.1-12.1.noarch                                                                                                     3/22
owncloud-app-user_ldap-8.1.1-12.1.noarch was supposed to be removed but is not!
  Verifying  : owncloud-app-user_ldap-8.1.1-12.1.noarch                                                                                                      4/22
owncloud-app-user_webdavauth-8.1.1-12.1.noarch was supposed to be removed but is not!
  Verifying  : owncloud-app-user_webdavauth-8.1.1-12.1.noarch                                                                                                5/22
owncloud-app-files_sharing-8.1.1-12.1.noarch was supposed to be removed but is not!
  Verifying  : owncloud-app-files_sharing-8.1.1-12.1.noarch                                                                                                  6/22
  Verifying  : owncloud-server-8.1.3-12.1.noarch                                                                                                             7/22
owncloud-app-files-8.1.1-12.1.noarch was supposed to be removed but is not!
  Verifying  : owncloud-app-files-8.1.1-12.1.noarch                                                                                                          8/22
owncloud-app-files_trashbin-8.1.1-12.1.noarch was supposed to be removed but is not!
  Verifying  : owncloud-app-files_trashbin-8.1.1-12.1.noarch                                                                                                 9/22
owncloud-app-files_versions-8.1.1-12.1.noarch was supposed to be removed but is not!
  Verifying  : owncloud-app-files_versions-8.1.1-12.1.noarch                                                                                                10/22
owncloud-app-firstrunwizard-8.1.1-12.1.noarch was supposed to be removed but is not!
  Verifying  : owncloud-app-firstrunwizard-8.1.1-12.1.noarch                                                                                                11/22
owncloud-app-files_texteditor-8.1.1-12.1.noarch was supposed to be removed but is not!
  Verifying  : owncloud-app-files_texteditor-8.1.1-12.1.noarch                                                                                              12/22
owncloud-server-8.1.1-12.1.noarch was supposed to be removed but is not!
  Verifying  : owncloud-server-8.1.1-12.1.noarch                                                                                                            13/22
owncloud-app-files_external-8.1.1-12.1.noarch was supposed to be removed but is not!
  Verifying  : owncloud-app-files_external-8.1.1-12.1.noarch                                                                                                14/22
owncloud-app-templateeditor-8.1.1-12.1.noarch was supposed to be removed but is not!
  Verifying  : owncloud-app-templateeditor-8.1.1-12.1.noarch                                                                                                15/22
owncloud-app-user_external-8.1.1-12.1.noarch was supposed to be removed but is not!
  Verifying  : owncloud-app-user_external-8.1.1-12.1.noarch                                                                                                 16/22
owncloud-app-gallery-8.1.1-12.1.noarch was supposed to be removed but is not!
  Verifying  : owncloud-app-gallery-8.1.1-12.1.noarch                                                                                                       17/22
owncloud-app-files_pdfviewer-8.1.1-12.1.noarch was supposed to be removed but is not!
  Verifying  : owncloud-app-files_pdfviewer-8.1.1-12.1.noarch                                                                                               18/22
owncloud-3rdparty-8.1.1-12.1.noarch was supposed to be removed but is not!
  Verifying  : owncloud-3rdparty-8.1.1-12.1.noarch                                                                                                          19/22
owncloud-app-files_locking-8.1.1-12.1.noarch was supposed to be removed but is not!
  Verifying  : owncloud-app-files_locking-8.1.1-12.1.noarch                                                                                                 20/22
owncloud-app-files_videoviewer-8.1.1-12.1.noarch was supposed to be removed but is not!
  Verifying  : owncloud-app-files_videoviewer-8.1.1-12.1.noarch                                                                                             21/22
owncloud-app-activity-8.1.1-12.1.noarch was supposed to be removed but is not!
  Verifying  : owncloud-app-activity-8.1.1-12.1.noarch                                                                                                      22/22

Failed:
  owncloud-3rdparty.noarch 0:8.1.1-12.1                  owncloud-app-activity.noarch 0:8.1.1-12.1            owncloud-app-encryption.noarch 0:8.1.1-12.1
  owncloud-app-external.noarch 0:8.1.1-12.1              owncloud-app-files.noarch 0:8.1.1-12.1               owncloud-app-files_external.noarch 0:8.1.1-12.1
  owncloud-app-files_locking.noarch 0:8.1.1-12.1         owncloud-app-files_pdfviewer.noarch 0:8.1.1-12.1     owncloud-app-files_sharing.noarch 0:8.1.1-12.1
  owncloud-app-files_texteditor.noarch 0:8.1.1-12.1      owncloud-app-files_trashbin.noarch 0:8.1.1-12.1      owncloud-app-files_versions.noarch 0:8.1.1-12.1
  owncloud-app-files_videoviewer.noarch 0:8.1.1-12.1     owncloud-app-firstrunwizard.noarch 0:8.1.1-12.1      owncloud-app-gallery.noarch 0:8.1.1-12.1
  owncloud-app-provisioning_api.noarch 0:8.1.1-12.1      owncloud-app-templateeditor.noarch 0:8.1.1-12.1      owncloud-app-user_external.noarch 0:8.1.1-12.1
  owncloud-app-user_ldap.noarch 0:8.1.1-12.1             owncloud-app-user_webdavauth.noarch 0:8.1.1-12.1     owncloud-server.noarch 0:8.1.1-12.1
  owncloud-server.noarch 0:8.1.3-12.1

Complete!

**Comment by LukasReschke** [comment]
@jnweiger

**Comment by RealRancor** [comment]
Very likely a dup of https://github.com/owncloud/core/issues/19078

**Comment by directict** [comment]
Yes, i think its the same indeed.

**Comment by RealRancor** [comment]
Feel free to clsoe if its the same.

**Comment by directict** [comment]
yes

**Comment by jnweiger** [comment]
@directict do you confirm it is also centos 6?

**Comment by directict** [comment]
yes, centos 6.7

**Comment by jnweiger** [comment]
thanks. Fix is under test.

**Comment by directict** [comment]
How do you mean @jnweiger
