### ISSUE TITLE
Accessibility of 'share button', alternative text is not provided for the image that is the only thing within a link.

### ISSUE THREAD

**Issue by davitol** [owncloud/core#19089]
### Steps to reproduce

1. Login ownCloud.

### Expected behaviour
An alternative text should be provided for 'share button' due to it is a image that is the only thing within a link.

### Actual behaviour

An alternative text is not provided for 'share button' image.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
master 
{"installed":true,"maintenance":false,"version":"8.2.0.4","versionstring":"8.2 pre alpha","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
 Firefox.

**Comment by jancborchardt** [comment]
@PVince81 is there a way to add the alt text to the image _only_ when the file is not shared yet? Because then the text »Shared« is next to it and the image should not have alt text anymore.

**Comment by PVince81** [comment]
You can try adding it here https://github.com/owncloud/core/blob/master/core/js/share.js#L290 and check that `hasShares` and `hasLink` are false

**Comment by cmonteroluque** [comment]
This issue will fall off 8.2 if not resolved by 6 Oct

**Comment by rullzer** [comment]
> is there a way to add the alt text to the image only when the file is not shared yet? 

Really? That seems very weird. Also since if a file is shared with you there is text next to it but in that case it is just the user that shared it with you. Seems to me that just having the alt text `Share` all the time is way more consistent.

**Comment by jancborchardt** [comment]
> Seems to me that just having the alt text `Share` all the time is way more consistent.

In that case it will read out »Share Shared« to screen reader users, which creates a problem the other way around. We’re intelligent enough to only add the alt text if it’s not shared, right? ;)
In the case of another person having it shared with you, the alt text of the icon should say »Shared by«.

**Comment by jancborchardt** [comment]
Btw @cmonteroluque rather than putting issues we couldn’t resolve in current milestone into the backlog, should they not automatically go into the next milestone? cc @karlitschek @DeepDiver1975

**Comment by karlitschek** [comment]
@jancborchardt Well. I think this gives us the opportunity to reevaluate an issue for inclusion into the next release. If we automatically move everything from one release to the next then everything is as important. And if everything is important then nothing is important.

**Comment by cmonteroluque** [comment]
@jancborchardt exactly. It does require that we change how we deal with the backlog, so it's not a black hole, of course.

**Comment by jancborchardt** [comment]
Cool, thanks for the clarification.

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/26158
