### ISSUE TITLE
file is locked error message when file doesn't exist in the filesystem

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19096]
## Env
FreeBSD, ZFS
MariaDB 10
PHP 5.5
Encryption turned on

```
Enabled:
  - activity: 2.1.2
  - encryption: 1.0.0
  - files: 1.1.11
  - files_external: 0.2.3
  - files_sharing: 0.6.3
  - files_texteditor: 2.0
  - files_versions: 1.0.6
  - gallery: 14.0.0
  - provisioning_api: 0.2
```
### Description

I always upload the same files to perform tests and recently the GUI has prevented me from doing so.
I get a "file is locked" yellow notification

Looking at the JSON I see a code of null and status of error.

There is nothing in the ownCloud logs.

Running occ files operation does nothing.

@PVince81 @DeepDiver1975

**Comment by karlitschek** [comment]
@icewind1991

**Comment by oparoz** [comment]
@PVince81 It seems the DB table holding the information is dirty and that's what's causing the problem. It would be good to add an extra step to the occ repair command.

**Comment by PVince81** [comment]
Is it still happening on master ? I seem to remember having a similar discussion recently. Locks should now auto-clean already after a TTL.

**Comment by oparoz** [comment]
We talked about it in another issue. Should be fixed. I will re-open should the TTL prove to be an ineffective ghost buster :)
