### ISSUE TITLE
After upgrade 8.1.0 to 8.1.3 I have a "Schrödingers cat" app

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#19099]
### Steps to reproduce
1. Download Tar file
2. extract Tar,
3. move old oC folder to oC.old
4. I copied config.php and my theme too
5. move extracted oC to the oC directory in var/www/html/owncloud
6. run occ updater
7. in the interface some apps are disabled.
8. enabled app
9. app look enabled and disabled at the same time
10. try to disable or enabled and same statement. 

![enabled](https://cloud.githubusercontent.com/assets/7264495/9909901/b06715ae-5c9a-11e5-9ad8-a6cc9d6a9176.png)

![disabled](https://cloud.githubusercontent.com/assets/7264495/9909903/b2f74f5a-5c9a-11e5-9abc-49d1ebd837ef.png)

### Expected behaviour
After upgrade app should be enabled

### Actual behaviour
After upgrade app should be enabled/disabled

### Server configuration
**Operating system**:
Ubuntu 14.04.2 LTS \n \l

**Web server:**
Server version: Apache/2.4.7 (Ubuntu)
Server built:   Mar 10 2015 13:05:59

**Database:**
mysql  Ver 15.1 Distrib 5.5.44-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

Connection id:          98563
Current database:
Current user:           root@localhost
SSL:                    Not in use
Current pager:          stdout
Using outfile:          ''
Using delimiter:        ;
Server:                 MariaDB
Server version:         5.5.44-MariaDB-1ubuntu0.14.04.1 (Ubuntu)
Protocol version:       10
Connection:             Localhost via UNIX socket
Server characterset:    latin1
Db     characterset:    latin1
Client characterset:    utf8
Conn.  characterset:    utf8
UNIX socket:            /var/run/mysqld/mysqld.sock
Uptime:                 --------------

**PHP version:**
PHP 5.5.9-1ubuntu4.11 (cli) (built: Jul  2 2015 15:23:08)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

**ownCloud version:** (see ownCloud admin page)
8.1 Community Edition

**Updated from an older ownCloud or fresh install:**
Fresh install

**List of activated apps:**
```
Enabled:
 - activity: 2.0.1
 - calendar: 0.7.2
 - files: 1.1.9
 - files_external: 0.2.3
 - files_locking:
 - files_mv: 0.8.1a
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - firstrunwizard: 1.1
 - provisioning_api: 0.2
 - registration: 0.0.3
 - templateeditor: 0.1
 - updater: 0.6
 - bookmarks
 - contacts
 - delete_confirmation
 - direct_menu
 - external
 - files_antivirus
 - files_pdfviewer
 - ownnote
 - sharelinks
 - tasks
```

**The content of config/config.php:**

```
$CONFIG = array (
  'instanceid' => 'xxxxx',
  'passwordsalt' => 'xxxxx',
  'secret' => 'xxxxxx',
  'trusted_domains' =>
  array (
    0 => 'xxxxx',
    1 => 'xxxxx',
  ),
  'datadirectory' => '/mnt/owncloud/data',
  'dbtype' => 'mysql',
 Before upgrade 'version' => '8.1.0.8',
 After upgrade  'version' => '8.1.3.0', 
  'dbname' => 'ocxxxxxx',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxxxx',
  'dbpassword' => 'xxxxxx',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'xxxxxx',
  'mail_domain' => 'xxxxxx',
  'mail_smtpsecure' => 'tls',
  'mail_smtpauth' => 1,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => 'xxxxxx',
  'mail_smtpport' => '25',
  'mail_smtpname' => 'xxxxxxx',
  'mail_smtppassword' => 'xxxxxx',
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
NFS = '/mnt/owncloud/data'

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

#### ownCloud log (data/owncloud.log)
This logs is when I was logged in and activated the app, After I try to login and there is no info about the app.
```
{"reqId":"ZPVhLIpwoCV1tHBlX8VV","remoteAddr":"93.202.89.149","app":"core","message":"App directory already exists","level":3,"time":"2015-09-16T15:36:48+00:00"}
```

Even if I erase the folder and try to reinstall I have both behaviors :worried:

**Comment by LukasReschke** [comment]
The OCS ID is not set for that app in info.xml :cry:

**Comment by cdamken** [comment]
I copied config.php and my theme too. forgot to write in my configuration

**Comment by LukasReschke** [comment]
@cdamken Please try https://github.com/juliushaertl/direct_menu/pull/12

**Comment by cdamken** [comment]
@LukasReschke  

> @cdamken Please try juliushaertl/direct_menu#12

trying that now only appears as enabled and now "approved"

But same behavior is with other apps: Contacts, Delete Confirmation.

**Comment by LukasReschke** [comment]
> But same behavior is with other apps: Contacts, Delete Confirmation.
> Should I do the same "trick"?

If they miss a OCS ID. Then yes, you need to add the OCS ID, but the right one. For https://apps.owncloud.com/content/show.php/Delete+Confirmations?content=169968 it's for example 169968. Contacts should however already have it: https://github.com/owncloud/contacts/blob/7f16042621d122bc482974140d07ca61118be442/appinfo/info.xml#L20

**Comment by PVince81** [comment]
Is this still an issue ? Or can we close this ?

**Comment by PVince81** [comment]
Closing due to lack of feedback
