### ISSUE TITLE
Make sure all external links open in a new window

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19104]
Some links still don't open new tabs. I just saw the link to PageKite per example. All links should be reviewed and fixed.

**Comment by oparoz** [comment]
Another example: The notification about daily being available.

**Comment by jancborchardt** [comment]
@oparoz if you point me more detailed to where this occurs then I’m happy to fix it. Where do we link to PageKite for example? And where is the link about the daily – in the admin settings? Anything I can grep for?

**Comment by oparoz** [comment]
>Where do we link to PageKite for example?

If you enable the ownCloud proxy app, there should be a section in the admin panel which links to PageKite.

Regarding the daily notification, I don't remember if the link was in a yellow notification or simply added to the list of problems at the top.
It requires the updater app to be installed if I'm not mistaken.

Unfortunately, I don't have access to a dev env with those enabled atm...

**Comment by jancborchardt** [comment]
See the PR for the Proxy app at https://github.com/owncloud/proxy/pull/3

For the update notification it seems to be https://github.com/owncloud/core/blob/master/apps/updatenotification/js/notification.js#L21 – @LukasReschke can you fix that by adding `target="_blank"` there? I have no idea about the syntax there.

**Comment by oparoz** [comment]
@jancborchardt append this `.attr("target","_blank")`

I had forgotten that each app was responsible for their own little section... That makes it difficult to fix in one go...
