### ISSUE TITLE
Choose between singleUser and singleuser

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19106]
Look at those search results:
https://github.com/owncloud/core/search?utf8=%E2%9C%93&q=singleUser

There is a mix of singleuser and singleUser values set in the configuration.

This results in config.php storing things like this:

```
  'loglevel' => 0,
  'theme' => '',
  'maintenance' => false,
  'singleUser' => true,
  'singleuser' => false,
```

This could have some unfortunate consequences, depending on how the config array is parsed.

@DeepDiver1975 @Xenopathic @nickvergessen

**Comment by Xenopathic** [comment]
Everything else is lowercase -> singleuser

**Comment by oparoz** [comment]
Yeah, looks like it's an occ encryption command problem only

**Comment by schiesbn** [comment]
fixed: https://github.com/owncloud/core/pull/19113
