### ISSUE TITLE
ImageMagick previews can't be generated in singleuser mode

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19105]
Not sure if this is by design or not. If not it could be a symptom of a bigger problem. If yes, then the documentation should be updated, highlighting the limitations.

### Env

oC VM
master
PHP 5.5.9

### Steps to reproduce

1. Turn on single user mode
2. Add the `\OC\Provider\Font` provider to your config
3. Upload a font

### Expected result

A preview

### Actual result

No preview

----
@georgehrke

**Comment by PVince81** [comment]
By design. In single user mode also Webdav is disabled.
