### ISSUE TITLE
Error during Travis setup

### ISSUE THREAD

**Issue by Henni** [owncloud/core#19103]
I'm not able to set up owncloud in travis to test the notes app.
```
exception 'Exception' with message 'App "LDAP user and group backend" cannot be installed because the following dependencies are not fulfilled: The library ldap is not available.' in /home/travis/build/owncloud/core/lib/private/app.php:1155
Stack trace:
#0 /home/travis/build/owncloud/core/lib/private/app.php(306): OC_App::installApp('user_ldap')
#1 /home/travis/build/owncloud/core/tests/enable_all.php(13): OC_App::enable('user_ldap')
#2 /home/travis/build/owncloud/core/tests/enable_all.php(22): enableApp('user_ldap')
```
see: https://travis-ci.org/owncloud/notes/jobs/80701531#L377

cc @Xenopathic @DeepDiver1975

**Comment by Xenopathic** [comment]
You are trying to use `autotest.sh`, which will try to enable all core apps (apart from files_external), including user_ldap, and test them. You probably want to run phpunit directly in your app directory, so only it gets tested.

**Comment by DeepDiver1975** [comment]
@Xenopathic this happens during installation of owncloud - not related to unit test execution

**Comment by Xenopathic** [comment]
Sorry, not autotest.sh, but rather the before_install.sh script (https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh) which uses the core_install.sh script (https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/core_install.sh) which calls enable_all.php

**Comment by DeepDiver1975** [comment]
ah - the enable_all.php

**Comment by DeepDiver1975** [comment]
hmmm ... we might want to drop this call meanwhile

**Comment by DeepDiver1975** [comment]
potential fix: https://github.com/owncloud/administration/commit/88f1d550f6a491fa0add48aa8e0c148b32bc01f1

**Comment by DeepDiver1975** [comment]
fixed .. as in lesser issue
