### ISSUE TITLE
SMB::manipulateStorageConfig() should be compatible with Backend::manipulateStorageConfig()

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19107]
```
PHP Strict Standards:  Declaration of OCA\Files_External\Lib\Backend\SMB::manipulateStorageConfig() should be compatible with OCA\Files_External\Lib\Backend\Backend::manipulateStorageConfig(OCA\Files_External\Lib\StorageConfig &$storage) in apps/files_external/lib/backend/smb.php on line 33
```

**Comment by Xenopathic** [comment]
Well this certainly is confusing. The SMB backend doesn't use `manipulateStorageConfig`...

**Comment by Xenopathic** [comment]
In addition, I'm unable to reproduce this. Could you list some steps?

**Comment by oparoz** [comment]
> Well this certainly is confusing. The SMB backend doesn't use manipulateStorageConfig...

It does:
https://github.com/owncloud/core/blob/master/apps/files_external/lib/backend/smb.php#L59

**Comment by Xenopathic** [comment]
/me should really remember to update local branches...

**Comment by oparoz** [comment]
hehe ;)

**Comment by nickvergessen** [comment]
> /me should really remember to update local branches...

Or use an IDE:
![bildschirmfoto vom 2015-09-17 08 23 38](https://cloud.githubusercontent.com/assets/213943/9926421/8e837d9e-5d15-11e5-895c-03b529f7963b.png)

**Comment by Xenopathic** [comment]
@nickvergessen No, I couldn't see the new method since it was introduced with the SMB domain thing and I hadn't run a `git fetch` yet :smile:
