### ISSUE TITLE
WebDav: create directory with an already existing directory name -> Fatal error

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#19101]
### Steps to reproduce
1. Mount the instance with WebDav (in my case Ubuntu, Filemanager: PCManFM)
2. Create a directory on local / external mount, (external with SMB) via WebDav
3. Try to create another directory with the same name (conflict) via WebDav

### Expected behaviour
Message from the filemanager: "Target file already exists"
No further error messages in the owncloud log

### Actual behaviour
Two Fatal error messages are logged

### Server configuration
**Operating system**: Ubuntu 14.04
**Web server:** nginx 1.9.4
**Database:** mysql 5.5.44
**PHP version:** 5.5.9

**ownCloud version:** 8.2 pre Alpha git
**Updated from an older ownCloud or fresh install:** fresh

**List of activated apps:** 

```
  - files: 1.1.9
  - files_external: 0.2.3
  - files_sharing: 0.6.2
  - files_trashbin: 0.6.3
  - files_versions: 1.0.6
  - provisioning_api: 0.2
```

**The content of config/config.php:**

```
       "logtimezone": "Europe\/Vienna",
       "installed": true,
       "memcache.local": "\\OC\\Memcache\\APCu",
       "theme": "",
       "maintenance": false,
       "loglevel": 2,
```

**Are you using external storage, if yes which one:** local/smb/
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** FireFox
**Operating system:** Ubuntu (same machine)

#### ownCloud log (data/owncloud.log)
There are always two error messages coming as pair
```
Fatal 	remote 		2015-09-16T13:07:42+02:00

Fatal 	webdav 	Exception: {"Message":"HTTP\/1.1 405 The resource you tried to create already exists","Code":0,"Trace":"
#0 \/xxx\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(583): Sabre\\DAV\\Server->createCollection('fgh', Array, Array)\
n#1 [internal function]: Sabre\\DAV\\CorePlugin->httpMkcol(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\
n#2 \/xxx\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\
n#3 \/xxx\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:MKCOL', Array)\
n#4 \/xxx\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\
n#5 \/xxx\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\
n#6 \/xxx\/remote.php(132): require_once('\/xxx\/...')\
n#7 {main}","File":"\/xxx\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","Line":1154} 	2015-09-16T13:07:42+02:00
```

### Additional Info
- I did this test on my dev machine where I am currently working on core PR #16534 (exclude directories from beeing processed).
- But I am also running a production evironment whith the actual officially release (ownCloud 8.1.1 (stable)). When I access via devmachine/WebDav my prodmachine/owncloud instance, I get the same error, means that this is also present in stable and not related to my dev instance.
- Usually you do not get this error when you do this test with a Windows WebDav client, because it seems that Windows WebDav clients (Windows native, CyberDuck ect) check the directory name to be created against a cached list first so the request does not get passed to the WebDav server and therefore not triggering the error.

**Comment by mmattel** [comment]
I just have downloaded another Windows WebDav client named CarotDav.
This client does not check if the folder to be created already exists against a local cache entry but sends the request directly to the server. The Fatal Error message also comes up with Windows. This means, that it is proven not to be a issue of Windows/Linux clients.

**Comment by PVince81** [comment]
Works for me on 8.2RC1, getting "405 The resource you tried to create already exists"

If I remember correctly, this was fixed already.
