### ISSUE TITLE
-1 is not a valid value for maximal versions retention obligation

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19109]
When uploading files to Files
`"method":"POST","url":"\/owncloud\/index.php\/apps\/files\/ajax\/upload.php`

This message shows up:
`"files_versions","message":"-1 is not a valid value for maximal versions retention obligation. Check versions_retention_obligation in your config.php. Falling back to auto.`

The default config contains 'auto', so there must be a check somewhere which uses '-1'.

**Comment by karlitschek** [comment]
@VicDeo Can you have a look?

**Comment by VicDeo** [comment]
@oparoz anything specific about file being uploaded?
I can't reproduce it.

**Comment by oparoz** [comment]
It's not easy to reproduce.

1. Upload 2 JPGs
2. Upload them again
3. Chose to replace the images

**Comment by oparoz** [comment]
The cron also triggers the error.

**Comment by VicDeo** [comment]
@oparoz is it for the latest master or daily?

**Comment by oparoz** [comment]
master from a few hours ago.

**Comment by LukasReschke** [comment]
Also here:

![2015-10-02_21-51-25](https://cloud.githubusercontent.com/assets/878997/10256174/bd416baa-694f-11e5-84c6-c0a92da66728.png)

**Comment by LukasReschke** [comment]
Well. This is actually pretty easy. `$splitValues` is `['auto']` and thus `$maxValue` is set to `\OCA\Files_Versions\Expiration::NO_OBLIGATION` which has a default of `-1`.

@VicDeo Please sort out what the right default is - THX. - Can be triggered by just opening `cron.php` multiple times.

![2015-10-02_22-06-20](https://cloud.githubusercontent.com/assets/878997/10256481/d29b1508-6951-11e5-8401-d59e2c75f9ad.png)
