### ISSUE TITLE
Uploading of 0 bytes files is not possible.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#19116]
### Steps to reproduce

1. Upload an empty file (0 bytes) using the web ui.

### Expected behaviour
File is uploaded.

### Actual behaviour
File is not uploaded because it has 0 bytes.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
master 
{"installed":true,"maintenance":false,"version":"8.2.0.4","versionstring":"8.2 pre alpha","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Chrome.

**Comment by oparoz** [comment]
I'm on 8.2.0.5 and was able to upload a 0Kb text file

![okb](https://cloud.githubusercontent.com/assets/323220/9935168/708bdb98-5d55-11e5-80aa-ee59a3b84d7e.png)

**Comment by SergioBertolinSG** [comment]
@oparoz what browser?

I have seen that after some time, it works. (today it works, yesterday it didn't in the same server same browser). 
But when creating a new instance you can't upload it.

I guess it is a problem with new users uploading 0 bytes files.

**Comment by oparoz** [comment]
> what browser?

Chrome as well.

> But when creating a new instance you can't upload it.

**Comment by gmurayama** [comment]
I tested as well and got the same problem. I can work on to fix it.
Apparently, this bug happen only on Chrome.

**Comment by SergioBertolinSG** [comment]
Still happening on master (2016-01-20). I find this very annoying when you have a 0 bytes file inside a group of files and the upload is not possible.

**Comment by Nyxa** [comment]
who can tell me how to solve this problem

**Comment by PVince81** [comment]
Weird, I just tried on stable9.1 and master and dragging a zero bytes file into Firefox 48 and Chromium 51 and it worked.

**Comment by PVince81** [comment]
Okay, so @michaelstingl reported that on v9.1.0 with Chromium 35 on a Mac it doesn't work.
On Linux it works for me, so it could be platform specific.

**Comment by PVince81** [comment]
@SergioBertolinSG when you tested was it also from a Mac ? Would be good to get more data about which systems it works on and which don't.

**Comment by michaelstingl** [comment]
@PVince81 `EmptyTest.txt` with 0 byte worked for me, but uncommon/unknown file extension like `EmptyTest.blubb` with 0 byte don't work.

<img width="1058" alt="emptytest_-_files_-_owncloud" src="https://cloud.githubusercontent.com/assets/214010/18504363/3902e5ce-7a62-11e6-8736-79d35fefd240.png">

`Error uploading file "EmptyTest.blubb": Unable to upload EmptyTest.blubb as it is a directory or has 0 bytes
`
### Client configuration

**Browser:**
Chrome 53

**Operating system:**
Mac OS 10.11.8

00006142

**Comment by michaelstingl** [comment]
|         | Chrome 53, Mac OS X 10.11.8 | ? | … |
|---------|:-------------------------:|:-:|:…:|
| *.txt   |             ✔             | ? | … |
| *.blubb |             ✘             | ? | … |

**Comment by SergioBertolinSG** [comment]
> @SergioBertolinSG when you tested was it also from a Mac ? Would be good to get more data about which systems it works on and which don't.

Yes, confirmed it is platform specific, tested on mac :x: tested on linux ✅  (daily master)

**Comment by SergioBertolinSG** [comment]
> @SergioBertolinSG when you tested was it also from a Mac ? Would be good to get more data about which systems it works on and which don't.

I tested this on a mac. But I've tested it again and found that the problem is the file not the OS.
It is the extension, like Michael has pointed which makes it fail. I found this with a .log file. So I guess the mimetype is involved.

Another thing I've seen is that changing the extension in linux doesn't make the behaviour change. But in mac it does. When uploading a file which was a .log file from linux it fails and refresh automatically the web ui.

**Comment by PVince81** [comment]
Confirmed, I can reproduce the issue with a different extension.

**Comment by PVince81** [comment]
Once upon a time an eager developer added a feature to make it possible to upload folders in Chromium. However as this feature doesn't work in other browsers, a check was put in that tries to detect when people try uploading folders with such browsers. Unfortunately the way how the check is implemented would also filter out zero-byte files that have no mime type !

This line: https://github.com/owncloud/core/blob/v9.0.4/apps/files/js/file-upload.js#L341

Now the problem is that if we modify this check to allow empty files again, we'll also lose the error message in case of folder upload with unsupported browsers. I checked the File object from such upload and there is no accurate way of detecting a failed folder upload, it simply appears like an empty file...

So let's remove the error message and allow uploading empty files again.

**Comment by PVince81** [comment]
I just did some testing and in Firefox when uploading a directory, `readAsBinaryString()` is supposed to throw an exception but it doesn't... any more? So we can't show that error message any more in Firefox, so users will have to do with "Could not upload file 'directory'"

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/core/pull/26113
