### ISSUE TITLE
Avatars in dropdown should set srcset

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#19112]
Currently the javascript code takes an avatar of the required size (size \* devicePixelRatio). It probably is a better idea to use standard sizes and let the browser decide like we did in #17998

We could provide for example
- 32 \* 32
- 64 \* 64
- 128 \* 128
- 256 \* 256

This way we only have to generate 4 sizes (could even do that on avatar upload). And we will thus always hit the cache and server a static file.

I would argue that if a user for his/her screen actually needs a 61 \* 61 image the 64 \* 64 would be just fine.

Of course this is only a change on the js size. The backend still servers images of the exact size. But again, in most cases we would then just hit the cache which should provide less load on the server and a better user experience.

**Comment by oparoz** [comment]
> Of course this is only a change on the js size. The backend still servers images of the exact size. 

Hmmm...Is that a limitation of Preview or avatar?

**Comment by rullzer** [comment]
@oparoz I might have phrased it wrong. I mean that

`.../avatar/rullzer/21` should return a valid avatar of 21*21. So the background should stay generic. But the js side should usually just request common sizes.

But we could have a similar setup for the previews.... but for now I just mean avatars

**Comment by oparoz** [comment]
OK!

Yes, Gallery does the same for the slideshow, but not in such a drastic way because of they large difference in screen sizes between users. There is an issue logged in core to standardise sizes for previews in order to not have to generate so many and fill the disk until there is none left, but if previews have 5 categories, avatar 4 and some other app 3, then that's a lot of categories.

**Comment by rullzer** [comment]
well sure. But for avatars now it is bascially generate whatever is requested. And I do not think we can properly unify this since avatars generally require much smaller sizes than image previews etc. Altough we might do it for the thumbnails.
