### ISSUE TITLE
Carddav sync broken for URI/UID with curly brackets, v 8.1.3

### ISSUE THREAD

**Issue by Tratoschek** [owncloud/core#19111]
We just upgrading our Owncloud Server to 8.1. Since then, Carddav-Support for some Contacts are broken. In my case they are neither synced to my desktop (using KDE/akonadi) nor to my smartphone (using DavDroid), so I think the server is the problem. After some investigation it seems, that all of this special contacts, have an URI/UID which cointains curly brackets. An example:

Column carddata in oc_contact_cards:
```
BEGIN:VCARD
VERSION:3.0
FN:Max Muster
N:Muster;Max;;;
PRODID:-//ownCloud//NONSGML Contacts 0.2.5//EN
REV:2014-04-27T11:34:13+00:00
TEL;TYPE=CELL:0123456789
UID:{c174e5db-c4ba-4cfb-aa0e-0e7e1c22798f}
END:VCARD
```
Column uri:
```
{c174e5db-c4ba-4cfb-aa0e-0e7e1c22798f}
```

We also create one fake contact without curly brackets (it was synced) and then changed the URI and UID to a curly one. The contact disappears (except from webinterface).

**Comment by RealRancor** [comment]
Please re-open in: https://github.com/owncloud/contacts/issues

by using the issue template described here: https://github.com/owncloud/contacts/blob/master/CONTRIBUTING.md#short-version

**Comment by Tratoschek** [comment]
Done: https://github.com/owncloud/contacts/issues/1050
