### ISSUE TITLE
Missing checkboxes in share dialog

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#19117]
![sharesidebarcheckboxes](https://cloud.githubusercontent.com/assets/277525/9929848/b94e72a8-5d2f-11e5-850a-7eeb7aa0c0db.png)

Observed on master (c9397dffea9da757d18514e8eb303c3c88756c84)

Possibly introduced by #18735 

@jancborchardt can you have a look ?

**Comment by jancborchardt** [comment]
cc @Henni @raghunayyar can you take a look?
