### ISSUE TITLE
Missing default expiration value when sharing link on reshare

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#19119]
### Steps

1. Go to admin page and tick "Set default expiration date"
1. User1 creates folder "test"
1. User1 shares "test" with link (a default exp date will be set, exact value doesn't matter)
1. User1 shares "test" with "user2" (in that order!)
1. User2 (re)shares "test" with link

### Expected result
A default expiration date is set when user2 clicks "Share link"

### Actual result
When user2 shares with link, the expiration date is not set at all. (checkbox is not ticked)
But when user1 did, it was for that user.
Maybe the reshare information is messing up.

### Versions
ownCloud 8.2 pre-alpha git master (c9397dffea9da757d18514e8eb303c3c88756c84)

Note: this scenario never worked on previous versions due to https://github.com/owncloud/core/issues/11396

CC @blizzz

**Comment by PVince81** [comment]
I'll still tag as regression because I saw that when https://github.com/owncloud/core/issues/11396 is fixed, the reshare does get the correct default expiration date.

**Comment by PVince81** [comment]
Ok, actually not a regression but existing old bug with "default expiration date".

Here are reduced steps:

1. Go to admin page and tick "Set default expiration date"
1. User1 creates folder "test"
1. User1 shares "test" with "user2" (in that order!)
1. User2 (re)shares "test" with link
1. Check the network console

I can see that expirationDate is set properly and sent to the ajax/share.php code.
HOWEVER the database field for expiration is NULL:
```
MariaDB [owncloud]> select * from oc_share;
+----+------------+------------+-----------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-----------------+-----------+
| id | share_type | share_with | uid_owner | parent | item_type | item_source | item_target | file_source | file_target | permissions | stime      | accepted | expiration | token           | mail_send |
+----+------------+------------+-----------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-----------------+-----------+
|  1 |          0 | user1      | root      |   NULL | folder    | 8           | /8          |           8 | /test       |          31 | 1442489961 |        0 | NULL       | NULL            |         0 |
|  2 |          3 | NULL       | user1     |      1 | folder    | 8           | /8          |           8 | /test       |           1 | 1442489972 |        0 | NULL       | 8sCiQGwFQ2Vm6LX |         0 |
+----+------------+------------+-----------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-----------------+-----------+
```

This is about reshares.

When doing it on a local folder it works properly.
There must be some code that decides to discard the expiration date for reshares...

@schiesbn

**Comment by blizzz** [comment]
Is this now also fixed with https://github.com/owncloud/core/pull/19122?

**Comment by PVince81** [comment]
@blizzz no. This bug was hidden by the other one.
Now that the PR is merged (and hopefully its backport soon too), this bug will become visible on 8.1.
However on master it's already visible.

**Comment by rullzer** [comment]
same happens on the OCS endpoint. If now expiration date is provided no expiration date is set on the reshare..

So probably something goes wrong in my most favourite file...

**Comment by rullzer** [comment]
Ok I think I got it. Let me prepare a PR and hope nothing else breaks...
