### ISSUE TITLE
Checkboxes are missing

### ISSUE THREAD

**Issue by Xenopathic** [owncloud/core#19118]
In the external storage configuration form on master, checkboxes are no longer displayed:

![screenshot_2015-09-17_11-09-12](https://cloud.githubusercontent.com/assets/2016878/9930582/a057d7a6-5d2c-11e5-93ef-86c43c5fb64f.png)

cc @jancborchardt @PVince81

**Comment by Xenopathic** [comment]
Broken by 7be8984fd9a6c6c3292f01d4bdbf24d80e4c0079, part of #18735 

cc @raghunayyar 

Probably related to #19117

**Comment by jancborchardt** [comment]
@Henni @raghunayyar can you take a look at this too?

**Comment by Henni** [comment]
Not as simple to fix as #19117 because the checkboxes need IDs to work with the labels.
Because of #18735 checkboxes can't be nested in the labels. Instead the label has to refer to the checkbox via the `for` attribute. I haven't found a way to generate unique ids for the inputs yet.

**Comment by PVince81** [comment]
You can use `_.uniqueId('prefix')` to generate an id, then pass it to the template
