### ISSUE TITLE
Unable to get app list due to "cURL error 56"

### ISSUE THREAD

**Issue by Forage** [owncloud/core#19127]
### Steps to reproduce
1. Go to the "Apps" page
2. Click on "Multimedia"

### Expected behaviour
Give me a list of all available apps

### Actual behaviour
The notification "No apps found for your version" is displayed. With the error "Could not get applications: cURL error 56: See http://curl.haxx.se/libcurl/c/libcurl-errors.html" in the log on the admin page.

Trying the following give me no errors "curl -v https://api.owncloud.com/v1" or "curl -v https://apps.owncloud.com"

### Server configuration
**Operating system**: Linux version 2.6.31.8.duov2 (debian based)

**Web server:** Apache/2.2.16 (Debian)

**Database:** MySQL 5.1.49-3 (Debian)

**PHP version:** 5.4.44

**cURL version:** 7.21.0

**ownCloud version:** 8.1.3

**Updated from an older ownCloud or fresh install:** 8.1.2 (same issue there, hence the update)

**List of activated apps:**
Enabled:
 - activity: 2.0.2
 - files: 1.1.10
 - files_external: 0.2.3
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.6

Disabled:
 - encryption
 - external
 - user_external
 - user_ldap
 - user_webdavauth

**The content of config/config.php:**
http://pastebin.com/wztcZmnV

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 40.0.3

**Operating system:** Ubuntu 15.04 (x64)

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
http://pastebin.com/kmtD3xMM

**Comment by RealRancor** [comment]
Curl error 56 is:

> CURLE_RECV_ERROR (56)
>
> Failure with receiving network data.

Anything blocking PHP to accesd your network? SELinux?

**Comment by Forage** [comment]
It shouldn't. I tried the test script posted in a different issue and it works as expected: https://github.com/owncloud/core/issues/16255#issuecomment-112481294
It returns me 200 and 301 so I don't expect anything is being blocked.

**Comment by Forage** [comment]
Anyone got any other suggestions?

**Comment by PVince81** [comment]
Please try again with 8.2.2 or 9.0 RC1. Else you might either need to upgrade your curl or fix your environment. This is unlikely to be a bug in ownCloud.

See http://owncloud.org/support for help
