### ISSUE TITLE
OC8.1 - Openstack Swift remove does not work

### ISSUE THREAD

**Issue by Berndinox** [owncloud/core#19125]
#### Config.php
```
'objectstore' => array(
    'class' => 'OC\\Files\\ObjectStore\\Swift',
    'arguments' => array(
        'username' => 'xxx@xxx',
        'password' => 'xxx',
        'container' => 'owncloud',
        'autocreate' => true,
        'region' => 'SBG-1',
        'url' => 'https://auth.Runabove.io/v2.0',
        'tenantName' => 'xxx',
        'serviceName' => 'swift',
    ),
),
```
After removing the files does not appear in deleted folder, but are immedialty remove from DB, however the objects on the Bucket are not removed. 

I manually triggered the Cron and Adminpanel says last run, x Seconds ago, but this does not change anything. Nothing deleted on the Swift Backend.

#### Error log:
```
Error	PHP	Array to string conversion at /var/www/owncloud/lib/private/template/functions.php#36
```
--> Seems like this has nothing to do with the "remove issue": https://github.com/owncloud/core/pull/18921

Any ideas?
BR Bernd

#### EDIT:
nginx version: nginx/1.4.6 (Ubuntu)
PHP Version 5.5.9-1ubuntu4.11
https://cloud.berndklaus.at/phpinfo.php

Strange! Seems like it has something to do with the encryption:
Steps: Installed fresh Owncloud, enabled Encryption Modul, disabled Encryption Modul, added default Swift Storage via config.php (see above). Nothing in the logs, Files just **not** get removed from Swift backend.
Afterwards, i reenabled the encryption modul, and suddenly the following log appear after a delete request:
```
Error	objectstore	Could not get object: urn:oid:46 could not be found. The API returned this HTTP response: HTTP/1.1 404 Not Found
 Content-Length: 70
 Content-Type: text/html; charset=UTF-8
 X-Trans-Id: 2D20E8B5:9DEF_05C4F7D0:01BB_55FB0B9D_1FBE841:6B1A
 Date: Thu, 17 Sep 2015 18:51:09 GMT
 Connection: close
 
 <html><h1>Not Found</h1><p>The resource could not be found.</p></html>	2015-09-17T18:51:09+00:00
Error	PHP	fclose() expects parameter 1 to be resource, boolean given at /var/www/cloud.berndklaus.at/lib/private/files/storage/wrapper/encryption.php#626	2015-09-17T18:51:09+00:00
Error	PHP	fread() expects parameter 1 to be resource, boolean given at /var/www/cloud.berndklaus.at/lib/private/files/storage/wrapper/encryption.php#625	2015-09-17T18:51:09+00:00
Error	objectstore	Could not get object: urn:oid:46 could not be found. The API returned this HTTP response: HTTP/1.1 404 Not Found
 Content-Length: 70
 Content-Type: text/html; charset=UTF-8
 X-Trans-Id: 2D20E8B5:9DEE_05C4F7D0:01BB_55FB0B9D_2067C1B:6B1D
 Date: Thu, 17 Sep 2015 18:51:09 GMT
 Connection: close
 
 <html><h1>Not Found</h1><p>The resource could not be found.</p></html>	2015-09-17T18:51:09+00:00
Error	objectstore	Could not get object: urn:oid:45 could not be found. The API returned this HTTP response: HTTP/1.1 404 Not Found
 Content-Length: 70
 Content-Type: text/html; charset=UTF-8
 X-Trans-Id: 2D20E8B5:9DEB_05C4F7D0:01BB_55FB0B9C_1366FC3:6B18
 Date: Thu, 17 Sep 2015 18:51:09 GMT
 Connection: close
 
 <html><h1>Not Found</h1><p>The resource could not be found.</p></html>
```

Another thing i found is:
When trying to disable the recovery keys the Browser Console say:
```
POST https://cloud.berndklaus.at/index.php/apps/encryption/ajax/adminRecovery 503 (Service Unavailable)
```
Now i did:
```
sudo -u www-data php -f occ encryption:status
 - enabled: true
 - defaultModule: OC_DEFAULT_MODULE
```
and
```
sudo -u www-data php -f occ encryption:status
Encryption disabled
```
Now again: No Logs, just got not deleted from Swift Bucket. :(

?
BR Bernd

#### Another Update 1:

When Uploading some files who are "known" by owncloud (.ini textfile) there are created 3 files in (Maybe some Meta files?) Swift backend. When deleting the file in OC and calling the cron the 2 Meta files got removed but not the .ini files itself.
please excuse my bad english!

#### Another Update 2:
**A fresh installation without ever used encryption works! Seems like encryption modul is breaking something.**

However i'm not able to add it as a primary storage, like here:
https://doc.owncloud.org/server/8.0/admin_manual/enterprise_external_storage/s3_swift_as_primary_object_store_configuration.html

There appears "Internal Server Error"... 
Mounting via Backend GUI, without encryption does work..

**Comment by karlitschek** [comment]
@butonic any idea?

**Comment by PVince81** [comment]
@icewind1991 fixed as per your recent PR ?

**Comment by icewind1991** [comment]
I dont think it's related

**Comment by butonic** [comment]
IIRC there was a problem with the post delete hook ... file id was no longer available or some such thing ... I will investigate

**Comment by Berndinox** [comment]
Noticed this during my test.
Transfered 10k files, removed some from owncloud webinterface. i dont know why, but one file was removed from openstack storage but owncloud does not receive an confirmation, it was still in the owncloud dB.. From Time to time my log grows with errors that the file could not be found. Quick and Dirty Solution: create a blank file with that Name (from log) directly in horizon.

**Comment by PVince81** [comment]
Is this still happening in 9.0.3 or 9.1.0 RC1 ?

**Comment by scysys** [comment]
It´s not solved. Openstack Files still can not removed in ownCloud 9.1

**Comment by kdslkdsaldsal** [comment]
@scysys Please create a new issue and make sure that you're filling out the issue template shown when doing so.
