### ISSUE TITLE
8.1.1.3 (stable channel) says no new Updates although 8.1.3 (stable) is out

### ISSUE THREAD

**Issue by Siedlerchr** [owncloud/core#19133]
### Steps to reproduce
1. Install OC 8.1.1.3
2. Click Check for updates in stable channel

### Expected behaviour
New update in stable channel should be available (8.1.3)

Previous update to 8.1.1.3  worked succesfully a while aog

### Actual behaviour
OC up to date  Checked at [Timestamp]

### Server configuration
**Operating system**:

Apache-Version 2.2.29
PHP-Version 5.4.40
MySQL-Version 5.6.23
Architektur x86_64
Betriebssystem linux
Kernel-Version 2.6.32-042stab108

**ownCloud version:** (see ownCloud admin page)
8.1.1.3

**Updated from an older ownCloud or fresh install:**
Updated from 8.1

**List of activated apps:**
- external: 1.2
 - files: 1.1.10
 - files_external: 0.2.3
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - galleryplus: 13.0.0
 - updater: 0.6
 - user_external: 0.4
Disabled:
 - activity
 - encryption
 - gallery
 - provisioning_api
 - templateeditor
 - user_ldap
 - user_webdavauth

**The content of config/config.php:**

```
php occ config:list system --public
                                                            
  [InvalidArgumentException]                                
  There are no commands defined in the "config" namespace.  

<?php
$CONFIG = array (
  'instanceid' => '522b44e093443',
  'passwordsalt' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'datadirectory' => '/home/xxxxxxxxxxxx/public_html/data',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'dbname' => 'xxxxxxxxxxx_xxxxxxxxx',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'x_xxxxxxxxxx',
  'dbpassword' => 'xxxxxxxxxxxx',
  'installed' => true,
  'forcessl' => true,
  'maxZipInputSize' => 838860800,
  'allowZipDownload' => true,
  'loglevel' => 1,
  'logdateformat' => 'F d, Y H:i:s',
  'logtimezone' => 'Europe/Berlin',
  'appstoreenabled' => true,
  'appstoreurl' => 'https://api.owncloud.com/v1',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/home/xxxxxxxxxx/public_html/apps',
      'url' => '/apps',
      'writable' => true,
    ),
  ),
  'appcodechecker' => true,
  'enable_previews' => true,
  'theme' => '',
  'maintenance' => false,
  'updatechecker' => true,
  'has_internet_connection' => true,
  'check_for_working_webdav' => true,
  'check_for_working_htaccess' => true,
  'trusted_domains' => 
  array (
    0 => 'xxxxxx.xxxxx.xxxxx',
  ),
  'secret' =>'xxxxxxxxxxx',
);


(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
NO

**Are you using encryption:** yes/no
Only SSL

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
nop 

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Nothing 
```

#### ownCloud log (data/owncloud.log)
```
Nothing inside
```

#### Browser log
```
Insert your browser log here, this could for example include:
Nothing important, only:
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src https://xxxxxxxxxx.xxxxxxxxxx.xxxxxxxx'unsafe-eval'").
```

**Comment by RealRancor** [comment]
Hi,

its the same after every release: Updates via the updater are delayed for a few days after the release.

**Comment by karlitschek** [comment]
done.
