### ISSUE TITLE
Share dialog checkbox spinner is shifted

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#19137]
On master in the sidebar share tab:

Click on "Share link" or other checkboxes. For a short time the checkbox is shifted and the spinner is shifted.

**Comment by jancborchardt** [comment]
cc @Henni @raghunayyar ;)

**Comment by davitol** [comment]
Same behaviour with the trashbin icon when deleting a share

**Comment by PVince81** [comment]
Yeah, almost all the spinners.

A few days ago I tried to quickfix it but it seems to be a tougher one.
Ideally the spinner should replace the checkbox/icon completely. This used to work, not sure why it doesn't with the new layout.

**Comment by jancborchardt** [comment]
@Henni maybe an interesting problem for you to look into? :)

**Comment by schiesbn** [comment]
> Same behaviour with the trashbin icon when deleting a share

Also we don't hide the trashbin icon while showing the spinner so the cover each other
