### ISSUE TITLE
Find a way to make the right sidebar permanent if the user wants to

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19136]
As a user, I should be able to configure the view of my file manager.
I should be able to permanently show the right sidebar in order to have quick access to the information I need, as I go through my files.

It's nice to have a very clean UI, but it's not very useful if you have to click 3 times to get a simple task done or to have access to useful info. It's up to the users to decide what works for them.

A first step could be to offer to pin the sidebar. That way there is no scary button to add to the empty "controls" bar.

@jancborchardt @PVince81 @icewind1991

**Comment by jancborchardt** [comment]
(Off-topic, but as a general thing: We should _not_ use male-specific personal pronouns like »him«, »he« etc. when referring to people using our software. Please use »them«, »they« instead, as we do not design and develop this software just for one man. Thanks.)

**Comment by oparoz** [comment]
OK. For me, it's always implied, just like when you post a recruitment offer (you post a one-liner at the end, explaining it isn't gender specific), but I'll try to use "they" instead.

**Comment by jancborchardt** [comment]
In any normal flow like clicking on details, or sharing a different file, the sidebar will stay open anyway. It shows when needed and hides when not. I’m not sure if a general pinning feature is really useful, so I would say we rather discuss this on a case-by-case basis where we actually see this is a problem.

**Comment by PVince81** [comment]
@owncloud/design for input
