### ISSUE TITLE
Missing check boxes in file comparator

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19135]
![checkboxes](https://cloud.githubusercontent.com/assets/323220/9937145/cb54fc80-5d5f-11e5-8096-77b30a3f6cca.png)

@Henni

**Comment by Henni** [comment]
How do I reproduce this?
I don't know how to invoke the file comparator.

**Comment by oparoz** [comment]
Ah :)

1. upload 2 files
2. upload the same files again

**Comment by PVince81** [comment]
Can't we just have a fallback style for all checkboxes that haven't been updated yet ?
The problem with this is that if other apps have checkboxes too, they'd disappear as well until the developer updates their app.

@jancborchardt ^

**Comment by oparoz** [comment]
@Henni What about @PVince81's suggestion?

**Comment by Henni** [comment]
@oparoz @PVince81 a fallback is difficult to implement. I think it isn't possible in css and a fallback in javascript would be quite ugly. But I'll take another look at a javascript solution.

**Comment by oparoz** [comment]
Thanks! :)

**Comment by PVince81** [comment]
Next time it would be good to first think about the fallback possibility before making potentially breaking changes

**Comment by jancborchardt** [comment]
@PVince81 it wasn’t apparent then that there would be so much possible breakage.
