### ISSUE TITLE
Add a http-header for the current logged user

### ISSUE THREAD

**Issue by jmeile** [owncloud/core#19134]
I really find useful to see the logged user into the apache logs, so, I added a user header in my app, as follows:

    public function setUserHeader() {
        $container = $this->getContainer();
        $session = $container->query('OCP\IUserSession');
        $headerValue = '-';
        if ($session->isLoggedIn()) {
            $headerValue = $session->getUser()->getUID();
        }
        header('X-OCUser: ' . $headerValue);
    }

Then I called it from app.php:
$app = new Application();
$app->setUserHeader();

If would be nice if you could add this to the core library, ie, at the beginning of the function handleRequest from "lib/core.php". I'm using this on apache as follows:

LogFormat "%h - %{X-OCUser}o %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" ownCloud

Then inside my VirtualHost I declare a custom log:
CustomLog ${APACHE_LOG_DIR}/owncloud_access.log owncloud

It works pretty good.

Best regards
Josef

**Comment by tflidd** [comment]
In the combined LogFormat you already have a username (%u):
https://httpd.apache.org/docs/2.4/en/logs.html#accesslog
Are there situations where this option is not working for you?

**Comment by jmeile** [comment]
I have owncloud  8.1.0 under ubuntu 14.x and under RedHat Server 7 and it doesn't work. Instead of the username, you will see a dash '-'. I have seen this in other applications and I think it is because the http basic authentication doesn't pass any username to apache. Please test it yourself and see if it works.

**Comment by jmeile** [comment]
"common" was the log type I used before.

**Comment by jmeile** [comment]
Ok, now I see:
When using a desktop client, the user gets logged, but if you login through the browser, then it won't appear.

**Comment by tflidd** [comment]
> Please test it yourself and see if it works.

You are right. I've often seen the username in the apache logfiles and thought that this is always written. Indeed, it's only the client. Sorry for that.

**Comment by PVince81** [comment]
So, potential bug ?

**Comment by jmeile** [comment]
I would say this is actually an enhancement. As far as I know, this is a problem with "HTTP Basic authentication" and not with OwnCloud

**Comment by LukasReschke** [comment]
I doubt that this is something that we will add to core. But a custom application would be able to do that.
