### ISSUE TITLE
Backport request of #18684

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#19147]
Hi,

to avoid that this got lost please consider to backport #18684 to stable8.1

Within this week we had at least 6-7 people at the forums or IRC breaking their encryption setup because they where directly upgrading from 7.0.x to 8.1.3 which is definitely not supported.

**Comment by nickvergessen** [comment]
Also backport https://github.com/owncloud/core/pull/19131

**Comment by MorrisJobke** [comment]
#19149 is merged
