### ISSUE TITLE
Consolidate deleted files in deleted folders

### ISSUE THREAD

**Issue by Armada651** [owncloud/core#19140]
### Steps to reproduce
1. Delete a folder full of files using the sync client.
2. Open the deleted files tab.
3. Attempt to restore folder with contents.

### Expected behaviour
The deleted folder should be shown and restoring it should restore all contents, perhaps we could even open the deleted folder to show the deleted files inside. These files should not be shown individually and instead we should see the folder structure being retained.

### Actual behaviour
The folder and all its files are shown individually and have to be restored individually, this is a near impossible task without restoring all deleted files currently retained. The list becomes huge and it's impossible to restore files that were deleted before the folder was deleted.

### Server configuration
**Operating system**: Ubuntu Server 14.04

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.5.9-1ubuntu4.11

**ownCloud version:**  8.1.0 (stable)

**Updated from an older ownCloud or fresh install:**
Updated from OC7

**List of activated apps:**
Enabled:
 - activity: 2.0.1
 - files: 1.1.9
 - files_locking:
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1

Disabled:
 - calendar
 - contacts
 - encryption
 - external
 - files_external
 - files_versions
 - user_external
 - user_ldap
 - user_webdavauth

**The content of config/config.php:**
N/A

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

**Operating system:** Windows 7

**Comment by PVince81** [comment]
@Armada651 deleting folders should already keep the folder structure and make it possible to restore that structure by restoring the deleted folder.

How was the deletion done ? Was it using the sync client or any specific Webdav client ?
The correct way of deleting through Webdav is sending a DELETE on the folder and not deleting every file inside.

**Comment by Armada651** [comment]
I deleted the folder using the Sync client. The folder structure was kept when restoring the file, but they were listed as individual files in the deleted files tab.

**Comment by Armada651** [comment]
I just checked, it seems there were also a lot of files that lost their folder structure and were instead restored to the root of my owncloud folder.

**Comment by PVince81** [comment]
@guruz @ogoffart in which situations would the desktop client send a DELETE operation for each individual file when deleting a folder ?

Maybe it's an older issue and is already fixed ?

**Comment by ogoffart** [comment]
The desktop client does not send individual DELETE for years (since the new propagator).  So any supported version of the desktop client is fine.

But one still need to support third party webdav client which can behaver howerver they like.

**Comment by PVince81** [comment]
This ticket here was about the desktop sync client. So probably an old issue, closing.

If the issue still occurs with recent desktop clients, feel free to reopen. Thanks.
