### ISSUE TITLE
Reverse encryption?

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [owncloud/core#19143]
Hello,

how do I reverse the encryption from my owncloud 8.1? Every single of my files in my separate data folder is broken. I tried to download them via my FTP client, but none of the files work anymore. Downloading via owncload gives me a few kb size file for every file.

**Comment by RealRancor** [comment]
Hi,

if you don't want to report a bug such questions should be asked at the users mailinglist or github. To answer your question just quoting from the docs:

> Plan very carefully before enabling encryption because it is not reversible

https://doc.owncloud.org/server/8.1/admin_manual/configuration_files/encryption_configuration.html#before-enabling-encryption

**Comment by karlitschek** [comment]
yes. great question for the user mailing list or the forum. but not an owncloud bug.

**Comment by RealRancor** [comment]
@Unrepentant-Atheist Btw. if you think there is a bug in ownCloud causing the file corruption please create a new issue using the issue template provided here:

https://raw.githubusercontent.com/owncloud/core/master/issue_template.md
