### ISSUE TITLE
Operation not permitted  util.php#841

### ISSUE THREAD

**Issue by thinkive** [owncloud/core#19146]
2015/09/18 14:17:59 [error] 24822#0: *1 FastCGI sent in stderr: "PHP message: {"reqId":"Lo8+1lAq3pQm\/jhX3QbI","remoteAddr":"","app":"PHP","message":"chmod(): Operation not permitted at \/root\/www\/nodejs\/trunk\/public\/HTML5\/owncloud\/lib\/private\/util.php#841","level":3,"time":"2015-09-18T06:17:59+00:00"}" while reading response header from upstream, client: , server: localhost, request: "GET /owncloud/index.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000",

**Comment by RealRancor** [comment]
https://stackoverflow.com/questions/23070266/php-chmod-operation-not-permitted-safe-mode-deprecation-involved

etc. should provide you the infos how to fix your setup so your PHP is allowed to execute the needed chmod command.
