### ISSUE TITLE
singleuser mode cannot be turned off

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19141]
Something has changes the behaviour of ownCloud when installed on Travis and the instance is now in singleuser mode and integration tests fail with a 503.

I've noticed this in the VM as well. The instance stayed in singleusermode after a successful installation.

@DeepDiver1975 @nickvergessen @schiesbn

**Comment by oparoz** [comment]
It can't be turned off. Something keeps turning it on.

```
$ php occ maintenance:singleuser --off
Single user mode disabled
```

Later

```
$CONFIG = array (
  'appstoreenabled' => false,
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/home/travis/build/owncloud/core/apps',
      'url' => '/apps',
      'writable' => true,
    ),
  ),
  'passwordsalt' => 'HhNFBvkzqgXOgAVaRDx3eKWmLTI+Z4',
  'secret' => 'ixG5xYZ4+cyYp3BjdSkPYd9FTtql9reYiDV+/0NOk/CADSnT',
  'trusted_domains' => 
  array (
    0 => 'localhost',
  ),
  'datadirectory' => '/home/travis/build/owncloud/core/data-autotest',
  'overwrite.cli.url' => 'http://localhost',
  'dbtype' => 'sqlite3',
  'version' => '8.2.0.5',
  'logtimezone' => 'UTC',
  'installed' => true,
  'instanceid' => 'ocsprcz485e9',
  'singleuser' => true,
  'enabledPreviewProviders' => '',
);
```

**Comment by oparoz** [comment]
It seems impossible to disable singleuser mode...

```
$ php occ maintenance:singleuser --off
Single user mode disabled
$ occ maintenance:singleuser
Single user mode is currently enabled
```

**Comment by oparoz** [comment]
Same problem when trying to use config:system
```
$ php occ config:system:set singleuser --value=false
System config value singleuser set to false
$ php occ config:system:get singleuser
true
```

But if I try to set another variable, it works just fine...
```
$ php occ config:system:set singleUser --value=false
System config value singleUser set to false
$ php occ config:system:get singleUser
true
```

**Comment by oparoz** [comment]
I suspect caching to be the problem.

**Comment by Xenopathic** [comment]
Nope, it's the encryption commands, specifically `encryption:encryptyall`, broken in #19113 by 82eb3f8027ba95dd859cde75241921222d970ce1. It calls `setSystemValue('singleuser', true)` during command construction for some reason.

cc @nickvergessen

**Comment by oparoz** [comment]
Actually, that would be this PR: https://github.com/owncloud/core/commit/9bd4f2d41e5a211ad60a83bfcdc60b8633076a54

but I don't understand why since I'm not using encryption. Are all commands instantiated when invoking occ?

**Comment by Xenopathic** [comment]
@oparoz Yes, when occ is called all commands for all enabled apps are loaded. Unfortunately it seems the encryption encryptall command is over-zealous and tries to set single user mode, breaking many things.

**Comment by nickvergessen** [comment]
Fixing...

**Comment by nickvergessen** [comment]
@Xenopathic the actual problem was https://github.com/owncloud/core/commit/9bd4f2d41e5a211ad60a83bfcdc60b8633076a54 from https://github.com/owncloud/core/pull/18938 which sets configs in construct and destruct....

**Comment by cormite** [comment]
I am having the same problem now after updating from 10.0.5 to 10.0.7.

I am unable to turn off singleuser mode.
