### ISSUE TITLE
Users checkbox and +add group button should be aligned

### ISSUE THREAD

**Issue by davitol** [owncloud/core#19158]
Users checkbox and +add group button should be aligned
ownCloud Enterprise Edition 8.2 pre alpha (daily) 9803d68e55254c63e0b60ad76b36fa5da948adf7
![alinear](https://cloud.githubusercontent.com/assets/10596560/9956266/b383637e-5df7-11e5-9e0e-452004d4a73f.png)

8.1.3
![alinear2](https://cloud.githubusercontent.com/assets/10596560/9956269/b95533ae-5df7-11e5-8201-375c16ffafd9.png)

**Comment by PVince81** [comment]
@owncloud/designers

**Comment by jancborchardt** [comment]
No, the text should align. It’s correct in the top screenshot (master).

**Comment by PVince81** [comment]
This is how it looks like on master with Chromium 44:
![master-groupdrop](https://cloud.githubusercontent.com/assets/277525/10015643/eb88c1c4-6121-11e5-9f79-896ef1b7365e.png)

doesn't look right

**Comment by jancborchardt** [comment]
@Henni checkbox issue it seems – can you move it a bit to the right, add more whitespace to the left?
