### ISSUE TITLE
Consolidate Windows Storage Backends into External Storage

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#19156]
-	Consolidate Windows secondary storage backends – bring together a single backend for WND, Windows Home Directories, and CIFS storage so that there is a single, consolidated and performant backend.

Acceptance Criteria:
-	Consolidate WND and CIFS into a single backend.
-	Take into account situations where CIFS backend storage is slow, and extended response times are needed (clients take too long to respond)
-	Enable the use of DFS based backend filesystems
-	Standardize all existing authentication mechanisms (user provided stored in DB, user scraped session stored (no sharing), admin set) for all external storage options
o	(Duplicate? CML?)External Storage – Global authentication for multiple mount points. We need to fold all of the authentication options (global authentication password/username, user entered username and password, session scraped user/password) into the backend storage,
-	External Storage – Currently there is no status for a mount point “pending”. SharePoint has such a mount point status. This needs to be folded as possible (depending on the back end, pending may not be possible) into the external storage backend.
-	Enable each mount point to set sharing for the files mounted by the endpoint, and carry through the sharing API for clients to ensure proper sharing capabilities
-	Enterprise Edition offers a similar front end across storage, with the same UX for end users as they mount storage endpoints.

**Comment by DeepDiver1975** [comment]
Tasks:

- [ ] add status in core/files external for missing/wrong credentials
- [ ] consolidate SMB backend implementation

**Comment by DeepDiver1975** [comment]
> Enable the use of DFS based backend filesystems

@MTRichards do we have a test instance?

**Comment by jmaciasportela** [comment]
my thought: DFS implies some extra configuration in samba in the OC server side. Am I wrong??

**Comment by Xenopathic** [comment]
@jmaciasportela No, the only DFS configuration necessary is on the SMB server itself, but oC can only use DFS with the libsmbclient-php native extension, not the smbclient wrapper (limitations of the command)

**Comment by MTRichards** [comment]
@bboule ?

-- 
Matt Richards
VP Products & Markets 
ownCloud, inc.

**Comment by jmaciasportela** [comment]
@Xenopathic That is want I wanted to say. You need to configure WINS server inside smb.conf and some extra packages intalled to work fine with DFS. It is not trivial and we need to documentate how to set up correctly to work. It is an extra work ...

**Comment by jmaciasportela** [comment]
Some steps are not intuitive
http://mattslay.com/connecting-ubuntu-to-windows-shares-and-dfs-trees/

**Comment by Xenopathic** [comment]
@jmaciasportela From my experience, none of that is necessary. I have a completely unconfigured smb.conf and yet I can connect to DFS shares just fine. This was connecting to a DFS share on a Samba4 server.

**Comment by DeepDiver1975** [comment]
So at the end DFS is something we best integrate into the php sambe module @icewind1991 objections? THX

**Comment by jmaciasportela** [comment]
I don't think so, DFS must works at Operating System level. I not agree with @Xenopathic and DFS, I tryed to configure and instance in our lab some weeks ago, and DFS works between windows, but I never could connect from linux.

**Comment by DeepDiver1975** [comment]
@xenopathic is talking about DFS on samba4. We need to connect to DFS on Windows. This can result in different observation.

**Comment by jmaciasportela** [comment]
Good observation !

**Comment by PVince81** [comment]
> External Storage – Currently there is no status for a mount point “pending”. SharePoint has such a mount point status. This needs to be folded as possible (depending on the back end, pending may not be possible) into the external storage backend.

@jmaciasportela did you take this one into account in your PR about statuses ?

**Comment by jmaciasportela** [comment]
Pending status is not really a mountPoint (storage) status, is a status but only for the webUI while availability checking is running.

![reloades](https://cloud.githubusercontent.com/assets/1454351/11500214/f602d2ca-982b-11e5-8d93-7f660033f621.gif)

Row is greyed and frezed while checking the availability. This is available for all external mount points

**Comment by Xenopathic** [comment]
@jmaciasportela files_external defers the check until the storage is actually used, which I imagine dramatically reduces the load on the server (each of those 'pending' updates is another query + storage ping). Instead, if a storage is clicked on and it is unavailable, it is marked as so in the database, then the row should be marked as red to indicate that.

**Comment by jmaciasportela** [comment]
This is a requirement from Matt to have the same UX from WND and SP apps. I understand your explanation but is not my decision. @PVince81 ??

**Comment by PVince81** [comment]
I guess that the requirement is to make it possible for users to find out early about unavailable storages @MTRichards 

Also there is another requirement for the "admin defined a storage globally but need to ask the user's password the first time" where we also need to ping the storages to find out if a password is required.

**Comment by MTRichards** [comment]
Yes, @PVince81 the requirement is for a user to know if something is or is not going to work before clicking on it. The color coding is one mechanism for doing that. 
If there is a better mechanism, or one that takes less overhead or something, ok, but that is the baseline requirement.

**Comment by Xenopathic** [comment]
We should definitely implement the red row for unavailable storages, my concern is only with the status check that occurs every time the page is loaded. Perhaps we could refresh the status only when the availability TTL expires? That avoids a lot of the overheads while still giving feedback to the user if a storage breaks.

**Comment by PVince81** [comment]
@Xenopathic makes sense. Where to store the availability TTL ?

**Comment by jmaciasportela** [comment]
Availability is not always checked. There is a cache in the JS, so is only checked globally first time when files app is loaded, or single check when access to one mount point and come back to root filesystem.

**Comment by Xenopathic** [comment]
@PVince81 Already implemented :smile: : https://github.com/owncloud/core/blob/master/lib/private/files/cache/storage.php#L147

**Comment by PVince81** [comment]
Consolidation is done.
See https://github.com/owncloud/core/issues/16305 for QA and doc tickets.
