### ISSUE TITLE
external storage upload in background

### ISSUE THREAD

**Issue by christianWilling** [owncloud/core#19155]
is there a way to upload or move files with the web gui or sync them with an desktop clint via lan fast and upload it with an cronjob automatic in background?

for dropbox for example so that i can share big data fast from dropbox and upload it in background over my slow internet at home.

**Comment by MorrisJobke** [comment]
cc @icewind1991 @Xenopathic Does this makes sense?

I think the issue here is, that the owncloud server is in the local LAN and therefore access to it is very fast.

**Comment by MorrisJobke** [comment]
Just found another ticket about this, that covers this use case: #11839 -> closing this as duplicate
