### ISSUE TITLE
When a Group Member deleted shared folder locally, they can't get it back

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#19159]
As a user, I want an easy way to re-share a file or folder with a group I have already shared with, because when a sharee deletes a folder by accident, the only way for them to get it back is to reshare the entire folder again.

Expected Behavior:
When I delete a folder shared with me, I want to be able to get it back.
OR
When a user I shared files with deletes a folder, I want to be able to add them again.

Perhaps a "refresh share" sort of button on the share widow that re-adds the folder or file to the recipients ownCloud would be cool.

**Comment by PVince81** [comment]
Fits in well with overview of pending/rejected shares #13495 

That poor user could simply go to that page and re-accept the share.

We're past feature-freeze, moving to 9.1

CC @cmonteroluque @rullzer @schiesbn

**Comment by PVince81** [comment]
Moving to 9.2.

**Comment by PVince81** [comment]
@pmaier1 solution will be to implement https://github.com/owncloud/core/issues/13495

Moving to backlog

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/issues/13495
