### ISSUE TITLE
Misleading error message "User backend OC_User_IMAP not found." when user_external app is disabled

### ISSUE THREAD

**Issue by xshadow** [owncloud/core#19162]
If you install owncloud and configure it to use an IMAP backend (without enabling the user_external app first), you get the error message "User backend OC_User_IMAP not found."

It's written in the [docs](https://doc.owncloud.org/server/8.0/admin_manual/configuration_user/user_auth_ftp_smb_imap.html) that you should enable the user_external app first. But it possible to read over it.

It would be great if there would be a check if the user_external app is disabled, and if so the error message could be "App user_external is disabled".

**Comment by DeepDiver1975** [comment]
this is kind of hard - when loading a class we have no understanding where the class should live in case we do not find it.

for sure such an error message would be great - but this is not possible right away.
