### ISSUE TITLE
Feature Request: Group Membership Admin

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#19165]
Allow a user to be granted "Group Membership Admin" for a group. Meaning:
1) The user can [add|remove] any users [to|from] the group.
2) The user cannot ever create a new user.
3) The user cannot ever delete a user.
4)The user cannot change the quota or other settings of a user.

This is different to the current "Group Admin" which is aimed at allowing the "Group Admin" to manage the users in a group (add new users and delete existing users that are in the group). The current "Group Admin" will not let the Group Administrator add existing system users to the group. And even if it did, then that would probably allow the Group Administrator to subsequently delete those users - effectively giving them the ability to delete every user on the system, not such a great idea.

This is somewhat related to https://github.com/owncloud/core/issues/3362 but different again.

Use Case:
There are groups for various departments in an organisation. We want to give the administration of group membership to the relevant managers, e.g.:
Finance-staff group membership managed by jane.doe (Finance Manager)
HR-staff group membership managed by joe.bloggs (HR Manager)
...

**Comment by karlitschek** [comment]
@MTRichards  fyi

**Comment by Xenopathic** [comment]
Really what we need is a way to select exact permissions given to a group admin, be that creation of users, deletion of users, addition/removal of existing users to the group (this feature request), changing user quotas etc.

**Comment by MTRichards** [comment]
Yes, true.  We will need to update group admin no question. Probably not for 9.0, but maybe ... Or shortly thereafter.

-- 
Matt Richards
VP Products & Markets 
ownCloud, inc.
