### ISSUE TITLE
[Sharing] It is not possible to share a second file/folder with the same user.

### ISSUE THREAD

**Issue by davitol** [owncloud/core#19164]
### Steps to reproduce

1. Log in as admin user
2. Create a new user
3. Share a file/folder with the user created before
4. Try to share another file/folder with the same user

### Expected behaviour
It should be possible to share another file/folder with the user

### Actual behaviour
Cannot share another file/folder with the same user. The user B is not displayed in the textbox. it seems it is only allow to share one time.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** ownCloud Enterprise Edition 8.2 pre alpha (daily) Build:2015-09-18T03:08:29+00:00 9803d68e55254c63e0b60ad76b36fa5da948adf7

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Firefox

**Comment by davitol** [comment]
Note: If user A logs out and then he logs in again, it is possible to share the second file

**Comment by individual-it** [comment]
should be fixed by #19220 
please check & review
