### ISSUE TITLE
+ button in Files is not a square on IE8

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19160]
I'll add a screenshot later... but just load master on everyone's favourite browser and you shall see.

@jancborchardt

**Comment by jancborchardt** [comment]
@oparoz if it’s just a slight rectangle then it seriously is no issue. As long as it works, that’s fine.

**Comment by oparoz** [comment]
No, it looks broken as the + is not centered.

**Comment by oparoz** [comment]
![plus ie8](https://cloud.githubusercontent.com/assets/323220/9958854/3a7866f2-5e0e-11e5-9daa-bfb6853f3287.png)

Just off-centered

**Comment by jancborchardt** [comment]
@karlitschek @MTRichards issue or not? I’d say no since it doesn’t impair the functionality.

**Comment by karlitschek** [comment]
i think for IE8 it is mainly important that it works. small visual glitches that are hard to fix are not a huge problem. what do you think @MTRichards ?

**Comment by oparoz** [comment]
I completely agree, if it's hard to fix, but my two cents is that this contributes to the image of the product. So if a hundred people see this and can't be bothered to test with another browsers, then it's really not an issue. Now if 5000 employees use oC on a regular basis and see little broken things here and there, they might not think very highly of the product, because most will probably not understand the difference between IE8 and Chrome 45.

**Comment by MTRichards** [comment]
Ideally everything is perfect :)

But I can live with good enough for ie8.

-- 
Matt Richards
VP Products & Markets 
ownCloud, inc.

**Comment by oparoz** [comment]
OK!
