### ISSUE TITLE
When 3rdparty is set then "Composer autoloader not found, unable to continue. Check the folder "3rdparty""

### ISSUE THREAD

**Issue by peossource** [owncloud/core#19167]
From:
https://forum.owncloud.org/viewtopic.php?f=31&t=30489#p96861

User "Paaps" requests a fix to avoid a total break when '3rdpartyroot' is set.
Please check.
I hope that it is ok when I refer to the owncloud forum...
Thanks
Christian

**Comment by DeepDiver1975** [comment]
the system is not configured properly

 '3rdpartyroot' => '/var/www/owncloud/3rdparty',

should be

 '3rdpartyroot' => '/var/www/owncloud/',


quite confusing - yes - but thats the way ....

**Comment by peossource** [comment]
Yes indeed! Thanks.
There should be a hint in the documentation / config.sample.php that this is the place where that 3rdparty directory is stored...

-
Prost! Morgen geht's los...
Christian

**Comment by DeepDiver1975** [comment]
@carlaschroder can I ask you to double check the docs? THX

**Comment by carlaschroder** [comment]
Yay, something easy for once. PR: https://github.com/owncloud/core/pull/19169

**Comment by MorrisJobke** [comment]
Fixed -> close
