### ISSUE TITLE
Sharing a file/folder, it is not possible enable/disable the sharing permissions

### ISSUE THREAD

**Issue by davitol** [owncloud/core#19161]
### Steps to reproduce

1.Share a file/folder
2. Click on the permissions in the SideBar.

### Expected behaviour
It should be possible to select the permissions allowed

### Actual behaviour
Cannot enable/disable the sharing permissions

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** ownCloud Enterprise Edition 8.2 pre alpha (daily) Build:2015-09-18T03:08:29+00:00 9803d68e55254c63e0b60ad76b36fa5da948adf7

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Firefox, Chrome

![comparper](https://cloud.githubusercontent.com/assets/10596560/9956790/b643ba24-5dfb-11e5-9125-0b3ac837a154.png)

**Comment by individual-it** [comment]
I cannot reproduce the problem

**Comment by davitol** [comment]
It seems to be fixed in ownCloud Enterprise Edition 8.2 beta1 (daily) Build:2015-09-21T03:08:19+00:00 bbd1e996050fee80795d0e656da98b6451232c6c :+1: I'll close it
