### ISSUE TITLE
Wrong warning about nearly full storage

### ISSUE THREAD

**Issue by VNovotna** [owncloud/core#19178]
My local storage have ~4GB filled out of 27GB. I have also 50GB external storage with 31GB filed and I get "Your storage is almost full (94%)" warning. My guess is that the external storage is also counted to my local filesystem limit.
Screenshots: http://imgur.com/a/HZj6l

**Comment by PVince81** [comment]
External storage does not count in local storage.

The warning should only be shown for the local storage I believe.

**Comment by VNovotna** [comment]
But my local storage is far from full (double checked). And the warning started to appear after connecting big external storage and upgrading to 8.1.2 I believe.

**Comment by PVince81** [comment]
Yeah, must be a bug

**Comment by riku2015** [comment]
having this same issue. it went away from admin when i set admin user manually quota, but as other users i still got message "Storage of admin is almost full (96%)"
also set manual userquota every user not helping, there is plenty of diskspace on / at OS level

**Comment by VNovotna** [comment]
The behaviour changer a little in version 8.2.1. Warning appears only after entering webdav external storage (full from ~60%).

**Comment by PVince81** [comment]
Please try again with 8.2.6 or 9.0.3. There were a few fixes related to quota.

If the problem persists, please reopen. Thanks.

**Comment by vinyll** [comment]
I'm running ownCloud 9.1 as admin. Myself as a user has unlimited space.
Owncloud files are saved on a new blank 1TB external USB disk.
The web interface (ownCloud 9.1) display a top notice saying "Your storage is almost full (95%)"
The Mac OSX client (version 2.2) says "3.8 GB of 4 GB in use".
Is that related to this bug?
