### ISSUE TITLE
Fatal error since upgrade to 8.1.3

### ISSUE THREAD

**Issue by africanforest** [owncloud/core#19171]
After update from 8.1.1 to 8.1.3 i'm getting the following fatal error in my logfiles.
What does that mean? Can i ignore it? Actually, i have no choice since i'm running OwnCloud on a shared host.

Exception: {"Message":"HTTP\/1.1 500 An exception occurred while executing 'SELECT `fileid`, `storage`, `path`, `parent`, `name`, `mimetype`, `mimepart`, `size`, `mtime`,\n\t\t\t\t\t `storage_mtime`, `encrypted`, `etag`, `permissions`\n\t\t\t\tFROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ?' with params [\"1\", \"4c30131b52d71313537abe00ee30261c\"]:\n\nSQLSTATE[HY000]: General error: 2006 MySQL server has gone away","Code":0,"Trace":"#0 \/home\/.sites\/web\/cloud\/lib\/private\/connector\/sabre\/file.php(102): OC\\Connector\\Sabre\\File->convertToSabreException(Object(Doctrine\\DBAL\\Exception\\DriverException))\n#1 \/home\/.sites\/web\/cloud\/lib\/private\/connector\/sabre\/directory.php(113): OC\\Connector\\Sabre\\File->put(Resource id #256)\n#2 \/home\/.sites\/web\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1053): OC\\Connector\\Sabre\\Directory->createFile('flo_fotobuch.zi...', Resource id #256)\n#3 \/home\/.sites\/web\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(513): Sabre\\DAV\\Server->createFile('SYNC\/flo_fotobu...', Resource id #256, NULL)\n#4 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \/home\/.sites\/web\/cloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#6 \/home\/.sites\/web\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#7 \/home\/.sites\/web\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#8 \/home\/.sites\/web\/cloud\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n#9 \/home\/.sites\/web\/cloud\/remote.php(132): require_once('\/home\/.sites\/95...')\n#10 {main}","File":"\/home\/.sites\/web\/cloud\/lib\/private\/connector\/sabre\/file.php","Line":459}

**Comment by PVince81** [comment]
How did you update ? (distro package manager, updater app or manually extracted tarball)

This error means that the MySQL server is not running.

**Comment by africanforest** [comment]
The update module did not work (it said unknown server error without further explanation), so i copied all files to the istall directory overwriting the old ones. Finally i performed the update process by clicking the update button on the login screen.
Actually OwnCloud works as well all modules. I notices the errors occurring sometimes every minute, sometime an hour later. Do you think, this is a problem caused by the server of my hoster?

**Comment by RealRancor** [comment]
> MySQL server has gone away

That mostly means that there is a timeout happening within your MySQL server. See this for some basic pointers:

https://doc.owncloud.org/server/8.1/admin_manual/issues/index.html#common-problems-error-messages

**Comment by PVince81** [comment]
@africanforest don't overwrite existing files. You need to delete the old source code and then extract the new one. A mix of old files and new files is likely to cause trouble.

**Comment by africanforest** [comment]
Ok, so i would have to delete everything exept for would have to keep the folders

config
data
themes

but what should i do with the apps folder before upgrading in order to avoid data loss related to installed apps?

**Comment by RealRancor** [comment]
@africanforest Yes, that would be the correct way to upgrade.

You won't have any dataloss of apps as their data is either saved in the database or within the /data directory. You only need to enable the apps again to pull the new, compatible apps from the appstore.

**Comment by africanforest** [comment]
Great, thanks a lot for your help! 
And sorry for being off topic with my question...
