### ISSUE TITLE
Oracle: OCA\Files_sharing\Tests\EtagPropagation very slow

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#19180]
Oracle: 5.5 minutes (https://ci.owncloud.org/job/core-ci-linux/database=oci,label=SLAVE/1553/testReport/(root)/OCA_Files_sharing_Tests_EtagPropagation/)
MySQL: 21 seconds
PGSQL: 19 seconds
SQLite: 12 seconds

Something is seriously wrong here.

cc @DeepDiver1975 @cmonteroluque

**Comment by LukasReschke** [comment]
When I execute just these tests on it's own then there is not really a big performance difference. Seems to be a bigger underlying problem. Very very strange…

Let me see what happens if I compare the whole test suite using blackfire.

**Comment by PVince81** [comment]
Is there still something seriously wrong or has it improved a bit ?

**Comment by nickvergessen** [comment]
https://ci.owncloud.org/job/core-ci-linux/database=oci,label=SLAVE/29526/testReport/%28root%29/OCA_Files_sharing_Tests_EtagPropagation/ 4min 50 secs

**Comment by PVince81** [comment]
@DeepDiver1975 what do you think ?

**Comment by DeepDiver1975** [comment]
We need to have a closer look with the current code codebase and on the new ci server.

There is for sure room for improvement

**Comment by PVince81** [comment]
Etag propgation should be much faster since OC 9.0 where propagation is done only on the current storage and a combined etag is computed.

**Comment by PVince81** [comment]
I'm moving this to backlog now until someone has time to look into the details. @DeepDiver1975 @butonic

**Comment by PVince81** [comment]
Closing as potentially obsolete, in OC 9.0 etag propagation is done in a much more efficient way using direct DB queries. I remember even seeing a black magic one for Oracle.

So this is likely fixed.
