### ISSUE TITLE
Attempt to upgrade to 8.1.3 breaks owncloud

### ISSUE THREAD

**Issue by Aesculapius** [owncloud/core#19185]
### Steps to reproduce
1. Try to update owncloud via Webgui updater app
2. After waiting 5 minutes of nothing, I tried to run the command line updater /occ upgrade
3. This only shows the line "ownCloud or one of the apps require upgrade - only a limited number of commands are available". For over 10 minutes now.

### Expected behaviour
The web updater should have worked and should have given more verbal information about its process. Yet the command line upgrade command should have always worked and at least show what is wrong...

### Actual behaviour
Not getting feedback from web updater, and getting too little feedback from command line app. It is just hanging and doing nothing. With htop, I do not see any processor intensive processes running. I cannot find any log file which gives more information.

I've tried running the  sudo -u www-data php occ maintenance:repair command but that only shows:
ownCloud or one of the apps require upgrade - only a limited number of commands are available
 - Repair mime types

and then also hangs for 10 minutes of nothing.

I've downloaded a fresh copy of owncloud, chowned everything to the right apache user and copied the config.php file again. Rerunning the cli upgrade command doesn't change its behavior.

### Server configuration
**Operating system**: Ubuntu 14.04.2 LTS

**Web server:** Apache 2.4.7

**Database:** MySql

**PHP version:** 5.5.9

**ownCloud version:** (see ownCloud admin page) was 8.1.1, going to 8.1.3

**Updated from an older ownCloud or fresh install:** update

**List of activated apps:**

Enabled:
 - files: 1.1.10
 - files_sharing: 0.6.2
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - provisioning_api: 0.2

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => '5141c1f0028db',
  'passwordsalt' => 'randomsalt',
  'datadirectory' => '/yoda/cloudstore/data/',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'dbname' => 'db_owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'secret',
  'overwritewebroot' => '/',
  'installed' => true,
  'forcessl' => true,
  'maintenance' => true,
  'trashbin_retention_obligation' => '30',
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'theme' => '',
  'has_internet_connection' => true,
  'check_for_working_webdav' => true,
  'check_for_working_htaccess' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'trusted_domains' =>
  array (
    0 => 'arc.domain.nl',
  ),
  'mail_from_address' => 'info',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'mydomain.nl',
  'secret' => 'justsomesecret',
  'asset-pipeline.enabled' => true,
  'preview_max_scale_factor' => 1,
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\Image',
    1 => 'OC\\Preview\\Illustrator',
    2 => 'OC\\Preview\\Postscript',
    3 => 'OC\\Preview\\Photoshop',
    4 => 'OC\\Preview\\TIFF',
    5 => 'OC\\Preview\\TXT',
    6 => 'OC\\Preview\\MarkDown',
    7 => 'OC\\Preview\\MSOffice2003',
    8 => 'OC\\Preview\\MSOffice2007',
    9 => 'OC\\Preview\\MSOfficeDoc',
    10 => 'OC\\Preview\\OpenDocument',
    11 => 'OC\\Preview\\StarOffice',
    12 => 'OC\\Preview\\SVG',
  ),
  'forceSSLforSubdomains' => true,
  'app.mail.server-side-cache.enabled' => true,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
disabled

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

Right now, the installation is useless. Can anyone pinpoint me in the right direction of what is going wrong here?

**Comment by RealRancor** [comment]
Hi,

> Can anyone pinpoint me in the right direction of what is going wrong here?

the data/owncloud.log as pointed out in the issue template you have used could be a starting point.

**Comment by Aesculapius** [comment]
Additional info: when running cli with -vvv, it shows this - so can I assume that I have a config corruption or something?

┌(arc)─[/var/www_ssl]
└─(26 files, 204Kb)─> sudo -u www-data php occ upgrade -vvv
ownCloud or one of the apps require upgrade - only a limited number of commands are available
Turned on maintenance mode
Repair step: Repair MySQL database engine
Repair step: Repair MySQL collation
Repair step: Repair SQLite autoincrement
Repair step: Repair duplicate entries in oc_lucene_status
Repair info: removing duplicate entries from lucene_status
Repair step: Repair config

**Comment by Aesculapius** [comment]
@RealRancor the log file is only filled with these lines of webdav not being available:

{"reqId":"aV4uTP+th70TQDHFh\/uz","remoteAddr":"ip-addr","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Service unavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www_ssl\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/var\\\/www_ssl\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www_ssl\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www_ssl\\\/remote.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www_ssl\\\/remote.php(135): handleException(Object(RemoteException))\\n#6 {main}\",\"File\":\"\\\/var\\\/www_ssl\\\/remote.php\",\"Line\":55}","level":4,"time":"2015-09-19T09:35:46+00:00"}

**Comment by Aesculapius** [comment]
The problem seems to be some kind of indefinite loop, where the "repair config" step is duplicating the oc_filecache table in the database to other oc_oc_filecache tables. It keeps doing this, where I just cancelled the process once the db reached 4GB in size!

The only thing I can imagine is that this has to do with the external_files app, with which I had previously linked to a local folder containing hardlinks with backups (hourlies, dailies, monthlies). If it is trying to comprehend all that info it can indeed grow indefinitely. 

Now, can I safely remove those oc_oc_filecache tables in the database? And can I safely truncate the original oc_filecache table (or will this for example break shared links?).

For now I've already disabled the external_files app, but that doesn't solve what's already in there.

**Comment by LukasReschke** [comment]
cc @icewind1991 Any idea?

**Comment by Aesculapius** [comment]
I managed to revert the installation to its current 8.1.1 using backups. Just wanted to stay away from updating as the system is needed in some critical usecases. To support those, I just wanted to add the documents app to the installation, only to notice that that forced an update process also. This has the same problem, leading me to the conclusion that at least this hasn't to do with 8.1.3 specific, but is present in previous update mechanisms also...

**Comment by PVince81** [comment]
>The problem seems to be some kind of indefinite loop, where the "repair config" step is duplicating the oc_filecache table in the database to other oc_oc_filecache tables. It keeps doing this, where I just cancelled the process once the db reached 4GB in size!

This is the "DB update simulation" step. It duplicates the table with its contents then tries applying the new schema on it.

You can skip it by passing `--skip-migration-test` to the `./occ upgrade` command.
But as I see you were using the updater app which AFAIK doesn't provide an option to disable it.

CC @VicDeo

**Comment by RealRancor** [comment]
@PVince81 From my knowledge the updater app is not doing any database upgrades or am i wrong? You still can run the occ command after the updater has updated the core files?

**Comment by PVince81** [comment]
Right, the updater app just redirects to the page that asks you to click "Start upgrade".
When doing updates over the web UI you cannot disable migration testing.

**Comment by PVince81** [comment]
Mimetype repair was improved to run faster in 8.2 and 9.0 will come with a revamped updater app.

If you're still having issues, please reopen.
