### ISSUE TITLE
External storage deleted and no longer works after 8.1.3 upgrade

### ISSUE THREAD

**Issue by keynet** [owncloud/core#19187]
<h4>Server:</h4>
SLES 11 SP4 / PHP 5.6.9

<h4>Steps taken:</h4>
Upgrade failed via repository route due to issues mentioned elsewhere (packages being recombined)
Installed fresh copy of 8.1.3  via tarball, set permissions on files to Apache's
Automatic database upgrade worked OK
However external storage (local files) deleted. 
When re-adding, green light comes on momentarily, then goes red.
Log excerpt below for any directory attempted, including ones with full permissions
Bug, problem with the database, or other?
```
Sep 19 12:40:25 ha-server ownCloud[11123]: {PHP} Undefined index: owner at /srv/www/htdocs/owncloud/apps/files/index.php#140
Sep 19 12:40:25 ha-server ownCloud[11123]: {PHP} Undefined index: ownerDisplayName at /srv/www/htdocs/owncloud/apps/files/index.php#141
Sep 19 12:40:25 ha-server ownCloud[11123]: {PHP} Undefined index: owner at /srv/www/htdocs/owncloud/apps/files/lib/helper.php#56
Sep 19 12:40:25 ha-server ownCloud[11123]: {PHP} Undefined index: ownerDisplayName at /srv/www/htdocs/owncloud/apps/files/lib/helper.php#57
Sep 19 12:40:28 ha-server ownCloud[11476]: {PHP} Array to string conversion at /srv/www/htdocs/owncloud/lib/private/template/functions.php#36
Sep 19 12:40:48 ha-server ownCloud[11587]: {PHP} file_put_contents(data/mount.json): failed to open stream: No such file or directory at /srv/www/htdocs/owncloud/apps/files_external/lib/config.php#711
Sep 19 12:40:48 ha-server ownCloud[11587]: {PHP} chmod(): No such file or directory at /srv/www/htdocs/owncloud/apps/files_external/lib/config.php#712
```
Thanks

**Comment by Xenopathic** [comment]
> file_put_contents(data/mount.json): failed to open stream: No such file or directory at /srv/www/htdocs/owncloud/apps/files_external/lib/config.php#711

This indicates that your data directory is incorrectly set. I think you may be using a relative path in config.php? A full bug report as per the issue template would really help...

**Comment by keynet** [comment]
Thanks - that was it 
In config.php, it has been 'data/mount.json' since 2013
So I changed the config.php file to absolute as follows, and the external storage mounts have now reappeared
'mount_file' => '/mnt/lvm/owncloud/mount.json',
Per SLES, the webserver is Apache 2.2.12 / database mysql  5.5.43, and as I reinstalled it, no external apps are loaded
Config.php is 
```
<?php
define('DEBUG',true);
$CONFIG = array (
  'instanceid' => 'xxxxxxxxxxxxxxxx',
  'passwordsalt' => 'xxxxxxxxxxxxxxxxxxxxxx',
  'trusted_domains' => 
  array (
    0 => 'xxxxxxxxxxxxxxxx',
    1 => 'oc.ha-server.lan',
  ),
  'datadirectory' => '/mnt/lvm/owncloud',
  'version' => '8.1.3.0',
  'dbtype' => 'mysql',
  'dbhost' => '127.0.0.1',
  'dbname' => 'owncloud',
  'dbuser' => 'oc_admin',
  'dbpassword' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'dbtableprefix' => 'oc_',
  'installed' => true,
  'default_language' => 'en',
  'defaultapp' => 'files',
  'knowledgebaseenabled' => true,
  'enable_avatars' => false,
  'allow_user_to_change_display_name' => true,
  'remember_login_cookie_lifetime' => 1296000,
  'session_lifetime' => 86400,
  'session_keepalive' => true,
  'skeletondirectory' => '',
  'user_backends' => 
  array (
  ),
  'mail_domain' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'mail_from_address' => 'owncloud',
  'mail_smtpdebug' => false,
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => '127.0.0.1',
  'mail_smtpport' => '25',
  'mail_smtptimeout' => 10,
  'overwritehost' => '',
  'overwriteprotocol' => '',
  'overwritewebroot' => '',
  'overwritecondaddr' => '',
  'overwrite.cli.url' => '',
  'trashbin_retention_obligation' => 90,
  'trashbin_auto_expire' => true,
  'appcodechecker' => true,
  'updatechecker' => true,
  'has_internet_connection' => true,
  'check_for_working_webdav' => true,
  'check_for_working_htaccess' => true,
  'log_type' => 'syslog',
  'logfile' => 'owncloud.log',
  'loglevel' => 0,
  'logdateformat' => 'F d, Y H:i:s',
  'logtimezone' => 'Europe/London',
  'log_query' => false,
  'cron_log' => true,
  'log_rotate_size' => false,
  '3rdpartyroot' => '',
  '3rdpartyurl' => '',
  'customclient_desktop' => 'http://owncloud.org/sync-clients/',
  'customclient_android' => 'https://play.google.com/store/apps/details?id=com.owncloud.android',
  'customclient_ios' => 'https://itunes.apple.com/us/app/owncloud/id543672169?mt=8',
  'appstoreenabled' => true,
  'appstoreurl' => 'https://api.owncloud.com/v1',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/srv/www/htdocs/owncloud/apps',
      'url' => '/apps',
      'writable' => true,
    ),
  ),
  'enable_previews' => true,
  'preview_max_x' => NULL,
  'preview_max_y' => NULL,
  'preview_max_scale_factor' => 10,
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'preview_office_cl_parameters' => ' --headless --nologo --nofirststartwizard --invisible --norestore -convert-to pdf -outdir ',
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\Image',
    1 => 'OC\\Preview\\MP3',
    2 => 'OC\\Preview\\TXT',
    3 => 'OC\\Preview\\MarkDown',
  ),
  'maintenance' => false,
  'singleuser' => false,
  'forcessl' => false,
  'openssl' => 
  array (
    'config' => '/absolute/location/of/openssl.cnf',
  ),
  'blacklisted_files' => 
  array (
    0 => '.htaccess',
  ),
  'theme' => '',
  'xframe_restriction' => true,
  'cipher' => 'AES-256-CFB',
  'minimum.supported.desktop.version' => '1.7.0',
  'memcache.distributed' => '',
  'memcached_servers' => 
  array (
    0 => 
    array (
      0 => 'localhost',
      1 => 11211,
    ),
  ),
  'cache_path' => '',
  'quota_include_external_storage' => true,
  'filesystem_check_changes' => 1,
  'asset-pipeline.enabled' => false,
  'mount_file' => '/mnt/lvm/owncloud/mount.json',
  'filesystem_cache_readonly' => false,
  'supportedDatabases' => 
  array (
    0 => 'sqlite',
    1 => 'mysql',
    2 => 'pgsql',
    3 => 'oci',
    4 => 'mssql',
  ),
  'custom_csp_policy' => 'default-src \'self\'; script-src \'self\' \'unsafe-eval\'; style-src \'self\' \'unsafe-inline\'; frame-src *; img-src *; font-src \'self\' data:; media-src *',
  'secret' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
);

```

**Comment by RealRancor** [comment]
@keynet Seems you have copied the config.sample.php to config.php in the past? Please note this is not supported and can cause various issues / problems.

**Comment by keynet** [comment]
Actually I remember customising it quite a lot in the past - but one has to start with a good template right ? Anyway OC keeps rewriting bits of it during upgrades as you can see, so who am I to doubt it ?

**Comment by RealRancor** [comment]
Most of the stuff in there are definitely not written by oC and the config.sample.php shouldn't be used as a template

**Comment by keynet** [comment]
Run a diff. You'll be disappointed, I couldn't find any that are not in the sample....
"...manually copy configuration switches that you consider important for your instance to your working ``config.php``, and* apply configuration options that are pertinent for your instance."
- Which is what I did !

Anyway the 1 that gave me trouble is clearly an error - the sample shows it as a relative path, nothing  says it must be absolute, it's worked this way for over 2yrs.
In the key directly above (assetdirectory) an absolute path is clearly shown. 
If it needs to be so, then seems logical to say so

Rather than spend time telling me I'm stupid, why not spend the time to fix the problem ?

**Comment by RealRancor** [comment]
> Run a diff. You'll be disappointed, I couldn't find any that are not in the sample....

Thats the problem. You shouldn't use any of the ones from the sample as most of the ones you're using are just copied over and this can cause issues in future updates if defaults needs to be changed.

But if you don't want to follow the advice of an experienced user feel free. I'm out of here and have learned again that some people think they are too clever for the world and don't need to listen to advices of others :hear_no_evil:

**Comment by Xenopathic** [comment]
The settings in config.sample.php were never guaranteed to work, in fact in many cases they aren't even sensible defaults. Note `openssl` in your config.php, it's completely wrong (unless your openssl.cnf really *is* at /absolute/location/of/openssl.cnf). In newer versions of oC we have explicitly disallowed using config.sample.php as a beginning template, but even prior to that it was never recommended, and the comments at the top of the file highly discouraged it.

**Comment by keynet** [comment]
I don't get it, I exactly followed the instructions to "manually copy configuration switches..." 
I reviewed each and every line, the best I could, without reading every line of OC code. 
What else to do? 
And no, of course I'm not using /absolute/location/of/openssl.cnf - I use nss not openssl.

**Comment by RealRancor** [comment]
@keynet You need to see the config.sample.php as a documentation of the possible config switches which are already defaults used within oC when not added/included in your config.php.

A sane / default config.php for example is:

```
<?php
$CONFIG = array (
  'instanceid' => 'redacted',
  'passwordsalt' => 'redacted',
  'secret' => 'redacted',
  'trusted_domains' => 
  array (
    0 => '127.0.0.1',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'overwrite.cli.url' => 'http://127.0.0.1/owncloud',
  'dbtype' => 'sqlite3',
  'version' => '8.1.0.7',
  'installed' => true,
);

Only add additional stuff in there if you actually want to change them from the defaults. For example adding this here:

```
  'customclient_desktop' => 'http://owncloud.org/sync-clients/',
  'customclient_android' => 'https://play.google.com/store/apps/details?id=com.owncloud.android',
  'customclient_ios' => 'https://itunes.apple.com/us/app/owncloud/id543672169?mt=8',
  'appstoreurl' => 'https://api.owncloud.com/v1',
```

doesn't make any sense as those are the defaults anyway. And if those URLs get changed in the future you're ending up with broken links or in case of the appstoreurl with a not working oC internal appstore.

**Comment by keynet** [comment]
OK! 
Thanks - now this making sense.
Can I suggest the docs are amended slightly to make it clear which ones SHOULD be left alone?
I didn't pick up what you're saying from the config.php in the admin manual.
It says "These parameters are configured by the ownCloud installer, and are required for your ownCloud server to operate." then lists pretty much all of them.
 I want most of the optional functions, and certainly didn't pick up that, for example,<b>appstoreurl</b> should be left alone. 
I mean as admin I want to be able to install Apps, so following the wording "When enabled, admins may install apps from the ownCloud app store".  
I would expect to set it - but you're saying don't ?

**Comment by RealRancor** [comment]
Hi,

if you think there are some details missing at the page here:

https://doc.owncloud.org/server/8.1/admin_manual/configuration_server/config_sample_php_parameters.html

feel free to make a suggestion at the issue tracker of the documentation:

https://github.com/owncloud/documentation/issues

**Comment by keynet** [comment]
Will do if I find anything that I feel confident enough to submit. 
Without knowing the code it's not so easy...

**Comment by RealRancor** [comment]
Hi,

you don't need to submit code for this. :)

Just submit your experience while reading this. You could even post the text from your last comment into a new issue at the documentation tracker.

I think its always good to have such experience posted there.

**Comment by RealRancor** [comment]
@keynet Hope this clarify this in more details: https://github.com/owncloud/documentation/pull/1681

**Comment by keynet** [comment]
I see you're having a good debate! And I don't think the users are quite as stupid as some suggest - they just don't know the code (my point above) like the devs, and can't be expected to.

I think the approach can be improved  - IMHO the config file is trying to do too many things:
a) Holding parameters that are user configurable and not changed by OC
e.g 'mail_domain' => 'example.com',
b) Holding parameters that are system dependent and/or version dependent
e.g  'version' => '7.0.2.1'
c) Holding parameters that can get (over)written by OC while running or at update time
e.g.  'mail_from_address' => 'owncloud',

Trying to do so many things in 1 file is too difficult IMHO.
My suggestion is to have separate configs for the separate use cases. Also improves security as the owner can be set to root or at least read only for the fixed params.

I also think the documentation has too many (yes too many) words. I know someone is trying to explain, but it would IMHO be better to have a table that lists, for each parameter:
Name, description, default setting, updated by OC (when)?, Notes (big fat warnings etc)

My example is mkvtoolnix, but even he could add more columns as I suggest above to help clarity
https://www.bunkus.org/videotools/mkvtoolnix/doc/mkvmerge.html

HTH

**Comment by Xenopathic** [comment]
@keynet Yes, we've known for quite a while that config.php is becoming very bloated. We need to find a long-term solution for that...
