### ISSUE TITLE
After Upgrade to 8.1.3

### ISSUE THREAD

**Issue by tetam** [owncloud/core#19184]
Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'DELETE FROM `oc_queuedtasks` WHERE `app`=?' with params ["search_lucene"]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.oc_queuedtasks' doesn't exist

**Comment by RealRancor** [comment]
Dup of https://github.com/owncloud/search_lucene/issues/90, https://github.com/owncloud/core/issues/18327, https://github.com/owncloud/core/issues/18247, https://github.com/owncloud/core/issues/18712

**Comment by RealRancor** [comment]
Ah, btw. this needs a new release of search_lucene at the appstore including the fix of https://github.com/owncloud/search_lucene/issues/102
