### ISSUE TITLE
Notify/Show owner of all share permissions

### ISSUE THREAD

**Issue by godspeed20** [owncloud/core#19188]
Couldn't see this posted before so apologies if it is, and it looks like it affects all version.

Take the following scenario:

User A shares folder X with Users B and C. Allows user B to share it further.
User B shares folder X with User D.
User A can only see that the folder is shared with Users B and C. User B can only see that User A shared the folder to them, and that they have shared the folder to User D.

Ideally, User A (the owner) should be able to see that folder X has been shared with User D, and be able to remove that share. The owner should have an overriding view of all shares of their folder.

**Comment by rullzer** [comment]
This will be part of the sharing 2.0 (#13014).

**Comment by PVince81** [comment]
This is done in 9.0 as part of https://github.com/owncloud/core/issues/9058
