### ISSUE TITLE
Upgrade can't find calendar

### ISSUE THREAD

**Issue by ggemmill** [owncloud/core#19192]
Environment: Mageia 5
Trying to upgrade from Owncloud 8.0.8 installed from Mageia repository to Owncloud 8.1.1 installed from tarball.
Upgrade fails with the following messages:
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Updated "updater" to 0.6
Updated "files" to 1.1.10
Updated "activity" to 2.0.1
Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "calendar_index" as such route does not exist.
I hope for a quick resolution because I have no access to the active calendar (and I can't remember what's happening next week!).
Thanks
Graeme

**Comment by RealRancor** [comment]
Dup of tons of already reported issues here. Please close and follow the still open issue here: https://github.com/owncloud/core/issues/19145

**Comment by Xenopathic** [comment]
As a temporary workaround, try the upgrade again, it will succeed. We are tracking the problem in #19145

**Comment by ggemmill** [comment]
On 19/09/15 19:02, Robin McCorkell wrote:
>
> As a temporary workaround, try the upgrade again, it will succeed. We 
> are tracking the problem in #19145 
> <https://github.com/owncloud/core/issues/19145>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/owncloud/core/issues/19192#issuecomment-141693911>.
>
Sorry for the duplication - many thanks.
Graeme
