### ISSUE TITLE
Smashbox is having troubke on stable8.1 ... is it the docker?

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#19198]
https://ci.owncloud.org/view/translation-sync/job/smashbox-on-docker-daily-stable8.1/42/DOCKER_IMAGE=ubuntu_oc_lamp_redis,TEST_NAME=test_uploadFiles,compiler=g++,label=master,mirallBranch=v1.8.3,qt=qt4,serverVersion=daily-stable8.1,slave=SMASH/console

**Comment by MorrisJobke** [comment]
https://ci.owncloud.org/job/smashbox-on-docker-daily-stable8.1/ <- green again
