### ISSUE TITLE
Error upgrading after ip address of computer has changed

### ISSUE THREAD

**Issue by Dommeltje** [owncloud/core#19194]
Hi all,

Owncloud runs flawlessly on an Olimex Lime creditcard size computer since one and a half year now.
Some time ago I changed the ip address of the Olimex from 192.168.0.3 to 192.168.0.102, without any problem.
I'm now trying to upgrade owncloud from 8.0.0 to 8.1.3 using Update Center.
It hangs forever.
In nginx error.log I get the following message:
2015/09/19 17:33:13 [error] 2118#0: *5201 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.0.3, server: , request: "POST /index.php/apps/updater/ajax/download.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "192.168.0.102", referrer: "https://192.168.0.102/index.php/apps/updater/update.php".
It seems the Update Center finds the obsolete ip address somewhere and tries using it.

**Comment by Xenopathic** [comment]
Please fill out the issue template.

**Comment by MorrisJobke** [comment]
I will close this due to inactivity. Please reopen this ticket if you have the requested information - issue template can be found at https://github.com/owncloud/core/blob/master/issue_template.md

Especially the owncloud.log in the data folder is of interest.

Thanks.
