### ISSUE TITLE
Can't set cookie in middleware when ownCloud is not installed in a folder

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19196]
### To test this

1. Launch the VM
2. Add cookie setting code to middleware of an app and redirect to a page (https://github.com/owncloud/gallery/blob/master/middleware/checkmiddleware.php#L150-L159)
3. Add code to landing page which reads the cookie (https://github.com/owncloud/gallery/blob/master/controller/pagecontroller.php#L134-L148)
4. Go to localhost/owncloud/trigger.php

You get the cookie

5. Go to localhost/trigger.php

Now you don't

### Notes
It's a simple way to test this, but if you want to discard the methodology, then just set up 2 different instances, one installed in a folder and one installed at / and you'll get the same results.

The problem doesn't happen if you set a cookie in a controller.

Happens on both master and stable8.1

Reminds me of https://github.com/owncloud/core/pull/19010

@LukasReschke @BernhardPosselt @nickvergessen @Xenopathic

**Comment by LukasReschke** [comment]
Same issue - yes.

**Comment by oparoz** [comment]
I wonder if this isn't also the cause of https://github.com/owncloud/core/issues/18891

**Comment by cmonteroluque** [comment]
is this resolved?

**Comment by LukasReschke** [comment]
Let me try to hook up a debugger on iOS then.

@cmonteroluque - not yet. Will dig into this tomorrow.

**Comment by cmonteroluque** [comment]
@LukasReschke thanks!

**Comment by DeepDiver1975** [comment]
@LukasReschke any update on this? THX
