### ISSUE TITLE
Desktop Client for Debian 8 downloading old version from repository

### ISSUE THREAD

**Issue by Melonhead55** [owncloud/core#19199]
I just switched over to Debian 8 and I used the repository from the owncloud site to download the desktop client. I noticed that doing this downloads client version 1.6.4. is there another way to download the latest version?

I'm checking due to a "Wrong credentials" error on login (confirmed credentials are correct) and the fix that I've found is to update the client.

**Comment by RealRancor** [comment]
Hi,

please ask such support questions at either the user mailinglist or the forums. This tracker here is used for bugs within the oc server.

**Comment by Kawohl** [comment]
This was not reproducable for me and it is in the wrong github-repo. 

Closed

**Comment by Kawohl** [comment]
@Melonhead55 I assume your repo configuration is wrong. Please check.
