### ISSUE TITLE
Directories downloaded as Zip archive cannot be opened on Linux/KDE with ark

### ISSUE THREAD

**Issue by cthil** [owncloud/core#19205]
### Steps to reproduce
1. Download a set of files/a directory as a Zip archive

### Expected behaviour
Zip file should be readable with the default archiver on KDE, *ark*

### Actual behaviour
*ark* reports a corrupt Zip archive. The directory tree is displayed, but files cannot be extracted.

![ark](https://cloud.githubusercontent.com/assets/8024840/9986895/1de96e60-6042-11e5-9983-b3a4f95b3fa2.png)

### Server configuration

Managed server at Domainfactory (http://df.eu/)

**Web server:**
Apache/2.4.10

**Database:**
MySQL 5.6.19-67.0-log

**PHP version:**
PHP Version 5.6.2

**ownCloud version:** (see ownCloud admin page)
8.1

**Updated from an older ownCloud or fresh install:**
fresh

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Chromium 43
ark 2.19

**Operating system:**
Debian Testing stretch/sid with KDE 4.14.2 (current)

**Comment by cthil** [comment]
This might be related to #10001 but I cannot comment there as the discussion is locked.

**Comment by LukasReschke** [comment]
This seems like an upstream issue, can you report this at https://github.com/McNetic/PHPZipStreamer and provide as well one of those ZIP files? THX.

**Comment by McNetic** [comment]
This is a duplicate of #16656.
