### ISSUE TITLE
No error message on corrupted file while making a zip file 

### ISSUE THREAD

**Issue by davodego** [owncloud/core#19203]
**Steps to reproduce**

Put a broken file in a folder.
Click download behind the folder with the broken file. 
The downloaded zip file not includes the folders content.

**Expected behavior**

Zip file will not be created when a broken file was in a folder. A error message appears.

**Actual behavior**

When click on "download" behind the folder a zip file was created to download. When I open the file I dont found the content of the folder, I found files named "[Content_Types].xml" an three folders: "_rels", "docProbs" and "word". When I click on "Download All" in upper right corner it is the same.

In my case, there was a corrupted pdf file in the folder. After removing the broken file, all works as expected. It takes a long time for me to spy out what happens. I downloaded file by file and on this pdf file an error message was shown.

**Server configuration**

Operating system: Debian 7

Web server: Apache

Database: MySQL 

PHP version: 5.4.x

ownCloud version: 7.0.6.2

Updated from an older ownCloud or fresh install: Updated

List of activated apps: 

The content of config/config.php:

Are you using external storage, if yes which one: YES, local/webdav/hubiC

Are you using encryption: YES

Client configuration

Browser: Firefox, Chrome

Operating system: Windows; Linux

**Logs**

Web server error log: nothing in log

ownCloud log: nothing in log

**Comment by LukasReschke** [comment]
What is a "broken file"?

**Comment by davodego** [comment]
Sorry for bad engish. 
I mean corrupted or damaged file.

**Comment by MorrisJobke** [comment]
Could I ask you to provide a "corrupted file"? I can't reproduce this locally.

I will reopen this ticket once we know more about this corrupted file that is causing issues here.

Thanks
