### ISSUE TITLE
Update from 8.1.1-1 to 8.1.3-13-1 breaks packages

### ISSUE THREAD

**Issue by pludi** [owncloud/core#19209]
### Steps to reproduce
1. Install `owncloud-{server,3rdparty}=8.1.1-1` on Debian Jessie
2. Run `apt-get upgrade`

### Expected behaviour
Clean update, with the old separate app packages being removed, which could be easily done by using the [Replaces](https://www.debian.org/doc/debian-policy/ch-relationships.html#s-replaces) keyword in the `control` file

### Actual behaviour
Errors about the update breaking the app packages, as will happen when just the server package is updated, but none of the app packages depending on it.

### Server configuration
**Operating system**: Debian 8.1 Jessie

**Web server:** nginx 1.6.2

**Database:** PostgreSQL 9.4.4

**PHP version:** 5.6.13

**ownCloud version:** (see ownCloud admin page) 8.1.1.3

**Updated from an older ownCloud or fresh install:** yes, since ownCloud 7

**List of activated apps:**
 - activity: 2.0.1
 - calendar: 0.7.2
 - contacts: 0.4.0.0
 - documents: 0.10.1
 - files: 1.1.10
 - files_external: 0.2.3
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - gallery: 0.6.0
 - notes: 0.9
 - tasks: 0.7.1
 - user_pwauth: 2.1

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => 'ocfec16d395d',
  'trusted_domains' =>
  array (
    0 => 'oc.xxx.yyy',
  ),
  'datadirectory' => '/srv/www/owncloud/data',
  'dbtype' => 'pgsql',
  'version' => '8.1.1.3',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'forcessl' => false,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'owncloud',
  'mail_domain' => 'xxx.yyy',
  'log_type' => 'owncloud',
  'logfile' => 'owncloud.log',
  'loglevel' => '0',
  'overwriteprotocol' => 'https',
  'overwritewebroot' => '/',
  'overwrite.cli.url' => '/',
  'mail_smtpsecure' => 'tls',
  'mail_smtpauthtype' => 'PLAIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'xxx.yyy',
  'mail_smtpport' => '25',
  'mail_smtpname' => 'owncloud@xxx.yyy',
);

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** PAM

**Comment by LukasReschke** [comment]
@jnweiger

**Comment by RealRancor** [comment]
@LukasReschke Already discussed here: https://github.com/owncloud/core/issues/19124

**Comment by LukasReschke** [comment]
@RealRancor THX.

**Comment by jnweiger** [comment]
@pludi, as you mentioned the Replaces keyword, do you believe this control file should do the job:

We have Replaces:, Conflicts:, Provides: there
https://build.opensuse.org/package/view_file/isv:ownCloud:community:8.1:testing/owncloud/debian.control?expand=1

**Comment by pludi** [comment]
I'm not an complete expert here, but AFAIK as soon as you have `Replaces` in there you can leave out `Breaks` and/or `Conflicts`. So far I've only seen `Replaces` with `Breaks` if a package was split into multiple packages (eg. from one package into platform dependend and independent packages), and `Conflicts` for packages providing the same service (eg. MTAs or web servers).

I'd have suggested asking the [debian-webapps](https://lists.debian.org/debian-webapps/) mailing list, but for all intents and purposes it's dead.
