### ISSUE TITLE
Allowed memory size of * exhausted after update to 8.1.3

### ISSUE THREAD

**Issue by DominuS-RU** [owncloud/core#19202]
Hi! I'm having an error:
Fatal error: Allowed memory size of 262144 bytes exhausted (tried to allocate 12288 bytes) in /var/www/cloud/lib/base.php on line 136
I've tried to increase memory_limit in my php.ini, but it did't help me to solve this. How can I do it?

**Comment by RealRancor** [comment]
Hi,

your current limit of 0,25 MB is far below any recommendations of memory limits. Set it to at least 128MB or even better to 512 MB when using stuff like the Gallery.

**Comment by nickvergessen** [comment]
Also after changing the value in php.ini restart your web server

**Comment by DominuS-RU** [comment]
I have already changed memory_limit value everywhere to 512M, but nothing happened
