### ISSUE TITLE
Error message during DB update to OC version 8.1.3

### ISSUE THREAD

**Issue by PartisanEntity** [owncloud/core#19206]
I used the built in update feature of OC.

I started the database update and got this message: Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "calendar_index" as such route does not exist.

After running the DB update a second time it worked.

**Comment by RealRancor** [comment]
Dup of https://github.com/owncloud/core/issues/18350, https://github.com/owncloud/core/issues/18334, https://github.com/owncloud/core/issues/18333, https://github.com/owncloud/core/issues/18317, https://github.com/owncloud/core/issues/18329, https://github.com/owncloud/core/issues/18296, https://github.com/owncloud/core/issues/18224, https://github.com/owncloud/core/issues/19192 and many more...

#18224 contains the ongoing discussion. A workaround is to run the upgrade routine again.

**Comment by Xenopathic** [comment]
Thanks @RealRancor
