### ISSUE TITLE
Thumbnail is not updated, when restoring a file

### ISSUE THREAD

**Issue by davitol** [owncloud/core#19219]
### Steps to reproduce

1. Create a file, edit and save it
2. Close the file.
3. Edit it and save it again. (A new file version is created)
3. Restore the file

### Expected behaviour
The file has been  restored, so it should change the thumbnail with the actual file

### Actual behaviour
The thumbnail shown is the older one.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** ownCloud Enterprise Edition 8.2 beta1 (daily) Build:2015-09-21T03:08:19+00:00 bbd1e996050fee80795d0e656da98b6451232c6c

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Firefox

**Comment by karlitschek** [comment]
@georgehrke  how should this work?

**Comment by georgehrke** [comment]
Dup of https://github.com/owncloud/core/issues/10559

Please excuse my brevity and typos.
