### ISSUE TITLE
An error is shown clicking two times on the restore button restoring a file

### ISSUE THREAD

**Issue by davitol** [owncloud/core#19218]
### Steps to reproduce

1. Create a file, edit and save it
2. Close the file.
3. Edit it and save it again. (A new file version is created)
3. Restore the file
4. Click on the restore button for a second time

### Expected behaviour
The file has been already restored, so it should not happen anything 

### Actual behaviour
An error is thrown. 

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** ownCloud Enterprise Edition 8.2 beta1 (daily) Build:2015-09-21T03:08:19+00:00 bbd1e996050fee80795d0e656da98b6451232c6c

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Firefox

![restoredfail](https://cloud.githubusercontent.com/assets/10596560/9990066/3e0fc308-605e-11e5-8638-3be3849da067.png)

**Comment by karlitschek** [comment]
@PVince81 what do you think?

**Comment by PVince81** [comment]
In the old dropdown the dropdown would close when clicking "Revert". In the new one we need to add better error handling.

**Comment by cmonteroluque** [comment]
This issue will fall off 8.2 if not resolved by 6 Oct

**Comment by davitol** [comment]
In ownCloud Enterprise Edition 8.2 beta1 (daily) Build:2015-10-05T03:08:46+00:00 2ffb1c2135d80ac82f62c2bd403fe452e2c4e51d the error cannot be reproduce with the steps written above, and the restore works fine. :+1:
