### ISSUE TITLE
forwarded_for_headers in config.php

### ISSUE THREAD

**Issue by luquercy** [owncloud/core#19211]
Hi,

I'm using owncloud 8.1.3 and i have a problem with reverse proxy and OC 8 log.
When i watch my log a have this :

{"reqId":"Vf08dn8AAQZZAFK4ga4AADAA","remoteAddr": 192.168.33.251","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/dirname\/gluster\/user@none.tld\/avatar.jpg","level":0,"time":"2015-09-19T12:44:06+02:00","method":"GET","url":"\/index.php\/avatar\/user@none.tld\\/128?requesttoken=XiS1nGzklvyESb5WNLnEL4pYYDXqYd"}

The client ip address in field "remoteAddr" is my front apache but not real address of users logged.

I try to put in config.php this values 

'trusted_proxies' => array('192.168.33.251'),
'forwarded_for_headers' => array('HTTP_X_FORWARDED', 'HTTP_FORWARDED_FOR'),

But no change in log file and yet my apache logs is okay.

PHP Version : PHP 5.5.9-1ubuntu4.11  
Mysql : 10.0.21-MariaDB-1~trusty-wsrep-log

Someone can help me please ?

**Comment by LukasReschke** [comment]
Please verify that your reverse proxy sets the appropriate headers.

**Comment by luquercy** [comment]
hi,

i show you up my virtual host config

<IfModule mod_ssl.c>
<VirtualHost _default_:443>
ServerAdmin webmaster@localhost

DocumentRoot /var/www/html



ErrorLog ${APACHE_LOG_DIR}/error.log
CustomLog ${APACHE_LOG_DIR}/access.log combined
Header always add Strict-Transport-Security "max-age=15768000"
ProxyPass / http://host.dom.local/
ProxyPassReverse / http://host.dom.local/
#ProxyRequests Off
#ProxyPreserveHost Off
#ProxyVia Off

ErrorLog ${APACHE_LOG_DIR}/app1.error.log
LogLevel warn
CustomLog ${APACHE_LOG_DIR}/app1.access.log combined

RewriteEngine On
RewriteCond %{HTTP_HOST} !^www.domaine.fr$
RewriteRule /.* http://www.domaine.fr/ [R]


SSLEngine on

SSLCertificateFile              /cert/ssl/server.crt
SSLCertificateKeyFile           /cert/ssl/server.key
SSLCertificateChainFile         /cert/ssl/ssl-bundle.crt

<FilesMatch "\.(cgi|shtml|phtml|php)$">
SSLOptions +StdEnvVars
</FilesMatch>
<Directory /usr/lib/cgi-bin>
SSLOptions +StdEnvVars
</Directory>

BrowserMatch "MSIE [2-6]" \
nokeepalive ssl-unclean-shutdown \
downgrade-1.0 force-response-1.0
# MSIE 7 and newer should be able to use keepalive
BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown

</VirtualHost>
</IfModule>

**Comment by luquercy** [comment]
hi 
Do you need some more information ?

Regards

**Comment by blizzz** [comment]
Closing this because of lack of information and likely a configuration issue. This is no place to give support, especially out of ownCloud scope. Feel free to reopen and provide more information if you still think this is a bug.
