### ISSUE TITLE
Encrypt-all command keeps server in single mode user

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#19213]
### Steps to reproduce

Having some regular not admin users with files do:

1. Encrypt all using the occ command encryption:encrypt-all
2. Recover admin files using the given password following occ instructions.
3. Try to access with another user.

### Expected behaviour
You can access with another user.

### Actual behaviour
Server is put on single user mode and it can't be changed. 
Even using maintenance:singleuser --off regular user can't access.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.2.0.6","versionstring":"8.2 beta1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in community edition..

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
Yes

**Logs**
```
```
### Client configuration

**browser**
Chrome 41

**Comment by schiesbn** [comment]
Hm, for some reasons single user mode doesn't get disabled after decrypting all files. Never happened to me so far. Can you try latest master? Maybe this https://github.com/owncloud/core/pull/19148 fixed it for you.

**Comment by SergioBertolinSG** [comment]
Applying that patch I was able to turn off single user mode and continue thanks.

I'll retest later from the beginning with it.

**Comment by SergioBertolinSG** [comment]
Fixed with that patch.
