### ISSUE TITLE
showDropDown broken, should use ShareDialogView

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#19214]
@blizzz can you take care of this ?

It should be a matter of opening the dropdown and embedding the new ShareDialogView into it.
It seems it doesn't work any more.

CC @oparoz

**Comment by PVince81** [comment]
The gallery app needs this

**Comment by karlitschek** [comment]
Yes. This is critical

**Comment by blizzz** [comment]
After investigating, some apps (at least Gallery :D) were using the old share dialog and manipulating it. Best and safest way for 8.2 seems to pack the "old" share dialog code into one file, let it both ship and load by the apps who need it. For 9.0 we look into a way to satisfy the needs of gallery, calendar and such by providing possibilities to interact with the new share dialogue code in a sane way (real API :D).

**Comment by PVince81** [comment]
I'm looking into providing a portable namespaced "share.js" that can be copied into gallery, calendar and contacts and usable directly.

**Comment by PVince81** [comment]
- [ ] calendar: https://github.com/owncloud/calendar/pull/940
- [ ] contacts
- [ ] gallery

**Comment by PVince81** [comment]
I tried putting these additions into the gallery app and it worked.
But the checkboxes are broken (the new styles), so let's wait for @Henni to fix them in https://github.com/owncloud/calendar/pull/940 first.

**Comment by PVince81** [comment]
PRs are available now for calendar, contacts and gallery: https://github.com/owncloud/core/issues/19214#issuecomment-142570399

Please review them!

**Comment by VicDeo** [comment]
Related to  https://github.com/owncloud/documents/issues/550

**Comment by PVince81** [comment]
All known apps have been fixed => closing
