### ISSUE TITLE
Advertise federation capability

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#19228]
For the authenticated case, there is the capabilities API.

But for cases without login, we might want to allow servers to advertise the fact that they support federation.

@rullzer

**Comment by rullzer** [comment]
Yes, probably makes sense so a server can actually check if sending requests makes sense. And if so what kind of requests.

**Comment by PVince81** [comment]
Federation is already advertised through the "ocs-provider" that is accessible publicly, that should already be enough.
