### ISSUE TITLE
Zip file created with multiple file download; not compatible with Mac OS X uncompress

### ISSUE THREAD

**Issue by DIYglenn** [owncloud/core#19226]
Yosemite 10.10.5:
The ZIP file created when downloading multiple files cannot be extracted with the built in function in OS X. "The Unarchiver" software can extract.

The built-in function (double clicking in Finder) just extracts a ".zip.cpgz" file. If this again is extracted, you're left with the original *.zip* again.
![zip bug](https://cloud.githubusercontent.com/assets/10504432/9992675/e7e4e34e-6073-11e5-9115-fcdb03af33f9.png)

**Comment by SergioBertolinSG** [comment]
This is a known bug, you can use the app the unarchiver to uncompress it.

**Comment by RealRancor** [comment]
Ref: https://github.com/owncloud/core/issues/10001

**Comment by compuguy** [comment]
Still an issue with 10.11. See bug #13669
