### ISSUE TITLE
[Share via link] Using Safari, the shared file is not shown in the linked page.

### ISSUE THREAD

**Issue by davitol** [owncloud/core#19227]
### Steps to reproduce

1. Create a file
2. Share it via link
3. Paste the link in Safari 

### Expected behaviour
The file should appear for sharing/downloading

### Actual behaviour
No info about the file is shown

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** ownCloud Enterprise Edition 8.2 beta1 (daily) Build:2015-09-21T03:08:19+00:00 bbd1e996050fee80795d0e656da98b6451232c6c

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Safari

Chrome
![chrome](https://cloud.githubusercontent.com/assets/10596560/9993423/0772c808-6078-11e5-8d09-e0c81d306e75.png)

Safari
![safari](https://cloud.githubusercontent.com/assets/10596560/9993430/1011e25a-6078-11e5-95fe-75fa988133a8.png)

**Comment by PVince81** [comment]
@davitol regression ?

**Comment by davitol** [comment]
@PVince81 Yes, it works fine in Safari with oC 8.1.3

**Comment by PVince81** [comment]
Can you try disabling the text editor app and see if the problem still exists on the daily build ?

**Comment by davitol** [comment]
I've tried with daily build, but WITHOUT disabling the editor app and it works. So I cannot reproduce it now.  I'll close the issue and if it is reproduce again i'll open it
