### ISSUE TITLE
a group admin can create a user with more space than allow to him by by superadmin

### ISSUE THREAD

**Issue by lordkalki** [owncloud/core#19224]
I've create and user who is admin over his own group. As super admin, I've give this user 1GB space. 
When this user login, he can create a new user for his own group and gives him 1GB space. This new user can upload 1GB data but, here is my point.... the first user who is admin has 1GB space..... why is it then possible that he can create a new user with 1GB or maybe more? In my example in total I lost 2 GB space but 1GB was allow....

**Comment by lordkalki** [comment]
you have't disscuss direct make it bug :p very fast

**Comment by PVince81** [comment]
What you're looking for is group quota, this isn't implemented yet. See feature request: https://github.com/owncloud/core/issues/1347
