### ISSUE TITLE
After clicking new + text file, the text editor should open

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19230]
### Description

As a user, I click on the "+" button to create a file I will use immediately.
Opening the text editor right after I've created a text file would save me one click and impress my friends about the usability of ownCloud.

### Acceptance criteria

* User clicks +, file is created, files is opened in text editor (if installed)
* The editor should only automatically open for media types supported by the text editor

@jancborchardt

**Comment by jancborchardt** [comment]
Technically a duplicate of https://github.com/owncloud/core/issues/7031, but this is more specific so let’s continue here instead. :) I totally agree @oparoz!

And for folders:
> For »New folder«, insert the folder directly in the file list and have it in rename mode.

**Comment by jancborchardt** [comment]
Also cc @tomneedham for the text editor.

**Comment by oparoz** [comment]
> For »New folder«, insert the folder directly in the file list and have it in rename mode.

Defo!

**Comment by PVince81** [comment]
This is done in 9.0, closing

**Comment by jancborchardt** [comment]
Opened https://github.com/owncloud/core/issues/21848 for the »New folder« part.

**Comment by oparoz** [comment]
:+1:
