### ISSUE TITLE
moving shared file to / moves file to other home path

### ISSUE THREAD

**Issue by leichtgemerkt** [owncloud/core#19239]
I think there is a bug when I move shared files or folders to my root. I try to explain it:
thats the setting:
![setting](https://cloud.githubusercontent.com/assets/14736216/10013623/4131341c-6113-11e5-8eaa-ee59b9cb7055.PNG)
So in my example User2 is moving test.txt to the root in his view. 
![fileproblem](https://cloud.githubusercontent.com/assets/14736216/10013687/de3dbe10-6113-11e5-8cd6-59fda422ec1b.PNG)
In the backend OC moves it out of the old home into the home of User2. This is a big problem because all other users are loosing this file and all shares on this file are gone! I had this problem on my server and my customers called because they missed files. They didn't expect this behavior too. I don't know how to solve this problem. Maybe the only solution would be to lock any moving of files to the root path if the user is not the owner?

**Comment by PVince81** [comment]
How are you moving it ? Web UI ? Webdav ?
Which OC version ?

Please use the issue template https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by schiesbn** [comment]
That's the expected behavior.  Given that you have delete permissions moving the file out of a shared folder to a local folder means that you delete it from the owner and create a copy in your local folder.

That's the only valid behavior. The behavior you suggest would include a lot of "magic". Including create new shares for the new copies of the owner, etc.

**Comment by leichtgemerkt** [comment]
Im moving the shared file per drag and drop via Web UI to the breadcrumb (Home-Symbol = Root)
My OC-Version is 8.0.0.7.

User1 cant know that user xy moved it out of his share. This is not usable for any of my users, sorry. I think I make a hotfix on my installation. I can't imagine any situation someone want to allow other users to remove his files by moving it around. In general I think that this action makes no sense at all and your "solution" produces questionmarks on all users. So why not locking it? My lokal hotfix will just lock any drag and drop to "/" if its not my home (because i got it per share).

**Comment by PVince81** [comment]
If you want to lock it, remove the "delete" permission on the share.

**Comment by leichtgemerkt** [comment]
yes and if my users forget that i can take a look why his files gone missing? Sorry I don't want to spend my time with this. I make a hotfix myself.

**Comment by schiesbn** [comment]
If users allow recipients to delete shared files they have to expect that they might do it, same for rename, edit, etc.
