### ISSUE TITLE
Locking should be able to handle exceptions

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#19242]
I just debugged a issue where we throw a exception during a copy operations because something went wrong. (https://github.com/owncloud/core/blob/master/lib/private/files/view.php#L788)

In this case we never free the lock and we will run into a lock exception later on, if we catch the error and try to recover.

We should always have a try-catch block between ````$this->lockFile(...);```` and ````$this->unlockFile(....);```` to make sure that we also release the lock correctly if something goes wrong.

cc @PVince81 @icewind1991 @DeepDiver1975

**Comment by PVince81** [comment]
Locking is already able to handle exceptions in many places.

But as there are so many different code paths, there is probably a bunch that aren't covered yet.

**Comment by schiesbn** [comment]
I will prepare a pull request to fix it

**Comment by Xenopathic** [comment]
Can we use RAII for this? So some object, that when constructed gets a lock, and when destructed releases the lock? Then we don't have to manually deal with releasing locks, we just let the locking object go out of scope.

Or is that just my C++ background showing through?

**Comment by individual-it** [comment]
as we are using TTLs in dblocking now, could we just delete all expired locks in https://github.com/owncloud/core/blob/master/lib/private/lock/dblockingprovider.php#L173 and not only the ones with lock == 0?

**Comment by PVince81** [comment]
@individual-it not removing locks could cause issues with subsequent code that might want to lock again (it can happen several times within a single PHP request).

In general I prefer having explicit closing of resources / releasing. Relying on automatic magic can sometimes lead to unpredictable results (happened before with fopen and file handles)

**Comment by PVince81** [comment]
another example was "closeCursor"
