### ISSUE TITLE
Moving files via WebUI sometimes causes integrity constraint violation

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#19241]
In my case I moved the folder `2007` from `Bilder/Fotos` to my home folder (drag and drop on the little house in the breadcrumbs.

```
An exception occurred while executing 'UPDATE `oc_filecache` SET `storage` = ?, `path` = ?, `path_hash` = ?, `name` = ?, `parent` =? WHERE `fileid` = ?' with params ["1", "files\/2007", "6143cb694bdc0c1ce138e6b048690ae9", "2007", "2", 257605]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-6143cb694bdc0c1ce138e6b048690ae9' for key 'fs_storage_path_hash'
```

For other folders this just works fine. But for some folders it causes this error. I could be possible that I had the folder with this name in my root some time back, but now this isn't present anymore. Once the integrity constraint violation gets triggered the folder completely disappeared. I need to do a files:scan on the destination folder to get it back in the web UI/webdav.

In the logs nothing is visible.

@PVince81 @icewind1991 Can I somehow check my filecache for some weird entries?

I'm still on vacation and will have tomorrow a look at the DB.

**Comment by PVince81** [comment]
@MorrisJobke did you have locking enabled ? If not you might still be victim of a variation of this https://github.com/owncloud/core/issues/13391

**Comment by MorrisJobke** [comment]
> @MorrisJobke did you have locking enabled ? If not you might still be victim of a variation of this #13391

Nope, because it's labeled experimental :see_no_evil:

**Comment by PVince81** [comment]
Not anymore, it's not called "transactional" :wink:

**Comment by PVince81** [comment]
@MorrisJobke did you find more info ?

**Comment by MorrisJobke** [comment]
> @MorrisJobke did you find more info ?

I happens from time to time, but not reproducable and also without further info :(

**Comment by PVince81** [comment]
@MorrisJobke can you enable transaction locking then and see if it still happens from times to times or not at all ?

**Comment by MorrisJobke** [comment]
It happened anymore -> closing. I will reopen if it still happens.
