### ISSUE TITLE
Clicking .odp file leads to error page

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#19249]
![capture du 2015-09-22 12-08-03](https://cloud.githubusercontent.com/assets/925062/10015768/a356986c-6122-11e5-97f6-d87075db2a7f.png)

> Can't read file
> Module with id: OC_DEFAULT_MODULE does not exist. Please enable it in your apps settings or contact your administrator.

This should never ever be visible to people. Maybe log it in the console and then download the file.

@PVince81 @schiesbn pretty sure this didn’t happen before.

**Comment by Xenopathic** [comment]
This comes from encryption...

**Comment by individual-it** [comment]
This happened to me on a hosted OC instance.
First we had encryption enabled, uploaded files. Then we disabled the "Default encryption module" and when accessing the old encrypted files this message was shown.
What is it actually the meaning of it? Should the user get a message like: "Your admin totally messed up the encryption, ask him to fix it" and a more technical message in the logs?

**Comment by DeepDiver1975** [comment]
> and then download the file.

this is not possible - the file is encrypted and the necessary code to decrypt it is not loaded.
The admin has to enable the correct app.

To be honest there is not mich we can do - the admin should setup the system properly.

@jancborchardt I vote for case closed as won't fix

**Comment by jancborchardt** [comment]
Ok, probably leftover issue from broken config.
