### ISSUE TITLE
Weird behaviour of the sidebar when clicking away

### ISSUE THREAD

**Issue by davitol** [owncloud/core#19246]
### Steps to reproduce

1. Create a file
2. Click on share button (Sidebar appears)
3. Click away in the bottom of the files view

### Expected behaviour
The sidebar should 'dissapear', or at least show the info of the last file selected

### Actual behaviour
The sidebar shows the info about the activity of the last selected file, but nothing in the sharing tab

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** ownCloud Enterprise Edition 8.2 beta1 (daily) Build:2015-09-21T03:08:19+00:00 bbd1e996050fee80795d0e656da98b6451232c6c

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Firefox

![sidebarempty](https://cloud.githubusercontent.com/assets/10596560/10014723/8cb3bba0-611b-11e5-912a-d90e1960a98e.png)

**Comment by schiesbn** [comment]
We already have a issue where we discussed it and some possible solutions: https://github.com/owncloud/core/issues/19120
