### ISSUE TITLE
The file name is stuck to the favorites icon

### ISSUE THREAD

**Issue by davitol** [owncloud/core#19243]
### Steps to reproduce

1. Create a file
2. Click on share button (Sidebar appears)

### Expected behaviour
The file name should have a distance from the favorites icon

### Actual behaviour
The file name is stuck to the favorites icon

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** ownCloud Enterprise Edition 8.2 beta1 (daily) Build:2015-09-21T03:08:19+00:00 bbd1e996050fee80795d0e656da98b6451232c6c

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
IE9&11

![iestart](https://cloud.githubusercontent.com/assets/10596560/10014365/153da4e8-6119-11e5-812a-69c05a730eb8.png)

**Comment by karlitschek** [comment]
@jancborchardt small layout fix for you :-)

**Comment by jancborchardt** [comment]
Fix to review at https://github.com/owncloud/core/pull/19257
