### ISSUE TITLE
Unable to build DEB from source, missing files

### ISSUE THREAD

**Issue by pludi** [owncloud/core#19245]
I'm attempting to build the ownCloud DEB package from the sources provided in the [OpenSUSE repositories](http://download.opensuse.org/repositories/isv:/ownCloud:/community/Debian_8.0/) in order to help with #19124 and #19209.

However, building fails with the message
```
sed < /usr/src/packages/SOURCES/apache_secure_data -e"s|@@OC_DIR@@|/var/www/owncloud|g" > owncloud.conf
/bin/bash: /usr/src/packages/SOURCES/apache_secure_data: No such file or directory
debian/rules:36: recipe for target 'override_dh_install' failed
make[1]: *** [override_dh_install] Error 1
```
Apparently there are hard dependencies to the RPM sources. Also missing is the configuration file for nginx.

**Comment by LukasReschke** [comment]
@jnweiger THX

**Comment by pludi** [comment]
Addendum: checked the current SRPM for F20, the nginx configuration file is apparently missing there too.

**Comment by PVince81** [comment]
Is this still an issue @owncloud/packaging @pludi ?

**Comment by pludi** [comment]
Closing issue. Lost track of it long ago.
