### ISSUE TITLE
Sharing via link with an address with 'email@example' structure should show an error

### ISSUE THREAD

**Issue by davitol** [owncloud/core#19256]
### Steps to reproduce

1. Create a file
2. Click on share button (Sidebar appears)
3. Share a file by link
4. Email link to a person with the following structure email@example

### Expected behaviour
An error message should be shown, as it is shown with other wrong email addresses.

### Actual behaviour
The mail seems to be sent.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** ownCloud Enterprise Edition 8.2 beta1 (daily) Build:2015-09-21T03:08:19+00:00 bbd1e996050fee80795d0e656da98b6451232c6c

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Firefox

![mailerr](https://cloud.githubusercontent.com/assets/10596560/10017561/d03d8220-612f-11e5-8902-4501cec49c48.png)

**Comment by davitol** [comment]
Also it is not detected e-mail invalid addresses as:
email@-example.com;
email@example.web;
email@111.222.333.44444;

**Comment by PVince81** [comment]
Hmmm I know we have email validation code, maybe it's tolerant @DeepDiver1975 ?

Also I think that "someone@hostname" is a correct email address, I sometimes have "localhost" as hostname when testing.

**Comment by nickvergessen** [comment]
As per http://www.faqs.org/rfcs/rfc2822.html they are perfectly valid.
And that is what the validation of Swiftmail (our 3rdparty lib for emails) validates against.
