### ISSUE TITLE
Broken/Bad link

### ISSUE THREAD

**Issue by sk8dancer** [owncloud/core#19258]
There is a bad link, "Release Channel", on https://owncloud.org/news/ in the section titled "Updates and Scalability Pain" located in the paragraph just above the image. The link points to "localhost:5000/release-channels"

Also there is something strange going on when I scroll to the bottom of the page. After a few seconds my browser (firefox) scrolls back to where I started the scroll from.

**Comment by PVince81** [comment]
Please report here https://github.com/owncloud/owncloud.org
