### ISSUE TITLE
Oc 8.1 Openstack Swift Primary Storage does not work

### ISSUE THREAD

**Issue by Berndinox** [owncloud/core#19255]
#### Steps to reproduce:
1 Install a fresh OC 8.1.3 on Nginx+HHVM+MariaDB Stack
2 Enable external Storage Addon
3 Connect Runabove OpenStack Swift Storage via Admin GUI: OK
4 Connect the same Bucket as primary Storage in config.php: NOK

#### Expected behaivour:
Default Storage should be Openstack Swift Backend

#### Actual behaivour:
The following Error occours, when connecting Swift Backend via config.php:
```
Exception: {"Exception":"OCP\\Files\\NotFoundException","Message":"","Code":0,"Trace":"#0 \/var\/www\/cloud.xxx.at\/apps\/files\/index.php(84): OC_Helper::getStorageInfo()\n#1 (1): include()\n#2 (): \u0000lambda_1()\n#3 \/var\/www\/cloud.xxx.at\/lib\/private\/route\/router.php(274): call_user_func()\n#4 \/var\/www\/cloud.xxx.at\/lib\/base.php(874): OC\\Route\\Router->match()\n#5 \/var\/www\/cloud.xxx.at\/index.php(40): OC::handleRequest()\n#6 {main}","File":"\/var\/www\/cloud.xxx.at\/lib\/private\/helper.php","Line":971}
```
```
Exception: {"Message":"Call to a member function getPath() on a non-object (boolean)","Code":0,"Trace":"#0 \/var\/www\/cloud.xxx.at\/apps\/files\/appinfo\/remote.php(63): OC\\Connector\\Sabre\\Node->__construct()\n#1 (): Closure$()\n#2 \/var\/www\/cloud.xxx.at\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array()\n#3 \/var\/www\/cloud.xxx.at\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(456): Sabre\\Event\\EventEmitter->emit()\n#4 \/var\/www\/cloud.xxx.at\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod()\n#5 \/var\/www\/cloud.xxx.at\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n#6 \/var\/www\/cloud.xxx.at\/remote.php(132): include()\n#7 {main}","File":"\/var\/www\/cloud.xxx.at\/lib\/private\/connector\/sabre\/node.php","Line":75}
```
> HHVM or Nginx does not show any errors.

**config.php:**
```
'objectstore' => array(
    'class' => 'OC\\Files\\ObjectStore\\Swift',
    'arguments' => array(
        'username' => 'user',
        'password' => 'pass',
        'container' => 'storage',
        'autocreate' => true,
        'region' => 'SBG-1',
        'url' => 'https://auth.Runabove.io/v2.0',
        'tenantName' => 'id',
        'serviceName' => 'swift',
    ),
),
```

**Env-Details:**

- Ubuntu 14.04
- Nginx 1.8
- HHVM 3.6
- redis 2.8
- mariadb 10.1.7

Enabled:
 - activity: 2.0.2
 - files: 1.1.10
 - files_external: 0.2.3
 - files_locking:
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.6

Disabled:
 - encryption
 - external
 - user_external
 - user_ldap
 - user_webdavauth

#### UPDATE:
**OC 8.0.8 on the same Server: It does work!**
But: On OC 8.0.8 remove does not work, the files are still on the swift backend

Hmm, after an Upgrade from 8.0.8 to 8.1.3 it does work, however i still can not remove files. Of course its working in owncloud, but the files still persist on the swift storage backend.

Something is not running very smooth with openstack storage...

BR Bernd

**Comment by karlitschek** [comment]
@butonic can you have a look please?

**Comment by butonic** [comment]
I guess the same underlying reason as https://github.com/owncloud/core/issues/19125. Will investigate tomorrow.

**Comment by Berndinox** [comment]
Hy, yes, sorry for duplicating, looks like it's another problem...

During the night there also occours this log entry:
```
Exception: {"Exception":"ErrorException","Message":"ps_files_cleanup_dir: opendir(\/var\/lib\/hhvm\/sessions) failed: Permission denied (13)","Code":0,"Trace":"#0 (): OC\\Session\\Internal->trapError()\n#1 \/var\/www\/cloud.berndklaus.at\/lib\/private\/session\/internal.php(38): session_start()\n#2 \/var\/www\/cloud.berndklaus.at\/lib\/base.php(454): OC\\Session\\Internal->__construct()\n#3 \/var\/www\/cloud.berndklaus.at\/lib\/base.php(594): OC::initSession()\n#4 \/var\/www\/cloud.berndklaus.at\/lib\/base.php(1122): OC::init()\n#5 \/var\/www\/cloud.berndklaus.at\/index.php(38): include()\n#6 {main}","File":"\/var\/www\/cloud.berndklaus.at\/lib\/private\/session\/internal.php","Line":104}
```
Seems like a bit an hhvm related problem?!
I will try switching to php-fpm and see how it's going.

Thanks in advanced for investigating, BR bernd

**Comment by Berndinox** [comment]
Hy, Problem still exists.

Adding the storage as primary via config.php -> Files got NOT removed from Openstack Backend
Adding the Storage via Web-GUI -> Everything fine, Files got removed on Swift Backend

:(

Any help would be very nice.. BR Bernd

**Comment by butonic** [comment]
Hey, I am working on this in https://github.com/owncloud/core/pull/19414. Delete and move should work but still tests failing...

Regarding swift as primary storage vs files external swift. The former stores only the binary data for a file id, hence the `urn:oid:45`. The latter treats swift as a pseudo filesystem. So what you are seeing is expected behavior.

**Comment by Berndinox** [comment]
Hy butonic,
Thanks for the Update.

BR Bernd

**Comment by butonic** [comment]
@Berndinox the testsuite is in place and https://github.com/owncloud/core/pull/17641 should fix the move / rename problems.

**Comment by Berndinox** [comment]
@butonic I guess #17641 is included into 8.1.3?

Move/rename seems to be fixed but not re-move (delete).
The files are still on the openstack backend after removing in owncloud.

-> Wenn ich die Dateien entfern im Owncloud GUI, liegen die Dateien immer noch im Openstack Container, sie werden dort niemals entfernt.

BR Bernd

**Comment by Berndinox** [comment]
To bad, it seems like webdav is broken after changing the code:
```
Exception: {"Message":"HTTP\/1.1 409 Parent node does not exist","Code":0,"Trace":"#0 \/var\/www\/cloud.berndklaus.at\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(583): Sabre\\DAV\\Server->createCollection('Dateien\/!Berufs...', Array, Array)\n#1 [internal function]: Sabre\\DAV\\CorePlugin->httpMkcol(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#2 \/var\/www\/cloud.berndklaus.at\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#3 \/var\/www\/cloud.berndklaus.at\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:MKCOL', Array)\n#4 \/var\/www\/cloud.berndklaus.at\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \/var\/www\/cloud.berndklaus.at\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n#6 \/var\/www\/cloud.berndklaus.at\/remote.php(132): require_once('\/var\/www\/cloud....')\n#7 {main}","File":"\/var\/www\/cloud.berndklaus.at\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","Line":1138}
```

**Comment by hyperbaba** [comment]
Is there any progress related to this swift bug?

**Comment by DeepDiver1975** [comment]
8.2.1 will contain a lot of fixes in the area of swift primary storages

**Comment by MorrisJobke** [comment]
@Berndinox @hyperbaba Many fixes went into 8.2.1 (next maintenance release) and 9.0.0 (next major release) - #17641 & #19882 

Please create a new ticket if there are still problems left. Thanks :)

**Comment by hyperbaba** [comment]
where can i find build 8.2.1-current. I can't build it by myself

**Comment by MorrisJobke** [comment]
> where can i find build 8.2.1-current. I can't build it by myself

As this was just merged 2 hours ago you need to wait for this nights builds. They can be downloaded tomorrow at following location: https://download.owncloud.org/community/daily/owncloud-daily-stable8.2.tar.bz2

Keep in mind that these are builds for testing purposes ;)

**Comment by Berndinox** [comment]
Thanks for fixing this, can't wait for 8.2.1 :)
Br

**Comment by hyperbaba** [comment]
Just tested with last night's build and the result is the same. The file is not deleted from swift container and it's deleted in the owncloud. The test is performed on a clean install.

**Comment by MorrisJobke** [comment]
> Just tested with last night's build and the result is the same. The file is not deleted from swift container and it's deleted in the owncloud. The test is performed on a clean install.

Also the same error messages?

**Comment by hyperbaba** [comment]
no error messages at all

**Comment by hyperbaba** [comment]
upon uploading a single file 3 objects are created in the container. Upon deletion two are deleted and the file itself stays (urn:oid blob)

**Comment by Berndinox** [comment]
My Steps were: 

Fixed it manualy on 8.2.0 -> Does work!
Update  half an hour ago to the daily -> Does work!

BR Bernd

**Comment by Berndinox** [comment]
@hyperbaba stupid question: did you empty the recycle bin?

**Comment by MorrisJobke** [comment]
I just talked to @hyperbaba and it would be best to open a new issue, because it seems something different.

**Comment by MorrisJobke** [comment]
New ticket is in https://github.com/owncloud/core/issues/19971
