### ISSUE TITLE
Focus on share field after opening share tab

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#19252]
### Steps

1. Create folder
1. Click "Share" icon

### Expected result
Focus on share field.

### Actual result
No focus.

### Versions
master

Would improve UX.

CC @jancborchardt

**Comment by jancborchardt** [comment]
Right, good point. It’s really annoying to need to manually click the share input again.

**Comment by cmonteroluque** [comment]
This issue will fall off 8.2 if not resolved by 6 Oct

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/19536
