### ISSUE TITLE
Sharing a parent folder prevents shares

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#19251]
## Steps to reproduce
1. Create folder1
2. Create sub1 and sub2 inside folder1
3. Share sub2 with link
4. Share folder1 with link

## Expected
1. sub1 can be shared with link
2. sub2 can be unshared

## Actual
The rightside bar sharing tab does not allow sharing interaction, although the current user owns the files
![folder_-_dateien_-_owncloud_-_2015-09-22_12 39 51](https://cloud.githubusercontent.com/assets/213943/10016408/094c144a-6127-11e5-9670-841ab6f01a42.png)

This worked before and was fixed in 8.0 or 8.1, now it's broken again :(

@PVince81 @blizzz

**Comment by PVince81** [comment]
Hmm, I followed the steps and am getting a different behavior: after sharing with link, in order "sub2" then "folder1" then "sub1", I get this JS error:
```
Uncaught TypeError: OC.Share.itemShares[share.share_type].push is not a function(anonymous function) 
@ shareitemmodel.js?v=04291a3e1348d53254439946c940081a:645
_.each._.forEach@underscore.js?v=04291a3e1348d53254439946c940081a:153
OC.Backbone.Model.extend._legacyFillCurrentShares@shareitemmodel.js?v=04291a3e1348d53254439946c940081a:633
OC.Backbone.Model.extend.parse@shareitemmodel.js?v=04291a3e1348d53254439946c940081a:675
(anonymous function)@shareitemmodel.js?v=04291a3e1348d53254439946c940081a:606
$.ajax.success@share.js?v=04291a3e1348d53254439946c940081a:318
x.Callbacks.c@jquery.min.js?v=04291a3e1348d53254439946c940081a:4
x.Callbacks.p.fireWith@jquery.min.js?v=04291a3e1348d53254439946c940081a:4
k@jquery.min.js?v=04291a3e1348d53254439946c940081a:6
x.ajaxTransport.send.r@ jquery.min.js?v=04291a3e1348d53254439946c940081a:6
```

**Comment by nickvergessen** [comment]
I made a full page refresh between the shares, maybe that helps.
But never the less it does not work as intended.

**Comment by PVince81** [comment]
Aha, the call to `_legacyFillCurrentShares` fails silently and the model population stops... Looking into it.

**Comment by PVince81** [comment]
Okay... share type is sometimes a string and "3" !== OC.Share.SHARE_TYPE_LINK, classic Javascript...

**Comment by PVince81** [comment]
Even more WTF, the server sometimes returns share type as string, sometimes as int...
![server-share-response-string](https://cloud.githubusercontent.com/assets/277525/10042101/8934d7b0-61e9-11e5-831a-9d06f6a46217.png)

I'll add some code on the JS side for now to make sure it's parsed to int.

**Comment by PVince81** [comment]
Now I wonder if the old JS code was using `==` sometimes :see_no_evil: 

Fix is here: https://github.com/owncloud/core/pull/19295

**Comment by PVince81** [comment]
Fixed through https://github.com/owncloud/core/pull/19295
