### ISSUE TITLE
Code files are not detected as text files with code icon.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#19254]
### Steps to reproduce

As admin user do:
1. Upload code files.
2. See their icons.

### Expected behaviour
They have a code icon. Like .pl files in this screenshot:

![screen shot 2015-09-21 at 13 08 26](https://cloud.githubusercontent.com/assets/9048796/10017325/ac897d40-612d-11e5-82a4-b92a83bda274.png)

### Actual behaviour
They are not detected as code.

.cpp, .xml and .tex are detected as plain text not code.

![screen shot 2015-09-22 at 08 56 11](https://cloud.githubusercontent.com/assets/9048796/10012388/deb0595e-6107-11e5-8d06-2b0a661a1a43.png)

.abap .ads .agi .algol .e .apl .scpt .arc. ArnoldC .as .au3 .awk .bas .bat .befunge .bg .boo .bf .ceylon .clj .cbl .coffee .cfml .lisp .context **.cs** .csh .d **.dart** .pas .djs .ecl .e .ex .lisp .erl .fal .f .fy .fan .fimpp .fs **.go** .golo .gsx .groovy .hs .hs .ho .hq9plus .idr .io **.java** .jl .kt .ls .lgt .lol .lua .m4 .mathematica .m .mod .nasm .n .ml .omgrofl .pn .ps1 .pde .pure .r .rkt .rexx .rb .sml .sbl **.sql** .stata .swift **.tcl** .uc .vala .v .vim .vb .asm .xpath2 .xquery .xslt .xtend .zu

All this file types are code and are showed as undetected type, like .rtf which is not detected as a document.
I think bolded ones needs to be fixed specially since those filetypes are very used.

![screen shot 2015-09-22 at 08 55 51](https://cloud.githubusercontent.com/assets/9048796/10012392/e942fcaa-6107-11e5-9780-9b88efc9424a.png)

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.2.0.6","versionstring":"8.2 beta1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in community edition..

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Chrome. Firefox.

cc @jancborchardt

**Comment by SergioBertolinSG** [comment]
@cmonteroluque not sure if this should be addressed to 8.2. or 9.0 What do you think?

**Comment by jancborchardt** [comment]
@SergioBertolinSG this is not a design issue but needs to be added to the filetype tables.

cc @Xenopathic @schiesbn can you provide a pull request for this? Priority is xml, cpp, java, sql (code) and rtf (text).

**Comment by PVince81** [comment]
could be a regression, @rullzer ?

**Comment by Xenopathic** [comment]
@PVince81 No, we don't have the appropriate mappings and aliases. I'm working on it :smile:

**Comment by rullzer** [comment]
thanks @Xenopathic :smile:

**Comment by Xenopathic** [comment]
Hmm, despite adding `text/x-c` as an alias for `text/code`, the icon shown is still the generic text icon... Same for XML. Any ideas @rullzer ?

**Comment by cmonteroluque** [comment]
thanks @Xenopathic

**Comment by cmonteroluque** [comment]
the types in bold have to be addressed at least
