### ISSUE TITLE
What happened to the file sidebar whitespace in previews

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#19250]
It’s totally off (too much) for any image:
![capture du 2015-09-22 12-07-42](https://cloud.githubusercontent.com/assets/925062/10015870/3f8a95d0-6123-11e5-8946-87eade1ea8d5.png)
@icewind1991 @Blizzz @PVince81 @georgehrke

**Comment by PVince81** [comment]
Ewww... bisect ?

**Comment by PVince81** [comment]
Going to bisect this

**Comment by PVince81** [comment]
Regression introduced by this PR https://github.com/owncloud/core/pull/18911

@icewind1991 please have a look

**Comment by oparoz** [comment]
This only happens with newly uploaded pictures.
Where is the code which builds the preview? It's setting the wrong height for some reason.

**Comment by icewind1991** [comment]
The problem is that `isCached` also returns a cached preview if a larger preview is available which the sidebar doesn't handle correctly

**Comment by oparoz** [comment]
> The problem is that isCached also returns a cached preview if a larger preview is available which the sidebar doesn't handle correctly

Argh, the problem is that it might not be just the sidebar which is affected... Otherwise I'd rather fix the side-bar than getting rid of your fix.

**Comment by schiesbn** [comment]
is this still an issue? I saw this a few days ago but on latest master it seems to be fixes... At least I can't reproduce it any longer.

**Comment by schiesbn** [comment]
OK, seems the PR which caused the issue was reverted https://github.com/owncloud/core/pull/19268
