### ISSUE TITLE
Shared with you and other sections empty sidebar

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#19264]
Sidebar interaction is broken with the sections "Shared with you" and other sharing related sections in the files app.

The sidebar is needed to make it possible to update shares for the selected item.

CC @jancborchardt

**Comment by jancborchardt** [comment]
Yup.

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/19270 (simpler than I thought)
