### ISSUE TITLE
SMB / CIFS with OC login not possible

### ISSUE THREAD

**Issue by JavaGuy85** [owncloud/core#19269]
Steps to reproduce:

1. Install owncloud-8.1.3 by downloading and unpacking the owncloud-8.1.3.tar.gz
2. 
  2.1 Configure LDAP as the user backend (probably not part of the issue, but for sake of completeness, this step is included.
  2.2 Configure SMB / CIFS with OC login as external storage (within administration panel all looks good, green light)
  2.3 Log in as a user from the LDAP-backend

Expected behaivour:
User should be able to see his home folder as external storage in owncloud

Actual behaivour:
Display resets to the standard owncloud/data folder when trying to access external storage. No error message is displayed within the application. Error message from the owncloud.log is below.

Server configuration:
Ubuntu 14.04 64-bit Server edition in a VM. All software is the newest version available from repository:
Apache2, 
MySQL, 
PHP
owncloud 8.1.3 fresh install

activated apps:
 - activity: 2.0.2
 - files: 1.1.10
 - files_external: 0.2.3
 - files_locking:
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.6
 - user_ldap: 0.6.1

config/config.php:
                                                                                                                                         
<?php
$CONFIG = array (
  'instanceid' => 'oc01m1cxjryj',
  'passwordsalt' => 'mysalt',
  'secret' => 'mysecret',
  'trusted_domains' =>
  array (
    0 => '172.16.199.139:8080',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://172.16.199.139:8080/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.1.3.0',
  'dbname' => 'dbase',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'dbuser',
  'dbpassword' => 'mypasswd',
  'logtimezone' => 'UTC',
  'installed' => true,
);

External storage: "SMB / CIFS with OC-login"
Encryption: no
External user-backend: ldap

LDAP Configuration
+-------------------------------+---------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                             |                                                    
+-------------------------------+---------------------------------------------------------------------------------------------
| hasMemberOfFilterSupport      |                                                                                             
| hasPagedResultSupport         |                                                                                             
| homeFolderNamingRule          |                                                                                             
| lastJpegPhotoLookup           | 0                                                                                           
| ldapAgentName                 | cn=admin,dc=myserver,dc=de                                                                  
| ldapAgentPassword             | ***                                                                                         
| ldapAttributesForGroupSearch  |                                                                                             
| ldapAttributesForUserSearch   |                                                                                             
| ldapBackupHost                |                                                                                                 
| ldapBackupPort                |                                                                                             
| ldapBase                      | dc=myserver,dc=de                                                                           
| ldapBaseGroups                | dc=myserver,dc=de                                                                           
| ldapBaseUsers                 | dc=myserver,dc=de                                                                          
| ldapCacheTTL                  | 600                                                                                         
| ldapConfigurationActive       | 1                                                                                           
| ldapEmailAttribute            |                                                                                             
| ldapExperiencedAdmin          | 1                                                                                           
| ldapExpertUUIDGroupAttr       |                                                                                             
| ldapExpertUUIDUserAttr        |                                                                                             
| ldapExpertUsernameAttr        |                                                                                             
| ldapGroupDisplayName          | cn                                                                                         
| ldapGroupFilter               | (|(cn=Lehrer)(cn=Schueler)(cn=admins))                                                      |                                                    
| ldapGroupFilterGroups         | Lehrer;Schueler;admins                                                                      
| ldapGroupFilterMode           | 0                                                                                           
| ldapGroupFilterObjectclass    |                                                                                             
| ldapGroupMemberAssocAttr      | memberUid                                                                                   
| ldapHost                      | localhost                                                                                   
| ldapIgnoreNamingRules         |                                                                                             
| ldapLoginFilter               | (&(|(objectclass=myPerson))(|(uid=%uid)(|(sambaSID=%uid)(uid=%uid)(userPassword=%uid))))    |                                                    
| ldapLoginFilterAttributes     |sambaSID;uid;userPassword 
| ldapLoginFilterEmail          | 0                                                                                           
| ldapLoginFilterMode           | 0                                                                                           
| ldapLoginFilterUsername       | 1                                                                                           
| ldapNestedGroups              | 0                                                                                           
| ldapNoCase                    | 0                                                                                           
| ldapOverrideMainServer        |                                                                                             
| ldapPagingSize                | 500                                                                                         
| ldapPort                      | 389                                                                                         
| ldapQuotaAttribute            |                                                                                             
| ldapQuotaDefault              |                                                                                             
| ldapTLS                       | 0                                                                                           
| ldapUserDisplayName           | cn                                                                                          
| ldapUserFilter                | (|(objectclass=myPerson))                                                                   
| ldapUserFilterGroups          |                                                                                             
| ldapUserFilterMode            | 0                                                                                           
| ldapUserFilterObjectclass     | myPerson                                                                                 
| ldapUuidGroupAttribute        | auto                                                                                        
| ldapUuidUserAttribute         | auto                                                                                        
| turnOffCertCheck              | 0                                                                                           
| useMemberOfToDetectMembership | 1                                                                                           
+-------------------------------+---------------------------------------------------------------------------------------------+                                                    

Client configuration:
Browser: Firefox: 40.0.3
Ubuntu 14.04 32-bit

Apache2 error.log:
[Tue Sep 22 15:02:21.559705 2015] [mpm_prefork:notice] [pid 29922] AH00163: Apache/2.4.7 (Ubuntu) mod_jk/1.2.37 PHP/5.5.9-1ubuntu4.11 mod_perl/2.0.8 Perl/v5.18.2 configured -- r\
esuming normal operations

Owncloud.log:
{"reqId":"Fw8cJNQckelYtjCBoQh1","remoteAddr":"192.168.200.16","app":"core","message":"Exception while scanning storage \"smb::myuser@localhost\/\/\/\/\": Icewind\\SMB\\Exception\
\\Exception: Unknown error (22) for smb:\/\/localhost\/\/","level":3,"time":"2015-09-22T13:02:31+00:00"}

Firebug Konsole log:
Content Security Policy: "The settings on this website prevented loading a Ressource on self ("script-src http://172.16.199.139:8080 'unsafe-eval'").

Firebug Network log:
no errors logged. 106 GET Request successfully finished within 4,41s.

**Comment by Xenopathic** [comment]
@icewind1991 Another "Unknown error"... it'd be great if your library actually included the erroring line with the exception message

**Comment by JavaGuy85** [comment]
@icewind1991 do you need any further information to debug this? If I can help fixing this somehow, please contact me.

**Comment by icewind1991** [comment]
> `smb::myuser@localhost\/\/\/\/\`

Looks like the share is not set for some reason

**Comment by JavaGuy85** [comment]
When I set share, I get following error, but not always:
{"reqId":"Tauj9wed+GJOOE1wek2d","remoteAddr":"192.168.200.16","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/ldap.p\
hp#257","level":3,"time":"2015-09-22T13:50:27+00:00"}

There is no external storage in any case, with share or without...

**Comment by icewind1991** [comment]
That looks like an unrelated ldap error

**Comment by JavaGuy85** [comment]
so if I don't use the ldap backend, the smb / cifs with oc login should work? I'll test that, thanks. It might be due to special structure of the ldap I am using.

**Comment by Xenopathic** [comment]
@JavaGuy85 No, the LDAP error is actually completely normal, cc @blizzz. It does not correlate to your external storage issue at all.

Does your storage work with the standard SMB/CIFS backend? Obviously with a set of credentials that works.

**Comment by JavaGuy85** [comment]
I tried the normal SMB/CIFS backend. Prior to that, I created a local user on the samba server machine and created a samba user with "sudo smbpasswd -a username". I disabled the LDAP backend in owncloud and added the user to owncloud, username and password match.

Now, in the administration part of owncloud, the SMB/CIFS backend shows a red square. 

owncloud.log has this to say about it:
Message\":\"Invalid request for smb:\\\/\\\/192.168.200.16:***\\\/home\\\/\",\"Code\":2,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewin\
d\\\/smb\\\/src\\\/NativeState.php(72): Icewind\\\\SMB\\\\NativeState->handleError('smb:\\\/\\\/192.168.2...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdpa\
rty\\\/icewind\\\/smb\\\/src\\\/NativeState.php(180): Icewind\\\\SMB\\\\NativeState->testResult(false, 'smb:\\\/\\\/192.168.2...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/fil\
es_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/NativeShare.php(105): Icewind\\\\SMB\\\\NativeState->stat('smb:\\\/\\\/192.168.2...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\
\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/NativeShare.php(100): Icewind\\\\SMB\\\\NativeShare->getStat('\\\/')\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_\
external\\\/lib\\\/smb.php(102): Icewind\\\\SMB\\\\NativeShare->stat('\\\/')\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/smb.php(136): OC\\\\Files\\\\Sto\
rage\\\\SMB->getFileInfo('')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/common.php(408): OC\\\\Files\\\\Storage\\\\SMB->stat('')\\n#7 \\\/var\\\/ww\
w\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(499): OC\\\\Files\\\\Storage\\\\Common->test(false)\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/con\
troller\\\/storagescontroller.php(132): OC_Mount_Config::getBackendStatus('\\\\OC\\\\Files\\\\Stora...', Array, false)\\n#9 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\
\\/controller\\\/globalstoragescontroller.php(157): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus(Object(OCA\\\\Files_external\\\\Lib\\\\Storage\
Config))\\n#10 [internal function]: OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController->update(2, 'SMB', '\\\\OC\\\\Files\\\\Stora...', Array, NULL, Array, Array, 1\
00)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\
\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStorag\
esController), 'update')\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Fil\
es_External\\\\Controller\\\\GlobalStoragesController), 'update')\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\
\\\\AppFramework\\\\App::main('GlobalStoragesC...', 'update', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#15 [internal function]: OC\\\\AppFramew\
ork\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#16 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(274): call_user_func(Object(OC\\\\AppFramework\\\\
\routing\\\\RouteActionHandler), Array)\\n#17 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(874): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#18 \\\/var\\\/www\\\
\/owncloud\\\/index.php(40): OC::handleRequest()\\n#19 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/NativeSta\
te.php\",\"Line\":44}","level":4,"time":"2015-09-22T15:05:19+00:00"}

**Comment by Xenopathic** [comment]
Can you connect directly to the share with other tools, such as a file manager (any that support GVFS can do it) or smbclient?

**Comment by JavaGuy85** [comment]
yes, with nautilus it works

**Comment by Xenopathic** [comment]
Have you tried putting a domain in front of the username? You should be able to find it in smb.conf on the Samba server, put `domain\username` as the username.

**Comment by JavaGuy85** [comment]
OK, the error with normal SMB/CIFS was a misconfiguration of my samba server, which I set up just for testing the normal SMB/CIFS. Now it works. However, the samba server I used for trying out the SMB/CIFS with OC login was not this test-server, and it is configured correctly.

So to sum it up, SMB/CIFS works. SMB/CIFS with OC login does not work. I am using the same samba test-server and same user for both, no ldap backend. It seems there is no error logged. Only error I see in the owncloud.log is:
{"reqId":"4u7osP3voqNYS5\/a\/bTC","remoteAddr":"192.168.200.16","app":"PHP","message":"Array to string conversion at \/var\/www\/owncloud\/lib\/private\/template\/functions.php#\
36","level":3,"time":"2015-09-22T17:11:26+00:00"}

**Comment by Xenopathic** [comment]
So the same credentials that you use to log into ownCloud with work in an SMB/CIFS mount, correct?

**Comment by JavaGuy85** [comment]
exactly, the same user is on the samba server machine, and has the same password for samba access. SMB/CIFS works, SMB/CIFS with OC login does not...

**Comment by Xenopathic** [comment]
Try putting in some debug statements (something like `\OCP\Util::writeLog('', $user, \OCP\Util::WARNING);`) right here: https://github.com/owncloud/core/blob/stable8.1/apps/files_external/lib/smb_oc.php#L65. Find out what the 'user' and 'password' variables are set to, make sure they match what you expect.

**Comment by JavaGuy85** [comment]
I get "undefinded class constant 'WARNING'"

**Comment by JavaGuy85** [comment]
it's 'WARN', not 'WARNING'. Pass and Username, as well as host are what I expect...

**Comment by Xenopathic** [comment]
Then there is no difference between your manually mounted SMB/CIFS and the SMB with OC login...

**Comment by JavaGuy85** [comment]
OK, so SMB/CIFS with OC login now works with the test-server, if I disable "username as share" option.

With the actual server, the share folder is /home/[uid] - uid is an Attribute from LDAP. Is that the problem?

**Comment by Xenopathic** [comment]
Using 'Username as share' clearly won't work in that case, since your share name is 'home/user' not 'user'. You can however manually specify a share, using the `$user` variable, which gets replaced with the user UID. So you can try with a share of `home/$user`.

**Comment by JavaGuy85** [comment]
this replaced the username with a long string that looks like an md5-hash or something. It is not the uid attribute from ldap.

**Comment by Xenopathic** [comment]
That is because your LDAP configuration is set to use a UUID attribute - if you go to the Users page you will see each user is represented by this string of characters. If you want to change it (WARNING: will reset all shares and/or data!) you have to change the UUID attribute in the Expert LDAP settings (to 'uid' if what you are telling me is correct), then clear the user mappings. However, this has now become an LDAP problem cc @blizzz

**Comment by JavaGuy85** [comment]
OK, now I get the actual path of the share folder in the log message, with the correct uid instead of the username or the UUID. However, it still says:

{"reqId":"vt+ZaxOfrpQGHlzFBg5W","remoteAddr":"192.168.200.16","app":"core","message":"Exception while scanning storage \"smb::myuser@localhost\/\/home\/4848\/\/\": Icew\
ind\\SMB\\Exception\\ForbiddenException: Invalid request for smb:\/\/localhost\/home\//4848\/","level":3,"time":"2015-09-22T20:26:47+00:00"}

4848 is the uid of "myuser". Is this some rights issue?

**Comment by ypid** [comment]
Hi

I am facing the same problem. It worked with oc [8.0.6](http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/openSUSE_13.1/) and fails with [8.1.1](http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.1/openSUSE_13.1/) and [8.1.3](https://owncloud.org/install/).

Manually mounting the CIFS share via `mount -t cifs` works as expected  (`domain\` something is not required). I am also using the LDAP external user app.

SMB / CIFS: Does not work. When I enter the working test credentials and host and share it remains red and logs:

Exception: {"Exception":"Icewind\\SMB\\Exception\\ForbiddenException","Message":"Invalid request for smb:\/\/cl01.domain.com\/sharepath\/"


SMB / CIFS mit OC-Login: Similar issue except that the "unknown error" is now shown to the user.

**Comment by icewind1991** [comment]
Did you specify the domain while testing?

**Comment by ypid** [comment]
No, a domain is not required. I can confirm that `mount -t cifs '//cl01.domain.com/sharepath' /mnt -o username=user --verbose` with logs `unc=\\cl01.domain.com/sharepath,user=user` works.

**Comment by ypid** [comment]
I can confirm that it works with ownCloud `8.0.2` and `8.0.8`. I downgraded the instance by restoring a backup. Feel free to ask for configuration details as needed. The system was setup from a appliance (default hostname `eval-appliance-oc8ee-vmdk-2015-8-5`) from owncloud.com (I guess, some one else set that up but I am managing it now :wink:) which I updated via Suses build service to 8.1.1 using `zypper`.

Details:

```
## /etc/os-release
NAME=openSUSE
VERSION="13.1 (Bottle)"
VERSION_ID="13.1"
PRETTY_NAME="openSUSE 13.1 (Bottle) (x86_64)"
ID=opensuse
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:opensuse:13.1"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://opensuse.org/"
ID_LIKE="suse"
```

```
## ./occ app:list 
Enabled:
 - activity
 - files
 - files_external
 - files_locking
 - files_pdfviewer
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - files_videoviewer
 - firstrunwizard
 - gallery
 - provisioning_api
 - templateeditor
 - user_ldap
Disabled:
 - external
 - files_encryption
 - user_external
 - user_webdavauth
```

**Comment by JavaGuy85** [comment]
This is no bug. Problem was, samba uses a different password for authentication, different from the user password. When samba password is reset through smbpasswd owncloud connects correctly to the external storage.
