### ISSUE TITLE
Searching for another user in the share dialog is limited to users in the same group

### ISSUE THREAD

**Issue by gig13** [owncloud/core#19263]
### Steps to reproduce
1. See description below

### Expected behaviour
When using the share dialog, all users should be found

### Actual behaviour
When searching for another user in the share dialog is limited to users in the same groups, one user can't find another if they only have one particular group in common. This group is the group that all our ownCloud users are a member of so it's very large as opposed to all our other groups which are quite small. If two users have any other group at all in common then they can find each other.

### Server configuration
**Operating system**: CentOS 6

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.5

**ownCloud version:** 7.0.8

**Updated from an older ownCloud or fresh install:** Updated

**List of activated apps:**

**Are you using external storage, if yes which one:** NO

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** AD

Here’s the longer version along with configuration details:

This issue affects special department accounts and it has only been reported in the last few weeks after our upgrade to 7.0.8. A normal user will be a member of a group called owncloudusers and that group will get them into the application. They will also be a member of several other groups that managed programmatically by other systems, one of which is called owncloudunrestrictedgal. This group holds all users who have no security restrictions on them. We have a manual version of that group called owncloudunrestrictedgalmanual. We restrict users to share within their group, however everyone is a member of the owncloudusers group. More on this in a moment.

We have some code that runs in /core/ajax/share.php when a search is sent. It checks for membership of these groups. If a user is not a member it removes groups from the $usergroups array except for their main department group. This is intended to allow them to search for those in their department but to not be able to see anyone else even though all users are in the same group as them, owncloudusers. We also remove certain groups such as owncloudusers from the search results so people can’t share a folder with the whole organization.

This code has worked perfectly for several months now and it’s still working fine for regular users, just not for users who aren’t in the owncloudunrestrictedgal group. I made a test user with the same group membership as the department account which includes owncloudusers and owncloudunrestrictedgalmanual and I added a couple of smaller groups as well. I was able to search for a user that was in the smaller group and users in the owncloudunrestrictedgalmanual group (it is small too), but not users that were in owncloudusers only.

I’ve added log output to spit out the values of the various arrays in share.php at various points as a search is processed. $usergroups shows the correct groups. I’ve done the same in OC_Group::DisplayNamesInGroups and verified that everything appears as it should be but no users are found when the only group in common is the owncloudusers group. Now if I turn limiting sharing by group membership off I can search for anyone from these accounts without a problem.

Two things have happened shortly before this issue started being reported, we upgraded to 7.0.8 from 7.0.6 and we have started our general roll out to all staff. So the owncloudusers group has grown from about 600 users to a little over 3000 now. The number of elements in the json array for owncloudusers in the ldap_group_members table is showing as 906 currently.

So to sum up, if two users only have this owncloudusers group in common, they can’t find each other. However if they have any other group in common then they can. The next biggest group is about 600-700 hundred. We haven’t had any problem reports form users in those groups. It’s only these department accounts that will be in the situation of having no other group in common. Searching for group names works fine also. This is just about searching for individual users where the only common group is owncloudusers.

I’ve tried removing all our code and just running stock and it makes no difference. And our code only removes items from the arrays that share.php makes anyway. There must be something about this group that is causing searches to fail. It would appear to me that it’s related to the size of the owncloudusers group or a change between 7.0.6 or 7.0.8 (I can’t find anything) or something is cached badly and hasn’t updated with the significant growth to this group over the last several weeks.

You’ll see a group in the group filter close to the end called OC Test Group. I added some test users that were in owncloudunrestrictedgalmanual to that test group. I can search for these users just fine. I can search for the other accounts in the manual group. But I can’t see any user where the only group in common is the owncloudusers group.

One more thing, we have the same setup on our dev server but the only difference is that the access group is called OwnCloudDevUsers. So everywhere owncloudusers appears in production, ownclouddevusers appears on the dev server. If I log in as the same test user to dev I can search for everyone who is a member of ownclouddevusers. This is the only difference in the ldap config between the two servers. And of course, this group is quite small. So I’m learning more towards there being a problem with the size of the owncloudusers group and the fact that it’s the only group in common when one user can’t search for another.

Hopefully this gives the ldap brains enough to try and replicate the problem we’re seeing and locate the solution. Is it save for use to delete the LDAP-Proxy-* files in the php temp location on the web servers and/or the row in ldap_group_members for this owncloudusers group? Will they re-create themselves automatically or will things break horribly?

I’ve also gone looking for any kind of php errors either in the owncloud.log or in the apache logs and found none. 

@LukasReschke @blizzz @bboule

**Comment by gig13** [comment]
More info at 
https://s3.owncloud.com/owncloud/index.php/apps/files?dir=%2FShared%2Fowncloud%2Fsupport%2Fgithub-issues%2Fcore%2F19263

**Comment by PVince81** [comment]
On the admin page there's an option "Restrict users to only share with users in their groups", is this set ?

If yes, it somehow remind me of this ticket: https://github.com/owncloud/core/issues/16346

**Comment by gig13** [comment]
@PVince81 
Not set in the admin page. More info has been updated on s3.

**Comment by PVince81** [comment]
Ok, so basically using a patched ajax/share.php

**Comment by gig13** [comment]
@PVince81 
Even after reverting the changes (mostly for debug) they are seeing the issue.

**Comment by PVince81** [comment]
Ok I see. Hmm... So it appears that "owncloudusers" is a magical (or cursed) group where users can't see each other in the autocomplete but it works for any other groups.

This could sound like a LDAP sync issue, especially that he said the group size didn't match what was on the LDAP server.

@blizzz can you check their LDAP config and answer the question.

> Is it save for use to delete the LDAP-Proxy-* files in the php temp location on the web servers and/or the row in ldap_group_members for this owncloudusers group? Will they re-create themselves automatically or will things break horribly?

**Comment by PVince81** [comment]
@gig13 I'd still expect old users (users created way before the group size of "owncloudusers" increased) to still be able to see each other, as those should still be present in ownCloud's database.
Only newly added users would suffer from it, if it was the size issue.

**Comment by blizzz** [comment]
So, update from 7.0.6.

> something is cached badly and hasn’t updated with the significant growth to this group over the last several weeks.

They can turn off caching in LDAP to verify this theory. They just need to set the Cache TTL to 0 in Advanced LDAP settings. However there were no (group-) related changes in the LDAP backend between 7.0.6 and 7.0.8, but I also fail to see related changes in sharing. If something is bogus, it's likely there for a longer time. Any chance they might have overseen this before?

> And of course, this group is quite small. So I’m learning more towards there being a problem with the size of the owncloudusers group and the fact that it’s the only group in common when one user can’t search for another.

The size of the group is reported as >= 3000k, to get all its users requires paged results to overcome the (default) limit of 1k entries per query. Because of the group restriction, we need to read all users in that group. When I try with a test script (https://gist.github.com/blizzz/736339dc4938a920e087), I get all members of a test group with more than 1.1k users. Maybe they can try that as well?

> can you check their LDAP config

appears to be fine

> Is it save for use to delete the LDAP-Proxy-* files in the php temp location on the web servers and/or

Yes. It won't help them though.

> the row in ldap_group_members for this owncloudusers group? Will they re-create themselves automatically or will things break horribly?

Hooks for users who left the group will not be thrown. Since (file) sharing does not rely on it anymore, it's probably safe though. It will not help them either.

**Comment by bboule** [comment]
@gig13 is this still an issue or can it be closed?

**Comment by gig13** [comment]
Can be closed.
