### ISSUE TITLE
Trashbin sidebar broken/empty

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#19261]
Trashbin sidebar should only contain file info, but no tabs.

Activity might work if the fileid matches.

Currently it is empty, which is wrong.

CC @jancborchardt

**Comment by jancborchardt** [comment]
cc what for? If it’s to agree, then yes, I agree. ;)

**Comment by jancborchardt** [comment]
I guess cc @schiesbn makes more sense here.

**Comment by PVince81** [comment]
For your information in case you find that issue too, so you don't need to re-raise.
Also to make sure you agree with the intended behavior.

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/19270 (simpler than I thought)
