### ISSUE TITLE
select user in share drop down with strange content

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#19260]
select user in the new share drop down shows strange content in some situations

Steps to reproduce:

1. login as 
2. create a user called "user1"
3. go to the share dialog
4. enter "use" -> the auto complete list will show you user1
5. press twice the "arrow down" key

The input field will show now ````[Object object] ````

cc @blizzz @PVince81

**Comment by PVince81** [comment]
Didn't happen in stable8.1 => regression.

It looks like there is an extra bogus item in the selection list.

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/19279
