### ISSUE TITLE
autocomplete list doesn't update correctly

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#19265]
auto-complete list doesn't update correctly with the new share dialog

Steps to reproduce:

1. share a file with "user1" (user get's auto-completed correctly)
2. delete the share
3. try to share again with "user1"

Expected behavior:

Auto-complete will find user1 again

Actual behavior:

auto-complete doesn't find "user1" only after you reload the webpage you can auto-complete "user1" again

cc @blizzz @PVince81

**Comment by PVince81** [comment]
@schiesbn does this PR https://github.com/owncloud/core/pull/19220 fix it ?

**Comment by schiesbn** [comment]
yes, the pr above fixes it.
