### ISSUE TITLE
Public sharing does not work for logged-in users when files_texteditor is installed

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19273]
### Env

Firefox
PHP 5.5
Encryption on

### Steps to reproduce

1. Share folder
2. Open new tab
3. Paste and go

### Actual result

I get an empty files list

Now if I open a new private window, I get the list.

### Logs

```
"message":"ob_end_clean(): failed to delete buffer. No buffer to delete at \/lib\/private\/files\/view.php#368","level":0,"time":"2015-09-22T13:58:01+00:00","method":"GET","url":"\/index.php\/apps\/files_sharing\/ajax\/publicpreview.php?file=%2F800px-Parliament_Building_Budapest_Hungary.jpg&c=ca0305ba538fbc9e048aca962bd71003&t=HHOW8VNfmVHrPqy&y=36&x=36"
```

**Comment by oparoz** [comment]
@LukasReschke @schiesbn

**Comment by PVince81** [comment]
Also happens without encryption

**Comment by PVince81** [comment]
I'll bisect this...

**Comment by PVince81** [comment]
and here we go, caused by https://github.com/owncloud/core/pull/18913

@LukasReschke please have a look

**Comment by LukasReschke** [comment]
Will do.

**Comment by LukasReschke** [comment]
Nope. Not me.

```
➜  master git:(master) ✗ ./occ app:disable files_texteditor
files_texteditor disabled
```
![2015-09-22_18-04-30](https://cloud.githubusercontent.com/assets/878997/10023857/6c6505fa-6154-11e5-8ef1-08ff6a2e578b.png)

```
➜  master git:(master) ✗ ./occ app:enable files_texteditor
files_texteditor enabled
```
![2015-09-22_18-04-13](https://cloud.githubusercontent.com/assets/878997/10023849/634e6308-6154-11e5-9cb6-277ee145d141.png)

**Comment by LukasReschke** [comment]
@tomneedham THX

**Comment by LukasReschke** [comment]
Also the AJAX responses do contain all data. It's a JS side problem I'd say.

**Comment by tomneedham** [comment]
@LukasReschke am in Uganda for another 7 days, won't be able to look at this till then.

**Comment by PVince81** [comment]
I'm on Earth this week, let me have a look

**Comment by DeepDiver1975** [comment]
> I'm on Earth this week,

welcome back :rocket:

**Comment by PVince81** [comment]
So if it's the files_texteditor it explains why this issue wasn't found before. It's only since the new version.

Strangely if I empty editor.js the problem still appears.
Looks like we're in weirdland.

**Comment by PVince81** [comment]
It's the CSS...

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/files_texteditor/pull/112 (one liner)
