### ISSUE TITLE
[Sidebar] Setting a file as favorite reloads the thumbnail of the file

### ISSUE THREAD

**Issue by davitol** [owncloud/core#19274]
### Steps to reproduce
1. Create a file
2. Click on share button (Sidebar appears)
3. Click on favorite button.
### Expected behaviour

The file name should be marked as favorite
### Actual behaviour

The file is marked as favorite, but the thumbnail is reloaded, when it should not be done
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** ownCloud Enterprise Edition 8.2 beta1 (daily) Build:2015-09-21T03:08:19+00:00 bbd1e996050fee80795d0e656da98b6451232c6c

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```
```
### Client configuration

**browser**
Firefox

**Comment by rullzer** [comment]
probably because we rerender the sidebar.
@PVince81

**Comment by PVince81** [comment]
We don't rerender the whole sidebar but only its sections.
The MainFileInfoView should be extended to cache the last thumbnail file name. Then if the model changes but the file name/etag didn't, then skip the lazy-loading logic and set the cached thumbnail name to the image.

**Comment by georgehrke** [comment]
@davitol Do you mean the thumbnail in the file list or in the right sidebar?

**Comment by davitol** [comment]
@georgehrke I think it was related to the sidebar thumbnail. The current behaviour is the that the thumbnail in the file list is refreshed each time a file is set as favorite

**Comment by PVince81** [comment]
@cmonteroluque Low severity, I suggest moving to 9.0 or backlog

**Comment by PVince81** [comment]
moved to more general UX group ticket: https://github.com/owncloud/core/issues/27578
