### ISSUE TITLE
[Sidebar] Email link to person; wrong 'placeholder' when emailing a link to a wrong address

### ISSUE THREAD

**Issue by davitol** [owncloud/core#19276]
### Steps to reproduce

1. Create a file
2. Click on share button (Sidebar appears)
3. Email link to person with a invalid email

### Expected behaviour
The 'placeholder' shown should be related about email not sent

### Actual behaviour
The 'placeholder' shown says the mail was sent

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** ownCloud Enterprise Edition 8.2 beta1 (daily) Build:2015-09-21T03:08:19+00:00 bbd1e996050fee80795d0e656da98b6451232c6c

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Firefox

![placeholdmail](https://cloud.githubusercontent.com/assets/10596560/10021142/c791cfa2-6146-11e5-9c53-0f270820b77f.png)

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/19631
