### ISSUE TITLE
Accessibility of 'favorite button', alternative text is not provided for the image that is the only thing within a link.

### ISSUE THREAD

**Issue by davitol** [owncloud/core#19286]
### Steps to reproduce

1. Login ownCloud.
2. Click on share button (Sidebar is shown)

### Expected behaviour
An alternative text should be provided for 'favorite button' due to it is a image that is the only thing within a link.

### Actual behaviour

An alternative text is not provided for 'favorite' image.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
master 
{"installed":true,"maintenance":false,"version":"8.2.0.4","versionstring":"8.2 pre alpha","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
 Firefox.

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/19633
