### ISSUE TITLE
Options icons are not shown properly using IE11

### ISSUE THREAD

**Issue by davitol** [owncloud/core#19290]
### Steps to reproduce

1. Login ownCloud using IE as browser
2. Click on file/folder options button  (menu is dropdrown)

### Expected behaviour
The icons of each option should be shown properly

### Actual behaviour
The icons of each option are not shown properly

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
master 
{"installed":true,"maintenance":false,"version":"8.2.0.4","versionstring":"8.2 pre alpha","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
 IE9 & 11

Internet Explorer:
![screen shot 2015-09-23 at 10 51 47](https://cloud.githubusercontent.com/assets/10596560/10041159/6dcc0f54-61e2-11e5-9c52-edc20eb5a3df.png)

Firefox
![screen shot 2015-09-23 at 10 52 45](https://cloud.githubusercontent.com/assets/10596560/10041162/72d9f6e6-61e2-11e5-9180-33a6a9542583.png)

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/19630

**Comment by davitol** [comment]
> Fix is here #19630

:+1: WFM, awesome
