### ISSUE TITLE
Preview in sidebare hides close button

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#19291]
The preview in the sidebar hides the (X) at the top right to close the sidebar which makes it impossible to close the sidebar.

![1](https://cloud.githubusercontent.com/assets/1589737/10041344/eff5904e-61e3-11e5-8ecf-edfae34f2187.png)

cc @jancborchardt @PVince81

**Comment by schiesbn** [comment]
Probably we should have some padding at every side if the image to see the (X) at the top and also to have some kind of a "frame" around the image. For some images it looks like they run out of the window with no margins.

**Comment by schiesbn** [comment]
I just played around with th window size. At some positions we see the whole (X) sometimes only parts of it, etc. Also it seems that sometimes we show the complete image resized to fit into the sidebar and sometimes we cut it off. Can we just predefine a area for the image and always resize it to fit into the area.

**Comment by jancborchardt** [comment]
This is because the x is dark. It’s not hidden by the preview, it’s just because of the color. Will submit a PR to add a slight border around the x.
