### ISSUE TITLE
[Activities] Weird behaviour clicking on the filename in the activities tab in the sidebar 

### ISSUE THREAD

**Issue by davitol** [owncloud/core#19300]
### Steps to reproduce
1. Perform some actions related to a file 
2. Go to sidebar --> Activities 
3. Click on the file's name

### Expected behaviour
The behaviour should probably the same as clicking on the thumbnail of the preview

### Actual behaviour
If the name is related to a folder, the action is browse into the folder, but if it is a file, it is shown the files view

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** ownCloud Enterprise Edition 8.2 beta1 (daily) Build:2015-09-21T03:08:19+00:00 bbd1e996050fee80795d0e656da98b6451232c6c

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Firefox

**Comment by PVince81** [comment]
@nickvergessen FYI

@davitol the activity view inside the sidebar is also part of the activity app (plugin), so in the future please raise such bugs in https://github.com/owncloud/activity/

**Comment by davitol** [comment]
@PVince81 Thanks for the info

**Comment by nickvergessen** [comment]
The file names have mostly been removed, so I guess we can close this?

**Comment by nickvergessen** [comment]
> so in the future please raise such bugs in https://github.com/owncloud/activity/

Or set the `feature:activity` label, which I also keep track of
