### ISSUE TITLE
Add fallback for checkboxes to avoid breaking third party apps

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#19304]
The new checkbox style provides CSS rules require that all checkboxes come with a "label" element.
If no label was provided, the checkbox will not be visible at all and functionality will be lost.

It has been already observed in core and some apps that checkboxes were broken and could be fixed manually by inserting a label. However, it is not guaranteed that all third party apps will have a label, so there is a risk of breaking third party apps (and potentially other apps under owncloud/apps).

See https://github.com/owncloud/core/pull/18735/files#r40192896

I suggest to add an additional CSS class for the checkbox class to make the new style optional/transitional. Once all/most third party apps have been migrated to work with the new style, that CSS class can be removed.

@Henni I know that you provided another fallback already, but it cannot work for dynamically created checkboxes, so won't cover all cases.

@Henni @jancborchardt @karlitschek @DeepDiver1975

**Comment by jancborchardt** [comment]
I would say we should document it at https://doc.owncloud.org/server/8.2/developer_manual/app/css.html

And then let the devs know. Because having a label next to a checkbox is needed anyway for good & accessible HTML.

**Comment by Henni** [comment]
The point is that the w3c standard allows the following three cases:
``` html
1. <input ... /><label></label>
2. <label></label><input ... />
3. <label><input ... /></label>
```
But only the first case displays the new checkbox style.
2. and 3. simply don't show a checkbox at all.

@jancborchardt do you think that we should add a `.checkbox` class and only apply the new style to checkboxes with this class?

**Comment by PVince81** [comment]
Also, see other potential locations that will have to be fixed eventually: https://github.com/owncloud/apps/search?utf8=%E2%9C%93&q=checkbox
https://github.com/owncloud/calendar/search?utf8=%E2%9C%93&q=checkbox (checkboxes in event dialog in calendar)

and possibly many more :wink:

**Comment by jancborchardt** [comment]
@Henni I’d say at least the 3rd case should also display the new checkbox, as that is quite common – like `<label><input type="checkbox"> Label text</label>`. 2 should be discouraged.

We could add a `.checkbox` class as well but I would only do that if we do not find any other options. We can identify checkboxes by `input type="checkbox"` already, no?

**Comment by PVince81** [comment]
@jancborchardt the ".checkbox" class would be for the fallback, see https://github.com/owncloud/core/issues/19304#issue-107909380

**Comment by jancborchardt** [comment]
@PVince81 as far as I understand, the `.checkbox` class will be added to the checkboxes we know, right? And everything without that class would use the normal checkbox style?

I mean, whatever you think is right and will work. @PVince81 @Henni you need to decide together.

**Comment by PVince81** [comment]
@jancborchardt yes, that's correct.

**Comment by Henni** [comment]
Ok let's add the `.checkbox` class then.
@jancborchardt Case 2 and 3 cannot be styled with pure CSS, as there is no parent or previous sibling selector.

**Comment by jancborchardt** [comment]
@Henni right

**Comment by PVince81** [comment]
So the cool thing here is that the "checkbox" class should make all 3 cases stylable and at the same time provide the fallback :smile:

**Comment by Henni** [comment]
@PVince81 how would you do this?
It would be possible to do this by applying a class to the label, but this would be (in my opinion) semantically incorrect and wouldn't allow us to remove this class in the future.

**Comment by PVince81** [comment]
How about we just stick with the cases 1) and 2) and have the "checkbox" class on the input element ?
In most cases developers will have to touch their code anyway so they could adjust it to match either 1) or 2) in case they had 3), to make it work.

**Comment by PVince81** [comment]
Right, you were talking about case 2). How about another additional class "checkboxlabel" then ?
It looks like to support 2) we won't be able to remove the classes in the future. It's not a bad thing though.

**Comment by Henni** [comment]
Either a `.checkboxlabel` class or a `.checkbox--right` class (which I prefer).
``` html
<input type="checkbox" class="checkbox checkbox--right">
<label>Label Text</label>
```
This would render the checkbox to the right of the "Label Text".

**Comment by PVince81** [comment]
Fine by me.

**Comment by Henni** [comment]
My solution with `.checkbox--right` only works if it's ok that checkboxes are on the wrong side in IE8.

**Comment by PVince81** [comment]
To be honest I don't care. The most important is to not break third party apps when introducing the new style.

**Comment by Henni** [comment]
(y)

**Comment by oparoz** [comment]
Could app devs have some documentation please?

**Comment by Henni** [comment]
@oparoz Feel free to create an issue in the documentation repo and assign me if you want :)
