### ISSUE TITLE
Do not simulate DB upgrade if no actual schema/table changes

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#19316]
### Steps to reproduce
1. Setup ownCloud
2. Increase version in versions.php
3. Run upgrade
### Expected result

No simulated update
### Actual result

Simulated update (observed with debugger, tables are actually copied!)
### Versions

ownCloud 8.2 beta and previous.

Before calling `copyTable`, a diff of the schema should be computed first to make sure there is anything to test.

This should accelerate updates significantly when there is a lot of data and update simulation is not disabled.

@karlitschek @icewind1991 @DeepDiver1975 @cmonteroluque

**Comment by PVince81** [comment]
From looking at the code the fix should be simple (as opposed to trivial).

8.2 or 9.0 ?

**Comment by PVince81** [comment]
Note: https://github.com/owncloud/core/issues/19317 will have to be fixed first because it wrongly detects index changes

**Comment by karlitschek** [comment]
Nice :+1: Please backport to 8.1

**Comment by PVince81** [comment]
@icewind1991 do you have time to fix this ?

**Comment by icewind1991** [comment]
#19344

**Comment by PVince81** [comment]
Obsolete, we killed upgrade simulation
