### ISSUE TITLE
Password Reset Not Working

### ISSUE THREAD

**Issue by iakko** [owncloud/core#19315]
### Steps to reproduce
1. Use a valid user
2. Login with wrong password
3. Click on the link sent by email
4. Change Password

### Expected behaviour
User expects to be redirected to the login/logged page with the new password.

### Actual behaviour
Nothing happens, the browser doesn't move.

### Server configuration
Ubuntu Server Ver. 14.04

Apache 2 Ver. 2.4.7

MySQL Ver. 5.6.21

PHP Ver. 5.5.9

OwnCloud Ver. 8.1.3 (same bug on Ver. 8.1.2)

Updated from 8.1.2

*Applications*
```
Enabled:
 - activity: 2.0.2
 - files: 1.1.10
 - files_external: 0.2.3
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.6
Disabled:
 - encryption
 - external
 - files_versions
 - user_external
 - user_ldap
 - user_webdavauth
```

**The content of config/config.php:**

```
$CONFIG = array (
  'instanceid' => '<INSTANCEID>',
  'passwordsalt' => 'XXX',
  'secret' => 'XXX,
  'trusted_domains' => 
  array (
    0 => '<DOMAIN0>,
    1 => '<DOMAIN1>',
  ),
  'datadirectory' => '/mnt/owncloud/data',
  'overwrite.cli.url' => 'http://<DOMAIN0>',
  'dbtype' => 'mysql',
  'version' => '8.1.3.0',
  'dbname' => '<DBNAME>',
  'dbhost' => '<DBURL>',
  'dbtableprefix' => 'oc_',
  'dbuser' => '<DBUSER>',
  'dbpassword' => '<DBPASS>',
  'installed' => true,
  'forcessl' => true,
  'forceSSLforSubdomains' => false,
  'maintenance' => false,
  'theme' => '<MYTHEME>',
  'loglevel' => 3,
  'themename' => '<MYTHEMENAME>',
);
```

No external storage

No encryption

No external user-backend

No LDAP

### Client configuration
Chrome/Firefox

Linux/iOs/Window

### Logs

N/A

#### Browser log

Chrome Console:

Mixed Content: The page at 'https://<DOMAIN>/index.php/lostpassword/reset/form/bR3eFNfwnJNCWzzy0DR0r/<USER>' was loaded over a secure connection, but contains a form which targets an insecure endpoint 'http://<DOMAIN>/index.php/lostpassword/set/bR3eFNfwnJNCWzzy0DR0r/<USER>'. This endpoint should be made available over a secure connection.
jquery.min.js:6 Refused to connect to 'http://<DOMAIN>/index.php/lostpassword/set/bR3eFNfwnJNCWzzy0DR0r/<USER>' because it violates the following Content Security Policy directive: "connect-src 'self'".
send @ jquery.min.js:6
jquery.min.js:6 POST https://<DOMAIN>/index.php/heartbeat 503 (Service Temporarily Unavailable)send @ jquery.min.js:6x.extend.ajax @ jquery.min.js:6x.(anonymous function) @ jquery.min.js:6(anonymous function) @ js.js:1051

**Comment by iakko** [comment]
Just a little note on the Browser Log section: the "http:///" lacks of domain because I omitted it, actually it's something like "http://my.domain.com/".

**Comment by LukasReschke** [comment]
Your HTTPS setup looks invalid. Please don't mix HTTP with HTTPS.

**Comment by LukasReschke** [comment]
Please reopen at https://forum.owncloud.org/

**Comment by iakko** [comment]
Well, what you mean with "invalid"? Where is the configuration issue? Your response is far from being a technical response :)

**Comment by LukasReschke** [comment]
> Edit: if you refere to the overwrite.cli.url value, it's a mistake I did obfuscating the real URL, I missed the "s", actually it's an https URL.

Then we have the problem already here. Sorry but with all the amounts of reports we get I can't spend more a lot of time on an issue that is lacking a proper config listed. Please use plain URLs and just replace your URL.

> Mixed Content: The page at 'https:///index.php/lostpassword/reset/form/bR3eFNfwnJNCWzzy0DR0r/' was loaded over a secure connection, but contains a form which targets an insecure endpoint 'http:///index.php/lostpassword/set/bR3eFNfwnJNCWzzy0DR0r/'. This endpoint should be made available over a secure connection.

Does indicate that you accessed the domain at an HTTPS domain but the server believes it is accessed via HTTP. I suspect you are using a reverse proxy, which was also not mentioned within your report. If so please check https://github.com/owncloud/core/blob/c269f658eb2ab8a69287a36b3bb923ae071a40d0/config/config.sample.php#L353-L360

**Comment by LukasReschke** [comment]
And also https://doc.owncloud.org/server/8.1/admin_manual/configuration_server/reverse_proxy_configuration.html

**Comment by iakko** [comment]
Thanks for the link, I'll invastigate about that.

I didn't mentioned "reverse proxy" because there is no reverse proxy in front of OwnCloud :)

Actually, it's a Virtual Host, here the Apache2 configuration:

Note: everything between *[SOMETHING]* is a placeholder.

```
<VirtualHost [INTERNAL_IP]:443>
	ServerName [DOMAIN]
	ServerAlias [ATLERNATE_DOMAIN]
	ServerAdmin [MY_EMAIL]

	DocumentRoot /var/www/[OWNCLOUD_PATH]

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

	<FilesMatch "\.(cgi|shtml|phtml|php)$">
			SSLOptions +StdEnvVars
	</FilesMatch>

	<Directory /usr/lib/cgi-bin>
			SSLOptions +StdEnvVars
	</Directory>

	<Directory /var/www/[OWNCLOUD_PATH] >
		Options -Indexes +FollowSymLinks +MultiViews
		AllowOverride All
		Allow from all
		Require all granted
		#Dav Off
		Satisfy Any
	</Directory>

	BrowserMatch "MSIE [2-6]" \
			nokeepalive ssl-unclean-shutdown \
			downgrade-1.0 force-response-1.0
	BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown

</VirtualHost>
```

Once you request a password reset, the email contains an HTTP link to the OwnCloud instance, not an HTTPS.

So, seems like it's not able to guess that the connection is SSL.
