### ISSUE TITLE
Schema diff detects index change during update simulation even if there is none

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#19317]
### Steps to reproduce

1. Setup ownCloud
1. Increase version in versions.php
1. Run upgrade

### Expected result
No schema change applied

### Actual result
In a debugger, I see that the diff contains changes and the produced SQL would drop indices and then recreate them.
@karlitschek this seems to match a query log you showed me last week.

### Versions
ownCloud 8.2 beta and possibly previous versions.

@karlitschek @icewind1991 @DeepDiver1975 @cmonteroluque please evaluate severity

**Comment by PVince81** [comment]
This was with:
mariadb-10.0.20-1.1.x86_64

Could be related to recent changes to index name format/handling

**Comment by PVince81** [comment]
Okay, I debugged further and this only happens during update simulation.

During the real actual DB update, the diff is correct and no indices are recreated.

**Comment by PVince81** [comment]
Ok, I'll evaluate severity myself: high because it slows down update simulation

**Comment by PVince81** [comment]
It's a regression. It worked in 8.1.0 (an earlier commit of the migrator file)

Going to bisect.

**Comment by PVince81** [comment]
Argh, I mis-debugged. Also found happening in 8.0.5.
Travelling further back...

**Comment by PVince81** [comment]
And here we go, it was the Doctrine/dbal update 46c2909c785267fc1c71cf2aa635d467ab2cded5 from https://github.com/owncloud/core/pull/11689

This was added in OC 8.0, so since OC 8.0 this needless index deletion is happening.

**Comment by PVince81** [comment]
Hmm, I tried to write a unit test to reproduce the issue, but in the unit test the diff is correct and doesn't contain bogus index changes.

**Comment by PVince81** [comment]
The schemas, this is during a real run:
```
      $sourceSchema->_tables['owncloud.oc_appconfig']->_indexes = (array[3]);
        $sourceSchema->_tables['owncloud.oc_appconfig']->_indexes['primary'] = (object|Doctrine\DBAL\Schema\Index[8])+;
        $sourceSchema->_tables['owncloud.oc_appconfig']->_indexes['appconfig_config_key_index'] = (object|Doctrine\DBAL\Schema\Index[8])+;
```
```
      $targetSchema->_tables['owncloud.oc_oc_appconfig_csg2sn4y769vr']->_indexes = (array[3]);
        $targetSchema->_tables['owncloud.oc_oc_appconfig_csg2sn4y769vr']->_indexes['appconfig_appid_key_index'] = (object|Doctrine\DBAL\Schema\Index[8])+;
        $targetSchema->_tables['owncloud.oc_oc_appconfig_csg2sn4y769vr']->_indexes['oc_kdjkozajmzwth'] = (object|Doctrine\DBAL\Schema\Index[8])+;
```

And here during a unit test run:
```
      $sourceSchema->_tables['oc_autotest.oc_oc_test_vxgiwexbfjvjl_tjdsaiptaoa67']->_indexes = (array[2]);
        $sourceSchema->_tables['oc_autotest.oc_oc_test_vxgiwexbfjvjl_tjdsaiptaoa67']->_indexes['primary'] = (object|Doctrine\DBAL\Schema\Index[8])+;
        $sourceSchema->_tables['oc_autotest.oc_oc_test_vxgiwexbfjvjl_tjdsaiptaoa67']->_indexes['oc_test_vxgiwexbfjvjl_name'] = (object|Doctrine\DBAL\Schema\Index[8])+;

```
```
      $targetSchema->_tables['oc_autotest.oc_oc_test_vxgiwexbfjvjl_tjdsaiptaoa67']->_indexes = (array[2]);
        $targetSchema->_tables['oc_autotest.oc_oc_test_vxgiwexbfjvjl_tjdsaiptaoa67']->_indexes['primary'] = (object|Doctrine\DBAL\Schema\Index[8])+;
        $targetSchema->_tables['oc_autotest.oc_oc_test_vxgiwexbfjvjl_tjdsaiptaoa67']->_indexes['oc_loirtaunipruu'] = (object|Doctrine\DBAL\Schema\Index[8])+;
```

So there is indeed something fishy with the appended random suffix

**Comment by PVince81** [comment]
Okay, my test had a bug.

Basically the Doctrine comparator detects that the indices have been renamed, which is obviously visible in the schema. But now the question is why it didn't do so in the previous version... and also how can we detect duplicate indices, knowing that we have to duplicate them for the test tables.

**Comment by PVince81** [comment]
Here it comes: before the Doctrine update, the Comparator from Doctrine was doing the a diff of the indices by checking their definition, not their names. So if there was another index with a different name but with the same spec, it would not consider it as a change.

In the new Doctrine (2.5) it only compares the index names. This breaks our detection during a simulation because the name is generated with a suffix.

So next step is to find a way to adjust our simulated indices to match this new behavior.

**Comment by PVince81** [comment]
Right, I retried with a debugger and the index changes appear under `renamedIndexes`.

I'll see if we can try and use the same index names without the generated suffix...

**Comment by PVince81** [comment]
Now why did we need a suffix in the first place ? I little time travel adventure brought me back to 0035147be96537193f0c7119dfd0628fe7363a26 from https://github.com/owncloud/core/pull/7015 (https://github.com/owncloud/core/commit/0035147be96537193f0c7119dfd0628fe7363a26#diff-6244155d6a93589cf488706b3dc2f7f9R94) where @icewind1991 added the suffix. Over time, the format of the suffix got changed several times.

In a regular non-simulating situation there is only `$startSchema`, which is the current existing schema and `$targetSchema`, the schema that only exists in PHP and to which the change will happen.
However when doing a simulation, we're basically duplicating the whole table, so we have to duplicate the indices too.

Hmmm... maybe the update simulation should also rename the indices in `$startSchema` and add the same suffix as we have in `$endSchema`, to make sure that the index names stay the same during simulation.

**Comment by PVince81** [comment]
So basically keep the index names the same until the time we do the diff. Whenever the diff is being done, append the suffix to all indices of the original table too.

**Comment by PVince81** [comment]
The thought process is as follows: in the end there are three tables:
1) The original table, ex: oc_appconfig
2) The simulated original table, ex: oc_appconfig_SUFFIX
3) The target schema table, this is what 2) willl become, also called oc_appconfig_SUFFIX

Table 2) is created by copyTable and preserves all indices. This means the indices have the same names but different namespace (table name). When transforming 2) to 3) it is logical to keep the same index names.

@icewind1991 pointed out on IRC that the reason for the suffix was because on PostgreSQL there were "duplicate index" issues. Let's hope that this was due to the old Doctrine version which wasn't able to properly detect index changes.

PR here: https://github.com/owncloud/core/pull/19347

**Comment by cmonteroluque** [comment]
@PVince81 it seems kind of silly to change severities at this point :). I am not sure really that there was a production impact but good job with the catch and the research!

**Comment by MorrisJobke** [comment]
From https://github.com/owncloud/core/pull/19347#issuecomment-145016465

> As per IRC last week, this is not a big thing for 8.2 and is low priority.
> Yes we do stuff on testing the update that is unnecessary, but only on sqlite.

@nickvergessen @PVince81 Change it to sev4?

**Comment by MorrisJobke** [comment]
sev3 as discussed with vincent, because it only applies to sqlite.

**Comment by PVince81** [comment]
Moving to 9.0 as per the PR's comment https://github.com/owncloud/core/pull/19347#issuecomment-145907077

**Comment by PVince81** [comment]
We killed update simulation in 9.2
