### ISSUE TITLE
The share link renew without a press

### ISSUE THREAD

**Issue by wilsonlmh** [owncloud/core#19321]
In Files app -> Shared links(in left side bar), the link of each share renew just after your click the "Shared" icon, but keep the original link. is there any better way (e.g. a "renew" button) to do this that avoid user confusion? you know when I got two different links point to same location(from my users), I doubt if I did something wrong. 
![image](https://cloud.githubusercontent.com/assets/5100899/10054158/4d3bff94-6262-11e5-9c7c-f94ca4c58d8b.png)

**Comment by rullzer** [comment]
Currently you can only have 1 link share per item. We won't fix this with our current implementation but we are looking at it for sharing 2.0

**Comment by PVince81** [comment]
I don't understand what you mean with "renew", can you elaborate ?

Best is to express yourself in steps, expected result, actual result as per the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by PVince81** [comment]
Closing due to lack of feedback.

As for supporting multiple share links per entry: https://github.com/owncloud/core/issues/22327
