### ISSUE TITLE
ignore system directories within webinterface

### ISSUE THREAD

**Issue by Rumbelstilzchen** [owncloud/core#19325]
My NAS creates in every directoy an indexing folder called "@eaDir". I would like to have owncloud to ignore those. So far I did not find an option to enable this within the config.php
I think I might have found a solution:
If I replace in lib\private\files\filesystem.php line 618:
`if ($dir === '.' || $dir === '..') {`
with this:
`if (in_array($dir, $this->config->getSystemValue('ignored_directories', array('..','.')))) {`
this should give me the possibility to do this trick by defining an extra entry in the config.php like `'ignored_directories'=> array('..','.','@eaDir')`?

**Comment by oparoz** [comment]
This would be great indeed, because some NAS create extra thumbnail folders and they show up in Gallery per example.

**Comment by PVince81** [comment]
See https://github.com/owncloud/core/pull/19235

**Comment by oparoz** [comment]
Good stuff!
