### ISSUE TITLE
Running occ encryption:decrypt-all without a username doesn't stop and warn the user.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#19327]
### Steps to reproduce

1. Run occ encryption:decrypt-all    (without a user)

### Expected behaviour
Command fails and tells the user it requires a user name.

### Actual behaviour
it continues until it finds that the user string is empty.
```
User "" does not exist. Please check the username and try again
 aborted.

```

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.2.0.6","versionstring":"8.2 beta1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition.
Encryption.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
Yes

**Output**

```
User "" does not exist. Please check the username and try again
 aborted.

```

**Comment by DeepDiver1975** [comment]
@schiesbn

**Comment by SergioBertolinSG** [comment]
Raising severity since the command should start to decrypt for all users instead of fail hard as discussed with @schiesbn (please correct me if I'm wrong)
