### ISSUE TITLE
OC8.1.3 upgrade->packages will be removed (apt-get upgrade)

### ISSUE THREAD

**Issue by armaccloud** [owncloud/core#19324]
Hi owncloud team,
I got the message that owncloud can be upgraded to the new version 8.1.3.
However when I perform the steps 'apt-get update && apt-get dist-upgrade' on my Ubuntu 15.04 system, it gives me the following information:

![selection_054](https://cloud.githubusercontent.com/assets/9272078/10055634/9af49442-6237-11e5-8970-59b67d3235e1.png)

Can I proceed with the upgrade in this manner or will it actually remove the mentioned packages, 'breaking' the functionality of the installation?
Thanks.

**Comment by karlitschek** [comment]
@jnweiger is this normal?

**Comment by Xenopathic** [comment]
With ownCloud 8.1.3 I believe we merged all the individual app packages into the owncloud-server package, so yes, this is completely normal and you will keep all your apps.

**Comment by RealRancor** [comment]
Yes, this is the expected behaviour when upgrading to 8.1.3

**Comment by armaccloud** [comment]
Ok, thanks. The upgrade went well.
