### ISSUE TITLE
External storage Google Drive not open a folder with some Cyrillic name.

### ISSUE THREAD

**Issue by schmel** [owncloud/core#19322]
This worked in version 7.0.7
After upgrade to Owncloud 8.1.3, owncloud sync stopped synchronization process with error:Internal Server Error. In Web GUI this folder not open.

https://youtu.be/eJ7GSYGKI0A - this bug.

Gdrive folder structure:
\Main.c\по основной деятельности.
\+Codeinside\по основной деятельности

OS: Ubuntu 14.04
root@persey:/var/www# locale
LANG=ru_RU.UTF-8
LANGUAGE=
LC_CTYPE="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER="ru_RU.UTF-8"
LC_NAME="ru_RU.UTF-8"
LC_ADDRESS="ru_RU.UTF-8"
LC_TELEPHONE="ru_RU.UTF-8"
LC_MEASUREMENT="ru_RU.UTF-8"
LC_IDENTIFICATION="ru_RU.UTF-8"
LC_ALL=

root@persey:/var/www# cat owncloud/data/owncloud.log
{"reqId":"kpert0CzH+OntDfoC6aw","remoteAddr":"92.18.186.131","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#44","level":3,"time":"2015-09-23T17:46:17+00:00"}
{"reqId":"kpert0CzH+OntDfoC6aw","remoteAddr":"92.18.186.131","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#44","level":3,"time":"2015-09-23T17:46:18+00:00"}
{"reqId":"kpert0CzH+OntDfoC6aw","remoteAddr":"92.18.186.131","app":"index","message":"Exception: {\"Exception\":\"Google_IO_Exception\",\"Message\":\"Connection timed out after 100000 milliseconds\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/google-api-php-client\\\/src\\\/Google\\\/IO\\\/Abstract.php(125): Google_IO_Curl->executeRequest(Object(Google_Http_Request))\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/google-api-php-client\\\/src\\\/Google\\\/Http\\\/REST.php(42): Google_IO_Abstract->makeRequest(Object(Google_Http_Request))\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/google-api-php-client\\\/src\\\/Google\\\/Client.php(556): Google_Http_REST::execute(Object(Google_Client), Object(Google_Http_Request))\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/google-api-php-client\\\/src\\\/Google\\\/Service\\\/Resource.php(195): Google_Client->execute(Object(Google_Http_Request))\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/google-api-php-client\\\/src\\\/Google\\\/Service\\\/Drive.php(1783): Google_Service_Resource->call('list', Array, 'Google_Service_...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/google.php(118): Google_Service_Drive_Files_Resource->listFiles(Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/google.php(343): OC\\\\Files\\\\Storage\\\\Google->getDriveFile('?????? ????????...')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/common.php(154): OC\\\\Files\\\\Storage\\\\Google->isUpdatable('?????? ????????...')\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/common.php(605): OC\\\\Files\\\\Storage\\\\Common->getPermissions('?????? ????????...')\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/encryption.php(149): OC\\\\Files\\\\Storage\\\\Common->getMetaData('?????? ????????...')\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(543): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->getMetaData('?????? ????????...')\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(113): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getMetaData('?????? ????????...')\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(141): OC\\\\Files\\\\Cache\\\\Scanner->getData('?????? ????????...')\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(344): OC\\\\Files\\\\Cache\\\\Scanner->scanFile('?????? ????????...', 1, 7588, Array, true)\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(384): OC\\\\Files\\\\Cache\\\\Scanner->scanChildren('?????? ????????...', true, 1, Array, true)\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(267): OC\\\\Files\\\\Cache\\\\Scanner->scanChildren('?????? ????????...', true, 1, Array, true)\\n#16 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(419): OC\\\\Files\\\\Cache\\\\Scanner->scan('?????? ????????...', true, 1)\\n#17 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/utils\\\/scanner.php(124): OC\\\\Files\\\\Cache\\\\Scanner->backgroundScan()\\n#18 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/ajax\\\/scan.php(55): OC\\\\Files\\\\Utils\\\\Scanner->backgroundScan('')\\n#19 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(154) : runtime-created function(1): require_once('\\\/var\\\/www\\\/ownclo...')\\n#20 [internal function]: __lambda_func(Array)\\n#21 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(274): call_user_func('?lambda_364', Array)\\n#22 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(874): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/aja...')\\n#23 \\\/var\\\/www\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n#24 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/google-api-php-client\\\/src\\\/Google\\\/IO\\\/Curl.php\",\"Line\":81}","level":4,"time":"2015-09-23T17:48:13+00:00"}
{"reqId":"kpert0CzH+OntDfoC6aw","remoteAddr":"92.18.186.131","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/owncloud\/lib\/private\/eventsource.php:99) at \/var\/www\/owncloud\/lib\/private\/response.php#103","level":3,"time":"2015-09-23T17:48:13+00:00"}

**Comment by schmel** [comment]
Insync (other gdrive client) ignore this folder.
Gdrive client - sync this folder.
Owncloud - stop sync with error.

**Comment by PVince81** [comment]
Have you tried setting the locale of the ownCloud process to en_US.UTF-8 ?

Did you upload the files to GDrive directly or through ownCloud ?

**Comment by PVince81** [comment]
Closing due to lack of feedback. You might have more luck with more recent versions like 9.1.1 where we updated the GDrive library.
