### ISSUE TITLE
IMAP auth do not work with 8.1.3

### ISSUE THREAD

**Issue by piccardi** [owncloud/core#19323]
Hi just installed a fresh  8.1.3 version, enabled external auth app, added:

  'user_backends' =>
  array (
    0 =>
    array (
      'class' => 'OC_User_IMAP',
      'arguments' =>
      array (
        0 => '{localhost:143/imap}',
      ),
    ),
  ),

to config/config.php and when trying a login with an IMAP user (just working fine with redmine in the same server) I'm getting:

{"reqId":"qKcyqFfgPyXsVWrgVEbp","remoteAddr":"XXX.XX.XX.XXX","app":"core","message":"User backend OC_User_IMAP already initialized.","level":0,"time":"2015-09-23T19:00:18+00:00","method":"POST","url":"\/owncloud\/index.php"}
{"reqId":"qKcyqFfgPyXsVWrgVEbp","remoteAddr":"XXX.XX.XX.XXX","app":"core","message":"Login failed: 'user@workingfineinroundcube' (Remote IP: 'XXX.XX.XX.XXX)","level":2,"time":"2015-09-23T19:00:18+00:00","method":"POST","url":"\/owncloud\/index.php"}

In another server I have an old version (8.0.4) that's working fine.

Regards
Simone

**Comment by MorrisJobke** [comment]
This app has been moved to the apps repository - It also looks like this issue is already reported there https://github.com/owncloud/apps/issues?utf8=✓&q=is%3Aissue+is%3Aopen+imap

-> closing this one here (feel free to reopen it in the apps repo)
