### ISSUE TITLE
Suggestion: Avoid annoying error flooding

### ISSUE THREAD

**Issue by africanforest** [owncloud/core#19320]
I'm running OwnCloud 8.1.3 with PHP 5.6. I believe to know that the error below is due to a PHP 5.6 issue, but since i'm on a shared host, i have no access to the php.ini. This error is constantly flooding the logfile of OwnCloud by reporting the same error again and again each minute!

The error message is:

Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. at Unknown#0

Please provide something to filter out such unwanted and useless errors for users that are not running an own server, thus cannot modify server configuration settings easily.

**Comment by karlitschek** [comment]
@LukasReschke Can you have a look?

**Comment by africanforest** [comment]
Me? Not sure i understood correctly. I can provide my logfile from 2015-09-18 to 2015-09-23 which is already 11 MB and constantly growing.

**Comment by Xenopathic** [comment]
This warning is generated by PHP itself, ownCloud has nothing to do with it. Please inform your shared hoster that this is happening, as it also affects all other users of PHP on that hoster.

**Comment by africanforest** [comment]
Thanks for the info.
