### ISSUE TITLE
"P" PHP module missing, but "P" does not exist. 

### ISSUE THREAD

**Issue by guillaumesoucy** [owncloud/core#19338]
When installing ownCloud server on my server, I got a message saying:
The following PHP modules are required to use ownCloud: P

But there was not PHP module named "P".

Server Version: Apache/2.2.31 (Unix)
Database: MySQL
PHP Version: 5.6.13
ownCloud version: 8.1.3
Updated from an older ownCloud or fresh install:  Fresh Install
List of activated apps: No one installed
Are you using external storage, if yes which one: No External Storage Installed. 
Are you using encryption: No
Are you using an external user-backend, if yes which one: No

![image mac 1 2015-09-24 05-49-51](https://cloud.githubusercontent.com/assets/14819445/10070951/f74dd004-6283-11e5-81a4-105735088880.png)

**Comment by karlitschek** [comment]
Do you have something in the owncloud.log ?

**Comment by MorrisJobke** [comment]
@guillaumesoucy Do you use a theme? This looks really like an old ownCloud.

Can you also check the method `checkServer` in `lib/private/util.php` https://github.com/owncloud/core/blob/d7a923671fa4b10f74dc615b583f6d4f5935d45b/lib/private/util.php#L562-L797

Or maybe provide the full `lib/private/util.php`

**Comment by LukasReschke** [comment]
Please test https://github.com/owncloud/administration/pull/53, then the proper error message should appear.

That said you are like missing PDO.

**Comment by mfraschalpi** [comment]
Great @LukasReschke - I was searching for hours. That was the solution. Just activating PDO in strato managend server. Thanks!
