### ISSUE TITLE
Horrible scrolling performance on alternative mobile webkit browsers

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19334]
### Env

Firefox on Android 4.3
BlackBerry 10 browser
Chrome on iOS
Safari on iOS

### Description

On the Files side, when using Chrome on iOS, the controls bar keeps being pushed out of place when scrolling. It did not happen on 8.1 and does not happen in Gallery per example.

Works fine on Firefox, so it seems to be a Webkit only issue, but Safari does not exhibit that behaviour, so maybe some iOS only optimisations were used somewhere?

@jancborchardt @fuhaoshih

**Comment by oparoz** [comment]
Regression introduced by:
https://github.com/owncloud/core/pull/18692

**Comment by jancborchardt** [comment]
Created a revert PR at https://github.com/owncloud/core/pull/19349

**Comment by oparoz** [comment]
Thanks. It's apparently tricky to implement if you have elements below it which use `position:absolute`.
