### ISSUE TITLE
Default expiration date only contains year

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#19333]
### Steps

1. Go to admin page
1. Enable "Set default expiration date"
1. Create folder "test"
1. Share "test" with link

### Expected result
Expiration date set to 7 days later.

### Actual result
Expiration date field contains the string "2015" with no month or day!
Note that this was tested Sept 24th 2015, in case the target date seven days later would confuse the code.

### Versions
ownCloud 8.2 git master (11974477bdeb699ae924fcc6e990dd899e63cf8a)

CC @rullzer @schiesbn 

I'll bisect this.

**Comment by PVince81** [comment]
Works properly on stable8.1.

Interestingly the target date is "2015-10-1 00:00:00".

**Comment by PVince81** [comment]
Oh no... getting closer... probably related to parsing the "expiration" field as int.
I suspect that sometimes share.php returns the date as string and sometimes as timestamp :frowning:

**Comment by PVince81** [comment]
Confirmed: regression introduced by parsing the expiration as int: https://github.com/owncloud/core/pull/19295

This now solves the mystery of why we need "parseTime". I'll reconnect it properly.

**Comment by PVince81** [comment]
Hmm, looks like `parseTime` is not enough, it doesn't actually parse the date string.
So basically the sharing code was somewhat working with both formats, which means that "expiration" can indeed be either an integer or a date string... Ideally we should have a consistent format.

**Comment by PVince81** [comment]
Ok, now reading the old code, it turns out that we only use parseTime() for "stime", not expiration: https://github.com/owncloud/core/blob/v8.1.3/core/js/share.js#L857 (CC @MorrisJobke in case you have further insights)
So for now I'll let expiration pass through.

**Comment by MorrisJobke** [comment]
https://github.com/owncloud/core/pull/19297#issuecomment-142877539

**Comment by PVince81** [comment]
Okay, yet another discover: in 8.1 we also allowed "expiration" to be a date string and blindly passed it through to the date picker. But the date picker does NOT parse it properly. When opening the date picker you can see that it doesn't pick the correct date.

I also tried writing code to parse the date string into a timestamp but am running into timezone nightmare, no easy way to parse it as a UTC date.

**Comment by PVince81** [comment]
Okay I managed to parse it. And now it rather looks like "expiration" as never a timestamp and always a string... so let's make it a string.

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/core/pull/19339
