### ISSUE TITLE
[IE9] [LDAP wizard] refreshing the screen the pwd written before is visible

### ISSUE THREAD

**Issue by davitol** [owncloud/core#19330]
### Steps to reproduce
1. Configure a LDAP configuration using LDAP wizard (server tab) with IE9 
2. Refresh the screen

### Expected behaviour
The password should not be visible, but shown as dots

### Actual behaviour
The password is visible

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** ownCloud Enterprise Edition 8.2 beta1 (daily) Build:2015-09-21T03:08:19+00:00 bbd1e996050fee80795d0e656da98b6451232c6c

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Internet Explorer 9

**Comment by karlitschek** [comment]
@blizzz

**Comment by PVince81** [comment]
Possibly related to https://github.com/owncloud/core/issues/16349

The placeholder shim library used for IE9 is having trouble

**Comment by davitol** [comment]
@PVince81 Could be related.
The different behaviour between them is #16349 was shown just a tenth of second and then was hidden and in this issue it keeps not 'codified'

**Comment by PVince81** [comment]
Confirmed.

It's even worse: it seems the placeholder library isn't properly activating itself. If you start with an empty config it doesn't show any placeholder anywhere. This might explain why it doesn't automatically hide the password value...

**Comment by PVince81** [comment]
It looks like the placeholder library doesn't work properly when manually setting values with `$el.val()`  which the wizard does for all fields. I tried updating the library and made sure that its jquery adapter is enabled, but also no luck. The fields are still blank, the password still appears when set...

**Comment by PVince81** [comment]
PR here with a workaround for the password field: https://github.com/owncloud/core/pull/19828

**Comment by MorrisJobke** [comment]
@PVince81 This was in 8.2.1 milestone. Should this be back ported? It's only a sev4 ticket. I would say no.

**Comment by PVince81** [comment]
I don't care
