### ISSUE TITLE
Double checkboxes in app manager

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19348]
![387621057621](https://cloud.githubusercontent.com/assets/323220/10078803/e2c78630-62e6-11e5-8c49-63c0ed48220e.png)

@Henni @jancborchardt

**Comment by jancborchardt** [comment]
@Henni I trust you take care of all the checkbox-related issues? cc @raghunayyar and @owncloud/designers for review where needed.

**Comment by Henni** [comment]
@jancborchardt yes i do. This issue will probably be fixed by the .checkbox class

**Comment by oparoz** [comment]
Thanks!

**Comment by Henni** [comment]
for reference: #19329

**Comment by PVince81** [comment]
please retest

**Comment by PVince81** [comment]
Just tried master and now it's only a single checkbox.

Should we leave this ticket open to update its style ? @Henni

**Comment by MorrisJobke** [comment]
> Should we leave this ticket open to update its style ? @Henni

I would close it. Changing the style is another story.

**Comment by oparoz** [comment]
I agree, but let's make sure it's tracked in the meta ticket about fixing all checkboxes
