### ISSUE TITLE
missing php dependencies & rpm/yum packaging conventions

### ISSUE THREAD

**Issue by lejeczek** [owncloud/core#19345]
provoked by this: 
https://forum.owncloud.org/viewtopic.php?f=31&t=29011&p=97520#p97520
and probably many similar I'd like to ask if there is, if there is not that would be great to have, such a mechanism where we could tell oC how to lookup and choose different PHP dependencies?

From that short forum discussion you can see how easily one can cause collision/clashes between two installation of oC and their dependencies.

Also I'd vote to rename package(s) that come from isv_ownCloud_community to something like: owncloud-community(-*).
OS default distro's packages will never be able to keep up with Oc upsteam and it would be great to have that possibility to run both.

many thanks

**Comment by DeepDiver1975** [comment]
@jnweiger please have a look - thx

**Comment by RealRancor** [comment]
@DeepDiver1975 The issue itself is not really packaging related. The users in the forums thread had to uninstall:

php-google-apiclient-1.1.4-1.fc22.noarch

from their distro because oC is also shipping this lib in its 3rdparty folder:

https://github.com/owncloud/core/tree/v8.0.4/apps/files_external/3rdparty/google-api-php-client

**Comment by LukasReschke** [comment]
> from their distro because oC is also shipping this lib in its 3rdparty folder:

IMHO: Don't use distros doing that then :speak_no_evil: :hear_no_evil: :see_no_evil: - we from time to time also have custom patches and this will only lead to problems…

**Comment by RealRancor** [comment]
I don't think that the users had installed this packages. They where probably just pulled in as a dependency by other packages.

**Comment by lejeczek** [comment]
yes, many things depend on many other things in rpm world. In many linux distros there is whole plethora of those and such a neat distro as RHEL(and derivatives) provides lots of php rpms. 
Rpm do great if one knows inner workings of a code, at de-duplicating that code and so, I guess, did the guys @EPEL repositories where oC 8.0.x pulls in distro's some php deps.

Best, in my opinion, from user/admin perspective would be to have a mechanism in oC where one could tell it: hey, use this bits from here and not the other one. If something is missing look here. An easy way without hacking in.
ps. also different names for oC rpms from isv_ownCloud_community would help a lot.
thanks.

**Comment by lejeczek** [comment]
I have a small patch for spec file that fixes rpm packages names to owncloud-community-ivs-*.
Also fixes rpm builds @ Scientific Linux (against rpm.src of 8.1.3-13.1 I got from distro) which currently fails in few places.
Also fixes SELinux fcontexes portion during rpm build. (also which build would fail for non-root users).
Should I email it over somewhere for a review?

**Comment by jnweiger** [comment]
@lejeczek you can
 
* send email to jw@owncloud.com (unreliable)
* attach files here (somewhat cumbersome, involves gist or similar)
* branch the package from here:
  -  https://build.opensuse.org/package/branch_dialog/isv:ownCloud:community:8.2:testing/owncloud
  - edit, commit, check build success, ... iterate...
  - send a submit request (perfect solution)

**Comment by lejeczek** [comment]
thanks, I dropped it there
https://gist.github.com/lejeczek/ae7bd8206f09c45eef1e

if changing rpm packages names then spec file also naturally needs Provides & Obsoletes and maybe Conflicts.

**Comment by jnweiger** [comment]
* @lejeczek where is '0%{?rhel} >= 6' used? Is this Scientific?

* @lejeczek you probably mean isv where it says ivs? But still it is a misnomer. This package does not come from an independant service provider. It comes from ownCloud. This is as upstream, as upstream can be.

* A general rename of the owncloud package is unlikely to happen. Sorry. If we want the ability to rename as an option, we should first start using the %define owncloud name more consistently.

**Comment by lejeczek** [comment]
everywhere,  - rhel_version - does not exist there.
Shame, it's just rpm packaging I'd have thought. Most distros provide their own oC and this causes conflicts, not just between php code but simply renders inability to use yum/rpm to install both versions.

**Comment by lejeczek** [comment]
only, I did not get a chance to run it on SL6, sorry.

**Comment by lejeczek** [comment]
rpm rebuild fails there @SL6 as there is no rpmspec tool, probably other RHELs < 7 too.
I guess not many think/need rebuild.

**Comment by lejeczek** [comment]
fails? it does on the obs_check_deb_spec.sh snippet, but completes building.
yes - 0%{?rhel} == 6 (not 600 as per my patch)

**Comment by PVince81** [comment]
@owncloud/packaging is this still an issue ?

**Comment by PVince81** [comment]
Closing due to lack of feedback on this old issue
