### ISSUE TITLE
Increase clickable area in file list

### ISSUE THREAD

**Issue by Henni** [owncloud/core#19350]
In 8.1 the files in the filelist where clickable on the whole width.
Currently there is no action when you click on the space between the file name and the share symbol.
![image](https://cloud.githubusercontent.com/assets/1267827/10087804/91551f80-6316-11e5-90b4-e45550f40c43.png)

Such a click should either open the file/folder or show the sidebar.

@jancborchardt

**Comment by PVince81** [comment]
This is not a regression but an intended change of behavior as per https://github.com/owncloud/core/issues/18238

However that behavior wasn't good enough so https://github.com/owncloud/core/issues/18238 has been reopened to bring back parts of the old behavior.

Please follow up in https://github.com/owncloud/core/issues/18238
