### ISSUE TITLE
Image Folder Upload Ploblem

### ISSUE THREAD

**Issue by zVerdomorez** [owncloud/core#19352]
I have drag folder that contain 677 pictures 1.77GB and upload it, But look at size of picture.It is only 4 KB and cannot open. 

I have test on https://demo.owncloud.org.
![bugg](https://cloud.githubusercontent.com/assets/14266988/10092628/d390020a-6372-11e5-874d-d3be5fb0f7dc.jpg)

**Comment by PVince81** [comment]
Please use the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by zVerdomorez** [comment]
@PVince81 Oh that is my fault. That file is hidden files. Sorry about that.
