### ISSUE TITLE
File is reuploaded after choosing "new files" in the conflict dialog in the web interface

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#19359]
### Steps to reproduce
1. Upload a big file (several MB)
2. Reupload the same file
3. When the conflict dialog appears, choose the new files option

### Expected behaviour
The file is immediately substituted with the new one (the file should be already in the server)

### Actual behaviour
The file is reuploaded again after choosing the option

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** 8.2 beta1 (daily) Build:2015-09-25T03:08:40+00:00 e7bc2a10e3ffd16cda8d15ff06dcbc870e34a627 

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by PVince81** [comment]
Duplicate https://github.com/owncloud/core/issues/8664

**Comment by PVince81** [comment]
the subtext is: not technically solvable as long as we're using POST for uploads
