### ISSUE TITLE
Missing "empty message" on public pages

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19364]
![empty](https://cloud.githubusercontent.com/assets/323220/10098250/3fb330ee-6380-11e5-86c2-da04beb0518f.png)

When you reach an empty folder, you get a big, centred message with an icon telling you the folder is empty.

That message is missing from public folders. The footer is glued to the header and you get the feeling that something is broken.

@jancborchardt

**Comment by karlitschek** [comment]
yes. would be great to have this fixed

**Comment by oparoz** [comment]
It's tricky, because the empty message is absolutely positioned while the footer is a relative element, pushed by the files list...

**Comment by MorrisJobke** [comment]
Worked in 8.1.3:

![bildschirmfoto von 2015-09-25 15-29-40](https://cloud.githubusercontent.com/assets/245432/10101656/4afa669c-639a-11e5-8658-ac436e3cad3a.png)

**Comment by MorrisJobke** [comment]
cc @owncloud/designers @Henni

**Comment by jancborchardt** [comment]
Ugh … @owncloud/designers someone of you has got to take this, I’m on vacation. @oparoz maybe you know what causes this and can fix it along with the Gallery emptycontent view for sharing you work on (and also needs to be fixed)?

**Comment by oparoz** [comment]
I have no idea why the element completely disappears on that page...

Would be good to take care of this at the same time: https://github.com/owncloud/core/issues/18968

**Comment by PVince81** [comment]
@oparoz are you sure it's not the files_texteditor bug again ?

**Comment by PVince81** [comment]
Works for me on master: 9a010cc8ce281650038cd1444f63a02245eea523

Please make sure you have the latest master from files_texteditor, due to https://github.com/owncloud/files_texteditor/pull/112

**Comment by oparoz** [comment]
Correct. Which script are you using to pull everything to stay in sync?

**Comment by PVince81** [comment]
@oparoz no script... I do it manually
