### ISSUE TITLE
Blurry previews in the right side-bar

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19369]
### Steps to reproduce

1. Set max preview at 756x756
2. Upload an image which is bigger. Mine was 800x600
3. Bring up the details view

### Expected result 

A crisp preview filling up the space

### Actual result

A blurry preview filling up the space

The container is about 430x240
The image is 320x240, stretched to fit

@jancborchardt @icewind1991

**Comment by icewind1991** [comment]
Can you check what dimensions were requested for the preview

**Comment by oparoz** [comment]
`background-image: url("/owncloud/index.php/core/preview.png?file=%2F800px-Parliament_Building_Budapest_Hungary.jpg&x=99999&y=240&a=1&c=2b46808592cb98f8f3f4180e3f44fd66&forceIcon=0"); height: auto;`

99999?

**Comment by oparoz** [comment]
Wouldn't it be possible to set a max size for that thumbnail and to keep it centred, in case the width of the container is larger than the image?
If large enough, this would avoid the white space around the image in most cases.

Maybe something like 600x600?

**Comment by icewind1991** [comment]
> 99999

Something high enough that it will be ignored after the aspect ratio is handled, not setting an x limit will make it fall back to the default (32)

**Comment by jancborchardt** [comment]
cc @rullzer @Xenopathic @georgehrke regarding previews. (not sure who exactly knows what ;)
