### ISSUE TITLE
Find a way to rename a file/folder with mouse/finger interactions

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19368]
In a lot of file managers, it's possible to edit the file name without having to use a menu and it would be great if ownCloud could do the same, because the current way of having to click on a button all the way to the left, then pick a menu item, to then go back to the filename does not provide a great UX.

* ~~Double-click~~ on the filename. Only works on non-touch devices
* ~~Swipe~~ on the filename. Most desktops don't allow mouse gestures for file operations
* Long press on the filename. Works in both environments!
* Ideas please!

@jancborchardt @MorrisJobke @PVince81 @schiesbn

**Comment by oparoz** [comment]
An alternative could be to use the long press to bring up the menu on mobile. On desktop it would be the right-click. The key point is to not have to move so much around to perform basic actions

**Comment by MorrisJobke** [comment]
> An alternative could be to use the long press to bring up the menu on mobile. On desktop it would be the right-click. The key point is to not have to move so much around to perform basic actions

Right click is dying ... long press is also hard to discover

**Comment by PVince81** [comment]
@nickvergessen @schiesbn 

It was also suggested to bring back the pencil icon.
Or make the file name in the sidebar clickable and/or have the pencil icon near the file name inside the sidebar, so the renaming could happen there. (actually many file actions could be moved there)

**Comment by oparoz** [comment]
> long press is also hard to discover

@MorrisJobke - Maybe, but we're talking about an advanced interaction. Beginners can still use the 3 dots, until they discover that there is a better way, either through testing or by reading the documentation.

**Comment by jancborchardt** [comment]
Sorry but rename is just not that much of a common action, so we’re not bringing back a pencil icon directly there. Right-click is not discoverable (and not available on mobile) and long-press is reserved for multiselect if anything.

I doubt this is a problem. cc @owncloud/designers

**Comment by blizzz** [comment]
I don't think this is an issue either, and since there are no contributions since 9/15 I guess there's no more input to it. Thus closing, please reopen if there is anything to do or discuss left.
