### ISSUE TITLE
Add javascript method to set oc_preferences

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#19361]
As indicated by https://github.com/owncloud/core/blob/master/core/js/config.js#L58 we need a proper way to set preferences via javascript. 

Then we could convert #19354 to use per user preferences instead of global.

CC: @PVince81

**Comment by PVince81** [comment]
Is there an OCS API for that ?
The one that comes to mind is a different one and is called "privatedata".

**Comment by PVince81** [comment]
moving to backlog. If these APIs are needed by features, they should be added as part of it.

**Comment by PVince81** [comment]
I don't think it's a good idea as it would open a way for users to change arbitrary values in their preferences and potentially break things. Changing arbitrary values is something I'd only leave up to an admin.

For now, apps need to use their own endpoints to set specific user preferences as needed.
