### ISSUE TITLE
Federated cloud sharing: New share to remote user times out, 

### ISSUE THREAD

**Issue by Kawohl** [owncloud/core#19370]
### Steps to reproduce
1.Have two owncloud instances running
2.Share  a folder or file from one to another
3.

### Expected behaviour

Share should appear in remote cloud of user shared with..

### Actual behaviour

Share times out saying :Freigabe von CentOS6,redis fehlgeschlagen, da carlos@cloud.damken.com nicht gefunden wurde. Möglicherweise ist der Server nicht erreichbar.

### Server configuration
**Operating system**:
Ubuntu 14.04
**Web server:**
Apache 2.4
**Database:**
Mysql
**PHP version:**
5.5.9-1ubuntu4.12
**ownCloud version:** (see ownCloud admin page)
8.1.3 (stable) 
**Updated from an older ownCloud or fresh install:**
updated from 8.1.2 (stable)

**List of activated apps:**
 - activity: 2.0.2
 - files: 1.1.10
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - registration: 0.0.7
 - templateeditor: 0.1
Disabled:
 - encryption
 - external
 - files_external
 - search_lucene
 - updater
 - user_external
 - user_ldap
 - user_webdavauth

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'ocqpce2svge0',
  'passwordsalt' => 
  'secret' => '
  'trusted_domains' => 
  array (
    0 => '46.101.140.225',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'https://46.101.140.225/',
  'dbtype' => 'mysql',
  'version' => '8.1.3.0',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_John',
  'dbpassword' => 
  'logtimezone' => 'UTC',
  'installed' => true,
  'appstore.experimental.enabled' => true,
  'mail_from_address' => 'john.kawohl',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'gmail.com',
  'maintenance' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'smtp.gmail.com',
  'mail_smtpport' => '465',
  'mail_smtpname' => 'john.kawohl',
  'mail_smtppassword' => 'xxxxxxx',
  'mail_smtpsecure' => 'ssl',
);

**Are you using external storage, **
no

**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

Second Server:

As above... since I´m not sure which logs you need feel free to tell me

**Comment by Kawohl** [comment]
@cdamken

**Comment by MorrisJobke** [comment]
@Kawohl Can you reach the remote server from your server? Maybe do a `ping ...` or a `curl https://cloud.damken.com/status.php` to see if your server is able to connect to the remote server.

Entries of the owncloud.log would also be helpful.

**Comment by Kawohl** [comment]
curl output: 

```{"installed":true,"maintenance":false,"version":"8.1.3.0","versionstring":"8.1.3","edition":""}````

Output on remote server of owncloud.log: 

``` Exception while scanning storage "shared::36ef21ed89d29eccb163f929578fdf9e": Sabre\HTTP\ClientException: SSL certificate problem: self signed certificate```

One bad thing that happens also t on the remote server instead of listing all the files after reloading the page it only shows the  "processing Circle" of death. 
To repair this you need to delete the share on the remote server in  oc_files_external to make your files appear in the browser.

**Comment by MorrisJobke** [comment]
> Exception while scanning storage "shared::36ef21ed89d29eccb163f929578fdf9e": Sabre\HTTP\ClientException: SSL certificate problem: self signed certificate

It's a not trusted certificate. I think your server doesn't have a valid cert.

> One bad thing that happens also t on the remote server instead of listing all the files after reloading the page it only shows the "processing Circle" of death.
> To repair this you need to delete the share on the remote server in oc_files_external to make your files appear in the browser.

This is really bad. cc @LukasReschke @schiesbn

**Comment by LukasReschke** [comment]
Tried the same on 8.1.1, I see the SSL exception but still can access my whole data.

**Comment by MorrisJobke** [comment]
Also cloud.damken.com is not reachable. :see_no_evil:

**Comment by LukasReschke** [comment]
I shared from 46.101.140.225 to cloud.smartworksg.ch

**Comment by LukasReschke** [comment]
> Also cloud.damken.com is not reachable. :see_no_evil:

So maybe it happens when the accepted remote host is not online…?

**Comment by Kawohl** [comment]
@MorrisJobke @LukasReschke maybe carlos1.0 rebooted. I can connect to  cloud.damken.com

**Comment by Kawohl** [comment]
@cdamken maybe you have some ideas or other logs?

**Comment by schiesbn** [comment]
> Share times out saying :Freigabe von CentOS6,redis fehlgeschlagen, da carlos@cloud.damken.com nicht gefunden wurde. Möglicherweise ist der Server nicht erreichbar.

This sounds like the server wasn't reachable while you tried to create the share. What happens if you re-try it, but check right before if the server is really online?

SSL shouldn't be a issue because you didn't enforced ssl, so if ssl fails it should fall back to non-ssl automatically, iirc (will double check).

**Comment by Kawohl** [comment]
We've checked and the server was reachable at that time. 
SSL  is enforced as far as i know.... correct me if im wrong.

**Comment by schiesbn** [comment]
> SSL is enforced as far as i know.... correct me if im wrong.

If the remote server enforces SSL then of course it has to be a certificate which can be validated by the sharing server. I just checked, cloud.damken.com uses a SSL certificate from StartCom, they should work fine.

**Comment by schiesbn** [comment]
I just tried to send a remote share to @cdamken (sorry for the spam :wink: ) Worked fine, from my side. @cdamken did you received the share?

**Comment by schiesbn** [comment]
@cdamken just confirmed that he received my server-to-server share. @Kawohl do you enforce ssl on your server too? What kind of certificate do you use?

**Comment by Kawohl** [comment]
Ah o.k. ,now i get it because my instance has a self signed certificate , @cdamken 's server can't read from mine. Is this documented somewhere?

**Comment by Kawohl** [comment]
So enforced ssl needs a public known cert from start ssl or similar for federated cloud sharing.

**Comment by schiesbn** [comment]
@Kawohl yes, carlos just shared a file with me from your ownCloud. I received it and could accept it. But is wasn't mounted on my server because it was a untrusted SSL certificate.

I did following to see the file on my server:
- enable the external storage app on my server and allow the users to mount at least one external storage
- go to my users preferences: Now I could upload ssl certificates I trust in the "ssl root certificates" section
- I went to your ownCloud with firefox, looked at the certificate details and exported it
- added it on my onwCloud to the certificates I trust
-> the shared file showed up.

@LukasReschke Two issues here:
1. With our latest changes (you remember) the user can now only add trusted certificates if the external storage app is enabled and if he can mount at least one type of external storages.
2. I think we definitely need some kind of pop-up in this case asking the user if he want to trust the certificate and then import it automatically.

**Comment by schiesbn** [comment]
If you want to use server-to-server sharing I would recommend to get a trusted SSL certificate. At https://startssl.com/ you can get one for free.

**Comment by Kawohl** [comment]
@schiesbn 

Thanks for the info! As you said above a popup or something would be great! Thanks!
What do you think , should we close this and open an "enhancement issue"?

**Comment by MorrisJobke** [comment]
> Thanks for the info! As you said above a popup or something would be great! Thanks!
> What do you think , should we close this and open an "enhancement issue"?

Feel free to do so and only add the needed use cases. Thanks

**Comment by schiesbn** [comment]
> Thanks for the info! As you said above a popup or something would be great! Thanks!
What do you think , should we close this and open an "enhancement issue"?

Yes, would be great if you could open a enhancement issue for it.

**Comment by Kawohl** [comment]
opened enhancement here: https://github.com/owncloud/core/issues/19599
