### ISSUE TITLE
hard to open the sidebar

### ISSUE THREAD

**Issue by jospoortvliet** [owncloud/core#19375]
While trying to view the activity stream of a file (nice feature of the sidebar!) and the larger file preview, I struggled to get the sidebar to open. It doesn't open anymore on a simple click of the file - nothing happens.

Turns out, you first have to click the sharing button (perhaps there's another, even more hidden way) and THEN you can switch between files clicking the empty space behind the name.

I'm not sure if this is intentional but if it is I wonder what the reason is why we want to hide our nice new sidebar?

This is with the daily snapshot from 2 days ago.

@owncloud/designers

**Comment by oparoz** [comment]
It's being worked on https://github.com/owncloud/core/pull/19365 and once you use that branch, it's really hard to go back to using master :D

**Comment by jospoortvliet** [comment]
Ok, then - closing this! Thanks.
