### ISSUE TITLE
New share to user of same instance times out

### ISSUE THREAD

**Issue by stormsh** [owncloud/core#19372]
This issue is similar to this one:
https://github.com/owncloud/core/issues/19370

Steps to reproduce

1.Have owncloud instance running
2.Share a folder or file from one user to another
3.
Expected behaviour

Share should appear in cloudfrontend of user shared with...

Actual behaviour

The share takes a very long time. Then OC "freezes". 
No response whatsoever. Windows desktop Client still working and syncing. Neither Apache nor nginx time out. 
Problem solvable only by restarting apache.
Nothing in the oc log files. Apache log shows one interesting thing:

    [Thu Sep 24 17:49:54.552436 2015] [core:notice] [pid 5664] AH00051: child pid 6699 exit signal Segmentation fault (11), possible coredump in /etc/apache2
    [Thu Sep 24 17:49:54.552564 2015] [mpm_prefork:notice] [pid 5664] AH00169: caught SIGTERM, shutting down

I checked the folder /etc/apache2 but couldn't find a dump.

Operating system:
Ubuntu 14.04
Web server:
Apache 2.4
Database:
Mysql
PHP version:
5.5.9
ownCloud version: (see ownCloud admin page)
8.1.3 (stable)
Updated from an older ownCloud or fresh install:
updated from 8.1.1 (stable)

List of activated apps:

    activity
    bookmarks
    calendar
    contacts
    documents
    encryption
    external
    files
    files_locking:
    files_opds
    files_pdfviewer
    files_reader
    files_sharing
    files_texteditor
    files_trashbin
    files_versions
    files_videoviewer
    firstrunwizard
    gallery
    news
    polls
    provisioning_api
    updater
    user_external
    user_ldap
    user_webdavauth

The content of config/config.php:
><?php
$CONFIG = array (
  'instanceid' => 'XXX',
  'passwordsalt' => 'XXX',
  'secret' => 'XXX',
  'trusted_domains' => 
  array (
    0 => 'XXX.domain.de',
  ),
  'datadirectory' => 'XXX.data',
  'overwrite.cli.url' => 'XXX',
  'dbtype' => 'mysql',
  'version' => '8.1.3.0',
  'dbname' => 'db',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'user',
  'dbpassword' => 'XXX',
  'installed' => true,
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\Image',
    1 => 'OC\\Preview\\MP3',
    2 => 'OC\\Preview\\TXT',
    3 => 'OC\\Preview\\MarkDown',
    11 => 'OC\\Preview\\Epub',
  ),
  'loglevel' => 1,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'theme' => '',
  'maintenance' => false,
  'mail_from_address' => 'XXX',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'XXX.de',
  'memcache.local' => '\\OC\\Memcache\\APCu',
);>

*Are you using external storage, *
no

Are you using encryption: yes/no
yes

Are you using an external user-backend, if yes which one: LDAP/ActiveDirectory/Webdav/...
no

Anyone an Idea what it could be or where I start looking?

Thx 4 F1.

st.

**Comment by PVince81** [comment]
Please follow up here: https://github.com/owncloud/core/issues/19488#issuecomment-144935001
