### ISSUE TITLE
Improve webdav or OCS API to get the sharer names

### ISSUE THREAD

**Issue by lgreulich** [owncloud/core#19371]
When using webdav 'list' to get the folders and files, shared folders and files are automatically added by OwnCloud but the user who shared them is not included.
We did not find any call in the OCS API which allows to get the sharer names.

Proposed improvement:
Add sharer name to webdav 'list' response or to OCS API.

### Steps to reproduce
1. Use webdav 'list' to get the folders and files.
2. Shared folders and files are automatically added by OwnCloud but the user who shared them is not included.
3. We did not find any call in the OCS API which allows to get the sharer names.

### Expected behaviour
When returning folders and files on webdav 'list' call, the user who shared the file should be included as information.

### Actual behaviour
Folder and files are returned by OwnCloud but the user who shared them is not included.

### Server configuration
**Operating system**: Debian

**ownCloud version:** 7.0.8

**Comment by rullzer** [comment]
So you want for a given shared file find out who shared it with you?

In that case you are probably looking for:

`/ocs/v1.php/apps/files_sharing/api/v1/shares?shared_with_me=1`

**Comment by lgreulich** [comment]
OK, thanks, yes, this was it. We didn't find it in the documentation:
https://doc.owncloud.org/server/7.0/developer_manual/core/ocs-share-api.html

Is there other things we could access trough this API that are not in the documentation?

**Comment by PVince81** [comment]
Doc ticket has been raised here: https://github.com/owncloud/documentation/issues/2064
