### ISSUE TITLE
Re-work the close button for the right side-bar

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19377]
Something for the next release. The current solution is probably good enough.

The problems with that x: 
- Smaller that the other UI elements
- Hard to see in some circumstances. A border would really help, but they've been removed everywhere... Maybe go all in and add a proper, plain chevron button. The image is a preview. I think it's OK if there is a button hiding a tiny bit of it
- Can be confused with something which hides the preview. Doesn't seem like it belongs to the side-bar

@jancborchardt and crew
@schiesbn @icewind1991 @MorrisJobke @PVince81

**Comment by MorrisJobke** [comment]
cc @owncloud/designers

**Comment by jancborchardt** [comment]
What do the others think? We haven’t gotten any other reports so far, and I don’t really see it as that much of a problem.

**Comment by PVince81** [comment]
Got used to it in the end

**Comment by oparoz** [comment]
>Got used to it in the end

Yes, it's difficult to look at it with fresh eyes.

Here is an example of what I mean... The where-is-the-close-button

![where-is-the-close-button](https://cloud.githubusercontent.com/assets/323220/13640348/901d99b8-e614-11e5-8581-86e9517b44b7.png)
 game

**Comment by jancborchardt** [comment]
However, that’s really quite an edge-case (only with image, in a specific aspect ratio, and specific colors in the top right) and it mostly occurs when you already know where the close button is anyway, no?

**Comment by oparoz** [comment]
Well, A lot of images are in landscape mode and unless you always have a plain background in the top right, it's really easy to miss that close button.
I'm sure users find it, eventually, but I just think "we" can do better.
