### ISSUE TITLE
upgrade owncloud to 8.1.3 ist failing

### ISSUE THREAD

**Issue by balladasdarein** [owncloud/core#19387]
OC\DatabaseException: An exception occurred while executing 'DELETE FROM "oc_queuedtasks" WHERE "app"=?': SQLSTATE[HY000]: General error: 1 no such table: oc_queuedtasks

**Comment by RealRancor** [comment]
Dup of owncloud/search_lucene#90, #18327, #18247, #18712, https://github.com/owncloud/core/issues/19184

This still needs a new release of search_lucene at the appstore including the fix of owncloud/search_lucene#102

**Comment by MorrisJobke** [comment]
> This still needs a new release of search_lucene at the appstore including the fix of owncloud/search_lucene#102

@karlitschek Who can do that?

**Comment by karlitschek** [comment]
Everyone with admin right should be able to do that. @butonic @MorrisJobke can you try?

**Comment by MorrisJobke** [comment]
> Everyone with admin right should be able to do that. @butonic @MorrisJobke can you try?

Seems that I'm not an admin ;)

**Comment by butonic** [comment]
On 28.09.2015 08:41, Morris Jobke wrote:
>     Everyone with admin right should be able to do that. @butonic
>     <https://github.com/butonic> @MorrisJobke
>     <https://github.com/MorrisJobke> can you try?
>
> Seems that I'm not an admin ;)
me neither

**Comment by butonic** [comment]
@LukasReschke probably

**Comment by balladasdarein** [comment]
deleting apps/search_lucene/appinfo/update.php solved my problem, many thanks
