### ISSUE TITLE
Strange error when setting password on a share link

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#19381]
I get this:
![share-with-password-press-enter](https://cloud.githubusercontent.com/assets/925062/10111501/8ca6e078-6428-11e5-8e2b-745829543d28.png)

Can you replicate @schiesbn? cc @Blizzz @PVince81

**Comment by PVince81** [comment]
@jancborchardt please use the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

Without knowing what kind of share you were creating (reshare?) and whether you set an expiration date, etc, it will be difficult to reproduce this.

**Comment by jancborchardt** [comment]
As seen from the screenshot:

* it’s a normal share, of a text file. No reshare
* no expiration date set


1. Press share on the file
2. Share link
3. Set a password and press enter -> error above occurs.

**Comment by PVince81** [comment]
Works for me on OC 8.2RC1 with Chromium 43.

Anything in the server log ?

**Comment by PVince81** [comment]
tested with mariadb and sqlite, both work

**Comment by jancborchardt** [comment]
Ok, must have been another remnant from an old setup. Nuked my dev installation and started anew. ;)
