### ISSUE TITLE
enhancement idea: Global sync-exclude.lst

### ISSUE THREAD

**Issue by Psy-Virus** [owncloud/core#19385]
Hey folks,

I was thinking about a GitHub-repository like use of Owncloud, in that way, that I share a folder where I update the content from time to time. But some files, a config file for example, should not be synced. And instead of telling every user to update it's clients ignore list, I was thinking about if it will be possible or if you want to implement this feature in the future?

Or maybe that the ignore list is handled via Owncloud instead of the client?

Hope you like the idea..

Thanks in advance

:-)

**Comment by oparoz** [comment]
Please test this PR: https://github.com/owncloud/core/pull/19235

**Comment by mmattel** [comment]
@oparoz I personally would like to seperate PR #19235 from this idea. From the concept point of view this requirement could easily be implemented as a "excluded" directory". But I would recommend to create a new config.php parameter and add the query against in the PR. Then things are more clear, even if we change the underlaying coding.

**Comment by mmattel** [comment]
hmmm, thinking more about this.
@Psy-Virus do I get it right that the original share owner should have full view and access while share taker and eventually reshare taker should have restricted view and access? PR #19235 does not distinguish between this, it prevents view and access to everybody.

We do have already a config.php parameter ``blacklisted_files' => array('.htaccess')`` but this has a very special meaning, works share independent and should imho *not* be used for.

@oparoz can we distinguish if an access comes from the original share owner versus a share (reshare) taker?

**Comment by oparoz** [comment]
> @oparoz can we distinguish if an access comes from the original share owner versus a share (reshare) taker?

It's possible to write a test for it (if currentUser === fileOwner), but I have no idea if there is an API method which does the same.

Reading the OP, I thought the request was about creating a global gitignore. There are files you're using locally and that you never want to sync. Sharees will have similar files in their tree and they will be mixed with files they sync with ownCloud.
Kind of like the snapshot or thumbnail scenario. You're OK to share everything else, just not the content of those folders.

**Comment by mmattel** [comment]
oh, sorry got it. I misinterpreted, cancel my comment...

**Comment by Psy-Virus** [comment]
Hey @mmattel,

> do I get it right that the original share owner should have full view and access while share taker and eventually reshare taker should have restricted view and access?

I thought more about something like the .gitignore file. The title is maybe a little bit irritating, sorry.

Okay, so I'll bring an example:
Let's say I will share a program, that I also want to maintain and/or update. Your are the client, that will profit from this simple method of updating. the program creates a config.file. This config.file shouldn't be synced, because every client will have it's very own setting in it.

But to tell everyone to add this and this and this file to the ignore list of it's sync_client is crap. So I thought about a more global handling, but per directory/share

The share would be configured that way, that the user will only have read access, so the source files can't be changed by them.
A 'simple' checkbox named "ignored files" or something in this direction would be a cool addition to the share dialog.

And this brings me to another idea, that the client_ignore_file should be handled via the userprofile on the server and also be synced. I bet there are tons of users who sync files from one pc to the server and to another pc and smart phone and laptop and mac and linux box. So It's not really cool to setup the ignores on all clients one by one.
Is this now a Client or a Core enhancement? XD

@oparoz 

I think this is too global :D But thanks anyway^^

Should I change the title?

**Comment by PVince81** [comment]
Some ideas here as well: https://github.com/owncloud/core/issues/25873

Basically having the server send an extra Webdav property to tell clients that this file/folder exists but must not be synced. How and when this property is set could, as per this ticket here (not the linked one), would be to have code return this property for excluded file patterns as well.

**Comment by PVince81** [comment]
Add webdav property to tell sync client to not sync an entry: https://github.com/owncloud/core/issues/26311

**Comment by PVince81** [comment]
or advertise a global exclusion list through the capabilities API

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/issues/7956
