### ISSUE TITLE
Fatal Error after upgrading the Owncloud to 8.1.3

### ISSUE THREAD

**Issue by vijaykumar0690** [owncloud/core#19388]
Hi team,

We are not able to login with AD user name and password after the upgrade.
I am able to login as the OwnCloud user and i can see that my AD connection is fine and shows in green.
But in the owncloud.log i see that its not working and it tells me that connection to the AD server has been lost.

Can you give me the solution for the issue.
below is the log,
Meanwhile i have to fall back to the older version.

Regards,
Vijay
root@ip-172-16-100-8:/var/www/owncloud/data# tail -f owncloud.log
{"reqId":"jEKbUIXkb8B7F\/mg\/3Yq","remoteAddr":"106.51.126.111","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => cn=kumar vijay,cn=users,dc=germany,dc=weh,dc=com\n)\n attr Array\n(\n    [0] => \n)\n limit 500 offset 0","level":0,"time":"2015-09-26T11:32:23+00:00","method":"GET","url":"\/index.php\/apps\/files\/"}
{"reqId":"jEKbUIXkb8B7F\/mg\/3Yq","remoteAddr":"106.51.126.111","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2015-09-26T11:32:23+00:00","method":"GET","url":"\/index.php\/apps\/files\/"}
{"reqId":"jEKbUIXkb8B7F\/mg\/3Yq","remoteAddr":"106.51.126.111","app":"user_ldap","message":"readAttribute: cn=kumar vijay,cn=users,dc=germany,dc=weh,dc=com found","level":0,"time":"2015-09-26T11:32:23+00:00","method":"GET","url":"\/index.php\/apps\/files\/"}
{"reqId":"LmK81XeTekOU+sveEKXe","remoteAddr":"106.51.126.111","app":"user_ldap","message":"No group filter is specified, LDAP group feature will not be used.","level":1,"time":"2015-09-26T11:32:56+00:00","method":"GET","url":"\/index.php\/apps\/files\/"}
{"reqId":"LmK81XeTekOU+sveEKXe","remoteAddr":"106.51.126.111","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => cn=kumar vijay,cn=users,dc=germany,dc=weh,dc=com\n)\n attr Array\n(\n    [0] => \n)\n limit 500 offset 0","level":0,"time":"2015-09-26T11:32:57+00:00","method":"GET","url":"\/index.php\/apps\/files\/"}
{"reqId":"LmK81XeTekOU+sveEKXe","remoteAddr":"106.51.126.111","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2015-09-26T11:32:57+00:00","method":"GET","url":"\/index.php\/apps\/files\/"}
{"reqId":"LmK81XeTekOU+sveEKXe","remoteAddr":"106.51.126.111","app":"user_ldap","message":"readAttribute: cn=kumar vijay,cn=users,dc=germany,dc=weh,dc=com found","level":0,"time":"2015-09-26T11:32:57+00:00","method":"GET","url":"\/index.php\/apps\/files\/"}
{"reqId":"LmK81XeTekOU+sveEKXe","remoteAddr":"106.51.126.111","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => cn=kumar vijay,cn=users,dc=germany,dc=weh,dc=com\n)\n attr Array\n(\n    [0] => \n)\n limit 500 offset 0","level":0,"time":"2015-09-26T11:32:57+00:00","method":"GET","url":"\/index.php\/apps\/files\/"}
{"reqId":"LmK81XeTekOU+sveEKXe","remoteAddr":"106.51.126.111","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2015-09-26T11:32:57+00:00","method":"GET","url":"\/index.php\/apps\/files\/"}
{"reqId":"LmK81XeTekOU+sveEKXe","remoteAddr":"106.51.126.111","app":"user_ldap","message":"readAttribute: cn=kumar vijay,cn=users,dc=germany,dc=weh,dc=com found","level":0,"time":"2015-09-26T11:32:57+00:00","method":"GET","url":"\/index.php\/apps\/files\/"}
{"reqId":"jEKbUIXkb8B7F\/mg\/3Yq","remoteAddr":"106.51.126.111","app":"index","message":"Exception: {\"Exception\":\"OC\\\\ServerNotAvailableException\",\"Message\":\"Lost connection to LDAP server.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/ldap.php(259): OCA\\\\user_ldap\\\\lib\\\\LDAP->postFunctionCall()\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/ldap.php(42): OCA\\\\user_ldap\\\\lib\\\\LDAP->invokeLDAPMethod('bind', Resource id #34, 'cn=LDAPReader,c...', 'buddha')\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/connection.php(609): OCA\\\\user_ldap\\\\lib\\\\LDAP->bind(Resource id #34, 'cn=LDAPReader,c...', 'buddha')\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/connection.php(541): OCA\\\\user_ldap\\\\lib\\\\Connection->bind()\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/connection.php(160): OCA\\\\user_ldap\\\\lib\\\\Connection->establishConnection()\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/connection.php(168): OCA\\\\user_ldap\\\\lib\\\\Connection->init()\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/access.php(152): OCA\\\\user_ldap\\\\lib\\\\Connection->getConnectionResource()\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/user_ldap.php(180): OCA\\\\user_ldap\\\\lib\\\\Access->readAttribute('cn=kumar vijay,...', '')\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/user_ldap.php(215): OCA\\\\user_ldap\\\\USER_LDAP->userExistsOnLDAP(Object(OCA\\\\user_ldap\\\\lib\\\\user\\\\User))\\n#9 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/user_ldap.php(261): OCA\\\\user_ldap\\\\USER_LDAP->userExists('Kumar-Vijay')\\n#10 [internal function]: OCA\\\\user_ldap\\\\USER_LDAP->getHome('Kumar-Vijay')\\n#11 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/user_proxy.php(67): call_user_func_array(Array, Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/proxy.php(137): OCA\\\\user_ldap\\\\User_Proxy->walkBackends('Kumar-Vijay', 'getHome', Array)\\n#13 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/user_proxy.php(191): OCA\\\\user_ldap\\\\lib\\\\Proxy->handleRequest('Kumar-Vijay', 'getHome', Array)\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/user\\\/user.php(231): OCA\\\\user_ldap\\\\User_Proxy->getHome('Kumar-Vijay')\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/user.php(573): OC\\\\User\\\\User->getHome()\\n#16 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(378): OC_User::getHome('Kumar-Vijay')\\n#17 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(350): OC\\\\Files\\\\Filesystem::initMountPoints('Kumar-Vijay')\\n#18 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/util.php(190): OC\\\\Files\\\\Filesystem::init('Kumar-Vijay', '\\\/Kumar-Vijay\\\/fi...')\\n#19 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(873): OC_Util::setupFS()\\n#20 \\\/var\\\/www\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n#21 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/ldap.php\",\"Line\":289}","level":4,"time":"2015-09-26T11:33:26+00:00","method":"GET","url":"\/index.php\/apps\/files\/"}
{"reqId":"LmK81XeTekOU+sveEKXe","remoteAddr":"106.51.126.111","app":"index","message":"Exception: {\"Exception\":\"OC\\\\ServerNotAvailableException\",\"Message\":\"Lost connection to LDAP server.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/ldap.php(259): OCA\\\\user_ldap\\\\lib\\\\LDAP->postFunctionCall()\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/ldap.php(42): OCA\\\\user_ldap\\\\lib\\\\LDAP->invokeLDAPMethod('bind', Resource id #34, 'cn=LDAPReader,c...', 'buddha')\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/connection.php(609): OCA\\\\user_ldap\\\\lib\\\\LDAP->bind(Resource id #34, 'cn=LDAPReader,c...', 'buddha')\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/connection.php(541): OCA\\\\user_ldap\\\\lib\\\\Connection->bind()\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/connection.php(160): OCA\\\\user_ldap\\\\lib\\\\Connection->establishConnection()\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/connection.php(168): OCA\\\\user_ldap\\\\lib\\\\Connection->init()\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/access.php(152): OCA\\\\user_ldap\\\\lib\\\\Connection->getConnectionResource()\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/user_ldap.php(180): OCA\\\\user_ldap\\\\lib\\\\Access->readAttribute('cn=kumar vijay,...', '')\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/user_ldap.php(215): OCA\\\\user_ldap\\\\USER_LDAP->userExistsOnLDAP(Object(OCA\\\\user_ldap\\\\lib\\\\user\\\\User))\\n#9 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/user_ldap.php(261): OCA\\\\user_ldap\\\\USER_LDAP->userExists('Kumar-Vijay')\\n#10 [internal function]: OCA\\\\user_ldap\\\\USER_LDAP->getHome('Kumar-Vijay')\\n#11 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/user_proxy.php(67): call_user_func_array(Array, Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/proxy.php(137): OCA\\\\user_ldap\\\\User_Proxy->walkBackends('Kumar-Vijay', 'getHome', Array)\\n#13 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/user_proxy.php(191): OCA\\\\user_ldap\\\\lib\\\\Proxy->handleRequest('Kumar-Vijay', 'getHome', Array)\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/user\\\/user.php(231): OCA\\\\user_ldap\\\\User_Proxy->getHome('Kumar-Vijay')\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/user.php(573): OC\\\\User\\\\User->getHome()\\n#16 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(378): OC_User::getHome('Kumar-Vijay')\\n#17 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(350): OC\\\\Files\\\\Filesystem::initMountPoints('Kumar-Vijay')\\n#18 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/util.php(190): OC\\\\Files\\\\Filesystem::init('Kumar-Vijay', '\\\/Kumar-Vijay\\\/fi...')\\n#19 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(873): OC_Util::setupFS()\\n#20 \\\/var\\\/www\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n#21 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/ldap.php\",\"Line\":289}","level":4,"time":"2015-09-26T11:34:00+00:00","method":"GET","url":"\/index.php\/apps\/files\/"}
![owncloud_error](https://cloud.githubusercontent.com/assets/10925174/10117358/c917049a-6471-11e5-856b-667c0577841a.jpg)

**Comment by Xenopathic** [comment]
Those logs are generated because ownCloud cannot connect to your LDAP server. Please make sure you are not having any network issues, and that the config is in order. cc @blizzz

**Comment by vijaykumar0690** [comment]
I do not have any network issues and when i reverted back to the previous version of Own Cloud. Owncloud 8.0.3 the login works for all users and i do not see any issue.
But when the upgrade to the new version 8.1.3 i faced the issue.
If you need any information please let me know so that i can share with you.

Regards,
Vijay

**Comment by ryantate13** [comment]
@vijaykumar0690 Did you wind up solving your issue? I am experiencing the same bug but with 9.1.
