### ISSUE TITLE
Federated sharing: Strange error when not putting in address

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#19382]
When putting in no address and pressing enter (or the confirm button), you get this strange error:
![federated-sharing-no-url-put](https://cloud.githubusercontent.com/assets/925062/10111548/ef16a342-6428-11e5-8bbc-261a37ddabbf.png)

When no URL is put in, nothing should happen (the button should be disabled). @schiesbn

**Comment by karlitschek** [comment]
@schiesbn Can we improve this?

**Comment by PVince81** [comment]
or @icewind1991 or @rullzer 

The part might be missing validation, it doesn't make sense to send the request if the field is empty.

**Comment by rullzer** [comment]
PR in #19421
