### ISSUE TITLE
Encryption issue after upgrading from 8.1.0 to 8.1.3

### ISSUE THREAD

**Issue by alichakery** [owncloud/core#19396]
### Expected behaviour
Successful Encryption keys migration 

### Actual behaviour
Users are not able to access their old files because the system is not able to decrypt the files using the migrated keys.

### Steps to reproduce
1. Upgrading the OCC Server from 1.8.0 to 1.8.3
2. Migrate the keys using SSH

### Server configuration
Operating system: CloudLinux

Web server:  LiteSpeed

Database: MardiaDB

PHP version: 5.4

ownCloud version: 8.1

Thank you

**Comment by RealRancor** [comment]
> Upgrading the OCC Server from 1.8.1 to 1.8.3

Probably "from 8.1.0 to 8.1.3"?

> Migrate the keys using SSH

Normally its not needed to migrate keys when updating from 8.1.0 to 8.1.3. Only when going from 8.0.8 to 8.1.3 for example. Can anyone explain that seen behavior?

**Comment by PVince81** [comment]
@schiesbn please assist

**Comment by alichakery** [comment]
Any ideas ?

**Comment by alichakery** [comment]
I restored the back up and went back to my previous version which is ownCloud 8.1.0 ... unfortunately it seems that no one here is able to help me .. even the main developers .... !!!

**Comment by schiesbn** [comment]
as said by @RealRancor nothing changes between 8.1.0 and 8.1.3 regarding key management.

What do you mean with "Migrate the keys using SSH"?

**Comment by alichakery** [comment]
I mean since the migration of encryption keys failed in Admin area so I migrated them using this command in SSH :
<addr>$ sudo -u www-data php occ encryption:migrate</addr>

**Comment by RealRancor** [comment]
@alichakery This command is only needed if you're upgrading from oC 8.0.x to 8.1.x. Not for minor updates like from 8.1.0 to 8.1.3.

Really wonder if your initial migration from 8.0.x to 8.1.0 was done successfully

**Comment by alichakery** [comment]
Yeah.. I restored my cPanel backup and it is working great... all files are accessible and there is no issues !!!
