### ISSUE TITLE
Allowed memory size of 262144 bytes exhausted

### ISSUE THREAD

**Issue by DominuS-RU** [owncloud/core#19393]
Hi! I'm having an error:
PHP Fatal error:  Allowed memory size of 262144 bytes exhausted (tried to allocate 49152 bytes) in /var/www/cloud/cron.php on line 156

I've tried to increase memory_limit in my php.ini, but it did't help me to solve this. How can I do it?
My current php_limit is 256M

small script 
<?php
echo ("memory limit: " . ini_get("memory_limit") . "<br />");
echo ("memory usage: " . round(memory_get_usage(true)/1048576,2) . "Mb (" . memory_get_usage(true) . " bytes)<br />");

gives me that results:
memory limit: 256M
memory usage: 0.25Mb (262144 bytes)

**Comment by RealRancor** [comment]
Hi,

as written in your older created issue https://github.com/owncloud/core/issues/19202 you need to raise the memory_limit in your php.ini. As the posted script is only checking the memory limit of your PHP running within your webserver and the error message is showing "cron" you have missed to correctly configure the php.ini of the PHP command line client.

Please close here and fix your configuration. If you have problems doing so please use the forums or the users mailinglist for such support questions.

**Comment by DominuS-RU** [comment]
I have tried to increase memory up to 2G with restart my php and nginx - nothing. I have tried to write memory in bytes - nothing. I have already checked my working php configuration with php_info - it's OK.

**Comment by RealRancor** [comment]
The config is not ok which is shown clearly in the posted error.
