### ISSUE TITLE
Bug? Error occurred while checking PostgreSQL version

### ISSUE THREAD

**Issue by geotheory** [owncloud/core#19391]
I'm trying to get Owncloud 8.1.3 running on Wheezy with PostgreSQL 9.1.18.  Running through the wizard to setup the database I'm getting the following error:

    Error occurred while checking PostgreSQL version
    Please make sure you have PostgreSQL >= 9 or check the logs for more information about the error

I've updated the config.php file with version, with no luck.  [This thread refers](https://forum.owncloud.org/viewtopic.php?f=31&t=30677&p=97620#p97620).  Checking the Postgres version with the same line ([from util.php?](https://github.com/owncloud/core/commit/a152f3a50fbae79c2fae98cf013aa71ca82174fb)) that appears to issue the error:

    postgres=# SHOW SERVER_VERSION;
     server_version
    ----------------
     9.1.18
    (1 row)

So I'm unclear why this error is being raised.  Grateful for assistance.

**Comment by PVince81** [comment]
Hmm... did PostgreSQL change the format of the response ?

**Comment by geotheory** [comment]
Any way I can test if that's the case? php not my thing, but if there's a script I can run..

**Comment by winpat** [comment]
I've the same problem using Debian Jessie and PostgreSQL 9.4.4

**Comment by sergioponfe** [comment]
Same problem here with postgresql 9.3.9. I had to use Mysql :-(

**Comment by PVince81** [comment]
You can comment out the version check, comment out this line https://github.com/owncloud/core/commit/a152f3a50fbae79c2fae98cf013aa71ca82174fb#diff-dd3121bfbeff46c08c30cb0666aa701eR491 as a workaround

**Comment by PVince81** [comment]
@icewind1991 IIRC you are using PostgreSQL, do you see this issue too ?

**Comment by icewind1991** [comment]
> do you see this issue too ?

no

@geotheory can you check the owncloud log for any db exceptions?

**Comment by geotheory** [comment]
@icewind1991, I went with MySQL in the end.  Next build I'll get the log if the problem reoccurs.

Thanks @PVince81 for the workaround.

**Comment by fabien-fac** [comment]
I have the same issue, any update about this ? I would like to use posgresql instead of mysql

**Comment by CannyFoxx** [comment]
I have same issue on fresh Debian Jessie (8).
PostgreSQL 9.4.5
PHP 5.6
Owncloud 8.2

**Comment by DrDanke** [comment]
Same issue here with PostgreSQL 9.4.5 and a fresh Debian 14.0.4

**Comment by icewind1991** [comment]
Maybe just assume the postgres version is correct if we cant check the version

cc @PVince81

**Comment by CannyFoxx** [comment]
Same issue on dev-version

**Comment by PVince81** [comment]
@icewind1991 yes, that would make sense

**Comment by icewind1991** [comment]
Fix is here: https://github.com/owncloud/core/pull/20524

**Comment by CannyFoxx** [comment]
After adding db user in psql console (used in postgresql, not system user) problem is solved.
