### ISSUE TITLE
dot isn't allowed in database names

### ISSUE THREAD

**Issue by n1trux** [owncloud/core#19390]
I tried to install owncloud 8.1 on my Debian host, but apparently it doesn't support dots in database names. Dots in usernames are fine.

Doesn't work: `oc.user`@`oc.database` (error: "Please match the requested format.")

Does work: `oc.user`@`ocdatabase`

It would be nice if you could fix this :)

**Comment by RealRancor** [comment]
Not quite sure but it seems its strongly discouraged to use dots in database names according to:

https://stackoverflow.com/questions/776123/does-mysql-allows-to-create-database-with-dot

**Comment by individual-it** [comment]
> Not quite sure but it seems its strongly discouraged to use dots in database names 
full ack + its only possible in MySQL >= 5.1.6
that's why :-1 for the idea of allowing dots or other funny characters in database/table names

**Comment by andrey-utkin** [comment]
>  for the idea of allowing dots or other funny characters in database/table names

**Provide mechanism, not policy.** Let user decide on his own. If error happens, you convey it to him.

> its only possible in MySQL >= 5.1.6

5.1.6 was released on 8 Feb 2006. Are you serious? Do you otherwise support such outdated web servers?

**Comment by PVince81** [comment]
Is there any validation code in OC that prevents using dots ?

@n1trux would be good to know what you mean with "isn't allowed". Is there an error message displayed ? Anything in the logs ?

**Comment by PVince81** [comment]
Closing due to lack of feedback. If there is requirement for this, feel free to submit a PR to fix it.
