### ISSUE TITLE
Federated cloud sharing requires case sensitive user names.

### ISSUE THREAD

**Issue by ftiede** [owncloud/core#19399]
### Steps to reproduce
1. Share a file with an all-lowercase user on a different owncloud-instance using a mixed-case username in sharing dialog.

This is more obviously when the user in question actually uses a mixed-case username and sharing is performed using all-lowercase.

### Expected behaviour
Regardless of case of characters, the shared file should show up in the target user's files app. At least after the target user changed apps for once.

### Actual behaviour
When the case of the username in the sharing dialog does not match the actual username's case, the share does not show up. It does so only after the username is written exactly as the registered username.

ownCloud is case-insensitive on logins - and I haven't tried whether or not, but doubt it, probably does not accept a username which matches another one except case, yet when using federated cloud sharing, usernames are case-sensitive.

The behaviour should at least be consistent, preferrably being case-insensitive on sharing.

### Server configuration
**Operating system:** Linux, 4.1 Kernel series.

**Web server:** Apache-2.4 on source instance, Nginx-1.8.0 on target instance.

**Database:** MariaDB-10.0.21

**PHP version:** 5.6.13

**ownCloud version:** 8.1.3

**Updated from an older ownCloud or fresh install:** Both updated, source instance has the full history from 4.5.7 through 8.1.3, target instance has started with 8.x series.

**Are you using external storage, if yes which one:** no

**Are you using encryption:** Source instance - no, target instance - yes.

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Seamonkey-2.3x as the source sharer, Firefox-38.x as the share recipient.

**Operating system:** Both on the same Linux system with 4.0 kernel series.

**Comment by PVince81** [comment]
@schiesbn @nickvergessen

**Comment by nickvergessen** [comment]
Uhh, I'd say this is a more general issue.
Basically all comparisons in all apps that are based on the uid rely on the casing of the currently given uid.

We could use LOWER = LOWER like on the login: https://github.com/owncloud/core/blob/d3ac73c0c9419750c65d3ccb8f0b0c25edacf34f/lib/private/user/database.php#L184-184
But I think we should fix this in another way, so apps don't need to care about the casing.
