### ISSUE TITLE
Old nightly/testing on SuSE-repo

### ISSUE THREAD

**Issue by tflidd** [owncloud/core#19397]
For debian 8, the source to be used (from owncloud.org) is:
http://download.opensuse.org/repositories/isv:/ownCloud:/community:/nightly/Debian_8.0/

But these "nightly" packages currently contain owncloud 8.1.1!

The testing branch contains OC 8.1.3:
http://download.opensuse.org/repositories/isv:/ownCloud:/community:/testing/Debian_8.0/

How is this supposed to work? Are the packages only build after the alpha/beta release of a version?

**Comment by PVince81** [comment]
@jnweiger

**Comment by Kawohl** [comment]
I cannot reproduce this. 
The right nightly build is from here:

OcVersion 8.2
Nightly:

https://software.opensuse.org/download/package?project=isv:ownCloud:community:nightly&package=owncloud

Please check your version.php /var/www/owncloud/version.php

The configuration of the testing repo seems to be wrong:
 my output 
```<?php 
$OC_Version = array(8,1,3,0);
$OC_VersionString = '8.1.3';
$OC_Edition = '';
$OC_Channel = 'stable';
$OC_Build = '2015-09-10T15:37:36+00:00 015323c1cb239ab242ff43183fd2edb8e3103025'; 
````



I assume you got your sources list wrong:

**Comment by tflidd** [comment]
Sorry, the normal apt-get update&upgrade didn't work and I haven't seen that the packet `owncloud` is not installed
````
 apt-cache policy owncloud
owncloud:
  Installed: (none)
  Candidate: 8.1-20150921
  Version table:
     8.1-20150921 0
        500 http://download.opensuse.org/repositories/isv:/ownCloud:/community:/nightly/Debian_7.0/  Packages
````
It has some unmet dependencies:
````
The following packages have unmet dependencies:
 owncloud : Depends: owncloud-server (= 8.1-20150921) but 8.1.1-1 is to be installed
            Depends: owncloud-config-apache (= 8.1-20150921) but it is not going to be installed
````
Removing the old packages (`owncloud-server`) and reinstalling owncloud solves the issue.

Now some 8.2 beta-version is installed (version.php):
````
$OC_Version = array(8,2,0,6);
$OC_VersionString = '8.2 beta1';
$OC_Channel = 'daily';
$OC_VersionCanBeUpgradedFrom = array(8,1);
$OC_Build = '2015-09-21T03:34:48+00:00 bbd1e996050fee80795d0e656da98b6451232c6c';
````

**Comment by jnweiger** [comment]
I've fixed things. There were new apps added, and existing apps removed, new files added.
All this needs specfile maintenance. Done.

**Comment by Kawohl** [comment]
Hmm i think we have the wrong link here, when i pull for debian 8 from https://software.opensuse.org/download/package?project=isv:ownCloud:community:testing&package=owncloud


i get this:

![bildschirmfoto 2015-09-29 um 09 43 50](https://cloud.githubusercontent.com/assets/12275313/10157989/26c8bed4-668f-11e5-85c0-9d59022684e1.png)

**Comment by jnweiger** [comment]
I've removed the old packages and placed a project link to isv:ownCloud:community:8.2:testing -- needs now a rebuild and publishing. https://build.opensuse.org/project/monitor/isv:ownCloud:community:testing

The setup of the unversioned community:testing repo is tricky as it mixes client and server package, coming from different repos.

**Comment by jnweiger** [comment]
The above changes should fix the issue.
