### ISSUE TITLE
Error message "failed to perform request for notifications" is shown sharing a file via link

### ISSUE THREAD

**Issue by davitol** [owncloud/core#19406]
### Steps to reproduce

1. Create a file
2. Share it via link
3. Paste the link in another browser

### Expected behaviour
The file should be shared

### Actual behaviour
An error message "failed to perform request for notifications" is shown

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** ownCloud Enterprise Edition 8.2 beta1 (daily) Build:2015-09-28T03:08:56+00:00 fe54d76e3dd047876847cebb63ed469c3273cf0a

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Firefox

![failedlink](https://cloud.githubusercontent.com/assets/10596560/10133911/d6d0f2a0-65e1-11e5-94a0-d62791ecbd75.png)

**Comment by PVince81** [comment]
No server logs?

**Comment by davitol** [comment]
@PVince81 Nothing related to this issue in the logs

**Comment by PVince81** [comment]
Searched the code and could not find this message anywhere.

@nickvergessen does this ring any bells ?

**Comment by nickvergessen** [comment]
The message is from the notifications app, but just says that an error occured.
But this makes me think, why is there a request when we are on the public.php?
Need to fix that :wink:

**Comment by nickvergessen** [comment]
Fix is here https://github.com/owncloud/notifications/issues/29
