### ISSUE TITLE
Invalid private key for Encryption App - 8.1.3(stable)

### ISSUE THREAD

**Issue by myjar** [owncloud/core#19410]
Just upgraded our server to ownCloud 8.1.3 (stable)

We are bound to an Active Directory, and have Server Side Encryption enabled.

Now, the problem we are getting is that when a user resets their AD password due to policy expiration, on next log in to the oc server, this message is displayed:

Invalid private key for Encryption App. Please update your private key password in your personal settings to recover access to your encrypted files.

Trying to perform this task:

Your private key password no longer matches your log-in password. 
Set your old private key password to your current log-in password:	
Old log-in password 
Current log-in password 

Results in the error: The current log-in password was not correct, please try again.

Users that have this error are no longer able to access any of their files on the server.

**Comment by karlitschek** [comment]
@schiesbn @blizzz any idea?

**Comment by schiesbn** [comment]
Thats's a known issue and will be fixed in 8.1.4 https://github.com/owncloud/core/pull/18747

Feel free to apply the patch to your installation to allow your users to reset the encryption key password

**Comment by schiesbn** [comment]
closed because the fix is already there and is waiting for release.

@myjar if you have some unexpected problems with the patch feel free to add your comment even if I close it for now.
