### ISSUE TITLE
How to re-upload everything over again (Global Reset)?

### ISSUE THREAD

**Issue by binarykitchen** [owncloud/core#19423]
Hello folks

Just wondering, is there a trick, a command, how I can tell my local Owncloud Client to wipe out everything on the server and to re-upload everything over again?

**Comment by RealRancor** [comment]
Looks to me that a question like this is better placed at the users mailinglist or the forums. The tracker here should be used for bugs or feature requests only.

**Comment by binarykitchen** [comment]
Ok, placed at https://forum.owncloud.org/viewtopic.php?f=31&t=30733

**Comment by binarykitchen** [comment]
@RealRancor can you please, pretty please, look at https://forum.owncloud.org/viewtopic.php?f=31&t=30733&p=97920#p97920 and give advice? Vielen Dank!
