### ISSUE TITLE
h2o HTTP2 webserver needs official support

### ISSUE THREAD

**Issue by HLFH** [owncloud/core#19429]
Hi,

I believe you should add official support to h2o HTTP2 webserver.

Thanks in advance,
HLFH

**Comment by LukasReschke** [comment]
Contributions welcome. Including documentation etc.

Not something we're aiming at right now from what I know.

**Comment by karlitschek** [comment]
@HLFH To officially support this we would need full testing and documentation and there seems to be at least one bug that needs to be fixed. We could label this officially supported once a volunteers does all this pieces.

**Comment by RealRancor** [comment]
At least the bug https://github.com/owncloud/core/issues/19428 is not related to this webserver as the headers are valid even if lowercase. Seems only the header check of oC needs to be fixed so it also is detecing those.

**Comment by HLFH** [comment]
@RealRancor I'm ok with you, the bug #19428 is more RFC-related than h2o-related. So, we just have to fix the header check of oC. What do you think @karlitschek?
