### ISSUE TITLE
h2o http2 headers bad warnings

### ISSUE THREAD

**Issue by HLFH** [owncloud/core#19428]
Hi,

I'm using [h2o webserver](https://github.com/h2o/h2o), because it is simply the best.
I got warnings on my ownCloud instance:

> L'en-tête HTTP "X-Content-Type-Options" n'est pas configurée pour être égale à "nosniff" créant potentiellement un risque relié à la sécurité et à la vie privée. Il est donc recommandé d'ajuster ce paramètre.
L'en-tête HTTP "X-Frame-Options" n'est pas configurée pour être égale à "SAMEORIGIN" créant potentiellement un risque relié à la sécurité et à la vie privée. Il est donc recommandé d'ajuster ce paramètre.

But when I'm using this http://www.webconfs.com/http-header-check.php, I saw this:

```bash
HTTP/1.1 301 Redirected => 
Date => Mon, 28 Sep 2015 21:07:46 GMT
Server => h2o/1.5.0-beta4
Connection => close
location => https://example.com/
content-type => text/html; charset=utf-8
x-powered-by => h2o
strict-transport-security => max-age=15768000; includeSubDomains; preload
public-key-pins => pin-sha256="mdNPwSGh8NF8XHwMIFbHfncrer8WE066L1PoVSzjd2E="; pin-sha256="DHKscLdFrBmZiBGxMdZiyaxp29vnyyPltRS1ZmTF09Y="; max-age=604800; includeSubDomains
x-frame-options => SAMEORIGIN
x-content-type-options => nosniff
```

So, the warnings does not seem to be right, my x-frame-options and x-content-type-options are in lowercase, I don't know if it's an issue, but it's [RFC-compatible](https://tools.ietf.org/html/rfc7230#section-3.2):

> Each header field consists of a case-insensitive field name followed
   by a colon (":"), optional leading whitespace, the field value, and
   optional trailing whitespace.

So, I don't understand why there is this warning showing up, if I have the right HTTP headers.

Thanks in advance,
HLFH

**Comment by LukasReschke** [comment]
> I'm using h2o webserver, because it is simply the best.

=> Please use the forum for further support. Not officially supported.

forum.owncloud.org

**Comment by HLFH** [comment]
...
