### ISSUE TITLE
Sharing errors are displayed as overlapping dialog boxes ... we have them inline in 8.1

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#19422]
![bildschirmfoto von 2015-09-28 21-58-39](https://cloud.githubusercontent.com/assets/1005065/10147075/39633672-662c-11e5-8e1d-6feb87077625.png)

@PVince81 @blizzz @jancborchardt THX

**Comment by PVince81** [comment]
Maybe these dialogs should actually be a tooltip appearing under the password field ?

**Comment by PVince81** [comment]
@DeepDiver1975 @cmonteroluque please evaluate severity

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 @cmonteroluque please evaluate severity

@cmonteroluque sev2 from my pov - we should not release 8.2 without this being fixed - THX

**Comment by PVince81** [comment]
Ok, let me have a look about making them a tooltip.

Any reason why this hasn't been done in the first place ? (I'm pretty sure @jancborchardt would have asked for either a tooltip or OC.Notification)

**Comment by DeepDiver1975** [comment]
in 8.1 the notification was not directly related to the popover and the user might not get the link between them.

With the side bar we have other options.

**Comment by PVince81** [comment]
@DeepDiver1975 what invalid characters were you using ? I tried chinese characters and "???" but they were accepted.

**Comment by DeepDiver1975** [comment]
@PVince81 you have to use the password policy app - https://github.com/owncloud/password_policy/pull/16

**Comment by PVince81** [comment]
Got it. Forgot to click "Save" since I have been trained to work without a "Save" button...

**Comment by PVince81** [comment]
Ah I see, it seems that a single error triggers the dialog twice.

**Comment by PVince81** [comment]
PR is here: https://github.com/owncloud/core/pull/19443

It actually sent the request twice due to having two jquery events.

**Comment by cmonteroluque** [comment]
@PVince81 @DeepDiver1975 thanks!
