### ISSUE TITLE
Fix the left side of the file comparator

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19438]
Since 8.1, it's not possible to get a preview of the uploaded file when using the Web GUI on Firefox.

### Approach 1

Add the `blob:` scheme to the CSP. I don't think this is going to happen. cc @LukasReschke 

### Approach 2

Fix the comparator so that it doesn't require `blob:`

* Stop using ObjectURL to load the data into a blob. I don't see the point of using an ObjectURL since the whole image is going to be loaded in memory anyway
* Use a better re-sampling algorithm

----

@icewind1991 @butonic @PVince81 @MorrisJobke @Xenopathic @rullzer @georgehrke

**Comment by LukasReschke** [comment]
> Add the blob: scheme to the CSP. I don't think this is going to happen. cc @LukasReschke

For images only? - `blob:` should be fine here. Will create a PR.

**Comment by oparoz** [comment]
Cool :). I can modify the one which adds `data:` so that it includes `blob:` as well.

**Comment by oparoz** [comment]
Ah, no, it's already merged :D

**Comment by LukasReschke** [comment]
There we go: https://github.com/owncloud/core/pull/19440
