### ISSUE TITLE
Fed. sharing via HTTPS, the files shared do not appear in server B

### ISSUE THREAD

**Issue by davitol** [owncloud/core#19434]
### Steps to reproduce

1. Fed Share a file from server A to server B via HTTPS (8.0.8 -> 8.2)
2. In server B accept the shared file

### Expected behaviour
The file should appear in server B

### Actual behaviour
The file is not shared

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** ownCloud Enterprise Edition 8.2 beta1 (daily) Build:2015-09-28T03:08:56+00:00 fe54d76e3dd047876847cebb63ed469c3273cf0a

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
{"reqId":"POauPTQESukldkfrKLBy","remoteAddr":"82.159.139.58","app":"core","message":"Exception while scanning storage \"shared::ebcf1eddef4c8e470f9a6b1367559062\": Sabre\\HTTP\\ClientException: SSL certificate problem: self signed certificate","level":3,"time":"2015-09-29T09:20:36+00:00"}

```
### Client configuration

**browser**
Firefox

**Comment by davitol** [comment]
Working on a 'share matrix' for each oc server version in order to clarify the behaviour between versions. ASAP i'll comment here the results

**Comment by LukasReschke** [comment]
> Sabre\\HTTP\\ClientException: SSL certificate problem: self signed certificate"

Well…

**Comment by LukasReschke** [comment]
Either get properly signed certificates or import the root certificate. - I don't see an issue in this.

**Comment by PVince81** [comment]
Related: https://github.com/owncloud/core/issues/18328 (showing a notification about the cert)

**Comment by davitol** [comment]
@PVince81 That's exactly my issue, so I'll close it becaouse mine is dupe of #18328

Thx for the info :wink:
