### ISSUE TITLE
Conflicts files sometimes created when saving without concurent modificiation

### ISSUE THREAD

**Issue by Zarus42** [owncloud/core#19435]
### Steps to reproduce
This is the easyet way I found to reproduce the issue, but happened with other file format and timing.
1. Open MS Word, create a new file and save it in an owncloud folder.
2. Open the file, modify it, and then save it.
3. Close MS Word.

### Expected behaviour
The file should be synchronized on the server.

### Actual behaviour
The file is not synchronized on the server and a conflict file is created which stores the modifications done in step 2.
The occurence of the issue is low for almost every users of the owncloud instance, it is high for one of them (can't find out what differs, I think it's the frequency of Ctrl+S that is more important...).

### Server configuration
**Operating system**:
CentOS 7.1

**Web server:**
Apache 2.4.6

**Database:**
MariaDB 5.5

**PHP version:**
PHP 5.4.16

**ownCloud version:** (see ownCloud admin page)
8.0.7 (from EPEL repository)

**Updated from an older ownCloud or fresh install:**
Updated with the yum package manager, don't known the initial version (installed with the package manager on July, 2015), but I had this issue also with the version 8.0.5.

**List of activated apps:**

Enabled:
 - files
 - files_external
 - files_pdfviewer
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - files_videoviewer
 - firstrunwizard
 - templateeditor
Disabled:
 - activity
 - external
 - files_encryption
 - files_locking
 - files_mv
 - gallery
 - provisioning_api
 - storagecharts2
 - user_external
 - user_ldap
 - user_webdavauth

**The content of config/config.php:**

$CONFIG = array (
  'log_type' => 'owncloud',
  'datadirectory' => '/home/owncloud/data',
  'updatechecker' => false,
  'check_for_working_htaccess' => false,
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/usr/share/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/lib/owncloud/apps',
      'url' => '/apps-appstore',
      'writable' => true,
    ),
  ),
  'instanceid' => 'xxxx',
  'passwordsalt' => 'xxxx',
  'secret' => 'xxxx',
  'trusted_domains' => 
  array (
    0 => 'xxx.xxx.xxx',
    1 => 'xx.xx.xx.xx',
  ),
  'overwrite.cli.url' => 'http://xxx.xxx.xxx/xxx',
  'dbtype' => 'mysql',
  'version' => '8.0.7.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxxx',
  'dbpassword' => 'xxxx',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => 2,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

**Network setup**
The owncloud server is accessed through a VPN (OpenVPN).

### Client configuration

**Operating system:**
Windows 7

#### Client log
24/09/2015 17:29:22Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mppVDX                        Non autorisé à envoyer ce fichier car il est en lecture seule sur le serveur. Restauration135 ko    

A conflict file is produced each time the message "Non autorisé à envoyer ce fichier car il est en lecture seule sur le serveur. Restauration" is displayed (translation for "Not allowed to upload this file because it is read-only on the server, restoring").
I've seen some messages in the activity tab saying that a stat command on some files failed but they disapear from the display when the error message is displayed.

#### Client log
I extracted lines where the file is referenced

09-24 17:29:08:377 0x8bdef8 OCC::FolderWatcher::changeDetected: detected changes in paths: QSet("C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp")
09-24 17:29:08:382 0x8bdef8 OCC::Folder::watcherSlot: void OCC::Folder::watcherSlot(QString) "C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" "Projets GLSI/PR.ABCDEF.001.001/02. Exigences" "Projets GLSI/PR.ABCDEF.001.001/02. Exigences/"
09-24 17:29:08:434 0x8bdef8 OCC::SocketApi::command_RETRIEVE_FILE_STATUS: void OCC::SocketApi::command_RETRIEVE_FILE_STATUS(const QString&, QIODevice*) "C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:08:435 0x8bdef8 OCC::SocketApi::fileStatus: OCC::SyncFileStatus OCC::SocketApi::fileStatus(OCC::Folder*, const QString&, c_strlist_t*) Could not determine state for file "Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" will set STATUS_NEW
09-24 17:29:08:435 0x8bdef8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:NEW:C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:10:456 0xbf83c68 csync_walker: file: C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp [inode=133036 size=134656]
09-24 17:29:10:456 0xbf83c68 _csync_detect_update: file: Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp, instruction: INSTRUCTION_NEW <<=
09-24 17:29:10:764 0x8bdef8 OCC::SocketApi::command_RETRIEVE_FILE_STATUS: void OCC::SocketApi::command_RETRIEVE_FILE_STATUS(const QString&, QIODevice*) "C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:10:765 0x8bdef8 OCC::SocketApi::fileStatus: OCC::SyncFileStatus OCC::SocketApi::fileStatus(OCC::Folder*, const QString&, c_strlist_t*) Could not determine state for file "Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" will set STATUS_NEW
09-24 17:29:10:766 0x8bdef8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:NEW:C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:11:598 0x8bdef8 _csync_merge_algorithm_visitor: INSTRUCTION_NEW      client file: Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp
09-24 17:29:11:683 0x8bdef8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:SYNC:C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:11:735 0x8bdef8 OCC::AbstractNetworkJob::start: !!! OCC::PUTFileJob created for "http://vpn.VDX.com/owncloud" + "/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp"
09-24 17:29:12:095 0x8bdef8 OCC::PropagateUploadFileQNAM::slotPutFinished: void OCC::PropagateUploadFileQNAM::slotPutFinished()  QUrl( "http://vpn.VDX.com/owncloud/remote.php/webdav/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" )  FINISHED WITH STATUS 0 "" QVariant(int, 201) QVariant(QString, "Created")
09-24 17:29:12:100 0x8bdef8 OCC::SyncJournalFileRecord::SyncJournalFileRecord: OCC::SyncJournalFileRecord::SyncJournalFileRecord(const OCC::SyncFileItem&, const QString&) "C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" Retrieved inode  133036 (previous item inode:  133036 )
09-24 17:29:12:102 0x8bdef8 OCC::SyncJournalDb::setFileRecord: "INSERT OR REPLACE INTO metadata (phash, pathlen, path, inode, uid, gid, mode, modtime, type, md5, fileid, remotePerm, filesize, ignoredChildrenRemote) VALUES (?1 , ?2, ?3 , ?4 , ?5 , ?6 , ?7,  ?8 , ?9 , ?10, ?11, ?12, ?13, ?14);" -7244578179408404302 104 "Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" 133036 0 "1443107496" "0" "6405a265d168125ceefa146a2826cb92" "00008032ocd72b0fe1a8" "" 134656 0
09-24 17:29:12:105 0x8bdef8 OCC::SyncJournalDb::setUploadInfo: "DELETE FROM uploadinfo WHERE path=?1" "Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp"
09-24 17:29:12:109 0x8bdef8 OCC::SyncEngine::slotItemCompleted: void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" INSTRUCTION_NEW 4 ""
09-24 17:29:12:112 0x8bdef8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK:C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:12:281 0x8bdef8 OCC::SocketApi::command_RETRIEVE_FILE_STATUS: void OCC::SocketApi::command_RETRIEVE_FILE_STATUS(const QString&, QIODevice*) "C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:12:283 0x8bdef8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK:C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:13:752 0x8bdef8 OCC::FolderWatcher::changeDetected: detected changes in paths: QSet("C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp")
09-24 17:29:13:755 0x8bdef8 OCC::Folder::watcherSlot: void OCC::Folder::watcherSlot(QString) "C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" "Projets GLSI/PR.ABCDEF.001.001/02. Exigences" "Projets GLSI/PR.ABCDEF.001.001/02. Exigences/"
09-24 17:29:13:895 0x8bdef8 OCC::SocketApi::command_RETRIEVE_FILE_STATUS: void OCC::SocketApi::command_RETRIEVE_FILE_STATUS(const QString&, QIODevice*) "C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:13:897 0x8bdef8 csync_vio_local_stat: CreateFileW failed on C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp
09-24 17:29:13:898 0x8bdef8 OCC::FileSystem::getModTime: Could not get modification time for "C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" with csync, using QFileInfo
09-24 17:29:13:898 0x8bdef8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK:C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:15:838 0xbf83948 csync_vio_local_stat: CreateFileW failed on C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp
09-24 17:29:15:838 0xbf83948 csync_ftw: Uniq ID from Database: Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp -> 6405a265d168125ceefa146a2826cb92
09-24 17:29:15:838 0xbf83948 _csync_detect_update: Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp excluded  (7)
09-24 17:29:15:838 0xbf83948 _csync_detect_update: file: Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp, instruction: INSTRUCTION_IGNORE <<=
09-24 17:29:16:143 0x8bdef8 OCC::SocketApi::command_RETRIEVE_FILE_STATUS: void OCC::SocketApi::command_RETRIEVE_FILE_STATUS(const QString&, QIODevice*) "C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:16:145 0x8bdef8 csync_vio_local_stat: CreateFileW failed on C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp
09-24 17:29:16:146 0x8bdef8 OCC::FileSystem::getModTime: Could not get modification time for "C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" with csync, using QFileInfo
09-24 17:29:16:147 0x8bdef8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK:C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:16:881 0xbf83948 csync_walker: file: owncloud://vpn.VDX.com/owncloud/remote.php/webdav/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp [file_id=00008032ocd72b0fe1a8 size=134656]
09-24 17:29:16:883 0xbf83948 _csync_detect_update: Need to update metadata for: Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp
09-24 17:29:16:883 0xbf83948 _csync_detect_update: file: Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp, instruction: INSTRUCTION_NONE <<=
09-24 17:29:16:968 0x8bdef8 _csync_merge_algorithm_visitor: INSTRUCTION_IGNORE   client file: Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp
09-24 17:29:17:029 0x8bdef8 _csync_merge_algorithm_visitor: INSTRUCTION_NONE     server file: Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp
09-24 17:29:17:053 0x8bdef8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:SYNC:C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:17:119 0x8bdef8 OCC::SyncEngine::slotItemCompleted: void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" INSTRUCTION_IGNORE 6 "Stat échoué."
09-24 17:29:17:120 0x8bdef8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:ERROR:C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:17:327 0x8bdef8 OCC::SocketApi::command_RETRIEVE_FILE_STATUS: void OCC::SocketApi::command_RETRIEVE_FILE_STATUS(const QString&, QIODevice*) "C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:17:329 0x8bdef8 csync_vio_local_stat: CreateFileW failed on C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp
09-24 17:29:17:329 0x8bdef8 OCC::FileSystem::getModTime: Could not get modification time for "C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" with csync, using QFileInfo
09-24 17:29:17:330 0x8bdef8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK:C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:19:618 0x8bdef8 OCC::FolderWatcher::changeDetected: detected changes in paths: QSet("C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp")
09-24 17:29:19:629 0x8bdef8 OCC::Folder::watcherSlot: void OCC::Folder::watcherSlot(QString) "C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" "Projets GLSI/PR.ABCDEF.001.001/02. Exigences" "Projets GLSI/PR.ABCDEF.001.001/02. Exigences/"
09-24 17:29:19:789 0x8bdef8 OCC::SocketApi::command_RETRIEVE_FILE_STATUS: void OCC::SocketApi::command_RETRIEVE_FILE_STATUS(const QString&, QIODevice*) "C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:19:790 0x8bdef8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:ERROR:C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:21:693 0xbf83768 csync_ftw: Uniq ID from Database: Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp -> 6405a265d168125ceefa146a2826cb92
09-24 17:29:21:693 0xbf83768 csync_walker: file: C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp [inode=133036 size=134656]
09-24 17:29:21:694 0xbf83768 _csync_detect_update: file: Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp, instruction: INSTRUCTION_EVAL <<=
09-24 17:29:21:992 0x8bdef8 OCC::SocketApi::command_RETRIEVE_FILE_STATUS: void OCC::SocketApi::command_RETRIEVE_FILE_STATUS(const QString&, QIODevice*) "C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:21:994 0x8bdef8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:ERROR:C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:22:228 0x8bdef8 _csync_merge_algorithm_visitor: INSTRUCTION_SYNC     client file: Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp
09-24 17:29:22:290 0x8bdef8 _csync_merge_algorithm_visitor: INSTRUCTION_NONE     server file: Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp
09-24 17:29:22:316 0x8bdef8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:SYNC:C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:22:320 0x8bdef8 OCC::SyncEngine::checkForPermission: checkForPermission: RESTORING "Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp"
09-24 17:29:22:366 0x8bdef8 OCC::PropagateDownloadFileQNAM::start: virtual void OCC::PropagateDownloadFileQNAM::start() "Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" 0
09-24 17:29:22:367 0x8bdef8 OCC::OwncloudPropagator::localFileNameClash: CaseClashCheck for  "C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp"
09-24 17:29:22:369 0x8bdef8 OCC::SyncJournalDb::setDownloadInfo: "INSERT OR REPLACE INTO downloadinfo (path, tmpfile, etag, errorcount) VALUES ( ?1 , ?2, ?3, ?4 )" "Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" "Projets GLSI/PR.ABCDEF.001.001/02. Exigences/.Planification ABCDEF.mpp.~669a" "6405a265d168125ceefa146a2826cb92" 0
09-24 17:29:22:371 0x8bdef8 OCC::AbstractNetworkJob::start: !!! OCC::GETFileJob created for "http://vpn.VDX.com/owncloud" + "/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp"
09-24 17:29:22:372 0x8bdef8 OCC::FolderWatcher::pathIsIgnored: * Discarded as is hidden! "C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/.Planification ABCDEF.mpp.~669a"
09-24 17:29:22:602 0x8bdef8 OCC::PropagateDownloadFileQNAM::slotGetFinished: void OCC::PropagateDownloadFileQNAM::slotGetFinished()  QUrl( "http://vpn.VDX.com/owncloud/remote.php/webdav/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" )  FINISHED WITH STATUS 0 "" 0 134656 134656 0 "" "134656"
09-24 17:29:22:606 0x8bdef8 OCC::OwncloudPropagator::localFileNameClash: CaseClashCheck for  "C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp"
09-24 17:29:22:612 0x8bdef8 OCC::PropagateDownloadFileQNAM::downloadFinished: Created conflict file "C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" -> "C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF_conflict-20150924-171136.mpp"
09-24 17:29:22:623 0x8bdef8 OCC::SyncJournalFileRecord::SyncJournalFileRecord: OCC::SyncJournalFileRecord::SyncJournalFileRecord(const OCC::SyncFileItem&, const QString&) "C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" Retrieved inode  78567 (previous item inode:  133036 )
09-24 17:29:22:626 0x8bdef8 OCC::SyncJournalDb::setFileRecord: "INSERT OR REPLACE INTO metadata (phash, pathlen, path, inode, uid, gid, mode, modtime, type, md5, fileid, remotePerm, filesize, ignoredChildrenRemote) VALUES (?1 , ?2, ?3 , ?4 , ?5 , ?6 , ?7,  ?8 , ?9 , ?10, ?11, ?12, ?13, ?14);" -7244578179408404302 104 "Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" 78567 0 "1443107496" "0" "6405a265d168125ceefa146a2826cb92" "00008032ocd72b0fe1a8" "RDNVCK" 134656 0
09-24 17:29:22:629 0x8bdef8 OCC::SyncJournalDb::setDownloadInfo: "DELETE FROM downloadinfo WHERE path=?1" "Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp"
09-24 17:29:22:633 0x8bdef8 OCC::SyncEngine::slotItemCompleted: void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" INSTRUCTION_CONFLICT 7 "Non autorisé à envoyer ce fichier car il est en lecture seule sur le serveur. Restauration"
09-24 17:29:22:635 0x8bdef8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:ERROR:C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:22:638 0x8bdef8 OCC::FolderWatcher::changeDetected: detected changes in paths: QSet("C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp")
09-24 17:29:22:638 0x8bdef8 OCC::Folder::watcherSlot: void OCC::Folder::watcherSlot(QString) Sync running, IGNORE event for  "C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp"
09-24 17:29:22:642 0x8bdef8 OCC::FolderWatcher::pathIsIgnored: * Discarded by component ignore pattern  ".Planification ABCDEF.mpp.~669a"
09-24 17:29:22:645 0x8bdef8 OCC::FolderWatcher::changeDetected: detected changes in paths: QSet("C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp")
09-24 17:29:22:645 0x8bdef8 OCC::Folder::watcherSlot: void OCC::Folder::watcherSlot(QString) Sync running, IGNORE event for  "C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp"
09-24 17:29:22:752 0x8bdef8 OCC::SocketApi::command_RETRIEVE_FILE_STATUS: void OCC::SocketApi::command_RETRIEVE_FILE_STATUS(const QString&, QIODevice*) "C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:22:753 0x8bdef8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK:C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"

#### ownCloud log (data/owncloud.log)
Time not related to other logs (was desactivated when the issue was reproduced), not sure errors are revelant.

Error	core	unable to rename, file does not exists : files_versions/Dossier personnel/Nouveau dossier.v	2015-09-29T07:50:02+00:00
Error	PHP	Undefined index: extension at /usr/share/owncloud/apps/files_versions/lib/storage.php#320	2015-09-29T07:50:02+00:00
Error	core	unable to rename, file does not exists : files_versions/Test.v	2015-09-29T07:27:59+00:00
Error	PHP	Undefined index: extension at /usr/share/owncloud/apps/files_versions/lib/storage.php#320	2015-09-29T07:27:59+00:00
Error	core	unable to rename, file does not exists : files_versions/Dossier personnel/Nouveau dossier.v	2015-09-29T07:21:23+00:00
Error	PHP	Undefined index: extension at /usr/share/owncloud/apps/files_versions/lib/storage.php#320	2015-09-29T07:21:23+00:00

**Comment by LukasReschke** [comment]
Can you please reopen at https://github.com/owncloud/client/issues?  - This seems like a client issue.

**Comment by Zarus42** [comment]
Ok, done : https://github.com/owncloud/client/issues/3901
