### ISSUE TITLE
Error sync filename ending with "space"

### ISSUE THREAD

**Issue by hmcs** [owncloud/core#19436]
Hi,

Via Web it is possible to create a directory-name with an ending space like "my folder " (Owncloud Server 8.1.3). 
The Windows-client (Version 2.0.1) has problems syncing this folder because spaces at begining or ending are not allowed in windows.  Nasty, it generates no error in log.

I assume, this apply also to files (not tested).

regards,

henry

**Comment by LukasReschke** [comment]
Please reopen at https://github.com/owncloud/client
