### ISSUE TITLE
Make keyboard navigation work with sidebar

### ISSUE THREAD

**Issue by schiessle** [owncloud/core#19442]
copied over from here https://github.com/owncloud/core/pull/19365#issuecomment-143188841

If you have multiple files you can use the key-up and key-down to navigate through the files and press enter to open them.  But with the sidebar open the sidebar doesn't update if I use the up/down keys to navigate through the files.

cc @PVince81

**Comment by PVince81** [comment]
I'll see what I can do.

**Comment by PVince81** [comment]
Oh noes, yet another highlight ?!!

I'll try and consolidate the keyboard highlight with the sidebar one. (ref https://github.com/owncloud/core/issues/18210#issuecomment-144061121)

**Comment by PVince81** [comment]
Keyboard shortcuts seem to be broken and don't behave as expected, especially when switching lists.
I'd like to move this to 9.0 because it will be a bigger change.

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/19445

**Comment by PVince81** [comment]
Closing in favor of general files app keyboard issue ticket: https://github.com/owncloud/core/issues/27580
