### ISSUE TITLE
SMB: unable to create pipe Too many open files

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#19444]
@icewind1991 

### Steps to reproduce
1. Have tons of pictures on an SMB share mounted in owncloud
2. Test the new ./occ command of https://github.com/owncloud/gallery/pull/387 to create ton´s of thumbnails
3. Let it run over all users and paths with ``sudo -u www-data ./occ gallery:create-thumbnails --all``

Note: this command, even currently as PR, is a good test to run ton´s of queries against SMB. The problem is not gallery related!

### Expected behaviour
Create all thumbs

### Actual behaviour
Stops after a while with continious errors: ``unable to create pipe Too many open files`` for each file accessed

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** nginx 1.9.5

**Database:** mysql 5.5.44

**PHP version:** 5.5.9

**ownCloud version:** 8.2 beta 1 git (cloned from master yesterday, 8.2.0.6)

**Updated from an older ownCloud or fresh install:** fresh

**List of activated apps:**

```
  - activity: 2.1.3
  - files: 1.1.11
  - files_external: 0.2.3
  - files_sharing: 0.6.3
  - files_trashbin: 0.6.3
  - files_versions: 1.0.6
  - gallery: 14.1.0
  - provisioning_api: 0.2
```

**The content of config/config.php:**

```
default config after installation
```

**Are you using external storage, if yes which one:** yes, SMB

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** none, using ssh

#### Web server error log
no errors corresponding to this issue

#### ownCloud log (data/owncloud.log)
```
Problem accessing /xxx/files/SMB/file-path.JPG
{"reqId":"xY97gdVFYGENI3dw8Ucx","remoteAddr":"","app":"PHP","message":"proc_open(): unable to create pipe Too many open files at \
/xxx\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/RawConnection.php#58","level":3,"time":"yyy"}
```

**Comment by DeepDiver1975** [comment]
looks like you are using smbclient - can you retry this with libsmbclient?

https://github.com/eduardok/libsmbclient-php

**Comment by RealRancor** [comment]
Also available in the OBS repo https://software.opensuse.org/download.html?project=isv%3AownCloud%3Acommunity%3A8.1&package=php5-libsmbclient

**Comment by icewind1991** [comment]
Do you have a stracktrace for that error?

**Comment by mmattel** [comment]
I have now installed libsmbclient and it run a lot longer BUT than it happened...
My filesystem got full and I wondered why. My finding was the following.

It was not the thumbs created...

My Ubuntu temp directory ``/tmp`` got filled up with pairs of files like:
````
      0 oc_tmp_ZqS2C7
2903252 oc_tmp_ZqS2C7-.JPG
````
and those files did not get removed automatically.

My SMB share contains >18700 pictures and the system stopped when the ``/tmp`` folder had >4300 files of that kind.

Now this is a mess. Not using libsmbclient I run into too many open files, using libsmbclinent I have not automatically deleted files in Ubuntu my temp space filling up the filesystem unnecessarily up to the point the filesystem system is full.

My expectation is, that this is not a problem of the ``./occ`` command itself but a handling of files underneath and of a general type. Means, that from my point of view critical for any system. The gallery PR is just highlighting this - but I may be wrong...

**Comment by icewind1991** [comment]
> and those files did not get removed automatically.

Most temp files get cleaned at the end of the "request" so a long running process like `occ` would cause issues there

**Comment by mmattel** [comment]
If I take an average of 3MB per file that is written to /tmp and 19K files to be processed, then I get the need of 57GB of temp space. I think that this is an issue because nobody will have a big temp space like that... :-1:  :unamused:
If the file is processed, it needs to get romoved from /tmp when done

**Comment by mmattel** [comment]
In addition, if you stop the ./occ process manually, you have tons of orphans remaining...

**Comment by mmattel** [comment]
Maybe one additional note regarding performance. When I kill the ./occ process and restart it, it compares if a thumbnail has already been created and walkes thru. I have found that this takes a long time (~0,8-0,9s per picture, remember 19K pictures in total) and the majority of the cpu time is used for mysql where I expect a query to be the cause, whatever this query is...

htop (found thumbnail)
![image](https://cloud.githubusercontent.com/assets/3321281/10175131/9970f0f6-66ed-11e5-951d-8aff05c090d7.png)

htop (creating thumbnail)
![image](https://cloud.githubusercontent.com/assets/3321281/10175660/88d3bdac-66f0-11e5-8d0a-8171bbf78677.png)

So if someone uses the ./occ thumbnail creation command on a big picture store, he currently runs in problems and it takes a long time. Pls keep in mind that this is not a gallery but a core problem.

**Comment by oparoz** [comment]
The first step is to scan the files and update the cache in order to make sure we generate thumbnails for working files, so that's the step which uses mysql a lot.

**Comment by DeepDiver1975** [comment]
More of an issue related to the thumbnail command in gallery?

**Comment by oparoz** [comment]
The fact that long running occ commands can't clean up the temp folder? Maybe, but other commands may be affected as well one day, although not many need to store data in temp.

The mysql load issue? No, but that's not related to SMB either, so could be opened as a separate issue about the Scanner class taking too much resources, if that's really a problem which can be solved because queries are inefficient.

But the `unable to create pipe Too many open files` seems to have been fixed by switching library, so this issue can probably be marked as solved.

@mmattel What do you think?

**Comment by mmattel** [comment]
I am in sorry that there are now three things in the same issue, they just came up at testing the new ./occ command.

1. An error is raised when using the icewind SMB library
2. After switching to libsmbclient tons of temp files are creates and fill up the filesystem instead beeing processed file by file and removed from /tmp after processing the file (currently after the job...)
To be checked if this would also have been taken place when using the icewind SMB library but the the error there was earlier compared to libsmbclient. Imho this is not library related but how owncloud handles files in ./occ comands, see the statement of @icewind above - but I maybe wrong
3. Long processing time during the check if a thumb has already been created. Here I think / ask if there is a performance improvement of the file handling (eg getId) possible.

**Comment by mmattel** [comment]
Following @oparoz suggestion, I state that the original issue problem: ``unable to create pipe Too many open files`` has been solved by using ``libsmbclient`` 

@icewind1991 maybe you want to look in more depth what may have caused the problem when using ``smbclient``.

I will open two seperate new issues which address performance and the exessive /tmp usage

**Comment by MorrisJobke** [comment]
> I will open two seperate new issues which address performance and the exessive /tmp usage

Then this issue here can be closed?

**Comment by mmattel** [comment]
If changing the library and not digging further into cause of the problem, yes

**Comment by PVince81** [comment]
`smbclient` is quite limited because it's basically a hack that use the CLI to run the process, this is not suitable for bigger installations anyway.

Closing.
