### ISSUE TITLE
Missing feedback when using "decrypt-all" command

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19456]
### Steps to reproduce

1. Encrypt all files using `occ encryption:encrypt-all`
2. Decrypt all files using `occ encryption:decrypt-all`

### Expected result

Decrypted files

### Actual result

> Please enter the recovery key password:

As no recovery password was ever set, the process fails

> [OC\Encryption\Exceptions\DecryptionFailedException]
  Encryption library: Decryption (symmetric) of content failed:

@schiesbn

**Comment by oparoz** [comment]
Ah, it's not an encryption issue, it's a command issue. It expects a user and when none given, it uses the recovery password.

I think there is some missing information in the dialogue.

Something like:

> No user given, using the master recovery key to decrypt all files stored in your ownCloud

**Comment by schiesbn** [comment]
> Ah, it's not an encryption issue, it's a command issue. It expects a user and when none is given, it uses the recovery password.

the "user" is optional. For a single user we provide both options, "user password" or "recovery key". But if you run the script for all users it is impractically to get each user at your desk and enter his password. Therefore this option only works with the recovery key.
