### ISSUE TITLE
File conflict dialog only shows one conflict after fresh page load

### ISSUE THREAD

**Issue by butonic** [owncloud/core#19464]
After a fresh page load, uploading multiple already existing files

![bildschirmfoto von 2015-09-30 09 52 35](https://cloud.githubusercontent.com/assets/956847/10187486/38ed6e46-6759-11e5-8963-01e8410f3258.png)

only shows the first one in the file comparison dialog.

![bildschirmfoto von 2015-09-30 09 50 50](https://cloud.githubusercontent.com/assets/956847/10187426/cf825e26-6758-11e5-8396-a0b81a134590.png)

Closing it with cancel or clicking continue without selecting anything and then uploading multiple existing files again shows correctly shows all conflicts:

![bildschirmfoto von 2015-09-30 09 51 53](https://cloud.githubusercontent.com/assets/956847/10187437/ec778092-6758-11e5-9eb2-50de84646581.png)

The same in IE11, chromium and iceweasel. Found while testing https://github.com/owncloud/core/pull/19449

**Comment by oparoz** [comment]
I experienced the same thing, but didn't investigate enough to discover that it was after a page reload.

**Comment by PVince81** [comment]
Please check if this https://github.com/owncloud/core/pull/19417 is the breaking PR

**Comment by PVince81** [comment]
Confirmed on master

**Comment by PVince81** [comment]
Looks like the fileexists dialog doesn't like being fed files one by one

**Comment by PVince81** [comment]
Ok, got it... the dialog template isn't loaded yet, but `addConflict` is trying to clone it.

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/core/pull/19521
