### ISSUE TITLE
It's not possible to download shared files by link after upgrade from 8.1.3 to 8.2

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#19465]
### Steps to reproduce
1. Install OC 8.1.3
2. Upload a file and share it by link
3. Upgrade to OC 8.2 (8.2 beta1 (daily) Build:2015-09-30T03:10:22+00:00 90810cc6052b38ac03dd8f08a200c5928a355d20)
4. Download the shared file using the shared link 

### Expected behaviour
Shared file is downloaded correctly

### Actual behaviour
It's possible to access the shared link and see the preview, but the download fails with a 404 error
Shared file: http://docker.oc.solidgear.es:52694/index.php/s/qpUJ7v1w1SEwQ3R
Download link: http://docker.oc.solidgear.es:52694/index.php/s/qpUJ7v1w1SEwQ3R/download

The file can be downloaded fine from the user account.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** 8.2 beta1 (daily) Build:2015-09-30T03:10:22+00:00 90810cc6052b38ac03dd8f08a200c5928a355d20

**Updated from an older ownCloud or fresh install:** updated from 8.1.3

### Notes
* Fresh install of 8.2 (same build) works as expected

**Comment by MorrisJobke** [comment]
Tested here with link created on stable8.1 (d6994b2) and upgraded to master (6760969). Link still works.

cc @schiesbn @PVince81

**Comment by PVince81** [comment]
Maybe it's only broken on "beta1"

**Comment by PVince81** [comment]
Hmm, I setup v8.1.3, created a link share then updated to "v8.2beta" but the link share still works.
This is with the CE version and with git.

@jvillafanez can you give more info about the file ? Is it inside a subfolder ? Is it a reshare ?

**Comment by jvillafanez** [comment]
It's a jpg image in the root folder. The preview of the file works fine, but I can't download it from the share link.

Feel free to use the links I've written in the issue

**Comment by PVince81** [comment]
I see the issue happening with your links, but cannot reproduce locally.
I tried setting up ownCloud enterprise 8.1.3, upload the picture, share with link, upgrade to ownCloud enterprise daily master complete. Link still works and download works too.

**Comment by PVince81** [comment]
@jvillafanez did you change any of the configs in the admin page or disabled apps, or it's all standard settings ?

**Comment by jvillafanez** [comment]
It's all the default settings

**Comment by LukasReschke** [comment]
Let me dig into this using SSH.

**Comment by jvillafanez** [comment]
The test I'm doing also shares the same file with another user before the upgrade. Maybe that's the piece left.

**Comment by LukasReschke** [comment]
```

Technical details
Remote Address: 31.10.133.244
Request ID: fSMwz4wQ3DY79eUScrJD
Type: Doctrine\DBAL\Exception\InvalidFieldNameException
Code: 0
Message: An exception occurred while executing 'INSERT INTO `activity` (`app`, `subject`, `subjectparams`, `message`, `messageparams`, `file`, `link`, `user`, `affecteduser`, `timestamp`, `priority`, `type`, `object_type`, `object_id`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["files_sharing", "public_shared_file_downloaded", "[\"\\\/google-logo.jpeg\"]", "", "[]", "\/google-logo.jpeg", "", null, "admin", 1443608721, 30, "public_links", "", 0]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'object_type' in 'field list'
File: /opt/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php
Line: 71

Trace
#0 /opt/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /opt/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO `ac...', Array)
#2 /opt/owncloud/lib/private/db/connection.php(203): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO `ac...', Array, Array)
#3 /opt/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(208): OC\DB\Connection->executeUpdate('INSERT INTO `*P...', Array, Array)
#4 /opt/owncloud/lib/private/db/querybuilder/querybuilder.php(121): Doctrine\DBAL\Query\QueryBuilder->execute()
#5 /opt/owncloud/apps/activity/lib/data.php(126): OC\DB\QueryBuilder\QueryBuilder->execute()
#6 /opt/owncloud/apps/activity/lib/consumer.php(74): OCA\Activity\Data->send(Object(OC\Activity\Event))
#7 /opt/owncloud/lib/private/activitymanager.php(183): OCA\Activity\Consumer->receive(Object(OC\Activity\Event))
#8 /opt/owncloud/lib/private/activitymanager.php(210): OC\ActivityManager->publish(Object(OC\Activity\Event))
#9 /opt/owncloud/apps/files_sharing/lib/controllers/sharecontroller.php(281): OC\ActivityManager->publishActivity('files_sharing', 'public_shared_f...', Array, '', Array, '/google-logo.jp...', '', 'admin', 'public_links', 30)
#10 [internal function]: OCA\Files_Sharing\Controllers\ShareController->downloadShare('ToPnrQlvw3Q4JV4', NULL, '')
#11 /opt/owncloud/lib/private/appframework/http/dispatcher.php(159): call_user_func_array(Array, Array)
#12 /opt/owncloud/lib/private/appframework/http/dispatcher.php(89): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Files_Sharing\Controllers\ShareController), 'downloadShare')
#13 /opt/owncloud/lib/private/appframework/app.php(108): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Files_Sharing\Controllers\ShareController), 'downloadShare')
#14 /opt/owncloud/lib/public/appframework/app.php(134): OC\AppFramework\App::main('ShareController', 'downloadShare', Object(OC\AppFramework\DependencyInjection\DIContainer))
#15 /opt/owncloud/core/routes.php(124): OCP\AppFramework\App->dispatch('ShareController', 'downloadShare')
#16 [internal function]: OC\Route\Router->{closure}(Array)
#17 /opt/owncloud/lib/private/route/router.php(281): call_user_func(Object(Closure), Array)
#18 /opt/owncloud/lib/base.php(829): OC\Route\Router->match('/s/ToPnrQlvw3Q4...')
#19 /opt/owncloud/index.php(40): OC::handleRequest()
#20 {main}
```

Activity is completely messed up. This throws an exception which the middleware converts into a 404.

cc @nickvergessen

**Comment by LukasReschke** [comment]
That said I will make the middleware log such exceptions as well as I had to hack it to get this now. - Let me see…

**Comment by LukasReschke** [comment]
https://github.com/owncloud/core/pull/19470 will not catch unrelated exceptions.

**Comment by nickvergessen** [comment]
Well to me that sounds like the activity app was not updated correctly.
The field was added in https://github.com/owncloud/activity/commit/0470887a2a75c018f67ed26574a35cc6bb3d2b28, the app version is also higher in 8.2 then in 8.1

@jvillafanez which version does the activity app tell you in it's info.xml file and in the database oc_appconfig

**Comment by nickvergessen** [comment]
@jvillafanez can you also make sure, that the activity app has no `appinfo/version` file?
The file was removed...

**Comment by jvillafanez** [comment]
It has the appinfo/version file. I uncompressed the tarball in the owncloud directory, so the file was there from the previous installation.

**Comment by nickvergessen** [comment]
Well delete it and enjoy the update.

Updating stuff should always be remove and then upload. Don't just overwrite and pray for magic to delete old files.

**Comment by MorrisJobke** [comment]
So not an issue anymore -> close?

**Comment by DeepDiver1975** [comment]
> So not an issue anymore -> close?

yes - performing proper upgrade is a prerequisite!

**Comment by jvillafanez** [comment]
All good now :+1:
