### ISSUE TITLE
Excessive temp space usage when running ./occ commands over many files

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#19469]
Followup of Issue #19444

### Steps to reproduce
1. Have tons of pictures on an SMB share mounted in owncloud
2. Test the new ./occ command of https://github.com/owncloud/gallery/pull/387 to create ton´s of thumbnails
3. Let it run over all users and paths with ``sudo -u www-data ./occ gallery:create-thumbnails --all``

Note: this command, even currently as PR, is a good test to run ton´s of queries against SMB. The problem is not gallery related!

### Expected behaviour
Create all thumbs where it does not fill up the temp space with files

### Actual behaviour
The filesystem gets filled up with tons of temporary files, because each temp file created will be deleted AFTER the complete ./occ job is done instead of clearing it after it has been processed. My system stopped working and I saw a 100% disk usage with df -h

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** nginx 1.9.5

**Database:** mysql 5.5.44

**PHP version:** 5.5.9

**ownCloud version:** 8.2 beta 1 git (cloned from master yesterday, 8.2.0.6)

**Updated from an older ownCloud or fresh install:** fresh

**List of activated apps:**

```
  - activity: 2.1.3
  - files: 1.1.11
  - files_external: 0.2.3
  - files_sharing: 0.6.3
  - files_trashbin: 0.6.3
  - files_versions: 1.0.6
  - gallery: 14.1.0
  - provisioning_api: 0.2
```

**The content of config/config.php:**

```
default config after installation
```

**Are you using external storage, if yes which one:** yes, SMB

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** none, using ssh

### Notes
My Ubuntu temp directory ``/tmp`` got filled up with pairs of files like:
````
      0 oc_tmp_ZqS2C7
2903252 oc_tmp_ZqS2C7-.JPG
````
and those files did not get removed automatically after they have been processed.

My SMB share contains >18700 pictures and the system stopped when the ``/tmp`` folder had >4300 files of that kind.

Because every second file has a 0 length and If I take an average of 3MB per file that is written to /tmp and 19K files to be processed, I get the need of 27GB of temp space. I think that this is a serious issue because nobody will have such a big temp space like that, the server stopped and needed manual intervention to get him up and running again...

In addition, if you stop the ./occ process manually, you have tons of orphans remaining in the temp space waiting for manual cleanup...

According an statement of @icewind1991 at the referenced issue #19444 
>
Most temp files get cleaned at the end of the "request" so a long running process like ``occ`` would cause issues there

**Comment by icewind1991** [comment]
Fix is here #19471
