### ISSUE TITLE
OC 8.1.3: SMB not working in "official" Click&Go VM

### ISSUE THREAD

**Issue by ounclowd** [owncloud/core#19479]
### Steps to reproduce
1. Downloaded the "official" OC8.1.3 Appliance (VMX) available at owncloud download page
2. Converted it into OVF and imported it into my vSphere5.
3. Started the VM, ran the final script and logged on Web-GUI as admin.
4. Activated the External-Storage-App

### Expected behaviour
Be able to add SMB/CIFS storage

### Actual behaviour
when I try to configure SMB/CIFS it states ```"smbclient" is not installed```

### Server configuration
**Operating system**:
Ubuntu 14.04.3
**Web server:**
Apache
**Database:**
MySQL
**PHP version:**

**ownCloud version:** (see ownCloud admin page)
8.1.3
**Updated from an older ownCloud or fresh install:**
fresh install (see "steps to reproduce")
**List of activated apps:**
Activity 2.0.2
Deleted files 0.6.3
External storage support 0.2.3
File Locking
First Run Wizard 1.1
LDAP user and group backend 0.6.1
Mail Template Editor 0.1
PDF Viewer 0.7
Pictures 0.6.0
Provisioning API 0.2
Proxy 0.1.5
Share Files 0.6.2
Text Editor 0.4
Updater 0.6
Versions 1.0.6
Video Viewer 0.1.3

**The content of config/config.php:**
```
<?php
$CONFIG = array (
  'instanceid' => 'oc9u9a0r0p6q',
  'passwordsalt' => '---',
  'secret' => '---',
  'trusted_domains' =>
  array (
    0 => 'localhost',
    1 => '192.168.1.69',
    2 => 'owncloud',
    3 => 'localhost',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'https://192.168.1.69/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.1.3.0',
  'dbname' => 'oc',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin',
  'dbpassword' => '---',
  'logtimezone' => 'UTC',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'ldapIgnoreNamingRules' => false,
);
```
**Are you using external storage, if yes which one:** local/smb/sftp/...
Would like to use SMB but doesn't work

**Are you using encryption:** yes/no
NO

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Will be using AD after SMB getting to work

### Client configuration
**Browser:**
IE10

**Operating system:**
Win7 Ent.

#### ownCloud log (data/owncloud.log)
```
{"reqId":"3CEqNT+4eWJVT0Aq8o1i","remoteAddr":"192.168.1.59","app":"core","message":"Login fail
ed: 'admin' (Remote IP: '192.168.1.59)","level":2,"time":"2015-09-30T12:46:22+00:00"}
{"reqId":"gB9spCNMnv6iQxSWktKj","remoteAddr":"192.168.1.59","app":"core","message":"Could not
get applications: cURL error 28: Resolving timed out after 5515 milliseconds","level":3,"time"
:"2015-09-30T13:19:25+00:00"}
```

**Comment by LukasReschke** [comment]
@jnweiger

**Comment by RealRancor** [comment]
@LukasReschke I'm not quite sure if this is packaging related. In the files_external app a check for the smbclient is done:

https://github.com/owncloud/core/blob/v8.1.3/apps/files_external/lib/smb.php#L297-L303

which is AFAIK not needed when using the new php5-libsmbclient.

**Comment by jnweiger** [comment]
Commit https://github.com/owncloud/vm/commit/e0ddcefc181b5ac77bd6869cf1ef6c2298db4aec now pulls in smbclient into the community vm. 
I consider this a workaround until the issue with files_external/lib/smb.php#L297-L303 is resolved.


My understanding is what @RealRancor assumed: smbclient should not be used at all. But I am not sure. Maybe we have code paths that use both smbclient and php5-libsmbclient?

**Comment by PVince81** [comment]
@icewind1991

**Comment by icewind1991** [comment]
We use php-libsmbclient when available and fallback to smbclient

**Comment by icewind1991** [comment]
Ignoring the (probably) outdated dependency check it *should* work without smbclient if libsmbclient is working but I've never tested it

**Comment by jdinkel** [comment]
Until this is fixed properly, it worked for me to just change /var/www/owncloud/apps/files_external/lib/smb.php, so that the line just reads "return true;" in the function at the end under " * check if smbclient is installed".

I have both the php5 libsmbclient and smbclient and cifs-utils installed, so I don't know if it works with just the php5 libsmbclient.

**Comment by jdinkel** [comment]
FYI Update on my previous comment - I uninstalled smbclient and cifs-utils, so only php5-libsmbclient was left installed and an smb external storage still works fine.  This is OwnCloud 8.2.2 on Debian 8.2.
