### ISSUE TITLE
Missing public version of Filesystem::normalizePath

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19472]
There is a normalizePath() in Node, but in case we receive a path from an event, we can't use it and there is a large difference in terms of what the 2 methods do.
#### Node

https://github.com/owncloud/core/blob/9883d5b85d8ae1e2d1d58b345c96a0563e112b97/lib/private/files/node/node.php#L283-L305
#### Filesystem

https://github.com/owncloud/core/blob/f70791653cefc40f640e48dcad489237b750d85c/lib/private/files/filesystem.php#L780-L850

---

@icewind1991 @LukasReschke @MorrisJobke @PVince81 @DeepDiver1975

**Comment by LukasReschke** [comment]
Mhm. Shouldn't we not just always pass around the normalized path? - I don't really think we should make this public.

**Comment by oparoz** [comment]
I did check to see if the events I was interested in were doing that, but then I thought that there might be other use cases for that function.
Maybe I should start with that?
