### ISSUE TITLE
Federated Cloud Sharing without Resharing

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/core#19477]
A user reported:

> We are trying to set up an owncloud installation for guest users. They should not have fully privileged accounts, but should be only allowed to receive shares via federated cloud sharing. Resharing via links or internal sharing shall not be allowed. Now I figured out that the users are only able to receive federated shared, if the flag "allow users, to share contents via link" (the second shown in the screenshot) is set. Otherwise, the notification that they received a new share does not appear. But this also allows the users to share links what we would like to deny.

> For me this seems like a bug. Is there a way to fix this?

![ihdfgbca](https://cloud.githubusercontent.com/assets/214010/10194676/543c2120-678a-11e5-8d55-e671789e7ca1.png)

### Server configuration

**ownCloud version:** (see ownCloud admin page)
8.1.3

**Updated from an older ownCloud or fresh install:**
fresh install

@MorrisJobke 

00003923

**Comment by MorrisJobke** [comment]
`/apps/files_sharing/api/externalShares` is available with following settings:

![bildschirmfoto von 2015-09-30 15-51-16](https://cloud.githubusercontent.com/assets/245432/10194856/3797e698-678b-11e5-8386-8714143d2c0a.png)

But it returns a 404 with following settings:

![bildschirmfoto von 2015-09-30 15-51-25](https://cloud.githubusercontent.com/assets/245432/10194867/40cf40a8-678b-11e5-9bee-0c3aeb745613.png)

@rullzer @schiesbn @PVince81 Any idea why? I can't find the code, that deactivates this route

**Comment by rullzer** [comment]
It is because of the middle ware https://github.com/owncloud/core/blob/master/apps/files_sharing/lib/middleware/sharingcheckmiddleware.php

More exactly: https://github.com/owncloud/core/blob/master/apps/files_sharing/lib/middleware/sharingcheckmiddleware.php#L106-L109

So we use the same middleware for the federated sharing stuff and for the link sharing stuff.
I'll look into it.

**Comment by rullzer** [comment]
Fix in #19487

**Comment by michaelstingl** [comment]
@rullzer @MorrisJobke Could this make it to 8.1.4 ?

**Comment by MorrisJobke** [comment]
> @rullzer @MorrisJobke Could this make it to 8.1.4 ?

We first need a fix for master. ;) It's even not 24h later and @rullzer working on this.

**Comment by MorrisJobke** [comment]
@michaelstingl This made it into 8.1.4 and 8.2.0

**Comment by michaelstingl** [comment]
@MorrisJobke @rullzer Thanks!
