### ISSUE TITLE
Missing logo on windows server 2008 + IE8

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#19474]
Very strange shit, the logo appears in Windows XP + IE8 and Windows 7 + IE8, but not in Windows Server 2008 + IE8.

It did in 8.1, so it's a regression.

Maybe Windows Server doesn't like the PNG format, or something...

@SergioBertolinSG @davitol FYI, raised this ticket to investigate further

**Comment by PVince81** [comment]
Observed here https://github.com/owncloud/core/pull/19451#issuecomment-144331296

**Comment by LukasReschke** [comment]
> Very strange shit, the logo appears in Windows XP + IE8 and Windows 7 + IE8, but not in Windows Server 2008 + IE8.

Well. Windows Server is not really thought for surfing. I would close this as won't fix :speak_no_evil:

**Comment by cmonteroluque** [comment]
This issue will fall off 8.2 if not resolved by 6 Oct

**Comment by MorrisJobke** [comment]
> Well. Windows Server is not really thought for surfing. I would close this as won't fix :speak_no_evil:

I have to agree here. 

cc @MTRichards is this okay?

**Comment by MTRichards** [comment]
Yes @MorrisJobke 
I am seeking an answer on this from customers on the need for IE 8 in general, but ok to drop IE8 on Windows 2008.

**Comment by MorrisJobke** [comment]
> I am seeking an answer on this from customers on the need for IE 8 in general, but ok to drop IE8 on Windows 2008.

It is not really a drop, but the header logo is missing.
