### ISSUE TITLE
PDF Preview not showing Embedded Images

### ISSUE THREAD

**Issue by mayarichman** [owncloud/core#19473]
I am running a server with ownCloud 8.1.3 (stable).

The embedded images in any PDF appears as a spinning ajax loader symbol in preview mode. An old OC thread mentioned it could be due to PHP memory limits, but I've got my memory limit set to 512MB in the local .htaccess. 

It could be the same issue as owncloud/core#18917

Old OC support: https://forum.owncloud.org/viewtopic.php?f=23&t=17760

**Comment by karlitschek** [comment]
probably a limit of the used pdf.js library

**Comment by mayarichman** [comment]
You can [add some lines](https://github.com/owncloud/files_pdfviewer/commit/0c4f142a3e79d408b15797b60dada9ec1734fe25) to the pdf viewer app, restart your server and it works in Chrome. FF is still not working.
