### ISSUE TITLE
Remaining Zero Byte Temp Files

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#19486]
@icewind1991, @oparoz; @DeepDiver1975 

I know, irritating stuff...

After merging of #19471 (Clean temp files used for thumbnail generation), I do not get temp files of a size > 0 in the temp folder anymore... :+1: 

But there are still 0 (zero) byte files of the style ``oc_tmp_xxxxxx`` created **which are not deleted**.
During this writing, the ./occ process is running and the filecount is at >3800 counting upwards.

There seems to be someting in the process which whyever creates this files but does not delete it... Keep in mind, that before #19471 we had a second file with the same name plus an dash and an extension (in my case .JPG, eg ``oc_tmp_ZqS2C7-.JPG``) and a size >0 which is now removed automatically.

**Comment by icewind1991** [comment]
Hard to fix without knowing what creates the temp files

**Comment by mmattel** [comment]
That is true, but it must be something close to that process that creates a temp file having (more or less) the same name but has the extension .JPG
````
      0 oc_tmp_ZqS2C7        open
2903252 oc_tmp_ZqS2C7-.JPG   fixed with #19471
````
Adding @oparoz

**Comment by oparoz** [comment]
I wonder why there is the dash at the end of the filename. That could be the source of the problem. 2 temp files with different names and only one of them removed at the end of an operation.

It must come from the part which copies the file over from the external storage for further processing.

**Comment by PVince81** [comment]
Please try again with 9.0 RC1. If it still happens, reopen.
