### ISSUE TITLE
Mounting an external folder doesn't removes the red borders when it is correctly mounted.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#19491]
### Steps to reproduce
1. Enable external storage.
2. Mount correctly a S3 folder. (For example, I've seen the problem with other storages as well)
3. See the borders of the textboxes.
### Expected behaviour

Black borders.
### Actual behaviour

Red borders.

![screen shot 2015-10-01 at 09 45 29](https://cloud.githubusercontent.com/assets/9048796/10215608/5fd2f9ca-6823-11e5-9126-8dddb15844c8.png)
### Server configuration

**Operating system**:
Cent OS 6.6

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.4

**ownCloud version:** (see ownCloud admin page)
Using enterprise theme.
{"installed":true,"maintenance":false,"version":"8.2.0.6","versionstring":"8.2 beta1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition.
+
External storage

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes, S3

**Are you using encryption:** 
No

**Comment by SergioBertolinSG** [comment]
Still happening. (9.0)

**Comment by PVince81** [comment]
I think I've seen this working correctly, recently. Please reopen if still happening in 10.0.4.
