### ISSUE TITLE
Sync client fails for larger files

### ISSUE THREAD

**Issue by Kulaki** [owncloud/core#19490]
Sync client fails for larger files. Smaller files sync with no error.
Client error message: Connection Lost

Please see log below:

Thanks,

Exception: {"Message":"HTTP\/1.1 400 expected filesize 5242880 got 147456","Code":0,"Trace":"#0 \/var\/www\/html\/owncloud\/lib\/private\/connector\/sabre\/file.php(100): OC\\Connector\\Sabre\\File->createFileChunked(Resource id #266)\n#1 \/var\/www\/html\/owncloud\/lib\/private\/connector\/sabre\/directory.php(113): OC\\Connector\\Sabre\\File->put(Resource id #266)\n#2 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1053): OC\\Connector\\Sabre\\Directory->createFile('LibreOffice_5.0...', Resource id #266)\n#3 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(513): Sabre\\DAV\\Server->createFile('LibreOffice_5.0...', Resource id #266, NULL)\n#4 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#6 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#7 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#8 \/var\/www\/html\/owncloud\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n#9 \/var\/www\/html\/owncloud\/remote.php(132): require_once('\/var\/www\/html\/o...')\n#10 {main}","File":"\/var\/www\/html\/owncloud\/lib\/private\/connector\/sabre\/file.php","Line":346}

Version
ownCloud 8.1.3 (stable)
on CentOS release 6.7 (Final)

**Comment by Kawohl** [comment]
@Kulaki 

Please move this issue to https://github.com/owncloud/client/issues
and use the issue template https://github.com/owncloud/client/blob/master/issue_template.md

**Comment by RealRancor** [comment]
Could be possible that this is already discussed here: https://github.com/owncloud/client/issues/3816
