### ISSUE TITLE
Restore file breaks file list

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#19495]
If you have multiple files in the trash bin and restore one of it you will get following result:

![1](https://cloud.githubusercontent.com/assets/1589737/10217242/d72d1b8a-682e-11e5-8caf-ba4a5a80da37.png)

@PVince81 probably some JavaScript magic needed, can you have a look? Thanks!

cc @jancborchardt

**Comment by schiesbn** [comment]
Tagged as medium for now because nothing breaks, the file list just look ugly after restore. Still something we want to fix most likely for 8.2

**Comment by PVince81** [comment]
I see there's `enableActions()` in the trashbin file list. It is supposed to hide the checkboxes during operation and show them again. Since the checkbox DOM elements changed, it is restoring the wrong checkboxes. @Henni

**Comment by PVince81** [comment]
https://github.com/owncloud/core/blob/master/apps/files_trashbin/js/filelist.js#L270

**Comment by cmonteroluque** [comment]
This issue will fall off 8.2 if not resolved by 6 Oct
