### ISSUE TITLE
Sidebar doesn't update correctly on version restore

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#19498]
Move this to a separate issue:  https://github.com/owncloud/core/issues/19403#issuecomment-144668831

Steps to reproduce:

1. create a file with multiple versions
2. open the sidebar and go to versions
3. restore a version

Expected Result:

The version you restored should disappear from the sidebar instead the new version, created during restore, should show up

Actual Result:

The new version gets added but the restored version doesn't get removed

cc @PVince81

**Comment by PVince81** [comment]
Indeed broken

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/19499
