### ISSUE TITLE
bug on isInternetConnectionWorking()

### ISSUE THREAD

**Issue by zaclys** [owncloud/core#19509]
Hi friends,

here is a new bug we found in ownCloud v8 :

Bug on isInternetConnectionWorking() :

On settings/controller/checksetupcontroller.php  line 86 : $client->get('https://www.owncloud.org/');

This call returns an error because https://www.owncloud.org/ returns an 301 or 302 url redirect code !

So the function isInternetConnectionWorking() returns an error on the admin back office and displays "This server has no working Internet connection" message.

This bug is present on all ownCloud v8 tested (the last one also)

This may help also for other issues we found reported here.

Best regards,
Mother Zaclys

**Comment by RealRancor** [comment]
Probably just related to the buggy NSS/OpenSSL versions used by your curl as described here:

https://doc.owncloud.org/server/8.1/admin_manual/configuration_server/security_setup_warnings.html#outdated-nss-openssl-version

**Comment by LukasReschke** [comment]
Very likely related yes. - The redirect is there for a reason :)

**Comment by zaclys** [comment]
no, curl and openssl are ok on our owncloud server

I think's it's because the website https://www.owncloud.org redirect to https://owncloud.org since some months , test it with your navigator : https://www.owncloud.org


to fix it , on settings/controller/checksetupcontroller.php  line 86 :

juste change :
$client->get('https://www.owncloud.org/');

by the real final url :
$client->get('https://owncloud.org/');

and it works

(the web site https://owncloud.org return the 200 http code as expected but https://www.owncloud.org return 301 http code , not expected  ...  )

**Comment by LukasReschke** [comment]
> I think's it's because the website https://www.owncloud.org redirect to https://owncloud.org since some months , test it with your navigator : https://www.owncloud.org

This is completely expected. Please post a screenshot of your setup warnings.

**Comment by RealRancor** [comment]
@LukasReschke Can't find the curl.php test script to test that outside from oC which you had posted in the past. I think that could easily show where this issue is coming from.

**Comment by LukasReschke** [comment]
https://github.com/owncloud/core/issues/16255#issuecomment-112481294

**Comment by zaclys** [comment]
@Lukas : ok , I see :  in some cases the bugged curl library returns 400 error http code, not 301 redirect http code as I think !

As explained here  :
https://bugzilla.redhat.com/show_bug.cgi?id=1241172

I understand, but we are on Centos 7 last release with all libs updated ... no solution for us at this time, just to ignore this warn message because only app manager is impacted.


PS : the only warn message on our admin panel is "This server has no working Internet connection ... " , no message  about curl php nor nss version

Tested on :
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.15.4 zlib/1.2.7 libidn/1.28 libssh2/1.4.3

and :
curl 7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.19.1 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2

**Comment by LukasReschke** [comment]
> I understand, but we are on Centos 7 last release with all libs updated ... no solution for us at this time, just to ignore this warn message because only app manager is impacted.

Correct. - No solution until CentOS updates their packages.

> PS : the only warn message on our admin panel is "This server has no working Internet connection ... " , no message about curl php nor nss version

Can you post your ownCloud config?

**Comment by RealRancor** [comment]
Probably just not on oC 8.1 but on oC 8.0?

**Comment by LukasReschke** [comment]
> Probably just not on oC 8.1 but on oC 8.0?

So true…

Closing this then. 8.1 should display a proper warning. I don't think this is feasible backporting considering that the whole stuff got refactored.
