### ISSUE TITLE
Details view is unuseful for deleted files

### ISSUE THREAD

**Issue by davitol** [owncloud/core#19506]
### Steps to reproduce

1. Delete a file
2. Go to the trashbin
3. Click on details of the file deleted

### Expected behaviour
Details view makes nonsense for deleted files or previous activities should be shown

### Actual behaviour
Details view is available and shows the sidebar

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** ownCloud Enterprise Edition 8.2 beta1 (daily) Build:2015-10-01T03:09:06+00:00 d6e3195b38d8285c12a1fa4a23f8498e5122f4fe

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Firefox

**Comment by PVince81** [comment]
It seems the activity app isn't able to retrieve activities for deleted files, it might be on purpose @nickvergessen ?

Regardless of activities, the sidebar can also show the bigger thumbnail, which can be useful too.

**Comment by nickvergessen** [comment]
Activity sidebar is empt, because the file id is not send in the request, will have a closer look

**Comment by nickvergessen** [comment]
`data-id="0"` is empty in the trashbin

**Comment by PVince81** [comment]
Okay, I'll have a look then

**Comment by PVince81** [comment]
Looks like we don't have access to the file id because the trashbin contents is read directly from the disk... it would require additional database queries to find the matching file id. (CC @schiesbn)

**Comment by PVince81** [comment]
Ok, let's go the other route: remove the sidebar in the trashbin and then invest a bit of time later to make it useful.

**Comment by PVince81** [comment]
PR is here https://github.com/owncloud/core/pull/19647

**Comment by PVince81** [comment]
Raised https://github.com/owncloud/core/issues/19649 to look into the data-id / activities at some point
