### ISSUE TITLE
Wrong credentials results in server 500 HTTP status code

### ISSUE THREAD

**Issue by David-Development** [owncloud/core#19504]
If I connect with wrong credentials to the news app api, the response is a 500 Server Error. At least the http status code should be 403. @BernhardPosselt told me, that this is an issue in the core.
With the current return code I'm not able to show my users a proper message that their password is wrong. More information on this issue: https://github.com/owncloud/news/issues/864

As you can see in the issue in the news repo the owncloud.log says something like:
\"Message\":\"CORS requires basic auth\"

**Comment by BernhardPosselt** [comment]
https://github.com/owncloud/core/blob/master/lib/private/appframework/middleware/security/corsmiddleware.php#L81

Ok, seems that this message is also sent if the basic auth login fails, 403 should be returned though, the message should be enhanced 

@LukasReschke

**Comment by David-Development** [comment]
Any news on this issue? Would be nice if it can be fixed in the next release. Thanks guys!

**Comment by PVince81** [comment]
Apps need to use one of the main login endpoints instead: https://github.com/owncloud/core/issues/27588
