### ISSUE TITLE
[Personal Settings] NetworkError: 404 Not Found - loading personal settings page

### ISSUE THREAD

**Issue by davitol** [owncloud/core#19502]
### Steps to reproduce

1. Go to personal page

### Expected behaviour
The personal page should be load without throwing errors

### Actual behaviour
"NetworkError: 404 Not Found - when loading personal page

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** ownCloud Enterprise Edition 8.2 beta1 (daily) Build:2015-10-01T03:09:06+00:00 d6e3195b38d8285c12a1fa4a23f8498e5122f4fe

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Firefox

![screen shot 2015-10-01 at 12 35 06](https://cloud.githubusercontent.com/assets/10596560/10218963/511d6aba-683b-11e5-953a-2a9fee9e5298.png)

**Comment by karlitschek** [comment]
@nickvergessen Can you have a look?

**Comment by nickvergessen** [comment]
Everything okay here, the 404 is expected when there are no notifying apps available.

However since this is the second report about this, I will use another status code.
