### ISSUE TITLE
Restoring versions creates fake versions which are only removed after refreshing.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#19528]
### Steps to reproduce

1. Create a text file
2. Modify it.
3. Open versions in the sidebar.
4. Restore first version.
5. Restore to the second version again.

### Expected behaviour
There should be only 1 version in the list.

### Actual behaviour
A new fake version is created with each restore.

![screen shot 2015-10-02 at 12 42 22](https://cloud.githubusercontent.com/assets/9048796/10244991/c549d752-6903-11e5-8e58-7276129cfaec.png)

![screen shot 2015-10-02 at 12 42 37](https://cloud.githubusercontent.com/assets/9048796/10244994/caf2f9ae-6903-11e5-9de0-90058b5c99b9.png)

![screen shot 2015-10-02 at 12 42 49](https://cloud.githubusercontent.com/assets/9048796/10245004/d102accc-6903-11e5-860e-9ba4c66d46d1.png)

### Server configuration
**Operating system**:
Cent OS 6.6

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.4

**ownCloud version:** (see ownCloud admin page)
Using enterprise theme.
{"installed":true,"maintenance":false,"version":"8.2.0.6","versionstring":"8.2 beta1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition.
+
External storage

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes, S3, SMB and Dropbox, but not related with test.

**Are you using encryption:** 
No

**Comment by PVince81** [comment]
@SergioBertolinSG please try again on master, it seems to found this just before https://github.com/owncloud/core/pull/19499 got merged

**Comment by SergioBertolinSG** [comment]
Works fine in master now.
