### ISSUE TITLE
Device/Session registry

### ISSUE THREAD

**Issue by danimo** [owncloud/core#19529]
## Purpose

The device registry would keep track of devices that connect to ownCloud (e.g. mobile clients, desktop clients) and stores a unique ID of the device. It can also be used to identify current browser sessions.

## Possible use cases

* per-device authentication tokens (login with normal credentials once to fetch a token which is only authorized to do a subset of actions (e.g. webdav only access), limited to a particular device
* Targetted remote wipe
* Device statistics
* Log out remote browser sessions

(This is mostly based from an old proposal that I made in 5.0 times and that I didn't want to get lost. It  could fit neatly e.g. with #10400. This also solves the remote wipe issue.)

## Stories implemented

* As an administrator, I want to be able to control/view permanently syncing devices and wipe them
* As a user, I do not want to reauthenticate permanently syncing services only because my user password changed.
* As a user I want to see which devices sync my stuff and when they did the last time, similar to https://github.com/settings/tokens
* As a user, I want to be able to log out stale browser sessions that I might have forgotten to properly close down.

/cc @MTRichards @cml @karlitschek

**Comment by nickvergessen** [comment]
Other story implemented
* As a user I want to see which devices sync my stuff and when they did the last time

**Comment by MorrisJobke** [comment]
> non-browser devices

I would also do this for browsers. This would enhance the security because we can "remote logout a browser session".

**Comment by karlitschek** [comment]
good idea. Something for the future :-)

**Comment by danimo** [comment]
@nickvergessen @MorrisJobke : Added, thanks!

**Comment by DeepDiver1975** [comment]
this will allow us to invalidate sessions on password change #18410

**Comment by MTRichards** [comment]
> This also solves the remote wipe issue.

Yep, good stuff. I have had it in the backlog for a while, just need to move some stuff off the plate to get this on the plate. Or get a second plate.

**Comment by guruz** [comment]
We were thinking of sending something like the locally set hostname (e.g. "Markus-MacBookPro") inside the user agent for logging purposes ([client issue](https://github.com/owncloud/client/issues/4606)). 
Now I'm thinking we could also send this in a HTTP header and it then gets saved into this registry.

Maybe this is also something that can be reused inside the activity log (@nickvergessen @dragotin)

**Comment by ChristophWurst** [comment]
This is what I added with pluggable auth, isn't it?
ref #24189

**Comment by guruz** [comment]
@ChristophWurst Yep indeed looks like it :)

I'm wondering: The table ```authtoken``` has ```name``` which is for the User-Agent. How would we put in a user defined description? 
E.g. "Markus' MacBook" or 'Christop's Android" or whatever.
Hm, maybe something for later.

Please feel free to assign this yourself and close it.

(If @danimo does not disagree)

**Comment by ChristophWurst** [comment]
@guruz the ``name`` attribute is used for the user agent of browser session tokens and for the device name of device tokens. You can already create a device token called "Markus' MacBook" in the personal settings or via the ``/token/generate`` route: https://github.com/owncloud/core/blob/c0a91ddca797c9821d3ce8771664b17ee588535f/core/Controller/TokenController.php#L60-L88
