### ISSUE TITLE
Sharee cannot open shared file from an external storage (SMB) using encryption.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#19532]
### Steps to reproduce

1. Mount SMB folder.
2. Enable encryption.
3. As admin logout and login.
4. As admin create a text file 'textfile.txt' inside the SMB folder.
5. As admin share it with 'user2'.
6. Login with 'user2' try to open 'textfile.txt'.

### Expected behaviour
Sharee can open the file without problems.

### Actual behaviour
500 error. Sharee is unable to open it.

### Server configuration
**Operating system**:
Cent OS 6.6

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.4

**ownCloud version:** (see ownCloud admin page)
Using enterprise theme.
{"installed":true,"maintenance":false,"version":"8.2.0.6","versionstring":"8.2 beta1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition.
External storage
Encryption default module.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes, SMB.

**Are you using encryption:** 
Yes.

**Server Logs**
```
with \"OC\\Preview\\TXT\"","level":0,"time":"2015-10-02T11:45:20+00:00","method":"GET","url":"\/index.php\/core\/preview.png?file=%2Ffichero.txt.txt&c=412&x=32&y=32&forceIcon=0"}
{"reqId":"MQdsqXr4QCHHFN2PTktc","remoteAddr":"HIDED_IP","app":"admin_audit","message":"Read \"\/user3\/files\/fichero.txt.txt\" by user user3, owner: admin [CLIENT_IP: HIDED_IP]","level":1,"time":"2015-10-02T11:45:20+00:00","method":"GET","url":"\/index.php\/core\/preview.png?file=%2Ffichero.txt.txt&c=412&x=32&y=32&forceIcon=0"}
{"reqId":"MQdsqXr4QCHHFN2PTktc","remoteAddr":"HIDED_IP","app":"no app in context","message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","level":
```

**Comment by SergioBertolinSG** [comment]
@schiesbn

**Comment by schiesbn** [comment]
how do you mounted the smb folder? System wide in the admin settings or for a specific user in the personal settings?

**Comment by DeepDiver1975** [comment]
> 500 error. Sharee is unable to open it.

there has to be an error message in the logs - please have a look and provide - THX

**Comment by SergioBertolinSG** [comment]
> how do you mounted the smb folder? System wide in the admin settings or for a specific user in the personal settings?

System wide in admin settings.

**Comment by SergioBertolinSG** [comment]
Added logs.

**Comment by DeepDiver1975** [comment]
> Added logs.

THX

**Comment by schiesbn** [comment]
> Added logs.

Where did you added the logs? Can't see them...


... I will try to re-produce it.

**Comment by DeepDiver1975** [comment]
> Where did you added the logs? Can't see them...

@schiesbn in the description

**Comment by schiesbn** [comment]
OK, we don't detect the system wide mount point. Seems like something changed here. In the past the array $mount['applicable']['users'] contained "all" if no specific user/group was defined. Will investigate...

**Comment by DeepDiver1975** [comment]
> In the past the array $mount['applicable']['users'] contained "all" if no specific user/group was defined.

sounds like a regression - sev1?

**Comment by schiesbn** [comment]
> sounds like a regression - sev1?

yes, I also searched the code for 'all' and it seems like there are still some places where we rely on it. Encryption is probably not the only thing which fails, just the first app we saw it.

````
$ grep -ir "'all'" apps/files_external/*
apps/files_external/js/settings.js:				if (users.indexOf('all') > -1 || users === '') {
apps/files_external/lib/config.php:		if (isset($mountConfig[self::MOUNT_TYPE_USER]) && isset($mountConfig[self::MOUNT_TYPE_USER]['all'])) {
apps/files_external/lib/config.php:			$mounts = $mountConfig[self::MOUNT_TYPE_USER]['all'];
apps/files_external/lib/etagpropagator.php:		if ($type === \OC_Mount_Config::MOUNT_TYPE_GROUP or $users === 'all') {
apps/files_external/service/globalstoragesservice.php:					'all',
apps/files_external/service/globalstoragesservice.php:				['all']
apps/files_external/service/globalstoragesservice.php:				['all']
apps/files_external/service/globalstoragesservice.php:				['all']
apps/files_external/service/storagesservice.php:			if ($applicable !== 'all') {
apps/files_external/tests/service/globalstoragesservicetest.php:						'all'
apps/files_external/tests/service/globalstoragesservicetest.php:						'all',
apps/files_external/tests/service/globalstoragesservicetest.php:						'all'
apps/files_external/tests/service/globalstoragesservicetest.php:						'all',
apps/files_external/tests/service/globalstoragesservicetest.php:		$this->assertEquals(['all'], array_keys($json[\OC_Mount_config::MOUNT_TYPE_USER]));
apps/files_external/tests/service/globalstoragesservicetest.php:		$mountPointData = $json[\OC_Mount_config::MOUNT_TYPE_USER]['all'];
apps/files_external/tests/mountconfig.php:		$applicable = 'all';
apps/files_external/tests/mountconfig.php:		$applicable = 'all';
apps/files_external/tests/mountconfig.php:				'all',
apps/files_external/tests/mountconfig.php:					'users' => array('all'),
apps/files_external/tests/mountconfig.php:		$applicable = 'all';
apps/files_external/tests/mountconfig.php:				'all',
apps/files_external/tests/mountconfig.php:					'applicable' => 'all',
apps/files_external/tests/mountconfig.php:		$applicable = 'all';
apps/files_external/tests/etagpropagator.php:			Filesystem::signal_param_users => 'all',
````

**Comment by schiesbn** [comment]
First try to fix it https://github.com/owncloud/core/pull/19534, please discuss in the PR

**Comment by SergioBertolinSG** [comment]
Tested on last master, working fine.
