### ISSUE TITLE
Error creating files and folders with IE11 and Owncloud 8.1.1

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#19540]
A strange issue with Owncloud 8.1.1 it is runing on Ubuntu 14.04 LTS.

One Users with  IE11 can not create new folders or files but this is randomly. 
Most of the time it is not created, but sometimes it works like it should.

There is no information in the oC log file.

The access Apache logs shows when a new folder is created successfully, but nothing when it doesn't.

With tcpdump we see in both cases that there are packages send, but in case of a failure less packages are send.

Is there a know setting for IE 11 that we can try? 

@MorrisJobke 

00003931

**Comment by PVince81** [comment]
Let that user open the browser's Javascript console and see if there are errors. The user might need to retry the operation to make output appear. (I think IE might not log things when the console is not open)

**Comment by MorrisJobke** [comment]
I tried creating folders and upload files for some minutes with IE11 but can't reproduce the issue :(

**Comment by PVince81** [comment]
The question is maybe whether something else was done before creating a new folder. Switched folder ? Changed shares ? Something that could affect the JS code somehow...

**Comment by cdamken** [comment]
Server stack:

• Operating system (name and version number):
root@cloud01:~# cat /etc/issue
Ubuntu 14.04.1 LTS \n \l

• Your ownCloud availability:
Internet

• Webserver (name and version number):
root@cloud01:~# apache2ctl -v
Server version: Apache/2.4.7 (Ubuntu)
Server built: Jul 24 2015 17:25:11

• Apache modules enabled as declared in:

access_compat.load
alias.conf
alias.load
auth_basic.load
authn_core.load
authn_file.load
authz_core.load
authz_host.load
authz_user.load
autoindex.conf
autoindex.load
deflate.conf
deflate.load
dir.conf
dir.load
env.load
filter.load
headers.load
mime.conf
mime.load
mpm_itk.load
mpm_prefork.conf
mpm_prefork.load
negotiation.conf
negotiation.load
php5.conf
php5.load
rewrite.load
setenvif.conf
setenvif.load
socache_shmcb.load
ssl.conf
ssl.load
status.conf
status.load

• Database (name and version number):
mysql Ver 14.14 Distrib 5.5.44, for debian-linux-gnu (x86_64) using readline 6.3

• PHP (version number):
root@cloud01:/etc/apache2/mods-enabled# php -v
PHP 5.5.9-1ubuntu4.11 (cli) (built: Jul 2 2015 15:23:08)

• PHP cache manager
dpkg -s php5-apcu
Package: php5-apcu
Status: install ok installed
Priority: optional
Section: php
Installed-Size: 313
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Source: php-apcu
Version: 4.0.6-1

• PHP installed packages
root@cloud01:/etc/apache2/mods-enabled# dpkg -l |grep php |awk {'print $2 " -> " $3'}
libapache2-mod-php5 -> 5.5.9+dfsg-1ubuntu4.11
php-pear -> 5.5.9+dfsg-1ubuntu4.11
php5-apcu -> 4.0.6-1
php5-cli -> 5.5.9+dfsg-1ubuntu4.11
php5-common -> 5.5.9+dfsg-1ubuntu4.11
php5-curl -> 5.5.9+dfsg-1ubuntu4.11
php5-dev -> 5.5.9+dfsg-1ubuntu4.11
php5-gd -> 5.5.9+dfsg-1ubuntu4.11
php5-imagick -> 3.1.2-1build1
php5-json -> 1.3.2-2build1
php5-ldap -> 5.5.9+dfsg-1ubuntu4.11
php5-mcrypt -> 5.4.6-0ubuntu5
php5-memcached -> 2.1.0-6build1
php5-mysql -> 5.5.9+dfsg-1ubuntu4.11
php5-oauth -> 1.2.3-1build1
php5-readline -> 5.5.9+dfsg-1ubuntu4.11
pkg-php-tools -> 1.11

• ownCloud Enterprise Server Version
Lookup in web: (URL from ownCloud)/status.php
{"installed":true,"maintenance":false,"version":"8.1.1.3","versionstring":"8.1.1","edition":"Enterprise"}

• Did you install your ownCloud with TAR files or packages?
From Tar file

• Tell us your migration path of the ownCloud software
fresh install

• Do you have records from your migration steps?

• List of owncloud-apps enabled/ in use (see bold printed apps in: administration ? Apps):
 Enabled:
- activity: 2.0.1
- admin_audit: 0.6
- calendar: 0.7.3
- enterprise_key: 0.1.0
- files: 1.1.10
- files_locking:
- files_pdfviewer: 0.7
- files_sharing: 0.6.2
- files_sharing_log: 0.5
- files_texteditor: 0.4
- files_trashbin: 0.6.3
- files_versions: 1.0.6
- files_videoviewer: 0.1.3
- firewall: 0.91.2
- firstrunwizard: 1.1
- tasks: 0.8
- templateeditor: 0.1
- updater: 0.6
- windows_network_drive: 0.1.1
 Disabled:
- encryption
- external
- files_antivirus
- files_drop
- files_external
- files_ldap_home
- gallery
- objectstore
- provisioning_api
- sharepoint
- user_external
- user_ldap
- user_shibboleth
- user_webdavauth

• The content of your config/config.php:
```
<?php
$CONFIG = array (
'supportedDatabases' =>
	array (
		0 => 'mysql',
		1 => 'pgsql',
		2 => 'oci',
	),
'instanceid' => 'ockfagc1u50g',
'passwordsalt' => '**********************************',
'secret' => '************************************************************',
'trusted_domains' => 
		array (
					0 => 'SERVER_NAME',
		),
'datadirectory' => '/home/www/SERVER_NAME/data',
'overwrite.cli.url' => 'https://SERVER_NAME',
'dbtype' => 'mysql',
'version' => '8.1.1.3',
'dbname' => 'DB-OC',
'dbhost' => 'localhost',
'dbtableprefix' => 'oc_',
'dbuser' => 'DB-OC',
'dbpassword' => '****************',
'logtimezone' => 'UTC',
'installed' => true,
'license-key' => '***********************************',
'memcache.local' => '\\OC\\Memcache\\Memcached',
'memcache.distributed' => '\\OC\\Memcache\\Memcached',
'memcached_servers' => 
	array (
		0 =>
		array (
			0 => 'localhost',
			1 => 11211,
		),
	),
);
```

• Storage type and setup
Storage is local on the server itself.

• LDAP
We use the local mysql database

• LDAP configuration (delete this part if not used)
We do not use LDAP

• Loadbalancer
There is no Loadbalancer in front of the webserver

• High availability setup
We do not have a failover configuration.

• Proxies
No proxy's in between

• Customizations
Non, except the header for icons.

• Additional architectural features (disaster recovery setup, etc.):
None

**Comment by cdamken** [comment]
I see they have ACPU but configured Memecached in the config.php

**Comment by cdamken** [comment]
We probably have found the issue causing this. This is due to the PHP APC cache module.
Even if this module is disabled on the server it causes interruptions in the drag and drop and creation of folders features.  Especially in Internet Explorer environments.

So we deleted the complete module and now everything works. I think this is a good one to mention in some developer FAQ.
So it was not activated, but still somehow giving all the weird IE errors.

**Comment by DeepDiver1975** [comment]
> We probably have found the issue causing this. This is due to the PHP APC cache module.
> Even if this module is disabled on the server it causes interruptions in the drag and drop and creation of folders features. Especially in Internet Explorer environments.
> 
> So we deleted the complete module and now everything works. I think this is a good one to mention in some developer FAQ.
> So it was not activated, but still somehow giving all the weird IE errors.

That's really a strange explanation ... I honestly cannot believe this

**Comment by cdamken** [comment]
I'm agree

**Comment by cdamken** [comment]
The issue is not resolved.
We've tested with the following configuration:
Ubunto 14.04.3 LTS
Apache 2.4.7
php and php fpm 5.5.9
Memcached 1.4
APCu 1.7(manual installation)
Redis 2.8

With APCu it doesn't work on IE and Edge.
WIth Memcached it sometimes works on IE but not on Edge
With Redis it works with IE but not on Edge
Firefox and Chrome doesn't have these problems

How do we test:
We use the OC webinterface to create a folder. Sometimes the folder is
created en sometimes not. Sometimes after 5 times it stops working.
We use the OC webinterface to upload files. Sometimes nothing happens.

We installed OC on a BSD server and it seems to work correctly.

What can be the problem?

**Comment by PVince81** [comment]
@cdamken we anything in the owncloud.log or javascript console when the problem happens ?

**Comment by PVince81** [comment]
Is always the same IE11 instance used or is that different machines ? Has the cache + cookies been cleared between the test cases ?

**Comment by cdamken** [comment]
@PVince81 Thanks for the hints.

I tested, but I can't reproduce the error in their environment. something is weird :weary:

**Comment by cdamken** [comment]
Ok, now I tested in another server:
with IE11: 
SCRIPT7002: XMLHttpRequest: Network Error 0x2ef3, Could not complete the operation due to error 00002ef3.

**Comment by MorrisJobke** [comment]
Maybe this helps: http://stackoverflow.com/a/15748586


But I don't see a nice way to patch all the AJAX requests :see_no_evil:

**Comment by PVince81** [comment]
The weird part is why it only happens sometimes and not always.

**Comment by cdamken** [comment]
The log files only shows:

```
PHP Startup: apc.shm_size now uses M/G suffixes, please update your ini files at Unknown#0
```

**Comment by MorrisJobke** [comment]
We now did a screenshare. We also did two times a create folder - the first one succeeded, the second request failed. Here is the network dump:

```
<?xml version="1.0" encoding="UTF-8"?>
<log>
	<version>1.1</version>
	<creator>
		<name>Internet Explorer Network Inspector</name>
		<version>11.0.9600.18036</version>
	</creator>
	<browser>
		<name>Internet Explorer</name>
		<version>11.0.9600.18036</version>
	</browser>
	<pages>
		<page>
			<startedDateTime>2015-10-13T16:24:41.306+01:00</startedDateTime>
			<id>0</id>
			<title/>
			<pageTimings>
				<onContentLoad>-1</onContentLoad>
				<onLoad>-1</onLoad>
			</pageTimings>
		</page>
	</pages>
	<entries>
		<entry>
			<pageref>0</pageref>
			<startedDateTime>2015-10-13T16:24:52.322+01:00</startedDateTime>
			<time>500</time>
			<request>
				<method>POST</method>
				<url>https://domain.tld/index.php/apps/files/ajax/newfolder.php</url>
				<httpVersion>HTTP/1.1</httpVersion>
				<cookies>
					<cookie>
						<name>XXXXXXXX</name>
						<value>XXXXXXXXXX</value>
					</cookie>
				</cookies>
				<headers>
					<header>
						<name>Accept</name>
						<value>*/*</value>
					</header>
					<header>
						<name>Content-Type</name>
						<value>application/x-www-form-urlencoded; charset=UTF-8</value>
					</header>
					<header>
						<name>requesttoken</name>
						<value>xxxxxxxxxxxxxxxxx</value>
					</header>
					<header>
						<name>OCS-APIREQUEST</name>
						<value>true</value>
					</header>
					<header>
						<name>X-Requested-With</name>
						<value>XMLHttpRequest</value>
					</header>
					<header>
						<name>Referer</name>
						<value>https://domain.tld/index.php/apps/files</value>
					</header>
					<header>
						<name>Accept-Language</name>
						<value>en-US,en;q=0.8,es-MX;q=0.7,es;q=0.5,de-DE;q=0.3,de;q=0.2</value>
					</header>
					<header>
						<name>Accept-Encoding</name>
						<value>gzip, deflate</value>
					</header>
					<header>
						<name>User-Agent</name>
						<value>Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko</value>
					</header>
					<header>
						<name>Host</name>
						<value>domain.tld</value>
					</header>
					<header>
						<name>Content-Length</name>
						<value>32</value>
					</header>
					<header>
						<name>Connection</name>
						<value>Keep-Alive</value>
					</header>
					<header>
						<name>Cache-Control</name>
						<value>no-cache</value>
					</header>
					<header>
						<name>Cookie</name>
						<value>xxxxxxxxxxx=xxxxxxxxxxx</value>
					</header>
				</headers>
				<queryString/>
				<postData>
					<mimeType>application/x-www-form-urlencoded</mimeType>
					<text>dir=%2F&amp;foldername=Carlos+Test+2</text>
				</postData>
				<headersSize>658</headersSize>
				<bodySize>32</bodySize>
			</request>
			<response>
				<status>200</status>
				<statusText>OK</statusText>
				<httpVersion>HTTP/1.1</httpVersion>
				<cookies/>
				<headers>
					<header>
						<name>Date</name>
						<value>Tue, 13 Oct 2015 16:24:58 GMT</value>
					</header>
					<header>
						<name>Server</name>
						<value>Apache/2.4.7 (Ubuntu)</value>
					</header>
					<header>
						<name>Strict-Transport-Security</name>
						<value>max-age=15768000</value>
					</header>
					<header>
						<name>Expires</name>
						<value>Thu, 19 Nov 1981 08:52:00 GMT</value>
					</header>
					<header>
						<name>Cache-Control</name>
						<value>no-store, no-cache, must-revalidate, post-check=0, pre-check=0</value>
					</header>
					<header>
						<name>Pragma</name>
						<value>no-cache</value>
					</header>
					<header>
						<name>Content-Security-Policy</name>
						<value>default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *; connect-src *</value>
					</header>
					<header>
						<name>X-Content-Type-Options</name>
						<value>nosniff</value>
					</header>
					<header>
						<name>X-XSS-Protection</name>
						<value>1; mode=block</value>
					</header>
					<header>
						<name>X-Robots-Tag</name>
						<value>none</value>
					</header>
					<header>
						<name>X-Frame-Options</name>
						<value>SAMEORIGIN</value>
					</header>
					<header>
						<name>Content-Length</name>
						<value>291</value>
					</header>
					<header>
						<name>Keep-Alive</name>
						<value>timeout=5, max=100</value>
					</header>
					<header>
						<name>Connection</name>
						<value>Keep-Alive</value>
					</header>
					<header>
						<name>Content-Type</name>
						<value>application/json; charset=utf-8</value>
					</header>
				</headers>
				<content>
					<size>291</size>
					<mimeType>application/json; charset=utf-8</mimeType>
					<text>{"data":{"id":184072,"parentId":"8529","date":"October 13, 2015 at 6:24:58 PM GMT+2","mtime":1444753498000,"icon":"\/core\/img\/filetypes\/folder.svg","name":"Carlos Test 2","permissions":31,"mimetype":"httpd\/unix-directory","size":0,"type":"dir","etag":"561d305a30667"},"status":"success"}</text>
				</content>
				<redirectionURL/>
				<headersSize>695</headersSize>
				<bodySize>291</bodySize>
			</response>
			<cache/>
			<timings>
				<send>0</send>
				<wait>391</wait>
				<receive>0</receive>
			</timings>
		</entry>
		<entry>
			<pageref>0</pageref>
			<startedDateTime>2015-10-13T16:25:02.103+01:00</startedDateTime>
			<time>31</time>
			<request>
				<method/>
				<url>https://domain.tld/index.php/apps/files/ajax/newfolder.php</url>
				<httpVersion/>
				<cookies/>
				<headers/>
				<queryString/>
				<headersSize>0</headersSize>
				<bodySize>0</bodySize>
			</request>
			<response>
				<cookies/>
				<headers/>
				<content>
					<size>0</size>
					<mimeType/>
				</content>
				<redirectionURL/>
				<headersSize>0</headersSize>
				<bodySize>0</bodySize>
			</response>
			<cache/>
			<timings>
				<send>31</send>
				<wait>-1</wait>
				<receive>-1</receive>
			</timings>
		</entry>
	</entries>
</log>
```

Somehow the second request is nearly empty. Could this be the cause or is this empty request only a symptom that is misinterpret in IE11.

**Comment by PVince81** [comment]
Right, that second request looks wrong. Even the request method is missing!

Are you able to reproduce this by creating a new folder twice within the same browser session ?
If yes it could mean that maybe the old XMLHttpRequest object is being reused instead of creating a new one, and maybe it's in a bad/broken state.

I checked in Chromium and the second request is always identical, so it's probably a IE-specific thing.
Will try with an IE11 VM next.

**Comment by MorrisJobke** [comment]
> Are you able to reproduce this by creating a new folder twice within the same browser session ?

I don't exaclty know, that it always was the second request, but it could be.

**Comment by PVince81** [comment]
Hmmm, that is just a simple ajax call: https://github.com/owncloud/core/blob/v8.1.1/apps/files/js/file-upload.js#L672 not even FileReader API or anything fancy.
This means that here we explicitly tell jquery to use the "POST" method, so if IE11 doesn't do it properly, either something is going wrong within jQuery or IE11 itself is buggy...

Works properly on IE9. Surprinsingly IE9 also has a network monitor!

**Comment by PVince81** [comment]
and I thought the IE8 times were almost over :scream:

**Comment by PVince81** [comment]
Here https://connect.microsoft.com/IE/feedback/details/817359/xmlhttprequest-issue some people also say they see this intermittently...

**Comment by PVince81** [comment]
Even more info here: http://stackoverflow.com/questions/13390189/do-ajax-applications-that-use-post-requests-always-fail-in-internet-explorer

Seems to be a weird bug in IE with Keep-alive connections

**Comment by PVince81** [comment]
and possibly another one: http://stackoverflow.com/questions/4796305/why-does-internet-explorer-not-send-http-post-body-on-ajax-call-after-failure

It is suggested to increase the server's keep-alive to more than 60 seconds to avoid triggering this browser bug.. However this also means that the server might have less connections available.

Now the question whether we can disable keep-alive from the client side specifically for IE.

**Comment by PVince81** [comment]
Question: when the issue occurred, did your laptop connect/disconnect from the network in-between ? For example, did you leave the browser tab opened, suspend the laptop directly (or switch off network), then after resuming you tried creating a folder within that same browser tab ?
Some articles say that IE might be trying to reuse an outdated network connection as part of the keep-alive scheme.

**Comment by PVince81** [comment]
Also since it's about keep-alive, I also read that it could be triggered when having several ajax calls running at the same time. When creating a folder it's only a single request. However, at some time intervals there's the "heartbeat" ajax call and also the "getstoragestats.php" call.
Maybe at the time you created the folder it was very shortly after one of these calls, which triggered the IE bug, where IE tried to reuse these connections.

**Comment by MorrisJobke** [comment]
> Question: when the issue occurred, did your laptop connect/disconnect from the network in-between ?

We did this during a screensharing session. The network was stable all the time.

**Comment by MorrisJobke** [comment]
> Maybe at the time you created the folder it was very shortly after one of these calls, which triggered the IE bug, where IE tried to reuse these connections.

We only have seen those two network requests. Nothing more in the network tab during testing.

**Comment by cdamken** [comment]
We removed Memcached and only APCu with the updated version 4.0.6 from the config.php but the same behaviour:

```
URL														Protocol	Method		Result		Type				Received	Taken	Initiator		Wait‎‎		Start‎‎	Request‎‎	Response‎‎	Cache read‎‎	Gap‎‎	
/index.php/apps/files/ajax/newfolder.php				HTTPS		POST		200			application/json	0.96 KB		0.50 s	XMLHttpRequest	11016		109		0		391			0			57975406
/index.php/apps/files/ajax/newfolder.php				HTTPS					(Aborted)						0 B			31 ms	XMLHttpRequest	20797		0		0		0			0			57966094
/index.php/apps/files/ajax/getstoragestats.php?dir=%2F	HTTPS		GET			200			application/json	0.87 KB		250 ms	XMLHttpRequest	131469		78		172		0			0			57855203
/index.php/apps/files/ajax/newfolder.php				HTTPS		POST		200			application/json	0.96 KB		406 ms	XMLHttpRequest	57977860	125		0		281			0			8656
/index.php/apps/files/ajax/newfolder.php				HTTPS					(Aborted)						0 B			16 ms	XMLHttpRequest	57986875	0		0		0			0			31
```

**Comment by cdamken** [comment]
I added the the ownCloud log and Apache logs: access.log, error.log in:

S3-ownCloud\Shared\owncloud\support\github-issues\core\19540

**Comment by MorrisJobke** [comment]
@PVince81 This looks like your idea. Always the second POST request failed.

**Comment by PVince81** [comment]
Are you creating two folder very quickly without waiting for the first call to return ? What if you wait for a minute before the second call ? (would fit in the keep-alive idea)

**Comment by cdamken** [comment]
not always, its really random, sometimes can be at the first time or sometime it take 4 times

**Comment by PVince81** [comment]
testing with @cdamken it seemed to happen if the second call is done within 5 to 10 seconds of the first one. Faster than 5 seconds worked.

We thought maybe it matched the keep-alive value that is set to 5 seconds.

**Comment by cdamken** [comment]
![ie9](https://cloud.githubusercontent.com/assets/7264495/10482838/cb766b5a-727b-11e5-960f-05fec903c123.png)

**Comment by cdamken** [comment]
The test for IE9:

S3-ownCloud\Shared\owncloud\support\github-issues\core\19540\IE9-Test-NetworkData.xml

**Comment by PVince81** [comment]
so basically IE aborts that call forever...

**Comment by PVince81** [comment]
I wonder if the APC/memcache settings could influence the keep-alive of the connection. Could explain why it happens on some servers and not others.

**Comment by cdamken** [comment]
the Apache is not a default Apache, its an apache-itk

**Comment by cdamken** [comment]
I uploaded the apache configuration and the php5 configuration in:
S3-ownCloud\Shared\owncloud\support\github-issues\core\19540

**Comment by cdamken** [comment]
now we tested in a new fresh installation who is also created with the same configuration over pxe,
but now with oC 8.2 CE.

over HTTP works without problem

over HTTPS happens the same problem.

**Comment by cdamken** [comment]
Guys, could you take a look to: http://jonnyreeves.co.uk/2013/making-xhr-request-to-https-domains-with-winjs/



I recently came across an interesting caveat when working with WinJS (the JavaScript layer for creating Windows 8 Store applications). If you attempt to make an HTTP POST request to a server over the HTTPS protocol you may run into the following error:

```
XMLHttpRequest: Network Error 0x2ef3, Could not complete the operation due to error 00002ef3.
```

This error appears to be caused by a security certificate issue; however the solution is pretty straight forward – you just need to make a GET request before attempting subsequent POST request, for example:

```
// Before making a POST request we first have to issue a GET against the target
// server to work around Network Error 0x2ef3.  Note you only need to do this
// ONCE in your app, not every time.
WinJS.xhr({
    url: "https://my.server/"
}).then(function () {

    // After a single GET request we can now invoke POST requests.
    WinJS.xhr({
        url: "https://my.server/endpoint",
        type: "POST",
        data: {
            foo: "bar"
        }
    })
}).then(function () {
    console.log("HTTPS POST request complete!");
});
```

**Comment by MorrisJobke** [comment]
> you just need to make a GET request before attempting subsequent POST request, for example:

:see_no_evil: :hear_no_evil: :speak_no_evil: cc @PVince81

**Comment by PVince81** [comment]
"just" ...

I think I understand why this might work: as we said before, IE11 has trouble reusing timed out ajax calls for that POST. So basically by doing a GET before that one, when the GET is finished, it will likely be reused (as per "keep alive") for the next POST call.

The problem would be the same as before: we would need to find **ALL** locations for **every** ajax call, and then make a GET call to the base domain (maybe status.php or heartbeat). This could lead to a lot of additional ajax calls to work around this IE issue.

What is not clear is whether this GET can run in parallel to the POST or whether the POST has to wait for that GET to finish. The latter is more complicated to achieve.

Again, the problem isn't about fixing a single ajax call, which would be easy, but **ALL** of them.

**Comment by PVince81** [comment]
Just had a look at the link from @cdamken and it seems the POST has to wait for the GET.
Also I'm not sure it's exactly the same. He's talking about Win8 app store apps, not websites. I can understand that the GET would first retrieve/verify the SSL certificate and POST would reuse it.

Not sure if that applies to our situation here, unless the browser forgets about the certificate within 5 seconds ?!

**Comment by felixboehm** [comment]
I can reproduce this by executing this code in the console on the specific testsystem:
```
  //  delete console.log;
  $.post( "/fun.php", { name: "John" })
  .done(function( data,text, xhr ) {
    console.log( "Success", xhr.status, xhr.readyState);
  })
  .fail(function(xhr) {
    console.log(xhr.status, xhr.statusText, xhr.readyState);
  });
```
Sometimes it gives me the same error:
```
SCRIPT7002: XMLHttpRequest: Netzwerkfehler 0x2ef3, Der Vorgang konnte aufgrund des folgenden Fehlers nicht fortgesetzt werden: 00002ef3.
0 error 0

/index.php/apps/files/fun.php	HTTPS		(Abgebrochen)		0 B	< 1 ms	XMLHttpRequest
```
On success (still an error, but well) it tells: ```404 Not Found 4``` as it should.

So, I guess this is not ownCloud specific, as a simple jquery post is not working as well.

**Comment by cdamken** [comment]
Hi Guys.

The problem is the apache itk module

the solution is here:

I installed a patch and it works with itk

http://lists.err.no/pipermail/mpm-itk/2015-September/000915.html

The issue is since September

## Thank you for your help!

**Comment by PVince81** [comment]
Well then, happy end. I'm really glad we didn't start implementing quirky workarounds...
