### ISSUE TITLE
getItemsSharedWithUser returns subshares even with no group membership

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#19541]
### Steps

1. Setup users "user1" and "user2"
1. Add "user1" to a new group "group1".
1. Login as "user2"
1. Create folder "test"
1. Share "test" with "group1"
1. Login as "user1"
1. Rename "test" to "test_renamed", this will make an extra entry appear in oc_share
1. Now within a single PHP request:
    1. Remove "user1" from group "group1" (group manager?)
    1. call `$shares = \OCP\Share::getItemsSharedWithUser('file', 'user1');

### Expected result
`$shares` contain zero shares

### Actual result
`$shares` contains a single share, with share_type = 2 (the reserved share type for sub-entries).
I noticed that if you call `getItemsSharedWithUser` **before** removing from group, it will return the sub-entry, but with `share_type=1`.

So far the workaround is to have the API consumer add additional code to strip out these bogus entries.

I also suspect that if you manually insert a sub-group entry for a user that is not in a group, that API will still return that result.

Observed in https://github.com/owncloud/core/pull/18128

@schiesbn @rullzer

**Comment by PVince81** [comment]
I'll provide some code in that PR that will reproduce the issue.

**Comment by PVince81** [comment]
See https://github.com/owncloud/core/commit/71cbb3fd3d32f92d8b2f563000122ff99a685513#diff-b3efca9d734e374573fd131fda288117R90

You can see it in action with a debugger: the database still contains the sub-share (it will be removed later, possibly by another event handler), but at this specific stage it still returns the sub-share, with the share_type == 2. This shouldn't happen.

Possible solutions:
1) make sure to always filter out "share_type === 2" from this API's result.
or
2) add logic to check that the user still belong to the parent share's group before adding

Solution 1) is probably the easiest that doesn't require to dive into the spaghetti code...

**Comment by PVince81** [comment]
I tried up to step 7, then I reinserted the share despite "user1" not being in the group any more:
```
insert into oc_share values (2, 2, 'user1', 'user2', 1, 'folder', 12, '/12', 12, '/test_renamed', 31, 1443807255, 0, NULL, NULL, 0);
```

Then login as "user1" in the web UI, the folder appears again!

Now I'm not aware of any real life situation where it could happen that there are leftovers share entries (LDAP?).

**Comment by labkode** [comment]
@PVince81 @blizzz This looks like the same problem as I pointed out here #14384.

This problem leads to disclosure of information

**Comment by PVince81** [comment]
@LukasReschke FYI

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/19577
@labkode can you try it with the LDAP situation ?

**Comment by PVince81** [comment]
Raising severity as it was observed in a real-life scenario (not just API case): https://github.com/owncloud/core/issues/14384

**Comment by PVince81** [comment]
@cmonteroluque @DeepDiver1975 @karlitschek FYI

**Comment by labkode** [comment]
@PVince81 as mentioned in #14384 we changed our infrastructure to not depend on OwnCloud LDAP groups and we implemented other solution, so I cannot test that scenario, but it should be straight forward to test it if you have some OC/LDAP instance.

The only special thing about our old LDAP integration is that it was big, thousands of users and thousands of groups.
