### ISSUE TITLE
Wrong format for expiration date in share dialogue

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19549]
### Steps to reproduce

1. Share a folder
2. Set an expiration date

### Expected behaviour

There should be a human readable date in the filed, using the user's locale.

### Actual behaviour

A readable date appears briefly and it changes immediately to the format shown below

![](https://cloud.githubusercontent.com/assets/323220/10246059/05a8c0c4-690e-11e5-9a1f-a4cfe93b7fef.png)

It also affects apps using the share dialogue and it seems the format can change if you make modifications using the desktop client, see https://github.com/owncloud/gallery/issues/398

**Comment by rullzer** [comment]
What do you mean by readable date?

**Comment by rullzer** [comment]
Ah I see what you mean. Yes this can and should be fixed.
It is currently not localized just `dd-mm-YYYY` but then we should probably switch to momentjs for 9.0

BUt let me take care of this.

**Comment by oparoz** [comment]
@rullzer - Look at the screenshot, at the bottom It's 2015-10-29. Only computers write dates like this and there is also the time information which we don't need :)

**Comment by rullzer** [comment]
@oparoz fix in #19553 please verify and review
