### ISSUE TITLE
Graphical glitch of sidebar on mobile

### ISSUE THREAD

**Issue by Henni** [owncloud/core#19554]
In the image the sidebar should fill the full height, but doesn't if the filelist is scrolled down.
This only appears while dragging the page to open the app-navigation.
Tested on Chrome on Desktop and Android.

<img src="https://cloud.githubusercontent.com/assets/1267827/10263636/c1f95058-69f5-11e5-91fc-8ce434768bd7.png" width="400" />

**Comment by Henni** [comment]
While dragging the page the controls are also hidden.
![image](https://cloud.githubusercontent.com/assets/1267827/10263702/ee5b289a-69f7-11e5-92f3-1f63b04428cc.png)
![image](https://cloud.githubusercontent.com/assets/1267827/10263714/46cee106-69f8-11e5-9cd8-d7f4b574821e.png)

**Comment by karlitschek** [comment]
@PVince81

**Comment by PVince81** [comment]
@Henni are you still seeing this on master ? AFAIK mobile style has been fixed

**Comment by Henni** [comment]
@PVince81 yes I still see this on master.
I can't reproduce it on Desktop anymore, because I'm not able to pull the menu even in DevTools device mode. But on mobile this still happens.

**Comment by PVince81** [comment]
please try again on 10.0.

there were lots of CSS changes with the new styles in upcoming 10.0.3.

cc @felixheidecke
