### ISSUE TITLE
Error when unsharing link 

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19550]
### Steps to reproduce
1. Go to the Server Client with Admin
2. Go to the Sharing option 
3. Select the option "Enforce password protection"
![](https://cloud.githubusercontent.com/assets/12032058/10245362/1cc768b6-6907-11e5-8e75-2c906b3d69b5.png)
4. Go to Files
5. Share a folder
6. Select the option Share by link
7. **Untick the option**

### Expected behaviour
The box should be unticked and the password field should disappear

### Actual behaviour

![unshare_error](https://cloud.githubusercontent.com/assets/323220/10263001/b79b7de6-69de-11e5-8efb-ecaf2c367715.png)

If you click on share link again, the password field now disappears

**Comment by rullzer** [comment]
Fix in #19558

**Comment by oparoz** [comment]
Thanks!

*Note: this only affects 8.2+*
