### ISSUE TITLE
Unreadable fonts in 8.2

### ISSUE THREAD

**Issue by BernhardPosselt** [owncloud/core#19555]
The fonts included in 8.2 are unusable for rendering articles. Check the image

![screen](https://cloud.githubusercontent.com/assets/195053/10263777/339a71fc-69fa-11e5-8ece-b4cfa132c0ff.png)

With more text, its even worse

@jancborchardt @MorrisJobke

**Comment by oparoz** [comment]
Join the club :) https://github.com/owncloud/core/issues/18954

But you also have a second issue. There needs to be a standard serif font for text. It makes it easier to read long content like articles.

**Comment by despens** [comment]
Arial: Best Font.
:smile:

**Comment by jancborchardt** [comment]
Dupe of https://github.com/owncloud/core/issues/18954 (I’m on vacation atm, exception)
