### ISSUE TITLE
Exception: Please upload the ca-bundle.crt file into the 'config' directory.

### ISSUE THREAD

**Issue by sutun2008** [owncloud/core#19551]
Exception: Please upload the ca-bundle.crt file into the 'config' directory.

**Comment by RealRancor** [comment]
Dup of https://github.com/owncloud/core/issues/19204 and https://github.com/owncloud/updater/issues/164 (should be available on the github search).

See https://github.com/owncloud/updater/issues/164#issuecomment-141549254 how to fix.

**Comment by MaxTorque1** [comment]
Hi RealRancor,
Thanks for pointing me to a potential solution but my .htaccess and Config.php files appear to be OK. The server however is still informing me that it is in maintenance mode and requires to upload a file with this warning:
Exception: Please upload the ca-bundle.crt file into the 'config' directory

My owncloud server is temporarily unavailable.

Any help on getting the system running again will be greatly received

**Comment by RealRancor** [comment]
> .htaccess and Config.php files appear to be OK.

Both files don't have the name "ca-bundle.crt" in their filename.

**Comment by MaxTorque1** [comment]
Hi RealRancor,
Yes, I understand (I think). I managed to copy the ca-bundle.crt file to the / var / www / html / owncloud / config folder with permissions set as 0644.
This allowed the update process to complete with update successful.
However, the server is still showing as temporarily unavailable  and I cannot now login to the owncloud web interface. When I enter my username and password, it just does not get passed the login screen.
Any ideas that you can think of would be appreciated. I am getting desperate as I need access on a daily basis. Thanks

**Comment by RealRancor** [comment]
Please create a new thread at either the forums or the users mailinglit providing more info about your environment and your problem.
