### ISSUE TITLE
Force SSL does not make share links https

### ISSUE THREAD

**Issue by gillytech** [owncloud/core#19557]
I have "force ssl" set to true in my config, but I noticed that the download links are not offered as SSL, I have to manually add https to the beginning. Thanks for your time.

**Comment by aspdye** [comment]
Force SSL is not longer supported in ownCloud 8.1 and higher.
You need to config your webserver manually to force HTTPS.

**Comment by oparoz** [comment]
@gillytech https://doc.owncloud.com/server/8.1/admin_manual/release_notes.html#changes-in-8-1

**Comment by LukasReschke** [comment]
See also https://github.com/owncloud/core/blob/2ffb1c2135d80ac82f62c2bd403fe452e2c4e51d/config/config.sample.php#L353-L360

**Comment by gillytech** [comment]
Hey guys thanks for getting back with me on this. I see what the issue is and Lukas' suggestion is spot on. Thanks again.
