### ISSUE TITLE
Impossible to easily clear the current selection

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19564]
### Steps to reproduce
1. Select a few files
2. Click anywhere outside the files list
### Normal behaviour
- The selection is cleared
- The sidebar shows a summary of the current folder (in the future)
### Actual behaviour

Nothing happens. There is not even a clear button

---

@jancborchardt @PVince81

**Comment by PVince81** [comment]
With selection you mean the checkbox selection, not the sidebar highlight ?

Related: #18210

**Comment by oparoz** [comment]
> With selection you mean the checkbox selection, not the sidebar highlight ?

Correct, the sidebar just adapts to the selection

**Comment by MorrisJobke** [comment]
@owncloud/designers We maybe want to discuss this behaviour change first ;)

**Comment by jancborchardt** [comment]
Hm, clicking outside of the files view accidentally and losing the selection is painful as well though. And the »summary of the current folder (in the future)« is not possible yet unfortunately because of https://github.com/owncloud/activity/issues/380

The clear function is clicking the »select all« checkbox on the top left in the header of the files list. Maybe we can make that more obvious with a clear button, taking hints from GNOME’s Nautilus.

**Comment by oparoz** [comment]
> Hm, clicking outside of the files view accidentally and losing the selection is painful as well though

Maybe, but that's the universal way to do things.

> The clear function is clicking the »select all« checkbox on the top left in the header of the files list.

Well, the first time you click it, all items are selected and only then can you clear the list. I'd call this a workaround, not a proper way to clear a selection.

**Comment by jancborchardt** [comment]
> Well, the first time you click it, all items are selected and only then can you clear the list. I'd call this a workaround, not a proper way to clear a selection.

Right, so that behavior needs to change:
* when no files are selected, clicking the checkbox should select all files
* when some files (or all files) are selected, clicking the checkbox should **deselect** all files

@PVince81 @schiesbn @owncloud/designers ok?

**Comment by MorrisJobke** [comment]
> when some files (or all files) are selected, clicking the checkbox should deselect all files

That's confusing o.O Why not have it first select all and then on the second click you have the deselect all ...

**Comment by jancborchardt** [comment]
@MorrisJobke cause that’s what we have now, and it’s strange. When you have some files selected, you need a way to just clear the selection more than quickly selecting all.

**Comment by MorrisJobke** [comment]
> @MorrisJobke cause that’s what we have now, and it’s strange. When you have some files selected, you need a way to just clear the selection more than quickly selecting all.

I'm okay with that then. Just tried it and it makes more sense with the updated behaviour.

**Comment by oparoz** [comment]
I did some research 

* You can only deselect elements on Windows if you click on the empty space on the right, when you don't have a preview or detailed pane
* Github does selection the same way ownCloud does (with an additional visual feedback for partial selection)

I think @jancborchardt's proposal could work. The key being to have good visual feedback, like a crossed checkbox when the action is remove_all.
An alternative could be to have a "clear selection" zone. I instinctively click on the controls bar, but maybe there is a study out there which lists what users are trying to do to clear the selection.

**Comment by jancborchardt** [comment]
Let’s first just go with I proposed please. It’s a very simple behavior improvement and doesn’t introduce any new elements.
