### ISSUE TITLE
No option to move or copy selected items without drag and drop

### ISSUE THREAD

**Issue by strugee** [owncloud/core#19569]
When you select multiple items in the web interface, a bar appears at the top with the option to download or delete the items. It should also be possible to move and copy them.

**Comment by RealRancor** [comment]
Hi,

there is an app providing both functionalities available here:

https://apps.owncloud.com/content/show.php/Files+move?content=150271

**Comment by strugee** [comment]
@RealRancor thanks. This should really be in core, though.

**Comment by PVince81** [comment]
Closing as duplicate of https://github.com/owncloud/core/issues/10656
