### ISSUE TITLE
Weather App

### ISSUE THREAD

**Issue by tx7** [owncloud/core#19565]
Hi all,

I'm currently using OC v8.1.3 running on Nginx.
My enabled apps are Agree Disclaimer , Delete Confirmation, Gallery Plus, Antivirus...
I'm keep getting this error, whenever I'm using the Weather app v1.2.0.

Error	PHP	Declaration of OCA\Weather\Db\CityMapper::delete() should be compatible with OCP\AppFramework\Db\Mapper::delete(OCP\AppFramework\Db\Entity $entity) at /media/82468379-6874-47f3-9a21-615766f2ccab/www/owncloud/apps/weather/db/citymapper.php#18	2015-10-04T18:34:11-04:00
Error	PHP	Argument 5 passed to OCA\Weather\Controller\CityController::__construct() must be an instance of OCA\Weather\Controller\SettingsMapper, instance of OCA\Weather\Db\SettingsMapper given, called in /media/82468379-6874-47f3-9a21-615766f2ccab/www/owncloud/apps/weather/appinfo/application.php on line 60 and defined at /media/82468379-6874-47f3-9a21-615766f2ccab/www/owncloud/apps/weather/controller/citycontroller.php#28	2015-10-04T18:34:11-04:00
Error	PHP	Declaration of OCA\Weather\Db\CityMapper::delete() should be compatible with OCP\AppFramework\Db\Mapper::delete(OCP\AppFramework\Db\Entity $entity) at /media/82468379-6874-47f3-9a21-615766f2ccab/www/owncloud/apps/weather/db/citymapper.php#18	2015-10-04T18:34:11-04:00
Error	PHP	Argument 5 passed to OCA\Weather\Controller\CityController::__construct() must be an instance of OCA\Weather\Controller\SettingsMapper, instance of OCA\Weather\Db\SettingsMapper given, called in /media/82468379-6874-47f3-9a21-615766f2ccab/www/owncloud/apps/weather/appinfo/application.php on line 60 and defined at /media/82468379-6874-47f3-9a21-615766f2ccab/www/owncloud/apps/weather/controller/citycontroller.php#28	2015-10-04T18:34:11-04:00
Error	PHP	Declaration of OCA\Weather\Db\CityMapper::delete() should be compatible with OCP\AppFramework\Db\Mapper::delete(OCP\AppFramework\Db\Entity $entity) at /media/82468379-6874-47f3-9a21-615766f2ccab/www/owncloud/apps/weather/db/citymapper.php#18	2015-10-04T18:34:11-04:00
Error	PHP	Declaration of OCA\Weather\Db\CityMapper::delete() should be compatible with OCP\AppFramework\Db\Mapper::delete(OCP\AppFramework\Db\Entity $entity) at /media/82468379-6874-47f3-9a21-615766f2ccab/www/owncloud/apps/weather/db/citymapper.php#18	2015-10-04T18:34:07-04:00
Error	PHP	Declaration of OCA\Weather\Db\CityMapper::delete() should be compatible with OCP\AppFramework\Db\Mapper::delete(OCP\AppFramework\Db\Entity $entity) at /media/82468379-6874-47f3-9a21-615766f2ccab/www/owncloud/apps/weather/db/citymapper.php#18	2015-10-04T18:34:04-04:00
Error	PHP	Argument 5 passed to OCA\Weather\Controller\CityController::__construct() must be an instance of OCA\Weather\Controller\SettingsMapper, instance of OCA\Weather\Db\SettingsMapper given, called in /media/82468379-6874-47f3-9a21-615766f2ccab/www/owncloud/apps/weather/appinfo/application.php on line 60 and defined at /media/82468379-6874-47f3-9a21-615766f2ccab/www/owncloud/apps/weather/controller/citycontroller.php#28	2015-10-04T18:34:03-04:00
Error	PHP	Declaration of OCA\Weather\Db\CityMapper::delete() should be compatible with OCP\AppFramework\Db\Mapper::delete(OCP\AppFramework\Db\Entity $entity) at /media/82468379-6874-47f3-9a21-615766f2ccab/www/owncloud/apps/weather/db/citymapper.php#18	2015-10-04T18:34:03-04:00
Error	PHP	Argument 5 passed to OCA\Weather\Controller\CityController::__construct() must be an instance of OCA\Weather\Controller\SettingsMapper, instance of OCA\Weather\Db\SettingsMapper given, called in /media/82468379-6874-47f3-9a21-615766f2ccab/www/owncloud/apps/weather/appinfo/application.php on line 60 and defined at /media/82468379-6874-47f3-9a21-615766f2ccab/www/owncloud/apps/weather/controller/citycontroller.php#28	2015-10-04T18:34:02-04:00
Error	PHP	Declaration of OCA\Weather\Db\CityMapper::delete() should be compatible with OCP\AppFramework\Db\Mapper::delete(OCP\AppFramework\Db\Entity $entity) at /media/82468379-6874-47f3-9a21-615766f2ccab/www/owncloud/apps/weather/db/citymapper.php#18	2015-10-04T18:34:02-04:00
Error	PHP	Declaration of OCA\Weather\Db\CityMapper::delete() should be compatible with OCP\AppFramework\Db\Mapper::delete(OCP\AppFramework\Db\Entity $entity) at /media/82468379-6874-47f3-9a21-615766f2ccab/www/owncloud/apps/weather/db/citymapper.php#18	2015-10-04T18:33:40-04:00
Error	PHP	Argument 5 passed to OCA\Weather\Controller\CityController::__construct() must be an instance of OCA\Weather\Controller\SettingsMapper, instance of OCA\Weather\Db\SettingsMapper given, called in /media/82468379-6874-47f3-9a21-615766f2ccab/www/owncloud/apps/weather/appinfo/application.php on line 60 and defined at /media/82468379-6874-47f3-9a21-615766f2ccab/www/owncloud/apps/weather/controller/citycontroller.php#28	2015-10-04T18:33:37-04:00

**Comment by karlitschek** [comment]
I guess this is a problem with the weather app and not ownCloud core. Please report te problem directly to the developer of the app.
