### ISSUE TITLE
Impossible to drag items with a small viewport

### ISSUE THREAD

**Issue by strugee** [owncloud/core#19568]
On desktop, if the browser window is somewhat narrow (e.g. occupying half the screen on a small laptop), it's not possible to drag and drop items, because doing so triggers the logic that allows you to drag open the navigation drawer.

**Comment by PVince81** [comment]
Dragging files up and down the files list will now autoscroll.

If you're still having issues, please use the issue template and explain the problem in detail (what are you dragging, where, etc)
