### ISSUE TITLE
LDAP buttons do not appear using IE8 as browser

### ISSUE THREAD

**Issue by davitol** [owncloud/core#19575]
### Steps to reproduce

1. Add new LDAP conf
2. Copy current LDAP conf

### Expected behaviour
The buttons should have their own icon and work

### Actual behaviour
The buttons do not have their own icon and work

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** ownCloud Enterprise Edition 8.2 beta1 (daily) Build:2015-10-05T03:08:46+00:00 2ffb1c2135d80ac82f62c2bd403fe452e2c4e51d

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Internet Explorer 8

![ldapicon8](https://cloud.githubusercontent.com/assets/10596560/10067917/88098a18-62a0-11e5-9c1e-648f00759d71.png)

**Comment by MorrisJobke** [comment]
https://github.com/owncloud/core/issues/15567 -> IE8 support is dropped for 9.0 -> this is not scheduled -> closing.
