### ISSUE TITLE
Error occurred while changing recovery password on OC 8.1.3

### ISSUE THREAD

**Issue by danielkoch** [owncloud/core#19571]
### Steps to reproduce
1. Run OC 8.1.3 (upgrading from 8.1.1)
2. Open Browser Developer Tools (Network tab or console)
3. Call Admin panel DOMAIN/index.php/settings/admin
4. Change Recovery password
### Expected behaviour

No errors in admin panel:
https://DOMAIN/index.php/settings/admin when changing the recovery password 
### Actual behaviour

POST to https://DOMAIN/apps/encryption/ajax/changeRecoveryPassword
Shows the following Error:
POST https://DOMAIN/apps/encryption/ajax/changeRecoveryPassword 503 (Service Unavailable)
Uncaught SyntaxError: Unexpected token < (I think this is because of the non-JSON response)
### Server configuration

**Operating system**:
CentOS

**Web server:**
Apache 2

**Database:**
MySQL

**PHP version:**
5.5.15

**ownCloud version:** (see ownCloud admin page)
8.1.3

**Updated from an older ownCloud or fresh install:**
Update from 8.1.1

**List of activated apps:**
- activity: 2.0.2
- calendar: 0.7.3
- contacts: 0.4.0.0
- encryption: 1.0.0
- files: 1.1.10
- files_pdfviewer: 0.7
- files_sharing: 0.6.2
- files_texteditor: 0.4
- gallery: 0.6.1
- templateeditor: 0.1
- updater: 0.6
### Client configuration

Chrome (current)

**Operating system:**
Mac OS X
#### Web server error log

No logs
#### ownCloud log (data/owncloud.log)

No Logs
#### Browser log

The network tab or console:
POST https://DOMAIN/apps/encryption/ajax/changeRecoveryPassword 503 (Service Unavailable)
Uncaught SyntaxError: Unexpected token

Maybe there is a link to #18229

**Comment by schiesbn** [comment]
I can't reproduce it. I don't get any error message and after changing the recovery key password I could also reset a user password with the new recovery key password.

**Comment by danielkoch** [comment]
I now? What can I do?

**Comment by schiesbn** [comment]
you could try to enable debug mode and increase the log level by adding to your config.php (or update the existing values):

````
'debug' => true,
'loglevel' => 0,
````

Then try again and check if you have anything in your owncloud.log or apache error log.

**Comment by MorrisJobke** [comment]
> 'debug' => true,

This won't work in 8.1.x (was added in 8.2) - please use:

```
define('DEBUG', true);
```
https://github.com/owncloud/core/blob/stable8.1/config/config.sample.php#L27

**Comment by cmonteroluque** [comment]
@danielkoch can you please try and let us know?

**Comment by danielkoch** [comment]
I set activate the Debug-Mode. No entry. Checked the owncloud.log and the Apache log.

**Comment by PVince81** [comment]
"Uncaught SyntaxError: Unexpected token"

Looks like you have a syntax error in the code ?!

How did you upgrade ? Did you delete the old source code before replacing ?

**Comment by danielkoch** [comment]
I used the update app.

**Comment by danielkoch** [comment]
Upgraded to version 8.2.1 (without the updater app). Same error.

**Comment by danielkoch** [comment]
One additional information. I look into the response of the first request that returns a 503 (https://DOMAIN/apps/encryption/ajax/changeRecoveryPassword):
```
Encryption library: Decryption (symmetric) of content failed: error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length
```
It is a html error page, this is why I get a JavaScript error says "Unexpected token <" because the ajax requests expects a JSON response.

**Comment by schiesbn** [comment]
I just tried it again and still can't reproduce it. But by looking at the URL in more detail I see the problem:

````
POST https://DOMAIN/apps/encryption/ajax/changeRecoveryPassword 503 (Service Unavailable)
````

The correct URL for the ajax request is: ````http://DOMAIN/index.php/apps/encryption/ajax/changeRecoveryPassword````

the index.php is missing in your path. The URL for the ajax call gets generated here: https://github.com/owncloud/core/blob/v8.1.3/apps/encryption/js/settings-admin.js#L65 and as you can see here OC.generateUrl() should add a "index.php" https://github.com/owncloud/core/blob/v8.1.3/core/js/js.js#L151

Can you check that you have the right files and the right code at this places?

**Comment by cmonteroluque** [comment]
@danielkoch we'd like to resolve this if possible this week, can you provide us with the additional info? thanks!

**Comment by danielkoch** [comment]
@schiesbn: I double-check the code-lines. The javascript is the same. Also the requests url is:
https://DOMAIN/index.php/apps/encryption/ajax/changeRecoveryPassword (I forgot the index.php, corrected the comment above). Meanwhile I am on version 8.2.1. But with the same result.

**Comment by schiesbn** [comment]
@danielkoch thanks for checking. This also confuses me a bit https://github.com/owncloud/core/issues/19571#issuecomment-160519152, the encryption error looks like ownCloud tried to decrypt your recovery key with the old password and failed. But the 503 indicate that it already failed earlier if something during encryption/decryption fails you should get a 400.

Can you create a dummy user with a few files, recovery key enabled and recover the users files with the user management? Does this works? I just want to make sure that the recovery key is not broken and that you have the right password.

**Comment by danielkoch** [comment]
I created a test-user and try to change the password (as admin) – I get also a 503 – Failed to load resource: the server responded with a status of 503 (Service Unavailable) – https://DOMAIN/index.php/settings/users/changepassword

**Comment by SergioBertolinSG** [comment]
Just tried with stable8.1, no problem found.
The request points to
index.php/apps/encryption/ajax/changeRecoveryPassword
and returns 200.

**Comment by PVince81** [comment]
@danielkoch do you have any external storages ? I'm still wondering about that 503... it shouldn't even be possible to happen with this code path. Some 503 are thrown by unavailable external storages, so I wonder if this is what is happening here.

**Comment by schiesbn** [comment]
Still have no idea how to get a 503 in this case. I also tried to manipulate the recovery key to cause a decryption error while decrypting the recovery key with the old password but even then you get a defined error message that ownCloud couldn't decrypt the key.

**Comment by PVince81** [comment]
@danielkoch okay, I see your report doesn't have files_external enabled.
It is still strange that you don't have anything in the log. Did you try setting "loglevel" to 0 ?
Also you might be able to find some clues inside the HTML page that is returned for the ajax call, it might contain a more detailed error message / stack trace ?

**Comment by danielkoch** [comment]
No files_external active, right. I set loglevel to 0. No entry. The only error I get can be found in the respond of the (html error) page. I posted the content in this this [comment] (https://github.com/owncloud/core/issues/19571#issuecomment-164161397)

**Comment by danielkoch** [comment]
Same behavior with oc 8.2.2

**Comment by cmonteroluque** [comment]
change milestone to 8.2.3. @schiesbn

**Comment by danielkoch** [comment]
Same behavior with oc 8.2.3

**Comment by PVince81** [comment]
@owncloud/encryption

**Comment by jknockaert** [comment]
Maybe a php timeout?

**Comment by danielkoch** [comment]
I Get the same error on 9.1.0. I tried to investigate again. Meanwhile I think it's not related to the `changeRecoveryPassword`. The root cause may be https://github.com/owncloud/core/issues/19571#issuecomment-160519152

**Comment by vegas23** [comment]
Getting same thing after a password reset. Not sure how to provide the kind of details you all have been talking about, not a developer. I did see in the console that message:

index.php/apps/encryption/ajax/updatePrivateKeyPassword 503 (Service Unavailable)
`Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (settings-personal.js?v=6c7c433…:22)
    at j (jquery.js:3099)
    at Object.fireWith [as rejectWith] (jquery.js:3211)
    at x (jquery.js:8266)
    at XMLHttpRequest.<anonymous> (jquery.js:8605)
(anonymous)	@	settings-personal.js?v=6c7c433…:22
j	@	jquery.js:3099
fireWith	@	jquery.js:3211
x	@	jquery.js:8266
(anonymous)	@	jquery.js:8605`

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.
