### ISSUE TITLE
Cron job doesn't clean up tmp files

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#19578]
Copy of https://github.com/owncloud/core/issues/17748#issuecomment-145131001:

--

Re-opening due to cron showing files timestamped in the future.

```
lib/private/cache/file.php: $result = $storage->touch($key, time() + $ttl);
lib/private/cache/fileglobal.php: return touch($cache_dir.$key, time() 
+ $ttl);
```

As long as these future dated files don't fill up the filesystem, this can be ignored.

However, yesterday the system ran itself out of inodes again as a result of the other files left behind by the cronjob script.

Narrowed the ldap base user and base group trees in the advanced config and enabled apc caching on the command line to see if this helps with the problem.  Since the cronjob seems to randomly fail to cleanup  and fills up the filesystem,  I can't say its working until its been 
stable for longer than a week.

@MorrisJobke

**Comment by MorrisJobke** [comment]
@gig13 

* What files are created? And you said the mtime of those files is in the future?
* Anything related in the owncloud.log?
* How often is cron run?
* On what ownCloud version are you?

**Comment by gig13** [comment]
OC 7.0.10 version

Files left behind are
```

-rw-r--r--. 1 apache apache 16 Oct 24 2015
LDAP-Proxy-fd4ab49a709be163d72fdd80a63a4045
-rw-r--r--. 1 apache apache 16 Oct 24 2015
LDAP-Proxy-fd5274e2643a2bb7d68b2003016d00eb
-rw-r--r--. 1 apache apache 16 Oct 25 2015
LDAP-Proxy-fd8edfce74fd64a3b6e2e7648f3e71ab
-rw-r--r--. 1 apache apache 16 Oct 25 2015
LDAP-Proxy-fdb359b6f2d0782d6023d40ffdec7f3c
-rw-r--r--. 1 apache apache 16 Oct 24 2015
LDAP-Proxy-fdcd9854637d2fe0c0a4deafeeaba346
-rw-r--r--. 1 apache apache 16 Oct 24 2015
LDAP-Proxy-fe0e316eed04e33dba259e5fef1eeba2
-rw-r--r--. 1 apache apache 16 Oct 25 2015
LDAP-Proxy-fe14a67d4c2d86d4b92167c16c55ff64
-rw-r--r--. 1 apache apache 16 Oct 24 2015
LDAP-Proxy-fe764d59f77ddd3882055e54ca6b1f94
-rw-r--r--. 1 apache apache 16 Oct 25 2015
LDAP-Proxy-fe9eec0985bef55a5022ef329a6410ff
-rw-r--r--. 1 apache apache 16 Oct 24 2015
LDAP-Proxy-ff2c5191a62759ee915a464cd5b40968
-rw-r--r--. 1 apache apache 16 Oct 24 2015
LDAP-Proxy-ff81969df7ad234512e6a130f992d11c
```

Nothing of not in the owncloud.log

Checking how often the cron ran.

**Comment by MorrisJobke** [comment]
It seems that this is the old user_ldap file cache implementation. (ownCloud 7)

@blizzz Do you know from any cleanup issues? Back in stable7 user_ldap always used the file cache: https://github.com/owncloud/core/blob/stable7/lib/private/cache.php#L27-27

Then later it was switched to the configured memory cache.

**Comment by gig13** [comment]
@blizzz @MorrisJobke 
Is the recommendation to move to OC8? If the OC7 can be patched in the meantime, that would be great, otherwise, what else would be an acceptable workaround? Can we setup a cron to delete any of these files?

**Comment by blizzz** [comment]
> @blizzz Do you know from any cleanup issues? Back in stable7 user_ldap always used the file cache: https://github.com/owncloud/core/blob/stable7/lib/private/cache.php#L27-27

Nope. Would not be LDAP related anyway, but a thingy in the file cache implementation. IIRC not many components were using the file cache mechanism anyway, so it falls down to LDAP.

> Is the recommendation to move to OC8?

The switch to APCu should help, too, I think.

> Can we setup a cron to delete any of these files?

Unneeded files are supposed to be cleaned up automatically by the file cache implementation, actually.

**Comment by gig13** [comment]
Closing -- waiting for additional information.
