### ISSUE TITLE
"file already exists" error message is not shown completely

### ISSUE THREAD

**Issue by rperezb** [owncloud/core#19579]
### Steps to reproduce
1. Upload "photo.jpg" to the server
2. Upload another photo with the same name ("photo.jpg")
3. In the folder, there are two files ("photo.jpg" and "photo (2).jpg")
4. Rename "photo (2).jpg" as "photo.jpg"
5- An alert message is shown "photo.png already exists"

### Expected behaviour
The alert message is readable completely

### Actual behaviour
Error message, "fileXx already exists" is not shown completely
![screen shot 2015-10-05 at 11 29 58](https://cloud.githubusercontent.com/assets/1846927/10277238/ed30c75a-6b54-11e5-90a6-bed5041d673b.png)

### Server configuration
Operating system: MacOS 

ownCloud 8.2 beta1 (daily) Build:2015-10-02T03:39:51+00:00 f891b91cf8475eee16ab1ca08869430bd2dbe51b 

Browser: Chrome and FF

**Comment by PVince81** [comment]
Huh?! This message should be on the right

**Comment by rperezb** [comment]
Nice!
