### ISSUE TITLE
Replace existing remote share user interaction to interactive notifications

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#19587]
As an admin, I want to be able to have users accept remote share links with an interactive notification so that only desired content is shared among users across instances.

(We are moving accept remote shares to an interactive dialog, and to replace the current implementation)

Acceptance Criteria:
- Migrate the code to the new interactive notifications
- Note: If notification app is off, remote shares cannot be accepted.

**Comment by schiesbn** [comment]
> Note: If notification app is off, remote shares cannot be accepted.

Unless we implement this as well, which I think is something we should have independent from this feature: https://github.com/owncloud/core/issues/13495

**Comment by nickvergessen** [comment]
In order to bring back notifications, the following commit has to be reverted:
https://github.com/owncloud/core/commit/6bc93c740194d245bb9a7d1f230ed33461f842a7

**Comment by PVince81** [comment]
- doc: https://github.com/owncloud/documentation/issues/2153
- QA: https://github.com/owncloud/QA/issues/130
