### ISSUE TITLE
Repair step to remove bogus shares from old group memberships

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#19583]
See https://github.com/owncloud/core/issues/19541 and https://github.com/owncloud/core/issues/14384

Write a repair step (or add a case in "RepairInvalidShares") that iterates over all group shares and remove all sub-share entries for users who do not belong to that group any more.

**Comment by PVince81** [comment]
Either a repair step or a background job depending on how expensive it is.

Ideally this situation should never happen once both tickets above are fixed, so I suggest a repair step instead.

**Comment by rullzer** [comment]
Yes repair step please. As you mention it *should* never happen. But if it does it can be a pretty expensive job involving a lot of queries. Would not be wise to fire that of every day ;)

However, this could (I think) be a "live" repair job.. as to not slow down the upgrade process significantly on large installation.

**Comment by cmonteroluque** [comment]
@nickvergessen @PVince81 the PR is marked 9.0. Is this 8.2.1?

**Comment by nickvergessen** [comment]
Well the PR is 9.0 because it goes against master.
If we want this to be fixed in 8.2.1, we backport it, after it was merged, for which we create a new PR that has the milestone of 8.2.1
