### ISSUE TITLE
checkExistingFiles doesn't work for folders

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19581]
The check done to see if files already exist before uploading a list of files/folders doesn't work for folders.
This is quite important since folders are likely to contain a lot of files.

In `var fileInfo = fileList.findFile(upload.files[0].name);`, the name only contains the filename, not the full path. It needs to be combined with relativePath, if it exists.

https://github.com/owncloud/core/blob/1d8c10cf638fb954d1cc20c47ad46e697a18e9e4/apps/files/js/file-upload.js#L189

---
@PVince81 @MorrisJobke @rullzer

**Comment by PVince81** [comment]
Did folder overwrite work before ? I'm not sure, I seem to remember issues.

So basically the scenario is as follows:
1. File tree is:
    - file1.jpg
    - file2.jpg
    - somefolder
    - somefolder/inside1.jpg
    - somefolder/inside2.jpg
1. User has the drags the following files into the Chrome windows (folder upload only works in Chrome):
    - file1.jpg
    - somefolder
    - somefolder/inside1.jpg
    - somefolder/inside3.jpg
1. The conflict dialog should show the following conflicts:
    - file1.jpg
    - somefolder/inside1.jpg

Not sure whether this ever worked properly before.

**Comment by oparoz** [comment]
I have no idea if it ever worked. All I know is that it doesn't now :) . Thanks for the use case, it will help trying to figure out if this is fixable.

**Comment by oparoz** [comment]
It's fixable and makes operations much faster in case of a mistake :)

**Comment by PVince81** [comment]
Thing is, I don't want the new client-side conflict-checking code to retrieve the contents of the folder just to find the conflicts in it. The backend already does that.

**Comment by oparoz** [comment]
Argh, of course... It's working in Gallery because I have some thumbnails of sub-folders, but it's not going to work without the full list.

So I think we can close this as "won't fix" as building a fileInfo[] for all sub-folders is going to slow things down too much.
