### ISSUE TITLE
Load mobile styles after other styles

### ISSUE THREAD

**Issue by Henni** [owncloud/core#19596]
Reordering the stylesheets so that `mobile.css` is loaded after the desktop styles allows us to clean up the mobile stylesheet.

Currently 19 of the 61 rules in `mobile.css` contain `!important` which is code smell.
If the stylesheet would be loaded later than others like `apps.css`, most (if not all) of the `!important` could be removed.

**Comment by PVince81** [comment]
Makes sense.

CC @jancborchardt

**Comment by jancborchardt** [comment]
Yes, great call. Mobile styles should of course be last to load.

**Comment by jancborchardt** [comment]
Where is the order of this decided @PVince81 @DeepDiver1975?

**Comment by PVince81** [comment]
Just grep the code for "mobile": https://github.com/owncloud/core/blob/v9.0.0/lib/private/template.php#L115

**Comment by jancborchardt** [comment]
Thanks! I grepped, but didn’t know in which file. ;)
