### ISSUE TITLE
./occ command feature request - stat output on scanning

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#19593]
@oparoz has written a great ./occ command where you can create thumbnails in advance. See PR https://github.com/owncloud/gallery/pull/387

Part of his work was, that he prints a statistic of the work done, see his example below.
![image](https://cloud.githubusercontent.com/assets/3321281/10284819/32f1d988-6b86-11e5-9891-7e84d83f72b2.png)
My request is now, if that kind of statistic could also be generated for the ./occ files commands as this would be very useful.

**Comment by DeepDiver1975** [comment]
Pull requests are welcome - THX

**Comment by PVince81** [comment]
Implemented in https://github.com/owncloud/core/issues/21201
