### ISSUE TITLE
Federated cloud sharing: No Notification of invalid shares through self signed ssl certs.

### ISSUE THREAD

**Issue by JKawohl** [owncloud/core#19599]
Steps to reproduce

1.Have two owncloud instances running one with a self signed ssl cert. 
2.Share a folder or file from one to another

Expected behaviour

Share should appear in remote cloud of user shared with.., or if the share is not possible because the remote server doesn't trust the self signed cert there should be a popup. 
The Popup should inform the user that the share is not possible because of the "not trusted cert" or similar.

Actual behaviour

No Warning, file is not shared.

**Comment by schiesbn** [comment]
probably the popup should allow the user to directly accept the certificate.

@LukasReschke I think you already suggested something similar? Do you want to give it a try?

**Comment by atroxix** [comment]
I think this needs to be also possible on "server" level, eg. from Admin settings.
