### ISSUE TITLE
Owncloud update issue

### ISSUE THREAD

**Issue by MaxTorque1** [owncloud/core#19608]
I am trying to update my owncloud server (Linux Ubuntu server) via the web interface on a windows 10 desktop computer. The update is from version 8.0.4 to 8.1.3. The update process gets as far as creating a backup. It then advises me that the update is unsuccessful due to the following:
 'Exception: Please upload the ca-bundle.crt file into the 'config' directory.'

To be honest, I have no idea what that means or how I would do it. Any help will be gratefully received, thank you

**Comment by RealRancor** [comment]
Hi,

dup of https://github.com/owncloud/core/issues/19551, https://github.com/owncloud/core/issues/19204 and https://github.com/owncloud/updater/issues/164 (should be available on the github search).

See https://github.com/owncloud/updater/issues/164#issuecomment-141549254 how to fix.
