### ISSUE TITLE
ownCloud .deb/.rpm packages. Strong file/directory permissions as default.

### ISSUE THREAD

**Issue by julenl** [owncloud/core#19618]
As we are all more or less concerned about security, the official documentation recommends setting strong file/directory permissions on the owncloud directory.
https://doc.owncloud.org/server/8.0/admin_manual/installation/installation_wizard.html#setting-strong-directory-permissions

Why not to set those permissions the right way already in the package? This would also solve the overwrite issue with the updates.

**Comment by PVince81** [comment]
@jnweiger any reason why it's not done on the package already ?

**Comment by jnweiger** [comment]
Permissions were much stronger half a year ago. That increased the number of big reports. In response to that, permissions were gradually relaxed.

Can you give details about the overwrite issue?
I'd expect such issues when permissions are too tight.

**Comment by PVince81** [comment]
Closing due to lack of feedback.
