### ISSUE TITLE
NaN error message when changing quota

### ISSUE THREAD

**Issue by gig13** [owncloud/core#19613]
### Steps to reproduce
1. Setup OC 7.0.5.2
2. Set the primary storage to an Amazon NFS mounted EBS
3. Attempt to Change the quota

### Expected behaviour
An admin should be able to change the quota. If an error occurs, it should be a useful message for the end user.

### Actual behaviour
When changing the quota, a poorly handled error is propagated to the end user.

<img width="561" alt="quotaerror" src="https://cloud.githubusercontent.com/assets/4803385/10315200/d66fcd86-6c26-11e5-8f91-b915bfa4955f.png">

### Server configuration
**Operating system**: Ubuntu

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.5.9-1ubuntu4.7

**ownCloud version:** 7.0.5.2

**Updated from an older ownCloud or fresh install:** Updated

**List of activated apps:** See config report on S3

**Are you using external storage, if yes which one:** NO

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration 
See Config Report

#### ownCloud log 
To obtain

@tariqsiddiqui @MorrisJobke

**Comment by MorrisJobke** [comment]
I remind that something similiar was fixed some time back. This is a 7.0.5 and 7.0.10 is the current one. Could already be fixed...

**Comment by gig13** [comment]
@MorrisJobke 
I saw similar issues, but wanted to confirm before forcing an upgrade.

**Comment by MorrisJobke** [comment]
Fixed in 8.1 and 8.0.2 - #9342

**Comment by MorrisJobke** [comment]
And for stable7 we are in the "security fixes only" phase.

**Comment by gig13** [comment]
@bboule 
Can this be back ported to OC7.0.x?

**Comment by MorrisJobke** [comment]
> Can this be back ported to OC7.0.x?

As this is not a security related bug: I don't think so.

**Comment by bboule** [comment]
We am should discuss as this may need to happen

**Comment by DeepDiver1975** [comment]
> We am should discuss as this may need to happen

Not much to be discussed - https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule#minor-releases---maintenance-releases

@cmonteroluque

**Comment by bboule** [comment]
Lets not live in a black in white world (we sometimes lose that luxury when we deal with paying customers).  While I understand what is written in the policy that you have posted (and we try to abide by that policy), I think these are exceptions that warrant discussion.  We have a set of circumstances here that prevents an upgrade on the customer side (time needed for testing of new versions, complexity of setup etc.) and asking them to live with this is a tall order... we should discuss vs. dismiss out of hand....  Please note I am not trying to set any type of precedent here I understand this is exception only...

@cmonteroluque perhaps we could discuss is a back port of this fix out of the question for reasons other than "policy"?? i.e. is it simply too much work? If it is we will deliver that message but I am hoping to discuss?

**Comment by MorrisJobke** [comment]
> @cmonteroluque perhaps we could discuss is a back port of this fix out of the question for reasons other than "policy"?? i.e. is it simply too much work? If it is we will deliver that message but I am hoping to discuss?

Let me check how hard this is.

**Comment by tflidd** [comment]
7.0.0 was released in June 2014. The fix was in Jan/Feb 2015, shouldn't it be in the bug/security fix cycle (7-12 months)?
@bboule If it is so important, you could even consider applying the patch yourself (only a 3 lines are changed)

**Comment by MorrisJobke** [comment]
> @bboule If it is so important, you could even consider applying the patch yourself (only a 3 lines are changed)

The problem is, that we also need to check for possible side effects.

**Comment by cmonteroluque** [comment]
@bboule let's talk.

**Comment by MorrisJobke** [comment]
Backport is in #19626

**Comment by cmonteroluque** [comment]
@gig13 can you test this? From my conversation with @bboule

**Comment by gig13** [comment]
@gig -- No lab = no testing

**Comment by bboule** [comment]
Yes we can test  thank you @cmonteroluque

**Comment by MorrisJobke** [comment]
Fix is merged to 7.0.11
