### ISSUE TITLE
[Sharing by link] Text files are not downloaded right. Instead the file, a .rar with a folder is downloaded. 

### ISSUE THREAD

**Issue by davitol** [owncloud/core#19614]
### Steps to reproduce

1. Create a text file
2. Click on share icon (sidebar is shown)
3. Share the file via link
4. Paste the link in another browser
5. Try to download the file

### Expected behaviour
A .txt should be download

### Actual behaviour
A .rar file is downloaded and it contains an empty folder named as the text file

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** ownCloud Enterprise Edition 8.2 RC1 (daily) Build:2015-10-07T03:08:55+00:00 648b86abdd3c6610716a418cd52d8e4186ae11b2

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Firefox and Chrome

**Comment by PVince81** [comment]
Bisect time

**Comment by PVince81** [comment]
Confirmed on master, in my case it's a zip file

**Comment by davitol** [comment]
Yes, It is due to you work on Windows. On OSX rar file appears

**Comment by PVince81** [comment]
I don't work on Windows :wink:

**Comment by davitol** [comment]
:speak_no_evil:

**Comment by PVince81** [comment]
Caused by be46cd6737f7b4414d4583d0096d90b73929ce3d from the zip lock fix: https://github.com/owncloud/core/pull/19407
@DeepDiver1975

**Comment by PVince81** [comment]
Single file download from the file list (regular list and public link) works fine.
So it's really only the "single file share public link download" that is broken.

**Comment by jvillafanez** [comment]
I guess this is what I'm seeing with the upgrades to 8.2RC1. The hash for the shared file after the upgrade is different.

**Comment by PVince81** [comment]
This issue here doesn't have anything to do with the share hash.

**Comment by jvillafanez** [comment]
To be clearer, I'm hashing the file locally to verify the downloaded file is the same than the one I've uploaded. I'm not saying the hash stored in the ownCloud filecache is modified or anything, just the downloaded file isn't the expected one.

**Comment by PVince81** [comment]
Ah ok, I thought you were talking about the hash in the public share URL.

**Comment by DeepDiver1975** [comment]
> The hash for the shared file after the upgrade is different.

we are talking about a text file? And Windows is involved? Most probably some \n\r \n :hankey:

**Comment by DeepDiver1975** [comment]
I'll have a look at this

**Comment by jvillafanez** [comment]
No windows in my case

**Comment by nickvergessen** [comment]
> we are talking about a text file? And Windows is involved? Most probably some \n\r \n :hankey:

@DeepDiver1975 no, any text file is (when downloaded directly) downloaded as an archive instead of directly.

**Comment by davitol** [comment]
OSX => as .tar file
Windows, Linux => as .zip file

In all cases the compress file contains a folder named as the text file, and this folder is empty

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 no, any text file is (when downloaded directly) downloaded as an archive instead of directly.

yes - I'm talking about the has missmatch .. anyway - I'll look into the issue
