### ISSUE TITLE
[IE9] actions menu icon garbled

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#19629]
While IE8 is working fine now, IE9 decided to not show the file actions menu properly.

### Steps

1. Upload a file in IE9
1. Click on the three dots "..."
1. Look at the icons and feel sad

**Comment by PVince81** [comment]
CC @davitol who likes broken IE9 stuff

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/19630

**Comment by PVince81** [comment]
Duplicate of https://github.com/owncloud/core/issues/19290

**Comment by davitol** [comment]
:+1: Great!
