### ISSUE TITLE
Ubuntu package upgrade from 8.1.3 to 8.2RC1 ignores provides line

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#19622]
### Steps to reproduce
1. Install OC 8.1.3 from packages
2. Upgrade to 8.2RC1 from packages

### Expected behaviour
The upgrade is done smoothly

### Actual behaviour
Warning messages appears during the upgrade

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** 8.2RC1

**Updated from an older ownCloud or fresh install:** update from 8.1.3

```
INFO Ign http://download.opensuse.org  InRelease
INFO Ign http://archive.ubuntu.com trusty InRelease
INFO Get:1 http://download.opensuse.org  Release.gpg [189 B]
INFO Get:2 http://download.opensuse.org  Release [1054 B]
INFO Ign http://archive.ubuntu.com trusty-updates InRelease
INFO Ign http://archive.ubuntu.com trusty-security InRelease
INFO Get:3 http://download.opensuse.org  Packages [5134 B]
INFO Hit http://archive.ubuntu.com trusty Release.gpg
INFO Hit http://archive.ubuntu.com trusty-updates Release.gpg
INFO Hit http://archive.ubuntu.com trusty-security Release.gpg
INFO Hit http://archive.ubuntu.com trusty Release
INFO Hit http://archive.ubuntu.com trusty-updates Release
INFO Hit http://archive.ubuntu.com trusty-security Release
INFO Hit http://archive.ubuntu.com trusty/main Sources
INFO Hit http://archive.ubuntu.com trusty/restricted Sources
INFO Hit http://archive.ubuntu.com trusty/universe Sources
INFO Hit http://archive.ubuntu.com trusty/main amd64 Packages
INFO Hit http://archive.ubuntu.com trusty/restricted amd64 Packages
INFO Hit http://archive.ubuntu.com trusty/universe amd64 Packages
INFO Hit http://archive.ubuntu.com trusty-updates/main Sources
INFO Hit http://archive.ubuntu.com trusty-updates/restricted Sources
INFO Hit http://archive.ubuntu.com trusty-updates/universe Sources
INFO Hit http://archive.ubuntu.com trusty-updates/main amd64 Packages
INFO Hit http://archive.ubuntu.com trusty-updates/restricted amd64 Packages
INFO Hit http://archive.ubuntu.com trusty-updates/universe amd64 Packages
INFO Hit http://archive.ubuntu.com trusty-security/main Sources
INFO Hit http://archive.ubuntu.com trusty-security/restricted Sources
INFO Hit http://archive.ubuntu.com trusty-security/universe Sources
INFO Hit http://archive.ubuntu.com trusty-security/multiverse Sources
INFO Hit http://archive.ubuntu.com trusty-security/main amd64 Packages
INFO Hit http://archive.ubuntu.com trusty-security/restricted amd64 Packages
INFO Hit http://archive.ubuntu.com trusty-security/universe amd64 Packages
INFO Hit http://archive.ubuntu.com trusty-security/multiverse amd64 Packages
INFO Fetched 6377 B in 3s (1616 B/s)
INFO Reading package lists...
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-3rdparty
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-activity
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-encryption
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-external
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-files
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-files-encryption
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-files-external
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-files-locking
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-files-pdfviewer
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-files-sharing
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-files-texteditor
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-files-trashbin
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-files-versions
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-files-videoviewer
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-firstrunwizard
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-gallery
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-provisioning-api
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-templateeditor
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-updater
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-user-external
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-user-ldap
WARNING W: Ignoring Provides line with DepCompareOp for package owncloud-app-user-webdavauth
WARNING W: You may want to run apt-get update to correct these problems
```

**Comment by jnweiger** [comment]
Next rebuild 8.2~RC1-3.1 should have that fixed. Please test again.

**Comment by Kawohl** [comment]
Tested and passed.

**Comment by jvillafanez** [comment]
:+1:

**Comment by jnweiger** [comment]
Thanks!

**Comment by adebruyn-abit** [comment]
Hi,

I still have this issue with Debian Jessie and 8.2:

# dpkg -l |grep owncloud
ii  owncloud                       8.2.0-2.1                    all          The ownCloud Server - Private file sync and share server
ii  owncloud-config-apache         8.2.0-2.1                    all          The ownCloud configuration for the apache web server
ii  owncloud-server                8.2.0-2.1                    all          The owncloud-server package

# /var/www/owncloud/occ upgrade
Console has to be executed with the user that owns the file config/config.php
Current user: root
Owner of config.php: www-data
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.oc_file_locks' doesn't exist' in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91
Stack trace:
#0 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(Array)
#1 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(989): Doctrine\DBAL\Driver\PDOStatement->execute(Array)
#2 /var/www/owncloud/lib/private/db/connection.php(203): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM `oc...', Array, Array)
#3 /var/www/owncloud/lib/private/lock/dblockingprovider.php(184): OC\DB\Connection->executeUpdate('DELETE FROM `*P...', Array)
#4 /var/www/owncloud/lib/private/lock/dblockingprovider.php(189): OC\Lock\DBLockingProvider->cleanEmptyLocks()
#5 [internal function]: OC\Lock\DBLockingProvider->__destruct()
#6 {main}

Next exception 'Doctrine\DBAL\Driver\PDOException' with message 'SQLSTATE[42S in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 53

Thanks for your help.

**Comment by MorrisJobke** [comment]
cc @nickvergessen Didn't you wrote something about this some yesterday?

**Comment by MorrisJobke** [comment]
> cc @nickvergessen Didn't you wrote something about this some yesterday?

Shouldn't this be solved by https://github.com/owncloud/core/pull/19644

**Comment by nickvergessen** [comment]
It's solved by https://github.com/owncloud/core/pull/19893
The previous patch was incomplete

**Comment by adebruyn-abit** [comment]
Ok thanks, problem solved.
