### ISSUE TITLE
Can't upload files large than 8192 bytes to owncloud 8.1.3

### ISSUE THREAD

**Issue by Aikhjarto** [owncloud/core#19621]
Since the last update to 8.1.3 I cannot upload files larger than 8192. Files smaller than 8kB work fine thou. Sync client version i 2.0.1.
Seems to me that file chunking is broken as this would possible kick in for files larger than 8kB.
Error message from the log is as follows:

<10>Oct  7 13:48:54 ownCloud[10493]: {webdav} Exception: {"Message":"HTTP\/1.1 400 expected filesize 8193 got 0","Code":0,"Trace":"#0 \/pub\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1087): OC\\Connector\\Sabre\\File->put(Resource id #255)\n#1 \/pub\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(501): Sabre\\DAV\\Server->updateFile('clientsync\/a.tx...', Resource id #255, NULL)\n#2 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#3 \/pub\/www\/htdocs\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#4 \/pub\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#5 \/pub\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#6 \/pub\/
 www\/htdocs\/owncloud\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n#7 \/pub\/www\/htdocs\/owncloud\/remote.php(132): require_once('\/pub\/www\/htdocs...')\n#8 {main}","File":"\/pub\/www\/htdocs\/owncloud\/lib\/private\/connector\/sabre\/file.php","Line":144}

**Comment by DeepDiver1975** [comment]
@Aikhjarto can you provide the client logs as well?

Information about the server and the client is welcome as well:

https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#submitting-issues

**Comment by Aikhjarto** [comment]
Of course I can provide more information. Server is an apache 2.4 with php 5.6 running on openSUSE 13.1. Apps are mostely disabled:
```
# sudo -u wwwrun php occ app:list
Enabled:
 - files: 1.1.10
 - files_external: 0.2.3
 - files_sharing: 0.6.2
 - files_trashbin: 0.6.3
 - updater: 0.6
```

Clients are running openSUSE Tumbleweed and Windows 10.


Client log extracted from from my Tumbleweed machine:
```
10-07 14:13:58:718 14547 OCC::SyncJournalErrorBlacklistRecord::update: blacklisting  "a.txt"  for  25 , retry count  1
10-07 14:13:58:718 14547 OCC::SyncJournalDb::updateErrorBlacklistEntry: set blacklist entry for  "a.txt" 1 "Error downloading https://owncloud.wa2.eu:83/remote.php/webdav/clientsync/a.txt - server replied: Bad Request (expected filesize 8193 got 0)" 1444220038 25 1444220028 "0515db384b87076718906191cfd87c02"
10-07 14:13:58:718 14547 OCC::SyncEngine::slotItemCompleted: void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "a.txt" INSTRUCTION_SYNC 2 "Error downloading https://owncloud.wa2.eu:83/remote.php/webdav/clientsync/a.txt - server replied: Bad Request (expected filesize 8193 got 0)"
10-07 14:13:58:741 14547 OCC::SyncEngine::slotItemCompleted: void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "" INSTRUCTION_NONE 0 ""
10-07 14:13:58:746 14547 OCC::SyncJournalDb::walCheckpoint: void OCC::SyncJournalDb::walCheckpoint() took 0 msec
10-07 14:13:58:746 14547 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "All Finished." 
```

**Comment by DeepDiver1975** [comment]
> Error downloading https://owncloud.wa2.eu:83/remote.php/webdav/clientsync/a.txt - server replied: Bad Request (expected filesize 8193 got 0)"

error downloading?  the server logs says it's a PUT??

@dragotin can one of the desktop guys have a look here? THX

**Comment by Aikhjarto** [comment]
Digged around a bit further: Uploading via Webinterface (used firefox and chrome on both, openSUSE Tumbleweed and Windows 10) doesn't work for files large than 8192 bytes either.
Error message in the browser (yellow bar in the owncloud tab) is: "Das Upload-Verzeichnis konnte nicht gesetzt werden."
Smaller files can be uploaded.

**Comment by Aikhjarto** [comment]
Found the issue #3816 similar to mine.
I followed the suggestions there for setting apache's ```KeepAliveTimeout``` and ```SSLRenegBufferSize``` to large values. This did not change anything.
The workaround in #3816 to start the client with larger chunk size ```OWNCLOUD_CHUNK_SIZE=1048576 ./owncloud```or ```SSLStrictSNIVHostCheck off``` in apache's config  doesn't work either.

**Comment by Aikhjarto** [comment]
Yet another test: uploading files larger than 8k also won't work with the webdav interface remote.php/webdav
Tested with the Dolphin filebrowser on openSUSE Tumbleweed and the webdav client from Windows 10.
Same error on server side as in the first post.

**Comment by Aikhjarto** [comment]
Just tested with a fresh installation of owncloud 8.1.3, 8.1.2, 8.1.1, 8.1.0, and 8.0.8 on openSUSE 13.1 with apache 2.4 and mariadb 5.5 and php 5.4 and upload of files larger than 8k won't work either.
I also tried disabling SSL with no effect.
Is there any known incompatiblity with owncloud and the following versions of mine:
```console
test:~ # httpd2 -v
Server version: Apache/2.4.6 (Linux/SUSE)
Server built:   2015-09-23 13:45:33.000000000 +0000
test:~ # mysql --version
mysql  Ver 15.1 Distrib 5.5.45-MariaDB, for Linux (x86_64) using readline 5.2
test:~ # php --version
PHP 5.4.20 (cli)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies
test:~ #
```

**Comment by Aikhjarto** [comment]
Found something else: There was an apache patch regarding chunk header parsing:
https://bugzilla.suse.com/show_bug.cgi?id=938728

**Comment by Aikhjarto** [comment]
Found the solution: I seems an incompatibilty with apache 2.4.6 (at least the version that comes with openSUSE 13.1 per default).
Now I tested apache 2.4.10 and 2.4.16 and with both I was able to upload files larger than 8 kB.
