### ISSUE TITLE
OC/OCA is undefined on IE8

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19620]
![ie8_js_errors](https://cloud.githubusercontent.com/assets/323220/10336698/f1389358-6cfa-11e5-8bd0-830ae628fc94.png)

@PVince81 - Do we care?

cc @MTRichards

**Comment by PVince81** [comment]
@oparoz yes. It is likely that in that situation everything is broken, or at least all the functionality linked to these files.

Can you provide the steps to reproduce ?

**Comment by DeepDiver1975** [comment]
which co version is that?

**Comment by oparoz** [comment]
It's when listing files via a public share, but my problem is that that list doesn't seem to refresh... So I need to figure that out first in order to be able to pinpoint the problem.

**Comment by oparoz** [comment]
False alarm. That happens when enabling compatibility mode, which is probably unsupported.
Close this if I'm correct :)

**Comment by DeepDiver1975** [comment]
> False alarm. That happens when enabling compatibility mode, which is probably unsupported.

yes -compat mod is not supported -> closing
