### ISSUE TITLE
Endless notification - Activity

### ISSUE THREAD

**Issue by stevejordi** [owncloud/core#19639]
### Steps to reproduce
1.	Enable Activity App
2.	Link owncloud to an ActiveDirectory with about 3,500 users
3.	From one account, share one document/folder with a group including all 3,500 users

### Expected behaviour
Each user should receive 1 notification about the share (should those notifications be enabled)

### Actual behaviour
Each user receives 10 notifications every 7 minutes.
After 12 hours more than 40,000 notifications have been sent in an endless loop.
The only way we eventually found to stop the flood was to turn Activity off, and then enable it back.

### Question	
Is the number of users hard coded somewhere? Like 1024 or 2048?
With 3,500 I suspect we have an "overflow" problem endlessly looping with negative user counts
Just a hint?

### Server configuration
**Operating system**: CentOS 6.7

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 5.6.13

**ownCloud version:** 8.1.0

**Updated from an older ownCloud or fresh install:**
Fresh install

**List of activated apps:**
Enabled:
 - activity: 2.0.1
 - contacts: 0.4.0.0
 - files: 1.1.9
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - templateeditor: 0.1
 - updater: 0.6
 - user_ldap: 0.6.1
Disabled:
 - encryption
 - external
 - files_external
 - files_locking
 - provisioning_api
 - user_external
 - user_webdavauth

**Comment by PVince81** [comment]
@nickvergessen

**Comment by nickvergessen** [comment]
Will have a look

**Comment by nickvergessen** [comment]
Created 3.500 users in my database backend and couldn't find any issue.
So this seems to be a problem with the user backend.
The call we use to get the users is here:
https://github.com/owncloud/activity/blob/8a401847fad96e314553486c720d738de030a196/lib/fileshooks.php#L264-264

So it seems to be a problem within AD (LDAP), summoning @blizzz 
Could this be caused by https://github.com/owncloud/core/pull/19489 ?

**Comment by stevejordi** [comment]
I don’t know whether it’s related to the LDAP loops, 
but my guess is yes.
We sent about 80,000 messages before turning Activity off.

But the problem is that Activity tracking is something we have to give to the end users.
If it starts behaving like this again, we’ll have to disable it.

Steve

**Comment by blizzz** [comment]
Unlikely, that #19489 is related.

@stevejordi do you still see the issue today?

**Comment by stevejordi** [comment]
No
It was not related to LDAP groups, it is an Activity app bug.
We had to disable the activity plugin to stop sending emails. We sent about 400,000 of them for nothing.
Disable/Enable was enough to fix the problem, but too late.

**Comment by blizzz** [comment]
ok, thanks for letting us know!
