### ISSUE TITLE
Forgotten Share Link Password

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#19632]
As we have been using the share link with password a lot lately, we have discovered that sometimes we forget the password. However, the password has already been communicated to our 7 recipients so we can't send out a new password, we just want to send the password to an eighth participant. 

The question – can we put an eye on the share link password field so that we can see the password in case we forget it?

OR

Is the password stored hashed / encrypted and we don't actually know the password once it is stored?

**Comment by MTRichards** [comment]
@schiesbn @karlitschek

**Comment by MorrisJobke** [comment]
> Is the password stored hashed / encrypted and we don't actually know the password once it is stored?

:white_check_mark:

**Comment by MorrisJobke** [comment]
```
1|$2y$10$eHerd.xpvEfcTIU6CGX7vOB/Ljl615rab5bG.fW5NmrIr10jWST9G
1|$2y$10$BEzH3nNvzZjyshRvCsD24OEFAyi4VTWe2vL4CI60g9PbxsANH1HhS
```

Both are ways how `abc` as password can look like.

**Comment by rullzer** [comment]
As @MorrisJobke said we have no way to know the password since it hashed (as it should be btw).

@MTRichards but for sharing 2.0 there is a plan to introduce multiple link shares for a file/folder (with an alias for easy bookkeeping). That way you could hand out (or mail out) private links to users and thus also revoke acces... or just rest the password for a given link (which is then unique).

**Comment by MTRichards** [comment]
Concur this is how it should work, just wanted to check and make certain...

**Comment by MTRichards** [comment]
So the last question - we can probably add an eye for while you are typing it...because it isn't yet submitted. Can we do that?
(asking only at this point)

**Comment by rullzer** [comment]
Yes that would be possible. The password is hashed on the server side so while you are typing it can be shown.

**Comment by PVince81** [comment]
but once the password is set it is not possible to get it back from the DB. An eye icon would not help with that.

**Comment by PVince81** [comment]
@pmaier1
