### ISSUE TITLE
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_filecache ENGINE=InnoDB;': SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

### ISSUE THREAD

**Issue by BBagger** [owncloud/core#19637]
I get the above error when trying to update to Owncloud version 8.0.3 from version 8.0.1. What can I do?

**Comment by PVince81** [comment]
restart mysql

**Comment by RealRancor** [comment]
Also have a look at https://doc.owncloud.org/server/8.1/admin_manual/issues/index.html#common-problems-error-messages

**Comment by skironDotNet** [comment]
this helped https://help.nextcloud.com/t/solved-update-fails-because-of-database-error/21624
