### ISSUE TITLE
CloudSync on Synology

### ISSUE THREAD

**Issue by plgingembre** [owncloud/core#19641]
Hi,

I'm not sure that this is the most accurate place to post this type of query, so do not hesitate to move it in the appropriate directory...

I am a real fan of ownCloud and Synology features. I need to get a clear solution to have my users able to sync their files either on the cloud platform or on their Synology at home, but they want to have all of them synced on every platform.

I am using CloudSync app on Synology to sync some contents with Google Drive, OneDrive, Dropbox or hubiC, but I would love to see ownCloud from one of the suggested cloud provider in this app! You would have best of both worlds! A really fast access to your files at home even if you have a poor or low bandwidth connection to the Internet and a fast access to the same cloud files when you are leveraging your 3G/4G/LTE connection while moving outside.

I am not talking at the moment about the ability to cipher all the connections between both platforms, but I will post it later on a new feature request ;-).

I would love to read ownCloud community on this one...

Best!

**Comment by PVince81** [comment]
Hmmm, is this a feature request for CloudSync to work with ownCloud ? I don't know this app but it's not developed by this community. You might want to report this to the CloudSync project directly.

**Comment by plgingembre** [comment]
Hi Vincent,

Maybe you’re right, I thought it was interesting to see if there was something needed on ownCloud side to be « included » in this great Synology app.

Anyway, thanks a lot for your feedback

Best!

**Comment by PVince81** [comment]
I'm not familiar at all with CloudSync. If it's able to connect to Webdav then it could work. I don't think there is anything that needs to be done on OC side.

**Comment by PVince81** [comment]
I'm closing this ticket.
If you have a URL that points to your request in another repo, feel free to post it here :smile:

**Comment by plgingembre** [comment]
Wow, sorry about that. Do you have the URL or the other repo?

**Comment by PVince81** [comment]
I'd have to google it. Is CloudSync open source ?

**Comment by plgingembre** [comment]
Unfortunately I don’t think so. It is a Synology app developed for their DSM OS and I am almost sure that the code is not open source, but I am not sure. I need to check that.
Currently they have a long list of authorized cloud storage providers that can sync files seamlessly with any Synology box, which is a very very cool feature to have your files synced anywhere. They seem to have a WebDAV connector, maybe I need to test it.

**Comment by PVince81** [comment]
Yeah, with a bit of luck the WebDAV connector might work

**Comment by minimoe** [comment]
Just want to confirm I got this working using the webdav-connector and I haven't had any issues yet.

Please refer to the documentation: https://doc.owncloud.org/server/8.1/user_manual/files/access_webdav.html?highlight=webdav
