### ISSUE TITLE
File downloaded from a folder shared by link is not named as the folder.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#19646]
### Steps to reproduce

1. Share a folder called FOLDER by link.
2. in a different browser open the link and download the entire folder.

### Expected behaviour
A file called FOLDER.tar is downloaded in OS X, FOLDER.zip in other OS.

### Actual behaviour
A file called download.tar (download.zip) is downloaded.

### Server configuration
**Operating system**:
ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.2.0.9","versionstring":"8.2 RC1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Comment by DeepDiver1975** [comment]
I was just retesting this on 8.0 - the folder is named download as well - no regression.

won't fix then -> close

**Comment by SergioBertolinSG** [comment]
Ok not a regression, but it is still a bad name.
