### ISSUE TITLE
Can not download multiple times from public page

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#19642]
## Steps
1. Share a folder with multiple files as link
2. Open public link
3. Select more then one file from the list
4. Press Download

### Expected
Can press download again

### Actual
Button is "disabled"
![files_-_owncloud_-_2015-10-08_11 03 49](https://cloud.githubusercontent.com/assets/213943/10362053/47433f94-6dac-11e5-96cb-a7fc66622076.png)

Works fine in 8.1

@PVince81 maybe something for you while you are in your JS phase :wink:

**Comment by PVince81** [comment]
I'll have a look.

CC @MorrisJobke who introduced the spinner recently

**Comment by PVince81** [comment]
It looks like public download doesn't set the magic cookie so we cannot know when the download started. From what I remember this used to work ?

**Comment by PVince81** [comment]
The cookie is only set in "files/ajax/download.php" while the public page goes through an app framework controller for the download.

From reading the code it looks like this never could work, at least not since we have the controllers.

**Comment by PVince81** [comment]
@DeepDiver1975 not a regression. I just checked the git history and this feature has only be added in 8.2. I mistakenly thought that @MorrisJobke backported it

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/19643

**Comment by DeepDiver1975** [comment]
> Works fine in 8.1

worked before and now it's broken -> regression for me

**Comment by nickvergessen** [comment]
Well, the cookie is not in 8.1 right, but in 8.1 you can press the dl button multiple times without a page reload

**Comment by PVince81** [comment]
fine
