### ISSUE TITLE
Clicking away over file/folder list does not save the password for sharing via link

### ISSUE THREAD

**Issue by davitol** [owncloud/core#19648]
### Steps to reproduce
1. Share a file by link.
2. Write down a password to share
3. Click away over a file/folder of the list
### Expected behaviour

The password should be saved
### Actual behaviour

The password is not saved

Note: Clicking away over a file/folder of the list, saves the expiration date, so both behaviours should be the same
### Server configuration

**Operating system**:
ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.2.0.9","versionstring":"8.2 RC1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Comment by PVince81** [comment]
Not sure. The password is something sensitive, it might be on purpose that the user needs to hit enter.
Did you check how it used to behave in 8.1.3 ?

**Comment by davitol** [comment]
@PVince81 Yes, I did, and the behaviour was to save the password

**Comment by PVince81** [comment]
Ok, then it makes sense to make it behave the same here.
Thanks.

**Comment by PVince81** [comment]
Works for me in 8.2RC1 in Chromium 43.

Which browser did you use and where did you click ?
I clicked on the empty space below the file list.

**Comment by davitol** [comment]
Mozilla Firefox 
![sharepass](https://cloud.githubusercontent.com/assets/10596560/10460225/b7f01444-71d3-11e5-869c-910b58f83b68.gif)

**Comment by PVince81** [comment]
Ah, so you're selecting another file. Hmmm... this seems to prevent the saving to happen because the field is destroyed due to switching.

**Comment by PVince81** [comment]
(this is another reason why I dislike save on blur, you run into all kinds of weird situations)

**Comment by davitol** [comment]
@PVince81 Same behaviour on Chrome.

**Comment by PVince81** [comment]
This is a tough one. Need to find a way to delay the element's destruction when selecting another item in the file list.

**Comment by PVince81** [comment]
obsolete by the new modal in 10.0
