### ISSUE TITLE
home directory is not created when using \OC_User::loginWithApache()

### ISSUE THREAD

**Issue by butonic** [owncloud/core#19656]
When doing a form login the home dir is created on the fly in https://github.com/owncloud/core/blob/master/lib/private/user.php#L252

When using an apache auth mechanism the home dir is not created on the fly, resulting in:
```json
{
   "level" : 4,
   "time" : "2015-10-05T20:32:59+00:00",
   "app" : "index",
   "remoteAddr" : "128.205.218.181",
   "reqId" : "l7gXm+K7RFJt0vismdZ6",
   "message" : "Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":"see below",\"Line\":971}"
}
```
```
#0 /var/www/owncloud/apps/files/index.php(84): OC_Helper::getStorageInfo('/', false)
#1 /var/www/owncloud/lib/private/route/route.php(154) : runtime-created function(1): require_once('/var/www/ownclo...')
#2 [internal function]: __lambda_func(Array)
#3 /var/www/owncloud/lib/private/route/router.php(274): call_user_func('?lambda_763', Array)
#4 var/www/owncloud/lib/base.php(874): OC\Route\Router->match('/apps/files/')
#5 /var/www/owncloud/index.php(40): OC::handleRequest()
#6 {main}
```

It should be possible to use the post_login hook as the only codepath for homedir / filesystem setup:
The hook in https://github.com/owncloud/core/blob/master/lib/private/user.php#L291 should be fired in https://github.com/owncloud/core/blob/master/lib/private/user.php#L252 as well.

@icewind1991 or am I wrong?

**Comment by awrede** [comment]
I just ran into the same issue with OC_User_IMAP. Is there a work-around, other than creating a local account?

**Comment by butonic** [comment]
use an onLogin hook:
```php
\OCP\Util::connectHook('OC_User', 'post_login', 'OCA\CookieSSO\User\Backend\CookieSSO', 'onLogin');
```
to register a hook that calls `\OC::$server->getUserFolder($params['uid']);` to initialize the home directory for that user.
```php
	/**
	 * called by hook listener added in app.php
	 * will create the user home
	 * @param string[] $params
	 */
	public static function onLogin(array $params) {
		\OC::$server->getUserFolder($params['uid']);
	}
```

hope this helps.

**Comment by MorrisJobke** [comment]
cc @PVince81 please triage and assign the correct milestone

**Comment by PVince81** [comment]
Set to 9.0 to look into a generic solution that doesn't require a workaround.

CC @cmonteroluque

**Comment by MorrisJobke** [comment]
Fixed via https://github.com/owncloud/core/pull/23903#issuecomment-211755488
