### ISSUE TITLE
Cronjob PHP fatal error

### ISSUE THREAD

**Issue by despens** [owncloud/core#19653]
### Steps to reproduce
1. set up cronjob as described in manual:
```crontab
*/15  *  *  *  * php -f /var/www/owncloud/cron.php
```

### Expected behaviour
Cronjob should do its thing.

### Actual behaviour

```sh
$ php -f /var/www/owncloud/cron.php
PHP Fatal error:  Call to a member function removeChild() on a non-object in /var/www/owncloud/apps/search_lucene/3rdparty/zendframework/zendsearch/library/ZendSearch/Lucene/Document/HTML.php on line 119
```

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Server version: Apache/2.4.7 (Ubuntu)
Server built:   Sep  2 2015 13:02:10

**Database:** mysql  Ver 14.14 Distrib 5.5.44, for debian-linux-gnu (x86_64) using readline 6.3

**PHP version:** PHP 5.5.9-1ubuntu4.12 (cli) (built: Aug 13 2015 22:34:42) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

**ownCloud version:**  ownCloud 8.1.3 (stable) 

**Updated from an older ownCloud or fresh install:** from 8.1.1

**List of activated apps:**

```
Enabled:
 - activity: 2.0.2
 - calendar: 0.7.3
 - contacts: 0.4.0.0
 - documents: 0.10.2
 - files: 1.1.10
 - files_external: 0.2.3
 - files_locking: 
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - search_lucene: 0.7.0
 - templateeditor: 0.1
 - updater: 0.6
Disabled:
 - admin_dependencies_chk
 - bookmarks
 - encryption
 - external
 - files_encryption
 - files_pdfviewer
 - provisioning_api
 - user_external
 - user_ldap
 - user_webdavauth

```

**The content of config/config.php:**

```sh
$ php occ config:list system --public
                                                           
  [InvalidArgumentException]                                
  There are no commands defined in the "config" namespace.                                                            
```

**Are you using external storage, if yes which one:** sftp

**Are you using encryption:** no

#### ownCloud log (data/owncloud.log)
```

```

**Comment by MorrisJobke** [comment]
cc @butonic

**Comment by RealRancor** [comment]
Probably something which should be reported to https://github.com/owncloud/search_lucene/issues ?

**Comment by nickvergessen** [comment]
Is the error (including backtrace) logged in the owncloud.log file?

**Comment by PVince81** [comment]
Is this still an issue in 8.2.2 ?

**Comment by nickvergessen** [comment]
Closing as per missing info, if you can provide them feel free to open a new issue in https://github.com/owncloud/search_lucene
