### ISSUE TITLE
.part Files/Records en masse

### ISSUE THREAD

**Issue by segerl** [owncloud/core#19668]
Hi,

I have an installation of owncloud 7.0.10 (upgraded a few minutes before from 7.0.3) where we have over 23.000 files with ".part" as extension in oc_file_map table (and over 66.000 files without .part).

Because I saw in some supportcases that there were errors in the past which caused such problems and which also were solved with some patches (temporarily and in the next releases) I updated to 7.0.10. Now I'm running with that release but the .part records are still in the database and causing problems with syncing some clients.

What can I do to solve this / remove these records without getting (more) problems with syncing? I'm not sure if I should just remove the records from the database?

thx

Egon

**Comment by MorrisJobke** [comment]
Usually part files shouldn't show up in the filecache.

@PVince81 @icewind1991 Do you remind if we clean this up in a later version?

**Comment by PVince81** [comment]
oc_file_mapping table is for windows server, which isn't supported since 8.1

Part files should never appear in the oc_filecache.

**Comment by MorrisJobke** [comment]
As windows server is no longer supported and owncloud 7 is in "security fixes only" phase I will close this then.
