### ISSUE TITLE
Exception: Please upload the ca-bundle.crt file into the 'config' directory.

### ISSUE THREAD

**Issue by JtwoA** [owncloud/core#19669]
Exception: Please upload the ca-bundle.crt file into the 'config' directory.

Error received attempting to run updater to 8.1.3

**Comment by Kawohl** [comment]
@JtwoA 

Thanks for your contribution,
 please be a little more specific and use the issue template.

@JtwoA

**Comment by MorrisJobke** [comment]
> Error received attempting to run updater to 8.1.3

@VicDeo This seems like a bug in the updater.

**Comment by MorrisJobke** [comment]
In the meantime you can put this file in there as ca-bundle.crt https://raw.githubusercontent.com/owncloud/core/stable8.1/config/ca-bundle.crt

**Comment by MorrisJobke** [comment]
The actual problem was fixed with #18893 and in the updater it's also fixed: https://github.com/owncloud/updater/blob/stable8.1/lib/files.json#L4

**Comment by RealRancor** [comment]
Btw. dup of https://github.com/owncloud/core/issues/19551, https://github.com/owncloud/core/issues/19204 and https://github.com/owncloud/updater/issues/164 (and some more)

**Comment by JtwoA** [comment]
@Kawohl Sorry, I'm new.  I clicked the ISSUE button and filled out the form that came up.  Didn't see an option to change templates.

Everyone else, I did a search for "ca-bundle.crt" and came up empty.  I appreciated the assist.  @MorrisJobke I've grabbed the file you indicated and will drop that in.  

Thanks all.

**Comment by RealRancor** [comment]
Mhh, a search for this keyword leads here to 27 hits:

https://github.com/owncloud/core/search?q=ca-bundle.crt&type=Issues&utf8=%E2%9C%93

**Comment by JtwoA** [comment]
@RealRancor Thanks for your feedback!
