### ISSUE TITLE
Some labels are missed in the personal page

### ISSUE THREAD

**Issue by davitol** [owncloud/core#19674]
### Steps to reproduce

1. Login ownCloud.
2. Go to Personal menu

### Expected behaviour

'Pass2' and 'Updload new' do not have the corresponding label

### Actual behaviour

'Pass2' and 'Updload new' should have the corresponding label

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:**ownCloud 8.2 RC1 (daily) Build:2015-10-09T03:37:36+00:00 020bb33150ddaab4463b63799774f144a3448263

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
 Firefox.

**Comment by DeepDiver1975** [comment]
does this effect accessibility? - please test - thx

**Comment by MorrisJobke** [comment]
> 'Pass2' and 'Updload new' should have the corresponding label

For me for `pass2` the label is present:
![bildschirmfoto von 2015-10-09 10-57-47](https://cloud.githubusercontent.com/assets/245432/10389836/9c2f34e0-6e74-11e5-8c91-f894cdacf7fe.png)


What is `Upload new`? The upload button of the avatar? It is already text in a button. Isn't this enough? Why should we add the same text again?

**Comment by davitol** [comment]
@MorrisJobke As you said looking in the code, label for pass2 is present, but WAVE (Web accesibility evaluation tool) those error are shown. 

![screen shot 2015-10-09 at 13 12 02](https://cloud.githubusercontent.com/assets/10596560/10392463/a08da39c-6e87-11e5-9ef2-5f06dc24b593.png)


And yes, I was talking about upload button of avatar

![screen shot 2015-10-09 at 13 12 20](https://cloud.githubusercontent.com/assets/10596560/10392461/990a6254-6e87-11e5-8053-e28c75cc0b83.png)


I did not set a milestone in the issue, because I was not pretty sure if it was really an accessibility bug.

**Comment by DeepDiver1975** [comment]
@jancborchardt please have a look once you are back  :surfer:

**Comment by jancborchardt** [comment]
As you see from the tooltips, the labels are not necessary. The first error next to the password field is an image toggle (the »show password« button), and the second is just a button which is already correctly labeled. Adding any extra label here would duplicate the content.
