### ISSUE TITLE
Numbers added in the resharing forbidden message.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#19678]
### Steps to reproduce

1. As admin share a folder 'folder' with user1 without all permissions, specially resharing.
2. Try to reshare 'folder' with user2:
```
curl -X POST http://user1:PASSWORD@HOST/ocs/v1.php/apps/files_sharing/api/v1/shares -d "path=folder&shareWith=user2&shareType=0"
```

### Expected behaviour
```
<message>You are not allowed to share</message>
```

### Actual behaviour
```
<message>You are not allowed to share 45</message>
````
The number is variable.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.2.0.9","versionstring":"8.2 RC1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No.

**Comment by SergioBertolinSG** [comment]
cc @rullzer

**Comment by MorrisJobke** [comment]
It's the share ID ;) cc @schiesbn

**Comment by rullzer** [comment]
Yeah lets replace that share ID with the path.

**Comment by rullzer** [comment]
Fix in #19727

**Comment by rperezb** [comment]
As stated on the pr, there are more cases where the error number is shown, for instance:
- Share with the owner, error 32 https://github.com/owncloud/core/pull/19727#issuecomment-147753323
- Disable allow reshareing, error 29

It would be great if every case it's taken into account

**Comment by rullzer** [comment]
@rperezb please create separate issues so we can better keep track of them.
