### ISSUE TITLE
Error message about file not found should be more specific in fed.sharing

### ISSUE THREAD

**Issue by davitol** [owncloud/core#19675]
### Steps to reproduce

1. Federate share a file (two different oC servers)
2. Delete the file in server A
3. Try to open the file in server B

### Expected behaviour

An error about file not found should be shown

### Actual behaviour

'An internal server error occurred' error message is shown

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:**ownCloud 8.2 RC1 (daily) Build:2015-10-09T03:37:36+00:00 020bb33150ddaab4463b63799774f144a3448263

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
 Firefox.

![screen shot 2015-10-09 at 09 46 56](https://cloud.githubusercontent.com/assets/10596560/10389874/ef33e046-6e74-11e5-88ac-3e17b37fcb6d.png)

**Comment by PVince81** [comment]
The error is happening in the text editor, which uses its own ajax endpoint to access file contents. That one needs to be adjusted to catch "StorageNotAvailableException" or "StorageInvalidException".
@tomneedham

**Comment by PVince81** [comment]
@tomneedham please have a look, this is the text editor

**Comment by schiesbn** [comment]
This bug was introduced a few weeks ago and fixed by me last week https://github.com/owncloud/files_texteditor/pull/125

@davitol please checkout the lasted stable8.1 version from github of the text editor and check if it still happens. If yes we probably need to add a HintException but the chance is high that it is already fixed with the latest text editor.

**Comment by davitol** [comment]
@schiesbn Tested using:
Server A: ownCloud Enterprise Edition 8.2 RC3 (daily) Build:2015-10-19T03:08:48+00:00 bd835f9eccd59d8e5c5408beb97bb95835db42c5
Server B: ownCloud Enterprise Edition 8.1.3 (daily) Build:2015-10-20T03:19:30+00:00 c2ded337e602c6113c4adeb9071ef6581dfa5a81. 

In server B it is shown 'An internal server error occurred'

**Comment by schiesbn** [comment]
@davitol As said, this was a regression in the files_texteditor app which was fixed after the 8.1.3 release. Please replace apps/files_texteditor at server B with a up to date copy of the stable8.1 branch and try again: https://github.com/owncloud/files_texteditor/tree/stable8.1

**Comment by PVince81** [comment]
@davitol did it work with 8.1.4 which should contain the fixes ?

**Comment by davitol** [comment]
@PVince81 It did not worked for me in ownCloud 8.1.4 (stable). It is shown the same error as before

**Comment by PVince81** [comment]
@tomneedham do you mind having a quick look at this text editor issue on 8.1.4 ?

**Comment by schiesbn** [comment]
I will double check, maybe we don't throw a hint exception

**Comment by schiesbn** [comment]
I can reproduce it. It seems that we throw a generic exception if the file isn't there. We could through a hint exception instead with a more meaningful error message. But we need to make sure that we detect the correct state.

**Comment by schiesbn** [comment]
See pull request above, I updated the exception to have a more meaningful error message. Unfortunately we can't really decide what happened at the point where the exception happens. But at least you get now a "Storage not available" error message.
