### ISSUE TITLE
App menu spinner shifted

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#19673]
### Steps to reproduce

1. Go to the files app (important!)
1. Navigate to the apps page or any other app using the app menu on the top left

### Expected result
Aligned spinner

### Actual result
![files-appmenu-spinner](https://cloud.githubusercontent.com/assets/277525/10389305/b3e99e76-6e70-11e5-852c-47f7d1db3b80.png)

### Versions
ownCloud 8.2 RC1

This only happens while the files app is open so I suspect there might be a CSS rule conflict that shifts the spinner there.

@owncloud/designers

**Comment by MorrisJobke** [comment]
I debugged this and it only occurs with the current gallery master. If I disable gallery app everything works fine.

**Comment by MorrisJobke** [comment]
cc @oparoz

**Comment by MorrisJobke** [comment]
Fix is in https://github.com/owncloud/gallery/pull/415

**Comment by jancborchardt** [comment]
Nice, thanks @PVince81 @MorrisJobke – I encountered that bug but thought I was confused or it was a browser glitch.
