### ISSUE TITLE
owncloud-server-$INSTANCEID-cron.lock not removed on OC 8.1.3

### ISSUE THREAD

**Issue by resound88** [owncloud/core#19671]
Hi together,
On our system the file /tmp/owncloud-server-$INSTANCEID-cron.lock gets a new modified timestamp every 15 minutes, but isn't removed.
I haven't noticed this behaviour in previous versions of OC.
The MySQL oc_jobs table contains two jobs, which have a realtive new last_run timestamp:

OC\BackgroundJob\Legacy\RegularJob
OCA\Files_sharing\Lib\DeleteOrphanedSharesJob

There are no errors in OC log.

Is this a normal behaviour?

Thanks in advance.

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by RealRancor** [comment]
Yes, AFAIK the file should stay on the disc when reading this correctly:

https://github.com/owncloud/core/issues/3221

**Comment by PVince81** [comment]
Possible duplicate of https://github.com/owncloud/core/issues/18049
