### ISSUE TITLE
Missing tooltip styling in LDAP wizard

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#19684]
The replacement of jquery.tipsy with jquery.tooltip made them disappear from the LDAP wizard.

### Steps

1. Enable the LDAP app
1. Go to admin page
1. Hover on top of any of the LDAP fields

### Expected:
![ldap-tipsy](https://cloud.githubusercontent.com/assets/277525/10399810/6403df12-6eb5-11e5-8418-66c453548c24.png)

### Actual:
![ldap-missing-tispy](https://cloud.githubusercontent.com/assets/277525/10399797/47dccaf6-6eb5-11e5-8b5b-6a3fd62aaf69.png)

Regression since https://github.com/owncloud/core/pull/18122

### Versions
ownCloud 8.2 RC1

@Henni can you help bring them back ?
I suspect it was one of those global calls... might need to add them inside the wizard code directly.

CC @blizzz

**Comment by PVince81** [comment]
CC @jancborchardt who probably would have raised this if I didn't find it first :wink:

**Comment by blizzz** [comment]
Was this not all ported to the tooltip thing? I believe to remember so. Not aware that something happend in LDAP about that since.

**Comment by Henni** [comment]
I'll take a look tomorrow

**Comment by PVince81** [comment]
@blizzz I think the ldap code never contained any calls to tipsy/tooltip. It only worked because of a magical mega-global call that was done on whole pages. That call is gone.

**Comment by blizzz** [comment]
Mh, might been that…

**Comment by PVince81** [comment]
Regression => setting to 8.2.1 @DeepDiver1975 @cmonteroluque @karlitschek

**Comment by PVince81** [comment]
@Henni any update ?

**Comment by Henni** [comment]
@PVince81 I wasn't able to setup the ldap docker.
But I'll create an untested PR in a second.

**Comment by PVince81** [comment]
For the LDAP docker, you can use the start script here: https://github.com/owncloud/administration/tree/master/ldap-testing

Then type "ldap://localhost" in the wizard. You probably don't need any users for this fix.

**Comment by Henni** [comment]
I tried using this but didn't it work out when I tried.
I'll take another look.

**Comment by PVince81** [comment]
Closed through https://github.com/owncloud/core/issues/19940
