### ISSUE TITLE
I cannot view or sync files in S3 mount, even though I can upload them.

### ISSUE THREAD

**Issue by jerrac** [owncloud/core#19689]
### Steps to reproduce
1. Install OwnCloud with Amazon S3 personal mounting enabled.
2. Add S3 mount via "personal settings" screen.
3. Upload a file to the new mount via the web ui.

### Expected behaviour
The file should show up in the file list.

### Actual behaviour
No files or folders show in the file list. I cannot sync the files using the client. 

The files do get uploaded to S3. I can see them using S3's UI.

I did try running the files:scan --all command. It listed the files in S3, but they still do not show up in the file list.

I find https://github.com/owncloud/core/issues/11652 but it seems like it's about finding files that are uploaded to S3 outside of OwnCloud. 

I did not find anything else in the forums or issue queue that seemed helpful. 

I also asked on IRC, but I must have done so at a bad time since no one has responded.

### Server configuration
**Operating system**: Ubuntu 14.04 64bit

**Web server**: Apache 2.4

**Database:** MySQL

**PHP version:** PHP 5.5.9-1ubuntu4.13 (cli) (built: Sep 29 2015 15:24:49)

**ownCloud version:** 8.1.3 stable

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**

```
sudo -u www-data php occ app:list
Enabled:
 - activity: 2.0.2
 - files: 1.1.10
 - files_external: 0.2.3
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.6
 - user_external: 0.4
Disabled:
 - encryption
 - external
 - user_ldap
 - user_webdavauth

```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => 'cloud.host.tld',
  ),
  'datadirectory' => '/srv/ownclouddata',
  'overwrite.cli.url' => 'https://cloud.host.tld',
  'dbtype' => 'mysql',
  'version' => '8.1.3.0',
  'dbname' => 'owncloud',
  'dbhost' => 'ipaddress',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '',
  'logtimezone' => 'UTC',
  'installed' => true,
  'instanceid' => '',
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'user',
  'mail_domain' => 'host.tld',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'mail.host.tld',
  'mail_smtpport' => '587',
  'mail_smtpname' => 'user@host.tld',
  'mail_smtppassword' => '',
  'user_backends' => 
  array (
    0 => 
    array (
      'class' => 'OC_User_IMAP',
      'arguments' => 
      array (
        0 => '{mail.host.tld:993/imap/novalidate-cert/ssl}',
      ),
    ),
  ),
  'loglevel' => 0,
);
```

**Are you using external storage, if yes which one:** S3 mount

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** IMAP

### Client configuration
**Browser:** Firefox 41

**Operating system:** Ubuntu 14.04

#### ownCloud log (data/owncloud.log)
```
{"reqId":"F8gWrncuC2uAQ1sASOpo","remoteAddr":"cli.ent.ip.add","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'pic1.jpg' is not accessible or present !!!","level":0,"time":"2015-10-10T18:03:07+00:00","method":"GET","url":"\/index.php\/apps\/files\/ajax\/list.php?dir=%2FS3&sort=name&sortdirection=asc"}
{"reqId":"F8gWrncuC2uAQ1sASOpo","remoteAddr":"cli.ent.ip.add","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'pic2' is not accessible or present !!!","level":0,"time":"2015-10-10T18:03:07+00:00","method":"GET","url":"\/index.php\/apps\/files\/ajax\/list.php?dir=%2FS3&sort=name&sortdirection=asc"}
{"reqId":"F8gWrncuC2uAQ1sASOpo","remoteAddr":"cli.ent.ip.add","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'Test' is not accessible or present !!!","level":0,"time":"2015-10-10T18:03:07+00:00","method":"GET","url":"\/index.php\/apps\/files\/ajax\/list.php?dir=%2FS3&sort=name&sortdirection=asc"}
```

**Comment by MorrisJobke** [comment]
cc @butonic @Xenopathic

**Comment by PVince81** [comment]
### Steps

1. Enable external storage app
1. Go to admin page and allow personal mounts for "Amazon S3"
1. Go to personal page
1. Mount S3 storage as "/s3", filling out the fields "access key", "secret key" and "bucket" (EU), and enable SSL
1. Click outside and wait for the green dot to appear
1. Go to the files page
1. Navigate into the "s3" folder
1. Upload a new file "bacon.txt". The file appears
1. Refresh the page: file is still there.

Works for me in v8.1.3.

**Comment by PVince81** [comment]
Also tested with the files_locking and activity apps enabled, still works.

**Comment by jerrac** [comment]
https://github.com/owncloud/core/issues/19689#issuecomment-147358055 Up through step 7 is exactly what I did. It's just that the files I uploaded do not show up.

Oh, and at step 4 I tried both checking, and not checking, the "enable path style" box.

What other information could I provide? Could my Apache settings do anything to this? Or the fact I'm running on a Digital Ocean 512MB vps? 

I'll check my apache settings when I get off work, this is a personal server.

**Comment by cmonteroluque** [comment]
@jerrac any update?

**Comment by jerrac** [comment]
Nothing wrong with this, is there? For Apache 2.4.

    <Directory /var/www/owncloud>
      Options -Indexes +FollowSymLinks -MultiViews
      AllowOverride All
      Require all granted
    </Directory>

The only other things I can see, that might be an issue, is that I force a rewrite to https from http, and that my ssl cert is self-signed. 

I do have my data directory outside of my web root. /srv/ownclouddata. I set the permissions using that bash script in the administration documentation.

**Comment by PVince81** [comment]
@jerrac can you check `select * from oc_filecache where path like '%uploadedfile%'` (replace "uploadedfile" with the name of the uploaded file).

You said the scan command did display the files in question but they don't appear in the UI, correct ?

Is there any error appearing in the Javascript console when you refresh the file list in the web UI ?

**Comment by PVince81** [comment]
Also, did you disable sharing ?

**Comment by jerrac** [comment]
The select query returns "Empty set".

I got the file name from the scan --all command.

The files do not show in the web ui.

FF's console log: http://pastebin.com/3GsCsuge when viewing the S3
directory.

Line 381 looks interesting.

    Content Security Policy: The page's settings blocked the loading of a
resource at self ("script-src https://owncloud.domain.tld 'unsafe-eval'").
files:1:0



--David Reagan

**Comment by jerrac** [comment]
I did not disable sharing.

--David Reagan

**Comment by PVince81** [comment]
Hmmm that doesn't make sense.
The file upload should add an entry there after finishing the upload. But it seems it didn't.
And then, if the "files:scan" finds the remote file, it should also add it to "oc_filecache" if it's missing.
But it didn't either.

Let's have a look at your "oc_storages". It should have an entry that matches the amazon S3 storage.
Pick its "numeric_id" and write it down, let's call it $numid.
Then do a `select * from oc_filecache where storage=$numid` (replace accordingly).
You should at least have a few other entries there.

**Comment by jerrac** [comment]
There's one row. 

    mysql> select * from oc_filecache where storage=5;
    +--------+---------+------+----------------------------------+--------+------+----------+----------+------+------------+---    ------------+-----------+------------------+---------------+-------------+
    | fileid | storage | path | path_hash                        | parent | name | mimetype | mimepart | size | mtime      |     storage_mtime | encrypted | unencrypted_size | etag          | permissions |
    +--------+---------+------+----------------------------------+--------+------+----------+----------+------+------------+---    ------------+-----------+------------------+---------------+-------------+
    |     22 |       5 |      | d41d8cd98f00b204e9800998ecf8427e |     -1 |      |        2 |        1 |    0 | 1445001107     |    1445001107 |         0 |                0 | 56211ea3a0cdc |          23 |
    +--------+---------+------+----------------------------------+--------+------+----------+----------+------+------------+---    ------------+-----------+------------------+---------------+-------------+
    1 row in set (0.01 sec)

Shouldn't there be a row per file in my s3 bucket? I have one directory, and two jpg's in that bucket.

One thing, I initially tried using a bucket in the Oregon region. Then I switched to on in US Standard region, if I remember correctly, OwnCloud isn't supposed to work with the Oregon region. That first bucket is still listed in the oc_storages table. Even though I replaced (I didn't use the trash icon to delete it) the bucket with the one in the US Standard region. Could that be part of the problem? Is it safe to delete the old bucket from the table via mysql?

**Comment by PVince81** [comment]
Hmm, usually I'd expect a change of configuration to create a new "oc_storages" entry.
If it didn't then I suggest you delete that configuration in the web UI.
Also, manually delete the "oc_storages" entry to make sure it's gone.
After that, reconfigure your S3 storage from scratch.

**Comment by PVince81** [comment]
You are right: when it works correctly, the oc_filecache (which is more an index than a cache) contains entries from whatever is on the remote server.

**Comment by jerrac** [comment]
Deleting the S3 config from the personal settings page did not delete either amazon entry in oc_storages. 

After manually deleting both entries, I reconfigured my S3 folder with just the keys and bucket name. I left all other settings blank.

I still cannot see any files in the S3 directory.

Checking the cache table gives me:

    mysql> select * from oc_filecache where storage=6;
    +--------+---------+------+----------------------------------+--------+------+----------+----------+------+------------+---------------+-----------+------------------+---------------+-------------+
    | fileid | storage | path | path_hash                        | parent | name | mimetype | mimepart | size | mtime      | storage_mtime | encrypted | unencrypted_size | etag          | permissions |
    +--------+---------+------+----------------------------------+--------+------+----------+----------+------+------------+---------------+-----------+------------------+---------------+-------------+
    |     31 |       6 |      | d41d8cd98f00b204e9800998ecf8427e |     -1 |      |        2 |        1 |    0 | 1445006748 |    1445006748 |         0 |                0 | 562134ac55de0 |          23 |
    +--------+---------+------+----------------------------------+--------+------+----------+----------+------+------------+---------------+-----------+------------------+---------------+-------------+
    1 row in set (0.00 sec)

**Comment by jerrac** [comment]
Fun fact, trying the s3 mount on a brand new instance installed on my desktop also fails.

I also noticed an error message pop up when I try uploading files. See the screenshot. 

![sss_-_files_-_owncloud_-_2015-10-16_13 12 45](https://cloud.githubusercontent.com/assets/910764/10552292/c050d20a-7407-11e5-9711-f78683768a46.png)

**Comment by PVince81** [comment]
I still have no idea why this is happening.

The code for the Amazon storage is here: https://github.com/owncloud/core/blob/master/apps/files_external/lib/amazons3.php#L112

You could try adding log statements or debugging it.
The error you see in the UI is likely to happen when it tries to get the root entry of the remote storage, possibly in file_exists https://github.com/owncloud/core/blob/master/apps/files_external/lib/amazons3.php#L204 or opendir https://github.com/owncloud/core/blob/master/apps/files_external/lib/amazons3.php#L262

**Comment by DeepDiver1975** [comment]
@cmonteroluque I vote for moving this to 9.0 - we have no idea whats going on and we plan to work on s3 anyhow in 9.0 .... THX

**Comment by jerrac** [comment]
I'm fine with waiting on this. Especially since I seem to be the only one with a problem, and I haven't had time to dig into it.

Just to make sure, you're overriding php's opendir function here https://github.com/owncloud/core/blob/master/apps/files_external/lib/amazons3.php#L261 on purpose, right?

**Comment by jerrac** [comment]
Ok, I poked at it a bit before I have to go to work, here's some new information.

After upgrading to 8.2, I created a new bucket and added it via the Personal Settings page.

Here's what I get in owncloud.log when:

Creating a text file:

    {"reqId":"8NU1QSBxEIb9MZ9fdWnx","remoteAddr":"<my desktop ip>","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'testing.txt' is not accessible or present !!!","level":0,"time":"2015-10-23T15:35:10+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/newfile.php"}
    {"reqId":"8NU1QSBxEIb9MZ9fdWnx","remoteAddr":"<my desktop ip>","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'testing.txt' is not accessible or present !!!","level":0,"time":"2015-10-23T15:35:10+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/newfile.php"}
    {"reqId":"8NU1QSBxEIb9MZ9fdWnx","remoteAddr":"<my desktop ip>","app":"hook","message":"error while running hook (OCA\\Activity\\FilesHooksStatic::fileCreate): An exception occurred while executing 'INSERT INTO `oc_activity` (`app`, `subject`, `subjectparams`, `message`, `messageparams`, `file`, `link`, `user`, `affecteduser`, `timestamp`, `priority`, `type`, `object_type`, `object_id`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"files\", \"created_self\", \"[\\\"\\\\\\\/again\\\\\\\/testing.txt\\\"]\", \"\", \"[]\", \"\\\/again\\\/testing.txt\", \"https:\\\/\\\/owncloud.domain.tld\\\/index.php\\\/apps\\\/files?dir=%2Fagain\", \"<username>\", \"<username>\", 1445614510, 30, \"file_created\", \"\", 0]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'object_type' in 'field list'","level":3,"time":"2015-10-23T15:35:10+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/newfile.php"}
    {"reqId":"8NU1QSBxEIb9MZ9fdWnx","remoteAddr":"<my desktop ip>","app":"PHP","message":"Argument 1 passed to OCA\\Files\\Helper::formatFileInfo() must implement interface OCP\\Files\\FileInfo, boolean given, called in \/var\/www\/owncloud\/apps\/files\/ajax\/newfile.php on line 99 and defined at \/var\/www\/owncloud\/apps\/files\/lib\/helper.php#135","level":3,"time":"2015-10-23T15:35:10+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/newfile.php"}
    {"reqId":"8NU1QSBxEIb9MZ9fdWnx","remoteAddr":"<my desktop ip>","app":"PHP","message":"Call to a member function getMimetype() on a non-object at \/var\/www\/owncloud\/apps\/files\/lib\/helper.php#77","level":3,"time":"2015-10-23T15:35:10+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/newfile.php"}


Uploading an image:

    {"reqId":"UYgaIDuVDp6xQAoJssjn","remoteAddr":"<my desktop ip>","app":"files_external","message":"Exception: {\"Exception\":\"Aws\\\\S3\\\\Exception\\\\AccessDeniedException\",\"Message\":\"Access Denied\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Aws\\\/Common\\\/Exception\\\/NamespaceExceptionFactory.php(76): Aws\\\\Common\\\\Exception\\\\NamespaceExceptionFactory->createException('Aws\\\\S3\\\\Exceptio...', Object(Guzzle\\\\Http\\\\Message\\\\Request), Object(Guzzle\\\\Http\\\\Message\\\\Response), Array)\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Aws\\\/Common\\\/Exception\\\/ExceptionListener.php(55): Aws\\\\Common\\\\Exception\\\\NamespaceExceptionFactory->fromResponse(Object(Guzzle\\\\Http\\\\Message\\\\Request), Object(Guzzle\\\\Http\\\\Message\\\\Response))\\n#2 [internal function]: Aws\\\\Common\\\\Exception\\\\ExceptionListener->onRequestError(Object(Guzzle\\\\Common\\\\Event), 'request.error', Object(Symfony\\\\Component\\\\EventDispatcher\\\\EventDispatcher))\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/event-dispatcher\\\/Symfony\\\/Component\\\/EventDispatcher\\\/EventDispatcher.php(164): call_user_func(Array, Object(Guzzle\\\\Common\\\\Event), 'request.error', Object(Symfony\\\\Component\\\\EventDispatcher\\\\EventDispatcher))\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/event-dispatcher\\\/Symfony\\\/Component\\\/EventDispatcher\\\/EventDispatcher.php(53): Symfony\\\\Component\\\\EventDispatcher\\\\EventDispatcher->doDispatch(Array, 'request.error', Object(Guzzle\\\\Common\\\\Event))\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Message\\\/Request.php(589): Symfony\\\\Component\\\\EventDispatcher\\\\EventDispatcher->dispatch('request.error', Object(Guzzle\\\\Common\\\\Event))\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Message\\\/Request.php(378): Guzzle\\\\Http\\\\Message\\\\Request->processResponse(Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Curl\\\/CurlMulti.php(286): Guzzle\\\\Http\\\\Message\\\\Request->setState('complete', Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Curl\\\/CurlMulti.php(244): Guzzle\\\\Http\\\\Curl\\\\CurlMulti->processResponse(Object(Guzzle\\\\Http\\\\Message\\\\Request), Object(Guzzle\\\\Http\\\\Curl\\\\CurlHandle), Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Curl\\\/CurlMulti.php(227): Guzzle\\\\Http\\\\Curl\\\\CurlMulti->processMessages()\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Curl\\\/CurlMulti.php(211): Guzzle\\\\Http\\\\Curl\\\\CurlMulti->executeHandles()\\n#11 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Curl\\\/CurlMulti.php(105): Guzzle\\\\Http\\\\Curl\\\\CurlMulti->perform()\\n#12 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Curl\\\/CurlMultiProxy.php(91): Guzzle\\\\Http\\\\Curl\\\\CurlMulti->send()\\n#13 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Client.php(282): Guzzle\\\\Http\\\\Curl\\\\CurlMultiProxy->send()\\n#14 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Aws\\\/Common\\\/Client\\\/AbstractClient.php(262): Guzzle\\\\Http\\\\Client->send(Object(Guzzle\\\\Http\\\\Message\\\\Request))\\n#15 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Guzzle\\\/Service\\\/Client.php(136): Aws\\\\Common\\\\Client\\\\AbstractClient->send(Object(Guzzle\\\\Http\\\\Message\\\\Request))\\n#16 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Guzzle\\\/Service\\\/Command\\\/AbstractCommand.php(153): Guzzle\\\\Service\\\\Client->execute(Object(Aws\\\\S3\\\\Command\\\\S3Command))\\n#17 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Guzzle\\\/Service\\\/Command\\\/AbstractCommand.php(189): Guzzle\\\\Service\\\\Command\\\\AbstractCommand->execute()\\n#18 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Aws\\\/Common\\\/Iterator\\\/AwsResourceIterator.php(62): Guzzle\\\\Service\\\\Command\\\\AbstractCommand->getResult()\\n#19 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Guzzle\\\/Service\\\/Resource\\\/ResourceIterator.php(190): Aws\\\\Common\\\\Iterator\\\\AwsResourceIterator->sendRequest()\\n#20 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Guzzle\\\/Service\\\/Resource\\\/ResourceIterator.php(157): Guzzle\\\\Service\\\\Resource\\\\ResourceIterator->next()\\n#21 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/amazons3.php(278): Guzzle\\\\Service\\\\Resource\\\\ResourceIterator->rewind()\\n#22 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(89): OC\\\\Files\\\\Storage\\\\AmazonS3->opendir('')\\n#23 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/availability.php(93): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->opendir('')\\n#24 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(89): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->opendir('')\\n#25 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(89): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->opendir('')\\n#26 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(300): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->opendir('')\\n#27 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(335): OC\\\\Files\\\\Cache\\\\Scanner->getNewChildren('')\\n#28 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(268): OC\\\\Files\\\\Cache\\\\Scanner->scanChildren('', false, 3, Array, true)\\n#29 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/watcher.php(91): OC\\\\Files\\\\Cache\\\\Scanner->scan('', false)\\n#30 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1204): OC\\\\Files\\\\Cache\\\\Watcher->checkUpdate('', Array)\\n#31 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(861): OC\\\\Files\\\\View->getFileInfo('\\\/again', false)\\n#32 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/helper.php(838): OC\\\\Files\\\\Filesystem::getFileInfo('\\\/again', false)\\n#33 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/lib\\\/helper.php(45): OC_Helper::getStorageInfo('\\\/again')\\n#34 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/ajax\\\/upload.php(108): OCA\\\\Files\\\\Helper::buildFileStorageStatistics('\\\/again')\\n#35 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(154) : runtime-created function(1): require_once('\\\/var\\\/www\\\/ownclo...')\\n#36 [internal function]: __lambda_func(Array)\\n#37 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(282): call_user_func('?lambda_482', Array)\\n#38 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(831): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/aja...')\\n#39 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#40 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Aws\\\/Common\\\/Exception\\\/NamespaceExceptionFactory.php\",\"Line\":91}","level":3,"time":"2015-10-23T15:36:18+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/upload.php"}
    {"reqId":"UYgaIDuVDp6xQAoJssjn","remoteAddr":"<my desktop ip>","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'sss_-_Files_-_ownCloud_-_2015-10-16_13.12.45.png' is not accessible or present !!!","level":0,"time":"2015-10-23T15:36:19+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/upload.php"}
    {"reqId":"UYgaIDuVDp6xQAoJssjn","remoteAddr":"<my desktop ip>","app":"hook","message":"error while running hook (OCA\\Activity\\FilesHooksStatic::fileCreate): An exception occurred while executing 'INSERT INTO `oc_activity` (`app`, `subject`, `subjectparams`, `message`, `messageparams`, `file`, `link`, `user`, `affecteduser`, `timestamp`, `priority`, `type`, `object_type`, `object_id`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"files\", \"created_self\", \"[\\\"\\\\\\\/again\\\\\\\/sss_-_Files_-_ownCloud_-_2015-10-16_13.12.45.png\\\"]\", \"\", \"[]\", \"\\\/again\\\/sss_-_Files_-_ownCloud_-_2015-10-16_13.12.45.png\", \"https:\\\/\\\/owncloud.domain.tld\\\/index.php\\\/apps\\\/files?dir=%2Fagain\", \"<username>\", \"<username>\", 1445614579, 30, \"file_created\", \"\", 0]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'object_type' in 'field list'","level":3,"time":"2015-10-23T15:36:19+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/upload.php"}
    {"reqId":"1OKsuCOBBhvHBj9ljr1W","remoteAddr":"<my desktop ip>","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'sss_-_Files_-_ownCloud_-_2015-10-16_13.12.45.png' is not accessible or present !!!","level":0,"time":"2015-10-23T15:36:20+00:00","method":"GET","url":"\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=%2Fagain"}
    {"reqId":"1OKsuCOBBhvHBj9ljr1W","remoteAddr":"<my desktop ip>","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'testing.txt' is not accessible or present !!!","level":0,"time":"2015-10-23T15:36:21+00:00","method":"GET","url":"\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=%2Fagain"}

As before, both files are visible in the AWS interface.


I see:

    {"reqId":"8NU1QSBxEIb9MZ9fdWnx","remoteAddr":"<my desktop ip>","app":"hook","message":"error while running hook (OCA\\Activity\\FilesHooksStatic::fileCreate): An exception occurred while executing 'INSERT INTO `oc_activity` (`app`, `subject`, `subjectparams`, `message`, `messageparams`, `file`, `link`, `user`, `affecteduser`, `timestamp`, `priority`, `type`, `object_type`, `object_id`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"files\", \"created_self\", \"[\\\"\\\\\\\/again\\\\\\\/testing.txt\\\"]\", \"\", \"[]\", \"\\\/again\\\/testing.txt\", \"https:\\\/\\\/owncloud.domain.tld\\\/index.php\\\/apps\\\/files?dir=%2Fagain\", \"<username>\", \"<username>\", 1445614510, 30, \"file_created\", \"\", 0]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'object_type' in 'field list'","level":3,"time":"2015-10-23T15:35:10+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/newfile.php"}

In both outputs. Am I missing a column?

**Comment by DeepDiver1975** [comment]
> {"reqId":"8NU1QSBxEIb9MZ9fdWnx","remoteAddr":"<my desktop ip>","app":"hook","message":"error while running hook (OCA\\Activity\\FilesHooksStatic::fileCreate): An exception occurred while executing 'INSERT INTO `oc_activity` (`app`, `subject`, `subjectparams`, `message`, `messageparams`, `file`, `link`, `user`, `affecteduser`, `timestamp`, `priority`, `type`, `object_type`, `object_id`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"files\", \"created_self\", \"[\\\"\\\\\\\/again\\\\\\\/testing.txt\\\"]\", \"\", \"[]\", \"\\\/again\\\/testing.txt\", \"https:\\\/\\\/owncloud.domain.tld\\\/index.php\\\/apps\\\/files?dir=%2Fagain\", \"<username>\", \"<username>\", 1445614510, 30, \"file_created\", \"\", 0]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'object_type' in 'field list'","level":3,"time":"2015-10-23T15:35:10+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/newfile.php"}

looks like an upgrade issue - the db misses this columns?????

**Comment by jerrac** [comment]
This is what I did when upgrading:

    root@host:/var/www# tar xf owncloud-8.2.0.tar.bz2 
    root@host:/var/www# cd owncloud
    root@host:/var/www/owncloud# sudo -u www-data php occ upgrade
    ownCloud or one of the apps require upgrade - only a limited number of commands are available
    Set log level to debug - current level: 'Fatal'
    Turned on maintenance mode
    Checked database schema update
    Checked database schema update for apps
    Updated database
    Updating <files_texteditor> ...
    Updated <files_texteditor> to 2.0
    Update successful
    Turned off maintenance mode
    Reset log level to 'Fatal'

**Comment by jerrac** [comment]
Solved it. Since it worked perfect for @PVince81 and didn't work on two instances for me, I started wondering if I had messed up the Amazon side of things. I had just given authenticated users full access to the bucket, I figured my access keys would make that work. Apparently I was wrong. After poking around AWS some, I found where you can apply Policies to your user. After applying the AmazonS3FullAccess policy, I can see the files in my S3 bucket just fine.

Would explaining how to configure your S3 user be in the scope of the OwnCloud docs?
