### ISSUE TITLE
Changing sharing password activates default sharing expiration date

### ISSUE THREAD

**Issue by 8191** [owncloud/core#19685]
### Steps to reproduce
1. Configure "Set default expiration date" for link shares in admin panel
2. Share a folder by link; the default expiration time is applied
3. Uncheck the default expiration date
4. Set a password

### Expected behaviour
The default expiration date is applied again.

### Actual behaviour
The password should be set without affecting the expiration date.

### Server configuration
**Operating system**: CentOS 6.6

**Web server:** Apache httpd 2.2.15

**Database:** MySQL 5.1.73

**PHP version:** PHP 5.4.43

**ownCloud version:** 8.1.3

**Updated from an older ownCloud or fresh install:** updated several times since ownCloud 4.0.1

**List of activated apps:** Activity, Deleted files, External storage support, First Run Wizard, PDF Viewer, Pictures, Share Files, Text Editor, Video Viewer

**Are you using external storage, if yes which one:** N/A

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** N/A

### Client configuration
**Browser:** Firefox 41.0.1

**Operating system:** Fedora 22

#### Web server error log
No output shown

#### ownCloud log (data/owncloud.log)
No output shown

#### Browser log
No output shown in JS console

**Comment by MorrisJobke** [comment]
@rullzer This also happens on current master. I guess the logic to detect the "default date needs to be applied" is "apply the default date when no date is set" but should be "apply the default date when no date is set and the share is created"

**Comment by rullzer** [comment]
@MorrisJobke yes you are correct... Will fix.

**Comment by rullzer** [comment]
PR in #22192
