### ISSUE TITLE
Get rid of the ludicrous gap between the last row and the footer on public files lists

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19687]
![mind_the_gap](https://cloud.githubusercontent.com/assets/323220/10411780/ccf886be-6f71-11e5-8c9e-6128405999c3.png)

@Henni - As discussed

I'm thinking it can go back to 60px

**Comment by MorrisJobke** [comment]
cc @owncloud/designers

**Comment by jancborchardt** [comment]
We can go a bit lower, but there should always be some whitespace there to signify the end of the list, and to make reading more comfortable. Otherwise the lowest files always stick to the bottom of the screen.

**Comment by oparoz** [comment]
Yes, there needs to be a 60-100px gap, but this unnecessarily brings out the scrollbar in many cases and some users do scroll to see what they're missing.

**Comment by schiesbn** [comment]
we should only fix important bugs in maintenance releases. cc @cmonteroluque move milestone to 9.0 ?

**Comment by DeepDiver1975** [comment]
> we should only fix important bugs in maintenance releases. cc @cmonteroluque move milestone to 9.0 ?

yes

**Comment by cmonteroluque** [comment]
@schiesbn @DeepDiver1975 well, it's true that we prioritize bugs for maintenance releases. Important is too ill-defined to be a useful definition point.

**Comment by PVince81** [comment]
moving to backlog for now, PRs welcome. From what I remember this is quite a tricky bit of CSS...

@owncloud/design
