### ISSUE TITLE
External storage overview: Add link to personal settings

### ISSUE THREAD

**Issue by tflidd** [owncloud/core#19692]
When no external storage is configured, a messages shows:
![oc_rep](https://cloud.githubusercontent.com/assets/8111200/10417068/864aff94-702f-11e5-84b4-1679825ac4f8.png)

For better user experience: Can you add a link from "personal settings" in the message?

**Comment by karlitschek** [comment]
@jancborchardt

**Comment by jancborchardt** [comment]
Yeah, good call! @schiesbn @PVince81 is it possible to add a button there as individual message? Below the text there should be a button saying:

> Add external storage

which then leads to the personal settings, anchoring to the external storage section.
