### ISSUE TITLE
Upgrade 8.1 -> 8.2beta1 yields error in OCC

### ISSUE THREAD

**Issue by danimo** [owncloud/core#19695]
# Expected behavior

After upgrading the source, but before running `occ upgrade`, when running e.g. `occ help`, only expected output is shown

# Actual behavior

After upgrading the source, but before running `occ upgrade`, when running e.g. `occ help`, the following error is displayed after the actual output:

```
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.oc_file_locks' doesn't exist' in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91
Stack trace:
#0 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(Array)
#1 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(989): Doctrine\DBAL\Driver\PDOStatement->execute(Array)
#2 /var/www/owncloud/lib/private/db/connection.php(203): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM `oc...', Array, Array)
#3 /var/www/owncloud/lib/private/lock/dblockingprovider.php(175): OC\DB\Connection->executeUpdate('DELETE FROM `*P...', Array)
#4 /var/www/owncloud/lib/private/lock/dblockingprovider.php(179): OC\Lock\DBLockingProvider->cleanEmptyLocks()
#5 [internal function]: OC\Lock\DBLockingProvider->__destruct()
#6 {main}
```

**Comment by LukasReschke** [comment]
cc @icewind1991 Any idea? THX.

**Comment by LukasReschke** [comment]
@jnweiger also had this last week in nuremberg.
@cmonteroluque We should fix this before 8.2.

**Comment by PVince81** [comment]
Sounds like a duplicate, but can't find the original any more where there was a discussion about catching an exception in the destructor of the lock manager. @nickvergessen @icewind1991 do you remember ?

**Comment by icewind1991** [comment]
Fixed with https://github.com/owncloud/core/pull/19644
