### ISSUE TITLE
[8.2] Handling of trash-bin

### ISSUE THREAD

**Issue by tflidd** [owncloud/core#19694]
On large screens, why are the symbols to delete or to restore files not directly accessible? It's not very handy to click on the three points and select the action every time.

![oc-trash](https://cloud.githubusercontent.com/assets/8111200/10417617/b737cee4-7042-11e5-882c-ac9843e2ac4d.png)

(I know you can choose some files and there will be an additional menu on top).

**Comment by MorrisJobke** [comment]
cc @owncloud/designers

**Comment by cmonteroluque** [comment]
I don't think this is 8.2 at this point

**Comment by jancborchardt** [comment]
Right, good point. In the Deleted files section, restore should be the action which is always outside of the menu, just like share is in the normal Files view.

@PVince81 @MorrisJobke @schiesbn @owncloud/designers ok?

**Comment by PVince81** [comment]
@jancborchardt and the menu will have a single action which is "Delete" ?

**Comment by jancborchardt** [comment]
@PVince81 yes. I guess there could potentially be other things in the menu like »Download«.

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/19701
