### ISSUE TITLE
Sidebar: Selecting files sometimes marks other files as selected

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#19698]
Newest master. In folders with a huge amount of files (and some random other cases) when selecting a single file (here `4_oC_Security_MS.pptx`) another one (`35.1.9 DfPR Stimmen je Kand und Gde.xlsx`) gets displayed as hovered and the layout looks messed up.

![2015-10-11_23-52-42](https://cloud.githubusercontent.com/assets/878997/10419293/3a0dbb1e-7073-11e5-9986-2ba7abe60e8b.png)

**Comment by karlitschek** [comment]
@PVince81 what do you think?

**Comment by PVince81** [comment]
@LukasReschke does the layout issue happen for a specific browser width ?

Regarding the confusing highlights, see "Too many highlight types": #18210

**Comment by LukasReschke** [comment]
> @LukasReschke does the layout issue happen for a specific browser width ?

"specific browser width"? Care to elaborate?

**Comment by PVince81** [comment]
Does it happen with any browser window width ?
The layout might not be pefect in some narrower widths.

I'll try and reproduce this one later today.

**Comment by PVince81** [comment]
Layout looks fine for me in Chromium 45.0.2454.99 (64-bit) on master (e16ac12f5a9b4537c97b3fdecbdbee68e706b587)
![layout-looks-fine](https://cloud.githubusercontent.com/assets/277525/10424614/d2332ed0-70d0-11e5-817c-b5e95493a1cf.png)

**Comment by oparoz** [comment]
I think this is related to #18210 . It usually happens when having pressed shirt or ctrl at some point.

**Comment by PVince81** [comment]
@LukasReschke mind providing the exact steps ?

**Comment by LukasReschke** [comment]
Mhm. It happens rather  randomly here. Let me see if I can find something that triggers it.

**Comment by LukasReschke** [comment]
I'm confused, now it only highlights the file size column for me:

![2015-10-14_00-53-26](https://cloud.githubusercontent.com/assets/878997/10470511/014aafac-720e-11e5-88af-fcbb593dc979.png)

Is this the expected behaviour?

**Comment by PVince81** [comment]
No. It only ever should highlight the whole row.

Next time it happens can you use the DOM inspector and see whether the "highlighted" class is properly set on the "tr" or whether it somehow slipped to that column's "td" ?

**Comment by PVince81** [comment]
This is a bug in the rendering engine for Chrome 43.
I have been able to reproduce it after zooming out and switching before "Share with link" and "All files".

Also, zooming out further when the glitch appears makes it even more glitchy.
The CSS looks fine, so it's nothing that we can fix directly.

I don't want to start working around Chrome bugs that are likely to be fixed in their next update.

@LukasReschke @oparoz can you post your chrome version ?

**Comment by PVince81** [comment]
Sorry, it's actually Chrome 45, not 43

**Comment by LukasReschke** [comment]
Fair point. Also I can only reproduce this on my external screen so seems to be indeed an upstream bug. Closing then.
