### ISSUE TITLE
[8.2] External share overview shows no entries in single user mode

### ISSUE THREAD

**Issue by tflidd** [owncloud/core#19691]
### Steps to reproduce
1. Use OC 8.2 in single user mode
2. Add external SFTP storage
3. Go to files -> you can scan through external storage
4. Go to files -> External storage (select from overview on the left side)
### Expected behaviour

SFTP storage should show up
### Actual behaviour

List is empty!
Disabling the single user mode, the SFTP storage is shown.
### Server configuration

**Operating system**: Debian 8.0 (Jessie)

**Web server:** Apache

**Database:** Mysql

**ownCloud version:** ownCloud 8.2 RC1 (daily) Build:2015-10-11T03:37:52+00:00 188acd5e4e4bf9e35e327ecf8389c75ead744732 
from SuSE repo (nightly)

**Updated from an older ownCloud or fresh install:** Updated

**List of activated apps:**

```
Enabled:
  - activity: 2.1.3
  - files: 1.1.11
  - files_external: 0.2.3
  - files_locking: 
  - files_pdfviewer: 0.7
  - files_sharing: 0.6.3
  - files_texteditor: 2.0
  - files_trashbin: 0.6.3
  - files_versions: 1.0.6
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - provisioning_api: 0.2
  - templateeditor: 0.1
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'ocbhjjaeth7b',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' =>
  array (
    0 => 'xxx',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://xxx/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.2.0.9',
  'dbname' => 'owncloud-osdfj',
  'dbhost' => 'localhost',
  'dbtableprefix' => '',
  'dbuser' => 'oc_admin1',
  'dbpassword' => 'xxx',
  'logtimezone' => 'UTC',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_from_address' => 'xxx',
  'mail_domain' => 'xxx',
  'mail_smtpauth' => 1,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => 'xxx',
  'mail_smtpport' => '587',
  'mail_smtpname' => 'xxx',
  'mail_smtppassword' => 'xxx',
  'singleuser' => true,
  'loglevel' => 2,
);
```

**Are you using external storage, if yes which one:** sftp

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
#### ownCloud log (data/owncloud.log)

```
{"reqId":"sYftRRrRZh101swxR7Wb","remoteAddr":"my-ip","app":"PHP","message":"file_get_contents(\/var\/www\/owncloud\/resources\/config\/\/mimetypealiases.dist.json): failed to open stream: No such file or directory at \/var\/www\/owncloud\/lib\/private\/files\/type\/detection.php#115","level":3,"time":"2015-10-11T13:16:52+00:00"}
```

**Comment by MorrisJobke** [comment]
cc @Xenopathic @PVince81

**Comment by PVince81** [comment]
This is because single user mode is almost like maintenance mode. The Share API is returning "503 Service Not Available". Maybe the sections should simply be removed in this mode ?

**Comment by PVince81** [comment]
Similar to https://github.com/owncloud/core/issues/16597

**Comment by PVince81** [comment]
Need better general support for single user mode. Closing in favor of https://github.com/owncloud/core/issues/16597
