### ISSUE TITLE
8.2RC2: Bar overlaps scroll bar

### ISSUE THREAD

**Issue by danimo** [owncloud/core#19696]
# Expected behavior

Bar shown when selecting at least one item displays does not overlap scroll bar.

# Actual behavior

![image](https://cloud.githubusercontent.com/assets/1315934/10419198/0c2f5a84-7070-11e5-840d-35e4c7074bac.png)

**Comment by oparoz** [comment]
It's a duplicate, but I can't find the original... I think @PVince81 and @jancborchardt were talking about how to fix this, so let's ask them if this solution is OK :)

**Comment by MorrisJobke** [comment]
This is fixed afaik. Let me search for the fix.

**Comment by MorrisJobke** [comment]
Should be fixed by #19539

**Comment by MorrisJobke** [comment]
@danimo There is also no 8.2RC2 :see_no_evil: https://github.com/owncloud/core/releases

**Comment by MorrisJobke** [comment]
Just talked to @danimo - This will be fixed with RC2 ;)

**Comment by MorrisJobke** [comment]
> Just talked to @danimo

He said, that RC2 was a typo and it was tested with RC1

**Comment by danimo** [comment]
Fixing title for retrospective clarity.
