### ISSUE TITLE
File list summary bugged when file is edited

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#19709]
1. Create a folder
2. Create a file inside
3. Edit file
4. Look at summary: `2 files 5 kB` :x:  should be only 1 file
5. Delete file
6. Look at summary: `1 file  3 kB` :x: should be gone

@PVince81

**Comment by PVince81** [comment]
Additional note: editing must be done with the text editor app, which contains code to tell the file list to update the row

**Comment by PVince81** [comment]
https://github.com/owncloud/core/blob/v8.2RC1/apps/files/js/filelist.js#L1674

**Comment by PVince81** [comment]
Old issue. Reopen if issue persists with 10.0.4.
