### ISSUE TITLE
scrollto parameter not working on trashbin view of the file list

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#19707]
Would be nice to have,
[`scrollTo: urlParams.scrollto`](https://github.com/owncloud/core/blob/master/apps/files/js/app.js#L74) is missing from [`OCA.Trashbin.FileList(`](https://github.com/owncloud/core/blob/master/apps/files_trashbin/js/app.js#L26)

@PVince81

**Comment by PVince81** [comment]
Likely to be missing on other file list views too (shared with you, etc).
