### ISSUE TITLE
improved the way we handle part-files

### ISSUE THREAD

**Issue by schiessle** [owncloud/core#19706]
We had a issue with the way we handle .part files here https://github.com/owncloud/core/issues/17997. This was fixed with a minimal approach for 8.2 but in the long run I think we should try to improve it in general.

Two possible solutions where discussed:
1. Only skip .part-files if they are located in data/user/files so that metadata are not affected by the limitation.
2. Don't filter the part-files on a file cache level at all. The file cache should always maintain a consistent few of all files stored at the ownCloud server. This is especially important if it comes to object storages where we need to have a mapping between file name and object id no matter if it is a part-file or whatever. To avoid that the user sees the part-file in the files list or that the sync client tries to download it we should filter the part-files during output right before they leave ownCloud. At the moment this would be two end-points, the web view output and webdav but if we manage to move the web-ui to webdav there would be exactly one path where we have to apply the filter.

Option 2 is my favorite approach because I think it could reduce complexity a lot and would give us a consistent internal view on all files stored at the ownCloud

cc @icewind1991 @PVince81 @DeepDiver1975 @karlitschek @cmonteroluque

**Comment by icewind1991** [comment]
I would prefer 2 and minimize the amount of part files in the cache by not writing intermediate state to the cache

**Comment by PVince81** [comment]
also slightly related: chunk files are also indexed: https://github.com/owncloud/core/issues/17895
