### ISSUE TITLE
Insane logging spam when using custom CA certs

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19713]
OK, it only happens in debug mode, but still. This is a pain when trying to debug other stuff

I get millions of messages like this
`Debug	files_locking	INFO: Incrementing lock type 1 count for data/admin/files_external/uploads/ca-bundle.crt`

just because I'm using custom CA certs.

So, [this](https://github.com/owncloud/core/issues/17845) is badly needed, but in the mean time, is it really necessary to get a lock on that file? If we can't make the difference between that file an other stuff in "uploads", is it really the best place for the certs?

@PVince81 @MorrisJobke @LukasReschke

**Comment by PVince81** [comment]
Disable files_locking in 8.2. The app won't be shipped there any more.

**Comment by oparoz** [comment]
Ah and on 8.1? It doesn't happen? Or it doesn't matter because the app can be disabled?

**Comment by PVince81** [comment]
The app can be disabled on 8.1.

The message is apparently because any file that is accessed under "data/" if going through that app's locking.

**Comment by oparoz** [comment]
OK, so closing and the solution is to never use the files_locking app when debugging.

**Comment by oparoz** [comment]
Thanks!
