### ISSUE TITLE
Rename TLS encryption for SMTP connection to STARTTLS

### ISSUE THREAD

**Issue by krichter722** [owncloud/core#19726]
According to the [email configuation section in the 8.1 admin manual](https://doc.owncloud.org/server/8.1/admin_manual/configuration_server/email_configuration.html) choosing `TLS` establishes a STARTTLS connection to the SMTP server which is misleading because TLS and STARTTLS isn't the same. STARTTLS would be a better name for that option.

experienced with 8.1.3 with apache 2.4 running on Ubuntu 15.04

**Comment by RealRancor** [comment]
Hi,

please re-open in https://github.com/owncloud/documentation/issues

**Comment by krichter722** [comment]
https://github.com/owncloud/documentation/issues/1778
