### ISSUE TITLE
Chrome says: "Resource interpreted as Document but transferred with MIME type application/vnd.openxmlformats-officedocument.presentationml.presentation"

### ISSUE THREAD

**Issue by rakesh-sankar** [owncloud/core#19725]
When I try to download the copy of my file on my latest stable version of Chrome on Windows 7, I get noticed the above problem and the file is not getting downloaded.

**Comment by PVince81** [comment]
Please use the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md
