### ISSUE TITLE
Mention failing file in database file error message

### ISSUE THREAD

**Issue by krichter722** [owncloud/core#19721]
Messages in the form of

    Error while trying to create admin user: An exception occurred while executing 'CREATE TABLE "oc_appconfig" ("appid" VARCHAR(32) DEFAULT '' NOT NULL, "configkey" VARCHAR(64) DEFAULT '' NOT NULL, "configvalue" CLOB DEFAULT NULL, PRIMARY KEY("appid", "configkey"))': SQLSTATE[HY000]: General error: 14 unable to open database file 

should contain the information which file they refer to, otherwise they're utterly useless, e.g.

    Error while trying to create admin user: An exception occurred while executing 'CREATE TABLE "oc_appconfig" ("appid" VARCHAR(32) DEFAULT '' NOT NULL, "configkey" VARCHAR(64) DEFAULT '' NOT NULL, "configvalue" CLOB DEFAULT NULL, PRIMARY KEY("appid", "configkey"))': SQLSTATE[HY000]: General error: 14 unable to open database file [absolute path to file]

experienced with 8.1.3 running on apache 2.4 on Ubuntu 15.04

**Comment by RealRancor** [comment]
Database file is your /path/to/owncloud/data/owncloud.db which is the default sqlite install. As SQLite is not recommended anyway its recommended to switch to MySQL/PostgreSQL.

**Comment by RealRancor** [comment]
Yes, seems nothing oC specific:

http://fredericiana.com/2014/11/29/sqlite-error-open-database-file/

**Comment by krichter722** [comment]
Agreed, yet that's a very generic answer. Imo one should either wrap bad/unhelpful error messages of dependencies (how many million useless "service could not be started: No such file or directory" error message have and will we seen in our lives?), i.e. catch and enhance them, or solve the problem at its root (in case it's an open source or free dependency by contributing) or (in case it's a proprietary dependency hope for a speedy death of the enterprise which sells such a product and use it's successor improvements).

There's no way to sell a car with three wheels and claim that you depend on the axle supplier deliveries, but you recommend to google for a stuntwo_man course how to drive with three wheels only.

**Comment by RealRancor** [comment]
In this case its probably the best to complain at upstream (PHP) instead of expecting that each application is solve this on its own.

**Comment by MorrisJobke** [comment]
This is out of scope for ownCloud and needs to be fixed in the sqlite PHP module. Therefore I will close this one here
