### ISSUE TITLE
Review logging format with \\\\\\ between each word

### ISSUE THREAD

**Issue by krichter722** [owncloud/core#19720]
Logging entries in the form of 

    [Mon Oct 12 22:51:19.742645 2015] [:error] [pid 27265] [client 192.168.179.2:34000] {"reqId":"u10OK5vBNUfzQvO4Bkt6","remoteAddr":"192.168.179.2","app":"index","message":"Exception: {\\"Exception\\":\\"Doctrine\\\\\\\\DBAL\\\\\\\\DBALException\\",\\"Message\\":\\"Failed to connect to the database: An exception occurred while executing 'PRAGMA journal_mode = WAL':\\\\n\\\\nSQLSTATE[HY000]: General error: 14 unable to open database file\\",\\"Code\\":0,\\"Trace\\":\\"#0 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/3rdparty\\\\\\/doctrine\\\\\\/dbal\\\\\\/lib\\\\\\/Doctrine\\\\\\/DBAL\\\\\\/Connection.php(973): OC\\\\\\\\DB\\\\\\\\Connection->connect()\\\\n#1 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/lib\\\\\\/private\\\\\\/db\\\\\\/connection.php(151): Doctrine\\\\\\\\DBAL\\\\\\\\Connection->executeUpdate('PRAGMA read_unc...', Array, Array)\\\\n#2 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/3rdparty\\\\\\/doctrine\\\\\\/dbal\\\\\\/lib\\\\\\/Doctrine\\\\\\/DBAL\\\\\\/Connection.php(621): OC\\\\\\\\DB\\\\\\\\Connection->executeUpdate('PRAGMA read_unc...')\\\\n#3 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/lib\\\\\\/private\\\\\\/db\\\\\\/connection.php(83): Doctrine\\\\\\\\DBAL\\\\\\\\Connection->setTransactionIsolation(2)\\\\n#4 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/3rdparty\\\\\\/doctrine\\\\\\/dbal\\\\\\/lib\\\\\\/Doctrine\\\\\\/DBAL\\\\\\/DriverManager.php(172): OC\\\\\\\\DB\\\\\\\\Connection->__construct(Array, Object(Doctrine\\\\\\\\DBAL\\\\\\\\Driver\\\\\\\\PDOSqlite\\\\\\\\Driver), Object(Doctrine\\\\\\\\DBAL\\\\\\\\Configuration), Object(Doctrine\\\\\\\\Common\\\\\\\\EventManager))\\\\n#5 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/lib\\\\\\/private\\\\\\/db\\\\\\/connectionfactory.php(124): Doctrine\\\\\\\\DBAL\\\\\\\\DriverManager::getConnection(Array, Object(Doctrine\\\\\\\\DBAL\\\\\\\\Configuration), Object(Doctrine\\\\\\\\Common\\\\\\\\EventManager))\\\\n#6 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/lib\\\\\\/private\\\\\\/server.php(301): OC\\\\\\\\DB\\\\\\\\ConnectionFactory->getConnection('sqlite3', Array)\\\\n#7 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/3rdparty\\\\\\/pimple\\\\\\/pimple\\\\\\/src\\\\\\/Pimple\\\\\\/Container.php(112): OC\\\\\\\\Server->OC\\\\\\\\{closure}(Object(OC\\\\\\\\Server))\\\\n#8 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/lib\\\\\\/private\\\\\\/appframework\\\\\\/utility\\\\\\/simplecontainer.php(96): Pimple\\\\\\\\Container->offsetGet('DatabaseConnect...')\\\\n#9 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/lib\\\\\\/private\\\\\\/server.php(696): OC\\\\\\\\AppFramework\\\\\\\\Utility\\\\\\\\SimpleContainer->query('DatabaseConnect...')\\\\n#10 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/lib\\\\\\/private\\\\\\/db.php(42): OC\\\\\\\\Server->getDatabaseConnection()\\\\n#11 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/lib\\\\\\/private\\\\\\/server.php(209): OC_DB::getConnection()\\\\n#12 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/3rdparty\\\\\\/pimple\\\\\\/pimple\\\\\\/src\\\\\\/Pimple\\\\\\/Container.php(112): OC\\\\\\\\Server->OC\\\\\\\\{closure}(Object(OC\\\\\\\\Server))\\\\n#13 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/lib\\\\\\/private\\\\\\/appframework\\\\\\/utility\\\\\\/simplecontainer.php(96): Pimple\\\\\\\\Container->offsetGet('AppConfig')\\\\n#14 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/lib\\\\\\/private\\\\\\/server.php(642): OC\\\\\\\\AppFramework\\\\\\\\Utility\\\\\\\\SimpleContainer->query('AppConfig')\\\\n#15 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/lib\\\\\\/private\\\\\\/server.php(343): OC\\\\\\\\Server->getAppConfig()\\\\n#16 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/3rdparty\\\\\\/pimple\\\\\\/pimple\\\\\\/src\\\\\\/Pimple\\\\\\/Container.php(112): OC\\\\\\\\Server->OC\\\\\\\\{closure}(Object(OC\\\\\\\\Server))\\\\n#17 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/lib\\\\\\/private\\\\\\/appframework\\\\\\/utility\\\\\\/simplecontainer.php(96): Pimple\\\\\\\\Container->offsetGet('AppManager')\\\\n#18 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/lib\\\\\\/private\\\\\\/server.php(862): OC\\\\\\\\AppFramework\\\\\\\\Utility\\\\\\\\SimpleContainer->query('AppManager')\\\\n#19 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/lib\\\\\\/private\\\\\\/app.php(238): OC\\\\\\\\Server->getAppManager()\\\\n#20 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/lib\\\\\\/private\\\\\\/app.php(93): OC_App::getEnabledApps()\\\\n#21 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/lib\\\\\\/base.php(592): OC_App::loadApps(Array)\\\\n#22 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/lib\\\\\\/base.php(1122): OC::init()\\\\n#23 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/index.php(38): require_once('\\\\\\/var\\\\\\/www\\\\\\/ownclo...')\\\\n#24 {main}\\",\\"File\\":\\"\\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/lib\\\\\\/private\\\\\\/db\\\\\\/connection.php\\",\\"Line\\":50}","level":4,"time":"2015-10-12T20:51:19+00:00"}

shouldn't occur.

experienced with 8.1.3 running on apache 2.4

**Comment by karlitschek** [comment]
@LukasReschke Maybe some oversanitization  going on here? :-)

**Comment by DeepDiver1975** [comment]
The log file is json encoded and is a technical format - not made for human reading (a long discussed issue somewhere here on github)

@krichter722 how is the message displayed in the log viewer in the admin section?

**Comment by krichter722** [comment]
In the file specified as `ErrorLog` in the apache `VirtualHost` directive. My log file `/var/log/owncloud.log` is always empty.

**Comment by RealRancor** [comment]
> My log file /var/log/owncloud.log is always empty.

That should be /var/www/owncloud/data/owncloud.log as oC is not writing into /var/log/owncloud.log as a default.

**Comment by DeepDiver1975** [comment]
> @krichter722 how is the message displayed in the log viewer in the admin section?

@krichter722 please answer my question - screenshot is valid as well - THX

**Comment by krichter722** [comment]
> That should be /var/www/owncloud/data/owncloud.log as oC is not writing into /var/log/owncloud.log as a default.

Right (don't know where `/var/log/owncloud.log` came from), but in `/var/www/owncloud/data/owncloud.log` is the same issue.

> @krichter722 how is the message displayed in the log viewer in the admin section?

In the admin view every `/` is escaped with `\` which seems to result in escaping of the escaping result of the escaping result of ... at some point. I don't see a reason to escape `/` at all.

**Comment by MorrisJobke** [comment]
I can't reproduce this anymore. Exceptions contain usually `\\\\` between each namespace hierarchy because this is a JSON object (error object) within a JSON object (log line) and this escaping is fine.

Feel free to reopen if you still see the 8 \ in the log lines.
