### ISSUE TITLE
New-style checkboxes lost again in some places

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#19724]
Where did they go @Henni @owncloud/designers? ;)

Sharing admin settings cc @schiesbn 
![capture du 2015-10-13 13-00-35](https://cloud.githubusercontent.com/assets/925062/10441912/8035b1e0-71aa-11e5-8da7-b1910113f6d5.png)

Notification settings (bottom two checkboxes) cc @nickvergessen 
![capture du 2015-10-13 13-00-24](https://cloud.githubusercontent.com/assets/925062/10441913/803bf05a-71aa-11e5-8137-0aba9b1bffdd.png)

**Comment by nickvergessen** [comment]
For milestones and sev labels please ask cml to set them.

This is also not a regression, but an incomplete fix. But at least they work, so it's not that critical.

**Comment by MorrisJobke** [comment]
> Where did they go @Henni @owncloud/designers? ;)

They are now opt-in ;)
