### ISSUE TITLE
App menu loading icon is off-center

### ISSUE THREAD

**Issue by Henni** [owncloud/core#19736]
![image](https://cloud.githubusercontent.com/assets/1267827/10452429/40efdd6c-71a5-11e5-98d5-0cfe858a6f4a.png)

In some cases the loading icon in the app menu is shifted to the right.
Appears on Firefox and Chrome.

**Comment by oparoz** [comment]
Maybe you're not up to date with master of Gallery?
https://github.com/owncloud/gallery/pull/415

**Comment by Henni** [comment]
@oparoz thanks!
