### ISSUE TITLE
Add indeterminate style to checkboxes

### ISSUE THREAD

**Issue by Henni** [owncloud/core#19741]
The new checkbox style should support the indeterminate property.
Icons already exist: https://github.com/owncloud/core/blob/master/core/img/actions/checkbox-mixed.png

**Comment by MorrisJobke** [comment]
cc @owncloud/designers

**Comment by jancborchardt** [comment]
Yup. That’s why I added it there. Mostly this will be useful for Files multiselection, and an indicator that only some items are selected.

Also related to https://github.com/owncloud/core/issues/19564

**Comment by jancborchardt** [comment]
@Henni the icons were added some time ago, didn’t you also add the style for it?
