### ISSUE TITLE
sharing a single mp3 file with >= 2 spaces in filename via link results in "No data received"

### ISSUE THREAD

**Issue by comexos** [owncloud/core#19749]
When I share a single mp3 file (e.g. "01 Artist - This is the best song.mp3") via public link, the generated link doesn't return any data (No data received).

If I rename the File to "01 song1.mp3" (only 1 space) or "01 Artist - This is the best song.mp4", unshare the file and share it again (generate a new sharing link), everything works as expected, with the mp4 extension i also get a nice preview where i can play the song.
Also if I add "/download" to the link (e.g. https://cloud.example.com/index.php/s/TcH49mHZ8g3uh9A/download, the download works, so i guess there must be only a problem with the preview page.

i am using the latest stable version 8.1.3 on ubuntu 14.04 with apache 2.4.7 and mod_php 5.5.9.

**Comment by rullzer** [comment]
Mmm that sounds like a preview thing indeed... @oparoz

**Comment by PVince81** [comment]
@comexos is the preview from the music app ? (CC @MorrisJobke)

**Comment by MorrisJobke** [comment]
> is the preview from the music app ?

No. It's build into core. https://github.com/owncloud/core/blob/master/lib/private/preview/mp3.php

**Comment by oparoz** [comment]
>  the generated link doesn't return any data (No data received)

I'm guessing the player shows up, but nothing can be played. In which case it must be a problem with the music file action if that's the one providing the player.

**Comment by comexos** [comment]
@PVince81 i tested it with different owncloud installations, there are no extra apps installed, just the core system
@oparoz nope, nothing shows up, the https request doesn't return any data, not even http headers

**Comment by PVince81** [comment]
Any more luck with 8.2.2 ?

Without a way to reproduce the issue it will be difficult to fix it, if it's really a bug and not an environment problem.

**Comment by comexos** [comment]
unfortunately this bug still exists in 8.2.2
here is a link which produces the error: https://cloud.kaltenbrunner.it/index.php/s/EvnMNI3VSM4q6pW
if i manually append "/download" to the url, the download works: https://cloud.kaltenbrunner.it/index.php/s/EvnMNI3VSM4q6pW/download
@PVince81 just upload this file to an owncloud server and generate a public link, i am pretty sure you can reproduce this error.

**Comment by PVince81** [comment]
Works for me, I'm also running 8.2.2.
I uploaded your file and shared with link:
https://owncloud.vincentpetry.net/index.php/s/kby0CMfqFkAfgIc
and with download: https://owncloud.vincentpetry.net/index.php/s/kby0CMfqFkAfgIc/download

**Comment by PVince81** [comment]
Maybe something is wrong with your SSL certificate or your web server. Maybe you have some PHP modules enabled that mangle the URLs.

Are you using a reverse proxy ?

You haven't used the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by comexos** [comment]
oh sorry you are right, seems to be some memcached issue. I'm going to try it without memcached or redis instead.
### Steps to reproduce
1. upload a mp3 file with more than 2 spaces, e.g. 01 artist - great song.mp3
2. generate a public share link
3. request the generated link with web browser 

### Expected behaviour
preview page with download link

### Actual behaviour
error: no data received

### Server configuration
**Operating system**:
Ubuntu 14.04.4 LTS
**Web server:**
apache 2.4.7-1ubuntu4.9
**Database:**
mariadb 5.5.47-1ubuntu0.14.04.1
**PHP version:**
php 5.5.9+dfsg-1ubuntu4.14
**ownCloud version:** (see ownCloud admin page)
ownCloud 8.2.2 (stable)
**Updated from an older ownCloud or fresh install:**
updated
**Where did you install ownCloud from:**
https://download.owncloud.org/download/repositories/stable/owncloud/
**Signing status (ownCloud 9.0 and above):**
-
**List of activated apps:**
Enabled:
  - activity: 2.1.3
  - files: 1.2.0
  - files_locking: 
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
Disabled:
  - calendar
  - contacts
  - encryption
  - external
  - files_encryption
  - files_external
  - notifications
  - updater
  - user_external
  - user_ldap
  - user_webdavauth
**The content of config/config.php:**
{
    "system": {
        "instanceid": "ocp4w2t2vcrd",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.xxx.tld"
        ],
        "datadirectory": "\/srv\/www\/cloud\/htdocs\/data",
        "overwrite.cli.url": "https:\/\/cloud.xxx.tld",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "cloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "has_internet_connection": true,
        "mail_from_address": "owncloud",
        "mail_smtpmode": "php",
        "mail_domain": "xxx.tld",
        "theme": "",
        "maintenance": false,
        "updatechecker": false,
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "memcache.local": "\\OC\\Memcache\\Memcached",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "trashbin_retention_obligation": "30, auto",
        "log_rotate_size": 104857600,
        "loglevel": 2
    }
}
**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration
**Browser:**
any
**Operating system:**
any
### Logs
#### Web server error log
apache2: libmemcached/storage.cc:341: memcached_return_t memcached_send_ascii(memcached_st*, memcached_server_write_instance_st, const char*, size_t, const char*, size_t, time_t, uint32_t, uint64_t, bool, bool, memcached_storage_action_t): Assertion `memcached_failed(rc)' failed.
[2016-03-01 22:59:41.212182] [notice] [pid 2725] mpm_unix.c(419): [client AH00051: child pid 2772 exit signal Aborted (6), possible coredump in /etc/apache2
#### ownCloud log (data/owncloud.log)
-
#### Browser log
no data received

**Comment by PVince81** [comment]
```
[2016-03-01 22:59:41.212182] [notice] [pid 2725] mpm_unix.c(419): [client AH00051: child pid 2772 exit signal Aborted (6), possible coredump in /etc/apache2
```

You seem to be getting segfaults ?

**Comment by comexos** [comment]
yes it is definitely a bug within memcached on ubuntu 14.04. without memcached it works fine and i don't get segfaults.
i think this issue can be closed, thanks!
