### ISSUE TITLE
Add custom radio input styling

### ISSUE THREAD

**Issue by Henni** [owncloud/core#19743]
We added custom styles for checkboxes in #18735.
To be consistent we should also add custom styles for radio buttons.

@jancborchardt

**Comment by MorrisJobke** [comment]
cc @owncloud/designers

**Comment by jancborchardt** [comment]
Yup. I will add the icons for that soon.

In core we mostly use bare radio buttons in the cron settings. Anywhere else?
Elsewhere like in the installation db chooser, radio-type elements are usually styled as a button-bar (which is correct).

**Comment by jancborchardt** [comment]
@Henni the icons were added, do you want to take care of the rest? The place to test this in core are the Cron settings in Admin.
