### ISSUE TITLE
Show favorites indicator in the list for the Shared with you / others / by link views

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#19753]
Even when an element is favorited, in the 3 share views the star indicator column does not show. It should though, so you can quickly see which items are favorited, and to be able to unfavorite or favorite elements just as you can do in the All files and Favorites views.

@PVince81 @MorrisJobke @schiesbn @owncloud/designers

**Comment by PVince81** [comment]
There are three possible approaches:

1) Make the OCS share API should return the favorite info (and later tags?) along with its response. Might not fit with the API. But we might want to have the share API return the full file info anyway (like a PROPFIND)

2) If not, then the web UI will need to make additional ajax calls to retrieve the favorite/tag information for every file in the list, bad for performance.

3) Provide an additional (private?) endpoint that gets a list of file ids as input and returns the favorite/tag info for each of them. This is also not nice as it's very specific to this use case and also a private call.

Other ideas ?

(also CC @rullzer)

**Comment by PVince81** [comment]
CC @karlitschek @cmonteroluque @DeepDiver1975 for triaging/scheduling

**Comment by rullzer** [comment]
Mmm I'm not a big fan of any of those actually. But option 1 seems like the lesser evil. It just conflicts with my plan to cleanup the Share API output to contain a lot less info.

Let me think how we can solve this properly wihtout to much calls to the server.

**Comment by DeepDiver1975** [comment]
fixes with #26583
