### ISSUE TITLE
2.0.x client not working with Windows 8

### ISSUE THREAD

**Issue by macckone** [owncloud/core#19755]
The 2.0.x client is not working with Windows 8.
Backgrading to 1.8.4 fixed the issue.
Before backgrading I tried removing and reinstalling 2.0.1.
I also tried deleting and resyncing the account on the server.
It did not synchronize.
Backgrading the client worked but the client is attempting to
download and install the newer client.
This is undesirable due to the lack of synchronization under
2.0.x.

**Comment by LukasReschke** [comment]
Please reopen at https://github.com/owncloud/client using the issue template. 

https://github.com/owncloud/client/blob/master/CONTRIBUTING.md#submitting-desktop-client-issues
