### ISSUE TITLE
Fail to open stream with avatars and LDAP

### ISSUE THREAD

**Issue by gig13** [owncloud/core#19750]
### Steps to reproduce
1. Setup LDAP with avatars 
2. Check the owncloud.log for errors with the assumption that the users home directory is named for the internal username instead of the ldap attribute specified (upn in this case)

### Expected behaviour
No errors should be logged in the owncloud.log for avatars

### Actual behaviour
See the following log lines when logging into 8.1.3:

```
Oct 9 12:23:36 rvavdapp23 ownCloud[11187]: {PHP} fopen(/mnt/oc_data/77A57212-EF9F-4E38-AA0D-2E16887650F8/avatar.jpg): failed to open stream: No such file or directory at /var/www/html/owncloud-enterprise/lib/private/files/storage/local.php#257
Oct 9 12:23:36 rvavdapp23 ownCloud[11187]: {PHP} fwrite() expects parameter 1 to be resource, boolean given at /var/www/html/owncloud-enterprise/lib/private/files/storage/wrapper/encryption.php#200
Oct 9 12:23:36 rvavdapp23 ownCloud[11187]: {PHP} fclose() expects parameter 1 to be resource, boolean given at /var/www/html/owncloud-enterprise/lib/private/files/storage/wrapper/encryption.php#201
```

It's looking in the correct data directory (/mnt/oc_data) but looking for an avatar with the assumption that the users home directory is named for the internal username instead of the ldap attribute secified (upn in our case). We also aren't using any kind of encryption within ownCloud. Not sure why this encryption script was run but it the line before these gets to this storage/local.php fopen command. Line 199 runs an fopen function within the same class, and online 431 the local fopen is triggered. It then returns false because the file doesn’t exist. The encryption classes fopen function simply returns this value and it probably should. But in the file_put_contents function (where lines 199-201 live) there really should be a test on the handle that’s performed. Or use @ to suppress warnings on the fwrite and fclose functions. 

### Server configuration
**Operating system**: CentOS 6

**Web server:** Apache

**Database:** MySQL

**PHP version:** php5.5

**ownCloud version:** 8.1.3

**Updated from an older ownCloud or fresh install:** Update

**List of activated apps:** See report configuration

**Are you using external storage, if yes which one:**  See report configuration

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory

#### LDAP configuration (delete this part if not used)
See report configuration

#### ownCloud log (data/owncloud.log)
See above error message

**Comment by MorrisJobke** [comment]
The error messages are the same as #19572

@gig13 Just for clarification: Is the user directory name wrong? As far as I understand you this is the case and they should be different. The question then would be: Why are they wrong. Usually all occurences should have been fixed.

It would also be interesting what their settings look like - especially `./occ ldap:show-config` 

@blizzz Maybe it will be fixed by something like #16961

**Comment by MorrisJobke** [comment]
> @blizzz Maybe it will be fixed by something like #16961

cc @butonic

**Comment by bboule** [comment]
Hey Guys can I assume that the above code #16961 fixes this issue, @gig13 can you confirm?

**Comment by MorrisJobke** [comment]
> @gig13 can you confirm?

Please test with 8.1.4+ or 8.2.0+ ;)

**Comment by MorrisJobke** [comment]
Or better reopen if this is still an issue. I will close this for now.
