### ISSUE TITLE
app:check-code -> Fatal error

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19759]
```
# sudo -uwww-data ./occ app:check-code gallery
Analysing /var/www/owncloud/apps/gallery/middleware/envcheckmiddleware.php
 1 errors
    line  148: OC_User - Static method of private class must not be called
PHP Fatal error:  Call to undefined method PhpParser\Node\Expr\Variable::toString() in /var/www/owncloud/lib/private/app/codechecker/nodevisitor.php on line 172
```

----
@DeepDiver1975 @nickvergessen @MorrisJobke

**Comment by nickvergessen** [comment]
Can you post the code in question?

**Comment by MorrisJobke** [comment]
> PHP Fatal error:  Call to undefined method PhpParser\Node\Expr\Variable::toString() in /var/www/owncloud/lib/private/app/codechecker/nodevisitor.php on line 172

This looks also :fish:y

**Comment by oparoz** [comment]
> Can you post the code in question?

`\OC_User::setIncognitoMode(true);`

**Comment by oparoz** [comment]
OK, so it's not about that static method

`# git checkout -b create-thumbnail-command  origin/create-thumbnail-command`

Then

```
# sudo -uwww-data ./occ app:check-code gallery -vvv
...
Analysing /var/www/owncloud/apps/gallery/command/thumbnails.php
PHP Fatal error:  Call to undefined method PhpParser\Node\Expr\Variable::toString() in /var/www/owncloud/lib/private/app/codechecker/nodevisitor.php on line 172
```

**Comment by oparoz** [comment]
Am I delusional or is the app-checker now checking commands where it wasn't before?
