### ISSUE TITLE
owncloud 8.1.3 IE 11 problems

### ISSUE THREAD

**Issue by jostra** [owncloud/core#19767]
Environment: HomeServer
Server: nginx
Database: mysql
Client: InternetExplorer
OC-Version: 8.1.3
PHP-Version: 5.6.13

I have a problem with IE 11 with not showing everything as it is on firefox or chrome. The same problem is on https://demo.owncloud.org
The a look at this link where I attached some pictures:
https://forum.owncloud.org/viewtopic.php?f=31&t=30864&p=98702#p98702

**Comment by PVince81** [comment]
So basically you are saying that IE11 doesn't show the field placeholders.

Are you sure it's not running in compatibility mode ? If yes, please disable compatibility mode.

**Comment by MorrisJobke** [comment]
Should work: http://caniuse.com/#feat=input-placeholder

**Comment by MorrisJobke** [comment]
Ah yes. This is how it works. Please report this to Microsoft: http://www.html5accessibility.com/tests/placeholder-labelling.html

Close because we can't do anything here.
