### ISSUE TITLE
Unauthorised code doesn't match documentation.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#19761]
### Steps to reproduce

Having a user called 'brand-new-user' not admin and a group called newgroup do:
```
curl -X POST http://brand-new-user:123456@HOST/ocs/v1.php/cloud/users/brand-new-user/groups -d groupid="newgroup"
```

### Expected behaviour
According to documentation it should return 104 - insufficient priviliges:
https://doc.owncloud.org/server/8.2/admin_manual/configuration_user/user_provisioning_api.html#users-addtogroup

### Actual behaviour

It returns code 997 instead of 104.

```
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>997</statuscode>
  <message>Unauthorised</message>
 </meta>
 <data/>
</ocs>
````
The number is variable.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.2.0.9","versionstring":"8.2 RC1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No.

**Comment by SergioBertolinSG** [comment]
I don't know if this is the returned code is correct and the documentation is wrong.
cc @DeepDiver1975

**Comment by LukasReschke** [comment]
Please use http://lukasreschke.github.io/OpenCloudMeshSpecification/ instead of the existing documentation. The existing documentation has a lot of mistakes in it. 

Bug reports welcome at https://github.com/LukasReschke/OpenCloudMeshSpecification/issues, we can correct our docs with this data then once corrected.

**Comment by SergioBertolinSG** [comment]
Thanks @LukasReschke , so documentation will need all this info.

**Comment by LukasReschke** [comment]
Correct.
