### ISSUE TITLE
Error numbers added in the sharing error message

### ISSUE THREAD

**Issue by rperezb** [owncloud/core#19788]
### Steps to reproduce

Errors should contain paths and not internal ids on any error situation, such as:

- [x] Share with the owner, error 32 #19727 (comment)
- [x] Disable allow resharing, error 29
- [x] Disable share outside the group
- [ ] Disable sharing API

Related to: https://github.com/owncloud/core/issues/19678

**Comment by rperezb** [comment]
cc @rlindner

**Comment by rullzer** [comment]
> *Share with the owner, error 32 #19727 (comment)

Let me look into this one first

**Comment by rullzer** [comment]
PR for the first bullet in #19820

**Comment by rullzer** [comment]
> * Disable allow resharing, error 29
> * Disable sharing API

The error code should be fixed. But please also check the capabilities API for those. So that you do not even have to send the request.

**Comment by rperezb** [comment]
@rullzer yes, you are right, this is on our list 
We plan to check the capabilities for the next iteration of this feature 
cc @MTRichards

**Comment by PVince81** [comment]
@rullzer @rperezb any update ? are all cases fixed ?

**Comment by rullzer** [comment]
@PVince81 not yet.

**Comment by rperezb** [comment]
on the mobile apps we are implementing to check capabilities  API.

However, please notice that disable allow resharing can be checked individually, when you are sharing a file, so this needs to be taken into account here too.

**Comment by rullzer** [comment]
* Disable allow resharing, error 29

I just checked that one is fixed

**Comment by rullzer** [comment]
Ok so the last bullet is really a pain to fix in the old code. Since it can happen at so many places. Since this is for 8.2.1 and in 8.2 we already have the capabilities to indicate if sharing is enabled or not. Lets close this.
