### ISSUE TITLE
Fetching avatar from LDAP only work on second fetch

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#19785]
* fire up LDAP with avatars (see owncloud/administration#59)
* setup the LDAP server on core master (fill out only first page of wizard - click continue untill the end and set 20 seconds as TTL)
* login as LDAP user

### expected

* having the avatar fetched from LDAP

### actual

* no avatar set
* need to logout, remove the corresponding `lastFeatureRefresh` from oc_preferences and relogin as this user
* avatar is now loaded

cc @davitol @blizzz

**Comment by blizzz** [comment]
should be resolved

**Comment by davitol** [comment]
@blizzz yes, it is solved.
