### ISSUE TITLE
When getting an empty list of group subadmins an unknown error is returned.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#19789]
### Steps to reproduce

Having  a group called newgroup and a user called 'brand-new-user' not admin and not subadmin of group newgroup do:
```
curl -X GET http://USER:PASSWORD@HOST/ocs/v1.php/cloud/groups/newgroup/subadmins
```

### Expected behaviour

Perhaps return an empty list.

### Actual behaviour

It returns 400 Unknown error (using v2.php) and 102 Unknown error (using v1.php)

```
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>400</statuscode>
  <message>Unknown error occured</message>
 </meta>
 <data/>
</ocs>
```

```
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>102</statuscode>
  <message>Unknown error occured</message>
 </meta>
 <data/>
</ocs>
```

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.2.0.9","versionstring":"8.2 RC1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No.

**Comment by PVince81** [comment]
@tomneedham
