### ISSUE TITLE
Nice new README.md

### ISSUE THREAD

**Issue by aspdye** [owncloud/core#19792]
Hi there,

I think we should create new (nice looking) README.md's for the ownCloud-Repositories, like shown in https://github.com/owncloud/mail.

-Screenshot
-More Details about what the Repository does
-...

**Comment by LukasReschke** [comment]
Pull request welcome :smile:

**Comment by aspdye** [comment]
I Work on it ;)

**Comment by LukasReschke** [comment]
:rocket: :dancer: :beers: :wink:
