### ISSUE TITLE
feature req: deny certain fyle types or by mimes! by configuration file

### ISSUE THREAD

**Issue by mckaygerhard** [owncloud/core#19798]
Feature request to made a config part to list mymes or file types not allowed to upload to storage users!

### Steps to reproduce
1. upload a files with deny extension (a guindow file type from office)
2. file are uploaded

### Expected behaviour
Users must have a message about deny files or not alowed to upload a certain file types

### Actual behaviour
Any king of files can be uploaded

### Server configuration
**Operating system**:
Debian
**Web server:**
Lighttpd
**Database:**
Postgresql enterprise
**PHP version:**
5.3
**ownCloud version:** (see ownCloud admin page)
7.0.5
**Updated from an older ownCloud or fresh install:**
fresh install
**List of activated apps:**
storagecharts2, roundcube, games2, dashboard, editdoc

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'occfeacce759',
  'passwordsalt' => '9acba09bc045f2a86d5757a9e16b1a',
  'secret' => '9a39b6d7c7aea50c885e8ea8421d34c4f21c55e49051ceff363e616545d094dcc1b1e2ff551545be4f9e503a762bacac',
  'trusted_domains' => 
  array (
    0 => 'itsnotyourbussines.net.ve',
    1 => 'XXXX.XX.X.X',
    2 => '192.168.1.0',
  ),
  'datadirectory' => '/var/data/oc/data',
  'dbtype' => 'pgsql',
  'dbname' => 'simplenet',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'installed' => true,
  'updatechecker' => false,
  'knowledgebaseenabled' => false,
  'enable_avatars' => false,
  'allow_user_to_change_display_name' => false,
  'check_for_working_htaccess' => false,
  'enable_previews' => true,
  'preview_libreoffice_path' => '/opt/openoffice4/program/soffice',
  'preview_office_cl_parameters' => ' --headless --nologo --nofirststartwizard --invisible --norestore ',
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\Movies',
    1 => 'OC\\Preview\\SVG',
    2 => 'OC\\Preview\\Image',
   3 => 'OC\\Preview\\MP3',
    4 => 'OC\\Preview\\TXT',
    5 => 'OC\\Preview\\MarkDown',
    6 => 'OC\\Preview\\Html',
  ),
  'trashbin_retention_obligation' => 10,
  'loglevel' => '0',
  'xframe_restriction' => false,
  'theme' => 'mycore',
  'defaultapp' => 'dashboard',
  'appstoreenabled' => false,
  'custom_csp_policy' => 'default-src \'self\'; script-src \'self\' \'unsafe-inline\' \'unsafe-eval\'; style-src \'
self\' \'unsafe-inline\'; frame-src *; img-src *; font-src \'self\' data:; media-src *',
);
```

**Are you using encryption:**  no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**
Chromium on all clients version 13 and 17
**Operating system:**
Linux VenenuX on all clients 0.9

**Comment by RealRancor** [comment]
Ref: https://owncloud.com/features/#FileFirewall

**Comment by RealRancor** [comment]
Still this is a valid request. You can.also have a look at https://github.com/owncloud/core/issues/1141#issuecomment-75770209 for now.

Btw. you should also update to at least the latest stable of oC 7 as your 7.0.5 contains various security vulnerabilities:

**Comment by mckaygerhard** [comment]
wheantime in which line can i made that hardcoded?

and hey @RealRancor i not request for paid services, i request for a feature in oc stable releases! why this propaganda!

and my oc 7.0.5 does not use intenral thirt party php proyects, i thing oc must let appart that and let those files to the linux distributions comes includes!

**Comment by RealRancor** [comment]
Sorry, but what are you talking?

**Comment by mckaygerhard** [comment]
u take me to the FireFirewall but theres no way to get the app without paid.. the app are promoted by owncloud.com not owncloud.org, or there's a way to use that app without a privative license?

**Comment by LukasReschke** [comment]
> u take me to the FireFirewall but theres no way to get the app without paid.. the app are promoted by owncloud.com not owncloud.org, or there's a way to use that app without a privative license?

Please read https://owncloud.org/faq/#communityandenterprise. Sum-up: No there is no way. Thus this issue is tagged as enhancement.

**Comment by mckaygerhard** [comment]
i cited: 

> I don't think it is wise to give major decisions about a free software project to a large proprietary competitor, which might naturally prefer that the project develop less rather than more.

the true of the freedown its that the company relies in the comnunity request.. but of course i now understand why so good apps in app store are now abandoned by developers..

well the history its making by the guy that have the money.. untyl people gets in anger

**Comment by mckaygerhard** [comment]
about tagget as enhancement.. i track the cahnges of @musaa32 and i thnk its a pitty and stuppid change!

i track the changes to the 7 series and seems works but i have a problem, in admin panel the changes are saved automatically but in 7.X series of oc are not?

who can i made a form saved manually by click a button ! its the only that i need now to complete this feature in a fork like @musaa32 does!

**Comment by RealRancor** [comment]
@mckaygerhard What prevents you from implementing this feature instead of relaying that some one else is doing the work for you :see_no_evil:

**Comment by mckaygerhard** [comment]
i made the request due i dont know (event reading the api) where i must edit and start.. but the user musaa32 does the trick easyle... that makes me formulate a question: why this feature cannot be done so quickly in oc7 or oc8? why feature request?

i backported the trick made by musaa32 and seems works (inverting the trick does a blacklist implementation) by i have the problem that settings that i saved in the table does not show in the interface when i re-visit the admin panel again..

by example, i enter in the panel, set to do not alloweb stupid M$ files by addiding "application/msword" and then enabling the checkbox "allow filters file" etc etc.. 
when i move the mous outside the focus the settings are saved.. and i confirm are in the PREFIX_appconfig table correctly..
but if i return to the admin panel after, the section of the filter are emtpy... if i put any other settings will override the previously saved!

**Comment by carlospea** [comment]
+1

**Comment by musaa32** [comment]
@mckaygerhard finaly, I made an app:  https://apps.owncloud.com/content/show.php/files_filter?content=174667

**Comment by DeepDiver1975** [comment]
I guess we can close this now - there are solutions available.

**Comment by RealRancor** [comment]
@DeepDiver1975 I think those two could be also closed: https://github.com/owncloud/core/issues/9542, https://github.com/owncloud/apps/issues/2078

**Comment by DeepDiver1975** [comment]
THX @RealRancor

**Comment by mckaygerhard** [comment]
hello @musaa32 i used oc 7 brand due webserver used faster php 5.3 and recent oc does perform more slower in my excelente powered old hardware..

if work in that env i'll tryi and help to u mantanin.. as i doit with the most famoust app for oc, the roundcube plugin  .. as all knwoed today its the most famoust app 

so this issue could'n be closed due its not provided in oc still

**Comment by RealRancor** [comment]
Same here: Stop spreading your non-sense all around...
