### ISSUE TITLE
Themed logo-wide.svg not used

### ISSUE THREAD

**Issue by skyynet** [owncloud/core#19794]
When I put an own logo-wide.svg into `/themes/<name>/core/img/` it is not used while other images are.
When I replace `/core/img/logo-wide.svg` it is of course used.

The logo is used when I share a link and the recceiver opens the link.

Please check code if theming is implemented for that image.

Checked with OC8.0.2stable

**Comment by karlitschek** [comment]
@jancborchardt any idea?

**Comment by jancborchardt** [comment]
@skyynet is it a valid svg file? Does the same issue happen with other images?

cc @schiesbn cause this is more of a technical theming issue.

**Comment by skyynet** [comment]
@jancborchardt It's a valid svg file which is shown correctly when placed in the /core/img/ folder. But that's not the correct way of theming.

**Comment by jancborchardt** [comment]
@skyynet any log here, or browser errors? @schiesbn @MorrisJobke your technical help is needed here

**Comment by skyynet** [comment]
@jancborchardt What browser errors? The image is delivered but it's the default one and not the themed. For the browser everything is fine a long as it gets any image.

**Comment by MorrisJobke** [comment]
There is no logo-wide in stable8.1+. It only is there in 8.0.x.

@skyynet Does this also happen to other images or only to logo-wide?

**Comment by skyynet** [comment]
I upgraded to 8.1.3, had to solve the missing ca-bundle.crt bug while upgrading from 8.0.4 and now it looks good. The new approach seems to be to only show the unthemed cloud icon and the name of ones cloud solution righthand from that.

As we don't need to fix irrelevant bugs for old versions I close this bug report.

Thanks for checking and commenting!
