### ISSUE TITLE
Exception: Please upload the ca-bundle.crt file into the 'config' directory.

### ISSUE THREAD

**Issue by githubgoucho** [owncloud/core#19805]
I got this upgrading from 7 to 8.1.3
Where to get: "ca-bundle.cr" and where to put?

**Comment by PVince81** [comment]
You need to upgrade from 7 to 8.0.x, then to 8.1.3.

CC @LukasReschke

**Comment by LukasReschke** [comment]
You can get the file from https://raw.githubusercontent.com/owncloud/core/stable8.1/config/ca-bundle.crt
