### ISSUE TITLE
Can not open trashbin from within a folder

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#19804]
1. Freshly open the files view
2. Go into a folder
3. Click on "trashbin" link

### Expected
Trashbin opens

### Actual
Console:
```
TypeError: this._detailsView is null
```

A second click loads it correctly.

Most likely related to https://github.com/owncloud/core/pull/19647

@PVince81

**Comment by SergioBertolinSG** [comment]
I'm not able to reproduce this. Which trashbin link ?
Accessing the removed elements is possible and removing elements inside a folder works as well.

**Comment by nickvergessen** [comment]
It's about the `Deleted files` link in the bottom left corner of the left-sidebar

**Comment by SergioBertolinSG** [comment]
Works fine for me using Ubuntu 14.04, mysql, current master.

**Comment by PVince81** [comment]
Hmm strange, I can't reproduce it either on master (b876f8b2a7c40dc23de4849f6a9157ae8150988b) or 8.2RC2.
Can you try clearing your cache maybe ?

If it still happens, maybe there is a race condition somewhere or another app is causing trouble

**Comment by nickvergessen** [comment]
```json
./occ app:list --output=json_pretty
{
    "enabled": {
        "activity": "2.2.0",
        "enterprise_key": true,
        "files": "1.1.11",
        "files_sharing": "0.6.3",
        "files_texteditor": "2.0",
        "files_trashbin": "0.6.3",
        "files_versions": "1.0.6",
        "firewall": "2.3.0",
        "firstrunwizard": "1.1",
        "notifications": "0.2.0",
        "provisioning_api": "0.2",
        "templateeditor": "0.1"
    },
    "disabled": []
}
```

Error is reported for line `filelist.js:2617:4`
Also reproducable without going into a folder for me.

Using FF 41.0.1 and Chrome 45.0.2454.101

**Comment by nickvergessen** [comment]
Okay, seems to be caused by the activity app which is trying to register the sidebar View, although the sidebar is not there in the trashbin anymore

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/19814
