### ISSUE TITLE
Cumulative error notification

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#19817]
Currently the notification just shows an orange banner at the top of the screen.
That one is only able to show a single notification at once.

This is inconvenient for example when several uploads fail, it can only show the latest error.

I suggest we improve this `OC.Notification` component to make it able to display several notifications, one on each row. Each notification will still have its own optional expiration and its row might disappear from the list.

Note: this has nothing to do with the notification app! This is only for error messages and "undo" messages after deletion.

@jancborchardt @nickvergessen @karlitschek @MTRichards @cmonteroluque @DeepDiver1975

**Comment by nickvergessen** [comment]
:+1:

**Comment by jancborchardt** [comment]
Yep, good call.

**Comment by MTRichards** [comment]
So, did this make the cut for 9.0? That is set as the milestone, but don't know if it is actually being worked.

**Comment by PVince81** [comment]
This is a non-trivial change, might possibly take a day or so.

Also we need to agree on its design.
Should the notification always stay or disappear after a delay ?

One idea is having a single "x" to close ALL notifications, and that "x" only appears if there is a at least one error.
So if a user uploads "a.txt", "b.txt", "c.txt" ... "f.txt", and there are 2 failures, the user will see
- "a.txt uploaded successfully"
- "b.txt uploaded successfully"
- "c.txt uploaded successfully"
- "d.txt upload error, reason XYZ"
- "e.txt upload error, reason XYZ"
- "f.txt uploaded successfully".

The success messages would disappear after 7 seconds, but the error ones would stay and must be closed with a "x".

@jancborchardt what do you think ?

**Comment by PVince81** [comment]
![cumulative-notifications](https://cloud.githubusercontent.com/assets/277525/13174030/62a9878e-d701-11e5-99c7-f678a4718203.png)

Seems we'd also need a "dismiss all" button somewhere.

**Comment by PVince81** [comment]
@jancborchardt currently it only adds a close button if you pass `{type: 'error'}`, should we maybe always display the close button ? (temporary notifications still disappear after 7 seconds regardless of the button)

**Comment by nickvergessen** [comment]
We only use it for errors anyway, right?

**Comment by PVince81** [comment]
PR is here https://github.com/owncloud/core/pull/22516 please try it out

**Comment by PVince81** [comment]
> We only use it for errors anyway, right?

So far the types of notifications I saw:
- update notification (a new update is available), that one is permanent and cannot be dismissed
- errors: upload errors, validation errors (wrong expiration date or such)
- undo: delete a user, it will notify and ask if you want to undo (7 seconds timeout)

Anything else ?

**Comment by PVince81** [comment]
If this is not acceptable I suggest a popup alert dialog at the end of the transfer, that lists all failed files. Just like Dropbox and GDrive do.

**Comment by jancborchardt** [comment]
It seems fine. Since the box also has a limit of the 5 visible messages I would even say we do not need the X buttons at all since they vanish after 7 seconds anyway.

**Comment by nickvergessen** [comment]
> I would even say we do not need the X buttons at all since they vanish after 7 seconds anyway.

That is up to the API user, there is showTemporary (default 7secs) and show (doesn't vanish)

**Comment by PVince81** [comment]
Note that the upload errors are now permanent, not temporary.
For errors I think we should keep them. Someone might want to retry uploading the failed files.
If the errors disappear they have no chance to take note of the failed files.

**Comment by jancborchardt** [comment]
Ok, good call! :)
