### ISSUE TITLE
unable to query assigned user quota via provisioning api

### ISSUE THREAD

**Issue by michag86** [owncloud/core#19810]
When I request:
GET /ocss/v1.php/cloud/users/user
this results in somthing like that:

```
...
<quota>
    <free>13348716544</free>
    <used>106928627</used>
    <total>13455645171</total>
    <relative>0.79</relative>
</quota>
...
```

It is not possible to query if the user has assigned default, unlimited or xx GB quota.

Tested on ownCloud 8.1.1, but I think there are no changes in 8.1.3.

**Comment by PVince81** [comment]
@rullzer @tomneedham wasn't there a PR that unified the response of the provisioning API calls to make sure all the info is always returned ?

**Comment by rullzer** [comment]
@PVince81 no that PR (https://github.com/owncloud/core/pull/19666) just cleans up some stuff.

I think the problem is that quota actually returns something different than we expect.
