### ISSUE TITLE
Cannot change share info after switching sections

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#19812]
### Steps

1. Open the files app
1. Create two folders "test1" and "test2"
1. Share both with link
1. Refresh the page
1. Open the sidebar for "test1"
1. Switch to "Shared with link" section
1. Open the sidebar for "test1"
1. Click "Share with link" or any other checkboxes under it
1. Refresh the page
1. Try unsharing again

### Expected result
After switching the section, the share tab should still be usable.

### Actual result
The checkboxes do react internally and send network requests, but the UI doesn't refresh accordingly.
This is because there are several "#app-sidebar" appended into the DOM, and the one appearing on the top isn't the one where the click event happens... some weird kind of conflict.

There is a simple workaround: refresh the page.

### Versions

ownCloud 8.2RC2

CC @davitol

**Comment by PVince81** [comment]
@cmonteroluque @karlitschek @DeepDiver1975 please evaluate the severity and milestone I chose

**Comment by cmonteroluque** [comment]
@PVince81 they look good to me

**Comment by PVince81** [comment]
Ah yes, of course!

When clicking on the checkbox, it's actually a label. Labels need to point to specific checkboxes using the "id". And the "id" isn't unique... So making the checkbox ids unique might fix this.

**Comment by PVince81** [comment]
Fix is here for id uniqueness: https://github.com/owncloud/core/pull/19822

**Comment by MorrisJobke** [comment]
Backport to stable8.2: #19835
