### ISSUE TITLE
"failedstorage" entry in oc_storages

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#19829]
### Steps
1. Setup a Dropbox external storage
2. Check oc_storages

There will be an entry with the id "failedstorage".
This is probably due to the transitional state of the Dropbox storage where it wasn't authorized yet.

I remember that there is code that creates a virtual "failure" storage that only throws exceptions.
Unfortunately that one somehow found its way into the oc_storages table.

@Xenopathic please have a look

**Comment by PVince81** [comment]
Observed on 8.2RC2

**Comment by Xenopathic** [comment]
When a FailedStorage has `->getStorageCache()` called on it, these sorts of entries will appear. There is a reason why we can't throw StorageNotAvailableException in that method, but I forget why now.

**Comment by PVince81** [comment]
@Hemant-Mann have you seen such bogus entries when configuring Dropbox recently ? If not, please close.

**Comment by Hemant-Mann** [comment]
No I haven't seen these kind of entries in **oc_storages** while configuring Dropbox

**Comment by PVince81** [comment]
I think this is an old bug and is solved already, closing
