### ISSUE TITLE
[IE9] Ridiculous app icons in apps page

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#19826]
![ridiculous-ie9](https://cloud.githubusercontent.com/assets/277525/10539346/39132b88-73ff-11e5-9b40-61315dcd8de0.png)

Probably yet another "background-size" case.

Observed on master (7224e99ccd47a0c9320ef9fd7a297b67cbbfd67c) and OC 8.2 RC 2

CC @davitol @jancborchardt

**Comment by PVince81** [comment]
I haven't checked IE8 but it's likely that it happens there as well.

**Comment by PVince81** [comment]
Looks like IE9 should support background-size, and the images are the SVGs.
Maybe IE9 doesn't upscale SVGs ?!

**Comment by PVince81** [comment]
Okay, this post http://stackoverflow.com/a/27971005 says that IE doesn't upscale SVGs when the "img" tag has "width" and "height" attributes. I only see these appearing in IE but not in Firefox, now to find where they get added...

**Comment by PVince81** [comment]
Ok, that's not enough.
According to http://stackoverflow.com/a/27971837 the SVG files need to contain a `viewBox` attribute.
If I add one manually in our apps' icons it works.
However we cannot expect every app developer out there to think about adding this to their SVG files if it's missing.
But also there doesn't seem to be any PNG fallback for this.

So the only "solution" for now would be to hide these icons in IE9 (and IE8 which doesn't support SVGs anyway)

**Comment by PVince81** [comment]
Argh, it's even worse, also happens on IE10, IE11: http://stackoverflow.com/q/27970520

So, hide the app icons in every IE version ?!

The other alternative is to provide a build script for app developers to fix their SVG app icons before publishing the app, but that seems to be outside the scope of a simple bugfix.

**Comment by PVince81** [comment]
@davitol do you see this issue in IE10/IE11, see screenshot https://github.com/owncloud/core/issues/19826#issue-111802353 ?

**Comment by PVince81** [comment]
I tried IE11 and the same problem exists for the icons.

As a quickfix, I suggest not showing any app icons in the apps page for IE...

**Comment by jancborchardt** [comment]
Yeah, I would agree that simply not showing the app icons on that apps page in IE is a good quick fix – much better than it looking broken.

And indeed we can not expect folks to add the »viewBox« attribute, as it also probably gets stripped in the minification process. Hopefully it works in IE12.

**Comment by PVince81** [comment]
Thanks, makes sense

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/19923

**Comment by MorrisJobke** [comment]
> Hopefully it works in IE12.

I'm currently downloading all IEs (including Edge)...I will report back.

**Comment by davitol** [comment]
Using ie9 app icon preview in apps page is disable
Using ie11 the icons looks like this
</br>
</br>
![screen shot 2015-10-21 at 13 02 03](https://cloud.githubusercontent.com/assets/10596560/10634725/0d12a916-77f4-11e5-932b-8170ef405734.png)

Using edge as browser they look right
</br>
</br>
![screen shot 2015-10-21 at 13 01 28](https://cloud.githubusercontent.com/assets/10596560/10634734/15ef1998-77f4-11e5-9565-8f7911e08e25.png)

**Comment by PVince81** [comment]
Ok, so the edge browser is the only one that looks right

**Comment by davitol** [comment]
and in IE9, your intention was to not let them appear, isn`t it?

**Comment by PVince81** [comment]
The pull request should remove the app icon for **every** IE browser.

**Comment by davitol** [comment]
OK,then i'll change my comment https://github.com/owncloud/core/pull/19923#issuecomment-149853531

**Comment by MorrisJobke** [comment]
> The pull request should remove the app icon for every IE browser.

no. This i.e. class only works for IE up to 10 ;) in IE11 this doesn't work anymore ;)
