### ISSUE TITLE
Sidebar should not open, when renaming a file on mobile

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#19839]
### Steps
1. Open file list with max. 700 pixels, so the responsive design triggers
![bildschirmfoto vom 2015-10-16 16 53 28](https://cloud.githubusercontent.com/assets/213943/10544953/7d09e026-7426-11e5-83c8-30ad811c31f6.png)
2. Rename the file

### Expected
You should see the file list with your renamed file

### Actual
You see the sidebar  instead of the file list

---

I would not expect this behaviour. Suddenly a view pops up out of no where, although I didn't trigger it (intentionally).
The behaviour would be okay, if you can rename a file from the sidebar I guess. But atm it feels wrong.

@PVince81 what do you think?

**Comment by PVince81** [comment]
Ah... looks like hitting enter on the rename field automatically opens the sidebar. That shouldn't happen.
I guess it probably happens because the row gets auto-highlighted after rename, which triggers the sidebar *sigh*

**Comment by PVince81** [comment]
I should probably decouple the "set highlight" from "open sidebar" and make "open sidebar" something very explicit in the code.

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/19937
