### ISSUE TITLE
Drag and drop of a folder with more than 100 files uploads only 100 files.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#19834]
### Steps to reproduce
1. Using chrome, drag and drop a folder with more than 100 files.
### Expected behaviour

All files are uploaded.
### Actual behaviour

Only 100 files are inside the folder after finishing the download.
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Using enterprise theme.
{"installed":true,"maintenance":false,"version":"8.2.0.9","versionstring":"8.2 RC1","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Server logs**

```
{"reqId":"BN4ZzV0yqiH7Bq8EI4mi","remoteAddr":"82.159.139.58","app":"PHP","message":"Array to string conversion at \/opt\/owncloud\/lib\/private\/template\/functions.php#36","level":3,"time":"2015-10-16T12:11:16+00:00"}
{"reqId":"Ec23QymbiGqH34BcGfHt","remoteAddr":"82.159.139.58","app":"PHP","message":"Array to string conversion at \/opt\/owncloud\/lib\/private\/template\/functions.php#36","level":3,"time":"2015-10-16T12:17:57+00:00"}
```

**Comment by PVince81** [comment]
I don't see any limitation in the OC code, so it might be a limitation in Chrome's folder upload API.

**Comment by PVince81** [comment]
@SergioBertolinSG are you able to upload more than 100 files through drag and drop, but without using a folder ?

Related: https://productforums.google.com/forum/#!msg/drive/5TVELVWcLFs/3LvwVJI6QQgJ
and https://forum.owncloud.org/viewtopic.php?f=29&t=23662

**Comment by SergioBertolinSG** [comment]
Yes, without a folder, all files are uploaded.

**Comment by PVince81** [comment]
Browser limitation, nothing we can do.

It was mentioned to me by someone else last week.

**Comment by vuRoland** [comment]
we've experienced the same 100 files limitation when uploading a folder + files and found that it was a bug in jquery.fileupload.js that is used in owncloud, currently. If you adjust the js file according to the info in this github commit, it works again as expected (>100 files in a folder with drag and drop)

Fix for Issue and bug #3181 - drag drop 100 file limit: 
https://github.com/blueimp/jQuery-File-Upload/commit/911dcf1f5bbfda877573fd4fb2b67dd47f225752

**Comment by PVince81** [comment]
Ah! So it's not a limitation in Chromium.

Reopening to look into upgrading that library.

**Comment by PVince81** [comment]
maybe an opportunity to introduce bower + makefile in the files app

**Comment by tekGuy64** [comment]
Any word on resolving this bug? I have a client who has reported this problem as well.

**Comment by aguazul** [comment]
I'm surprised this is still an issue.  Github cannot upload a folder that has more than 100 files?  Strange...

This is really holding me back today...

**Comment by fshirzadi** [comment]
Still getting this error.

**Comment by qiksoft** [comment]
Yes, this is very discouraging. 100 files in a folder limitation is very small...

**Comment by tomycbf** [comment]
I have gotten the same message from github to upload code to my repository. Is there any method to resolve it? 100+ files are common in a real project. I don't know why github have such kind of limitation.

**Comment by PVince81** [comment]
Maybe github uses the same library like OC which has this limit.

Or the browser has a limit and the library needs special code to bypass it.

**Comment by PVince81** [comment]
Can someone try upgrading the jquery fileupload lib and see if it solves the issue ?
The code is here: https://github.com/owncloud/core/blob/master/apps/files/js/jquery.fileupload.js

This is likely to introduce a lot of new issues so will need full retesting of upload process, conflict dialog, etc.

**Comment by vfreex** [comment]
I just verified https://github.com/owncloud/core/issues/27875.
With the new version of jquery.fileupload.js, I can drag and drop a folder with more than 100 files now.

**Comment by SergioBertolinSG** [comment]
Working fine in 10.0.2.

**Comment by jredfox** [comment]
This is an issue again I never had this issue before with chrome come back 1 month later try and updload modified source then it says too many files needs < 100

**Comment by UWGuLab** [comment]
experiencing same issue with Chrome

**Comment by jredfox** [comment]
I also tried microsoft edge and chrome it doesn't work it use to work with chrome

**Comment by SergioBertolinSG** [comment]
Are you using a server with version 10.0.2 ? 

I am not seeing problems using chrome with current master.

**Comment by jredfox** [comment]
I am not using any server just github

**Comment by ndrewxie** [comment]
It's annoying, but you can use git to manually do it 😄

**Comment by jredfox** [comment]
I tried the desktop version of github but, it wouldn't select an already registered repository

**Comment by nexjsystems** [comment]
Getting this error message today... I am trying to upload wordpress plugins to my repo but it STOPS at 100 files... This is an issue!! Is there a current workaround?

**Comment by tedstrauss** [comment]
Bump!

**Comment by PVince81** [comment]
are you all using OC 10.0.3 ? If not please upgrade. We already upgraded the jquery.fileupload library which is supposed to be able to bypass this and it was confirmed working.

**Comment by tedstrauss** [comment]
Good to know!!
I have been wary upgrading from v9 to v10, but this will make it a priority.

**Comment by jredfox** [comment]
is this github issues itself please fix github it's annoying it shows 287 then refuses to upload more then 100

**Comment by filo-paa** [comment]
both in firefox 59.0.2 (32 bit) and chrome Version 65.0.3325.181 (official build) (32 bit) I am still limited to 100 files through the web user interface. I feel it is a design choice, rather than a bug.

**Comment by icuurd12b42** [comment]
Same issue over here. I just zipped my folder and uploaded the zip. will abandon git folders for all my projects in the futures. dont see the benefits of them in my case given I dont use the command prompt system, not will I ever... it's 2018, why are we still doing shit like it's the 70's

**Comment by naraphim** [comment]
Yoza! Thats a really poor design choice. Try designing a program that people want to use.

**Comment by PVince81** [comment]
There is no hard limit by design in ownCloud. The limitation is on the browser side. If the browser does not want to give the JS code more than 100 entries despite the fact that the user selected more, there is nothing that a JS dev can do about it.

**Comment by Huzo** [comment]
I have tried every browser I have, and I still can't get past this problem. Pretty frustrating.

**Comment by karmatechs** [comment]
Also got the same error uploading files in a folder on chrome

**Comment by stormyqq** [comment]
Yowza, that’s a lot of files. Try again with fewer than 100 files.

**Comment by vamshikrishnaChintha** [comment]
How Can i Upload Folder with More than 1000 Files at a Time

**Comment by vamshikrishnaChintha** [comment]
How Can i Upload Total Website at a time in Repository

**Comment by PVince81** [comment]
upgrade to OC 10.0.10 and try again

**Comment by BlitzNY** [comment]
this problem still happening today !!!!!!!

**Comment by PVince81** [comment]
@BlitzNY any details about your setup ?

**Comment by JimmyRooster** [comment]
How could I upload my project, it only has 101 files. Tried it in Chrome and Edge, it just says 

> Yowza, that’s a lot of files. Try again with fewer than 100 files.

**Comment by mariomuja** [comment]
i have the same issue - cannot drag a folder with more than 100 files to the upload area of github

**Comment by SeokLeeUS** [comment]
this still persisting issue, i don't know how this is not fixed.

**Comment by PVince81** [comment]
see https://github.com/owncloud/core/issues/19834#issuecomment-408359907, works for me.

if it doesn't for you, please state your OC version, browser, etc

**Comment by SergioBertolinSG** [comment]
@PVince81 I think they are talking about github instead of owncloud https://stackoverflow.com/questions/39716847/git-upload-project-full-site

I recommend to lock this conversation.

**Comment by PVince81** [comment]
@SergioBertolinSG right.

I'll lock this conversation now.

If anyone is having this issue with **ownCloud 10.1** or later version, please open a new ticket and use the [issue template](https://github.com/owncloud/core/blob/master/.github/issue_template.md)
