### ISSUE TITLE
Resizing the window downloads the woff fonts over and over

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19841]
1. Open a folder with lots of files in it
1. Hit F12
1. Go to the network tab
1. Hit ctrl+F5

The last 2 items in the list should be the fonts

1. Resize the window a few times until you start seeing the font being downloaded

Since resizing is a desktop activity, it doesn't matter that much in terms of bandwidth, but there is still a bug which makes some core script download the fonts over and over.

![font_overload](https://cloud.githubusercontent.com/assets/323220/10545347/980ff494-7428-11e5-83ea-5cc1beadaab2.png)

----
@jancborchardt @PVince81 @Henni @MorrisJobke

**Comment by Henni** [comment]
I can't reproduce this in Firefox or Chrome.
@oparoz can you describe the way to reproduce this in more detail?

**Comment by MorrisJobke** [comment]
I also can't reproduce this with Chrome and Firefox.

**Comment by oparoz** [comment]
I've updated the OP. You need to be in a folder with a lot of files in it. It's probably triggered when there are more than what the view can hold.

**Comment by PVince81** [comment]
@oparoz is this still happening in 9.0beta1 ? Not sure which version you had back then

**Comment by oparoz** [comment]
Not happening any more. Apparently we don't use woff fonts any more as no font gets downloaded.
