### ISSUE TITLE
Web view not properly refreshed after upload

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19845]
### Steps to reproduce

1. Open a folder in Chrome
1. Open the same folder in Firefox
1. Upload a folder in Chrome
1. Upload a file in Firefox

### Expected result

I should see both the new folder and the new file in Firefox

### Actual result

I only see the file I just uploaded

----
@MorrisJobke @PVince81

**Comment by MorrisJobke** [comment]
Duplicate of https://github.com/owncloud/core/issues/983
