### ISSUE TITLE
Send sharing link to more than one recipient [OC 8.1.3]

### ISSUE THREAD

**Issue by tflidd** [owncloud/core#19848]
### Steps:
1. Activate `Allow users to send mail notification for shared files`
2. Share file/folder via link
3. Try to send the shared link to several users: `mail1@example.org mail2@example.org`

### Expected behavior
Mails are sent like in Owncloud 8.0.6 you can send the shared link to more than one user with this string:
`mail1@example.org mail2@example.org`

### Actual behavior
Error shows up in the logfiles:
````
{"reqId":"1JSL4UiItKyRQo+1vc03","remoteAddr":"ip","app":"sharing","message":"Can't send mail with public link to mail1@example.org, mail2@example.org: Address in mailbox given [mail1@example.org, mail1@example.org] does not comply with RFC 2822, 3.6.2.","level":3,"time":"2015-10-16T21:10:46+00:00","method":"POST","url":"\/oc8\/owncloud\/index.php\/core\/ajax\/share.php"}

````
It seems like it should support more than one users because the interface shows this error
```
Error while sharing
Couldn't send mail to following users: mail1@example.org mail2@example.org
```

### Server configuration
**Apps**
Enabled:
 - activity: 2.0.2
 - bookmarks: 0.4
 - calendar: 0.7.3
 - contacts: 0.4.0.0
 - files: 1.1.10
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - galleryplus: 14.1.0
 - mail: 0.2.0
 - news: 6.0.5
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.6

Both mail addresses exist, you can send shared link to each address individually.

Tried this:
`mail1@example.org mail2@example.org`
`mail1@example.org, mail2@example.org`
`mail1@example.org; mail2@example.org`
`<mail1@example.org>, <mail2@example.org>`

**Owncloud**: 8.1.3 (on Ubuntu 14.04/apache/mysql)

This problem was originally reported by one of the users on the forum: https://forum.owncloud.org/viewtopic.php?f=19&t=30954

**Comment by RealRancor** [comment]
Looks to me like a dup of this request from 2013: https://github.com/owncloud/core/issues/1632

**Comment by RealRancor** [comment]
Looks to me like a dup of this request from 2013: https://github.com/owncloud/core/issues/1632

**Comment by tflidd** [comment]
It was working on OC 8.0.x with spaces as separator. So it's not a new feature (with comma as separator it would be a new "feature").
Or was it a bug and not a feature?

**Comment by RealRancor** [comment]
Ah, missed that. Then i think https://github.com/owncloud/core/issues/1632 could be closed and this here marked as a bug.

**Comment by PVince81** [comment]
@nickvergessen @LukasReschke has this been changed purposefully or is it a bug ?

**Comment by nickvergessen** [comment]
Something changed: we validate email addresses now :speak_no_evil: 
from my point of view not a regression thou. Removing a hidden feature. We can try to get it back though, but not blocking 8.2

**Comment by PVince81** [comment]
@cmonteroluque I'd suggest 8.2.1 then, not sure how much work it is

**Comment by nickvergessen** [comment]
I'd say 9.0 and see afterwards :-O

**Comment by cmonteroluque** [comment]
I'm afraid there are a lot of 8.2.1 issues already. Moving to 9.0

**Comment by MorrisJobke** [comment]
Reported as blue ticket: https://github.com/owncloud/core/issues/20504

**Comment by gig13** [comment]
@bboule 
This is missing/removed functionality from GCX perspective, can it be added to a patch release?

**Comment by gig13** [comment]
@MorrisJobke 
Do I need to add backport request tag? Any ETA when 8.1.5 will be available?

**Comment by bboule** [comment]
Back-port please as this is a regression from the users perspective @cmonteroluque is this possible?

**Comment by MorrisJobke** [comment]
> Do I need to add backport request tag? Any ETA when 8.1.5 will be available?

8.1.5 is planned for 2015-12-22 but this here is not yet finished. There is no fix available yet.

**Comment by MorrisJobke** [comment]
> Back-port please as this is a regression from the users perspective @cmonteroluque is this possible?

First of all we need a fix. Then we can discuss the backport.

**Comment by nickvergessen** [comment]
Reopening for backports

**Comment by MorrisJobke** [comment]
> Reopening for backports

Simply backport - I will not miss this - there is a backport-request label on this and I monitor those issues ;)

**Comment by MorrisJobke** [comment]
@gig13 @bboule This will be in 8.1.5 and 8.2.2 (ETA 2015-12-22) and 9.0.0 (ETA march 2016)
