### ISSUE TITLE
Segfault in ownCloud client 2.0.1 when ownCloud folder is removed/renamed from the server

### ISSUE THREAD

**Issue by mcastillof** [owncloud/core#19847]
Segfault in ownCloud client 2.0.1 when ownCloud folder is removed/renamed from the server

### Steps to reproduce
1. Install client and log in as user. Close the client (quit ownCloud).
2. In the server, rename or remove /var/www/owncloud.
3. Open the client again.

### Expected behaviour
The client should start, and warn the user that something happened to the server, as it can reach it, but can't find the ownCloud service in the url https://example.com/owncloud/ (404 error).

### Actual behaviour
The client app start, as you can see the icon in the notification area from your taskbar, but after half a second the app crashes with a "Segmentation fault".

### Server configuration
Operating system: Debian Jessie
Web server: lighttpd/1.4.35 (ssl)
Database: mysql  Ver 15.1 Distrib 10.0.20-MariaDB, for debian-linux-gnu (i686) using readline 5.2
PHP version: PHP 5.6.13-0+deb8u1 (cli) (built: Sep  8 2015 12:13:31)
ownCloud version: ownCloud 8.1.3 (stable) 
Storage backend: Local

### Client configuration
Client version: ownCloud version 2.0.1
Operating system: Debian Jessie
OS language: English
Installation path of client: /usr/bin/owncloud (I installed it from your Opensuse's repo)

### Logs

1. Output of `owncloud --logfile log.txt` when the owncloud folder is in the server: https://gist.github.com/anonymous/4d68dc6967d5a12167e7

2. Output of `owncloud --logfile log.txt` when the owncloud folder is removed from the server: https://gist.github.com/mcastillof/ac06ef9714ed241472c4

**Comment by RealRancor** [comment]
@mcastillof Sorry, should have pointed you directly to the correct bugtracker. The one for the client is located here: https://github.com/owncloud/client/issues

As github doesn't allow to move issues its the best to close here and re-open at the issue tracker of the client.
