### ISSUE TITLE
Why is Javascript not working?

### ISSUE THREAD

**Issue by ptsx** [owncloud/core#19856]
Error
`Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src http://local.bulutin.com 'unsafe-eval'").`

Code
/themes/aaaa/core/templates/login.php
`<?php
	if(isset($_POST) && isset($_POST['username']) && isset($_POST['password'])){
	    ?>
	        <script>alert(3);</script> 
	    <?php
	}?>`

**Comment by RealRancor** [comment]
Hi,

i think this perfectly fits as a question for https://mailman.owncloud.org/mailman/listinfo/devel as this doesn't look like an bug to me but a question how something is included in a custom theme.

**Comment by DeepDiver1975** [comment]
For security reasons we do not allow inline javascript

**Comment by ptsx** [comment]
@DeepDiver1975 Is there no solution?

**Comment by karlitschek** [comment]
please ask on the mailinglist as suggested
