### ISSUE TITLE
Wrong HTTP_X_FORWARDED example in config.sample.php?

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#19853]
Hi,

both 8.1.x and 8.2 contains the following line:

``'forwarded_for_headers' => array('HTTP_X_FORWARDED', 'HTTP_FORWARDED_FOR'),``

at:

https://github.com/owncloud/core/blob/v8.1.3/config/config.sample.php#L1022
https://github.com/owncloud/core/blob/v8.2RC3/config/config.sample.php#L1107

A user reported at the forums (https://forum.owncloud.org/viewtopic.php?f=31&t=30951) that he had to use:

``'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR', 'HTTP_FORWARDED_FOR'),``

instead to get the correct IP logged for fail2ban. I don't know whats the difference is or if the missing ``_FOR`` is just a typo?

cc @LukasReschke

**Comment by karlitschek** [comment]
@LukasReschke What do you think?

**Comment by LukasReschke** [comment]
That actually depends on the configuration of the reverse proxy. There are some cases where `HTTP_X_FORWARDED` is valid. We just provide examples that one needs to modify to properly follow.

That said, if your `forwarded_for_headers` contain more than one entry and you just use one reverse proxy it is likely misconfigured. You only need to specify the one you use.
