### ISSUE TITLE
[Uploader] Chunked cache files have future date

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/core#19852]
Hello,

currently I am uploading a large file with owncloud sync client 2.0.1 on linux to OC server 8.1.1.
As the connection vanishes sometimes, I wanted to check the size of the chunked files in: /data/USER/cache.
To my surprise these files have a date that lies in the future (tomorrow), shown by ls:
rw-r--r--  1 www-data www-data 10485760 Okt 19  2015 VID_20151017_143212.mp4-chunking-3083485732-9
whereas the current uploading file has the correct date:
-rw-r--r--  1 www-data www-data  1753088 Okt 18 13:11 VID_20151017_143212.mp4-chunking-3083485732-16.3OG0NSflLUejF5eY.part

This seems not to be a real problem as the resulting file has the same date as the original one on my laptop.
But I am curious why the date is set to the future? Now it is not easy to see, when the last partial upload was...

Thank you
Tobi

**Comment by RealRancor** [comment]
Hi,

this is the wanted behavior as described here: https://github.com/owncloud/core/issues/15407#issuecomment-135295079

**Comment by tobiasKaminsky** [comment]
Ok thank you for your fast reply.
