### ISSUE TITLE
Loading feedback for user menu entries

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#19857]
Just like the spinner which appears when you click an app in the app menu, there should be a spinner for the entry in the user menu you click. Simply a `class="icon-loading-small"`, replacing the icon of the respective entry.

cc @owncloud/designers @PVince81 @MorrisJobke

**Comment by MorrisJobke** [comment]
@jancborchardt What does "user menu" means? The menu in the top left?

**Comment by jancborchardt** [comment]
Yeah, the menu which appears when you click profile image / username in the top right (I assume you meant to say »top right«).

**Comment by MorrisJobke** [comment]
> Yeah, the menu which appears when you click profile image / username in the top right (I assume you meant to say »top right«).

m( ...yes. I meant top right.

**Comment by jancborchardt** [comment]
@owncloud/javascript can anyone take care of the JS side here?
