### ISSUE TITLE
»Enable User External Storage« enabled, but all storages disabled by default

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#19858]
After enabling the app, the settings look like this by default (»Enable« ticked, but none of the storage systems):
![capture du 2015-10-19 15-58-12](https://cloud.githubusercontent.com/assets/925062/10572278/580ca022-76a3-11e5-8de0-476467eda78b.png)

This is strange – I would expect either the main checkbox to not be ticked, or when it’s ticked that all the storages are enabled by default. What should be the default here @karlitschek @LukasReschke @DeepDiver1975?

Also, the label »Enable User External Storage« should rather be »Enable users to mount external storages«.

**Comment by DeepDiver1975** [comment]
> Also, the label »Enable User External Storage« should rather be »Enable users to mount external storages«.

PR welcome :speak_no_evil:

**Comment by DeepDiver1975** [comment]
> This is strange – I would expect either the main checkbox to not be ticked, or when it’s ticked that all the storages are enabled by default.

I'd vote for disable the main checkbox rather the opening up the system by default to allow everything

**Comment by jancborchardt** [comment]
I’d be fine with disabling it as well.

**Comment by jancborchardt** [comment]
PR for wording at https://github.com/owncloud/core/pull/19863

**Comment by MTRichards** [comment]
>Also, the label »Enable User External Storage« should rather be »Enable users to mount external storages«.

Totally dumb update, but the last "storages" should say storage, >> Enable users to mount external storage.<<

**Comment by jancborchardt** [comment]
@MTRichards of course – PR at https://github.com/owncloud/core/pull/20253

**Comment by jancborchardt** [comment]
So, PR for the original actual issue then? ;) @DeepDiver1975 @PVince81
