### ISSUE TITLE
[pre-alpha 9] Client can't connect: OCA\\DAV\\Connector\\Sabre\\ServerFactory

### ISSUE THREAD

**Issue by tflidd** [owncloud/core#19865]
I'm just testing the new testpilot & nightly build of OC. The client can't connect:
````
PHP Fatal error:  Class 'OCA\\DAV\\Connector\\Sabre\\ServerFactory' not found in /var/www/owncloud/apps/files/appinfo/remote.php on line 35
````
Nightly build is on Debian 8.0 installed from SuSE-repos:
ownCloud 9.0 pre alpha (daily) Build:2015-10-19T03:42:58+00:00 8d25528c49bfaa72873cad3e06188e3484ef552b

If this is due to work in progress, please close this.

**Comment by PVince81** [comment]
@DeepDiver1975

**Comment by nickvergessen** [comment]
https://github.com/owncloud/core/pull/19838
