### ISSUE TITLE
Files with | (vertical bar) or / (slash) are not synced without warning about that

### ISSUE THREAD

**Issue by paul-schulze** [owncloud/core#19866]
I work in a small office and we use ownCloud as our "Dropbox" solution. On HFS+ on a Mac you can create files which include a slash or a vertical bar in their name. Recently a colleague was puzzled about missing files. I investigated the problem and found out that the missing files are not even existing on the server itself. So I started inspecting the ownCloud client of the creator of the files and then I realized that the missing files have these characters in their names. But the ownCloud client did not warn that these files weren't synced. So of course my colleagues expected everything to be ok and in sync.

Maybe there are more characters which are involved with that bug. It is very important that a user sees the correct sync status of his/her files.

**Comment by LukasReschke** [comment]
Please reopen in the client tracker at https://github.com/owncloud/client/issues
