### ISSUE TITLE
root directory cleanup

### ISSUE THREAD

**Issue by karlitschek** [owncloud/core#19875]
The ownCloud root directory is getting more and more crowded with files and folder that makes sense for developers but not for normal admins or users. So we should clean this up a bit.

I suggest:
- Move ‘settings’ to  core
- Move ‘ressources’ to core
- Move ‘l10n’ to core
- Move ‘db_structure.xml’ to core
- Move ‘3rdparty’ to core

Not sure what to do with:
console.php and ‘lib’

**Comment by DeepDiver1975** [comment]
> Move ‘settings’ to core

into apps? as in user management and settings app - not with the intention to allow others to implements their own usermanagement but simply because of code structuring. We could get rid of some hardcoded special code paths

**Comment by DeepDiver1975** [comment]
> Move ‘l10n’ to core

does that one really matter? We anyhow strip it from the release - right?

anyway - can be moved if needed

**Comment by DeepDiver1975** [comment]
> Move ‘3rdparty’ to core

if we touch this I have two additional requirements:
- kill the submodule
- kill the configurable 3rdparty location

**Comment by DeepDiver1975** [comment]
> Not sure what to do with:
> console.php and ‘lib’

Depends on the docs and the way people use it.
Afaik in some case people are used to run this in root:

```sh
php console.php

**Comment by DeepDiver1975** [comment]
> Move ‘db_structure.xml’ to core

make core a true app :speak_no_evil:

**Comment by karlitschek** [comment]
- We could als use settings into apps. I just don't want to start a huge refactoring here. Just a simple move and fixing of some urls should be enough. into apps is also fine with me.
- i10n Not sure I understand. It is in the release. So we should have it at a better place. What do you man?
- Got the 3rdparty requirements. But I suggest to discuss this separately. Let's not make this small cleanup task super big :-) 
- console.php I'm just not sure if people still use it like that. What do you think? If people use it then it should stay in root. If not then move it away.

**Comment by DeepDiver1975** [comment]
> i10n Not sure I understand. It is in the release. So we should have it at a better place. What do you man?

l10n in root only holds transifex config and the sync script - we had this removed from the tarballs some releases back - but it came back .... anyway: we can move this to the build folder since it only holds dev related stuff

**Comment by DeepDiver1975** [comment]
> Just a simple move and fixing of some urls should be enough.

no need to fix urls - no php script is accessed/executed directly by now - which is great

**Comment by DeepDiver1975** [comment]
> Got the 3rdparty requirements. But I suggest to discuss this separately. Let's not make this small cleanup task super big :-)

At least killing the configurability of the 3rdparty folder location is an option because it removes test effort after change :wink:

**Comment by DeepDiver1975** [comment]
> console.php I'm just not sure if people still use it like that. What do you think?

I have seen people using php console.php instead of calling ./occ - especially in sudo invocations ....

**Comment by MorrisJobke** [comment]
* settings should be a separate app (it is already, but hardcoded in router for example)
* core should be a separate app (it is already, but hardcoded)

* core and settings have a lot an app already has, but it's really cluttered. Controllers are everywhere in the settings folder, but should maybe all reside in a single controller subfolder ;)

**Comment by nickvergessen** [comment]
:+1: for cleaning up.

**Comment by DeepDiver1975** [comment]
We should split up settings into:
- user mgmt
- app mgmt
- settings (personal and admin can live together I guess)

**Comment by karlitschek** [comment]
Sorry but now. We don't turn everything upside down now. The current structure might not be perfect but it works fine. This is only about cleaning up the root directory. Not refactoring the complete internals and turning everything into apps. Last time I checked we have a lot more pressing things to do.

**Comment by PVince81** [comment]
@DeepDiver1975 keep in 10.0 or backlog ?
