### ISSUE TITLE
Corrupted Files after multi-part upload

### ISSUE THREAD

**Issue by andi-at** [owncloud/core#19889]
Hello,

I have random issues with corrupted files on the server, which prevent the client to (re-)sync properly. I have already postet in client area here, but i think the issue is server-sided: https://github.com/owncloud/client/issues/3816#issuecomment-149314546

My setup:
Server: Debian 7, fresh owncloud installation v 8.1.3, Apache with SSL mod. Server side encryption activated. Cronjob activated
Client: Desktop Client 2.0.1 Mac / CMD Client 2.0.1 Debian

I sync two different folders with my two client, each having a lot of documents / files. The problem occured with both clients. At some stage the initial sync failed, with error message "connection closed", "operation aborted". Looking at the logfile didn't gave much infos expect of the problematic files. After deleting 3 of them the upload completed and the cloud was working with the first client.
The problem also showed up on the second command-line client, but there where much more corrupted files. 
Here is what happens:
- The desktop sync client shows that it tries to download the file, and stuck at lets say 300/700kb. After a few seconds it aborts and tells me "corrupted server returned empty filesize for non-empty file", "operation cancelled". Sync does not continue
-  Looking at the server the file is there, but with a wrong creation date (the upload date instead of 4 years like all other files in the directory show). Also the file has a wrong size, it is BIGGER! than the original.
- Trying to download the file over webinterface fails, the browser download starts but aborts after a few seconds with 0kb.
- No errors shows up in the apache logs

Pretty bad error because the cloud is useless to me. I think the (multi?)upload of the files got corrupted, but the server fails to detect the issue. At the next sync the client try to correct the problem, but the file is not longer accessible/writeable due to whatever...

My plan is to deactivate the encryption and resync, but i woud like to wait if you need some information from me to trace down the bug. Cause i have no idea how to reproduce it, it happened to random files for what i have seen.

thanks,
Andreas

**Comment by PVince81** [comment]
Note: encrypted files are about 30% bigger than unencrypted, when looking directly at the "data" folder.

**Comment by andi-at** [comment]
Hello,
Oh thats a good hint! Here are the sizes:
Original on client:84.480 Byte
Encrypted file in "data" folder: 121.168 Byte
OC Webinterface: 118kB

Really looks like something went wrong at the encryption?

**Comment by nickvergessen** [comment]
Just some math:
>Encrypted file in "data" folder: 121.168 Byte

divide by 1024 => 118,328125 kB, so the webUI is correct

> Original on client:84.480 Byte

As states encrypted files are larger, your file is (84.480 divided by 121.168) 69% so 31% bigger after the upload.

About the SQL error, please make sure your database has set transaction mode to READ_COMMITED 
https://dev.mysql.com/doc/refman/5.0/en/set-transaction.html

We do that on connect, but it seems like it fails for you:
https://github.com/owncloud/core/blob/58e96e53b039365751eb8c4a2d511fcfcf507891/lib/private/db/connection.php#L135-135

**Comment by tflidd** [comment]
Wouldn't it make more sense to show the real file size (without encryption overhead)? The user in general doesn't care about it and wants to see the same size like the files/folders have on his client (wasn't this the argument to use the Microsoft definition of a MB?). Then you have to adopt the quota size.

**Comment by nickvergessen** [comment]
Would be nice if we can split the discussions. The corruption problem is solved (because your server is misconfigured) and the "which size should be displayed" has been discussed multiple times already.
So I think we are done here with the triage

**Comment by PVince81** [comment]
The web UI already shows the unencrypted file size. If it doesn't then it's a different bug.
Maybe the corruption bug caused that database to contain the encrypted file size instead of unencrypted. The web UI simply shows whatever is in the database.

**Comment by andi-at** [comment]
nickvergessen i give it a try, deleting everything on server and resync everything. 

PVince81, i think so too, the wrong file size just indicates for me that the file is broken.

**Comment by andi-at** [comment]
hello,
that did not work, i have the same error messages again!

**Comment by andi-at** [comment]
Hello,
I have completely reinstalled the server, updated the client to 2.0.2 and resynced, the problem is gone so it can be closed. But you should release the 2.0.2, cause i would have dropped owncloud if the problem would still exists and im shure other would too..
