### ISSUE TITLE
pagination doesn't work on public link share page

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#19886]
Tested with v8.2.0 (git tag)

1. create a folder
2. upload 30 files (need to be more than 20 in my case)
3. share folder as link
4. open the link

Expected behavior:

file list should show all 30 files

Actual behavior:

file list shows only the first 20 files

cc @PVince81

**Comment by MorrisJobke** [comment]
Just tested and it works on stable8.1 and doesn't work on stable8.2

**Comment by MorrisJobke** [comment]
This looks more like a "view" problem. The file list call returns for me all 36 files, but only shows 18. cc @PVince81

**Comment by PVince81** [comment]
Maybe the scrollbar container has changed again and scroll detection is broken

**Comment by PVince81** [comment]
Regression => setting to 8.2.1 @DeepDiver1975 @cmonteroluque @karlitschek

**Comment by PVince81** [comment]
Let me bisect this

**Comment by PVince81** [comment]
And here is the winner. c1a5e9643589233e0e4e131f1b2808c40370cec9 from https://github.com/owncloud/core/pull/19611

@Henni please have a look
CC @oparoz

**Comment by PVince81** [comment]
It looks like you added a "content-wrapper". Is that the new scroll container ?
In case you need to change it, it is defined here: https://github.com/owncloud/core/blob/master/apps/files_sharing/js/public.js#L57

**Comment by Henni** [comment]
@PVince81 thanks, I just searched for this line!
