### ISSUE TITLE
SFTP external storage with encryption disabled in a server with encryption enabled returns internal server error while uploading files. 

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#19880]
### Steps to reproduce

1. Enable encryption app and default module.
2. Enable external storage.
3. Set up SFTP external folder. Disable encryption in this storage.
4. Upload files to the SFTP folder.

### Expected behaviour
All files are uploaded.

### Actual behaviour
Internal server error.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Using enterprise theme.
{"installed":true,"maintenance":false,"version":"8.2.0.12","versionstring":"8.2.0","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Encryption.
External storage.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes SFTP.

**Are you using encryption:** 
Yes.

**Server logs**
```
{"reqId":"uH0Quu9rkkqClQzEVHrI","remoteAddr":"82.159.139.58","app":"files","message":" Backends provided no user object for ","level":3,"time":"2015-10-20T07:06:45+00:00"}
{"reqId":"uH0Quu9rkkqClQzEVHrI","remoteAddr":"82.159.139.58","app":"no app in context","message":"Error while running background job: Backends provided no user object for ","level":3,"time":"2015-10-20T07:06:45+00:00"}
{"reqId":"wENR3JzwWI3TRGVcF5YU","remoteAddr":"82.159.139.58","app":"PHP","message":"Unsupported operand types at \/opt\/owncloud\/3rdparty\/phpseclib\/phpseclib\/phpseclib\/Net\/SFTP\/Stream.php#156","level":3,"time":"2015-10-20T07:06:48+00:00"}
{"reqId":"lqv\/7Lfakd+iVQy2llGU","remoteAddr":"82.159.139.58","app":"PHP","message":"Unsupported operand types at \/opt\/owncloud\/3rdparty\/phpseclib\/phpseclib\/phpseclib\/Net\/SFTP\/Stream.php#156","level":3,"time":"2015-10-20T07:07:54+00:00"}
```

**Comment by SergioBertolinSG** [comment]
cc @schiesbn

**Comment by PVince81** [comment]
Is this specific to SFTP or does it happen for SMB too ?
Could be a bug in the "partial disabling encryption" logic.

**Comment by SergioBertolinSG** [comment]
SMB works without problems.

**Comment by schiesbn** [comment]
did you configured the external storage mount point in the admin settings or in the users personal settings?

**Comment by schiesbn** [comment]
Tried it with both, system wide and personal mount point. Works for me in both cases. Also the error massage doesn't contain anything encryption specific... Tried git versions tagged as v8.2.0

**Comment by PVince81** [comment]
Works for me as well.

**Comment by SergioBertolinSG** [comment]
Ok I found my problem, an space after the port. https://github.com/owncloud/core/issues/16457#issuecomment-149857842
