### ISSUE TITLE
Fix CI for forks

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#19885]
@DeepDiver1975 @MorrisJobke raised ticket to track this :smile:

**Comment by DeepDiver1975** [comment]
first step into the right direction:
https://ci.owncloud.org/job/test-github-pr/

**Comment by DeepDiver1975** [comment]
This change did cause a too high additional load on the jenkins server - the cpu usage went up to 600% - reason: while we 'only' have less then 1000 remote branches to take care of within the core repo there are more then 9000 remote branches as soon as we take all forks into account.

This is far too much of a load -> let's delay this for now and see if there are better solutions in the not so distant future.

**Comment by PVince81** [comment]
9000 remote branches ? Does it try to run CI tests even for non-PR branches ?
Is there a way to make it only test for branches that have actual PRs against owncloud/core ?

**Comment by DeepDiver1975** [comment]
> 9000 remote branches ? Does it try to run CI tests even for non-PR branches ?
> Is there a way to make it only test for branches that have actual PRs against owncloud/core ?

I have to play a bit more around with the git refspec it seems - but primary goal is to bring back jenkins into a useable shape

**Comment by mmattel** [comment]
@DeepDiver1975 
Do you have any (good) news on that?

**Comment by DeepDiver1975** [comment]
> Do you have any (good) news on that?

no - not yet - sorry ...

**Comment by mmattel** [comment]
bad...
Do I get it right that I have to close down my current PR´s and create new once where I file against owncloud and not against my fork? (but if so why is  #21467 from icewind failing - he filed against owncloud but the check stuck at the same point...)

(I always had some "challenges" with rebasing when not using my fork which ended up in a great mess. I need some guidence here how to setup my repository in a proper way and how I do a rebase without getting all changes into my PR beeing additionally transferred to owncloud in the PR - help welcomed. For me this is a surgery on a beating heart...)

**Comment by DeepDiver1975** [comment]
we are finally there - thanks to Jenkins github organization plugin and the pipeline feature as of 2.0
