### ISSUE TITLE
formatTimeSpan usability problem - enhancement

### ISSUE THREAD

**Issue by ferdiga** [owncloud/core#19887]
on 8.0.3 web client
the date format is "2 hours ago" or 2 days ago

is it possible to change this to a usaual (linux) date time format as used in most file managers
yyyy-mm-dd HH24:mi:ss

I found this files using formatTimeSpan
./lib/private/datetimeformatter.php:196:        public function formatTimeSpan($timestamp, $baseTimestamp = null, \OCP\IL10N $l = null) {
./lib/private/template/functions.php:217:       return $formatter->formatTimeSpan($timestamp, $fromTime);
./lib/public/idatetimeformatter.php:95: public function formatTimeSpan($timestamp, $baseTimestamp = null, \OCP\IL10N $l = null);

IMO this should be configurable on a per user base

**Comment by MorrisJobke** [comment]
cc @owncloud/designers

**Comment by jancborchardt** [comment]
@ferdiga the normal date is easily visible on hovering the relative date (that should work on _any_ relative date in ownCloud).
The relative date is used because that makes it much easier to know the age of the file. Otherwise you always have to make calculations in your head.
