### ISSUE TITLE
Accessibility Bug for 8.2 UI

### ISSUE THREAD

**Issue by jsl303** [owncloud/core#19898]
The web UI for 8.2 has accessibility bug where you can't activate a lot of elements using tab keys. For example
1. Any check box in settings
Also, the check boxes don't report as a check box for screen readers.
2. Can't browse and open files/folder with using tab/shift+tab key
This is important for any user who uses screen readers or anyone who can't use mouse.
It'd be great if the accessibility bug can be fixed for the new design.
Please check out Web Content Accessibility Guidelines (WCAG) 2.0.
http://www.w3.org/TR/WCAG20/
Using WAI-ARIA
http://www.w3.org/TR/wai-aria/usage
Definition of Roles
http://www.w3.org/TR/wai-aria/roles
Definitions of States and Properties
http://www.w3.org/TR/wai-aria/states_and_properties

**Comment by PVince81** [comment]
@jancborchardt @owncloud/designers

**Comment by jsl303** [comment]
FYI, if you want to test the UI for Owncloud 8.2 with a screen reader,
Windows 10: Narrator (Press windoes+enter)
Windows: NVDA: (Open Source, more Advanced than Narrator)
http://www.nvaccess.org/
Mac: Voiceover (press command+f5)
IOS: settings > general > accessibility > Voiceover

**Comment by nickvergessen** [comment]
> 1. Any check box in settings
Also, the check boxes don't report as a check box for screen readers.

@Henni I think this is caused by your patch

**Comment by Henni** [comment]
@nickvergessen I'll look into this.

**Comment by jsl303** [comment]
Thanks! Hope it gets fixed soon.

**Comment by jancborchardt** [comment]
@jsl303 and @jmdaweb if possible it would be awesome if you can check how to make ownCloud more accessible, and even submit pull requests to directly fix it. :) We can mainly read up on guidelines and use the WAVE accessibility browser extension – if you’re deeper in the topic then you would be of great help! :)

**Comment by jancborchardt** [comment]
Also cc @Volker-E and @mroi on this accessibility issue. Any contribution is welcome. :)
