### ISSUE TITLE
[8.1]Theming

### ISSUE THREAD

**Issue by danielgek** [owncloud/core#19899]
Hello!
i'm with a problem about theming my owncloud instance!
i'm building theme and i want change the home button on files app(see image atached on the red rectangle), i have putted home.svg on `owncloud/themes/theme_name/core/img/places/home.svg` and the original place of the image is `owncloud/core/img/places/home.svg`

but the image is never switched ! 

can someone help ?
thanks in advance
<img width="576" alt="captura de ecra 2015-10-20 as 16 13 24" src="https://cloud.githubusercontent.com/assets/911198/10611812/c354590e-7745-11e5-9830-67ccf6c495a5.png">

**Comment by PVince81** [comment]
@jancborchardt any idea ?

**Comment by danielgek** [comment]
i think the image is loaded through javascript(breadcrum.js in files app if not  mistaked)

**Comment by jancborchardt** [comment]
@PVince81 I have no idea on these »images-not-getting-replaced« issues. Summoning @schiesbn cause he might have more of a clue.

Also @danielgek do you have any console log info?

**Comment by PVince81** [comment]
@jancborchardt I don't know what is supposed to be themable. If you say that such pictures should be replaceable then it's likely a bug.

**Comment by nickvergessen** [comment]
Well the image is loaded via JS:
https://github.com/owncloud/core/blob/89e3860e1ab2c5528f0f63c3192f458dc290b12e/core/js/js.js#L275-280
which doesn't have the mutlipath stuff (checking theme) like php does:
https://github.com/owncloud/core/blob/89e3860e1ab2c5528f0f63c3192f458dc290b12e/lib/private/urlgenerator.php#L156-182

No console log needed

**Comment by jancborchardt** [comment]
Yeah, all images should be themable by replacement.

**Comment by PVince81** [comment]
You should be able to force-replace it using your own CSS.
I've seen this done for other things.

Ideally that image should be changed to be CSS-only instead of an img tag.

**Comment by PVince81** [comment]
Please try again with 9.1 where theming bugs were fixed, or even 10.0 beta where theming was improved and can be provided through an app.

cc @phisch
