### ISSUE TITLE
Upgrade disabled apps listed twice

### ISSUE THREAD

**Issue by Xenopathic** [owncloud/core#19891]
When running an upgrade where apps get disabled, the disabled apps get listed twice:

![screenshot_2015-10-20_13-17-23](https://cloud.githubusercontent.com/assets/2016878/10606782/0b91d476-772d-11e5-8e3c-5a65baca66e6.png)

cc @PVince81

**Comment by PVince81** [comment]
Yeah, once as incompatible and once as third party, two separate checks...

**Comment by jancborchardt** [comment]
Just make one list like this:
> Following apps have been disabled:
> Calendar (incompatible), Notes, Mail
