### ISSUE TITLE
Bring back the legacy "8.0" search engine as an "legacy-mode" for contacts/calendar

### ISSUE THREAD

**Issue by aspdye** [owncloud/core#19897]
Since the contacts have now get even with 8.2 no real search function (which works for me), and not even taking place at the development of the calendar, I think it would make sense, to bring back the old search engine (as an legacy-mode!!) for these two apps for compatibility reasons since the use of both apps without a search does not make sense, and in my opinion both apps are "essential" for ownCloud.

Calendar+ and Contacts+ would be an option (they have an search-engine with 8.1 or 8.2) but they are not really an option, because the development does not take place in the "official" ownCloud-organisation ;)

This is not really an ownCloud Core bug, but bringing back the old-search is something with the core application (i think).

**Comment by karlitschek** [comment]
Hmm. The search app only work on top of files. So not sure this helps for missing search functions in calendar and contacts. Or maybe I misunderstood your question

**Comment by aspdye** [comment]
oh..ok. I thought there is any Search API Contacts and Calendar are using (and now they are incompatible) ;)
