### ISSUE TITLE
Update: v7.0.6 to 7.0.10 causes "multiple versions~" error.

### ISSUE THREAD

**Issue by Z4el3m** [owncloud/core#19902]
Hi, 
i had an update problem and asked at the ownCloud forum for help, There I was recommended to report a bug here. 

I tried to upgrade step by step from 7.0.5 -> 7.0.6 -> 7.0.10 -> 8.0.8.
The first update step caused only a white screen after the Login screen.
Then I made the second update. The owncloud updated appeared on the site and caused following  error:

"Updating ownCloud to version 7.0.10, this may take a while.
Wartungsmodus eingeschaltet
Exception: Updates between multiple major versions are unsupported."

I'd like to attach my bugreport template, but because I don't have permissions on this rep, I cannot attach it. Should I just upload it somewhere?

Thanks in advance

**Comment by LukasReschke** [comment]
> I'd like to attach my bugreport template, but because I don't have permissions on this rep, I cannot attach it. Should I just upload it somewhere?

Please just paste it as a comment here. Thanks :)

**Comment by Z4el3m** [comment]
Okay, here it goes:

### Steps to reproduce
1.I wanted to upgrade owncloud from 7.0.5 to 8.1.3. step by step.
2.Downloaded & installed v7.0.6 manually on 7.0.5 
3.Then downloaded & installed v7.0.10 manually on v7.0.6

### Expected behaviour
Update from 7.0.5 -> 7.0.6 -> 7.0.10 works :)

### Actual behaviour
- Update from 7.0.5 to 7.0.6 caused only white screen after I logged in to owncloud (loading screen)
- update from 7.0.6 to 7.0.10: Uploader appeared and caused this error: 

"Updating ownCloud to version 7.0.10, this may take a while.
Wartungsmodus eingeschaltet
Exception: Updates between multiple major versions are unsupported."

I downgraded back to 7.0.5. Now its working fine, but only this old version.

### Server configuration
**Operating system**:
CentOS 6
**Web server:**
Apache 2.2 (on Uberspace.de)
**Database:**
sqlite3
**PHP version:**
PHPVERSION=5.6
**ownCloud version:** (see ownCloud admin page)
7.0.5
**Updated from an older ownCloud or fresh install:**
Update
**List of activated apps:**
Bookmarks
Calendar
Contacts
Deleted files
External storage support
First Run Wizard
Full Text Search
ownCloud dependencies info
PDF Viewer
Pictures
Share Files
Text Editor
Updater0.4
Versions
Video Viewer
```

**Comment by Z4el3m** [comment]
I see the entry: 'version' => '8.0.2.0', in config.php Does this stands for ownCloud version 8.0.2? 
Maybe this is the problem? I dont know why its there, but should I try to change this to 7.0.5?
But is the admin page & version.php on ownCloud folder shows version 7.0.5...

**Comment by nickvergessen** [comment]
Yeah the config value is from your incorrect update attempt before.
Change it to 7.0.5 and retry. (This might also be the reason why you had the blank page after the update.)

Please report back, when the problem is resolved and your update to 7.0.10 finished successfully.

PS: If your owncloud.log file is too big to post it, just copy paste the last lines in the future (not needed here now anymore.

**Comment by Z4el3m** [comment]
Great, the update to 7.0.10 worked with changing the config file, thank you!!
Then I tried to update to 8.0.8. Now I have a white screen :(
Here are the last logs:

{"reqId":"5627ca895b3bf","app":"index","message":"OC\\NeedsUpdateException: ","level":4,"time":"2015-10-21T17:25:29+00:00","method":"GET","url":"\/owncloud\/index.php\/core\/js\/oc.js?v=45b994d6a19dd0a6f83c2b6c2db3b7c7"}
{"reqId":"5627ca8b8bce4","app":"core","message":"starting upgrade from 7.0.5.2 to 7.0.10.0","level":0,"time":"2015-10-21T17:25:31+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=fe294c2325f66d933ab7"}
{"reqId":"e029dc4efe55af13be367894f6633ebf","remoteAddr":"95.90.250.169","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/var\/www\/virtual\/zalem\/html\/owncloud\/lib\/private\/app.php#1232","level":3,"time":"2015-10-21T17:37:40+00:00","method":"GET","url":"\/owncloud\/"}
{"reqId":"e029dc4efe55af13be367894f6633ebf","remoteAddr":"95.90.250.169","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/virtual\/zalem\/html\/owncloud\/lib\/private\/app.php#1235","level":3,"time":"2015-10-21T17:37:41+00:00","method":"GET","url":"\/owncloud\/"}
{"reqId":"1de6d16eba36c5509fc4f743cc1eb44d","remoteAddr":"95.90.250.169","app":"index","message":"Exception: {\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/virtual\\\/zalem\\\/html\\\/owncloud\\\/lib\\\/private\\\/app.php(76): OC_App::loadApp('files_sharing')\\n#1 \\\/var\\\/www\\\/virtual\\\/zalem\\\/html\\\/owncloud\\\/lib\\\/private\\\/util.php(75): OC_App::loadApps(Array)\\n#2 \\\/var\\\/www\\\/virtual\\\/zalem\\\/html\\\/owncloud\\\/lib\\\/base.php(790): OC_Util::setupFS()\\n#3 \\\/var\\\/www\\\/virtual\\\/zalem\\\/html\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/var\\\/www\\\/virtual\\\/zalem\\\/html\\\/owncloud\\\/lib\\\/private\\\/app.php\",\"Line\":96}","level":4,"time":"2015-10-21T17:37:42+00:00","method":"GET","url":"\/owncloud\/index.php\/core\/js\/oc.js?v=d836aa6173e9d0534872ba74767bca7e"}
{"reqId":"7876a5fe021b64be41bfe3891b64fb96","remoteAddr":"95.90.250.169","app":"core","message":"starting upgrade from 7.0.10.0 to 8.0.8.0","level":0,"time":"2015-10-21T17:37:45+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=fe294c2325f66d933ab7"}
{"reqId":"7876a5fe021b64be41bfe3891b64fb96","remoteAddr":"95.90.250.169","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/var\/www\/virtual\/zalem\/html\/owncloud\/lib\/private\/app.php#1232","level":3,"time":"2015-10-21T17:37:45+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=fe294c2325f66d933ab7"}
{"reqId":"7876a5fe021b64be41bfe3891b64fb96","remoteAddr":"95.90.250.169","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/virtual\/zalem\/html\/owncloud\/lib\/private\/app.php#1235","level":3,"time":"2015-10-21T17:37:46+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=fe294c2325f66d933ab7"}
{"reqId":"28f9007ab2715abfddd9e4edc6271b51","remoteAddr":"95.90.250.169","app":"index","message":"Exception: {\"Message\":\"js file not found: script:miniColors\\\/l10n\\\/de_DE serverroot:\\\/var\\\/www\\\/virtual\\\/zalem\\\/html\\\/owncloud\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/virtual\\\/zalem\\\/html\\\/owncloud\\\/lib\\\/private\\\/templatelayout.php(156): OC\\\\Template\\\\ResourceLocator->find(Array)\\n#1 \\\/var\\\/www\\\/virtual\\\/zalem\\\/html\\\/owncloud\\\/lib\\\/private\\\/templatelayout.php(107): OC_TemplateLayout::findJavascriptFiles(Array)\\n#2 \\\/var\\\/www\\\/virtual\\\/zalem\\\/html\\\/owncloud\\\/lib\\\/private\\\/template.php(118): OC_TemplateLayout->__construct('guest', '')\\n#3 \\\/var\\\/www\\\/virtual\\\/zalem\\\/html\\\/owncloud\\\/lib\\\/private\\\/template\\\/base.php(103): OC_Template->fetchPage()\\n#4 \\\/var\\\/www\\\/virtual\\\/zalem\\\/html\\\/owncloud\\\/lib\\\/private\\\/template.php(197): OC\\\\Template\\\\Base->printPage()\\n#5 \\\/var\\\/www\\\/virtual\\\/zalem\\\/html\\\/owncloud\\\/lib\\\/private\\\/util.php(807): OC_Template::printGuestPage('', 'login', Array)\\n#6 \\\/var\\\/www\\\/virtual\\\/zalem\\\/html\\\/owncloud\\\/lib\\\/base.php(898): OC_Util::displayLoginPage(Array, Array)\\n#7 \\\/var\\\/www\\\/virtual\\\/zalem\\\/html\\\/owncloud\\\/lib\\\/base.php(849): OC::handleLogin()\\n#8 \\\/var\\\/www\\\/virtual\\\/zalem\\\/html\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/virtual\\\/zalem\\\/html\\\/owncloud\\\/lib\\\/private\\\/template\\\/resourcelocator.php\",\"Line\":46}","level":4,"time":"2015-10-21T17:37:50+00:00","method":"GET","url":"\/owncloud\/"}
{"reqId":"28f9007ab2715abfddd9e4edc6271b51","remoteAddr":"95.90.250.169","app":"PHP","message":"js file not found: script:miniColors\/l10n\/de_DE serverroot:\/var\/www\/virtual\/zalem\/html\/owncloud at \/var\/www\/virtual\/zalem\/html\/owncloud\/lib\/private\/template\/resourcelocator.php#46","level":3,"time":"2015-10-21T17:37:50+00:00","method":"GET","url":"\/owncloud\/"}
{"reqId":"1945687625e647a03f696701de39802f","remoteAddr":"95.90.250.169","app":"index","message":"Exception: {\"Message\":\"js file not found: script:miniColors\\\/l10n\\\/de_DE serverroot:\\\/var\\\/www\\\/virtual\\\/zalem\\\/html\\\/owncloud\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/virtual\\\/zalem\\\/html\\\/owncloud\\\/lib\\\/private\\\/templatelayout.php(156): OC\\\\Template\\\\ResourceLocator->find(Array)\\n#1 \\\/var\\\/www\\\/virtual\\\/zalem\\\/html\\\/owncloud\\\/lib\\\/private\\\/templatelayout.php(107): OC_TemplateLayout::findJavascriptFiles(Array)\\n#2 \\\/var\\\/www\\\/virtual\\\/zalem\\\/html\\\/owncloud\\\/lib\\\/private\\\/template.php(118): OC_TemplateLayout->__construct('guest', '')\\n#3 \\\/var\\\/www\\\/virtual\\\/zalem\\\/html\\\/owncloud\\\/lib\\\/private\\\/template\\\/base.php(103): OC_Template->fetchPage()\\n#4 \\\/var\\\/www\\\/virtual\\\/zalem\\\/html\\\/owncloud\\\/lib\\\/private\\\/template.php(197): OC\\\\Template\\\\Base->printPage()\\n#5 \\\/var\\\/www\\\/virtual\\\/zalem\\\/html\\\/owncloud\\\/lib\\\/private\\\/util.php(807): OC_Template::printGuestPage('', 'login', Array)\\n#6 \\\/var\\\/www\\\/virtual\\\/zalem\\\/html\\\/owncloud\\\/lib\\\/base.php(898): OC_Util::displayLoginPage(Array, Array)\\n#7 \\\/var\\\/www\\\/virtual\\\/zalem\\\/html\\\/owncloud\\\/lib\\\/base.php(849): OC::handleLogin()\\n#8 \\\/var\\\/www\\\/virtual\\\/zalem\\\/html\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/virtual\\\/zalem\\\/html\\\/owncloud\\\/lib\\\/private\\\/template\\\/resourcelocator.php\",\"Line\":46}","level":4,"time":"2015-10-21T17:38:52+00:00","method":"GET","url":"\/owncloud\/"}
{"reqId":"1945687625e647a03f696701de39802f","remoteAddr":"95.90.250.169","app":"PHP","message":"js file not found: script:miniColors\/l10n\/de_DE serverroot:\/var\/www\/virtual\/zalem\/html\/owncloud at \/var\/www\/virtual\/zalem\/html\/owncloud\/lib\/private\/template\/resourcelocator.php#46","level":3,"time":"2015-10-21T17:38:52+00:00","method":"GET","url":"\/owncloud\/"}
{"reqId":"b3ddd7576033f1f510a1db127776b23f","remoteAddr":"95.90.250.169","app":"PHP","message":"Class 'OC_Connector_Sabre_Principal' not found at \/var\/www\/virtual\/zalem\/html\/owncloud\/apps\/contacts\/appinfo\/remote.php#39","level":3,"time":"2015-10-21T17:39:14+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/carddav\/addressbooks\/zalem\/contacts\/"}
{"reqId":"2eada8f73b40dd9483184e4f8bbb380e","remoteAddr":"95.90.250.169","app":"PHP","message":"Class 'OC_Connector_Sabre_Principal' not found at \/var\/www\/virtual\/zalem\/html\/owncloud\/apps\/calendar\/appinfo\/remote.php#23","level":3,"time":"2015-10-21T17:39:14+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/caldav\/calendars\/zalem\/defaultcalendar\/"}
