### ISSUE TITLE
When you display details of a file, you cannot see the user menu

### ISSUE THREAD

**Issue by canepan** [owncloud/core#19900]
If you try to open the user menu when a file details are open, he menu is (I think) behind the details pane.
Not a big issue: if you close the details, the menu is open

**Comment by PVince81** [comment]
Are you talking about 8.2 ?

Can you post a screenshot ?

In general for bug reports, please use the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by jancborchardt** [comment]
Can’t reproduce and could never. We made sure of course that the user menu is always above the sidebar. ;)

**Comment by canepan** [comment]
It was an issue with my theme: I had
> #body-public #header {
> [...]
>           z-index: 100;

instead of
>         z-index: 2000;

**Comment by jancborchardt** [comment]
@canepan I would recommend to not mess with positioning such as z-index in a theme. :) If you simply remove the line, the core rule will be used.
