### ISSUE TITLE
The user management should use the provisioning API

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#19904]
To eliminate multiple code paths we should move the user management page from using it own custom private endpoint to the provisiioning API. 

With the recent improvements in the provisioning API I think this should be feasible. Probabaly not it the near future but could be a long term goal.

Steps:
1. Research missing functionality in provisioning API
2. Add missing functionality
3. Move user management to provisioning API
4. ....
5. World domination

CC: @tomneedham

**Comment by karlitschek** [comment]
good idea. Something for the future.

**Comment by MorrisJobke** [comment]
What we should also remind: We then need to add the provisiong_api app as mandatory.

**Comment by MorrisJobke** [comment]
cc @PVince81

**Comment by PVince81** [comment]
it does now with https://github.com/owncloud/user_management

**Comment by DeepDiver1975** [comment]
not going to happen -> close
