### ISSUE TITLE
Memcache warning with memcached

### ISSUE THREAD

**Issue by jasondickert** [owncloud/core#19908]
### Steps to reproduce
1. Install ownCloud 8.2
2. Configure ownCloud for memcached
3. Security & setup warnings 

### Expected behaviour
Should be no memcache warning on a system without memcache.  Memcahced shouldn't cause a warning about memcache.

### Actual behaviour
Warning on admin page:
Memcached is configured as distributed cache, but the wrong PHP module "memcache" is installed. \OC\Memcache\Memcached only supports "memcached" and not "memcache". See the memcached wiki about both modules.

### Server configuration
**Operating system**:
Amazon Linux, 4.1.7-15.23.amzn1.x86_64

**Web server:**
Apache 2.4, httpd 2.4.16-1.62.amzn1

**Database:**
sqlite3

**PHP version:**
PHP 5.6, 5.6.13-1.118.amzn1

**ownCloud version:** (see ownCloud admin page)
ownCloud 8.2.0 (stable) 

**Updated from an older ownCloud or fresh install:**
Ugraded from 8.1.3, then reset (deleted owncloud.db config.php and reset)

**List of activated apps:**
Enabled:
  - activity: 2.1.3
  - files: 1.2.0
  - files_locking: 
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - updater: 0.6
  - user_ldap: 0.7.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx,
  'trusted_domains' => 
  array (
    0 => 'acme',
  ),
  'datadirectory' => '/mnt/data/var/www/html/owncloud/data',
  'overwrite.cli.url' => 'https://acme/owncloud',
  'dbtype' => 'sqlite3',
  'version' => '8.2.0.12',
  'logtimezone' => 'UTC',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'mail_smtpmode' => 'php',
  'mail_from_address' => 'mail',
  'mail_domain' => 'acme.com',
  'memcache.local' => '\\OC\\Memcache\\Memcached',
  'memcache.distributed' => '\\OC\\Memcache\\Memcached',
  'memcached_servers' => 
  array (
    0 => 
    array (
      0 => 'localhost',
      1 => 11211,
    ),
  ),
);
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system --public
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No, the data directory is not the default though

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP

#### LDAP configuration (delete this part if not used)
+-------------------------------+-------------------------------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                                                   |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                                                                                 |
| hasPagedResultSupport         |                                                                                                                   |
| homeFolderNamingRule          |                                                                                                                   |
| lastJpegPhotoLookup           | 0                                                                                                                 |
| ldapAgentName                 | cn=owncloud,ou=sysaccounts,dc=acme,dc=com                                                                      |
| ldapAgentPassword             | ***                                                                                                               |
| ldapAttributesForGroupSearch  |                                                                                                                   |
| ldapAttributesForUserSearch   |                                                                                                                   |
| ldapBackupHost                |                                                                                                                   |
| ldapBackupPort                |                                                                                                                   |
| ldapBase                      | dc=acme,dc=com                                                                                                 |
| ldapBaseGroups                | ou=groups,dc=acme,dc=com                                                                                       |
| ldapBaseUsers                 | ou=people,dc=acme,dc=com                                                                                       |
| ldapCacheTTL                  | 60                                                                                                                |
| ldapConfigurationActive       | 1                                                                                                                 |
| ldapEmailAttribute            | mail                                                                                                              |
| ldapExperiencedAdmin          | 0                                                                                                                 |
| ldapExpertUUIDGroupAttr       |                                                                                                                   |
| ldapExpertUUIDUserAttr        |                                                                                                                   |
| ldapExpertUsernameAttr        | uid                                                                                                               |
| ldapGroupDisplayName          | ou                                                                                                                |
| ldapGroupFilter               | (&(objectclass=groupOfUniqueNames) (businessCategory=owncloud))                                                   |
| ldapGroupFilterGroups         |                                                                                                                   |
| ldapGroupFilterMode           | 1                                                                                                                 |
| ldapGroupFilterObjectclass    |                                                                                                                   |
| ldapGroupMemberAssocAttr      | uniqueMember                                                                                                      |
| ldapHost                      | ldaps://localhost.localdomain                                                                                       |
| ldapIgnoreNamingRules         |                                                                                                                   |
| ldapLoginFilter               | (&(&(objectclass=OpenLDAPperson)(businessCategory=owncloud))(|(uid=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid)))) |
| ldapLoginFilterAttributes     |                                                                                                                   |
| ldapLoginFilterEmail          | 1                                                                                                                 |
| ldapLoginFilterMode           | 1                                                                                                                 |
| ldapLoginFilterUsername       | 1                                                                                                                 |
| ldapNestedGroups              | 0                                                                                                                 |
| ldapOverrideMainServer        |                                                                                                                   |
| ldapPagingSize                | 500                                                                                                               |
| ldapPort                      | 636                                                                                                               |
| ldapQuotaAttribute            | ownCloudQuota                                                                                                     |
| ldapQuotaDefault              | 15 GB                                                                                                             |
| ldapTLS                       |                                                                                                                   |
| ldapUserDisplayName           | cn                                                                                                                |
| ldapUserFilter                | (&(objectclass=OpenLDAPperson) (businessCategory=owncloud))                                                       |
| ldapUserFilterGroups          |                                                                                                                   |
| ldapUserFilterMode            | 1                                                                                                                 |
| ldapUserFilterObjectclass     | OpenLDAPperson                                                                                                    |
| ldapUuidGroupAttribute        | auto                                                                                                              |
| ldapUuidUserAttribute         | auto                                                                                                              |
| turnOffCertCheck              | 0                                                                                                                 |
| useMemberOfToDetectMembership | 0                                                                                                                 |
```
On ownCloud 7+ with access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

On ownCloud 6 with access to your command line run e.g.:
sqlite3 data/owncloud.db or mysql -u root -p owncloud
then execute:  select * from oc_appconfig where appid='user_ldap';

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query above.

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
Firefox

**Operating system:**
OS X

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
Bulk of log is this (found no 'memcache' in logs):
{"reqId":"qPTDHrBwxV36kKC3dKao","remoteAddr":"172.31.5.192","app":"PHP","message":"Undefined index: cn at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/access.php#695","level":3,"time":"2015-10-20T15:01:13+00:00"}
{"reqId":"7+51fAYQEqeejlnRUsl+","remoteAddr":"172.31.31.183","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-20T15:03:10+00:00"}
{"reqId":"Y1qWACJUaXpdmrSygXyr","remoteAddr":"172.31.5.192","app":"PHP","message":"ldap_search(): Partial search results returned: Sizelimit exceeded at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-20T15:03:35+00:00"}
{"reqId":"JZSeRcFRbWJmhU235th9","remoteAddr":"172.31.5.192","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-20T15:04:10+00:00"}
{"reqId":"2KjdkX0WIbvnL2rE\/F3t","remoteAddr":"172.31.5.192","app":"PHP","message":"Undefined index: cn at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/access.php#695","level":3,"time":"2015-10-20T15:04:41+00:00"}
{"reqId":"GTtJdupApDI+uitKOvHC","remoteAddr":"172.31.31.183","app":"PHP","message":"Array to string conversion at \/var\/www\/html\/owncloud\/lib\/private\/template\/functions.php#36","level":3,"time":"2015-10-20T15:11:10+00:00"}
{"reqId":"XekRYEVEOjVLGB786Nc+","remoteAddr":"172.31.31.183","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-20T15:11:12+00:00"}
{"reqId":"niaym9oOTAb+unPI3nuk","remoteAddr":"172.31.31.183","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-20T15:11:26+00:00"}
{"reqId":"1921GeMSgKMzhua7kdJP","remoteAddr":"172.31.31.183","app":"PHP","message":"array_slice() expects parameter 1 to be array, object given at \/var\/www\/html\/owncloud\/apps\/user_ldap\/group_ldap.php#530","level":3,"time":"2015-10-20T15:11:43+00:00"}
{"reqId":"380jaLI0fAw7no3bQBvY","remoteAddr":"172.31.31.183","app":"PHP","message":"Array to string conversion at \/var\/www\/html\/owncloud\/lib\/private\/template\/functions.php#36","level":3,"time":"2015-10-20T15:12:57+00:00"}
{"reqId":"3W4hfIWn1P5FqIE5TRcE","remoteAddr":"172.31.31.183","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-20T15:12:59+00:00"}
{"reqId":"WW5\/rxMbMm\/jwA8pEHRJ","remoteAddr":"172.31.5.192","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-20T17:41:26+00:00"}
{"reqId":"RUkP5GGFpfzEKNXwkpLG","remoteAddr":"172.31.31.183","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-20T18:36:55+00:00"}
{"reqId":"fyluVK4dDFcBhmI3SX2+","remoteAddr":"172.31.31.183","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-20T18:37:13+00:00"}
{"reqId":"k\/OFvBON741lwrqLe6Yo","remoteAddr":"172.31.31.183","app":"PHP","message":"Array to string conversion at \/var\/www\/html\/owncloud\/lib\/private\/template\/functions.php#36","level":3,"time":"2015-10-20T18:52:12+00:00"}
{"reqId":"iML65LfuijCm9jOC6e2C","remoteAddr":"172.31.31.183","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-20T18:52:15+00:00"}
{"reqId":"I5sZwxqP6h2Vi7to\/Oly","remoteAddr":"172.31.31.183","app":"PHP","message":"Array to string conversion at \/var\/www\/html\/owncloud\/lib\/private\/template\/functions.php#36","level":3,"time":"2015-10-20T19:53:35+00:00"}
{"reqId":"F0Ct9ZpOrefYCVb9XW8V","remoteAddr":"172.31.31.183","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-20T19:53:37+00:00"}

**Comment by karlitschek** [comment]
@LukasReschke can you have a look?

**Comment by jasondickert** [comment]
![ocwarnings](https://cloud.githubusercontent.com/assets/15220124/10619732/4aabda36-7745-11e5-9561-ea5a2cd58b5d.png)
![memcached](https://cloud.githubusercontent.com/assets/15220124/10619733/4c572052-7745-11e5-81e7-ef125e128fa3.png)

**Comment by Xenopathic** [comment]
Oops the check is wrong...
