### ISSUE TITLE
upgrade 8.1.3 to 8.2.0 aborted at documents app

### ISSUE THREAD

**Issue by ege1** [owncloud/core#19905]
Hi,

My owncloud upgrade aborted with the message:

PHP Fatal error:  Call to undefined method OCP\App::register() in /var/www/owncloud/apps/documents/appinfo/app.php on line 24

After some fiddling I was able to get it running again but as soon as I re-enable documents app I do get the same failure. I've to set maintenance mode by editing the config file, disable documents through occ and disable maintenance mode to get owncloud working again.

I'm running debian wheezy and am using PostgreSQL database backend.

The owncloud logfile in the data directory is empty.

What else do you need?

Erik

**Comment by RealRancor** [comment]
Hi,

please report this to:

https://github.com/owncloud/documents/issues

by using the issue template described in the guidelines for contributing (linked in the yellow box when creating a new issue).

The issue itself seems to be caused by the documents app declaring itself as compatible to oC 8.5 where it seems it is not.

**Comment by karlitschek** [comment]
Did we remove the OCP register call? It should be still present to keep the API compatible. @DeepDiver1975 @LukasReschke  ?

**Comment by ege1** [comment]
Thanks, opened issue 558: https://github.com/owncloud/documents/issues/558

**Comment by RealRancor** [comment]
@karlitschek Deprecated since 3years so it seems it was removed as discussed here:

https://github.com/owncloud/core/pull/15663

**Comment by ege1** [comment]
OK, for me this is solved. My "documents" application wasn't the latest version, that's why it didn't work. Now after updating "documents" all is fine.

**Comment by karlitschek** [comment]
@DeepDiver1975 This is what we discussed earlier. We have to find some way that this can't happen anymore.
Like:
- keep empty deprecated ocp call around longer
- send more visible warning to the log or even Admin page that an app is using deprecated api and should be updated soon?
- force upgrading of apps before core upgrade. (probably doesn't work)
- some thing else

**Comment by LukasReschke** [comment]
Or: Have apps not lying :speak_no_evil: 

https://github.com/owncloud/documents/commit/a8e1d1462249b3e15906da4b325b02d30eccf92b#commitcomment-13881357

**Comment by shaneonabike** [comment]
Also documenting that documents is no longer shipped as a app would be good in the 8.2 docs cause I ran into this and had no idea :/
