### ISSUE TITLE
owncloud client 2.0.1 centos 6 linux package error in owncloudcmd script

### ISSUE THREAD

**Issue by toddpfaff** [owncloud/core#19903]
--- /usr/bin/owncloudcmd.orig   2015-10-14 07:14:05.000000000 -0400
+++ /usr/bin/owncloudcmd        2015-10-20 14:50:28.614604431 -0400
@@ -5,6 +5,6 @@
 source /opt/qt-4.8/bin/qt-4.8-env.sh
 source /opt/neon-0.30.0/oc-neon-env.sh
 
-exec /opt/qt-4.8/bin/owncloud "$@"
+exec /opt/qt-4.8/bin/owncloudcmd "$@"
 
 # end

... better yet, change to this:

  exec /opt/qt-4.8/bin/`basename $0` "$@"

in both owncloud and owncloudcmd scripts and then link one to the other.

tp

**Comment by RealRancor** [comment]
Hi,

the clients issue tracker is located here:

https://github.com/owncloud/client/issues

Please re-open there using the issue template described in the guidelines for contributing (linked in the yellow box when creating a new issue).
