### ISSUE TITLE
Tasks app is missing after upgrade 8.1.3 to 8.2.0

### ISSUE THREAD

**Issue by ege1** [owncloud/core#19906]
Hi,

After upgrading owncloud the Tasks app disappeared. I even can't find it under the experimental applications.

Did I miss something?

Erik

**Comment by RealRancor** [comment]
Just check https://apps.owncloud.com/content/show.php/Tasks?content=164356

There is no oC 8.2 compatible version released yet.

**Comment by ege1** [comment]
Ahhh, thanks :)

I just overlooked the "Maximum Required" Version.

Sorry for the noise...
