### ISSUE TITLE
User menu does not close on file actions menu opening

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#19916]
This works fine with the apps menu and the actions menu, and the apps menu and the user menu. It’s just that when you:
1. Open the user menu in the top right
2. Open the file actions menu on a file

You would expect the user menu to close. But it doesn. cc @PVince81

**Comment by PVince81** [comment]
I guess the user menu is probably not registered as menu using `OC.registerMenu` or `OC.showMenu`
