### ISSUE TITLE
upgrade 8.1.3 to 8.2.0 failed : Updates between multiple major versions and downgrades are unsupported.

### ISSUE THREAD

**Issue by elkos66** [owncloud/core#19910]
Hello,
I have this message after trying to update from 8.1.3 to 8.2.0
Manualy update -> copy owncloud from the zip file, copy my config file (8.1.3)
Restart web server.
Was working fine with all other version

**Comment by karlitschek** [comment]
Can you please post a full bug report using this issue template?
https://raw.githubusercontent.com/owncloud/core/master/issue_template.md
Thanks a lot

**Comment by elkos66** [comment]
In the config file was in version was :
version' => '8.0.2.0' i put manually 8.1.3 and it's ok
I close the case
