### ISSUE TITLE
Database unavailable

### ISSUE THREAD

**Issue by rossey** [owncloud/core#19911]
MySQL had run out of memory on my VPS and ownCloud sent back a generic 500 error. I couldn't find anything in the ownCloud or Apache logs. 

I think it would be worth either logging or sending back a message that says the database in unavailable.

I'm happy to make a PR if someone points me in the right direction :)

**Comment by Xenopathic** [comment]
We should already be logging database connection errors, if we aren't then that's a bug. For reference, the code that throws the exception is here: https://github.com/owncloud/core/blob/master/lib/private/db/connection.php#L52

**Comment by rossey** [comment]
Thanks @Xenopathic. This was Digital Ocean's pre-built ownCloud VM. I was looking in `/var/logs/owncloud.log`. Although it looks like the logging is not configured in `config.php`. Do you know what the default logging configuration is?

**Comment by Xenopathic** [comment]
The default configuration is set to the warning level, but database connection errors are logged at any log level, so they should definitely appear.

**Comment by RealRancor** [comment]
@rossey If no logging is configured in your config.php it defaults to your datadir/owncloud.log (e.g. /var/www/owncloud/data/owncloud.log)

**Comment by MorrisJobke** [comment]
@rossey Please reopen if the db outage isn't logged.
