### ISSUE TITLE
"resources" folder missing after upgrade to 8.2.0 (using apt on Debian 8.2)

### ISSUE THREAD

**Issue by DerZeitspringer** [owncloud/core#19912]
### Steps to reproduce
1. Upgrade from Version 8.1.3 to Version 8.2.0 via apt-Repository on Debian 8.2

### Expected behaviour
Apps "Contacts" and "Calendar" have been marked to be disabled during upgrade as they were incompatible. Normally, you can update them via "Apps" page.

### Actual behaviour
Apps "Contacts" and "Calendar" have been out-of-date. OwnCloud did not update them (via "Apps" page), so functionality was broken. After checking the "Admin" page, i realized, that my ownCloud thought it was offline ("... no working internet connection ..."). That never happened before.

So i check ownCloud.log, which was flooded with the following:
`{core} Could not get application: SSL CA bundle not found: /var/www/owncloud/resources/config/ca-bundle.crt`

The mentioned folder structure (/resources/config) wasn't there. I downloaded the owncloud sources to check and found the corresponding .crt file among others ("metadetection" stuff). I copied the complete "resources" folder to my installation and everything was fine again (update of apps, internet detection).

I assume that the "resources" folder is not part of the .deb file.

### Server configuration
**Operating system**: Debian 8.2

**Web server:**
n/a

**Database:**
n/a

**PHP version:**
n/a

**ownCloud version:** (see ownCloud admin page)
8.2.0 
**Updated from an older ownCloud or fresh install:**
8.1.3
**List of activated apps:**
n/a

**The content of config/config.php:** 
n/a

**Are you using external storage, if yes which one:** local/smb/sftp/... 
no

**Are you using encryption:** 
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
n/a

**Operating system:**
n/a

#### Web server error log
n/a

#### ownCloud log (data/owncloud.log)
see above

#### Browser log
n/a

**Comment by Xenopathic** [comment]
cc @jnweiger

**Comment by RealRancor** [comment]
Should be already fixed since a few hours: https://github.com/owncloud/owncloud.org/issues/754#issuecomment-149649089
