### ISSUE TITLE
Video streaming broken in 8.2.0, returns HTTP status code 200 instead of 206

### ISSUE THREAD

**Issue by Instagit** [owncloud/core#19919]
The result is that videos with a size of more than a few MB can't be played anymore.

VideoJS throws this error:

"The video could not be loaded, either because the server or network failed or because the format is not supported"

The default video player fails silently.

**Comment by PVince81** [comment]
Is that the video player app from https://github.com/owncloud/apps ?

CC @VicDeo

**Comment by Instagit** [comment]
Yes, that video player only showed an empty element. My own video player app showed the mentioned error message. After installing the latest patches through the Ubuntu repository

owncloud:amd64 (8.2.0-1.1, 8.2.0-2.1)
owncloud-server:amd64 (8.2.0-1.1, 8.2.0-2.1)
owncloud-config-apache:amd64 (8.2.0-1.1, 8.2.0-2.1)

 the videos are playing again though, in both players.
