### ISSUE TITLE
Text editor: 'File: modified since opening', can't save on some external storages

### ISSUE THREAD

**Issue by Jaimy85** [owncloud/core#19914]
When trying to save a modified text file on external storages I get a warning like 'Problem saving changes, click to continue editing'.
This does not happen with a S3 external storage, only with Hubic app https://apps.owncloud.com/content/show.php?content=168188 and Openstack object storage.
"File: x modified since opening" is from the log.

**Comment by PVince81** [comment]
The text editor is here: https://github.com/owncloud/files_texteditor

@tomneedham

**Comment by nickvergessen** [comment]
Please open a new issue in the repository mentioned above
