### ISSUE TITLE
Integrating with GitFS (filesystem automatically tracking changes) as underlying filesystem

### ISSUE THREAD

**Issue by arjamizo** [owncloud/core#19928]
Hello, 

recently I have learned (thanks to #unknownews on fb) about https://www.presslabs.com/gitfs/ 
I have always dreamed about having full file history on owncloud, now it seems easier than ever. 
Do you think this is possible to integrate owncloud and GitFS?

**Comment by DeepDiver1975** [comment]
> Do you think this is possible to integrate owncloud and GitFS?

why not - give it a try :wink: 

At first sight it looks like a local folder is mounted to a git repo.
This is something to be done on pure operating system level from my understanding - nothing to be implemented within owncloud.

**Comment by DeepDiver1975** [comment]
> nothing to be implemented within owncloud.

and because of that I'm closing this issue - THX a lot

**Comment by arjamizo** [comment]
Partly I agree, partly no (about nothing to be implemented within owncloud). 
It would be awesome to have an interface to access previous revisions from within OC, don't you think? 

I will give it a try and let you know how it works.

**Comment by DeepDiver1975** [comment]
> It would be awesome to have an interface to access previous revisions from within OC, don't you think?

If there is any kind of interface to access this information - this is for sure of interest.
