### ISSUE TITLE
Remove .mailmap from release tarball

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#19921]
The release tarball for 8.2 contains the file ".mailmap" which is only useful when working with git, not for productive servers.

This file doesn't exist in RPM/DEB package, so I think it should be excluded from the tarballs as well.

@karlitschek @cmonteroluque @DeepDiver1975

**Comment by nickvergessen** [comment]
I thought the same, when I updated my installations yesterday with the **tarballs**.

Other files that should be either updated or deleted are:
* [`indie.json`](https://github.com/owncloud/core/blob/master/indie.json#L31) - Says the version is 7.0.0 `"version": "7.0.0",`
* [`AUTHORS`](https://github.com/owncloud/core/blob/master/AUTHORS) missing almost everyone that is currently active and the list of libs is quite small/outdated as well
* [`.tag`](https://github.com/owncloud/core/blob/master/.tag) - whats the use of this file?

**Comment by DeepDiver1975** [comment]
AUTHORS should be updated as soon as we update .mailmap ...
.tag was requested by @danimo - for sure for a reason :wink: 
and finally summoning @jancborchardt on indie.json - I have no idea what this is about

**Comment by nickvergessen** [comment]
From the commit message:
>  **Add .tag file to make tar balls tracable**
>
The "git archive" operation will substitute the contents of this
file with the hash sum of the commit that this tar ball is based
on. This improves tracebility and allows to retrospectively set
tags. It has proven to be a valuable asset in mirall.

Seems like we are not using git archive and therefor this makes no sense

**Comment by jancborchardt** [comment]
@bnvk did the indie.json ever go anywhere? The only other file I see is the one [in Mailpile](https://github.com/mailpile/Mailpile/blob/master/indie.json), which is also pretty outdated.

**Comment by karlitschek** [comment]
O.K. The .mailmap file will be removed from the releases from now on. Even better would be to not have all this internal cruft in the core repository in the first place. We rely on the packaging scripts nowadays to delete a ton of stuff that is in the core repository but shouldn't be in the release. I still like the old days where doing a release was basically zipping up core with all this additional magic steps that can break stuff.

I wouldn't mind killing indie.json too if it is not useful. Less stuff is better.

**Comment by bnvk** [comment]
Yes, kill indie.json it never went anywhere. I appreciated the
willingness to try it back then :)

**Comment by nickvergessen** [comment]
@karlitschek statement about the .tag file? then I can prepare a PR tomorrow.

**Comment by DeepDiver1975** [comment]
> statement about the .tag file? then I can prepare a PR tomorrow.

@danimo's call is required as well

**Comment by DeepDiver1975** [comment]
> then I can prepare a PR tomorrow.

https://github.com/owncloud/core/pull/19953

**Comment by LukasReschke** [comment]
> AUTHORS should be updated as soon as we update .mailmap ...

What about https://github.com/owncloud/core/pull/20049?

**Comment by MorrisJobke** [comment]
Okay ...so this is all done. Close
