### ISSUE TITLE
upload on link shared folder failes with JS Error "TypeError: OCA.Files.App is undefined"

### ISSUE THREAD

**Issue by michag86** [owncloud/core#19922]
### Steps to reproduce
1. share a folder by link with upload permission
2. try to upload a file to this link share

### Expected behaviour
file should be uploaded

### Actual behaviour
file isn't uploaded
JS Error: TypeError: OCA.Files.App is undefined  -  file-upload.js:185:7

### Server configuration
Fresh VM Image: http://download.owncloud.org/community/production/vm/xUbuntu_14.04-owncloud-8.2.0-2.1-201510201921.vmx.zip

**Comment by PVince81** [comment]
Indeed...

**Comment by PVince81** [comment]
Likely to be a regression introduced by the changes for the conflict dialog: https://github.com/owncloud/core/issues/19417

**Comment by PVince81** [comment]
It's even worse, even after fixing the filelist issue, the upload doesn't work due to "formData is not defined"

**Comment by PVince81** [comment]
@cmonteroluque @DeepDiver1975 @karlitschek

**Comment by enoversum** [comment]
I think this is about the same. When I uploaded a file and share the link, clicking the download button on the link gives out an error in the console (`Uncaught ReferenceError: oc_appconfig is not defined  shareconfigmodel.js`) plus an owncloud warning of an internal server error.

**Comment by PVince81** [comment]
@enoversum that looks like a different issue, not related to upload. Please raise a separate ticket.

**Comment by enoversum** [comment]
@PVince81 Oh well, sounded like the same source. Will do, thanks!

**Comment by PVince81** [comment]
Thanks. Please mention me there.

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/19931
