### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by briskspirit** [owncloud/core#19926]
OC 8.2, get this error in browser console on every page:
Failed to load resource: the server responded with a status of 404 (Not Found)
https://xxx/assets/jquery.min.map

Plus this one in Files, Admin, Applications(and etc):
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'".

**Comment by RealRancor** [comment]
Hi,

this .map file is requested by google developer tools:

https://stackoverflow.com/questions/18365315/jquerys-jquery-1-10-2-min-map-is-triggering-a-404-not-found/18365316#18365316

Nothing what needs to be fixed from oC side.

**Comment by briskspirit** [comment]
So maybe for production releases you need to switch maps off? Like on stackoverflow?

You can remove the 404 by removing the line

//@ sourceMappingURL=jquery-1.10.2.min.map
from the top part of your jQuery file.

**Comment by nickvergessen** [comment]
@MorrisJobke @PVince81 js dependency fun

**Comment by PVince81** [comment]
The map file (source map) error can be ignored, it's usually there for debugging but actually never worked... Since it never worked let's remove it.

**Comment by briskspirit** [comment]
And what about Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". ?

**Comment by PVince81** [comment]
No idea. @LukasReschke ?

Maybe a third party app is trying to use eval()

**Comment by briskspirit** [comment]
This happens in native apps : Files, Admin, Appstore

**Comment by nickvergessen** [comment]
Note that other apps can run code on those. So not all scripts that run on files are actually from files.

**Comment by briskspirit** [comment]
ok, will try to shut off most apps

**Comment by briskspirit** [comment]
Shut off ALL apps (Enabled tab is empty) - same error persists. So it is core error.

**Comment by MorrisJobke** [comment]
I just tested with the tar ball from owncloud.org and I can't reproduce the issue

**Comment by briskspirit** [comment]
Get this error after deb upgrade from 8.1.3

**Comment by briskspirit** [comment]
![1](https://cloud.githubusercontent.com/assets/11968822/10634891/4b320724-77fd-11e5-977e-43ee6e255277.png)

And what is this I can't understand:
![2](https://cloud.githubusercontent.com/assets/11968822/10634899/5cd2f632-77fd-11e5-8da0-18819381ec29.png)

**Comment by LukasReschke** [comment]
Yeah. We neither can understand this error message. Sorry. Can you post that in English?

**Comment by briskspirit** [comment]
Error when tried to download resource (But HTTP 200 and opens in browser...)

This what in scan.php:
event: user
data: "briskspirit"

event: done
data: 0

event: __internal__
data: "close"

**Comment by briskspirit** [comment]
And what about unsafe-eval error? It is on every page and with shut off all apps, so it is core problem with some js inside html? (As I understood from http://stackoverflow.com/questions/8502307/chrome-18-how-to-allow-inline-scripting-with-a-content-security-policy)

**Comment by LukasReschke** [comment]
Sorry. We can't help you. Again. Your browser is throwing some random error in https://github.com/owncloud/core/issues/19926#issuecomment-149857532 in Russian that we can't understand. 

Please please configure your system to use the English language. We can't help you otherwise at all.

**Comment by briskspirit** [comment]
As I said it is "Error to load resource", no more info.

**Comment by briskspirit** [comment]
Got problem root!
Disabled asset.pipeline and all "eval" errors are gone! And this fixed music app problem and all minor problems. So asset.pipeline needs to be disabled or fixed to operate properly.
