### ISSUE TITLE
shipped.json has wrong version in 8.2 and master

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#19933]
https://github.com/owncloud/core/blob/master/core/shipped.json#L2

Should either get rid of the version or add it to the release todo list

@DeepDiver1975  your call

**Comment by PVince81** [comment]
same here: indie.json is still on 7.0: https://github.com/owncloud/core/blob/stable8.2/indie.json#L31

**Comment by PVince81** [comment]
If we had a build script with a $VERSION$ variable this could be substituted automatically at build time :see_no_evil:

**Comment by nickvergessen** [comment]
Then git won't have a good value...
