### ISSUE TITLE
Move core apps to separate repositories

### ISSUE THREAD

**Issue by Henni** [owncloud/core#19938]
The goal is to extract all apps currently residing in the apps folder in the core repository.
Instead every app should have it's own repository and should be included into the core repo with git submodules.

This modularization would reduce the time needed for testing, because every app could run its own tests in parallel to other apps. Furthermore issues and PRs could be created in the matching repo instead of gathering all of them in core.

**Comment by DeepDiver1975** [comment]
https://github.com/owncloud/core/issues/4774

**Comment by karlitschek** [comment]
I don't like this idea. This makes learning, developing and getting into ownCloud more complicated then necessary. It also makes tracking and reporting of bugs and features a mess. Executing tests only for core or only for a specific app should be done somehow else.

**Comment by Henni** [comment]
@karlitschek I don't agree with your points. I think getting into developing for ownCloud is more complicated if all the code, all the issues and PRs are in one single repository.
Splitting the core repository up by extracting the apps would create some kind of structure.

BTW: I created this issue because the discussion came up on IRC and it looks like the dav app will be set up this way.

**Comment by karlitschek** [comment]
Thanks for your input but simple is better here.
The dav app should be in core because of licensing and the reasons I stated.
Splitting up everything in a hundred pieces doesn't make anything better. There are a lot of examples in ownCloud and outside ownCloud that demonstrate this.

**Comment by Henni** [comment]
@karlitschek ok. I guess you have more experience with this than me.

**Comment by DeepDiver1975** [comment]
> The dav app should be in core because of licensing and the reasons I stated.

Bääh .. this bloody licensing issue ... I'd really love to find a solution one day.



> I created this issue because the discussion came up on IRC and it looks like the dav app will be set up this way.

@karlitschek just to put some light on the background respectively what we did talk about on irc:

The dav code requires a lot additional testing effort - which of course needs to be automated.
I simply cannot put more of my time into more test cases and tools on jenkins and make sure to maintain them all.

Out of this my idea was born to use travis for this purpose and let it work on the dav code in its own repo. I still like to discuss this approach.

**Comment by karlitschek** [comment]
It's not only the license. 
I strongly believe that splitting up a software in tiny repositories is the wrong direction. I can give you several real world examples where this went wrong. Actually we should go the opposite direction. Move more magic out of the packaging script and handle stuff correctly in the repositories. Something to discuss.
I understand the testing issue. But there must be a way to execute only parts of the tests even if more tests exist in the same repository.

**Comment by Henni** [comment]
@karlitschek just out of interest: could you give me an example where this went wrong?

**Comment by DeepDiver1975** [comment]
> I understand the testing issue. But there must be a way to execute only parts of the tests even if more tests exist in the same repository.

this option exists - as we already do now:
each pull request on core has not 14 individual test suites of various kinds - once we have smashbox integrated this number will grow further.
The more we add the longer we have to wait until a pr is in a mergable state and the more we have to monitor on jenkins to get this thing going - this for sure eats more time on jenkins compared to travis

**Comment by karlitschek** [comment]
@Henni This is a complex topic and difficult to summarize in just few sentences here because it involves community management, development processes, psychology and more topics.
But one example is KDE. A lot of people consider the decision7 years ago to split up KDE into a ton of sub git repositories as one of the main reasons why the community contributions dropped over the last few years. There are some blog posts and talks online that cover this topic in a lot of detail. I share this opinion even although I supported the decision at the time. This just moves too many things out of the spotlight for too many developers and basically kills the community feeling be having too many small islands. We see the same in ownCloud. We moved a lot of apps out of the core repository into separate repos in the past. A lot of them became significantly less active now. Some are even graveyards. 
We can't do this anymore. Actually we should think really hard about ways to revert it.

**Comment by DeepDiver1975** [comment]
While II can unterstand the community splitting effect - I See no way to provide a proper CI system. Core is already to big and we need to move more things out - e.g. the external fileeystems AS discussed and planned for 9.0

**Comment by DeepDiver1975** [comment]
Lets try to find the time to talk about this when meet next time.

**Comment by Henni** [comment]
@karlitschek Thanks for the example.
