### ISSUE TITLE
Inconsistent use of different languages

### ISSUE THREAD

**Issue by hitam4450** [owncloud/core#19946]
After a fresh installation of OC 8.2 and with the default language German I receive the following after opening the administration menue:

> Sicherheits- & Einrichtungswarnungen
>
> Transactional file locking is using the database as locking backend, for best performance it's advised to configure a memcache for locking. See the documentation ↗ for more information.
>  Es wurde kein PHP Memory Cache konfiguriert. Konfiguriere zur Erhöhung der Leistungsfähigkeit, soweit verfügbar, einen Memory Cache. Weitere Informationen finden Sie in unserer Dokumentation.
>
> Bitte überprüfe noch einmal die Installationsanleitungen ↗ und kontrolliere das Log auf mögliche Fehler oder Warnungen.

regards, hitam4450

**Comment by karlitschek** [comment]
Hmm. Seems to be some problem with the german translation

**Comment by DeepDiver1975** [comment]
Pretty simple - not all strings had been translated by the time of release.
To fix this a PR against stable8.2 is required.

**Comment by Bullnados** [comment]
This string is one of the untranslated ones

**Comment by PVince81** [comment]
I think we're close enough now (RC1) :smile:

**Comment by nickvergessen** [comment]
@vgezer did you use a script to backport language changes? the diff is rather huge, and I'm not sure whether that is doable by hand (500+ files changed between stable8.2 and master)

**Comment by nickvergessen** [comment]
Script found at https://github.com/vgezer/oc_l10n_patch_applier

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/issues/20338

**Comment by MorrisJobke** [comment]
Fixed and merged
