### ISSUE TITLE
Drop core's external ftp implementation in favor of icewind1991/files_external_ftp

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#19941]
@icewind1991 did come up with an external storage implementation for ftp based on the new flysystem based concept: https://github.com/icewind1991/files_external_ftp

Proposed steps:
- move https://github.com/icewind1991/files_external_ftp to the owncloud orga
- adjust packaging scripts to pull in the new repo
- drop the old code https://github.com/owncloud/core/blob/master/apps/files_external/lib/ftp.php

@karlitschek @cmonteroluque this would the first step to start working on external file system based on flysystem as discussed for 9.0 - objections? agreement?

I suggest to do this soonish in order to get field experience before addressing other implementations like dropbox etc

**Comment by karlitschek** [comment]
I think this makes sense except one thing. I really think we should keep the new files_external_ftp app in core/apps. Exactly as we have today. All the stuff that is in core should stay in core. All the connectors that are in other repos at the moment can stay there. Otherwise the danger is that all this apps become unmaintained graveyards.

**Comment by DeepDiver1975** [comment]
But then we loose the power of automated testing - on travis the new implementation has a test setup and coverage we can never build (that easy) on jenkins:
https://travis-ci.org/icewind1991/files_external_ftp

The implementation is tested on 5 different php versions against 3 different ftp servers.

Just to visualize it:
![bildschirmfoto von 2015-10-21 17-10-52](https://cloud.githubusercontent.com/assets/1005065/10640813/b638290e-7816-11e5-89ae-1cf37a4eb9a8.png)

**Comment by DeepDiver1975** [comment]
Just to summarize the picture with respect to dav

Besides the usual phpunit test suite this holds an additional test suite for litmus to ensure WebDAV compliance. 

![bildschirmfoto von 2015-10-21 17-25-15](https://cloud.githubusercontent.com/assets/1005065/10641266/c3a39478-7818-11e5-8b8d-dd67a754f20b.png)

Additional tools for caldav and carddav testing will folllow - as an example Apples calendar tester

**Comment by DeepDiver1975** [comment]
@karlitschek @cmonteroluque since we seem to have a solution regarding travis testing core apps - see https://github.com/owncloud/core/pull/20089 - I guess we can move on moving @icewind1991's ftp app into core

@karlitschek @cmonteroluque @icewind1991 objections? THX

**Comment by icewind1991** [comment]
That still doesn't give the flexibility of the testing matrix for different ftp servers

**Comment by DeepDiver1975** [comment]
> That still doesn't give the flexibility of the testing matrix for different ftp servers

it should .. what are your concerns?

**Comment by icewind1991** [comment]
Hmm, looking at it some more it might be possible but I think it would become a mess if we try to combine apps with various requirements in a single travis config.

The ftp app for example needs to configure the ftpd and create the user.

Also I believe having separate repos for apps will be easier for maintenance than having them in the core repo.

**Comment by DeepDiver1975** [comment]
> Hmm, looking at it some more

I did the same - this might cause issues: https://github.com/icewind1991/files_external_ftp/blob/master/.travis.yml#L20-27 since I'm using travis' docker infrastructure which does not allow sudo

**Comment by DeepDiver1975** [comment]
> I think it would become a mess if we try to combine apps with various requirements in a single travis config.

as long as we move all specific steps to bash scripts it should be possible

**Comment by PVince81** [comment]
Any update ? Especially considering https://github.com/owncloud/core/issues/9630#issuecomment-169729922

**Comment by cmonteroluque** [comment]
@DeepDiver1975 ping

**Comment by DeepDiver1975** [comment]
As soon as there is time left I can have a look

**Comment by cmonteroluque** [comment]
@DeepDiver1975 thanks

**Comment by cmonteroluque** [comment]
changed severity to match https://github.com/owncloud/core/issues/9630

**Comment by DeepDiver1975** [comment]
I don't see this happening in the scope of 9.0 - there is simply no time to work out a proper ci concept.

In order to fix #9630 I suggest to test https://github.com/icewind1991/files_external_ftp.git with 9.0 and ship this to customers who need this.

**Comment by cmonteroluque** [comment]
ok thanks

**Comment by PVince81** [comment]
We're past feature freeze, moving to 9.2 ? @DeepDiver1975

**Comment by DeepDiver1975** [comment]
yes - the pr is already on 9.2

**Comment by DeepDiver1975** [comment]
Case closed
