### ISSUE TITLE
Syncing of files does not work

### ISSUE THREAD

**Issue by marbetschar** [owncloud/core#19947]
See attached image; the following scenarios are failing:

1. Symbolic links from inside an XYZ.app file
2. Hidden files
3. Files with a slash ("/") in filename

Any ideas?

![owncloud](https://cloud.githubusercontent.com/assets/392542/10640534/5f6b3086-7815-11e5-95f1-5f53d2bef372.png)

**Comment by nickvergessen** [comment]
Please use the [issue template](https://github.com/owncloud/core/blob/master/CONTRIBUTING.md), make sure that your screenshots are in a readable size and make sure whether your issue belongs in the client repo instead

**Comment by marbetschar** [comment]
Ok - thanks! I'll reopen the issue in the client repo.
