### ISSUE TITLE
Can't Login via Web UI

### ISSUE THREAD

**Issue by McKay1717** [owncloud/core#19948]
### Steps to reproduce
Try to login to https://cloud.mckay1717.eu/
### Expected behaviour
Login correctly and display file app

### Actual behaviour
Login request does'nt work and fail attempt was'nt display
### Server configuration
**Operating system**:
Ubuntu 15.04

**Web server:**
nginx/1.6.2 (Ubuntu)

**Database:**
5.6.25

**PHP version:**
5.6.4

**ownCloud version:** 
9.0

**Updated from an older ownCloud or fresh install:**
Update from 3.2

**List of activated apps:**
Enabled:
- activity: 2.2.0
- files: 1.3.0
- files_locking:
- files_pdfviewer: 0.7
- files_sharing: 0.8.1
- files_texteditor: 2.0
- files_trashbin: 0.8.0
- files_versions: 1.2.0
- files_videoviewer: 0.1.3
- firstrunwizard: 1.1
- provisioning_api: 0.4.0
- templateeditor: 0.1
Disabled:
- dav
- encryption
- external
- files_external
- gallery
- notifications
- updater
- user_external
- user_ldap    

**The content of config/config.php:**

{
    "system": {
        "instanceid": "ocle25k4x281",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.mckay1717.eu"
        ],
        "datadirectory": "\/home\/data",
        "overwrite.cli.url": "https:\/\/cloud.mckay1717.eu\/",
        "dbtype": "mysql",
        "version": "9.0.0.0",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Paris",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "cloud",
        "mail_domain": "mckay1717.eu",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "maintenance": false,
        "asset-pipeline.enabled": true,
        "theme": "",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        },
        "loglevel": 0,
        "log_type": "owncloud"
    }
}

**Are you using external storage, if yes which one:** 
None

**Are you using encryption:** 
No

**Are you using an external user-backend, if yes which one:**
None

### Client configuration
**Browser:**
Iceweasel 38.3.0
Firefox 41

**Operating system:**
Debian 8.2
Windows 7

**Comment by LukasReschke** [comment]
Can you please fill out the issue template? THX.

https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by McKay1717** [comment]
Sorry, it's done

**Comment by LukasReschke** [comment]
Anything in the ownCloud or apache log?

**Comment by McKay1717** [comment]
Nop nginx error log is empty and the owncloud log (Login failed attemp is'nt display){"reqId":"DpYNPKpIwu46HBP9wg9l","remoteAddr":"212.47.250.41","app":"files_locking","message":"INFO: Incrementing lock type 2 count for \/home\/data\/McKay1717\/files\/Photos\/Num\u00e9risations\/IMG_20151021_105837675.jpg","level":0,"time":"2015-10-21T19:44:06+02:00","method":"PUT","url":"\/remote.php\/webdav\/Photos\/Num%C3%A9risations\/IMG_20151021_105837675.jpg"}
{"reqId":"DpYNPKpIwu46HBP9wg9l","remoteAddr":"212.47.250.41","app":"files_locking","message":"INFO: Releasing locks on \/home\/data\/McKay1717\/files\/Photos\/Num\u00e9risations\/IMG_20151021_105837675.jpg","level":0,"time":"2015-10-21T19:44:06+02:00","method":"PUT","url":"\/remote.php\/webdav\/Photos\/Num%C3%A9risations\/IMG_20151021_105837675.jpg"}
{"reqId":"DpYNPKpIwu46HBP9wg9l","remoteAddr":"212.47.250.41","app":"files_locking","message":"INFO: Released lock handle Resource id #46 on \/home\/data\/McKay1717\/files\/Photos\/Num\u00e9risations\/IMG_20151021_105837675.jpg","level":0,"time":"2015-10-21T19:44:06+02:00","method":"PUT","url":"\/remote.php\/webdav\/Photos\/Num%C3%A9risations\/IMG_20151021_105837675.jpg"}
{"reqId":"DpYNPKpIwu46HBP9wg9l","remoteAddr":"212.47.250.41","app":"files_locking","message":"FREE: Released locks on \/home\/data\/McKay1717\/files\/Photos\/Num\u00e9risations\/IMG_20151021_105837675.jpg","level":0,"time":"2015-10-21T19:44:06+02:00","method":"PUT","url":"\/remote.php\/webdav\/Photos\/Num%C3%A9risations\/IMG_20151021_105837675.jpg"}

**Comment by McKay1717** [comment]
Greetings !
I continued my investigation and I discovered a thing !
The first time where a browser landing on the login page , login work .
But the other time a security warning is displayed in browser console : 
Content security policy: The settings of the page have prevented the loading of a resource (« script-src https://cloud.mckay1717.eu 'unsafe-eval' »).

Thank's for your help

**Comment by McKay1717** [comment]
I have found a problem with session store in my php fpm server. So the problem is solve.
