### ISSUE TITLE
ownCloud Windows Installer of Some Kind

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#1995]
I would love to see a drop dead simple Windows Installer, perhaps even a Windows Web Platform Installer, for easy setup and installation.

How hard would it be to create a Windows / IIS / SQL Server Express Web Platform Installer entry?  I see the list of steps below, but have no idea how hard this is.

http://www.iis.net/learn/develop/windows-web-application-gallery/package-an-application-for-the-windows-web-application-gallery
http://www.microsoft.com/WEB/gallery/

**Comment by LukasReschke** [comment]
This is possible using https://bitnami.com/stack/owncloud – voting for closing.

**Comment by karlitschek** [comment]
Agreed. We should link to the friendly people at bitnami and let them do the heavy lifting :-)
