### ISSUE TITLE
changing expiration date of shared link breaks password

### ISSUE THREAD

**Issue by autrui** [owncloud/core#19950]
Hi.

Since 8.2.0 setting/changing the expiration date for shared links breaks the password for these links, so you can't access them anymore with the correct password.

Expected behaviour: setting/changing the expiration date of a shared link sets/changes it and that's it.

Actual behaviour: changing or setting the expiration date of a shared link breaks the password, i.e. you cannot access the shared link with the correct password because it always reports "wrong password" (even though it's correct).

Strangely, there's one way: when I set a **default, _not enforced_ expiration date for _shared links_ as an admin for _all_ users**. Then when I share a link I **do not touch** the previously set default expiration date (= not change nor disable it). Then it works.
 
But that's hardly a good longterm solution to this problem.

-----------
Operating system: CentOS 6.7
Web server: Apache 2.2.15
PHP version: 5.6.12
ownCloud version: 8.2
Enabled apps:  Activity, Gallery, Mail Template Editor, PDF Viewer, Share Files, Updater, Video Viewer
Are you using external storage, if yes which one: no
Are you using encryption: no
Are you using an external user-backend: no
Browser: Firefox 41.0.x, Safari 9

logs show nothing related to this problem or the time it happened.

**Comment by DeepDiver1975** [comment]
@rperezb this is exactly the case I was asking you to test before the release and this was working - right?

Please reevaluate - THX

**Comment by rperezb** [comment]
Yes, you are right, I have been able to reproduce it following @autrui steps:

1.- Share a folder by link
2.- Set up a password
3.- Access to the link the password is requested -> works
4.- Set up an expiration date
5.- Access to the link, the password is requested -> not works

SERVER:
ownCloud 8.2.0 (stable) 

I have not seen either any logs

cc @davitol fyi

**Comment by DeepDiver1975** [comment]
THX for verifying this once more - may I ask why this was not detected before the release? :imp: 

Please update the test plan - THX

**Comment by davitol** [comment]
@DeepDiver1975 My fault :skull: , I tested before the release and "this was working for me". And I tried in several ways. Maybe I skipped a step. I'll test again.

**Comment by DeepDiver1975** [comment]
I'll debug this and fix it ....

**Comment by davitol** [comment]
https://github.com/owncloud/QA/issues/7#issuecomment-146101268

**Comment by davitol** [comment]
Retested with ownCloud Enterprise Edition 8.2 beta1 (daily) Build:2015-10-06T03:08:41+00:00 0577eed14e5c4be25afd541c71c2b75b4ad5f9c7 and https://github.com/owncloud/core/issues/19950#issuecomment-150162521 steps and fails :-1:
