### ISSUE TITLE
Streaming API?

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/core#19958]
As wished in https://github.com/owncloud/android/issues/592, is there a streaming API that can be used from within the android app? 
My idea would be to pass the generated url to an app that can stream, e.g. vlc?

I have searched, but could not find a valid issue or answer to my question.

Thank you!

**Comment by DeepDiver1975** [comment]
Isn't video streaming to be implemented using http range requests? 
In this case getting a file via webdav should work since webdav supports range requests.

Or what would the required protocol to  support? THX

**Comment by RealRancor** [comment]
> Isn't video streaming to be implemented using http range requests?
> In this case getting a file via webdav should work since webdav supports range requests.

Exactly this was achieved within the video player app a few days ago: https://github.com/owncloud/apps/pull/2111 by using the webdav endpoint.

**Comment by tobiasKaminsky** [comment]
:)
I think this question is a result of an old owncloud version, wrong understanding of streaming and a wrong android app.
I have now tried https://test:test@demo.owncloud.org/remote.php/webdav/Demo Movie OGG - Big Buck Bunny Trailer.ogg to open it in vlc on android and it works.
So this would be the way to go in the android app:
- Generate the url from its path on server and file name
- Send url via intent to (known) network streaming capable apps (like vlc)
- (maybe with a warning that it only depends on the app and not on the server if it fails)

Since when is the streaming working in oc server?

Thank you!

**Comment by DeepDiver1975** [comment]
> Since when is the streaming working in oc server?

Since forever - because it relies obviously on http range request which are implemented in sabredav (the server side webdav library we use) :wink: 

Just send all your :beers: and :pizza: to @evert for building SabreDAV

**Comment by evert** [comment]
:dancers:

**Comment by LukasReschke** [comment]
So I suppose we can *erm* close this?

**Comment by tobiasKaminsky** [comment]
Yes, thank you all for helping and clarifying this.
Then I can built it sooner or later into the android app. :)
And special thanks to @evert ;)

**Comment by tobiasKaminsky** [comment]
A consecutive question, if you do not mind: 
I am sending the webdav url to e.g. VLC like this: https://192.168.0.100/owncloud/remote.php/webdav/2/1.ogg
But this does not work as a basic authentication is missing. So I could use "https://tobi:pass@192.168.0.100".  But this would expose the password to potential other viewing user. (At least VLC shows the complete url while buffering).
So, as I do not know the internal: Is it possible to use a session key or something similar instead to prevent exposing the password?

Thank you!
