### ISSUE TITLE
[Suggestion] a little documentation change in the repo page on download.owncloud.org

### ISSUE THREAD

**Issue by ervee** [owncloud/core#19961]
Hi,

I propose a little documentation change here: https://download.owncloud.org/download/repositories/8.2/owncloud/ (click Debian, and possibly elsewhere).
My suggestion: Make users aware of installing package apt-transport-https first before switching the repo to a https repo. If not, you'll get ugly errors on the first apt-get update. And when you then want to install apt-transport-https you get some more! You then have to comment out the https repo, apt-get update and the install apt-transport-https before giving it another try.

**Comment by LukasReschke** [comment]
@jnweiger

**Comment by jnweiger** [comment]
@LukasReschke what is the reason for recommending https repos? The gpg key is available from download.owncloud.org via https.

**Comment by LukasReschke** [comment]
From my PoV it's fine to just keep the HTTP ones as before. But the GPG key should be referenced using HTTPS :)

**Comment by jnweiger** [comment]
okay. i'll have to split the config then to allow different schemes.

**Comment by jnweiger** [comment]
hope that helps at all with the issue here.

**Comment by PVince81** [comment]
Any update ?

**Comment by ervee** [comment]
@jnweiger, sorry, missed your comment. The page in post 1 now uses a http deb link so the problem is gone.
