### ISSUE TITLE
owncloud 8.2 repository not reflecting 'CentOS_CentOS-6' from opensuse community repository

### ISSUE THREAD

**Issue by FlyinFistOfJuda** [owncloud/core#19966]
Hello,

i'm on Centos 6.6 with a third party php repository for php5.6 to meet the requirements of owncloud. Up to 8.1.3 i've been following the opensuse repository for centos on path <b>CentOS_CentOS-6</b>, see <code>http://download.opensuse.org/repositories/isv:ownCloud:community/CentOS_CentOS-6/isv:ownCloud:community.repo</code>.

The 8.2 repository at download.owncloud.org does not reflect this path, so i'm stuck with 8.1.3 from the opensuse repository. See <code>https://download.owncloud.org/download/repositories/8.2/</code>

This aside, the other repositories like CentOS_6_PHP56/ demands new packages which cant be found (like rh-php56-php* packages and a httpd24), and would mix up my current setup, so this won't be a solution.

How should I upgrade to the current stable version?

Thanks in advance.

**Comment by MorrisJobke** [comment]
cc @jnweiger

**Comment by TheFiZi** [comment]
Same issue here: https://forum.owncloud.org/viewtopic.php?f=36&t=31065&p=99452

**Comment by jnweiger** [comment]
CentOS_6_PHP56 instructions added to http://download.owncloud.org/download/repositories/8.2/owncloud/CentOS.html

**Comment by FlyinFistOfJuda** [comment]
Thanks, that worked fine following the steps for Centos_6 owncloud-8.2.0-2.1 from instructions.

**Comment by mclindy** [comment]
As of December 5, 2015 9:00am Pacific time, the links to www.softwarecollections.org don't work. The directories from the links are empty.
