### ISSUE TITLE
Can't connect external SMB storage without specifying a SHARE

### ISSUE THREAD

**Issue by jrh7675** [owncloud/core#19963]
### Steps to reproduce
1. Attempt to add an External SMB/CIFS share NOT specifying a share name (only specifying a server to connect to) It does not matter whether it is a global or personal share and it does not matter whether it is username/password or session - SHARE is a required field no matter what.
### Expected behaviour

You used to be able to add just a SERVER (not specifying a SHARE) then upon connecting to the shared folder via ownCloud it should show all the shares the server has and from there you could drill inside them. This works in 8.0.5 and I think it just broke in 8.2 but I never had much luck with any 8.1.x version for other reasons.

Maybe this was never intended but it sure was nice!
### Actual behaviour

You cannot add an External Storage without specifying a share, it is a required field.
### Server configuration

Ubuntu 14.04

Apache2

MySQL

**PHP version:**

ownCloud 8.2

Updated 

**List of activated apps:**
Enabled:
- activity: 2.1.3
- files: 1.2.0
- files_external: 0.3.0
- files_locking:
- files_pdfviewer: 0.7
- files_sharing: 0.7.0
- files_texteditor: 2.0
- files_trashbin: 0.7.0
- files_versions: 1.1.0
- files_videoviewer: 0.1.3
- firstrunwizard: 1.1
- gallery: 14.2.0
- provisioning_api: 0.3.0
- templateeditor: 0.1
- user_ldap: 0.7.0
  Disabled:
- encryption
- external
- galleryplus
- notifications
- updater
- user_external

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'ocuufuhnt24a',
  'trusted_domains' =>
  array (
    0 => '192.168.1.199',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://192.168.1.199/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.2.0.12',
  'dbname' => 'dbowncloud_dev',
  'dbhost' => 'mine.hellriegel.com.',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'logtimezone' => 'UTC',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'loglevel' => 1,
  'memcache.local' => '\OC\Memcache\APCu',
  'theme' => '',
  'maintenance' => false,
  'trashbin_retention_obligation' => 'auto',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP
#### LDAP configuration (delete this part if not used)

+-------------------------------+--------------------------------------------------+
| Configuration                 |                                                  |
+-------------------------------+--------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                |
| hasPagedResultSupport         |                                                  |
| homeFolderNamingRule          |                                                  |
| lastJpegPhotoLookup           | 0                                                |
| ldapAgentName                 | CN=Own Cloud,OU=People,DC=hellriegel,DC=com      |
| ldapAgentPassword             | **\*                                              |
| ldapAttributesForGroupSearch  |                                                  |
| ldapAttributesForUserSearch   |                                                  |
| ldapBackupHost                |                                                  |
| ldapBackupPort                |                                                  |
| ldapBase                      | DC=hellriegel,DC=com                             |
| ldapBaseGroups                | DC=hellriegel,DC=com                             |
| ldapBaseUsers                 | DC=hellriegel,DC=com                             |
| ldapCacheTTL                  | 600                                              |
| ldapConfigurationActive       | 1                                                |
| ldapEmailAttribute            |                                                  |
| ldapExperiencedAdmin          | 0                                                |
| ldapExpertUUIDGroupAttr       |                                                  |
| ldapExpertUUIDUserAttr        |                                                  |
| ldapExpertUsernameAttr        |                                                  |
| ldapGroupDisplayName          | cn                                               |
| ldapGroupFilter               | (&(|(objectclass=group)))                        |
| ldapGroupFilterGroups         |                                                  |
| ldapGroupFilterMode           | 0                                                |
| ldapGroupFilterObjectclass    | group                                            |
| ldapGroupMemberAssocAttr      | member                                           |
| ldapHost                      | srvdc01.hellriegel.com.                          |
| ldapIgnoreNamingRules         |                                                  |
| ldapLoginFilter               | (&(&(|(objectclass=user)))(samaccountname=%uid)) |
| ldapLoginFilterAttributes     |                                                  |
| ldapLoginFilterEmail          | 0                                                |
| ldapLoginFilterMode           | 0                                                |
| ldapLoginFilterUsername       | 1                                                |
| ldapNestedGroups              | 0                                                |
| ldapOverrideMainServer        |                                                  |
| ldapPagingSize                | 500                                              |
| ldapPort                      | 389                                              |
| ldapQuotaAttribute            |                                                  |
| ldapQuotaDefault              |                                                  |
| ldapTLS                       | 0                                                |
| ldapUserDisplayName           | displayName                                      |
| ldapUserFilter                | (&(|(objectclass=user)))                         |
| ldapUserFilterGroups          |                                                  |
| ldapUserFilterMode            | 0                                                |
| ldapUserFilterObjectclass     | user                                             |
| ldapUuidGroupAttribute        | auto                                             |
| ldapUuidUserAttribute         | auto                                             |
| turnOffCertCheck              | 0                                                |
| useMemberOfToDetectMembership | 1                                                |
+-------------------------------+--------------------------------------------------+
### Client configuration

**Browser:**
Chrome

**Operating system:**
Windows

**Comment by Xenopathic** [comment]
This worked in 8.0? That's strange, there was never any code to support it. Specifying the share is, understandably, required, but being able to select the share from a dropdown could be quite a nice feature (cc @jmaciasportela)

**Comment by jrh7675** [comment]
I really don't think it is understandable to require the share since it isn't really required (think of the Network view in Windows Explorer) and previously worked in a manner that was more desirable. What's the big deal with making it not required, the way it was? I've got a lot of external hard drives all shared out on my computer - this share thing is the difference between having to add one external storage folder for the computer versus many (one for each share/external drive on the computer). 

I do agree a drop down might be nice though, so long as leaving it blank was also an option.

BTW ... There is another bug in SMB storage since version 8.1 ... I'm getting ready to file it, don't have all the info yet but it looks like when you share out your C$ share, the one with Pagefile.sys - ownCloud let's you add it but upon viewing it ownCloud responds with "unknown error". The ownCloud log seems to imply it can't pull file metadata info from the file - Pagefile.sys and that makes sense because even in Windows Explorer not all info displays for that file, presumably because it is open. Anyway I mention this because if the share were simply not required I think there's still a bug preventing it from working - this other bug, and if it were fixed too we'd get back to where we were in 8.0.x - and I could finally upgrade my production system to the latest/greatest.

**Comment by Xenopathic** [comment]
@jrh7675 No, the whole point is that this was never designed to work. And a share is always required, otherwise you aren't actually connecting to a file storage. It is possible to list shares available on a machine, which is what the Network view does, but for actual file storage a share is necessary. If this ever worked before, it was an unintended side effect of the SMB4PHP code, and was likely broken in some subtle ways.

**Comment by PVince81** [comment]
smb4php is old, insecure and unmaintained.

We switched to icewind/smb which is based on php5-libsmbclient.

However to be able to provide this feature it would need a lot of extra code because these libraries doesn't expose the shares like regular folders, so a share name is always required.

Considering that this is a rather special use case and not much in demand, I'm going to close this, unless anyone is willing to invest the time to submit a PR to add this functionality in a clean manner. Note that this is not a trivial fix so might need a week or more.
