### ISSUE TITLE
CardDAV cookie authentication

### ISSUE THREAD

**Issue by Henni** [owncloud/core#19969]
The webdav backend seems to have problems with cookies in the request header:

The following curl (from command line) works as expected:
```
$ curl testuser:testpasswd@localhost:8080/remote.php/carddav/addressbooks/testuser/contacts/15e3775c-87ae-4fa0-82c1-fa7fd845a4d4.vcf 
BEGIN:VCARD
VERSION:3.0
PRODID:-//ownCloud//NONSGML Contacts 0.5.0.0//EN
N:Leppelsack;Hendrik;;;
UID:15e3775c-87ae-4fa0-82c1-fa7fd845a4d4
REV:2015-10-21T19:09:28+00:00
FN:
END:VCARD
```

while the same curl with the session cookies copied from the browser returns a "not found"-exception:
```
$ curl --cookie "oc_sessionPassphrase=cwTfwcYDgpy80KkBgPMW73JTcLJWF5Lqs7OGEIn6JtBlmC6v26bvAcRpnCPnbvYVJPjh07xlSEZiTa4XWGv9Pyvh0uhUaF8TVI2z4o2kw1ZTbg%2FiVPRbwqehZCKzidDk; ocbjoy4fintd=8uso7q3ugst8md4572q2chklo3" testuser:testpasswd@localhost:8080/remote.php/carddav/addressbooks/testuser/contacts/15e3775c-87ae-4fa0-82c1-fa7fd845a4d4.vcf
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>2.1.7</s:sabredav-version>
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>Card not found</s:message>
</d:error>
```

This happens on owncloud stable8.2.
I can't test it on 9.0 as carddav is currently broken because of the dav changes in core.

cc @DeepDiver1975

**Comment by DeepDiver1975** [comment]
@LukasReschke does this ring any bell? THX

**Comment by LukasReschke** [comment]
This does not affect the WebDAV backend. Please be specific in the error title, this case only affects CardDAV.

**Comment by LukasReschke** [comment]
Ok. I know why it's behaving this. It's a little bit strange since core is behaving like this since 8.0 but I will see how I can workaround this problem.

**Comment by DeepDiver1975** [comment]
> This does not affect the WebDAV backend. Please be specific in the error title, this case only affects CardDAV. WebDAV would have given me a shock ;)

but the authentication mechanisms are identical on webdav and carddav so there is a risk of impacting this the webdav interface as well

**Comment by LukasReschke** [comment]
> but the authentication mechanisms are identical on webdav and carddav so there is a risk of impacting this the webdav interface as well

Well, but this bug does only affect CardDAV as the code path is not used by the WebDAV plugin in that way :)

**Comment by LukasReschke** [comment]
Though arguably this was more a bug that the files plugin does not use it :speak_no_evil:
