### ISSUE TITLE
Core application description translation

### ISSUE THREAD

**Issue by Bullnados** [owncloud/core#19968]
Don't know exactly it's correct that application description is always English?
If not would it be possible to add the core application description to Transifex?

Hope the issue doesn't exist.

**Comment by DeepDiver1975** [comment]
There is an open issue already somewhere in here -> closing

**Comment by DeepDiver1975** [comment]
To answer the question: it is possible from a technical point of view - but the effort is rather high and the value is very little - the description is only read by the admin. THX
