### ISSUE TITLE
[master] JS error in share side bar

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#19979]
```js
sharedialoglinkshareview.js?v=c397349262c23adfcb9d3218b165d8ce:154 
Uncaught TypeError: this.focus is not a function

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/20046

**Comment by MorrisJobke** [comment]
Moving this to 9.0-current because of @PVince81 s comment:

> Note: this is 9.0 only because I recently moved the event registration to the top of the class, so this isn't the current jquery element any more but the actual view class.

**Comment by PVince81** [comment]
I just double checked and this also happens on 8.2.1 because the code in question was backported to 8.2.1 too... Moving milestone again.

**Comment by MorrisJobke** [comment]
@PVince81 I added the backport label to the PR -> moving this to 9.0 milestone and then I will set the brown labels once it is backported.;)
