### ISSUE TITLE
[8.2] Missing icons in appdrawer

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#19984]
Just made a fresh install if 8.2. I enabled the apps: contacts, mail, calendar, and documents. The problem is that the icons are missing in the appdraver.

![image](https://cloud.githubusercontent.com/assets/4511254/10670480/fcbf59e0-78e5-11e5-9609-0f1182a85c75.png)

What could cause this issue? They are not missing on my reguar installation.

I tried to reinstall the apps deactivating them and remove them from the apps dir in the backend, and then activated them again for a fresh install. Didn't work.

**config.php**
```
<?php
$CONFIG = array (
  'instanceid' => 'oc5wn9phwym0',
  'passwordsalt' => 'XXXXXXXXXX',
  'secret' => 'XXXXXXXXXXX',
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.2.0.12',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'ocadmin',
  'dbpassword' => 'XXXXXXXXXX',
  'logtimezone' => 'UTC',
  'installed' => true,
  'appstore.experimental.enabled' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpauth' => 1,
  'mail_smtpport' => '465',
  'mail_smtphost' => 'smtp.gmail.com',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_from_address' => 'XXXXXXXX',
  'mail_domain' => 'gmail.com',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpname' => 'XXXXXXXXXX',
  'mail_smtppassword' => 'XXXXXX',
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
  ),
  'trusted_domains' => 
  array (
    0 => '192.168.1.112',
  ),
  'overwrite.cli.url' => 'http://192.168.1.112/owncloud',
  'maintenance' => false,
);
```

**Comment by enoch85** [comment]
Turns out they are working over HTTPS but not HTTP. Would still want to know what could cause this. Please.

**Comment by LukasReschke** [comment]
Can you check in the browser debug tools where those images are pointing to? THX.

**Comment by enoch85** [comment]
@LukasReschke Thanks for awnswering. Problem is, I can't find the specific line that concerns the svgs in appdrawer. Would be very appriciated it you could download the VM and give it a try: https://en0ch.se/index.php/s/MUl79ovm7Ifo4kG

**Comment by enoch85** [comment]
Found it:
![image](https://cloud.githubusercontent.com/assets/4511254/10679638/39903fd6-791a-11e5-9986-f4302972d672.png)

![image](https://cloud.githubusercontent.com/assets/4511254/10679657/487f94a6-791a-11e5-9c36-6d9d988f442e.png)

![image](https://cloud.githubusercontent.com/assets/4511254/10679662/56bbee0c-791a-11e5-8468-0fd028a7a0cd.png)

**Comment by enoch85** [comment]
Ping @LukasReschke :)

**Comment by PVince81** [comment]
Did you enable asset pipeline ? Maybe try disabling it, just in case.

**Comment by enoch85** [comment]
@Pvince81 what is assets pipline?

**Comment by PVince81** [comment]
Sorry, I should have looked at your config.php. You don't have it enabled.
It's an optimization that bundles many JS files together within a single call to avoid many network requests. Some people reported that when disabling asset pipeline their 404 issues disappeared.

**Comment by enoch85** [comment]
@PVince81 Aah, you mean  'appstore.experimental.enabled' => true,

**Comment by PVince81** [comment]
Is there a quick way to convert your VMX vm to something Virtualbox can import ? The tool you linked against is a windows program but I'm running Linux. Thanks.

**Comment by enoch85** [comment]
Sorry @PVince81, no "easy fix". Like I mentioned in my setup guide, you have to create a new virtual machine in VirtualBox and use existing .vmdk. That's as easy as it gets. https://www.en0ch.se/complete-install-instructions-owncloud/ Please report back to me if you notice any issues, thanks! :)

Regarding the missing icons, still an issue...

**Comment by PVince81** [comment]
"still an issue" as in "tried with 8.2.1RC1" ? :wink:

**Comment by enoch85** [comment]
@PVince81 You're right. Haven't tried that one yet. :)

**Comment by PVince81** [comment]
Works for me with HTTPS:
![enoch-vm](https://cloud.githubusercontent.com/assets/277525/10996737/01c96c20-8488-11e5-8cba-d2269ca18bc7.png)

Ok, seems HTTP is broken too.

**Comment by PVince81** [comment]
- HTTP:
    - For regular apps, the URL points to "/owncloud/apps/activity/img/activity.svg"
    - For the other ones, it points to "/apps/mail/img/mail.svg" which is wrong.
- HTTPS
   - "/owncloud/apps/activity/img/activity.svg"
   - "/apps/mail/img/mail.svg"
   
Even though the URL looks wrong, it works with HTTPS. Did you set any redirect/rewrite rules and forgot to apply them to HTTP ?

**Comment by PVince81** [comment]
Please double check the env, I don't think this is a bug.

**Comment by enoch85** [comment]
@PVince81 This is a clean install. No changes made to the paths. What should I change?

**Comment by PVince81** [comment]
Not sure. You could check the access logs to find out where they are trying to reach to ?

When looking at /var/www/owncloud I didn't see any folder /var/www/apps, so you probably have rewrite rules somewhere in the apache config?

**Comment by enoch85** [comment]
@PVince81 This is a fresh download of the VM: 

![image](https://cloud.githubusercontent.com/assets/4511254/11000388/c92c2a14-84a1-11e5-9cbb-1c79f7c4f676.png)

I can see mail.svg, and the path is correct afaik. What is wrong here. No redirect rules at all. :unamused:

**Comment by PVince81** [comment]
The URL seemed to point to "/var/www/apps" (outside) not "/var/www/owncloud/apps"

**Comment by enoch85** [comment]
Strange, I'll just wait for 8.2.1 and see if something changes. Thanks for your help @PVince81

**Comment by nopeee535** [comment]
i got the same problem in oc 9.1

systemctl restart apache2.service
restarting apache helped for me

**Comment by shuangyu1937** [comment]
I  got the problem too. in the end , i  changed  my owncloud.conf  like this：
old: Alias /   "/var/www/owncloud/"
new: Alias /owncloud  "/var/www/owncloud/"
