### ISSUE TITLE
Upgrade instructions for openSUSE 13.2 are not correct for the latest release

### ISSUE THREAD

**Issue by StopTrain** [owncloud/core#19985]
https://download.owncloud.org/download/repositories/8.2/owncloud/

On this page, the instructions are incorrect for the repo addition.

This line:

zypper addrepo https://download.owncloud.org/download/repositories/8.2/openSUSE_13.2/ce:8.2.repo

Should read:

zypper addrepo https://download.owncloud.org/download/repositories/8.2/openSUSE_13.2/

zypper will find the .repo file itself and make adjustments on that.

Now, you CAN run this command: zypper install owncloud  
and it will work, but zypper will throw a warning: 
There is an update candidate for 'owncloud', but it is from a different vendor. Use 'zypper install owncloud-8.2.0-2.1.noarch' to install this candidate.

This is a bit of an extra step and if you follow through with this, you'll get this:

Problem: owncloud-8.2.0-2.1.noarch requires owncloud-config-apache = 8.2.0, but this requirement cannot be provided
  uninstallable providers: owncloud-config-apache-8.2.0-2.1.noarch[ownCloud8.2Repo]
 Solution 1: Following actions will be done:
  install owncloud-config-apache-8.2.0-2.1.noarch (with vendor change)
    obs://build.opensuse.org/isv:ownCloud  -->  obs://s2.owncloud.com/ce
  install owncloud-server-8.2.0-2.1.noarch (with vendor change)
    obs://build.opensuse.org/isv:ownCloud  -->  obs://s2.owncloud.com/ce
 Solution 2: do not install owncloud-8.2.0-2.1.noarch
 Solution 3: break owncloud-8.2.0-2.1.noarch by ignoring some of its dependencies

This might be somewhat confusing to users.

The easiest way to do the upgrade is using zypper dup: zypper dup --from 7   (the number is the number of the repo in the zypper lr   list)

This will change vendors for you and grab the existing packages.

Just make sure you follow the REST of the new upgrade documentation for manually running occ upgrade and turning off maintenance mode.

I just completed this process and all is working!

**Comment by LukasReschke** [comment]
@jnweiger

**Comment by PVince81** [comment]
CC @carlaschroder

**Comment by PVince81** [comment]
@owncloud/packaging still an issue ?

**Comment by Kawohl** [comment]
Is resolved afaik `zypper addrepo http://download.owncloud.org/download/repositories/8.2/openSUSE_13.2/ce:8.2.repo`

Close
