### ISSUE TITLE
[8.2.0] logfile parameter needed for syslog to work

### ISSUE THREAD

**Issue by josh4trunks** [owncloud/core#19983]
I noticed this while debugging this issue https://github.com/owncloud/core/issues/19965

If I set the following, logging doesn't happen in syslog or the owncloud.log file
```'log_type' => 'syslog',```

syslog works if I set..
```
'log_type' => 'syslog',
'logfile' => '',
```

####

In my opinion, if an admin sets 'log_type' to 'syslog' 'logfile' is irrelevant and syslog should work. I believe this worked as expected in versions 7-8.1.X but something might have changed in version 8.2.0

**Comment by Tschaul** [comment]
Just tried to reproduce, but failed. It logs to syslog without 'log_file' being set. 

I running ubuntu 15.10 and used pip3/ocdev to setup my dev envirnoment.

Greetings!

**Comment by josh4trunks** [comment]
@Tschaul what version of owncloud are you on? I'll see if i can reproduce right now on 8.2.2

**Comment by josh4trunks** [comment]
I can confirm syslog worked on my system without 'logfile' being set in 8.2.2. I'm going to close this bug =]
