### ISSUE TITLE
Windows & Mac Desktop Clients Unable to Connect to Owncloud Server 

### ISSUE THREAD

**Issue by shinshuri** [owncloud/core#19981]
Hi I have been working with IT Tech Support at our Web Host Provider for the past three days troubleshooting the connection and sync issue with Owncloud Desktop Clients. We use both the Mac and Windows versions in our organization. We have not been able to use either since we upgraded to the most recent version of owncloud 8.2. Below is a description of the issues our Web Host Service Provider found. 

"Please note that WebDAV that is running on Owncloud is provided by Sabre and the warning is because of the compatibility issue with the new version of Owncloud with sabre webadmin. I have found following errors being logged when using WebDav."

=====================================
[Tue Oct 20 16:49:19 2015] [error] [client 208.76.83.142] PHP Fatal error: Call to undefined method OC\\AppFramework\\Http\\Request::getPathInfo() in /home/shinshur/public_html/owncloud/remote.php on line 91
[Tue Oct 20 16:49:29 2015] [error] [client 98.238.178.246] PHP Fatal error: Call to undefined method OC\\AppFramework\\Http\\Request::getPathInfo() in /home/shinshur/public_html/owncloud/remote.php on line 91
[Tue Oct 20 16:49:37 2015] [error] [client 208.76.83.142] PHP Fatal error: Call to undefined method OC\\AppFramework\\Http\\Request::getPathInfo() in /home/shinshur/public_html/owncloud/remote.php on line 91
=====================================
getPathInfo() is a standard PHP library function t get path info of a an object or a file. Seems this function is not properly defined in Owncloud. Can you report this error to Owncloud as they might be able to debug what's the issue with script and what is causing Webdav to fail.
=====================================

See the attached image files for a screenshot of the connection/sync errors.
![owncloud connection error](https://cloud.githubusercontent.com/assets/13647535/10650221/1aee3826-77fd-11e5-92f7-98217189c536.png)
![owncloud sync error](https://cloud.githubusercontent.com/assets/13647535/10650222/1af2611c-77fd-11e5-97bd-5027aad51dc7.png)

Thanks,
Shinshuri

**Comment by RealRancor** [comment]
Hi,

have you followed you the upgrade manual by deleting all files and folder expect /data/ and /config/ and afterwards extracting the 8.2.0 folders into your oC installation dir?

For me it seems not as the mentioned line 91 just exists as an comment:

https://github.com/owncloud/core/blob/v8.2.0/remote.php#L91
