### ISSUE TITLE
Webinstaller still installs owncloud 8.1.3 

### ISSUE THREAD

**Issue by Bullnados** [owncloud/core#19989]
Reproduce:
1. Download web-installer script from: https://owncloud.org/install/#instructions-server
2. Run script
3. Go Adminpanel Version 8.1.3

Expected:
Installation of the latest 8.2 release.

Seems that this version is old: https://download.owncloud.org/download/community/owncloud-latest.zip

**Comment by nickvergessen** [comment]
@jnweiger

**Comment by nickvergessen** [comment]
or is this @cmonteroluque @karlitschek part?

**Comment by Bullnados** [comment]
One question. Why doesn't take te webinstaller the normal download https://download.owncloud.org/community/owncloud-8.2.0.zip link?
And than rename .zip from owncloud-x.x.x.zip zi owncloud-latest.zip?
So u have not to change the installer script every version.

**Comment by Xenopathic** [comment]
This is another `owncloud-latest` symlink issue

**Comment by DeepDiver1975** [comment]
@karlitschek @cmonteroluque FYI - related to the release sripts

**Comment by karlitschek** [comment]
fixed now.
