### ISSUE TITLE
RHEL 6, Owncloud 8.2 installation problem

### ISSUE THREAD

**Issue by yvlitvin** [owncloud/core#19992]
Hello, truing to install Owncloud 8.2 on RHEL 6, follwing by instruction   
https://download.owncloud.org/download/repositories/8.2/owncloud/  RHEL_6_PHP56 
and receiving an error with package dependencies
uname -a
Linux xxx.xxx.xx 2.6.32-573.7.1.el6.x86_64 #1 SMP Thu Sep 10 13:42:16 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux
cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.7 (Santiago)

yum install  owncloud
Loaded plugins: product-id, rhnplugin, subscription-manager
This system is receiving updates from RHN Classic or RHN Satellite.
Setting up Install Process
Resolving Dependencies
--> Running transaction check
---> Package owncloud.noarch 0:8.2.0-2.1 will be installed
--> Processing Dependency: owncloud-config-apache = 8.2.0 for package: owncloud-8.2.0-2.1.noarch
--> Processing Dependency: owncloud-server = 8.2.0 for package: owncloud-8.2.0-2.1.noarch
--> Running transaction check
---> Package owncloud-config-apache.noarch 0:8.2.0-2.1 will be installed
--> Processing Dependency: httpd24-httpd for package: owncloud-config-apache-8.2.0-2.1.noarch
---> Package owncloud-server.noarch 0:8.2.0-2.1 will be installed
--> Processing Dependency: rh-php56-php >= 5.4.0 for package: owncloud-server-8.2.0-2.1.noarch
--> Processing Dependency: rh-php56-php-json for package: owncloud-server-8.2.0-2.1.noarch
--> Processing Dependency: rh-php56-php-zip for package: owncloud-server-8.2.0-2.1.noarch
--> Processing Dependency: rh-php56-php-xml for package: owncloud-server-8.2.0-2.1.noarch
--> Processing Dependency: rh-php56-php-posix for package: owncloud-server-8.2.0-2.1.noarch
--> Processing Dependency: rh-php56-php-ldap for package: owncloud-server-8.2.0-2.1.noarch
--> Processing Dependency: rh-php56-php-mbstring for package: owncloud-server-8.2.0-2.1.noarch
--> Processing Dependency: rh-php56-php-gd for package: owncloud-server-8.2.0-2.1.noarch
--> Processing Dependency: rh-php56-php-pdo for package: owncloud-server-8.2.0-2.1.noarch
--> Processing Dependency: rh-php56-php-process for package: owncloud-server-8.2.0-2.1.noarch
--> Finished Dependency Resolution
__Error: Package: owncloud-config-apache-8.2.0-2.1.noarch (ce_8.2)
           Requires: httpd24-httpd
Error: Package: owncloud-server-8.2.0-2.1.noarch (ce_8.2)
           Requires: rh-php56-php-mbstring
Error: Package: owncloud-server-8.2.0-2.1.noarch (ce_8.2)
           Requires: rh-php56-php-ldap
Error: Package: owncloud-server-8.2.0-2.1.noarch (ce_8.2)
           Requires: rh-php56-php >= 5.4.0
Error: Package: owncloud-server-8.2.0-2.1.noarch (ce_8.2)
           Requires: rh-php56-php-posix
Error: Package: owncloud-server-8.2.0-2.1.noarch (ce_8.2)
           Requires: rh-php56-php-json
Error: Package: owncloud-server-8.2.0-2.1.noarch (ce_8.2)
           Requires: rh-php56-php-zip
Error: Package: owncloud-server-8.2.0-2.1.noarch (ce_8.2)
           Requires: rh-php56-php-pdo
Error: Package: owncloud-server-8.2.0-2.1.noarch (ce_8.2)
           Requires: rh-php56-php-process
Error: Package: owncloud-server-8.2.0-2.1.noarch (ce_8.2)
           Requires: rh-php56-php-gd
Error: Package: owncloud-server-8.2.0-2.1.noarch (ce_8.2)
           Requires: rh-php56-php-xml__
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

rpm -qa| grep php
php-mbstring-5.6.14-1.el6.remi.x86_64
php-5.6.14-1.el6.remi.x86_64
php-pdo-5.6.14-1.el6.remi.x86_64
php-pecl-zip-1.13.1-1.el6.remi.5.6.x86_64
php-pecl-jsonc-1.3.9-1.el6.remi.5.6.x86_64
php-cli-5.6.14-1.el6.remi.x86_64
php-gd-5.6.14-1.el6.remi.x86_64
php-ldap-5.6.14-1.el6.remi.x86_64
php-xml-5.6.14-1.el6.remi.x86_64
php-common-5.6.14-1.el6.remi.x86_64
php-process-5.6.14-1.el6.remi.x86_64

**Comment by nickvergessen** [comment]
@jnweiger

**Comment by yvlitvin** [comment]
Resolved with php and httpd installed from SCL 
https://www.softwarecollections.org/en/scls/rhscl/rh-php56/
https://www.softwarecollections.org/en/scls/rhscl/httpd24/

**Comment by Kawohl** [comment]
Since adding SCL is the recommended way, i'll close.

**Comment by yvlitvin** [comment]
Its recommended, but doesnt exist in RHEL https://download.owncloud.org/download/repositories/stable/owncloud/
i.e.
![image](https://cloud.githubusercontent.com/assets/8770272/11845606/58839810-a41d-11e5-990a-a33a00dcaf40.png)


but exists in CentOS:
**yum install -y https://www.softwarecollections.org/en/scls/rhscl/rh-php56/epel-6-x86_64/download/rhscl-rh-php56-epel-6-x86_64.noarch.rpm**
**yum install -y https://www.softwarecollections.org/en/scls/rhscl/httpd24/epel-6-x86_64/download/rhscl-httpd24-epel-6-x86_64.noarch.rpm**

![image](https://cloud.githubusercontent.com/assets/8770272/11845576/40f84bc8-a41d-11e5-94e7-066a5c224786.png)
