### ISSUE TITLE
Microsoft Office lock files via webdav

### ISSUE THREAD

**Issue by cc6541** [owncloud/core#20000]
Hello,

I am using OC 8.1.3.0 with webdav and shared Office Documents (Excel and Word).

I am looking for a way to lock files when someone is working on it. It works with openoffice, I can see the lock file when someone is working. But with MS OFFICE, there is only a lock in the folder to whom it belongs.. And any other user can open it.

Is there a way to manage with this stuff ? Many thanks.

Regards

**Comment by DeepDiver1975** [comment]
already reported

**Comment by cc6541** [comment]
Hello Deepdiver1975,

I do not use github, Could you pelase tell me where I can find a fix ? Thank you

**Comment by DeepDiver1975** [comment]
Sorry - failed to past the link to the issue https://github.com/owncloud/core/issues/14157

**Comment by DeepDiver1975** [comment]
> where I can find a fix ?

Just to be clear: there is no fix up to now
