### ISSUE TITLE
[8.0.4] "Authentication error"  instead going to the login page in Chrome

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#20006]
### Expected behavior:

Should be redirected to the login page

### Actual behavior:

Shows an error "Authentication error"

#### 

I added in the config php:

```
'remember_login_cookie_lifetime' =>60,
'session_lifetime' => 60,
```

It works perfectly in IE and Firefox, but not with Chrome

@MorrisJobke 

00003979

**Comment by MorrisJobke** [comment]
This is worked on in https://github.com/owncloud/core/pull/16783

**Comment by MorrisJobke** [comment]
Ref https://github.com/owncloud/core/issues/16392

**Comment by cmonteroluque** [comment]
https://github.com/owncloud/core/issues/20006#issuecomment-151057902 Moving milestone forward in sync with https://github.com/owncloud/core/pull/16783

**Comment by bboule** [comment]
@cdamken looks like this is addressed in 9 is that acceptable to the customer?  Have we informed them?

**Comment by cdamken** [comment]
I informed the customer at ```11/11/2015 6:12 PM``` that the solution will be in 9.0

**Comment by PVince81** [comment]
@MorrisJobke have you checked whether https://github.com/owncloud/core/pull/16783 already fixes it ?

**Comment by MorrisJobke** [comment]
> @MorrisJobke have you checked whether #16783 already fixes it ?

It does -> closing. @cdamken Case is already closed on SF.
