### ISSUE TITLE
[8.1.3] Remove share/delete functionality for guest users

### ISSUE THREAD

**Issue by pomelo** [owncloud/core#20009]
Hi, I know it's not the proper place to ask about this question. I have asked this question in the official forum, but without luck. So I come to here to ask for help. It's urgent, thanks!

I set up ownCloud 8.1.3 on CentOS/PHP5.4/MySQL.
I want to restrict normal users to read-only permissions, better to remove all the options on the file list panel and the side bar for the following features:
- favorite;
- sharing;
- deleting;
- create/rename folders;

I can't do this through the configuration, so I guess I should modify the JS/PHP files and hide all the buttons. I tried to modify some of the JS files under core/apps, but the buttons are still there. What should I do? Thanks again!

**Comment by DeepDiver1975** [comment]
tweaking the code is the road to hell - don't do that

to get readonly guest users you could do the following:
- give them a quota of 0
- and share what ever files/folders they should be capable to access with them as read only
- done :wink:

**Comment by pomelo** [comment]
Hi @DeepDiver1975 ,

Thanks a lot for the response. However, I didn't find how to give the guest users a quota of 0.
Besides, I need also to remove the favorite icon for the admin account, so I would tend to know where the source code is, which load the icons, and comment them out. Wouldn't that be the easiest solution?

**Comment by Bullnados** [comment]
Go to user menu->Qutoa->Other->0

**Comment by pomelo** [comment]
Hi @Bullnados ,

I set the quota to 0. However, the share, favorite, etc., buttons are still there. And above all there is a warning about the storage... I don't think it is the result I expected. But thanks all the same.

**Comment by RealRancor** [comment]
@pomelo Sharing can be restricted / disabled for specific groups in your admin backend.

Whats your use case for disabling the favorites?
