### ISSUE TITLE
carddav sync problem with vcard 4.0

### ISSUE THREAD

**Issue by tigermick** [owncloud/core#20005]
Hi,

Since 8.1 version, I have a problem with 1 user on my owncloud server. I don't know why, his contact book is updated to vcard 4.0 just for this user ... 
However, when I try to sync my contact with an application like davdroid (vcard 4.0 compatible), it doesn't work.
I have open a topic on davdroid issue website here : 
https://forums.bitfire.at/topic/765/problem-with-contact-sync-with-owncloud/3
And a developper advises me to open a topic here because it might be a bug about owncloud and not about davdroid ... More precisely about invalid characters with carddav sync with vcard 4.0 only.
If i use an old davdroid version not vcard 4.0 compatible, carddav sync works and with the last versions (vcard 4.0 compatible), it doesn't work.
Anyone can help me to fix this problem please ?

Thank you

**Comment by DeepDiver1975** [comment]
please reopen this in the contacts repo at https://github.com/owncloud/contacts - THX
