### ISSUE TITLE
Provide a warning / check for non-working .well-known urls

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#20012]
Follow-Up of https://github.com/owncloud/core/issues/19801, https://github.com/owncloud/core/issues/19803 and https://github.com/owncloud/3rdparty/pull/189

cc @DeepDiver1975 @georgehrke @smat88

# Problem

oC is currently shipping four rewrite-rules for the apps user_webfinger (no idea if this is used/supported at all), calendar and contacts:

```
RewriteRule ^\.well-known/host-meta /public.php?service=host-meta [QSA,L]
RewriteRule ^\.well-known/host-meta\.json /public.php?service=host-meta-json [QSA,L]
RewriteRule ^\.well-known/carddav /remote.php/carddav/ [R=301,L]
RewriteRule ^\.well-known/caldav /remote.php/caldav/ [R=301,L]
```
https://github.com/owncloud/core/blob/v8.2.0/.htaccess#L39-L42

This rules are working fine if oC is installed in the root dir but are failing if oC is placed in a subdir as discussed in the references above. That leads to various issues with CalDAV and CardDAV clients not being able to detect the correct CalDAV and CardDAV addresses. Especially especially OS X 10.1 El Captain are affected by this problem because it seems the client there is only using the .well-known URLs without allowing to specify another location of the CalDAV / CardDAV urls.

# Current situation

To make users aware of this a documentation is available here: https://doc.owncloud.org/server/8.2/admin_manual/issues/index.html#apple-ios and i've also created an issue to make this more prominent in the documentation: https://github.com/owncloud/documentation/issues/1800

But from the past experience such documentation won't be read by most people so i think another solution is needed.

# Possible solution

If one of the mentioned apps user_webfinger, calendar or contacts are enable check with a similar call like the one already done for the WebDAV interface check if the rewrite-rules are working as expected and warn the user if not.

**Comment by DeepDiver1975** [comment]
Could be something we add to the admin section.

**Comment by RealRancor** [comment]
cc @libasys This is also relevant for your contactsplus and calendarplus apps

**Comment by RealRancor** [comment]
Btw. this affects (probably all) users of the packages as those are installing oC into a subdir.

**Comment by nextgens** [comment]
This is also a problem for reverse-proxied setups when the proxy does the SSL termination...
I've updated my .htaccess locally to redirect to the absolute URL

**Comment by MorrisJobke** [comment]
Is this something for the setup checks in the admin page? Should be easy to check.

cc @LukasReschke
