### ISSUE TITLE
No update of nightly builds / insecure DH-parameters on download.owncloud.org

### ISSUE THREAD

**Issue by tflidd** [owncloud/core#20019]
* Last `nightly` builds are from Oct 19!
* weak DH-parameters: https://www.ssllabs.com/ssltest/analyze.html?d=download.owncloud.org&s=209.126.100.233&latest
-> https://weakdh.org/sysadmin.html

**Comment by LukasReschke** [comment]
> Last nightly builds are from Oct 19!

@karlitschek 

> weak DH-parameters: https://www.ssllabs.com/ssltest/analyze.html?d=download.owncloud.org&s=209.126.100.233&latest -> https://weakdh.org/sysadmin.html

Duplicate of https://hackerone.com/reports/84078

**Comment by RealRancor** [comment]
> Duplicate of https://hackerone.com/reports/84078

Not accessible without an account. :-)

**Comment by LukasReschke** [comment]
> Not accessible without an account. :-)

Also then not accessible until you have my account as the issue is tagged private. But that is just for reference that we can close this one once the nightly builds are fixed from my PoV.

**Comment by karlitschek** [comment]
@cmonteroluque Have you found a solution for the github packaging account problem?

**Comment by cmonteroluque** [comment]
@karlitschek Not yet. Let's check tomorrow

**Comment by PVince81** [comment]
This is old, likely to be solved already ?

**Comment by tflidd** [comment]
SSL settings are ok.
The `nightly` build isn't very reliable. Currently the latest build is from Feb 26:
https://download.owncloud.org/download/repositories/nightly/Debian_8.0/

**Comment by jnweiger** [comment]
Did another manual push into the nightlies, while pushing RC1 to the 9.0:testing downloads.
The automatic update has multiple error messages each day. The latest was a disk full condition, that I cannot reproduce.

**Comment by tflidd** [comment]
Ok, I was able to upgrade to the latest build.

**Comment by jnweiger** [comment]
And as of today,  9.1.0~prealpha.20160304-2.1 is visible through the nightly channel!
Automated updates are fixed. We are rolling again!
