### ISSUE TITLE
New Config Parameter for HTTP Header HSTS and HPKP

### ISSUE THREAD

**Issue by Georg-Git** [owncloud/core#20017]
HTTP Headers for Strict Transport Security (HSTS) and Public Key Pinning (HPKP) is easy to enable via header set in .htaccess file.

But this http headers are not send with php running in cgi mode.

So I added in
/lib/private/response.php:
```
    header('Public-Key-Pins: " ..YourPINData.."; max-age=604800;"');
    header('Strict-Transport-Security:max-age=15768000; includeSubDomains');
```
Of course this is a dirty solution.

So I request a new config parameter to set individuel http headers for a SSL domain.

**Comment by LukasReschke** [comment]
Thanks a lot for your report. I consider it problematic to add this to the admin interface as already with the previous configuration people misconfigured their instances resulting in making their instance inaccessible.

This is also something that can easily be enforced from within your web server. Such as within the VHost config.

**Comment by Georg-Git** [comment]
1. I requested this parameters in the config file.
2. A lot of users installed owncloud in shared hosting environments - no access to apache configs.
3. And after OC is now overwriting .htaccess file when updating, we need another place to config such domain individuel settings

**Comment by osamak** [comment]
I second this request.  With shared hosting, setting headers through web server may not be an option.  Setting these headers through `config.php` or the admin interface will be more practical.
