### ISSUE TITLE
Owncloud log file

### ISSUE THREAD

**Issue by MaxTorque1** [owncloud/core#20015]
I am on a steep learning curve here as I am new to the world of Linux. I am running a virtual Ubuntu Server 14.04 in Windows 2012R2. Owncloud is hosted on the Ubuntu Server and is set up with a CIFS mount for the data.
The server is running fine but I see some recommendations about memory cache in the Administration account and to check the owncloud log file. When I navigate to the data\owncloud.log it only has this line in it: 

{"reqId":"c12e5a72359193225318a54c0d09bd84","remoteAddr":"XX.XX.XX.XX","app":"PHP","message":"touch(): Unable to create file \/var\/www\/html\/owncloud\/data\/owncloud.log because No such file or directory at \/var\/www\/html\/owncloud\/lib\/private\/log\/owncloud.php#48","level":3,"time":"2015-06-01T22:08:19+00:00"}

(Note: The XX.XX.XX.XX is the IP address of my PC where I remote into the server)

What does that even mean and how do I fix it?
Any help greatly appreciated

**Comment by RealRancor** [comment]
Hi,

@MaxTorque1 
please try to ask such support questions at the forums: https://forum.owncloud.org/

The logfile entry itself (nothing to worry about that) was fixed in oC 8.2 and the warnings in your admin backend are described here:

https://doc.owncloud.org/server/8.2/admin_manual/configuration_server/security_setup_warnings.html

**Comment by MaxTorque1** [comment]
Hi RealRancor,

 

Thanks for your response and will do.

 

By using the find command I have located the owncloud.log file in the mounted data drive and it is 461Mb. Is this normal and can I delete it periodically with harming the system?

 

I will see if I can find out how to do the upgrade to 8.2

 

David Rusbridge

info@livingundergrace.com

**Comment by tflidd** [comment]
You can add this to your config.php:
https://github.com/owncloud/core/blob/master/config/config.sample.php#L578-L585
