### ISSUE TITLE
OC 8.2 Bitnami Stack behaviour

### ISSUE THREAD

**Issue by apg1980** [owncloud/core#20016]
Hello together,

first my oc configuration:
Bitnami OC 8.2 Stack
Ubuntu 14.04
Apache to 2.4.17
PHP to 5.5.29
MySQL to 5.6.25

config.php
  'dbtype' => 'mysql',
  'version' => '8.2.0.12',
  'dbname' => 'bitnami_owncloud',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'root',
  'dbpassword' => 'xxx',
  'installed' => true,
  'log_authfailip' => false,
  'cron_log' => true,
  'appcodechecker' => false,
  'updatechecker' => true,
  'check_for_working_webdav' => false,
  'check_for_working_htaccess' => false,
  'appstoreenabled' => true,
  'loglevel' => 0,
  'asset-pipeline.enabled' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'x.x.x.x',
  'mail_smtpport' => '4425',
  'mail_from_address' => 'xx',
  'mail_domain' => xxx.de',
  'mail_smtpdebug' => false,
  'theme' => 'grunet.de',
  'maintenance' => false,
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'ldapIgnoreNamingRules' => false,
  'logtimezone' => 'Europe/Berlin',
  'log_rotate_size' => 202400,
  'forcessl' => false,
  'secret' => 'blabla',
  'overwrite.cli.url' => '/owncloud',
  'xframe_restriction' => true,
  'knowledgebaseenabled' => true,
  'allow_user_to_change_display_name' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'appstore.experimental.enabled' => true,
  'trashbin_retention_obligation' => '30, auto',
  'defaultapp' => 'files',
  'activity_expire_days' => 30,

My Cloud is up and running, but some times while opening adminpage i get the following errors (just sometimes - sorry for the german output below):

#############################################################
Sicherheits- & Einrichtungswarnungen

    Dein Datenverzeichnis und Deine Dateien sind wahrscheinlich vom Internet aus erreichbar. Die .htaccess-Datei funktioniert nicht. Es wird dringend empfohlen, Deinen Webserver dahingehend zu konfigurieren, dass das Datenverzeichnis nicht mehr vom Internet aus erreichbar ist oder dass Du es aus dem Document-Root-Verzeichnis des Webservers herausverschiebst.

    Dieser Server hat keine funktionierende Internetverbindung. Dies bedeutet, dass einige Funktionen wie das Einhängen externen Speicherplatzes, Update-Benachrichtigungen oder die Installation von Drittanbieter-Apps nicht funktionieren werden. Der Fernzugriff auf Dateien und der Versand von E-Mail-Benachrichtigungen kann ebenfalls nicht funktionieren. Es wird empfohlen, die Internetverbindung dieses Servers zu aktivieren, wenn Du alle Funktionen nutzen möchtest.
    /dev/urandom ist für PHP nicht lesbar, wovon aus Sicherheitsgründen dringend abgeraten wird. Weitere Informationen hierzu findest Du in unserer Dokumentation.
    The reverse proxy headers configuration is incorrect, or you are accessing ownCloud from a trusted proxy. If you are not accessing ownCloud from a trusted proxy, this is a security issue and can allow an attacker to spoof their IP address as visible to ownCloud. Further information can be found in our documentation.
    Memcached is configured as distributed cache, but the wrong PHP module "memcache" is installed. \OC\Memcache\Memcached only supports "memcached" and not "memcache". See the memcached wiki about both modules.

    Transactional file locking is using the database as locking backend, for best performance it's advised to configure a memcache for locking. See the documentation ↗ for more information.
    Es wurde kein PHP Memory Cache konfiguriert. Konfiguriere zur Erhöhung der Leistungsfähigkeit, soweit verfügbar, einen Memory Cache. Weitere Informationen finden Sie in unserer Dokumentation.

Bitte überprüfe noch einmal die Installationsanleitungen ↗ und kontrolliere das Log auf mögliche Fehler oder Warnungen.
#############################################################

Sometimes the errors disappear after browser refresh and it will be displayed: All checks passed.

I get also sometimes after clicking the owncloud symbol above left a download for index.php.

i cannot see any further error log entrys just the following in error.log:
[Sat Oct 24 10:32:32.091897 2015] [:error] [pid 47801] [client 10.10.20.10:49938] PHP Fatal error:  Call to undefined function OCA\\Documents\\get_temp_dir() in /OWNCLOUD-DATA/opt/bitnami/apps/owncloud/htdocs/apps/documents/lib/converter.php on line 53

can anybody help?

**Comment by enoch85** [comment]
Try this VM: https://www.en0ch.se/pre-configured-owncloud-installaton/ and see if the issue persists. I configured Redis cache and Transactional File locking.

**Comment by LukasReschke** [comment]
Also please ask generic support questions at forum.owncloud.org – THX.

**Comment by RealRancor** [comment]
@LukasReschke 
This was already asked at the forums and we pointed the user here. The problem here is not that the warnings are shown but that they shown up from time to time and sometimes the OP is getting a "All checks passed".

Don't think that we can help at the forums about such issues.

**Comment by apg1980** [comment]
do you need further Infos?

**Comment by RealRancor** [comment]
@apg1980 If no one is re-opening here maybe create a new issue.

Make sure that you clearly state there:

- The issue is not the warnings itself
- The warnings are sometimes showing up and sometimes you're getting the "All checks passed" message

**Comment by apg1980** [comment]
My Problem is not the warning that appears sometimes in admin page, furthermore the behaviour of getting index.php downloading after clicking or that output:

[]HTTP/1.1 200 OKDate: Thu, 29 Oct 2015 16:44:02 GMT
Server: Apache
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=15768000; includeSubDomains; preload
X-Powered-By: PHP/5.5.30
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-cache, must-revalidate
Pragma: no-cache
Content-Security-Policy: default-src 'none';script-src 'self' 'unsafe-eval';style-src 'self' 'unsafe-inline';img-src 'self' data: blob: data:;font-src 'self' data:;connect-src 'self';media-src 'self'
Vary: Accept-Encoding
Content-Encoding: gzip
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Robots-Tag: none
Content-Length: 3630
Keep-Alive: timeout=300, max=299
Connection: Keep-Alive
Content-Type: text/html; charset=UTF-8

‹������Õ\ëŽÛ6þ<ã¢Û­Föø2vk§˜dÒnÝ4Ø´è
E@IG6g$Q¥({&è»ìŸ>C_ /¶‡¤®¶3ÇC;b‰"Ïwøñè<$5tñÝÓï~ñŒ¬d=~8ä8¿²DÈ7ÏÈô·Çsõ€øÍ²E/Y:~–øoª2ÍÔÓ ¨¤NQV<
@8!÷s,Ò(ƒ‰h²\ô¼z<ô+$sœ¡f·@i”ÙÑ(/¥FúäGóìÄûPCrœÚƒù
h`$äˆE¯?Ï¦çã§Îä«'g4î?uÎãSgr:}2~5žÆ“RÀï9dRò+Hšw“S:f0öO½ÑpÂÁl6@™gáüYèMGgAÿ¬?ë÷§tÀÙÈa<ùc¼ýôãêÓ_Féjôûäêå^0˜`8èÏ<,úž7CfŒ‡§£!þ³éY0ô&€hŸbÖ1
ý³ÙÈÇ¬“~ß÷'ãQÌÂBx:L½Óàl¼É)„Ó³q�³áøl4�ŸžAØÇ
ŒQÚäó_žÅëÁÓŸezÑ{ø�ÿ¯ó$%þŠŠä¢—ËÐ™öôÉdêêÁ×4Š@Ü|JòôÛï~¸8ùú??<öýÉÅ3Ly!ØšJâEÀäjÀšùàè›ÏK˜d4r2ŸF°œô?#1¦ÅyÜJ¢×í¤8š¦8Læ dÞ4`ñÎaÁb<NÎN“Ù[ÊÆÜcø³O•w|šÒ6%7Ý­h&©Ì3Ç£/oZ2<|›®î&E7[£hÙø;¥ßIq¹‚ŸG¼Ù”œÆžOMîˆ%WD@´èe+lH?—„aÎ‘7)J`1]‚›&ËY¡U,z.ß$~ÄóÀÕÂ3w)°5äI�®Ï¸,^º!]+'ªØˆ!AòÜ_9*“
ðÑ4yÁ;@IÐƒv…T³d+�¹+Yò³Ì5™NðòËõ¢?^8D×2ýQF0 è7Ð¡s8CïCÀ(Šö@ò®˜Êk‚èÓØO·˜ª…:¦6D#ïMºëJ²ë®M6Î#É2ˆÀ—Ý¯q¨Á…{‰qãä¬ôÍ Ní–ˆ
Öy­ 9ÇfH;Uf–†Ï_ùK=NE •¨îºV#^S\wKz†£µng£®8ØÊzO­AyÓ¹,�~™9YîE,nô—]*"2‰Ýÿ†½®ìO
g<~ý^•h'u§JÂ%™#ùÒ8ÞÇ�Æ8Áî£¬ˆ/»«þÒÓ(ï¼òûñ»õ
Ûðêöâ/™\åžSq`Î÷Øº*œÀlÞ#æÞË¥äÝ0±vÔñkñv%îc–ƒj`K%É„ß„eI�×'é*5x—™Ëý“Ë;!=ž»FfYÑý»#ÐÒíÅ,±
åÄl)¨„­ÛN qœÿÃë<“<¶›cSŠL§Ô—öàbC"]d²¸t6èÅœˆ«¨SfwE“ Š¬qiÎ‹r`qêÄÁX½øc‹s‰£!š*¤rŽbúWO º°�…õh„Äm4Ó¥Èš,‹˜¼±±=P³Â}Çˆ·ÄÓ¥%¹Ñ oÃ›*±n`É*¹/!FÓ”–ä¾d2ã¹ð-ø< ™
CÌ€
¥ Ì•5[o.\ÙÑE+’cœÆ«À¾]éË¤=ÿŸ%4E°�A\õ"àJú¿ïpÐ´:ëÑ¬ö6tM%µaC¶žÎ„WÚ=‰XÇWž‡W:ØÓ¦)ao;š{ÙæÚ‚‹×vzÄ6„ò>|m"
BµÖ
B¿HôÂw”/­ÌÇ.‹À’é+cŽvb…áˆÂ6†
Ð7‚%!WZT!}Û \§Lè·¸8}©ûÚNà,ƒX{s·1Ð¼ÉV[6ý^¨î{«Å‘.0·Aî²cµGf{MÅŒ¿»€i&XÀ”%ç:(S^[€Ù@äóØÒ´·…P[yÎNÌ¢4Op¦wïQÑã³f[ ÅŒ£ÊcË5nÁ·åÒBÌë<A‡[àÔøÆŽÞwÿ]ó>0O�
|‘Ç^g£‘—ßóÊÃ-h‚wÀbi"j_¥}4¹ÂæJ(»ç±ý-®gØ©Aà4"‰NÊ£Eî¾DûªYjÞÂöX1OÔÊ¸‰TÕ÷ÝtW…Ó\°ðÆÅ2®¹ìÜc8Iá²üuÔ‚Î3°=V¼lîèJí°<ºçØí­¯9ÕFðô¸9®^¬W:<Ü,zêBêPKñó„Wùç[ë ¿¤kjÒÍ6o|¢^0È€œ'4ƒ‚vÈ:Mtùª°yj¶CTdìÙaŽ˜¨å3EŠ§Ÿ/zƒb?…[œÿÁ)=×[ðI¶®wÏ¯åóHœ5Ër´½›jGÆÏ¤»ÈniŠõ‡­ê|Ð«0umÕu~¡&”Ää’/—êÄC]­Ó²Z
­[J¥ËS[:5ØÐ‡ |lKCÇ>}Ë6ÑÌa9÷ˆÞ³è¡‹O#zóyÂø¢Uº,””­¾ªkÍz•®Sš´nÒ+CE²êM1[Ê› ¸J¨®å’V UˆÅKB#|QzÄœÓé
O{dl¹’úºÌÿÖí6Á½ËA/·-OŸx:VädDN¯?#ÇŠœNÉèºÒ®ESÝxeB†ÍÒh ÓØÏµ¥'zëSâX¢WÅçå«¤¸n´uÉû¾ ˜:ÑBýbO§2Â“†uÔêl
Þ•yò¨¡ðWILmÊQVußº¯ JïGu%©­ù?YÂA
—>9ß³=±RþK“c!Eÿ qúEëüé±ÇO?<{j ~xú¤:‚Š‰ïûê‡ÃóÆ1ÔC[jÇ7·,Í‹!Â‘ÂÛ›lî–î©Ù«ê+}rWÚè½¿F4¨Ä W[9å™,{D“³t€õ "(©%âö¡ÌËÜ_A¡ª*^ˆbIªAû$i²ÌÉÈ¿8i©ã’Å+±¦QŽIÅÅ‹šø¨¥^…a³#;Wq Gš—y±yV4Oèº¨3^±e9¬Æ—ÄÖCMö
7¶;s[•0+&Z·ÞâNg§°îgF“»“l½Kj Cú¨\ÄtQÂ
½¥ìÂ`ÖG7,1ù£Á<‚Ãr/ÂÁ{µ¡Á—•pEf¬VÌ,ùLA#ªŸp ðW”°B_)»+ßÉ%{}ÔHûêÄªRä ×¹YÌ¥A`…Ë&†"´™`›Yî_TXGÐKó€ñCºtSÀN/dDwdšÿ~1$/0óQô¥¨Ð†‹à«2VH¬¥wÄãøæ/!%²$³81MèRwýwc³Ñê�JÍåèx.Ûq[uÎÇöÈ1îÌŸ‰•áºJn”J¨ ÙU¦â“bÎF`UªeÊ­§½&?ÍégÔÂ~°\¨zØŒ]é…ç¦,µ´ÞLü¨Þ‘”}T/¬6×8!,–¦9É¸PÜsD?#ú†:|Œh{kXñŠŠÚŠwŒXmÝO|Áîvèÿïbþfj]—ïEe
ê
ÐJ¦Ê^|âS,qL´<ÔÇÎé&>NÑ_@¬Äš4óMRžeê{•@Ì2ý$ìÏÊáÑŠµ×ò-\èÝƒŽÊp+!m®=pl8ÌƒiS°
ÖÎ•.*­8çµÍ_s5¿V»½£äm¹ÊAìÖ®ƒýâÐ!“ò{-ŽÚäÓ(W_(fÍ~µ¦Bx
‰²9œù?B Ñrñ$4OÔ1”&ÿíW^mM^uµÕe×ìÒÔÎžÀ9ÊVÊNÊ|™‹Öø„EM2æã«´‡úrñCUã-n«]‡]ç…–hbŸ»ÎLï§Ò‰eÞj¬w¬e©o£–zC¥A»’¥!—{™J¥
