### ISSUE TITLE
8.2 Activating documents crashes owncloud

### ISSUE THREAD

**Issue by ochurlaud** [owncloud/core#20021]
I just upgraded to 8.2

When I enabled my usual apps, I could not come back to the website: I had only a white page.

I thought it was an issue of upgrade, so I did a fresh install and it had the same issue. I solved it by turning the yes to no in the line Documents | enabled | yes of the table oc_appconfig.

I'm on a OVH mutualized server, but I don't think that this explains the issue.

The only relevant line I found in the logs was:

     [Sun Oct 25 13:19:53 2015] [error] [client X.X.X.X] [host example.com] FastCGI: server "/owncloud/path/index.php" stderr: PHP message: PHP Fatal error:  Call to undefined method OCP\\App::register() in /owncloud/path/apps/documents/appinfo/app.php on line 24

**Comment by RealRancor** [comment]
Hi,

@ochurlaud 
you have a version of documents installed from oC 8.0 not compatible with oC 8.2. Please always try to use the latest available version of an App, in this case 0.10.2 and not 0.9.1.

The issue tracker of the App itself is located here:

https://github.com/owncloud/documents/issues

where you can find an existing issue: https://github.com/owncloud/documents/issues/558 about that.

**Comment by ochurlaud** [comment]
So it means that oC 8.2 doesn't ship a Document app version that works with itself ? That strange.

**Comment by ochurlaud** [comment]
I found my answer in your link. Thx
