### ISSUE TITLE
Dead test instance after upgrading from 8.2 to 9.0 pre alpha

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#20023]
### Steps to reproduce
1. Upgrade test instance from 8.2 to 9.0 pre alpha (via get rebase, done as usual)
2. Run via the browser the upgrade - finished, but did not show the login
3. ./occ still showed that an upgrade is needed
4. Run ./occ upgrade command - successful
5. instance is dead, needed to reinstall

### Expected behaviour
Successful instance upgrade

### Actual behaviour
Test instance is dead, needed to reinstall

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** nginx

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** 8.2 (regulary updated test instance) to 9.0 pre alpha

**Updated from an older ownCloud or fresh install:** yes, 8,2

**List of activated apps:** files, files_external, gallery

**The content of config/config.php:** this was the old instance config before reinstall

```
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'assetdirectory' => '/var/www/xxx',
  'asset-pipeline.enabled' => true,
  'preview_max_scale_factor' => 1,
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\JPEG',
    2 => 'OC\\Preview\\GIF',
    3 => 'OC\\Preview\\Illustrator',
    4 => 'OC\\Preview\\Postscript',
    5 => 'OC\\Preview\\Photoshop',
    6 => 'OC\\Preview\\TIFF',
    7 => 'OC\\Preview\\Raw',
  ),
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
  'trashbin_retention_obligation' => 'auto',
);
```

**Are you using external storage, if yes which one:** smb

**Are you using encryption:** no

### Client configuration
**Browser:** Opera

**Operating system:** W7

#### Web server error log
printed in pairs on each try to access via browser
```
2015/10/25 17:32:38 [error] 3087#3087: *23 open() "/var/www/xxx/assets/13e3e478ed6b40cec4c53d06f2aa2e46.css" failed (2: No such file or directory), client: 80.110.35.173, server: xxxxx, request: "GET /assets/13e3e478ed6b40cec4c53d06f2aa2e46.css HTTP/2.0", host: "xxxxx", referrer: "https://xxxxx/"
2015/10/25 17:32:38 [error] 3087#3087: *23 open() "/var/www/xxx/assets/a8a7191e8a3285791d916ba1ba3da02f.js" failed (2: No such file or directory), client: 80.110.35.173, server: xxxxx, request: "GET /assets/a8a7191e8a3285791d916ba1ba3da02f.js HTTP/2.0", host: "xxxxx", referrer: "https://xxxxx/"
```

**Comment by mmattel** [comment]
Very bad.
After cleaning up including the database and as usual installing via ``sudo ocdev base --dir=/var/www/xxx`` I finalized the installation in the browser. I also did the post tasks as usual via a script like setting rights ect. I end up in a loop that the installation screen on the browser is shown again and again. Here is the log:
````
 tail -f data/owncloud.log
{"reqId":"g0fHhEOxhTBI2Ht8MVZB","remoteAddr":"80.110.35.173","app":"PHP","message":"fopen(\/var\/www\/xxx\/config\/config.php): failed to open stream: No such file or directory at \/var\/www\/xxx\/lib\/private\/config.php#188","level":3,"time":"2015-10-25T17:09:33+00:00"}
{"reqId":"B5nitW50PgljFfvQFUs9","remoteAddr":"80.110.35.173","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/xxx\/lib\/private\/setup\/mysql.php#45","level":3,"time":"2015-10-25T17:10:01+00:00"}
````
````
-rw-r-----  1 www-data www-data  1116 Oct 25 18:11 config.php
-rw-r-----  1 www-data www-data 36657 Oct 25 17:47 config.sample.php
-rw-r-----  1 www-data www-data   225 Oct 25 17:47 .htaccess
````

**Comment by mmattel** [comment]
This is interresting:
I did the upgrade yesterday night with all the probems described above. Now in the morning I tried to logon again - I did nothing else than login, no changes to any setup or at the database - and I can login. No error message in owncloud.log or the websites error log. This means that the fopen/undedined offet error above is not relevant anymore. The issue self is still valid. Very strange...

**Comment by mmattel** [comment]
Update: ok, it works that I can login, but enabling extenal storage support does not do it. I click enable, and when I switch to the admin page (even after some time), it is not enabled. Back in app management, external storage support is not enabled. No log entries - really strange...

**Comment by PVince81** [comment]
@mmattel when reporting bugs for unreleased versions, it might be useful to specify the commit id on which your git version is sitting on

**Comment by mmattel** [comment]
here it is: eb10e3a

**Comment by PVince81** [comment]
Can you retest if the upgrade problem still happens with the latest master ?

**Comment by PVince81** [comment]
Please retest upgrading to 9.0beta2 or wait for RC1 to come out tomorrow.
