### ISSUE TITLE
Cannot share with groups

### ISSUE THREAD

**Issue by igor1912** [owncloud/core#20022]
### Steps to reproduce
1. Couple of groups and data in the system
2. Try to share a folder or a calendar or a contacts book with a group
3. 

### Expected behaviour
I can share it with a group

### Actual behaviour
Cannot share with groups, only with single users

### Server configuration
**Operating system**:
Linux Ubuntu

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.26

**ownCloud version:** (see ownCloud admin page)
8.1.3

**Updated from an older ownCloud or fresh install:**
Updated from 8.0.3 

**List of activated apps:**
Activity  2.0.2
Deleted files  0.6.3
File Locking  
First Run Wizard  1.1
Mail Template Editor  0.1
PDF Viewer  0.7
Provisioning API  0.2
Share Files  0.6.2
Text Editor  0.4
Updater  0.6
Versions  1.0.6
Video Viewer  0.1.3
Calendar  0.7.3
Contacts  0.4.0.0
Galerie+  14.1.0
RainLoop  4.2

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'ocl34t1xqrht',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' => 
  array (
    	'www.xxx',
	'https://www.xxx',
	'xxx',
  ),
  'datadirectory' => '/www/xxx/xxx/xxx/owncloud/data',
  'overwrite.cli.url' => 'https://xxx/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.1.3.0',
  'dbname' => 'xxx',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'installed' => true,
  'forcessl' => true,
  'mail_from_address' => 'admin',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'xxx',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtpsecure' => 'tls',
  'mail_smtphost' => 'xxx',
  'mail_smtpport' => 'xxx',
  'mail_smtpname' => 'xxx',
  'mail_smtppassword' => 'xxx',
  'trashbin_retention_obligation' => 14,
  'trashbin_auto_expire' => true,
  'loglevel' => 0,
  'maintenance' => false,
  'theme' => '',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** yes/no
No.

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No.

### Client configuration
**Browser:**
Tried with the newest version of Chrome and Firefox

**Operating system:**
Mac OS X El Capitan Version 10.11.1

**Comment by LukasReschke** [comment]
Can you provide us with a screenshot from the admin menu, specifically the sharing settings? THX.

![2015-10-25_18-22-51](https://cloud.githubusercontent.com/assets/878997/10716827/76ef1d20-7b45-11e5-9a48-ead48fad9551.png)

**Comment by igor1912** [comment]
Found the error. Please close.
