### ISSUE TITLE
index.html redirect causes problems when users wants to host something else at IP/domain

### ISSUE THREAD

**Issue by maxnet** [owncloud/core#20029]
Please get rid of the index.html -> index.php redirect.
Some browsers such as Google Chrome cache redirects for an awfully long time.
Meaning that even after a user removed owncloud and wants to host something else at his domain, visitors are still getting redirected to domain.com/index.php

See: http://salferrarello.com/chrome-clear-redirect-cache/

**Comment by LukasReschke** [comment]
The `index.html` file has actually resolved problems with some other browsers. I personally consider it more important to have a working ownCloud instance in all cases even if deinstallation might cause a little bit more problems then.

**Comment by LukasReschke** [comment]
… unless you do have an idea how we can resolve this in a way without degrading existing installations I doubt that we can change this.

**Comment by maxnet** [comment]
>The index.html file has actually resolved problems with some other browsers.

Care to explain?

Commit e22a8866fbf636b57bd8fae97f73c51a8e66504c suggests `index.html` was only added to simplify things for IIS web server users.
Would argue that using an IIS specific file (default.htm?) would have been better then.

**Comment by karlitschek** [comment]
Strange. I think cached redirects is nothing we can solve on the owncloud side. This actually means that no web application can use redirects anymore because this might break if something is changed on the server but the browser still caches it.
Nothing we can solve on the owncloud side. Sorry.

**Comment by maxnet** [comment]
>This actually means that no web application can use redirects anymore

Normal web applications can continue using "HTTP 302 Found" redirects all they want.

It is just that some browsers are treating the meta refresh stuff you have as equivalent to "HTTP 301 Moved Permanently" instead.

**Comment by DeepDiver1975** [comment]
> Would argue that using an IIS specific file (default.htm?) would have been better then.

It states: IIS for example ... not exclusivly - but anyway

**Comment by sgabler** [comment]
Isn't this a rather obscure use case that @maxnet is describing? It seems to me like this issue could be closed, as this particular case could probably be solved by server configuration

**Comment by maxnet** [comment]
>Isn't this a rather obscure use case that @maxnet is describing?

The thought of someone wanting to host something different than Owncloud at some point is obscure to you?

**Comment by sgabler** [comment]
Ok, bad wording from my side. Sorry about that. :sweat_smile: 

I just noticed that the javascript in the index.html will actually generate a 302 redirect.

https://github.com/owncloud/core/blob/master/index.html#L4

So unless javascript is disabled, this issue should actually not pop up. Or am I missing something?

**Comment by maxnet** [comment]
The meta tag prevails over the Javascript in practice.
At least with Google Chrome.

**Comment by sgabler** [comment]
I tried a lot of different things on my machine, but couldn't come to any satisfying conclusion. Do you have any idea on how to approach this @maxnet?

**Comment by maxnet** [comment]
I am not a native English speaker, so can you clarify what you mean with "couldn't come to any satisfying conclusion" ?
Are you unable to reproduce it?

**Comment by sgabler** [comment]
Oh, sorry for the confusion. I meant that I tried lots of different things to solve the issue, but all my ideas were not good enough to actually solve the problem in a satisfying way.

**Comment by PVince81** [comment]
Is this still a relevant issue ? Is the Chrome cache still a problem ?

Is index.html still needed to work with modern web browsers and Apache 2.4 or Nginx ?

Note that you can use the URL rewrite feature index.html / index.php wouldn't be needed at all in such cases.

Please reopen if this is still an issue.
