### ISSUE TITLE
Error when running autotest.sh

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#20038]
``` 
./autotest.sh sqlite tests/lib/repair/repairmimetypes.php 
Using PHP executable /usr/bin/php
Parsing all files in lib/public for the presence of @since or @deprecated on each method...

Using database oc_autotest
Setup environment for sqlite testing on local storage ...
Installing ....
ownCloud is not installed - only a limited number of commands are available
creating sqlite db
ownCloud was successfully installed
Testing with sqlite ...
No coverage

PHP Fatal error:  Call to undefined method Composer\Autoload\ClassLoader::setClassMapAuthoritative() in /home/nickv/ownCloud/master/core/3rdparty/composer/autoload_real.php on line 45
PHP Stack trace:
PHP   1. {main}() ~/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() ~/phpunit/phpunit/phpunit:55
PHP   3. PHPUnit_TextUI_Command->run() ~/phpunit/phpunit/src/TextUI/Command.php:132
PHP   4. PHPUnit_TextUI_Command->handleArguments() ~/phpunit/phpunit/src/TextUI/Command.php:141
PHP   5. PHPUnit_TextUI_Command->handleBootstrap() ~/phpunit/phpunit/src/TextUI/Command.php:638
PHP   6. PHPUnit_Util_Fileloader::checkAndLoad() ~/phpunit/phpunit/src/TextUI/Command.php:812
PHP   7. PHPUnit_Util_Fileloader::load() ~/phpunit/phpunit/src/Util/Fileloader.php:77
PHP   8. include_once() ~/phpunit/phpunit/src/Util/Fileloader.php:93
PHP   9. require_once() /home/nickv/ownCloud/master/core/tests/bootstrap.php:9
PHP  10. OC::init() /home/nickv/ownCloud/master/core/lib/base.php:1082
PHP  11. require_once() /home/nickv/ownCloud/master/core/lib/base.php:504
PHP  12. ComposerAutoloaderInit2f23f73bc0cc116b4b1eee1521aa8652::getLoader() /home/nickv/ownCloud/master/core/3rdparty/autoload.php:7

Fatal error: Call to undefined method Composer\Autoload\ClassLoader::setClassMapAuthoritative() in /home/nickv/ownCloud/master/core/3rdparty/composer/autoload_real.php on line 45

Call Stack:
    0.0002     233136   1. {main}() ~/phpunit:0
    0.0020     548768   2. PHPUnit_TextUI_Command::main() ~/phpunit/phpunit:55
    0.0020     549384   3. PHPUnit_TextUI_Command->run() ~/phpunit/phpunit/src/TextUI/Command.php:132
    0.0020     551936   4. PHPUnit_TextUI_Command->handleArguments() ~/phpunit/phpunit/src/TextUI/Command.php:141
    0.0047     926168   5. PHPUnit_TextUI_Command->handleBootstrap() ~/phpunit/phpunit/src/TextUI/Command.php:638
    0.0048     934696   6. PHPUnit_Util_Fileloader::checkAndLoad() ~/phpunit/phpunit/src/TextUI/Command.php:812
    0.0048     934872   7. PHPUnit_Util_Fileloader::load() ~/phpunit/phpunit/src/Util/Fileloader.php:77
    0.0051     940392   8. include_once('/home/nickv/ownCloud/master/core/tests/bootstrap.php') ~/phpunit/phpunit/src/Util/Fileloader.php:93
    0.0070    1232832   9. require_once('/home/nickv/ownCloud/master/core/lib/base.php') /home/nickv/ownCloud/master/core/tests/bootstrap.php:9
    0.0071    1237472  10. OC::init() /home/nickv/ownCloud/master/core/lib/base.php:1082
    0.0109    1625824  11. require_once('/home/nickv/ownCloud/master/core/3rdparty/autoload.php') /home/nickv/ownCloud/master/core/lib/base.php:504
    0.0110    1639464  12. ComposerAutoloaderInit2f23f73bc0cc116b4b1eee1521aa8652::getLoader() /home/nickv/ownCloud/master/core/3rdparty/autoload.php:7
```

@rullzer did you break it?
It works with master of 2015-10-20 `git checkout master@{2015-10-20}` but not with the newest one `git checkout master`

**Comment by Xenopathic** [comment]
#20024

**Comment by Xenopathic** [comment]
Ahh, no, you forgot to update your 3rdparty submodule

**Comment by LukasReschke** [comment]
Passes on CI => Thou shall give more system information.

**Comment by nickvergessen** [comment]
> Ahh, no, you forgot to update your 3rdparty submodule

I think you know me better....


```
php --version
PHP 5.5.30-1+deb.sury.org~trusty+1 (cli) (built: Oct  4 2015 16:23:01) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.3.2, Copyright (c) 2002-2015, by Derick Rethans
    with blackfire v1.6.0, https://blackfire.io, by Blackfireio Inc.
```

**Comment by MorrisJobke** [comment]
Works here too.

**Comment by rullzer** [comment]
https://github.com/owncloud/3rdparty/blob/3fc181b1261d020c98f1554c5203dcd239541ce8/composer/ClassLoader.php#L253-L262 <-- do you have that function locally?

**Comment by nickvergessen** [comment]
Okay the fix is to call `composer.phar dump`
The problem is I had more projects and one had an old autoloader without that method.
Since it was in my path, it was prefered over the local composer version which was up to date.

**Comment by blizzz** [comment]
Running into this as well. @nickvergessen where did you run the dump command? does not work for me in 3rdparty (and would also change that repo).

**Comment by PVince81** [comment]
I'm also getting this on master (c30919303990c51b78157d86b95c0f97e004233d) but not on stable8.2

**Comment by PVince81** [comment]
@nickvergessen is this something that many developers are going to experience ? We might need a better solution for this

**Comment by PVince81** [comment]
My system info:
- openSUSE Factory (recently updated)
± % php --version
PHP 5.6.13 (cli) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans
- PHPUnit 4.3.5

Getting the error like the OP when running `./autotest.sh sqlite`

**Comment by LukasReschke** [comment]
EXPLAIN EXPLAIN EXPLAIN! As in: Give system information.

That said, likely https://github.com/composer/composer/issues/2553 which is caused by having some composer mixups locally ;-)

**Comment by LukasReschke** [comment]
Aha! There are the system information. Best try the steps from https://github.com/composer/composer/issues/2553 to ensure that you do not have stuff in the PATH or somewhere else that mix stuff up :wink:

**Comment by PVince81** [comment]
I have my composer here: /home/vincent/bin/composer which is the only composer in the PATH.
I tried `composer selfupdate` but the problem persists.

Now trying to find the steps you were mentionning.

**Comment by PVince81** [comment]
Okay, running `composer global dump` inside the git root solved it for me.
@blizzz check this out

**Comment by PVince81** [comment]
This is all black magic for me... so composer has global stuff too ?

**Comment by PVince81** [comment]
That fixed it for good. Switching between stable8.2 and master, unit tests can still be run.
So this can probably be closed => local env issue

**Comment by blizzz** [comment]
Works for me as well. Ty @LukasReschke

**Comment by PVince81** [comment]
Thanks guys!

**Comment by LukasReschke** [comment]
You're welcome :)

So what you likely locally have had is a outdated composer / PHPUnit class map not having those functions. As this classmap is loaded before the one from ownCloud the function is not found. Dumping the autoloader new should regenerate the classmap with a new one that has the required function. :smile:
