### ISSUE TITLE
[design] OC 8.2 - External Storage - FTP - ftps checkbox description is badly placed

### ISSUE THREAD

**Issue by HLFH** [owncloud/core#20032]
Hi,

It seems that we need a little fix for the ftps checkbox on Personal & Admin page. It's badly placed on the right on full screen (1366 x 768).
I'm using Chrome 46.0.2490.71 and I'm running Chrome OS with an Asus C300MA.
![personal goto-stockage-externe](https://cloud.githubusercontent.com/assets/2359059/10720627/98aadd06-7b99-11e5-90ad-f2317a81a7d0.jpg)

Thanks in advance,
HLFH

**Comment by PVince81** [comment]
@Xenopathic, need to find a way to make them stick together

**Comment by SergioBertolinSG** [comment]
Still happening on 9.0.

**Comment by guruz** [comment]
WiP PR on https://github.com/owncloud/core/pull/25120
