### ISSUE TITLE
[8.2] LDAP - Quota not delivered

### ISSUE THREAD

**Issue by eidota** [owncloud/core#20043]
### Steps to reproduce
1. Set up ownCloud 8.2
2. Configure LDAP
3. Login with User / Wait for quota refresh time

### Expected behaviour
Quota in ownCloud should be set to the value given by LDAP ('Quota Field')
This was working with the same LDAP-Configuration using Version 8.1.3.

### Actual behaviour
Quota is set to 1073741824 ('Quota Default'); Quota is not refreshed when logging or after waiting 24h.

### Server configuration
**Operating system**:
Redhat 7
**Web server:**
Apache/2.4.6
**Database:**
MariaDB
**PHP version:**
5.4.16
**ownCloud version:** (see ownCloud admin page)
8.2
**Updated from an older ownCloud or fresh install:**
Fresh Install

#### LDAP configuration

+-------------------------------+------------------------------------------------------+
| Configuration                 |                                                      |
+-------------------------------+------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                    |
| hasPagedResultSupport         |                                                      |
| homeFolderNamingRule          |                                                      |
| lastJpegPhotoLookup           | 0                                                    |
| ldapAgentName                 | cn=ownCloudUser,ou=Special Users,dc=...,dc=de        |
| ldapAgentPassword             | ***                                                  |
| ldapAttributesForGroupSearch  | description                                          |
| ldapAttributesForUserSearch   | mail;givenName;uid;displayName;sn                    |
| ldapBackupHost                |                                                      |
| ldapBackupPort                |                                                      |
| ldapBase                      | dc=...,dc=de                                  	   |
| ldapBaseGroups                | ou=Groups,dc=...,dc=de                        	   |
| ldapBaseUsers                 | ou=People,dc=...,dc=de                        	   |
| ldapCacheTTL                  | 600                                                  |
| ldapConfigurationActive       | 1                                                    |
| ldapEmailAttribute            | mail                                                 |
| ldapExperiencedAdmin          | 1                                                    |
| ldapExpertUUIDGroupAttr       | cn                                                   |
| ldapExpertUUIDUserAttr        | uid                                                  |
| ldapExpertUsernameAttr        |                                                      |
| ldapGroupDisplayName          | description                                          |
| ldapGroupFilter               | (cn=*)                                               |
| ldapGroupFilterGroups         |                                                      |
| ldapGroupFilterMode           | 0                                                    |
| ldapGroupFilterObjectclass    |                                                      |
| ldapGroupMemberAssocAttr      | memberUid                                            |
| ldapHost                      | 							                           |
| ldapIgnoreNamingRules         |                                                      |
| ldapLoginFilter               | (&(OwnCloudQuota=*)(uid=%uid))                   	   |
| ldapLoginFilterAttributes     |                                                      |
| ldapLoginFilterEmail          | 0                                                    |
| ldapLoginFilterMode           | 0                                                    |
| ldapLoginFilterUsername       | 1                                                    |
| ldapNestedGroups              | 0                                                    |
| ldapOverrideMainServer        |                                                      |
| ldapPagingSize                | 499                                                  |
| ldapPort                      | 636                                                  |
| ldapQuotaAttribute            | OwnCloudQuota                                 	   |
| ldapQuotaDefault              | 1073741824                                           |
| ldapTLS                       | 0                                                    |
| ldapUserDisplayName           | displayName                                          |
| ldapUserFilter                | (OwnCloudQuota=*)                            		   |
| ldapUserFilterGroups          |                                                      |
| ldapUserFilterMode            | 0                                                    |
| ldapUserFilterObjectclass     |                                                      |
| ldapUuidGroupAttribute        | auto                                                 |
| ldapUuidUserAttribute         | auto                                                 |
| turnOffCertCheck              | 0                                                    |
| useMemberOfToDetectMembership | 1                                                    |
+-------------------------------+------------------------------------------------------+

**Comment by PVince81** [comment]
@blizzz @MorrisJobke @Xenopathic

**Comment by blizzz** [comment]
This is known, but has only been seen when testing the patch for 8.1. We will need to port https://github.com/owncloud/core/commit/a05ead505d5cd6b29119e96c95d83b6d0bdb0f98 to 8.2 resp. master (from https://github.com/owncloud/core/pull/19427), but i prefer to have that one reviewed and merged first.

**Comment by blizzz** [comment]
Setting Milestone to current maintenance release, i expect we should be able to get this done in time.

**Comment by eidota** [comment]
Nice - Thank you for the quick response
