### ISSUE TITLE
Feature request: In user management page - See currently used disk space per user.

### ISSUE THREAD

**Issue by ezula** [owncloud/core#20055]
Let the admin user see the currently used disk space per user in the user management page.

**Comment by RealRancor** [comment]
@ezula Have a look at this two apps providing such a functionality:

https://apps.owncloud.com/content/show.php/Storage+Charts+2?content=165528
https://apps.owncloud.com/content/show.php/Storage+Usage+%2B+Activity+Charts?content=166746

**Comment by ezula** [comment]
@RealRancor Seems to be what I'm looking for. Thanks!

**Comment by DeepDiver1975** [comment]
> Seems to be what I'm looking for. Thanks!

and ... close
