### ISSUE TITLE
Downloaded file using wget on mac cannot be opened.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#20057]
### Steps to reproduce

1. Share by link a folder.
Using OS X:
2. Using a terminal tool such as wget or curl download the file from the public link.
For example:
```
wget http://HOST/index.php/s/r0hN73XTFGHi42k/download.tar
```
3. Open it without using extra decompressing apps.

### Expected behaviour
tar file is opened.

### Actual behaviour
tar file cannot be opened. (It can be using external tools).

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Using enterprise theme.
{"installed":true,"maintenance":false,"version":"9.0.0.1","versionstring":"9.0 pre alpha","edition":""}
Seen also in 8.2.0

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Comment by SergioBertolinSG** [comment]
cc: @VicDeo

**Comment by DeepDiver1975** [comment]
@SergioBertolinSG please add the curl statement including request and response headers - THX

**Comment by schiesbn** [comment]
@SergioBertolinSG are you sure that you are using the right command?

if you download a folder you will get a zip file and not a tar file, the command that works for me is:

````
 wget http://localhost/master/index.php/s/3G97jTrd5sPvyGf/download -O test.zip
````

for a single file something like this works for me:

````
wget http://localhost/master/index.php/s/3G97jTrd5sPvyGf/download -O textfile.txt
````

**Comment by DeepDiver1975** [comment]
> if you download a folder you will get a zip file and not a tar file, the command that works for me is:

Two things come to my mind:
- we don't detect MAC when a wget is issued
- the response header which indicates the file name (disposition) is not properly handled by wget (either wgets fault of ours - no idea)

**Comment by SergioBertolinSG** [comment]
@schiesbn using the first command in your comment there is the same problem. Which is behaving like before the tarstreamer was added. (it uncompresses to a .cpgz file not readable, you need to install unarchiver app if you want to open it as a workaround)

**Comment by DeepDiver1975** [comment]
@SergioBertolinSG please provide the requested information - https://github.com/owncloud/core/issues/20057#issuecomment-151165811

**Comment by SergioBertolinSG** [comment]
```
HTTP/1.1 200 OK
Date: Tue, 27 Oct 2015 08:40:01 GMT
Server: Apache/2.4.7 (Ubuntu)
X-Powered-By: PHP/5.5.9-1ubuntu4.13
Set-Cookie: ocw67kemtc39=l00bidsbgsn697ukhvonuonnn7; path=/; HttpOnly
Expires: 0
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: public
Set-Cookie: oc_sessionPassphrase=fIEsDj3AnjsQHJ4%2FTSje8%2FDU3d8WoDH7DS1DPkvnr03sPDYmsJ3vzkyVR0RyaswCCAHXkqQNNsmitU2oohgKZFvGYd0JhpLsa1FBR0%2Bmlw6p7H1yL7oGNoZyaDXb5tGQ; path=/; httponly
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: Sameorigin
X-Robots-Tag: none
Last-Modified: Tue, 27 Oct 2015 08:40:01 GMT
Accept-Ranges: bytes
Connection: Keep-Alive
Content-Disposition: attachment; filename="Documents.zip";
Content-Transfer-Encoding: binary
Transfer-Encoding: chunked
Content-Type: application/zip
```

**Comment by DeepDiver1975** [comment]
@SergioBertolinSG THX - we need the request as well

**Comment by SergioBertolinSG** [comment]
Added to previous comment.

**Comment by DeepDiver1975** [comment]
> > User-Agent: curl/7.30.0

The user-agent is pure curl - no sign about the client os.

Won't fix from my pov

**Comment by nickvergessen** [comment]
> Content-Type: application/zip

So you should put it into a zip and try to unpack that

**Comment by DeepDiver1975** [comment]
> So you should put it into a zip and try to unpack that

the zips we generate cannot be opened on mac

**Comment by nickvergessen** [comment]
yeah, will not fix then

**Comment by nickvergessen** [comment]
Or better worded: can not fix

**Comment by DeepDiver1975** [comment]
> Or better worded: can not fix

well - one option would be to force the archive type by adding some magic url parameter.

But seriously .......

**Comment by SergioBertolinSG** [comment]
Another workaround for this is forcing a safari user agent to curl:
-A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.75.14 (KHTML, like Gecko) Version/7.0.3 Safari/7046A194A"
this way a tar is downloaded which can be opened.

**Comment by VicDeo** [comment]
@SergioBertolinSG yes, this is how it's supposed to work. 
The only reason we added tar support for OSX clients is their default zip implementation. It is dated by 2009 and it is not aware of modern zip package structure. 
But the client should indicate that it is running OSX to get tar instead of zip.
