### ISSUE TITLE
Cannot access to the folder shared by link while it is being setting a password for the link

### ISSUE THREAD

**Issue by davitol** [owncloud/core#20054]
### Steps to reproduce

1.- Share a folder by link
2.- Copy the link
3.- Check set up a password checkbox
4.- Set up a passsword, but do not click away in the page
5.- Try to access to the folder shared by link in other browser

### Expected behaviour

The link should show the folder without asking for a pwd

### Actual behaviour

Owncloud login page is shown

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** ownCloud Enterprise Edition 8.2.0 (daily) Build:2015-10-26T03:20:41+00:00 0aca6312166914b485bf4e31c00e41a208d20605

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:** LDAP

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
 Firefox and Chrome

**Comment by rullzer** [comment]
@davitol I can't reproduce this on master (or stable8.2) could you verify?

**Comment by davitol** [comment]
Me neither :eyes: So let's close it and if I can reproduce it again, I'll reopen the issue.

 Thanks @rullzer
