### ISSUE TITLE
New patchwork release throws `E_USER_WARNING` if fallback if used

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#20065]
With the newly updated patchwork release it throws `E_USER_WARNING` if the fallback is used. From a technical PoV this makes perfect sense. The native PHP INTL extension is way faster and more stable.

This has been added with https://github.com/tchwork/utf8/commit/e23bf48fae812bc6450c00397c30f97c852801d7 and is thus included within master. Each request now results in quite some entries in the error log.

> You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead. at /Users/lukasreschke/Documents/Programming/master/3rdparty/patchwork/utf8/src/Patchwork/Utf8/Bootup/intl.php#18	

I see the following options:

1. Require the PHP INTL extension. Best for performance but may upset some users.
2. Add some magic to our logger to catch this `E_USER_WARNING` and drop this error silently.
3. Just ignore this situation and live with a spammed error log.
4. Check if "symfony/polyfill" behaves better (https://github.com/owncloud/core/issues/20065#issuecomment-151209686)

Thoughts?

cc @karlitschek @DeepDiver1975

**Comment by LukasReschke** [comment]
Note that this is logged with the error level of "Error":

![2015-10-26_17-55-52](https://cloud.githubusercontent.com/assets/878997/10735961/d002db3e-7c0a-11e5-882b-5faccbbc7649.png)

**Comment by LukasReschke** [comment]
… or we check if "symfony/polyfill" behaves better :)

https://github.com/owncloud/core/issues/20067

**Comment by redhell** [comment]
Hey,
i am experiencing this error on current master but my php runs with the intl extension. 

Does it only affect PHP7 (FPM?) that it can't recognize the extension?

**Comment by rullzer** [comment]
@LukasReschke is this now fixed with https://github.com/owncloud/core/pull/21135 ?

**Comment by PVince81** [comment]
@LukasReschke is this fixed already with the recent polyfills ?

**Comment by LukasReschke** [comment]
Patch is at https://github.com/owncloud/3rdparty/pull/249
