### ISSUE TITLE
Consider using "symfony/polyfill"

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#20067]
Pretty cool polyfill for a lot of PHP functions: https://github.com/symfony/polyfill

**Comment by DeepDiver1975** [comment]
Seems to have an intersection with the patchwork lib which we are already using?

**Comment by LukasReschke** [comment]
Yup. But the libraries are by the same maintainer so I'd consider it to be at least as stable as before. I'm right now testing what stuff this would affect.

**Comment by DeepDiver1975** [comment]
> I'm right now testing what stuff this would affect.

great - thx a lot!

**Comment by rullzer** [comment]
PR in https://github.com/owncloud/core/pull/21135 is already mered. Closing this.
