### ISSUE TITLE
WebDAV MOVE on a non existing file results in Internal Server Error 

### ISSUE THREAD

**Issue by davivel** [owncloud/core#20069]
### Steps to reproduce
1. In the web UI, create a folder named ```src``` in the root folder; leave it empty.
2. From command line, type
```curl -v -u [user]:[password] https://[domain_and_base_path]/remote.php/webdav/src/nofile.txt -X MOVE -H "Destination:https://[domain_and_base_path]/remote.php/webdav/nofile.txt" -H "Overwrite:F"```

### Expected behaviour
HTTP/1.1 404 Not Found
...
Exception with message ```File with name src/nofile.txt could not be located``` (seen in version 8.1.3)

### Actual behaviour
HTTP/1.1 500 Internal Server Error
...
No response body

### Server configuration
**Operating system**:
Ubuntu

**Web server:**
Apache/2.4.7

**Database:**
MySQL

**PHP version:**
PHP/5.5.9-1ubuntu4.13

**ownCloud version:** (see ownCloud admin page)
ownCloud 8.2.0 (stable)
8.2.0.12 in status.php

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Activity  2.1.3
Deleted files  0.7.0
File Locking  
First Run Wizard  1.1
Gallery  14.2.0
Mail Template Editor  0.1
Notifications  0.1.0
PDF Viewer  0.7
Provisioning API  0.3.0
Share Files  0.7.0
Text Editor  2.0
Updater  0.6
Versions  1.1.0
Video Viewer  0.1.3

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:**
No

**Are you using an external user-backend, if yes which one:**
No

#### ownCloud log (data/owncloud.log)
```Error	PHP	Call to a member function isDeletable() on a non-object at /opt/owncloud/lib/private/connector/sabre/filesplugin.php#135	2015-10-26T19:48:30+00:00 ```

#### EXTRA
There is no error if nofile.txt is "located" in the root folder, instead of a subfolder.

**Comment by davivel** [comment]
@rperezb, this will break automatic tests in #owncloud-android-library if run with an OC server version 8.2, what is needed to add a test for the operation to get sharees.

**Comment by DeepDiver1975** [comment]
There is a null check missing in https://github.com/owncloud/core/blob/stable8.2/lib/private/connector/sabre/filesplugin.php#L135

@rullzer mind taking care? master and stable8.2 require this fix - please including unit tests - THX

**Comment by rullzer** [comment]
Yes will take care.

**Comment by rullzer** [comment]
PR in #20076

**Comment by davivel** [comment]
Works for me. Thank you all.
