### ISSUE TITLE
Using IE9 as browser, tooltips in app menu are not shown completely

### ISSUE THREAD

**Issue by davitol** [owncloud/core#20075]
### Steps to reproduce

1.- Using IE9 as browser, go to the apps menu
2.- Mouse over 'Official' word in order to show the tooltip

### Expected behaviour

Tooltips should be shown completely

### Actual behaviour

Tooltips are shown cut

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** ownCloud Enterprise Edition 9.0 pre alpha (daily) Build:2015-10-26T03:32:42+00:00 172bcf2d51d9a10520129a7a794d397457d91d96

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:** 

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Internet Explorer 9

Note: This behaviour happens due to https://github.com/owncloud/core/pull/19923

![tooltipcor](https://cloud.githubusercontent.com/assets/10596560/10752475/e4f2109e-7c89-11e5-901a-2f815909ab83.png)

**Comment by nickvergessen** [comment]
@PVince81 @MorrisJobke

**Comment by jancborchardt** [comment]
This seems to be because the app icons are not shown on IE9. A simple fix would be to show the tooltips to the right of the label (if that looks good).

**Comment by davitol** [comment]
@jancborchardt 

> Note: This behaviour happens due to #19923

**Comment by PVince81** [comment]
or change the tooltip container. I saw @Henni do that lately for the LDAP wizard and it worked nicely.

**Comment by Henni** [comment]
changing the container is the way to go.
I'll take a look.
