### ISSUE TITLE
Exception: Please upload the ca-bundle.crt file into the 'config' directory.

### ISSUE THREAD

**Issue by Skelos** [owncloud/core#20086]
I got this error when updating. Message said "Please report this issue to the .... " and so I'm here.

**Comment by RealRancor** [comment]
Dup of https://github.com/owncloud/core/issues/19805, https://github.com/owncloud/core/issues/19669, https://github.com/owncloud/core/issues/19551, ...

**Comment by MorrisJobke** [comment]
To fix it: Upload https://raw.githubusercontent.com/owncloud/core/master/resources/config/ca-bundle.crt as ca-bundle.crt to the config dir.

**Comment by Skelos** [comment]
Thank you. It works.

**Comment by ps-nsimic** [comment]
just out of interest, why is this necessary?

**Comment by RealRancor** [comment]
Becaus of a bug in the updater app: https://github.com/owncloud/updater/issues/164
