### ISSUE TITLE
Link to owncloud-8.0.3.tar.gz contains Version 8.1.3

### ISSUE THREAD

**Issue by matrixritter** [owncloud/core#20085]
I downloaded the following file: https://download.owncloud.org/community/owncloud-8.0.3.tar.bz2 and upgraded unexpectedly from 8.0.2 straight to 8.1.3 (!). The md5 check (which I missed, my bad) gives a mismatch, the version.php in the archive says it's 8.1.3. The aquivalent .zip has the right version according to the filename in it.

**Comment by DeepDiver1975** [comment]
oh yes - too bad

@cmonteroluque @karlitschek @danimo who can help out here? THX

**Comment by MorrisJobke** [comment]
> @cmonteroluque @karlitschek @danimo who can help out here? THX

Ping

**Comment by SergioBertolinSG** [comment]
This is fixed.
