### ISSUE TITLE
[8.2][Ubuntu][14.04] Available?

### ISSUE THREAD

**Issue by pierrejochem** [owncloud/core#20087]
When is version 8.2 available at: http://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_14.04/

?

**Comment by karlitschek** [comment]
@jnweiger

**Comment by RealRancor** [comment]
Hi,

there won't be any oC 8.2 packages available here as described in this blogpost:

https://owncloud.org/blog/upgrading-to-owncloud-server-8-2/

This is also described in the release notes of oC 8.2: https://doc.owncloud.org/server/8.2/admin_manual/release_notes.html#changes-in-8-2

**Comment by pierrejochem** [comment]
I see it is a new repo url:

deb http://download.owncloud.org/download/repositories/8.2/xUbuntu_14.04/ /

**Comment by pierrejochem** [comment]
Thank you :-)

**Comment by pierrejochem** [comment]
@karlitschek You can close it and next time I read the release notes :eyeglasses:
