### ISSUE TITLE
When chosing Gallery, the user gets switched

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#20088]
@oparoz 

It is for me not distingusiable if this is a pure Gallery problem or if this is a core problem.
I put it to core because IMHO, a user switch is made in core.

The following is true on stable 8.2 and master 9.0 (eb10e3a)

### Steps to reproduce
1. Having one admin user and no other users present
2. Add an SMB Share with many pictures (let it scan)
3. Open Gallery or Gallery+
4. Thumbs are created and shown
5. Add an additional user with an additional group and assign the group additionally to the share
6. Logoff and logon with the new user
7. Open Gallery or Gallery+, no thumbs are shown, the foldername is shown only
8. The user shown in the right upper corner is NOT the logged on user but the admin user
9. If you now try to logoff this false user you get ``{"data":{"message":"Token abgelaufen. Bitte laden Sie die Seite neu.","error":"token_expired"},"status":"error"}``
10. Going back to the files page and logoff works
11. Relogging in with the admin user and switching to Gallery does from now on not show any thumbs

### Expected behaviour
Thumbs are shown for each user logged on

### Actual behaviour
False user switch, no thumbs shown

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** nginx 1.9.5

**Database:** MySQL

**PHP version:** 5.5.9

**ownCloud version:** stable 8.2 and master 9.0 (eb10e3a)
The stable version was installed from scratch

**Updated from an older ownCloud or fresh install:** no

**List of activated apps:**

```
Enabled:
  - activity: 2.1.3
  - files: 1.2.0
  - files_external: 0.3.0
  - files_locking:
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - galleryplus: 14.3.0
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - updater: 0.6
Disabled:
  - encryption
  - external
  - gallery
  - user_external
  - user_ldap
```

**The content of config/config.php:** (from the stable release)

```
{
    "system": {
        "instanceid": "oclv9ak7fgy1",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "owncloud.diemattels.at"
        ],
        "datadirectory": "\/mnt\/mm-eddie\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/owncloud.diemattels.at",
        "dbtype": "mysql",
        "version": "8.2.0.12",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Vienna",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "tempdirectory": "\/var\/www\/owncloudtemp",
        "assetdirectory": "\/var\/www\/owncloud",
        "asset-pipeline.enabled": true,
        "filesystem_check_changes": 1,
        "preview_max_scale_factor": 1,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Raw"
        ]
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/... SMB

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Opera

**Operating system:** W7

### Logs
no relevant log entries

**Comment by mmattel** [comment]
I did a test and disabled cache-purging in my nginx config.
After disabling, non of the problmes occured and it worked like expected.

@RealRancor do you have any idea what could cause this? And an idea how to fix it?

**Comment by oparoz** [comment]
> After disabling, non of the problmes occured and it worked like expected.

OK, so I think, this is a configuration issue. I'd be happy to add something to the Gallery wiki, if there is something to add to the NGINX config.

**Comment by mmattel** [comment]
I have found the root cause. It is in the nginx cache purge setup.

We have to change the line:
``fastcgi_cache_key $scheme$request_method$host$request_uri$;``
to
``fastcgi_cache_key $http_cookie$request_method$host$request_uri;``

The issue here is, that with the original fastcgi_cache_key definition, everyone has the same key identifyer leading to confusion because not unique to the user. After changing this to have the cookie included, the key created becomes unique.

I will create immediate a documentation PR to have that fixed.

**Comment by oparoz** [comment]
Cool :) I can't comment as I'm not using NGINX, but I'm glad a solution has been found.

**Comment by mmattel** [comment]
It costed me some grey hairs to find the root cause. But I can tell you using nginx cache purge speeds up thumbnail presentation quite a lot. The difference when you browse thru a big picture filesystem going forth an back is impressive... Therefore I can really suggest that functionality when you use nginx.
