### ISSUE TITLE
Who invented the "in progress" label?

### ISSUE THREAD

**Issue by butonic** [owncloud/core#20084]
see https://github.com/owncloud/core/labels/in%20progress
How is it different from "2 - Developing"?

The idea is to use https://huboard.com/owncloud/core to visualize our issues in a kanbab board. For example the state of milestones like [8.1.4-current-maintenance](https://huboard.com/owncloud/core#/?milestone=%5B%228.1.4-current-maintenance%22%5D) or [8.1.5-next-maintenance](https://huboard.com/owncloud/core#/?milestone=%5B%228.1.5-next-maintenance%22%5D)

Selecting a filter on the left only grays out items not matching the filter. Clicking it a second time completely hides them, leaving only the filtered items.

For that to work the labels need to start with a number to indicate the order of steps in our development workflow. 

cc @cmonteroluque @DeepDiver1975

**Comment by DeepDiver1975** [comment]
it's from waffle.io - which is what we are having a look at

**Comment by cmonteroluque** [comment]
@butonic Unfortunately waffle.io makes changes on its own. Not cool. Sorry for the confusion.

**Comment by SergioBertolinSG** [comment]
A similar alternative is https://www.zenhub.io/ it adds an extra layer of labels only for the boards.
