### ISSUE TITLE
Share autocomplete produces warning in log

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#20095]
### Steps

1. Create two users "user1" and "user2"
1. Create a folder "test"
1. Share "test" with "user1"
1. From here, observe the logs
1. Type "us" in the share with autocomplete field and wait until the dropdown appears

### Expected result
No warning in log

### Actual result
```
{"reqId":"ZZqww86BjSNPgg9Exgvk","remoteAddr":"127.0.0.1","app":"PHP","message":"Array to string conversion at \/srv\/www\/htdocs\/owncloud\/core\/ajax\/share.php#363","level":3,"time":"2015-10-27T18:47:48+00:00","method":"GET","url":"\/owncloud\/index.php\/core\/ajax\/share.php?fetch=getShareWith&search=us&limit=200&itemShares%5B0%5D%5B%5D=user1&itemType=file"}
```

It doesn't break any functionality, but somewhat looks like a potential programming error.

### Versions
Observed on master (c30919303990c51b78157d86b95c0f97e004233d) and also 8.4.1RC1

@rullzer @schiesbn @blizzz

**Comment by rullzer** [comment]
Ah one of my favorite files...

**Comment by rullzer** [comment]
@LukasReschke your fault! :stuck_out_tongue_winking_eye:  https://github.com/owncloud/core/commit/a7df23cebadfc0a60095ff53e4ae5e293eb02b38#diff-e574f71b1f320c19e9ffb5c5322146deR280

are those weird casts really needed here?

**Comment by nickvergessen** [comment]
Wait, in_array() call wiht only one parameter?

**Comment by nickvergessen** [comment]
Oh that's an is_array, not in_array,...

FIX
IT
