### ISSUE TITLE
wrong icon theme on debian package and zipfile

### ISSUE THREAD

**Issue by tchncs** [owncloud/core#20094]
Im confused:
I just updated my Archlinux instance without any problems.
Now i tryed to install a fresh cloud to my debian 8 server.

I tryed the zipfile and the ```Debian_8.0 owncloud-server_8.2.0-2``` Repo package from your page.

The folder icons are the old onces.... first i thought its my fault, but it seems to be by your packages... .
![](https://files.tchncs.de/Images/Random/Screenshots/Bildschirmfoto%20vom%202015-10-27%2019-55-03.png)

**Comment by LukasReschke** [comment]
@jnweiger ?

**Comment by MorrisJobke** [comment]
I just checked the owncloud-server_8.2.0-2.1_all.deb and it contains the correct folder icons. @tchncs Can you inspect the icon (right click -> inspect element - in chrome and firefox) and check from which URL the image is loaded.

**Comment by tchncs** [comment]
Ouh, the Icon was cached by Firefox (i installed accidently ownCloud 7 first).
The next time i know what i have to check before making issues, big sorry for that!

**Comment by MorrisJobke** [comment]
> The next time i know what i have to check before making issues, big sorry for that!

Good to know:) No problem
