### ISSUE TITLE
empty() fails in subadmin.php under php5.4 (release 8.1.3)

### ISSUE THREAD

**Issue by DanielTosello** [owncloud/core#20099]
The call to empty() in /lib/private/subadmin.php:180 causes php 5.4 to fail with the following error: 

`Can't use method return value in write context in /var/www/html/owncloud/lib/private/subadmin.php on line 180`
 
This is expected behavior (using reference params in empty() is supported from php5.5), but /index.php defines min version as 5.4.

This problem appears to exist in release 8.1.3 but that's the earliest version i've checked.

**Comment by DeepDiver1975** [comment]
@rullzer mind having a look? Thx

**Comment by rullzer** [comment]
@DanielTosello are you running master? (since there I see the line https://github.com/owncloud/core/blob/master/lib/private/subadmin.php#L180 )

> This problem appears to exist in release 8.1.3 but that's the earliest version i've checked.

What is the error you get there.. since there is no mention of empty in the subadmin in 8.1 https://github.com/owncloud/core/blob/stable8.1/lib/private/subadmin.php

**Comment by DanielTosello** [comment]
I am running master, and apparently checked the wrong tree to confirm that the code was present... i have no idea how i did that though :/

Sorry bout the disinfo there.

**Comment by rullzer** [comment]
No problem. I was just confused as to why it would be happening on the other versions as well. Let me prepare a fix.

**Comment by nickvergessen** [comment]
If only there would be Development Environments that would highlight such issues
![bildschirmfoto vom 2015-10-28 08 37 10](https://cloud.githubusercontent.com/assets/213943/10782284/2d0a6e10-7d4f-11e5-99f5-e4cff40e1be4.png)

**Comment by rullzer** [comment]
Weird thing is my unit tests pass with php 5.4.... strange strange world

**Comment by nickvergessen** [comment]
Btw while looking at the file,
you always select all entries and only check for the first.

Would be nice to add `->setMaxResults(1)`,
also you can use `$result->closeCursor()` to save memory

**Comment by DeepDiver1975** [comment]
> Btw while looking at the file,
> you always select all entries and only check for the first.
> 
> Would be nice to add ->setMaxResults(1),
> also you can use $result->closeCursor() to save memory

or simple do a select count

**Comment by rullzer** [comment]
> Weird thing is my unit tests pass with php 5.4.... strange strange world

A no they do not... but phpunit does not respect our PHP_EXE enviroment variable...

**Comment by rullzer** [comment]
PR in https://github.com/owncloud/core/pull/20102
