### ISSUE TITLE
Can't download large files through webui

### ISSUE THREAD

**Issue by flimao** [owncloud/core#20098]
Hi,

I can't seem to download large files (so far I've tried files as small as 300 MB) from owncloud through the webui. This issue doesn't seem to affect small files (or, at least smaller than 10 MB, which is the largest file I've managed to download successfully).

My setup is a Raspberry Pi running Raspbian Wheezy, and an external USB drive. I've upgraded nginx to version 1.9.5, in order to get `http2` support. 

The `owncloud.log` file makes no reference to this failure. The nginx `/var/log/nginx/access.log` file records the GET request,

    10.0.1.229 - - [28/Oct/2015:02:34:56 +0000] "GET / HTTP/1.1" 200 9732 https://olimpo.limao.me/index.php/apps/files/?dir=%2Fvideos%2FThe%20Blacklist%2FS3#" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240"

but the nginx `/var/log/nginx/error.log` file doesn't show any errors. The `/var/log/php5-fpm.log` file logs a slow-running script,
```
[28-Oct-2015 03:05:54] WARNING: [pool www] child 20826, script '/var/www/owncloud/index.php' (request: "GET /index.php") executing too slow (74.118286 sec), logging
[28-Oct-2015 03:05:54] NOTICE: child 20826 stopped for tracing
[28-Oct-2015 03:05:54] NOTICE: about to trace 20826
[28-Oct-2015 03:05:54] ERROR: failed to ptrace(PEEKDATA) pid 20826: Input/output error (5)
[28-Oct-2015 03:05:55] NOTICE: finished trace of 20826
```

which records `index.php`'s trace in `/var/log/php.fpm.log.slow`:

```
[28-Oct-2015 03:05:54]  [pool www] pid 20826
script_filename = /var/www/owncloud/index.php
[0xb6371360] readfile() /var/www/owncloud/lib/private/files/view.php:373
[0xb63712b8] readfile() /var/www/owncloud/lib/private/files/filesystem.php:664
[0xb6371170] readfile() /var/www/owncloud/lib/private/files.php:187
[0xb63710b0] get() /var/www/owncloud/apps/files/ajax/download.php:42
[0xb6371018] +++ dump failed
```

Here's `top`'s output right after the download is triggered:

```
top - 01:20:27 up 9 days,  3:38,  2 users,  load average: 3.33, 3.03, 2.31
Tasks:  89 total,   1 running,  88 sleeping,   0 stopped,   0 zombie
%Cpu(s):  2.0 us, 17.5 sy,  0.0 ni,  0.0 id, 75.8 wa,  0.0 hi,  4.7 si,  0.0 st
KiB Mem:    493764 total,   480376 used,    13388 free,     3544 buffers
KiB Swap:   524284 total,     4900 used,   519384 free,   383616 cached

  PID USER      PR  NI  VIRT  RES  SHR S  %CPU %MEM    TIME+  COMMAND
21010 www-data  20   0  148m  20m  15m D  17.3  4.3   0:06.10 php5-fpm
  110 root      20   0     0    0    0 S   2.2  0.0   1:14.32 usb-storage
   21 root      20   0     0    0    0 S   1.0  0.0   0:51.53 kswapd0
   40 root      20   0     0    0    0 S   1.0  0.0   1:52.64 mmcqd/0
20298 pi        20   0  3368 1940 1604 R   1.0  0.4   1:00.93 top

```

As you can see, the % of CPU cycles spent on waiting for IO spikes. I tried setting `fastcgi_read_timeout = 60000` in `/etc/nginx/sites-available/owncloud`, but it didn't work.

I'm not sure how to proceed. Any help is appreciated.

Cheers!

**Comment by RealRancor** [comment]
Not really sure if there is something what could be done from oC side. This just looks like a timeout within your environment caused by a long running download. Have a look at:

https://groups.drupal.org/node/229898

for example for some pointers.

**Comment by RealRancor** [comment]
@flimao This could give you some additional pointers:

https://github.com/owncloud/documentation/wiki/Uploading-files-up-to-16GB

**Comment by flimao** [comment]
@RealRancor thank you for your suggestions, but I wasn't able to fix the issue. I'm guessing the owncloud forums are a better place to ask for support, so I moved this discussion [there](https://forum.owncloud.org/viewtopic.php?f=31&t=31233).

Cheers!
