### ISSUE TITLE
Searching users named '_' returns all users. 

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#20107]
### Steps to reproduce

Having several users created without '_' in their usernames do:
```
curl -X GET http://ADMIN_USER:PASSWORD@OC_HOST/ocs/v1.php/cloud/users\?search\=_ 
```

### Expected behaviour
No users are returned.

### Actual behaviour
All users are returned.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"9.0.0.1","versionstring":"9.0 pre alpha","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Comment by nickvergessen** [comment]
Duplicate of #16580

cc @LukasReschke

**Comment by nickvergessen** [comment]
atm you can escape it yourself
```
curl -X GET 'http://ADMIN_USER:PASSWORD@OC_HOST/ocs/v1.php/cloud/users?search=\_'
```

**Comment by nickvergessen** [comment]
However that makes the result different for different user backends, some need escaping, other's do not
