### ISSUE TITLE
Shared resource - download statistics 

### ISSUE THREAD

**Issue by Resquer** [owncloud/core#20100]
Now, I can see "Public shared file blablabla was downloaded" in Activity tab. It is better to view separate statictic data of each shared file of folder in the main interface (download count, last download time, etc.)
Just enhancement suggestion. :)

**Comment by RealRancor** [comment]
To me this sounds like a dup of https://github.com/owncloud/core/issues/14446

**Comment by DeepDiver1975** [comment]
> To me this sounds like a dup of #14446

yes
