### ISSUE TITLE
How to disabled or hide setting > webdav

### ISSUE THREAD

**Issue by dikodhiko** [owncloud/core#20106]
hello world,

can someone tell me how to hide or remove or disable webdav menu on setting (left bottom side)?
im using owncloud 8.2

regards,
diko

**Comment by DeepDiver1975** [comment]
not really possible out of the box - you might want to add some custom css via a theme to hide the full settings panel

```css
#app-settings {
  display: none
}

**Comment by DeepDiver1975** [comment]
or remove this html element from the template
https://github.com/owncloud/core/blob/master/apps/files/templates/appnavigation.php#L12

**Comment by dikodhiko** [comment]
@DeepDiver1975 
can u show to me the original path of #app-setting?
im just wanna using the original theme without webdav menu. :)

**Comment by dikodhiko** [comment]
@DeepDiver1975 
i already solved this case,

u can mark
this 


path on  owncloud/apps/files/templates/appnavigation.php

thanks,

case close

**Comment by RealRancor** [comment]
@dikodhiko Btw. please note that this issue tracker is for reporting bugs and feature requests. If having questions to such dev specific stuff its recommended to ask at:

https://mailman.owncloud.org/mailman/listinfo/devel
