### ISSUE TITLE
Owncloud 8.2 can't save settings

### ISSUE THREAD

**Issue by delumerlino** [owncloud/core#20119]
Actual behaviour

can't save settings in admin page

Server configuration

Operating system:
Ubuntu 14.04

Web server:
apache/2.4.16

Database:
Mysql 5.5.44-0ubuntu0.14.04.1
PHP version:
PHP 5.6.14-1+deb.sury.org~trusty+1

ownCloud version: 
ownCloud 8.2 (stable)

Updated from an older ownCloud or fresh install:
Fresh install

List of activated apps:
Deleted files 0.7.0
File locking
Share files 0.7.0
Updater 0.6
Versions 1.1.0
Calendar 0.8.0
Contacts 0.5.0.0
Dashboard 1.1
Owncloud SMS 1.5.0
Ownnote 1.05

The content of config/config.php:

<?php
$CONFIG = array (
'instanceid' => 'oca5xsros0qm',
'passwordsalt' => 'delumerlino',
'secret' => 'delumerlino',
'trusted_domains' => 
array (
0 => 'internal',
'external',
'external:port'
),
'datadirectory' => '/var/www/owncloud/data',
'overwrite.cli.url' => 'https://',
'dbtype' => 'mysql',
'version' => '8.2.0.12',
'dbname' => 'owncloud',
'dbhost' => 'localhost',
'dbtableprefix' => 'oc_',
'dbuser' => 'oc_admin',
'dbpassword' => '',
'logtimezone' => 'UTC',
'installed' => true,
'theme' => '',
'mail_smtpmode' => 'smtp',
'mail_from_address' => 'name',
'mail_domain' => 'domain.com',
'mail_smtpauthtype' => 'PLAIN',
'mail_smtpauth' => true,
'mail_smtpname' => 'name@domain.com',
'mail_smtppassword' => 'password',
'mail_smtphost' => 'smtp.domain.com',
'mail_smtpport' => 'port',
'mail_smtpsecure' => 'tls',

'loglevel' => 0,
'maintenance' => false,
);

Are you using external storage, if yes which one:
no

Are you using encryption:
no

After fresh install, can't save settings:

- Email setting are manually saved in config.php (can't select smtp mode in admin page). Can't send test email 
- can't chose OwnNote saving method (database or database/folder)
- can't select to get users stats in dashboard settings
- can select sharing options, but they are not saved
- can't click "more" on logs

Security and configuration warning at the top of the page is stuck on loading

**Comment by PVince81** [comment]
Anything in owncloud.log or Apache's error log from the time of saving the settings ?

**Comment by delumerlino** [comment]
Nothing important....

here is apache errror log:

[Thu Oct 29 10:13:31.546596 2015] [core:notice] [pid 1764] AH00052: child pid 1770 exit signal Segmentation fault (11)
[Thu Oct 29 10:13:31.810174 2015] [mpm_prefork:notice] [pid 1764] AH00169: caught SIGTERM, shutting down
[Thu Oct 29 10:13:32.581054 2015] [ssl:warn] [pid 5731] AH01906: RSA server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Oct 29 10:13:32.638263 2015] [ssl:warn] [pid 5732] AH01906: RSA server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Oct 29 10:13:32.644284 2015] [mpm_prefork:notice] [pid 5732] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.13 OpenSSL/1.0.1f configured -- resuming normal operations
[Thu Oct 29 10:13:32.644338 2015] [core:notice] [pid 5732] AH00094: Command line: '/usr/sbin/apache2'

Nothing important in owncloud.log, only transactions....

**Comment by PVince81** [comment]
Are you able to change settings in the admin page, like link share settings ? Are these properly saved ?

**Comment by delumerlino** [comment]
I can change them, but they are not saved.

**Comment by PVince81** [comment]
Does the network console in the browser say anything ? Any error code ?

**Comment by delumerlino** [comment]
If you mean the top of the page in the admin page it says nothing. The animated gif is stuck on loading.

**Comment by PVince81** [comment]
Hmmm, no. Open the browser console, it must have a "Network" tab, select it.
Then change one of the settings.
The network tab should now have an additional line with "appconfig.php". Check what the response code and reponse body is for that one.

**Comment by delumerlino** [comment]
Sorry but I can't understand. I am using OC on Ubuntu server, my web browser is Chrome under Windows...

**Comment by PVince81** [comment]
In Chrome, hit the F12 key to open the console, you should see this:
![chrome-dev-console](https://cloud.githubusercontent.com/assets/277525/10816036/247bf12e-7e30-11e5-8439-cb1ef1e334ca.png)

**Comment by delumerlino** [comment]
Thank you.
It seems no errors:

data: true, status: "success"}
data: true
status: "success"

I have tried now to unistall dashboard because it wasn't logging. Now seems I am able to save the settings....

**Comment by PVince81** [comment]
Hmmm, maybe that app is causing trouble. Can you submit a bug report to that project ?

**Comment by delumerlino** [comment]
I can confirm it is caused by dashboard. I will submit right now a bug report! Thanks a lot!

**Comment by PVince81** [comment]
Thanks, closing
