### ISSUE TITLE
Stable 8.2 AdminPage: version print for updates and the check date is defect

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#20115]
Running ownCloud 8.2.0 (stable) on Ubuntu 14.04/mysql/php5.5.9

When you go to the admin page, you see at the bottom that the version print for updates and the check date is defect. Anything else is running fine.

![image](https://cloud.githubusercontent.com/assets/3321281/10788079/4744cb2e-7d75-11e5-9eb2-8c6963e32d20.png)

**Comment by RealRancor** [comment]
Hi,

seems thats an issue within the updater app which is already reported here: https://github.com/owncloud/updater/issues/184
