### ISSUE TITLE
Oracle on Travis takes too long and kills our overall travis performance

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#20110]
Because we start using travis for some core prs now: individual job execution times are more critical.

Once of the most critical are jobs which use oracle for unit testing.
Installing oracle taken most of the time.

In addition we should switch to the container based infrastructure

Affected apps:
- activity
- antivirus
- updater
- documents

**Comment by DeepDiver1975** [comment]
@nickvergessen interesed? :wink:

**Comment by DeepDiver1975** [comment]
User AWS RDS??? https://aws.amazon.com/rds/oracle/

**Comment by nickvergessen** [comment]
I just checked it by forking the activity repo, the only thing that fails is oracle set up, the other dbs work just fine on the container based stuff.

The problem is sudo usage in `before_install_oracle.sh`

**Comment by PVince81** [comment]
@DeepDiver1975 will you invest time in this in the context of 10.0 ? If not -> backlog

**Comment by PVince81** [comment]
and backlog it is

**Comment by DeepDiver1975** [comment]
we move to selhosted drone - oracle is faster there
