### ISSUE TITLE
Ownload LDAP configuration

### ISSUE THREAD

**Issue by mohit-solanki** [owncloud/core#20113]
Hello,

I am trying to configure owncloud to integrate with my existing LDAP setup which is currently being used for Qmail server setup.

At present I have these objectClasses - 
inetOrgPerson
person
qmailUser
top

And 1000+ users, but owncloud is not detecting my users, though it is detecting I have over 1000 entries in my BaseDN

Also, Not able to find any compatibility documents on documentations.

Could you please help me understand if I can achieve this setup.

Thanks,
Mohit S.

**Comment by PVince81** [comment]
For support requests, please use the forums here http://forum.owncloud.org/

If you think this is a bug, please fill out the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

CC @blizzz

**Comment by MorrisJobke** [comment]
There is also detailed documentation in the manual: https://doc.owncloud.org/server/8.2/admin_manual/configuration_user/user_auth_ldap.html

**Comment by mohit-solanki** [comment]
Thanks MorrisJobke & PVince81

I have already seen and worked with the link, its not helping. 

I just want to know if it can scan users from my qmailUser or inetOrgPerson objectclass as I mentioned above from - 
inetOrgPerson
person
qmailUser
top

As it is not scanning users from any of them (Have 1000+ qmail users) so I am not able to test the product, or further getting the premium solutions.

Kindly help me if it could detect users from my qmailUser or inetOrgPerson objectclass.

So I could test it further.

Thanks,
