### ISSUE TITLE
Move ext storage backends into their own apps

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#20116]
I'd like to discuss the explicit steps to take in scope of 9.0 regarding out external storage implementations.

As soon as we touch any of these following steps are to be taken:
- convert the implementation to an app of its own
- setup travis unit testing - example https://github.com/icewind1991/files_external_ftp

In addtion we need to come up with a decision on if we want to continue to ship each of them - basically because of resource to be invested regarding the initial upgrade and future maintenance.

In case we decide to no longer ship any of these we can come up with a plan to move the code out to the community

Immediate action required:
- amazon s3
- dropbox
- google
- swift

Unclear:
- sftp

No action required
- ftp (already taken care of https://github.com/icewind1991/files_external_ftp)
- owncloud
- dav
- smb

@karlitschek @cmonteroluque @MTRichards @icewind1991 THX for your comments

**Comment by cmonteroluque** [comment]
@DeepDiver1975 thanks! My initial reaction is to continue to support what we have so far, under the new implementation. As many as possible in 9.0 and the rest afterwards. It is my default reaction, happy to talk more

**Comment by karlitschek** [comment]
thanks @DeepDiver1975

**Comment by icewind1991** [comment]
s3, dropdox and sftp have flysystem implementations which we could use

**Comment by DeepDiver1975** [comment]
> s3, dropdox and sftp have flysystem implementations which we could use

no swift support? I missed that - THX

**Comment by DeepDiver1975** [comment]
ah rackspace - https://github.com/thephpleague/flysystem-rackspace - anyway

**Comment by PVince81** [comment]
First step would anyway moving the parts that aren't storage backends to core: https://github.com/owncloud/core/issues/18160

**Comment by PVince81** [comment]
Yes, let's do that.

Not sure if we'll have enough time in the scope of 10.0, at least for not all of them.

Regarding Dropbox, we might want to wait until the API situation is solved: https://github.com/owncloud/core/issues/25969

**Comment by PVince81** [comment]
Moving to 10.0.1, I'd like to tackle a few of them until then

**Comment by PVince81** [comment]
Moving to triage for rescheduling. We should probably schedule individual backends as each might take 1-2md per backend depending on complexity.

**Comment by PVince81** [comment]
I suggest we start with S3 so we can do the Guzzle update in both the app and https://github.com/owncloud/core/pull/28063

**Comment by DeepDiver1975** [comment]
closing in favor of https://github.com/owncloud/core/issues/27049
