### ISSUE TITLE
Travis always red when not modifying dav app

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#20121]
```
The command "bash tests/travis/test_for_app.sh $APP" failed and exited with 1 during .
```
The above is intended in order to not waste travis time.
However, we actually would like it pass or not run at all, instead of error/fail.

Will have a look if there is a way around it

cc @DeepDiver1975

**Comment by DeepDiver1975** [comment]
Thx

**Comment by MorrisJobke** [comment]
I just also check for this. And it doesn't seem to be an easy way. I thought of a global variable that needs to be checked in each script and then simply exits with 0.

**Comment by nickvergessen** [comment]
I made a similar approach: https://github.com/owncloud/core/issues/20134

I output 1 or 0 in a script when the app was changed or not and store the result in a variable.

then for each script call in `.travis.yml` I check if the var is 1 or 0
