### ISSUE TITLE
Error Messages after upgrade from OC to 8.2.0

### ISSUE THREAD

**Issue by h-2** [owncloud/core#20125]
I am seeing the same issue as in #18224, i.e.
```
Unable to generate a URL for the named route "calendar_index" as such route does not exist.
```
 but when trying to upgrade calender and contacts apps after upgrade to 8.2.0. Repeatedly pressing the button does not help. `./occ upgrade` won't do anything because it says that owncloud is up to date.

Anything I can do?

**Comment by h-2** [comment]
After copying around some files and using chrome instead of Firefox to access the web-interface it actually worked -.-

**Comment by RealRancor** [comment]
Hi,

very likely a dup of the still open issue here: https://github.com/owncloud/core/issues/19145
