### ISSUE TITLE
Share API must not return invalid shares that have a non-existing parent

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#20131]
In some rare cases in OC7, bugs might have generated share entries where the parent was deleted but not the children.

### Steps to reproduce:

1. Create two users "user1" and "user2"
1. Login as "user1"
1. Create a folder "test"
1. Share "test" with "user2"
1. Login as "user2"
1. Share "test" with link
1. In the database, delete the parent link entry
1. Go to "Shared with link" section

![dirname-error](https://cloud.githubusercontent.com/assets/277525/10811998/0ea17af4-7e12-11e5-8b14-504284a2954b.png)

### Versions
OC 7.0.10, 8.0.6, 8.1.4RC1

The share API should not return such entries at all. Currently it returns invalid entries that are missing the "path" attribute and possibly others, this breaks the web UI and might break other apps as well.

Note: a repair step https://github.com/owncloud/core/issues/20130 will clean these up, but we still need the code to be able to survive such cases.

@rullzer @nickvergessen @schiesbn @MorrisJobke

**Comment by PVince81** [comment]
CC @cmonteroluque @DeepDiver1975 @karlitschek for the milestone assignment.
This would technically resolve a blue ticket, but as we cannot backport to OC 7 it would only prevent such issues to happen in the future.

**Comment by nickvergessen** [comment]
Yeah, sounds like "save programming" to do a little `isset()` check before using the item itself?

**Comment by rullzer** [comment]
Let me take case of this when I move fetching shares over to the new share manager.

**Comment by rullzer** [comment]
This should be fixed in master now. As there are no parents with the new resharing behaviour (only for specific group shares but they should never be returned alone)...
