### ISSUE TITLE
Show quota for subadmins as text and not as dropdown

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#20139]
Subadmins cannot change the system-wide default quota, so the field doesn't work:

![subadmin-default-quota](https://cloud.githubusercontent.com/assets/277525/10815036/d164f96e-7e29-11e5-8d81-82f0e1e84715.png)

I suggest to simply hide that field when the current user is not an admin (but only a subadmin).

Observed in OC 9.0 pre-alpha / master (f428d31a5d1f91c6e7aa96fd8550c75c02cc0963)

Should hopefully be easy, tagging as junior job

@jancborchardt @MorrisJobke @LukasReschke

**Comment by jancborchardt** [comment]
Yeah, good call to just not show it.

**Comment by jancborchardt** [comment]
Also – @Henni an instance of checkboxes which need to be styled. ;)

**Comment by prastut** [comment]
Is this present in the users > quota ?
![fireshot capture 16 - users - owncloud - http___localhost_core_index php_settings_users](https://cloud.githubusercontent.com/assets/10279686/13457399/0ce461f2-e08e-11e5-8a6b-79cf15a65c7a.png)

If not can you guide me where this is present and how to go about this issue?

**Comment by MorrisJobke** [comment]
> If not can you guide me where this is present and how to go about this issue?

There is a little gear icon in the lower left of the sidebar - click it ;)

**Comment by prastut** [comment]
@MorrisJobke It only shows the WebDAV field.

**Comment by MorrisJobke** [comment]
> @MorrisJobke It only shows the WebDAV field.

In the user management ;)

**Comment by prastut** [comment]
Ahaa. My bad. Thanks @MorrisJobke. Also how can I connect with you?

**Comment by prastut** [comment]
Doubts:
* I understand that we don't have to display system-wide default quota for subadmin. Generally I think there are 3 types of users (Correct me if I am wrong)
  * Admin [1]
  * SubAdmin (which are like admins of some group) [2]
  * Users [3]

Since the "User" interface is only visible for user type [1] & [2], can I just hide the default quota if the user is not of type [1]? 

Otherwise if you do want to write a specific case I was trying out the following:

```
<?php if((bool) !$_['isAdmin']): ?>
	<?php if((bool)!$_['isSubAdmin']): ?>
		<select class='quota' disabled="disabled">
			<option selected="selected">
				<?php p($_['default_quota']);?>
			</option>
		</select>
	<?php endif; ?>
<?php endif; ?>

```
This code doesn't seem to work. I did find instances of isSubAdmin being used in various parts of the code therefore was trying to use it.

**Comment by MorrisJobke** [comment]
> This code doesn't seem to work. I did find instances of isSubAdmin being used in various parts of the code therefore was trying to use it.

The isAdmin is defined here: https://github.com/owncloud/core/blob/933f60e3147ad872acf3211dc826ebf528434681/settings/users.php#L113-L113 with the variable itself is defined here: https://github.com/owncloud/core/blob/933f60e3147ad872acf3211dc826ebf528434681/settings/users.php#L59-L59

Something similar needs to be done for the subadmin variable ;)

**Comment by prastut** [comment]
I wish to use  [isSubAdmin function](https://github.com/owncloud/core/blob/933f60e3147ad872acf3211dc826ebf528434681/lib/private/subadmin.php#L214-L234)

This function belongs to SubAdmin class. How to invoke the subAdmin class like the OC_User class? PHP log gives me an error saying SubAdmin class undefined, when I am trying to use the following code:

`$isSubAdmin = SubAdmin::isSubAdmin(OC_User::getUser());`

**Comment by MorrisJobke** [comment]
> $isSubAdmin = SubAdmin::isSubAdmin(OC_User::getUser());

This should do the trick:

```
OC_SubAdmin::isSubAdmin(OC_User::getUser());
```

**Comment by prastut** [comment]
@MorrisJobke Doesn't work. Still getting the following error
`PHP Fatal error:  Class 'OC_SubAdmin' not found in /var/www/html/core/settings/users.php`

I couldn't find the class OC_SubAdmin too. There's a [class SubAdmin](https://github.com/owncloud/core/blob/933f60e3147ad872acf3211dc826ebf528434681/lib/private/subadmin.php#L36) though

**Comment by MorrisJobke** [comment]
> I couldn't find the class OC_SubAdmin too. There's a class SubAdmin though

Sorry. I was on an older version. 

``
\OC::$server->getGroupManager()->getSubAdmin()->isSubAdmin(\OC::$server->getUserSession()->getUser());
```

But you could also rely on the fact that this page could only accessed by admins or subadmins. Then if `$isAdmin` is `false` it needs to be a subadmin ;)

**Comment by prastut** [comment]
Yes. That's what I was confirming 6 comments above. (Is there any way to link a comment in Github)

> * I understand that we don't have to display system-wide default quota for subadmin. Generally I think there are 3 types of users (Correct me if I am wrong)
  * Admin [1]
  * SubAdmin (which are like admins of some group) [2]
  * Users [3]

> Since the "User" interface is only visible for user type [1] & [2], can I just hide the default quota if the user is not of type [1]? 

Will create a PR now ;)

**Comment by MorrisJobke** [comment]
> (Is there any way to link a comment in Github)

Click on the time stamp of the comment and then use the URL ;)

**Comment by prastut** [comment]
@MorrisJobke ;)

**Comment by MorrisJobke** [comment]
> I suggest to simply hide that field when the current user is not an admin (but only a subadmin).

I would propose to not hide it completely but show it as text only - otherwise a subadmin doesn't know what the current default size is.

cc @owncloud/designers

**Comment by jancborchardt** [comment]
@MorrisJobke yeah, instead of a dropdown it should be plain text. e.g.:

> Default quota: none

**Comment by prastut** [comment]
@jancborchardt Then this issue becomes invalid right?

**Comment by MorrisJobke** [comment]
> @jancborchardt Then this issue becomes invalid right?

Not really, but adjusted.
