### ISSUE TITLE
Repair step: delete shares where the parent doesn't exist any more

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#20130]
In some rare cases in OC7, bugs might have generated share entries where the parent was deleted but not the children.

### Steps to reproduce:

1. Create two users "user1" and "user2"
1. Login as "user1"
1. Create a folder "test"
1. Share "test" with "user2"
1. Login as "user2"
1. Share "test" with link
1. In the database, delete the parent link entry
1. Go to "Shared with link" section

![dirname-error](https://cloud.githubusercontent.com/assets/277525/10811998/0ea17af4-7e12-11e5-8b14-504284a2954b.png)

### Versions
OC 7.0.10, 8.0.6, 8.1.4RC1

A repair step should be written that deletes any `oc_share` entry where the parent does not exist any more.

@rullzer @nickvergessen @schiesbn @MorrisJobke

**Comment by nickvergessen** [comment]
Already implemented in https://github.com/owncloud/core/pull/19871

Feel free to review
