### ISSUE TITLE
Multiselect with shift key outside checkbox selects wrong items

### ISSUE THREAD

**Issue by pellaeon** [owncloud/core#20145]
1. Select an item A using checkbox
2. Deselect item A
3. Select item B above A by clicking white area (not the checkbox)
4. Hold shift and click item C (below A) by clicking white area
5. ownCloud checkbox selects item A+1 to C

Expected: item B to C are selected

What is the purpose of grey selected background and checkbox ? They are the 2 ways of selecting items, and are confusing, there should only be one (personally I prefer grey background select), or at least they should always be in sync.

Related: #15157

**Comment by MorrisJobke** [comment]
cc @owncloud/designers

**Comment by jancborchardt** [comment]
Well, of course it should select correctly. ;) @MorrisJobke @PVince81 JS issue I guess?

**Comment by PVince81** [comment]
Yes, shift select is buggy, see https://github.com/owncloud/core/issues/15157#issuecomment-92953470

**Comment by PVince81** [comment]
Closing in favor of general files app keyboard issue ticket: https://github.com/owncloud/core/issues/27580
