### ISSUE TITLE
Empty package

### ISSUE THREAD

**Issue by roberthr74** [owncloud/core#20168]
Latest Debian package as of today is without binary file.

**Comment by RealRancor** [comment]
Already reported here: https://github.com/owncloud/client/issues/4041

Btw. please also have a look at the "guidelines for contributing" linked in the yellow box when creating a new issue:

https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

This shows you that this is the issue tracker of the ownCloud core part where you can find the issue tracker for the client here:

https://github.com/owncloud/client/issues
