### ISSUE TITLE
Keep search input open if search is in action

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#20165]
* type something in the search field
* press enter
* wait for search results

## actual
* search input is cleared and collapsed

## expected
* search input should stay expanded to show the search term
* clear search term on browsing away -> which also closes the search input to the default appearance

ref https://github.com/owncloud/core/pull/18573#issuecomment-134893360

**Comment by MorrisJobke** [comment]
cc @Henni @pellaeon Maybe one of you is interested in this ;)

**Comment by pellaeon** [comment]
I can't reproduce this. I'm on current master.

**Comment by Henni** [comment]
I also can't reproduce this. Works as expected in files, apps, and users view.

**Comment by MorrisJobke** [comment]
Once the input looses focus it is hidden. I would say it should stay open, because it is still filled with the search term. That would also be a proper indicator, that it is currently a search.
