### ISSUE TITLE
Client Sync in Continuous Sync Mode Deleting Files from Server after Version 8.2 Upgrade

### ISSUE THREAD

**Issue by shinshuri** [owncloud/core#20164]
This issue was originally posted as a bug in Owncloud/Client, but was requested to post issue in 'owncloud core' Bug Tracker. Here is the link to the original post:

https://github.com/owncloud/client/issues/3973

This is persistent and we are unable to use our clients Mac and Windows. With the amount of data on our owncloud server using the browser is way to inefficient. Can we get a resolution on this quickly? 

Any help is appreciated.

Thanks,
Shinshuri

**Comment by RealRancor** [comment]
@shinshuri It might be useful to fill out the issue template as asked here (linked in the yellow box when creating an issue): https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version

This provides the mandatory info about your environment.

**Comment by PVince81** [comment]
Database is locked issue: https://github.com/owncloud/client/issues/3973#issuecomment-151668502

But probably not related to the original issue.

@shinshuri while filling the issue template with steps and logs https://raw.githubusercontent.com/owncloud/core/master/issue_template.md, can you also clarify what you mean with "shares". Are these "local filesystem mounts", "external storage mounts from OC's external storage app" or "OC shares that were created in the OC web UI". (assuming that all share related things you mention are on the server, not the client)

**Comment by PVince81** [comment]
A fix for the "oc_file_locks" issue, please use a redis server for file locking, see https://doc.owncloud.org/server/8.2/admin_manual/configuration_files/files_locking_transactional.html

By default it uses a database-based locking which is much slower. As I understand you seem to be having a system with many users, so it's best to switch to redis. This should increase performance. Not sure if this will fix the slow PROPFIND issue and deletion (which could be completely separate and unrelated issues)

**Comment by shinshuri** [comment]
@PVince81 When I mention shares it is any shares I have given to others made from the owncloud web interface (server) or my local disk.

Regarding your second comment, what is redis?  How do I get access to it or have it available for use? I need more information about redis, what it is , and how to use it?

I am working on completing the issue template. When I click the link it takes me to a file that displays as plain text in the browser. Should I respond with a text file with my responses for the issue template? The file extension on the above link is .md not sure I can create a .md file. Is it an available file extension in a word processing program like MS Word?

**Comment by RealRancor** [comment]
@shinshuri Have you even clicked on the link posted above? This contains all needed info about redis.

For the issue template just copy the content of the file https://raw.githubusercontent.com/owncloud/core/master/issue_template.md into the comment field here and full out all asked stuff.

**Comment by shinshuri** [comment]
Thanks I will get this handled with our IT department then I will respond with the issue template.

**Comment by shinshuri** [comment]
Hi:
Here are the responses for the issue template. I received this back from the IT Host Tech Team. Not all fields were completed but this is what I have plus a written explanation of possible issues with installing PHP 5.5+, APCu, and Redis. See explanation directly below. Issue template pasted after Tech Team note.

EXPLANATION FROM HOSTING TECH TEAM REGARDING REDIS, PHP 5.5+, and APCu

"Your requests are not compatible with your current server setup, which is running PHP with the suPHP handler which is the standard setup we run. The changes you want such as APCu and Redis will NOT work with the suPHP handler and will cause issues. These issues will range can range from broken scripts to WordPress no longer allowing automatic updates.

Since these packages are not part of our standard configuration, please confirm you are willing to accept these risks before I allow our staff to proceed."


![scloud_snapshot](https://cloud.githubusercontent.com/assets/13647535/10896653/20c75cce-8170-11e5-999c-fb88328da6ac.png)

------------------------------------------------Beginning of Issue Template----------------------------------------

### Steps to reproduce
1. Host installed owncloud version 8.2 from an upgrade 
2. I and my staff had our clients syncing to the server
3. The sync process stayed in discovery mode for 4-5 days then started deleting some files. Not all files.
4. current owncloud version admin area in web browser interface currently show the errors. (See attached file screen image)

### Expected behaviour
 We should have a smooth syncing of files that are shared between users without a delay in file detection and sync transfer.

### Actual behaviour
Sync processing search mode for multiple days then transfers and deletes happen simultaneously very solw. We have lost over 25 GB of data from the data share folder. Behavior is rather erratic. 

### Server configuration
**Operating system**: CentOS release 6.7 (Final)

**Web server:** Apache/2.2.31 (Unix)

**Database:** MySQL 5.1.73

**PHP version:** PHP 5.4.43

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**

**List of activated apps:**
Set-Cookie: ocrfl89s2w24=ce016a7ce71cbdc948af016cb3c46732; path=/; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Set-Cookie: oc_sessionPassphrase=bORLJScsuvYRcYEZ5W0mEo8chaAmwzfOJVZPyCAW/8nkjww3WHc4M231jPI/qoc3WwqtWKY/Tf2SszMOFeIvdgVuhR/p/v53Kz7tBM86g5xp7PKkQUEyIW45kiLLCaoR; path=/; httponly
Content-Security-Policy:default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: Sameorigin
X-Robots-Tag: none
Content-type: text/html; charset=UTF-8

```


**The content of config/config.php:**


```
<?php
$CONFIG = array (
'instanceid' => 'ocrfl89s2w24',
'passwordsalt' => 'xxxxxxxxxxxxxxxxxxxxxxxx',
'secret' => 'xxxxxxxxxxxxxxxxxx',
'trusted_domains' =>
array (
0 => 'shinshuri.com',
1 => 'www.shinshuri.com',
2 => 'scloud.shinshuri.com',
3 => 'www.scloud.shinshuri.com',
),
'datadirectory' => '/home/shinshur/public_html/owncloud/data',
'overwrite.cli.url' => 'http://shinshuri.com/owncloud',
'dbtype' => 'sqlite3',
'version' => '8.2.0.12',
'installed' => true,
'theme' => 'shinshuri',
'maintenance' => false,
'check_for_working_webdav' => false,
'loglevel' => 0,
'trashbin_retention_obligation' => 'auto',

);

```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

#### LDAP configuration (delete this part if not used)

```
On ownCloud 7+ with access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

On ownCloud 6 with access to your command line run e.g.:
sqlite3 data/owncloud.db or mysql -u root -p owncloud
then execute: select * from oc_appconfig where appid='user_ldap';

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query above.

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
```
There is no specific error logs with owncloud
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
est::getPathInfo() at \/home\/shinshur\/public_html\/owncloud\/remote.php#91","level":3,"time":"2015-10-20^CT08:53:32+00:00"}
{"reqId":"56fae037518d50e1d1c9e521129f7bd8","remoteAddr":"98.238.178.246","app":"PHP","message":"Call to undefined method OC\\AppFramework\\Http\\Request::getPathInfo() at \/home\/shinshur\/public_html\/owncloud\/remote.php#91","level":3,"time":"2015-10-20T08:53:49+00:00"}
{"reqId":"56229872e41be57e7c4a82fbc475a860","remoteAddr":"98.238.178.246","app":"PHP","message":"Call to undefined method OC\\AppFramework\\Http\\Request::getPathInfo() at \/home\/shinshur\/public_html\/owncloud\/remote.php#91","level":3,"time":"2015-10-20T08:54:02+00:00"}
{"reqId":"7df399d7214181656b9d5d5335c586fa","remoteAddr":"98.238.178.246","app":"PHP","message":"Call to undefined method OC\\AppFramework\\Http\\Request::getPathInfo() at \/home\/shinshur\/public_html\/owncloud\/remote.php#91","level":3,"time":
#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
------------------------------------------------End of Issue Template--------------------------------------------

**Comment by shinshuri** [comment]
Will I be able to use version 8.2 stable version since It appears I may not be able to install PHP 5.5+ and APCu? If not, what is the possible solution for us with the server configuration we have?

Thanks,
Shinshuri

**Comment by shinshuri** [comment]
Hello. I'm still waiting for a response regarding this issue. I'd appreciate any information and support.

**Comment by shinshuri** [comment]
We did more research on our server regarding transactional file locking to install the right additional scripts to support Owncloud. I received this response back from our IT Host. 

"redis PHP module which is available on your server at the moment. ownCloud’s new transactional file locking mechanism require Redis server (Daemon) and redis PHP module for the file locking to work. Please note that this is something categorically not supported by cPanel and may cause issues. Please look into this with your developer and then get back to us with a confirmation on the install and a maintenance time so that we can get this sorted."

To fix our current issue I need a response back from someone regarding the initial comment on this ticket about resolving the Transactional File Locking issue. Can someone please respond to me on this ticket so we can work through our issue and get it resolved?

**Comment by PVince81** [comment]
If you cannot use redis you might want to update to 8.2.0 then. That version also has a database based locking instead of redis. The locking is enabled by default in that version and should ensure better data integrity. However, note database locking is much slower than redis based locking.

Additionally 8.2.0's database locking performance has been improved in the 8.2.1 version.

**Comment by PVince81** [comment]
Thanks for the detailed infos. I just noticed that you are using SQLite.
It is highly recommended to switch to MySQL or PostgreSQL in environments with a lot of data/users and concurrency. There is a tool to convert the database: https://doc.owncloud.org/server/8.1/admin_manual/configuration_database/db_conversion.html

**Comment by PVince81** [comment]
I'd suggest you to try converting the database first before attempting to enable locking. That might already help with your issues.

**Comment by shinshuri** [comment]
@PVince81 thank you for your follow up feedback. We have already had our IT Host convert the PHP Handler from suPHP to fastcgi and we have fixed the Transactional File Locking using the documentation link supplied earlier in this post so redis, APCu, and Memcache are all configured on our server. If we convert the dabade to MySQL, will that create an issue with our current configuration and will we loose any data in the process? I want to make sure we don't have any issues with the conversion of the database.

**Comment by PVince81** [comment]
You shouldn't lose any data by converting the database with the command I mentioned above.

**Comment by MorrisJobke** [comment]
Issue seems to be resolved - please reopen if not.
