### ISSUE TITLE
Download: Signature files with an expired key! (Pls. update the signature with a non-expired key!)

### ISSUE THREAD

**Issue by Wikinaut** [owncloud/core#20162]
Pls. update the signature with a non-expired key!

```
gpg --verify owncloud-8.2.0.tar.bz2.asc
gpg: Signature made Mo 19 Okt 2015 15:29:31 CEST using RSA key ID F6978A26
gpg: Good signature from "ownCloud <info@owncloud.com>"
gpg: Note: This key has expired!
Primary key fingerprint: E303 6906 AD9F 3080 7351  FAC3 2D5D 5E97 F697 8A2
```

**Comment by RealRancor** [comment]
@Wikinaut Works for me like expected when following the correct steps provided at:

https://doc.owncloud.org/server/8.2/admin_manual/installation/source_installation.html#example-installation-on-ubuntu-14-04-lts-server

```
wget https://download.owncloud.org/community/owncloud-8.2.0.tar.bz2.asc
wget https://download.owncloud.org/community/owncloud-8.2.0.tar.bz2
wget https://www.owncloud.org/owncloud.asc
gpg --import owncloud.asc

gpg --verify owncloud-8.2.0.tar.bz2.asc owncloud-8.2.0.tar.bz2
gpg: Signature made Mo 19 Okt 2015 15:29:31 CEST using RSA key ID F6978A26
gpg: Good signature from "ownCloud <info@owncloud.com>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: E303 6906 AD9F 3080 7351  FAC3 2D5D 5E97 F697 8A26
```

Seems you have missed some steps or you have not imported the updated owncloud.asc and the old one of you expired.

**Comment by Wikinaut** [comment]
ok, you are right. I did not import the new key. Done now, works.

Tip:

```gpg --with-fingerprint owncloud.asc```

prints the fingerprint of the key without actually importing it. In that way one can check the fingerprint before actually importing it.
