### ISSUE TITLE
Dropping a droppable item on overlapping breadcrumb and folder moves it into the folder and shows an error "item is locked"

### ISSUE THREAD

**Issue by pellaeon** [owncloud/core#20161]
I discovered this when developing #20150 , when breadcrumb overlaps with a folder, dropping an item over breadcrumb would move the item inside that folder, and shows an error "item is locked".
![2](https://cloud.githubusercontent.com/assets/916913/10826804/7818596e-7ea6-11e5-8f4c-8453b2ea3ede.png)
You see the long yellow highlight, that is the file's `td` highlighted, while the home icon is also highlighted, that means both elements detect the droppable item hovering over them, where there should be only the top (by z-index) one that receives.

![3](https://cloud.githubusercontent.com/assets/916913/10826856/a84abc4e-7ea6-11e5-8ad4-cd986cb5e548.png)
If I drop the item, it is moved inside that folder, and shows an error.

**Expected**: item should be moved to Home, the drop target with larger z-index.

This is a known wontfix for jquery-ui: http://bugs.jqueryui.com/ticket/3452
There is a fix (not tested): https://github.com/vaceta/jquery-top-droppable

**Comment by PVince81** [comment]
Argh, nice find. Looks like a twisted situation.

**Comment by PVince81** [comment]
Do you know which one of both event handlers is getting the event first ? Maybe the breadcrumb drop can cancel the event (preventDefault or something) to prevent it reaching the folder element ?

**Comment by MorrisJobke** [comment]
#22341 was merged
