### ISSUE TITLE
"unshare" action should be called "unshare" in the action menu and not "delete"

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#20172]
In the actions menu of the "Shared with you" file list the "delete" action should be called "unshare" because that is what it actually does. Same problem exists in the normal files list.

Affected versions: ownCloud 8.2 and later

cc @PVince81 @jancborchardt

**Comment by PVince81** [comment]
Correct. It got lost when moving the actions to the menu and cleaning up the action registration code (removed all hacks)

It might be possible to de-register the delete action in that list and register a new delete action with a different label.

**Comment by jancborchardt** [comment]
Adding backport-request because this should probably be fixed in 8.2 then too, right?

**Comment by karlitschek** [comment]
Agreed. Important to do right. please backport :+1:

**Comment by PVince81** [comment]
Some ideas to make this work without hacks: make it possible to pass a function as `FileAction.displayName`. If it's a function, whenever the menu is rendered it will call the function and pass a "FileActionContext". This way the function can compute the display name based on whatever the current file is (regular, shared with you, etc)

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/21153
