### ISSUE TITLE
OC_AppConfig hook isn't present anymore

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#20179]
It is used in the sharing helper:

https://github.com/owncloud/core/blob/d6b2b877bcb5c9d0749d6836f1f7f51ff0977f11/apps/files_sharing/lib/helper.php#L39

Then also the Sharing Hook listener isn't needed anymore: https://github.com/owncloud/core/blob/d6b2b877bcb5c9d0749d6836f1f7f51ff0977f11/apps/files_sharing/lib/maintainer.php

The hook emitter was removed with 7.0.0: https://github.com/owncloud/core/pull/4624/files#diff-21567a3c046dfd9774fda2f94e13d1cfL164

Maybe this is the reason for some orphaned shares? Should we introduce this again or simply delete this code, that is never executed since 7.0.0 and rely on the fact that link shares are not shown anymore when this setting is disabled but reside in place. (I just checked with current master and also the public link page is blocked)

I would simply delete this. @schiesbn @PVince81 @rullzer Opinions?

I would also take care of creating the PR if this is wanted.

**Comment by MorrisJobke** [comment]
also @DeepDiver1975

**Comment by DeepDiver1975** [comment]
> Maybe this is the reason for some orphaned shares?

Not that I can think of - this code simply removed public link shares in case the admin is turning off this feature. Really what ownCloud can do :wink: 

Is that really a scenario we need to take care of online?
maybe we add this to the orphan job?

**Comment by MorrisJobke** [comment]
> maybe we add this to the orphan job?

We don't do this at all. We simply forbid to access it and simulate that there are no link shares (in the users view and once you browse the link). But the entries reside in the DB. That is what I noticed during testing this on master today.

**Comment by DeepDiver1975** [comment]
> But the entries reside in the DB.

this was exactly my suggestion above: add this cleanup step to the orphan job.

so as soon as public link sharing is disbaled the job can cleanup the db

**Comment by MorrisJobke** [comment]
> so as soon as public link sharing is disbaled the job can cleanup the db

Roger

**Comment by DeepDiver1975** [comment]
the need for this is still questionable ... my assumption would be that one either has this setting enabled or disabled

so let's first cleanup the code and kill all the dead pieces \o/

**Comment by schiesbn** [comment]
> so as soon as public link sharing is disbaled the job can cleanup the db

not sure if this is really needed. You could also see it as a feature that if you enable link sharing again that the old links are back again.

Sharing 2.0 will change anything a lot, no need to try to fix this separately. I would just add a comment "FIXME: No longer needed, see #20179", so that  @rullzer and I get remembered when we touch the code during the sharing 2.0 development.

**Comment by PVince81** [comment]
the sharing helper is dead
