### ISSUE TITLE
Truncate very small files on download / sync

### ISSUE THREAD

**Issue by Danamir** [owncloud/core#20174]
Hello, I got a bug with my instance of owncloud when downloading very small text files from the server, or synchronizing with the client, those file are truncated.

**Server version**: ownCloud 8.1.1 on a shared server (web based setup, no command line)
**Client version**: 2.0.2 (build 5569) Windows 10 Pro 64-bits

An example of file is a one-line txt file containing an ip, or a file containing a residential group key.

The file is correctly displayed when using the web interface on the server, but truncated to 2 bytes in one case, and 0 bytes in the other when downloading.

**Comment by karlitschek** [comment]
Please post a full bug report using the issue template. Thanks a lot

**Comment by Danamir** [comment]
### Steps to reproduce
1. Upload or synchronize a very small text file to owncloud. ie. file containing a single ip, or a residential group key . Single line, and size < 15 bytes.
2. Download file via owncloud web page, or synchronize via windows client.

### Expected behaviour
Should obtain the same file that is stored on the server.

### Actual behaviour
Gets a two-bytes file with only the beginning of the file, or an empty file.

### Server configuration
**Operating system**: 

**Web server:** OVH shared web server.

**Database:** MySQL v5.5

**PHP version:** PHP v5.4

**ownCloud version:** ownCloud 8.1.1 (stable) Note that the admin interface says it's up-to-date, but the last owncloud server seems to be 8.2.0 ...

**Updated from an older ownCloud or fresh install:** Updated from older . The installation was done with the web installer.

**List of activated apps:**

```
Activity  2.0.1
Deleted files  0.6.3
External storage support  0.2.3
First Run Wizard  1.1
Mail Template Editor  0.1
PDF Viewer  0.7
Pictures  0.6.0
Share Files  0.6.2
Text Editor  0.4
Updater  0.6
Versions  1.0.6
Video Viewer  0.1.3
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'ocd5f176172b',
  'passwordsalt' => '...',
  'trusted_domains' =>
  array (
    0 => 'www.danamir.com',
    1 => 'cloud.danamir.com',
  ),
  'datadirectory' => '/home/danamir/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'dbname' => 'danamir',
  'dbhost' => 'danamir.mysql.db',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'danamir',
  'dbpassword' => '...',
  'installed' => true,
  'check_for_working_webdav' => false,
  'default_language' => 'en',
  'theme' => '',
  'maintenance' => false,
  'loglevel' => '0',
  'secret' => '...',
  'mail_from_address' => 'danamir',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'danamir.com',
);
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** MozillaFirefox v41.0.2 , Google Chrome v46.0.2490.80 m

**Operating system:** Windows 10 Pro 64-bits

### Logs
#### Web server error log
```
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"VjOJHgoAX8gAADyTc3cAAAB@","remoteAddr":"152.77.66.142","app":"core","message":"Generating preview for \"\/documents\/Citadel\/ip.txt\" with \"OC\\Preview\\TXT\"","level":0,"time":"2015-10-30T15:13:34+00:00","method":"GET","url":"\/index.php\/core\/preview.png?file=%2Fdocuments%2FCitadel%2Fip.txt&c=0d25086e8eaba45027bb32c994c23c2d&x=36&y=36&forceIcon=0"}
```

#### Browser log
```
The download action produces no network log in FireBug, it just launches the download.
```

**Comment by Danamir** [comment]
I just saw that my server is not correctly proposing to upgrade to 8.2, or even 8.1.3 . Maybe i'll try to upgrade it by hand without loosing my database or files. Still pretty tricky without command line.

**Comment by PVince81** [comment]
@Danamir very strange. I don't see anything wrong with your config.

Is the truncated file always truncated the same way, or does its size change randomly when trying to download it several times ?

**Comment by Danamir** [comment]
It's always the same file size that is downloaded, regardless of the file line number.

Here is a screenshot of the result of various txt files uploaded then downloaded. The size varies from "size minus 11 bytes", except for the 25 bytes file that is downloaded as "size minus 12 bytes". At 26 bytes and greater, the files are allright.

![downloaded](https://cloud.githubusercontent.com/assets/15424198/10883971/b87e7c0a-8175-11e5-9eb6-d0e69c692fac.png)

It could still be a problem of php configuration since the installation is on a shared web server and I do not have full access to the environment variables. But the same files downloaded directly from the apache server are ok.

**Comment by PVince81** [comment]
It is very likely that something is wrong in your (or your shared hosters) environment. Maybe some PHP module or setting is disturbing the file transfer.

**Comment by Danamir** [comment]
The strange thing is that those file were fine some months ago. Sadly I did not have to lookup my ip file for some time, so I don't now exactly when. But you are right, it could be a change on the shared hoster side.

**Comment by PVince81** [comment]
Have you tried looking at the forums whether other people on OVH had similar issues ?
See http://owncloud.org/support

This problem is very unlikely to be a bug in ownCloud, there is no special handling for such small files. Maybe OVH or some PHP module is messing with the file contents.

**Comment by Danamir** [comment]
Hello,

I changed my OVH hosting plan from a mutualized server to a VPS, and 
done a fresh install of owncloud. No more problems since.

Thanks for the followup.
