### ISSUE TITLE
Failed login Log entry format

### ISSUE THREAD

**Issue by barscm** [owncloud/core#20182]
Can we find a better way to manage log entries?

The "/lib/private/user/manager.php" file was updated in Feburary, and a bug introduced which meant that failed login log entries gave an IP address with a missing "'",

e.g. '1.1.1.1, instead of '1.1.1.1'

This broke my fail2ban jail pattern, and therefore any brute force attempts on my box from Feburary to This month (when the bug was fixed) would not have been prevented.

Perhaps we could maintain an up to date regular expression in the README to use with programs such as fail2ban. For example, I am using the simple yet not fool-proof:

.\*remoteAddr.\*":"\<HOST\>".\*Login failed:.\*

Or perhaps updates to the security related files such as this could be highlighted with each release, so Admins can retest.

Please correct me if I have missed a test script or something which would have caught this.

**Comment by RealRancor** [comment]
@barscm 
This pattern was only fixed with oC 8.2 and the changed regex is also documented within the release notes of oC 8.2:

https://doc.owncloud.org/server/8.2/admin_manual/release_notes.html

**Comment by barscm** [comment]
Perfect. Thanks RealRancor. I apologise for not reading properly.

**Comment by RealRancor** [comment]
@barscm 
Sorry, had updated my post afterwards as the pointer to the release notes where wrong. I thought you havn't noticed the bugfix from '1.1.1.1 to '1.1.1.1'. Only this is described in the release notes, not the bug before which got fixed by oC 8.2.0.
