### ISSUE TITLE
File version tree for Education

### ISSUE THREAD

**Issue by SebCanet** [owncloud/core#20183]
Hi,
I read some of issues about version in onwcloud, and way to see it.
But I would like to use owncloud with any debutant teacher in collaborating goal, and owncloud has a lack in viewing the different file. I'm a french STEM teacher and national coach.

I explain : using Github, you can access to different version of file, like this
https://github.com/technologiescollege/mBlock-languages/network
and we would like to see version of directories or file the same way in owncloud.

Why ? Because when someone has created a very goo activity to learn, by example, to code and has created this for his 12 years old pupills, I could take this, change things for my 10 years old pupills, and save it like a version in owncloud.

I hope nobody already asked it, thanks a lot for answering.
Thanks for this great project.
Sebastien

**Comment by karlitschek** [comment]
Please ask your question in the forum at forum.owncloud.org
Thanks

**Comment by SebCanet** [comment]
I think it was an issue discussion...ok I'll do it.

**Comment by RealRancor** [comment]
@karlitschek You might want to re-open this. For me this looks like a feature request for the files_version app.

The user requested a new possibility to access file versions besides the existing versions dropdown menu. There is nothing what we can do about this at the forums.

**Comment by SebCanet** [comment]
Thansk, I didn't know where to post it...but that's really a new feature based upon actual file_version app.

**Comment by RealRancor** [comment]
@SebCanet If no one is re-opening here you might want to create a new issue stating clearly that this is a feature request for the files_version app.
