### ISSUE TITLE
ownCloud Error - Exception: Please upload the ca-bundle.crt file into the 'config' directory.

### ISSUE THREAD

**Issue by SlinkMink** [owncloud/core#20190]
Whilst updating to v8.1.3
Exception: Please upload the ca-bundle.crt file into the 'config' directory.
Can anyone assist with this ownCloud error please

Thank you

**Comment by RealRancor** [comment]
Dup of https://github.com/owncloud/core/issues/19805, https://github.com/owncloud/core/issues/19669, https://github.com/owncloud/core/issues/19551, https://github.com/owncloud/core/issues/20086 and some more.

The message itself is telling you what to do. If stuck also see this comment https://github.com/owncloud/core/issues/20086#issuecomment-151547507
