### ISSUE TITLE
Admin panel incorrectly warns about data/.htaccess not working

### ISSUE THREAD

**Issue by RalfJung** [owncloud/core#20199]
When I open the admin panel, it tells me that my data directory would be available in public and the `.htaccess` file would not be working. However, when I actually try to access anything in the data directory (e.g., `/data/htaccesstest.txt`), then apache replies "Forbidden". So it seems that this is a false positive, but it still has me quite nervous. Can I be sure that the test is wrong here?

This is with ownCloud 8.2.0-2.1 on Debian Jessie.

**Comment by LukasReschke** [comment]
Could you fill out the issue template? THX.

https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by RealRancor** [comment]
Might be a dup of https://github.com/owncloud/core/issues/17652

**Comment by RalfJung** [comment]
oO reporting an issue here needs more fields filled out than applying for a license...

### Steps to reproduce
1. Go to the admin panel

### Expected behaviour
It shouldn't give me spurious warnings

### Actual behaviour
It warns me about my data directory being unprotected. As far as I can tell, that's just wrong.

### Server configuration
**Operating system**: Debian Jessie

**Web server:** Apache 2.4

**Database:** MySQL 5.5.46

**PHP version:** 5.6.14

**ownCloud version:** (see ownCloud admin page) 8.2

**Updated from an older ownCloud or fresh install:** Installed from deb packages

**List of activated apps:** none

**The content of config/config.php:**

(using that "config:list" thingy didn't work, it replies `The "--public" option does not exist.`)


```
$CONFIG = array (
  'instanceid' => 'oc83afe77c37',
  'trusted_domains' => 
  array (
    0 => 'oc.XXX',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.2.0.12',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'installed' => true,
  'forcessl' => true,
  'mail_from_address' => 'admins',
  'mail_smtpmode' => 'sendmail',
  'mail_smtpname' => 'XXX',
  'mail_domain' => 'XXX',
  'theme' => '',
  'maintenance' => false,
  'loglevel' => 2,
  'trashbin_retention_obligation' => 'auto',
);
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no (assuming you mean that "server-side encryption" switch. I am of course using HTTPS.)

**Are you using an external user-backend, if yes which one:** No

### Logs
#### Web server error log
```
[Sat Oct 31 15:05:40.627727 2015] [negotiation:error] [pid 7763:tid 140206061586176] [client 84.165.151.195:54692] AH00687: Negotiation: discovered file(s) matching request: /var/www/owncloud/settings/admin (None could be negotiated).
```

#### ownCloud log (data/owncloud.log)
Nothing appears here when the admin page is loaded

#### Browser log
You are kidding, right? This is a server-side issue.

**Comment by RalfJung** [comment]
Looking at the source code, it seems that the test is rejected if the file already exists while testing:

```
                // creating a test file
                $testFile = $config->getSystemValue('datadirectory', OC::$SERVERROOT . '/data') . '/' . $fileName;

                if (file_exists($testFile)) {// already running this test, possible recursive call
                        return false;
                }
```

The file seems to permanently exist on my system. I certainly didn't create it. Removing that file fixed the issue.
ownCloud should probably take some precautions to be able to get out of a permanent failure state again, in case that file happens to be around for longer than intended. Right now, it fails in rather scary ways, incorrectly telling admins all their users' data is publicly available. Let's hope nobody got a heart attack from this yet ;-)

**Comment by nickvergessen** [comment]
@LukasReschke should we write the timestamp into the file and check that in case of existance as a TTL?

**Comment by MorrisJobke** [comment]
Fix is in https://github.com/owncloud/core/pull/21479

**Comment by MorrisJobke** [comment]
Fix was reverted
