### ISSUE TITLE
The list of Users is not generating

### ISSUE THREAD

**Issue by ggujabidze** [owncloud/core#20194]
As LukasReschke suggested me from this thread: https://github.com/owncloud/core/pull/20191 I'm opening new Bug. Description is that, when I'm pushing on Users tab, list is not generating and nothing appears, just loading circle.

### Steps to reproduce
1. Just click on Users tab

### Expected behaviour
Should appear a large list of users (mostly ldap user but several local users also

### Actual behaviour
Nothing appears and circle is rotating infinitely

### Server configuration
**Operating system**:  CentOS Linux release 7.1.1503

**Web server:**  Apache/2.4.6

**Database:**  Ver 15.1 Distrib 5.5.44-MariaDB

**PHP version:**   PHP Version => 5.4.16

**ownCloud version:**   8.2.0.12

**Updated from an older ownCloud or fresh install:**   Updated from 8.0.3

**List of activated apps:**.

Enabled:
  - activity: 2.0.2
  - files: 1.1.10
  - files_pdfviewer: 0.7
  - files_sharing: 0.6.2
  - files_texteditor: 2.0
  - files_trashbin: 0.6.3
  - files_versions: 1.0.6
  - firstrunwizard: 1.1
  - gallery: 0.6.0
  - provisioning_api: 0.2
  - user_ldap: 0.6.1

**The content of config/config.php:**

"system": {
        "instanceid": "ocvkqnd40ojf",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
           "REMOVED BY ME"
        ],
        "datadirectory": "\/cloud",
        "overwrite.cli.url": ""REMOVED BY ME"",
        "dbtype": "mysql",
        "version": "8.2.0.12",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Asia\/Tbilisi",
        "installed": true,
        "default_language": "en",
        "defaultapp": "files",
        "allow_user_to_change_display_name": true,
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 900,
        "trashbin_retention_obligation": 30,
        "ldapIgnoreNamingRules": false,
        "enable_previews": true,
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "preview_max_scale_factor": 10,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\PDF"
        ],
        "maintenance": false,
        "singleuser": false,
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        },
        "asset-pipeline.enabled": true,
        "theme": "",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "owncloud",
        "mail_domain": ""REMOVED BY ME"",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.office365.com",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "check_for_working_htaccess": true,
        "loglevel": 2
    }

**Are you using encryption:**  NO

**Are you using an external user-backend, if yes which one:**  YES, I'm using Microsoft Active Directory

#### LDAP configuration

+-------------------------------+---------------------------------------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                                                           |
+-------------------------------+---------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                         |
| hasPagedResultSupport         |                                                                                                                           |
| homeFolderNamingRule          |                                                                                                                           |
| lastJpegPhotoLookup           | 0                                                                                                                         |
| ldapAgentName                 | CN=ldap,OU=System Users,DC=gcfund,DC=dc                                                                                   |
| ldapAgentPassword             | ***                                                                                                                       |
| ldapAttributesForGroupSearch  |                                                                                                                           |
| ldapAttributesForUserSearch   |                                                                                                                           |
| ldapBackupHost                | dc01.gcfund.dc                                                                                                            |
| ldapBackupPort                | 389                                                                                                                       |
| ldapBase                      | DC=gcfund,DC=dc                                                                                                           |
| ldapBaseGroups                | DC=gcfund,DC=dc                                                                                                           |
| ldapBaseUsers                 | DC=gcfund,DC=dc                                                                                                           |
| ldapCacheTTL                  | 600                                                                                                                       |
| ldapConfigurationActive       | 1                                                                                                                         |
| ldapEmailAttribute            | mail                                                                                                                      |
| ldapExperiencedAdmin          | 0                                                                                                                         |
| ldapExpertUUIDGroupAttr       |                                                                                                                           |
| ldapExpertUUIDUserAttr        |                                                                                                                           |
| ldapExpertUsernameAttr        | sAMAccountName                                                                                                            |
| ldapGroupDisplayName          | cn                                                                                                                        |
| ldapGroupFilter               |                                                                                                                           |
| ldapGroupFilterGroups         |                                                                                                                           |
| ldapGroupFilterMode           | 0                                                                                                                         |
| ldapGroupFilterObjectclass    |                                                                                                                           |
| ldapGroupMemberAssocAttr      | member                                                                                                                    |
| ldapHost                      | gcf-r2.gcfund.dc                                                                                                          |
| ldapIgnoreNamingRules         |                                                                                                                           |
| ldapLoginFilter               | (&(&(|(objectclass=person))(|(|(memberof=CN=ownCloud Users,DC=gcfund,DC=dc)(primaryGroupID=1663))))(samaccountname=%uid)) |
| ldapLoginFilterAttributes     |                                                                                                                           |
| ldapLoginFilterEmail          | 0                                                                                                                         |
| ldapLoginFilterMode           | 0                                                                                                                         |
| ldapLoginFilterUsername       | 1                                                                                                                         |
| ldapNestedGroups              | 0                                                                                                                         |
| ldapOverrideMainServer        |                                                                                                                           |
| ldapPagingSize                | 500                                                                                                                       |
| ldapPort                      | 389                                                                                                                       |
| ldapQuotaAttribute            |                                                                                                                           |
| ldapQuotaDefault              |                                                                                                                           |
| ldapTLS                       | 0                                                                                                                         |
| ldapUserDisplayName           | displayname                                                                                                               |
| ldapUserFilter                | (&(|(objectclass=person))(|(|(memberof=CN=ownCloud Users,DC=gcfund,DC=dc)(primaryGroupID=1663))))                         |
| ldapUserFilterGroups          | ownCloud Users                                                                                                            |
| ldapUserFilterMode            | 0                                                                                                                         |
| ldapUserFilterObjectclass     | person                                                                                                                    |
| ldapUuidGroupAttribute        | auto                                                                                                                      |
| ldapUuidUserAttribute         | auto                                                                                                                      |
| turnOffCertCheck              | 0                                                                                                                         |
| useMemberOfToDetectMembership | 0                                                                                                                         |
+-------------------------------+---------------------------------------------------------------------------------------------------------------------------+

#### ownCloud log
{"reqId":"VjPentUyRgTi5brpLn7MGAAAAAI","remoteAddr":"192.168.0.212","app":"PHP","message":"Undefined index: displayname at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/access.php#695","level":3,"time":"2015-10-31T01:18:22+04:00"} {"reqId":"VjPfoATRsViVAKXC7sjSGAAAAAo","remoteAddr":"192.168.0.212","app":"PHP","message":"Undefined index: displayname at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/access.php#695","level":3,"time":"2015-10-31T01:22:40+04:00"} {"reqId":"VjPiLDRaqg4FHIhHmZrYFwAAAAU","remoteAddr":"86.171.223.236","app":"PHP","message":"Call to undefined method OCA\\user_ldap\\lib\\user\\OfflineUser::processAttributes() at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/access.php#698","level":3,"time":"2015-10-31T01:33:32+04:00"} {"reqId":"VjPlTNUyRgTi5brpLn7MHwAAAAI","remoteAddr":"192.168.0.212","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-31T01:46:53+04:00"} {"reqId":"VjPlYdUyRgTi5brpLn7MJAAAAAI","remoteAddr":"192.168.0.212","app":"PHP","message":"ldap_search(): Partial search results returned: Sizelimit exceeded at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-31T01:47:14+04:00"} {"reqId":"VjPlfdUyRgTi5brpLn7MKQAAAAI","remoteAddr":"192.168.0.212","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-31T01:47:41+04:00"} {"reqId":"VjPlhGzVaa7aWsh53p5@KQAAAAM","remoteAddr":"192.168.0.212","app":"PHP","message":"Call to undefined method OCA\\user_ldap\\lib\\user\\OfflineUser::processAttributes() at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/access.php#712","level":3,"time":"2015-10-31T01:47:49+04:00"} {"reqId":"VjPneWvRD-JNFgZT05NFbQAAAAc","remoteAddr":"192.168.0.212","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-31T01:56:09+04:00"} {"reqId":"VjPnfGvRD-JNFgZT05NFbwAAAAc","remoteAddr":"192.168.0.212","app":"PHP","message":"ldap_search(): Partial search results returned: Sizelimit exceeded at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-31T01:56:12+04:00"} {"reqId":"VjPpb9UyRgTi5brpLn7MMAAAAAI","remoteAddr":"192.168.0.212","app":"PHP","message":"Call to undefined method OCA\\user_ldap\\lib\\user\\OfflineUser::processAttributes() at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/access.php#712","level":3,"time":"2015-10-31T02:04:31+04:00"} {"reqId":"VjPpd0gEgF@Ofb6pbRwyQQAAAAA","remoteAddr":"192.168.0.212","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-31T02:04:39+04:00"} {"reqId":"VjPpfEgEgF@Ofb6pbRwyQwAAAAA","remoteAddr":"192.168.0.212","app":"PHP","message":"ldap_search(): Partial search results returned: Sizelimit exceeded at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-31T02:04:44+04:00"} {"reqId":"VjPp2EgEgF@Ofb6pbRwySwAAAAA","remoteAddr":"192.168.0.212","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-31T02:06:21+04:00"} {"reqId":"VjPp3UgEgF@Ofb6pbRwyTAAAAAA","remoteAddr":"192.168.0.212","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-31T02:06:22+04:00"} {"reqId":"VjPp7dUyRgTi5brpLn7MNgAAAAI","remoteAddr":"192.168.0.212","app":"PHP","message":"Call to undefined method OCA\\user_ldap\\lib\\user\\OfflineUser::processAttributes() at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/access.php#712","level":3,"time":"2015-10-31T02:06:37+04:00"}

**Comment by PVince81** [comment]
@blizzz AD stuff

**Comment by PVince81** [comment]
I've seen this "OCA\user_ldap\lib\user\OfflineUser::processAttributes()" errors in this other ticket https://github.com/owncloud/core/issues/20090

**Comment by MorrisJobke** [comment]
There was a PR merged just an hour ago that fixes something similar: https://github.com/owncloud/core/pull/20192 

That one also will get back ported to 8.1.5 and 8.2.1

**Comment by MorrisJobke** [comment]
Maybe you can test the patch.

I would like to close this ticket now - feel free to report back if the proposed solution is not working.

**Comment by ggujabidze** [comment]
@PVince81 Yea, I've read that post, but I think mine is a bit more sophisticated, as I had 4 different error messages:

1.{"reqId":"VjPentUyRgTi5brpLn7MGAAAAAI","remoteAddr":"192.168.0.212","app":"PHP","message":"Undefined index: displayname at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/access.php#695","level":3,"time":"2015-10-31T01:18:22+04:00"} 

2.{"reqId":"VjPiLDRaqg4FHIhHmZrYFwAAAAU","remoteAddr":"86.171.223.236","app":"PHP","message":"Call to undefined method OCA\user_ldap\lib\user\OfflineUser::processAttributes() at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/access.php#698","level":3,"time":"2015-10-31T01:33:32+04:00"} 

3.{"reqId":"VjPlTNUyRgTi5brpLn7MHwAAAAI","remoteAddr":"192.168.0.212","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-31T01:46:53+04:00"}   ----  Though I changed useMemberOfToDetectMembership to 0, it didn't help. It doesn't help on my current installation either, I have owncloud server v. 8.1.3, I have set useMemberOfToDetectMembership to 0, but I still view a lot of errors in log.

4.{"reqId":"VjPlYdUyRgTi5brpLn7MJAAAAAI","remoteAddr":"192.168.0.212","app":"PHP","message":"ldap_search(): Partial search results returned: Sizelimit exceeded at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-31T01:47:14+04:00"}  ---- And I think this last one is more problematic for me, as I had the following symptoms: when trying to click on Users tab, only circle was rotating and nothing was brought in list  :(

**Comment by ggujabidze** [comment]
@MorrisJobke OK, I can't try it just right now, but when new minor update will be available I'll give a try one more time.

**Comment by MorrisJobke** [comment]
> {"reqId":"VjPentUyRgTi5brpLn7MGAAAAAI","remoteAddr":"192.168.0.212","app":"PHP","message":"Undefined index: displayname at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/access.php#695","level":3,"time":"2015-10-31T01:18:22+04:00"}

Was also fixed last week AFAIK.



> {"reqId":"VjPlYdUyRgTi5brpLn7MJAAAAAI","remoteAddr":"192.168.0.212","app":"PHP","message":"ldap_search(): Partial search results returned: Sizelimit exceeded at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-31T01:47:14+04:00"}

This one was also there some weeks ago. @blizzz Was this fixed?

**Comment by MorrisJobke** [comment]
Just noticed the conversation at #20191 -> reopen

**Comment by blizzz** [comment]
>> {"reqId":"VjPlYdUyRgTi5brpLn7MJAAAAAI","remoteAddr":"192.168.0.212","app":"PHP","message":"ldap_search(): Partial search results returned: Sizelimit exceeded at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-31T01:47:14+04:00"}

> This one was also there some weeks ago. @blizzz Was this fixed?

Not a problem. Have seen this also just with ldapsearch on command line without anything wrong. Can be ignored.

**Comment by blizzz** [comment]
Closing this again as duplicates ;)
