### ISSUE TITLE
Please upload the ca-bundle.crt file into the 'config' directory

### ISSUE THREAD

**Issue by stevey1983** [owncloud/core#20205]
Hi, i am trying to update owncloud on my Netgear ReadyNAS 314 and when i update (from within owncloud admin page) i get the error "Please upload the ca-bundle.crt file into the 'config' directory"

Thanks for your help

**Comment by RealRancor** [comment]
Dup of https://github.com/owncloud/core/issues/19805, https://github.com/owncloud/core/issues/19669, https://github.com/owncloud/core/issues/19551, https://github.com/owncloud/core/issues/20086, https://github.com/owncloud/core/issues/20190 and some more.

The message itself is telling you what to do. If stuck also see this comment https://github.com/owncloud/core/issues/20086#issuecomment-151547507

**Comment by stevey1983** [comment]
Where would i find the config directory on the readyNAS? all i can see is a folder called owncloud and only has the user folders, data folder (with only a temp folder in) , a private key folder, a index html file, a owncloud data base file, owncloud txt file and thats in, no config?

**Comment by RealRancor** [comment]
Hi,

it should be easy to find with common linux tools like find or locate. Please note this is a bugtracker for bugs and feature requests. If you need support to understand your operation system please ask at the forums or the users mailinglist.
