### ISSUE TITLE
Easy way to install themes

### ISSUE THREAD

**Issue by marvelloard** [owncloud/core#20200]
Hi,

I want to be honest and think the new set of icons looks ugly. In general I really dislike this nowadays widely used "modern" flat look.

What about a complete support for themes? Where users can create "packages", admins copy them to a "theme" folder inside oC and enable them in the webinterface, just like apps.

**Comment by LukasReschke** [comment]
What are you missing at https://github.com/owncloud/core/tree/master/themes? - This is already possible.

**Comment by marvelloard** [comment]
I'm sorry I didn't realise it's possible because I first looked at the admin preferences (UI) and didn't find an option for it there. Also I thought if this was possible there would be some website like apps.owncloud.com where themes would be presented. I didn't find one so I thought it's not possible at all.

Still, a website like themes.owncloud.com and UI integration to select them would be nice ;)

**Comment by PVince81** [comment]
cc @PhilippSchaffrath

**Comment by PVince81** [comment]
basically making it possible for apps to provide themes, so enabling a theme is only a matter of enabling the app.

cc @DeepDiver1975

**Comment by PhilippSchaffrath** [comment]
Possibility to provide Themes through an App has been added in #26462 and merged into master.
Documentation will soon get updated correspondingly, see [owncloud/documentation#2711](https://github.com/owncloud/documentation/issues/2711)
