### ISSUE TITLE
User Photos from LDAP don't get refreshed

### ISSUE THREAD

**Issue by alex42ka** [owncloud/core#20204]
As described above. I've added the LDAP-login to Owncloud. Afterwards I've added user photos to the users and hoped that they will get synced to owncloud. But this is not happening. 

I'm using ownCloud 8.2. For some users, for which I've added a photo before configuring OC to use the LDAP, the user photos is used so it doesn't seems to be a configuration mistake.

**Comment by karlitschek** [comment]
@blizzz what do you think?

**Comment by blizzz** [comment]
@alex42ka thank you for using the [Issue Template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md).

The user pictures should get loaded next time they login after the LDAP Backend Cache has run out, otherwise on demand after 24h.

**Comment by alex42ka** [comment]
You're right. When the users login their photo is loaded. Sorry for disturbing!

**Comment by blizzz** [comment]
no problem
