### ISSUE TITLE
Put 8.1.4 in the current stable channel of SuSE repos

### ISSUE THREAD

**Issue by tflidd** [owncloud/core#20206]
A lot of users use this current-stable-branch:
http://download.opensuse.org/repositories/isv:/ownCloud:/community/Debian_8.0/

where the current version still is 8.1.3.

If you go directly to the 8.1.x-sources (http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.1/Debian_8.0/), the packages are already updated to 8.1.4.

@jnweiger

**Comment by PVince81** [comment]
@cmonteroluque @karlitschek

**Comment by jnweiger** [comment]
Opened the mirrors for 8.1.4 - currently I am checking build success from the weekend, and releasing, what looks good.

**Comment by jnweiger** [comment]
8.1.4 is now visible in http://download.opensuse.org/repositories/isv:/ownCloud:/community/Debian_8.0/
