### ISSUE TITLE
[feature request for files_version app] File version tree, for Education

### ISSUE THREAD

**Issue by SebCanet** [owncloud/core#20209]
Hi,
I read some of issues about version in onwcloud, and way to see it.
But I would like to use owncloud with any debutant teacher in collaborating goal, and owncloud has a lack in viewing the different file. I'm a french STEM teacher and national coach.

I explain : using Github, you can access to different version of file, like this
https://github.com/technologiescollege/mBlock-languages/network
and we would like to see version of directories or file the same way in owncloud.

Why ? Because when someone has created a very goo activity to learn, by example, to code and has created this for his 12 years old pupills, I could take this, change things for my 10 years old pupills, and save it like a version in owncloud.

I hope nobody already asked it, thanks a lot for answering.
Thanks for this great project.
Sebastien

**Comment by MTRichards** [comment]
This is a pretty cool idea. Not specifically possible for the next release (9.0) unless someone can work on it, but certainly a nice user experience.

**Comment by AsavarTzeth** [comment]
Do I understand this correctly? It is like mixture of displaying file versions (old & new) and a template system?

**Comment by SebCanet** [comment]
What do you mean by 'template system' ?

**Comment by AsavarTzeth** [comment]
You know, using file versions as templates for a new modified file. That is how I interpret your example with someone else having created "a good activity".

**Comment by SebCanet** [comment]
I just imagined something where a teacher decide his document is a version of another and tag it in the good branch version.
Then you cloud see it in a graphical way.

**Comment by AsavarTzeth** [comment]
I see. That is why I asked. I had a hard time understanding what you meant, and still do to some extent. Thank you for clarifying.

So I suppose it would be more like a revision/version control system than templates. Or at least parts of it, simplified so "normal" users could integrate it in their workflow.

**Comment by SebCanet** [comment]
SOrry, quite difficult to understand, how to use but the priority is 'normal' user, french teacher working together through France. So no expert user of git...

Hope it could give ideas, I think it's real collaborative tool that nobody has never done.

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/issues/23002
