### ISSUE TITLE
Default apache config of Let's Encrypt might break oC routes

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#20202]
Hi,

more a discussion if there is something which could be done on oC side here or if this should be reported upstream:

It seems that Let's Encrypt is creating a default Apache config containing the config parameter:

``AcceptPathInfo Off`` (https://httpd.apache.org/docs/2.4/en/mod/core.html#acceptpathinfo)

as seen here:

https://forum.owncloud.org/viewtopic.php?f=21&t=31248&p=100263#p100257
http://itrig.de/index.php?/archives/2158-Lets-Encrypt-Ein-erster-Blick-auf-die-kostenlose-Zertifizierungsstelle-von-Mozilla-und-der-EFF.html
https://forum.owncloud.org/viewtopic.php?f=36&t=31240

This seems to be causing broken routes like seen in https://forum.owncloud.org/viewtopic.php?f=21&t=31248 and https://forum.owncloud.org/viewtopic.php?f=36&t=31240

Is there anything what could be done here from oC side to prevent such broken installs besides documenting that? Any opinions?

**Comment by LukasReschke** [comment]
@rullzer @danimo You have a beta invite - right?

**Comment by danimo** [comment]
@LukasReschke Indeed. What do you need?

**Comment by RealRancor** [comment]
@danimo Are you using the auto generated Let's Encrypt Apache configs or some own?

I have posted this issue because from the links above Let's Encrypt currently seems to generating an Apache config containing:

``AcceptPathInfo Off``

The docs of this options is saying:

> A request will only be accepted if it maps to a literal path that exists. Therefore a request with trailing pathname information after the true filename such as /test/here.html/more in the above example will return a 404 NOT FOUND error.

which is very likely causing the issue seen in https://forum.owncloud.org/viewtopic.php?f=21&t=31248

**Comment by tflidd** [comment]
The owncloud.conf cannot be parsed by letsencrypt: https://github.com/letsencrypt/letsencrypt/issues/1264

Would be nice to get both projects working together on one server...

**Comment by RealRancor** [comment]
Upstream issue for the AcceptPathInfo problem here: https://github.com/letsencrypt/letsencrypt/issues/1274

**Comment by RealRancor** [comment]
Fixed in Let's Encrypt with https://github.com/letsencrypt/letsencrypt/pull/1390 so closing here.
