### ISSUE TITLE
Updating to 8.1.3 error when 'contats_index' does not exist

### ISSUE THREAD

**Issue by valentinrusu-movidius** [owncloud/core#20207]
Just updated from 8.1.1 to 8.1.3 using the admin interface directly into owncloud.

At the end I got this message:

====================================
Updating ownCloud to version 8.1.3, this may take a while.

Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Updated "activity" to 2.0.2
Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "contacts_index" as such route does not exist.
The update was unsuccessful. Please report this issue to the ownCloud community.
====================================

Now reopening my owncloud server's URL the upgrade wizard started over and I ended-up into my normal owncloud session, but contacts and calendar apps where disabled. I re-enabled them and I was brought back to the upgrade wizard. And this time it worked, I now restored the contacts and the calendar

**Comment by DeepDiver1975** [comment]
We are pretty much aware of this behavior. You fixed it yourself the recommended way.
Future releases will be more stable.

Closing for now since there is nothing to do for now in the old releases.
