### ISSUE TITLE
Enforce "min-version" and "max-version" for apps

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#20218]
From my PoV we should enforce a "min-version" and "min-version" for apps in their appinfo.xml. If they don't have one: Don't allow users to enable the app.

Way too many apps are somehow trying to inject stuff in other core code resulting in a famously broken ownCloud. That would help from my PoV.
(as long as developers don't set ownCloud 9999 as `max-version`…)

**Comment by LukasReschke** [comment]
@karlitschek @jospoortvliet @DeepDiver1975 Thoughts?

**Comment by karlitschek** [comment]
hmmm. i agree. but the danger is that people just set owncloud 42 as max.
we also should start with a strong warning if this is not set yet. we can make it a hard requirement in a year

**Comment by DeepDiver1975** [comment]
> hmmm. i agree. but the danger is that people just set owncloud 42 as max.

can we define a valid range of versions?
As in: an ownCloud 9.0 instance detects a max version of up to 11.0 as valid?

**Comment by DeepDiver1975** [comment]
> we also should start with a strong warning if this is not set yet. we can make it a hard requirement in a year

well - in a year I guess every app of interest will have a valid max version set.
The proposed approach is to protect current live instances from breakage.

So ... what about marking them as experimental as soon as the versions are missing?
It's then the admin's explicit choice to enable a potentially broken app

**Comment by jancborchardt** [comment]
* In the appstore we require a min and max version to be set. You can only set a max version which is current version +1 (dev version). This ensures that devs either test their app or at least for every version need to manually change it.
* In ownCloud itself, any app with invalid version is set as experimental, as Thomas said also.

**Comment by jospoortvliet** [comment]
Amen with @jancborchardt and @DeepDiver1975

**Comment by DeepDiver1975** [comment]
@karlitschek @cmonteroluque 9.0 from my pov - minimal change with big impact

**Comment by karlitschek** [comment]
Yes. Big impact because it would break existing apps which is what we don't want. Let's go with a warning in the logfile first.

**Comment by cmonteroluque** [comment]
@karlitschek Would the idea be of having just a warning in the logfile for 9.0 then?

**Comment by karlitschek** [comment]
Yes. I suggest to go with a logfile warning first before we make this a hard requirement. We need a transition period for everything that breaks existing apps.

**Comment by DeepDiver1975** [comment]
But the logfile will not help to protect an instance from being broken because of an inkompatible app.

Basically we have a different view: protect the instance vs. Allow apps to be installed.

**Comment by nickvergessen** [comment]
If we do a warning, it should be on the apps page where they reenable the app after the update, no one reads logs in advance to see if there is a warning that the app is not going to work in a future version.

**Comment by jancborchardt** [comment]
If an app dev didn’t update their app to use the new format – which exists since a long time already – then most likely the app is not fit for being installed anyway, right?
And even if, we of course need to communicate this through the devel mailing list and an update can be made very quickly via the appstore.

**Comment by karlitschek** [comment]
This is not clear if an app without this works or not. This wasn't a mandatory field in the past but will be in the future. So this is a break of API that we can only do after a grace period. 
This is a good example what it means to keep a stable API for some time. 
So we can add it as mandatory to the documentation today and do a warning in the log or apps page or somewhere else. But we can't jump directly to a hard requirement.

**Comment by DeepDiver1975** [comment]
> This is not clear if an app without this works or not.

well - it most probably will not - give the past experience. Never the less this change will not block an admin from installing/enabling any of these apps - we propose to notify the admin that there is a potential issue with this app.

The admin can by himself judge if he is willing to tale the risk or not.

So from my pov the UX is improved and we did the best to protect the instance from crashing.

**Comment by karlitschek** [comment]
Great!
Some kind of notification makes 100% sense. 
We just can't block apps there weren't updated (yet) :-)

**Comment by DeepDiver1975** [comment]
> We just can't block apps there weren't updated (yet) :-)

So ... 9.0 task?

**Comment by jancborchardt** [comment]
I assumed anyway that this would only happen starting with 9.0 – so if we announce it now that we’ll do it, that gives plenty of time for app devs to update, no?

**Comment by karlitschek** [comment]
Plenty of time before we break old apps that are not updated was defined as 3 years.

**Comment by jospoortvliet** [comment]
@karlitschek I bet @jancborchardt meant 12.0, not 9.0 ;-)

**Comment by jancborchardt** [comment]
The small problem here is that we already break »old« apps of app devs which have been diligent in filling out their min/max version in this new way – when they miss to update it to the most recent version. This doesn’t happen if you don’t set any min/max at all.

So we basically penalize people if they try to follow the guidelines but miss the latest, and don’t do anything if they don’t follow the guidelines at all. That’s the source of confusion here. So if we really mean to not break old apps for 3 years then setting a max-version of 8.0 should actually be treated by ownCloud as a max-version of 11.0 or so.

**Comment by nickvergessen** [comment]
You misunderstood frank I think.
The value should not be interpreted in anyway, our shipped apps don't work with other versions then the ones they are shipped with...
What frank meant is that we can't make the field a full hard requirement before oC 11.

**Comment by DeepDiver1975** [comment]
> What frank meant is that we can't make the field a full hard requirement before oC 11.

hard requirement -> oc 11
notification/warning in the apps page -> oc 9.0

can we now finally agree on that? This discussion is runnin for too long already - there are many more things to do. THX

**Comment by jospoortvliet** [comment]
:+1:

**Comment by karlitschek** [comment]
@nickvergessen Thanks for the clarification. Sorry for not being clear! :-)

**Comment by karlitschek** [comment]
@DeepDiver1975 agreed :-)

**Comment by DeepDiver1975** [comment]
scheduling for 9.0
