### ISSUE TITLE
OC 8.2 unable to upload files via share link

### ISSUE THREAD

**Issue by apg1980** [owncloud/core#20214]
Hello,

my environment:
oc 8.2
ubuntu 14.04 on bitnami stack (latest)
Version 8.2.0-0      2015-10-20
* Apache to 2.4.17
* PHP to 5.5.29
* MySQL to 5.6.25

I am using user_ladap.
As a logged on user i am able to upload files via the webfrontend. A shared link to via email are able to open but the recipient is unable to upload any files. 
with internet explorer and firefox i get the following errors in debugger console:

Internet Explorer
fileList = OCA.Files.App.fileList
SCRIPT5007: Die Eigenschaft "fileList" eines undefinierten oder Nullverweises kann nicht abgerufen werden.

Firefox:
TypeError: OCA.Files.App is undefined

Can anybody help?

Thanks a lot

**Comment by RealRancor** [comment]
Hi,

thats an known issue which will be fixed with oC 8.2.1: https://github.com/owncloud/core/issues/19922

**Comment by PVince81** [comment]
Yes, sorry for inconvenience. In the meantime you can patch your setup with this https://github.com/owncloud/core/pull/19956

Closing as duplicate.
