### ISSUE TITLE
Windows Owncloud client doesn’t support with Windows deduplication

### ISSUE THREAD

**Issue by falkenau** [owncloud/core#20213]
Hi there!

I’m using Windows 8.1 Pro. On my second volume I’m using NTFS with deduplication. (https://weikingteh.wordpress.com/2013/10/10/enable-deduplication-on-your-windows-8-1/)

Now I bought a QNAP NAS and installed Owncloud 8.0.4. Almost everything works very well, Android client on my smartphone, LDAP connection and a test Windows client.

However, my private notebook with the deduplicated volume, doesn’t work. A lot of files are synced to Owncloud and almost half of the files are not synced. Owncloud client Version 2.0.2 (build 5569)

I used the logwindow option to get more information:
owncloud.exe --logwindow --logfile c:\temp\OCclient.log

It turns out that there are many errors:
11-02 01:48:41:776 0x3778a8 OCC::SyncEngine::slotItemCompleted: void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "Scan-Laptop.pdf" INSTRUCTION_IGNORE 6 "Symbolische Verknüpfungen werden bei der Synchronisation nicht unterstützt."

(Symbolic links are not supported in syncing)

The file named “Scan-Laptop.pdf” has a blue mark, not a green one. All errors are tagged 0x3778a8. If I copy the file it will get synced. But after Windows deduplication has deduped the copy, it will get a blue mark and deleted from Owncloud.

Junction Link Magic (http://www.rekenwonder.com/linkmagic.htm) is not able to find any symlink on the second volume D:\. Of course there are many in C:\ (my systemroot).

Therefore, I guess, the Owncloud client is seeing all my deduplicated files a symbolic links. And so the client is pretty useless to my. :(

Any suggestions? Should this be treated as a bug or as a feature request?

Hope it helps.

**Comment by RealRancor** [comment]
Hi,

@falkenau The issue tracker of the sync client is located here: https://github.com/owncloud/client/issues

Please re-open there by using the issue template provided here: https://raw.githubusercontent.com/owncloud/client/master/issue_template.md

**Comment by MorrisJobke** [comment]
Please reopen in the client issue tracker (see link above).
