### ISSUE TITLE
[OC8.2.0] MySQL file socket not working during initial setup

### ISSUE THREAD

**Issue by josh4trunks** [owncloud/core#20210]
Several users are hitting the error the error...
```
Error while trying to create admin user: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] Can't assign requested address
```
when specifying "localhost:/tmp/mysql.sock" as the 'Database host' during initial setup of ownCloud 8.2.0. Something during inital setup is passing "/tmp/mysql.sock" as a port instead of a unix_socket to Doctrine.

* This was not an issue in versions <8.2.0
* https://github.com/owncloud/core/blob/master/lib/private/db/connectionfactory.php seems to be doing its job correctly, as once you get passed the initial setup specifying having "localhost:/tmp/mysql.sock" in your config works just fine. my production setup, which uses a non-standard socket location (/var/run/mysql/mysql.sock) also continued to work with an upgrade to ownCloud 8.2.0.
* A workaround if using the standard location of /tmp/mysql.sock is to use "localhost", in which case no port is passed to Doctrine and subsequently pdo-mysql extension. The extension when not passed a port or unix_socket tries it default socket location which would work.

**Reference**
https://forums.freenas.org/index.php?threads/how-to-owncloud-using-nginx-php-fpm-and-mysql.17786/page-35#post-237777

**Comment by MorrisJobke** [comment]
cc @butonic

**Comment by josh4trunks** [comment]
I'm wondering if this was addressed in the 8.2.1RC1?
More users are hitting this bug in the thread I linked.

**Comment by DeepDiver1975** [comment]
This is related to the changes we did in the MySQL setup code.

**Comment by PVince81** [comment]
@DeepDiver1975 what kind of changes ? :smile:

**Comment by MorrisJobke** [comment]
> @DeepDiver1975 what kind of changes ?

I guess https://github.com/owncloud/core/pull/17963

**Comment by josh4trunks** [comment]
isn't doctrine used for all mysql connections from owncloud? if so I wonder why it only doesn't work during setup but works fine during normal use.

**Comment by DeepDiver1975** [comment]
> I guess #17963

yes

**Comment by DeepDiver1975** [comment]
> if so I wonder why it only doesn't work during setup but works fine during normal use.

that's the question to be answered

**Comment by PVince81** [comment]
@DeepDiver1975 were you able to reproduce this locally ?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 were you able to reproduce this locally ?

no - not yet
