### ISSUE TITLE
Still no working PUT User-Provisioning API

### ISSUE THREAD

**Issue by alexdetsch** [owncloud/core#20212]
Hi,
I just upgraded to the new owncloud 8.2 and have to migrate round about 120 users to a new server.
But when I want to change the users display-name and e-mailadress I had encountered the same bug as in #14283.
I can create new users over the API, but all PUT-Requests fail with the exact same behavior as in the bug mentioned above.
In the other thread there was a hint, that it belongs to the calendar-app, so I deactivated both the calendar and the contact-app, but it still does not work.
I access the API through PHP. Firstly with http_put_data() (commented), then with curl:

    function put_data($url, $data, $username, $password) {
     $options = array(
         'http' => array(
             'header'  => "Content-type: application/x-www-form-urlencoded",
             'method'  => 'PUT',
             'content' => http_build_query($data),
         ),
     );
     $context  = stream_context_create($options);
     $result = file_get_contents($url, false, $context);
    }

    $escapedUsername = str_replace("@", "%40", $username);
    $apiurl = "https://admin:password@owncloud.mydomain.de/ocs/v1.php/cloud/users/". $escapedUsername;
    $data = array(
        //'email' => $username,
        'display' => $name
    );
    //put_data($apiurl, $data, "admin", "password");
    
    $curl = curl_init($apiurl);
    curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "PUT");
    curl_setopt($curl, CURLOPT_HEADER, false);
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($curl, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
    curl_setopt($curl, CURLOPT_USERPWD, "admin:password");  
    curl_setopt($curl, CURLOPT_POSTFIELDS, http_build_query($data));
    $response = curl_exec($curl);
    curl_close($curl);
    echo($response);

I use the e-mailadress to authenticate the user against an IMAP-server, so I have to replace the '@' with an '%40' for the url.

**Comment by DeepDiver1975** [comment]
Anything in the logs? How does the response look like?

**Comment by alexdetsch** [comment]
As I sayd, the EXACT same behavior as in #14283.
    {"reqId":"nR\/C1v96\/zaaaaB57PkQ","remoteAddr":"127.0.0.1","app":"PHP","message":"Undefined index: key at \/var\/www\/owncloud\/apps\/provisioning_api\/lib\/users.php#199","level":3,"time":"2015-11-01T19:32:39+00:00","method":"PUT","url":"\/ocs\/v1.php\/cloud\/users\/user%40domain.de"}
Curl get also the same answer as in the bug above.

**Comment by DeepDiver1975** [comment]
You are sending a wrong body. You should send 

```php
$data = array(
    'key' => 'display',
    'value' => $name
);

**Comment by DeepDiver1975** [comment]
see https://doc.owncloud.org/server/8.2/admin_manual/configuration_user/user_provisioning_api.html?highlight=provisioning%20api#id5

**Comment by alexdetsch** [comment]
Oh, sorry for my mistake, but thank you for the fast answer ;)
Now it works well :)
