### ISSUE TITLE
Safari 9.0 pinned tab icon

### ISSUE THREAD

**Issue by maprambo** [owncloud/core#20211]
Hey ownCloud developers,
when pinning ownCloud in Safari 9.0, it doesn't show any icon.
After some research, I found out you could add one by adding this tag:
```
<link rel="mask-icon" href="logo-icon-black.svg" color="#1d2d44">
```
"logo-icon-black.svg" should be replaced with a black version of the ownCloud logo (in svg format!).

If you need more information you can gather it here: https://developer.apple.com/library/prerelease/mac/releasenotes/General/WhatsNewInSafari/Articles/Safari_9.html#//apple_ref/doc/uid/TP40014305-CH9-SW20

**Comment by karlitschek** [comment]
@jancborchardt

**Comment by jancborchardt** [comment]
@maprambo I don’t have Safari to test – can you show a screenshot of how it looks right now and how it is supposed to look?

Because there is no black version of the ownCloud logo, at least the cloud should never be used in a dark way. We should use the normal favicon, like favicon-touch.svg
@maprambo It would be cool if you can just make that change and open a pull request. :)

**Comment by jancborchardt** [comment]
Ok … it has to be full black? In that case I would say we use a square version of the favicon-touch.svg icon, make the dark blue black and the white cloud transparent and use #fff (white) for the color. Ok @maprambo?

**Comment by MorrisJobke** [comment]
> Ok … it has to be full black?

On that side following is also mentioned:

> In the example, the color attribute sets the display color of the image. That attribute can specify a single color with a hexadecimal value (#990000), an RGB value (rgb(153, 0, 0)), or a recognized color-keyword, such as: red, lime, or navy.

So we can provide our blue color there with a black version of the SVG. Maybe also the blue version works :see_no_evil:

**Comment by maprambo** [comment]
I can do the pull request today in the evening, that should work. 
And as the icon is very small I would prefer the owncloud logo without any borders or backgrounds, I can send a picture of how it will look before I make the pull request.

**Comment by jancborchardt** [comment]
@maprambo ok, but the cloud should then be white. If something dark is needed, we should use the negative space around the cloud, in #1d2d44

**Comment by maprambo** [comment]
@jancborchardt I don't really know what you mean by the negative space...
Safari needs a black svg. It will be grey when another tab is open and coloured (with the specified color) when the pinned tab is open. You can see it in the attached screenshots and compare it to twitter. I have to say that twitter looks actually bigger but it is only higher.
<img width="234" alt="bildschirmfoto 2015-11-02 um 17 37 18" src="https://cloud.githubusercontent.com/assets/7558730/10887833/65a029d4-8189-11e5-984f-a7da18192a9c.png">
<img width="255" alt="bildschirmfoto 2015-11-02 um 17 37 40" src="https://cloud.githubusercontent.com/assets/7558730/10887835/65cce370-8189-11e5-82e3-fc11ca29ee95.png">
<img width="257" alt="bildschirmfoto 2015-11-02 um 17 37 54" src="https://cloud.githubusercontent.com/assets/7558730/10887834/65cac040-8189-11e5-9679-5361bc177e3c.png">

**Comment by maprambo** [comment]
@jancborchardt Ok, I tried to create a pull request. Despite I have no idea of git, I cloned core with GitHub for Mac, created a branch, made the necessary changes and tried to press "Send Pull Request". 
GitHub gives me this:
```
You may not have permission to access core. Check Preferences to make sure you’re still logged in.
```
(and yep, I am logged in.)

**Comment by MorrisJobke** [comment]
@maprambo You need to fork the repo https://help.github.com/articles/fork-a-repo/ Then you can push to that repo and create the pull request.

**Comment by maprambo** [comment]
Thanks :+1:

**Comment by jancborchardt** [comment]
@maprambo I’m not really happy with the cloud being dark. Clouds are not dark blue, and we never display our logo as such. Can you try how it looks when just using the »favicon.svg« file? Basically instead of the cloud being white, make it transparent.

**Comment by MorrisJobke** [comment]
> @maprambo I’m not really happy with the cloud being dark. Clouds are not dark blue, and we never display our logo as such. Can you try how it looks when just using the »favicon.svg« file? Basically instead of the cloud being white, make it transparent.

@maprambo Just to make it more clear: https://raw.githubusercontent.com/owncloud/core/master/core/img/favicon-touch.png <- this is the image @jancborchardt is referring to. There is also a sag version in the same folder.

**Comment by maprambo** [comment]
Thanks. After some fiddling in inkscape, I got what you wanted. Looks better. (I tried to leave the cloud white but Safari made just a filled rectangle out of it.)
<img width="263" alt="bildschirmfoto 2015-11-03 um 12 27 59" src="https://cloud.githubusercontent.com/assets/7558730/10907012/cd4f3230-8226-11e5-8e64-27ddae881f09.png">
<img width="213" alt="bildschirmfoto 2015-11-03 um 12 27 50" src="https://cloud.githubusercontent.com/assets/7558730/10907013/cd871bdc-8226-11e5-9ffa-257eba38309b.png">

**Comment by MorrisJobke** [comment]
Looks nice :) Can you push your changes?

**Comment by MorrisJobke** [comment]
> Looks nice :) Can you push your changes?

Just noticed that this is the issue and the changes are already present.

**Comment by MorrisJobke** [comment]
PR is merged
