### ISSUE TITLE
Use HTTPS for federated cloud share when another share already uses HTTPS

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#20216]
In case a share has already been done with another instance via HTTPS we should enforce HTTPS as well for all future shares. Otherwise an adversary might block the HTTPS port when a new share is initiated resulting in a downgraded new share.

I'm also thinking whether it would make sense to add this to `OCP\Http\Client` in combination with HSTS and certificate pinning. Something to consider. Mhm…

@schiesbn Thoughts?
@jospoortvliet FYI

**Comment by jospoortvliet** [comment]
Wouldn't we get a list of 'trusted servers'? It'd be good to ensure no adversary can pretend to be one of those... Perhaps loading a certificate or something.

**Comment by LukasReschke** [comment]
> > Wouldn't we get a list of 'trusted servers'? It'd be good to ensure no adversary can pretend to be one of those... Perhaps loading a certificate or something.

> I'm also thinking whether it would make sense to add this to OCP\Http\Client in combination with HSTS and certificate pinning. Something to consider. Mhm…

:wink:

**Comment by MorrisJobke** [comment]
> I'm also thinking whether it would make sense to add this to OCP\Http\Client in combination with HSTS and certificate pinning.

Yep. I would go the HSTS way, because this is the standard way to handle scenarios like this.

**Comment by PVince81** [comment]
What to do with this request ? I set it to 9.1 to keep it in view

**Comment by PVince81** [comment]
@Peter-Prochaska

**Comment by PVince81** [comment]
@Peter-Prochaska please evaluate severity

**Comment by PVince81** [comment]
until then -> backlog

**Comment by settermjd** [comment]
WRT public key (certificate) pinning, [that is being progressively deprecated (primarily in Google Chrome)](https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/he9tr7p3rZ8/eNMwKPmUBAAJ?hn) and replaced by [the Expect-CT header and Certificate Transparency](https://scotthelme.co.uk/a-new-security-header-expect-ct/). That said, I agree that HSTS is the way to go.

**Comment by PVince81** [comment]
not sure if we need this any more as we enforce https since 10.0.8 with https://github.com/owncloud/core/pull/30198
