### ISSUE TITLE
Recursive external shares kill web server 

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#20228]
* UserA shares a folder "/abc" by link
* Open that link
* UserA clicks "Add to my owncloud" and types in the URL of the same OC instance
* UserA logs in and accepts the new share
* ~~UserA moves the folder "/abc (2)" into "/abc" -> now the share is mounted as "/abc/abc (2)"~~

:boom: 

I tested this with latest master.

cc @PVince81 @schiesbn 

cc @michaelstingl

**Comment by PVince81** [comment]
@MorrisJobke which OC version ?

**Comment by PVince81** [comment]
Ah, latest master. Damn... I thought I fixed something similar recently.

**Comment by PVince81** [comment]
I can't reproduce this on master 053effaa5124ac527712ac97193eb444259c69bc. Moving a received share (mount point) into an outgoing shared folder is not allowed. It says "Cannot move abc".

How was the folder moved ? I did it on the web UI.

**Comment by PVince81** [comment]
CC @rullzer @schiesbn

**Comment by rullzer** [comment]
Stop trying to break everything! :wink:

**Comment by Touchwoody** [comment]
On MacOS I was able to move the shared folder in the file system (mv abc (2)/ abc/). Guess that applies to Linux and Windows likewise.

**Comment by rullzer** [comment]
@Touchwoody you mean using the sync client?

**Comment by Touchwoody** [comment]
Yes. The sync clients seems to recognize when a share is moved. Which is nice.

But it should check if a loop was created and then drop the share. 
Or move it again, into a "lost shares" folder or something. Would be nicer than just dropping it.

**Comment by rullzer** [comment]
No the client should not have to care. We should check on the server end if we try to move a share into another share and then say. NOPE!

@schiesbn we do "in general" do not allow moving a sharedmount into another sharedmount right?

**Comment by PVince81** [comment]
@rullzer yes, this is denied with a 403 Forbidden. Also moving a shared mount into an outgoing share also does that. At least it did for me in the web UI, not sure if someone managed to bypass it.

**Comment by MorrisJobke** [comment]
I tried it with the last step only one time and it worked. On all subsequent tries my apache killed itself always in the step after accepting the share. The file list didn't load. nothing in the logs and the web server need to be killed hardly (kill -9 httpd).

**Comment by PVince81** [comment]
Note that I tested with the git version and didn't have any apps enabled. Maybe some apps are doing something before the move is done, or one of them is preventing the detection to work ?

**Comment by PVince81** [comment]
Setting to 9.0, we need to keep this in sight.

**Comment by MorrisJobke** [comment]
I need to clarify: This is only possible in stable8.1

**Comment by PVince81** [comment]
this was fixed on 8.2 + master in this PR: https://github.com/owncloud/core/pull/19525

**Comment by PVince81** [comment]
I discovered a similar case, but where you move "abc" into "abc (2)" (not covered by the PR), see https://github.com/owncloud/core/issues/20296 (pyramids inside)

**Comment by MorrisJobke** [comment]
@michaelstingl The sharing situation will not be possible anymore with 8.1.5. Cleanup of existing shares is not done yet. And it's also really hard to detect. Best is a manual cleanup once we notice such stuff.

**Comment by michaelstingl** [comment]
@MorrisJobke @PVince81 Thank you – awesome work!

**Comment by MorrisJobke** [comment]
I just discussed this with @PVince81 and it's nearly impossible to properly detect such cases. As a side effect an automatic repair will most likely cause more trouble than it solves. Sad to say so, but the only way to address this is to manually fix this once this is noticed. The fixes to prevent such cases are in 8.1.5+ and 8.2.0+.
