### ISSUE TITLE
Upgrade 8.1.4 Ubuntu

### ISSUE THREAD

**Issue by AslHoffmann** [owncloud/core#20238]
error 

Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "contacts_index" as such route does not exist.

**Comment by RealRancor** [comment]
Dup of https://github.com/owncloud/core/issues/19145, https://github.com/owncloud/core/issues/20125, https://github.com/owncloud/core/issues/20207 and some more. Should be easy to find when using the search box at the top.
