### ISSUE TITLE
LDAP not working after upgrade from 8.1.3-13.1 to 8.1.4-12.1- Debian

### ISSUE THREAD

**Issue by belzebubek** [owncloud/core#20235]
PHP Fatal error:  Call to undefined method OCA\\user_ldap\\lib\\user\\OfflineUser::processAttributes() in /var/www/owncloud/apps/user_ldap/lib/access.php on line 709
PHP Stack trace:
PHP   1. {main}() /var/www/owncloud/remote.php:0
PHP   2. require_once() /var/www/owncloud/remote.php:132
PHP   3. Sabre\\DAV\\Server->exec() /var/www/owncloud/apps/files/appinfo/remote.php:83   
PHP   4. Sabre\\DAV\\Server->invokeMethod() /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php:254
PHP   5. Sabre\\Event\\EventEmitter->emit() /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php:456
PHP   6. call_user_func_array:{/var/www/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php:105}() /var/www/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php:105
PHP   7. Sabre\\DAV\\Auth\\Plugin->beforeMethod() /var/www/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php:105
PHP   8. OC\\Connector\\Sabre\\Auth->authenticate() /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php:118
PHP   9. OC\\Connector\\Sabre\\Auth->auth() /var/www/owncloud/lib/private/connector/sabre/auth.php:122
PHP  10. Sabre\\DAV\\Auth\\Backend\\AbstractBasic->authenticate() /var/www/owncloud/lib/private/connector/sabre/auth.php:149
PHP  11. OC\\Connector\\Sabre\\Auth->validateUserPass() /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Auth/Backend/AbstractBasic.php:74
PHP  12. OC_User::login() /var/www/owncloud/lib/private/connector/sabre/auth.php:76
PHP  13. OC\\User\\Session->login() /var/www/owncloud/lib/private/user.php:242
PHP  14. OC\\User\\Manager->checkPassword() /var/www/owncloud/lib/private/user/session.php:217
PHP  15. OCA\\user_ldap\\USER_LDAP->checkPassword() /var/www/owncloud/lib/private/user/manager.php:178
PHP  16. OCA\\user_ldap\\USER_LDAP->getLDAPUserByLoginName() /var/www/owncloud/apps/user_ldap/user_ldap.php:100
PHP  17. OCA\\user_ldap\\lib\\Access->fetchUsersByLoginName() /var/www/owncloud/apps/user_ldap/user_ldap.php:83
PHP  18. OCA\\user_ldap\\lib\\Access->fetchListOfUsers() /var/www/owncloud/apps/user_ldap/lib/access.php:670
PHP  19. OCA\\user_ldap\\lib\\Access->batchApplyUserAttributes() /var/www/owncloud/apps/user_ldap/lib/access.php:683

**Comment by DeepDiver1975** [comment]
this has already reported - please use the search on github - THX

**Comment by belzebubek** [comment]
Can you point me out where it was reported?
