### ISSUE TITLE
[Proposal] Make etags only propagate to the root of the storage.

### ISSUE THREAD

**Issue by icewind1991** [owncloud/core#20231]
Almost all etag propagation issues come down to having to propagate etags across storage boundaries.

We could get rid of all those problems by only propagating etags up to the root of the storage which saves us from having to update etags for other users besides the owner of the file (or the current user in case of multiple users sharing an external storage).

Then when reading the etag of a folder from the database we combine the "storage etag" with the etags from all mount points in that folder to calculate an etag that has proper cross storage propagation.

A similar method is used to calculate folder sizes and this could also be used for folder mtimes

We sacrifice some complexity when reading etag (I dont think it will actually result in a performance penalty since we already need to get the metadata from the cache for all mount points in a folder to get the size) to make etag propagation a **lot** simpler.

Note that this could also lead the way to reproducible folder etags although that would conflict with things like #20229

cc @DeepDiver1975 @PVince81 @MorrisJobke

**Comment by PVince81** [comment]
But you would still be able to propagate etags in a single query within the same storage, right ?

**Comment by icewind1991** [comment]
Stable/reproducible folder etags will make it difficult/impossible because it will require different etags for the parents, the #20229 trick relies on giving all parents the same etag

But this approach can still give good improvements for etag propagation without stable folder etags

**Comment by PVince81** [comment]
@icewind1991 link to your PR ? Or is it not related ?

**Comment by icewind1991** [comment]
Fix is here: https://github.com/owncloud/core/pull/20439

**Comment by MorrisJobke** [comment]
#20439 was merged yesterday -> closing
