### ISSUE TITLE
As part of the installation process, add a step for enabling certain settings at install time.

### ISSUE THREAD

**Issue by risingfish** [owncloud/core#20233]
What specifically prompted me for this is I would see the "Sync hidden files" as as an option I can enable when installing. I'm sure there are other settings that would make sense to be made available at install.

**Comment by RealRancor** [comment]
Hi,

@risingfish 

You probably mean the setting within the sync client? If yes please re-open at:

https://github.com/owncloud/client/issues

where you can find the issue tracker of the sync client.

**Comment by risingfish** [comment]
ok, cool. I apologize for putting it in the wrong place.
