### ISSUE TITLE
OC 8.2 files_external DrobBox Share Download with Speed from DrobBox

### ISSUE THREAD

**Issue by apg1980** [owncloud/core#20230]
Hello together,

correct mi if i am wrong. I have enabled files_external and addet my drobox, this is working flawless.
I have uploadet a bigger file to drobbox and shared via my owncloud a link to this file which is residing on drobbox. the download speed of that file has the bandwith of my home dsl which is pretty slow.
is it possible to let the user which is getting the share to download with the bandwith of drobbox and not from my owncloud instance hosted on my home dsl?

Best regards.

**Comment by tflidd** [comment]
Drop your dropbox and get a real server (or FTTH) :D

All shares and downloads you create with owncloud must pass through owncloud. If you use external storage, you can of course access this external storage directly* (without owncloud), but in this case you can't create links and set the permissions via owncloud.

*only if you don't use the encryption app

**Comment by apg1980** [comment]
slowly slowly i got my own server. this was just a question for some purposes in case of share a file in a much faster way then my dsl provide it.

**Comment by DeepDiver1975** [comment]
we do not generate the share on dropbox - as a result there is no way to download the shared file from dropbox. The file needs to be downloaded to the owncloud instance and then gets forwarded to the user.

Yes - this is pretty inefficient - but this is the way it works.
