### ISSUE TITLE
Undefined index error after upgrading to 8.2

### ISSUE THREAD

**Issue by Bugsbane** [owncloud/core#20242]
Since upgrading to version 8.2 I've been getting the following error in my logs:
Undefined index: extension at /PATH/TO/MY/owncloud/lib/private/installer.php#267

I'm running Nginx, MariaDB on arkOS (Arch derivative).

What further information would be useful?

**Comment by DeepDiver1975** [comment]
Please let us know which app you are trying to install from the appstore - this error occurs during app installation

**Comment by Bugsbane** [comment]
I just installed a couple, namely the updated versions of calendar, contacts and music.

**Comment by DeepDiver1975** [comment]
> I just installed a couple, namely the updated versions of calendar, contacts and music.

did they all succeed?

**Comment by Bugsbane** [comment]
Yes

**Comment by DeepDiver1975** [comment]
so - this is of lesser criticality

**Comment by Bugsbane** [comment]
It's tagged needsinfo. What info do you need?

**Comment by sonanchenko** [comment]
this appears when I try to update Bookmarks to 0.6 version

**Comment by karlitschek** [comment]
@blizzz

**Comment by blizzz** [comment]
@sonanchenko did the update succeed?

Two of the current bookmark apps tarballs will have no extension when they are being downloaded (hosted on an ownCloud and provided via link share). The missing extension causes the warning, but looking at the code it should not create other issues. @icewind1991

**Comment by sonanchenko** [comment]
@blizzz , which update ?

owncloud update of application one ?
Could you, please, clarify what I shoud check ?

**Comment by blizzz** [comment]
@sonanchenko 

The update of bookmarks to 0.6

**Comment by sonanchenko** [comment]
still can't update to 0.6 from 0.4.
the same issue


2015-11-16 15:05 GMT+02:00 blizzz <notifications@github.com>:

**Comment by blizzz** [comment]
@sonanchenko that's most likely because of https://github.com/owncloud/bookmarks/issues/192#issuecomment-152680430

**Comment by sonanchenko** [comment]
@blizzz I've checked with latest version.
Everything seems OK.
