### ISSUE TITLE
User quota is not read from LDAP in 8.2

### ISSUE THREAD

**Issue by torlasz** [owncloud/core#20249]
Since I upgraded from 8.1 to 8.2, the user quota field defined in LDAP is neglected. Every user gets the default quota specified in LDAP, no matter what I do. The exact same setup worked perfectly until the upgrade. I had to delete the quota field in the LDAP config and set quotas in owncloud locally to be able to assign different quotas to different users again.

**Comment by DeepDiver1975** [comment]
@blizzz mind taking a look?THX

**Comment by lokidaibel** [comment]
Same problem here. Default Quota is beeing used for all LDAP Users even they have some other value in the Quota field. Btw we are using MS AD as Ldap Backend. If you need more imput tell me what to provide.

**Comment by blizzz** [comment]
Fixed with https://github.com/owncloud/core/pull/20093
