### ISSUE TITLE
Updater seems to be broken using asset-pipeline

### ISSUE THREAD

**Issue by codebucketdev** [owncloud/core#20251]
Hello,

I really like ownCloud and I am using it since 2 years from now on. Today I moved my ownCloud installation completly (also with the database and the MySQL users) from my old VPS to my Raspberry Pi, because I wanted to have more storage space using external drives for this purpose. So I downloaded the owncloud folder from my VPS using sftp on my Pi and noticed that ownCloud is running very slow on my Apache2 configuration on my Raspberry Pi. I found out in the FAQ that there is a option called ```asset.pipeline.enabled``` which should cache the assets and enabled this. But now I noticed that the Update section in the Admin panel is broken.

I've attatched a screenshot from this issue, because my english is not good enough to explain that kind of error/bug. (I usually use the stable channel)

![3zeoll](https://cloud.githubusercontent.com/assets/5750114/10903138/d81d67ce-8206-11e5-8227-0f1fd49af326.png)

**Comment by MorrisJobke** [comment]
cc @VicDeo

**Comment by DeepDiver1975** [comment]
Owncloud version?

**Comment by RealRancor** [comment]
This issue is already tracked here: https://github.com/owncloud/updater/issues/184

**Comment by codebucketdev** [comment]
I am using ownCloud version 8.2 stable on a Raspberry Pi B+ with Raspbian Wheezy. The data storage is on a external drive.

**Comment by DeepDiver1975** [comment]
> This issue is already tracked here: owncloud/updater#184

THX

**Comment by codebucketdev** [comment]
thanks, seems like I have to disable this option until the next update :+1:
