### ISSUE TITLE
upgrade from owncloud-server 8.1.3-13.1 to  8.1.4-12.1 stuck on maintenance mode

### ISSUE THREAD

**Issue by jsalatiel** [owncloud/core#20257]
I have upgraded from  owncloud-server:all 8.1.3-13.1 to 8.1.4-12.1 using apt-get and now i am stuck on maintenance mode.

I tried manually run php occ upgrade , it updated a few package but kept the maintenance mode. If i try to rerun , now it shows Maybe an upgrade is already in process. Please check the logfile (data/owncloud.log). If you want to re-run the upgrade procedure, remove the "maintenance mode" from config.php and call this script again.

Environment
Server Configuration

OS: Debian Jessie 3.16.0-4-amd64
Web server: Apache2 2.4.10-10+deb8u3
Database: MySQL 5.5.46-0+deb8u1
PHP version: 5.6.14+dfsg-0+deb8u1
ownCloud version: 8.1.4-12.1

**Comment by wrst** [comment]
I had that issue on and upgrade with a similar system this morning. I edited the config.php and changed the line 'maintenance' => true, to 'maintenance' => false, had owncloud open in another browser window and it took just a few seconds to pick up on the change and I was able to log in.

**Comment by LukeOwncloud** [comment]
I had the same problem when updating to 8.2.0.12. I switched off the maintainence mode manually. 

    sudo -uwww-data ./occ maintenance:mode --off

Then everything was back to normal. I do not have any further logs unfortunately.

**Comment by RealRancor** [comment]
@LukeOwncloud For oC 8.2 this is the expected behaviour as stated in this blogpost: https://owncloud.org/blog/upgrading-to-owncloud-server-8-2/

Seems that should be better communicated (as always :-/)
