### ISSUE TITLE
error Message after update

### ISSUE THREAD

**Issue by ojohann** [owncloud/core#20250]
Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "contacts_index" as such route does not exist.

**Comment by bwildenhain** [comment]
Got the same message, Debian 8.2 (jessie) when upgrading from ownCloud 8.1.3-13.1
  to 8.1.4-12.1

**Comment by MorrisJobke** [comment]
@Xenopathic Looks like https://github.com/owncloud/core/issues/18861 is back somehow. Any idea what this could cause now?

**Comment by DeepDiver1975** [comment]
@MorrisJobke #18861 is only applied to 8.2 - nothing has been backported.
And we should not backport that fix -> won't fix for be in any version previous to 8.2

**Comment by RealRancor** [comment]
Dup of https://github.com/owncloud/core/issues/19145, https://github.com/owncloud/core/issues/20125, https://github.com/owncloud/core/issues/20207 and some more.

https://github.com/owncloud/core/issues/19145 is still open

**Comment by andrenarchy** [comment]
Same here on Ubuntu 14.04 after upgrading 8.1.3-13.1 to 8.1.4-12.1.
