### ISSUE TITLE
User mgnt: Weird error messages on not allowed rename

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#20254]
> But it works for me in master?

No, but the (visible) messages are different:
1. Go to Users page.
2. Attempt to delete an LDAP User, here Zombie15, by clicking on the trash icon.

![y a a y 4](https://cloud.githubusercontent.com/assets/2184312/9601127/ef514cdc-509f-11e5-8c9a-5ce9ecbe68f0.png)

So far so good.

Network Log for this step:

![y a a y 4](https://cloud.githubusercontent.com/assets/2184312/9601289/b5189aba-50a0-11e5-949f-cc88746303e8.png)
1. Attempt to delete another LDAP User, here Zombie16, by clicking on the trash icon.

![y a a y 4](https://cloud.githubusercontent.com/assets/2184312/9601152/12c58afc-50a0-11e5-9acc-67a5efc9f680.png)

Repeated Message! And a little bit later:

![y a a y 4](https://cloud.githubusercontent.com/assets/2184312/9601166/29a26c18-50a0-11e5-8dbd-15213ddbbcbb.png)

Click messages away.

Network Log for this step:

![y a a y 4](https://cloud.githubusercontent.com/assets/2184312/9601316/d9ee9088-50a0-11e5-84fd-d55f650ac316.png)
1. Attempt to delete another LDAP User, here Zombie17, by clicking on the trash icon:

![y a a y 4](https://cloud.githubusercontent.com/assets/2184312/9601195/4db5c7ee-50a0-11e5-92b6-8ede7f978d3f.png)

Failed to delete Zombie16!

![y a a y 4](https://cloud.githubusercontent.com/assets/2184312/9601205/54e3a202-50a0-11e5-8e3f-f4567084d0af.png)

Now message about Zombie17.

Network Log for this step:

![y a a y 4](https://cloud.githubusercontent.com/assets/2184312/9601330/f29aab08-50a0-11e5-90c2-3e45601c542e.png)
1. Reload the page by pressing F5:

![y a a y 4](https://cloud.githubusercontent.com/assets/2184312/9601232/7870a3fa-50a0-11e5-96da-6a456c6ee879.png)

Is visible before the reloading is completed.

Also here the last delete operation is retried:

![y a a y 4](https://cloud.githubusercontent.com/assets/2184312/9601344/1871e6d4-50a1-11e5-9b7d-668a5da91d5b.png)

That's now all against master, but the same symptoms i see on the backport.

From https://github.com/owncloud/core/pull/18566#issuecomment-136660341

cc @blizzz

**Comment by PVince81** [comment]
@MorrisJobke is this still happening in 8.2.2 or 9.0 RC1 ?

**Comment by MorrisJobke** [comment]
> @MorrisJobke is this still happening in 8.2.2 or 9.0 RC1 ?

yes. Current master - still the same

**Comment by PVince81** [comment]
@owncloud/ldap are you able to reproduce this on 9.0.4 or 9.1 ?

**Comment by PVince81** [comment]
Please reopen if issue persists on 10.0.4
