### ISSUE TITLE
Disabled checkboxes not distinguishable from others with the new checkbox style

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#20255]
Browser default:
![personal_-_owncloud_-_2015-11-03_09 14 02](https://cloud.githubusercontent.com/assets/213943/10903574/5f86d3fe-820b-11e5-81bc-9d953436abf0.png)

Same boxes with ownClouds new checkbox style:
![personal_-_owncloud_-_2015-11-03_09 14 14](https://cloud.githubusercontent.com/assets/213943/10903577/71e00b88-820b-11e5-82aa-4fb8d39038c2.png)

I think this needs improvements...

cc @Henni @jancborchardt

**Comment by Henni** [comment]
@jancborchardt we might need additional checkbox images here.
For checked checkboxes opacity works to show the disabled state, but unchecked checkboxes are almost indistinguishable.

**Comment by jancborchardt** [comment]
@Henni is it possible to use a separate image for disabled state? Then I can create one with grey-ish fill instead of white.

**Comment by Henni** [comment]
@jancborchardt yes it is possible. That would be great!

**Comment by nickvergessen** [comment]
Fixed with #20530 and #20991

**Comment by nickvergessen** [comment]
Final result https://github.com/owncloud/core/pull/20991#issuecomment-162571200
