### ISSUE TITLE
Local ignore list file like ".gitignore"

### ISSUE THREAD

**Issue by oruchreis** [owncloud/core#20260]
We can set ignore patterns through global ignore list. But it will be useful if we can create ignore lists per directory like .gitignore files. For instance, we can put an ignore list file per project directory that includes patterns for bin folder, so if we add a new project directory to the cloud, we simply copy this ignore list file to new project directory.

**Comment by PVince81** [comment]
This is probably more something for the different clients, not the server, because the clients are the ones that need to decide what to sync and what not.

**Comment by MorrisJobke** [comment]
I would also move this to client side.

**Comment by karlitschek** [comment]
yes. please open this in the client repository. thanks :-)

**Comment by janphigoe** [comment]
Could you provide a link to the respective issue in the client repository?
