### ISSUE TITLE
File Comments Data Structure

### ISSUE THREAD

**Issue by blizzz** [owncloud/core#20265]
Contributes to #16328 

Comment:
* [ ] id, INTEGER
* [ ] parentid (on replies to comments), INTEGER
* [ ] topmostparentid, INTEGER
* [ ] level,  INTEGER
* [ ] children-count, INTEGER
* [ ] message, CLOB
* [ ] actorid (== userid), TEXT
* [ ] actortype, TEXT
* [ ] verb (= 'comment'), TEXT
* [ ] timestamp, INTEGER
* [ ] latestchildtimestamp, INTEGER
* [ ] objectype, STRING
* [ ] objectid, STRING

The chosen way to identify comments as unread is to keep a "last seen time" timestamp per user and file, which applies to all file activities (like updates). This would be  implemented within the Timelime logic and structure (https://github.com/owncloud/core/issues/20259).

In general, a thing to ensure is it that userids are compatible with federation.

@nickvergessen @PVince81  @DeepDiver1975 @jancborchardt

**Comment by nickvergessen** [comment]
fileid is not always int (depends on the storage)

**Comment by PVince81** [comment]
Please replace "(Un)read status, per comment version:" with "last read status". We don't want each comment to have a flag. We only need the last read date for each file, so the fields would be "fileid, userid, lastdate"

**Comment by blizzz** [comment]
@nickvergessen @PVince81 adjusted

**Comment by DeepDiver1975** [comment]
commantid -> id

**Comment by blizzz** [comment]
:heavy_check_mark:

**Comment by PVince81** [comment]
- [ ] filelid must be string from now on

**Comment by nickvergessen** [comment]
object type and object id please instead of file id

**Comment by DeepDiver1975** [comment]
children-count

**Comment by blizzz** [comment]
updated the encryption. Set the object type to string, is more explanatory than numbers, especially in URLs.

**Comment by nickvergessen** [comment]
timestamp of last child for sorting?

**Comment by blizzz** [comment]
yes, added

**Comment by blizzz** [comment]
If we want to totally keep a hierarchy possible that is deeper than just one level, we'd need to add a topmostparentid in order to be able to cheaply detect the root of the thread. We agreed that in the file comments matter, 1-level depth might be considerable in future. However, this does not need to apply to all possible use cases of the comments infrastracture. What do you think?

**Comment by blizzz** [comment]
@DeepDiver1975 @PVince81 @nickvergessen ^

**Comment by nickvergessen** [comment]
Well consensus was to make it possible to have it nested.
But we could also not add it now and then when we ever need it, add it.

**Comment by blizzz** [comment]
Adding it later does not sound too desirable. If you need to determine those parents for millions of comments upon update. Well, you could skip that and only determine that column on demand and/or specific cli call, but we'd need to carry this load forever. Better we do it now or not, let's do this. In our first implementation, it'll be always 0 anyways.

**Comment by blizzz** [comment]
we need another field, see https://github.com/owncloud/core/pull/20562/files#r45613011. I'll add it to the description.
