### ISSUE TITLE
[Firefox] Search button is lined with a red line

### ISSUE THREAD

**Issue by davitol** [owncloud/core#20268]
### Steps to reproduce

1.- Log in owncloud using Firefox as browser

### Expected behaviour

The search button should not be marked in red

### Actual behaviour

The search button is lined with a red line

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** ownCloud Enterprise Edition 9.0 pre alpha (daily) Build:2015-11-03T04:35:03+00:00 0559b2092cc9db3537576c8117bf3b165fc90728

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:** 

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```

```
### Client configuration

**browser**
 Firefox

![screen shot 2015-11-03 at 14 06 52](https://cloud.githubusercontent.com/assets/10596560/10908929/8d1ba0c2-8235-11e5-8495-125c81555a8a.png)

**Comment by schiesbn** [comment]
fixed here: https://github.com/owncloud/core/pull/20256
