### ISSUE TITLE
New layer wrapping the view?

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#20263]
We need a way for two of our apps to do stuff "on a view" level in cases files are read/changed/deleted/etc.

The first app blocks access (FFW), the second app will [set tags](https://github.com/owncloud/core/issues/20258).

The problems with existing stuff:
### WebDAV plugin
- Apps work around it, therefor access blocking/auto tagging is not completly possible

### Storage (wrapper) level
- To low level
- Missing file id or full path in some actions?

### Hooks
- Exceptions are killed, so only `$run = false` would be possible which is insufficient

Now after some thoughts @PVince81 and I came up with a new idea: View Wrappers
The view always contains the full path (and its resolvable to an id).

The only problem here is, that currently all Apps instantiate the class directly `new View($path)`.
The idea would be to create a factory that hands out the view and takes care of the wrapping.

cc @DeepDiver1975 @PVince81 @icewind1991

**Comment by PVince81** [comment]
If we agree with view wrappers, the steps to proceed would be the following:
1) Introduce `\OC::$server->getViewManager()` (or something similar to the Node API names)
2) Replace all occurrences of `new View` with getViewManager()
3) optionally: rename the "View" class to "OldView". This will purposefully break apps that used this private API that they weren't supposed to
4) Implement view wrapper logic in the ViewManager / ViewFactory
5) Have apps register their view wrappers to do their things they couldn't do on the other layers (btw, Locking would have been one of them)

**Comment by icewind1991** [comment]
I don't think it's needed and I don't really like adding more levels of indirection.

> Missing file id or full path in some actions?

During storage wrapper setup you have access to the mountpoint, pass it to your wrapper and you can get full paths

**Comment by nickvergessen** [comment]
Other Idea: don't kill Exceptions in hooks?

**Comment by DeepDiver1975** [comment]
Hooks are a pain with respect to unit testability

**Comment by nickvergessen** [comment]
Does that mean "No"?

**Comment by PVince81** [comment]
Triggering hooks from a test should be easier to test than testing whether a hook was triggered.
So far it seems the hooks solution is the best compromise.

**Comment by nickvergessen** [comment]
Okay, so the steps are:

1. Remove the Exception killing, (or define a public exception which is rethrown, if we don't want this for all exceptions)
2. Add a hook to View::getDirectoryContent

**Comment by PVince81** [comment]
As discussed :+1: 

Any objections @icewind1991 @DeepDiver1975 ?

**Comment by icewind1991** [comment]
@nickvergessen what is it you're actually trying to do?

**Comment by DeepDiver1975** [comment]
Having another look at the issue I fear that the view is not the correct place to intercept.
We need to move this to the storage level. In the view there is the possibility to bypass the view logic totally by getting the storage in resolvePath.
