### ISSUE TITLE
Exception: Failed to open archive when installing app when updating 8.0.4-1 to 8.1.4-12.1

### ISSUE THREAD

**Issue by Mad-Halfling** [owncloud/core#20262]
Updating to 8.1.4 and had the following update output:-
Updating ownCloud to version 8.1.4, this may take a while.

Set log level to debug - current level: "Warning"
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Updated "files" to 1.1.10
Updated "activity" to 2.0.2
Updated "files_sharing" to 0.6.3
Updated "files_trashbin" to 0.6.3
Updated "files_versions" to 1.0.6
Exception: Failed to open archive when installing app

Loading up the login page again (in a new tab, to retain the errors) and running the upgrade again fixed the issue, but I thought I'd report it.

Running on 5.5.30-1
Ubuntu 12.04
Apache 2.4.16

**Comment by Mad-Halfling** [comment]
Ah, just found out what the error is - it's the Bookmarks app, it's failing to update from v0.4 to v0.5

**Comment by RealRancor** [comment]
Yes, as discussed in the still open issue here: https://github.com/owncloud/core/issues/20237#issuecomment-153247800
