### ISSUE TITLE
Client Window keeps popping up on Ubuntu 14.04

### ISSUE THREAD

**Issue by leftyfb** [owncloud/core#20270]
owncloud-client 2.0.2-3 installed from http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/xUbuntu_14.04/ running on Ubuntu 14.04.3.

Upon boot, the owncloud client window pops up. Moments after closing it, it will open up again. This will go on forever unless I close owncloud completely from the notification area.

**Comment by RealRancor** [comment]
Hi,

@leftyfb The issue tracker of the sync client is located here: https://github.com/owncloud/client/issues

Please re-open there by using the issue template provided here: https://raw.githubusercontent.com/owncloud/client/master/issue_template.md

**Comment by karlitschek** [comment]
@jnweiger

**Comment by RealRancor** [comment]
@karlitschek Its now reported here: https://github.com/owncloud/client/issues/4065

@leftyfb You can click on the "Close" button below the comment box to close here.
