### ISSUE TITLE
Error log during writing to GDrive

### ISSUE THREAD

**Issue by ayumn** [owncloud/core#20275]
### Steps to reproduce
1. connect GDrive with Owncloud
2. Upload a new file using the owncloud sites direct upload

### Expected behaviour
No error log should exist

### Actual behaviour
the file gets created sucessfully in GDrive every time but with this error log

### Server configuration
**Operating system**: FreeBSD 9.3

**Web server:** lighttpd

**Database:** mysql

**PHP version:** 5.6

**ownCloud version:** 8.2

**Updated from an older ownCloud or fresh install:** -

**List of activated apps:** default +calendar +contacts -filelocking

```
<?php
$CONFIG = array (
  'instanceid' => '112233445566',
  'passwordsalt' => '0987654321',
  'secret' => '1234567890',
  'trusted_domains' =>
  array (
    0 => 'example.de',
    1 => '192.168.1.126',
  ),
  'datadirectory' => '/mnt/tank/owncloud/data',
  'overwrite.cli.url' => 'https://example.de',
  'dbtype' => 'mysql',
  'version' => '8.2.0.12',
  'dbname' => 'xxx',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'logtimezone' => 'UTC',
  'installed' => true,
  'forcessl' => true,
  'preview_libreoffice_path' => '/usr/local/bin/libreoffice',
  'filesystem_check_changes' => 1,
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
  ),
  'filelocking.enabled' => 'true',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
);
```
**Are you using external storage, if yes which one:** GDrive
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** Webdav

### Client configuration
**Browser:** Firefox 41

**Operating system:** debian

#### ownCloud log (data/owncloud.log)
```
Error 
hook
error while running hook (OCA\Activity\FilesHooksStatic::fileCreate): An exception occurred while executing
'INSERT INTO `oc_activity` (`app`, `subject`, `subjectparams`, `message`, `messageparams`, `file`, `link`, `user`, `affecteduser`, `timestamp`, `priority`, `type`, `object_type`, `object_id`)
VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'
with params ["files", "created_self", "[\"\\\/GDrive\\\/Test\\\/test.txt\"]", "", "[]", "\/GDrive\/Test\/test.txt",
"https:\/\/192.168.1.126\/index.php\/apps\/files?dir=%2FGDrive%2FTest", "User", "User",
1446583797, 30, "file_created", "files", 46327]:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'object_type' in 'field list'
```

**Comment by MorrisJobke** [comment]
This looks like the same problem as in #20276.

Please try the steps in https://github.com/owncloud/core/issues/20276#issuecomment-153589686

If this doesn't fix the issue we can reopen this ticket.

**Comment by ayumn** [comment]
worked. Thanks.
removed the folder activity and extract the new folder activity from the 8.2 oC.tar.bz2 file
