### ISSUE TITLE
8.2.0 introduced high disk load with PROPFIND

### ISSUE THREAD

**Issue by LeCoyote** [owncloud/core#20277]
I upgraded from 8.1.3 to 8.2.0 recently. I quickly noticed an increase in IO operations: iowait stats increased by a x10 factor. This happens with the 2.0.2 desktop client *without* any syncing activity (ie. no files are copied in any direction). Each PROPFIND request from the client takes about 10 seconds to process (only 1 client) with the CPU at 90%+ IO usage. The corresponding client request is OCC::RequestEtagJob

Similarly, getting index.php/apps/files to display in a browser is much longer than it used to be.

### Server configuration
**Operating system**: linux 3.14

**Web server:** apache 2.2.31

**Database:** sqlite3

**PHP version:** 5.5.30

**ownCloud version:** 8.2.0

**Updated from an older ownCloud or fresh install:** from 8.1.3

**List of activated apps:** 
  - calendar: 0.8.0
  - contacts: 0.5.0.0
  - documents: 0.11.0
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_versions: 1.1.0
  - gallery: 14.2.0

**The content of config/config.php:**

{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/cloud\/htdocs\/owncloud\/data",
        "dbtype": "sqlite3",
        "version": "8.2.0.12",
        "installed": true,
        "instanceid": "509758b965ca6",
        "loglevel": 1,
        "theme": "",
        "maintenance": false,
        "trusted_domains": [
            "cloud.domain.tld"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***"
    }
}

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Operating system:** Windows, Linux, Mac

#### Web server error log
No errors.

#### ownCloud log (data/owncloud.log)
No relevant log since upgrade

**Comment by karlitschek** [comment]
@icewind1991

**Comment by MorrisJobke** [comment]
@LukasReschke Is this a duplicate of https://github.com/owncloud/core/issues/19888 ?

**Comment by LeCoyote** [comment]
Quite possibly. I had not came across this PR before. I guess I could try enabling Redis and see if it helps, in which case it would definitely be a duplicate.

**Comment by LeCoyote** [comment]
It definitely is a duplicate. Redis eliminated the issue. Thanks!
