### ISSUE TITLE
Upgrade error: ..."contacts_index" as such route does not exist.

### ISSUE THREAD

**Issue by Amgine0** [owncloud/core#20278]
Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "contacts_index" as such route does not exist.

**Comment by Amgine0** [comment]
./occ upgrade 
```bash
An unhandled exception has been thrown:
OC\HintException: [0]: Missing memcache class \OC\Memcache\APC for local cache (Is the matching PHP module installed and enabled ?)
```
I am using APC, the php module is installed and is working dandy according to various other scripts using it.

**Comment by RealRancor** [comment]
Dup of #19145, #20125, #20207 and some more.

#19145 is still open

Really wonder why people are not finding those duplicates?

For the memcache see:

https://doc.owncloud.org/server/8.1/admin_manual/configuration_server/caching_configuration.html#additional-config-for-background-job-cron-and-occ-command-line-tool
