### ISSUE TITLE
Allow non-admin users to see members of their groups

### ISSUE THREAD

**Issue by pjrobertson** [owncloud/core#20282]
I have set up multiple groups (e.g. HR, Developers, Management etc.) for my users so that they can share files with each other easily.

Unfortunately, it seems very difficult for non-admin user to see the groups they are in, especially when sharing files. I have only just found out that the groups users are part of are shown under their 'Personal' page. Here are my suggestions:
- [ ] Ideally, there should be another page called 'Groups' that shows which groups a member is a part of, and who is in those groups.

As a **quick fix**, the following could be done:
- [ ] On the 'Personal' page there be an anchor on the left hand side to 'Groups'
- [ ] In the 'Groups' section, all users who are members of each group should be listed

**sharing files**
- [ ] when clicking the 'share' button in the files app there should be a link showing all the user's groups, or ideally a list of all users (not sure if this is advisable e.g. when using LDAP)
- [ ] Perhaps when hovering over the 'i' it could say "You can share with people in these groups..."

**Comment by MorrisJobke** [comment]
> Ideally, there should be another page called 'Groups' that shows which groups a member is a part of, and who is in those groups.

I don't think we will do that - there was a discussion about this some months ago cc @owncloud/designers 

> On the 'Personal' page there be an anchor on the left hand side to 'Groups'

That is an actual issue.

> In the 'Groups' section, all users who are members of each group should be listed

I don't think we will do this because of information disclosure - cc @LukasReschke 




> Perhaps when hovering over the 'i' it could say "You can share with people in these groups..."

Think of instances with 100s of groups

> when clicking the 'share' button in the files app there should be a link showing all the user's groups, or ideally a list of all users (not sure if this is advisable e.g. when using LDAP)

Same here - this doesn't scale well with thousand of users.

**Comment by MorrisJobke** [comment]
> > On the 'Personal' page there be an anchor on the left hand side to 'Groups'
> That is an actual issue.

@owncloud/designers Currently there is only the "personal info" label in the sidebar that groups password, display name, email, groups and the avatar. Should this really be changed?

**Comment by pjrobertson** [comment]
I've created a pull request with a few simple ideas.

To answer your points:

>> Ideally, there should be another page called 'Groups' that shows which groups a member is a part of, and who is in those groups.

> I don't think we will do that - there was a discussion about this some months ago

Fair enough, I understand 

>> On the 'Personal' page there be an anchor on the left hand side to 'Groups'
> That is an actual issue.

This is fixed in my PR

>> In the 'Groups' section, all users who are members of each group should be listed
> I don't think we will do this because of information disclosure - cc @LukasReschke

If information disclosure really is a big issue, then in reality the 'autocomplete' feature that shows users when sharing a file shouldn't be enabled. I could, if I really wanted, type every combination of letters and see everyone who has an account on my ownCloud instance (OK, it is a hassle to do in reality).

How about this: we have an admin option to "allow users to see members in their group", disabled by default (to keep the current setup). If an admin enabled it, then my changes (2nd commit) could be enabled, and searching could be made easier.

>> Perhaps when hovering over the 'i' it could say "You can share with people in these groups..."
> Think of instances with 100s of groups

OK then, maybe just a list of the groups the user can share with. That would be simpler (and avoid info disclosure). I see the share dialogues are javascript, which is a bit more tricky for me to get my head round, so I haven't done this (yet).

**Comment by jancborchardt** [comment]
Let’s look a bit more long-term here.

Especially with more focus on sharing and making it visually attractive by showing profile images etc, I think that the »Users« page should not be an admin-only thing anymore. Normal users should also be able to read-only the people and groups which they are part of or which they know.

The current solution with just showing the groups in the Personal page is quite the afterthought and doesn’t really provide a lot of value. We also often have the request for ad-hoc groups which are user-specific – that is that I could create a group which is not global. This would also be solved by making the Users page not admin-only anymore.

What do you think @karlitschek @LukasReschke @DeepDiver1975 @PVince81?

**Comment by MorrisJobke** [comment]
also @butonic had some thoughts on this.

**Comment by karlitschek** [comment]
Interesting idea. What do you think @MTRichards

**Comment by MTRichards** [comment]
I would suggest that this also merges nicely with the concept of having local user defined groups. For example, if you share with 4 people all the time, you would want to create a group for those 4 people to make it easier to share.

Would be interesting. Certainly something for after 9 I think, but an interesting feature update.

**Comment by butonic** [comment]
I don't think the users page should be exposed to all users. Ad Hoc groups sounds more like contacts integration is for: you create a group in your contacts and can use it in the sharing dialog. What @MorrisJobke is referring to is [my guest app](https://github.com/butonic/guests) that allows jailing 'guests' to a certain set of apps and makes their home storage readonly. One of the ways to identify a user as a guest is by creating a guest account on the fly when an email is entered in the sharing dialog. I plan to extend that to contacts and groups.

**Comment by jancborchardt** [comment]
If you look at the case of our internal ownCloud for example: Users and Contacts almost exactly match each other. Hence this really calls for combination, we just need to see how to best do it.

**Comment by hamzaadamu** [comment]
Users can read only the group to which they belong by clicking a hyperlink in their users' page; this will enable them to get their group status.

**Comment by PVince81** [comment]
Renamed subject and added "see members of their groups".

It is already possible to see the group names in the settings page.

**Comment by pjrobertson** [comment]
@JanAckermann - for future reference (e.g. people finding this from Google etc.) can you please explain the reason for closing this issue? Was it fixed, and if so - where?

Thanks!
