### ISSUE TITLE
Apps upgrade: Deactivated apps say they are activated (inconsitent)

### ISSUE THREAD

**Issue by alexara** [owncloud/core#20284]
Hi!

The Owncloud updater is unfortunately not reliable as it always tells that the latest version is running. That's why I always upgrade more or less like this: 
```
Activate maintence mode
wget owncloud.zip && unzip owncloud.zip && cp -r owncloud/* /path/to/owncloud
```
For an unknown reason the activity app was not upraded to the latest version.
This led to a bug where I was adviced to delete ```owncloud/apps/activity``` folder and to replace it by the one from the oC.zip package.
I decided to delete and replace all apps just to go sure.

It seems that Owncloud only activates some standard apps by default. Other apps, which were activated before, must be activated manually again. (annoying).
However, at this point an inconsitency occurs:
Non-standard apps become deactivated but the button below the app's name indicate the opposite as the following screenshot illustrates:

![owncloud_apps_deactivated](https://cloud.githubusercontent.com/assets/13819719/10933724/ea4a1f12-82da-11e5-9601-287e2c63d1fe.png)

**Comment by RealRancor** [comment]
@alexara 
Your way of upgrading is not correct. Yyou shouldn't just copy over the newer files over the old unes during an upgrade. Thats the reason why you're seeing this issue. Please follow the upgrading steps provided here:

https://doc.owncloud.org/server/8.2/admin_manual/maintenance/upgrade.html#manual-upgrade-procedure

**Comment by alexara** [comment]
> Your way of upgrading is not correct. You shouldn't just copy over the newer files over the old ones during an upgrade. Thats very likely the reason why you're seeing this issue. Please follow the upgrading steps provided here:

> https://doc.owncloud.org/server/8.2/admin_manual/maintenance/upgrade.html#manual-upgrade-procedure

@RealRancor You might be right. I will close this thread then and follow the instruction given in your link next time. However, if the same errors occur again I will reopen it.
