### ISSUE TITLE
Download problems

### ISSUE THREAD

**Issue by danieanna** [owncloud/core#20281]
Goodmorning everyone,
first of all I installed ubuntu 14.4 lts server version and use owncloud 8.1.3 and apache2 , but I have problems when I perform downloads . In fact, when I try to download multiple files of different sizes and my connection drops below 100K , one of the download stops to give more bandwidth to others.
You know tell me why ?

Thanks.

**Comment by MorrisJobke** [comment]
> You know tell me why ?

Sadly not :( If there is no specific error we can't do much. I you have a specific error you can fill out the issue template https://github.com/owncloud/core/blob/master/issue_template.md

Beside that we always try to improve the performance. But for a optimized setup you should better ask in the forum: http://forum.owncloud.org

Thanks
