### ISSUE TITLE
[PERSONAL] Not possible to save Full name

### ISSUE THREAD

**Issue by rperezb** [owncloud/core#20290]
STEPS:
1.- Create a user, user1
2.- Login as user1
3.- Access to personal
4.- Select to modify the full name

CURRENT BEHAVIOR:
it keeps "saving" forever

EXPECTED:
The full name is saved

### LOGS

````
Error	PHP	Invalid argument supplied for foreach() at /opt/owncloud/settings/users.php#76	2015-11-04T10:02:13+00:00
Error	PHP	Undefined variable: subAdmins at /opt/owncloud/settings/users.php#76
````

ownCloud Enterprise Edition 9.0 pre alpha (daily) Build:2015-11-04T04:38:58+00:00 5a25f1c2a0b77e42db6881a3c5c5ca49fb39b563

**Comment by rperezb** [comment]
@LukasReschke does this ring any bell?

**Comment by DeepDiver1975** [comment]
This was just fixed

**Comment by DeepDiver1975** [comment]
https://github.com/owncloud/core/pull/20283
