### ISSUE TITLE
[Ubuntu 14.04.3 LTS] Owncloud does not restart after dist-upgrade

### ISSUE THREAD

**Issue by marcorighi** [owncloud/core#20293]
This morining Owncloud server does not restart after the upgrade. Using firefox it is shown the maintenace page. Follows details on installed package.

Write me for further information.

Best
Marco

dpkg -s  owncloud-server
Package: owncloud-server
Status: install ok installed
Priority: optional
Section: devel
Installed-Size: 77877
Maintainer: Jürgen Weigert <jw@owncloud.com>
Architecture: all
Source: owncloud
Version: 8.1.4-12.1
Replaces: owncloud (<< 7.9.9), owncloud-3rdparty (<< 8.1.4-12.1~), owncloud-app-activity (<< 8.1.4-12.1~), owncloud-app-encryption (<< 8.1.4-12.1~), owncloud-app-external (<< 8.1.4-12.1~), owncloud-app-files (<< 8.1.4-12.1~), owncloud-app-files-encryption (<< 8.1.4-12.1~), owncloud-app-files-external (<< 8.1.4-12.1~), owncloud-app-files-locking (<< 8.1.4-12.1~), owncloud-app-files-pdfviewer (<< 8.1.4-12.1~), owncloud-app-files-sharing (<< 8.1.4-12.1~), owncloud-app-files-texteditor (<< 8.1.4-12.1~), owncloud-app-files-trashbin (<< 8.1.4-12.1~), owncloud-app-files-versions (<< 8.1.4-12.1~), owncloud-app-files-videoviewer (<< 8.1.4-12.1~), owncloud-app-firstrunwizard (<< 8.1.4-12.1~), owncloud-app-gallery (<< 8.1.4-12.1~), owncloud-app-provisioning-api (<< 8.1.4-12.1~), owncloud-app-templateeditor (<< 8.1.4-12.1~), owncloud-app-updater (<< 8.1.4-12.1~), owncloud-app-user-external (<< 8.1.4-12.1~), owncloud-app-user-ldap (<< 8.1.4-12.1~), owncloud-app-user-webdavauth (<< 8.1.4-12.1~)
Depends: php5 (>= 5.4.0), php5-mysqlnd | php5-mysql, php5-sqlite, php5-pgsql, php5-common, php5-gd, php-xml-parser, php5-intl, php5-mcrypt, php5-curl, php5-json, php5-ldap, php5-cli
Suggests: php5-apcu (>= 4.0.6) | php-apc
Breaks: owncloud (<< 7.9.9), owncloud-3rdparty (<< 8.1.4-12.1~), owncloud-app-activity (<< 8.1.4-12.1~), owncloud-app-encryption (<< 8.1.4-12.1~), owncloud-app-external (<< 8.1.4-12.1~), owncloud-app-files (<< 8.1.4-12.1~), owncloud-app-files-encryption (<< 8.1.4-12.1~), owncloud-app-files-external (<< 8.1.4-12.1~), owncloud-app-files-locking (<< 8.1.4-12.1~), owncloud-app-files-pdfviewer (<< 8.1.4-12.1~), owncloud-app-files-sharing (<< 8.1.4-12.1~), owncloud-app-files-texteditor (<< 8.1.4-12.1~), owncloud-app-files-trashbin (<< 8.1.4-12.1~), owncloud-app-files-versions (<< 8.1.4-12.1~), owncloud-app-files-videoviewer (<< 8.1.4-12.1~), owncloud-app-firstrunwizard (<< 8.1.4-12.1~), owncloud-app-gallery (<< 8.1.4-12.1~), owncloud-app-provisioning-api (<< 8.1.4-12.1~), owncloud-app-templateeditor (<< 8.1.4-12.1~), owncloud-app-updater (<< 8.1.4-12.1~), owncloud-app-user-external (<< 8.1.4-12.1~), owncloud-app-user-ldap (<< 8.1.4-12.1~), owncloud-app-user-webdavauth (<< 8.1.4-12.1~)
Description: The owncloud-server package

**Comment by RealRancor** [comment]
Maybe now the same behavior as for the oC 8.2 packages that you need to disable maintenance mode after running the upgrade:

https://owncloud.org/blog/upgrading-to-owncloud-server-8-2/

**Comment by RealRancor** [comment]
Got some additional questions about this at the forums: https://forum.owncloud.org/viewtopic.php?f=21&t=31321

@jnweiger Is the new behaviour of the oC 8.2 packages also ported to 8.1.4?

**Comment by RealRancor** [comment]
Might be also a dup of https://github.com/owncloud/core/issues/20257

**Comment by MorrisJobke** [comment]
> @jnweiger Is the new behaviour of the oC 8.2 packages also ported to 8.1.4?

Yes. The packages now doesn't run the `occ upgrade` step anymore, because it caused a lot of trouble. I will try to get more details and then send an email to devel@.. and user@... mailing list.

AFAIK this was ported to all available packages during the last maintenance release cycle.

**Comment by MorrisJobke** [comment]
cc @jnweiger ^
