### ISSUE TITLE
[JS] All javascript file should be compiled with closure to find syntax errors

### ISSUE THREAD

**Issue by cryptomilk** [owncloud/core#20299]
All javascript file should be compiled with closure to find syntax errors. Closure has warnings and errors and it would reveal issues in the code if the developer doesn't use closure. The best would be to have this as part of the CI. Not only for the core but also for the apps.

Learn more at:

https://developers.google.com/closure/compiler/

**Comment by dragotin** [comment]
@DeepDiver1975 what do you think?

**Comment by DeepDiver1975** [comment]
Good idea - contributions welcome. ;-)

**Comment by gladiac** [comment]
I only contribute to C code ;-)

**Comment by karlitschek** [comment]
The only thing to keep in mind is that we don't want to introduce an additional step for contributors and developers. We could do this as part of packaging or testing.

**Comment by DeepDiver1975** [comment]
> The only thing to keep in mind is that we don't want to introduce an additional step for contributors and developers.

This is nothing for contributors to worry about - we already have a ci job which executes the javascript unit tests in code. Executing this closure compiler as a sub step of this job will allow us to detect syntax errors in all js files.

Just to clarify: we will not checkin compiled js code. The compiler is only used to verify the js code.

**Comment by karlitschek** [comment]
@DeepDiver1975 Great. Exactly my idea :-)

**Comment by rullzer** [comment]
Initial PR in #21300

**Comment by PVince81** [comment]
Could be added to the Makefile or the JS unit test suite
