### ISSUE TITLE
Allow external storage backends to provide a custom icon for their folders

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#20305]
External storage backends must be extended to be able to provide custom icons for their folders.

- [ ] add a method `getFolderIcon()` on the Backend could return "app name" + "path" to the icon that represents the mount point
- [ ] pass the icon back somehow to the files app (need to clear out how to do it)
- [ ] modify files UI code to support custom icons in every place where the generic ext storage icon is specified. Note that as per 9.0 it is possible to specify "data-icon" on the "tr" element to override the folder icon

@jmaciasportela @Xenopathic @icewind1991

**Comment by codebucketdev** [comment]
+1

**Comment by jmaciasportela** [comment]
I have been checking how files_external manage their icon and I realized that is not managed by files_external but files app.

- formatFileInfo: detect if is external mountPoint and add mountType attibute
https://github.com/owncloud/core/blob/master/apps/files/lib/helper.php#L163

add mountType => external-root or external 

- _createRow
https://github.com/owncloud/core/blob/master/apps/files/js/filelist.js#L923

Check mountType and if starts with "external" --> icon = OC.MimeType.getIconUrl('dir-external');

- getIconUrl: return folder-external icon (SVG or PNG)
https://github.com/owncloud/core/blob/master/core/js/mimetype.js#L70


My proposal is modify formatFileInfo to add differents mountType based on the mount parent Class:

inside public static function formatFileInfo(FileInfo $i)

	- get_class($i->getStorage()) ??? I get OCA\\Files_Trashbin\\Storage, why ??

	- Knowing the storage parent class, add:
		- external-root-wnd
		- external-root-dropbox
		- ...
    - Add external folders icons to core/img/filetypes
	- Modify _createRow and getIconUrl to return the icon that match with the new mountType

**Comment by PVince81** [comment]
I realize that it will require deeper changes in the files app, especially regarding the move to Webdav.
We'll need to introduce a new webdav attribute to be able to tell what kind of storage it is.
Maybe every storage can have an alias name like ex: "smb", "swift".

Or other ideas:
- provide an icon URL field in Webdav ?
- or reuse the mime type field ? (might break because currently httpd/unix-directory is required in many places)

**Comment by PVince81** [comment]
I'll take over this and keep it in mind when doing the move to Webdav.

**Comment by jmaciasportela** [comment]
I think that provide a URL field is a good idea and ownCloud clients could use it

**Comment by PVince81** [comment]
I think we can close this as you solved the icon issue in your PR: https://github.com/owncloud/core/pull/20569
