### ISSUE TITLE
Not able to download files via webdav or sync client

### ISSUE THREAD

**Issue by andre-dierker** [owncloud/core#20309]
Hi Team,
since the last ~~update~~ clean install from 8.1.1 to 8.2.0 (stable) I am no longer able to load all the files from OC. Some files work, others do not. Showing via WebDAV, the first KB loaded (about 100 - 250KB), then the download will abort and can be resumed until the next file.

The web server itself displays no errors in the logs, OC raises this here:

```
{"REQID": "FFWTSnbvXT7aWDEpblJy", "RemoteAddr": "178.8.62.24", "app", "PHP", "message": "Can not modify header information - headers already sent by (output started at \ / var \ / www \ / ownCloud \ / 3rdparty \ / Sabre \ / http \ / lib \ /Sapi.php: 70) at\/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#63","level":3,"time":"2015-11-04T17:54:32+00:00","method":"GET","url":"\/cloud\/remote.php\/webdav\/InstantUpload\/20150730_151913.jpg"}
```

The Sync Client makes this error in ownCloud Log back:

```
{"reqId":"xK9dBxjZRzU2cUzBBfAd","remoteAddr":"178.8.62.24","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#63","level":3,"time":"2015-11-04T18:07:00+00:00","method":"GET","url":"\/cloud\/remote.php\/webdav\/InstantUpload\/20150730_151945.jpg"}
{"reqId":"xK9dBxjZRzU2cUzBBfAd","remoteAddr":"178.8.62.24","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#63","level":3,"time":"2015-11-04T18:07:00+00:00","method":"GET","url":"\/cloud\/remote.php\/webdav\/InstantUpload\/20150730_151945.jpg"}
{"reqId":"2CvFuEMiCdEY7n+OmzSG","remoteAddr":"178.8.62.24","app":"webdav","message":"Exception: {\"Message\":\"Encryption library: Decryption (symmetric) of content failed: error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length\",\"Exception\":\"OC\\\\Encryption\\\\Exceptions\\\\DecryptionFailedException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(419): OCA\\\\Encryption\\\\Crypto\\\\Crypt->decrypt(false, false, 'JOev0Xo7Yn1iKRF...', 'AES-256-CFB')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/encryption.php(329): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('2\\\\x99\\\\xB4\\\\x99\\\\x966\\\\x7Feo'Y\\\\xF0\\\\x884A...', 'JOev0Xo7Yn1iKRF...', 'AES-256-CFB')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(442): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt('2\\\\x99\\\\xB4\\\\x99\\\\x966\\\\x7Feo'Y\\\\xF0\\\\x884A...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(281): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#4 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/Wrapper.php(67): fread(Resource id #50, 8192)\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/CallbackWrapper.php(88): Icewind\\\\Streams\\\\Wrapper->stream_read(8192)\\n#7 [internal function]: Icewind\\\\Streams\\\\CallbackWrapper->stream_read(8192)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/http\\\/lib\\\/Sapi.php(70): file_put_contents('php:\\\/\\\/output', Resource id #53)\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\HTTP\\\\Sapi::sendResponse(Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#12 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php\",\"Line\":476}","level":4,"time":"2015-11-04T18:07:00+00:00","method":"GET","url":"\/cloud\/remote.php\/webdav\/InstantUpload\/20150730_152031.jpg"}
```

occ files:scan did not help.
Unfortunately ownCloud is no longer usable for me.

Greetings Andre

**Comment by MorrisJobke** [comment]
@andre-dierker Can you please fill out the issue template, especially the server configuration part: https://github.com/owncloud/core/blob/master/issue_template.md

Thanks

**Comment by andre-dierker** [comment]
Sure,

Steps to reproduce

--

Expected behaviour

No broken files while dowloading 

Actual behaviour


__Server configuration__

Operating system:

`Debian Jessie 
Linux metapixl.com 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u5 (2015-10-09) x86_64 GNU/Linux`

Web server:

`nginx version: nginx/1.9.6`

Database:

`10.0.22-MariaDB-0+deb8u1 (Debian)`

PHP version:

`PHP 5.6.14-0+deb8u1 (cli) (built: Oct  4 2015 16:13:10) 
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies`


ownCloud version: (see ownCloud admin page)

`ownCloud 8.2.0 (stable)`

Updated from an older ownCloud or fresh install:

fresh install with old data after broken update

List of activated apps:

`Enabled:
  - activity: 2.1.3
  - calendar: 0.8.0
  - contacts: 0.5.0.0
  - encryption: 1.1.0
  - files: 1.2.0
  - files_external: 0.3.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - news: 6.0.6
  - tasks: 0.8
  - templateeditor: 0.1
  - updater: 0.6
Disabled:
  - documents
  - external
  - files_locking
  - notifications
  - provisioning_api
  - user_external
  - user_ldap`

  `  "system": {
        "instanceid": "oc0dfc8eac9b",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/home\/owncloud\/data",
        "overwrite.cli.url": "\/cloud",
        "dbtype": "mysql",
        "version": "8.2.0.12",
        "dbname": "oc6",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "asset-pipeline.enabled": true,
        "installed": true,
        "enable_previews": true,
        "theme": "",
        "maintenance": false,
        "forcessl": true,
        "trusted_domains": [
            "6bq.de",
            "www.6bq.de"
        ],
        "mail_smtpmode": "smtp",
        "appcodechecker": false,
        "mail_from_address": "cloudmaster",
        "mail_domain": "6bq.de",
        "filesystem_check_changes": 1,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "app.mail.server-side-cache.enabled": true,
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "appstore.experimental.enabled": true,
        "mail_smtphost": "localhost",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto"
    }`


Are you using external storage, if yes which one: local/smb/sftp/...

no

Are you using encryption: yes/no

yes

Are you using an external user-backend, if yes which one: LDAP/ActiveDirectory/Webdav/...

no

LDAP configuration (delete this part if not used)

Logs

Web server error log

none

`{"REQID": "FFWTSnbvXT7aWDEpblJy", "RemoteAddr": "178.8.62.24", "app", "PHP", "message": "Can not modify header information - headers already sent by (output started at \ / var \ / www \ / ownCloud \ / 3rdparty \ / Sabre \ / http \ / lib \ /Sapi.php: 70) at\/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#63","level":3,"time":"2015-11-04T17:54:32+00:00","method":"GET","url":"\/cloud\/remote.php\/webdav\/InstantUpload\/20150730_151913.jpg"}`

`{"reqId":"xK9dBxjZRzU2cUzBBfAd","remoteAddr":"178.8.62.24","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#63","level":3,"time":"2015-11-04T18:07:00+00:00","method":"GET","url":"\/cloud\/remote.php\/webdav\/InstantUpload\/20150730_151945.jpg"}
{"reqId":"xK9dBxjZRzU2cUzBBfAd","remoteAddr":"178.8.62.24","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#63","level":3,"time":"2015-11-04T18:07:00+00:00","method":"GET","url":"\/cloud\/remote.php\/webdav\/InstantUpload\/20150730_151945.jpg"}
{"reqId":"2CvFuEMiCdEY7n+OmzSG","remoteAddr":"178.8.62.24","app":"webdav","message":"Exception: {\"Message\":\"Encryption library: Decryption (symmetric) of content failed: error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length\",\"Exception\":\"OC\\\\Encryption\\\\Exceptions\\\\DecryptionFailedException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(419): OCA\\\\Encryption\\\\Crypto\\\\Crypt->decrypt(false, false, 'JOev0Xo7Yn1iKRF...', 'AES-256-CFB')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/encryption.php(329): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('2\\\\x99\\\\xB4\\\\x99\\\\x966\\\\x7Feo'Y\\\\xF0\\\\x884A...', 'JOev0Xo7Yn1iKRF...', 'AES-256-CFB')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(442): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt('2\\\\x99\\\\xB4\\\\x99\\\\x966\\\\x7Feo'Y\\\\xF0\\\\x884A...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(281): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#4 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/Wrapper.php(67): fread(Resource id #50, 8192)\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/CallbackWrapper.php(88): Icewind\\\\Streams\\\\Wrapper->stream_read(8192)\\n#7 [internal function]: Icewind\\\\Streams\\\\CallbackWrapper->stream_read(8192)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/http\\\/lib\\\/Sapi.php(70): file_put_contents('php:\\\/\\\/output', Resource id #53)\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\HTTP\\\\Sapi::sendResponse(Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#12 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php\",\"Line\":476}","level":4,"time":"2015-11-04T18:07:00+00:00","method":"GET","url":"\/cloud\/remote.php\/webdav\/InstantUpload\/20150730_152031.jpg"}`


__All file are accessible via web interface__

**Comment by PVince81** [comment]
@schiesbn could be the mismatch file size issue ?

**Comment by PVince81** [comment]
You could try applying this patch https://github.com/owncloud/core/pull/22626 or wait for 8.2.3 (there's a 8.2.3 RC1)

Can you check in `oc_filecache` whether the broken files have the "encrypted" column set to 1 ? If not, you might need to manually set it.

Did you manually restore these files from a backup ?

**Comment by viki53** [comment]
Hi, I have the same error on my server (Debian Jessie)

```
"app":"webdav","message":"Exception: {\"Message\":\"Encryption library: Decryption (symmetric) of content failed: error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length\",\"Exception\":\"OC\\\\Encryption\\\\Exceptions\\\\DecryptionFailedException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(467): OCA\\\\Encryption\\\\Crypto\\\\Crypt->decrypt(false, '', 'mW88f1eA65rgHc2...', 'AES-256-CFB')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/encryption.php(363): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('', 'mW88f1eA65rgHc2...', 'AES-256-CFB', 0, 286)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(459): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt('', 286)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(290): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#4 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(1052)\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/Wrapper.php(83): fread(Resource id #92, 8192)\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/CallbackWrapper.php(91): Icewind\\\\Streams\\\\Wrapper->stream_read(8192)\\n#7 [internal function]: Icewind\\\\Streams\\\\CallbackWrapper->stream_read(8192)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/http\\\/lib\\\/Sapi.php(78): stream_copy_to_stream(Resource id #96, Resource id #100, '2350040')\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(470): Sabre\\\\HTTP\\\\Sapi::sendResponse(Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#12 \\\/var\\\/www\\\/owncloud\\\/remote.php(138): require_once('\\\/var\\\/www\\\/ownclo...')\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php\",\"Line\":587,\"User\":\"viki53\"}"
```

I looked in the `filecache` table and the `encrypted` column is at `0`:

```
name : IMG_20150602_144220.jpg
mimetype : 4
mimepart : 3
size : 2350040
mtime : 1433249309
storage_mtime : 1433249309
encrypted : 0
unencrypted_size : 0
etag : fdce3c66e5242da3bdef87ffd726bd66
permissions : 27
checksum : NULL
```

The file is a photo that was uploaded into `InstantUpload` via the Android app

**Comment by Happyfeet01** [comment]
i have also the same Error. I can´t sync complete the files with Server and Desktop. 

`Exception: {"Message":"Encryption library: Decryption (symmetric) of content failed: error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length`

![sync abbruch](https://cloud.githubusercontent.com/assets/3295104/15883944/13e62db2-2d4d-11e6-8769-39abeb37c485.png)

i discussed this issue at the Forum https://forum.owncloud.org/viewtopic.php?f=21&t=37156
Server-Konfiguration
**Betriebssystem:** 
ubuntu 14.04 LTS
**Webserver-Typ:** Apache2 2.4.7
**Datenbank-Typ:** MySQL Ver 14.14 Distrib 5.5.49
**PHP-Version:** php 7.0.7
**ownCloud-Version:** owncloud 9.0.2

ownCloud log (data/owncloud.log): 

`Uncaught Error: Access to undeclared static property: OC\Files\Filesystem::$normalizedPathCache in /var/www/vhosts/cloud-surfer.eu/httpdocs/owncloud/lib/private/files/filesystem.php:807 Stack trace: #0 /var/www/vhosts/cloud-surfer.eu/httpdocs/owncloud/lib/private/files/view.php(1977): OC\Files\Filesystem::normalizePath('/Lars/files/Dok...') #1 /var/www/vhosts/cloud-surfer.eu/httpdocs/owncloud/lib/private/files/view.php(1095): OC\Files\View->unlockFile('/Dokumente/Verk...', 1) #2 [internal function]: OC\Files\View->OC\Files\{closure}() #3 /var/www/vhosts/cloud-surfer.eu/httpdocs/owncloud/apps/files_external/3rdparty/icewind/streams/src/CallbackWrapper.php(109): call_user_func(Object(Closure)) #4 [internal function]: Icewind\Streams\CallbackWrapper->stream_close() #5 {main} thrown at /var/www/vhosts/cloud-surfer.eu/httpdocs/owncloud/lib/private/files/filesystem.php#807   2016-06-05T09:26:50+02:00
Fatal   webdav   Exception: {"Message":"Encryption library: Decryption (symmetric) of content failed: error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length","Exception":"OC\\Encryption\\Exceptions\\DecryptionFailedException","Code":0,"Trace":"#0 \/var\/www\/vhosts\/cloud-surfer.eu\/httpdocs\/owncloud\/apps\/encryption\/lib\/crypto\/crypt.php(467): OCA\\Encryption\\Crypto\\Crypt->decrypt(false, '', '3u+K96WGq\/bUD0V...', 'AES-256-CFB')\n#1 \/var\/www\/vhosts\/cloud-surfer.eu\/httpdocs\/owncloud\/apps\/encryption\/lib\/crypto\/encryption.php(363): OCA\\Encryption\\Crypto\\Crypt->symmetricDecryptFileContent('', '3u+K96WGq\/bUD0V...', 'AES-256-CFB', 0, 230)\n#2 \/var\/www\/vhosts\/cloud-surfer.eu\/httpdocs\/owncloud\/lib\/private\/files\/stream\/encryption.php(459): OCA\\Encryption\\Crypto\\Encryption->decrypt('', 230)\n#3 \/var\/www\/vhosts\/cloud-surfer.eu\/httpdocs\/owncloud\/lib\/private\/files\/stream\/encryption.php(290): OC\\Files\\Stream\\Encryption->readCache()\n#4 [internal function]: OC\\Files\\Stream\\Encryption->stream_read(409)\n#5 \/var\/www\/vhosts\/cloud-surfer.eu\/httpdocs\/owncloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php(83): fread(Resource id #544, 8192)\n#6 \/var\/www\/vhosts\/cloud-surfer.eu\/httpdocs\/owncloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/CallbackWrapper.php(91): Icewind\\Streams\\Wrapper->stream_read(8192)\n#7 [internal function]: Icewind\\Streams\\CallbackWrapper->stream_read(8192)\n#8 \/var\/www\/vhosts\/cloud-surfer.eu\/httpdocs\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php(78): stream_copy_to_stream(Resource id #548, Resource id #558, '483887')\n#9 \/var\/www\/vhosts\/cloud-surfer.eu\/httpdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(470): Sabre\\HTTP\\Sapi::sendResponse(Object(Sabre\\HTTP\\Response))\n#10 \/var\/www\/vhosts\/cloud-surfer.eu\/httpdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#11 \/var\/www\/vhosts\/cloud-surfer.eu\/httpdocs\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(55): Sabre\\DAV\\Server->exec()\n#12 \/var\/www\/vhosts\/cloud-surfer.eu\/httpdocs\/owncloud\/remote.php(138): require_once('\/var\/www\/vhosts...')\n#13 {main}","File":"\/var\/www\/vhosts\/cloud-surfer.eu\/httpdocs\/owncloud\/apps\/encryption\/lib\/crypto\/crypt.php","Line":587,"User":"Lars"}`

php log:

`(32)Broken pipe: mod_fcgid: ap_pass_brigade failed in handle_request_ipc function`

**Comment by nemobis** [comment]
I see the same error in 9.1.1, server details unknown.
```
Exception: {"Message":"Encryption library: Decryption (symmetric) of content failed: error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length","Exception":"OC\\Encryption\\Exceptions\\DecryptionFailedException","Code":0,"Trace":"#0 \/home\/wikimedi\/public_html\/apps\/encryption\/lib\/Crypto\/Crypt.php(469): OCA\\Encryption\\Crypto\\Crypt->decrypt(false, false, '\\xDB\\xD3|...', 'AES-128-CFB')\n#1 \/home\/wikimedi\/public_html\/apps\/encryption\/lib\/Crypto\/Encryption.php(363): OCA\\Encryption\\Crypto\\Crypt->symmetricDecryptFileContent('PK\\x03\\x04\\x14\\x00\\x00\\x08\\x00\\x00 rkI\\x85...', '\\xDB\\xD3|\\xC3\\xC9rBD\\x94\\xD5L\\xF0\\x9AD)...', 'AES-128-CFB', 351, 0)\n#2 \/home\/wikimedi\/public_html\/lib\/private\/Files\/Stream\/Encryption.php(459): OCA\\Encryption\\Crypto\\Encryption->decrypt('PK\\x03\\x04\\x14\\x00\\x00\\x08\\x00\\x00 rkI\\x85...', 0)\n#3 \/home\/wikimedi\/public_html\/lib\/private\/Files\/Stream\/Encryption.php(290): OC\\Files\\Stream\\Encryption->readCache()\n#4 [internal function]: OC\\Files\\Stream\\Encryption->stream_read(8192)\n#5 \/home\/wikimedi\/public_html\/3rdparty\/icewind\/streams\/src\/Wrapper.php(83): fread(Resource id #621, 8192)\n#6 \/home\/wikimedi\/public_html\/3rdparty\/icewind\/streams\/src\/CallbackWrapper.php(91): Icewind\\Streams\\Wrapper->stream_read(8192)\n#7 [internal function]: Icewind\\Streams\\CallbackWrapper->stream_read(8192)\n#8 \/home\/wikimedi\/public_html\/3rdparty\/sabre\/http\/lib\/Sapi.php(78): stream_copy_to_stream(Resource id #625, Resource id #635, '144096')\n#9 \/home\/wikimedi\/public_html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(470): Sabre\\HTTP\\Sapi::sendResponse(Object(Sabre\\HTTP\\Response))\n#10 \/home\/wikimedi\/public_html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#11 \/home\/wikimedi\/public_html\/apps\/dav\/appinfo\/v1\/webdav.php(56): Sabre\\DAV\\Server->exec()\n#12 \/home\/wikimedi\/public_html\/remote.php(164): require_once('\/home\/wikimedi\/...')\n#13 {main}","File":"\/home\/wikimedi\/public_html\/apps\/encryption\/lib\/Crypto\/Crypt.php","Line":587,"User":"Nemo"}	
```

**Comment by PVince81** [comment]
> I have seen in an other issue that this might be related to files with similar names, and I do have a file named IMG_20150602_144220_edited.jpg in the same directory.

If that's the case then the keys for these files were already messed up in older OC versions where that old bug existed.

In general such issue is happening when keys are messed up. So if you're not able to restore the keys of this file from a backup, you won't be able to recover the data.

Now if this is happening for newly updated files, then it's definitely a bug. But old files: likely broken through old bugs, sorry :-/

**Comment by hodyroff** [comment]
Sounds like messed up keys. Closing.
