### ISSUE TITLE
Allow public routes for group specific enabled apps

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#20304]
Currently if you try to access a public route of an app only enabled for specific users, you get an authentication failure and redirected to the logic screen.

This is because the security middleware uses OC_App::isEnabled() which fails because that method calls OC\App\AppManager->isEnabledForUser with null user value, which fails.
- https://github.com/owncloud/core/blob/master/lib/private/appframework/middleware/security/securitymiddleware.php#L132
- https://github.com/owncloud/core/blob/master/lib/private/app.php#L276
- https://github.com/owncloud/core/blob/master/lib/private/app/appmanager.php#L118
- https://github.com/owncloud/core/blob/master/lib/private/app/appmanager.php#L141

So what we need to do here is adjust the logic here: https://github.com/owncloud/core/blob/master/lib/private/appframework/middleware/security/securitymiddleware.php#L132 such that if the route has the  'PublicPage' annotation, check if the appconfig values for 'enabled' != 'no' (meaning its either yes, or the json group string) rather than calling isEnabledForUser.

Is this a correct understanding and suitable fix? My head hurts. Then can we add tests for this?

@LukasReschke @nickvergessen @PVince81 @schiesbn

**Comment by MorrisJobke** [comment]
cc @bboule @butonic for the purple ticket ;)

**Comment by DeepDiver1975** [comment]
> So what we need to do here is adjust the logic here: https://github.com/owncloud/core/blob/master/lib/private/appframework/middleware/security/securitymiddleware.php#L132 such that if the route has the 'PublicPage' annotation, check if the appconfig values for 'enabled' != 'no' (meaning its either yes, or the json group string) rather than calling isEnabledForUser.

@tomneedham your proposal sounds reasonable - PR? :wink:

**Comment by tomneedham** [comment]
Sure :) I am correct that everything with @PublicPage doesn't need auth right?

**Comment by DeepDiver1975** [comment]
> everything with @PublicPage doesn't need auth right?

yes

**Comment by PVince81** [comment]
There's a PR from @tomneedham https://github.com/owncloud/core/issues/20310

**Comment by PVince81** [comment]
@nickvergessen can you help @tomneedham moving this forward ?

**Comment by nickvergessen** [comment]
I still think that this brings us into the devils kitchen. Because the app has not been loaded so far, it should not be available. So we would need to check if the app was already loaded and then load it, etc.
But then again other app authors wouldn't know that an app that is restircted to a group is suddenly public available?

**Comment by PVince81** [comment]
Moving to 9.2 like the PR.

**Comment by felixboehm** [comment]
@tomneedham solved in 10 ?
