### ISSUE TITLE
Owncloud 8.2 missing dependences

### ISSUE THREAD

**Issue by marcorighi** [owncloud/core#20314]
Hi,
Owncloud dependences permit the owncloud installation without

Codice: Seleziona tutto
    libapache2-mod-php5

library! Please update owncloud server dependencies!

For a complete description
https://forum.owncloud.org/viewtopic.php?f=20&t=31327

**Comment by karlitschek** [comment]
please post a full bug report using the issue template
https://github.com/owncloud/core/blob/master/CONTRIBUTING.md
by the way: ownCloud 8.3 doesn't exist

**Comment by marcorighi** [comment]
Done

**Comment by karlitschek** [comment]
sorry. please post a full bug report using the issue template https://raw.githubusercontent.com/owncloud/core/master/issue_template.md
Otherwise we can't help you

**Comment by DeepDiver1975** [comment]
@marcorighi according to your post on the forum libapache2-mod-php5 was installed. I honestly think your server was not yet properly configured by the time the error occurred.

Maybe the web server was not restarted after the packages have been installed?

Nevertheless: not an issue -> close?

**Comment by marcorighi** [comment]
Hi,
synaptic marked the package libapache2-mod-php5 as not installed and
php5 as installed. Perhaps is this a synaptic bug?

On 04/11/2015 23:26, Thomas Müller wrote:
> @marcorighi according to your post on the forum libapache2-mod-php5 was installed. I honestly think your server was not yet properly configured by the time the error occurred.
> 
> Maybe the web server was not restarted after the packages have been installed?
> 
> Nevertheless: not an issue -> close?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/owncloud/core/issues/20314#issuecomment-153889083
> 



-- 
Think Marco, think different
web site:http://www.di.unipi.it/~righi/

**Comment by PVince81** [comment]
Did you use the official package from OBS or did you use the package from your distro's repository ?
Usually it is best to only use the ones from https://download.owncloud.org/download/repositories/stable/owncloud/

**Comment by marcorighi** [comment]
Il 09/11/2015 13:43, Vincent Petry ha scritto:
> Did you use the official package from OBS or did you use the package
> from your distro's repository ?
> Usually it is best to only use the ones from
> https://download.owncloud.org/download/repositories/stable/owncloud/
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/core/issues/20314#issuecomment-155053209>.
> 

the repositories are:

deb
http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_14.04/
/

deb
http://download.owncloud.org/download/repositories/stable/xUbuntu_14.04/ /


-- 
Think Marco, think different
web site:http://www.di.unipi.it/~righi/
