### ISSUE TITLE
Activity page, time zone inconsistent (stuck in Berlin)

### ISSUE THREAD

**Issue by peterkahl** [owncloud/core#20317]
in my OC 8.1.3 config.php I've defined time zone as Asia/Hong_Kong. This appears to produce correct time strings throughout OC, but not on the page "Activity" (where it seems to be stick in the Europe/Berlin time zone).

**Comment by MorrisJobke** [comment]
cc @nickvergessen

**Comment by nickvergessen** [comment]
Activity takes the user timezone not the global one.
So you'd need to change the oc_preference value for your user.

That value is updated every time you log in. So try logging in and out again.

**Comment by MorrisJobke** [comment]
Ah. I misread it. @peterkahl You can also change this setting in your personal settings page. (top right menu).


If this issue then still exists feel free to reopen it.

**Comment by peterkahl** [comment]
Persona? Top right menu?

Don't see any settings for time zone, OC 8.1.3.

**Comment by nickvergessen** [comment]
> You can also change this setting in your personal settings page. (top right menu).

No, that's not there. The timezone is taken directly from the browser.

**Comment by peterkahl** [comment]
I am using Safari, so I'm not doing any tricks with JS. Still, the time zone is wrong.

**Comment by MorrisJobke** [comment]
> No, that's not there. The timezone is taken directly from the browser.

ah...sorry mixed this up with the language.

**Comment by MorrisJobke** [comment]
> I am using Safari, so I'm not doing any tricks with JS. Still, the time zone is wrong.

"Still" means: after logout and relogin?

**Comment by peterkahl** [comment]
Logout, login...

My OC doesn't have much activity, so I don't see any difference now. But will keep my eyes open and try logout/login again.

**Comment by nickvergessen** [comment]
Well the timezone is retro active and should work at any time.
The question is, whether your browser/OS sends the timezone or whether it sends the berlini timezone

**Comment by peterkahl** [comment]
This morning, that's about 8am in Asia/Hong_Kong, I looked at the activity page and saw that it said "Today created....", which was wrong. I created yesterday, not today. So I thought there was a time zone default to Berlin.

As there wasn't any activity now, I am unable to verify proper operation of the activity page.

--
"The higher we soar the smaller we appear to those who cannot fly." ~ F. Nietzsche 弗里德里希·尼采

https://www.colossalmind.com/subscribe/

**Comment by peterkahl** [comment]
Okay. From my side, I confirm this BUG.
It's 7:22 AM in my time zone.
Activity page says that "Today" I created XYZ. Not true. I did that yesterday.
As you requested, I have logged out, then logged in. Still the same problem.

**Comment by nickvergessen** [comment]
When you hover "today" whats the date? And also whats the date/time on the right side of the activity?

**Comment by peterkahl** [comment]
November 5, 2015. But in my time zone it's November 6.

Hovering on right side (20 hours ago) says "November 5, 10:50am", which seems correct.

**Comment by nickvergessen** [comment]
Does the `oc_preferences` database table have the correct timezone for you?

**Comment by peterkahl** [comment]
That's me (as user):
calendar...timezone....Asia/Hong_Kong
core.........timezone....Asia/Shanghai

Those 2 zones are same.

**Comment by nickvergessen** [comment]
@peterkahl does the issue still exist?

**Comment by peterkahl** [comment]
Let me check.

**Comment by peterkahl** [comment]
Okay. I shared a link with myself. Opened the link. Looking at the activity page and it says "5 minutes ago". That implies that it works as intended.
