### ISSUE TITLE
OC 8.1.4 contacts configuration under OS X EL Capitan 

### ISSUE THREAD

**Issue by mariobig** [owncloud/core#20316]
I can't configure contacts at OS X EL Capitan to be synchronized with Owncloud 8.1.4.

instruction described at:
https://doc.owncloud.org/server/7.0/user_manual/pim/sync_osx.html
does not work. There is no Configuration.plist file at the indicated folder to be be edited.

Apache log shows following:
83.28.187.229 - - [04/Nov/2015:22:20:16 +0100] "PROPFIND /.well-known/carddav HTTP/1.1" 405 486 "-" "Mac OS X/10.11.1 (15B42) AddressBook/1679"
83.28.187.229 - - [04/Nov/2015:22:20:16 +0100] "PROPFIND / HTTP/1.1" 200 2432 "-" "Mac OS X/10.11.1 (15B42) AddressBook/1679"
83.28.187.229 - - [04/Nov/2015:22:20:16 +0100] "PROPFIND /principals/ HTTP/1.1" 405 478 "-" "Mac OS X/10.11.1 (15B42) AddressBook/1679"

Message from OS X: Error CoreDAVHTTPStatusErrorDomain405

I will appreciate your help.

kr
Mario
info@wawasoft.com

**Comment by MorrisJobke** [comment]
Please reopen this in the contacts repo: https://github.com/owncloud/contacts/issues

**Comment by RealRancor** [comment]
There is a longer issue about this here: https://github.com/owncloud/contacts/issues/1058

Also note: https://github.com/owncloud/core/issues/20012

**Comment by Tuxkowo** [comment]
Repo have been moved, issue mentioned earlier is now there: https://github.com/owncloudarchive/contacts/issues/1058
