### ISSUE TITLE
8.0.9 file sharing not possible

### ISSUE THREAD

**Issue by melo1** [owncloud/core#20311]
Hello,

after upgrading from 8.0.8 to 8.0.9 it's not possible anymore to share files because the share button is missing.
Sharing is enabled and works with calendars.
The behaviour can be tested with IE10, IE11, Firefox, Chrome and Safari.
That's why I think, it must be a 8.0.9 problem.

Manuel

**Comment by karlitschek** [comment]
can you post a full bug report using the issue template please? https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by melo1** [comment]
### Steps to reproduce
1. Install Owncloud 8.0.9
2. Activate sharing
3. Try to share a file or folder

### Expected behaviour
A sharing button should appear

### Actual behaviour
No sharing button available

### Server configuration
**Operating system**:
SMP Debian 3.16.7 Jessie

**Web server:**
nginx 1.8.0

**Database:**
MariaDB 5.5.44

**PHP version:**
5.6.14

**ownCloud version:** (see ownCloud admin page)
8.0.9

**Updated from an older ownCloud or fresh install:**
updated from 8.0.8

**List of activated apps:**
calendar
contacts
ownnote
versions
file locking
deleted files

**The content of config/config.php:**
<?php
$CONFIG = array (
  'overwritewebroot' => '/owncloud',
  'overwrite.cli.url' => 'https://blah/owncloud',
  'skeletondirectory' => '',
  'appstoreenabled' => true,
  'appstoreurl' => 'https://api.owncloud.com/v1',
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/volume2/web/owncloud/apps',
      'url' => '/apps',
      'writable' => true,
    ),
  ),
  'appcodechecker' => false,
  'dbtype' => 'mysql',
  'dbname' => 'owncloud',
  'dbuser' => ,
  'dbpassword' => ,
  'dbhost' => ,
  'dbtableprefix' => 'oc_',
  'version' => '8.0.9.2',
  'installed' => true,
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'loglevel' => '3',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'blah',
  'mail_smtpport' => '465',
  'trusted_domains' =>
  array (
    0 => 'blah',
  ),
  'mail_from_address' => 'owncloud',
  'mail_domain' => 'blah',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'blah',
  'mail_smtppassword' => ,
  'secret' => ,
  'forceSSLforSubdomains' => true,
  'hashingCost' => 10,
  'defaultapp' => 'files',
  'knowledgebaseenabled' => false,
  'enable_avatars' => true,
  'allow_user_to_change_display_name' => true,
  'remember_login_cookie_lifetime' => 1296000,
  'session_lifetime' => 86400,
  'session_keepalive' => true,
  'trashbin_retention_obligation' => '30, auto',
  'updatechecker' => true,
  'has_internet_connection' => true,
  'check_for_working_webdav' => true,
  'check_for_working_htaccess' => false,
  'config_is_read_only' => false,
  'log_type' => 'owncloud',
  'logfile' => '/volume2/web/owncloud/data/owncloud.log',
  'logdateformat' => 'F d, Y H:i:s',
  'log_query' => false,
  'cron_log' => false,
  'log_rotate_size' => false,
  'enable_previews' => true,
  'preview_max_x' => NULL,
  'preview_max_y' => NULL,
  'preview_max_scale_factor' => 10,
  'preview_max_filesize_image' => 50,
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\Image',
    1 => 'OC\\Preview\\MP3',
    2 => 'OC\\Preview\\TXT',
    3 => 'OC\\Preview\\MarkDown',
  ),
  'xframe_restriction' => true,
  'cipher' => 'AES-256-CFB',
  'filesystem_check_changes' => 1,
  'asset-pipeline.enabled' => false,
  'assetdirectory' => '/volume2/web/owncloud',
  'mount_file' => 'data/mount.json',
  'filesystem_cache_readonly' => false,
  'custom_csp_policy' => 'default-src \'self\'; script-src \'self\' \'unsafe-eval\'; style-src \'self\' \'unsafe-inline\'; frame-src *; img-

src *; font-src \'self\' data:; media-src *; connect-src *',
  'forwarded_for_headers' =>
  array (
    0 => 'HTTP_X_FORWARDED',
    1 => 'HTTP_FORWARDED_FOR',
  ),
  'max_filesize_animated_gifs_public_sharing' => 10,
  'appstore.experimental.enabled' => false,
);


**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
IE10
IE11
Firefox
Chrome
Safari

**Operating system:**
MS Windows7
Android
iOS

### Logs
#### Web server error log
no error log

#### ownCloud log (data/owncloud.log)
no log entries

#### Browser log

**Comment by melo1** [comment]
sorry - I don't know why, but the share files app was disabled
