### ISSUE TITLE
Can not move images from folder

### ISSUE THREAD

**Issue by MacsKavana** [owncloud/core#20322]
Photos uploaded by android app into UPLOAD folder.
All photos manually moved succesfully to ARCHIVE folder except a couple.
These photos can be seen in the UPLOAD folder (even with their thumbnails) but they can not be viewed or moved.

Clicking on these photos pops up a spinner and this message: 

"Error! Could not generate a preview of this file.
Please go to the next slide while we remove this image from the slideshow."

Moving these images to ARCHIVE results this message:

"Could not move FILENAME - File with this name already exists".

Looking for the files on the filesystem:

/OWNCLOUD-DATA-DIR/myusername/files_encryption/keys/files/UPLOAD/ARCHIVE/IMG_20151021_190903.jpg/OC_DEFAULT_MODULE/recoveryKey_23c427e3.shareKey
/OWNCLOUD-DATA-DIR/myusername/files_encryption/keys/files/UPLOAD/ARCHIVE/IMG_20151021_190903.jpg/OC_DEFAULT_MODULE/myusername.shareKey
/OWNCLOUD-DATA-DIR/myusername/files_encryption/keys/files/UPLOAD/ARCHIVE/IMG_20151021_190903.jpg/OC_DEFAULT_MODULE/fileKey
/OWNCLOUD-DATA-DIR/myusername/files/UPLOAD/ARCHIVE/IMG_20151021_190903.jpg

The file names don't contain any accents or spec characters.

Environment: 
debian 8 64bit + phpfpm + mysql + nginx + owncloud 8.2

---
Thank you!

**Comment by nickvergessen** [comment]
@schiesbn

**Comment by MacsKavana** [comment]
sudo -u www-data php occ files:scan --all 

seems to have solved the problem.
