### ISSUE TITLE
Update unsuccessful

### ISSUE THREAD

**Issue by WietseSas** [owncloud/core#20335]
I get the following message when clicking on Start Update. Meanwhile I cannot access my cloud files or even login (it always shows the screen to "Start update", I do not even have to login...)

Updating ownCloud to version 8.2.0, this may take a while.

Preparing update
Set log level to debug - current level: "Warning"
Turned on maintenance mode
Exception: Updates between multiple major versions and downgrades are unsupported.
The update was unsuccessful. Please report this issue to the ownCloud community.
<img width="302" alt="capture1" src="https://cloud.githubusercontent.com/assets/2316224/10971524/07cc826e-83d5-11e5-947b-33f405636ca6.PNG">
<img width="426" alt="capture2" src="https://cloud.githubusercontent.com/assets/2316224/10971525/08b777ba-83d5-11e5-9c46-fc8f42dae925.PNG">

**Comment by karlitschek** [comment]
well it is exactly as stated in the message. you should update from owncloud 8.0 to 8.1 to 8.2 No jumping directly to new versions.
