### ISSUE TITLE
The update was unsuccessful. Please report

### ISSUE THREAD

**Issue by Newsearay** [owncloud/core#20330]
Problems with updating to 8.1.3. What can i do?

**Comment by schiesbn** [comment]
First step: use the issue template... We need more information in order to help you https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by Newsearay** [comment]
I startetd Onecloud to upload 179mb file  and it doesn't work. Before i tried again i saw the mark to update to version 8.1.3 and i started it( Aktualisiere auf owncloud....) and after a few seconds : Exception: Please upload the ca-bundle.crt file into the 'config' directory.
The update was unsuccessful. Please report this issue to the ownCloud community.
were ist this file for direct download?, if i copy the https://raw.githubusercontent.com/owncloud/core/master/resources/config/ca-bundle.crt  it to notepad++, can't create a crt file.

**Comment by RealRancor** [comment]
@Newsearay Download https://raw.githubusercontent.com/owncloud/core/v8.1.4/config/ca-bundle.crt (without using notepad++ or stuff like that) and place it into your config/ folder (not resources/config).

**Comment by Newsearay** [comment]
AHHHH it works, thx a lot

Thomas Busch
--------------------------------------------------------------------------
Schmid Ingenieure GmbH
Bau- und Verkehrswesen
Reichsstraße 12
D - 14052 Berlin

Tel.:      +49 (0)30 / 300 604 - 22
Fax:      +49 (0)30 / 300 604 - 19
Mobil:   +49 0163 / 866 97 70
email:   tb@schmidingenieure.de<mailto:tk@schmidingenieure.de>
http://www.schmidingenieure.de/

--------------------------------------------------------------------------
Sitz: Berlin
Handelsregister: Amtsgericht Charlottenburg / HRB 136206 B
Geschäftsführer: Michael Grätz, Ulf Radloff, Benjamin Schmid
--------------------------------------------------------------------------

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail sind nicht gestattet.

This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.



Von: RealRancor [mailto:notifications@github.com]
Gesendet: Donnerstag, 5. November 2015 13:41
An: owncloud/core <core@noreply.github.com>
Cc: Busch, Thomas <TB@schmidingenieure.de>
Betreff: Re: [core] The update was unsuccessful. Please report (#20330)


@Newsearay<https://github.com/Newsearay> Download https://raw.githubusercontent.com/owncloud/core/v8.1.4/config/ca-bundle.crt (without using notepad++ or stuff like that) and place it into your config/ folder (not resources/config).
