### ISSUE TITLE
Enhancement proposal : number of files quota

### ISSUE THREAD

**Issue by centredecalcul** [owncloud/core#20334]
Size quota is a very good feature, but t would be nice to be able to limit the maximum number of files by user.

Store thousand of 10 Mo files is not a problem, but store millions of 4 Ko files is a big problem for performance, database, backup, etc.

**Comment by PVince81** [comment]
I understand the admin's point of view that you described, it makes sense.

However from the user's perspective, I'm not sure that users would be happy about or understand an error message saying "you have too many files". In general users are used to storage/byte based limits, not file count. But I could be mistaken :smile:

**Comment by centredecalcul** [comment]
If we develop this feature, would you be interested in including/merge it ?
We can make a contribution, but we do not want to create a separate application. Improving the existing quota feature would make it easier to manage the associated notifications.

**Comment by PVince81** [comment]
I'd personally prefer to have it as a separate app, but I'm not sure it's possible with the current APIs.

@pmaier1 @DeepDiver1975 see feature request and contribution proposal.
What do you think ?

**Comment by pmaier1** [comment]
I agree with @PVince81 that this could be confusing for users but more features are always nice at least when they're opt-in. Developing this as a separate app would also be my preferred solution. However, integrating this with the existing quota feature is fine as well as it is just a slight change and you're not forced to use it.

**Comment by centredecalcul** [comment]
Yes, you are not forced to used it. Or you can set a very high limit (dropbox limit is 300000) as a safeguard.
If the file quota must be in a separate app, maybe the size quota must also be in that app ?

**Comment by PVince81** [comment]
@centredecalcul didn't you guys develop an app for that ?

**Comment by karakayasemi** [comment]
@PVince81 I have an app to use filesystem quota on ownCloud which is working with file hooks and I am planning to implement it with storage wrapper instead of hooks. If I succeed there, I can create a new app for this feature also.

**Comment by centredecalcul** [comment]
Yes a colleague started a development but he did not have time to finish before the end of his contract. The app is not in production, all the features have not been completed.
You can find code here : https://github.com/centredecalcul/files_quota

**Comment by PVince81** [comment]
once ready for production you could publish it on http://marketplace.owncloud.com/

**Comment by PVince81** [comment]
Something to be done in a separate app, not part of core.
