### ISSUE TITLE
Cron.php doesn't delete files in trashbin

### ISSUE THREAD

**Issue by fossxplorer** [owncloud/core#20349]
Also, i can see some of the user's files versions mtime are changed by the cron for some reasons.

### Steps to reproduce
Run cron.php on a bigger installation with some hundred thousands of entries in oc_jobs. In this case there are ~ 640000 entries there.
oC8.1.1 

### Expected behaviour
cron.php runs the jobs in oc_jobs and exits. 

### Actual behaviour
Cron.php running for > 24h without removing any files in trashbin nor expiring file versions.

### Server configuration
**Operating system**:
CentOS 6.7

**Web server:**
Nginx reverse proxy and Nginx web server/backend

**Database:**
MariaDB 10

**PHP version:**
5.5.27

**ownCloud version:** (see ownCloud admin page)
 8.1.1

**Updated from an older ownCloud or fresh install:**

**List of activated apps:**
Enabled:
 - activity: 2.0.1
 - bookmarks: 0.4
 - calendar: 0.7.2
 - contacts: 0.4.0.0
 - documents: 0.10.1
 - files: 1.1.10
 - files_external: 0.2.3
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - galleryplus: 14.0.0
 - mozilla_sync: 1.4
 - music: 0.3.7
 - news: 5.3.9
 - notes: 1.1.0
 - tasks: 0.7.1

**The content of config/config.php:**

**Are you using external storage, if yes which one:** local/smb/sftp/...
Google Drive
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
Not relevant here.

Can of course provide more details if needed.

@VicDeo

**Comment by nickvergessen** [comment]
Please update to 8.1.4 at least,
Other then that in 8.2 trashbin stuff was changed a bit, maybe it was fixed there?

**Comment by fossxplorer** [comment]
The following will show the mtime changing done by the cron.php, notice the file named state.conf.v1443266204 for which the mtime has been changed at least 3 times:
 
[ocuser1@srv02 root]$ ll -t     /var/data/user11/files_versions/Project1/.zim//
-rw-r--r--. 1 ocuser1 ocuser1  3309 Nov  5 16:57 state.conf.v1443266204
-rw-r--r--. 1 ocuser1 ocuser1  3407 Sep 26 14:08 state.conf.v1442508347
-rw-r--r--. 1 ocuser1 ocuser1  3452 Sep 17 17:08 state.conf.v1441414706
-rw-r--r--. 1 ocuser1 ocuser1 24576 Sep  4 21:56 index.db.v1441285570
-rw-r--r--. 1 ocuser1 ocuser1  3500 Sep  3 22:09 state.conf.v1440293413
-rw-r--r--. 1 ocuser1 ocuser1 24576 Sep  3 15:29 index.db.v1440289671
-rw-r--r--. 1 ocuser1 ocuser1  3597 Aug 16 22:09 state.conf.v1438715488
-rw-r--r--. 1 ocuser1 ocuser1 24576 Aug 16 22:09 index.db.v1438713273
-rw-r--r--. 1 ocuser1 ocuser1  3714 Jul 29 00:56 state.conf.v1437744057
-rw-r--r--. 1 ocuser1 ocuser1 24576 Jul 29 00:56 index.db.v1437743889
-rw-r--r--. 1 ocuser1 ocuser1  3787 Jul 18 21:34 state.conf.v1436749707
-rw-r--r--. 1 ocuser1 ocuser1 24576 Jul 18 21:34 index.db.v1436749697
-rw-r--r--. 1 ocuser1 ocuser1  3641 Jul 13 02:34 state.conf.v1436110809
-rw-r--r--. 1 ocuser1 ocuser1 24576 Jul 13 02:34 index.db.v1436106928

[ocuser1@srv02 root]$ ll -t     /var/data/user11/files_versions/Project1/.zim//
total 176
-rw-r--r--. 1 ocuser1 ocuser1  3309 Nov  5 16:59 state.conf.v1443266204
-rw-r--r--. 1 ocuser1 ocuser1  3407 Sep 26 14:08 state.conf.v1442508347
-rw-r--r--. 1 ocuser1 ocuser1  3452 Sep 17 17:08 state.conf.v1441414706
-rw-r--r--. 1 ocuser1 ocuser1 24576 Sep  4 21:56 index.db.v1441285570
-rw-r--r--. 1 ocuser1 ocuser1  3500 Sep  3 22:09 state.conf.v1440293413
-rw-r--r--. 1 ocuser1 ocuser1 24576 Sep  3 15:29 index.db.v1440289671
-rw-r--r--. 1 ocuser1 ocuser1  3597 Aug 16 22:09 state.conf.v1438715488
-rw-r--r--. 1 ocuser1 ocuser1 24576 Aug 16 22:09 index.db.v1438713273
-rw-r--r--. 1 ocuser1 ocuser1  3714 Jul 29 00:56 state.conf.v1437744057
-rw-r--r--. 1 ocuser1 ocuser1 24576 Jul 29 00:56 index.db.v1437743889
-rw-r--r--. 1 ocuser1 ocuser1  3787 Jul 18 21:34 state.conf.v1436749707
-rw-r--r--. 1 ocuser1 ocuser1 24576 Jul 18 21:34 index.db.v1436749697
-rw-r--r--. 1 ocuser1 ocuser1  3641 Jul 13 02:34 state.conf.v1436110809
-rw-r--r--. 1 ocuser1 ocuser1 24576 Jul 13 02:34 index.db.v1436106928
[ocuser1@srv02 root]$ ll -t     /var/data/user11/files_versions/Project1/.zim//
total 208
-rw-r--r--. 1 ocuser1 ocuser1  3362 Nov  6 02:16 state.conf.v1446761059
-rw-r--r--. 1 ocuser1 ocuser1  3364 Nov  5 23:54 state.conf.v1446748864
-rw-r--r--. 1 ocuser1 ocuser1  3309 Nov  5 21:39 state.conf.v1443266204
-rw-r--r--. 1 ocuser1 ocuser1 24576 Nov  5 21:39 index.db.v1441393276
-rw-r--r--. 1 ocuser1 ocuser1  3407 Sep 26 14:08 state.conf.v1442508347
-rw-r--r--. 1 ocuser1 ocuser1  3452 Sep 17 17:08 state.conf.v1441414706
-rw-r--r--. 1 ocuser1 ocuser1 24576 Sep  4 21:56 index.db.v1441285570
-rw-r--r--. 1 ocuser1 ocuser1  3500 Sep  3 22:09 state.conf.v1440293413
-rw-r--r--. 1 ocuser1 ocuser1 24576 Sep  3 15:29 index.db.v1440289671
-rw-r--r--. 1 ocuser1 ocuser1  3597 Aug 16 22:09 state.conf.v1438715488
-rw-r--r--. 1 ocuser1 ocuser1 24576 Aug 16 22:09 index.db.v1438713273
-rw-r--r--. 1 ocuser1 ocuser1  3714 Jul 29 00:56 state.conf.v1437744057
-rw-r--r--. 1 ocuser1 ocuser1 24576 Jul 29 00:56 index.db.v1437743889
-rw-r--r--. 1 ocuser1 ocuser1  3787 Jul 18 21:34 state.conf.v1436749707
-rw-r--r--. 1 ocuser1 ocuser1 24576 Jul 18 21:34 index.db.v1436749697
-rw-r--r--. 1 ocuser1 ocuser1  3641 Jul 13 02:34 state.conf.v1436110809
-rw-r--r--. 1 ocuser1 ocuser1 24576 Jul 13 02:34 index.db.v1436106928
[ocuser1@srv02 root]$

**Comment by PVince81** [comment]
Slightly related: debounce expire jobs https://github.com/owncloud/core/issues/16826

**Comment by MorrisJobke** [comment]
Fixed in 8.1.5 and 8.2.2 and the upcoming 9.0.0 - see #20425
