### ISSUE TITLE
LDAP wizard tab: if you mouse over the "descriptions" of each field, the cursor turns into a finger cursor.

### ISSUE THREAD

**Issue by davitol** [owncloud/core#20345]
### Steps to reproduce
1. Go to LDAP wizard
2. Mouse over the "descriptions" of any field (all tabs have the same behaviour)
### Expected behaviour

The cursor should not change.
### Actual behaviour

The cursor turns into a finger cursor.
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:**ownCloud 9.0 pre alpha (daily) Build:2015-11-05T05:14:55+00:00 b23159fa5e9540aa10dd9e39124fe8471f129a02

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```
```
### Client configuration

**browser**
 Firefox.

**Comment by PVince81** [comment]
moved to grouped UX ticket: https://github.com/owncloud/user_ldap/issues/69
