### ISSUE TITLE
There is something wrong when I use swift as external storage

### ISSUE THREAD

**Issue by kebenxiaoming** [owncloud/core#20343]
Recently,I use swift as external storage,it can be used normally.But something happened in owncloud.log when I upload or delete files:

{"reqId":"d60b3118a7d20f90e323463eaf1b2f49","remoteAddr":"127.0.0.1","app":"files_external","message":"Client error response\r\n[status code] 404\r\n[reason phrase] Not Found\r\n[url] http:\/\/192.168.200.188:8080\/v1\/AUTH_0fd51bb47779419e890c7320c12fbc43\/1001001166\/1.zip","level":3,"time":"2015-11-05T09:08:49+00:00"}

Maybe it's the problem of v1 authentication?

Wait for response and thx.

**Comment by LukasReschke** [comment]
Thanks a lot for your report. To debug this properly we need some more information.

Could you please fill out the issue template as described at https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version? Thanks a lot!

**Comment by kebenxiaoming** [comment]
@LukasReschke .OK,thx.

**Comment by RealRancor** [comment]
> ownCloud version: 8.0.4.2

Have you considered to update/upgrade to one of the latest stable 8.0.9/8.1.4/8.2.0. When having such issues its always a good idea to use the latest available version to avoid reporting an issue which might be already fixed.

**Comment by kebenxiaoming** [comment]
@RealRancor 

Maybe I can modify this like the lastest version like this:

private function doesObjectExist($path) {
		try {
			$this->getContainer()->getPartialObject($path);
			return true;
		} catch (ClientErrorResponseException $e) {
			// Expected response is "404 Not Found", so only log if it isn't
			if ($e->getResponse()->getStatusCode() !== 404) {
				\OCP\Util::writeLog('files_external', $e->getMessage(), \OCP\Util::ERROR);
			}
			return false;
		}
	}

this is the lastest version modify,not write "404 Not Found" in log....

Thanks a lot.

**Comment by MorrisJobke** [comment]
> Have you considered to update/upgrade to one of the latest stable 8.0.9/8.1.4/8.2.0. When having such issues its always a good idea to use the latest available version to avoid reporting an issue which might be already fixed.

Indeed. We improved a lot for the swift storage in 8.2.0. Can you please try this version? Thanks

**Comment by kebenxiaoming** [comment]
@MorrisJobke 
I will consider to update to the latest stable version 8.2.0.Thanks

**Comment by PVince81** [comment]
(note: you need to first upgrade to 8.1.x and only then 8.2.x)

**Comment by kebenxiaoming** [comment]
@PVince81 OK,Thanks for your reminding.
