### ISSUE TITLE
Share link requires Javascript

### ISSUE THREAD

**Issue by fkraiem** [owncloud/core#20342]
### Steps to reproduce
1. Create a share link.
2. Give it to someone who does not have Javascript enabled.
### Expected behaviour

The receiver should be able to download the file.
### Actual behaviour

Intrusive screen blocking access to everything, including the download URL.
### Server configuration

**Operating system**: Ubuntu 14.04

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.5.9

**ownCloud version:** 8.2.0

**Updated from an older ownCloud or fresh install:** Updated

**List of activated apps:**
- activity: 2.1.3
- files: 1.2.0
- files_locking: 
- files_pdfviewer: 0.7
- files_sharing: 0.7.0
- files_texteditor: 2.0
- files_trashbin: 0.7.0
- files_versions: 1.1.0
- files_videoviewer: 0.1.3

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => 'oc03e0efe71b',
  'passwordsalt' => '',
  'trusted_domains' => 
  array (
    0 => 'owncloud.fkraiem.org',
  ),
  'datadirectory' => '/home/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.2.0.12',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '',
  'installed' => true,
  'mail_from_address' => 'firas',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'fkraiem.org',
  'theme' => '',
  'maintenance' => false,
  'forcessl' => true,
  'secret' => '',
  'enable_previews' => true,
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'forceSSLforSubdomains' => true,
  'memcache.local' => '\OC\Memcache\APCu',
  'loglevel' => 2,
  'trashbin_retention_obligation' => 'auto',
);

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Any

**Operating system:** Any

**Comment by PVince81** [comment]
You can manually append "/download" at the end of the link as a workaround.

**Comment by rysiekpl** [comment]
This seems so easy to fix, and would improve usability immensely. In our organisation we're running ownCloud behind a Tor Hidden Service, our Tor users would rather not use JavaScript. There are many functionalities oC can or should be able to offer without JS enabled.

**Comment by PVince81** [comment]
You need Javascript to use the ownCloud platform frontend.

If someone wants to build a Javascript-less frontend, it is already possible using the various HTTP APIs to manage files or links.

Note that the link share can also be a direct download link by appending "/download" or copying it from the field in the UI. Then the recipient can simply curl/wget said link.
