### ISSUE TITLE
Do not load all avatars on settings/user

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#20353]
Loading of the avatars should only be done when needed.
### Steps to reproduce
1. Create more then 250 users (50 may also be enough to show the issue)
2. Navigate to `index.php/settings/users`
3. Have a look at the network tab
### Expected

Only 20 (or how many users are displayed) avatars should be loaded:

```
index.php/avatar/user120/32
```
### Actual

All 250 avatars are loaded firing off 250 request against the server
### Improvements

Two things could be done as improvement:
1. Only load avatars close to the viewport:
   In case of user mgmt maybe the displayed entries + 10 more
2. Cache the result of the ajax request locally:
   It shouldn't be a problem when avatars are outdated for some minutes. This is quite normal in the web world today.

@PVince81 @MorrisJobke what do you think?

**Comment by MorrisJobke** [comment]
> @PVince81 @MorrisJobke what do you think?

Sounds good, but having to maintain two different paginations sounds weird, but maybe is the only way to do. Or better divide rendering and pagination. So better only render a part, but fetch the actual data in advance. SO the browser doesn't get overloaded but doesn't need to run requests.

**Comment by nickvergessen** [comment]
I mean we can also just not render the avatar:
https://github.com/owncloud/core/blob/1601e8acfe3df25d29760edaaa9ad29259f88c11/core/js/jquery.avatar.js#L78-82
```js
		var url = OC.generateUrl(
			'/avatar/{user}/{size}',
			{user: user, size: Math.ceil(size * window.devicePixelRatio)});

		$.get(url, function(result) {
```

I see no need in rendering them all, when they are not visible

**Comment by PVince81** [comment]
CC @rullzer

**Comment by PVince81** [comment]
loading avatars should be fine now that they don't require setupFS, at least better perf.

also we reduced the result set size again
