### ISSUE TITLE
Move mount.json to database configuration

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#20354]
Part of https://github.com/owncloud/core/issues/19156

- [ ] REQUIRES: occ command to add/edit/delete/import configs: https://github.com/owncloud/core/issues/20368
- [x] move mount.json to database by implementing a DB backend for the configuration
- [x] provide migration path to move existing configs to the DB (at update time?)

@icewind1991 @DeepDiver1975

**Comment by PVince81** [comment]
Note: there was already some thinking done here https://github.com/owncloud/core/issues/11261#issuecomment-61234239 regarding a possible DB structure.

CC @Xenopathic

**Comment by PVince81** [comment]
One challenge I see is for the mount.json in user homes, might require a repair step that iterates over all users. (please note that in many cases "userid" != "home folder name" in LDAP)

**Comment by karlitschek** [comment]
A way to add,edit,change mountpoints via occ is needed before we can do that. This is critical to automate certain deployment scenarios.

**Comment by PVince81** [comment]
@karlitschek you're right, I forgot those details. Added in the original post and raised as https://github.com/owncloud/core/issues/20368

**Comment by icewind1991** [comment]
WIP: #20370

**Comment by PVince81** [comment]
We already have comments to import/export configs, closing.
The other ones are part of the task for providing occ commands for more fine-grained ext storage management.
