### ISSUE TITLE
Add occ command to add/change/delete ext storage configs

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#20368]
@icewind1991 @karlitschek @MTRichards

**Comment by PVince81** [comment]
CC @Xenopathic

**Comment by PVince81** [comment]
I believe that the LDAP feature already has such features, maybe some parts can be reused.
Also there's the occ:config commands from @nickvergessen.

**Comment by PVince81** [comment]
Prerequisite for https://github.com/owncloud/core/issues/20354

**Comment by nickvergessen** [comment]
No real reuse possible, since the only content it does is calling `\OC::$server->getConfig()->doStuff()`

outputting arrays is in the base class, that might be helpful for exporting/importing maybe

**Comment by PVince81** [comment]
- [ ] list: list mounts: https://github.com/owncloud/core/pull/20574
- [ ] export: export mounts as mount.json (similar format as before?)
- [ ] import: import mount.json config
- [ ] delete: delete config by id

Anything missing ?

**Comment by nickvergessen** [comment]
Looking at the discussion regarding config, maybe put all in one endpoint?

**Comment by PVince81** [comment]
@carlaschroder @jospoortvliet just a heads up of what's coming, see https://github.com/owncloud/core/issues/20368#issuecomment-157761007 (not finished yet)

**Comment by PVince81** [comment]
@icewind1991 any update on creating new mounts ? As discussed on IRC the command should take the minimum unchangeable parameters needed, like storage type: `occ files_external:create-mount storage_type` and make it output the id of the newly created mount. Then other parameters can be set using the other commands.

**Comment by PVince81** [comment]
- QA: https://github.com/owncloud/QA/issues/119
