### ISSUE TITLE
Request repos for Opensuse v42.1 Leap release

### ISSUE THREAD

**Issue by JohnA3** [owncloud/core#20374]
Please build/enable repos for current Opensuse release, Opensuse Leap 42.1, here
http://download.opensuse.org/repositories/isv:/ownCloud:/community/

**Comment by RealRancor** [comment]
As written in IRC you could have checked if OBS is supporting that new OpenSUSE version. That seems to be not the case:

https://en.opensuse.org/openSUSE:Build_Service_supported_build_targets

So just give them some time until the make that version available, especially that short after the release of this distro. That can't happen instantly.

**Comment by JohnA3** [comment]
irc?  No clue what you're talking about. 

OBS builds for leap 42.1 are most certainly supported.   There are lots of repos already enabled and populated for it.   It simply requires clicking one check box...

**Comment by RealRancor** [comment]
Ah, sorry. Then it was another user requesting this.

**Comment by LukasReschke** [comment]
@jnweiger

**Comment by JohnA3** [comment]
Could someone with privileges please just click the one checkbox required to enable this repo?

**Comment by jnweiger** [comment]
Done. Added openSUSE_Leap_42.1 to all build projects. 

https://build.opensuse.org/package/show/isv:ownCloud:community/owncloud successfully built version 8.1.4 for Leap.

Version 8.2.0 for Leap is available at https://download.owncloud.org/download/repositories/ce:/8.2/owncloud/

**Comment by JohnA3** [comment]
> Version 8.2.0 for Leap is available at https://download.owncloud.org/download/repositories/ce:/8.2/owncloud/

No, just 

openSUSE_13.1 owncloud-8.2.0-2.1
openSUSE_13.2 owncloud-8.2.0-2.1

are there.

**Comment by jnweiger** [comment]
https://download.owncloud.org/download/repositories/stable/owncloud/ has 9.0.1 built for openSUSE_Leap_42.1 (not 8.2)
