### ISSUE TITLE
Transactional file locking database backend warning is only shown when there is another warning.

### ISSUE THREAD

**Issue by Bubu** [owncloud/core#20376]
### Steps to reproduce
1. Have no other warnings in the admin page
2. Don't have a redis memory cache for file locking configured
3. Visit the owncloud admin page

### Expected behaviour
Message 
```Transactional file locking is using the database as locking backend, for best performance it's advised to configure a memcache for locking. See the documentation ↗ for more information.``` 
is shown.

### Actual behaviour
```  All checks passed. ``` shown.

### Server configuration
**Operating system**:  Arch Linux

**Web server:** apache 2.4.17

**Database:** mysql  Ver 15.1 Distrib 10.0.22-MariaDB, for Linux (x86_64) using readline 5.1

**PHP version:** PHP 5.6.15 (cli)

**ownCloud version:** (see ownCloud admin page)
8.2.0.12

**Updated from an older ownCloud or fresh install:**
Updated from 8.1 form 8.0

**List of activated apps:**

```
Enabled:
  - activity: 2.1.3
  - calendar: 0.8.0
  - contacts: 0.5.0.0
  - files: 1.2.0
  - files_external: 0.3.0
  - files_locking: 
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - updater: 0.6
Disabled:
  - admin_migrate
  - apptemplate
  - django_auth
  - emoji
  - encryption
  - encryption_dummy
  - external
  - files_archive
  - files_odfviewer
  - files_sgfviewer
  - files_svgedit
  - fluxx_compensator
  - impress
  - imprint
  - ownpad_lite
  - pong
  - pushnotifications
  - reader
  - search
  - tattoo
  - user_external
  - user_ldap
  - user_migrate
  - user_oauth
  - user_openid_provider
  - user_persona
  - user_saml
  - user_vd
  - user_webfinger
```

**The content of config/config.php:**

```
 "system": {
        "instanceid": "oc5rziive344",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "x.y.z"
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "datadirectory": "\/usr\/share\/webapps\/owncloud\/data",
        "overwrite.cli.url": "x.y.z",
        "dbtype": "mysql",
        "version": "8.2.0.12",
        "dbname": "dsg988-owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "mail_smtpmode": "sendmail",
        "mail_from_address": "owncloud",
        "mail_domain": "x.y.z"
        "loglevel": 1,
        "theme": "",
        "maintenance": false,
        "trashbin_retention_obligation": "auto"

```

**Are you using external storage, if yes which one:** 
local

**Are you using encryption:**
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox 42

**Operating system:**
Xubuntu 14.04

#### ownCloud log (data/owncloud.log)
Repeatedly this line:
```
Array to string conversion at /usr/share/webapps/owncloud/lib/private/template/functions.php#36 
```

#### Browser log
```
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://x.y.z 'unsafe-eval'"). admin
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery.min.js:5:0
```

**Comment by RealRancor** [comment]
@Bubu That is the expected behavior. You should use redis for transactional locking if possible. Until that the message is shown.

**Comment by Bubu** [comment]
Yes, I understand that. The point is the message is not shown unless there is some other warning to show.

**Comment by RealRancor** [comment]
Ah, i see. Seems you have a typo in:

> ownCloud version: (see ownCloud admin page)
8.0.12

There is no 8.0.12 available yet so you're probably running 8.2.0 when reading your config.php correctly?

**Comment by Bubu** [comment]
Yes, sorry I meant:   ```- version: 8.2.0.12```

**Comment by codebucketdev** [comment]
+1, I also have this issue :(
