### ISSUE TITLE
Nested AD Group share not working

### ISSUE THREAD

**Issue by gig13** [owncloud/core#20377]
I've had a user report that a group share isn't showing in their account since our upgrade to 8.1.3.

In researching, here's what I've found.

His uid is a member of three groups in oc_ldap_group_members: AG700 (the group on the share), CL550, OGS AG700 Archives. If I go to the users interface in ownCloud and click everyone I can search for this user and see his groups, but they're different. CL550, OGS AG700 Archives, OwncloudUsers, SC300 Personnel. AG700 is missing and OwncloudUsers and SC300 Personnel are added. Those two new groups have over 1000 people and there's a separate ticket about them being empty in the oc_ldap_group_members table. Reference https://github.com/owncloud/core/issues/20274

If I select AG700, it's empty.

In AD, AG700 has no direct users as members, the CL groups are members. This user is a member of AG700 by virtue of CL550 being a member. We have nested groups turned on in our settings and it appears that the old system is working with nested groups because the oc_ldap_group_members table is reflecting the hundreds of users who are members via their respective CL groups. But the new method that directly references AD for sharing is not working with our nested groups.

### Server configuration
**Operating system**: RHEL 

**Web server:** Apache

**Database:** Galera Cluster

**PHP version:** 5.5.30

**ownCloud version:** 8.1.3

**Updated from an older ownCloud or fresh install:** Updated

**List of activated apps:** See s3 config report https://s3.owncloud.com/owncloud/index.php/apps/files?dir=%2FShared%2Fowncloud%2Fsupport%2Fgithub-issues%2Fcore%2F20377

**Are you using external storage, if yes which one:** No

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory

#### LDAP configuration
See s3 config report

@MorrisJobke @blizzz

**Comment by gig13** [comment]
Is https://github.com/owncloud/core/pull/18123 safe to patch on top of 8.1.3 ?

**Comment by MorrisJobke** [comment]
> Is #18123 safe to patch on top of 8.1.3 ?

As a rule of thumb: It's never safe to patch a random patch ontop of any release. That's why we have QA for and why we test releases as a whole again (after already testing single patches).

**Comment by MorrisJobke** [comment]
This issue indeed looks like be fixed in 8.1.4. @gig13 Can you try to upgrade to 8.1.4?

**Comment by gig13** [comment]
I have communicated such, upgrade to 1.8.4 in testing.

**Comment by bboule** [comment]
@gig13 any word back on this?  Can we close?

**Comment by gig13** [comment]
We can close it out
