### ISSUE TITLE
"you may not use dots in the database name" - this is false

### ISSUE THREAD

**Issue by andrey-utkin** [owncloud/core#20381]
You can use dots in DB name in MySQL for sure if you use backticks when specifying it. At last Wordpress copes with that. Also nothing should prevent you to use dots in SQLite DB name. This is very annoying and frustrating issue, because
- it is natural to name database by FQDN of the site which uses it;
- this field is filled after you have created DB and have set up the permissions, so it forces you to do this job twice without technical reason.

**Comment by RealRancor** [comment]
@andrey-utkin @karlitschek Dup of https://github.com/owncloud/core/issues/19390

**Comment by RealRancor** [comment]
@andrey-utkin As you have found #19390 feel free to close here.
