### ISSUE TITLE
Upgrading to OC 8.2 gives error "Could not acquire a shared lock on the config file /var/www/owncloud/config/config.php"

### ISSUE THREAD

**Issue by step4wd** [owncloud/core#20385]
I upgraded to OC 8.2 using the new repo for Ubuntu. Then I ran the command `./occ upgrade` and got this output:

    PHP Warning:  flock() expects parameter 1 to be resource, boolean given in /var/www/owncloud/lib/private/config.php on line 198

    An unhandled exception has been thrown:
    exception 'Exception' with message 'Could not acquire a shared lock on the config file /var/www/owncloud/config/config.php' in /var/www/owncloud/lib/private/config.php:199

    Stack trace:
    #0 /var/www/owncloud/lib/private/config.php(59): OC\Config->readData()
    #1 /var/www/owncloud/lib/base.php(133): OC\Config->__construct('/var/www/ownclo...')
    #2 /var/www/owncloud/lib/base.php(485): OC::initPaths()
    #3 /var/www/owncloud/lib/base.php(1061): OC::init()
    #4 /var/www/owncloud/console.php(42): require_once('/var/www/ownclo...')
    #5 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')

Please help!

**Comment by RealRancor** [comment]
@step4wd You need to run ./occ upgrade as the webservers user:

https://doc.owncloud.org/server/8.2/admin_manual/configuration_server/occ_command.html#run-occ-as-your-http-user

The message itself is a duplicate of https://github.com/owncloud/core/issues/15417

**Comment by step4wd** [comment]
Based on your help, I ran this command `sudo -u www-data php occ upgrade` and got the following output:

    ownCloud or one of the apps require upgrade - only a limited number of commands are available
    Set log level to debug - current level: 'Debug'
    Checked database schema update
    Checked database schema update for apps
    Updated database
    Disabled incompatible app: calendar
    Disabled 3rd-party app: calendar
    Disabled incompatible app: contacts
    Disabled 3rd-party app: contacts
    Updating <files_texteditor> ...
    Updated <files_texteditor> to 2.0
    Updating <gallery> ...
    Updated <gallery> to 14.2.0
    Updating <files> ...
    Updated <files> to 1.2.0
    Updating <activity> ...
    Updated <activity> to 2.1.3
    Updating <files_sharing> ...
    Updated <files_sharing> to 0.7.0
    Updating <files_trashbin> ...
    Updated <files_trashbin> to 0.7.0
    Updating <files_versions> ...
    Updated <files_versions> to 1.1.0
    Update 3rd-party app: calendar
    Update 3rd-party app: contacts
    Update successful
    Maintenance mode is kept active
    Reset log level to 'Debug'

Now what should I do since it said to have kept active the Maintenance mode?

**Comment by RealRancor** [comment]
Hi,

just disable the maintenance mode via occ as also described in the linked documentation above:

https://doc.owncloud.org/server/8.2/admin_manual/configuration_server/occ_command.html#maintenance-commands-label

**Comment by step4wd** [comment]
Thank you!

**Comment by intoxicadocoder** [comment]
Change owner of ownclod folder to apache or www-data
  chown -Rf apache:apache owncloud
