### ISSUE TITLE
Prolem upgrading to 8.1.4 server

### ISSUE THREAD

**Issue by TerryHewitt** [owncloud/core#20382]
Doing the upgrade and  I got this

Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "contacts_index" as such route does not exist.

Followed by a message to report it to the OwnCloud community.

Could someone advise how to fix the upgrade and get my owncloid server back online?

Best wishes
Terry

**Comment by TerryHewitt** [comment]
Previous message was doing the upgradw via web interface.

doing occ upgrade worked.

Best wishes
Terry

**Comment by RealRancor** [comment]
@TerryHewitt @karlitschek 

Dup of #19145, #20125, #20207 and some more.

#19145 is still open

Really wonder why people are not finding those duplicates?
