### ISSUE TITLE
Weird group list behaviour in settings/users

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#20398]
Group names matter!!!!

### Steps to reproduce
1. Create a user
2. Make the user part of group `test3`
3. Make the user part of group `g`
4. Login as user2 that is a subadmin of group `g` and `test3`
5. Play around with the groups:
  1. Show
![bildschirmfoto vom 2015-11-09 13 26 34](https://cloud.githubusercontent.com/assets/213943/11033720/db7ce816-86e5-11e5-9620-f8e454cf6282.png)
  2. Remove from group `test3`
![bildschirmfoto vom 2015-11-09 13 26 42](https://cloud.githubusercontent.com/assets/213943/11033722/dcb01974-86e5-11e5-9093-480d97e5e5a9.png)
  3. Add to group `test3`
![bildschirmfoto vom 2015-11-09 13 26 49](https://cloud.githubusercontent.com/assets/213943/11033724/de28b2f2-86e5-11e5-906b-e717df0b5a43.png)

### As admin
even more weirdness:
![bildschirmfoto vom 2015-11-09 13 23 43](https://cloud.githubusercontent.com/assets/213943/11033837/eed0ddea-86e6-11e5-94d6-308ae18a855c.png)
![bildschirmfoto vom 2015-11-09 13 23 46](https://cloud.githubusercontent.com/assets/213943/11033839/f0116daa-86e6-11e5-92cc-cba6b655b836.png)
![bildschirmfoto vom 2015-11-09 13 23 48](https://cloud.githubusercontent.com/assets/213943/11033840/f13bfcae-86e6-11e5-82b2-302be7010ae9.png)
![bildschirmfoto vom 2015-11-09 13 23 50](https://cloud.githubusercontent.com/assets/213943/11033841/f24c1b06-86e6-11e5-963c-7853e5b83153.png)

@PVince81

**Comment by nickvergessen** [comment]
PS: a hard refresh after any time displayes the correct and expected list of groups

**Comment by PVince81** [comment]
Something to look into when ajaxifying the group names. Will be obsoleted by https://github.com/owncloud/core/pull/10994
