### ISSUE TITLE
Double displayname doesn't result in showing the e-mail addres in the share menu

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/core#20391]
An user reported:
> We noticed that once there are more than one user with exactly the same "Display Name" configured, that the share menu shows all the names, but doesn't show the e-mail address behind it to know which one is which. 

### Steps to reproduce
1. Create 2 users
2. Add the same displayname (John Doe) to both users
3. Share a folder and start typing "John D…"

### Expected behaviour
ownCloud should show additional information (like email) to distinguish users

### Actual behaviour
I see both users, but don't know which is the right one

@MorrisJobke Are there any plans to improve this?

00004123

**Comment by MorrisJobke** [comment]
I just thought about this. It would be ideal to show the email address only if there are duplicate entries. Then I checked the response on an autocomplete request and it doesn't contain any further information.

@rullzer Does it make sense to also deliver the email address (if set) to the frontend. Maybe this is already available as an OCS API and then show this info when it is needed. Or is this too much? Or the wrong approach?

**Comment by rullzer** [comment]
@MorrisJobke I would go for the user id (I think we had a ticket about that)... since the e-mail can be empty

**Comment by rullzer** [comment]
https://github.com/owncloud/core/issues/20291

**Comment by MorrisJobke** [comment]
> @MorrisJobke I would go for the user id (I think we had a ticket about that)... since the e-mail can be empty

Nah...just think about LDAP ... you won't use the user ID -> it's internal stuff ;)

**Comment by MorrisJobke** [comment]
Ah okay...let's close this as duplicate

**Comment by rullzer** [comment]
well then we need to think about something generic. Since we can't assume the e-mail is set.

**Comment by MorrisJobke** [comment]
@rullzer https://github.com/owncloud/core/issues/20291#issuecomment-155087501
