### ISSUE TITLE
Registering jobs with install.php works until an exception occurs

### ISSUE THREAD

**Issue by butonic** [owncloud/core#20399]
On an Exception the job is removed from the joblist: https://github.com/owncloud/core/blob/master/lib/private/backgroundjob/job.php#L57

@DeepDiver1975 @PVince81 My stomach tells me we are going to see bug reports coming in about files not being moved to trash, or versions not being aggregated, or orphaned shares not being cleaned up.

ref https://github.com/owncloud/core/issues/15460

**Comment by MorrisJobke** [comment]
Oha...nice spot. Indeed looks like a potential issue.

**Comment by MorrisJobke** [comment]
cc @nickvergessen

**Comment by nickvergessen** [comment]
well basically the job thing shouldn't remove jobs when they failed and they are recursive?
