### ISSUE TITLE
What to do when "Recovery Key" is forgotten / not documented?

### ISSUE THREAD

**Issue by skottitwo** [owncloud/core#20407]
Hi, is there a way to reset the "recovery key"? Situation is that the one person setting up owncloud with encryption took the key with him. Users are all fine but we want to move oc to new hardware. And we would feel better if we had a chance to get back in control.
Thank you and best
skotti

**Comment by aspdye** [comment]
You should Backup all User Data (unencrypted) and setup an new ownCloud Instance :) After that You can restore all User Data Manually 😁 😁

**Comment by RealRancor** [comment]
For changing a recovery key you need the old one as seen here:

https://doc.owncloud.org/server/8.2/admin_manual/configuration_files/encryption_configuration.html#enabling-users-file-recovery-key

Your only chance is probably the one above or the decryption of all files via occ.

**Comment by RealRancor** [comment]
Btw. this is the core bugtracker where issues and feature requests are posted. Such questions are better placed at the forums or the users mailinglist.

If you think this special use case is missing in the docs you can note that at:

https://github.com/owncloud/documentation/issues

**Comment by skottitwo** [comment]
It all depends on the perspective one takes. I know this is this the core bugtracker, so, ... since encryption is a core application. And it is and will be a core problem for admins if anything like this may happen to any of them and their users. So this will have to go to documentation cause I couldn't find anything else I wanted to trust on information about this. This is a choking matter for us, pardon the pun.
If there is technical way to give admins another backdoor? If you implement something like this all user of owncloud certainly want to know ;-) and can.

**Comment by RealRancor** [comment]
So you want to have a "Recovery Password" for a "Recovery Password"? :see_no_evil:

**Comment by skottitwo** [comment]
I know that it makes no sense. But the system I inherited has gone in production mode and they didn't talk/document about what they were doing (as it seems) and I am afraid I will be shredding user data in the process of upgrading oc. Takin care of the users data, that's all I wanna do. Backup is here and its workin but any change GBs on data takes a looong time and will delay us further.
In this case here? Even a more explicit warning in the documentation might not have helped in the first place. Who reads a manual anyways ....
