### ISSUE TITLE
External Storage: $user for Directory DisplayName

### ISSUE THREAD

**Issue by htwsaaraub** [owncloud/core#20400]
Hello,

I like to recommend an enhencement. 
I would be great to use the $user Variable in the Display Name Field in External Storage Directory. 
In 8.2 setting the Display Name to $user in the admin section leads to a folder called $user instead of the Username.
For our Home Directories I would like to set the Display Name of the Folder "Home" to the Username like it's shown for the Windows Network Share.

**Comment by MorrisJobke** [comment]
cc @Xenopathic

**Comment by Xenopathic** [comment]
What is the 'Display Name Field in External Storage Directory'?

**Comment by htwsaaraub** [comment]
I just checked the Documentation. 
It's simply called Folder Name. 
The Display Name of the external Storage Mount Point.

**Comment by Xenopathic** [comment]
Ah. From my POV the `$user` stuff is currently contributing to code smell, and while it's a really useful feature we need to implement it a lot better than we currently are. Unfortunately this means I don't see this as a priority for now.

**Comment by mmattel** [comment]
:+1:

**Comment by 0fe57b3f** [comment]
Hi, just wondering if the issue might be fixed in 8.3 (or 8.2 point release)? The $user var as "Folder name" is working for us in 8.1.5.
