### ISSUE TITLE
Make storage API more flexible, in regards to etag propagation, cache impl

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#20401]
- [x] investigate how to give the storage control of etag propagation / what code paths are assuming etag propagation from the outside
- [x] make current Cache interface public https://github.com/owncloud/core/pull/20898
- [x] implement a test Storage that has no Cache implementation (unit test, make sure everything can still work) => https://github.com/icewind1991/files_nullcache
- [ ] support for string file ids
- [x] Move `\OC\Files\Cache\Updater` to the storage level https://github.com/owncloud/core/pull/20731
- [x] Possible ideas for simplified propagation #20231 
- [ ] provide an example implementation (see https://github.com/owncloud/core/pull/20898#issuecomment-173228174)

@icewind1991 @DeepDiver1975 @schiesbn

**Comment by PVince81** [comment]
This PR from @icewind1991 moves etag propagation to the storage level: https://github.com/owncloud/core/pull/20439

**Comment by PVince81** [comment]
Waiting for @DeepDiver1975's feedback to get a summary of the core requirements for storage extensibility.

**Comment by PVince81** [comment]
I added an entry "support for string file ids". Might be a more complex task as it might have consequences on the UI.

**Comment by icewind1991** [comment]
https://github.com/icewind1991/files_nullcache can be used for testing oc against a storage backend that doesn't provide a cache.
Any cache write will throw an exception thus making it possible to find code paths relying on the cache.

Currently everything breaks when you enable the app :smile:

**Comment by PVince81** [comment]
Cool. What's your next step to make it not explode ? (or explode less)

**Comment by icewind1991** [comment]
Once #20439 I can make the Updater storage specific/overwritable

**Comment by PVince81** [comment]
@icewind1991 if the example test storage is done, please ticket the matching checkbox.

**Comment by PVince81** [comment]
Regarding string id, would be good to find out whether "tolerating" string ids in the core API is enough to make it work, and ignore the clients and third party apps in this first step.

**Comment by PVince81** [comment]
cache interfaces was merged: https://github.com/owncloud/core/pull/20898

@icewind1991 please make checkboxes / tickets for the remaining tasks.

**Comment by DeepDiver1975** [comment]
> I added an entry "support for string file ids". Might be a more complex task as it might have consequences on the UI.

Changing the file id is kind of critical - the client is expecting a fixed size value of 36 chars - https://github.com/owncloud/client/blob/master/csync/src/csync.h#L148

**Comment by PVince81** [comment]
I suggest we move the string id to a separate ticket to discuss for 9.1 and close this one ?

@DeepDiver1975 @icewind1991

**Comment by PVince81** [comment]
Doc ticket https://github.com/owncloud/documentation/issues/2150

**Comment by PVince81** [comment]
Raised ticket for string id: https://github.com/owncloud/core/issues/22330
