### ISSUE TITLE
Owncloud 8.2 Shared folder link issue

### ISSUE THREAD

**Issue by directict** [owncloud/core#20408]
### Steps to reproduce
1. Create a folder in owncloud
2. Create 30 subfolders in the folder created at 1.
3. Share the created folder(step1) via link and allow editing.
4. Navigate to the folder link, and log in.
5. Only the first 20  (or random 21 in chrome) Folders are shown! and also it is not possible to upload files/folders

### Expected behaviour
All folders should be visible and also the upload function should be working.

### Actual behaviour
Not all folders are visible
Upload not working.

### Server configuration
**Operating system**:
CentOS 6.7
**Web server:**
nginx
**Database:**
mysql
**PHP version:**
5.6.14 
**ownCloud version:** (see ownCloud admin page)
8.2.0 (stable) 

**Updated from an older ownCloud or fresh install:**
Updated from an older owncloud (8.0)
**List of activated apps:**
Enabled:
  - activity: 2.1.3
  - files: 1.2.0
  - files_external: 0.3.0
  - files_locking:
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - user_ldap: 0.7.0
Disabled:
  - encryption
  - external
  - notifications
  - user_external

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system --public
from within your ownCloud installation folder
{
    "system": {
        "instanceid": "ocyk8tdggrfu",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "",
            ""
        ],
        "datadirectory": "\/storage\/storage",
        "overwrite.cli.url": "",
        "dbtype": "mysql",
        "version": "8.2.0.12",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "maintenance": false,
        "dbname": "-",
        "dbhost": "-",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "DirectICT-8.2",
        "forcessl": true,
        "mail_from_address": "no-reply",
        "mail_smtpmode": "smtp",
        "mail_domain": "",
        "loglevel": 3,
        "mail_smtphost": "",
        "mail_smtpport": "",
        "trashbin_retention_obligation": "auto"
    }
}


Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
LDAP YES, but not relevant?
```

### Client configuration
**Browser:**
Firefox, Google Chrome, Internet Explorer
**Operating system:**
Windows 7 + Windows 10.
### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by RealRancor** [comment]
@directict Thats a duplicate of #20388 and #19886 which gets fixed with oC 8.2.1

**Comment by directict** [comment]
@RealRancor OK Thanks, excuse me for making duplicates.. do you know the ETA of 8.2.1? or where can i check this?

**Comment by RealRancor** [comment]
@directict Planned release dates are listed here: https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule

**Comment by RealRancor** [comment]
Ah, feel free to close this issue with the Close Button below the comments field.

**Comment by directict** [comment]
done thanks, i will try to manually fix it.. 17-11 is a long wait ;-)
