### ISSUE TITLE
8.2.0 case sensitive file search for files with cyrillic file names in shared folders

### ISSUE THREAD

**Issue by Hettikus** [owncloud/core#20406]
### Steps to reproduce
1. Add some files(with cyrillic names) to folder(any)
2. Share the folder with someone else
3. Login under "someone else"'s account
4. Try to search for files with cyrillic names
### Expected behaviour

File search should be case insensitive
### Actual behaviour

File search is case sensitive

The problem exists ONLY for shared folders shared by other people. Inside account's own folders search behaves normally for both latin and cyricllic names

Cyrillic filename for testing purposes, that you can cut and paste at your leasure with letters in different cases
Прометей ПРОМЕТЕЙ прометей
### Server configuration

**Operating system**:
FreeBSD 10.2

**Web server:**
nginx 1.8.0

**Database:**
PostgreSQL

**PHP version:**
5.6

**ownCloud version:** (see ownCloud admin page)
8.2

**Updated from an older ownCloud or fresh install:**
fresh

**Comment by PVince81** [comment]
@butonic

**Comment by PVince81** [comment]
@VicDeo 

For a search on the root folder, I believe it uses the database directly. But for mount points (a received share is a mount point) it might use another approach.

**Comment by PVince81** [comment]
Please try again with 9.1.4 or 10.0 beta and reopen if the problem persists.
