### ISSUE TITLE
Why owncloud packages exist only for xUbuntu?

### ISSUE THREAD

**Issue by mahnunchik** [owncloud/core#20416]
Why owncloud packages exist only for xUbuntu?

According to the following page: https://download.owncloud.org/download/repositories/stable/owncloud/
There are packages only for: xUbuntu_12.04, xUbuntu_14.04, xUbuntu_14.10, xUbuntu_15.04.

Does `owncloud` packages support `just` Ubuntu? Or is it a naming mistake?

**Comment by DeepDiver1975** [comment]
![bildschirmfoto von 2015-11-10 08 13 25](https://cloud.githubusercontent.com/assets/1005065/11056522/f95f798c-8782-11e5-8302-602bee5b17e8.png)

@mahnunchik I don't get your question - there are other distributions listed as well

**Comment by RealRancor** [comment]
@mahnunchik The X just means that those packages can be used for all flavors:

Ubuntu, Lubuntu, Xubuntu

and so on. The x is just a placeholder here.

**Comment by mahnunchik** [comment]
@RealRancor Thanks for clarification!

@DeepDiver1975 Packages for other systems named clear to me. I was surprised by the names of packages for Ubuntu.

<img width="771" alt="2015-11-11 00 09 41" src="https://cloud.githubusercontent.com/assets/780935/11070972/2dc99b1c-8800-11e5-93cd-1ca9590eb92e.png">

I thought that they exist only for [Xubuntu](http://xubuntu.org/) variant of Ubuntu.

**Comment by mahnunchik** [comment]
Also I have one more question about Ubuntu packages.

There are both variants of packages: https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client

For Ubuntu and xUbuntu. What does it mean?
