### ISSUE TITLE
owncloud shared by link does not support resume

### ISSUE THREAD

**Issue by jsalatiel** [owncloud/core#20413]
I have noticed that files shared by link can not resume when download from wget/curl/...
They always start from beginning. Am i right or in some moment in the past resume was supported ?
debian jessie
`
dpkg -l | grep -i 'owncloud \|php5 \|apache2 '
ii  apache2                               2.4.10-10+deb8u3                     amd64        Apache HTTP Server
ii  libapache2-mod-php5                   5.6.14+dfsg-0+deb8u1                 amd64        server-side, HTML-embedded scripting language (Apache 2 module)
ii  owncloud                              8.1.4-12.1                           all          The ownCloud Server - Private file sync and share server
ii  owncloud-config-apache                8.1.4-12.1                           all          The ownCloud configuration for the apache web server
ii  php5                                  5.6.14+dfsg-0+deb8u1                 all          server-side, HTML-embedded scripting language (metapackage)

`

**Comment by RealRancor** [comment]
@jsalatiel From my understanding you need configure https://doc.owncloud.org/server/8.1/admin_manual/configuration_files/serving_static_files_configuration.html to make resume to work with downloads in 8.1

Please note that X-Sendfile was removed in https://github.com/owncloud/core/pull/18881 as discussed in https://github.com/owncloud/core/issues/18870

**Comment by DeepDiver1975** [comment]
after moving the files app to webdav we can move shared links to webddav as well - webdav supports resume.

**Comment by MorrisJobke** [comment]
Isn't it already possible to use the public webdav endpoint to download a file (which is already used for federated cloud sharing). Then we only need to change the URL and can resume the download.

**Comment by MorrisJobke** [comment]
cc @schiesbn

**Comment by PVince81** [comment]
It is, but the link might look ugly, for example:
- for a file: "https://token@host/owncloud/public.php/webdav/" (yes, no file name...)
- for a file inside the share: "https://token@host/owncloud/public.php/webdav/fileinside.ogg"

More work might be required to provide an additional / replacement endpoint that includes the file name.

**Comment by MorrisJobke** [comment]
> More work might be required to provide an additional / replacement endpoint that includes the file name.

Isn't this the case when we move to the new dav app? cc @DeepDiver1975

**Comment by mitar** [comment]
> More work might be required to provide an additional / replacement endpoint that includes the file name.

Where does one get `token` programmatically? Because when I make an URL for sharing in ownCloud 8.2.1 I get such URL:

```
https://host/owncloud/index.php/s/token/download?path=%2F&files=fileinside.ogg
```

If I then use the token to make the Webdav URL things work, but how can I get this URL programmatically?

I am looking into this because I would like to address https://github.com/owncloud/music/issues/457, so I would like to replace custom URLs Music app provides to download files with Webdav links which can be both sought (http range) and also accessible from the public, without having to be logged into ownCloud. Current code to generate URLs is [here](https://github.com/owncloud/music/blob/master/db/track.php#L123). Any suggestion how I could replace this so that it provides a public Webdav URL for the same file?

**Comment by PVince81** [comment]
There is no clean API to get it. There is a global hidden input field containing it. You can use `$('[name=sharingToken]').val()` to read it.

**Comment by mitar** [comment]
I would like to find that in the PHP, on the server side, so that I can put it into the URL generated by the JSON API. And is this sharing token global or to what it is linked?

**Comment by PVince81** [comment]
It does now, please try 9.1.0 beta2.
