### ISSUE TITLE
Files menu doesn't have borders in edge browser.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#20419]
### Steps to reproduce

1. Using edge, in the files view, click in the '+' and show the dropdown.

### Expected behaviour
Same as in chrome or firefox.

### Actual behaviour
No borders:

![screen shot 2015-11-10 at 09 10 54](https://cloud.githubusercontent.com/assets/9048796/11057710/96a38120-878d-11e5-9aa8-4bf3fce886d5.png)

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.2.1.0","versionstring":"8.2.1 RC1","edition":"Enterprise"}

Happening also in master branch.

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Server logs**
```

```

cc @jancborchardt

**Comment by PVince81** [comment]
Hmmm, I thought I added a fallback border for all IE.

**Comment by SergioBertolinSG** [comment]
Ok I guess this is a duplicate of this one https://github.com/owncloud/core/issues/18992
But that one is closed and it is still happening.

**Comment by PVince81** [comment]
@SergioBertolinSG mind checking if you see the border in IE8/IE9 ?
If yes then maybe additional work is needed to make it appear for Edge.

**Comment by SergioBertolinSG** [comment]
Tested microsoft browsers:
IE8 : has border - :white_check_mark: 
IE9 : has border - :white_check_mark: 
IE10: doesn't have border - :x: 
IE11: doesn't have border - :x: 
Edge: doesn't have border - :x:

**Comment by PVince81** [comment]
Hmm....... I'd also expect newer IE versions to support the CSS we use.

**Comment by PVince81** [comment]
Ok, here are my findings:
- there is no version of IE that supports filter: drop-shadow (not the same as box-shadow)
- the workaround is expecting the class "ie" to be set on the html element. However that class is missing for IE >= 10
- IE >= 10 don't support conditional comments, so the trick we used to detect IE here cannot work and requires another trick...

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/20434
