### ISSUE TITLE
Show external storage status in file list + prompt credentials if different

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#20427]
- Whenever an external storage triggers a specific exception (to be determined), the exception must be propagated to the file list JS.
- the filelist row must be shown in red if there is a credentials issue
- the user should be able to click the row and a credentials popup will ask for credentials (this only if the exception was related to wrong credentials, not StorageNotAvailable)

Open questions:
- need to find the right place in the filesystem code to identify storage availability and return this through Webdav (remember, in the future we only use webdav)
- OR have additional JS code loaded in the files app that checks the mount points **after** the file list was loaded (similar to how it used to be done in the WND) app. That part might be easier to implement.

@jmaciasportela @icewind1991

**Comment by Xenopathic** [comment]
As a more generic method than a credentials popup, we should rather send the user to the external storage configuration section if the external storage is unavailable and they click on the entry in the file list. It will reduce the overall code complexity and re-use the configuration GUI

**Comment by icewind1991** [comment]
Will that work correctly if it's an admin setup mount where the user will need to enter the password (use case for WND)

**Comment by Xenopathic** [comment]
@icewind1991 Yes, since once #18999 is merged (which needs a rebase and re-review then it's ready) all applicable global storages will be displayed in the personal settings, and the credentials for said storages can be directly modified by the user

**Comment by jmaciasportela** [comment]
@Xenopathic  I'm mixing some javascript from WND app with files_external. Big part can be reused. Once I will have a working version we will discuss about the best UX.

**Comment by jmaciasportela** [comment]
Some advances:
![reloades](https://cloud.githubusercontent.com/assets/1454351/11145484/2b78b7fa-8a06-11e5-95fa-b3b21f4a019d.gif)

http://docker.oc.solidgear.es:53648

Branch: core/issue_20427

**Comment by PVince81** [comment]
Requires: https://github.com/owncloud/core/issues/11792

The reason why the invalid mount doesn't appear under "All files" is because the mount point might get discarded when invalid. We should change the behavior and always show the mount point folder, but entering it will throw StorageNotAvailable. https://github.com/owncloud/core/issues/11792

**Comment by jmaciasportela** [comment]
- [ ]  Different icons for different files_external storages #20598 
- [ ]  Capture different errors on storage exceptions

**Comment by PVince81** [comment]
@jmaciasportela your PR https://github.com/owncloud/core/issues/20569 already shows the icons, I think it's enough for 9.0.

**Comment by PVince81** [comment]
- [ ] dialog with credentials: https://github.com/owncloud/core/pull/20920

**Comment by PVince81** [comment]
Dialog as added, closing.
