### ISSUE TITLE
If reshare is disabled no input should be shown

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#20420]
Having following settings (only allow incoming federated shares)

<img width="658" alt="bildschirmfoto 2015-11-10 um 09 59 52" src="https://cloud.githubusercontent.com/assets/245432/11058246/d139db3c-8791-11e5-9ac0-8d13b232dcab.png">

* User A from remote server is sharing a folder via federated cloud sharing with user B at the above server
* B tries to share the folder and opens the share dialog:

### actual behavior

![bildschirmfoto 2015-11-10 um 09 55 15](https://cloud.githubusercontent.com/assets/245432/11058176/2dd752c6-8791-11e5-8cd4-787366e98717.png)

### expected behavior

The top input field should not be visible.

cc @rullzer @schiesbn

**Comment by MorrisJobke** [comment]
I replaced the images with english versions ;)

**Comment by nickvergessen** [comment]
The first checkbox from `Sharing` allows user's to share files locally?

**Comment by MorrisJobke** [comment]
> The first checkbox from Sharing allows user's to share files locally?

A right :( Is it possible to disable the local sharing and only receiving federated shares.

**Comment by MorrisJobke** [comment]
Let me retest everything.

**Comment by MorrisJobke** [comment]
But it is still weird: resharing of a received share is forbidden. Then it still should not work. It's definitely a bug in the view. I can't share anything, because it's a received share. The input should not be there.

**Comment by MorrisJobke** [comment]
I just checked the code and federated cloud shares doesn't seem to be threaded as shares - therefore resharing is possible even if it is not allowed in the admin settings. @rullzer can you have a look at this?

**Comment by nickvergessen** [comment]
s/reshare/remote share

> therefore "remote share" is possible even if resharing is not allowed in the admin settings.

Sounds like validity to me, but yeah

**Comment by rullzer** [comment]
So currently federated shares are still those special shares. There is the plan to get this all sorted out for the new sharing stuff (but first get the basic working as they should). And as @nickvergessen I think from the current technical point of view the situation is indeed valid.

I also understand that users can expect something different.

Let me think about a quick work around here...

**Comment by bboule** [comment]
Feature Request

**Comment by MTRichards** [comment]
This is an enhancement to federated sharing, right?
If a federated share is shared by with me, I can't share it with other users on this system if resharing is disabled. Right?

**Comment by PVince81** [comment]
@rullzer any update on this regarding new sharing ?

**Comment by rullzer** [comment]
Incomming federated shares are still handled the old way. @schiesbn has plans to intergrate this nicely. Then we can say you can't reshare... so you also can't reshare federated shares.

But nothing for 9.0...

Also a quick fix is non trivial as incommnig federated shares are basically webdav mounts...

**Comment by PVince81** [comment]
I think this is mostly about forbidden the creating of remote shares if the source folder is already shared, which could be done on OCS API level and also in the GUI.

Enforcing this in the public.php/webdav is another story.

**Comment by rullzer** [comment]
I think we fixed this with moving the webUI to webdav. At least here it looks good.

@MorrisJobke can you verify?

**Comment by MorrisJobke** [comment]
> @MorrisJobke can you verify?

Yes - it is working:

<img width="310" alt="bildschirmfoto 2016-02-19 um 09 00 25" src="https://cloud.githubusercontent.com/assets/245432/13169631/4695480e-d6e7-11e5-9507-ff6ce301ea7a.png">
