### ISSUE TITLE
Jobs table is pilling up a lot of "OC\Command\CommandJob" jobs

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#20425]
```
SELECT class, COUNT(*) FROM oc_jobs GROUP BY class;
+-----------------------------------------------+----------+
| class                                         | COUNT(*) |
+-----------------------------------------------+----------+
| OCA\Activity\BackgroundJob\EmailNotification  |        2 |
| OCA\Activity\BackgroundJob\ExpireActivities   |        5 |
| OCA\Files_sharing\Lib\DeleteOrphanedSharesJob |        1 |
| OCA\user_ldap\lib\Jobs                        |        1 |
| OC\Command\CommandJob                         |  2198563 |
| \OCA\User_LDAP\Jobs\CleanUp                   |        1 |
+-----------------------------------------------+----------+
6 rows in set (0.47 sec)
```

Now the cron job is running endless.

Those command jobs are mostly trash bin and version expiries. I guess we need a way to parallelize those CommandJobs and trigger them separately. Otherwise big instances will have a huge problem of endless running cron.php calls and the actual cron behavior is killed.

This is on a 8.1.3 instance.

@cmonteroluque @karlitschek I rated this as a sev2-high ticket and put it in the current milestone. (feel free to change this)

@icewind1991 @PVince81 @nickvergessen @schiesbn I would really like to have your opinion on this. I think the CommandJobs can easily parallelized, because they are independent (or should be).

**Comment by MorrisJobke** [comment]
00004146

cc @michaelstingl @cdamken

**Comment by cmonteroluque** [comment]
@MorrisJobke can this wait for 9.0?

**Comment by MorrisJobke** [comment]
> @MorrisJobke can this wait for 9.0?

Nothing for 8.2.1 I think, but we should have this is mind and hopefully should also have this backported if possible.

**Comment by nickvergessen** [comment]
I think there was a problem with them, meaning that they are not executed at all

**Comment by nickvergessen** [comment]
And I also guess that https://github.com/owncloud/core/blob/master/cron.php#L132-L134 will take forever, if we create 2mio objects

**Comment by MorrisJobke** [comment]
The jobs are actually executed but there are more jobs coming in that the machine can sequentially process.

**Comment by DeepDiver1975** [comment]
> And I also guess that https://github.com/owncloud/core/blob/master/cron.php#L132-L134 will take forever, if we create 2mio objects

indeed - an more iterative  apporach is required.

In addition I think it would make sense to have an explicit job execution command for occ.
This way we can parallelize execution as well (assuming there is some lock mechanism in the db :see_no_evil: )

**Comment by rullzer** [comment]
So they should be able to run in parallel. 
But... most of those jobs should be almost instant. @MorrisJobke could you get a log using https://github.com/owncloud/core/blob/master/cron.php#L135-L137 how long some of the jobs actually run? Because I suspect a deeper issue.

**Comment by MorrisJobke** [comment]
@rullzer I will ask ;)

**Comment by Helios07** [comment]
Here are some example lines:
{"reqId":"dOCZJ7fjm0ChM8UQMF8I","remoteAddr":"","app":"cron","message":"Run job with ID 683949","level":0,"time":"2015-11-10T15:46:27+01:00"}
{"reqId":"dOCZJ7fjm0ChM8UQMF8I","remoteAddr":"","app":"cron","message":"Finished job with ID 683949","level":0,"time":"2015-11-10T15:46:32+01:00"}
{"reqId":"dOCZJ7fjm0ChM8UQMF8I","remoteAddr":"","app":"cron","message":"Run job with ID 683953","level":0,"time":"2015-11-10T15:46:32+01:00"}
{"reqId":"dOCZJ7fjm0ChM8UQMF8I","remoteAddr":"","app":"cron","message":"Finished job with ID 683953","level":0,"time":"2015-11-10T15:46:36+01:00"}
{"reqId":"dOCZJ7fjm0ChM8UQMF8I","remoteAddr":"","app":"cron","message":"Run job with ID 683957","level":0,"time":"2015-11-10T15:46:36+01:00"}
{"reqId":"dOCZJ7fjm0ChM8UQMF8I","remoteAddr":"","app":"cron","message":"Finished job with ID 683957","level":0,"time":"2015-11-10T15:46:42+01:00"}
{"reqId":"dOCZJ7fjm0ChM8UQMF8I","remoteAddr":"","app":"cron","message":"Run job with ID 683961","level":0,"time":"2015-11-10T15:46:42+01:00"}
{"reqId":"dOCZJ7fjm0ChM8UQMF8I","remoteAddr":"","app":"cron","message":"Finished job with ID 683961","level":0,"time":"2015-11-10T15:46:46+01:00"}
{"reqId":"dOCZJ7fjm0ChM8UQMF8I","remoteAddr":"","app":"cron","message":"Run job with ID 683965","level":0,"time":"2015-11-10T15:46:46+01:00"}
{"reqId":"dOCZJ7fjm0ChM8UQMF8I","remoteAddr":"","app":"cron","message":"Finished job with ID 683965","level":0,"time":"2015-11-10T15:46:52+01:00"}
{"reqId":"dOCZJ7fjm0ChM8UQMF8I","remoteAddr":"","app":"cron","message":"Run job with ID 683969","level":0,"time":"2015-11-10T15:46:52+01:00"}
{"reqId":"dOCZJ7fjm0ChM8UQMF8I","remoteAddr":"","app":"cron","message":"Finished job with ID 683969","level":0,"time":"2015-11-10T15:46:57+01:00"}
{"reqId":"dOCZJ7fjm0ChM8UQMF8I","remoteAddr":"","app":"cron","message":"Run job with ID 683973","level":0,"time":"2015-11-10T15:46:57+01:00"}
{"reqId":"dOCZJ7fjm0ChM8UQMF8I","remoteAddr":"","app":"cron","message":"Finished job with ID 683973","level":0,"time":"2015-11-10T15:47:02+01:00"}
{"reqId":"dOCZJ7fjm0ChM8UQMF8I","remoteAddr":"","app":"cron","message":"Run job with ID 683977","level":0,"time":"2015-11-10T15:47:02+01:00"}
{"reqId":"dOCZJ7fjm0ChM8UQMF8I","remoteAddr":"","app":"cron","message":"Finished job with ID 683977","level":0,"time":"2015-11-10T15:47:07+01:00"}
{"reqId":"dOCZJ7fjm0ChM8UQMF8I","remoteAddr":"","app":"cron","message":"Run job with ID 683981","level":0,"time":"2015-11-10T15:47:07+01:00"}
{"reqId":"dOCZJ7fjm0ChM8UQMF8I","remoteAddr":"","app":"cron","message":"Finished job with ID 683981","level":0,"time":"2015-11-10T15:47:12+01:00"}
{"reqId":"dOCZJ7fjm0ChM8UQMF8I","remoteAddr":"","app":"cron","message":"Run job with ID 683985","level":0,"time":"2015-11-10T15:47:12+01:00"}
{"reqId":"dOCZJ7fjm0ChM8UQMF8I","remoteAddr":"","app":"cron","message":"Finished job with ID 683985","level":0,"time":"2015-11-10T15:47:17+01:00"}
{"reqId":"dOCZJ7fjm0ChM8UQMF8I","remoteAddr":"","app":"cron","message":"Run job with ID 683989","level":0,"time":"2015-11-10T15:47:17+01:00"}
{"reqId":"dOCZJ7fjm0ChM8UQMF8I","remoteAddr":"","app":"cron","message":"Finished job with ID 683989","level":0,"time":"2015-11-10T15:47:22+01:00"}
{"reqId":"dOCZJ7fjm0ChM8UQMF8I","remoteAddr":"","app":"cron","message":"Run job with ID 683993","level":0,"time":"2015-11-10T15:47:22+01:00"}

The cronjob is running at the moment, but jobs are still created a bit faster, so oc_jobs is increasing.

You can ask me directly for more data if you need them. I am responsible for the ownCloud installation.

**Comment by MorrisJobke** [comment]
> But... most of those jobs should be almost instant.

@rullzer Each job runs roughly 4 seconds ... that's not really "instant". Is this expected?

**Comment by Helios07** [comment]
Just FYI to get an impression, why that database is not incredibly fast:

MariaDB [rwth_aachen]> select count(*) from oc_filecache;
+----------+
| count(*) |
+----------+
| 21225449 |
+----------+
1 row in set (2.53 sec)

**Comment by rullzer** [comment]
@Helios07 @MorrisJobke I don't know about all te jobs. it is just that locally here it all is almost instant. That is why is syspect something is not exactly as it should be...

**Comment by Helios07** [comment]
Some of the jobs delete trash folders for example. I had a look at one process while doing so and could see the files vanishing. I had to wait for more than a minute until a folder with 1000 entries was emptied. The servers are under quite some load so everything tooks a bit longer than on a test system.

**Comment by rullzer** [comment]
Jikes that is indeed quite some load. But then would running in parallel really solve the issue? As expiring the trashbin and version are mainly I/O jobs. Probably if you have 2 jobs in parallel they would just take each about twice as long?

**Comment by MorrisJobke** [comment]
> Jikes that is indeed quite some load. But then would running in parallel really solve the issue? As expiring the trashbin and version are mainly I/O jobs. Probably if you have 2 jobs in parallel they would just take each about twice as long?

Are they all are really about deleting actually stuff? Ah right ... they set as last run in the future (i.e. in 30 days for a 30 day expiry of a trashed file) and then run once the date is passed. Or am I wrong? But why does the cron run then take so long? @Helios07 Any chance to count how many jobs are executed for one cron.php call? Maybe check the start and end time and then grep the logs?

**Comment by Helios07** [comment]
@rullzer Since we have a quite fast parallel filesystem here (GPFS) I would doubt that. But you are maybe right regarding the database, which I assume to be the bottleneck here. 
@MorrisJobke As many as you want since oc_jobs is filling faster than cron.php is processing the jobs. Or did I get your question wrong?

**Comment by MorrisJobke** [comment]
> @MorrisJobke As many as you want since oc_jobs is filling faster than cron.php is processing the jobs. Or did I get your question wrong?

But why are filled that much? Usually there should be an entry for each delete and each update, but they should also executed over the same time as they are incoming ... something is wrong here. I guess the execution is triggered to early.

@schiesbn Any ideas? What was the idea behind those jobs?

**Comment by Helios07** [comment]
The cron.php did not run in fact for some time, so the jobs could fill up to this point. I cannot tell exactly why it made problems initially, but I think the reason was that it did not finish anymore and so my colleague stopped it completely. And now I have to get rid of all those jobs...

**Comment by rullzer** [comment]
Aaaah that would explain a lot. Since if the versioing has not run for some time it will notice that just cleaning up versioins for this file is not the solution. So it will start iterating over all files for that user to cleanup stuff.

And the trashbin most likely then has a lot of stuff to clean.

So currently you are probabaly still doing a lot of stuff from "old" entries. Which take a long time since they want to expire a lot of stuff.. What I would suspect here is that over night the number of entries significantly drops. And during the day it slowly grows. So over the course of 24H does the table still grow or shrink? And I expect that the furter you get in the list the faster stuff will go.

**Comment by Helios07** [comment]
I will have a look at it and inform you, if I see a tendency.

**Comment by MorrisJobke** [comment]
I just had a call with @Helios07 and we checked the performance impact of the cron execution:

* in tables that contain a lot of those cron job entries the execution time is quite big (1 job entry was removed every ~5-10 seconds)
* `ls -l` took long on the file system - ~5-10 seconds - that is quite common for distributed file systems -> I think that this is the major cause for the long execution time of a cron job -> parallelization would help here because it's not really an IO issue but a latency issue of the filesystem

@icewind1991 What happens if the cron.php is called on multiple servers? The locking of the cron.php is only working on one machine.

What about a separate cron executable that work iterative on parallelizable entries. It could delete the entries from the DB and then works on them. Or we make the general cron.php execution safe for parallel execution by mark the entries that are worked on in the DB.

@PVince81 @DeepDiver1975 @karlitschek Does this makes sense?

**Comment by rullzer** [comment]
Just a word of warning. If you wannt to run this stuff in parallel we need to make absolutely certain that the jobs can be executed independently. Else large installations will at some point run into weird race condictions which are very very hard (if not impossible) to debug.

I'm all in favor of doing this but it will require carefully analyzing all of the Commandjobs.

**Comment by MorrisJobke** [comment]
> I'm all in favor of doing this but it will require carefully analyzing all of the Commandjobs.

Yep. In a first step I would only parallelize versions and trash bin expiry.

**Comment by icewind1991** [comment]
`CommandJob` background jobs should be fine to paralize, I can look into creating a cli endpoint that executes a single `CommandJob`, then the admin can decide to call that cli scrip in paralel

**Comment by MorrisJobke** [comment]
> CommandJob background jobs should be fine to paralize, I can look into creating a cli endpoint that executes a single CommandJob, then the admin can decide to call that cli scrip in paralel

That would be really nice :)

**Comment by MorrisJobke** [comment]
@icewind1991 Did you already start with this?

**Comment by Touchwoody** [comment]
I want to stress that only https://github.com/owncloud/core/blob/master/apps/files_trashbin/command/expire.php jobs are slow. I assume all other jobs run fast enough. 

A few days ago oc_jobs tables started to grow in another one of our owncloud instances. I was able to monitor closely what happened. In the beginning two users created ~3000 jobs like these:

- - - - -
 | 9801921 | OC\Command\CommandJob                         | "O:33:\"OCA\\Files_Trashbin\\Command\\Expire\":2:{s:39:\"\u0000OCA\\Files_Trashbin\\Command\\Expire\u0000user\";s:24:\"someuser@example.com\";s:47:\"\u0000OCA\\Files_Trashbin\\Command\\Expire\u0000trashBinSize\";i:7314513088;}"                                                                                                                                                                                                       |          0 |
| 9801925 | OC\Command\CommandJob                         | "O:33:\"OCA\\Files_Trashbin\\Command\\Expire\":2:{s:39:\"\u0000OCA\\Files_Trashbin\\Command\\Expire\u0000user\";s:24:\"someuser@example.com\";s:47:\"\u0000OCA\\Files_Trashbin\\Command\\Expire\u0000trashBinSize\";i:7314632189;}"                                                                                                                                                                                                       |          0 |
| 9801929 | OC\Command\CommandJob                         | "O:33:\"OCA\\Files_Trashbin\\Command\\Expire\":2:{s:39:\"\u0000OCA\\Files_Trashbin\\Command\\Expire\u0000user\";s:24:\"someuser@example.com\";s:47:\"\u0000OCA\\Files_Trashbin\\Command\\Expire\u0000trashBinSize\";i:7314513254;}"  
- - - - -

Only these slow down cron.php. It took about half a day to run these jobs and in that time oc_jobs table size grew to about ~30k. After those trashbin expire jobs were done, table size started to drop sharply  ... until another user dumped ~50.000 new trashbin expire jobs. cron.php is working on these since then, but will now only finish ~4.000 per day. Table size is now ~145k and still growing.

I suggest two solutions here:
- Why is apps/files_trashbin/command/expire.php so slow?
  - it does some Util-FS stuff. Is this necessary with cron.php?
  - is it possible to fasten Trashbin::expire($this->trashBinSize, $this->user); ?
- Why are there so many similar jobs anyway?
  - I don't know under which condition a user is able to create 50k jobs? rm on a webdav mount?
  - is it really necessary to run all of them? Basically https://github.com/owncloud/core/blob/master/apps/files_trashbin/lib/trashbin.php#L641-L655 is run. 
    - are there ways to merge them? Maybe "check if a similar job in oc_jobs exist and replace it"?
    - are there ways to prevent them? Maybe don't create a job everytime a file change happens in the trashbin dir, but wait a bit to let any rm/mv cmd finish?

**Comment by PVince81** [comment]
Similar jobs (or same duplicate jobs) is a problem yes, see https://github.com/owncloud/core/issues/16826

Util-FS stuff might be needed to make sure hooks get triggered properly when files get expired. For example the thumbnails subsystem will listen to file deletion to also delete the matching thumbnails.
It might still be worth having a deeper look if it can be made faster.

**Comment by PVince81** [comment]
I'll tag this as trashbin for now. @schiesbn

**Comment by MorrisJobke** [comment]
I raised the sev because the jobs table is filling faster than it can be proceed. I will try to find a solution for the parallel execution of the expiry jobs today. This should work in the short time. For the long term solution we should definitely look into #16826

**Comment by rullzer** [comment]
Probabaly a "somewhat" doable solution would be to drop the $trashBinSize. And calculate that during the job.

That way the jobs are actually identical and can properly be detected as such.

**Comment by PVince81** [comment]
@MorrisJobke suggested to have the expire job itself check for other instances of itself and then clean them up. It might be tricky as there are no proper columns for this info except for the serialized blob. Might still be possible to find these entries (hacky) with a LIKE statement...

**Comment by MorrisJobke** [comment]
> Probabaly a "somewhat" doable solution would be to drop the $trashBinSize. And calculate that during the job.
> 
> That way the jobs are actually identical and can properly be detected as such.

Yep. I also discussed this with @PVince81 ;)

**Comment by rullzer** [comment]
> @MorrisJobke suggested to have the expire job itself check for other instances of itself and then clean them up. It might be tricky as there are no proper columns for this info except for the serialized blob. Might still be possible to find these entries (hacky) with a LIKE statement...

that sounds like a good to lose all your sanity

**Comment by Touchwoody** [comment]
@PVince81 @MorrisJobke nice suggestion. 
Side note: for that the expire job still needs to recalculate $trashBinSize itself, as it might me called with the wrong (not last entry in oc_jobs) value.

**Comment by nickvergessen** [comment]
> @MorrisJobke suggested to have the expire job itself check for other instances of itself and then clean them up. It might be tricky as there are no proper columns for this info except for the serialized blob. Might still be possible to find these entries (hacky) with a LIKE statement...

That will not work for CLI, because we already grabbed all the entries and so they will still be executed and re-add the sub calls

**Comment by Touchwoody** [comment]
Which leads me to the following idea:
If cron.php is gnawing away on that very large bone anyway, will it be feasible to reduce the bone, err, table size in the background?

As every run of the trashbin expire job does just the same: am I right, that basically it is only necessary to run _one_ (namely the last entry in oc_jobs) expire job, to get everything aligned?

If so, won't this be a workaround to clean up an overflowing oc_jobs table:
- have a script that searches for multiple trashbin expire jobs per user in the oc_jobs table
- have the script delete every job entry except the last one
- stop cron.php and wait for it to relaunch

Or will this create inconsistencies?

**Comment by MorrisJobke** [comment]
> Or will this create inconsistencies?

I work on something like this. The only problem I see is, that it is difficult to determine the right point in time where to delete the other entries. Best is right after the start of the corresponding expiry task. Let me see if this is easily possible.

**Comment by MorrisJobke** [comment]
I will now do following steps:

* try to get somehow rid of the trashbin size in the arguments list (to make it easier to find same jobs - not  100% necessary but would make our life easier)
* ~~then on start of the execution of an trash bin expiry job I will delete all following jobs from the jobs table that are queried for the same user~~
   * ~~this needs to be done right before the execution because otherwise there could be a race condition where it looks like a expiry job execution is pending but is actually nearly finished and won't run properly~~
   * ~~scenario: start the (long running) expiry job, now a new expiry job should be added to the job list (current expiry job is still running), started expiry job finishes and deletes the entry from the job list -> at the point of adding the job the running job has maybe already processed that much, that it didn't take the newly trashed stuff into account and a new expiry job should run~~
* I just checked the implementation: the job is removed first and then executed - so only adding it if the job is not present is fine.

**Comment by MorrisJobke** [comment]
> I just checked the implementation: the job is removed first and then executed - so only adding it if the job is not present is fine.

https://github.com/owncloud/core/blob/fbba7a61cb00229128c722cef8d0248b04d00299/lib/private/backgroundjob/queuedjob.php#L41-L42

**Comment by rullzer** [comment]
@MorrisJobke  Sounds like a solid approach!

@Touchwoody when the patch from @MorrisJobke is done. To my understanding it will then add 1 final job (without the trashBinSize). All further additions will get deduplicated against that. Then the number of new jobs should be reduced significantly. Thus the server can finally catch up.

Your workaround sounds like it *should* work. But testing it is not so trivial...

**Comment by MorrisJobke** [comment]
> @Touchwoody when the patch from @MorrisJobke is done. To my understanding it will then add 1 final job (without the trashBinSize). All further additions will get deduplicated against that. Then the number of new jobs should be reduced significantly. Thus the server can finally catch up.

Yep. That's the plan. I already have a version without trash bin size locally ;)

**Comment by MorrisJobke** [comment]
And here it is: https://github.com/owncloud/core/pull/20790

**Comment by MorrisJobke** [comment]
I just received an update on this: The trashbin is not the only problem: version expire has a similar problem: https://github.com/owncloud/core/issues/21108

**Comment by fossxplorer** [comment]
Reported a while back by me https://github.com/owncloud/core/issues/20349
