### ISSUE TITLE
[Theming] Changing color of logos in header don't work

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#20433]
### Steps to reproduce
1.  `cp /var/www/owncloud/core/img/actions/caret-dark.svg /var/www/owncloud/themes/theme_name/core/img/actions/caret.svg` same goes for .png

### Expected behaviour
Icon should be dark

### Actual result
Icon is still white

### System 
Ubuntu Server 14.04
ownCloud Server 8.2
PHP 5.5.9

**Comment by MorrisJobke** [comment]
Just to be sure:

You added `"theme" => "theme_name"` to your config.php?

**Comment by enoch85** [comment]
@MorrisJobke Yes

**Comment by MorrisJobke** [comment]
You also need to overwrite the icon class in `core/css/icons.css` in your theme:

```
.icon-caret {
	background-image: url("../img/actions/caret-dark.svg");
}
```

Then it replaces the icon correctly.

**Comment by MorrisJobke** [comment]
Please reopen if this doesn't fix your issues.

**Comment by enoch85** [comment]
@MorrisJobke That solved it. Thanks! 

Tried to do the same for search.svg, but that didn't work. Any suggestions?

### Steps to reproduce
1. wget the search.svg from github
2. change the permissions
3. change icons.css
