### ISSUE TITLE
Sidebar closes after returning from picture detail view

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#20437]
1. Open the sidebar on some file
2. Click on any image to open the picture detail view
3. Exit the detail view again

Expected: Everything is back to how it was before, with the sidebar open as before.

Actually, the file list refreshes and you don’t know which sidebar was open anymore.

@PVince81 @oparoz

**Comment by MorrisJobke** [comment]
I guess this is because of the IE8 workaround to refresh the whole page. @oparoz

**Comment by oparoz** [comment]
Correct. 
Now that @PVince81 has implemented a workaround, it should be possible to avoid that refresh.

**Comment by MorrisJobke** [comment]
Okay. So it's more a gallery app issue, right? Can we move this ticket over? Thanks :)

**Comment by oparoz** [comment]
It's already there: https://github.com/owncloud/gallery/issues/313
