### ISSUE TITLE
Misleading "stable" version on admin-page

### ISSUE THREAD

**Issue by tflidd** [owncloud/core#20430]
## Steps to reproduce
1. Install OC 6.0.5 (or OC 7.0.5)
2. Go to admin page
## Expected result

for 6.0.5: your product is EOL (7.0.5: You are not using the latest release)
## Actual result

![bildschirmfoto vom 2015-11-10 11 20 36](https://cloud.githubusercontent.com/assets/8111200/11059922/19d68ec0-879d-11e5-973a-d698880596a0.png)

This is completely misleading for users, they think to run a "stable" version (=everything is ok) even though they use a version with known security issues and even without support.

**Comment by RealRancor** [comment]
:+1: , that makes really sense.

I think it can't be added to such outdated versions but it might make sense to add it to the still supported (and updated) versions like 8.0+ via an update.

**Comment by MorrisJobke** [comment]
A rough plan for EOL date can be found here https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule

**Comment by RealRancor** [comment]
Yes, but from what i know this is not really linked somewhere at owncloud.org or the documentation. It will also not get noticed / read by most of the people out there.

**Comment by PVince81** [comment]
@cmonteroluque @karlitschek

**Comment by karlitschek** [comment]
the updater app should show that a new version is available. The fact that this is 6.0.5 and it is a stable release and not a beta, RC or daily build is also correct.

Stable doesn't imply up to date.
If an ownCloud is up to date can be seen with the updater app or with the notification that we have in newer versions.

**Comment by tflidd** [comment]
I would opt for only putting beta, RC, and daily-tags. Stable just doesn't provide any useful information and only confuses people. Or put stable-branch instead.

Not everyone is using the updater app. And people using older versions (e.g. 6.0.x, 7.0.x) can only be discouraged to follow through all updates via updater app.

**Comment by PVince81** [comment]
or "stable channel" ?

**Comment by karlitschek** [comment]
Yes. I think we should remove it when we are at stable. i though we did it but it still should in 8.2

**Comment by PVince81** [comment]
Reopening. Pull request welcome.

**Comment by PVince81** [comment]
To be able to inject a EOL string, the admin page would need to be connected to the internet and be able to download this information. Would not work with offline instances.

The only thing we can do is hard-code the EOL string for the last major version of a release. But then if people are on the previous version they'd still see stable.
