### ISSUE TITLE
Shared folders not showing when a user is part of two groups, one group being a subdirectory of the other group

### ISSUE THREAD

**Issue by rugebiker** [owncloud/core#20449]
Shared folders not showing when a user is part of two groups, one group being a subdirectory of the other group

Steps to reproduce
--------------------------
I have a main user (user1) that is the main account for my owncloud. There are other users in the system (user2, user3, etc). User2 is in two groups (group1 and group2). Under user1 there is the following directory structure:

root
-directory1 (shared to group1)
---subdirectory1 (shared to group2)
---subdirectory2 (shared to group3)

Expected behaviour
-----------------------------

user1 should be able to see directory1 plus all the subdirectories.

Actual behaviour
------------------------ 

When user1 clicks on directory1, it goes straight to subdirectory1, so he is not able to see the other subdirectories.

Server configuration
------------------------

ownCloud version: 8.1.3 stable

Hope I explained myself :)

**Comment by karlitschek** [comment]
@schiesbn @rullzer

**Comment by MorrisJobke** [comment]
Can I ask you to show your table `oc_share` with the entries for the directory and the subdirectory.

```
SELECT * FROM oc_share WHERE file_source IN (SELECT fileid FROM oc_filecache WHERE name IN ("directory", "subdirectory")) OR parent IN (SELECT id FROM oc_share WHERE file_source IN (SELECT fileid FROM oc_filecache WHERE name IN ("directory", "subdirectory")) );
```

Simply replace `directory` with the name of the directory and `subdirectory` with the name of the subdirectory.

For me this looks in your scenario like this (and works just nicely):

<img width="1142" alt="bildschirmfoto 2015-11-11 um 09 00 18" src="https://cloud.githubusercontent.com/assets/245432/11086568/ab1e0f60-8852-11e5-811d-4a21fd852ce8.png">

**Comment by rugebiker** [comment]
Here is the image of that command:

![Image of Yaktocat](http://ibin.co/2MCjIeYZ3iR3)

The directory structure is:

root
-Committees (Shared with board)
---IT (Shared with IT)
---Bikes (Shared with Bikes)

As an example, diewit is member of both board and Bikes groups. But when he clicks on committees, it gets directly inside the contents of IT, without going first to the contents of Committees (IT, Bikes).

**Comment by MorrisJobke** [comment]
That looks like it was renamed. The last three entire (74, 75,76) are marked to me named `Committees`on the receiving side (and not `Bikes`) like the original folder name. @PVince81 @schiesbn How could something like this happen? One way would be to rename this as recipient and one way would be the naming collision detection (but that code usually appends a `(2)` or `(3)`). Any other ideas?

The weird thing is also that the share 62 also targets to `Committees` which in the end would collide with 74.

**Comment by rugebiker** [comment]
Nobody of the users renamed the folders, as I still control those users. =/

**Comment by PVince81** [comment]
When receiving  a share from several groups, I believe that there is logic that tries to combine them into a single mount point. Not sure what happens if the recipient renames that mount point. @schiesbn

**Comment by PVince81** [comment]
Feel free to reopen if the problem persists with 9.0.5 or 9.1.1. Some important issues were fixed related to receiving multiple shares.
