### ISSUE TITLE
v8.2: Remember login checkbox cannot be checked with keyboard

### ISSUE THREAD

**Issue by Fmstrat** [owncloud/core#20448]
I have filled out all of the template elements that should apply. I'm 99% sure this is a CSS issue, and unrelated to the backend in any way.

### Steps to reproduce
1. Visit login screen
2. Type username, hit tab
3. Type password, hit tab
4. Hit tab repeatedly attempting to get to the "remember" checkbox

### Expected behaviour
Tabbing should eventually take you to the "remember" checkbox

### Actual behaviour
You never reach the checkbox, and thus, can not login with the remember flag without the use of a mouse or pointer.

### Server configuration
**ownCloud version:** 8.2

### Client configuration
**Browser:** Latest versions of Firefox and Chrome

**Operating system:** Windows 8.1

**Comment by karlitschek** [comment]
@jancborchardt

**Comment by MorrisJobke** [comment]
cc @Henni

**Comment by Henni** [comment]
Will be fixed by #20148

**Comment by MorrisJobke** [comment]
Duplicate of #19898

**Comment by Fmstrat** [comment]
Ahh, sorry about that. My search had "remember" in it, which kept 19898 from popping up.
