### ISSUE TITLE
[IE 8] Ugly elements in the files view.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#20445]
### Steps to reproduce

1. Using internet explorer 8 go to the files view.

### Expected behaviour
See elements correctly.

### Actual behaviour
![screen shot 2015-11-10 at 17 16 16](https://cloud.githubusercontent.com/assets/9048796/11068079/0573b63c-87d0-11e5-9802-7f9a140812d3.png)

See the white box in the upper left and the sliced '+' button.

**ownCloud version:** 8.2.1 RC1

Happening also in master branch.

cc @jancborchardt

**Comment by jancborchardt** [comment]
@SergioBertolinSG btw, you can mention @owncloud/designers as well, not only me.

@SergioBertolinSG what is that white element on the top left? Has that been there in prior versions? Can you right click and inspect it to see what it is?

**Comment by SergioBertolinSG** [comment]
@jancborchardt Ok.
It is the search field, it is totally moved to the left. And the magnifier has dissapeared.
In previous versions that didn't happen.

**Comment by PVince81** [comment]
Works for me in 8.2.1RC3 (from git, no apps) with IE8 on XP
![ie8-clean](https://cloud.githubusercontent.com/assets/277525/11180512/8bdaadc2-8c5b-11e5-9398-136759bb375b.png)

Maybe any additional apps that mess up with the styles ?

**Comment by SergioBertolinSG** [comment]
![screen shot 2015-11-16 at 12 52 26](https://cloud.githubusercontent.com/assets/9048796/11181240/f54f7ce2-8c60-11e5-8dfd-feda441de812.png)

Just retested with 8.2.1rc3 enterprise tarball.

```
Enabled:
  - activity: 2.1.3
  - admin_audit: 0.6
  - enterprise_key: 0.1.0
  - files: 1.2.0
  - files_locking: 
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_sharing_log: 0.5
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firewall: 2.2.0
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - updater: 0.6
  - user_ldap: 0.7.0
  - windows_network_drive: 0.1.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_drop
  - files_external
  - files_ldap_home
  - objectstore
  - password_policy
  - sharepoint
  - user_external
  - user_shibboleth
```

**Comment by PVince81** [comment]
@cmonteroluque setting this to 8.2.2 as it's too late for 8.2.1.

**Comment by PVince81** [comment]
Maybe a problem with the enterprise theme.
Let me try this locally.

**Comment by jancborchardt** [comment]
@SergioBertolinSG you don’t have compatibility mode enabled or something like that, right? Cause that’s not supported.

**Comment by PVince81** [comment]
Strange, with the enterprise version I do see the enterprise theme in the login page, but the files page looks like non-ee:
![ie8-ee](https://cloud.githubusercontent.com/assets/277525/11182009/aac7f0f8-8c67-11e5-83cd-e6ea8a631bbb.png)

I downloaded the enterprise complete tarball for 8.2.1RC3 and set it up as is.

**Comment by PVince81** [comment]
and that's only in IE8. On Chromium it properly shows the enterprise theme.

**Comment by PVince81** [comment]
weeeeeeird, in IE8 when I switch to the personal page it switched to EE mode but on the files app it's CE theme.

**Comment by SergioBertolinSG** [comment]
@jancborchardt I saw that with edge working as ie8, it seems it is working in compability mode.

Using ie8 in another machine it works fine.

**Comment by jancborchardt** [comment]
@PVince81 that’s gotta be some caching-related issue … superstrange.
