### ISSUE TITLE
Empty textfields in login screen (IE10 & IE11)

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#20444]
### Steps to reproduce

1. Using internet explorer 10 or 11 go to the login screen.

### Expected behaviour
Username and Password are written in the textfields.

### Actual behaviour
![screen shot 2015-11-10 at 17 14 06](https://cloud.githubusercontent.com/assets/9048796/11067966/7020647c-87cf-11e5-98bc-08e8f5c1dcff.png)

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.2.1.0","versionstring":"8.2.1 RC1","edition":"Enterprise"}

Happening also in master branch.

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in community edition.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Server logs**
```

```

cc @jancborchardt

**Comment by PVince81** [comment]
It's not empty, it's the placeholder. In IE the placeholder disappears on focus.
It's IE's standard behavior for placeholders, not a bug.

**Comment by SergioBertolinSG** [comment]
Well it behaves differently in Edge and previous versions. There the text inside fields is shown.
