### ISSUE TITLE
[8.2] Updater not working

### ISSUE THREAD

**Issue by kriztan** [owncloud/core#20459]
Some days ago, I've upgraded from OC 8.1 to OC 8.2 like it is described in the docs. After Upgrading everything is working, except the updater. In the admin settings the updater shows:
![image](https://cloud.githubusercontent.com/assets/3350754/11094157/6b5a5f28-888e-11e5-9844-b73f61e685d6.png)

I've looked into the database and searched for the key `lastupdateResult`, the value is `{"version":{},"versionstring":{},"url":{},"web":{}}`

Do you have any ideas what's wrong? How can I get the updater working?

Thanks a lot.

**Comment by MorrisJobke** [comment]
Please reopen this in the updater bug tracker https://github.com/owncloud/updater/issues

**Comment by MorrisJobke** [comment]
Thanks :)

**Comment by RealRancor** [comment]
Already there: https://github.com/owncloud/updater/issues/184
