### ISSUE TITLE
Full name is not shown just after modifying it in the Personal Page

### ISSUE THREAD

**Issue by davitol** [owncloud/core#20455]
### Steps to reproduce

1. Go to personal settings
2. Change the full name
3. Click away in order to save it

### Expected behaviour

The full name should be updated in the up-right corner of the page

### Actual behaviour

No Name is shown in the up-right corner of the page

Note: The new Full name is visible after refreshing the screen.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 8.2.1. (RC2)

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

![screen shot 2015-11-11 at 13 56 52](https://cloud.githubusercontent.com/assets/10596560/11091579/390ed736-887c-11e5-8f91-b2906390a105.png)

**Comment by MorrisJobke** [comment]
Bisected: 83c177fc1b010aba12382a8ac66df9f9b7142b75

**Comment by MorrisJobke** [comment]
Fix is in #20458

**Comment by PVince81** [comment]
Sev low, moving to 9.0

**Comment by MorrisJobke** [comment]
Fix is in https://github.com/owncloud/core/pull/23370
