### ISSUE TITLE
owncloudcmd: error while loading shared libraries: libQtWebKit.so.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Superkikim** [owncloud/core#20452]
Step to reproduce:

Install CentOS 7 Core from scratch. Install owncloud repository. Install owncloud-client package. Run owncloudcmd or owncloud

Result:
owncloudcmd: error while loading shared libraries: libQtWebKit.so.4: cannot open shared object file: No such file or directory

Error during installation:

    Downloading packages:
    opt-libQtWebKit4-2.2.3-28.1.x86_64.rpm                     |  13 MB   00:05     
    Running transaction check
    Running transaction test
    Transaction test succeeded
    Running transaction
      Installation : opt-libQtWebKit4-2.2.3-28.1.x86_64                         1/1
    Error unpacking rpm package opt-libQtWebKit4-2.2.3-28.1.x86_64
    error: unpacking of archive failed on file /opt/qt-4.8/lib64: cpio: rename
      Vérification : opt-libQtWebKit4-2.2.3-28.1.x86_64                         1/1

    Failed:
      opt-libQtWebKit4.x86_64 0:2.2.3-28.1

**Comment by Xenopathic** [comment]
Please report this to the client repository, not the server. Also, it seems this was already reported (and solved): owncloud/client#2341
