### ISSUE TITLE
Updates between multiple major versions are unsupported.

### ISSUE THREAD

**Issue by elalimellamoysoyelamo** [owncloud/core#20450]
Hi,
Updating ownCloud to version 8.1.3., this may take a while.
Turned on maintenance mode
Updates between multiple major versions are unsupported.
The update was unsuccessful. Please report this issue to the ownCloud community.

my owncloud version is 4.90.11 and i'm running it on centos6
can anyone have a an advice for me.
thanks a lot.

**Comment by DeepDiver1975** [comment]
You have to first upgrade to 5 then 6, 7,8,8.1 and finally 8.2
