### ISSUE TITLE
"Very weak password" tooltip does not dissapear in personal settings page

### ISSUE THREAD

**Issue by davitol** [owncloud/core#20454]
### Steps to reproduce

1. Go to personal settings
2. Try to change your pwd with another very weak and write a wrong pwd in current password

### Expected behaviour

The "very week password" tooltip should dissapear

### Actual behaviour

The tooltip stills there after browsing away or scrolling

Note: The text file is created and it is visible after refreshing the screen.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 8.2.1. (RC2)

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox
![tooltipw](https://cloud.githubusercontent.com/assets/10596560/11091233/cecc4514-8878-11e5-8040-abd9f422ec25.gif)

**Comment by georgehrke** [comment]
I think this is something to fix upstream in https://github.com/MorrisJobke/strengthify

@MorrisJobke Do you agree?

**Comment by MorrisJobke** [comment]
I thought this was fixed some weeks ago.

**Comment by MorrisJobke** [comment]
https://github.com/owncloud/core/pull/19625

Ah right ... the password is not cleared and this is the reason it stays. Maybe we should hide the tooltip on scroll?

**Comment by MorrisJobke** [comment]
I don't think this is worth to backport it. It's a not that often used functionality and doesn't cause any big trouble.

cc @karlitschek @cmonteroluque

**Comment by karlitschek** [comment]
agreed. backport are only done for serious problems. no backport please
