### ISSUE TITLE
Could not obtain lock type 1 on ...

### ISSUE THREAD

**Issue by yonas** [owncloud/core#20468]
```
"Exception: {\"Message\":\"HTTP\\\/1.1 503 OCP\\\\Files\\\\LockNotAcquiredException: Could not obtain lock type 1 on \\\"\\\/usr\\\/local\\\/www\\\/owncloud\\\/data\\\/yonas\\\/files\\\/Photos\\\/San Francisco.jpg\\\".\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/local\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')

"Exception: {\"Message\":\"Could not obtain lock type 1 on xxx.part\\\".\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/local\\\/www\\\/owncloud\\\/apps\\\/files_locking\\\/lib\\\/lockingwrapper.php(45): OCA\\\\Files_Locking\\\\Lock->addLock(1, Resource id #325)
```

owncloud will create folders and upload partial files, but ends up with a locking error for every file it tries to upload.

The only fix I know is to disable the File Locking app. Transactional file locking with Redis also works:

https://doc.owncloud.org/server/8.1/admin_manual/configuration_files/files_locking_transactional.html

Software used:
* owncloud 8.1.3
* owncloudclient 2.0.1
* FreeBSD 10.2

**Comment by MorrisJobke** [comment]
Related: https://github.com/owncloud/files_locking/issues/39

Lets also cite @PVince81 here:

> Both locking should be able to work properly when enabled, but I'm not sure I'd recommend that.
> 
> At some point the old files_locking will be obsoleted by the transactional locking, as it fixes way more problems.


https://github.com/owncloud/core/issues/17236#issuecomment-117051770

**Comment by PVince81** [comment]
files_locking is obsolete since 8.2.

If enabling Transactional File Locking worked for you then that's all you need to do :smile:
