### ISSUE TITLE
Error while updating OwnCloud from 8.1.0 to 8.1.3

### ISSUE THREAD

**Issue by LughI0** [owncloud/core#20462]
Hello, 

Below is the text screened on the HTTP page while updating (after backup and download). 

The text is in French, the error message in english. 

"
La mise à jour de ownCloud vers la version 8.1.3 est en cours. Cela peut prendre un certain temps.

Mode de maintenance activé
Mise à jour du schéma de la base de données vérifiée
Mise à jour du schéma de la base de données pour les applications vérifiée
Base de données mise à jour
Mise à jour de « files » vers 1.1.10
Mise à jour de « activity » vers 2.0.2

Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "calendar_index" as such route does not exist.
The update was unsuccessful. Please report this issue to the ownCloud community."

It's done now ;)

The Server is based on a Bitnami Ruby Stack on Mac OS X (El Capitan).
The 8.1.0 was working as a charm, but for a connexion from the application Contacts on OS X Elcapitan : 
 : (CoreDAVHTTPStatusErrorDomain erreur 405).

This motivate me to upgrade to see if it was a solution to this (The CardDAV synchro works on iOS).

**Comment by LughI0** [comment]
... I've tried again... Just by clicking on the update button after reloading the page, and it worked at this second time...

**Comment by RealRancor** [comment]
Dup of #19145, #20125, #20207 and some more.

#19145 is still open

Really wonder why people are not finding those duplicates? Is the search engine of github that bad?

**Comment by LughI0** [comment]
Probably, as I have searched this text before posting : 
"Unable to generate a URL for the named route "calendar_index" as such route does not exist."

Result : 
We couldn’t find any code matching 'Unable to generate a URL for the named route "calendar_index" as such route does not exist.'

**Comment by RealRancor** [comment]
That brings up 24 hits if you hit the "issues" link on the left side:

![issues](https://cloud.githubusercontent.com/assets/2248459/11098264/14b6904a-88a4-11e5-926e-050e9fd24410.png)

**Comment by LughI0** [comment]
Indeed. 
I had not look at all the page, as the main frame was so explicit... Thanks for the tip. 
So the ticket should now be closed.

**Comment by wiwie** [comment]
@RealRancor Small comment to your question, why people are not finding it; I personally was lazy and just reported the problem after I had read the error message on my owncloud start page. Where it said, please go to github and report the problem. It didn't state to check for duplicates. My lazy bad. ;-)
