### ISSUE TITLE
When using the search function, pressing enter should open the first result

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#20467]
Whether it’s a folder or a file, pressing enter when performing a search should open the first result so one can quickly navigate.

cc @butonic @PVince81 @DeepDiver1975 @owncloud/designers

**Comment by PVince81** [comment]
I think we should first fix keyboard navigation and when it works, then focus on the first element.
Then, if you hit enter again it will simply trigger that element.

**Comment by prastut** [comment]
Are we going with @PVince81 strategy or as @jancborchardt commented?

Using @jancborchardt strategy right now:
**To do:**
When the keyup event is enter on searching, the first element of the file-list which is not hidden should be triggered (open):
 
Finding difficulty in going through the search.js. I found that the file-search is using this protocol for searching:
https://github.com/owncloud/core/blob/master/core/search/js/search.js#L378

Rest of the code is searching from other app and displaying them in `$(#searchresults)`. 

Please correct if I am thinking in some other direction. I can wrap this up with a little help.

**Comment by prastut** [comment]
I worked on it again and found that filesearch is connected using a plugin. Understood.  For filesearch we are using [this file](https://github.com/owncloud/core/blob/master/apps/files/js/search.js).

I have the following strategy but this is using JQuery. 

```
$("#fileList").children().filter(function(){
	return !$(this).hasClass("hidden")
}).first();
```
After getting that first element (which is not hidden), just trigger a click on that.

I think there might be a better solution to this. Let me know.

**Comment by ManZzup** [comment]
Hi
I was just going through the issue list and saw this
isn't it better if the search shows a mini-list just below the search bar when searching and then user can pick one of the shown files from that list (use arrow keys and press enter)?
sort of what you get when searching in google but with icon previews as well

**Comment by stefan-niedermann** [comment]
i think the mini list appears while typing (search as you type) and the first list item is marked as "selected" - hitting enter would just open the selected. selection could be changed using up and down arrow keys.

**Comment by ManZzup** [comment]
That sounds good
I would like to start working on this

**Comment by prastut** [comment]
@stefan-niedermann can you check [this](https://github.com/owncloud/core/issues/20467#issuecomment-191251466) & [this](https://github.com/owncloud/core/issues/20467#issuecomment-191374031) comment?

**Comment by MorrisJobke** [comment]
> @MorrisJobke , @stefan-niedermann can you check this & this comment?

@owncloud/designers :)

**Comment by MorrisJobke** [comment]
> @owncloud/designers :)

BTW: Designer also include UX design ;) Therefore I mention this team here to discuss about the behaviour

**Comment by jancborchardt** [comment]
@prastut yes on this from a design perspective:

> When the keyup event is enter on searching, the first element of the file-list which is not hidden should be triggered (open)

@ManZzup we previously had a mini-result list but abandoned it for the much more nicely integrated direct filtering of the content as it is now.

**Comment by prastut** [comment]
@jancborchardt Okay cool. 

@owncloud/javascript 
I have the following strategy:

```
$("#fileList").children().filter(function(){
	return !$(this).hasClass("hidden")
}).first();
```
After getting that first element (which is not hidden), just trigger a click on that.

This is way too hack-ish and I think there might be a better solution to this. Let me know.
