### ISSUE TITLE
Transaction Locking: Remove from EE appliance for 8.2.1

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#20466]
Is transaction locking now enabled by default in 8.2 (I think the answer is yes)?

Do we now require redis to be installed for ownCloud 8.2 to work by default (because of transaction locking)?
If so, @carlaschroder just a quick minor update to docs to say this is enabled by default and redis must be installed, perhaps needs to be linked to the installation section so that people install it by default there, instead of configuring it later.

Do we have the appliance updated to also install redis and configure the config file properly?
@jnweiger 

Thanks.

@cmonteroluque @PVince81 @DeepDiver1975 @karlitschek

**Comment by DeepDiver1975** [comment]
> Is transaction locking now enabled by default in 8.2 (I think the answer is yes)?

Yes - by default we store the locks in the DB.

Redis has to explicitly be enabled

**Comment by cburnard** [comment]
So we are expecting the customer to install and configure Redis even for a 50 user deal?  Is the benefit there for such?

Also, has any one been successful in getting Redis running as file locking and PHP cache.  I can get one or the other, but not both on 8.2.1

**Comment by MTRichards** [comment]
@cburnard No, not at all. What I think @DeepDiver1975 means is that the database is used by default, and redis needs to be enabled in the config file if you want to use that instead of the database for transaction locking.

**Comment by MTRichards** [comment]
@DeepDiver1975 Any insight into when you would switch over to a redis implementation? I am a little vague on when or where.

**Comment by cburnard** [comment]
@mtRichards.  That I understand.  What is causing the confusion is it is triggering the error message on the admin page unnecessarily.  So now a Centos 7 out of the box install is presented with the below. 

![image](https://cloud.githubusercontent.com/assets/12254958/11104252/833e65c4-8895-11e5-8c33-739f70c7ac53.png)

**Comment by MTRichards** [comment]
Ok, here we go.

CRITICAL priority, Gold ticket prior to 8.2.1 release:
- Remove transaction locking warning (or just turn off transaction locking) in the appliance
@jnweiger - please see what is needed to remove this from the appliance config file.

To discuss for later:
- Remove the redis check warning for deployments until they reach X size in storage, or users, or some proxy for determining when to do it.

**Comment by karlitschek** [comment]
correct. the db bases locking is enabled by default. redis is optional.no configuration is needed.
The warning could be removed because we did performance improvements between 8.2.0 and 8.2.1

**Comment by MTRichards** [comment]
Can we make it so? :smiley_cat: @cmonteroluque

**Comment by RealRancor** [comment]
Why remove this warning? It should be obvious that redis is faster than the db backend so why not make the users aware of this?

**Comment by PVince81** [comment]
Isn't that warning similar to the "No memory cache has been configured" that we had for a while ? The only difference is that it applies to locking. If someone configues a memcache they can also configure it for locking. Well, unless the memcache is not redis but something else, is that the issue ?

**Comment by karlitschek** [comment]
@PVince81 Yes. Exactly.

**Comment by jnweiger** [comment]
@MTRichards is this about the enterprise appliance or the community appliance?

**Comment by MTRichards** [comment]
@PVince81 yep.

I should also explain more specifically what I mean, because there are 2 appliances.
For the ownCloud Server appliance, it could stay as is, or be updated for other caches - whatever makes sense. I think users actually want to see that warning, and would try Redis (or something else) and great.
However, for the ownCloud Enterprise appliance (see owncloud.com) - in those cases this slows deployments for people checking out ownCloud, that is the one where I would like to remove the warning.

I changed the title of the issue to be clearer.

**Comment by MTRichards** [comment]
@jnweiger EE. Seems we hit submit at the same time.

**Comment by jnweiger** [comment]
I just could not wait any longer :-)

**Comment by jnweiger** [comment]
I have still to figure out how to enable that redis thing. Instructions don't hint at what packages are needed.

**Comment by MTRichards** [comment]
@bboule because I know you have configured redis and it works on SUSE, CentOS and Ubuntu

Honestly, if we can get all of those warnings resolved that would be the goal for the EE appliance. Since we control the environment, maybe we can?

However, since we know how to resolve the others, we can help customers handle them. However, every warning adds friction to the demo process which makes people uneasy and starts to impact effectiveness of the appliance. Thus the ask to resolve.

Let's start with the transaction locking one first, and then step through resolving the rest if we can.

**Comment by cburnard** [comment]
@jnweiger   I agree, the oC instructions to not go into detail about Redis, other then how to modify the config.php.

Although not SUSE here is how I get it in CentOS (from my cheat sheet)

![image](https://cloud.githubusercontent.com/assets/12254958/11120952/20b4d910-8921-11e5-9f27-ef51cc892693.png)

**Comment by jnweiger** [comment]
There is no php-redis for suse. I'll build one, to see if it works at all. https://build.opensuse.org/package/show/isv:ownCloud:devel/php-redis

**Comment by MTRichards** [comment]
Just talked to @bboule he compiled it from Github, and it worked - so I guess that is the approach.

**Comment by jnweiger** [comment]
sidenote for the community appliance: apt-get install php5-redis  (all needed dependedncies pulled)

**Comment by jnweiger** [comment]
@bboule check the updated config.sh -- this should do the trick.
https://s2.owncloud.com/package/rdiff/ee:8.2:testing/eval-appliance-oc8ee?linkrev=base&rev=8

**Comment by jnweiger** [comment]
@MTRichards the warning is gone. We now use Redis for transaction locking in eval-appliance-oc8ee. That was not exactly what you asked for, still okay?

**Comment by MTRichards** [comment]
It is ok!

**Comment by MTRichards** [comment]
(thank you)

**Comment by PVince81** [comment]
Great! Thanks for solving this :smile:

**Comment by jnweiger** [comment]
@Kawohl new appliance is ready. Let's do a round of test driving.

**Comment by jnweiger** [comment]
Umm, more rebuilds needed. autoconfig.php still overwrites my code....

**Comment by jnweiger** [comment]
... to be fixed when RC3 packages appear some time during the week end...

**Comment by jnweiger** [comment]
... one more fix to go.

**Comment by jnweiger** [comment]
done with RC4 finally.
