### ISSUE TITLE
A yellow warning should be shown when creating a user/group that already exists

### ISSUE THREAD

**Issue by davitol** [owncloud/core#20470]
### Steps to reproduce

1. Go to users page
2. Try to create a user/group that already exists

### Expected behaviour

A yellow warning should be shown

### Actual behaviour

A pop-up window appears. Besides the "background" can be clicked.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 8.2.1. (RC2)

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

![screen shot 2015-11-12 at 09 48 16](https://cloud.githubusercontent.com/assets/10596560/11114134/a763e1ee-8922-11e5-880b-6388c61d0972.png)

![screen shot 2015-11-12 at 09 48 39](https://cloud.githubusercontent.com/assets/10596560/11114138/adfd45d6-8922-11e5-8487-1061ad75b0c5.png)

**Comment by MorrisJobke** [comment]
cc @owncloud/designers

**Comment by enoch85** [comment]
What about a notification instead, using the new notifications?

**Comment by MorrisJobke** [comment]
> What about a notification instead, using the new notifications?

What are you referring to? The notification center?

**Comment by enoch85** [comment]
Yes

**Comment by MorrisJobke** [comment]
The notification center is for more persistent notifications like "you received a share" that should also be present in the client.

**Comment by enoch85** [comment]
@MorrisJobke Ah ok, then I missunderstood.

**Comment by jancborchardt** [comment]
Yeah, showing a yellow notification is a better solution than a modal.
Who can implement that @icewind1991 @PVince81? In any case this is something for 9.0, not for a maintenance release.

Ideal of course would be that directly when you type in a username that it checks for duplicates with inline validation, and you are not required to press the »Create« buton first. It could check with 500ms or 1s timeout so it’s not too much, or when the field is unfocused.

**Comment by davitol** [comment]
It happens the same behaviour in users page when setting a wrong email address creating a new user

**Comment by PVince81** [comment]
This should be as easy as replacing "OC.dialogs.alert" with "OC.Notification.showTemporary".

Tagging as junior job.

**Comment by PVince81** [comment]
So who's up to the challenge ? :wink:

**Comment by MorrisJobke** [comment]
@Henni ? :D

**Comment by Henni** [comment]
@MorrisJobke maybe early next week

**Comment by edwardcrompton** [comment]
There doesn't seem to have been any activity on this for while so I thought I'd have an attempt here
https://github.com/owncloud/core/pull/21625

I would appreciate your reviews @Henni @PVince81

**Comment by PVince81** [comment]
@edwardcrompton can you adjust your PR ? Thanks.
