### ISSUE TITLE
Update unsuccessfull

### ISSUE THREAD

**Issue by MarekK82** [owncloud/core#20479]
I just updated ownCloud 8.1.3 to 8.1.4 though the Updater App. The update process ended with the message:

```
Exception: Failed to open archive when installing app
```

And here is the screenshot:

![capture](https://cloud.githubusercontent.com/assets/486983/11119754/096ad0c2-894c-11e5-9e57-e47709f6836c.PNG)

After a browser refresh I ended back at the start update screen. So I clicked to start the update process again and this time it finished successfully. Strange...

Is there anything else I should consider?

**Comment by DeepDiver1975** [comment]
please rerun the upgrade process - the upgrade is failing because of the app archive cannot properly ba recognized - this is fixed with the next maintenance releases
