### ISSUE TITLE
Files/folders created while the users group was included in 'Exclude groups from sharing' cannot be shared even if the group is removed from the excluded groups.

### ISSUE THREAD

**Issue by davitol** [owncloud/core#20476]
### Steps to reproduce

1. Create a user that belongs to a group
2. Go to admin page
3. Set the group to be excluded from sharing
4. Login with the  user created in another browser and create a folder and a file
5. With admin user remove the users group from the list of 'excluded from sharing"

### Expected behaviour

After removing the users group from the list of 'excluded from sharing", the file/folder created WHILE the group was in the list, now should be enabled from sharing.

### Actual behaviour

The files/folders created while the users group was included in 'Exclude groups from sharing' cannot be shared even if the group is removed from the excluded groups.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 8.2.1. (RC2)

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

![screen shot 2015-11-12 at 13 16 38](https://cloud.githubusercontent.com/assets/10596560/11118111/b01664e8-893f-11e5-94e6-119c8dce8106.png)

**Comment by PVince81** [comment]
Hmmm, I suspect that the "permissions" field in the database excluded sharing at the time to folder was created.

**Comment by PVince81** [comment]
A `./occ files:scan userid` might fix that though.

**Comment by PVince81** [comment]
@icewind1991

**Comment by nickvergessen** [comment]
> Hmmm, I suspect that the "permissions" field in the database excluded sharing at the time to folder was created.

Confirmed, the file (uploaded while the group was blocked) has `11`, a new file uploaded after 5 has `27`

And indeed, a rescan fixes that. Still nasty though

**Comment by PVince81** [comment]
I think I found something: SharedStorage checks the user's sharing ability in `isSharable`. This means that the sharing permission will be permanently stored in the database: https://github.com/owncloud/core/blob/v8.2.1/apps/files_sharing/lib/sharedstorage.php#L271

We should remove it and make the check happen at a later stage when computing permissions, maybe in the view.

**Comment by PVince81** [comment]
I'll have a look at this.

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/issues/21038
