### ISSUE TITLE
Moving files with (Windows-)Client can break Synchronization and may result in dataloss

### ISSUE THREAD

**Issue by xn--nding-jua** [owncloud/core#20486]
### Steps to reproduce
1. Create a top-folder and make it a public sharing within ownCloud webinterface
2. Create a new folder within this public folder (Windows names it "Neuer Ordner")
3. Give the folder a desired name (e.g. folder1)
4. Copy some files into folder1 (in my case around 20 mp3s with each ~5 MB)
5. Create a second new folder and give it a new name (e.g. folder2)
6. Use Ctrl+X -> Ctrl+V to move the mp3s from folder1 to folder2
7. Create a third and fourth folder and rename it (e.g. folder3 and - guess it - folder4)
8. Move some files from folder2 to folder3 and some files to folder4

### Expected behaviour
When synchronization has finished all files should be stored within ownCloud like in the Windows-directory-structure.

### Actual behaviour
The Windows-Client stops working with several errors (not at the same time):
- Connection Closed
- Operation Cancelled
- Error downloading xxx: Not Found

Some description and hints for the analysis:
Error 1: During moving the files the connection interrupted (don't know the reason - internet connection is stable and fast). From one single file only the file within USER/files/folder1 had been moved to USER/files/folder2. The entry in oc_filecache was still USER/files/folder1. The encryption keys were not moved and still in USER/files_encryption/keys/files/folder1. So the client could not found the (encrypted) file anymore and stopped working. I had to move the file per ftp back to the original folder -> client worked again and everything fine for that moment.

Error 2: then the client stopped again. Looking in the ftp-folderstructure the files seemed to be intact, but in oc_filecache I had a double-entry for a file: one entry for the source-folder USER/files/folder1/file.abc and one entry for the destination-folder USER/files/folder2/file.abc (if I remember correctly the etags were the same). After deleting the defective second entry the client started synchronizing again.

Error 3: at the end the client stopped again for the last 5 files. Here it was very strange: all 5 files were missing in the ftp-server but the encryption keys were there and the database-entries in oc_filecache were present. I had to delete the oc_filecache entries and the encryption-folders. Afterwards I had to move the files out of the windows-folder-structure to let the client know, that I want to delete them. After finishing synchronization I could move them back to the cloud-folder and the synchronization-process worked fine again.

If I had no access to oc_filecache/FTP and could not delete/move the defective entries/files the synchronization would not work anymore.

Summa summarum: moving files seems to be problematic at the moment (for multiple files around 5 MB each file). Maybe it is just a timing-problem: I've renamed some folders quite fast, but this should not lead to the three errors described above.

### Server configuration
**Operating system**:
Ubuntu 14.04.2 LTS

**Web server:**
Apache (unknown version)

**Database:**
SQL 5.4

**PHP version:**
PHP 5.6

**ownCloud version:** (see ownCloud admin page)
8.1.0.8

**Updated from an older ownCloud or fresh install:**
from an older installation (8.0.2)

**List of activated apps:**
 - activity: 2.0.1
 - Default encryption module: 1.0.0
 - Deleted files: 0.6.3
 - Documents: 0.10.2
 - File Locking
 - First Run Wizard: 1.1
 - PDF Viewer: 0.7
 - Shared Files: 0.6.2
 - Text Editor: 0.4
 - updater: 0.6
 - Versions: 1.0.6
 - Video Viewer: 0.1.3
 - Calendar: 0.7.3
 - Gallery+: 14.3.0
 - Mail: 0.2.1
 - Music: 0.3.8
 - News: 6.0.6
 - Tasks: 0.8
 - Bookmarks: 0.4
 - Charts: 3.4.5
 - Contacts: 0.4.0.0
 - Extended GPX Viewer: 1.4
 - Log Reader: 1.0.0

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => 'xxxx',
  'passwordsalt' => 'xxxx',
  'trusted_domains' => 
  array (
    0 => 'www.xxxx.de',
    1 => 'cloud.xxxx.de',
    2 => 'xxxx.de',
  ),
  'datadirectory' => '/www/htdocs/xxxx/xxxx/cloud/data',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'xxxx',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxxx',
  'dbpassword' => 'xxxx',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'mail_from_address' => 'xxxx',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'xxxx.de',
  'forcessl' => true,
  'trashbin_retention_obligation' => 60,
  'trashbin_auto_expire' => true,
  'loglevel' => 2,
  'log_rotate_size' => false,
  'logtimezone' => 'Europe/Berlin',
  'check_for_working_webdav' => true,
  'check_for_working_htaccess' => true,
  'xframe_restriction' => false,
  'secret' => 'xxxx',
  'forceSSLforSubdomains' => true,
  'tempdirectory' => '/www/htdocs/xxxx/tmp',
  'enable_previews' => true,
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\Image',
    1 => 'OC\\Preview\\MP3',
    2 => 'OC\\Preview\\TXT',
    3 => 'OC\\Preview\\MarkDown',
    4 => 'OC\\Preview\\Illustrator',
    5 => 'OC\\Preview\\Postscript',
    6 => 'OC\\Preview\\Photoshop',
    7 => 'OC\\Preview\\TIFF',
  ),
  'singleuser' => false,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
ownCloud Client 2.0.2
**Browser:**
Firefox 42.0

**Operating system:**
Windows 7 64-Bit

**Comment by MorrisJobke** [comment]
@xn--nding-jua Can I ask you to open this in the client bug tracker? https://github.com/owncloud/client/issues Thanks :)

**Comment by xn--nding-jua** [comment]
@MorrisJobke Well, the last times the problem was within the ownCloud-Code. So I thought a post here is the best location. But I will open the issue at the client :)

**Comment by MorrisJobke** [comment]
Thanks ... looks much like the client. Sorry for the trouble ... but we need to do some first time triaging ;)
