### ISSUE TITLE
Abillity for admin to change avatars (and possibly other user info)

### ISSUE THREAD

**Issue by Bugsbane** [owncloud/core#20485]
Most of the users on my OC install are family members whose accounts afre created by me. I already have their photos and email addresses. It's a real pain to create their accounts though as I can do all of it from the user page except avatars. Currently, to add their avatars, for **every single user** I have to repeatedly:
1. Remember or reset the password created for them
2. Log out of the current user
3. Log in as their user
4. Go to the "Personal" menu item
5. Change their avatar
6. Repeat for the next user

and then at the end of  that log out and log back in. Really, I jujst want to be able to click on their avatar and get an add/update avatar popup that mirrors what's already in the personal page for them.

This is what I would consider was needed to close this issue. That said, for real future compatibility, even when other options get added to users "Personal" page, I would suggest that rather than trying to replicate every configuration option of the users personal page in the admin > users page, thatthe admin/users page have a "configure" link for each user, that allowed the admin to access and make modifications on the users account configuration page directly, returning to the users page on save. This way, the UX is always consistent, we avoid code duplication and any new features automatically become available to admins as well as users.

We could possibly add a "Modified by {admin user} on {date}. Reason: {admin supplied reason}" notification when the user accesses their personal page, too, although personally I would consider this optional.

**Comment by AleksBelytskyi** [comment]
Hi,

Is this feature implemented?
