### ISSUE TITLE
BIG Problem

### ISSUE THREAD

**Issue by boynickie** [owncloud/core#20495]
We've updated Owncloud to 8.2 but it appears creating user accounts etcetera is NOT working in google chrome.
Also 99% of all the apps don't work properly in chrome.
We installed OwnCloud again and still does not work properly in chrome.
Huge problem.

**Comment by LukasReschke** [comment]
Please use the issue template - https://github.com/owncloud/core/blob/master/CONTRIBUTING.md THX
