### ISSUE TITLE
Google Chrome issue, cannot create user, JS error

### ISSUE THREAD

**Issue by boynickie** [owncloud/core#20496]
### Expected behaviour
When creating an account, or using apps and clicking the button or some actions (changing password) the button should respond.

### Actual behaviour
They do not respond, they simply don't do anything at all.

### Server configuration
**Operating system**: -

**Web server:** -

**Database:** MYSQL

**PHP version:** 5.5

**ownCloud version:** 8.2.0

**Updated from an older ownCloud or fresh install:** UPDATED

**List of activated apps:** activity, documents, file locking, gallery, mail template editor, notifications, pdf viewer, provisioning API, share files, text editor, updater, versions, video viewer (ALL ARE OFFICIAL APPS)

``
Insert your config.php content here

<?php
$CONFIG = array (
  'instanceid' => 'ocboarhtptzi',
  'passwordsalt' => '----',
  'secret' => '----',
  'trusted_domains' => 
  array (
    0 => 'upcastnetwork.com',
  ),
  'datadirectory' => '---',
  'overwrite.cli.url' => '---',
  'dbtype' => 'mysql',
  'version' => '8.2.0.12',
  'dbname' => 'upcastne_devcld',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'upcastne_devcld',
  'dbpassword' => '----',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'developers',
  'mail_domain' => 'upcastnetwork.com',
  'mail_smtphost' => 'smtp@byethost50.org',
  'mail_smtpauthtype' => 'PLAIN',
  'loglevel' => 2,
  'trashbin_retention_obligation' => 'auto',
);

(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

**Comment by MorrisJobke** [comment]
> When creating an account, or using apps and clicking the button or some actions (changing password) the button should respond.

Which button do you mean? Maybe provide a screenshot.

**Comment by boynickie** [comment]
sorry for the delay.

In the first one you see that i try adding a user to the cloud, once i press the "create" button nothing happens, it just appears as it is on the screenshot (pressing enter same result)
But when i do this in Internet Explorer it works just fine.
![screenshot_4](https://cloud.githubusercontent.com/assets/15726577/11157737/8ce6e3a2-8a53-11e5-9971-b4b6e8237cc5.png)


In the second one you can see that i try changing my password, again same issue, literally nothing happens
![screenshot_7](https://cloud.githubusercontent.com/assets/15726577/11157740/92a03ca8-8a53-11e5-8bde-1c7c2e233b3e.png)

And there comes the worst part, in nearly every app the buttons or systems just do not work in chrome, for example, in the third screenshot i tried adding an announcement to the cloud, once the button is pressed the only thing that happens is the word "Announcing" appearing, nothing happens after, not even after 60 minutes.
While if i do this in Internet Explorer for example it does work instantly.
![screenshot_6](https://cloud.githubusercontent.com/assets/15726577/11157790/d8e8531c-8a53-11e5-8fde-32133ece4719.png)

In previous versions of owncloud we did not have this problem.
We tried freshly installing the 8.2 version (without any other apps than the default ones) and once installed it did exactly the same in chrome, not able to create accounts etcetera.

**Comment by boynickie** [comment]
I just found out this issue also happens in the Microsoft Edge Browser.
AND
In Firefox Aswell, this issue is even more serious than i thought.
It only works in Internet Explorer!

**Comment by boynickie** [comment]
While trying to add the user in chrome, i pressed f12 and got 2 errors:

http://ourcloud.com/index.php/settings/users/users Failed to load resource: the server responded with a status of 403 (Forbidden)

users.js?v=9906bdc98b4c3729ce52d088a0b43cb8:815 Uncaught TypeError: Cannot read property 'message' of undefined

**Comment by PVince81** [comment]
Every time a button doesn't work, is there a matching Javascript error in the console ?

**Comment by PVince81** [comment]
Which user backend are you using ?

**Comment by boynickie** [comment]
The error i get when trying to change password
> jquery.min.js?v=9906bdc98b4c3729ce52d088a0b43cb8:6 POST http://cloudlink/index.php/settings/personal/changepassword 403 (Forbidden)

We're currently using a webhosting, so everything we do runs with cPanel.

**Comment by boynickie** [comment]
Anyone able to help me resolve this matter?

**Comment by boynickie** [comment]
Fixed this myself, since i got no solution, some codes had to be tweaked with, but it is all resolved now.

**Comment by PVince81** [comment]
What code did you need to change ? Was it an environment issue ?
