### ISSUE TITLE
Design question regarding file path + hash

### ISSUE THREAD

**Issue by psychok7** [owncloud/core#20498]
Hey there, i got a question regarding the saving of the file path on the database. i see that you guys hash the path string so i was wondering if there is a function in the api that i am supposed to use to save and retrieve the file path? are you querying by the hash instead of the string to get a file's related data?

thanks in advance

**Comment by karlitschek** [comment]
thanks for the question. not sure this is actually a bug so I recommend to ask this question on the developer mailinglist instead. thanks
