### ISSUE TITLE
Exception: Ошибка открытия архива при установке приложения

### ISSUE THREAD

**Issue by brainkit** [owncloud/core#20490]
Set log level to debug - current level: "Warning"
Режим отладки включён
Проверено обновление схемы БД
Проверено обновление схемы БД приложений
База данных обновлена
Обновлено "files_sharing" до 0.6.3
Exception: Ошибка открытия архива при установке приложения

**Comment by MorrisJobke** [comment]
Can you please provide a english version of this exception and some more information to your setup. Have a look at the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md That are mostly the information we need.

**Comment by nickvergessen** [comment]
@brainkit please issue the issue template, so we have the necessary information:
https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version

**Comment by RealRancor** [comment]
Looks like a dup of https://github.com/owncloud/core/issues/20237
