### ISSUE TITLE
ownCloud update: Apache reload failed, stays in maintenance mode

### ISSUE THREAD

**Issue by RalfJung** [owncloud/core#20491]
I just did an update of ownCloud on my Debian Jessie machine from 8.2.0-2.1 to 8.2.0-4.1. During that update, ownCloud tried to reload the apache configuration, which failed:

```
To activate the new configuration, you need to run:
  service apache2 reload
Preparing to unpack .../owncloud_8.2.0-4.1_all.deb ...
Unpacking owncloud (8.2.0-4.1) over (8.2.0-2.1) ...
Preparing to unpack .../owncloud-server_8.2.0-4.1_all.deb ...
owncloud-server: occ maintenance:mode --on
Maintenance mode enabled
Unpacking owncloud-server (8.2.0-4.1) over (8.2.0-2.1) ...
Setting up owncloud-server (8.2.0-4.1) ...
Leaving server in maintenance mode. Please run occ upgrade manually.

See https://doc.owncloud.org/server/8.2/admin_manual/maintenance/upgrade.html

Setting up owncloud-config-apache (8.2.0-4.1) ...
Enabling conf owncloud.
To activate the new configuration, you need to run:
  service apache2 reload
apache2_invoke rewrite: already enabled
apache2_invoke owncloud: already enabled
Job for apache2.service failed. See 'systemctl status apache2.service' and 'journalctl -xn' for details.
invoke-rc.d: initscript apache2, action "reload" failed.
Setting up owncloud (8.2.0-4.1) ...
```

Here's what journalctl has to say about the reload:

```
Nov 13 12:49:28 HOSTNAME apache2[3394]: Reloading web server: apache2.
Nov 13 12:49:28 HOSTNAME apache2[3459]: Stopping web server: apache2.
Nov 13 12:49:28 HOSTNAME apache2[3481]: Starting web server: apache2AH00112: Warning: DocumentRoot [/home/git/gitlab/public] does not exist
Nov 13 12:49:28 HOSTNAME apache2[3481]: (98)Address already in use: AH00072: make_sock: could not bind to address [::]:80
Nov 13 12:49:28 HOSTNAME apache2[3481]: (98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:80
Nov 13 12:49:28 HOSTNAME apache2[3481]: no listening sockets available, shutting down
Nov 13 12:49:28 HOSTNAME apache2[3481]: AH00015: Unable to open logs
Nov 13 12:49:29 HOSTNAME apache2[3481]: Action 'start' failed.
Nov 13 12:49:29 HOSTNAME apache2[3481]: The Apache error log may have more information.
Nov 13 12:49:29 HOSTNAME apache2[3481]: .
Nov 13 12:49:29 HOSTNAME apache2[3543]: Reloading web server: apache2 failed!
Nov 13 12:49:29 HOSTNAME apache2[3543]: Apache2 is not running ... (warning).
Nov 13 12:49:29 HOSTNAME systemd[1]: apache2.service: control process exited, code=exited status=1
Nov 13 12:49:29 HOSTNAME systemd[1]: Reload failed for LSB: Apache2 web server.
```

I don't know why it is trying both a reload and a restart, but somehow, that seems to upset apache and it ends up in a bad state. "systemctl status" said

```
● apache2.service - LSB: Apache2 web server
   Loaded: loaded (/etc/init.d/apache2)
   Active: active (running) (Result: exit-code) since Fri 2015-11-13 12:49:29 CET; 18s ago
  Process: 3543 ExecReload=/etc/init.d/apache2 reload (code=exited, status=1/FAILURE)
   CGroup: /system.slice/apache2.service
           ├─ 3307 /usr/sbin/apache2 -k start
           └─18301 /usr/sbin/apache2 -k start
```

I did not try actually connecting to the website before I restart apache manually, but from the look of it, apache was down. In particular, the process listing above lacks the `php5-cgi` process that should usually be running.

ownCloud is not in maintenance mode, and I have to take further manual action to get it back to a running state.

Seems like #15200 hasn't been fixed for good.

**Comment by MorrisJobke** [comment]
cc @jnweiger

**Comment by jnweiger** [comment]
@RalfJung I suspect there is something specia with your apache setup.
We cannot reproduce the issue here.

Please test when apache is running normally, if these work:

a)
<pre>service apache2 reload</pre>

and
b)
<pre>service apache2 restart</pre>

Do these command work, if called manually?

**Comment by RalfJung** [comment]
@jnweiger Yes, they do. I cannot think of anything being special about my apache setup, except for me moving the docroot to /srv/<subdomain>. (But not for ownCloud, obviously, since it is managed by the package.) I have never seen the error message above (failure to bind to port 80) except for when ownCloud is updated - and I did lots of reloading and restarting while configuring the server.

I suspect you hit a race condition in the apache reload/restart control, see my analysis in the other bug.

**Comment by PVince81** [comment]
@owncloud/packaging anything left to do ? is the race condition still likely to exist in the most recent packages ?

**Comment by crrodriguez** [comment]
This is a race condition that can be avoided by enabling mod_systemd and using a native systemd unit of type=notify to start apache, this must be provided by your distribution..otherwise it will keep happening and there is nothing we can do to help you..(systemd won't know when to wait for apache children to cleanup properly)
