### ISSUE TITLE
Unsuccessful update from 8.1.3 to 8.1.4

### ISSUE THREAD

**Issue by ram0042** [owncloud/core#20500]
Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "contacts_index" as such route does not exist.

That's all I get from the updater.

**Comment by RealRancor** [comment]
Please use the search to find the tons of duplicates like already described here:

https://github.com/owncloud/core/issues/20462#issuecomment-155858596
