### ISSUE TITLE
UPDATE FAIL from 8.1.3.0 to 8.1.4.2

### ISSUE THREAD

**Issue by ruccc** [owncloud/core#20501]
### Steps to reproduce
1. Update with the Updater plugin
2. Go to the index, and click "Start update"

### Expected behaviour
To get updated to the new version.

### Actual behaviour
```
Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'INSERT INTO oc_filecache (fileid, storage, path, path_hash, parent, name, mimetype, mimepart, size, mtime, storage_mtime, encrypted, unencrypted_size, etag, permissions) SELECT fileid, storage, path, path_hash, parent, name, mimetype, mimepart, size, mtime, storage_mtime, encrypted, unencrypted_size, etag, permissions FROM __temp__oc_filecache': SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: oc_filecache.fileid
```

### Server configuration
**Operating system**: Linux (Shared Hosting)

**Web server:** OVH

**Database:** MySQL on /data/owncloud.db

**PHP version:** 

**ownCloud version:** updating from 8.1.3.0 to 8.1.4.2
**Updated from an older ownCloud or fresh install:** Updated from 8.1.3.0

**List of activated apps:** Activity, Calendar, Cotacts, Dashboard, Direct Menu, Documents, Encryption, ownBackup, Tasks, Updater, WebDAV...

```
I don't have access to the command line

```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'oc40l11pgwqf',
  'datadirectory' => '/home/xxxx/www/intern/data',
  'overwrite.cli.url' => 'xxxx/intern',
  'dbtype' => 'sqlite3',
  'version' => '8.1.3.0',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_smtpmode' => 'php',
  'enable_previews' => true,
  'preview_max_x' => NULL,
  'preview_max_y' => NULL,
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
);
```

**Are you using external storage, if yes which one:** 

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

```
[I get blank output... Nothing...]
```

### Client configuration
**Browser:** Firefox 41.0

**Operating system:** Windows 8.1 x64

#### ownCloud log (data/owncloud.log)

```
{"reqId":"VkZBfAoAPkIAAC@BBGoAAABX","remoteAddr":"176.84.2.83","app":"core","message":"starting upgrade from 8.1.3.0 to 8.1.4.2","level":0,"time":"2015-11-13T20:01:00+00:00","method":"GET","url":"\/intern\/core\/ajax\/update.php?requesttoken=zX88%2BsRUQdUUBGgZx5BgQQqov2BeMs"}
{"reqId":"VkZBfAoAPkIAAC@BBGoAAABX","remoteAddr":"176.84.2.83","app":"update","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\UniqueConstraintViolationException\",\"Message\":\"An exception occurred while executing 'INSERT INTO oc_filecache (fileid, storage, path, path_hash, parent, name, mimetype, mimepart, size, mtime, storage_mtime, encrypted, unencrypted_size, etag, permissions) SELECT fileid, storage, path, path_hash, parent, name, mimetype, mimepart, size, mtime, storage_mtime, encrypted, unencrypted_size, etag, permissions FROM __temp__oc_filecache':\\n\\nSQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: oc_filecache.fileid\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/promoetidj\\\/www\\\/intern\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/home\\\/promoetidj\\\/www\\\/intern\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(945): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOSqlite\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO oc_...')\\n#2 \\\/home\\\/promoetidj\\\/www\\\/intern\\\/lib\\\/repair\\\/sqliteautoincrement.php(94): Doctrine\\\\DBAL\\\\Connection->query('INSERT INTO oc_...')\\n#3 \\\/home\\\/promoetidj\\\/www\\\/intern\\\/lib\\\/private\\\/repair.php(84): OC\\\\Repair\\\\SqliteAutoincrement->run()\\n#4 \\\/home\\\/promoetidj\\\/www\\\/intern\\\/lib\\\/private\\\/updater.php(313): OC\\\\Repair->run()\\n#5 \\\/home\\\/promoetidj\\\/www\\\/intern\\\/lib\\\/private\\\/updater.php(208): OC\\\\Updater->doUpgrade('8.1.4.2', '8.1.3.0')\\n#6 \\\/home\\\/promoetidj\\\/www\\\/intern\\\/core\\\/ajax\\\/update.php(93): OC\\\\Updater->upgrade()\\n#7 {main}\",\"File\":\"\\\/home\\\/promoetidj\\\/www\\\/intern\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractSQLiteDriver.php\",\"Line\":48}","level":4,"time":"2015-11-13T20:01:01+00:00","method":"GET","url":"\/intern\/core\/ajax\/update.php?requesttoken=zX88%2BsRUQdUUBGgZx5BgQQqov2BeMs"}
```

**Comment by ruccc** [comment]
I just updated ownCloud with the Updater plugin, and now I get this error message saying:

Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'INSERT INTO oc_filecache (fileid, storage, path, path_hash, parent, name, mimetype, mimepart, size, mtime, storage_mtime, encrypted, unencrypted_size, etag, permissions) SELECT fileid, storage, path, path_hash, parent, name, mimetype, mimepart, size, mtime, storage_mtime, encrypted, unencrypted_size, etag, permissions FROM __temp__oc_filecache': SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: oc_filecache.fileid

I tried to empty the filecache table from the database, but it gives another new error, so it's not a solution...

Any idea? I am stuck with it, and I really need it to work!!!

**Comment by RealRancor** [comment]
Not quite sure but looks to me like a duplicate of https://github.com/owncloud/core/issues/18502

**Comment by ruccc** [comment]
@RealRancor 
Hmmm... It could be the Encryption app which is making this problem? I think so, but I am not an expert at all... I'll take a look, thanks.

**Comment by ruccc** [comment]
No luck with the "filesystem_check_changes => 0;" parameter in config.php.
Still the same error... Also changing the "encryption" folder's name does'nt solve the problem...

**Comment by RealRancor** [comment]
@ruccc Just close here and follow https://github.com/owncloud/core/issues/18502. I think there is no point to keep two same issues open.

**Comment by ruccc** [comment]
@RealRancor Ok, thanks!

**Comment by cdamken** [comment]
> I tried to empty the filecache table from the database, but it gives another new error, so it's not a solution...

@ruccc The oc_filecache is not a cache!, it's the whole information of the files, erasing it creates serous problems :cry:
