### ISSUE TITLE
Error PHP (appframework)

### ISSUE THREAD

**Issue by tx7** [owncloud/core#20506]
Hi all,
Just install this app, and I'm getting this error.
Hope you guys can help resolve this.

Thanks in advance.

OC version: 8.1.4 with nginx 1.2.1-2.2

Enabled:
 - activity: 2.0.2
 - agreedisclaimer: 1.0.4
 - delete_confirmation: 1.0.1
 - direct_menu: 0.4
 - extrasecurity: 0.2.0
 - files: 1.1.10
 - files_antivirus: 0.7.0.1
 - files_external: 0.2.3
 - files_locking:
 - files_mv: 0.8.1a
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.3
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videojs-sublime: 0.9.5
 - firstrunwizard: 1.1
 - galleryplus: 14.3.0
 - music: 0.3.8
 - passwordpolicy: 1.1
 - provisioning_api: 0.2
 - templateeditor: 0.1

   Disabled:
 - audios
 - documents
 - encryption
 - external
 - files_videoviewer
 - gallery
 - html5_videoplayer
 - logreader
 - mail
 - updater
 - user_external
 - user_ldap
 - user_webdavauth
 - weather

Database:
MySQL

OS:
 Debian 3.16.7-ckt11-1+deb8u6~bpo70+1

Error logged:

Error	PHP	array_merge(): Argument #2 is not an array at /media/54bf67db-da31-4c50-bb3c-27140944b223/www/owncloud/lib/private/appframework/http/request.php#407

**Comment by karlitschek** [comment]
one of you apps seems to be broken. I recommend to disable the one by one and see when the error goes aways. please post the result here after you identified the broken app

**Comment by tx7** [comment]
The culprit is 'Agree Disclaimer 1.0.4'.

**Comment by RealRancor** [comment]
@tx7 Then please close here and report this to the issue tracker of that 3rdparty app which is located here:

https://github.com/jmeile/agreedisclaimer/issues
