### ISSUE TITLE
SFTP IPv6 Adress Parsing

### ISSUE THREAD

**Issue by MaximilianKindshofer** [owncloud/core#20508]
Hi Iam trying to connect via SFTP to an IPV6 Host (via ownCloud 8.2.0 (stable)) apperently there is a Problem parsing the Adress (with and without Bracets):

Cannot connect to 2a00:61e0. Error 0. php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/owncloud/3rdparty/phpseclib/phpseclib/phpseclib/Net/SSH2.php#1011

Cannot connect to [2a00:61e0. Error 0. Failed to parse IPv6 address "[2a00:61" at /var/www/owncloud/3rdparty/phpseclib/phpseclib/phpseclib/Net/SSH2.php#1011

I double checked if I entered the IP Adress correctly:
[2a00:61e0:4068:XXXX:XXX:XXXX:XXXX:XXXX]
However only the first two doubleoctets are handed over as it seams. As I am not familiar with the codebase I don't know where the error occours.

Apperently it had worked some time ago:
https://forum.owncloud.org/viewtopic.php?f=29&t=24802

The guys at phpseclib assumed -
Problem is likely here: https://github.com/owncloud/core/blob/v8.2.0/apps/files_external/lib/sftp.php#L70-L75 
(https://github.com/phpseclib/phpseclib/issues/869)

**Comment by PVince81** [comment]
Right, the code that splits the port needs to be adjusted.

**Comment by PVince81** [comment]
@icewind1991 @Xenopathic

**Comment by icewind1991** [comment]
Fix is here https://github.com/owncloud/core/pull/20534
