### ISSUE TITLE
use Federated ID field for LDAP users

### ISSUE THREAD

**Issue by atroxix** [owncloud/core#20513]
General setup:
- Multiple OwnCloud servers using one common LDAP authentication server (Active Directory)
- Users are divided between different OwnCloud servers based on their location and have access only to their "home" OwnCloud server
- Users share data with each other either in their "home" OwnCloud server locally, or to other OwnCloud server users via Federated ID

The issue with this is that it cannot be known which user is located in which OwnCloud server, so a kind of address book needs to be maintained with this information. It would ease such use-case very much if it was possible to specify Federated ID URL of every user in LDAP instead.

Eg. in Active Directory there are several fields "extensionAttributeN", so this information could be held there. This attribute should be configurable though.

Specifying multiple URLs could make sense too - if some user has eg. primary and secondary server in use then both could be listed when sharing to this user.

**Comment by karlitschek** [comment]
@schiesbn

**Comment by PVince81** [comment]
@rullzer @blizzz

**Comment by blizzz** [comment]
Isn't this already possible via https://github.com/owncloud/core/pull/17165 and https://github.com/owncloud/contacts/pull/924 ? At least, when using the Contacts app and having the LDAP addressbook configured there.

**Comment by atroxix** [comment]
LDAP address books don't retrieve Federated ID currently (thus https://github.com/owncloud/contacts/issues/1087) and even if they did then address books should be global, so it could be avoided to add the same LDAP address book under every user separately or to share one LDAP address book (sharing an LDAP address book does currently not work).

**Comment by PVince81** [comment]
Please reopen in [user_ldap app repo](https://github.com/owncloud/user_ldap) if there is still interest in getting this implemented. @butonic
