### ISSUE TITLE
Link-sharing files (and other resources) with users that have account on a given instance fails

### ISSUE THREAD

**Issue by rysiekpl** [owncloud/core#20512]
### Steps to reproduce
1. Link-share a file
2. Give the link to a user that has an account on the same instance
3. User clicks the link, is prompted to log-in (or is already logged-in) and is redirected to their home folder; no way of getting to the shared file (unless a different browser or incognito mode is used).

### Expected behaviour

If the user is not logged, they are not prompted to; if they are logged in, they nevertheless get access to the file in exactly the same way (interface-wise) as not-logged-in users; the "Add to your ownCloud" button adds the file to their files on the same instance.

### Actual behaviour

User is redirected to their home folder; no way of getting to the shared file (unless a different browser or incognito mode is used).

### Server configuration
**Operating system**:

Debian GNU/Linux stable

**Web server:**

nginx

**Database:**

MySQL

**PHP version:**

5.4.x

**ownCloud version:** (see ownCloud admin page)

8.0.x

**Updated from an older ownCloud or fresh install:**

Updated gradually from 4.x

### Client configuration
**Browser:**

Firefox, Chromium

**Operating system:**

Windows, Kubuntu GNU/Linux

**Comment by PVince81** [comment]
Are you using the latest 8.0.x version which is 8.0.9 ?

When opening a public link no one should be asked to log in. If you see it then it's either an env issue or a bug.

Does it happen for newly created link shares or only old ones from before the update ?

@rullzer

**Comment by rullzer** [comment]
I can't reproduce this on 8.0.9.
Do your logs show anything?

**Comment by rysiekpl** [comment]
We have just updated to 8.2.0 and the error seems to be gone. So I'm closing this. Sorry to bother, should have updated and tested beforehand.
