### ISSUE TITLE
Setting the log level in the admin panel

### ISSUE THREAD

**Issue by v1r0x** [owncloud/core#20514]
I faced a logfile of 9GB and got the hint that the log level might be wrong. And actually, it was set to 0 (debug).
I think the problem that it has been set to 0 is the setting in the admin panel. For me it doesn't look like a switch where I can set the loglevel but more like a filter for watching it right now in the browser.
Maybe a description text or replace the "Loglevel <Dropdown>" with "Set your loglevel to <Dropdown>" could resolve the (or my ;) ) confusion.

What do you think @owncloud/designers ?

![log-settings](https://cloud.githubusercontent.com/assets/9248714/11168884/6a61bc98-8ba3-11e5-92f7-f19bfa30760e.png)

**Comment by RealRancor** [comment]
> Maybe a description text or replace the "Loglevel " with "Set your loglevel to " could resolve the (or my ;) ) confusion.

Sounds good. Have seen quite often that users had set that to 0/Debug and where wondering why to get a lot of logging.

**Comment by jancborchardt** [comment]
Yeah, I’d say moving it below the list and renaming to »What to log« would clear up the confusion. Will open a PR.
