### ISSUE TITLE
PDF Viewer save file not working

### ISSUE THREAD

**Issue by infosysc** [owncloud/core#20523]
PDF Viewer save file button is not working in FF 42 with owncloud 8.1.1 and 8.1.4.

The download/save button is blocked with:
"Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf blob:https://"my.domain"/c2221e84-6cd5-4951-ac0d-ce7174831afc blockiert ("frame-src *"). "

**Comment by karlitschek** [comment]
@LukasReschke any idea?

**Comment by LukasReschke** [comment]
Good old Firefox. Let me see how I can work around this there. Works in Chrome and other browsers :speak_no_evil:

**Comment by PVince81** [comment]
@LukasReschke didn't you have a look at this recently ?

**Comment by MorrisJobke** [comment]
This is fixed in 9.0 - @LukasReschke Any chance to backport this to stable8.2/stable8.1 or should we better not do this?
