### ISSUE TITLE
Can not use OCSResponse in controller

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#20529]
```json
{
  "reqId": "7BmvTh8kZsBbNtQr5UZg",
  "remoteAddr": "127.0.0.1",
  "app": "PHP",
  "message": "Call to undefined method OCP\\AppFramework\\Http\\OCSResponse::succeeded() at \/lib\/private\/api.php#206",
  "level": 3,
  "time": "2015-11-16T11:42:19+00:00"
}
```

@LukasReschke

**Comment by LukasReschke** [comment]
cc @owncloud/appframework 

(created a group to notify a bunch of appframework people, if somebody wants to join or quit please go to  https://github.com/orgs/owncloud/teams/appframework)

**Comment by DeepDiver1975** [comment]
@nickvergessen what is the calling look like? THX

**Comment by nickvergessen** [comment]
```php
return new \OCP\AppFramework\Http\OCSResponse();
```

**Comment by BernhardPosselt** [comment]
You can also just return an array if you inherit from OCSController

**Comment by DeepDiver1975** [comment]
moving this to 9.1 - it is currently unclear on how we will continue with respect to app framework and ocs integration

**Comment by BernhardPosselt** [comment]
Or rather you shoul inherit from the controller or you need to write your own JSON/XML transformers for the result, see https://doc.owncloud.org/server/8.2/developer_manual/app/controllers.html#ocs

**Comment by nickvergessen** [comment]
> You can also just return an array if you inherit from OCSController

sounds neat, but being unable to set the status and message is a little pain

**Comment by BernhardPosselt** [comment]
@nickvergessen you mean http status code?

**Comment by nickvergessen** [comment]
I mean OCS code

**Comment by DeepDiver1975** [comment]
move to 9.2

**Comment by PVince81** [comment]
@DeepDiver1975 obsolete ?
