### ISSUE TITLE
Integration tests for etag propagation

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#20521]
Currently there are unit tests for etag propagation, but it would be good to have these on Webdav level as well.

Basically fire up a Webdav client (Sabre client?), setup shares, reshares, modify a file/folder and then check whether the etag of owner and all recipients and reshare recipients has changed or stayed the same.

There is a list of unit tests that could be used for reference: https://github.com/owncloud/core/blob/master/apps/files_sharing/tests/etagpropagation.php#L184 and also the test plans https://github.com/owncloud/core/pull/14764#issuecomment-78468808 and https://github.com/owncloud/core/pull/14764#issuecomment-91272178.
Not only the root of the user's etag must change but also every parent folder that lead to the changed folder/share.

@DeepDiver1975 @icewind1991 @SergioBertolinSG 

CC @rperezb

**Comment by PVince81** [comment]
@SergioBertolinSG let us know if you have questions about the cases, I know it's not trivial :smile:

**Comment by DeepDiver1975** [comment]
Is this something we shall implement using smashbox?

**Comment by PVince81** [comment]
I thought the integration tests were already using a Webdav client to test OCS ? Might as well do the same for this.

With smashbox, using the sync client to detect etag changes (and non-etag changes) is more tricky, especially need to detect non-redownloads when the etag did not change. The only approach, even in smashbox, would be to use only pyocclient to directly check the etag in the Webdav responses.

So, both are possible. Not sure which one is best.

**Comment by SergioBertolinSG** [comment]
@DeepDiver1975 This is the same request you were talking about in https://github.com/owncloud/core/pull/20397#issuecomment-155051672 ?

**Comment by PVince81** [comment]
Let's do smashbox with pyocclient then

**Comment by PVince81** [comment]
The tests are here https://github.com/owncloud/smashbox/pull/136
