### ISSUE TITLE
Received share to local user disappears from Webdav when LDAP server unavailable

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#20536]
### Steps

1. Setup OC with a local admin user "root"
1. Setup LDAP with zombies
1. Login as "zombie1"
1. Create a folder "test" with some files inside
1. Share "test" with "root"
1. Log out
1. Run `curl -X PROPFIND http://root:admin@localhost/owncloud/remote.php/webdav/ | xmllint --format -`, check that the result contains the folder "test" => it does
1. Turn off the LDAP server (I stopped the docker instance)
1. Run the same command again, check if the folder "test" is there.

### Expected result
Either Webdav fails completely or the folder "test" appears still, but a PROPFIND on it should return "503 Storage not available".

### Actual result
The folder "test" disappears from the Webdav result, which could cause the sync client to delete it locally. A PROPFIND on the folder directly gives a 404.

### Versions
Observed in OC 8.1.4 and master (9.0 pre-alpha).

Note: this might be an edge case as we're sharing files between LDAP users and non-LDAP users.

@blizzz @Xenopathic @icewind1991

**Comment by PVince81** [comment]
CC @MorrisJobke in case you ever observed something similar

**Comment by MorrisJobke** [comment]
> CC @MorrisJobke in case you ever observed something similar

o.O This was usually fixed by the famous PR https://github.com/owncloud/core/pull/15332

**Comment by PVince81** [comment]
Yes, except that here it is special: the current user is not a LDAP user. However the received shares are from LDAP users. So maybe there's a missing exception to be thrown in that case.

**Comment by blizzz** [comment]
In that case, an LDAP interaction does not happen. Either it might be that the code path does not check for user existance and no need to get home of the sharee (not sure how the location is determined). Or, those were cached from a previous attempt, @PVince81? Can  you retry after setting cache life time to 0 in LDAP advanced settings?

**Comment by PVince81** [comment]
With the cache ttl set to 0 I get the same behavior on stable8.2.

**Comment by blizzz** [comment]
I put it on 9.0.1 for further investigation.

**Comment by blizzz** [comment]
@PVince81 so i reproduced it (except a case where the LDAP was inside a vpn. closing the connection only ended up in a timeout), however I do not think the solution is to be sought in LDAP. Any external user backend would be affected by this, thus a general solution is thought.

Anyway, the ServerNotAvailable Exception is thrown, but caught in base.php, which just writes it to the log file. Opening a PR to  discuss it.

**Comment by blizzz** [comment]
Check out https://github.com/owncloud/core/pull/22800

This however would just totally fail not only WebDAV but the web login just as well. With some more digging, we might make it possible to only take out affected files with a proper error code (OTOH this might be confusing for the user just as well, but at least other components would be working). But it is the only time the Exception is thrown and without further context info (user, file) making it hard to do everything right. Probably the shared storaged would need to take care about it.
