### ISSUE TITLE
Error while updating to 8.1.4.

### ISSUE THREAD

**Issue by ford42** [owncloud/core#20531]
Hey,
while updating to 8.1.4. i got this error:

Set log level to debug - current level: "Warning"
Wartungsmodus eingeschaltet
Datenbankschema-Aktualisierung überprüft
Datenbankschema-Aktualisierung für Apps überprüft
Datenbank aktualisiert
„files_sharing“ zu 0.6.3 aktualisiert

Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "contacts_index" as such route does not exist.
The update was unsuccessful. Please report this issue to the ownCloud community.

Can anyone help me pls?

And sry for my worse english.

Thanks
Greetings ford

**Comment by RealRancor** [comment]
Hi,

please use the search to find the tons of duplicates like already described here:

https://github.com/owncloud/core/issues/20462#issuecomment-155858596
