### ISSUE TITLE
Viewable folders on shared links 8.2.0

### ISSUE THREAD

**Issue by pushitsolutions** [owncloud/core#20549]
On 16 items (folders or files) are viewable in the link when shared link is sent to someone.   if one views that folder in their own account there is no issues, all files are there in the shared link (if you sort the files Z-A instead of A-Z then you will see the other files show up but only 16 items is viewable at a time

**Comment by RealRancor** [comment]
That should be a dup of https://github.com/owncloud/core/issues/19922
