### ISSUE TITLE
error while upgrading to 8.1.4

### ISSUE THREAD

**Issue by akakeronos** [owncloud/core#20547]
While upgrading to 8.1.4 from 8.1.3 on my ubuntu system I got this error 
Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "contacts_index" as such route does not exist.

**Comment by RealRancor** [comment]
Hi,

please use the search to find the tons of duplicates like already described here:

https://github.com/owncloud/core/issues/20462#issuecomment-155858596

Re-do the update will workaround this issue.
