### ISSUE TITLE
OCS Share API integration tests overview

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#20553]
With the sharing rework in https://github.com/owncloud/core/issues/19331 this ticket will keep track of all the tests we want.

### Keep group permissions in sync
- [ ] Done
- [x] Blocked

0. user1 is in group1
1. user0 shares file/folder with group1
2. user1 sees the share
3. user1 moves the share (so the mountpoint in webdav)
4. user0 modifies the share permissions
5. user1 has those share permissions correctly reflected

This should be tested with a few permission sets.

* Removing of permissions  (e.g. from All -> Read only)
* Adding of permissions (e.g. from Read only -> All)
* Adding and remioving of permissions (e.g. from READ + UPDATE -> READ + SHARE)

### Delete all group shares
- [x] Done

0. user1 is in group1
1. user0 shares file/folder with group1
2. user1 sees the share
3. user1 moves the share (mountpoint in webdav)
4. user0 removes the share
5. share should be deleted for user1

### No reshare
- [x] Done

1. user0 shares file/folder with user1 without reshare permissions
2. user1 tries to reshare
3. fails

Should be tested also when sharing to a group and then a member of the group tries to reshare etc.

### Can't exceed permissions
- [x] Done

1. user0 shares file/folder with limited permissions to user1
2. user1 tries to share with more permissions
3. fails

### Shared with me
- [x] Done

As described in https://github.com/owncloud/core/pull/20558#issuecomment-157368808

1. user0 shares with user1
2. user1 fetches via `../ocs/v1.php/apps/files_sharing/api/v1/shares?format=json&shared_with_me=true`
3. user1 sees the incomming share.

### Not shared with me
- [ ] Done

1. user0 shares with user1
2. user2 tries to fetch that share
3. 404

I'll keep adding to this list if I think of more testcases.
CC: @SergioBertolinSG

**Comment by SergioBertolinSG** [comment]
@rullzer thanks

**Comment by rullzer** [comment]
FYI @DeepDiver1975

**Comment by SergioBertolinSG** [comment]
First test case, point 6, I am facing this issue
https://github.com/owncloud/core/issues/20582

**Comment by SergioBertolinSG** [comment]
Tests created in https://github.com/owncloud/core/pull/20587

**Comment by rullzer** [comment]
Added a testcase

**Comment by PVince81** [comment]
@SergioBertolinSG @rullzer anything left to do here ?

**Comment by rullzer** [comment]
Covered I think.
If I find new stuff I'll open tickets in the QA repo.
Closing for now.
