### ISSUE TITLE
Using openstack swift as primary storage returns errors at start.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#20550]
### Steps to reproduce
1.- Use this docker image for swift https://hub.docker.com/r/xenopathic/ceph-keystone/
I have it on a virtual machine with ports 80, 5000, 5034, 6789, 6800-6805 redirected.
2.- Set up objectstore in config.php before setting up the server.

## Expected behaviour
Swift as primary storage.

### Actual behaviour
Error. (Logs provided).

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.2.1.1","versionstring":"8.2.1 RC3","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition.

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'objectstore' => 
  array (
    'class' => 'OC\\Files\\ObjectStore\\Swift',
    'arguments' => 
    array (
      'username' => 'test',
      'password' => 'testing',
      'container' => 'owncloud-test',
      'autocreate' => true,
      'region' => 'testregion',
      'url' => 'http://My_VIRTUAL_MACHINE_IP:6789/v2.0',
      'tenantName' => 'testenant',
      'serviceName' => 'testceph',
    ),
  ),
  'instanceid' => 'ocxowphuo4fy',
  'passwordsalt' => 'HIDDEN',
  'secret' => 'HIDDEN',
  'trusted_domains' => 
  array (
    0 => 'HOST',
  ),
  'datadirectory' => '/opt/owncloud/data',
  'overwrite.cli.url' => 'HOST',
  'dbtype' => 'mysql',
  'version' => '8.2.1.2',
  'dbname' => 'admin8',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin8',
  'dbpassword' => 'HIDDEN',
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Server logs**

```
{"reqId":"2ghrPNcbkFnNRcKqO9ju","remoteAddr":"HOST_IP","app":"objectstore","message":"Could not create object: [curl] 23: Failed writing body (0 != 158) [url] http:\/\/My_VIRTUAL_MACHINE_IP:6789\/v2.0\/tokens","level":3,"time":"2015-11-16T12:11:07+00:00"}
```

**Comment by SergioBertolinSG** [comment]
cc @butonic @Xenopathic

**Comment by karlitschek** [comment]
@butonic

**Comment by PVince81** [comment]
@SergioBertolinSG I think you also need to mount some scripts to the swift docker.
Have a look how https://github.com/owncloud/core/blob/master/tests/objectstore/start-swift-ceph.sh#L39 starts the docker instance.

**Comment by SergioBertolinSG** [comment]
Yes I mounted them in the docker.

**Comment by PVince81** [comment]
@SergioBertolinSG still have trouble with the Swift docker ?

**Comment by SergioBertolinSG** [comment]
Didn't try it again.
This seems to be related: https://github.com/owncloud/core/issues/23506

**Comment by PVince81** [comment]
@SergioBertolinSG that ticket was fixed. Can you try again ?

**Comment by PVince81** [comment]
Closing due to lack of feedback.

The other day I was able to run the primary storage tests with SWIFT with this docker and it worked fine.
