### ISSUE TITLE
Disk space counting only the total space, not the WHM plan.

### ISSUE THREAD

**Issue by chrislee264** [owncloud/core#20556]
Hi all,
I understand that there is a thread about this issue, (https://github.com/owncloud/core/issues/5352)

But I still cannot figure out why the OwnCloud administrator take up the whole space, instead of WHM plan? Apparently, I set the plan as 1GB (as an example) only but it is counting up to 500GB.

Is there a way to edit the code to display only the plan storage and perhaps, limit the file upload quota? This way, the administrator can assign the available space (from the 1GB) to many new users. I checked all the threads here but I still cannot find any relevant info on how to change that.

**Comment by MorrisJobke** [comment]
> WHM

What is WHM?

**Comment by chrislee264** [comment]
Hi, it is Web Hosting Manager (Cpanel)

**Comment by chrislee264** [comment]
Hi all,
Any suggestion on this? I think it is not really storage but more of disk space. 
I checked all the threads here, most are about the storage quota. But what about disk quota? The OC installation should have taken up the WHM (Web Hosting Manager) account space, rather than the total available in the cPanel.

**Comment by chrislee264** [comment]
Hi all,
After exploring around the setting, I think I found the solution to it. Just need to set the default quota to the desired size (can be found on the botom left shown as screw nut)
And then, create another admin and assign a group to it. Set up the size for the admin to be allocated to the users. For the group admin, assign the newly created admin too.
The rest of the users, create as per normal but dont assign them to the group admin. Only the group. 

They will show up the default quota as set up in the master admin (the very first account after setting up the OC).

Took like almost 7-10 days to figure out just this part! I dont know what will happen if I get another new issue. That would take ages to figure/solve it
