### ISSUE TITLE
Files not installed?

### ISSUE THREAD

**Issue by gjedeer** [owncloud/core#20568]
Sorry if this is the wrong project, I don't know if Files is still part of the Core.

My sync client refuses to work after upgrading to OC8. It keeps receiving error 500. I checked OC error log and the message is that Files app is not installed. Obviously it's there, the "files" menu item is there and it shows my files.

Using OC 8.1.4

<pre>
{"reqId":"xxxxxxxxxxxx","remoteAddr":"xxxxxxxxx","app":"webdav","message":"Exception: {"Message":"HTTP/1.1 503 Exception: App not installed: files","Code":0,"Trace":"#0 [internal function]: {closure}(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#1 /owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)
#2 /owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(456): Sabre\Event\EventEmitter->emit('beforeMethod', Array)
#3 /owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#4 /owncloud/remote.php(64): Sabre\DAV\Server->exec()
#5 /owncloud/remote.php(135): handleException(Object(Exception))
#6 {main}","File":"/owncloud/remote.php","Line":62}","level":4,"time":"2015-11-18T10:44:24+00:00"}
</pre>

**Comment by PVince81** [comment]
Which approach did you use when upgrading ? It is likely that something went wrong. If you replaced the source code manually, please note that the old source code needs to be deleted before extracting the new code. See https://doc.owncloud.org/server/8.1/admin_manual/maintenance/upgrade.html#manual-upgrade-procedure

**Comment by gjedeer** [comment]
I deleted the source files before, as stated in the manual. Only data dir and config was left.

**Comment by PVince81** [comment]
You could check your oc_appconfig and see if the installed flag is set for the files app.

**Comment by gjedeer** [comment]
Not sure how to interpret this:

sqlite> select * from oc_appconfig where appid='files';
files|types|filesystem
files|installed_version|1.1.10

**Comment by nickvergessen** [comment]
missing files|enabled|yes

**Comment by PVince81** [comment]
I seem to remember that code was added to prevent this case. @MorrisJobke ?

**Comment by gjedeer** [comment]
Yeah, that was it. Thank you very much.

Maybe just unhiding files from the list of disabled apps would do the trick? I had to enable calendar and contacts manually anyway, had I found files there, I'd enable it too.

**Comment by MorrisJobke** [comment]
> I seem to remember that code was added to prevent this case. @MorrisJobke ?

Usually files is hardcoded to be enabled.

**Comment by MorrisJobke** [comment]
https://github.com/owncloud/core/blob/8d79c9576a3476122ea336c1e9d45403b1610b43/lib/private/app.php#L262-L264

**Comment by MorrisJobke** [comment]
Sorry wrong link: https://github.com/owncloud/core/blob/27849077822cf85647bc79262c4b72b9591d43fa/core/shipped.json#L37-L40

**Comment by gjedeer** [comment]
And remote.php uses isInstalled instead of isEnabled, which may be why
this happened

https://github.com/owncloud/core/blob/master/remote.php#L128

**Comment by MorrisJobke** [comment]
> And remote.php uses isInstalled instead of isEnabled, which may be why
> this happened

:see_no_evil:

**Comment by gjedeer** [comment]
Looks like it was not there in 8.1.4:

https://github.com/owncloud/core/blob/v8.1.4/core/shipped.json

**Comment by MorrisJobke** [comment]
> Looks like it was not there in 8.1.4:
> 
> https://github.com/owncloud/core/blob/v8.1.4/core/shipped.json

Back then it was hardcoded in the PHP code. I will try to find a backportable solution
