### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by schnoeing** [owncloud/core#20565]
Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "contacts_index" as such route does not exist.

**Comment by schnoeing** [comment]
Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "contacts_index" as such route does not exist.

**Comment by schnoeing** [comment]
After updating second time all is good

**Comment by RealRancor** [comment]
Hi,

please use the search to find the tons of duplicates like already described here:

https://github.com/owncloud/core/issues/20462#issuecomment-155858596

Re-do the update will workaround this issue.
