### ISSUE TITLE
Cannot open extended mount options dropdown on master

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#20566]
### Steps

1. Enable external storage
1. Create a system-wide mount point (ex: SFTP)
1. Click on the cog icon in the row

### Expected result
Dropdown appears with extended mount options.

### Actual result
Nothing happens.

### Versions
Observed on 9.0 pre-alpha git master (6efa72867a300dd8399ad2d47de4f5189ded961f)

Works fine on v8.2.1RC3. => regression

@Xenopathic @icewind1991

**Comment by PVince81** [comment]
Caused by 56b537271ef591446f952c834257ae8eaac7e255 @raghunayyar from PR https://github.com/owncloud/core/pull/18821

In the future we should be **very** careful even with CSS changes.

@raghunayyar please have a look

**Comment by raghunayyar** [comment]
@PVince81 I will take care of this during the weekend.

**Comment by PVince81** [comment]
Thanks

**Comment by PVince81** [comment]
Note: you don't need an actual storage, just start setting one up and the cog will appear.

**Comment by PVince81** [comment]
@raghunayyar any update ?

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/20837
