### ISSUE TITLE
\OC\Files hooks don't fire, when files are changed via sync client or webdav

### ISSUE THREAD

**Issue by stevenbuehner** [owncloud/core#20564]
Hi there,
I am writing an automated tagging application. The goal is to automatically assign tags from the files content and metadata after it was created / modified / moved ... 
To achieve this I used hooks explained in the [Developper Manual 8.2](https://doc.owncloud.org/server/8.2/developer_manual/app/hooks.html?highlight=hook)

In my test I set up some logging for these hooks: 
* postCreate
* postCopy
* postDelete
* postRename
* postWrite

When I do changes in ownclouds webbrowser-gui, all of the hooks are fired (which I can see in the log). But when I create or move files on my local computer and the files are synced to owncloud, none of the hooks are called. Same problem accurs when I rename, create, or delete files with webdav.

I would expect, that the hooks should be fired. Because the hooks don't fire as documented in  [Developper Manual 8.2](https://doc.owncloud.org/server/8.2/developer_manual/app/hooks.html?highlight=hook) I would see this as bug.

Any help is very welcome...

**Comment by PVince81** [comment]
Hooks should fire when doing changes through Webdav, so it's likely a bug.

@icewind1991

**Comment by PVince81** [comment]
@pellaeon I remember you also had a similar question lately, but hooks did work ?

**Comment by pellaeon** [comment]
Yeah, #18759 , but I only tested hooks via web interface, let me see if I can reproduce this.

**Comment by pellaeon** [comment]
Yep, should be a bug, I can reproduce this.

**Comment by PVince81** [comment]
Can you give more information how you registered the hooks ? (just paste the lines of code that do the registration)

**Comment by PVince81** [comment]
CC @icewind1991

**Comment by pellaeon** [comment]
https://github.com/pellaeon/owncloud-ftpquota/blob/master/appinfo/application.php

**Comment by zocker22** [comment]
@PVince81 Shure thing:
In appinfo/application.php
```
		// Hooks
		$container->registerService ( 'FileHooks', function ($c) {
			return new FileHooks ( $c->query ( 'ServerContainer' )->getRootFolder (), $c->query ( 'ServerContainer' )->getLogger (), $c->resolve ( 'OCA\KnowledgeBase\Controller\FileChangeController' ) );
		} );
```

In appinfo/app.php
```
$app = new Application ();

// Register File-Hooks
/* @var $fileHooks FileHooks */
$fileHooks = $app->getContainer ()->query ( 'FileHooks' );
$fileHooks->registerFileCreated ();
$fileHooks->registerFileDeleted ();
$fileHooks->registerFileChanged ();
$fileHooks->registerFileMoved ();
$fileHooks->registerFileCopied ();
```

And here the complete file in hools/filehooks.php
```
<?php

namespace OCA\KnowledgeBase\Hooks;

use OCP\ILogger;
use OCA\KnowledgeBase\Controller\FileChangeController;

class FileHooks {
	protected $userFolder;
	protected $logger;
	protected $fileChangeController;

	public function __construct($userFolder, ILogger $logger, FileChangeController $fileChangeController) {
		$this->userFolder = $userFolder;
		$this->logger = $logger;
		$this->fileChangeController = $fileChangeController;
	}

	public function registerFileCreated() {
		$callback = function (\OCP\Files\Node $node) {
			$this->logger->error ( 'FileCreated Hook fired' );
			$this->fileChangeController->fileCreated ( $node );
		};
		
		$this->userFolder->listen ( '\OC\Files', 'postCreate', $callback );
		// $this->userFolder->listen ( '\OC\Files', 'postTouch', $callback );
	}

	public function registerFileCopied() {
		$callback = function (\OCP\Files\Node $source, \OCP\Files\Node $target) {
			$this->logger->error ( 'FileCopied Hook fired' );
			$this->fileChangeController->fileCopied ( $source, $target );
		};
		
		$this->userFolder->listen ( '\OC\Files', 'postCopy', $callback );
	}

	public function registerFileDeleted() {
		$callback = function (\OCP\Files\Node $node) {
			$this->logger->error ( 'FileDeleted Hook fired' );
			$this->fileChangeController->fileDeleted ( $node );
		};
		
		$this->userFolder->listen ( '\OC\Files', 'postDelete', $callback );
	}

	public function registerFileMoved() {
		$callback = function (\OCP\Files\Node $source,\OCP\Files\Node $target) {
			$this->logger->error ( 'FileMoved Hook fired' );
			$this->fileChangeController->fileMoved ( $source, $target );
		};
		
		$this->userFolder->listen ( '\OC\Files', 'postRename', $callback );
	}

	public function registerFileChanged() {
		$callback = function (\OCP\Files\Node $node) {
			$this->logger->error ( 'FileChanged Hook fired' );
			$this->fileChangeController->fileChanged ( $node );
		};
		
		$this->userFolder->listen ( '\OC\Files', 'postWrite', $callback );
	}

}

?>
```

**Comment by zocker22** [comment]
If someone points me, to where I need to change files, I would do it. But I guess I am not the right person for this :). 
What I can do, updating the development guide. I would like to add a comment, that file-hooks are broken and only work in the webinterface.
Or do you think this bug will be fixed by someone in the next release 2.2 maintenance | 2.3 ? ....

**Comment by athorel-asi** [comment]
Hi @stevenbuehner, I had the same issue as you,

Webdav use php file core/remote.php and use application filesystem
Your application is not loaded so the event is welled emit, but your application has not registered listener.

So you can change the remote.php

and after line 120
`	

       // Load all required applications
	\OC::$REQUESTEDAPP = $app; 
	OC_App::loadApps(array('authentication')); 
	OC_App::loadApps(array('filesystem', 'logging')); 
        //--> Load your app HERE
	OC_App::loadApp('myAPP'); 
`

@PVince81 this solution is a patch, maybe the new version of owncloud can allow developer to specify if application has to be loaded by webdav in appinfo.php

**Comment by stevenbuehner** [comment]
@athorel-asi
Thanks. I was hoping to find a solution that won't need any core-modification (because we use linux upgrade-system). But still this patch helps me to at least keep on working. So, thank you.

**Comment by tombou** [comment]
I'm new with owncloud apps and this fix works like a charm in 8.2.2. That would be great if we don't have to patch the remote.php in next version.

**Comment by oparoz** [comment]
Fix might be in #23636

**Comment by DeepDiver1975** [comment]
Loading all apps is wrong.
If your app should operate on DAV it has to be if type 'filesystem'

**Comment by butonic** [comment]
See e.g., https://github.com/owncloud/core/blob/master/apps/files_external/appinfo/info.xml#L18

**Comment by stevenbuehner** [comment]
@DeepDiver1975 So did I get this right, if a app is [labeled](https://github.com/owncloud/core/blob/master/apps/files_external/appinfo/info.xml#L18) as filesystem app, it will automatically be loaded during dav and also fire the corresponding hooks?

**Comment by icewind1991** [comment]
Yes

**Comment by oparoz** [comment]
Documentation problem:
https://github.com/owncloud/documentation/issues/2325
