### ISSUE TITLE
Do not use 15768000 as standard HTST value

### ISSUE THREAD

**Issue by Fohlen** [owncloud/core#20561]
I am currently using OwnCloud Stable 8.1.4(stable) on my server (the configuration is not important for this issue).
Within the warning headers of my OwnCloud I noticed the following
![hsts_settings](https://cloud.githubusercontent.com/assets/3730888/11213579/fce2a29a-8d3c-11e5-85d4-bc2f9f79e4c4.png)
This is actually a bad practice and should not warn system administrators in the way it's done.
Since Let's Encrypt is about to roll the dice, you should **strongly** consider [*"Why ninety-day lifetime for certificates"*](https://letsencrypt.org/2015/11/09/why-90-days.html)

**Comment by LukasReschke** [comment]
> This is actually a bad practice and should not warn system administrators in the way it's done.
Since Let's Encrypt is about to roll the dice, you should strongly consider "Why ninety-day lifetime for certificates"

HSTS does only check whether the request is coming via HTTPS. It does no kind of certificate pinning.

**Comment by Fohlen** [comment]
Why on earth do you warn about a short lifetime than?
Since key-pinning requires an accommodate backup plan with certificates from several CA's this is somewhat expensive and can not be generally recommended.

**Comment by LukasReschke** [comment]
> Why on earth do you warn about a short lifetime than?

We don't warn about the certificate lifetime at all.

https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security vs. https://en.wikipedia.org/wiki/HTTP_Public_Key_Pinning

HSTS is the former.

**Comment by LukasReschke** [comment]
From said Wikipedia link:
> The HSTS Policy[2] is communicated by the server to the user agent via an HTTP response header field named "Strict-Transport-Security". HSTS Policy specifies a period of time during which the user agent shall access the server in a secure-only fashion.

This has nothing to do with the certificate at all. You could use another one for each request and your browser wouldn't care.
