### ISSUE TITLE
Generated previews on public sharing page are not high-res

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#20576]
When viewing an image via a shared link, the generated thumbnail looks blurry on high-res screens. This worked fine in the past as far as I remember?

Easy to test by sharing a screenshot (or something else pixel-perfect) and viewing it on a smartphone.

@owncloud/thumbnails @owncloud/sharing

**Comment by georgehrke** [comment]
> When viewing an image via a shared link,

Are you referring to ownCloud2ownCloud sharing or public links?

**Comment by jancborchardt** [comment]
Public links. Public sharing page, as said.

**Comment by icewind1991** [comment]
Fix is here: #20581

The loaded preview was taking into account the dpi correctly but then when displaying the image it didn't properly set the size to force the browser into using it as hidpi image
