### ISSUE TITLE
File picker styles broken on master

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#20573]
### Steps

1. Upload a bunch of files and folders
1. Go to the personal page
1. Go to the avatar section
1. Click "Select from new files"

### Expected result
Not so ugly dialog

### Actual result
Ugly and broken-looking dialog

![filepicker-boken-master](https://cloud.githubusercontent.com/assets/277525/11244042/e2d309ba-8e0b-11e5-862d-1c8afd1b32c7.png)

### Versions
Observed on master, works fine on stable8.2 => regression

I did not bisect but I could imagine it affected by recent CSS changes.

@raghunayyar @Henni @owncloud/designers

**Comment by Henni** [comment]
My (first ever) bisect tells me that this was introduced long before the recent CSS changes in:
5e9ca79788fba962418865c0431d25a0a2dc89f7 PR #19742 by @rullzer

**Comment by rullzer** [comment]
mmm could be. since I removed the icon. But that could should not use it as far as I know.

@Henni when you revert my commit on master is the issue fixed?

**Comment by Henni** [comment]
reverting 5e9ca79788fba962418865c0431d25a0a2dc89f7 results in:
![image](https://cloud.githubusercontent.com/assets/1267827/11421196/b0a6c9a8-9433-11e5-8f8c-bd99d51e1f78.png)

**Comment by rullzer** [comment]
PR with fix in #21364
