### ISSUE TITLE
Symfony\Component\Routing\Exception\RouteNotFoundException

### ISSUE THREAD

**Issue by Llorc** [owncloud/core#20589]
Hello,
I was updating my ownCloud from 8.1.3 to 8.1.4 using the menu tool when
when an error was raised:
            Mise à jour de « files_sharing » vers 0.6.3
Symfony\Component\Routing\Exception\RouteNotFoundException:
Unable to generate a URL for the named route "contacts_index" as such route does not exist.

I was queryied to post this, so I do ;)

I don't know what information to add to help.

**Comment by Xenopathic** [comment]
Please search for duplicate issues before posting, we already have one for this: #19145

**Comment by RealRancor** [comment]
One? Thousands :-)
