### ISSUE TITLE
owner-display-name webdav attribute shows wrong user for remote shares

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#20580]
### Steps

1. Create two users "user1" and "user2"
1. Login as "user1"
1. Create folder "test"
1. Share folder "test" with "user2@localhost/owncloud" (or similar)
1. Login as "user2"
1. Accept the share
1. Query the "owner-display-name" property using PROPFIND

### Expected result
The value is "user1@localhost/owncloud".

### Actual result
The value appears as "user2" (the same as the currently logged in user).
It is likely due to the fact that we used `getOwner()`, not sure if this would create the compound remote user name ? @rullzer @schiesbn @icewind1991 

### Versions
OC 9.0 pre-alpha git master 6efa72867a300dd8399ad2d47de4f5189ded961f

Required for https://github.com/owncloud/core/pull/16902

**Comment by icewind1991** [comment]
Fix is here: https://github.com/owncloud/core/pull/20584

**Comment by PVince81** [comment]
You rock :smile:
