### ISSUE TITLE
Cannot unfavorite from sidebar in Favorites section when path is in subdir

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#20586]
### Steps

1. Create a folder "abc/def"
1. Mark "def" as favorite
1. Go to "Favorites" section
1. Open the sidebar for "def"
1. Click the star in the sidebar

### Expected
Favorite properly removed

### Actual
Error, it seems it's using "/def" instead of "/abc/def" as path.

Possibly trivial fix, must make the sidebar action code use the proper path, not the file list dir.

### Versions
OC 8.2.1 RC3 and master (9.0 pre-alpha)

CC @SergioBertolinSG @davitol to add such cases to test plan, most importantly is that the shared or favorite file/folder isn't inside the root originally, file actions might differ/break as they have to use the correct real path

**Comment by rullzer** [comment]
This works for me correctly on master.

**Comment by davitol** [comment]
It does NOT WFM on Master

![screen shot 2016-02-10 at 13 11 24](https://cloud.githubusercontent.com/assets/10596560/12946884/e6193a26-cff7-11e5-8b46-efacdf6f5d15.png)

**Comment by PVince81** [comment]
Hmm, that is supposed to be fixed by https://github.com/owncloud/core/pull/22213

**Comment by davitol** [comment]
1- Create a folder "abc/def"
    2 - Mark "def" as favorite
    3 - Go to "Favorites" section
    4-  Open the sidebar for "def"
    5 - Click the star in the sidebar
    Clicking on on the sidebar star again, it is not posible to favorite the folder again. No console logs are present.

**Comment by rullzer** [comment]
@davitol that all works here.... very weird...

Can you see the post commands that are send?

**Comment by davitol** [comment]
![favforrull](https://cloud.githubusercontent.com/assets/10596560/12972049/2333bb16-d0a2-11e5-895b-de8cc7df4d8f.gif)

**Comment by rullzer** [comment]
Thanks! Now I can reproduce it.

**Comment by PVince81** [comment]
Works fine on 9.1.1
