### ISSUE TITLE
Getting an specific share with a user as recipient doesn't return anything.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#20582]
### Steps to reproduce

Having 'user0' and 'user1' as users.
'user1' belongs to group1.
1. Using user0 share a file 'textfile.txt' with group1.
2. Do 
```
curl -X GET http://user0:user0@HOST/ocs/v1.php/apps/files_sharing/api/v1/shares
```
Get the share id of 'textfile.txt'.

3. Using the share id you got, do:

```
curl -X GET http://user1:user1@HOST/ocs/v1.php/apps/files_sharing/api/v1/shares/share_id
```

## Expected behaviour
Return a response code.

### Actual behaviour
Nothing is answered. (internal error?)

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"9.0.0.2","versionstring":"9.0 pre alpha","edition":"Enterprise"}

Happening also in master branch.

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in community edition.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Server logs**
```

```

cc @rullzer

**Comment by rullzer** [comment]
Yes this behaviour is well. undefined to say the least. Basically what we had so far:

* `../shares` list all shares by me
* `../shares?shared_with_me=true` list all shares with me
* `../shares/<ID>` get info of share with id <ID> by me

Now I think the cleanest approach here would be to make sure that `../shares/<ID>` would return also info for shares with me. So in the OCS endpoint we need to have a check that verifies if either the share is by me or to me.

@DeepDiver1975 I assume that is fine as it is not breaking the API?

However, I don't feel much for trying to add that to the existing code. Let me tackle that in sharing 2.0

**Comment by rullzer** [comment]
This is fixed with the new sharing code.
