### ISSUE TITLE
Group specific enabling of apps that listen for hooks from users across different groups

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#20583]
We have debated this issue slightly here: https://github.com/owncloud/core/pull/20310, yet that PR is to fix purely apps that use public.php.

What is still an issue is apps such as Activity listen for user-generated hooks (for example on file access/deletion etc). If Activity is only enabled for a specific set of users (in a defined list of groups) there is no mechanism to load the backends of Activity for the other users, meaning Activity streams are left incomplete as the hooks have no listeners for users outside of the enable list for the Activity app.

Obviously this depends on the app as to whether it is an issue, but for Activity it seems a user would still be interested in actions performed on their files by other users even if the Activity app is not enabled for them.

Finally, to make things clearer, this issue does not affect apps using public.php routes since in these conditions all apps are loaded regardless so hooks can be triggered.

This ticket is purely for discussion of how this issue may be addressed.

@PVince81 @nickvergessen

**Comment by nickvergessen** [comment]
Activity is marked as filesystem because of that, so it can only be enabled for all or no-one.
