### ISSUE TITLE
CentOS 7 issues with fresh 8.2.1

### ISSUE THREAD

**Issue by carlaschroder** [owncloud/core#20592]
I found a few quirks on a clean 8.2.1 stable installation on CentOS 7. I installed it on an updated, current CentOS from CentOS_7 owncloud-8.2.1-1.1 on https://download.owncloud.org/download/repositories/stable/owncloud/

1. It is missing the Update app and apps categories. The missing categories are Multimedia, Productivity, Game, and Tool.

Enabled:
  - activity: 2.1.3
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1

Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap

2. It reports on the admin page "This server has no working Internet connection", which is not correct.

3. It reports "cURL is using an outdated NSS version (NSS/3.15.4)." But 3.19.1 is installed.

If you need more information I am happy to provide it.

**Comment by RealRancor** [comment]
Hi,

the no internet connection message is very likely caused by cURL message. That check is not version based but reproduces the Bug:

> For NSS the patch version depends on your distribution and an heuristic is running the test which actually reproduces the bug. There are distributions such as RHEL/CentOS which have this backport still pending.

from https://doc.owncloud.org/server/8.2/admin_manual/configuration_server/security_setup_warnings.html#outdated-nss-openssl-version

The second message is very likely correct.

**Comment by PVince81** [comment]
@jnweiger see above for the potentially missing app ?

**Comment by RealRancor** [comment]
@PVince81 The updater app is not shipped via the repositories because users shouldn't use the updater app when updating their oC installation via repositories.

**Comment by PVince81** [comment]
Of course... that makes sense

**Comment by jnweiger** [comment]
intentional. see https://github.com/owncloud/updater/issues/122

**Comment by carlaschroder** [comment]
Ok I am no amazing developer guru :) I just know that when I install ownCloud on Ubuntu 14.04 and 15.04, new fresh clean installations, the Updater app is installed and enabled.

It would be nice to be un-confused on how the Updater app is supposed to operate, because when I am confused the documentation is confused, and then users are confused and they bother you nice developers. Yes, everyone is supposed to use occ. But shared hosters do not have this option, and when there is a nice big button to click most users will click the button.

Any ideas about the missing app categories for CentOS?

**Comment by carlaschroder** [comment]
Re Ubuntu-- I will run one more test installation to make sure.

**Comment by RealRancor** [comment]
> Ok I am no amazing developer guru :) I just know that when I install ownCloud on Ubuntu 14.04 and 15.04, new fresh clean installations, the Updater app is installed and enabled.

From repository or by a manual installation? If installed via repository there should be really no updater shipped.

> Any ideas about the missing app categories for CentOS?

Have done a write-up about that at the forums:

https://forum.owncloud.org/viewtopic.php?f=17&t=29790

The cURL/NSS message is the root cause of this.

**Comment by carlaschroder** [comment]
That is wonderful, @RealRancor. Pay top dollar to Red Hat and watch the bug report for a crucial app sit there for a year.

**Comment by carlaschroder** [comment]
> From repository or by a manual installation?

Repository.

**Comment by carlaschroder** [comment]
Results of clean new 8.2.1 installation on brand-new Ubuntu 15.04 VM from https://download.owncloud.org/download/repositories/stable/owncloud/

Apache/2.4.10
MariaDB 5.6.27
PHP 5.6.4
ownCloud 8.2.1 (stable) 

Enabled:
  - activity: 2.1.3
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - updater: 0.6

Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap

config.php:

  'instanceid' => 'foo',
  'passwordsalt' => 'foo',
  'secret' => 'foo',
  'trusted_domains' => 
  array (
    0 => 'localhost',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://localhost/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.2.1.4',
  'dbname' => 'ocdbb',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_molly1',
  'dbpassword' => 'foo',
  'logtimezone' => 'UTC',
  'installed' => true,

**Comment by jnweiger** [comment]
owncloud-app-updater should not be installed on new clean Ubuntu installations. That is a bug.
Any difference that you see between Ubuntu 14.04 and Centos 7 is amost certainly a bug.

**Comment by jnweiger** [comment]
Removed updater app from DEB packages. Was still there, although long ago removed from RPM packages.
https://s2.owncloud.com/package/rdiff/ce:8.2:testing/owncloud?linkrev=base&rev=13

**Comment by jnweiger** [comment]
Fix to be visible with 8.2.2 and later...

**Comment by jnweiger** [comment]
@carlaschroder is that a step towards less confusion or more confusion?

**Comment by carlaschroder** [comment]
@jnweiger Confusion is receding and clarity is developing :) Thanks, the biggest doc issues are always installation and upgrading. Now I can clean that up, and then go complain to my Red Hat friends about their addiction to obsolete software versions :)

**Comment by carlaschroder** [comment]
Closing for https://github.com/owncloud/documentation/issues/1911
https://github.com/owncloud/documentation/issues/1912
