### ISSUE TITLE
OCS API error code:997 from clients 2.0.2 testing with OC8.1.3

### ISSUE THREAD

**Issue by gig13** [owncloud/core#20590]
### Steps to reproduce
1. We're testing our build of 2.0.2 before release and have an error message when sharing from the desktop on the Mac. 
 
2. When sharing from the desktop client on the Mac, I see the share link checkbox checked and a box at the bottom of the window with the following error message:
```
OCS API error code: 997
```
3. There's a close button also. No controls for password or expiry.

### Expected behavior
The client should not show any error messages.

### Actual behavior
Desktop clients display an OCS API error code 997

### Server configuration
**Operating system**: RHEL 6

**Web server:** Apache

**Database:** Percona

**PHP version:** 5.5.30

**ownCloud version:** 8.1.3

**Updated from an older ownCloud or fresh install:** Updated

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** Active Directory

### Client configuration
Client OS: Mac

This is against our production server on 8.1.3. We have the sharing api turned on and allow users to share by public link. We have a default expiry date of 30 days but don't require it to be used. We don't have federation turned on. No other restrictions in place.

Keep in mind we have our F5 in between. We have a number of paths that are excluded from authenticating on the F5 including /remote.php/webdav/ and all the urls required for public links. 

@MorrisJobke

**Comment by MorrisJobke** [comment]
It would be super interesting what 997 means. http://www.freedesktop.org/wiki/Specifications/open-collaboration-services/ doesn't even know a single occurrence of 997. I searched the code and it seems to be a permission issue.

It's used for user deletion, user change and looking up group memberships. cc @rullzer @tomneedham

**Comment by rullzer** [comment]
It comes from https://github.com/owncloud/core/blob/master/lib/public/api.php#L54 

So it is indeed an unauthorized thing.

**Comment by gig13** [comment]
I think we've found the culprit. I'll confirm with you tomorrow when it's fixed, but it's something with our F5 config. A direct connection to the web server doesn't have the same problem.

**Comment by gig13** [comment]
@MorrisJobke @tomneedham @rullzer 
Additional feedback based on expected functionality.

I was doing my testing on a file that had been shared with the test user from another account. When creating a public link I was expecting the date to be set accordingly and in the web interface it appeared as though it was. Clicking the share button to make the dialog go away and again to draw it again showed no expiry date. The database also showed no expiry date. So the web interface was showing what the javascript was sending to the server, not what the server was sending back.

Because this was a reshare execution eventually rolls through /lib/private/share/share.php and the checkReshare function (called by put). The expiration date sent from the browser as part of the request is passed to this function. It then runs getItemShareWithBySource which returns an array  which is stored as $checkReshare. This array contains the details of the original share to make sure you're not granting permissions you yourself don't have. There's no expiration on the original share because it's an internal share.

A little way down the expiration date is set with the following.
$result['expirationDate'] = min($expirationDate, $checkReshare['expiration']);
min() returns the unset $checkReshare['expiration'] because null is less than everything.


This could all be by design but my expectation would be that ANY public link gets the default expiration period. Is it even possible to put an expiration on an internal link or re-share a public link you've linked to your owncloud account from someone else's server?

So to me this statement should look like something like this:

if (isset($checkReshare['expiration'])) { $result['expirationDate'] = min($expirationDate, $checkReshare['expiration']); } else { $result['expirationDate'] = $expirationDate; }

This would make sure that the parents expiration is taken into account if it exists but won't cancel the new expiration if it doesn't.

So I guess the issue for this ticket is resolved by fixing our F5 config. But this secondary bug/unexpected design is something different.

**Comment by MorrisJobke** [comment]
> Is it even possible to put an expiration on an internal link or re-share a public link you've linked to your owncloud account from someone else's server?

no.

**Comment by MorrisJobke** [comment]
@rullzer Didn't you fixed something on the expiration code recently?

**Comment by rullzer** [comment]
@MorrisJobke most likely.. but I can't remember this situation.

Comment from @gig13 makes sense. I'll try to look into it in a bit more detail soon.

**Comment by gig13** [comment]
@rullzer Any update?

**Comment by gig13** [comment]
@MorrisJobke @rullzer @bboule 
Any updates?

**Comment by rullzer** [comment]
@gig13 are you in a position to prepare a PR with your patch?

**Comment by MorrisJobke** [comment]
> @gig13 are you in a position to prepare a PR with your patch?

I will do so.

**Comment by MorrisJobke** [comment]
> I will do so.

https://github.com/owncloud/core/pull/20877

**Comment by gig13** [comment]
thanks

**Comment by PVince81** [comment]
Can this be closed or is there anything left to do ?

**Comment by MorrisJobke** [comment]
This is solved in 9.0 - a backport request is pending.

**Comment by MorrisJobke** [comment]
@gig13 Fixes went into 8.1.5, 8.2.2 and 9.0.0

**Comment by bboule** [comment]
@gig13  are you good here can we c;lose this out?

**Comment by gig13** [comment]
This is closed.
