### ISSUE TITLE
Different icons for different files_external storages

### ISSUE THREAD

**Issue by jmaciasportela** [owncloud/core#20598]
We need custom icons to identify the external storage type in the web interface. We need default icon and error icon.

![icons](https://cloud.githubusercontent.com/assets/1454351/11264682/d512d352-8e95-11e5-9ab6-d0775e5b58ac.jpg)

The list of storages is:

- amazon S3
- webdav
- dropbox
- ftp 
- google drive
- local 
- owncloud
- sftp
- SMB <-- We already have it
- openstack

cc @jancborchardt @PVince81 

Related: https://github.com/owncloud/core/issues/20427

**Comment by jancborchardt** [comment]
Previously (years ago when I proposed it) there was uncertainty about if using logos of other services is ok. @karlitschek @MTRichards can you confirm this?

**Comment by PVince81** [comment]
I think it's not that bad to keep the generic icon for the other services.

**Comment by karlitschek** [comment]
I'm not sure. It is a really good idea to have the icons. But I'm not sure we can. @MTRichards What do you think?

**Comment by MTRichards** [comment]
I need to ask our legal folks...if we have open source icons for that, should be ok - I would like to keep them if we can.

For windows, for example, this could work - there are icons for windows there: https://github.com/Templarian/WindowsIcons/blob/master/WindowsPhone/license.txt

**Comment by hodyroff** [comment]
@MTRichards that doesn't help as "* Does not apply to copyrighted logos
- Skype
- Facebook
- Twitter
- etc...
"
Meaning to get copyrighted icons from somebody else doesn't make them better.
ownCloud style icons which are reusing icons from others in a descriptive way without change, other then the colours is fine. Need to review them one by one.
If there are icons in the pointed set which work and are truly CC-non attribution then it works of course as well, however they need to be added to the 3rd party list!

**Comment by MTRichards** [comment]
>It is a really good idea to have the icons. But I'm not sure we can. @MTRichards What do you think? 

So the answer is yes, if we review the icons one at a time and approve, but then we can get them in.

**Comment by PVince81** [comment]
This sounds like a nice to have, if possible. Not necessarily high priority.
Should we set this to 9.1 ?

Regarding the WND and sharepoint icons, we had them before, so we might want to keep these at least (as it is now already).

**Comment by jmaciasportela** [comment]
There are some cases very easy to implement without legal problems:
![local](https://cloud.githubusercontent.com/assets/1454351/11299498/921da552-8f87-11e5-82fb-e6bafc91a998.jpg)
![dav](https://cloud.githubusercontent.com/assets/1454351/11299496/9218a7d2-8f87-11e5-8799-581dac8d3eb1.jpg)
![sftp](https://cloud.githubusercontent.com/assets/1454351/11299499/921f7440-8f87-11e5-84d0-8127b24c767c.jpg)
![ftp](https://cloud.githubusercontent.com/assets/1454351/11299497/921c1c64-8f87-11e5-92ef-273f8bd2a9f1.jpg)

Of course is only a suggestion, but I think that is few work but very good enhancement.

**Comment by jancborchardt** [comment]
The question there is if it’s really relevant which exact protocol is used. I’d say the info that it’s an external storage is enough. Anything beyond that is technical detail.

**Comment by MTRichards** [comment]
@jancborchardt 
Really? I would parse this one layer down...

Knowing that a file is in SharePoint or WND, and a visual cue to see that this is the SharePoint folder, just makes it easier to find what you are looking for in the browser., particularly since there is no requirement to call the folder mount point SharePoint in any way. 

I think this is primarily because not all back ends are created equal, or have the same interaction experience. We try hard, but they don't. 

Anyway, after WND and SharePoint, the rest I am not so worried about. I think Local is not necessary, that is a technical detail. 
DAV, SFTP, FTP I am indifferent about.

When we add, for example something like documentum, I might also add a logo there as that is a big animal and it is good to know as a user what to expect.

**Comment by jancborchardt** [comment]
@MTRichards I only meant the technical protocols like local, dav, sftp, ftp etc which you also said you are indifferent about. ;) The others I think could get icons, and WND/Sharepoint already have them anyway and that’s fine.

**Comment by MTRichards** [comment]
Ok, then we are agreed. Thanks for clarifying, and we have a plan!

**Comment by jancborchardt** [comment]
So then the plan is though to keep it as it is, right? ;) Use the generic »external storage« icon on all external storages except wnd and sharepoint where we use the custom ones.

**Comment by PVince81** [comment]
Only WND and sharepoint show a special icon, others are kept as before.
