### ISSUE TITLE
Security & setup warnings: cURL is using an outdated NSS version (NSS/3.15.4).

### ISSUE THREAD

**Issue by Landver** [owncloud/core#20608]
Full text of error:
cURL is using an outdated NSS version (NSS/3.15.4). Please update your operating system or features such as installing and updating apps via the app store or Federated Cloud Sharing will not work reliably.

I want to fix that bug without update of curl. Anyway city-fan repo is down and I can't update to latest verion of curl or libcurl.

CentOS version 7 x64
ownCloud verion 8.2

curl version:
[root@localhost stast]# rpm -qa |grep curl
curl-7.29.0-19.el7.x86_64
libcurl-7.29.0-19.el7.x86_64
python-pycurl-7.19.0-17.el7.x86_64

php version:
[root@localhost stast]# rpm -qa |grep php
php-mbstring-5.4.16-36.el7_1.x86_64
php-cli-5.4.16-36.el7_1.x86_64
php-gd-5.4.16-36.el7_1.x86_64
php-common-5.4.16-36.el7_1.x86_64
php-xml-5.4.16-36.el7_1.x86_64
php-pdo-5.4.16-36.el7_1.x86_64
php-mysql-5.4.16-36.el7_1.x86_64
php-5.4.16-36.el7_1.x86_64

apache verion:
[root@localhost stast]# rpm -qa |grep http
httpd-2.4.6-31.el7.centos.1.x86_64
httpd-tools-2.4.6-31.el7.centos.1.x86_64

Epel repository had already been installed. That's last verions that I can take from there.

**Comment by LukasReschke** [comment]
> I want to fix that bug without update of curl. Anyway city-fan repo is down and I can't update to latest verion of curl or libcurl.

=> You can't. Ignore and life with some potential bugs or update it.

**Comment by Landver** [comment]
But city-fan repo is down and I can't update to latest verion of curl or libcurl

**Comment by LukasReschke** [comment]
But this is the wrong place to discuss this. Please go to https://owncloud.org/support/

**Comment by RealRancor** [comment]
From my PoV this even don't need to be discussed. There is a bug in the running NSS lib which needs to be fixed with an upgrade.
