### ISSUE TITLE
Quota configuration from LDAP user not used

### ISSUE THREAD

**Issue by blink38** [owncloud/core#20600]
### Steps to reproduce
1. Configure your owncloud to use LDAP authentication
2. In LDAP Special Attributes (Advanced Tab), set an attribute for "Quota Field"
3. In your LDAP, set a value for this attribute to a user.
4. Login with this user and verify that the LDAP value is in use

## Expected behaviour
The LDAP value is used

## Actual behaviour
The LDAP value is always ignored

## Server configuration
debian 7 / Nginx / MySQL / PHP 5.4.45 / Owncloud 8.2.0 (Updated from 8.1.3)

## Problem identified :
In file <b>apps/user_ldap/lib/user/user.php</b>
In function updateQuota($valueFromLDAP = null)
Line : 
<pre><code>    $quota = !is_null($valueFromLDAP)
                        ? $valueFromLDAP
                        : $quotaDefault !== '' ? $quotaDefault : null;</code></pre>
Do not work as expected. Even if $valueFromLDAP is set, $quota use $quotaDefault.

Corrected Line :
<pre><code>                $quota = !is_null($valueFromLDAP)
                        ? $valueFromLDAP
                        : <b>(</b>$quotaDefault !== '' ? $quotaDefault : null<b>)</b>;</code></pre>

If you add parenthesis on the last line, $quota is set to $valueFromLDAP when $valueFromLDAP have a value.

You can found below a small php script which will show you the importance of parenthesis.
<pre><code>$quotaDefault = "2 GB";
$valueFromLDAP = "10 GB";

echo "1. quota (expected 10 GB) = " . 
		$quota = !is_null($valueFromLDAP)
                        ? $valueFromLDAP
                        : $quotaDefault !== '' ? $quotaDefault : null;

echo "\n2. quota (expected 10 GB) = " . 
		$quota = !is_null($valueFromLDAP)
                        ? $valueFromLDAP
                        : ($quotaDefault !== '' ? $quotaDefault : null);

$valueFromLDAP = null;

echo "\n3. quota (expected 2 GB) = " . 
		$quota = !is_null($valueFromLDAP)
                        ? $valueFromLDAP
                        : $quotaDefault !== '' ? $quotaDefault : null;

echo "\n4. quota (expected 2 GB) = " . 
		$quota = !is_null($valueFromLDAP)
                        ? $valueFromLDAP
                        : ($quotaDefault !== '' ? $quotaDefault : null);
echo "\n";</code></pre>

Result is :
<pre>1. quota (expected 10 GB) = 2 GB
2. quota (expected 10 GB) = 10 GB
3. quota (expected 2 GB) = 2 GB
4. quota (expected 2 GB) = 2 GB</pre>

**Comment by MorrisJobke** [comment]
cc @blizzz

**Comment by MorrisJobke** [comment]
@blink38 Can you maybe also create a pull request for the proposed changes. This then would speed up the time to fix this. ;)

**Comment by blizzz** [comment]
fixed in 8.2.1, was also reported twice at least

**Comment by blink38** [comment]
Yes fixed in https://github.com/owncloud/core/commit/e1d61284f87f2bb5aaf1523ce4f78e439d737165
