### ISSUE TITLE
issues with documentation + backgrounjobs + app testing

### ISSUE THREAD

**Issue by psychok7** [owncloud/core#20606]
I was wondering if the documentation for owncloud 8.2 regarding backgroundjobs (https://doc.owncloud.org/server/8.2/developer_manual/app/backgroundjobs.html) and app testing (https://doc.owncloud.org/server/8.2/developer_manual/app/testing.html) is up to date?

I am having trouble making these work, and i also realized that the calling of the background job example in the link above is different from the calling here https://doc.owncloud.org/server/8.2/developer_manual/app/init.html .

Could anyone provide me with working examples please?

**Comment by PVince81** [comment]
If you need support for development stuff, please use the development mailing list instead.
See https://owncloud.org/support/
