### ISSUE TITLE
[settings:personal] First Run Wizard button and the quota section are stuck together.

### ISSUE THREAD

**Issue by davitol** [owncloud/core#20610]
### Steps to reproduce

1. Go to personal settings

### Expected behaviour

There should be more distance between First Run Wizard button and the quota section

### Actual behaviour

First Run Wizard button and the quota section are stuck together.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 9.0 pre alpha (daily) Build:2015-11-19T04:29:14+00:00 da5285dc23dc88d8f570409a8d7ed1296b95f407

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox
![screen shot 2015-11-19 at 14 19 00](https://cloud.githubusercontent.com/assets/10596560/11271763/975b057e-8ec8-11e5-9951-d56e304599f4.png)

**Comment by MorrisJobke** [comment]
cc @owncloud/designers

**Comment by jancborchardt** [comment]
Seems like another bug possibly related to the recent moving-around of CSS, most likely the inputs. cc @Henni @raghunayyar

**Comment by jancborchardt** [comment]
@Henni another similar issue also related by the same pull request of moving the inputs.css https://github.com/owncloud/core/pull/20465/files

Before (correctly connected) & now (own rows)
![capture du 2015-11-25 22-02-14](https://cloud.githubusercontent.com/assets/925062/11409437/3cf5fda8-93c0-11e5-8963-0448c8150474.png)![capture du 2015-11-25 22-01-01](https://cloud.githubusercontent.com/assets/925062/11409438/3cfc40c8-93c0-11e5-8309-186afc520554.png)

@Henni were there more changes than just the whitespace move?

**Comment by Henni** [comment]
there are no other changes.
Only problem might be different prioritization because of css order.

**Comment by MorrisJobke** [comment]
This will be fixed by https://github.com/owncloud/core/pull/20994
