### ISSUE TITLE
[IE8] Instead or redirect to login page, a JSON response is shown

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#20612]
### Steps

1. Login into OC using IE8
1. On the server, delete the session files to simulate expiration
1. Refresh the page

### Expected result
Redirect to login page

### Actual result
A JSON response appears.
Sometimes it even tries to download that page...

![ie8-redirectlogin](https://cloud.githubusercontent.com/assets/277525/11272709/338bf772-8ecf-11e5-9ae5-277d835c8887.png)

### Versions
Observed on OC pre-alpha 9.0 git master 58eaeb267c60ed2aed4b5592a28d16f5453bb773

**Comment by PVince81** [comment]
@LukasReschke 
@davitol (for the test case)

**Comment by MorrisJobke** [comment]
This only happens in master - stable8.2 works fine.

As IE8 support is dropped in 9.0 I will close this issue.

https://github.com/owncloud/core/issues/15567
