### ISSUE TITLE
open_basedir issue

### ISSUE THREAD

**Issue by hoorna** [owncloud/core#20621]
Hi, I have the same open_basedir issue as team4music in issue #20451. When I open the adminstrator webpage then the next warning is written in owncloud.log. 

`{"reqId":"GXUcwdxkVGWgHw\/9PpTp","remoteAddr":"192.168.2.1","app":"PHP","message":"is_dir(): open_basedir restriction in effect. File(\/var\/services\/homes) is not within the allowed path(s): (\/etc.defaults:\/etc:\/usr\/syno\/synoman:\/tmp:\/var\/services\/tmp:\/var\/services\/web:\/var\/services\/homes:\/dev\/urandom) at \/volume1\/web\/owncloud\/3rdparty\/symfony\/process\/Symfony\/Component\/Process\/ExecutableFinder.php#59","level":3,"time":"2015-11-19T17:25:28+01:00"}`

I think I found the problem. A search in the complete owncloud database for "volume1" (which is a wrong directory) points to the table oc_jobs and it gives two hits. See the next picture.

![schermafdruk 2015-11-19 17 46 20](https://cloud.githubusercontent.com/assets/7532234/11278853/8eacb894-8eed-11e5-8b0a-76c3fc7f25a4.jpg)

The wrong directory with "volume1" is probably placed in the oc_jobs table because of the variable "datadirectory" in config.php a long time ago. Later on I changed this variable but the old records are not deleted in oc_jobs. Probably this is a bug. 

Because of this, I have 3 questions:
1) The subdirectory in record 4 is the only one which points to the right directory. So can I safely delete the records 5, 6 and 7 manually?
If this is not possible:
2) The id's 6 and 7 with the wrong subdirectory "\/volume1\" should be replaced by "\/var\/services\/web\". Is it safe to edit and change this manually?
3) Besides that, the subdirectory in id 5 is no longer existing. Can I delete this record safely?

**Comment by RealRancor** [comment]
Maybe related to the fact that moving the datadir after an installation is not supported yet: https://github.com/owncloud/documentation/pull/1588

**Comment by hoorna** [comment]
Seems very likely to me!

What should I do to solve the problem in my situation? Can somebody give me a clue?

**Comment by PVince81** [comment]
You might need to manually update the paths in oc_storages and oc_jobs to match the new ones.

I wasn't aware that logrotate is using absolute values, will raise separately.

**Comment by PVince81** [comment]
Raised here https://github.com/owncloud/core/issues/20628

@hoorna it looks like there are already entries for your new path ? If yes, you can then manually delete the old outdated entries. The warning is likely to be appearing because the old entries were trying to access the wrong folder.

**Comment by hoorna** [comment]
Hi Vincent,

I deleted the old outdated entries.

Unfortunately I still get the following (new) error:

is_dir(): open_basedir restriction in effect. File(/var/services/homes) 
is not within the allowed path(s): 
(/etc.defaults:/etc:/usr/syno/synoman:/tmp:/var/services/tmp:/var/services/web:/var/services/homes:/dev/urandom) 
at 
/volume1/web/owncloud/3rdparty/symfony/process/Symfony/Component/Process/ExecutableFinder.php#59

This is strange because if I search the complete owncloud database for 
the text "homes" (part of "/var/services/homes") there is not one single 
hit. Searching the .\owncloud directory with Windows Explorer (searching 
for the text "homes" in all the files) doesn't gives me a relevant hit 
either.

Can you help me out to solve this problem? I hope you are willing to 
reply. Thanks for that.

Best regards,
Alfred

------ Origineel bericht ------
Van: "Vincent Petry" <notifications@github.com>
Aan: "owncloud/core" <core@noreply.github.com>
CC: "hoorna" <email@alfredvanhoorn.nl>
Verzonden: 20-11-2015 10:10:56
Onderwerp: Re: [core] open_basedir issue (#20621)

**Comment by hoorna** [comment]
Hi Vincent,

I have discovered two other strange issues with the open_basedir 
error-messages:
First, if you look in the allowed paths in open_basedir (in my last 
mail), you can see that /var/services/homes is in open_basedir. So, why 
is owncloud complaining that /var/services/homes is not within it?
When I delete /var/services/homes from open_basedir, then the 
error-rmessage disappears. This seems also strange to me because in this 
case /var/services/homes is not with the paths of open_basedir. Just in 
this situation I should expect that owncloud complains about the absence 
of /var/services/homes in open_basedir, but owncloud is not.
I hope that you get this mail and my writings are clear. Sorry for my 
english.

Best regards,
Alfred


------ Origineel bericht ------
Van: "Alfred van Hoorn" <email@alfredvanhoorn.nl>
Aan: "owncloud/core" 
<reply@reply.github.com>
Verzonden: 20-11-2015 21:46:38
Onderwerp: Re[2]: [core] open_basedir issue (#20621)

**Comment by RealRancor** [comment]
Hi,

> I should expect that owncloud complains about the absence of /var/services/homes in open_basedir, but owncloud is not.

those are messages directly from your PHP and not from ownCloud itself. open_basedir is something handled by PHP and not by an application like ownCloud.

Maybe thats just a buggy behavior with your specific PHP version or something similar.

**Comment by hoorna** [comment]
Hi,

I think it is a problem within owncloud.

What I understand from the code in 
/owncloud\/3rdparty\/symfony\/process\/Symfony\/Component\/Process\/ExecutableFinder.php 
this code is using open_basedir and checks all the subdirectories in 
open_basedir one by one. I am using PHP version 5.5.30 in a Synology 
Diskstation (latest firmware).


------ Origineel bericht ------
Van: "RealRancor" <notifications@github.com>
Aan: "owncloud/core" <core@noreply.github.com>
CC: "hoorna" <email@alfredvanhoorn.nl>
Verzonden: 22-11-2015 15:44:44
Onderwerp: Re: [core] open_basedir issue (#20621)

**Comment by RealRancor** [comment]
@hoorna If you think this is a problem within oC please create a new issue. The initial issue here is already raised in https://github.com/owncloud/core/issues/20628
