### ISSUE TITLE
Homedirectory-Mounts in .org-Version

### ISSUE THREAD

**Issue by aspdye** [owncloud/core#20620]
Hi there,

According to https://forum.owncloud.org/viewtopic.php?f=21&t=31462 I wanted to ask why Homedirectory-Mounts are only possible in the Enterprise Version.

Would be nice if External Storage (NAS) could be selected as Default for users and not only for a subfolder ;)

**Comment by karlitschek** [comment]
homedirectory mount is a typical enterprise feature that is only needed in big installations. This is what the enterprise edition is optimized for.
