### ISSUE TITLE
Error when there is a file "config.php" in current directory

### ISSUE THREAD

**Issue by txt-file** [owncloud/core#20626]
My $HOME contains a file named ```config.php``` with content
```
<?php
echo "BUG!\n";
?>
```

I added a ```var_dump($message);``` inside lib/public/util.php which provided
```
owncloud@txtpie:~$ php5 -f /home/owncloud/owncloud/cron.php 
string(52) "Autoload path not allowed: /home/owncloud/config.php"
PHP Fatal error:  Call to a member function getLogger() on null in /home/owncloud/owncloud/lib/public/util.php on line 155
owncloud@txtpie:~$ 
```

System information:
owncloud 8.2.1
php 5.6.14-0+deb8u1

**Comment by txt-file** [comment]
This error is in a different behaviour also in version 7.0.7 of owncloud.
```
owncloud@Cubian:~$ echo -e "<?php\necho \"BUG\\\n\";\n?>" > config.php
owncloud@Cubian:~$ /usr/bin/php5 /home/owncloud/owncloud/cron.php 
BUG
owncloud@Cubian:~$ php5 -v
PHP 5.4.45-0+deb7u2 …
```

**Comment by MorrisJobke** [comment]
Fixed with https://github.com/owncloud/core/pull/20365

Duplicate of https://github.com/owncloud/core/issues/19959

**Comment by txt-file** [comment]
1. Why won't you backport this fix to all current releases?
2. Would this fix the behaviour in comment 2 (owncloud 7.0.x)?

**Comment by MorrisJobke** [comment]
> Would this fix the behaviour in comment 2 (owncloud 7.0.x)?

stable7 is in security fixing mode only and will be eol in january.

**Comment by MorrisJobke** [comment]
> Why won't you backport this fix to all current releases?

See https://github.com/owncloud/core/pull/20365#issuecomment-154416796 <- too much risk to break other stuff horribly. Therefore the workaround is to remove the file from those directories.

**Comment by txt-file** [comment]
Alright. Thanks for taking the time to answer.
