### ISSUE TITLE
Incomplete View in OC'version' => '8.2.1.4',

### ISSUE THREAD

**Issue by hitam4450** [owncloud/core#20631]
After an successful (technically) upgrade to the current version, i wanted to check and look around the new version.

However, i could not access the   Administration menu in the far right corner of menu bar! 
(see enclosed screen shot!)
I did not change anything at all of the monitor display controls, all other OC instances i have full access to the admin menu  by using the *direct menu* app.. I use FF 42.0 and the OC 8.2.1 instance is shown in its own FF tab!
regards, hitam4450
PS: After disabling the *direct menu* app I have access to the admin panel again!

![oc821-rc](https://cloud.githubusercontent.com/assets/9738727/11297356/238014a4-8f78-11e5-9b16-abf6e4e195ef.png)

**Comment by Xenopathic** [comment]
The direct menu app is a 3rd party app, so you should report the issue there.
