### ISSUE TITLE
asset-pipeline not working properly

### ISSUE THREAD

**Issue by symphoniker** [owncloud/core#20632]
Owncloud 8.2.1
OS: Debian

Asset-Pipeline is breaking the Update Section in Admin (see attached image)

I cleared all browser cache and did "occ maintenance:repair" to clear the asset-pipeline cache in owncloud as well. The issue still exists.

Setting asset-pipeline.enabled = false, does solve the issue.

![updater-owncloud](https://cloud.githubusercontent.com/assets/13055014/11298119/3d01e614-8f7d-11e5-9905-480ef436699f.PNG)

**Comment by RealRancor** [comment]
@symphoniker Duplicate of https://github.com/owncloud/updater/issues/184 which gets fixed with oC 9.0 by https://github.com/owncloud/core/pull/20461

**Comment by symphoniker** [comment]
Sorry I did a quick search but I have not found the issue so this one can be closed.

**Comment by RealRancor** [comment]
You can close this on your own by hitting the "Close" button below the comment box.

**Comment by symphoniker** [comment]
Perfect thx for the info.
