### ISSUE TITLE
Problem with sync client.

### ISSUE THREAD

**Issue by gthery** [owncloud/core#20634]
Hi all,

I've a problem with my sync client (2.0.2 build 5569) and my owncloud server (8.2.1)

The client can't download files, I you paste this error message:

In tab activity:
Operation canceled and connection timed out....

Do you have a solution? I can't sync any files.

Thanks
Sorry for my English I'm French :)

**Comment by RealRancor** [comment]
Hi,

please put those keywords:

Operation canceled
connection timed

into the search field on top of

https://github.com/owncloud/core/issues

and

https://github.com/owncloud/client/issues

where you should find some duplicate, already reported issues about that.
