### ISSUE TITLE
Mixed Language messages from update(r)

### ISSUE THREAD

**Issue by hitam4450** [owncloud/core#20630]
Today I upgraded my OC 8.1.4 test installation to OC 8.2.1 without any (technical) problems.

However, i noticed that the upgrade messages were presented in a *mixed language* (german/english) mode!
For me personally, this *mixed mode*  is no problem, since I am not only bi-lingual - I am even multi-lingual -.
However i could imagine, that some users / administrators might be annoyed by this fact!

This serves just as a feedback!

regards, hitam4450

Enclosed you*ll find some screen shots of the messages displayed!
![update821a](https://cloud.githubusercontent.com/assets/9738727/11296520/e4431b92-8f72-11e5-9ba4-0691aeeda117.png)
![update821b](https://cloud.githubusercontent.com/assets/9738727/11296518/e440c0f4-8f72-11e5-9940-e79717205b8d.png)
![update821](https://cloud.githubusercontent.com/assets/9738727/11296519/e4410622-8f72-11e5-918e-349abe2fa319.png)

**Comment by MorrisJobke** [comment]
@nickvergessen something for your l10n backport tool ;) (the one from @vgezer )

**Comment by nickvergessen** [comment]
Well translations have not been there in time

**Comment by nickvergessen** [comment]
String for future copy-paste usage
> `Checking whether the database schema can be updated (this can take a long time depending on the database size)`
> `Checking whether the database schema for %s can be updated (this can take a long time depending on the database size)`

The strings are not even translated by now, so nothing we can fix really.

**Comment by DeepDiver1975** [comment]
as far as I can tell all the updater messages are by now translated -> closing
Please reopen in case the issue still persists - THX
