### ISSUE TITLE
Upgrade from 8.0.4.2 to 8.2.0 fails with "Updates between multiple major versions and downgrades are unsupported"

### ISSUE THREAD

**Issue by a-schild** [owncloud/core#20640]
Debian server 64Bit with 8.0.4 installed.

When trying the update, it fails with this error:

"Exception: Updates between multiple major versions and downgrades are unsupported."

In the config.php I see this:
'version' => '8.0.4.2'

In the log I see this:

```
{"reqId":"6U24EhE0XTz3o\/5GF1uE","remoteAddr":"2001:470:26:421:1dd1:571b:1a3f:3327","app":"PHP","message":"Class 'OC_FileProxy' not found at \/home\/digitrade\/cloud\/htdocs\/apps\/files_sharing\/appinfo\/ap
p.php#28","level":3,"time":"2015-11-20T13:41:58+00:00"}
{"reqId":"BEqjAqHsySKp6H+g8jUM","remoteAddr":"2001:470:26:421:1dd1:571b:1a3f:3327","app":"core","message":"starting upgrade from 8.0.4.2 to 8.2.1.4","level":0,"time":"2015-11-20T13:42:01+00:00","method":"GET
","url":"\/core\/ajax\/update.php?requesttoken=c0R9T3wnEHltNyozOWw3OTZpBQgFDSJVJEU4FD8k%3A75E6MRf%2BXYnDLCdUNFhPWtzcN7RdzB"}
{"reqId":"BEqjAqHsySKp6H+g8jUM","remoteAddr":"2001:470:26:421:1dd1:571b:1a3f:3327","app":"core","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Updates between multiple major versions and do
wngrades are unsupported.\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/digitrade\\\/cloud\\\/htdocs\\\/lib\\\/private\\\/updater.php(205): OC\\\\Updater->doUpgrade('8.2.1.4', '8.0.4.2')\\n#1 \\\/home\\\/digitrade
\\\/cloud\\\/htdocs\\\/core\\\/ajax\\\/update.php(111): OC\\\\Updater->upgrade()\\n#2 {main}\",\"File\":\"\\\/home\\\/digitrade\\\/cloud\\\/htdocs\\\/lib\\\/private\\\/updater.php\",\"Line\":285}","level":3,
"time":"2015-11-20T13:42:01+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=c0R9T3wnEHltNyozOWw3OTZpBQgFDSJVJEU4FD8k%3A75E6MRf%2BXYnDLCdUNFhPWtzcN7RdzB"}
{"reqId":"EhQikNShe9lywvd47YSg","remoteAddr":"2001:470:26:421:1dd1:571b:1a3f:3327","app":"PHP","message":"Class 'OC_FileProxy' not found at \/home\/digitrade\/cloud\/htdocs\/apps\/files_sharing\/appinfo\/app
.php#28","level":3,"time":"2015-11-20T13:44:46+00:00"}
{"reqId":"zaZZzjz83qaORvrK0cgi","remoteAddr":"2001:470:26:421:1dd1:571b:1a3f:3327","app":"core","message":"starting upgrade from 8.0.4.2 to 8.2.1.4","level":0,"time":"2015-11-20T13:44:49+00:00","method":"GET
","url":"\/core\/ajax\/update.php?requesttoken=JigJEEM5FRNRFhQcQ3V8FBBZHyg8EixiXjk9NXM%2F%3AbY1irLcAdxPk6Z%2FxhvrpnktT4KWE6Y"}
{"reqId":"zaZZzjz83qaORvrK0cgi","remoteAddr":"2001:470:26:421:1dd1:571b:1a3f:3327","app":"core","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Updates between multiple major versions and do
wngrades are unsupported.\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/digitrade\\\/cloud\\\/htdocs\\\/lib\\\/private\\\/updater.php(205): OC\\\\Updater->doUpgrade('8.2.1.4', '8.0.4.2')\\n#1 \\\/home\\\/digitrade
\\\/cloud\\\/htdocs\\\/core\\\/ajax\\\/update.php(111): OC\\\\Updater->upgrade()\\n#2 {main}\",\"File\":\"\\\/home\\\/digitrade\\\/cloud\\\/htdocs\\\/lib\\\/private\\\/updater.php\",\"Line\":285}","level":3,
"time":"2015-11-20T13:44:49+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=JigJEEM5FRNRFhQcQ3V8FBBZHyg8EixiXjk9NXM%2F%3AbY1irLcAdxPk6Z%2FxhvrpnktT4KWE6Y"}
{"reqId":"XK96kVO\/VnzbBnW1J1Hg","remoteAddr":"2001:470:26:421:1dd1:571b:1a3f:3327","app":"PHP","message":"Class 'OC_FileProxy' not found at \/home\/digitrade\/cloud\/htdocs\/apps\/files_sharing\/appinfo\/ap
p.php#28","level":3,"time":"2015-11-20T13:44:53+00:00"}
{"reqId":"xJbx7WrVBHVJNaKikVw6","remoteAddr":"2001:470:26:421:1dd1:571b:1a3f:3327","app":"core","message":"starting upgrade from 8.0.4.2 to 8.2.1.4","level":0,"time":"2015-11-20T13:45:35+00:00","method":"GET
","url":"\/core\/ajax\/update.php?requesttoken=FykNEXVNMSNnIyMmRG1rOQtGWgkWNRlvWhEdHDwz%3ASX5hD8GqRMgQ1B8Usi7QDLAY0cwlyU"}
{"reqId":"xJbx7WrVBHVJNaKikVw6","remoteAddr":"2001:470:26:421:1dd1:571b:1a3f:3327","app":"core","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Updates between multiple major versions and do
wngrades are unsupported.\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/digitrade\\\/cloud\\\/htdocs\\\/lib\\\/private\\\/updater.php(205): OC\\\\Updater->doUpgrade('8.2.1.4', '8.0.4.2')\\n#1 \\\/home\\\/digitrade
\\\/cloud\\\/htdocs\\\/core\\\/ajax\\\/update.php(111): OC\\\\Updater->upgrade()\\n#2 {main}\",\"File\":\"\\\/home\\\/digitrade\\\/cloud\\\/htdocs\\\/lib\\\/private\\\/updater.php\",\"Line\":285}","level":3,
"time":"2015-11-20T13:45:35+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=FykNEXVNMSNnIyMmRG1rOQtGWgkWNRlvWhEdHDwz%3ASX5hD8GqRMgQ1B8Usi7QDLAY0cwlyU"}
```

**Comment by RealRancor** [comment]
Hi,

@a-schild 
i think the message should clear where the issue is? You first need to upgrade to 8.1.4 before you're able to go to 8.2.1.

I think you can close this one yourself and do the following upgrade path:

8.0.4 -> 8.0.9 -> 8.1.4 -> 8.2.1

Each older release is available here: https://owncloud.org/changelog/

**Comment by a-schild** [comment]
Hmmm...

no, the message is not clear, since I did not want to do a downgrade.

Also the update manager told me that a upgrade was available, so I did just used the update manager to do the upgrade.
The update manager should handle this correctly and propos (and make) a upgrade to the required version and not a (apparaently) impossible jump to the latest version

**Comment by RealRancor** [comment]
> no, the message is not clear, since I did not want to do a downgrade.

The message is telling:

> Updates between multiple major versions

> The update manager should handle this correctly and propos (and make) a upgrade to the required version and not a (apparaently) impossible jump to the latest version

Thats not an issue of the updater app or oC core itself but of the update url. There is a long running / open issue about that: https://github.com/owncloud/appstore-issues/issues/4

I think there is nothing what can be done within core here.

**Comment by a-schild** [comment]
OK, agree with this.

**Comment by RealRancor** [comment]
Just have pushed https://github.com/owncloud/appstore-issues/issues/4 again. This is now open since more than a year and was always an issue for the updater app. :-/

**Comment by step21** [comment]
This should be fixed asap, maybe it is fixed in 9? Especially as even when manually checking, the obvious thing is to see 8 as the major version, thus 7.x to 8.x could be assumed to be fine, as long as not upgrading to 9.x directly. :-/

**Comment by RealRancor** [comment]
@step21 See https://github.com/owncloud/appstore-issues/issues/4 Nothing to fix/discuss in core or updater app.

Btw. 7.0.x, 8.0.x, 8.1.x, 8.2.x and 9.0.x are major versions.

**Comment by step21** [comment]
@RealRancor thanks, yeah I saw that already. Though for outsiders not familiar with the codebase, it is unclear where this originates and just still creates a bad experience, also as it is unclear what Owncloud sees as major and minor versions. (thanks for explaining, but it is not possible to discern that from core or the updater app.

**Comment by RealRancor** [comment]
> also as it is unclear what Owncloud sees as major and minor versions.

I think thats clearly defined here:

> Major releases are 8.0, 8.1, 8.2, and 9.0. Point releases are intermediate releases for each major release. For example, 8.0.9 and 8.1.3 are point releases. Skipping major releases is not supported.

https://doc.owncloud.org/server/9.0/admin_manual/maintenance/upgrade.html
