### ISSUE TITLE
Problems installing ownCloud 8.0.X

### ISSUE THREAD

**Issue by aspdye** [owncloud/core#20647]
I am trying to install ownCloud 8.0.X on an Webserver. ownCloud 7, 8.1 and 8.2 installation just works. But 8.0.X is not possible. But why? I need it for having an stable ownCloud Instance with Calendar and Contacts ;) 

### Steps to reproduce
1. Install ownCloud 8.0.X (by copying files into the vhost)
2. Go to https://url/owncloud
3. Type in Admin Username and Password / Setup Database
4. Click Install

### Expected behaviour
Should go to Files app, after preparing database.

### Actual behaviour
Internal Server Error (ownCloud Error Message)

### Server configuration
**Operating system**:
Ubuntu 14.10 LTS
**Web server:**
Apache
**Database:**
Tested with MySQL / SQLite 
**PHP version:**
5.6
**ownCloud version:** (see ownCloud admin page)
8.0.X
**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**
Nothing changed.

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.
**Are you using encryption:** yes/no
No.
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No.

### Client configuration
**Browser:**
Firefox, Chrome, Edge
**Operating system:**
Windows 10 
#### Web server error log
```
[Wed Nov 18 18:03:08.105835 2015] [authz_core:error] [pid 22976] [client ] AH01630: client denied by server configuration: /var/www/vhosts/XXX/httpdocs/owncloud/owncloud/data/htaccesstest.txt
[Wed Nov 18 18:03:19.686831 2015] [authz_core:error] [pid 23012] [client ] AH01630: client denied by server configuration: /var/www/vhosts/XXX/httpdocs/owncloud/owncloud/data/htaccesstest.txt
[Wed Nov 18 18:03:19.839763 2015] [authz_core:error] [pid 23003] [client ] AH01630: client denied by server configuration: /var/www/vhosts/XXX/httpdocs/owncloud/owncloud/data/htaccesstest.txt
[Wed Nov 18 18:03:20.805527 2015] [proxy_fcgi:error] [pid 22968] [client ] AH01071: Got error 'PHP message: creating sqlite db\n', referer: http://XXX/owncloud/owncloud/
[Wed Nov 18 18:05:46.322671 2015] [authz_core:error] [pid 23003] [client ] AH01630: client denied by server configuration: /var/www/vhosts/XXX/httpdocs/owncloud/owncloud/data/htaccesstest.txt
[Wed Nov 18 18:05:46.452158 2015] [authz_core:error] [pid 23382] [client ] AH01630: client denied by server configuration: /var/www/vhosts/XXX/httpdocs/owncloud/owncloud/data/htaccesstest.txt
[Wed Nov 18 18:06:00.443201 2015] [proxy_fcgi:error] [pid 23012] [client ] AH01071: Got error 'PHP message: creating sqlite db\n', referer: http://XXX/owncloud/owncloud/index.php/apps/files/
[Wed Nov 18 18:09:33.310141 2015] [proxy_fcgi:error] [pid 21458] [client ] AH01071: Got error 'PHP message: creating sqlite db\n', referer: http://XXX/owncloud/owncloud/
[Wed Nov 18 18:09:50.691375 2015] [proxy_fcgi:error] [pid 23367] [client ] AH01070: Error parsing script headers, referer: http://XXX/owncloud/owncloud/index.php/apps/contacts/
[Wed Nov 18 18:09:50.739421 2015] [proxy_fcgi:error] [pid 22898] [client ] AH01070: Error parsing script headers, referer: http://XXX/owncloud/owncloud/index.php/apps/contacts/
[Wed Nov 18 19:55:14.380137 2015] [proxy_fcgi:error] [pid 24069] [client ] AH01070: Error parsing script headers, referer: https://XXX/owncloud/owncloud/index.php/apps/contacts/
```

**Comment by karlitschek** [comment]
This sounds like some kind of strange configuration problem on the server. I recommend that look for support on the forum or the other options listed here: https://owncloud.org/support/
