### ISSUE TITLE
Cannot share at all when share with link is disabled globally

### ISSUE THREAD

**Issue by Liwindo** [owncloud/core#20642]
I have the problem since the update to 8.2.1 that i can't share files in the cloud via names or groups anymore. With the activated option to share files via a link username autocompletion and sharing via groups and names works but without this option not.

**Comment by karlitschek** [comment]
@schiesbn any idea?

**Comment by PVince81** [comment]
Please use the issue template https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

"in the cloud", do you mean federated shares ? If yes, which OC version do the original and target OC server have ?

From which version did you upgrade ? (the template will ask you that)

**Comment by Liwindo** [comment]
### Steps to reproduce
1. Type an existing name of a group or user in the sharing field

### Expected behaviour
A name of a group or a user for sharing pops up

### Actual behaviour
No name pops up

### Server configuration
**Operating system:** Ubuntu 14.04

**Web server:** Apache with nginx-proxy

**Database:** Mysql

**PHP version:** 5.6.14

**ownCloud version:** 8.2.1

**Updated from an older ownCloud or fresh install:** 8.1.4

**List of activated apps:** Activity, Default Encryption Modul, Deleted Files, File Locking, First Run Wizard, Gallery, Mail Template Editor, PDF Vierwer, Provisioning API, Share Files, Text Editor, Updater, Versions, Video Viewer, Calender, Contacts, Password Policy, Polls, User Conversations

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'secret',
  'passwordsalt' => 'secret',
  'secret' => 'secret',
  'trusted_domains' => 
  array (
    0 => 'domain.tld',
  ),
  'datadirectory' => '/var/www/vhosts/domain.tld/cloud/data',
  'overwrite.cli.url' => 'https://domain.tld',
  'dbtype' => 'mysql',
  'version' => '8.2.1.4',
  'dbname' => 'secret',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'secret',
  'dbuser' => 'secret',
  'dbpassword' => 'secret',
  'installed' => true,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'theme' => 'themename',
  'maintenance' => false,
  'logtimezone' => 'Europe/Berlin',
  'log_type' => 'owncloud',
  'log_authfailip' => true,
  'mail_smtpmode' => 'php',
  'mail_from_address' => 'hostmaster',
  'mail_domain' => 'domain.tld',
  'mail_smtpsecure' => 'tls',
  'mail_smtpauth' => 1,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => 'domain.tld',
  'loglevel' => 3,
  'trashbin_retention_obligation' => 'auto',
);

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 42

**Operating system:** Windows 7

### Logs
#### Web server error log
empty

#### ownCloud log (data/owncloud.log)
empty

Supplement: No, i don't mean federated sharing. Sharing by links is deactivated and resharing too.
I upgraded from 8.1.4 to 8.2.1 by the update app.
I seem to be not the only one, have a look at the first reply: https://forum.owncloud.org/viewtopic.php?f=36&t=31588

**Comment by McBochi** [comment]
I can confirm this bug, it happens in my updated installation too.
However the AJAX call works correctly and data is provided but it won't get rendered...

**Comment by PVince81** [comment]
Indeed, disabling link sharing in the admin page breaks the share dialog.

**Comment by PVince81** [comment]
It says "resharing is not allowed" which is wrong and there is a JS error in the console:
![sharenolinkerror](https://cloud.githubusercontent.com/assets/277525/11333489/425d15cc-91ce-11e5-9460-0f7a11551c4c.png)

**Comment by PVince81** [comment]
@rullzer

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/21009

**Comment by douglasanpa** [comment]
I have this same problem ... put this all enabled, the only difference is that sharing does not work with LDAP users

I'm in owncloud 9 with php 5.5.9

My config in Sharing 
Allow apps to use the Share API (yes)
Allow users to share via link (yes)
Enforce password protection (no)
Allow public uploads (yes)
Allow users to send mail notification for shared files (yes)
Set default expiration date (no)
Allow resharing (yes)
Restrict users to only share with users in their groups (yes)
Allow users to send mail notification for shared files to other users (yes)
Exclude groups from sharing (no)
Allow username autocompletion in share dialog. If this is disabled the full username needs to be entered. (yes)

**Comment by PVince81** [comment]
@douglasanpa mind making a new ticket for this one ?

CC @blizzz @rullzer in case you have heard of this issue with sharing + LDAP ?

**Comment by douglasanpa** [comment]
@PVince81 It has been fixed in 9.0.1
