### ISSUE TITLE
Missing singlequote for login failed log entry

### ISSUE THREAD

**Issue by jsalatiel** [owncloud/core#20659]
After upgrade to  8.1 , fail2ban regular expression to block owncloud bruteforce stopped working. At first i was going to notify fail2ban developers, but after taking a look  i noticed that there is now a missing single quote in the warn line for login failed.

{"reqId":"VlBmD38AAQEAABzPRPQAAAAA","remoteAddr":"192.168.254.102","app":"core","message":"Login failed: 'jsalatiel' (Remote IP: '192.168.254.102)","level":2,"time":"2015-11-21T09:39:43-03:00"}

You can see that the message shows (Remote IP: **'192.168.254.102**)" , old versions showed (Remote IP: '192.168.254.102')" , i think there is a missing single quote. If i am wrong , just close the issue.

Thanks!

**Comment by RealRancor** [comment]
Hi,

yes this is known and was fixed with 8.2 with https://github.com/owncloud/core/pull/17517
