### ISSUE TITLE
SMB External Storage Sharing C$

### ISSUE THREAD

**Issue by jrh7675** [owncloud/core#20656]
### Steps to reproduce
1. ownCloud 8.1 + (as recent as 8.2.1)
2. Create a user or global share as a SMB/CIFS w/Session credentials. Point the ownCloud folder to a Windows device's default C$ share, not specifying a remote subfolder. (If you don't want to point to C$ - then create another share pointing to the root of your C drive or a drive containing a special system file like Pagefile.sys.
3. Attempt to view the ownCloud folder, you should experience an "unknown error" toast message flash in the browser and the contents of the remote share will not be displayed.

Basically your creating an ownCloud share to the root of a Windows C: drive. I think ownCloud bombs because of locked files at the root.

### Expected behaviour
The contents of the C$ share should be displayed.

### Actual behaviour
Unknwon error message toasted in the browser then the contents of the last folder successfully displayed are displayed. 

As you can see from the logs an error seems to occur when parsing pagefile.sys which is a special file always open by the system. This file's attributes aren't all queriable so something about this file is throwing ownCloud for a loop. I imagine ownCloud queries file information for parsing and when it is not available it doesn't handle the error well. 

SMB has been a mess since the switch in 8.1, I personally don't consider the switch an upgrade and am left on 8.0.x on my production system because of all these undesirable "features".

### Server configuration
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**

**ownCloud version:** (see ownCloud admin page)
8.2.1

**Updated from an older ownCloud or fresh install:**
Updated

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
Enabled:
  - activity: 2.1.3
  - files: 1.2.0
  - files_external: 0.3.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - user_ldap: 0.7.0


**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system --public
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP/AD

#### LDAP configuration (delete this part if not used)

```
On ownCloud 7+ with access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

On ownCloud 6 with access to your command line run e.g.:
sqlite3 data/owncloud.db or mysql -u root -p owncloud
then execute:  select * from oc_appconfig where appid='user_ldap';

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query above.

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
+-------------------------------+--------------------------------------------------+
| Configuration                 |                                                  |
+-------------------------------+--------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                |
| hasPagedResultSupport         |                                                  |
| homeFolderNamingRule          |                                                  |
| lastJpegPhotoLookup           | 0                                                |
| ldapAgentName                 | CN=Own Cloud,OU=People,DC=hellriegel,DC=com      |
| ldapAgentPassword             | ***                                              |
| ldapAttributesForGroupSearch  |                                                  |
| ldapAttributesForUserSearch   |                                                  |
| ldapBackupHost                |                                                  |
| ldapBackupPort                |                                                  |
| ldapBase                      | DC=hellriegel,DC=com                             |
| ldapBaseGroups                | DC=hellriegel,DC=com                             |
| ldapBaseUsers                 | DC=hellriegel,DC=com                             |
| ldapCacheTTL                  | 600                                              |
| ldapConfigurationActive       | 1                                                |
| ldapEmailAttribute            |                                                  |
| ldapExperiencedAdmin          | 0                                                |
| ldapExpertUUIDGroupAttr       |                                                  |
| ldapExpertUUIDUserAttr        |                                                  |
| ldapExpertUsernameAttr        |                                                  |
| ldapGroupDisplayName          | cn                                               |
| ldapGroupFilter               | (&(|(objectclass=group)))                        |
| ldapGroupFilterGroups         |                                                  |
| ldapGroupFilterMode           | 0                                                |
| ldapGroupFilterObjectclass    | group                                            |
| ldapGroupMemberAssocAttr      | member                                           |
| ldapHost                      | srvdc01.hellriegel.com.                          |
| ldapIgnoreNamingRules         |                                                  |
| ldapLoginFilter               | (&(&(|(objectclass=user)))(samaccountname=%uid)) |
| ldapLoginFilterAttributes     |                                                  |
| ldapLoginFilterEmail          | 0                                                |
| ldapLoginFilterMode           | 0                                                |
| ldapLoginFilterUsername       | 1                                                |
| ldapNestedGroups              | 0                                                |
| ldapOverrideMainServer        |                                                  |
| ldapPagingSize                | 500                                              |
| ldapPort                      | 389                                              |
| ldapQuotaAttribute            |                                                  |
| ldapQuotaDefault              |                                                  |
| ldapTLS                       | 0                                                |
| ldapUserDisplayName           | displayName                                      |
| ldapUserFilter                | (&(|(objectclass=user)))                         |
| ldapUserFilterGroups          |                                                  |
| ldapUserFilterMode            | 0                                                |
| ldapUserFilterObjectclass     | user                                             |
| ldapUuidGroupAttribute        | auto                                             |
| ldapUuidUserAttribute         | auto                                             |
| turnOffCertCheck              | 0                                                |
| useMemberOfToDetectMembership | 1                                                |

### Client configuration
**Browser:**
Chrome/any

**Operating system:**
W8.1

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Exception: {"Exception":"Icewind\\SMB\\Exception\\Exception","Message":"Unknown error (16) for smb:\/\/srvdc01.hellriegel.com\/c$\/pagefile.sys","Code":16,"Trace":"
#0 \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/NativeState.php(72): Icewind\\SMB\\NativeState->handleError('smb:\/\/srvdc01.h...')\n
#1 \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/NativeState.php(180): Icewind\\SMB\\NativeState->testResult(false, 'smb:\/\/srvdc01.h...')\n
#2 \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/NativeShare.php(105): Icewind\\SMB\\NativeState->stat('smb:\/\/srvdc01.h...')\n
#3 \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/NativeShare.php(100): Icewind\\SMB\\NativeShare->getStat('\/pagefile.sys')\n
#4 \/var\/www\/owncloud\/apps\/files_external\/lib\/smb.php(102): Icewind\\SMB\\NativeShare->stat('\/pagefile.sys')\n
#5 \/var\/www\/owncloud\/apps\/files_external\/lib\/smb.php(272): OC\\Files\\Storage\\SMB->getFileInfo('pagefile.sys')\n
#6 \/var\/www\/owncloud\/lib\/private\/files\/storage\/common.php(91): OC\\Files\\Storage\\SMB->filetype('pagefile.sys')\n
#7 \/var\/www\/owncloud\/lib\/private\/files\/storage\/common.php(125): OC\\Files\\Storage\\Common->is_dir('pagefile.sys')\n
#8 \/var\/www\/owncloud\/lib\/private\/files\/storage\/common.php(149): OC\\Files\\Storage\\Common->isCreatable('pagefile.sys')\n
#9 \/var\/www\/owncloud\/lib\/private\/files\/storage\/common.php(611): OC\\Files\\Storage\\Common->getPermissions('pagefile.sys')\n
#10 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(562): OC\\Files\\Storage\\Common->getMetaData('pagefile.sys')\n
#11 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(562): OC\\Files\\Storage\\Wrapper\\Wrapper->getMetaData('pagefile.sys')\n
#12 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/availability.php(456): OC\\Files\\Storage\\Wrapper\\Wrapper->getMetaData('pagefile.sys')\n
#13 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/encryption.php(147): OC\\Files\\Storage\\Wrapper\\Availability->getMetaData('pagefile.sys')\n
#14 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(562): OC\\Files\\Storage\\Wrapper\\Encryption->getMetaData('pagefile.sys')\n
#15 \/var\/www\/owncloud\/lib\/private\/files\/cache\/scanner.php(114): OC\\Files\\Storage\\Wrapper\\Wrapper->getMetaData('pagefile.sys')\n
#16 \/var\/www\/owncloud\/lib\/private\/files\/cache\/scanner.php(142): OC\\Files\\Cache\\Scanner->getData('pagefile.sys')\n
#17 \/var\/www\/owncloud\/lib\/private\/files\/cache\/scanner.php(345): OC\\Files\\Cache\\Scanner->scanFile('pagefile.sys', 3, 162414, NULL, true)\n
#18 \/var\/www\/owncloud\/lib\/private\/files\/cache\/scanner.php(268): OC\\Files\\Cache\\Scanner->scanChildren('', false, 3, Array, true)\n
#19 \/var\/www\/owncloud\/lib\/private\/files\/cache\/watcher.php(103): OC\\Files\\Cache\\Scanner->scan('', false)\n
#20 \/var\/www\/owncloud\/lib\/private\/files\/view.php(1207): OC\\Files\\Cache\\Watcher->update('', Array)\n
#21 \/var\/www\/owncloud\/lib\/private\/files\/filesystem.php(861): OC\\Files\\View->getFileInfo('\/SRVDC01-C$', true)\n
#22 \/var\/www\/owncloud\/apps\/files\/ajax\/list.php(34): OC\\Files\\Filesystem::getFileInfo('\/SRVDC01-C$')\n
#23 \/var\/www\/owncloud\/lib\/private\/route\/route.php(154) : runtime-created function(1): require_once('\/var\/www\/ownclo...')\n
#24 [internal function]: __lambda_func(Array)\n
#25 \/var\/www\/owncloud\/lib\/private\/route\/router.php(282): call_user_func('?lambda_837', Array)\n
#26 \/var\/www\/owncloud\/lib\/base.php(851): OC\\Route\\Router->match('\/apps\/files\/aja...')\n
#27 \/var\/www\/owncloud\/index.php(39): OC::handleRequest()\n
#28 {main}","File":"\/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/NativeState.php","Line":66} 
```
#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by Xenopathic** [comment]
cc @icewind1991

**Comment by PVince81** [comment]
Unknown error 16, @icewind1991 what is that ?

**Comment by icewind1991** [comment]
> Unknown error 16, @icewind1991 what is that ?

"Device or resource busy"

**Comment by PVince81** [comment]
@jrh7675 please try again with 8.2.6 or 9.0.3 and make sure that you have at least Samba 4.2 and the PHP module "php5-libsmbclient" enabled.

If the problem persists, please reopen.
