### ISSUE TITLE
Service is brocken after fail run the updater from 8.1.4 to 8.2.1

### ISSUE THREAD

**Issue by caroloat** [owncloud/core#20655]
As a message of a new version was promted i did the procedure
1) Go to admin  2) Clic on Update ( I have the server in spanish)
3) A new page present information about the backup
4)  Upgrading owncloud to 8.2.1 can take a while (but in spanish)
After that this messages appears

  >Stablis register lever to debuggin/Maintenance mode activated (in spanish)
  >Exception: Updates between multiple major versions and downgrades are unsupported.
 >The update was unsuccessful. Please report this issue to the ownCloud community.

As the maintenace mode is active when i try to connect to the server again using

http://MYDOMAIN/owncloud/index.php

Instead login, i was directed to the same warning page, in other words  "i lost my owncloud service", where are my files how i retrieve them?, how i back again to 8.1.4 or solve the issue.?

**Comment by RealRancor** [comment]
@caroloat Sure you had 8.1.4 installed previously? Could you post the config.php like described in the issue template:

https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version

**Comment by MorrisJobke** [comment]
This looks like you installed a older version rather than a newer version. Please reopen once you have the exact steps and verified, that you not copied over an older version or skipped a major version before the upgrade to 8.2.x (only following upgrade path is allowed 7.0 -> 8.0 -> 8.1 -> 8.2)
