### ISSUE TITLE
Unable to restore shared folder to user who deleted shared folder

### ISSUE THREAD

**Issue by syzdek** [owncloud/core#20653]
OwnCloud: 8.2.1

I have a user1 which has shared a folder called folder1 with group1 and group2.  User2 accidentally deleted "folder1" using the webUI.  "folder1" does not appear in the deleted items or under "Shared with you".  When user1 shares folder1 with user2 directly, it still does not appear in User2's Files view.

Is there a way to restore a deleted share?

**Comment by karlitschek** [comment]
Please ask questions like that in the owncloud forum or via some of the other support channels at owncloud.org/support
Thanks
