### ISSUE TITLE
Transactional File Locking with redis that uses authentification doesn't work

### ISSUE THREAD

**Issue by beingalink** [owncloud/core#20652]
According to the [documentation](https://doc.owncloud.org/server/8.2/admin_manual/configuration_files/files_locking_transactional.html) I'm using following redis config:
```
'filelocking.enabled' => 'true',
'memcache.locking' => '\OC\Memcache\Redis',
'redis' => array(
     'host' => 'redis_docker',
     'port' => 6379,
     'timeout' => 0.0,
     'password' => 'mypass', // Optional, if not defined no password will be used.
      ),
```
When I try to upload a file with this config I get following error message in owncloud: `Failed to AUTH connection`.

If I remove the password from my redis config, everything works fine. I'm using redis 3.0.5.

**Comment by karlitschek** [comment]
@icewind1991

**Comment by RealRancor** [comment]
@karlitschek This is only available in 9.0 https://github.com/owncloud/core/pull/20193 and wasn't backported to 8.2. Seems the documentation was just accidentally published for 8.2 in https://github.com/owncloud/documentation/commit/811f6c32ffe045ad01bc28ff0190b7d2ef904b9d#diff-5135beeb0f35226ece9b5053d4262ba5R44

**Comment by PVince81** [comment]
It looks like a trivial fix, maybe backporting is quicker than just updating the documentation ?
@karlitschek

**Comment by karlitschek** [comment]
@pvince81 agreed

**Comment by PVince81** [comment]
@beingalink if you feel adventurous, you could try with this patch: https://github.com/owncloud/core/pull/20690

**Comment by beingalink** [comment]
@PVince81 this patch seems to work fine. Thank you all for handling this so quick! :)

**Comment by PVince81** [comment]
Reopening, the PR hasn't been merged yet.

**Comment by PVince81** [comment]
PR was merged, closing
