### ISSUE TITLE
Thunderbird CardBook sync failure OC 8.2.1 Contacts 0.5.0.0

### ISSUE THREAD

**Issue by fonzmike** [owncloud/core#20658]
Hi OC,

since update to 8.2.1 and Contacts 0.5.0.0 Thunderbird Cardbook plugin fails to sync contacts (HTTP 404).

OC is great!

Thanks in advance,

Michael

Log output:
2015.11.21 12:34:52:237 : ocKontakte : No discovery
2015.11.21 12:34:52:238 : ocKontakte : Searching ctag...
2015.11.21 12:34:54:705 : ocKontakte : Ctag request finished, status : 207
2015.11.21 12:34:54:705 : ocKontakte : Ctag found : 1444145551
2015.11.21 12:34:54:706 : ocKontakte : Searching cards...
2015.11.21 12:34:55:048 : ocKontakte : Cards request finished, status : 207
2015.11.21 12:34:55:576 : ocKontakte : Can not get https://apps.xxxxxx.de/oc/remote.php/carddav/addressbooks/michael/kontakte/oCRFnz24AAAI3AAAB.vcf (status : 404)
2015.11.21 12:34:55:745 : ocKontakte : Can not get https://apps.xxxxxx.de/oc/remote.php/carddav/addressbooks/michael/kontakte/oCRFnz24AAAI3CwAAAA%3d%3d.vcf (status : 404)

**Comment by RealRancor** [comment]
@fonzmike Please close here and re-open in the issue tracker of the contacts app:

https://github.com/owncloud/contacts/issues

Please make also sure that you're using the issue template (for this and further reported issues) which is provided here: https://github.com/owncloud/contacts/blob/master/CONTRIBUTING.md#short-version

**Comment by RealRancor** [comment]
Might be also related to https://github.com/owncloud/contacts/issues/1103
