### ISSUE TITLE
https://github.com/owncloud/core/issues/18755 is still an issue

### ISSUE THREAD

**Issue by lexpierce** [owncloud/core#20651]
If you don't understand how OC is checking that the directory is writeable (touch a dot file/  REALLY?!?!?!?!) the script will change ownership back.  If you don't usually use chmod -R, and see there is nothing in the directory, debugging is hard. `lib/private/template.php` could really be updated to have a little more robust way of checking writeability.

**Comment by Xenopathic** [comment]
Keep it in the original issue please.
