### ISSUE TITLE
Downgrading is not supported and is likely to cause unpredictable issues (from 8.2.1.4 to 8.2.0.12)

### ISSUE THREAD

**Issue by satarsa** [owncloud/core#20657]
Hello
I updated owncloud from 8.2.0 to 8.2.1 using gentoo package manager emerge. When I try to login, I get the message:
"Downgrading is not supported and is likely to cause unpredictable issues (from 8.2.1.4 to 8.2.0.12)"

The workaround is to change in config/version.php 'version' from 8.2.1.4 to 8.2.0.12, then it works.

**Comment by RealRancor** [comment]
@satarsa Could you make sure that the gentoo packages are not broken and have actually done this downgrade from 8.2.1 to 8.2.0?

**Comment by satarsa** [comment]
Surely, I have version 8.2.1. Here is my version.php:
```php
<?php
$OC_Version = array(8,2,1,4);
$OC_VersionString = '8.2.1';
$OC_Edition = '';
$OC_Channel = 'stable';
$OC_VersionCanBeUpgradedFrom = array(8,1);
$OC_Build = '2015-11-17T16:38:22+00:00 8f71705c2ec73d396ff8178f088661c3a20988b0';
```
After upgrade, I cleaned owncloud-8.2.0 with emerge -C, thus it cannot be anywhere in the system.

**Comment by satarsa** [comment]
The problem seems to be gone mystically! I restarted php-fpm, nginx, redis many times, then owncloud showed its standard upgrade page, upgraded everything (as usual db scheme, etc),  and now it works fine.

**Comment by Xenopathic** [comment]
This was likely an issue with PHP recompilation of scripts. You might want to check the value of `opcache.revalidate_freq` in php.ini. It's useful as a [performance booster](https://mccorkell.me.uk/article/performance-tuning), but can cause issues like this

**Comment by satarsa** [comment]
Yes, probably it is a good idea to switch off the opcache option ahead the update.
