### ISSUE TITLE
Can't change languages (OC 8.2.x)

### ISSUE THREAD

**Issue by IzK666** [owncloud/core#20666]
Hi!
I'm having troubles changing languages on OC 8.2.0 and 8.2.1.
I can select the language I want, but it's applied only when spanish or english is selected. Otherwise, the last one used is applied.
In the database the language is changed correctly.

I'm using Firefox and Chrome, and both had the issue.
I have tried a clean install (installing OC on a new folder and creating a new database), with the same results.

**Comment by MorrisJobke** [comment]
@IzK666 Can you take a screenshot of how it looks like in the personal page?

Maybe related to #20346

**Comment by IzK666** [comment]
![french](https://cloud.githubusercontent.com/assets/2158443/11344811/c131ce02-9213-11e5-9fd1-a619daafd0f4.PNG)
![italian](https://cloud.githubusercontent.com/assets/2158443/11344812/c1341144-9213-11e5-94b9-8e9bd14b2b9a.PNG)

To take both screenshots, I changed the language on the personal page and once the page is reloaded I have updated the sql query. The current user is "izk".

**Comment by MorrisJobke** [comment]
The only language related change (I know of) that went into 8.2.1 is https://github.com/owncloud/core/pull/20346 and can't trigger this behavior.

@nickvergessen Maybe you have an idea here.

**Comment by nickvergessen** [comment]
Can reproduce, the language is overwriten by the ones send with the accept-language headers of the browser. I don't have russian in that header, so selecting russion will result in german pages.

**Comment by nickvergessen** [comment]
Also @MorrisJobke https://github.com/owncloud/core/commits/master/lib/private/l10n.php there have been some more changes

**Comment by lookshe** [comment]
I can confirm that the change of the language depends on the accept-language header of the browser. In the files app the selected language from the account is used. Everything else is different.
How useful is the posibility to change set the language in the account settings, if this setting is not used?

**Comment by nickvergessen** [comment]
@PVince81 should put this on the list

**Comment by PVince81** [comment]
Are we sure the "accept-language" stuff worked in 8.1 and before ? (confirm the regression)

CC @cmonteroluque for 8.2.2

**Comment by nickvergessen** [comment]
its a regression, previously we didn't use the header on each request, but the setting of the user...

**Comment by MorrisJobke** [comment]
This will be fixed in 8.2.2 and 9.0.0
