### ISSUE TITLE
copySkeleton should not copy the content of links

### ISSUE THREAD

**Issue by alvaroaleman** [owncloud/core#20664]
When the skeleton folder contains a softlink on a directory, the whole content of that directory gets copied over on user creation by [copySkeleton](https://github.com/owncloud/core/blob/427d107b9f375f5667a3e8f40191edd46924fdb8/lib/private/util.php#L294). This should not happen, instead the link should be copied as link.

Demonstration:

```bash
mkdir /companydata
dd if=/dev/zero of=/companydata/bigfile bs=1024 count=10000000
ln -s /companydata /var/www/owncloud/core/skeleton/companydata
```

This causes the whole 10GiB file to be copied on user creation. Instead, it should copy just the link.

This behaviour is caused by [copyr](https://github.com/owncloud/core/blob/427d107b9f375f5667a3e8f40191edd46924fdb8/lib/private/util.php#L317) having a ``is_dir`` but no ``is_link`` check.

**Comment by karlitschek** [comment]
softlinks in the ownCloud data directory are not supported in the first place. This will create a lot of problems. Sorry. No bug.

**Comment by alvaroaleman** [comment]
Could you elaborate on that or point me to the place in the docs where I can find info about this?

**Comment by RealRancor** [comment]
@alvaroaleman Little bit hidden but it's there: https://doc.owncloud.org/server/8.2/admin_manual/release_notes.html#owncloud-does-not-follow-symlinks
