### ISSUE TITLE
Another open_basedir issue?

### ISSUE THREAD

**Issue by hoorna** [owncloud/core#20669]
I have discovered two other strange issues with the open_basedir error-messages (see also #20621):

{"reqId":"GXUcwdxkVGWgHw\/9PpTp","remoteAddr":"192.168.2.1","app":"PHP","message":"is_dir(): open_basedir restriction in effect. File(\/var\/services\/homes) is not within the allowed path(s): (\/etc.defaults:\/etc:\/usr\/syno\/synoman:\/tmp:\/var\/services\/tmp:\/var\/services\/web:\/var\/services\/homes:\/dev\/urandom) at \/volume1\/web\/owncloud\/3rdparty\/symfony\/process\/Symfony\/Component\/Process\/ExecutableFinder.php#59","level":3,"time":"2015-11-19T17:25:28+01:00"}

* First, if you look in the allowed paths in open_basedir you can see that /var/services/homes is in open_basedir. So, why is owncloud complaining that /var/services/homes is not within it?
* Next, when I delete /var/services/homes from open_basedir, the error-rmessage disappears. This seems also strange to me because in this case /var/services/homes is not with the paths of open_basedir. Just in this situation I should expect that owncloud complains about the absence of /var/services/homes in open_basedir, but owncloud is not.

Is it a problem in owncloud? From what I understand in the owncloud-code in /owncloud\/3rdparty\/symfony\/process\/Symfony\/Component\/Process\/ExecutableFinder.php is that this code is using open_basedir and checks all the subdirectories in open_basedir one by one. I am using PHP version 5.5.30 in a Synology Diskstation (latest firmware).

**Comment by Xenopathic** [comment]
You are hitting a known PHP bug: https://bugs.php.net/bug.php?id=69240

There is a patch in Symfony Process, but it's only been released on the 2.7 and 2.3 branches so far, so unless we upgrade to Symfony Process 2.7.6, we need to wait for a point release on the 2.6 branch with the fix.

**Comment by MorrisJobke** [comment]
> There is a patch in Symfony Process, but it's only been released on the 2.7 and 2.3 branches so far, so unless we upgrade to Symfony Process 2.7.6, we need to wait for a point release on the 2.6 branch with the fix.

@DeepDiver1975 Should we then upgrade Symfony Process?

**Comment by rullzer** [comment]
I'm in the process of upgrading most of the symfony packages. I can do symfony/process next.

**Comment by hoorna** [comment]
Thanks for your serious attention to this issue!

**Comment by rullzer** [comment]
Latest symfony/process is now in master.

**Comment by hoorna** [comment]
Great!
