### ISSUE TITLE
[OC 8.2.1] Sidebar shared file no filesize is displayed

### ISSUE THREAD

**Issue by MegaV0lt** [owncloud/core#20667]
when viewing via "shared" link on the left
![2015-11-22 13_27_41-von ihnen geteilt - owncloud](https://cloud.githubusercontent.com/assets/2804301/11323774/27cbfb6c-911d-11e5-8b7f-163d752a1d12.png)

But is working in standard files view
![2015-11-22 13_32_50-tools - dateien - owncloud](https://cloud.githubusercontent.com/assets/2804301/11323786/9bb7b87c-911d-11e5-9313-04408bd08e72.png)

**Comment by karlitschek** [comment]
@PVince81

**Comment by PVince81** [comment]
Yeah, this information is not available from the OCS API.

The "solution" for now is to hide the field.

**Comment by MegaV0lt** [comment]
Hiding the filesize can not be the solution. The size is a basic information.

**Comment by PVince81** [comment]
This is the prerequisite: https://github.com/owncloud/core/issues/8792

**Comment by PVince81** [comment]
This will be fixed in 10.0 through https://github.com/owncloud/core/pull/26603
