### ISSUE TITLE
Updating ownCloud to version 8.2.1

### ISSUE THREAD

**Issue by xenographer** [owncloud/core#20660]
Updating ownCloud to version 8.2.1, this may take a while.

Preparing update
Set log level to debug - current level: "Warning"
Turned on maintenance mode
Exception: Updates between multiple major versions and downgrades are unsupported.
The update was unsuccessful. Please report this issue to the ownCloud community.

Going from 8.0.3 (I think) -> 8.2.1. I can't check current version, because every time I load my instance, it goes straight to the 'start update' screen. Anyone can help?

**Comment by RealRancor** [comment]
Hi,

8.0.3 to 8.2.1 is unsupported as the message is telling you. You can close here and do the following upgrade steps:

8.0.3 -> 8.0.9 -> 8.1.4 -> 8.2.1

as also discussed in this duplicate issue: https://github.com/owncloud/core/issues/20640

**Comment by xenographer** [comment]
Yes, just searched and found duplicate: https://github.com/owncloud/core/issues/20640

So a manual upgrade is the only way?

**Comment by RealRancor** [comment]
Either a manual upgrade or if https://github.com/owncloud/appstore-issues/issues/4 finally gets fixed after more than a year.

**Comment by xenographer** [comment]
Thanks for your help!
