### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by JanSladic** [owncloud/core#20661]
This issue detected:
Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO oc_appconfig (appid, configkey, configvalue) SELECT appid, configkey, configvalue FROM __temp__oc_appconfig': SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: oc_appconfig.appid

**Comment by RealRancor** [comment]
@JanSladic Please fill out the issue template provided here:

https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version

as asked in the "guidelines for contributing" (linked at the yellow box when creating a new issue).

In your report even the basic infos like used oC version etc. is missing.

**Comment by MorrisJobke** [comment]
I'm closing this issue as it is missing essential information. Feel free to reopen if you have the missing information. Thanks
