### ISSUE TITLE
8.2.1 Activity App, "Favorites" and "All" showing same data

### ISSUE THREAD

**Issue by plabong** [owncloud/core#20671]
oc 8.2.1 -- Activity App:
Click on "all Activities" or "Favorites" givin the same picture (-> all Activities)

**Comment by karlitschek** [comment]
please post a full bug report using the issue template https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by MorrisJobke** [comment]
And please open this in the activity app bug tracker: https://github.com/owncloud/activity/issues

Thanks
