### ISSUE TITLE
wrong video link in "shared by url" shares

### ISSUE THREAD

**Issue by krodelabestiole** [owncloud/core#20676]
i can download but not stream videos in these shared directories...
both VideoJS Sublime and HTML5 Video Player are trying to load a wrong url and get a 404 :
> index.php/apps/files/ajax/download.php?dir=%2F&files=file.mp4

i guess location should be something like
> index.php/s/23d5DdPfdsDs4Z3L/download?path=%2F&files=file.mp4

i'm not sure the problem comes from the core though, a fix might be needed in the video apps, but i post here because both apps show the issue, and i guess they have to get this wrong url from somewhere

**Comment by MorrisJobke** [comment]
cc @PVince81 

With current master they try the webdav URL


How to test:

* activate VideoJS-sublime
* share a folder by link (needs to contain a video file)
* open the link
* click the video - current master tries webdav (but with the wrong folder subpath and older versions try the wrong URL)

The weird thing is: The gallery app also uses the download.php URL and it works :see_no_evil: 

https://github.com/Instagit/videojs-sublime

**Comment by PVince81** [comment]
Hmm, maybe `getDownloadUrl` is wrong in the public page since the move to Webdav.

**Comment by MorrisJobke** [comment]
> Hmm, maybe getDownloadUrl is wrong in the public page since the move to Webdav.

Yes and no. Because it also didn't worked before (so it went from a broken state to another broken state)

**Comment by PVince81** [comment]
@krodelabestiole which ownCloud version are you using ?

**Comment by krodelabestiole** [comment]
sorry i forgot to specify : ownCloud 8.1.4 (stable) on debian

**Comment by PVince81** [comment]
Please try again with 8.1.8, 8.2.6 or 9.0.3. It should now use the correct download.php link
