### ISSUE TITLE
Unable to update shared file if own quota is reached

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#20686]
* having two users "userA" (no quota limit) and "userB" (0 Byte quota)
* share file "shared.txt" from "userA" to "userB"
* userB cannot update "welcome.txt" in it's root, but userB can update "shared.txt" (shared file from userA) - this works in the web UI (with file text editor because it doesn't use webdav and **via client/webdav it fails**)

Also reproducible via curl:
```
$ curl -X PUT -u userB:userB -i -H "Content-Type: text/plain" -d "test123" http://localhost/master/remote.php/webdav/shared.txt

HTTP/1.1 507 Insufficient Storage
Date: Mon, 23 Nov 2015 14:41:36 GMT
Server: Apache/2.4.16 (Unix) PHP/5.6.14
X-Powered-By: PHP/5.6.14
Set-Cookie: ocamsbuzhv8d=q86p48sdlnt0o2op37lmnl97k4; path=/master; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Set-Cookie: oc_sessionPassphrase=xnrqDqLxNtIl%2B50M8yhIMweqsMuJZ7eBig4cXffyUhCQzV6tO5lCFxWYohi7sm0fhQithuXMD96MMTUzc6qnl1phNdlU4iaRpWpSMv%2FSKsJFhgbWaKJG%2FTcZAtrjOpSP; path=/master; httponly
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Robots-Tag: none
X-Frame-Options: SAMEORIGIN
Content-Length: 192
Content-Type: application/xml; charset=utf-8

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\InsufficientStorage</s:exception>
  <s:message/>
</d:error>
```

@PVince81 @icewind1991 

cc @felixboehm 

ref https://github.com/owncloud/client/issues/4114

**Comment by MorrisJobke** [comment]
@DeepDiver1975 @SergioBertolinSG @nickvergessen Is it worth to write a smashbox test for this case? Or should there be a behat test?

**Comment by PVince81** [comment]
Original report is for OC server 8.1.3.

**Comment by MorrisJobke** [comment]
I tested this with todays master

**Comment by nickvergessen** [comment]
well there is no api to set quota, is there?

anyway I think behat is better for this

**Comment by PVince81** [comment]
Provisioning API should be able to set the quota, at least with 9.0 I believe

**Comment by felixboehm** [comment]
@MorrisJobke Please let me know if we can get this fixed soon.

**Comment by MorrisJobke** [comment]
> @MorrisJobke Please let me know if we can get this fixed soon.

I have written a behat test that reproduces the issue https://github.com/owncloud/core/pull/20876 - now engineering can work on this.

**Comment by bboule** [comment]
Guys next steps?

@felixboehm @MorrisJobke

**Comment by MorrisJobke** [comment]
> Guys next steps?

@cmonteroluque Someone needs to have a look at my provided test that reproduces this issue and fix the cause. :see_no_evil:

**Comment by cmonteroluque** [comment]
@bboule @MorrisJobke Currently on the 9.0 timeframe. Is there a reason to accelerate this? Reassigning to @schiesbn

**Comment by PVince81** [comment]
Ah yes of course, it's because it checks the quota of the containing folder.
Shared files are somewhat special...

**Comment by PVince81** [comment]
- [ ] In the web UI: free space in current folder is 0 (stored in a JS variable), so it disallows upload without even trying. Ideally the web UI should always try and upload and let the server decide whether there is enough space. (we certainly don't want to add extra magic for the magic shared files)
- [ ] In Webdav: the quota plugin prevents uploading and checks the parent folder, might be adjustable to make sure the target file isn't a shared file when checking.
- [ ] other: there might be other places where the quota is checked that need adjusting

Non-trivial task.

**Comment by PVince81** [comment]
Arghh, this is even more tricky: when uploading to "user1/files/shared.txt" the shared file, it will first create a part file in "user1/files/shared.txt-$transactionId.part" which is actually on the uploader's storage, not the target user's storage. So the quota check is done on the wrong storage.

**Comment by PVince81** [comment]
Looks like this logic will need to be adjusted: https://github.com/owncloud/core/blob/master/apps/dav/lib/connector/sabre/file.php#L120 when computing `$partStorage`

**Comment by PVince81** [comment]
@icewind1991 any reason why we are doing a cross-storage move here 06a65fab13fca510cbc5213d3353335046ba9445 instead of putting the part file directly on the target storage ? I was thinking of making `$partStorage = $storage` but maybe that did not work back then ?

**Comment by PVince81** [comment]
I started something here https://github.com/owncloud/core/pull/21610 but will need a lot more work to cover all code paths.

**Comment by MorrisJobke** [comment]
@cmonteroluque @PVince81 We have a green sev2 ticket here. I provided a test case that covers this and therefore is a no brainer on the reproduction steps. Could we get some traction in here. Sadly I'm not capable to properly debug this.

Maybe @icewind1991 or @schiesbn could have a look.

**Comment by PVince81** [comment]
@icewind1991 I need your advice how to move forward with my PR https://github.com/owncloud/core/pull/21610

**Comment by PVince81** [comment]
Maybe the code checker should find such issues: https://github.com/owncloud/core/issues/22420

**Comment by PVince81** [comment]
The fix was merged, close ?

**Comment by MorrisJobke** [comment]
> The fix was merged, close ?

The test fails :(

```
  Scenario: Upload forbidden if quota is 0                              # /ssd/jenkins/workspace/ocs-api-integration-tests-ci/build/integration/features/sharing-v1.feature:499
    Given using dav path "remote.php/webdav"                            # FeatureContext::usingDavPath()
    And As an "admin"                                                   # FeatureContext::asAn()
    And user "user0" exists                                             # FeatureContext::assureUserExists()
    And user "user1" exists                                             # FeatureContext::assureUserExists()
    And user "user1" has a quota of "0"                                 # FeatureContext::userHasAQuotaOf()
    And User "user0" moved file "/welcome.txt" to "/myfile.txt"         # FeatureContext::userMovedFile()
    And file "myfile.txt" of user "user0" is shared with user "user1"   # FeatureContext::assureFileIsShared()
    When User "user1" uploads file "data/textfile.txt" to "/myfile.txt" # FeatureContext::userUploadsAFileTo()
    Then the HTTP status code should be "201"                           # FeatureContext::theHTTPStatusCodeShouldBe()
      Failed asserting that 204 matches expected '201'.
```

**Comment by PVince81** [comment]
201 is "created", 204 is "no content".

201 is only when uploading brand new files I believe.
204 is when overwriting files.

Can you check ? Do you also get 204 is you remove the quota limit ?

**Comment by MorrisJobke** [comment]
@PVince81 Correct. I updated the PR and we will see.

**Comment by MorrisJobke** [comment]
Yes fixed -> closing.
