### ISSUE TITLE
error to update version 8.1 to 8.2.1

### ISSUE THREAD

**Issue by mgdiaspan** [owncloud/core#20683]
I performed the update through their own page owncloud , however at the time you start the upgrade displays the error :

![image](https://cloud.githubusercontent.com/assets/8422303/11337876/824cebd6-91d7-11e5-88ad-87ef2cd5e621.png)

After clicking start update:

![image](https://cloud.githubusercontent.com/assets/8422303/11337897/b44abc80-91d7-11e5-97f4-c57145aaa58d.png)

I'm waiting for a solution.

**Comment by karlitschek** [comment]
Please ask this question on one of the support channels listed at owncloud.org/support. Thanks a lot.

**Comment by RealRancor** [comment]
@karlitschek Thats one example why https://github.com/owncloud/appstore-issues/issues/4 should be implemented. After the release of 8.2.1 via the updater a lot of people have tried to directly upgrade from 8.0 to 8. :see_no_evil:
