### ISSUE TITLE
Problems upgrading ownCloud 8.1.1 (@isv_ownCloud_community)

### ISSUE THREAD

**Issue by maxferrario-msf** [owncloud/core#20687]
Hi,
I am running Owncloud 8.1.1 on a server administrated by me. The server is running Centos 7 and I originally installed Owncloud via yum packet mananger using this repository config:

    $ cat /etc/yum.repos.d/isv\:ownCloud\:community.repo
    [isv_ownCloud_community]
    name=Latest stable community release of ownCloud (CentOS_CentOS-7)
    type=rpm-md
    baseurl=http://download.opensuse.org/repositories/isv:/ownCloud:/community/CentOS_CentOS-7/
    gpgcheck=1
    gpgkey=http://download.opensuse.org/repositories/isv:/ownCloud:/community/CentOS_CentOS-7/repodata/repomd.xml.key
    enabled=1

My problem is that I'm not able to upgrade owncloud anymore (something that I've done a couple of times in the last year or so).
This is what I see when I try to update owncloud (I've added ==> to the lines where I see an error):

	$ yum update
	Loaded plugins: fastestmirror, refresh-packagekit, replace, security
	Setting up Update Process
	Loading mirror speeds from cached hostfile
	 * base: it.centos.contactlab.it
	 * epel: mirror.23media.de
	 * extras: it.centos.contactlab.it
	 * ius: mirror.amsiohosting.net
	 * updates: it.centos.contactlab.it
	 * webtatic: uk.repo.webtatic.com
	Resolving Dependencies
	--> Running transaction check
	---> Package owncloud-3rdparty.noarch 0:8.1.1-12.1 will be obsoleted
	---> Package owncloud-app-activity.noarch 0:8.1.1-12.1 will be obsoleted
	---> Package owncloud-app-encryption.noarch 0:8.1.1-12.1 will be obsoleted
	---> Package owncloud-app-external.noarch 0:8.1.1-12.1 will be obsoleted
	---> Package owncloud-app-files.noarch 0:8.1.1-12.1 will be obsoleted
	---> Package owncloud-app-files_external.noarch 0:8.1.1-12.1 will be obsoleted
	---> Package owncloud-app-files_locking.noarch 0:8.1.1-12.1 will be obsoleted
	---> Package owncloud-app-files_pdfviewer.noarch 0:8.1.1-12.1 will be obsoleted
	---> Package owncloud-app-files_sharing.noarch 0:8.1.1-12.1 will be obsoleted
	---> Package owncloud-app-files_texteditor.noarch 0:8.1.1-12.1 will be obsoleted
	---> Package owncloud-app-files_trashbin.noarch 0:8.1.1-12.1 will be obsoleted
	---> Package owncloud-app-files_versions.noarch 0:8.1.1-12.1 will be obsoleted
	---> Package owncloud-app-files_videoviewer.noarch 0:8.1.1-12.1 will be obsoleted
	---> Package owncloud-app-firstrunwizard.noarch 0:8.1.1-12.1 will be obsoleted
	---> Package owncloud-app-gallery.noarch 0:8.1.1-12.1 will be obsoleted
	---> Package owncloud-app-provisioning_api.noarch 0:8.1.1-12.1 will be obsoleted
	---> Package owncloud-app-templateeditor.noarch 0:8.1.1-12.1 will be obsoleted
	---> Package owncloud-app-user_external.noarch 0:8.1.1-12.1 will be obsoleted
	---> Package owncloud-app-user_ldap.noarch 0:8.1.1-12.1 will be obsoleted
	---> Package owncloud-app-user_webdavauth.noarch 0:8.1.1-12.1 will be obsoleted
	---> Package owncloud-server.noarch 0:8.1.1-12.1 will be updated
	---> Package owncloud-server.noarch 0:8.1.4-12.1 will be obsoleting
	--> Finished Dependency Resolution

	Dependencies Resolved

	===================================================================================================================================
	 Package                         Arch                   Version                       Repository                              Size
	===================================================================================================================================
	Installing:
	 owncloud-server                 noarch                 8.1.4-12.1                    isv_ownCloud_community                  24 M
			 replacing  owncloud-3rdparty.noarch 8.1.1-12.1
			 replacing  owncloud-app-activity.noarch 8.1.1-12.1
			 replacing  owncloud-app-encryption.noarch 8.1.1-12.1
			 replacing  owncloud-app-external.noarch 8.1.1-12.1
			 replacing  owncloud-app-files.noarch 8.1.1-12.1
			 replacing  owncloud-app-files_external.noarch 8.1.1-12.1
			 replacing  owncloud-app-files_locking.noarch 8.1.1-12.1
			 replacing  owncloud-app-files_pdfviewer.noarch 8.1.1-12.1
			 replacing  owncloud-app-files_sharing.noarch 8.1.1-12.1
			 replacing  owncloud-app-files_texteditor.noarch 8.1.1-12.1
			 replacing  owncloud-app-files_trashbin.noarch 8.1.1-12.1
			 replacing  owncloud-app-files_versions.noarch 8.1.1-12.1
			 replacing  owncloud-app-files_videoviewer.noarch 8.1.1-12.1
			 replacing  owncloud-app-firstrunwizard.noarch 8.1.1-12.1
			 replacing  owncloud-app-gallery.noarch 8.1.1-12.1
			 replacing  owncloud-app-provisioning_api.noarch 8.1.1-12.1
			 replacing  owncloud-app-templateeditor.noarch 8.1.1-12.1
			 replacing  owncloud-app-user_external.noarch 8.1.1-12.1
			 replacing  owncloud-app-user_ldap.noarch 8.1.1-12.1
			 replacing  owncloud-app-user_webdavauth.noarch 8.1.1-12.1

	Transaction Summary
	===================================================================================================================================
	Install       1 Package(s)

	Total download size: 24 M
	Is this ok [y/N]: y
	Downloading Packages:
	owncloud-server-8.1.4-12.1.noarch.rpm                                                                       |  24 MB     00:23
	Running rpm_check_debug
	Running Transaction Test
	Transaction Test Succeeded
	Running Transaction
	owncloud-server: Upgrade starting
	owncloud-server: occ maintenance:mode --on
	Maintenance mode enabled
	==> /var/tmp/rpm-tmp.oDgFJu: line 12: /run/occ_maintenance_mode_during_owncloud_install: No such file or directory
	==> error: %pre(owncloud-server-8.1.4-12.1.noarch) scriptlet failed, exit status 1
	==> Error in PREIN scriptlet in rpm package owncloud-server-8.1.4-12.1.noarch
	==> error:   install: %pre scriptlet failed (2), skipping owncloud-server-8.1.4-12.1
	owncloud-app-external-8.1.1-12.1.noarch was supposed to be removed but is not!
		Verifying  : owncloud-app-external-8.1.1-12.1.noarch                                                                        1/22
	owncloud-app-provisioning_api-8.1.1-12.1.noarch was supposed to be removed but is not!
		Verifying  : owncloud-app-provisioning_api-8.1.1-12.1.noarch                                                                2/22
	owncloud-app-encryption-8.1.1-12.1.noarch was supposed to be removed but is not!
		Verifying  : owncloud-app-encryption-8.1.1-12.1.noarch                                                                      3/22
	owncloud-app-user_ldap-8.1.1-12.1.noarch was supposed to be removed but is not!
		Verifying  : owncloud-app-user_ldap-8.1.1-12.1.noarch                                                                       4/22
	owncloud-app-files_videoviewer-8.1.1-12.1.noarch was supposed to be removed but is not!
		Verifying  : owncloud-app-files_videoviewer-8.1.1-12.1.noarch                                                               5/22
	owncloud-app-files_sharing-8.1.1-12.1.noarch was supposed to be removed but is not!
		Verifying  : owncloud-app-files_sharing-8.1.1-12.1.noarch                                                                   6/22
	owncloud-app-files-8.1.1-12.1.noarch was supposed to be removed but is not!
		Verifying  : owncloud-app-files-8.1.1-12.1.noarch                                                                           7/22
	owncloud-app-files_trashbin-8.1.1-12.1.noarch was supposed to be removed but is not!
		Verifying  : owncloud-app-files_trashbin-8.1.1-12.1.noarch                                                                  8/22
	owncloud-app-files_versions-8.1.1-12.1.noarch was supposed to be removed but is not!
		Verifying  : owncloud-app-files_versions-8.1.1-12.1.noarch                                                                  9/22
	owncloud-app-firstrunwizard-8.1.1-12.1.noarch was supposed to be removed but is not!
		Verifying  : owncloud-app-firstrunwizard-8.1.1-12.1.noarch                                                                 10/22
	owncloud-app-files_texteditor-8.1.1-12.1.noarch was supposed to be removed but is not!
		Verifying  : owncloud-app-files_texteditor-8.1.1-12.1.noarch                                                               11/22
	owncloud-server-8.1.1-12.1.noarch was supposed to be removed but is not!
		Verifying  : owncloud-server-8.1.1-12.1.noarch                                                                             12/22
	owncloud-app-files_external-8.1.1-12.1.noarch was supposed to be removed but is not!
		Verifying  : owncloud-app-files_external-8.1.1-12.1.noarch                                                                 13/22
	owncloud-app-templateeditor-8.1.1-12.1.noarch was supposed to be removed but is not!
		Verifying  : owncloud-app-templateeditor-8.1.1-12.1.noarch                                                                 14/22
	owncloud-app-user_external-8.1.1-12.1.noarch was supposed to be removed but is not!
		Verifying  : owncloud-app-user_external-8.1.1-12.1.noarch                                                                  15/22
		Verifying  : owncloud-server-8.1.4-12.1.noarch                                                                             16/22
	owncloud-app-gallery-8.1.1-12.1.noarch was supposed to be removed but is not!
		Verifying  : owncloud-app-gallery-8.1.1-12.1.noarch                                                                        17/22
	owncloud-app-files_pdfviewer-8.1.1-12.1.noarch was supposed to be removed but is not!
		Verifying  : owncloud-app-files_pdfviewer-8.1.1-12.1.noarch                                                                18/22
	owncloud-3rdparty-8.1.1-12.1.noarch was supposed to be removed but is not!
		Verifying  : owncloud-3rdparty-8.1.1-12.1.noarch                                                                           19/22
	owncloud-app-files_locking-8.1.1-12.1.noarch was supposed to be removed but is not!
		Verifying  : owncloud-app-files_locking-8.1.1-12.1.noarch                                                                  20/22
	owncloud-app-user_webdavauth-8.1.1-12.1.noarch was supposed to be removed but is not!
		Verifying  : owncloud-app-user_webdavauth-8.1.1-12.1.noarch                                                                21/22
	owncloud-app-activity-8.1.1-12.1.noarch was supposed to be removed but is not!
		Verifying  : owncloud-app-activity-8.1.1-12.1.noarch                                                                       22/22

	Failed:
		owncloud-3rdparty.noarch 0:8.1.1-12.1                            owncloud-app-activity.noarch 0:8.1.1-12.1
		owncloud-app-encryption.noarch 0:8.1.1-12.1                      owncloud-app-external.noarch 0:8.1.1-12.1
		owncloud-app-files.noarch 0:8.1.1-12.1                           owncloud-app-files_external.noarch 0:8.1.1-12.1
		owncloud-app-files_locking.noarch 0:8.1.1-12.1                   owncloud-app-files_pdfviewer.noarch 0:8.1.1-12.1
		owncloud-app-files_sharing.noarch 0:8.1.1-12.1                   owncloud-app-files_texteditor.noarch 0:8.1.1-12.1
		owncloud-app-files_trashbin.noarch 0:8.1.1-12.1                  owncloud-app-files_versions.noarch 0:8.1.1-12.1
		owncloud-app-files_videoviewer.noarch 0:8.1.1-12.1               owncloud-app-firstrunwizard.noarch 0:8.1.1-12.1
		owncloud-app-gallery.noarch 0:8.1.1-12.1                         owncloud-app-provisioning_api.noarch 0:8.1.1-12.1
		owncloud-app-templateeditor.noarch 0:8.1.1-12.1                  owncloud-app-user_external.noarch 0:8.1.1-12.1
		owncloud-app-user_ldap.noarch 0:8.1.1-12.1                       owncloud-app-user_webdavauth.noarch 0:8.1.1-12.1
		owncloud-server.noarch 0:8.1.1-12.1                              owncloud-server.noarch 0:8.1.4-12.1

Please note that this output was not collected the first time I tried to upgrade owncloud, and I suspect some packages (owncloud.noarch and owncloud-config-apache.noarch) were actually upgraded during my first try:

	$ yum list installed | grep -i owncloud
	owncloud.noarch                      8.1.4-12.1                @isv_ownCloud_community
	owncloud-3rdparty.noarch             8.1.1-12.1                @isv_ownCloud_community
	owncloud-app-activity.noarch         8.1.1-12.1                @isv_ownCloud_community
	owncloud-app-encryption.noarch       8.1.1-12.1                @isv_ownCloud_community
	owncloud-app-external.noarch         8.1.1-12.1                @isv_ownCloud_community
	owncloud-app-files.noarch            8.1.1-12.1                @isv_ownCloud_community
	owncloud-app-files_external.noarch   8.1.1-12.1                @isv_ownCloud_community
	owncloud-app-files_locking.noarch    8.1.1-12.1                @isv_ownCloud_community
	owncloud-app-files_pdfviewer.noarch  8.1.1-12.1                @isv_ownCloud_community
	owncloud-app-files_sharing.noarch    8.1.1-12.1                @isv_ownCloud_community
	owncloud-app-files_texteditor.noarch 8.1.1-12.1                @isv_ownCloud_community
	owncloud-app-files_trashbin.noarch   8.1.1-12.1                @isv_ownCloud_community
	owncloud-app-files_versions.noarch   8.1.1-12.1                @isv_ownCloud_community
	owncloud-app-files_videoviewer.noarch
																			 8.1.1-12.1                @isv_ownCloud_community
	owncloud-app-firstrunwizard.noarch   8.1.1-12.1                @isv_ownCloud_community
	owncloud-app-gallery.noarch          8.1.1-12.1                @isv_ownCloud_community
	owncloud-app-provisioning_api.noarch 8.1.1-12.1                @isv_ownCloud_community
	owncloud-app-templateeditor.noarch   8.1.1-12.1                @isv_ownCloud_community
	owncloud-app-user_external.noarch    8.1.1-12.1                @isv_ownCloud_community
	owncloud-app-user_ldap.noarch        8.1.1-12.1                @isv_ownCloud_community
	owncloud-app-user_webdavauth.noarch  8.1.1-12.1                @isv_ownCloud_community
	owncloud-config-apache.noarch        8.1.4-12.1                @isv_ownCloud_community
	owncloud-server.noarch               8.1.1-12.1                @isv_ownCloud_community

Do you have any suggestion on how to fix it?

**Comment by karlitschek** [comment]
@jnweiger any idea?

**Comment by jnweiger** [comment]
@maxferrario-msf  Try this
<pre>
sudo mkdir /run
sudo yum update
</pre>

How comes, that your /run directory no longer exists?

**Comment by maxferrario-msf** [comment]
Thanks @jnweiger, that did the trick!
I'm pretty sure (but not 100% sure) I didn't delete /run, but my Centos installation has a /var/run folder with all the necessary stuff in ìt, so I just created a symlink and the upgrade was succesfull.

**Comment by jnweiger** [comment]
This is strange. My CentOS_7 reference also has symlinks, but the other way round:
<pre>
$ ls -la /var/run    
lrwxrwxrwx 1 root root 6 Jun 18 12:34 /var/run -> ../run
$ ls -la /run    
total 0
drwxr-xr-x 1 root root   0 Nov 24 14:26 .
drwxr-xr-x 1 root root 186 Nov 24 14:21 ..
</pre>

**Comment by maxferrario-msf** [comment]
My fault, Jürgen: I have two machine with owncloud server installed, and 
the one I'm referring to is running CentOS version 6.7, not version 7!
