### ISSUE TITLE
Ext storage admin status indicator shifted

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#20701]
On master cb69e6c2011d43b2c19e594e89cbe7c737aaef1b

![ext-storage-status-indicator](https://cloud.githubusercontent.com/assets/277525/11363676/a209e98c-929b-11e5-8bfe-5a8de39012fd.png)

Who fancies a bisect ?

@icewind1991 @Xenopathic

**Comment by icewind1991** [comment]
will investigate

**Comment by icewind1991** [comment]
Caused by 97c60fd21794a6a0a56dc69ba8b77ab93b5d212c

will try to fix

**Comment by icewind1991** [comment]
Fix is here: #20707
