### ISSUE TITLE
Glitch editing odt

### ISSUE THREAD

**Issue by mayarichman** [owncloud/core#20708]
We are running ownCloud 8.1.3 (stable) on our Debian server. I installed libreoffice so we can directly edit the odts on the Owncloud web interface. Recently some people haven't been able to view or edit the files on the interface.
 
<img width="875" alt="owncloud screenshot1" src="https://cloud.githubusercontent.com/assets/1129086/11367146/1abfa31a-92b2-11e5-8f0e-c38e54cb3b1e.png">

When they click to view it a white box opens and nothing else is visible. They are using an up-to-date Chrome browser to access it, but I feel like it is some kind of Javascript issue. When they try to edit it, a loading icon comes up, but never resolves.

The page raised an exception: ASSERTION FAILED: tried to unsubscribe unknown callback from event "input/compositionstart".

<img width="873" alt="owncloud screenshot2" src="https://cloud.githubusercontent.com/assets/1129086/11367149/1d2f8a98-92b2-11e5-8d15-e6732afcfb55.png">

**Comment by karlitschek** [comment]
please reopen this issue in the documents repository. thanks
