### ISSUE TITLE
ownCloud sync client does not sync files - operation cancelled

### ISSUE THREAD

**Issue by errotu** [owncloud/core#20704]
### Steps to reproduce
1. Upload several files via desktop or web client to the owncloud server.
2. Start the desktop client on another device, let the synchronisation begin.
3. An error will occur in the "Activity"-Tab of the desktop client stating that particular files cannot be download because either "Operation cancelled" or "Connection closed".

### Expected behaviour
Tell us what should happen

The desktop synchronisation should work and sync all files from the web to the desktop client.

### Actual behaviour
Tell us what happens instead

Particular files are not synced but the errors mentioned above appear. It is not reproducible which files aren't synced. Sometimes, the same file with another is synced while the original file only leads to an error.

### Server configuration
**Operating system**:
Debian and Windows

**Web server:**
SunOS

**Database:**
MySQL

**PHP version:**
5.6.14

**ownCloud version:** (see ownCloud admin page)
8.2

**Updated from an older ownCloud or fresh install:**
Updated from older ownCloud 8.x versions

**List of activated apps:**
- Activity
- Default encryption module
- Deleted files
- External Sites
- External storage support
- External user support
- First Run Wizard
- Gallery
- Notifications
- PDF Viewer
- Share Files
- Text Editor
- Updater
- Versions
- Video Viewer

```

<?php
$CONFIG = array (
  'instanceid' => 'ocjl9qnrzgsk',
  'dbtype' => 'mysql',
  'version' => '8.2.1.4',

  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_from_address' => 'info',
  'mail_smtpmode' => 'php',
  'maintenance' => false,
  'remember_login_cookie_lifetime' => 432000,
  'session_lifetime' => 3600,
  'loglevel' => 2,
);


```

```

**Are you using external storage, if yes which one:**  no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no


### Client configuration
**Browser:** Firefox

**Operating system:** Debian and Windows

### Logs
#### Web server error log
```
Insert your webserver log here

#### ownCloud log (data/owncloud.log)
```
{"reqId":"VlRB@8CoLCwAAFH6kowAAAFV","remoteAddr":"88.70.40.245","app":"PHP","message":"touch(): Unable to create file \/mnt\/webt\/c1\/42\/54815342\/htdocs\/owncloud_core\/data\/owncloud.log because No such file or directory at \/mnt\/webt\/c1\/42\/54815342\/htdocs\/owncloud_core\/lib\/private\/log\/owncloud.php#53","level":3,"time":"2015-11-24T10:54:55+00:00"}
{"reqId":"VlRCEcCoLSwAACiCmvYAAALW","remoteAddr":"88.70.40.245","app":"PHP","message":"fopen(\/mnt\/webt\/c1\/42\/54815342\/htdocs\/owncloud_core\/config\/config.php): failed to open stream: No such file or directory at \/mnt\/webt\/c1\/42\/54815342\/htdocs\/owncloud_core\/lib\/private\/config.php#188","level":3,"time":"2015-11-24T10:55:13+00:00"}
```
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by karlitschek** [comment]
I guess there is some kind of error with your network or server setup or config. Irecommend to go to owncloud.org/support to see if you can ask this questions at on of the support channels. maybe at the forum. Thanks
