### ISSUE TITLE
When resynchronize, after a client update, owncloud can delete local folders bigger then the size 500Mb

### ISSUE THREAD

**Issue by adrianoafonso** [owncloud/core#20716]
### Steps to reproduce

1. (Re)Install the ownCloud client Versão 2.0.2 (build 5569) on your Machine
2. Sync your previous selected folder
3. If there is a folder on your server bigger then the size specified on the client, he can "deselect" that folder and start to delete all the local files and folders.

### Expected behaviour

Sync bidirectionally, or at least, keep local folders and files.

### Actual behaviour
Owncloud client deselect the folder bigger then the size specified, and start to delete the local files and folders.

### Operating system:

Distributor ID: Debian
Description:    Debian GNU/Linux 8.1 (jessie)
Release:        8.1
Codename:       jessie

### ownCloud
ownCloud 8.2.1 (stable)

**Comment by RealRancor** [comment]
@adrianoafonso Pleas re-open in https://github.com/owncloud/client/issues where the issue tracker for the client is located.

**Comment by PVince81** [comment]
CC @guruz @ogoffart

**Comment by guruz** [comment]
The same happened to @robert128 in https://github.com/owncloud/client/issues/3969#issuecomment-156212605
I think this is quite an annoying bug. Blocking 2.1? @dragotin 

@ogoffart Why would this happen? I guess only if that folder hat modifications in remote or local?

**Comment by guruz** [comment]
@adrianoafonso Did you need to re-add the folder to the configuration?

**Comment by adrianoafonso** [comment]
@RealRancor It seems that many people already made a link to this issue. Sorry about that, next time I'll be more careful.
@guruz yes, I did. It seems that in all updates I have to re-add the folder. I have more then 15 clients installed, and all of them, I had to re-add the folder.
And also a yes @guruz for the diff between the local folder and the server (owncloud) folder...

This is pretty annoying, and dangerous, since he deleted some important files that where not yet uploaded. I had to recover a lot of files from the hard drive after that!

**Comment by guruz** [comment]
@adrianoafonso :-| Sounds bad yes. The folder-losing is a problem of the 2.0.2 update, it should not happen with the 2.1 update. I'll close this therefore for now.. let's track in client tracker if it happens again

@MTRichards @dragotin Maybe it needs to be re-thought a bit how the selective sync behaves if a folder is not selected and has local changes that are not on the server..

**Comment by adrianoafonso** [comment]
@guruz @MTRichards @dragotin
My 2ct about the needs to re-think how the selective sync behaves. In every moment, the local data shouldn't be deleted. If it is, it needs to have specific authorisation from the user and proper warning. When you deselect a folder, a warning should appear telling the user that this folder is going to be deleted in the local machine. It could give the option to maintain the local data, and the folder should have a red background warning the user that that folder is only available locally. When is selected again, the user should be warned about the possible conflicts, and the folder syncs again, without the deletion of any data.
PS: I'm not a programmer, so I can.t help, but I can give some ideas :palm_tree: 

@guruz when it will be available the 2.1?
