### ISSUE TITLE
2 Updaters is 2 two too many?

### ISSUE THREAD

**Issue by carlaschroder** [owncloud/core#20715]
To us awesome ownCloud gurus, the idea of a core update notifier and a separate Updater app is comprehensible. To the random ownCloud admin out in the wilds they look like the same thing:

![2-updates](https://cloud.githubusercontent.com/assets/8388387/11373473/4cf3b612-9287-11e5-96e3-47bae59dcd33.png)

When you click the top banner you are taken to the upgrading chapter of the admin manual. (Yay for embedded doc links! Pure genius.) Or you can click on the Update button in the Updater app. Two different things that look like one.

The Updater app is not included in the latest releases, but that won't cure this because when users install it on purpose they're going to see the above screen. I'm updating the documentation, which will help. But I'm thinking this is a user interface issue, or perhaps the two could be combined. What say ye?

Plus I am unclear about what to tell our users. If they install from Linux packages then they should not use the Updater app, correct? But what about users who want to track the different release channels? The Updater app makes that easy.

**Comment by carlaschroder** [comment]
@VicDeo @PVince81 @DeepDiver1975

**Comment by carlaschroder** [comment]
Another use case for the Updater app is users on shared hosting.

**Comment by PVince81** [comment]
From what I understand, the reason for the separation is that you might have people with tarballs who don't want to use the updater app so they disabled it, but still want to see the notification.

This might be overly complex / flexible so maybe the notification should be changed to only be displayed for people who have the updater app enabled.

also CC @karlitschek for more input

**Comment by karlitschek** [comment]
the updater app is useful in some scenarios and not in others. because of that it is not shipped/enabled for everyone.
for 9 we add an updater that is always shipped. i hope this makes things easier

**Comment by VicDeo** [comment]
@carlaschroder  I'm not an UX expert but I was all against https://github.com/owncloud/updater/issues/40 
and one of the reasons for that is https://github.com/owncloud/core/issues/20715#issue-118653821 :)

**Comment by VicDeo** [comment]
This is how it is supposed to work from my standpoint:
- A favorite distro package manager (apt, zypper, yum, etc) should be used where possible. 
- Updater app is for the rest. 
- A tiny group of nerds  wget && unzip && cp && ln -s && service restart **shell access required**

And a naggy yellow bubble *Your upgrade is near* from core to notify  all listed above that their time has come.

**Comment by carlaschroder** [comment]
Thanks @VicDeo, now I can make a specific UX suggestion. A banner is boring, so how about this:

![homer-end-is-near1](https://cloud.githubusercontent.com/assets/8388387/11381192/86714d00-92af-11e5-913b-5e8527ff031b.jpg)

**Comment by carlaschroder** [comment]
Closing in anticipation of 9.0 grooviness.
