### ISSUE TITLE
ldap_read(): Search: Invalid DN syntax at /var/www/html/owncloud/apps/user_ldap/lib/ldap.php#257

### ISSUE THREAD

**Issue by ggujabidze** [owncloud/core#20725]
I've have upgraded my ownCloud Server from v.8.1.3 to 8.2.1, but the old errors still exist in logs. I had that errors in old version, though I've set useMemberOfToDetectMembership to 0 and after upgrade, it's still there. I do understand that this error actually is not an error and everything works perfectly, but I would like my log file be error/warning-free. Also I've read somewhere in your forum that this error causes additional network traffic in my local network. So, it'll be great if you can help me to fix it. It's strange that I couldn't find anyone reporting this error on the latest version, so maybe the problem is in my installation?

### Steps to reproduce
It just appearing time to time in logs

### Server configuration
**Operating system**:  CentOS Linux release 7.1.1503

**Web server:**  Apache/2.4.6

**Database:**  Ver 15.1 Distrib 5.5.44-MariaDB

**PHP version:**  5.4.16

**ownCloud version:**  8.2.1

**Updated from an older ownCloud or fresh install:**  Updated from 8.1.3

**List of activated apps:**  

activity: 2.1.3
files: 1.2.0
files_pdfviewer: 0.7
files_sharing: 0.7.0
files_texteditor: 2.0
files_trashbin: 0.7.0
files_versions: 1.1.0
firstrunwizard: 1.1
gallery: 14.2.0
provisioning_api: 0.3.0
user_ldap: 0.7.0

**The content of config/config.php:**

{
    "system": {
        "instanceid": "ocvkqnd40ojf",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xx.xx.xx.xx"
        ],
        "datadirectory": "\/cloud",
        "overwrite.cli.url": "http:\/\/192.168.0.228\/owncloud",
        "dbtype": "mysql",
        "version": "8.2.1.4",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Asia\/Tbilisi",
        "installed": true,
        "default_language": "en",
        "defaultapp": "files",
        "allow_user_to_change_display_name": true,
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 900,
        "trashbin_retention_obligation": "30, auto",
        "ldapIgnoreNamingRules": false,
        "enable_previews": true,
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "preview_max_scale_factor": 10,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\PDF"
        ],
        "maintenance": false,
        "singleuser": false,
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        },
        "asset-pipeline.enabled": true,
        "theme": "",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "owncloud",
        "mail_domain": "gcfund.ge",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.office365.com",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "check_for_working_htaccess": true,
        "loglevel": 2
    }
}

**Are you using encryption:**  No

**Are you using an external user-backend, if yes which one:**  M$ Active Directory

#### LDAP configuration (delete this part if not used)
+-------------------------------+---------------------------------------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                                                           |
+-------------------------------+---------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                         |
| hasPagedResultSupport         |                                                                                                                           |
| homeFolderNamingRule          |                                                                                                                           |
| lastJpegPhotoLookup           | 0                                                                                                                         |
| ldapAgentName                 | CN=ldap,OU=System Users,DC=gcfund,DC=dc                                                                                   |
| ldapAgentPassword             | ***                                                                                                                       |
| ldapAttributesForGroupSearch  |                                                                                                                           |
| ldapAttributesForUserSearch   |                                                                                                                           |
| ldapBackupHost                | dc01.gcfund.dc                                                                                                            |
| ldapBackupPort                | 389                                                                                                                       |
| ldapBase                      | DC=gcfund,DC=dc                                                                                                           |
| ldapBaseGroups                | DC=gcfund,DC=dc                                                                                                           |
| ldapBaseUsers                 | DC=gcfund,DC=dc                                                                                                           |
| ldapCacheTTL                  | 600                                                                                                                       |
| ldapConfigurationActive       | 1                                                                                                                         |
| ldapEmailAttribute            | mail                                                                                                                      |
| ldapExperiencedAdmin          | 0                                                                                                                         |
| ldapExpertUUIDGroupAttr       |                                                                                                                           |
| ldapExpertUUIDUserAttr        |                                                                                                                           |
| ldapExpertUsernameAttr        | sAMAccountName                                                                                                            |
| ldapGroupDisplayName          | cn                                                                                                                        |
| ldapGroupFilter               |                                                                                                                           |
| ldapGroupFilterGroups         |                                                                                                                           |
| ldapGroupFilterMode           | 0                                                                                                                         |
| ldapGroupFilterObjectclass    |                                                                                                                           |
| ldapGroupMemberAssocAttr      | member                                                                                                                    |
| ldapHost                      | gcf-r2.gcfund.dc                                                                                                          |
| ldapIgnoreNamingRules         |                                                                                                                           |
| ldapLoginFilter               | (&(&(|(objectclass=person))(|(|(memberof=CN=ownCloud Users,DC=gcfund,DC=dc)(primaryGroupID=1663))))(samaccountname=%uid)) |
| ldapLoginFilterAttributes     |                                                                                                                           |
| ldapLoginFilterEmail          | 0                                                                                                                         |
| ldapLoginFilterMode           | 0                                                                                                                         |
| ldapLoginFilterUsername       | 1                                                                                                                         |
| ldapNestedGroups              | 0                                                                                                                         |
| ldapOverrideMainServer        |                                                                                                                           |
| ldapPagingSize                | 500                                                                                                                       |
| ldapPort                      | 389                                                                                                                       |
| ldapQuotaAttribute            |                                                                                                                           |
| ldapQuotaDefault              |                                                                                                                           |
| ldapTLS                       | 0                                                                                                                         |
| ldapUserDisplayName           | displayname                                                                                                               |
| ldapUserFilter                | (&(|(objectclass=person))(|(|(memberof=CN=ownCloud Users,DC=gcfund,DC=dc)(primaryGroupID=1663))))                         |
| ldapUserFilterGroups          | ownCloud Users                                                                                                            |
| ldapUserFilterMode            | 0                                                                                                                         |
| ldapUserFilterObjectclass     | person                                                                                                                    |
| ldapUuidGroupAttribute        | auto                                                                                                                      |
| ldapUuidUserAttribute         | auto                                                                                                                      |
| turnOffCertCheck              | 0                                                                                                                         |
| useMemberOfToDetectMembership | 0                                                                                                                         |
+-------------------------------+---------------------------------------------------------------------------------------------------------------------------+

#### ownCloud log
{"reqId":"VlVcmf-wj9CEYZvG2G4cpgAAAA0","remoteAddr":"192.168.0.212","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-11-25T11:00:41+04:00"}
{"reqId":"VlVg367AE6bEknUwJo2L0AAAABY","remoteAddr":"192.168.0.212","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-11-25T11:18:55+04:00"}
{"reqId":"VlVj1Aol0NGqvSDbzVD-ygAAABg","remoteAddr":"192.168.0.212","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-11-25T11:31:32+04:00"}

**Comment by MorrisJobke** [comment]
See https://github.com/owncloud/core/issues/17570#issuecomment-131974635


> About
>
> ``Error PHP ldap_read(): Search: Invalid DN syntax``
> 
> You can safely ignore this for now.  It  is triggered by this line:
> 
> https://github.com/owncloud/core/blob/master/apps/user_ldap/ajax/testConfiguration.php#L52
> 
> I am looking into hiding the message. I found some other questions while looking at it, but that's fine so far.
