### ISSUE TITLE
No backup files listed

### ISSUE THREAD

**Issue by peterkahl** [owncloud/core#20721]
OS 8.2.1 shows no backups, although they exist in the exact same directory.
![no-backups](https://cloud.githubusercontent.com/assets/2703373/11387410/1f863590-9365-11e5-887e-9514cdaf9bd5.png)

**Comment by RealRancor** [comment]
Please re-open in https://github.com/owncloud/updater/issues where the issue tracker of the updater app is located.

**Comment by nickvergessen** [comment]
Reported as https://github.com/owncloud/updater/issues/197
