### ISSUE TITLE
Share via link a file and set a pwd of more than 72 characters (the following ones are ignored)

### ISSUE THREAD

**Issue by davitol** [owncloud/core#20726]
### Steps to reproduce

1. Create a file
2. Click on share button 
3. Share the file via link and set a long password (more than 72 characters)  
4. Paste the link in another browser and access to the file writing only the first 72 characters or 

### Expected behaviour
The file pwd should fix exacty to what it is set.

### Actual behaviour
Only the first 72 characters are being considered.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** ownCloud Enterprise Edition 8.2.1 (stable)

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Firefox

**Comment by PVince81** [comment]
Not sure why... @rullzer @LukasReschke 
If only 72 chars are supported, maybe we should make the UI stop at 72 ?

It might be due to the limit in the field width for the encoded password.

**Comment by rullzer** [comment]
Yes this is known. And a limitation of the underlying hash stuff: http://php.net/manual/en/function.password-hash.php

The trouble is if we start to hardcode 72 char stuff. Then switching to something different (which we might want in the future) will be a hard.

**Comment by rullzer** [comment]
Same holds true for your regular passwords btw.

**Comment by LukasReschke** [comment]
I still vote for: Ignore. Do not care. And close.

**Comment by LukasReschke** [comment]
https://github.com/owncloud/core/issues/14578
