### ISSUE TITLE
[8.1.4] System Cron never run if skip update

### ISSUE THREAD

**Issue by PoPoutdoor** [owncloud/core#20737]
System cron works with 7.0.x before update (manual update from 7.0.x -> 8.0.x -> 8.1.x)

Maybe related to:

https://github.com/owncloud/core/blob/v8.1.4/cron.php#L35,L38

**Comment by Xenopathic** [comment]
Logs?

**Comment by PoPoutdoor** [comment]
@Xenopathic Nothing about cron in owncloud.log

**Comment by Xenopathic** [comment]
Is anything printed when you run cron.php manually? How do you know it's not working?

**Comment by PoPoutdoor** [comment]
@Xenopathic I get the cron status from Admin page.
~~~
sudo -u www-data -f /path/to/owncloud_root/cron.php
~~~
does not print anything, return code is 0.

**Comment by PoPoutdoor** [comment]
Found out this is a lxc container permission issue.
