### ISSUE TITLE
Exception on Update

### ISSUE THREAD

**Issue by cyberer** [owncloud/core#20732]
Exception: Updates between multiple major versions and downgrades are unsupported after upgrading from 8.0.4 to 8.2.1.
Now the installation is useless and broken.

**Comment by RealRancor** [comment]
Please use the search here and upgrade first to 8.1.4 before upgrading to 8.2.1.

The message itself is telling you exactly what to do and where the problem is.

**Comment by cyberer** [comment]
But the message comes in the middle of the process. Now I have a broken cloud. If it's known, the upgrade-process can stop at the beginning, not in the middle of process.
The message is useless at this point.
In my eyes a upgrade between major versions would be 7.something to 8.x. between 8.0 and 8.1 should be a minor upgrade

**Comment by RealRancor** [comment]
The upgrade process have not started yet and stopped

oC 8.1 is a major and not a minor release as stated at various places.

**Comment by Xenopathic** [comment]
As written on our [official release channel page](https://owncloud.org/release-channels/):

> Stable repositories are available for the following major versions: 8.2, 8.1, 8.0, 7.0

Minor version updates are for example 8.2.0 -> 8.2.1. 8.2 is a completely new major version from 8.1. Please update first to 8.1.x, then to 8.2.x

**Comment by RealRancor** [comment]
And also in: https://doc.owncloud.org/server/8.1/admin_manual/maintenance/upgrade.html

> It is best to keep your ownCloud server upgraded regularly, and to install all point releases and major releases without skipping any of them, as skipping releases increases the risk of errors. Major releases are 8.0, 8.1, 8.2, and 9.0. Point releases are intermediate releases for each major release. For example, 8.0.9 and 8.1.3 are point releases.
