### ISSUE TITLE
video player works fine if logged in, but not on shared links. there you only have download.

### ISSUE THREAD

**Issue by mdonges** [owncloud/core#20739]
we have public videos on the ownCloud, becuase do not want to send them via mail. (too much MB ;)
but you can only download them, if you use the public shared link.
the play button exists but does not work.

it would be wondeful, to have the video player opened as id you are logged in.
Logged in its a very nice feature!

having the same on public shared links would be perfect!

**Comment by LukasReschke** [comment]
More information: This is a MKV file on an iPad.

**Comment by jancborchardt** [comment]
@Instagit does this work properly with your new video player?

**Comment by RealRancor** [comment]
@LukasReschke @jancborchardt 

Known issue with share links as discussed here: https://github.com/owncloud/apps/issues/2087#issuecomment-146460985

There is an open issue at the app issue tracker to make that to work with shared links : https://github.com/owncloud/apps/issues/2120

**Comment by Instagit** [comment]
@jancborchardt 

Shared folders use the custom video player, single shared files the default HTML5 player. In Firefox everything works, in Chrome some files don't play and for those that do, seeking doesn't work. I think making it work is all about ownCloud sending HTTP response with status 206, partial content.

https://github.com/Instagit/videojs-sublime/issues/18

**Comment by RealRancor** [comment]
> I think making it work is all about ownCloud sending HTTP response with status 206, partial content.

206 means support ranged requests right? If yes then i think this can be closed in favor of https://github.com/owncloud/apps/issues/2120

**Comment by PVince81** [comment]
Would be good to use the issue template https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

Please try with ownCloud 8.2.1 where a recent video player fix was put in.

**Comment by PVince81** [comment]
Feel free to reopen if it doesn't work in that version, and use the issue template https://raw.githubusercontent.com/owncloud/core/master/issue_template.md to provide more info.

**Comment by jancborchardt** [comment]
@PVince81 it’s still the case exactly as described. Because the video player used on the share page is the default video element, whereas the one used when you are logged in is mediaelement.js with more fallbacks etc.

@Instagit is it also possible that when the new video player is installed that the public share page also uses that for videos? Everywhere where there are videos, we should use the same player for consistency of look and working condition.

**Comment by PVince81** [comment]
So are you saying tht the mediaelement.js doesn't work on all environments ? It worked for me.

**Comment by Instagit** [comment]
I always get the default HTML5 player for shared files. The video player apps only work for shared folders, where the page layout is the same as the normal ownCloud file browser.

![screenshot](https://cloud.githubusercontent.com/assets/2681794/11438195/a05ebafe-94f3-11e5-9ad9-7867a82419ae.png)

**Comment by PVince81** [comment]
Please reopen if issue persists with 10.0.4 and latest files_videoplayer app version.
