### ISSUE TITLE
Sabre/dav asks for authentication

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#20738]
![capture du 2015-11-25 20-32-28](https://cloud.githubusercontent.com/assets/925062/11407537/bc5f8f80-93b3-11e5-8406-b7ddafa7d84a.png)

This happens often with the Contacts Rework, but Thomas asked me to open the issue in here. ;)

cc @DeepDiver1975 @Henni

**Comment by DeepDiver1975** [comment]
I did observe the same with the files app - related to the sabredav update ...

**Comment by PVince81** [comment]
@jancborchardt did you properly update your submodule ?

Might be related #20727

**Comment by DeepDiver1975** [comment]
> Might be related #20727

that's the same issue -> closing - thx
