### ISSUE TITLE
Sharing tokens should be unique

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#20741]
Currently we rely on pure luck that the tokens we generate for link shares are unique. Now this is most likely the case but not at all guaranteed. Probabaly bad stuff happens if we have duplicated tokens.
- We should use transactions to verify the insert and rollback if required.
- This is probably also a good health check candidate (CC @MorrisJobke )

CC: @LukasReschke

**Comment by PVince81** [comment]
So we're not using the secure generator function ?

**Comment by rullzer** [comment]
We are. But those do not guarantee uniqueness.

**Comment by rullzer** [comment]
Relevant dilbert: http://dilbert.com/strip/2001-10-25
