### ISSUE TITLE
Stop sending notification

### ISSUE THREAD

**Issue by Landver** [owncloud/core#20743]
## **Steps to reproduce**
For test I set V on all of possible notifications in user settings
All Mail Templates are defaulted.
Problem happen after some changes, I have no idea what can cause that.

## **Expected behaviour**
Email should be sent with activity notification

## **Actual behaviour**
I stop receive notification email (hourly/daily/weekly) any of them.
I can succesfully receive test emails and see them in logs, here is example:
**Sent mail to "Array ( [stast@io-sat.com] => stast )** " with subject "test email settings"2015-11-26T09:06:44+00:00

## **Question about**
What can be a problem? Or what you recomend to do for fixing that issue?

## **Server configuration**
**Owncloud version**: 8.2.0
**CentOS**: 7
**Apache**:
[root@localhost ~]# rpm -qa |grep htt
httpd-2.4.6-31.el7.centos.1.x86_64
httpd-tools-2.4.6-31.el7.centos.1.x86_64
**php**:
[root@localhost ~]# rpm -qa |grep php
php-mbstring-5.4.16-36.el7_1.x86_64
php-process-5.4.16-36.el7_1.x86_64
php-cli-5.4.16-36.el7_1.x86_64
php-gd-5.4.16-36.el7_1.x86_64
php-pecl-igbinary-1.2.1-1.el7.x86_64
php-common-5.4.16-36.el7_1.x86_64
php-pear-1.9.4-21.el7.noarch
php-xml-5.4.16-36.el7_1.x86_64
php-pdo-5.4.16-36.el7_1.x86_64
php-mysql-5.4.16-36.el7_1.x86_64
php-pecl-apcu-4.0.7-1.el7.x86_64
php-5.4.16-36.el7_1.x86_64

**Comment by PVince81** [comment]
Please check your cron config on the admin page and also check whether your system cron service is running (if you are using system cron).

For more support please check https://owncloud.org/support/

If all your settings are correct and cron is working and you think this is a bug, please reopen and use the issue template https://raw.githubusercontent.com/owncloud/core/master/issue_template.md
