### ISSUE TITLE
Internal share (LDAP) works only once

### ISSUE THREAD

**Issue by stevejordi** [owncloud/core#20747]
Several users complained about not being able to share a folder with several internal users (populated by our LDAP server).
- On a folder, click SHARE
- Type in a user from the LDAP (do not share with a link)
- Select the user
- Click SHARE again. Either nothing happens or you can't do anything in the edit field. Some can type a name (search will work) but then it's impossible to select a name in the list

The only way to share again is to hit F5 to refresh the page.
Not convenient when wanting to share with 10 persons. 

Doesn't work in InterentExplorer 9 and 10.
Doesn't work in FireFox 3x.
Woks fine in Chrome and Safari
ownCloud 8.1.0 on CentOS 6

**Comment by PVince81** [comment]
Please use the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

You might want to upgrade to 8.1.2 to make sure you got the latest LDAP fixes.

If the problem still persists, would be good to have a look at the Javascript and Network log in the browser to see what response you get from the server, and also owncloud.log.

**Comment by stevejordi** [comment]
That did it. Thanks.
Just tried with two LDAP directories, one on ActiveDir, the other on LotusDomino, both work now.
I have to rewrite the manuals and republish new tutorial videos now since the share interface has changed, but this, you can't help :-)

Thanks for your prompt answer.
Steve
