### ISSUE TITLE
Undefined index etag in trashbin

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#20748]
* setup a new owncloud (master)
* delete the `welcome.txt`
* go to trash bin

## expected 

* no errors in log

## actual

owncloud.log once you enter the trash bin page
```
{"reqId":"njeNskpjd++XOsC7izlq","remoteAddr":"::1","app":"PHP","message":"Undefined index: etag at \/Users\/morrisjobke\/Projects\/owncloud\/master\/lib\/private\/files\/fileinfo.php#167","level":0,"time":"2015-11-26T10:40:47+00:00","method":"GET","url":"\/master\/index.php\/apps\/files_trashbin\/ajax\/list.php?dir=%2F&sort=mtime&sortdirection=desc"}
```

cc @icewind1991 @PVince81 @schiesbn

**Comment by PVince81** [comment]
@icewind1991 does your etag computation enhancement affect trashbin and other ?

**Comment by PVince81** [comment]
This was fixed a while ago. It was due to the result formatting code that was expecting an etag attribute to exist.

Cannot reproduce on 9.1.0 beta2.
