### ISSUE TITLE
No calendar export for some calendars

### ISSUE THREAD

**Issue by dlehmann69** [owncloud/core#20749]
I have get the following error message at the export of one calendar from owncloud. Other calendars are possible to export.

owncloud 8.2.1
Ubuntu 14.04.3
mysql DB
Apache 2.4 Server

Error	index	Exception: {"Exception":"Sabre\\VObject\\EofException","Message":"End of document reached prematurely","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php(168): Sabre\\VObject\\Parser\\MimeDir->readLine()\n#1 \/var\/www\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php(137): Sabre\\VObject\\Parser\\MimeDir->parseLine('BEGIN:VEVENT')\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php(63): Sabre\\VObject\\Parser\\MimeDir->parseDocument()\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Reader.php(44): Sabre\\VObject\\Parser\\MimeDir->parse('BEGIN:VCALENDAR...', 0)\n#4 \/var\/www\/owncloud\/apps\/calendar\/lib\/export.php(68): Sabre\\VObject\\Reader::read('BEGIN:VCALENDAR...')\n#5 \/var\/www\/owncloud\/apps\/calendar\/lib\/export.php(43): OC_Calendar_Export::generateEvent(Array)\n#6 \/var\/www\/owncloud\/apps\/calendar\/lib\/export.php(28): OC_Calendar_Export::calendar('5')\n#7 \/var\/www\/owncloud\/apps\/calendar\/export.php(20): OC_Calendar_Export::export('5', 'calendar')\n#8 \/var\/www\/owncloud\/lib\/private\/route\/route.php(154) : runtime-created function(1): require_once('\/var\/www\/ownclo...')\n#9 [internal function]: __lambda_func(Array)\n#10 \/var\/www\/owncloud\/lib\/private\/route\/router.php(282): call_user_func('?lambda_2320', Array)\n#11 \/var\/www\/owncloud\/lib\/base.php(851): OC\\Route\\Router->match('\/apps\/calendar\/...')\n#12 \/var\/www\/owncloud\/index.php(39): OC::handleRequest()\n#13 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php","Line":250}

**Comment by RealRancor** [comment]
Hi,

please re-open in https://github.com/owncloud/calendar/issues (where the issue tracker of the calendar app is located) by using the issue template as described here: https://github.com/owncloud/calendar/blob/master/CONTRIBUTING.md#short-version
