### ISSUE TITLE
[3rdparty] Switch to stable sabre before 9.0 release

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#20740]
Currently our 3rdparty repo contains sabre-3.0.x-dev. This is since we have quite a number of upstream fixes. However before the 9.0 release we should make sure we are on a stable version so we ship with a proper version.

This issue is there so we don't foret.

FYI @cmonteroluque 

CC: @LukasReschke @DeepDiver1975

**Comment by DeepDiver1975** [comment]
added to the meta issue for dav in scope of 9.0 - https://github.com/owncloud/core/issues/20047
