### ISSUE TITLE
Resharing is not allowed

### ISSUE THREAD

**Issue by aartatimago** [owncloud/core#20751]
Hello,

I've updated this morning the owncloud-server from 8.1.4 to 8.2.1.

Now I cannot share anything. I always get the message "resharing is not allowed".
On the admin-page the checkbox from resharing is "on".

It is happening with:
- known users & new users
- known folders & new folders.

Hopefully there is a quick answer, because it is stopping me from doing anything.

See also: https://forum.owncloud.org/viewtopic.php?f=36&t=31728&p=102044#p102044

**Comment by rullzer** [comment]
Probabaly caused by https://github.com/owncloud/core/issues/20642 (if nto please reopen). We are looking into it.

**Comment by aartatimago** [comment]
Yes, you are right.
In our case we don't allow share links, so this was off.

When i turned "shared links" on, than I can share.
Thanks for the workaround.

Looking forward to the update.
