### ISSUE TITLE
Can't delete folder on external SMB storage

### ISSUE THREAD

**Issue by raptwa** [owncloud/core#20750]
### Steps to reproduce
1. Add SMB external storage
2. Create folder within the external storage 
3. Delete folder by using the web ui

### Expected behaviour
The folder should be deleted

### Actual behaviour
Could not delete folder

The folder can be deleted directly on the server or by Windows Explorer. Files on the other hand can be deleted from within the browser without any problem.

### Server configuration
**Operating system**:
Windows 7
**Web server:**
Debian Jessie
**Database:**
MariaDB
**PHP version:**
5.6.15-1
**ownCloud version:** (see ownCloud admin page)
8.2.1.4
**Updated from an older ownCloud or fresh install:**
8.0.1.4
**List of activated apps:**
 - audios: 1.2.5
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - documents: 0.11.0
  - external: 1.2
  - files: 1.2.0
  - files_external: 0.3.0
  - files_latexeditor: 0.7
  - files_mv: 0.8.1a
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - gallery: 14.2.0
  - html5_videoplayer: 1.0
  - ocdownloader: 1.5
  - passwords: 15
  - rainloop: 4.8
  - tasks: 0.8.1
  - templateeditor: 0.1
  - updater: 0.6
  - user_ldap: 0.7.0

**The content of config/config.php:**

"system": {
        "instanceid": "occb0e8e6d5f",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "my.xxxxxxx.de"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/my.xxxxxxx.de",
        "dbtype": "mysql",
        "version": "8.2.1.4",
        "dbname": "owncloud",
        "dbhost": "mysql.xxxxxxx.de",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "php",
        "ldapIgnoreNamingRules": false,
        "loglevel": 0,
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": true,
        "filesystem_check_changes": 1,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        }
    }

**Are you using external storage, if yes which one:** local/smb/sftp/...
smb, sftp
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** 
LDAP
#### LDAP configuration (delete this part if not used)
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                                                           |
| hasPagedResultSupport         |                                                                                                                                                             |
| homeFolderNamingRule          |                                                                                                                                                             |
| lastJpegPhotoLookup           | 0                                                                                                                                                           |
| ldapAgentName                 | uid=admin,dc=xxxxxxx,dc=de                                                                                                                                |
| ldapAgentPassword             | ***                                                                                                                                                         |
| ldapAttributesForGroupSearch  |                                                                                                                                                             |
| ldapAttributesForUserSearch   |                                                                                                                                                             |
| ldapBackupHost                |                                                                                                                                                             |
| ldapBackupPort                |                                                                                                                                                             |
| ldapBase                      | dc=xxxxxxx,dc=de                                                                                                                                          |
| ldapBaseGroups                | ou=owncloud,dc=xxxxxxx,dc=de;ou=Groups,dc=xxxxxxx,dc=de                                                                                                 |
| ldapBaseUsers                 | ou=User,dc=xxxxxxx,dc=de;dc=xxxxxxx,dc=de                                                                                                               |
| ldapCacheTTL                  | 600                                                                                                                                                         |
| ldapConfigurationActive       | 1                                                                                                                                                           |
| ldapEmailAttribute            | mail                                                                                                                                                        |
| ldapExperiencedAdmin          | 0                                                                                                                                                           |
| ldapExpertUUIDGroupAttr       | cn                                                                                                                                                          |
| ldapExpertUUIDUserAttr        | uid                                                                                                                                                         |
| ldapExpertUsernameAttr        | uid                                                                                                                                                         |
| ldapGroupDisplayName          | cn                                                                                                                                                          |
| ldapGroupFilter               | (&(|(objectclass=posixGroup))(|(cn=admin)(cn=allusers)(cn=oc_user))) |
| ldapGroupFilterGroups         | admin;allusers;oc_user;                                                                           |
| ldapGroupFilterMode           | 0                                                                                                                                                           |
| ldapGroupFilterObjectclass    | posixGroup                                                                                                                                                  |
| ldapGroupMemberAssocAttr      | member                                                                                                                                                      |
| ldapHost                      | ldap.xxxxxxx.de                                                                                                                                           |
| ldapIgnoreNamingRules         |                                                                                                                                                             |
| ldapLoginFilter               | (&(&(|(objectclass=posixAccount))(|(memberof=cn=oc_user,ou=owncloud,dc=xxxxxxx,dc=de)))(|(uid=%uid)(|(uid=%uid))))                                        |
| ldapLoginFilterAttributes     | uid                                                                                                                                                         |
| ldapLoginFilterEmail          | 0                                                                                                                                                           |
| ldapLoginFilterMode           | 0                                                                                                                                                           |
| ldapLoginFilterUsername       | 1                                                                                                                                                           |
| ldapNestedGroups              | 1                                                                                                                                                           |
| ldapOverrideMainServer        | 0                                                                                                                                                           |
| ldapPagingSize                | 500                                                                                                                                                         |
| ldapPort                      | 389                                                                                                                                                         |
| ldapQuotaAttribute            |                                                                                                                                                             |
| ldapQuotaDefault              |                                                                                                                                                             |
| ldapTLS                       | 1                                                                                                                                                           |
| ldapUserDisplayName           | cn                                                                                                                                                          |
| ldapUserFilter                | (&(|(objectclass=posixAccount))(|(memberof=cn=oc_user,ou=owncloud,dc=xxxxxxx,dc=de)))                                                                     |
| ldapUserFilterGroups          | oc_user                                                                                                                                                     |
| ldapUserFilterMode            | 0                                                                                                                                                           |
| ldapUserFilterObjectclass     | posixAccount                                                                                                                                                |
| ldapUuidGroupAttribute        | auto                                                                                                                                                        |
| ldapUuidUserAttribute         | auto                                                                                                                                                        |
| turnOffCertCheck              | 0                                                                                                                                                           |
| useMemberOfToDetectMembership | 1                                                                                                                                                           |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------+

### Client configuration
**Browser:**
Firefox
**Operating system:**
Windows 7
#### Web server error log
- 

#### ownCloud log (data/owncloud.log)
Exception: {"Message":"Invalid request for smb:\/\/192.168.100.4\/Home\/","Exception":"Icewind\\SMB\\Exception\\ForbiddenException","Code":13,"Trace":"#0 \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/NativeState.php(72): Icewind\\SMB\\NativeState->handleError('smb:\/\/192.168.1...')\n#1 \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/NativeState.php(180): Icewind\\SMB\\NativeState->testResult(false, 'smb:\/\/192.168.1...')\n#2 \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/NativeShare.php(105): Icewind\\SMB\\NativeState->stat('smb:\/\/192.168.1...')\n#3 \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/NativeShare.php(100): Icewind\\SMB\\NativeShare->getStat('\/')\n#4 
\/var\/www\/owncloud\/apps\/files_external\/lib\/smb.php(102): Icewind\\SMB\\NativeShare->stat('\/')\n#5 
\/var\/www\/owncloud\/apps\/files_external\/lib\/smb.php(272): OC\\Files\\Storage\\SMB->getFileInfo('')\n#6 
\/var\/www\/owncloud\/lib\/private\/files\/storage\/common.php(91): OC\\Files\\Storage\\SMB->filetype('')\n#7 
\/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(99): OC\\Files\\Storage\\Common->is_dir('')\n#8 
\/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/availability.php(104): OC\\Files\\Storage\\Wrapper\\Wrapper->is_dir('')\n#9 
\/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(99): OC\\Files\\Storage\\Wrapper\\Availability->is_dir('')\n#10 
\/var\/www\/owncloud\/lib\/private\/files\/cache\/watcher.php(102): OC\\Files\\Storage\\Wrapper\\Wrapper->is_dir('')\n#11 
\/var\/www\/owncloud\/lib\/private\/files\/view.php(1207): OC\\Files\\Cache\\Watcher->update('', Array)\n#12 
\/var\/www\/owncloud\/lib\/private\/connector\/sabre\/objecttree.php(148): OC\\Files\\View->getFileInfo('Home')\n#13 
\/var\/www\/owncloud\/lib\/private\/connector\/sabre\/custompropertiesbackend.php(100): OC\\Connector\\Sabre\\ObjectTree->getNodeForPath('Home')\n#14 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/PropertyStorage\/Plugin.php(86): OC\\Connector\\Sabre\\CustomPropertiesBackend->propFind('Home', Object(Sabre\\DAV\\PropFind))\n#15 
[internal function]: Sabre\\DAV\\PropertyStorage\\Plugin->propFind(Object(Sabre\\DAV\\PropFind), Object(OC\\Connector\\Sabre\\Directory))\n#16 
\/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#17 
\/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1016): Sabre\\Event\\EventEmitter->emit('propFind', Array)\n#18 
\/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(936): Sabre\\DAV\\Server->getPropertiesByNode(Object(Sabre\\DAV\\PropFind), Object(OC\\Connector\\Sabre\\Directory))\n#19 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(327): Sabre\\DAV\\Server->getPropertiesForPath('', Array, 1)\n#20 
[internal function]: Sabre\\DAV\\CorePlugin->httpPropfind(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#21 
\/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#22 
\/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PROPFIND', Array)\n#23 
\/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#24 
\/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(55): Sabre\\DAV\\Server->exec()\n#25 
\/var\/www\/owncloud\/remote.php(137): require_once('\/var\/www\/ownclo...')\n#26 
{main}","File":"\/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/NativeState.php","Line":42} 

#### Browser log
POST https://my.staderweg.de/index.php/apps/files/ajax/delete.php
	
200 OK
		190ms	
jquery....ee38a70 (line 6)
HeadersPostResponseJSONCookies

{"data":{"message":"Could not delete:\nNeuer Ordner\n","uploadMaxFilesize":21474836480,"maxHumanFilesize"
:"Hochladen (max. 20 GB)","freeSpace":-2,"usedSpacePercent":0,"owner":"xxx","ownerDisplayName":"xxx"},"status":"error"}

**Comment by Xenopathic** [comment]
cc @icewind1991

**Comment by icewind1991** [comment]
Can't reproduce against a windows serrver 2012 share

**Comment by raptwa** [comment]
Samba server is running on Debian Jessie. 
Version: 2:4.1.18+dfsg-3~inverse1

**Comment by kaeser-sosae** [comment]
Same problem here. Running Server 2012 R2, ownCloud 8.2.2

php5-libsmbclient installed.

**Comment by kaeser-sosae** [comment]
![image](https://cloud.githubusercontent.com/assets/13239751/12349128/3e3c9ab8-bba8-11e5-8b2f-ec833e9bbf46.png)

**Comment by kaeser-sosae** [comment]
![image](https://cloud.githubusercontent.com/assets/13239751/12349361/08027420-bbaa-11e5-8ff8-0b6fcf0fc1b9.png)

**Comment by kaeser-sosae** [comment]
Additionally, when I get that error come up, I do not see anything in the logs.

**Comment by kaeser-sosae** [comment]
Further information: deleting a folder works with the Sync client on windows, just not through the web interface.

**Comment by kaeser-sosae** [comment]
Anyone out there?

**Comment by cooper-42** [comment]
I have the same issue.
Creating a new folder, renaming, creating file in the new folder and deleting this file, all works. But deleting the folder doesn't.
Nothng in the logs as well...
I have smb mounts to my Win 2012R2 Server.

**Comment by PVince81** [comment]
Are you guys all using DFS ?

Make sure you all have the PHP module php5-libsmbclient installed and possibly Samba >= 4.2.8

**Comment by cooper-42** [comment]
Hi PVince81,
I have php5-libsmbclient and Samba 4.1.6 installed.
If it helps, here is the Errorlog:

Exception: {"Message":"Unknown error (22) for smb:\/\/obdn-s-fl01.obdn.local\/0_BIMM\/00000_b.i.m.m_CLOUD_R2015\/bimm_015_VORLAGEN\/300_000_005_Vorlage_CAD_Archiv_R2015.rte","Exception":"Icewind\\SMB\\Exception\\Exception","Code":22,"Trace":"#0 \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/NativeState.php(72): Icewind\\SMB\\NativeState->handleError('smb:\/\/obdn-s-fl...')\n#1 \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/NativeState.php(146): Icewind\\SMB\\NativeState->testResult(false, 'smb:\/\/obdn-s-fl...')\n#2 \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/NativeShare.php(147): Icewind\\SMB\\NativeState->unlink('smb:\/\/obdn-s-fl...')\n#3 \/var\/www\/owncloud\/apps\/files_external\/lib\/smb.php(242): Icewind\\SMB\\NativeShare->del('\/00000_b.i.m.m_...')\n#4 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(79): OC\\Files\\Storage\\SMB->rmdir('00000_b.i.m.m_C...')\n#5 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/availability.php(82): OC\\Files\\Storage\\Wrapper\\Wrapper->rmdir('00000_b.i.m.m_C...')\n#6 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/encryption.php(259): OC\\Files\\Storage\\Wrapper\\Availability->rmdir('00000_b.i.m.m_C...')\n#7 \/var\/www\/owncloud\/lib\/private\/files\/view.php(1023): OC\\Files\\Storage\\Wrapper\\Encryption->rmdir('00000_b.i.m.m_C...')\n#8 \/var\/www\/owncloud\/lib\/private\/files\/view.php(296): OC\\Files\\View->basicOperation('rmdir', '\/0_BIMM\/00000_b...', Array)\n#9 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/directory.php(246): OC\\Files\\View->rmdir('\/0_BIMM\/00000_b...')\n#10 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Tree.php(179): OC\\Connector\\Sabre\\Directory->delete()\n#11 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(287): Sabre\\DAV\\Tree->delete('0_BIMM\/00000_b....')\n#12 [internal function]: Sabre\\DAV\\CorePlugin->httpDelete(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#13 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#14 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:DELETE', Array)\n#15 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#16 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(56): Sabre\\DAV\\Server->exec()\n#17 \/var\/www\/owncloud\/remote.php(137): require_once('\/var\/www\/ownclo...')\n#18 {main}","File":"\/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/NativeState.php","Line":66}

**Comment by cooper-42** [comment]
Some additional informations:
I can rename files and folders without a problem.

**Comment by PVince81** [comment]
Try upgrading your Samba to 4.2. I heard that older Samba versions had trouble with DFS. (that is, if you're connecting to DFS shares)

**Comment by PVince81** [comment]
Is this still happening with 9.0.3 or 9.1.0RC1 and Samba > 4.2 ? There were some updates to the Icewind/SMB lib.
