### ISSUE TITLE
loading-icon-dark still showing in navigation if user stays on page during file upload

### ISSUE THREAD

**Issue by JackWillDavis** [owncloud/core#20766]
When clicking through the navigation menu in the top left, the icon is replaced with a loading gif.

If a user is uploading a file and attempts to move pages, a pop up warning appears saying there is a file upload in progress. At that stage, if the user stays on the page to complete the upload, the navigation icon should be restored to the default.

At the moment, if the user stays on the same page, the loading gif still continues to display in the navigation.

This is in the main Files section. Windows 7, Chrome 46.0.2490.86.

**Comment by jancborchardt** [comment]
Yeah, good design detail catch! :) Since you seem familiar with pull requests already – do you want to submit a fix yourself?

You’re also very welcome in our IRC channels #owncloud-design (and #owncloud-dev if you have any code questions or need help)! Welcome to ownCloud :)

**Comment by JackWillDavis** [comment]
OK, I'll create a pull request when I've got a fix for it and leave the link here.

Thanks!

**Comment by JackWillDavis** [comment]
https://github.com/owncloud/core/pull/20926
