### ISSUE TITLE
Downgrading is not supported and is likely to cause unpredictable issues (from 8.2.1.4 to 8.1.4.2)

### ISSUE THREAD

**Issue by cracker0dks** [owncloud/core#20774]
Hey, 
I updated my owncloud server successfully to 8.2.1 everything was fine. 
Then i run: 

    sudo apt-get update && apt-get dist-upgrade 

because owncloud told me that my php version was not up to date. 
Now I can't login anymore and I get this message on the Owncloud page:

    Downgrading is not supported and is likely to cause unpredictable issues (from 8.2.1.4 to 8.1.4.2)

what can I do? Did not found anything on the net.
Thanks :)

**Comment by RealRancor** [comment]
Hi,

when running apt-get dist-upgrade you have exactly done what the message is telling you.

Please close here and use either the users mailinglist or the forums for support questions like this.

**Comment by cracker0dks** [comment]
ok ty
