### ISSUE TITLE
Certificate of website apps.owncloud.com expired

### ISSUE THREAD

**Issue by hitam4450** [owncloud/core#20779]
This morning I wanted to check https://apps.owncloud.com/index.php an received from ff42.0 the error message:

This site cannot be trusted.

apps.owncloud.com verwendet ein ungültiges Sicherheitszertifikat. Das Zertifikat ist am 27.11.2015 03:40 abgelaufen.
Die aktuelle Zeit ist 27.11.2015 07:55. (Fehlercode: sec_error_expired_certificate)

Sorry, for german language!

What is to do??

regards, hitam4450

_________________

**Comment by rullzer** [comment]
@karlitschek

**Comment by nickvergessen** [comment]
https://github.com/owncloud/appstore-issues/issues/36
