### ISSUE TITLE
Applications-Selections-Surface,downloader-decompress_to_apps

### ISSUE THREAD

**Issue by blackcrack** [owncloud/core#20777]
Hi,

we need an Ass, Applications Selections Surface for downloading from 
apps.owncloud.com , extract to ./apps/ and make possible with it for 
see clearly, selecting and (downloading&) installing, like in KDE the themes, but
there in the Admin-webinterface-> Apps->Popup [Selecting and installing OC-Apps]

Ass, so, letzt'z Play with the Card's ;)

[as suggestion,
i have to less time for coding that's at the next time..
have prove me in my new Job.. at first.. a year long..
for have an save job..]

best regards
Blacky

**Comment by DeepDiver1975** [comment]
Apps can be downloaded from the appstore using the apps management page in ownCloud.

**Comment by blackcrack** [comment]
in 8.2 ? i have 8.1.1 or something .. and there it is only "activate" and not "activate"
and no "downloader/manager" where is makes possible to browse the apps from apps.owncloud.com ..
:\ 
and at bottom at the gear icon , it's only a checkbox foe experimental apps ..
i can may wrong.. but i don't see an manager ..:\
http://www.blackysgate.net/files/upload/owncloud/Screen00000.jpg
http://www.blackysgate.net/files/upload/owncloud/Screen00001.jpg

by the way, when's comes the stabile 8.2 for the updater ? *s* *pry*

best regards
Blacky
