### ISSUE TITLE
Issues with Small/Big Letters - OC 8.x

### ISSUE THREAD

**Issue by andi-at** [owncloud/core#20778]
Hello,

I´ve got an sync error due to small/big letters on windows & mac clients. A CAD-Program seems to rename some files, i dont know what happens exactly. But i´ve got an error for syncing a file, when i look at the server i find that the problematic file is 2 times there:
FILE.DWG
file.dwg

The files have two different dates, so after deleting the old one everything is fine. Seems that owncloud differs the two files, but windows & mac doesn´t an therefore they see two versions of the same file on the server.

Upgrading server&client to the latest version didn´t help, but deleting one of them helped. Mabe you can fix that?

best regards,
andi

**Comment by nickvergessen** [comment]
Please use the issue template to provide the necessary information
https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version

**Comment by MorrisJobke** [comment]
Client handles this properly and shows an error message:

<img width="781" alt="bildschirmfoto 2016-02-14 um 20 33 38" src="https://cloud.githubusercontent.com/assets/245432/13035893/592470de-d35a-11e5-9b0e-2afc3cfb79e7.png">
<img width="1108" alt="bildschirmfoto 2016-02-14 um 20 33 47" src="https://cloud.githubusercontent.com/assets/245432/13035891/5921ba88-d35a-11e5-8553-61587e57c97a.png">
