### ISSUE TITLE
OC 8.2.1: Can't rename files/folders via webinterface

### ISSUE THREAD

**Issue by tflidd** [owncloud/core#20776]
When hovering over a file or folder, there was a pencil which allowed me to edit the file/folder-name. On OC 8.2.1 there is no pencil any more. I can open the menu on the right but I didn't see a way to edit the filename. Is there a new trick?

The interface is like on:
demo.owncloud.org

**Comment by DeepDiver1975** [comment]
![bildschirmfoto von 2015-11-27 11-20-43](https://cloud.githubusercontent.com/assets/1005065/11439013/eef32808-94f8-11e5-9f15-95a88ba0abf4.png)

**Comment by tflidd** [comment]
I prefer the way it was before. Is there a reason everything is put there, the screen would be large enough (on desktop computers) to show all symbols directly?
