### ISSUE TITLE
Merge versions app into activity app or show more info on versions app

### ISSUE THREAD

**Issue by mafigo** [owncloud/core#20783]
I find myself going back and forth between the activity and the versions app when I need to restore/download a version of a file because in the versions app there isn't the user o created the version.
I can think off to approaches for this:
1- Merge the two apps in to one, which I think that's a more elegant solution because basically both are showing the same information, and when reviewing the activity a user can choose to download that version or revert to that version.

![image](https://cloud.githubusercontent.com/assets/13766132/11437606/002d3d28-94e7-11e5-9310-ec6202f9acff.png)

2- Add the user information to the versions app.

![image](https://cloud.githubusercontent.com/assets/13766132/11437614/09275724-94e7-11e5-8f61-454d1db97272.png)

I do really think this proposed enhancement will improve user usability.

**Comment by jancborchardt** [comment]
As said previously I totally think that the representation in the interface of Versions and the correlating file changes and deletions in the interface **should be connected**. They belong together and it’s for a purely technical reason (they are separate apps) that they are currently separated.

Interface-wise, every change and delete activity could have a 3-dot menu (same as for the file actions) which will reveal the actions:
- View this version
- Download
- Restore this version

How it’s done technically is a completely different discussion. Of course the app code should ideally not be merged, but we’re talking about the interface here.

@mafigo can you reopen this issue in https://github.com/owncloud/core/issues please? This issue tracker is only for the apps in this repository.

cc @owncloud/designers @karlitschek

**Comment by PVince81** [comment]
@pmaier1
