### ISSUE TITLE
Inconsistency in icons for checkmark and cross

### ISSUE THREAD

**Issue by raghunayyar** [owncloud/core#20780]
I think the thickness of the .icon-checkmark-white and .icon-cross is inconsistent, they look like belonging to different icon families. Shouldn't they be consistent with each other?

@jancborchardt @owncloud/designers what do you think?

**Comment by jancborchardt** [comment]
Yeah, can you adjust the checkmark accordingly @raghunayyar? (Don’t forget to compress it.)
