### ISSUE TITLE
3rdparty packages blocked upgrades

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#20787]
With our list of outdated packages shrinking (see [versioneye](https://www.versioneye.com/user/projects/54d1f76f3ca0840b190000c0)). We run into some packages that we can't update at the moment.

I indent to keep this list up to date so we have an overview why certain packages are not updated

By php version

| package | Reason |
| --- | --- |
| >=sabre/event-3 | requires >=php-5.5 |
| >=sabre/vobject-4 | requires >=php5.5 |
| guzzlehttp/guzzle | requires  >=php5.5 |
| >=symfony/process-3 | requires >=php5.5.9 |
| >=symfony/routing-3 | requires >=php5.5.9 |
| >=symfony/console-3 | requires >=php5.5.9 |
| >=symfony/event-dispatcher-3 | requires >=php5.5.9 |
| >=doctrine/common-2.6 | requires >=php5.5 |

Other:

| package | Reason |
| --- | --- |
| rackspace/php-opencloud | requires somebody with swift knowledge to fix what break in OC |
| guzzle/parser | blocked by php-opencloud |
| guzzle/http | blocked by php-opencloud |
| guzzle/common | blocked by php-opencloud |
| guzzle/stream | blocked by php-opencloud |

@DeepDiver1975 as discussed
@cmonteroluque FYI

**Comment by rullzer** [comment]
It should be noted that the `guzzle/*` pacakges are deprecated. Which raises the question if we should be looking into alternatives.

**Comment by DeepDiver1975** [comment]
> It should be noted that the guzzle/* pacakges are deprecated. Which raises the question if we should be looking into alternatives.

as soon as we upgrade php-opencloud this will resolve itself - right?

**Comment by rullzer** [comment]
> as soon as we upgrade php-opencloud this will resolve itself - right?

Nope :( Even php-opencloud master still uses the old guzzle packages.. https://github.com/rackspace/php-opencloud/blob/working/composer.json#L26

**Comment by DeepDiver1975** [comment]
but then we are talking about an alternative to php-opencloud :wink:

**Comment by rullzer** [comment]
O yes. That is what I meant :P sorry.

For the time being we should try to upgrade to the latest version. But yeah probabaly good to think about how we want to deal with deprecated packages that are still required.

**Comment by MorrisJobke** [comment]
> It should be noted that the guzzle/* pacakges are deprecated. Which raises the question if we should be looking into alternatives.

They are simply named guzzlehttp now ;)

**Comment by MorrisJobke** [comment]
> They are simply named guzzlehttp now ;)

https://github.com/guzzle/guzzle#version-guidance

**Comment by rullzer** [comment]
@MorrisJobke I know. But then php-opencloud should use them... We have guzzlehttp also in 3rdparty.

**Comment by MorrisJobke** [comment]
> @MorrisJobke I know. But then php-opencloud should use them... We have guzzlehttp also in 3rdparty

Hehe. They migrated to a new repo and bumped the version from 1 to 2 with breaking changes: https://github.com/rackspace/php-opencloud/issues/586#issuecomment-127661631

**Comment by MorrisJobke** [comment]
It's now named `php-opencloud/openstack` and has API changes....so our object store guru @butonic is needed here :see_no_evil:

**Comment by MorrisJobke** [comment]
> It's now named php-opencloud/openstack and has API changes....so our object store guru @butonic is needed here :see_no_evil: 

... in some years because this lib is PHP >= 5.6 https://github.com/php-opencloud/openstack/blob/354c7c641fc094afed7cf17f22bf4906babccade/composer.json#L28

**Comment by rullzer** [comment]
Updated the list

Basically we see more and more packages drop php 5.4 support.

**Comment by stenstad** [comment]
https://github.com/php-opencloud/openstack is needed to support Openstack Swift using Identity v3 for authentication. This includes (amongst others) IBM Bluemix and Zetta.IO.

Identity v2 has been marked as deprecated since.. Late 2013?

**Comment by butonic** [comment]
We merged https://github.com/owncloud/core/pull/25513 \o/

Running `make` now fetches composer and will lament a missing npm I nodejs. After manualy installing I get a fow warnings on Ubuntu 16.04.1 LTS / Xenial:
```
[...]
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.
[...]
npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global marked@0.3.6 should be installed with -g
[...]
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
```
So I'll just drop this here to track stuff that could be polished:
- [ ] replace guzzle/parser, guzzle/common, guzzle/stream, guzzle/http with guzzle/guzzle
- [ ] replace wrench.js with [fs-extra](https://github.com/jprichardson/node-fs-extra)
- [ ] update minimatch
- [ ] investigate marked

**Comment by PVince81** [comment]
Guzzle 6.2: https://github.com/owncloud/core/pull/28063

**Comment by PVince81** [comment]
any update ? I think we moved forward already with many things
