### ISSUE TITLE
Can't access a shared folder on external storage

### ISSUE THREAD

**Issue by VynceCook** [owncloud/core#20800]
### Steps to reproduce
1. Share a directory on a external folder with another user
2. From the second user, try to access to the folder

### Expected behaviour
When access to the shared folder, the user should see
the files inside.

### Actual behaviour
I can share a directory with a second user. But when I log
with the second user credentials, I can't see the folder
under the "All files" section. When I select the "Shared
with you" section, I see the shared folder, but when I click
on it, I am redirected to the root directory of the "All files"
section.
It works well with a shared folder on the local storage, only
with shared folder on external storage (Dropbox and sftp).

### Server configuration
**Operating system**: Linux / Debian 8.0

**Web server:** Nginx 1.8.0

**Database:** Mysql 5.5.46

**PHP version:** 5.6.14

**ownCloud version:** 8.2.1

**Updated from an older ownCloud or fresh install:** Updated from 8.1

**List of activated apps:**
Enabled:
- activity: 2.1.3
- calendarplus: 1.1.1
- contactsplus: 1.0.9
- encryption: 1.1.0
- files: 1.2.0
- files_external: 0.3.0
- files_pdfviewer: 0.7
- files_sharing: 0.7.0
- files_texteditor: 2.0
- files_trashbin: 0.7.0
- files_versions: 1.1.0
- files_videoviewer: 0.1.3
- firstrunwizard: 1.1
- galleryplus: 14.3.0
- news: 6.1.1
- provisioning_api: 0.3.0
- rainloop: 4.8
- tasksplus: 1.0.3
- templateeditor: 0.1
- updater: 0.6
Disabled:
- documents
- external
- files_mv
- files_videojs-sublime
- gallery
- notifications
- sharelinks
- user_external
- user_ldap

  **The content of config/config.php:**
{
    "system": {
        "instanceid": "ocol0bgh0j92",
            "passwordsalt": "***REMOVED SENSITIVE VALUE***",
            "secret": "***REMOVED SENSITIVE VALUE***",
            "trusted_domains": [
                "127.0.0.1",
            "***REMOVED SENSITIVE VALUE***"
            ],
            "datadirectory": "\/var\/oc-data",
            "overwrite.cli.url": "http:\/\/127.0.0.1:8080\/owncloud",
            "dbtype": "mysql",
            "version": "8.2.1.4",
            "dbname": "ocdb",
            "dbhost": "127.0.0.1",
            "dbtableprefix": "oc_",
            "dbuser": "***REMOVED SENSITIVE VALUE***",
            "dbpassword": "***REMOVED SENSITIVE VALUE***",
            "logtimezone": "UTC",
            "installed": true,
            "memcache.local": "\\OC\\Memcache\\APCu",
            "asset-pipeline.enabled": true,
            "mail_from_address": "owncloud",
            "mail_smtpmode": "php",
            "mail_domain": "***REMOVED SENSITIVE VALUE***",
            "loglevel": 2,
            "theme": "",
            "maintenance": false,
            "trashbin_retention_obligation": "auto"

    }

}

     **Are you using external storage, if yes which one:** local/sftp/Dropbox

     **Are you using encryption:** yes

     **Are you using an external user-backend, if yes which one:** No

### Client configuration
       **Browser:** Firefox (Iceweasel 40.0.3)

       **Operating system:** Linux / Debian Testing

#### Web server error log

31.32.174.92 - - [27/Nov/2015:19:31:34 +0100] "GET /index.php/apps/files/ajax/list.php?dir=%2FCecile.InstantUpload&sort=name&sortdirection=asc HTTP/1.1" 404 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0 Iceweasel/40.0.3"
31.32.174.92 - - [27/Nov/2015:19:31:34 +0100] "GET /index.php/apps/files/ajax/list.php?dir=%2F&sort=name&sortdirection=asc HTTP/1.1" 200 2475 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0 Iceweasel/40.0.3"
31.32.174.92 - - [27/Nov/2015:19:31:34 +0100] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/1.1" 200 203 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0 Iceweasel/40.0.3"
31.32.174.92 - vincent [27/Nov/2015:19:31:34 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 2040 "-" "Mozilla/5.0 (Linux) mirall/2.0.2"

#### ownCloud log (data/owncloud.log)

{"reqId":"22uTGxVFlH9mUlFZ59Oj","remoteAddr":"31.32.174.92","app":"files_sharing","message":"Unable to get mount for shared storage '20' user 'cecile'","level":3,"time":"2015-11-27T18:31:34+00:00"}

**Comment by LukasReschke** [comment]
> {"reqId":"22uTGxVFlH9mUlFZ59Oj","remoteAddr":"31.32.174.92","app":"files_sharing","message":"Unable to get mount for shared storage '20' user 'cecile'","level":3,"time":"2015-11-27T18:31:34+00:00"}

@icewind1991 any thoughts?

**Comment by PVince81** [comment]
This is reproducible with the following steps:
1. Setup OC v8.2.1 as admin user "root"
1. Enable ext storage app
1. Create user "user1"
1. Allow personal mounts for SFTP in admin page
1. Go to personal page
1. Mount "/sftp" as SFTP mount
1. Create a folder "/sftp/sub"
1. Share "/sftp/sub" with "user1"
1. Login as "user1"

### Expected
"sub" folder appears

### Actual result
No "sub" folder and error in log as above.

Note: it works correctly for system-wide mounts.

**Comment by PVince81** [comment]
Works properly in 8.1.4 => regression.

**Comment by PVince81** [comment]
Bisect result:

There are only 'skip'ped commits left to test.
The first bad commit could be any of:
272a46ebe1a5e195a078dde74f5f2ad941923d9e
1eeca031f863a652d07ebfa2f75339232bf60dc1
a6a69ef1dfe1545e1362953803219ed6f28f71a5
37beb58c6f395523d8e2934870c5f52a8c6f6df0
c572631087e2b56aa48c87ac753447e709248234
97dbc79c16ba9d4d6c361d6f397908ef7893954d
We cannot bisect more!

**Comment by PVince81** [comment]
@Xenopathic

**Comment by PVince81** [comment]
@ice

**Comment by PVince81** [comment]
@icewind1991

**Comment by icewind1991** [comment]
https://github.com/owncloud/core/pull/20953 might fix this

**Comment by PVince81** [comment]
@icewind1991 I just tried it but it doesn't solve the problem.
It must be something else.

**Comment by icewind1991** [comment]
Fix is here: https://github.com/owncloud/core/pull/21003
