### ISSUE TITLE
Text Editor 2.0 saving errors - ownCloud 8.2.1 upgrade from 8.1.4

### ISSUE THREAD

**Issue by capnjb** [owncloud/core#20802]
As usual there are a few bumps in the road in the upgrade process.  This last one was no exception although it was a little smoother than in the past.  I had two quirks, the other is for a different forum... The one noted in the subject line is a little strange. I use this app a lot for note taking and the previous versions have worked perfectly as expected. 

In the upgrade process I upgraded the Text Editor app to version 2.0.  All seemed to work fine... the new improvements in the Text Editor make it a little nicer to use with the auto-save feature.  It works as expected when creating a text file, editing and saving with in the Files area on ownCloud.  The strange behavior occurs after to create or attempt to edit a text file on a share across the network.  You can create the text file, you can open it and edit it, however ONLY the 1st save saves OK.  All subsequent saves fail and eventually locks up the text file.  You can close it but only the 1st save EACH time you open it saves.

You would thing that there is a permissions problem; if that were so you could not create/save the file and the first save would fail as well.

Error message next the file name: Failed!

Error message when closing the text file: There was a problem saving your changes. Click to resume editing

System
ownCloud: 8.2.1
php: 5.6
OS: CentOS 7
app: Text Editor 2.0
I have the same problem on a different system
System
ownCloud: 8.2.1
php: 5.4.4
OS: CentOS 6.5
app: Text Editor 2.0

Any pointers to solve the problem would be appreciated.

DaCapn

**Comment by Xenopathic** [comment]
Please submit this issue to the [files_texteditor repository](https://github.com/owncloud/files_texteditor)

**Comment by martin-rueegg** [comment]
could also be related to https://github.com/owncloud/core/issues/20380
