### ISSUE TITLE
Users can not download shared folder

### ISSUE THREAD

**Issue by washaqq** [owncloud/core#20805]
Simply; Users can not download shared folders,

what i do is ; create folder upload new folders into created folder and share created folder, grab the share link and pass it to Users by mail. 
but when they click the link they see the folders everything is normal but when they click on download link owncloud says the file/folder can not be found.

To reproduce the problem:
1. create folder 24513
2. upload subfolder 6456-4-3
3. put something in subfolder
4. share folder 24513 as link
5. open this link and download subfolder 6456-4-3

2 different download link is produced
click the box to choose the subfolder 6456-4-3 and click to download link, it works, than i realise that owncloud produce 2 different downlod link

if i click the box to choose the subfolder 6456-4-3 to download this is the link:

index.php/s/xErUI6tcWB79MCb

but if i just click the download link without choosing the subfolder 6456-4-3 this is the link:

index.php/s/xErUI6tcWB79MCb#

Topics in owncloud forums:
started from here: https://forum.owncloud.org/viewtopic.php?f=31&t=31600
continuing in here : https://forum.owncloud.org/viewtopic.php?f=36&t=31727
 
ownCloud version: 8.2.1
Webserver: Apache
Database: MySQL
OS: Linux ubuntu 14.04
PHP version: 5.5

Error Codes so far (Logs from owncloud admin interface) : 
Invalid argument supplied for foreach() at /var/www/owncloud/apps/files_sharing/lib/controllers/sharecontroller.php#273 

Fatal	webdav	Exception: {"Message":"HTTP\/1.1 503 System in maintenance mode.","Code":0,"Trace":"#0 [internal function]: OC\\Connector\\Sabre\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n#5 \/var\/www\/owncloud\/remote.php(132): require_once('\/var\/www\/ownclo...')\n#6 {main}","File":"\/var\/www\/owncloud\/lib\/private\/connector\/sabre\/maintenanceplugin.php","Line":83}

Fatal	webdav	Exception: {"Message":"HTTP\/1.1 503 Service unavailable","Code":0,"Trace":"#0 [internal function]: {closure}(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/var\/www\/owncloud\/remote.php(64): Sabre\\DAV\\Server->exec()\n#5 \/var\/www\/owncloud\/remote.php(135): handleException(Object(RemoteException))\n#6 {main}","File":"\/var\/www\/owncloud\/remote.php","Line":55}

Error PHP Invalid argument supplied for foreach() at /var/www/owncloud/apps/files_sharing/lib/controllers/sharecontroller.php#274 2015-11-26T09:23:54+00:00

Error PHP require_once(): Failed opening required '/appinfo/remote.php' (include_path='/var/www/owncloud/3rdparty/phpseclib/phpseclib/phpseclib:/var/www/owncloud/3rdparty/pear/console_getopt:/var/www/owncloud/3rdparty/pear/archive_tar:/var/www/owncloud/3rdparty/pear/pear_exception:/var/www/owncloud/3rdparty/pear/pear-core-minimal/src:/var/www/owncloud/lib/private:/var/www/owncloud/config:/var/www/owncloud/3rdparty:/var/www/owncloud/apps:/var/www/owncloud/lib:.:/usr/share/php:/usr/share/pear:/var/www/owncloud') at /var/www/owncloud/remote.php#137 2015-11-26T09:20:34+00:00

Error PHP require_once(/appinfo/remote.php): failed to open stream: No such file or directory at /var/www/owncloud/remote.php#137

Error PHP Invalid argument supplied for foreach() at /var/www/owncloud/apps/files_sharing/lib/controllers/sharecontroller.php#274 2015-11-26T12:10:11+00:00

Error PHP Invalid argument supplied for foreach() at /var/www/owncloud/apps/files_sharing/lib/controllers/sharecontroller.php#274 2015-11-26T12:10:04+00:00
Debug core-preview Passed token parameter is not valid

**Comment by LukasReschke** [comment]
Can reproduce this one. Will check what I can do about it.

**Comment by PVince81** [comment]
I can't reproduce this on v8.2.1.
Note that I only have a single folder "6465-4-3" as per the test case.

These are the links I get:
- click "Download" on the row of the folder: http://localhost/owncloud/index.php/s/4TWPb32jG2IONME/download?path=%2F&files=6465-4-3&downloadStartSecret=8qwlj1jjvloez5mi
- select the folder by ticking the checkbox, then click "Download" in the header, this will download the whole folder since everything is selected (everything being that single row): http://localhost/owncloud/index.php/s/4TWPb32jG2IONME/download?path=%2F&files=&downloadStartSecret=07p7lq15pvdq85mi
- click "Download" on the top right of the page, the main button: http://localhost/owncloud/index.php/s/4TWPb32jG2IONME/download?path=%2F&files

All three links work.

Maybe you have an app enabled that breaks the link generation ? I don't have any app enabled.
Do you see anything in the Javascript console ?

**Comment by PVince81** [comment]
I had a quick look at the forum posts but didn't find anything that could help reproduce the issue locally.
So far it looks like an environment issue, maybe an update gone wrong, maybe code that wasn't replaced properly.

I still wonder where @LukasReschke saw it happening ?

**Comment by schiesbn** [comment]
fwiw, I just tried it and also couldn't reproduce it? @LukasReschke can you re-produce it reliable? I assume that you will work on a fix. If you need any help just ping me

**Comment by washaqq** [comment]
Hi,
sorry for the late reply, i dont have any apps enabled i had a problem after upgrade to latest version so i disabled all the apps, this issue happens if you upload folder 6465-4-3 into main folder, and share the main folder, this problem started before the upgrade and i tried to update&upgrade automatically but it didnt worked so i did it manually by following docs on ownclouds forum, but problem is not solved.

**Comment by LukasReschke** [comment]
@washaqq Can you add a `var_dump($files_list); exit();` in front of https://github.com/owncloud/core/blob/v8.2.1/apps/files_sharing/lib/controllers/sharecontroller.php#L274 in the file `apps/files_sharing/lib/controllers/sharecontroller.php`?

Then try to access the share in your browser and please let us know what the returned value is.

**Comment by PVince81** [comment]
@cmonteroluque ticket was deferred to 8.2.3 because it is not reproducible yet and it is not clear whether it's an environment issue or a bug.

**Comment by PVince81** [comment]
Closing due to lack of feedback.

If you're still seeing this issue in 8.2.3, please provide the requested info. Thanks.
