### ISSUE TITLE
Copy-on-write/storage virtualization/deduplication/you name it.

### ISSUE THREAD

**Issue by AnrDaemon** [owncloud/core#20803]
Since you are now storing file hash in the database, it should be easier to implement single file storage/copy-on-write mechanics, which in certain cases could drastically reduce storage space usage.

The simplest use case coming to mind is photo gallery, where a user dumps whole load of raw material from a camera into the cloud, then start making directories, copy and rename files around to form albums or otherwise organize the files… In current storage paradigm, this easily leads to an order of magnitude of wasted storage space.

A more sane approach would be to keep only one file for each instance of the duplicated file.

Then you could create a new separate instance for each attempt of uploading a file that already exists in the storage, separately share them, and otherwise organize the instances without duplicating an actual file in storage, until it is, actually, changed.

**Comment by karlitschek** [comment]
We consider a feature like that out of scope for ownCloud. This can be done by a filesystem like zfs or btrfs. We don't want to reimplement filesystem features in ownCloud. I hope this makes sense for you.

**Comment by AnrDaemon** [comment]
No, this doesn't make sense to me.
I have no control over filesystems in different storage adapters ownCloud supports.
And to me this is a logical next step in hash-based synchronization.
"Don't Repeat Yourself" is one of the major principles of sanely operating software.
