### ISSUE TITLE
Sign responses from the update server

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#20810]
As described in https://github.com/owncloud/core/pull/20809 responses from the update server should be signed. Can be done using the CA from https://github.com/owncloud/core/pull/20285.

**Comment by LukasReschke** [comment]
cc @karlitschek FYI

**Comment by RealRancor** [comment]
Also something for the updater app: https://github.com/owncloud/updater/issues/194 ?

**Comment by PVince81** [comment]
CC  @VicDeo

**Comment by VicDeo** [comment]
Err... Does this mean that I will need to purchase a cert in order to be able just to test the process on localhost?

**Comment by LukasReschke** [comment]
> Err... Does this mean that I will need to purchase a cert in order to be able just to test the process on localhost?

![3115744](https://cloud.githubusercontent.com/assets/878997/11486071/f779f34c-97b6-11e5-84fc-7daaf941810d.jpg)

Actually the CA is also controlled by ownCloud, see https://github.com/owncloud/core/pull/20285
