### ISSUE TITLE
UTF-8 support different on User Provisioning API function calls

### ISSUE THREAD

**Issue by jgrete** [owncloud/core#20817]
I'm trying to do some operations on an owncloud 8.2 instance by using the User Provisioning API.
I've written a small bash script which basically hides the API and and provides a very narrow and simple interface. Within this script I'm using curl to communicate with the API.
I'm running into problems when I'm trying to add a group which has german umlauts in its name (e.g. "Däst"). I'm getting a statuscode 101/message 'Invalid group name'. 
Adding the same group name by using the OC webinterface succeeds.

The strange thing is that <i>I can delete the group by using my script without any problems!</i>

This is the curl call to add a group (no success):
<code>curl --netrc-file $credentials_file -X POST -k $base/groups -d groupid="$1" </code>
I also tried the variation "groupid=$1", no success
  
This call deletes the group successfully:
<code>curl --netrc-file $credentials_file -X DELETE -k $base/groups/"$1"</code>

my locale settings:
<code>LANG=de_DE.UTF-8</code>
<code>LC_CTYPE="de_DE.UTF-8"</code>
<code>LC_NUMERIC=de_DE.UTF-8</code>
<code>LC_TIME=de_DE.UTF-8</code>
<code>LC_COLLATE=de_DE.UTF-8</code>
<code>LC_MONETARY=de_DE.UTF-8</code>
<code>LC_MESSAGES="de_DE.UTF-8"</code>
<code>LC_PAPER="de_DE.UTF-8"</code>
<code>LC_NAME="de_DE.UTF-8"</code>
<code>LC_ADDRESS="de_DE.UTF-8"</code>
<code>LC_TELEPHONE="de_DE.UTF-8"</code>
<code>LC_MEASUREMENT=de_DE.UTF-8</code>
<code>LC_IDENTIFICATION="de_DE.UTF-8"</code>
<code>LC_ALL=</code>

The owncloud instance lives on a OpenSuse 13.2 machine
php 5.6, Apache 2.4.10, mysql 5.6.26

I have not startet a systematic test of all API calls yet, so this behaviour might be shown by
other API calls too.

Regards
Juergen

**Comment by PVince81** [comment]
Can you try with the locale en_US.UTF-8 just in case ? (shouldn't matter, but who knows...).

You might need to url encode the names.

CC @SergioBertolinSG

**Comment by PVince81** [comment]
@tomneedham mind taking a look at this ?

**Comment by tomneedham** [comment]
Likely because of this https://github.com/owncloud/core/blob/master/apps/provisioning_api/lib/groups.php#L133. Will take a look on Wednesday.

**Comment by PVince81** [comment]
Note: the web UI doesn't allow to create users with special chars, however it allows group names with special chars like umlauts.

**Comment by jgrete** [comment]
Hello PVince81,
reading tomneedham's comment I think it's needless to try it with activated locale en_US.UTF-8, isn't it? I've taken a look into the source he pointed to and think just searching the log for the errormessage would be sufficient. I'll do that in th evening today or tomorrow. It looks like we have to live with "umlautless" groupids :-)
Regards
Jürgen

**Comment by DeepDiver1975** [comment]
> Note: the web UI doesn't allow to create users with special chars, however it allows group names with special chars like umlauts.

so looks like we need to sync the name verification
