### ISSUE TITLE
invoicing

### ISSUE THREAD

**Issue by wayneward** [owncloud/core#20814]
ive had a good look around and not found any invoicing, i found one project but its empty
if you could select people from the address book to invoice and another drop box that you can add services and a calendar to select date owncloud could provide simple invoicing
its the only thing i can think thats missing from owncloud 
this would be awesome
unless there is already a project that plugs in?

**Comment by thomas-p-wilson** [comment]
I believe that @wayneward is referencing my owncloud invoicing project, which I never got started on. I'd be more than happy to contribute invoicing functionality to core, as this is only my list of todos anyway!

**Comment by PVince81** [comment]
I don't think invoicing is in the scope for core, would be better implemented as a separate app.
The only part that might be scoped for core is if there are some missing APIs to access information (like per-user storage quota usage, which has another ticket already which I can't find for some reason)

**Comment by thomas-p-wilson** [comment]
I most assuredly did not expect that invoicing would be part of the core
functionality of Owncloud. I think the issue here was meant more for
discovery than anything else. I'm currently working on an invoicing plugin
elsewhere. I believe you may close this issue at your leisure.
