### ISSUE TITLE
ubuntu touch support

### ISSUE THREAD

**Issue by wayneward** [owncloud/core#20812]
ive got owncloud integrated into my ubuntu phone 
used a script to add the contacts and calendar and this syncs with cron script on the hour
and i have the data syncing again with scripts on a cron on the hour
be nice to just be able to add the calendar and contacts in gui i guess thats down to developers at ubuntu but a owncloud client would be great that would detect changes etc
its working cap in hand with the phone and laptop
also be nice for a front end app that will show the to do lists from owncloud or maybe a scope?...

thank you

**Comment by PVince81** [comment]
This is the bug tracker for ownCloud server, probably not the right place for app wishes.
You might want to try on Ubuntu side if you can find developers willing to develop such app.

**Comment by jospoortvliet** [comment]
@wayneward even without app, good to hear you managed to get some stuff integrated. Perhaps you're interested in helping me write a blog post about that? Maybe somebody sees it and decides to write an Ubuntu App ;-)
