### ISSUE TITLE
Update to 8.2.1 unsuccessful

### ISSUE THREAD

**Issue by KMPR8** [owncloud/core#20813]
after starting the requested/offered update I ended up with this message, whenever I start my owncloud now:

Aktualisiere ownCloud auf Version 8.2.1. Dies könnte eine Weile dauern.

Update vorbereiten
Log-Level auf Debug gesetzt - aktuelles Level: "Warning"
Wartungsmodus eingeschaltet
Exception: Updates between multiple major versions and downgrades are unsupported. 

how do I get out of this, back/forward to a working owncloud.

Kindest regards, Klaus

**Comment by LukasReschke** [comment]
> Exception: Updates between multiple major versions and downgrades are unsupported.

Simple: You cannot update from ownCloud 8 to ownCloud 8.2, update to ownCloud 8.1 first.

**Comment by KMPR8** [comment]
how can I update from 8 to 8.1, when 8.2 is already in the pipeline? 
Would be grateful for any advise!
KMP

**Comment by RealRancor** [comment]
@KMPR8 Get 8.1.4 from https://owncloud.org/changelog/ and manually install that first before upgrading to 8.2.1
