### ISSUE TITLE
Idea: use If-None-Match with etag for directory PROPFIND

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#20820]
When doing a PROPFIND on a directory, a client could send the already known etag in the "If-None-Match" header. Then the server could check if the directory etag matches, and if it does, it could return "304 Not Modified" instead of a full content.

This could save a bit of computation, at least when retrieving directory contents and creating the XML response for bigger directories.

I checked the Sabre code and "If-None-Match" is currently only checked for files (`IFile`) and not directories. See https://github.com/fruux/sabre-dav/blob/e09b67f2e66b51436bd5902a145db1b85e7d8ae7/lib/DAV/Server.php#L1266
Maybe the standard doesn't allow for this ? @evert

We could still create a plugin that does this check additionally for directories, if that makes sense.

@DeepDiver1975 @guruz @ogoffart @icewind1991

**Comment by guruz** [comment]
@PVince81 In theory good idea :-)
In practice not needed.

For checking if we should start a sync, we only check with ```Depth: 0``` so only the folder entry itself is received.
If that leads to an Etag change, we start the sync and list the directory with ```Depth: 1```.
Then for each directory entry received, we only recurse into it if the Etag changed. So we don't even request that subdirectory.

**Comment by ogoffart** [comment]
Note that in 2.1, the client only does `Depth:0`  (But only if trhe server is more than 8.1,  because the older server had a bug that would not update the root etag)

**Comment by evert** [comment]
It indeed doesn't work for non-files, because etags should be meaningless. Owncloud overloads the etag to mean something it's not. While you can certainly hack it in to make it work, the proper solution is to use WebDAV-Sync instead: http://sabre.io/dav/sync/.

This will allow you to pass sync-tokens to the `If:` header, which is a much more powerful version of `If-Match` / `If-None-Match`.

**Comment by PVince81** [comment]
Okay, fair enough. Thanks for the feedback :smile: 

I'll close this then.
