### ISSUE TITLE
Sign SuperClosure closures

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#20826]
Ref https://github.com/jeremeamia/super_closure#signing-closures

**Comment by LukasReschke** [comment]
@icewind1991 Any objections? THX

**Comment by PVince81** [comment]
@Peter-Prochaska thoughts ?

**Comment by Peter-Prochaska** [comment]
@PVince81 How often do we (want to) serialize closures?

**Comment by DeepDiver1975** [comment]
I'm not sure if it is used anywhere as of today .....
