### ISSUE TITLE
Can't Update from 8.2.0 to 8.2.1

### ISSUE THREAD

**Issue by JoergiVreden** [owncloud/core#20823]
I got this Error when i try to upgrade with "sudo -u www-data php occ upgrade" and have now idea what i´ve to do.

An unhandled exception has been thrown:
exception 'UnexpectedValueException' with message 'Unable to detect system temporary directory' in /share/web/oc/lib/private/tempmanager.php:242
Stack trace:
```
#0 /share/web/oc/lib/private/tempmanager.php(53): OC\TempManager->getTempBaseDir()
#1 /share/web/oc/lib/private/server.php(367): OC\TempManager->__construct(Object(OC\Log), Object(OC\AllConfig))
#2 /share/web/oc/3rdparty/pimple/pimple/src/Pimple/Container.php(112): OC\Server->OC\{closure}(Object(OC\Server))
#3 /share/web/oc/lib/private/appframework/utility/simplecontainer.php(104): Pimple\Container->offsetGet('TempManager')
#4 /share/web/oc/lib/private/server.php(919): OC\AppFramework\Utility\SimpleContainer->query('TempManager')
#5 /share/web/oc/lib/base.php(648): OC\Server->getTempManager()
#6 /share/web/oc/lib/base.php(1081): OC::init()
#7 /share/web/oc/console.php(42): require_once('/share/web/oc/l...')
#8 /share/web/oc/occ(11): require_once('/share/web/oc/c...')
#9 {main}root@NAS:/share/web/oc# 'Unable to detect system temporary directory'Unable to detect system temporary directory^C
```

**Comment by PVince81** [comment]
Please check your PHP configuration. Maybe the functions "sys_get_temp_dir" are disallowed or your temp directory is not writable.

**Comment by JoergiVreden** [comment]
Where is the temp directory stored? Where, How can i allow the function sys_get_temp_dir?
I had never problems with updating before.

**Comment by PVince81** [comment]
Possible "/tmp". Not sure what sys_get_temp_dir usually returns.
This has nothing to do with updating, but will affect a running OC instance too.

Try executing this php script:
```php
<?php
print(sys_get_temp_dir());
```

Mine returns "/tmp". Then check if your web server has permissions to write there.
Disabled functions can be usually found in php.ini.

**Comment by JoergiVreden** [comment]
It says /tmp 
I didn't find sys_get_temp_dir in the php.ini
There was no tmp folder. I tried to create it manualy and set the owner and group to www-data and chmod to 777. But the upgrade does not work.

**Comment by JoergiVreden** [comment]
Perhaps this helps you. Owncloud is running in a RasberryPi with rasbian and PHP 5.4.45-0+deb7u2

**Comment by JoergiVreden** [comment]
I don't know why but now the upgrade worked. But now i've another problem. I can login but then it shows only a white website. Any idea?

**Comment by PVince81** [comment]
Please note that this is a bug tracker, not a support platform.

To get proper support from people who might have similar issues, see https://owncloud.org/support

Also without any logs it will be impossible to help you.

**Comment by enoch85** [comment]
@JoergiVreden I'm guessing that your config.php is misconfigured. Please close this issue as the original problem is solved. Thanks.
