### ISSUE TITLE
remove app icon from app menue without deactivate the app or group-permissions

### ISSUE THREAD

**Issue by stefkey** [owncloud/core#20822]
Hi,

where can I control the icons from the app-menue?
I would like one oder two icons remove from the liste without deactivate the app.
In styles.css the apps are not width id for display: none :-(

Thanks a lot!

**Comment by karlitschek** [comment]
thanks for your question. this is not a bug and not a feature request. So I'm closing this. I recommend to ask your question on the developer mailinglist or in the forum. thanks
