### ISSUE TITLE
Task for PHPUnit optimizations

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#20833]
There have already been some code pieces to look into:
- [ ] Why do unit tests for preview generation require database access? (Yes - filesystem foo - but could be structured differently)
- [ ] Pure tests on the server container - why? 
- [ ] DIContainerTest
- [x] avatar tests
- [x] avatar controller tests #20510
- [ ] stream wrapper tests
- [ ] OCA\Provisioning_API\Tests\AppsTest needs mocks
- [ ] ShareControllerTest needs to mock file system
- [ ] All LDAP unit tests require DB access - even those who already mock IConfig etc :fish: -y
- [ ] Test_UrlGenerator - basically the UrlGenerator needs to inject the router object
- [ ] https://github.com/owncloud/core/issues/20771
- [ ] Test_Util_CheckServer on postgresql

TODO:
- review all unit test in group DB - is real database access really required here?
- review all still failing unit tests - is real database access required?
- think about more separation of existing classes to get more isolated testing (e.g. preview generation)

**Comment by PVince81** [comment]
Please tick boxes if anything has been done in between.
Tech debt, moving to 9.1
