### ISSUE TITLE
List of apps availables from CLI doesn't match reality

### ISSUE THREAD

**Issue by nabab** [owncloud/core#20838]
On latest version (8.2.1), I am trying to create a command line script to install Owncloud, but it seems I cannot list or enable all the apps really availables.
If I do ./occ app: list, I get this:

Enabled:
  - activity: 2.1.3
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - updater: 0.6

Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap

However, in the web client, I have bookmarks, documents, calendar, which are disabled. If I try to enable them from CLI:
./occ app:enable bookmarks
I get:
bookmarks not found

Now, if I enable it from the GUI it works, then appear in the app:list, and from that moment I can enable and disable it from the command line. The exact same scenario happens with any app which is not present in the list, and is in fact outside of the categories Enabled and Disabled.
I think to remember that in the disabled apps, I could see all of them. Now if documents is disabled I see it in Productivity but not in Disabled.

Subsidiary question: how can I change the value of the configuration var "trusted_domains" from the CLI?

Many thanks!

**Comment by karlitschek** [comment]
this is an expected behavior. occ can only enable and disable apps that already exist on the server. the webinterface has the advanced feature to download apps from apps.owncloud.com. This is the case for bookmarks for example.

**Comment by karlitschek** [comment]
i suggest to ask the other questions at owncloud.org/support

**Comment by nabab** [comment]
Thanks!
Is the process of downloading and activating an app from the command line documented?
And by any chance do you know the answer to my last question? All parameters passed to config:system:set are taken as string.
Cheers

**Comment by nabab** [comment]
Sorry I hadn't seen, will do right away
