### ISSUE TITLE
Sharing a file allows you to set create permissions

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#20839]
![share](https://cloud.githubusercontent.com/assets/45821/11474312/997b735e-9777-11e5-89b2-75f974b9074d.png)

The webinterface allows us to set create permissions on files. This does not make any sense since on the FS files do not even have create permissions (so we increase the permissions for a shared file). I also would have no idea what this would mean.

The old sharing code actually happily allows you to set create permissions. However nothing bad (usually) happens since the actions create gives you are not valid for files anyway.

We should remove the craete permissions from the webinterface.

CC: @PVince81

**Comment by rullzer** [comment]
The new sharing code actually does not allow this. Since it checkes if we do not increase permissions.

**Comment by PVince81** [comment]
Looks like it was introduced by the move to Webdav. "data-sharepermissions" isn't computed the same it seems.

**Comment by PVince81** [comment]
Fix must be done here: https://github.com/owncloud/core/blob/master/core/js/files/client.js#L297
This is the Webdav permission to OC permission conversion.

**Comment by rullzer** [comment]
PR in #21163
