### ISSUE TITLE
View Sharing Information for Folders Shared To You

### ISSUE THREAD

**Issue by moheinz** [owncloud/core#20848]
When folders or objects are shared to you, you should be able to view who is shared on that object.

We are going to heavily use server to server sharing with our subsidiary company.  However, when a folder or object is shared to a user, you cannot see who else is shared on the folder and what access they have.  This is a security risk because in order to really feel confident placing documents or objects in a shared folder, you really need to know everyone that has access and what access they have.

Thanks for your help and attention on this.

**Comment by jancborchardt** [comment]
Yeah, this is planned for the sharing rework. cc @owncloud/sharing – I guess we can close this in favor of another issue or already work-in-progress PR?

**Comment by moheinz** [comment]
Awesome news, thanks.
