### ISSUE TITLE
Gnome Shell Account Online Owncloud Calendar

### ISSUE THREAD

**Issue by danjde** [owncloud/core#20849]
Hi friends,
I've set up my Owncloud Server, and now I've set up a Owncloud simple user on Gnome Shell Account Online.

Now I can read and write files and documents from Nautilus/File, but I cannot see the appointments on Gnome Calendar Panel. Is it necessary Evolution?

Before, I had configured google account with Gnome Shell Account Online (without Evolution) and the calendar worked well.

many thanks!

davide

**Comment by LukasReschke** [comment]
This is more a question for the forums. THX 

forum.owncloud.org
