### ISSUE TITLE
knowledgebaseenabled doesn't seem to work

### ISSUE THREAD

**Issue by stevejordi** [owncloud/core#20857]
owncloud 8.2.1
CentOS6

config.php
'knowledgebaseenabled' => 'false'

The Help menu doesn't disappear from the top right menu (which contains Personal, Help, Log Out)
Tried on three different servers and configurations.

**Comment by DeepDiver1975** [comment]
> owncloud 8.2.1

community edition or enterprise?

**Comment by stevejordi** [comment]
Commmunity, sorry

**Comment by DeepDiver1975** [comment]
use 

```php
'knowledgebaseenabled' => false
