### ISSUE TITLE
Apache 2.4.17 can break clean URL handling

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#20856]
Not quite sure if this really fits in here but want to post it anyway for discussion:

> Some experimentation revealed that clean URL handling no longer worked, though ?q=foo did. I eventually realized that an upgrade from Apache 2.4.16 to 2.4.17 was responsible. Under some configuration conditions - possibly requiring FastCGI - several server variables have changed.

Source: https://www.drupal.org/node/2603696

An user reported such an issue together with ownCloud at the forums:

https://forum.owncloud.org/viewtopic.php?f=32&t=31570

**Comment by RealRancor** [comment]
Might be related to https://github.com/owncloud/core/pull/17491

**Comment by PVince81** [comment]
@LukasReschke

**Comment by rickard2** [comment]
I'm currently facing the same issue after upgrading to apache 2.4.17

Maybe I can help out with testing or something. Will roll back to 2.4.16 for now

**Comment by oparoz** [comment]
Apparently it only affects people who install ownCloud in a folder, but that Apache change breaks a lot of apps when using PHP-FPM.

**Comment by rickard2** [comment]
I tried moving ownCloud onto a separate domain, but still had the same issue. Can try it again to verify if needed.

**Comment by RealRancor** [comment]
The main question is:

Is this simething which should be fixed on oC side?

**Comment by RealRancor** [comment]
> It seems that Apache is going to revert that change for 2.4.18.  x-ref
>
>https://bz.apache.org/bugzilla/show_bug.cgi?id=57785
>
>http://svn.apache.org/viewvc?view=revision&revision=1712268
>
>Or rather, not quite revert it, but make it configurable, with the default off.  Applying the patch from SVN on top of 2.4.17 (doesn't apply cleanly to CHANGES and manual, but the code does fine) puts things back to normal.
>
>Doesn't really help until the .18 release, of course.  And since it's configurable, PHP probably >still needs to handle it for cases where it's turned on.

from https://bugs.php.net/bug.php?id=70757

**Comment by oparoz** [comment]
Thanks!

**Comment by PVince81** [comment]
From what I see Apache 2 is on 2.4.20 at least here on Tumbleweed.
If this is still an issue, please reopen.

**Comment by rickard2** [comment]
Seems to be working now with apache 2.4.20
