### ISSUE TITLE
Internal Server Error on port 80

### ISSUE THREAD

**Issue by psychok7** [owncloud/core#20858]
Hey there, so i started getting this `Internal Server Error` when i try to access owncloud through the Port `80` (running Apache) and i have no idea why this is happening. If i access through `8080` with the development server instead it works. Any ideas?

This is the traceback:

```
Technical details

    Remote Address: 10.0.0.1
    Request ID: lTVeXZXT7iiiBjsD8k8V
    Type: ErrorException
    Code: 0
    Message: session_start(): open(/var/lib/php5/sess_072t4vea2v5vtr5hr22bd7kpn2, O_RDWR) failed: Permission denied (13)
    File: /var/www/lib/private/session/internal.php
    Line: 106


Trace

#0 [internal function]: OC\Session\Internal->trapError(2, 'session_start()...', '/var/www/lib/pr...', 44, Array)
#1 /var/www/lib/private/session/internal.php(44): session_start()
#2 /var/www/lib/base.php(399): OC\Session\Internal->__construct('octzgkr7ygax')
#3 /var/www/lib/base.php(556): OC::initSession()
#4 /var/www/lib/base.php(1061): OC::init()
#5 /var/www/index.php(37): require_once('/var/www/lib/ba...')
#6 {main}
```

**Comment by Xenopathic** [comment]
You need to correctly configure Apache with the PHP session directory. If you need any assistance I'd suggest posting on the forums, since this is a configuration issue.

**Comment by psychok7** [comment]
@Xenopathic you guided me in the correct direction i fixed it with `sudo chown -R www-data:www-data /var/lib/php5/` thanks anyways
