### ISSUE TITLE
Update bubble menu actions

### ISSUE THREAD

**Issue by Patt92** [owncloud/core#20862]
Hello all,

just stepped about it, while updating my app. It seems to be impossible to change fileactions in the bubble menu, because the code is not present, if the menu is closed, I haven't found a solution to change the code for a bubble menu action. My app is showing a state as action displayname, but no way to change it.

**Comment by MorrisJobke** [comment]
cc @PVince81

**Comment by PVince81** [comment]
The idea is to make it possible to pass a `function` to the attribute "name" file action when calling `registerAction`. That function can then compute the name at the time where the name is retrieved.

**Comment by PVince81** [comment]
@Patt92 in 9.0 you'll be able to pass a function to "displayName": https://github.com/owncloud/core/pull/21153

You'll receive the file action context (similar to what the action handler function receives).
Based on this info, you can compute the display text of the action.

You might need to add some additional `data-xxx` attributes on the "tr" row to be able to read them from that function. See the linked PR for an example.

**Comment by PVince81** [comment]
This is the example: https://github.com/owncloud/core/pull/21153/files#diff-6cfa15099b7891cdc06cd1108f80438fR620
