### ISSUE TITLE
Browser:Chrome. 404 error occurs when closing a txt file and there is no preview due to it was not edited.

### ISSUE THREAD

**Issue by davitol** [owncloud/core#20863]
### Steps to reproduce

1. In files view create a text file
2. WIthout editing it open the text file
3. Close the filetext editor

### Expected behaviour

No error should happen

### Actual behaviour

404 (Not Found) error occurs when closing the file and there is no preview due to it was not edited.
Note: Using Firefox as browser it works fine

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:**ownCloud Enterprise Edition 8.2.1 (stable)

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
 Chrome.

![screen shot 2015-12-01 at 13 00 31](https://cloud.githubusercontent.com/assets/10596560/11500263/4d54db5e-982c-11e5-9d2b-d13f539f0e59.png)

**Comment by PVince81** [comment]
@cmonteroluque low severity, moving to 9.0 instead.

**Comment by cmonteroluque** [comment]
agree

**Comment by PVince81** [comment]
Yes, there is no preview for empty text files, just the icon.
