### ISSUE TITLE
occ encryption:encrypt-all fails for old unencrypted files

### ISSUE THREAD

**Issue by maphy-psd** [owncloud/core#20864]
Hi!

After reading the docs I'd realized that isn't possible to encrypt old unencrypted files. When I have files in my owncloud and would enable encryption then the existing files are not encrypted. I think the occ encryption:encrypt-all command should also encrypt this existing unencrypted files.

Greets maphy-psd

**Comment by MorrisJobke** [comment]
cc @schiesbn

**Comment by PVince81** [comment]
@maphy-psd mind telling us which OC version you are using ?

AFAIK 8.2.1 already has such command.
@schiesbn can you confirm ?

**Comment by PVince81** [comment]
Can you also give more information about what you mean with "old unencrypted file" ?

**Comment by maphy-psd** [comment]
I use 8.2.1. The command occ encryption:encrypt-all already exists. But I understand the docs, that this command only encrypt the files that uploaded after the activation.

Old unencrypted file means that files, that are uploaded before the activation of encryption.

As for instance: I use version 8.2.1 for month without encryption. Then I activate encryption and the files that are uploaded are never encrypted with the occ command. For me the command produces this error:

[OCA\Encryption\Exceptions\PrivateKeyMissingException]
  Private Key missing for user: please try to log-out and
   log-in again

In ocdata/username/files_encryption/OC_DEFAULT_MODULE exists the files
username.privateKey, username.publicKey

**Comment by PVince81** [comment]
Ok, then this is an issue, maybe a bug.

**Comment by PVince81** [comment]
@schiesbn

**Comment by MorrisJobke** [comment]
> Private Key missing for user: please try to log-out and
> log-in again

@maphy-psd Sorry for the dumb question: But did you logged out and in through the web UI after enabling encryption? :see_no_evil: Often the old session is reused and the re-login didn't happen yet.

**Comment by maphy-psd** [comment]
I use 8.2.1. The command occ encryption:encrypt-all already exists. But I understand the docs, that this command only encrypt the files that uploaded after the activation.

Old unencrypted file means that files, that are uploaded before the activation of encryption.

As for instance: I use version 8.2.1 for month without encryption. Then I activate encryption and the files that are uploaded are never encrypted with the occ command. For me the command produces this error:

[OCA\Encryption\Exceptions\PrivateKeyMissingException]
  Private Key missing for user: please try to log-out and
   log-in again

In ocdata/username/files_encryption/OC_DEFAULT_MODULE exists the files
username.privateKey, username.publicKey

**Comment by PVince81** [comment]
No, the actual behavior is as follows: when you enable encryption, all files uploaded after that point get encrypted. If you want to also encrypt the files that were uploaded before activation, use the "encrypt-all" command.

In your case if the command fails then that's the problem.

**Comment by MorrisJobke** [comment]
> In your case if the command fails then that's the problem.

Sure, but I just want to make sure in which state this instance is.



> I also remove the key files. After that oc tells me, that the keys aren't initialized and I have to log out and in. When I logged out and in, then the key files are created.

Why did you remove the key files? This then would destroy the access to the files that are encrypted with those keys o.O

**Comment by maphy-psd** [comment]
No files are encrypted, that's the problem. I remove the username.privateKey, and username.publicKey in ocdata/username/files_encryption/OC_DEFAULT_MODULE only for testing with a copy of the data.

**Comment by schiesbn** [comment]
How did you enabled encryption? You need to perform two steps to enable encryption:

- enable the default encryption module app
- enable server side encryption in the admin settings

Only if both are enabled files will be encrypted.

Let's skip the occ tool for now. The first step is to enable encryption correctly and make sure that new uploaded files are encrypted. If this works we can look in the occ tool issue.

**Comment by hlx98007** [comment]
Same goes for me. I enabled Encryption in the latest OC8.2.1 and it is working properly for newly uploaded files.

The encrypt-all command does not encrypt all the files that were dated prior to the enablement of Encryption.

**Comment by PVince81** [comment]
@hlx98007 please also answer the questions: https://github.com/owncloud/core/issues/20864#issuecomment-162482748

Which steps did you use to enable encryption ?

**Comment by hlx98007** [comment]
@PVince81 

1. I enable the plugin in OC, 
2. I tick the box in admin page, enable server-wide encryption
3. I did `sudo -u nginx php occ encryption:migrate`, twice
4. I logout and log back in
5. I did `sudo -u nginx php occ encryption:encrypt-all` --> no old files get encrypted.

**Comment by PVince81** [comment]
Thanks for the details, this looks correct.
Running the commands twice should not cause any bug.

@schiesbn is there something wrong maybe with the detection of files which are not encrypted ? How is that detection done ?

@hlx98007 can you do this: `select * from oc_filecache where path like 'files/%' and encrypted = 0` ?
If all goes well it should show a list of all non-encrypted files. I think that's how the command is supposed to find them.

**Comment by hlx98007** [comment]
@PVince81 I still have `1101 rows in set (0.04 sec)` after doing all previously mentioned steps.

**Comment by PVince81** [comment]
Is this still an issue with 8.2.5 or 9.0.2. If yes, please reopen. Thanks.
