### ISSUE TITLE
Allow webdav interface to preserve file time/date stamp

### ISSUE THREAD

**Issue by tschiu** [owncloud/core#20873]
Hi

I'd like to preserve the as-is date/timestamp of the files when I transfer them over the webdav interface, rather than have owncloud create them with the current date/time.

It would be nice if the web interface also had a checkbox to "preserve time/date stamp".

We're looking to migrate our document file storage system for forms and so forth to owncloud and 

For example, we have a number of forms that haven't changed since 2012 and I'd like them to retain that time/date instead of showing that they were all "created" on December 1, 2015

**Comment by PVince81** [comment]
For Webdav, you can make OC keep the MTIME by setting the actual mtime to the "X-OC-MTIME" header (see an example here https://github.com/owncloud/pyocclient/blob/master/owncloud/owncloud.py#L395)

For web UI uploads, see https://github.com/owncloud/core/issues/19503
