### ISSUE TITLE
/lib/public/util.php on line 166

### ISSUE THREAD

**Issue by Gabrah4378** [owncloud/core#20885]
On a shared web server the following error occurs when after running the setup-owncloud.php
Fatal error: Call to a member function getLogger() on null in /www/htdocs/--xxx--/-xxx--/lib/public/util.php on line 166
The setup was called thtrough https://subdomain.domain.extension

**Comment by PVince81** [comment]
If you need support, see https://owncloud.org/support/.

If you think this is a bug, please reopen and use the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

Thanks.
