### ISSUE TITLE
Reference/Link to a file in a shared folder

### ISSUE THREAD

**Issue by shellstrom** [owncloud/core#20886]
I've been looking for a way to reference single files in a link-shared folder.

What I did was the obvious thing:

1. Locate the folder to share
2. Share folder by link...
3. Open the link in an incognito window
4. Click on a file in the share (in this case an image), which loads in the gallery-app of ownCloud. This generates a URL in the shape of: .../index.php/s/OvXi3yoiaJnlRC7#//HighResScreenShot_2015-10-05_07-24-33.png
5. Open up yet another incognito window
6. Paste the link from the 4th step

What I would like to happen is that the specific file would load in the same way as in the 4th step. What happens instead is that I get taken to the file listing of the shared folder.

My reasoning is that if I could share a file reference within a shared folder, I wouldn't have to do other unnecessary maneuvers such as:

1. Sharing a link to the file specifically with ownClouds tools
2. Copy and paste the file name to the recipient, forcing them to look through the list themselves to find the right file

I can't be the only one wishing this but I didn't have any luck finding stuff on this specific topic during my searches.

**Comment by PVince81** [comment]
See #11732 and join the discussion :smile:
