### ISSUE TITLE
User management page should use the provisioning API instead of private endpoints

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#20887]
Currently the user management page has its own private REST endpoints.

To reduce the number of code paths to cover when testing, it would be nice if that page could directly use the OCS provisioning API endpoints instead.

@LukasReschke @SergioBertolinSG @tomneedham @blizzz @MorrisJobke

**Comment by MorrisJobke** [comment]
Yep. I also thought about this recently ;)

**Comment by MorrisJobke** [comment]
> To reduce the number of code paths to cover when testing, it would be nice if that page could directly use the OCS provisioning API endpoints instead.

We then need to add the provisiong_api app as mandatory.

**Comment by rullzer** [comment]
Thou shalt first look took trough the open issues. https://github.com/owncloud/core/issues/19904

**Comment by PVince81** [comment]
@rullzer I did, but my keywords were "users provisioning API" not "user management" :frowning:
