### ISSUE TITLE
OBS packages out of date

### ISSUE THREAD

**Issue by pludi** [owncloud/core#20897]
ownCloud 8.2.0 was tagged on Oct 21st, 2015.
Current build in the OBS system is 8.1.4, built on Oct 31st, 2015

Any information on when or if the current release will be built for package managing?

**Comment by karlitschek** [comment]
@jnweiger @dragotin

**Comment by dragotin** [comment]
which repo are we talking?

**Comment by jnweiger** [comment]
@pludi opensuse mirrors will stick to 8.1.x
If you want to go 8.2, please visit https://owncloud.org/install/#instructions-server
https://download.owncloud.org/download/repositories/stable/owncloud/

**Comment by RealRancor** [comment]
And also https://doc.owncloud.org/server/8.2/admin_manual/release_notes.html#changes-in-8-2 :-)

**Comment by pludi** [comment]
@jnweiger Any reason why?
