### ISSUE TITLE
Files not updated properly in web browser

### ISSUE THREAD

**Issue by pschoenbach** [owncloud/core#20906]
Browser: Firefox 42.0

To reproduce:
1. Go to Files view
2. Create a folder
3. Change into that folder
4. Upload some files
5. Change into the Files home folder
6. **Information is not refreshed until you press `<Ctrl-Shift-R>` in Firefox**
7. Change back into the folder where the files have been uploaded
8. **Folder is displayed as being empty. Information is not refreshed until you press `<Ctrl-Shift-R>` in Firefox**

**Comment by MorrisJobke** [comment]
@pschoenbach Which version of owncloud do you use?

**Comment by Xenopathic** [comment]
Unable to reproduce with ownCloud 8.2.1 and Firefox 42.0

**Comment by pschoenbach** [comment]
8.2.1. I even tried it with Firefox in safe mode to make sure that it is not an addon problem. Could it be a config issue?

When clicking on e.g. I also see no wait indicator for a refresh.

**Comment by Xenopathic** [comment]
Check your browser logs, see if a new connection is made when opening the folder for the second time. It might be a caching issue, where the browser will only clear the cache on a force refresh (Ctrl+Shit+R rather than just Ctrl+R)

**Comment by pschoenbach** [comment]
Same behavior with MSIE 11.0.25

**Comment by pschoenbach** [comment]
To me, it looks like some server side caching. Could it be a PHP setting or an Apache module that causes this?

**Comment by Xenopathic** [comment]
@pschoenbach Yes, it could be. That's why I asked you to post browser logs, which so far I see none.

**Comment by pschoenbach** [comment]
Now, that is weird. I enabled logging like this:

https://developer.mozilla.org/en-US/docs/Mozilla/Debugging/HTTP_logging

Since then, it basically works. Also after logging out and in again. Any idea why?

The only remaining weirdness: The modify date of the uploaded file says "**in** a few seconds".

**Comment by MorrisJobke** [comment]
> The modify date of the uploaded file says "in a few seconds".

Known problem which looks like you have some clock issue either on your server or your client.

**Comment by pschoenbach** [comment]
They are both NTP synced, though.
