### ISSUE TITLE
Shares not removed on file deletion

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#20908]
I came across this when debugging the smashbox tests for the new share creation code. However it is also happening on master.

#### Steps:

1. user1 shares a file `foo` with user2
2. All is well and user2 has access. There is a nice share entry in the db
3. user1 deletes file `foo`
4. DB entry is still present.

Now of course we would expect to have the share also removed since the file is explicitly deleted. This can lead to a lot of pollution in the sharing table.

I'm not sure if it will lead to problems since the file id no longer exists. But I can't be certain.

@MorrisJobke another one for the health app
@cmonteroluque FYI

CC: @schiesbn @PVince81

**Comment by rullzer** [comment]
It feels like a regression. But no bisect tonight for me... it is on the list for tomorrow.

**Comment by MorrisJobke** [comment]
> @MorrisJobke another one for the health app

Existing behavior (until 8.2):

* share entries for fileids that don't exist are ignored
* there is a background job that cleans this up: https://github.com/owncloud/core/blob/master/apps/files_sharing/lib/deleteorphanedsharesjob.php



> @MorrisJobke another one for the health app

Not really because it is a repairable state and then we should auto repair it.

**Comment by rullzer** [comment]
Ah mmm. starting to remember now.

Do you remember what was the reason we did not install a hook to listen for the delete events?

**Comment by rullzer** [comment]
Because the repair step is fine... but it should not happen any more.

**Comment by PVince81** [comment]
@rullzer the reason for not using hooks: the delete hook only fires for the deleted folder, not its children. We didn't want to have recursive logic to find the file id of all children and delete the matching parents as it would be too expensive and would delay the delete operation for too long for the user/client.

**Comment by rullzer** [comment]
Ai... I get it... but we need some way to solve this if we are going to allow 3rdparty shareproviders.

**Comment by rullzer** [comment]
So this bit me again today..

We really should think how to fix this..

**Comment by rullzer** [comment]
Ok so this can haunt us now that we have lazy shares... let me fix the OCS endpoint to not crash on this...

**Comment by nickvergessen** [comment]
Also think about accidently deletion of a folder...
Currently you can quickly restore it from the trashbin, and all the thousand shares are still there.

**Comment by nickvergessen** [comment]
Closing as per #22434 and after talking to @rullzer who agreed, that this is all we can do atm
