### ISSUE TITLE
Show diff for text files in versions

### ISSUE THREAD

**Issue by pascalBokBok** [owncloud/core#20913]
When you have a .txt file in owncloud with many versions (revisions) it would be a big help if Owncloud on demand could show you a diff between the versions.

I'm using owncloud 8.2.1

**Comment by PVince81** [comment]
Text editor repo is here: https://github.com/owncloud/files_texteditor

**Comment by pascalBokBok** [comment]
Hi @PVince81, I don't think it belongs in the editor repo. That's like assigning image thumbnail generation to the gallery app.
There is already some processing of the versions (text thumbnails), so it could also show a diff - perhaps created on the fly.

**Comment by PVince81** [comment]
My first thought was that the text editor app could use the version app's API (also a separate app) to be able to retrieve the old version and then create a diff there.

Thumbnails are different as they are part of core, not gallery. Thumbnails are still generated even if the gallery app is not enabled.

I'm fine with reopening though. A discussion about the approach needs to take place first.

**Comment by RealRancor** [comment]
@PVince81 Dup of https://github.com/owncloud/core/issues/4056
