### ISSUE TITLE
[stable 8.1] jquery.min.js: An invalid or illegal string was specified

### ISSUE THREAD

**Issue by PoPoutdoor** [owncloud/core#20911]
Function scope [at.setDocument/<]
*<exception>*: SyntaxError

> stack: at.setDocument/<@http://192.168.1.15/core/vendor/jquery/jquery.min.js?v=54c3aae804324a35e8811410d70d86b8:4:13742ut@http://192.168.1.15/core/vendor/jquery/jquery.min.js?v=54c3aae804324a35e8811410d70d86b8:4:10921at.setDocument@http://192.168.1.15/core/vendor/jquery/jquery.min.js?v=54c3aae804324a35e8811410d70d86b8:4:13484@http://192.168.1.15/core/vendor/jquery/jquery.min.js?v=54c3aae804324a35e8811410d70d86b8:4:24907@http://192.168.1.15/core/vendor/jquery/jquery.min.js?v=54c3aae804324a35e8811410d70d86b8:4:7800@http://192.168.1.15/core/vendor/jquery/jquery.min.js?v=54c3aae804324a35e8811410d70d86b8:4:0"

same error with:

Function scope [ut]

**Comment by PVince81** [comment]
Please use the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

Also, which "stable8.1" version/commit are you using ? It is best to use released versions like v8.1.4 instead. (there's a github tag for it)

**Comment by PoPoutdoor** [comment]
Forgot the last commit of site code, will test with stable 8.1 563f0c8 and post update later.

**Comment by PoPoutdoor** [comment]
### Steps to reproduce
1. Enable debug in config.php
2. Restart nginx/php-fpm
3. Clear browser cache
4. Login owncloud with firefox developer tools open
5. Click top-left dropdown menu

### Expected behaviour
No repeated errors about jquery.min.js.

### Client configuration
**Browser:** Firefox 38.4.0
**Operating system:** Linux

**Comment by PoPoutdoor** [comment]
Found this: http://stackoverflow.com/questions/28637589/why-is-jquery-not-working-in-my-mvc-4-application-after-firefox-update

Test with Opera 12.16 does NOT show related jquery error, so most likely Firefox related.

**Comment by PVince81** [comment]
How about your config.php ? Did you enable the asset pipeline ?

**Comment by PoPoutdoor** [comment]
asset pipeline is disabled

**Comment by PoPoutdoor** [comment]
Upgrade Firefox to 42.0, got same error.

**Comment by PoPoutdoor** [comment]
After some test, most likely related to mail app 0.3 alpha.

Closed for now.
