### ISSUE TITLE
Search field symbol shortly shown and is hidden after page displayed

### ISSUE THREAD

**Issue by marneu** [owncloud/core#20912]
Expected:
To see the search symbol in the menu bar (to be expanded).

Behaviour:
The symbol is show for a short moment and disappears when the page is completely shown.
The only page where it is remaining is the files app, all others are loosing the symbol.

Difference in the DOM is:
files:

```
<form class="searchbox" action="#" method="post" role="search">
                <label for="searchbox" class="hidden-visually">
                    Suche               </label>
                <input id="searchbox" class="svg" name="query" value="" autocomplete="off" tabindex="5" type="search">
</form>
```

documents (f.e.):

```
<form class="searchbox" action="#" method="post" role="search">
                <label for="searchbox" class="hidden-visually">
                    Suche               </label>
                <input style="display: none;" id="searchbox" class="svg" name="query" value="" autocomplete="off" tabindex="5" type="search">
</form>
```

Have not found where to switch off the 'display: none' attribute.

Version is Ubuntu 8.2.1-1.1
Activated: files, documents, contacts, calendar, first run, mail template editor, provisioning api, share files, updater, versions

**Comment by karlitschek** [comment]
@jancborchardt What do you think?

**Comment by jancborchardt** [comment]
These apps do not support search, that’s why it’s not shown. You will see it work in the Apps management, User list, and apps like Mail for example.

@DeepDiver1975 @PVince81 Instead of showing the search box and hiding it via CSS, we should do that via PHP directly. Then that flash would be avoided.

**Comment by marneu** [comment]
Hmm, I'd like to turn this into a feature request then, and make i a design goal for future apps.
If you have f.e. hundreds of contacts you relay on the browsers search capabilities but can not search within the data.
(Usage case: I'm coming from a google addressbook with was perfect edited over the years and contains lot of good information besides phone and address).

**Comment by marneu** [comment]
@jancborchardt: Isn't contacts/lib/search/provider.php f.e. the necessary interface for providing a search mechanism within 8.2?

**Comment by jancborchardt** [comment]
@marneu if it’s a feature request for search, then best open it in the individual apps. Contacts for example already has one: https://github.com/owncloud/contacts/issues/961

**Comment by jancborchardt** [comment]
@PVince81 @MorrisJobke can we hide the search field via PHP and not CSS? Right now the flash of content is quite confusing. Same for the Notification icon showing for a split second cc @nickvergessen

**Comment by nickvergessen** [comment]
Notifications will be resolved when we enable it in core for something and we have 2 items on the todo (quota and federated shares)

**Comment by marneu** [comment]
@nickv: Maybe there is a miss understanding. I'm not talking about notifications, I'm referencing the search functionality.
@jancborchardt: I understand for each(!) app.
Isn't there a common interface for the search functionality within the head line?
I still like to refer to my former post, it looks to me as core team does not have it in the design book on how to "coding apps" , am I right? So how should a 3rd party developer know?
I think there should be a line within https://owncloud.org/blog/owncloud-8-for-application-developers/ -> User interface stating and/or reffering howto integrate with the core shell. Yust an idea...

**Comment by jancborchardt** [comment]
@DeepDiver1975 @BernhardPosselt is there a page on the Search API we can link @marneu to?

@marneu the main thing is that even with the core search API in place, the app of course has to interface with it. As I mentioned above:

> You will see it work in the Apps management, User list, and apps like Mail for example.

**Comment by PVince81** [comment]
Please reopen if issue persists in 10.0.4
