### ISSUE TITLE
Add IFTTT Channel/Support

### ISSUE THREAD

**Issue by kphaas** [owncloud/core#20925]
Could we add an channel for IFTTT? It would have similar operations as seagate channel (See Link Below) I really like the owncloud solution but this would set it apart for having your own cloud service. 

http://www.seagate.com/manuals/network-storage/ifttt/using-ifttt/

**Comment by PVince81** [comment]
Probably a candidate for a separate app

**Comment by kphaas** [comment]
Why would this be a separate app? Wouldn't this just be opening owncloud capabilities to IFTTT protocol?

**Comment by PVince81** [comment]
ownCloud is a platform, and apps can provide their own services. IFTTT being one.
Calendar and contacts, news, etc are other services too.

**Comment by joeplus** [comment]
IFTTT does not really support individuals adding apps on their end and they only have just recently added the "[Maker Channel](https://ifttt.com/maker)" but without HTTPS support and I believe you can only make or send a web request. This probably is nothing like the seagate channel described above.

**Comment by PVince81** [comment]
I don't know enough about IFTTT, but I'd expect that an OC app itself would listen to various OC hooks and then publish whatever events were published into IFTTT channels.

The app would also listen to IFTTT channels and then use the OC APIs to perform various actions.

**Comment by PVince81** [comment]
I'm closing this. If anyone is interested, please implement this as an app.

If any hooks or APIs are missing, please raise tickets and mention which ones are needed, thanks.
