### ISSUE TITLE
Logout URL missing trailing slash

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#20922]
@LukasReschke as discussed

### Steps:

1. Setup a new instance on master and have no mod_rewrite installed
1. Login as admin
1. Log out

### Expected result
Back to login page, URL has trailing slash, http://localhost/owncloud/

### Actual result
403 page, URL is http://localhost/owncloud

### Versions
master e62b6c1617886b2cdd7553ea9b119c431e4eb363

**Comment by LukasReschke** [comment]
Fix is at https://github.com/owncloud/core/pull/20924
