### ISSUE TITLE
Sabre namespaces weirdness in response since upgrade to 3.0

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#20930]
In the past, Sabre properly added the OC namespace in the "?xml" tag.

But now it just adds the namespace inline in the response, which might disturb our hacky XML parsing workaround for IE:

![sabre-namespace](https://cloud.githubusercontent.com/assets/277525/11563570/e948e97a-99d4-11e5-9166-05b5ebf4a8d4.png)

Maybe there's a new API that we forgot to call to make it look right ? @DeepDiver1975 @evert

**Comment by DeepDiver1975** [comment]
https://github.com/owncloud/core/blob/master/apps/dav/lib/connector/sabre/filesplugin.php#L100

should be 

```php
		$server->xml->namespaceMap[self::NS_OWNCLOUD] = 'oc';

**Comment by PVince81** [comment]
Ok, I'll change it, thanks.

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/20931
