### ISSUE TITLE
Fedora 23 packages

### ISSUE THREAD

**Issue by pjsanon** [owncloud/core#20932]
Hi,

I would like to request Packages for for Fedora 23 for the version 8.2.1
Also you could have the same repo files for all releases, so that when an upgrade is done, it refers to the new repository transparently.

Thank you.

[ce_stable]
name=ownCloud Server stable Community Edition (Fedora_$releasever)
type=rpm-md
baseurl=http://download.owncloud.org/download/repositories/stable/Fedora_$releasever
gpgcheck=1
gpgkey=http://download.owncloud.org/download/repositories/stable/Fedora_$releasever/repodata/repomd.xml.key
enabled=1

**Comment by MorrisJobke** [comment]
We are currently fully loaded with creating the current packages and I don't think that we will add additional support for more distributions. This task is up to the maintainers of the distribution. Please ask this question in the fedora community.

Feel free to reopen if this is a misunderstanding from my side.

cc @karlitschek @jnweiger

**Comment by pjsanon** [comment]
Will do.
Thanks,
