### ISSUE TITLE
Update 8.1.4 to 8.2.1 fails with Redis Error

### ISSUE THREAD

**Issue by timreeves** [owncloud/core#20945]
Hi,

I did the convenient update via the GUI, but...

Updated "files_texteditor" to 2.0
RedisException: protocol error, got 'k' as reply type byte 

{"reqId":"MPbQzgE1v2ra58zlo0VZ","remoteAddr":"178.26.4.226","app":"core","message":"starting upgrade from 8.1.4.2 to 8.2.1.4","level":0,"time":"2015-12-04T09:36:26+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=TiM6Ln4LGgEECjwVLic5NAEAZSZmFhxbRDwgFDES%3AyDQOKIn4LZiQxPtf90%2Fk5PO%2BpZESsh"}
{"reqId":"MPbQzgE1v2ra58zlo0VZ","remoteAddr":"178.26.4.226","app":"core","message":"Exception: {\"Exception\":\"RedisException\",\"Message\":\"protocol error, got 'k' as reply type byte\\n\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/vhosts\\\/gemeinwohl.info\\\/owncloud.lasslos.net\\\/lib\\\/private\\\/memcache\\\/redis.php(74): Redis->get('651ffab0163d1be...')\\n#1 \\\/var\\\/www\\\/vhosts\\\/gemeinwohl.info\\\/owncloud.lasslos.net\\\/lib\\\/autoloader.php(150): OC\\\\Memcache\\\\Redis->get('OCP\\\\\\\\App')\\n#2 [internal function]: OC\\\\Autoloader->load('OCP\\\\\\\\App')\\n#3 \\\/var\\\/www\\\/vhosts\\\/gemeinwohl.info\\\/owncloud.lasslos.net\\\/apps\\\/files\\\/appinfo\\\/app.php(26): spl_autoload_call('OCP\\\\\\\\App')\\n#4 \\\/var\\\/www\\\/vhosts\\\/gemeinwohl.info\\\/owncloud.lasslos.net\\\/lib\\\/private\\\/app.php(160): require_once('\\\/var\\\/www\\\/vhosts...')\\n#5 \\\/var\\\/www\\\/vhosts\\\/gemeinwohl.info\\\/owncloud.lasslos.net\\\/lib\\\/private\\\/app.php(141): OC_App::requireAppFile('files')\\n#6 \\\/var\\\/www\\\/vhosts\\\/gemeinwohl.info\\\/owncloud.lasslos.net\\\/lib\\\/private\\\/app.php(1171): OC_App::loadApp('files', false)\\n#7 \\\/var\\\/www\\\/vhosts\\\/gemeinwohl.info\\\/owncloud.lasslos.net\\\/lib\\\/private\\\/updater.php(429): OC_App::updateApp('files')\\n#8 \\\/var\\\/www\\\/vhosts\\\/gemeinwohl.info\\\/owncloud.lasslos.net\\\/lib\\\/private\\\/updater.php(320): OC\\\\Updater->doAppUpgrade()\\n#9 \\\/var\\\/www\\\/vhosts\\\/gemeinwohl.info\\\/owncloud.lasslos.net\\\/lib\\\/private\\\/updater.php(205): OC\\\\Updater->doUpgrade('8.2.1.4', '8.1.4.2')\\n#10 \\\/var\\\/www\\\/vhosts\\\/gemeinwohl.info\\\/owncloud.lasslos.net\\\/core\\\/ajax\\\/update.php(111): OC\\\\Updater->upgrade()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/vhosts\\\/gemeinwohl.info\\\/owncloud.lasslos.net\\\/lib\\\/private\\\/memcache\\\/redis.php\",\"Line\":74}","level":3,"time":"2015-12-04T09:36:51+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=TiM6Ln4LGgEECjwVLic5NAEAZSZmFhxbRDwgFDES%3AyDQOKIn4LZiQxPtf90%2Fk5PO%2BpZESsh"}

Tipp: Redis server version 2.2.12 (Ubuntu 12.04 LTS). So that old version of Redis may need to be detected and e.g. use the old KEYS command instead of SCAN.

CLI-Upgrade via "php occ upgrade" worked.

Cheers,
Tim

**Comment by RealRancor** [comment]
@timreeves You already reported the same some days ago: https://github.com/owncloud/core/issues/20509 That issue is still open so i think you can close here.

**Comment by timreeves** [comment]
OK, thanks - so much software, so many issues - sometimes I lose the overview )-:
