### ISSUE TITLE
Redis Server Went Away when switch to Unix Socket

### ISSUE THREAD

**Issue by timreeves** [owncloud/core#20950]
Using Ubuntu 12.04 with Redis-Server 2.2.12:

This older version of Redis supports in it's config the "unixsocket" directive, but not the "unixsocketperm" directive - the Socket is created like this:
srwxrwx--- 1 redis redis 0 Dec  4 11:19 /var/run/redis/redis.sock

So I added the OC-User to the "redis" group: usermod -aG redis {OC-User}
And tried it out: sudo -u {OC-User} redis-cli -s /var/run/redis/redis.sock
That works, connecting is no problem.

Problem is, OC won't play ball when I configure it to use the socket as noted here:
https://doc.owncloud.org/server/8.2/admin_manual/configuration_files/files_locking_transactional.html
Then OC logs this:
{"reqId":"EotEAvrMqCC2aLEfu2SF","remoteAddr":"178.26.4.226","app":"webdav","message":"Exception: {\"Message\":\"Redis server went away\",\"Exception\":\"RedisException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/vhosts\\\/gemeinwohl.info\\\/owncloud.lasslos.net\\\/lib\\\/private\\\/memcache\\\/redis.php(136): Redis->incrBy('453c575d90eea83...', 1)\\n#1 \\\/var\\\/www\\\/vhosts\\\/gemeinwohl.info\\\/owncloud.lasslos.net\\\/lib\\\/private\\\/lock\\\/memcachelockingprovider.php(63): OC\\\\Memcache\\\\Redis->inc('files\\\/a0e822710...')\\n#2 ....

So I had to fall back to TCP, that works fine (so it's not a problem with the old Redis per se).

Cheers,
Tim

**Comment by RealRancor** [comment]
Hi,

please fill out the issue template here: 

https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version

which is linked in the yellow box when creating a new issue.

**Comment by timreeves** [comment]
### Server configuration
**Operating system**: Ubuntu 12.04.5 LTS‬

**Web server:**  nginx/1.9.4

**Database:**  mysql  Ver 14.14 Distrib 5.5.46

**PHP version:**  5.6.14 with redis 2.2.7

**ownCloud version:** (see ownCloud admin page)  8.2.1.4

**Updated from an older ownCloud or fresh install:**  Update from 8.1.4

**List of activated apps:**
Enabled:
  - activity: 2.1.3
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - documents: 0.11.0
  - files: 1.2.0
  - files_external: 0.3.0
  - files_mv: 0.8.1a
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - mail: 0.2.1
  - updater: 0.6
Disabled:
  - encryption
  - external
  - files_locking
  - files_videoviewer
  - firstrunwizard
  - gallery
  - notifications
  - provisioning_api
  - templateeditor
  - user_external
  - user_ldap
  - user_webdavauth

config.php:

$CONFIG = array (
'instanceid' => '...',
'passwordsalt' => '...',
'trusted_domains' =>
array (
  0 => 'owncloud.lasslos.net',
),
'datadirectory' => '/var/www/vhosts/...',
'dbtype' => 'mysql',
'version' => '8.2.1.4',
'dbname' => '...',
'dbhost' => 'localhost',
'dbtableprefix' => 'oc_',
'dbuser' => '...',
'dbpassword' => '...',
'installed' => true,
'loglevel' => '2',
'forcessl' => true,
'theme' => '',
'maintenance' => false,
'mail_from_address' => '...',
'mail_smtpmode' => 'php',
'mail_domain' => 'timreeves.de',
'default_language' => 'en',
'mail_smtpname' => '...',
'mail_smtppassword' => '...',
'secret' => '...',
'preview_libreoffice_path' => '/usr/bin/libreoffice',
'log_rotate_size' => 10485760,
'check_for_working_htaccess' => false,
'memcache.local' => '\\OC\\Memcache\\Redis',
'filelocking.enabled' => 'true',
'memcache.locking' => '\OC\Memcache\Redis',
// THIS I HAD TO COMMENT OUT
// 'redis' => array(
//   'host' => '/var/run/redis/redis.sock',
//   'port' => 0,
//   'timeout' => 0.0,
//   'dbindex' => 1,
// ),
'redis' => array (
  'host' => 'localhost',
  'port' => 6379,
  'timeout' => 0,
  'dbindex' => 1,
),
'trashbin_retention_obligation' => 'auto',
);

Sorry, the OC-Log got cleaned )-:

**Comment by RealRancor** [comment]
This one here works for me:

```
  'redis' => 
  array (
    'host' => '/var/run/redis/redis.sock',
    'port' => 0,
    'timeout' => 0,
  ),
```

with oC 8.2.1 (and also 8.1.4 previously). You probably just needs to put your webservers user into the redis group so that user is able to access the socket.

**Comment by timreeves** [comment]
Hm but I already did, see above: usermod -aG redis {OC-User}

BTW that's an own compiled version of PHP 5.6.14 running as PHP-FPM getting its requests directly from Nginx (no Apache between).

I had been wondering if OC was testing for world rw on the socket instead of testing if it could actually do the job, but if you have had success with the group access method then that's probably not the problem.

I see 2 differences in the config for the socket variant:
1. 'timeout' => 0.0  /  'timeout' => 0,
2. 'dbindex' => 1,

**Comment by RealRancor** [comment]
@timreeves Then check stuff like open_basedir and similar which could prevent PHP to connect to that socket where the command line is allowing it. Also make sure you have chosen the correct "OC-User" as nginx could run as a different user than php-fpm.

Overall i don't think that this is an issue within oC but more an issue somewhere within the environment.

**Comment by timreeves** [comment]
@RealRancor you were right - I normally think of open_basedir, e.g. for /dev/urandom, but in this case I overlooked it. One must add "/var/run/redis". Sorry about that and many thanks to you!

It might be good to add a reminder to the page on [Transactional file locking](https://doc.owncloud.org/server/8.2/admin_manual/configuration_files/files_locking_transactional.html), and/or in config.sample.php.

Case closed!

Cheers, Tim

**Comment by RealRancor** [comment]
> It might be good to add a reminder to the page on Transactional file locking, and/or in config.sample.php.

From my PoV the docs of oC already contains way too much non-oC related documentation. But feel free to post that at https://github.com/owncloud/documentation/issues and let us see what others are thinking about this :-)
