### ISSUE TITLE
LDAP uuid

### ISSUE THREAD

**Issue by andersklenke** [owncloud/core#20958]
Hi,

I'm using this great product with a LDAP connection to Active Directory. I have a question regarding the creation of the uuid. 

When I create a user in Active Directory, a UUID is automatically assigned to the user. 
If I delete the user in AD, the user is removed from mysql and the personal folder is kept (this is what I want). 
If I create a new user with same name and the same email, the user is assigned to the same UUID and has access to the same files as the first user.
Is this a bug? 

Thanks!

**Comment by karlitschek** [comment]
thanks for the question. please check owncloud.org/support for options to get answers
