### ISSUE TITLE
Admin account creation failed without any error/info messages

### ISSUE THREAD

**Issue by rishibaldawa** [owncloud/core#20969]
I tried a long password while setting up my server's first admin account

     74:FuxPo7gmftmz9jR3un/ep.7ee7&sWfjMuJVA{c"%%8Nfs4@AK3LjuQDE^hDJP

I just kept on getting redirected without any error messages

This was for version 8.2.1 w php5 + mySql

**Comment by karlitschek** [comment]
@LukasReschke

**Comment by karlitschek** [comment]
@rishibaldawa Does it work with a shorter password?

**Comment by LukasReschke** [comment]
Please fill out the issue template as described at https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version

**Comment by rishibaldawa** [comment]
@karlitschek shorter password works. Tried a 25 character and found no issues. 

@LukasReschke sorry about that. will try to fill it up in the next couple of days.

**Comment by rishibaldawa** [comment]
### Steps to reproduce
1. Install owncloud
2. Login for the first time
3. Pick a really long password (like the one I've pasted above)
4. Set the usual values for the rest things like login and database etc

### Expected behaviour
Account should get created.

### Actual behaviour
The page just refreshes back to the same page. No error message was shown. Works when I retried a randomly generated shorter password

### Server configuration
**Operating system**: raspbian wheezy 

**Web server:** nignx

**Database:** mysql

**PHP version:** 5

**ownCloud version:** 8

**Updated from an older ownCloud or fresh install:** fresh install

**List of activated apps:** None. Was the first thing I tried to install.

**The content of config/config.php:** Sorry, I've deleted the instance last night. Didn't realize it would be required.

**Are you using external storage, if yes which one:** self-mounted on raspberry pi @ /media/usbstorage

**Are you using encryption:**  yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 42

**Operating system:** Windows 10

### Logs 

Sorry wiped the OS before I storing the logs elsewhere due to a different issue.

**Comment by PVince81** [comment]
> ownCloud version: 8

We need the full version number.

**Comment by rishibaldawa** [comment]
I'm sorry but I don't have the instance running anymore.
