### ISSUE TITLE
Text file does not open in editor when using Favourites

### ISSUE THREAD

**Issue by johndevs** [owncloud/core#20964]
I have marked a text file as a favourite. 

When I click the file under "All Files" the file opens in the text editor but when I open the file under Favourites the file is downloaded. I would expect the behaviour to be same under Favourites as it is under Files.

**Comment by karlitschek** [comment]
Could you open this issue in the text_editor repo please? https://github.com/owncloud/files_texteditor

**Comment by johndevs** [comment]
Sure.

https://github.com/owncloud/files_texteditor/issues/152
