### ISSUE TITLE
[feature request] Extend the User Provisioning API to handle avatar

### ISSUE THREAD

**Issue by cedriccarbone** [owncloud/core#20973]
Right now, User Provisioning API [1] doesn't allow to set or get the **avatar** of a user. It should be great  if the API can handle avatar to be able to manage Users externally.
Thanks!
-cedric

[1] https://doc.owncloud.org/server/8.0/admin_manual/configuration_user/user_provisioning_api.html#users-edituser

**Comment by tomneedham** [comment]
@PVince81 @MTRichards

**Comment by DeepDiver1975** [comment]
There was the plan to have a DAV resource to handle avatars.

**Comment by rullzer** [comment]
Even more we kind of need to use a different endpoint since OCS does not allow us to return binary data. But maybe we could (once the DAV endpoint is in place) put the link into the provisioning API responses.

**Comment by tomneedham** [comment]
> But maybe we could (once the DAV endpoint is in place) put the link into the provisioning API responses.

I like this idea :)

**Comment by SergioBertolinSG** [comment]
@PVince81 @DeepDiver1975 I think a personal API / DAV endpoint for all personal changeable options is required. Clients needs this to give more options to the users. For example I've seen recently that android app is getting the avatars from the url directly  /index.php/avatar/admin/256#256 .

**Comment by DeepDiver1975** [comment]
Absolutely

**Comment by DeepDiver1975** [comment]
we can use the system addressbook like this:
http://localhost:8080/remote.php/dav/addressbooks/system/system/system/Database:admin.vcf?photo

this will return the users avatar - but only in 96x96 pixels. not perfect

**Comment by PVince81** [comment]
@DeepDiver1975 backlog, or do you have time for this ?

**Comment by SamuAlfageme** [comment]
Linking https://github.com/owncloud/core/pull/26872 - regarding the avatar DAV resource. Original request was to use the provisioning API to operate on the avatar, not sure if this will suffice or there's additional actions required.
