### ISSUE TITLE
webgui update owncloud 8.21

### ISSUE THREAD

**Issue by ronny987** [owncloud/core#20974]
Hi 

during the update i receive the error message:

Aktualisiere ownCloud auf Version 8.2.1. Dies könnte eine Weile dauern.
Update vorbereiten
Log-Level auf Debug gesetzt - aktuelles Level: "Warning"
Wartungsmodus eingeschaltet
Exception: Updates between multiple major versions and downgrades are unsupported.
The update was unsuccessful. Please report this issue to the ownCloud community.

How can i fix that error? Now after reloading owncloud, the update dialog appears. The error appears every time. 

At the moment the version 8.0.4 is installed.

how can i fix the update problem?

best regards
ronny

**Comment by LukasReschke** [comment]
Update to 8.1.x first. https://owncloud.org/changelog/

**Comment by RealRancor** [comment]
Also suggesting doing the following upgrade path:

8.0.4 -> 8.0.9 -> 8.1.4 -> 8.2.1

as discussed at various places.

**Comment by ronny987** [comment]
hm.. why does the autoupdater installs the wrong version? It would be great if the autoupdater would installs the correct version (updatepath), instead to download the newest version. 

how should i cancle the upgrade procedure to 8.21?

**Comment by RealRancor** [comment]
@ronny987 The updater is not responsible for this. There is a long outstanding issue which needs to be fixed on the update server: https://github.com/owncloud/appstore-issues/issues/4

**Comment by ronny987** [comment]
Thank you RealRancor, 

but how to abort the actual upgrade to 8.21?

**Comment by RealRancor** [comment]
1. Remove all files and folders expect /data/ and /config/
2. Download 8.0.9 from the changelog posted above and extract it into your install dir
3. Run the update via the webgui

Repeat those steps with 8.1.4 and 8.2.1

**Comment by ronny987** [comment]
@RealRancor a big thank you... the update worked.. 
thx for that great support!
