### ISSUE TITLE
Updater should be able to execute external (own) sript

### ISSUE THREAD

**Issue by hitam4450** [owncloud/core#20970]
Hello Developer community of OwnCloud,

How about the idea, to provide a possibility that the Updater provides a possibility to execute an external (own) script at a given point of the update process??

I am looking forward to discussing with you!

Have a Nice, relaxing Sunday!

regards, hitam4450

**Comment by RealRancor** [comment]
@hitam4450 The issue tracker of the updater is located here: https://github.com/owncloud/updater/issues

**Comment by RealRancor** [comment]
@hitam4450 As you have already re-open in https://github.com/owncloud/updater/issues/202 you can close this here on your own by hitting the "Close" button below the comment field.
