### ISSUE TITLE
Rename hooks not fired when moving a file to a directory on new webdav endpoint

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#20982]
When looking into https://github.com/owncloud/core/issues/20769 I uses the new dav endpoint to test. But no hooks were fired.

Steps:
1. user has a file 'foo.txt'
2. user has a folder 'bar'
3. user moves 'foo.txt' into 'bar.txt'

Now I would expect the rename hooks to be fired see https://github.com/owncloud/core/blob/master/lib/private/files/node/file.php#L140

But they are not. This all works on the old endpoint.

I think we are missing a plugin since we let sabre handle the move. And since it is a different directory sabre falls back to default webdav behaviour. Which means copy the file over to the new location and delete the old one.

@DeepDiver1975

**Comment by PVince81** [comment]
I'm not sure the change is due to the move of the webdav code. There might be other changes in the filesystem code that could influence this behavior.

The Webdav code in the end only uses the `View` class to do operations, and that `View` class is the one triggering the hooks. So maybe there were changes there ? @icewind1991

**Comment by rullzer** [comment]
I looked some more into this and it is defenitly an issue with the new webdav endpoint.
We no longer extend the objectree. Thus the move is not handled by our code.

**Comment by rullzer** [comment]
Yes it happens here:

https://github.com/owncloud/core/blob/master/apps/dav/lib/server.php#L51

There we pass the RootCollection. Which is an INode... 

Then https://github.com/fruux/sabre-dav/blob/master/lib/DAV/Server.php#L200 creates a 'regular' tree sabre tree... https://github.com/fruux/sabre-dav/blob/master/lib/DAV/Tree.php

And thus on move we call: 

https://github.com/fruux/sabre-dav/blob/master/lib/DAV/Tree.php#L143

This thus happens outside of our scope... which means we do not do an internal move. Thus no hooks are fired etc...

**Comment by DeepDiver1975** [comment]
> Then https://github.com/fruux/sabre-dav/blob/master/lib/DAV/Server.php#L200 creates a 'regular' tree sabre tree... https://github.com/fruux/sabre-dav/blob/master/lib/DAV/Tree.php

this was done on intention - we basically need to operate on the regular tree implementation.

**Comment by rullzer** [comment]
Aaah mm well then we need to fix other stuff. since the rename hooks should be fired.

**Comment by PVince81** [comment]
> I looked some more into this and it is defenitly an issue with the new webdav endpoint.
> We no longer extend the objectree. Thus the move is not handled by our code.

Hmmm, but in that case I'd expect versions to be lost. I just tested locally on master and a Webdav MOVE on the new endpoint did preserve versions.

**Comment by PVince81** [comment]
I'll still set this to high as it might break other stuff we haven't discovered yet, stuff depending on these hooks.

**Comment by PVince81** [comment]
Likely related to https://github.com/owncloud/core/issues/26992 where a MOVE on the new DAV endpoint is actually a copy+delete. More info here https://github.com/owncloud/core/pull/27508#issuecomment-289516817

**Comment by PVince81** [comment]
Checked with a debugger in files_versions and the post_rename hook is called.
Likely fixed by the above.
