### ISSUE TITLE
System tag filter section in files navigation

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#21001]
Quoting @MTRichards:

> On the left files app view, a new filter appears when tags are created that allows users to select a tag dropdown, and then select one or more tags for filtering. The appropriate files then appear in the files view.

Related to https://github.com/owncloud/core/issues/16325

@jancborchardt can you help design the GUI for this ?
I'd rather suggest to have the filter input in the controls bar instead of the navigation bar itself.

### Frontend / JS
- [x] clear out UI design
- [x] implement UI

### Backend
- [x] DAV endpoint for getting all files tagged with one or multiple system tags:
    - get all files tagged with $tagId: PROPFIND "dav/systemtags-relations/tagged/files/$tagId/" and receive a list of tagged files.
    - BEWARE, the file name in the result needs to be unique, so it won't be the real file name but a generated name. File name will be available in "oc:name" property.
    - make sure it works for multiple tags, maybe use the format `${tagId1}+${tagId2}+${tagId3}` as the collection name
    - alternative: use REPORT method
- [ ] filesystem level search API: `searchBySystemTag` or do the query directly in the system tags manager

**Comment by jancborchardt** [comment]
> I'd rather suggest to have the filter input in the controls bar instead of the navigation bar itself.

@PVince81 what do you mean by that? Actually I’d want to have as little as possible in the controls bar since we’ll for sure get problems on mobile.

It should simply be an entry »Tags« in the left navigation. Then either we use:

- a select2-like element (with the improvements talked about @PVince81)
- a subfolder mechanism like in the News app where tags are sub-entries (this might not scale for lots of tags though as it misses search)

**Comment by PVince81** [comment]
The part that disturbs me is having the select box crammed in into the navigation entry. Also it might wrap if you select multiple tags. Do we want that ?

Does the news app also have dropdowns embedded inside the nav bar ?

**Comment by jancborchardt** [comment]
@PVince81 it will work well for 3 tags or so – and how much more deeply would you want to go with the filter? It shouldn’t wrap, as we talked about in the other issue. Should behave like our multiselect.js

The News app has subfolders, which are expandable navigation entries. Best just install it and check it out to get a feel for it. The Mail app does the same.

Another option is to integrate this into the search function, however it isn’t that discoverable.

**Comment by PVince81** [comment]
Okay, sounds like the time has come to investigate customizing select2 to make it work like multiselect.
This also means that in the nav sidebar the tags selector will look differently than in the files sidebar where it is used for tagging. But I guess that's fine and the fact that they are visually different imply a different function (filter vs tagging)

**Comment by PVince81** [comment]
By the way, it would still be good to have a mock up for this, for the record. Or do you have screenshots that could be posted ?
While I might invest some time at some point later in setting up the apps you mentioned to see how it looks like, not everybody reading this ticket will.
And having mock ups can also help the people to visualize while having the discussion.
I know what we're talking about regarding the select2 modifications but other people might not.

**Comment by PVince81** [comment]
Another alternative as discussed with @karlitschek this week is to have tag presets. So the subfolders in question are actually preset names, not tag names. The user can click a "+" button (need to decide where it goes) and enter a preset name. Then in the controls bar of the files app (where the path is usually shown) there's a select2 dropdown to select one or multiple tags.

**Comment by PVince81** [comment]
Here we go, more visuals don't hurt.

Simple version with select2 in controls bar:
![filter-tag-simple](https://cloud.githubusercontent.com/assets/277525/12679780/553e1a26-c6a6-11e5-9d54-9adf50032924.jpg)

Extended version with presents:
![filter-tag-presets](https://cloud.githubusercontent.com/assets/277525/12679806/70f216c8-c6a6-11e5-8502-15c77c8b0a8e.jpg)

**Comment by PVince81** [comment]
and here a screenshot of the news app to see how the indented elements look like:
![news-folders](https://cloud.githubusercontent.com/assets/277525/12679953/7f993b92-c6a7-11e5-8888-ec288a953cd0.png)

**Comment by PVince81** [comment]
Depending on how much dev time is left I might go with either the simple or extended version from my mock up. Being able to filter in the first place is already quite an enhancement.

**Comment by MTRichards** [comment]
This function is a big move forward for tags! If it looks like it will make 9.0, then I will roll it into my writeup - thanks @PVince81 !

**Comment by MTRichards** [comment]
@jospoortvliet For you to know, because this should be added to our 9 conversations.

**Comment by karlitschek** [comment]
@PVince81 agreed. As discussed! Very cool!

**Comment by PVince81** [comment]
I'm still busy with other stuff (comments, etc), my gut feeling tells me that I won't have time to do this fully before the freeze. There is some tricky backend work to be done for the filtering first before the UI can use it.

So for now, consider this unlikely to make it for 9.0.

**Comment by PVince81** [comment]
- Backend PR: https://github.com/owncloud/core/pull/22112
- Frontend PR: https://github.com/owncloud/core/pull/22197

**Comment by jancborchardt** [comment]
Sorry about the vacation timing last week, will look into this today and tomorrow!

**Comment by PVince81** [comment]
This is implemented already, closing.

Here is a follow up ticket for tweaking the design/icons if needed: https://github.com/owncloud/core/issues/22240

**Comment by PVince81** [comment]
- doc https://github.com/owncloud/documentation/issues/2151
- QA: https://github.com/owncloud/QA/issues/129

**Comment by PVince81** [comment]
@MTRichards FYI we did manage to implement it in time

**Comment by MTRichards** [comment]
:sun_with_face: AWESOME. Thanks for the extra effort here.
