### ISSUE TITLE
Separate permission for user share and link share in external storage mount options

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#21000]
See original ticket https://github.com/owncloud/core/issues/19157

So far there is an option "Enable sharing" that combines both user share and link shares by using the existing share permission from the storages.

This needs to be extended to support separating user shares and link shares.

@MTRichards @icewind1991

**Comment by PVince81** [comment]
This could be done by introducing a new storage level permission for link shares, and reusing the existing one for only user shares.
Please note that this addition will require adjusting all the clients (web, desktop, mobile) to be able to distinguish these two permissions.

**Comment by PVince81** [comment]
Now thinking of it, we might also want to have "federated share" option separately

**Comment by MTRichards** [comment]
yeah, really good point.

**Comment by rullzer** [comment]
@PVince81 thinking about this in relation to https://github.com/owncloud/core/pull/22834

Maybe a similar property would make sense. To list the possible share types.

**Comment by PVince81** [comment]
@rullzer good point.

**Comment by MTRichards** [comment]
Moved milestone to 9.2 as this is largely a bigger issue than it seems.

@PVince81 Is this issue for a global issue, or is this intended to be external storage? Just trying to understand the scope of what is here. Yes, I know, I wrote the original issue. :smile:

**Comment by PVince81** [comment]
It is more global in a way that affect the filesystem code, we basically need to add new permissions to be able to separate/distinguish the two sharing cases.

**Comment by PVince81** [comment]
No time for this => backlog for now
