### ISSUE TITLE
Delete share hotspot not wide enough

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#21013]
### Steps

1. Share something with another user
1. Open the share dialog in the sidebar
1. Move the mouse to the trash icon but don't click, it will turn into a hand cursor
1. Now continue moving the cursor to the right until the hand cursor changes back into an arrow
1. Now go back a few pixels to the left to go back to hand cursor mode. The goal is to click on the rightmost part of the trashicon where the cursor is still a hand
1. Click!

### Expected result
Share deleted, action triggerred

### Actual result
Full page reload ! Very annoying !

I suspect that the link's hotspot doesn't match the image size.
Or the click event is listening on the image instead of the link.

### Versions
ownCloud 8.2.1 and master

**Comment by blizzz** [comment]
> Move the mouse to the trash icon but don't click, it will turn into a hand cursor
Now continue moving the cursor to the right until the hand cursor changes back into an arrow
Now go back a few pixels to the left to go back to hand cursor mode. The goal is to click on the rightmost part of the trashicon where the cursor is still a hand

Whoa, how wicked! I only managed to reproduce it once out of several attempts. During the others, nothing happened, which is also odd while having the pointer icon.
