### ISSUE TITLE
Changed/Replaced image does not update corresponding gallery thumbnail/image

### ISSUE THREAD

**Issue by arjanvs** [owncloud/core#21017]
Hi all

I have something similar as https://github.com/owncloud/core/issues/10822

I would formulate the issue as follows:
* Changed/Replaced image does not update corresponding gallery thumbnail/image

Issue is on OwnCloud 8.2.1:

Steps to reproduce:
1. Go to files, create a new folder and upload photos into that folder
2. Go to images, and browse to folder and see the thumbnails
3. Go back to files, upload different photos but with same names, and choose to replace existing files with new ones when the dialog appears. Or change the image.
4. Clear browser cache to make sure browser cache is not issue here (or open a new browser)
5. Go back to images into the folder: Thumbs of images are (incorrectly) not updated. But clicking the thumbs shows the new (different) image correctly.[/list]

What I would expect? Is the following:
* After change/replace of the image and gallery app is used
* The gallery app checks date and time of original image with date and time of thumbnail and preview image. If thumbnail data/time is older than original image, then create new thumbnail and preview image.

According to the previous issue, it was fixed. But my personnel observation, would say it is open again.

The code improvement of the previous issue I cannot find it in the current app code.

BTW. I use the latest client 2.1.0

Thank you!

Kind regards

Arjan

**Comment by PVince81** [comment]
@georgehrke @oparoz 

Wasn't this fixed already recently ? Or is there a duplicate open ticket ?

**Comment by arjanvs** [comment]
According to the previous issue, it was fixed. But my personnel observation, would say it is open again.

The code improvement of the previous issue I cannot find it in the current app code.

BTW. I use the latest client 2.1.0

**Comment by oparoz** [comment]
I think this is a known problem with the Preview class which doesn't have the necessary hooks to update the previews on upload.

**Comment by georgehrke** [comment]
> to update the previews on upload.

Well, the preview class is not supposed to generate previews after files changed. It's supposed to delete the old ones and generate new ones on demand. Or am I misreading your comment?

**Comment by oparoz** [comment]
That's correct. I can't find the issue where preview hooks were discussed. The problem is that it's not happening. the previews don't get deleted.

**Comment by arjanvs** [comment]
Was it this issue: https://github.com/owncloud/core/issues/14572?

**Comment by oparoz** [comment]
Might be #14572, yes, but that one is about shares and in this case, nothing is shared.
If hooks are present to detect when a file is updated, then there is a bug or a component is not calling them when it should.

**Comment by arjanvs** [comment]
I don't want to nag, but I disagree with the label. Shouldn't it say bug? Because it doesn't work as intended.

**Comment by oparoz** [comment]
There ;)

**Comment by arjanvs** [comment]
Thx :D

**Comment by oparoz** [comment]
I just re-read the steps. In step 3, do you get an updated thumbnail in the Files app? When I tested I didn't, but I just want to make sure and test on older version to see if it's a regression.

**Comment by arjanvs** [comment]
@oparoz - Yes, I forgot to mention that. For me the icon thingy in the file app was not so annoying.

**Comment by PVince81** [comment]
Please try again with 8.2.5, 9.0.2 or 9.1.0 beta2.

If the problem still exists, please reopen.

**Comment by phpweb** [comment]
Version 10.0.9 has the same problem. The same image (overriding existing one) has different thumbnails for users. For a user it has the old thumbnail and for another user it has the new replaced image thumbnail. 

If I go to the **thumbnail** directory of the user who still has the old image thumbnail and if I delete `rm -rf thumbnails/*` then the user will have the new updated image thumbnail. Is there no a way to automate this somehow?

**Comment by phil-davis** [comment]
@phpweb please read issue #31855 - I think this is the currently-open issue for the thumbnail-sync problem you describe.
Then post there if you have information to add.
