### ISSUE TITLE
Update npm ???

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#21026]
````
02:29:46 + ./autotest-js.sh
02:29:46 npm WARN deprecated This version of npm lacks support for important features,
02:29:46 npm WARN deprecated such as scoped packages, offered by the primary npm
02:29:46 npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
02:29:46 npm WARN deprecated latest stable version. To upgrade to npm@2, run:
02:29:46 npm WARN deprecated 
02:29:46 npm WARN deprecated   npm -g install npm@latest-2
02:29:46 npm WARN deprecated 
02:29:46 npm WARN deprecated To upgrade to the latest stable version, run:
02:29:46 npm WARN deprecated 
02:29:46 npm WARN deprecated   npm -g install npm@latest
02:29:46 npm WARN deprecated 
02:29:46 npm WARN deprecated (Depending on how Node.js was installed on your system, you
02:29:46 npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
02:29:46 npm WARN deprecated on Windows, run them from an Administrator prompt.)
02:29:46 npm WARN deprecated 
02:29:46 npm WARN deprecated If you're running the version of npm bundled with
02:29:46 npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
02:29:46 npm WARN deprecated will be bundled with a version of npm@2, which has some small
02:29:46 npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
02:29:46 npm WARN deprecated semver behavior.

**Comment by DeepDiver1975** [comment]
seen on https://ci.owncloud.org/job/core-ci-linux-jsunit/database=sqlite,label=SLAVE/52993/console

**Comment by DeepDiver1975** [comment]
@PVince81

**Comment by PVince81** [comment]
Let me first test this locally...

**Comment by PVince81** [comment]
I can't reproduce this message locally with:
- node v0.10.32
- npm 1.4.28

Could not check on Jenkins, seems the link above is broken (white page that loads forever)

**Comment by PVince81** [comment]
I see there is a new node JS version, actually two, one LTS and one stable on the official website: https://nodejs.org/en/

I will try with the tests run properly with the LTS version locally and we can probably upgrade Jenkins to that one too. I don't see the old 0.10 version there any more.

**Comment by PVince81** [comment]
I updated my local node JS to this version:
- node v4.2.3
- npm 2.14.7 (bundled by node)

Then I cleared "build/node_modules" and ran `autotest-js.sh`. It worked properly.

Do you want to attempt an upgrade of node JS ? (it will update npm as well)

**Comment by DeepDiver1975** [comment]
> Do you want to attempt an upgrade of node JS ? (it will update npm as well)

Once Jenkins is back in proper shape - I can try to kill it again ;-)

**Comment by PVince81** [comment]
@DeepDiver1975 did you actually do the update ? Moving to 9.1 for now.

**Comment by DeepDiver1975** [comment]
> Moving to 9.1 for now.

agreed

**Comment by DeepDiver1975** [comment]
npm was updated during the operation in the past weeks on ci -> close
