### ISSUE TITLE
S2S is not able to handle errors properly. Resulting in broken WebDAV + undeletable files

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#21033]
Federated Cloud Sharing is not able to properly handle error cases, if the remote server does not return an expected output there is a lot of stuff that goes wrong.

One example:

1. From ownCloud 8.0 server share to ownCloud 8.2 server
2. From ownCloud 8.2 server accept the share
3. From ownCloud 8.0 server delete the file

Now when accessing the public link WebDAV URL this will throw a fatal error on the 8.0 server. In newer releases we don't throw the fatal error anymore. This bug however means that an error on a remote ownCloud S2S server can totally make your own ownCloud server go wrong:

> {"reqId":"LjCCj8473fantn8XAZH5","remoteAddr":"31.10.132.38","app":"PHP","message":"Call to a member function getType() on a non-object at \/var\/www\/html\/owncloud\/apps\/files_sharing\/publicwebdav.php#79","level":3,"time":"2015-12-04T11:36:28+01:00","method":"GET","url":"\/public.php\/webdav"}

Syncing with the 8.2 server using the ownCloud client will now be not possible anymore as the XML response contains an error. Also deleting the file is not really possible. Nightmare as it requires fiddling in the database to fix it. The WebDAV response is:

> ➜  ~  curl https://s3.owncloud.com/owncloud/remote.php/webdav/ -X PROPFIND -u lukas | xmllint --format -

```xml
  <d:response>
    <d:href>/owncloud/remote.php/webdav/ownCloudUserManual.pdf</d:href>
    <d:propstat>
      <d:prop>
        <d:getlastmodified>Wed, 15 Jul 2015 23:26:28 GMT</d:getlastmodified>
        <d:getcontentlength>2215875</d:getcontentlength>
        <d:resourcetype/>
        <d:getetag>"7aad56ba3eedec2c78100df1dec23066"</d:getetag>
        <d:getcontenttype>application/pdf</d:getcontenttype>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
```

Accessing the folder using a PROPFIND that our client issues will however explode hard:
```http 
PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1
Depth: 1
User-Agent: Mozilla/5.0 (Macintosh) mirall/2.1.0
Content-Type: text/xml; charset=utf-8
Content-Length: 291
Connection: Keep-Alive
Accept-Encoding: gzip, deflate
Accept-Language: en-US,*
Host: s3.owncloud.com

<?xml version="1.0" ?>
<d:propfind xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">
  <d:prop>
    <d:resourcetype />
    <d:getlastmodified />
    <d:getcontentlength />
    <d:getetag />
    <oc:id />
    <oc:downloadURL />
    <oc:dDC />
    <oc:permissions />
  </d:prop>
</d:propfind>
```

```http
HTTP/1.1 500 Internal Server Error
Date: Tue, 08 Dec 2015 10:11:30 GMT
Server: Apache
X-Powered-By: PHP/5.6.9
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: Sameorigin
X-Robots-Tag: none
Content-Length: 191
Connection: close
Content-Type: application/xml; charset=utf-8

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>OCP\Files\StorageNotAvailableException</s:exception>
  <s:message/>
</d:error>
```

The server log says:
```
{"reqId":"CbgA5p0GRKRhwcY7PE5T","remoteAddr":"81.62.32.191","app":"webdav","message":"Exception: {\"Message\":\"\",\"Exception\":\"OCP\\\\Files\\\\StorageNotAvailableException\",\"Code\":0,\"Trace\":\"
#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud-8.2.0\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/availability.php(421): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->checkAvailability()\\n
#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud-8.2.0\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(498): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->getDirectDownload('')\\n
#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud-8.2.0\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php(334): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getDirectDownload('')\\n
#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud-8.2.0\\\/lib\\\/private\\\/connector\\\/sabre\\\/filesplugin.php(187): OC\\\\Connector\\\\Sabre\\\\File->getDirectDownload()\\n
#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud-8.2.0\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/PropFind.php(98): OC\\\\Connector\\\\Sabre\\\\FilesPlugin->OC\\\\Connector\\\\Sabre\\\\{closure}()\\n
#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud-8.2.0\\\/lib\\\/private\\\/connector\\\/sabre\\\/filesplugin.php(192): Sabre\\\\DAV\\\\PropFind->handle('{http:\\\/\\\/ownclou...', Object(Closure))\\n
#6 [internal function]: OC\\\\Connector\\\\Sabre\\\\FilesPlugin->handleGetProperties(Object(Sabre\\\\DAV\\\\PropFind), Object(OC\\\\Connector\\\\Sabre\\\\File))\\n
#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud-8.2.0\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n
#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud-8.2.0\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1016): Sabre\\\\Event\\\\EventEmitter->emit('propFind', Array)\\n
#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud-8.2.0\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(936): Sabre\\\\DAV\\\\Server->getPropertiesByNode(Object(Sabre\\\\DAV\\\\PropFind), Object(OC\\\\Connector\\\\Sabre\\\\File))\\n
#10 \\\/srv\\\/www\\\/htdocs\\\/owncloud-8.2.0\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(327): Sabre\\\\DAV\\\\Server->getPropertiesForPath('', Array, 1)\\n
#11 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropfind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#12 \\\/srv\\\/www\\\/htdocs\\\/owncloud-8.2.0\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n
#13 \\\/srv\\\/www\\\/htdocs\\\/owncloud-8.2.0\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n
#14 \\\/srv\\\/www\\\/htdocs\\\/owncloud-8.2.0\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#15 \\\/srv\\\/www\\\/htdocs\\\/owncloud-8.2.0\\\/apps\\\/files\\\/appinfo\\\/remote.php(55): Sabre\\\\DAV\\\\Server->exec()\\n
#16 \\\/srv\\\/www\\\/htdocs\\\/owncloud-8.2.0\\\/remote.php(137): require_once('\\\/srv\\\/www\\\/htdocs...')\\n
#17 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud-8.2.0\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/availability.php\",\"Line\":63}","level":4,"time":"2015-12-08T10:15:27+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
```
<hr/>

Ref https://github.com/owncloud/enterprise/issues/933

<hr/>

@icewind1991 @schiesbn

**Comment by PVince81** [comment]
Note that some better error handling has been added recently. I don't think this was backported to 8.0.

**Comment by LukasReschke** [comment]
> Note that some better error handling has been added recently. I don't think this was backported to 8.0.

S3 is on 8.2.0. The error handling on the sending side is there, but the receiving side is still broken.

**Comment by PVince81** [comment]
Do we have a more exact version than 8.0 ?

I'll try and find the tickets that fix the issue to see if they are backportable.

**Comment by PVince81** [comment]
Here's one: https://github.com/owncloud/core/pull/17273 (8.1 only)
and also https://github.com/owncloud/core/pull/15530 which has a 8.0 backport (8.0.4)

**Comment by PVince81** [comment]
@LukasReschke do you mean that 8.2 also needs better fixing ? Maybe there are still a few code paths that need better exception catching in case the remote server returns malformed content.

**Comment by PVince81** [comment]
- [ ] TODO: 8.2 check that StorageNotAvailable returns a 503 error code instead of 500. It should also allow the root list to be listed. Only when exploring the subdir it should return 503. (this was fixed before, maybe a regression)

**Comment by PVince81** [comment]
Interestingly the exception is thrown in the PROPFIND handling code `handleGetProperties`:
```
#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud-8.2.0\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php(334): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getDirectDownload('')\
```

In general, handleGetProperties would work even with a non-available storage because we have the properties from cache. However it seems that for some reason the direct download link was requested explicitly and that code path might throw the exception apparently.

I'm still not clear why/who would request that property, maybe the sync client in some setups.
Let's see...

**Comment by PVince81** [comment]
With this PR it would catch the exception when calling `getDirectDownload()` on an unavailble storage: https://github.com/owncloud/core/pull/21046

**Comment by PVince81** [comment]
Next up: try and reproduce the issue.
I hope we can get the more exact 8.0 version too.

**Comment by PVince81** [comment]
@cmonteroluque I have set this ticket to 8.2. We should at least look into making sure that 8.2.x still can sync whenever a remote storage is not available.
This used to work, I remember testing this in the 8.1 times so it might be a regression.
Will confirm this after testing.

**Comment by PVince81** [comment]
I tried the following:

1. Setup OC A: 8.0.3RC3 (an older instance I had lying around)
1. Setup OC B: 8.2.0
1. Login in OC A
1. Create a folder "test"
1. Share "test" with root@OCB
1. Login in OC B
1. Accept the share
1. Back in OC A
1. Delete the folder "test" (leave it in trash)
1. On OC B: do a PROPFIND on the root and request all properties including the download URL
1. On OC A delete "test" from trash
1. Try again with the PROPFIND

In all cases, I was able to get a correct result for the PROPFIND on root.
A PROPFIND on "/test" in OC B correctly returned a 503 exception.

For now => cannot reproduce with folders.

But now let's try again with a single file.

**Comment by PVince81** [comment]
Same test but with the owncloud manual, say "test.pdf".
Same results, all works.

Now let's try with having the file inside a folder on OC A: share "test/test.pdf", but then delete the parent folder "test".

**Comment by PVince81** [comment]
Same result.

Next step is to try and find out more precise steps, whether parent folder / reshares were involved and also the exact OC 8.0 version.

**Comment by PVince81** [comment]
Seeing in your log that `getDirectDownload()` throws an exception, the only place it does is when the storage was already marked as unavailable thanks to @Xenopathic's new mechanism.
I tried to trigger this by manually setting "availble" to 0 for the shared storages in "oc_storages".
BUT when I do so, the PROPFIND sets it back to 1 ?!

So it looks like some connection is still able to go through and is not interpreting the missing file as a missing availability. But in your system it does. That OC 8.0 instance is still available in general ?

**Comment by PVince81** [comment]
From the original post it looks like the OC 8.0 instance wasn't giving a correct response, this is likely to have made the availability detection set it to 0. I'll try and simulate that case.

Anyway, a fix will be needed for 8.2 to make sure that unavailable remote storages do not throw uncontrolled exceptions.

**Comment by PVince81** [comment]
Okay, so here is the fix for 8.2 https://github.com/owncloud/core/pull/21046
I'll make another PR for master where the files are in another location.

**Comment by PVince81** [comment]
Hmmmm, the 9.0 fix will be more complicated because now we also call `$storage->getOwner()` in `getDirectoryContents()` and that one throws `StorageNotAvailableException` too...

**Comment by PVince81** [comment]
The 9.0 / master fix will require https://github.com/owncloud/core/pull/21086 to fully work.
I'll submit another PR to forward port https://github.com/owncloud/core/pull/21046

**Comment by PVince81** [comment]
master/9.0 PR is here https://github.com/owncloud/core/pull/21087

**Comment by PVince81** [comment]
### Steps to reproduce
1. Setup OC A and OC B
1. From OC A share a file remotely with OC B
1. Accept the share in OC B
1. Edit OC A's index.php and add garbage
1. In OC B, set "availability" to 0 in oc_storages for the remote storage (or trigger it, not sure how, it happens eventually)
1. Create a text file "propfind.txt" and use the contents
```xml
<?xml version="1.0" ?>
<d:propfind xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">
  <d:prop>
    <d:resourcetype />
    <d:getlastmodified />
    <d:getcontentlength />
    <d:getetag />
    <oc:id />
    <oc:downloadURL />
    <oc:dDC />
    <oc:permissions />
  </d:prop>
</d:propfind>
```
1. Curl against OC B: `curl -X PROPFIND -H "Content-Type: application/xml" --data-binary "@propfind2.txt" http://root:admin@localhost/owncloud/remote.php/files/ | xmllint --format -`

### Expected result
File listing appears, including the unavailable share.

### Actual result
503 error, no listing

- Fix for stable8.2: https://github.com/owncloud/core/pull/21046
- Fixes for master: https://github.com/owncloud/core/pull/21086 https://github.com/owncloud/core/pull/21087
