### ISSUE TITLE
Caching not enabled on URLs despite serving static files

### ISSUE THREAD

**Issue by mitar** [owncloud/core#21036]
Example response headers on my ownCloud 8.2.1 installation for `/remote.php/webdav/download.mp3`:

```
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Connection: keep-alive
Content-Disposition: attachment
Content-Disposition: attachment
Content-Length: 39343336
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *
Content-Type: audio/mpeg
Date: Tue, 08 Dec 2015 11:11:22 GMT
ETag: "851440c8f536eaebb17a392718dc0e3f"
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Last-Modified: Tue, 08 Dec 2015 10:35:50 GMT
OC-ETag: "851440c8f536eaebb17a392718dc0e3f"
Pragma: no-cache
Server: nginx
X-Content-Type-Options: nosniff
X-Frame-Options: Sameorigin
X-Robots-Tag: none
X-XSS-Protection: 1; mode=block
```

Observe that there are many headers which are effectively disabling caching (`Expires` way in the past, `Pragma: no-cache`, `Cache-Control: no-store, no-cache`), but there are correct `Last-Modified` and `ETag` headers set which would really make things easy to cache. I do not understand why caching is disabled? So if a file changes, then both `ETag` and `Last-Modified` will change? So clients can request a response only if any of those fields are different.

I am trying to build an [radio app](https://github.com/mitar/radio-app) on top of ownCloud, but I really have issues because it is so ineffective for media files: no caching, and no seeking/range support. Really sad.

**Comment by karlitschek** [comment]
What do you think @LukasReschke  ?
Cool app by the way :-)

**Comment by LukasReschke** [comment]
There are two considerations here:

1. The case where a shared PC would be used and after logging out still all accessed files would be stored. We also use WebDAV for the web interface for some operations in 9.0.
2. The case where a caching reverse proxy such as Varnish is used.

Let me think about it some more…

**Comment by mitar** [comment]
> The case where a shared PC would be used and after logging out still all accessed files would be stored. We also use WebDAV for the web interface for some operations in 9.0.

OK, what is a threat model here? Is it that a) you worry about an user using a shared computer and once they log out that somebody can still access the file URLs from the browser? Or b) is that using a shared computer now files be available in the browser's cache on filesystem so somebody can access them?

I think this should be a configuration option then, because different users have a different threat model. For example, in my case all files are made shared and public anyway and I would prefer caching over security I do not need in my case. But I do agree that for some other users a different threat model can apply. But I do think we can make one design decision for all use cases, especially if we want to see ownCloud as an app platform for various uses.

If it is a), then the solution is simple, you use `Cache-Control: must-revalidate` header and you mix session into Etag. So once session changes (user logs out) Etag changes.

> The case where a caching reverse proxy such as Varnish is used.

That can be addressed with `Cache-Control: private` which I would be OK with setting. In my case I am interested in client-side (browser) caching.

**Comment by mitar** [comment]
For b), one option would be that the ownCloud remembers all the URLs if fetched since the user logged in, and then on logout it makes an ajax query to all ot those URLs again requesting the user to send a no-cache header this time for them, effectively clearing the cache. Not sure if it is worth it, though.

I think the easiest way would be to provide an option to enable `Cache-Control: private` and additionally `must-revalidate`, with explanation that this will potentially allow people to access files on the user's computer after logout.

**Comment by mitar** [comment]
Of course, files could always be encrypted, so cached files would be encrypted files. So then on logout you just erase the decryption key and this is it. So for really paranoid that is the solution and they can even keep the cache.

**Comment by butonic** [comment]
Cache-Control and Expires are not sent with current master. Pragma may be sent by php (session.cache_limiter must be empty in php.ini ). 
```
HTTP/1.1 200 OK
Date: Wed, 09 Nov 2016 22:19:18 GMT
Server: Apache/2.4.18 (Ubuntu)
Content-Security-Policy: default-src 'none';
Last-Modified: Wed, 20 Apr 2016 07:41:18 GMT
ETag: "2a289fa28e9bfbfe41d6de90048dff36"
Content-Length: 1459
Content-Disposition: attachment; filename*=UTF-8''hosts; filename="hosts"
OC-ETag: "2a289fa28e9bfbfe41d6de90048dff36"
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Robots-Tag: none
X-Frame-Options: SAMEORIGIN
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: application/octet-stream
```

Considering this fixed.
