### ISSUE TITLE
vCard VERSION is repeated 5 times and propstat has no etag for the addressbook at all

### ISSUE THREAD

**Issue by marneu** [owncloud/core#21049]
Using 8.2
Using the output from XML I find 5 times repeated the VERSION:3.0 
And within the header for the addressbook I find the d:getlastmodified but don't see an etag.
Does this function as designed or bug?

When reading http://sabre.io/dav/building-a-carddav-client/ I have understood that the etag could be a good point to stop syncing immediately if the etag remains the same from the header.

**Comment by RealRancor** [comment]
@marneu I think you should re-open this in https://github.com/owncloud/contacts/issues using the issue template (if suitable) provided here: https://github.com/owncloud/contacts/blob/master/CONTRIBUTING.md#short-version

**Comment by marneu** [comment]
May be later, it does not hurt - just didn't want to forget it. I far as I understood, there is new contacts version on it's way ...
