### ISSUE TITLE
Updating from OC 8.1.4 to OC 8.2.1 - Updater, Text Editor 2.0 & SMB Share Problems #2

### ISSUE THREAD

**Issue by capnjb** [owncloud/core#21050]
### Steps to reproduce
1.Issue 1 -  Enable Updater App
2.Issue 2 - Create text file on SMB Share and Open and add text
3. Issue 3 - Create text file in user data files directory and Open and add text
4. Issue 4 - Delete files or add File to an SMB share

It is unknown if these are related or not.  I have two systems that have nearly the exact same problem that will be posted here as well.

### Expected behaviour
1.Issue 1 -  Updater should work 
2.Issue 2 - Create text file on SMB Share and Open and add text.  The text editor should automatically save changes to text flle
3. Issue 3 - Create text file in user data files directory and open and add text. The text editor should automatically save changes to text flle
4. Issue 4 - File listing on the OC webpage are updated as files are added or deleted from the shared directory

### Actual behaviour
- Updater App kills the ownCloud Admin webpage (If disabled al is OK)
- Text Editor 2.0 creates a file OK on an SMB share and the very first auto save works after that they all fail including when closing/exiting the file.  If you attempt to delete the file it will not delete.
- Text Editor 2.0 creates a file OK in the ownCloud local data directory.  It works for a while.. eventually you can open the file but cannot edit it anymore. If you attempt to delete the file it will not delete as complains that the file is locked.
- SMB shares don't reindex when changes are made (The SMB shares are not updated on ownCloud) in the shared directory

### Server configuration
**Operating system**:
CentOS 6.5
**Web server:**
 Apache 2.2.15
**Database:**
MySQL 5.1.73
**PHP version:**
5.4.45
**ownCloud version:** (see ownCloud admin page)
8.2.1 (Stable)
**Updated from an older ownCloud or fresh install:**
8.1.4
**List of activated apps:**
```
Enabled:
  - activity: 2.1.3
  - documents: 0.11.0
  - files: 1.2.0
  - files_external: 0.3.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - firstrunwizard: 1.1
Disabled:
  - encryption
  - external
  - files_videoviewer
  - gallery
  - notifications
  - provisioning_api
  - templateeditor
  - user_external
  - user_ldap
```
**The content of config/config.php:**
```
<?php
$CONFIG = array (
  'instanceid' => 'oc9015e1d0d9',
  'passwordsalt' => '**********************',
  'trusted_domains' => 
  array (
    0 => '***************.net',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.2.1.4',
  'installed' => true,
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'owncloud',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => '192.168.0.4',
  'mail_smtpport' => '25',
  'mail_smtpname' => 'owncloud@**************.com',
  'mail_smtppassword' => 'owncloud',
  'mail_from_address' => 'owncloud',
  'mail_domain' => '***************.com',
  'theme' => '',
  'maintenance' => false,
  'enable_previews' => true,
  'preview_max_x' => NULL,
  'preview_max_y' => NULL,
  'preview_max_scale_factor' => 10,
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'preview_office_cl_parameters' => '',
  'appcodechecker' => false,
  'loglevel' => 0,
  'secret' => '******************************************',
  'trashbin_retention_obligation' => 'auto',
);
```
**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes SMB/CIFS
**Are you using encryption:** yes/no
NO
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO
```
### Client configuration
**Browser:**
Does not Matter - Chrome/Firefox
**Operating system:**
Does not Matter - Windows 7/Windows Xp

### Logs
#### Web server error log
```
[Sun Dec 06 03:25:01 2015] [notice] Digest: generating secret for digest authentication ...
[Sun Dec 06 03:25:01 2015] [notice] Digest: done
[Sun Dec 06 03:25:01 2015] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.4.45 mod_ssl/2.2.15 OpenSSL/1.0.1e-fips configured -- resuming normal operations
[Tue Dec 08 10:27:33 2015] [notice] caught SIGTERM, shutting down
[Tue Dec 08 10:27:33 2015] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Tue Dec 08 10:27:33 2015] [notice] Digest: generating secret for digest authentication ...
[Tue Dec 08 10:27:33 2015] [notice] Digest: done
[Tue Dec 08 10:27:33 2015] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.4.45 mod_ssl/2.2.15 OpenSSL/1.0.1e-fips configured -- resuming normal operations
[Tue Dec 08 10:28:00 2015] [error] [client 192.168.0.28] Directory index forbidden by Options directive: /var/www/html/
[Tue Dec 08 10:28:00 2015] [error] [client 192.168.0.28] File does not exist: /var/www/html/favicon.ico
[Tue Dec 08 10:28:00 2015] [error] [client 192.168.0.28] File does not exist: /var/www/html/favicon.ico
[Tue Dec 08 11:11:07 2015] [error] [client 192.168.0.28] PHP Warning:  phpinfo(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /var/www/html/*info.php on line 1
[Tue Dec 08 11:11:08 2015] [error] [client 192.168.0.28] File does not exist: /var/www/html/favicon.ico, referer: http://192.168.0.2:81/*info.php
[Tue Dec 08 11:19:01 2015] [error] [client 192.168.0.254] client denied by server configuration: /var/www/html/owncloud/data/htaccesstest.txt
[Tue Dec 08 11:19:01 2015] [error] [client 192.168.0.254] File does not exist: /var/www/html/core
```
#### ownCloud log (data/owncloud.log)
```
{"reqId":"7rj0ZNanNIj9OYFz7ZhV","remoteAddr":"192.168.0.254","app":"core","message":"No update found at the ownCloud appstore for app 166049","level":0,"time":"2015-11-27T18:26:58+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/list?category=1&includeUpdateInfo=1"}
{"reqId":"7rj0ZNanNIj9OYFz7ZhV","remoteAddr":"192.168.0.254","app":"core","message":"No update found at the ownCloud appstore for app 166051","level":0,"time":"2015-11-27T18:26:58+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/list?category=1&includeUpdateInfo=1"}
{"reqId":"0d561ucVZ1hI2S+DJWBH","remoteAddr":"192.168.0.254","app":"core","message":"No update found at the ownCloud appstore for app 166055","level":0,"time":"2015-11-27T18:29:09+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"0d561ucVZ1hI2S+DJWBH","remoteAddr":"192.168.0.254","app":"core","message":"No update found at the ownCloud appstore for app 166054","level":0,"time":"2015-11-27T18:29:10+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"0d561ucVZ1hI2S+DJWBH","remoteAddr":"192.168.0.254","app":"core","message":"No update found at the ownCloud appstore for app 166051","level":0,"time":"2015-11-27T18:29:10+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"0d561ucVZ1hI2S+DJWBH","remoteAddr":"192.168.0.254","app":"core","message":"No update found at the ownCloud appstore for app 166056","level":0,"time":"2015-11-27T18:29:10+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"0d561ucVZ1hI2S+DJWBH","remoteAddr":"192.168.0.254","app":"core","message":"No update found at the ownCloud appstore for app 166046","level":0,"time":"2015-11-27T18:29:11+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"0d561ucVZ1hI2S+DJWBH","remoteAddr":"192.168.0.254","app":"core","message":"No update found at the ownCloud appstore for app 166048","level":0,"time":"2015-11-27T18:29:11+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"0d561ucVZ1hI2S+DJWBH","remoteAddr":"192.168.0.254","app":"core","message":"No update found at the ownCloud appstore for app 166049","level":0,"time":"2015-11-27T18:29:12+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"0d561ucVZ1hI2S+DJWBH","remoteAddr":"192.168.0.254","app":"core","message":"No update found at the ownCloud appstore for app 166049","level":0,"time":"2015-11-27T18:29:12+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"OVrWrvCLnXTq0phpw8om","remoteAddr":"192.168.0.254","app":"DeleteOrphanedSharesJob","message":"0 orphaned share(s) deleted","level":0,"time":"2015-11-27T18:29:39+00:00","method":"GET","url":"\/owncloud\/cron.php"}
{"reqId":"fPvS+3GNEInzWLozWZ0y","remoteAddr":"192.168.0.254","app":"core","message":"Generating preview for \"\/!Test\/text.txt\" with \"OC\\Preview\\TXT\"","level":0,"time":"2015-11-27T18:31:40+00:00","method":"GET","url":"\/owncloud\/index.php\/core\/preview.png?file=%2F!Test%2Ftext.txt&x=75&y=75&c=1449009525&forceIcon=0"}
{"reqId":"kJxglVK+nzhdiLFZMnzI","remoteAddr":"192.168.0.254","app":"core","message":"Generating preview for \"\/!Test\/text.txt\" with \"OC\\Preview\\TXT\"","level":0,"time":"2015-11-27T18:31:41+00:00","method":"GET","url":"\/owncloud\/index.php\/core\/preview.png?file=%2F!Test%2Ftext.txt&c=1449009525&x=32&y=32&forceIcon=0"}
{"reqId":"xpA3g9BKhKrJhuEUzt1N","remoteAddr":"192.168.0.254","app":"files_versions","message":"Mark to expire \/!Test\/text.txt next version should be 1448562691 or smaller. (prevTimestamp: 1448649091; step: 86400","level":0,"time":"2015-12-08T16:18:50+00:00","method":"GET","url":"\/owncloud\/cron.php"}
{"reqId":"xpA3g9BKhKrJhuEUzt1N","remoteAddr":"192.168.0.254","app":"files_versions","message":"Mark to expire \/!Test\/text.txt next version should be 1448562691 or smaller. (prevTimestamp: 1448649091; step: 86400","level":0,"time":"2015-12-08T16:18:50+00:00","method":"GET","url":"\/owncloud\/cron.php"}
{"reqId":"xpA3g9BKhKrJhuEUzt1N","remoteAddr":"192.168.0.254","app":"files_versions","message":"Mark to expire \/!Test\/text.txt next version should be 1448562691 or smaller. (prevTimestamp: 1448649091; step: 86400","level":0,"time":"2015-12-08T16:18:50+00:00","method":"GET","url":"\/owncloud\/cron.php"}
{"reqId":"xpA3g9BKhKrJhuEUzt1N","remoteAddr":"192.168.0.254","app":"files_versions","message":"Expire: \/!Test\/text.txt.v1448649069","level":0,"time":"2015-12-08T16:18:50+00:00","method":"GET","url":"\/owncloud\/cron.php"}
{"reqId":"xpA3g9BKhKrJhuEUzt1N","remoteAddr":"192.168.0.254","app":"files_versions","message":"Expire: \/!Test\/text.txt.v1448649035","level":0,"time":"2015-12-08T16:18:50+00:00","method":"GET","url":"\/owncloud\/cron.php"}
{"reqId":"xpA3g9BKhKrJhuEUzt1N","remoteAddr":"192.168.0.254","app":"files_versions","message":"Expire: \/!Test\/text.txt.v1448649014","level":0,"time":"2015-12-08T16:18:50+00:00","method":"GET","url":"\/owncloud\/cron.php"}
```
#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by LukasReschke** [comment]
> 1.Issue 1 - Updater should work 
> 2.Issue 2 - Create text file on SMB Share and Open and add text. The text editor should automatically save changes to text flle
> 3. Issue 3 - Create text file in user data files directory and open and add text. The text editor should automatically save changes to text flle
> 4. Issue 4 - File listing on the OC webpage are updated as files are added or deleted from the shared directory

Can you open dedicated new issues for each one of this? THX.
