### ISSUE TITLE
The warning "Redis server too old" is potentially misleading

### ISSUE THREAD

**Issue by laryllian** [owncloud/core#21054]
Hey all,
the warning "Redis server too old." is potentially misleading, since the check can also fail, if only the  php5-redis-Module is too old. Referring to https://github.com/owncloud/core/issues/17731

Solution:
Change the warning to "Redis server (or corresponding modules) too old."

**Comment by karlitschek** [comment]
cool. Do you want to open a pull request for a fix?

**Comment by paurisa** [comment]
Where is the file containing this string? Did a grep from the root folder and just found an archive in /tests/lib/memcache/redis.php that contains a similar line but not exactly the same. 
Has this been already fixed?

**Comment by PVince81** [comment]
I can't find any related message on master. Maybe that message is produced by PHP itself ?

**Comment by PVince81** [comment]
Please reopen if issue persists in 10.0.4
