### ISSUE TITLE
Admin pages not available after 8.2.1 upgrade if updater V0.6 app enabled

### ISSUE THREAD

**Issue by keynet** [owncloud/core#21051]
### Expected behaviour
After update via RPM, admin functions should still work

### Actual behaviour
Admin menu just gives white page if updater app is enabled
The following is logged in the syslog
`Class 'OC_Appconfig' not found at /srv/www/htdocs/owncloud/apps/updater/admin.php#31`
`{PHP} Undefined index: owner at /srv/www/htdocs/owncloud/apps/files/index.php#152`
`{PHP} Undefined index: ownerDisplayName at /srv/www/htdocs/owncloud/apps/files/index.php#153`
`{PHP} Undefined index: owner at /srv/www/htdocs/owncloud/apps/files/lib/helper.php#56`
`{PHP} Undefined index: ownerDisplayName at srv/www/htdocs/owncloud/apps/files/lib/helper.php#57`

Notes 
The updater app appears to date from the last install (September) and was not removed or updated.
Owncloud appears to work OK aside from the above lack of admin 
Disabling the updater app allows admin pages to work again

The following observed during command line upgrade
`PHP Fatal error:  Class 'OC\App\CodeChecker' not found in /srv/www/htdocs/owncloud/lib/private/installer.php on line 570`

I re-ran and it was OK

### Server configuration
SLES11 SP4

**Web server:**
Apache 2.2.27

**Database:**
Mysql 5.5.43

**PHP version:**
5.6.9

**ownCloud version:** (see ownCloud admin page)
8.2.1 upgraded from 8.1.4
(built from source owncloud-8.2.1-1.1.src.rpm  without error)
Note there is no updater app in the build - should there be?

**List of activated apps:**
Activity, deleted files, external storage, first run, gallery, pdf, share files, text ed, versions, video 

config
{
    "system": {
        "instanceid": "xxxxxxxxxxxxxxxxxxxxxxx",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "127.0.0.1",
            "oc.xxxxxxxx",
            "oc.xxxxxxxx"
        ],
        "datadirectory": "\/mnt\/lvm\/owncloud",
        "version": "8.2.1.4",
        "dbtype": "mysql",
        "dbhost": "127.0.0.1",
        "dbname": "owncloud",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "installed": true,
        "log_type": "syslog",
        "knowledgebaseenabled": true,
        "enable_avatars": false,
        "allow_user_to_change_display_name": true,
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "skeletondirectory": "",
        "mail_domain": "xxxxxxxxxxxxxxxx",
        "mail_from_address": "owncloud",
        "mail_smtpdebug": false,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "127.0.0.1",
        "mail_smtpport": "25",
        "mail_smtptimeout": 10,
        "overwritehost": "",
        "overwriteprotocol": "",
        "overwritewebroot": "",
        "overwritecondaddr": "",
        "overwrite.cli.url": "http:\/\/oc.ha-server.lan",
        "trashbin_retention_obligation": "120, auto",
        "appcodechecker": true,
        "updatechecker": true,
        "has_internet_connection": true,
        "check_for_working_webdav": true,
        "check_for_working_htaccess": true,
        "logfile": "owncloud.log",
        "loglevel": 0,
        "logdateformat": "F d, Y H:i:s",
        "logtimezone": "Europe\/London",
        "log_query": false,
        "cron_log": true,
        "log_rotate_size": false,
        "blacklisted_files": [
            ".htaccess"
        ],
        "xframe_restriction": true,
        "cipher": "AES-256-CFB",
        "minimum.supported.desktop.version": "1.7.0",
        "quota_include_external_storage": true,
        "filesystem_check_changes": 1,
        "asset-pipeline.enabled": true,
        "mount_file": "\/mnt\/lvm\/owncloud\/mount.json",
        "filesystem_cache_readonly": false,
        "maintenance": false,
        "theme": "",
        "debug": true
    }
}

**Comment by LukasReschke** [comment]
Where did you get the RPM from?

**Comment by keynet** [comment]
https://download.owncloud.org/download/repositories/stable/owncloud/
I used the leap version, as there is no longer a current one for SLE11 or 12

**Comment by LukasReschke** [comment]
@jnweiger Do we bundle the updater app with that packages?

**Comment by RealRancor** [comment]
@LukasReschke Packages are not shipped with packages as discussed here: https://github.com/owncloud/core/issues/20592 and some other issues. But this problem might happen if the updater app wasn't removed during an upgrade of the packages.

**Comment by keynet** [comment]
The updater was in the 8.1.4 package I think, so I'm thinking update packages should remove it if that's the ongoing plan, else the old updater kills the admin interface. 
I have just deleted the updater directory for now.

**Comment by keynet** [comment]
By the way, I'm still getting these when navigating in owncloud
    {PHP} Undefined index: owner at /srv/www/htdocs/owncloud/apps/files/index.php#152
    {PHP} Undefined index: ownerDisplayName at /srv/www/htdocs/owncloud/apps/files/index.php#153
    {PHP} Undefined index: owner at /srv/www/htdocs/owncloud/apps/files/lib/helper.php#56
    {PHP} Undefined index: ownerDisplayName at /srv/www/htdocs/owncloud/apps/files/lib/helper.php#57

**Comment by PVince81** [comment]
@keynet something might be wrong with your storages. Does the files app still work properly ?
Might posting a dump of "oc_storages" for the user who seems this error, in a separate ticket ?
Let's keep this ticket here for the update issue.
Thanks.

**Comment by PVince81** [comment]
I hope it's not a case of "not all the source code of ownCloud was updated properly" which of course could cause any case of unpredictable issues to happen...

**Comment by keynet** [comment]
Files app seems to be working as far as I can tell - it is syncing files. 
Of course this morning I can't make it create these "undefined index" messages...

So I checked all the files dated from the last RPM install (8.1.4) , and as well as the updater app mentioned above, the following files seem to date from that install, and were not updated or removed.

file:///srv/www/htdocs/owncloud/l10n
file:///srv/www/htdocs/owncloud/l10n/l10n.pl
file:///srv/www/htdocs/owncloud/apps/delete_confirmation
file:///srv/www/htdocs/owncloud/apps/delete_confirmation/appinfo
file:///srv/www/htdocs/owncloud/apps/delete_confirmation/appinfo/app.php
file:///srv/www/htdocs/owncloud/apps/delete_confirmation/appinfo/info.xml
file:///srv/www/htdocs/owncloud/apps/delete_confirmation/appinfo/version
file:///srv/www/htdocs/owncloud/apps/delete_confirmation/js
file:///srv/www/htdocs/owncloud/apps/delete_confirmation/js/bind_first.js
file:///srv/www/htdocs/owncloud/apps/delete_confirmation/js/script.js
file:///srv/www/htdocs/owncloud/.mailmap
file:///srv/www/htdocs/owncloud/.tag
file:///srv/www/htdocs/owncloud/.user.ini
file:///srv/www/htdocs/owncloud/core/vendor/handlebars/.bower.json
file:///srv/www/htdocs/owncloud/core/vendor/jcrop/.bower.json
file:///srv/www/htdocs/owncloud/core/vendor/jquery/.bower.json
file:///srv/www/htdocs/owncloud/core/vendor/jquery-migrate/.bower.json
file:///srv/www/htdocs/owncloud/core/vendor/jsTimezoneDetect/.bower.json
file:///srv/www/htdocs/owncloud/core/vendor/select2/.bower.json
file:///srv/www/htdocs/owncloud/core/vendor/snapjs/.bower.json
file:///srv/www/htdocs/owncloud/core/vendor/strengthify/.bower.json
file:///srv/www/htdocs/owncloud/core/vendor/zxcvbn/.bower.json
file:///srv/www/htdocs/owncloud/indie.json
file:///srv/www/htdocs/owncloud/core/vendor/blueimp-md5/.bower.json
file:///srv/www/htdocs/owncloud/core/vendor/moment/.bower.json
file:///srv/www/htdocs/owncloud/core/vendor/underscore/.bower.json
file:///srv/www/htdocs/owncloud/3rdparty/doctrine/common/.gitmodules
file:///srv/www/htdocs/owncloud/3rdparty/james-heinrich/getid3/.gitattributes
file:///srv/www/htdocs/owncloud/3rdparty/kriswallsmith/assetic/.gitattributes

**Comment by PVince81** [comment]
These hidden files like ".mailmap" are not part of the release, and not part of the RPMs.

If you're using RPM packages, you should not use the updater app because they both conflict. If you use packages, always update using the packages.

Not sure how you got the updater app ?

User error -> closing.

You might want to reinstall the OC source code from scratch (keep your "config" and "data" folders) to be clean.

**Comment by keynet** [comment]
I've been through maybe 15-20 version of OC.
Once-upon-a-time the updater was included by default, and as I noted above not removed by a subsequent update, along with possibly other cruft.  
Penalty of being an early adopter is you carry all the history not wanting to blow away that carefully crafted config at every release like a newbie.

**Comment by PVince81** [comment]
Yeah, I guess there was probably a buggy package that included the updater.
From what I remember the updater was there in much older versions and was removed to avoid such issues.
