### ISSUE TITLE
Search in Share API should not return the user that are making the request

### ISSUE THREAD

**Issue by javiergonzper** [owncloud/core#21065]
On the iOS and on the Android mobile apps when we search a user to share a file we are getting also the  same user that are making the request.
This not have sense on our case because we are searching users to share the file with them... and we can not share our file with ourselves.

It is happening on 8.2 versions.

**Comment by PVince81** [comment]
@rullzer is that really the case ?

The web UI currently uses the old ajax API, but if we change it to use the OCS Share API, we'll meet the same problem.

I'm setting this to 9.0 as it will become more relevant.

**Comment by rullzer** [comment]
mmm well I assume @nickvergessen kept it there because else the pagination does not match. Filtering the user out is trivial since you know who you are.

I'd say keep it there and just filter it on the client side. Just like you already need to filter out the users that you already shared with.

**Comment by DeepDiver1975** [comment]
> I'd say keep it there and just filter it on the client side. Just like you already need to filter out the users that you already shared with.

Yes - this was the design decision we did go for when designing the API.

Won't fix for me -> close - THX

**Comment by PVince81** [comment]
Fine be me.

Question: if you still try to create a share with the current user it should fail ?

**Comment by PVince81** [comment]
@javiergonzper I hope it's fine for you too

**Comment by nickvergessen** [comment]
> Question: if you still try to create a share with the current user it should fail ?

Yes https://github.com/owncloud/core/blob/bb8dbc291b710fd044d3ac4a04233cb1ab6dc7c9/lib/private/share/share.php#L683-L688

**Comment by rullzer** [comment]
Yes it fails, you can't share with yourself

**Comment by javiergonzper** [comment]
@PVince81 yes it is ok for me :+1: . We can filter the user on the clients
