### ISSUE TITLE
Migrate Owncloud from Windows to Linux server

### ISSUE THREAD

**Issue by MMS10** [owncloud/core#21063]
### Steps to reproduce
1. Install Linux server with OC 8.0.2
2. Move config / data / DB from Windows to Linux Server
3. Run files:scan --all to be able to access files again

### Expected behaviour
All Users can see their files, shared links and shared with other users content

### Actual behaviour
Users can see their own files.
Shared Links etc. is lost.

### Server configuration
**Operating system**: Windows 2008 R2 -> Ubuntu 14.04.3 LTS

**Web server:** IIS 7.5 -> Apache2

**Database:** MySQL 5.7 -> MySQL 5.5

**PHP version:** NA -> 5.5.9

**ownCloud version:** 8.0.2 -> 8.0.2

**Updated from an older ownCloud or fresh install: Migration

**List of activated apps:**

 - disclaimer
 - files
 - files_pdfviewer
 - files_sharing
 - files_texteditor
 - files_versions
 - provisioning_api
 - templateeditor
 - updater
 - user_ldap

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => 'x',
  'passwordsalt' => 'x',
  'secret' => 'x',
  'trusted_domains' =>
  array (
    0 => '10.50.30.186',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'x',
  'dbtype' => 'mysql',
  'version' => '8.0.2.0',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'x',
  'dbpassword' => 'x',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'theme' => 'sivantos',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'x',
  'mail_smtpport' => '25',
  'mail_from_address' => 'x',
  'mail_domain' => 'x',
  'forcessl' => true,
  'enable_avatars' => false,
  'loglevel' => 0,
  'proxy' => '10.50.30.3:81'
);

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 7

#### ownCloud log (data/owncloud.log)

{"reqId":"9402b2bf254cb81f9dd21192f878795a","remoteAddr":"10.50.30.3","app":"share","message":"could not resolve linkItem","level":0,"time":"2015-12-09T09:22:37+00:00","method":"GET","url":"\/index.php\/apps\/files_sharing\/ajax\/list.php?t=TY6R32YHFSw14Kx&dir=%2F&sort=name&sortdirection=asc"}

**Comment by LukasReschke** [comment]
You can't migrate the DB like that. Only the files, if you need more support please see more support options at https://owncloud.org/support/

**Comment by MMS10** [comment]
I already asked the community
https://forum.owncloud.org/viewtopic.php?f=31&t=31948

Actual the migration is working well, expect shared file handling.
This means DB migration from Win to Linux is not allowed / supported?

**Comment by LukasReschke** [comment]
> This means DB migration from Win to Linux is not allowed / supported?

Unless somebody writes a script to do that: Not possible that way. Writing that script would take quite some time. You could either try to do that yourself, pay [ownCloud Inc.](https://owncloud.com/) do to that, or just resetup all shares manually.
