### ISSUE TITLE
proxy option in config.php and federated cloud sharing

### ISSUE THREAD

**Issue by fuco809** [owncloud/core#21079]
our server is behind a firewall with restricted internet access and only can access internet with a proxy. this proxy is configured in the owncloud/config/config.php file per option "proxy". this normally works, but when using federated cloud sharing with a folder from an external owncloud server this shared folder cannot be accessed. a tcpdump shows that owncloud then tries to connect directly to the server (without proxy).

**Comment by karlitschek** [comment]
@schiesbn do we use the proxy setting here?

**Comment by PVince81** [comment]
@LukasReschke didn't you add proxy support for fed sharing + DAV client recently ?

**Comment by LukasReschke** [comment]
Partially. So it works for stuff like https://github.com/owncloud/core/commit/bf4a0385351f4eb8757a31b4253803211d6cdec7

However, stuff like [`testRemoteUrl`](https://github.com/owncloud/core/blob/f2088cafb8388d5be3b22920403652718c77908b/apps/files_sharing/lib/external/storage.php#L250-L265) still uses `file_get_contents` :see_no_evil:

**Comment by fuco809** [comment]
is this fixed in OC 9 ?

**Comment by PVince81** [comment]
`testRemoteUrl` now uses Guzzle in OC >= 9.1, so it should be fixed there.
