### ISSUE TITLE
Doctrine\DBAL\Exception\TableNotFoundException: SQLSTATE[42S02]: Base table or view not found: 1146 

### ISSUE THREAD

**Issue by CHuLoYo** [owncloud/core#21070]
I update with Updater App to version 8.2.1 and then try to enable some apps inside the owncloud. The upgrade was successful. When I try to enable first app It tries to upgrade the app to new version, but I can't and this error message appears everytime I try to enter in owncloud. My owncloud installation is now useless, I can't pass successfully the screen of upgrade.
The error:

Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'DELETE FROM `oc_queuedtasks` WHERE `app`=?' with params ["search_lucene"]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxx_cloud.oc_queuedtasks' doesn't exist

**Comment by DeepDiver1975** [comment]
You need to update the search lucene app 

duplicate https://github.com/owncloud/core/issues/18327
