### ISSUE TITLE
Rename external storage mount point deletes files

### ISSUE THREAD

**Issue by davitol** [owncloud/core#21074]
### Steps to reproduce

1. Configure a files_external mount point (e.g. SMB)
2. Click on the 'three dots' button in the files view
3. Try to rename the mount point

### Expected behaviour

The rename option should not be shown due to it is not possible to rename files_external mount points

### Actual behaviour

The rename option is shown in the 'three dots' menu.
Note: A message about cannot rename the mount point is shown.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 9.0 pre alpha (daily)

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

**Comment by PVince81** [comment]
Personal mounts can be renamed but not system-wide mounts.

Now that the web UI is using Webdav, the permissions might not be correct so the UI doesn't adjust properly.

**Comment by PVince81** [comment]
Tested with SFTP:
- when renaming a system-wide mount, it says "cannot rename"
- when renaming a personal mount, it renames it in the UI but the rename did not work (will raise separately)

**Comment by PVince81** [comment]
Raised bug with renaming personal mounts (which should be possible) here https://github.com/owncloud/core/issues/21083

**Comment by davitol** [comment]
Renaming a SMB mountpoint, the files are deleted from the backend, that's why I've increased to sev-2

**Comment by PVince81** [comment]
Ok, I'll retest with SMB then. Could be a different issue.

**Comment by PVince81** [comment]
I tried the following:
- SMB system-wide mount, rename from files app => shows rename error (not allowed). No deletions
- SMB system-wide mount, rename mount point in admin page => 
- SMB personal mount, rename from files app => no deletions (rename doesn't work because of https://github.com/owncloud/core/issues/21083)
- SMB personal mount, rename mount point in personal page => no deletions

@davitol please tell me:
1) Where do you configure the SMB storage, admin page or personal page ?
2) How do you configure the SMB storage (which settings)
3) Where do you rename the SMB mount point, admin page, personal page or files web UI ?
4) What exactly is deleted ? The mount point ? The data inside the mount point within the web UI ? The real data on the external storage, as seen when connecting to the SMB folder outside of ownCloud ?

**Comment by davitol** [comment]
@PVince81 
1) Configured in admin page
2) User/Password; root; All user;
smb.conf file in SMB server
´´´
[rootshare]
path = /opt/owncloud/samba
available = yes
valid users = root
read only = no
browseable = yes
public = yes
writable = yes
´´´
3) files web UI
4) The real data on the external storage

**Comment by PVince81** [comment]
hmm, how about the settings on the admin page ? Only username, password, host and share ? Or did you also specify a root path ?

**Comment by davitol** [comment]
![screen shot 2015-12-10 at 14 05 44](https://cloud.githubusercontent.com/assets/10596560/11716072/74446244-9f47-11e5-99e6-7047f6015eca.png)


Cannot reproduce it in 8.2.1.

**Comment by MorrisJobke** [comment]
regression -> not an enhancement but a bug

**Comment by PVince81** [comment]
Actually this bug was hijacked and is actually two bugs... one is "don't show rename option for system-wide external storages" and the other one much more critical is "when renaming ext storage, files got deleted from SMB".

I have raised https://github.com/owncloud/core/issues/21130 for the "don't show rename option for systme-wide mounts"

**Comment by PVince81** [comment]
@davitol are you still seeing this in 9.0beta1 ?

**Comment by davitol** [comment]
@PVince81 Yes, I have just reproduce the issue in 9.0beta1

**Comment by PVince81** [comment]
Is it still deleting actual files ? I'm pretty sure the three dots are still there but most important is to know whether it's deleting files when it shouldn't. (having the three dots is less severe)

**Comment by davitol** [comment]
@PVince81 Yes, just tested. The files are deleted from SMB backend, but I have also tested with my pal @SergioBertolinSG and in his SMB with oC the deletion does not happen. :astonished:

**Comment by SergioBertolinSG** [comment]
Hi, I have reproduced it now with my instance as well.

The first time there were some encrypted files there which couldn't be deleted by oC so perhaps that saved the rest files for being deleted.

**Comment by SergioBertolinSG** [comment]
Raising this to critical since there is data loss.

**Comment by PVince81** [comment]
When I try to rename "/smb" to "/smb_test" I see this in the log:
```
{"reqId":"payL\/2EwdJFi9ExG7f+c","remoteAddr":"127.0.0.1","app":"webdav","message":"Exception: {\"Message\":\"\\\"\\\"\",\"Exception\":\"Icewind\\\\SMB\\\\Exception\\\\AccessDeniedException\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/Share.php(373): Icewind\\\\SMB\\\\Parser->checkForError(Array, '\\\"\\\"')\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/Share.php(98): Icewind\\\\SMB\\\\Share->parseOutput(Array, '\\\"\\\"')\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/Share.php(164): Icewind\\\\SMB\\\\Share->simpleCommand('rmdir', '\\\/')\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/smb.php(261): Icewind\\\\SMB\\\\Share->rmdir('\\\/')\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(80): OC\\\\Files\\\\Storage\\\\SMB->rmdir('')\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/availability.php(83): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->rmdir('')\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/encryption.php(280): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->rmdir('')\\n#7 [internal function]: OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->rmdir('')\\n#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/storage.php(144): call_user_func_array(Array, Array)\\n#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/storage.php(106): OCA\\\\Files_Trashbin\\\\Storage->doDelete('', 'rmdir')\\n#10 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/encryption.php(465): OCA\\\\Files_Trashbin\\\\Storage->rmdir('')\\n#11 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(558): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->moveFromStorage(Object(OCA\\\\Files_Trashbin\\\\Storage), '', 'files\\\/smb_test')\\n#12 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(733): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->moveFromStorage(Object(OCA\\\\Files_Trashbin\\\\Storage), '', 'files\\\/smb_test')\\n#13 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/objecttree.php(239): OC\\\\Files\\\\View->rename('smb', 'smb_test')\\n#14 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(642): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->move('smb', 'smb_test')\\n#15 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMove(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#16 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#17 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:MOVE', Array)\\n#18 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#19 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#20 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/remote.php(137): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#21 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/Parser.php\",\"Line\":61}","level":4,"time":"2016-02-19T11:42:49+00:00","method":"MOVE","url":"\/owncloud\/remote.php\/webdav\/smb"}
```

And indeed it deleted all files :scream: 

I'll debug this. Since renaming such mount points is not allowed, it must not even go to the storage and deny it right away.

**Comment by PVince81** [comment]
@icewind1991 the system-wide mount doesn't implement `MoveableMount`, so it attempts to call `moveFromStorage`. One idea would be to make it implement `MoveableMount` but also return `false` when calling `isTargetAllowed`.

**Comment by PVince81** [comment]
The reason why the deletion happens is because it attempts a `moveFromStorage`. Then the encryption wrapper converts this to `copyBetweenStorage` (even though encryption is not enabled! @schiesbn) and then it deletes it. Basically it converts "rename" to "copy to target name then delete the source".

Several problems here:
- need to catch this situation much earlier and deny the rename
- why is `rmdir('')` on the SMB storage deleting all contents ? it should simply fail

**Comment by PVince81** [comment]
Ah, and the trashbin seems to also play a role...

**Comment by PVince81** [comment]
Basic fix is here: https://github.com/owncloud/core/pull/22518

Will submit a separate PR for hardening

**Comment by PVince81** [comment]
Hardening PR: https://github.com/owncloud/core/pull/22520 (not required to fix this, best is https://github.com/owncloud/core/pull/22518)
