### ISSUE TITLE
Feature Request (able to set permissions on external site links in the admin section)

### ISSUE THREAD

**Issue by Pammetje** [owncloud/core#21082]
I like to be able to set permissions to who (owncloud users) will be able to see external site links (under the admin section). Just like I am able to do under external storage (in the admin section)
So I am able to show certain users an external site link and some not.

Thanks in advance (keep up the good work in this amazing project)

Kr,

Pammetje

**Comment by RealRancor** [comment]
From my PoV a dup of one of those: https://github.com/owncloud/apps/issues/2048, https://github.com/owncloud/apps/issues/1998, https://github.com/owncloud/apps/issues/2037 (which are also partly duplicates).

**Comment by MorrisJobke** [comment]
> From my PoV a dup of one of those: owncloud/apps#2048, owncloud/apps#1998, owncloud/apps#2037 (which are also partly duplicates).

Yes. Closing
