### ISSUE TITLE
Renaming personal mount deletes it / doesn't work

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#21083]
### Steps to reproduce

1. Enable SFTP mount for users
1. Go to the personal page
1. Mount an SFTP storage under "/sftp"
1. Go to the files app and navigate into it, works
1. In the web UI, rename "sftp" to "sftp_renamed"
1. Refresh the page => not renamed
1. Go to the personal page
1. Rename "sftp" to "sftpren"
1. Refresh the page => mount point is gone ?!!

### Expected result
Ability to rename mount points in the files app and also personal page.

### Actual result
Renaming mount point in the files app doesn't work, mount point is not renamed.
Renaming it in the personal page kills it, the config disappears.

### Versions
ownCloud 9.0 pre-alpha git master bec34f12757517a784f6e35fc6b7294ab1673c59

@icewind1991 @Xenopathic

**Comment by PVince81** [comment]
Looks like renaming system-wide mounts (SMB) also doesn't work in the admin page, it stays on the old name. Maybe some problem with the new config code ?

**Comment by icewind1991** [comment]
Fix is here #21215

**Comment by MorrisJobke** [comment]
Tested and works :+1:
