### ISSUE TITLE
Personal page a little bit mixed up

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#21089]
![2015-12-09_20-09-08](https://cloud.githubusercontent.com/assets/878997/11695681/c5bd418c-9eb0-11e5-9074-42bc2d6c45a9.png)

**Comment by LukasReschke** [comment]
Oh. That's in every browser… Ok :speak_no_evil: 

@jancborchardt

**Comment by MorrisJobke** [comment]
Fixes are in https://github.com/owncloud/core/pull/20994

**Comment by jancborchardt** [comment]
Also, this is a duplicate of https://github.com/owncloud/core/issues/20610 ;)
