### ISSUE TITLE
Opening a public share via link in safari shows a login dialog

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#21092]
### Steps to reproduce
1. Share a folder of files via public link
2. Load link in Safari

### Expected behaviour
 - See the list of files

### Actual behaviour
 - Authentication dialog shows asking for user/pass combo 'To view this page, you must log in to area “sabre/dav” on owncloud.dev:80.'

### Server configuration
**Operating system**: OSX :see_no_evil: 
**Web server:** Apache
**Database:** Sqlite
**PHP version:** 5.6
ownCloud 9.0 pre-alpha from git

**Comment by tomneedham** [comment]
![screen shot 2015-12-09 at 20 08 35](https://cloud.githubusercontent.com/assets/660805/11697259/a8066cb8-9eb0-11e5-84bc-d3f0c51c024e.png)

**Comment by schiesbn** [comment]
@LukasReschke afaik you are also using this strange operating system, right? :wink: Can you have a look? Thanks!

**Comment by MorrisJobke** [comment]
I can confirm. Works in chrome and is broken in safari. Only for file lists (shared folders)

**Comment by MorrisJobke** [comment]
@PVince81 I guess you need to show me how to debug this :see_no_evil: 

Looks good so far:
<img width="1264" alt="bildschirmfoto 2015-12-10 um 18 17 44" src="https://cloud.githubusercontent.com/assets/245432/11722669/64b14900-9f6a-11e5-9a5f-705842d1661c.png">

**Comment by PVince81** [comment]
@MorrisJobke check those two webdav calls in the network console. Do they contain a header "WWW-Authenticate" with the value "DummyBasic" ?

If yes, then it means that Safari doesn't want to behave like other browsers and will need an additional workaround... Browsers are supposed to only show this dialog if the value is "Basic" (for basic auth) and not for any custom values. :frowning: 

The code in question is here: https://github.com/owncloud/core/blob/master/apps/dav/lib/connector/sabre/auth.php#L165

**Comment by PVince81** [comment]
Hmmm, I think I mixed this up with "log out detection".

This is actually when trying to connect to public webdav.
Does this share have a password ?

**Comment by PVince81** [comment]
When you open the link share, and after entering the password, it should save this fact in the session.
Then this code https://github.com/owncloud/core/blob/master/apps/dav/lib/connector/publicauth.php#L86 should recognize that the requested token matches the last one for which we were authenticated. So it shouldn't redisplay the dialog.

**Comment by PVince81** [comment]
Now thinking of it, maybe if you open multiple link shares with passwords, the session value will not be valid any more for one of the pages, so the dialog would be shown. To prevent this, we could use the same approach as https://github.com/owncloud/core/issues/21092#issuecomment-163695580 for public auth to make sure we just redirect to the actual password page for re-entry instead of letting this dialog appear.

But first @MorrisJobke would be good to know what is actually happening in your situation :smile:

**Comment by MorrisJobke** [comment]
> Does this share have a password ?

No. Without password.

**Comment by MorrisJobke** [comment]
> @MorrisJobke check those two webdav calls in the network console. Do they contain a header "WWW-Authenticate" with the value "DummyBasic" ?

I would love to do so, but the dialog is faster than me and clicking "Cancel" will redirect me to the login page :(

**Comment by MorrisJobke** [comment]
Also the same as in https://github.com/owncloud/core/issues/20681#issuecomment-163690745 applies here. Debugging this will be PITA :(

**Comment by PVince81** [comment]
@MorrisJobke can you debug into the sabre auth code ?

I was testing something different and found this:
```
        $request->headers['x-requested-with'][1][0] = (string[30]) 'XMLHttpRequest, XMLHttpRequest';
```

Obviously if the header is set twice, the check for the header doesn't work... maybe that's happening for you too ?

**Comment by PVince81** [comment]
@MorrisJobke this PR makes it work even with duplicate headers: https://github.com/owncloud/core/pull/21144

**Comment by MorrisJobke** [comment]
> @MorrisJobke can you debug into the sabre auth code ?

You mean starting in the saber stack :see_no_evil: I never was there, but I can give this a try.

**Comment by PVince81** [comment]
here  https://github.com/owncloud/core/blob/master/apps/dav/lib/connector/publicauth.php#L86 and/or here https://github.com/owncloud/core/blob/master/apps/dav/lib/connector/sabre/auth.php#L165

**Comment by MorrisJobke** [comment]
Mmmmh...it works now. The file list is just working in Safari with current master. :confused:

**Comment by MorrisJobke** [comment]
I tested this with 6317a8 (before @PVince81's header fix went in)

**Comment by cmonteroluque** [comment]
is this ready to close?

**Comment by MorrisJobke** [comment]
I haven't seen this for a while. Just retested and it works here.
