### ISSUE TITLE
enable HSTS by default in .htaccess

### ISSUE THREAD

**Issue by mbiebl** [owncloud/core#21094]
I think it would be a good idea if the default .htaccess shipped by owncloud enables HSTS

<IfModule mod_headers.c>
  Header always set Strict-Transport-Security "max-age=15768000; includeSubDomains; preload"
</IfModule>

**Comment by karlitschek** [comment]
@LukasReschke

**Comment by LukasReschke** [comment]
We can't do this, sorry. This aill explode hard depending on the environment.
