### ISSUE TITLE
Call to a member function getLogger() on a non-object in public/util.php

### ISSUE THREAD

**Issue by MoonshineSG** [owncloud/core#21097]
i just upgraded to 8.2.1 and i get thie error "Fatal error: Call to a member function getLogger() on a non-object in /Users/x/Sites/cloud/lib/public/util.php on line 166" .

**Comment by RealRancor** [comment]
Ref: https://github.com/owncloud/core/issues/20885

Please use the issue template provided here: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md as asked in the guidelines for contributing (linked in the yellow bix when creating a new issue).

**Comment by MorrisJobke** [comment]
> i just upgraded to 8.2.1 and i get thie error "Fatal error: Call to a member function getLogger() on a non-object in /Users/x/Sites/cloud/lib/public/util.php on line 166" .

https://github.com/owncloud/core/blob/v8.2.1/lib/public/util.php#L166

**Comment by MorrisJobke** [comment]
As already stated: it would be really nice to get the issue template filled.

**Comment by dallaslu** [comment]
```log
2016/01/07 23:01:49 [error] 28764#0: *1495 FastCGI sent in stderr: "PHP message: PHP Warning:  flock() expects parameter 1 to be resource, boolean given in /var/www/html/owncloud/lib/private/config.php on line 198
PHP message: PHP Fatal error:  Call to a member function getLogger() on a non-object in /var/www/html/owncloud/lib/public/util.php on line 166" while reading response header from upstream, client: 222.171.XXX.XXX, server: cloud.honeyhaw.com, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "cloud.xxxxxx.com"
```

**Comment by MoonshineSG** [comment]
I solved this by cleaning up the sqlite database - removing old tables, from "System". After that the upgrade works fine. Strange error....

**Comment by apotek** [comment]
@MoonshineSG Are you sure you cleared it by cleaning up your database? Usually you can fix this error by making sure the web server user owns the config/config.php file and the apps/ directory.

In any event, I don't think this is a bug since you fixed it yourself, so this issue should probably be closed as "invalid."

**Comment by MoonshineSG** [comment]
It's solved so yes, I'll close it. Is it a bug? I don't know, but in any case the error message was misleading...
