### ISSUE TITLE
Can't sync Caldav/Carddav on iOS9

### ISSUE THREAD

**Issue by redhell** [owncloud/core#21106]
Hello,

i recently switched to php 7 as it is stable now. I noticed that i can't sync with iOS 9.x

In the log file i find:
Array to string conversion at /*path*/3rdparty/sabre/dav/lib/CalDAV/CalendarQueryValidator.php#62

My server logs doesn't show any error to those timestamps.

After switching back to PHP 5.6 it starts to synchronize again.

- oC 8.2.1
- Ubuntu 14.04.
- MariaDB 10
- PHP 7.0 / PHP 5.6.16
- redis cache and locking
- Calendar/Contacts/Tasks are enabled.

**Comment by MorrisJobke** [comment]
Please open this in the calendar bug tracker. This is not related to the core, but to the calendar app.

https://github.com/owncloud/calendar/issues

Thanks
