### ISSUE TITLE
SMB icon not replaced properly after availability check

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#21110]
### Steps

1. Mount SMB storage globally (admin page)
1. Go to the files app "All files"
1. Wait for availability check to finish

### Expected result
After availability check, icon shows properly

### Actual result
Icon disappears after availability check. (I cleared the cache, same result)

@jmaciasportela please have a look.

**Comment by jmaciasportela** [comment]
@PVince81 Do you have enable windows network drive app? The icon source is on it ... so if it isn't enabled that's the problem

Maybe we can add the icon to files_external or to the core

**Comment by PVince81** [comment]
No WND app, it's just core git.

When it's a SMB mount (not WND), I suggest to not change the icon at all. Leave whatever is there.
Only change it if it's WND.

**Comment by jmaciasportela** [comment]
But the storage backend is the same in both cases, and that info comes from a REST request to:
```
apps/files_external/api/v1
```
in both cases backend is "smb"  because is the main class.

I can change it to use the storage text label "SMB /CIFS", Is good for you?

**Comment by PVince81** [comment]
Hmmm, we should make the WND backend return "wnd" instead because it's a different backend/config.
Is the storage ID "smb://" or "wnd://" ? We need them to be different.

**Comment by jmaciasportela** [comment]
I can extend the main class SMB and only change the name

**Comment by PVince81** [comment]
Sounds good. @icewind1991 agreed ?

**Comment by jmaciasportela** [comment]
Also is useful to override getId method to return the same Id that the old WND app, so migration will be easier

**Comment by PVince81** [comment]
Yes, that makes sense

**Comment by icewind1991** [comment]
> Also is useful to override getId method to return the same Id that the old WND app, so migration will be easier

Yes, otherwise sync clients will try to re-download everything
