### ISSUE TITLE
Feature request - Mandatory notification settings for all users

### ISSUE THREAD

**Issue by ags67** [owncloud/core#21111]
Hello!

I would like to be able to set this settings in the "true" by default in the configuratiom files:

1. Set "Notify by email" to be on for everyone, everything by default when file sharing;

2. Set "Notify about my actions by email" for users notifications settings.

Thanks.

**Comment by MorrisJobke** [comment]
cc @nickvergessen @jancborchardt

**Comment by nickvergessen** [comment]
Since we want to use sensible defaults instead of duplicating all those settings for admins to define the default values, that is unlikely to happen.
But you can do that yourself if you want:

> 1. Set "Notify by email" to be on for everyone, everything by default when file sharing;

* A file or folder has been <strong>shared</strong>
* A file or folder was shared from <strong>another server</strong>

Both are already enabled for emails by default

> 2. Set "Notify about my actions by email" for users notifications settings.

You can enable this, by changing the `return false;` to `return true;` in
https://github.com/owncloud/activity/blob/master/lib/usersettings.php#L92-L93

**Comment by ags67** [comment]
Hello!

When a file shared "Notifi by email" is not checked by default. Which parameter I must change in config for all new users behaviour for file sharing?
![new_file_sharing](https://cloud.githubusercontent.com/assets/16239222/11716046/14e99696-9f58-11e5-8898-a9691b354205.jpg)

**Comment by jancborchardt** [comment]
Actually, this »Notify by email« _should_ be on by default. People should always be notified when something is shared with them. Then if they really want to be notified (whether by email or by web notification) is entirely up to the recipient.

Can we change that @MTRichards? Then we can get rid of that extra element which is also a very confusing interaction as a checkbox.

**Comment by ags67** [comment]
I change the file /var/www/owncloud/apps/activity/lib/usersettings.php 
public function getDefaultSetting($method, $type) {
		if ($method === 'setting') {
			if ($type === 'batchtime') {
				return 3600;
			} else if ($type === 'self') {
				return true;
			} else if ($type === 'selfemail') {
				return true;
			}
		}
		$settings = $this->manager->getDefaultTypes($method);
		return in_array($type, $settings);
	}

But nothing changed while file shared - checkbox "Notify by email" does not checked.

**Comment by nickvergessen** [comment]
> Actually, this »Notify by email« should be on by default.

That settings sends a direct share email, it was disabled when activity was added to the ship list. Activities are triggered independent from that setting, so no, it should NOT be enabled by default

> But nothing changed while file shared - checkbox "Notify by email" does not checked.

Well when you once changed the setting, we store your "no", but for new users it will be "yes".
So you will have to manually tick the box once.

**Comment by ags67** [comment]
nickvergessen - It does not work for me.
Each time for any users (new or existing) when files sharing, the checkbox "Notify by email" is clear.

**Comment by nickvergessen** [comment]
the one in the dropdown yes, but the one on the personal page for shares is checked...
As said, the setting from your screenshot does not do what you think it does,
and my "fix" is not for the one from your screenshot, but from the personal page

**Comment by MTRichards** [comment]
>Actually, this »Notify by email« should be on by default. People should always be notified when something is shared with them. Then if they really want to be notified (whether by email or by web notification) is entirely up to the recipient.

>Can we change that @MTRichards? Then we can get rid of that extra element which is also a very confusing interaction as a checkbox.

Yes, this makes a lot of sense.

**Comment by MTRichards** [comment]
Not much work to make this the default, is it?

**Comment by ags67** [comment]
I was going to monitoring files sharing by mail server logs. Now I don't have any possibilities to control who, which files shared. It can provide critical data leaks from company.

**Comment by MTRichards** [comment]
A better answer for that would be a log manager, with the more in depth logging apps turned on. This is really the design point for controlling data leaks from a company. Another thought is a sharing report that you can just view, but that doesn't yet exist.

**Comment by ags67** [comment]
In the current release of owncloud log manager does not help me - owncloud community edition does not write in logs information about who, what and whom sharing. As a continuing of such task - prevent sharing files from one external user to another external user.
