### ISSUE TITLE
OC 8.2.1 apps/files/ajax/scan.php hangs up server with HTTP/2 enabled

### ISSUE THREAD

**Issue by vansieleghemstijn** [owncloud/core#21121]
When I enable HTTP/2 on my Apache server, Owncloud keeps hanging on the following call: (removed requesttoken)

index.php/apps/files/ajax/scan.php?force=false&dir=&requesttoken=

It even makes my server unreachable and when I turn off HTTP/2 it starts working again as expected.

Here are the response headers for this request: 

> HTTP/2.0 200 OK
> Date: Thu, 10 Dec 2015 14:05:54 GMT
> Server: Apache
> Expires: Thu, 19 Nov 1981 08:52:00 GMT
> Pragma: no-cache
> Content-Security-Policy: default-src https: data: 'unsafe-inline' 'unsafe-eval'
> Cache-Control: no-cache
> x-accel-buffering: no
> Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
> Public-Key-Pins: pin-sha256="veRz1oEOnNHBMQfSg4AnBrACajS4FHH+q78QxryW098=";pin-sha256="CUE8YpWUoNU/J0DhrS5q/HPIE3SJGmfRus2OXpHDirc=";pin-sha256="MIUlsxN4k3nCe++bYswxXTM0yKf3pdNp/9KVfLZc4Ss=";includeSubdomains; > max-age=2592000
> x-xss-protection: 1; mode=block
> x-frame-options: SAMEORIGIN
> x-content-type-options: nosniff
> x-robots-tag: none
> Content-Type: text/event-stream;charset=UTF-8
> X-Firefox-Spdy: h2

The response headers after I've disabled HTTP/2: 

> HTTP/1.1 200 OK
> Date: Thu, 10 Dec 2015 14:13:43 GMT
> Server: Apache
> Expires: Thu, 19 Nov 1981 08:52:00 GMT
> Pragma: no-cache
> Content-Security-Policy: default-src https: data: 'unsafe-inline' 'unsafe-eval'
> Cache-Control: no-cache
> x-accel-buffering: no
> Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
> Public-Key-Pins: pin-sha256="veRz1oEOnNHBMQfSg4AnBrACajS4FHH+q78QxryW098=";pin-sha256="CUE8YpWUoNU/J0DhrS5q/HPIE3SJGmfRus2OXpHDirc=";pin-sha256="MIUlsxN4k3nCe++bYswxXTM0yKf3pdNp/9KVfLZc4Ss=";includeSubdomains; > max-age=2592000
> x-xss-protection: 1; mode=block
> x-frame-options: SAMEORIGIN
> x-content-type-options: nosniff
> x-robots-tag: none
> Keep-Alive: timeout=100, max=200
> Connection: Keep-Alive
> Transfer-Encoding: chunked
> Content-Type: text/event-stream;charset=UTF-8

**Comment by MorrisJobke** [comment]
cc @LukasReschke

**Comment by LukasReschke** [comment]
Works for me on my HTTP/2.0 instance. Anyways, this file will be gone with 9.0 where scan.php is gone. For now I'd recommend to stick to HTTP/1.1.
