### ISSUE TITLE
Feature request: Include a presentation feature

### ISSUE THREAD

**Issue by alex42ka** [owncloud/core#21120]
With impress.js there is a free and open source alternative for neat preasentation-systems like Prezi. 
(Impress.js: https://github.com/impress/impress.js/tree/master 
Demo: http://impress.github.io/impress.js/#/bored )

And there are HTML-based Editors like strut as well.
(strut: https://github.com/tantaman/Strut )

For our school, and I can imagine for many others, it would be really helpful if something like this would be integrated in owncloud as app. 
(But sadly we are not having the capabilities to write it ourselves)

**Comment by MorrisJobke** [comment]
https://github.com/owncloud/apps/tree/master/impress <- available but unmaintained. Can I ask you to reopen this in the apps issues tracker: https://github.com/owncloud/apps/issues 

Thanks
