### ISSUE TITLE
if "Paging chunksize" set to 0, it takes 500 not like the description for that option (0=disabled)

### ISSUE THREAD

**Issue by rolandbu** [owncloud/core#21136]
Hi
If you set the option "Paging chunksize" to 0. It always takes 500 not 0.

This ist the description of the option:
"Chunksize used for paged LDAP searches that may return bulky results like user or group enumeration. (Setting it 0 disables paged LDAP searches in those situations.)"

You can try a simple test. Set it to 0 and go to "LDAP-Users" settings and press "Verify settings and count users" the answer will be "500 users found". Please go back to the "Paging chunksize" option and use for example 2000. Make the same test and the answer is now "> 1000 users found". You need more then 500 active users on your owncloud to reproduce that issue.

*Debian 8 with Owncloud 8.2.1

**Comment by rullzer** [comment]
@blizzz

**Comment by rolandbu** [comment]
any ideas?

**Comment by blizzz** [comment]
had not have time yet. @leo-b like to give it a glance?

**Comment by leo-b** [comment]
It looks like setting a ``pagingSize`` of 0 was disabled by @blizzz: https://github.com/owncloud/core/commit/f28235a7ef6664978a8b4f6d16a47df508244294

However, IMHO even using a ``pagingSize`` of 500 shouldn't limit the number of results to 500. Does your LDAP server support [Paged Results](https://tools.ietf.org/html/rfc2696)?

**Comment by blizzz** [comment]
That commit comes from  a PR fixing https://github.com/owncloud/core/issues/12306, also this affects readAttribute() only. With the comment above, passing 0 we would not get any results (using paged search).

**Comment by leo-b** [comment]
You are right, readAttribute() isn't used when fetching users. Sorry.
So I guess this is the relevant change: https://github.com/owncloud/core/commit/42d3ed47e23724419aeed0df5ccedec6f92ac172

Unfortunately I don't have a working owncloud-ldap infrastructure available at the moment, so it's hard for me to test right now.

**Comment by blizzz** [comment]
Which was supposed to fix https://github.com/owncloud/core/issues/13533#issuecomment-76092306

I guess it makes sense to totally disable paged search when the chunk size is set to 0. Or not? Like this https://github.com/owncloud/core/commit/d5e48669b71e350f57f9c222b48554158d5accf9

@rolandbu 

> You can try a simple test. Set it to 0 and go to "LDAP-Users" settings and press "Verify settings and count users" the answer will be "500 users found". Please go back to the "Paging chunksize" option and use for example 2000. Make the same test and the answer is now "> 1000 users found". You need more then 500 active users on your owncloud to reproduce that issue.

What actually is your expectation?

**Comment by rolandbu** [comment]
@blizzz 
We are using openldap without "paged search". We would be happy with "Paging chunksize = 0" give us the full result without any limits like 500.

**Comment by blizzz** [comment]
The result in the wizard will always show 1000 max users for performance reasons. Hiw many di you have? Coukd you test wether tho commit mentioned above helps?

**Comment by rolandbu** [comment]
I will try your fix https://github.com/owncloud/core/commit/d5e48669b71e350f57f9c222b48554158d5accf9 and report the results, ok?

**Comment by rolandbu** [comment]
@blizzz 
Still the same problem with your fix https://github.com/owncloud/core/commit/d5e48669b71e350f57f9c222b48554158d5accf9 

"Paging chunksize = 0" returns "Verify settings and count users = 500 users found"

**Comment by rolandbu** [comment]
The bug is still in the newest version 8.2.2

@blizzz any ideas?

**Comment by blizzz** [comment]
Just some debug steps to do, but I cannot promise when I will come round to it. One theory is that counting counts the same users until >1k is reached, if $pagesSearchOK https://github.com/owncloud/core/blob/master/apps/user_ldap/lib/access.php#L959 turns out to be true instead of false, as expected. How likely that is, is a different question, but something to verify.

**Comment by blizzz** [comment]
@rolandbu what is the maximum size limit configured on your LDAP server? (In OpenLDAP look for olcSizeLimit). I just checked it here and counting works as desired with  d5e4866. Just one operation is done, and the server replies with the maximum value.

**Comment by blizzz** [comment]
Also would downrate this to medium @cmonteroluque @PVince81

**Comment by blizzz** [comment]
FYI, opened PR with the suggested fix: https://github.com/owncloud/core/pull/23527

**Comment by cmonteroluque** [comment]
@blizzz @PVince81 I agree
