### ISSUE TITLE
Question: Support of CalDAV and CardDAV in 9.0 

### ISSUE THREAD

**Issue by aspdye** [owncloud/core#21132]
Hi there,

I have a little question to the Developers of ownCloud. Does the Integration of the CalDAV and CardDAV Backend mean that Calendar and Contacts (not frontend) will be again part of ownCloud Core - and as this - not longer community apps? So will Calendar and Contacts will again recive a "better" support?  

And what does the CardDAV and CalDAV Integration mean for ownCloud Enterprise? Will they recive Contacts and Calendar too? (Supported)

All in all: A good step from you to move CalDAV and CardDAV into the Core. Thank you for your hard work ;)

**Comment by karlitschek** [comment]
sorry but this is a bug tracker. please ask question on the developer mailinglist. thanks

**Comment by aspdye** [comment]
I'm sorry. I have to learn the various rules of the various (not only ownCloud) repositorys on GitHub :see_no_evil:
