### ISSUE TITLE
PDF Preview Not Working Correctly Again

### ISSUE THREAD

**Issue by mbressman** [owncloud/core#21134]
It seems that PDF preview for my oC v8.1.1 is not working correctly once more - also tested it using the demo.owncloud.org (running v8.2.0) and experienced the same issues.  Some PDF's seem to load fine (generally these seem to be ones I download from the Internet, etc.) and others do not (again, generally this seems to be ones I scan from my Neat Scanner, etc.).  I thought this might be related to a recent Chrome web browser update (since that's what I use for most of my web browsing), but it also is happening in Firefox (although I recently updated Firefox as well).  This seems somewhat related to a previous issues of mine - https://github.com/owncloud/core/issues/18917

Steps to reproduce:
1) scan a document to PDF using my Neat scanner
2) Load that PDF into oC
3) Attempt to preview that PDF in oC
(there are probably other ways to reproduce as well, and I'm not saying it's only PDF's created from my Neat scanner that are problematic - just haven't done enough testing yet)

Expected Behavior: PDF preview displays correctly within web browser
Actual Behavior: I see the correct number (and even correctly sized) pages for the PDF preview, but no text/images show up - they are just blank/white

Server Configuration:
OS: Ubuntu 12.04 LTS
Web Server: Apache v2.2.22
Database: MySQL v5.5.46
PHP Version: 5.4.45-1+deb.sury.org~precise+1
oC Version: 8.1.1 (but also tested with demo.owncloud.org running v8.2.0 and problem persists)
Updated or Fresh Install: Updated
List of apps: 
Enabled:
 - activity: 2.0.1
 - bookmarks: 0.4
 - documents: 0.10.1
 - files: 1.1.10
 - files_external: 0.2.3
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - galleryplus: 13.0.0
 - search_lucene: 0.6.0
 - updater: 0.6
Disabled:
 - encryption
 - external
 - files_locking
 - gallery
 - provisioning_api
 - templateeditor
 - user_external
 - user_ldap
 - user_webdavauth

Config.php:
running "sudo -u www-data php occ config:list system --public" gives me this error:
 [InvalidArgumentException]
 There are no commands defined in the "config" namespace.

<?php
$CONFIG = array (
  'instanceid' => '<unsure if this is private, so REDACTED>',
  'passwordsalt' => '<REDACTED>',
  'datadirectory' => '<REDACTED>',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'dbname' => 'cloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '<REDACTED>',
  'dbpassword' => '<REDACTED>',
  'installed' => true,
  'forcessl' => true,
  'maintenance' => false,
  'memcache.local' => '\\OC\\Memcache\\APC',
  'theme' => '',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => '<REDACTED>',
  'mail_smtpport' => '587',
  'mail_smtpauth' => true,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpname' => '<REDACTED>',
  'mail_smtppassword' => '<REDACTED>',
  'trusted_domains' =>
  array (
    0 => '<REDACTED>',
    1 => '<REDACTED>',
    2 => '<REDACTED>',
    3 => '<REDACTED>',
  ),
  'secret' => '<REDACTED>
);

Are you using external storage, if yes which one? 
Enabled:
- Amazon S3 and Compliant
- Dropbox
- FTP
- Google DRive
- ownCloud
- SFTP
- SMB / CIFS
- WebDAV

Configured:
- Google Drive and Dropbox (via Personal settings and not Admin settings)
- SMB/CIFS (via Admin Settings)

Encryption: No
External User-Backend: No

Client Configuration:
Browser: Chrome v47.0.2526.73 m  -and-  Firefox v42.0
OS: Windows 8.1 Enterprise and Windows 10 (version 1511) Enterprise

Logs: I don't necessarily feel comfortable posting my logs, but can provide upon request

Thanks!!

**Comment by LukasReschke** [comment]
Please reopen and provide the file at http://github.com/owncloud/files_pdfviewer, can you also test with 8.2.0?

**Comment by LukasReschke** [comment]
Also with 8.1.4 and not with 8.1.1 :)

**Comment by LukasReschke** [comment]
@stp-ip Mind updating the demo server once more? :smile:

**Comment by stp-ip** [comment]
Updated.
