### ISSUE TITLE
Desktop clent issue

### ISSUE THREAD

**Issue by albheart** [owncloud/core#21142]
Hello,

Recently installed ownCloud Windows client (ownCloud-2.1.0.5683-setup) and it won't function. 

Everything works fine in my Android devices, it just won't work in windows. It says:

"Failed to connect to ownCloud at http:// xxxxxxxxxxxx . com/owncloud/status.php:
Host xxxxxxxxxxxxx.com not found"
See picture attached.

This is the result of the status.php from the browser.
" {"installed":true,"maintenance":false,"version":"8.2.0.12","versionstring":"8.2.0","edition":""} "

Searched for an answer but found nothing.

Is there any solution for this issue?

![owncloud](https://cloud.githubusercontent.com/assets/16253725/11741181/841d8b68-9ff7-11e5-9f5f-efec7cafd4e1.jpg)

**Comment by MorrisJobke** [comment]
This bug tracker is only for actual bug. This does look more like a setup problem.

Please ask this in the forums: https://forum.owncloud.org

As a first step, try to reach the host within your browser -> if this doesn't work, then it's most likely a network problem below the application level.
