### ISSUE TITLE
Sometimes trying to reach ownCloud without last trailing slash causes »Forbidden« page to show up

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#21141]
Like this:
![capture du 2015-12-11 10-53-10](https://cloud.githubusercontent.com/assets/925062/11740953/3f862056-9ff6-11e5-8d4e-2d8e88791832.png)
Whereas when you add the trailing slash, it will properly redirect:
![capture du 2015-12-11 10-53-45](https://cloud.githubusercontent.com/assets/925062/11740952/3f6c3394-9ff6-11e5-9631-5e398141cc0c.png)

This happened automatically before and should be put in place again.

Sounds like it might be caused by https://github.com/owncloud/core/pull/20889 cc @LukasReschke

**Comment by LukasReschke** [comment]
If people would only review my PRs :speak_no_evil: 
https://github.com/owncloud/core/pulls/LukasReschke

**Comment by LukasReschke** [comment]
https://github.com/owncloud/core/pull/20878 + https://github.com/owncloud/core/pull/21020 it is
