### ISSUE TITLE
Mod_php7.c reference missing in .htaccess

### ISSUE THREAD

**Issue by Gummikavalier** [owncloud/core#21146]
Version ownCloud 8.2.1 with PHP7 and httpd/apache.

[owncloud root]/.htaccess does not have reference for mod_php7.c module.

Because of this the following parameters under ifModule are skipped:
> `<IfModule mod_php5.c>`
>  php_value upload_max_filesize 18G
>  php_value post_max_size 18G
>  php_value memory_limit 512M
>  php_value mbstring.func_overload 0
>  php_value always_populate_raw_post_data -1
>  php_value default_charset 'UTF-8'
>  php_value output_buffering 0
>  `<IfModule mod_env.c>`
>    SetEnv htaccessWorking true
>  `</IfModule>`
> `</IfModule>`

This can be verified under admin console where the upload limit value does not change according to php_value upload_max_filesize and php_value post_max_size values in .htaccess.
In addition to this, admin page complains about the lack of privileges and the value field is greyed out.

Replacing mod_php5.c string with mod_php7.c fixes the problem.

**Comment by MorrisJobke** [comment]
cc @LukasReschke

**Comment by cmonteroluque** [comment]
@PVince81 @LukasReschke fyi

**Comment by LukasReschke** [comment]
Patch is at https://github.com/owncloud/core/pull/23250

**Comment by Wikinaut** [comment]
I am interested in learning soon, whether this patch fixes the upload-size-problem also for self-compiled PHP 7 (like on my servers).
