### ISSUE TITLE
Data directory file storage improvement

### ISSUE THREAD

**Issue by arjanvs** [owncloud/core#21167]
According to me identical files need to be stored only once in the data directory. This will significantly improve the file storage capacity.

Current situation:
*User user1 upload a file FILE1.txt with one sentence: "The quick brown fox jumps over the lazy dog"
*User user2 already has a file type_face.txt with the same sentence: "The quick brown fox jumps over the lazy dog"

This results in storing two files:
*data/user1/files/FILE1.txt
*data/user2/files/type_face.txt
And of course a lot of labels and tags in the database.

It is obvious, that this has a negative impact for big files. But for small files it will have an impact on the block usage, because files are rounded up on the highest block number.

My suggestion:
*Determine at client side the checksum value of the to be uploaded file
*Transfer file and store it in a temporary directory
*Write in database the checksum and directory in the cloud
*Background check if file already exists. If file exists, delete temporary file. Else store the file under it checksum in the data directory. And make a reference link in the database.

After a file change:
*Fork the files

My checksum suggestion:
*Use two checksums to be sure that the file is unique.
*MD5
*SHA256
*Together with file size in bytes

Additional benefit:
*File integrity is checked at each file synchronization

Kind regards

Arjan

**Comment by karlitschek** [comment]
Thanks for the suggestion. Deduplication is the job of the filesystem. You will get exactly this functionallity if you use ZFS or BTRFS. This doesn't belong in the higher level of the stack like ownCloud.
I hope this makes sense.

**Comment by arjanvs** [comment]
Sorry, I have a different opinion. Because most ownCloud users cannot choose their file system. The file system is determined by the hosting authority.

Actually, I am opting for file deduplication. Because this will have positive impact on quota utilization at the hosting authority.
