### ISSUE TITLE
Owncloud v7.0.4.2 -> v8.2.1

### ISSUE THREAD

**Issue by busstech** [owncloud/core#21162]
Hi all,
After reading https://forum.owncloud.org/viewtopic.php?f=17&t=6638 I assumed that upgrading to v8.2.1 would be all good, but that was not the case. :-(

**Error:**
Exception: Updates between multiple major versions and downgrades are unsupported.

**status.php results:**
(
    [installed] => 1
    [maintenance] => 
    [version] => 8.2.1.4
    [versionstring] => 8.2.1
    [edition] => 
)

**What did I do to get here?**
1) disabled "/etc/yum/pluginconf.d/priorities.conf"
2) yum update owncloud
3) Logged into owncloud
4) Went to upgrade manager
5) followed instructions
6) Error

**Server details:**
CentOS Linux release 7.1.1503 (Core)

**Previous Version:**
7.0.4.2

**Question:**
Can anyone assist with the upgrade process? Documentation is lacking and as a result I cannot resolve this matter. I can also not log into owncloud since selecting upgrade manager.

**Comment by RealRancor** [comment]
See the duplicates like: https://github.com/owncloud/core/issues/20732

As this is not a bug you can close here and ask for more support at the forums

**Comment by busstech** [comment]
Thanks! 
Moving all comments there.
