### ISSUE TITLE
Admin manual missing from releases

### ISSUE THREAD

**Issue by carlaschroder** [owncloud/core#21164]
Hellos! Since at least 8.0 the Admin manual PDF is missing from oC releases. Both the Admin and User manuals should be included.

**Comment by karlitschek** [comment]
the latex build script gives me this output:

ing/index'
/root/releasescripts/temp-docucheckout/documentation/admin_manual/contents.rst: WARNING: toctree contains ref to nonexisting file 'enterprise_firewall/index'
/root/releasescripts/temp-docucheckout/documentation/admin_manual/configuration_server/config_sample_php_parameters.rst:: WARNING: unusable reference target found: ldap:show-remnants
IOError: [Errno 2] No such file or directory: '/root/releasescripts/temp-docucheckout/documentation/admin_manual/_build/latex/ownCloud_Server_Administration_Manual.tex'
Unable to open destination file for writing ('/root/releasescripts/temp-docucheckout/documentation/admin_manual/_build/latex/ownCloud_Server_Administration_Manual.tex').  Exiting.
make: *** [latexpdf] Error 1



@danimo any idea?

**Comment by carlaschroder** [comment]
I don't see those errors on my local builds, not sure what's going on.

**Comment by cmonteroluque** [comment]
@danimo can you please help?

**Comment by danimo** [comment]
```
Unable to open destination file for writing ('/root/releasescripts/temp-docucheckout/documentation/admin_manual/_build/latex/ownCloud_Server_Administration_Manual.tex').
```

Permission issue? Did someone build this as root by chance? Where is this being run? sign?

**Comment by karlitschek** [comment]
try yourself. /releasescripts/makedocu.php  make master admin_manual latexpdf

**Comment by danimo** [comment]
`zypper install texlive-morefloats` fixed it \o/

**Comment by karlitschek** [comment]
nice!!!! Thanks

**Comment by carlaschroder** [comment]
Hurrah, well done!  :smiley_cat:

**Comment by cmonteroluque** [comment]
Sorry @danimo. It worked with 8.2.2 RC1 but not with 8.1.5, 8.0.10, or 7.0.12. Re-opening. @karlitschek @carlaschroder

**Comment by danimo** [comment]
`make stable7 admin_manual latexpdf` succeeded, same for stable8 and stable81. What is the error you're getting?

**Comment by cmonteroluque** [comment]
fixed now

**Comment by carlaschroder** [comment]
Hurrah!
