### ISSUE TITLE
aborted occ encryption:migrate does not skip already migrated accounts

### ISSUE THREAD

**Issue by hostingnuggets** [owncloud/core#21165]
I am migrating from OC 8.0.9 to OC 8.1.4 and am at the stage of migrating the encryption keys by running "occ encryption:migrate". Unfortunately I had an out of memory error so it stopped in the middle of the process. Now I gave more RAM to this VPS a ran again "occ encryption:migrate" and noticed that it starts again from the beginning.

Shouldn't it simply skip the accounts which have already been migrated instead? 

Also I have to note here that it is terribly slow, I have an instance with >1000 users but only 80 GB data and it took already 4 hours when it crashed at the letter "p" of the accounts, so approximately at the middle...

**Comment by karlitschek** [comment]
@schiesbn is there a way to redume this? and can we check for memory before starting

**Comment by hostingnuggets** [comment]
by the way that VPS had 2 GB, I increased it to 4 GB and it managed to migrate all accounts but stil it took around 6 hours.

**Comment by PVince81** [comment]
From what I remember it last time I tried it did resume, so maybe there's a bug.

@schiesbn please have a look

**Comment by PVince81** [comment]
@schiesbn are you able to reproduce this ?

**Comment by schiesbn** [comment]
The migration are all rename operation so once a key was already renamed it can't be renamed a second time if you restart the process.

Of course you will still see some output that ownCloud looks at every user and system folder again to see if there are some keys to migrate or not. But in case the keys are already on the right location (e.g. from a previous run of the migration) nothing will happen and it should move on to the next user quickly.
