### ISSUE TITLE
Update to 8.1.4 Error Unable to generate a URL for the named route "contacts_index"

### ISSUE THREAD

**Issue by mahdsip** [owncloud/core#21166]
Updating owncloud server throught apt-get command i have received this message accessing to the server the fisrt time after update:

Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "contacts_index" as such route does not exist.

What can be causing this?

**Comment by mahdsip** [comment]
Repeting the process has resulted a successfull update!
Thanks

**Comment by RealRancor** [comment]
Also a dup of https://github.com/owncloud/core/issues/19145 (and a lot of more).
