### ISSUE TITLE
OCS v2.draft1: text errata

### ISSUE THREAD

**Issue by martin-rueegg** [owncloud/core#21174]
`remark:` this issue is regarding the regarding the [OCS v2 draft 1 specification](http://www.open-collaboration-services.org/ocs/ocs2-draft1.html). please refer to [OCS v2.draft1 comments overview](https://github.com/owncloud/core/issues/21172) for further information.
- [ ] in the section [Accessing shared files](http://www.open-collaboration-services.org/ocs/ocs2-draft1.html#accessing-shared-files), the `webdav` resource is called `access`. this is ambiguous.
- [ ] generally in the documentation there is the use of `OCS success message`. this should be changed to read `OCS response message`.
- [ ] [Output format / OCS Format](http://www.open-collaboration-services.org/ocs/ocs2-draft1.html#output-format--ocs-format): the term 'customer' instead of 'consumer' is used.
- [ ] [Get all values of store](http://www.open-collaboration-services.org/ocs/ocs2-draft1.html#get-all-values-of-store): URL structure must not include `/{key}`, while it should be added to the "Get value of a key in a store" section instead.

**Comment by LukasReschke** [comment]
Subscribing myself here.

**Comment by DeepDiver1975** [comment]
To some extend the API specification is continued here: https://github.com/GEANT/OCM-API
