### ISSUE TITLE
OCS v2.draft1: provider service list

### ISSUE THREAD

**Issue by martin-rueegg** [owncloud/core#21180]
`remark:` this issue is regarding the regarding the [OCS v2 draft 1 specification](http://www.open-collaboration-services.org/ocs/ocs2-draft1.html). please refer to [OCS v2.draft1 comments overview](https://github.com/owncloud/core/issues/21172) for further information.
# the provider service list (PSL)
## versioning

the OCS specification [states](http://www.open-collaboration-services.org/ocs/ocs2-draft1.html#versioning) that "Providers MAY remove the endpoint but SHALL NOT make an existing endpoint incompatible," yet there is no foreseen way, how to achieve this for the PSL itself, as the location is "hard-coded" to be at `/ocs-provider/` of the root of the instance and the `version` is only mentioned within the file, but not as a container, which would allow multiple versions within one file.
- one solution to this "problem" is by implementing an alternate service discovery as described in #21177.
- a second solution would be by encapsulating all information within different version objects, so that multiple representation of the information can co-exist in one file/response.
- a third approach would be to announce the "versioned PSL" within the existing "root PSL v1". this could be implemented maintaining backwards compatibility (and as such adhering to the already-in-use spec) and complement the alternate service discovery. this approach shall be laid out hereafter.
### new top element `location`

a newly introduced element `location` could announce where the respective version of a PSL can be found. this would only require, that the current draft (and future specs) needs to be updated in the sense, that unknown elements MUST be silently ignored.

the `services` element is only given, if version 2-style information about the services is actually still provided.

so the extended version 2 would look something like the following:

```
{
    "version": 2,
    "location": {
        // version 1 is obviously deprecated
        // version 2 is this file, so only versions as v3 can be announced here

        // PSL relative to the location of this file
        3: "v3",
            //-> .../ocs-provider/v3

        // PSL relative to the root of the webserver
        4: "/different/path/to/PSL/v4",

        // PSL on the same host, but different port
        5: "4343:/different/path/to/PSL/v5",

        // PSL on an entirely different host
        6: "https://ocs.mycloud.com[:port]/PSL/v6",
    },
    "services": {
        (...)
    }
}
```
## format selection

currently the format (JSON vs. XML) is selected by using the GET query string `format={format}`. the `format` variable is not mandatory and no default format is specified. either of this should be done in the specification.

a more HTTP-like way of format selection would be the use of the http `Accept` header, which MUST be either
- `application/xml`
- `application/json`
  a missing header would lead to select the defined default format (e.g. JSON). any other value would lead to a `400/4xxx` (see #21175) error reply, also using the default format.
## webdav or XRD style PSL

has there been a discussion of whether to use an already established resource description format? as the consumer needs to be webdav capable once it accesses the resource, the webdav `PROPFIND` method could basically be used to get information about the available services.

an other way to locate services is [XRD](http://docs.oasis-open.org/xri/xrd/v1.0/xrd-1.0.html) which is used for [Web Host Metadata](http://tools.ietf.org/html/rfc6415#section-3) in [`/.well-known/host-meta`](http://tools.ietf.org/html/rfc6415#section-6.1). a similar approach to `host-meta` and `host-meta.json` could be chosen, which would make the locator even compatible with [RFC 6415](http://tools.ietf.org/html/rfc6415) and might be included in [`/.well-known/host-meta`].
## enhanced service information

it might well be possible, that future service (implementations) need to advert their capabilities, similar to reply of the [EHLO](https://tools.ietf.org/html/rfc1869#section-4) command in ESMTP. for example, the `FEDERATED_SHARING` can - in the OwnCloud implementation - offer shares and/**or** accept shares. if it only accept shares, the `webdav` url is of no need and does not necessarily be advertised. or the service might implement something like "live-updates" which would mean, that the sharing site will automatically send updates to the receiving site if a file on the share has been created, modified, or deleted. such further capabilities might also be provided by add-ons or extensions to this specification. therefore it would be wise to implement some sort of capability advertising facility.

the following suggestion is displayed in JSON but could be implemented in any defined format, of course:
#### service description variant a: `version` as identifier

```
{
    "version": 3,
    "services": {
        "FEDERATED_SHARING": {
            "capabilities": {
                "share": {
                    // share implementation version
                    2, {
                        "endpoint": "/ocs/v2.php/cloud/shares",
                        "spec": "http://www.open-collaboration-services.org/ocs/ocs2-draft1.html#federated_sharing"
                    }
                    3, {
                        "endpoint": "/ocs/v3.php/cloud/shares",
                        "spec": "http://www.open-collaboration-services.org/ocs/ocs3.html#federated_sharing"
                        "extensions": {
                            "mailmap": {
                                "version": 1,
                                "spec": "http://www.open-collaboration-services.org/ocs/mailmap1.html"
                            },
                            "addon-x": {
                                "spec": "http://www.example.org/addon-x/3.html"
                            }
                        }
                    }
                },
                "webdav": {
                    1, {
                        "endpoint": "/public.php/webdav/",
                        "spec": "http://tools.ietf.org/html/rfc4918"
                    }
                },
                "mailmap": {
                    1, {
                        "endpoint": "/ocs/v3.php/cloud/mailmap",
                        "spec": "http://www.open-collaboration-services.org/ocs/ocs3.html#federated_sharing-mailmap"
                    }
                }
            }
        }
    }
}
```
#### service description variant b: `version` as property

```
{
    "version": 3,
    "services": {
        "FEDERATED_SHARING": {
            "capabilities": {
                "share": {[
                    // share implementation version
                    {
                        "version": 2, // mandatory if more than one version is provided
                        "endpoint": "/ocs/v2.php/cloud/shares",
                        "spec": "http://www.open-collaboration-services.org/ocs/ocs2-draft1.html#federated_sharing"
                    },
                    {
                        "version": 3, // mandatory if more than one version is provided
                        "endpoint": "/ocs/v3.php/cloud/shares",
                        "spec": "http://www.open-collaboration-services.org/ocs/ocs3.html#federated_sharing"
                        "extensions": {
                            "mailmap": {
                                "version": 1,
                                "spec": "http://www.open-collaboration-services.org/ocs/mailmap1.html"
                            },
                            "addon-x": {
                                "spec": "http://www.example.org/addon-x/3.html"
                            }
                        }
                    }
                ]},
                "webdav": {[
                    {
                        // "version" is left out, as only one array element is given
                        "endpoint": "/public.php/webdav/",
                        "spec": "http://tools.ietf.org/html/rfc4918"
                    }
                ]}
            }
        }
    }
}
```

**Comment by LukasReschke** [comment]
Subscribing myself here.

**Comment by DeepDiver1975** [comment]
To some extend the API specification is continued here: https://github.com/GEANT/OCM-API
