### ISSUE TITLE
Shared with others show create permissions for files

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#21187]
![foo](https://cloud.githubusercontent.com/assets/45821/11781132/dd21473c-a267-11e5-82b6-5c930bd100ff.png)

When you share a file and move to the 'shared with others' page and then click on the share icon you can edit the share permissions as expected.

However, you can now again set create permissions for files (Which do not mean anything).

CC: @PVince81

**Comment by PVince81** [comment]
even after your fix ?!

**Comment by rullzer** [comment]
yes, because this page does not get the info from webdav

**Comment by rullzer** [comment]
PR is on the way!

**Comment by rullzer** [comment]
PR in #21189
