### ISSUE TITLE
Precompile Assets Cache

### ISSUE THREAD

**Issue by stonerl** [owncloud/core#21188]
Since I read about WD teaming up with ownCloud using a RasPi, one thought came into my mind. When enabling the asset-pipeline ownCloud's WebUI does significantly speed up and gets much snappier. The problem though, generating these assets can take a significant amount of time, especially on a Pi.

Would it be somehow possible to precompile assets during an instance update or via an ```occ``` command? Since I don't know ownCloud's internals, this might not be feasible. What do you think?

**Comment by PVince81** [comment]
@DeepDiver1975 @icewind1991 what do you think ? Maybe an occ command ?

**Comment by icewind1991** [comment]
The problem would be knowing which assets to generate, unless we want to manually define a list we would need to do something like iterating over all registered routes and check which assets are loaded for each

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 @icewind1991 what do you think ? Maybe an occ command ?

It is not really possible - the set of compiled assets is different for each page which is loaded.
We would need to generated them for a bunch of urls - which is a high configuration effort.

Furthermore the assets have to be *potentially* regenerated after each app being enabled/disabled and so on.

The approach will be highly error prone ....

**Comment by stonerl** [comment]
Shall I close this issue or do you want it to stay open?
