### ISSUE TITLE
Mounting an external storage for a specific user shows error for other users

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#21183]
cc @Xenopathic @icewind1991 

![bildschirmfoto 2015-12-14 um 11 53 33](https://cloud.githubusercontent.com/assets/245432/11779098/6101f15a-a259-11e5-9b68-9daa15c5921f.png)

Login as user `abc` shows me following (after clicking on the red row)

<img width="1083" alt="bildschirmfoto 2015-12-14 um 11 53 51" src="https://cloud.githubusercontent.com/assets/245432/11779116/7315e86a-a259-11e5-93dd-cb30089ddd97.png">

**Comment by MorrisJobke** [comment]
Noticed with 96b2838

**Comment by Xenopathic** [comment]
cc @jmaciasportela

**Comment by jmaciasportela** [comment]
@MorrisJobke  Why If the mount is only available for mjob is in the file list of abc user?

**Comment by MorrisJobke** [comment]
> @MorrisJobke Why If the mount is only available for mjob is in the file list of abc user?

That is the question ;)

**Comment by icewind1991** [comment]
Can't reproduce, can you check the content of `oc_mount_applicable`

**Comment by PVince81** [comment]
@MorrisJobke is this still happening ? Similar bugs have been fixed recently.
If yes, please post the contents of "oc_external_applicable".

**Comment by MorrisJobke** [comment]
I can't reproduce anymore.
