### ISSUE TITLE
How to configure multiple Domains for External Storage SMB/CIFS?

### ISSUE THREAD

**Issue by gig13** [owncloud/core#21206]
### Expected behaviour

Configure Users for External Storage using multiple Domains
### Actual behaviour

Only one Domain is listed in the External Storage configuration section
### Server configuration

**Operating system**: RHEL

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.5

**ownCloud version:** 8.2.1

**Updated from an older ownCloud or fresh install:** Updated

**Are you using external storage, if yes which one:** SMB/CIFS

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** LDAP

@MorrisJobke

**Comment by Xenopathic** [comment]
What are the steps to reproduce? I just configured two SMB storages with different domains and both are saved (and later retrieved) correctly. Using ownCloud master as of now

**Comment by gig13** [comment]
@Xenopathic 
Can we have one storage with multiple domains? We have 5 domains to setup, which would mean 5 configs...

**Comment by Xenopathic** [comment]
@gig13 Could you elaborate on what you mean by multiple domains? Do you mean one external storage should be accessible to multiple users, which are in different domains (via LDAP)?

**Comment by gig13** [comment]
@Xenopathic 
We have users over about 5 different domains with multiple users over domains per share. I was hoping there was a way to query ldap for the users domain and use that for the authentication.

**Comment by PVince81** [comment]
So if I understand well, having an "auto-detect user domain" way, that depends on which user is currently accessing the storage ? Potentially similar to the `$user` variable ?

**Comment by PVince81** [comment]
backlog for now until the requirement is clarified

**Comment by MorrisJobke** [comment]
> backlog for now until the requirement is clarified

cc @MTRichards for this feature request

**Comment by Xenopathic** [comment]
@gig13 The 'domain' parameter is optional, you might want to try configuring the storage without specifying the domain.

**Comment by MTRichards** [comment]
@gig13 if you can try the @Xenopathic option, great.

**Comment by gig13** [comment]
@Xenopathic 

The user originally tried without the domain filled out and it wouldn't work. A user can only be a member of a single domain in Active Directory, and they have many users over 5 different domains. For example . "rhillary" is under "campus" and "rhadmin" is under "sde" but both users require access to the same external storage over CIFS. I'm sure there is an LDAP attribute which contains the domain information. 

In LDAP there is an attribute of the user called "userPrincipalName" the portion after the "@" is the domain. Maybe you could split this off and store it in the same place as you already have with user credentials (cookies or whatever). When a user logs into owncloud with AD/LDAP integration it now stores user/pass/domain. When they access external storage using "session credentials" It can pass each of these values to the cifs share

My example below is 2 different domains:
<img width="998" alt="ldap_domain_config" src="https://cloud.githubusercontent.com/assets/4803385/11848452/759d081e-a3f0-11e5-9d04-e2308d38c688.png">

**Comment by bboule** [comment]
@gig13 Lets discuss when you are back

**Comment by gig13** [comment]
@bboule Any updates after our discussion?

**Comment by gig13** [comment]
FR - backlog
