### ISSUE TITLE
SMB clear local stat cache on upload/fopen/write

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#21205]
@icewind1991 please have a look, I found that there is no mechanism to clear `$this->statCache` for the current file when doing a fopen.

Maybe need the close wrapper ?

CC @jmaciasportela

**Comment by PVince81** [comment]
https://github.com/owncloud/core/blob/v8.2.1/apps/files_external/lib/smb.php#L190 no stat cache is cleared here

**Comment by icewind1991** [comment]
Fix is here: https://github.com/owncloud/core/pull/21216
