### ISSUE TITLE
Unknown error browsing external Webdav folders, containing files with special characters.

### ISSUE THREAD

**Issue by dinkonin** [owncloud/core#21213]
ownCloud 8.2.1 (stable). 
Centos 7

When browsing external webdav mounted storage , if a directory contains a file with "+" in its name for example "test+test.txt". Owncloud shows "Unknown error" and does not open the folder . If the file is renamed there's no problem.

This is shown in the log:Exception: {"Exception":"Sabre\HTTP\ClientHttpException","Message":"Not Found","Code":404,"Trace":"#0 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Client.php(233): Sabre\HTTP\Client->send(Object(Sabre\HTTP\Request))\n#1 \/var\/www\/html\/owncloud\/lib\/private\/files\/storage\/dav.php(263):

**Comment by PVince81** [comment]
@dinkonin what kind of Webdav server are you connecting to ? Is it another ownCloud instance of maybe an Apache Webdav (mod_dav) module ?

**Comment by dinkonin** [comment]
@PVince81 It's Apache WebDev running on a NetGear ReadyNas 102, when i mount it or open it in a browser there's no problem.

**Comment by PVince81** [comment]
Okay, thanks. Maybe some extra encoding needs to be done for "+" signs. Some servers automatically convert "+" to spaces...

**Comment by PVince81** [comment]
If someone can provide a docker instance where this is reproducible I could have a look.

**Comment by PVince81** [comment]
Please try with 10.0.4 and reopen if the problem persists.
