### ISSUE TITLE
SMB storage must throw StorageNotAvailable in specific cases

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#21219]
@icewind1991 @jmaciasportela make the SMB storage throw StorageNotAvailableException in case of timeouts or when the remote server does not identify as a SMB server, or the credentials have changed.

Do not throw it for other exceptions like ForbiddenException.

**Comment by PVince81** [comment]
Not sure if handled by your recent PRs ? @icewind1991

**Comment by icewind1991** [comment]
No

**Comment by PVince81** [comment]
and maybe have a special exception for timeouts as well, as discussed with @jvillafanez recently

**Comment by PVince81** [comment]
Seems we already throw this in 10.0.4 for some code paths, closing.
