### ISSUE TITLE
higher load after upgrade (2.92x)

### ISSUE THREAD

**Issue by colttt** [owncloud/core#21224]
Hello,

after upgrade from 8.0.2 to 8.2.1 we have i higher load, i know this is not a hugh higher load, but we have not a big enviroment (~200 active users).
When i take a look on the server, i see the higher load comes from mysql, did you change something on the database which explain the higher load?

Take a look at the screenshots and on the load average
![after_upgrade](https://cloud.githubusercontent.com/assets/10084871/11837712/f353b0ea-a3e2-11e5-9eab-072c5ddf8c1f.png)
![before_upgrade](https://cloud.githubusercontent.com/assets/10084871/11837711/f3500b20-a3e2-11e5-8472-4b1f080f9410.png)

**Comment by rullzer** [comment]
This could very well be the file locking which is now by default in 8.2.
I suggest setting up redis.

**Comment by MorrisJobke** [comment]
See https://doc.owncloud.org/server/8.2/admin_manual/configuration_files/files_locking_transactional.html for setting up redis for file locking. 

Closing this here. Feel free to reopen if this issue still exists after you switched to redis.
