### ISSUE TITLE
version 8.2.1 encryption:enable-master-key clients work, web does not

### ISSUE THREAD

**Issue by k6run** [owncloud/core#21221]
### Steps to reproduce
1. Web interface: Enable server-side encryption
2. cli:  occ encryption:enable-master-key
3.

### Expected behaviour
encryption on a single sign on oc system

### Actual behaviour
encryption works with the clients, they upload files that get encrypted.
I can look at the files on the storage device and they are indeed encrypted.
The clients can also download and use the files.
However, using any web browser, the files are visible, but not accessible.
Refuses to download the files, "files are bad".
Also, banner indicates "log out and log back in"

### Server configuration
Ubuntu 14.04

**Web server:**
Apache 2

**Database:**
Mysql 5.5.46

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
8.2.1

**Updated from an older ownCloud or fresh install:**
fresh install

**List of activated apps:**
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
Enabled:
  - activity: 2.1.3
  - announcementcenter: 1.0.0
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_w2g: 0.8.2.2
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - updater: 0.6
  - user_cas: 1.1
  - user_ldap: 0.7.0

**The content of config/config.php:**

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or

Insert your config.php content here
(Without the database password, passwordsalt and secret)

{
    "system": {
        "instanceid": "ocioje8jtzyr",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "rcloud-1.own.private",
            "rcloud.usr.edu"
        ],
        "datadirectory": "\/owncloud-data",
        "overwrite.cli.url": "http:\/\/rcloud-1.own.private\/owncloud",
        "filesystem_check_changes": 1,
        "dbtype": "mysql",
        "version": "8.2.1.4",
        "dbname": "owncloud",
        "dbhost": "rclouddb-1.own.private",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "PST",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "logfile": "\/owncloud-data\/owncloud.log",
        "loglevel": 1,
        "mail_from_address": "noreply",
        "mail_smtpmode": "php",
        "mail_domain": "own.private"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
nfs mounted

**Are you using encryption:** yes/no
trying to

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
+-------------------------------+---------------------------------------+
| Configuration                 |                                       |
+-------------------------------+---------------------------------------+
| hasMemberOfFilterSupport      | 0                                     |
| hasPagedResultSupport         |                                       |
| homeFolderNamingRule          | attr:uid                              |
| lastJpegPhotoLookup           | 0                                     |
| ldapAgentName                 | cn=owncloud,ou=Specials,dc=usr,dc=edu |
| ldapAgentPassword             | ***                                   |
| ldapAttributesForGroupSearch  |                                       |
| ldapAttributesForUserSearch   |                                       |
| ldapBackupHost                | ldaps://ldap5-mgmt.cis.usr.edu        |
| ldapBackupPort                | 636                                   |
| ldapBase                      | ou=persons,dc=usr,dc=edu              |
| ldapBaseGroups                | ou=Ucrcid,ou=AutoGroups,dc=usr,dc=edu |
| ldapBaseUsers                 | ou=persons,dc=usr,dc=edu              |
| ldapCacheTTL                  | 60                                    |
| ldapConfigurationActive       | 1                                     |
| ldapEmailAttribute            | mail                                  |
| ldapExperiencedAdmin          | 1                                     |
| ldapExpertUUIDGroupAttr       | cn                                    |
| ldapExpertUUIDUserAttr        |                                       |
| ldapExpertUsernameAttr        | uid                                   |
| ldapGroupDisplayName          | cn                                    |
| ldapGroupFilter               | (cn=*)                                |
| ldapGroupFilterGroups         |                                       |
| ldapGroupFilterMode           | 1                                     |
| ldapGroupFilterObjectclass    |                                       |
| ldapGroupMemberAssocAttr      | member                                |
| ldapHost                      | ldaps://ldap2-mgmt.cis.usr.edu        |
| ldapIgnoreNamingRules         |                                       |
| ldapLoginFilter               | (&(usrService=owncloud)(uid=%uid))    |
| ldapLoginFilterAttributes     |                                       |
| ldapLoginFilterEmail          | 0                                     |
| ldapLoginFilterMode           | 1                                     |
| ldapLoginFilterUsername       | 1                                     |
| ldapNestedGroups              | 0                                     |
| ldapOverrideMainServer        |                                       |
| ldapPagingSize                | 0                                     |
| ldapPort                      | 636                                   |
| ldapQuotaAttribute            | ownCloudQuota                         |
| ldapQuotaDefault              | 3 TB                                  |
| ldapTLS                       |                                       |
| ldapUserDisplayName           | displayname                           |
| ldapUserFilter                | (usrService=owncloud)                 |
| ldapUserFilterGroups          |                                       |
| ldapUserFilterMode            | 1                                     |
| ldapUserFilterObjectclass     |                                       |
| ldapUuidGroupAttribute        | auto                                  |
| ldapUuidUserAttribute         | auto                                  |
| turnOffCertCheck              | 1                                     |
| useMemberOfToDetectMembership | 1                                     |
+-------------------------------+---------------------------------------+

### Client configuration
**Browser:**
chrome, safari, firefox

**Operating system:**
Linux, Mac

**Comment by PVince81** [comment]
Thank you for the detailed report.

@schiesbn can you have a look ?

**Comment by PVince81** [comment]
@k6run I guess you already tried to log out then log back in in the web UI, and then the files could still not be read ? Can you confirm ?

**Comment by k6run** [comment]
Yes, at least as much as one can log out and log back in with SSO.

**Comment by PVince81** [comment]
@k6run hmmm... so the main problem is more that people cannot easily log out from SSO in cases where encryption requires re-login ? There are many cases where the encryption app requires this.

**Comment by k6run** [comment]
SSO means they never actually log in or out of a service, like OC. They
authenticate against another service and are permitted access. That is what
the master key is supposed to provide, the ability to use SSO with
encryption, but though it works with OC clients, it is not working with the
web interface.

**Comment by butonic** [comment]
Reproduced here. It happens when user sessions are active when encryption is enabled. On the client side you can force a new session by deleting the oc cookies. on the server side you can achieve the same thing by invalidating all php sessions. Depending on your configuration that may mean deleting php session files, clearing memcached or redis.

@LukasReschke is there a way to force logout all users by now?

**Comment by PVince81** [comment]
Not that I'm aware of, at least no mechanism that doesn't involve deleting session files.

@LukasReschke ?

**Comment by schiesbn** [comment]
As described correctly by @butonic and @PVince81 the only way to force a re-login is to invalidate the session. This is a feature planed for 9.1: https://github.com/owncloud/core/issues/23558

Once this is implemented we can invalidate the session after encryption was enabled... But I don't think this is something we can backport. So I would say this is a 9.1.X milestone. cc @cmonteroluque

**Comment by PVince81** [comment]
@k6run please try again with 8.2.6 or 9.0.3, this fix https://github.com/owncloud/core/issues/24182 related to SSO and master key made it in.
