### ISSUE TITLE
Feature Request: Enable Federated Cloud Sharing with Shibboleth

### ISSUE THREAD

**Issue by rontrompert** [owncloud/core#21227]
Unfortunately it is not possible at the moment to use federated cloud sharing together with Shibboleth. Can this be fixed?

**Comment by karlitschek** [comment]
@schiesbn @DeepDiver1975 any idea?

**Comment by DeepDiver1975** [comment]
From my understanding this should work as soon as the ocs api routes used for federated sharing are NOT protected by the apache shibboleth authentication.

This requires some testing - calling @owncloud/qa

**Comment by PVince81** [comment]
@rontrompert Please use the issue template https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

Any errors in logs ? In what sharing scenario are you seeing an error ? (share with link + add to owncloud or sharing over share dialog)

**Comment by rontrompert** [comment]
@PVince81 According to the 8.2 release notes this is not possible. That's why this is not a bug but a feature request.

**Comment by PVince81** [comment]
You're right, tagging as enhancement

CC @MTRichards @cmonteroluque

**Comment by PVince81** [comment]
CC @karlitschek

**Comment by davitol** [comment]
Trying to share a file with a shib user:
(oC8.2.2 shib autoprov -> oC 8.1.5 'standard user') :X:

oC 8.2.2. owncloud.log

```
{"reqId":"b2p6mwHHTRetuL1TsZzb","remoteAddr":"172.17.0.1","app":"PHP","message":"Undefined index: HTTP_USER_AGENT at \/opt\/owncloud\/lib\/private\/appframework\/http\/request.php#678","level":3,"time":"2015-12-21T08:23:15+00:00"}
{"reqId":"1ex20r5J20oVknYlme80","remoteAddr":"172.17.0.1","app":"PHP","message":"Undefined index: HTTP_USER_AGENT at \/opt\/owncloud\/lib\/private\/appframework\/http\/request.php#678","level":3,"time":"2015-12-21T08:23:15+00:00"}





oC 8.1.5 owncloud.log
```
{"reqId":"Y6PvTwxXqYLmSGEl62Ca","remoteAddr":"82.159.139.58","app":"PHP","message":"Argument 3 passed to OC\\Hooks\\BasicEmitter::listen() must be callable, array given, called in \/opt\/owncloud\/apps\/files\/ajax\/scan.php on line 50 and defined at \/opt\/owncloud\/lib\/private\/hooks\/emittertrait.php#36","level":3,"time":"2015-12-21T08:23:13+00:00"}
{"reqId":"i0af\/MKRXRgDW6Rez1Hs","remoteAddr":"82.159.139.58","app":"core","message":"Exception while scanning storage \"shared::dfbd4943c546c863437858ca1e1e0e2f\": Sabre\\HTTP\\ClientException: Failed to connect to idp.testshib.org port 54216: No route to host","level":3,"time":"2015-12-21T08:23:14+00:00"}


********
(oC8.2.2 shib autoprov -> oC 8.1.5 'shib autov') :X:

oC 8.2.2 owncloud.log -> No logs

oC 8.1.5 owncloud.log 

```
{"reqId":"8Lk+g02Nr7YTenJIIVAs","remoteAddr":"82.159.139.58","app":"PHP","message":"Argument 3 passed to OC\\Hooks\\BasicEmitter::listen() must be callable, array given, called in \/opt\/owncloud\/apps\/files\/ajax\/scan.php on line 50 and defined at \/opt\/owncloud\/lib\/private\/hooks\/emittertrait.php#36","level":3,"time":"2015-12-21T08:47:04+00:00"}
{"reqId":"9kB0xTGDF7LokTq5+DI0","remoteAddr":"82.159.139.58","app":"core","message":"Exception while scanning storage \"shared::09dce0f31d225777447c28c71b4ede54\": Sabre\\HTTP\\ClientException: Failed to connect to idp.testshib.org port 54216: No route to host","level":3,"time":"2015-12-21T08:47:08+00:00"}

Trying to share the file via link, the same log is created

**Comment by PVince81** [comment]
Ah, interesting... whenever it tries to connect to the remote shared storage, it actually lands on the IDP instead of ownCloud.

Do public link shares work ?
Maybe something in the SSO config needs to allow connecting to "public.php/webdav" without redirecting to the IDP ?

**Comment by PVince81** [comment]
not sure if this is something to be configured on the SSO config side or the shibboleth app ?
@DeepDiver1975

**Comment by SURFsara-e-infra** [comment]
Hi, any news on this

**Comment by DeepDiver1975** [comment]
> not sure if this is something to be configured on the SSO config side or the shibboleth app ?

this should be solvable by changing the config on apache to not redirect the webdav and ocs api endpoints



> Hi, any news on this

No priority has be placed on this

**Comment by MTRichards** [comment]
@SURFsara-e-infra This is not currently planned for oC 9 as oC 9 roadmap and development was slated in November last year. For us to consider it for oC 9.1 - the next release (Aug release) please submit a ticket to support so it flows through properly and we won't lose it.

**Comment by cdamken** [comment]
In ownCloud 10 Federation and Shibboleth works, please follow the documentation.
