### ISSUE TITLE
[Sharing] Resharing a file, the name of the first user should not be shown in the searchbox

### ISSUE THREAD

**Issue by davitol** [owncloud/core#21225]
### Steps to reproduce

1. Share a file from user1 to user2
2. Log in with user2 and try to share a file with user1

### Expected behaviour

user1 should not be shown as a possible option in the searchbox of sharing

### Actual behaviour

user1 appears in the search result

Note: If you try to share the file, an error message appears (right behaviour)

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 8.2.2 RC1 (testing)

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

**Comment by PVince81** [comment]
@rullzer we should exclude the user in the JS code

**Comment by rullzer** [comment]
Will be fixed with https://github.com/owncloud/core/pull/21349

**Comment by davitol** [comment]
> Will be fixed with #21349

@rullzer Tested and yes it is fixed with PR #21349 :+1:
