### ISSUE TITLE
Unexpected Behaviour with Function OC\Group\getVerifiedUsers in Relation to Application OCA\user_ldap

### ISSUE THREAD

**Issue by alexweirig** [owncloud/core#21223]
See attached PDF for the calling stack ...

The last two function calls execute a query against the database looking for a user in the “ldap_user_mapping” table.  Sometimes a valid user is not found (not present in the table for some unknown reason) and a return result of “false” or “null” is bubbled up the above call stack and the existing user is not added to the array to be returned by getVerifiedUsers.

Calling Context

The getVerifiedUsers function is called many times during the rendering of users and their groups on the OwnCloud Admin→Users page.  When a user clicks on a “dynamic” group in the left column an ldap search is performed to retrieve all the members of the group.  The function getVerifiedUsers function is called and loops through all the provided users.  Only users that are “successfully verified” by getVerifiedUsers are displayed on the page. 

Regards,

Alex
[OwnCloud Code Issue - getVerifiedUsers.pdf](https://github.com/owncloud/core/files/63688/OwnCloud.Code.Issue.-.getVerifiedUsers.pdf)

**Comment by LukasReschke** [comment]
cc @owncloud/ldap

**Comment by PVince81** [comment]
Report is for OC 8.2.1 (from the PDF)

**Comment by alexweirig** [comment]
Yes, I confirm

**Comment by PVince81** [comment]
@blizzz any idea ? Please adjust severity

**Comment by blizzz** [comment]
i put it preliminary to high. Need to further investigate.

**Comment by PVince81** [comment]
Any update ?

**Comment by blizzz** [comment]
No.

**Comment by PVince81** [comment]
@alexweirig can you try again with 8.2.2 ? There were many LDAP fixed there

**Comment by alexweirig** [comment]
@PVince81 I currently only have a 8.2.1 patched to support the dynamic ldap groups.

I'd have to apply the changes from 8.2.1 to 8.2.2 in order to be able to complete the tests.

**Comment by alexweirig** [comment]
@PVince81 I'm looking at 9.0RC1 and found that the dynamic group members are no longer shown. When I click on a dynamic LDAP group, the member list is empty.

**Comment by PVince81** [comment]
@blizzz any idea ?

**Comment by alexweirig** [comment]
@blizzz @PVince81 I had a look at the code ... if I understand correctly, it seems that group members are loaded in the background (multiple threads?).
I wonder if there is a problem to merge the "static" members and the "dynamic" members of a group. All groups having static members show up correctly. Only the groups with dynamic membership are shown empty.

**Comment by blizzz** [comment]
> @blizzz @PVince81 I had a look at the code ... if I understand correctly, it seems that group members are loaded in the background (multiple threads?).

What you probably refer to is the background job. But this is only done in order to throw hooks announcing the join or a removal of a user to a group.

In normal operation the members are retrieved on-demand (and only a cache is in between, by default living 10minutes).

Also, there were no code changes in group_ldap.php since merging your feature.

**Comment by alexweirig** [comment]
@blizzz @PVince81 
I'm trying to debug what's going on and it seems the group members are correctly found/retrieved but then they are not displayed in the list.
I added logging code to the method and this is what happens when I click on a dynamic group ("cn=ens-president").
As you can see it finds all the members "$$aw_dy_group_url found memberuid=" but then there are lots of other log entry from user_ldap...

[owncloud.log.zip](https://github.com/owncloud/core/files/158546/owncloud.log.zip)

**Comment by blizzz** [comment]
@alexweirig do you know why the cn is read for each user? 

> {"reqId":"J6Ck2aXeUlAzKVaRFudX","remoteAddr":"10.81.1.19","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => $REPLACEDDN\n)\n attr Array\n(\n    [0] => cn\n)\n limit 500 offset 0","level":0,"time":"2016-03-04T10:56:36+00:00","method":"GET","url":"\/index.php\/settings\/users\/users?offset=0&limit=250&gid=ens-president&pattern="}

But the problem might be here:

> {"reqId":"J6Ck2aXeUlAzKVaRFudX","remoteAddr":"10.81.1.19","app":"PHP","message":"Array to string conversion at \/var\/www\/html\/owncloud\/apps\/user_ldap\/group_ldap.php#471","level":3,"time":"2016-03-04T10:56:36+00:00","method":"GET","url":"\/index.php\/settings\/users\/users?offset=0&limit=250&gid=ens-president&pattern="}

Which is strange, I don't see which variable would be an array instead of string. Could you debug this? I don't have such messages appear in my setup. 

However  this is why 

> {"reqId":"J6Ck2aXeUlAzKVaRFudX","remoteAddr":"10.81.1.19","app":"user_ldap","message":"$$aw_getUserGroups2 Array","level":0,"time":"2016-03-04T10:56:36+00:00","method":"GET","url":"\/index.php\/settings\/users\/users?offset=0&limit=250&gid=ens-president&pattern="}

happens. It should not be "getUserGroups2 Array", instead Array should be something meaningful. This is what results from above.

**Comment by alexweirig** [comment]
@blizzz 
The array conversion is probably a consequence of my "profound" PHP knowledge ;-)
I had added this in getUserGroups:
\OCP\Util::writeLog('user_ldap', '$$aw_getUserGroups2 '. $dynamicGroup, \OCP\Util::DEBUG);
I now removed that line of code but that doesn't fix the problem. The users list is still empty.

**Comment by alexweirig** [comment]
@blizzz I suppose once the code has retrieved the users that are part of the dynamic group, it has to read each user to figure out what other groups that user is member of to display that in the user list.
I guess that is what is causing the re-reading of the users cn?
But this works fine in our patched 8.2.1 code.
Also, I notice a huge performance decrease between the 8.2.1 and 9.0.0rc1 when the users list is shown... It takes about 7 seconds to see the first list of users in 8.2.1 while it takes about 45 !!! seconds to display the same first list in 9.0.0rc1

**Comment by alexweirig** [comment]
@blizz certainly the VMs are not the same. Production is running on ESXi 6 while the test is a VM downloaded from techandme.se and is running on my MacPro but that's still a huge difference.

**Comment by blizzz** [comment]
@alexweirig About the performance, do you have caching enabled on your test instance? 

In getUserGroups() the $groups array is not overwritten.

However, that should not be the relevant method here either. usersInGroup() is what needs to be debugged. 

First, is the $groupDN retrieved properly in line 621? :

```php
$groupDN = $this->access->groupname2dn($gid);
```

Second and if so, are the members pulled correctly in line 629? : 

```php
$members = array_keys($this->_groupMembers($groupDN));
```

**Comment by alexweirig** [comment]
@blizzz 
this looks good to me:
1) groupDN is correctly retrieved:
{"reqId":"bGfPOGxNbRkBOpXOx1gp","remoteAddr":"10.81.1.19","app":"$$aw$$","message":"usersInGroup - groupDN cn=ens-president,cn=groups,cn=accounts,dc=technolink,dc=lu","level":0,"time":"2016-03-04T13:46:24+00:00","method":"GET","url":"\/index.php\/settings\/users\/users?offset=0&limit=250&gid=ens-president&pattern="}

2) members are correctly pulled:
{"reqId":"bGfPOGxNbRkBOpXOx1gp","remoteAddr":"10.81.1.19","app":"$$aw$$","message":"usersInGroup - members is OK","level":0,"time":"2016-03-04T13:46:24+00:00","method":"GET","url":"\/index.php\/settings\/users\/users?offset=0&limit=250&gid=ens-president&pattern="}
{"reqId":"bGfPOGxNbRkBOpXOx1gp","remoteAddr":"10.81.1.19","app":"$$aw$$","message":"usersInGroup - members is uid=annagrevink,cn=users,cn=accounts,dc=technolink,dc=lu","level":0,"time":"2016-03-04T13:46:24+00:00","method":"GET","url":"\/index.php\/settings\/users\/users?offset=0&limit=250&gid=ens-president&pattern="}
{"reqId":"bGfPOGxNbRkBOpXOx1gp","remoteAddr":"10.81.1.19","app":"$$aw$$","message":"usersInGroup - members is uid=annemarieschwartz,cn=users,cn=accounts,dc=technolink,dc=lu","level":0,"time":"2016-03-04T13:46:24+00:00","method":"GET","url":"\/index.php\/settings\/users\/users?offset=0&limit=250&gid=ens-president&pattern="}
{"reqId":"bGfPOGxNbRkBOpXOx1gp","remoteAddr":"10.81.1.19","app":"$$aw$$","message":"usersInGroup - members is uid=carolinepundel,cn=users,cn=accounts,dc=technolink,dc=lu","level":0,"time":"2016-03-04T13:46:24+00:00","method":"GET","url":"\/index.php\/settings\/users\/users?offset=0&limit=250&gid=ens-president&pattern="}
{"reqId":"bGfPOGxNbRkBOpXOx1gp","remoteAddr":"10.81.1.19","app":"$$aw$$","message":"usersInGroup - members is uid=christophedeloge,cn=users,cn=accounts,dc=technolink,dc=lu","level":0,"time":"2016-03-04T13:46:24+00:00","method":"GET","url":"\/index.php\/settings\/users\/users?offset=0&limit=250&gid=ens-president&pattern="}
{"reqId":"bGfPOGxNbRkBOpXOx1gp","remoteAddr":"10.81.1.19","app":"$$aw$$","message":"usersInGroup - members is uid=christophepletschette,cn=users,cn=accounts,dc=technolink,dc=lu","level":0,"time":"2016-03-04T13:46:24+00:00","method":"GET","url":"\/index.php\/settings\/users\/users?offset=0&limit=250&gid=ens-president&pattern="}
{"reqId":"bGfPOGxNbRkBOpXOx1gp","remoteAddr":"10.81.1.19","app":"$$aw$$","message":"usersInGroup - members is uid=claudegrethen,cn=users,cn=accounts,dc=technolink,dc=lu","level":0,"time":"2016-03-04T13:46:24+00:00","method":"GET","url":"\/index.php\/settings\/users\/users?offset=0&limit=250&gid=ens-president&pattern="}
{"reqId":"bGfPOGxNbRkBOpXOx1gp","remoteAddr":"10.81.1.19","app":"$$aw$$","message":"usersInGroup - members is uid=guyentringer,cn=users,cn=accounts,dc=technolink,dc=lu","level":0,"time":"2016-03-04T13:46:24+00:00","method":"GET","url":"\/index.php\/settings\/users\/users?offset=0&limit=250&gid=ens-president&pattern="}
{"reqId":"bGfPOGxNbRkBOpXOx1gp","remoteAddr":"10.81.1.19","app":"$$aw$$","message":"usersInGroup - members is uid=jeanwelter,cn=users,cn=accounts,dc=technolink,dc=lu","level":0,"time":"2016-03-04T13:46:24+00:00","method":"GET","url":"\/index.php\/settings\/users\/users?offset=0&limit=250&gid=ens-president&pattern="}
{"reqId":"bGfPOGxNbRkBOpXOx1gp","remoteAddr":"10.81.1.19","app":"$$aw$$","message":"usersInGroup - members is uid=jeanpaulbarthel,cn=users,cn=accounts,dc=technolink,dc=lu","level":0,"time":"2016-03-04T13:46:24+00:00","method":"GET","url":"\/index.php\/settings\/users\/users?offset=0&limit=250&gid=ens-president&pattern="}
{"reqId":"bGfPOGxNbRkBOpXOx1gp","remoteAddr":"10.81.1.19","app":"$$aw$$","message":"usersInGroup - members is uid=kellymeris,cn=users,cn=accounts,dc=technolink,dc=lu","level":0,"time":"2016-03-04T13:46:24+00:00","method":"GET","url":"\/index.php\/settings\/users\/users?offset=0&limit=250&gid=ens-president&pattern="}
{"reqId":"bGfPOGxNbRkBOpXOx1gp","remoteAddr":"10.81.1.19","app":"$$aw$$","message":"usersInGroup - members is uid=kristinawelter,cn=users,cn=accounts,dc=technolink,dc=lu","level":0,"time":"2016-03-04T13:46:24+00:00","method":"GET","url":"\/index.php\/settings\/users\/users?offset=0&limit=250&gid=ens-president&pattern="}
{"reqId":"bGfPOGxNbRkBOpXOx1gp","remoteAddr":"10.81.1.19","app":"$$aw$$","message":"usersInGroup - members is uid=lucbartz,cn=users,cn=accounts,dc=technolink,dc=lu","level":0,"time":"2016-03-04T13:46:24+00:00","method":"GET","url":"\/index.php\/settings\/users\/users?offset=0&limit=250&gid=ens-president&pattern="}
{"reqId":"bGfPOGxNbRkBOpXOx1gp","remoteAddr":"10.81.1.19","app":"$$aw$$","message":"usersInGroup - members is uid=maloufaber,cn=users,cn=accounts,dc=technolink,dc=lu","level":0,"time":"2016-03-04T13:46:24+00:00","method":"GET","url":"\/index.php\/settings\/users\/users?offset=0&limit=250&gid=ens-president&pattern="}
{"reqId":"bGfPOGxNbRkBOpXOx1gp","remoteAddr":"10.81.1.19","app":"$$aw$$","message":"usersInGroup - members is uid=marcmolitor,cn=users,cn=accounts,dc=technolink,dc=lu","level":0,"time":"2016-03-04T13:46:24+00:00","method":"GET","url":"\/index.php\/settings\/users\/users?offset=0&limit=250&gid=ens-president&pattern="}
{"reqId":"bGfPOGxNbRkBOpXOx1gp","remoteAddr":"10.81.1.19","app":"$$aw$$","message":"usersInGroup - members is uid=moniqueadam,cn=users,cn=accounts,dc=technolink,dc=lu","level":0,"time":"2016-03-04T13:46:24+00:00","method":"GET","url":"\/index.php\/settings\/users\/users?offset=0&limit=250&gid=ens-president&pattern="}
{"reqId":"bGfPOGxNbRkBOpXOx1gp","remoteAddr":"10.81.1.19","app":"$$aw$$","message":"usersInGroup - members is uid=pascaleschonckert,cn=users,cn=accounts,dc=technolink,dc=lu","level":0,"time":"2016-03-04T13:46:24+00:00","method":"GET","url":"\/index.php\/settings\/users\/users?offset=0&limit=250&gid=ens-president&pattern="}
{"reqId":"bGfPOGxNbRkBOpXOx1gp","remoteAddr":"10.81.1.19","app":"$$aw$$","message":"usersInGroup - members is uid=sheilaclesse,cn=users,cn=accounts,dc=technolink,dc=lu","level":0,"time":"2016-03-04T13:46:24+00:00","method":"GET","url":"\/index.php\/settings\/users\/users?offset=0&limit=250&gid=ens-president&pattern="}
{"reqId":"bGfPOGxNbRkBOpXOx1gp","remoteAddr":"10.81.1.19","app":"$$aw$$","message":"usersInGroup - members is uid=tomdauphin,cn=users,cn=accounts,dc=technolink,dc=lu","level":0,"time":"2016-03-04T13:46:24+00:00","method":"GET","url":"\/index.php\/settings\/users\/users?offset=0&limit=250&gid=ens-president&pattern="}
{"reqId":"bGfPOGxNbRkBOpXOx1gp","remoteAddr":"10.81.1.19","app":"$$aw$$","message":"usersInGroup - members is uid=kyramichels,cn=users,cn=accounts,dc=technolink,dc=lu","level":0,"time":"2016-03-04T13:46:24+00:00","method":"GET","url":"\/index.php\/settings\/users\/users?offset=0&limit=250&gid=ens-president&pattern="}
{"reqId":"bGfPOGxNbRkBOpXOx1gp","remoteAddr":"10.81.1.19","app":"$$aw$$","message":"usersInGroup - members is uid=christinehoffmann,cn=users,cn=accounts,dc=technolink,dc=lu","level":0,"time":"2016-03-04T13:46:24+00:00","method":"GET","url":"\/index.php\/settings\/users\/users?offset=0&limit=250&gid=ens-president&pattern="}

and then I get over 5000 log lines from the user_ldap method again.

**Comment by alexweirig** [comment]
@blizzz 
when I list all the users, you can see that for none of the users the dynamic group membership is correctly identified. All the users show "no group" (except those that have static group memberships).
see the 2 screenshots attached, one from the 9rc1 the other one from the 8.2.1.
[Archive.zip](https://github.com/owncloud/core/files/158793/Archive.zip)

**Comment by alexweirig** [comment]
@blizzz 
I think I found the problem:
**in 8.2.1** in user_ldap.php in function getUserGroups we have:
$userMatch = $this->access->readAttribute(
                                                $uid
                                                'uid'
                                                $memberUrlFilter
                                        );
here, $uid is the BaseDN string, i.e. uid=....,cn=,......

**in 9.0.0** we have
$userMatch = $this->access->readAttribute(
                                                $uid,
                                                $this->access->connection->ldapUserDisplayName,
                                                $memberUrlFilter
                                        );
but here the $uid contains only the "uid" not the baseDN.

In lib/access.php we have the method "readAttribute". It contains the following line (ignore the logging, that's me):
\OCP\Util::writeLog('__aw__', 'readAttribute dn = ' . $dn, \OCP\Util::DEBUG);
                **$dn = $this->DNasBaseParameter($dn);**
\OCP\Util::writeLog('__aw__', 'readAttribute dn = ' . $dn, \OCP\Util::DEBUG);

but when I execute the code, $dn keeps the same value. So this->DNasBaseParameter does not change the value in this case.

When I change user_ldap.php and manually add the baseDN to the $uid variabel (in our case that's uid=...,cn=users,cn=accounts,dc=technolink,dc=lu) e.g.
$uidWithBaseDN = 'uid=' . $uid . ',cn=users,cn=accounts,dc=technolink,dc=lu' and then use $uidWithBaseDN in the this->access-readAttribute call then everything works fine and the groups are correctly retrieved.

The problem now makes sense to me, since we're running a filter on LDAP with merely the simple userid (no baseDN) LDAP can't find anything in readAttribute.

What might be causing this difference? Is $uid in getUserGroups supposed to be just the userid or is it supposed to contain the baseDN?
Do you want me to do other tests?

**Comment by alexweirig** [comment]
@blizzz 
I've now installed 9.0.0 and wanted to see if the problem was fixed.

The problem with the uid still exists so I fixed this by generating a valid DN using:
`$uidBaseDN = $this->access->username2dn($uid);`
before calling 
`$userMatch = $this->access->readAttribute(`
in `group_ldap.php`
After this I noticed that with 9.0.0 there is another problem ...
In `lib/access.php` in `readAttribute` it seems that 
```
$er = $this->ldap->firstEntry($cr, $rr);
if(!$this->ldap->isResource($er)) {
```
now always is false even though $rr seems to be a Resource and seems to contain the correct result for the LDAP search.

**Comment by alexweirig** [comment]
@blizzz @PVince81 
I've created a new issue for this: #23081

**Comment by blizzz** [comment]
Sorry it took me some time to get to the originally reported problem. 

So far I am not entirely convinced this is an issue.

>  Sometimes a valid user is not found (not present in the table for some unknown reason) and a return result of “false” or “null” is bubbled up the above call stack and the existing user is not added to the array to be returned by getVerifiedUsers.

This means a user was deleted from the mappings table. Since the LDAP backends hands out a username only if the mapping succeeded. This brings us to possible scenarios:
* user mappings table was cleared
* user was removed manually from the mappings table
* user was deleted properly

In the last case, no tracks of the user are supposed to be left. For one we do a cleanup in core ourselves, for the other hooks are thrown. However, apps need to react to it by themselves.

In any cases the username is lost as in unmapped, as such getVerifiedUsers() is not supposed to return a value. We cannot do look up remotely, because it is an ownCloud value. Yes, based on an LDAP one, but a) it can be manipulated (character constraints, name collisions), b) it introduces a risk that former local users could be recognized as LDAP users by doing a search on this input.

What brings back to live such users would be logging in or looking them up (search dialogue, users page). Since getVerifiedUsers behaves as desired I consider this a "won't fix". 

@alexweirig does this explain your observations?

**Comment by alexweirig** [comment]
@blizzz 
I think the problem is that the user not showing up is "temporary". Let me explain:

- we have a dynamic group in LDAP with 20 users
- we click on the group in LDAP and get only 19 users
- we look at the list of all users, the 1 user is not displayed
- we do a search for that user and now the user is being displayed
- we click on the dynamic group again and now the 20 users are being displayed

So this problem applied to users that **are still active** and that have not been deleted from the "source", i.e. LDAP.

**Comment by alexweirig** [comment]
@blizzz 
from what I can see, the problem seems to no longer occur in 9.0.0 with my fix for the dynamic groups applied.

**Comment by blizzz** [comment]
@alexweirig Ah, this makes sense: the added ``$this->access->dn2groupname($dynamicGroup['dn'][0]);`` triggers a mapping.
