### ISSUE TITLE
Upgrade from 8.0.3 to 8.2.1 not working

### ISSUE THREAD

**Issue by michael71** [owncloud/core#21228]
Hi, I tried to upgrade an owncloud installation from 8.0.3.4 to 8.2.1 - even the manual upgrade (unzipping the new owncloud code to a separate dir, run "occ upgrade" at the command line did not work.

ERROR Msg:
"Exception: Updates between multiple major versions and downgrades are unsupported.
Update failed"

In the meantime I have understood that this is a "major" upgrade (although it is from 8.x to 8.x) - so what can I do now ? Do I have to do a "new install" and recreate the users?

Any help is appreciated.

thanks, michael.

**Comment by tflidd** [comment]
Duplicate of https://github.com/owncloud/core/issues/21186

**Comment by RealRancor** [comment]
See https://github.com/owncloud/core/issues/20974#issuecomment-162319494 how to do a correct upgrade.
