### ISSUE TITLE
Object of class OC\\Connector\\Sabre\\Directory could not be converted to string

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#21230]
```
{"reqId":"LrktWybwli\/kyKS3yogp","remoteAddr":"172.26.112.16","app":"PHP","message":"Object of class OC\\Connector\\Sabre\\Directory could not be converted to string at \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/objecttree.php#191","level":3,"time":"2015-12-11T13:33:31+00:00"}
```

Instead it should be something like `Could not copy directory PATH, target exists'.

![bildschirmfoto 2015-12-16 um 14 15 19](https://cloud.githubusercontent.com/assets/245432/11841771/e0557308-a3ff-11e5-8e79-6af3e4326b41.png)

*cough* @icewind1991 *cough* (please fix it - I don't know how to get a path out of an ICollection :see_no_evil: )

https://github.com/owncloud/core/commit/fe0de5fc10f61a7bb3173a04a986b145789b9160#diff-bad86217951709753766eabf0f82deacR62 ;)

This is the line on current master: 
https://github.com/owncloud/core/blob/aa6230e389b9756fc4cdb0e6b382281a762ddf74/apps/dav/lib/connector/sabre/objecttree.php#L193

Or @deepdiver1975 or @PVince81

**Comment by PVince81** [comment]
I think it should be `$sourceNode->getName()` or something... seems this error case hasn't been tested.
