### ISSUE TITLE
Usermanagement: Password change error display behavior

### ISSUE THREAD

**Issue by michag86** [owncloud/core#21239]
On changing the password of an user in the user management, the password change error message is shown permanently:
https://github.com/owncloud/core/blob/v8.2.1/settings/js/users/users.js#L657

Is there a better way to show the password change error?

The easiest way is to change "OC.Notification.show" to "OC.Notification.showTemporary".

This notification can be used in [password policy app](https://apps.owncloud.com/content/show.php?content=167207) to show, that the password will not comply with the policy. But it is not useful to show this error permanently. 

At the moment, the app does not return the correct formatted response. But this is just a small change.

**Comment by PVince81** [comment]
@michag86 change it to `showTemporary` instead.
PR ? :smile:

**Comment by michag86** [comment]
@DeepDiver1975 can we backport this to 8.2 and 8.1?

**Comment by karlitschek** [comment]
@PVince81 @DeepDiver1975 are you in favor of a backport?

**Comment by DeepDiver1975** [comment]
> @PVince81 @DeepDiver1975 are you in favor of a backport?

no objections - low criticality
