### ISSUE TITLE
Lost password JavaScript gets stuck

### ISSUE THREAD

**Issue by carlalexander** [owncloud/core#21243]
### Steps to reproduce
1. Attempt to login with invalid password
2. Click reset password button
3. Click on reset password email link
4. Enter new password
5. Click "Reset password"

### Expected behaviour
I'd expect to see a login form or to be logged in. I haven't seen it work yet.

### Actual behaviour
The reset form gets submitted and the spinner just stays there forever. Further investigation shows that the webserver returns a 405 error during [`resetDone`](https://github.com/owncloud/core/blob/master/core/js/lostpassword.js#L98-L105) in `lostpassword.js`. This blocks the script which gets stuck because there wasn't a valid response.

I'll put more details below in the browser log section.

### Server configuration
**Operating system**: Ubuntu LTS 14.04.3

**Web server:** nginx 1.4.6

**Database:** 5.5.46-MariaDB

**PHP version:** PHP 5.5.9

**ownCloud version:** 8.2.1

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**

Enabled:
  - activity: 2.1.3
  - encryption: 1.1.0
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1

Disabled:
  - external
  - files_external
  - updater
  - user_external
  - user_ldap

**The content of config/config.php:**

```json
{
    "system": {
        "forcessl": true,
        "logdateformat": "Y-m-d H:i:s.u",
        "loglevel": 0,
        "logtimezone": "UTC",
        "remember_login_cookie_lifetime": "1296000",
        "session_keepalive": true,
        "session_lifetime": "86400",
        "trashbin_auto_expire": true,
        "trashbin_retention_obligation": 30,
        "mail_domain": "globalvoices.org",
        "mail_from_address": "owncloud",
        "mail_smtpmode": "sendmail",
        "instanceid": "ock2zlgl298t",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.globalvoices.org"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/cloud.globalvoices.org",
        "dbtype": "mysql",
        "version": "8.2.1.4",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true
    }
}
```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** Yes (tried with both scenarios)

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Chrome/Firefox/Safari

**Operating system:** Mac / iOS

#### Web server error log

No webserver logs

#### ownCloud log (data/owncloud.log)

Each time I tested, I could see this log entry:

```
{"reqId":"H83D0hLcD1Lg0dcSRcqz","remoteAddr":"::ffff:50.21.138.140","app":"hook","message":"error while running hook (OCA\\Encryption\\Hooks\\UserHooks::setPassphrase): Private Key missing for user: please try to log-out and log-in again","level":3,"time":"2015-12-16 17:02:26.000000"}
```
#### Browser log

```
POST https://cloud.globalvoices.org/ 405 (Not Allowed)
send @ jquery.min.js:6
x.extend.ajax @ jquery.min.js:6
x.(anonymous function) @ jquery.min.js:6
OC.Lostpassword.resetDone @ lostpassword.js?v=3395da550a3a8c167047df9a650121ae:94
c @ jquery.min.js:4
p.fireWith @ jquery.min.js:4
k @ jquery.min.js:6
r @ jquery.min.js:6
```

**Comment by PVince81** [comment]
A 405 ? Maybe double check your nginx config, something must be preventing that route to be executed properly ?

**Comment by PVince81** [comment]
Why is it posting to https://cloud.globalvoices.org/ and not the full route ?
Maybe something went wrong when computing the route.

@LukasReschke @icewind1991

**Comment by carlalexander** [comment]
Would you like me to show the nginx vhost config?

**Comment by tobru** [comment]
I see exactly the same behaviour here, the server specs are the same as in the original bug report, except that I'm running ownCloud 8.2.2. Here is the Nginx vHost configuration (excerpt):

```
server {

[snip]

  location / {
    rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
    rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json last;
    rewrite ^/.well-known/carddav /remote.php/carddav/ redirect;
    rewrite ^/.well-known/caldav /remote.php/caldav/ redirect;
    rewrite ^(/core/doc/[^\/]+/)$ $1/index.html;
    root      /var/www/owncloud/;
    index     index.html index.htm index.php;
    try_files $uri $uri/ /index.php;
  }

  location ~ ^/(?:\.htaccess|data|config|db_structure\.xml|README) {
    deny all;
  }

  location ~ \.php(?:$|/) {
    include /etc/nginx/uwsgi_params;
    uwsgi_pass unix:/var/lib/uhosting/oc.socket;
    uwsgi_modifier1 14;
  }

}
```

**Comment by PVince81** [comment]
Is this still happening with 9.0.2 ?

**Comment by PVince81** [comment]
This looks more like a setup issue than a bug in ownCloud, closing.

You might want to check http://owncloud.org/support if it's still happening
