### ISSUE TITLE
upgrade from 8.1.1.4 to 8.1.4.2 failed

### ISSUE THREAD

**Issue by michael71** [owncloud/core#21246]
I'm trying to follow the upgrade path which seems to be recommended ( #20974 ). However, after the upgrade from 8.1.1.4 to 8.1.4.2 (made on the command line, it was "successful") owncloud does not start, in the owncloud.log there I find several "getPath() on non-object errors":

{"reqId":"vLGJsV897oiMknta9K30","remoteAddr":"46.237.1.1","app":"PHP","message":"Call to a member function getPath() on a non-object at \/var\/www\/html\/od\/lib\/private\/connector\/sabre\/node.php#75","level":3,"time":"2015-12-17T05:29:37+00:00"}

and the following error:
```
{"reqId":"7iCibuweQEf6D4w9iY1d","remoteAddr":"46.237.1.1","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/od\\\/apps\\\/files\\\/index.php(84): OC_Helper::getStorageInfo('\\\/', false)\\n#1 \\\/var\\\/www\\\/html\\\/od\\\/lib\\\/private\\\/route\\\/route.php(154) : runtime-created function(1): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#2 [internal function]: __lambda_func(Array)\\n#3 \\\/var\\\/www\\\/html\\\/od\\\/lib\\\/private\\\/route\\\/router.php(274): call_user_func('?lambda_99', Array)\\n#4 \\\/var\\\/www\\\/html\\\/od\\\/lib\\\/base.php(874): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#5 \\\/var\\\/www\\\/html\\\/od\\\/index.php(48): OC::handleRequest()\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/od\\\/lib\\\/private\\\/helper.php\",\"Line\":971}","level":4,"time":"2015-12-17T05:29:56+00:00"}
```

What can be done?

thanks, michael.

**Comment by PVince81** [comment]
@michael71 did you move your data folder ?
Maybe clear the browser cookies ?
Does the home folder of the user still exist in the data folder ?

This looks similar to https://github.com/owncloud/core/issues/20527

**Comment by michael71** [comment]
thanks for the hints ! I forgot to move the data folder (it's in a fixed location on my other owncloud server)
