### ISSUE TITLE
Upgrade from 8.2.0 to 8.2.1 Fails

### ISSUE THREAD

**Issue by JBear7** [owncloud/core#21242]
### Steps to reproduce
1. apt-get update
2. apt-get upgrade
3. sudo -u www-data php occ upgrade

### Expected behaviour
upgrade should happen

### Actual behaviour

root@Horton:/var/www/owncloud# sudo -u www-data php occ upgrade

				ownCloud or one of the apps require upgrade - only a limited number of commands are available
				Set log level to debug - current level: 'Debug'
				Checking whether the database schema can be updated (this can take a long time depending on the database size)
				Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO `oc_oc_appconfig_zh85an8d1jme2` SELECT * FROM `oc_appconfig`':

				SQLSTATE[HY000]: General error: 1665 Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT
				and at least one table uses a storage engine limited to row-based logging. InnoDB is limited to row-logging when transaction isolation level is READ COMMITTED or READ UNCOMMITTED.
				Update failed
				Maintenance mode is kept active
				Reset log level to 'Debug'
				PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1665 Cannot execute statement: 
				impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at least one table uses a storage engine limited to row-based logging. 
				InnoDB is limited to row-logging when transaction isolation level is READ COMMITTED or READ UNCOMMITTED.' in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91
				Stack trace:
				#0 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(Array)
				#1 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(989): Doctrine\DBAL\Driver\PDOStatement->execute(Array)
				#2 /var/www/owncloud/lib/private/db/connection.php(203): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM `oc...', Array, Array)
				#3 /var/www/owncloud/lib/private/lock/dblockingprovider.php(241): OC\DB\Connection->executeUpdate('DELETE FROM `*P...', Array)
				#4 /var/www/owncloud/lib/private/lock/dblockingprov in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 115
root@Horton:/var/www/owncloud#

after changing binlog-format to MIXED and restarting mysql

				root@Horton:/var/www/owncloud# nano /etc/mysql/my.cnf
					
the new error is 

root@Horton:/var/www/owncloud# sudo -u www-data php occ upgrade
ownCloud or one of the apps require upgrade - only a limited number of commands are available
Set log level to debug - current level: 'Debug'
Checking whether the database schema can be updated (this can take a long time depending on the database size)
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'DROP TABLE `oc_oc_mimetypes_3466vbwg7s4ju`':

SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
Update failed
Maintenance mode is kept active
Reset log level to 'Debug'
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 
2006 MySQL server has gone away' in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104
Stack trace:
#0 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(104): PDO->query('SHOW FULL TABLE...')
#1 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(833): Doctrine\DBAL\Driver\PDOConnection->query('SHOW FULL TABLE...')
#2 /var/www/owncloud/lib/private/db/connection.php(182): Doctrine\DBAL\Connection->executeQuery('SHOW FULL TABLE...', Array, Array, NULL)
#3 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(766): OC\DB\Connection->executeQuery('SHOW FULL TABLE...', Array, Array)
#4 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php(219): Doctrine\DBAL\Connection->fetchAll('SHOW FULL TABLE...')
#5 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManag in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 115
root@Horton:/var/www/owncloud#

### Server configuration
**Operating system**:

	Distributor ID: Ubuntu
	Description:    Ubuntu 14.04.3 LTS
	Release:        14.04
	Codename:       trusty

**Web server:**

	apache2 Server version: Apache/2.4.7 (Ubuntu) Server built:   Oct 14 2015 14:18:49
	
**Database:**

	mysql  Ver 15.1 Distrib 10.0.22-MariaDB, for debian-linux-gnu (i686) using readline 5.2
	
**PHP version:**

	PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:32:13)
	
**ownCloud version:** (see ownCloud admin page)

	

**Updated from an older ownCloud or fresh install:**

	Upgrade path from /var/log/dpkg.log and dpkg.log.1
	
		8.1.3-13.1 to  8.1.4-12.1 OK
		8.1.4-12.1 to 8.2.0-2.1  OK
		8.2.0-2.1 to  8.2.1-1.1  Failed

**List of activated apps:**

	root@Horton:/var/www/owncloud# sudo -u www-data php occ app:list
	ownCloud or one of the apps require upgrade - only a limited number of commands are available
	Enabled:
	  - activity: 2.1.3
	  - files: 1.2.0
	  - files_pdfviewer: 0.7
	  - files_sharing: 0.7.0
	  - files_texteditor: 2.0
	  - files_trashbin: 0.7.0
	  - files_versions: 1.1.0
	  - files_videoviewer: 0.1.3
	  - firstrunwizard: 1.1
	  - gallery: 14.2.0
	  - provisioning_api: 0.3.0
	  - templateeditor: 0.1
	  - updater: 0.6
	Disabled:
	  - encryption
	  - external
	  - files_antivirus
	  - files_external
	  - notifications
	  - user_external
	  - user_ldap

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

	root@Horton:/var/www/owncloud# sudo -u www-data php occ config:list system
	ownCloud or one of the apps require upgrade - only a limited number of commands are available
	{
		"system": {
			"instanceid": "ochpa1mr2qj2",
			"passwordsalt": "***REMOVED SENSITIVE VALUE***",
			"secret": "***REMOVED SENSITIVE VALUE***",
			"trusted_domains": [
				"192.168.1.204"
			],
			"datadirectory": "\/mnt\/owncloud\/data_1",
			"overwrite.cli.url": "http:\/\/192.168.1.204\/owncloud",
			"dbtype": "mysql",
			"version": "8.2.0.12",
			"dbname": "ownclouddb",
			"dbhost": "localhost",
			"dbtableprefix": "oc_",
			"dbuser": "***REMOVED SENSITIVE VALUE***",
			"dbpassword": "***REMOVED SENSITIVE VALUE***",
			"logtimezone": "UTC",
			"installed": true,
			"loglevel": 0,
			"mail_smtpmode": "smtp",
			"mail_from_address": "owncloud",
			"mail_domain": "horton.home.wallace-inc.com",
			"maintenance": true,
			"theme": "",
			"trashbin_retention_obligation": "auto"
		}
	}
	root@Horton:/var/www/owncloud#

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

	NO

**Are you using encryption:** yes/no

	NO

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

	NO

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

	chrome
	
**Operating system:**

	win7, win8
	android

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)

	
```
	root@Horton:/var/www/owncloud# cat /var/www/owncloud/data/owncloud.log
	{"reqId":"mDK9kUszBLKm7H7MK\/pJ","remoteAddr":"","app":"PHP","message":"fopen(\/var\/www\/owncloud\/config\/config.php): 
	failed to open stream: No such file or directory at \/var\/www\/owncloud\/lib\/private\/config.php#191","level":3,"time":"2015-10-17T22:27:46+00:00"}
	root@Horton:/var/www/owncloud#
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log

**Comment by MorrisJobke** [comment]
Documented in https://doc.owncloud.org/server/8.2/admin_manual/configuration_database/linux_database_configuration.html?highlight=binlog_format#mysql-mariadb-with-binary-logging-enabled




> SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
> Update failed

The mysql server is not available. Not much we can do here.

**Comment by JBear7** [comment]
The mysql server is available, every time I run the occ upgrade owncloud adds a new table to the database then chokes trying to DROP it.

Here is the list of tables,
MariaDB [ownclouddb]> show tables;
+-------------------------------+
| Tables_in_ownclouddb          |
+-------------------------------+
| oc_activity                   |
| oc_activity_mq                |
| oc_appconfig                  |
| oc_file_locks                 |
| oc_file_map                   |
| oc_filecache                  |
| oc_files_antivirus            |
| oc_files_avir_status          |
| oc_files_trash                |
| oc_group_admin                |
| oc_group_user                 |
| oc_groups                     |
| oc_jobs                       |
| oc_mimetypes                  |
| oc_oc_appconfig_0daf6xiq85s18 |
| oc_oc_appconfig_0rp03nzv6gvoj |
| oc_oc_appconfig_14apapdncpv5s |
| oc_oc_appconfig_3daqdx7joagka |
| oc_oc_appconfig_51eu4jkbtwtsx |
| oc_oc_appconfig_58onky9xy32i7 |
| oc_oc_appconfig_6nkbbjf5nq0c1 |
| oc_oc_appconfig_9kozzhdzpj426 |
| oc_oc_appconfig_d5z6fw8a49stp |
| oc_oc_appconfig_eeavhkwy8w476 |
| oc_oc_appconfig_gprhzl87klz7w |
| oc_oc_appconfig_hqgi5bpjt69nk |
| oc_oc_appconfig_i31yvqjye26of |
| oc_oc_appconfig_j4ov0d60q7ih5 |
| oc_oc_appconfig_j512120d24eg9 |
| oc_oc_appconfig_jigq332272meo |
| oc_oc_appconfig_jjgx31mfhdr3j |
| oc_oc_appconfig_lv7t378yz5ly5 |
| oc_oc_appconfig_mbk69uo581nqx |
| oc_oc_appconfig_mxfb96s5q6c3b |
| oc_oc_appconfig_pfrkelnr129aq |
| oc_oc_appconfig_qb7aofvh7qrt8 |
| oc_oc_appconfig_qspk4rco90py3 |
| oc_oc_appconfig_t3ez599vq7h51 |
| oc_oc_appconfig_ti3fmp2mwpfrc |
| oc_oc_appconfig_u6sc936b9k2tz |
| oc_oc_appconfig_ucn8bawzg7ixq |
| oc_oc_appconfig_vtni57tqpnbxq |
| oc_oc_appconfig_yuh58qdqy1m86 |
| oc_oc_appconfig_zh85an8d1jme2 |
| oc_oc_file_map_i1y8fissyb5fr  |
| oc_oc_mimetypes_3466vbwg7s4ju |
| oc_oc_mimetypes_g5x3ofmp2vsh7 |
| oc_oc_storages_ykymjm29xwc22  |
| oc_preferences                |
| oc_privatedata                |
| oc_properties                 |
| oc_share                      |
| oc_share_external             |
| oc_storages                   |
| oc_users                      |
| oc_vcategory                  |
| oc_vcategory_to_object        |
+-------------------------------+
57 rows in set (0.01 sec)

**Comment by MorrisJobke** [comment]
> https://doc.owncloud.org/server/8.2/admin_manual/configuration_database/linux_database_configuration.html?highlight=binlog_format#mysql-mariadb-with-binary-logging-enabled

@JBear7 Did you tried this to fix at least following error:

```
 SQLSTATE[HY000]: General error: 1665 Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT
            and at least one table uses a storage engine limited to row-based logging. InnoDB is limited to row-logging when transaction isolation level is READ COMMITTED or READ UNCOMMITTED.
           
````

**Comment by JBear7** [comment]
Yes I made that change in /etc/mysql/my.cnf.

MariaDB [ownclouddb]> show variables like 'binlog_format';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| binlog_format | MIXED |
+---------------+-------+
1 row in set (0.00 sec)

MariaDB [ownclouddb]>

**Comment by JBear7** [comment]
Here is one of the more resent errors:

root@Horton:~# sudo -u www-data php /var/www/owncloud/occ upgrade -vvv
ownCloud or one of the apps require upgrade - only a limited number of commands are available
2015-12-21T00:16:41+00:00 Set log level to debug - current level: 'Debug'
2015-12-21T00:16:41+00:00 Repair step: Repair MySQL database engine
2015-12-21T00:16:41+00:00 Repair step: Repair MySQL collation
2015-12-21T00:16:41+00:00 Repair step: Repair SQLite autoincrement
2015-12-21T00:16:41+00:00 Repair step: Repair duplicate entries in oc_lucene_status
2015-12-21T00:16:41+00:00 Repair info: lucene_status table does not exist -> nothing to do
2015-12-21T00:16:41+00:00 Repair step: Repair config
2015-12-21T00:16:41+00:00 Checking whether the database schema can be updated (this can take a long time depending on the database size)
2015-12-21T00:16:43+00:00 Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'DROP TABLE `oc_oc_appconfig_qb7aofvh7qrt8`':

SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
2015-12-21T00:16:43+00:00 Update failed
2015-12-21T00:16:43+00:00 Maintenance mode is kept active
2015-12-21T00:16:43+00:00 Reset log level to 'Debug'
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104
Stack trace:
#0 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(104): PDO->query('SHOW FULL TABLE...')
#1 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(833): Doctrine\DBAL\Driver\PDOConnection->query('SHOW FULL TABLE...')
#2 /var/www/owncloud/lib/private/db/connection.php(182): Doctrine\DBAL\Connection->executeQuery('SHOW FULL TABLE...', Array, Array, NULL)
#3 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(766): OC\DB\Connection->executeQuery('SHOW FULL TABLE...', Array, Array)
#4 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php(219): Doctrine\DBAL\Connection->fetchAll('SHOW FULL TABLE...')
#5 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManag in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 115
root@Horton:~#

Jerry

**Comment by skironDotNet** [comment]
This helped https://help.nextcloud.com/t/solved-update-fails-because-of-database-error/21624
