### ISSUE TITLE
Public link shares to a file have no preview

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#21250]
* it's a lie - they have a preview of size 2 x 1 pixel, but it's simply invisible ;)

![bildschirmfoto 2015-12-17 um 10 14 25](https://cloud.githubusercontent.com/assets/245432/11865832/ff09cf18-a4a6-11e5-800c-d8b66cca665e.png)

Because quite big values for x and y are passed via URL I guess the preview code is buggy.

cc @icewind1991 @georgehrke @oparoz

**Comment by PVince81** [comment]
bisect?

**Comment by oparoz** [comment]
Since you mentioned large dimensions, it could be that GD ran out of memory or something like that.

**Comment by MorrisJobke** [comment]
Works somehow now. Closing
