### ISSUE TITLE
owncloud-latest.tar.bz2 Download-Link is outdated

### ISSUE THREAD

**Issue by golderweb** [owncloud/core#21258]
### Steps to reproduce
wget https://download.owncloud.org/community/owncloud-latest.tar.bz2

### Expected behaviour
Download of latest owncloud-server version

### Actual behaviour
The link above points to an outdated release (8.0.3 rather than 8.2.1)

Since I like to use a script for automatic updating process via command line, having a working latest-link would be great.

**Comment by rullzer** [comment]
@cmonteroluque

**Comment by karlitschek** [comment]
fixed
