### ISSUE TITLE
Redis server went away

### ISSUE THREAD

**Issue by sif77** [owncloud/core#21266]
I am using version 8.2.1.

When i use unix socket, i get "Redis server went away" (owncloud-8.2.1/lib/private/memcache/redis.php(74)).

My config.php file :
...
  'filelocking.enabled' => 'true',
  'memcache.locking' => '\OC\Memcache\Redis',
  'memcache.local' => '\OC\Memcache\Redis',
  'redis' => array(
     'host' => '/var/lib/redis/redis.sock',
     'port' => 0,
     'timeout' => 0.0,
     'dbindex' => 8,
  ),

But no problem with TCP socket 

...
  'filelocking.enabled' => 'true',
  'memcache.locking' => '\OC\Memcache\Redis',
  'memcache.local' => '\OC\Memcache\Redis',
  'redis' => array(
     'host' => '127.0.0.1',
     'port' => 6379,
     'timeout' => 0.0,
     'dbindex' => 8,
  ),

**Comment by karlitschek** [comment]
This is a problem of you local installation and not an ownCloud bug. Please check owncloud.org/support for option to get help.

**Comment by sif77** [comment]
I did a test outside owncloud before addind this issue.

<?php
$sock = '/var/lib/redis/redis.sock';
$port = 0;
$timeout = 0.0;
$redis = new Redis();
try {
        $redis->connect($sock);
        print "ok\n";
} catch (Exception $e) {
    error_log("Error 1: ".$e->getMessage());
}
try {
    $redis->get("unknown key");
} catch (Exception $e) {
    error_log("Error 2: ".$e->getMessage());
}
?>
