### ISSUE TITLE
Syncing to external storage prevent file type recognition

### ISSUE THREAD

**Issue by paolosg** [owncloud/core#21271]
When I sync a folder containing pictures or music directly to an external storage (Google Drive) the file type (jpg or mp3) is not recognized and the OC web interface always open the files as text.

OC v8.1.4 (on Ubuntu server 14.04)
Windows OC client 2.1.0 (build 5683)

**Comment by karlitschek** [comment]
can zou please send a full bug report using the template? https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by paolosg** [comment]
### Steps to reproduce
1. Sync a folder (using the Windows client) that contains pictures or music directly to a mounted external storage (I could try only with Google Drive)

### Expected behaviour
Music and pictures should be recognized as such by ownCloud

### Actual behaviour
Media files are identified by OC as text and not as pictures or music.
Downloading them back to the client PC they're correctly recognized and opened. When uploading to the server's local storage everything works out as expected.

### Server configuration
**Operating system**:
Ubuntu server 14.04.3 LTS

**Web server:**
Apache 2.4.7

**Database:**
MySQL 5.5.46

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
8.1.4

**Updated from an older ownCloud or fresh install:**
Updated

**List of activated apps:**
Enabled:
 - activity: 2.0.2
 - calendar: 0.7.3
 - contacts: 0.4.0.1
 - documents: 0.10.2
 - encryption: 1.0.0
 - files: 1.1.10
 - files_external: 0.2.3
 - files_locking:
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.3
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - mail: 0.2.1
 - music: 0.3.8
 - provisioning_api: 0.2
 - templateeditor: 0.1

Disabled:
 - external
 - updater
 - user_external
 - user_ldap
 - user_webdavauth

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'oc64fnpqejyx',
  'passwordsalt' => ###,
  'secret' => ###,
  'trusted_domains' =>
  array (
    0 => MY-URL,
    1 => MY-IP,
    2 => '192.168.1.64',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => MY-URL,
  'dbtype' => 'mysql',
  'version' => '8.1.4.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => oc_paolo,
  'dbpassword' => ###,
  'logtimezone' => 'UTC',
  'installed' => true,
  'maintenance' => false,
  'loglevel' => 0,
  'theme' => '',
  'enable_previews' => false,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
Google Drive

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox 42.0

**Operating system:**
Windows 10 (build 1511)

### Logs
#### Web server error log
Nothing useful here, only Apache complaining about my self-signed certificate

#### Web server access log
MY-IP - paolo [18/Dec/2015:15:08:06 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1405 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
MY-IP - paolo [18/Dec/2015:15:08:05 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 2289 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
MY-IP - paolo [18/Dec/2015:15:08:08 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 2146 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
MY-IP - paolo [18/Dec/2015:15:08:16 +0100] "MKCOL /remote.php/webdav/GoogleDrive/test_sync HTTP/1.1" 201 956 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
MY-IP - paolo [18/Dec/2015:15:08:25 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1360 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
MY-IP - paolo [18/Dec/2015:15:08:23 +0100] "PROPFIND /remote.php/webdav/GoogleDrive/test_sync HTTP/1.1" 207 1362 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
MY-IP - paolo [18/Dec/2015:15:08:23 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 2146 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
MY-IP - paolo [18/Dec/2015:15:08:25 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 2146 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
MY-IP - paolo [18/Dec/2015:15:08:25 +0100] "PROPFIND /remote.php/webdav/GoogleDrive HTTP/1.1" 207 2975 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
MY-IP - paolo [18/Dec/2015:15:08:27 +0100] "PROPFIND /remote.php/webdav/GoogleDrive/test_sync HTTP/1.1" 207 1261 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
MY-IP - paolo [18/Dec/2015:15:08:31 +0100] "PROPFIND /remote.php/webdav/GoogleDrive/test_sync HTTP/1.1" 207 1532 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
MY-IP - paolo [18/Dec/2015:15:08:36 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 3047 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
MY-IP - paolo [18/Dec/2015:15:08:33 +0100] "PUT /remote.php/webdav/GoogleDrive/test_sync/1.jpg HTTP/1.1" 201 884 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
MY-IP - paolo [18/Dec/2015:15:09:06 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1262 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
MY-IP - - [18/Dec/2015:15:09:19 +0100] "GET /index.php/apps/files/ajax/list.php?dir=%2F&sort=name&sortdirection=asc HTTP/1.1" 200 2391 "https://MY-URL/index.php/apps/files/?dir=%2F" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0"
MY-IP - - [18/Dec/2015:15:09:20 +0100] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/1.1" 200 1013 "https://MY-URL/index.php/apps/files/?dir=%2F" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0"
MY-IP - - [18/Dec/2015:15:09:21 +0100] "GET /index.php/apps/files/ajax/list.php?dir=%2FGoogleDrive&sort=name&sortdirection=asc HTTP/1.1" 200 3519 "https://MY-URL/index.php/apps/files/?dir=%2FGoogleDrive" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0"
MY-IP - paolo [18/Dec/2015:15:09:29 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1360 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
MY-IP - - [18/Dec/2015:15:09:27 +0100] "GET /index.php/apps/files/ajax/list.php?dir=%2FGoogleDrive%2Ftest_sync&sort=name&sortdirection=asc HTTP/1.1" 200 1317 "https://MY-URL/index.php/apps/files/?dir=%2FGoogleDrive%2Ftest_sync" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0"
MY-IP - - [18/Dec/2015:15:09:29 +0100] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2FGoogleDrive%2Ftest_sync HTTP/1.1" 200 1015 "https://MY-URL/index.php/apps/files/?dir=%2FGoogleDrive%2Ftest_sync" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0"
MY-IP - paolo [18/Dec/2015:15:09:36 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1405 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
MY-IP - - [18/Dec/2015:15:09:24 +0100] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2FGoogleDrive HTTP/1.1" 200 1015 "https://MY-URL/index.php/apps/files/?dir=%2FGoogleDrive" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0"

#### ownCloud log (data/owncloud.log)
{"reqId":"+KI5HSy94KRcdbGIEMtp","remoteAddr":"MY-IP","app":"music","message":"update - \/paolo\/files\/GoogleDrive\/test_sync","level":0,"time":"2015-12-18T14:08:23+00:00","method":"MKCOL","url":"\/remote.php\/webdav\/GoogleDrive\/test_sync"}
{"reqId":"I+sLX0qeul9DFRxM8sV0","remoteAddr":"MY-IP","app":"files_locking","message":"INFO: Read lock requested for \/var\/www\/owncloud\/data\/paolo\/files_encryption\/OC_DEFAULT_MODULE\/paolo.publicKey","level":0,"time":"2015-12-18T14:08:48+00:00","method":"PUT","url":"\/remote.php\/webdav\/GoogleDrive\/test_sync\/1.jpg"}
{"reqId":"I+sLX0qeul9DFRxM8sV0","remoteAddr":"MY-IP","app":"files_locking","message":"PASS: Acquired read lock for \/var\/www\/owncloud\/data\/paolo\/files_encryption\/OC_DEFAULT_MODULE\/paolo.publicKey","level":0,"time":"2015-12-18T14:08:48+00:00","method":"PUT","url":"\/remote.php\/webdav\/GoogleDrive\/test_sync\/1.jpg"}
{"reqId":"I+sLX0qeul9DFRxM8sV0","remoteAddr":"MY-IP","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/var\/www\/owncloud\/data\/paolo\/files_encryption\/OC_DEFAULT_MODULE\/paolo.publicKey","level":0,"time":"2015-12-18T14:08:48+00:00","method":"PUT","url":"\/remote.php\/webdav\/GoogleDrive\/test_sync\/1.jpg"}
{"reqId":"I+sLX0qeul9DFRxM8sV0","remoteAddr":"MY-IP","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/var\/www\/owncloud\/data\/paolo\/files_encryption\/OC_DEFAULT_MODULE\/paolo.publicKey","level":0,"time":"2015-12-18T14:08:48+00:00","method":"PUT","url":"\/remote.php\/webdav\/GoogleDrive\/test_sync\/1.jpg"}
{"reqId":"I+sLX0qeul9DFRxM8sV0","remoteAddr":"MY-IP","app":"encryption","message":"no public key found for user \"marta\", user will not be able to read the file","level":2,"time":"2015-12-18T14:08:48+00:00","method":"PUT","url":"\/remote.php\/webdav\/GoogleDrive\/test_sync\/1.jpg"}
{"reqId":"I+sLX0qeul9DFRxM8sV0","remoteAddr":"MY-IP","app":"files_locking","message":"INFO: Read lock requested for \/var\/www\/owncloud\/data\/files_encryption\/OC_DEFAULT_MODULE\/recoveryKey_5aa2c7d5.publicKey","level":0,"time":"2015-12-18T14:08:48+00:00","method":"PUT","url":"\/remote.php\/webdav\/GoogleDrive\/test_sync\/1.jpg"}
{"reqId":"I+sLX0qeul9DFRxM8sV0","remoteAddr":"MY-IP","app":"files_locking","message":"PASS: Acquired read lock for \/var\/www\/owncloud\/data\/files_encryption\/OC_DEFAULT_MODULE\/recoveryKey_5aa2c7d5.publicKey","level":0,"time":"2015-12-18T14:08:48+00:00","method":"PUT","url":"\/remote.php\/webdav\/GoogleDrive\/test_sync\/1.jpg"}
{"reqId":"I+sLX0qeul9DFRxM8sV0","remoteAddr":"MY-IP","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/var\/www\/owncloud\/data\/files_encryption\/OC_DEFAULT_MODULE\/recoveryKey_5aa2c7d5.publicKey","level":0,"time":"2015-12-18T14:08:48+00:00","method":"PUT","url":"\/remote.php\/webdav\/GoogleDrive\/test_sync\/1.jpg"}
{"reqId":"I+sLX0qeul9DFRxM8sV0","remoteAddr":"MY-IP","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/var\/www\/owncloud\/data\/files_encryption\/OC_DEFAULT_MODULE\/recoveryKey_5aa2c7d5.publicKey","level":0,"time":"2015-12-18T14:08:48+00:00","method":"PUT","url":"\/remote.php\/webdav\/GoogleDrive\/test_sync\/1.jpg"}
{"reqId":"I+sLX0qeul9DFRxM8sV0","remoteAddr":"MY-IP","app":"files_locking","message":"INFO: Write lock requested for \/var\/www\/owncloud\/data\/files_encryption\/keys\/files\/GoogleDrive\/test_sync\/1.jpg.ocTransferId1974068519.part\/OC_DEFAULT_MODULE\/fileKey","level":0,"time":"2015-12-18T14:08:49+00:00","method":"PUT","url":"\/remote.php\/webdav\/GoogleDrive\/test_sync\/1.jpg"}
{"reqId":"I+sLX0qeul9DFRxM8sV0","remoteAddr":"MY-IP","app":"files_locking","message":"PASS: Write lock succeeded on \/var\/www\/owncloud\/data\/files_encryption\/keys\/files\/GoogleDrive\/test_sync\/1.jpg.ocTransferId1974068519.part\/OC_DEFAULT_MODULE\/fileKey","level":0,"time":"2015-12-18T14:08:49+00:00","method":"PUT","url":"\/remote.php\/webdav\/GoogleDrive\/test_sync\/1.jpg"}
{"reqId":"I+sLX0qeul9DFRxM8sV0","remoteAddr":"MY-IP","app":"files_locking","message":"INFO: Incrementing lock type 2 count for \/var\/www\/owncloud\/data\/files_encryption\/keys\/files\/GoogleDrive\/test_sync\/1.jpg.ocTransferId1974068519.part\/OC_DEFAULT_MODULE\/fileKey","level":0,"time":"2015-12-18T14:08:49+00:00","method":"PUT","url":"\/remote.php\/webdav\/GoogleDrive\/test_sync\/1.jpg"}
{"reqId":"I+sLX0qeul9DFRxM8sV0","remoteAddr":"MY-IP","app":"files_locking","message":"INFO: Write lock requested for \/var\/www\/owncloud\/data\/files_encryption\/keys\/files\/GoogleDrive\/test_sync\/1.jpg.ocTransferId1974068519.part\/OC_DEFAULT_MODULE\/paolo.shareKey","level":0,"time":"2015-12-18T14:08:50+00:00","method":"PUT","url":"\/remote.php\/webdav\/GoogleDrive\/test_sync\/1.jpg"}
{"reqId":"I+sLX0qeul9DFRxM8sV0","remoteAddr":"MY-IP","app":"files_locking","message":"PASS: Write lock succeeded on \/var\/www\/owncloud\/data\/files_encryption\/keys\/files\/GoogleDrive\/test_sync\/1.jpg.ocTransferId1974068519.part\/OC_DEFAULT_MODULE\/paolo.shareKey","level":0,"time":"2015-12-18T14:08:50+00:00","method":"PUT","url":"\/remote.php\/webdav\/GoogleDrive\/test_sync\/1.jpg"}
{"reqId":"I+sLX0qeul9DFRxM8sV0","remoteAddr":"MY-IP","app":"files_locking","message":"INFO: Incrementing lock type 2 count for \/var\/www\/owncloud\/data\/files_encryption\/keys\/files\/GoogleDrive\/test_sync\/1.jpg.ocTransferId1974068519.part\/OC_DEFAULT_MODULE\/paolo.shareKey","level":0,"time":"2015-12-18T14:08:50+00:00","method":"PUT","url":"\/remote.php\/webdav\/GoogleDrive\/test_sync\/1.jpg"}
{"reqId":"I+sLX0qeul9DFRxM8sV0","remoteAddr":"MY-IP","app":"files_locking","message":"INFO: Write lock requested for \/var\/www\/owncloud\/data\/files_encryption\/keys\/files\/GoogleDrive\/test_sync\/1.jpg.ocTransferId1974068519.part\/OC_DEFAULT_MODULE\/recoveryKey_5aa2c7d5.shareKey","level":0,"time":"2015-12-18T14:08:50+00:00","method":"PUT","url":"\/remote.php\/webdav\/GoogleDrive\/test_sync\/1.jpg"}
{"reqId":"I+sLX0qeul9DFRxM8sV0","remoteAddr":"MY-IP","app":"files_locking","message":"PASS: Write lock succeeded on \/var\/www\/owncloud\/data\/files_encryption\/keys\/files\/GoogleDrive\/test_sync\/1.jpg.ocTransferId1974068519.part\/OC_DEFAULT_MODULE\/recoveryKey_5aa2c7d5.shareKey","level":0,"time":"2015-12-18T14:08:50+00:00","method":"PUT","url":"\/remote.php\/webdav\/GoogleDrive\/test_sync\/1.jpg"}
{"reqId":"I+sLX0qeul9DFRxM8sV0","remoteAddr":"MY-IP","app":"files_locking","message":"INFO: Incrementing lock type 2 count for \/var\/www\/owncloud\/data\/files_encryption\/keys\/files\/GoogleDrive\/test_sync\/1.jpg.ocTransferId1974068519.part\/OC_DEFAULT_MODULE\/recoveryKey_5aa2c7d5.shareKey","level":0,"time":"2015-12-18T14:08:50+00:00","method":"PUT","url":"\/remote.php\/webdav\/GoogleDrive\/test_sync\/1.jpg"}
{"reqId":"I+sLX0qeul9DFRxM8sV0","remoteAddr":"MY-IP","app":"music","message":"update - \/paolo\/files\/GoogleDrive\/test_sync\/1.jpg","level":0,"time":"2015-12-18T14:09:00+00:00","method":"PUT","url":"\/remote.php\/webdav\/GoogleDrive\/test_sync\/1.jpg"}
{"reqId":"I+sLX0qeul9DFRxM8sV0","remoteAddr":"MY-IP","app":"music","message":"update - mimetype text\/plain","level":0,"time":"2015-12-18T14:09:00+00:00","method":"PUT","url":"\/remote.php\/webdav\/GoogleDrive\/test_sync\/1.jpg"}

#### Browser log
The issue can be replicated also with both Internet Explorer and Chrome


This should be all is requested by the template.
Let me know if you need anything else to dig into the issue.
Thanks.

**Comment by PVince81** [comment]
Did you disable encryption on the Google Drive storage ?

I see you have encryption enabled and by default it would encrypt files on Google Drive too, unless you disabled it for that storage in the mount options.

You are saying that files were uploaded directly to Google Drive without going through ownCloud, so the Google Drive should report the correct mime type (unless the files are encrypted...)

**Comment by paolosg** [comment]
Sorry I wasn't too clear on this point.

The issue comes up when uploading files to a Google Drive folder using the desktop sync client (not direclty to GD without going through ownCloud): in this case ownCloud apparently loses the mime type information and files are reported (and thus opened) as text in the OC web interface.

Everything works as expected when uploading (to a GD folder) using the OC web interface: they are encrypted if looked up directly in GD, but they're correctly interpreted and opened in OC.

Writing it down I understand the client's log can be useful. I attach it here.
[oc_client_log.txt](https://github.com/owncloud/core/files/68797/oc_client_log.txt)

**Comment by PVince81** [comment]
@paolosg thanks for the clarification. However the sync client doesn't do anything with the mime type.

The only difference between the web UI and sync client is that the web UI uses different internal endpoints while the sync client uses Webdav. So I suspect that something is wrong with the Webdav endpoints.

**Comment by PVince81** [comment]
Something to verify on 8.2.2 whether it still happens (haven't tried to reproduce this issue yet)

**Comment by PVince81** [comment]
Tested the following, without encryption, on 8.2.2:

1. Go to admin page
1. Setup GDrive storage
1. Open GDrive page
1. Upload a jpg image
1. Go to the files app in the web UI
1. Click the image to open it
1. Check the "data-mime" attribute of that row: it's "image/jpeg"

Redo the steps from scratch but first enable encryption.
Same result.

Works for me. Tested with Chromium 48.

**Comment by PVince81** [comment]
Okay, I read the wrong steps.

Trying again with your comment from https://github.com/owncloud/core/issues/21271#issuecomment-166373434 to upload to GDrive with the sync client.
Since you have encryption enabled, it means the file will be encrypted there too which might get us closer to the issue.

Trying now...

**Comment by PVince81** [comment]
Confirmed on 8.1.5, the uploaded picture has "data-mime" as "text/plain".

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/22408
