### ISSUE TITLE
Directory not syncing if a file with an identical name previously existed

### ISSUE THREAD

**Issue by sukosevato** [owncloud/core#21273]
So I ran into the following issue.

I had a text file named: "A1" (assignment 1).
I wanted to move it into a folder named "A1" because I got more files belonging to the same assignment. So I renamed this file temporarily so I could create a folder name A1 and moved the file into it together with the new files. This all synced without a problem with owncloud.

However, when I started owncloud on another computer, I got syncing errors.

"Not a directory" is the error message that I get. And all files that I had moved into the directory fail to sync. So I renamed the file "A1" into "A1_old" and then got the error messages "No such file or directory" due to the directory "A1" still not existing. I then manually created a folder named "A1" and then owncloud did sync succesfully.

Sounds like a bug to me.

Both system that run the owncloud client are:
- Linux 4.2.5-1-ARCH 2015 x86_64 GNU/Linux
- Owncloud client 2.1.0, Built from Git revision c0c9fb on Dec 8 2015, 12:35:25 using Qt 5.5.1, OpenSSL 1.0.2e 3 Dec 2015

The owncloud server is running: 
- FreeBSD 10.2
- Apache24-2.4.17
- Php55-5.5.30 
- OwnCloud 8.2.1 (stable)

All of them use ZFS as file system.

**Comment by karlitschek** [comment]
This sounds a client issue. Can you reopen this in the client repository please?  Thanks
