### ISSUE TITLE
copyr duplicated in OC_Util and OC_Helper

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#21284]
https://github.com/owncloud/core/blob/450e2f3bd308388e5df01b2b2ea38e6bf16b1c67/lib/private/helper.php#L226-L246

https://github.com/owncloud/core/blob/e01a488b3136ec7b0f2614cd49e4cf1afce1f655/lib/private/util.php#L310-L331

@icewind1991 Is there any chance to combine those two?

**Comment by MorrisJobke** [comment]
@icewind1991 ping ;)

**Comment by icewind1991** [comment]
You linked to the same file twice :smile: 

iirc there is a difference between the two versions in working against oc's filesystem and the local fs

**Comment by MorrisJobke** [comment]
> You linked to the same file twice

Pssst :)

**Comment by MorrisJobke** [comment]
I updated the links
