### ISSUE TITLE
Cannot connect ldaps

### ISSUE THREAD

**Issue by elliott38** [owncloud/core#21306]
I am having issues connecting ownCloud to my ldap server using ldaps. Device syncs fine using standard ldap, but as soon as i add ldaps:// to the server name field and change the port to the correct ldaps port, i get a message at the top of the screen stating "Lost connection to LDAP server" and "Configuration Incorrect" at the bottom of the ldap field.

ownCloud is currently running on a Synology device;

DSM 5.2-5644
ownCloud version - ownCloud 8.2.1

Any help would be greatly appreciated.

**Comment by aspdye** [comment]
Looks like an individual problem with your configuration. Try to ask in the forum (forum.owncloud.org), or find other support options: https://owncloud.org/support/ ;)

There are higher chances to get help, because you may find there people who ever had a similar problem;)
