### ISSUE TITLE
Verify that cron.php is run with correct user

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#21303]
Do something like https://github.com/owncloud/core/blob/d0cb4c9ab3db8dce7c2e31bd45f7e74b9c80345b/console.php#L52-L65 in cron.php

This makes stuff like #19959 not possible anymore - and as you see this was quite hard to debug and detect.

**Comment by MorrisJobke** [comment]
@PVince81 @rullzer @DeepDiver1975 What do you think?

**Comment by RealRancor** [comment]
@MorrisJobke Mhhh, there is already such a check: https://github.com/owncloud/core/blob/v8.2.1/cron.php#L86-L100

**Comment by rullzer** [comment]
> This makes stuff like #19959 not possible anymore - and as you see this was quite hard to debug and detect.

That is not true. That still could have happend then.

**Comment by MorrisJobke** [comment]
This was a false positive. -> closing
