### ISSUE TITLE
Caldav is not compatible with PHP7

### ISSUE THREAD

**Issue by xaviermiller** [owncloud/core#21309]
Hi!

After the upgrade to PHP7, we lost the calender in our Android clients.

see also https://owncloud.org/blog/php-7-is-here-and-owncloud-is-ready/comment-page-1/#comment-71288

**Comment by RealRancor** [comment]
@xaviermiller CalDAV / CardDAV is handled within the issue tracker of the Calendar or Contacts app. At the issue tracker of the calendar app you can find an existing report about that:

https://github.com/owncloud/calendar/issues/1002

**Comment by xaviermiller** [comment]
Sorry, I didn't find this issue before I posted.

The updated sabre file fixes the problem for me.

**Comment by aspdye** [comment]
The Question is wether this also happens with the CalDAV/CardDAV Implementation of the current ownCloud Core Master. If yes, it would be also an Core Problem ;)

**Comment by DeepDiver1975** [comment]
> If yes, it would be also an Core Problem ;)

No - core is php7 ready
