### ISSUE TITLE
Language Issues

### ISSUE THREAD

**Issue by bdwinsalt** [owncloud/core#21305]
OwnCloud does fine to detect the system language, but when changing the language in the personal profile area it does not change the language for OwnCloud entirely.  There is a single section in the admin panel where the AJAX/Cron settings are that shows up in Spanish and that's it.  Haven't tried other languages, but did try all forms of Spanish supported.

My iPad is set to Spanish and it shows up in Spanish fine because of that.  If there was an override to specify a different language that would be right.  The browser isn't always right. :)

**Comment by Xenopathic** [comment]
Fixed in #20993? cc @nickvergessen

**Comment by nickvergessen** [comment]
Yeah should be fixed in 8.2.2 which will be released soon
