### ISSUE TITLE
encryption module not working with fresh installation, no openssl warning

### ISSUE THREAD

**Issue by dl8bh** [owncloud/core#21319]
I installed OC 8.2.1 following the instructions. When I activated the encryption, the " Encryption App is enabled but your keys are not initialized, please log-out and log-in again" does not disappear after logging out/in several times.

**Comment by karlitschek** [comment]
Can you post a full bug report using the issue template please? https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by karlitschek** [comment]
@schiesbn

**Comment by dl8bh** [comment]
I solved the issue, missing openssl.conf for FreeBSD port.
Found the hint when looking into the logfile for this bugreport.
A hint in the UI would have been great, see attached bugreport.

### Steps to reproduce
1. Install OC 8.2.1 on FreeBSD 10.1 with openssl port
2. don't have a openssl.cnf installed
3. enable encryption

### Expected behaviour
Encryption should work without openssl.conf or at least should give some hint, that the openssl installation is the issuie

### Actual behaviour
"Encryption App is enabled but your keys are not initialized, please log-out and log-in again" is shown on every login which misleads a bit when searching the actual problem.

### Server configuration
**Operating system**:
FreeBSD 10.1

**Web server:**
nginx

**Database:**
mysql

**PHP version:**
5.x

**ownCloud version:** (see ownCloud admin page)
8.2.1

**Updated from an older ownCloud or fresh install:**
fresh install
**List of activated apps:**
encryption
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'someinstanceid',
  'passwordsalt' => 'somesalt,
  'secret' => 'somesecret',
  'trusted_domains' => 
  array (
    0 => 'cloud.example.de',
  ),
  'datadirectory' => '/owncloud',
  'overwrite.cli.url' => 'https://cloud.example.de',
  'dbtype' => 'mysql',
  'version' => '8.2.1.4',
  'dbname' => 'owncloud',
  'dbhost' => '192.168.0.3',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'somethingelse',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_smtpmode' => 'php',
  'mail_from_address' => 'owncloud',
  'mail_domain' => 'example.de',
);

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
{"reqId":"z5705jGU9fBSQfwn3M8b","remoteAddr":"2001:6f8:1174::28","app":"encryption","message":"Encryption Library, symmetrical encryption failed no content given","level":3,"time":"2015-12-21T21:31:09+00:00"}
{"reqId":"z5705jGU9fBSQfwn3M8b","remoteAddr":"2001:6f8:1174::28","app":"encryption","message":"Encryption Library couldn't generate users key-pair for \"no user given\"","level":3,"time":"2015-12-21T21:31:10+00:00"}
{"reqId":"z5705jGU9fBSQfwn3M8b","remoteAddr":"2001:6f8:1174::28","app":"encryption","message":"Encryption library openssl_pkey_new() fails: error:0E064002:configuration file routines:CONF_load:system lib","level":3,"time":"2015-12-21T21:31:10+00:00"}
{"reqId":"z5705jGU9fBSQfwn3M8b","remoteAddr":"2001:6f8:1174::28","app":"encryption","message":"Encryption library couldn't export users private key, please check your servers OpenSSL configuration.\"no user given\"","level":3,"time":"2015-12-21T21:31:10+00:00"}
{"reqId":"z5705jGU9fBSQfwn3M8b","remoteAddr":"2001:6f8:1174::28","app":"encryption","message":"Encryption Library:error:2006D080:BIO routines:BIO_new_file:no such file","level":3,"time":"2015-12-21T21:31:10+00:00"}

**Comment by PVince81** [comment]
Setting to enhancement to add a visual hint in the UI when openssl is missing.

@schiesbn
