### ISSUE TITLE
Links to doc in admin.setupcheck open in the same window

### ISSUE THREAD

**Issue by ryno83** [owncloud/core#21317]
### Steps to reproduce
1. Disable something checked by setupchecks.js (for exemple memcache)
2. Open ownCloud admin page
3. See the message about no memory cache enable.
4. The link to the documentation open in the same window

### Expected behaviour
The link should open a new windows (target="_blank") like many other messages on the same page.

**Comment by karlitschek** [comment]
Good catch. Do you want to open a pull request?

**Comment by ryno83** [comment]
Pull Request here #21318

**Comment by PVince81** [comment]
@ryno83 thanks!
