### ISSUE TITLE
Feature Request: restriction per-user for external storage configuration

### ISSUE THREAD

**Issue by joakinen** [owncloud/core#21326]
Is there any way to restrict the user external storage configuration feature on a per-user basis? I would like to make this feature available for my IT staff so that they can connect to new resources but not for standard users which will use only preconfigured connections. The options I see only allow an all-or-none scenario.

Posted in forum as a question [here](https://forum.owncloud.org/viewtopic.php?f=36&t=32117).

**Comment by PVince81** [comment]
This would need a new field where one can select groups that are allowed to configure personal mounts.

**Comment by PVince81** [comment]
PRs welcome.
