### ISSUE TITLE
ubuntu 14.04 server package missing /ocs-provider/

### ISSUE THREAD

**Issue by martin-rueegg** [owncloud/core#21327]
note: as my message from 12.12.2015 to both packaging@owncloud.org and the package maintainer remained unmoderated and unreplied respectively, i hope this issue finds more attention.

-----
Subject: 	ubuntu 14.04 server package missing /ocs-provider/
Date: 	Sat, 12 Dec 2015 17:00:55 +0000

i've been looking for any package related issue tracker but only found this mailinglist. so i hope, it's ok to post it here, and cc the package maintainer listed in the ubuntu package info.

not sure, if i'm the one missing something, but i think the server package for ubuntu 14.04 (and maybe others too) does miss the directory https://github.com/owncloud/core/tree/master/ocs-provider .

following this message, please find the info of my system and how i made the ocs to work,

is there a reason why the files are not included in the owncloud-server package?
if so, would it not make sense to create a package e.g. owncloud-server-ocs and also move the other ocs-related files to this package?
if not, will they be included in a future package release or should i open an issue somewhere?

thanks,
martin.

----

	 # uname -a
	Linux jackal 3.19.0-41-generic #46~14.04.2-Ubuntu SMP Tue Dec 8 17:46:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

	# cat /etc/apt/sources.list.d/owncloud.list
	#deb http://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_14.04/ /
	deb http://download.owncloud.org/download/repositories/stable/Ubuntu_14.04/ /

(i previously used the opensuse-repository [i guess up until 8.1] and then switched to the owncloud repo)

	# dpkg --list | grep owncloud
	ii  owncloud                                    8.2.1-1.1                            all          The ownCloud Server - Private file sync and share server
	ii  owncloud-config-apache                      8.2.1-1.1                            all          The ownCloud configuration for the apache web server
	ii  owncloud-server                             8.2.1-1.1                            all          The owncloud-server package

	# apt-cache show owncloud-server
	Package: owncloud-server
	Source: owncloud
	Version: 8.2.1-1.1
	Architecture: all
	Maintainer: Jürgen Weigert <jw@owncloud.com>
	Installed-Size: 82490
	(...)
	Filename: ./all/owncloud-server_8.2.1-1.1_all.deb
	Size: 22968356
	MD5sum: 4edb416620387f10499a6b12ef8b787c
	SHA1: 0c3fbae0fc7446d07581f25d35f0252b8dbecc4a
	SHA256: 118ad0ba921fd5c092030db9c8fb9eb8a71eff6c7995faef534c0fd216f64e00
	Section: devel
	Priority: optional
	Description: The owncloud-server package
	 .
	 Server internals. For a complete system install package owncloud.
	Description-md5: 9fad35b7290d84c315d51d9ce427d609

	# dpkg-query -L owncloud-server | grep /ocs
	/var/www/owncloud/ocs
	/var/www/owncloud/ocs/v2.php
	/var/www/owncloud/ocs/routes.php
	/var/www/owncloud/ocs/providers.php
	/var/www/owncloud/ocs/v1.php
	/var/www/owncloud/lib/private/db/ocsqliteplatform.php
	/var/www/owncloud/lib/private/ocs.php
	/var/www/owncloud/lib/private/ocs
	/var/www/owncloud/lib/private/ocs/person.php
	/var/www/owncloud/lib/private/ocs/cloud.php
	/var/www/owncloud/lib/private/ocs/config.php
	/var/www/owncloud/lib/private/ocs/privatedata.php
	/var/www/owncloud/lib/private/ocs/result.php
	/var/www/owncloud/lib/private/ocs/corecapabilities.php
	/var/www/owncloud/lib/private/ocs/exception.php
	/var/www/owncloud/lib/private/ocsclient.php
	/var/www/owncloud/lib/public/appframework/ocscontroller.php
	/var/www/owncloud/lib/public/appframework/http/ocsresponse.php

while the `/ocs` directory is installed, the `/ocs-provider` is not. the files are neither included in any other oc package:

	# dpkg-query -L owncloud-config-apache | grep /ocs
	# dpkg-query -L owncloud | grep /ocs

in fact, the files are missing in the installed dir:

	# ls -lad /var/www/owncloud/ocs*
	drwxr-xr-x 2 root root 6 Nov 27 17:24 /var/www/owncloud/ocs

so when calling the web url `https://server/owncloud/ocs-provider/` i get a 404 not found error.

while on [`https://demo.owncloud.org/ocs-provider/`](https://demo.owncloud.org/ocs-provider/) i get the expected json file (currently running ownCloud 8.2.0 (stable))

if i install the files from git

	# mkdir ocs-provider
	# cd ocs-provider/
	# wget https://raw.githubusercontent.com/owncloud/core/v8.2.1/ocs-provider/index.php
	# wget https://raw.githubusercontent.com/owncloud/core/v8.2.1/ocs-provider/provider.php
	# ls -la /var/www/owncloud/ocs-provider/
	total 8
	drwxrwxr-x  2 root root    4 Dec 12 17:50 .
	drwxr-xr-x 17 root root   38 Dec 12 17:49 ..
	-rw-rw-r--  1 root root 1041 Dec 12 17:49 index.php
	-rw-rw-r--  1 root root 2487 Dec 12 17:50 provider.php

and now i can access the service list on
`https://server/owncloud/ocs-provider/`

probably other (ubuntu) packages are affected too.

**Comment by PVince81** [comment]
@jnweiger @cmonteroluque

**Comment by PVince81** [comment]
For OC 8.2, have a look at the stable8.2 branch instead: https://github.com/owncloud/core/tree/stable8.2/ocs-provider
The folder exists there too.

**Comment by PVince81** [comment]
@martin-rueegg thanks for your report.

This folder will be included in future builds of the owncloud-server package.

It seems to be only missing from the Ubuntu package (I didn't check, but that's what you said). On my server I have the openSUSE package for 8.2.2 RC1 and the folder is there.

Note that the absence of this folder should not break any features, as it is only used for future clients that want to query which OCS endpoints exist on this server. Federated shares will still work because OC doesn't not access these when making remote connections.

**Comment by martin-rueegg** [comment]
@PVince81, you're welcome

no, i actually did not say, "only ubuntu packages are affected". i said, that i only checked ubuntu 14.04 package, and others (maybe only ubuntu) packages *might* be affected to.

as i could not find any building scripts, i cannot verify. so i leave that up to the package maintainers to check.

yes, the folder exists in the git repository, on branch 8.2.1 as well as 8.2. however, it is not included in the (ubuntu 14.04) package. so i think, without updating any build-script, also with 8.2.2 it will not automatically be included.

**Comment by jnweiger** [comment]
there seems to be a new folder, that is not yet listed in the *.install files.

**Comment by jnweiger** [comment]
Submitted fix of debian.owncloud-server.install
https://s2.owncloud.com/package/rdiff/ce:8.2/owncloud?linkrev=base&rev=11

@cmonteroluque Build release number 8.2.2-26.1 in https://download.owncloud.org/download/repositories/8.2:/testing/owncloud/ has the fix.

Everything else is post-8.2.2, as just discussed. Okay?

**Comment by PVince81** [comment]
@jnweiger can you double check the 8.1 packages too, just in case ? Git tells me that the folder also exists in stable8.1 (but not stable8)

**Comment by jnweiger** [comment]
Thanks @PVince81 for the hint. Also done for 8.1 https://build.opensuse.org/package/rdiff/isv:ownCloud:community:8.1:testing/owncloud?linkrev=base&rev=77

available for download at https://software.opensuse.org/download.html?project=isv%3AownCloud%3Acommunity%3A8.1%3Atesting&package=owncloud

when rebuilds are done.

**Comment by davitol** [comment]
:+1: tested in the testing urls written by jnweiger and the ubuntu 14.04 server packages for 8.2.2. and 8.1.5 are fixed
