### ISSUE TITLE
Dragging a folder to a share in the web interface works with Chrome but not Internet Explorer or Firefox: Error Unable to upload xxx as it is a directory or has 0 bytes

### ISSUE THREAD

**Issue by aleishman01** [owncloud/core#21329]
### Steps to reproduce
1. Make a publicly shared folder in ownCloud
2. Open the share link (while not logged in)
3. Drag a folder to the share using either Firefox or Internet Explorer

### Expected behaviour
I would expect the folder and its contents to be uploaded to the share

### Actual behaviour
This only works with Chrome.

### Server configuration
Debian Linux 9.0
Linux 3.16.0-4-686-pae on i686

**Web server:**
Apache version 2.4.16

**Database:**
MariaDB: 10.0.20-MariaDB-3

**PHP version:**
PHP 5.6.16-2 (cli)

**ownCloud version:** (see ownCloud admin page)
ownCloud 8.2.1 (stable)

The error message in Firefox is: Error Unable to upload "xxx" as it is a directory or has 0 bytes

I've read many posts that are similar to this but none of the suggestions work.

Is this feature, dragging entire folders into a share, not supported in Internet Explorer and Firefox?

**Comment by PVince81** [comment]
Chrome is the only browser that implement dragging folders, nothing we can do.

Regarding the error message, there is a ticket to improve the message at least: https://github.com/owncloud/core/issues/17788#issuecomment-125265470
