### ISSUE TITLE
Stable branches unit test execution fail

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#21339]
Regression caused by https://github.com/owncloud/core/pull/21235 and https://github.com/owncloud/core/pull/21232

@DeepDiver1975 Any chance that we can get unit test execution properly on those branches on PRs as well?

**Comment by LukasReschke** [comment]
```
13:27:23 ...........................PHP Fatal error:  Class 'OCA\DAV\Connector\Sabre\Directory' not found in /ssd/jenkins/workspace/server-stable8.2-linux/database/sqlite/label/SLAVE/tests/lib/connector/sabre/objecttree.php on line 306
```

Seems only to affect the tests but still……

**Comment by LukasReschke** [comment]
Stable8.1: https://github.com/owncloud/core/pull/21340
Stable8.2: https://github.com/owncloud/core/pull/21341

**Comment by rullzer** [comment]
Both merged.
