### ISSUE TITLE
Agree and document that we want "proxy_request_buffering off" in nginx_configuration.html?

### ISSUE THREAD

**Issue by guruz** [owncloud/core#21338]
This is a semi-new nginx feature that avoids spooling the upload chunk first to nginx and only then forwarding it to ownCloud. Probably good for our goal of avoiding timeouts, especially if we would directly forward a chunk to an external storage or things like virus scanning and checksuming are done on-the-fly..

Disadvantage: More PHP processes get "used" because nginx immediatly uses them instead of waiting until the chunk is really there (from a slow sending client)

FYI @fossexplorer @PVince81 @RealRancor 

https://www.nginx.com/blog/nginx-plus-r6-released/
http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_request_buffering
https://doc.owncloud.org/server/8.2/admin_manual/installation/nginx_configuration.html

**Comment by RealRancor** [comment]
@fossxplorer is probably right. Don't know if @josh4trunks can say something to this?

**Comment by josh4trunks** [comment]
I'm not familiar with this, @guruz can you confirm this will actually make a difference for owncloud?

This statement makes it seem like this setting isn't taken into account if the client sends chunked HTTP/1.1
``When HTTP/1.1 chunked transfer encoding is used to send the original request body, the request body will be buffered regardless of the directive..``

**Comment by PVince81** [comment]
Note, this symptom (the buffering) was also discovered and discussed here: https://github.com/owncloud/core/issues/9832#issuecomment-162806896

**Comment by fossxplorer** [comment]
@josh4trunks I noticed this pretty good feature when it was introduced with Nginx 1.7.11 a while ago, but haven't had time to test it out with ownCloud scenario.
But related to proxy_request_buffering, the documentation states  "When HTTP/1.1 chunked transfer encoding is used to send the original request body, the request body will be buffered regardless of the directive value unless HTTP/1.1 is enabled for proxying. 
IIRC,

**Comment by josh4trunks** [comment]
@fossxplorer I don't have HTTP/1.1 enabled between nginx and php-fpm (it's HTTP/1.0 by default), and sharing works for me.
But, I do remember the thread where there was an issue with HTTP/1.0, maybe it was multiple webserver layers though which isn't what we're talking about here. that's why I purposely didn't quote that part of the docs, thinking it wasn't relevant by default.

**Comment by guruz** [comment]
(Neither web browsers nor the ownCloud client use HTTP chunked _upload_/_POST_/_PUT_ so really no worry here)

**Comment by josh4trunks** [comment]
great, I don't know enough about this to thumbs up it. but it sounds like a good idea.
when I get a chance I'll update my nginx and try this out =]

**Comment by fossxplorer** [comment]
@josh4trunks IIRC HTTP/1.1 and oC "issue" was only limited to Nginx being used as a reverse proxy. In my setup (where i use Nginx as both reverse proxy and web server (the backends) ) i had to tell reverse proxy to use HTTP/1.1 after a tip from @LukasReschke on IRC.
It seems for me you are using Nginx just as a webserver. 
But the buffering switches were added for both type of usage, hence the link to fastcgi_request_buffering in my previous post. 
I'll try to test this out as well.

**Comment by mew1033** [comment]
I'm working on setting up ownCloud on apache behind an nginx reverse proxy. I added the proxy_request_buffering off; directive, thinking it would help optimize uploads. Testing on a local gigabit network, I was getting about 250 Mb/s. When I got rid of that setting, allowing proxy_request_buffering to be on by default, performance shot back up to ~950Mb/s.

At least for the ownCloud on Apache behind an nginx reverse proxy scenario, disabling proxy request buffering is a Bad Idea™.

**Comment by guruz** [comment]
@mew1033 Thanks

The goal of ```proxy_request_buffering ``` is for scenarios with high latency to not get into timeout situations.
So that would be a different benchmark, e.g. have your server in US but test uploads from Europe

**Comment by guruz** [comment]
I had actually added ```fastcgi_request_buffering off;``` to https://github.com/owncloud/documentation/wiki/ownCloud-9.x-nginx-example-configuration

(Note the proxy_ vs fastcgi_ .. but same principle?)

**Comment by settermjd** [comment]
@guruz is this going ahead?

**Comment by guruz** [comment]
@settermjd Wow, for some reason https://github.com/owncloud/documentation/wiki/ownCloud-9.x-nginx-example-configuration is deleted?

I still think it should be in the documentation.

**Comment by josh4trunks** [comment]
nginx configuration was removed from the wiki because on multiple occasions people made incorrect changes without anyone reviewing them. It is in the standard ownCloud documentation as it was previously.

**Comment by settermjd** [comment]
Closing as the configuration is in [the NGINX documentation example](https://github.com/owncloud/documentation/blob/master/admin_manual/installation/nginx_configuration.rst) already.

**Comment by guruz** [comment]
merci!
