### ISSUE TITLE
EventSource support for searching

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#21348]
Just thinking whether it would make sense to have EventSource support on the search endpoint at https://github.com/owncloud/core/blob/726f7e5fa8c5414a3f4ecff583a43356b78bfa92/core/search/ajax/search.php 

Then we could show first results as soon as we have some instead of waiting for the completion of the complete search. Would probably result in a way better UX.

Thoughts? 

@owncloud/search @DeepDiver1975 @jancborchardt @karlitschek

**Comment by DeepDiver1975** [comment]
My natural answer to requirements is: use pagination

**Comment by PVince81** [comment]
Yeah, pagination sounds better.

**Comment by jancborchardt** [comment]
Yeah, whatever achieves the best result for UX. If pagination does that, go for it. :)

**Comment by butonic** [comment]
ref https://github.com/owncloud/core/issues/10077

**Comment by DeepDiver1975** [comment]
So let's close this then - THX
