### ISSUE TITLE
[Feature Request] limit bandwidth

### ISSUE THREAD

**Issue by tessus** [owncloud/core#21344]
As  suggested in the forum post "[limit bandwidth on server?](https://forum.owncloud.org/viewtopic.php?f=36&t=32072)", I'd like to open a feature request to limit the bandwidth on the server.

There might be other options available, but all have issues: 
* `mod_ratelimit` does not work
* `mod_cband` hasn't been developed for 10 years, is not Apache 2.4 compatible and has a few major bugs

Maybe there is a way to code this in PHP, in which case this feature would work on all supported web servers.

**Comment by karlitschek** [comment]
There is no good way to do this in PHP. This is something that is usually done one the webserver or OS level. Why does mod_ratelimit not work? Seems to be the tool that everybody is using

**Comment by tessus** [comment]
@karlitschek 
>  Why does mod_ratelimit not work? Seems to be the tool that everybody is using

I seriously doubt that. `mod_ratelimit` limits the bandwidth per connection (client). This means this is **not** a server based limit.

It's sad that you just closed this without further discussion.

**Comment by karlitschek** [comment]
sure. I can open it again. But I'm not sure if discussion helps here. bandwidth can be controlled on the Desktop client side and globally on the server by the webserver. Additionally there are ways to do this with ipchains in Linux servers. There is no good way to implement this on the PHP side.

**Comment by tessus** [comment]
The problem is that you cannot do this reliable on the web server (as I pointed out in my first post). The other problem is that there are circumstances where it isn't possible to use ipchains or other Linux tools either. I've explained it in the forum post. Sorry that I haven't added here as well.

It's a problem, if you have several IP addresses assigned to one physical interface. In modern Linux distros, those virtual interfaces are not even named eth0:0 eth0:1 ... anymore. You have one interface eth0 (if not the consistent interface naming schema applies) and that's it.
This means, if you use tc, ipchains, or whatnot, it will aplly to **ALL** interfaces.

Now, you run different domains on different IPs and start using tc (or wondershaper). Bad idea.

**Comment by Xenopathic** [comment]
@tessus If you are looking to rate limit on a particular IP, you can do it with iptables pretty easily:

    iptables -d 192.168.0.x -m limit ...

TBH that's a pretty bad idea though, it makes DoSing your server really easy... that's why per-client limits are almost always a better option, but they are handled at the web server level.

**Comment by tessus** [comment]
@Xenopathic yep, this is another reason why maybe a server based rate limit would be beneficial. In my forum post I said:

*The oc sync client has bandwidth management, thus I hoped the server would too.*

Then @RealRancor suggested to open a feature request.

**Comment by Xenopathic** [comment]
PHP cannot handle per-client rate limiting (each request is a separate process, tracking the number of requests coming in would take HUGE DB writes and/or memcache races, ie not worth it). Instead, the web server is in the perfect position to handle that. From the comments above it seems that `mod_ratelimit` can do it, unfortunately I'm in no position to advise since I use nginx which has built-in per-client rate limiting: http://nginx.org/en/docs/http/ngx_http_limit_req_module.html

**Comment by Xenopathic** [comment]
As for 'server based rate limit', that's what the iptables rule that I posted is for...

**Comment by tessus** [comment]
@Xenopathic I never asked for per-client rate limiting, but a server based rate limit. and as you mentioned earlier, the iptables approach is not the best.

The question now is: is a server wide rate limit possible with PHP?

If not, the feature request can be closed. If yes, we can discuss the options.

**Comment by Xenopathic** [comment]
@tessus *Any* global rate limiting is vulnerable to DoS attacks, regardless of where it occurs. If you block traffic at the firewall (iptables) level, or right at the application level in PHP, it doesn't matter - an attacker can send more traffic than the limit and no legitimate clients will be able to connect. Hence the 'bad idea'.

**Comment by tessus** [comment]
@Xenopathic I'm not quite sure your statement makes sense.

Let's say you server has a 100MBit/s (up/down) connection. Now you have a 1000 clients trying to download something. It doesn't matter, if you limit the owncloud instance to 80Mbit/s, in either case the download will most likely come to a crawl. But with the limit in place, people can still log into the server via ssh or do something else apart from using owncloud.

My physical connection bandwidth is also a limit. If you set the limit lower it might happen a bit earlier, but that's it. It's not that you are only vulnerable to DoS attacks when using a server bandwidth limit.

**Comment by Xenopathic** [comment]
@tessus In your 1000 clients scenario, if the bandwidth were limited at the PHP level, all 1000 clients would still repeatedly attempt to connect, causing web server processes to do work and the system to buffer the incoming data, before PHP even has a chance to see it. Thus, all 100Mbit/s is consumed by ownCloud clients even though 20Mbit/s of that is getting rejected by PHP. If, on the other hand, you perform this throttling at the firewall level with iptables, TCP will notice the dropped packets and scale back until the server can cope (consuming 80Mbit/s and no more). It should be pretty clear at this point that throttling can *only* occur at the firewall level, not at the application level.

And so, back to the *very first comment I wrote on this issue*:

   iptables -d 192.168.0.x -m limit ...

**Comment by tessus** [comment]
@Xenopathic hmm, but this only means that PHP just does not have a way of limiting bandwidth **correctly**. b/c if PHP were doing it correctly, it would not allow further connections.

hereby you basically told me that PHP cannot throttle/limit bandwidth, which means this feature request is impossible to implement.

I truly hoped that this discussion would reveal that PHP had a workable solution.

**Comment by Xenopathic** [comment]
The first control PHP has over the connection is when the script starts to get parsed, by which point a connection has already been established by the web server and it's too late. The web server can do the throttling itself, but for bandwidth throttling you really need to do it at the firewall level.
