### ISSUE TITLE
[Debian Packaging] Change php5-cgi dependency to php5-fpm or php5-cgi

### ISSUE THREAD

**Issue by robin24** [owncloud/core#21342]
As of version 8.2.2-1.1, the Debian owncloud-server package depends on php5-cgi.
However, this package is not required on many systems, because other software (e.g. php5-fpm) is in use. Therefore, could you please change this dependency to 'php5-cgi | php5-fpm' so that users are not forced to install php5-cgi unnecessarily?
Thanks!

**Comment by RealRancor** [comment]
@jnweiger

**Comment by SebastianS90** [comment]
I can confirm that owncloud runs perfectly with php5-fpm and nginx or apache. Please don't force us to install the unnecessary php5-cgi. Thanks!

**Comment by PVince81** [comment]
@jnweiger @DeepDiver1975 @karlitschek @cmonteroluque

**Comment by McNetic** [comment]
In fact, neither php5-cgi nor php5-fpm are required. Owncloud is also fine with mod_php.

**Comment by MrFloppy** [comment]
Please fix that, as I am not able to update at the moment :(.

**Comment by jnweiger** [comment]
The php5-cgi requirement was added to avoid an otherwie implicit hard requirement on apache.
I am changing to php5-cgi | php5-fpm | libapache2-mod-php5
That should do the trick.

**Comment by jnweiger** [comment]
Will be fixed in 8.2.3 / 9.0

**Comment by cmonteroluque** [comment]
@jnweiger fixed?

**Comment by jnweiger** [comment]
Fixed for DEB packages. I have not found a solution for RPM. But that was not requested here.

closing.
