### ISSUE TITLE
Get CI running on forks + older branches

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#21346]
We have now successfully managed to break different master and stable unit tests by not executing the tests properly against forks or older branches in under 24 hours.

Ref https://github.com/owncloud/core/issues/21345 and https://github.com/owncloud/core/issues/21339

cc @DeepDiver1975

**Comment by DeepDiver1975** [comment]
My statement is clear on this: reading helps!

Why are prs with fail status merged?

**Comment by RealRancor** [comment]
Ref: https://github.com/owncloud/core/issues/19885

**Comment by PVince81** [comment]
This ticket was already raised for CI on forks: https://github.com/owncloud/core/issues/19885

**Comment by MorrisJobke** [comment]
Duplicate of #19885
