### ISSUE TITLE
8.2.2 not released for ubuntu 15.10 repo

### ISSUE THREAD

**Issue by SchroSct** [owncloud/core#21354]
http://download.owncloud.org/download/repositories/stable/Ubuntu_15.10/ Still contains owncloud_8.2.1-3.1_all.deb 
while http://download.owncloud.org/download/repositories/stable/Ubuntu_15.04/ has up to owncloud_8.2.2-1.1_all.deb.

**Comment by RealRancor** [comment]
cc @jnweiger

**Comment by PVince81** [comment]
@dragotin @cmonteroluque

**Comment by PVince81** [comment]
Looks like it was built in testing http://download.owncloud.org/download/repositories/8.2:/testing/Ubuntu_15.10/ but not moved/transferred to stable ?

**Comment by cmonteroluque** [comment]
See pending result in https://github.com/owncloud/core/issues/21327 . It just needs to be published, in the meantime, the packages in the testing repository should do the trick

**Comment by bjmi** [comment]
Interestingly https://download.owncloud.org/download/repositories/stable/xUbuntu_15.10/ contains 8.2.2

**Comment by Amgine0** [comment]
Bump?

**Comment by menaceone** [comment]
It seems we have to wait for 8.2.3
Btw. what is the difference between the Ubuntu and xUbuntu repository? 
is it secure to change between these two repos?

greetings

**Comment by PVince81** [comment]
@jnweiger any update ?

**Comment by RealRancor** [comment]
> Btw. what is the difference between the Ubuntu and xUbuntu repository? 

Both containing exactly the same packages.

AFAIK the xUbuntu repository is just "legacy" as people thought in the past that this Repos is only for http://xubuntu.org/. Howeverwhere the "x" was just a placeholder for all Ubuntu flavors like Ubuntu, Kubuntu, Lubuntu and so on.

**Comment by jnweiger** [comment]
Reruning ***bin/publish_ce 8.2 Ubuntu_15.10*** did the trick. I'd love to pass on this 'secret knowledge' so that there is less waiting on Juergen to return from vacation. sorry for the delay. I see no error why the original publishing in December published all except 15.10.

**Comment by jnweiger** [comment]
The ***x*** in xUbuntu should go away. As @RealRancor explained, it was once a good thing, now only creates confusion. If packages exist in both, they are identical.
