### ISSUE TITLE
Details view loads twice on open

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#21353]
When I click on the share action the sharedialog nicely opens.

However the share view is rendered twice. I noticed this when looking at the network console. Since all the avatars are loaded twice.

Also when you set a breakpoint in the `sharedialogshareelistview.js` render function you'll see that it gets called twice. However when using the stack trace I'm unable to determine why.

Must be some dark js magic going on somewhere.

OC: master
browser: firefox and chromium

CC: @PVince81 @blizzz @owncloud/javascript

**Comment by PVince81** [comment]
The list view might be rendered twice, yes. First empty because the data isn't there, and then again after the data is fetched.

In general it would be more correct to not render any of the subviews and show a single spinner. And only after the data was fetched, render the subviews.

**Comment by rullzer** [comment]
The data is there... else it would not load the avatars ;)

**Comment by PVince81** [comment]
not reproducibe on master 10.0
