### ISSUE TITLE
Update from 8.2.1 to failed 8.2.2: Maintenance mode is kept active after update success!

### ISSUE THREAD

**Issue by tuxayo** [owncloud/core#21358]
Yesterday I triggered the migration via the webpage (after having updated the package) and it seemed to have succeeded but the server stays in maintenance mode.
I just trigger to rerun the migration from the command line:

```
Set log level to debug - current level: 'Debug'
Checking whether the database schema can be updated (this can take a long time depending on the database size)
Checked database schema update
Checking updates of apps
Checked database schema update for apps
Updating database schema
Updated database
Disabled 3rd-party app: contacts
Update successful
Maintenance mode is kept active
Reset log level to 'Debug'
```

I had files that were kept locked and I wanted to upgrade to fix this problem.

**List of activated apps:**
  - activity: 2.1.3
  - encryption: 1.1.0
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - updater: 0.6

#### ownCloud log
The original update occurred 2015-12-22 around [14:00-16:00] \(i can't find the exact time in the logs...)

The second try was at 2015-12-23T14:48:06+00:00

http://sebsauvage.net/paste/?1f4d9423fd51c859#+aN0weZngjYgUBxQJ0ETPb60xiiRaTZ5erZ9jU1xkx0=

**Comment by karlitschek** [comment]
@PVince81 any idea?

**Comment by rullzer** [comment]
The first time sounds like a bug.
The second time is expected behaviour. If the system is in maintenance mode an upgrade will not enable it afterwards.

run: `./occ maintenance:mode --off`

**Comment by tuxayo** [comment]
thanks, `maintenance:mode --off` did the job :-)

As it would be hard to try to reproduce and investigate if I'm was the only one concerned, I think I can close the issue.

**Comment by RealRancor** [comment]
> The second time is expected behaviour. If the system is in maintenance mode an upgrade will not enable it afterwards.

Exact. This behavior is also documented at https://doc.owncloud.org/server/8.2/admin_manual/maintenance/package_upgrade.html and various other places.

**Comment by tuxayo** [comment]
@RealRancor If I understand the doc, everything was expected (especially the first time when the upgrade actually took place)
