### ISSUE TITLE
Download-Link (owncloud-latest.tar.bz2) is outdated again

### ISSUE THREAD

**Issue by golderweb** [owncloud/core#21355]
The Download-Link for latest version is broken again (like this Issue
#21258   owncloud-latest.tar.bz2 Download-Link is outdated). It furthermore points to 8.2.1.

I think link update should be done more or less automatically in the release process.

**Comment by rullzer** [comment]
ping @cmonteroluque @karlitschek

**Comment by karlitschek** [comment]
what exactly is the full link that is broken?

**Comment by rullzer** [comment]
Good question ;) https://download.owncloud.org/community/owncloud-latest.tar.bz2 seems to point to 8.2.2

**Comment by golderweb** [comment]
Yes, it seems like somebody have fixed it in the last 1.5 hours. But the initial issue, that there is no automatism to update this link, persists. 8.2.2 was announced yesterday.

**Comment by karlitschek** [comment]
O.K. Sometimes it takes while until the mirror sync completely.
