### ISSUE TITLE
error installing rpm 7.0.12 on SLES11SP4

### ISSUE THREAD

**Issue by asvetter** [owncloud/core#21361]
When installing owncloud rpm from build.opensuse.org thefollowing error is thrown:

1 package to upgrade.
Overall download size: 25.7 MiB. After the operation, 136.0 KiB
will be freed.
Continue? [y/n/? shows all options] (y):
Installing: owncloud-7.0.12-1.1 [error]
Installation of owncloud-7.0.12-1.1 failed:
(with --nodeps --force) Error: Subprocess failed. Error: RPM fai
led: owncloud update: Checking for running Apache
owncloud-server: installing upgrade ...
owncloud: occ maintenance:mode --on
Maintenance mode enabled
/var/tmp/rpm-tmp.68564: line 26: /run/occ_maintenance_mode_durin
g_owncloud_install: No such file or directory
error: %pre(owncloud-7.0.12-1.1.noarch) scriptlet failed, exit s
tatus 1
error:   install: %pre scriptlet failed (2), skipping owncloud-7
.0.12-1.1

**Comment by karlitschek** [comment]
@jnweiger

**Comment by asvetter** [comment]
/run does not exist on SLES11. Use /var/run.
I used  a symlink as workaround.

**Comment by PVince81** [comment]
Old issue, likely solved already. If still happening with recent packages, please reopen.
