### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Bouzeghoub** [owncloud/core#21366]
Hi,
Updating ownCloud to version 8.2.1, this may take a while.

Preparing update
Set log level to debug - current level: "Warning"
Turned on maintenance mode
Exception: Updates between multiple major versions and downgrades are unsupported.
The update was unsuccessful. Please report this issue to thed downgrades are unsupported.

**Comment by RealRancor** [comment]
Please use the search on top of this repository before creating new issues. With that you will find plenty of duplicates describing your problem.

Then see this FAQ how to correctly upgrade: https://forum.owncloud.org/viewtopic.php?f=17&t=32087

**Comment by Bouzeghoub** [comment]
Hi,
Thank you so mush.




De :    RealRancor <notifications@github.com>
A :     owncloud/core <core@noreply.github.com>
Cc :    Bouzeghoub <redouane.bouzeghoub@mobilis.dz>
Date :  24/12/2015 11:47
Objet : Re: [core] Update (#21366)



Please use the search on top of this repository before creating new 
issues. With that you will find plenty of duplicates describing your 
problem.
Then see this FAQ how to correctly upgrade: 
https://forum.owncloud.org/viewtopic.php?f=17&t=32087
?

**Comment by RealRancor** [comment]
@Bouzeghoub As this is no bug in oC feel free to close this issue on your own by using the close button below the comment field.

**Comment by RealRancor** [comment]
Ref: https://github.com/owncloud/core/issues/21367 to remove the misleading text that this should be reported here.
