### ISSUE TITLE
CalDAV + CardDAV Backend = ActiveSync Protocol

### ISSUE THREAD

**Issue by aspdye** [owncloud/core#21369]
Hi there,

With adding CalDAV and CardDAV Backends into the core, it should be possible to add an ActiveSync functionality, syncing CalDAV and CardDAV ;)

Nice piece of software for realizing that: https://z-push.org/
A project also using ownCloud with Z-Push (for Calendar, Contacts from ownCloud and IMAP from its own server): https://mailinabox.email

**Comment by karlitschek** [comment]
pull requests welcome :-) Preferable as a standalone app for now

**Comment by aspdye** [comment]
Then I have something to do between the years ;)

**Comment by Xenopathic** [comment]
A Z-push app for ownCloud would actually be really cool - Z-push is rather awkward to configure by itself

**Comment by aspdye** [comment]
The 2 backend files are already there: 
https://github.com/aspdye/ownPush/tree/master/backends
(Taken from Mail-in-a-Box)

If you copy them into your z-push instance, ActiveSync should (and does) work. Im now working for an automatic installation - and maybe an frontend (if needed).

**Comment by chrisb86** [comment]
Any news on this topic?

**Comment by DeepDiver1975** [comment]
This is Open Source! Build it!

**Comment by aspdye** [comment]
@chrisb86 you are able to Setup Zpush with downloading it and use the backends Provided in the ownPush Repository. After that you are able to config it Manually. I will take a Look at automation soon :wink:
