### ISSUE TITLE
Remove wrong/misleading text if major version was skipped.

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#21367]
There is currently a wave of duplicate created issues about the "Exception: Updates between multiple major versions and downgrades are unsupported" message here at github.

I think a main problem here is, that the text afterwards is telling "The update was unsuccessful. Please report this issue to the ownCloud community". This is plainly wrong as that issue don't need to be reported here, instead the user just needs to do a correct upgrade path.

**Comment by RealRancor** [comment]
Refs: https://github.com/owncloud/core/issues/21366, https://github.com/owncloud/core/issues/20640, https://github.com/owncloud/core/issues/19910, https://github.com/owncloud/core/issues/20732, https://github.com/owncloud/core/issues/20813, https://github.com/owncloud/core/issues/20974, https://github.com/owncloud/core/issues/20660 and a lot more.

**Comment by RealRancor** [comment]
Another one: https://github.com/owncloud/core/issues/21386

**Comment by PVince81** [comment]
Maybe we should change the text to "please **don't** report" :wink: 
I agree with you @RealRancor

**Comment by jernst** [comment]
In this error message, please also report the version numbers in question. Something like "you attempted to upgrade from version a.b.c to d.e.f. However, upgrades are only supported from version g.h.i onwards. To get to that version, use a previous version of ownCloud." (I note the code has the version numbers right there, they just need to be added to the error message.)

**Comment by MorrisJobke** [comment]
Fix for this is in #22186
