### ISSUE TITLE
GUI broken because of CSP

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#21362]
I haven't been able to use the GUI of my master instance for a couple of weeks because of CSP errors which block the loading of resources.

### Env
Apache 2.4.17
PHP-FPM 5.6

### Browser
Chromium, Firefox

Here is the first thing which breaks down
```
Error: call to Function() blocked by CSP
OC.L10N._generatePluralFunction()
 l10n.js:119
OC.L10N.register()
 l10n.js:75
<anonymous>
```

Then it's
```
downloadable font: download not allowed (font-family: "Open Sans" style:normal weight:300 stretch:normal src index:2): content blocked source: https://domain.com/core/fonts/OpenSans-Light.woff
```

followed by

```
Refused to load the image 'https://domain.com/core/img/favicon-touch.png' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.
```

#### First analysis

This commit is responsible: https://github.com/owncloud/core/commit/7b9bc721e998096220019ab462d4ac51f04a667c

The CSP is incomplete and doesn't have any policy for fonts or images.

Why is it working with mod_php and not PHP-FPM?

**Comment by karlitschek** [comment]
strange. works for me.
@LukasReschke any idea?

**Comment by oparoz** [comment]
For me, this commit is what killed it:
https://github.com/owncloud/core/commit/7b9bc721e998096220019ab462d4ac51f04a667c

**Comment by LukasReschke** [comment]
@oparoz What OS do you use? Or more precisely: Where do you get your Apache from? Also can you try https://github.com/owncloud/core/pull/21220?

**Comment by oparoz** [comment]
> Where do you get your Apache from

Compiled from source

>  Also can you try #21220?

I did try to use setifempty when I saw that the rule was for Apache 2.2, but I got the same result.

To me, the error message is quite clear. There is no policy for `img-src` or `font-src` and the fallback `default-src 'none'`does not work.

**Comment by butonic** [comment]
same here ... index.php returns the csp header twice:
```
Content-Security-Policy:default-src 'none'; style-src 'self' 'unsafe-inline'; script-src 'self'
Content-Security-Policy:default-src 'none';script-src 'self' 'unsafe-eval';style-src 'self' 'unsafe-inline';img-src 'self' data: blob:;font-src 'self';connect-src 'self';media-src 'self';frame-src 'self'
```

**Comment by LukasReschke** [comment]
Fixed with https://github.com/owncloud/core/pull/21538#event-509606360

**Comment by oparoz** [comment]
Thanks!
