### ISSUE TITLE
[Feature Request] Have secondary default application

### ISSUE THREAD

**Issue by bdwinsalt** [owncloud/core#21375]
I am working on a project that is going to initially inform the user of something.  Once they accept it, it is going to send them to the Files application.  I was thinking it might be a good idea to add a secondary default location.  Say for instance the user already has seen that page, they then go straight to the secondary default.  Not everyone defaults to the Files application.

I know I can achieve my goals without it working this way, but I think it would be beneficial to others in the long run.  This could also serve as a secondary default in case the primary default application is buggy.

**Comment by RealRancor** [comment]
Hi,

such edge-use cases are probably better implemented in a separate app.

**Comment by RealRancor** [comment]
Just an additional hint to that:

> This could also serve as a secondary default in case the primary default application is buggy.

Thats already possible with the defaultapp config option:

> You can use a comma-separated list of app names, so if the first app is not enabled for a user then ownCloud will try the second one, and so on. If no enabled apps are found it defaults to the Files app.

https://doc.owncloud.org/server/8.2/admin_manual/configuration_server/config_sample_php_parameters.html#user-experience
