### ISSUE TITLE
php occ files:scan leads to [InvalidArgumentException]

### ISSUE THREAD

**Issue by gfkpth** [owncloud/core#21374]
I want to rescan the files for one user, but I cannot use "sudo -u www-data php occ files:scan USERNAME" (it does not work with --all either). Instead of scanning files, this just throws the following error:
 [InvalidArgumentException]                               
  There are no commands defined in the "files" namespace. 

Also "... occ list" does not provide the files:scan command at all, so I wonder if this command is still available or if I am doing anything wrong.

I just upgraded to owncloud 8.2.2.2, but I don't know if the problem applied before, as I haven't used the files:scan command in quite a while.

**Comment by gfkpth** [comment]
For some recason this issue went away after enabling and disabling maintenance mode.
Although the scan couldn't be completed (will look into this separately), this at least allowed the occ files:scan to run.

Not sure if the need for switching maintenance on and off is intended or if it is a problem with my setup, but at least the workaround seems simple enough (once you think of trying it).

If this is intended behaviour, feel free to close this ticket.

**Comment by DeepDiver1975** [comment]
Quite as expected. Only a limited list of commands is available in maintenance mode.
