### ISSUE TITLE
Feature Request: Sharing full folder path

### ISSUE THREAD

**Issue by filipjandura** [owncloud/core#21376]
Hi, is there any chance to implement functionality for sharing folder with it's full hierarchy path? I read some issues about permission like [Allow different permissions for Subfolder](https://github.com/owncloud/core/issues/4579) but it is not what i really need. Here is an example:

parentFolder1
-childFolder11
-childFolder12

### Actual behaviour
I share childFolder11 to user 'user1' and he can see under his root folder:

childFolder11

### Expected behaviour
I share childFolder11 to user 'user1' and next to sharing permissions i can check/uncheck checkbox with label like 'Share full hierachy' or 'Share full path'. After that 'user1' can see under his root folder

parentFolder1
-childFolder11

however he cannot see childFolder12.

**Comment by Yamakasi** [comment]
This is a ery old and known "issue".

I think it won't be fixed as it's not needed and not doable it seems because of the complexibility. just use proper groups and multiple shares.

**Comment by filipjandura** [comment]
Thanks for your answer. I'll try reorganize my folder structure. I hope that feature will be implemented in some time.
