### ISSUE TITLE
OSX Webdav share, still no upload, folder add, etc

### ISSUE THREAD

**Issue by Yamakasi** [owncloud/core#21379]
It's still not possible in OSX to add a folder for a mounted webdav share or copy a file to it.

Is there any fix or workaround for this yet ?

**Comment by DeepDiver1975** [comment]
Which version are you using?

**Comment by Yamakasi** [comment]
OSX El Cpatain 10.11.2
Owncloud 8.2.2.2

**Comment by MorrisJobke** [comment]
> It's still not possible in OSX to add a folder for a mounted webdav share or copy a file to it.

Can I ask you to describe this more detailed? What webdav mount are you referring to? An files_external mount inside ownCloud or a webdav mount inside Finder where the webdav refers to an ownCloud instance?

**Comment by Yamakasi** [comment]
Hi,

As webdav mount in Finder to index.php/webdav/

**Comment by MorrisJobke** [comment]
> As webdav mount in Finder to index.php/webdav/

But the URL should end with `remote.pgp/webdav/`. Or is this just a typo?

**Comment by Yamakasi** [comment]
But is this only .pgp for finder ? The URL is simply shown on the left
bottom of a useraccount.

2016-01-02 22:27 GMT+01:00 Morris Jobke <notifications@github.com>:

**Comment by MorrisJobke** [comment]
> But is this only .pgp for finder ? The URL is simply shown on the left
> bottom of a useraccount.

Sorry - was a typo: I meant `remote.php/webdav/` of course. Yes the bottom left value. Let me test this with 8.2.2.

**Comment by MorrisJobke** [comment]
I just checked this with Finder and ownCloud 8.2.2 - works as expected. I can create a folder, the folder then is also visible via ownCloud web UI and there are no error messages in the log file.

@Yamakasi I don't think that this is a general ownCloud problem but rather a setup issue. As this is the bug tracker and not a support forum I would kindly ask you to ask for help in the forums https://forum.owncloud.org

Also check you web servers logs, owncloud logs and test if this work with other clients (i.e. owncloud client, other webdav apps,...) to rule out that some more general problems exists (and it's really limited to finder).

Thanks

**Comment by Yamakasi** [comment]
Hi,

Which OSX version did you test ?

I'm sure it's not setup issue, it has been there before in the past, thi
issue.

Thanks!

2016-01-04 9:23 GMT+01:00 Morris Jobke <notifications@github.com>:

**Comment by MorrisJobke** [comment]
> Which OSX version did you test ?

10.11.2

**Comment by Yamakasi** [comment]
Maybe you can explain what you think there could be different in setup ?
OSX and OwnCloud are both kinda basic in that case.

2016-01-05 8:29 GMT+01:00 Morris Jobke <notifications@github.com>:

**Comment by MorrisJobke** [comment]
> Maybe you can explain what you think there could be different in setup ?

We don't know anything about your architecture and used software. Therefore it is proved that it works on many different setups. As this is the tracker where developers will track open reproducible issues it's hard to figure out first if the setup is done right. Therefore I asked you to describe your setup in the forums and ask for help there first. There are many experienced people that can help to properly setup an instance - maybe there is only a small detail missing.

You just stated that it is not working.

If you are really sure, it is a problem within owncloud: describe your issue using the issue template https://github.com/owncloud/core/blob/master/issue_template.md

It's also essential to first test if everything is working fine by using a different client otherwise the problem can be everywhere in between your OS X and the server.

**Comment by Yamakasi** [comment]
Yes understood, other clients just work fine, Windows ones. I have one OSX
at the moment and moved away back the days as other webdav software worked
OK with this OSX machine and OwnCloud didn't and there was spoken it was an
OSX issue which Apple needed to fix, which I doubt. People on IRC are still
saying so I'm lost there. I will checkout the forums.

Thanks

2016-01-05 10:16 GMT+01:00 Morris Jobke <notifications@github.com>:

**Comment by MorrisJobke** [comment]
> Yes understood, other clients just work fine, Windows ones. I have one OSX
> at the moment and moved away back the days as other webdav software worked
> OK with this OSX machine and OwnCloud didn't and there was spoken it was an
> OSX issue which Apple needed to fix, which I doubt. People on IRC are still
> saying so I'm lost there. I will checkout the forums.

If you tested all of this, then feel free to post a full issue description. But with your given info above it's simply guessing ;)
