### ISSUE TITLE
Connection Closed Error

### ISSUE THREAD

**Issue by TheOtterslider** [owncloud/core#21380]
Here's some details:

Client - 2.1.0. build 2944 (Mac 10.11.3)
Server - Upgraded yesterday to 8.2.2 (on CentOS)

Pre upgrade, I had been running  CLient 1.7.1 (on Mac 10.11.3) and Server 8.<something>.  Sorry I don't remember.

I had been running Client 1.7.1 because of this issue:  https://github.com/owncloud/client/issues/3313 and https://github.com/owncloud/client/issues/3248

Here's what happens.  My Sync client tries to sync and immediately (without trying to sync) disconnects with an error "Connection Closed",

I've got a log file made ready to send it.  I'd love to email it to someone.  The thing is about 47MB big and there's several different errors in it.  I'm not real sure where to start.

**Comment by Xenopathic** [comment]
Please fill out the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

In particular, with such a large log file, I'd suggest either removing it or moving it elsewhere, reproducing the issue, then copying the contents of the newly created log file here. (which should be considerably smaller and only containing the relevant messages)

**Comment by TheOtterslider** [comment]
### Steps to reproduce
Dunno.  I had been working ok with version 8.x.x (can't remember what) as the server and 1.7.1 client.  I upgraded to
Client - 2.1.0. build 2944 (Mac 10.11.3)
Server - Upgraded yesterday to 8.2.2
That's when the errors started.

### Expected behaviour
No errors and syncing

### Actual behaviour
Errors.  See log

### Server configuration
**Operating system**: CentOS release 6.6 (Final)

**Web server:**Server version: Apache/2.2.15 (Unix)

**Database:** MySQL 5.1.73 Source distribution

**PHP version:**PHP 5.6.11 (cli)

**ownCloud version:** 8.2.2

**Updated from an older ownCloud or fresh install:** upgrade

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```
[xxxx@xxxx ~]# sudo -u apache php /var/www/html/owncloud/occ  app:list
Enabled:
  - activity: 2.0.1
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - documents: 0.11.0
  - files: 1.1.9
  - files_external: 0.2.3
  - files_pdfviewer: 0.7
  - files_sharing: 0.6.2
  - files_texteditor: 2.0
  - files_trashbin: 0.6.3
  - files_versions: 1.0.6
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 0.6.0
  - templateeditor: 0.1
  - updater: 0.6
Disabled:
  - admin_dependencies_chk
  - bookmarks
  - calendar_old
  - contacts_old
  - encryption
  - external
  - files_encryption
  - files_locking
  - notifications
  - provisioning_api
  - search_lucene
  - user_external
  - user_ldap
  - user_webdavauth


**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder
[xxxx@xxxx ~]# sudo -u apache php /var/www/html/owncloud/occ config:list system
{
    "system": {
        "instanceid": "oc8e61b24903",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "MYDOMAIN"
        ],
        "datadirectory": "\/encryptedfs\/stuff\/ownCloudData\/",
        "overwrite.cli.url": "https:\/\/MYDOMAIN\/owncloud",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "mail_from_address": "admin",
        "mail_smtpmode": "php",
        "mail_domain": "otterslide.us",
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "singleuser": false,
        "loglevel": 0
    }
}

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
NO

**Are you using encryption:** yes/no
NO

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO


### Client configuration
**Browser:** n/a Happens from Sync client

**Operating system:**  OSX 10.11.3 Beta (15D9c)

### Logs
#### Web server error log
I don't see any errors related to owncloud in my error log

#### ownCloud log (data/owncloud.log)
My log is 45MB big.  I started the client from the command line using the command Applications/owncloud.app/Contents/MacOS/owncloud --logfile LOGFILENAME and made a fresh log.  I let the client run until it showed an error.  Like I said, there's several errors reported.  I'm not sure where to start.

#### Browser log
n/a

**Comment by TheOtterslider** [comment]
I'm adding this as a new comment just because I noticed it.  I thought the log you wanted was from the sync client log (as opposed to the server log).  My client log is 45MB (that is from a clean run up to the error being shown).  I can't locate my owncloud log...I don't have a data directory in my owncloud folder.

**Comment by RealRancor** [comment]
@TheOtterslider You have posted the location of your datadir in the issue template:

"datadirectory": "\/encryptedfs\/stuff\/ownCloudData\/",

**Comment by TheOtterslider** [comment]
Edited my post.  Would it be best to delete and resubmit?

**Comment by TheOtterslider** [comment]
Here's some additional info.  Rolling back to 1.7.1 (build 1655) appears to have resolved the sync issues.  My client is now syncing once again

**Comment by Xenopathic** [comment]
@TheOtterslider You will find your owncloud.log in `/encryptedfs/stuff/ownCloudData/`, perhaps there are some useful messages in there. However, if you are saying that a client rollback fixed your issue, I'd suggest reporting this in the owncloud/client repository

**Comment by TheOtterslider** [comment]
Ok.  let's call this one closed.  My guess is it is a client issue...not a server one.  I didn't notice that there were separate places for the client and server.  I reposted it there: https://github.com/owncloud/client/issues/4322
