### ISSUE TITLE
Upgrade from 8.2.1 to 8.2.2 failed

### ISSUE THREAD

**Issue by seichter** [owncloud/core#21388]
Might be something along the lines of  #21358 ... however for me switching off maintenance (as I did with the previous updates) did nothing. And I am out of wits where to find the problem. I am using the .deb packages on Debian 7.

### Steps to reproduce

No idea how to reproduce. Only one box ...

What I can reproduce is that 
```
php ./occ upgrade
ownCloud is already latest version

php ./occ maintenance:mode --off
Maintenance mode disabled

php ./occ maintenance:mode
Maintenance mode is currently disabled
```

does configure the maintenance mode right in config/config.php however the web landing page states it is waiting for it to be switched off. Tested with various browsers also in private mode, just to be sure.

### Expected behaviour

Upgrade with apt-get should update (as it did before). occ maintenance:mode --off and happy user.

### Actual behaviour
Upgrade was seemingly behaving as expected. But landing page shows 

> This ownCloud instance is currently in maintenance mode, which may take a while.
>       This page will refresh itself when the ownCloud instance is available again.
>       Contact your system administrator if this message persists or appeared unexpectedly.
>       Thank you for your patience.

### Server configuration
**Operating system**: Debian Linux 7 i686

**Web server:** Apache 2.2.22

**Database:** 5.5.47

**PHP version:** 5.6.16

**ownCloud version:** 

php ./occ status
  - installed: true
  - version: 8.2.2.2
  - versionstring: 8.2.2
  - edition: 

**Updated from an older ownCloud or fresh install:**
Update obviously

**List of activated apps:**

```
Enabled:
  - files: 1.1.10
  - files_external: 0.2.3
  - files_pdfviewer: 0.7
  - files_sharing: 0.6.2
  - files_texteditor: 2.0
  - files_trashbin: 0.6.3
  - files_versions: 1.0.6
  - files_videoviewer: 0.1.3
```

**The content of config/config.php:**

```
  'datadirectory' => '/var/www/owncloud-data',
  'dbtype' => 'mysql',
  'version' => '8.2.2.2',
  'installed' => true,
  'instanceid' => '50cbb2acc1bf0',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => '3',
  'trusted_domains' => 
  array (
    0 => 'somewhere.onmydomain.net',
  ),
  'mail_smtpmode' => 'php',
```

**Are you using encryption:** no

#### ownCloud log (data/owncloud.log)
last relevant line
```
{"reqId":"ttb7+OYYoZZF+rvaQRpu","remoteAddr":"","app":"core","message":"starting upgrade from 8.2.1.4 to 8.2.2.2","level":0,"time":"2015-12-22T23:34:26+01:00","method":"--","url":"--"}
```
would appreciate any hint what went wrong here or if I am missing something.

**Comment by RealRancor** [comment]
@seichter Have you tried to restart your webserver/php to make sure there is no caching issue?

**Comment by seichter** [comment]
@RealRancor Thanks! Restarting the webserver (which I usually try to avoid as much as possible) did the job. This should be added into the .deb package script/recipe as it does anyway stop the owncloud instance.

**Comment by RealRancor** [comment]
@seichter Which caching module (APC, APCu, XCache, OPCache, Redis...) are you using? Never had to do this with APCu or Redis.

**Comment by Xenopathic** [comment]
That would be the PHP Opcache doing funny things, likely due to a long recheck TTL. We do try to clear the opcache on upgrades, but the occ command runs in a separate PHP process so the cache clear has no effect on the web server process. Since this is a user-configured option, and is not a default on any system, it should be the responsibility of the admin to restart their server after an upgrade.

**Comment by MorrisJobke** [comment]
> Since this is a user-configured option, and is not a default on any system, it should be the responsibility of the admin to restart their server after an upgrade.

Yep. Closing

**Comment by seichter** [comment]
@RealRancor  I'm using OPcache and APCu. 

@Xenopathic  Well, if I am somehow serious about the performance in my PHP applications running on my server caches are necessary - this is only a vServer. Are there still people out there using no mem or opcode caches? 

I think having a bit of control over the caching mechanism and modules in occ similar to drush for Drupal would be a great feature for ownCloud.

**Comment by RealRancor** [comment]
@seichter I think the issue here is not Opcache itself. I'm also using it without such issue. It's more an non-default config option you're using according to @Xenopathic s post

**Comment by Xenopathic** [comment]
Indeed, in fact I wrote a blog post a while back about it: https://mccorkell.me.uk/article/performance-tuning
