### ISSUE TITLE
Feature Request: The ability to sync clipboard contents between devices.

### ISSUE THREAD

**Issue by octo777** [owncloud/core#21381]
Hi, I think it would be really handy to be able to see something great on your PC, copy the link to share with someone on your phone, go to your phone and just paste that link in whatsapp or whatever!  

I hate having to re-find the video or website or whatever. 
There are times I see something cool on the phone and want to send it to someones PC from an email I dont have on the phone. 
I just think that would be cool, dont know if anyone else has ever thought this?
Is there an easy way to have owncloud clients store and retrieve clipboard contents with your very own owncloud as the middle man?

**Comment by Yamakasi** [comment]
That is possible, default with some apps. Check Qownnotes.org for an example. Android store has notes apps too.

**Comment by rullzer** [comment]
This is not something we will support in core. You need 3rdpraty solutions (like the one @Yamakasi suggested for example).

Closing this.
