### ISSUE TITLE
Contacts app hangs when opened as "...jquery-1.10.2.js was not found on this server."

### ISSUE THREAD

**Issue by droid001** [owncloud/core#21389]
1. Open contacts
2. Spinner appears, freezes and page is unresponsive for a few seconds
3. Contact list appears unsorted in the background of a popup dialogue warning of the following:
```
A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.

Script: https://pacolola.net/owncloud/…836adbe35ae63abfeabe42c557ba5e:6
```
When opening the debugger the following HTML is shown:
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /owncloud/core/vendor/jquery/jquery-1.10.2.js was not found on this server.</p>
<hr>
<address>Apache/2.4.7 (Ubuntu) Server at pacolola.net Port 443</address>
</body></html>
```
Close the developer tools and the contacts are sorted and Contacts page is fully functional.

Server: OC 8.2.2 (was also present in v.8.1.3), Contacts 0.5.0.0, Lubuntu 12.04
Client: FF 43.0, Ubuntu 15.10

**Comment by RealRancor** [comment]
@droid001 Please re-open in https://github.com/owncloud/contacts/issues after you made sure you're running version 0.5.0.0 of the contacts app.

**Comment by droid001** [comment]
Moved to Contacts issues

**Comment by critzinger** [comment]
i have the same problem.
i have uploaded jquery-1.10.2.js, but the problem was the same.

we have currently over 800 non ldap users. the users are managed internal with owncloud

**Comment by RealRancor** [comment]
@critzinger See https://github.com/owncloudarchive/contacts/issues/1118

Just note that the old pre9.0 contacts app is unmaintained and won't get any fixes

**Comment by critzinger** [comment]
we have the problem with the user app (user management - owncloud internal)
not with the contact app

we have upgraded vom 8.2.2 to 9.0.1

following apps are enabled / disabled

Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - files: 1.4.4
  - files_sharing: 0.9.1
  - files_trashbin: 0.8.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0

Disabled:
  - encryption
  - external
  - federation
  - files_external
  - files_pdfviewer
  - files_texteditor
  - files_versions
  - files_videoplayer
  - firstrunwizard
  - gallery
  - user_external
  - user_ldap

**Comment by RealRancor** [comment]
@critzinger So why are you hijacking a thread about "Contacts app hangs when opened" with issues about the user management? Please create a new issue filling out the issue template shown.
