### ISSUE TITLE
OC 8.1.1 > 8.2.2: Log spammed with "Undefined index: HTTP_USER_AGENT" messages after manual upgrade

### ISSUE THREAD

**Issue by sehucke** [owncloud/core#21387]
### Steps to reproduce (not confirmed / reproduced yet)
1. Do a manual upgrade from OC 8.1.1 to 8.2.2
2. Reactivated / updated all addons
3. Open Admin page
4. See the log file spammed

### Expected behaviour
No error messages regarding the HTTP_USER_AGENT variable (since it was not a problem before and it might not be set anyway, see http://stackoverflow.com/questions/6465397/is-it-possible-for-serverhttp-user-agent-to-not-be-set for example)

### Actual behaviour
Massive flooding of the log file with following php error message (1 per second):
> Undefined index: HTTP_USER_AGENT at /path/to/ownCloud/lib/private/appframework/http/request.php#678

### Server configuration
**Operating system**: Linux (Shared Hosting, therefore no further data available)

**Web server:** Apache 2.2

**Database:** MySQL 5.6

**PHP version:** 5.6.2

**ownCloud version:** (see ownCloud admin page) 8.2.2

**Updated from an older ownCloud or fresh install:** Updated from 8.1.1

**List of activated apps:**
* Activity
* Default encryption module
* Deleted Files
* Documents
* File Locking
* First Run Wizard
* Gallery
* Notifications
* PDF Viewer
* Share Files
* Text Editor
* Updater
* Versions
* VideoViewer
* Bookmarks
* Calendar
* Contacts
* Tasks
* Mozilla Sync

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'trusted_domains' => 
  array (
    0 => '',
  ),
  'datadirectory' => '/path/to/owncloudData',
  'dbtype' => 'mysql',
  'version' => '8.0.2.0',
  'dbname' => '',
  'dbhost' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'forcessl' => true,
  'loglevel' => 1,
  'theme' => '',
  'maintenance' => false,
  'secret' => '',
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => '',
  'mail_from_address' => '',
  'mail_domain' => '',
  'mail_smtpauth' => 1,
  'mail_smtphost' => '',
  'mail_smtpport' => '',
  'mail_smtpname' => '',
  'mail_smtppassword' => '',
  'mail_smtpauthtype' => '',
  'forceSSLforSubdomains' => true,
);

**Are you using external storage, if yes which one:** No

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** No

### Partial Log:
Some lines of the mentioned log output
> {"reqId":"VoFl538AAAEAAGk2LhYAAAAR","remoteAddr":"myWANIP","app":"PHP","message":"Undefined index: HTTP_USER_AGENT at \/path\/to\/ownCloud\/lib\/private\/appframework\/http\/request.php#678","level":3,"time":"2015-12-28T16:40:07+00:00"}
> {"reqId":"VoFl538AAAEAAGk8xpUAAAAX","remoteAddr":"myWANIP","app":"PHP","message":"Undefined index: HTTP_USER_AGENT at \/path\/to\/ownCloud\/lib\/private\/appframework\/http\/request.php#678","level":3,"time":"2015-12-28T16:40:08+00:00"}
> {"reqId":"VoFl6H8AAAEAAGk4cYUAAAAT","remoteAddr":"myWANIP","app":"PHP","message":"Undefined index: HTTP_USER_AGENT at \/path\/to\/ownCloud\/lib\/private\/appframework\/http\/request.php#678","level":3,"time":"2015-12-28T16:40:09+00:00"}
> {"reqId":"VoFl6X8AAAEAAGlQLdEAAAAr","remoteAddr":"myWANIP","app":"PHP","message":"Undefined index: HTTP_USER_AGENT at \/path\/to\/ownCloud\/lib\/private\/appframework\/http\/request.php#678","level":3,"time":"2015-12-28T16:40:09+00:00"}
> {"reqId":"VoFl6n8AAAEAAGlKvV4AAAAl","remoteAddr":"myWANIP","app":"PHP","message":"Undefined index: HTTP_USER_AGENT at \/path\/to\/ownCloud\/lib\/private\/appframework\/http\/request.php#678","level":3,"time":"2015-12-28T16:40:10+00:00"}
> {"reqId":"VoFl638AAAEAAGaL4jcAAAA0","remoteAddr":"myWANIP","app":"PHP","message":"Undefined index: HTTP_USER_AGENT at \/path\/to\/ownCloud\/lib\/private\/appframework\/http\/request.php#678","level":3,"time":"2015-12-28T16:40:11+00:00"}

### Suggested solution
I modified the request.php mentioned in the error message at line 677ff and added `isset()` to check whether the HTTP_USER_AGENT variable is set:
```php
if (isset($this->server['HTTP_USER_AGENT'])) {
	foreach ($agent as $regex) {
		if (preg_match($regex, $this->server['HTTP_USER_AGENT'])) {
			return true;
		}
	}
}
```

Since you cannot rely on this variable being set one should always check if it is set before using it.

### Error source
I was not able to determine the error source yet. My Firefox 43 sets the HTTP_USER_AGENT (determined by useragentstring.com: "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0"). It may be a problem with some Android devices (I use following apps: owncloud, CardDAV-Sync, CalDAV-Sync) in my network - though it is unclear to me why the error message appears every second.

**Comment by LukasReschke** [comment]
Should be fixed with https://github.com/owncloud/core/commit/358858c9e3f06560b67b69e1d15c141debb2729a

@karlitschek @DeepDiver1975 Backport to stable8.2?

**Comment by karlitschek** [comment]
Please backport! :+1:

**Comment by sehucke** [comment]
:+1: for this lightning fast response!

Thanks a lot!

**Comment by MorrisJobke** [comment]
Backport is in #21391
