### ISSUE TITLE
Error while upgrade from 8.0.2.0 to 8.2.1

### ISSUE THREAD

**Issue by Deunze** [owncloud/core#21386]
Exception: Updates between multiple major versions and downgrades are unsupported.

**Comment by RealRancor** [comment]
@Deunze Please use the search on top of this repository before creating new issues. With that you will find plenty of duplicates describing your problem.

Then see this FAQ how to correctly upgrade: https://forum.owncloud.org/viewtopic.php?f=17&t=32087
