### ISSUE TITLE
Can't load contacts after contacts import - "Allowed memory size of bytes exhausted"

### ISSUE THREAD

**Issue by CriticalNoob** [owncloud/core#21384]
### Steps to reproduce
1. Import a moderately large contact list (Around 150 contacts) ( .vcf file) 
2. Try to load contact

### Expected behavior
Contacts should be displayed.

### Actual behavior
Spinning wheel forever and error 500

### Server configuration
**Operating system**:
Ubuntu 14.04
**Web server:**
Apache 2
**Database:**
Mysql
**PHP version:**
5.5
**ownCloud version:** (see ownCloud admin page)
8.2
**Updated from an older ownCloud or fresh install:**
Fresh install
**List of activated apps:**
Enabled:
  - activity: 2.1.3
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - updater: 0.6
Disabled:
  - encryption
  - external
  - files_external
  - gallery
  - user_external
  - user_ldap

**The content of config/config.php:**

{
    "system": {
        "instanceid": "ocjjeva77i4v",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "example.com",
            "www.example.com"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/example.com",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "asset-pipeline.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "loglevel": 0
    }
}

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Relevant ?
Safari

**Operating system:**
Mac os X.11

#### Web server error log
Clean

#### ownCloud log (data/owncloud.log)

{"reqId":"a7LUAHv8JCX6Fk50ZfZl","remoteAddr":"88.168.110.81","app":"core","message":"OC\\Tags::getFavorites, exception: Could not find category \"_$!<Favorite>!$_\"","level":0,"time":"2015-12-28T13:08:54+00:00","method":"GET","url":"\/index.php\/apps\/contacts\/groups\/"}
{"reqId":"nTR2rGgIk1z6SVuk2fNg","remoteAddr":"88.168.110.81","app":"contacts","message":"OCA\\Contacts\\Contact::retrieve Error parsing carddata  for: 1518 End of document reached prematurely","level":3,"time":"2015-12-28T13:08:55+00:00","method":"GET","url":"\/index.php\/apps\/contacts\/addressbook\/local\/5\/contacts"}
{"reqId":"nTR2rGgIk1z6SVuk2fNg","remoteAddr":"88.168.110.81","app":"contacts","message":"OCA\\Contacts\\Contact::retrieve Error parsing carddata  for: 1518 End of document reached prematurely","level":3,"time":"2015-12-28T13:08:55+00:00","method":"GET","url":"\/index.php\/apps\/contacts\/addressbook\/local\/5\/contacts"}
{"reqId":"nTR2rGgIk1z6SVuk2fNg","remoteAddr":"88.168.110.81","app":"contacts","message":"OCA\\Contacts\\Contact::retrieve Error parsing carddata  for: 1518 End of document reached prematurely","level":3,"time":"2015-12-28T13:08:55+00:00","method":"GET","url":"\/index.php\/apps\/contacts\/addressbook\/local\/5\/contacts"}
{"reqId":"nTR2rGgIk1z6SVuk2fNg","remoteAddr":"88.168.110.81","app":"PHP","message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 498073600 bytes) at \/var\/www\/owncloud\/apps\/contacts\/lib\/utils\/jsonserializer.php#86","level":3,"time":"2015-12-28T13:09:05+00:00","method":"GET","url":"\/index.php\/apps\/contacts\/addressbook\/local\/5\/contacts"}

#### Browser log

[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (contacts, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (jquery.min.map, line 0)

#### Edit :
Weird thing, in chrome dev tool, network, I get : 
contacts	GET	500	xhr	a59ca11f2d5674e459c130137b587d1c.js:6	217 MB

And it is still downloading at full bandwidth, what is happening ?!?

**Comment by RealRancor** [comment]
@CriticalNoob Please re-open in https://github.com/owncloud/contacts/issues

**Comment by CriticalNoob** [comment]
Done.

**Comment by RealRancor** [comment]
@CriticalNoob Thanks. You can close this issue here on your own by hitting the close button below the comment box.
