### ISSUE TITLE
Importing large Calender (.ics) files fails silently on shared Webhosting

### ISSUE THREAD

**Issue by ThomasChr** [owncloud/core#21382]
Hello Owncloud-Team, 

when importing large ics-Files (in this case ~ 3 MB) on a shared Webhosting Environment (with strict rules regarding maximum runtime of PHP Scripts) the Import Silently fails when the script is aborted.

In my case the maximum runtime is 60 seconds. 
When I import the file the request to import.php is sent out, and after exactly 60 Seconds it comes back with Status Code 500 (the Script has been aborted forcefully).

On the import dialog I get absolutly no feedback about that.

Is it possible to
a) Import large .ics-Files by restarting the script automaticly (PHPMyAdmin uses this way to import large SQL Files), or
b) At least give a feedback that the import failed?

I have a testing environment ready, and also a .ics-File.
Problem is: The ics-File is private so I can't put it online.

Because of the hosting environment I have not much logfiles to offer - the owncloud.log (with debug turned on) does output absolutly nothing.

Thomas

PS: Owncloud Server-Version is most recent stable (8.2.2)

**Comment by ThomasChr** [comment]
### Steps to reproduce
1. Install Owncloud
2. Activate the Calender App
3. Try to Import an .ics-File with more than 3 MB (in my case ~5600 Events)

### Expected behaviour
Owncloud should either succed to import all events - or come back with an error message.

### Actual behaviour
After importing about 600 Events the max_execution_time of 60 seconds has been exhausted and so import.php fails silently.
The import dialog still is open without any kind of feedback about the error.
(import.php Request comes back with code 500) 

### Server configuration
**Operating system**:
Linux af939 2.6.32-573.7.1.el6.x86_64 #1 SMP Tue Sep 22 22:00:00 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
(shared hosting environment)

**Web server:**
Apache

**Database:**
Doesn't matter

**PHP version:**
5.4.45

**ownCloud version:** (see ownCloud admin page)
8.2.2

**Updated from an older ownCloud or fresh install:**
Fresh Install

**List of activated apps:**
Only the offical Calender App

**The content of config/config.php:**
>>>>
<?php
define('DEBUG', true);
$CONFIG = array (
  'instanceid' => 'occr7us5su7x',
  'passwordsalt' => 'XXX',
  'secret' => 'XXX',
  'trusted_domains' =>
  array (
    0 => 'www.tcplay.de',
    1 => 'tcplay.de',
  ),
  'datadirectory' => '/var/www/vhosts/hosting5811.af939.netcup.net/httpdocs/owncloud/data',
  'overwrite.cli.url' => 'http://www.tcplay.de/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.2.2.2',
  'dbname' => 'XXX',
  'dbhost' => '10.35.249.59',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'XXX',
  'dbpassword' => 'XXX',
  'logtimezone' => 'UTC',
  'installed' => true,
);
<<<<

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no


### Client configuration
**Browser:**
Firefox, most recent - doesn't really matter

**Operating system:**

### Logs
#### Web server error log
Because of shared hosting environment I have no direct access to these logs

#### ownCloud log (data/owncloud.log)
-> Nothing with actual timestamp here

#### Browser log
Request to import.php gets aborted after 60 Seconds with Response Code 500

**Comment by RealRancor** [comment]
@ThomasChr Please re-open at https://github.com/owncloud/calendar/issues

**Comment by ThomasChr** [comment]
My bad. Sorry.

Issue opend here: https://github.com/owncloud/calendar/issues/1007
