### ISSUE TITLE
CSS #header .logo links to the false image

### ISSUE THREAD

**Issue by IngoBelka** [owncloud/core#21396]
Hello,

with version 8.2.x came a little mistake in CSS:
```css
#header .logo 
```
currently there is:
```css
background-image: url("../img/logo-icon.svg");
```
but it has to be:
```css
background-image: url("../img/logo.svg");*
```
Thank You very much for your work on owncloud and I wish you a happy new year 2016.

Ingo

**Comment by rullzer** [comment]
I think this is by design. @jancborchardt

**Comment by jancborchardt** [comment]
Yep, it’s by design to have no text with the logo anymore.

@IngoBelka thanks for the report though, and don’t hesitate to report other design issues if you find any! :)

**Comment by IngoBelka** [comment]
My first post is not clear enough, may be. I mean the CSS for the login-screen.

I read documentation and other related things. But now I don't understand the sence of these three selectors:
```
#header .logo 
#header .logo-wide
#header .logo-icon
```
if you use **logo-icon.svg** in **#header .logo**

**Comment by jancborchardt** [comment]
@IngoBelka they are just there for backwards compatibility, say in case a template of an app on the store uses these old classes. But logo-wide and logo-icon are deprecated in favor of just logo.
