### ISSUE TITLE
Text "door de ownCloud gemeenschaplinkclose}, de" not formatted correctly.  Contains [linkclose}].

### ISSUE THREAD

**Issue by radoeka** [owncloud/core#21390]
De Dutch translation is missing an opening square bracket in the following sentence:
at the bottom of the page: owncloud/index.php/settings/admin#admin-tips
The translated text is:

Versie
ownCloud 8.2.2 (stable)
Ontwikkeld door de ownCloud gemeenschaplinkclose}, de
    ==============

The last sentence above (the ====) contains: linkclose}, that shouldn't be there.

The translation misses the opening opening bracket, as shown in the following code diff:

    # diff -u settings/l10n/nl.json-old settings/l10n/nl.json | sed 's/^/    /'
    --- settings/l10n/nl.json-old       2015-12-29 10:55:15.367406570 +0100
    +++ settings/l10n/nl.json   2015-12-29 10:56:13.864941832 +0100
    @@ -250,7 +250,7 @@
         "Issued By" : "Uitgegeven door",
         "Valid until %s" : "Geldig tot %s",
         "Import root certificate" : "Importeren root certificaat",
    -    "Developed by the {communityopen}ownCloud community{linkclose}, the {githubopen}source code{linkclose} is licensed under the {licenseopen}<abbr title=\"Affero General Public License\">AGPL</abbr>{linkclose}." : "Ontwikkeld door de {communityopen}ownCloud gemeenschaplinkclose}, de {githubopen}source code{linkclose} is gelicenseerd onder de {licenseopen}<abbr title=\"Affero General Public License\">AGPL</abbr>{linkclose}.",
    +    "Developed by the {communityopen}ownCloud community{linkclose}, the {githubopen}source code{linkclose} is licensed under the {licenseopen}<abbr title=\"Affero General Public License\">AGPL</abbr>{linkclose}." : "Ontwikkeld door de {communityopen}ownCloud gemeenschap{linkclose}, de {githubopen}source code{linkclose} is gelicenseerd onder de {licenseopen}<abbr title=\"Affero General Public License\">AGPL</abbr>{linkclose}.",
         "Show storage location" : "Toon opslaglocatie",
         "Show last log in" : "Toon laatste inlog",
         "Show user backend" : "Toon backend gebruiker",

**Comment by MorrisJobke** [comment]
This needs to be fixed on transifex. @jospoortvliet @icewind1991 or @rullzer Can one of you fix this? Thanks

**Comment by DeepDiver1975** [comment]
> ownCloud 8.2.2 (stable)

requires backport to stable8.2

**Comment by radoeka** [comment]
Transifex:
https://www.transifex.com/owncloud_robot/owncloud/viewstrings/#nl/settings-1/40730744?q=agpl

**Comment by radoeka** [comment]
I could adjust it myself.   Please verify if done correctly @jospoortvliet @icewind1991 or @rullzer 
https://www.transifex.com/owncloud_robot/owncloud/viewstrings/#nl/settings-1/40730744?q=agpl
Backport to 8.2 is up to others.

**Comment by rullzer** [comment]
Already synced to master https://github.com/owncloud/core/commit/45c41e2b2cefa97c9d8c3bc73cfc088839640d1d

**Comment by rullzer** [comment]
@DeepDiver1975 how do we backport translations? Just like regular PR's?

**Comment by MorrisJobke** [comment]
> @DeepDiver1975 how do we backport translations? Just like regular PR's?

There is a script by @vgezer - usually @nickvergessen executes it with the needed l10n strings as arguments.

**Comment by nickvergessen** [comment]
8.2 backport https://github.com/owncloud/core/issues/21441
