### ISSUE TITLE
occ upgrade from console

### ISSUE THREAD

**Issue by ukirfan** [owncloud/core#21407]
![cifs mounted upgrade](https://cloud.githubusercontent.com/assets/4848972/12064604/f18b9318-afe0-11e5-8bae-8334d2b85e0c.png)

hi,

I have mounted the data folder using cifs external storage of few GBs. i am trying to upgrade from 6 to owncloud 7. i am able to see the mounted folder /mnt/data/ownclouddata with all of the files using ftp . but some how upgrade is not being done by the command  ? as shown in screenshot atached. how to upgrade as it is not able to see .ocdata even through chown command is given for suselinux user wwwrun:www 

how to upgrade it is easily for mounted cifs storage data folders. ? 
mounted using : 
 mount  -t cifs  -o username=abcdwindowsadminuserxyz,rw,nounix,iocharset=utf8,uid=wwwrun,gid=www,file_mode=0770,dir_mode=0770  //172.20.28.32/DPW_HO_Storage2/HOCloud/hoclduatdata   /mnt/data/ownclouddata

**Comment by ukirfan** [comment]
suse linux 13.2 , php 5.4.20 , apache 2.2

**Comment by Xenopathic** [comment]
Are you sure your datadirectory is set correctly? According to the screenshot it may be `/mnt/data/ownclouddata/ownclouddata`, which seems to have a duplicated directory component.

**Comment by ukirfan** [comment]
yes i have duplicated the same name. as it is visible through ftp, this path is right . and i have tried using local storage earlier and the upgrade was fine, only with cifs mount this error gets repeated.

**Comment by ukirfan** [comment]
config set  already as 

'datadirectory' => '/mnt/data/ownclouddata/ownclouddata',

**Comment by ukirfan** [comment]
![cifs folder](https://cloud.githubusercontent.com/assets/4848972/12064923/cf2daa8e-afe7-11e5-9cf3-e09d0d3711ff.png)
 
as u can see the cifs folders are having windows permissions full. and are visible on ftp, because of thsi mount. only for the occ it is not readable that makes this upgrade error.

**Comment by JohannesKleine** [comment]
Are you running this command in chrooted environment?

**Comment by ukirfan** [comment]
thank you for the troubleshooting, i performed this test for checking if i am in chrooted env.
cd /
ls -di


it gives the result 2
no iam not in chroot environment. 

i copied files for upgrade to 8.0.4, after upgrade, on the screen i get as in the screenshot
![cannot read data](https://cloud.githubusercontent.com/assets/4848972/12073617/ba8b5856-b140-11e5-9fae-1c2e40bf2dbc.png)

**Comment by JohannesKleine** [comment]
There is a script in the admin manual to set the right permissions, owner (user and group)

**Comment by ukirfan** [comment]
yes i have tried the script , i hope this is the one you are mentioning about ?
#!/bin/bash
ocpath='/srv/www/htdocs'
htuser='wwwrun'
htgroup='www'
rootuser='root' # On QNAP this is admin 
find /srv/www/htdocs/ -type f -print0 | xargs -0 chmod 0640
find /srv/www/htdocs/ -type d -print0 | xargs -0 chmod 0750

chown -R wwwrun:www /srv/www/htdocs/
chown -R wwwrun:www /srv/www/htdocs/apps/
chown -R wwwrun:www /srv/www/htdocs/config/
chown -R wwwrun:www /mnt/data/ownclouddata/
chown -R wwwrun:www /srv/www/htdocs/themes/

chown wwwrun:www /srv/www/htdocs/.htaccess
chown wwwrun:www /mnt/data/ownclouddata/ownclouddata/.htaccess

chmod 0644 /srv/www/htdocs/.htaccess

**Comment by LukasReschke** [comment]
This seems more like an environment issue. Please see https://owncloud.org/support on ways on how to get support. The bug tracker is the wrong place for this.
