### ISSUE TITLE
ownCloud 8.x.x on Synology server | ownCloud Client Download problem

### ISSUE THREAD

**Issue by Kaelber** [owncloud/core#21405]
I use Synology servers all equiped with ownCloud. I use with Synology package but I also have tried the solution with the ownCloud webinstaller on my Synology servers
DS412+ with DSM 5.2-5644 update 2,
DS1512+ with DSM 5.2-5644 update 2,
DS712+ with DSM 6.0 Beta,
DS414 with DSM 5.2-5644 update 2. 

I only use server directories with External Storage Support "Local" included with the effect that at server side and between different Synology DS's everything is going great. Are files modified on client side, this are also uploaded with the client (v2.1.0). Only download files that have been changed on the server does not always work as download.

There is for the client a server-side difference between the respective root directory and his subdirectories. The content of root directory (files) is always synchronized, respectively, while sub-directories will only synchronize, if the content of root directory is modified and to synchronize.

If in a root is nothing to synchronize and if downloading from a server subdirectory to the client side is not ongoing and when files are uploaded to the server, the other server-side files are also downloaded, but only in those directories, a uploading is done. And this effect only is in this directories, I have this load processes.

**Comment by aspdye** [comment]
Looks like an Individual configuration problem. I think the best and fastest was to help you is refering you to the Support options of ownCloud. Maybe you could ask for help in the IRC or in the Forums, where may be are users with the same problems you have: 

https://ownCloud.org/Support/

**Comment by Kaelber** [comment]
I think, I´m right here, because in other sources, FAQ´s, communities, etc., right now I got no solution or idea for this problem. Or you have a idea?

**Comment by aspdye** [comment]
@PVince81

**Comment by Xenopathic** [comment]
ownCloud cannot detect direct modifications to any data directories or external storages connected to it without expensive rescan operations.

**Comment by Kaelber** [comment]
In which way I can include the rescan 

/bin/su -c /bin/sh -c "/usr/bin/php -f /volume1/web/owncloud/occ files:scan --all" http

inside of cron.php?

Because the above rescan in the crontab doesn´t work!

**Comment by Xenopathic** [comment]
You need to run occ in the root directory of your ownCloud installation, so `cd` into it first

**Comment by Kaelber** [comment]
Okay, in which way I can include the command

occ files:scan --all
or
/volume1/web/owncloud/occ files:scan --all

in the cron.php ?

**Comment by Xenopathic** [comment]
`... /bin/sh -c "cd /volume1/web/owncloud && /usr/bin/php -f occ files:scan --all" ...`

**Comment by Kaelber** [comment]
with 

/bin/sh -c "cd /volume1/web/owncloud && /usr/bin/php -f occ files:scan --all"

I got a fault message. Or I have to use 

... /bin/sh -c "cd /volume1/web/owncloud && /usr/bin/php -f occ files:scan --all" ...

with the points? I don´t know.

**Comment by Xenopathic** [comment]
The ellipsis was me skipping the rest of the cron line

**Comment by Kaelber** [comment]
Thanks it´s because your short comments. Now I use in the crontab :+1: 
0,20,40	*	*	*	*	root	/bin/sh -c "cd /volume1/web/owncloud && /usr/bin/php -f occ files:scan --all" http	#ownCloud Filesystem ReScan

but it doesn´t work. With which syntax I can use inside of cron.php? I use your line in the cron.php and get a "fault in line xxx".

**Comment by Kaelber** [comment]
With which syntax I can use inside of cron.php 

0,20,40 * * * * root /bin/sh -c "cd /volume1/web/owncloud && /usr/bin/php -f occ files:scan --all" http

**Comment by Xenopathic** [comment]
@Kaelber Read up on crontab syntax (`man 1 crontab`), there's not much help I can give you now, just that you need to `cd` into the ownCloud root before running occ

**Comment by Kaelber** [comment]
Your "pre-way" was good! Now I found  the solution as follow and I include in the crontab 

0,20,40	4-23	*	*	*	root	/bin/su -s /bin/sh -c "cd /volume1/web/owncloud && /usr/bin/php -f occ files:scan rescan" http >> /volume1/web/owncloud/data/logs/cron_rescan_rescan_$(date +\%Y-\%m-\%d_\%H-\%M-\%S).log 2>&1

but this only is valid for ownCloud 8.2.x-versions. This doesn´t run with 8.1.x versions. This may no problem, I update all servers on v8.2.2 - but with the new Synology DSM 6.0 beta also this doesn´t work with the ownCloud versions 8.2.x. 

As follow a rescan-log with the combination Synology DSM 6.0 beta mit ownCloud 8.2.2:

An unhandled exception has been thrown:
exception 'Doctrine\DBAL\DBALException' with message 'Failed to connect to the database: An exception occured in driver: could not find driver' in /volume1/web/owncloud/lib/private/db/connection.php:52
Stack trace:
#0 /volume1/web/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /volume1/web/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /volume1/web/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /volume1/web/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(621): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /volume1/web/owncloud/lib/private/db/connection.php(135): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /volume1/web/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#6 /volume1/web/owncloud/lib/private/db/connectionfactory.php(118): Doctrine\DBAL\DriverManager::getConnection(Array, Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#7 /volume1/web/owncloud/lib/private/server.php(328): OC\DB\ConnectionFactory->getConnection('mysql', Array)
#8 /volume1/web/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(112): OC\Server->OC\{closure}(Object(OC\Server))
#9 /volume1/web/owncloud/lib/private/appframework/utility/simplecontainer.php(104): Pimple\Container->offsetGet('DatabaseConnect...')
#10 /volume1/web/owncloud/lib/private/server.php(763): OC\AppFramework\Utility\SimpleContainer->query('DatabaseConnect...')
#11 /volume1/web/owncloud/lib/private/db.php(42): OC\Server->getDatabaseConnection()
#12 /volume1/web/owncloud/lib/private/server.php(235): OC_DB::getConnection()
#13 /volume1/web/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(112): OC\Server->OC\{closure}(Object(OC\Server))
#14 /volume1/web/owncloud/lib/private/appframework/utility/simplecontainer.php(104): Pimple\Container->offsetGet('AppConfig')
#15 /volume1/web/owncloud/lib/private/server.php(702): OC\AppFramework\Utility\SimpleContainer->query('AppConfig')
#16 /volume1/web/owncloud/lib/private/server.php(373): OC\Server->getAppConfig()
#17 /volume1/web/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(112): OC\Server->OC\{closure}(Object(OC\Server))
#18 /volume1/web/owncloud/lib/private/appframework/utility/simplecontainer.php(104): Pimple\Container->offsetGet('AppManager')
#19 /volume1/web/owncloud/lib/private/server.php(929): OC\AppFramework\Utility\SimpleContainer->query('AppManager')
#20 /volume1/web/owncloud/lib/private/app.php(259): OC\Server->getAppManager()
#21 /volume1/web/owncloud/lib/private/app.php(104): OC_App::getEnabledApps()
#22 /volume1/web/owncloud/lib/base.php(566): OC_App::loadApps(Array)
#23 /volume1/web/owncloud/lib/base.php(1081): OC::init()
#24 /volume1/web/owncloud/console.php(42): require_once('/volume1/web/ow...')
#25 /volume1/web/owncloud/occ(11): require_once('/volume1/web/ow...')
#26 {main}

Any idea?

In which way may be possible to include a fixed rescan modul in owncloud, to have a "internal" ownCloud system solution?

**Comment by d-tamm** [comment]
See this solution, which worked for me:
http://www.synology-forum.de/showthread.html?74988-DSM-6-0-OwnCloud-8-2-X-X-PHP-Cron-Fehler
Essentially using /usr/local/bin/php56 instead of /bin/php
