### ISSUE TITLE
occ files:scan missing feedback while running

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#21412]
There is no feedback at all while the files:scan operation is running. If I remember correctly, in the past all files were displayed running down, which was a bad experience as well but at least it gave feedback.

A simple feedback like »Scanning files …« would already go a long way. If we can, even showning the percentage of scanned files. (If that doesn’t work, adding a dot for every scanned file as live progress bar would be good.)

cc @DeepDiver1975

**Comment by karlitschek** [comment]
I agree. Some feedback would be nice. Ideally something like xxx% done
@icewind1991

**Comment by mmattel** [comment]
I did the last update of the files:scan command where I changed based on parameters what will be printed out.

- no parameter: at the end, only the summary how many files/directories that had been processed are printed.
- --quiet (-q): means no printout at all
- --verbose (-v): means printout of each file/directory in process (that was the old behaviour)

The documentation has been updated accordingly.

You can get your known behaviour by adding the parameter --verbose or -v

@karlitschek 
To printout a progress bar, you need to know how many files/directories are present, but this is not known in advance. This means that you need to run the files:scan command in two phases. Count first and then print where you are. That will slow down scanning in an unnecessary way what should be avoided. Performance and the choice what will be printed out were the reasons for my changes.

btw: -v or -vv or -vvv are treated equally and are set to -v

**Comment by karlitschek** [comment]
@mmattel I'm aware of the problem. :-) But it might be enough to do a rough estimation instead of a 100% correct count. Maybe just saying  x from y user directories are scanned. Or we use the number of high top directories in every user home. 
Not always 100% correct but definitely better then no progress output at all.

**Comment by jancborchardt** [comment]
Exactly. Verbose is too much, quiet is nothing at all and hence too little. @mmattel It should be some kind of feedback like I described in my post above.

**Comment by mmattel** [comment]
Maybe we could have more kinds of verbose (-v and -vv).
-v does some kind of estimation (however we decide/do that), and
-vv does that what is currently done with the full printout.
By that we can have a finer granularity of the data presented AND also control possible performance impacts.
I personally would start with minimum data presented as we do now having no additional parameter and increase the printout with -v/-vv respectively quietness with -q.

**Comment by jancborchardt** [comment]
I don’t think the solution is adding _more_. Giving basic loading feedback should be the default, what happens when no parameters are given.
