### ISSUE TITLE
keeps trying to update but im on the latest version

### ISSUE THREAD

**Issue by kiwiandy** [owncloud/core#21427]

**Comment by kiwiandy** [comment]
i am running owncloud 8.2.1 on my NAS (Asusstor 604T with ADM 2.5.1.RB62)

I had a problem when trying to update an old version 8.01 or something like that, and when I tried to update to 8.2.1 i got an error message when I tired to update, so I deleted the owncloud and reinstalled the latest version which is 8.2.1
it seemed to be working ok for a while and then now when I try to log in I am getting the same message about updating to 8.2.1 and when I click the update button i get a message that the update was unsuccesful, and to report the issue here?
![screen shot 2016-01-04 at 4 46 56 pm](https://cloud.githubusercontent.com/assets/8674704/12083188/d81c93da-b302-11e5-8854-cac675093a87.png)
![screen shot 2016-01-04 at 4 47 07 pm](https://cloud.githubusercontent.com/assets/8674704/12083191/dcdad1a2-b302-11e5-8876-9248255859b8.png)

**Comment by kiwiandy** [comment]
![screen shot 2016-01-04 at 4 48 15 pm](https://cloud.githubusercontent.com/assets/8674704/12083201/ff1f13f4-b302-11e5-8f96-7db2556291d0.png)
my existing installation

**Comment by RealRancor** [comment]
@kiwiandy Issues with ownCloud packaged by 3rdparty vendors/developers should be reported to its maintainer (shown on screenshot).

Please also make them aware that major versions can't be skipped. An correct upgrad path of your old 8.0.1 to 8.2.1 would be:

8.0.1 -> 8.0.10 -> 8.1.5 -> 8.2.1 (or better 8.2.2)
