### ISSUE TITLE
Purging trash on mobile browsers not possible

### ISSUE THREAD

**Issue by foobar26** [owncloud/core#21421]
How to reproduce:
1) Upload a file
2) Remove it so it is moved to the trash
3) Open owncloud -> trash in a mobile browser (i.e. Chrome)
4) Select the checkbox for marking all files

![screenshot_2016-01-03-12-28-52](https://cloud.githubusercontent.com/assets/1873393/12078573/bba001f6-b217-11e5-9f4c-3769d39448d4.png)

Desired behavior: The "Delete trash" button is visible on the top right to empty the trash
Actual behavior: Only the "Restore" button is visible, you cannot push the "Delete trash" button.

This is only a bug for mobile browsers. On desktop browsers like Firefox it is working as intended.

Cheers,
Frank

**Comment by LukasReschke** [comment]
@jancborchardt

**Comment by noveens** [comment]
@PVince81 ,
close the issue?
