### ISSUE TITLE
occ failure during command line installation 

### ISSUE THREAD

**Issue by liuxunchen** [owncloud/core#21428]
hello,

I am trying to do a command line installation on fedora23 server edition. 
The server is running well with phpBB3 and website based installation wizard works well on fedora23 desktop edition.
the issue is

$ sudo -u apache php occ

An unhandled exception has been thrown: exception 'Exception' with message 'Not installed' in /usr/share/owncloud/lib/base.php:223
Stack trace: #0 /usr/share/owncloud/lib/base.php(562): OC::checkInstalled()

I noticed that owncloud is installed on the following location on fedora23, but was not an issue on desktop edition
/usr/share/owncloud
/var/lib/owncloud

Thanks a lot!

**Comment by fossxplorer** [comment]
@liuxunchen can you use the issue template from [1] to provide some more details?
What happens if you run the following commands?
#cd /usr/share/owncloud
#./occ maintenance:install

[1] https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by liuxunchen** [comment]
### Steps to reproduce
1. fresh installation of fedora 23 server edition
2. dnf install owncloud
3. chown apache:apache /usr/share/owncloud
4. sudo -u apache php occ

### Expected behaviour
occ gives a list such as 

ownCloud version 8.0.9
Usage:
  command [options] [arguments]
Options:


### Actual behaviour
An unhandled exception has been thrown:
exception 'Exception' with message 'Not installed' in /usr/share/owncloud/lib/base.php:223
Stack trace:
#0 /usr/share/owncloud/lib/base.php(562): OC::checkInstalled()


### Server configuration
**Operating system**:
Fedora 23 server

**Web server:**
httpd-2.4.17
**Database:**
mariadb-1.10
**PHP version:**
php-5.6.16
**ownCloud version:** (see ownCloud admin page)
8.0.9
**Updated from an older ownCloud or fresh install:**
fresh
**List of activated apps:**



**The content of config/config.php:**
?php
$CONFIG = array (
    "log_type" => "syslog",
    "datadirectory" => "/var/lib/owncloud/data",
    "updatechecker" => false,
    "check_for_working_htaccess" => false,
    "asset-pipeline.enabled" => false,
    "assetdirectory" => '/var/lib/owncloud',

    "apps_paths" => array(
        0 =>
        array (
            'path'=> '/usr/share/owncloud/apps',
            'url' => '/apps',
            'writable' => false,
        ),
        1 =>
        array (
            'path' => '/var/lib/owncloud/apps',
            'url' => '/apps-appstore',
            'writable' => true,
        ),
    ),
);
~                 


**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
