### ISSUE TITLE
Safari ignores autocomplete="off" in share dialog

### ISSUE THREAD

**Issue by DenBeke** [owncloud/core#21422]
### Steps to reproduce
1. Open your ownCloud in Safari browser
2. Try to share a file by link.

### Expected behaviour
You click on the checkbox "Share with Link", and you can copy paste the URL

### Actual behaviour
The "Share with Link" actually works, but Safari thinks it's necessary to hint all my usernames/passwords in the "Username" field, which gives me list that is super positioned over the "Share with Link", so you can't click the checbox. This is because Safari (and possibly also other browser) ignores the `autocomplete="off"` option for an input field.

![schermafbeelding 2016-01-03 om 13 38 59](https://cloud.githubusercontent.com/assets/3856745/12079131/3bfce6d2-b22e-11e5-9c64-d4f9caa6f557.png)

I could look into this issue, since I think it can't be too hard to fix this. I only don't know where to start digging in toe code base to find the template of the share dialog. 

### Server configuration
**Operating system**: Ubuntu

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.5.9

**ownCloud version:** 8.1.1 (stable)

**Updated from an older ownCloud or fresh install:** Updated

### Client configuration
**Browser:** Safari 9.0.2

**Operating system:** OS X 10.11.2

(I hope I have provided enough parts of the issue template, if not I'll add the others...)

**Comment by DenBeke** [comment]
As @RealRancor pointed out on IRC yesterday, this is probably already fixed in the newer ownCloud versions...

**Comment by LukasReschke** [comment]
> As @RealRancor pointed out on IRC yesterday, this is probably already fixed in the newer ownCloud versions...

Can you let us know which versions? Also on 8.1.2?

**Comment by DenBeke** [comment]
The newer version we tried on is the actual demo site: https://demo.owncloud.org/
