### ISSUE TITLE
php-fpm dumped core (php 7)

### ISSUE THREAD

**Issue by satou-kun** [owncloud/core#21423]
I have an install of owncloud 8.2 from two weeks ago, on arch linux. I upgraded to php 7, every things looks okay, except php-fpm crashing with the following log:

systemd-coredump[20086]: Process 19893 (php-fpm) of user 33 dumped core.
                                              Stack trace of thread 19893:
                                              #0  0x00007f95434f75f8 raise (libc.so.6)
                                              #1  0x00000000006b4af5 n/a (php-fpm)
                                              #2  0x00000000006b4bf2 n/a (php-fpm)
                                              #3  0x00007f95434f7680 __restore_rt (libc.so.6)
                                              #4  0x00007f95435ade0d accept (libc.so.6)
                                              #5  0x00000000007201e0 n/a (php-fpm)
                                              #6  0x000000000043367b n/a (php-fpm)
                                              #7  0x00007f95434e4610 __libc_start_main (libc.so.6)
                                              #8  0x0000000000434949 _start (php-fpm)
There aren't other owncloud logs. 
It didn't crash before moving to php7 and I think i've followed all the instructions correctly.
The owncloud server still works but pages aren't refreshing immediately after performing actions, even if the actions are successfully processed (uploading, sharing, enabling, etc..).

**Comment by karlitschek** [comment]
ownCloud can't really crash the php process because it is only php scripts. This must be a problem in php 7, you distribution or the way it is compiled. Sorry. nothing we can do on the owncloud side here.

**Comment by satou-kun** [comment]
Hi, this morning i've gone again through all the settings for nginx/owncloud/php/php-fpm.

It seems that php-fpm has stopped crashing repeatedly.

It only stopped after I have it using 127.0.0.1:9000 instead of php-fpm.sock.

If I switch back it fills my logs with dumped core again.

I leave this there in case it can help somebody,

Sincerely.
