### ISSUE TITLE
ownCloud 8.2.2: php-error Undefined index: HTTP_USER_AGENT

### ISSUE THREAD

**Issue by BenS89** [owncloud/core#21429]
Steps to reproduce:
1. Upgrade from 8.2.1 to 8.2.2
2. Open the admin-panel in the web-frontend
3. Look into the logfiles

Expected behaviour:
No errors

Actual behaviour:
You can see the following error in the admin-panel:

<code>Error PHP Undefined index: HTTP_USER_AGENT at /share/MD0_DATA/htdocs/owncloud/lib/private/appframework/http/request.php#678</code>

Enabled apps:
Calendar 0.8.1
Contacts 0.5.0.0

PHP-Version: 5.6.10
OS: Embedded QNAP-Linux

**Comment by Xenopathic** [comment]
Fixed with 358858c9e3f06560b67b69e1d15c141debb2729a

**Comment by RealRancor** [comment]
And a dup of https://github.com/owncloud/core/issues/21387 :-)
