### ISSUE TITLE
Begin of year prayers

### ISSUE THREAD

**Issue by hecsa** [owncloud/core#21426]
Hi!
First of all, thanks to the entire team. You are making a great job.
This January, 1st., I raised my eyes to the sky, and asked Santa about incremental sync support. This, and faster client discovery, it takes hours to discover a directory when having a lot of files.
Thanks to all of you, and thanks to Santa if my prayers become truth.
Best regards,

HeCSa.

**Comment by karlitschek** [comment]
thanks for the feedback. closing as duplicate

**Comment by RealRancor** [comment]
Ref: https://github.com/owncloud/client/issues/179
