### ISSUE TITLE
iOS app: simple .xlsx file not displayed properly

### ISSUE THREAD

**Issue by sco2tbold** [owncloud/core#21425]
Hi - we're sharing a simple .xlsx file but on the OC app under iOS this file is not display right. Most of the cells are covered with a white area, only at the left border you can see the first few letters. I'll attach 2 screenshots. Thanks.

![oniphone-01](https://cloud.githubusercontent.com/assets/7213039/12080533/c8fe10c2-b25d-11e5-8c38-24e2f94a48f4.jpg)

![onmac](https://cloud.githubusercontent.com/assets/7213039/12080520/43efa152-b25d-11e5-8f30-22f9145a512d.png)

**Comment by RealRancor** [comment]
Hi,

@sco2tbold 
the issue tracker of the iOS app is located here:

https://github.com/owncloud/ios/issues

But AFAIK the iOS app is not including an viewer for Excel files so this looks more like an issue with an local viewer app installed on your phone.
