### ISSUE TITLE
Sidebar (Files): opacity of edited date leads to unreadable text

### ISSUE THREAD

**Issue by fcturner** [owncloud/core#21436]
Although issued (and closed) but not solved here: #18291, the opacity on hover of the last changed date, leads to almost unreadable text, especially on smaller screens (like smartphones) and preview of images:
(source: [demo.owncloud.org](https://demo.owncloud.org/index.php/apps/files/) on Jan 4th, 2016:)
![image](https://cloud.githubusercontent.com/assets/7526559/12088009/f064f778-b2d7-11e5-932e-4b720aa0b8d9.png)
**Solution:**
This should do it already, following you style:
```css
#app-sidebar .file-details {
	/*opacity: 0.5;*/
	color: #999;
}
```

**Result:**
![image](https://cloud.githubusercontent.com/assets/7526559/12088247/d2342862-b2d9-11e5-8e8e-3d138dca838f.png)

**Comment by LukasReschke** [comment]
@owncloud/designers

**Comment by MorrisJobke** [comment]
Fix is in https://github.com/owncloud/core/pull/21454

**Comment by fcturner** [comment]
Great! You're quick :wink:

**Comment by jancborchardt** [comment]
@fcturner in the future you are also welcome to open a pull request directly. :) Especially when you already have the solution.

**Comment by fcturner** [comment]
Will do. Thanks again.
