### ISSUE TITLE
Documentation shown is related to 8.2 instead of 9.0 oC version

### ISSUE THREAD

**Issue by davitol** [owncloud/core#21432]
### Steps to reproduce

1. Configure a new ownCloud server
2. Click on apps menu
3. Go to Developer documentation or Admin documentation of any app.

### Expected behaviour

The user should be redirected to a 9.0 oC version URL

### Actual behaviour

The user is redirected to a 8.2 oC version URL

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: 9.0 pre alpha (daily) Build:2016-01-04T04:33:14+00:00 6ca2da7d5ccb9d3353c64125e196ad5a56ed4cfb

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

**Comment by PVince81** [comment]
Fixed in https://github.com/owncloud/enterprise/issues/996
