### ISSUE TITLE
Clustered ownCloud with Redis in HA environment

### ISSUE THREAD

**Issue by GitHubUser4234** [owncloud/core#21433]
Hello,

In a HA environment Redis supports failover (slaves can be promoted to master in case of a failure), it's just that ownCloud does neither support its monitoring tool (Sentinel) nor does it seem to support setting 2 Redis masters (similarly to setting multiple memcached_servers)... So in conclusion, the ownCloud documentation strongly recommends using Redis in a distributed system, but actually only supports a single Redis instance which certainly isn't what you want in a HA environment. 

Is there any good workaround for this? Would at least using local (independent) Redis instances work?

Thanks. 

(ownCloud version 8.2.1)

**Comment by LukasReschke** [comment]
Thanks a lot for your report. This is the bug tracker for bugs, please check https://owncloud.org/support to see resources on how to get support.

**Comment by GitHubUser4234** [comment]
@LukasReschke: Uhm, actually it is also feature request: While ownCloud's documentation strongly recommends Redis in a distributed environment, Redis is downright unusable here as ownCloud doesn't support a clustered configuration.
