### ISSUE TITLE
2015 year appears in some places in ownCloud server, instead of 2016

### ISSUE THREAD

**Issue by davitol** [owncloud/core#21431]
### Steps to reproduce

1. Configure a new ownCloud server

### Expected behaviour

The year shown should be 2016.

### Actual behaviour

The year shown is 2015 as it can be seen in the pictures attached

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: 9.0 pre alpha (daily) Build:2016-01-04T04:33:14+00:00 6ca2da7d5ccb9d3353c64125e196ad5a56ed4cfb

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

![screen shot 2016-01-04 at 10 16 30](https://cloud.githubusercontent.com/assets/10596560/12086867/3a9bc010-b2ce-11e5-91de-4950d34c8720.png)
![screen shot 2016-01-04 at 10 11 16](https://cloud.githubusercontent.com/assets/10596560/12086868/3a9f14b8-b2ce-11e5-93fe-b4bc5f9b582a.png)

**Comment by LukasReschke** [comment]
This is an enterprise edition bug. Nothing in core. Will fix anyways.
