### ISSUE TITLE
occ failure during command line installation

### ISSUE THREAD

**Issue by liuxunchen** [owncloud/core#21453]
### Steps to reproduce

1. dnf install owncloud
2. chown apache:apache /usr/share/owncloud
3. sudo -u apache php occ

### Expected behaviour
occ gives a list such as 

ownCloud version 8.0.9
Usage:
  command [options] [arguments]
Options:

### Actual behaviour
An unhandled exception has been thrown:
exception 'Exception' with message 'Not installed' in /usr/share/owncloud/lib/base.php:223
Stack trace:
#0 /usr/share/owncloud/lib/base.php(562): OC::checkInstalled()

### Server configuration
**Operating system**:
Fedora 23 server

**Web server:**
httpd-2.4.17
**Database:**
mariadb-1.10
**PHP version:**
php-5.6.16
**ownCloud version:** (see ownCloud admin page)
8.0.9
**Updated from an older ownCloud or fresh install:**
fresh
**List of activated apps:**

**The content of config/config.php:**
?php
$CONFIG = array (
    "log_type" => "syslog",
    "datadirectory" => "/var/lib/owncloud/data",
    "updatechecker" => false,
    "check_for_working_htaccess" => false,
    "asset-pipeline.enabled" => false,
    "assetdirectory" => '/var/lib/owncloud',

    "apps_paths" => array(
        0 =>
        array (
            'path'=> '/usr/share/owncloud/apps',
            'url' => '/apps',
            'writable' => false,
        ),
        1 =>
        array (
            'path' => '/var/lib/owncloud/apps',
            'url' => '/apps-appstore',
            'writable' => true,
        ),
    ),
);
            

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

**Comment by MorrisJobke** [comment]
`./occ` works on an uninstalled instance starting with owncloud 8.1.0. In owncloud 8.0.x this is not working and will not be backported, because there is no use case available in 8.0. Starting with 8.1.0 you can install an instance via occ.

I will close this here as won't fix.

**Comment by liuxunchen** [comment]
Thanks @MorrisJobke
