### ISSUE TITLE
Downloading a single file should not create a .zip

### ISSUE THREAD

**Issue by Zopieux** [owncloud/core#21452]
### Steps to reproduce
1. Select a single file.
2. Click *Download*.

### Current behavior
The download dialog pops up with `download.zip`.

### Expected behavior
The download dialog pops up to download the selected file with its own MIME type.

**Comment by DeepDiver1975** [comment]
Which OC version?

**Comment by Zopieux** [comment]
This is `8.2.2.2`.

**Comment by PVince81** [comment]
Might be an old bug.
But you're right. It should be possible to detect that the selection array only contains a single entry and then use the single download URL instead.

**Comment by MorrisJobke** [comment]
Fixed in #21599
