### ISSUE TITLE
lost password hash expire

### ISSUE THREAD

**Issue by michag86** [owncloud/core#21466]
If a user clicks on "lost password", the hash is stored until he changes it. But if the user remembers his old password, the password hash is valid until his next click on "lost password".

In my case there are about 100 users and the system is running for about a year and there are 10 lostpassword hashes.

If the reset mail with the link is sent unencrypted via smtp, maybe there is an mailadmin that knows the link too.

It would be useful if there is a timestamp generated and stored in oc_preferences as lostpasswordtime. So it would be possible to create an job that cleans up all hashs that are older as x hours (value from config.php).

**Comment by LukasReschke** [comment]
This is already implemented in 8.2. See https://github.com/owncloud/core/commit/db4cb1dd4d1266c3284052fcbbfc0acc042485a2 and https://github.com/owncloud/core/pull/18491

**Comment by michag86** [comment]
Oh sorry! I'm still using 8.1.x and searched for an issue before I created this.
Thanks!
