### ISSUE TITLE
[php7] Sabre\DAV\Exception\NotAuthenticated: HTTP/1.1 401 No basic authentication headers were found

### ISSUE THREAD

**Issue by skjnldsv** [owncloud/core#21461]
### Steps to reproduce
1. Install Owncloud 8.2.2
2. Install php7
3. Profit

### Expected behaviour
I should be able to connect to owncloud

### Actual behaviour
I get errors from multiple app:
1. Android:
```
org.apache.http.MalformedChunkCodingException: Chunked stream ended unexpectedly
org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:222)
org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:183)
org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:155)
org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:175)
org.apache.http.impl.io.ChunkedInputStream.exhaustInputStream(ChunkedInputStream.java:289)
org.apache.http.impl.io.ChunkedInputStream.close(ChunkedInputStream.java:262)
org.apache.http.entity.BasicHttpEntity.consumeContent(BasicHttpEntity.java:142)
org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:484)
org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
org.dmfs.dav.r.b(Unknown Source)
org.dmfs.dav.r.a(Unknown Source)
org.dmfs.dav.r.b(Unknown Source)
org.dmfs.dav.b.a(Unknown Source)
org.dmfs.dav.b.b(Unknown Source)
org.dmfs.caldav.lib.n.a(Unknown Source)
org.dmfs.caldav.lib.n.doInBackground(Unknown Source)
android.os.AsyncTask$2.call(AsyncTask.java:288)
java.util.concurrent.FutureTask.run(FutureTask.java:237)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
java.lang.Thread.run(Thread.java:841)

App: org.dmfs.caldav.lib
App version: 0.4.27
OS version: 19
OS Info: 4.4.4-android
```
2. Owncloud official client
```
01-05 13:32:28:675 14087 OCC::PassiveUpdateNotifier::versionInfoArrived: Client is on latest version!
01-05 13:32:56:980 14087 OCC::ConnectionValidator::checkServerAndAuth: Checking server and authentication
01-05 13:32:56:981 14087 OCC::AbstractNetworkJob::setTimeout: void OCC::AbstractNetworkJob::setTimeout(qint64) 27000
01-05 13:32:56:981 14087 unknown: QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State)
01-05 13:32:56:981 14087 OCC::AbstractNetworkJob::start: !!! OCC::CheckServerJob created for "https://xxxxxxxxx.xxx" + "status.php"
01-05 13:32:57:042 14087 OCC::CheckServerJob::finished: status.php returns:  QMap(("edition", QVariant(QString, ""))("installed", QVariant(bool, true))("maintenance", QVariant(bool, false))("version", QVariant(QString, "8.2.2.2"))("versionstring", QVariant(QString, "8.2.2")))   QNetworkReply::NetworkError(NoError)  Reply:  QNetworkReplyHttpImpl(0x1f33170)
01-05 13:32:57:043 14087 OCC::ConnectionValidator::slotStatusFound: ** Application: ownCloud found:  QUrl("https://xxxxxxxxx.xxx/status.php")  with version  "8.2.2" ( "8.2.2.2" )
01-05 13:32:57:043 14087 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
01-05 13:32:57:043 14087 OCC::AbstractNetworkJob::setTimeout: void OCC::AbstractNetworkJob::setTimeout(qint64) 27000
01-05 13:32:57:043 14087 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://xxxxxxxxx.xxx" + "/"
01-05 13:32:57:045 14087 unknown: QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State)
01-05 13:32:57:105 14087 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() QNetworkReply::NetworkError(RemoteHostClosedError) "Connection closed" QVariant(Invalid)
01-05 13:32:57:105 14087 OCC::AccountSettings::showConnectionLabel: "Pas de connexion à ownCloud sur <a href=\"https://xxxxxxxxx.xxx\">https://xxxxxxxxx.xxx</a>.\nConnection closed"
01-05 13:32:57:106 14087 OCC::FolderMan::slotAccountStateChanged: Account "admin@xxxxxxxxx.xxx" disconnected, terminating or descheduling sync folders
01-05 13:32:57:107 14087 OCC::PropfindJob::finished: PROPFIND request *not* successful, http result code is 0 ""
```
3. Nginx side
```
Sabre\DAV\Exception\NotAuthenticated: HTTP/1.1 401 No basic authentication headers were found /usr/share/webapps/owncloud/lib/private/connector/sabre/auth.php
- line 154: Sabre\DAV\Auth\Backend\AbstractBasic->authenticate(Object(OC\Connector\Sabre\Server), 'ownCloud') /usr/share/webapps/owncloud/lib/private/connector/sabre/auth.php
- line 127: OC\Connector\Sabre\Auth->auth(Object(OC\Connector\Sabre\Server), 'ownCloud') /usr/share/webapps/owncloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php
- line 118: OC\Connector\Sabre\Auth->authenticate(Object(OC\Connector\Sabre\Server), 'ownCloud') [internal function] Sabre\DAV\Auth\Plugin->beforeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response)) /usr/share/webapps/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php
- line 105: call_user_func_array(Array, Array) /usr/share/webapps/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php
- line 456: Sabre\Event\EventEmitter->emit('beforeMethod', Array) /usr/share/webapps/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php
- line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response)) /usr/share/webapps/owncloud/apps/files/appinfo/remote.php
- line 56: Sabre\DAV\Server->exec() /usr/share/webapps/owncloud/remote.php - line 137: require_once('/usr/share/weba...') {main}
```

### Server configuration
- Linux 4.3.3-2-ARCH
- Nginx 1.8.0
- mysql  Ver 15.1 Distrib 10.1.10-MariaDB, for Linux (x86_64) using readline 5.1
- PHP 7.0.1
- ownCloud 8.2.2 (stable)

```
Enabled:
  - activity: 2.1.3
  - calendar: 0.8.1
  - contactsplus: 1.0.9
  - direct_menu: 0.5
  - emoji: 0.1
  - fbsync: 1.7.3
  - files: 1.2.0
  - files_mv: 0.8.1a
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - firstrunwizard: 1.1
  - logreader: 1.1.2
  - ocsms: 1.5.0
  - ownbackup: 0.3.7
  - ownnote: 1.05
  - provisioning_api: 0.3.0
  - tasks: 0.8.1
  - theme_switcher: 2.0
  - updater: 0.6
Disabled:
  - admin_migrate
  - apptemplate
  - calendarplus
  - chat
  - contacts
  - django_auth
  - documents
  - encryption
  - encryption_dummy
  - external
  - files_archive
  - files_external
  - files_odfviewer
  - files_sgfviewer
  - files_svgedit
  - files_videoviewer
  - fluxx_compensator
  - impress
  - imprint
  - ownpad_lite
  - pong
  - pushnotifications
  - reader
  - search
  - tattoo
  - templateeditor
  - user_external
  - user_ldap
  - user_migrate
  - user_oauth
  - user_openid_provider
  - user_persona
  - user_saml
  - user_vd
  - user_webfinger
```
```
{
    "system": {
        "instanceid": "ocidnhjvvrqt",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "127.0.0.1",
            "xxxxxxxxx.xxx",
            "192.168.1.111"
        ],
        "datadirectory": "\/usr\/share\/webapps\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/127.0.0.1",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "theme": "",
        "maintenance": false,
        "loglevel": 0,
        "debug": true,
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": true,
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        }
    }
}
```

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**
Chromium 47.0.2526.106
Linux 4.3.3-2-ARCH

**Comment by skjnldsv** [comment]
Maybe is this a duplicate of #21352.
Not really sure. :/

**Comment by Xenopathic** [comment]
PHP 7 seems to be doing really weird things to DAV... I'm scared to update my Arch box in case it nukes my installation.

**Comment by skjnldsv** [comment]
@Xenopathic Don't do it!! Wait a bit! I didn't correctly watched the php version I was updating, and after seeing it was php7 and after owncloud said "PHP 7 Is Here And ownCloud Is Ready" I said to myself Well, it should be good!
Guess i was wrong and owncloud isn't php7 ready!

**Comment by Xenopathic** [comment]
@skjnldsv More like, PHP7 wasn't ready for release. We don't do anything magic in ownCloud, we use standard functions and interfaces that work fine with PHP 5.4 through to the latest PHP 5.6. PHP7 was supposed to be 100% backwards compatible - clearly it isn't.

**Comment by skjnldsv** [comment]
@LukasReschke what additional info do you need?

**Comment by Noctivivans** [comment]
I have similar error to @skjnldsv, but in owncloud desktop client (www seems to work fine):
## Actual behaviour
Message "connection closed" while trying to authenticate via owncloud desktop client. Existing sessions works until owncloud-client restart.

Error only occurs on PHP 7.x and php-apcu 5.1.2, downgrading PHP to 5.6.16 and php-apcu to 4.0.10 (php-apcu 5.x does not work for me with PHP 5.x) fixes problem.

### owncloud.log:
```
{"reqId":"u9f1uZfSbTQd0GgjXooP","remoteAddr":"***REMOVED SENSITIVE VALUE***","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(154): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#1 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(127): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#2 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/remote.php(137): require_once('\\\/usr\\\/share\\\/weba...')\\n#9 {main}\",\"File\":\"\\\/usr\\\/share\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2016-01-09T12:07:05+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/"}
```
### Nginx error.log:
```
2016/01/09 13:07:05 [error] 26423#0: *33 readv() failed (104: Connection reset by peer) while reading upstream, client: ***REMOVED SENSITIVE VALUE***, server: ***REMOVED SENSITIVE VALUE***, request: "PROPFIND /remote.php/webdav/ HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "***REMOVED SENSITIVE VALUE***"
```
## Server configuration
* Linux 4.3.3-2-ARCH
* Nginx 1.8.0
* mysql Ver 15.1 Distrib 10.1.10-MariaDB, for Linux (x86_64) using readline 5.1
* PHP 7.0.2
* PHP APCU 5.1.2 (with php-apcu-bc, refer to https://wiki.archlinux.org/index.php/OwnCloud#Caching)
* ownCloud 8.2.2 (stable)

### config.php

```
<?php
$CONFIG = array (
  'instanceid' => 'oce82dcfe86e',
  'passwordsalt' => '***REMOVED SENSITIVE VALUE***',
  'datadirectory' => '/srv/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.2.2.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost:/run/mysqld/mysqld.sock',
  'dbtableprefix' => 'oc_',
  'dbuser' => '***REMOVED SENSITIVE VALUE***',
  'dbpassword' => '***REMOVED SENSITIVE VALUE***',
  'installed' => true,
  'forcessl' => true,
  'language' => 'pl',
  'theme' => '',
  'maintenance' => false,
  'trashbin_retention_obligation' => '90, auto',
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'enable_previews' => true,
  'loglevel' => 0,
  'trusted_domains' => 
  array (
    0 => '***REMOVED SENSITIVE VALUE***',
    1 => '***REMOVED SENSITIVE VALUE***',
  ),
  'secret' => '***REMOVED SENSITIVE VALUE***',
  'forceSSLforSubdomains' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/usr/share/webapps/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/srv/owncloud/apps',
      'url' => '/wapps',
      'writable' => true,
    ),
  ),
);
```



### Enabled apps:
* Activity 2.1.3
* Deleted files 0.7.0
* Gallery 14.2.0
* PDF Viewer 0.7
* Share Files 0.7.0
* Text Editor 2.0
* Updater 0.6
* Versions 1.1.0
* Video Viewer 0.1.3

## Client configuration
* client version: 2.1.0 x86_64
* operating system: Archlinux x86_64 (different machine than server)

**Comment by JapSeyz** [comment]
I am running into this issue as well. It's extremely weird.

**Comment by fschwan** [comment]
Same issue here with PHP 7.

**Comment by DeepDiver1975** [comment]
Anybody mind testing current git master branch? We just updated sabredav which holds php7 fixes - THX

**Comment by fschwan** [comment]
@DeepDiver1975 Can you point me to a patch for current stable 8.2?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 Can you point me to a patch for current stable 8.2?

there is no patch for stable8.2 - the patch just arrived in master (upcoming oc9)

**Comment by Xenopathic** [comment]
Current master does not work with PHP7 and the oC client, client reports 'Connection closed' when setting up an account and this error is printed to the logs:

> {"reqId":"pO6fkau3JTdXbsgAy6mB","remoteAddr":"10.248.41.23","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/srv\\\/git@robin\\\/owncloud\\\/core\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/srv\\\/git@robin\\\/owncloud\\\/core\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/srv\\\/git@robin\\\/owncloud\\\/core\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/srv\\\/git@robin\\\/owncloud\\\/core\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(53): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/srv\\\/git@robin
\\\/owncloud\\\/core\\\/remote.php(137): require_once('\\\/srv\\\/git@robin\\\/...')\\n#6 {main}\",\"File\":\"\\\/srv\\\/git@robin\\\/owncloud\\\/core\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DA
V\\\/Auth\\\/Plugin.php\",\"Line\":188}","level":0,"time":"2016-01-14T11:17:54+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}

**Comment by DeepDiver1975** [comment]
Using php 7.0.1 and latest master setting up sync is not a problem for me locally

**Comment by Xenopathic** [comment]
Might be a bug in the client then, it seems to never send any credentials over at any point (verified using Wireshark), just some session cookies, and who knows where they came from...

**Comment by DeepDiver1975** [comment]
The first request is alway unauthenticated - this is where the exception in the log is coming from

**Comment by deviousway** [comment]
Same issue on Archlinux Nginx+php-fpm (PHP 7.0.2)

**Comment by deviousway** [comment]
fixed by disabling fastcgi_buffering in nginx vhost config
``` location ~ \.php(?:$|/) {
...
 fastcgi_buffering off;
...
```

**Comment by JapSeyz** [comment]
@deviousway Thank you!

**Comment by Noctivivans** [comment]
@deviousway : disabling fastcgi buffering helped me too, thanks! 
But I am wondering if that won't make any performance impact? According to nginx manual there is another option:
>Buffering can also be enabled or disabled by passing “yes” or “no” in the “X-Accel-Buffering” response header field.

I am guessing now, but maybe it can be disabled for authentication process only, without disabling for data transfer? As I mentioned before, when I updated/restarted php, existing connections remain intact until owncloud-client restart.

**Comment by deviousway** [comment]
@Noctivivans @JapSeyz 
you can use separate location for auth just use same settings as for 'php location' location ~ \.php(?:$|/)

 Make sure ~ \.php is BELOW the location /remote.php/webdav
for examle
```
location = /remote.php/webdav {
fastcgi_split_path_info ^(.+\.php)(/.+)$;
                        include fastcgi_params;
                        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                        fastcgi_param PATH_INFO $fastcgi_path_info;
                        fastcgi_param HTTPS on;
                        fastcgi_param MOD_X_ACCEL_REDIRECT_ENABLED on;
                        fastcgi_buffering off;
                        fastcgi_pass unix:/var/run/php-fpm/microsoft.sucks.sock;
}
 location ~ \.php(?:$|/) {
.....
}

```

**Comment by deviousway** [comment]
@Noctivivans  about performance impact, may but i'm use owncloud at home (me,wife and 5-7 friends) 
if users are more, then maybe you will notice something, but you can use separate location 
```
location = /remote.php/webdav
```

**Comment by Noctivivans** [comment]
@deviousway I am also using owncloud at home, I was just thinking about "general" solution (that may be added to official documentation) for all ownCloud users.

**Comment by timreeves** [comment]
Many thanks @Noctivivans and @deviousway - this I think puts us on the right track! I had already noted more-or-less the same problem at https://github.com/owncloud/core/issues/21352, and I tried out the new Nginx config fix. With some tweaking, it works!

**Tweak 1**: /remote.php/webdav is too specific - if you use CalDAV or CardDav you'll have URLs beginning /remote.php/caldav etc. Evereything after .php/ is PATH_INFO, anyway.

**Tweak 2**: Adding the "fastcgi_buffering off" only to location "remote.php" got CalDAV + CardDAV working, but NOT the ownCloud Client (files sync):

> 01-20 12:05:24:699 0x4e17bb0 OCC::AbstractNetworkJob::setTimeout: void OCC::AbstractNetworkJob::setTimeout(qint64) 27000
01-20 12:05:24:700 0x4e17bb0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://owncloud.example.com" + "/"
> 01-20 12:05:24:798 0x84585c0 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x84584b0) QHttpNetworkReply(0xa839ca0) 0 false 3 8 QAbstractSocket::ConnectedState
> 01-20 12:05:24:798 0x84585c0 unknown: ERRORING CURRENT QHttpNetworkReply(0xa839ca0)  QUrl( "https://owncloud.example.com/remote.php/webdav/" ) 

In other words it seems that the Client is also usinf a URL not below /remote.php. When I added the  "fastcgi_buffering off" to the main PHP-Block as well, then it worked.

**Tweak 3**: If you're using CalDAV then you'll NEED the fixed version of CalendarQueryValidator.php, see https://github.com/owncloud/calendar/issues/1002

**Recommendation:** Eager beavers like me can go for PHP7 as shown here - but if you don't need it I would wait until around April/May, when OC 9.0.1 comes out...

Finally, here the guts of Nginx-Config that WORKS (tailored to Ubuntu + Plesk + Own-PHP). Note that the extra location block for /remote.php is currently effectively redundant, since I had to duplicate it's add-ons to the main PHP block. At least it skips "try_files". But I retain hope that the fastcgi buffering can go back on in the main block at a later date, with a newer PHP plus OC 9.0.x, with the updated version of Sabre.

```
location = /remote.php {
  fastcgi_param PATH_INFO $fastcgi_path_info;

  # Extra fastcgi config from https://github.com/owncloud/core/issues/21461#issuecomment-173026172
  fastcgi_param HTTPS on;
  fastcgi_param MOD_X_ACCEL_REDIRECT_ENABLED on;
  fastcgi_buffering off;

  # Tell Nginx to pass authorization headers
  fastcgi_pass_header Authorization;
  # Avoid sending the security headers twice
  fastcgi_param modHeadersAvailable true;
  # You can add any application-special headers to $_SERVER here
  fastcgi_param PATH "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin";
  fastcgi_pass "unix:/usr/local/$sockname.sock";

  # TR: Sets SCRIPT_FILENAME as $document_root$fastcgi_script_name
  # TR: Meaning that $fastcgi_script_name MUST be correct now!
  include /etc/nginx/fastcgi.conf;
  # access_log off;
}

# PHP-Handling: Best of Plesk and ownCloud and Web-Forum articles
# A match here pre-empts Plesk's "location /", sends the script to PHP-FPM
# "(?U)" sets internal "ungreedy" option, i.e. to FIRST ".php" - NEED THIS HERE for PATH-INFO requests
location ~ ^((?U).+?\.php)(/.*)?$ {
  # TR: See http://wiki.nginx.org/HttpFastcgiModule#fastcgi_split_path_info
  # TR: Directive populates $fastcgi_script_name + $fastcgi_path_info
  # TR: BUT there's a problem: http://trac.nginx.org/nginx/ticket/321
  fastcgi_split_path_info ^((?U).+\.php)(/?.+)$;
  set $path_info $fastcgi_path_info;
  # Requested PHP Scripts MUST exist exactly as named
  try_files $fastcgi_script_name =404;
  # try_files has emptied $fastcgi_path_info
  fastcgi_param PATH_INFO $path_info;

  # Extra fastcgi config from https://github.com/owncloud/core/issues/21461#issuecomment-173026172
  fastcgi_param HTTPS on;
  fastcgi_param MOD_X_ACCEL_REDIRECT_ENABLED on;
  fastcgi_buffering off;

  # Tell Nginx to pass authorization headers
  fastcgi_pass_header Authorization;
  # Avoid sending the security headers twice
  fastcgi_param modHeadersAvailable true;
  # You can add any application-special headers to $_SERVER here
  fastcgi_param PATH "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin";
  fastcgi_pass "unix:/usr/local/$sockname.sock";
  # TR: Sets SCRIPT_FILENAME as $document_root$fastcgi_script_name
  # TR: Meaning that $fastcgi_script_name MUST be correct now!
  include /etc/nginx/fastcgi.conf;
  # access_log off;
}
```

**Comment by RealRancor** [comment]
New SabreDAV release for testing in https://github.com/owncloud/3rdparty/pull/246

**Comment by DeepDiver1975** [comment]
Please update to php 7.0.3 - it contains a fix relevant for fpm and unix sockets https://github.com/owncloud/core/issues/21935#issuecomment-177257772
