### ISSUE TITLE
owncloud decryption bug (unencrypted files)

### ISSUE THREAD

**Issue by MacsKavana** [owncloud/core#21465]
I have found that when I try to decrypt an user's files occ fails when it tries to decrypt an unencrypted file.

Probably this file was copied manually to the user's files directory so never was encrypted.

This is the log:

###############################
 decrypt files for user myusername (1 of 1): /myusername/files/myodtfile.odt 
 [--->------------------------]                                                  PHP Fatal error:  Call to a member function get() on null in /usr/share/nginx/html/apps/files_sharing/lib/updater.php on line 76
###############################

Current workaround: download the file and upload it via OC client or browser.

It would be nice if the decryption didn't fail on an unencrypted file.

Thank you!

**Comment by RealRancor** [comment]
@MacsKavana Can you fill out the issue template as asked in the guidelines for contributing (linked in the yellow box when creating a new issue). For example even the basic info which oC version you're running is missing.

**Comment by PVince81** [comment]
issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by PVince81** [comment]
CC @schiesbn

**Comment by MacsKavana** [comment]
Sorry guys, I forgot to attach the template but now it's uploaded: [oc.issue_template.txt](https://github.com/owncloud/core/files/83726/oc.issue_template.txt).

**I'd like clarify the issue description by the past days' experience**: this error happens on encrypted files (not on unencrypted ones).
The decryption is done, an error message is thrown and the process stops (OC remains in singleuser and maintenance mode).

When I start the process again, it fails on the same file which is already decrypted (that's why the original description of this issue).

The whole process can be seen here: [oc.decrypt-all.log.txt](https://github.com/owncloud/core/files/83725/oc.decrypt-all.log.txt)

**Comment by MacsKavana** [comment]
Well, after several tries this happens on all the files one by one:

1. the file gets unencrypted
2. the error message is dsiplayed
3. the decryption process stops
4. I have to move the decrypted file to a different directory (i.e. /home/macskavana/decrypted.files)
5. start over the decryption

**Comment by blizzz** [comment]
summoning @owncloud/encryption

**Comment by jknockaert** [comment]
>This is really nothing what you should do, especially with encryption enabled.

Well, this was actually supported at one point:
https://github.com/owncloud/core/pull/11659#issuecomment-60225105
Not sure if and when we gave up that functionality.

**Comment by RealRancor** [comment]
@jknockaert Mhh, you're quoting an 1 1/2 year old comment. The current documentation is telling the opposite:

> The data directory on the server is exclusive to ownCloud and must not be modified manually.

https://doc.owncloud.org/server/8.2/admin_manual/issues/index.html#debugging-sync-issues
https://doc.owncloud.org/desktop/2.1/troubleshooting.html#isolating-other-issues

**Comment by MacsKavana** [comment]
Hi guys,

As I pointed later out (on Jan 9) I was mistaken. There were no unencrypted files copied manually to the directory. Those unencrypted files were the ones I have decrypted with occ (but that time I didn't know I have to move them to a different directory).

**Comment by MacsKavana** [comment]
Hi again,

It seems that 9.0.1 solved the problem.
All the files are decrypted in one round without any problem.
Thanks!
