### ISSUE TITLE
Big Files Sync problem

### ISSUE THREAD

**Issue by Messa1** [owncloud/core#21471]
### Steps to reproduce
1. Owncloud 8.2.1
2. Windows Client 2.1
3. Upload "big" file > 200 MB

### Expected behaviour
Upload File

### Actual behaviour
Start uploading, stop after  short time.

### Server configuration
**Operating system**:
Linux 2.6.32-604.16.2.lve1.3.54.el6.x86_64 #1 SMP Mon Jul 27 11:32:29 EDT 2015 x86_64

**Database:**
MySQL 5.5

**PHP version:**
PHP Version 5.5.29

**ownCloud version:** (see ownCloud admin page)
8.2.1
**Updated from an older ownCloud or fresh install:**

**List of activated apps:**
Activity
Deleted files
First Run Wizard
Gallery
Mail Template Editor
Notifications
PDF Viewer
Provisioning API  
Share Files
Text Editor  
Updater
Versions
Versions

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' => 
  array (
    0 => 'www.mydomain.com',
    1 => 'cloud.mydomain.com',
  ),
  'datadirectory' => '/home/.sites/16/site839/web/owncloud/data',
  'overwrite.cli.url' => 'http://www.mydomain.com/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.2.1.4',
  'dbname' => 'xxx',
  'dbhost' => 'xxx',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'logtimezone' => 'UTC',
  'installed' => true,
  'loglevel' => 0,
  'DEBUG' => 1,
);

```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
Windows

**Operating system:**

#### Web server error log
```
Error	PHP	tempnam(): open_basedir restriction in effect. File(/tmp) is not within the allowed path(s): (/home/.sites/16/site839/web:/home/.sites/16/site839/tmp:/usr/share/pear) at /home/.sites/16/site839/web/owncloud/lib/private/tempmanager.php#228
```

#### ownCloud log (data/owncloud.log)
```
Error downloading http://cloud.maydomain.com/remote.php/webdav/cover 2.psd-chunking-1394233011-48-10 - server replied: Internal Server Error (An exception occurred while executing 'SELECT `fileid`, `storage`, `path`, `parent`, `name`, `mimetype`, `mimepart`, `size`, `mtime`,
					   `storage_mtime`, `encrypted`, `etag`, `permissions`
				FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ?' with params ["1", "7b109720be7fc00ba8ed0a6fdf8a5eb7"]:

SQLSTATE[HY000]: General error: 2006 MySQL server has gone away)```

**Comment by karlitschek** [comment]
The error message says that your mysql server has crashed. Please check your setup. Maybe you ar running out of ram or disk space.
Nothing we can do on the owncloud side.

**Comment by Messa1** [comment]
Problem is at a share host i can't set higher time out.
But "OWNCLOUD_CHUNK_SIZE=1000000" works perfect.
