### ISSUE TITLE
Accessing CardDAV causes segmentation fault with PHP 7

### ISSUE THREAD

**Issue by evmcl** [owncloud/core#21476]
OwnCloud 8.2.2
PHP 7.0.1
Apache HTTP 2.4.18
ArchLinux
Using either php7_module or fcgid

When trying to access the CardDAV URL for an address book, it causes the processing running PHP to have a segmentation fault.

To reproduce, go to your Contacts, click the setting cog in the bottom left, the click the little chain link icon to get the CardDAV URL. Copy to your clipboard.

Run curl -v <url> then check your /var/log/httpd/error_log for the error produced.

**Comment by evmcl** [comment]
Looking at [1002](https://github.com/owncloud/calendar/issues/1002) it looks likely there is an issue with the Sabre part of the libraries.

**Comment by MorrisJobke** [comment]
This is a duplicate owncloud/contacts#1002 but I keep this open, because master now includes the carddav code.

@DeepDiver1975 I think we need to also fix this in core for master once the sabre code is fixed upstream.

**Comment by RealRancor** [comment]
Quoting from https://github.com/owncloud/calendar/issues/1002:

> It's not the only PHP7 problem. All of these are fixed in master and will be released this week. Bit more info here: https://groups.google.com/forum/#!topic/sabredav-discuss/kHWTl4dT9jo

**Comment by DeepDiver1975** [comment]
Looks like php7 support will only come with sabre 3.1 ?

@evert do I understand this correctly?

**Comment by evert** [comment]
Yea the plan is to release 3.1 quickly so we have a version out there that supports PHP 7.

**Comment by DeepDiver1975** [comment]
> Yea the plan is to release 3.1 quickly so we have a version out there that supports PHP 7.

too bad - so we either support php7 or php5.4 with oc9 :cry:

**Comment by evert** [comment]
Could be a blessing in disguise ;)

**Comment by RealRancor** [comment]
So this is not only an issue within CalDAV/CardDAV but could also affect WebDAV?

If this is true that: https://owncloud.org/blog/php-7-is-here-and-owncloud-is-ready/ should be probably updated. :see_no_evil:

**Comment by DeepDiver1975** [comment]
> Could be a blessing in disguise ;)

not really - php 5.4 is a hard requirement for oc9 - php7 is supported since 8.2 - I'd rather not love to drop that.

@evert What are the necessary fixes which need backport to the 3.0 branch? I'm happy to help out with the backport and testing effort.

**Comment by evert** [comment]
The original reason to not support php 5.4 was because vobject 3 also had issues, which I had already fixed in vobject 4. So I don't fully know what the issues with PHP 5.4 were.

I would recommend simply starting by either

1. Add PHP 5.4 to `travis.yml` and setup travis for your github fork (or initiate a PR which will also trigger travis).
2. Make sure you have PHP 5.4 installed on your local machine and just run the unittests there.

I'm confident enough in the unittests to say that if the unittests pass, PHP 5.4 will probably work.

**Comment by DeepDiver1975** [comment]
> I'm confident enough in the unittests to say that if the unittests pass, PHP 5.4 will probably work.

so we are talking about bringing php 5.4 support back to sabre 3.1?

**Comment by evert** [comment]
No, sorry I edited my comment several times after that. Please re-read. I was confused

**Comment by DeepDiver1975** [comment]
:+1: let me take care of php7 in sabre 3.0 - THX

**Comment by JapSeyz** [comment]
@DeepDiver1975 @evert  Wasn't SabreDav 3.1 released already? http://sabre.io/blog/2016/sabre-dav-3.1-release/

Or am I completely misunderstanding something?

**Comment by evert** [comment]
Yes, but sabre/dav 3.1 dropped PHP 5.4 support.

**Comment by JapSeyz** [comment]
Ahh, but it doesn't support PHP 7 all that much either.  There's a lot of errors while trying to connect with the desktop client on a PHP 7 OC server

**Comment by evert** [comment]
sabre/dav 3.1 certainly does support PHP 7, owncloud is running sabre/dav 3.0 which does not currently.

**Comment by JapSeyz** [comment]
Ahh, then I follow. And PC doesn't upgrade because 5.4 is not supported?

**Comment by DeepDiver1975** [comment]
please retest with current git master - THX

regarding OC8.2 which uses Sabre 2.1.x - I honestly think php7 compat is out of scope - @evert

**Comment by evert** [comment]
It all depends on how easy or hard it is @DeepDiver1975 . I'm not strongly against it, as long as we can do it in ways that allow me to keep BC. The 2.1 branch _will_ get sabre/vobject 3.5 automatically, so that's not an issue. It's possible that the only change is the same as we did on the 3.0 branch.

**Comment by DeepDiver1975** [comment]
Let me give it a try then

**Comment by DeepDiver1975** [comment]
We did address this with 
sabre/dav 2.1.9 
sabre/dav 3.0.7 
sabre/vobject 3.4.9 and 3.5.0
