### ISSUE TITLE
Recovery keys should be disabled when master key is enabled

### ISSUE THREAD

**Issue by GitHubUser4234** [owncloud/core#21478]
Hello,

In the [ownCloud 8.2 documentation](https://doc.owncloud.org/server/8.2/admin_manual/configuration_files/encryption_configuration.html) it says that the master encryption key "replaces all individual user keys". Therefore, if I understood it correctly, recovery keys are obsolete when the master key is enabled as the user's password isn't needed for file decryption anyway. To avoid confusion, recovery keys and the recovery option as a whole should be hidden or disabled when the master key is enabled .

Thanks.

**Comment by MorrisJobke** [comment]
cc @schiesbn

**Comment by schiesbn** [comment]
> To avoid confusion, recovery keys and the recovery option as a whole should be hidden or disabled when the master key is enabled .

Yes, that's correct

**Comment by PVince81** [comment]
@sharidas does the modified UI cover this ?

**Comment by sharidas** [comment]
Yes when the master key is enabled the recovery keys are disabled in the UI screenshot -> 
![masterkeyui](https://user-images.githubusercontent.com/3600427/30195903-610c3d9e-947a-11e7-9409-cc57f57f22e9.png)
