### ISSUE TITLE
Unable to list available apps and unable to update

### ISSUE THREAD

**Issue by nroach44** [owncloud/core#21470]
### Steps to reproduce
1. Open OC
2. Switch to '+' Apps
3. Note the lack of categories / Note the failure of updates

### Expected behaviour
Updates should occur and I should be able to see available apps for installation

### Actual behaviour
Updates fail silently and no categories are shown

### Server configuration
**Operating system**:
Debian Jessie x86_64

**Web server:**
Apache 2.4.10-10+deb8u3

**Database:**
mysql 5.5.46-0+deb8u1

**PHP version:**
5.6.14+dfsg-0+deb8u1

**ownCloud version:**
8.2.1

**Updated from an older ownCloud or fresh install:**
Grandfathered all the way from 6.0 (possibly earlier)

**List of activated apps:**

```
Enabled:
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_versions: 1.1.0
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - notes: 1.0.0
  - ocsms: 1.5.0
  - updater: 0.6
Disabled:
  - activity
  - calendar
  - contacts
  - documents
  - encryption
  - external
  - files_external
  - files_locking
  - files_trashbin
  - files_videoviewer
  - notifications
  - provisioning_api
  - templateeditor
  - user_external
  - user_ldap

```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc046c2880c0",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "sync.haven"
        ],
        "datadirectory": "\/srv\/data\/oc\/data",
        "dbtype": "mysql",
        "version": "8.2.1.4",
        "dbname": "haven_owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "forcessl": true,
        "loglevel": 0,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        },
        "memcache.local": "\\OC\\Memcache\\Redis"
    }
}

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No 
### Client configuration
**Browser:**
Iceweasel (Firefox), numerous versions up to 43.2 (latest)

**Operating system:**
Debian Testing x86_64

#### Web server error log
```
Nothing applicable to OC
```

#### ownCloud log (data/owncloud.log)
Too large - but the lines that show when testing:
```
{"reqId":"CgqcvRyo2c0VhWCFo400","remoteAddr":"10.1.10.51","app":"core","message":"Could not get application: cURL error 28: Resolving timed out after 5514 milliseconds","level":3,"time":"2016-01-05T16:57:24+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=0"}
{"reqId":"On0tpVxiiBUzyZezsi5o","remoteAddr":"10.1.10.51","app":"core","message":"Could not get application: cURL error 28: Operation timed out after 0 milliseconds with 0 out of 0 bytes received","level":3,"time":"2016-01-05T16:57:40+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=1&includeUpdateInfo=0"}
{"reqId":"OcA6RkjHEd3OcK6aFRLY","remoteAddr":"10.1.10.51","app":"core","message":"No update found at the ownCloud appstore for app 166055","level":0,"time":"2016-01-05T16:57:46+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=1&includeUpdateInfo=1"}
{"reqId":"OcA6RkjHEd3OcK6aFRLY","remoteAddr":"10.1.10.51","app":"core","message":"No update found at the ownCloud appstore for app 166052","level":0,"time":"2016-01-05T16:57:47+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=1&includeUpdateInfo=1"}
{"reqId":"OcA6RkjHEd3OcK6aFRLY","remoteAddr":"10.1.10.51","app":"core","message":"No update found at the ownCloud appstore for app 166051","level":0,"time":"2016-01-05T16:57:49+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=1&includeUpdateInfo=1"}
{"reqId":"OcA6RkjHEd3OcK6aFRLY","remoteAddr":"10.1.10.51","app":"core","message":"No update found at the ownCloud appstore for app 166038","level":0,"time":"2016-01-05T16:57:53+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=1&includeUpdateInfo=1"}
{"reqId":"OcA6RkjHEd3OcK6aFRLY","remoteAddr":"10.1.10.51","app":"core","message":"No update found at the ownCloud appstore for app 160567","level":0,"time":"2016-01-05T16:57:55+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=1&includeUpdateInfo=1"}
{"reqId":"OcA6RkjHEd3OcK6aFRLY","remoteAddr":"10.1.10.51","app":"core","message":"No update found at the ownCloud appstore for app 166049","level":0,"time":"2016-01-05T16:57:58+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=1&includeUpdateInfo=1"}
{"reqId":"OcA6RkjHEd3OcK6aFRLY","remoteAddr":"10.1.10.51","app":"core","message":"No update found at the ownCloud appstore for app 166054","level":0,"time":"2016-01-05T16:57:59+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=1&includeUpdateInfo=1"}
{"reqId":"\/CPm9rtEzL7hCA19lZms","remoteAddr":"10.1.10.51","app":"core","message":"Could not get application: cURL error 28: Resolving timed out after 5513 milliseconds","level":3,"time":"2016-01-05T16:58:29+00:00","method":"POST","url":"\/index.php\/settings\/ajax\/updateapp.php"}
{"reqId":"\/CPm9rtEzL7hCA19lZms","remoteAddr":"10.1.10.51","app":"core","message":"Could not get application download URL: cURL error 28: Operation timed out after 0 milliseconds with 0 out of 0 bytes received","level":3,"time":"2016-01-05T16:58:34+00:00","method":"POST","url":"\/index.php\/settings\/ajax\/updateapp.php"}

```

#### Browser log
```
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://sync.haven 'unsafe-eval'"). apps
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery.min.js:5:17117

```

Additionally of note: I asked on IRC and user RealRancor linked me this: http://pastebin.com/MhRAymqk which returns HTTP200 on test, when tested in the OC dir.

**Comment by Xenopathic** [comment]
cURL error 28: Resolving timed out

Seems like you might have DNS resolving issues? Try that `doCurl()` test @RealRancor sent you but with the URL `https://api.owncloud.com/v1` instead

**Comment by nroach44** [comment]
Still gets HTTP200, takes a few seconds, is it possible OC is using a different timeout?

**Comment by karlitschek** [comment]
This is the dns resolving timeout of your operating system. This is a problem with your setup or internet connection or dns setup I assume. Nothing we can do on the owncloud side.

**Comment by nroach44** [comment]
Not helpful.
I would at least like some help in debugging it. This has been an issue for me for at least one major version, and I finally decided to stop working around it.

Everything else on this server and network has no issues with connections heading onto the internet.

**Comment by karlitschek** [comment]
sure. but this is the owncloud bugtracker not a support forum. Please check owncloud.org/support for options. Thanks .

**Comment by nroach44** [comment]
> This is the dns resolving timeout of your operating system.

It might be the set time out, but when I query the fqdn before I load the apps page it still does the same thing, which it shouldn't as the OS would already have the query cached. (Unless OC is ignoring the host cache)

**Comment by Xenopathic** [comment]
@nroach44 Typically the host doesn't do any caching, unless you specifically have a caching DNS server (e.g. Unbound or BIND) running locally and resolv.conf points at localhost. Linux (or more accurately, glibc) does no caching by itself.

**Comment by nroach44** [comment]
Ah, that's probably where I was getting confused as I am running a caching DNS server on my router.

That however raises another issue -  If I dig/ping the apps.owncloud.com server from my OC server and after a successful resolve load the apps page it will still "fail to resolve" the domain, which if it were actually trying to resolve it my router should have responded.
