### ISSUE TITLE
Directory shared via Link not mangling files in directory

### ISSUE THREAD

**Issue by mickg10** [owncloud/core#21472]
If a share a directory (even a local one) via a link, I can browse it just fine, and all directories in it are correct.
But links  to files look like
https://...../owncloud/public.php/webdav/DSC00721.JPG

when it should be mangling the name.
owncloud is at origin/master.

**Comment by karlitschek** [comment]
So why is this a problem? You see the filename anyways when click on the link?

**Comment by mickg10** [comment]
The problem is that clicking the _file_ link in the directory listing results in a WebDAV auth request.
Here is a shared directory. Clicking on the InnerFolder directory works. Clicking on the PDF file does not.
https://secure.mickg.net/own_git/core/index.php/s/7DCNhcNAZKgmznQ

Reproduction:
1. Create folder to be shared - OuterFolder.
2. Create inner folder - OuterFolder/InnerFolder
3. Create test file in - OuterFolder/FILE.
4. Share OuterFolder via link.
5. Visit link. 
6. Click FILE link - needs webdav authentication. Cannot access the file.
