### ISSUE TITLE
Two requests using FolderSync (FolderSync uploads files twice)

### ISSUE THREAD

**Issue by kayrus** [owncloud/core#21486]
ownCloud 8.2.1 (stable) + nginx + fastcgi (with the following config: https://github.com/owncloud/documentation/blob/master/admin_manual/installation/nginx_configuration.rst) + `fastcgi_buffering off;`

I'm not sure to whom is it related but it seems like to ownCloud core, not to FolderSync.

The problem is that FolderSync tries to use cookies which were acquired by authentication. But for some reason these cookies are not valid.

As a result we receive following behavior:

```
123.123.123.123 - - [06/Jan/2016:14:04:58 +0100] "PUT /remote.php/webdav/big.file.tacitpart HTTP/1.1" 401 278 "-" "android-cloud-api - Android 4.4.2"
123.123.123.123 - user [06/Jan/2016:14:05:03 +0100] "PUT /remote.php/webdav/big.file.tacitpart HTTP/1.1" 201 25 "-" "android-cloud-api - Android 4.4.2"
```

Here is how I see its behavior (thanks tcpdump and HTTPS proxy):

* > At the very first request (not logs above) FolderSync tries to make a request with the old cookie and without "Authorization" header.
* < ownCloud responds that credentials are invalid and set new "oc_sessionPassphrase" and "ocjutnjgekvm" cookies.
* > FolderSync saves this cookie and next request contains "Authorization" header.
* < ownCloud responds with the non-error code.
* > FolderSync tries to make new request without "Authorization" header but with "oc_sessionPassphrase" and "ocjutnjgekvm" cookies.
* < ownCloud responds with the 401 error code.
* > FolderSync tries to make next request with the "Authorization" header and so on...

As a result when you have 500Mb file it is uploaded twice. That takes extra time and traffic.

I'm not sure whether this behavior (using cookies instead of auth) is correct.

P.S. Probably relates to https://github.com/owncloud/core/issues/18568 and https://github.com/owncloud/core/issues/19969

**Comment by guruz** [comment]
Very probably related: https://github.com/owncloud/client/issues/4326#issuecomment-169282743
:-)

**Comment by kayrus** [comment]
@guruz is there any workaround available?

**Comment by PVince81** [comment]
Looks like there is a fix here https://github.com/owncloud/core/pull/21491 in case you want to help testing @kayrus

**Comment by kayrus** [comment]
@PVince81 looks like I don't have "apps/dav/" directory in my ownCloud 8.2.1 installation...

**Comment by PVince81** [comment]
Ah sorry, the Webdav code has moved on master and changed slightly so the patch is unlikely to apply.

**Comment by loripino21** [comment]
I have owncloud 9.0.0 and using FolderSync 2.8.5.90. It seems I still have this issue. Is it possible? If not, what could be the cause?
