### ISSUE TITLE
Cannot access files in directories shared via link

### ISSUE THREAD

**Issue by mickg10** [owncloud/core#21487]
The problem is that clicking the file link in the directory accessed via shared link listing results in a WebDAV auth request. 
For an example : link goes to a shared directory. Clicking on the InnerFolder directory works. Clicking on the PDF file does not.
https://secure.mickg.net/own_git/core/index.php/s/7DCNhcNAZKgmznQ

Reproduction:
1. Create folder to be shared - OuterFolder.
2. Create inner folder - OuterFolder/InnerFolder
3. Create test file in - OuterFolder/FILE.
4. Share OuterFolder via link.
5. Visit link. 
6. Click FILE link - needs webdav authentication. Cannot access the file.

At origin/master, fresh install.
A followup to https://github.com/owncloud/core/issues/21472 with a better description.

**Comment by karlitschek** [comment]
@schiesbn

**Comment by rullzer** [comment]
and @PVince81

**Comment by MorrisJobke** [comment]
> At origin/master, fresh install.

@mickg10 Can I ask you to specify this more concrete, because there was a similar issue some weeks ago that was fixed recently.

**Comment by mickg10** [comment]
Buggy as of d39551

**Comment by PVince81** [comment]
Tried the link in the OP and I see this header being returned by the server:
```
WWW-Authenticate:Basic realm="sabre/dav"
```

Usually the realm is ownCloud, so it looks like something might be using a different code path here and doesn't go into our authentication classes (PublicAuth).

**Comment by PVince81** [comment]
But also I see that the token is missing from the URL.
Normally the token needs to be prepended before the host name.

I'll have a look.

**Comment by PVince81** [comment]
Problem is reproducible on master 336fe868b2ee3a4105b93b71a1e739c9e412237b

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/21503
