### ISSUE TITLE
Memory Problems Owncloud Client on Windows (2012 and 7) hosted on VMware

### ISSUE THREAD

**Issue by Stephan-ch** [owncloud/core#21497]
I updated my virtual machines (windows 7 and server 2012) to the last client version in december 15 an got since then bluescreens and sometimes reboot of the whole esxi server (5.5). 
Bluescreen told memory problems.... 
I changed the hardware, so the problem isn't a hardware problem. Did you changed the mem-management of the client?

**Comment by MorrisJobke** [comment]
Hi @Stephan-ch Please reopen this in the client bug tracker: https://github.com/owncloud/client/issues Thanks :)
