### ISSUE TITLE
Why are some PR checks passing and why are some checks stuck

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#21504]
@PVince81 @DeepDiver1975 

Question: I have two PR´s (#21445 and #21449) and both are stuck at the check at the same place.
If I go to the details link of #21449 at the first item where it is stuck https://ci.owncloud.org/job/server-master-linux-php7-ci/database=sqlite,label=SLAVE/29974/
I get as result only:
```
HTTP ERROR 404

Problem accessing /job/server-master-linux-php7-ci/database=sqlite,label=SLAVE/29974/. Reason:

    Not Found
Powered by Jetty://
```

First I thought it maybe a problem because I used mmattel/xxxx as branch, but when I look to  #21467, the branch is owncloud/xxxx and it is stuck the same point.

What am I missing or what can be done to complete the checks?

**Comment by RealRancor** [comment]
@mmattel CI for forks like yours is currently not working at all: https://github.com/owncloud/core/issues/19885

**Comment by DeepDiver1975** [comment]
@mmattel - @RealRancor is right - we currently have no possibility to run ci on forks - which is a big issue ... but is not easy either. :cry:

**Comment by DeepDiver1975** [comment]
Let's continue the discussion in #19885
