### ISSUE TITLE
Scroll to newly created user after creation

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#21508]
### Steps
1. Go to the users management page
2. Create 20-30 users
3. Refresh the page
4. Create a user with a name that would appear at the bottom of the list
### Expected result

List autoscrolls and highlights the newly created user, like the file list app does for new files.
### Actual result

User is created but the list doesn't scroll.

Side note: it would be nice to have generic list components with the same behavior that can be reused for files, users, etc so we don't need to reimplement the same behaviors everywhere.
### Versions

Observed on master 9.0 git pre-alpha

@owncloud/designers

**Comment by jancborchardt** [comment]
Totally agree this is an issue. Seems to be JS specifically rather than design tho, right?

**Comment by PVince81** [comment]
Yes, JS. I pinged design to get a confirmation that it's what we want.
