### ISSUE TITLE
Error message about a wrong expiration date of a shared link is not very specific.

### ISSUE THREAD

**Issue by davitol** [owncloud/core#21518]
### Steps to reproduce
1. Share a file
2. Set an expiration date using the calendar
3. Modify the expiration date writing in the textbox a new but 'wrong' date (e.g. 12-13-2016) 
### Expected behaviour

A message about wrong date format should be shown
### Actual behaviour

The message info is 'not clear'  for a user
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:  ownCloud Enterprise Edition 9.0 pre alpha (daily) Build:2016-01-07T04:44:34+00:00 d3922510d01fb5feed3ea01a3d390dfaa8b1312f

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Firefox

![screen shot 2016-01-07 at 17 56 07](https://cloud.githubusercontent.com/assets/10596560/12177007/6b30d758-b56a-11e5-9ef4-d72020c9a922.png)

**Comment by PVince81** [comment]
Looks like a generic "parse error" message, likely returned by the PHP code.

@rullzer

**Comment by rullzer** [comment]
Probaly fixed once https://github.com/owncloud/core/issues/21554 is in

**Comment by rullzer** [comment]
Ok the error is better now. But incorrect. Since it states that the format must be YYYY-MM-DD. But that is for the OCS Share API. We input the date differently.

I would actually prefer here to handle this gracefully on the client side. So detect invalid dates in javascript.

**Comment by PVince81** [comment]
the dialog has changed in OC 10, please retest in OC 10 and reopen if the bug persists there
