### ISSUE TITLE
Profile picture is not being updated the 2nd time it is set

### ISSUE THREAD

**Issue by davitol** [owncloud/core#21513]
### Steps to reproduce

1. Go to personal settings
2. Upload a Profile photo
3. Choose the photo
4. Upload another Profile photo
5. Choose this new photo

### Expected behaviour

The photo should be updated

### Actual behaviour

The photo shown is the previous one

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:  ownCloud Enterprise Edition 9.0 pre alpha (daily) Build:2016-01-07T04:44:34+00:00 d3922510d01fb5feed3ea01a3d390dfaa8b1312f

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

![changeavatar](https://cloud.githubusercontent.com/assets/10596560/12174503/250d8a30-b55d-11e5-8285-f52822d96602.gif)

**Comment by karlitschek** [comment]
caching issue?

**Comment by davitol** [comment]
clearing the cache, the issue still happening.

**Comment by PVince81** [comment]
@rullzer

**Comment by rullzer** [comment]
Aaaah I think I get why this is happening... let me verify

**Comment by rullzer** [comment]
Ok yeah, since we do more agressive caching of generated avatars on the server side. We have to make sure to delete all resized avatars as well.

Fix in #21527
