### ISSUE TITLE
Mail notification checkbox not shown in sharee list

### ISSUE THREAD

**Issue by rzg-kaiser** [owncloud/core#21511]
### Steps to reproduce
1. Settings: allowMailNotification=yes, allowPublicMailNotification=no
2. Share a file with another (internal) ownCloud user

### Expected behaviour
"Notify by email" checkbox should be shown in sharee list on the right

### Actual behaviour
"Notify by email" checkbox doesn't show up, unless allowPublicMailNotification is set as well

### Affected version
8.2.2 EE as well as git master 601457d

### Likely issue
Wrong (copy/pasted?) if statement in:
core/js/sharedialogshareelistview.js:29

**Comment by PVince81** [comment]
Could be by design, not sure.

@nickvergessen @rullzer do you know ?

**Comment by cdamken** [comment]
@MorrisJobke 
	
00004519

**Comment by rullzer** [comment]
@PVince81 no idea...

**Comment by MorrisJobke** [comment]
I already noticed this some time back. I need to retest and try to find the issue here.

**Comment by MorrisJobke** [comment]
@rzg-kaiser This will be fixed in 8.2.3

**Comment by rzg-kaiser** [comment]
@MorrisJobke Thanks a lot for the quick reaction!
