### ISSUE TITLE
Deprecation of "forcessl" option silent

### ISSUE THREAD

**Issue by clarjon1** [owncloud/core#21514]
Hello

After a refresh of my firefox and the removal of https-everywhere, I discovered that the forcessl option was no longer redirecting http to https. After looking in the admin for errors or a notification, I was confused to find out that there was nothing telling me why this was no longer functional.

It took some digging through the documentation to find that the option has been deprecated, and using htaccess or the virtualhost configuration to setup the redirect was now the recommended way to do it, but this was not made obvious at all -- in fact googling for the issue only led me to instructions on how to setup the now deprecated function.

I propose the addition of code that, when it detects the deprecated "forcessl" option, a message will be generated in the administrative panel for owncloud, similar to the markup I quickly whipped up via my browser's Inspect Element tool, with the word "documentation" being a link to the relevant documentation: http://i.imgur.com/SiBMj5x.png

This way administrators would be made more quickly aware that a) this change has been made, and they need to reconfigure their setup, and b) they can clean out the config.php file so as to not have to worry about that setting becoming an issue in the future, in the event that a future addon or feature of owncloud might use the same name, and cause issues.

**Comment by karlitschek** [comment]
I agree. We have to communicate this better in the future or not remove a feature at all. @LukasReschke @jospoortvliet FYI
Closing because this is too late. Let's do better next time
