### ISSUE TITLE
Cannot remove share in OC 8.2.2 (data and database restored from 8.0.4)

### ISSUE THREAD

**Issue by anduz** [owncloud/core#21516]
There is no possibility to edit a share like in 8.0.4, please see attached pics.
![oc8 0 4](https://cloud.githubusercontent.com/assets/4547041/12176044/c6fdfa2a-b565-11e5-8b3a-bb55a7f797d0.PNG)
![oc8 2 2](https://cloud.githubusercontent.com/assets/4547041/12176050/cb493914-b565-11e5-93af-13ed866236ff.PNG)

**Comment by PVince81** [comment]
Something looks broken in your instance. There is no file name on the left of the rename icon ?

Are you saying that the "Teilen" (Sharing) tab in the sidebar is empty ?
Are there any entries in the owncloud log or the Javascript console ?

You should use the issue template to provide more info about your setup (LDAP, etc): https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by PVince81** [comment]
Closing due to lack of feedback

**Comment by anduz** [comment]
Sorry for my late reply

I don't know exactly why the name was missing,
Yes, the sidebar was empty, so there must be something wrong, either in the
backup/restore or somewhere else.


2016-03-01 16:37 GMT+01:00 Vincent Petry <notifications@github.com>:
