### ISSUE TITLE
External storage (even local) only accessible to admin users

### ISSUE THREAD

**Issue by mickg10** [owncloud/core#21529]
Symptom: external storage mounts only accessible to admin users.

Prerequisites:
1 admin user (at least)
1 non-admin user (at least)

Reproduction:
1. As admin user, create local external mount, let's say mnt.
2. Verify that a different admin user has access to mnt. 
3. Log in as non-admin user.
4. Try to access mnt. This will fail. This is the bug.

More info:
Just pulled to master, still there.
Bug manifests itself with and without ldap backend.
Bug manifests itself with local and SMB shares, at least.

In log there is this suspicious thing:
Debug	no app in context	Logged in user must be an admin

**Comment by PVince81** [comment]
To clarify: this was observed by @mickg10 on master. (would be good if you could always clearly state which version you are using)

@Xenopathic @icewind1991

**Comment by Xenopathic** [comment]
#21467?

**Comment by icewind1991** [comment]
> #21467?

Sounds like it

**Comment by Xenopathic** [comment]
@mickg10 Could you retry with the latest master? A fix was merged that should solve this issue.

**Comment by mickg10** [comment]
Confirmed fixed at 7528fe5a8840615520469d58c8be37a7a5ff72f4
