### ISSUE TITLE
SFTP external backend lacks proper isUpdatable method implementation

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#21526]
See: https://github.com/owncloud/files_texteditor/issues/155#issuecomment-167980906

The SFTP backend extends the common storage backend class and hence only uses the default isUpdatable() method which returns true if the file exists (https://github.com/owncloud/core/blob/master/lib/private/files/storage/common.php#L121).

Would be great if we could return a value from the file mode retrieved with stat() so that things like the editor could enable/disable editing appropriately as currently the UI thinks it can save, but the saves end up failing.

@PVince81 @Xenopathic

**Comment by PVince81** [comment]
This is causing other more serious issues: https://github.com/owncloud/core/issues/23781

**Comment by PVince81** [comment]
@bantu is that even possible or was that a limitation of phpseclib ?

**Comment by bantu** [comment]
You can at least look at the file mode as per the ticket description.

**Comment by SergioBertolinSG** [comment]
Not sure if related but the https://github.com/owncloud/files_texteditor/issues/155 issue is happening also when using another external storage (WND) without permissions.
