### ISSUE TITLE
Error while updating from 8.0.2 t0 8.2.2

### ISSUE THREAD

**Issue by marcelkraan** [owncloud/core#21520]
Hello,

I have an error while updating
The old version is 8.0.2 and i try to update it to 8.2.2
I instealled the ownloud manually and not via yum
 
CentOS Linux release 7.2.1511 (Core)
mysql  Ver 15.1 Distrib 5.5.44-MariaDB, for Linux (x86_64) using readline 5.1

The console error =
sudo -u apache php occ upgrade
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug - current level: 'Warning'
Turned on maintenance mode
Exception: Updates between multiple major versions and downgrades are unsupported.
Update failed
Maintenance mode is kept active
Reset log level to 'Warning'

Maybe this is small else i stay at the old version

This web interface error =)
...
Updating ownCloud to version 8.2.2, this may take a while.

Preparing update
Set log level to debug - current level: "Warning"
Turned on maintenance mode
Exception: Updates between multiple major versions and downgrades are unsupported.
The update was unsuccessful. Please report this issue to the ownCloud community.

This is my config.php
<?php
$CONFIG = array (
  'instanceid' => 'oc1xcnwjnn84',
  'passwordsalt' => 'xxxxxxxxxxxxxxxx',
  'secret' => 'xxxxxxxxxxxxxxxxxxxxxxxxx',
  'trusted_domains' =>
  array (
    0 => '192.168.123.1',
    1 => 'gateway.blabla.net',
  ),
  'datadirectory' => '/opt/ocdata',
  'overwrite.cli.url' => 'http://192.168.123.1/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.2.0',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'xxxxxxxxxxxxxx',
  'installed' => true,
  'forcessl' => false,
  'mail_from_address' => 'root',
  'mail_smtpmode' => 'sendmail',
  'mail_domain' => 'blabla.net',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpauthtype' => 'PLAIN',
  'theme' => '',
  'maintenance' => false,
);
~

**Comment by marcelkraan** [comment]
i think my question is here:
https://github.com/owncloud/core/issues/21186

Thanks

**Comment by RealRancor** [comment]
@marcelkraan You can close this issue as you don't need to report this here and just do the correct upgrade path as shown in https://github.com/owncloud/core/issues/21496 or the various other duplicates available here.
