### ISSUE TITLE
General question: when is the update server going to reflect the latest release?

### ISSUE THREAD

**Issue by brevilo** [owncloud/core#21528]
Not sure this repo is the correct one for asking this question...

Admins using the updater app depend on the new update server providing the latest release in a timely manner. What's the policy/process regarding updating the version information returned by the server? Right now [it still returns 8.2.1](https://updates.owncloud.com/server/?version=8x0x0x7x1382907615.86x1435439812xstablexx2015-02-07T02:34:55+00:00) despite 8.2.2 being released and announced more than two weeks ago.

Thanks

**Comment by RealRancor** [comment]
@brevilo The developers mailinglist is the best place to ask such questions as this is no bug/feature. There you can find an existing discussion about that recurring issue:

http://owncloud.10557.n7.nabble.com/Update-available-via-admin-interface-td16048.html

**Comment by brevilo** [comment]
Sure, thanks.

**Comment by brevilo** [comment]
FWIW, there's an actual issue at https://github.com/owncloud/updater/issues/183 which discusses this, well, issue. As discussed in the thread mentioned above and in the updater issue, the process is broken right now and needs fixing (i.e. immediate availability of new releases on the `stable` release channel).
