### ISSUE TITLE
consider adopting predis library to remove redis php extension requirement

### ISSUE THREAD

**Issue by lsmith77** [owncloud/core#21521]
see https://github.com/nrk/predis

This is a pure PHP library. There is an optional PHP extension to speed up serialization https://github.com/nrk/phpiredis. As you can see the library is seeing quite a lot of use https://packagist.org/packages/predis/predis.

For example on my synology it is quite a lot easier to install Redis, than it is to try and install the PHP redis extension. I assume the same will apply to many users in other setups as well. Given that Redis is recommended to get transactional file locking (https://doc.owncloud.org/server/8.2/admin_manual/configuration_files/files_locking_transactional.html), it seems like it would be a good idea to make it as easy as possible to get Redis support.

**Comment by DeepDiver1975** [comment]
Are there any statistics regarding performance and memory foot print comparing this php lib to the native module? THX

**Comment by Xenopathic** [comment]
@DeepDiver1975 https://github.com/nrk/predis/blob/v1.0/FAQ.md#speaking-about-performances

**Comment by RealRancor** [comment]
Pull request to use predis in https://github.com/owncloud/core/pull/24033

**Comment by PVince81** [comment]
@butonic which one are we using now ?
