### ISSUE TITLE
SMB/CIFS support for using user as share name 

### ISSUE THREAD

**Issue by mickg10** [owncloud/core#21530]
In previous versions, the SMB/CIFS backend supported the use of the username as the share.

As of some time ago on origin/master, this feature is gone now - or at least I cannot figure out how to make it work.

Placing $user as the share does not work.

**Comment by PVince81** [comment]
I don't think this feature has been removed.

Can you provide more details about your setup and logs ?
See issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

CC @Xenopathic @icewind1991

**Comment by Xenopathic** [comment]
On (noarly) current master, this feature works for me (as in, `$user` is correctly replaced with the username when the storage is used). That was tested with a Local storage

**Comment by mickg10** [comment]
Xenopathic - actually you are right. Just tried it with a local user, and it works as intended.

The issue seems to stem from the LDAP user backend using UUIDs as internal usernames, actually.
Example username: 0B2A1968-8EEE-4722-B14D-76F4AE6BE36E
What fixed it is going to Settings->LDAP->Expert and setting "Internal Username Attribute" to samaccountname, and then clearing Username-LDAP user mappings. This forces the internal names to use domain usernames, as expected. Would not work with multiple domains, I think, if there are samaccountname collisions.

Not sure how to resolve this in the general case...
Should we close this and move it somewhere else?

**Comment by Xenopathic** [comment]
:warning: Changing the UUID WILL nuke all your shares, versions, and (maybe) data! We need to rethink how the `$user` placeholder works... probably too late for 9.0, maybe 9.1

**Comment by mickg10** [comment]
Sure. Maybe have a checkbox (and warning) or something in the LDAP config box? People generally configure this before they have any data...

**Comment by blizzz** [comment]
> Sure. Maybe have a checkbox (and warning) or something in the LDAP config box? People generally configure LDAP before they have any data...

It's documented on-tab in the LDPA config wizard as well as in the documentation. Though, maybe it is too technical? There's also a feature request to use the username by default (https://github.com/owncloud/core/issues/10583), however it's not necessarily guaranteed to be unique (maybe good enough).

OTOH even if it is configured properly there not guarantee that the uid will identicall be the internal username (e.g. allowed characters restriction, already existing users with the same name). Thus a smarter mechanism on files_external site, probably via a third component, would be more reliable.

**Comment by blizzz** [comment]
So far, however, this is a config issue, so I am closing this.
