### ISSUE TITLE
Creating a new file, the sum of the number of files is increased +2

### ISSUE THREAD

**Issue by davitol** [owncloud/core#21535]
### Steps to reproduce

1. Go to files view
2. Create a new text file

### Expected behaviour

The result of the sum of files/should be increased +1

### Actual behaviour

The result of the sum is increased +2

Note: If you refresh the screen, the result of the sum turns into the right number.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:  ownCloud Enterprise Edition 9.0 pre alpha (daily) Build:2016-01-07T04:44:34+00:00 d3922510d01fb5feed3ea01a3d390dfaa8b1312f

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

![screen shot 2016-01-08 at 10 02 12](https://cloud.githubusercontent.com/assets/10596560/12194276/06065738-b5ef-11e5-90b0-315e60ef82ea.png)

**Comment by davitol** [comment]
Could be related to https://github.com/owncloud/core/issues/21534

**Comment by PVince81** [comment]
Yes, similar.

**Comment by rullzer** [comment]
PR in #21573

**Comment by rullzer** [comment]
PR merged. Closing.
