### ISSUE TITLE
apt-get install owncloud fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by dhuyvetter** [owncloud/core#21531]
On my Ubuntu VPS I added the owncloud repo and tried to install owncloud, but get dependency issues:

	# apt-get install owncloud
	Reading package lists... Done
	Building dependency tree       
	Reading state information... Done
	Some packages could not be installed. This may mean that you have
	requested an impossible situation or if you are using the unstable
	distribution that some required packages have not yet been created
	or been moved out of Incoming.
	The following information may help to resolve the situation:

	The following packages have unmet dependencies:
	 owncloud : Depends: owncloud-server (= 8.2.2-1.1) but it is not going to be installed
		        Recommends: owncloud-config-apache (= 8.2.2-1.1) but it is not going to be installed
	E: Unable to correct problems, you have held broken packages.

Trying to install owncloud-server ofcourse brings up another unmet dependency:

	# apt-get install owncloud-server
	Reading package lists... Done
	Building dependency tree       
	Reading state information... Done
	Some packages could not be installed. This may mean that you have
	requested an impossible situation or if you are using the unstable
	distribution that some required packages have not yet been created
	or been moved out of Incoming.
	The following information may help to resolve the situation:

	The following packages have unmet dependencies:
	 owncloud-server : Depends: php5-intl but it is not going to be installed
	E: Unable to correct problems, you have held broken packages.

I've got my LAMP stack installed on the server, Wordpress is running. Any tips on getting past this?

**Comment by RealRancor** [comment]
Hi,

seems you have a broken package setup as php5-intl can't be installed which is not an issue of the owncloud packages itself.

What happens when trying to apt-get install php5-intl

**Comment by dhuyvetter** [comment]
# apt-get install php5-intl
	Reading package lists... Done
	Building dependency tree       
	Reading state information... Done
	Some packages could not be installed. This may mean that you have
	requested an impossible situation or if you are using the unstable
	distribution that some required packages have not yet been created
	or been moved out of Incoming.
	The following information may help to resolve the situation:

	The following packages have unmet dependencies:
	 php5-intl : Depends: php5-common (= 5.5.9+dfsg-1ubuntu4) but 5.5.9+dfsg-1ubuntu4.14 is to be installed
	E: Unable to correct problems, you have held broken packages.

And then:

	# apt-get install php5-common
	Reading package lists... Done
	Building dependency tree       
	Reading state information... Done
	php5-common is already the newest version.
	0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.

Dependecy hell!

**Comment by RealRancor** [comment]
@dhuyvetter apt-get dist-upgrade :-)

Overall thats not an issue of ownCloud. @PVince81 @MorrisJobke I think the packaging tag can be removed here.

**Comment by dhuyvetter** [comment]
There seems to be an issue with the owncloud-server dependencies, I've downgraded php5-common to the version required by php5-intl, which is required by owncloud-server, but still get an error:

	~# apt-get install owncloud-server
	Reading package lists... Done
	Building dependency tree       
	Reading state information... Done
	Some packages could not be installed. This may mean that you have
	requested an impossible situation or if you are using the unstable
	distribution that some required packages have not yet been created
	or been moved out of Incoming.
	The following information may help to resolve the situation:

	The following packages have unmet dependencies:
	 owncloud-server : Depends: php5-intl but it is not going to be installed
	E: Unable to correct problems, you have held broken packages.
	root@zonk:~# apt-get install php5-intl
	Reading package lists... Done
	Building dependency tree       
	Reading state information... Done
	php5-intl is already the newest version.
	0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

**Comment by dhuyvetter** [comment]
@RealRancor I also did `apt-get update --fix-missing` and `apt-get upgrade -f` and `apt-get dist-upgrade`. 

This is a pretty new system, and the only source outside of the official Ubuntu ones I have added is the owncloud one, as instructed on https://download.owncloud.org/download/repositories/stable/owncloud/ which is why I think it is an owncloud related issue. 

	# find /etc/apt/ -name "*.list" -exec bash -c 'printf "\n%s\n%s\n%s\n" "========" "$1" "========"; cat "$1"' _ {} \;

	========
	/etc/apt/sources.list.d/owncloud.list
	========
	deb http://download.owncloud.org/download/repositories/stable/Ubuntu_14.04/ /

	========
	/etc/apt/sources.list
	========
	deb http://nl.archive.ubuntu.com/ubuntu trusty main
	deb http://security.ubuntu.com/ubuntu trusty-updates main
	deb http://archive.ubuntu.com/ubuntu trusty universe

The two answers I find on https://askubuntu.com/ concerning php5-intl say it is a problem with sources or PPA's.

**Comment by RealRancor** [comment]
@dhuyvetter Whats the output of:

apt-cache policy php5-intl

**Comment by dhuyvetter** [comment]
# apt-cache policy php5-intl php5-common
	php5-intl:
	  Installed: (none)
	  Candidate: 5.5.9+dfsg-1ubuntu4
	  Version table:
		 5.5.9+dfsg-1ubuntu4 0
		    500 http://archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
		    100 /var/lib/dpkg/status
	php5-common:
	  Installed: 5.5.9+dfsg-1ubuntu4.14
	  Candidate: 5.5.9+dfsg-1ubuntu4.14
	  Version table:
	 *** 5.5.9+dfsg-1ubuntu4.14 0
		    500 http://security.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
		    100 /var/lib/dpkg/status
		 5.5.9+dfsg-1ubuntu4 0
		    500 http://nl.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages

Looks like Ubutnu repo's don't have an up-to)date version of php5-intl

**Comment by RealRancor** [comment]
There you see your issue. http://packages.ubuntu.com/trusty/php5-intl is at 5.5.9+dfsg-1ubuntu4.14

I think you can close this issue and ask for support at an ubuntu community.

**Comment by dhuyvetter** [comment]
OK, I will. Thanks for bearing with me! ;)

**Comment by withit** [comment]
@dhuyvetter,

How did you solve this? I have the same issue (running xUbuntu_14.04-owncloud-8.2.0-2.1-201510201921.vmx, and wanting to upgrade to 8.2.2).
