### ISSUE TITLE
Davdroid "Login with email address"

### ISSUE THREAD

**Issue by ODDSys** [owncloud/core#21537]
### Steps to reproduce
1: Launch the Davdroid App on android phone
2: Select the "Key +" icon on the top right
3: Select Login with email address
4: enter details (ie username@domain.com and password)
5: Click next arrow

### Expected behaviour
Login to Owncloud and list contact and calenders

### Actual behaviour
Failed login due to invalid username or password
This behaviour is due to DavDroid passing the full email address as a username.
If the server is setup with standard usernames instead of email address's it fails to authorise.

**ownCloud version:** (see ownCloud admin page)
8.1.5 (stable) 

Hello

Long time user, first time complainer i would like to thank you owncloud, it is an excellent system.
I have a small setup with only a handfull of users so i only use the first part of the email address's as a username in owncloud.

My work around is to modify owncloud/lib/private/user.php, find 'function "login"' (~ line 246) and add '$loginname = str_replace("@domain.com","",$loginname);' as the first line to the function.

This is probably not an issue for larger setups using LDAP.

I am happy to have a go at submitting a change, just wondering what others think or if i creating a security or something like that.

Thank you

**Comment by rullzer** [comment]
Why not use login with URL and username option in DavDroid?

**Comment by ODDSys** [comment]
Hi rullzer, i have been using that up until recently.
While supporting a couple of my friends & family it was difficult to get the full url's over the phone.
I always wished to use the single setup nature of the email setup and auto config via dns that Davdroid supports.

**Comment by ODDSys** [comment]
sorry, click early.
Realized it was easy to get working by adding that line.
Now my users just enter a single email address and everything is listed (Calendar, contacts, tasks)

**Comment by ODDSys** [comment]
just to clarify, easy to get working *after* you have added _caldavs._tcp & _carddavs._tcp TXT & SRV records to your DNS

**Comment by DeepDiver1975** [comment]
We could add an auth plugin for this case which transform the email address to the user id and uses the id for login.

This somehow falls into the area of login-with-your-email-address - @jancborchardt 

Any issues with this approach from a sec perspective? @LukasReschke

**Comment by MorrisJobke** [comment]
> This somehow falls into the area of login-with-your-email-address - @jancborchardt

https://github.com/owncloud/core/issues/2927




> Any issues with this approach from a sec perspective? @LukasReschke

The same as already mentioned in #2927 - we need to verify the email is only set up once.

**Comment by DeepDiver1975** [comment]
> we need to verify the email is only set up once.

oh yes - that was the issue ...

**Comment by ODDSys** [comment]
I see what you mean, unfortunately i do not see how the initial "email" can be sent when the users only have a userid instead of an email (As per instructions https://doc.owncloud.org/server/6.0/admin_manual/configuration/configuration_users.html)

This then also affects "Reset your Password" function on the login page then as the user does not have a defined email

**Comment by ODDSys** [comment]
Scratch that, just realized there is an email field.....

**Comment by ODDSys** [comment]
OK, now i see where you are going with this, user has an email address field, that can be looked at for login.

That address assumes that the users email address is on the same domain as the Owncloud instance.
What happens when i have OC on a different domain to my email (ie email: testperson@maindomainc.com, OwnCloud testperson@ocdomain.com)

**Comment by DeepDiver1975** [comment]
I was testing Mac's Calendar and the automated setup mode for calendars is using the email as well.
And it magically did work - maybe because the user name is stripped off the email properly ..... let's debug this .. once day ;-)

**Comment by Xenopathic** [comment]
The way the Active Directory world (and by extension, Kerberos) does it is by treating a username in the format 'abc@example.com' not as an email address, but as a username + domain part. I think it's a misnomer calling it an email login, and it's unfortunate that the LDAP app has it baked in with that terminology for so long. It's true that in many cases the email address will be identical to the username + domain part, but not always.

I'd suggest that any authenticators for ownCloud strip the domain part if they match the current server, otherwise return failure (allowing the potential for some sort of federation to occur towards other servers if a different domain part is specified). This is exactly how Active Directory does it.

**Comment by jancborchardt** [comment]
This is one of the reasons why allowing sign in with email and making sure emails are unique is so important.

People might not remember their username for a specific platform, but usually know their email address. Making sure that's part of our flow will also make it easier to integrate with other systems.
(Just in case you don't know: big platforms like FB and others also allow log in via email for that exact reason.)

**Comment by PVince81** [comment]
login with email address was implemented in 9.1: https://github.com/owncloud/core/pull/24389
