### ISSUE TITLE
If you mark a folder as favorite, the sum of folders is increased

### ISSUE THREAD

**Issue by davitol** [owncloud/core#21534]
### Steps to reproduce

1. Go to files view
2. Mark a file as favorite

### Expected behaviour

The result of the sum of files/folders should not change after marking a file/folder as favorite

### Actual behaviour

The result of the sum is increased +1

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:  ownCloud Enterprise Edition 9.0 pre alpha (daily) Build:2016-01-07T04:44:34+00:00 d3922510d01fb5feed3ea01a3d390dfaa8b1312f

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

![screen shot 2016-01-08 at 09 42 28](https://cloud.githubusercontent.com/assets/10596560/12194081/51a1f26c-b5ed-11e5-8114-5a7216eddc41.png)

**Comment by rullzer** [comment]
PR in #21573
