### ISSUE TITLE
'Choose file' button for avatar image is not right located

### ISSUE THREAD

**Issue by davitol** [owncloud/core#21542]
### Steps to reproduce

1. Go to personal settings page
2. In Profile picture section, click on 'Select from files button'

### Expected behaviour

The button should fit inside the 'choose an image window' 

### Actual behaviour

The button is stack to the border

Note: It happens in several browsers, but the issue is more visible in Mozilla

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:  ownCloud Enterprise Edition 9.0 pre alpha (daily) Build:2016-01-07T04:44:34+00:00 d3922510d01fb5feed3ea01a3d390dfaa8b1312f

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

![screen shot 2016-01-08 at 12 39 19](https://cloud.githubusercontent.com/assets/10596560/12197349/9ef70142-b606-11e5-8e4e-60fef8accb10.png)

**Comment by rullzer** [comment]
@owncloud/designers
