### ISSUE TITLE
Problem configuring Apps - no repository access

### ISSUE THREAD

**Issue by mlangguth** [owncloud/core#21547]
Hi,
I do have problems configuring the Apps: 
Out of the sudden (since 01-07-2015): Only the currently installed ones are visible, a listing of the available apps in the shop is empty. This occurs on the different instances on three different hosts.

In detail:
As an admin, opening “+ Apps”, in the left navigation plane only the following elements are present:
-	Enabled
-	Not enabled
-	Developer documentation
-	gearwheel

Normally there would also be: All, Multimedia, Productivity etc.  but these are missing. 
Then, when selecting “not enabled”, the list seems shorter than normal. 
So installing / enableing new apps isn’t possible. Even “standard ones” like Calendar, Contacts and Bookmarks are not available.

I do have this strange behavior on three hosted ownCloud-Providers. In all, everything worked till 2015-01-06.
Using different browsers and clearing the browsers cache didn’t help.
So I think it must be a problem with the backend (https://apps.owncloud.com/)!?

**Comment by RealRancor** [comment]
@mlangguth See https://forum.owncloud.org/viewtopic.php?f=17&t=29790

It might also help if you fill out the issue template as asked in the guidelines for contributing (linked in the yellow box when creating a new issue):

https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version

Currently even the basic info which oC version you're running is missing.

**Comment by mlangguth** [comment]
Ups, sorry... newbees...
Here are the infos:

### Server configuration
**Operating system**: ? (don't know, it's hosted)

**Web server:** ? (don't know, it's hosted)

**Database:** in one instance: MySQL, on the other:  don't know, it's hosted

**PHP version:** in one instance 5.6.14, on the other:  don't know, it's hosted

**ownCloud version:** 8.2.2

**Updated from an older ownCloud or fresh install:** fresh installed 8.2.2

**List of activated apps:**
Activity  2.1.3
Deleted files  0.7.0
External Sites  1.2
External storage support  0.3.0
First Run Wizard  1.1
Gallery  14.2.0
Mail Template Editor  0.1
Notifications  0.1.0
PDF Viewer  0.7
Provisioning API  0.3.0
Share Files  0.7.0
Text Editor  2.0
Updater  0.6
Versions  1.1.0
Video Viewer  0.1.3

**Comment by mlangguth** [comment]
... and
**Are you using external storage, if yes which one:** no external storage linked

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** none

other informations are hard to get, since the instances are hosted.

**Comment by RealRancor** [comment]
Have you checked the linked FAQ?

**Comment by mlangguth** [comment]
It seems I need a little sleep. Overlooked the FAQ-Link...

...

On one host I can open a SSH-Connection:
  curl -i https://apps.owncloud.com

works, but

  wget https://apps.owncloud.com

produces:
  --2016-01-08 14:43:45--  https://apps.owncloud.com/
  Resolving apps.owncloud.com... 85.25.74.45
  Connecting to apps.owncloud.com|85.25.74.45|:443... connected.
  ERROR: cannot verify apps.owncloud.com's certificate, issued by
   '/C=US/ST=Arizona/L=Scottsdale/O=GoDaddy.com,
   Inc./OU=http://certs.godaddy.com/repository//CN=Go Daddy Secure Certificate Authority - G2':
  Unable to locally verify the issuer's authority.
  To connect to apps.owncloud.com insecurely, use `--no-check-certificate'.



So it seems there is a problem with the shops certificate?
The linked FAQ links to ca-bundle.crt which should be updated but says that this doesn't apply for oC 8.2.x.
Also, nothing was changed on the instance side of the ownCloude installations. And the instances are run on different hosters (strato and onwcube). 

What can I check next?

**Comment by rullzer** [comment]
It seems you do not have the required root certificate on your system. Which is why the request is failing. This is not something we can fix. Please contact your hoster.
