### ISSUE TITLE
collapse complex configuration options

### ISSUE THREAD

**Issue by karlitschek** [owncloud/core#21549]
Some of the settings on the admin and personal page are quite complex. It would be cool to collapse and hide some of the more advanced settings and only shoe them on click. Something like 'advanced options' or 'security settings'

![sharing](https://cloud.githubusercontent.com/assets/867445/12199355/80b7930c-b5e5-11e5-86a7-054d6f2b0520.png)

**Comment by karlitschek** [comment]
@schiesbn @jancborchardt What do you think?
The notification settings on the personal page are also an example for something that we might hide behind an additional button. @nickvergessen 
Opinions?

**Comment by DeepDiver1975** [comment]
9.0 ?

**Comment by schiesbn** [comment]
Yes, the share settings are way to complex. I already thought about this in the past. Might be a good idea to hide some of them by default. On the other hand it makes it harder to discover all settings if you first have to expand all categories.  @jancborchardt what do you think from a UX point of view?

**Comment by jancborchardt** [comment]
Definitely the indented Share link sub-points can be collapsed.

Maybe weven the ones below which are set very well by default and are super specific. Could we even remove settings from there which prove to not really be useful after all?

(Also, shouldn't both federated sharing boxes be checked by default when you enabled the app?)

**Comment by PVince81** [comment]
I'd say obsoleted by https://github.com/owncloud/core/pull/26449 where the settings only appear alone when selecting a section.

@tomneedham @DeepDiver1975 

Closing
