### ISSUE TITLE
" This app has no minimum ownCloud version assigned. This will be an error in ownCloud 11 and later." shown for all appstore apps

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#21556]
This makes the appstore entries look somewhat strange, some of these apps have certainly
![2016-01-08_18-03-33](https://cloud.githubusercontent.com/assets/878997/12204022/25f4cea6-b632-11e5-828e-ed8e27605b07.png)

Added with https://github.com/owncloud/core/pull/21506 by @nickvergessen

**Comment by LukasReschke** [comment]
Probably we just need to parse the appstore response. Let me see.

**Comment by LukasReschke** [comment]
@nickvergessen We have two choices here:

1. Adjust the appstore to make it return the min- and max-version. I don't see it in the return of https://api.owncloud.com/v1/content/data?version=8x2x0x0&categories=922&approved=all
2. Do just assume apps from the appstore are compatible. This seems likely as you explicitly need to mark the version there.

My call there is for 2, objections?

**Comment by karlitschek** [comment]
No objections. At the moment the logic is done on the app store side so only compatible apps are returned to the owncloud server.

**Comment by nickvergessen** [comment]
Woops, makes sense

**Comment by LukasReschke** [comment]
There we go: https://github.com/owncloud/core/pull/21586

**Comment by nickvergessen** [comment]
> At the moment the logic is done on the app store side so only compatible apps are returned to the owncloud server. 

The only bit that is somewhat missing is to have a forced maximum ownCloud version
