### ISSUE TITLE
Footer on admin and personal is really messy 

### ISSUE THREAD

**Issue by karlitschek** [owncloud/core#21551]
I think we should structure this a bit better.

![footer](https://cloud.githubusercontent.com/assets/867445/12199488/79fa16c4-b5e6-11e5-93e5-a3428b99d034.png)
Also the updater should be integrated into the footer.

**Comment by karlitschek** [comment]
@jancborchardt FYI

**Comment by DeepDiver1975** [comment]
9.0 ?

**Comment by jancborchardt** [comment]
This was fixed by #21596, and the imtegration of Updater into Versions is tracked at https://github.com/owncloud/updater/issues/212
