### ISSUE TITLE
Web interface should use the OCS Share API

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#21554]
In order to allow core to move away from the old sharing code we need to migrate the webinterface to the OCS Share API. (see #19331).

This requires fixing the backbone model to do json calls to the OCS endpoint instead of the current ajax endpoints.

@PVince81 as discussed.

**Comment by PVince81** [comment]
Two parts:
- [ ] Adjust core/js/share.js, the part that retrieves share info for the file list icon/states
- [ ] Adjust share dialog

**Comment by PVince81** [comment]
PR in progress here: https://github.com/owncloud/core/pull/21860

**Comment by PVince81** [comment]
We still have core/share.js requiring a summarizing call:
- https://github.com/owncloud/core/blob/master/core/js/share.js#L55
- https://github.com/owncloud/core/blob/master/core/ajax/share.php#L261

There is a similar core in OCS but the response is huge and wasteful and might cause performance impact when many shares. See https://github.com/owncloud/core/issues/21798#issuecomment-175116407

**Comment by PVince81** [comment]
Discussed with @DeepDiver1975, one idea would be to return the summarized share info as part of the Webdav response. Add a new property "oc:share" or "oc:shareTypes" or "oc:shareIds" that makes it possible to display the icon (regular share or public share) in the web UI.

The fetching of the shares of a folder must use a method on the share manager to retrieve all shares by folder, passing the file id. Fetching shares individually for every file id would be unefficient.

**Comment by PVince81** [comment]
Now using OCS response for status icons: https://github.com/owncloud/core/pull/22305
