### ISSUE TITLE
"PHP","message":"Undefined variable:

### ISSUE THREAD

**Issue by OktoZ** [owncloud/core#21568]
Hi
The application log (owncloud.log) ownCloud is a lot of errors:

{"reqId":"Jc6LImqY6Ey1dfFKrRBK","remoteAddr":"83.11.XX.XXX","app":"PHP","message":"Undefined variable: fi at \/tmpfs\/prepend\/xxxx#88","level":3,"time":"2016-01-09T13:28:28+00:00"}

Please support me.

Serwer:	Linux 3.2.74-xxxx-std-ipv6-64 #1 SMP Sun Nov 29 18:29:10 CET 2015 x86_64 x86_64 x86_64 GNU/Linux
Apache: 2.4
PHP: 5.6.13
MySQL: 5

**Comment by Xenopathic** [comment]
What is at `/tmpfs/prepend/xxxx`? It sounds like you have a broken app enabled.

**Comment by OktoZ** [comment]
This is a webhosting:

ls -al /tmpfs
 drwx--x--x    2 root   root   17520 gru  2 07:01 prepend
 [/tmpfs/prepend]# ls -al
	ls: .: Access denide
 [/tmpfs/prepend]#

**Comment by RealRancor** [comment]
It might be useful to not redact the filename which is causing that warning:

\/tmpfs\/prepend\/xxxx#88

**Comment by LukasReschke** [comment]
This is not caused by ownCloud and not an ownCloud issue. Please report this to your web hoster.
