### ISSUE TITLE
Error in upgrade-process from 8.2.1 to 8.2.2

### ISSUE THREAD

**Issue by Liwindo** [owncloud/core#21569]
**Steps to reproduce**

1. Go to administration page
2. Start the Upgrade to 8.2.2

**Expected behaviour**
The Upgrade works

**Actual behaviour**
The Upgrade works not

**Server configuration**

**Operating system:**
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0.1

**ownCloud version: (see ownCloud admin page)**
8.2.1

**Updated from an older ownCloud or fresh install:**
8.2.1

**Logs**
Error 	updater 	Unable to move /path_to_cloud/_oc-upgrade/8.2.2.2/core/resources to /path_to_cloud/resources 	2016-01-09T13:56:34+00:00
Error 	updater 	Something went wrong for core. Rolling back. 	2016-01-09T13:56:22+00:00
Error 	PHP 	rename(/path_to_cloud/_oc-upgrade/8.2.2.2/core/resources,/path_to_cloud/resources): Directory not empty at /path_to_cloud/apps/updater/lib/helper.php#52

**Comment by Xenopathic** [comment]
If you use the Updater app, please ensure that the web server user has write permissions to the ownCloud directory, otherwise it can't do anything.

**Comment by RealRancor** [comment]
Quoting from the changelog:

> Unable to move /srv/http/owncloud/_oc-upgrade/8.2.1.4/core/resources to /srv/http/owncloud/resources - updater

Unfurtunately 8.2.1 ships this buggy updater app so you need some workarounds like described here fore example: https://github.com/owncloud/updater/issues/189#issuecomment-158762851

**Comment by Liwindo** [comment]
@Xenopathic Would be really helpful to close not my issue immediately without checking it. @RealRancor Thx.
