### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by patkor** [owncloud/core#21567]
Hi,

i received the following error message while trying to update to owncloud 8.2.1:

Exception: Updates between multiple major versions and downgrades are unsupported.

Do you have expierences with this problem?

**Comment by calcmandan** [comment]
happened to me last week. what version are you on now? 8.0.3?

**Comment by RealRancor** [comment]
@patkor Please use the search function on top of this repository before posting. With that you will find plenty of duplicates like https://github.com/owncloud/core/issues/21496

Just close this issue (as it don't need to be reported) and do the correct upgrade path by not skipping major versions (eg. you need to go from 8.0.x to 8.1.5 first before going to 8.2.2) like described in the upgrading manuals.

See this FAQ for more info: https://forum.owncloud.org/viewtopic.php?f=17&t=32087
