### ISSUE TITLE
occ in chroot environment

### ISSUE THREAD

**Issue by JohannesKleine** [owncloud/core#21579]
My target is to lunch occ on shared hosting webspaces.
# Actual behaviour

running: 
```php
user@server:~$ php foo/occ 
{"reqId":"PRdORwAloaLoaH5Jw3Gu","remoteAddr":"","app":"PHP","message":"mkdir(): No such file or directory at \foo\/apps\/updater\/lib\/helper.php#116","level":3,"time":"2016-01-05T09:39:10+00:00","method":"--","url":"--"}
{"reqId":"PRdORwAloaLoaH5Jw3Gu","remoteAddr":"","app":"PHP","message":"chmod(): No such file or directory at \foo\/lib\/private\/log\/owncloud.php#92","level":3,"time":"2016-01-05T09:39:10+00:00","method":"--","url":"--"}
An unhandled exception has been thrown:
exception 'Exception' with message 'Unable to create /var/www/clients/client123/web456/foo/data/updater_backup/' in foo/apps/updater/lib/helper.php:117
Stack trace:
#0 foo/apps/updater/appinfo/application.php(52): OCA\Updater\Helper::mkdir('/var/www/client...')
#1 foo/apps/updater/appinfo/app.php(15): OCA\Updater\AppInfo\Application->__construct()
#2 foo/lib/private/app.php(160): require_once('foo/apps/updat...')
#3 foo/lib/private/app.php(141): OC_App::requireAppFile('updater')
#4 foo/lib/private/app.php(118): OC_App::loadApp('updater')
#5 foo/lib/private/console/application.php(57): OC_App::loadApps()
#6 foo/console.php(68): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 foo/occ(11): require_once('foo/console.ph...')
#8 {main}
```
gives an error, because the php (running as user) startet in the chroot environment and his "/" dir located in 
```
/var/www/clients/client123/web456/
```
but hi can see only "/".  In contrast to the php (running as apache or www) started by viewing oc over the webinterface, this can use the path from the config.php file, saved in 
```
'datadirectory' => '/var/www/clients/client123/web456/foo/data',
```
and works as expected. 
# Possible solutions
1.- At the moment, my work around is a little check, wether it runs in the chroot environment or startet from the webinterface:
```
 'datadirectory' => ((php_sapi_name() != 'cli') ? '/var/www/clients/client123/web456/' : '') . '/foo/data',
```
Of course this can not be the final solution. 
2.- Introduce a new variables
```
'datadirectory_cli' => 'foo/data'
```
change the old
```
'datadirectory'
```
in the config.php file to 
```
'datadirectory_server'
```
and perform a check in the console.php file wether it is lunched from cli or as usual.
```
if ((php_sapi_name() == 'cli')
    'datadirectory' = 'datadirectory_cli'
    else 'datadirectory' = 'datadirectory_server'
```
3.- Only one new variable
```
'datadirectory_cli' => 'foo/data'
```
and perform a check in the console.php file wether it is lunched from cli or as usual.
```
if ((php_sapi_name() == 'cli')
    'datadirectory' = 'datadirectory_cli'
```
# Some ideas
how can we be shure, that every script started by "php occ" uses the right variable content if the check is performed in console.php? (Actually i can not programm php.) Will each script read direktly from config.php or uses the variables from his parent process? Or shuld an environment check be placed between oc core and the config file?
oc core || environment check || config.php
Let as discuss.

**Comment by Xenopathic** [comment]
From ownCloud's perspective, you are running it in one directory, then expecting occ to work on it from a completely different directory. `chroot` is a system-level feature, and ownCloud cannot detect or work around it. Please run your `occ` command inside the `chroot` as well, so they see a consistent filesystem.

**Comment by JohannesKleine** [comment]
I started the command 
```
user@server:~$ php foo/occ 
```
inside the chroot.

**Comment by Xenopathic** [comment]
I would suggest talking to your hoster about this

**Comment by JohannesKleine** [comment]
@MorrisJobke
