### ISSUE TITLE
php.ini/upload_tmp_dir doesn't work as expected

### ISSUE THREAD

**Issue by arabesc** [owncloud/core#21570]
### Steps to reproduce
1. set [```php.ini/upload_tmp_dir```](https://secure.php.net/manual/en/ini.core.php#ini.upload-tmp-dir) parameter to a different path from the system temp location;
1. start uploading of some large file in the OC web interface/Files menu (upload should lasts some time);
2. periodically check free space on the server filesystems.

### Expected behaviour
The file is being directly uploaded to the folder that has been set in the [```php.ini/upload_tmp_dir```](https://secure.php.net/manual/en/ini.core.php#ini.upload-tmp-dir) parameter.

### Actual behaviour
The file has been uploaded to a system temp folder; then it has been moved to the [```php.ini/upload_tmp_dir```](https://secure.php.net/manual/en/ini.core.php#ini.upload-tmp-dir) location and finally it has been moved to the user data folder.

### Server configuration
**Operating system**:
FreeBSD 10.2

**Web server:**
[nginx-1.8.0](https://freshports.org/www/nginx/)

**Database:**
[MariaDB-10.0.23](https://freshports.org/databases/mariadb100-server/)

**PHP version:**
[PHP-5.6.16](https://freshports.org/lang/php56/)

**ownCloud version:** (see ownCloud admin page)
[ownCloud-8.2.2](https://freshports.org/www/owncloud/)

**Updated from an older ownCloud or fresh install:**
Fresh install.

**List of activated apps:**
```
Enabled:
  - activity: 2.1.3
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - files: 1.2.0
  - files_external: 0.3.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - updater: 0.6
Disabled:
  - encryption
  - external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "************",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "example.com"
        ],
        "datadirectory": "/mnt/storage/owncloud/data",
        "overwrite.cli.url": "https://example.com/owncloud",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe/Moscow",
        "installed": true,
        "activity_expire_days": 90,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "allow_user_to_change_display_name": true,
        "check_for_working_webdav": true,
        "check_for_working_htaccess": true,
        "loglevel": 0,
        "cron_log": true,
        "assetdirectory": "/usr/local/www/owncloud",
        "asset-pipeline.enabled": true,
        "maintenance": false,
        "singleuser": false,
        "filesystem_check_changes": 1,
        "debug": false
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
NO

**Are you using encryption:** yes/no
NO

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO

### Client configuration
**Browser:**
Firefox-43.0.4

**Operating system:**
Mac OS X 10.11.2

**Comment by Xenopathic** [comment]
It is `nginx` putting the files into the system temporary directory, not PHP. Look into `fastcgi_request_buffering`

**Comment by arabesc** [comment]
Are you sure? I've set ```fastcgi_request_buffering off;``` in the nginx ```http {...}``` section and the behaviour is completely the same.

**Comment by Xenopathic** [comment]
You might want to look at exactly *what* files are being created in the system temporary directory, rather than just knowing 'there are some'. The filename or exact location will give you clues as to what part of the process is creating them. Other than that, please note that this is a bug tracker, and any support queries should be directed to https://owncloud.org/support/

**Comment by arabesc** [comment]
There are a lot of different temp files in the system temp location. It will be complicated to find the right one...
I've caught the file moving from the system temp to the [```upload_tmp_dir```](https://secure.php.net/manual/en/ini.core.php#ini.upload-tmp-dir) location:
```
# lsof -u www | grep owncloud
php-fpm 54199  www    9r    VREG     170,1663107246 2132205077   1855 /mnt/storage/owncloud/php/upload_tmp/phpBcnBhJ
php-fpm 54199  www   10w    VREG     170,1663107246 1129725952   1858 /mnt/storage/owncloud (zstore/owncloud)
```

**Comment by arabesc** [comment]
It seems this behaviour is due to [recommendation](https://doc.owncloud.org/server/8.0/admin_manual/configuration_files/big_file_upload_configuration.html#nginx) to set ```nginx``` parameter [```client_max_body_size```](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size) to some large value - probably as large as largest upload could be. It leads to this issue: at first the file has been uploaded to the [```client_body_temp_path```](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_body_temp_path) location and then it has been moved to the [```upload_tmp_dir```](https://secure.php.net/manual/en/ini.core.php#ini.upload-tmp-dir) location.
May be it's not a bug but it seems pretty inefficient. There is high amount if the useless extra work.
As a workaround I would suggest setting [```client_body_temp_path```](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_body_temp_path) and [```upload_tmp_dir```](https://secure.php.net/manual/en/ini.core.php#ini.upload-tmp-dir) to locations in the same file system. Otherwise file moving is going to be performed as expensive copy + delete operations.
It would be nice to reflect these nuances in the docs.

**Comment by Xenopathic** [comment]
Unfortunately there's not much we can do about any of that, that's nginx talking to php-fpm. However, full ack about the docs. cc @carlaschroder More nginx craziness :smile:

**Comment by RealRancor** [comment]
https://github.com/owncloud/documentation/issues/new

:-)

**Comment by carlaschroder** [comment]
A friendly reminder that Nginx is not officially supported. We maintain Nginx docs because it is popular, and because of awesome community contributors who maintain the Nginx pages. I can proofread, markup, and publish Nginx examples; I need someone who knows what they're doing to write out the exact steps.
