### ISSUE TITLE
enable 'old_password' in MySQL

### ISSUE THREAD

**Issue by RogerRabbit15** [owncloud/core#21587]
just suggesting the possibility of adding an option at set up/install to decide if you would like to use MySQL with old password hashing vs the new which is currently in place.  There are many hosts out there that would allow an owncloud install on a shared hosting plan, however, they run MySQL with 'old_passwords' on so that older other users applications can still run.  I'd really rather prefer to use OwnCloud vs the other option pydio but without the option to connect to MySQL with the old password hashing i can't install it.  just an idea

**Comment by RealRancor** [comment]
Old password where pre-4.1 so is this really something which should be supported by ownCloud?

**Comment by RogerRabbit15** [comment]
I would like it to be considered, owncloud.org installs from what i gather is something for anyone who wants to run their "own cloud" service, not everyone has a VPS plan or a dedicated server where the end user can control the scripting language and parameters.  (such is my case) so if the ability to choose what type of hashing is used would just allow more users to use the software.  The end user would be taking all the risk being it is an older "outdated" encryption method.

**Comment by karlitschek** [comment]
I agree with @RealRancor We should only support what is really needed out there. Adding config option and features if absolutely needed.
So far I remember zero bug reports from users who are affected by that.

**Comment by RogerRabbit15** [comment]
Ok so essentially self hosted own cloud is only for users who have full control over their hosting account. A bit disappointing users on shared hosting. Obviously not in the scope of owncloud. Thanks anyway.

**Comment by karlitschek** [comment]
Not what I said. I think the share of users who use a super old MySQL is small enough to be ignored. Actually I'm not aware of a single case.
