### ISSUE TITLE
Owncloud SMB to windows share on StorageSpaces

### ISSUE THREAD

**Issue by AndrewTilson** [owncloud/core#21584]
I am using a canned VM image of owncloud in a box on suse. Its running as 8.2.2. I had this same issue with version 8.2.1 on a ubuntu image i built before. I have a windows 10 file server that has 2 drives. A C:\ stand alone disk and a D:\ which is a storage spaces disk of 5 drives. If i create a file share on the C:\ i can get to it just fine. If i create the same share on the d:\ storage space disk i cannot and it just gives me the red box. Here is the log entry out of the admin interface. I have also installed the ftp client on the vm and ftp server on the windows server. In this configuration it will work. Only seems to be a issue when using a file share on the Storage Spaces drive.

Exception: {"Exception":"Icewind\SMB\Exception\Exception","Message":"Unknown error (NT_STATUS_OBJECT_NAME_INVALID) for \/","Code":0,"Trace":"#0 \/srv\/www\/htdocs\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Share.php(364): Icewind\SMB\Parser->checkForError(Array, '\/')\n#1 \/srv\/www\/htdocs\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Share.php(128): Icewind\SMB\Share->parseOutput(Array, '\/')\n#2 \/srv\/www\/htdocs\/owncloud\/apps\/files_external\/lib\/smb.php(102): Icewind\SMB\Share->stat('\/')\n#3 \/srv\/www\/htdocs\/owncloud\/apps\/files_external\/lib\/smb.php(136): OC\Files\Storage\SMB->getFileInfo('')\n#4 \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/storage\/common.php(410): OC\Files\Storage\SMB->stat('')\n#5 \/srv\/www\/htdocs\/owncloud\/apps\/files_external\/lib\/config.php(261): OC\Files\Storage\Common->test(false)\n#6 \/srv\/www\/htdocs\/owncloud\/apps\/files_external\/controller\/storagescontroller.php(237): OC_Mount_Config::getBackendStatus('\\OC\\Files\\Stora...', Array, false)\n#7 \/srv\/www\/htdocs\/owncloud\/apps\/files_external\/controller\/storagescontroller.php(257): OCA\Files_External\Controller\StoragesController->updateStorageStatus(Object(OCA\Files_external\Lib\StorageConfig))\n#8 [internal function]: OCA\Files_External\Controller\StoragesController->show(1)\n#9 \/srv\/www\/htdocs\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#10 \/srv\/www\/htdocs\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Files_External\Controller\GlobalStoragesController), 'show')\n#11 \/srv\/www\/htdocs\/owncloud\/lib\/private\/appframework\/app.php(108): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Files_External\Controller\GlobalStoragesController), 'show')\n#12 \/srv\/www\/htdocs\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\AppFramework\App::main('GlobalStoragesC...', 'show', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)\n#13 [internal function]: OC\AppFramework\routing\RouteActionHandler->__invoke(Array)\n#14 \/srv\/www\/htdocs\/owncloud\/lib\/private\/route\/router.php(291): call_user_func(Object(OC\AppFramework\routing\RouteActionHandler), Array)\n#15 \/srv\/www\/htdocs\/owncloud\/lib\/base.php(851): OC\Route\Router->match('\/apps\/files_ext...')\n#16 \/srv\/www\/htdocs\/owncloud\/index.php(39): OC::handleRequest()\n#17 {main}","File":"\/srv\/www\/htdocs\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Parser.php","Line":66}

Now strangely enough if i share the root of the drive the admin screen gives me a green indicator but when i try to browse it shows nothing on the drive but there is. I can also upload a image and it shows up on the file system but the interface pops up with "The target folder has been moved or deleted."

From the owncloud vm i am able to successfully connect with the smb client to see the share on both drives. I am also able to mount it and navigate this way.

The owncloud vm i am using is here.
https://susestudio.com/a/TadMax/owncloud-in-a-box

**Comment by karlitschek** [comment]
@icewind1991 any idea?

**Comment by PVince81** [comment]
@AndrewTilson can you confirm that the user you used in the OC SMB configuration has enough permission on these shares ?

**Comment by PVince81** [comment]
Does it work with non-full-disk shares ?

**Comment by AndrewTilson** [comment]
The share i have created does have the user i configured with full control and i have also granted everyone with full control as well. I am able to from the server use the smb client to connect to the share without any issues. As for non-full-disk shares? Im assuming you mean the share is not full on space. The disk in question is a 6TB space with only 2TB used.

**Comment by PVince81** [comment]
With non-full-disk share I mean create a SMB share on "D:\subdirectory" instead of "D:\".
Goal is to see whether the bug appears when the path is short / whenever the complete disk is the share.

**Comment by PVince81** [comment]
Any update ?

**Comment by AndrewTilson** [comment]
Hm I had gotten a notification that this was closed as an environment issue so I haven't been keeping track of it. I can try to pull down the latest owncloud image and try it this weekend again.

**Comment by PVince81** [comment]
I do think this is likely to be an environment issue and was just trying to find clues to confirm it.

**Comment by AndrewTilson** [comment]
Hm I had gotten a notification that this was closed as an environment issue so I haven't been keeping track of it. I can try to pull down the latest owncloud image and try it this weekend again.

**Comment by AndrewTilson** [comment]
I understand your reason for thinking this however i can get a file share to work on any system on a standard disk drive. I could only reproduce this when using windows storagespaces feature to create a drive similar to a software raid disk and creating a file share on that drive.

**Comment by PVince81** [comment]
8.2.2 is old, please try again with 8.2.6. There were also updates to the Icewind/SMB library.

If looks like ownCloud in a box updated to 9.0.1, you could try with that version, although the current latest version is 9.0.3.

**Comment by PVince81** [comment]
Please reopen if it still doesn't work with 9.0.5

**Comment by markopetrovikj** [comment]
It still doesn't work with 9.0.5 / 9.1.1 /9.1.2 Do you find any solution.
