### ISSUE TITLE
Star icons on apps interface are pixelated on retina display

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#21588]
The star icons on the appstore interface seem pixelated on a retina display. Seems like we need them in a new resolution as well? (or even as SVG?)

Talking about the icons from https://github.com/owncloud/core/tree/656b5418996744b5ba095afac59b4fdb4db37337/core/img/rating that can be seen /index.php/settings/apps?category=productivity

cc @owncloud/designers

**Comment by PVince81** [comment]
Since we're dropping IE8 support, SVG should work now without any workarounds.

**Comment by jancborchardt** [comment]
Yeah, we just need the star icons as SVG. Setting as Junior Job if anyone wants to do it. The actions/star.svg and actions/starred.svg are good for that.

Otherwise I'll fix that when there's time.

**Comment by paurisa** [comment]
I have remade the images as SVG and I'm now trying to find where is the code that displays them.
So far I looked in https://github.com/owncloud/core/blob/master/settings/templates/apps.php but had no luck.

**Comment by LukasReschke** [comment]
@paurisa https://github.com/owncloud/core/blob/256dfd27b6129f9eba205bf4195246c0cac6045b/settings/js/apps.js#L3-L11 is the code. Right now score is there basically a number between 0 - 10 and each value is another half star. See https://github.com/owncloud/core/tree/master/core/img/rating

So probably there would be some logic change required there to add the stars in SVG format :)

**Comment by paurisa** [comment]
@LukasReschke Thanks for the help! Gonna familiarize myself with the code to add the stars in SVG format.

**Comment by paurisa** [comment]
Fixed the issue. Do I have to create a branch or can I do a pull request directly?

**Comment by MorrisJobke** [comment]
Fix via #23371
