### ISSUE TITLE
Warnings on admin page

### ISSUE THREAD

**Issue by ThierryMasson** [owncloud/core#21583]
Dear,

Despite I have in apach2.conf the following header for security (for all hosted website):
Header always set X-Frame-Options SAMEORIGIN
Header always set Strict-Transport-Security "max-age=63072000; includeSubDomains"
Header always edit Set-Cookie (.*) "$1; HTTPOnly; Secure"
Header always set X-Xss-Protection "1; mode=block"
Header always set X-Content-Type-Options nosniff

OwnCloud claim the follwing (sorry it's in french):
    Ce serveur ne peut se connecter à internet. Cela signifie que certaines fonctionnalités, telles que le montage de supports de stockage distants, les notifications de mises à jour ou l'installation d'applications tierces ne fonctionneront pas. L'accès aux fichiers à distance, ainsi que les notifications par mail peuvent aussi être indisponibles. Il est recommandé d'activer la connexion internet pour ce serveur si vous souhaitez disposer de l'ensemble des fonctionnalités offertes.
    Aucun cache de la mémoire n'est configuré. Si possible, configurez un "memcache" pour augmenter les performances. Pour plus d'information consultez la documentation.
    L'en-tête HTTP "X-XSS-Protection" n'est pas configurée pour être égale à "1; mode=block" créant potentiellement un risque relié à la sécurité et à la vie privée. Il est donc recommandé d'ajuster ce paramètre.
    L'en-tête HTTP "X-Content-Type-Options" n'est pas configurée pour être égale à "nosniff" créant potentiellement un risque relié à la sécurité et à la vie privée. Il est donc recommandé d'ajuster ce paramètre.
    L'en-tête HTTP "X-Frame-Options" n'est pas configurée pour être égale à "SAMEORIGIN" créant potentiellement un risque relié à la sécurité et à la vie privée. Il est donc recommandé d'ajuster ce paramètre.

All work fine, but, as the Header are correct (and tested) it's annoying to see theses warnings...

If I delete all theses Header (upper mentionned), the following warnings deasepear: x-frame-options, x-xss-protection and x-content-type-options, but "Strict-Transport-Security" appear in warning (the only one who's "respond" correctly).
Probably OwnCloud not check if theses headers are already set :+1: 
- x-frame-options
- x-xss-protection
- x-content-type-options
(Twice loading ?)

Also, I don't understand why OwnCloud said there is no "internet connectivity" and claim about "memcache"...
as, the Internet connectivity is working (that's a good think for a online server :D )
and Xcache is also installed.

Best regards,

**Comment by RealRancor** [comment]
@ThierryMasson 

This probably means that your webserver is sending the headers twice which it shouldn't. You can easily test this with a request like:

curl -I http://www.example.com/owncloud/index.php

which probably shows the headers twice.

For the memcache follow the documentation link, this is not there just for fun.

For the internet connection message see: https://forum.owncloud.org/viewtopic.php?f=17&t=29790

Overall all of those are no bugs in ownCloud but server configuration issues. Have a look at:

https://owncloud.org/support/

for the different support channels where you can get further help with that.

**Comment by ThierryMasson** [comment]
Thanks for you very quick reply !
/
/Sorry for memcache...I have probably missreading something... it's OK 
now, thanks for the link.

For header problem.. "ok", I will try to find why server sending headers 
twice


But for 1st warning (No Internet connectivity)... how is it possible to 
have the following in OwnCloud :

*À jour.* /Dernière vérification : 10 janvier 2016 16:24:47 UTC+1
/

/And also, App working, update working,...
/

/wget https://apps.owncloud.com
Working, ...
/

/I have already read all post of your link
/

/All my SSL Certificate is ok (Grade A+)
/

A specific port ? (I have a strict firewall)

I'm going out of idea...

**Comment by RealRancor** [comment]
Maybe the no internet connection is also related to https://github.com/owncloud/core/issues/20028

**Comment by ThierryMasson** [comment]
I will have a look (but something sure, I have no issue at all with my 
SSL certificate (CA, bundle, CR all OK > and checked with ssllabs.com > 
Grade A+))
But could be a miss recognition as it's a multi-certificate ?


For header, that's because they are set in the .htaccess and there is no 
"check" if there are already set by the server itself.
I have comment out in the .htaccess :
     #Header set X-Content-Type-Options "nosniff"
     #Header set X-XSS-Protection "1; mode=block"
No more warning (as both header are already set in apache2.conf)
Don't know if I can prevent this on the server side....
