### ISSUE TITLE
Public share fails when master key is enabled

### ISSUE THREAD

**Issue by GitHubUser4234** [owncloud/core#21598]
Hello,

When master key is enabled in ownCloud 8.2.1, and a public link is accessed by a public user, the following screen is shown:

![image](https://cloud.githubusercontent.com/assets/16538178/12227958/a201c992-b86f-11e5-83f1-15a52fb0ecc0.png)

(In words: error "Private Key missing for user: please try to log-out and log-in again" shows up in browser)

However, any **logged in** user can download the file by accessing the same public link. A related pubShare_`<xxx>`.shareKey exists. No errors found in the ownCloud log.

In case this is a bug, it's really a show stopper to us. Please help, thanks.

**Comment by rullzer** [comment]
@schiesbn

**Comment by SergioBertolinSG** [comment]
I can reproduce this on stable8.2.

# Steps to reproduce:

1. Enable encryption with default module.
2. Run occ encryption:enable-master-key
3. Upload some files.
4. Public share one file.
5. Open it in another browser.

**Comment by schiesbn** [comment]
fix is here: https://github.com/owncloud/core/pull/21612

@SergioBertolinSG @GitHubUser4234 maybe you can give it a try and report back? Thanks!

**Comment by GitHubUser4234** [comment]
Great, thanks a lot @schiesbn :smiley:
