### ISSUE TITLE
Owncloud randomly deleting files

### ISSUE THREAD

**Issue by jeremyrjk** [owncloud/core#21595]
### Steps to reproduce
1. Use as normal. Change files on phone or computer, seems to be random.

### Expected behaviour
Sync without deleting files

### Actual behaviour
Occasionally empties files; deletes contents but leaves the file there.

### Server configuration
my.owndrive.com
OwnDrive 8.2.2 (stable)

### Client configuration
**Browser:** OwnCloud for Android 1.9.0
**OwnCloud-Client:** 2.1.0-2

**Operating system:** Android (with Manjaro Linux on desktop)

**Comment by karlitschek** [comment]
Can you post a full bug report using this template please? https://github.com/owncloud/core/blob/master/CONTRIBUTING.md
@rperezb Are you aware of any Android bugs?

**Comment by PVince81** [comment]
Missing important information: ownCloud version, whether encryption is enabled, whether the files in question are shared files (accessing as recipient or sharer)

**Comment by jeremyrjk** [comment]
I don't see any settings for encryption so I don't know it it's enabled - I guess whatever the my.owndrive.com default settings are.

I am sharing the files with myself only. I access and change them on my laptop and on my phone.

**Comment by jeremyrjk** [comment]
This problem happened about 4 times. There was about a month or so in between although it was very random. It has not happened since I posted this bug. In addition, the app seems to be updating files more frequently with the most recent updates. It seems to be working more smoothly? I will close the bug for now.

Thanks for an awesome app/service!!
