### ISSUE TITLE
Documents app missing on 8.2.2 on Debian 8

### ISSUE THREAD

**Issue by anomaly256** [owncloud/core#21597]
Hi, I've just installed a fresh Owncloud instance on a new Debian 8 machine from the stable repository to find that the 'Documents' app is not present in the owncloud-server .deb package.  I decided to look inside the .deb thinking I could copy it out manually if it was merely not enabled by the installer script or was removed by it as I didn't have libreoffice installed at first, but I found that it is in fact not present in the package at all:
```
/var/www/owncloud/apps/
/var/www/owncloud/apps/activity
/var/www/owncloud/apps/encryption
/var/www/owncloud/apps/external
/var/www/owncloud/apps/files
/var/www/owncloud/apps/files_external
/var/www/owncloud/apps/files_pdfviewer
/var/www/owncloud/apps/files_sharing
/var/www/owncloud/apps/files_texteditor
/var/www/owncloud/apps/files_trashbin
/var/www/owncloud/apps/files_versions
/var/www/owncloud/apps/files_videoviewer
/var/www/owncloud/apps/firstrunwizard
/var/www/owncloud/apps/gallery
/var/www/owncloud/apps/notifications
/var/www/owncloud/apps/provisioning_api
/var/www/owncloud/apps/templateeditor
/var/www/owncloud/apps/user_external
/var/www/owncloud/apps/user_ldap
```
Is this intended?  Where is the app now if not in the owncloud-server package?

**Comment by RealRancor** [comment]
Documents is not shipped anymore since two major versions (8.0) and needs to be manually installed via the oC internal appstore. See this wiki page which apps are shipped: https://github.com/owncloud/core/wiki/Apps-in-the-release

**Comment by anomaly256** [comment]
What is this 'oc internal appstore' you speak of?  Is it something other than the 'Apps' item in the oc dropdown menu?  I'm guessing it is because 'Documents' isn't listed anywhere within that either

**Comment by anomaly256** [comment]
This?  https://apps.owncloud.com/content/show.php/Documents?content=168711
Bit off topic but I'd like to comment that it would be nice if apps.owncloud.com were accessible from within owncloud itself :)

**Comment by RealRancor** [comment]
Yes, i mean the "Apps" item within ownCloud itself. The documents app will appear within the "Productivity" category.

I think you can close here and see https://owncloud.org/support/ for the support channels where you can get help with that issue if the app doesn't show app for you.

**Comment by anomaly256** [comment]
Ok thanks... It doesn't show there, I'll check out the support channels provides
