### ISSUE TITLE
Fix Util::addScript so that it can pick the apps where it's needed

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#21605]
Most apps are only looking at injecting JS into files and files_sharing, but I don't think we should restrict what devs can do with their apps, so let's be open and simply add a new variable to the signature.

### Before

`Util::addScript($myApp, 'myscript');`

### After

`Util::addScript($myApp, 'myscript', [files, files_sharing]);`

`[files, files_sharing]` would be the default value.

----
@BernhardPosselt @nickvergessen @PVince81 @MorrisJobke

**Comment by nickvergessen** [comment]
No, we should instead make more use of
```php
		$eventDispatcher = \OC::$server->getEventDispatcher();
		$eventDispatcher->addListener('OCA\Files::loadAdditionalScripts', []);
```

**Comment by nickvergessen** [comment]
Sample of the activity app loading it's sidebar JS
https://github.com/owncloud/activity/blob/master/lib/fileshooksstatic.php#L42-L43

Event is dispatched in https://github.com/owncloud/core/blob/8aaab0dbadf1798bdc11e8fefddad01cf23e1892/apps/files/controller/viewcontroller.php#L205-L205

**Comment by nickvergessen** [comment]
So this allows files to be only loaded on the files frontpage, which is exactly what is needed here.

**Comment by oparoz** [comment]
You missed the part where it's needed in more locations than just Files

**Comment by PVince81** [comment]
I thought about maybe a more global event "\OC::appResourcesLoaded" to give apps a chance to do something after an app has added the resources to load.

**Comment by oparoz** [comment]
The problem with new methods is that it won't fix the current situation unless devs are updating their apps, which they may not in a timely manner, etc. leading to frustration and bug reports.

So, while I agree that dispatchers are the way forward, I'm thinking maybe the current situation could be fixed as well?

**Comment by PVince81** [comment]
@oparoz how to fix the current situation ?
The proposal you made with the extra arguments to `addScript` would also require app devs to update their apps

**Comment by oparoz** [comment]
> The proposal you made with the extra arguments to addScript would also require app devs to update their apps

Not necessarily, but I'm being selfish. It would restrict the problem to Files and Sharing and clean up the JS mess in all the other loaded apps.

**Comment by nickvergessen** [comment]
Which means it breaks admin and personal page to begin with.
Not really a step forward in my eyes.

**Comment by MorrisJobke** [comment]
> Which means it breaks admin and personal page to begin with.

Correct. I will break all the apps that rely on the fact that it is loaded everywhere :(

**Comment by oparoz** [comment]
> Which means it breaks admin and personal page to begin with.

Why? admin and personal are not in the Files app's "namespace"

**Comment by nickvergessen** [comment]
Well you want to add a default value for addScript which is used everywhere.

Anyway, let's move forward instead of discussing in circles. If you think there are controllers missing a `$this->eventDispatcher->dispatch()` call, we should add them and start a list of them for documentation

**Comment by MorrisJobke** [comment]
> Why? admin and personal are not in the Files app's "namespace"

But the JS is maybe needed to do something there ;)

**Comment by karlitschek** [comment]
hmm. this breaks comoatibility with old apps. something we can't do

**Comment by oparoz** [comment]
> But the JS is maybe needed to do something there ;)

Ah, yes, if an app needs to customise those pages...

> hmm. this breaks comoatibility with old apps. something we can't do

These unmaintained apps are breaking every release of ownCloud and the only recourse users have is to simply disable them, **after having spent time trying to figure out what was wrong with their setup**.

Adding the dispatcher to more core apps is the way forward, but it won't stop old apps from messing up instances for as long as that addScript method stays as-is.

**Comment by nickvergessen** [comment]
They can also throw an exception in app.php if they want, killing your hole instance.
Do the way forward, we can't change the past, and we need to retain it for 2-3 years.
Thats our BC phase and not up for discussions.

Create issues in the repos of the apps doing the "breaking" stuff and advice them to use the new way.
That's all we can do.
