### ISSUE TITLE
WebDAV-Sync aborts with ownCloud 8.2.1 and php7

### ISSUE THREAD

**Issue by xn--nding-jua** [owncloud/core#21600]
### Steps to reproduce
1. Use FolderSync-Lite for Android to sync some pictures (each with around 3.4 MB in size) between Android-Mobilephone and ownCloud (upload)
2. after some pictures are uploaded the sync-process aborts with "Internal Server Error"
3. switching to php5.6 and it works
4. switching to php7.0.1 it does not work

### Expected behaviour
The sync-process should finish successfully.

### Actual behaviour
The upload process aborts on Android, but on Windows 10-client and TotalCommander for Android it works. So it has something to do with the WebDAV-handling within FolderSync.

Maybe related to this issue: https://github.com/owncloud/core/issues/21352

### Server configuration
**Operating system**:
Ubuntu 14.04.2 LTS

**Web server:**
Apache (unknown version)

**Database:**
SQL 5.4

**PHP version:**
PHP 5.6 (working)/7.0.1 (aborting)

**ownCloud version:** (see ownCloud admin page)
8.2.1.4

**Updated from an older ownCloud or fresh install:**
from an older installation (6.x -> 7.x -> 8.0 -> 8.1 -> 8.2.1)

**List of activated apps:**
Enabled:
  - activity: 2.1.3
  - bookmarks: 0.6
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - documents: 0.11.0
  - encryption: 1.1.0
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - galleryplus: 14.3.0
  - logreader: 1.1.0
  - mail: 0.2.1
  - music: 0.3.8
  - news: 6.1.1
  - notifications: 0.1.0
  - ocusagecharts: 3.4.5
  - tasks: 0.8.1
  - updater: 0.6

Disabled:
  - external
  - files_external
  - gallery
  - provisioning_api
  - templateeditor
  - user_external
  - user_ldap

**The content of config/config.php:**
    "system": {
        "instanceid": "12345",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "www.12345.de",
        ],
        "datadirectory": "\/www\/htdocs\/w00bd480\/12345\/cloud\/data",
        "tempdirectory": "\/www\/htdocs\/w00bd480\/tmp",
        "dbtype": "mysql",
        "version": "8.2.1.4",
        "dbname": "12345",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "mail_from_address": "webmaster",
        "mail_smtpmode": "php",
        "mail_domain": "12345.de",
        "forcessl": true,
        "trashbin_retention_obligation": "30, 60",
        "versions_retention_obligation": "auto",
        "loglevel": 4,
        "log_rotate_size": 10485760,
        "logtimezone": "Europe\/Berlin",
        "check_for_working_webdav": true,
        "check_for_working_htaccess": true,
        "xframe_restriction": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": true,
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "singleuser": false,
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "appstore.experimental.enabled": true,
        "filesystem_check_changes": 0,
        "default_language": "de",
        "updatechecker": false,
        "cipher": "AES-256-CFB",
        "minimum.supported.desktop.version": "2.0.0",
        "filelocking.enabled": true
    },

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
Android FolderSync-Lite
Android ownCloud Client
Windows 10 ownCloud Client 2.1

**Browser:**
Firefox 43.0.4

**Operating system:**
Android 5.0 on Samsung Galaxy S5

**Comment by DeepDiver1975** [comment]
@xn--nding-jua anything in the owncloud log or the apache error log?

**Comment by xn--nding-jua** [comment]
@DeepDiver1975 No, nothing related to the upload-process. The sync has aborted on all three Android-phones the last three days... the log is OK for this time.

The fatal-errors are related to some bad addressbook-card-pictures. Yesterday I've switched back to php5.6 and the "Cannot modifiy header blahblah" started again

**Comment by DeepDiver1975** [comment]
> The fatal-errors are

hmmm - fatal php errors usually cause log entries .....

Well - we are aware that php7 and sabre 3.0 have issues which we are currently working on.

**Comment by xn--nding-jua** [comment]
OK, then maybe we should close this issue already, because it is only this single software. Total Commander is working. And under php5.6 everything is working well. I can reopen it, if this still occures in the next release of oC.
