### ISSUE TITLE
How to change login page with theme

### ISSUE THREAD

**Issue by gig13** [owncloud/core#21619]
When using the theming, what files need to be modified to adjust some small links on the login page? The theme has been applied, but some very minor additional changes are desired for the login page.

### Expected behavior - Two small changes
1. Click on the "logo" area to link to another website (main company website for example).
2. Add an "icon image" under the login credentials area to link to another website (main company website for example)

### Actual behavior
The Web theme does not allow for URL redirect on the login logo, and it is not clear what other files need to be modified to make additional customization to the layout and functionality of the login page.

### Server configuration
**Operating system**: Ubuntu

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.5

**ownCloud version:** 8.2.1

**Updated from an older ownCloud or fresh install:** Fresh Install

**Are you using encryption:** NO

### Client configuration
**Browser:** Chrome, Firefox, Safari

**Operating system:** Windows, Mac

@MorrisJobke

**Comment by DeepDiver1975** [comment]
Create a copy of https://github.com/owncloud/core/blob/master/core/templates/layout.guest.php within the template directory - e.g. themes/example/core/templates/layout.guest.php

Within this file you can customize the basic layout as you like.

@gig13 please close if this fits your needs.

**Comment by gig13** [comment]
Good to go, closing.
