### ISSUE TITLE
initial setup broken on master

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#21621]
I can no longer set up a fresh installation on master. Page loaded forever but I never see the setup/login page.

The only error message I see is:

````
server reached MaxRequestWorkers setting, consider raising the MaxRequestWorkers setting
````

git bisect lead me to this PR: https://github.com/owncloud/core/pull/21479. Before this PR the initial setup works, after the PR it fails like described above. I'm the only one who experience this behavior?

cc @MorrisJobke Please have a look, Thanks!

**Comment by LukasReschke** [comment]
Had this as well. Fixed it by restarting my Apache. Thought it was just me :speak_no_evil:

**Comment by schiesbn** [comment]
> Had this as well. Fixed it by restarting my Apache. Thought it was just me

Tried this multiple times, didn't helped in my case

**Comment by LukasReschke** [comment]
Voting for reverting https://github.com/owncloud/core/pull/21479 then.

Any objections, @MorrisJobke @icewind1991?

**Comment by MorrisJobke** [comment]
I would really like to understand the actual issue. But a revert for now is okay.

**Comment by LukasReschke** [comment]
Revert: https://github.com/owncloud/core/pull/21622
