### ISSUE TITLE
In calendar app the time (AM/PM) is cut off

### ISSUE THREAD

**Issue by bnvk** [owncloud/core#21633]
The experience I am having is:

In the "create new calendar event" modal which pops up, the time field only lists hours + minutes, while the AM / PM part is hidden (due to input field being too small). The only way to discover if an event is AM or PM is to put cursor into field and go to the far right

![owncloud-am-pm](https://cloud.githubusercontent.com/assets/48677/12247005/289d6460-b8b2-11e5-9640-ada3f631ce06.png)

I'm using Chromium in Debian.

**Comment by RealRancor** [comment]
@bnvk Plese close and re-open in https://github.com/owncloud/calendar/issues using the issue template provided here: https://github.com/owncloud/calendar/blob/master/CONTRIBUTING.md#short-version
