### ISSUE TITLE
Can not share with case sensitive userbackends and remote urls anymore

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#21639]
We lowercase the search before passing it in to the backends:
https://github.com/owncloud/core/blob/372f54075fda0567d9df977b2e49ed1fdae0a60a/apps/files_sharing/api/sharees.php#L356-L356

For me this breaks remote shares, because my virtual host does not match anymore. Maybe others have a similar set up.

And the same may apply to user backends. if you have a case sensitive user/group backend, it will not match anymore. Each backend should itself take care of lowering or not?

cc @rullzer as discussed

**Comment by rullzer** [comment]
At least the user db backend does the lowering itself. And the same holds for the group backend. I assume other backends do it this way as well since if you pass it lowercase it still has to be matches properly.

I'll prepare a PR.
