### ISSUE TITLE
Area that opens the sidebar is too small, introduce double clicking?

### ISSUE THREAD

**Issue by pellaeon** [owncloud/core#21635]
## Current behavior
- Single clicking on the name ( `<span class="nametext">` elements) opens it
- Single clicking on elsewhere within `<a class="name">` opens the sidebar

## Problem
- Area that opens the sidebar varies according to name length. I often accidently opens the file when I just want to view its sidebar.
- Clicking on the date `<td class="date">` nor the filesize `<td class="filesize">` opens the sidebar

## Suggestion
- Single clicking on anywhere within the `<tr>` opens the sidebar. Except for file actions like favorite, share and action menu.
- Double clicking on area described above opens the file.

## Version
master 45c41e2b2cefa97c9d8c3bc73cfc088839640d1d

**Comment by PVince81** [comment]
@owncloud/designers

**Comment by jancborchardt** [comment]
The sidebar is alsp opened by clicking on Share, and the Versioms and Details entries in the menu. Bringing it up on clicking the rest of the row is just an addition, so I see this as a non-issue.

Definitely double-click is not something we will introduce, as it is not used anywhere on the web for actions like these. (Except zoom mechanisms on Maps / Picture apps.)

**Comment by pellaeon** [comment]
Google Drive uses this, single click select, double click open.

If I send a PR to enable opening sidebar on rest of the row, will you accept it?

Let me illustrate my points a bit more, first let me define the areas:
1. the area that opens the file is `<span class="nametext">`, whose height equals the `td`, and width equals to the length of the text. It not only includes the text but also white spaces above and below the text.
2. the area that opens the sidebar is elsewhere within `<a class="name">`

I think the biggest problem is that **there are no clear boundaries to separate the areas which opens the file and which opens the sidebar.** (except for the buttons)
If clicking on area 2, which appear to user as white spaces within the row, opens the sidebar:
- why not white spaces to the right of date field opens the sidebar?
- why not white spaces in area 1 outside the text opens the sidebar, but opens the file?

I think this is quite inconsistent.

**Comment by jancborchardt** [comment]
Then I would rather say that the rest of the whitespace should either select the file, or simply also open it.

**Comment by jancborchardt** [comment]
Closing this because the current behavior is fine.
