### ISSUE TITLE
Error logs are written in owncloud.log file when a file is deleted in a DropBox mountpoint

### ISSUE THREAD

**Issue by davitol** [owncloud/core#21642]
### Steps to reproduce
1. Configure a Dropbox mountpoint
2. Using web interface, delete a file from the Dropbox mountpoint 
### Expected behaviour

No logs should be shown in owncloud.log file
### Actual behaviour

The following log is printed in owncloud.log file

```
{"reqId":"MzKaL61SXuL1oxYqf6SL","remoteAddr":"82.159.139.58","app":"files_external","message":"Resource at uri: https:\/\/api.dropbox.com\/1\/fileops\/delete could not be found","level":3,"time":"2016-01-12T09:47:57+00:00"
```
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:  ownCloud Enterprise Edition 9.0 pre alpha (daily) Build:2016-01-12T04:19:25+00:00 373776b8d84bece3df4a06b157bbe41f51ef511d

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** yes; dropbox.
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Firefox

**Comment by davitol** [comment]
Log in as a non-admin user, deleting a file the following logs are written:
```
{"reqId":"vFZckK6x8uP\/ANSELPmr","remoteAddr":"82.159.139.58","app":"PHP","message":"opendir(\/opt\/owncloud\/data\/user1\/files_trashbin\/files): failed to open dir: No such file or directory at \/opt\/owncloud\/lib\/private\/files\/storage\/local.php#96","level":3,"time":"2016-01-12T10:15:21+00:00"}
{"reqId":"+Yv0LNJxF5TBLaRj6iCq","remoteAddr":"82.159.139.58","app":"files_external","message":"Resource at uri: https:\/\/api.dropbox.com\/1\/fileops\/delete could not be found","level":3,"time":"2016-01-12T10:15:43+00:00"}
{"reqId":"PYtemfYYilU90VRZiRVl","remoteAddr":"82.159.139.58","app":"PHP","message":"Undefined index: permissions at \/opt\/owncloud\/lib\/private\/files\/fileinfo.php#198","level":3,"time":"2016-01-12T10:16:10+00:00"}
{"reqId":"PYtemfYYilU90VRZiRVl","remoteAddr":"82.159.139.58","app":"PHP","message":"Undefined index: etag at \/opt\/owncloud\/lib\/private\/files\/fileinfo.php#169","level":3,"time":"2016-01-12T10:16:10+00:00"}
```

**Comment by PVince81** [comment]
Did you open the trashbin ? If yes you probably saw https://github.com/owncloud/core/issues/21378 which are unrelated to Dropbox.

The first message is indeed strange. Maybe it's because after deleting the file we check that the file is really gone from the remote, but forget to catch/ignore the exception.

**Comment by davitol** [comment]
@PVince81 You are right about my comment, I opened the trashbin, so it would be the other issue. 
The issue should be only focus on the dropbox log written above.

**Comment by PVince81** [comment]
please try again with new dropbox app and reopen if it still occurs
