### ISSUE TITLE
Using an external storage mountpoint, unchecking previews checkbox should disable the file previews

### ISSUE THREAD

**Issue by davitol** [owncloud/core#21646]
### Steps to reproduce
1. Configure a Dropbox mountpoint
2. When configuring, uncheck 'Enable previews' checkbox
### Expected behaviour

The file previews should not longer be visible
### Actual behaviour

The previews are still available
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:  ownCloud Enterprise Edition 9.0 pre alpha (daily) Build:2016-01-12T04:19:25+00:00 373776b8d84bece3df4a06b157bbe41f51ef511d

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** yes; dropbox.
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Firefox

**Comment by PVince81** [comment]
Does this also happen for other storage types or only Dropbox? (generic issue vs storage specific issue)

**Comment by davitol** [comment]
@PVince81 Tested in SFTP and fails, but it works using local as external storage. Let me check with all the storages types available and I will write the results here.

**Comment by PVince81** [comment]
If SFTP fails too, then it's likely a global issue.
The "Local" one is a bit special.

So if you find 2-3 non-local storages that don't work, it's enough to qualify as "general issue"

**Comment by davitol** [comment]
Tested also in SMB and it doesn't work, so let's qualify it as "general issue"

**Comment by PVince81** [comment]
Can you retest with 9.1.4 or 9.1.5 RC1 ? there was a fix related to disabling previews, maybe it was in 9.1.4

**Comment by PVince81** [comment]
Please reopen if issue persists in 10.0.4
