### ISSUE TITLE
Server errors causing client crash on first sync of large dataset

### ISSUE THREAD

**Issue by cscashby** [owncloud/core#21645]
OwnCloud Windows client crashes not long after startup - fairly large client dataset around 170 GB - against Server version 8.3.

I've reported in the client issues list but was advised to post here.  Additional logs can be provided if it's required.

Some errors in server log (Ubuntu ):

Exception: {"Message":"An exception occurred while executing 'INSERT INTO oc_file_locks (key,lock,ttl) SELECT ?,?,? FROM oc_file_locks WHERE key = ? HAVING COUNT(*) = 0' with params [\"files\\/1c21f1a5699694d9f93f26edf2121bb3\", 1, 1452534262, \"files\\/1c21f1a5699694d9f93f26edf2121bb3\"]:\n\nSQLSTATE[23000]: Integrity constraint violation

And PHP errors:
unlink(FILENAME-chunking-1167022733-27): No such file or directory at /var/www/owncloud/lib/private/files/storage/local.php#190

Note - the owncloud server has an NFS r/w automounted as a data source.  MySQL and OwnCloud install directories are local.

Server is Ubuntu 14.04.3 LTS (GNU/Linux 3.19.0-43-generic x86_64)
mysql  Ver 14.14 Distrib 5.5.46, for debian-linux-gnu (x86_64) using readline 6.3
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

Reboot of server attempted and has not fixed the issue.

**Comment by karlitschek** [comment]
can you open this in the client repository please? Thanks

**Comment by cscashby** [comment]
I did - https://github.com/owncloud/client/issues/4346#issuecomment-170847584 - advised to file it here.
