### ISSUE TITLE
database table "oc_jobs" isn't updated

### ISSUE THREAD

**Issue by aberndt2406** [owncloud/core#21649]
Steps to reproduce
1.change path of logfile in config.php 
2.disable app "Versions"

Expected behaviour
1. old values path should be deleted
2. value "OCA\Files_Versions\BackgroundJob\ExpireVersions" should be deleted

Actual behaviour
values are still available

Server configuration
Operating system: openSUSE 13.2
Web server: apache 2.4.16
Database: mysql 
PHP version: 5.6.1
ownCloud 8.2.1

**Comment by karlitschek** [comment]
@icewind1991 FYI

**Comment by nickvergessen** [comment]
versions and trashbin should be affected both in the same way.

We could simply fix it by listening to the `'OC_App', 'pre_disable'` hook and if the app is the same app remove the background job:
```php
		if ($params['app'] === 'files_versions') {
			\OC::$server->getJobList()->remove('OCA\Files_Versions\BackgroundJob\ExpireVersions');
		}
```

However when re-enabling the app, the job is not readded (only on install or update, not on enable).
So unless we have a fix for that, we may have to live with this.

**Comment by aberndt2406** [comment]
...what about the old logfile path?

Regards
Achim

Von meinem Windows Phone gesendet
________________________________
Von: Joas Schilling<mailto:notifications@github.com>
Gesendet: �12.�01.�2016 16:32
An: owncloud/core<mailto:core@noreply.github.com>
Cc: Berndt, Achim<mailto:aberndt@studio-hamburg.de>
Betreff: {Disarmed} Re: [core] database table "oc_jobs" isn't updated (#21649)


versions and trashbin should be affected both in the same way.

We could simply fix it by listening to the 'OC_App', 'pre_disable' hook and if the app is the same app remove the background job:

        if ($params['app'] === 'files_versions') {
            \OC::$server->getJobList()->remove('OCA\Files_Versions\BackgroundJob\ExpireVersions');
        }

However when re-enabling the app, the job is not readded (only on install or update, not on enable).
So unless we have a fix for that, we may have to live with this.

�

**Comment by nickvergessen** [comment]
That's nothing we can do, because we can't know, what the old value was.
It's kind of the responsibility of the admin to remove/retain the file, when the log file config is changed, which shouldn't happen too often.

**Comment by aberndt2406** [comment]
Hi,

there should be only one entry for „\OC\Log\Rotate” in the table oc_jobs?!
If we define a new path for the logfile in the config.php, the other one must
be the old one.

Regards
Achim

Von: Joas Schilling [mailto:notifications@github.com]
Gesendet: Donnerstag, 14. Januar 2016 13:50
An: owncloud/core
Cc: Berndt, Achim
Betreff: {Disarmed} Re: [core] database table "oc_jobs" isn't updated (#21649)


That's nothing we can do, because we can't know, what the old value was.
It's kind of the responsibility of the admin to remove/retain the file, when the log file config is changed, which shouldn't happen too often.

**Comment by PVince81** [comment]
A new mechanism has been introduced in info.xml for apps to specify which jobs they need, which makes it possible to accurately delete irrelevant jobs upon disabling.

If you still see this issue in 9.1, feel free to reopen.
