### ISSUE TITLE
Make web UI use the dav v2 endpoint

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#21643]
@DeepDiver1975 is the dav v2 endpoint for files ready to be used ?

I wondered about whether and when we should make the web UI use that one instead.
Hopefully it's only a matter of renaming the URL from "remote.php/webdav" to "remote.php/dav/files/$user/" ?

Asking mostly in regards to testing. Is the files v2 endpoint ready ?

CC @SergioBertolinSG who asked about it

**Comment by LukasReschke** [comment]
Closed in favour of https://github.com/owncloud/core/issues/22753
