### ISSUE TITLE
Getting folder size (length) via webdav propfind

### ISSUE THREAD

**Issue by Christophe42** [owncloud/core#21650]
Not really a bug, but I want to get the folder size when listing files via webdav.
I understand there is performance penalty but users want to see it.
I know it is stored somewhere in an ownCloud cache (fscache?), so technically the information could be sent as this information is also shown in the web interface of ownCloud.

### Steps to reproduce
1. Create a folder
2. Upload some files to it
3. Try to get folder size via propfind (via custom property oc:size)
    This is what is sent by the Java Sardine client code (works well):

#### Request:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<propfind xmlns="DAV:">
  <prop>
    <creationdate />
    <displayname />
    <getcontentlength />
    <getcontenttype />
    <getetag />
    <getlastmodified />
    <resourcetype />
    <oc:size xmlns:oc="http://owncloud.org/ns" />
    <oc:permissions xmlns:oc="http://owncloud.org/ns" />
  </prop>
</propfind>
```
#### Response:
In the response I get the folder list and for each item:
* oc:id (never asked for it)
* oc:permissions (even if I do not ask for it)
* oc:size is (always empty string)

How can I get the folder size via webdav while listing ?
I understand there have been some changes in recent ownCloud versions (concerning allProps and the oc:id/oc:permissions). But I cannot find a way to get the folder size while listing.

### Expected behaviour
Expecting to get the folder size via the custom property oc:size or via the getcontentlength

### Actual behaviour
The props always contain oc:id and oc:permissions, even when not asking for them
oc:size is always empty (so no size information about folder ?)

### Server configuration
**Operating system**: Debian

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** ownCloud 1:7.0.8~dfsg-1hitec3 (Debian) (stable)

**Updated from an older ownCloud or fresh install:**

**List of activated apps:** Just base installation of ownCloud

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
Potentially sensitive, works well with sharing, groups and login and so on...

### Client configuration
Java Sardine library (list method is used)

#### Web server error log
Not an error

#### ownCloud log (data/owncloud.log)
Not an error

#### Browser log
Not an error

**Comment by DeepDiver1975** [comment]
{http://owncloud.org/ns}size is supposed to hold the folder size

**Comment by DeepDiver1975** [comment]
![bildschirmfoto von 2016-01-12 14-21-44](https://cloud.githubusercontent.com/assets/1005065/12264551/d5fb71bc-b937-11e5-98f2-e7088c6fb509.png)

**Comment by DeepDiver1975** [comment]
wokrs for me -> close

**Comment by Christophe42** [comment]
I changed the request xml to be exactly like yours but still get the same response, are you using ownCloud 1:7.0.8 ?

**Comment by DeepDiver1975** [comment]
I'm using git master which is the upcoming OC9

**Comment by DeepDiver1975** [comment]
Possibly this property was not supported back in oc7

**Comment by Christophe42** [comment]
Ok thanks for your support, we probably must (carefully) migrate to a new version.
