### ISSUE TITLE
Input boxes rounded corners are placed wrongly on setup page, caused by #21377

### ISSUE THREAD

**Issue by pellaeon** [owncloud/core#21658]
![2016-01-12 11 18 45](https://cloud.githubusercontent.com/assets/916913/12267714/6dfe8a5c-b984-11e5-9adc-4b14c7922dac.png)
![2016-01-12 11 19 00](https://cloud.githubusercontent.com/assets/916913/12267715/73d8203c-b984-11e5-8566-074ec862e403.png)

See the `.groupbottom` elements (inputs at the bottom), rounded corners are placed wrongly. If I revert #21377 it works again.

**Comment by pellaeon** [comment]
Relevant: #21377 @ChristophWurst

**Comment by karlitschek** [comment]
@jancborchardt

**Comment by ChristophWurst** [comment]
@jancborchardt should we use a more specific rule instead?
I've played around a bit and the best solution I can find is the following change:
```patch
diff --git a/core/css/styles.css b/core/css/styles.css
index 76c6dda..e78db6f 100644
--- a/core/css/styles.css
+++ b/core/css/styles.css
@@ -382,12 +382,13 @@ body {
 .groupbottom input {
        margin-top: 0;
        border-top: 0;
-}
-#body-login .groupbottom #password {
        border-top-right-radius: 0;
        border-top-left-radius: 0;
        box-shadow: 0 1px 0 rgba(0,0,0,.1) inset !important;
 }
+#body-login .groupbottom input[type=submit] {
+       box-shadow: none !important;
+}
 
 /* keep the labels for screen readers but hide them since we use placeholders */
 label.infield {
```

This reverts the modifications of #21377 and simply unsets the box shadow for the submit button (arrow) only. This works for the login page and the setup page. Is there any other view that might be affected?

**Comment by jancborchardt** [comment]
body-login and groupbottom is only use for log in and installation afaik. So go for it. :)
