### ISSUE TITLE
`Call to a member function acquireLock() on null` during installation

### ISSUE THREAD

**Issue by pellaeon** [owncloud/core#21657]
in /var/www/html/owncloud/lib/private/files/view.php on line 1838

## Steps to reproduce
1. clone the owncloud core repo, cd into it
2. git submodule init, git submodule update
3. visit setup page, fill in MySQL/MariaDB database credentials
4. submit
5. it shows a blank page, in Apache error log:
`PHP Fatal error:  Call to a member function acquireLock() on null in /var/www/html/owncloud/lib/private/files/view.php on line 1838`

## Version
- Ubuntu 14.04
- ownCloud master eac5d9fb3a52932fafdb200a2cf5d50fe9f1c759
- PHP 5.6.17
- 5.5.46-MariaDB

**Comment by PVince81** [comment]
Works for me with my usual checkout on the same commit and also latest master.

Did you also git clone any apps ?

**Comment by PVince81** [comment]
More info in this duplicate ticket https://github.com/owncloud/core/issues/21674 (nginx)

**Comment by PVince81** [comment]
@icewind1991 can you have a look ?

@mmattel @pellaeon are you able to bisect the issue to find which commit introduced this issue ?

**Comment by PVince81** [comment]
@LukasReschke is this similar to the install issue you found on master ? https://github.com/owncloud/core/issues/21669

**Comment by LukasReschke** [comment]
Different error message but likely to be the same due to the view instantiation.

**Comment by mmattel** [comment]
I did not clone any apps, only cloning core including submodules

**Comment by mmattel** [comment]
I just did the following:
- clear mysql so there are no leftovers from previous install tries
- delete the contents of the data folder
- delete the config.php file from the broken installation
- then:
```
sudo git log
[sudo] password for xxxx: 

commit eac5d9fb3a52932fafdb200a2cf5d50fe9f1c759
Merge: 2493cfe 0d0377e
Author: Thomas Müller <thomas.mueller@tmit.eu>
Date:   Tue Jan 12 15:01:46 2016 +0100

    Merge pull request #21336 from owncloud/system-root-certs
    
    Allow admins to add system wide root certificates

commit 2493cfede92c472c29cffc098206b8cdb7a2ca30
Merge: 4fc0fbe 8b6b042
Author: Thomas Müller <thomas.mueller@tmit.eu>
Date:   Tue Jan 12 14:46:09 2016 +0100

    Merge pull request #21640 from owncloud/add-config-to-disable-wellknown-chec
    
    Add config switch to disable the .well-known URL check

```
and checked out the commit previous the suspected one
```
sudo git checkout 2493cfede92c472c29cffc098206b8cdb7a2ca30
```

voila --> works, the installation completed sucessfully.
Seems that #21336 (Allow admins to add system wide root certificates) causes the problem.

@PVince81 @LukasReschke @icewind1991

**Comment by icewind1991** [comment]
Did you test it with https://github.com/owncloud/core/pull/21671?

**Comment by mmattel** [comment]
I just prepared the environment and cloned from master again which includes #21671 (merged).
This time the installation passed without any problems. Thanks @LukasReschke for the fix. :+1:
