### ISSUE TITLE
`Call to a member function isUserAgent() on null` after upgrading to 8.2.2

### ISSUE THREAD

**Issue by mikew** [owncloud/core#21652]
Upgraded from 8.2.1 to 8.2.2 last night, things looked fine but the client cannot connect and I'm seeing this error all over the logs:

```
PHP message: PHP Fatal error:  Call to a member function isUserAgent() on null in /var/www/owncloud/lib/private/connector/sabre/serverfactory.php on line 111
```

**Comment by karlitschek** [comment]
Can you post a full bug report using the template please? https://github.com/owncloud/core/blob/master/CONTRIBUTING.md
And how did you upgrade?

**Comment by nickvergessen** [comment]
The method was added in 8.1, and I can't see that error happening, and there is no way `$this->request` can be false with core and the shipped apps.

So more information is needed.

**Comment by nebulade** [comment]
I am hitting the same issue also upgrading from 8.2.1 -> 8.2.2. A fresh 8.2.2 installation does not have the issue. 

I upgraded by simply extracting the new version in place of the old one and then ran:
```
sudo -u www-data php /app/code/occ upgrade
```
Is there any other migration script I should run? I am using ldap for auth, otherwise no other non default app is enabled.

Thanks

**Comment by nebulade** [comment]
I just saw this in the admin panel:
"Your web server is not yet set up properly to allow file synchronization because the WebDAV interface seems to be broken."

and in the error log:
```
Error	PHP	Call to a member function isUserAgent() on null at /app/code/lib/private/connector/sabre/serverfactory.php#111	2016-01-20T09:38:06+00:00
Error	PHP	Undefined variable: request at /app/code/lib/private/connector/sabre/serverfactory.php#80	2016-01-20T09:38:06+00:00
Error	PHP	Argument 8 passed to OC\Connector\Sabre\ServerFactory::__construct() must implement interface OCP\IRequest, none given, called in /app/data/apps/files/appinfo/remote.php on line 43 and defined at /app/code/lib/private/connector/sabre/serverfactory.php#72
```

**Comment by nickvergessen** [comment]
The call was modified between 8.2.1 and 8.2.2
Seems like your `/app/data/apps/files/appinfo/remote.php` is still having the 8.2.1 code.

So the most important question is, how did you update?

**Comment by nebulade** [comment]
Ah! thanks for the hint about the code change. Indeed I still have the old code there, since I have the apps/ folder outside the ownlcloud installation, since I am on a readonly fs where owncloud is installed. Sorry for the report, sounds like a very specific issue to my setup.

**Comment by mikew** [comment]
Sorry for taking so long to reply. My issue was the same, old code was in `apps/`. Our installation uses Docker and our ownCloud image used a volume for ownCloud's `apps/` folder, which resulted in old code.

We've since dropped the volume, but now I am wondering if any apps ever expect write access to their installation directory.

**Comment by nickvergessen** [comment]
@LukasReschke is this catched by your signing stuff?

**Comment by LukasReschke** [comment]
Should get catched in 9.0. Yes :)

**Comment by nickvergessen** [comment]
Closing as such
