### ISSUE TITLE
Renaming and moving displays an error in public shared folder with edit permissions.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#21678]
### Steps to reproduce

1. Public share a folder, Allow editing.
2. Using another browser without login, try to rename a file.
or
2. Using another browser without login, try to move a file to another folder.

### Expected behaviour
Files are renamed or moved.

### Actual behaviour
Error is displayed.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Using enterprise theme.
{"installed":true,"maintenance":false,"version":"9.0.0.6","versionstring":"9.0 pre alpha","edition":"Enterprise"}
(current master)

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Comment by DeepDiver1975** [comment]
> Error is displayed and operation doesn't happen.

which one?

**Comment by SergioBertolinSG** [comment]
OK, edit, the operation actually happens.

It just displays an error.

When moving Could not move {filename}
When renaming Could not rename {filename}

Some logs:

```
{"reqId":"0hkNUqyR6HVPdmtfsHgs","remoteAddr":"HIDED_IP","app":"admin_audit","message":"Rename \"\/admin\/files\/Photos\/San Francisco.jpg\" to \"\/admin\/files\/Photos\/FOLDEREXTRA\/San Francisco.jpg\" by IP HIDED_IP, owner: admin [CLIENT_IP: HIDED_IP]","level":1,"time":"2016-01-13T09:56:17+00:00","method":"MOVE","url":"\/public.php\/webdav\/San%20Francisco.jpg"}
{"reqId":"0hkNUqyR6HVPdmtfsHgs","remoteAddr":"HIDED_IP","app":"PHP","message":"Call to a member function get() on a non-object at \/opt\/owncloud\/apps\/files_sharing\/lib\/updater.php#76","level":3,"time":"2016-01-13T09:56:17+00:00","method":"MOVE","url":"\/public.php\/webdav\/San%20Francisco.jpg"}
```

**Comment by DeepDiver1975** [comment]
> Call to a member function get() on a non-object at \/opt\/owncloud\/apps\/files_sharing\/lib\/updater.php#76","level":3,"time":"2016-01-13T09:56:17+00:00","method":"MOVE","url":"\/public.php\/webdav\/San%20Francisco.jpg

that's the one ...

@rullzer @icewind1991 @schiesbn mind having a look? THX

**Comment by rullzer** [comment]
@SergioBertolinSG could you retry... all seems to work overhere on master now.

**Comment by SergioBertolinSG** [comment]
@rullzer tested on current master, is still happening exactly the same way.

**Comment by rullzer** [comment]
ah mmm I see I get errors in the transfer log... but no error indicating otherwise... anyway I'll look into it

**Comment by rullzer** [comment]
PR  in #22159
