### ISSUE TITLE
A lot entries in the oc_jobs Table

### ISSUE THREAD

**Issue by Crotriop** [owncloud/core#21677]
I recently checked the oc_jobs Table of the mysql DB and saw that there are around 41.000 entries, most of them look like this:

http://imgur.com/d21hf5T

I've been told to report this to you, not sure if the template is any use but I complete this as good as possible.

### Steps to reproduce
Don't know, I just saw the issue

### Expected behaviour
less entries in this table ?

### Actual behaviour
41.000+ Entries in this table

### Server configuration
**Operating system**: 
Linux (this is shared hosting)

**Web server:** 
Apache

**Database:** 
mysql 5.6.27

**PHP version:** 
5.6.16

**ownCloud version:** (see ownCloud admin page)
8.2.2

**Updated from an older ownCloud or fresh install:**
Update

**List of activated apps:**

Default encryption module 1.1.0 
Deleted files 0.7.0
File Locking 
Gallery 14.2.0
Mail Template Editor 0.1
PDF Viewer 0.7
Provisioning API 0.3.0
Share Files 0.7.0
Text Editor 2.0
Updater 0.6
Versions 1.1.0
Bookmarks 0.6

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'ideal',
  'passwordsalt' => 'slatandpeppar',
  'secret' => 'shhhhtitssoquiet',
  'trusted_domains' => 
  array (
    0 => 'domain.net',
  ),
  'datadirectory' => '/www/htdocs/customernumber/folder1/ocwebroot',
  'overwrite.cli.url' => 'https://domain.net',
  'dbtype' => 'mysql',
  'version' => '8.2.2.2',
  'dbname' => 'dbname',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'user',
  'dbpassword' => 'youshouldnotseethis',
  'installed' => true,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'mail_from_address' => 'own',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'domain.net',
  'loglevel' => 1,
  'trashbin_retention_obligation' => '14, auto',
  'log_rotate_size' => 10485760,
  'maintenance' => false,
  'theme' => '',
  'tempdirectory' => '/www/htdocs/customernumber/folder1/ocwebroot/tmp/',
);
```

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
Yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Firefox

**Operating system:**
Windows 10

#### Web server error log
```
Insert your webserver log here
```
No access to that

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
I uploaded it here:
http://www40.zippyshare.com/v/9ol85iBj/file.html

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by PVince81** [comment]
Is your cron running properly ? It should have processed such jobs.

But also there was a bug in the past where the entries did not get deduplicated, which was fixed. But older entries might still live in the database.

Can you check the full string behind the "\Expire" column ? (it's truncated in your screenshot)
Are they all the same ?

**Comment by PVince81** [comment]
CC @MorrisJobke

**Comment by Crotriop** [comment]
Wow, thanks for your swift response !

I use Ajax cron and this seems to do it's job http://imgur.com/8QVk3RZ
It also seems that these entries (checked 5 of them) are all different, mainly. check yourself:
3 examples
http://imgur.com/YRJoSK3
http://imgur.com/HaUVzrW
http://imgur.com/H73Np46

**Comment by MorrisJobke** [comment]
Ah yes. This is already fixed. Let me lookup the PR.

**Comment by MorrisJobke** [comment]
versions jobs: #21109
trashbin jobs: #20790 

Both went into 8.1.5 and 8.2.2. So simply upgrade to one of those two versions and wait. The jobs table then should get smaller over time.

**Comment by Crotriop** [comment]
Ahm, I am on 8.2.2

**Comment by PVince81** [comment]
@Crotriop if you have lots of files, ajax cron is unlikely to be suitable as it won't run often enough.
Best is to use system cron.

**Comment by Crotriop** [comment]
Ok I'll try that

**Comment by MorrisJobke** [comment]
> Ahm, I am on 8.2.2

Then you maybe want to run one time the system cron from the command line (to clean up all the old entries - this will take some time) and then the ajax one may be capable to catch up with the fewer incoming jobs.

**Comment by Crotriop** [comment]
I'm on a shared hosting with no access to the commandline.
I've switched to "cron" in the Admin Page and it did not gave an error.
How long shall I wait for this to be completed ?

**Comment by MorrisJobke** [comment]
Without her ver access you can't properly setup the cron mode:  https://doc.owncloud.org/server/9.0/admin_manual/configuration_server/background_jobs_configuration.html#cron

As alternative you can set the cron mode to ajax again and then call it via script very often (and not only once every page load.

In a unix shell you should be able to do following to call the cron.php every 0.2 seconds. This then still take some time, but is a lot faster ;)

```bash
while true; do curl https://cloud.example.org/cron.php; sleep .2; done;
```

**Comment by Crotriop** [comment]
Ah thanks, this seems to help. The Number is going down slowly now.

Thanks god I got that RaspberryPi :)

Thanks for your help !

**Comment by Crotriop** [comment]
All cleared down now.
This worked nicely, thanks.
