### ISSUE TITLE
Feature Request: Default user group for new users

### ISSUE THREAD

**Issue by alve89** [owncloud/core#21672]
I think it was very helpful to set a config value that assigns a new user (who was authenticated against for example IMAP) to a specified group (e.g. "employees").
Otherwise there's always an action of an admin needed and an admin is not always available, so this new user is not able to use previously shared data.

What do you think about this?

**Comment by karlitschek** [comment]
Good idea. But this is something that could be done on the IDP / LDAP side. I don't think this is necessarily the business of ownCloud.

**Comment by alve89** [comment]
Sorry für reopening - but what should a user do, who doesn't have any external identity solution? Because that's (for me as a web hosting user) the reason why I use IMAP authentication. 

If there's no way to implement it, could you at least tell me if there's a method / function to assign a user to a group Sinai can modify the IMAP authentication?
