### ISSUE TITLE
Enhancement : Create a Unique Share URL linking to website OR local hard disk (if client is installed)

### ISSUE THREAD

**Issue by ghost** [owncloud/core#21688]
I would kile to propose an enhancement for sharing a file link between owncloud users (not a public share)...
#### Pain
- When adding files to OC, how to make the users aware of this ?  Usually, we send an email "Hey look at this file..." but which URL should be provided there ?
- There is no quick URL that allows a user to acces the file... and no way to provide a quick download/preview link :-(
#### Proposed Solution

Create a "share with owncloud user link" , which is a unique url that points either : 
- to the local file on the harddisk (already synchronized)
- OR on the owncloud website (if directory not synced on disk)
#### Technical possiblities :
- This unique url should check for the existence of the owncloud client installed locally (depends on operating system ?? Records a new filetype associated with owncloud client ??)
- If there is a client, the client should redirect the url to the file (by computing a full path to file according to the synchronized folder configuration in the client... so the somone should know where is located the file on the hard disk)
- Indeed there is no owncloud client, the url should open a browser and display the file directly
- It should be possible to point to one file (and download/display it) or to a directory (to list its content)
- As a side solution, this should be used to refer to owncloud documents in all web tools that organize the daily job ("to do's" programs as Jira, bitbucket, github, etc)
#### Ideal scenario
- Email recieved by a colleague : "Hey, I've updated the document test.doc"
- Clicking on the link (file already synchronized in background), it opens the document directly
- Review of the document, save it (what will update the document on the owncloud)
- Answer to email "OK, document approved" :-)

**Comment by stephane84** [comment]
@dvergeylen

**Comment by PVince81** [comment]
@stephane84 your proposal is an extension of the permalinks ticket: https://github.com/owncloud/core/issues/11732

In theory, once permalinks exist the client could parse the fileid out of it and match the file id known in its local database (given that we uniformize the formats).

**Comment by dvergeylen** [comment]
As of #24434, I guess this issue can be closed now?
