### ISSUE TITLE
owncloudcmd return 

### ISSUE THREAD

**Issue by paoloB132** [owncloud/core#21683]
owncloudcmd --version
ownCloud version 2.1.0
Using Qt 5.4.2

calling it from command line in order to manually sync, returns all time unrecognized option like:

owncloudcmd /root/mydir  https://mycloud.mydomain
Unrecognized option '/root/mydir'
Try 'owncloud --help' for more information

I want to sync manually and no interactive ... any hints ?

Regards,
Paolo.

**Comment by DeepDiver1975** [comment]
Please reopen in the client repo - THX
