### ISSUE TITLE
How to delete temporary database tables created during the Upgrade process

### ISSUE THREAD

**Issue by pako81** [owncloud/core#21686]
### Steps to reproduce
1. Upgrading oC from 8.2.1 to 8.2.2 by using the occ command and without the --skip-migration-test option
2. Upgrade fails after filling up the local file system because of not enough available storage
3. Running again the occ upgrade command this time with the --skip-migration-test option: this time upgrade succeeds
4. After upgrade, Database still contains the temporary table used during the migration test therefore has an increased size.

### Server configuration
**Operating system**:

RHEL 7.1 (one single machine running database and application server)

**Web server:**

Apache 2.4

**Database:**

MySQL

**PHP version:**

5.4

**ownCloud version:** (see ownCloud admin page)

8.2.2

**Updated from an older ownCloud or fresh install:**

Updated from 8.2.1

**Are you using external storage, if yes which one:** local/smb/sftp/...

Local/Windows Network Drives

**Are you using encryption:** yes/no

no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

LDAP

@MorrisJobke what would be the best way to bring the database back to the original size (therefore eliminating the temporary files created during the migration test). Would the occ maintenance:repair command be helpful or is a files:scan --all necessary (Customer has almost 400TB of storage and scanning all the files will require really a lot of time)?

@carlaschroder I guess the documentation needs also to be modified accordingly as is talking about a "temporary directory" for the database tables:
https://doc.owncloud.com/server/8.2/admin_manual/configuration_server/occ_command.html?highlight=occ#command-line-upgrade

**Comment by MorrisJobke** [comment]
> @carlaschroder I guess the documentation needs also to be modified accordingly as is talking about a "temporary directory" for the database tables:

```
... ownCloud first runs a simulation by copying all database tables to a temporary directory ...
```

it's not a directory but it copies it over to a new table (or better copies each table to a new one, runs the upgrade on them and then deletes them) ;)

**Comment by MorrisJobke** [comment]
> @MorrisJobke what would be the best way to bring the database back to the original size (therefore eliminating the temporary files created during the migration test). Would the occ maintenance:repair command be helpful or is a files:scan --all necessary (Customer has almost 400TB of storage and scanning all the files will require really a lot of time)?

There are tables generated with the same name but added 13 random characters:

`oc_filecache` will then be something like `oc_lkjashfiwnciwfilecache`

Simply drop those tables with the random characters in the name. In Sqlite it will generate a new database file with the name `oc_RANDOMCHARACTER.db` in the data dir. Simply delete then this file.

**Comment by pako81** [comment]
@MorrisJobke thanks! This is however what Customer has:

![image003](https://cloud.githubusercontent.com/assets/12248713/12296485/3a39f4ca-ba08-11e5-8d50-354df74129d9.jpg)

This table has a size of only 96k and does not explain the increase of several GB because of the migration test. Or is maybe the Data free parameter of this table (9.4 GiB) the allocated size for this table?

**Comment by MorrisJobke** [comment]
> This table has a size of only 96k and does not explain the increase of several GB because of the migration test. Or is maybe the Data free parameter of this table (9.4 GiB) the allocated size for this table?

Sorry. I'm not really how the data is occupied in mysql. But try to delete it and see if this then helps to free the space.

**Comment by pako81** [comment]
Before and after (/dev/mapper/rhel_owncloud-root):

´´´
 
[root@owncloud ~]# df -h
Filesystem                      Size  Used Avail Use% Mounted on
/dev/mapper/rhel_owncloud-root   80G   51G   30G  63% /
devtmpfs                         47G     0   47G   0% /dev
tmpfs                            47G  160K   47G   1% /dev/shm
tmpfs                            47G   17M   47G   1% /run
tmpfs                            47G     0   47G   0% /sys/fs/cgroup
/dev/sda1                       497M  124M  374M  25% /boot
/dev/gpfs                       815T  486T  330T  60% /gpfs
[root@owncloud ~]#
[root@owncloud ~]#
[root@owncloud ~]#
[root@owncloud ~]#
[root@owncloud ~]#
[root@owncloud ~]#
[root@owncloud ~]# df -h
Filesystem                      Size  Used Avail Use% Mounted on
/dev/mapper/rhel_owncloud-root   80G   51G   30G  63% /
devtmpfs                         47G     0   47G   0% /dev
tmpfs                            47G  160K   47G   1% /dev/shm
tmpfs                            47G   17M   47G   1% /run
tmpfs                            47G     0   47G   0% /sys/fs/cgroup
/dev/sda1                       497M  124M  374M  25% /boot
/dev/gpfs                       815T  486T  330T  60% /gpfs
[root@owncloud ~]#
 
´´´
Unfortunately no changes on the available space on disk

**Comment by MorrisJobke** [comment]
```sql
SELECT 
    table_name AS `Table`, 
    round(((data_length + index_length) / 1024 / 1024), 2) `Size in MB` 
FROM information_schema.TABLES 
WHERE table_schema = "owncloud";
```

`owncloud` in the where statement is the database name ;)

**Comment by pako81** [comment]
Here the output:

```

Table,"Size in MB"

oc_activity,0.17
oc_activity_mq,0.06
oc_appconfig,0.05
oc_file_locks,5380.39
oc_file_map,0.03
oc_filecache,31166.69
oc_files_trash,0.06
oc_group_admin,0.03
oc_group_user,0.03
oc_groups,0.02
oc_jobs,0.03
oc_ldap_group_mapping,0.03
oc_ldap_group_members,0.02
oc_ldap_user_mapping,0.03
oc_mimetypes,0.03
oc_notifications,0.08
oc_preferences,0.23
oc_privatedata,0.02
oc_properties,0.03
oc_share,0.06
oc_share_external,0.05
oc_storages,0.06
oc_users,0.02
oc_vcategory,0.06
oc_vcategory_to_object,0.03
oc_wnd_credentials,0.05
oc_wnd_global_creds,0.03
oc_wnd_mounts,0.02
oc_wnd_mounts_applicable,0.03
oc_wnd_personal_mounts,0.03

```

**Comment by MorrisJobke** [comment]
> oc_filecache,31166.69

31 GB in filecache. Not much we can do here. Can they check how many files and folders they have in the data dir (`find . | wc -l`should do the trick) and then run a `SELECT COUNT(*) FROM oc_filecache;` and compare the numbers. They could be slightly more, but shouldn't be the doubled count of files.

**Comment by pako81** [comment]
@MorrisJobke thanks. Customer agreed on closing this case.
