### ISSUE TITLE
Changing values of 'Available for textbox' generates a log error in owncloud.log file

### ISSUE THREAD

**Issue by davitol** [owncloud/core#21685]
### Steps to reproduce

1. As an admin user, configure an external storage mountpoint
2. In admin view change 'Available for textbox' value.

### Expected behaviour

No log error should be shown in owncloud.log file

### Actual behaviour

The following log error is printed in owncloud.log file

```
{"reqId":"xe1KUVsB\/1AwyPJtBUgP","remoteAddr":"82.159.139.58","app":"PHP","message":"usort(): Array was modified by the user comparison function at \/opt\/owncloud\/lib\/private\/user\/manager.php#244","level":3,"time":"2016-01-13T11:00:06+00:00"}
```

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:  ownCloud Enterprise Edition 9.0 pre alpha (daily) Build:2016-01-12T04:19:25+00:00 373776b8d84bece3df4a06b157bbe41f51ef511d

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** yes; dropbox.
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

**Comment by PVince81** [comment]
You got eagle eyes, spotting such log issues for small things :wink:

**Comment by PVince81** [comment]
@blizzz @LukasReschke @icewind1991 something weird in the user manager ?

**Comment by Xenopathic** [comment]
Unable to reproduce on current master
