### ISSUE TITLE
A log is written in owncloud.log when editing a text file that has been fed shared with a LDAP user

### ISSUE THREAD

**Issue by davitol** [owncloud/core#21680]
### Steps to reproduce
1. As admin user, configure a LDAP
2. Federate share a file.txt with a LDAP user
3. Log in oC with one user of the AD
4. Edit the file
### Expected behaviour

No log should be shown loging in oC.
### Actual behaviour

The following log is shown in owncloud.log after editing the file with a LDAP user, but the user can edit the file.

```
{"reqId":"CEtEPOI54X5ykvAn9p99","remoteAddr":"82.159.139.58","app":"files","message":" Backends provided no user object for user2@dockerXXXXXXXXXXXXXX\/","level":3,"time":"2016-01-13T09:44:25+00:00"}
{"reqId":"CEtEPOI54X5ykvAn9p99","remoteAddr":"82.159.139.58","app":"hook","message":"error while running hook (OCA\\Files_Versions\\Hooks::write_hook): Backends provided no user object for user2@dockerXXXXXXXXXXXXXXXX\/","level":3,"time":"2016-01-13T09:44:25+00:00"}
{"reqId":"CEtEPOI54X5ykvAn9p99","remoteAddr":"82.159.139.58","app":"hook","message":"error while running hook (OCA\\Activity\\FilesHooksStatic::fileUpdate): File with id \"4133\" has not been found.","level":3,"time":"2016-01-13T09:44:26+00:00"}
```
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:  ownCloud Enterprise Edition 9.0 pre alpha (daily) Build:2016-01-12T04:19:25+00:00 373776b8d84bece3df4a06b157bbe41f51ef511d

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** yes; dropbox.
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Chrome/Firefox

**Comment by karlitschek** [comment]
@schiesbn

**Comment by PVince81** [comment]
Looks like version app + activity having trouble with fed shared files ?

**Comment by PVince81** [comment]
Please reopen if issue persists with 10.0.4
