### ISSUE TITLE
Selecting several files in small windows requires to close sidebar per each file selected.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#21698]
## Steps to reproduce:

Using a small screen, mobile device or reduce the size of the browser until the left sidebar is hided.
1. Select 10 files. (Close sidebar 10 times)

## Expected behaviour
You are allowed to select several files quickly. 

## Observed behaviour
All sidebars has to be closed. Making the selection very slow and annoying.

A screen like this appears per file selected:
![screen shot 2016-01-13 at 18 25 24](https://cloud.githubusercontent.com/assets/9048796/12302081/b05bdaf4-ba23-11e5-9084-df5508aef97e.png)

Master branch
{"installed":true,"maintenance":false,"version":"9.0.0.6","versionstring":"9.0 pre alpha","edition":""}

Seen in Firefox, Chrome and Safari on iPad.

**Comment by SergioBertolinSG** [comment]
cc @owncloud/designers

**Comment by jancborchardt** [comment]
Yeah, select should clearly not open the sidebar. If I remember correctly I mentioned this in another issue as well but can't find it.

What do you think @PVince81 @owncloud/designers?

**Comment by PVince81** [comment]
The discussion has changed several times, but it was never said that select should not open the sidebar at all.

I'm fine with changing the behavior again.

Should the sidebar auto-close if it's open when a user clicks the checkbox ?

**Comment by jancborchardt** [comment]
@PVince81 yeah, unfortunately one of the aspects that mainly becomes clear with daily use.

About the auto-closing: The sidebar should be closed if the selected file is any other file than the one for which the sidebar is currently open, or if multiple files are selected (since we do not do multiple files sharing etc yet).

**Comment by jancborchardt** [comment]
@owncloud/javascript we need to fix this for 9.0 – it makes selection on mobile completely unusable as the sidebar is always opened full-screen for every selection you make. Another point for not automatically opening it on select.

**Comment by PVince81** [comment]
> The sidebar should be closed if the selected file is any other file than the one for which the sidebar is currently open

Can you elaborate ?
This sounds like the following:

1. User selects "test1.txt" by clicking on a white space within its row
1. System opens side bar and displays details of "test1.txt"
1. User selects another file "test2.txt" (ie not the currently displayed one) by clicking on a white space within its row
1. System closes sidebar

I don't think it's correct to close the sidebar in this situation.

Maybe you meant decouping the sidebar from the checkboxes ? So if you select files with the checkboxes, I proposed to always close the sidebar regardless of how many files were selected.
Every checkbox action closes the sidebar.
However if checkboxes are selected, and the user clicks in the white space, the sidebar would reopen for that specific file ? Or not ?

**Comment by PVince81** [comment]
Let me prepare a PR for this: checkbox action always closes the sidebar.

**Comment by PVince81** [comment]
@jancborchardt here we go https://github.com/owncloud/core/pull/22400

**Comment by MorrisJobke** [comment]
> Maybe you meant decouping the sidebar from the checkboxes ? So if you select files with the checkboxes, I proposed to always close the sidebar regardless of how many files were selected.
> Every checkbox action closes the sidebar.
> However if checkboxes are selected, and the user clicks in the white space, the sidebar would reopen for that specific file ? Or not ?

Correct. I think @jancborchardt meant the checkboxes. Clicking on the whitespace beside a file should open the sidebar nevertheless, but once the selection is continued with un-/checking another check box the sidebar should close again.
