### ISSUE TITLE
Integrate updater further into Versions section in settings

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#21691]
Now that we simplified the updater further and further, it's time that we put it directly into the versions section where it belongs.

The reasoning being that when your version is up to date (most of the time this will be the case), the app will simply display a message »up to date« next to the version in the Version section.

When there is an update, the message could be »Version 8.2.3 available« and a button »Update« next to it. On click, the section could expand to what it is now.

cc @karlitschek @te-online @VicDeo

(Reopen of https://github.com/owncloud/updater/issues/212 )

**Comment by karlitschek** [comment]
Yes. Definitely!

**Comment by DeepDiver1975** [comment]
> When there is an update, the message could be »Version 8.2.3 available« and a button »Update« next to it. On click, the section could expand to what it is now.

how do we implement this from a technical perspective?

The button will redirect the the url of the updater which we expect to be living in OCWEBROOT/updater ?

**Comment by jancborchardt** [comment]
I guess by inserting the template generated from the Updater app in there? In core check if updater us installed – if yes, inject it there.

**Comment by DeepDiver1975** [comment]
> I guess by inserting the template generated from the Updater app in there? I

there is no updater app - and there is no template which can be loaded.
the new updater is a self contained cli tool and web app.

**Comment by nickvergessen** [comment]
Check in core if the folder exists, if yes show the button :speak_no_evil: 
Hacky and "depenedency" but it works?

**Comment by jancborchardt** [comment]
@DeepDiver1975 Let me be extra-clear:
However we do the update process from the web – the only interface exposed by default should be this part directly by the ownCloud version in the Version section. Then on click of the »Update« button, anything else can be loaded, be it an extra page or an additional template.

**Comment by te-online** [comment]
Okay, I feel that we travelled back in time and have a stand-alone updater page again? :smile: 
Am I missing the something?

However, I *know* that it always was a problem to use the app you are currently using to overwrite the app you are currently using... – you know what I'm talking about :wink: 

Still, I don't understand why we have to force the user to use a different interface only because they are updating the system. Therefore I like your point @jancborchardt 

> be it an extra page or an additional template

Let's use some _fancy_ technology like AJAX and maybe even an API to update your ownCloud? You could even have an app on your phone/toaster/fridge for updating... :rocket:

**Comment by jancborchardt** [comment]
> Okay, I feel that we travelled back in time and have a stand-alone updater page again? :smile:
> Am I missing something?

I’m confused here too to be honest. @DeepDiver1975 can you clarify what you exactly mean?

**Comment by DeepDiver1975** [comment]
From a tech pov we have to implement the updater independent of the code base which we are updating. As a result the integration will be minimal.

Using some http based api might be a solution to provide a smooth integration.
But to be honest: we are not yet there - the first concepts of updater web ui is about to be implemented this week.

**Comment by jancborchardt** [comment]
> the first concepts of updater web ui is about to be implemented this week.

Well, if we both talk about https://github.com/owncloud/updater/ (which @VicDeo and @te-online have been working on) then it’s definitely further along than first concepts to be implemented?

Also, what @te-online said above.

**Comment by DeepDiver1975** [comment]
> Well, if we both talk about https://github.com/owncloud/updater/ (which @VicDeo and @te-online have been working on) then it’s definitely further along than first concepts to be implemented?

The updater as we did ship it up to oc 8.2 is dead - oc 9 will come with a new updater based on different technical requirements. The main first goal is to provide a CLI based application followed by a web based approach.

**Comment by karlitschek** [comment]
yes.but we also need the web interface. even if it is simple

**Comment by PVince81** [comment]
@VicDeo @DeepDiver1975 what to do with this ? Is the current implementation adequate for this ticket's requirement or needs further work ?

**Comment by PVince81** [comment]
Closing as obsolete with the new updater which has a separate UI
