### ISSUE TITLE
PUT of large files via oc-client inefficient with standard chunksize in fast networks

### ISSUE THREAD

**Issue by kiu-ball** [owncloud/core#21696]
### Steps to reproduce
1. Take a large File (>1GB) in a fast network environment (>1GBit)
2. Upload it to your oC with oc-client using standard chunksize
3. Watch transferrate and server load
4. Set the chunksize to a higher value (export OWNCLOUD_CHUNK_SIZE=51248800 for example) and repeat step 2 and 3

### Expected behaviour
ownCloud desktop client performs well while uploading large files in a fast network. (~100MB/s)

### Actual behaviour
ownCloud desktop client performs bad while producing a high server load with standard parameters. (~10-20MB/s)
If you set the chunksize to a higher value the transfrerate raises while the server load drops. (~90-100MB/s)

### Server configuration
openSUSE 13.1 (Bottle) (x86_64)

**Web server:**
Apache/2.4.16

**Database:**
PostgreSQL 9.4.5

**PHP version:**
5.6.9

**ownCloud version:** (see ownCloud admin page)
8.2.2

**Updated from an older ownCloud or fresh install:**
Updated

**List of activated apps:**
Standard

**Are you using external storage, if yes which one:** local/smb/sftp/...
NFS

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP

### Client configuration

**Operating system:**
OS X 10.10.5

**Client Version:**
2.1.0 (build 2944)
```

**Comment by PVince81** [comment]
@dragotin

**Comment by MorrisJobke** [comment]
This looks clearly like a client enhancement.

I guess this is the stuff that @michaelstingl talked about yesterday. Right?

cc @butonic

**Comment by MorrisJobke** [comment]
cc @DeepDiver1975

**Comment by michaelstingl** [comment]
> I guess this is the stuff that @michaelstingl talked about yesterday. Right?

==> @felixboehm

**Comment by DeepDiver1975** [comment]
from my pov the client could learn the chunk size depending on the network quality.

client 'issue' -> closing

**Comment by kiu-ball** [comment]
Moved > https://github.com/owncloud/client/issues/4354
