### ISSUE TITLE
Row keeps highlighted after closing sidebar.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#21697]
## Steps to reproduce:

1. Select a row from files view.
2. Close the sidebar.
3. Select another row.

## Expected behaviour

Only second row is selected.

## Observed behaviour

Both rows are selected.

![screen shot 2016-01-13 at 18 19 40](https://cloud.githubusercontent.com/assets/9048796/12301854/7ee89292-ba22-11e5-965e-88ebd4cf98a1.png)

Master branch
{"installed":true,"maintenance":false,"version":"9.0.0.6","versionstring":"9.0 pre alpha","edition":""}

Seen in firefox and chrome.

**Comment by SergioBertolinSG** [comment]
cc @owncloud/designers

**Comment by jancborchardt** [comment]
Btw, this is not selection. It's only highlight. Selection is done via the checkboxes.

Nevertheless, this highlight should of course only be for the last file of which the sidebar has been opened for.

**Comment by jancborchardt** [comment]
cc @PVince81 @owncloud/javascript  for the logic.

**Comment by jancborchardt** [comment]
Can’t reproduce this anymore.
