### ISSUE TITLE
 'Enable User External Storage' looks like is available when it isn't.

### ISSUE THREAD

**Issue by davitol** [owncloud/core#21706]
### Steps to reproduce

1. In admin menu, check that 'Enable User External Storage' is NOT marked
2. Go to personal view

### Expected behaviour

An advice about 'User External Storage' is not available should be shown

### Actual behaviour

External storage section 'seems to be enable'. (Note: It is not enabled, so the behaviour is right). But it can be confused.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:  ownCloud Enterprise Edition 9.0 pre alpha (daily) Build:2016-01-12T04:19:25+00:00 373776b8d84bece3df4a06b157bbe41f51ef511d

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** yes; dropbox.
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

![screen shot 2016-01-14 at 09 46 45](https://cloud.githubusercontent.com/assets/10596560/12319999/42faabf6-baa6-11e5-94a1-30ef202f2ab4.png)

**Comment by PVince81** [comment]
Possible regression from 8.2.2 due to recent changes.

@Xenopathic @icewind1991

**Comment by davitol** [comment]
@PVince81 No, I tested it also in 8.2.2 and it looks in the same way

**Comment by Xenopathic** [comment]
Unable to reproduce, it's disabled in the admin settings and as expected the section is hidden in the personal settings.

@davitol Could you run the following MySQL command: `select * from oc_appconfig where configkey = 'allow_user_mounting' or configkey = 'user_mounting_backends';` and post what it outputs?

**Comment by davitol** [comment]
@Xenopathic as I said before, it seems to be enabled, but it isn't. The behaviour is right and the combobox cannot be spread.

about the SQL command, executing when Enable User External Storage is not marked I got the following output:

SELECT *
FROM appconfig
WHERE configkey = 'allow_user_mounting'
OR configkey = 'user_mounting_backends'
LIMIT 0 , 30

**Comment by Xenopathic** [comment]
> allow_user_mounting: yes

This value means that the 'Enable User External Storage' checkbox is marked, at least according to the backend. Thus the behaviour that the section is being displayed is in fact correct...

**Comment by davitol** [comment]
@Xenopathic Sorry, wrong scenario when I executed the SQL query, my fault.

Now I'll show you in the following .gif file the bug, and the execution of the SQL sentence:

![externalvis](https://cloud.githubusercontent.com/assets/10596560/12325111/2ebf4e0e-bac8-11e5-83f6-e62e9a4daba2.gif)

![screen shot 2016-01-14 at 14 00 42](https://cloud.githubusercontent.com/assets/10596560/12325115/3712ac0e-bac8-11e5-97af-8b1447c21787.png)

**Comment by Xenopathic** [comment]
Ah right, so an empty value is incorrectly detected. I'll have a look.
