### ISSUE TITLE
[Edge] Downloading files or folders keeps spinner spinning forever. 

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#21707]
## Steps to reproduce:

Using Microsoft's Edge browser do:

1. Download a file or a folder.

## Expected behaviour

File or folder is downloaded and spinner appears very little or nothing at all.

## Observed behaviour

File or folder is downloaded but spinner keeps spinning forever. It ends only when refreshing the page.

![screen shot 2016-01-14 at 09 52 59](https://cloud.githubusercontent.com/assets/9048796/12320052/a6f8ed2a-baa6-11e5-8c46-58ea6b3d8f5a.png)

Master branch
{"installed":true,"maintenance":false,"version":"9.0.0.6","versionstring":"9.0 pre alpha","edition":""}

**Comment by PVince81** [comment]
Looks like the download token cookie hack doesn't work in edge ? :frowning: 

CC @MorrisJobke

**Comment by PVince81** [comment]
I can have a look later

**Comment by Dianafg76** [comment]
I tested this issue and now is working OK
Server v {"installed":true,"maintenance":false,"version":"9.0.0.10","versionstring":"9.0 pre alpha","edition":"Enterprise"}
