### ISSUE TITLE
[CentOS] Images are downloaded instead of previewed.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#21709]
### Steps to reproduce

1. Upload some images.
2. Open it in the files view.

### Expected behaviour
A preview is shown.

### Actual behaviour
File is downloaded.

### Server configuration
**Operating system**:
CentOS 6.6

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Master branch
{"installed":true,"maintenance":false,"version":"9.0.0.6","versionstring":"9.0 pre alpha","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
```
Enabled:
  - activity: 2.2.1
  - admin_audit: 0.7
  - dav: 0.1.3
  - enterprise_key: 0.1.0
  - files: 1.4.1
  - files_pdfviewer: 0.8
  - files_sharing: 0.8.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoviewer: 0.1.3
  - firewall: 2.3.0
  - firstrunwizard: 1.1
  - gallery: 14.3.0
  - notifications: 0.2.2
  - provisioning_api: 0.4.0
  - templateeditor: 0.1
  - windows_network_drive: 0.1.1
Disabled:
  - encryption
  - external
  - federation
  - files_antivirus
  - files_drop
  - files_external
  - files_ldap_home
  - objectstore
  - password_policy
  - sharepoint
  - user_external
  - user_ldap
  - user_shibboleth
```

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
Probably not related, but this is the only logs that appears when clicking on an image.
```
{"reqId":"QNNlLan1iOeMUaf7dED7","remoteAddr":"82.159.139.58","app":"PHP","message":"You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead. at \/var\/www\/html\/owncloud\/3rdparty\/patchwork\/utf8\/src\/Patchwork\/Utf8\/Bootup\/intl.php#18","level":3,"time":"2016-01-14T09:42:33+00:00"}
```

### Client configuration

**browser**
Chrome

**Comment by PVince81** [comment]
Strange. The preview usually comes from the gallery app.
Can you use the browser's DOM inspector on the image's row in the file list, and check the "data-mime" attribute ? Maybe the mime type is wrong for some reason...

**Comment by SergioBertolinSG** [comment]
I see this:

Resource interpreted as Document but transferred with MIME type image/jpeg: "HOST/remote.php/webdav/IMAGE.JPG".

**Comment by PVince81** [comment]
Hmmm, can the downloaded image be opened or is it corrupt ?

**Comment by SergioBertolinSG** [comment]
It can be opened without problems.

**Comment by vanquan223** [comment]
I also failed to upload pictures from the same android app, android app preview ok, but when viewing them on the web, there is no thumbnails and images are downloaded instead of preview.
Sorry for bad english :)

![web](https://cloud.githubusercontent.com/assets/16588123/13342508/ccbd197e-dc74-11e5-9630-80caf4bf0a86.PNG)
![app android](https://cloud.githubusercontent.com/assets/16588123/13342509/ccbe79b8-dc74-11e5-805b-3b7fcbb9ece5.png)

**Comment by vanquan223** [comment]
https://github.com/owncloud/core/issues/14148

removing the method "getMimeType" from the Swift class
OK

**Comment by PVince81** [comment]
@SergioBertolinSG is this still happening in v9.0.3RC1 or v9.1.0beta2 ?

**Comment by SergioBertolinSG** [comment]
Works fine in master.
