### ISSUE TITLE
[Edge] Download files from a public shared folder doesn't work.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#21713]
### Steps to reproduce

1. Share by link a folder giving all permissions.

Using Microsoft's Edge anonymously do:

2. Open public link.
3. Download one of the files inside the folder.

### Expected behaviour
File is downloaded.

### Actual behaviour
Spinner spins but file never is downloaded.

### Server configuration
**Operating system**:
CentOS 6.6

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Master branch
{"installed":true,"maintenance":false,"version":"9.0.0.6","versionstring":"9.0 pre alpha","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
```
Enabled:
  - activity: 2.2.1
  - admin_audit: 0.7
  - dav: 0.1.3
  - enterprise_key: 0.1.0
  - files: 1.4.1
  - files_pdfviewer: 0.8
  - files_sharing: 0.8.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoviewer: 0.1.3
  - firewall: 2.3.0
  - firstrunwizard: 1.1
  - gallery: 14.3.0
  - notifications: 0.2.2
  - provisioning_api: 0.4.0
  - templateeditor: 0.1
  - windows_network_drive: 0.1.1
Disabled:
  - encryption
  - external
  - federation
  - files_antivirus
  - files_drop
  - files_external
  - files_ldap_home
  - objectstore
  - password_policy
  - sharepoint
  - user_external
  - user_ldap
  - user_shibboleth
```

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

No relevant logs found.

### Client configuration

**browser**
Edge

**Comment by rullzer** [comment]
@SergioBertolinSG there was a bug for public link downloads where the server was hosten on a non default port (https://github.com/owncloud/core/pull/22095). Could you test again (as I assume you are testing on the docker setups).

**Comment by SergioBertolinSG** [comment]
Works in current master.
