### ISSUE TITLE
8.1 to 8.2.2 upgrade never ending

### ISSUE THREAD

**Issue by ipm-uma** [owncloud/core#21712]
I've follow the steps in the docs to upgrade and when I try to upgrade it show the error:

```
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 65552 bytes) in /var/www/html/owncloud/lib/private/log.php on line 214
```
I have increased the memory limit to 1024MB and the upgrade doesn't fail now but it's running during 24h without any changes:

```
sudo -u apache php occ upgrade
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug - current level: 'Debug'
Turned on maintenance mode
Updating database schema
Updated database
```

What's wrong? I'm still waiting the end of the upgrade.

CentOS 6.7
PHP 5.4.37

**Comment by jvillafanez** [comment]
Please follow the issue template (https://raw.githubusercontent.com/owncloud/core/master/issue_template.md). Be sure you add the ownCloud version you're updating from (I'm not sure if it's 8.1.0, 8.1.1, or any other 8.1.x), and also the list of enabled apps specially if you use any other app that doesn't come with the "standard" ownCloud package.

In addition, include whether you're updating using tarball or using linux packages.

I have tests passing for CentOS 6.6 and php 5.4.16 (from the scl repository) using tarballs for 8.1.x to the stable8_2 daily tarball (I've pass through 8.2.2). Those tests use the standard apps from the tarball without any other app. The point is that there might an external app that is causing the failure.

**Comment by ipm-uma** [comment]
### Steps to reproduce
1. ```rpm --import https://download.owncloud.org/download/repositories/stable/CentOS_6/repodata/repomd.xml.key```
2. ```wget http://download.owncloud.org/download/repositories/stable/CentOS_6/ce:stable.repo -O /etc/yum.repos.d/ce:stable.repo```
3. ```yum clean expire-cache```
4. ```yum update owncloud```
5. ```sudo -u apache php occ upgrade --skip-migration-test```

### Expected behaviour
Upgrade from owncloud 8.1.3-13.1 to 8.2.2-1.1.

### Actual behaviour
The upgrading proccess doesn't finish.

### Server configuration
**Operating system**:
CentOS 6.7 

**Web server:**
Apache/2.2.15

**Database:**
PostgreSQL 9.4

**PHP version:**
PHP 5.4.37

**ownCloud version:**
8.2.2.

**Updated from an older ownCloud or fresh install:**
8.1.3.

**List of activated apps:**

Enabled:
  - activity: 2.1.3
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - user_ldap: 0.7.1

Disabled:
  - calendar
  - contacts
  - documents
  - encryption
  - external
  - files_external
  - notifications
  - user_external
  - user_servervars
  - user_shibboleth

**The content of config/config.php:**
```
{
    "system": {
        "instanceid": "oc6c171d2d2c",
        "datadirectory": "\/var\/www\/html\/owncloud\/data",
        "dbtype": "pgsql",
        "version": "8.1.3.0",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "theme": "",
        "installed": true,
        "maintenance": true,
        "trusted_domains": [
            "nimbo.sci.uma.es"
        ],
        "overwrite.cli.url": "https:\/\/nimbo.sci.uma.es\/owncloud",
        "logtimezone": "UTC",
        "loglevel": 0,
        "ldapIgnoreNamingRules": false,
        "mail_smtpmode": "smtp",
        "mail_from_address": "admin",
        "mail_domain": "uma.es",
        "mail_smtphost": "correo.uma.es",
        "mail_smtpport": "25",
        "trashbin_retention_obligation": "auto"
    }
}
```
**Are you using external storage, if yes which one:** None

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** OpenLDAP

I can't access now.

### Client configuration
**Browser:** None
**Operating system:** None

### Logs
#### Web server error log
No error in the server log.

#### ownCloud log (data/owncloud.log)
```
{"reqId":"On1H1qBHBTwHiLu6VwRw","remoteAddr":"","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-01-14T13:49:22+00:00","method":"--","url":"--"}
```

#### Browser log
None.

**Comment by jvillafanez** [comment]
The only thing I can figure out about the issue is a problem with ldap. I don't have tests with ldap :disappointed: 

@blizzz any help you can provide here? Is it possible that the ldap app get stuck at some point during the upgrade? Any difference between the ldap versions that could cause this issue?

**Comment by ipm-uma** [comment]
The upgrade are finished! It has taken about 30 hours! An installation without users!

Thanks for all.
Regards.
