### ISSUE TITLE
Enforce Password Share Link image issue

### ISSUE THREAD

**Issue by Woodwergs** [owncloud/core#21726]
Owncloud 8.2.2 (Fresh Install)
Steps to reproduce

Go to the Server Client with Admin
Go to the Sharing option
Select the option "Enforce password protection" 
Go to Files
Share a folder
Click Share link
Un-click Share link 
Checkbox changes to loading-small.gif and stays that icon until the page is refreshed
![image](https://cloud.githubusercontent.com/assets/16705830/12329168/e02cfe9e-bad6-11e5-9635-606ef87be1b2.png)

**Comment by PVince81** [comment]
@davitol are you able to reproduce this ?

**Comment by davitol** [comment]
@PVince81 Yes, tested in Firefox and Chrome for MacOS and it happens. No logs are generated in owncloud.log and in the browser console

**Comment by rullzer** [comment]
PR  in #22266
