### ISSUE TITLE
ownCloud update problem (via UI)

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#21722]
Server: Ubuntu 14.04, PHP 5.5.9, MySQL, Redis
Browser: W7/Opera

One of my productive instances running 8.2.0 reported that there is an update to 8.2.2 available.
![image](https://cloud.githubusercontent.com/assets/3321281/12325798/01de3274-bacd-11e5-8601-ed5311c2c17f.png)

I went to the admin page to the bottom and tried to update (stable).
I got the following response:
![image](https://cloud.githubusercontent.com/assets/3321281/12325801/08352772-bacd-11e5-9fbf-3dbda04f06bd.png)

The following Files and Directories  (a loooong list) has been reported:

**The web directory name for owncloud**
```
/var/www/<directory>
```

**Directories**
```
3rdparty
core
lib
l10n
settings
ocs
ocs-provider
resources
```

**Files in Root**
```
.htaccess
.mailmap
.tag
.user.ini
AUTHORS
COPYING-AGPL
console.php
cron.php
db_structure.xml
index.html
index.php
indie.json
occ
ocs-provider
ocs-provider/index.php
ocs-provider/provider.php
public.php
remote.php
robots.txt
status.php
version.php
```

This is the complete instance!

If I compare the requirement to set proper access rights according the documentation (https://github.com/owncloud/documentation/blob/master/admin_manual/installation/installation_wizard.rst#setting-strong-directory-permissions) and the required rights as listed above to do the update, I see a big difference. Which is also a security issue because some files need ``root:[HTTP group]`` and not ``[HTTP group]:[HTTP group]``

Finally it ended after a couple of tries (no more access rights complaints) with:
```
Update fehlgeschlagen.Unable to move /<directory>/_oc-upgrade/8.2.2.2/core/resources to /<directory>/resources
```
Following updater backups have been created so far:
![image](https://cloud.githubusercontent.com/assets/3321281/12326456/37323c82-bad1-11e5-9084-a023207dc6ee.png)

**owncloud.log:**
```
Error	updater	Unable to move /<directory>/_oc-upgrade/8.2.2.2/core/resources to /<directory>/resources	2016-01-14T15:03:43+01:00
Error	updater	Something went wrong for core. Rolling back.	2016-01-14T15:03:17+01:00
Error	PHP	rename(/<directory>/_oc-upgrade/8.2.2.2/core/resources,/<directory>/resources): File exists at <directory>/apps/updater/lib/helper.php#52	
```
``<directory>`` ... owncloud instance

How to deal with that?

**Comment by RealRancor** [comment]
@mmattel You need to revert the strong permissions as described in the documentation before being able to using the updater app:

https://doc.owncloud.org/server/8.2/admin_manual/maintenance/update.html#setting-strong-permissions

The ``Unable to move /<directory>/_oc-upgrade/8.2.2.2/core/resources to /<directory>/resources`` was a bug in the updater previous to 8.2.2: https://github.com/owncloud/updater/issues/189

**Comment by nickvergessen** [comment]
Closing as duplicate of https://github.com/owncloud/updater/issues/189
