### ISSUE TITLE
[Files_external] Editing files with sidebar visible creates logs in owncloud.log file

### ISSUE THREAD

**Issue by davitol** [owncloud/core#21733]
### Steps to reproduce
1. As admin user configure an External Storage MountPoint (e.g. DropBox)
2. In files view, Browse into the mountpoint folder
3. With the sidebar visible, edit a text file.
### Expected behaviour

The text file should be edited, the preview image updated and no logs should be written in owncloud.log file.
### Actual behaviour

The text file should be edited, the preview image updated but the following logs are written in owncloud.log file.

```
{"reqId":"YySPc\/O5aFEisxViRKc7","remoteAddr":"82.159.139.58","app":"PHP","message":"fopen(\/opt\/owncloud\/data\/admin\/thumbnails\/537\/35-35.png): failed to open stream: No such file or directory at \/opt\/owncloud\/lib\/private\/files\/storage\/local.php#247","level":3,"time":"2016-01-14T17:20:02+00:00"}
```

Note: This log is only written editing files in a files_external mountpoint. Could not reproduce it in local folders.
The same logs are created when we restore one file from the sidebar.
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:  ownCloud Enterprise Edition 9.0 pre alpha (daily) Build:2016-01-12T04:19:25+00:00 373776b8d84bece3df4a06b157bbe41f51ef511d

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** yes; dropbox.
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Firefox

![screen shot 2016-01-14 at 18 20 47](https://cloud.githubusercontent.com/assets/10596560/12332062/c1c52e52-baec-11e5-8ece-64fcd1a0414e.png)

**Comment by PVince81** [comment]
@tomneedham can you have a look ?

**Comment by PVince81** [comment]
Please reopen if issue persists with 10.0.4
