### ISSUE TITLE
[Files external] It is not possible to delete several files at the same time

### ISSUE THREAD

**Issue by davitol** [owncloud/core#21731]
### Steps to reproduce

1. As admin user configure an External Storage MountPoint (e.g. DropBox)
2. In files view, Browse into the mountpoint folder
3. Select more than one file

### Expected behaviour

Delete button should be enabled and it should be possible to delete several files in a row.

### Actual behaviour

There is no chance to delete several files located in an external mountpoint at the same time

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:  ownCloud Enterprise Edition 9.0 pre alpha (daily) Build:2016-01-12T04:19:25+00:00 373776b8d84bece3df4a06b157bbe41f51ef511d

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** yes; dropbox.
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

Local files:

![screen shot 2016-01-14 at 17 55 19](https://cloud.githubusercontent.com/assets/10596560/12331128/8542047c-bae8-11e5-9b9f-ba4fcdc0dbed.png)

External storage mountpoint files:

![screen shot 2016-01-14 at 17 54 52](https://cloud.githubusercontent.com/assets/10596560/12331141/90c365b6-bae8-11e5-9eae-8bcd258a3247.png)

**Comment by Xenopathic** [comment]
Unable to reproduce on current master with SFTP storage (mounted through Personal settings)

**Comment by davitol** [comment]
Just reproduce it again in ownCloud 9.0 pre alpha (daily) Build:2016-01-15T05:01:28+00:00 b48ddc94a9caa1c482a7260a298f5418b6028793.
Browser Firefox for OSX and DropBox as External Storage

**Comment by Xenopathic** [comment]
Are there any browser logs?

**Comment by davitol** [comment]
There are no browser logs...

**Comment by PVince81** [comment]
Is this a system-wide mount or personal mount ?

Possibly duplicate of https://github.com/owncloud/core/issues/16533

**Comment by davitol** [comment]
@PVince81 system-wide mount. So yes, it is dupe of #16533. Let's close it
