### ISSUE TITLE
Problems with syncing a file

### ISSUE THREAD

**Issue by notaduck** [owncloud/core#21734]
I have a file called berlin 041.jpg and everytime my user tries to upload the file from his macbook then he get's the message connection closed and aren't able to sync any files with the owncloud server? but as soon as the file is remove from the owncloud folder then everything works just fine?

-u www-data php occ status
 > - installed: true
  >- version: 8.2.2.2
  >- versionstring: 8.2.2
  >- edition: 

 apache2 -v
>Server version: Apache/2.4.7 (Ubuntu)

php5 -v
>PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46) 
>Copyright (c) 1997-2014 The PHP Group
>Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
>    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

```
 Fatal 	webdav 	Exception: {"Message":"HTTP\/1.1 400 expected filesize 1222303 got 179547","Exception":"Sabre\\DAV\\Exception\\BadRequest","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/directory.php(115): OC\\Connector\\Sabre\\File->put(Resource id #29)\n#1 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1053): OC\\Connector\\Sabre\\Directory->createFile('Berlin 041.jpg', Resource id #29)\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(513): Sabre\\DAV\\Server->createFile('Berlin 041.jpg', Resource id #29, NULL)\n#3 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#5 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#6 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#7 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(56): Sabre\\DAV\\Server->exec()\n#8 \/var\/www\/owncloud\/remote.php(137): require_once('\/var\/www\/ownclo...')\n#9 {main}","File":"\/var\/www\/owncloud\/lib\/private\/connector\/sabre\/file.php","Line":139} 
```

**Comment by karlitschek** [comment]
I guess there is something wrong in your setup. Can you please post your question at one of the support options at owncloud.org/support. Thanks

**Comment by RealRancor** [comment]
@notaduck See also https://forum.owncloud.org/viewtopic.php?f=17&t=32517
