### ISSUE TITLE
[Chrome] Thumbnails of versions are not shown

### ISSUE THREAD

**Issue by davitol** [owncloud/core#21738]
### Steps to reproduce

1. As admin user configure a mountpoint (e.g DropBox, S3...)
2. Share a file from the external storage with user1
3. Using Chrome as browser, edit file with user1 and go to Versions menu

### Expected behaviour

The preview thumbnails of the versions should be visible

### Actual behaviour

The preview thumbnails of the versions are not shown. Error 404.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 9.0 pre alpha (daily) Build:2016-01-14T04:16:39+00:00 d0a690fde46d1bba886e0a94a5e59c40f1e5c3b0

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** yes; dropbox.
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome Version 47.0.2526.111 (64-bit) for Mac OSX

![screen shot 2016-01-15 at 11 00 15](https://cloud.githubusercontent.com/assets/10596560/12350625/6fa0b204-bb78-11e5-8a75-db039118b02c.png)

**Comment by PVince81** [comment]
Regression ? It used to work.

**Comment by PVince81** [comment]
So only with external storages, local storage works ?

**Comment by davitol** [comment]
It also fails in 8.2.2. oC version (just tested) and it only happens with external storages

**Comment by PVince81** [comment]
Works for me in 9.1.0beta2
