### ISSUE TITLE
Wrong storage availability check when admin has no access

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#21749]
### Steps

1. Enable ext storage
1. Create a user "user1"
1. Setup a system-wide ext storage mount (I used "/sftp")
1. Apply the mount for "user1" but not for admin/root
1. Go to admin's "All files" view

### Expected result
"/sftp" does NOT appear for admin user.

### Actual result
"/sftp" DOES appear for admin user, and the availability check says that the mount point is not connected.

### Versions
ownCloud 9.0 pre-alpha git master fcec704174a384f93214a1f2b83bed385e763ff6

Technically a regression because in OC <= 8.2 we did not show that mount.

Please have a look @jmaciasportela @Xenopathic @icewind1991

**Comment by icewind1991** [comment]
I remember fixing this...

**Comment by icewind1991** [comment]
https://github.com/owncloud/core/pull/21467

**Comment by PVince81** [comment]
Weird. I did pull master, still happens. Maybe it's another twisted code path that leads to this ?
Note that I first had "all" as applicable, then I created the user, and then added it into the applicable field. So technically the storage was available for admin for a short time.

Shouldn't matter though...

**Comment by Xenopathic** [comment]
```
MariaDB [owncloud]> select * from oc_external_applicable;
+---------------+----------+------+------------+
| applicable_id | mount_id | type | value      |
+---------------+----------+------+------------+
|             2 |        2 |    1 | NULL       |
|             4 |        3 |    1 | NULL       |
|             6 |        5 |    1 | NULL       |
|            12 |        5 |    3 | BlueDragon |
|             1 |        1 |    3 | root       |
+---------------+----------+------+------------+
5 rows in set (0.00 sec)

MariaDB [owncloud]> delete from oc_external_applicable where mount_id = 5 and type = 1 and value = null;
Query OK, 0 rows affected (0.00 sec)
```

Umm, wat. :boom: 

So what's happening is, when you change an external storage from globally applicable to some user/group, that SQL query (or similar) is run to remove the 'null' applicable line. But for some reason it doesn't work, so the DB config reader assumes it's applicable to all. This fails when the storage is actually used, since it has non-empty applicable users/groups.

**Comment by Xenopathic** [comment]
AH, looks like SQL needs `is null` rather than `= null`. But we pass in the `null` as a named parameter... Although, it looks like we don't actually need to check if it's null or not, since with a `type = 1` the value will always be null.

**Comment by PVince81** [comment]
CC @davitol

**Comment by PVince81** [comment]
Tested, works :+1:

**Comment by davitol** [comment]
:+1: WFM
