### ISSUE TITLE
Shibboleth integration only for Enterprise Edition?

### ISSUE THREAD

**Issue by ipm-uma** [owncloud/core#21740]
I am an employee of University of Malaga IT (Spain) with Owncloud 8.2.2 server installed.

We want to federate Owncloud using Shibboleth (really auth_mellon) but the official app is only for Enterprise Edition.

Do we have any alternative?

**Comment by jospoortvliet** [comment]
Other than buying the Enterprise Edition? I suggest you get in contact with ownCloud sales for the education discount, or use another solution. You could also write code yourself but I would guess that buying the enterprise edition would be cheaper AND you would be supporting ownCloud, giving the warm and fuzzy feeling of doing the right thing!
