### ISSUE TITLE
can't select view-input-folder

### ISSUE THREAD

**Issue by Julian1998** [owncloud/core#21756]
<h2>Steps to reproduce</h2>

Select new folder and try to select a specific part of the content
<h2>Expected behaviour</h2>

Specific part is going to be selected

<h2>Actual behaviour</h2>

You can select all or nothing

<h3>Server configuration</h3>

Operating system: debian 8

Web server: apache 2.4.10

Database: sqlite

PHP version: 5.6.7

**ownCloud version: ownCloud 9.0 pre alpha (git)

Updated from an older ownCloud or fresh install: Fresh install

Are you using external storage, if yes which one: no
Are you using encryption: no
Are you using an external user-backend, if yes which one: no

Client configuration

Browser: 47.0.2526.111 m (64-bit) for windows

**Comment by nickvergessen** [comment]
Can you try to explain your steps a bit more in details? Or maybe support them with some screenshots?
It's a bit hard to understand what you are trying to do.

**Comment by blizzz** [comment]
Closing because of missing info.
