### ISSUE TITLE
[CalDAV/CardDAV] birthday calendar

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#21750]
Question to ask:
- is the birthday calendar a server side feature?
- or is this something we want to build into the client (calendar-rework app)?

Seems like there are devices/apps out there which already extract birthday information from synced contacts. This is basically quite logic if you have all contacts at hand.

@georgehrke @Henni @irgendwie @raghunayyar @jancborchardt @karlitschek

**Comment by DeepDiver1975** [comment]
Kind of 9.0 topic because we have the birthday calendar server side so we need an answer for the migration

**Comment by georgehrke** [comment]
> Seems like there are devices/apps out there which already extract birthday information from synced contacts. This is basically quite logic if you have all contacts at hand.

The only client I know of is the calendar app for iOS and OS X. I'm not 100% sure, but I don't think Lightning, the Gnome calendar and KDE's Kalendar provide this feature. On iOS and OS X you can simply hide ownCloud's birthday calendar if you don't want to see it.

**Comment by DeepDiver1975** [comment]
> On iOS and OS X you can simply hide ownCloud's birthday calendar if you don't want to see it.

for sure - and this was my answer in the past to feature requests for a config switch to disable the birthday calendar :wink: 

On android there are apps like this: https://play.google.com/store/apps/details?id=org.birthdayadapter.free&hl=en

No idea about Windows Phone and Desktop @icewind1991 @jakobsack 

Gnome and KDE integration is a point to research into.

**Comment by jakobsack** [comment]
On Windows Phone birthday calendars are server side. Windows phone doesn't do this. It's the same for the desktop.

**Comment by DeepDiver1975** [comment]
THX @jakobsack

**Comment by jakobsack** [comment]
KDE PIM has its own birthday calendar but it is very easy to choose the shown calendars.

**Comment by PVince81** [comment]
We're past feature freeze, 9.1 ?

**Comment by DeepDiver1975** [comment]
> We're past feature freeze, 9.1 ?

Not having the birthday calendar could be seen as feature regression

@karlitschek opinion? Freeze exception? It would take me one day to finish the open PR #22198

**Comment by karlitschek** [comment]
This is technically a feature regression so fixing this after freeze is fine. The real question is if it is doable in the required quality. What do you guys think?

**Comment by georgehrke** [comment]
> The real question is if it is doable in the required quality.

We should do it how it's used to be. Just display the name and the year of birth in brackets.
Maybe add a birthday cake in the front. There is a unicode for that one.

Displaying the actual age is really difficult via CalDAV, because we can't use repeating events and would have to create one event per birthday.

**Comment by DeepDiver1975** [comment]
> We should do it how it's used to be. Just display the name and the year of birth in brackets.

this is already implemented in #22198 - what is missing are
- [ ] unit tests
- [ ] daily cron job to sync contacts and the birthday calendar
- [ ] migration step to generate the birthday_calendar

Just in case one asks:
Why don't we calculate the birthday information from all contacts on the fly when a request comes in? (This is how it was done in the past)

This will result in a hight load on the server because ALL contacts from all addressbooks need to be loaded and all VCards have to be parsed.

The new approach will store the birthday information in the db right away - no computation on the server.
The data id kept in sync using an event based mechanism - as soon as a contacts is changed the birthday information is updated.

The cron job is used as a safety net.
