### ISSUE TITLE
Federation app uses nonexistent other category

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#21758]
https://github.com/owncloud/core/blob/59e9b93be646c46a47ac780b60cc1f0b9cf6e258/apps/federation/appinfo/info.xml#L10

"other" was removed from the appstore a few months ago https://github.com/owncloud/appstore-issues/issues/26#issuecomment-139913987

**Comment by rullzer** [comment]
@schiesbn

**Comment by PVince81** [comment]
Is this bad ? (if yes, please raise severity)

**Comment by schiesbn** [comment]
I don't think it is crucial, most apps don't have it at all. Of course it is easy to change, so if someone has a good idea for the correct category name? I looked at the user back-end, but I would say that they are in a similiar category but they don't have a category at all.

**Comment by PVince81** [comment]
Closing as this app won't appear on app store or market anyway
