### ISSUE TITLE
Access to all calendar

### ISSUE THREAD

**Issue by pacomedina** [owncloud/core#21767]
Hello,

I've just noticed I can access to all calendar from one account using URL : /remote.php/caldav/principals/username/

I can see everyone calendar on the server if I replace "username" in the URL by the name of an other user.

Exemple : 

user1 has calendar1
user2 has calendar2

I can see calendar2 using url /remote.php/caldav/principals/user2 and connecting with user1 credentials.

Is this an issue on my server only ?
I'm connecting with the OSX calendar client.

Regards,
Paco Medina

**Comment by nickvergessen** [comment]
@DeepDiver1975 sounds like a real issue to me?

**Comment by DeepDiver1975** [comment]
> /remote.php/caldav/principals/username/

this is th 'old' calendar ap - this issue should be reported in https://github.com/owncloud/calendar
