### ISSUE TITLE
after upgrade from 8.0.2 to 8.1.0 segmentation fault

### ISSUE THREAD

**Issue by waspinator** [owncloud/core#21764]
### Steps to reproduce
1. upgrade from owncloud 8.0.2 to 8.1.0 using the manual method
2.
3.

### Expected behaviour
Owncloud should work as before

### Actual behaviour
I get segmentation fault in `/log/apache2/error.log`
    `[Sun Jan 17 13:03:23 2016] [notice] child pid 7576 exit signal Segmentation fault (11)`

and in Firefox I get a `The connection was reset` error while in chrome I get `No data received` error

### Server configuration
**Operating system**:
Debian GNU/Linux 7.9 (wheezy)

**Web server:**
Apache/2.2.22 (Debian)

**Database:**
5.5.46, for debian-linux-gnu (x86_64) using readline 6.2

**PHP version:**
PHP 5.4.4-14+deb7u12 (cli) (built: Jun 30 2014 13:15:11)

**ownCloud version:** (see ownCloud admin page)
'version' => '8.1.0.8' 

**Updated from an older ownCloud or fresh install:**
updated from 8.0.2

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```
Enabled:
 - activity: 2.0.1
 - files: 1.1.9
 - files_external: 0.2.3
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - updater: 0.6
 - user_ldap: 0.6.1

Disabled:
 - documents
 - encryption
 - external
 - files_locking
 - files_versions
 - provisioning_api
 - templateeditor
 - user_external
 - user_webdavauth

**The content of config/config.php:**
	<?php
	$CONFIG = array (
	  'instanceid' => '**********',
	  'passwordsalt' => '**************',
	  'datadirectory' => '/owncloud_data/data',
	  'dbtype' => 'mysql',
	  'version' => '8.1.0.8',
	  'dbname' => 'owncloud',
	  'dbhost' => 'localhost',
	  'dbtableprefix' => '',
	  'dbuser' => 'owncloud',
	  'dbpassword' => '**********',
	  'installed' => true,
	  'ldapIgnoreNamingRules' => false,
	  'theme' => '',
	  'maintenance' => false,
	  'trusted_domains' =>
	  array (
	    0 => '10.34.1.5',
	    1 => 'owncloud.******.com',
	  ),
	  'loglevel' => 2,
	  'forcessl' => true,
	  'secret' => '***********',
	);

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
Firefox/Chrome
**Operating system:**
OSX 10.11, Ubuntu 14.04, Windows 8.1
#### Web server error log
```
`[Sun Jan 17 13:03:23 2016] [notice] child pid 7576 exit signal Segmentation fault (11)`

Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by RealRancor** [comment]
@waspinator Why not going directly to 8.1.5? 8.1.0 is outdated and contains quite a few bugs.

**Comment by waspinator** [comment]
I tried upgrading to 8.1.5 with the same result. as well as 8.2.2.

**Comment by waspinator** [comment]
After upgrading to 8.2.2 and then migrating from Debian 7.9 to 8 ownCloud started working again. I'm thinking maybe 8.1+ isn't compatible with Debian 7.x since it uses Apache 2.2 instead of 2.4. But maybe that's just a coincidence.

**Comment by RealRancor** [comment]
You're probably just hitting a bug in PHP which gets triggered by oC.
