### ISSUE TITLE
On mobile broswers, cannot tap on dots in sidebar

### ISSUE THREAD

**Issue by valmar** [owncloud/core#21777]
On mobile browers (Firefox or Chrome on Android, browser in Ubuntu Touch), if I click on an entry in the sidebar, and then on the dots to open the popup menu, the popup menu does not come up and instead the sidebar closes. This makes impossible to perform a number of tasks using the web interface from mobile (for example, in the news app, one cannot remove feeds, mark all as read, etc.)

Thank you very much for looking into this. Let me know if you need more information...

**Comment by karlitschek** [comment]
@jancborchardt

**Comment by jancborchardt** [comment]
cc @BernhardPosselt because the News app is the only app atm which uses the dots in the sidebar. Do you have any insight on how to fix this? It’s a JS issue so I guess we need to do some stopPropagation or similar?

cc @owncloud/designers

**Comment by BernhardPosselt** [comment]
I think the issue is that the dots are above the link so a click on the dots should not toggle a link on the link. Probably as easy as preventing the event if it originated from the dots

**Comment by jancborchardt** [comment]
@BernhardPosselt basically what I said with the stopPropagation, right? Could you prepare a pull request for that?

**Comment by BernhardPosselt** [comment]
Not enough time, sorry

**Comment by BernhardPosselt** [comment]
As in: lots of stuff to do at work (deadline) and my remaining time is spent on maintaining the News app and trying to get in featuers (which is very hard because of lacking time)

**Comment by valmar** [comment]
Can I help with something? I am a scientific software developer, but I don't know php, only python and C++...

**Comment by jancborchardt** [comment]
@valmar there’s definitely some Javascript involved here. So calling @owncloud/javascript for help.

**Comment by PVince81** [comment]
@valmar is the news app the only one affected ? Unless there is any CSS in core that would interfere with this, this is a bug in the news app: https://github.com/owncloud/news

**Comment by valmar** [comment]
I think it is. I haven't seen the problem in any other app. However, as someone pointed out above, it is possible that the news up is the only one using the dots in the sidebar.

I originally reported the bug in the news app, but the developer suggested that I open the bug in core...

https://github.com/owncloud/news/issues/912

PS: Another problem that I have in the mobile browser is that I cannot scroll down throught the Contacts in the Contacts application, but I guess this is unrelated

**Comment by PVince81** [comment]
> PS: Another problem that I have in the mobile browser is that I cannot scroll down throught the Contacts in the Contacts application, but I guess this is unrelated

Please raise these in the calendar and contact repositories.
