### ISSUE TITLE
Internet Download Manager (IDM) Does not support for download public file?

### ISSUE THREAD

**Issue by raisulmac** [owncloud/core#21776]
Hello,

When, someone download a zip file via public share link. Then, Internet Download Manager does not support. Why? I saw that auto browser download option open for download the file.
But,
I want, when click Download Button. Then, Auto download manager open for download the file.
Someone can help me for fix the problem?
I am waiting for valuable response.

Best Regards,
Raisul

**Comment by DeepDiver1975** [comment]
Thew zip files are created on the fly - resume is not possible as a result.

Besides that I cannot imagine a reason why IDM should not work with public sharing.

further debugging and analysis is welcome

**Comment by raisulmac** [comment]
Actually, I am using large file on my owncloud server.
So, most people like, Internet download manager
for download big file.
So, I want people download the file via internet download manage
Also, pause and resume via download manager.

**Comment by DeepDiver1975** [comment]
Please test the upcoming ownCloud 9.0 - we will support http range requests in public share page which is a necessity for download resume. Please let me know if this works. THX

**Comment by PVince81** [comment]
Reminded me to raise this: https://github.com/owncloud/core/issues/21787

**Comment by PVince81** [comment]
range request was implemented in 9.0 for public link shares (files). Please try again.
