### ISSUE TITLE
contacts can not be edited in 8.2.2

### ISSUE THREAD

**Issue by zoff99** [owncloud/core#21783]
this bug was finally fixed in the latest 8.1 and now in 8.2.2 the exact same bug is here again.

![oc_822_contacts_bug](https://cloud.githubusercontent.com/assets/6833516/12401156/f47f148a-be24-11e5-9965-ee6914d8acbf.png)
this "rotating-thingy" does not dissapear, and then the contacts can be selected but the edit form fields do not show.

**Comment by zoff99** [comment]
i am using a slower shared host. so maybe some vital part does not load? hope it can be fixed like in 8.1

**Comment by RealRancor** [comment]
@zoff99 The contacts app issue tracker is located here:

https://github.com/owncloud/contacts/issues

Please re-open there by using the issue template provided here: https://github.com/owncloud/contacts/blob/master/CONTRIBUTING.md#short-version

(That one is linked in the yellow boxes at each repository while you're creating a new issue).
