### ISSUE TITLE
Google Adsense Ads does not work properly on OwnCloud.

### ISSUE THREAD

**Issue by raisulmac** [owncloud/core#21789]
Hello

I have OwnCloud website. I am using google adsense ads on my owncloud website. But does not work properly. (Specific Google Chrome Browse)
But, Other old version browser working like_ Old Firefox, Internet Explore 9,10

I am using the google ads on this (public.php & authenticate.php) templates.
See the example....

https://properfile.com/cloud/index.php/s/aHcSwwB5EWnSIOZ

Old version firefox browser: https://properfile.com/cloud/index.php/s/DV5W7at7wzYEhms
Google chrome browser: https://properfile.com/cloud/index.php/s/SVixeWD2WgRdEqL

I need fix this problem. Can you help me?
I am waiing for your positive response.

Best Regards,
Raisul

**Comment by RealRancor** [comment]
@raisulmac As this issue tracker is used for bugreports and feature requests you should see https://owncloud.org/support/ for support options which describes the places to get help with that.

**Comment by MorrisJobke** [comment]
This is nothing owncloud core related. This is clearly something in your plugin that is not working. Closing therefore
