### ISSUE TITLE
New option to disable file icons

### ISSUE THREAD

**Issue by sualko** [owncloud/core#21796]
Beside <code>enable_previews</code>, which disables all previews (also in gallery app owncloud/gallery#488), a <code>enable_fileicon</code> flag, which disables only the generation of little file icons, would be very helpful. Especially on low processing power devices like Raspberry, because the generation of these icons in folders with hundreds of images is really a pain.

**Comment by karlitschek** [comment]
what do you mean with generation? This should be static icons which are fast to load from the server. same as all other images. Do i miss something here?

**Comment by sualko** [comment]
OC 8.2 generates icons depending on the file type. 

e.g. For text files (*.txt) the icon will be a preview of the content.

![screen shot 2016-01-20 at 16 05 13](https://cloud.githubusercontent.com/assets/2974196/12452655/d8c642ce-bf8f-11e5-9914-8b1551b76b69.png)

This has a really bad impact (100% cpu usage) on my instance which runs on a vserver. After disabling, oc runs really smooth.

**Comment by karlitschek** [comment]
@sualko but this should be the previews that are not generated when disabled. Or do I miss something?

**Comment by sualko** [comment]
Yes you are right. If I set <code>enable_previews = false</code> these previews will not be generated, but also the ones for the gallery. This flag disables the generation of all previews, that is why I propose a second flag, which disables only the generation of previews in the file app.

**Comment by rullzer** [comment]
Well that is going to become a web of settings then. Which is not something we want.

Because previews also manager the previews in the side bar. And since we support many different display format it could very well be that a preview in the sidebar on one machine is close to the dimensions of the preview icon on a different once (high resolution display).

You have previews or you don't. Either way it should just be 'slow' the first time. Since previews are cached.

**Comment by sualko** [comment]
> You have previews or you don't.

I see this different. I want to decide in which app I have previews and in which not.

> And since we support many different display format it could very well be that a preview in the sidebar on one machine is close to the dimensions of the preview icon on a different once

I don't understand why this is important. I also do not open the sidebar for every file.

> Either way it should just be 'slow' the first time. Since previews are cached.

I have no time to wait in every folder 1-2 minutes until every file icon is generated. And also the cache works, as far as I know, on a user level base. So it is slow for every single user.

> Well that is going to become a web of settings then.

What is there against an option "disable preview file icons" in the admin settings?

One general questions: Is it common practice, that a single person can decide if an enhancement is valid or not? Should it not be the same as for pr that you need two reviewers?
