### ISSUE TITLE
Share link activities not triggered anymore due to move to webdav

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#21794]
### Download via name-link
1. Share a folder via link
2. Open public link
3. Download by clicking on the file name
4. Check whether an activity was added for the owner :x: 

### Download via dropdown
1. Share a folder via link
2. Open public link
3. Download by clicking `...` menu and then on the download button
4. Check whether an activity was added for the owner :x: 

### Download via list-checkbox
1. Share a folder via link
2. Open public link
3. Check the checkbox of a file
4. Click the download button at the top of the list
5. Check whether an activity was added for the owner :white_check_mark: 

### Download via header-button
1. Share a folder via link
2. Open public link
3. Click the download button  in the header
4. Check whether an activity was added for the owner :white_check_mark: 

### Download file via header-button
1. Share a file via link
2. Open public link
3. Click the download button  in the header
4. Check whether an activity was added for the owner :white_check_mark: 

### Download file via page-button
1. Share a file via link
2. Open public link
3. Click the download button below the preview
4. Check whether an activity was added for the owner :white_check_mark: 

@PVince81 broken since you moved those to webdav

**Comment by PVince81** [comment]
How was the download detection done so far ?

Maybe we can fix this as part of https://github.com/owncloud/core/issues/21787 and log the activity when doing the redirection.

This means that direct access to "public.php/the/file.dat" wouldn't log an activity, but downloading over the official URL "index.php/s/$token" would.

I'm assuming that the intention was only to log downloads done over the web UI.

Note that if a public link was mounted as part of "Add to ownCloud", it already goes through public.php and wouldn't have logged download activities in OC <= 9

**Comment by nickvergessen** [comment]
Well the activity code is in the share controller, so yes keeping it there and then redirecting would work, although that is doubled efforts and somewhat incomplete as you mentioned.

**Comment by PVince81** [comment]
Why would it be doubled efforts ?

The incompleteness already existed before. It is conceptually difficult to accurately track downloads because we have to specify what qualifies as a download. For now I suggest to try and make it log an activity for the same actions as before, no behavior change.

**Comment by nickvergessen** [comment]
> Why would it be doubled efforts ?

Because we need to load all apps and stuff before the redirect as well, otherwise the redirect could have been moved to htaccess level or what ever.

**Comment by PVince81** [comment]
Ah I see, you're right.

**Comment by rullzer** [comment]
This should be fixed with https://github.com/owncloud/core/pull/22297

**Comment by rullzer** [comment]
Yep just tested... all activities work again... closing.
