### ISSUE TITLE
OwnCloud WebDAV fails mounting from Windows 7/8

### ISSUE THREAD

**Issue by tps800** [owncloud/core#21804]
### Steps to reproduce
1. Install OwnCloud, Configure OwnCloud, Configure LDAP access
2. Allow WebDAV
3. Go to your Windows Box, then open File-Browser, click on "Connect network drive"
4. Follow the instructions, then copy your OwnCloud server WebDAV-URL: "`https://<yourserversaddress>/owncloud/remote.php/webdav/`"

### Expected behaviour
Mount WebDAV as driveletter without issues.

### Actual behaviour
Shows certificate, asks it this certificate shall be installed. After answering "yes", fails with: "Cant connect drive: device error".

It **does** work with Linux and davfs out of the box:
* Ubuntu 14.04.5 LTS
* CentOS 6,7
* Fedora 22,23,24

It does work with
* Windows XP (but that is outdated)

It **does not** work with
* Windows 7
* Windows 10

### Client configuration
**Operating system:** Ubuntu 14.04.5 LTS

**OwnCloud Client:** nightly

**Operating system:** Windows 7 Pro

**OwnCloud Client:** nightly

**Operating system:** Windows 10 Pro

**OwnCloud Client:** nightly

### Server configuration
**Operating system:** Oracle Linux 6.7

**Web server:** Apache 2.2.15-47.0.1

**Database:** PostgreSQL 9.3.10-1

**PHP version:** PHP 5.6.16-1

**redis version:** redis-2.4.10-1

**ownCloud version:** owncloud-8.2.2-1.1

**Updated from an older ownCloud or fresh install:** Upgrade from 6.5

**List of activated apps:**
* Enabled:
 - activity
 - files
 - files_pdfviewer
 - files_sharing
 - files_trashbin
 - files_texteditor
 - files_versions
 - gallery
 - imprint
 - ocusagecharts
 - password_policy
 - user_ldap

* Disabled:
 - external
 - files_encryption
 - files_external
 - files_locking
 - files_videoviewer
 - firstrunwizard
 - provisioning_api
 - templateeditor
 - updater
 - user_external
 - user_webdavauth

**The content of config/config.php:** 

```
<?php
$CONFIG = array (
  'instanceid' => 'oc692ddacb52',
  'passwordsalt' => '',
  'trusted_domains' =>
  array (
    0 => '<server1>.<local1>.<domain1>',
    1 => '<server2>.<local2>.<domain2>',
  ),
  'datadirectory' => '/data/owncloud/data',
  'dbtype' => 'pgsql',
  'version' => '7.0.1.1',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncld',
  'dbpassword' => '',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => '0',
  'mail_smtpmode' => 'php',
  'mail_smtpname' => 'admin',
  'mail_smtppassword' => '',
  'overwritewebroot' => '/owncloud',
  'overwrite.cli.url' => '/owncloud',
  'secret' => '',
  'redis' => array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
    'dbindex' => 0,
  ),
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'proxy' => 'proxy-lb:8080',
);

```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

### Client configuration
**Browser:**
* Windows XP/7/8:
 * Chrome (stable, beta, snapshot)
 * Chromium (stable, continuous)
 * Firefox (stable, nightly)
 * Opera (stable)
 * lynx (from cygwin)
 * w3m (from cygwin)
* Linux (Debian, Ubuntu 12.04/14.04/14.10, Fedora 19/20/21, Oracle Linux 6.5/7.0)
 * Chrome (stable, beta, snapshot)
 * Chromium (stable, continuous)
 * Firefox (stable, nightly)
 * Opera (last available)
 * Konqueror (stable)
 * lynx (stable)
 * w3m (stable)

#### Web server error log
```
10.160.2.12 - user [20/Jan/2016:14:05:18 +0100] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 369
```

#### ownCloud log (data/owncloud.log)
```
no entry related found
```

#### Browser log
```
Browser log
```

**Comment by RealRancor** [comment]
Hi,

the windows native webdav implementations are known to have various issues with WebDAV connections. Have a look at:

https://doc.owncloud.org/server/8.2/user_manual/files/access_webdav.html#known-problems
https://forum.owncloud.org/viewtopic.php?f=17&t=21656
https://doc.owncloud.org/server/8.2/user_manual/files/access_webdav.html#accessing-files-using-microsoft-windows

for some pointers.

**Comment by DeepDiver1975** [comment]
This is a known issue - please follow our docs https://doc.owncloud.org/server/9.0/user_manual/files/access_webdav.html#accessing-files-using-microsoft-windows
