### ISSUE TITLE
high mysql connections every night

### ISSUE THREAD

**Issue by colttt** [owncloud/core#21800]
Hello normally we've ~6 connection on our owncloud-mysql-server, but every night it goes up to more than 150.. 
Can you tell me why this happen, is this same reason like https://github.com/owncloud/core/issues/21224 ?

![mysql_peak](https://cloud.githubusercontent.com/assets/10084871/12446599/34efe6b0-bf6b-11e5-82ce-da2aac69674e.png)

```
176635	owcl-user	localhost	wolke7	Query	224	Writing to net	SELECT /*!40001 SQL_NO_CACHE */ * FROM `oc_filecache`
176636	owcl-user	localhost	wolke7	Query	349	Waiting for table level lock	DELETE FROM `oc_file_locks` WHERE `lock` = 0 AND `ttl` < '1453157151'
[...]
176690	owcl-user	localhost	wolke7	Query	301	Waiting for table level lock	DELETE FROM `oc_file_locks` WHERE `lock` = 0 AND `ttl` < '1453157199'
176692	owcl-user	localhost	wolke7	Query	299	Waiting for table level lock	UPDATE `oc_preferences` SET `configvalue` = '1453157201' WHERE `userid` = 'xxx63b52-c3ae-1033-86d6-8763c51afxxx' AND `appid` = 'user_ldap' AND `configkey` = 'lastFeatureRefresh'
176693	owcl-user	localhost	wolke7	Query	299	Waiting for table level lock	UPDATE `oc_preferences` SET `configvalue` = '1453157201' WHERE `userid` = 'xxx63b52-c3ae-1033-86d6-8763c51afxxx' AND `appid` = 'user_ldap' AND `configkey` = 'lastFeatureRefresh'
176694	owcl-user	localhost	wolke7	Query	298	Waiting for table level lock	DELETE FROM `oc_file_locks` WHERE `lock` = 0 AND `ttl` < '1453157202'
176695	owcl-user	localhost	wolke7	Query	295	Waiting for table level lock	DELETE FROM `oc_file_locks` WHERE `lock` = 0 AND `ttl` < '1453157205'
[...]
176771	owcl-user	localhost	wolke7	Query	210	Waiting for table level lock	DELETE FROM `oc_file_locks` WHERE `lock` = 0 AND `ttl` < '1453157290'
176772	owcl-user	localhost	wolke7	Query	209	Waiting for table level lock	UPDATE `oc_preferences` SET `configvalue` = '1453157291' WHERE `userid` = 'xxx63b52-c3ae-1033-86d6-8763c51afxxx' AND `appid` = 'user_ldap' AND `configkey` = 'lastFeatureRefresh'
176773	owcl-user	localhost	wolke7	Query	209	Waiting for table level lock	UPDATE `oc_preferences` SET `configvalue` = '1453157291' WHERE `userid` = 'xxx63b52-c3ae-1033-86d6-8763c51afxxx' AND `appid` = 'user_ldap' AND `configkey` = 'lastFeatureRefresh'
176774	owcl-user	localhost	wolke7	Query	209	Waiting for table level lock	DELETE FROM `oc_file_locks` WHERE `lock` = 0 AND `ttl` < '1453157291'
[...]
176815	owcl-user	localhost	wolke7	Query	145	Waiting for table level lock	DELETE FROM `oc_file_locks` WHERE `lock` = 0 AND `ttl` < '1453157355'
176816	owcl-user	localhost	wolke7	Query	143	Waiting for table level lock	UPDATE `oc_preferences` SET `configvalue` = '1453157357' WHERE `userid` = 'xxx67c54-7e2a-1030-89f7-a1198bbfexxx' AND `appid` = 'user_ldap' AND `configkey` = 'lastFeatureRefresh'
176817	owcl-user	localhost	wolke7	Query	141	Waiting for table level lock	DELETE FROM `oc_file_locks` WHERE `lock` = 0 AND `ttl` < '1453157359'
176819	owcl-user	localhost	wolke7	Query	138	Waiting for table level lock	DELETE FROM `oc_file_locks` WHERE `lock` = 0 AND `ttl` < '1453157362'[...]
176856	owcl-user	localhost	wolke7	Query	69	Waiting for table level lock	DELETE FROM `oc_file_locks` WHERE `lock` = 0 AND `ttl` < '1453157431'
176877	root	localhost	NULL	Query	0	NULL	SHOW full processlist

```

**Comment by RealRancor** [comment]
Hi,

do you have a wrongly configured cronjob that is running the cron.php only at this time instead of the recommended 10 minutes in between the runs?

**Comment by colttt** [comment]
hi,

we still use the ajax cronjob..

**Comment by RealRancor** [comment]
That is something you really shouldn't use, especially not when using many users.

Setup a cronjob which calls the cron.php every 10 minutes and see if that solves your issue.

**Comment by colttt** [comment]
so, now i run the cron every 10 minutes, but i still have this issue
![owncloud_conn](https://cloud.githubusercontent.com/assets/10084871/12880781/35546f80-ce44-11e5-9e41-a5428676d57b.png)

**Comment by RealRancor** [comment]
And what is running during this time? The "SHOW full processlist" is probably not catched exactly at this time?

**Comment by colttt** [comment]
i can create a trigger to catch this, you will have this list tomorrow

**Comment by colttt** [comment]
Hello, in attach the output from "SHOW full processlist"
[show_full_processlist.log.zip](https://github.com/owncloud/core/files/124314/show_full_processlist.log.zip)

**Comment by colttt** [comment]
Hello, in attach the output from "SHOW full processlist"
[show_full_processlist.log.zip](https://github.com/owncloud/core/files/124319/show_full_processlist.log.zip)

**Comment by blizzz** [comment]
Since it's periodic it is most likely to be a job. ownCloud background jobs have an own internval with which they are run. You could check the oc_jobs table and check those. Or you (or one of your users) does periodically access ownCloud every 2hrs with another scheduled task. 

Anyway, I think this is far from a bug report and rather belongs rather to discussion or support channels, please see https://owncloud.org/support/
