### ISSUE TITLE
Can't view the full list of files by sharing big directory over a link

### ISSUE THREAD

**Issue by tm-dd** [owncloud/core#21809]
Hello developers,

if you share big directories on ownCloud over a link, there is a bug by viewing the files in the browser. You can only see the first files of the directory and can't NOT SCROLL down to the others files below.

The bug was not in the older version 8.1.5 of ownCloud but on the current version 8.2.2 and is only in the public view over the shared link.

For a quick and dirty fix, I changed the file "owncloud/apps/files_sharing/templates/public.php" and disable the ```<div id="content">``` and ```</div>``` in the code. 

Here are the output of 'diff -c public.php.original public.php':

```
*** public.php.original	2016-01-20 13:24:38.223838325 +0100
--- public.php	2016-01-20 13:26:29.168092776 +0100
***************
*** 88,94 ****
  		</div>
  </div></header>
  <div id="content-wrapper">
! 	<div id="content">
  		<div id="preview">
  			<?php if (isset($_['folder'])): ?>
  				<?php print_unescaped($_['folder']); ?>
--- 88,94 ----
  		</div>
  </div></header>
  <div id="content-wrapper">
! <!--	<div id="content"> -->
  		<div id="preview">
  			<?php if (isset($_['folder'])): ?>
  				<?php print_unescaped($_['folder']); ?>
***************
*** 115,121 ****
  				</div>
  			<?php endif; ?>
  		</div>
! 	</div>
  	<footer>
  		<p class="info">
  			<?php print_unescaped($theme->getLongFooter()); ?>
--- 115,121 ----
  				</div>
  			<?php endif; ?>
  		</div>
! <!--	</div> -->
  	<footer>
  		<p class="info">
  			<?php print_unescaped($theme->getLongFooter()); ?>
```

I hope you can fix this bug in one of the next releases.

MANY THANKS FOR PROGRAMING OWNCLOUD !!!
This is a great and very useful software for many people.

Regards,

Thomas Müller (PKS)

**Comment by RealRancor** [comment]
@tm-dd There are currently two open issues reported about such stuff:

https://github.com/owncloud/core/issues/21373 -> disabling files_pdfviewer
https://github.com/owncloud/core/issues/21203 -> IE issue

**Comment by jancborchardt** [comment]
Please review if this backport for files_pdfviewer fixes it https://github.com/owncloud/files_pdfviewer/pull/92 cc @Henni

**Comment by tm-dd** [comment]
Sorry, should I try something ?
What means review backport owncloud/files_pdfviewer#92 ? 
To try a new version of files for "files_sharing" or only to read the page ?

Here are a short screenshot of the problem:

![owncloudbug_21809](https://cloud.githubusercontent.com/assets/9142382/12455440/0854fa56-bf9c-11e5-9909-14beb4f269f9.png)

**Comment by RealRancor** [comment]
@tm-dd You cold download the two files here:

https://github.com/owncloud/files_pdfviewer/pull/92/files

View Button -> Raw Button

and replace the old ones of your installation with them.

**Comment by jancborchardt** [comment]
Will be fixed in the next maintenance release cause https://github.com/owncloud/files_pdfviewer/pull/92 has been merged. :)

**Comment by tm-dd** [comment]
I'm wondering about why you need to fix files in "files_pdfviewer", because the problem was not in a pdfviewer, but I changed the files from https://github.com/owncloud/files_pdfviewer/pull/92/files and these new files FIX THE PROBLEM on my ownCloud server.

Many thanks for solving the problem !

Thomas

**Comment by jancborchardt** [comment]
@tm-dd yep, it sure seems strage – but the reason is that we minify the files and serve everything at once, important for performance. Hence the styles of one app, if not properly namespaced, can interfere with others.
