### ISSUE TITLE
ownCloud LDAP users imported, but can't login

### ISSUE THREAD

**Issue by tps800** [owncloud/core#21803]
### Steps to reproduce
1. Install OwnCloud, Configure OwnCloud, Configure LDAP access
2. Upgrade to OwnCloud 8.2.2 from 8.1
3. Change the uid-filter list to include additional users
4. none of these new users will be able to login. They are all kicked out with wrong password.

### Expected behaviour
Login of these new users works, LDAP authenticates

### Actual behaviour
Login of these new users does not work. Users are imported, but authentication fails.

### Client configuration
**Operating system:** Ubuntu 14.04.5 LTS

**OwnCloud Client:** nightly

**Operating system:** Windows 7 Pro

**OwnCloud Client:** nightly

**Operating system:** Windows 10 Pro

**OwnCloud Client:** nightly

### Server configuration
**Operating system:** Oracle Linux 6.7

**Web server:** Apache 2.2.15-47.0.1

**Database:** PostgreSQL 9.3.10-1

**PHP version:** PHP 5.6.16-1

**redis version:** redis-2.4.10-1

**ownCloud version:** owncloud-8.2.2-1.1

**Updated from an older ownCloud or fresh install:** Upgrade from 6.5

**List of activated apps:**
* Enabled:
 - activity
 - files
 - files_pdfviewer
 - files_sharing
 - files_trashbin
 - files_texteditor
 - files_versions
 - gallery
 - imprint
 - ocusagecharts
 - password_policy
 - user_ldap

* Disabled:
 - external
 - files_encryption
 - files_external
 - files_locking
 - files_videoviewer
 - firstrunwizard
 - provisioning_api
 - templateeditor
 - updater
 - user_external
 - user_webdavauth

**The content of config/config.php:** 

```
<?php
$CONFIG = array (
  'instanceid' => 'oc692ddacb52',
  'passwordsalt' => '',
  'trusted_domains' =>
  array (
    0 => '<server1>.<local1>.<domain1>',
    1 => '<server2>.<local2>.<domain2>',
  ),
  'datadirectory' => '/data/owncloud/data',
  'dbtype' => 'pgsql',
  'version' => '7.0.1.1',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncld',
  'dbpassword' => '',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => '0',
  'mail_smtpmode' => 'php',
  'mail_smtpname' => 'admin',
  'mail_smtppassword' => '',
  'overwritewebroot' => '/owncloud',
  'overwrite.cli.url' => '/owncloud',
  'secret' => '',
  'redis' => array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
    'dbindex' => 0,
  ),
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'proxy' => 'proxy-lb:8080',
);

```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

### Client configuration
**Browser:**
* Windows XP/7/8:
 * Chrome (stable, beta, snapshot)
 * Chromium (stable, continuous)
 * Firefox (stable, nightly)
 * Opera (stable)
 * lynx (from cygwin)
 * w3m (from cygwin)
* Linux (Debian, Ubuntu 12.04/14.04/14.10, Fedora 19/20/21, Oracle Linux 6.5/7.0)
 * Chrome (stable, beta, snapshot)
 * Chromium (stable, continuous)
 * Firefox (stable, nightly)
 * Opera (last available)
 * Konqueror (stable)
 * lynx (stable)
 * w3m (stable)

#### Web server error log
```
10.160.0.85 - user [20/Jan/2016:13:46:52 +0100] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 369
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"WII8Q69AesvHRFT5EzYH","remoteAddr":"10.160.3.176","app":"core","message":"Login failed: 'user' (Remote IP: '10.160.3.176')","level":2,"time":"2016-01-20T13:46:52+00:00"}
```

#### Browser log
```
Browser log
```

**Comment by MorrisJobke** [comment]
Can I ask you for the LDAP config: `./occ ldap:show-config` and what value the und filter was before the change?

cc @blizzz

**Comment by karlitschek** [comment]
This sounds like a setup specific problem. Please also consider to ask your question at on of the channels listed here. owncloud.org/support.

**Comment by blizzz** [comment]
> Change the uid-filter list to include additional users

You also need to adjust the login filter, not only user filter.

**Comment by tps800** [comment]
Yes, this was it. Now it is working as expected!
