### ISSUE TITLE
.user.ini not shipped in packages (debian, centos, maybe more?)

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#21801]
Hi,

current oC 8.2.2 packages (Only checked debian and centos6) are not providing the .user.ini for php-fpm installations:

https://github.com/owncloud/core/blob/master/.user.ini

@jnweiger Any chances to include that file in the packages?

**Comment by MorrisJobke** [comment]
I just checked: the file is present in the tar.bz2 file, so it's clearly happening during packaging.

**Comment by jnweiger** [comment]
Yes. all the .bower .git* and so on files are removed during packaging. Only .htaccess was curently retained.

9.0 packaging will have the .user.ini --

**Comment by jnweiger** [comment]
backported to 8.2 packages. Change will be visible with 8.2.3
