### ISSUE TITLE
Search for files in folders shared by link

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#21818]
It would be fancy to be able to search for files in public shared folders, so if somebody sends me a huge shared public shared folder and I just want to access a specific file I'd like to just click on search and have a search on the file name.

cc @jancborchardt as discussed

**Comment by PVince81** [comment]
Public shared folders ? Do you mean federated shares ?

**Comment by jancborchardt** [comment]
@PVince81 shared links.

**Comment by PVince81** [comment]
Ok, so you want the search field to be visible in the public page.
