### ISSUE TITLE
Text files created in google drive folder with editor cannot be opened

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#21813]
### Steps to reproduce

1. Enable external storage and mount a google drive folder.
2. Create a text file using editor inside the folder.
3. Save it.

### Expected behaviour
File can be opened.

### Actual behaviour
File is downloaded, it is not detected as text file.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Master branch
{"installed":true,"maintenance":false,"version":"9.0.0.6","versionstring":"9.0 pre alpha","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```

```

### Client configuration

**browser**
Chrome

**Comment by PVince81** [comment]
Can they be opened after refreshing the page ?

If not, then it's probably sev-high

**Comment by SergioBertolinSG** [comment]
Refreshing doesn't help.
File can be downloaded and read then, but no edited.

**Comment by PVince81** [comment]
Works for me in 9.0.3RC1. I believe we fixed a mime type issue recently.
