### ISSUE TITLE
Contact Picture is not showing

### ISSUE THREAD

**Issue by Happyfeet01** [owncloud/core#21819]
Hello,

i have a new Issue found. 

**Issue**

When you add an Picture on the Phone and sync them to the owncloud Server. The Picture is only on Owncloud not showing.

### Steps to reproduce

1. create an Contact and add an Picture on Android.
2. Sync the Client.
3. the Picture is not showing, Only Profilepictures they are added on Ownloud are showing.

### Server configuration

Owncloud 8.2.2
Odroid U3
PHP 5.5.9-1ubuntu4 (cli)
Server version: Apache/2.4.7 (Ubuntu)
Server built:   Apr  3 2014 12:23:45
mysql

**activated and deactivated Apps**

**Enabled:**
  - activity: 2.1.3
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - documents: 0.11.0
  - encryption: 1.1.0
  - files: 1.2.0
  - files_ckeditor: 0.1.0
  - files_external: 0.3.0
  - files_mv: 0.8.1a
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - galleryplus: 14.3.0
  - music: 0.3.8
  - news: 7.0.0
  - notes: 2.0.0
  - notifications: 0.1.0
  - ocdownloader: 1.5
  - ownbackup: 0.3.7
  - polls: 0.6.4
  - provisioning_api: 0.3.0
  - shorty: 0.5.0
  - shorty_tracking: 0.3.0
  - templateeditor: 0.1

**Disabled:**

  - bookmarks
  - external
  - files_antivirus
  - files_w2g
  - firstrunwizard
  - gallery
  - piwik
  - proxy
  - storagecharts2
  - tasks
  - user_external
  - user_ldap

### Logs

no entry´s in owncloud.log

**Comment by RealRancor** [comment]
@Happyfeet01 The issue tracker of the contacts app is located here: https://github.com/owncloud/contacts/issues

Unfortunately github doesn't allow to move issues so please close here and re-open at the linked issue tracker after you made sure that no existing issue exists.

**Comment by MorrisJobke** [comment]
Yes. This is a contacts issue. Please reopen there. Thanks
