### ISSUE TITLE
[CalDAV/CardDAV] core's dav app has to provide old caldav and carddav endpoints for already setup clients

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#21812]
Clients which are already connected to an ownCloud instance use the webdav endpoints
- remote.php/caldav
- remote.php/carddav

We need to implement these endpoints within the dav app of core in oc9.0 as well

**Comment by RealRancor** [comment]
Good point. But shouldn't it be possible to do just a redirect within the .htaccess or is that not enough?

**Comment by DeepDiver1975** [comment]
I was thinking about redirects as well - first of all I have no idea how various client will react on redirects.
Second - the urls do not fully match.
E.g. the new addressbook urls adds users - remote.php/dav/addressbooks/users/admin/test vs remote.php/carddav/calendars/admin/test

**Comment by RealRancor** [comment]
Ah, sure. Probably many clients can handle redirects as there are the .well-known/* redirects but i thinks its better safe than sorry.

A little bit off-topic concerning the new calendar and addressbook urls:

Do you have some time to re-check https://github.com/owncloud/documentation/pull/2013 where i have already updated the URLs to the new DAV endpoints. After i have seen the new ones above i'm not absolutely sure if all of them are correct.

**Comment by DeepDiver1975** [comment]
> Ah, sure. Probably many clients can handle redirects as there are the .well-known/* redirects but i thinks its better safe than sorry.

I think we have to make a difference between redirects during the initial lookup and once the calendars and addressbooks are setup.

**Comment by DeepDiver1975** [comment]
> Do you have some time to re-check owncloud/documentation#2013 where i have already updated the URLs to the new DAV endpoints. After i have seen the new ones above i'm not absolutely sure if all of them are correct.

THX - yes - these urls need some love - https://github.com/owncloud/documentation/issues/2074

**Comment by PVince81** [comment]
@DeepDiver1975 still todo ?

**Comment by PVince81** [comment]
I thought we already merged a PR that would do that

**Comment by nickvergessen** [comment]
Okay, what I found out so far is, that for calendars the queries are executed with the wrong principal, `principal/test` instead of `principal/users/test`.

I could get that fixed with:
```diff
diff --git a/apps/dav/appinfo/v1/caldav.php b/apps/dav/appinfo/v1/caldav.php
index f860ced..370f07f 100644
--- a/apps/dav/appinfo/v1/caldav.php
+++ b/apps/dav/appinfo/v1/caldav.php
@@ -29,22 +29,20 @@ use Sabre\CalDAV\CalendarRoot;
 
 $authBackend = new Auth(
 	\OC::$server->getSession(),
-	\OC::$server->getUserSession(),
-	'principals/'
+	\OC::$server->getUserSession()
 );
 $principalBackend = new Principal(
 	\OC::$server->getUserManager(),
-	\OC::$server->getGroupManager(),
-	'principals/'
+	\OC::$server->getGroupManager()
 );
 $db = \OC::$server->getDatabaseConnection();
 $calDavBackend = new CalDavBackend($db, $principalBackend);
 
 // Root nodes
-$principalCollection = new \Sabre\CalDAV\Principal\Collection($principalBackend);
+$principalCollection = new \Sabre\CalDAV\Principal\Collection($principalBackend, 'principals/users');
 $principalCollection->disableListing = true; // Disable listing
 
-$addressBookRoot = new CalendarRoot($principalBackend, $calDavBackend);
+$addressBookRoot = new CalendarRoot($principalBackend, $calDavBackend, 'principals/users');
 $addressBookRoot->disableListing = true; // Disable listing
 
 $nodes = array(
```

The pre-check then passes, however we are trying to check one level too much then:
```xml
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>3.0.7</s:sabredav-version>
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>File not found: principals in 'root'</s:message>
</d:error>
```

But I will continue to investigate

**Comment by DeepDiver1975** [comment]
The principal for caldav URL does not contain the users sub folder

**Comment by DeepDiver1975** [comment]
And yes this issue is finished

**Comment by nickvergessen** [comment]
Yeah already fixed it, PR is coming

**Comment by nickvergessen** [comment]
Well as per https://github.com/owncloud/core/issues/22346 this is broken, #22348 is the fix for it.
