### ISSUE TITLE
Verify encryption key status

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#21828]
It would be nice to have an `occ` command to verify that all keys are available at the correct place. This is helpful for example when a backup is restored and allows the admin to check, that each file has at least a corresponding key.

@schiesbn Does this make sense?

@MTRichards @DeepDiver1975 @karlitschek for the vision and architecture stand point

cc @felixboehm - we just have a case where it is unclear if all files also have the keys available

**Comment by MTRichards** [comment]
Conceptually makes sense to me, and would solve some real world usability challenges with encryption. What do you think @schiesbn @DeepDiver1975 ?

**Comment by karlitschek** [comment]
I agree. Would be good to have

**Comment by PVince81** [comment]
Setting to backlog for now.
