### ISSUE TITLE
OC_Helper::linkTo <--> caldav app

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#21827]
oC cloned from master via ocdev base (which includes cloning some apps)

You can enable the shipped calendar app 
![image](https://cloud.githubusercontent.com/assets/3321281/12480298/9d65286e-c041-11e5-839b-957c1aca307c.png)
but you get an error because of #21253 (Remove deprecated OC_Helper::linkTo).
The calendar app can not be opened (white screen).

oC error log:
Call to undefined method OC_Helper::linkTo() at /xxxx/apps/calendar/templates/calendar.php#1

**Comment by DeepDiver1975** [comment]
please open in https://github.com/owncloud/calendar
