### ISSUE TITLE
[8.2.2] Encryption - Certain pictures unreadable

### ISSUE THREAD

**Issue by josh4trunks** [owncloud/core#21823]
I may be kinda screwed here, possibly lost some engagement pictures.
I was syncing some files and noticed 2 of my folders of pictures were not opening as JPEGs. I do have daily snapshots of my owncloud data-directory going back 8 weeks but I don't know if that will help in recovering my files.

What can I possibly try to do to unencrypt files given everything in the data-directory.
Here's one of the files that isn't opening as a JPEG. I have about 200 pictures that have the same issue.
![adajosh-028](https://cloud.githubusercontent.com/assets/1018807/12475394/896b7238-bfd7-11e5-9286-74868a76c1f3.jpg)

**Comment by josh4trunks** [comment]
I'm trying with a single file, from my 2015-11-26 snapshot. Copied the encrypted file, and keys where I'd expect them to go, rescanned files in owncloud, but the file isn't being decrypted properly by owncloud. This is even for files I know should work (show as JPEGs currently) so I'm probably doing something wrong.

**Comment by MorrisJobke** [comment]
@josh4trunks Can you specify the owncloud version?

**Comment by MorrisJobke** [comment]
@schiesbn for the recovery case for encryption.

**Comment by MorrisJobke** [comment]
@josh4trunks And also write down the files you have recovered - just to be save, that you used the correct files and paths.

**Comment by josh4trunks** [comment]
I'm on 8.2.2 (see title).
I actually have been able to recover a single file, at least partially for now. I'll post my results

**Comment by PVince81** [comment]
Any update on the results ?

**Comment by josh4trunks** [comment]
I was able to recover everything =]

I used 'dd' in a script with a for loop to create files with the same name that were larger then anything I previously had. then synced those files over to my owncloud instance. then on my server I replaced the encrypted files and keys with what I had from a zfs snapshot. then I download the whole folder as a zip from the web-interface.
deleted all the previous stuff and replaced it with the proper pictures from the zip

here's some things that tripped me up...
* if I synced over files that were to small, the resultant files downloaded from owncloud would be cut off. the jpeg weren't complete. make sure you go larger then you need. ratio of encrypted to unencrypted was like 1.3 so sync over files that are at least 0.8x the size of your largest encrypted file.
* download everything as a zip. otherwise your jpegs will be padded, which you could probably identify/fix with hex editor but the zip did this for me.
