### ISSUE TITLE
Add config option to change curl timeout

### ISSUE THREAD

**Issue by berturion** [owncloud/core#21821]
### Steps to reproduce
1. Login to ownCloud with an admin account
2. Go to "+ Applications" to access to the application menu
3. Wait for application categories to show up

### Expected behaviour
We see the categories:
* Enabled
* Disabled
* Multimedia
* Productivity
* Game
* Tool

### Actual behaviour
We only see:
* Enabled
* Disabled

In the logs, I have curl timeouts when getting categories and applications:

    {"reqId":"1KH\/vDesBFgDMmB\/Zn\/r","remoteAddr":"x.x.x.x","app":"core","message":"Could not get categories: cURL error 6: See http:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html","level":3,"time":"2015-09-21T05:33:37+00:00"}
    {"reqId":"dU8ZUbVi4egXeKk6OJWv","remoteAddr":"x.x.x.x","app":"core","message":"Could not get application: cURL error 6: See http:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html","level":3,"time":"2015-09-21T05:33:39+00:00"}
    {"reqId":"dU8ZUbVi4egXeKk6OJWv","remoteAddr":"x.x.x.x","app":"core","message":"Could not get application: cURL error 6: See http:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html","level":3,"time":"2015-09-21T05:33:44+00:00"}
    {"reqId":"dU8ZUbVi4egXeKk6OJWv","remoteAddr":"x.x.x.x","app":"core","message":"Could not get application: cURL error 6: See http:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html","level":3,"time":"2015-09-21T05:33:49+00:00"}
    {"reqId":"dU8ZUbVi4egXeKk6OJWv","remoteAddr":"x.x.x.x","app":"core","message":"Could not get application: cURL error 6: See http:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html","level":3,"time":"2015-09-21T05:33:54+00:00"}
    {"reqId":"dU8ZUbVi4egXeKk6OJWv","remoteAddr":"x.x.x.x","app":"core","message":"Could not get application: cURL error 6: See http:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html","level":3,"time":"2015-09-21T05:33:59+00:00"}
    {"reqId":"Cr1jsdvnesj65z6vebuB","remoteAddr":"x.x.x.x","app":"core","message":"Could not get categories: cURL error 6: See http:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html","level":3,"time":"2015-09-21T05:34:16+00:00"}
    {"reqId":"JdfFKB9dCLWKI0uFDzyE","remoteAddr":"x.x.x.x","app":"core","message":"Could not get application: cURL error 6: See http:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html","level":3,"time":"2015-09-21T05:34:17+00:00"}    

### Server configuration

**Operating system**:

Debien Jessie Armhf (Armbian)

**Web server:**

Nginx

**Database:**

MySQL

**PHP version:**

5.6.7

**ownCloud version:** (see ownCloud admin page)

8.2.2.2 (debian package)

**Updated from an older ownCloud or fresh install:**

Updated fom 8.0.3 (from a manual install)

**Signing status (ownCloud 9.0 and above):**

...

**List of activated apps:**

Enabled:

  - activity: 2.1.3
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - encryption: 1.1.0
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - music: 0.3.8
  - news: 7.0.1
  - provisioning_api: 0.3.0
  - templateeditor: 0.1

Disabled:

  - external
  - files_external
  - notifications
  - user_external
  - user_ldap

**The content of config/config.php:**

    "system": {
        "instanceid": "oc5df511e38e",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/media\/usbnas\/owncloud-data",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "mail_smtpdebug": false,
        "mail_domain": "free.fr",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "smtp.free.fr",
        "mail_smtpsecure": "ssl",
        "mail_smtptimeout": 30,
        "mail_smtpauth": true,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "maintenance": false,
        "loglevel": 2,
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "mail_from_address": "berturion",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpport": "465",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "appcodechecker": false,
        "appstoreenabled": true,
        "appstoreurl": "https:\/\/api.owncloud.com\/v1",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "appstore.experimental.enabled": true,
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "asset-pipeline.enabled": false
    }

**Are you using external storage, if yes which one:** local/smb/sftp/...

no

**Are you using encryption:** yes/no

no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

no

#### LDAP configuration (delete this part if not used)

Not used

### Client configuration

**Browser:**

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0

**Operating system:**

Linux Mint 17.3 64bit

#### Web server error log

    {"reqId":"1KH\/vDesBFgDMmB\/Zn\/r","remoteAddr":"x.x.x.x","app":"core","message":"Could not get categories: cURL error 6: See http:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html","level":3,"time":"2015-09-21T05:33:37+00:00"}
    {"reqId":"dU8ZUbVi4egXeKk6OJWv","remoteAddr":"x.x.x.x","app":"core","message":"Could not get application: cURL error 6: See http:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html","level":3,"time":"2015-09-21T05:33:39+00:00"}
    {"reqId":"dU8ZUbVi4egXeKk6OJWv","remoteAddr":"x.x.x.x","app":"core","message":"Could not get application: cURL error 6: See http:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html","level":3,"time":"2015-09-21T05:33:44+00:00"}
    {"reqId":"dU8ZUbVi4egXeKk6OJWv","remoteAddr":"x.x.x.x","app":"core","message":"Could not get application: cURL error 6: See http:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html","level":3,"time":"2015-09-21T05:33:49+00:00"}
    {"reqId":"dU8ZUbVi4egXeKk6OJWv","remoteAddr":"x.x.x.x","app":"core","message":"Could not get application: cURL error 6: See http:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html","level":3,"time":"2015-09-21T05:33:54+00:00"}
    {"reqId":"dU8ZUbVi4egXeKk6OJWv","remoteAddr":"x.x.x.x","app":"core","message":"Could not get application: cURL error 6: See http:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html","level":3,"time":"2015-09-21T05:33:59+00:00"}
    {"reqId":"Cr1jsdvnesj65z6vebuB","remoteAddr":"x.x.x.x","app":"core","message":"Could not get categories: cURL error 6: See http:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html","level":3,"time":"2015-09-21T05:34:16+00:00"}
    {"reqId":"JdfFKB9dCLWKI0uFDzyE","remoteAddr":"x.x.x.x","app":"core","message":"Could not get application: cURL error 6: See http:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html","level":3,"time":"2015-09-21T05:34:17+00:00"}    

#### ownCloud log (data/owncloud.log)

    Error	core	Could not get application: cURL error 28: Resolving timed out after 5516 milliseconds	2016-01-20T13:09:37+00:00
    Error	core	Could not get application: cURL error 28: Resolving timed out after 5514 milliseconds	2016-01-20T13:09:34+00:00
    Error	core	Could not get application: cURL error 28: Resolving timed out after 5515 milliseconds	2016-01-20T13:09:31+00:00
    Error	core	Could not get application: cURL error 28: Resolving timed out after 5516 milliseconds	2016-01-20T13:09:26+00:00
    Error	core	Could not get application: cURL error 28: Resolving timed out after 5516 milliseconds	2016-01-20T13:09:20+00:00
    Error	core	Could not get categories: cURL error 28: Resolving timed out after 5517 milliseconds	2016-01-20T13:09:19+00:00
    Error	core	Could not get application: cURL error 28: Resolving timed out after 5516 milliseconds	2016-01-20T13:09:11+00:00

#### Browser log

not relevant

### Workaround

The error is due to the hard coded timeout on file `owncloud/lib/private/ocsclient.php`.
To make things working I had to modify all lines like this:

    'timeout' => 5

to this:

    'timeout' => 20

**With that change, categories and apps from the appstore are now displayed and I can add all applications I want from there.**

### Feature request

Please add a timeout parameter in config.php to override the 5 seconds default timeout for appstore (file `ocsclient.php`). Maybe an `'appstore.timeout' = 5`.

More information here: https://forum.owncloud.org/viewtopic.php?f=31&t=29192&start=10

**Comment by MorrisJobke** [comment]
This is a feature request to be able to increase the curl timeout because there is a RTT on that given system between 8 and 12 seconds (because of some security systems that check the traffic).

cc @LukasReschke does this make sense?

**Comment by LukasReschke** [comment]
I'd really love to avoid having more configuration options when it can be avoided to avoid cluttering the code with more configuration options. 

Thinking further this will also affect Federated Cloud Sharing and then it starts to get more complicated. I'm more a fan of sane defaults, so maybe we should make the appstore loading not blocking the main GUI and increase the timeout?

**Comment by berturion** [comment]
I understand, increasing the timeout is certainly enough. For my own installation, 10s wasn't enough, that's why I jumped to 20s which can seem huge for other people. I don't know owncloud enough to know if there is side effects to keep it. I will let the experts answer :)

**Comment by RealRancor** [comment]
Just a thought: If a request takes longer then 5 seconds than there are some more serious issues happening on network level. I don't think that a request to the appstore URL should ever takes that long.

**Comment by berturion** [comment]
I live in Reunion Island, where Internet connections are sometimes slow and my ISP is the cheapest one there.

Also, I changed my DNS to those given here: https://www.opennicproject.org/

Maybe these are the reasons for this long request time.

    # curl -v --trace-time https://api.owncloud.com/
    16:02:50.431295 * Hostname was NOT found in DNS cache
    16:03:05.960583 *   Trying 85.25.74.45...
    16:03:06.188674 * Connected to api.owncloud.com (85.25.74.45) port 443 (#0)
    16:03:06.193674 * successfully set certificate verify locations:
    16:03:06.194447 *   CAfile: none
      CApath: /etc/ssl/certs
    16:03:06.196231 * SSLv3, TLS handshake, Client hello (1):
    16:03:06.422327 * SSLv3, TLS handshake, Server hello (2):
    (...)

But should that prevent me from using the owncloud appstore ?

**Comment by RealRancor** [comment]
Ah, sure. Havn't thought about home users with a maybe slow internet connection.

**Comment by tflidd** [comment]
You could set up your own dns resolver in your local network. It will cache the entry and responds faster than external dns servers.

Other option, put api.owncloud.com into your /etc/hosts file, so no dns query will be sent. Downside: if the ip address changes you need to update this entry.

How long is a ping to the DNS servers? How fast do they respond (`dig @serverip api.owncloud.com`)? Do you have other network issues (old dns addresses, not properly working ipv6)?

**Comment by berturion** [comment]
Without DNS cache or /etc/hosts entry, `dig api.owncloud.com`:

    ; <<>> DiG 9.9.5-9+deb8u5-Debian <<>> api.owncloud.com
    ;; global options: +cmd
    ;; Got answer:
    ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8719
    ;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

    ;; QUESTION SECTION:
    ;api.owncloud.com.		IN	A

    ;; ANSWER SECTION:
    api.owncloud.com.	0	IN	A	85.25.74.45

    ;; Query time: 19 msec
    ;; SERVER: 192.168.24.1#53(192.168.24.1)
    ;; WHEN: Sun Jan 24 11:16:08 RET 2016
    ;; MSG SIZE  rcvd: 50

I don't understand why curl takes so long time.

192.168.24.1 is my modem-router.

**Comment by berturion** [comment]
Ok, I found the problem, it's an ipv6 issue. If I run `curl` with `-4` option to force use of ipv4, it is very fast:

    curl -4 -v --trace-time https://api.owncloud.com
    11:35:28.601284 * Rebuilt URL to: https://api.owncloud.com/
    11:35:28.602579 * Hostname was NOT found in DNS cache
    11:35:28.664758 *   Trying 85.25.74.45...
    11:35:28.920966 * Connected to api.owncloud.com (85.25.74.45) port 443 (#0)
    11:35:28.925671 * successfully set certificate verify locations:
    11:35:28.926604 *   CAfile: none
      CApath: /etc/ssl/certs
    11:35:28.928313 * SSLv3, TLS handshake, Client hello (1):
    11:35:29.190404 * SSLv3, TLS handshake, Server hello (2):
    (...)

If I run the same command forcing the use of ipv6, DNS resolving fails.

    curl -6 -v --trace-time https://api.owncloud.com
    11:36:41.712257 * Rebuilt URL to: https://api.owncloud.com/
    11:36:41.713411 * Hostname was NOT found in DNS cache
    11:36:52.235836 * Could not resolve host: api.owncloud.com
    11:36:52.236207 * Closing connection 0
    curl: (6) Could not resolve host: api.owncloud.com

So, I think the problem is that curl tries first to resolve with ipv6, fails, and fall back to ipv4. But the process is then very long.

We could say that this is not related to owncloud but a bad ipv6 configuration.
More information on my network, if any one can help me:

    $ ifconfig
    eth0      Link encap:Ethernet  HWaddr **REMOVED SENSITIVE VALUE**  
          inet addr:192.168.24.84  Bcast:192.168.24.255  Mask:255.255.255.0
          inet6 addr: fe80::1:9ff:fe01:52f4/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:69529 errors:0 dropped:0 overruns:0 frame:0
          TX packets:46570 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:70698199 (67.4 MiB)  TX bytes:6124671 (5.8 MiB)
          Interrupt:45 

    lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:56010 errors:0 dropped:0 overruns:0 frame:0
          TX packets:56010 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:6049594 (5.7 MiB)  TX bytes:6049594 (5.7 MiB)

    $ route -A inet
    Kernel IP routing table
    Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
    default         sagembox.home   0.0.0.0         UG    0      0        0 eth0
    192.168.24.0    *               255.255.255.0   U     0      0        0 eth0

    $ route -A inet6
    Kernel IPv6 routing table
    Destination                    Next Hop                   Flag Met Ref Use If
    fe80::/64                      ::                         U    256 0     0 eth0
    ::/0                           ::                         !n   -1  1     1 lo
    ::1/128                        ::                         Un   0   3   111 lo
    fe80::1:9ff:fe01:52f4/128      ::                         Un   0   1     0 lo
    ff00::/8                       ::                         U    256 2   223 eth0
    ::/0                           ::                         !n   -1  1     1 lo

    $ cat /etc/resolve.conf
    domain home
    search home
    nameserver 192.168.24.1

**Comment by tflidd** [comment]
You have no public ipv6 address. You have two options:
* make ipv6 working (if you provider doesn't support it, you can use a tunnelbroker: https://en.wikipedia.org/wiki/List_of_IPv6_tunnel_brokers), this can be an advantage if you want to access owncloud outside your home network (and external connection has ipv6)
* disable ipv6 on your server

**Comment by berturion** [comment]
My internal network has ipv6 but not my external connection so I disabled ipv6. I opened a post on armbian forum (http://forum.armbian.com/index.php/topic/635-making-curl-use-ipv4-by-default/) because curl still tries to resolve DNS with ipv6 protocol first despite of disabled ipv6.
I don't understand why.

**Comment by berturion** [comment]
Then, could it be possible to add an Owncloud parameter to force curl to resolve server with ipv4 instead of increasing timeout ?

In PHP:

    curl_setopt($ch, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4 );

**Comment by tflidd** [comment]
ipv6 is preferred by default, so owncloud won't be your only problem. Forcing IPv4 is no solution for IPv6-only environments. You need to set up your network properly.
https://wiki.debian.org/DebianIPv6#How_to_turn_off_IPv6

**Comment by berturion** [comment]
I understand. I already followed this wiki and this has no effect on curl.

**Comment by berturion** [comment]
Ok. I re-enabled ipv6 on my machine and simply added these lines to /etc/dhcp/dhclient.conf:

    prepend domain-name-servers 79.133.43.124;
    prepend domain-name-servers 85.25.105.193;

Since then, DNS resolving is done by my local server with opennic nameservers and not my modem-router which fails.

Resolving lasts now 500ms long. Much better.
The real problem was a bad local network configuration. I think my feature request is not so useful. I let you decide.
