### ISSUE TITLE
Update via updater fail

### ISSUE THREAD

**Issue by azharyatim** [owncloud/core#21820]
Tried to update to OC 8.2.1 but received the following message:

Set log level to debug - current level: "Error"
Turned on maintenance mode

The update was unsuccessful. Please report this issue to the ownCloud community.

**Comment by MorrisJobke** [comment]
@azharyatim Can I ask you provide us more information. Please fill out the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

Thanks

**Comment by azharyatim** [comment]
@MorrisJobke Sorry, not too sure about all those.. Anyway I can revert back to the previous version?
