### ISSUE TITLE
Group Manager should clean cache, when new backends are added

### ISSUE THREAD

**Issue by RomanKreisel** [owncloud/core#21835]
Unfortunately the GroupManager (OC\Group\Manager) doesn't clear its caches on addBackend() as it is done by clearBackends().
This makes it impossible for apps to add new groups to a user for which the groups have already been queried and therefor cached. This actually renders my first app "GroupEveryone" (https://apps.owncloud.com/content/show.php?content=174661) unusable.

**Comment by PVince81** [comment]
Linked PR https://github.com/owncloud/core/pull/21836

**Comment by PVince81** [comment]
PR was merged, closing
