### ISSUE TITLE
Share folder by link - missing or wrong scrollbar

### ISSUE THREAD

**Issue by tsbatista** [owncloud/core#21842]
### Steps to reproduce
1. I shared a folder containing 392 files via link (I used the desktop client to generate the link). Each file of about 60M if it matters. The filenames are all in the form of UID_timestsamp_timstamp.csv.gz (6f59760c-e6b1-4682-a3f2-f4cc6e90accb_1443654000000_1451606400000.csv.gz). A full list is attached.
[file_list.txt](https://github.com/owncloud/core/files/100634/file_list.txt)

2. Access the shared folder via browser using an unauthenticated session

### Expected behaviour
I would expect to see the full list of files available on the folder and be able to scroll the list

### Actual behaviour
When accessing the shared link, only the first few files are shown on the web interface, as there is no scroll bar for the inner element with the list of files as you can see on the attached screenshot. The window does have a scrollbar but as soon as you get to the footer of the page, it stops scrolling. as you can see on the attached screenshot.

![screenshot from 2016-01-22 10-01-02](https://cloud.githubusercontent.com/assets/5938977/12507681/34504774-c0ef-11e5-8789-b75e51d1c5e4.png)

### Server configuration
**Operating system**:
Gentoo

**Web server:**
nginx

**Database:**
postgres

**PHP version:**
5.6

**ownCloud version:** (see ownCloud admin page)
8.2.2

**Updated from an older ownCloud or fresh install:**
updated

**List of activated apps:**
Enabled:
  - activity: 2.1.3
  - files: 1.2.0
  - files_external: 0.3.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - templateeditor: 0.1
  - updater: 0.6

Disabled:
  - encryption
  - external
  - notifications
  - provisioning_api
  - user_external
  - user_ldap

**The content of config/config.php:**

I redacted more personal identifiers, if you need them contact me via DM please

{
    "system": {
        "instanceid": "oc453833cd76",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/home\/owncloud\/data",
        "asset-pipeline.enabled": true,
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "8.2.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "preview_libreoffice_path": "\/usr\/bin\/loffice",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "gmail.com",
        "forcessl": true,
        "loglevel": 0,
        "allowZipDownload": true,
        "check_for_working_webdav": false,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpsecure": "tls",
        "mail_smtphost": "smtp.gmail.com",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "theme": "",
        "maintenance": false,
        "forceSSLforSubdomains": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "trashbin_retention_obligation": "auto",
        "appstoreenabled": true
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
Irrelevant for this issue

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
chromium and firefox in their latest releases

**Operating system:**
linux

#### Browser log
Nothing useful on the browser logs, no errors or warnings.

**Comment by karlitschek** [comment]
can you post a full bug report using this template pleae: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by RealRancor** [comment]
@tsbatista Very likely a duplicate of https://github.com/owncloud/core/issues/21373, https://github.com/owncloud/core/issues/21203, https://github.com/owncloud/core/issues/21675 and https://github.com/owncloud/core/issues/21809 which gets fixed with the upcoming 8.2.3

**Comment by tsbatista** [comment]
Without a doubt! Trust me I tried to search for it, but for some reason used scroll as a keyword, did not come across them. Sorry for the noise!
