### ISSUE TITLE
Support single-step upgrading from any version to current version

### ISSUE THREAD

**Issue by jernst** [owncloud/core#21859]
Upgrading while skipping a major package version currently is a lot of manual work. ("Download; install; upgrade; uninstall; repeat" per [forum post](https://forum.owncloud.org/viewtopic.php?f=17&t=32087).) This should be automated.

Many users have run into this, as the many duplicate bug reports related to "Exception: Updates between multiple major versions and downgrades are unsupported." [show](https://github.com/owncloud/core/issues?utf8=%E2%9C%93&q=Updates+between+multiple+major+versions+and+downgrades+are+unsupported.).

Mediawiki has one way of doing this kind of thing. At every release, they add whatever migrations needed to be done at the end of a long upgrade script, which grows with every release. As a result, the script can upgrade any old version of Mediawiki and installs of intermediate versions are never required.

This is important not just for people who don't upgrade ownCloud every time a new version comes out, but particularly for being able to restore old backups.

We just ran into this issue on [UBOS](http://ubos.net/) where users may end up with partially non-functioning devices as we cannot invoke any code (unless we develop it ourselves) that migrates and will work for all possible ownCloud installs. See also https://github.com/uboslinux/ubos-owncloud/issues/9.

(Moved from https://github.com/owncloud/appstore-issues/issues/40)

**Comment by PVince81** [comment]
Requires doctrine migrations: #14851

**Comment by PVince81** [comment]
It is now possible to upgrade from 8.2 to 10.0 and will also be possible to skip major versions in future releases.
