### ISSUE TITLE
Desktop and mobile clients need the Share API exposes the Shares *received* by user

### ISSUE THREAD

**Issue by davivel** [owncloud/core#21855]
To offer the same capabilities than the web UI, native clients need to access the instances of Shares received by the current user. This is important to:
+ Know the maximum permissions the user may set when resharing ; otherwise the UI cannot be adapted dynamically as the web is adapted right now hiding the checkboxes that shouldn't be enabled.
+ Show the identifier of the user that created the share, as the web UI shows.

This could be added as an extension, there is no need to break the API as it is right now.

I would expect that the currently undocumented parameter "shared_with_me" of the GET SHARES request is combinable with the "path" parameter, so that the clients may request the Share instance of a file shared with me only when needed. That granularity is important to grant the synchrony of the information of the server side while keeping the network usage at a minimum. Right now seems that GET SHARES with "shared_with_me" always returns the full list of Shares received by the user, no matter if other parameters are added.

**Comment by rullzer** [comment]
@davivel I had a chat with @ckamm yesterday who was working on it on the desktop client.

What he did so far was: fetch `shares?shared_with_me=true`. Filter out the share for the path you try to share. If there is an entry use the permissions set there.

**Comment by rullzer** [comment]
Combining it with the get parameter is on my todo list... but I first need to finish other sharing stuff..

**Comment by rullzer** [comment]
Also that won't be backwards compatible... so you need to implement the naive way anyway for clients connecting to 8.2 servers

**Comment by davivel** [comment]
Thanks @rullzer . We came to a different work around in mobile. Instead of setting automatically maximum permissions, we set minimum if the file is being reshared. This way the share itself works, and the user may edit the permissions later. The error from the server if the users tries to give excessive permissions is much easier to understand in this case, because it's explicitly setting them in the UI.

We explored the solution of ```shared_with_me```, but we don't think it's acceptable for mobile devices. We receive a list of shares very long to find just one of them, and we have to consider the user could be accessing to the server through radio, not through wifi.

**Comment by PVince81** [comment]
So 9.1 ?

**Comment by rullzer** [comment]
@PVince81 yes lets set it to 9.1. Other stuff to focus on for 9.0

**Comment by davivel** [comment]
:+1:

**Comment by rullzer** [comment]
@davivel for 9.0 there is already a path variable that can be passed to shared_with_me=yes so that should work out...

**Comment by davivel** [comment]
Thanks, will check it today.

**Comment by davivel** [comment]
Checked, this works for us: "GET shares?path=[path]&shared_with_me=true" returns the shares received by my current user **only** for the file set in path.

Does it mean that will be finally in 9.0 instead of 9.1 ?

**Comment by rullzer** [comment]
it will be in 9.0.

**Comment by rullzer** [comment]
It was a small fix. And it fixed a bug in the webui...

**Comment by davivel** [comment]
Then I will dare to update the milestone ;) .

And it's fixed for us. Thanks.
