### ISSUE TITLE
Nightly packages out of date

### ISSUE THREAD

**Issue by tflidd** [owncloud/core#21865]
I have a testing setup where I use the nightly repo. Back in november, the OC 9.0 pre-alpha packages were installed:
`9.0 pre alpha (daily) Build:2015-11-17T05:31:22+00:00 5ec64c4fd7f087027ef945c4d694de1d90bbd814`

Now the repository contains OC 8.1:
http://download.owncloud.org/download/repositories/nightly/Debian_8.0/

**Comment by karlitschek** [comment]
@jnweiger @dragotin Please have a look

**Comment by jnweiger** [comment]
Our ce:nightly project appears to be broken. Even in a broken state it should remain where it was and not travel back in time. I'll investigate.

**Comment by jnweiger** [comment]
The ce:nightly project should be filled in by some jenkins job. Curently the status says:

 Jenkins @ ownbrander (jenkins) committed about 1 month ago (revision 69)
Update by Mr. Jenkins nightly build.

**Comment by jnweiger** [comment]
@danimo I can hotfix the docker container running at rotor. Do you know how to add wget to the image?

**Comment by jnweiger** [comment]
@tflidd http://download.owncloud.org/download/repositories/nightly/Debian_8.0/ has version 9.0pre~alpha.20160127 now.

**Comment by tflidd** [comment]
Thanks a lot. Slowly it gets interesting, what you guys figured out for 
OC 9.0 ;-)
