### ISSUE TITLE
Cant delete "lib" folder

### ISSUE THREAD

**Issue by ianklemm** [owncloud/core#21867]
Hello
The "lib" folder is not Deletable as a web user, other folders of the Owncloud instance already.
Apache 2.4 under FCGID is used.
The newest Owncloud version is used.
Is it a bug?

**Comment by RealRancor** [comment]
Folder not removable at file system level -> not a bug in ownCloud

As you already have asked at https://forum.owncloud.org/viewtopic.php?f=36&t=32664 for support you can close here.

**Comment by ianklemm** [comment]
All the other folder are deletable. The same thing is happening on other server.

**Comment by ianklemm** [comment]
So I speak of the "lib" folder of the Owncloud instance, not the of the file system.

**Comment by RealRancor** [comment]
The "lib" folder of the ownCloud instance is on your file system. Honestly, the bugtracker here is not the right place for giving support for issues like this.

**Comment by ianklemm** [comment]
I think you know what i mean

**Comment by Xenopathic** [comment]
It appears you have a configuration issue, please see https://owncloud.org/support for appropriate support.
