### ISSUE TITLE
Differentiate between users with same display name in search results

### ISSUE THREAD

**Issue by scolebrook** [owncloud/core#21861]
When searching for someone in the share dialog only the one attribute is displayed in the search results. For LDAP this is the displayname. If two or more users have the same displayname, which would be a common occurrence in a large organization, there is no way to tell one person from another. Having the option to display a second attribute, such as email address, would be helpful for users to ensure they're sharing with the correct individual. For the ldap backend, this attribute should be configurable.

This then should available in the searching api used by the apps. See https://github.com/owncloud/ios/issues/564

@MTRichards

**Comment by LukasReschke** [comment]
@scolebrook Can you check if https://github.com/owncloud/core/pull/21834 would help you?

**Comment by MTRichards** [comment]
thanks

If we only offer email address, is this good enough for now? Basically the same question as @LukasReschke

**Comment by scolebrook** [comment]
It's a start. But I think having the ability to specify which attribute is used would be very useful. If a subset of users in the directory need to have their email address kept private for some reason, this solution is unsuitable.

But if an admin can specify a specific attribute for this purpose, they can either use an empty attribute and populate it as needed by script. Or pick another attribute that can be used to differentiate users depending on what they put in their directory.

**Comment by blizzz** [comment]
@scolebrook may I assume this is fulfilled with  https://github.com/owncloud/core/pull/22102?

**Comment by butonic** [comment]
Secondary displayed fixes this
