### ISSUE TITLE
Add batch scan option to the occ files:scan command [patch to 8.2.2 attached]

### ISSUE THREAD

**Issue by Yetangitu** [owncloud/core#21868]
The _occ files:scan_ command currently lacks the option to scan more than one specified file or directory from the command line, the only options are 'for user X (and Y and Z)', 'all files' and 'this path'. I propose adding an additional option: 'the paths listed in this file', allowing a single invocation of the command to scan a distinct multiple of files without needing multiple invocations (which would be slow) or resorting to recursive directory scans (which, depending on the size of the scanned directory, would be even slower).

The use case for this option is closely tied to another weakness in Owncloud: the absence of _inotify_-based metadata-synchronisation on the server. Files which are changed in external local mounts are only picked up on the next full scan. A full scan of a large file system is prohibitively expensive, especially when compared to scanning a single file.

An example of this can be seen when using the _files_opds_ app (which provides an OPDS service for Owncloud-hosted content) linked to an externally mounted library. This library is mounted as an external local mount in Owncloud and is available to all users. Publications are added to the library by the librarian, but they only become available to Owncloud users after doing either a full scan - which can take a long time given the size of the library (more than half a million publications, > 600GB) or when new or changed publications are 'manually' scanned using _occ files:scan -p /user/files/Library/path/to/publication_ - tedious at best. The solution is obvious: use _inotify_ to watch the directory and do targeted scans of new/changed/deleted files. As publications sometimes are added in batches, this would lead to a large number of _occ_ invocations to scan each individual file, or to unnecessarily expensive recursive directory scans to pick up a single changed file. Adding a batch scan option to _occ_ enabled me to cut down on this waste of resources while simultaneously making sure the latest changes to the library are available to Owncloud users in more or less real-time.

Attached is a patch to Owncloud core ([occ-path_list.patch.txt](https://github.com/owncloud/core/files/102026/occ-path_list.patch.txt), applies against OC core 8.2.2). It implements a new option: _--path_list|-l "..."_ which expects a path to a file containing one path per line to scan. This file can be produced by tools like _inotifywait_ and fed to _occ_ periodically, an example script ([oc-watch.txt](https://github.com/owncloud/core/files/102032/oc-watch.txt)) implementing such a scheme is attached to this message.

While the best solution would be for Owncloud to implement _inotify_-based (or a functionally similar system based on _FSEvents_ or _fam_ for non-Linux hosts) external storage monitoring, the combination of an external _inotify_-based daemon and the batch scan option does solve most of the problems related to the lack of external local storage synchronisation.

**Comment by PVince81** [comment]
@Yetangitu mind sending this patch as a pull request against master ?
See https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#contributing-to-source-code and https://doc.owncloud.org/server/8.2/developer_manual/bugtracker/codereviews.html#how-will-it-work

Will the "SplFile" calls work on any setup or does it require specific PHP modules to be installed ?

**Comment by PVince81** [comment]
Regarding inotify and external storage change detection, see this ticket https://github.com/owncloud/core/issues/11797 that discusses its trickiness

**Comment by Yetangitu** [comment]
WRT applying it against master, that would need a bit of rewriting as this part of OC has changed quite a bit since 8.2 - hence the patch. I'll see what I can do in that respect, one of these days.


WRT the pitfalls of inotify I don't see the problem. This command extension does not depend on the notification mechanism, it just consumes lists of files to scan. For local storage change notification on Linux, inotify is the most suitable mechanism with the example script I added being one potential implementation of such. For other types of storage this does not apply, other mechanisms would need to be used to generate change lists. For OSX hosts probably FSEvents is the mechanism to use, although it does seem to have drawbacks compared to inotify.

Given the nature of these change monitors - some of which will need to be on watch continuously (eg. inotify/fam/FSEvents-based, ...), others need to be invoked regularly (Dropbox, S3, ...) - it makes sense to separate the gathering of change data from the scanner. For that to work, the scanner needs to have an efficient way to execute batch scans. As to whether this should be done through occ or through some api? The latter is more Owncloud-y, the former probably faster...

**Comment by Yetangitu** [comment]
https://github.com/owncloud/core/pull/21924

**Comment by Yetangitu** [comment]
As hinted to in https://github.com/owncloud/core/issues/21868#issuecomment-175003783, another way to implement batch scanning would be to add an option to the files api. Before I go off in some tangent and hack together something to implement this it would be enlightening to know whether there are plans to standardise on any one-and-only scheme for implementing external api's for Owncloud. Currently this seems to be all over the place, with apis popping up on different locations using different url schemes.

**Comment by Yetangitu** [comment]
Pull request for an experimental implementation of a scan api:

https://github.com/owncloud/core/pull/21984
