### ISSUE TITLE
Make the mention of app licenses translation-friendly

### ISSUE THREAD

**Issue by zinks-** [owncloud/core#21874]
https://github.com/owncloud/core/blob/master/settings/templates/apps.php#L65

```php
({{licence}}-<?php p($l->t('licensed')); ?>)
// EN: AGPL-licensed
// FR : AGPL-sous license
```
The French version is not proper.
We should be able **to change the order of the words** : "sous license AGPL"

Other languages probably have this issue too
Thank you

**Comment by MorrisJobke** [comment]
Fix is in https://github.com/owncloud/core/pull/21878
