### ISSUE TITLE
Owncloud doesn't handle .odt files correctly

### ISSUE THREAD

**Issue by pollti** [owncloud/core#21870]
### Steps to reproduce
1. Create an owncloud account with an .odt file in any repo.
2. Open the file by visiting <server>/index.php/apps/documents/ and add any content. (not necessary)
3. Go back to <server>/index.php/apps/files and open the file by clicking on the file's name.

### Expected behaviour
The editor should open or the content should be shown correctly

### Actual behaviour
The editor doesn't open and character encoding doesn't work as expected (owncloud tries to show the file's source code)..

**Comment by RealRancor** [comment]
@pollti The issue tracker of the documents app is located here: https://github.com/owncloud/documents/issues

Please re-open there using the complete issue template (currently even the oC and documents app you're running is missing).

**Comment by pollti** [comment]
Thanks @RealRancor.
