### ISSUE TITLE
opcache creates problems for Windows sync app

### ISSUE THREAD

**Issue by stephengraf** [owncloud/core#21876]
I have discovered that when opcache is enabled the Windows sync app has connection problems.

I can take out opcache by removing opcache.ini and the app has no problems.  When I put the 
opcache.ini file back to enable opcache, the errors start again.  .

I ran with opcache enabled on openBSD 5.7, php 5.5 and ownCloud 8.1.5 with sync app 2.1.0 for quite a while without problems.  This problem has only happened since I upgraded to openBSD 5.8, php 5.6 and ownCLoud 8.2.2.

In my testing I went back to the sync app ver 1.8.5, which ran properly with opcache enabled.  Ver 2.0.0 and up exhibited the problem.

I had to create a http server in the web server to be able to see the packets.  In normal operation https is used.  I traced the packets using Wireshark.  The raw packet trace indicated that there was a split packet when the error was occurring.  The web server saw the first part of the packet and replied.  When the second part came through, which was after the web server replied to the first part, the web server saw an unrecognizable packet, returned a 400 error message with the "Bad Request" message that the sync app displays and then the web server closed the connection.

How opache on the server can create this is beyond me!

### Steps to reproduce
1. Enable php opcache module
2. 
[opcache]
; Determines if Zend OPCache is enabled

opcache.enable=1

; Determines if Zend OPCache is enabled for the CLI version of PHP
opcache.enable_cli=1 

### Expected behaviour
Windows sync app should work

### Actual behaviour
Windows sync app stops connecting and shows a "Bad Request" error.

### Server configuration
**Operating system**:
openBsd 5.8

**Web server:**
OpenBSD httpd

**Database:**
mysql (Mariadb)

**PHP version:**
5.6

**ownCloud version:** (see ownCloud admin page)
8.2.2

**Updated from an older ownCloud or fresh install:**
Manual update from 8.1.5

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### LDAP configuration (delete this part if not used)
n/a
```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
Edge

**Operating system:**
Windows 10
Sync app ver 2.1.0

#### Web server error log
```
Insert your webserver log here

Nothing showing in error logs

192.168.1.10 192.168.1.61 - - [23/Jan/2016:16:59:50 -0800] "GET /status.php HTTP/1.1" 200 0
192.168.1.10 192.168.1.61 - - [23/Jan/2016:16:59:50 -0800] "GET /remote.php/webdav/ HTTP/1.1" 401 0
192.168.1.10 192.168.1.61 - - [23/Jan/2016:17:00:00 -0800] "PROPFIND /remote.php/webdav/ HTTP/1.1" 401 0
192.168.1.10 192.168.1.61 - - [23/Jan/2016:17:00:00 -0800] "<UNKNOWN> " 400 0


#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
No entries for this problem

#### Browser log
```


```
Wireshark log
The packet log for wireshark shows that there is a split message when the errors occur.  This does not happen when opcache is not enabled and the app is working properly.

Packet from sync app that got split.

PROPFIND /remote.php/webdav/ HTTP/1.1
Depth: 0
User-Agent: Mozilla/5.0 (Windows) mirall/2.1.0
Content-Type: text/xml; charset=utf-8
Cookie: ocd4dc1c1402=u18ca5i6nb3ip157mkmfb3nu55; 
oc_sessionPassphrase=sS0VSShVpXGJPhzVxeQJnC2xLUybJI5zhFSWNrm1GLjii%2FelAE2XKb5FZWB616HdQqgiUNizsjDwN9KJ7XHof99omsi9fvZSovzhfTf1EqMEgClRdJPAqFdBqaseJ8Lg
Content-Length: 114
Connection: Keep-Alive
Accept-Encoding: gzip, deflate
Accept-Language: en-US,*
Host: 192.168.1.10:8080

The xml code is missing and comes after the webserver replies.

Reply from server.

HTTP/1.1 401 Unauthorized
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Connection: keep-alive
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *
Content-Type: application/xml; charset=utf-8
Date: Sun, 24 Jan 2016 01:00:00 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Pragma: no-cache
Server: OpenBSD httpd
Transfer-Encoding: chunked
WWW-Authenticate: Basic realm="ownCloud"
X-Content-Type-Options: nosniff
X-Frame-Options: Sameorigin
X-Powered-By: PHP/5.6.11
X-Robots-Tag: none
X-XSS-Protection: 1; mode=block

f2
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
  <s:message>No basic authentication headers were found</s:message>
</d:error>
0

The following lines of xml should be part of the first packet from the sync app.

<?xml version="1.0" ?>
<d:propfind xmlns:d="DAV:">
  <d:prop>
   <d:getlastmodified />
  </d:prop>
</d:propfind>

Next packet from sync app.

PROPFIND /remote.php/webdav/ HTTP/1.1
Depth: 0
User-Agent: Mozilla/5.0 (Windows) mirall/2.1.0
Content-Type: text/xml; charset=utf-8
Cookie: ocd4dc1c1402=u18ca5i6nb3ip157mkmfb3nu55; 
oc_sessionPassphrase=sS0VSShVpXGJPhzVxeQJnC2xLUybJI5zhFSWNrm1GLjii%2FelAE2XKb5FZWB616HdQqgiUNizsjDwN9KJ7XHof99omsi9fvZSovzhfTf1EqMEgClRdJPAqFdBqaseJ8Lg
Content-Length: 114
Connection: Keep-Alive
Accept-Encoding: gzip, deflate
Accept-Language: en-US,*
Host: 192.168.1.10:8080
Authorization: Basic dGVzdHByb2Q6Z2luZ2VyYWthMjM=

<?xml version="1.0" ?>
<d:propfind xmlns:d="DAV:">
  <d:prop>
    <d:getlastmodified />
  </d:prop>
</d:propfind>

Reply from server because of xml code.

HTTP/1.0 400 Bad Request
Date: Sun, 24 Jan 2016 01:00:00 GMT
Server: OpenBSD httpd
Connection: close
Content-Type: text/html
Content-Length: 362

<!DOCTYPE html>
<html>
<head>
<title>400 Bad Request</title>
<style type="text/css"></style>
</head>
<body>
<h1>400 Bad Request</h1>
<hr>
<address>OpenBSD httpd</address>
</body>
</html>

**Comment by karlitschek** [comment]
this sounds like a setup/bsd specific problem in combination with opcode caching. Nothing we can do from inside ownCloud because ownCloud is only php which can influence the opcode caching directly. Please report to the opcode cache developer or look at owncloud.org/support. thanks

**Comment by stephengraf** [comment]
I doubt that the problem is with opcache or openBSD.  The rest of Owncloud works well with opcache enabled, including syn from my android phone via caldav and carddav, WebDAV from Outlook to publish calendars and the ownCloud Windows sync app version 1.8.5.  It is only the ownCloud sync app from version 2.0.0 and up that are failing with opcache enabled. It seems very weird as I cannot see how opcache can affect what the client is sending.

Please consider opening this issue again, maybe as a sync app problem.

**Comment by RealRancor** [comment]
@stephengraf Have raised https://github.com/owncloud/core/issues/22117
