### ISSUE TITLE
Don't check for .htaccess if you're not using Apache.

### ISSUE THREAD

**Issue by ZacharyDuBois** [owncloud/core#21875]
Seriously, checking for `.htaccess` in the CLI client is horrible. Please stop because you can't just assume everyone uses Apache. And the people that use Apache should be smart enough to disable the htaccess module because it kills your disk and slows everything down.

```
zacharydubois@AmiKawashima:/srv/http/owncloud/public$ sudo -u oc-fpm php occ upgrade
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug - current level: 'Warning'
Exception: .htaccess file has the wrong version. Please upload the correct version. Maybe you forgot to replace it after updating?
Update failed
Maintenance mode is kept active
Reset log level to 'Warning'
```

If I get the chance, I will go through and get rid of all htaccess crap in the near future.

**Comment by RealRancor** [comment]
How should php-cli know it is not running apache? The only chance is to add another config option to the config.php which looks a little bit overkill to me.  Just upload the .htaccess file  and you're fine as other web servers won't use it anyway.

**Comment by ZacharyDuBois** [comment]
The point I am making is even if you're using apache, you shouldn't be using htaccess files.

**Comment by RealRancor** [comment]
Have you though about the oC users out there not having access to their webservers config?

**Comment by ZacharyDuBois** [comment]
Yes, but they have a separate web installer. Create the access files in the web installer instead of using it for everything and then doing checks for it when nearly any sysadmin that knows that htaccess is a complete joke.

**Comment by RealRancor** [comment]
Web installers won't have access to the main apache config. There is a lot of stuff in the htacces which can't or shouldn't be done from PHP.

 If oC wants to support more than the users having access to their apache config then their is no way around htaccess. And everyone else just can disable htaccess and move the stuff into their main webservers config like its already done with the provided nginx config.

**Comment by ZacharyDuBois** [comment]
My point is everything inside the htaccess can be put in the Apache config. Nowhere did I say that it should be left to PHP. During installation, you can prompt the user to either allow OC to create the htaccess files (if Apache) or give a paste-able config block for a virtual host configuration. Running htaccess is a thing but secure. 9/10 people using htaccess have them set so the web user can write to them creating more security issues than it solves.

**Comment by ZacharyDuBois** [comment]
The other point about the CLI would be not to assume everything is Apache (or even assume a web server for that matter) and then just exit if one htaccess isn't found. No override is provided for that. There are tons of other web servers out there. They're basically a dime a dozen now. For example, running Apache on a Raspberry Pi would be stupid because of the file operations. People would settle for something like lighttpd.

**Comment by DeepDiver1975** [comment]
> Exception: .htaccess file has the wrong version. Please upload the correct version. Maybe you forgot to replace it after updating? Update failed

How to you get to this error? You killed .htaccess?

**Comment by ZacharyDuBois** [comment]
My deploy for applications does a standard `unzip` and `mv`. By default, `mv` will not move hidden files. So by default, the root htaccess was not moved.

**Comment by DeepDiver1975** [comment]
> So by default, the root htaccess was not moved.

and this is the failure in your installation method -> case closed

**Comment by karlitschek** [comment]
@ZacharyDuBois We can only support ownCloud if you use it in the way it is documented and packaged. Any other hack is a hack and nothing we can fix.

**Comment by ZacharyDuBois** [comment]
I was bringing up a statement on security and promoting proper configuration and environment testing. htaccess should not be included in CLI checks and should only be included in web checks if the HTTPd is Apache and htaccess is enabled.

**Comment by DeepDiver1975** [comment]
> htaccess should not be included in CLI checks and should only be included in web checks if the HTTPd is

deploying htaccess is part of out delivery - not properly deploying is a sign of setup issue which we are notifiing the admin about in any case

**Comment by ZacharyDuBois** [comment]
Then there should at least be an override option. You are still missing the point.

**Comment by RealRancor** [comment]
I think you're missing the point. An advanced admin can still disable .htaccess files. Furthermore non-apache servers are just not using .htaccess at all so there is no security implications when shipping a .htaccess.

Make differences between apache, non-apache and cli just makes things complicated without any benefits.

**Comment by DeepDiver1975** [comment]
> Then there should at least be an override option. You are still missing the point.

TBH: simply deploy .htacces and you are done - no need for any additional config switch

**Comment by ZacharyDuBois** [comment]
Why not just remove the validation/check from the CLI. It will be obvious to the apache users that they forgot it when they load the page. Odds of those users is they will use the web updater too.

**Comment by DeepDiver1975** [comment]
Because we want to Informationen the user about all issues in all scenarios.

Imagine how anoying it is to get some warnings/notifications when execue cli others on the web and again others when running cron script .....
... Or just show them *if possible* in any case.

This is to help and support admins where ever we can.
