### ISSUE TITLE
Thumbnails, libjpeg: recoverable error: Invalid SOS parameters for sequential JPEG

### ISSUE THREAD

**Issue by rajil** [owncloud/core#21873]
Hello,

I have some photos taken from a phone which render fine in gwenview and gimp, but give an error in owncloud. The errors I get in the owncloud.log file is
"imagecreatefromjpeg(): gd-jpeg, libjpeg: recoverable error: Invalid SOS parameters for sequential JPEG"

The web UI is unable to show the thumbnail.
The relevant packages i have installed are php56-gd-5.6.17 and jpeg-turbo-1.4.2

Google returned this
golang/go#3916
https://code.google.com/p/go/issues/detail?id=3916

**Comment by MorrisJobke** [comment]
> golang/go#3916

With the image that is linked there I can reproduce the error:


```
{"reqId":"vFZDhvb9KbRyDLVYHRnt","remoteAddr":"::1","app":"PHP","message":"imagecreatefromjpeg(): gd-jpeg, libjpeg: recoverable error: Invalid SOS parameters for sequential JPEG\n at \/Users\/morrisjobke\/Projects\/owncloud\/master\/lib\/private\/image.php#515","level":0,"time":"2016-01-25T08:26:49+00:00","method":"GET","url":"\/master\/index.php\/core\/preview.png?file=%2Fasd%2Fxx.jpg&c=1338e8260789f433aefdda62641e5109&x=64&y=64&forceIcon=0"}
```

**Comment by MorrisJobke** [comment]
Workaround: 
```
ini_set ('gd.jpeg_ignore_warning', 1);
```

See http://php.net/manual/en/image.configuration.php

cc @oparoz

**Comment by oparoz** [comment]
Thanks @MorrisJobke . It had already been added to Gallery(+), but would be good to have it enabled in `core`. Where though?

**Comment by LukasReschke** [comment]
I'd advocate for https://github.com/owncloud/core/blob/308396b770f3b1b41ba31ff0ee889d485b14d14a/lib/base.php#L471-L476. Any objections?

**Comment by oparoz** [comment]
Sounds good to me :)

**Comment by LukasReschke** [comment]
=> https://github.com/owncloud/core/pull/21950
