### ISSUE TITLE
[9.1] drop old calendar and contacts tables

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#21889]
With 9.0 we will migrate conatcts and calendar data over to the new core tables.
I don't want to run into the situation where we fail to execute the migration and delete the tables in 9.0.

Therefore we drop the tables with 9.1

clndr_calendars
clndr_objects
clndr_share_event
clndr_share_calendar
clndr_repeat

contacts_addressbooks
contacts_cards

**Comment by karlitschek** [comment]
makes sense

**Comment by rullzer** [comment]
* And a cleanup script to remove all the shared contacts and calendar stuff from the oc_share table.

**Comment by DeepDiver1975** [comment]
> And a cleanup script to remove all the shared contacts and calendar stuff from the oc_share table.

**Comment by rullzer** [comment]
I can take care of that final step.
Assiging to myself so I don't forget.

**Comment by DeepDiver1975** [comment]
@rullzer THX - as you wish - please use repair steps as introduced with https://github.com/owncloud/core/pull/24199

**Comment by ho4ho** [comment]
Missed contacts_cards_properties removing: https://github.com/owncloud/core/issues/35720, https://github.com/nextcloud/server/pull/157
