### ISSUE TITLE
encryption_migration_backup_<TIMESTAMP> directories in user data

### ISSUE THREAD

**Issue by hostingnuggets** [owncloud/core#21882]
Hello,

After a few upgrades of my now ownCloud 8.2.2 installation with the Encryption App always enabled I noticed that every user has two "encryption_migration_backup_<TIMESTAMP>" (e.g. "encryption_migration_backup_2015-11-28_03-05-18") directories in their data directory. 

Now that all these upgrades went fine can I safely delete manually these directories? or is there a CLI command to do that? What would be the right process here? Unfortunately I could not find any pointers in the documentation about this specific topic.

**Comment by karlitschek** [comment]
i suggest that you ask this question at one of the support places listed on owncloud.org/support. Closing because not an owncloud core bug.
