### ISSUE TITLE
Unicode Support

### ISSUE THREAD

**Issue by ghost** [owncloud/core#21899]
Hi,

As per this thread https://forum.owncloud.org/viewtopic.php?f=4&t=14426 it would be good if unicode support could be added so that the use of emoji's in calendar entries doesn't break CalDAV synchronisation.

Keep up the good work.

**Comment by DeepDiver1975** [comment]
requires https://github.com/owncloud/core/pull/17978

**Comment by DeepDiver1975** [comment]
> requires #17978

@MorrisJobke any update on the dockers for mysql utf8mb4 - THX

**Comment by ben1390** [comment]
Hi,

Would changing the collation type to utf8m4b_bin across all of my database tables be a suitable fix for this or is there more to it?

Many thanks.

**Comment by DeepDiver1975** [comment]
> or is there more to it?

if life would be that easy :wink:

**Comment by DeepDiver1975** [comment]
@ben1390 please follow the conversation on the linked pr to see the necessary changes

**Comment by RealRancor** [comment]
SabreDAV itself is now using utf8mb4 internally since 3.1.0 according to its Changelog:

https://github.com/fruux/sabre-dav/blob/3.1.0/CHANGELOG.md

**Comment by PVince81** [comment]
Closing in favor of this older ticket https://github.com/owncloud/core/issues/4513
