### ISSUE TITLE
After clearing Username-LDAP User mapping and Groupname-LDAP Group mapping, some LDAP groups are displayed with the _2 suffix

### ISSUE THREAD

**Issue by pako81** [owncloud/core#21891]
### Steps to reproduce
1. Configure LDAP without specifying any value for the Internal Username Attribute. LDAP Users are displayed with their UUID
2. Click on Clear Username-LDAP User mapping and Groupname-LDAP Group mapping (since the intention is to use the WND app in combination with the $user variable)
3. Specifiy sAMAccountName as Internal Username Attribute
4. LDAP Users are correctly displayed with their Usernames however for some LDAP groups, group names are then displayed with the _2 suffix (i.e. IT_2, Admin_2 and so on)
5. Also deleting the actual configuration and recreating a new one is not helpful

### Server configuration

**Operating system**:

RHEL 7.1

**Web server:**

Apache 2.4 

**Database:**

MySQL 5.5

**PHP version:**

5.4

**ownCloud version:** (see ownCloud admin page)

8.2.2

**Updated from an older ownCloud or fresh install:**

Updated from 8.2.1

**Are you using external storage, if yes which one:** local/smb/sftp/...

local and external storage

**Are you using encryption:** yes/no

no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

LDAP

This is a test environment therefore Usernames and Groupnames have been cleared up. Is there however a way to have the LDAP group names correctly displayed (without the _2 suffix)? And why is this affecting only some LDAP groups? 

@blizzz can you maybe help here?

00004661

**Comment by blizzz** [comment]
Cannot reproduce with master. Do they have local groups (or groups from somewhere else) with the same name?

**Comment by pako81** [comment]
@blizzz thanks. No, they only have LDAP groups.
After clearing Username-LDAP User mapping and Groupname-LDAP Group mapping, in addition to the sAMAccountName as Internal Username Attribute, they have also overidden UUID detection by specifying sAMAccountName for the UUID Attribute for Users/Groups:

https://doc.owncloud.com/server/8.2/admin_manual/configuration_user/user_auth_ldap.html#expert-settings

This configuration has been however erased and now they only have sAMAccountName as Internal Username Attribute.
Could it be that overriding UUID detection for Groups is the cause for this behaviour..but again why this occurs only for some LDAP groups..

**Comment by pako81** [comment]
any news please?

**Comment by blizzz** [comment]
1. The cleared group mappings
2. they set "samaccountname" as UUID attribute for groups 
3. they deleted the configuration
4. they did a new configuration with default UUIDs

That's the order what has happened right?

I believe after 2) they also went to the users page.

This means, groups were read from and mapped from AD. Usually groups in AD do not have a samaccountname attribute, this would result in something empty. Which could cause strange behaviour.

Anyway, it this point of time groups were mapped again and deleting and creating a new configuration does not clear mappings. The mappings are configuration-independent.

Therefore, groups will be mapped again if the already mapped groups and the newly fetched ones do not match in DN or (the configured) UUID. When names clash, a random number is added.

→ Clear group memberships once more.

**Comment by pako81** [comment]
@blizzz thanks.

> The cleared group mappings
they set "samaccountname" as UUID attribute for groups
they deleted the configuration
they did a new configuration with default UUIDs
That's the order what has happened right?

The order is right but these are the correct steps they did:

1. they cleared group mappings
2. they set "samaccountname" as Internal Username Attribute and as UUID Attribute for Users/Groups
3. they deleted the configuration
4. they did a new configuration with "samaccountname" as Internal Username Attribute only

> I believe after 2) they also went to the users page.

correct

> → Clear group memberships once more.

Then based on the steps described above, just clearing the group membership once more should do the trick?

**Comment by blizzz** [comment]
@pako81 thanks for confirming, I left out irrelevant parts, though did not mention it.

> > → Clear group memberships once more.

> Then based on the steps described above, just clearing the group membership once more should do the trick?

Yes

**Comment by pako81** [comment]
@blizzz it indeed did the trick. Many thanks! Please close this.
