### ISSUE TITLE
Creating a folder in Edge via web UI doesn't work

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#21904]
It simply doesn't create the folder and the response to the MKCOL request is "415 Unsupported Media Type":

![bildschirmfoto 2016-01-26 um 10 13 06](https://cloud.githubusercontent.com/assets/245432/12576654/9144e1dc-c415-11e5-82b0-7ddcf6e2b359.png)

A notification with `Could not create folder "asdasb"` pops up. The same works fine in Safari or Chrome.

**Comment by MorrisJobke** [comment]
cc @PVince81

**Comment by MorrisJobke** [comment]
In IE this works just fine.

**Comment by PVince81** [comment]
The call looks wrong, the URL of the MKCOL is supposed to contain the name of the folder too.

**Comment by MorrisJobke** [comment]
Duplicate of https://github.com/owncloud/core/issues/21710

**Comment by MorrisJobke** [comment]
Lets close this here then.
