### ISSUE TITLE
[Files external ] Personal mountpoints. Unchecking the option after configuring a mountpoint does not make disappear the configuration in the personal page.

### ISSUE THREAD

**Issue by davitol** [owncloud/core#21905]
### Steps to reproduce

1. As admin user configure a S3 personal mountpoint  
2. In admin view, in Allow users to mount external storage, uncheck Amazon S3
3. Go to the personal page.

### Expected behaviour

The S3 personal mountpoint configuration should not be shown in the personal page

### Actual behaviour

The configuration of the S3 personal mountpoint is visible in the personal page

Note: The mountpoints are not available in the files view (right behaviour)
 

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 9.0 pre alpha (daily) Build:2016-01-26T04:16:42+00:00 4c9e328211a3f986cd2c6186e4c1de755d5c940b

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** yes; S3.
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox for Mac OSX

![screen shot 2016-01-26 at 09 56 30](https://cloud.githubusercontent.com/assets/10596560/12576437/ebe5d72e-c413-11e5-9939-4e985324c1e7.png)

![screen shot 2016-01-26 at 09 54 42](https://cloud.githubusercontent.com/assets/10596560/12576442/f3c0f834-c413-11e5-8c51-9172855560a4.png)

**Comment by PVince81** [comment]
@icewind1991 @Xenopathic possible regression

@davitol can you confirm whether this is a regression from 8.2.2 ?

**Comment by Xenopathic** [comment]
A quick test shows that while it continues to be displayed in the UI, it correctly does not get mounted, and doesn't display in the files view. This raises an interesting question: do we want to forcefully remove any mount types that have been disabled by the admin (like 8.2 behaviour) or do we want to notify the user that the backend is no longer available by a greyed row or something? Then again, in reality this is something that will happen very rarely, so perhaps just going back to 'forcefully remove' is best, and it's not worth improving.

**Comment by PVince81** [comment]
If this behaves like in the past then we can keep it on sev4-low and think of @Xenopathic's suggestions later.

**Comment by Xenopathic** [comment]
Personally I don't think it will ever be worth improving this beyond the 8.2 behaviour, the only situation where it actually becomes visible is when a user sets up a storage with a given backend, *then* the admin decides they shouldn't be able to mount it. In such cases one would hope that the admin sends out a notification email to their users telling them of the configuration change that is about to occur

**Comment by davitol** [comment]
> If this behaves like in the past then we can keep it on sev4-low

In EE 8.2.2 the behaviour is different. When we uncheck the S3 option, the personal mountpoint disappears from the personal page.
