### ISSUE TITLE
Modification of S3 mountpoint configured values is not been saved

### ISSUE THREAD

**Issue by davitol** [owncloud/core#21903]
### Steps to reproduce

1. As admin user configure a S3 mountpoint  and save it
2. In admin page, try to modify the configuration of the mountpoint

### Expected behaviour

~~The configuration cannot be edited after saving the mountpoint~~
The values should be modified and saved

### Actual behaviour

The values can be edited, but they are not saved. So no changes can be done.

~~It seems that it can be possible to edit values as the bucket or the access key of a saved mountpoint.~~
~~Note: The original values are kept, no changes are saved (Right behaviour)~~

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 9.0 pre alpha (daily) Build:2016-01-26T04:16:42+00:00 4c9e328211a3f986cd2c6186e4c1de755d5c940b

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** yes; S3.
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome Version 47.0.2526.111 (64-bit) for Mac OSX

**Comment by PVince81** [comment]
I don't understand. Which values should not be changeable ?

**Comment by davitol** [comment]
the bucket id, the key ....
After saving the mountpoint, should this values be changed? If the answer is yes, then the problem is that those modifications are not been saved

**Comment by PVince81** [comment]
Usually you can edit all values, so the bug is then that they aren't saved properly.

**Comment by davitol** [comment]
Ok, so let's change the issue title and the sev.

**Comment by PVince81** [comment]
Works for me on master / 9.1.0.

Changing the bucket name and leaving the field properly saves the value on an existing config, even after refreshing the page.
