### ISSUE TITLE
Cannot edit a text file in a S3 mountpoint

### ISSUE THREAD

**Issue by davitol** [owncloud/core#21902]
### Steps to reproduce
1. As admin user configure a S3 mountpoint  
2. Edit a .txt file located in the mountpoint
### Expected behaviour

The text can be opened and edited
### Actual behaviour

An error is shown when we try to open the file

Note: Edition of text files located in other S3 buckets works fine. 
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 9.0 pre alpha (daily) Build:2016-01-26T04:16:42+00:00 4c9e328211a3f986cd2c6186e4c1de755d5c940b

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** yes; S3.
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Chrome Version 47.0.2526.111 (64-bit) for Mac OSX

![screen shot 2016-01-26 at 09 07 57](https://cloud.githubusercontent.com/assets/10596560/12575510/48071e52-c40d-11e5-8dc8-648e1c3c338d.png)

``` "reqId":"EVnl4Fig45zWNJyDAZ4E","remoteAddr":"82.159.139.58","app":"no app in context","message":"Encryption module defined in \"hola.txt\" not loaded!","level":3,"time":"2016-01-26T08:07:53+00:00"
{"reqId":"Sx6qwKTfIg20YHbO34IM","remoteAddr":"82.159.139.58","app":"no app in context","message":"Encryption module defined in \"hola.txt\" not loaded!","level":3,"time":"2016-01-26T08:08:09+00:00"}
```

**Comment by PVince81** [comment]
This more looks like a problem with encryption.
Does it work without encryption ? Do you have to refresh the page to make the file editable after creation ?

**Comment by PVince81** [comment]
@davitol still an issue ?

**Comment by PVince81** [comment]
Please reopen if issue persists with 10.0.4.

Maybe you had an old encrypted file from a former test there
