### ISSUE TITLE
Sharing files/folders which are located on a CIFS/SMB share and authenticated via session credentials are not supported

### ISSUE THREAD

**Issue by p5ych017** [owncloud/core#21918]
OS: Ubuntu Server 14.04 LTS
OC: 8.22
PHP: 5.5

Is it possible to extend the external storage plugin to support sharing of files/folders which are located
on a CIFS/SMB share and authenticated via session credentials?

Maybe a possible solution:
Add another user/password field to the external storage configuration page, if session credentials enabled to define a user which has full-access on the share.
Use this account to share files via a link.

I'm very unhappy to see, that this is not possible atm.
We don't want to pump all our files into OC. We just want to use it as a gateway for
our existing fileserver. 

LDAP and NTFS rights are working fine!
I don't know what to do with the sharing of files on SMB with session enabled! HELP!

![oc2](https://cloud.githubusercontent.com/assets/15014519/12582025/b1310758-c43a-11e5-971b-1b5cb8a9d05f.jpg)

![oc1](https://cloud.githubusercontent.com/assets/15014519/12581939/3787e034-c43a-11e5-8a67-70298921db6a.jpg)

**Comment by Xenopathic** [comment]
As is noted in the [documentation](https://doc.owncloud.org/server/8.2/admin_manual/configuration_files/external_storage/auth_mechanisms.html#password-based-mechanisms), this is by design to improve security: the oC server never directly stores the username and password. With 9.0 a new authentication mechanism, Login Credentials, will be available which stores the login user credentials in the database and keeps them updated.

**Comment by p5ych017** [comment]
But it's already defined if I use "Username and password" authentication !?

Just to clarify:
If I select "Session credentials", OC should use an additionally defined user and password in the configuration only for the sharing mechanism. The session ticket of the current user, which would share something is neither cached nor stored in the db or somewhere else on the server. OC should use a dedicated user only for the sharing mechanism.

**Comment by p5ych017** [comment]
That's really sad, because the sharing is one of the core features of OC!

**Comment by p5ych017** [comment]
Example:
User is logging in with it's LDAP credentials (session credentials) and would share a file, which is accessible for him.
OC will then just take the path to share and use the additionally dedicated user in the configuration to share it. Not the session credentials!

Can you label as discuss?

**Comment by p5ych017** [comment]
Example:
User is logging in with it's LDAP credentials (session credentials) and would share a file, which is accessible for him.
OC will then just take the path to share and use the additionally dedicated user in the configuration to share it. Not the session credentials!

Can you label as discuss?

**Comment by Xenopathic** [comment]
If you select 'Session credentials', you are explicitly stating that you only want credentials to be stored in the session, for extra security, such that the ownCloud server does not save the credentials to disk at any point, preventing sharing. If you want an 'additionally defined user and password ... only for the sharing mechanism' then you are giving ownCloud credentials that it saves to the database, removing the security benefits of session credentials entirely. In fact, there's no point in even storing credentials in the session in this case: ownCloud already has the credentials in the DB!

Use session credentials when you want security at the cost of losing sharing capability. Use username and password when you have a storage that is always accessed with a single set of credentials, and the ownCloud server can securely store them.

**Comment by p5ych017** [comment]
Okay, I understand!

But it would be great, if there will be a checkbox to enable this "mixed authentication" for the
users who need this feature. Maybe with a short information, that this feature will reduce security.

Our problem is that we have to set up two additional OC systems if it's not possible in any other way.
One for our users to work with it and another one just to use the sharing mechanism with our customers and partners. I think they don't realize, why they have to change the system!
The benefit of the session authentication is, that every user has only access to the files, he is entitled for in the NTFS permissions.

**Comment by Xenopathic** [comment]
My point is, this 'mixed authentication' you are talking about is completely identical to just using the provided username and password directly. You talk about leveraging NTFS permissions - it's not secure at all, since a user could simply share the storage with themselves or another accomplice, who then has access to the storage with the provided credentials - completely bypassing any NTFS permissions you have in place.

**Comment by p5ych017** [comment]
It's not 100% secure....that's clear! But every user have to be careful with the files he has access to. And that's what is really important. I think it's a difference, if someone has access to every file and he doesn't care about those, which are not important for himself, but interesting to someone else! Otherwise everyone knows what's happening, if somebody with a usb stick is around the house.
