### ISSUE TITLE
Update sabre/dav to 2.1.9 and sabre/vobject to 3.5.0 for PHP7 compatibility

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#21914]
Just a short pointer as this was requested in https://github.com/owncloud/calendar/issues/1002

sabre/dav 2.1.9 including sabre/vobject 3.5.0 was released yesterday which should bring PHP7 compatibility into oC 8.x when updating to this release:

http://sabre.io/blog/2016/sabre-dav-2.1.9-release/

**Comment by rullzer** [comment]
Backporting 3rdparty updates is basically asking for troubles. Since so much can go wrong.

For 9.0 we are on 3.0.7 https://github.com/owncloud/3rdparty/blob/177daad35de835dafacc6e84f09e6335cc229a75/composer.json#L39

**Comment by DeepDiver1975** [comment]
> Backporting 3rdparty updates is basically asking for troubles. Since so much can go wrong.

yes - but 2.1.9 was basically released for us to fix ownCloud 8.2.x on php7 :wink:

**Comment by nblock** [comment]
+1

**Comment by rullzer** [comment]
@DeepDiver1975 ah ok... well then... let me prepare a 3rdparty update for 8.2... and pray nothing breaks...

**Comment by RealRancor** [comment]
@rullzer For sabre/vobject one compatibility breaking issue was introduced:

http://sabre.io/blog/2016/sabre-vobject-3.4.9-and-3.5.0-release/

No idea if the renamed classfiles are used within oC.

**Comment by DeepDiver1975** [comment]
> No idea if the renamed classfiles are used within oC.

not as far as I'm aware of - we use vobjects 3.5.0 in master as well

**Comment by rullzer** [comment]
PR in https://github.com/owncloud/core/pull/21938 please test

**Comment by redhell** [comment]
#21938 works perfectly (Mac/iOS and Web)

PHP 7.0.2 w/MariaDB 10.1, redis

**Comment by rullzer** [comment]
PR is in => Closing
