### ISSUE TITLE
Every time files are downloading in Windows Client!

### ISSUE THREAD

**Issue by kantakt2** [owncloud/core#21917]
I use my own sabreDAV  - web - server.
And files are fetching every login in own cloud.
Only when I use ETAg  - like "56a64a3b0aba3" - for All nodes - it not downloading. But also not updating what I need...
May be you can see place in ownCloud - where ETag is generating...

**Comment by RealRancor** [comment]
@kantakt2 Please use the issue template provided here:

https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version

as asked in the "guidelines for contributing" (linked in the yellow box when creating a new issue). Currently your posted issue contains nearly zero information about your issue.
