### ISSUE TITLE
Rewording of credentials dropdown in external storage.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#21911]
A change is needed from "session credentials" and "login credentials" to "login credentials, save in session"  and "login credentials, save in DB"

**Comment by SergioBertolinSG** [comment]
As discussed @PVince81

**Comment by PVince81** [comment]
@MTRichards @jancborchardt what do you think ?

Ref: https://github.com/owncloud/core/issues/16305#issue-75765206

**Comment by MTRichards** [comment]
Yes. The login credentials / session credentials is not too descriptive. Should be:

Login credentials, store in session
Login credentials, store in DB

@jancborchardt thoughts?

**Comment by jancborchardt** [comment]
Is that understandable? How about a bit simpler and less technical:

> Credentials, store temporarily
> Credentials, store permanently

(Btw, »Log in« is 2 separate words.)

**Comment by PVince81** [comment]
Probably not technical enough. At least for an admin.
For a regular non-admin user it might be fine.

**Comment by jancborchardt** [comment]
Then

> Credentials, store in session
> Credentials, store in database

**Comment by SergioBertolinSG** [comment]
If there are global credentials, specifying that these are about login is important.

Not english native here, but seems to be a word http://www.oxforddictionaries.com/definition/english/login

**Comment by PVince81** [comment]
Let's clarify a bit, I was also confused just a minute ago.

According to https://github.com/owncloud/core/issues/16305#issue-75765206 we have three modes:
- "Login credentials, store in session" => the login credentials are captured at login time then stored (no popup)
- "Login credentials, store in database" => the login credentials are captured at login time then stored (no popup)
- "User entered" (stored in database) => the user gets a popup when clicking on the entry, creds are stored in database

So it might be important to be able to distinguish between "Login" credentials and "User".

Is the word "Credentials" when used alone already to be understood as the user's login ?

**Comment by jancborchardt** [comment]
Ok, sounds fine to me then. Except »Login« -> »Log in«.

**Comment by MTRichards** [comment]
>"Log in credentials, store in session" => the login credentials are captured at login time then stored (no popup)
>"Log in credentials, store in database" => the login credentials are captured at login time then stored (no popup)
>"User entered" (stored in database) => the user gets a popup when clicking on the entry, creds are stored in database

For parallel reasons, I would make the last one "User entered, store in database"

Otherwise ok for me.

**Comment by SergioBertolinSG** [comment]
User entered then will be the same as custom credentials in WND.

With the new improvements old WND credentials choice will appear also? If that is the case the names should be the same.

**Comment by PVince81** [comment]
@SergioBertolinSG no, the mapping is as follows:

- "Login credentials" => "Log-in credentials, save in session" (and later save in DB too)
- "Global credentials" => TODO: to be implemented, discussed here https://github.com/owncloud/core/issues/16305#issuecomment-174983424
- "User credentials" => "User entered, store in database"
- "Custom credentials" => "Username and password" (the inline user/password fields that always existed with most external storages)

**Comment by SergioBertolinSG** [comment]
ok thanks @PVince81

**Comment by PVince81** [comment]
PR is here https://github.com/owncloud/core/pull/22045
