### ISSUE TITLE
Error creating shared link in files app

### ISSUE THREAD

**Issue by pjrobertson** [owncloud/core#21919]
Hi there,

I'm using ownCloud 8.2.2 and have been doing so for a while. Just now I uploaded a folder to my ownCloud install using the desktop client (OS X, v2.1.0.2944) and then logged into the online file manager to try and create a shared link. Clicking the checkbox to share a link on this folder gave me this popup error:

```
An exception occurred while executing 'INSERT INTO "oc_share" ( "item_type", "item_source", "item_target", "share_type", "share_with", "uid_owner", "permissions", "stime", "file_source", "file_target", "token", "parent", "expiration") VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)' with params ["folder", "2516", "\/2516", 3, null, "patrick", "1", 1453817816, "2516", "\/Great Wall 25-01-2016", "OBB4Ejgz8y4TBIe", null, null]: SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "oc_share_pkey" DETAIL: Key (id)=(35) already exists.
```

Renaming the folder doesn't help.
I can't find anything useful in the log files

**Comment by pjrobertson** [comment]
FYI the row in the database with the pkey of 35 is for the calendar app:

```
 35 |          0 | nameX     | nameY   |        | calendar  | 19          | calendarName  |             |                       |          31 | 1451051061 |        0 |       
```

**Comment by pjrobertson** [comment]
Update 2: every time I clicked the 'share' button, the `INSERT INTO` SQL was updated with the id going up one each time.
The calendar in question (see last comment above) which was conflicting with this was shared to 4 people. Once I had clicked the 'share' button 4 times, on the 5th time it worked successfully (id in the `INSERT INTO` SQL was incremented past all the current existing rows.

Unconfirmed, but perhaps a way to reproduce this (all as the same user):

* Share a folder in the files app by link
* Create a calendar, and share it with 3 people
* Go and try to share another folder in files app

**Comment by nickvergessen** [comment]
Did you restore a backup lately?

**Comment by LukasReschke** [comment]
Can you also fill out the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md - some stuff missing such as the used DB etc.

**Comment by nickvergessen** [comment]
Please provide the details from https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version

**Comment by pjrobertson** [comment]
Sorry, the contributing page wouldn't load for me previously

### Steps to reproduce

**Unconfirmed**

1. Share a folder in the files app by link
2. Create a calendar, and share it with 3 people
3. Go and try to share another folder in files app

### Expected behaviour
Share the link as expected without any problem in the files app

### Actual behaviour
Given the error in files app as follows: 
```
An exception occurred while executing 'INSERT INTO "oc_share" ( "item_type", "item_source", "item_target", "share_type", "share_with", "uid_owner", "permissions", "stime", "file_source", "file_target", "token", "parent", "expiration") VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)' with params ["folder", "2516", "\/2516", 3, null, "patrick", "1", 1453817816, "2516", "\/Great Wall 25-01-2016", "OBB4Ejgz8y4TBIe", null, null]: SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "oc_share_pkey" DETAIL: Key (id)=(35) already exists.
```

### Server configuration
**Operating system**:
Centos 7: 3.10.0-327.3.1.el7.x86_64

**Web server:**
Server version: Apache/2.4.6 (CentOS)
Server built:   Dec  3 2015 21:06:31

**Database:**
psql (PostgreSQL) 9.4.5

**PHP version:**
PHP 7.0.2 (cli) (built: Jan 25 2016 14:09:14) ( NTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies

Using CGI with Apache

**ownCloud version:** (see ownCloud admin page)
8.2.2

**Updated from an older ownCloud or fresh install:**
Updated from an old version (have been updated successfully from about owncloud 7 - for several years.

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

- logged in as an admin and loaded that page - just redirected to my default app.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.1.3
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - documents: 0.11.0
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - templateeditor: 0.1
  - updater: 0.6
Disabled:
  - encryption
  - external
  - files_external
  - notifications
  - provisioning_api
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocea658fae01",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.patrick.is"
        ],
        "datadirectory": "\/home\/pjrobertson\/DATA\/cloud\/data",
        "dbtype": "pgsql",
        "version": "8.2.2.2",
        "dbname": "patrickis_cloud",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "theme": "",
        "maintenance": false,
        "defaultapp": "calendar",
        "preview_libreoffice_path": "\/home\/pjrobertson\/bin\/openoffice4\/program\/soffice",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 1,
        "trashbin_retention_obligation": "auto",
        "asset-pipeline.enabled": true,
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/home\/pjrobertson\/var\/run\/redis.sock",
            "port": 0,
            "timeout": 0
        }
    }
}

```

**Are you using external storage, if yes which one:**

No external storage

**Are you using encryption:** 

No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

NO

### Client configuration
**Browser:**
46.0.2490.86 (64-bit)

**Operating system:**
OS X

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"A8I5ypi+2MRJZmS\/z1PJ","remoteAddr":"","app":"cli","message":"Memcache \\OC\\Memcache\\Redis not available for local cache","level":1,"time":"2016-01-26T14:30:01+00:00"}
{"reqId":"A8I5ypi+2MRJZmS\/z1PJ","remoteAddr":"","app":"cli","message":"Memcache \\OC\\Memcache\\Redis not available for distributed cache","level":1,"time":"2016-01-26T14:30:01+00:00"}
{"reqId":"Hy51yM+OeZUNe1HTyD5F","remoteAddr":"","app":"cli","message":"Memcache \\OC\\Memcache\\Redis not available for local cache","level":1,"time":"2016-01-26T14:42:32+00:00"}
{"reqId":"Hy51yM+OeZUNe1HTyD5F","remoteAddr":"","app":"cli","message":"Memcache \\OC\\Memcache\\Redis not available for distributed cache","level":1,"time":"2016-01-26T14:42:32+00:00"}
{"reqId":"VGBOfRkfwUfb5f7lkTRf","remoteAddr":"","app":"cli","message":"Memcache \\OC\\Memcache\\Redis not available for local cache","level":1,"time":"2016-01-26T14:44:32+00:00"}
{"reqId":"VGBOfRkfwUfb5f7lkTRf","remoteAddr":"","app":"cli","message":"Memcache \\OC\\Memcache\\Redis not available for distributed cache","level":1,"time":"2016-01-26T14:44:32+00:00"}
{"reqId":"vhmt+Jmr+Wh7z2tyIb4G","remoteAddr":"","app":"cli","message":"Memcache \\OC\\Memcache\\Redis not available for local cache","level":1,"time":"2016-01-26T14:45:01+00:00"}
{"reqId":"vhmt+Jmr+Wh7z2tyIb4G","remoteAddr":"","app":"cli","message":"Memcache \\OC\\Memcache\\Redis not available for distributed cache","level":1,"time":"2016-01-26T14:45:01+00:00"}
```

#### Browser log
```
N/A
```

**Comment by pjrobertson** [comment]
@nickvergessen - no backups restored lately. The (perhaps) conflicting calendar rows in `oc_share` were created over the Christmas period

**Comment by PVince81** [comment]
@rullzer any idea why trying to create a link share for a folder would affect a calendar share ?

**Comment by nickvergessen** [comment]
@pjrobertson can you have a look whether the autoincrement value of the table is lower than the last value? Other then that I'd assume it might also be related to php7?

**Comment by pjrobertson** [comment]
So right now (I'm using `postgres`):

```
=> select last_value from oc_share_id_seq;
 last_value 
------------
         39
(1 row)

=> select id from oc_share order by id DESC limit 1;
 id 
----
 39
(1 row)
```

But, if I go back to my backups from the 26th and look at the pg_dump it contains these lines:

```
--
-- Name: oc_share_id_seq; Type: SEQUENCE SET; Schema: public; Owner: somebody
--

SELECT pg_catalog.setval('oc_share_id_seq', 32, true);

--
-- Data for Name: oc_share; Type: TABLE DATA; Schema: public; Owner: somebody
--

COPY oc_share (id, share_type, share_with, uid_owner, parent, item_type, item_source, item_target, file_source, file_target, permissions, stime, accepted, ex
piration, token, mail_send) FROM stdin;
[... snip... - last row below]
36      0       name   othername \N      calendar        19      calendarname        \N      \N      31      1451051064      0       \N      \N      0
```

So it looks like this is where the problem was. When I created that new shared calendar (named 'calendarname' above) and shared it with 4 people the rows got inserted but the `oc_share_id_seq` val wasn't incremented

**Comment by nickvergessen** [comment]
Okay, well that seems to be the problem then. If you happen to face the issue again, please open an issue in the calendar repository: https://github.com/owncloud/calendar

**Comment by pjrobertson** [comment]
OK, so you're saying the issue isn't with core but with calendar, and that I should open an issue there?

**Comment by nickvergessen** [comment]
I assume the issue was because a DB backup was restored. But if you face the issue again, then open an issue in calendar, yes.

**Comment by pjrobertson** [comment]
I never restored any backups, which is why it’s a bit strange.

OK, if I encounter it again I’ll open a new issue
