### ISSUE TITLE
Can we PLEASE have the option to turn off 'Trusted Domain' setting, or at least add wild card?

### ISSUE THREAD

**Issue by Cursewords** [owncloud/core#21922]
Original thread here: https://forum.owncloud.org/viewtopic.php?p=105909#p105909

C'mon guys you have been asked this question MANY times now, and have gotten many threads and posts about issues that it is causing. Please give us the option to disable the 'trusted domain' feature or allow us to add wildcards.

I know it's a good security feature but users should still get administrative rights and the right to put their foot down and have the final say on whether or not they want a feature added or not. There is other software, plugins and methods to prevent access to Owncloud via only 'trusted domains'.

Please for the love of god, give users the ability to disable the feature without breaking the entire setup, or allow us to add wildcards into the domain listing to allow for dynamic domain hosts.

**Comment by LukasReschke** [comment]
> Please for the love of god, give users the ability to disable the feature without breaking the entire setup, or allow us to add wildcards into the domain listing to allow for dynamic domain hosts.

Well. Pull request welcome as somebody in the forum has already stated. https://github.com/owncloud/core/pull/12979 would just require fixing the unit tests :wink:

**Comment by nickvergessen** [comment]
Sometimes we use trusted_domain to generate links (federated share e.g., iirc). I think we need a method then which returns the first non-wildcard domain?

**Comment by jnweiger** [comment]
From within a VM, we cannot discern our domain name a-priori. We either need a wildcard, or a reliably way to get that information back from a browser. Currently the [Add Trusted Domains Button] in the web interface is unreliable.

**Comment by jnweiger** [comment]
@Cursewords please check out the following workaround:
wget https://raw.githubusercontent.com/owncloud/vm/master/vagrant/oc9ce/wildcard-trusted-domains.config.php
and add this file to your config folder.

It is not a real wildcard, but effectively disables the trusted domain check by feeding the current $_SERVER['HTTP_HOST'] into the Config.

**Comment by jnweiger** [comment]
Closing this inactive issue. The offered workaround appears acceptable in many cases.

Please open a follow up issue  if link generation still depends on trusted domains settings. There should not be such a dependency.

**Comment by linuxaos** [comment]
Cursewords: Dude I feel your pain! WTF owncloud???  I may want the security feature but dammit give me the option to disable it. Why, why , why do I have to search Google for an hour before I get here? Come on already !
Cursewords, you have the patience of a God. Also, your comment was exactly what I was feeling. Thank you my brother !

**Comment by carlox97** [comment]
> @Cursewords please check out the following workaround:
> wget https://raw.githubusercontent.com/owncloud/vm/master/vagrant/oc9ce/wildcard-trusted-domains.config.php
> and add this file to your config folder.
> 
> It is not a real wildcard, but effectively disables the trusted domain check by feeding the current $_SERVER['HTTP_HOST'] into the Config.

I'm relatively new (== not entirely a noob) could you explain how could I do this workaround?
I'm running owncloud 10.0 on DietPi. my config folder is
`/var/www/owncloud/config`

should I create a new .php file in that directory? or should I edit the current config.php? if yes, which line should I replace?

**Comment by carlox97** [comment]
ol

**Comment by ha11oga11o** [comment]
> 
> 
> Cursewords: Dude I feel your pain! WTF owncloud??? I may want the security feature but dammit give me the option to disable it. Why, why , why do I have to search Google for an hour before I get here? Come on already !
> Cursewords, you have the patience of a God. Also, your comment was exactly what I was feeling. Thank you my brother !

After all this years,... frustration and everything im upvoting this because im full of it! (trying to stay polite here)

Cheers!

**Comment by bastiOo** [comment]
yeah, frustrating when you realize you cannot print the one important document in your local copyshop. ... seems like the private cloud users have to look around for alternatives soon.
