### ISSUE TITLE
Owncloud 8.2.2.2 breaks support for OneNote 2013

### ISSUE THREAD

**Issue by brandonkirsch** [owncloud/core#21925]
I just upgraded through each major release of OwnCloud since 7.0 and my Windows 7 OneNote 2013 client quit working when I finally reached 8.2.2.2.

I used mod_dumpio to capture the HTTPS traffic and I see 4 unique requests.  2 HEAD requests, 1 PROPFIND request and finally a LOCK request where the error occurs.  The LOCK request can be viewed here:  http://pastebin.com/Hcj2PUgq

When OneNote 2013 requests a LOCK, Owncloud responds with the following error:

`<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\\DAV\\Exception\\NotImplemented</s:exception>
  <s:message>There was no handler found for this "LOCK" method</s:message>
</d:error>`

...and my OneNote Notebook fails to sync.

This was not the case in Owncloud 8.0.latest or 8.1.latest during my upgrade process, only failing once I reached 8.2.2.2.

I believe this issue may be related to: https://github.com/owncloud/core/issues/17732

**Comment by LukasReschke** [comment]
Probably requires whitelisting OneNote 2013 as well at https://github.com/owncloud/core/blob/aa598fc7012fa584df7dc397ae70997f97b7c8ae/apps/dav/lib/server.php#L99-L103, let me create a PR for you to test.

**Comment by LukasReschke** [comment]
Patch is at https://github.com/owncloud/core/pull/21926, please test.

**Comment by brandonkirsch** [comment]
Fixed it!  

I worry the patch may be a little overly specific (OneNote 2010 is still popular, although I don't have a copy to test with) but I am back in action.

Thanks for the ridiculously quick fix!

**Comment by stribog** [comment]
OneNote 2013, I'm using (v15.0.4805.1000) using two "user-agents"=>"Microsoft Office OneNote 2013" and "OneNote/15.0.4805.1000 (Windows/xx; Desktop WOW64; en-US; Desktop app; Vendor/Computer Model)".
I don't know if it was always like that or changed recently.
It prevents from OwnCloud users to change some items that were already created.
I fixed it in my instance of OwnCloud by adding another user agent in Server.php and ServerFactory.php
It looks like that;
if($request->isUserAgent([
 			'/WebDAVFS/',
 			'/Microsoft Office OneNote 2013/',
 +                     '/OneNote/',
 		])) {

I propose to make similar change in the running change log
