### ISSUE TITLE
Exchange of the shared_secret doesn't work

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#21929]
* Setup two servers (localhost/master and localhost/stable with both master code).
* enable federation app
* add the URL of the other server in the federation settings of each server (yellow sign is shown in front of the url then)

On localhost/stable run `php cron.php`:

```
{"reqId":"M+IXMjX0eH8kSZCObKNo","remoteAddr":"","app":"cron","message":"Run job with ID 13","level":0,"time":"2016-01-26T17:34:00+00:00","method":"--","url":"--"}
{"reqId":"M+IXMjX0eH8kSZCObKNo","remoteAddr":"","app":"no app in context","message":"Exception: {\"Exception\":\"GuzzleHttp\\\\Exception\\\\ClientException\",\"Message\":\"Client error response [url] http:\\\/\\\/localhost\\\/master\\\/ocs\\\/v2.php\\\/apps\\\/federation\\\/api\\\/v1\\\/shared-secret?format=json&url=http%3A%2F%2Flocalhost%2Fstable&token=OicCzFpdJrhEKzmo [status code] 403 [reason phrase] Forbidden\",\"Code\":403,\"Trace\":\"#0 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/stable\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Subscriber\\\/HttpError.php(32): GuzzleHttp\\\\Exception\\\\RequestException::create(Object(GuzzleHttp\\\\Message\\\\Request), Object(GuzzleHttp\\\\Message\\\\Response))\\n#1 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/stable\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Event\\\/Emitter.php(109): GuzzleHttp\\\\Subscriber\\\\HttpError->onComplete(Object(GuzzleHttp\\\\Event\\\\CompleteEvent), 'complete')\\n#2 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/stable\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(91): GuzzleHttp\\\\Event\\\\Emitter->emit('complete', Object(GuzzleHttp\\\\Event\\\\CompleteEvent))\\n#3 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/stable\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(132): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#4 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/stable\\\/3rdparty\\\/react\\\/promise\\\/src\\\/FulfilledPromise.php(25): GuzzleHttp\\\\RequestFsm->GuzzleHttp\\\\{closure}(Array)\\n#5 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/stable\\\/3rdparty\\\/guzzlehttp\\\/ringphp\\\/src\\\/Future\\\/CompletedFutureValue.php(55): React\\\\Promise\\\\FulfilledPromise->then(Object(Closure), NULL, NULL)\\n#6 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/stable\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Message\\\/FutureResponse.php(43): GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureValue->then(Object(Closure), NULL, NULL)\\n#7 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/stable\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(134): GuzzleHttp\\\\Message\\\\FutureResponse::proxy(Object(GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureArray), Object(Closure))\\n#8 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/stable\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(165): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#9 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/stable\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(125): GuzzleHttp\\\\Client->send(Object(GuzzleHttp\\\\Message\\\\Request))\\n#10 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/stable\\\/lib\\\/private\\\/http\\\/client\\\/client.php(129): GuzzleHttp\\\\Client->get('http:\\\/\\\/localhos...', Array)\\n#11 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/stable\\\/apps\\\/federation\\\/backgroundjob\\\/getsharedsecret.php(145): OC\\\\Http\\\\Client\\\\Client->get('http:\\\/\\\/localhos...', Array)\\n#12 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/stable\\\/lib\\\/private\\\/backgroundjob\\\/job.php(52): OCA\\\\Federation\\\\BackgroundJob\\\\GetSharedSecret->run(Array)\\n#13 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/stable\\\/lib\\\/private\\\/backgroundjob\\\/queuedjob.php(42): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#14 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/stable\\\/apps\\\/federation\\\/backgroundjob\\\/getsharedsecret.php(126): OC\\\\BackgroundJob\\\\QueuedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#15 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/stable\\\/apps\\\/federation\\\/backgroundjob\\\/getsharedsecret.php(115): OCA\\\\Federation\\\\BackgroundJob\\\\GetSharedSecret->parentExecute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#16 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/stable\\\/cron.php(136): OCA\\\\Federation\\\\BackgroundJob\\\\GetSharedSecret->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#17 {main}\",\"File\":\"\\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/stable\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Exception\\\/RequestException.php\",\"Line\":89}","level":3,"time":"2016-01-26T17:34:00+00:00","method":"--","url":"--"}
```

and on the other server (localhost/master):

```
{"reqId":"T\/5fpv8VlLjKxv2EdwcK","remoteAddr":"::1","app":"no app in context","message":"remote server (http:\/\/localhost\/stable) didn't send a valid token (got GgE6TdzbTLoDrnU+) while getting shared secret","level":3,"time":"2016-01-26T17:34:00+00:00","method":"GET","url":"\/master\/ocs\/v2.php\/apps\/federation\/api\/v1\/shared-secret?format=json&url=http%3A%2F%2Flocalhost%2Fstable&token=GgE6TdzbTLoDrnU%2B"}
{"reqId":"i1261Dc6pNMVoNpXHW\/q","remoteAddr":"::1","app":"no app in context","message":"remote server (http:\/\/localhost\/stable) didn't send a valid token (got Jte5TpKbbugCQsfT) while getting shared secret","level":3,"time":"2016-01-26T17:34:00+00:00","method":"GET","url":"\/master\/ocs\/v2.php\/apps\/federation\/api\/v1\/shared-secret?format=json&url=http%3A%2F%2Flocalhost%2Fstable&token=Jte5TpKbbugCQsfT"}
{"reqId":"IiNcXOEb+xJ9AhYgjbMY","remoteAddr":"::1","app":"no app in context","message":"remote server (http:\/\/localhost\/stable) didn't send a valid token (got pT4ZeYuNqWKY7tu+) while getting shared secret","level":3,"time":"2016-01-26T17:34:00+00:00","method":"GET","url":"\/master\/ocs\/v2.php\/apps\/federation\/api\/v1\/shared-secret?format=json&url=http%3A%2F%2Flocalhost%2Fstable&token=pT4ZeYuNqWKY7tu%2B"}
{"reqId":"P\/l1JsjrSpmpCzx2PPxd","remoteAddr":"::1","app":"no app in context","message":"remote server (http:\/\/localhost\/stable) didn't send a valid token (got OicCzFpdJrhEKzmo) while getting shared secret","level":3,"time":"2016-01-26T17:34:00+00:00","method":"GET","url":"\/master\/ocs\/v2.php\/apps\/federation\/api\/v1\/shared-secret?format=json&url=http%3A%2F%2Flocalhost%2Fstable&token=OicCzFpdJrhEKzmo"}
```

Also the job is remove from the background jobs list and therefore the server will never get secret if something bad happened. Also I don't understand why the clientException isn't catched,because the code is inside a try catch and the catch clause also specifies the clientException.

cc @schiesbn 

I also don't understand why https://github.com/owncloud/core/blob/682821c71ed2af297170294632931be1ac769f25/apps/federation/backgroundjob/requestsharedsecret.php#L111-L111 is done? Why not make it inverse? Remove the job and stop execution if the server isn't listed in the DB anymore (same applies for the getsharedsecret job).

**Comment by schiesbn** [comment]
> Remove the job and stop execution if the server isn't listed in the DB anymore (same applies for the getsharedsecret job).

That's what it does. We remove the job, because this should be done in any case and execute it if the server is still in the list, otherwise skip it.

**Comment by schiesbn** [comment]
I couldn't re-produce the issue. Please try https://github.com/owncloud/core/pull/22046 if this changes anything for you.

**Comment by MorrisJobke** [comment]
> I couldn't re-produce the issue. Please try #22046 if this changes anything for you.

I re-setup this and now it gets more clear:

* I entered the domain in both instances
* then I run php cron.php on the first instance(/stable) - nothing in the logs
* then I run php cron.php on the second instance (/master) - following in the owncloud log:

masters owncloud.log:
```
{"reqId":"wx35Wj34AddQgmL5\/D99","remoteAddr":"","app":"no app in context","message":"Exception: {\"Exception\":\"GuzzleHttp\\\\Exception\\\\ClientException\",\"Message\":\"Client error response [url] http:\\\/\\\/localhost\\\/stable\\\/ocs\\\/v2.php\\\/apps\\\/federation\\\/api\\\/v1\\\/request-shared-secret?format=json [status code] 403 [reason phrase] Forbidden\",\"Code\":403,\"Trace\":\"#0 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/master\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Subscriber\\\/HttpError.php(32): GuzzleHttp\\\\Exception\\\\RequestException::create(Object(GuzzleHttp\\\\Message\\\\Request), Object(GuzzleHttp\\\\Message\\\\Response))\\n#1 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/master\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Event\\\/Emitter.php(109): GuzzleHttp\\\\Subscriber\\\\HttpError->onComplete(Object(GuzzleHttp\\\\Event\\\\CompleteEvent), 'complete')\\n#2 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/master\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(91): GuzzleHttp\\\\Event\\\\Emitter->emit('complete', Object(GuzzleHttp\\\\Event\\\\CompleteEvent))\\n#3 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/master\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(132): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#4 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/master\\\/3rdparty\\\/react\\\/promise\\\/src\\\/FulfilledPromise.php(25): GuzzleHttp\\\\RequestFsm->GuzzleHttp\\\\{closure}(Array)\\n#5 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/master\\\/3rdparty\\\/guzzlehttp\\\/ringphp\\\/src\\\/Future\\\/CompletedFutureValue.php(55): React\\\\Promise\\\\FulfilledPromise->then(Object(Closure), NULL, NULL)\\n#6 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/master\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Message\\\/FutureResponse.php(43): GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureValue->then(Object(Closure), NULL, NULL)\\n#7 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/master\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(134): GuzzleHttp\\\\Message\\\\FutureResponse::proxy(Object(GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureArray), Object(Closure))\\n#8 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/master\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(165): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#9 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/master\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(150): GuzzleHttp\\\\Client->send(Object(GuzzleHttp\\\\Message\\\\Request))\\n#10 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/master\\\/lib\\\/private\\\/http\\\/client\\\/client.php(191): GuzzleHttp\\\\Client->post('http:\\\/\\\/localhos...', Array)\\n#11 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/master\\\/apps\\\/federation\\\/backgroundjob\\\/requestsharedsecret.php(143): OC\\\\Http\\\\Client\\\\Client->post('http:\\\/\\\/localhos...', Array)\\n#12 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/master\\\/lib\\\/private\\\/backgroundjob\\\/job.php(52): OCA\\\\Federation\\\\BackgroundJob\\\\RequestSharedSecret->run(Array)\\n#13 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/master\\\/lib\\\/private\\\/backgroundjob\\\/queuedjob.php(42): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#14 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/master\\\/apps\\\/federation\\\/backgroundjob\\\/requestsharedsecret.php(124): OC\\\\BackgroundJob\\\\QueuedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#15 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/master\\\/apps\\\/federation\\\/backgroundjob\\\/requestsharedsecret.php(115): OCA\\\\Federation\\\\BackgroundJob\\\\RequestSharedSecret->parentExecute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#16 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/master\\\/cron.php(141): OCA\\\\Federation\\\\BackgroundJob\\\\RequestSharedSecret->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#17 {main}\",\"File\":\"\\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/master\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Exception\\\/RequestException.php\",\"Line\":89}","level":3,"time":"2016-02-01T13:01:46+00:00","method":"--","url":"--"}
```

stables log:
```
{"reqId":"lnvzdlOTWM2vSzGAD9ia","remoteAddr":"::1","app":"federation","message":"remote server (http:\/\/localhost\/master) presented lower token","level":3,"time":"2016-02-01T13:01:46+00:00","method":"POST","url":"\/stable\/ocs\/v2.php\/apps\/federation\/api\/v1\/request-shared-secret?format=json"}
```


After first step:
```
::1 - - [01/Feb/2016:14:01:22 +0100] "GET /master/status.php HTTP/1.1" 200 103
::1 - - [01/Feb/2016:14:01:22 +0100] "POST /stable/apps/federation/trusted-servers HTTP/1.1" 200 101
::1 - - [01/Feb/2016:14:01:28 +0100] "GET /stable/status.php HTTP/1.1" 200 103
```

After second step:
```
::1 - - [01/Feb/2016:14:01:28 +0100] "POST /master/apps/federation/trusted-servers HTTP/1.1" 200 101
::1 - - [01/Feb/2016:14:01:35 +0100] "POST /master/ocs/v2.php/apps/federation/api/v1/request-shared-secret?format=json HTTP/1.1" 200 79
```

After third step:
```
::1 - - [01/Feb/2016:14:01:46 +0100] "POST /stable/ocs/v2.php/apps/federation/api/v1/request-shared-secret?format=json HTTP/1.1" 403 79
::1 - - [01/Feb/2016:14:01:46 +0100] "GET /stable/ocs/v2.php/apps/federation/api/v1/shared-secret?format=json&url=http%3A%2F%2Flocalhost%2Fmaster&token=s6GwT6PiSgf8RFif HTTP/1.1" 200 129
```

**Comment by Helios07** [comment]
Hi,

I am struggling with the same problem. It set up two instances (one with RedHat 6, one with Ubuntu 14.04), tried to establish the trusted relationship and got a similar messages as Morris did:

`128.176.188.28 - - [03/Feb/2016:09:22:32 +0100] "POST /ocs/v2.php/apps/federation/api/v1/request-shared-secret?format=json HTTP/1.1" 403 79 "-" "ownCloud Server Crawler"`

How can I help you with more information?

**Comment by Helios07** [comment]
I forgot to mention that the previous message came from the server, I wanted to establish the connection with. On the server, I triggered the action I got this message:

`{"reqId":"DW7y\/dqryR42u1FoBCxP","remoteAddr":"","app":"no app in context","message":"Exception: {\"Exception\":\"GuzzleHttp\\\\Exception\\\\ClientException\",\"Message\":\"Client error response [url] https:\\\/\\\/sns-staging.sciebo.de\\\/ocs\\\/v2.php\\\/apps\\\/federation\\\/api\\\/v1\\\/request-shared-secret?format=json [status code] 403 [reason phrase] Forbidden\",\"Code\":403,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud-master\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Subscriber\\\/HttpError.php(33): GuzzleHttp\\\\Exception\\\\RequestException::create(Object(GuzzleHttp\\\\Message\\\\Request), Object(GuzzleHttp\\\\Message\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud-master\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Event\\\/Emitter.php(109): GuzzleHttp\\\\Subscriber\\\\HttpError->onComplete(Object(GuzzleHttp\\\\Event\\\\CompleteEvent), 'complete')\\n#2 \\\/var\\\/www\\\/owncloud-master\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(91): GuzzleHttp\\\\Event\\\\Emitter->emit('complete', Object(GuzzleHttp\\\\Event\\\\CompleteEvent))\\n#3 \\\/var\\\/www\\\/owncloud-master\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(132): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#4 \\\/var\\\/www\\\/owncloud-master\\\/3rdparty\\\/react\\\/promise\\\/src\\\/FulfilledPromise.php(25): GuzzleHttp\\\\RequestFsm->GuzzleHttp\\\\{closure}(Array)\\n#5 \\\/var\\\/www\\\/owncloud-master\\\/3rdparty\\\/guzzlehttp\\\/ringphp\\\/src\\\/Future\\\/CompletedFutureValue.php(55): React\\\\Promise\\\\FulfilledPromise->then(Object(Closure), NULL, NULL)\\n#6 \\\/var\\\/www\\\/owncloud-master\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Message\\\/FutureResponse.php(43): GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureValue->then(Object(Closure), NULL, NULL)\\n#7 \\\/var\\\/www\\\/owncloud-master\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(135): GuzzleHttp\\\\Message\\\\FutureResponse::proxy(Object(GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureArray), Object(Closure))\\n#8 \\\/var\\\/www\\\/owncloud-master\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(165): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#9 \\\/var\\\/www\\\/owncloud-master\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(150): GuzzleHttp\\\\Client->send(Object(GuzzleHttp\\\\Message\\\\Request))\\n#10 \\\/var\\\/www\\\/owncloud-master\\\/lib\\\/private\\\/http\\\/client\\\/client.php(191): GuzzleHttp\\\\Client->post('https:\\\/\\\/sns-sta...', Array)\\n#11 \\\/var\\\/www\\\/owncloud-master\\\/apps\\\/federation\\\/backgroundjob\\\/requestsharedsecret.php(145): OC\\\\Http\\\\Client\\\\Client->post('https:\\\/\\\/sns-sta...', Array)\\n#12 \\\/var\\\/www\\\/owncloud-master\\\/lib\\\/private\\\/backgroundjob\\\/job.php(52): OCA\\\\Federation\\\\BackgroundJob\\\\RequestSharedSecret->run(Array)\\n#13 \\\/var\\\/www\\\/owncloud-master\\\/lib\\\/private\\\/backgroundjob\\\/queuedjob.php(42): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#14 \\\/var\\\/www\\\/owncloud-master\\\/apps\\\/federation\\\/backgroundjob\\\/requestsharedsecret.php(124): OC\\\\BackgroundJob\\\\QueuedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#15 \\\/var\\\/www\\\/owncloud-master\\\/apps\\\/federation\\\/backgroundjob\\\/requestsharedsecret.php(115): OCA\\\\Federation\\\\BackgroundJob\\\\RequestSharedSecret->parentExecute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#16 \\\/var\\\/www\\\/owncloud-master\\\/cron.php(141): OCA\\\\Federation\\\\BackgroundJob\\\\RequestSharedSecret->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#17 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud-master\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Exception\\\/RequestException.php\",\"Line\":89}","level":3,"time":"2016-02-03T08:22:32+00:00"}`
 in the owncloud.log

**Comment by Helios07** [comment]
I think I forgot to mention one other error message:
`{"reqId":"Jna7t4RXogoZ6NUEdlhi","remoteAddr":"128.176.4.8","app":"federation","message":"remote server not trusted (https:\/\/sns-staging.sciebo.de) while requesting shared secret","level":3,"time":"2016-02-03T09:51:20+00:00"}`

**Comment by SergioBertolinSG** [comment]
I am experiencing this as well.
```
Exception: {"Exception":"GuzzleHttp\\Exception\\ClientException","Message":"Client error response [url] http:\/\/HIDED_HOST:54824\/ocs\/v2.php\/apps\/federation\/api\/v1\/request-shared-secret?format=json [status code] 403 [reason phrase] Forbidden","Code":403,"Trace":"#0 \/opt\/owncloud\/3rdparty\/guzzlehttp\/guzzle\/src\/Subscriber\/HttpError.php(33): GuzzleHttp\\Exception\\RequestException::create(Object(GuzzleHttp\\Message\\Request), Object(GuzzleHttp\\Message\\Response))\n#1 \/opt\/owncloud\/3rdparty\/guzzlehttp\/guzzle\/src\/Event\/Emitter.php(109): GuzzleHttp\\Subscriber\\HttpError->onComplete(Object(GuzzleHttp\\Event\\CompleteEvent), 'complete')\n#2 \/opt\/owncloud\/3rdparty\/guzzlehttp\/guzzle\/src\/RequestFsm.php(91): GuzzleHttp\\Event\\Emitter->emit('complete', Object(GuzzleHttp\\Event\\CompleteEvent))\n#3 \/opt\/owncloud\/3rdparty\/guzzlehttp\/guzzle\/src\/RequestFsm.php(132): GuzzleHttp\\RequestFsm->__invoke(Object(GuzzleHttp\\Transaction))\n#4 \/opt\/owncloud\/3rdparty\/react\/promise\/src\/FulfilledPromise.php(25): GuzzleHttp\\RequestFsm->GuzzleHttp\\{closure}(Array)\n#5 \/opt\/owncloud\/3rdparty\/guzzlehttp\/ringphp\/src\/Future\/CompletedFutureValue.php(55): React\\Promise\\FulfilledPromise->then(Object(Closure), NULL, NULL)\n#6 \/opt\/owncloud\/3rdparty\/guzzlehttp\/guzzle\/src\/Message\/FutureResponse.php(43): GuzzleHttp\\Ring\\Future\\CompletedFutureValue->then(Object(Closure), NULL, NULL)\n#7 \/opt\/owncloud\/3rdparty\/guzzlehttp\/guzzle\/src\/RequestFsm.php(135): GuzzleHttp\\Message\\FutureResponse::proxy(Object(GuzzleHttp\\Ring\\Future\\CompletedFutureArray), Object(Closure))\n#8 \/opt\/owncloud\/3rdparty\/guzzlehttp\/guzzle\/src\/Client.php(165): GuzzleHttp\\RequestFsm->__invoke(Object(GuzzleHttp\\Transaction))\n#9 \/opt\/owncloud\/3rdparty\/guzzlehttp\/guzzle\/src\/Client.php(150): GuzzleHttp\\Client->send(Object(GuzzleHttp\\Message\\Request))\n#10 \/opt\/owncloud\/lib\/private\/http\/client\/client.php(191): GuzzleHttp\\Client->post('http:\/\/docker.o...', Array)\n#11 \/opt\/owncloud\/apps\/federation\/backgroundjob\/requestsharedsecret.php(145): OC\\Http\\Client\\Client->post('http:\/\/docker.o...', Array)\n#12 \/opt\/owncloud\/lib\/private\/backgroundjob\/job.php(52): OCA\\Federation\\BackgroundJob\\RequestSharedSecret->run(Array)\n#13 \/opt\/owncloud\/lib\/private\/backgroundjob\/queuedjob.php(42): OC\\BackgroundJob\\Job->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#14 \/opt\/owncloud\/apps\/federation\/backgroundjob\/requestsharedsecret.php(124): OC\\BackgroundJob\\QueuedJob->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#15 \/opt\/owncloud\/apps\/federation\/backgroundjob\/requestsharedsecret.php(115): OCA\\Federation\\BackgroundJob\\RequestSharedSecret->parentExecute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#16 \/opt\/owncloud\/cron.php(163): OCA\\Federation\\BackgroundJob\\RequestSharedSecret->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#17 {main}","File":"\/opt\/owncloud\/3rdparty\/guzzlehttp\/guzzle\/src\/Exception\/RequestException.php","Line":89}
```

But please note that I am using ajax cron (Not sure if this is not supposed to work).

**Comment by MorrisJobke** [comment]
> (Not sure if this is not supposed to work).

It is. This should work just fine.

@schiesbn Could you have a look?

**Comment by schiesbn** [comment]
> But please note that I am using ajax cron (Not sure if this is not supposed to work). 

Ajax cron should work just fine. That's what I used all the time during development. You just have to make sure that after adding the trusted server to both servers that you reload the pages multiple time on both servers by turns. Every page reload will execute one cron job and depending how many other cron jobs you have this can take about 5 alternating page refreshes.

Therefor for testing it is better to use the cron.php and call this file on both servers twice (server1, server2, server1, server2). That makes it easier to test and this PR is completely independent from the cron type.

**Comment by schiesbn** [comment]
Sorry, I still can't reproduce it... But I'm still looking into it

**Comment by DeepDiver1975** [comment]
Can we increase the UX on this for the admin?
The admin is basically blind until it magically works ... if not he will never realize.

**Comment by schiesbn** [comment]
@DeepDiver1975 do you have any idea how it could be improved? 

We already have the status codes, we could have more detailed states. The indicator would be the same (red, yellow, green) but on hover we could show a short message depending on the status code. Something:

1. Waiting for initial exchange of shared secret
2. Waiting for initial address book sync

But would this improve it that much. If we could get some information from the background jobs we could also add something like ("will happen in about X Minutes"), but this is a information we don't have and can't get.

**Comment by MorrisJobke** [comment]
> And then we would still miss the information about the remote server, we never know when the remote server will execute his background jobs, e.g. to generate the local address book, the next time.

But providing this information is also helpful for debugging. For example in my case both jobs already run and it looks all the same before, during and after the job execution. And it still looks like there are steps to be done.

**Comment by schiesbn** [comment]
> But providing this information is also helpful for debugging. For example in my case both jobs already run and it looks all the same before, during and after the job execution. And it still looks like there are steps to be done.

We also change to a failure state and a red indicator is something fails and we can't recover automatically, see https://github.com/owncloud/core/blob/master/apps/federation/backgroundjob/getsharedsecret.php#L182

But it seems like in your case it fails somewhere else irrecoverable. If we find the bug we can fix it and maybe add additional transitions to the failure state.

**Comment by schiesbn** [comment]
We could sort out the issue reported by @Helios07 which was basically a miss-configured 'overwrite.cli.url' in the config.php.

This leaves us with the problem reported by @MorrisJobke... Morris, do you have set 'overwrite.cli.url' in the config.php in one of your test instances? If not please try https://github.com/owncloud/core/pull/22403 if this changes at least something regarding the error messages.

**Comment by MorrisJobke** [comment]
> Morris, do you have set 'overwrite.cli.url' in the config.php in one of your test instances?

No. I don't set this.

**Comment by MorrisJobke** [comment]
It somehow magically works now :+1:
