### ISSUE TITLE
Error while Creating / Syncing new folder

### ISSUE THREAD

**Issue by mschad** [owncloud/core#21936]
Dear Community,

There is an error while syncing new added folders by windows at the Owncloud directory (Client 2.1.0). --> Server replies: forbidden.

Although it is not possible to create a folder over the web. Ther it is the messagt "error while create this folder".

**Comment by karlitschek** [comment]
This looks like an configuration issue on your side and not an ownCloud bug. Can you please submit a full bug report using the issue template?  https://github.com/owncloud/core/blob/master/CONTRIBUTING.md
