### ISSUE TITLE
php5-libsmbclient is not up to date

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#21934]
### Steps to reproduce
1. Install ownCloud from download.owncloud.org

### Expected beahaviour
php5-libsmbclient that is shipped should be up to date. 

### Actual behaviour
The php5-libsmbclient is [not up to date](
https://github.com/oerdnj/deb.sury.org/issues/235#issuecomment-175103020). (And it would be better if it wasn't a part of the ownCloud repo if you ask me)

### Ref
Ref: https://github.com/oerdnj/deb.sury.org/issues/235#issuecomment-175220714

### Server
**Ubuntu Server 14.04 LTS**
PHP 5.6
Apache 2.4
MySQL 5.6

cc @jnweiger

**Comment by jnweiger** [comment]
If there is a working version in ubuntu 14.04 the best solution is to stop shipping one bundled.

**Comment by enoch85** [comment]
@jnweiger Isn't this about just updating to a newer version?

`/usr/lib/php5/20121212` should be `/usr/lib/php5/20131226/` instead.

**Comment by jnweiger** [comment]
The build log file https://build.opensuse.org/package/live_build_log/isv:ownCloud:community/php5-libsmbclient/xUbuntu_14.04/x86_64
shows that we build against:
<pre>
[   60s] PHP Api Version:         20121113
[   60s] Zend Module Api No:      20121212
[   60s] Zend Extension Api No:   220121212
</pre>

Whatever php version wants 20131226, it is not the 5.5 that ships with Ubuntu 14.04

 php -r 'phpinfo();' | grep PHP | egrep '(API|Version)'
PHP Version => 5.5.9-1ubuntu4.14
PHP API => 20121113
PHP Extension Build => API20121212,NTS

**Comment by RealRancor** [comment]
> Whatever php version wants 20131226, it is not the 5.5 that ships with Ubuntu 14.04

Exactly. 20131106 is PHP 5.6 which @enoch85 seems to be using atm.

@enoch85 If you upgrade your PHP "out of band" then you also need  to use the correct repository which would be the one for 15.04 which is build against the wanted API:

https://build.opensuse.org/package/live_build_log/isv:ownCloud:community/php5-libsmbclient/xUbuntu_15.04/x86_64

```
[  154s] PHP Api Version:         20131106
[  154s] Zend Module Api No:      20131226
[  154s] Zend Extension Api No:   220131226
```

**Comment by jnweiger** [comment]
Updating to a newer version is independant from compiling for a matching php version.

Eduardok has new releases. I'll check out 0.7.0

**Comment by RealRancor** [comment]
Yes, but the original issue which @enoch85 is referring (https://github.com/oerdnj/deb.sury.org/issues/235) is about the API problem he had posted there:

> PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20131226/libsmbclient.so' - /usr/lib/php5/20131226/libsmbclient.so: cannot open shared object file: No such file or directory in Unknown on line 0

or am i wrong?

**Comment by jnweiger** [comment]
You are right. @enoch85 mixes two topics in this issue. The easy one is upgrading. The hard one is providing a package for each and every phpapi version.

**Comment by RealRancor** [comment]
Maybe the hard one is something which needs to be solved by upstream.

There is even a php-smb package available at debian and ubuntu:

https://packages.debian.org/sid/php/php-smb
http://packages.ubuntu.com/xenial/php-smb

both referencing to the non-existent package php5-smbclient in their repository.

**Comment by enoch85** [comment]
Ok, you're right. Didn't think of that. 

If it's possible to fix it would be awesome anyway.

**Comment by PVince81** [comment]
CC @icewind1991 I remember you mentioned this on IRC

**Comment by RealRancor** [comment]
Just an additional note, seems the 9.0 repositories at https://download.owncloud.org/download/repositories/stable/ are not shipping the php5-libsmbclient at all.

**Comment by enoch85** [comment]
> •seems the 9.0 repositories at https://download.owncloud.org/download/repositories/stable/ are not shipping the php5-libsmbclient at all
•Ubuntu (http://packages.ubuntu.com/search?keywords=php-smbclient) and Debian (https://packages.debian.org/search?keywords=php-smbclient) have now php5-libsmbclient in their newest branches

So this can be closed then right? @jnweiger

**Comment by jnweiger** [comment]
Great to have the package upstream!
Let's close here!
