### ISSUE TITLE
Change "in a few seconds" to "seconds ago" in recently modified

### ISSUE THREAD

**Issue by strugee** [owncloud/core#21937]
When you e.g. upload a file, ownCloud displays the last modified time as "in a few seconds." This is confusing, as it implies that the change will happen soon, not that it has already happened. Also, it's somewhat wordy. It should be changed to "seconds ago" instead.

I'm on ownCloud 8.1.

**Comment by DeepDiver1975** [comment]
Looks like your system clocks are not in sync. Please setup ntp. Sync clocks are requires to run a stable system.

**Comment by strugee** [comment]
@DeepDiver1975 I definitely have an ntpd running - is this a bug? If so I can fill out the issue template

**Comment by DeepDiver1975** [comment]
this is not a bug - no need to fill out the issue template.

ntp running on your client as well?

**Comment by strugee** [comment]
@DeepDiver1975 shoot, sorry. I've been missing a lot of GitHub notifications recently :/

I'm not sure if ntp was running on the client (I'll check when I have access to it), but shouldn't the server normalize timestamps into e.g. epoch time, and then convert into the local timezone? Whether this particular computer had ntp running or not, we can't expect everyone to run it.
