### ISSUE TITLE
SFTP: Sync over single connection

### ISSUE THREAD

**Issue by rigid** [owncloud/core#21931]
External SFTP storage uses a new connection for every file. It would be nicer for the server to use a single SFTP connection.

**ownCloud version:** ownCloud 8.2.2 (git)

**Comment by Xenopathic** [comment]
Each file you download from ownCloud invokes a new connection to PHP. Sure, HTTP/2 and pipelining fixes a lot of that, but they are still individual PHP processes (and hence individual SFTP connections) for each file.

Not much we can do without moving away from PHP :disappointed:

**Comment by rigid** [comment]
Hm, indeed that's disapointing. I'm not sure whether to close this.
Maybe there's some way in the future? Or maybe a workaround where (optionally) the files could be synced to the owncloud server using one SFTP connection and then synced to clients via multiple connections?

**Comment by Xenopathic** [comment]
The current model of external storages is a direct connection to the target filesystem, so the data never gets copied to the ownCloud server and remains on your fileserver. What you are asking for is a way to synchronise files between a fileserver (SFTP) and ownCloud, such that they all appear locally in ownCloud. I'd advise you look into rsync, GlusterFS, or other filesystem synchronisation tools.

**Comment by rigid** [comment]
@Xenopathic i'm aware that I could simply use another syncing solution, but that'd be just a workaround.
I hope there might be some way for owncloud to "bundle" requests to SFTP. In the end, directory listings also don't need 1 request per file.
Maybe it's not easily possible to "cache" requests for files in a SFTP storage, so that - say - all files requested within 10 seconds get downloaded via a single SFTP connection. But maybe there's another solution...

**Comment by PVince81** [comment]
Not possible with current architecture as the connection won't survive the end of the PHP request. Would likely require to implement an external service (daemon) that keeps the connections open.
