### ISSUE TITLE
[Files external] It should NOT be possible to name the mountpoints

### ISSUE THREAD

**Issue by davitol** [owncloud/core#21939]
### Steps to reproduce

1. As admin user configure a files external mountpoint  and save it
2. Configure another mountpoint same named as the previous one

### Expected behaviour

An advice about you cannot create a mountpoint named in the same way as a previous one should be shown

### Actual behaviour

The mountpoint is created, and the configuration that prevails over is the last one. In files view this last mountpoint is the one that is shown.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 9.0 pre alpha (daily) Build:2016-01-26T04:16:42+00:00 4c9e328211a3f986cd2c6186e4c1de755d5c940b

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** yes; webDAV.
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox for Mac OSX

**Comment by rperezb** [comment]
Duplicated to: https://github.com/owncloud/core/issues/10511
