### ISSUE TITLE
Sharing a file of a S3 mountpoint from an LDAP user to another user crashes webUI

### ISSUE THREAD

**Issue by davitol** [owncloud/core#21944]
### Steps to reproduce

1. As admin user configure a files external S3 mountpoint  and save it
2. Login with an LDAP user, share a file from the S3 mountpoint with another user

### Expected behaviour

The file should be shared.

### Actual behaviour

A blank sheet appears when we check if the file has been shared. webUI is no longer available

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 9.0 pre alpha (daily) Build:2016-01-27T04:16:03+00:00 db788a382c94b86f62980bc41945b8ea6825f59e

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** yes; S3.
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox for Mac OSX

```
{"reqId":"BvFYAI71PV2KtrKlCGUo","remoteAddr":"82.159.139.58","app":"files","message":" Backends provided no user object for aaliyah_adams","level":3,"time":"2016-01-27T09:12:44+00:00"}
{"reqId":"BvFYAI71PV2KtrKlCGUo","remoteAddr":"82.159.139.58","app":"core","message":"Backends provided no user object for aaliyah_adams","level":3,"time":"2016-01-27T09:12:44+00:00"}
{"reqId":"BvFYAI71PV2KtrKlCGUo","remoteAddr":"82.159.139.58","app":"PHP","message":"Call to a member function getCache() on a non-object at \/opt\/owncloud\/lib\/private\/files\/config\/usermountcache.php#72","level":3,"time":"2016-01-27T09:12:44+00:00"}
```

**Comment by davitol** [comment]
Same behaviour with an Active directory user
```
{"reqId":"fbYpARKl+mH5bU3+jjkp","remoteAddr":"82.159.139.58","app":"files","message":" Backends provided no user object for SAlexander","level":3,"time":"2016-01-27T09:51:17+00:00"}
{"reqId":"fbYpARKl+mH5bU3+jjkp","remoteAddr":"82.159.139.58","app":"core","message":"Backends provided no user object for SAlexander","level":3,"time":"2016-01-27T09:51:17+00:00"}
{"reqId":"fbYpARKl+mH5bU3+jjkp","remoteAddr":"82.159.139.58","app":"PHP","message":"Call to a member function getCache() on a non-object at \/opt\/owncloud\/lib\/private\/files\/config\/usermountcache.php#72","level":3,"time":"2016-01-27T09:51:17+00:00"}
```

**Comment by PVince81** [comment]
@Xenopathic mind having a look ? I suspect it might be the "LDAP user id !== login user id" story

**Comment by Xenopathic** [comment]
`Call to a member function getCache() on a non-object` cc @icewind1991

**Comment by davitol** [comment]
Same behaviour in Local as external storage

**Comment by PVince81** [comment]
Works for me now with S3 on master 7b0f83b616246c5274b551ab46b923b0989c464e
I can access both file shares and folder shares as recipient, shared from the S3 mount.

@davitol can you test again ?

**Comment by davitol** [comment]
@PVince81 just tested again with ownCloud Enterprise Edition 9.0 beta 1 (daily) Build:2016-02-17T04:14:46+00:00 c6b24573066cfc87b73b1b61b41032b8c5a406cf

scenario1: Share a file located in S3 mountpoint from LDAP user to LDAP user --> WFM
scenario2: Share a file located in S3 mountpoint from LDAP user to admin user --> :x: 

The file never appears in admin account in the files view

owncloud.log

```
{"reqId":"bkodW6bjyAvTfm5Qg4N+","remoteAddr":"82.159.139.58","app":"files","message":" Backends provided no user object for aaliyah_adams","level":3,"time":"2016-02-17T12:07:35+00:00"}
{"reqId":"bkodW6bjyAvTfm5Qg4N+","remoteAddr":"82.159.139.58","app":"core","message":"Backends provided no user object for aaliyah_adams","level":3,"time":"2016-02-17T12:07:35+00:00"}
```

These logs are print when sharing and unsharing

**Comment by PVince81** [comment]
Ok... looks like a different issue.
Let's see whether this also happens for non-ext storages.

**Comment by PVince81** [comment]
@davitol can you post your "applicable" setting ? Did you only assign the ext storage to a single LDAP user, or do all users see it ?

**Comment by davitol** [comment]
@PVincent applicable to all users

**Comment by PVince81** [comment]
also happens with SFTP, adjusting title to not scare away devs

**Comment by PVince81** [comment]
You know what, I think we should close this. This ticket was about crashing.

I'll open a new one.

**Comment by PVince81** [comment]
Raised here https://github.com/owncloud/core/issues/22467
