### ISSUE TITLE
comparison of the files/folders und exist files/folder on the fs(Datafolder).

### ISSUE THREAD

**Issue by blackcrack** [owncloud/core#21948]
Had try today this : 
(no Server Side Encryption because it's my own server)

=> move files up to the owncloud -> then go on the filesystem per cli/prompt remove
(or move on an other place)
the files/folders 
=>and reload the page of the owncload.. 
The removed/moved files exist ! and it's not movable/deletable . !

now move the files back in the original place and try it again..
now works again by existing files..

the matching/comparson of the data/files/folder is missing in 
the db and the real exist files. on each loading of the page 
should be check the comparson to the real exist files/folder and the files/folders in the database.

best regards
Blacky

**Comment by karlitschek** [comment]
This is not supported behavior. You can amke changes in the data folder and expect that ownCloud handles this. You can modify files only via wen interface, WebDAV mount, or mobile or desktop clients.

**Comment by blackcrack** [comment]
so, not directly local .. a bit pity .. to be not support the local files changed ..
because owner of a local Server it is with this behavior if someone per ssh move or delete files  
via mc so something and do this via "su apache" or something...

but thank you for your support :)

best regards
Blacky
