### ISSUE TITLE
Sharing a file of a personal mountpoint with two LDAP users that begin in the same way

### ISSUE THREAD

**Issue by davitol** [owncloud/core#21941]
### Steps to reproduce
1. As admin user configure a files external mountpoint  and save it
2. Configure a personal mountpoint with the same configuration as the previous one
3. Share a file with an LDAP user called 'aaliyah adams'
4. Share the same file with an LDAP user called 'aaliyah adams II'
### Expected behaviour

The file should be shared also with the second user
### Actual behaviour

An error is shown
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 9.0 pre alpha (daily) Build:2016-01-27T04:16:03+00:00 db788a382c94b86f62980bc41945b8ea6825f59e

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** yes; S3.
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Firefox for Mac OSX

![screen shot 2016-01-27 at 09 07 21](https://cloud.githubusercontent.com/assets/10596560/12608253/4f6a9e66-c4db-11e5-90ac-877084ac44f6.png)

**Comment by PVince81** [comment]
Please reopen in user_ldap app repo if issue still happens with 10.0.4 and latest user_ldap version
