### ISSUE TITLE
Unauthenticated user enumeration in server2server.php

### ISSUE THREAD

**Issue by mkh-dsn** [owncloud/core#21945]
Using the federated sharing API, it is possible to enumerate user names on an OC instance, without authentication. 

### Steps to reproduce
1. Have Owncloud instance with federated sharing enabled, i.e. as admin enable "Allow users on this server to receive shares from other servers"
2. Send sharing request to sharing API, e.g. using curl:

`curl -i -s -k -X 'POST' --data-binary $'shareWith=username&token=empty&name=empty&remoteId=1&owner=empty&remote=empty' 'http://owncloudserver/owncloud/ocs/v1.php/cloud/shares?format=json'`

### Expected behaviour
Server should answer with the same message, whether the users exists or not. So in this case,

{"ocs":{"meta":{"status":"ok","statuscode":100,"message":null},"data":[]}}

### Actual behaviour
The server responds with an error message that the user does not exist:

{"ocs":{"meta":{"status":"failure","statuscode":400,"message":"User does not exists"},"data":[]}}

### Server configuration
**Operating system**:
Ubuntu 14.04.3 LTS
**Web server:**
Apache/2.4.7 (Ubuntu) 
**Database:**
mysql 5.5.46
**PHP version:**
5.5.9-1ubuntu4.14
**ownCloud version:** (see ownCloud admin page)
8.2.2
**Updated from an older ownCloud or fresh install:**
Updated from 8.2.1.4

**Comment by LukasReschke** [comment]
**Side remark:** We do at the moment consider unauthenticated user enumeration not a privacy or security problem per-se when it requires actively bruteforcing all combinations. This can also happen using other mechanisms (such as login etc.). We would something actively consider a privacy issue if a list of usernames would be returned and the instance has been configured not to do so.

**Comment by LukasReschke** [comment]
Considering that this is the use-case of Server-to-Server sharing and for better UX (e.g. user types wrong username => We should be able to notify it) I'm closing this.

Server-to-Server sharing can be disabled which will make this scenario gone as can be seen at https://github.com/owncloud/core/blob/c264f9362d3d5f9b21dbff3ebce92454a0d3163c/apps/files_sharing/api/server2server.php#L41-L43
