### ISSUE TITLE
Client DoS by sending large number of sharing requests

### ISSUE THREAD

**Issue by mkh-dsn** [owncloud/core#21946]
By generating a large number of sharing requests to an OC instance with federated sharing enabled, one can spam user accounts with request pop-ups, rendering the web application unusable for the specific account.
### Steps to reproduce
1. Have Owncloud instance with federated sharing enabled, i.e. as admin enable "Allow users on this server to receive shares from other servers"
2. Send multiple sharing requests to the sharing API, e.g. using curl. Replace username with a valid username:

`for n in {1..1000}; do curl -i -s -k -X 'POST' --data-binary $'shareWith=username&token=empty&name=empty remoteId=1&owner=empty&remote=empty' 'http://owncloudserver/owncloud/ocs/v1.php/cloud/shares?format=json'; done`
### Expected behaviour

As expected, the server accepts the sharing request and displays them as pop-up messages to the user after login or when accessing the Files app. 
### Actual behaviour

The web application displays all sharing requests as pop-ups after login and when displaying the Files app:

![owncloud_sharedialog](https://cloud.githubusercontent.com/assets/16914814/12608956/586b7df6-c4df-11e5-90f6-4c90f38db2f1.PNG)

These pop-ups require user interaction and are a hindrance if there are many of them, as all of them have to "clicked away". Furthermore, a high number of requests (tested with 8000, but 100 already cause a few seconds of delay) can render the browser tab or the whole browser unresponsive (Iceweasel crashed, in Chromium only the tab crashes).

![owncloud_unresponsive_chromium](https://cloud.githubusercontent.com/assets/16914814/12608957/586bf970-c4df-11e5-9278-26117df483f1.PNG)
### Server configuration

**Operating system**:
Ubuntu 14.04.3 LTS
**Web server:**
Apache/2.4.7 (Ubuntu) 
**Database:**
mysql 5.5.46
**PHP version:**
5.5.9-1ubuntu4.14
**ownCloud version:** (see ownCloud admin page)
8.2.2
**Updated from an older ownCloud or fresh install:**
Updated from 8.2.1.4
**Browser versions:**
Chromium 47.0.2526.80
Iceweasel/38.5.0

**Comment by LukasReschke** [comment]
@nickvergessen @karlitschek Something for the new notification API?

**Comment by karlitschek** [comment]
Yes.Is there a way to build some kind of basic DoS prevention? So only x requests from a specific IP is allowed per timeframe? @LukasReschke check the apps.oc.com sourcecode for inspiration ;-)

**Comment by karlitschek** [comment]
by the way. We could do the same for login attempts.

**Comment by LukasReschke** [comment]
> Yes.Is there a way to build some kind of basic DoS prevention?

Not really. Especially not since PHP is anyways very prone to server-side DoS due to an insufficient hash table implementation: http://lukasmartinelli.ch/web/2014/11/17/php-dos-attack-revisited.html

> So only x requests from a specific IP is allowed per timeframe?

Won't help considering IPv6 etc. – What we better need here is a mechanism to aggregate and collect notifications and show something like "And 3838383 notifications".

**Comment by LukasReschke** [comment]
> and show something like "And 3838383 other notifications".

Plus maybe group the notifications based on remote server (requires some logic to verify that the request really comes from the remote server) and some basic rules like "Deny all", "Never ask again", …

**Comment by nickvergessen** [comment]
Btw the notification app has no problem with this. By default it only shows the last 25 notifications:
https://github.com/owncloud/notifications/blob/master/lib/handler.php#L143

But of course when you remove all those 25, the next poll will bring new 25 notifications. But at least it's not killing the web UI

**Comment by rullzer** [comment]
Like @LukasReschke said. There are always ways around this.
But we could for example in the federation app count the number of unaccepted incomming federated shares from a remote user... and if that is more than N return something like status code 429 ( Too Many Requests ).

Attackers could hack around that... but if you want to be able to receive federated shares there will always be a problem like this...
