### ISSUE TITLE
Setting enable_avatar to false with occ causes some bugs

### ISSUE THREAD

**Issue by Pookay** [owncloud/core#21949]
Hello,
I'm Installing owncloud 8.2.2 on CentOS 6.6 with php7

When I set enable_avatar to false through occ, with this command :

    sudo -u apache php ${oc_dir}/occ config:system:set enable_avatars --value="false"

* First it just disable the avatar in the "Personnal" page but not the tiny picture beside the display name (photos of LDAP users are automatically used when I plug my LDAP on owncloud).
* Then when I go on the user's admin page, loading never ends. Even if I do not enable LDAP user backend app and admin is the only user.

**Comment by MorrisJobke** [comment]
> ``` 
> sudo -u apache php ${oc_dir}/occ config:system:set enable_avatars --value="false"
> ```

running the occ command form somewhere else and not the owncloud root folder is supported starting with ownCloud 9.0

**Comment by MorrisJobke** [comment]
I will test your reported issue

**Comment by MorrisJobke** [comment]
the correct command would be:

```
sudo -u apache php occ config:system:set enable_avatars --value="false" --type=boolean
```


Does this then work for you?

**Comment by MorrisJobke** [comment]
Fix is in #21953

**Comment by nickvergessen** [comment]
type was added for 9.0, so no chance to en/disable avatars via console in 8.2

**Comment by Pookay** [comment]
Thank you,
If it's not working for 8.2 by the occ. Manual edit of config/config.php seems to work to disable/enable avatars.
