### ISSUE TITLE
Support config directory outside of ownCloud application directory.

### ISSUE THREAD

**Issue by kyrofa** [owncloud/core#21965]
ownCloud supports both an apps directory and a data directory which is outside of the application directory. Really the only support it's missing is for the config directory itself to be outside of the application directory.

Rationale/use-case: installing/running ownCloud on Ubuntu Core (the Ubuntu distribution targeting the Internet of Things). All applications on Ubuntu Core are read-only, and run in a strictly confined environment. In this case, the application is ownCloud. There are only a few places where ownCloud is allowed to write, and into the application directory isn't one of them. ownCloud does of course support read-only configs, but that greatly limits what the users can do (e.g. update mail settings, etc.).

Proposal: Support an out-of-application config directory that can be specified via an environment variable: `$OWNCLOUD_CONFIG_DIR` perhaps. This would need to affect both the config.php as well as autoconfig.php.

I have these changes made in a fork. I'm creating this issue to begin a discussion, and determine if this change would be welcome upstream.

**Comment by Xenopathic** [comment]
And symlinks don't work why?

**Comment by kyrofa** [comment]
Ah, good question @Xenopathic, thank you.

There are a number of reasons symlinks don't work:

- .snaps containing symlinks that point outside of the .snap itself (which is the read-only area) violates store policy and can't be published.
- The directories where applications are allowed to write change depending on a number of factors (vendor, version, method of install, etc.), and can't be determined at package creation time. They're provided to the application via environment variables.

**Comment by DeepDiver1975** [comment]
We have been discussing this multiple times.
This is now a path we are willing to walk.

I'll link the other issue later - I'm on my mobile.

**Comment by kyrofa** [comment]
@DeepDiver1975 sorry about that, I tried to find another issue for this but didn't see one. Please do link it when you get a chance. If my approach sounds interesting to I can make a PR.

**Comment by kyrofa** [comment]
> This is now a path we are willing to walk.

I misunderstood this, so to make this issue clearer, after our conversation on IRC, I believe this should say "This is **not** a path we are willing to walk."
