### ISSUE TITLE
Personal mount points using login credentials cannot be shared.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#21962]
### Steps to reproduce

1. Enable external storage, allow users to mount folders. 
2. Using a regular user not admin, go to personal setting and mount a SFTP folder using login credentials store in session.
3. Go to files view.

### Expected behaviour
Sharing button is present.

### Actual behaviour
Sharing button is removed.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Master branch
{"installed":true,"maintenance":false,"version":"9.0.0.6","versionstring":"9.0 pre alpha","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes SFTP.

**Are you using encryption:** 
No

**Logs**

```

```

### Client configuration

**browser**
Chrome

**Comment by SergioBertolinSG** [comment]
Is this by design or this is a bug? @PVince81 @jmaciasportela @icewind1991 ?

**Comment by jmaciasportela** [comment]
It is right. Can not be shared.

**Comment by LukasReschke** [comment]
That's the expected behaviour. You cannot share files from those endpoints as ownCloud has no credentials to access them when the user is not logged-in.

If you want sharing you need to configure stored credentials within the database.

**Comment by SergioBertolinSG** [comment]
great, thanks.
