### ISSUE TITLE
"Log out" menu present if page accessed as guest (@PublicPage)

### ISSUE THREAD

**Issue by Commenter123** [owncloud/core#21977]
Steps to reproduce:
  1. Create a new route for pagecontroller::testPage
  1. The testPage method must have a `@PublicPage` annotation and should return a OCP\AppFramework\Http\TemplateResponse with $renderAs argument not set (`return new TemplateResponse('myapp', 'testPage', array());`)
  1. The guest should not see the "Log out" menu item. Also he should not be able to see the activated apps (top left menu)

![owncloud-non-admin](https://cloud.githubusercontent.com/assets/13712808/12645149/57e76680-c5c8-11e5-985d-d71e14148e7a.png)

**Comment by nickvergessen** [comment]
`$renderAs can be set to "guest", "user" or "admin"`

**Comment by nickvergessen** [comment]
So you should use one of them, or `'blank'` or `''` to not add any header at all.

**Comment by Commenter123** [comment]
As already said, I don't use $renderAs at all.
But I also tried your suggestions, however none of them works as expected.

**Comment by nickvergessen** [comment]
Well default is user, so you render the page as user, instead of guest?
In your controller check, if the user is logged in, then render as user/guest respectivily

**Comment by Commenter123** [comment]
Why doesn't owncloud do this? Hide "Log out" and show "Log in" instead...

**Comment by nickvergessen** [comment]
Well that is what the renderAs value is for, default is "user" and not "we will guess it".
