### ISSUE TITLE
FTP and WebDav external storage setup loses square of connection

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#21976]
### Steps to reproduce

1. Enable external storage.
2. Mount FTP external storage see green dot or red square.
3. Go to files page.
4. Go to admin page again.

### Expected behaviour
Green dot or red square is still there.

### Actual behaviour
Dot/Square is lost.

![screen shot 2016-01-28 at 13 40 14](https://cloud.githubusercontent.com/assets/9048796/12644805/e2fdc9e2-c5c5-11e5-9253-211fb0b80392.png)

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Master branch
{"installed":true,"maintenance":false,"version":"9.0.0.6","versionstring":"9.0 pre alpha","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes FTP and SFTP.

**Are you using encryption:** 
No

**Logs**

```

```

### Client configuration

**browser**
Chrome

**Comment by Xenopathic** [comment]
Probably fixed by #21928

**Comment by SergioBertolinSG** [comment]
Happening in webdav as well.

**Comment by PVince81** [comment]
@SergioBertolinSG is this still an issue with v9.0.3RC1 and v9.1.0beta2 ?

**Comment by SergioBertolinSG** [comment]
Works fine in master.
