### ISSUE TITLE
WebDAV connection leads to failed login attempts with user '(null)'

### ISSUE THREAD

**Issue by fcturner** [owncloud/core#21972]
I finally (might have) found out why my logreader looks like this:

```
WARNING
Thursday 28-01-2016 11:01:00 uur in core:
Login failed: '(null)' (Remote IP: '[removed]')

WARNING
Thursday 28-01-2016 11:00:59 uur in core:
Login failed: '(null)' (Remote IP: '[removed]')

WARNING
Thursday 28-01-2016 11:00:59 uur in core:
Login failed: '(null)' (Remote IP: '[removed]')

WARNING
Thursday 28-01-2016 11:00:59 uur in core:
Login failed: '(null)' (Remote IP: '[removed]')

WARNING
Thursday 28-01-2016 10:45:57 uur in core:
Login failed: '(null)' (Remote IP: '[removed]')

WARNING
Thursday 28-01-2016 10:45:57 uur in core:
Login failed: '(null)' (Remote IP: '[removed]')

WARNING
Thursday 28-01-2016 10:45:57 uur in core:
Login failed: '(null)' (Remote IP: '[removed]')

WARNING
Thursday 28-01-2016 10:45:57 uur in core:
Login failed: '(null)' (Remote IP: '[removed]')

WARNING
Thursday 28-01-2016 10:45:56 uur in core:
Login failed: '(null)' (Remote IP: '[removed]')

WARNING
Thursday 28-01-2016 10:45:56 uur in core:
Login failed: '(null)' (Remote IP: '[removed]')

WARNING
Thursday 28-01-2016 10:45:56 uur in core:
Login failed: '(null)' (Remote IP: '[removed]')

WARNING
Thursday 28-01-2016 08:55:29 uur in core:
Login failed: '(null)' (Remote IP: '[removed]')

WARNING
Thursday 28-01-2016 08:55:29 uur in core:
Login failed: '(null)' (Remote IP: '[removed]')

WARNING
Thursday 28-01-2016 08:55:29 uur in core:
Login failed: '(null)' (Remote IP: '[removed]')

WARNING
Thursday 28-01-2016 08:55:29 uur in core:
Login failed: '(null)' (Remote IP: '[removed]')
```

I removed the IP, but it is the IP of my work, where I connected `https://mydomain/owncloud/remote.php/webdav/` to a drive letter. 

Sometimes, I get 10-15 log entries a second. As you can see above, the top four are within one second, and the next seven are within one second too.

Is this familiar behaviour to you? What can I do to further debug this? 

The biggest disadvantage is that I cannot use fail2ban because of this, as it will jail every IP address I'm connected to. My workaround was to check for `(null)` in the relevant part of `base.php`. Dreadful, of course.

**Comment by PVince81** [comment]
Please use the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md (missing ownCloud version, config, etc)

**Comment by fcturner** [comment]
### Steps to reproduce
1. Connect to WebDAV thru Windows File Explorer (Map Network drive)
2. Sit and wait

### Expected behaviour
No login attempts with user `(null)` (a string, including the round brackets or parentheses or however they call it outside the UK)

### Actual behaviour
Login attempts with user `(null)` (and probably password `(null)` too)

### Server configuration
**Operating system**:
Ubuntu 14.04.3 LTS
**Web server:**
Apache 2.4.7
**Database:**
MySQL
**PHP version:**
5.5
**ownCloud version:** (see ownCloud admin page)
8.2.2
**Updated from an older ownCloud or fresh install:**
Updated
**Signing status (ownCloud 9.0 and above):**
N/A
```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
--> Just redirects to index.php/apps/files/ (yes, I was logged in as admin)
```
Just redirects to index.php/apps/files/
**List of activated apps:**
```php
SELECT `appid` FROM `oc_appconfig` WHERE `configkey` = 'enabled' AND `configvalue` = 'yes':
activity
calendar
contacts
files
files_clipboard
files_pdfviewer
files_sharing
files_texteditor
files_trashbin
files_versions
files_videoviewer
firstrunwizard
gallery
music
notifications
passwords
piwik
provisioning_api
tasks
templateeditor
theme_switcher
updater
```

**The content of config/config.php:**

```php
!! ALL VALUES WITH  => '' ARE HIDDEN ON PURPOSE !!

<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'installed' => true,
  'trusted_domains' => 
  array (
	0 => '',
	1 => '',
	2 => '',
	3 => '',
  ),
  'appstore.experimental.enabled' => true,
  'appstoreenabled' => true,
  'datadirectory' => '/var/www/data/',
  'dbhost' => 'localhost',
  'dbname' => '',
  'dbpassword' => '',
  'dbtableprefix' => 'oc_',
  'dbtype' => 'mysql',
  'dbuser' => '',
  'default_language' => '',
  'forcessl' => true,
  'knowledgebaseenabled' => false,
  'logdateformat' => 'D d-m-Y H:i:s',
  'loglevel' => 2,
  'logtimezone' => '',
  'mail_domain' => '',
  'mail_from_address' => '',
  'mail_smtpauth' => 1,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => '',
  'mail_smtpmode' => 'smtp',
  'mail_smtpname' => '',
  'mail_smtppassword' => '',
  'mail_smtpport' => '465',
  'mail_smtpsecure' => 'ssl',
  'maintenance' => false,
  'overwrite.cli.url' => '',
  'remember_login_cookie_lifetime' => 1296000,
  'secret' => '',
  'session_lifetime' => 3600,
  'theme' => '',
  'updatechecker' => true,
  'version' => '8.2.2.2',
  'enable_avatars' => true,
  'enable_previews' => true,
  'preview_max_scale_factor' => 1,
  'enabledPreviewProviders' => 
  array (
	0 => 'OC\\Preview\\PNG',
	1 => 'OC\\Preview\\JPEG',
	2 => 'OC\\Preview\\GIF',
	11 => 'OC\\Preview\\Illustrator',
	12 => 'OC\\Preview\\Postscript',
	13 => 'OC\\Preview\\Photoshop',
	14 => 'OC\\Preview\\TIFF',
	15 => 'OC\\Preview\\Raw',
  ),
  'trashbin_retention_obligation' => 'disabled',
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Chrome 48
**Operating system:**
Windows 7 SP1
### Logs
#### Web server error log
```
(no relevant entries)
```

#### ownCloud log (data/owncloud.log)
```
(see above)
```

#### Browser log
```
(no relevant entries)
```

**Comment by PVince81** [comment]
@LukasReschke can you evaluate severity ? Thanks

**Comment by cmonteroluque** [comment]
@LukasReschke any thoughts on severity?

**Comment by PVince81** [comment]
@fcturner how are these messages triggered ? Is it about password protected link shares where the user input the wrong password ?

**Comment by fcturner** [comment]
No, I don't know exactly. But it's not from human action, as there are sometimes up to 20 log entries within the same second. Besides, users cannot set a value (null). Empty values would appear as ''. 
Seems like an error in a procedure that calls the password validation check. I think this latter check is being called with empty parameters (value: NULL).

**Comment by PVince81** [comment]
Are you still seeing this in 9.0.5 or 9.1.1 ?

**Comment by fcturner** [comment]
I'll map my ownCloud to a windows drive letter again to try and report back. Thanks in advance.

**Comment by AndreaGiardini** [comment]
Same thing is happening to me. Owncloud 8.2.5

In my case the problem seems to be generated by the iOs client (which, i think, uses webdav). Same symptoms, logs are full of:

```
{"reqId":"LgLYPa\/mDn8Zqy3wGefF","remoteAddr":"121.121.121.121","app":"core","message":"Login failed: '(null)' (Remote IP: '121.121.121.121')","level":2,"time":"2016-10-06T00:43:53+02:00"}
```

**Comment by AndreaGiardini** [comment]
I upgraded my owncloud installation to version 9.1.1 and the problem seems gone... i will report if i have any news

**Comment by fcturner** [comment]
Gone in 9.1.0. :+1:

**Comment by PVince81** [comment]
Thanks for the feedback, I'm closing this then.

I suspect it might be related to the changes/cleanup in the auth code that happened when introducing token based auth + two factor. Maybe it indirectly fixed that issue.

**Comment by AndreaGiardini** [comment]
Updating to version 9.1.2 re-introduced the issue! Please re-open the issue

**Comment by AndreaGiardini** [comment]
```
{"reqId":"5VeFW1C1AvgUIwB6wZHL","remoteAddr":"X.X.X.X","app":"core",
"message":"Login failed: '(null)' (Remote IP: 'X.X.X.X')","level":2,
"time":"2016-12-24T14:59:49+01:00","method":"GET",
"url":"\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/shares?path=&subfiles=true","user":"--"}
{"reqId":"IpZ8eYUpfMqGA5UYDxy4","remoteAddr":"X.X.X.X","app":"core",
"message":"Login failed: '(null)' (Remote IP: 'X.X.X.X')","level":2,"time":"2016-12-24T14:59:50+01:00","method":"PROPFIND",
"url":"\/remote.php\/webdav\/","user":"--"}
{"reqId":"oswk\/OENMPtZGMzVqMAY","remoteAddr":"X.X.X.X","app":"core",
"message":"Login failed: '(null)' (Remote IP: 'X.X.X.X')","level":2,"time":"2016-12-24T14:59:50+01:00","method":"GET",
"url":"\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/shares?path=&subfiles=true","user":"--"}
{"reqId":"mwJb7WZPnMpGzmKwQWWL","remoteAddr":"X.X.X.X","app":"core",
"message":"Login failed: '(null)' (Remote IP: 'X.X.X.X')","level":2,"time":"2016-12-24T14:59:50+01:00","method":"GET",
"url":"\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/shares","user":"--"}
```

**Comment by AndreaGiardini** [comment]
@fcturner Do you have this issue with 9.1.2 ?

**Comment by AndreaGiardini** [comment]
Indeed... the problem seems to be the iOs application... at least in my case

New bug: https://github.com/owncloud/ios/issues/824

**Comment by PVince81** [comment]
Hmm, maybe the ios app is trying to authenticate using the OCS endpoints and it somehow fails ?

**Comment by fcturner** [comment]
Yes, I could confirm this was caused by the iOS app. We should continue there:  https://github.com/owncloud/ios/issues/824
