### ISSUE TITLE
Upload error: 3 - The uploaded file was only partially uploaded 

### ISSUE THREAD

**Issue by lfratini** [owncloud/core#21973]
Hi We have this problem on our production enviornment 
When upload a 4Gb file  from Browser , the upload file with the message in object  
The environment :
Linux Centos 7.1 with Nginx 1.9.5-1 as Reverse Proxy as Front End 
Linux Centos 7.1 with Owncloud 8.0.0-27.1 , mariadb-server-5.5.41-2

The configuration of Nginx for FE of Virtual Host is  

```
client_body_buffer_size 40k;
client_header_buffer_size 4k;
 client_max_body_size 24G; # set max upload size
 fastcgi_buffers 64 16K;
 sendfile on;
 tcp_nopush on;
  tcp_nodelay on;

 location / {
proxy_set_header Host $host;
proxy_pass https://owncloud.local;
 proxy_set_header   Host   $host;
 proxy_set_header   X-Real-IP  $remote_addr;
 proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
 proxy_buffering off;
proxy_request_buffering off;
proxy_read_timeout 300;
        }
```

The configuration for Ngin 

BE is attached

**Comment by PVince81** [comment]
ownCloud 8.0.0 is quite old.

Please try with 8.0.9 or the more recent 8.1.5 or 8.2.2.

Which web browser ?

**Comment by PVince81** [comment]
Also note, this is a bug tracker.
If you need support, see https://owncloud.org/support

If you still have problems with recent ownCloud versions and think it's a bug, feel free to reopen and use the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by lfratini** [comment]
Hi Vincent

the browser is Internet Explorer 11 and Firefox 44 .
