### ISSUE TITLE
Get rid of mimetype table, compute on the fly by extension

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#21974]
Since at least OC 7 we compute the mime type based on the file's extension instead of the old slow `finfo` approach which didn't work well on external storages.

We still have the "oc_mimetypes" table and that table is kept up to date by repair scripts when new mime types are added.

How about just removing that table and compute the mime types on the fly based on the file's extension ? Are there any code paths that cannot use this approach ?

@karlitschek @DeepDiver1975 @icewind1991 @oparoz @nickvergessen @MorrisJobke

**Comment by PVince81** [comment]
aaaaand @rullzer @Xenopathic

**Comment by DeepDiver1975** [comment]
We have search capabilities by mimetype which use this information AFAIK.

Searching using like within the cache table for file extensions is a pain.

**Comment by PVince81** [comment]
Yeah, this was originally @karlitschek's idea but then after I posted this ticket he also remembered that.

So probably not a good idea => closing
