### ISSUE TITLE
FTP and WebDav mounts can't be updated in administration page.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#21978]
### Steps to reproduce

1. Enable external storage.
2. Mount FTP external storage.
3. Check that user can access storage.
4. Edit mount point, restrict it for admin user only, for example. (Any update won't be stored).
5. Refresh page, check if the update is still there.

### Expected behaviour
Changes are stored. Admin is able to modify mount point.

### Actual behaviour
Nothing is stored in modification. Admin has to delete and create a new mount.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Master branch
{"installed":true,"maintenance":false,"version":"9.0.0.6","versionstring":"9.0 pre alpha","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes FTP.

**Are you using encryption:** 
No

**Logs**

```

```

### Client configuration

**browser**
Chrome

**Comment by SergioBertolinSG** [comment]
This happens also with WebDav mounts.

**Comment by Xenopathic** [comment]
Let me guess, you have 'Secure https://' checkbox unchecked? If so, this is just yet another iteration of #21928

**Comment by SergioBertolinSG** [comment]
Yes.

**Comment by PVince81** [comment]
The PR that fixes validation was fixed, can you try again with 9.0beta1 ?

**Comment by SergioBertolinSG** [comment]
Works fine on 9.0beta1.
