### ISSUE TITLE
FTP users can't use mount points using login credentials if their password is updated in both FTP server and oC.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#21982]
### Steps to reproduce

1. Enable external storage.
2. Mount FTP external storage using login credentials stored on database or session correctly.
3. Check that user can access storage.
4. Change password for user in FTP server.
5. Check red row appears due to failed login. 
6. Change password for user in owncloud and relogin in oC.
7. Try to access the FTP mounted folder.

### Expected behaviour
User can access the mount point without problems, since he has updated the password.

### Actual behaviour
User can't access the mount point anymore.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Master branch
{"installed":true,"maintenance":false,"version":"9.0.0.6","versionstring":"9.0 pre alpha","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes FTP.

**Are you using encryption:** 
No

**Logs**

```
{"reqId":"xIBy4NocyKthRO1hnJoC","remoteAddr":"HIDED_IP","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Storage not available\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(903): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('FTP2')\\n#1 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(336): Sabre\\\\DAV\\\\Server->getPropertiesForPath('FTP2', Array, 1)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#5 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(53): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/opt\\\/owncloud\\\/remote.php(137): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#8 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/objecttree.php\",\"Line\":157}","level":4,"time":"2016-01-28T13:47:29+00:00"}
```

### Client configuration

**browser**
Chrome

**Comment by PVince81** [comment]
@SergioBertolinSG I think the user will be able to access the storage after 10 minutes ?

If yes, the bug is probably that the storage is marked unavailable for 10 minutes, but changing the config/credentials should reset that timeout. @Xenopathic

**Comment by PVince81** [comment]
Any update, is this still happening ?

**Comment by PVince81** [comment]
@davitol can you verify?

**Comment by davitol** [comment]
@PVince81 It still happening

**Comment by Xenopathic** [comment]
Changing storage configuration in the mount config GUI triggers a recheck, which resets the storage availability, but logging in with a storage that uses login credentials does not trigger this recheck. If we do it synchronously with the login process however, it will make logins veeeery slow for users with lots of storages, but I don't see any other way of doing it such that WebDAV clients still trigger it.

**Comment by PVince81** [comment]
@jmaciasportela did this work before with WND ? If yes, how ?

**Comment by jmaciasportela** [comment]
@PVince81 Using both types of login credentials, it works fine for me:

```
{"installed":true,"maintenance":false,"version":"9.0.0.11","versionstring":"9.0 beta 1","edition":"Enterprise"}
```
Following the same steps:

1. Enable external storage.
2. Mount FTP external storage using login credentials stored on database or session correctly.
3. Check that user can access storage.
4. Change password for user in FTP server.
5. Check red row appears due to failed login.
6. Change password for user in owncloud and relogin in oC.
    Try to access the FTP mounted folder.

![captura de pantalla de 2016-02-26 12-33-00](https://cloud.githubusercontent.com/assets/1454351/13351495/3d2109f2-dc87-11e5-92c0-b9db53468dd5.png)

**Comment by jmaciasportela** [comment]
TEST ENVIRONMENT
- http://docker.oc.solidgear.es:55568/
- admin/Password
- maci/maci

FTP config url: localhost  -> login with user maci
ssh -p 55570 root@docker.oc.solidgear.es "passwd maci"

**Comment by davitol** [comment]
Checked and works. Maybe in the previous test I did not log out and log in 'to refresh' the credentials
