### ISSUE TITLE
[LDAP] throw pre_addToGroup hooks

### ISSUE THREAD

**Issue by blizzz** [owncloud/core#21986]
If/When #21854 is merged, LDAP needs to throw pre_addToGroup hooks on the crun job, when group memberships are updated, cf. https://github.com/owncloud/core/pull/21854#issuecomment-174198467

**Comment by PVince81** [comment]
@blizzz bug or enhancement ? Which severity ?

**Comment by blizzz** [comment]
@PVince81 would be just like #21854 :see_no_evil:

**Comment by MorrisJobke** [comment]
@PVince81 Usually has nothing to do with me - I guess this was a reminder ticket for @blizzz

**Comment by blizzz** [comment]
Yep, in case #21854 gets merged. And it really happened a bit earlier today.

**Comment by blizzz** [comment]
Turns out to be not necessary, cf. https://github.com/owncloud/core/pull/22664#issuecomment-189458101
