### ISSUE TITLE
execution of occ commands via web requests

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#21985]
we are basically coming from here:
https://github.com/owncloud/updater/pull/217#issuecomment-176185631

So in CLI mode the new updater can easily execute occ and process it's json output. No brainer.

But in the web based updater ui we cannot rely on being allowed to spawn off the occ cli tool.

So from my understanding we need a way to execute some/all occ commands via web requests.

Something like 

````
POST https://domain.tld/owncloud/index.php/occ/app:list?format=json
````

Access should be limited - e.g. by using a shared key/secret between the updater and the owncloud instance by placing a commonly used file into config or data dir.

This could also be used to by pass maintenance mode checks - if necessary.

@VicDeo @karlitschek @PVince81 @LukasReschke fire your :gun:s and throw your :bomb:s and :hocho:s at these ideas. THX

**Comment by PVince81** [comment]
Ideal is then to have a generic mapper that maps to command, else we'd need to write some kind of adapter for every command... time consuming. And have a whitelist of allowed commands.

Yeah, sounds good.

**Comment by LukasReschke** [comment]
> Access should be limited - e.g. by using a shared key/secret between the updater and the owncloud instance by placing a commonly used file into config or data dir.

I'd vote for some signing mechanism that also includes an expiration date. (e.g. admin leaves organisation => should not be able to execute commands in the future)

JWT offers all of this: http://jwt.io/introduction/

**Comment by DeepDiver1975** [comment]
> I'd vote for some signing mechanism that also includes an expiration date. (e.g. admin leaves organisation => should not be able to execute commands in the future)

I was mote thinking about this:
1. updater wants to execute a web occ request
2. places new secret into the config folder
3. updater executes the request
4. owncloud processes the request
5. owncloud removes the file

**Comment by DeepDiver1975** [comment]
Note that the updater has to have some authentication mechanisms already to restrict access. maybe some stupid password hash file like apache auth works

**Comment by karlitschek** [comment]
O.K. But more important is the actual password protection of the web UI itself. Not sure how this can be done. Maybe ownCloud generates a hash and stores it in the config.php. The link from the admin page to the update then reads the hash from the config file and adds it to the updater url with GET. The updater then compares the hash with the one in the config file.
This would mean of course that there is no user friendly way to use the web ui if an admin doesn't come from the admin page. But this is O.K. I guess.
Opinions?

**Comment by DeepDiver1975** [comment]
> Opinions?

We have to take this into account as well - very true. Worth a ticket in the updater repo about web auth

**Comment by DeepDiver1975** [comment]
web ui auth is handled in https://github.com/owncloud/updater/issues/220

**Comment by PVince81** [comment]
From what I heard this is done, close ?

**Comment by DeepDiver1975** [comment]
> From what I heard this is done, close ?

not that I'm aware of

**Comment by LukasReschke** [comment]
https://github.com/owncloud/updater/blob/dcc32bced24c6f86d2a3387f9dd60db42457f843/src/Controller/IndexController.php#L118-L146 implements this.

**Comment by DeepDiver1975** [comment]
this would mean that the updater is loading core code - which break the concept.

**Comment by PVince81** [comment]
Converting to bug, sev2-high due to discutable approach. Let's look into improving this in 9.1

**Comment by DeepDiver1975** [comment]
> Converting to bug, sev2-high due to discutable approach. Let's look into improving this in 9.1

I fear this is too late ... as soon as 9.0 is out we need this

**Comment by VicDeo** [comment]
@DeepDiver1975 @LukasReschke what if we reuse an existing token from config.php for authorisation?

**Comment by PVince81** [comment]
QA ticket: https://github.com/owncloud/QA/issues/277

So far it looks like we only need to review these backports and this is finished:
- https://github.com/owncloud/updater/pull/362
- https://github.com/owncloud/updater/pull/363

@VicDeo can you double check whether I missed anything ?

**Comment by PVince81** [comment]
I suggest to put this into 9.1 (post RC1)

**Comment by PVince81** [comment]
All done -> closing
