### ISSUE TITLE
"Global credentials" auth backend for external storages

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#21991]
- provide two fields "Username" and "Password" in the admin page (and also user page)
- the credentials from these fields are stored in the CredentialManager
- all backends that support username and password also have the new option "Global credentials" in the auth backend list, which will make them use whichever credentials were input in the new fields

@jmaciasportela @Xenopathic @icewind1991 @MTRichards

**Comment by MTRichards** [comment]
Thank you.

**Comment by PVince81** [comment]
PR is here https://github.com/owncloud/core/pull/22107
