### ISSUE TITLE
Federated cloud shares make android client crash

### ISSUE THREAD

**Issue by acolad** [owncloud/core#22014]
### Steps to reproduce
1. Share any file or folder to an external owncloud user (federated cloud)
2. With the android app browse to the folder containing the data you just shared
3. Android app crashes as soon as it wants to list the given data

### Expected behaviour
Android app shouldn't crash just because it sees data shared to a federated cloud user

### Actual behaviour
Android app crashes as explained in "Steps to reproduce"

### Server configuration
**Operating system**:
CentOS7

**Web server:**
Apache 2.4.6

**Database:**
MariaDB 5.5.44

**PHP version:**
5.5.31

**ownCloud version:** (see ownCloud admin page)
8.2.2

**Updated from an older ownCloud or fresh install:**
Upgraded since 8.1 (I think)

**Signing status (ownCloud 9.0 and above):**
N/A

**Android app version**
1.9.0

**List of activated apps:**
Only official apps + approved "Files Move" app

Enabled:
  - activity: 2.1.3
  - files: 1.2.0
  - files_external: 0.3.0
  - files_mv: 0.8.1a
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - updater: 0.6
Disabled:
  - encryption
  - external
  - gallery
  - user_external
  - user_ldap

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => '###SensitiveRemoved###',
  'passwordsalt' => '###SensitiveRemoved###',
  'secret' => '###SensitiveRemoved###',
  'trusted_domains' =>
  array (
    0 => '###SensitiveRemoved###',
  ),
  'datadirectory' => '###SensitiveRemoved###',
  'overwrite.cli.url' => '###SensitiveRemoved###',
  'dbtype' => 'mysql',
  'version' => '8.2.2.2',
  'dbname' => '###SensitiveRemoved###',
  'dbhost' => 'localhost',
  'dbtableprefix' => '###SensitiveRemoved###',
  'dbuser' => '###SensitiveRemoved###',
  'dbpassword' => '###SensitiveRemoved###',
  'logtimezone' => 'Europe/Zurich',
  'installed' => true,
  'mail_from_address' => '###SensitiveRemoved###',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => '###SensitiveRemoved###',
  'theme' => '',
  'loglevel' => 2,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'maintenance' => false,
  'trashbin_retention_obligation' => 'auto',
  'updatechecker' => true,
  'appstore.experimental.enabled' => true,
  'mail_smtphost' => '###SensitiveRemoved###',
  'mail_smtpport' => '25',
  'activity_expire_days' => '7',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes, 1 local

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
iE and Firefox (but unrelated information)

**Operating system:**
Win7x64 (but unrelated information)

**Comment by karlitschek** [comment]
looks like a bug in the android app. Please open this bug report in the android repository. thanks.
