### ISSUE TITLE
Share by is always the same as the first received share

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#22019]
* have 3 users: userA, userB, userC
* userA has two folders: abc and def
* userA shares abc with userB
* userB shares abc with userC
* userA shares def with userC

### expected

* userC sees abc (owner userA - in file list) and in the sidebar - "shared by userB"
* userC sees def (owner userA -in file list) and in the sidebar: "shared by userA"

### actual

* userC sees abc (owner userA - in file list) and in the sidebar - "shared by userB"
* userC sees def (owner userA -in file list) and in the sidebar: "shared by **userB**"

I also noticed that the "shared by..." text is always using the name that is listed in the users first incoming share. All later shares are shown as they are shared by the same person as the first share was shared from.

cc @rullzer @schiesbn

**Comment by rullzer** [comment]
Lets see if this is just a display issue or an actual API issue...

**Comment by rullzer** [comment]
Aaaah the returned API info is correct... I think it is just the filtering of it that goes wrong...

Let me add the api call properly...

**Comment by rullzer** [comment]
fix in progress... will also make the clients happy...
