### ISSUE TITLE
LDAP users cleanup don't quite work

### ISSUE THREAD

**Issue by kalletabur** [owncloud/core#22024]
### Steps to reproduce
1. Disable Active Directory user and take user out the owncloud group
2. Enable ldapUserCleanupInterval in config.php
3. Check with sudo -u www-data php occ ldap:show-remnants to see how many and what users you should manually delete

### Expected behaviour
All disabled users, or users who don't belong to owncloud group, should be shown in this remnants list.

### Actual behaviour
Remnants list is emptied, users cannot be deleted

### More detailed explanation
We have used owncloud quite a while but haven't so far dealt with old users.
We use LDAP users (Active Directory). Since we have old users I tried removing them.

We didn't have ldapUserCleanupInterval settings in config.php. I just manually removed couple of users just to see what happens with files, DB etc.

I used ldap:show-remnants occ command and 19 old accounts and deleted 2 of them.
Log file entry
```
... "app":"user_ldap","message":"Cleaning up after user u.user1","level":1 ...
```
Then I wanted to try automate this with ldapUserCleanupInterval
I set it up and let it run a while and now ldap:show-remnants is empty.

```
sudo -u www-data php occ ldap:show-remnants
+---------------+--------------+----------+---------+------------+-----+--------+
| ownCloud name | Display Name | LDAP UID | LDAP DN | Last Login | Dir | Sharer |
+---------------+--------------+----------+---------+------------+-----+--------+
```

So I checked old users folders and these still existed. I checked DB and for every user (shown in ldap:show-remnants list) have entries in oc_preferences table and all of them had configKey isDeleted with configvalue 0

```
mysql> select * from oc_preferences where configkey='isDeleted';
+--------------+-----------+-----------+-------------+
| userid       | appid     | configkey | configvalue |
+--------------+-----------+-----------+-------------+
| u.user2      | user_ldap | isDeleted | 0           |
| u.user3      | user_ldap | isDeleted | 0           |
| u.user4      | user_ldap | isDeleted | 0           |
...
```

Ok, maybe this was meant to be that I delete these users by hand. I then tried to delete one of these users
```
sudo -u www-data php occ user:delete u.user2
```
but no luck
Message on command line
```
"The specified user could not be deleted. Please check the logs."
```
and in log file
```
... "app":"user_ldap","message":"User u.user2 is not marked as deleted, not cleaning up.","level":1 ...
```

I checked and these users are inactive in Active Directory.

I also find couple of more users who are inactive in AD but owncloud didn't show these as remnants. These users have home dir. These users also cannot be deleted. Same messages.
None of these inactive users are shown in owncloud web admin Users list.

### Server configuration
**Operating system**:
Debian 8.2
**Web server:**
nginx
**Database:**
mysql
**PHP version:**
PHP 5.6.14-0+deb8u1
**ownCloud version:** (see ownCloud admin page)
8.2.2 (stable)
**Updated from an older ownCloud or fresh install:**
updated

```
http://example.com/index.php/settings/integrity/failed 

send me back to 
https://example.com/index.php/apps/files/

```

**List of activated apps:**

```
Enabled:
  - activity: 2.1.3
  - contacts: 0.5.0.0
  - documents: 0.11.0
  - encryption: 1.1.0
  - files: 1.2.0
  - files_external: 0.3.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - user_ldap: 0.7.1
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc19d4c8f8b1",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "10.10.10.10",
        ],
        "datadirectory": "\/var\/ownc\/",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "ownclouddb_dev",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "forcessl": true,
        "loglevel": 1,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "exch1",
        "mail_smtpport": "25",
        "logtimezone": "Europe\/Tallinn",
        "theme": "",
        "share_folder": "\/Shared",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": false,
        "appstore.experimental.enabled": true,
        "trashbin_retention_obligation": "auto",
        "ldapUserCleanupInterval": 60
    }
}

```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
+-------------------------------++
| Configuration                 | s01|++
| hasMemberOfFilterSupport      | 1|
| hasPagedResultSupport         ||
| homeFolderNamingRule          |   |
| lastJpegPhotoLookup           | 0 |
| ldapAgentName                 | CN=owncloudDC=local              |
| ldapAgentPassword             | ***                   |
| ldapAttributesForGroupSearch  |   |
| ldapAttributesForUserSearch   |   |
| ldapBackupHost                |   |
| ldapBackupPort                |   |
| ldapBase  | DC=local|
| ldapBaseGroups                | DC=local|
| ldapBaseUsers                 | DC=local|
| ldapCacheTTL                  | 600                   |
| ldapConfigurationActive       | 1 |
| ldapEmailAttribute            | mail                  |
| ldapExperiencedAdmin          | 0 |
| ldapExpertUUIDGroupAttr       |   |
| ldapExpertUUIDUserAttr        |   |
| ldapExpertUsernameAttr        | sAMAccountName        |
| ldapGroupDisplayName          | cn|
| ldapGroupFilter               | (&(|(objectclass=group))(|(cn=Tal-Dev)(cn=Tal-Owncloud)(cn=Tal-Sys)))    |
| ldapGroupFilterGroups         | Tal-Dev;Tal-Owncloud;Tal-Sys     |
| ldapGroupFilterMode           | 0 |
| ldapGroupFilterObjectclass    | group                 |
| ldapGroupMemberAssocAttr      | member                |
| ldapHost  | tll1-dc3              |
| ldapIgnoreNamingRules         |   |
| ldapLoginFilter               | (&(&(|(objectclass=person))(|(|(memberof=CN=Tal-Sys,DC=local)(primaryGroupID=13778))))(samaccountname=%uid))                 |
| ldapLoginFilterAttributes     |   |
| ldapLoginFilterEmail          | 0 |
| ldapLoginFilterMode           | 1 |
| ldapLoginFilterUsername       | 1 |
| ldapNestedGroups              | 0 |
| ldapOverrideMainServer        | 0 |
| ldapPagingSize                | 500                   |
| ldapPort  | 389                   |
| ldapQuotaAttribute            |   |
| ldapQuotaDefault              |   |
| ldapTLS   | 0 |
| ldapUserDisplayName           | displayname           |
| ldapUserFilter                | (&(|(objectclass=person))(|(memberof=CN=Tal-Owncloud,DC=local)(memberof=CN=Tal-Dev,DC=local)(memberof=CN=Tal-Sys,DC=local))) |
| ldapUserFilterGroups          |   |
| ldapUserFilterMode            | 1 |
| ldapUserFilterObjectclass     | person                |
| ldapUuidGroupAttribute        | auto                  |
| ldapUuidUserAttribute         | auto                  |
| turnOffCertCheck              | 1 |
| useMemberOfToDetectMembership | 1 |
+-------------------------------++
```

#### ownCloud log (data/owncloud.log)
```
"app":"user_ldap","message":"User u.user2 is not marked as deleted, not cleaning up.","level":1
```

**Comment by LukasReschke** [comment]
@owncloud/ldap

**Comment by MorrisJobke** [comment]
Every 51 minutes are 50 users scanned - https://github.com/owncloud/core/blob/682821c71ed2af297170294632931be1ac769f25/apps/user_ldap/lib/jobs/cleanup.php#L42-L45

It could take some time until all users are scanned.

@kalletabur How long did you wait until you checked the remnants? Maybe they will show up a bit later.

**Comment by kalletabur** [comment]
I have waited days. I configured this config.php last week - and still the remnants list is empty. And I haven't (been able to) removed users since.

**Comment by blizzz** [comment]
Up to and including  8.2, only LDAP users that are actually **deleted** on LDAP are considered gone. Intentionally.

Starting 9.0  the behaviour is changed and allows clean up of user that cannot be find with the configured filters. Related PR: https://github.com/owncloud/core/pull/18212

**Comment by MegaBrutal** [comment]
I'm not sure if I experience the same issue with ownCloud 9.1, but LDAP users whose accesses have been revoked (not qualifying the LDAP filters anymore) are still happily log in to the ownCloud instance. I don't really want them to be permanently removed automatically, but it would be great if
– ownCloud would not allow them to log in while they are excluded by the filters;
– I would have an option to MANUALLY remove them if I want to.
This way, I could temporarily ban users or have them deleted permanently, whichever I choose. Is it the right issue to discuss this, or should I open a new?
