### ISSUE TITLE
»Authorisation request« credentials popup sometimes when reopening browser

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#22020]
Not sure if this really is a problem in ownCloud core – but I get it with both Mail and Contacts-Rework, so I assume it’s not specific to an app.

Oftentimes when I reopen the browser after a restart, the ownCloud tab gets focus and this annoying window pops up:
![capture du 2016-01-28 14-47-19](https://cloud.githubusercontent.com/assets/925062/12677510/d91f231a-c699-11e5-8a41-0ce56b7c7128.png)
Or this (note the »sabre/dav«):
![capture du 2016-01-28 14-47-33](https://cloud.githubusercontent.com/assets/925062/12677511/d9243b70-c699-11e5-9e10-6c7b1c37bc11.png)

Any idea @DeepDiver1975?

**Comment by PVince81** [comment]
@DeepDiver1975 you might need to pass "X-Requested-With: XMLHttpRequest" in your Webdav requests. In that case you should get a 401 error that needs to be redirected to the login page (session timeout case).

**Comment by PVince81** [comment]
To test: a timing out session in the contacts/calendar app. It is likely that this is what is causing this dialog to appear.

**Comment by DeepDiver1975** [comment]
> you might need to pass "X-Requested-With: XMLHttpRequest" in your Webdav

@PVince81 you mean the apps (js code) need to pass in that header on every request - right?

**Comment by PVince81** [comment]
@DeepDiver1975 yes. Because it is used in the backend to find out whether the request comes from JS or not: https://github.com/owncloud/core/blob/32067ac49b6f891471a6b5672c903a390b4ac26d/apps/dav/lib/connector/sabre/auth.php#L168

If it comes from JS, then it uses a dummy auth scheme to prevent the dialog to appear. It also makes it possible for JS code to catch 401 codes.

**Comment by DeepDiver1975** [comment]
so we need to let the devs of the apps know about this one

**Comment by jancborchardt** [comment]
Any progress here? cc @Henni for the Contacts app.

**Comment by PVince81** [comment]
I found that even if apps are using jQuery, as soon as either an OCS API or REST API (app framework) is used, a 401 error will still trigger the auth dialog.

A possible solution is in the works: https://github.com/owncloud/core/pull/16783

**Comment by PVince81** [comment]
Fixed with https://github.com/owncloud/core/pull/16783
