### ISSUE TITLE
Show deleted files from a shared folder to everyone with access to that folder

### ISSUE THREAD

**Issue by colomar** [owncloud/core#22027]
When someone deletes a file within a shared folder, it is only visible in the folder owner's "Deleted files". This means that nobody else who has access to the folder can restore the file, making the owner a potential bottleneck.
It should instead be visible to anyone with read access to the folder, and restorable to everyone with write access.

**Comment by MorrisJobke** [comment]
> When someone deletes a file within a shared folder, it is only visible in the folder owner's "Deleted files".

It is also visible to the person who deleted the shared file.

cc @schiesbn

**Comment by colomar** [comment]
Ah yes, sorry, I forgot to mention that. I know.
The issue is that if a folder is shared with many users, one first has to identify who deleted it in order to recover it.

Here is the situation we have (maybe there's a better way to do what we want to do in the first place, I don't know): Our ownCloud installation is hooked up to an LDAP with hundreds of users. Each user has a 100MB space limit for their personal files.
However, we have a (rather big) group which needs a lot of storage space. For that, the sysadmins have created an account with unlimited space who shares a folder with this group.
Now if someone accidentally deletes a file which someone else in the group still needs and the latter person would like to restore the file, he or she has to either contact the sysadmins or has to find out who deleted the file.

This may or may not be a very exotic setup, but in this setup, it would be really helpful if any member of the group could restore a file from the shared folder, regardless of who originally deleted it.

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/issues/24053
