### ISSUE TITLE
No dropdown list of names when sharing folders

### ISSUE THREAD

**Issue by NickyHendriks** [owncloud/core#22039]
Hi there,

If I try to share a folder with a group, in my case that'd be 'Others', I only get the loading-icon for a second, and then it disappears and nothing happens next.

Now I can't share any folders, which I'd like to do.

I am using Apache2 with the latest version of ownCloud, running on Ubuntu 14.04LTS. I already tried it on different devices and browsers.

Hope anybody can help.

**Comment by LukasReschke** [comment]
Please fill out the issue template as can be seen at https://github.com/owncloud/core/blob/master/CONTRIBUTING.md
