### ISSUE TITLE
ownCloud discovery through bonjour/zeroconf

### ISSUE THREAD

**Issue by mitar** [owncloud/core#22037]
It is possible to mount ownCloud using Webdav from Mac OS X Finder. But it would be even better if it would appear through Bonjour/Zeroconf automatically among networked devices/services.

**Comment by PVince81** [comment]
I thought about this before. It might already possible to create a custom file in `/etc/avahi/services` to make ownCloud visible without requiring any changes in the PHP code.

**Comment by RealRancor** [comment]
Its probably also only possible to use it that way as ownCloud itself would need an own Daemon or am i wrong?

**Comment by DeepDiver1975** [comment]
> I thought about this before. It might already possible to create a custom file in /etc/avahi/services to make ownCloud visible without requiring any changes in the PHP code.

This seems to be the way to go - nothing really we can do from the code base perspective.
http://kodi.wiki/view/Avahi_Zeroconf

We might want to give this a try and come up with a proper sample config and add this to our documentation.

**Comment by PVince81** [comment]
duplicate of https://github.com/owncloud/core/issues/12318
