### ISSUE TITLE
occ upgrade: An exception occurred while executing 'INSERT INTO `oc_oc_jobs_qdbremjhzj23w` SELECT * FROM `oc_jobs`'

### ISSUE THREAD

**Issue by friedrico** [owncloud/core#22038]
Server: 
> uname -a
> Linux NAS 3.4.6 #1 Tue Jan 19 10:55:12 CST 2016 armv5tel unknown

Database: 
> mysql --version
> /usr/local/mariadb/bin/mysql  Ver 15.1 Distrib 5.5.44-MariaDB, for Linux () using readline 5.1

OC-Version:
> cat version.php 
> <?php 
> $OC_Version = array(8,2,2,2);
> $OC_VersionString = '8.2.2';
> $OC_Edition = '';
> $OC_Channel = 'stable';
> $OC_VersionCanBeUpgradedFrom = array(8,1);
> $OC_Build = '2015-12-21T12:52:55+00:00 d60d903e75296950a52a0e25c7cd31f5b55ab68f';

PHP-Version:
> phpinfo()
> PHP Version => 5.5.29</code>

my.cnf
> max_allowed_packet = 256M
> wait_timeout = 31536000

tables
> show tables;
> +--------------------------+
> | Tables_in_owncloud       |
> +--------------------------+
> | oc_activity              |
> | oc_activity_mq           |
> | oc_appconfig             |
> | oc_file_locks            |
> | oc_file_map              |
> | oc_filecache             |
> | oc_files_trash           |
> | oc_group_admin           |
> | oc_group_user            |
> | oc_groups                |
> | oc_jobs                  |
> | oc_mimetypes             |
> | oc_notifications         |
> | oc_oc_jobs_9u65xeh8elfu3 |
> | oc_oc_jobs_a6xh57yx7uaxv |
> | oc_oc_jobs_eycygupk3lvjl |
> | oc_oc_jobs_f596tvssr77l6 |
> | oc_oc_jobs_i3qmfiyojg8yw |
> | oc_oc_jobs_p36ifhvtatcc4 |
> | oc_oc_jobs_qdbremjhzj23w |
> | oc_oc_jobs_ra0mdqazrd97z |
> | oc_oc_jobs_w2qti48ffwy87 |
> | oc_preferences           |
> | oc_privatedata           |
> | oc_properties            |
> | oc_share                 |
> | oc_share_external        |
> | oc_storages              |
> | oc_users                 |
> | oc_vcategory             |
> | oc_vcategory_to_object   |
> +--------------------------+

config.php
> cat config/config.php 
> <?php
>   'dbtype' => 'mysql',
>   'version' => '8.2.2.2',
>   'dbtableprefix' => 'oc_',
> );

apache.conf
> <Directory /share/Web/owncloud8>
>         Options Indexes FollowSymLinks MultiViews
>         AllowOverride All
>         Order allow,deny
>         allow from all
> </Directory>

Problem
> ownCloud or one of the apps require upgrade - only a limited number of commands are available
> You may use your browser or the occ upgrade command to do the upgrade
> Set log level to debug - current level: 'Debug'
> Checking whether the database schema can be updated (this can take a long time depending on the database size)
> Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO ```oc_oc_jobs_19ry3h5l0zu1p``` SELECT * FROM ```oc_jobs```':
> 
> SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
> Update failed
> Maintenance mode is kept active
> Reset log level to 'Debug'
> PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in /share/HDB_DATA/Web/owncloud8/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104
> Stack trace:
> #0 /share/HDB_DATA/Web/owncloud8/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(104): PDO->query('SHOW FULL TABLE...')
> #1 /share/HDB_DATA/Web/owncloud8/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(833): Doctrine\DBAL\Driver\PDOConnection->query('SHOW FULL TABLE...')
> #2 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/db/connection.php(182): Doctrine\DBAL\Connection->executeQuery('SHOW FULL TABLE...', Array, Array, NULL)
> #3 /share/HDB_DATA/Web/owncloud8/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(766): OC\DB\Connection->executeQuery('SHOW FULL TABLE...', Array, Array)
> #4 /share/HDB_DATA/Web/owncloud8/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php(219): Doctrine\DBAL\Conne in /share/HDB_DATA/Web/owncloud8/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 115

I didn't do much more than:
> unzipping the tarball
> unzipping the unix user backend
> changing the apache.conf
> calling ./occ upgrade

Log file
> rm data/owncloud.log
> ./occ upgrade
> cat owncloud.log | sed ...
> {"reqId":"+0t8aiJRoG+p9soIsy1t","remoteAddr":"","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at /share/HDB_DATA/Web/owncloud8/owncloud/occ:4) at /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/response.php#254","level":3,"time":"2016-01-30T17:44:03+00:00","method":"--","url":"--"}
> {"reqId":"+0t8aiJRoG+p9soIsy1t","remoteAddr":"","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at /share/HDB_DATA/Web/owncloud8/owncloud/occ:4) at /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/response.php#259","level":3,"time":"2016-01-30T17:44:03+00:00","method":"--","url":"--"}
> {"reqId":"+0t8aiJRoG+p9soIsy1t","remoteAddr":"","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at /share/HDB_DATA/Web/owncloud8/owncloud/occ:4) at /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/response.php#260","level":3,"time":"2016-01-30T17:44:03+00:00","method":"--","url":"--"}
> {"reqId":"+0t8aiJRoG+p9soIsy1t","remoteAddr":"","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at /share/HDB_DATA/Web/owncloud8/owncloud/occ:4) at /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/response.php#261","level":3,"time":"2016-01-30T17:44:03+00:00","method":"--","url":"--"}
> {"reqId":"+0t8aiJRoG+p9soIsy1t","remoteAddr":"","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at /share/HDB_DATA/Web/owncloud8/owncloud/occ:4) at /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/response.php#262","level":3,"time":"2016-01-30T17:44:03+00:00","method":"--","url":"--"}
> {"reqId":"+0t8aiJRoG+p9soIsy1t","remoteAddr":"","app":"core","message":"starting upgrade from 8.2.2.2 to 8.2.2.2","level":0,"time":"2016-01-30T17:44:04+00:00","method":"--","url":"--"}
> {"reqId":"+0t8aiJRoG+p9soIsy1t","remoteAddr":"","app":"PHP","message":"PDO::exec(): MySQL server has gone away at /share/HDB_DATA/Web/owncloud8/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php#57","level":3,"time":"2016-01-30T17:44:22+00:00","method":"--","url":"--"}
> {"reqId":"+0t8aiJRoG+p9soIsy1t","remoteAddr":"","app":"PHP","message":"PDO::exec(): Error reading result set's header at /share/HDB_DATA/Web/owncloud8/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php#57","level":3,"time":"2016-01-30T17:44:22+00:00","method":"--","url":"--"}
> {"reqId":"+0t8aiJRoG+p9soIsy1t","remoteAddr":"","app":"core","message":"Simulated database structure update failed (exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in /share/HDB_DATA/Web/owncloud8/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:57
> Stack trace:
> #0 /share/HDB_DATA/Web/owncloud8/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(57): PDO->exec('INSERT INTO ```oc...')
> #1 /share/HDB_DATA/Web/owncloud8/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1025): Doctrine\DBAL\Driver\PDOConnection->exec('INSERT INTO ```oc...')
> #2 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/db/migrator.php(233): Doctrine\DBAL\Connection->exec('INSERT INTO ```oc...')
> #3 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/db/migrator.php(135): OC\DB\Migrator->copyTable('oc_jobs', 'oc_oc_jobs_z40w...')
> #4 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/db/migrator.php(110): OC\DB\Migrator->checkTableMigrate(Object(Doctrine\DBAL\Schema\Table))
> #5 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/db/mdb2schemamanager.php(130): OC\DB\Migrator->checkMigrate(Object(Doctrine\DBAL\Schema\Schema))
> #6 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/db.php(248): OC\DB\MDB2SchemaManager->simulateUpdateDbFromStructure('/share/HDB_DATA...')
> #7 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/updater.php(343): OC_DB::simulateUpdateDbFromStructure('/share/HDB_DATA...')
> #8 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/updater.php(308): OC\Updater->checkCoreUpgrade()
> #9 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/updater.php(205): OC\Updater->doUpgrade('8.2.2.2', '8.2.2.2')
> #10 /share/HDB_DATA/Web/owncloud8/owncloud/core/command/upgrade.php(213): OC\Updater->upgrade()
> #11 /share/HDB_DATA/Web/owncloud8/owncloud/3rdparty/symfony/console/Symfony/Component/Console/Command/Command.php(253): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #12 /share/HDB_DATA/Web/owncloud8/owncloud/3rdparty/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #13 /share/HDB_DATA/Web/owncloud8/owncloud/3rdparty/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #14 /share/HDB_DATA/Web/owncloud8/owncloud/3rdparty/symfony/console/Symfony/Component/Console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #15 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/console/application.php(100): Symfony\Component\Console\Application->run(NULL, NULL)
> #16 /share/HDB_DATA/Web/owncloud8/owncloud/console.php(69): OC\Console\Application->run()
> #17 /share/HDB_DATA/Web/owncloud8/owncloud/occ(13): require_once('/share/HDB_DATA...')
> #18 {main}
> 
> Next exception 'Doctrine\DBAL\Driver\PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in /share/HDB_DATA/Web/owncloud8/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:59
> Stack trace:
> #0 /share/HDB_DATA/Web/owncloud8/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1025): Doctrine\DBAL\Driver\PDOConnection->exec('INSERT INTO ```oc...')
> #1 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/db/migrator.php(233): Doctrine\DBAL\Connection->exec('INSERT INTO ```oc...')
> #2 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/db/migrator.php(135): OC\DB\Migrator->copyTable('oc_jobs', 'oc_oc_jobs_z40w...')
> #3 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/db/migrator.php(110): OC\DB\Migrator->checkTableMigrate(Object(Doctrine\DBAL\Schema\Table))
> #4 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/db/mdb2schemamanager.php(130): OC\DB\Migrator->checkMigrate(Object(Doctrine\DBAL\Schema\Schema))
> #5 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/db.php(248): OC\DB\MDB2SchemaManager->simulateUpdateDbFromStructure('/share/HDB_DATA...')
> #6 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/updater.php(343): OC_DB::simulateUpdateDbFromStructure('/share/HDB_DATA...')
> #7 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/updater.php(308): OC\Updater->checkCoreUpgrade()
> #8 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/updater.php(205): OC\Updater->doUpgrade('8.2.2.2', '8.2.2.2')
> #9 /share/HDB_DATA/Web/owncloud8/owncloud/core/command/upgrade.php(213): OC\Updater->upgrade()
> #10 /share/HDB_DATA/Web/owncloud8/owncloud/3rdparty/symfony/console/Symfony/Component/Console/Command/Command.php(253): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #11 /share/HDB_DATA/Web/owncloud8/owncloud/3rdparty/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #12 /share/HDB_DATA/Web/owncloud8/owncloud/3rdparty/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #13 /share/HDB_DATA/Web/owncloud8/owncloud/3rdparty/symfony/console/Symfony/Component/Console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #14 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/console/application.php(100): Symfony\Component\Console\Application->run(NULL, NULL)
> #15 /share/HDB_DATA/Web/owncloud8/owncloud/console.php(69): OC\Console\Application->run()
> #16 /share/HDB_DATA/Web/owncloud8/owncloud/occ(13): require_once('/share/HDB_DATA...')
> #17 {main}
> 
> Next exception 'Doctrine\DBAL\Exception\DriverException' with message 'An exception occurred while executing 'INSERT INTO ```oc_oc_jobs_z40wrt8a9y10a``` SELECT * FROM ```oc_jobs```':
> 
> SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in /share/HDB_DATA/Web/owncloud8/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115
> Stack trace:
> #0 /share/HDB_DATA/Web/owncloud8/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
> #1 /share/HDB_DATA/Web/owncloud8/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1027): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO ```oc...')
> #2 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/db/migrator.php(233): Doctrine\DBAL\Connection->exec('INSERT INTO ```oc...')
> #3 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/db/migrator.php(135): OC\DB\Migrator->copyTable('oc_jobs', 'oc_oc_jobs_z40w...')
> #4 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/db/migrator.php(110): OC\DB\Migrator->checkTableMigrate(Object(Doctrine\DBAL\Schema\Table))
> #5 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/db/mdb2schemamanager.php(130): OC\DB\Migrator->checkMigrate(Object(Doctrine\DBAL\Schema\Schema))
> #6 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/db.php(248): OC\DB\MDB2SchemaManager->simulateUpdateDbFromStructure('/share/HDB_DATA...')
> #7 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/updater.php(343): OC_DB::simulateUpdateDbFromStructure('/share/HDB_DATA...')
> #8 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/updater.php(308): OC\Updater->checkCoreUpgrade()
> #9 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/updater.php(205): OC\Updater->doUpgrade('8.2.2.2', '8.2.2.2')
> #10 /share/HDB_DATA/Web/owncloud8/owncloud/core/command/upgrade.php(213): OC\Updater->upgrade()
> #11 /share/HDB_DATA/Web/owncloud8/owncloud/3rdparty/symfony/console/Symfony/Component/Console/Command/Command.php(253): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #12 /share/HDB_DATA/Web/owncloud8/owncloud/3rdparty/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #13 /share/HDB_DATA/Web/owncloud8/owncloud/3rdparty/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #14 /share/HDB_DATA/Web/owncloud8/owncloud/3rdparty/symfony/console/Symfony/Component/Console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #15 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/console/application.php(100): Symfony\Component\Console\Application->run(NULL, NULL)
> #16 /share/HDB_DATA/Web/owncloud8/owncloud/console.php(69): OC\Console\Application->run()
> #17 /share/HDB_DATA/Web/owncloud8/owncloud/occ(13): require_once('/share/HDB_DATA...')
> #18 {main})","level":4,"time":"2016-01-30T17:44:22+00:00","method":"--","url":"--"}
> {"reqId":"+0t8aiJRoG+p9soIsy1t","remoteAddr":"","app":"core","message":"Exception: {"Exception":"Doctrine\DBAL\Exception\DriverException","Message":"An exception occurred while executing 'INSERT INTO ```oc_oc_jobs_z40wrt8a9y10a``` SELECT * FROM ```oc_jobs```':
> 
> SQLSTATE[HY000]: General error: 2006 MySQL server has gone away","Code":0,"Trace":"#0 /share/HDB_DATA/Web/owncloud8/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
> #1 /share/HDB_DATA/Web/owncloud8/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1027): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO ```oc...')
> #2 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/db/migrator.php(233): Doctrine\DBAL\Connection->exec('INSERT INTO ```oc...')
> #3 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/db/migrator.php(135): OC\DB\Migrator->copyTable('oc_jobs', 'oc_oc_jobs_z40w...')
> #4 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/db/migrator.php(110): OC\DB\Migrator->checkTableMigrate(Object(Doctrine\DBAL\Schema\Table))
> #5 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/db/mdb2schemamanager.php(130): OC\DB\Migrator->checkMigrate(Object(Doctrine\DBAL\Schema\Schema))
> #6 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/db.php(248): OC\DB\MDB2SchemaManager->simulateUpdateDbFromStructure('/share/HDB_DATA...')
> #7 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/updater.php(343): OC_DB::simulateUpdateDbFromStructure('/share/HDB_DATA...')
> #8 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/updater.php(308): OC\Updater->checkCoreUpgrade()
> #9 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/updater.php(205): OC\Updater->doUpgrade('8.2.2.2', '8.2.2.2')
> #10 /share/HDB_DATA/Web/owncloud8/owncloud/core/command/upgrade.php(213): OC\Updater->upgrade()
> #11 /share/HDB_DATA/Web/owncloud8/owncloud/3rdparty/symfony/console/Symfony/Component/Console/Command/Command.php(253): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #12 /share/HDB_DATA/Web/owncloud8/owncloud/3rdparty/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #13 /share/HDB_DATA/Web/owncloud8/owncloud/3rdparty/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #14 /share/HDB_DATA/Web/owncloud8/owncloud/3rdparty/symfony/console/Symfony/Component/Console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #15 /share/HDB_DATA/Web/owncloud8/owncloud/lib/private/console/application.php(100): Symfony\Component\Console\Application->run(NULL, NULL)
> #16 /share/HDB_DATA/Web/owncloud8/owncloud/console.php(69): OC\Console\Application->run()
> #17 /share/HDB_DATA/Web/owncloud8/owncloud/occ(13): require_once('/share/HDB_DATA...')
> #18 {main}","File":"/share/HDB_DATA/Web/owncloud8/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php","Line":115}","level":3,"time":"2016-01-30T17:44:22+00:00","method":"--","url":"--"}

I think the table name oc_oc_.* is wrong and the reason for the error but I don't know why and where that happens

**Comment by LukasReschke** [comment]
> SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

Seems to be the actual error. Please check https://doc.owncloud.com/server/8.0/admin_manual/issues/index.html#common-problems-error-messages and retry the update, as this seems to be an environment related issues see https://owncloud.org/support/ for pages where you could ask questions.
