### ISSUE TITLE
Server error logs, does they always really indicate errors?

### ISSUE THREAD

**Issue by casper000** [owncloud/core#22033]
Hello everyone,

Does log level 4 or any of them except 0 always mean that It has logged issue in all situations and something is wrong? In my situation when 2 clients have synchronized same data and I start to delete data on one client, after few seconds delete same data from second client, (which can be done by users), client logs: error downloading https://.... server replied Locked. after that server logs exception that file is locked. after sync is finished all clients has deleted data. I have also tested to upload same data of course with same names on both clients at same time. first client just uploaded and second client first uploaded an on second sync process downloaded same files. I have checked on server in data directory when deleting all files, they where deleted and when uploading all file were uploaded. So where is error?

My question is. Does error message in server log file really means that there was error on server side?

### Server configuration
**Operating system**: 3.10.0-327.el7.x86_64

**Web server:** Apache/2.4.6

**Database:**15.1 Distrib 5.5.44-MariaDB

**PHP version:**PHP 5.6.16 (cli)

**ownCloud version:**8.2.2

**Updated from an older ownCloud or fresh install:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:** 

```
Enabled:
  - activity: 2.1.3
  - announcementcenter: 1.0.0
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - gallery: 14.2.0
  - notifications: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - files_texteditor
  - files_videoviewer
  - firstrunwizard
  - provisioning_api
  - templateeditor
  - updater
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```php
<?php
$CONFIG = array (
  'instanceid' => 'XXXX',
  'passwordsalt' => 'XXXX',
  'secret' => 'XXXX',
  'trusted_domains' => 
  array (
    0 => 'host.mydomain.com',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'overwrite.cli.url' => 'https://10.0.0.3/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.2.2.2',
  'dbname' => 'XXXX',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'XXXX',
  'dbpassword' => 'XXXX',
  'logtimezone' => 'XXXX',
  'installed' => true,
  'has_internet_connection' => true,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'XXXX',
  'mail_domain' => 'gmail.com',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtpsecure' => 'tls',
  'mail_smtphost' => 'smtp.gmail.com',
  'mail_smtpport' => '587',
  'mail_smtpname' => 'XXXX',
  'mail_smtppassword' => 'XXXX',
  'loglevel' => 2,
  'logdateformat' => 'Y-m-d_H:i:s',
  'knowledgebaseenabled' => false,
  'enable_avatars' => true,
  'allow_user_to_change_display_name' => false,
  'updatechecker' => false,
  'enable_previews' => true,
  'preview_max_x' => 1024,
  'preview_max_y' => 768,
  'preview_max_scale_factor' => 1,
  'preview_max_filesize_image' => 5,
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\JPEG',
    2 => 'OC\\Preview\\GIF',
    3 => 'OC\\Preview\\BMP',
    4 => 'OC\\Preview\\XBitmap',
  ),
  'default_language' => 'en',
  'asset-pipeline.enabled' => true,
  'trashbin_retention_obligation' => 'auto',
  'activity_expire_days' => 365,
  'check_for_working_webdav' => true,
  'maintenance' => false,
  'singleuser' => false,
  'filesystem_check_changes' => 0,
  'filelocking.enabled' => 'true',
  'memcache.locking' => '\OC\Memcache\Redis',
  'redis' => array(
  'host' => '/var/run/redis/redis.sock',
  'port' => 0,
  'timeout' => 0.0,
),
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser: Google Chrome**

**Operating system: Windiows 7 x86/x64**

**Comment by LukasReschke** [comment]
> My question is. Does error message in server log file really means that there was error on server side?

Depends on the error type and message. Can you please post the log messages in question? Thanks.

**Comment by RealRancor** [comment]
@LukasReschke I had pointed the user from https://forum.owncloud.org/viewtopic.php?f=36&t=32790 here because he got that

```client logs: error downloading https://.... server replied Locked. after that server logs exception that file is locked.```

described in the initial post.

**Comment by casper000** [comment]
The only solution for now, but not solution of course I have reduced amount of errors by increasing:
innodb_buffer_pool_size = 1024M and installing Redis. now I receive 60% less this error messages.

**Comment by blizzz** [comment]
I guess the question was answered with "it depends" as so often. Closing, if you think there is a bug, open a new issue with more specific details.
