### ISSUE TITLE
Make notifications after updates

### ISSUE THREAD

**Issue by hitam4450** [owncloud/core#22031]
Hi,
I see in my OC installations (8.2.0,  8.22) the icon *Notifications* but I did not found yet any possibility to configure the *notifications*.

I would love, if notification could inform me about:

New version of installed and enabled apps,
New Versions of OC (e.g. beta)
New versions of OC, ready for download and installation

Additionally configurable events

regards, hitam4450

**Comment by MorrisJobke** [comment]
cc @nickvergessen

**Comment by nickvergessen** [comment]
Sounds good

**Comment by PVince81** [comment]
I guess the "update notification" that usually shows as a yellow banner could be ported to use the notification API instead.

CC @VicDeo

**Comment by RealRancor** [comment]
> New version of installed and enabled apps

That would partly solve https://github.com/owncloud/core/issues/17230

**Comment by hitam4450** [comment]
All suggestions :thumbsup:

**Comment by nickvergessen** [comment]
Implemented for 9.1: https://github.com/owncloud/core/pull/24444
