### ISSUE TITLE
improvement of getTempBaseDir() in tempmanager.php

### ISSUE THREAD

**Issue by marschal** [owncloud/core#22032]
**Suggestion:**
According to my [comment](https://github.com/owncloud/core/issues/14886#issuecomment-166319235) on a related issue I would suggest to reorder the assignment of configured temp-dir paths. 

**Reason:**
Hence the function in the `tempmanager.php` simply returns the first found tmp directory, the user has no possibility to reconfigure the systems temp dir if the user has no root access on the machine. For example all environment variables or temp-dirs set in `.htaccess` file are ignored if there is set a temp dir in the system.

**Example:**
I would suggest the following order to return a temp directory:

    /**
	 * Get the temporary base directory configured on the server
	 *
	 * @return string Path to the temporary directory or null
	 * @throws \UnexpectedValueException
	 */
	public function getTempBaseDir() {
		if ($this->tmpBaseDir) {
			return $this->tmpBaseDir;
		}

		$directories = [];

		// first check user specified directories
		if ($temp = ini_get('upload_tmp_dir')) {
			$directories[] = $temp;
		}
		if ($temp = getenv('TMP')) {
			$directories[] = $temp;
		}
		if ($temp = getenv('TEMP')) {
			$directories[] = $temp;
		}
		if ($temp = getenv('TMPDIR')) {
			$directories[] = $temp;
		}

		// check systems temp directories
		if ($temp = $this->config->getSystemValue('tempdirectory', null)) {
			$directories[] = $temp;
		}
		$temp = tempnam(__FILE__, '');
		if (file_exists($temp)) {
			unlink($temp);
			$directories[] = dirname($temp);
		}
		if ($temp = sys_get_temp_dir()) {
			$directories[] = $temp;
		}

		// return the first temp directory found (users first, if configured)
		foreach ($directories as $dir) {
			if ($this->checkTemporaryDirectory($dir)) {
				return $dir;
			}
		}
		throw new \UnexpectedValueException('Unable to detect system temporary directory');
	}

**Comment by RealRancor** [comment]
@marschal Why not using the tempdirectory of your config.php:

https://github.com/owncloud/core/blob/v8.2.2/config/config.sample.php#L994-L1002

which is at the top of the various possible locations:

https://github.com/owncloud/core/blob/v8.2.2/lib/private/tempmanager.php#L213-L215

Exactly allowing what you're looking for.

**Comment by marschal** [comment]
Thanks @RealRancor , I didn't noticed this setting in the `config.php`. Works for me!
