### ISSUE TITLE
Owncloud Server No Internet Connection

### ISSUE THREAD

**Issue by SurfYourName** [owncloud/core#22048]
I am getting the following error message.

This server has no working Internet connection. This means that some of the features like mounting external storage, notifications about updates or installation of third-party apps will not work. Accessing files remotely and sending of notification emails might not work, either. We suggest to enable Internet connection for this server if you want to have all features.

I have OwnCloud version 8.2.2 installed. 

Here is my config code.

 `<?php
$CONFIG = array (
  'instanceid' => 'ocjtm7vqxtxr',
  'passwordsalt' => 'XXXXXXX',
  'secret' => 'XXXXXX',
  'trusted_domains' => 
  array (
    0 => 'aXXXXraft.aero',
  ),
  'datadirectory' => '/home/aXXXXXcraft/public_html/cloud/data',
  'overwrite.cli.url' => 'http://amerXXXXXraft.aero/cloud',
  'dbtype' => 'sqlite3',
  'version' => '8.2.2.2',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_smtpmode' => 'php',
  'mail_smtphost' => 'server.suXXXXXXXme.com',
  'mail_smtpport' => '587',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpauth' => 1,
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
  'trashbin_retention_obligation' => 'auto',
);
`

I have read several different postings but have not been able to resolve this issue.  Can anyone help?

**Comment by karlitschek** [comment]
The issue is exactly as the message says. Your server can't reach the internet which is most likely an configuration issue on you server or network. Please see here owncloud.org/support for help how to solve this.

**Comment by SurfYourName** [comment]
Is this possibly an issue with the settings within Owncloud?

**Comment by luckydonald** [comment]
@karlitschek 
I have the same Issue.
The server itself **clearly** has internet, as `wget`, `apt-get`, `ping google.com`, etc. all can connect to the internet successfully.
```
PING google.com (64.15.112.40) 56(84) bytes of data.
64 bytes from cache.google.com (64.15.112.40): icmp_req=1 ttl=58 time=6.71 ms
64 bytes from cache.google.com (64.15.112.40): icmp_req=2 ttl=58 time=6.65 ms
64 bytes from cache.google.com (64.15.112.40): icmp_req=3 ttl=58 time=6.67 ms
^C
--- google.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 6.658/6.681/6.715/0.024 ms
```

**Comment by luckydonald** [comment]
The question is: 
What could be a reason for this? 
I don't have a proxy, or IPTables.

**Comment by RealRancor** [comment]
@luckydonald  See  https://forum.owncloud.org/viewtopic.php?f=17&t=29790
