### ISSUE TITLE
Windows client 2.1.0 (build 5683) does not synchronize shared files

### ISSUE THREAD

**Issue by crysman** [owncloud/core#22043]
We've just found out with my colleague that **Windows client 2.1 does not synchronize shared files** until logged-out/connect again or restarting the computer.

What is even worse, in "activity" it is logged, but physically, on the hard drive, nothing is being created/deleted. Tested on two independent windows machines (W7pro, W10) and two independent user accounts. In web interface, everything is OK, synchronized correctly.

My very obsolete (newest official) Xubuntu owncloud client (1.8.1+dsfg-1ubuntu1) does not have any problem and synchronizes everything correctly.

I've even tried to turn off the cache (memcache.local) in the owncloud config - has not helped. 

**How to debug this and get it fixed**? Thanks

Debug info:
```
⚡ sudo -u ownclouduser php occ status
  - installed: true
  - version: 8.2.2.2
  - versionstring: 8.2.2
  - edition: 
⚡ sudo -u ownclouduser php occ app:list
Enabled:
  - activity: 2.1.3
  - external: 1.2
  - files: 1.2.0
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - gallery: 14.2.0
  - provisioning_api: 0.3.0
  - user_external: 0.4
Disabled:
  - calendar
  - contacts
  - conversations
  - documents
  - encryption
  - files_encryption
  - files_external
  - files_pdfviewer
  - files_videoviewer
  - firstrunwizard
  - galleryplus
  - notes
  - notifications
  - tasks
  - templateeditor
  - user_ldap
⚡ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.9 (wheezy)
Release:	7.9
Codename:	wheezy
```

**Comment by LukasReschke** [comment]
Please reopen at https://github.com/owncloud/client using the issue template from https://github.com/owncloud/client/blob/master/CONTRIBUTING.md

**Comment by crysman** [comment]
Posted there as https://github.com/owncloud/client/issues/4418
