### ISSUE TITLE
Detection of existing tags doesn't allow to create tags named like a prefix substring of an existing tag.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#22064]
### Steps to reproduce

Having no tags in the system do;
1. Open sidebar of a file and assign(creating it) a tag called "javascript".
2. In the same file, assign(creating it) a tag called "java". 

### Expected behaviour
That file has the tags "java" and "javascript" on it.

### Actual behaviour
"javascript" tag is unassigned, "java" tag is never created. 

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Master branch
{"installed":true,"maintenance":false,"version":"9.0.0.8","versionstring":"9.0 pre alpha","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No

**Logs**

```
```

### Client configuration

**browser**
Chrome

**Comment by PVince81** [comment]
Ah yes, I know why. Assigning to self.

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/22065

**Comment by nickvergessen** [comment]
nice find :smiley_cat:
