### ISSUE TITLE
file uploaded twice (unnecessarily) via the web interface upload form

### ISSUE THREAD

**Issue by moscicki** [owncloud/core#22067]
I have an impression that it was reported and fixed already but I cannot find the issue. Here is the problem for version 8.0.2 with Chrome and Safari (so seems browser-independent):

whenever I upload a file which exists already, the web portal uploads the file, then asks me if to keep or replace the file and if I check (replace, drop the old) it uploads it again

**Comment by RealRancor** [comment]
Hi,

i think it would make sense to at least test the latest stable 8.0.10 of the 8.0.x branch.

**Comment by PVince81** [comment]
@moscicki this is fixed in 8.2.2.

The conflict logic will first check if the file is known in the local list. Only if it's not, it will go to the server.

**Comment by PVince81** [comment]
Fixed by https://github.com/owncloud/core/pull/19417
