### ISSUE TITLE
Invalid owncloud version file on Owncloud download server for 8.0.3

### ISSUE THREAD

**Issue by TuemmlerKon** [owncloud/core#22060]
In case someone would like to download the 8.0.3 Version of OwnCloud as tar.gz from [owncloud server](https://owncloud.org/changelog/) he currently gets the newest version 8.2.2. The zip archive contains a valid 8.0.3. That also causes that the md5 (only on tar.gz) sum is invalid (didn't checked the other checksums but I think it's the same problem)

**Comment by PVince81** [comment]
@karlitschek @cmonteroluque

**Comment by karlitschek** [comment]
@cmonteroluque not sure how this could have happend. Do you have an idea?

**Comment by cmonteroluque** [comment]
@karlitschek I honestly don't.

**Comment by karlitschek** [comment]
Hmm. This is really a mystery to me. Somewhere we have a bug in our download mirroring or publishing system. But I don't know where.

**Comment by PVince81** [comment]
8.0.3 is old, better use a newer version.
