### ISSUE TITLE
[Storage API] Considerations and ToDos ...

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#22069]
@icewind1991 this is some feedback we got on the storage api - mind taking a look? THX

- [x] add list of keys which are required for the array which is returned by stat()
- [ ] remove duplicate implementations with respect to filemtime, filetype and stat
- [x] do we really need the hash() method? Can we drop it? => needed by documents
- [ ] file_get_contents is duplicate with respect to the storage implementation - can we drop it?
- [x] search methods need PHPDoc with respect to search behavior and syntax
- [x] search methods should be marked as deprecated for 9.0 due to lack of pagination and proper capabilities
- [x] drop getLocalFolder() - unused afaik - #22166
- [x] ICache::getFolderContents() - add comment that this is non recursive
- [x] ICache:search*() deprecate them for 9.0 - reason as above

**Comment by icewind1991** [comment]
> search methods should be marked as deprecated for 9.0 due to lack of pagination and proper capabilities

Deprecate them without having any alternatives?

**Comment by karlitschek** [comment]
@DeepDiver1975 i don't remember why we should deprecate search?

**Comment by DeepDiver1975** [comment]
The search methods as they exist today offer no pagination capabilities - in bigger installations this will cause issues if the result set holds hundreds of thousands of elements.

API implementators will have big issues in coming up with a proper implementation without risking their system stability - as a result they even might concern to no implement search at all.

Marking the methods a deprecated now allows us to move to a proper api design at a sooner point in time.

**Comment by DeepDiver1975** [comment]
To clarify the way to walk (should be written in this form in the phpdoc of the methods):
- as of 9.0 we require these methods to be implemented
- their limitations are quite clear and we aim to fix them in 9.1
- a potential implementation might 'simply' return an empty array to avoid system overload
- and therefore we deprecate them right away

**Comment by icewind1991** [comment]
> add list of keys which are required for the array which is returned by stat()

Is already specified

**Comment by icewind1991** [comment]
> do we really need the hash() method?

We might want to use that to verify file checksums

> remove duplicate implementations with respect to filemtime, filetype and stat-

Can't really drop either of these now since both are used

> file_get_contents is duplicate with respect to the storage implementation - can we drop it?

Same here, file_get_contents is used so we cant easily drop it

**Comment by DeepDiver1975** [comment]
> do we really need the hash() method?
> 
> We might want to use that to verify file checksums

If we need it - we can add it - but is it needed right now?
The less an implementor has to do the better ;-)

**Comment by DeepDiver1975** [comment]
as far as I can tell hash is unused - let's drop it

**Comment by PVince81** [comment]
@icewind1991 any update ? Can this be done before the freeze ?

**Comment by icewind1991** [comment]
Turns out hash is being used by the documents app

**Comment by icewind1991** [comment]
I dont think I can "fix" the two remaining issues

while some of the methods are duplicated/mostly unneeded there is code using them (also in 3rdparty apps)
so we cant drop them

**Comment by DeepDiver1975** [comment]
THX - let's create an issue for 9.1 where we address the remaining issues.

**Comment by PVince81** [comment]
@icewind1991 @DeepDiver1975 can you make the ticket ? Thanks

**Comment by DeepDiver1975** [comment]
> @icewind1991 @DeepDiver1975 can you make the ticket ? Thanks

https://github.com/owncloud/core/issues/22388
