### ISSUE TITLE
Add option to set mail-address for users/adduser provisioning API & mail notifications via API

### ISSUE THREAD

**Issue by BennyE** [owncloud/core#22074]
## Add option to set mail-address for users/adduser provisioning API & mail notifications via API

This goes with the enhancement discussed in #15242 for the users/adduser provisioning API that adds "group"-capabilities to the users/adduser provisioning API.

I'd like to suggest that it is made possible to set the mail-address of a user while creating them through the provisioning API. The web-interface offers that capability, **which also allows to even notify the new users via mail.**

I believe that this would be good enhancement for larger-scale OwnClouds, where you would import / create users via the provisioning API.

In addition I'd like to suggest that the provisioning API offers an email-notification towards the user, leveraging the same mail templates that are used when creating a user through the web-interface (where the capability is already there).

I think that notification should be a flag for any API action, to notify the user that something happened.

Update:
I should probably add that I reviewed the corresponding source-code at [../master/apps/provisioning_api/lib/users.php](https://github.com/owncloud/core/blob/master/apps/provisioning_api/lib/users.php) before I opened this issue. I didn't see any new functions with regards to mail notfications nor mail-addresses as part of the users/adduser API.

I didn't figure out a way to apply the Labels "app:provisioning_api" and "enhancement" to this issue.

**Comment by PVince81** [comment]
as far as I can see, setting email address through provisioning API is already supported: https://github.com/owncloud/core/blob/v10.0.10/apps/provisioning_api/lib/Users.php#L311
