### ISSUE TITLE
Old file versions seem to be corrupted (Win 8.1, chrome, openSUSE)

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#22073]
I use the web interface, navigate into a folder and select a powerpoint presentation that has changed a lot. I then select to download a version that is not the current version. When I open the downloaded presentation, powerpoint says the file is corrupted, and the files is actually rendered as completely empty.

Environment
s3
openSUSE
Windows 8.1 Chrome latest browser
Powerpoint 2010 and 2013

Steps to reproduce:

First create a ppt and make and save lots of changes, let it sync. This will create a file with lots of versions in it.
Log into the web interface, download a previous version. It will open as corrupted and be empty.

**Comment by PVince81** [comment]
So this is 8.2.2, but the file was likely modified several times in older versions.

@MTRichards does the most recent version work ? Like, make a small change, then download the most recent version. If that doesn't work, then the bug is in 8.2.2.

If it's only very old versions, then it could be a bug that happened in older versions.

**Comment by MTRichards** [comment]
It was in the lest 2 weeks with all new files.

-- 
Matt Richards
VP Products & Markets 
ownCloud, inc.

**Comment by PVince81** [comment]
Okay, that's bad.

Is the ppt file uploaded through the sync client or using the web UI ?

**Comment by PVince81** [comment]
S3 is running PHP7 as far as I know, not sure which exact version.

I tried creating a ppt file and text file in a shared folder as recipient, and I cannot download any of the versions. However the file owner is able to properly download versions.

However on a local 8.2.2 instance it works fine.
So either it's related to PHP 7 or something else.

**Comment by PVince81** [comment]
The "Content-Length" header of the download is 0 bytes.
And "Content-Type" is application/octet-stream. It's almost as if the server didn't find the file and just returns whatever.

**Comment by PVince81** [comment]
### Steps:

1. Have two users "user1" and "user2"
1. "user2" shares a folder "test" with "user1"
1. "user1" creates a text file as "test/file.txt"
1. "user1" edits the text file several times and saves it, to create versions
1. "user1" opens the sidebar and "versions" tab
1. Try downloading any of the versions

### Expected result
Versions can be downloaded, version thumbnail appears.

### Actual result
Versions file have 0 bytes when downloaded and the thumbnail appears as a broken image.

### Env
ownCloud 8.2.2
PHP 7 (not sure which minor version)

**Comment by PVince81** [comment]
@Xenopathic @icewind1991

**Comment by Xenopathic** [comment]
Seems to work fine on master...

**Comment by PVince81** [comment]
On my private ownCloud instance, it works fine for new files.
However, for some older files the recipient cannot download the versions but the owner can.

This appears when the previews get created:
```
{"reqId":"qh9ugH5XcZgWfGkdAmbg","remoteAddr":"85.180.6.139","app":"core","message":"File:\"\/clientsync\/petry\/doc\/Shoppen\/asia_laden.txt.v1450290905\" not found","level":0,"time":"2016-02-03T09:47:01+00:00","method":"GET","url":"\/index.php\/apps\/files_versions\/preview?file=%2Fclientsync%2Fpetry%2Fdoc%2FShoppen%2Fasia_laden.txt&version=1450290905"}
{"reqId":"qh9ugH5XcZgWfGkdAmbg","remoteAddr":"85.180.6.139","app":"core","message":"File not found.","level":0,"time":"2016-02-03T09:47:01+00:00","method":"GET","url":"\/index.php\/apps\/files_versions\/preview?file=%2Fclientsync%2Fpetry%2Fdoc%2FShoppen%2Fasia_laden.txt&version=1450290905"}
{"reqId":"9e8UnWV9572xNq8UKueX","remoteAddr":"85.180.6.139","app":"core","message":"File:\"\/clientsync\/petry\/doc\/Shoppen\/asia_laden.txt.v1449674527\" not found","level":0,"time":"2016-02-03T09:47:01+00:00","method":"GET","url":"\/index.php\/apps\/files_versions\/preview?file=%2Fclientsync%2Fpetry%2Fdoc%2FShoppen%2Fasia_laden.txt&version=1449674527"}
{"reqId":"9e8UnWV9572xNq8UKueX","remoteAddr":"85.180.6.139","app":"core","message":"File not found.","level":0,"time":"2016-02-03T09:47:01+00:00","method":"GET","url":"\/index.php\/apps\/files_versions\/preview?file=%2Fclientsync%2Fpetry%2Fdoc%2FShoppen%2Fasia_laden.txt&version=1449674527"}
{"reqId":"vI+nKb0Hx129zcgYJjhb","remoteAddr":"85.180.6.139","app":"core","message":"File:\"\/clientsync\/petry\/doc\/Shoppen\/asia_laden.txt.v1447009824\" not found","level":0,"time":"2016-02-03T09:47:01+00:00","method":"GET","url":"\/index.php\/apps\/files_versions\/preview?file=%2Fclientsync%2Fpetry%2Fdoc%2FShoppen%2Fasia_laden.txt&version=1447009824"}
{"reqId":"vI+nKb0Hx129zcgYJjhb","remoteAddr":"85.180.6.139","app":"core","message":"File not found.","level":0,"time":"2016-02-03T09:47:01+00:00","method":"GET","url":"\/index.php\/apps\/files_versions\/preview?file=%2Fclientsync%2Fpetry%2Fdoc%2FShoppen%2Fasia_laden.txt&version=1447009824"}
{"reqId":"iT9fA0uncGI5EsDFdZEr","remoteAddr":"85.180.6.139","app":"core","message":"File:\"\/clientsync\/petry\/doc\/Shoppen\/asia_laden.txt.v1442141555\" not found","level":0,"time":"2016-02-03T09:47:01+00:00","method":"GET","url":"\/index.php\/apps\/files_versions\/preview?file=%2Fclientsync%2Fpetry%2Fdoc%2FShoppen%2Fasia_laden.txt&version=1442141555"}
{"reqId":"iT9fA0uncGI5EsDFdZEr","remoteAddr":"85.180.6.139","app":"core","message":"File not found.","level":0,"time":"2016-02-03T09:47:01+00:00","method":"GET","url":"\/index.php\/apps\/files_versions\/preview?file=%2Fclientsync%2Fpetry%2Fdoc%2FShoppen%2Fasia_laden.txt&version=1442141555"}
```

and this when trying to download the version as recipient:
```
{"reqId":"tzL\/tc21KQqnJmwX5rCE","remoteAddr":"85.180.6.139","app":"PHP","message":"filesize(): stat failed for \/srv\/www\/vhosts\/owncloud\/data\/tingting\/files_versions\/clientsync\/petry\/doc\/Shoppen\/asia_laden.txt.v1450290905 at \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/storage\/local.php#139","level":3,"time":"2016-02-03T09:47:10+00:00","method":"GET","url":"\/index.php\/apps\/files_versions\/download.php?file=%2Fclientsync%2Fpetry%2Fdoc%2FShoppen%2Fasia_laden.txt&revision=1450290905"}
{"reqId":"tzL\/tc21KQqnJmwX5rCE","remoteAddr":"85.180.6.139","app":"PHP","message":"fopen(\/srv\/www\/vhosts\/owncloud\/data\/tingting\/files_versions\/clientsync\/petry\/doc\/Shoppen\/asia_laden.txt.v1450290905): failed to open stream: No such file or directory at \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/storage\/local.php#247","level":3,"time":"2016-02-03T09:47:10+00:00","method":"GET","url":"\/index.php\/apps\/files_versions\/download.php?file=%2Fclientsync%2Fpetry%2Fdoc%2FShoppen%2Fasia_laden.txt&revision=1450290905"}
```

**Comment by PVince81** [comment]
It looks like it's using the wrong home folder when downloading the version:
`owncloud\/data\/tingting\/files_versions\/clientsync\/petry\/doc\/Shoppen\/asia_laden.txt.v1450290905` (recipient)
instead of
`owncloud\/data\/vincent\/files_versions\/clientsync\/petry\/doc\/Shoppen\/asia_laden.txt.v1450290905` (owner)

The share entry looks fine:
```
MariaDB [owncloud]> select * from oc_share where item_source=844 \G
*************************** 1. row ***************************
         id: 16
 share_type: 0
 share_with: tingting
  uid_owner: vincent
     parent: NULL
  item_type: folder
item_source: 844
item_target: /844
file_source: 844
file_target: /petry
permissions: 31
      stime: 1379851467
   accepted: 0
 expiration: NULL
      token: NULL
  mail_send: 0
1 row in set (0.00 sec)
```

So it's not clear yet in what conditions the versions will be resolved wrongly.
There are situations in which it works fine.

Needs further research.

**Comment by PVince81** [comment]
Ok, I think I got it, the shared folder must not be in root for the owner:

Here are the steps to reproduce it:
1. Create two users "user1" and "user2"
1. Log in as "user1"
1. Create a folder "test/sub"
1. Share "sub" with "user2"
1. Log in as "user2"
1. Create a text file with the text editor in "sub/file.txt"
1. Edit+save the file several times to create versions
1. Try downloading any of the versions

At this point, the versions are not resolved properly.
However if as "user1" you move "sub" to the root, then it will work again.

I suspect that the path resolution for shares doesn't work properly.

**Comment by PVince81** [comment]
Also broken on master / 9.0.

Works properly in 8.0.10, 8.1.5.
Broken since 8.2.0.

This is bisectable.

**Comment by nickvergessen** [comment]
I ended up on https://github.com/owncloud/core/commit/f9b05578a62973e8fa0fee619cf84474efc3650b which makes no sense, so not sure what exactly caused this.

But it's important to note, that the version-files on the server are all valid for me all the time. So the state is recoverable.

**Comment by MorrisJobke** [comment]
Also noticed by @pako81 00004660

**Comment by PVince81** [comment]
I'll investigate this

**Comment by PVince81** [comment]
Looks like the versions ajax endpoint is returning the wrong path, the one from the owner instead of recipient! ("path" attribute)

**Comment by PVince81** [comment]
Looks like it was always returning the wrong path, so there might be some weird JS magic that used to fix it in 8.1. Let's see...

**Comment by PVince81** [comment]
Ok got it. In 8.1 the versions.js code **ignored** the `path` from the response and just used whatever the real path of the file was.

There are two possible fixes then:
1) Make the sidebar versions code behave like the old one, read the path from the file list, not the versions response
or
2) Fix the versions response to return the correct path and not disclose the owner's original path!

I'll go with 2)

**Comment by PVince81** [comment]
I went for both, PR is here https://github.com/owncloud/core/pull/22273
