### ISSUE TITLE
download button in public link serves tar on Mac

### ISSUE THREAD

**Issue by jospoortvliet** [owncloud/core#22075]
... and that doesn't work, I've been told by @LukasReschke 

Share a public link, try it on a mac and get nothing (? lukas?)

# System:
* ownCloud 8.2.2
* PHP 7, PHP modules include ```php7-zip php7-zlib php7-bz2```
* Mysql, Apache, openSUSE 13.2. openSUSE packages.
* updated from older installations (since 6.0)

# Apps:
Files, Gallery, Calendar, Contacts, Documents

# config:
* External storage (local folder)
* no encryption
* no ldap and such

# Logs:
This repeats a lot ;-)
```Exception: {"Exception":"Exception","Message":"Unable to send file download.tar. HTML Headers have already been sent from \/srv\/www\/htdocs\/owncloud\/3rdparty\/deepdiver1975\/tarstreamer\/src\/TarStreamer.php in line 30","Code":0,"Trace":"#0 \/srv\/www\/htdocs\/owncloud\/lib\/private\/streamer.php(57): ownCloud\\TarStreamer\\TarStreamer->sendHeaders('download.tar')\n#1 \/srv\/www\/htdocs\/owncloud\/lib\/private\/files.php(118): OC\\Streamer->sendHeaders('download')\n#2 \/srv\/www\/htdocs\/owncloud\/apps\/files_sharing\/lib\/controllers\/sharecontroller.php(310): OC_Files::get('\/Pictures\/FOSS ...', '', false)\n#3 [internal function]: OCA\\Files_Sharing\\Controllers\\ShareController->downloadShare('TCtDZWcAdgGt7RX', '', 'share', '')\n#4 \/srv\/www\/htdocs\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#5 \/srv\/www\/htdocs\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Files_Sharing\\Controllers\\ShareController), 'downloadShare')\n#6 \/srv\/www\/htdocs\/owncloud\/lib\/private\/appframework\/app.php(108): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Files_Sharing\\Controllers\\ShareController), 'downloadShare')\n#7 \/srv\/www\/htdocs\/owncloud\/lib\/public\/appframework\/app.php(134): OC\\AppFramework\\App::main('ShareController', 'downloadShare', Object(OC\\AppFramework\\DependencyInjection\\DIContainer))\n#8 \/srv\/www\/htdocs\/owncloud\/core\/routes.php(124): OCP\\AppFramework\\App->dispatch('ShareController', 'downloadShare')\n#9 [internal function]: OC\\Route\\Router->{closure}(Array)\n#10 \/srv\/www\/htdocs\/owncloud\/lib\/private\/route\/router.php(291): call_user_func(Object(Closure), Array)\n#11 \/srv\/www\/htdocs\/owncloud\/lib\/base.php(851): OC\\Route\\Router->match('\/s\/TCtDZWcAdgGt...')\n#12 \/srv\/www\/htdocs\/owncloud\/index.php(39): OC::handleRequest()\n#13 {main}","File":"\/srv\/www\/htdocs\/owncloud\/3rdparty\/deepdiver1975\/tarstreamer\/src\/TarStreamer.php","Line":46} ```

**Comment by DeepDiver1975** [comment]
Duplicate https://github.com/owncloud/core/issues/21866
