### ISSUE TITLE
Remove files_locking from shipped.json

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#22083]
Hi,

it seems files_locking is still listed as shipped in:

https://github.com/owncloud/core/blob/master/core/shipped.json#L15

but its not even included in recent oC versions (8.2.2, 9.0.0).

Furthermore are there any regressions if people are using the new file locking included in core and the old files_locking app?

**Comment by nickvergessen** [comment]
> Furthermore are there any regressions if people are using the new file locking included in core and the old files_locking app?

I don't think so, because everytime the low-level files_locking app locks it, the high-level file-locking already locked it in the DB/Memcache. It will only make the app redundant, but shouldn't cause any troubles.

**Comment by PVince81** [comment]
There shouldn't be regressions. But also, the files_locking app isn't shipped any more so it should be possible to remove that entry in shipped.json.
