### ISSUE TITLE
CE vs EE: files_antivirus in shipped.json

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#22092]
The current shipped.json contains:

"files_antivirus",

however this app is not shipped anymore in CE and only shipped in EE.

The problem here is, that files_antivirus won't get disabled during updates/upgrades and might break an installation if not compatible.

**Comment by PVince81** [comment]
@karlitschek @VicDeo @DeepDiver1975 @cmonteroluque what do you think ?

**Comment by karlitschek** [comment]
Good catch. This is not correct but hard to fix at the moment. I think the only good option is to use the apps.owncloud.com app store for EE too.

**Comment by cmonteroluque** [comment]
nod

**Comment by PVince81** [comment]
Raised https://github.com/owncloud/enterprise/issues/1092 internally for "make EE work with the app store"

So we then need a different shipped.json for EE than for CE ?

**Comment by PVince81** [comment]
> The problem here is, that files_antivirus won't get disabled during updates/upgrades and might break an installation if not compatible.

If we consider that files_antivirus is supposed to always be compatible, then this might be a non-issue.

**Comment by PVince81** [comment]
files_antivirus is now shipped with both CE and EE, closing.
