### ISSUE TITLE
LDAP credentials error when using Safari and Keychain autocomplete

### ISSUE THREAD

**Issue by zwollex** [owncloud/core#22091]
Are you getting an LDAP configuration error "Credentials not valid/mismatch" and you are using Safari with Keychain autocomplete enabled? Then this is the cause.

What happens is, when you have autocomplete enabled and after you login, you go to the admin panel Safari/Keychain automatically fills in the username or password on the LDAP configuration password field. Causing the error message I just mentioned.

You can do 2 things:
1. Don't use password auto complete any more or use another browser where you have to manually type in your password
2. Go to the admin panel and create a secondary LDAP configuration where the real connection details are stored. Click on the first configuration and then on Advanced. Make sure the option "Configuration Active" is not checked.

So every time you go to the admin panel, the password on your first configuration is updated but since that profile is not active, it doesn't affect it. The second configuration is remained intact.

Request to devs is to turn autocomplete for the LDAP configuration off or don't allow keychain to use this field for autocomplete. This should fix it.

**Comment by LukasReschke** [comment]
@blizzz @jancborchardt And that's the reason why I exactly suggested that we _need_ to use a "Save" button or some other kind instead of relying on auto fill-in. This will explode hard again as soon as browser vendors are adjusting their browsers :wink:

**Comment by LukasReschke** [comment]
@zwollex On which version are you exactly?

**Comment by zwollex** [comment]
@LukasReschke I am on 8.1.5, but I had this issue in every version. Don't know if this is still present in 8.2, but since there is no official bug report about it, I doubt they addressed this.

**Comment by PVince81** [comment]
Please reopen in [user_ldap app repo](https://github.com/owncloud/user_ldap) if issue persists with 10.0.4 and the latest user_ldap app from marketplace.
