### ISSUE TITLE
ETA is totally unrealiable

### ISSUE THREAD

**Issue by mateusz-lacki** [owncloud/core#22094]
Dear Developers,

While syncing, the ETA is shown. I find it totally unrealiable. It seems the estimate is "total transfer to be made/ current transfer speed". The truth is there is a "constant cost" if transferring a single file, which is easy to estimate (it is around 0.8 sec in my case). Actually in my case I am pretty sure the sync will be over in approximately two hours, just because the remainder of files consists of larger files.

The "transfer time per file" is given by:
* a constant value (in my case 0.8 sec) for a small file
* filesize/ transfer rate for large files.

There is a smooth crossover between "small" and "large" file regime. Currently OC wrongly assumes all files are large.

Though I guess it would reordering synchronization order (first send a few small files, and then a large one to get the estimate of both the constant component and the actual transfer speed). Or am I wrong?

![untitled](https://cloud.githubusercontent.com/assets/17043732/12779317/a6ba4d9c-ca67-11e5-9c3e-0b29cdef72e4.png)

**Comment by jospoortvliet** [comment]
This is an issue for the client, see https://github.com/owncloud/client/issues

I'll close this here, if you don't mind.

You're right about it, btw, and this would be a nice-to-have - a great junior job, I suppose, not a high priority thing.
