### ISSUE TITLE
Long tag names makes dropdown edit button to be not aligned properly.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#22097]
### Steps to reproduce

1. Create ~8 tags with small names.
2. Create one tag with 64 characters starting with a character which alphabetically would be ordered before one of them at least.
3. Refresh the page.
4. Open tags dropdown 

### Expected behaviour
Edit buttons remain aligned.

### Actual behaviour
Buttons overlap and lose alignment.

![screen shot 2016-02-03 at 12 18 56](https://cloud.githubusercontent.com/assets/9048796/12780914/3631b948-ca71-11e5-8ec6-8376fd3152bb.png)

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Master branch
{"installed":true,"maintenance":false,"version":"9.0.0.8","versionstring":"9.0 pre alpha","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No

**Logs**

```
```

### Client configuration

**browser**
Chrome, Edge, Firefox

**Comment by ErikPel** [comment]
What would be the preferred way to fix this?

Split the tag name into two or more lines or just show x amount of characters for every tag?

**Comment by SergioBertolinSG** [comment]
I would choose show x amount of chars.
cc @owncloud/designers

**Comment by PVince81** [comment]
x amount of chars is not accurate because the width of characters is variable.

Best is to use `text-overflow: ellipsis` and a fixed width, maybe 90%. CSS will automatically add "..." if the row is too long.

**Comment by SergioBertolinSG** [comment]
Sounds better.

**Comment by ErikPel** [comment]
Never actually used the tagging feature. Where in the app I can tag stuff so I can test this and get to work?

**Comment by PVince81** [comment]
This is new in 9.0, enable the "system tags" app and look at the sidebar for files.

It's call system tags because the tags are visible for all users.

**Comment by PVince81** [comment]
Fix by @ErikPel is here: https://github.com/owncloud/core/pull/22103

**Comment by MorrisJobke** [comment]
#22103 is merged
