### ISSUE TITLE
Mark own comments as read directly after posting

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#22100]
### Steps

1. Post a new comment
1. Check the unread counter for that file (using Webdav or the upcoming UI)

### Expected result
Own comments not counted in unread comments.

### Actual result
Counter is set to 1

Basically, automatically mark own comments as read after posting, but keep them unread for other users.

Please have a look @blizzz 

Observed on master 621f54da514af548bf900f7a1c64af046f53b86d

**Comment by MorrisJobke** [comment]
I also noticed this.

**Comment by PVince81** [comment]
@blizzz I'll take care of this

**Comment by PVince81** [comment]
PR is here https://github.com/owncloud/core/pull/22165
