### ISSUE TITLE
Enable only for specific groups checkbox doesn't appear in apps if the admin account is translated.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#22109]
### Steps to reproduce

1. As admin user go to personal and choose a translated language, for example spanish.
2. As admin go to apps page.
3. Scroll down.

### Expected behaviour
Some apps has an option to  "Enable only for specific groups".

### Actual behaviour
This option doesn't appear in any app.

For example:
![screen shot 2016-02-03 at 16 25 40](https://cloud.githubusercontent.com/assets/9048796/12791254/93c882a0-caa6-11e5-8edc-8816687b769b.png)

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Master branch
{"installed":true,"maintenance":false,"version":"9.0.0.8","versionstring":"9.0 pre alpha","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No

**Logs**

```
```

### Client configuration

**browser**
Chrome

**Comment by PVince81** [comment]
Works for me on 9.1.2RC1 with the text editor.

Note that system tags doesn't have the "enable for groups" option at all.
