### ISSUE TITLE
apps_paths config option has no effect on assets

### ISSUE THREAD

**Issue by kyrofa** [owncloud/core#22114]
Using ownCloud 8.2.2. Test case:

config.php contains the following:

```
'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/some/other/path',
      'url' => '/apps',
      'writable' => true,
    ),
  ),
```

Which 1) does exist, 2) is writable, and 3) contains the default apps. Go to app store, install a non-default app (e.g. contacts). Notice that contacts does indeed get installed into `/some/other/path`. Attempt to visit contacts app. Notice that none of the images or JS files can be found. It seems that the /apps URL always seems to resolve to the default apps directory contained within ownCloud, because if I remove that directory, even the files app starts having that problem (even though it was copied into `/some/other/path`).

Am I missing something? Is there more setup required to have an out-of-source apps folder?

**Comment by DeepDiver1975** [comment]
You have to configure yor web server to deliver the content of /some/other/path as /apps
