### ISSUE TITLE
Quota is not working

### ISSUE THREAD

**Issue by vanquan223** [owncloud/core#22115]
I noticed quota does not work when a user to upload files from mobile.
Owncloud 8.2
android app v1.9

**Comment by PVince81** [comment]
Please use the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

Make sure to provide the values you used for the quota, and check the "size" column of the "files" entry of that user in the oc_filecache database table.

**Comment by cdamken** [comment]
Tested with 8.2.2 and android 1.9.

once the quota is reached:

![screenshot_2016-02-08-12-17-19](https://cloud.githubusercontent.com/assets/7264495/12884440/886240b6-ce5e-11e5-90a4-660643a2d5e0.png)

Please reopen if the problem still exist.
