### ISSUE TITLE
Password-link shares listed in "Shared in ... with ..." section of sidebar

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#22128]
```
Shared in test with 1|$2y$10$mLhrcvhKwViQqPcJx2.9rOpaIZa77lQhf3mhR0SpFJN7sei2e.lhS, test1
```

### Steps
1. Create a folder test
* Share `test` as link with password
* Create a folder test/test2
* Share `test/test2` with user test1
* Open sharing dialog

### Expected
Shared in test with test1

### Actual
Shared in test with 1|$2y$10$mLhrcvhKwViQqPcJx2.9rOpaIZa77lQhf3mhR0SpFJN7sei2e.lhS, test1

@rullzer @PVince81

**Comment by PVince81** [comment]
Cannot reproduce on master 899444103a30a157a2112ca7389e9b047256b72d
Opening the share dialog for the subdir doesn't contain any entries, neither for the owner nor the recipient.

@nickvergessen you set the 8.2 milestone, so does it mean it happens on 8.2.2 ? (no version field in your report). Let me try.

**Comment by PVince81** [comment]
Also cannot reproduce on v8.2.2, same result as master.

@nickvergessen did you miss a step maybe ?

**Comment by nickvergessen** [comment]
yes happens on stable8.2 and 8.2.2

Just did it again and it still reproduces. Note you have to set a password on the link share

**Comment by nickvergessen** [comment]
Problem code is https://github.com/owncloud/core/blob/ea5b7585f9308d72d09262ad8e65302bbfb65f1f/core/js/sharedialogshareelistview.js#L121-L121

It never checks the type?

**Comment by PVince81** [comment]
I did add a password on the link share. Maybe the order is different ?

I'll check that code anyway.

**Comment by PVince81** [comment]
@rullzer can you have a look ?

**Comment by rullzer** [comment]
@nickvergessen mmm this does not happen at my instance...

**Comment by nickvergessen** [comment]
Updated steps still work on stable8.2


1. Create a folder test
* Share `test` as link with password
* Create a folder test/test2
* Share `test/test2` with user test1
* Open sharing dialog

**Comment by rullzer** [comment]
Ah yet got it now...
Will fix.
