### ISSUE TITLE
Owncloud update was unsuccessful

### ISSUE THREAD

**Issue by Glitz111** [owncloud/core#22129]
I wanted to upgrade to the latest release via the Updater on the Admin panel of the Web Interface.

Instead I got this message "Updating ownCloud to version 8.2.1, this may take a while. Preparing update
Set log level to debug - current level: "Warning" Turned on maintenance mode
Exception: Updates between multiple major versions and downgrades are unsupported.
The update was unsuccessful. Please report this issue to the ownCloud community."

Database: sqlite3
PHP: 5.4.45
Owncloud: 8.0.2.?
Updating from older Owncloud (see above)
I can't log into Owncloud anymore.

Config:
<?php
$CONFIG = array (
  'instanceid' => 'ocdtxzoydcbc',
  'passwordsalt' => 'XXX.',
  'secret' => 'XXX',
  'trusted_domains' => 
  array (
    0 => 'www.XXX.de',
    1 => 'XXX.de',
  ),
  'datadirectory' => '/sfbxabko/www.XXX.de/owncloud/data',
  'overwrite.cli.url' => 'http://www.XXX.de/owncloud',
  'dbtype' => 'sqlite3',
  'version' => '8.0.2.0',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => 2,
);

Browser: Chrome 48.0.2564.97 (64-bit)
OSX Yosemite

Any help appreciated.
J.

**Comment by Glitz111** [comment]
Here's the error log from the server:

[Thu Feb 04 07:02:17 2016] [error] [client 191.232.136.103] (36)File name too long: access to /Sch\xc3\x83\xc6\x92\xc3\x86\xe2\x80\x99\xc3\x83\xe2\x80\xa0\xc3\xa2\xe2\x82\xac\xe2\x84\xa2\xc3\x83\xc6\x92\xc3\xa2\xe2\x82\xac\xc2\xa0\xc3\x83\xc2\xa2\xc3\xa2\xe2\x80\x9a\xc2\xac\xc3\xa2\xe2\x80\x9e\xc2\xa2\xc3\x83\xc6\x92\xc3\x86\xe2\x80\x99\xc3\x83\xc2\xa2\xc3\xa2\xe2\x80\x9a\xc2\xac\xc3\x85\xc2\xa1\xc3\x83\xc6\x92\xc3\xa2\xe2\x82\xac\xc5\xa1\xc3\x83\xe2\x80\x9a\xc3\x82\xc2\xaf\xc3\x83\xc6\x92\xc3\x86\xe2\x80\x99\xc3\x83\xe2\x80\xa0\xc3\xa2\xe2\x82\xac\xe2\x84\xa2\xc3\x83\xc6\x92\xc3\x82\xc2\xa2\xc3\x83\xc2\xa2\xc3\xa2\xe2\x82\xac\xc5\xa1\xc3\x82\xc2\xac\xc3\x83\xe2\x80\xa6\xc3\x82\xc2\xa1\xc3\x83\xc6\x92\xc3\x86\xe2\x80\x99\xc3\x83\xc2\xa2\xc3\xa2\xe2\x80\x9a\xc2\xac\xc3\x85\xc2\xa1\xc3\x83\xc6\x92\xc3\xa2\xe2\x82\xac\xc5\xa1\xc3\x83\xe2\x80\x9a\xc3\x82\xc2\xbf\xc3\x83\xc6\x92\xc3\x86\xe2\x80\x99\xc3\x83\xe2\x80\xa0\xc3\xa2\xe2\x82\xac\xe2\x84\xa2\xc3\x83\xc6\x92\xc3\x82\xc2\xa2\xc3\x83\xc2\xa2\xc3\xa2\xe2\x82\xac\xc5\xa1\xc3\x82\xc2\xac\xc3\x83\xe2\x80\xa6\xc3\x82\xc2\xa1\xc3\x83\xc6\x92\xc3\x86\xe2\x80\x99\xc3\x83\xc2\xa2\xc3\xa2\xe2\x80\x9a\xc2\xac\xc3\x85\xc2\xa1\xc3\x83\xc6\x92\xc3\xa2\xe2\x82\xac\xc5\xa1\xc3\x83\xe2\x80\x9a\xc3\x82\xc2\xbdlke_CV.html failed (filesystem path '/home/XXX/www.XXX.de/Sch\xc3\x83\xc6\x92\xc3\x86\xe2\x80\x99\xc3\x83\xe2\x80\xa0\xc3\xa2\xe2\x82\xac\xe2\x84\xa2\xc3\x83\xc6\x92\xc3\xa2\xe2\x82\xac\xc2\xa0\xc3\x83\xc2\xa2\xc3\xa2\xe2\x80\x9a\xc2\xac\xc3\xa2\xe2\x80\x9e\xc2\xa2\xc3\x83\xc6\x92\xc3\x86\xe2\x80\x99\xc3\x83\xc2\xa2\xc3\xa2\xe2\x80\x9a\xc2\xac\xc3\x85\xc2\xa1\xc3\x83\xc6\x92\xc3\xa2\xe2\x82\xac\xc5\xa1\xc3\x83\xe2\x80\x9a\xc3\x82\xc2\xaf\xc3\x83\xc6\x92\xc3\x86\xe2\x80\x99\xc3\x83\xe2\x80\xa0\xc3\xa2\xe2\x82\xac\xe2\x84\xa2\xc3\x83\xc6\x92\xc3\x82\xc2\xa2\xc3\x83\xc2\xa2\xc3\xa2\xe2\x82\xac\xc5\xa1\xc3\x82\xc2\xac\xc3\x83\xe2\x80\xa6\xc3\x82\xc2\xa1\xc3\x83\xc6\x92\xc3\x86\xe2\x80\x99\xc3\x83\xc2\xa2\xc3\xa2\xe2\x80\x9a\xc2\xac\xc3\x85\xc2\xa1\xc3\x83\xc6\x92\xc3\xa2\xe2\x82\xac\xc5\xa1\xc3\x83\xe2\x80\x9a\xc3\x82\xc2\xbf\xc3\x83\xc6\x92\xc3\x86\xe2\x80\x99\xc3\x83\xe2\x80\xa0\xc3\xa2\xe2\x82\xac\xe2\x84\xa2\xc3\x83\xc6\x92\xc3\x82\xc2\xa2\xc3\x83\xc2\xa2\xc3\xa2\xe2\x82\xac\xc5\xa1\xc3\x82\xc2\xac\xc3\x83\xe2\x80\xa6\xc3\x82\xc2\xa1\xc3\x83\xc6\x92\xc3\x86\xe2\x80\x99\xc3\x83\xc2\xa2\xc3\xa2\xe2\x80\x9a\xc2\xac\xc3\x85\xc2\xa1\xc3\x83\xc6\x92\xc3\xa2\xe2\x82\xac\xc5\xa1\xc3\x83\xe2\x80\x9a\xc3\x82\xc2\xbdlke_CV.html')
[Thu Feb 04 07:18:25 2016] [error] [client 78.46.50.246] File does not exist: /home/XXX/www.XXX.de/robots.txt
[Thu Feb 04 07:33:05 2016] [error] [client 66.249.64.14] File does not exist: /home/XXX/www.XXX.de/robots.txt
[Thu Feb 04 07:59:15 2016] [error] [client 136.243.83.16] File does not exist: /home/XXX/www.XXX.de/robots.txt
[Thu Feb 04 08:17:25 2016] [error] [client 84.201.153.12] File does not exist: /home/XXX/www.XXX.de/robots.txt
[Thu Feb 04 09:35:56 2016] [error] [client 202.46.52.179] File does not exist: /home/XXX/www.XXX.de/2011symposium
[Thu Feb 04 10:14:42 2016] [error] [client 193.111.140.106] File does not exist: /home/XXX/www.XXX.de/robots.txt
[Thu Feb 04 10:24:12 2016] [error] [client 194.187.168.234] File does not exist: /home/XXX/www.XXX.de/robots.txt
[Thu Feb 04 10:38:52 2016] [error] [client 184.172.172.26] File does not exist: /home/XXX/www.XXX.de/wordpress
[Thu Feb 04 10:44:49 2016] [error] [client 81.4.124.178] File does not exist: /home/XXX/www.XXX.de/blog
[Thu Feb 04 10:50:47 2016] [error] [client 69.163.208.120] File does not exist: /home/XXX/www.XXX.de/wp
[Thu Feb 04 10:56:47 2016] [error] [client 37.247.54.2] File does not exist: /home/XXX/www.XXX.de/old
[Thu Feb 04 12:46:08 2016] [crit] [client 77.75.254.17] (13)Permission denied: /home/XXX/www.XXX.de/owncloud/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable
[Thu Feb 04 12:46:37 2016] [error] [client 123.125.71.112] File does not exist: /home/XXX/www.XXX.de/robots.txt
[Thu Feb 04 13:07:20 2016] [error] [client 208.115.111.75] File does not exist: /home/XXX/www.XXX.de/robots.txt
[Thu Feb 04 13:20:07 2016] [error] [client 68.180.228.254] File does not exist: /home/XXX/www.XXX.de/robots.txt
[Thu Feb 04 13:28:57 2016] [error] [client 77.75.77.72] File does not exist: /home/XXX/www.XXX.de/robots.txt
[Thu Feb 04 13:32:31 2016] [error] [client 150.214.142.96] File does not exist: /home/XXX/www.XXX.de/breadnav.js, referer: http://www.XXX.de/
[Thu Feb 04 13:32:32 2016] [error] [client 150.214.142.96] File does not exist: /home/XXX/www.XXX.de/favicon.ico, referer: http://www.XXX.de/
[Thu Feb 04 13:46:59 2016] [error] [client 193.175.73.216] File does not exist: /home/XXX/www.XXX.de/favicon.ico
[Thu Feb 04 13:53:21 2016] [error] [client 193.175.73.216] File does not exist: /home/XXX/www.XXX.de/favicon.ico, referer: http://www.XXX.de/owncloud/core/doc/user/documents.html
[Thu Feb 04 14:01:31 2016] [error] [client 5.9.151.22] File does not exist: /home/XXX/www.XXX.de/robots.txt
[Thu Feb 04 14:10:17 2016] [crit] [client 77.75.254.17] (13)Permission denied: /home/XXX/www.XXX.de/owncloud/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable
[Thu Feb 04 14:26:55 2016] [error] [client 193.175.73.216] File does not exist: /home/XXX/www.XXX.de/favicon.ico, referer: http://www.XXX.de/info.php

**Comment by DeepDiver1975** [comment]
You cannot upgrade from a 8.0.x to 8.2.x - you first have to upgrade to 8.1.x

@VicDeo does the updater support this / take care of this? THX

**Comment by VicDeo** [comment]
@DeepDiver1975 
>does the updater support this 

No. Supporting this means storing a list of all owncloud packages already released somewhere.
That's why https://github.com/owncloud/appstore-issues/issues/4 was opened more than a year ago. 
Feed should not propose a package that is not suitable for update (imho).

> does the updater take care of this

yes, there is a check that prevents wrong packages from downloading,  but it checks major digit only so  8.0 ->8.2 is legit from the updater POV

**Comment by RealRancor** [comment]
Ref for removing the misleading message that this should be reported here: https://github.com/owncloud/core/issues/21367

**Comment by MorrisJobke** [comment]
**Exception: Updates between multiple major versions and downgrades are unsupported.** <- unsupported

**Comment by MorrisJobke** [comment]
Fix for this is in #22186
