### ISSUE TITLE
Federate share dissapears in the sidebar and removes the share label on the files view until refreshing.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#22120]
### Steps to reproduce

1. Make a federated share from admin in serverA to user1 in serverB.
2. Accept share using user1 on serverB.
3. Refresh the page.
4. As admin on serverA, open the sidebar, click on sharing.

### Expected behaviour
You can see the file is shared with user1 in serverB.

### Actual behaviour
All sharing disappears.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Master branch
{"installed":true,"maintenance":false,"version":"9.0.0.8","versionstring":"9.0 pre alpha","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No

**Logs**

```
```

### Client configuration

**browser**
Chrome

**Comment by PVince81** [comment]
@rullzer I think we made a mistake when switching to the OCS API.

The OCS API doesn't return federated shares it seems. Or is it part of the federated share provider task ?

**Comment by rullzer** [comment]
Will be fixed by https://github.com/owncloud/core/pull/22080

**Comment by rullzer** [comment]
This is fixed with #22080
