### ISSUE TITLE
heavy problems while i'am trying to update from ownCloud 7.0.4 to 8.x

### ISSUE THREAD

**Issue by towerlexa** [owncloud/core#22136]
Hi @All,

i've some strange problems while i'am trying to upgrade from 7.0.4 to 8.x.x (8.2.1 currently)!

In the moment i couldn't really explain all the circumstances. I a parallel testing installation the upgrade was successful. I have to rerun the upgrade with some different versions. ( 7.0.4 => 8.0.0 => 8.1.[45] => 8.2.2).
As i mentioned, on my testing env it is working fine. 

In my production environment these steps results by the hair in a complete lost of my calendar!!! What the [......] is happen there ? Dou you think, that the owncloud logfile may have some more informations?

Could you please give me some hints what could going wrong there? What kind of logging may i create to give you enough hints for solving the problem?
Are there any debug switches i could set during the upgrade process?
How could i ensure, that my data wont lost?

Any helps and hints are highly appreciated, because my owncloud instance is aging, faster i could update it :-(...

Kind regards

Axel Birndt

PS: Of course i (waste) use a lot of time for googling, and searching all the resources, which are exist. But for this (in my mind) very strange issue, i don't found any solution.

PS1: My owncloud instance is running on Debian Wheezy, may there be some strange php, or other version issues?? In the moment i'am trying to upgrade to Jessie, but this isn't complete yet.

[owncloud.log_filtered_december_for_bugreport_04.02.2016.txt](https://github.com/owncloud/core/files/117762/owncloud.log_filtered_december_for_bugreport_04.02.2016.txt)

**Comment by karlitschek** [comment]
Please post you question at one of the support channels listed here: owncloud.org/support  Thanks

**Comment by towerlexa** [comment]
sory for my mistake. could you move it?
