### ISSUE TITLE
OC 8.2.2 | Openstack Swift

### ISSUE THREAD

**Issue by sirkazey** [owncloud/core#22132]
Hi everybody, 
I've a issue with Openstack Swift. I can't access to my cloud storage. I've tried with cloudberry swift browser and it works.

`Error 	PHP 	readdir() expects parameter 1 to be resource, boolean given at /volume1/web/owncloud/apps/files_external/lib/swift.php#561`

For the record, my authentication is Keystone V2

My OS is hosted on a Synology.

Thanks a lot,

**Comment by LukasReschke** [comment]
Please fill out the issue template: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version
