### ISSUE TITLE
ownCloud 8.0.2 update problem

### ISSUE THREAD

**Issue by gnomo84** [owncloud/core#22137]
Server Centos 7.0.1406
Owncloud version: 8.2.0 (stable)

when I try to upgrade (via UI) from version 8.2 to 8.2.2 (stable) I get this error:

> Unable to move /var/www/html/owncloud/_oc-upgrade/8.2.2.2/core/core to /var/www/html/owncloud/core
>

**Comment by karlitschek** [comment]
Please post this error at one of the support channels listed at owncloud.org/support. Thanks
