### ISSUE TITLE
OCC Setting an array Configuration Value fails

### ISSUE THREAD

**Issue by sporokh** [owncloud/core#22131]
From the official document:
https://doc.owncloud.org/server/8.2/admin_manual/configuration_server/occ_command.html

Some configurations (e.g. the trusted domain setting) are an array of data. In order to set (and also get) the value of one key, you can specify multiple config names separated by spaces:
`$ sudo -u www-data php occ config:system:get trusted_domains`
localhost
owncloud.local
sample.tld

To replace sample.tld with example.com trusted_domains => 2 needs to be set:
`$ sudo -u www-data php occ config:system:set trusted_domains 2 --value=example.com`
System config value trusted_domains => 2 set to string example.com

I got owncloud server 'version' => '8.2.2.2' up and runing. But when I try to replace trusted domains, I got this kind of exception:
`sudo -u www-data php occ config:system:set trusted_domains 1 --value=example.com`

` [RuntimeException]   
  Too many arguments.  
`

**Comment by karlitschek** [comment]
@LukasReschke can you have a look please?

**Comment by LukasReschke** [comment]
Documentation lies, this has been merged with https://github.com/owncloud/documentation/pull/2092 and  is 9.0 only.

@carlaschroder You merged this with https://github.com/owncloud/documentation/commit/222e44b6044288d56d53c8804d0025b5eece6249 into stable8.2. Can you double check? THX.

**Comment by LukasReschke** [comment]
@sporokh This command is only available with the upcoming master release. Sorry.

See https://github.com/owncloud/core/pull/18444

**Comment by sporokh** [comment]
@LukasReschke Thanks a lot with the fast response

**Comment by carlaschroder** [comment]
Sorry, but these commands are on 8.2.2:

````
config
 config:app:delete                    Delete an app config value
 config:app:get                       Get an app config value
 config:app:set                       Set an app config value
 config:import                        Import a list of configs
 config:list                          List all configs
 config:system:delete                 Delete a system config value
 config:system:get                    Get a system config value
 config:system:set                    Set a system config value
````

It appears to be a syntax problem:

````
$ sudo -u www-data php occ config:system:get trusted_domains
localhost

$ sudo -u www-data php occ config:system:set trusted_domains 1 --value=example.com                       
  [RuntimeException]   
 Too many arguments.  

$ sudo -u www-data php occ config:system:set trusted_domains  --value=example.com
System config value trusted_domains set to example.com
$ sudo -u www-data php occ config:system:get trusted_domains example.com
````

So, who knows the correct syntax?

**Comment by sporokh** [comment]
@carlaschroder 
When you doing this 
`sudo -u www-data php occ config:system:set trusted_domains  --value=example.com`
you inserting trusted_domains like a variable, not like an array. Just to point it out.
So how to insert array argument correctly?

**Comment by LukasReschke** [comment]
> Sorry, but these commands are on 8.2.2:

The commands itself: Yes. But only for strings, any other data type modification is only available in master.

So "Setting an array Configuration Value" is only applicable for 9.0

**Comment by LukasReschke** [comment]
The syntax itself will be correct on 9.0:

> ➜  master git:(master) ✗ ./occ config:system:set trusted_domains 1 --value=example.com
System config value trusted_domains => 1 set to string example.com

**Comment by carlaschroder** [comment]
Thanks @LukasReschke

**Comment by carlaschroder** [comment]
Is there any chance of adding a helpful error or help message to 8.2? The commands are there, with no indication that they're not going to work as expected.

**Comment by carlaschroder** [comment]
Of course I will add a doc note.

**Comment by carlaschroder** [comment]
This is getting weirder. When I run  config:system:set for trusted_domains or maintenance, and then try to open the Web GUI, I get errors. When I manually correct config.php I get the same errors. Does config:system:set write to some secret config file that overrides config.php? I'm opening a separate issue for all this.

**Comment by carlaschroder** [comment]
Allrightythen, fixed in docs. config:system:set does not write to config.php with correct syntax, and does not give error messages when you use wrong config values. I'll follow it in 9.0 & report any 9.0 issues that I find.

**Comment by carlaschroder** [comment]
Thanks for reporting this, @sporokh
