### ISSUE TITLE
PHP errors when trying fresh install

### ISSUE THREAD

**Issue by thejrose1984** [owncloud/core#22141]
Running ownCloud from FreeNAS/FreeBSD. Currently installed as package and running on nginx. Figured I'd try installing an instance from git.

Unfortunately, it wasn't as simple as running `git clone https://github.com/owncloud/core.git` and adjusting nginx conf file didn't do the trick. I would restart php-fpm and nginx, but would be greeted by a blank page and the following errors in the logs - http://pastebin.com/KKMY7dsh

Also tried copying my conf file in place and restarted services again - same errors found in the logs. Any suggestions?

**Comment by vincchan** [comment]
You're missing the 3rdparty submodule. Try:
```git clone --recursive https://github.com/owncloud/core.git```

**Comment by RealRancor** [comment]
Probably something which better fits somewhere here: https://owncloud.org/support/

**Comment by DeepDiver1975** [comment]
> Figured I'd try installing an instance from git.

You better only walk this path as a developer. We provide tars to be downloaded:
https://owncloud.org/install/

**Comment by thejrose1984** [comment]
Noted, however the stable version, at least where my setup is concerned, can be quirky at times. I found the master version in the git repository seems more stable than what was in FreeBSD's repositories.

**Comment by RealRancor** [comment]
If you want to use testing versions you still can use those without git:

https://owncloud.org/install/#testing-development
