### ISSUE TITLE
occ upgrade notification before use of any occ command if the instance requires that

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#22142]
Using master, 9.0 pre alpha

**Issue**
I upgraded (rebase) my test instance (last rebase was last week was also 9.0 pre alpha) and wanted to use ``sudo -uwww-data ./occ files:scan --all`` immediately after. Interestingly nothing happend and when I interrupted with ctrl-c, I got a strange error on the console that something is wrong with symphony. I had that issue once in the past and remembered that the error shown is totally unrelated to the root cause.

In reality I needed to run a occ upgrade and then any other occ command runs fine and without error.

You can also run a pure occ command without any parameter and then you get the note that a upgrade is mandatory before using any occ parameter (like files:scan).

Currently the occ command entered (except empty and upgrade...) looks like it is stuck and runs forever.

**Suggestion**
Check on any occ command if there is an mandatory upgrade necessary, drop a command line note and do not run the command entered.

**Comment by karlitschek** [comment]
The correct way here is that the developers increase the minor version number and then an upgrade is executed automatically.

**Comment by mmattel** [comment]
hmmm,
please correct me if I do not see this correct but...
If I do a git rebase (not using a browser!) and directly afterwards a occ command, I do not know if an upgrade is necessary or not. A upgrade is currently NOT made automatically when the occ command starts. This would IMHO also not be wanted and is a decision by the admin when done. But when I run a occ command and the command does not respond caused by upgrade needs after the rebase, I would like to see at least a notification on the command shell about this need. This would also prevent unrelated error messages when interruptung the stuck command with ctrl-c...
