### ISSUE TITLE
"Get the apps to sync your files" pixelated on retina

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#22154]
The icons are not using the SVG version which makes it look pixelated on a retina screen.

Ref https://github.com/owncloud/core/blob/7dde2c773f4efee0094176fe76b2c64f4f74a1ea/settings/templates/personal.php#L171-L183

**Comment by LukasReschke** [comment]
We have one for the desktop app button but not for the others. I'll adjust that, the other stuff is probably up to @owncloud/designers.

**Comment by LukasReschke** [comment]
![2016-02-05_13-01-24](https://cloud.githubusercontent.com/assets/878997/12845782/924051ac-cc08-11e5-8e50-29ab073e2206.png)

**Comment by LukasReschke** [comment]
What a pity, the desktop app button looks wrong on Firefox as per @rullzer in https://github.com/owncloud/core/pull/22155#issuecomment-180324561

**Comment by Henni** [comment]
@LukasReschke this is probably because @rullzer hasn't installed the FreeSans font which is used by the SVG.
The SVG looks good to me in Chrome and Firefox

**Comment by rullzer** [comment]
@Henni indeed that is not yet installed on the new laptop.

But I don't think we can assume this font to be available at all our users...

**Comment by Henni** [comment]
@rullzer sure we can't. But we can include it or use a different font.
Give me a second

**Comment by rullzer** [comment]
Awesome thanks!
