### ISSUE TITLE
#navigation: add overflow: auto

### ISSUE THREAD

**Issue by stefan-niedermann** [owncloud/core#22158]
It will have no effect on the most instances, but if you have installed many apps, you will be able to scroll to bottom apps.

Without overflow: auto:
Not scrollable, only the top apps are reachable
![without-overflow](https://cloud.githubusercontent.com/assets/4741199/12846839/3567c026-cc0f-11e5-9e3f-cf758f82ecdd.png)

With overflow: auto:
Scrollbar appears on instances with many apps and all apps are reachable
![with-overflow](https://cloud.githubusercontent.com/assets/4741199/12846854/482ac38e-cc0f-11e5-8ce3-3484c899fe8b.png)

Maybe the navigation should expand to the right when there are very many apps?
cc @jancborchardt @owncloud/designers

**Comment by LukasReschke** [comment]
@v1r0x or @Gomez also mentioned something like that to me I think.

**Comment by v1r0x** [comment]
@LukasReschke Yes, I mentioned it at 32c3. With around 16 apps (+ the apps settings) enabled the last row is outside the div. A scrollbar would definitely be a good temporary solution.
Maybe something like the [android marshmallow app drawer](http://media2.giga.de/2015/06/android-m-app-drawer--rcm992x0.png) would be a good solution?
- First row with favorite/most often used apps
- All apps in alphabetical order after the favorite row
- above the first row a search bar to filter apps

**Comment by jancborchardt** [comment]
@stefan-niedermann yup. You wanna add that? We had it in the past, not sure where it got lost.

**Comment by stefan-niedermann** [comment]
hmm, i'll try to prepare a pull request. not sure about the build ‎procedure in core.

**Comment by MorrisJobke** [comment]
> hmm, i'll try to prepare a pull request. not sure about the build ‎procedure in core.

There is none ;) Just update the css files.

**Comment by stefan-niedermann** [comment]
Tricky, it's [already there](https://github.com/owncloud/core/blob/master/core/css/header.css#L159-L160) but commented out - and i think i know why.
```css
	/*overflow-y: auto;
	overflow-x: hidden;*/
```
it causes disappearing of the black arrow. Well, have to think about it...

**Comment by jancborchardt** [comment]
Aaah yes. Sorry for not adding a proper comment. At the time it was a tradeoff and the black arrow was more important than having the potential to be able to show a huuuge amount of apps. We should find a solution to this though. :)

**Comment by ErikPel** [comment]
How do I get that many apps so I can test and work on this?

Is there easy way or do I just have to create bunch of mock apps?

**Comment by stefan-niedermann** [comment]
hehe, just use developer tools of your browser and copy 'n' paste one entry ;)
