### ISSUE TITLE
Chrome blocking modal dialogs

### ISSUE THREAD

**Issue by weedenb** [owncloud/core#22179]
With Chrome's default blocking of modal dialogs [https://googlechrome.github.io/samples/block-modal-dialogs-sandboxed-iframe/](url) is there any effort underway to address the impact on OC's functionality? window.print() from pdfviewer is my current showstopper.

Posted over on the forums ( [https://forum.owncloud.org/viewtopic.php?f=36&t=32910](url)) but was advised to do here also.

**Comment by LukasReschke** [comment]
> window.print() from pdfviewer is my current showstopper.

Please reopen at https://github.com/owncloud/files_pdfviewer

**Comment by ErikPel** [comment]
I think this is already fixed?
Check out
https://github.com/owncloud/files_pdfviewer/commit/15fe81ee9b211745f1b01a26760ae8719c733db2

I think if you just update the app this should be resolved, or am I missing something?
