### ISSUE TITLE
TBD: Authorization stuff in .htaccess for non mod_php servers

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#22178]
Hi,

after https://github.com/owncloud/core/pull/18194 was merged i had another look at this whole authorization stuff in the .htaccess. This is currently just a mess from my PoV:

When searching on google the only hits for "XAUTHORIZATION" are for ownCloud which was introduced some years ago in https://github.com/owncloud/core/pull/337. As oC is not the only PHP application out there it looks really strange to me.

Does anyone out there have any insights in the various modules which could be used:

mod_fcgid
mod_cgi (https://github.com/owncloud/core/issues/15883)
mod_proxy_fcgi
mod_fastcgi

I have added the two missing to https://github.com/owncloud/core/pull/22177 however no idea if this is correct.

**Comment by RealRancor** [comment]
The apache 2.4 docs are also showing a config option which might be needed https://httpd.apache.org/docs/2.4/en/mod/core.html#cgipassauth

**Comment by LukasReschke** [comment]
Before somebody mentions me in here: Nope. No idea myself :speak_no_evil:

**Comment by RealRancor** [comment]
@LukasReschke At least i'm not alone :-)

**Comment by RealRancor** [comment]
https://github.com/owncloud/core/pull/22177 was closed because no one has the knowledge about that stuff so also closing here.
