### ISSUE TITLE
Feature Request: Method User::login() 

### ISSUE THREAD

**Issue by alve89** [owncloud/core#22181]
Hi all!

Was it possible to extend \OCP\User by a method login($uid, $password) to enable a login with an external script (that includes /lib/base.php)? Because if a logout is possible, why not a login...? :-)

**Comment by LukasReschke** [comment]
> Was it possible to extend \OCP\User by a method login($uid, $password) to enable a login with an external script (that includes /lib/base.php)? Because if a logout is possible, why not a login...? :-)

This is already possible using https://github.com/owncloud/core/blob/feb0522cd059c44b77b5afe1382e5f62bbeb59aa/lib/public/authentication/iapachebackend.php

https://github.com/owncloud/core/blob/2bafb1c6493d67360f9ac6f4997a56664f3f2751/lib/private/user.php#L215-L236

**Comment by alve89** [comment]
I'm sorry, but first I think that's not what I meant (because this requires an authentication against Apache - and I don't know how to make this work because I'm not using the basic auth but an authentication against my IMAP server. And this isn't working with Apache authentication).
Second I'd like to login a user with PHP directly from a script (here: against my IMAP-server).
Is this special case also possible with the existing methods or is my wish for a new method justified?

**Comment by LukasReschke** [comment]
> I'm sorry, but first I think that's not what I meant (because this requires an authentication against Apache - and I don't know how to make this work because I'm not using the basic auth but an authentication against my IMAP server. And this isn't working with Apache authentication).

It does not require Apache or anything. It's simply called that way. Implement `IApacheBackend` and checkout `isSessionActive` and `getCurrentUserId`.

**Comment by LukasReschke** [comment]
Furthermore, this is a bug tracker and already possible. For support and development related questions such as those please refer to https://owncloud.org/support/ (or our IRC channel etc.)
