### ISSUE TITLE
Grey stars remain when unfavoriting files in edge.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#22188]
### Steps to reproduce

Having several files and using edge as browser do:
1. Favorite all files.
2. Unfavorite all files.
### Expected behaviour

All stars dissapear.
### Actual behaviour

Some grey stars remain.

![screen shot 2016-02-08 at 09 27 27](https://cloud.githubusercontent.com/assets/9048796/12881020/acbdccea-ce46-11e5-92ab-1879f79fe9f4.png)
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Master branch
{"installed":true,"maintenance":false,"version":"9.0.0.10","versionstring":"9.0 pre alpha","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No

**Logs**

```
```
### Client configuration

**browser**
Edge

**Comment by PVince81** [comment]
Maybe the "permanent" class wasn't removed properly for some reason or Edge is having bugs related to hover effects. Tagging as junior job for whoever wants to investigate.

**Comment by jancborchardt** [comment]
Yeah, this most likely seems to be a JS issue. Removing design label.

**Comment by kavishdahekar** [comment]
Was able to reproduce the error in Edge.
After un-favouriting, not only do some stars remain gray, some rows stay highlighted even if the stars have reset back to white.
Apparently, simply hovering over the rows clears the issue.
Seems like a JS issue as @jancborchardt predicted. Looking further to pin-point the problem.

**Comment by kavishdahekar** [comment]
Found a way to reproduce the bug consistently.
![image](https://cloud.githubusercontent.com/assets/3937361/13477449/7178574a-e0f2-11e5-993d-b4b5afc63ef0.png)

1. For any file, click its star to favorite it. Animation will be displayed. Star will turn yellow.
2. Click it again to unfavorite but don't move the mouse away from where you just clicked, the animation will display, just when the animation is about to end, remove mouse from the star. The hover event will stay on the star even though you have removed the mouse.

**Comment by kavishdahekar** [comment]
I found it!! Found the bug.
https://connect.microsoft.com/IE/feedback/details/926665/ie-11-hovering-over-an-element-and-then-scrolling-without-moving-the-mouse-pointer-leaves-the-element-in-hover-state

Doesn't look like they fixed it, can somebody please take a look?

**Comment by PVince81** [comment]
moved to more general UX group ticket: https://github.com/owncloud/core/issues/27578
