### ISSUE TITLE
server replied: Internal Server Error

### ISSUE THREAD

**Issue by fihufil** [owncloud/core#22184]
I recently installed fresh ownCloud 8.2.2 from repository for Ubuntu 14.04 and copied over my old data dir from 8.0.4. The web server is nginx.
Desktop client (verion 2.1.0-11.1 on Ubuntu 14.04) throws errors constantly:
server replied: Internal Server Error
owncloud.log shows the following:

`
{"reqId":"nFLm1iJj2teeacmucmMs","remoteAddr":"83.9.69.116","app":"base","message":"Exception: {\"Exception\":\"ErrorException\",\"Message\":\"session_start(): ps_files_cleanup_dir: opendir(\\\/var\\\/lib\\\/php5) failed: Permission denied (13)\",\"Code\":0,\"Trace\":\"#0 [internal function]: OC\\\\Session\\\\Internal->trapError(8, 'session_start()...', '\\\/var\\\/www\\\/ownclo...', 44, Array)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/session\\\/internal.php(44): session_start()\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(411): OC\\\\Session\\\\Internal->__construct('ocbrgedlo9bs')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(568): OC::initSession()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(1081): OC::init()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(87): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/session\\\/internal.php\",\"Line\":106}","level":3,"time":"2016-02-08T00:20:11+00:00"}
`
`
{"reqId":"MaOzKhpV9cflSIRkAibI","remoteAddr":"83.9.69.116","app":"base","message":"Exception: {\"Exception\":\"ErrorException\",\"Message\":\"session_start(): ps_files_cleanup_dir: opendir(\\\/var\\\/lib\\\/php5) failed: Permission denied (13)\",\"Code\":0,\"Trace\":\"#0 [internal function]: OC\\\\Session\\\\Internal->trapError(8, 'session_start()...', '\\\/var\\\/www\\\/ownclo...', 44, Array)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/session\\\/internal.php(44): session_start()\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(411): OC\\\\Session\\\\Internal->__construct('ocbrgedlo9bs')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(568): OC::initSession()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(1081): OC::init()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(87): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/session\\\/internal.php\",\"Line\":106}","level":3,"time":"2016-02-08T00:21:02+00:00"}
`
`
{"reqId":"XEPNVqgHTMIsmpxniRgQ","remoteAddr":"83.9.69.116","app":"base","message":"Exception: {\"Exception\":\"ErrorException\",\"Message\":\"session_start(): ps_files_cleanup_dir: opendir(\\\/var\\\/lib\\\/php5) failed: Permission denied (13)\",\"Code\":0,\"Trace\":\"#0 [internal function]: OC\\\\Session\\\\Internal->trapError(8, 'session_start()...', '\\\/var\\\/www\\\/ownclo...', 44, Array)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/session\\\/internal.php(44): session_start()\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(411): OC\\\\Session\\\\Internal->__construct('ocbrgedlo9bs')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(568): OC::initSession()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(1081): OC::init()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(87): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/session\\\/internal.php\",\"Line\":106}","level":3,"time":"2016-02-08T00:22:02+00:00"}
`

nginx error log show no errors. I belive it to be a bug because /var/lib/php5 has drwx-wx-wt permissions by design.

EDIT: Web interface also randomly give errors at login: Internal Server Error and it produce same as above output in owncloud.log

**Comment by RealRancor** [comment]
Hi,

you have some permission issues. Please see https://owncloud.org/support/ where to get help for such configuration issues.

**Comment by MorrisJobke** [comment]
@fihufil Please check your permissions:

```
ps_files_cleanup_dir: opendir(\\\/var\\\/lib\\\/php5) failed: Permission denied (13)
```

Closing because it is a setup issue.
