### ISSUE TITLE
Receiving Unauthorized error while using edit user function in the provisioning api

### ISSUE THREAD

**Issue by supportreq** [owncloud/core#22194]
For all edit user apis under the provisioning api I am getting the following error : 
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>997</statuscode>
  <message>Unauthorised</message>
 </meta>
 <data/>
</ocs>

I tried using "http://user1:password@localhost.com/ocs/v1.php/cloud/users/user1" and also "http://admin:adminpass@localhost.com/ocs/v1.php/cloud/users/user1"

Please advice, I want to change the email id. Thank You

**Comment by LukasReschke** [comment]
Please fill out the issue template. 
https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version

**Comment by LukasReschke** [comment]
Also this seems not like a bug and more like a question => owncloud.org/support
