### ISSUE TITLE
Unable to install any apps

### ISSUE THREAD

**Issue by DanielMalmgren** [owncloud/core#22196]
I simply don't see any of the links that I'm supposed to see at index.php/settings/apps that are related to installing any apps. Discussed this on G+ (https://plus.google.com/115070296268980646831/posts/6Zbt5exf9iK) and found no solution, so I'm thinking it might be a bug somewhere.

Pasting filled-in issue template:
### Steps to reproduce
1. Log in as admin
2. Click apps in the top left menu

### Expected behaviour
I should see something like this: https://doc.owncloud.org/server/8.0/admin_manual/_images/oc_admin_app_page.png

### Actual behaviour
I see enabled and not enabled apps in the left column, other than that it's empty

### Server configuration
**Operating system**: Debian 8.3 (armhf)

**Web server:** Apache 2.4.10

**Database:** MySQL 5.5.46

**PHP version:** 5.6.17

**ownCloud version:** 8.2.2

**Updated from an older ownCloud or fresh install:** Updated from 7.x (and before that 6.x if I'm not remembering wrong)

**List of activated apps:**
The default ones:
  - activity: 2.1.3
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - templateeditor: 0.1

**The content of config/config.php:**

(note: The only things I've changed there is appstoreenabled, appstoreurl and apps_paths, which I've changed to try to fix my problem)

  'trusted_domains' =>
  array (
    0 => 'cube',
    1 => 'whatever',
  ),
  'datadirectory' => '/usr/share/owncloud/data',
  'overwrite.cli.url' => 'http://cube/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.2.2.2',
  'appstoreenabled' => true,
  "appstoreurl" => "http://api.apps.owncloud.com/v1",
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/usr/share/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => array (
      "path" => "/usr/share/owncloud/apps2",
      "url" => "/apps2",
       "writable" => true,
    ),
  ),
  'dbname' => 'owncloud',
  'filesystem_check_changes' => 1,
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'installed' => true,
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'theme' => '',
  'maintenance' => false,
  'forcessl' => true,
  'loglevel' => 2,
  'trashbin_retention_obligation' => 'auto',

**Are you using external storage, if yes which one:** local/smb/sftp/...

Nope

**Are you using encryption:** yes/no

Well, I'm using https, if that's what the question is about?

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

No

### Client configuration
**Browser:** Mostly Firefox

**Operating system:** Windows 7 and Windows 10 tested

#### Web server error log

Found nothing that seems related to this. Nothing new in the log when I access index.php/settings/apps

#### ownCloud log (data/owncloud.log)

These are the rows I get in the log when accessing the apps page:

{"reqId":"A0519DMtBy13WoeONHYX","remoteAddr":"193.42.159.226","app":"PHP","message":"vsprintf(): Too few arguments at \/usr\/share\/owncloud\/lib\/private\/l10n\/string.php#76","level":3,"time":"2016-02-08T10:39:08+00:00"}
{"reqId":"A0519DMtBy13WoeONHYX","remoteAddr":"193.42.159.226","app":"PHP","message":"Method OC_L10N_String::__toString() must return a string value at \/usr\/share\/owncloud\/lib\/private\/util.php#1168","level":3,"time":"2016-02-08T10:39:08+00:00"}
{"reqId":"33bcIDdnGQNkrGtZrcUa","remoteAddr":"193.42.159.226","app":"core","message":"Could not get categories, content was no valid XML","level":3,"time":"2016-02-08T10:39:10+00:00"}
{"reqId":"2MptgNoV4JErPOawlL7v","remoteAddr":"193.42.159.226","app":"core","message":"Could not get application, content was no valid XML","level":3,"time":"2016-02-08T10:39:11+00:00"}
{"reqId":"2MptgNoV4JErPOawlL7v","remoteAddr":"193.42.159.226","app":"core","message":"Could not get application, content was no valid XML","level":3,"time":"2016-02-08T10:39:12+00:00"}
{"reqId":"2MptgNoV4JErPOawlL7v","remoteAddr":"193.42.159.226","app":"core","message":"Could not get application, content was no valid XML","level":3,"time":"2016-02-08T10:39:12+00:00"}
{"reqId":"2MptgNoV4JErPOawlL7v","remoteAddr":"193.42.159.226","app":"core","message":"Could not get application, content was no valid XML","level":3,"time":"2016-02-08T10:39:13+00:00"}

**Comment by DeepDiver1975** [comment]
> {"reqId":"33bcIDdnGQNkrGtZrcUa","remoteAddr":"193.42.159.226","app":"core","message":"Could not get categories, content was no valid XML","level":3,"time":"2016-02-08T10:39:10+00:00"}
> {"reqId":"2MptgNoV4JErPOawlL7v","remoteAddr":"193.42.159.226","app":"core","message":"Could not get application, content was no valid XML","level":3,"time":"2016-02-08T10:39:11+00:00"}
> {"reqId":"2MptgNoV4JErPOawlL7v","remoteAddr":"193.42.159.226","app":"core","message":"Could not get application, content was no valid XML","level":3,"time":"2016-02-08T10:39:12+00:00"}
> {"reqId":"2MptgNoV4JErPOawlL7v","remoteAddr":"193.42.159.226","app":"core","message":"Could not get application, content was no valid XML","level":3,"time":"2016-02-08T10:39:12+00:00"}
> {"reqId":"2MptgNoV4JErPOawlL7v","remoteAddr":"193.42.159.226","app":"core","message":"Could not get application, content was no valid XML","level":3,"time":"2016-02-08T10:39:13+00:00"}

this indicates that you are having issues connecting to the appstore and as a result no apps are displayed for installation

**Comment by DeepDiver1975** [comment]
> "appstoreurl" => "http://api.apps.owncloud.com/v1",

remove that line from the config - there is no need in adjusting this

**Comment by LukasReschke** [comment]
>  "appstoreurl" => "http://api.apps.owncloud.com/v1",

Why did you change that? That's just wrong. Please don't adjust config values you don't need to adjust and don't properly understand. That is doomed to fail. :speak_no_evil:

**Comment by DanielMalmgren** [comment]
Ok... That's weird. The server is not behind any form of proxy or anything like that. Doing a "wget http://api.apps.owncloud.com/v1" works fine. What does it need to reach?

The appstoreurl was added when I tried to solve the problem. It doesn't work with or without it...

**Comment by LukasReschke** [comment]
> Ok... That's weird. The server is not behind any form of proxy or anything like that. Doing a "wget http://api.apps.owncloud.com/v1" works fine. What does it need to reach?

The api. The server you have specified there does _NOT_ reach the API. It's a wrong URL.

**Comment by LukasReschke** [comment]
> The appstoreurl was added when I tried to solve the problem. It doesn't work with or without it...

Also go to your admin menu and tell us what it says in the setup warnings and so on. Plus do a `ls` over the ownCloud folder and post the reuslts.

**Comment by DanielMalmgren** [comment]
Doh. Removing the appstoreurl actually did make things work... Question then is why it didn't work in the first place...

**Comment by LukasReschke** [comment]
> Doh. Removing the appstoreurl actually did make things work... Question then is why it didn't work in the first place...

:crystal_ball: :wink: 

Closing this one then. Maybe a hiccups on the API server or so…

**Comment by DanielMalmgren** [comment]
Thanks a lot!

**Comment by Pazu** [comment]
I have this _'appstoreurl' => 'http://api.apps.owncloud.com/v1'_ in my config as well, but I'm certain I never added or modified it. My config has been around for years, though; is it possible this was originally included with config in older versions of owncloud?

I see the sample config now specifies a different URL for this; is it recommended now to change it to 'https://api.owncloud.com/v1'? Should owncloud do this itself during upgrade?

**Comment by RealRancor** [comment]
> included with config in older versions of owncloud?

This was never included in any config of older oC versions. But you might have copied over the config.sample.php to config.php in the past.

> is it recommended now to change it to 'https://api.owncloud.com/v1

It is recommended to remove it completely. See also:

> The installer creates a configuration containing the essential parameters. Only manually add configuration parameters to config/config.php if you need to use a special value for a parameter. Do not copy everything from config/config.sample.php . Only enter the parameters you wish to modify!

The page there has a sane default config.php listed:

https://doc.owncloud.org/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#default-config-php-examples

If unsure setup a fresh oC 9.1 installation and compare the config.php from there with yours. Then clean-up your old config.php file.

> Should owncloud do this itself during upgrade?

Nope, oC shouldn't touch user configured stuff in the config.php during the upgrade
