### ISSUE TITLE
External storage cannot be mounted using global credentials.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#22195]
### Steps to reproduce

Having several files and using edge as browser do:
Having external storage app enabled as admin do:
1. Mount FTP external storage using global credentials.

### Expected behaviour
FTP folder is mounted.

### Actual behaviour
FTP folder is not mounted.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Master branch
{"installed":true,"maintenance":false,"version":"9.0.0.10","versionstring":"9.0 pre alpha","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No

**Logs**

```
{"reqId":"DKh4VDNsNoB610I782yu","remoteAddr":"HIDED_IP","app":"PHP","message":"Call to a member function getUID() on a non-object at \/opt\/owncloud\/apps\/files_external\/lib\/auth\/password\/globalauth.php#78","level":3,"time":"2016-02-08T10:22:02+00:00"}
```

### Client configuration

**browser**
Chrome

**Comment by SergioBertolinSG** [comment]
Happening also with SFTP. And the files view cannot be accessed anymore after mounting it with global credentials.

**Comment by PVince81** [comment]
Weird, it worked when I tested it in a PR. Maybe something else broke it.

@icewind1991

**Comment by icewind1991** [comment]
possible fix: #22202

**Comment by SergioBertolinSG** [comment]
Sorry, this is a mistake. The FTP server was not accessible. 
But connecting to it make the instance to hard fail.

**Comment by SergioBertolinSG** [comment]
I'll close it an probably open another with the bad connection situation.
