### ISSUE TITLE
First run wizard fails to load.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#22201]
### Steps to reproduce

1. With a new user open oc web for first time.

### Expected behaviour
First run wizard.

### Actual behaviour
Content failed to load.

![screen shot 2016-02-08 at 09 24 46](https://cloud.githubusercontent.com/assets/9048796/12885399/ec8d6f1e-ce65-11e5-99ac-c0baba552eea.png)

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Master branch
{"installed":true,"maintenance":false,"version":"9.0.0.10","versionstring":"9.0 pre alpha","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No

**Logs**

```
```

### Client configuration

**browser**
Chrome

**Comment by DeepDiver1975** [comment]
Anything in the browser error console?
Anything in owncloud logs?
Anything in the web server logs?

Please - without this information bug reports like this are pointless - THX

**Comment by DeepDiver1975** [comment]
@LukasReschke maybe some content security fun?

**Comment by LukasReschke** [comment]
![2016-02-09_09-57-17](https://cloud.githubusercontent.com/assets/878997/12911545/8cc32b4c-cf13-11e5-87f6-05c72a5e96a2.png)

```
{"reqId":"DLP51xYQA+ecqTf3G8Hk","remoteAddr":"::1","app":"index","message":"Exception: {\"Exception\":\"RuntimeException\",\"Message\":\"image not found: image:appstore.png webroot:\\\/master serverroot:\\\/Users\\\/lukasreschke\\\/Documents\\\/Programming\\\/master\",\"Code\":0,\"Trace\":\"#0 \\\/Users\\\/lukasreschke\\\/Documents\\\/Programming\\\/master\\\/lib\\\/public\\\/util.php(425): OC\\\\URLGenerator->imagePath('core', 'appstore.png')\\n#1 \\\/Users\\\/lukasreschke\\\/Documents\\\/Programming\\\/master\\\/apps\\\/firstrunwizard\\\/templates\\\/wizard.php(23): OCP\\\\Util::imagePath('core', 'appstore.png')\\n#2 \\\/Users\\\/lukasreschke\\\/Documents\\\/Programming\\\/master\\\/lib\\\/private\\\/template\\\/base.php(161): include('\\\/Users\\\/lukasres...')\\n#3 \\\/Users\\\/lukasreschke\\\/Documents\\\/Programming\\\/master\\\/lib\\\/private\\\/template\\\/base.php(139): OC\\\\Template\\\\Base->load('\\\/Users\\\/lukasres...')\\n#4 \\\/Users\\\/lukasreschke\\\/Documents\\\/Programming\\\/master\\\/lib\\\/private\\\/template.php(223): OC\\\\Template\\\\Base->fetchPage()\\n#5 \\\/Users\\\/lukasreschke\\\/Documents\\\/Programming\\\/master\\\/lib\\\/private\\\/template\\\/base.php(122): OC_Template->fetchPage()\\n#6 \\\/Users\\\/lukasreschke\\\/Documents\\\/Programming\\\/master\\\/apps\\\/firstrunwizard\\\/wizard.php(43): OC\\\\Template\\\\Base->printPage()\\n#7 \\\/Users\\\/lukasreschke\\\/Documents\\\/Programming\\\/master\\\/lib\\\/private\\\/route\\\/route.php(154) : runtime-created function(1): require_once('\\\/Users\\\/lukasres...')\\n#8 [internal function]: __lambda_func(Array)\\n#9 \\\/Users\\\/lukasreschke\\\/Documents\\\/Programming\\\/master\\\/lib\\\/private\\\/route\\\/router.php(273): call_user_func('\\\\x00lambda_6178', Array)\\n#10 \\\/Users\\\/lukasreschke\\\/Documents\\\/Programming\\\/master\\\/lib\\\/base.php(856): OC\\\\Route\\\\Router->match('\\\/apps\\\/firstrunw...')\\n#11 \\\/Users\\\/lukasreschke\\\/Documents\\\/Programming\\\/master\\\/index.php(39): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/Users\\\/lukasreschke\\\/Documents\\\/Programming\\\/master\\\/lib\\\/private\\\/urlgenerator.php\",\"Line\":190}","level":3,"time":"2016-02-09T08:57:05+00:00"}
```

So we need to use the SVG there as well, since the PNG is gone. Let me adjust that. But yeah, log and browser console would have helped :wink:

**Comment by LukasReschke** [comment]
Also needs some CSS magic :speak_no_evil:

**Comment by LukasReschke** [comment]
Fix is at https://github.com/owncloud/firstrunwizard/pull/40
