### ISSUE TITLE
FTP mount keeps mounted after changing from login and password to global credentials.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#22204]
### Steps to reproduce

Having external storage app enabled as admin do (Global credentials are empty):
1. Mount FTP external storage using login and password.
2. Check it is correctly mounted.
3. Go back to admin page and change it to global credentials
### Expected behaviour

FTP folder is red and not mounted because global credentials were not provided.
### Actual behaviour

FTP folder is still mounted.
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Master branch
{"installed":true,"maintenance":false,"version":"9.0.0.10","versionstring":"9.0 pre alpha","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes, FTP.

**Are you using encryption:** 
No

**Logs**

```
```
### Client configuration

**browser**
Chrome

**Comment by PVince81** [comment]
Still an issue with 9.0.6 RC1 or 9.1.2 RC1 ?

**Comment by SergioBertolinSG** [comment]
Still happening in 9.1.2RC1.

**Comment by PVince81** [comment]
If still happening in 10.0.4 and only with FTP, raise in https://github.com/owncloud/files_external_ftp
