### ISSUE TITLE
Federated share doesn't produce status icon any more

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#22215]
### Steps

1. Create a federated share
1. Refresh the page

### Expected result
The share icon in the file list row appears as shared

### Actual result
The share icon appears as unshared until the share panel is opened.

### Versions
9.0 master a35d5625e0ff3e50ab18b4079c630837e8322ffd

Note: if you upgrade from v8.2.2 with an existing fed share, the icon indicator will still be correct, so possibly something related to the new formats ?

@rullzer @schiesbn

**Comment by rullzer** [comment]
Yeah already got it... PR incomming

**Comment by rullzer** [comment]
PR IN #22217
