### ISSUE TITLE
Searching file in IE does not scroll when clicking on a result

### ISSUE THREAD

**Issue by Pookay** [owncloud/core#22210]
Hello,
using owncloud 8.2.2 on centOS 6.6 and testing on IE11

When I search files (in my external storage) and find it in "search results in other folders", I click on it and :
- in Chrome or Firefox : I get in the right folder scrolled at the right place (file on top)
- in IE11 : i get in the right folder but no scrolling.

I can't test this with edge

**Comment by PVince81** [comment]
Is this a follow up of https://github.com/owncloud/core/issues/21898 ?

**Comment by Pookay** [comment]
I think it is an other bug. Related with IE, searching files and design too.

**Comment by PVince81** [comment]
Is this still happening with 8.2.8 or 9.0.5 ?
