### ISSUE TITLE
Update fails when not on the main URL

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#22226]
1. Find a way to be behind *master*
1. Load an app like Gallery
1. Do a `git pull --rebase` of core
1. Refresh the browser window

At this stage, you're presented with the update page

1. Click update

It fails

1. Modify the URL so that it only goes to the root folder
1. Click update

It now succeeds.

So, the updater should never run from an app. It should be smart enough to detect that it's not the root URL and redirect the user.

**Comment by DeepDiver1975** [comment]
Works for me here.

Was that an app update or an update of core itself?

**Comment by oparoz** [comment]
I updated core and a couple of apps, but not the app I was on (Gallery). The update wouldn't work until I realised I was on the Gallery URL and switched.

**Comment by DeepDiver1975** [comment]
My browser was pointing to the gallery as well.
Next I incremented the version in version.php to force an upgrade
After refreshing the browser the upgrade was executed without issues .....

**Comment by oparoz** [comment]
Just tested various scenarios again and I can't reproduce, so I'm closing this until and if it happens again.
