### ISSUE TITLE
Regression in trashbin entry in sidebar

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#22235]
![bildschirmfoto 2016-02-09 um 11 39 40](https://cloud.githubusercontent.com/assets/245432/12913945/f4adb7e6-cf21-11e5-9fc1-5f8dc8565838.png)

cc @owncloud/designers

**Comment by MorrisJobke** [comment]
There is too much space between "Settings" and "Trashbin"

**Comment by PVince81** [comment]
@MorrisJobke works for me on master d11179a0f5b69ae479c214033a1ffc8d64752c83 in Chromium and Firefox.

Did you disable any apps ?

**Comment by jancborchardt** [comment]
Could this be the cause? https://github.com/owncloud/core/pull/22232

**Comment by MorrisJobke** [comment]
> Could this be the cause? #22232

I reverted it and it still didn't work. Currently other stuff on my list that is more critical. I will retry later

**Comment by jancborchardt** [comment]
@MorrisJobke I can’t reproduce this. Any more info, any specific other app enabled? Otherwise I would close it.

cc @owncloud/designers

**Comment by MorrisJobke** [comment]
Same here - works.
