### ISSUE TITLE
Theming issues

### ISSUE THREAD

**Issue by ITfee** [owncloud/core#22237]
I've tried to build a custom theme with inverse colors, e.g. I choose yellow as background color and it's not completely possible to adjust everything, for example
```
.icon-caret {
	background-image: url('../img/actions/caret-dark.svg');
}
```
just affects the left caret, but not the right beneath the user name. To see at last something I did this workaround:
```
#expand img {
	background: #000;
}
```
Changing the search field is also a bit tricky and it's also not possible to change the color of the remember login container.

The example theme in the directory seems also to be outdated...

**Comment by LukasReschke** [comment]
This is the bug tracker only used for bugs, for help regarding theming and other stuff please look at other available resources at https://owncloud.org/support/

**Comment by ITfee** [comment]
I don't need support theming my owncloud, but since the last update from 8.1.3. to 8.2.2 it simply doesn't work anymore due to changes in the core files, that obviously doesn't refer to the included example theme.
