### ISSUE TITLE
Don't emit 'post_create' hook for default files

### ISSUE THREAD

**Issue by musaa32** [owncloud/core#22236]
I have the **Version 8.2.2.2** and there is an isssue with hooks. I have developed an app that works with the _Filesystem_  Hooks e.g. 'post_create'. The problem is if I create a new user, the default files are created into the users directory, but the hook is also works for this files. How can I detect the default files(skeleton) in my app. My proposed solution would be to disable the _Filesystem_ Hooks for default files.

## Server configuration

Operating system: Fedora
Web server: nginx/1.6.3
Database: 10.0.21-MariaDB 
PHP-Version: 5.6.15
ownCloud version: 8.2.2.

**Comment by LukasReschke** [comment]
From my point of view that is expected behaviour as developers might require that hook as well for the initial setup.

**Comment by nickvergessen** [comment]
well there are apps which need these hooks also on skeleton files, so not sure
