### ISSUE TITLE
[federation] Cannot add new oC servers in the admin page

### ISSUE THREAD

**Issue by davitol** [owncloud/core#22239]
### Steps to reproduce

1. Enable federation app.
2. In Admin menu, click on +Add owncloud Server button
3. Write down a oC server URL

### Expected behaviour

The server should be detected and added

### Actual behaviour

The  oC server url is not recognized

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** ownCloud Enterprise Edition 9.0 pre alpha (daily) Build:2016-02-09T04:14:39+00:00 850ac0cf84f2492b16204b811f58a0dc7dc43b6e

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No

**Logs**

```
{"reqId":"Y2gswiUnBD+0K0Plyp6E","remoteAddr":"82.159.139.58","app":"federation","message":"No ownCloud server found","level":3,"time":"2016-02-09T12:08:45+00:00"}

```

### Client configuration

**browser**
Firefox

![screen shot 2016-02-09 at 11 25 07](https://cloud.githubusercontent.com/assets/10596560/12915914/b6ed78da-cf2e-11e5-9cf4-bc6f5416308f.png)

**Comment by davitol** [comment]
@schiesbn maybe?

**Comment by DeepDiver1975** [comment]
The remote server has to be version 9 or higher.

We should adjust the error messages.
