### ISSUE TITLE
System tags / global tags, how to make it clear ?

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#22233]
When tagging files in the sidebar, it isn't clear to the user that these tags are system-wide.

Wording suggestions: "public tags", "system tags", "global tags" (CC @MTRichards)

Some suggestions:
1. Add a label on top of the label: "Public tags:"
or
1. Add a small hint inside the dropdown at the top, of the box "Note: these tags are visible for all users".

@jancborchardt @karlitschek what do you think ?

**Comment by nickvergessen** [comment]
subscribing for wording in activity and admin_audit

**Comment by karlitschek** [comment]
Hmm. "public tags", "system tags" and "global tags" would all work for me. @MTRichards @jancborchardt What do you think?

**Comment by PVince81** [comment]
also important for documentation @carlaschroder

**Comment by MTRichards** [comment]
It should be "system tags" for the hidden ones, only the system can see or maniupulate them.

Then there are tags which users can see. In general there are three types of user tags: global, public and private. We don't have private tags yet.

But I do like calling them global (the ones users see but cannot edit) and Public (tags that are user viewable and editable)

**Comment by PVince81** [comment]
I was more hoping for a term that encompasses them all.

Technically, the hidden tags can still be seen by all admins, which make them semi-public (for admins). Public as opposite to "personal tags" or "private tags".

The purpose of the term should be to make sure users (and admins) understand that the tags are not only for themselves.

In the sidebar GUI, the user can see both "visible" and "not assignable" tags within the same field, so it would be good to have a term for that. "Global tags" might do like you said.

**Comment by PVince81** [comment]
It would be bad if someone started to tag their own stuff "this crappy stuff" believing that it's only for them, and then other people saw this tag in the dropdown :wink:

**Comment by jancborchardt** [comment]
I would prefer »Global tags« because »Public« sounds like it is visible to anyone and everyone (even people not on the ownCloud).

**Comment by nickvergessen** [comment]
which they are, if you federate-shared the file, right @PVince81 ?

**Comment by karlitschek** [comment]
good point

**Comment by MTRichards** [comment]
Public suggests something anyone can use, change, etc. This is what they are.

Private tags we don't have yet, so that would be later.

Which leaves the other tags that people can see but not edit. 

So @PVince81 you are looking for a name for the sidebar where tags show up, which would show public and global tags by my definition?

I would use Public tags. People understand that means something others will see. Global is more technical, not all office users will understand that language.

**Comment by jancborchardt** [comment]
Ok, I’m fine either way.

**Comment by PVince81** [comment]
Do we all agree on "Public tags" before we start changing the wording everywhere in the code and documentation ? @karlitschek @MTRichards @cmonteroluque

**Comment by nickvergessen** [comment]
"Invisible totally-hidden and inaccessible" type for a Public tags makes no sense to me.

**Comment by karlitschek** [comment]
works for me too

@nickvergessen i don't get what you mean :-)

**Comment by nickvergessen** [comment]
Well we have <..> tags that are invisible to users (e.g. for retention, etc.) those tags would be called "invisible public tags", which seems invalid to me, which is why I would prefer system or global. Public does simply not apply to all use cases of those tags...

**Comment by MTRichards** [comment]
I thought those were system tags. Public tags were the visible ones...

-- 
Matt Richards
VP Products & Markets 
ownCloud, inc.

**Comment by nickvergessen** [comment]
We need one word to rule them all.

**Comment by cmonteroluque** [comment]
I like @MTRichards proposal

**Comment by karlitschek** [comment]
Discussed again with Matt
I agree too with @MTRichards 

But I think in places like the left side bar we can just call it 'Tags' because a distinction between the different tag types is not necessary in this context.

And I understand that this doesn't solve the original request from @PVince81 but I don't think it is a huge problem. I would prefer to have a shorter name as 'Tags' in the left side bar instead of the more clunky name 'system tags'.

does this make sense?

**Comment by PVince81** [comment]
I'm fine with "Tags", but then make sure to add a hint in the tagging field of the sidebar to make sure people know that these are visible for everybody.

**Comment by PVince81** [comment]
@jancborchardt can you come up with some suggestions how to do this ? See https://github.com/owncloud/core/issues/22233#issuecomment-185110596

**Comment by jancborchardt** [comment]
@PVince81 talked with @karlitschek about this again. These tags are only visible when a tagged file is shared though, right? And I think then it can be expected that the tag belonging to the file is also visible to other people.

**Comment by PVince81** [comment]
That's not 100% correct. If "user1" tags a private file with a tag "mystuff", then "user2" will also see "mystuff" in their tagging dropdown.
The tags are a global list, so the dropdown picks it from there.

**Comment by PVince81** [comment]
Had a chat with @jancborchardt and @karlitschek and here is what we're going to do:
- rename "system tags" to "collaborative tags" in the UI (community part)
    - change placeholder of the dropdown on the top right
    - rename the app to "Collaborative Tags"
    - add a note in the app's description that providers should disable the app because the tags are visible for all users

**Comment by jancborchardt** [comment]
Yep – just a small thing, the app name should be »Collaborative tags«. We only capitalize the first letter. :)

**Comment by PVince81** [comment]
@jancborchardt will you take care of this ? Or should I ?

**Comment by jancborchardt** [comment]
Yeah, I’ll do this.
