### ISSUE TITLE
Tweak design for filtering files by global tags

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#22240]
Current state:
![systemtags-filter-gui2](https://cloud.githubusercontent.com/assets/277525/12912991/60ccd4bc-cf1c-11e5-9340-39b487cd2d78.png)
- better icon ?
- improve styling of filter box
- wording ?

@jancborchardt @owncloud/designers

**Comment by PVince81** [comment]
Ref wording discussion https://github.com/owncloud/core/issues/22233

**Comment by SergioBertolinSG** [comment]
The filtering box, when having two rows covers the name label.

![screen shot 2016-02-12 at 14 59 27](https://cloud.githubusercontent.com/assets/9048796/13008888/93243a5c-d199-11e5-99be-9be112333f45.png)

**Comment by jancborchardt** [comment]
@PVince81 instead of having an empty view directly when you click the »Tags« entry in the sidebar, how about below that entry there’s a select2 dropdown? (That works even better when Tags is the last entry in the list.) Then as soon as you select a tag, the list gets filtered down.

Or would that be an entirely different view?

**Comment by PVince81** [comment]
@jancborchardt do you mean that instead of requiring the user to type in something, open the dropdown directly with a list of all tags for easier selection ?

**Comment by jancborchardt** [comment]
@PVince81 basically yes. We could sort the tags by most used, and directly expand the top 5 when clicking on »Tags« in the sidebar. Of course also a search box on top and a means at the bottom to list the rest, but that would already make the flow a lot easier.

**Comment by aspdye** [comment]
I noticed that the tag icon in the Sidebar is brighter than the other icons.

**Comment by PVince81** [comment]
@felixheidecke
