### ISSUE TITLE
Remove new updater from 9.0 release RPM/DEB packages

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#22257]
As soon as the 9.0 tarballs are ready, we need to make sure to adjust the spec files for RPM/DEB package to not include the new "updater" folder that will appear in the tarballs.

@jnweiger @cmonteroluque @karlitschek 

CC @carlaschroder @VicDeo @DeepDiver1975

**Comment by PVince81** [comment]
Also there's a new app that does the update notification thing, needs to be removed too.

So basically, remove those at packaging time:
- [ ] "updater"
- [ ] "apps/updatenotification"

CC @LukasReschke

**Comment by karlitschek** [comment]
@deepdiver1975 can you please also doublecheck if this is correct for all usecases and scenarios? i think it is

**Comment by PVince81** [comment]
Hmm, removing these apps from the packages will likely mess with integrity check, see https://github.com/owncloud/core/issues/22151

So maybe the app codes can stay but they somehow need to be disabled by default ?

**Comment by jnweiger** [comment]
updatenotification/appinfo/app.php stats with 
if(\OC::$server->getConfig()->getSystemValue('updatechecker', true) === true)

can this be used to disable the apdatenotification app?

**Comment by LukasReschke** [comment]
> can this be used to disable the apdatenotification app?

That would work.

> sed -i -e 's@default_enable@default_disable@' $(DROOT)/$(OC_DIR)/apps/updatenotification/appinfo/info.xml

That won't work. The app is cryptographically signed and this would invalidate the signature.

Personally I'd be kind of a big fan disabling the updatenotification app using OCC in a packaging script. We could probably also keep the /updater/ folder then since it simply won't do anything. (unless an admin bothers to configure the required shared secret manually)

@karlitschek @DeepDiver1975 Any preferences?

**Comment by karlitschek** [comment]
let's not mess with the code please. We do a config file switch to disable the notification that we set with a config override file which we ship with the linux packages. Does this work @LukasReschke ?

**Comment by LukasReschke** [comment]
That will work. @jnweiger please set `updatechecker` to `false` in an override config like we have with ee.config.php.

I'll make sure that this will be respected properly in core.

**Comment by jnweiger** [comment]
Config file override is a good solution. Great to know that this is sufficient! 

Did not know about app signing. The sed trick worked quite well in the appliance.

**Comment by LukasReschke** [comment]
> Did not know about app signing. The sed trick worked quite well in the appliance.

Introduced with 9.0. Any manual changes on ownCloud files except the config file will result in an error :speak_no_evil:

**Comment by jnweiger** [comment]
Added disable-updatechecker.config.php to
https://obs.int.owncloud.com/package/show/ce:9.0:testing/owncloud-files
Thanks @LukasReschke for clearing this.

**Comment by jnweiger** [comment]
@LukasReschke testing the beta2 Ubuntu:14.04 package from https://obs.int.owncloud.com/package/show/ce:9.0:testing/owncloud-files
shows, that the disable-updatechecker.config.php got merged into config.php
My $CONFIG contains 'updatechecker' => false,

Still there is  

Update notification 0.1.0 listed as enabled in the Apps view.

**Comment by LukasReschke** [comment]
> Update notification 0.1.0 listed as enabled in the Apps view.

Yes. The app will be marked as enabled but it won't do anything basically. Not much we can do here from my PoV. Adding a hack to core for this seems odd.

**Comment by jnweiger** [comment]
Okay. If that is correct behavoiur, let's close here. Thanks.
