### ISSUE TITLE
Multiple quota API

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#22254]
- having a user user1
- user1 has a quota of 1 GB
- user1 upload 250 MB to it's ownCloud
- admins adds an external storage for user1
- external storage contains 25 GB of data and has 75 GB of free space
### how the clients handle this:
- client doesn't know anything about the mount points
- client sees a free space of 750 MB
- client sees a usage of 25,25 GB 
- client shows 25,25 GB of 26 GB are in use (because "25,25 GB of 1GB are in use" wouldn't make sense and "250 MB of 1GB are in use" would be really weird when you just synced 25 GB)
### how the web ui handles this:
- web UI shows 250 MB of 1 GB used

ref https://github.com/owncloud/client/issues/3652

Now the user is :confused: 

Proposal by @butonic: Allow the client to see all possible "mount points" (shares, external storages, ...) and how their used/free ratio is. Then the client and the web UI could use this as common knowledge and show the same values instead of applying some magic to calculate a useful value.

cc @karlitschek @MTRichards @DeepDiver1975 @icewind1991 Does this make sense?

**Comment by PVince81** [comment]
- need to make sure the client knows which mount points exist so it can query the quota on them
- quota value already available on Webdav: "quota-available-bytes" property, given that the underlying storage supports it
- improve ext storage backends to return the correct free space value, if supported at all

**Comment by DeepDiver1975** [comment]
No matter who we calculate these values - there has to be ONE code path exposing the information and all clients have to use that one.

**Comment by butonic** [comment]
* we might also expose other constraints like maximum file size or utf8 encoding constraints depening on the external storage mount point

**Comment by DeepDiver1975** [comment]
> we might also expose other constraints like maximum file size or utf8 encoding constraints depening on the external storage mount point

this was already discussed in the past in the area of giving the server the capability to express such criteria for the client so that it can check before upload.

we explicitly decided against this approach because you cannot express all crazy combinations of regulations a storage can have on files.

we did walk the path of letting the server perform storage specific checks and throw back an error in case criteria don't match

**Comment by butonic** [comment]
related https://github.com/owncloud/core/issues/23406

**Comment by butonic** [comment]
pinging @MTRichards and @cmonteroluque for a target milestone

**Comment by cmonteroluque** [comment]
@butonic 9.1 seems ok

**Comment by PVince81** [comment]
Moving enhancement to 9.2 since we're past feature freeze

**Comment by PVince81** [comment]
Backlog ? @pmaier1 @felixboehm @butonic

**Comment by pmaier1** [comment]
Should probably be part of a larger user management rework. Postpone if nobody disagrees for now.
