### ISSUE TITLE
Personal page elements are not correctly distibuted for LDAP users.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#22272]
### Observed behaviour

There is a lack of order in the LDAP users personal page:

<img width="992" alt="screen shot 2016-02-10 at 13 25 25" src="https://cloud.githubusercontent.com/assets/9048796/12947216/22f9f032-cffa-11e5-8008-9d785e825d67.png">

While regular users have elements correctly ordered:

<img width="1008" alt="screen shot 2016-02-10 at 13 25 13" src="https://cloud.githubusercontent.com/assets/9048796/12947233/3c9bfc38-cffa-11e5-8fb2-2532d63399cc.png">

Observed in current master 9.0.10 pre alpha using Chrome.

**Comment by SergioBertolinSG** [comment]
cc @owncloud/designers

**Comment by jancborchardt** [comment]
Is there an installation where you can give me the credentials to so I can test and fix this? I don’t have LDAP.

**Comment by SergioBertolinSG** [comment]
Apparently part of this layout is fixed already, but there are still some problems yet:

![screen shot 2016-02-29 at 12 44 38](https://cloud.githubusercontent.com/assets/9048796/13393535/51098676-dee2-11e5-805d-f1d3f5e3e4d7.png)

**Comment by jancborchardt** [comment]
Fix at https://github.com/owncloud/core/pull/22722

Haha, that’s a funny coincidence – issue #22272, fix pr #22722 ;) let’s drink on that numerology.

**Comment by MorrisJobke** [comment]
> Haha, that’s a funny coincidence – issue #22272, fix pr #22722 ;) let’s drink on that numerology.

:beers:
