### ISSUE TITLE
LDAP Configuration, groups filter can not be changed

### ISSUE THREAD

**Issue by ejouvin** [owncloud/core#22278]
Hye.

Owncloud v 8.2.2

In under specific case, we can not change the group filter synchronization.
Go to the tab Groups.
Change group class
Select some groups

Click on "Modify query" in order to set it manually
Click again on "Modify query" to return to assisted configuration.
The group class is enabled but not the groups filter list.

But, we can close the window and return on it.

Regards

**Comment by PVince81** [comment]
@blizzz

**Comment by blizzz** [comment]
Can confirm,  same happens on users page.

**Comment by blizzz** [comment]
That was tough to debug, because race condition. Made my brain turn :see_no_evil: 

But, the fix is in https://github.com/owncloud/core/pull/22358 

Would be great if you could test @ejouvin
