### ISSUE TITLE
Federated sharing auto-complete need a better way to distinguish users

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#22277]
on auto complete in the share dialog we just show the display name, something like `John Doe (remote)` but if you have share the user list with many servers chance is high that there will be more than one "John Doe". Maybe we should show instead `John Doe (on owncloud.org)` so that you also know the server. @owncloud/designers what do you think?

**Comment by schiesbn** [comment]
set this to 9.0 because I think at least the second part of the issue should be fixed during the bug fixing phase

**Comment by PVince81** [comment]
I think that makes sense :smile:

**Comment by jancborchardt** [comment]
@schiesbn good call!
