### ISSUE TITLE
Link shares are not unique per user in the web UI

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#22275]
1. As user test1 share a folder with user2
2. As user test2 share the folder as link
3. As user test1 share the folder as link

### Expected
It should work

### Actual
Step 3 is only possible on OCS, because the web UI shows the link share of test2 already.

### Comment
I think it is actually nice, because it gives you a web view that can delete the link shares of others, but up to the feature maintainers

cc @rullzer

**Comment by rullzer** [comment]
Yeah so the webUI is not fit to handle this... because it only allows 1 link share. And you get weird behaviour when you add another user that shares by link.

I'll make sure the link only shows the link for the owner... and then we need to rethink how we display multiple links...

**Comment by PVince81** [comment]
Hmmm... right. So with flat shares the original sharer can also see all link shares ?

**Comment by rullzer** [comment]
yes, it is shares to their data...
