### ISSUE TITLE
Add setup check for X-OC-MTime and OC-ETag

### ISSUE THREAD

**Issue by ghost** [owncloud/core#22280]
> The client show the error message "Server does not support X-OC-MTime" if the HTTP reply does not have a header X-OC-MTime header with the value accepted. Make sure that the headers are not removed out of the HTTP traffic. 

from https://github.com/owncloud/core/issues/22268

Might be useful to add another check for the two headers `X-OC-MTime` and `OC-ETag` which might be stripped off on various environments.

_Edit_ Another ref: https://github.com/owncloud/client/issues/4452

**Comment by PVince81** [comment]
Hmmm... are these arbitrary headers that get stripped or does X-OC-Mtime have a special meaning ?
It would be bad to not be able to use custom headers (like the checksum one @rullzer) because some envs strip it.

@DeepDiver1975 @LukasReschke
