### ISSUE TITLE
Meta: Do a security check on the new apps

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#22287]
- [x] updater
- [x] files_video_player (https://github.com/owncloud/files_video_player/issues/28)
- [x] federatedfilesharing
- [x] updatenotification

Did I miss anything? Let me go through the release tarball later as well…

**Comment by nickvergessen** [comment]
videojs-sublime

**Comment by nickvergessen** [comment]
+ the ones that are new in the core repo
