### ISSUE TITLE
federated share auto complete shows wrong user

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#22284]
Steps to reproduce:

- setup two instances
- create on both instances a user with the same user name (let's say "user1")
- enable federation and make sure that the address books are synced
- try to share a file with user1

Expected behavior:

The auto-complete should show two user1, once the local one and once the user on the second server

Actual result:

At first it looks good, you see "user1" and "user1 (remote)" but if you share with "user1 (remote)" you see that it will be shared again with the local user1, just as a remote share

Looks like by removing duplicates we remove the exactly wrong user in this case... @DeepDiver1975 can you have a look at this?

**Comment by schiesbn** [comment]
I looked into it in more detail. The problem is that we don't have unique URIs in the oc_card table. The local user has the URI `Database:user1.vcf` and the user from the remote server also has the URI `Database:user1.vcf`.

Once we populate the properties table we use the first card-ID we found for the uri `Database:user1.vcf` which is the local user and so the property for `user1@remote` points to the local `user` in the properties table

**Comment by schiesbn** [comment]
@DeepDiver1975 can you try to make the URI unique? Maybe for syned address books the uri shouldn't start with `Database:` but with `<remote_address>:` ?

**Comment by schiesbn** [comment]
We should probably also make the `uri` column unique so that it can never happen that we add the same uri twice.

**Comment by schiesbn** [comment]
I voted this up to critical because we should really fix this before the release. Otherwise the users will have broken database entries and it will be much harder (or even impossible) to fix the bug and repair the broken database entries.

**Comment by PVince81** [comment]
Who can take care of this, @schiesbn @DeepDiver1975 @rullzer ?

**Comment by schiesbn** [comment]
as it seems to be a bug in the dav app and I don't know the other implications it would have to change it I would prefer if @DeepDiver1975 could have a look at it.

**Comment by DeepDiver1975** [comment]
I'll have a look ...

**Comment by DeepDiver1975** [comment]
Testing with current master I see

![bildschirmfoto von 2016-02-15 13-34-40](https://cloud.githubusercontent.com/assets/1005065/13048839/ee6c8d5a-d3e8-11e5-8464-bfa5d15aaec9.png)

... there is something wrong in filtering the local remote address ...

**Comment by DeepDiver1975** [comment]
looks like the wrong cardid is stored in the card properties table

![bildschirmfoto von 2016-02-15 14-03-47](https://cloud.githubusercontent.com/assets/1005065/13049410/ff176ce8-d3ec-11e5-9314-f9d4ade03ad5.png)

**Comment by DeepDiver1975** [comment]
The problem is within the method getCardId which only take the uri as parameter - but the uri is only unique within one addressbook. The addressbook id has to be passed in as well ....
