### ISSUE TITLE
Meta: Do a security check on the new APIs

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#22282]
- [x] CalDAV
- [x] CardDAV
- [x] WebDAV
- [x] Comments (https://github.com/owncloud/core/issues/22367)
- [x] Tags (https://github.com/owncloud/core/pull/22536)
- [x] Federation
- [x] Sharing rewrite
- [x] Updater 
- …

Any other API that I missed? If so: Listing welcome :) I'll try to go through all new files as well but that would certainly save some time.

**Comment by LukasReschke** [comment]
@karlitschek @DeepDiver1975 @PVince81 Anything that I missed?

**Comment by karlitschek** [comment]
i think this should be all. cool. thanks
