### ISSUE TITLE
Public webdav short URL does not work on Chrome

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#22296]
### Steps to reproduce

1. Make sure you're using ownCloud via a secure URL (SSL)
1. Share a folder containing images
1. Open the share in a new tab
1. Modify the URL so that it **does not contain index.php**
1. Click on an image

### Expected results

The image should be downloaded (because files_sharing can't load scripts from apps yet, so there is no slideshow)

### Actual results

On Firefox, I'm presented with a dialogue asking me if I want to log in using the username "fhlkjashf3432fusfhs", which is the token in the URL. Not a great UX, but at least it works.

On Chrome, I get a page containing

>This page contains the following errors:
error on line 1 at column 1: Encoding error
Below is a rendering of the page up to the first error.

The URL is `https://domain.com/public.php/webdav/test.jpg`. There is no token in the URL

----
@PVince81 @MorrisJobke @rullzer @LukasReschke

**Comment by PVince81** [comment]
Tested so far:

1. from the files app (not gallery), share a folder using the files app, with images inside.
1. Link is: http://localhost/owncloud/index.php/s/1gSlIVwnVItkQHh
1. Shorten the link to be http://localhost/owncloud/s/1gSlIVwnVItkQHh

So far it works fine.

I tried appending the picture name in both links, but it doesn't seem to work at all.

If I copy the link by right clicking on an image name, the link is the public webdav one including token.

@oparoz how does the link look like before the redirect (if any) with image name in it ?

This is on master 6b836325cf8b8087a0734574ce4d5d1f8ec8456d

**Comment by PVince81** [comment]
and Chromium Version 48.0.2564.82 (64-bit)

**Comment by PVince81** [comment]
Potential fix: https://github.com/owncloud/core/pull/22297

**Comment by oparoz** [comment]
OK, so I've pulled the latest code.
In Filelist mode, if I hover over the images, I can see links like this:
`https://domain.com/public.php/webdav/800px-Hamburg_City_Beach_Club.jpg`
but if I copy the link, then I get this
`https://rmCfVS2taMZjQl8@domain.com/public.php/webdav/800px-Hamburg_City_Beach_Club.jpg`

That's probably just cosmetic.

Looking at the dev panel, I see that the GET URL is the one with the token and I get a response 200, with an attachment disposition, a valid content-length and content-type.
Both the preview and response tabs contain the same binary data with a JFIF header.

Chrome is not able to understand what it gets as an image apparently...

Could you try using SSL?

**Comment by oparoz** [comment]
Just tried with a non-SSL url and it works...

**Comment by PVince81** [comment]
@oparoz this PR https://github.com/owncloud/core/pull/22297 reverts back to original URLs.

I have the feeling that this token as username thingy is causing too many issues, so let's revert it instead.

**Comment by oparoz** [comment]
A shame for video playback... ;(

**Comment by oparoz** [comment]
And yes, the fix works.

**Comment by PVince81** [comment]
In theory the video player could build that URL manually... but would likely experience similar issues.
