### ISSUE TITLE
Possibility of 'invisible' link shares

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#22295]
Discovered in https://github.com/owncloud/core/pull/22285

Since we have no way to display multiple link shares in the WebUI and we have the flat shares. There is the possibility of 'invisible' link shares.

Example:

1. user1 shares foo with group2
2. user2 (in group2) shares foo by link
3. user1 unshares from group2

In the webUI user1 won't see that his file is actually still shared by link.

**Comment by rullzer** [comment]
I have a solution in mind. It won't scale if all 10K members of group2 share a file by link. But in the more likely scenario that there are only a few. All should work out.

**Comment by rullzer** [comment]
Ok thinking more about this and I propose the following.

Since we still have the same database layout we can make link shares hierachcical. So:

1. user1 shares foo with user2
2. user2 shares foo by link

Now the link will have the share created in 1 as parent. Then when the parent is deleted we delete the share as well.

All the logic for this is still there as I did not have time to clean it up yet. (and deleting children does not hurt when there are no children).

@schiesbn lets discuss this tomorrow.

@PVince81 FYI

**Comment by schiesbn** [comment]
discussed ith with @rullzer on IRC and I agree with this approach.
