### ISSUE TITLE
Controls bar width is not being correctly calculated

### ISSUE THREAD

**Issue by vincchan** [owncloud/core#22301]
### Steps to reproduce
1. Have a long list of files
2. Non-native scrollbar is displayed
3. Control bar width will be programatically set
### Expected behaviour

Control bar should not overlap scrollbar
### Actual behaviour

Control bar overlaps scrollbar

<img width="245" alt="screen shot 2016-02-10 at 23 11 47" src="https://cloud.githubusercontent.com/assets/868272/12963927/9142133c-d04d-11e5-9175-bc1b554a958f.png">
### Client configuration

**Browser:** Chrome, Safari, Edge

**Operating system:** Mac OS X El Capitan 10.11.3, Windows 10

@owncloud/designers

**Comment by PVince81** [comment]
There is some magic code that tries to calculate (or guess?) the scrollbar width, see https://github.com/owncloud/core/blob/v8.2.2/core/js/js.js#L1649

It uses an invisible / out-of-screen container with a real scroll bar then measures the length.
Maybe the styling of that specific container isn't 100% accurate on Safari and results in a one pixel shift ?

**Comment by PVince81** [comment]
moved to general design / UX / styling issues group ticket: https://github.com/owncloud/core/issues/27578
