### ISSUE TITLE
9.0beta1 tarball includes a new app which cannot be enabled.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#22306]
### Observed behaviour

9.0beta1 tarball a new app is included called **VideoJS Sublime** (Marked as experimental).
When enabling it, it says "No app name specified".

cc @karlitschek @cmonteroluque

**Comment by DeepDiver1975** [comment]
Please reopen in here: https://github.com/owncloud/videojs-sublime/issues

**Comment by SergioBertolinSG** [comment]
here it is https://github.com/owncloud/videojs-sublime/issues/24
