### ISSUE TITLE
Exception when upgrading from 8.0.3.4 to 8.2.1.4

### ISSUE THREAD

**Issue by Spereicle** [owncloud/core#22300]
Looking for best way forward to restore ownCloud after update exception. Currently no access to GUI or login.

Our ownCloud is installed on a shared server and has been functioning very well for a year or more.

Attempted to update using the internal Update App (via Admin GUI) earlier today without success.

Message upon exit: 

> Preparing update
Set log level to debug - current level: "Warning"
Turned on maintenance mode
Exception: Updates between multiple major versions and downgrades are unsupported.
The update was unsuccessful. Please report this issue to the ownCloud community.

Current Status:
All URL's return 'ownCloud will be updated to version 8.2.1' splash screen.
Unable to login or access files. 

checked config.php:
  'version' => '8.0.3.4',
  'installed' => true,
  'maintenance' => false,
  'loglevel' => 2,

Screenshots attached
ownCloud.log attached

Is there a way of finding out more information on what is actually hanging the process?
What is the best way to troubleshoot the process?
What happens if I overwrite the current ownCloud system (not data) files with those (8.0.3.4) auto-backed up at the start of the update?

[owncloud Log_partial.txt](https://github.com/owncloud/core/files/125515/owncloud.Log_partial.txt)
[owncloud Log_partial.xlsx](https://github.com/owncloud/core/files/125516/owncloud.Log_partial.xlsx)

![current display page - screenshot](https://cloud.githubusercontent.com/assets/12239124/12961915/b390d2d0-cff7-11e5-8e6d-7a254d032d05.png)
![owncloud 8 2 1 exception on update - screenshot](https://cloud.githubusercontent.com/assets/12239124/12961914/b383da26-cff7-11e5-9afd-a7a57d42ee8d.png)

**Comment by LukasReschke** [comment]
You can't update from 8.0 to 8.2, update first to 8.1

**Comment by Oinosseus** [comment]
Hello,

I'm at the same point point. I triggered an auto update from 8.0 to 8.2 with the same result.

Now I downloaded the 8.1 version and unpack it on my webserver. I also copied my old config.php to the new 8.1 installation.
Unfortunately the same screen shows up again.

Do I also have to delete the data folder from the failed update trial? Or what has to be done to come back to a functional Installation?

Thx,
Thomas

**Comment by Spereicle** [comment]
Thanks for the timely reply Lukas. 

Thomas, here is how I was able to revert our install without loss of data:
IMPORTANT NOTE: our data files are stored outside the webserver and outside the ownCloud tree structure.

1. Make backups of the database, ownCloud system files, and file repository.
2. Copy the config.php out of the ownCloud tree structure, and make an offsite backup.
3. Copy the ownCloud install package of the version you were updating FROM to the appropriate webserver directory for install. (likely from [ownCloud data directory]/updater_backup/ directory). Note, choose the version you attempted to upgrade from and the one without the random string as this is the entire package.
4. Completely delete the current ownCloud directory tree and all files.
5. Reinstall the ownCloud directory tree and all files from the zipped package above.
6. Reinstall the config.php file.

I also did a roll back on the mySQL database, which may not have been required.

**Comment by Oinosseus** [comment]
Thank you for your answer.

But meanwhile I restored my backup. I recovered the owncloud-directory, the data-directory and the database. Fortunately I learned from the past and I make a complete backup before every owncloud update.

Now I will try to update to 8.1

Thx,
Thomas
