### ISSUE TITLE
user data removed (on clients) when server-side storage not available

### ISSUE THREAD

**Issue by umlaeute** [owncloud/core#22310]
### Steps to reproduce
1. put `ownload/data` on an NFS share
2. make NFS share fail (e.g. unmount the share; power down the NFS-server while the oc-server boots,...)
3. have the oc-clients automatically sync while the `owncloud/data` directory is empty.

### Expected behaviour
the server tell the clients that it is currently *out-of-order*.
the client should then stop synching and try again after some time (10 minutes).

### Actual behaviour
the server serves from the invalid (empty) `owncloud/data` directory.
the client syncs with the empty directory, removing all files previously synched.

### Server configuration
**Operating system**:

`Debian/jessie 8.3 (amd64)`

**Web server:**

`apache 2.4.10-10+deb8u4`

**Database:**

`PostgreSQL 9.4.5-0+deb8u`

**PHP version:**

`5.6.17+dfsg-0+deb8u`

**ownCloud version:** (see ownCloud admin page)

`7.0.4+dfsg-4~deb8u4`

**Updated from an older ownCloud or fresh install:**

updated

**Signing status (ownCloud 9.0 and above):**

n/a

**List of activated apps:**

- Enabled
 - activity
 - calendar
 - contacts
 - documents
 - files
 - files_pdfviewer
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - files_videoviewer
 - firstrunwizard
 - gallery
 - search_lucene
 - user_ldap
- Disabled:
 - admin_dependencies_chk
 - bookmarks
 - external
 - files_encryption
 - files_external
 - templateeditor
 - user_external
 - user_webdavauth

**The content of config/config.php:**

~~~
<?php
$CONFIG = array (
  'instanceid' => 'ocb6155c0dd2',
  'dbtype' => 'pgsql',
  'passwordsalt' => 'XXX',
  'datadirectory' => '/usr/share/owncloud/data',
  'version' => '7.0.4.2',
  'appstoreenabled' => false,
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/usr/share/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
  ),
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'XXX',
  'dbpassword' => 'XXX',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'forcessl' => true,
  'theme' => 'example',
  'loglevel' => '2',
  'name' => 'iemCloud',
  'title' => 'iemCloud',
  'maintenance' => false,
  'trusted_domains' => 
  array (
    0 => 'cloud.example.com',
    1 => 'cloud.local',
  ),
  'mail_from_address' => 'noc',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'example.com',
  'mail_smtphost' => 'mail.local',
  'mail_smtpport' => '25',
  'secret' => 'XXX',
);
~~~

**Are you using external storage, if yes which one:** local/smb/sftp/...

NFS

**Are you using encryption:**

yes (`https`)

the data itself is not encrypted on the storage.

**Are you using an external user-backend, if yes which one:**

LDAP

#### LDAP configuration (delete this part if not used)

~~~
+------------------------------+---------------------------------------------+
| Configuration                | s02                                         |
+------------------------------+---------------------------------------------+
| hasMemberOfFilterSupport     |                                             |
| hasPagedResultSupport        |                                             |
| homeFolderNamingRule         |                                             |
| lastJpegPhotoLookup          | 0                                           |
| ldapAgentName                |                                             |
| ldapAgentPassword            | ***                                         |
| ldapAttributesForGroupSearch |                                             |
| ldapAttributesForUserSearch  | cn;uid;gecos                                |
| ldapBackupHost               |                                             |
| ldapBackupPort               |                                             |
| ldapBase                     | o=Staff,o=organization,dc=example,dc=com    |
| ldapBaseGroups               | o=organization,dc=example,dc=com    |
| ldapBaseUsers                | ou=people,o=Staff,o=organization,dc=example,dc=com  |
| ldapCacheTTL                 | 600                                         |
| ldapConfigurationActive      | 1                                           |
| ldapEmailAttribute           | mail                                        |
| ldapExperiencedAdmin         | 1                                           |
| ldapExpertUUIDGroupAttr      |                                             |
| ldapExpertUUIDUserAttr       |                                             |
| ldapExpertUsernameAttr       |                                             |
| ldapGroupDisplayName         | cn                                          |
| ldapGroupFilter              |                                             |
| ldapGroupFilterGroups        |                                             |
| ldapGroupFilterMode          | 1                                           |
| ldapGroupFilterObjectclass   | posixGroup                                  |
| ldapGroupMemberAssocAttr     | uniqueMember                                |
| ldapHost                     | ldaps://ldap.example.com                  |
| ldapIgnoreNamingRules        |                                             |
| ldapLoginFilter              | (&(|(objectclass=inetOrgPerson))(uid=%uid)) |
| ldapLoginFilterAttributes    |                                             |
| ldapLoginFilterEmail         | 0                                           |
| ldapLoginFilterMode          | 1                                           |
| ldapLoginFilterUsername      | 1                                           |
| ldapNestedGroups             | 0                                           |
| ldapNoCase                   | 0                                           |
| ldapOverrideMainServer       | 0                                           |
| ldapPagingSize               | 500                                         |
| ldapPort                     | 636                                         |
| ldapQuotaAttribute           |                                             |
| ldapQuotaDefault             |                                             |
| ldapTLS                      | 0                                           |
| ldapUserDisplayName          | cn                                          |
| ldapUserFilter               | (|(objectclass=inetOrgPerson))              |
| ldapUserFilterGroups         |                                             |
| ldapUserFilterMode           | 1                                           |
| ldapUserFilterObjectclass    | inetOrgPerson                               |
| ldapUuidGroupAttribute       | auto                                        |
| ldapUuidUserAttribute        | auto                                        |
| turnOffCertCheck             | 0                                           |
+------------------------------+---------------------------------------------+
~~~

**Comment by PVince81** [comment]
The mounted data folder will contain a special file ".ocdata". Whenever the NFS mount become unavailable, ownCloud will detect that the "data" folder isn't the expected one because that file is missing.

From what I see the fix was already in OC 6: https://github.com/owncloud/core/pull/7732

Did you mount NFS directly on "owncloud/data" or on subdirectories of it ?

**Comment by umlaeute** [comment]
no, i don't mount subdirectories of `owncloud/data/`.

in fact, by now I NFS-mount the entire `owncloud/` folder (from a single share) and put the config-files there as well, so that the entire instance fails if NFS is not available.

i see that there *is* an `owncloud/data/.ocdata` file.
maybe I have somehow managed to *also* have this file on the local filesystem (cannot check right now as the server is in production and the local filesystem is shadowed by the NFS).

i also see that this file is empty.
maybe this file could include some hash about the filesystem characteristics (disk-uuid, inode,...) and if that hash was stored in the db, owncloud could check if it has the correct filesystem.

**Comment by PVince81** [comment]
Yeah, maybe you managed to somehow get that file on the non-mounted system. Let us know once you get a chance to look at it during maintenance.

The hash thing is an interesting idea.
I'll mark this ticket as enhancement then to look into making storage detection more robust.

**Comment by PVince81** [comment]
I wanted to add: the ".ocdata" file is always empty.

**Comment by MorrisJobke** [comment]
@umlaeute Could we ask you to upgrade to a more recent version of owncloud. You are using 7.0.4 which was released over 1 year ago. We fixed in the meantime many issues with regard to unavailable external services.

It's mostly the same as https://github.com/owncloud/core/issues/22313#issuecomment-183240646 and we are very sad that you have run into those issues :(

@karlitschek @DeepDiver1975 @LukasReschke I guess we need to discuss this with the debian guys to avoid additional data loss due to really old code bases.

@umlaeute I will close this issue here. Feel free to report back if an upgrade resolved the issue for you. Thanks

**Comment by umlaeute** [comment]
@PVince81 i can confirm that the `.ocdata` file was there.

is there also a file i could create to prevent a directory from being used?

e.g. if my owncloud-user (`www-data`) has write-access to the directory, there is little to prevent the volume from accidentally becoming an owncloud-owned directory.

i imagine something like `.ocNOdata` that would stop owncloud from using that directory (even if there was an `.ocdata` file)

**Comment by PVince81** [comment]
That file ".ocdata" should only be created when running the ownCloud installation, so I'm not sure why ownCloud would decide to recreate it inside the data folder when unmounted.

**Comment by umlaeute** [comment]
ah ok. than this is a non-problem.

(one possible use would involve filesystem backups - where you have backed up the `.ocdata` file but don't want this directory to become a oc-volume ever; but i'm just making this up and don't have a real-world use-case at hand (i think))

**Comment by PVince81** [comment]
I think I can imagine a scenario that maybe triggered this situation of yours.

Did you originally have all files inside the "data" folder and later on decided to make it an NFS mount ?
So you'd have copied all files with "mv data/* /mnt/thefuturenfsmount". And later on you mounted that NFS mount onto the old data folder ?
That `mv` command doesn't move hidden files like ".ocdata" :frowning:

**Comment by PVince81** [comment]
but then the NFS mount would be missing ".ocdata" and you'd get an error that the file is missing, and decide to manually create it ?

**Comment by umlaeute** [comment]
yes, i started out on a local filesystem, and moved to an NFS-share (for capacity reasons).

afair, i just `rsync`ed the filesystems (which would of course include the `.ocdata`).

in any case, i have now removed that offending `.ocdata` file from the local filesystem.

**Comment by MorrisJobke** [comment]
> in any case, i have now removed that offending .ocdata file from the local filesystem.

Ah ... this was the problem! It was still there. Good that this is fixed now.
