### ISSUE TITLE
A folder contained in an already shared folder with two groups appears twice for an user in these two groups.

### ISSUE THREAD

**Issue by zinks-** [owncloud/core#22312]
A variation of #9724 with subfolders

Let's assume these folders :

/FolderA/
/FolderA/FolderB

and two groups Group1 and Group2, who both include our user

### Steps to reproduce
1. Share FolderA with Group1
2. Share FolderB with Group2

### Expected behaviour
The user already has access to FolderB through the sharing of FolderA with Group1, so the second sharing should not show up

### Actual behaviour
the user has two copies of FolderB :
/FolderA/FolderB
/FolderB

### Server configuration
**Operating system**: CentOS 6

**Web server:** apache

**Database:** mysql 5.5

**PHP version:** 5.4

**ownCloud version:** 8.1.5

**Updated from an older ownCloud or fresh install:** upgrade

**Comment by PVince81** [comment]
Possible duplicate, I think I've seen this before.

@rullzer @schiesbn

**Comment by rullzer** [comment]
Yes and without a big performance penalty there is not much we can do about it.

To merge those two things we need to find out for each share if (one of) the parent folders is already shared with this user. And then for the folder merge the permissions.

**Comment by rullzer** [comment]
@PVince81 certianly not something we can fix for 9.0

**Comment by PVince81** [comment]
Closing in favor of other duplicate https://github.com/owncloud/core/issues/24575
