### ISSUE TITLE
Move "SQLite is used as database" to "Security & setup warnings"

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#22318]
With https://github.com/owncloud/core/pull/8827 the following note was introduced in oC7:

> SQLite is used as database. For larger installations we recommend to switch to a different database backend.
> Especially when using the desktop client for file syncing the use of SQLite is discouraged.

This is hidden down below at "Tips & tricks". As the experience has shown the stuff down there won't be read by users i'm suggesting to move it to "Security & setup warnings" and make it a (not read) warning like "No memory cache has been configured"

Especially with the always enabled, database based file locking in 8.2 the people should really switch to PostgreSQL / MySQL.

**Comment by RealRancor** [comment]
Especially with the always enabled, database based file locking in 8.2 the people should really switch to PostgreSQL / MySQL.

**Comment by PVince81** [comment]
@LukasReschke @karlitschek what do you think ?

**Comment by karlitschek** [comment]
We want to restructure and re-prioritize all out warning and hints and errors anyways for 9.1
so let's discuss it in a few weeks
