### ISSUE TITLE
Fatal error without mbstring module installed

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#22324]
>  <klaas> PHP Fatal error:  Cannot redeclare mb_convert_encoding() (previously declared in /home/kf/oC/master/core/3rdparty/symfony/polyfill-mbstring/bootstrap.php:19) in /home/kf/oC/master/core/3rdparty/patchwork/utf8/src/Patchwork/Utf8/Bootup/mbstring.php on line 23

cc @nickvergessen @dragotin

**Comment by nickvergessen** [comment]
https://github.com/tchwork/utf8/blob/1.2/src/Patchwork/Utf8/Bootup.php#L69
https://github.com/symfony/polyfill/blob/master/src/Mbstring/bootstrap.php#L14

Both check whether mb_strlen is defined and then define it themselves, so it seems those are loaded in parallel?!

**Comment by dragotin** [comment]
While we're over it: I got a lot of 
```
{"reqId":"2Rym\/fFbVTbbZYpIJ+ku","remoteAddr":"::1","app":"PHP","message":"You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead. at \/home\/kf\/oC\/master\/core\/3rdparty\/patchwork\/utf8\/src\/Patchwork\/Utf8\/Bootup\/intl.php#18","level":3,"time":"2016-02-11T13:41:55+00:00"}
```
in the owncloud.log. Got no warning on the admin page. Installing php5-intl fixed it.

**Comment by DeepDiver1975** [comment]
Looks like patchwork and polyfill don't like each other.

**Comment by DeepDiver1975** [comment]
> Got no warning on the admin page. Installing php5-intl fixed it.

should we add this?

**Comment by nickvergessen** [comment]
Maybe it's then time to adjust the docs:

https://doc.owncloud.org/server/9.0/admin_manual/installation/source_installation.html#prerequisites
> Recommended packages:
....
    PHP module intl (increases language translation performance and fixes sorting of non-ASCII characters)

**Comment by nickvergessen** [comment]
> Looks like patchwork and polyfill don't like each other.

As pointed out, both check for existance of the function (and btw both are from the same author, so not sure if it's about disliking :stuck_out_tongue_closed_eyes: )

About the log message, thats from patchwork, not sure we can do anything against it apart from installing what it recommends

**Comment by LukasReschke** [comment]
Let me look into this. I'm rather reluctant to add another hard dependency while it may be easy to fix the fact stays that our users sometimes are quite angry if they update from an older version and it won't work due to a new dependency…

**Comment by LukasReschke** [comment]
Potential patch is at https://github.com/owncloud/3rdparty/pull/249
