### ISSUE TITLE
Occ tool in 9.0beta1 tarball doesn't come with execution permissions.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#22321]
The command line tool occ comes with  -rw-r--r-- when the expected are -rwxr-xr-x.

**Comment by DeepDiver1975** [comment]
@cmonteroluque @karlitschek @LukasReschke issue with the release script?

**Comment by karlitschek** [comment]
I added the x permission to occ. Please not that file permissions are not always preserved depending on the package format and options and if you unpack it as root or normal user. This this doesn't always work

**Comment by DeepDiver1975** [comment]
> I added the x permission to occ

the x permission is set via git - did we loose it on checkout?
