### ISSUE TITLE
Mac OS Desktop client isn't syncing any files with server

### ISSUE THREAD

**Issue by dmkanter** [owncloud/core#22333]
for some reason, my server files are never synced to my desktop. I've installed OwnCloud MacOS desktop on 2 machines and both seem to exhibit the same behavior.

version: ownCloud-2.1.0.2944

**Comment by LukasReschke** [comment]
From https://github.com/owncloud/core/blob/master/CONTRIBUTING.md:

> ### Guidelines
> * Please search the existing issues first, it's likely that your issue was already reported or even fixed.
>   - Go to one of the repositories, click "issues" and type any word in the top search/command bar.
>   - You can also filter by appending e. g. "state:open" to the search string.
>   - More info on [search syntax within github](https://help.github.com/articles/searching-issues)
> * This repository ([core](https://github.com/owncloud/core/issues)) is *only* for issues within the ownCloud core code. This also includes the apps: > files, encryption, external storage, sharing, deleted files, versions, LDAP, and WebDAV Auth
> * __SECURITY__: Report any potential security bug to us via [our HackerOne page](https://hackerone.com/owncloud) or security@owncloud.com following our [> security policy](https://owncloud.org/security/) instead of filing an issue in our bug tracker
> * **The issues in other components should be reported in their respective repositories: **
>   - [Android client](https://github.com/owncloud/android/issues)
>   - [iOS client](https://github.com/owncloud/ios/issues)
>   - [**Desktop client**](https://github.com/owncloud/client/issues)
>   - [Documentation](https://github.com/owncloud/documentation/issues)
  - [ownCloud apps](https://github.com/owncloud/core/wiki/Maintainers#apps-repo)
> * **Report the issue using our template, it includes all the information we need to track down the issue.**
