### ISSUE TITLE
[Sharing] Writing down the complete name of a group, it is shown twice in the dropdown

### ISSUE THREAD

**Issue by davitol** [owncloud/core#22332]
### Steps to reproduce
1. In share dialog, write down the complete username
### Expected behaviour

The dropdown should show the group name
### Actual behaviour

The group name is shown twice
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 9.0 pre alpha (daily) Build:2016-02-10T04:14:42+00:00 53d57bffed38d5f0723df26f011b1876be9360f7

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no.
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Firefox for Mac OSX

![screen shot 2016-02-11 at 17 20 36](https://cloud.githubusercontent.com/assets/10596560/12982406/e96d190c-d0e4-11e5-8ea3-065d2f4cc298.png)

@rullzer

**Comment by rullzer** [comment]
Mmmm I can't reproduce this. Could you try with the latest version?

**Comment by PVince81** [comment]
Probably already fixed, the report was for an old 9.0 version.

Please reopen if still reproducible.
