### ISSUE TITLE
Can't download beta from https://owncloud.org/install/#testing-development

### ISSUE THREAD

**Issue by tflidd** [owncloud/core#22339]
There is no link to the announced beta version of OC 9.0 as an archive (*.zip or *.tar.gz)

**Comment by nickvergessen** [comment]
Take this for now:
http://download.owncloud.org/community/testing/owncloud-9.0beta1.zip
http://download.owncloud.org/community/testing/owncloud-9.0beta1.tar.bz2

**Comment by MorrisJobke** [comment]
cc @LukasReschke @karlitschek

**Comment by MorrisJobke** [comment]
also @jospoortvliet

**Comment by enoch85** [comment]
JFTR: The BETA VM contains the latest version. https://www.techandme.se/pre-configured-owncloud-installaton/

**Comment by jospoortvliet** [comment]
https://github.com/owncloud/owncloud.org/pull/864 fixes this.

I have only VERY SLOW internet connection in the evening. I will try to merge and deploy but if it doesn't work (couldn't even do git push this afternoon) anybody should feel free to help out :D
