### ISSUE TITLE
Shared calendar urls not working anymore after update

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#22346]
### Steps
1. Install 8.2.2
* Create a calendar test as user1
* Share calendar with user2
* In your caldav client of choice add: `remote.php/caldav/calendars/user2/test_shared_by_user1`
* Update to 9.0-beta1

### Expected
You can still access and sync the calendar

### Actual
404 - Not Found

### Info
`remote.php/dav/calendars/user2/test_shared_by_user1` (dav instead of caldav as first folder) works, but we want a smooth transition, so the old links should still work.

**Comment by RealRancor** [comment]
@nickvergessen Seems thats already tracked in https://github.com/owncloud/core/issues/21812

**Comment by nickvergessen** [comment]
right

**Comment by nickvergessen** [comment]
Reopening because the problem exists, but the linked issue got closed.
