### ISSUE TITLE
Make tags search case insensitive

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#22352]
Makes it easier to type tags and select existing ones.

I found it cumbersome to select my tags where I had the first letter uppercase but when searching I used lowercase.

CC @jancborchardt

**Comment by rullzer** [comment]
Yes noticed this as well...
PR on the way..

**Comment by jancborchardt** [comment]
Yep – search should always be case insensitive. In user mgmt and files search this is already the case. Thx @rullzer
