### ISSUE TITLE
Make OC.Files.Client.move() return the new etag as part of the answer

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#22359]
OC.Files.Client.move() currently only sends back the status after having tried to move a file, but I would find it useful to get the new etag a well so that clients don't have to make an extra request jut to get it or to reload the whole list of files because their cache is outdated.

@PVince81 @MorrisJobke @rullzer

**Comment by PVince81** [comment]
Hmm, not sure if this fits the Webdav spec.
I guess it might be possible to make the server's MOVE operation return the etag in a header.

Which etag do you mean, the one of the moved file or the containing folder ?

I have a similar case with Webdav upload in this PR https://github.com/owncloud/core/pull/21237 where I need to do a PROPFIND after each upload... not good.

**Comment by oparoz** [comment]
>I guess it might be possible to make the server's MOVE operation return the etag in a header.

That's what I was thinking

>Which etag do you mean, the one of the moved file or the containing folder?

If I move a file from folderA to folderB. I'd want the new etag for folderA, but ideally, I would get both, depending on the penalty associated with the retrieval of that information.
Anything which avoids scanning the folders again for nothing.

**Comment by PVince81** [comment]
So maybe two headers "Etag" and "Parent-etag"

**Comment by oparoz** [comment]
`origin-etag` & `destination-etag` ?
