### ISSUE TITLE
Problem with owncloud 8.2.2.2 settings/admin. Webserver gives up with error 500, internal error

### ISSUE THREAD

**Issue by noci2012** [owncloud/core#22361]
In the log file the next message shows:

{"reqId":"SSlG7PQWMQQIyvAMfmpN","remoteAddr":"127.0.0.1","app":"PHP","message":"Array to string conversion at \/var\/www\/oc\/htdocs\/lib\/private\/template\/functions.php#36","level":3,"time":"2016-02-13T01:04:13+00:00"}
{"reqId":"SSlG7PQWMQQIyvAMfmpN","remoteAddr":"127.0.0.1","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/oc\/htdocs\/lib\/private\/template\/resourcelocator.php#119","level":3,"time":"2016-02-13T01:04:13+00:00"}
{"reqId":"SSlG7PQWMQQIyvAMfmpN","remoteAddr":"127.0.0.1","app":"3rdparty","message":"Could not find resource file \"\/js\/chosen\/chosen.jquery.min.js\"","level":3,"time":"2016-02-13T01:04:13+00:00"}
{"reqId":"SSlG7PQWMQQIyvAMfmpN","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Exception\":\"RuntimeException\",\"Message\":\"The source file \\\"\\\/js\\\/chosen\\\/chosen.jquery.min.js\\\" does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/oc\\\/htdocs\\\/3rdparty\\\/kriswallsmith\\\/assetic\\\/src\\\/Assetic\\\/Asset\\\/BaseAsset.php(103): Assetic\\\\Asset\\\\FileAsset->load()\\n#1 \\\/var\\\/www\\\/oc\\\/htdocs\\\/3rdparty\\\/kriswallsmith\\\/assetic\\\/src\\\/Assetic\\\/Asset\\\/AssetCollection.php(151): Assetic\\\\Asset\\\\BaseAsset->dump(NULL)\\n#2 \\\/var\\\/www\\\/oc\\\/htdocs\\\/3rdparty\\\/kriswallsmith\\\/assetic\\\/src\\\/Assetic\\\/AssetWriter.php(68): Assetic\\\\Asset\\\\AssetCollection->dump()\\n#3 \\\/var\\\/www\\\/oc\\\/htdocs\\\/lib\\\/private\\\/templatelayout.php(236): Assetic\\\\AssetWriter->writeAsset(Object(Assetic\\\\Asset\\\\AssetCollection))\\n#4 \\\/var\\\/www\\\/oc\\\/htdocs\\\/lib\\\/private\\\/templatelayout.php(152): OC_TemplateLayout->generateAssets()\\n#5 \\\/var\\\/www\\\/oc\\\/htdocs\\\/lib\\\/private\\\/template.php(214): OC_TemplateLayout->__construct('user', 'settings')\\n#6 \\\/var\\\/www\\\/oc\\\/htdocs\\\/lib\\\/private\\\/template\\\/base.php(121): OC_Template->fetchPage()\\n#7 \\\/var\\\/www\\\/oc\\\/htdocs\\\/settings\\\/admin.php(236): OC\\\\Template\\\\Base->printPage()\\n#8 \\\/var\\\/www\\\/oc\\\/htdocs\\\/lib\\\/private\\\/route\\\/route.php(154) : runtime-created function(1): require_once('\\\/var\\\/www\\\/oc.bag...')\\n#9 [internal function]: __lambda_func(Array)\\n#10 \\\/var\\\/www\\\/oc\\\/htdocs\\\/lib\\\/private\\\/route\\\/router.php(291): call_user_func('\\\\x00lambda_94', Array)\\n#11 \\\/var\\\/www\\\/oc\\\/htdocs\\\/lib\\\/base.php(851): OC\\\\Route\\\\Router->match('\\\/settings\\\/admin')\\n#12 \\\/var\\\/www\\\/oc\\\/htdocs\\\/index.php(39): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/oc\\\/htdocs\\\/3rdparty\\\/kriswallsmith\\\/assetic\\\/src\\\/Assetic\\\/Asset\\\/FileAsset.php\",\"Line\":62}","level":3,"time":"2016-02-13T01:04:27+00:00"}
{"reqId":"SSlG7PQWMQQIyvAMfmpN","remoteAddr":"127.0.0.1","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/oc\/htdocs\/lib\/private\/template\/resourcelocator.php#119","level":3,"time":"2016-02-13T01:04:27+00:00"}
{"reqId":"SSlG7PQWMQQIyvAMfmpN","remoteAddr":"127.0.0.1","app":"3rdparty","message":"Could not find resource file \"\/js\/chosen\/chosen.jquery.min.js\"","level":3,"time":"2016-02-13T01:04:27+00:00"}
{"reqId":"SSlG7PQWMQQIyvAMfmpN","remoteAddr":"127.0.0.1","app":"core","message":"Exception: {\"Exception\":\"RuntimeException\",\"Message\":\"The source file \\\"\\\/js\\\/chosen\\\/chosen.jquery.min.js\\\" does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/oc\\\/htdocs\\\/3rdparty\\\/kriswallsmith\\\/assetic\\\/src\\\/Assetic\\\/Asset\\\/BaseAsset.php(103): Assetic\\\\Asset\\\\FileAsset->load()\\n#1 \\\/var\\\/www\\\/oc\\\/htdocs\\\/3rdparty\\\/kriswallsmith\\\/assetic\\\/src\\\/Assetic\\\/Asset\\\/AssetCollection.php(151): Assetic\\\\Asset\\\\BaseAsset->dump(NULL)\\n#2 \\\/var\\\/www\\\/oc\\\/htdocs\\\/3rdparty\\\/kriswallsmith\\\/assetic\\\/src\\\/Assetic\\\/AssetWriter.php(68): Assetic\\\\Asset\\\\AssetCollection->dump()\\n#3 \\\/var\\\/www\\\/oc\\\/htdocs\\\/lib\\\/private\\\/templatelayout.php(236): Assetic\\\\AssetWriter->writeAsset(Object(Assetic\\\\Asset\\\\AssetCollection))\\n#4 \\\/var\\\/www\\\/oc\\\/htdocs\\\/lib\\\/private\\\/templatelayout.php(152): OC_TemplateLayout->generateAssets()\\n#5 \\\/var\\\/www\\\/oc\\\/htdocs\\\/lib\\\/private\\\/template.php(214): OC_TemplateLayout->__construct('user', 'settings')\\n#6 \\\/var\\\/www\\\/oc\\\/htdocs\\\/lib\\\/private\\\/template\\\/base.php(121): OC_Template->fetchPage()\\n#7 \\\/var\\\/www\\\/oc\\\/htdocs\\\/settings\\\/admin.php(236): OC\\\\Template\\\\Base->printPage()\\n#8 \\\/var\\\/www\\\/oc\\\/htdocs\\\/lib\\\/private\\\/route\\\/route.php(154) : runtime-created function(1): require_once('\\\/var\\\/www\\\/oc.bag...')\\n#9 [internal function]: __lambda_func(Array)\\n#10 \\\/var\\\/www\\\/oc\\\/htdocs\\\/lib\\\/private\\\/route\\\/router.php(291): call_user_func('\\\\x00lambda_94', Array)\\n#11 \\\/var\\\/www\\\/oc\\\/htdocs\\\/lib\\\/base.php(851): OC\\\\Route\\\\Router->match('\\\/settings\\\/admin')\\n#12 \\\/var\\\/www\\\/oc\\\/htdocs\\\/index.php(39): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/oc\\\/htdocs\\\/3rdparty\\\/kriswallsmith\\\/assetic\\\/src\\\/Assetic\\\/Asset\\\/FileAsset.php\",\"Line\":62}","level":3,"time":"2016-02-13T01:04:41+00:00"}
{"reqId":"SSlG7PQWMQQIyvAMfmpN","remoteAddr":"127.0.0.1","app":"core","message":"Exception: {\"Exception\":\"RuntimeException\",\"Message\":\"The source file \\\"\\\/js\\\/chosen\\\/chosen.jquery.min.js\\\" does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/oc\\\/htdocs\\\/3rdparty\\\/kriswallsmith\\\/assetic\\\/src\\\/Assetic\\\/Asset\\\/BaseAsset.php(103): Assetic\\\\Asset\\\\FileAsset->load()\\n#1 \\\/var\\\/www\\\/oc\\\/htdocs\\\/3rdparty\\\/kriswallsmith\\\/assetic\\\/src\\\/Assetic\\\/Asset\\\/AssetCollection.php(151): Assetic\\\\Asset\\\\BaseAsset->dump(NULL)\\n#2 \\\/var\\\/www\\\/oc\\\/htdocs\\\/3rdparty\\\/kriswallsmith\\\/assetic\\\/src\\\/Assetic\\\/AssetWriter.php(68): Assetic\\\\Asset\\\\AssetCollection->dump()\\n#3 \\\/var\\\/www\\\/oc\\\/htdocs\\\/lib\\\/private\\\/templatelayout.php(236): Assetic\\\\AssetWriter->writeAsset(Object(Assetic\\\\Asset\\\\AssetCollection))\\n#4 \\\/var\\\/www\\\/oc\\\/htdocs\\\/lib\\\/private\\\/templatelayout.php(152): OC_TemplateLayout->generateAssets()\\n#5 \\\/var\\\/www\\\/oc\\\/htdocs\\\/lib\\\/private\\\/template.php(214): OC_TemplateLayout->__construct('error', '')\\n#6 \\\/var\\\/www\\\/oc\\\/htdocs\\\/lib\\\/private\\\/template\\\/base.php(121): OC_Template->fetchPage()\\n#7 \\\/var\\\/www\\\/oc\\\/htdocs\\\/lib\\\/private\\\/template.php(338): OC\\\\Template\\\\Base->printPage()\\n#8 \\\/var\\\/www\\\/oc\\\/htdocs\\\/index.php(55): OC_Template::printExceptionErrorPage(Object(RuntimeException))\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/oc\\\/htdocs\\\/3rdparty\\\/kriswallsmith\\\/assetic\\\/src\\\/Assetic\\\/Asset\\\/FileAsset.php\",\"Line\":62}","level":3,"time":"2016-02-13T01:04:41+00:00"}
firew

**Comment by RealRancor** [comment]
Hi,

looks like https://github.com/owncloud/core/issues/12095 and a not correctly done upgrade. Please follow the upgrade manuals and delete all files and folders in your /var/www/oc/htdocs except /data and /config. Afterwards extract the 8.2.2 archive into your install dir.

**Comment by noci2012** [comment]
OK, Shorty was to blame... Appearantly a half removed part of an old API was used.
/var/www/oc/htdocs/3rdparty/kriswallsmith   was missing some files.
