### ISSUE TITLE
Web install error owncloud on webserver

### ISSUE THREAD

**Issue by Vilor** [owncloud/core#22366]
Warning: rename(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /hsphere/local/home/unifon/mobinstal.net/MobCloud/setup-owncloud.php on line 158 Warning: rename(tmp-owncloud1455371079/owncloud,./owncloud): No such file or directory in /hsphere/local/home/unifon/mobinstal.net/MobCloud/setup-owncloud.php on line 158

Error

ownCloud is NOT installed
download of ownCloud source file failed.
SSL: certificate subject name '*.owncloud.com' does not match target host name 'download.owncloud.org'SSL: certificate subject name '*.owncloud.com' does not match target host name 'download.owncloud.org'

**Comment by LukasReschke** [comment]
Please fill out the issue template. https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by RealRancor** [comment]
Probably just that SSL/NSS buggy lib used for curl

**Comment by DeepDiver1975** [comment]
> Probably just that buggy OpenSSL/NSS lib used for curl here.

seems so -> closing for now
