### ISSUE TITLE
Security Check: Comments

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#22367]
- [ ] Missing CSRF checks.
 - [ ] https://github.com/owncloud/core/issues/22368
- [ ] …

**Comment by LukasReschke** [comment]
Mhm… figuring how to excecute the Behat test suite here in core so I can write tests for some stuff :speak_no_evil:

**Comment by MorrisJobke** [comment]
> Mhm… figuring how to excecute the Behat test suite here in core so I can write tests for some stuff

```
cd build/integration
./run.sh
```

**Comment by LukasReschke** [comment]
Thanks @MorrisJobke :rocket: 

There we go: https://github.com/owncloud/core/pull/22511
