### ISSUE TITLE
Problem instaling updates

### ISSUE THREAD

**Issue by Vilor** [owncloud/core#22362]
Updating ownCloud to version 8.2.1, this may take a while.

Preparing update
Set log level to debug - current level: "Debug"
Turned on maintenance mode
Exception: Updates between multiple major versions and downgrades are unsupported.
The update was unsuccessful. 

Please report this issue to the ownCloud community.

**Comment by MorrisJobke** [comment]
@vilor Please use the search on top of this repository before creating new issues. With that you will find plenty of duplicates describing your problem. See #21366, #21186, #20640, #19910, #20732, #20813, #20974, #20660 and a lot more.

Then see this FAQ how to correctly upgrade: https://forum.owncloud.org/viewtopic.php?f=17&t=32087
