### ISSUE TITLE
VM does not properly handle code signing and sets release channel to "daily"

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#22371]
This message absolutely makes sense in production, but is getting in the way when working with master, so please disable it when the instance is in debug mode.

#### Update

Old VMs were on the daily channel and so if someone update that code using git, file verification will fail.

**Comment by LukasReschke** [comment]
> This message absolutely makes sense in production, but is getting in the way when working with master, so please disable it when the instance is in debug mode.

Where do you see it? I don't happen to see that here.

**Comment by LukasReschke** [comment]
(as in: what have you checked out and done etc.)

**Comment by oparoz** [comment]
I'm using master, have not configured anything else. I expect the signatures not to be in the repository as I suppose they need to be generated before packaging.

**Comment by oparoz** [comment]
Some examples of fails which fail:

```
- files_sharing
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
- files_external
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
```

**Comment by LukasReschke** [comment]
Well. We all use master as well and it works here, so I rather need some more information on what you use ;-)

Aka config.php, checkout, which apps are installed, etc. ;-)

**Comment by LukasReschke** [comment]
In fact, the code check is already disabled for anything marked as `git` version :)

**Comment by LukasReschke** [comment]
What does  `OC_Util::getChannel();` return for you?

https://github.com/owncloud/core/blob/296519f44a3c0f1d34f6a67a7de33965d0edb9ef/lib/private/integritycheck/checker.php#L89-L98

**Comment by oparoz** [comment]
Channel is `daily`

**Comment by oparoz** [comment]
### config.php

```
<?php
$CONFIG = array (
  'trusted_domains' =>
  array (
    0 => 'localhost',
    1 => '10.0.2.15',
    2 => 'owncloud',
    3 => 'localhost',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'https://10.0.2.15/owncloud',
  'dbtype' => 'mysql',
  'version' => '9.0.0.11',
  'dbname' => 'oc',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin',
  'dbpassword' => 'password',
  'logtimezone' => 'UTC',
  'installed' => true,
  'loglevel' => 0,
  'theme' => '',
  'maintenance' => false,
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\JPEG',
    1 => 'OC\\Preview\\PNG',
    2 => 'OC\\Preview\\GIF',
    3 => 'OC\\Preview\\Postscript',
    4 => 'OC\\Preview\\Font',
  ),
  'preview_max_x' => 2048,
  'preview_max_y' => 2048,
  'debug' => true,
  'updatechecker' => 'false',
  'singleuser' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
);
```

**Comment by LukasReschke** [comment]
Daily? Where did you get that build from? They should be signed :speak_no_evil: 

Did you by any chance configure a channel in the updater app? If so try to delete that key and then rerun the code check in the admin menu: `\OC::$server->getAppConfig()->deleteKey('core', 'OC_Channel');`

**Comment by oparoz** [comment]
This is using the ownCloud VM.

**Comment by LukasReschke** [comment]
Then that is packaging related :)

@jnweiger @enoch85 FYI

**Comment by oparoz** [comment]
OK, so, some more info.

* Installed official VM of stable 8.1, ditched the folder and cloned master, which is regularly updated
* *Updater* app is disabled

so, if the signatures are supposed to be delivered via the updater, then I'm never getting them.

I'm guessing I should switch to a different channel in order to not get bugged by the messages any more, but which one?

**Comment by enoch85** [comment]
Noticed. Thanks.

**Comment by LukasReschke** [comment]
> so, if the signatures are supposed to be delivered via the updater, then I'm never getting them.

They are not supposed to be delivered by the updater. They are included within the zip file. But the VM seems not to bundle them and states to be a daily release which is supposed to be signed. :)

> I'm guessing I should switch to a different channel in order to not get bugged by the messages any more, but which one?

You need to remove that key. Or wait for @enoch85 to fix that  to include the signature as well such as https://download.owncloud.org/community/daily/owncloud-daily-master.tar.bz2 has :)

**Comment by oparoz** [comment]
>Or wait for @enoch85 to fix that to include the signature as well such as
OK, but let's say I download that daily, the next time I do a git pull, then all my signatures will be invalid again, so for devs, it's best to remove that key from the dev VM

**Comment by LukasReschke** [comment]
> OK, but let's say I download that daily, the next time I do a git pull, then all my signatures will be invalid again, so for devs, it's best to remove that key from the dev VM

Not if the VM would properly claim to be built from Git and sets the version to `git`. But if it claims to be daily. I'd just advocate that the VM sets the version to `git` if it really is built from Git :)

**Comment by oparoz** [comment]
Hmmm... I've deleted the OC_Channel key and it still says I'm on daily...

**Comment by oparoz** [comment]
And in version.php, I have:
```
// The ownCloud channel
$OC_Channel = 'git';
```

**Comment by LukasReschke** [comment]
@oparoz Delete all your sessions (or just clear the cookies). It's cached within there.

**Comment by oparoz** [comment]
I'm now on the git channel, but I still get the message and when I click on it I get

>Integrity checker has been disabled. Integrity cannot be verified.

**Comment by LukasReschke** [comment]
> I'm now on the git channel, but I still get the message and when I click on it I get

Try to click the rescan button in the admin interface :wink: Otherwise you will get the scanned results.

**Comment by oparoz** [comment]
OK, that worked, thanks. It's a bit of a pain though. I guess we have to pick our VM carefully from the start :)

**Comment by enoch85** [comment]
Ok guys @all, [this](https://github.com/enoch85/ownCloud-VM/blob/master/beta/dev/owncloud_install_testing.sh#L120-L139) is how I install the dev VM that is released on [Tech and Me](https://www.techandme.se/pre-configured-owncloud-installaton/). What should I change? AFAIK there are no key downloaded? What steps should I take to fix this issue?

**Comment by oparoz** [comment]
If I were you, I would substitute [this](https://github.com/enoch85/ownCloud-VM/blob/master/beta/dev/owncloud_install_testing.sh#L121-L123) with a `git clone` of *master* and siable the updater app.

**Comment by enoch85** [comment]
@oparoz Thanks for the idea. I will look into that tomorrow. And also update the [update script](https://github.com/enoch85/ownCloud-VM/blob/master/beta/dev/owncloud_update_testing.sh#L46) accordingly in that case.

**Comment by enoch85** [comment]
@oparoz What's your nick on IRC? Would want you to test [this](https://github.com/enoch85/ownCloud-VM/blob/master/beta/dev/owncloud_update_testing.sh) as it breaks my system. Is that what you mean bu git? Because I can't get it to work with git, maybe because master is failing?

**Comment by oparoz** [comment]
The same as on here, but I'm rarely there.
In the update script you simply need to pull, the cloning must happen in the install script.

**Comment by PVince81** [comment]
@enoch85 @LukasReschke I heard this should be fixed now, can you check ?

**Comment by enoch85** [comment]
Sorry, I can't tes right nowt, forgot my laptop this weekend in Stockholm.

**Comment by cmonteroluque** [comment]
@enoch85 any luck testing this today or tomorrow? We want to lock down this release by tomorrow. Many thanks for all your help!

**Comment by enoch85** [comment]
Oh, just missed it! I've been without my laptop for a while now, just got it back. @PVince81 Where is the merged fix? Please link.

**Comment by PVince81** [comment]
@enoch85 I'm not sure it's an actual fix in the code, possibly a fix in the packages themselves.

@LukasReschke ?

**Comment by PVince81** [comment]
@enoch85 any update ?

**Comment by enoch85** [comment]
Actually, I don't know what to look for? Maybe @jnweiger can help on this?

**Comment by enoch85** [comment]
@oparoz Have you tried the latest VM?

**Comment by jnweiger** [comment]
@I am no longer following. It is git pull but also packaging, it is signing something and also vm. 
so many contradictions. Where is a release channel seen?

**Comment by oparoz** [comment]
The main problem is that the dev VM needs to use the git channel. That disables code checking. So if that's done, then we're half way there.
The other half is about making sure that the standard VM uses daily, stable, etc., matching their download link. Code signing should automatically work there if the new files are downloaded from the ownCloud repos.
If that's also working as expected, then this can be closed.

**Comment by enoch85** [comment]
@oparoz I (Tech and Me) don't provide a dev VM anymore if that's what you mean? I will rewrite the bash code completely some day per our discussion on IRC some weeks ago, using git and with more loose permissions and such. 

I wasn't aware of that the official VM was existing as a dev VM as well?

**Comment by oparoz** [comment]
>I wasn't aware of that the official VM was existing as a dev VM as well?

It doesn't, I was referring to your work.
The remaining problem is purely process related then. If people want to start using git from an official VM in order to test different branches per example, then they need to make sure they switch to git first in the admin panel.

The problem is that we can't really document this because the official VM doesn't work as-is for development work, yet.

**Comment by enoch85** [comment]
Ok, so as I decided not to provide the dev VM anymore, then this isn't an issue. Right?

Per your request (or wish) I will make a new one when I find the time with your help (and/or @jnweiger) as I'm not a git pro, yet ;)

**Comment by oparoz** [comment]
>Per your request (or wish) I will make a new one when I find the time with your help (and/or @jnweiger) as I'm not a git pro, yet ;)

Something to do during a virtual hackaton :)

**Comment by enoch85** [comment]
@all Feel free to contribute as the code is on GitHub: https://github.com/enoch85/ownCloud-VM/tree/master/beta/dev
