### ISSUE TITLE
No update of nightly builds

### ISSUE THREAD

**Issue by tflidd** [owncloud/core#22374]
The nightly builds stopped again updating, the last version is from Feb 10:
https://download.owncloud.org/download/repositories/nightly/Debian_8.0/
@jnweiger

**Comment by jnweiger** [comment]
Added new subpackages for newly added apps.
This is a temporary fix to make it build with the old 8.x packaging code.
The new 9.0 packaging code will produce one package with all apps included.

**Comment by jnweiger** [comment]
@tflidd I just checked the Debian_8.0 target: Nightly did built again.

**Comment by tflidd** [comment]
Yes, now it is ok. This morning (and the days before) it wasn't. Packages*, Release*, and Sources* were updated, but owncloud_9.0~beta1.* wasn't.

**Comment by jnweiger** [comment]
Right. The build failed as the apps were rearrangned, and the packaging code was not updated to handle this. Sorry for this.

**Comment by tflidd** [comment]
Thank you. If everything worked perfect, testing would be quite boring :smile:

**Comment by tflidd** [comment]
@jnweiger : New problems ;-)
1) I can update the owncloud-package any more:
````
root@myhost:~# apt-cache policy owncloud
owncloud:
  Installed: 9.0~beta1.20160217
  Candidate: 9.0~beta1.20160217
  Version table:
 *** 9.0~beta1.20160217 0
        100 /var/lib/dpkg/status
     9.0~beta1-5.1 0
        999 https://download.owncloud.org/download/repositories/nightly/Debian_8.0/  Packages
````
apt doesn't update. So I removed owncloud, and reinstalled it, now I have `9.0~beta1-5.1 0`.

2) The version shown on the admin page `ownCloud 9.0 beta 1 (daily) Build:2016-02-17T04:42:01+00:00 c6b24573066cfc87b73b1b61b41032b8c5a406cf`
This build is older than beta2.

**Comment by PVince81** [comment]
@tflidd thought the server was fixed yesterday, can you check again ?

**Comment by PVince81** [comment]
CC @DeepDiver1975

**Comment by jnweiger** [comment]
I've done several fixes to the update scripts and pushed the latest rebuild to 

http://download.owncloud.org/download/repositories/nightly/owncloud/index.html
http://download.owncloud.org/download/repositories/nightly/owncloud-files/index.html

(all manual pushes, as rotor still has issues)

**Comment by tflidd** [comment]
I didn't try again after there was no response here. Just ran the upgrade, now I'm on OC 9.0.0 beta 2 83d5080e78fa481db3855da8fcd75f624f8cac1c
:+1: let's test the other issues

**Comment by jnweiger** [comment]
Nightly updated tonight, without any manual intervention. New packaging is in place. 

Can we close here?

**Comment by tflidd** [comment]
From my POV, it can be closed.

**Comment by jnweiger** [comment]
thnaks,

**Comment by tflidd** [comment]
It hangs again ;-( Last update was on Feb 25/26! @jnweiger 
https://download.owncloud.org/download/repositories/nightly/Debian_8.0/
