### ISSUE TITLE
Allow to define group for sharing setting "Restrict sharing to group members only"

### ISSUE THREAD

**Issue by rikmer** [owncloud/core#22382]
Didn't find a solution to allow only a certain group to share only in this group. This would be a great feature to control which users are allowed to share to the public and which are not.
In more detail:
I would like to be able to allow users from a group to share only in that group. But other users which are part of that group and another group to share to the public. E.g. user1 and user2 are members of the group group1. user2 is also member of the group group2. user1 can only share with user2 but user2 can also share with the public.

Or is there a way?
Using OC8.2.2.

**Comment by PVince81** [comment]
please try again with OC 10.0.9 or so, there are new sharing options in regards to group restrictions

it is likely that some combination will fit your scenario
