### ISSUE TITLE
Closing a picture in the tags view goes back to the picture location.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#22387]
### Steps to reproduce

1. Assign tag to a picture (png, jpg) inside a folder.
2. Go to the tags section, search the tag assigned in 1.
3. Open picture with slideshow.
4. Close slideshow.

### Expected behaviour
Closing slideshow comes back to the tag search view.

### Actual behaviour
Closing slideshow comes back to the files view where the picture is located.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Master branch
{"installed":true,"maintenance":false,"version":"9.0.0.11","versionstring":"9.0 beta 1","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No

**Logs**

```
```

### Client configuration

**browser**
Chrome

**Comment by PVince81** [comment]
Maybe the slideshow code doesn't only close the view but also redirects to the files view ?

@oparoz

**Comment by oparoz** [comment]
Correct @PVince81

**Comment by nickvergessen** [comment]
I guess this is a bug in the gallery app then?

**Comment by oparoz** [comment]
Yes. It's already logged.
