### ISSUE TITLE
Enabling an app via CLI, 'appname enabled' message should not be shown if the app was already enabled because it is redundant

### ISSUE THREAD

**Issue by davitol** [owncloud/core#22389]
### Steps to reproduce

1. Try to enable an app that was already enable via CLI (e.g. sudo -u www-data ./occ app:enable files_external)

### Expected behaviour

A message 'files_external is already enabled' should be shown

### Actual behaviour
It is shown two messages:
- files_external is already enabled
- files_external enabled

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 9.0 beta 1 (daily) Build:2016-02-15T04:14:27+00:00 ac367b97f0567481d3496a213c04eeb5cf654a9f

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** 

oC 9.0

![screen shot 2016-02-15 at 11 55 48](https://cloud.githubusercontent.com/assets/10596560/13046786/3cac8d16-d3db-11e5-9fe3-db20d986f166.png)

oC 8.2.2 (stable)

![screen shot 2016-02-15 at 11 56 34](https://cloud.githubusercontent.com/assets/10596560/13046783/38300dd0-d3db-11e5-9722-d6268cfbac07.png)

**Comment by nickvergessen** [comment]
Well we can only deduplicate it by removing the "is already enabled". That was not called for all cases anyway.
