### ISSUE TITLE
Give sub-admin rights to app maintainers

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#22396]
As the maintainer of an app which is part of the ownCloud domain, I'm missing some functionalities that I have access to when managing apps under domains in which I have admin rights, mainly hooks access to make it possible to integrate the repository with 3rd party services.

Would it be possible to create sub-admin groups, one for each app and add the maintainers of the app in that group? They wouldn't have admin rights over anything else.

This is the list of additional permissions, compared to collaborators with _write_ permission
- Delete repositories
- **Change a repository's settings**
- Change a repository's visibility  
- Transfer repositories into, and out of, the organization account
- Add a repository to a team
- Add outside collaborators to a repository

[Source](https://help.github.com/articles/repository-permission-levels-for-an-organization/)

@karlitschek @DeepDiver1975 @BernhardPosselt @georgehrke @nickvergessen

**Comment by karlitschek** [comment]
yes. this is a good idea. let me look into this

**Comment by oparoz** [comment]
Added the list of differences compared to the "write" permission.

**Comment by nickvergessen** [comment]
@karlitschek any update?

Or could you enable the wiki for https://github.com/owncloud/announcementcenter in the meantime, so I can document stuff a bit?

**Comment by karlitschek** [comment]
I think we should do this on a case by case level. I gave you admin rights for announcementcenter and @oparoz has admin rights for gallery. 
Please don't add external collaborators without coordinating with me. It is vital to keep licensing and CLAs under control.

**Comment by nickvergessen** [comment]
Thanks, and ACK

**Comment by nickvergessen** [comment]
Can I have permission for activity as well?

**Comment by oparoz** [comment]
Looks like I never said thanks, so thanks :). It's useful to be able to clean up scrutinizer reports and such.
