### ISSUE TITLE
Feature request: auto-add LDAP users to group(s)

### ISSUE THREAD

**Issue by labnuke** [owncloud/core#22395]
Not sure if this is correct spot as first time posting on github.

Is there a way to automatically add users (who are authenticating via LDAP) to existing groups in OC? I have an Everyone group that I want all users to be members of automatically to get served company content when first logging in.

thanks.

**Comment by nickvergessen** [comment]
Listen to `Util::connectHook('OC_User', 'post_login', ...` and add the users there

**Comment by PVince81** [comment]
Instead of just LDAP, the feature could be summarized as "have a list of default groups for any newly created or detected user (LDAP)"

**Comment by labnuke** [comment]
Note that I am unable to manually add LDAP users to any group.

**Comment by blizzz** [comment]
@labnuke 

> Note that I am unable to manually add LDAP users to any group.

Er, I rephrase: adding LDAP users to local groups does not work. Correct?

**Comment by labnuke** [comment]
correct

**Comment by blizzz** [comment]
> correct - specifically adding LDAP users to any Owncloud local groups.

@labnuke I cannot reproduce it, works like a charm (current master). I'd welcome if you could open a bug report about it.

**Comment by PVince81** [comment]
Please reopen in [user_ldap app repo](https://github.com/owncloud/user_ldap) if issue persists with 10.0.4 and the latest user_ldap app from marketplace.

You can likely use the provisioning API from outside for your use case.
