### ISSUE TITLE
Skip heartbeat calls if an ajax call was detected

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#22397]
The notifications app, when enabled, polls the server every 30 seconds.
The files app, when opened, calls "ajax/getstoragestats.php" every now and then.

This makes the heartbeat redundant.

Here is an idea: jQuery makes it possible to receive an event after every ajax call.
If such call is received, reset the heartbeat's interval.
This means that the heartbeat call would only ever be sent whenever there was no ajax call for the configured interval.

What do you think ?
@icewind1991 @DeepDiver1975 @karlitschek 

As discussed with @nickvergessen over lunch

**Comment by karlitschek** [comment]
good idea. the performance benefit with this change is probably tiny but why not

**Comment by nickvergessen** [comment]
well its one request less per user per tab per 30 secs...
