### ISSUE TITLE
Wrong error message in occ commands when the argument is invalid

### ISSUE THREAD

**Issue by davitol** [owncloud/core#22391]
### Steps to reproduce

1.  Run a occ command with a wrong argument

### Expected behaviour

A message 'InvalidArgumentException' should be shown

### Actual behaviour

[Symfony\Component\Console\Exception\CommandNotFoundException] message is shown 

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 9.0 beta 1 (daily) Build:2016-02-15T04:14:27+00:00 ac367b97f0567481d3496a213c04eeb5cf654a9f

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** 

oC 9.0

![screen shot 2016-02-15 at 12 01 09](https://cloud.githubusercontent.com/assets/10596560/13046924/edd8080e-d3db-11e5-9fc3-8eabc5b69603.png)

oC 8.2.2 (stable)

![screen shot 2016-02-15 at 12 01 36](https://cloud.githubusercontent.com/assets/10596560/13046918/e5ecb2b6-d3db-11e5-92a5-381a25af6cc4.png)

**Comment by DeepDiver1975** [comment]
Why should that be an issue?

**Comment by davitol** [comment]
I think the error message should not show the whole path.

@DeepDiver1975 If you consider it is not an issue or it is a waste of time to 'fix it' let's close it.

**Comment by DeepDiver1975** [comment]
> I think the error message should not show the whole path.

this is not a path but the php namespace - for sure a wont fix
