### ISSUE TITLE
Tagging plugin needs to be able in all views but trashbin.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#22393]
Currently tagging is only available in files view and favorites view.

It needs to be added to tags view and shares views as well.

Sharing view sidebar when opening a file:

![screen shot 2016-02-15 at 12 42 10](https://cloud.githubusercontent.com/assets/9048796/13047742/90f7fd82-d3e1-11e5-85fd-9df6835d2fb9.png)

Tags view sidebar when opening a file:

![screen shot 2016-02-15 at 12 42 38](https://cloud.githubusercontent.com/assets/9048796/13047768/bb50992c-d3e1-11e5-9413-725c13a38efb.png)

**Comment by SergioBertolinSG** [comment]
cc @PVince81

**Comment by PVince81** [comment]
Making this a bug because it's missing and I know I forgot to add it.
