### ISSUE TITLE
list users without group for easier group membership administration

### ISSUE THREAD

**Issue by crysman** [owncloud/core#22401]
Please, is there a way to **list (view) all owncloud user accounts which are not part of any group**? I use IMAP authentication and automated user creation. Whenever a new account is created, we must assign the new user to some groups, according to who it is. We have got quite a lot of users.

In actual implementation, it is very inconvenient to administrate them through web "Users" menu in top-right, because it uses some wierd async javascript and
1. It is very slow to scroll and wait all the way down through multiple iterations until you get to somebody on "Z" and
2. We would appreciate if we could just click on "no groups" virtual group where all users without group membership would be listed immediately - just like "administrators" for example.

If it's currently not possible, consider this a legitimate feature request. Thanks

**Comment by MorrisJobke** [comment]
cc @blizzz

**Comment by nickvergessen** [comment]
well getting all users with no group, basically means get all users and check if they have any group assigned... I don't think our user backends (have to) support this at the moment.

**Comment by crysman** [comment]
@nickvergessen Imagine you have aprx. 15 groups and 100 users, like we do.

1) Imagine a new user "zorro" is being created (automatically, through IMAP auth extension) and asks you to assign him to group Alpha and Beta. Imagine now you assign him - open the "Users" menu, scroll down... ok, that lets you with somebody on "B"... so again, scroll down... ok, that lets you on page with users on "F"... and so on and so on, until you finally get to "Z" users... that is soooo annoying! :/

2) Imagine you want once a while to check, if everybody is in group "Gamma" - how you are gonna do that effectively without "no group" virtual group?

**Comment by nickvergessen** [comment]
I understand the use-case and the intention, I just say that the implementation is not possible at the moment.

We can easily do it for our local backend, but it will not work for all others, until we can force an api change

**Comment by crysman** [comment]
@nickvergessen OK, understood. I thought you were not going to look into it... You say "at the moment", so possibly in the future this might get implemented, right? Thank you all!

**Comment by MorrisJobke** [comment]
> ou say "at the moment", so possibly in the future this might get implemented, right? Thank you all!

Correct. Currently there is no plan to implement this. Nevertheless if somebody come up with this implemented we are fine with integrating this. Therefore it is in the backlog - the pool of ideas that would be nice, but are not considered yet for the next release.
