### ISSUE TITLE
Different errors when you select the "Exclude groups to share " on v8.2.2 and v9.0

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/core#22402]
### Steps to reproduce
1. Install the Desktop client v 2.2.0 with Server v 9.0, with yellow user
2. Go to the Server Web
3. Select the option "Exclude groups from sharing"
![screen shot 2016-02-15 at 15 13 24](https://cloud.githubusercontent.com/assets/12032058/13050936/cc9578fa-d3f6-11e5-8bf2-a4bafad86be6.png)
4. Go to the Desktop client
5. Create a new folder
6. Share with owncloud
7. Write on 'Share with users or gruops', the group that include the yellow user, in this case colors

### Actual behaviour
When you select the group (e.g. colors), appears this error: 
![screen shot 2016-02-15 at 14 56 51](https://cloud.githubusercontent.com/assets/12032058/13051023/4fd2cf4c-d3f7-11e5-92ae-7a434c3a450d.png)
LOG
```
02-15 14:57:39:355 0x7fb6db521fe0 OCC::OcsJob::finished: Reply to "POST"  QUrl( "https://xxxxxxxxxxx/ocs/v1.php/apps/files_sharing/api/v1/shares" )  (QPair("path","/Share_with_others"), QPair("shareType","1"), QPair("shareWith","colors")) has unexpected status code: 403 "{"ocs":{"meta":{"status":"failure","statuscode":403,"message":"The Share API is disabled"},"data":[]}}"
02-15 14:57:39:356 0x7fb6db521fe0 OCC::ShareUserGroupWidget::displayError: Error from server 403 "The Share API is disabled"
```

NOTE: If I do the same with a server 8.2.2, I have the different error:
![screen shot 2016-02-15 at 14 59 22](https://cloud.githubusercontent.com/assets/12032058/13051072/8a4aad70-d3f7-11e5-88f2-89c08f7cdb2e.png)

### Server configuration
Desktop v ownCloud-2.2.0.3123-nightly20160215.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.2.2","versionstring":"8.2.2","edition":"Enterprise"}
{"installed":true,"maintenance":false,"version":"9.0.0.11","versionstring":"9.0 beta 1","edition":""}

**Comment by rullzer** [comment]
Mmmm... I'll look into this...

**Comment by rullzer** [comment]
@Dianafg76 I think I got it... it is just the error message that has changed right?

**Comment by Dianafg76** [comment]
@rullzer Yes

**Comment by rullzer** [comment]
Ok will fix. Thanks

**Comment by rullzer** [comment]
PR in #22416
