### ISSUE TITLE
per user backup

### ISSUE THREAD

**Issue by pierreozoux** [owncloud/core#22404]
```
Given I am an ownCloud admin,
And I do hourly backups,
When I receive a request from a user to restore his account 3 days ago (files+contacts+calendar)
Then I should be able to restore just this user
```

Do you know if there is any tool that allow that?
Thanks!

**Comment by DeepDiver1975** [comment]
> Do you know if there is any tool that allow that?

I'm not aware of any

**Comment by enoch85** [comment]
@pierreozoux Make a bash script that saves to different locations and time. Would requrie alot of space but should be possible.

**Comment by pierreozoux** [comment]
@enoch85 I don't understand.
I think a more accurate description would be:"how to backup/restore all lines in a db that belong to one user".
(Files are easy)

**Comment by enoch85** [comment]
@pierreozoux Yeah, you're right. That's "a bit" more tricky. :)
