### ISSUE TITLE
remember checkbox pre-checked if known IP

### ISSUE THREAD

**Issue by unhammer** [owncloud/core#22428]
The remember checkbox has gone back and forth between being checked https://github.com/owncloud/core/pull/4175 and unchecked https://github.com/owncloud/core/issues/5286 by default. I would guess what makes sense for most users is for default-unchecked on new IP addresses, default-checked if you've successfully logged in from that IP before.

**Comment by nickvergessen** [comment]
Please elaborate which checkbox you are talking about. e.g. a screenshot would be helpful

**Comment by unhammer** [comment]
Sorry, I mean this: https://doc.owncloud.org/server/7.0/user_manual/_images/oc_connect.png

**Comment by MorrisJobke** [comment]
cc @LukasReschke - you also want to do something with detecting malicious logins that also depend on the IP address.
