### ISSUE TITLE
Sharing a file, the own user is shown in the user sharing list

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/core#22427]
### Steps to reproduce
1. Go to the Server Web with v 9.0 with one user (e.g p@nk)
2. Create a new file (e.g Share_folder.txt)
3. Share the file with the same user (e.g p@nk). Sharing a file, write down a pattern that matches with the user logged. I can see the name p@nk (remote) in the dropdown

### Expected behaviour
Tell us what should happen

### Actual behaviour
Appears this error
![screen shot 2016-02-16 at 13 58 56](https://cloud.githubusercontent.com/assets/12032058/13076941/f9351798-d4b5-11e5-86e3-60f2ddeb0950.png)

![screen shot 2016-02-16 at 13 59 09](https://cloud.githubusercontent.com/assets/12032058/13077070/e87e072e-d4b6-11e5-9edd-8d67ee191eb7.png)

No logs in owncloud.log file

### Server configuration
Server v {"installed":true,"maintenance":false,"version":"9.0.0.11","versionstring":"9.0 beta 1","edition":"Enterprise"}

**Comment by nickvergessen** [comment]
For me it shows two entries, first entry is the local user (works), the other one is user p on server nk (does not work).
So works as expected for me?
![bildschirmfoto vom 2016-02-16 14 42 07](https://cloud.githubusercontent.com/assets/213943/13077842/9ac71430-d4bb-11e5-84e7-facc698d936b.png)

**Comment by Dianafg76** [comment]
@nickvergessen If you go to the Server Web with v 9.0 with one user (e.g p@nk), you can't share the folder/file with the same user

**Comment by rullzer** [comment]
@Dianafg76 I assume your dropdown shows `p@nk (remote)`?

Which happens because there is an `@` in the username. When clicking on it it tries to share with the user `p` at the server `nk`. Now it can't find the server `nk` so all fails.

I agree with @nickvergessen that this is actually the correct behaviour.

**Comment by Dianafg76** [comment]
@rullzer the @ is part of the my username (p@nk). My confusion has been with the @
I'll close the issue

**Comment by rullzer** [comment]
Yeah usernames containing an @ are not ideal in this situation...
