### ISSUE TITLE
[Code checker] Check for missing index names

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#22420]
To avoid issues like https://github.com/owncloud/core/issues/22394

@nickvergessen @LukasReschke

**Comment by nickvergessen** [comment]
Well my patch fixes the actual issue, so the default fallback works. Then we don't need a code checker for it: https://github.com/owncloud/core/pull/22399 (2nd commit)

**Comment by PVince81** [comment]
Okay, then this is not needed :smile:
