### ISSUE TITLE
Use symfony/polyfill instead of patchwork

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#22442]
Due to issues such as https://github.com/owncloud/core/issues/22324 and https://github.com/owncloud/core/issues/20065

**Comment by PVince81** [comment]
@DeepDiver1975 @PhilippSchaffrath thoughts ? Would move to backlog if there is no objection.

**Comment by DeepDiver1975** [comment]
symfony/polyfill appears to be more active compared to patchwork .... I'm undecided ...

**Comment by PVince81** [comment]
please reopen when this becomes relevant again, if applicable
