### ISSUE TITLE
Displayed share with disappears after navigate through a folder

### ISSUE THREAD

**Issue by nasli** [owncloud/core#22449]
### Steps to reproduce

1.In a root of a server with some folders shared with me via federated sharing and some folders shared with other user, navigate to a folder and go back to root
### Expected behaviour

The displayed share with name remained after navigate
![screen shot 2016-02-16 at 18 39 40](https://cloud.githubusercontent.com/assets/6570505/13103080/9bba49b4-d553-11e5-8dc3-e2a4064d8380.png)
### Actual behaviour

The displayed share with name not remained after navigate
![screen shot 2016-02-16 at 18 39 06](https://cloud.githubusercontent.com/assets/6570505/13103084/a18193de-d553-11e5-8c2a-64d85ba6e2f6.png)
### Server configuration

{"installed":true,"maintenance":false,"version":"9.0.0.11","versionstring":"9.0 beta 1","edition":""}

**Comment by nickvergessen** [comment]
also happens with normal shares...
@PVince81

**Comment by PVince81** [comment]
Normal shares is another issue and possibly a regression, could be related to the changes to the sharing code.

**Comment by rullzer** [comment]
I can't reproduce this on master. I also find it very weird they both disappear. As they get the info from different sources.

@nasli are you testing master or the beta1?

**Comment by nickvergessen** [comment]
Okay maybe it's important that the folder also contains an item (at least that is what made it work for me)

https://raw.githubusercontent.com/nickvergessen/jubilant-succotash/master/sharing-info-vanishing.mp4

**Comment by PVince81** [comment]
@nasli is this still happening with OC 10.0.3 ?

**Comment by PVince81** [comment]
Please reopen if issue persists with 10.0.4
