### ISSUE TITLE
Share the folder with a group and then with a user included in the group , the icon continues to spin

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/core#22441]
### Steps to reproduce
1. Go to the Server Web with v 9.0 with one user (e.g yellow)
2. Create a new folder/file (e.g hello)
3. Share the folder with the group call colors
4. Share the folder with the red user (this user is include to the group colors)
![screen shot 2016-02-16 at 16 59 33](https://cloud.githubusercontent.com/assets/12032058/13081923/f15aac36-d4ce-11e5-8880-1d76b92a37e2.png)
5. Click on OK for the "Error while sharing"

### Expected behaviour
Tell us what should happen

### Actual behaviour
And the sharing option is disabled and the icon continues to spin 
![screen shot 2016-02-16 at 16 59 49](https://cloud.githubusercontent.com/assets/12032058/13081986/3073fc24-d4cf-11e5-9c8e-b980b01a66e4.png)

![screen shot 2016-02-16 at 17 20 52](https://cloud.githubusercontent.com/assets/12032058/13082635/bdcfa666-d4d1-11e5-8833-25149c586cd2.png)

### Server configuration
Server v {"installed":true,"maintenance":false,"version":"9.0.0.11","versionstring":"9.0 beta 1","edition":"Enterprise"}

**Comment by rullzer** [comment]
Aaah yes we should handle that properly. I'll take care.

**Comment by rullzer** [comment]
PR in #22452
