### ISSUE TITLE
Resharing is not allowed for a federated folder on master

### ISSUE THREAD

**Issue by nasli** [owncloud/core#22448]
### Steps to reproduce
1.User server A share a folder with a user other server B

### Expected behaviour
User in server B can share this folder

### Actual behaviour
User in server B can not share this folder
![screen shot 2016-02-17 at 09 01 24](https://cloud.githubusercontent.com/assets/6570505/13103291/7271b414-d555-11e5-937c-4afd1f4538b3.png)

### Server configuration
{"installed":true,"maintenance":false,"version":"9.0.0.11","versionstring":"9.0 beta 1","edition":""}

**Comment by rullzer** [comment]
@schiesbn this is expected for 9.0 right?

**Comment by rullzer** [comment]
@nasli could you verify if this is still the case? I can't reproduce this. For me this is not happening...

**Comment by nasli** [comment]
:+1: Fixed via #22503
