### ISSUE TITLE
[Files_external] Configuring mounts via CLI; backends command should show authentication fields required

### ISSUE THREAD

**Issue by davitol** [owncloud/core#22447]
### Steps to reproduce

1. Run the command

sudo -u www-data ./occ files_external:backends

### Expected behaviour

All arguments required to create a files_external mountpoint are shown

### Actual behaviour

It is shown the type of authentication but not the name of the arguments needed. You have to look them up in the code in /files_external/lib/XXX.php files

e.g. sudo -u www-data ./occ files_external:backends

```
...
dropbox:
- name: Dropbox
- identifier: dropbox
- configuration:
- storage_class: \OC\Files\Storage\Dropbox
- supported_authentication_backends:
  - oauth1::oauth1
```

but for creating a dropbox mount via CLI I must run:

sudo -u www-data ./occ files_external:create newdropbox dropbox oauth1::oauth1 -c app_key=XXX -c app_secret=XXX

is there any way to know that the name o fthe arguments are app_key and app_secret without looking into the php code?

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 9.0 beta 1 (daily) Build:2016-02-15T04:14:27+00:00 ac367b97f0567481d3496a213c04eeb5cf654a9f

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** googleDrive;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**

**Comment by PVince81** [comment]
It should be possible for the CLI command to ask every backend which options they expect to have and display those. These options are registered API-wise already to be able to display them in the GUI.

Since this is an enhancement request, moving to 9.2

CC @icewind1991

**Comment by icewind1991** [comment]
Fix is here https://github.com/owncloud/core/pull/25314
