### ISSUE TITLE
It is not possible to 'grant access' to a googledrive mount configuration via CLI

### ISSUE THREAD

**Issue by davitol** [owncloud/core#22440]
### Steps to reproduce

1. Create a googledrive mount point via command line interface.

e.g.

sudo -u www-data ./occ files_external:create newgdrive googledrive oauth2::oauth2 -c client_id=XXXXXXXXXXXXXXX.apps.googleusercontent.com -c client_secret=XXXXXXXXX

### Expected behaviour

The mountpoint is created and the access is granted

### Actual behaviour

The client_id and client_secret configuration is shown in the webUI, but it is need to click on Grant Access button in the admin menu in order to finish the mountpoint configuratio

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 9.0 beta 1 (daily) Build:2016-02-15T04:14:27+00:00 ac367b97f0567481d3496a213c04eeb5cf654a9f

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** googleDrive;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**

**Comment by PVince81** [comment]
Might not be technically possible as it requires web interaction with Google's pages.

**Comment by DeepDiver1975** [comment]
> Might not be technically possible as it requires web interaction with Google's pages.

exactly -> close as wontfix
