### ISSUE TITLE
Wrong tooltip message when trying to fed.share a file with a fed.user that has already received the share

### ISSUE THREAD

**Issue by davitol** [owncloud/core#22459]
### Steps to reproduce
1. Fed. share a file with a user of another server
2. Try to fed.share the same file with the same user again
### Expected behaviour

A tooltip warning that the file has been already shared with the user should be shown
### Actual behaviour

 No user or groups found tooltip message is shown
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 9.0 beta 1 (daily) Build:2016-02-15T04:14:27+00:00 ac367b97f0567481d3496a213c04eeb5cf654a9f

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Firefox

![screen shot 2016-02-17 at 10 47 10](https://cloud.githubusercontent.com/assets/10596560/13106256/889c1f60-d567-11e5-85d9-3325ceb53369.png)

**Comment by rullzer** [comment]
Yes this is because there is only a single status code for a remote server rejecting a share. @schiesbn we should look into this.

**Comment by PVince81** [comment]
@davitol still an issue with 9.0.5 / 9.1.1 ?

**Comment by PVince81** [comment]
Please reopen if issue still exists in 10.0.4
