### ISSUE TITLE
[OC 8.2.2] Renaming Shared file

### ISSUE THREAD

**Issue by kwiatek6324** [owncloud/core#22453]
Case Scenario
User A, User B
User A shares file file.txt to User B
User B see in Shared folder file "file.txt"
User A renames file to file2.txt
User B see in Shared folder old filename "file.txt"

Is it correct ?
User B should see "file2.txt".

**Comment by rullzer** [comment]
No this is correct. The mount point can be renamed. Else what would happen if you already have a file called `file2.txt` does that get overwritten. Etc.

If you share a folder `foo`. And inside that folder is a file called `file.txt` and you rename that to `file2.txt` then user B will see that rename.

However if user A renames the folder `foo` to`bar`. Then user B won't see that.
