### ISSUE TITLE
Display login dialog instead of redirect when session timeout in Javascript

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#22458]
In some apps like the notes app, you might have typed in stuff that hasn't been saved yet.
If the session times out, as per https://github.com/owncloud/core/pull/16783 you will be redirected to the login page and would lose the notes.

Instead of the redirect, what should happen is that an overlay grays out the page and a popup dialog appears to prompt for the credentials for re-login. (some trickery might be needed in case of SSO, like reauthing inside an iframe)
After logging in again, the overlay disappears and work can resume.

@jancborchardt @BernhardPosselt @MorrisJobke @DeepDiver1975 @LukasReschke @karlitschek

**Comment by jancborchardt** [comment]
In which scenario would the session time out _while you’re working on something_? Or do I misunderstand? Cause the Notes app saves everything directly.

Stuff like session timeout is not a nice UX and we should prevent it wherever possible.

**Comment by PVince81** [comment]
This is only valid assuming that all apps are using auto-save like the text editor does now.

Session timeout seldom happens. The only cases I can think of is if someone puts their computer to sleep with an owncloud tab open, and opens the computer again a day later. In this case the heartbeat cannot keep the session open.

There might be other SSO-cases where a redirect will happen to recreate a new SSO-session. A user would still lose whatever was visible. At least maybe the SSO case needs to be handled with a hidden iframe in the future to avoid the redirect.

**Comment by MorrisJobke** [comment]
> Stuff like session timeout is not a nice UX and we should prevent it wherever possible.

Not possible in days of just closing the lid of your laptop and open it some days later.

**Comment by oparoz** [comment]
>Instead of the redirect, what should happen is that an overlay grays out the page and a popup dialog appears to prompt for the credentials for re-login

Yes, please. That's the way smart web apps do it. Nothing worse than losing the content of a long post because of an expired session...

**Comment by karlitschek** [comment]
don't we have the keepalive ping to prevent session timeouts?
The only bad scenario is the shutting down the laptop and open it up again later or a lost network connection for a long time. But maybe I'm old school but I as a user wouldn't expect from a web application that it survives such a situation.
In the end I agree that we should implement the proposed behavior from Vincent

**Comment by LukasReschke** [comment]
> don't we have the keepalive ping to prevent session timeouts?

Won't work with some SSO such as Shibboleth. Shibboleth tokens as-is just expire after some time :speak_no_evil: :see_no_evil: :hear_no_evil:

**Comment by BernhardPosselt** [comment]
Simply use something else that does not block the content, that way even network issues should not be a problem

**Comment by jancborchardt** [comment]
Ok, I can’t comment about stuff like Shibboleth. But in the normal cases I totally agree with Frank – we have the keepalive ping for that.

But yeah, if it’s absolutely necessary then a simple modal is better than redirecting to the log in page.
