### ISSUE TITLE
Shared mount points still accessible after turning off sharing

### ISSUE THREAD

**Issue by rperezb** [owncloud/core#22457]
Related to: https://github.com/owncloud/core/issues/19157

### Steps to reproduce
1. Register a new mount point, such as: ownCloud called it ocMount, make it available for just the admin group and grant reshare availability
2. Create a user (user1) on that server and *do not* included it on the admin group
3. Share ocMount with user1
4.- User1 has access to the mountpoint
5.- As admin, remove the share option

### Expected behaviour
Following: 
```If any shares existed already on that storage, they will continue to exist internally but will not be accessible for recipients any more. In the event where the admin will re-enable sharing for such mounts, the shares will become accessible again.````
After step5, the folder ocMount should not be visible for user1

### Actual behaviour
ocMount has access to the folder

### Server configuration
ownCloud 9.0 beta 1 (daily) Build:2016-02-17T04:42:01+00:00 c6b24573066cfc87b73b1b61b41032b8c5a406cf

**Comment by PVince81** [comment]
@rperezb did you wait for the external storage to re-save itself ? You can check in the admin page whether the option is still set after refreshing (small UX issue).
If it's indeed disabled after refresh, then it's a bug.

@icewind1991 the checks might not be water-tight enough ?

**Comment by icewind1991** [comment]
Can't reproduce

**Comment by rperezb** [comment]
:walking: just checked again... and working
