### ISSUE TITLE
Support for master / slave in DB connection

### ISSUE THREAD

**Issue by sidey79** [owncloud/core#22454]
Question:

Is there support or planning for  a master/slave configuration as described in MasterSlaveConnection.php from the doctrine  Lib?

**Comment by DeepDiver1975** [comment]
Not yet supported - and also nothing planned for now - contributions are welcome

**Comment by sidey79** [comment]
Just to get some more feeling what has to be done.

I've looked a litte bit at the code. As i understand, there is core/lib/private/db/connection.php which acts as an drive to the database.

From my point, this class has to be extended to the example from the MasterSlaveConnection.php. Not really a hughe thing. The main difference is to, open a connection when a select/insert/etc. is called, instead of creating the connection at initialisation. May a easy way of working is to do it with an value in the connect() value that has a default to connect to a slave server. I know, there are some more details, as config values, reconnect to the master and how to detect if a slave is operational.
Also ther must be an mode of operation for installations which doesn't worry about a slave server.

May someone can verify if i'm on the right thing or if i missed something general.

**Comment by butonic** [comment]
closing in favor of https://github.com/owncloud/core/issues/26909
