### ISSUE TITLE
External Storage Admin Checkbox to share enable by default

### ISSUE THREAD

**Issue by rperezb** [owncloud/core#22460]
related to: https://github.com/owncloud/core/issues/19157

### Expected behaviour
It was expected: Check box (disabled by default) labeled “allow sharing” is checked when the mount point for external storage or any secondary storage app is added

### Actual behaviour
The allow sharing is enable by default

@MTRichards guess this is fine

**Comment by PVince81** [comment]
@icewind1991 @Xenopathic I guess it should be possible already for storage backends to provide default values for mount options ? (in case some storages need to use different defaults)

**Comment by icewind1991** [comment]
> I guess it should be possible already for storage backends to provide default values for mount options

No, the storage backend can't, the mount provider can

**Comment by icewind1991** [comment]
Disabling sharing by default would lead to issues with all existing shares disappearing until sharing is re-enabled for the storage

**Comment by PVince81** [comment]
> Disabling sharing by default would lead to issues with all existing shares disappearing until sharing is re-enabled for the storage

Not really. "By default" means, it's disabled the first time the storage is created. At creation time, a storage doesn't have any shares on it.

**Comment by PVince81** [comment]
@MTRichards should sharing be disabled by default for any newly created external storage mount point regardless of type ?

That was the case for WND for example, maybe it was a safety measure.

**Comment by MTRichards** [comment]
It should be off by default.

**Comment by PVince81** [comment]
@icewind1991 can you make the sharing option off by default ?

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/22600

**Comment by karlitschek** [comment]
hmm. this is a change of behavior. Do we really want to do that?

**Comment by PVince81** [comment]
@karlitschek by default WND had sharing disabled (opt-in). External storage in core had no such option and sharing was always enabled.

Now they are both integrated with core. The quickest solution was to make it (opt-in) for all in this PR https://github.com/owncloud/core/pull/22600

If we want to have per-storage defaults then it will need more changes to allow storage backends to specify their preferred defaults.

Do we want this difference ? It seemed like we don't want to have WND's sharing enabled by default (change of behavior there).

@karlitschek @MTRichards

**Comment by karlitschek** [comment]
hmm ok. in this case I agree. Lets do disable by default. Sorry for the confusion

**Comment by PVince81** [comment]
@karlitschek thanks
