### ISSUE TITLE
[FIles external] Cannot share a file from a S3 mount with a LDAP user and share the same file from S3 mount to the same LDAP user.

### ISSUE THREAD

**Issue by davitol** [owncloud/core#22469]
### Steps to reproduce

1. As admin user configure a files external S3 mountpoint  and save it (applicable = all)
2. Login with an LDAP user, share a file from the S3 mountpoint with admin user
3. Login with admin user, share the same file from the S3 mountpoint with the same LDAP user

### Expected behaviour
Two possible options:
a) The LDAP user should not be shown in the list of users available for sharing due to we consider it is the same file
b) The file should be shared

### Actual behaviour

An error message is shown. This message is shown: Sharing failed, because the user aaliyah_adams is the original sharer

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 9.0 beta 1 (daily) Build:2016-02-17T04:14:46+00:00 c6b24573066cfc87b73b1b61b41032b8c5a406cf

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** yes; S3.
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox for Mac OSX

**Comment by blizzz** [comment]
@davitol I expect this to work with local users just the same. Isn't it so?

@rullzer what do you think?

**Comment by rullzer** [comment]
@davitol Am I correct in understanding that you try to create a share with the owner of the data?

Sharing *should* indeed be the same with local users etc.

**Comment by davitol** [comment]
Tested again and it works fine. Sol let's close it

**Comment by aspdye** [comment]
Can we "backport" this to the 9.0 release?

**Comment by blizzz** [comment]
@aspdye backport what? There are no change. @davitol tested with OC 9 pre-release.

**Comment by aspdye** [comment]
uuppps ... Thought there were changes because it was tagged with the milestone 9.0.1 :sweat_smile:
