### ISSUE TITLE
need to adjust required phpunit version

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#22466]
It seems like in the development cycles for 9.0 we introduced PHPUnit features which requires PHPUnit 4.4 or higher, e.g. https://github.com/owncloud/core/blob/master/apps/federatedfilesharing/tests/federatedshareprovidertest.php#L134

autotest.sh requires only phpunit 3.7 or higher, https://github.com/owncloud/core/blob/master/autotest.sh#L57

We should rise the requirement or "downgrade" our tests.

(PS: as a Debian stable user I would prefer not to require such a high version, but of course that's no real argument :wink: )

cc @DeepDiver1975 @rullzer @PVince81

**Comment by rullzer** [comment]
> ... such a high version.

Released on 2014-12-05.... :wink:

**Comment by schiesbn** [comment]
@rullzer I know, debian stable is sooo old :wink: Still for a enterprise distribution this isn't old, so I don't know if we want to rise the requirements that high.

Anyway, we don't have to keep the requirement that low just for me. Thinking more about productive environments which run all this stable and old versions like centos, rhel, sles, debian,...

**Comment by DeepDiver1975** [comment]
For me the time is long gone where I use the distribution repos to get phpunit - same will soon happen to php itself ....

anyway - Jenkins is running phpunit 4.6

Let's require 4.4 as minimum
