### ISSUE TITLE
Error (imagecreatefromjpeg(): gd-jpeg, libjpeg: recoverable error)

### ISSUE THREAD

**Issue by TheKaban** [owncloud/core#22471]
Hello!
Self can not find a solution for this problem, for this I ask your help.
An error:
`
imagecreatefromjpeg (): gd-jpeg, libjpeg: recoverable error:? at /var/www/owncloud/lib/private/image.php#512`

Causes of error I do not know.
Please tell me how it can be solved?

Thank you!

**Comment by LukasReschke** [comment]
![2016-02-17_14-20-53](https://cloud.githubusercontent.com/assets/878997/13110664/ac52ae6e-d581-11e5-8600-d96f0cab60fc.png)

Anyways. Seems to be fixed with 9.0 (https://github.com/owncloud/core/commit/f32827e903ef8d833a6a3249a45bedcaf774e1eb)

**Comment by TheKaban** [comment]
Thank you!
Regarding the registration posts, I will consider for the future.
