### ISSUE TITLE
Add save button for external storage configuration

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#22479]
The external storage configuration is too complex to be able to rely on auto-save for settings.
Also there is the risk of mistyping something or clicking on the wrong field and then saving these values into the wrong configuration. Changing config values here can have bigger consequences as it would affect the storage of many users.

So for this, I suggest that we add a "Save" button.
Whenever an unsaved configuration is detected, do not let the user leave the page and show the usual "You are leaving this page with unsaved changes, continue ?" like we do for example when uploads are running.

This would also help with situations where people forgot to click outside the mount options dropdown and stuff wasn't saved properly.

@MTRichards @Xenopathic @icewind1991 @DeepDiver1975 @rperezb

**Comment by guruz** [comment]
Good suggestion, for me on Chrome / OS X it seems to trigger a save/PUT just by loading the whole ```index.php/settings/admin```

**Comment by PVince81** [comment]
This has some security implications: whenever an admin creates a new external storage, they might not reach the "Applicable" field quickly enough. During that time, the storage is shortly availble for ALL users.

**Comment by PVince81** [comment]
@felixheidecke what do you think ?

**Comment by PVince81** [comment]
cc @pmaier1 @jvillafanez

**Comment by pmaier1** [comment]
Sounds good. Anyway we need to come to some consistency in terms of saving settings. Some fields have auto-save, for some you need to hit 'enter', some others have buttons. What about smart buttons btw. https://central.owncloud.org/t/ui-proposal-smart-buttons-prevent-accidental-dangerous-changes-of-the-oc-configuration/2074?

**Comment by PVince81** [comment]
moving to triage for now. @pmaier1 please add PM priority

**Comment by PVince81** [comment]
- [ ] also consider adding a way to have storages not assigned to anyone instead of "All"
