### ISSUE TITLE
[Files external] CLI, --help command should show the names of the available options of each command

### ISSUE THREAD

**Issue by davitol** [owncloud/core#22474]
### Steps to reproduce
1. Manage external mounts  for a mount with files external commands
### Expected behaviour

The info shown with --help command should provide us the different options available for each command
### Actual behaviour

e.g ./occ files_external:option --help    command returns:

```
Usage:
  files_external:option <mount_id> <key> [<value>]

Arguments:
  mount_id              The id of the mount to edit
  key                   key of the mount option to set/get
  value                 value to set the mount option to, when no value is provided the existing value will be printed

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
```

How a user can know that the mount options are 'previews' or 'enable_sharing' for example?
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 9.0 beta 1 (daily) Build:2016-02-17T04:14:46+00:00 c6b24573066cfc87b73b1b61b41032b8c5a406cf

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** yes; S3.
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Firefox for Mac OSX

**Comment by PVince81** [comment]
We can't detect the options in advance as backends could provide their own. Currently there are no plans in adding a way for backends to advertise their options. Best would be to document these.
