### ISSUE TITLE
Range request fail with GDrive stream wrapper, stream lies about being seekable

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#22476]
### Steps to reproduce

1. Setup GDrive storage as "gdrive"
1. Upload a small text file with known contents
3. `curl -X GET -H Range:bytes=2-5 'http://root:admin@localhost/owncloud/remote.php/webdav/gdrive/bacon.txt'`

### Expected behaviour
Returned bytes match

### Actual behaviour
Returned bytes start at the beginning of the stream

### Version
ownCloud 9.0 git master 9c1248521a76d7d8e5c6c893cf73b149fdf80df1

This happens because the stream lies about being seekable when doing this check: https://github.com/owncloud/3rdparty/blob/master/sabre/dav/lib/DAV/CorePlugin.php#L336

If you debug into that block and evaluate the stream's metadata, its "seekable" value is true.
However as soon as Sabre tries to do a `fseek` it will fail.

I suspect this might be due to our stream wrappers which do implement `fseek`. We might need to somehow patch the wrappers to properly forward the underlying stream metadata.

@icewind1991 @schiesbn

**Comment by PVince81** [comment]
This breaks syncing when the sync client tries to resume downloading using range requests.

**Comment by PVince81** [comment]
Citing http://php.net/manual/de/function.stream-get-meta-data.php#115608
"Apparently, custom wrappers are always seekable."

But maybe there is a way to influence the metadata ?

**Comment by PVince81** [comment]
If that doesn't work, then we might want to implement the "read and discard data up to the correct position" to simulate forward fseek. (which Sabre actually does already if we tell it that the stream is not seekable)

**Comment by PVince81** [comment]
Something to be fixed in the streams library https://github.com/icewind1991/Streams/issues/2

**Comment by PVince81** [comment]
I did some research and didn't find any way to make the stream wrapper influence the return value of `stream_get_meta_data`. So I raised at ticket for Sabre DAV https://github.com/fruux/sabre-dav/issues/787 to revert to the old 2.1 behavior where it was actually checking the result of `fseek`

**Comment by PVince81** [comment]
fseek works for GDrive on OC 9.0.0 because we had to fix the download by adding an intermediary temporary file which is seekable.

However, we still need the general solution for non-seekable stream.

**Comment by PVince81** [comment]
Note that in 9.0 this isn't an issue any more because of the GDrive workaround using a temporary file.

So before applying the patch, let's find out which external storages support streaming and would suffer from the fseek issue.

I suspect that Webdav/ownCloud external storages (and/or fed shares) might.

**Comment by PVince81** [comment]
Hmm, with federated shares, `fseek` seems to work fine. Weird, it's not supposed to work on network streams.

**Comment by PVince81** [comment]
AHA, it looks like doing a `fopen()` on `http://` supports fseek, but `https://` doesn't...

**Comment by PVince81** [comment]
Steps:

1. Setup an OC instance with SSL/HTTPS
1. Create a folder "test" with a file "bacon.txt" inside
1. Create a link share for "test"
1. Mount the link share on a local OC 9.0 / master as "test"
1. `curl -X GET -H Range:bytes=2-5 'http://admin:admin@localhost/owncloud/remote.php/webdav/gdrive/bacon.txt'` (on the local instance)

Expected: fseek worked, middle of the text returned
Actual: start of the text returned

**Comment by PVince81** [comment]
Fix is here through library update: https://github.com/owncloud/3rdparty/pull/258

**Comment by guruz** [comment]
@atroxix is getting negative content lengths already from PROPFIND.
Is this fixed with that PR too?

https://github.com/owncloud/client/issues/4573#issuecomment-199708526

**Comment by PVince81** [comment]
No, negative content length is a different thing.
