### ISSUE TITLE
Not is possible to unshare o delete a federated folder accepted

### ISSUE THREAD

**Issue by nasli** [owncloud/core#22483]
### Steps to reproduce
1.User server A share a folder with user folder B
2.User B accept federated sharing
3.User A delete the folder

### Expected behaviour
It is possible to delete o unshare the federated folder accepted

### Actual behaviour
Not is possible to delete o unshare the federated folder accepted

### Server configuration
{"installed":true,"maintenance":false,"version":"8.2.2.2","versionstring":"8.2.2","edition":""}
{"installed":true,"maintenance":false,"version":"9.0.0.11","versionstring":"9.0 beta 1","edition":""}

**Comment by PVince81** [comment]
@rullzer @schiesbn

**Comment by rullzer** [comment]
Mmmm this seems to be a result of moving to webdav. Since we try to get the node for the folder. Which does not exists so we throw an error before we can do the actual delete....

**Comment by rullzer** [comment]
Happens here https://github.com/owncloud/core/blob/master/apps/files_sharing/lib/external/storage.php#L258

@schiesbn can you have a look?

**Comment by PVince81** [comment]
One step is missing: User A must delete the folder from the trash bin.
Else the share info still exists.

However even in this case, User B still sees the folder. Navigating into the folder must make it disappear.

The bug is that Server A must return `StorageInvalid` not `StorageNotAvailable`

**Comment by PVince81** [comment]
Actually, no. The shareinfo.php call must tell that the share is gone.

**Comment by PVince81** [comment]
Okay, I think I got it, the share entry still exists:
```
+----+------------+--------------------------+-----------+---------------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-----------------+-----------+
| id | share_type | share_with               | uid_owner | uid_initiator | parent | item_type | item_source | item_target | file_source | file_target | permissions | stime      | accepted | expiration | token           | mail_send |
+----+------------+--------------------------+-----------+---------------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-----------------+-----------+
|  1 |          6 | user1@localhost/owncloud | root      | root          |   NULL | folder    | 8           | NULL        |           8 |             |           7 | 1455792080 |        0 | NULL       | 4XaoK5wPvt22QDO |         0 |
+----+------------+--------------------------+-----------+---------------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-----------------+-----------+
1 row in set (0.00 sec)
```

Now let's run cron to clean it up...

**Comment by PVince81** [comment]
And POOF the share entry is gone.

And yet... User B still cannot get rid of it.

Steps so far:

1. User 1 shares folder "test" with User 2 with fed sharing
1. User 2 accepts the share
1. User 1 deletes the folder "test"
1. User 1 empties trashbin
1. System runs cron.php to make sure the share gets cleant up (invalid file id)
1. User 2 enters folder "test"

Actual: The folder is still there "storage not available"
Expected: The folder disappears after entering with "storage invalid".

Still looks like a bug in the 404 detection.

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/22498
