### ISSUE TITLE
The "path" parameter returned by share api for federated sharing is not the full path

### ISSUE THREAD

**Issue by nasli** [owncloud/core#22484]
### Steps to reproduce
1.User A share a folder with files to user B in other server
2.User B in the other server share this folder with user C in the same server
3.user C share a file inside this folder

### Expected behaviour
The share api return
file_target has the filename: image.gif and path has the full path: /folder/image.gif
`<file_target>/image.gif</file_target>`
`<path>/folder/image.gif</path>`

### Actual behaviour
For files inside federated folders for the parameter "path" returned by share api (files_sharing/api/v1/shares) is not the full path
file_target has the filename: image.gif but path not the full path: /folder/image.gif
 `<file_target>/image.gif</file_target>`
  `<path>/folder</path>`

### Server configuration
{"installed":true,"maintenance":false,"version":"9.0.0.11","versionstring":"9.0 beta 1","edition":""}

**Comment by PVince81** [comment]
@schiesbn @rullzer please evaluate severity

@nasli do you know if this is a regression ?

**Comment by rullzer** [comment]
Aaah the joy of federation resharing...

**Comment by rullzer** [comment]
@nasli can you retest with https://github.com/owncloud/core/pull/22503 that seems to fix it here.

**Comment by nasli** [comment]
@rullzer fixed via #22503 :)
