### ISSUE TITLE
On some mobile devices, the sidebar pushes the files list away instead of covering it

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#22480]
### Steps to reproduce
1. Open ownCloud on a tablet
2. Open Files
3. Tap on a file to bring out the sidebar
### Expected behaviour

The sidebar should cover the right side of the files list.
### Actual behaviour

The sidebar pushes the files list to the left, underneath the left navigation menu
### Server configuration

**ownCloud version:** master
### Client configuration

**Browser:** Safari

**Operating system:**

iOS 9.2.1 / iPad2 (lowdpi)

**Comment by PVince81** [comment]
@owncloud/designers

**Comment by PVince81** [comment]
@oparoz regression from 8.2.2 or earlier ?

**Comment by oparoz** [comment]
@PVince81 - Just tested 8.2.2 and it's working fine.

**Comment by oparoz** [comment]
Correction, it's also broken on 8.2.2

**Comment by cmonteroluque** [comment]
@rperezb

**Comment by cmonteroluque** [comment]
@javi

**Comment by PVince81** [comment]
@oparoz I see this is tagged as regression, so did this ever work before ?
If it did, it can't be before 8.2.0 because there was no sidebar then.

Can you maybe help to bisect it if it worked before ? Maybe it will point at some CSS changes that might help find a fix ?

**Comment by PVince81** [comment]
@felixheidecke would you be able to help with this ?

**Comment by felixheidecke** [comment]
I'll be taking a look @ it in a minute.

**Comment by felixheidecke** [comment]
> I'll be taking a look @ it in a minute.

Well … that was 22 Days ago :expressionless: … Anyway I'll be looking at it this afternoon.

**Comment by felixheidecke** [comment]
Well … this like a feature rather than a bug. My predecessor made the wise decision to chose a breakpoint where pushing wouldn't leave enough space to push the rest into. This translates directly to mobile.

![its_a_feature_not_a_bug](https://cloud.githubusercontent.com/assets/12717530/20632503/4ca041de-b33e-11e6-9581-6b0d1d34ed1c.gif)

**Comment by PVince81** [comment]
@felixheidecke close then ?

**Comment by felixheidecke** [comment]
Sure. I'll pick up on that behavior in an other issue.
