### ISSUE TITLE
Clicking detail action when the file is already open should not reload the sidebar

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#22488]
1. Sidebar for file is already open
2. Click the detail action again (or the area in the row which would trigger the sidebar)

Expected: Nothing happens.

What happens: There’s a reload of the sidebar content, which is quite confusing.

Similarly:
When the sharing tab is open, pressing Details should result in the »Activities« tab being opened. However, without reloading the whole content of the sidebar.

**Comment by nickvergessen** [comment]
Well then the user needs to do a hard page reload to load new comments, shares, activities, ...
Because there is no way to refresh the infos?

**Comment by jancborchardt** [comment]
They aren’t refreshed on chaning the tab or via a heartbeat?

**Comment by nickvergessen** [comment]
Not when changing the tab, and not all of them are in the tab section...

**Comment by PVince81** [comment]
moved to more general UX group ticket: https://github.com/owncloud/core/issues/27578
