### ISSUE TITLE
Announce support for setting the lastmodified in DAV header

### ISSUE THREAD

**Issue by ziotibia81** [owncloud/core#22499]
Hello,
in lasts version of ownclode there was some different ways to set mtime of file using propatch
(issue #15850 , #19737 ). So could be nice to annunce to DAV client support for setting the lastmodified in DAV header (dav: 1, 3, extended-mkcol) or another custom header.

**Comment by LukasReschke** [comment]
@DeepDiver1975 @dragotin @karlitschek Thoughts?

**Comment by PVince81** [comment]
It was always intended to be PROPPATCH on `lastmodified`. There was a version where it changed to `getlastmodified` but it was wrong as this property must be read-only as per webdav specs, so it was fixed to be the correct one again.

I wasn't aware that it was possible to advertise supported read-write properties in DAV headers ?

**Comment by PVince81** [comment]
@ziotibia81 is that part of any standard ? If yes, then it's cool because it could help ownCloud detect if remote DAV storages support this or not, for https://github.com/owncloud/core/pull/16688#issuecomment-182371464

**Comment by martinprikryl** [comment]
http://www.webdav.org/specs/rfc4918.html#HEADER_DAV

> The value is a comma-separated list of all compliance class identifiers that the resource supports. Class identifiers may be Coded-URLs or tokens (as defined by [RFC2616]). Identifiers can appear in any order. Identifiers that are standardized through the IETF RFC process are tokens, but other **identifiers SHOULD be Coded-URLs to encourage uniqueness.**

For example the Apache mod_dav uses Coded-URL `<http://apache.org/dav/propset/fs/1>` to announce support for `executable` property:

    DAV: 1,2
    DAV: <http://apache.org/dav/propset/fs/1>

**Comment by ziotibia81** [comment]
@PVince81 I think that @martinprikryl 's commet is really quite exhaustive... ;-)

**Comment by PVince81** [comment]
That's cool, setting to 9.1.

**Comment by PVince81** [comment]
I won't have time to look into this right now, but if you guys have an idea where to add this using the Sabre DAV APIs, please submit a pull request :smile:

**Comment by PVince81** [comment]
The best place to add this is likely to be the files plugin: https://github.com/owncloud/core/blob/v9.0.0beta2/apps/dav/lib/connector/sabre/filesplugin.php

However, I'm not sure what Sabre API to use from there to make.

**Comment by martinprikryl** [comment]
Override `ServerPlugin::getFeatures` to return something like `array("https://owncloud.org/dav/proppatch-lastmodified");`

See used of the method in [`CorePlugin::httpOptions`](https://github.com/fruux/sabre-dav/blob/6f7dfce310f3a873a71bcbddda5e1ec6740dc313/lib/DAV/CorePlugin.php#L210).

**Comment by PVince81** [comment]
Backlog for now. PRs welcome

**Comment by ziotibia81** [comment]
There are plans to have this feature early?

**Comment by PVince81** [comment]
No plans for now, this is not a priority. Feel free to implement this yourself (or find someone who does it) if this is important for your use cases
