### ISSUE TITLE
Certificate issue installing official bookmarks app

### ISSUE THREAD

**Issue by g4b0** [owncloud/core#22505]
1. On my brand new OC 8.2.2 I installed lot of apps (calendar, contacts, news, an so on)
2. When I try to install the official bookmarks app I get the following error: cURL error 60: SSL certificate problem: unable to get local issuer certificate
3. I copied the bookmarks folder in my 'app' directory, but nothing happens

### Server configuration
**Operating system**: Debian Jessie fully updated

**Web server:** Nginx 1.6.2

**Database:** Mysql 5.5.47

**PHP version:** 5.6.17

**ownCloud version:** 8.2.2

**Updated from an older ownCloud or fresh install:** fresh install

**List of activated apps:**

$ php occ app:list
Enabled:
  - activity: 2.1.3
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - documents: 0.11.1
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - news: 7.1.1
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - updater: 0.6
Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap

**The content of config/config.php:**

php occ config:list system
{
    "system": {
        "instanceid": "oc47oiayqajl",
        "dbtype": "mysql",
        "dbname": "owncloud",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED BY ME***"
        ],
        "datadirectory": "***REMOVED BY ME***",
        "overwrite.cli.url": "***REMOVED BY ME***",
        "version": "8.2.2.2",
        "logtimezone": "UTC",
        "installed": true,
        "appcodechecker": false,
        "mail_smtpmode": "smtp",
        "mail_from_address": "root",
        "mail_domain": "***REMOVED BY ME***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "127.0.0.1",
        "mail_smtpport": "25",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome (lastest on debian testing)

**Operating system:** Debian jessie

#### ownCloud log (data/owncloud.log)

"app":"core","message":"cURL error 60: SSL certificate problem: unable to get local issuer certificate","level":3,"time":"2016-02-18T13:49:04+00:00"

**Comment by LukasReschke** [comment]
Do you see any setup errors in the admin screen? Likely caused by an outdated cURL version which can't handle the redirects that the bookmarks app uses.

**Comment by g4b0** [comment]
The only error I can see is the one posted before: cURL error 60: SSL certificate problem: unable to get local issuer certificate

cURL is up to date in my system, here you are my versions:

```code
# dpkg -l | grep curl
ii  curl                           7.38.0-4+deb8u3               amd64        command line tool for transferring data with URL syntax
ii  libcurl3:amd64                 7.38.0-4+deb8u3               amd64        easy-to-use client-side URL transfer library (OpenSSL flavour)
ii  php5-curl                      5.6.17+dfsg-0+deb8u1          amd64        CURL module for php5
```

**Comment by hubertu** [comment]
Same problem here with oc 8.2.2, quite similar setup as described above.

**Comment by g4b0** [comment]
@LukasReschke what info do you need? I think that's a problem with the bookmarks app certificate, since other apps works well. @hubertu did you install other apps?

**Comment by hubertu** [comment]
to specify my case: I did an upgrade from 8.1 (?) to 8.2.2. I have a lot of other apps installed. If i try to upgrade the (not longer supported) Bookmarks App from 0.5 to 0.6, I get the error. No problems with other apps after oc upgrade.
installed apps:
`activity
bookmarks
calendar
contacts
documents
encryption
external
files
files_external
files_mv
files_pdfviewer
files_sharing
files_texteditor
files_trashbin
files_versions
files_videoviewer
files_w2g
firstrunwizard
gallery
galleryplus
news
notes
notifications
ownnote
provisioning_api
tasks
templateeditor
user_external
user_ldap
`

**Comment by JB1985** [comment]
Same here on Debian Jessie. Fresh Install of owncloud 8.2.2.

After i have put the bookmarks app in the apps folder manually, identify owncloud the app as "Experimental Apps".

**Comment by PVince81** [comment]
Some app links redirect to github and from what I remember, some curl versions don't properly check certificates in such situations.#

Have you tried upgrading your curl library and PHP curl module ?

**Comment by PVince81** [comment]
Closing due to lack of feedback
