### ISSUE TITLE
calendar migration skips ldap users

### ISSUE THREAD

**Issue by p5n** [owncloud/core#22508]
### Steps to reproduce
Upgrade from 8.2.2 -> 9.0beta1 with ldap backend enabled
1. sudo -u http ./occ upgrade
2. LDAP user's calendars are missing however users from oc_users table are ok

### Expected behaviour
All calendars migrated

### Actual behaviour
Only local DB user's calendars migrated from calendar to calendar-rework

### Server configuration
**Operating system**: Arch Linux

**Web server:** apache-2.4.18

**Database:** mariadb-10.1.11

**PHP version:** 7.0.3

**ownCloud version:** (see ownCloud admin page) 9.0beta1

**Calendar version:** (see ownCloud apps page) -0.8.2 -> -rework-1.0alpha2

**Updated from an older ownCloud or fresh install:** from 8.2.2

#### Workaround
1. Revert db
2. Copy all ldap users to oc_users
3. Do upgrade again
4. delete ldap users back from oc_users table

**Comment by DeepDiver1975** [comment]
@p5n Thanks a lot for testing this!

@blizzz @MorrisJobke yet another issue with user enumeration? ldap app no loaded on upgrade?

**Comment by PVince81** [comment]
@DeepDiver1975 when is that upgrade code running ?
If the LDAP app is loaded later then the user manager won't be available... this reminds me of that old issue: https://github.com/owncloud/core/pull/13865.

I thought it was solved already by making sure the user backend apps are loaded before the other ones at upgrade time ?

@blizzz

**Comment by PVince81** [comment]
Setting to critical because it could be an issue with app update order

**Comment by nickvergessen** [comment]
user_ldap is after calendar in the alphabet...

**Comment by blizzz** [comment]
@VicDeo since it's updating, does it refer to code parts you are involved in with regard to 9.0? If so, you might have a fix at hand? Otherwise it looks like we need to bring back life into #13865 indeed :speak_no_evil:

**Comment by DeepDiver1975** [comment]
> @VicDeo since it's updating, does it refer to code parts you are involved in with regard to 9.0? If so, you might have a fix at hand? Otherwise it looks like we need to bring back life into #13865 indeed :speak_no_evil:

@blizzz the new updater will start working oc9+ - the upgrade to 9 will be done via the traditional path. In addition the overall upgrade mechanism is handled in core.

Looks like we need to fix the app upgrade order asap ....

**Comment by p5n** [comment]
these 2 patches fix this issue

**Comment by DeepDiver1975** [comment]
> these 2 patches fix this issue

great - thx!
