### ISSUE TITLE
backgroundScan must ignore root storage

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#22501]
The `Scanner::backgroundScan` routine retrieves ALL mounts of the current user and rescans them.

It doesn't make sense to scan the root storage (data dir) in this case so it must be excluded.
This has resulted in issues in some envs where it would also scan all user's homes and store them in the root storage.

Additionally, we might also want to exclude the user's home storage and limit the scanning to external storages ?

@icewind1991 @LukasReschke @MorrisJobke @butonic

**Comment by PVince81** [comment]
This only seems to happen if there are already entries that have a size of "-1" inside the root storage.
You need to upgrade from 8.0 where occ files:scan ran once to have a few entries there.

**Comment by MorrisJobke** [comment]
Fix is in https://github.com/owncloud/core/pull/22565
