### ISSUE TITLE
On some platforms, an admin does not get the correct file permissions

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#22510]
### Steps to reproduce
1. Open your ownCloud on a rare BlackBerry 10 device
2. Log in as an admin
### Expected behaviour

I should be able to use the Files app and upload files, etc.
### Actual behaviour

I'm shown a message telling me that I don't have permission to upload or create files
As a side-effect, if you enable Gallery, the slideshow doesn't work properly because the files array doesn't contain any file IDs.

Due to the fact that this only happens on this platform, this should be considered a minor issue, but it could be related to a more serious problem regarding permissions.
### Server configuration

**Operating system**: Ubuntu 14.04

**Web server:** Apache

**Database:**

**PHP version:** 5.6

**ownCloud version:** master

**Updated from an older ownCloud or fresh install:** updated via `git pull`

**List of activated apps:**

none

**The content of config/config.php:**

```
  'loglevel' => 0,
  'theme' => '',
  'maintenance' => false,
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\JPEG',
    1 => 'OC\\Preview\\PNG',
    2 => 'OC\\Preview\\GIF',
    3 => 'OC\\Preview\\Postscript',
    4 => 'OC\\Preview\\Font',
  ),
  'preview_max_x' => 2048,
  'preview_max_y' => 2048,
  'debug' => true,
  'updatechecker' => 'false',
  'singleuser' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
```

**Are you using external storage, if yes which one:** smb

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Browser

**Operating system:** BlackBerry 10.3.2
### Logs

There is nothing relevant

**Comment by PVince81** [comment]
Weird. Since this is on master I'd have suspected that the Webdav PROPFIND request isn't done properly by the blackberry browser.

But then you said even gallery doesn't work, and that one doesn't use Webdav, does it ?

Would need debugging on the PHP side to see whether the requests are done properly by the browser.

**Comment by oparoz** [comment]
>Since this is on master I'd have suspected that the Webdav PROPFIND request isn't done properly by the blackberry browser.

I'll check the request

>But then you said even gallery doesn't work, and that one doesn't use Webdav, does it ?

It's the slideshow, because the file IDs are missing, so the app doesn't know which files to download.

**Comment by oparoz** [comment]
@PVince81 - I compared the PROPFIND response of a working config vs a non-working one and they're completely different...

### Working

```
<d:response>
  <d:href>/remote.php/webdav/pics/1280px-BaskaVoda13Chorvatsko.JPG</d:href>
  <d:propstat>
   <d:prop>
    <d:getlastmodified>Wed, 10 Feb 2016 02:32:16 GMT</d:getlastmodified>
    <d:getetag>&quot;f62c3498ad1afca5f308eb464363f1a6&quot;</d:getetag>
    <d:getcontenttype>image/jpeg</d:getcontenttype>
    <d:resourcetype/>
    <oc:fileid>298130</oc:fileid>
    <oc:permissions>RDNVW</oc:permissions>
    <d:getcontentlength>280951</d:getcontentlength>
    <oc:tags/>
    <oc:favorite></oc:favorite>
    <oc:comments-unread>0</oc:comments-unread>
    <oc:owner-display-name>admin</oc:owner-display-name>
   </d:prop>
   <d:status>HTTP/1.1 200 OK</d:status>
  </d:propstat>
  <d:propstat>
   <d:prop>
    <oc:size/>
   </d:prop>
   <d:status>HTTP/1.1 404 Not Found</d:status>
  </d:propstat>
 </d:response>
```

### Not working

```
<d:response>
  <d:href>/remote.php/webdav/pics/1280px-BaskaVoda13Chorvatsko.JPG</d:href>
  <d:propstat>
   <d:prop>
    <d:getlastmodified>Wed, 10 Feb 2016 02:32:16 GMT</d:getlastmodified>
    <d:getcontentlength>280951</d:getcontentlength>
    <d:resourcetype/>
    <d:getetag>&quot;f62c3498ad1afca5f308eb464363f1a6&quot;</d:getetag>
    <d:getcontenttype>image/jpeg</d:getcontenttype>
   </d:prop>
   <d:status>HTTP/1.1 200 OK</d:status>
  </d:propstat>
 </d:response>
```

**Comment by PVince81** [comment]
Is the request part from the blackberry the same ? I suspect that it might not be sending the request body at all... when you don't send a body with PROPFIND, you'll only get a list of default properties. (it's a Sabre thing).

Could be a browser compatibility thing...

**Comment by oparoz** [comment]
The request is exactly the same. I'm not sure why Sabre would act differently depending on the browser, but it could be a regression in Sabre 3.

**Comment by PVince81** [comment]
Can you double check the Blackberry requests' namespaces and aliases maybe ? Are they also the same ? (in case it's something subtle)

I grepped the Sabre code but didn't see anything related to blackberry like user agent detection.
Maybe something else is different, the headers.

I still don't see why it would influence the result.

**Comment by oparoz** [comment]
Everything is the same.

The 2 differences I can see in the Blackberry debugger:

* Transfer-Encoding:chunked
* Via:1.1 proxy.local (squid/3.5.14)

But that could be because the debugger presents information differently

**Comment by PVince81** [comment]
Still happening in 9.0.3 ?

**Comment by PVince81** [comment]
Closing due to lack of feedback
