### ISSUE TITLE
Performance regression on some propfinds requests.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#22519]
Comparison between 8.2.2 server and current master 9.0 beta 1.

![performance_test_master backup csvresults_8 2 2_2016-02-17 17-00-25 csv](https://cloud.githubusercontent.com/assets/9048796/13175323/f30d3228-d709-11e5-8cb7-27ab89614338.png)

Tests do 10 iterations each.

Special regression on DiscoverySingleDirectoryJob

which requests:

```
"<d:resourcetype/><d:getlastmodified/><d:getcontentlength/><d:getetag/><oc:id/><oc:downloadURL/><oc:dDC/><oc:permissions/>"
```

**Comment by PVince81** [comment]
This is suspicious. I don't see any valid reason why the discovery PROPFIND would need more time.

I suspect that there might be new Webdav plugins which logic kicks in even when not needed. (system tags, comments, tag reports, etc)

CC @icewind1991 @blizzz

**Comment by PVince81** [comment]
@SergioBertolinSG are there any received shared folder inside the test folder for the discovery ? (just asking because it could also have some impact)

**Comment by SergioBertolinSG** [comment]
@PVince81 not sure right now. 
@MorrisJobke perhaps knows.

**Comment by MorrisJobke** [comment]
> @SergioBertolinSG are there any received shared folder inside the test folder for the discovery ? (just asking because it could also have some impact)

No. There is no sharing involved. Only plain file upload/download via webdav

**Comment by blizzz** [comment]
> I suspect that there might be new Webdav plugins which logic kicks in even when not needed. (system tags, comments, tag reports, etc)

At least overhead is added. For every new plugin in apps/dav/lib/connector/sabre/ it is

* instantiated
* initialized
* handlers registered

However unnecessary extra operations (DB  access etc.) were not executed.

At least on the example of the comments plugin.

A profiler would provide more useful information.

**Comment by PVince81** [comment]
@SergioBertolinSG is this still an issue on 9.1 beta2 ?

**Comment by SergioBertolinSG** [comment]
> @SergioBertolinSG is this still an issue on 9.1 beta2 ?

Yes:

<img width="947" alt="screen shot 2016-06-29 at 11 28 32" src="https://cloud.githubusercontent.com/assets/9048796/16447389/a7f3855e-3dec-11e6-9cdc-0a5a32c4f743.png">

**Comment by PVince81** [comment]
@mrow4a FYI

**Comment by PVince81** [comment]
unless someone is actively looking at this -> backlog

**Comment by PVince81** [comment]
some separate work has been done to improve performance in 9.1 and 10.0, maybe it's solved already.

needs rechecking

**Comment by PVince81** [comment]
please try again with 10.0.4 and reopen if perf issue is still there, especially on the new dav endpoint.
