### ISSUE TITLE
Federated Sharing: Removing source account, the sharees keep on viewing the shares

### ISSUE THREAD

**Issue by jesmrec** [owncloud/core#22525]
### Steps to reproduce
1. UserA(serverA) shares "FileA" with UserB(serverB)
2. UserB accepts the share 
3. UserA account is removed

### Expected behaviour
UserB has not anymore in his file list "FileA"

### Actual behaviour
UserB sees in its file list "FileA" although the share does not already exist anymore. UserB can neither open nor delete "FileA" (any action on the file can be performed)

### Server configuration

ServerA:
{"installed":true,"maintenance":false,"version":"9.0.0.11","versionstring":"9.0 beta 1","edition":"Enterprise"}

ServerB:
{"installed":true,"maintenance":false,"version":"9.0.0.11","versionstring":"9.0 beta 1","edition":"Enterprise"}

**Comment by Dianafg76** [comment]
It also happens on the desktop

**Comment by jesmrec** [comment]
Related to this: the deletion of a source file in a re-share causes the same behaviour. 

- User1 shares User2, and User2 re-shares to User3 (all of them federated)
- User2 remove the file -> the actual and expected behaviours in User3 are the same as descripted.

**Comment by PVince81** [comment]
Works correctly in 9.1.0 / master. Navigating into the folder as recipient will trigger the detection that notices that the folder is not shared any more, then the folder gets deleted.

If it doesn't happen directly, might need to run cron to have it discard orphaned shares for deleted users.
