### ISSUE TITLE
Expose "file size pending" status via WebDAV

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#22532]
* having a folder that has the file size not determined yet (in Web UI this is shown as pending)
* the PROPFIND returns a size of 0 for these folders (which is incorrect) - `<d:quota-used-bytes>0</d:quota-used-bytes>`
* the client then also shows 0 (which is correct)

Is it possible to expose this?

@PVince81 The current web UI in master shows correctly the "Pending" - how is that done?

Tested on a 8.2.2 instance. Was noticed while debugging 00004617 - therefore I add @MTRichards here.

**Comment by PVince81** [comment]
The "Pending" is when the size is -1.

The web UI is using the "oc:size" property: https://github.com/owncloud/core/blob/master/core/js/files/client.js#L272

**Comment by MorrisJobke** [comment]
I tested: this is available in 8.2.2 and master - so this is clearly a client issue: https://github.com/owncloud/client/issues/4491
