### ISSUE TITLE
Invalid private key for encryption app. 

### ISSUE THREAD

**Issue by Domsen** [owncloud/core#22539]
### Steps to reproduce
1. Activate the app "Default encryption module".
2. Enable the server-side encryption at settings/admin.
3. Logout, Login. The error message appears at the top. 

### Expected behaviour
The encryption module should work fine. 

### Actual behaviour
The encryption module does not work. Can't upload files. Can't update my private key. Don't know how. With SQLite it works fine. But not with MySQL. 

### Server configuration
**Operating system**:
Raspbian

**Web server:**
nginx

**Database:**
MySQL 

**PHP version:**
PHP 5.6.17-0+deb8u1 (cli) (built: Jan 24 2016 12:25:22)

**ownCloud version:** (see ownCloud admin page)
8.2.2 (stable) 

**Updated from an older ownCloud or fresh install:**
fresh

**Signing status (ownCloud 9.0 and above):**
nothing wrong. Just load "index.php/apps/files/".

**List of activated apps:**
 Activity 2.1.3
 Default encryption module 1.1.0
 Deleted files 0.7.0
 First Run Wizard 1.1
 Gallery 14.2.0
 Mail Template Editor 0.1
 Notifications 0.1.0
 PDF Viewer 0.7
 Provisioning API 0.3.0
 Share Files 0.7.0
 Text Editor 2.0
 Updater 0.6
 Versions 1.1.0
 Video Viewer 0.1.3

**The content of config/config.php:**
Censored with [hidden]
<?php
$CONFIG = array (
  'instanceid' => '[hidden]',
  'passwordsalt' => '[hidden]',
  'secret' => '[hidden]',
  'trusted_domains' =>
  array (
    0 => '192.168.178.12',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'https://192.168.178.12',
  'dbtype' => 'mysql',
  'version' => '8.2.2.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_Admin',
  'dbpassword' => '[hidden]',
  'logtimezone' => 'UTC',
  'installed' => true,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
No, internal storage. (default)

**Are you using encryption:** yes/no
no, but I want. This is the reason for this report. 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### LDAP configuration (delete this part if not used)
Could not open input file: occ

### Client configuration
**Browser:**
Firefox 42.0

**Operating system:**
Windows 8.1

**Sum**
It works fine with SQLite. But not with MySQL.

**Comment by rullzer** [comment]
@schiesbn

**Comment by rullzer** [comment]
Is there anything in your log files?

**Comment by Domsen** [comment]
{"reqId":"YTQV+nvx+3AS8of5McSf","remoteAddr":"192.168.178.26","app":"no app in context","message":"Encryption module \"\" not found, file will be stored unencrypted (Default encryption module not loaded)","level":2,"time":"2016-02-20T13:00:12+00:00"}
{"reqId":"78VLmP2cG4Lsti9IdpS\/","remoteAddr":"192.168.178.26","app":"no app in context","message":"Encryption module \"\" not found, file will be stored unencrypted (Default encryption module not loaded)","level":2,"time":"2016-02-20T13:00:12+00:00"}
{"reqId":"qihUox\/C\/grErf0DxDJ2","remoteAddr":"192.168.178.26","app":"no app in context","message":"Encryption module \"\" not found, file will be stored unencrypted (Default encryption module not loaded)","level":2,"time":"2016-02-20T13:00:14+00:00"}

**Comment by blizzz** [comment]
@owncloud/encryption bug or config issue?   ^

**Comment by jknockaert** [comment]
You have to take two steps to activate encryption: install the app, and enable encryption in the admin settings.

**Comment by PVince81** [comment]
Closing due to lack of feedback.
Feel free to reopen if you're still having issues with v9.0.2.
