### ISSUE TITLE
Feedback for characters that are not allowed on some platforms during creation

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#22534]
Today I got a request to give the user feedback about not allowed characters on some platforms (like `:` which is fine on Linux but are not synced on Windows).

The idea is to somehow bring this up during creation time, to make spot this early.

I'm pretty unsure when and how this should happen: Showing it all the time could be annoying for users that know this limitation and are aware of it. On the other side it maybe reduces UX problems during sync before they arise. People maybe see the message and choose a different file name then.

cc @owncloud/designers for the UX aspect

@MTRichards because this is a feature request originating from 00004607

Any further objections or ideas for this?

[00004607](https://na25.salesforce.com/5003100000XZpIE)

**Comment by jancborchardt** [comment]
Yeah, we could use a tooltip – as soon as you type an unsupported character in the new file/folder or rename field, it will pop up and say something like:

> This file will not sync to Windows devices with the '$' in the name

(A bit shorter maybe) Does that make sense?

**Comment by MTRichards** [comment]
How about:
Files with a $ in the name will not sync to Windows.

**Comment by jancborchardt** [comment]
Yup, sounds good. And in place of the $ of course we show all the offending characters which were used in the name.

**Comment by ddeenniiss** [comment]
just to complete: with the spaces at the end of a directory (not allowed on windows)

**Comment by cdamken** [comment]
[00004607](https://na25.salesforce.com/5003100000XZpIE)

Also another discussion in: https://github.com/owncloud/enterprise/issues/1258

**Comment by cdamken** [comment]
@felixboehm @dragotin  Are we using this https://github.com/owncloud/enterprise/issues/1258 for this solution?

**Comment by cdamken** [comment]
Any news here?

**Comment by felixboehm** [comment]
Please reopen / open new issue with a clear issue and your expectations on how this should work.

**Comment by cdamken** [comment]
https://github.com/owncloud/core/issues/22534#issuecomment-218170191
