### ISSUE TITLE
Selection in files app broken

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#22531]
* click on the whitespace beside a file/folder
* sidebar should open
* click on the whitespace of another file/folder
* expected: sidebar for that file/folder should open
* actual: action (download for file, browse for folder) is executed

Current master f867762

@PVince81 regression in the files app

**Comment by PVince81** [comment]
Works for me on master f8677628d4ce9e47b1c7760291bb41d7d3cf6ed1

Were you in the "All files" list or another one ?
What did you do before these steps ? Did you select files with checkboxes or so ?

**Comment by MorrisJobke** [comment]
> Were you in the "All files" list or another one ?

Yes

> What did you do before these steps ?

Login :)

> Did you select files with checkboxes or so ?

No. Only the above steps. Tested in Chrome and Safari. Also with todays master present.

@PVince81 Feel free to ping me tomorrow and we could have a screen share to test this together.

**Comment by PVince81** [comment]
Did you clear your caches and changed the oil ?

**Comment by PVince81** [comment]
(still cannot reproduce it, even after relogging in and clearing the caches).

I uploaded some JPGs and when clicking on their rows, alternating between JPGs and welcome.txt, the sidebar stays open and its content updates.

I don't have any apps enabled, maybe it could be that ?

**Comment by MorrisJobke** [comment]
> I don't have any apps enabled, maybe it could be that ?

It was fixed by an update of the activity app to the latest master. There was a JS error.
