### ISSUE TITLE
Count Calendar and Contacts into Quota

### ISSUE THREAD

**Issue by aspdye** [owncloud/core#22538]
I think it would be a good Idea to count the users calendar and contacts into the Quota ;) 
We could make this optional with an function in the config.php like this:

`'count_db_stuff_to_quota' => true`

It would be interesting to handle all user-stuff in Database like Bookmarks, News, ... from the 3rdparty-Apps also with the Quota.

**Comment by RealRancor** [comment]
> No description provided.

*Please insert text here*

**Comment by RealRancor** [comment]
@aspdye Why do you think that it is a good idea to count maybe 2-5 MB contacts and calendar against the quota of a user?

**Comment by nickvergessen** [comment]
We would need an API to check the quota then and on each upload each other app would need to load to have a look how much the user has in other apps.

"Will not fix" for me, @DeepDiver1975

**Comment by DeepDiver1975** [comment]
> "Will not fix" for m

me too - the volume contacts and calendar information consume is to be ignored compared to e.g. pictures being stored in owncloud
