### ISSUE TITLE
8.2.2 Federated Sharing Problem

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#22533]
### Steps to reproduce
1. Create a new local owncloud user, lets name it "test_user"
2. Logon as "test_user" once and logoff again
3. Enable as admin external storage support, federated sharing, and using external storage support for users
4. Try to share a file or folder to test_user

### Expected behaviour
test_user@domain.xx should be found and usable as sharee

### Actual behaviour
1. test_user without the @domain.xx appendix is found and can be used
2. test_user@domain.xx: From the same owncloud instance: Freigabe von xxx fehlgeschlagen, da test_user@domain.xx nicht gefunden wurde. Möglicherweise ist der Server nicht erreichbar.
3. Same error message if you try from outside from another owncloud (I think it is 8.2) sharing a file or folder naming the remote user

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** nginx

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** (see ownCloud admin page)
8.2.2.

**Updated from an older ownCloud or fresh install:**
fresh install from scratch

**Signing status (ownCloud 9.0 and above):**

```
---
```

**List of activated apps:**

```
Enabled:
  - activity: 2.1.3
  - files: 1.2.0
  - files_external: 0.3.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - updater: 0.6
Disabled:
  - encryption
  - external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "xxxx",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "owncloud.xxx.xx"
        ],
        "datadirectory": "\var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/owncloud.xxx.xx",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Vienna",
        "installed": true,
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "assetdirectory": "\/var\/www\/owncloud",
        "asset-pipeline.enabled": true,
        "filesystem_check_changes": 1,
        "preview_max_scale_factor": 1,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Raw"
        ],
        "loglevel": 1
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
smb

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:** Opera

**Operating system:** W7x64

#### Web server error log
```
No errors logged when trying to share
```

#### ownCloud log (data/owncloud.log)
```
When trying to share:
Error	PHP	Array to string conversion at /var/www/owncloud/lib/private/template/functions.php#36
```

**Comment by mmattel** [comment]
If I do the same on my dev instance (ownCloud 9.0.0 beta 2 (git), master, updated some seconds ago), the spinner at the share recipient user@domain runs forwver, if I change the screen to eg "Administration", I get a webserver error logged:
```
2016/02/19 17:32:11 [error] 2401#2401: *5882 access forbidden by rule, client: 80.110.35.173, server: xx.xx.xx, request: "GET /data/.ocdata HTTP/2.0", host: "xx.xx.xx"
```
```
-rw-r-----  1 www-data www-data    0 Feb 19 17:28 .ocdata
```

**Comment by rullzer** [comment]
Are you by any chance using ssl? And if so a self signed certificate?

**Comment by mmattel** [comment]
I have disabled SSL and use TLS 1.x 
The certificate is from Letsencrypt

**Comment by mmattel** [comment]
OK, I found the problem. I am now able to use Federated Sharing.

Even I did what LE guidelines said, something was wrong with the nginx ssl certificate setup (would have hit imho the apache setup too). I will do a documentation PR to give some hints to avoid running into that issue.
