### ISSUE TITLE
Multithreading for sharing with encryption

### ISSUE THREAD

**Issue by Liwindo** [owncloud/core#22546]
### Steps to reproduce
1. Have the encryption-app enabled.
2. Share a folder with a lot data inside with a group or a user.

### Expected behaviour
All CPU-Cores are used for the process.

### Actual behaviour
Only one CPU-Core is used.

### Server configuration
**Operating system:** Ubuntu 14.04.4

**Web server:** apache with nginx proxy

**Database:** mysqli

**PHP version:** 7.0.3

**ownCloud version:** 8.2.2

**Comment by DeepDiver1975** [comment]
Tbh: it is good to not consume all cores. In a multiuser environment one operation shall never use all resources.
