### ISSUE TITLE
App Store shows no Apps

### ISSUE THREAD

**Issue by aspdye** [owncloud/core#22540]
### Steps to reproduce
1. Install BETA or DAILY BUILD 
2. Click on "+ Apps" to activate some new apps (like Calendar-Rework)
3. 

### Expected behavior
You should see the activated apps, the non-activated ones (and the categories of the App Store - not yet because it's a beta maybe)

### Actual behavior
You cannot see any apps. Also not the one you tried to install manually, or the ones already activated.
<img width="1240" alt="bildschirmfoto 2016-02-20 um 11 41 06" src="https://cloud.githubusercontent.com/assets/12893462/13196164/1582fbe0-d7c7-11e5-9875-1488880d8057.png">

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS
**Web server:**
Apache + Nginx Reserve Proxy
**Database:**
SQLite
**PHP version:**
7.0.3
**ownCloud version:** (see ownCloud admin page)
9.0.0 (DAILY BUILD and BETA)
**Updated from an older ownCloud or fresh install:**
fresh
**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
only the core-ones
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => 'domain.com',
  ),
  'datadirectory' => '/var/www/vhosts/domain.com/httpdocs/owncloud/data',
  'overwrite.cli.url' => 'http://domain.com/owncloud',
  'dbtype' => 'sqlite3',
  'version' => '9.0.0.12',
  'logtimezone' => 'UTC',
  'installed' => true,
);
```

**Are you using encryption:** yes/no
no

### Client configuration
**Browser:**
Safari
**Operating system:**
OS X El Capitan
#### ownCloud log (data/owncloud.log)
```
Error

no app in context

Exception: {"Exception":"DomainException","Message":"Contacts tables are missing. Nothing to do.","Code":0,"Trace":"#0 \/var\/www\/vhosts\/domain.com\/httpdocs\/owncloud\/apps\/dav\/lib\/migration\/migrateaddressbooks.php(55): OCA\\Dav\\Migration\\AddressBookAdapter->setup()\n#1 \/var\/www\/vhosts\/domain.com\/httpdocs\/owncloud\/apps\/dav\/appinfo\/application.php(178): OCA\\Dav\\Migration\\MigrateAddressbooks->setup()\n#2 \/var\/www\/vhosts\/domain.com\/httpdocs\/owncloud\/apps\/dav\/appinfo\/install.php(26): OCA\\Dav\\AppInfo\\Application->migrateAddressbooks()\n#3 \/var\/www\/vhosts\/domain.com\/httpdocs\/owncloud\/lib\/private\/installer.php(617): include('\/var\/www\/vhosts...')\n#4 \/var\/www\/vhosts\/domain.com\/httpdocs\/owncloud\/lib\/private\/installer.php(568): OC_Installer::includeAppScript('\/var\/www\/vhosts...')\n#5 \/var\/www\/vhosts\/domain.com\/httpdocs\/owncloud\/lib\/private\/installer.php(542): OC_Installer::installShippedApp('dav')\n#6 \/var\/www\/vhosts\/domain.com\/httpdocs\/owncloud\/lib\/private\/setup.php(370): OC_Installer::installShippedApps()\n#7 \/var\/www\/vhosts\/domain.com\/httpdocs\/owncloud\/core\/controller\/setupcontroller.php(64): OC\\Setup->install(Array)\n#8 \/var\/www\/vhosts\/domain.com\/httpdocs\/owncloud\/lib\/base.php(822): OC\\Core\\Controller\\SetupController->run(Array)\n#9 \/var\/www\/vhosts\/domain.com\/httpdocs\/owncloud\/index.php(39): OC::handleRequest()\n#10 {main}","File":"\/var\/www\/vhosts\/domain.com\/httpdocs\/owncloud\/apps\/dav\/lib\/migration\/addressbookadapter.php","Line":53}```

**Comment by RealRancor** [comment]
There where similar issues reported with memcached:

https://github.com/owncloud/core/issues/14185

But it seems you havn't enabled this?

**Comment by nickvergessen** [comment]
Can you have a look at the browser console? Because even "Enabled" and "Disabled" lists are missing and those two are not served by the app store.

**Comment by aspdye** [comment]
`Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
ReferenceError: oc_appconfig is not defined
 shareconfigmodel.js:24:4
TypeError: link is undefined
 js.js:203:1
getPreventDefault() sollte nicht mehr verwendet werden. Verwenden Sie stattdessen defaultPrevented. jquery.min.js:5:17117
TypeError: data.ocs is undefined`

**Comment by aspdye** [comment]
Solved with help of @LukasReschke :see_no_evil: Thank you very much. It was a problem with the nginx Short URL rules. Read more here: #22881
