### ISSUE TITLE
Cannot create subfolders in folder shared by link

### ISSUE THREAD

**Issue by ogasser** [owncloud/core#22545]
When I share a folder by link and allow editing, only the upload icon is shown and there is no way to create a subfolder.

![2016-02-21-234435_1920x1080_scrot](https://cloud.githubusercontent.com/assets/2095178/13206006/c84a6e6e-d8f5-11e5-828e-7fa2abfb34d2.png)

Instead of the upload icon I would expect to see the plus button here just like in files.

**Comment by jancborchardt** [comment]
Ah, this seems to be possible with current master (coming 9.0).

@PVince81 I thought this was a regression, but I assume we didn’t have it in 8.2 and before?
