### ISSUE TITLE
[Suggestion] Use Swagger for Owncloud API Documentation 

### ISSUE THREAD

**Issue by PatelParas** [owncloud/core#22547]
Why don't we consider to use Swagger(http://swagger.io/)  Which is industry standard API documentation format? https://github.com/OAI/OpenAPI-Specification

Now a day's The Open API Initiative (OAI) was created by a consortium of forward-looking industry experts who recognize the immense value of standardizing on how REST APIs are described. As an open governance structure under the Linux Foundation, the OAI is focused on creating, evolving and promoting a vendor neutral description format. SmartBear Software is donating the Swagger Specification directly to the OAI as the basis of this Open Specification.  
Many industry players accepted this standard format :
 e.g. 
Google 
Microsoft
ebay
paypal
https://apinf.io/
https://apigee.com/about/
Chef 
Demo URL : http://petstore.swagger.io/#/pet

if anyone up for this i would love to join..

**Comment by LukasReschke** [comment]
I already have lying around a very rough prototype for the sharing API here. It's not that much work to define the OCS rules within it but there are some caveats.

If I find some time I'll create a repository and we can talk there about it :smile: Having consumers for most programming languages is indeed something cool.

**Comment by PatelParas** [comment]
:+1:

**Comment by PVince81** [comment]
@rullzer looked into this at some point. Not sure where the example yaml file was.

Tricky part is to make Swagger work with Webdav.

**Comment by VinayaSathyanarayana** [comment]
Any updates on getting Share API on swagger?

**Comment by PVince81** [comment]
Feel free to contribute a yml spec file for Swagger. AFAIK we likely won't be able to use PHP annotations for that so it is likely a tedious manual process.

**Comment by noveens** [comment]
You can use Swagger API documentation for my JS Library (js-owncloud-client).
Link: https://github.com/noveens/js-owncloud-client

Here I have covered almost all of the existing OC APIs (both WebDAV and non-WebDAV).
To make the swagger spec, please follow the instructions given in the README.

If you have any further doubts, feel free!

**Comment by PVince81** [comment]
We won't be able to provide a full spec with Swagger because it's not compatible with Webdav and also likely cannot represent the tree-like structure of Webdav. Maybe another tool is needed.

As an alternative, someone could built a separate REST frontend for all these APIs (for example using https://github.com/noveens/js-owncloud-client)
