### ISSUE TITLE
Updater tries to update from 7.0.12 to 8.2.1 but fails

### ISSUE THREAD

**Issue by habakuk007** [owncloud/core#22544]
### Steps to reproduce
1. Run Owncloud 7.0.12
2. Use the integrated Updater
3. Owncloud is broken

### Expected behaviour
Updater should not try to upgrade if it is not possible to upgrade...

### Actual behaviour
Updater breaks owncloud

### Server configuration

**ownCloud version:** 7.0.12
**Updated from an older ownCloud or fresh install:** Update

**Comment by RealRancor** [comment]
Duplicate of https://github.com/owncloud/appstore-issues/issues/4
