### ISSUE TITLE
Incorrect message error when re-share without edit privilege

### ISSUE THREAD

**Issue by jesmrec** [owncloud/core#22553]
### Steps to reproduce
1. User1(serverA) share a file with User1(serverB) without edit permission
2. User1(serverB) accepts the share
3. User1(serverB) tries to share the file with User2(serverB)
### Expected behaviour

The following message should be displayed (or similar):

Cannot increase premissions of file.txt
### Actual behaviour

The following message is shown:

Cannot increase premissions of /user1/files/file.txt
### Server configuration

ServerB: {"installed":true,"maintenance":false,"version":"9.0.0.12","versionstring":"9.0.0 beta 2","edition":""}

**Comment by nasli** [comment]
Happens the same, full path is shown trying to reshare a file if resharing is not enabled on the server
"You are not allowed to share /user1/files/file.txt"

**Comment by PVince81** [comment]
Please reopen if still happening with 10.0.4
