### ISSUE TITLE
Too many mapping entries for system tag kill the DB server

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#22566]
### Steps to reproduce
1. Add files 1-1000 to tag X
2. Get files for tag X
3. Watch the server die :disappointed: 

### Expected behaviour
Server should not die and the API should have an option to get the list with a limit

### Actual behaviour
!(**Expected behaviour**)

@PVince81 as discussed

**Comment by PVince81** [comment]
We can try introducing pagination like for comments in that REPORT call.
