### ISSUE TITLE
Deleting a file from the trashbin via View/Node API leaves trashbin entry in DB

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#22564]
### Steps to reproduce
1. Delete a file so it's moved to the trashbin
2. Delete the trashed file via one of the APIs:

  ```php
  $view = new \OC\Files\View('/' . $user);
  $view->unlink('/files_trashbin/files/' . $file);
  ```
3. Check the trashbin table

### Expected behaviour
There should be no entry

### Actual behaviour
Entry is left 

### Server configuration
**ownCloud version:** 9.0

@schiesbn

**Comment by PVince81** [comment]
Works for me on master / 9.1.0.

Maybe you forgot to add the suffix with the timestamp ".d1466772552".
