### ISSUE TITLE
Calendar names can be enumerated

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#22578]
- Request a not existing calendar: `http://localhost/remote.php/dav/calendars/admin/NotExistingCalendar`

```xml
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>Node with name 'NotExistingCalendar' could not be found</s:message>
</d:error>
```

- Request an existing, not-shared, calendar:  `http://localhost/remote.php/dav/calendars/admin/existingcalendar`
```xml

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAVACL\Exception\NeedPrivileges</s:exception>
  <s:message>User did not have the required privileges ({DAV:}read) for path "calendars/admin/existingcalendar"</s:message>
  <d:need-privileges>
    <d:resource>
      <d:href>/remote.php/dav/calendars/admin/existingcalendar</d:href>
      <d:privilege>
        <d:read/>
      </d:privilege>
    </d:resource>
  </d:need-privileges>
</d:error>
```

(probably also affects the other endpoints, just reading through the code and testing)

<hr/>

From a security PoV we should not leak the existence of a calendar. Is there any CalDAV standard that prohibits this? It seems odd to me to leak the existence of such things.

cc @DeepDiver1975

**Comment by DeepDiver1975** [comment]
@LukasReschke what is the http status code in both cases? THX

**Comment by LukasReschke** [comment]
Not existing: 404
Existing but no permission to access: 403

**Comment by DeepDiver1975** [comment]
so - just based on this http status code it is already possible to determine if a calendar exists or not.

I guess this is quite valid for any api of any service out there to give the api user feedback on the error.
There is a difference between these two cases.

I honestly don't know how to fix this ....
... is this really an issue?

**Comment by cmonteroluque** [comment]
@LukasReschke moving this to 9.1, do you object?

**Comment by LukasReschke** [comment]
@cmonteroluque Yes.

**Comment by LukasReschke** [comment]
Proposed patch is at https://github.com/owncloud/core/pull/22731
