### ISSUE TITLE
[API] Pending share are deleted instead of being accepted

### ISSUE THREAD

**Issue by rperezb** [owncloud/core#22589]
Related to: https://github.com/owncloud/QA/issues/152

### Steps to reproduce
1.- check list of pending remote shares
```
curl -X GET http://USER:PASSWORD@HOST/ocs/v1.php/apps/files_sharing/api/v1/remote_shares/pending
```
Getting this as answer:
```xml
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message/>
 </meta>
 <data>
  <element>
   <id>28</id>
   <remote>SERVER</remote>
   <remote_id>4</remote_id>
   <share_token>FF1hnZ7zX9xqUhh</share_token>
   <name>/textfile..txt</name>
   <owner>admin</owner>
   <user>admin</user>
   <mountpoint>{{TemporaryMountPointName#/textfile..txt}}</mountpoint>
   <accepted>0</accepted>
  </element>
 </data>
```

2.- Try to accept the pending share using remote_id (Following documentation):
```
curl -X POST http://USER:PASSWORD@docker.oc.xxxx/ocs/v1.php/apps/files_sharing/api/v1/remote_shares/4
```

### Actual behaviour
This deletes the pending share, and it is not accepted.

### Expected behaviour
The share is accepted

### NOTE
This seems to be a bug or the docs are not right:
A POST request with /remote_shares/$remote_id deletes the pending share

@SergioBertolinSG @rullzer

**Comment by nickvergessen** [comment]
@rperezb the PyOCClient performs the POST on `remote_shares/pending/' + str(share_id)`
https://github.com/owncloud/pyocclient/blob/master/owncloud/owncloud.py#L669-L673

You seem to miss the `pending` part?

**Comment by nickvergessen** [comment]
I can not reproduce that the remote share is deleted.
I also receive `405 Method Not Allowed` on those urls (missing the `pending` part), but other then that I could not find a way to delete it with a POST.
Please confirm @SergioBertolinSG

**Comment by schiesbn** [comment]
I also tested it with the same results as @nickvergessen 

````
curl -X POST http://USER:PASSWORD@docker.oc.xxxx/ocs/v1.php/apps/files_sharing/api/v1/remote_shares/4
````

doesn't change anything and if I add `pending` to the path I can accept the share correctly:

````
curl -X POST http://USER:PASSWORD@docker.oc.xxxx/ocs/v1.php/apps/files_sharing/api/v1/remote_shares/pendig/4
````

**Comment by schiesbn** [comment]
@rperezb @SergioBertolinSG there is another mistake:

> 2.- Try to accept the pending share using remote_id (Following documentation):

you need to use the `id` to accept/decline remote shares

**Comment by SergioBertolinSG** [comment]
So documentation is not correct in this request, https://doc.owncloud.org/server/9.0/developer_manual/core/ocs-share-api.html

**Comment by SergioBertolinSG** [comment]
It should be added here https://github.com/owncloud/documentation/issues/2174

**Comment by nickvergessen** [comment]
yes @SergioBertolinSG bug in the docs: https://github.com/owncloud/documentation/pull/2191
