### ISSUE TITLE
When you have a Notifications, could be bigger the red spot

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/core#22585]
### Steps to reproduce

When you have a Notifications the red spot is a little small
![screen shot 2016-02-23 at 08 55 19](https://cloud.githubusercontent.com/assets/12032058/13245393/2085a9fa-da0d-11e5-8d18-c79718a57e87.png)

For example on Github the blue spot is bigger than in ownCloud

![screen shot 2016-02-23 at 08 55 38](https://cloud.githubusercontent.com/assets/12032058/13245415/475aee32-da0d-11e5-81a3-47b65e76e20a.png)

### Expected behaviour
It could be bigger red spot

### Server configuration
{"installed":true,"maintenance":false,"version":"9.0.0.12","versionstring":"9.0.0 beta 2","edition":""}

**Comment by rperezb** [comment]
@owncloud/designers

**Comment by MorrisJobke** [comment]
For relation:

<img width="440" alt="bildschirmfoto 2016-02-23 um 10 55 57" src="https://cloud.githubusercontent.com/assets/245432/13247902/173d4db2-da1c-11e5-9d4c-37460128343a.png">

**Comment by jancborchardt** [comment]
As per https://github.com/owncloud/notifications/pull/66 we will only show the icon if there _are_ notifications. So I think it’s fine for now. Also, I have to say the Github icon has a strange visual balance.
