### ISSUE TITLE
decryption fails on external WEBdav storage

### ISSUE THREAD

**Issue by jknockaert** [owncloud/core#22583]
A bit of a a weird issue. I mounted an external owncloud (7.something; probably enterprise; no encryption) storage using its nonshib webdav server interface on my community 8.2 server with encryption. So far so good, the external storage is accessible through the user interface. Then I upload a file. The (encrypted) file gets properly stored on the external storage, and the encryption keys are properly stored on my local storage. Nothing seems wrong so far. Then when I try to download the file again, decryption fails. It basically gets off track when it gets here: https://github.com/owncloud/core/blob/stable8.2/apps/encryption/lib/crypto/crypt.php#L432
So somehow the downloaded encrypted file is fed here without the final 'xx'. Note that the encrypted file in the external storage does have these 'xx' in the end. Not sure what happens here; it seems like only part of the encrypted file is fed into `removePadding`.
Then when I try to delete the file, that fails also. But no encryption error in that case, so may be unrelated.

**Comment by jknockaert** [comment]
@PVince81 @schiesbn Any idea?

**Comment by PVince81** [comment]
>  its nonshib webdav server interface

What's this ?

Did you use the "ownCloud" external storage type, not "Webdav" ?

**Comment by jknockaert** [comment]
OK, after upgrading today to OC9 I revisited this issue. So I have a stock community OC9 with encryption enabled. I try to mount an account on another owncloud server as external storage. As it happens, the external owncloud has been upgraded to OC 8.2.2 since I originally opened this issue. The external owncloud has shibboleth authentication (so it is probably a customised enterprise edition) with nonshib-webdav enabled to allow users to connect using a webdav client. So I use the webdav client of my OC9 to approach the external OC8.2 as external storage.
But it doesn't work. As far as I can see, the error is on the OC8.2 side. When my OC9 try to gets an encrypted file, the OC8.2 recognises the encryption, but with encryption disabled on the OC8.2 server, it refuses to serve the file. This behaviour is specific to the nonshib-webdav interface; the user interface does properly serve the encrypted file.
I'm afraid I cannot do much more debug work on my end.

**Comment by PVince81** [comment]
@jknockaert so you are using the "ownCloud" external storage type, not "Webdav", right ?
Because the "ownCloud" external storage has some special handling.

IIRC it will explicitly not double-encrypt files when storing them on the remote OC.

**Comment by jknockaert** [comment]
@PVince81 No, on the OC9 end I use "Webdav" external storage (so the webdav client). On the external OC8.2 end I use the nonshib webdav server described here: https://doc.owncloud.org/server/9.0/admin_manual/enterprise_user_management/user_auth_shibboleth.html#webdav-support

**Comment by jknockaert** [comment]
@PVince81 I actually tried to use the "ownCloud" external storage type, but it doesn't seem to support the Shibboleth authentication on the external owncloud.

**Comment by PVince81** [comment]
Wow, I never heard of non-shib Webdav before, CC @DeepDiver1975 

@jknockaert yeah, the "ownCloud" external storage assumes "remote.php/webdav" :frowning: 

If you like you could have a quick try changing the code of your OC9 instance and change this value https://github.com/owncloud/core/blob/v9.0.0/apps/files_external/lib/owncloud.php#L34 to the non-shib one and see if it works correctly. This, assuming that this is your only OC ext storage.

**Comment by jknockaert** [comment]
@PVince81 Using the trick works in the sense that it doesn't give errors. But it doesn't work in the sense that it simply results in disabling encryption. There seems to be a bug here as well: the external OC8.2 doesn't support encryption (because of Shibboleth authentication) and my OC9 doesn't encrypt either because it's leaving that to the external OC8.2.

**Comment by jknockaert** [comment]
@PVince81 I think you can remove the "needs info" label.

**Comment by PVince81** [comment]
Hmmm right. If using shib authentication, there is no password so encryption cannot work.
Unless 8.2 is modified to use the "master key" approach instead.

So what should we keep this bug about ? We see several issues:

1) Encryption not working with shib is a known issue and isn't fixable due to missing password.
2) The "ownCloud" external storage needs a checkbox "use shib endpoint" for this situation

Anything else ?

**Comment by jknockaert** [comment]
When I try to download an encrypted file (so encrypted by the OC9 server) from the OC8.2 server over the nonshib webdav server, I get the following xml (using Firefox):
```
<d:error><s:exception>Sabre\DAV\Exception\ServiceUnavailable</s:exception><s:message>Encryption not ready: Module with id: OC_DEFAULT_MODULE does not exist.</s:message></d:error>
```
So it seems like encryption is not enabled on the OC8.2 server (although a master key approach would work).
Main issue here is that the nonshib webdav server fails to serve externally encrypted files.

**Comment by PVince81** [comment]
> externally encrypted files

What do you mean by this ?

OC 8.2 should only encrypt files for OC 8.2. So when downloading a file to 9.0, it has to be decrypted by 8.2.
Whenever OC 9.0 writes a file to OC 8.2, it sends the file unencrypted, and the encryption is done by 8.2.

**Comment by jknockaert** [comment]
No, the setup is different. The OC9 server mounts the OC8.2 server as external storage. The OC8.2 has no encryption whatsoever. The OC9 server has encryption. So when using the OC9 server to save a file to the external storage, the OC9 server encrypts the file (when using "webdav" external storage type) and saves it on the OC8.2 server. But when retrieving the file, the OC8.2 nonshib webdav server simply refuses to serve the encrypted file (in its encrypted format), because it recognises the file being encrypted but fails to find the encryption module.
When mounting the external storage using the "owncloud" type (and with the nonshib hack implemented) the OC9 server sends the file unencrypted to the OC8.2 server. The OC8.2 server not having encryption, it doesn't encrypt the file either.
So I see two issues:
1. The nonshib webdav server fail to serve externally encrypted files when local encryption is disabled
2. The "owncloud" external storage type should have an option to force encryption on the local server for the where the external server is untrusted (that's basically the main use case for which OC encryption was designed)

**Comment by PVince81** [comment]
Okay, then in this case I'm assuming that the setup is intentional. You do want OC 9 to encrypt files when storing them to unencrypted 8.2.

And the 8.2 encryption wrapper mistakenly thinks it's supposed to be able to decrypt the file but it shouldn't, it must simply deliver the file as is. This is the bug.
We could rephrase it as "ownCloud server must deliver files as is, even if encrypted, when encryption is disabled" for this specific use case.

Trouble though, I think this was added as a security measure in case encryption was disabled during migration and to prevent sync clients to download encrypted files.

Maybe we need another flag of some sorts.

@schiesbn any thoughts ?

Slightly related, disabling encryption wrapper when encryption is off: https://github.com/owncloud/core/pull/23393.

**Comment by jknockaert** [comment]
@PVince81 Yes the setup is definitely intentional. Just one observation to add: the failure to serve externally encrypted files only happens to the (nonshib) webdav server. The encrypted files can be downloaded in their encrypted format when using the regular web interface of the OC8.2 server. So the issue seems to be with the webdav server rather than with the OC filesystem.

**Comment by PVince81** [comment]
I suspect that maybe the shib code somehow bypasses the encryption wrapper completely, so it doesn't get in the way.

**Comment by schiesbn** [comment]
I fear this is not that easy to fix... but I will have a look at it. The problem is that the ownCloud which stores the files refuses to provide a encrypted file if it can't be decrypted. That's bad in your case but makes sense in most other cases. E.g. the desktop client shouldn't download a encrypted file if can't be decrypted to avoid data lost on the desktop

**Comment by jknockaert** [comment]
Only WebDAV refuses to provide the encrypted file. The web interface does provide it. So it seems to be something specific to WebDAV.

**Comment by PVince81** [comment]
We found some cases recently where the class name of fed share / external storage was not detected properly. So it is likely that the code path that is supposed to disable encryption did not work.

Please try again with 10.0.4 where this is fixed.
