### ISSUE TITLE
Wizard is not using theme's slogan

### ISSUE THREAD

**Issue by Commenter123** [owncloud/core#22580]
### Steps to reproduce
1. Create a custom theme: Copy themes/example to themes/mytheme
2. Edit themes/mytheme/defaults.php and edit `getSlogan()` function (see below)
3. The wizard however still shows the default slogan "Your personal web services. All your files, contacts, calendar and more, in one place."

``` php
public function getSlogan() {
    return 'Hello world';
}
```

**Comment by LukasReschke** [comment]
@karlitschek @jancborchardt Should we adjust this? What is the expected behaviour here?

**Comment by Commenter123** [comment]
Expected behaviour is to show `Hello world` instead.
Looks like this is `true`: https://github.com/owncloud/firstrunwizard/blob/f50b1bbe64d2c9097199ae300376227247564b07/templates/wizard.php#L7

**Comment by karlitschek** [comment]
hmm. i think we should adjust that. what donyou think @jancborchardt?

**Comment by jancborchardt** [comment]
Hm … that sentence has nothing to do with the slogan though.

Regarding that people don’t read a lot of text – and there’s already a bunch of text in that wizard window – I’d rather cut the line entirely.

**Comment by PVince81** [comment]
Reopened in firstrunwizard app: https://github.com/owncloud/firstrunwizard/issues/69
