### ISSUE TITLE
Federated Sharing: resharing not allowed whitout edit permission

### ISSUE THREAD

**Issue by jesmrec** [owncloud/core#22587]
### Steps to reproduce
1. User1 (server1) shares a file with User2 (server2) without edit permission
2. User2 (server2) accepts the federated share
3. User2 (server2) wants to re-share the file with another user

### Expected behaviour
User2 can re-share the file if permissions do not exceed the granted ones.

### Actual behaviour
User2 can not re-share the file with anybody in his server or in other server, because its permissions on default exceed. Displayed message: 

" Can not increase permissions of file1"
(file with absolute path, related: https://github.com/owncloud/core/issues/22553)

### Server configuration

Server1: {"installed":true,"maintenance":false,"version":"9.0.0.12","versionstring":"9.0.0 beta 2","edition":""}

Server2: {"installed":true,"maintenance":false,"version":"9.0.0.12","versionstring":"9.0.0 beta 2","edition":""}

**Comment by rperezb** [comment]
ownCloud 9.0.0 beta 2 (daily) Build:2016-02-23T04:40:25+00:00 83d5080e78fa481db3855da8fcd75f624f8cac1c

**Comment by rullzer** [comment]
Aaaah warg... this is because we use the webdav properties... And there a mountpoint always has delete permissions... But we do not allow sharing with delete.. @PVince81 this is biting us again :(
