### ISSUE TITLE
occ files:scan --all doesn't scan external storages

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#22595]
### Steps

1. Setup a GDrive mount as "/gdrive" (system-wide)
1. Setup as SFTP mount as "/sftp" (system-wide)
1. Setup as S3 mount as "/s3" (system-wide)
1. Run "occ files:scan --all -v"

### Expected
Scanner also scans external storage

### Actual
Scanner only scans local files

I had to use `--path` with the path to the external storages to make it work.

### Versions
ownCloud 9.0 git master fae6643e6dd4bc308170e0ab45886f110f60a639

I believe this is a regression, especially that many rely on this feature to update their storages as a workaround for update detection.

**Comment by PVince81** [comment]
@icewind1991 @mmattel 

I'll try a quick debug later since I have it reproduced locally.

**Comment by mmattel** [comment]
Can´t test as I do not have GDrive or SFTP ect, SMB only
But FYI, the coding changes done were not related to the scan process itself but only to the behaviour of console output of the details. Scanning of SMB does work on my system with occ files:scan --all -v

**Comment by PVince81** [comment]
@mmattel with the latest master ?

I seem to remember seeing it sometimes working, sometimes not.
Sometimes you said it doesn't work and when I did, it did work.

There seems to be some random element there. Now that I have it failing, maybe I'll find what's wrong.

**Comment by PVince81** [comment]
Additional detail: `occ files:scan root -v` also doesn't work. Maybe the mount points are initialized properly.
Debugging now...

**Comment by mmattel** [comment]
The issues from thepast are fixed and I do not have something open here.
Tested with latest master today an works with smb flawless, example below, all smb.
```
...
File   /xxx/files/SMB/zzz.MOV

+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 530     | 18707 | 00:01:22     |
+---------+-------+--------------+
```

**Comment by PVince81** [comment]
Okay, I think I got it.

Actually I found this while testing https://github.com/owncloud/core/pull/22579 with external storages.
I believed it was broken on master but then it suddenly worked again on master.

Sorry for the noise.

**Comment by PVince81** [comment]
There is one problem though: in the case I tested there was an encryption exception, but it did not get displayed. This led the my confusion that there was a problem in the scan routine that made it ignore external storages. Would be good to log the exception here: https://github.com/owncloud/core/blob/master/apps/files/command/scan.php#L136

@mmattel does hitting ctrl+c also create an exception ? If yes, might need to split it into two catch blocks then.

**Comment by mmattel** [comment]
Yes it creates a exception. This is the best way to interupt the running scanning process. The exception thrown and catched here is a generic one. Maybe needed to ceate a particular one (global CtrlC exception) and do more specific catch blocks according the needs. The good thing on exceptions here is, that on any exception thrown you get the scan results processed and depending on the parameters these will be shown or not.

**Comment by PVince81** [comment]
@mmattel do you have time to make the change ?
It's fine if you don't, I'd then make a separate ticket for it. :smile:

**Comment by mmattel** [comment]
Please do the PR.
Need to prepare a company event in Spain, sorry.

**Comment by PVince81** [comment]
@mmattel no worries
