### ISSUE TITLE
Unable to scroll file list on shared folder

### ISSUE THREAD

**Issue by plinss** [owncloud/core#22606]
### Steps to reproduce
1. Create folder
2. Upload enough files to folder to require vertical scrolling
3. Share folder via link
4. View folder via share link
5. Attempt to scroll to see all files

### Expected behaviour
Should be able to scroll vertically to see all files

### Actual behaviour
Vertical scrolling only happens enough to reveal "ownCloud - web services under your control'" footer

### Server configuration
**Operating system**:
Debian 8

**Web server:**
Nginx

**Database:**
MariaDB

**PHP version:**
5.6.17-0

**ownCloud version:** (see ownCloud admin page)
8.2.2 (stable)

**Updated from an older ownCloud or fresh install:**
Updated from 8.1

**Signing status (ownCloud 9.0 and above):**
n/a

**List of activated apps:**
Enabled:
  - activity: 2.1.3
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - encryption: 1.1.0
  - files: 1.2.0
  - files_external: 0.3.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - provisioning_api: 0.3.0
  - tasks: 0.8.1
  - templateeditor: 0.1
Disabled:
  - external
  - notifications
  - user_external
  - user_ldap

**The content of config/config.php:**
{
    "system": {
        "instanceid": "ocd6tly2mdcn",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.linss.com"
        ],
        "datadirectory": "\/var\/www\/data",
        "overwrite.cli.url": "https:\/\/cloud.linss.com",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "cloud",
        "mail_smtpmode": "php",
        "mail_domain": "cloud.linss.com",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "session_lifetime": 86400,
        "maintenance": false,
        "appstore.experimental.enabled": true,
        "loglevel": 2,
        "theme": "",
        "trashbin_retention_obligation": "auto"
    }
}

**Are you using external storage, if yes which one:** l
No

**Are you using encryption:** 
yes

**Are you using an external user-backend, if yes which one:** 
No

### Client configuration
**Browser:**
Firefox, Safari

**Operating system:**
OSX

#### Web server error log
xxxx:xxxx:xxxx::16 - - [23/Feb/2016:02:47:18 -0800] "GET /index.php/s/AtYfxGezkSbyA8Z?path=%2FVlad HTTP/1.1" 200 16183 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0"
xxxx:xxxx:xxxx::16 - - [23/Feb/2016:02:47:18 -0800] "GET /index.php/core/js/oc.js?v=fee77f4d39feda7693d6890e1ac99e6f HTTP/1.1" 200 2250 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0"
xxxx:xxxx:xxxx::16 - - [23/Feb/2016:02:47:20 -0800] "GET /core/img/actions/download.svg HTTP/1.1" 200 320 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0"
xxxx:xxxx:xxxx::16 - - [23/Feb/2016:02:47:20 -0800] "GET /core/img/actions/delete.svg HTTP/1.1" 200 478 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0"
xxxx:xxxx:xxxx::16 - - [23/Feb/2016:02:47:20 -0800] "GET /core/img/logo-icon.svg HTTP/1.1" 200 2910 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0"
xxxx:xxxx:xxxx::16 - - [23/Feb/2016:02:47:20 -0800] "GET /core/fonts/OpenSans-Regular.woff HTTP/1.1" 200 20544 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0"
xxxx:xxxx:xxxx::16 - - [23/Feb/2016:02:47:20 -0800] "GET /core/fonts/OpenSans-Semibold.woff HTTP/1.1" 200 69888 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0"
xxxx:xxxx:xxxx::16 - - [23/Feb/2016:02:47:20 -0800] "GET /core/fonts/OpenSans-Light.woff HTTP/1.1" 200 62844 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0"
xxxx:xxxx:xxxx::16 - - [23/Feb/2016:02:47:20 -0800] "GET /core/img/breadcrumb.svg HTTP/1.1" 200 455 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0"
xxxx:xxxx:xxxx::16 - - [23/Feb/2016:02:47:20 -0800] "GET /core/img/actions/toggle-pictures.svg HTTP/1.1" 200 557 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0"
xxxx:xxxx:xxxx::16 - - [23/Feb/2016:02:47:21 -0800] "GET /index.php/apps/gallery/config.public?extramediatypes=1&token=AtYfxGezkSbyA8Z HTTP/1.1" 200 102 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0"
xxxx:xxxx:xxxx::16 - - [23/Feb/2016:02:47:21 -0800] "GET /core/img/filetypes/folder.svg HTTP/1.1" 200 662 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0"
xxxx:xxxx:xxxx::16 - - [23/Feb/2016:02:47:21 -0800] "GET /core/img/places/home.svg HTTP/1.1" 200 506 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0"
xxxx:xxxx:xxxx::16 - - [23/Feb/2016:02:47:21 -0800] "GET /core/img/breadcrumb.svg HTTP/1.1" 200 455 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0"
xxxx:xxxx:xxxx::16 - - [23/Feb/2016:02:47:21 -0800] "GET /index.php/apps/files_sharing/ajax/list.php?t=AtYfxGezkSbyA8Z&dir=%2FVlad&sort=name&sortdirection=asc HTTP/1.1" 200 7674 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0"
xxxx:xxxx:xxxx::16 - - [23/Feb/2016:02:47:21 -0800] "GET /core/img/actions/upload.svg HTTP/1.1" 200 331 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0"
xxxx:xxxx:xxxx::16 - - [23/Feb/2016:02:47:21 -0800] "GET /core/img/actions/more.svg HTTP/1.1" 200 660 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0"
xxxx:xxxx:xxxx::16 - - [23/Feb/2016:02:47:21 -0800] "GET /core/img/actions/checkbox.svg HTTP/1.1" 200 479 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0"
xxxx:xxxx:xxxx::16 - - [23/Feb/2016:02:47:21 -0800] "GET /core/img/filetypes/video.svg HTTP/1.1" 200 607 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0"
xxxx:xxxx:xxxx::16 - - [23/Feb/2016:02:47:21 -0800] "GET /core/img/actions/triangle-s.svg HTTP/1.1" 200 395 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0"
xxxx:xxxx:xxxx::16 - - [23/Feb/2016:02:47:21 -0800] "GET /core/img/actions/triangle-n.svg HTTP/1.1" 200 397 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0"

#### ownCloud log (data/owncloud.log)
{"reqId":"TKKJpaNUlXaMYHcsEALN","remoteAddr":"192.168.19.6","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#685","level":3,"time":"2015-08-29T13:29:15+00:00"}
{"reqId":"TKKJpaNUlXaMYHcsEALN","remoteAddr":"192.168.19.6","app":"PHP","message":"fopen(\/var\/www\/owncloud\/config\/config.php): failed to open stream: No such file or directory at \/var\/www\/owncloud\/lib\/private\/config.php#191","level":3,"time":"2015-08-29T13:29:15+00:00"}
{"reqId":"i2WmG\/rd7pBI9rFRngHg","remoteAddr":"192.168.19.6","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#685","level":3,"time":"2015-08-29T13:31:35+00:00"}

#### Browser log
Content Security Policy: Directive 'frame-src' has been deprecated. Please use directive 'child-src' instead. <unknown>
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://cloud.linss.com 'unsafe-eval'").

**Comment by LukasReschke** [comment]
Probably fixed in 8.2.3, mind testing https://github.com/owncloud/files_pdfviewer/pull/92? THX

**Comment by plinss** [comment]
Yes, that fixes it. Note there's a bunch of extra space between the last item and the footer though (but I'm not complaining).

**Comment by LukasReschke** [comment]
> Yes, that fixes it. Note there's a bunch of extra space between the last item and the footer though (but I'm not complaining).

Thanks. Yes, that's another bug, also on the todo list :-)
