### ISSUE TITLE
Some files can't be deleted with Webinterface; Sync error with same files with Client(Mac, Windows, Android)

### ISSUE THREAD

**Issue by beniroquai** [owncloud/core#22609]
### Steps to reproduce
1. Going to web-interface, deleting specific files, wait until the loading-cicrcle is done 
2. Refresh the page (F5), files reappear
3. Deleting them and recreate a file with same name solves the problem

### Expected behaviour
I delete the file and this gets synced to all clients.

### Actual behaviour
File reappears in Webgui, Sync-Client throws error. "Server replied: Service unavailable" or "INSTRUCTION_ERROR 6 "Das Element ist aufgrund vorheriger Fehler nicht synchronisiert: Error downloading https://XXX.XxX./X.. - server replied: Forbidden""

### Server configuration
No admin. Private Strato-Server. Owncloud 9.X. Fresh install. 
```
### Client configuration
**Browser:**
Chrome, Firefox

**Operating system:**
Windows 7 SP2; MAC

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here

02-24 07:47:15:434 0x47c6d68 OCC::SyncEngine::slotDiscoveryJobFinished: Permissions of the root folder:  "RDNVCK"
02-24 07:47:15:479 0x47c6d68 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "post treewalk" and starting new transaction
02-24 07:47:15:483 0x47c6d68 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "post stale entry removal" and starting new transaction
02-24 07:47:15:487 0x47c6d68 OCC::OwncloudPropagator::start: Using QNAM/HTTP parallel code path
02-24 07:47:15:488 0x47c6d68 OCC::SyncEngine::slotDiscoveryJobFinished: <<#### Post-Reconcile end ####################################################  122866
02-24 07:46:15:419 0x93d5a90 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0xf5df338) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
02-24 07:46:15:419 0x93d5a90 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0xf5df338) QObject(0x0)  0 false 3 0
02-24 07:46:18:525 0x93d5a90 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x973daf0) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
02-24 07:46:18:525 0x93d5a90 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x973daf0) QObject(0x0)  0 false 3 0
02-24 07:46:20:086 0x93d5a90 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x93d56b0) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
02-24 07:46:20:086 0x93d5a90 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x93d56b0) QObject(0x0)  0 false 3 0
02-24 07:47:16:081 0x47c6d68 OCC::Folder::slotSyncStarted: #### Propagation start #################################################### >>
02-24 07:47:16:082 0x47c6d68 OCC::SocketApi::slotUpdateFolderView: Not sending UPDATE_VIEW for "Masterarbeit" because status() is 3
02-24 07:47:16:084 0x47c6d68 OCC::ownCloudGui::slotSyncStateChange: Sync state changed for folder  "Masterarbeit" :  "Sync Running"
02-24 07:47:16:085 0x47c6d68 OCC::SyncEngine::slotItemCompleted: void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "2015-12-03 12.25.29.jpg" INSTRUCTION_ERROR 6 "Das Element ist aufgrund vorheriger Fehler nicht synchronisiert: Error downloading https://XXXXX.XXX/Masterarbeit/2015-12-03 12.25.29.jpg - server replied: Forbidden"

[....]

OCC::SyncEngine::slotItemCompleted: void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "Aufnahmen/Cell_sAPpx_15-RadiusIphoneLCD_100_530nm_500ms" INSTRUCTION_ERROR 6 "Das Element ist aufgrund vorheriger Fehler nicht synchronisiert: Error downloading https://XXXX/Cell_sAPpx_15-RadiusIphoneLCD_100_530nm_500ms - server replied: Forbidden"

I'm definitely not an expert, but this issue happened to me a while ago. I created a new User-account. Everything worked fine until I switched to the MAC. Could it be an encryption error? Any uncleaned lock-files or so? It is really anoying... Any idea? Thank you very much! I can't give any further details unless I'm not the servers admin. Sorry for that!

**Comment by LukasReschke** [comment]
Can you post the log from your ownCloud as well? This seems to be the client log.

**Comment by beniroquai** [comment]
Sorry, I was waiting for the admin, but he is in holidays :D..Sorry. Any ideas, what could cause the problem? As I've said, when deleting the folder in the web and recreating a file with the same name I can bypass the problem with the sync.

**Comment by PVince81** [comment]
@ben-denham 9.X isn't enough information. We need the full version because some fixes have gone in already since 12 days.

**Comment by PVince81** [comment]
Closing due to lack of feedback.
Feel free to reopen if you're still having issues with v9.0.2.
