### ISSUE TITLE
Chunked Files: Optimize checking if all chunks are there

### ISSUE THREAD

**Issue by guruz** [owncloud/core#22601]
(not proven 100%)

We've seen benchmarks (TODO: where) where we have seen that for chunked files the later chunks take longer and longer than the first chunks. We're thinking ```isComplete``` of ```OC_FileChunking``` is to be blamed because it checks the file system for the existance of all chunks for the file. This gets slower (? probably because a succesful stat takes more time) 

https://github.com/owncloud/core/blob/c5a200c4198de951dabdd3f783ade655b8ea6434/lib/private/filechunking.php#L76

One optimization idea: Have a fast path to check for ```currentChunk+1``` (if it has that many chunks) and if that does not exist then return immediatly as ```false``` instead of counting all chunks.

FYI @dragotin @DeepDiver1975 @jturcotte @ogoffart @rullzer

**Comment by ogoffart** [comment]
Client issue showing that the more chunk, the slower: https://github.com/owncloud/client/issues/4354

**Comment by PVince81** [comment]
> One optimization idea: Have a fast path to check for currentChunk+1 (if it has that many chunks) and if that does not exist then return immediatly as false instead of counting all chunks.

Sounds like a plan.

**Comment by rullzer** [comment]
PR already in #22602

**Comment by rullzer** [comment]
>> One optimization idea: Have a fast path to check for currentChunk+1 (if it has that many chunks) and if that does not exist then return immediatly as false instead of counting all chunks.
>
>Sounds like a plan.

After thinking about it we now just traverse the list from back to front (instead of front to back) and error out the moment we find 1 missing chunk.. But the idea is the same :)

**Comment by rullzer** [comment]
@PVince81 @cmonteroluque just FYI this helps with a blue ticket on the client.. so would 9.0.1 be an option? (PR is already available).

**Comment by PVince81** [comment]
done
