### ISSUE TITLE
Table comments_read_markers has no index

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#22622]
The table should have a unique index over uid, object_type and object_id

cc @blizzz

**Comment by blizzz** [comment]
Yes, same with the comments table, it was decision to postpone it when other stuff is done, so DB queries are known.

**Comment by nickvergessen** [comment]
Right, sounds good, but we should do that before final, because of performance on the queries and on a future update when there are thousands of comments already

**Comment by karlitschek** [comment]
I agree. We need the proper indexes. @DeepDiver1975 Do you have an overview over the different limitation of index lengths etc for different databases?

**Comment by blizzz** [comment]
Proposed keys here https://github.com/owncloud/core/pull/22638

Biggest key takes 388 bytes.

**Comment by nickvergessen** [comment]
Name length is 30, content length 700 something
