### ISSUE TITLE
OC_Installer::checkCode() is broken

### ISSUE THREAD

**Issue by kernins** [owncloud/core#22625]
Incorrect CodeChecker instantiation at lib/private/installer.php:570 (wrong NS and missing ctor arg)
OwnCloud 8.2.2

**Comment by LukasReschke** [comment]
https://github.com/owncloud/core/blob/v8.2.2/lib/private/installer.php#L570
https://github.com/owncloud/core/blob/v8.2.2/lib/private/app/codechecker/codechecker.php#L55-L58

Seems like a bug indeed.

**Comment by LukasReschke** [comment]
@karlitschek @DeepDiver1975 This is fixed in master with https://github.com/owncloud/core/pull/21730. Should that one get backported?

**Comment by LukasReschke** [comment]
Commit in question: https://github.com/owncloud/core/commit/1d0724a7729ebcc22d286a240eac7363f1bb37d4

**Comment by DeepDiver1975** [comment]
> @karlitschek @DeepDiver1975 This is fixed in master with #21730. Should that one get backported?

doesn't hurt from my pov

**Comment by DeepDiver1975** [comment]
@cmonteroluque adding this one to 8.2.4

**Comment by karlitschek** [comment]
Agreed. Please backport

**Comment by PVince81** [comment]
@DeepDiver1975 any update ? (it's assigned to you)

**Comment by PVince81** [comment]
Ok, looks like it's just a matter of doing the backport.

**Comment by PVince81** [comment]
I submit a PR with the commit to stable8.2, please have a look: https://github.com/owncloud/core/pull/22751

**Comment by PVince81** [comment]
Backport was done here: https://github.com/owncloud/core/pull/22751
