### ISSUE TITLE
Show who owns a file / uploaded a revision

### ISSUE THREAD

**Issue by h3ndrik** [owncloud/core#2263]
In shared folders there is no way to tell who uploaded a file.

The history of a file should include the timestamp and the uploader of every revision.

**Comment by jancborchardt** [comment]
Postponing to 8.2 I assume @schiesbn @PVince81?

**Comment by jancborchardt** [comment]
@schiesbn if we combine versions and the activity, having the display of who uploaded the version (who made the change) would already be there. cc @nickvergessen for Activity.

**Comment by nickvergessen** [comment]
Activity behaves like intended and does what it can.
