### ISSUE TITLE
Owncloud HHVM Login Not working any solutions?

### ISSUE THREAD

**Issue by royalterra** [owncloud/core#22631]
### Steps to reproduce
1.Install HHVM
2. Try to Login Owncloud
3. Session not transfer 

### Expected behaviour
Tell us what should happen
Need to Login but that never happens 
### Actual behaviour
Tell us what happens instead
Keep in the seam login page or say if I forgot my password
### Server configuration
**Operating system**:
Ubuntu 14.4 
**Web server:**
Apache 2.5 mod fastcgi hhvm
**Database:**
MAriaDb 10.01
**PHP version:**
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

**ownCloud version:** (see ownCloud admin page)
ownCloud 8.2.0 (stable)
**Updated from an older ownCloud or fresh install:**

Any idea I test with last version of Owncloud and this old version and none can't login . Any ideas hwo make works with HHVM
```

**Comment by LukasReschke** [comment]
HHVM is unsupported.

**Comment by RealRancor** [comment]
@LukasReschke Something for the documentation?

**Comment by DeepDiver1975** [comment]
> Something for the documentation?

afaik supported versions are listed ...

**Comment by RealRancor** [comment]
There is no notice of the keyword hhvm at the docs:

https://github.com/owncloud/documentation/search?q=hhvm

**Comment by DeepDiver1975** [comment]
> There is no notice of the keyword hhvm at the docs:

because we don't support it :wink:
