### ISSUE TITLE
Feature Request: OCC Change Password Using Hash

### ISSUE THREAD

**Issue by alphasierra59** [owncloud/core#22635]
I'm writing a script to synchronize the usernames and passwords between owncloud and another online service. The passwords are stored in a hashed form, but OCC only accepts passwords in plaintext. Can OCC be made to accept passwords in a hashed form? It would be preferable to having to generate a bunch of SQL commands.

**Comment by LukasReschke** [comment]
I don't see this happening. If you are synchronizing usernames and password like that you probably should implement your own login provider. (see for example user_ldap)
