### ISSUE TITLE
Federated shares not marked as shares if api disabled on server8

### ISSUE THREAD

**Issue by nasli** [owncloud/core#22643]
### Steps to reproduce
1.Server A share a folder with user in server B
2.Server B disabled share api

### Expected behaviour
User B see the folder and can see that this folder is shared with me

### Actual behaviour
User B can see the folder but is not shown as folder shared with me

Note:
Web with Server 9 works fine

### Server configuration
{"installed":true,"maintenance":false,"version":"8.2.2.2","versionstring":"8.2.2","edition":""}

**Comment by PVince81** [comment]
If it's fixed in 9.0 already then it's too low to qualify for a backport, closing.
