### ISSUE TITLE
OC9 Share by Link with "Enforce expiration date" return 403 through

### ISSUE THREAD

**Issue by javiergonzper** [owncloud/core#22642]
### Steps to reproduce
1. On "Allow users to share via link" mark "Set default expiry date 7 days" and mark "Enforce expiration date"
2. Using the Share API create a share by link of any file/folder

### Expected behaviour
The Share API should create a the share with the default expiration days.

### Actual behaviour
We receive this response: 
```
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>403</statuscode>
  <message>Expiration date is enforced</message>
 </meta>
 <data/>
</ocs>
```

### Server configuration

**ownCloud version:**
{"installed":true,"maintenance":false,"version":"9.0.0.13","versionstring":"9.0.0 beta 2","edition":""}

cc: @rperezb

**Comment by PVince81** [comment]
@rullzer please have a look

**Comment by jesmrec** [comment]
Related: after the server option "Set default expiration date" switches from enabled to disabled, the expiration date keeps on being requested.

**Comment by rullzer** [comment]
aaah yes... the joy of nested config settings...
I'll fix that after the merge as well.
