### ISSUE TITLE
Debian package only "Recommends" mysql or mariadb but not postresql

### ISSUE THREAD

**Issue by PanCakeConnaisseur** [owncloud/core#22645]
The debian package from the official owncloud repository has the Option "Recommends" which is set to :
mysql-server | mariadb-server, curl, exim4 | mail-transport-agent,
            owncloud-config-apache (= 8.2.2-1.1)
but imho should be :
mysql-server | mariadb-server** | postgresql**, curl, exim4 | mail-transport-agent,
            owncloud-config-apache (= 8.2.2-1.1)

Right now even if I want to use PostgreSQL and have already installed postgresql, still the mariadb-server gets installed. Although it is only a "Recommends" it is the default behavior for apt and aptitude to install all recommended packages.

### Steps to reproduce on Debian 8 Jessie
1. wget -nv https://download.owncloud.org/download/repositories/stable/Debian_8.0/Release.key -O Release.key
apt-key add - < Release.key
2. sh -c "echo 'deb http://download.owncloud.org/download/repositories/stable/Debian_8.0/ /' >> /etc/apt/sources.list.d/owncloud.list"
3. apt-get update
4. apt-get install owncloud

### Expected behavior
Owncloud installs without pulling mysql or mariadb server

### Actual behavior
Owncloud installation pulls in a lot of mysql packages:
mysql-common
libmysqlclient18
libdbd-mysql-perl
mysql-client-5.5
mysql-server-core-5.5
mysql-common
mysql-server-5.5
mysql-server
php5-mysqlnd
libmysqlclient18
libdbd-mysql-perl
mysql-client-5.5
mysql-server-core-5.5
mysql-server-5.5
mysql-server
php5-mysqlnd

### Server configuration
**Operating system**:
Debian 8 Jessie

**Web server:**
apache2-2.4.10-10+deb8u1

**Database:**
postgres-9.4+165

**PHP version:**
php5-5.6.14+dfsg-0+deb8u1

**ownCloud version:** (see ownCloud admin page)
owncloud-8.2.2-1.1

**Updated from an older ownCloud or fresh install:**
fresh install

**Comment by LukasReschke** [comment]
cc @jnweiger

**Comment by jnweiger** [comment]
It is "only" a Recommends. This is intentional, as we also support a remote database.
You can configure your apt-get to include or exclude 'Recommends' per default:
<pre>
cat > /etc/apt/apt.conf.d/01norecommend << EOF
APT::Install-Recommends "0";
APT::Install-Suggests "0";
EOF
</pre>
or add ``--no-install-recommends`` to your apt-get commands.

Adding postgresql as an alternative to mysql and mariadb is a good idea! Thanks for pointing this out.

**Comment by jnweiger** [comment]
Added to the control files for upcoming 8.2.x and 9.0 test releases.
Thanks!
