### ISSUE TITLE
FTP mount with wrong configuration does not let to browse to other menus

### ISSUE THREAD

**Issue by davitol** [owncloud/core#22651]
### Steps to reproduce

1. In admin menu, configure a FTP mount with wrong configuration

### Expected behaviour

It should be possible to browse to files view. A FTP mount red backcoloured should be shown. 

### Actual behaviour

It is not possible to browse to another menu. e.g. files view, users view etc

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 9.0.0 beta 2 (daily) Build:2016-02-25T04:15:38+00:00 faf65e73b778867d36f0e13dd1b0f1a4ef1f4723

### Logs

```
{"reqId":"11n5SflOZQo+52E4AOj3","remoteAddr":"82.159.139.58","app":"PHP","message":"stat(): stat failed for ftp:\/\/xxx:xxx@123.123.123\/ at \/opt\/owncloud\/apps\/files_external\/lib\/streamwrapper.php#126","level":3,"time":"2016-02-25T15:43:48+00:00"}
{"reqId":"bAYKo7oJcES3iAp+\/nUz","remoteAddr":"82.159.139.58","app":"PHP","message":"file_exists(): connect() failed: Connection timed out at \/opt\/owncloud\/apps\/files_external\/lib\/streamwrapper.php#73","level":3,"time":"2016-02-25T15:44:20+00:00"}
```

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** yes; S3.
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox for Mac OSX

![ftpdes](https://cloud.githubusercontent.com/assets/10596560/13325224/3ff92a8e-dbe1-11e5-8f0c-12adc85947b6.gif)

**Comment by PVince81** [comment]
Works for me. However I had to use "192.168.1.1" to make sure it fails early.
If I use "123.123.123" the spinner will run for several minutes, waiting for a timeout.

**Comment by davitol** [comment]
@PVince81 Just tested again with my host modified and it fails earlier as you said. So not sure if it is considered a bug or not. If it isn't feel free to close it.

**Comment by PVince81** [comment]
Not sure why it wouldn't let you switch to the files page... as far as I know there is no special logic to prevent you from leaving the page.

If this doesn't brick ownCloud / make it completely unusable, then we can reduce severity.
Can you confirm ?

**Comment by davitol** [comment]
Yes, let's reduce the severity. After a couple of minutes you can browse to the other menu. Even more, I've check with chrome browser and it works better. And if you delete the mountpoint, the server recovers its performance.

**Comment by davitol** [comment]
@PVince81 same behaviour in other oC menus
e.g. Loading users from an LDAP in users view and trying to browse to other menus before the load is completed

![escapeload](https://cloud.githubusercontent.com/assets/10596560/13456688/b0b7017e-e064-11e5-9f21-169ad2ae0e90.gif)

**Comment by PVince81** [comment]
@davitol this is probably because the avatar code is calling `setupFS` and `setupFS` might be trying to mount the external storages, and the FTP one is taking a looooooong time.

**Comment by PVince81** [comment]
CC @rullzer @icewind1991 maybe the avatar code shouldn't mount anything else but the user's home

**Comment by davitol** [comment]
@PVince81 

> might be trying to mount the external storages, and the FTP one is taking a looooooong time.

This behaviour I show you in my last comment was in other server with only an LDAP configured, external storage was not enabled. I posted it in this issue due to maybe the origin of cannot switch to the files page or other while loading could be the same

**Comment by PVince81** [comment]
@davitol if the web browser sent more than 5 ajax requests and they're all stalling for some reason, it might not attempt to do further requests until at least one of them returns.

**Comment by PVince81** [comment]
I don't think this is fixable, closing.
