### ISSUE TITLE
API shares root-folder without ID

### ISSUE THREAD

**Issue by xerc** [owncloud/core#22656]
1. does not responde with Database-ID in XML
2. does not list the shares via API nor WebClient
3. does not check for already created root-share

$ php occ --version
```
ownCloud version 8.2.2
```
$  curl "http://localhost/ocs/v1.php/apps/files_sharing/api/v1/shares" -k -u USER:PASS -X POST --data "shareType=3&path=/"
```
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message/>
 </meta>
 <data>
  <id>unknown</id>
  <url>http://localhost/index.php/s/CmgBjz5zLRB68Cc</url>
  <token>CmgBjz5zLRB68Cc</token>
 </data>
</ocs>
```
mysql> select * from oc_share;
```
| 6 | 3 | NULL | USER | NULL | folder | 45 | /45 | 45 | / | 1 | 1456418943 | 0 | NULL | k6sAsZYhPCSnqiT | 0 | @ 8.1.1
| 7 | 3 | NULL | USER | NULL | folder | 45 | /45 | 45 | / | 1 | 1456419030 | 0 | NULL | QMYDStNbc1JPagm | 0 | @ 8.1.1
| 8 | 3 | NULL | USER | NULL | folder | 45 | /45 | 45 | / | 1 | 1456423347 | 0 | NULL | CmgBjz5zLRB68Cc | 0 | @ 8.2.2
```

**Comment by rullzer** [comment]
In 9.0 you can 'cleanly' share your root folder.
But we should filter this out! Since you can't see it from the webUI etc.

@PVince81 @cmonteroluque FYI

**Comment by rullzer** [comment]
PR in #22660
