### ISSUE TITLE
Using Chrome as browser, secure ftps checkbox is not right located in External storage menu.

### ISSUE THREAD

**Issue by davitol** [owncloud/core#22655]
### Steps to reproduce

1. In admin menu, configure a FTP mount.

### Expected behaviour

 Secure ftps checkbox should be right located as it is in other browsers.

### Actual behaviour

 Secure ftps checkbox is not right located

Note: Clicking over the words  'secure ftps' checks/unchecks the option.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 9.0.0 beta 2 (daily) Build:2016-02-25T04:15:38+00:00 faf65e73b778867d36f0e13dd1b0f1a4ef1f4723

### Logs

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** yes; owncloud,FTP.
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome for Mac OSX Version 48.0.2564.116 (64-bit)

Chrome:
![screen shot 2016-02-25 at 18 03 38](https://cloud.githubusercontent.com/assets/10596560/13327738/6736df38-dbeb-11e5-9dc3-0e263dc2385e.png)

Firefox:

![screen shot 2016-02-25 at 18 11 13](https://cloud.githubusercontent.com/assets/10596560/13327676/39e3a5f2-dbeb-11e5-903c-2190794f0b25.png)

**Comment by davitol** [comment]
@owncloud/designers

**Comment by guruz** [comment]
WiP PR on #25120

**Comment by guruz** [comment]
This should be fixed.. :)
