### ISSUE TITLE
No WWW-authenticate response header for HTTP PUT API requests

### ISSUE THREAD

**Issue by martinrotter** [owncloud/core#22666]
NOTE: I reported this to news repo before. They said, I should report it here too.
### Steps to reproduce
1. Send ownCloud NEWS API request (for example via CURL).
2. Check HTTP answer.
3. No WWW-authenticate header inside the answer.
### Expected behaviour

The HTTP/401 response MUST include WWW-authenticate header to indicate the kind of desired auth method.
### Actual behaviour

When someone sends /items/star/multiple request without BASIC auth credentials, HTTP 401 response does not contain WWW-authenticate header.

**This is not standard behavior.** Server should always indicate which method of authentication it expects when authentication fails and 401 is returned. This literally breaks some existing libraries - for example Qt Network stack, where you have to explicitly append Authentication header and not to wait for server's answer. All API calls must return WWW-authenticate header when HTTP/401 response is returned.

From standard RFC 1945:

> 401 Unauthorized
> 
>  The request requires user authentication. The response must include
>  a WWW-Authenticate header field (Section 10.16) containing.......
### Server configuration

**Operating system**: Ubuntu 14.04

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 5.5

**ownCloud version:** (see ownCloud admin page) 8.2 whatever

**Updated from an older ownCloud or fresh install:** Official virtual image

**Comment by PVince81** [comment]
> 8.2 whatever

Make sure it's 8.2.2

@LukasReschke any idea about the auth header issue ?

**Comment by martinrotter** [comment]
Yea, its ownCloud 8.2.2-0.

https://bitnami.com/stack/owncloud/virtual-machine

**Comment by PVince81** [comment]
@LukasReschke isn't the news API using REST ? Reminds me of the cookie problem with the thumbnail API.

@martinrotter you could try with this patch: https://github.com/owncloud/core/pull/22901

**Comment by martinrotter** [comment]
@PVince81 No way to test it, sorry. I used the official virtual image.

**Comment by PVince81** [comment]
Okay here we go, some more detailed steps to reproduce:

1. Download and setup the bitnami VM https://bitnami.com/stack/owncloud/virtual-machine (make sure to set bridge adapter)
1. Enable the news app
1. `curl -D - 'http://192.168.177.229/index.php/apps/news/settings' -X PUT -H 'Content-Type: application/json;charset=UTF-8' --data-binary '{"language":"en","showAll":true,"compact":false,"oldestFirst":false,"compactExpand":false,"preventReadOnScroll":false}' `

```
HTTP/1.1 401 Unauthorized
Date: Wed, 16 Mar 2016 15:53:54 GMT
Server: Apache
X-Powered-By: PHP/5.5.30
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Pragma: no-cache
Cache-Control: no-cache, must-revalidate
Content-Security-Policy: default-src 'none';script-src 'self' 'unsafe-eval';style-src 'self' 'unsafe-inline';img-src 'self' data: blob:;font-src 'self';connect-src 'self';media-src 'self'
Set-Cookie: oc9s63fwa82f=4uvld3da234trflbini6djrqs2; path=/; HttpOnly
Set-Cookie: oc_sessionPassphrase=FGn6OYmXr1iejSyZpYIhDkWCQuo7MRBa34xcnbX73CoMF6f5hhwjH6jKmma1wSjlA4Z%2FOIeYmM0AbdQ4SkSKs7H6BDbrVFvgL3PRBMNTBJIsSyRaxnBjVgsioBK1IZpT; path=/; httponly
X-Frame-Options: SAMEORIGIN
Vary: Cookie
Content-Length: 43
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Robots-Tag: none
Content-Type: application/json; charset=utf-8

{"message":"Current user is not logged in"}
```

There are no authorization headers.

I tried the same on a local v8.2.2 instance:
```
curl -D - 'http://192.168.177.229/index.php/apps/news/settings' -X PUT -H 'Content-Type: application/json;charset=UTF-8' --data-binary '{"language":"en","showAll":true,"compact":false,"oldestFirst":false,"compactExpand":false,"preventReadOnScroll":false}'
HTTP/1.1 401 Unauthorized
Date: Wed, 16 Mar 2016 15:58:31 GMT
Server: Apache/2.4.18 (Linux/SUSE)
X-Powered-By: PHP/5.6.17
Set-Cookie: ockbfur1449k=u5v42kge9nn8f5jm39c4fbg4mv6226au66s63ovhphc4hqecqu40; path=/owncloud; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: oc_sessionPassphrase=UXxPbHDIcxvwKhIFL4VELJiJs%2Fjh3NUfd0lunEbKkPp6OXXXKhzIfkJdNjrCBnq3VxDbPRR7QoXl1%2BfdH3sHgS%2BBltrNc%2BxuGMRgs16QpUG%2FjGImM9j7dv1CLygrKCSP; path=/owncloud; httponly
Content-Security-Policy: default-src 'none';script-src 'self' 'unsafe-eval';style-src 'self' 'unsafe-inline';img-src 'self' data: blob:;font-src 'self';connect-src 'self';media-src 'self'
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: Sameorigin
X-Robots-Tag: none
Content-Length: 43
Content-Type: application/json; charset=utf-8

{"message":"Current user is not logged in"}
```

Also no authenticate header.

With Webdav however:
```
HTTP/1.1 401 Unauthorized
Date: Wed, 16 Mar 2016 15:59:39 GMT
Server: Apache
X-Powered-By: PHP/5.5.30
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *
WWW-Authenticate: Basic realm="ownCloud"
Set-Cookie: oc9s63fwa82f=ac8g6pcj2ps4o2i174elhbaod2; path=/; HttpOnly
Set-Cookie: oc_sessionPassphrase=lm8vtLy%2BYUPJjz8rUlwUJtaw6pxB31AvIWfJxl0xuqkPz9TJ68Y2cOOlw%2FZMZE8nSo%2BKHV%2F149DvSakCYwenxbYDvsD20A5k%2FP%2Ba1TOtw2BH3eyr6JzIevx02vJe%2FYHR; path=/; httponly
X-Frame-Options: SAMEORIGIN
Vary: Cookie
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Robots-Tag: none
Transfer-Encoding: chunked
Content-Type: application/xml; charset=utf-8

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
  <s:message>No basic authentication headers were found</s:message>
</d:error>
```

@BernhardPosselt @LukasReschke is the app framework missing something ?

**Comment by PVince81** [comment]
Also missing on GET requests.

I tried OC 8.0 and there is no such header either.

So it looks like this was never implemented in the first place ?

**Comment by LukasReschke** [comment]
> So it looks like this was never implemented in the first place ?

ACK. => Feature request.
