### ISSUE TITLE
Calendar: Shared Calendars Aren't Visible After Upgrading From 8.2.2 -> 9.0.0{beta2,RC1,final}

### ISSUE THREAD

**Issue by uli-heller** [owncloud/core#22678]
### Steps to reproduce
1. start with owncloud 8.2.2 and the standard calendar
2. UserB: create some calendars and share them
3. UserA: create a personal calendar
4. UsarA: looking at the calendar page within 8.2.2, it looks pretty crowded. I see my personal calendar and lots of shared calendars
5. upgrade to 9.0beta2
6. upgrade the calendar to calendar-rework-1.0-alpha2

### Expected behaviour
Similar to 8.2.2 - I extected to see all the calendars.

### Actual behaviour
UserA: I'm seeing only my personal calendar. It doesn't seem possible to access the other calendars.

### Server configuration
**Operating system**:
Ubuntu14.04

**Web server:**
Apache2.4.7

**Database:**
MariaDB-5.5

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
ownCloud 9.0.0 beta 2 (testing)

**Updated from an older ownCloud or fresh install:**
8.2.2

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
root@owncloud9:/var/www/owncloud9# sudo -u www-data php occ app:list
sudo: unable to resolve host owncloud9
Enabled:
  - activity: 2.2.1
  - calendar: 0.82
  - comments: 0.2
  - dav: 0.1.4
  - federatedfilesharing: 0.1.0
  - files: 1.4.3
  - files_pdfviewer: 0.7
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.3.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - federation
  - files_external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
root@owncloud9:/var/www/owncloud9# sudo -u www-data php occ config:list system
sudo: unable to resolve host owncloud9
{
    "system": {
        "instanceid": "oc481dt7ire4",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "internal.daemons-point.com",
            "83.236.132.110",
            "10.2.100.166",
            "192.168.0.199",
            "192.168.0.195"
        ],
        "datadirectory": "\/srv\/owncloud-data",
        "overwrite.cli.url": "https:\/\/internal.daemons-point.com\/owncloud9",
        "dbtype": "mysql",
        "version": "9.0.0.12",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "apps_paths": [
            {
                "path": "\/var\/www\/owncloud9\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/owncloud9\/apps-local",
                "url": "\/apps-local",
                "writable": true
            }
        ],
        "loglevel": 2,
        "theme": "",
        "maintenance": false,
        "trashbin_retention_obligation": "auto"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Chrome, Version 48.0.2564.116 (64-bit)

**Operating system:**
Ubuntu-14.04

#### ownCloud log (data/owncloud.log)
```
{"reqId":"742d2422fbf1dcf362edbd10bc8cd150","remoteAddr":"10.2.2.1","app":"PHP","message":"DateTimeZone::__construct(): Unknown or bad timezone (W. Europe) at \/var\/www\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Sabre\/VObject\/TimeZoneUtil.php#412","level":3,"time":"2016-02-11T12:33:55+00:00"}
{"reqId":"152c4f03f97ba14c57011e78ca073345","remoteAddr":"10.2.2.1","app":"PHP","message":"Undefined index:  at \/var\/www\/owncloud\/apps-local\/calendar\/templates\/part.showevent.php#52","level":3,"time":"2016-02-11T12:34:18+00:00"}
{"reqId":"152c4f03f97ba14c57011e78ca073345","remoteAddr":"10.2.2.1","app":"PHP","message":"Illegal offset type at \/var\/www\/owncloud\/apps-local\/calendar\/templates\/part.showevent.php#134","level":3,"time":"2016-02-11T12:34:18+00:00"}
{"reqId":"152c4f03f97ba14c57011e78ca073345","remoteAddr":"10.2.2.1","app":"PHP","message":"Illegal offset type at \/var\/www\/owncloud\/apps-local\/calendar\/templates\/part.showevent.php#159","level":3,"time":"2016-02-11T12:34:18+00:00"}
{"reqId":"152c4f03f97ba14c57011e78ca073345","remoteAddr":"10.2.2.1","app":"PHP","message":"Illegal offset type at \/var\/www\/owncloud\/apps-local\/calendar\/templates\/part.showevent.php#172","level":3,"time":"2016-02-11T12:34:18+00:00"}
{"reqId":"152c4f03f97ba14c57011e78ca073345","remoteAddr":"10.2.2.1","app":"PHP","message":"Illegal offset type at \/var\/www\/owncloud\/apps-local\/calendar\/templates\/part.showevent.php#185","level":3,"time":"2016-02-11T12:34:18+00:00"}
{"reqId":"152c4f03f97ba14c57011e78ca073345","remoteAddr":"10.2.2.1","app":"PHP","message":"Illegal offset type at \/var\/www\/owncloud\/apps-local\/calendar\/templates\/part.showevent.php#198","level":3,"time":"2016-02-11T12:34:18+00:00"}
{"reqId":"152c4f03f97ba14c57011e78ca073345","remoteAddr":"10.2.2.1","app":"PHP","message":"Illegal offset type at \/var\/www\/owncloud\/apps-local\/calendar\/templates\/part.showevent.php#211","level":3,"time":"2016-02-11T12:34:18+00:00"}
```

**Comment by LukasReschke** [comment]
cc @DeepDiver1975

**Comment by PVince81** [comment]
Didn't we fix this recently already ? @nickvergessen

**Comment by DeepDiver1975** [comment]
@uli-heller are the shared calendars visible via webdav? Please connect via e.g. cadaver to see if the calendar exists.

reading the error message I suspect some issue the calendar app - @georgehrke can you please have a look? THX

**Comment by georgehrke** [comment]
> reading the error message I suspect some issue the calendar app

`part.showevent.php` was part of the legacy calendar app and doesn't exist anymore. Can't judge whether this is a server side or client side issue from the logs.

**Comment by DeepDiver1975** [comment]
> part.showevent.php was part of the legacy calendar app and doesn't exist anymore. Can't judge whether this is a server side or client side issue from the logs.

thx

**Comment by uli-heller** [comment]
Am 02.03.2016 um 16:41 schrieb Thomas Müller:
>
> @uli-heller <https://github.com/uli-heller> are the shared calendars 
> visible via webdav? Please connect via e.g. cadaver to see if the 
> calendar exists.
>
> reading the error message I suspect some issue the calendar app - 
> @georgehrke <https://github.com/georgehrke> can you please have a 
> look? THX
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/owncloud/core/issues/22678#issuecomment-191292245>.
>

Unfortunately no, the calendars aren's visible via webdav.
I tried via cadaver and thunderbird. For both, I can see the
calendars using owncloud8 urls and I don't see the
calendars using owncloud9 urls.

Best regards, Uli

-- 
Uli Heller

daemons point Gesellschaft für Datenverarbeitung mbH
Zahn-Nopper-Straße 1-3, 70435 Stuttgart
Internet: www.daemons-point.com
Tel:+49 711 806708 0, Fax: +49 711 806708 19
mailto:uli.heller@daemons-point.com

Geschäftsführer: Steffen Walter, Uli Heller
Sitz der Gesellschaft: Stuttgart
Amtsgericht Stuttgart, HRB 22333

**Comment by nickvergessen** [comment]
Can you post your URLs, just to be sure? (You can also remove the domain, but the rest is important)

**Comment by uli-heller** [comment]
Am 03.03.2016 um 09:42 schrieb Joas Schilling:
>
> Can you post your URLs, just to be sure? (You can also remove the 
> domain, but the rest is important)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/owncloud/core/issues/22678#issuecomment-191654480>.
>

These are the URLs:

* 
https://internal.daemons-point.com/owncloud/remote.php/caldav/calendars/uli/feiertage_shared_by_jplatzer
    ... this is the one I've taken from owncloud 8

* 
https://internal.daemons-point.com/owncloud9/remote.php/caldav/calendars/uli/feiertage_shared_by_jplatzer
    ... this is the one I've made up for owncloud 9 (since I don't see 
the calendar, I cannot grab the caldav url there)

Best regards,
Uli

-- 
Uli Heller

daemons point Gesellschaft für Datenverarbeitung mbH
Zahn-Nopper-Straße 1-3, 70435 Stuttgart
Internet: www.daemons-point.com
Tel:+49 711 806708 0, Fax: +49 711 806708 19
mailto:uli.heller@daemons-point.com

Geschäftsführer: Steffen Walter, Uli Heller
Sitz der Gesellschaft: Stuttgart
Amtsgericht Stuttgart, HRB 22333

**Comment by DeepDiver1975** [comment]
@uli-heller can you connect with cadaver to the oc9 caldav endpoint?

https://internal.daemons-point.com/owncloud9/remote.php/caldav

**Comment by uli-heller** [comment]
Am 03.03.2016 um 17:30 schrieb Thomas Müller:
>
> @uli-heller <https://github.com/uli-heller> can you connect with 
> cadaver to the oc9 caldav endpoint?
>
> https://internal.daemons-point.com/owncloud9/remote.php/caldav
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/owncloud/core/issues/22678#issuecomment-191839720>.
>
Yes, this works:

```
uli@ulidesktop:~$ cadaver
dav:!> open https://internal.daemons-point.com/owncloud9/remote.php/caldav
Authentication required for sabre/dav on server 
`internal.daemons-point.com':
Username: XXX
Password: YYY
dav:/owncloud9/remote.php/caldav/> ls
Listing collection `/owncloud9/remote.php/caldav/': succeeded.
Coll:   calendars                              0  Jan  1  1970
Coll:   principals                             0  Jan  1  1970
```

-- 
Uli Heller

daemons point Gesellschaft für Datenverarbeitung mbH
Zahn-Nopper-Straße 1-3, 70435 Stuttgart
Internet: www.daemons-point.com
Tel:+49 711 806708 0, Fax: +49 711 806708 19
mailto:uli.heller@daemons-point.com

Geschäftsführer: Steffen Walter, Uli Heller
Sitz der Gesellschaft: Stuttgart
Amtsgericht Stuttgart, HRB 22333

**Comment by DeepDiver1975** [comment]
Can you cd into calendars/uli and the ls? THX

**Comment by uli-heller** [comment]
```
dav:/owncloud9/remote.php/caldav/> cd calendars/uli
dav:/owncloud9/remote.php/caldav/calendars/uli/> ls
Listing collection `/owncloud9/remote.php/caldav/calendars/uli/': succeeded.
Coll:   inbox                                  0  Jan  1  1970
Coll:   outbox                                 0  Jan  1  1970
```

**Comment by DeepDiver1975** [comment]
hmmm .... looks like the calendar migration did not run

Can you pelase run

```sh
./occ dav:migrate-calendars uli

**Comment by DeepDiver1975** [comment]
The command will only be available if you set debug to true in config.php

**Comment by uli-heller** [comment]
```
root@owncloud9:/var/www/owncloud9# sudo -u www-data ./occ dav:migrate-calendars uli
sudo: unable to resolve host owncloud9
Start migration for uli
```

Unfortunately, nothing changed. I've also executed the command against the users who created the shared calendars I'd like to see, but also no effect. Stopping and starting apache didn't help either.

Maybe I didn't do the migration correclty at all? I think I

* activated the maintenance mode
* stopped the apache
* renamed the old application folder from owncloud to owncloud-8.2.2
* extracted the new version
* copied the config.php from the old version
* extracted the new calendar app into .../owncloud/apps-local
* `occ upgrade`
* deactivated the maintenance mode
* `mv owncloud owncloud9`
* did some changes within config.php (owncloud->owncloud9)
* did some changes to the apache config (owncloud->owncloud9)
* started the apache

From my perspective, everything is fine except the calendars ;)

**Comment by uli-heller** [comment]
I did some more tests:

* when I look at my personal calender, it is shared. The name of the groups are displayed
* when I unshare and reshare it, the display looks differently afterwards: "(Gruppe)" or "(group)" shows up  after the name
* looking at the table "oc_share", there are some strange records
    * there is one for the group that has edit permission
    * there is none for the group that has no edit permission
    * there are many more for individual users (but not for all of the group)

**Comment by DeepDiver1975** [comment]
sharing information for calendars and addressbooks is stored in oc_dav_shares

**Comment by uli-heller** [comment]
OK, I see. Thanks.

**Comment by uli-heller** [comment]
I do have a procedure allowing me to see the shared calendars:

1. start with an invisible shared calendar
2. do a login with the user owning the calendar
3. unshare the calendar
4. share the calendar
5. logout
6. login with your original user
7. the shared calendar is visible now

**Comment by uli-heller** [comment]
I  think the contents of oc_dav_shares is wrong.

```
select * from oc_dav_shares;
+----+------------------------------------------+----------+--------+------------+
| id | principaluri                             | type     | access | resourceid |
+----+------------------------------------------+----------+--------+------------+
|  3 | principals/users/pwb  | calendar |      3 |          6 |
...
| 22 | principals/groups/pwb | calendar |      3 |         18 |
```

"pwb" is a group, but for the missing calendars. it shows up underneath principals/users/.
For me, this fixes the issue:

```
update oc_dav_shares set principaluri='principals/groups/pwb' where principaluri='principals/users/pwb';

```

**Comment by DeepDiver1975** [comment]
9.0.1 will come with a fix for this https://github.com/owncloud/core/pull/22949

**Comment by plinss** [comment]
I have the same issue, more details:
If I un-share and re-share the calendar it does show up for the other users in the ownCloud web app, but it still not visible to iOS or OSX (El Capitan) CalDAV clients.
If I share the calendar to individual users instead of a group, it seems to work normally.

**Comment by PVince81** [comment]
PR https://github.com/owncloud/core/pull/22949 was merged, closing
