### ISSUE TITLE
Resharing in same server does not behave properly

### ISSUE THREAD

**Issue by jesmrec** [owncloud/core#22672]
### Steps to reproduce
1. User1 shares File1 with User2
2. User2 re-shares the File1 with User3

### Expected behaviour

User1 sees File1 as shared only with User2 
User2 sees File1 as sharee from User1, and shared with User3
User3 sees File1 as sharee from User2

### Actual behaviour
User1 sees File1 as shared with User2 and User3
User2 sees File1 as sharee from User1, and shared with User3
User3 sees File1 as sharee from User1

If User1 removes the (incorrect) share with User3:

User3 does not see FileA anymore

### Server configuration
{"installed":true,"maintenance":false,"version":"9.0.0.13","versionstring":"9.0.0 beta 2","edition":""}

**Comment by nickvergessen** [comment]
This is part of changed behaviour in 9.0 and now expected:
https://github.com/owncloud/core/issues/9058
