### ISSUE TITLE
.htaccess rewriterule breaks letsencrypt using webroot

### ISSUE THREAD

**Issue by lbdroid** [owncloud/core#22688]
### Steps to reproduce
1. Install owncloud to the "root" of a domain, i.e. owncloud.mydomain.net
2. Attempt to configure letsencrypt using --webroot

### Expected behaviour
letsencrypt should be able to install its verification files and perform its domain validation

### Actual behaviour
letsencrypt received 404 response from domain being validated

### Server configuration
**Operating system**: CentOS 6.7

**Web server:** Apache from CentOS repositories;
httpd-2.2.15-47.el6.centos.3.x86_64

**ownCloud version:** (see ownCloud admin page)
8.2.2

**Updated from an older ownCloud or fresh install:**
Updated from 8.2.1 (which was also affected)

**Are you using encryption:** yes/no
Yes.

THE PROBLEM IS LOCATED AT;
/var/www/html/owncloud/.htaccess:47
RewriteRule ^(\.|autotest|occ|issue|indie|db_|console).* - [R=404,L]

THE ISSUE IS:
letsencrypt adds a file within the webroot under .well-known/acme-challenge/ -- which is caught by that RewriteRule, resulting in the 404.

**Comment by Xenopathic** [comment]
Fixed with #20966, will be fixed in 9.0
