### ISSUE TITLE
[IE11] input autofocus in sharing sidebar hides placeholder

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/core#22689]
### Steps to reproduce
1. open files app in IE11
2. klick sharing icon
### Expected behaviour

Placeholder should show "Share with users, groups or remote users …"
### Actual behaviour

Instructions in placeholder aren't visible, because input focus is already in input field when sharing sidebar moves in.

![cursor_and_ie11_-_win8_1](https://cloud.githubusercontent.com/assets/214010/13367724/ebc71f52-dce4-11e5-8a76-f3257c064491.png)
### Server configuration

**ownCloud version:** (see ownCloud admin page)
8.2.2

**Updated from an older ownCloud or fresh install:**
fresh install
### Client configuration

**Browser:**
IE11

**Operating system:**
Win 8.1

@MorrisJobke This is the default ([buggy](https://twitter.com/IEDevChat/status/479699046215319552)) behavior of IE11, but in our case it's an usability issue. Could the input autofocus be disabled for IE11? This would also help with https://github.com/owncloud/core/issues/19767 and https://github.com/owncloud/core/issues/20444 .

00004901

**Comment by MorrisJobke** [comment]
> @MorrisJobke This is the default (buggy) behavior of IE11, but in our case it's an usability issue. Could the input autofocus be disabled for IE11? This would also help with #19767 and #20444 .

Sure, but this doesn't make it more maintainable :cry: 

@PVince81 How do you rate the UX vs maintainability ratio?

**Comment by MorrisJobke** [comment]
> @PVince81 How do you rate the UX vs maintainability ratio?

Or @rullzer

**Comment by PVince81** [comment]
DAMMIT IE11, I thought we were done with placeholder workarounds ??!!

**Comment by PVince81** [comment]
Looks like we'll need to hunt for a new jquery placeholder shim for IE10/IE11.
But first, does the existing one work in these versions ?

**Comment by PVince81** [comment]
How did we do it in OC < 8.2 where there was no sidebar ? Pretty sure it likely looked the same.

**Comment by michaelstingl** [comment]
@PVince81 I would be happy to help with testing.

**Comment by PVince81** [comment]
Moving forward as it isn't critical.

Looks like this will be more than a one-liner as we'll need to add code to detect IE11 specifically (we don't see to have anything yet)

**Comment by PVince81** [comment]
@michaelstingl in the meantime here's a quick hack to disable the share field autofocus completely:
```
diff --git a/core/js/sharedialogview.js b/core/js/sharedialogview.js
index e5ef5bb..52b1db6 100644
--- a/core/js/sharedialogview.js
+++ b/core/js/sharedialogview.js
@@ -318,9 +318,11 @@
                        if (!this._loadingOnce) {
                                this._loadingOnce = true;
                                // the first time, focus on the share field after the spinner disappeared
+                               /*
                                _.defer(function() {
                                        self.$('.shareWithField').focus();
                                });
+                          */
                        }
                },
```

**Comment by michaelstingl** [comment]
@PVince81 Thanks!

**Comment by PVince81** [comment]
moving to 8.2.9

**Comment by butonic** [comment]
this seems to work in ie 11: http://jsfiddle.net/q05ngura/3/

**Comment by butonic** [comment]
would solve multiple issues with ie11

**Comment by butonic** [comment]
maybe @PVince81 or @felixheidecke can have a look?

**Comment by cdamken** [comment]
Hi, any news here?

**Comment by michaelstingl** [comment]
@cdamken @felixheidecke is ooto and should be back next week…

**Comment by cdamken** [comment]
Thanks, I'll wait 😃

**Comment by Kawohl** [comment]
@felixheidecke do you have an ETA?

**Comment by felixheidecke** [comment]
In general: Using a placeholder on an input field ist not a label replacement UX wise. _(The latter is present button hidden.)_ Replacing the default placeholder behavior in IE using a workaround is a quick and dirty "fix" and should not be a long term solution.

Labels are hidden or shown as seen fit throughout the web interface wich does not contribute to a unified user experience.

My solution:

1. Quick fixing the IE behavior
2. Establishing a thought thru UX/UI guide on how to display forms soon!

**Comment by PVince81** [comment]
@felixheidecke sounds good.

**Comment by felixheidecke** [comment]
See PR https://github.com/owncloud/core/issues/22689

**Comment by Kawohl** [comment]
@felixheidecke awesome! Is this backportable to 8.2?

**Comment by felixheidecke** [comment]
I'm no expert but I guess so. (Never ported anything so far :smile: )

**Comment by PVince81** [comment]
Backporting is ok but without the library update. Please use `OC.isIE11()` in the backports.

**Comment by felixheidecke** [comment]
@Kawohl if the backport is needed, then this should be a new issue.
I'll close this one for now as the task is completed.

**Comment by PVince81** [comment]
@felixheidecke no new issues for backports.
We add the "backport-request" label on the PR and keep it until the backport PRs are opened and referenced to.

**Comment by PVince81** [comment]
backport still pending ?

**Comment by felixheidecke** [comment]
Backport to what version?

**Comment by cdamken** [comment]
IMO Stable 9.1 could be enough, 9.0 is EOL in 2 months

**Comment by felixheidecke** [comment]
@PVince81 Too much has happened since the PR. So I would go ahead and write the nessesary changes by hand.

**Comment by phil-davis** [comment]
@felixheidecke does this still need the backport-request label?
It looks like back-porting already happened?
