### ISSUE TITLE
Spinner in link share stays if an error occurs

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#22680]
- do the steps in https://github.com/owncloud/core/pull/22673 (without the patch) which results in a 403 
- expected: popup with error message & checkbox is back (unchecked)
- actual: popup with error message & spinner is still there

<img width="1435" alt="bildschirmfoto 2016-02-26 um 15 11 55" src="https://cloud.githubusercontent.com/assets/245432/13354450/656904e6-dc9b-11e5-98b2-6bc9b814e721.png">

cc @rullzer

**Comment by rullzer** [comment]
@MorrisJobke but with the patch this is fixed right?

**Comment by MorrisJobke** [comment]
> @MorrisJobke but with the patch this is fixed right?

Yes, but this indicates, that the JS can't handle error cases (that could happen) properly.

**Comment by rullzer** [comment]
Ok true ;)

**Comment by PVince81** [comment]
Pffff, still happening on stable9.1

**Comment by PVince81** [comment]
obsoleted by modal in 10.0
