### ISSUE TITLE
Not possible to update reshares as initiator

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#22682]
https://github.com/owncloud/core/pull/22660 introduced a bug.

1. user1 shares a folder with user2
2. user2 shares a folder with user3
3. user2 modified the share to user3

Expected: All is well
Actual: Error that you can't share your root

It seems the check in #22660 is a bit to strict.
I'll prepare a PR

**Comment by rullzer** [comment]
Fix in #22683 with intergration test.

**Comment by cmonteroluque** [comment]
need one more reviewer

**Comment by oparoz** [comment]
The implications are quite vast. It's impossible to make any sort of modifications on a reshare as user2.
Fix works.
