### ISSUE TITLE
oc 9.0 beta2: file integrity check

### ISSUE THREAD

**Issue by vanMacG** [owncloud/core#22698]
### Steps to reproduce
1. made a copy of small production oc 8.2.2
2. rename of old oc, upload 9.0 beta2, moved config.php and data-folder to new oc
3. perform web-update

### Expected behaviour
file integrity: ok

### Actual behaviour
file integrity: reports error, EXTRA_FILE

### Server configuration
**Operating system:** Shared webhost: Linux dd27002 3.2.0-98-generic #138-Ubuntu SMP Mon Jan 11 12:33:01 UTC 2016 x86_64

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.5.31

**ownCloud version:** ownCloud 9.0.0 beta 2 (testing)

**Updated from an older ownCloud or fresh install:** update from 8.2.2

**Signing status (ownCloud 9.0 and above):** 
- core
	- EXTRA_FILE
		- data_ufdruqd6b2/admin/thumbnails/7/1024-768-max.png
		- data_ufdruqd6b2/admin/thumbnails/7/200-200.png
		- data_ufdruqd6b2/admin/thumbnails/7/267-200-with-aspect.png
		- data_ufdruqd6b2/admin/thumbnails/9/300-200-with-aspect.png
		- data_ufdruqd6b2/admin/thumbnails/9/1024-683-max.png
		- data_ufdruqd6b2/admin/thumbnails/9/200-200.png
		- data_ufdruqd6b2/admin/thumbnails/8/300-200-with-aspect.png
		- data_ufdruqd6b2/admin/thumbnails/8/1024-683-max.png
		- data_ufdruqd6b2/admin/thumbnails/8/200-200.png
		- data_ufdruqd6b2/admin/files/ownCloud_User_Manual.pdf
		- data_ufdruqd6b2/owncloud.log
		- data_ufdruqd6b2/updater_backup/8.2.1.4-9f264f98.zip
		- data_ufdruqd6b2/updater_backup/8.2.1.4.zip
		- data_ufdruqd6b2/updater_backup/8.2.2.2.zip
		- data_ufdruqd6b2/files_external/rootcerts.crt
		- data_ufdruqd6b2/.htaccess

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

**Comment by LukasReschke** [comment]
What is this `data_ufdruqd6b2` folder in the root folder of your ownCloud?

**Comment by vanMacG** [comment]
It's my datadirectory as specified in config.php.
I just added some random chars for making it harder to guess in some case of attack... sry for confusing.

**Comment by LukasReschke** [comment]
Can you also provide your config file etc.?

**Comment by vanMacG** [comment]
**The content of config/config.php:**
<?php
$CONFIG = array (
'instanceid' => 'oc0flwmdlhen',
'passwordsalt' => 'xxx',
'secret' => 'xxx',
'trusted_domains' =>
array (
0 => 'betacloud.xxx.eu',
),
'datadirectory' => '/www/htdocs/w0069a6f/testing/owncloud/data_ufdruqd6b2',
'overwrite.cli.url' => 'https://betacloud.xxx.eu',
'dbtype' => 'mysql',
'version' => '9.0.0.12',
'dbname' => 'd01ed8f6',
'dbhost' => 'localhost',
'dbtableprefix' => 'oc_',
'dbuser' => 'd01ed8f6',
'dbpassword' => 'xxx',
'logtimezone' => 'UTC',
'installed' => true,
'tempdirectory' => '/www/htdocs/w0069a6f/testing/tmp/',
'theme' => '',
'loglevel' => 2,
'maintenance' => false,
);

**Owncloud.log:**
{"reqId":"VtLoDVUNkdgAAH9TPHkAAAAV","remoteAddr":"x.x.x.x","app":"index","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/www\\\/htdocs\\\/w0069a6f\\\/testing\\\/owncloud\\\/lib\\\/private\\\/app.php(118): OC_App::loadApp('files')\\n#1 \\\/www\\\/htdocs\\\/w0069a6f\\\/testing\\\/owncloud\\\/lib\\\/private\\\/util.php(138): OC_App::loadApps(Array)\\n#2 \\\/www\\\/htdocs\\\/w0069a6f\\\/testing\\\/owncloud\\\/lib\\\/base.php(855): OC_Util::setupFS()\\n#3 \\\/www\\\/htdocs\\\/w0069a6f\\\/testing\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/www\\\/htdocs\\\/w0069a6f\\\/testing\\\/owncloud\\\/lib\\\/private\\\/app.php\",\"Line\":143}","level":3,"time":"2016-02-28T12:29:01+00:00"}
{"reqId":"VtLoElUNkdgAAH9rPVUAAAAW","remoteAddr":"x.x.x.x","app":"core","message":"starting upgrade from 8.2.2.2 to 9.0.0.12","level":0,"time":"2016-02-28T12:29:06+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=BicKdw4eZAQAei8eARooBxYnJihfA2doMiAeVQEV%3AefP%2F8D3FP6xS5OrCzjsfkt00Kdw98cAx8J8F4vYe"}
{"reqId":"VtLoElUNkdgAAH9rPVUAAAAW","remoteAddr":"x.x.x.x","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Contacts tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/www\\\/htdocs\\\/w0069a6f\\\/testing\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/migrateaddressbooks.php(55): OCA\\\\Dav\\\\Migration\\\\AddressBookAdapter->setup()\\n#1 \\\/www\\\/htdocs\\\/w0069a6f\\\/testing\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/application.php(143): OCA\\\\Dav\\\\Migration\\\\MigrateAddressbooks->setup()\\n#2 \\\/www\\\/htdocs\\\/w0069a6f\\\/testing\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/install.php(26): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateAddressbooks()\\n#3 \\\/www\\\/htdocs\\\/w0069a6f\\\/testing\\\/owncloud\\\/lib\\\/private\\\/installer.php(617): include('\\\/www\\\/htdocs\\\/w00...')\\n#4 \\\/www\\\/htdocs\\\/w0069a6f\\\/testing\\\/owncloud\\\/lib\\\/private\\\/installer.php(568): OC_Installer::includeAppScript('\\\/www\\\/htdocs\\\/w00...')\\n#5 \\\/www\\\/htdocs\\\/w0069a6f\\\/testing\\\/owncloud\\\/lib\\\/private\\\/installer.php(542): OC_Installer::installShippedApp('dav')\\n#6 \\\/www\\\/htdocs\\\/w0069a6f\\\/testing\\\/owncloud\\\/lib\\\/private\\\/updater.php(328): OC_Installer::installShippedApps()\\n#7 \\\/www\\\/htdocs\\\/w0069a6f\\\/testing\\\/owncloud\\\/lib\\\/private\\\/updater.php(215): OC\\\\Updater->doUpgrade('9.0.0.12', '8.2.2.2')\\n#8 \\\/www\\\/htdocs\\\/w0069a6f\\\/testing\\\/owncloud\\\/core\\\/ajax\\\/update.php(120): OC\\\\Updater->upgrade()\\n#9 {main}\",\"File\":\"\\\/www\\\/htdocs\\\/w0069a6f\\\/testing\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/addressbookadapter.php\",\"Line\":53}","level":3,"time":"2016-02-28T12:29:30+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=BicKdw4eZAQAei8eARooBxYnJihfA2doMiAeVQEV%3AefP%2F8D3FP6xS5OrCzjsfkt00Kdw98cAx8J8F4vYe"}
{"reqId":"VtLoElUNkdgAAH9rPVUAAAAW","remoteAddr":"x.x.x.x","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Calendar tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/www\\\/htdocs\\\/w0069a6f\\\/testing\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/migratecalendars.php(57): OCA\\\\Dav\\\\Migration\\\\CalendarAdapter->setup()\\n#1 \\\/www\\\/htdocs\\\/w0069a6f\\\/testing\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/application.php(159): OCA\\\\Dav\\\\Migration\\\\MigrateCalendars->setup()\\n#2 \\\/www\\\/htdocs\\\/w0069a6f\\\/testing\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/install.php(27): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateCalendars()\\n#3 \\\/www\\\/htdocs\\\/w0069a6f\\\/testing\\\/owncloud\\\/lib\\\/private\\\/installer.php(617): include('\\\/www\\\/htdocs\\\/w00...')\\n#4 \\\/www\\\/htdocs\\\/w0069a6f\\\/testing\\\/owncloud\\\/lib\\\/private\\\/installer.php(568): OC_Installer::includeAppScript('\\\/www\\\/htdocs\\\/w00...')\\n#5 \\\/www\\\/htdocs\\\/w0069a6f\\\/testing\\\/owncloud\\\/lib\\\/private\\\/installer.php(542): OC_Installer::installShippedApp('dav')\\n#6 \\\/www\\\/htdocs\\\/w0069a6f\\\/testing\\\/owncloud\\\/lib\\\/private\\\/updater.php(328): OC_Installer::installShippedApps()\\n#7 \\\/www\\\/htdocs\\\/w0069a6f\\\/testing\\\/owncloud\\\/lib\\\/private\\\/updater.php(215): OC\\\\Updater->doUpgrade('9.0.0.12', '8.2.2.2')\\n#8 \\\/www\\\/htdocs\\\/w0069a6f\\\/testing\\\/owncloud\\\/core\\\/ajax\\\/update.php(120): OC\\\\Updater->upgrade()\\n#9 {main}\",\"File\":\"\\\/www\\\/htdocs\\\/w0069a6f\\\/testing\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/calendaradapter.php\",\"Line\":49}","level":3,"time":"2016-02-28T12:29:30+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=BicKdw4eZAQAei8eARooBxYnJihfA2doMiAeVQEV%3AefP%2F8D3FP6xS5OrCzjsfkt00Kdw98cAx8J8F4vYe"}
{"reqId":"VtLoElUNkdgAAH9rPVUAAAAW","remoteAddr":"x.x.x.x,"app":"core","message":"No update found at the ownCloud appstore for app 166054","level":0,"time":"2016-02-28T12:29:31+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=BicKdw4eZAQAei8eARooBxYnJihfA2doMiAeVQEV%3AefP%2F8D3FP6xS5OrCzjsfkt00Kdw98cAx8J8F4vYe"}

**Comment by LukasReschke** [comment]
Ok. I can reproduce this. This is a must fix as scanning the data folder in big instances can make the update process break otherwise.

**Comment by LukasReschke** [comment]
Patch is at https://github.com/owncloud/core/pull/22756. @vanMacG Mind testing? THX.

**Comment by vanMacG** [comment]
@LukasReschke tested with the patched file. I can confirm that the errors regarding the datadirectory are solved.
As you said in #22756 the patched file is reported (invalid_hash).

But I have a new problem now, but honestly I think this is intended... so don't know what you want to do about it or just ignore it.
My webserver generates access-logs in the owncloud-folder (cause it is the root-folder of the subdomain). Therefore I have now the following "extra_file":
Results
=======
- core
	- INVALID_HASH
		- lib/private/integritycheck/iterator/excludefoldersbypathfilteriterator.php
	- EXTRA_FILE
		- logs/access_log_2016-02-29.gz
		- logs/access_log_betacloud_xxx_eu_2016-02-29.gz
		- logs/access_log_betacloud_xxx_eu_2016-02-28.gz
		- logs/access_log_2016-02-28.gz

**Comment by LukasReschke** [comment]
Thanks a lot for testing, awesome work. And kudos for testing a beta :rocket: :smile: 

Yes, those are indeed intended. Writing into the ownCloud folder manually will trigger an EXTRA_FILE warning, best would be to move it out of there or ignore/disable code signing for this. (`'integrity.check.disabled' => true` in `config.php`)

**Comment by vanMacG** [comment]
And a second comment about this. The access-log-folder permissions were set restrictive so the integrity-checker couldn't read/access it. But it didn't skip the folder, it just "stoped" checking ingetrity. Result was that the custom-datadirectory-stuff wasn't displayed as an error anymore. Maybe this could be an issue, as you want a complete ingetritycheck.
If you want to track this down please ask for details if you need more info.

**Comment by LukasReschke** [comment]
> And a second comment about this. The access-log-folder permissions were set restrictive so the integrity-checker couldn't read/access it. But it didn't skip the folder, it just "stoped" checking ingetrity. Result was that the custom-datadirectory-stuff wasn't displayed as an error anymore. Maybe this could be an issue, as you want a complete ingetritycheck.

Interesting. Can you open a new ticket about this? Then I can debug this there :-)
(just copy-paste this text and as well a `ls -lah` on the folder would help so that I understand the set permissions)

**Comment by vanMacG** [comment]
Will do so after dinner :)

**Comment by vanMacG** [comment]
> Thanks a lot for testing, awesome work. And kudos for testing a beta :rocket: :smile:
Yes, those are indeed intended. Writing into the ownCloud folder manually will trigger an EXTRA_FILE warning, best would be to move it out of there or ignore/disable code signing for this. ('integrity.check.disabled' => true in config.php)

I'm glad to help. Thanks for tracking this non-standard-issue down :)

Just some more annotation:
- I'm on a shared hosting (all-inkl, not so small in Germany...) and the log-folder is autogenerated and can't be changed. So you probably will hear this issue some more times when releasing 9.0... I understand the intention of the integrity check here, but you should be prepared for some people who don't.
- I tried disabling the check, no more errors ^^ After switch back on I still don't get errors anymore. Just out of curiosity, when/how is the check triggered?
- Would be nice to see the disable-option in config.sample.php. I bet it's already on your to-do-list, so this is just a reminder ;)
