### ISSUE TITLE
Menu language can't be changed

### ISSUE THREAD

**Issue by tflidd** [owncloud/core#22695]
### Steps to reproduce
1. Create new user
2. Go to personal page, set language to "English"
3. Logout
4. Login
5. Go to personal page
6. Click on menu (top right)

### Expected behaviour
Menu in english

### Actual behaviour
menu in german
![screenshot](https://cloud.githubusercontent.com/assets/8111200/13376076/52de8b68-ddb1-11e5-94d9-a61d3745a1d2.PNG)

### Server configuration
**Operating system**: Debian 8

**Web server:** Apache

**Database:** MariaDB

**PHP version:** DotDEB PHP 7.0.3 (same problem with 5.6.17-0+deb8u1), mod_php

**ownCloud version:** Nightly repo: ownCloud 9.0.0 beta 2 (daily) Build:2016-02-26T04:41:33+00:00 cb41b1a86397579d55e0ce96e67b80a83037d1d2
(same problem on: ownCloud 9.0 beta 1 (testing))

**Updated from an older ownCloud or fresh install:** Update from 8.2.2

**Signing status (ownCloud 9.0 and above):** Integrity check? -> no issues.

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.4
  - federatedfilesharing: 0.1.0
  - federation: 0.0.3
  - files: 1.4.3
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0

```

**The content of config/config.php:**

```
$CONFIG = array (
  'instanceid' => 'ocbhjjaeth7b',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' =>
  array (
    0 => 'xxxx',
    1 => 'xxxy',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://xxxx/owncloud',
  'dbtype' => 'mysql',
  'version' => '9.0.0.13',
  'dbname' => 'owncloud-osdfj',
  'dbhost' => 'localhost',
  'dbtableprefix' => '',
  'dbuser' => 'oc_admin1',
  'dbpassword' => 'xxx',
  'logtimezone' => 'UTC',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_from_address' => 'xxx',
  'mail_domain' => 'xxxx',
  'mail_smtpauth' => 1,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => 'xxx',
  'mail_smtpport' => '587',
  'mail_smtpname' => 'xxx',
  'mail_smtppassword' => 'xxx',
  'singleuser' => false,
  'loglevel' => 0,
  'trashbin_retention_obligation' => 'auto',
  'updatechecker' => false,
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => '/tmp/redis.sock',
    'port' => 0,
    'timeout' => 0,
  ),
);

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:** Firefox/Chrome

**Operating system:** Win 7 Pro

#### Browser log
If I open the browser console in Firefox, I get this error (for the security settings):
```
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src https://myhost 'unsafe-eval'").
```
owncloud is installed on https://myhost/owncloud

No js-error, only warnings:
```
getPreventDefault() sollte nicht mehr verwendet werden. Verwenden Sie stattdessen defaultPrevented. jquery.min.js:5:17117
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead
```

**Comment by tflidd** [comment]
It takes the browser language of highest priority regardless the setting used in the user's config.

**Comment by DeepDiver1975** [comment]
@nickvergessen mind taking a look? THX
