### ISSUE TITLE
Clean up the Database and Filesystem

### ISSUE THREAD

**Issue by blackcrack** [owncloud/core#22696]
### Steps to reproduce
1. --> goto --> Administration
2. ---> goto --> Clean Up OwnCloud
 * [Button] check the Space (clean the DB up and check what it is on the Space and what it is on DB (compare)
 * [Button] Check the Apps and check what's real install or only in the DB and remove the mess entry's (DB-App-Regestry-Cleanup)
 * [Button] Create a Tar.gz from the trash with date under /trashbackup/Trash-XXXXXXXX-backup.tar.gz
 * [Button] Clean up the Trash in Regestry & Filesystem

### Expected behaviour
The Database clean & fixing up for running an Clean Owncloud

### Actual behaviour
A mess in the Database and configurations of Apps where was
installed and be removed and by reinstall not correctly functioning

### Server configuration
**Operating system**:
OpenMandriva 2 (2014) ServerSystem (Blackysgate.net)
http://www.blackysgate.net/phpinfo.php

**Web server:**
  Version: 2.4.17-0.1:2014.0
        Gruppe: System/Server
        Architektur: x86_64
        Größe: 984 KB
        Medium: main updates (localserver2)

**Database:**
        Version: 10.0.22-0.1:2014.0
        Gruppe: System/Server
        Architektur: x86_64
        Größe: 0 KB
        Medium: main updates (localserver2)

**PHP version:**
PHP Version 5.5.31

**ownCloud version:** (see ownCloud admin page)
ownCloud 8.2.2 (stable) 
**Updated from an older ownCloud or fresh install:**
fresh on filesystem, /old in mysql 

**Signing status (ownCloud 9.0 and above):**
```
nothing
```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
Datei nicht gefunden

Das ausgewählte Dokument wurde auf dem Server nicht gefunden.

Du kannst zur Rückkehr zu ownCloud hier klicken.
```
**Are you using encryption:** yes/no
nope, my own server, my own files and my own administration.
where i want have access 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
not need..

### Client configuration
**Browser:**
Firefox (but not interesting for this issue.. )

**Operating system:**
^^ OMLx

best regards
Blacky

**Comment by LukasReschke** [comment]
> ---> goto --> Clean Up OwnCloud

Can you make a screenshot of where you found this and did you install by any chance a third-party program providing this functionality? This seems not like a core ownCloud function.

**Comment by blackcrack** [comment]
it exist still not, should be create ..
or do you find this in addons ? I guess not ..
so, should it build.. from anyone or should be as issue, 
what i have now done . An Tweaking/Cleanup-app for owncloud
and not a long page for admin with adjustments, would be very nice, 
if someone make slowly register cards for an clean administration.
Any application his register card and on top the Name, for fast selecting.
This should slowly change, otherwith would be the Administrationpage 1-2 miles 
long and you can scroll  up to you become black..*lol*

So, Registercards would maybe not a bad possibility for manage 
the whole app-configuration and an Cleanup-app would also not a bad choice for 
the Database, Ownloud and OC-Filesystem.

best regards
Blacky

**Comment by LukasReschke** [comment]
Our goal is to have no manual actions necessary and perform such operations in the background.
