### ISSUE TITLE
A user can create an unlimited amount of duplicate public links for a single folder when using the API

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#22692]
### Steps to reproduce
1. Create a new folder share using the API
2. Create it again using the same POST data

URL: `/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json`
Payload: `path=pics%2Fbrand+guideline+logos&shareType=3&shareWith=&publicUpload=0&password=&permissions=1`

### Expected behaviour

The second request should not go through and a specific error should be returned, indicating to the client that a link already exists

OR

The link which was created earlier should be returned

### Actual behaviour

Each request returns a new link object, with a different ID and token.

### Server configuration

**ownCloud version:** master

#### Browser log

1st request

```
id: 624, share_type: 3, uid_owner: "admin", displayname_owner: "admin", permissions: 1, stime: 1456584648, parent: null, expiration: null, token: "uaidgEJbXb3DQzj", uid_file_owner: "admin",...
```

2nd request

```
id: 625, share_type: 3, uid_owner: "admin", displayname_owner: "admin", permissions: 1, stime: 1456584745, parent: null, expiration: null, token: "V1azHym3B4EchAf", uid_file_owner: "admin",...
```

----
@rullzer @PVince81 @MorrisJobke

**Comment by oparoz** [comment]
@rullzer @PVince81 @MorrisJobke

**Comment by rullzer** [comment]
Yes this is possible now indeed.
Note that you can always find more since with the new resharing if one of the people you shared with shared by link you can also fetch that.

We could block this case in the API for now. But I'm not sure if that is really what we want. @schiesbn

**Comment by oparoz** [comment]
Reshares are good, but I can't think of a single reason for allowing the creation of duplicate links, this just creates junk data in the DB. It's also going to be a problem for people consuming shares. You typically pick up the first one from the list which meets your criteria.

BTW, I'm not familiar with the original issue, but this could be another reason some apps recently ended up with incompatible shares.

**Comment by rullzer** [comment]
Well there are valid use cases https://github.com/owncloud/core/issues/22327
So as said we could block this in 9.0.1. But eventually apps will need to switch. The trouble is that the behaviour is not specified anywhere. So you could make both assumptions.

Which other apps ended up with issues?

**Comment by oparoz** [comment]
#22327 contains cases which technically are not duplicates.

* public links sent to specific email addresses
* public links using different passwords
* public links having different expiration date
etc.

but there are 2 issues:

* There is no GUI available which gives users access to all the links, so currently, the link shown depends on how the app retrieves the information
* #22327 is in the backlog, so this is not something which will land in 9.0

So a limiter should be put in place for 9.0 and we have to accept the fact the database contains junk data which cannot be automatically cleaned up.

**Comment by oparoz** [comment]
Another reason why this has to be limited until there is a proper GUI for it.

1. UI asks for list of links
1. UI shows a random link from the list, usually first or last
1. User unticks *Share link*
1. UI removes the link
1. User closes and re-open share dialogue
1. Bam, there is still a link
1. User fills in a bug report

**Comment by rullzer** [comment]
Ok I kind of agree.

PR in #22700

@PVince81 and @cmonteroluque I let you decide 9.0 or 9.0.1

**Comment by PVince81** [comment]
Change of behavior from 8.2.2, kind of a regression that can affect some clients.
Increasing severity.
