### ISSUE TITLE
Specify mounting point of external storages

### ISSUE THREAD

**Issue by alve89** [owncloud/core#22704]
### Expected behavior

In http://cloud.tld/index.php/settings/[admin/personal] under "External Storage" you should be able to set a mounting point (e.g. an existing folder within the cloud or the root directory).
### Actual behavior

External storages are always mounted in the root directory.
### Server configuration

Operating system: Ubuntu 3.13

Web server: Apache 2

Database: MySQL 5.0.11

PHP version: 5.6.17

ownCloud version:8.2.2
### Comments

That's a pity - especially if you have several external storages you want to share with other users - it was so much more efficient to mount these storages within a shared folder than share all storages again manually.

**Comment by PVince81** [comment]
@alve89 if you have an existing folder "mounts" you can just specify "mounts/sftp" for your SFTP mount point for example.

This should already work, closing.

If it's broken, feel free to reopen and we'll label it as bug.

**Comment by alve89** [comment]
This might work for SFTP (I can't try, my hoster doesn't offer this) but it doesn't work for FTP, WebDAV, Dropbox, ownCloud. I couldn't test the other storages.
So it's not a bug but a feature request that could be very helpful I think.

**Comment by alve89** [comment]
How could I even reopen an issue if I'd like to (generally, not this one)?

**Comment by PVince81** [comment]
@alve89 SFTP was just an example. It should work already will all other external storages too.

If it doesn't work when adding the parent folder name in the mount point name, then it's likely a bug.

**Comment by alve89** [comment]
@PVince81 Oh great. I didn't know that just adding the parent folder name would work. So it works now.
But for non-tech-users who might be allowed to add external storages too, a input-select-box (as it is used in sharing input box that displays available users via AJAX) was very helpful.
What do you think?

**Comment by PVince81** [comment]
Ok, then let me reopen this for adding mount point creation  assistance in the form of a lookup dropdown or others.
