### ISSUE TITLE
Activity Feed doesn't load additional information when scrolling

### ISSUE THREAD

**Issue by mbressman** [owncloud/core#22703]
When I go to the activity feed in oC 8.2.2 and then start scrolling down, I hit the spinning circle (looks similar to this: http://ceblog.s3.amazonaws.com/wp-conte ... pinner.png) and it just stays there forever instead of loading more data in the activity feed - confirmed that others are experiencing this as well via post on forum: https://forum.owncloud.org/viewtopic.php?f=36&t=33120

### Steps to reproduce
1. Launch oC 8.2.2
2. Select "Activity" from the upper left menu
3. Scroll down as far as you can and see the spinning circle that makes it appear the page is attempting to load more of the activity feed but it never loads anything further

### Expected behaviour
Further items in the activity feed should continue to load as you continue to scroll down

### Actual behaviour
The spinning circle appears that makes it seem like the page is preparing to load more items in the activity feed except the spinning circle never goes away and the page never loads more items in the activity feed

### Server configuration
**Operating system**: Ubuntu Linux 12.04.5 LTS

**Web server:** Apache v2.2.22

**Database:** MySQL v5.5.47

**PHP version:** 5.4.45-3+deb.sury.org~precise+1

**ownCloud version:**  8.2.2

**Updated from an older ownCloud or fresh install:**  Updated from older version

**List of activated apps:**

Enabled:

activity: 2.0.1
bookmarks: 0.4
documents: 0.10.1
files: 1.1.10
files_external: 0.2.3
files_pdfviewer: 0.7
files_sharing: 0.6.2
files_texteditor: 0.4
files_trashbin: 0.6.3
files_versions: 1.0.6
files_videoviewer: 0.1.3
firstrunwizard: 1.1
galleryplus: 13.0.0
search_lucene: 0.6.0
updater: 0.6 Disabled:
encryption
external
files_locking
gallery
provisioning_api
templateeditor
user_external
user_ldap
user_webdavauth

**The content of config/config.php:**

WOULD PREFER NOT TO POST THIS BUT CAN SEND IT PRIVATELY TO OWNCLOUD DEVELOPERS IF NECESSARY

**Are you using external storage, if yes which one:** 

Enabled:

Amazon S3 and Compliant
Dropbox
FTP
Google DRive
ownCloud
SFTP
SMB / CIFS
WebDAV

Configured:

Google Drive and Dropbox (via Personal settings and not Admin settings)
SMB/CIFS (via Admin Settings)

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** NO

### Client configuration
**Browser:**  Chrome

**Operating system:**  Win 8.1 and Win10

#### Web server error log
```
WOULD PREFER NOT TO POST THIS BUT CAN SEND IT PRIVATELY TO OWNCLOUD DEVELOPERS IF NECESSARY
```

#### ownCloud log (data/owncloud.log)
```
WOULD PREFER NOT TO POST THIS BUT CAN SEND IT PRIVATELY TO OWNCLOUD DEVELOPERS IF NECESSARY
```

#### Browser log
```

WOULD PREFER NOT TO POST THIS BUT CAN SEND IT PRIVATELY TO OWNCLOUD DEVELOPERS IF NECESSARY
```

**Comment by LukasReschke** [comment]
Could you reopen this at https://github.com/owncloud/activity? THX a lot :smile:

**Comment by mbressman** [comment]
Moved here: https://github.com/owncloud/activity/issues/467
