### ISSUE TITLE
German Umlaute in Notes field blow up until OC starts to hang

### ISSUE THREAD

**Issue by ufgum** [owncloud/core#22709]
### Steps to reproduce
1. insert or update a contact with Kadressbook and a German umlaut (Ü) in the notes field
2. waiting until entry gets size of some MB
3. webserver continuously hanging on 100%

### Expected behaviour
Tell us what should happen

### Actual behaviour
the notes field getting bigger as long as the oc running

Here is a screenshot from kadressbook:
![screenshot_004](https://cloud.githubusercontent.com/assets/1183243/13390705/556db028-ded0-11e5-90d1-70ea59b0304f.png)

Here from OC Calendar entry:
![screenshot_005](https://cloud.githubusercontent.com/assets/1183243/13390717/65111920-ded0-11e5-85c2-e587acaed49a.png)

Here from the notes field:
![screenshot_006](https://cloud.githubusercontent.com/assets/1183243/13390722/705cdc38-ded0-11e5-95ef-2d4662d127df.png)

And this is raising many MB

The Name Jürgen is then like:
JÃÂÃÂÃÂÃÂÃÃ\r\n ......
many MB
...ÃÂ\r\n ¼rgen

### Server configuration
debian

**Web server:**
apache2
**Database:**
mysql
**PHP version:**
5.4.45
**ownCloud version:** (see ownCloud admin page)
8.2.2
**Updated from an older ownCloud or fresh install:**
update, but I see this behavior long time now
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
nothing shows up here

**List of activated apps:**

  - activity: 2.1.3
  - bookmarks: 0.6
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - documents: 0.11.1
  - files: 1.2.0
  - files_locking: 
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_videoviewer: 0.1.3
  - gallery: 14.2.0

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

**Comment by nickvergessen** [comment]
Should be a problem with the old contacts app: https://github.com/owncloud/contacts/ ,
I tested the new endpoint and it works fine.
But also 8.2.2 is no problem for me, so maybe a problem with your DB setup?

**Comment by ufgum** [comment]
Would you please try to update an entry with umlaute in the notes field? Just update another field. I also can not reprocuce it on any times, but last, the notes field was already there and I add a birthday.

**Comment by DeepDiver1975** [comment]
> Should be a problem with the old contacts app: https://github.com/owncloud/contacts/ ,

should be reported there - but is kind of pointless since the app is no longer maintained
