### ISSUE TITLE
Inconsistent share owner shown in Files for reshares

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#22702]
### Steps to reproduce

1. UserA shares a folder with UserB
2. UserB shares the same folder with UserC
3. As UserC, click on the row of the shared folder to bring out the sidebar

### Expected behaviour

The same user should be shown both on the row and in the sidebar

### Actual behaviour

The row shows UserA
The sidebar shows UserB

----
@rullzer @MorrisJobke @PVince81

**Comment by MorrisJobke** [comment]
This is intended behavior. The row shows the actual owner of the data.The sidebar shows who added you to the share list.

cc @schiesbn @PVince81

**Comment by oparoz** [comment]
@jancborchardt You're OK with this behaviour? As a user I find it confusing to see rows belonging to people I don't know.

**Comment by MorrisJobke** [comment]
> @jancborchardt You're OK with this behaviour? As a user I find it confusing to see rows belonging to people I don't know.

At least this is how it was discussed in https://github.com/owncloud/core/issues/19331

**Comment by oparoz** [comment]
Thanks. Seems there still are some big outstanding issues, like the way unsharing works.

**Comment by rullzer** [comment]
> Thanks. Seems there still are some big outstanding issues, like the way unsharing works.

How so? Unsharing is just unsharing. There is no tree anymore so you just unshare 1 share at a time.

**Comment by oparoz** [comment]
>There is no tree anymore so you just unshare 1 share at a time.

Exactly. How do you like clicking 10, 20, 30 times on unshare because some popular content got reshared a lot?
1st level shares should be clearly marked and there should be a tick box near each unshare button allowing users to completely wipe that tree.

**Comment by PVince81** [comment]
"Unshare from all" ?

**Comment by oparoz** [comment]
>"Unshare from all" ?

@PVince81 Exactly. I don't know if there is already a discussion on unsharing specifically, if not I can open a feature request

**Comment by PVince81** [comment]
Not that I'm aware of. Would be a nice addition.

**Comment by rullzer** [comment]
That would be a nice addition.

However, I have yet to come across an installation that has so many reshares of a single file. It is more of a theoretical problem.

**Comment by oparoz** [comment]
Quick question:

A and B belongs to group1
B and C belong to group2
A shares with B who shares with C

Does A see C as a sharee?

**Comment by MorrisJobke** [comment]
> Does A see C as a sharee?

Yes. In 9.0 the hierarchy is dropped and the sharees are added to the original share.

**Comment by oparoz** [comment]
Thanks for confirming.
