### ISSUE TITLE
Checksums: Implement RFC 3230

### ISSUE THREAD

**Issue by dragotin** [owncloud/core#22711]
This enhancement will implement compliance with [RFC 3220](https://tools.ietf.org/html/rfc3230) which is about how client and server negotiate a checksum over the request/reply body.

### Expected behaviour
Server should follow RFC 3230. That means in a nutshell:
The server checks requests for the existance of the header `Want Digest`. If it is there, the server adds a header value to the reply with the checksum asked for. 

### Actual behaviour
It does not happen. If the server has a checksum it is only returned on PROPFIND and GET as described in #18716

**Comment by DeepDiver1975** [comment]
> This enhancement will implement compliance with RFC 3220 which is about how client and server negotiate a checksum over the request/reply body.

Nice - I was not aware of this - THX

**Comment by DeepDiver1975** [comment]
We should have a look at this RFC and see how this fits into our requirements for the followup implementations regarding checksum handling on the server.

**Comment by dragotin** [comment]
@moscicki fyi, what do you think about this?

**Comment by dragotin** [comment]
Ok, I think this went out of scope for now.
