### ISSUE TITLE
'Files Drop' over PUT

### ISSUE THREAD

**Issue by jorgeboucas** [owncloud/core#22718]
It would be good if one could set a folder to "Files Drop" with PUT.
Thanks!

**Comment by nickvergessen** [comment]
There is no "Files drop" in core which requires a folder being set.
If you mean the  "Files drop" app, then I will move/copy your report to the respective repository:

> ![personal_-_owncloud_-_2016-02-29_13 40 53](https://cloud.githubusercontent.com/assets/213943/13394648/15cd7c04-deea-11e5-8ddc-9b7e729e9e8e.png)

**Comment by jorgeboucas** [comment]
Yes, please! Thank you!

**Comment by nickvergessen** [comment]
https://github.com/owncloud/files_drop/issues/91

**Comment by MorrisJobke** [comment]
Hi @jorgeboucas if you intend to open a support case (because you referred to an enterprise version only app) please contact the support directly - otherwise we are not able to properly track this with you as a customer.

Thanks

**Comment by jorgeboucas** [comment]
Hi @MorrisJobke, I've asked my service provider to contact you guys. Thanks for the support!

**Comment by MorrisJobke** [comment]
> Hi @MorrisJobke, I've asked my service provider to contact you guys. Thanks for the support!

:+1:
