### ISSUE TITLE
Document the event names of Dispatcher events

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#22719]
We started using more and more EventDispatcher events.
I think it would be nice, to document the names:
1. To make it visible which events exist
2. Prevent duplication of event names
3. To prevent typos/casing issues in the event name (constants e.g.)
4. Make it clear that events are somewhat public API and should not be changed.

@DeepDiver1975 

Either in code (lib/public/) or in the developer docs. Docs allow for better comments, while code allows reusage of constants etc.

**Comment by oparoz** [comment]
:+1:

**Comment by PVince81** [comment]
@settermjd 

and yes, you'll ask me to provide a list of existing ones... Assigning to self first to find these
