### ISSUE TITLE
Upgrade to "owncloud-files" package in 9.0 tries **unsuccessfully** to delete the config and data folder inside the ownCloud installation

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#22715]
### Steps to reproduce
1. Install the "owncloud" package (version 8.2) from the official repos
2. Fill the FS a bit (upload several files, create a couple of acounts, etc)
3. Install the "owncloud-files" package (version 9.0) from the official repos

### Expected behaviour
No issues found. The config and data folder remains in the system.

### Actual behaviour
Following message appears:
```
Removing owncloud-server (8.2.2-3.1) ...
dpkg: warning: while removing owncloud-server, directory '/var/www/owncloud/config' not empty so not removed
dpkg: warning: while removing owncloud-server, directory '/var/www/owncloud/data' not empty so not removed
```

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** 8.2.2 upgraded to 9.0.0

**Updated from an older ownCloud or fresh install:** updated from 8.2.2

PD: The folders **WON'T** be deleted, but the message is scary. That's why the low severity.

@jnweiger

**Comment by jnweiger** [comment]
Didn't we have the same messages in the 8.1 -> 8.2 upgrade? 
I remember seeing them before, but am not sure where and when...

**Comment by jvillafanez** [comment]
Maybe for 8.2.1 or 8.2.0. I've checked the latest tests and I haven't found anything for 8.2.2
