### ISSUE TITLE
Share api does not allow update permission of a reshared folder

### ISSUE THREAD

**Issue by nasli** [owncloud/core#22717]
### Steps to reproduce
1.User 1 share a folder with user 2 same server with permissions: read, create and share:21
2.User 2 share this folder with user 3 same server,
3.User 2 try to update permissions of this folder for user 3

`
 curl -u user1:user server/ocs/v2.php/apps/files_sharing/api/v1/shares -X POST -d "path=/ab/&shareType=0&shareWith=user2&permissions=21"
`
`
curl -u user2:user server/ocs/v2.php/apps/files_sharing/api/v1/shares -X POST -d "path=/ab/&shareType=0&shareWith=user3&permissions=1"
`
`
curl -u user2:user server/ocs/v2.php/apps/files_sharing/api/v1/shares/27 -X PUT -d "permissions=17"
`

### Expected behaviour
API allows to update this reshared folder

### Actual behaviour
We can not update the permissions
 `
<statuscode>400</statuscode>
  <message>You can't share your root folder</message>
`

### Server configuration
Today master https://github.com/owncloud/core/commit/a1c02a0567739773c58cbec37c2a1b60887f85e7

Related issue update permissions of a reshared folder https://github.com/owncloud/core/issues/22675

**Comment by rullzer** [comment]
Known and fix is already merged https://github.com/owncloud/core/pull/22683
