### ISSUE TITLE
LDAP Wizard: detecting display name might run after counting users, resulting in 0 users with default attriubute

### ISSUE THREAD

**Issue by blizzz** [owncloud/core#22716]
A thing I have seen today. Seems, email + user display name detectors are run the same time with counting. It does matter for email, but the user display name setting can have an impact.
### Steps to reproduce
1. Have an LDAP set up, where "displayname" attribute is _not_ set
2. Configure Basic LDAP tab, then move to User tab
3. configure as needed, then click "Count Users"
### Expected behaviour
- correct number of users, or "> 1000" should be shown
### Actual behaviour
- 0 users might be shown. 

However, this would only happens once. To force this behaviour again, user display name needs to be set to "displayName" (case sensitive) manually. 
### Server configuration

**ownCloud version:** 9.0

**Comment by PVince81** [comment]
@owncloud/ldap

**Comment by PVince81** [comment]
Please reopen in [user_ldap app repo](https://github.com/owncloud/user_ldap) if issue persists with 10.0.4 and the latest user_ldap app from marketplace.
