### ISSUE TITLE
File owners think they can modify the permissions on reshares, but they can be overriden by sharees

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#22726]
### Steps to reproduce
1. A shares a folder with B
2. B shares a folder with C
3. A removes the _edit_ permission for user C
### Expected behaviour

The _edit_ permission should disappear from B's UI when looking at the share created for C and C should not be able to perform any of the _edit_ actions
### Actual behaviour

B can see the disabled _edit_ permission and even re-enable it.

One solution would be to update B's UI to reflect the real power that he has over that particular share, but nothing prevents B from creating another share with all the permissions enabled.

The real problem is that A can see that the folder is shared with C and thinks he can modify the permissions, but in reality he has not control over that share.
For this reason, the best thing to do would be to remove the permissions from A's UI.
### Server configuration

owncloud master. No idea if this was already happening on 8.2

---

@rullzer @PVince81 @MorrisJobke @schiesbn @jancborchardt

**Comment by PVince81** [comment]
@rullzer can you evaluate severity ? I'll set this to 9.0.1 for now as this seems problematic.

**Comment by rullzer** [comment]
This is not a bug but more a future feature. Yes if B wants he can share again or reenable the edit permisisons. But I fail to see how the situation now is worse than it was with <9.0.0... Now at least the owner of the files can see who has access.

**Comment by oparoz** [comment]
>Now at least the owner of the files can see who has access.

Yes, but owners should not be shown actions they can't perform (false assurances). That's why I think the implementation is incomplete and I would call it a bug ;)

**Comment by rullzer** [comment]
THey can remove the permission..
Just userB can restore it...

**Comment by oparoz** [comment]
1. A removes the permission, thinks he's done
1. B notices the permission is "wrong", restores it
1. C decides he doesn't like the content of the folder and deletes it
1. A can't find the folder any more

This could happen with less drastic changes, such as editing a document.

**Comment by oparoz** [comment]
My point is that if you decide to implement control granularity, then it has to be done right.
If we still want to let owners have control over all the reshares, then something needs to be done to the UI of all people in between and I would call that an enhancement, but I think in the mean time the best course of action would be to remove permissions from owners in order to avoid problems down the line-

**Comment by rullzer** [comment]
So then there is no point in showing the owner the list of everybody who has access anyway... Since they can't do anything about it. Because the same holds for deleting a share. Somebody else could still reshare to that user.

**Comment by rullzer** [comment]
@schiesbn what do you think?

**Comment by oparoz** [comment]
>So then there is no point in showing the owner the list of everybody who has access anyway... Since they can't do anything about it.

Good point actually. There is a similar problem with unsharing. B can just re-add the share..
I still find it useful to see who has access to the item, but any action taken with the current design has more drawbacks than benefits from my point of view.

**Comment by schiesbn** [comment]
I agree with @rullzer. The whole point is that the owner sees who has access to his files, with which permissions and that can also change it, unshare it etc. But if user A gave user B reshare and edit permission, then he gave him this power by choice. So he shouldn't be surprised if the user exercise it. If user A don't want user B to be able to edit and/or re-share the file he has to remove the permissions from user B.

Giving user B re-share permission only with a subset of the permissions he has would be a new feature. But I really don't want to go this way. Sharing and the permissions are already complex enough

**Comment by oparoz** [comment]
>The whole point is that the owner sees who has access to his files, with which permissions

Yes, read-only permissions sound like a good idea.

>If user A don't want user B to be able to edit and/or re-share the file he has to remove the permissions from user B.

Yes, but it's user C we're talking about here. There is no point in letting A modify those since everybody between A and C can modify these.

**Comment by schiesbn** [comment]
> Yes, but it's user C we're talking about here. There is no point in letting A modify those since everybody between A and C can modify these.

Yes, but A is the owner, so he should be able to change it. Btw, not everybody between A and C can change it. Only the users who got the corresponding permissions from A. So this are users user A trust anyway, otherwise he wouln't give them the permissions.

**Comment by oparoz** [comment]
>Yes, but A is the owner, so he should be able to change it

Of course, but the reality is that he has no controls over those permissions, unless he makes the change to the top share. So that view is misleading and that's my problem with it.

**Comment by schiesbn** [comment]
He has control over it, together with the users he empowered to control it as well. But this was a decision by the owner and by purpose. If he doesn't like it or feel that a user miss-used the rights given to him he can reduce his rights.

**Comment by oparoz** [comment]
> If he doesn't like it or feel that a user miss-used the rights given to him he can reduce his rights.

Which might be restored without him knowing about it, defeating the purpose of reducing the rights in the first place.
As the file owner, my decision should be final and it seems the only way to do that right now is to delete the share with C and re-create it using custom permissions. That way B can't share it any more and I have a direct relationship with C.

I'm not sure this is the best way to deal with this.

**Comment by MorrisJobke** [comment]
I noticed https://github.com/owncloud/core/issues/22739 why following this discussion.

**Comment by hodyroff** [comment]
Not a bug, works as designed. @pmaier1 closing if you agree..
