### ISSUE TITLE
Update Sabre to 3.1

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#22724]
In 9.1, update Sabre to 3.1, if possible.

Need to double check the PHP version compatibilities.

**Comment by rullzer** [comment]
Well not argument here that that is what we want ;)

But requires php >=5.5.0

**Comment by RealRancor** [comment]
That would also include https://github.com/fruux/sabre-dav/issues/727 which is a Fix for Windows 10 / Windows Phone CalDAV clients.

**Comment by PVince81** [comment]
> But requires php >=5.5.0

@karlitschek @DeepDiver1975 we might need to hold on this one.

If there are particular small bugfixes in Sabre 3.1 that we'd need in 3.0 we can always ask for backports to 3.0.

**Comment by karlitschek** [comment]
Yes. We can't do this right now. Maybe 9.2

**Comment by PVince81** [comment]
Setting to backlog then.

**Comment by RealRancor** [comment]
SabreDAV 3.2 currently in Beta brings an interesting "improvement":

http://sabre.io/blog/2016/validation-changes/

which might be important for oC. IIRC there where various issues in the past because some clients imported broken vcards or events into oC.

**Comment by PVince81** [comment]
sabre 3.2 PR: https://github.com/owncloud/core/pull/26115
