### ISSUE TITLE
Slow queries in the appconfig table

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#22720]
While analyzing the performance of a system slow query log was enabled. There were 1500 slow query above 100 seconds. (it was a system under high load)

650 of those queries are

```sql
SELECT `appid`, `configvalue` FROM `oc_appconfig` WHERE `configkey` = 'installed_version'; 
```

560 of those queries are

```sql
SELECT * FROM `oc_appconfig`;
```

I think those are the ones we need to improve next. I also think that those queries could be easily cached in-memory without fearing difficult issues.

cc @karlitschek because you are often interested in those performance things.

cc @LukasReschke @nickvergessen @icewind1991 @PVince81 

The other queries are some file cache and share queries where potential caching is really hard.

**Comment by nickvergessen** [comment]
> I also think that those queries could be easily cached in-memory without fearing difficult issues.

Just want to highlight the issue again, enabling an app via console can not purge web memcache...

**Comment by DeepDiver1975** [comment]
> SELECT `appid`, `configvalue` FROM `oc_appconfig` WHERE `configkey` = 'installed_version';

is that one using an index?

**Comment by nickvergessen** [comment]
```
id 	select_type 	table 	type 	possible_keys 	key 	key_len 	ref 	rows 	Extra 	
1 	SIMPLE 	oc_appconfig 	ref 	appconfig_config_key_index 	appconfig_config_key_index 	194 	const 	14 	Using index condition
```
Yes app+configkey is the primary key.

**Comment by nickvergessen** [comment]
@MorrisJobke can we get the number of entries in the table?

**Comment by MorrisJobke** [comment]
```sql
SELECT `appid`, COUNT(*) AS `num_entries` FROM `oc_appconfig` GROUP BY `appid`;
+-----------------------+-------------+
| appid                 | num_entries |
+-----------------------+-------------+
|                       |           1 |
| backgroundjob         |           1 |
| carddavmate           |           3 |
| core                  |          18 |
| enterprise_key        |           3 |
| external              |           2 |
| files                 |           6 |
| files_external        |           4 |
| files_imageviewer     |           2 |
| files_ldap_home       |           4 |
| files_pdfviewer       |           2 |
| files_sharing         |        2692 |
| files_texteditor      |           4 |
| files_trashbin        |           4 |
| files_versions        |           3 |
| gallery               |           3 |
| group_ldap            |           2 |
| remoteStorage         |           2 |
| session_login_tracker |           3 |
| user_ldap             |          55 |
| user_ldap_ext         |           2 |
| user_openid           |           2 |
| user_webfinger        |           2 |
+-----------------------+-------------+
23 rows in set (0.42 sec)  
```

Most of the entries are for the share propagation stuff.

**Comment by MorrisJobke** [comment]
> is that one using an index?

Yes.

**Comment by DeepDiver1975** [comment]
> Most of the entries are for the share propagation stuff.

fishy .....

**Comment by icewind1991** [comment]
those are no longer created for 9.0

**Comment by MorrisJobke** [comment]
> those are no longer created for 9.0

Nice :)

**Comment by rullzer** [comment]
> those are no longer created for 9.0

So should we maybe then add a cleanup job for 9.1?

**Comment by MorrisJobke** [comment]
> So should we maybe then add a cleanup job for 9.1?

That would be nice.

**Comment by icewind1991** [comment]
cleanup step: https://github.com/owncloud/core/pull/23157

**Comment by PVince81** [comment]
cleanup job was merged, closing
