### ISSUE TITLE
504 Gateway Time-out  nginx (when using Hubic Storage)

### ISSUE THREAD

**Issue by 9787954511** [owncloud/core#22723]
### Steps to reproduce
1. I have integrated the Hubic storage from https://github.com/arelange/owncloud-files-hubic
2. i have done everything, last two days i can access my files of hubic in owncloud, but suddenly its thoroughing 504 Gateway Time-out error
3). When i try to access from terminal i can fetch the files from the Hubic.

### Expected behaviour
Its should fetch the data from the Hubic and list in the owncloud

### Actual behaviour
504 gateway Time-out ngnix

### Server configuration
**Operating system**: Ubuntu 14.04.4 LTS

**Web server:** ngnix

**Database:** mysql

**PHP version:**5.5.9.1

**ownCloud version:** (8.2.2)

Fresh install ion.

**External Storage Support, Hubic external storage support**

```
If you have access to your command line run e.g.:
- activity: 2.1.3
  - files: 1.2.0
  - files_external: 0.3.0
  - files_hubic: 8.0.2
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - updater: 0.6

from within your ownCloud installation folder
```

**The content of config/config.php:**

$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' =>
  array (
    0 => 'owncloud.test.com',
  ),
  'datadirectory' => '/var/www/owncloud.test.com/data',
  'overwrite.cli.url' => 'https://lowncloud.test.com',
  'dbtype' => 'mysql',
  'version' => '8.2.2.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '****************',
  'logtimezone' => 'UTC',
  'installed' => true,

```

**Are you using external storage, if yes which one:** local/amazons3/hubic/...

**Are you using encryption:** yes

### Client configuration
**chrome:**

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Error files_hubic Client error response [status code] 404 [reason phrase] Not Found [url] https://******.hubic.ovh.net/v1/*******************************/default/******/*******/  2016-02-29T13:40:16+00:00
Error files_hubic Client error response [status code] 404 [reason phrase] Not Found [url] https://******.hubic.ovh.net/v1/*******************************/default/******/*******/  2016-02-29T13:40:04+00:00
Error files_hubic Client error response [status code] 404 [reason phrase] Not Found [url] https://******.hubic.ovh.net/v1/*******************************/default/******/
```

#### Browser log
```
GET https://owncloud.test.com/index.php/apps/files/ajax/list.php?dir=%2F&sort=name&sortdirection=asc 504 (Gateway Time-out)send @ jquery.min.js?v=86b92546e320594c19c0bccb2170c98d:6x.extend.ajax @ jquery.min.js?v=86b92546e320594c19c0bccb2170c98d:6FileList.reload @ filelist.js?v=86b92546e320594c19c0bccb2170c98d:1345FileList.changeDirectory @ filelist.js?v=86b92546e320594c19c0bccb2170c98d:1248FileList._onUrlChanged @ filelist.js?v=86b92546e320594c19c0bccb2170c98d:455x.event.dispatch @ jquery.min.js?v=86b92546e320594c19c0bccb2170c98d:5v.handle @ jquery.min.js?v=86b92546e320594c19c0bccb2170c98d:5x.event.trigger @ jquery.min.js?v=86b92546e320594c19c0bccb2170c98d:5e.event.trigger @ jquery-migrate.min.js?v=86b92546e320594c19c0bccb2170c98d:2(anonymous function) @ jquery.min.js?v=86b92546e320594c19c0bccb2170c98d:5x.extend.each @ jquery.min.js?v=86b92546e320594c19c0bccb2170c98d:4x.fn.x.each @ jquery.min.js?v=86b92546e320594c19c0bccb2170c98d:4x.fn.extend.trigger @ jquery.min.js?v=86b92546e320594c19c0bccb2170c98d:5OCA.Files.App._onPopState @ app.js?v=86b92546e320594c19c0bccb2170c98d:208OCA.Files.App.initialize @ app.js?v=86b92546e320594c19c0bccb2170c98d:87(anonymous function) @ app.js?v=86b92546e320594c19c0bccb2170c98d:228(anonymous function) @ underscore.js?v=86b92546e320594c19c0bccb2170c98d:768
filelist.js?v=86b92546e320594c19c0bccb2170c98d:1406 Uncaught TypeError: Cannot read property 'permissions' of undefinedFileList.reloadCallback @ filelist.js?v=86b92546e320594c19c0bccb2170c98d:1406(anonymous function) @ jquery.min.js?v=86b92546e320594c19c0bccb2170c98d:4c @ jquery.min.js?v=86b92546e320594c19c0bccb2170c98d:4p.fireWith @ jquery.min.js?v=86b92546e320594c19c0bccb2170c98d:4k @ jquery.min.js?v=86b92546e320594c19c0bccb2170c98d:6r @ jquery.min.js?v=86b92546e320594c19c0bccb2170c98d:6
jquery.min.js?v=86b92546e320594c19c0bccb2170c98d:6 GET https://owncloud.test.com/index.php/apps/files/ajax/getstoragestats.php?dir=%2F 504 (Gateway Time-out)send @ jquery.min.js?v=86b92546e320594c19c0bccb2170c98d:6x.extend.ajax @ jquery.min.js?v=86b92546e320594c19c0bccb2170c98d:6x.(anonymous function) @ jquery.min.js?v=86b92546e320594c19c0bccb2170c98d:6x.extend.getJSON @ jquery.min.js?v=86b92546e320594c19c0bccb2170c98d:6Files._updateStorageStatistics @ files.js?v=86b92546e320594c19c0bccb2170c98d:28Files.updateStorageStatistics @ files.js?v=86b92546e320594c19c0bccb2170c98d:50FileList.updateStorageStatistics @ filelist.js?v=86b92546e320594c19c0bccb2170c98d:1415FileList.reloadCallback @ filelist.js?v=86b92546e320594c19c0bccb2170c98d:1404(anonymous function) @ jquery.min.js?v=86b92546e320594c19c0bccb2170c98d:4c @ jquery.min.js?v=86b92546e320594c19c0bccb2170c98d:4p.fireWith @ jquery.min.js?v=86b92546e320594c19c0bccb2170c98d:4k @ jquery.min.js?v=86b92546e320594c19c0bccb2170c98d:6r @ jquery.min.js?v=86b92546e320594c19c0bccb2170c98d:6

Please help me, highly appreciated, thanks

**Comment by LukasReschke** [comment]
This is a third-party app, please file this to the maintainer at https://github.com/arelange/owncloud-files-hubic

**Comment by 9787954511** [comment]
Thanks @LukasReschke and any other way to integrate the Hubic on owncloud?
