### ISSUE TITLE
Sharees don't have access to the permissions given to them by sharers

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#22737]
### Actual behaviour

As a sharee, I have no idea what I'm able to do (CRUD) with the share and I discover the limits of my power as I go along

### Expected behaviour

As a sharee, I should have access to the permissions given to me by the sharer in order to be able to make informed decisions.

----
@rullzer @PVince81 @schiesbn @jancborchardt

**Comment by rullzer** [comment]
Yes this is known (can't find the issues right now). We are thinking about how to do this properly.

A somewhat working approach right now is `shares?shared_with_me=true&path=<PATH>`. 

Most likely another webdav property will be added or the current OC Permissions extended. CC: @PVince81

**Comment by rullzer** [comment]
PR to solve it will be in https://github.com/owncloud/core/pull/22834 but it will be in the webdav API

**Comment by oparoz** [comment]
Thanks

**Comment by rullzer** [comment]
#22834 is in

**Comment by oparoz** [comment]
Thanks!
