### ISSUE TITLE
CalDAV: support public sharing

### ISSUE THREAD

**Issue by georgehrke** [owncloud/core#22735]
The dav app should support publishing calendars as described in https://trac.calendarserver.org/browser/CalendarServer/trunk/doc/Extensions/caldav-sharing.txt

cc @DeepDiver1975 

First we need to implement caldav sharing as below - after that being done we need to see where publishing is being hooked in

# Steps to take to make this happen
1. Add Sabre\CalDAV\SharingPlugin to v1 and v2 dav routes
2. OCA\DAV\CalDav\Calendar has to implement interface IShareableCalendar (beware of meothod conflicts)
3. Add interface SharingSupport to apps/dav/lib/CalDav/CalDasvBackend.php (beware there might be conflicts with existing method used by our own sharing) - mainly the 
4. Add sharing tests of the caldavtester project

 # Update:
looks like we need to reimplement Sabre\CalDAV\SharingPlugin - support for publish-url is missing

**Comment by gour** [comment]
:+1:

**Comment by crti** [comment]
can't wait to use this :+1:

**Comment by DeastinY** [comment]
Nice !

**Comment by thomasgraf** [comment]
is longingly expected :+1:

**Comment by MasterFox** [comment]
please integrate it soon - thx :+1:

**Comment by georgehrke** [comment]
moving to 9.2

**Comment by tcitworld** [comment]
How would you see the `publish-url` format ? The files app uses a token name but maybe it isn't necessary here.

**Comment by georgehrke** [comment]
I'd go with a token as well.

**Comment by DeepDiver1975** [comment]
> How would you see the publish-url format ? The files app uses a token name but maybe it isn't necessary here.

good question - I'd vote for using a token as part of the url.
We have to see how to generate and store the token because there is also a pre-publish-url which should hold the url even before the publishing was done.

**Comment by georgehrke** [comment]
Maybe some hash over calendar id and some dedicated (new) secret from config.php?

**Comment by DeepDiver1975** [comment]
> Maybe some hash over calendar id and some dedicated (new) secret from config.php?

question is if we need only obscurity or real secret tokens

**Comment by lpirl** [comment]
Not quite sure if this issue has an effect on the following possibly desired feature:
It would be nice to be able to (re)generate the sharing URL upon request (as in: revoke access regarding the old URL, grant access by handing out the newly generated URL).

**Comment by DeepDiver1975** [comment]
Generating the token based on a hash should be fine - we will anyhow only expose calendars which are published. 

We can expose public calendars in a dav resource of it's own like:

https://example.com/remote.php/dav/public-calendars/1234567890

the collection public-calendars will only allow enumeration in debug mode.

**Comment by DeepDiver1975** [comment]
Before we talk about publishing we need to implement the sharing mechanisms and in a second step we add the publishing.

Both sharing and publishing information should go into the existing oc_dav_share table - we might need to add some columns - let's see

**Comment by tcitworld** [comment]
Does this mean that support for notifications/invites has to be brought ? I don't see much sharing mechanism to implements apart from the ones mentioned on top.

**Comment by DeepDiver1975** [comment]
> Does this mean that support for notifications/invites has to be brought ?

Invites are optional as far as I can tell - regarding notifications I cannot really tell - this is something to find out while integrating this.

I suggest to develop this while testing with Apples iCal application - if at hand

**Comment by DeepDiver1975** [comment]
Case closed on the server side
