### ISSUE TITLE
Sharees should be shown error messages if they try to perform actions they're not allowed to

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#22738]
### Steps to reproduce
1. A shares a folder with B
2. A removes the delete permission
3. B creates a new folder inside the share
4. B tries to move some of the file to that new folder via drag and drop
### Expected behaviour

I should be able to move the files or be told that I'm not allowed to do so.
### Actual behaviour

Nothing happens when I drop the files into the folder.

---

@rullzer @PVince81 @schiesbn @jancborchardt

**Comment by PVince81** [comment]
Hmm strange. I thought this was already implemented, could also be a regression from the move to Webdav.

**Comment by rullzer** [comment]
Ok I checked and we don't even send something to the server. So it seems we block this directly in JS.
