### ISSUE TITLE
CalDAV: send out email notifications for VALARMs

### ISSUE THREAD

**Issue by georgehrke** [owncloud/core#22734]
The dav app should send email alarms configured by the user.

cc @DeepDiver1975

**Comment by DeepDiver1975** [comment]
Maybe something to be integrated into the activity stream?

@nickvergessen @karlitschek

**Comment by karlitschek** [comment]
Definitely something for the activity stream but also notifications.

**Comment by toxic-tonic** [comment]
Hi,

do I get that right, the mail-notification is not jet a function but on the list for enhancements? So there is no timeline for the feature to be working?

Thanks

Tobias

**Comment by georgehrke** [comment]
> do I get that right, the mail-notification is not jet a function but on the list for enhancements? 

Exactly.

> So there is no timeline for the feature to be working?

There is an milestone assigned 😉 

<img width="1025" alt="caldav__send_out_email_notifications_for_valarms_ _issue__22734_ _owncloud-core_safari_technology_preview__today_at_1_41_00_pm" src="https://cloud.githubusercontent.com/assets/1250540/15112035/bff9ea04-15eb-11e6-9606-fa09876bf00f.png">

**Comment by DeepDiver1975** [comment]
I'm moving this to 9.2 - there is already a big backlog ....

**Comment by niko886** [comment]
I just wanted you to know, that I think, that this is the must have feature :)
