### ISSUE TITLE
log_authfailip not documented

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/core#22745]
In multiple places I read about parameter `log_authfailip` for ``config.php``. Is it real? Does it still exist? Documentation does not mention it: https://doc.owncloud.org/search.html?q=log_authfailip

**Comment by RealRancor** [comment]
@LukeOwncloud That was removed some time ago: https://github.com/owncloud/core/issues/13094

**Comment by LukeOwncloud** [comment]
Ouch! Don't know why I didn't find that issue on my own. Sorry!
