### ISSUE TITLE
logtimezone not documented nor set automatically

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/core#22748]
By default the datestamp in log file uses UTC formatting:

    "time":"2016-03-01T10:25:58+00:00"

However, this is very unconvenient as it is not easily readable. Rather, the local timezone should be used:

    "time":"2016-03-01T11:26:42+01:00"

This can be achieved by adding config value (see ``lib/private/log/owncloud.php``):

    'logtimezone' => 'Europe/Berlin'

This should be done automatically, e.g. by using the server time zone `date_default_timezone_get();` (the user timezone is probably not wanted here?)

Further, the config parameter should be documented: https://doc.owncloud.org/search.html?q=logtimezone

**Comment by RealRancor** [comment]
> Further, the config parameter should be documented: https://doc.owncloud.org/search.html?q=logtimezone

As written in your previous issue https://github.com/owncloud/core/issues/22745 you can't use the search there.

The logtimezone itself is documented in your config.sample.php as well as in https://doc.owncloud.org/server/8.2/admin_manual/search.html?q=logtimezone

**Comment by DeepDiver1975** [comment]
I'm closing this since it can easily be configured. UTC as reasonable default is accepted for a long time.

**Comment by LukeOwncloud** [comment]
> for a long time

And that is the reason not to change it? If I personally set a system wide default (via php.ini), I expect applications to use it.

But okay, the actual issue is: https://github.com/owncloud/owncloud.org/issues/533

Background:
The problem first occured when I wanted to setup fail2ban to protect owncloud. The problem there: fail2ban does not parse the time format correctly (https://github.com/fail2ban/fail2ban/issues/1342)
Finding out how to change it was a pain in the butt. Maybe it would have been easier if that search worked...

**Comment by DeepDiver1975** [comment]
> And that is the reason not to change it?

I see this as some kind of poll - one person whats it to be changed - but nobody else.
So it is expected that as soon as we change the behavior that all the others will start to cry. :wink:

**Comment by DeepDiver1975** [comment]
Furthermore this was already proposed in the past and rejected

**Comment by LukeOwncloud** [comment]
You are probably referring to https://github.com/owncloud/core/issues/4564. So it is not just me! :smile: 
But config.php is fair enough. Thanks for your quickly reply!
