### ISSUE TITLE
Adding a column to the filecache is super time consuming (depending on db)

### ISSUE THREAD

**Issue by butonic** [owncloud/core#22747]
The resulting ALTER TABLE for the [added checksum column in OC9](https://github.com/owncloud/core/pull/21997) will create a temp table with tha same columns as the filecache, add the colum, COPY the table content and finally rename it and delete the original table. Big installations will experience a very long downtime as we have seen today with a huge activity table change when updating to oc 8.2.2.

In this case mysql 5.5 was used. In the documentation for it I see no way around copying the contents: http://dev.mysql.com/doc/refman/5.5/en/alter-table.html#idm140603778401088 It seems this has still not changed with mysql 5.7: http://dev.mysql.com/doc/refman/5.7/en/innodb-create-index-overview.html#idm140023654764880 although it should be less of a performance hog.

cc @MorrisJobke @DeepDiver1975 @karlitschek

**Comment by butonic** [comment]
Postgres may omit rebuilding the table if no default value is specified: http://www.postgresql.org/docs/9.5/static/sql-altertable.html#AEN72358

**Comment by karlitschek** [comment]
yes. this is actually the wanted behavior. we want to simulate the upgrade because we actually touch the real table. the reason is that we had a ton of bugs before triggered by combinations of specific db types and servers with specific limitations. certain sometimes broken entries in the table, size limitations ir the combination of all if that.
so we destroyed user data in the past.
the fix is to copy the table first and test it. it is accepted that this takes some times but is better then destroying the database.
experienced admin can skip this if they tested the upgrade manually befores

**Comment by MorrisJobke** [comment]
> the fix is to copy the table first and test it. it is accepted that this takes some times but is better then destroying the database.

It's not our code that copies the table. It's mysql that copies the table. So the migration will copy the table (1) -> run the upgrade steps -> that itself triggers a copy of the same table in mysql (2). Then we run the same on the actual code (3+4).

This means we copy the whole table 4 times instead of 2 times. This totally kills bigger installations on mysql.

I guess we either need a way to figure out why mysql copies the table sometimes when a column is added (I guess this is the case when the whole table doesn't fit in memory).

**Comment by MorrisJobke** [comment]
@karlitschek @DeepDiver1975 You asked me about this. It seems that I was wrong here. Today I noticed that the complete activity table was copied while running the alter table statement to add two columns (https://github.com/owncloud/activity/commit/0470887a2a75c018f67ed26574a35cc6bb3d2b28).

**Comment by MorrisJobke** [comment]
We should re-evaluate the add of the column to the file cache because this could add a serious problem.

Ref https://github.com/owncloud/core/pull/21997

@karlitschek @DeepDiver1975 Sorry - I did a mistake by stating that this will not be a problem. :cry:

**Comment by MorrisJobke** [comment]
@PVince81 @nickvergessen I remind that Frank said that you tested this and it worked fine. What exactly was the test scenario?

**Comment by PVince81** [comment]
I think @karlitschek tested it himself and it was fast.

**Comment by DeepDiver1975** [comment]
adding sev1 - this needs to be sorted out

**Comment by MorrisJobke** [comment]
I updated my description above - it's a ratio of 1 to 4.

**Comment by PVince81** [comment]
To clarify: this report is NOT about simulated update.
It's about the ALTER TABLE that happens afterwards.

**Comment by DeepDiver1975** [comment]
http://dev.mysql.com/doc/refman/5.7/en/alter-table.html - see 'Storage, Performance, and Concurrency Considerations'

**Comment by MorrisJobke** [comment]
> I think @karlitschek tested it himself and it was fast.

The question is how big was the table and how much memory was available. This happened on an instance with 177M entries in the activity table.

**Comment by MorrisJobke** [comment]
> To clarify: this report is NOT about simulated update.
> It's about the ALTER TABLE that happens afterwards.

Correct.

**Comment by DeepDiver1975** [comment]
Reading the docs the behavior is depending on the mysql version

**Comment by MorrisJobke** [comment]
This was a mariadb 5.5.48 on RHEL 7.

**Comment by DeepDiver1975** [comment]
looks like the behavior can be influenced by setting  ALGORITHM=INPLACE in the command.
InnoDB is supporting this

**Comment by MorrisJobke** [comment]
> looks like the behavior can be influenced by setting ALGORITHM=INPLACE in the command.

@butonic Didn't you say that this does not work in innodb?

**Comment by DeepDiver1975** [comment]
http://dev.mysql.com/doc/refman/5.7/en/innodb-online-ddl.html

'The online DDL feature enhances many types of ALTER TABLE operations to avoid table copying, blocking of DML operations while DDL is in progress, or both. '

**Comment by DeepDiver1975** [comment]
requires mylsq 5.7 \o/

**Comment by karlitschek** [comment]
Sorry for the misunderstanding. I see now that this is about the alter table command itself and not our code.

**Comment by karlitschek** [comment]
I indeed did a test on my local machine with some automatically generated data. obviously not a real production environment. And in this case this was surprisingly fast to add a column to an existing huge table. basically instant. I used a a new mariadb. The latest that comes with Ubuntu 15.10

**Comment by karlitschek** [comment]
I don't see an alternative to the current approach. It was always clear that we have long db migrations again once we touch the filecache table. This was expected. The only alternative would be to put the checksum into a new table and join them. This would mean fast migration and slower during operation. ->  No an option. 
Let' explore if online ddl can help in new mysql/mariadb versions. Otherwise we have to live with long running db migrations.
By the way. it was the plan of the nur updater to make it possible to do the db alter tables asynchronously before the real update. unfortunately this  wasn't done for 9.0

**Comment by nickvergessen** [comment]
What we could also do is to give the `ALTER TABLE` command to the customers before the update.
So they can modify the table in the night before the update, where usage is low.

Our updater then does not need to create the table anymore and therefor is faster.

**Comment by karlitschek** [comment]
@nickvergessen Yes. This is what I meant earlier. :-)

**Comment by nickvergessen** [comment]
> @nickvergessen Yes. This is what I meant earlier. :-) 

And what I meant is, that although the updater is not capable to do that, we can still achieve this manually, so the update is faster and we don't need to do big changes now anymore.

**Comment by DeepDiver1975** [comment]
> looks like the behavior can be influenced by setting ALGORITHM=INPLACE in the command.

What about adding the algorithm statement to the sqls we are generating?
Worth a try?

**Comment by MorrisJobke** [comment]
> What about adding the algorithm statement to the sqls we are generating?
> Worth a try?

I think so.

**Comment by butonic** [comment]
@DeepDiver1975 NO, `ALGORITHM=INPLACE` cannot be used when adding columns. It will produce an erre. See the [5.7 documentation on DDL](http://dev.mysql.com/doc/refman/5.7/en/innodb-create-index-overview.html#idm140023654764880):

> Concurrent DML but Table Copy Still Required
> -----------------------------------------------------------
> 
> Some other ALTER TABLE operations allow concurrent DML but still require a table copy. However, the table copy for these operations is faster than it was in MySQL 5.5 and prior.
> 
> * **Adding, dropping, or reordering columns.**

And from [the mysql .7 `ALTER TABLE` documentation](http://dev.mysql.com/doc/refman/5.7/en/alter-table.html#idm140023676116464):
> As of MySQL 5.7.4, ALTER TABLE upgrades MySQL 5.5 temporal columns to 5.6 format for ADD COLUMN, CHANGE COLUMN, MODIFY COLUMN, ADD INDEX, and FORCE operations. This conversion cannot be done using the INPLACE algorithm because the table must be rebuilt, so specifying ALGORITHM=INPLACE in these cases results in an error. Specify ALGORITHM=COPY if necessary.

**Comment by butonic** [comment]
I really think the only thing we can do is plan large installations in advance. Any Ideas welcome.

**Comment by karlitschek** [comment]
@nickvergessen Sure. With some manual hacking like: somehow extract the alter tables commands and prevent that they are executed during upgrade. 
What I meant is that we should do this nice as a step in the upgrade process.
But you are right. We COULD do this also manually today.

**Comment by PVince81** [comment]
So, is there anything to do in the scope of 9.0 before the freeze ?

It seems that we're out of quick workarounds or do you guys want to keep looking ?
(apart from just creating the column manually in the DB before running the upgrade)

**Comment by butonic** [comment]
For big installations subsequent user migrations might allow a better handling of this scenario. 

IMO we should mention this in the release notes.

**Comment by PVince81** [comment]
Tagging as release not, @carlaschroder 

Need confirmation from you guys for adding this to the release notes for now with an upcoming fix later.

**Comment by cmonteroluque** [comment]
yes, 9.0.1 as the updater goes forward...

**Comment by PVince81** [comment]
So if I understand well, we need to adjust the updater to give estimates ?
Assigned @VicDeo

**Comment by VicDeo** [comment]
er, I wouldn't touch that with a 10 foot pole because it might kill kittens...
But there IS a way to speedup ALTER TABLE for MySQL.
Something like that
```
CREATE TABLE new_table LIKE old_table;
ALTER TABLE new_table ADD new_column _datatype_;
INSERT INTO new_table SELECT *, NULL FROM old_table;
DROP TABLE old_table;
RENAME TABLE new_table TO old_table;
```

**Comment by MorrisJobke** [comment]
> But there IS a way to speedup ALTER TABLE for MySQL in particular.

Why should this be faster?

**Comment by VicDeo** [comment]
@MorrisJobke It's my own recipe but something that I found online. This should be measured to say for sure. The main reason is a lack of a temporary table I guess.

**Comment by VicDeo** [comment]
A planned workaround is asking user to run `ALTER TABLE`  query on his own in case database platform is MySQL/Postrge and number of entries in  `filecache`  table exceeds a certain threshold.

**Comment by MorrisJobke** [comment]
> A planned workaround is asking user to run ALTER TABLE query on his own in case database platform is MySQL/Postrge and number of entries in filecache table exceeds a certain threshold.

How does this speed up the process? What is this threshold?

**Comment by VicDeo** [comment]
@MorrisJobke
> How does this speed up the process?

This is a workaround and not the solution. 

> What is this threshold?

I think it's something like ~300k (and more) filecache entries. What's your opinion?

**Comment by VicDeo** [comment]
some benchmarks that I've done on solidgear docker instance by bumping version and adding `checksum` filed to filecache (and droping the column on the next iteration)
MySQL 5.1 (chosen intentionally because 5.5 is faster)

 num of filecache entries | time, seconds 
------------ | -------------
 1 000 | 3-6s 
 10 000 | ~ 8s 
 100 000 | 170-180 
 300 000 | ~ 1300

**Comment by butonic** [comment]
There is official documentation on how to improve bulk insert performance: http://dev.mysql.com/doc/refman/5.5/en/optimizing-innodb-bulk-data-loading.html

Basically disabling index updates and uniqueness checks. Be aware that enabling them after the insert operation causes a rebuild of the index. It will still be faster than updating the index on every insert, however.

**Comment by VicDeo** [comment]
@butonic it's not possible to disable indexes completely for innodb storage and altering is not the same with bulk insert.

The only profit I see is  DB copying speedup: https://github.com/owncloud/core/pull/23395

Here are four test results on the same container (Schema change was nothing but adding/droping `checksum` column to `filecache` table with 300 000 entries in it):
Time of `occ upgrade` completion (including schema check) in seconds

operation | 8.2.3 | 8.2.3 + #23395
------|--------|------
add column | 1417 | 1131
drop column | 1360 |  1085

this doesn't speed up the migration itself, just a test test migration performance tweak

**Comment by guruz** [comment]
Why not have a new table for the checksum?
With a nice index from fileId->(checksumType,checkSum)
That way you also save space for directories or files that don't have a checksum

**Comment by nickvergessen** [comment]
But we would need to left join the column all the time, which is even worse for huge installations

**Comment by MorrisJobke** [comment]
> Why not have a new table for the checksum?

Because it's too late.

**Comment by VicDeo** [comment]
@PVince81 @DeepDiver1975 So, what finally needs to be done? 

Add the following to update notification in  Web UI for  stable8.2 && MySQL && oc_filecache ahs more than 200k entries?:
>According to your filecache table size upgrade might take too long. Please run the following query on your database to speedup the upgrade process: ALTER TABLE oc_filecache ADD COLUMN checksum varchar(255) DEFAULT NULL AFTER permissions; `

**Comment by PVince81** [comment]
Sounds good to me. @karlitschek @DeepDiver1975 @butonic @MorrisJobke what do you think ?

**Comment by karlitschek** [comment]
we discussed this and we don't want to have a new table for the. we optimize for production speed instead of upgrade speed

**Comment by karlitschek** [comment]
I think we should add a warning to the web ui and the cli if you have more then 200k. Please check the original updater 2.0 issue for the right place in the flow where we have the hint about the length of the upgrade.
We should use this text instead:

You have an ownCloud installation with over 200.000 files so the upgrade might take a while. The recommendation is to use the command-line instead of the web interface for big ownCloud servers. Hint: You can speed up the upgrade by executing  this SQL command manually: ALTER TABLE oc_filecache ADD COLUMN checksum varchar(255) DEFAULT NULL AFTER permissions; `


Not. Please show the hint only if using mysql.
Please show the CLI hint only in the web ui.

Does this make sense?

**Comment by VicDeo** [comment]
@karlitschek shouldn't this notice be added to 8.2 in order to be displayed before any action takes place?

**Comment by karlitschek** [comment]
I thin 9.0.x is fine

**Comment by nickvergessen** [comment]
But the update to 9.0.x is the one causing the troubles?! :confused:

**Comment by MorrisJobke** [comment]
> But the update to 9.0.x is the one causing the troubles?!

And then already the new 9.0.x code is available before the upgrade step has run. So this should be fine ;)

**Comment by PVince81** [comment]
So if I understand well the warning has been added 9.0.1, closing hence.

Please reopen if you think there is something left to do.
