### ISSUE TITLE
Tooltip in federated sharing is not showing the full url.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#22746]
### Steps to reproduce

Having admin in serverA and admin in serverB
1. Share a file from admin@serverA with admin@serverB.
2. In ServerB accept the share.
3. In ServerA open the sidebar of the shared file and hover the shared name

### Expected behaviour
Tooltip shows full url.

### Actual behaviour
Tooltip shows the same information.

![screen shot 2016-03-01 at 09 35 07](https://cloud.githubusercontent.com/assets/9048796/13465159/a901abde-e094-11e5-99c4-78b9a2adce5b.png)

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"9.0.0.13","versionstring":"9.0.0 beta 2","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No

**Logs**

```
```

### Client configuration

**browser**
Chrome

**Comment by jancborchardt** [comment]
Hm, why is the »http://« shown here? Cutting that would already help cc @ErikPel

**Comment by ErikPel** [comment]
@jancborchardt you can use https as well so I thought it might be relevant to show it.  Not sure if it acually makes difference. It still doesn't fix the problem with really long urls(or usernames), just fixes this specific case.
Not saying taking off the http would be bad thing to do. Maybe we can do both take off the http and then breaking the url to multiple lines.

What do you think?

**Comment by jancborchardt** [comment]
@ErikPel yeah, I guessed it was because of https. Nevertheless, that complicates the address so I would cut both https:// and http://. I’d also not necessarily show the port number – definitely not in the share list display because there’s too little space.

If there’s still problems, we can break after the @ in the tooltip like:

> username@
> remoteserver.com

**Comment by ErikPel** [comment]
Good points. Can you tell me which element hover triggers the tooltip so I can use chrome dev tools to always show it and try different options?

**Comment by jancborchardt** [comment]
I guess it’s the element of the name. @MorrisJobke @PVince81 do the tooltip elements have a specific class `tooltip` like `tipsy` in the past?

**Comment by ErikPel** [comment]
@jancborchardt there is has-tooltip class but triggering hover on it does nothing

**Comment by jancborchardt** [comment]
That’s because it’s done via JS I assume. It calls a tooltip function on mouse over. cc @owncloud/javascript for help.

**Comment by blizzz** [comment]
Yes, it's triggered by JS, you can use the console and do ``$('#elementId').tooltip('show');`` to have see it permanently.

**Comment by PVince81** [comment]
Just make sure the `title` attribute on the element has the correct value. The jquery tooltip plugin takes the value from there.

**Comment by SergioBertolinSG** [comment]
I find annoying to not being able to copy the full url, is it possible to show the entire url clicking somewhere instead of just showing the tooltip?

![screen shot 2016-05-19 at 14 37 27](https://cloud.githubusercontent.com/assets/9048796/15393762/52f45732-1dcf-11e6-8020-0734cd63e85f.png)

Perhaps detecting a click in the three dots and showing the entire url?
