### ISSUE TITLE
Disable etag propagation outside of "files/" in home storage

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#22758]
@icewind1991 that would be the next step to improve etag propagation performance.

@schiesbn

**Comment by PVince81** [comment]
@butonic didn't you want to look into etag propagation perf ? That could be a start

**Comment by PVince81** [comment]
@mrow4a in case you're interested at some point

**Comment by mrow4a** [comment]
Can you add more details here, some context and points in the code?

**Comment by PVince81** [comment]
Could be as simple as extending this array: https://github.com/owncloud/core/blob/stable10/lib/private/Files/Cache/HomePropagator.php#L34

Or make it a whitelist instead of a blacklist
