### ISSUE TITLE
[8.2.2] Erased shares are still in DB

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#22759]
Similar as the issue: https://github.com/owncloud/core/issues/22431 I saw that the oc_share still have the old erased shares. "Trash" information is kept in the database.

### Steps to reproduce
1. Create a Folder and share with groups and/or users
2. Delete the folder, if you want from the trashbin too 
3. Check the database : oc_share and the registers is still there

### Expected behaviour
if I erase a folder, the share in the database should be erased too

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache 2.4

**Database:**
mysql  Ver 15.1 Distrib 5.5.46-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
8.2.2

**Updated from an older ownCloud or fresh install:**
8.1.0.8 -> 8.1.3.0 -> 8.1.4 -> 8.2.2

**Where did you install ownCloud from:**
TAR

**List of activated apps:**
```
Enabled:
  - activity: 2.1.3
  - bookmarks: 0.6
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - delete_confirmation: 1.1.0
  - direct_menu: 0.5
  - documents: 0.11.0
  - files: 1.2.0
  - files_external: 0.3.0
  - files_mv: 0.8.1a
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - notifications: 0.1.0
  - ownnote: 1.05
  - provisioning_api: 0.3.0
  - registration: 0.1.0
  - sharelinks: 1.0.1
  - tasks: 0.8.1
  - templateeditor: 0.1
  - updater: 0.6
```

**The content of config/config.php:**
```
<?php
$CONFIG = array (
  'instanceid' => 'XXXXXX',
  'passwordsalt' => 'XXXXXX',
  'secret' => 'XXXXXX',
  'trusted_domains' =>
  array (
    0 => 'cloud.damken.com',
  ),
  'datadirectory' => '/mnt/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.2.2.2',
  'dbname' => 'XXXXXX',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'XXXXXX',
  'dbpassword' => 'XXXXXX',
  'loglevel' => 0,
  'logtimezone' => 'Europe/Berlin',
  'log_rotate_size' => 10485760,
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'XXXXXX',
  'mail_domain' => 'damken.com',
  'mail_smtpsecure' => 'XXXXXX',
  'mail_smtpauth' => 1,
  'mail_smtpauthtype' => 'XXXXXX',
  'mail_smtphost' => 'damken.com',
  'mail_smtpport' => 'XXXXXX',
  'mail_smtpname' => 'XXXXXX',
  'mail_smtppassword' => 'XXXXXX',
  'theme' => 'damken',
  'maintenance' => false,
  'appstoreenabled' => true,
  'appstoreurl' => 'https://api.owncloud.com/v1',
  'appstore.experimental.enabled' => true,
  'memcache.local' => '\\OC\\Memcache\\ACPu',
  'filelocking.enabled' => 'true',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => '127.0.0.1',
    'port' => 6379,
    'timeout' => 0,
    'dbindex' => 0,
  ),

  'trashbin_retention_obligation' => '7,30',
  'versions_retention_obligation' => '15,90',
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
```
NFS->
10.1.10.102:/mnt/md1/public/owncloud  /mnt/owncloud nfs soft,intr,rsize=8192,wsize=8192
```
**Are you using encryption:** yes/no
No

**Comment by PVince81** [comment]
@cdamken did you try clearing the trashbin ?
The share information stays in case you restore the file/folder from trash.

**Comment by PVince81** [comment]
Okay, I see you have it in the steps. Deleting the files from trash is an important step.

Also, depending how you deleted the folder, you might also need to run cron.php for the orphaned shares to get cleared. One scenario affected by this is when you share "folder/subfile.txt" but delete "folder". Deleting the shares for all subfiles in every sub-sub-sub-directory would be expensive.
This is why the clearing of orphaned shares is happening in a background job.

**Comment by cdamken** [comment]
> This is why the clearing of orphaned shares is happening in a background job.

You are right, today it disappeared! I tried yesterday to run the cron.php, but didn't clean at that moment, probably was only scheduled for the night or in some specific time.
