### ISSUE TITLE
Missing translations in settings-admin.php

### ISSUE THREAD

**Issue by vidaren** [owncloud/core#22767]
### Steps to reproduce
1. Select a non-English language
2. Activate the Federation app
3. Go to the Admin page, section Federation
4. Observe the missing translations

### Expected behaviour
All text should be translated.

### Actual behaviour
The following are not translated:
- "Add server automatically once a federated share was created successfully" checkbox text
- "Trusted ownCloud Servers" heading
- "+ Add ownCloud server" button text
- "ownCloud server" in edit field after clicking the "+ Add ownCloud server" button  

### Server configuration
**Operating system**: 
Linux

**Web server:**
Nginx

**Database:**
SQLite

**PHP version:**
5.6

**ownCloud version:** (see ownCloud admin page)
ownCloud 9.0.0 beta 2 (daily) Build:2016-03-01T04:41:06+00:00 52d217d77519ed95a18237b09a351f83a0ae7f47

**Updated from an older ownCloud or fresh install:**
Fresh

**Where did you install ownCloud from:**
Daily archive download.

**Signing status (ownCloud 9.0 and above):**

```
N/A
```

**List of activated apps:**

```
Federation, standard
```

**The content of config/config.php:**

```
N/A. Rest of template truncated, all N/A
```

EDIT: The strings are not in Transifex because they are not in t() calls in settings-admin.php.

**Comment by blizzz** [comment]
@schiesbn
