### ISSUE TITLE
oC 9.0 beta2: file integrity check aborts on permission error

### ISSUE THREAD

**Issue by vanMacG** [owncloud/core#22762]
This is a follow up of #22698 
Setup of system and configs are the same.

Steps to reproduce:
1. create first extra folder/file in oC root. e.g. /extra_blabla/extra_file.txt
2. create second extra folder/files in oC root. e.g. /logs/access_log...
3. first extra folder is read/writeable by oC
4. second extra folder folder is not accessible by oC
--> file integrity check "aborts" on the second extra folder and doesn't report the first extra folder.

In the following example 'www-data' is the user of apache running oC.

Output of file integrity when both folders are accessible:
- EXTRA_FILE
	- extra_blabla/extra_file.txt
	- logs/access_log_2016-02-29.gz
	- logs/access_log_betacloud_xxx_eu_2016-02-29.gz
	- logs/access_log_betacloud_xxx_eu_2016-02-28.gz
	- logs/access_log_2016-02-28.gz
![integrity2](https://cloud.githubusercontent.com/assets/8269814/13438886/393b353a-dfeb-11e5-954c-748845d7220c.PNG)

When changing permissions so oC can't access (700 with different user):
- EXCEPTION
	- UnexpectedValueException
	- RecursiveDirectoryIterator::__construct(/www/htdocs/w0069a6f/testing/owncloud/logs): failed to open dir: Permission denied
![integrity1](https://cloud.githubusercontent.com/assets/8269814/13438936/835b4f6a-dfeb-11e5-9cd6-8d7bef272154.PNG)

**Comment by LukasReschke** [comment]
All mine :)

**Comment by LukasReschke** [comment]
I had some more thoughts about this. While this is not the most intuitive behaviour it is actually acceptable.

The other option would be to display a warning "unreadable folder". This won't change much compared to the generic PHP exception.

**Comment by vanMacG** [comment]
@LukasReschke I agree with you that a php exception or a warning message results in exactly the same. My point was that the hole integrity check blows up and doesn't display the other errors (file differences).
So in a case where there is, for what ever reason, a file/folder which is not readable, you don't get any information from the ingetrity checker. 
What I expected was an output/information like "there is a folder unaccessible, but the rest is fine" or "there is a folder unaccessible, and owncloud/core/filexy.php is corrupt".
