### ISSUE TITLE
[LDAP] A lot of 'noise' in owncloud.log showing LDAP users in users view

### ISSUE THREAD

**Issue by davitol** [owncloud/core#22770]
### Steps to reproduce

1. Configure a LDAP users backend
2. Go to the users view

### Expected behaviour

The users are shown in users page and no logs are shown

### Actual behaviour

owncloud.log file is full of logs

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 9.0.0 beta 2 (daily) Build:2016-02-25T04:15:38+00:00 faf65e73b778867d36f0e13dd1b0f1a4ef1f4723

### Logs

```
{"reqId":"r+kyRntoy99t1xLKiOZs","remoteAddr":"XX.XX.XXX.XX","app":"PHP","message":"Argument 9 passed to OCA\\user_ldap\\lib\\user\\User::__construct() must implement interface OCP\\IUserManager, instance of OCA\\user_ldap\\lib\\user\\Manager given, called in \/opt\/owncloud\/apps\/user_ldap\/lib\/user\/manager.php on line 121 and defined at \/opt\/owncloud\/apps\/user_ldap\/lib\/user\/user.php#111","level":3,"time":"2016-03-02T09:09:59+00:00"}
{"reqId":"QJnexZj+GWVUcLeE5Gga","remoteAddr":"XX.XXX.XXX.XX","app":"PHP","message":"Argument 7 passed to OCA\\user_ldap\\lib\\user\\Manager::__construct() must implement interface OCP\\IUserManager, instance of OCA\\user_ldap\\lib\\user\\Manager given, called in \/opt\/owncloud\/apps\/user_ldap\/lib\/proxy.php on line 76 and defined at \/opt\/owncloud\/apps\/user_ldap\/lib\/user\/manager.php#90","level":3,"time":"2016-03-02T09:10:27+00:00"}
```
This log is shown hundreds of times

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration
**Browser:** Firefox for Mac OSX

@blizzz

**Comment by blizzz** [comment]
Fix in https://github.com/owncloud/core/pull/22778
