### ISSUE TITLE
AD Login issue when user have workstation restriction (logon to)

### ISSUE THREAD

**Issue by frungillo** [owncloud/core#22772]
### Steps to reproduce
1. Create an AD user with LogonTo property activated (eg. single workstation access restrict)
2. Logon to OC webUI or windows client with those credentials
### Expected behaviour

Also providing credentials correctly, OC fail logon with message "invalid credentials"
### Actual behaviour

If the credentials are valid and meet the criteria, of course I expect OC let me access
### Server configuration

Ubuntu Server 15.10

Apache2

MySql

php 5.5

OC 8.2.2

/*****/
For some reason, the php ldap_bind () function, is presented to the LDAP server as if the user were logging directly on the AD server instead owncloud machine.
This situation leads to users that have restrictions on the machines that can be accessed, an access error (531 - User is not authorized to access this wokstation).
This error is produced by the Domain server only when past credentials are valid but do not have access to a specific workstation.

I solved the problem,  could be helpful for someone or for developing:

I am only interested that the credentials are valid, so I made a small change to the source app ldap_user.
Specifically, I changed the "bind ()" function of the class connection (apps/user_ldap/lib/connection.php):

`
public function bind() {
      static $getConnectionResourceAttempt = false;
      if(!$this->configuration->ldapConfigurationActive) {
         return false;
      }
      if($getConnectionResourceAttempt) {
         $getConnectionResourceAttempt = false;
         return false;
      }
      $getConnectionResourceAttempt = true;
      $cr = $this->getConnectionResource();
      $getConnectionResourceAttempt = false;
      if(!$this->ldap->isResource($cr)) {
         return false;
      }
      /*
      $ldapLogin = @$this->ldap->bind($cr,
                              $this->configuration->ldapAgentName,
                              $this->configuration->ldapAgentPassword);
                              */
      define(LDAP_OPT_DIAGNOSTIC_MESSAGE, 0x0032);
      $ldapLogin = ldap_bind($cr, $this->configuration->ldapAgentName,
                              $this->configuration->ldapAgentPassword);
      if (!$ldapLogin) {
         if (ldap_get_option($cr, LDAP_OPT_DIAGNOSTIC_MESSAGE, $extended_error)) {
            //echo $extended_error;
            if ( strpos($extended_error,"data 531")> 0) { //check error code from LdapServer
               $ldapLogin=true;
            } else {
               $ldapLogin=false;
            }
         } else {
            $ldapLogin=false;
         }
      }
      if(!$ldapLogin) {
         \OCP\Util::writeLog('user_ldap',
            'Bind failed: ' . $this->ldap->errno($cr) . ': ' . $this->ldap->error($cr),
            \OCP\Util::WARN);
         $this->ldapConnectionRes = null;
         return false;
      }
      return true;
   }
`

**Comment by blizzz** [comment]
> If the credentials are valid and meet the criteria, of course I expect OC let me access

AD must allow access, the bind must be successful. 

Even if "data 531" is returned, is it guaranteed that the provided credentials are valid?

Nevertheless, having the bind returning a negative result, it still feels wrong to overrule the ADs reply. Definitely at this part, this would rather go into areCredentialsValid() in lib/access.php.

My feeling that the more proper approach is to allow bind from ownCloud.

For reference: https://www-01.ibm.com/support/docview.wss?uid=swg21290631

**Comment by frungillo** [comment]
the error code 531 Indicates an Active Directory (AD) AcceptSecurityContext data error That is logon failure Caused Because the user is not permitted to log on from this computer.
En Returns Only When presented with a valid username and password valid credential.
the ultimate aim being to ensure access user with valid domain credentials, in the presence of the error 531 you can be reasonably sure that past credentials are secure.
Given the connection.bind () method does not consider valid the past credentials because the user with access restrictions on the machines is not authorized to log in on the domain controller, I think it is appropriate to consider such a change to allow for this possibility.

Currently hold only the user who has the property "Log On To" set to "all computers" successfully logs to OC.
The user with the access restrictions on the workstations to conclude a successful login must have domain servers between workstations that can access (logon to property).

My amendment is a bit dirty, but least effective.

**Comment by blizzz** [comment]
> the error code 531 Indicates an Active Directory (AD) AcceptSecurityContext data error That is logon failure Caused Because the user is not permitted to log on from this computer.

Is there a reason why you would not allow that user to log in from the machine running ownCloud?

> Basically I do not think it is sufficient to bind () to determine if the credentials are valid and edit areCredentialsValid () method does not seem to be enough to allow access.

areCredentialsValid() is a callee of the Connectiong::bind() method. The changes you are suggesting there could (and imho should) go to areCredentialsValid() without issues. Unless I have overseen something, then tell me ;)

The downside in having it in Connectiong::bind() is that it would also apply for the configured user agent. While I could understand to avoid hassling with normal user records, this one definitely should (and must) be able to act from within ownCloud.

**Comment by frungillo** [comment]
> Is there a reason why you would not allow that user to log in from the machine running ownCloud?


I understand that I am using a translator and that may not be clear that that I try to express.
The problem is that the active directory user should also have access to the machine that has the role of domain controllers or all computers! (Property 'Logon to')
The steps to reproduce the problem are simple:

1) Create a user in Active Directory by assigning as machines who can only access the server OwnCloud
2) Try to log in with the credentials you just created on the server owncloud

In this condition, the server denies access, citing 'error username or password'

The login is successful ONLY if we add the domain controller to the machine at which the user can access.

I do not believe in a company where there are these access restrictions, should be given to individual users access to the domain controller to use ownCloud.

I proposed the change because in the presence of the error 531, it is reasonably sure that the supplied credentials are valid.

**Comment by blizzz** [comment]
@frungillo OK, thank you for detailed remarks. Now, if you could implement your code within the areCredentialsValid() method instead and open a pull request against it, that would be great and we could merge it after a review. Also I wonder whether it makes sense to add a config switch so an admin can enable/disable this behaviour. And what the right default would be, I tend to have it disabled by default (also but not only because not everybody is running AD).

**Comment by frungillo** [comment]
@blizzz 
I'll do it in the evening.
thank you, and excuse my english

**Comment by blizzz** [comment]
> thank you, and excuse my english

don't excuse :) pretty sure most of us are non-native English speakers. You're doing fine and it's great to use different "technologies" :)

**Comment by PVince81** [comment]
Please reopen in [user_ldap app repo](https://github.com/owncloud/user_ldap) if issue persists with 10.0.4 and the latest user_ldap app from marketplace.
