### ISSUE TITLE
Downloading of large file not working when using Swift as primary storage

### ISSUE THREAD

**Issue by hyperbaba** [owncloud/core#22780]
### Steps to reproduce

1.Upload large file (>1.5GB) to owncloud
2.Try to download it
3.
### Expected behaviour

Tell us what should happen
File is downloaded to client computer
### Actual behaviour

Tell us what happens instead
Nothing happens. Not even a error in owncloud.log
### Server configuration

**Operating system**:
Ubuntu 14.04
**Web server:**
Apache
**Database:**
mysql
**PHP version:**
5.5
**ownCloud version:** (see ownCloud admin page)
8.2.2.2

**Updated from an older ownCloud or fresh install:**
Updated from an older
**Where did you install ownCloud from:**
From tar.gz downloaded from your download page
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**
default

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder

Enabled:
  - activity: 2.1.3
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - ocusagecharts: 3.4.5
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
Disabled:
  - encryption
  - external
  - files_external
  - files_trashbin
  - notifications
  - updater
  - user_external
  - user_ldap

```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
I am using swift as a primary storage
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
We are using webdav on our client side
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
### Client configuration

**Browser:**

**Operating system:**
#### Web server error log

```
Insert your webserver log here
```

no errors
#### ownCloud log (data/owncloud.log)

no errors or warnings on that matter

```
Insert your ownCloud log here
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by hyperbaba** [comment]
Forgot to mention. I see in /tmp that file is geting downloaded from objectstore but when it's downloaded it's deleted and new download from objectstore started with diferent php... name 
This loops until client request is canceled

**Comment by PVince81** [comment]
@icewind1991 can you have a look ?

CC @butonic

**Comment by PVince81** [comment]
Not sure if related, but there was this ticket about large file support: https://github.com/owncloud/core/pull/19004

**Comment by hyperbaba** [comment]
It's unrelated . Fails for files from 1GB+ . the #19004 is about swift restrictions for files 5GB+. We are using ceph radosgw instead of swift (but the with the swift v1  api.

**Comment by PVince81** [comment]
Could it be a PHP timeout issue then ? How long does it take to download ?

**Comment by hyperbaba** [comment]
it's under 2 minutes

**Comment by PVince81** [comment]
@butonic have you ever observed this kind of issue with swift primary storage ?

**Comment by PVince81** [comment]
What swift server are you using ?

**Comment by hyperbaba** [comment]
I am using ceph's version  0.94.5 radosgw
.

**Comment by hodyroff** [comment]
Swift will be deprecated in favor of full S3 support. Ceph supports S3.
