### ISSUE TITLE
Cannot Access caldav/carddav in Thunderbird

### ISSUE THREAD

**Issue by dom-madrid** [owncloud/core#22794]
### Steps to reproduce
1. In TB 38.6 with Lightning 4.0.6 (with or without Sogo plugin) - Owncloud 8.2.2 on Ubuntu 14.04
2. Connect to OC calendar or OC contacts
3. Nothing is shown - only error in TB

### Expected behaviour
Calendar/Contact info should appear and synchronize with OC

### Actual behaviour
Nothing happens. Error in TB as follow:
Timestamp: 02/03/2016 18:38:37
Warning: There has been an error reading data for calendar: OC Remote.  However, this error is believed to be minor, so the program will attempt to continue. Error code: DAV_NOT_DAV. Description: The resource at https://www.solipym.net/apps/cloud/remote.php/caldav/calendars/mipc/personal is either not a DAV collection or not available
Source File: file:///C:/Users/mipc/AppData/Roaming/Thunderbird/Profiles/0wg9ecr7.default/extensions/%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D/calendar-js/calCalendarManager.js
Line: 960

and 

Timestamp: 02/03/2016 18:38:37
Warning: There has been an error reading data for calendar: OC Remote.  However, this error is believed to be minor, so the program will attempt to continue. Error code: READ_FAILED. Description: 
Source File: file:///C:/Users/mipc/AppData/Roaming/Thunderbird/Profiles/0wg9ecr7.default/extensions/%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D/calendar-js/calCalendarManager.js
Line: 960

and 

Timestamp: 02/03/2016 18:57:06
Error: [calCachedCalendar] replay action failed: null, uri=https://www.solipym.net/apps/cloud/remote.php/caldav/calendars/mipc/personal, result=2147500037, op=[xpconnect wrapped calIOperation]
Source File: file:///C:/Users/mipc/AppData/Roaming/Thunderbird/Profiles/0wg9ecr7.default/extensions/%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D/calendar-js/calCachedCalendar.js
Line: 322

and Timestamp: 02/03/2016 18:57:06
Error: [calCachedCalendar] replay action failed: null, uri=https://www.solipym.net/apps/cloud/remote.php/caldav/calendars/mipc/defaultcalendar, result=2147500037, op=[xpconnect wrapped calIOperation]
Source File: file:///C:/Users/mipc/AppData/Roaming/Thunderbird/Profiles/0wg9ecr7.default/extensions/%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D/calendar-js/calCachedCalendar.js
Line: 322

### Server configuration
**Operating system**:
Linux Ubuntu 14.04.04 LTS
**Web server:**
Apache/2.4.7 (Ubuntu)
**Database:**
mysql  Ver 14.14 Distrib 5.5.47, for debian-linux-gnu (x86_64) using readline 6.3
**PHP version:**
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
**ownCloud version:** (see ownCloud admin page)
ownCloud 8.2.2 (stable) 
**Updated from an older ownCloud or fresh install:**
Updated from previous version
**Where did you install ownCloud from:**
Originally downloaded source from owncloud.org, then internal update
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

Enabled:
  - activity: 2.1.3
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - files: 1.2.0
  - files_external: 0.3.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - mail: 0.3.0
  - ownnote: 1.05
  - provisioning_api: 0.3.0
  - tasks: 0.8.1
  - updater: 0.6

Disabled:
  - encryption
  - external
  - files_locking
  - notifications
  - templateeditor
  - user_external
  - user_ldap

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

{
    "system": {
        "instanceid": "ocf6bffe7b17",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/srv\/data\/ocData",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "cloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "theme": "",
        "maintenance": false,
        "maxZipInputSize": 838860800,
        "allowZipDownload": true,
        "loglevel": 3,
        "trusted_domains": [
            "www.solipym.net",
            "www.solipym.com"
        ],
        "mail_smtpmode": "php",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": false,
        "trashbin_retention_obligation": "auto",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        }
    }
}


or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox 44.0.2
Thunderbird 38.6
**Operating system:**
Win7 x64
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log / Thunderbird log
```
Insert your browser log here, this could for example include:

See TB error log at the beginning
```

**Comment by RealRancor** [comment]
Hi,

that looks more like an setup issue of your environment. Have a look at this FAQ:

https://forum.owncloud.org/viewtopic.php?f=17&t=7536

Especially at the link to the litmus test where you can check your environment for a correct setup.

**Comment by DeepDiver1975** [comment]
in case the error persists - please reopen this issue in https://github.com/owncloudarchive/calendar
