### ISSUE TITLE
occ integrity check should return an exit code different than 0 in case of error

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#22806]
### Steps to reproduce
1. Run `sudo -u www-data ./occ integrity:check-core` and verify success (no console message and exit code = 0)
2. Create a new file with any content in the FS inside the ownCloud installation
3. Run again `sudo -u www-data ./occ integrity:check-core`
### Expected behaviour

Error message is shown (through stderr?) and the exit code is different than 0. There could be more exit codes depending on the type of error (new file added, modified file, missing file, etc).
### Actual behaviour

Error message is shown, but the exit code is 0.
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** 9.0.0RC1

**Updated from an older ownCloud or fresh install:** fresh install

This applies to "integrity:check-app", "integrity:check-core", "integrity:sign-app" and "integrity:sign-core"

@LukasReschke

**Comment by PVince81** [comment]
@ppaysant did you recent addition to occ return code cover this too ?

**Comment by ppaysant** [comment]
Nope
And sadly I think it's not possible with current code.

For instance ./occ integrity:check-core [calls $this->checker->verifyCoreSignature()](https://github.com/owncloud/core/blob/master/core/Command/Integrity/CheckCore.php#L60-L61) which [catch error](https://github.com/owncloud/core/blob/master/lib/private/IntegrityCheck/Checker.php#L551-L567) and returns an array, which is displayed on console.

So, from occ point of view, there's no error, just a message to display.

**Comment by ppaysant** [comment]
If the error were not catched in the command code, it would go up to the occ script which "echo" the exception message and exit with "1" code.

If different error codes are needed, we need to change that [error handling](https://github.com/owncloud/core/blob/master/console.php#L99-L103) and to return a specific error code to occ along with the exception...

**Comment by PVince81** [comment]
I thought `execute()` could just return an error code and it would be returned by Symfony's console system ?

@VicDeo can you take care of this ?

**Comment by VicDeo** [comment]
@PVince81 
> execute() could just return an error code and it would be returned by Symfony's console system ?

exactly
