### ISSUE TITLE
9.0 RC1 RPM package integrity check fail, git files missing

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#22803]
@LukasReschke please remove the git files from the integrity check.

I upgraded from 8.2.2 to 9.0 RC1 using our openSUSE RPM:
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- FILE_MISSING
		- 3rdparty/.gitignore
		- 3rdparty/bantu/ini-get-wrapper/.gitignore
		- 3rdparty/doctrine/cache/.gitignore
		- 3rdparty/doctrine/collections/.gitignore
		- 3rdparty/doctrine/common/.gitignore
		- 3rdparty/doctrine/common/.gitmodules
		- 3rdparty/doctrine/inflector/.gitignore
		- 3rdparty/icewind/streams/.gitignore
		- 3rdparty/ircmaxell/security-lib/.gitignore
		- 3rdparty/james-heinrich/getid3/.gitattributes
		- 3rdparty/james-heinrich/getid3/.gitignore
		- 3rdparty/paragonie/random_compat/.gitignore
		- 3rdparty/pear/archive_tar/.gitignore
		- 3rdparty/pear/console_getopt/.gitignore
		- 3rdparty/pear/pear-core-minimal/.gitignore
		- 3rdparty/pear/pear_exception/.gitignore
		- 3rdparty/rackspace/php-opencloud/.gitignore
		- 3rdparty/react/promise/.gitignore
		- 3rdparty/sabre/dav/.gitignore
		- 3rdparty/sabre/event/.gitignore
		- 3rdparty/sabre/http/.gitignore
		- 3rdparty/sabre/uri/.gitignore
		- 3rdparty/sabre/vobject/.gitignore
		- 3rdparty/sabre/xml/.gitignore
		- core/vendor/.gitignore
		- l10n/.gitignore
		- updater/.gitignore
		- updater/vendor/guzzlehttp/guzzle/.gitignore
		- updater/vendor/guzzlehttp/ringphp/.gitignore
		- updater/vendor/guzzlehttp/streams/.gitignore
		- updater/vendor/pimple/pimple/.gitignore
		- updater/vendor/psr/log/.gitignore
		- updater/vendor/symfony/console/.gitignore
	- EXTRA_FILE
		- assets/0bf5783e5ab79b2226fb16a459d55abe.js
		- assets/ee9844bfbb4579f4a5167a2dc79918a6.js
		- assets/b9afea3e1ec4ca039acdf91fb011fc07.js
		- assets/3d8ccef3ce87e327ef99206a6c66b8bd.js
		- assets/08e5b4cd046f151888da06c14d4999e1.css
		- assets/9cfcddb9f13dd41dab3c7f97d1ba0821.css
		- assets/ef9204f2e601db9fc48471762295b313.css
		- assets/04c1593fc6e89099f2c35dae8b5a992a.js
		- assets/38a6d94f98275b5d7cefed7ec6087e06.js
		- assets/e0c1e2a41ed8c3e14c873f2039195aec.css
		- assets/ba8e353a70c169f16469af3062040083.css
		- assets/e51a91ab2d73943b6809cb0685143488.css
		- assets/3c899948b4ba7501077a78add553da63.css
		- assets/74a091649d32f817005c8e72733d4015.css
		- assets/fa3eab50c830140c62e928a54792c3d7.js
		- assets/8047082b1468e1a84b68ae0ecd5f80b7.js
		- assets/d7c28fae75fdaa58689336b27f601022.css
		- assets/fcf1b85f2ce170e0fc126b5f7cb3497e.js
		- assets/d80f96981d7a5b26f97ebf7fc5cd111c.css
		- assets/05535b61337686cfdc24f07c351a09a8.js
		- assets/199e58dfc06f01380e20f8eb1d8b577d.js
		- assets/def0a2ebf8cd3c14128799fd2cb3f3ce.js
		- assets/fec1fd3a1703463ef22d54b7f59977d8.js
		- assets/3f5132d8802e640bad5a7683afaf37c4.js
		- assets/82f842936078e56c846c306286c69633.js
		- assets/2419b520222de27e5ffa3010a560fa16.js
		- assets/c613c4770f1c32cd01cb05320a477fe4.js
		- assets/ef6da96447b6d3e32c34bec88e0c2f87.js
- systemtags
	- FILE_MISSING
		- l10n/.gitkeep
- files_trashbin
	- FILE_MISSING
		- l10n/.gitkeep
- encryption
	- FILE_MISSING
		- l10n/.gitkeep
- firstrunwizard
	- FILE_MISSING
		- l10n/.gitignore
- federation
	- FILE_MISSING
		- l10n/.gitkeep
- activity
	- FILE_MISSING
		- l10n/.gitkeep
- files_versions
	- FILE_MISSING
		- l10n/.gitkeep
- files_texteditor
	- FILE_MISSING
		- js/vendor/ace/src-noconflict/mode-text.js
- comments
	- FILE_MISSING
		- l10n/.gitkeep
- updatenotification
	- FILE_MISSING
		- l10n/.gitkeep
- federatedfilesharing
	- FILE_MISSING
		- l10n/.gitkeep
- external
	- FILE_MISSING
		- l10n/.gitkeep
- files_external
	- FILE_MISSING
		- 3rdparty/.gitignore
		- 3rdparty/aws-sdk-php/Symfony/Component/ClassLoader/.gitignore
		- 3rdparty/icewind/smb/.gitignore
		- l10n/.gitkeep
- gallery
	- FILE_MISSING
		- .github/CONTRIBUTING.md
		- .github/issue_template.md
		- .github/pull_request_template.md
		- .gitmodules
		- build/documentation/reports/code coverage/index.html
		- vendor/symfony/yaml/.gitignore
- user_ldap
	- FILE_MISSING
		- l10n/.gitkeep
- files_sharing
	- FILE_MISSING
		- l10n/.gitkeep
```

CC @jnweiger not a packaging issue

**Comment by PVince81** [comment]
Also, you should make it skip the "assets" folder too!

**Comment by PVince81** [comment]
CC @cmonteroluque another thing that we'll need for 9.0

**Comment by LukasReschke** [comment]
The extra files thingy is a bug in the assets/ thing. The other stuff should not get touched by any OBS build script. Take the release tar and not delete data from it ;)

**Comment by jnweiger** [comment]
@LukasReschke RPM packages must not contain empty files. RPMLINT complains about these:

<pre>
owncloud/settings/js/old-apps.js
owncloud/apps/systemtags/l10n/.gitkeep
owncloud/apps/updatenotification/l10n/.gitkeep
owncloud/apps/files_versions/l10n/.gitkeep
owncloud/apps/federation/l10n/.gitkeep
owncloud/apps/federatedfilesharing/l10n/.gitkeep
owncloud/apps/files_sharing/l10n/.gitkeep
owncloud/apps/gallery/build/documentation/reports/code coverage/index.html
owncloud/apps/gallery/build/documentation/reports/index.html
owncloud/apps/gallery/l10n/no-php
owncloud/apps/activity/l10n/no-php
owncloud/apps/activity/l10n/.gitkeep
owncloud/apps/external/l10n/.gitkeep
owncloud/apps/comments/l10n/.gitkeep
owncloud/apps/encryption/l10n/.gitkeep
owncloud/apps/files_texteditor/js/vendor/ace/src-noconflict/mode-text.js
owncloud/apps/files_texteditor/l10n/.gitkeep
owncloud/apps/files_external/l10n/.gitkeep
owncloud/apps/firstrunwizard/l10n/.gitignore
owncloud/apps/files_trashbin/l10n/.gitkeep
owncloud/apps/user_ldap/l10n/.gitkeep
owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/README.markdown
</pre>

Currently I run ``find . -size 0 -print0 | xargs -r -0 rm`` to handle this.

**Comment by LukasReschke** [comment]
> @LukasReschke RPM packages must not contain empty files. RPMLINT complains about these:

@karlitschek @cmonteroluque Seems like we need to adjust the release script then? This is something that needs to get fixed packaging wise.

> Also, you should make it skip the "assets" folder too!

Patch is at https://github.com/owncloud/core/pull/22813

**Comment by jnweiger** [comment]
Non-critical on my side. Only affects RPM packages. DEB does not have similar rules.
The RPMLINT complains are already warnings only on most systems. 

I am now retaining all the dot files and empty files so that we have the RPMLINT messages in the build logs.

**Comment by LukasReschke** [comment]
If that is the case then #22813 should be sufficient, as long as the RPMs still install at least :wink:

**Comment by PVince81** [comment]
If someone installs a RPM from our source, they'd expect us to be trustworthy and having that message appear makes it look like something went wrong. This is why I set this to critical.

**Comment by jnweiger** [comment]
We'll find and handle uninstallable cases, if any do remain. :-)

**Comment by LukasReschke** [comment]
> If someone installs a RPM from our source, they'd expect us to be trustworthy and having that message appear makes it look like something went wrong. This is why I set this to critical.

As far I get https://github.com/owncloud/core/issues/22803#issuecomment-191759891 the empty files will not stay and thus there should also be no error message in ownCloud itself anymore. Right, @jnweiger?

**Comment by jnweiger** [comment]
No, it is not critical with regards to trustworthiness. The RPMLINT errors are visible only at packaging time. It may fail to install when selinux, apparmor or other hardening tools enforce similar policies though. That is why I asume we'll find uninstallable cases soonish.

**Comment by LukasReschke** [comment]
Stable9 at https://github.com/owncloud/core/pull/22822 and considering that the packaging behaviour is changed as well this should then be fixed :smile:

**Comment by cmonteroluque** [comment]
I fixed the archive build script to remove the files in 
https://github.com/owncloud/core/issues/22803#issuecomment-191749499

**Comment by jnweiger** [comment]
:+1:

**Comment by cmonteroluque** [comment]
let's keep it open until we ship 9.0.0 just to make sure

**Comment by PVince81** [comment]
I just tested the updated RC1 package on my server and the git files are gone from the warnings.

Now only assets/* appear which will be fixed in the RC2 release: https://github.com/owncloud/core/pull/22822

https://github.com/owncloud/core/pull/22822 still needs a second review!

**Comment by PVince81** [comment]
Ok, it was merged now.

Let's keep it open and verify in RC2

**Comment by PVince81** [comment]
I updated to RC2 on my own server and the warnings disappeared. Integrity check suceeds now.
