### ISSUE TITLE
Integration with Mattermost

### ISSUE THREAD

**Issue by menelic** [owncloud/core#22809]
I requested owncloud integration over at mattermost (free and open self hosted slack alternative - with more features than slack itself) - this became one of their most popular feature requests. https://mattermost.uservoice.com/forums/306457-general/suggestions/9950943-integration-with-owncloud#comments .Now they have responded - they want to do it and are asking for support from the oc community:

> Thanks to everyone who upvoted this, can we have the community’s help breaking this feature into smaller parts that can be written into tickets?
> 
> It seems there’s:
> 1. Ability to “Choose a file” from OwnCloud instead of hard drive. 
> 2. Add a preview of files referenced in conversations with hyperlinks to files hosted on OwnCloud
> 3. Something about webhooks, we’re not sure we understand
> 
> Can we have help from the OwnCloud community understanding what’s the first step?

@jancborchardt @coreyhulen @it33 maybe you could get together on this?

**Comment by LukasReschke** [comment]
cc @karlitschek External integrator requesting some support.

**Comment by karlitschek** [comment]
this is pretty cool. Also usermanagement integration would be great so that local and remote users are visible. 
@jancborchardt @LukasReschke Can you help here a bit how this could work?

This is pretty exiting :-)

**Comment by jancborchardt** [comment]
»Choose a file from ownCloud« relates to a JS/WebDAV endpoint from our side. cc @DeepDiver1975 
Similar for the previews for files referenced via hyperlink I guess? @LukasReschke?

cc @coreyhulen @jwilander @hmhealey from @Mattermost on this. What do you ideally need from us? :)

**Comment by it33** [comment]
Hi everyone, thanks for extending the discussion. Mattermost uses an [accepting pull requests process](http://docs.mattermost.com/process/accepting-pull-request.html) to define the design of new features before coding starts. As an example, we've opened one for [owncloud link previews in Mattermost](https://mattermost.uservoice.com/forums/306457-general/suggestions/9950943-integration-with-owncloud) for anyone who's like to contribute. 

Proposing two options for next steps: 

1. Find someone who uses both Mattermost and owncloud to contribute the APR? 
2. Discuss designs for 1) and 3) (perhaps on original thread?) to open an appropriate APR?

**Comment by karlitschek** [comment]
@it33 Yes. Would be great if you could find someone to work on this integration. This would be cool. I'm sure that some of the ownCloud core people will answer questions and help with that. but we need to fine a developer to drive this forward. You could ask on the owncloud developer mailing-list if you want.

**Comment by it33** [comment]
Thanks @karlitschek! Email sent to devel@owncloud.org, much appreciated!

**Comment by JakobReiter** [comment]
Ping. Any Updates on this? Would be highly interested in using this.

**Comment by DeepDiver1975** [comment]
> Ping. Any Updates on this? Would be highly interested in using this.

I'm not aware of anybody taking care of this

**Comment by furai** [comment]
Hey, I'm also interested in it, is it going to happen?

**Comment by PVince81** [comment]
out of scope for ownCloud core.

this needs to be a separate app.
feel free to ask in https://central.owncloud.org/c/apps in case someone is interested in developing this
