### ISSUE TITLE
9.0 RC1 RPM missing execute permission on "occ" file

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#22804]
I've upgraded from the 8.2.2 RPM to 9.0~RC1 RPM in openSUSE 13.2 x86_64.

After the upgrade, the `occ` command was missing execute permissions.

Not sure if RPM packaging issue or tarball issue ?

@jnweiger @cmonteroluque 

Setting this to 9.0, possibly a regression

**Comment by jnweiger** [comment]
fixed in owncloud-files-9.0.0~RC1-2.1.

**Comment by jnweiger** [comment]
verified. xbits seen in new packages. packages pushed to download mirrors.
