### ISSUE TITLE
Use filesystem instead of manual stream copying in files_versions

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#22817]
The workaround added with https://github.com/owncloud/core/commit/54cea05271b887f1c8062c034741df869bc0f055 uses manual streaming for object storages and thus the filesystem can get bypassed.

This requires us to maintain workarounds like https://github.com/owncloud/core/pull/22796/files#r54785664 to ensure that the cache is always consistent. 

We should make sure to always use the filesystem instead of manually stream copying in ownCloud.

Ref https://github.com/owncloud/core/pull/22796#issuecomment-191760881 

cc @icewind1991 @PVince81

**Comment by PVince81** [comment]
Thanks!
