### ISSUE TITLE
"Not enabled" link in Apps not visible in left menu

### ISSUE THREAD

**Issue by Geegs** [owncloud/core#22811]
### Steps to reproduce
1. Install 8.2.2.2 from tarball
2. Click on + Apps
3. 

### Expected behaviour
Both "Enabled" and "Not Enabled" links should appear in left menu area

### Actual behaviour
"Not Enabled" link not visible. Apache error log reports multiple instances of segfault (11)

### Server configuration
**Operating system**: Slackware Linux 13.37
**Web server:** Apache/2.4.16 (Unix) OpenSSL/1.0.1r PHP/5.6.17 mod_perl/2.0.9 Perl/v5.12.3 
**Database:** SQLite (default)
**PHP version:** 5.6.17
**ownCloud version:** 8.2.2.2
**Updated from an older ownCloud or fresh install:** Fresh 
**Where did you install ownCloud from:** Tarball
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
...
/index.php/settings/integrity/failed does not exist in 8.2.2.2
...
**List of activated apps:**
...
Enabled:
  - activity: 2.1.3
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - updater: 0.6
Disabled:
  - calendar
  - encryption
  - external
  - files_antivirus
  - files_external
  - mail
  - notifications
  - provisioning_api
  - templateeditor
  - user_external
  - user_ldap

**The content of config/config.php:**
```
<?php
$CONFIG = array (
  'instanceid' => 'ocy7960j2nhv',
  'passwordsalt' => 'xxxxxx',
  'secret' => 'xxxxxxx',
  'trusted_domains' =>
  array (
    0 => '192.168.1.43',
  ),
  'datadirectory' => '/home/apache/owncloud/data',
  'overwrite.cli.url' => 'https://192.168.1.43',
  'dbtype' => 'sqlite3',
  'version' => '8.2.2.2',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_from_address' => 'xxxxxx',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'xxxxxx.net.au',
  'appstoreenabled' => true,
  'appstore.experimental.enabled' => false,
 );

**Are you using external storage, if yes which one:** local/smb/sftp/... no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... no

### Client configuration
...
**Browser:**
Firefox 27.0.1
Chrome 31.0
Internet Explorer 11

**Operating system:**
...
Windows 7

#### Web server error log
```
[Mon Feb 29 20:24:57.744886 2016] [core:notice] [pid 17932] AH00052: child pid 21022 exit signal Segmentation fault (11)
[Mon Feb 29 20:24:57.744969 2016] [core:notice] [pid 17932] AH00052: child pid 21073 exit signal Segmentation fault (11)
[Mon Feb 29 20:24:57.744989 2016] [core:notice] [pid 17932] AH00052: child pid 21074 exit signal Segmentation fault (11)
[Mon Feb 29 20:24:58.747052 2016] [core:notice] [pid 17932] AH00052: child pid 21021 exit signal Segmentation fault (11)
[Mon Feb 29 20:24:58.747118 2016] [core:notice] [pid 17932] AH00052: child pid 21069 exit signal Segmentation fault (11)
[Mon Feb 29 20:24:59.748079 2016] [core:notice] [pid 17932] AH00052: child pid 21072 exit signal Segmentation fault (11)
[Mon Feb 29 20:24:59.748126 2016] [core:notice] [pid 17932] AH00052: child pid 21078 exit signal Segmentation fault (11)
[Mon Feb 29 20:24:59.748137 2016] [core:notice] [pid 17932] AH00052: child pid 21080 exit signal Segmentation fault (11)

#### ownCloud log (data/owncloud.log)
```
No errors generated

#### Browser log
```
No browser logs generated
```

**Comment by LukasReschke** [comment]
Segfault usually indicate a setup specific problem, for those please checkout owncloud.org/support

**Comment by Geegs** [comment]
That is correct; I eventually traced the issue to a bug in openssl-1.0.1r (in this particular combination/platform). Reverting to openssl-0.9.8zh corrected the issue. Security issues of the earlier version are another question altogether... Apologies for wasting your time!
