### ISSUE TITLE
oC 9.0 RC1: updatenotification enabled but no updater-section in admin-panel

### ISSUE THREAD

**Issue by vanMacG** [owncloud/core#22827]
### Steps to reproduce
1. fresh install of oC 9.0 RC1

### Expected behaviour
If I get things right, there still should be a "update" section in the admin panel if "updatenotification" (core-app) is enabled. At least there should be a link to the new updater.

### Actual behaviour
updatenotification is enabled, nothing in admin-panel. Unfortunately I don't get any error to trace the issue...

![updatenotification2](https://cloud.githubusercontent.com/assets/8269814/13502557/bdbaeaf4-e16b-11e5-8111-5fffe0dc904b.PNG)

### Server configuration
**Operating system**: Shared webhost: Linux dd27002 3.2.0-98-generic #138-Ubuntu SMP Mon Jan 11 12:33:01 UTC 2016 x86_64

**Web server:** Apache

**Database:** SQLite (had the same issue with MySQL)

**PHP version:** 5.5.31

**ownCloud version:** ownCloud 9.0.0 RC1 (testing)

**Updated from an older ownCloud or fresh install:** fresh install (same issue when updating)

**Where did you install ownCloud from:** RC1.zip

**Signing status (ownCloud 9.0 and above):** No errors have been found.

**List of activated apps:**

![updatenotification](https://cloud.githubusercontent.com/assets/8269814/13502261/7fe65610-e16a-11e5-97e4-420c1974f6a2.PNG)

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => 'oc2btbks0edn',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' => 
  array (
    0 => 'xxx.eu',
  ),
  'datadirectory' => '/www/htdocs/w0069a6f/testing/oc9rc1/owncloud/data',
  'overwrite.cli.url' => 'http://xxx.eu/testing/oc9rc1/owncloud',
  'dbtype' => 'sqlite3',
  'version' => '9.0.0.16',
  'logtimezone' => 'UTC',
  'installed' => true,
  'loglevel' => 0,
);

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 44.0.2

**Operating system:** Windows 7

#### Web server error log
Don't know how t oaccess cause I'm on a shared hosting.

#### ownCloud log (data/owncloud.log)
Debug 	core 	No update found at the ownCloud appstore for app 166051 	2016-03-03T17:04:24+00:00
Debug 	core 	No update found at the ownCloud appstore for app 166055 	2016-03-03T17:04:23+00:00
Debug 	core 	No update found at the ownCloud appstore for app 166049 	2016-03-03T17:04:23+00:00

**Comment by LukasReschke** [comment]
The link is only displayed when an update is available as requested in https://github.com/owncloud/core/pull/22354

@karlitschek @jancborchardt What should we do here:

1. Keep the behaviour
2. Always show the link to the updater

Your decision :smile:

**Comment by vanMacG** [comment]
So how do i select/change the release-channel then? Also, in 8.x there was a green dot with information when the check was performed. So how can I know if there's no new version or did the check simply failed?

**Comment by vanMacG** [comment]
As I am really confused a bit with the new namings regarding the updater ("updatenotification", "new updater", ...) I try to explain my pov a bit more.
I agree that the real "update notification", the yellow info-text on the top page, should only be visible if there is a update available. But a link to the new "update center" (new updater) in admin-panel would be nice to be always visible for manual check, list of backups, release-channel, etc.

**Comment by jancborchardt** [comment]
I’m a bit confused here. Shouldn’t Updater have the update notification inside? Why the need for a separate app?

**Comment by karlitschek** [comment]
Definitely show the link only if an update is available. 
@VicDeo How does switching the release channels work now?

**Comment by LukasReschke** [comment]
@jancborchardt Updater is not an ownCloud app. The updater can display nothing inside ownCloud. It barely can read the config file.

**Comment by VicDeo** [comment]
@karlitschek 
oh, missed that part. We have a regression with switching channels. 
It's possible in CLI with `occ config:app:set core OC_Channel --value` only.

This task can be a part of updatenotification app.

**Comment by LukasReschke** [comment]
I'll add that to the updatenotification app.

**Comment by PVince81** [comment]
To clarify: the GUI will look like it did before. One difference will be that the button will link to the new updater web page instead of running the update.

**Comment by LukasReschke** [comment]
Patch is at https://github.com/owncloud/core/pull/22857

**Comment by karlitschek** [comment]
Argh.
@LukasReschke Thanks a lot for the quick fix!!!

**Comment by vanMacG** [comment]
@LukasReschke Thanks for fixing! Next time I will report an issue right away in beta-stage so you have some more time ;)

**Comment by karlitschek** [comment]
@vanMacG Thanks a lot for reporting!
