### ISSUE TITLE
[LDAP] share link with "users in group" search/autosuggest faulty in: webinterface

### ISSUE THREAD

**Issue by f-s** [owncloud/core#22821]
Hi, 

using 8.2.2 and LDAP for login, with "Restrict users to only share with users in their groups" **enabled**, I get _no_ search results (autosuggestion) for "Share with users, groups, etc." in the webinterface, when I try and search for a user, I share a LDAP group with.

What actually works in this server install:
- Using the owncloud **client** (api) with Ubuntu and Windows to find users in the same group to share with
- the User Manager works (and all groups and functions) etc.
- "Restrict users to only share with users in their groups" => **disabled**, the user, group search interface for link shares works as expected across groups.

Things used to work in the past, of course no errors logged :-D

Thank you,

fse

**Comment by PVince81** [comment]
Can you post this in the other ticket, even if it's slightly different ? Thanks.
