### ISSUE TITLE
Emoticon in calendar event causes parse error

### ISSUE THREAD

**Issue by csware** [owncloud/core#22820]
I don't know if this is the right place and this affects the calendar. However, https://github.com/owncloud/calendar removed all old issues and is now only for the new calendar of 9.x - also there is stated, that I should report it here.

### Steps to reproduce
1. Create a new calendar, and mount it on an iPhone
2. use an iPhone and create a new entry which has an emoticon (in e.g., the location)
3. See parse errors in owncloud.log

### Expected behaviour
Synchronisation should work w/o problems. Calendar is not usable any more.

### Actual behaviour
I get an error, which is similar to https://webcache.googleusercontent.com/search?q=cache:qIa7qMCRlykJ:https://github.com/owncloud/calendar/issues/997%2Bowncloud+calendar+997&hl=de&&ct=clnk:

`Exception: {"Message":"End of document reached prematurely","Exception":"Sabre\\VObject\\EofException","Code":0,"Trace":"#0 \/var\/www\/SERVERNAME\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php(168): Sabre\\VObject\\Parser\\MimeDir->readLine()\n#1 \/var\/www\/SERVERNAME\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php(137): Sabre\\VObject\\Parser\\MimeDir->parseLine('BEGIN:VEVENT')\n#2 \/var\/www\/SERVERNAME\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php(63): Sabre\\VObject\\Parser\\MimeDir->parseDocument()\n#3 \/var\/www\/SERVERNAME\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Reader.php(44): Sabre\\VObject\\Parser\\MimeDir->parse('BEGIN:VCALENDAR...', 0)\n#4 \/var\/www\/SERVERNAME\/owncloud\/apps\/calendar\/lib\/sabre\/backend.php(384): Sabre\\VObject\\Reader::read('BEGIN:VCALENDAR...')\n#5 \/var\/www\/SERVERNAME\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Calendar.php(163): OCA\\Calendar\\Sabre\\Backend->getCalendarObject('50', '81A9DEB2-084B-4...')\n#6 \/var\/www\/SERVERNAME\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Tree.php(105): Sabre\\CalDAV\\Calendar->childExists('81A9DEB2-084B-4...')\n#7 \/var\/www\/SERVERNAME\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAVACL\/Plugin.php(758): Sabre\\DAV\\Tree->nodeExists('calendars\/steff...')\n#8 [internal function]: Sabre\\DAVACL\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#9 \/var\/www\/SERVERNAME\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#10 \/var\/www\/SERVERNAME\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#11 \/var\/www\/SERVERNAME\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#12 \/var\/www\/SERVERNAME\/owncloud\/apps\/calendar\/appinfo\/remote.php(60): Sabre\\DAV\\Server->exec()\n#13 \/var\/www\/SERVERNAME\/owncloud\/remote.php(137): require_once('\/var\/www\/srv1.7...')\n#14 {main}","File":"\/var\/www\/SERVERNAME\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php","Line":250}`

When I issue `SELECT * FROM oc_clndr_objects WHERE calendardata NOT LIKE '%END:VCALENDAR%' ` I see that the entry is truncated after `Location:`.

Example entry: [Privat.ics.txt](https://github.com/owncloud/core/files/156965/Privat.ics.txt)

### Server configuration
**Operating system**:

Debian 8.3

**Web server:**

Apache 2.4

**Database:**

MySQL 5.5.47

**PHP version:**

5.6.17-0+deb8u1

**ownCloud version:** (see ownCloud admin page)

8.2.2 (stable) 

**Updated from an older ownCloud or fresh install:**

Updated from older version.

**List of activated apps:**

```
Enabled:
  - activity: 2.1.3
  - calendar: 0.8.2
  - contacts: 0.5.0.0
  - files: 1.2.0
  - files_locking:
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - templateeditor: 0.1
  - updater: 0.6
Disabled:
  - encryption
  - external
  - files_external
  - notifications
  - provisioning_api
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "51547ad6130fd",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/srv\/owncloud-data",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "loglevel": "2",
        "apps_paths": [
            {
                "path": "\/var\/www\/SERVERNAME\/owncloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "maintenance": false,
        "theme": "",
        "overwrite.cli.url": "https:\/\/XXXX",
        "trusted_domains": [
            "XXXX",
            "cloud.XXXX"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        }
    }
}
```

**Are you using encryption:** no

**Apache log**

```
XXXXX - - [03/Mar/2016:15:28:21 +0100] "PUT /remote.php/caldav/calendars/USERNAME/privat/81A9DEB2-084B-48C1-876D-D213A6ED50CF.ics HTTP/1.1" 201 779 "-" "iOS/9.2.1 (13D15) dataaccessd/1.0"
XXXXX - - [03/Mar/2016:15:28:48 +0100] "DELETE /remote.php/caldav/calendars/USERNAME/privat/81A9DEB2-084B-48C1-876D-D213A6ED50CF.ics HTTP/1.1" 500 1121 "-" "iOS/9.2.1 (13D15) dataaccessd/1.0"
```

**Comment by DeepDiver1975** [comment]
the old calendar issues live in https://github.com/owncloudarchive/calendar

**Comment by csware** [comment]
@DeepDiver1975 Why is it stated in https://github.com/owncloud/calendar issue template otherwise? - Also the README is broken and linking to itself.

**Comment by RealRancor** [comment]
@csware Not everything is fully updated to reflect the difference between the old and the new calendar app.

This move was done one or two days ago so just give the people a little bit time to sort everything out ;-)
