### ISSUE TITLE
usage of undocumented OCS SHARE API calls

### ISSUE THREAD

**Issue by moscicki** [owncloud/core#22839]
@DeepDiver1975: Owncloud v.8 web-browser client is using undocumented parameters in the OCS SHARE API calls and undocumented requests:

1. shares?format=json&shared_with_me=false

https://demo.owncloud.org/ocs/v1.php/apps/files_sharing/api/v1/shares?format=json&shared_with_me=true

2. remote_shares?format=json

https://demo.owncloud.org/ocs/v1.php/apps/files_sharing/api/v1/remote_shares?format=json

You can see these ajax calls triggered by navigating in your demo instance: https://demo.owncloud.org/index.php/apps/files/?dir=%2F&view=sharingin

As we already pointed out in https://github.com/owncloud/pyocclient/issues/154#issuecomment-191603623: this API is poorly documented and incomplete.

https://doc.owncloud.org/server/8.0/developer_manual/core/ocs-share-api.html

Are these undocumented calls in v8 an issue in v9 (which AFAIK should be using webdav instead?)
Should the doc be updated or will this usage disappear in the next version?

**Comment by rullzer** [comment]
Those functions are still there.

Yes we should update the docs. We are looking into how to do this properly in a maintainable way.

In version 9 you will see even more calls to the OCS Share API endpoints. :wink:

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/documentation/issues/2212
