### ISSUE TITLE
Why wasn't the commenting system designed as a sub-system of a generic meta data managing system?

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#22837]
I'm asking because there are lots of similar, more business oriented, uses for file related meta data and it looks like duplicating the comments app and the comments manager would currently be the best option to manage properties such as as notes, signatures, read status, etc., but that seems to be a waste of effort and could lead to problems down the road if all the different implementation were slightly different.

@karlitschek @MTRichards @DeepDiver1975 @PVince81 @MorrisJobke @schiesbn @icewind1991 @rullzer @nickvergessen

**Comment by nickvergessen** [comment]
Well the biggest issue with things like that is, that it's really hard to write something in a general way,
when you don't even know the cases you want to use it for.
However the comments table has a `verb` column, which is one step into that direction. I think it is hardcoded now to comment, but could allow to change it in the future and then we are pretty close to that?

Or did I misunderstand your point?

**Comment by oparoz** [comment]
You understand the point. 
In my mind, I should be able to define a model, submit it to the metaDataManager and have full CRUD capabilities. I would then need to build the UI which integrates with the detailsview in Files, but wouldn't have to create a DAV plugin, a manager, etc.
On top of that, something like comments is completely integrated into `core`, adding public interfaces, methods to the AppFramework, forcing people who want to implement something similar to either fork `core` or to lobby for the integration of their meta data into `core`

In lights of recent announcements that ownCloud now wants to manage more than files, maybe the model should be revisited.
File model, new MetaData model, User model all loosely connected to give a maximum of flexibility to architects.
Tags seem to be going in the right direction because they're not restricted to files, but comments seem to be.

**Comment by nickvergessen** [comment]
Well we aimed for the same with comments, and there is a PR to fix it:
https://github.com/owncloud/core/pull/22620

**Comment by oparoz** [comment]
That a step in the right direction, but it's still awkward to use a commentsManager to store other entities, no?

**Comment by DeepDiver1975** [comment]
To be honest: we had a general purpose sharing backend for years - this way a nightmare.

In addition: commenting on a calendar entry is something different compared to commenting on a file.
