### ISSUE TITLE
Download button with several files selected doesn't trigger the download.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#22838]
### Steps to reproduce

1. Upload a bunch of files.
2. Select some files using the checkboxes, three for example.
3. Click on the download button.

### Expected behaviour
Files are downloaded joining them in a tar or zip file.

### Actual behaviour
Download doesn't start.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"9.0.0.16","versionstring":"9.0.0 RC1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
Yes in serverA.

**Browser Logs**

```
Request URL:http://HIDDEN_HOST/index.php/core/preview.png?file=%2Fdownload.svg&c=36bc7465811a31a7ce0c2cf44e99e82b&x=24&y=24&forceIcon=0
Request Method:GET
Status Code:404 Not Found
Remote Address:HIDDEN_IP
```

### Client configuration

**browser**
Chrome, Edge, Firefox.

**Operating System**
OS X El Capitán, Windows 10.

**Comment by PVince81** [comment]
I have 9.0 RC1 with encryption on my personal server and I'm able to reproduce this... shit.

**Comment by PVince81** [comment]
CC @cmonteroluque another critical issue, I'll have a look ASAP

**Comment by PVince81** [comment]
Bisect result: b634f1e2c70809a4fde7f738cb7c252b6fc3f4dc from https://github.com/owncloud/core/pull/22461

**Comment by PVince81** [comment]
PR is here: https://github.com/owncloud/core/pull/22846
