### ISSUE TITLE
The download archive should be named after the name of the current folder

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#22836]
### Steps to reproduce

1. Create a folder named `Brazil_2016` which contains a sub-folder named `Beaches`
1. Share the folder via link
1. Open the link
1. Download the folder by using the download button in the header
1. Go into the sub-folder
1. Click on "Download" again

### Expected behaviour

The first download should be named `Brazil_2016` 
The 2nd download should be named `Beaches`

### Actual behaviour

The first download is named `download`
The 2nd download is named `download(1)`

It's a poor user experience.
The download endpoint used to support naming the archive using the arguments sent along the GET request, but that doesn't work any more.

----
@jancborchardt @rullzer @PVince81 @MorrisJobke

**Comment by jancborchardt** [comment]
Yeah, this should definitely be fixed. As far as I remember this worked some time in the past already?

**Comment by oparoz** [comment]
That was also my impression, at least in some cases where it was possible to download content.
I've checked with 8.2.2 and it's the same problem on the Files side. On the Gallery side, you get a name only if you're on a sub-folder. IIRC with earlier version of Gallery+ you would get the folder name all the time, but something did change in `core` which broke the behaviour.

**Comment by PVince81** [comment]
Indeed, that looks fishy

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/22902

**Comment by oparoz** [comment]
Thanks for the quick fix!

**Comment by oparoz** [comment]
Re-opening as the fix is incomplete.

1. Share a folder containing a folder names "superéàéàélongfolder name because i can"
1. On the public side, descend into that folder
1. Press the download button

The zip will be named: "super%C3%A9%C3%A0%C3%A9%C3%A0%C3%A9longfolder%20name%20because%20i%20can.zip"

That's unreadable for a "normal" user.

**Comment by PVince81** [comment]
It's an issue with the zip/tar libraries: https://github.com/owncloud/core/issues/19862, fixed in OC 9.0

Are you still seeing this in that version ?

**Comment by oparoz** [comment]
Yep, I've performed the test above on stable9.

**Comment by oparoz** [comment]
Response header in Firefox:

```
Content-Disposition:"attachment; filename*=UTF-8''super%25C3%25A9%25C3%25A0%25C3%25A9%25C3%25A0%25C3%25A9longfolder%2520name%2520because%2520i%2520can.zip; filename="super%25C3%25A9%25C3%25A0%25C3%25A9%25C3%25A0%25C3%25A9longfolder%2520name%2520because%2520i%2520can.zip""
```

**Comment by oparoz** [comment]
Maybe https://github.com/owncloud/core/pull/22489 broke it...

**Comment by PVince81** [comment]
@LukasReschke 
![explain](https://cloud.githubusercontent.com/assets/277525/13578488/89c0f1b4-e498-11e5-880c-0bb03168a90b.jpg)

**Comment by LukasReschke** [comment]
No idea. Works here on Linux and Mac. Don't have Windows :see_no_evil: 

![2016-03-07_19-15-12](https://cloud.githubusercontent.com/assets/878997/13578552/edb50e26-e498-11e5-8df6-8d57c039aee7.png)

**Comment by LukasReschke** [comment]
Aha. The ZIP it is. Let me test that as well :)

**Comment by PVince81** [comment]
Doesn't work on Linux with Chromium 48 either:
![scheisse](https://cloud.githubusercontent.com/assets/277525/13578581/1ca6c7b0-e499-11e5-9aaa-38ba034ecd2f.png)
 
Looks like it's time for bisecting.

**Comment by LukasReschke** [comment]
I guess it's https://github.com/owncloud/core/issues/19862#issuecomment-153789872 :wink: 

> Also then we need to remove https://github.com/owncloud/core/blob/05359e384e7b33b6928ab239f4d7f518d250c236/lib/private/streamer.php#L54-L57 after merging this.

**Comment by rullzer** [comment]
All those weird non-ascii languages! :wink:

**Comment by LukasReschke** [comment]
> Looks like it's time for bisecting.

Won't help. That never worked for you then if it really is https://github.com/owncloud/core/issues/22836#issuecomment-193378032. Mind testing for you?

**Comment by PVince81** [comment]
@LukasReschke yeah, discarding those lines makes it work for me in Chromium and Firefox.

Can you make a PR ?

**Comment by LukasReschke** [comment]
> Can you make a PR ?

Sure :)

**Comment by LukasReschke** [comment]
https://github.com/owncloud/core/pull/22918

**Comment by LukasReschke** [comment]
Stable9 at https://github.com/owncloud/core/pull/22919

**Comment by oparoz** [comment]
Good job and that also takes care of the Gallery side without any additional changes :)
