### ISSUE TITLE
space in the directory name

### ISSUE THREAD

**Issue by ddeenniiss** [owncloud/core#22845]
Hi,

Windows seems to refuse the spaces at the end of a directory, considering them invalid.

If a directory is created on Mac or Linux, they will not be synchronized on Windows machines.

**Comment by aspdye** [comment]
Please keep in mind our Contributing and Issue Submitting Guidelines according to: 
https://github.com/owncloud/core/blob/master/CONTRIBTING.md ;)

**Comment by LukasReschke** [comment]
Dupe of https://github.com/owncloud/core/issues/22534
