### ISSUE TITLE
App loading spinner & new tab

### ISSUE THREAD

**Issue by luckydonald** [owncloud/core#22840]
### Steps to reproduce
1. Navigate to Documents
2. <kbd>cmd</kbd>+ <kbd>click</kbd> on Files, to open files in a new tab.
3. Open that menu again

### Actual behaviour
The spinner stays there forever.
![image](https://cloud.githubusercontent.com/assets/2737108/13521919/7c969948-e1ec-11e5-99ae-844b173d1839.png)

### Expected behaviour
It should not show a "load" animation when opening in a new tab,
or remove that after a while.

### Server configuration
Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u2 x86_64 GNU/Linux

**Web server:**
Apache

**Database:**
MySQL

**ownCloud version:**
`ownCloud 8.2.2 (production)`

**Updated from an older ownCloud or fresh install:**
Yes.

**Where did you install ownCloud from:**
updater.php

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.1.3
  - bookmarks: 0.6
  - calendarplus: 1.1.1
  - documents: 0.11.1
  - external: 1.2
  - files: 1.2.0
  - files_external: 0.3.0
  - files_locking:
  - files_markdown: 0.1
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - imprint: 0.2.5
  - search_lucene: 0.6.0
  - storagecharts2: 2.5.4.268
  - user_external: 0.4
  - user_ldap: 0.7.1
Disabled:
  - calendar
  - contacts
  - encryption
  - files_encryption
  - music
  - news
  - notifications
  - ocusagecharts
  - provisioning_api
  - templateeditor
  - updater
  - user_webdavauth
```

**The content of config/config.php:**

Will post if needed

**Are you using external storage, if yes which one:** local/smb/sftp/...
- local
- SMB / CIFS
- SMB / CIFS with login

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** 
- ActiveDirectory (LDAP)

#### LDAP configuration (delete this part if not used)

```
sudo -u www-data php occ ldap:show-config
```

### Client configuration
**Browser:**
Chromium Mac OS 10.9.5

**Comment by LukasReschke** [comment]
cc @owncloud/designers

**Comment by jancborchardt** [comment]
This is a JS issue, not design. As far as I know we had this issue in the past as well, and fixed it to not show a spinner when Ctrl-Clicking.

cc @owncloud/javascript

**Comment by PVince81** [comment]
Slightly related https://github.com/owncloud/core/issues/20766

**Comment by nickvergessen** [comment]
In 9.1 the loading spinner is removed and the drop down is also closed when opening in a new tab.
