### ISSUE TITLE
Comments are not kept when you log out the account

### ISSUE THREAD

**Issue by davitol** [owncloud/core#22849]
### Steps to reproduce

1. In the sidebar, write a comment about the file. (The comment is shown)
2. Logout from oC
3. Login again

### Expected behaviour

The comment should be shown and kept

### Actual behaviour

The comment is not available

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 9.0.0 RC1 (testing)

### Logs

```
{"reqId":"AxGf1oU9S58cWNB+\/PNR","remoteAddr":"82.159.139.58","app":"PHP","message":"ucwords() expects exactly 1 parameter, 2 given at \/opt\/owncloud\/lib\/private\/comments\/comment.php#365","level":3,"time":"2016-03-04T10:26:29+00:00"}
```

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox for Mac OSX

![screen shot 2016-03-04 at 11 33 59](https://cloud.githubusercontent.com/assets/10596560/13524695/1c00f810-e1fd-11e5-9b87-5b422b2fbc50.png)

![screen shot 2016-03-04 at 11 34 07](https://cloud.githubusercontent.com/assets/10596560/13524704/222a1c94-e1fd-11e5-9fac-976a8471dacb.png)

**Comment by PVince81** [comment]
@blizzz @nickvergessen

**Comment by PVince81** [comment]
I'll have a look at the JS side

**Comment by PVince81** [comment]
Are you kidding me ??! REPORT gives:
```
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:card="urn:ietf:params:xml:ns:carddav" xmlns:oc="http://owncloud.org/ns">
 <d:response>
  <d:status>HTTP/1.1 200 OK</d:status>
  <d:href>/owncloud/remote.php/dav/comments/files/3/</d:href>
  <d:propstat>
   <d:prop/>
   <d:status>HTTP/1.1 418 I'm a teapot</d:status>
  </d:propstat>
 </d:response>
</d:multistatus>
```

**Comment by PVince81** [comment]
@nickvergessen @blizzz any idea what this means ?

```
ucwords() expects exactly 1 parameter, 2 given at \/srv\/www\/htdocs\/owncloud\/lib\/private\/comments\/comment.php#365
```

**Comment by PVince81** [comment]
Observed on PHP php5-5.5.14-41.1.x86_64

@davitol what's your PHP version ?

**Comment by PVince81** [comment]
Okay, looking at the documentation: http://php.net/manual/en/function.ucwords.php

The second parameter was added in PHP 5.5.16...

**Comment by davitol** [comment]
PHP 5.5.9-1
