### ISSUE TITLE
it is need to close the yellow warning of 'file bigger than the upload limit' instead of disappear

### ISSUE THREAD

**Issue by davitol** [owncloud/core#22856]
### Steps to reproduce

1. Try to upload a file bigger than the upload limit

### Expected behaviour

The yellow warning disappears a few seconds later

### Actual behaviour

It is need to click on the cross to close it (see screenshot below)

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 9.0.0 RC1 (testing)

### Logs

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox for Mac OSX

![screen shot 2016-03-04 at 13 45 13](https://cloud.githubusercontent.com/assets/10596560/13527538/eb7f569c-e20f-11e5-9011-6da8c6da206b.png)

**Comment by davitol** [comment]
I think now it is the behaviour for all 'yellow warnings' ?

![screen shot 2016-03-04 at 13 55 52](https://cloud.githubusercontent.com/assets/10596560/13527655/f0c86ec6-e210-11e5-9747-4938bacee6ee.png)

**Comment by PVince81** [comment]
Not all of them, only upload errors so far.

One needs to explicit ad  `{type: 'error'}` in the call of `showTemporary` to make the cross appear.

**Comment by PVince81** [comment]
Regarding uploading with not enough space, I think it's acceptable to require people to close it.
This makes sure people can actually read notifications.

Imagine you start to upload then go away, then when you come back you thought everything was uploaded but didn't, because the notification already disappeared.

Closing as expected.
