### ISSUE TITLE
Using Safari as browser, it is not possible to browse into the search results

### ISSUE THREAD

**Issue by davitol** [owncloud/core#22854]
### Steps to reproduce

1. In the search box write down a pattern that fits with a folder

### Expected behaviour

The folder search should be shown in the results and it should be able to browse into it

### Actual behaviour

Using Safari as browser, there's no way to browse into the folder 

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 9.0.0 RC1 (testing)

### Logs

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Safari

Firefox behaviour

![screen shot 2016-03-04 at 12 34 17](https://cloud.githubusercontent.com/assets/10596560/13526068/cb44102a-e205-11e5-9884-18e7e2fc03a5.png)

Safari behaviour

![screen shot 2016-03-04 at 12 33 55](https://cloud.githubusercontent.com/assets/10596560/13526076/d7be6cb0-e205-11e5-83a4-164dbd9be0b4.png)

**Comment by PVince81** [comment]
Hopefully a recent Safari version ?

**Comment by davitol** [comment]
Safari Version 8.0.8 (10600.8.9) (Yosemite) --> The 'bug' is reproduced
Safari Version 9.0 (11601.1.56) (El Capitan) --> The behaviour is like the other borsers

**Comment by PVince81** [comment]
Ugh, Safari < 9 already had some other bugs...

**Comment by PVince81** [comment]
Is this still an issue with 9.1.0 ?

**Comment by PVince81** [comment]
@davitol can you verify with 9.1.2 RC1 ?

**Comment by davitol** [comment]
> can you verify with 9.1.2 RC1 ?

@PVince81 Solved, so let's close it
