### ISSUE TITLE
federation app not automatically enabled

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#22869]
Is it intended that the federation app is not enabled by default or an oversight?

https://github.com/owncloud/core/blob/master/apps/federation/appinfo/info.xml

cc @schiesbn @karlitschek

**Comment by karlitschek** [comment]
Argh. Should be enabled automatically. 
Can we still fix that?
@cmonteroluque

**Comment by LukasReschke** [comment]
I'll create a PR :wink:

**Comment by LukasReschke** [comment]
Master: https://github.com/owncloud/core/pull/22870
Stable9: https://github.com/owncloud/core/pull/22871

**Comment by nickvergessen** [comment]
I actually thought this was intended because it otherwise passes on your user list on remote share?

**Comment by karlitschek** [comment]
this behavior can be disabled on admin page. but should be on be default
