### ISSUE TITLE
Make hash algorithm choice configurable

### ISSUE THREAD

**Issue by wetsixteen** [owncloud/core#22873]
Hi,
I have not found a way to change the default hash algorithm for user passwords.
It would be great for me to have a config option to select the algorithm used for hashing a users password.

Background: Using the OC user database as a backend e.g. for dovecot, but unfortunately blowfish is not supported out of the box in current debian.

**Comment by LukasReschke** [comment]
This is possible by writing a custom user manager. See https://github.com/owncloud/apps/tree/master/user_external or https://github.com/owncloud/core/tree/master/apps/user_ldap for some examples.
