### ISSUE TITLE
Problems with showing Files and the "+"-Button

### ISSUE THREAD

**Issue by aspdye** [owncloud/core#22881]
### Expected behavior
Should show me the example-files (example.odt) and the "+"-Button for adding files.

### Actual behaviour
Displays only the sidebar and an empty folder-overview. (All Icons are in a low quality and pixelated.)
<img width="1234" alt="ohne titel" src="https://cloud.githubusercontent.com/assets/12893462/13547256/a4a25852-e2cb-11e5-8c1c-ffdfa1447e8e.png">

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS
**Web server:**
Apache + Nginx Reserve Proxy
**Database:**
SQLite
**PHP version:**
Tested with FPM and FastCGI 5.5, 5.6, 7.0
**ownCloud version:** (see ownCloud admin page)
9.0.0 RC1
**Updated from an older ownCloud or fresh install:**
fresh 
**Where did you install ownCloud from:**
owncloud.org test build
**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```
**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => 'mydomain.de',
  ),
  'datadirectory' => '/var/www/vhosts/mydomain.de/httpdocs/owncloud/data',
  'overwrite.cli.url' => 'http://mydomain.de/owncloud',
  'dbtype' => 'sqlite3',
  'version' => '9.0.0.16',
  'logtimezone' => 'UTC',
  'installed' => true,
);
```

### Client configuration
**Browser:**
Tested with Safari and Firefox
**Operating system:**
OS X El Capitan

#### ownCloud log
```
Error	PHP	is_readable(): open_basedir restriction in effect. File(/dev/urandom) is not within the allowed path(s): (/var/www/vhosts/mydomain.de/:/tmp/) at /var/www/vhosts/mydomain.de/httpdocs/owncloud/3rdparty/paragonie/random_compat/lib/random.php#66	2016-03-05T11:11:55+00:00```

**Comment by RealRancor** [comment]
I think there is really something fishy at your setup as you also had the issue reported here: https://github.com/owncloud/core/issues/22540

**Comment by LukasReschke** [comment]
@aspdye Any chance you can give me a test login? See my profile for my mail address.

**Comment by aspdye** [comment]
@LukasReschke You have a mail :wink:

**Comment by LukasReschke** [comment]
@aspdye You too :wink:

**Comment by aspdye** [comment]
:scream: You are fast - too fast :sweat_smile: 
Thank you very much ;)

**Comment by LukasReschke** [comment]
I suppose we can https://github.com/owncloud/core/issues/22540 close then as well once you got it working properly? :smile:

**Comment by RealRancor** [comment]
@aspdye It might be useful to post what the bug in the nginx config was. :-)

**Comment by aspdye** [comment]
I quote @LukasReschke for now:

> /owncloud/core/js/oc.js = destroyed
> /owncloud/index.php/core/js/oc.js = works
> 
> ownCloud is not going to support Short URLs with nginx and will only maintain Apache-Rules. 

I am going to close #22540 for the same reason now :rocket: Everything works fine now :muscle:

**Comment by RealRancor** [comment]
@aspdye Thanks for the info. Maybe its worth to try the suggested nginx config here: https://github.com/owncloud/core/pull/14081#issuecomment-73935967 which seems to already work for nginx.

**Comment by aspdye** [comment]
@LukasReschke told me that this should be documented. But honestly - I have no plan how to do this in a appropriate way :confused:

**Comment by RealRancor** [comment]
No worries :-) Have pointed to nginx guys from #14081 to https://github.com/owncloud/documentation/issues/2014

**Comment by aspdye** [comment]
:+1:
