### ISSUE TITLE
Upload to local storage with no space left gives 500 instead of 507

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#22899]
### Steps

1. Mount the data directory using a limited size tmpfs, for example: `sudo mount -t tmpfs -o size=1024M tmpfs data`
1. Setup OC
1. Leave all quotas on "Unlimited"
1. Upload many files using **webdav** until the disk becomes full

### Expected result
Uploading further files must result in 507 Insufficient Storage

### Actual result
Internal Server Error in streamCopy is thrown.

The reason is that since https://github.com/owncloud/core/pull/21610 we had to call `free_space` on file names due to shared files and quota checks.
The trouble is that `disk_free_space` returns `false` when called on files.

### Versions
9.0 RC2

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/22912

**Comment by rullzer** [comment]
#22912 is merged. Closing.

**Comment by PVince81** [comment]
This was the wrong approach... see https://github.com/owncloud/core/issues/23546
