### ISSUE TITLE
Add strict mode to integrity checker

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#22890]
We should add a strict mode to integrity checker which has no exclusions. This can then be used by the updater app to ensure that the release is really an official one from us. So even if somebody hacks the download and update server the update won't get installed.

We already check the integrity. But there are some exclusions that an adversary could still abuse here for the core exclusions. The app integrity checker is fine.

Probably a matter of adding a new if-else switch :smile: 

cc @VicDeo

**Comment by aspdye** [comment]
Good call. Will this be optional??

**Comment by PVince81** [comment]
backlog for now

@Peter-Prochaska @VicDeo let me know if you think otherwise
