### ISSUE TITLE
Sort apps with available updates up top in the app list

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#22892]
As commented in https://github.com/owncloud/core/pull/22422

This is exactly how the Play Store and iOS App Store do it as well.

cc @nickvergessen

**Comment by nickvergessen** [comment]
Steps:
1. We need an endpoint that gives back update info about a list of given ocs ids on the app store
2. We need to make the request and then sort the app data based on that before putting that in the UI, to prevent resorting when an app has an update available.

// Unassigning and putting to backlog until the endpoint is there.

**Comment by jancborchardt** [comment]
How do we get this endpoint? @LukasReschke @karlitschek?

**Comment by MorrisJobke** [comment]
Request came also in via apps repo: https://github.com/owncloud/apps/issues/2155

**Comment by DeepDiver1975** [comment]
oc willcome with a new ui and marketplace -> close
