### ISSUE TITLE
Make sure all bundled apps have their version in "appinfo/info.xml"

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#22905]
Starting with 9.1, the "appinfo/version" will not be supported any more.
The version number must be moved to "appinfo/info.xml" in all the bundled apps.

Among them:

- [x] files_antivirus
- [x] files_pdfviewer
- [x] templateeditor
- [x] user_external
- [x] firstrunwizard

**Comment by karlitschek** [comment]
Have we discussed that we want to do this API break already?

**Comment by PVince81** [comment]
I'm fine with keeping it longer. So far we haven't merged https://github.com/owncloud/core/pull/22828
This was already advertised as deprecated on the mailing lists some time ago.

If we want to keep it longer, OC 11 could be a good fit because that's what we also had in the max version field. So if people anyway need to touch their info.xml, those two changes could go together.

@DeepDiver1975 @MorrisJobke

**Comment by MorrisJobke** [comment]
> If we want to keep it longer, OC 11 could be a good fit because that's what we also had in the max version field. So if people anyway need to touch their info.xml, those two changes could go together.

I'm fine with this grace period. Nevertheless we should move the version to the info.xml sooner ;)

**Comment by tahaalibra** [comment]
created pull request..
https://github.com/owncloud/files_antivirus/pull/92
https://github.com/owncloud/files_pdfviewer/pull/104
 will do for the rest of them today

**Comment by tahaalibra** [comment]
updated templateeditor and firstrunwizard

**Comment by MorrisJobke** [comment]
All PRs are merged -> closing
