### ISSUE TITLE
support CLASS property when sharing objects via CALDAV 

### ISSUE THREAD

**Issue by georgehrke** [owncloud/core#22914]
https://tools.ietf.org/html/rfc5545#page-83

`Public` show up just normal
`Private` are supposed to be busy only
`Confidential` should not be shared at all

**Comment by melo1** [comment]
This feature is absolutely necessary when you offer caldav sync and shared  calendars.
Without the software is useless because of the privacy and security gaps.

**Comment by stefangweichinger** [comment]
Does that mean that we can't hide confidential events with 9.0.1 calendars right now?
I am searching for a solution as dicussed in https://forum.owncloud.org/viewtopic.php?f=38&t=36732
The customer does not like that right now .... and downgrading seems quite a hassle as well.
pls comment, thanks.

**Comment by DeepDiver1975** [comment]
> Does that mean that we can't hide confidential events with 9.0.1 calendars right now?

yes

**Comment by stefangweichinger** [comment]
that is bad. recommended workaround is roll back to 8.x ?? 
I can't let that installation run this way, the employees are complaining ....

**Comment by DeepDiver1975** [comment]
> that is bad. recommended workaround is roll back to 8.x ??

not much more you can do - sorry.

This will hopefully come with 9.1 in August

**Comment by stefangweichinger** [comment]
Isn't that a very basic feature needed and wanted by most oc-users?
I am puzzled by the fact that this is in the stable release ... (and worked in 8.2.2 here).

**Comment by DeepDiver1975** [comment]
> Isn't that a very basic feature needed

maybe

> wanted by most oc-users?

you are the second since the release of 9.0 who is asking for it



> I am puzzled by the fact that this is in the stable release ... (and worked in 8.2.2 here).

The whole caldav and carddav backend was rewritten ... things take it's time

**Comment by stefangweichinger** [comment]
ok, understood. Thanks for your work.

**Comment by kosli** [comment]
was this fixed in 9.1.0 ? as in 9.0.4 it still doesn't work (just upgraded to 9.0.4)

**Comment by DeepDiver1975** [comment]
> was this fixed in 9.1.0

yes - as the milestone says

**Comment by kosli** [comment]
sorry, missed the milestone. so will need to upgrade to 9.1 then to get that feature back :-) thanks.

**Comment by DeepDiver1975** [comment]
> so will need to upgrade to 9.1 then to get that feature back

yes

**Comment by DeepDiver1975** [comment]
have fun
