### ISSUE TITLE
Tooltip of a fed.sharing remote user that not exists doesn't disappear

### ISSUE THREAD

**Issue by davitol** [owncloud/core#22910]
### Steps to reproduce

1. In the sidebar, try to share a file with a remote fake user 

### Expected behaviour

The tooltip with the fake remote user disappears

### Actual behaviour

The tooltip with the wrong user does not disappear.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud 9.0.0 RC3 (testing)

### Logs

```
```

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** yes; no.
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox for Mac OSX

![screen shot 2016-03-07 at 13 55 28](https://cloud.githubusercontent.com/assets/10596560/13570115/9b006c2e-e46c-11e5-958d-7281a62df5f9.png)

**Comment by PVince81** [comment]
Works for me on master / 9.1.0beta2. The tooltip properly disappears now.
