### ISSUE TITLE
Backport federation translations to 9.0.1

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#22916]
We added some translations late in the game:
https://github.com/owncloud/core/pull/22775

The commit `1b3e7ae82be1c906464a9652bca28d96d10e4baa` and the respective translations string should be backported before 9.0.1 so translations are available.

**Comment by nickvergessen** [comment]
First couple of strings was backported with https://github.com/owncloud/core/pull/23478

**Comment by PVince81** [comment]
Is there more ?

**Comment by nickvergessen** [comment]
Well I will do another backport go next week, so translations from this week are also available

**Comment by nickvergessen** [comment]
Not a lot added this time, so closing
