### ISSUE TITLE
array_key warnings when exclude group from sharing and PROPFIND

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#22931]
### Steps

1. Setup ownCloud
1. Create a user "user1"
1. Add "user1" to a group "group1"
1. Go to the admin page
1. Enable "Exclude groups from sharing" and select "group1"
1. Log out
1. curl -X PROPFIND -H "Depth: 1" http://user1:test@localhost/owncloud/remote.php/files/

### Expected result
No warnings

### Actual result
Warnings in log:
```
{"reqId":"+vDWgq4DdSflWmUJkYBT","remoteAddr":"127.0.0.1","app":"PHP","message":"array_keys() expects parameter 1 to be array, boolean given at \/srv\/www\/htdocs\/owncloud\/lib\/private\/group\/manager.php#283","level":3,"time":"2016-03-07T23:01:05+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/files\/"}
{"reqId":"+vDWgq4DdSflWmUJkYBT","remoteAddr":"127.0.0.1","app":"PHP","message":"array_map(): Argument #2 should be an array at \/srv\/www\/htdocs\/owncloud\/lib\/private\/group\/manager.php#283","level":3,"time":"2016-03-07T23:01:05+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/files\/"}
```

This happens because `files_sharing/appinfo/app.php` is calling `isSharingDisabledForUser()` but when using Webdav, the authentication hasn't happened yet during app loading. So any calls to such APIs will have a `null` user. But that piece of code is only for displaying navigation entries, and aren't relevant for Webdav access.

@nickvergessen @rullzer

**Comment by PVince81** [comment]
Observed on stable9 9232a124e22e65dbdb36e6b103bf6791e04cb140

**Comment by rullzer** [comment]
We really need to resturcture the files sharing app. Because this does not even have to be loaded on webdav access...

**Comment by PVince81** [comment]
@rullzer we do need the files_sharing app for the federated shared storage, until that one is moved over to the federation app. The bogus part is that we shouldn't directly register stuff in app.php.

**Comment by rullzer** [comment]
That is exactly what I ment ;)

**Comment by PVince81** [comment]
Fixed by https://github.com/owncloud/core/issues/22908
