### ISSUE TITLE
Calendar group shares are not properly migrated

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#22932]
### Steps to reproduce
1. Install ownCloud 8.2
2. Create a group named "Calendar Access"
3. Add some users to that group
4. Create a calendar and share with "Calendar Access"
5. Try to access with some users of the groups => Works
6. Update to ownCloud 9.0
7. Open the calendar app

### Expected behaviour
The calendar should still be properly shared. Users should be able to access it.

### Actual behaviour
It shows the calendar is shared but users don't see it. When deleting the share and recreating it then users finally see the share.

<hr/>

cc @DeepDiver1975

**Comment by MorrisJobke** [comment]
For my instance the shares are still available but the permissions are set to read only

**Comment by DeepDiver1975** [comment]
> It shows the calendar is shared but users don't see it. When deleting the share and recreating it then users finally see the share.

@LukasReschke Can you please post the entries of that calendar in table oc_dav_shares after migration and after recreate? I suspect some wrong entries in the db after migration

**Comment by LukasReschke** [comment]
After migration:
```
id          principaluri                      type        access      resourceid
----------  --------------------------------  ----------  ----------  ----------
1           principals/users/Calendar Access  calendar    3           2
```

After recreate:
```
sqlite> select * from oc_dav_shares;
id          principaluri                       type        access      resourceid
----------  ---------------------------------  ----------  ----------  ----------
2           principals/groups/Calendar Access  calendar    3           2
```

So that should be probably a `groups` and not a `users`. Also I experience the permission stuff from https://github.com/owncloud/core/issues/22932#issuecomment-193657403

**Comment by DeepDiver1975** [comment]
What is the share_type in oc share for this calendar?

**Comment by LukasReschke** [comment]
Seems to be 1

```
sqlite> select * from oc_share;
id          share_type  share_with       uid_owner   parent      item_type   item_source  item_target   file_source  file_target   permissions  stime       accepted    expiration  token       mail_send   uid_initiator
----------  ----------  ---------------  ----------  ----------  ----------  -----------  ------------  -----------  ------------  -----------  ----------  ----------  ----------  ----------  ----------  -------------
1           1           Calendar Access  admin                   calendar    3            admin's test               admin's test  31           1457430579  0                                   0
```

**Comment by DeepDiver1975** [comment]
php - you bloody son of a :dog2: https://github.com/owncloud/core/blob/master/apps/dav/lib/migration/migratecalendars.php#L119

**Comment by DeepDiver1975** [comment]
> For my instance the shares are still available but the permissions are set to read only

will take care of this as well
