### ISSUE TITLE
Share link: user mail is disappearing after selecting expiration date

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/core#22947]
### Steps to reproduce
1. Enable: Allow users to share via link > Allow users to send mail notification for shared files
2. Share link
3. Input: Email link to person
4. Select expiration date with date selector

### Expected behaviour
- Email address shouldn't disappear after setting an expiration data

### Actual behaviour
- Email address disappears after setting an expiration data

![2016-03-08 13_20_04](https://cloud.githubusercontent.com/assets/214010/13601499/dc8d438c-e530-11e5-899a-de5921945c36.gif)

### Server configuration
**ownCloud version:** (see ownCloud admin page)
8.2.2, 8.2.3RC2

**Updated from an older ownCloud or fresh install:**
fresh install

### Client configuration
**Browser:**
Chrome 49

**Operating system:**
Mac OS X 10.11.3

@MorrisJobke Who can help here?

00004983

**Comment by PVince81** [comment]
@rullzer

**Comment by PVince81** [comment]
Maybe we should move that field to the bottom ? Looks like this user would want to first set all settings before actually sending out the email, which makes sense.

**Comment by MorrisJobke** [comment]
> Maybe we should move that field to the bottom ? Looks like this user would want to first set all settings before actually sending out the email, which makes sense.

@owncloud/designers

**Comment by prastut** [comment]
I think the set-expiration date should come in the block where all of the settings are present ie password protect, allow editing. @PVince81 makes sense. 

I could make a PR for it, let me know. @jancborchardt

**Comment by PVince81** [comment]
The reason why the field clears is because every time a setting is changed, the whole view is re-rendered. Ideally this should be changed to only update the part that was actually modified, not the whole view.

**Comment by jancborchardt** [comment]
Yeah, I honestly don’t know why that email field is inbetween those settings. It should be the last one for sure.

Also, it shouldn’t be cleared. Even if the whole view is re-rendered, the value could be remembered and put in again. Or yes, just rerender the part which was modified.

(And repeating myself, ideally it’s combined with the box at the top: https://github.com/owncloud/core/issues/22327#issuecomment-190789253 )

**Comment by PVince81** [comment]
The value isn't part of the share itself, that's why it's not remembered.
But you're right, it could be stored temporarily in a local variable and re-set after rerendering.

**Comment by butonic** [comment]
I agree with @jancborchardt the password should be the last input field. That should solve the usability problem.

@PVince81  Can we get the different orderang for 8.2.4?

**Comment by MorrisJobke** [comment]
> @PVince81 Can we get the different ordering for 8.2.4?

He is on vacation. Maybe @rullzer or @ChristophWurst could help out here :)

**Comment by ChristophWurst** [comment]
@jancborchardt @butonic what should be on the last position? the email field or the password field?

**Comment by jancborchardt** [comment]
Email should be last, as @PVince81 and me said above. Not sure if @butonic confused that. ;)

**Comment by MorrisJobke** [comment]
How critical is this? The fix went into master. It also moves a lot of code and I would vote against a backport to stable8.2. @michaelstingl Is this okay?

**Comment by MorrisJobke** [comment]
> How critical is this? The fix went into master. It also moves a lot of code and I would vote against a backport to stable8.2. @michaelstingl Is this okay?

cc @karlitschek

**Comment by MorrisJobke** [comment]
> How critical is this? The fix went into master. It also moves a lot of code and I would vote against a backport to stable8.2. @michaelstingl Is this okay?

It seems the backport is already decided: https://github.com/owncloud/core/pull/23980#issuecomment-212352956 ...then nevermind my comment.

**Comment by karlitschek** [comment]
yes. probably not critical but definitely annoying.
