### ISSUE TITLE
Cannot enable any app in oC 9.1 daily version

### ISSUE THREAD

**Issue by davitol** [owncloud/core#22956]
### Steps to reproduce

1. Go to apps menu
2. Try to enable an app

### Expected behaviour

It should be possible to enable any app

### Actual behaviour

It is not possible to enable any app

Note: In /opt/owncloud/apps/XXXX/appinfo/info.xml these are the values set

owncloud min-version="9.0" max-version="9.0" 

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 9.1.0 pre alpha (daily) Build:2016-03-08T04:04:10+00:00 9f0711004f0574d5373574f8a1dc49552c3568e3

### Logs

```
```

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** yes; no.
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox for Mac OSX

![screen shot 2016-03-08 at 17 13 55](https://cloud.githubusercontent.com/assets/10596560/13607599/32343a32-e551-11e5-9850-e224c7c94fc5.png)

**Comment by LukasReschke** [comment]
This is a bug within the applications. Not in core. The apps need to be updated to declare compatibility with 9.1

**Comment by LukasReschke** [comment]
- external: https://github.com/owncloud/apps/pull/2150
- user_external: https://github.com/owncloud/apps/pull/2151
