### ISSUE TITLE
Google Drive external storage broke my owncloud

### ISSUE THREAD

**Issue by stanelie** [owncloud/core#22958]
### Expected behaviour

Attach a google drive external storage and be able to use it
### Actual behaviour

It doesn't work well with big files because it is unable to stream (see issue https://github.com/owncloud/core/issues/5949). So I tried to remove the google drive external storage. Now, I get 
"Error while loading the list of folders from the server" from the Mac or PC client and I am unable to sync anything. Also, I now get "Your web server is not yet set up properly to allow file synchronization because the WebDAV interface seems to be broken." in the admin panel.
### Steps to reproduce
1. Attach external Google Drive storage containing big files
2. weep
3. 

### Server configuration
Operating system:
Ubuntu 14.04
Web server: 
Apache
Database:
MySQL
PHP version:
5.5.9-1ubuntu4.14
ownCloud version:
8.2.2
Storage backend:
Local and smb shares through "external storage" app
### Client configuration
Client version:
2.x
Operating system:
windows 7
OS language:
English
Installation path of client:
default
### Logs

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
empty

2. Web server error log:
nothing relevant

3. ownCloud log (data/owncloud.log):
`Exception: {"Exception":"Exception","Message":"Creating \\OC\\Files\\Storage\\Google storage failed","Code":0,"Trace":"#0 \/var\/www\/owncloud\/apps\/files_external\/lib\/config.php(258): OC\\Files\\Storage\\Google->__construct(Array)\n#1 \/var\/www\/owncloud\/apps\/files_external\/controller\/storagescontroller.php(237): OC_Mount_Config::getBackendStatus('\\OC\\Files\\Stora...', Array, false)\n#2 \/var\/www\/owncloud\/apps\/files_external\/controller\/storagescontroller.php(257): OCA\\Files_External\\Controller\\StoragesController->updateStorageStatus(Object(OCA\\Files_external\\Lib\\StorageConfig))\n#3 [internal function]: OCA\\Files_External\\Controller\\StoragesController->show(13)\n#4 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#5 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Files_External\\Controller\\GlobalStoragesController), 'show')\n#6 \/var\/www\/owncloud\/lib\/private\/appframework\/app.php(108): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Files_External\\Controller\\GlobalStoragesController), 'show')\n#7 \/var\/www\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('GlobalStoragesC...', 'show', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#8 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#9 \/var\/www\/owncloud\/lib\/private\/route\/router.php(291): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#10 \/var\/www\/owncloud\/lib\/base.php(851): OC\\Route\\Router->match('\/apps\/files_ext...')\n#11 \/var\/www\/owncloud\/index.php(39): OC::handleRequest()\n#12 {main}","File":"\/var\/www\/owncloud\/apps\/files_external\/lib\/google.php","Line":80} `

and also this from `tail owncloud.log`
`{"reqId":"5AkHaFiFahAbGZKcSnsy","remoteAddr":"192.168.0.2","app":"files_external","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Creating \\\\OC\\\\Files\\\\Storage\\\\Google storage failed\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(258): OC\\\\Files\\\\Storage\\\\Google->__construct(Array)\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/controller\\\/storagescontroller.php(237): OC_Mount_Config::getBackendStatus('\\\\OC\\\\Files\\\\Stora...', Array, false)\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/controller\\\/storagescontroller.php(257): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus(Object(OCA\\\\Files_external\\\\Lib\\\\StorageConfig))\\n#3 [internal function]: OCA\\\\Files_External\\\\Controller\\\\StoragesController->show(13)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'show')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'show')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('GlobalStoragesC...', 'show', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#8 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(291): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(851): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#11 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/google.php\",\"Line\":80}","level":3,"time":"2016-03-08T15:23:53+00:00"}`

Note :  the 192.168.0.2 local address is my reverse proxy.

**Comment by stanelie** [comment]
Any thoughts on how I can clean up this mess so that I can use ownCloud again without reinstalling from scratch?

**Comment by LukasReschke** [comment]
@stanelie You could try to disable files_external. Is deleting the mountpoint not possible?

**Comment by stanelie** [comment]
I could, but I'd rather not.
I was reckless and I messed with the googledrive external storage on a production server. The users are using the external storage app and I'm afraid disabling and re-enabling it will trigger a re-download on their sync clients.
Also, I am the only user affected, so, I'd rather take the long way and fix the underlying issue. Also, we might learn something from this.

**Comment by stanelie** [comment]
Well,

I upgraded to ownCloud 9 and I was able to see the phantom google drive external storage mount under the admin account and remove it. I can now sync with the client and list available folders.

Maybe there should be a warning when one tries to set up a google drive external storage mount point that it might break everything.

**Comment by PVince81** [comment]
GDrive is now able to stream download since OC 9.0.1 and error handling of unavailable storages have been improved.

Feel free to reopen if you're still getting breakages.
