### ISSUE TITLE
Clicking on a tag should also show dropdown

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#22952]
### Steps to reproduce
1. Create a file
2. Assign tags "1", "2" and "3" to it
3. Try to unassign tag "1" by clicking on it
### Expected behaviour

The dropdown should appear.
### Actual behaviour

Dropdown only appears when clicking in an empty place. This is kinda unintuitive from my PoV.

![2016-03-08_14-59-13](https://cloud.githubusercontent.com/assets/878997/13603574/7e7db142-e53e-11e5-8370-5dcb1a08f1a2.png)

cc @owncloud/designers

**Comment by PVince81** [comment]
select2 hackery fun

**Comment by jancborchardt** [comment]
Keep in mind that usually the tags have an X button to delete that tag as well, so the overlap there might be a bit strange.
