### ISSUE TITLE
Max Upload Size Not Changing

### ISSUE THREAD

**Issue by KeithIMyers** [owncloud/core#22964]
I just went through the process of upgrading to OwnCloud 9 and noticed that the Max File Upload Settings reverted back to 513 MB. I attempted to modify the value via the usual method and it failed. I cannot for the life of me figure out how to make it work in 9.0

### Here is what I tested
1) I tried to manually edit the .htaccess provided by OwnCloud in config/.htaccess
2) I tried to manually edit the .user.ini file in the base of the OwnCloud install (Note : This threw off the Signature Check, It ultimately did not work and I reverted back to a backup of the file)
3) I made the .user.ini file writable by the "www-data" user so I can modify the value in the OwnCloud admin section. Upon editin

### Expected behaviour
1) The "Max Upload" value in the OwnCloud Admin should reflect the new value
2) I should be able to upload files greater than 513 MB

### Actual behaviour
1) The "Max Upload" value in the OwnCloud Admin section reflects 513 MB
2) I am unable to upload files larger then 513 MB

### Server configuration
**Operating System : Ubuntu 14.04.4 LTS**:
**Web Server : Apache 2.4.7**
**Database : MySQL 14.14**
**PHP Version : 5.5.9**
**ownCloud Version : 9.0.0.19** 
**Updated from 8.2.2-1:**
**Ubuntu Repo hosted at download.owncloud**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.

```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```
Enabled:
  - activity: 2.2.1
  - calendar: 1.0
  - comments: 0.2
  - contacts: 1.0.0.0
  - dav: 0.1.5
  - documents: 0.12.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - mail: 0.3.0
  - music: 0.3.9
  - news: 7.1.2
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - tasks: 0.8.1
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)


{
    "system": {
        "instanceid": "ocb6xcbo6kjk",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "office.kmyers.me"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/office.kmyers.me",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "php",
        "mail_from_address": "Alerts",
        "mail_domain": "office.kmyers.me",
        "appstore.experimental.enabled": true,
        "updatechecker": false,
        "maintenance": false,
        "loglevel": 0,
        "theme": ""
    }
}

```

**Are you using external storage, if yes which one:** local/smb/sftp/...** NO

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...** NO

### Client configuration
**Browser : Google Chrome**

**Operating system:: Multiple**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by KeithIMyers** [comment]
Closing - user error on my part

**Comment by Reemster** [comment]
What was the error? because i have the same problem...
