### ISSUE TITLE
 owncloud-8.2.3.tar.bz2 contains /apps/dav folder

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#22962]
Seems there is something broken with the build script. The https://download.owncloud.org/community/owncloud-8.2.3.tar.bz2 from https://owncloud.org/changelog/ contains a:

apps/dav/tests/unit/connector/sabre/requesttest/

folder with a file called "partfileinrootupload.php"

**Comment by LukasReschke** [comment]
Will be fixed with https://github.com/owncloud/core/pull/22935
