### ISSUE TITLE
'oc_activity' already exists

### ISSUE THREAD

**Issue by cattin** [owncloud/core#22963]
### Steps to reproduce
1. Upgraded files to 9.0.0 from the latest stable version
2. Fired up webbrowser and pressed the "Start update" Button
3. Then I got the error message below

### Expected behaviour

I expected that the update run through without any problems.

### Actual behaviour
Instead I got this error message on the browser 

Doctrine\DBAL\Exception\TableExistsException: An exception occurred while executing 'CREATE TABLE `oc_activity` (`activity_id` INT AUTO_INCREMENT NOT NULL, `timestamp` INT DEFAULT 0 NOT NULL, `priority` INT DEFAULT 0 NOT NULL, `type` VARCHAR(255) DEFAULT NULL, `user` VARCHAR(64) DEFAULT NULL, `affecteduser` VARCHAR(64) NOT NULL, `app` VARCHAR(255) NOT NULL, `subject` VARCHAR(255) NOT NULL, `subjectparams` VARCHAR(4000) NOT NULL, `message` VARCHAR(255) DEFAULT NULL, `messageparams` VARCHAR(4000) DEFAULT NULL, `file` VARCHAR(4000) DEFAULT NULL, `link` VARCHAR(4000) DEFAULT NULL, `object_type` VARCHAR(255) DEFAULT NULL, `object_id` INT DEFAULT 0 NOT NULL, INDEX activity_time (`timestamp`), INDEX activity_user_time (`affecteduser`, `timestamp`), INDEX activity_filter_by (`affecteduser`, `user`, `timestamp`), INDEX activity_filter_app (`affecteduser`, `app`, `timestamp`), PRIMARY KEY(`activity_id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_activity' already exists

### Server configuration
**Operating system**: Linux 14.04

**Web server:** Apache 2.4.7-1ubuntu4.9

**Database:** mysql 5.5.47

**PHP version:** 5.5.9

**ownCloud version:** 8.2.2.2 -> 9.0.0

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

Can not do it as I can no longer log in.

Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

Can no longer log in.

**List of activated apps:**

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder

ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Enabled:
  - dav: true
  - federatedfilesharing: 0.1.0
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - templateeditor: 0.1
Disabled:
  - activity
  - calendar
  - comments
  - contacts
  - documents
  - encryption
  - external
  - federation
  - provisioning_api
  - systemtags
  - updatenotification
  - user_external
  - user_ldap

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)

$CONFIG = array (
  'passwordsalt' => '***',
  'datadirectory' => '/UFS/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.2.2.2',
  'installed' => true,
  'instanceid' => '507f12a87e5b7',
  'maintenance' => false,
  'loglevel' => 0,
  'theme' => '',
  'maxZipInputSize' => 838860800,
  'allowZipDownload' => true,
  'trusted_domains' => 
  array (
    0 => 'somedomain.net',
    1 => '192.168.1.2',
    2 => '192.168.1.22',
    3 => '192.168.1.22',
  ),
  'secret' => '',
  'dbname' => 'oc_db',
  'dbhost' => '127.0.0.1',
  'dbuser' => 'oc_db_user',
  'dbpassword' => '***',
  'forcessl' => true,
  'trashbin_retention_obligation' => 'auto',
);


**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

no

### Client configuration
**Browser:** google-chome  49.0.2623.75 (64-bit)

**Operating system:** linux 14.04

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)

This is that part added to the log when I press "Start update" again.
```
{"reqId":"Z8sC1SAtJPwTlE85hLgt","remoteAddr":"178.83.71.100","app":"core","message":"starting upgrade from 8.2.2.2 to 9.0.0.19","level":0,"time":"2016-03-08T18:06:16+00:00","method":"GET","url":"\/oc\/core\/ajax\/update.php?requesttoken=FiIIMxNXKiYaAQYjHDItAGAReRgUASwYNgoUHW9nJhE%3D%3APVxYi2BTUElHoxcTSuAPs7btOIml94JA6z%2BJScF47Zw%3D"}
{"reqId":"Z8sC1SAtJPwTlE85hLgt","remoteAddr":"178.83.71.100","app":"core","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\TableExistsException\",\"Message\":\"An exception occurred while executing 'CREATE TABLE `oc_activity` (`activity_id` INT AUTO_INCREMENT NOT NULL, `timestamp` INT DEFAULT 0 NOT NULL, `priority` INT DEFAULT 0 NOT NULL, `type` VARCHAR(255) DEFAULT NULL, `user` VARCHAR(64) DEFAULT NULL, `affecteduser` VARCHAR(64) NOT NULL, `app` VARCHAR(255) NOT NULL, `subject` VARCHAR(255) NOT NULL, `subjectparams` VARCHAR(4000) NOT NULL, `message` VARCHAR(255) DEFAULT NULL, `messageparams` VARCHAR(4000) DEFAULT NULL, `file` VARCHAR(4000) DEFAULT NULL, `link` VARCHAR(4000) DEFAULT NULL, `object_type` VARCHAR(255) DEFAULT NULL, `object_id` INT DEFAULT 0 NOT NULL, INDEX activity_time (`timestamp`), INDEX activity_user_time (`affecteduser`, `timestamp`), INDEX activity_filter_by (`affecteduser`, `user`, `timestamp`), INDEX activity_filter_app (`affecteduser`, `app`, `timestamp`), PRIMARY KEY(`activity_id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB':\\n\\nSQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_activity' already exists\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/oc\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/oc\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(945): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'CREATE TABLE `o...')\\n#2 \\\/var\\\/www\\\/oc\\\/lib\\\/private\\\/db\\\/mdb2schemamanager.php(167): Doctrine\\\\DBAL\\\\Connection->query('CREATE TABLE `o...')\\n#3 \\\/var\\\/www\\\/oc\\\/lib\\\/private\\\/db\\\/mdb2schemamanager.php(70): OC\\\\DB\\\\MDB2SchemaManager->executeSchemaChange(Object(Doctrine\\\\DBAL\\\\Schema\\\\Schema))\\n#4 \\\/var\\\/www\\\/oc\\\/lib\\\/private\\\/db.php(172): OC\\\\DB\\\\MDB2SchemaManager->createDbFromStructure('\\\/var\\\/www\\\/oc\\\/app...')\\n#5 \\\/var\\\/www\\\/oc\\\/lib\\\/private\\\/installer.php(567): OC_DB::createDbFromStructure('\\\/var\\\/www\\\/oc\\\/app...')\\n#6 \\\/var\\\/www\\\/oc\\\/lib\\\/private\\\/installer.php(546): OC_Installer::installShippedApp('activity')\\n#7 \\\/var\\\/www\\\/oc\\\/lib\\\/private\\\/updater.php(336): OC_Installer::installShippedApps()\\n#8 \\\/var\\\/www\\\/oc\\\/lib\\\/private\\\/updater.php(215): OC\\\\Updater->doUpgrade('9.0.0.19', '8.2.2.2')\\n#9 \\\/var\\\/www\\\/oc\\\/core\\\/ajax\\\/update.php(120): OC\\\\Updater->upgrade()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/oc\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":49}","level":3,"time":"2016-03-08T18:06:21+00:00","method":"GET","url":"\/oc\/core\/ajax\/update.php?requesttoken=FiIIMxNXKiYaAQYjHDItAGAReRgUASwYNgoUHW9nJhE%3D%3APVxYi2BTUElHoxcTSuAPs7btOIml94JA6z%2BJScF47Zw%3D"}
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by LukasReschke** [comment]
@nickvergessen Could this be caused by https://github.com/owncloud/activity/commit/7f6f2ab16b75f26154cc45ba6258993c0937c39b?

**Comment by kaksikanaa** [comment]
Same problem here on Arch LInux Arm / Owncloud 8.2 -> upgrade to 9.0.0.

**Comment by cattin** [comment]
If I understood it right you wanted me to remove the 107-114 from the file apps/activity/appinfo/database.xml. I then reran the "Start update" but still got the same error.

**Comment by LukasReschke** [comment]
@cattin No. Please don't touch the database.xml file yourself. That was just a question for @nickvergessen who is the maintainer of the activity app :wink:

**Comment by kaksikanaa** [comment]
Hmm, if I just drop the activity table for a moment and then rerun the update, it proceeds over this problem but second is similar with the database table oc_addressbooks -> "...Base table or view already exists: 1050 Table 'oc_addressbooks' already exists"

**Comment by nickvergessen** [comment]
Did you attempt an update, then restored a backup and are now trying it again?

**Comment by kaksikanaa** [comment]
Yes, I did that but the second update fails again first at 'oc_activity' already exists -> dropped that just see where it gets, tried again -> fails at 'oc_addressbooks'  -> Next fails to `oc_addressbookchanges` -> Next fails to 'oc_cards'  etc.   Have to go back 8.2.

**Comment by nickvergessen** [comment]
Yeah, because the first update created the tables.
Between your upgrade attempts please do not only restore the backup, but also delete all existing tables before restoring your backup.

**Comment by cattin** [comment]
For me this happened on the first update. I did not restore any tables (didn't even make a backup as suggested).

**Comment by skriems** [comment]
I have a similar problem with `oc_notifications` when trying to update from 8.2 to 9. My oc runs in a docker container (using PostgreSQL), so I deleted `version.php` and started the `.occ upgrade` which failed. I renamed to the table and got the same error msg with another table, so no luck.
Trying to go back to 8.2 gives me now the same error. oh well.
Will do some further examination now.

**Comment by pipiche38** [comment]
+1

**Comment by nickvergessen** [comment]
Why would you delete the version.php?!
