### ISSUE TITLE
Delay the check if the remote is an owncloud instance till we actually use the scanner

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#22973]
Ref https://github.com/owncloud/core/pull/22855, we should at this in a way so that other implementeros like Pydio still works.

This is especially relevant if one has mounted very slow S2S storages and no memory cache is configured.

Ref https://github.com/owncloud/core/issues/22987

**Comment by LukasReschke** [comment]
cc @icewind1991

**Comment by LukasReschke** [comment]
@cmonteroluque @karlitschek @PVince81 I added this to 9.0.1 since this has a substantial performance impact on instances in case no memory cache is configured and S2S remote endpoints respond very slow (or are down etc…)

**Comment by karlitschek** [comment]
makes sense

**Comment by LukasReschke** [comment]
I'll give it a try…

**Comment by LukasReschke** [comment]
https://github.com/owncloud/core/pull/22998
