### ISSUE TITLE
Upgrade oc8.2.2 to oc9 Server error 500 -> Cannot redeclare class OC_L10N

### ISSUE THREAD

**Issue by JB1985** [owncloud/core#22984]
### Steps to reproduce
1. Overwrite all files from 8.2.2 to 9.0
2. sudo -u web12 php occ maintenance:mode on
3. sudo -u web12 php occ upgrade
4. sudo -u web12 php occ maintenance:mode off

### Expected behaviour
I get a Server Error 500

The logs:

[Wed Mar 09 08:18:20.195784 2016] [:error] [pid 12410] [client XXX.XXX.XXX:43448] PHP Fatal error:  Cannot redeclare class OC_L10N in /var/customers/webs/web12/owncloud/lib/private/l10n.php on line 42
[Wed Mar 09 08:18:52.941684 2016] [:error] [pid 12433] [client XXX.XXX.XXX:43456] PHP Fatal error:  Cannot redeclare class OC_L10N in /var/customers/webs/web12/owncloud/lib/private/l10n.php on line 42

### Server configuration
**Operating system**: Debian Jessie 8.0

**Web server:** Apache 2.4.10

**Database:** mySQL 5.5.47

**PHP version:** PHP 5.6

**ownCloud version:** I hope 9.0 :)

**Updated from an older ownCloud or fresh install:** Updated from OC 8.2.2

**Where did you install ownCloud from:** From tarball source

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

sudo -u web12 php occ app:list
PHP Fatal error:  Cannot redeclare class OC_L10N in /var/customers/webs/web12/owncloud/lib/private/l10n.php on line 42

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
PHP Fatal error:  Cannot redeclare class OC_L10N in /var/customers/webs/web12/owncloud/lib/private/l10n.php on line 42

```

**Comment by LukasReschke** [comment]
Please describe how you updated. My bet is that you just put in all the new files without deleting the old ones. 

Do a `ls -lah` on `lib/private/` if it shows a "l10n.php" you did upgrade incorrectly.

**Comment by JB1985** [comment]
# ls -ls | grep l10n.php
16 -rw-r--r--  1 web12 web12 14461 Dec 21 07:46 l10n.php

Look at Steps to reproduce to see how i have do the update.

**Comment by LukasReschke** [comment]
> Overwrite all files from 8.2.2 to 9.0

That's wrong. Delete all files from 8.2.2 except /data/ and /config/ then upload the new files.

**Comment by JB1985** [comment]
Sorry! That's the mistake!

**Comment by ucyrus** [comment]
Same to me. Same error message. same I10n.php file in lib/private. 
I had to remove packet owncloud again, delete the whole owncloud directory, installed owncoud 9.0.0.1, unzip the downloaded owncloud 9, copy of the old config.php to subdir config, edited the version to 9.0.0.1 and run occ upgrade
