### ISSUE TITLE
Files Sidebar shows no entries

### ISSUE THREAD

**Issue by blizzz** [owncloud/core#22980]
### Steps to reproduce
1. Update to 9.0
2. Go to Files
3. Click on "Shared with you" in the left sidebar

### Expected behaviour
Files shared with you do appear

### Actual behaviour
"Nothing shared with you yet". However, in the default view, they appear. Log output:

```
{"reqId":"Ofw+\/U2oFGh7wP6x9G6L","remoteAddr":"92.200.128.123","app":"PHP","message":"OC\\Share20\\Exception\\InvalidShare:  at \/path\/to\/owncloud\/lib\/private\/share20\/defaultshareprovider.php#783","level":3,"time":"2016-03-09T01:14:16+00:00"}
```

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache2

**Database:** MySQL

**PHP version:** 5.5.9

**ownCloud version:** 9.0.0

**Updated from an older ownCloud or fresh install:** upgrade 

**Where did you install ownCloud from:** tarballs

**Signing status (ownCloud 9.0 and above):** awesome

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 44

**Operating system:** Antergos Linux

#### ownCloud log (data/owncloud.log)
```
{"reqId":"Ofw+\/U2oFGh7wP6x9G6L","remoteAddr":"92.200.128.123","app":"PHP","message":"OC\\Share20\\Exception\\InvalidShare:  at \/path\/to\/owncloud\/lib\/private\/share20\/defaultshareprovider.php#783","level":3,"time":"2016-03-09T01:14:16+00:00"}
```

@rullzer

**Comment by rullzer** [comment]
I'm not sure why you code would actually follow that path. Could you send me a dump of your oc_share table? Seems the migration did not finish its job...

**Comment by blizzz** [comment]
@rullzer Shared to you

**Comment by rullzer** [comment]
Ok I think I know why... the SQL queries are not narrow enough and they pick up your shared calendar and contacts... let me prepare a patch...

**Comment by rullzer** [comment]
Possible fix in https://github.com/owncloud/core/pull/23008 please have a look. The patch is pretty simple

**Comment by rullzer** [comment]
Fixed with #23008
Backport to stable9 in #23016

**Comment by blizzz** [comment]
For the record, the sections "Shared with others" and "Shared by link" did not work, because of bogus entries in the share table. Basically link shares without token. Very likely they origin from a very early improper migration (the instance exists since OC 4, at least, and those shares were from 2012). Since those links don't work anymore, deleting them from the DB fixed the issue: ``delete from share where share_type = '3' and token is null;`` The token was not present already before upgrading to OC 9. Repair step is a candidate.

**Comment by Kawohl** [comment]
had the same here on fresh installs on opensuse leap.
