### ISSUE TITLE
Wrong documentation link (Performance Tuning)

### ISSUE THREAD

**Issue by MeCias** [owncloud/core#22985]
Hi,

Just noticed that under OC9 final in the admin area under Tips & Tricks the link Performance Tuning has not the right link.

It is linked to 

https://doc.owncloud.org/server/9.0/admin_manual/configuration_server/performance_tuning.html

and should most likely be linked to

https://doc.owncloud.org/server/9.0/admin_manual/configuration_server/performance_tuning/index.html

**Comment by LukasReschke** [comment]
Thanks. I adjusted the URLs, they should be fixed with the next deployment of the documentation.
