### ISSUE TITLE
Unknown .htaccess and external site icons causing integrity check to fail

### ISSUE THREAD

**Issue by sndrsk** [owncloud/core#22982]
### Expected behaviour
oC 9 passes integrity check

### Actual behaviour
oC 9 fails integrity check, based on .htaccess in /core/ that I can't find, plus icons needed in the external sites img folder (I do have hidden files visible turned on in WinSCP)

### Server configuration
**Operating system**: Ubuntu

**Web server:** nginx

**Database:** MySQL

**PHP version:** 5.6

**ownCloud version:** 9

**Updated from an older ownCloud or fresh install:** Manually updated from 8.2.2

**Where did you install ownCloud from:** zip

**Signing status (ownCloud 9.0 and above):**

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- .htaccess
- external
	- EXTRA_FILE
		- img/mightytext.png
		- img/wallabag.png
		- img/weather.png

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.htaccess] => Array
                        (
                            [expected] => f40e7ca19cd76ff922ccd164e38f4d73806f66170cafa202fb470be225c813b4b242f4321da8a01bef1329e300acf3d137dbcbff058c501f166a2619031fc651
                            [current] => fc32b2dc1c0049127185f5e530140bcbe8e7bd9f9ddee4c73edc38e7aa68642327623155758dec05aa345223900673b9c22bcf3d4fb276ca06afef245ce8839b
                        )

                )

        )

    [external] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [img/mightytext.png] => Array
                        (
                            [expected] => 
                            [current] => 7fa67f0a65a60ecee5111a92981f8223300214db633411d84072ffbec55fa8bcd15598458c872441acf4d92159b5111d5a35fcb581f676d7d1bec5c87a818404
                        )

                    [img/wallabag.png] => Array
                        (
                            [expected] => 
                            [current] => 04567ef021f4caf8877a7516070246799696040a6c0ed6a0bb543a24eef027bb0c10dd5368323d642a2d9e6a913b7f44a49d3fafbdeacedae07941d5e1d7239b
                        )

                    [img/weather.png] => Array
                        (
                            [expected] => 
                            [current] => c2a7e4378e0944ed11f23c58b3dce7f583ddebad9d5727c2364ec829802228e7d2e198fae08ac9a19267688a45c0e8fbe9aea81a818885fdb4c6e9e79da27966
                        )

                )

        )

)
```

**List of activated apps:** Activity, default encryption module, documents, external storage support, first run wizard, gallery, mail template editor, notifications, PDF viewer, provisioning API, share files, text editor, updater, bookmarks, calendar, contacts, mail, news, notes, tasks

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'debug' => false,
  'instanceid' => 'oc6aoeblvimo',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => 'domain.com',
  ),
  'datadirectory' => '/home/user/domain.com/oc-data',
  'overwrite.cli.url' => 'https://domain.com',
  'dbtype' => 'mysql',
  'version' => '9.0.0.19',
  'dbname' => 'oc',
  'dbhost' => 'mysql.sanders.io',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'user',
  'dbpassword' => '',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_from_address' => 'web',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'domain.com',
  'theme' => 'sandbox',
  'maintenance' => false,
  'defaultapp' => 'mail',
  'loglevel' => 0,
  'app.mail.imaplog.enabled' => false,
);

```

**Are you using external storage, if yes which one:** WebDAV

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

**Operating system:** Windows 10

#### Web server error log
```
(none)
```

#### ownCloud log (data/owncloud.log)
```
(none since upgrade)
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by sndrsk** [comment]
I rummaged around a little bit and this came up in the oC error log:

```
{"reqId":"Vt@190WjkHcAAAj7qk0AAAAB","remoteAddr":"123.12.123.123","app":"mail","message":"loading messages 0 to 20 of folder <SU5CT1g=>","level":0,"time":"2016-03-09T05:34:48+00:00","method":"GET","url":"\/box\/index.php\/apps\/mail\/accounts\/1\/folders\/SU5CT1g%3D\/messages?from=0&to=20&filter="}
{"reqId":"Vt@2YEWjkHcAABPNREoAAAAA","remoteAddr":"123.12.123.123","app":"core","message":"No update found at the ownCloud appstore for app 166046","level":0,"time":"2016-03-09T05:36:34+00:00","method":"GET","url":"\/box\/index.php\/settings\/apps\/list?category=enabled&includeUpdateInfo=1"}
{"reqId":"Vt@2YEWjkHcAABPNREoAAAAA","remoteAddr":"123.12.123.123","app":"core","message":"No update found at the ownCloud appstore for app 166048","level":0,"time":"2016-03-09T05:36:35+00:00","method":"GET","url":"\/box\/index.php\/settings\/apps\/list?category=enabled&includeUpdateInfo=1"}
{"reqId":"Vt@2YEWjkHcAABPNREoAAAAA","remoteAddr":"123.12.123.123","app":"core","message":"No update found at the ownCloud appstore for app 166049","level":0,"time":"2016-03-09T05:36:36+00:00","method":"GET","url":"\/box\/index.php\/settings\/apps\/list?category=enabled&includeUpdateInfo=1"}
{"reqId":"Vt@2YEWjkHcAABPNREoAAAAA","remoteAddr":"123.12.123.123","app":"core","message":"No update found at the ownCloud appstore for app 166051","level":0,"time":"2016-03-09T05:36:36+00:00","method":"GET","url":"\/box\/index.php\/settings\/apps\/list?category=enabled&includeUpdateInfo=1"}
{"reqId":"Vt@2YEWjkHcAABPNREoAAAAA","remoteAddr":"123.12.123.123","app":"core","message":"No update found at the ownCloud appstore for app 166055","level":0,"time":"2016-03-09T05:36:37+00:00","method":"GET","url":"\/box\/index.php\/settings\/apps\/list?category=enabled&includeUpdateInfo=1"}
```

**Comment by LukasReschke** [comment]
> oC 9 fails integrity check, based on .htaccess in /core/

The .htaccess is the main .htaccess in the root folder. My guess is that while updating you did not replace it with the new version, thus it contains now multiple inserts by ownCloud like "#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####"

> plus icons needed in the external sites img folder

This is a bug in the external sites app. It should

**Comment by RealRancor** [comment]
> The .htaccess is the main .htaccess in the root folder. My guess is that while updating you did not replace it with the new version, thus it contains now multiple inserts by ownCloud like "#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####"

As also suggested in https://github.com/owncloud/core/issues/22966 this .htaccess should be either not checked or upload limit stuff should be removed from that. Its very likely that you will get tons of reports about those here.

**Comment by LukasReschke** [comment]
> As also suggested in #22966 this .htaccess should be either not checked or upload limit stuff should be removed from that. Its very likely that you will get tons of reports about those here.

No. It has to be checked. We need to ensure that users use the newest .htaccess, this is what we did before as well. (e.g. just with the "Your htaccess is not correct") warning.

Replacing the values is not a problem as stated in https://github.com/owncloud/core/issues/22966#issuecomment-194162880

**Comment by sndrsk** [comment]
Thanks, I will double check these after work tonight. How can I fix the external sites issue? Will disabling the app work or will the scanner still see the images there and flag it?

Also, will the cron job not run if the file integrity check fails? Cron has not been successful since I upgraded last night.

**Comment by ezraholm50** [comment]
Would this error go away if its only the core .htaccess error and not the icons error, upon updating ownCloud from 9.0.19 to the next version?
