### ISSUE TITLE
well-known URLs for contacts and calendar

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#22995]
@DeepDiver1975 @evert 

Should they point to `remote.php/dav/calendars` and `remote.php/dav/contacts` instead of just to `remote.php/dav`.

I used DAVdroid and after changing this the caldav and carddav was auto detected.

cc @LukasReschke for the rewrite rule.

**Comment by DeepDiver1975** [comment]
According to http://sabre.io/dav/service-discovery/ the root dav url should be used - and this is working with caldav sync and ios - so I suspect davdroid having an issue

**Comment by evert** [comment]
Root dav url should indeed be fine
