### ISSUE TITLE
IApacheBackend implementation fails for new users

### ISSUE THREAD

**Issue by GitHubUser4234** [owncloud/core#22992]
Hi,

Logging in through an ownCloud 8.2.1 IApacheBackend implementation fails for new users who never logged in by username/password before. It can be reproduced this way:

1) Use Admin account to create a new user "abcd".
2) Write a backend app implementing IApacheBackend with isSessionActive() returning true and getCurrentUserId() returning "abcd"
3) Enable the backend app
4) Access ownCloud, login fails with this error:

> Exception: {"Exception":"OCP\\Files\\NotFoundException","Message":"","Code":0,"Trace":"
> #0 \/owncloud\/apps\/files\/index.php(92): OC_Helper::getStorageInfo('\/', false)
> #1 \/owncloud\/lib\/private\/route\/route.php(154) : runtime-created function(1): > require_once('\/owncloud\/apps\/user_ext...')
> #2 [internal function]: __lambda_func(Array)
> #3 \/owncloud\/lib\/private\/route\/router.php(282): call_user_func('\\x00lambda_2305', Array)
> #4 \/owncloud\/lib\/base.php(851): OC\\Route\\Router->match('\/apps\/files\/')
> #5 \/owncloud\/index.php(39): OC::handleRequest()
> #6 {main}","File":"\/owncloud\/lib\/private\/helper.php","Line":841}

5) Disable the backend app
6) User "abcd" logs in by username/password and logs out again
7) Enable the backend app
8) Access ownCloud, user "abcd" is logged in successfully

Thanks for any help.

**Comment by LukasReschke** [comment]
Please share your application code. We can't help otherwise.

**Comment by GitHubUser4234** [comment]
Sure, here it is:

user_ext_test/appinfo/app.php:

```php
<?php


	require_once 'user_ext_test/lib/test.php';

	// register user backend
	OC_User::useBackend( 'EXT_TEST' );
```

user_ext_test/lib/test.php:

```php
<?php


class OC_USER_EXT_TEST extends \OCP\Authentication\IApacheBackend{ {
	
	/**
	 * Create new authentication provider
	 *
	 */
	public function __construct() {
		parent::__construct("OC_USER_EGIS_USER_DP");
	}

	/**
	 * In case the user has been authenticated by Apache true is returned.
	 *
	 * @return boolean whether Apache reports a user as currently logged in.
	 */
	public function isSessionActive() {
		return true;
	}
	
	/**
	 * Return the id of the current user
	 * @return string
	 */
	public function getCurrentUserId(){
		return "abcd";
	}
	
	/**
	 * Creates an attribute which is added to the logout hyperlink. It can
	 * supply any attribute(s) which are valid for <a>.
	 *
	 * @return string with one or more HTML attributes.
	 */
	public function getLogoutAttribute(){
		return 'href="' . link_to('', 'index.php') . '?logout=true&amp;requesttoken=' . urlencode(\OCP\Util::callRegister()) . '"';
	}
}
```

**Comment by GitHubUser4234** [comment]
I saw that the exception is thrown in the getStorageInfo() method of core/lib/private/helper.php, in particular this code:

```php
if (!$rootInfo instanceof \OCP\Files\FileInfo) {
			throw new \OCP\Files\NotFoundException();
		}
```

Maybe the username/password login initializes something on first login but the Apache API is missing it?

**Comment by DeepDiver1975** [comment]
> class OC_USER_EXT_TEST implements \OCP\Authentication\IApacheBackend {

only implementing IApachebackend is not enough - please get in touch with us on irc - the issue tracker is for real issues and enhancement requests not for general development help.

THX

**Comment by GitHubUser4234** [comment]
Oh, I was in fact thinking it was a bug. Thanks for the hint though, will contact you there :)

**Comment by GitHubUser4234** [comment]
As it turned out to be a core bug, but DeepDiver1975 doesn't have the resources to reopen/investigate the bug, a new issue #23899 has been created.
