### ISSUE TITLE
ownCloud 9: OC\Share20\Exception\InvalidShare

### ISSUE THREAD

**Issue by BenS89** [owncloud/core#22997]
### Steps to reproduce
1. Upgrade from ownCloud 8.2.2 to 9.0
2. Open the admin panel
3. Take a look at the logfiles

### Expected behaviour
No errors in the logiles
The views "shared by me" and "shared by link" work correctly

### Actual behaviour
the following error is logged multiple times:<code>OC\Share20\Exception\InvalidShare: at /share/MD0_DATA/htdocs/owncloud/lib/private/share20/defaultshareprovider.php#783</code>

The views "shared by me" and "shared by link" are empty even though files are shared

### Server configuration
**Operating system**: Embedded QNAP Linux

**Web server:** Apache 2.4.12

**Database:** MariaDB 5.5

**PHP version:** 5.6

**ownCloud version:** (see ownCloud admin page) 9.0

**Updated from an older ownCloud or fresh install:** Upgraded from 8.2.2

**Signing status (ownCloud 9.0 and above):** "No errors have been found."

**List of activated apps:**
Calendar 1.0
Contacts 1.0

**Comment by LukasReschke** [comment]
@owncloud/sharing

**Comment by rullzer** [comment]
Do you have shared calendar and/or contacts?

**Comment by BenS89** [comment]
No, I don´t. This error occurs everytime I want to see the views "shared by me" and "shared by link". Both views should not be empty, but they are (see issue [#23000](https://github.com/owncloud/core/issues/23000))

**Comment by calis2002** [comment]
I got the same error message in the log after visiting "shared with me" and the page is empty.
"shared by me" is working fine and and actually shows my shared files.

**Comment by BenS89** [comment]
I have a federated cloud share with another ownCloud server with version 8.2.2
Could this cause problems if an ownCloud server 9 has a federated share with an ownCloud server 8.2.2? Nevertheless, this cannot be the root cause since "shared by link" causes this exception, too...

**Comment by rullzer** [comment]
Two things to consider.

1. Does https://github.com/owncloud/core/pull/23016 fix your problem?
2. Maybe it is https://github.com/owncloud/core/issues/22980#issuecomment-194297195

**Comment by calis2002** [comment]
@rullzer #23016 fixed the problem for me, thanks

**Comment by BenS89** [comment]
@rullzer #23016 fixed the issue for me, too. Really nice. Thanks

**Comment by rullzer** [comment]
Lets keep this ticket open a while longer. Just so that other can find it as well. Because I have the feeling this will show up a few times before 9.0.1

**Comment by PVince81** [comment]
Let's close this now, no new tickets have been linked to this one since 5 days.
I don't mind taking care of linking duplicates when they pop up.

**Comment by godfuture** [comment]
Heyho, I have this issue as well.
It seems #23016 is fixing this issue. How can I apply such a fix? Thx!

**Comment by rullzer** [comment]
@godfuture well if you don't know how to patch yourself I would suggest not to try it on a live system. 9.0.1 is expected to be released soonish so best to just upgrade to that.

**Comment by TheReal1604** [comment]
Hey guys,

got this error too, but #23016 not fix this for me.

`Call to undefined method OCA\user_ldap\lib\user\OfflineUser::composeAndStoreDisplayName() at /var/www/owncloud/apps/user_ldap/user_ldap.php#381	`
Is permanently in my logfile then i try to show the "shared by me" view.

Anyone have an idea?

**Comment by PVince81** [comment]
@TheReal1604 then it is likely a different issue with similar symptoms. Can you make a new ticket and use the issue template ? https://raw.githubusercontent.com/owncloud/core/master/issue_template.md
Then ping me there. Thanks!
