### ISSUE TITLE
Ability to Manage Version Branches

### ISSUE THREAD

**Issue by dragotin** [owncloud/core#23002]
Currently the versions app only can deal with  linear versions of a file, one version follows on the next. However, in the world of multiple devices syncing a file it happens that conflict files need to be created on clients. The reason is that the file is changed on a two independent devices at the same time. 

The current handling of conflict files on the desktop client is to save the local change and prefer the server version. That has issues and is subject of tickets such as owncloud/client#3222 and owncloud/client#4079.

The main concern is that we currently do not save changes of the conflict file to the server and as a result, the file is not secured.
### Proposal: Version Branches

The version app should be aware of the ETag which is the uniq identifier of a version of a file. There should be the possibility to save a file version as direct successor of a specific (previous) ETag via a PUT request.  The client could send the ETag of the predecessor version of this specific file in a HTTP header This would enable the client to build up version branches. 

A file that was uploaded as followup version of a former version of the file would need a new, not yet used ETag assigned by the versions app. That needs to be sent back to the client with a header in the reply.

Note that a branch version of a file would not be visible in the ownCloud WI by default, only through the versions app if we want that.

Both creating the branch versions as well as retrieving it should be added to the API discussed in #10571. 

@MTRichards @karlitschek @DeepDiver1975

**Comment by karlitschek** [comment]
Good idea.
No sure if this is a feature 'normal' users would understand or need.
But something to consider.

**Comment by MTRichards** [comment]
Wow, lots of thought. It is an interesting way to fix the "lost data" user story about how a conflict file is not replicated to the server.

Is there a simpler way than adding all the version branching / UX complexity to push conflict files to the server?

**Comment by PVince81** [comment]
> Is there a simpler way than adding all the version branching / UX complexity to push conflict files to the server?

Upload the conflict file to the server with a special file name. If that's not enough, set a special tag "conflict" on it. Or have an additional custom property "oc:originalFile" containing the original file name to which the conflict file refers to. That would make it possible to also provide conflict resolution in the web UI.

**Comment by dragotin** [comment]
Yes, that would be possible. But what would be the result? A *new* file with no natural relation to the original file. The versions app maintains at least the relation *this version is successor of this version* so I thought it would be more obvious to enhance that app.

**Comment by PVince81** [comment]
Or instead of implementing "multiple version branches support" which can be complex, only have an single internal special branch for conflicts.

On another note: if one day we decide to explore multi-branch versioning, it would become possible to use the official Webdav versioning API. The current versioning isn't really compatible with that.

**Comment by SamuAlfageme** [comment]
Linking this here: https://github.com/owncloud/core/pull/29257

**Comment by PVince81** [comment]
not sure if this is really part of the basic use case of ownCloud.

this could be implemented as a separate different app that tracks its own versions and the branching, and needs a way to switch branches

would close as "out of scope"

@pmaier1

**Comment by phil-davis** [comment]
This is what ``git`` does - you have multiple versions of a file in branches and have to resolve conflicts...
The whole of a user's local storage could be a git repo, and the normal flow is that every file upload/delete/change is a commit to master... Then you have full version history and can make branches for conflicts and...

:)
