### ISSUE TITLE
Integrity check on occ upgrade takes forever

### ISSUE THREAD

**Issue by haolink** [owncloud/core#23007]
Dear owncloud team,

I was ugprading my owncloud server today using the Ubuntu 14.04 packages. Sadly the new integrity check is taking just forever.

I can see the reasoning why this was added but in this current form. Maybe there's some PHP dependency I'm missing which makes code signing verification horribly slow?

Steps to reproduce:
1. Run ./occ upgrade (alternative php5.6 ./occ upgrade to force using PHP 5.6) - also tested with -vvv parameter but sadly code integrity doesn't give verbose details.

Expected behaviour:
Upgrade takes some time but usually within reason (never longer than 5 minutes in the past).

Actual behaviour:
"Starting code integrity check..." - and it stalls - tested for 2 hours.

Server configuration:

Operating system: Ubuntu Linux 14.04 LTS
Web Server: Apache 2.4.18 (repository: https://launchpad.net/~ondrej/+archive/ubuntu/apache2 ) - command however being executed from console so I assume irrelevant
Database: MariaDB 10.0.24 (trusty - mariadb.org binary distribution)
PHP version: 7.0.4 / 5.6.19 (repository: https://launchpad.net/~ondrej/+archive/ubuntu/php )
ownCloud version: 9.0.0
Where did you install ownCloud from: Ubuntu 14.04 repository
Signing status: Unknown

Notice about the server hardware to not blame this:
CPU: Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
RAM: 32 GB (much of it available during the executions of the upgrade command)

List of activated apps: 
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0

config.php:```
{
    "system": {
        "instanceid": "ocpvqbmtgndf",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***removed by me***"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "***removed by me***",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "forceSSLforSubdomains": false,
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "tls",
        "theme": "",
        "maintenance": true,
        "loglevel": 0,
        "trashbin_retention_obligation": "auto",
        "updatechecker": false
    }
} ```

External storage: sftp but only for select data
Encryption: no
External user backend: No
LDAP: Not in use

Client configuration is irrelevant I imagine

**Comment by LukasReschke** [comment]
It should actually work quite fast (less than 2 minutes), this more likely indicates an environmental issue or some unchecked dependencies etc.

Can you apply https://github.com/owncloud/core/commit/ab8f64ad693f19f7467a41d469850ef38c10c2af on your instance? It should then contain some more output.

Also any chance you can share your phpinfo() output with us?

**Comment by haolink** [comment]
Thank you for the very quick reply. I applied the patch to my instance - and well: the output gave me the hint. The sessions folder was just full - there were 550463 files in there and the upgrade process tried to generate a signature for each of it. This obviously stopped the process from advancing. I imagine I will have to check my PHP session save path - and why it didn't delete older session files.

So this wasn't a problem directly related to owncloud but to my PHP configuration.

Thank you :) . Feel free to close this bug unless you still have something to add.

**Comment by LukasReschke** [comment]
> Thank you for the very quick reply. I applied the patch to my instance - and well: the output gave me the hint. The sessions folder was just full - there were 550463 files in there and the upgrade process tried to generate a signature for each of it. 

That is interesting. It should actually not to generate signatures of the sessions. Where do you have your ownCloud installed and where do your sessions live? :)

**Comment by haolink** [comment]
My sessions used to live in the file system. As PHP runs as a FPM with user privileges it stored them in ~/sessions . Owncloud was installed in /var/www/owncloud using the standard repository using https://download.owncloud.org/download/repositories/stable/owncloud/ which installs it there.

The only change I always do is changing the owner from root to owncloud - as owncloud is the user under which the FPM instance of owncloud was running. /var/www/owncloud has also been set to the home address of this user - so there were files which had nothing to do with owncloud. .bash_history and other files have also been in there. I cleaned up the folder from foreign files and switched the home directory of that user so that no new files would be automatically created in it by external processes.

**Comment by LukasReschke** [comment]
Gotcha.
