### ISSUE TITLE
Calendar doesn't support dates before Unix epoch => can't import contact birthdays

### ISSUE THREAD

**Issue by twistedfall** [owncloud/core#23004]
You can't create event in the calendar with the start/end date that predates Unix epoch because of the column type for oc_calendarobjects.firstoccurence and calendarobjects.lastoccurence being INT UNSIGNED. This problem is especially visible when system tries to create birthday calendar entries for "older" (born before 1970) contacts.

Modifying the type of those columns to just BIGINT resolves the problem. Using BIGINT helps with another problem of how iOS stores birthdates without a year, it assigns them year 1604 resulting in a very long timestamp like -11540880000

**Comment by LukasReschke** [comment]
cc @DeepDiver1975

**Comment by DeepDiver1975** [comment]
@twistedfall THX - can I ask you for an example ics file which holds data as described? THX

**Comment by twistedfall** [comment]
Sure:

[before-epoch.vcf.ics.txt](https://github.com/owncloud/core/files/165113/before-epoch.vcf.ics.txt)

**Comment by DeepDiver1975** [comment]
THX

**Comment by PVince81** [comment]
Is this a regression ?

**Comment by DeepDiver1975** [comment]
I never tried with the old calendar app - unsure ..

But worth a notification to @evert https://github.com/fruux/sabre-dav/blob/master/examples/sql/mysql.calendars.sql#L10

**Comment by twistedfall** [comment]
The old table has these fields:

`startdate`	 datetime
`enddate`	datetime	

so I suppose yes, it is a regression

**Comment by evert** [comment]
What are the symptoms of the problem? The firstoccurence/lastoccurence stuff is specifically for things like querying/freebusy which generally is not really important for dates that far in the past.

So I'm curious what you are seeing. Where is it going wrong? Any error messages?

**Comment by twistedfall** [comment]
I encountered this problem when trying to migrate the birthdays using `occ dav:sync-birthday-calendar`. It kept giving me error messages like:

[https://gist.github.com/twistedfall/f3c77514da447f9b6447](https://gist.github.com/twistedfall/f3c77514da447f9b6447)

and then, after fixing INT UNSIGNED to just INT:

[https://gist.github.com/twistedfall/5a6608191dac6cce7cf7](https://gist.github.com/twistedfall/5a6608191dac6cce7cf7) (this is the one created by iOS, when you set up only day and month, but not the year for the contact's birthday)

changing to BIGINT helped in this case.

I also tried to create event with date of 01-01-1950, it failed producing similar error message in the log.

**Comment by DeepDiver1975** [comment]
@twistedfall I just tested this with mysql and firstoccurence is set to 0 - no exception is thrown

**Comment by evert** [comment]
So perhaps the migration script should ensure that those values are set to 0 for values ` < 0 `. I don't know if this is also an issue on the sabre side.

**Comment by twistedfall** [comment]
Do you mean that you supplied firstoccurence to be `0`, or you supplied negative value and it was set to `0` in the database?

**Comment by twistedfall** [comment]
It's not an option to set negative values to `0` as it breaks the date encoded into timestamp, basically a date of birth of 04-12-1950 will be reset to 1970-01-01.

**Comment by DeepDiver1975** [comment]
> Do you mean that you supplied firstoccurence to be 0, or you supplied negative value and it was set to 0 in the database?

I basically insert your ics file - https://github.com/owncloud/core/pull/23018/files#diff-f3017aa6638f5486e5938504e2f4faa5R472 and firstoccurrance is 0 in the database

**Comment by DeepDiver1975** [comment]
@twistedfall which database are you using?

**Comment by evert** [comment]
> It's not an option to set negative values to 0 as it breaks the date encoded into timestamp, basically a date of birth of 04-12-1950 will be reset to 1970-01-01.

This shouldn't be a problem. It doesn't affect your source data, just your indexes.

**Comment by DeepDiver1975** [comment]
> It's not an option to set negative values to 0 as it breaks the date encoded into timestamp, basically a date of birth of 04-12-1950 will be reset to 1970-01-01.

as @evert explained this column is only used for query - we have to check if this still works at the end

**Comment by twistedfall** [comment]
I see. The database version is MySQL 5.6.29-1debian8

**Comment by vonschultz** [comment]
This bug is not fixed. In `apps/dav/appinfo/database.xml`, I had to change 
`<name>firstoccurence</name>
                        <type>integer</type>
                        <unsigned>true</unsigned>
                        <length>11</length>` to `...  <unsigned>false</unsigned> ...` before an upgrade with a date before Unix epoch went through. Just changing `firstoccurrence` to BIGINT doesn't solve the problem if the BIGINT is still unsigned.
