### ISSUE TITLE
ownCloud 9 | occ files:scan --all memory error with local storage

### ISSUE THREAD

**Issue by Kaelber** [owncloud/core#23019]
I use Synology servers all equiped with ownCloud as follow : 

DS1815+ with DSM 5.2-5644 update 5,
DS412+ with DSM 5.2-5644 update 5,
DS1512+ with DSM 5.2-5644 update 5,
DS712+ with DSM 6.0 RC-1,
DS414 with DSM 5.2-5644 update 5.

I only use server directories with External Storage Support "Local" and the client v2.1.1 and for a smooth running I use the cron´s 

0,10,20,30,40,50	*	*	*	*	root	/bin/su -s /bin/sh -c "/usr/bin/php -f /volume1/web/owncloud/cron.php" http 

0,30	7-22	*	*	*	root	/bin/su -s /bin/sh -c "cd /volume1/web/owncloud && /usr/bin/php -f occ files:scan rescan" http 

10	0	*	*	*	root	/bin/su -s /bin/sh -c "cd /volume1/web/owncloud && /usr/bin/php -f occ files:scan --all" http 

The first line is regarding the cron.php and the next 2 lines are file rescans for the user "rescan" and once per day for all user. The user "rescan" I use for choosed folders to shorten the scanning time in the main daily time.

With the Synology DSM 5.2 and ownCloud 8.2.2.2 all is running well. Now with the new ownCloud version 9.0.0.19 the cron.php is running, because I see the update in "Administration". The second line, it seems also, that it run, because of the log as follow : 

####################################################################

Starting scan for user 1 out of 1 (rescan)

+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 1381 | 11021 | 00:04:49 |
+---------+-------+--------------+

####################################################################

But !

Modified files on client side are uploaded with the client but only download files that have been changed on the server side does not always work as download. This effect I have in the past when I using ownCloud version 8.x.x.x without the rescan in the crontab. 

A log for the scan for all users I have in the follow condition :

####################################################################

Scanning files for 4 users
Starting scan for user 1 out of 4 (admin)
Starting scan for user 2 out of 4 (x)
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 36 bytes) in /volume1/web/owncloud/lib/private/files/cache/cache.php on line 200

####################################################################

at another time I got

####################################################################

Scanning files for 4 users
Starting scan for user 1 out of 4 (admin)
Starting scan for user 2 out of 4 (x)
Starting scan for user 3 out of 4 (y)
Starting scan for user 4 out of 4 (z)

+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 4217    | 31376 | 00:17:26     |
+---------+-------+--------------+

####################################################################

I also got the message 

"PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20 bytes) in /volume1/web/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 91"

from the log of cron.php.

Regarding the documentation all commands are the same. What changing is the problem, what is to doe?

**Comment by LukasReschke** [comment]
cc @icewind1991

**Comment by PVince81** [comment]
@icewind1991 does PHP's stat cache also eat memory ?

**Comment by Kaelber** [comment]
In this moment it seems normal. The name of process is "php-fpm" and in the summary this use 85 MB RAM

**Comment by Kaelber** [comment]
I imagine, we have to wait until version 9.0.1 until next tests ........?

**Comment by icewind1991** [comment]
> @icewind1991 does PHP's stat cache also eat memory ?

Not sure and google doesn't seem to help there either

**Comment by Bazon** [comment]
I think I have a close to same problem:
I use my owncloud server as a radio-recorder with streamripper, too. After recording, I run a scan only in the path of the recording (with occ files:scan --path=....). So it's only a relativly small amount of files and definitely no php-RAM issue (which I solved anyhow for rescan all with a bigger RAM for php).
What happens is:
The scan is successful, when I use my browser and the owncloud webinterface, the new files appear where they should.
BUT!:
This doesn't trigger any sync activity. Neither on the activity page in the webinterface, nor in the server-activity tab in the sync-client. 
I'm using owncloud 9.0.0-1 and owncloud-client 2.1.1-1 on arch linux. (-1 is arch specific.)

**Comment by Bazon** [comment]
(PS: And as no sync activity is triggered, the files are not downloaded either. although they appear in the webinterface.)

**Comment by icewind1991** [comment]
> @icewind1991 does PHP's stat cache also eat memory ?

We clear the statcache already so that shouldn't be a problem

I've done some experimentation but I can't find any issue with memory leaks in the scanner

Note that switching from the databased based locking backend to the memcache/redis based one does seem to decrease the memory usage significantly with the scanner

**Comment by Bazon** [comment]
> I also got the message
> 
> "PHP Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20 bytes) in /volume1/web/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 91"


That's 128MB and may be too small for large owncloud data. (I ran into that before) You can change the allowed memory size in /etc/php/php.ini with memory_limit. I changed mine to `memory_limit = 2048M` and I'm satisified with that.

**Comment by PVince81** [comment]
@icewind1991 didn't we cache the lock information in memory / PHP attributes ? Maybe these should also be capped ?

**Comment by PVince81** [comment]
or they should be deleted after the lock is released, as in `delete $someArray['value']` instead of just setting to null ?

**Comment by PVince81** [comment]
For example unset when reaching 0 ?
- https://github.com/owncloud/core/blob/v9.0.0/lib/private/lock/abstractlockingprovider.php#L62
- https://github.com/owncloud/core/blob/v9.0.0/lib/private/lock/abstractlockingprovider.php#L79

Might cause PHP to restructure its internal hash table ? If unsetting makes it slower, then maybe only do this after a certain time has elapsed, some kind of GC ?

**Comment by icewind1991** [comment]
> For example unset when reaching 0 ?

Tried this but it only seems to save a few hunderd kb out of the ~70mb

**Comment by MorrisJobke** [comment]
Profiling analysis:

Nearly empty: https://blackfire.io/profiles/0b90caa3-cd5f-4293-a225-09333bd04938/graph
10k files: https://blackfire.io/profiles/b6b1fe75-8967-4d2a-adec-6e3160d8f3a0/graph
20k files: https://blackfire.io/profiles/362a9921-d242-45f4-84fa-ad5a4ddd9312/graph
120k run: https://blackfire.io/profiles/25679b5a-0a18-44eb-9f93-949731adee90/graph

<img width="989" alt="bildschirmfoto 2016-03-31 um 16 32 53" src="https://cloud.githubusercontent.com/assets/245432/14179350/1b2650d0-f75f-11e5-8df3-a7bbfbb84035.png">

<img width="988" alt="bildschirmfoto 2016-03-31 um 16 32 34" src="https://cloud.githubusercontent.com/assets/245432/14179357/2586c56e-f75f-11e5-9712-f5b9510297af.png">

<img width="989" alt="bildschirmfoto 2016-03-31 um 16 39 16" src="https://cloud.githubusercontent.com/assets/245432/14179367/2ab78582-f75f-11e5-8d15-e9c5abc46c41.png">

<img width="996" alt="bildschirmfoto 2016-03-31 um 16 49 38" src="https://cloud.githubusercontent.com/assets/245432/14179768/a8e9371a-f760-11e5-951a-5e7833149f76.png">

10k vs 20k comparision: https://blackfire.io/profiles/compare/70cb699d-971a-45e6-9801-ad2ab96fbbb0/graph
20k vs 120k: https://blackfire.io/profiles/compare/0842e923-3ab1-4387-a51b-94e8278ec713/graph

Somehow this time it used less memory.

And I had a crashed 120k scan:

120k files hits the limit of 1G here:

https://blackfire.io/profiles/d0dd4ef7-281a-47b7-9431-46ce7f785d5a/graph

<img width="1328" alt="bildschirmfoto 2016-03-31 um 16 44 34" src="https://cloud.githubusercontent.com/assets/245432/14179583/ed09a21e-f75f-11e5-90dd-16bb9824f7c4.png">

**Comment by MorrisJobke** [comment]
Honestly I have no idea how to properly analyze this :( Could we maybe have a look at this during the team week?

**Comment by Kaelber** [comment]
May is possible to include the rescan engine completly in ownCloud, so it´s also ajustable over the administration side. So also no crontab or others is needed. Because with further tests the above effect I had with v9.0.0, now with the current version v9.0.1 I have no change. This effect I have with Synology DSM 5.2 and if I test the new DSM 6.0 I also have no rescan, no logs and additionally a problem with drivers.

**Comment by Kaelber** [comment]
Attached some logs I got from ownCloud, made with ownCloud v9 RC-1 and Synology-Server with DSM 5.2-5644 Update 5.

[cron_rescan_all_2016-04-01_00-10-01-2.txt](https://github.com/owncloud/core/files/199244/cron_rescan_all_2016-04-01_00-10-01-2.txt)
[cron_rescan_rescan_2016-04-01_08-00-01.txt](https://github.com/owncloud/core/files/199243/cron_rescan_rescan_2016-04-01_08-00-01.txt)
[cron_rescan_rescan_2016-04-01_08-30-01.txt](https://github.com/owncloud/core/files/199246/cron_rescan_rescan_2016-04-01_08-30-01.txt)
[cron_rescan_rescan_2016-04-01_09-00-01.txt](https://github.com/owncloud/core/files/199247/cron_rescan_rescan_2016-04-01_09-00-01.txt)
[cron_rescan_rescan_2016-04-01_09-30-01.txt](https://github.com/owncloud/core/files/199248/cron_rescan_rescan_2016-04-01_09-30-01.txt)
[cron_rescan_rescan_2016-04-01_10-00-01.txt](https://github.com/owncloud/core/files/199245/cron_rescan_rescan_2016-04-01_10-00-01.txt)
[cron_rescan_rescan_2016-04-01_10-30-01.txt](https://github.com/owncloud/core/files/199249/cron_rescan_rescan_2016-04-01_10-30-01.txt)
[cron_rescan_serpil_2016-04-01_08-15-01.txt](https://github.com/owncloud/core/files/199251/cron_rescan_serpil_2016-04-01_08-15-01.txt)
[cron_rescan_serpil_2016-04-01_10-15-01.txt](https://github.com/owncloud/core/files/199250/cron_rescan_serpil_2016-04-01_10-15-01.txt)

**Comment by Kaelber** [comment]
Now, after testing the v9 RC-2 the result is the same: on Synology´s with 

- DSM 5.2 | rescan runs and logs are storing, but no file update is running from server to client.
- DSM 6 | no rescan runs, no logs are stored, no file update is running from server to client.
- both DSM´s | updates from client to server are running.

**Comment by PVince81** [comment]
For those with etag propagation / update detection issues with "files:scan", GOTO https://github.com/owncloud/core/issues/24255

Let's keep this ticket here for the memory errors only.

**Comment by butonic** [comment]
@MorrisJobke the query logger seems to be active in https://blackfire.io/profiles/d0dd4ef7-281a-47b7-9431-46ce7f785d5a/graph It will store ALL queries in RAM, which might explain some of the growth you are seeing.

**Comment by MorrisJobke** [comment]
I will try this with the php-memory-profiler that was proposed by @butonic https://github.com/arnaud-lb/php-memory-profiler

**Comment by MorrisJobke** [comment]
It seems to be the `markAcquire` method, that holds a local attribute, that gets filled:

![bildschirmfoto 2016-05-02 um 10 00 26](https://cloud.githubusercontent.com/assets/245432/14949793/0461c544-104d-11e6-8aab-da5102cef24c.png)
![bildschirmfoto 2016-05-02 um 10 00 36](https://cloud.githubusercontent.com/assets/245432/14949799/0e5559b2-104d-11e6-85a3-ae853b8fc80b.png)
![bildschirmfoto 2016-05-02 um 10 01 30](https://cloud.githubusercontent.com/assets/245432/14949800/11bb97ec-104d-11e6-8722-734b6eb79f85.png)


@icewind1991 For what is this even needed? The state is stored in the DB/Memcache nevertheless, or am I wrong?

**Comment by icewind1991** [comment]
> For what is this even needed? The state is stored in the DB/Memcache nevertheless, or am I wrong?

It's needed for performance optimizations for the db based locking

https://github.com/owncloud/core/pull/24387 will free up the memory once the last shared lock is removed

**Comment by Kaelber** [comment]
Update :

with oc 9.0.2 RC-2 and oc_9.1.0 pAlp-1 and Client 2.2.0 Beta 2 the same situation :

Synology DS414 mit DSM 5.2 | ? : rescan runs and logs are storing, but no file update is running from server to client.
Synology DS712+ mit DSM 6 | ? : rescan runs and logs are storing, but no file update is running from server to client.

Regarding the filescan I got from the Logfile as follow :

With oc 9.0.1 (not 9.1.0)

Starting scan for user 1 out of 1 (rescan)

+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 12706 | 52211 | 01:04:55 |
+---------+-------+--------------+

----- End ----------

with oc 9.0.2 RC-2

Starting scan for user 1 out of 1 (rescan)

----- End ----------

**Comment by Kaelber** [comment]
Update :

with oc 9.0.2 and oc_9.1.0 pAlp-1 and Client 2.2.0 the follow situation :

Synology DS414 mit DSM 5.2 | ? : rescan runs and logs are storing, file only updateing, if I use --all in the scan command. If I use a user in the command, no update is done.

Synology DS712+ mit DSM 6 | ? : rescan runs and logs are storing, but no file update is running from server to client, also not with --all in the scan command

Regarding the filescan I got from the Logfile as follow :

With oc 9.1.0 preAlpha and DS414 mit DSM 5.2

Scanning files for 4 users
Starting scan for user 1 out of 4 (admin)
Starting scan for user 2 out of 4 (kaelber)
Starting scan for user 3 out of 4 (rescan)
Starting scan for user 4 out of 4 (kaelber2)

+---------+--------+--------------+
| Folders | Files  | Elapsed time |
+---------+--------+--------------+
| 47127   | 200633 | 02:23:05     |
+---------+--------+--------------+


----- End ----------


With oc 9.0.2 and DS712+ mit DSM 6

Scanning files for 4 users
Starting scan for user 1 out of 4 (admin)
Starting scan for user 2 out of 4 (kaelber)
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 77 bytes) in /volume1/web/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 128

----- End ----------

**Comment by Kaelber** [comment]
Update :

with oc 9.1.0 Beta 1 and Client 2.2.0 the follow situation :

Synology DS414 mit DSM 5.2 | ? : scan runs and logs are storing, file only updating, **if I use --all** in the scan command. A **USER** in the command is **NOT RUNNING**, no update is done.

Synology DS712+ mit DSM 6 | ? : rescan runs and logs are storing, but no file update is running from server to client, **also not with --all in the scan command**

Regarding the filescan I got from the Logfile as follow :

**Synology DS414 with DSM 5.2**

Scanning files for 4 users
Starting scan for user 1 out of 4 (admin)
Starting scan for user 2 out of 4 (kaelber)
Starting scan for user 3 out of 4 (rescan)
Starting scan for user 4 out of 4 (kaelber2)

+---------+--------+--------------+
| Folders | Files  | Elapsed time |
+---------+--------+--------------+
| 54235   | 238428 | 03:05:59     |
+---------+--------+--------------+

**----- End ----------

Synology DS712+ with DSM 6**

Scanning files for 4 users
Starting scan for user 1 out of 4 (admin)
Starting scan for user 2 out of 4 (kaelber)

**----- End ----------**

**Comment by Kaelber** [comment]
Issue is NOT closed

**Comment by PVince81** [comment]
@Kaelber can you elaborate on your last post ? You are saying that scan didn't work or didn't trigger a sync. But the first question is whether you are still seeing the "Allowed memory size" issues during the scan ?

I'd expect 9.1.0 beta1 (or beta2) to not have these issues any more.
There are more fixes incoming that could reduce memory usage for shares, but as you seem to have only 4 users it is unlikely to help, unless these users have thousands of shares.

**Comment by Kaelber** [comment]
In this moment further tests are needed, I come back with news. Thanks.

**Comment by PVince81** [comment]
9.0.3 RC1 is out. There are fixed for memory usage that were backported there, so you might want to test with that version.

**Comment by Kaelber** [comment]
In this moment is running on different Synology machines in a good condition. Doe you have the same engine in 9.1.0 beta 2 ?

**Comment by Kaelber** [comment]
It seems, I doesn´t need the command "occ files:scan --all", right?

**Comment by Kaelber** [comment]
I can confirm, that currently the scan engine of oc 9.0.3 RC-1 more or less runs in a condition like oc 8.2.5 - very good !
