### ISSUE TITLE
Ubuntu/Debian packages: Add conflict to libapache2-mod-php5filter

### ISSUE THREAD

**Issue by ghost** [owncloud/core#23015]
libapache2-mod-php5filter is known to block certain WebDAV/HTTP Verbs and causing various other issues like seen in the past:

https://github.com/owncloud/core/issues/9395, https://github.com/owncloud/core/issues/8536, https://github.com/owncloud/core/issues/2495, https://github.com/owncloud/core/issues/510

Today we had another user at IRC which had installed this package. It would make sense to add a conflict or similar to the ownCloud packages so that people are forced to install libapache2-mod-php5 instead to avoid such issues.

**Comment by nickvergessen** [comment]
@LukasReschke ?

**Comment by LukasReschke** [comment]
@jnweiger

**Comment by crrodriguez** [comment]
Already fixed

**Comment by kdslkdsaldsal** [comment]
This wasn't fixed so created https://github.com/owncloud/administration/pull/133 to address this issue
